### ISSUE TITLE
Index signature & iterators

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#2862]
```
interface Files {
	[key: number]: SomeFile
	length: number
}
var data: Files = []
// no complaints
for (var i in data) {
}

// Type 'Files' is not an array type or a string type
for (let file of data) {
}
```
I'm not sure what is the right move here. Files has an index but that doesn't mean it's iterable/enumerable. Think the check should just be removed.

**Comment by jbondc** [comment]
Or keep the check and but 'Iterable' to lib.d.ts
```
interface Files extends Iterable {
    [key: number]: SomeFile
    length: number
}
interface Files2 {
    [System.iterator]() : Iterator;
    [key: number]: SomeFile
    length: number
}
```

**Comment by JsonFreeman** [comment]
This code is reasonable in ES5, but in ES6 you would have to declare it Iterable (which I think you allude to later). I would be fine with ES5 type check allowing iteration on ArrayLike things (types with a numeric indexer and a length). This could only be allowed for ES5 though, not ES3 or ES6.

**Comment by RyanCavanaugh** [comment]
> This could only be allowed for ES5 though, not ES3 or ES6.

:fearful:

**Comment by jbondc** [comment]
@JsonFreeman Don't have a good grasp on iterators, I'd expect this to work in ES5 (both currently errors):
```
// (a)
var r: {};
for (let j of r) {
}
// (b)
interface b { }
var r: b;
for (let j of r) {
}
```
I think (b) would fail in ES6 because the interface b is not Iterable?

**Comment by JsonFreeman** [comment]
@jbondc, those cannot work in ES5 because the downlevel emit for ES5 depends on the object having a length and an indexer. Since neither a length nor an indexer is present in `r` or `b`, it has to be an error.

**Comment by mhegazy** [comment]
one issue to keep in mind that strings cannot be treated as an array if it has surrogate pairs. e.g.: `
```ts
"𠮷".lenthg === 2;
for(var i of "𠮷) {
    charCount ++;
}
charCount === 1;
```

**Comment by JsonFreeman** [comment]
Oh yeah, so in effect, it is not even correct to allow strings in ES5

**Comment by JsonFreeman** [comment]
Actually, does ES5 even have surrogate pairs? Do they even support characters that involve surrogate pairs?

**Comment by mhegazy** [comment]
> Actually, does ES5 even have surrogate pairs? Do they even support characters that involve surrogate pairs?

There is nothing wrong with surrogate pairs, the issue is when you iterate on them.

> Oh yeah, so in effect, it is not even correct to allow strings in ES5

We can not get the correct semantics 100% of the time without a helper function that can understand surrogate pairs. I do not know if that means we should/should not consider enabling strings though.

**Comment by JsonFreeman** [comment]
I think we can still support iterating over strings. Surrogate pairs are a pretty marginal case.

**Comment by mhegazy** [comment]
i agree :)

**Comment by jbondc** [comment]
ES5 type check allowing iteration on ArrayLike things (types with a numeric indexer and a length) sounds good.

Can that be forward compatible with ES6? Seems like if something has that structure, could we emit the ArrayLikeIterator?

**Comment by jbondc** [comment]
Bah tried this:
```
const ArrayLikeIterator = function(arrayLike) {
    var _index = 0;
    return {
       next: function(){
           return _index < arrayLike.length ?
               {value: arrayLike[_index++], done: false} :
               {done: true};
       }
    }
}
var r = {0: "a", 1: "b", length: 4};
for (let j of ArrayLikeIterator(r)) {

}
// Firefox says: TypeError: r[Symbol.iterator](...) is undefined
```
Any ideas?

**Comment by jbondc** [comment]
Anyways, give up but would be nice if it could work. It does means more helper functions which is either good or bad.
```
const MakeArrayLikeIterable = function(arrayLike) {
  arrayLike[Symbol.iterator] = arrayLike[Symbol.iterator] ||  ArrayLikeIterator(arrayLike);
  return arrayLike;
}

var r = {0: "a", 1: "b", length: 2};
var __r = MakeArrayLikeIterable(r);
for (var j of __r) {

}
```

**Comment by jbondc** [comment]
Round #3:
```
   for (let x of Array.from(arrayLike)) { 

    }
```
Mentioned here:
http://www.2ality.com/2015/02/es6-iteration.html

**Comment by JsonFreeman** [comment]
Your second and third examples compile in TypeScript when target is ES6. But they will not compile in ES5 because neither Symbol nor Array.from is defined in ES5. This is an accurate representation of the runtime behavior.

**Comment by jbondc** [comment]
Sorry I wasn't clear what I meant:
```
interface Files {
    [key: number]: string
    length: number
}
var data: Files;
for (let file of data) { // no error
}
```
Currently its an error in both ES5:
c.ts(7,18): error TS2461: Type 'Files' is not an array type or a string type.
Or ES6:
c.ts(7,18): error TS2488: The right-hand side of a 'for...of' statement must have a '[Symbol.iterator]()';
```
Would like to allow the ES5 emit:
```
for (var _i = 0; _i < data.length; _i++) {
    var file = data[_i];
}
```
And the ES6 emit (which wraps the ArrayLike symbol):
```
for (let file of Array.from(data)) {
}
```

**Comment by JsonFreeman** [comment]
Oh I see what you mean now. If data, were iterable in ES6, we would emit:
```ts
for (let file of data) { }
```
But if it is only ArrayLike, we would emit
```ts
for (let file of Array.from(data)) { }
```
However, this violates a key principle of TypeScript emit, which is that we do not change emit based on type information. The reason is that the view of the types in your program is not perfect, and it is merely descriptive, a glimpse of what will happen at runtime. But it is intended to be used as a guide to the user, and should not impact the behavior of your program.

**Comment by jbondc** [comment]
Like that principle but in this case pragmatism should overrule:
https://github.com/borisyankov/DefinitelyTyped/blob/master/underscore/underscore.d.ts#L59
https://github.com/borisyankov/DefinitelyTyped/blob/master/touch-events/touch-events.d.ts#L16
https://github.com/borisyankov/DefinitelyTyped/blob/master/react/react.d.ts#L759

A ```for(value of arrayLike)``` of that structure should be 'iterable' IMHO.

**Comment by SaschaNaz** [comment]
Can we implement WebIDL-style `iterable` keyword to enable this?
```
interface NodeList iterable<Node> {
}
```

... which in ES6 will be same with:
```typescript
interface NodeList {
    [Symbol.iterator](): IterableIterator<Node>
}
```

... while still allowing for-of loop in ES5.

**Comment by jbondc** [comment]
@SaschaNaz You'd still have a type directed emit that changes code. Comes back to the same if you map ES5:
```
// (a)
interface NodeList {
    [key: number]: Node
    length: number
}
```
Into ES6
```
interface NodeList {
    [Symbol.iterator](): IterableIterator<Node>
}
```
It's not really a syntax issue. Prefer (a) because it's one less thing I have to learn.

**Comment by SaschaNaz** [comment]
@jbondc My thought is we may add an internal flag for `iterable` interfaces in ES5 while not changing emit.

```typescript
for (let node of document.querySelectorAll(".foo .bar")) {} // allowed

let nodeList: NodeList;
nodeList = document.querySelectorAll(".baz"); // okay
nodeList = <{ [key: string]: Node; length: number }>{}; // no `iterable` flag, not allowed.
```

**Comment by SaschaNaz** [comment]
Your first example with `iterable` flag will be: 

```
interface Files iterable<SomeFile> {
    [key: number]: SomeFile;
    length: number;
}
var data: Files = [] // okay, as arrays are iterable
```

**Comment by jbondc** [comment]
This works nicely:
```
interface Files {
    [key: number]: string
    length: number
}
var data: Files;
for (let file of data as string[]) { // no error
```
The ```as``` cast basically forces the use of the iterator for the type ```string[]```.

It also solves the issue of iterating over strings.
```
let someUnicode = "\uD83D\uDCA9";
for (let char of data as unicode[]) { // no error, uses iterator of new primitive unicode
}
```
https://mathiasbynens.be/notes/javascript-unicode
