### ISSUE TITLE
Unable to install typescript version 1.4.0.0

### ISSUE THREAD

**Issue by mt406** [Microsoft/TypeScript#2863]
Unable to install typescript version 1.4.0.0 .

It always gives error "acess denied" when I try to install it .

Note : I have admin rights and this error comes always even I have installed VS 2013 update 3 and then tried to install TS 1.4.0.0

I have formatted my machine and installed  vs 2013 update 3 then tried to install  typescript version 1.4.0.0 but still facing same "access denied , setup failed " error.

Please help me on this ..

**Comment by mhegazy** [comment]
pinging @paulvanbrenk.

**Comment by paulvanbrenk** [comment]
where do you get the access denied error? Can you share the setup logs files somewhere?

**Comment by mhegazy** [comment]
@mt406 can you give [TypeScript 1.5-beta](https://github.com/Microsoft/TypeScript/releases/tag/v1.5.0-beta) a try?

**Comment by mhegazy** [comment]
@mt406 please reopen if you are still running into issues.
