### ISSUE TITLE
JSX element type does not have any construct or call signatures in v3.2.0-rc

### ISSUE THREAD

**Issue by rexpan** [Microsoft/TypeScript#28631]
**TypeScript Version:**  3.2.0-rc, 3.2.1

**Code**

```tsx
import * as React from "react";
import { Component, ReactType} from "react";
function App(props:{component:ReactType}) {
  const Comp: ReactType = props.component
  return (<Comp />)
}
```

**Expected behavior:**
Should output normal as TypeScript 3.1.6

**Actual behavior:**
`TS2604: JSX element type 'Comp' does not have any construct or call signatures.`

**Comment by rexpan** [comment]
@Kovensky

I have make sure using the latest `@types/react 16.7.7` and no duplicates `@types/react` in `yarn.lock`.
If the issue is because of duplication of `@types/react`, it will return the error `Duplication of definition ...`.

I revert back to `"typescript": "^3.1.6"` then it work normally.

**Comment by goloveychuk** [comment]
Typescript 3.2.1

other example
```ts

interface P1 {
  p?: boolean
  c?: string
}

interface P2 {
  p?: boolean
  c?: any // if you replace c with string, error goes away
  d?: any
}

declare var C: React.ComponentType<P1> | React.ComponentType<P2>


const a = <C p={true} /> // element does not have any ...
```

It looks like, the problem is related to new "nullable discriminants" changes. Looks like ts can't find common interface for those types.
Other example
```ts
interface P1 {
  p?: any
  c?: string // remove this and it's ok
}

interface P2 {
  p?: boolean
}
```

**Comment by layershifter** [comment]
We have a similar problem, quick example:

```tsx
import * as React from 'react'

//
// Types
//

interface Config<P> {
  ElementType: React.ReactType<P>
}

interface EmptyProps {
}

interface Props {
  a?: string
}

type HProps = {
  configEmpty: Config<EmptyProps>,
  config: Config<Props>
}

//
// Component
//

const H: React.FC<HProps> = ({ config, configEmpty }) => {
  const A: React.ReactType<EmptyProps> = configEmpty.ElementType // assigned
  const B: React.ReactType<EmptyProps> = 'div' // assigned

  const C: React.ReactType<Props> = config.ElementType // assigned
  const D: React.ReactType<Props> = 'div' // in this case assignment failed

  return (
    <div>
      <A/> {/* TS2604: JSX element type 'A' does not have any construct or call signatures. */}
      <B/>

      <C/>
      <D/>
    </div>
  )
}

export default H
```

I see this behaviour as completely invalid, because `A` and `B` have the **same types**.
Code in repo: https://github.com/layershifter/ts-issue

**Comment by Kovensky** [comment]
They do not, because you're using `const`. The type of `A` is `typeof configEmpty.ElementType`, but the type of `B` is `'div'`. Using `let`s will show the same behavior on both.

**Comment by layershifter** [comment]
@Kovensky what about `A` and `C`? Why `C` works while `A` fails with `does not have any construct` error?

**Comment by azizhk** [comment]
I would probably say @rexpan and @goloveychuk's error is similar to #28795 and #28768 based on conditional JSX constructor.

**Comment by weswigham** [comment]
Hm, so the issue is that `ReactType<any>` returns a union of _every builtin jsx tag_ (plus `ComponentType<any>`, but that part's not problematic), and the signatures for those components do not trivially simplify (there is not a signature that perfectly encompasses all the others). This, too, relies on #7294 to be fixed. On the plus side, the underlying change needed to fix for all these JSX issues that get reported is the same.

For context, we effectively manufacture a type like this:
```ts
declare const JsxSigs: {[K in keyof JSX.IntrinsicElements]: ((props: JSX.IntrinsicElements[K]) => JSX.Element)}[keyof JSX.IntrinsicElements];
```
which ends up as being a union of a ton of unique signatures.

**Comment by Kovensky** [comment]
Before I changed it to be a union of all builtin jsx tags it was _just_ `string`, which was even worse.

**Comment by weswigham** [comment]
Aye, especially since prior to 3.2, a `string` type in a tag just quietly _disabled_ typechecker, because the "index not found" error it was supposed to issue never occurred.

**Comment by woutervanvliet** [comment]
Running into a problem that might be related. I have the following component:

```typescript
function MaybeLabel(props: { useLabel: boolean }) {
   const { useLabel } = props;
   const TagName = useLabel ? 'label' : 'div';

   return <TagName>Woookie</TagName>
}
```
which results in

`error TS2604: JSX element type 'TagName' does `not` have any construct or call signatures.`

while

```typescript
function MaybeLabel2(props: { useLabel: boolean }) {
   const { useLabel } = props;
   const TagName = useLabel ? 'span' : 'div';

   return <TagName>Woookie</TagName>
}
```

is completely acceptable to the typescript compiler. As is:

```typescript
export function MaybeLabel3(props: { useLabel: boolean }) {
	const { useLabel } = props;
	const TagName = useLabel ? 'label' : 'div';
	
	return React.createElement(TagName, 'Wookie')
}
```

Where the only difference in `MaybeLabel2` is that I'm using `span` instead of `label` (using `span` instead of `div` also seems acceptable). `MaybeLabel3` makes it even stranger, as that should be exactly what `MaybeLabel` compiles to.

Using latest version of @types/react and @types/react-dom, and verified the problem in typescript 3.2.1, 3.2.2 and 3.3.0-dev.20181219. In 3.1.6 it all works as expected (none of the examples produce errors)

**Comment by TacB0sS** [comment]
for me the solution was:

```
export type WrapperProps = {
	mainApp: React.ElementType
}

```

**Comment by hegelstad** [comment]
@TacB0sS please elaborate.

**Comment by TacB0sS** [comment]
I might have misunderstood the thread, but I wanted to pass a reference to an jsx Element to another jsx element:

```tsx
export const AppWrapper = hot(module)((props: WrapperProps) => {

	const MainApp = props.mainApp;
	if (!MainApp)  // <-- JSX elements MUST start with upper case!!
		throw new ImplementationMissingException("mainApp was not specified!!");

	return (
		<Router history={BrowserHistoryModule.getHistory()}>
			<MainApp prop1={"value"}/>
		</Router>)
});
``` 

Together with:

```tsx
export type WrapperProps = {
	mainApp: React.ElementType<{prop1:string}>
}
```

**Comment by orest22** [comment]
@TacB0sS For me the main trick was adding `if` condition. Looks like it doesn't matter whether you use `React.ComponentType` or  `React.ElementType`

**Comment by ericmasiello** [comment]
I'm not sure i understand the outcome of this. I have a similar error that I have not been able to resolve. Here is my use case:

```
// Logo.tsx

import classNames from 'classnames';

interface Props extends React.HTMLAttributes<HTMLElement> {
  tag?: React.ReactType;
}

const Logo: React.SFC<Props> = props => {
  const { tag: Tag = 'div', className, ...rest } = props;
  return (
    <Tag
      className={classNames(styles.logo, className)}
      {...rest}
      dangerouslySetInnerHTML={{ __html: logo }}
    />
  );
};
```

and then I'm using it like such in another component like so:

```
const Header: React.SFC<{}> = () => {
  return (
    <div>
      <Logo tag="h1" aria-label="Syn By Design: Eric Masiello's Portfolio" />
      Header online
    </div>
  );
};
```

When I run the compiler, i get this error:

```
components/Logo.tsx:13:6 - error TS2604: JSX element type 'Tag' does not have any construct or call signatures.

13     <Tag
        ~~~


Found 1 error.
```

Any ideas how to make this work?

**Comment by pinkbunny1** [comment]
Instead of `Component`, use `ComponentClass`

**Comment by styk-tv** [comment]
ComponentClass no go...

<img width="427" alt="Screenshot 2019-12-06 at 13 52 47" src="https://user-images.githubusercontent.com/838921/70327930-cbcd9980-182f-11ea-9796-7e64566078ba.png">

**Comment by jedwards1211** [comment]
I got this error because I imported default but forgot to declare the corresponding default export in a `.d.ts` file...confused me for awhile

**Comment by SARCASMOOO** [comment]
Just wanted to add this here. Not sure if this was already said but if you are doing a hirer order component you want to use the type React.ComponentType<P>. "https://flow.org/en/docs/react/types/#toc-react-componenttype"

**Comment by hellatan** [comment]
@ericmasiello I ended up using `React.ElementType` for a dynamically passed in component. My use case is basically the following:
```ts
type Props = {
    heading: React.ElementType
}
const Header: FC<Props> = props => {
    const Header = props.heading ?? 'h2';
    return (
        <Header className="some-class"><children /></Header>
    )
}
```

**Comment by ericmasiello** [comment]
> @ericmasiello I ended up using `React.ElementType` for a dynamically passed in component. My use case is basically the following:
> 
> ```ts
> 
> type Props = {
> 
>     heading: React.ElementType
> 
> }
> 
> const Header: FC<Props> = props => {
> 
>     const Header = props.heading ?? 'h2';
> 
>     return (
> 
>         <Header className="some-class"><children /></Header>
> 
>     )
> 
> }
> 
> ```

Cool! What version of Typescript and what version of @types/react do you have installed?

**Comment by hellatan** [comment]
@ericmasiello 

> Cool! What version of Typescript and what version of @types/react do you have installed?

TypeScript@3.9.7
@types/react@16.9.49

**Comment by LuisDev99** [comment]
I solved this problem by doing any of these two things:

### Case 1:

.d.ts file:
```ts
declare module "foo" {
   interface PropFoo {
      propy: string;
   }

   class MyTypedComponent extends React.Component<PropFoo> { }
}
```

React:

```tsx
import MyTypedComponent from "foo";

function AnotherComponent() {

   /* Notice in here we have to use the dot operator and reference the component */
   return <MyTypedComponent.MyTypedComponent /> 
}
```

Notice that, in order to use the newly typed component, we have to write _MyTypedComponent.MyTypedComponent_ . This may be obvious to some people, but I wasted alot of time when all I had to do was to use the dot operator on the import and reference the component.


### Case 2 [just another way of writing Case 1]:

.d.ts file:
```ts
declare module "foo" {
   interface PropFoo {
      propy: string;
   }

   export default class MyTypedComponent extends React.Component<PropFoo> { } //Notice the export default in here
}
```

React:

```tsx
import MyTypedComponent from "foo";

function AnotherComponent() {

   /* Since this component is default exported, no need to use the dot operator */
   return <MyTypedComponent /> 
}
```

Soo, basically, check your exports, default exports, and imports and make sure you are referencing correctly.

I'm very sorry for my English and I hope this helps.

**Comment by zhuxchong** [comment]
> for me the solution was:
> 
> ```
> export type WrapperProps = {
> 	mainApp: React.ElementType
> }
> ```

niu b

**Comment by nklaasse** [comment]
Give it a try;

```
import { ReactElement } from 'react';

export interface Example = {
 component: ReactElement;
} 
```

**Comment by mancoxu** [comment]
> > for me the solution was:
> > ```
> > export type WrapperProps = {
> > 	mainApp: React.ElementType
> > }
> > ```
> 
> niu b

ni zhe hui da ye nb haha

**Comment by d-zer** [comment]
```
import React, { useEffect, useState } from 'react';
import './App.css';
import axios from 'axios';
import { Header } from 'semantic-ui-react';

function App() {

  return (
    <div className="App">
      <Header as='h2' icon='users' content='Reactivities' />
      <header className="App-header"></header>
    </div>
  );
}
```
When I write this code i get "JSX element type 'Header' does not have any construct or call signatures.ts(2604)" error.
