### ISSUE TITLE
TSServer doesn't pickup the addition of a tsconfig.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#2864]
I've converted a project to use the tsconfig.json support.
After adding the tsconfig.json I had to restart the TSServer to pick up the addition of the tsconfig.json file.

**Comment by mhegazy** [comment]
We do not currently add a file watcher for missed tsconfig searches. this would be handy though.

**Comment by mhegazy** [comment]
this should be fixed now.
