### ISSUE TITLE
Mapped generic conditional type does not narrow properly

### ISSUE THREAD

**Issue by nomcopter** [Microsoft/TypeScript#28641]
**TypeScript Version:**  typescript@3.3.0-dev.20181121

**Search Terms:** Conditional Mapped Types Generic Type Parameter Narrow Distributive

**Code**

```ts
interface Foo {
    bar: number;
}

interface HasFoos {
    a: Foo;
    b: Foo;
    c: string;
}

type FooPropertyNames<T> = { [K in keyof T]: T[K] extends Foo ? K : never } [keyof T];

function good<K extends FooPropertyNames<HasFoos>>(t: HasFoos, key: K) {
    return t[key].bar;
}

// Should still work
function fails<T, K extends FooPropertyNames<T>>(t: T, key: K) {
    return t[key].bar;
}
```

**Expected behavior:**

It should all compile and `t[key]` should narrow properly.

**Actual behavior:**

`t[key]` does not narrow beyond `T[K]`.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0A%20%20%20%20bar%3A%20number%3B%0A%7D%0A%0Ainterface%20HasFoos%20%7B%0A%20%20%20%20a%3A%20Foo%3B%0A%20%20%20%20b%3A%20Foo%3B%0A%20%20%20%20c%3A%20string%3B%0A%7D%0A%0Atype%20FooPropertyNames%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20Foo%20%3F%20K%20%3A%20never%20%7D%20%5Bkeyof%20T%5D%3B%0A%0A%0Afunction%20good%3CK%20extends%20FooPropertyNames%3CHasFoos%3E%3E(t%3A%20HasFoos%2C%20key%3A%20K)%20%7B%0A%20%20%20%20return%20t%5Bkey%5D.bar%3B%0A%7D%0A%0A%2F%2F%20Should%20still%20work%0Afunction%20fails%3CT%2C%20K%20extends%20FooPropertyNames%3CT%3E%3E(t%3A%20T%2C%20key%3A%20K)%20%7B%0A%20%20%20%20return%20t%5Bkey%5D.bar%3B%0A%7D%0A

**Related Issues:** #23207

**Comment by ahejlsberg** [comment]
This is working as intended. For the type variable `K` we track that it is some subset of `keyof T`, but we do not track _which_ subset and what implications that would have for `T[K]`. I don't think it is feasible to change this.

**Comment by Kovensky** [comment]
Rather, it seems generics cannot narrow at all, not even with typeof or equality checks; only assertions.

**Comment by nomcopter** [comment]
That's unfortunate, and greatly reduces the usefulness of `PropertyNamesOfType<T>` for me. Hopefully it becomes feasible in the future! Thanks.
