### ISSUE TITLE
Create tsbuild public API and use incremental build in tsbuild --watch mode

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/TypeScript#28640]
- [ ] Use incremental build in tsbuild --watch mode
- [ ] Actual host apis for build with and without watch mapping to corresponding program
- [ ] Move caching login #28629 to creation of host for tsbuild (without watch mode instead and have another function that createCompilerHostWithCaching instead.)
- [ ] From #29161 We do not cache source files yet and that's something to be looked at later.
Two things can be done: 
 - To keep source files for program thats being updated in last few cycles
 - To release the source files if size exceeds or program is not used for few build cycles
 - CompilerHost and Likes api to be better once this is shaped up

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ajafff** [comment]
- [ ] create a new CompilerHost for each project so it knows the correct compilerOptions for that project (from discussion in https://github.com/Microsoft/TypeScript/pull/27560#discussion_r224996878)

**Comment by maclockard** [comment]
Just curious, are the any updates here? Clicking through some of the links in the initial issue it looks like this might be close?

**Comment by kirillonufreinko** [comment]
Is this issue resolved or planned to be resolved in certain release?

**Comment by sheetalkamat** [comment]
#31432 is up for this

**Comment by sheetalkamat** [comment]
Closed by #31432
