### ISSUE TITLE
Duplicate identifier error when assigning to class property if there is a method with same name

### ISSUE THREAD

**Issue by gnaeus** [Microsoft/TypeScript#28649]
**TypeScript Version:** 
typescript@3.3.0-dev.20181122

**Search Terms:**
duplicate identifier; class property; jsdoc; salsa

**Code**
We are using TypeScript with `--allowJs` flag:
```js
// @ts-check
export class Test {
  doSomething = this.doSomething.bind(this);
  doSomething() {}
}
```

**Expected behavior:**
No errors. [Babel](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqCmEAu0DeAoa0AmB7AyrgLbxIAWAlgHYDm0AvNORRAHR6EnO2sBG12ABTMIASgDcmHAWKlKtQaLQBfdMqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2&prettier=false&targets=&version=6.26.0&envVersion=) and [Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2AFQFMcAXMAb1TDABM4BlOAWyNIAsBLAOwHMwAvGA6ccAOnpNWIvmIBGPWgAoROAJQBuanUYs2XPkrWUAvqjNA) compile this code without errors.

**Actual behavior:**
`[ts] Duplicate identifier 'doSomething'. [2300]`

**Playground Link:** [link](http://www.typescriptlang.org/play/#src=class%20Test%20%7B%0D%0A%20%20doSomething%20%3D%20this.doSomething.bind(this)%3B%0D%0A%20%20doSomething()%20%7B%7D%0D%0A%7D)

**Comment by kitsonk** [comment]
While that is actually valid code, it is horribly unsound.  There are whole groups of code that aren't valid when type checked but are valid at runtime.  This is one of them.  It is also subjective at runtime, since [classes do not yet support instance class fields](https://github.com/tc39/proposal-class-fields).  I doubt TypeScript should ever consider this valid.

This works and has exactly the proper runtime behaviour:

```js
export class Test {
  constructor() {
    this.doSomething = this.doSomething.bind(this);
  }
  doSomething() {}
}
```

**Comment by weswigham** [comment]
We don't allow replacing methods with instance properties in general; however as @kitsonk points out, we relax that in the constructor.
