### ISSUE TITLE
TS2512: Overload signatures must all be abstract or non-abstract.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#28659]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
export interface IRNG
{
	internal_unif_rand(): number;
}

export abstract class IRNG
{
	abstract internal_unif_rand(): number;
}
```

**Expected behavior:**

> no error

**Actual behavior:**

> TS2512: Overload signatures must all be abstract or non-abstract.

**Playground Link:** 

**Related Issues:**

**Comment by weswigham** [comment]
I have mixed feelings here - the interface being merged with the class pretty much makes the definition within the class redundant; however the interface can't convey the `must-be-implememted-ness` of the signature. Thus, My advice would be to remove the signature from the interface, if possible.
