### ISSUE TITLE
direct index array access is not typesafe

### ISSUE THREAD

**Issue by prmichaelsen** [Microsoft/TypeScript#28650]
**Note** Duplicate of closed issue: https://github.com/Microsoft/TypeScript/issues/13778 
However, after reading the discussion there, I still believe it warrants discussion. I  more or less echo the sentiment expressed by @OliverJAsh in this [comment](https://github.com/Microsoft/TypeScript/issues/13778#issuecomment-406316164).

**TypeScript Version:**    typescript@3.3.0-dev.20181122

**Search Terms**
array access string number undefined

**Code**
index.ts
```ts
{
	const test: string[] = [];
	// expected [ts] error:
	// Type 'string | undefined' is not assignable to type 'string'.
	// Type 'undefined' is not assignable to type 'string'. [2322]
	const result: string = test[0];
}

{
       // here is an imagined case where we want the 
       // first result of a server response. Typescript 
       // tells us we can use our result however we wish.
	const response: () => string[] = () => [];
	const test = response();
	// expected [ts] error:
	// Type 'string | undefined' is not assignable to type 'string'.
	// Type 'undefined' is not assignable to type 'string'. [2322]
	const result: string = test[0];
}

```
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true
  }
}
```

**Expected behavior:**
```ts
	// Type 'string | undefined' is not assignable to type 'string'.
	// Type 'undefined' is not assignable to type 'string'. [2322]
```
**Actual behavior:**
No error on assignment of `undefined | string` to `string`

**Playground Link:** 
I will create a playground shortly, for now, here is the entire issue in a github repo: https://github.com/prmichaelsen/ts-array-access

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/13778 

**Note**
I understand there is a closed issue on this topic, but I believe that it is popular enough a request to warrant discussion. Here is my case.

The primary concern seems to be breaking existing for-loops where the index is clearly assigned. However, instead of:
```ts
const array = [1, 2, 3];
for (var i =0; i< array.length; i++) {
    array[i]+=1; // array[i] is possibly undefined
}
```
You can write:
```ts
const array = [1, 2, 3];
const result = array.map(value => value + 1);
// which is arguably an increasingly common way 
// of doing things, anyway
```
Then, when doing random index accesses, you are required to check if the result is undefined, but not while iterating an enumerated collection.

So:
```ts
const array = [1, 2, 3];
// good
const result = array.map(value => value + 1);
// or for in-place manipulation
array.forEach((value, i) => array[i] = value + 1);

// bad
for (var i =0; i< array.length; i++) {
    array[i]+=1; // array[i] is possibly undefined
}

// errors, which is good
const result: number = array[50]; // array[50] is possibly undefined
```

Please let me know what you think.

**Comment by yawaramin** [comment]
I suggest closing this since #13778 is now open.
