### ISSUE TITLE
Type 'IRNG' is not assignable to type 'R'.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#28652]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
export class RandomRngWithLibRmath<R extends libRmath.IRNG> extends RNG
{
	protected _rng: R;
	protected _seedable: boolean = true;

	protected _init(seed?, opts?, ...argv)
	{
		if (seed instanceof libRmath.IRNG)
		{
			this._rng = seed // Error:(83, 4) TS2322: Type 'IRNG' is not assignable to type 'R'.
		}
	}
}
```

**Expected behavior:**

no error

**Actual behavior:**

> Error:(83, 4) TS2322: Type 'IRNG' is not assignable to type 'R'.

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment]
Every `R` is a `IRNG`, but not every `IRNG` is a `R`. The behaviour of the compiler is as expected.

**Comment by bluelovers** [comment]
so what is correct way do in typescript?

**Comment by weswigham** [comment]
Annotate argument types on `protected _init(seed?, opts?, ...argv)` - `seed` specifically - so the instanceof check narrows to `R` rather than the concrete subtype of R.
