### ISSUE TITLE
.ts file not compiled if contins module import with outFile

### ISSUE THREAD

**Issue by danielsedlacek** [microsoft/TypeScript#28657]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**
outFile, module

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
[Archive.zip](https://github.com/Microsoft/TypeScript/files/2611245/Archive.zip)
When a main.ts file contains a module import statement form modules.ts file, and outFile is defined in tsconfig.json, then neither the main.ts file nor the module will be outputted to a single file. 

If other .ts files are in the source folder, these will be compiled to the outFile. 

If outFile is not defined, both main.ts and the modules.ts will be compiled to separate files. 

If the main.ts does not contain the module import, it is compiled correctly.

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by danielsedlacek** [comment]
I just tested it using 3.2.rc and the compiler throws Error:(1, 14) TS6131: Cannot compile modules using option 'outFile' unless the '--module' flag is 'amd' or 'system'.

You should really update the documentation on the outFile flag.

**Comment by RyanCavanaugh** [comment]
Not sure what's wrong about what here; `outFile` has been clear about its restrictions since forever.
