### ISSUE TITLE
true extends false

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#28654]
**TypeScript Version:**  3.2.0-dev.20181117

EDIT: I just tested with TS 3.2.0-rc and it has this bug

**Search Terms:** true extends false

**Code**

I feel like I'm losing my mind here. Or maybe I'm tired because it's 3.34am. Maybe I need to take a break. Am I missing something obvious?

```ts
//OK
//Expected: "n"
//Actual: "n"
type no = true extends false ? "y" : "n";

type G<DataT extends { b : boolean }> = (
    true extends DataT["b"]?
    ["Actual", "true extends", DataT["b"]] :
    "Expected"
)

//Wat?
//Expected: "Expected"
//Actual: ["Actual", "true extends", false]
type g = G<{ b : false }>;

```

**Expected behavior:**

`g` to be of type `"Expected"`.

Intuitively,

1. `DataT` is of type `{ b : false }`
2. `DataT["b"]` is of type `false`
3. `true extends false` should be... `false`

**Actual behavior:**

`g` is of type `["Actual", "true extends", false]`

**Playground Link:** [Here](http://www.typescriptlang.org/play/#src=%2F%2FOK%0A%2F%2FExpected%3A%20%22n%22%0A%2F%2FActual%3A%20%22n%22%0Atype%20no%20%3D%20true%20extends%20false%20%3F%20%22y%22%20%3A%20%22n%22%3B%0A%0Atype%20G%3CDataT%20extends%20%7B%20b%20%3A%20boolean%20%7D%3E%20%3D%20(%0A%20%20%20%20true%20extends%20DataT%5B%22b%22%5D%3F%0A%20%20%20%20%5B%22Actual%22%2C%20%22true%20extends%22%2C%20DataT%5B%22b%22%5D%5D%20%3A%0A%20%20%20%20%22Expected%22%0A)%0A%0A%2F%2FWat%3F%0A%2F%2FExpected%3A%20%22Expected%22%0A%2F%2FActual%3A%20%5B%22Actual%22%2C%20%22true%20extends%22%2C%20false%5D%0Atype%20g%20%3D%20G%3C%7B%20b%20%3A%20false%20%7D%3E%3B%0A)

-----

EDIT: I just tested and this is not a problem in TS 3.0.1

I'm not crazy, phew.

**Comment by AnyhowStep** [comment]
This has no problems.

```ts
type G<B extends boolean> = (
    true extends B?
    ["Actual", "true extends", B] :
    "Expected"
)

//OK
//Expected: "Expected"
//Actual: "Expected"
type g = G<false>;
```

**Comment by jack-williams** [comment]
I think this is happening because of #27470 

In `G` the constraint of `DataT` is being pulled down in the access expression `DataT["b"]`. So it is not that `true extends false`, rather it is eagerly using the base constraint in `DataT` so you get `true extends boolean`. This is not covered by the fix #27490 because `"b"` is not a generic type. You can see the correct behaviour if you defer the check using a parameter.

```ts
type G2<DataT extends { b : boolean }, B extends keyof DataT> = (
    true extends DataT[B]?
    ["Actual", "true extends", DataT[B]] :
    "Expected"
)
// g2: "Expected"
type g2 = G2<{ b: false }, "b">;
```
or even doing:
```ts
type G2<DataT extends { b : boolean }, B extends "b"> = (
    true extends DataT[B]?
    ["Actual", "true extends", DataT[B]] :
    "Expected"
)
// g2: "Expected"
type g2 = G2<{ b: false }, "b">;
```

**Comment by AnyhowStep** [comment]
Yikes. I hope this is fixed. This breaks a lot of my code that was working in 3.0.1.

Using your workaround would make the type declarations even more verbose and complex =(

**Comment by Kovensky** [comment]
This _might_ be related to some problems I found while working on the React types; proving that `'x' extends keyof T` is not sufficient to let you index `T` with `'x'`.

**Comment by ahejlsberg** [comment]
Simplified repro with expected outcomes:

```ts
type Foo<T extends { b: boolean }> = true extends T["b"] ? "yes" : "no";

type T0 = Foo<{ b: never }>     // "no"
type T1 = Foo<{ b: false }>;    // "no"
type T2 = Foo<{ b: true }>;     // "yes"
type T3 = Foo<{ b: boolean }>;  // "yes"
```

Currently `Foo` is eagerly evaluated to `"yes"` so every outcome is `"yes"`.

**Comment by AnyhowStep** [comment]
Thank you for fixing this so quickly!

I just updated from `3.0.1` to `3.3.0-dev.20181129` and nothing broke!
