### ISSUE TITLE
Ability to restrict generic to a partial of another generic

### ISSUE THREAD

**Issue by babakness** [microsoft/TypeScript#28664]
## Suggestion
It does not seem possible to restrict a generic to be a partial of another generic
```ts
declare function foo<O, P>(obj: O, part: P & Partial<O>): P
```

This syntax currently does restrict P to only keys of O either

```ts
declare function foo<O, P extends Partial<O>>(obj: O, part: P): P
```

This should be the case

## Use Cases

Many. For example, an update to state O using P where keys of P are required to in keys of O. Generic P is required as the function returns some computation resulting in P or a derivation thereof.

This current syntax does not allow for generic P, only to confine the second parameter as desired

```ts
declare function foo<O>>(obj: O, part: Partial<O>): unknown
```

## Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code

The syntax is valid today yet it does nothing.

* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [x ] This could be implemented without emitting different JS based on the types of the expressions
* [x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment]
```ts
declare function foo<P, O extends P>(obj: O, part: P): P;

foo({ 1: '', 2: '', 3: '' }, { 1: '', 4: '' });
//           ~~~~~ '2' does not exist in type { 1: '', 4: '' }
```
seems to achieve what you are trying to do, but the error messages are on the wrong parameter now.

Afaik, `extends` means that `O` is a more specialized version of `P`, meaning it has to have the properties of `P` but it can also have some more.

**Comment by RyanCavanaugh** [comment]
What you have here is the intended behavior. If you want to log a suggestion, please provide information like what valid and invalid `foo` calls should be - with two floating type parameters like this and two argument positions, there are really a lot of possible interpretations and it's not at all clear what you're trying to achieve.
