### ISSUE TITLE
Generic function allowing invalid type

### ISSUE THREAD

**Issue by thradams** [Microsoft/TypeScript#2866]
```javascript
class stack<T>
{
    data: T[] = [];
};

function push<T>(stack: stack<T>,  n : T)
{
    stack.data.push(n);
}

function main()
{
    var s = new stack<number>();    

    //fine
    push(s, 1);
 
    //Invalid type allowed here.. no error message
    push(s, "a");   
  
}

```

**Comment by RyanCavanaugh** [comment]
?

![image](https://cloud.githubusercontent.com/assets/6685088/7279341/0a8970de-e8d0-11e4-91b2-7a8aceca6333.png)

**Comment by thradams** [comment]
Sorry, I was using an old version that comes with Visual Studio 2013.

After this update:
https://visualstudiogallery.msdn.microsoft.com/2d42d8dc-e085-45eb-a30b-3f7d50d55304

It worked as expected.

error TS2453: Build: The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
