### ISSUE TITLE
Add license badge

### ISSUE THREAD

**Issue by open-source-explorer** [Microsoft/TypeScript#28666]
It would be a good idea to add license badge within the `README` file which is a common practice nowadays.
Thoughts 🤔

**Comment by DanielRosenwasser** [comment]
I appreciate trying to add information more information, but it seems redundant nowadays. I'd rather we not add more badges unnecessarily.

![image](https://user-images.githubusercontent.com/972891/49037275-a9119b00-f16e-11e8-890c-46002abbb989.png)

**Comment by open-source-explorer** [comment]
@DanielRosenwasser @kitsonk What do you think about adding a PR's welcome badge?

**Comment by DanielRosenwasser** [comment]
That information is extremely redundant given the `CONTRIBUTING.md` and "Contributing" sections of the README.

**Comment by open-source-explorer** [comment]
If that's the case, I shall close this!
