### ISSUE TITLE
Same const symbols comparison does not compile

### ISSUE THREAD

**Issue by hwanders** [microsoft/TypeScript#28668]
Using current TypeScript versions (3.1.4, also tested with 3.3.0-dev), the following will cause a compilation error:

```ts
const sym1 = Symbol.for('sym');
const sym2 = Symbol.for('sym');
sym1 === sym2;
```

The `tsconfig.json` should contain: `lib: [ "es2015" ]` to make `Symbol.for` available.

**Expected behavior:**
I think, the code should compile.

**Actual behavior:**
A compilation error occurs: `This condition will always return 'false' since the types 'unique symbol' and 'unique symbol' have no overlap.`

Notice: Using `let` instead of `const` makes it work.

[Playground](http://www.typescriptlang.org/play/#src=const%20sym1%20%3D%20Symbol.for('sym')%3B%0D%0Aconst%20sym2%20%3D%20Symbol.for('sym')%3B%0D%0Asym1%20%3D%3D%3D%20sym2%3B%0D%0A%2F%2F%20error%20occurs%20here%3A%0D%0A%2F%2F%20this%20condition%20will%20always%20return%20'false'%20since%20the%20types%20'unique%20symbol'%0D%0A%2F%2F%20and%20'unique%20symbol'%20have%20no%20overlap.%0D%0A%0D%0Alet%20sym3%20%3D%20Symbol.for('sym')%3B%0D%0Alet%20sym4%20%3D%20Symbol.for('sym')%3B%0D%0Asym3%20%3D%3D%3D%20sym4%3B%0D%0A%2F%2F%20works%0D%0A)

**Comment by weswigham** [comment]
@rbuckton why does `Symbol.for` generate a `unique symbol` instead of just a `symbol`? What usecase is that meant for? Object keys?

**Comment by rbuckton** [comment]
`Symbol.for` symbols should also be usable in an interface. The only downside is that two instances of `Symbol.for` for the same argument don't currently produce the *same* unique symbol.

Here's an example of this use case: https://github.com/esfx/esfx/blob/master/packages/equatable/src/index.ts

**Comment by rbuckton** [comment]
This was a known limitation of `unique symbol` when we introduced the feature as we have no way to indicate a "slightly less unique" symbol currently.

**Comment by kitsonk** [comment]
One could say it is a literal symbol, not a unique symbol.
