### ISSUE TITLE
Ambient filename must differ from implementation

### ISSUE THREAD

**Issue by niedzielski** [Microsoft/TypeScript#28661]
**Summary** It is currently not possible to split simple TypeScript type definitions into a pair of declaration (.d.ts) and implementation (.js) files if they have the same stem. E.g., src/foo.d.ts and src/foo.js cannot be distinguished. This is a useful means to share types, especially in JavaScript projects, which are limited to JSDoc-flavored TypeScript.

**TypeScript Version:**  3.3.0-dev.20181122

**Search Terms:** ambient module, ambient script, jsdoc shared types, declaration types, interface types, implementation types 

**Code**

```ts
// <math.d.ts> declaration
/** A coordinate type useful everywhere. */
type XY = Readonly<{x: number, y: number}>

// <math.js> implementation
/**
 * Converts two points to a vector.
 * @arg {XY} lhs
 * @arg {XY} rhs
 * @return {XY}
 */
module.exports.vector = function(lhs, rhs) {
  return {x: lhs.x - rhs.x, y: lhs.y - rhs.y}
}

// <index.js> program
// Error: File 'math.d.ts' is not a module. [2306]
const math = require('./math.js')

/**
 * @arg {XY} lhs
 * @arg {XY} rhs
 * @return {void}
 */
function main(lhs, rhs) {
  console.log(math.vector(lhs, rhs))
}

main({x: 1, y: 2}, {x: 3, y: 4}) // Prints {x: -2, y: -2}.
```

**Expected behavior:**
`XY` ambient type is available globally and math.js JavaScript file can be imported without type failure.

**Actual behavior:**
`XY` ambient type is available globally but math.js is confused with the declaration, math.d.ts.

**GitHub Link:** https://github.com/niedzielski/ambient-filename (Requires multiple files which the playground doesn't seem to support.)

**Comment by kitsonk** [comment]
How would you anticipate TypeScript supporting it.  There are a lot of existing code where people depend on the behaviour of the `.d.ts` file providing the type information and the `.js` just being the emitted code.

**Comment by niedzielski** [comment]
Perhaps I am misunderstanding. The above example is a JavaScript project that uses inference and JSDocs for typing. There's no bundling or code emitted so I can only import .d.ts files in the JSDocs themselves. E.g.:

```js
/** @typedef {import('./foo.d.ts').Foo} Foo */
/** @typedef {import('./foo.js').bar} bar */
```

The functional code can only import .js files.

If an extension is specified, I'd expect that to be used. That is, .js imports from the JavaScript file and .d.ts imports from the TypeScript file. If no extension is specified, perhaps they could be merged.

**Comment by weswigham** [comment]
*sigh* sadly, that can't be the case, because far more people expect to, eg, write `import("my/file/name.js")` and have the result type be pulled from the associated declaration file, and not the JS (and it would be very strange if import types resolved specifiers differently than import statements or expressions).

I recommend just avoiding the conflict and naming the declaration file part differently - eg, `foo.types.d.ts` instead of `foo.d.ts`.

**Comment by niedzielski** [comment]
Thanks for the background and consideration. Please feel welcome to resolve this issue if no further discussion is needed.
