### ISSUE TITLE
Not null refinement does not work for type being null

### ISSUE THREAD

**Issue by maximeg** [microsoft/TypeScript#28665]
**TypeScript Version:**  version of the playground

**Search Terms:** null, refinement

**Code**

I encountered a case that I simplified overly here, even if it appears synthetic:
```ts
let a: { foo: string | null, bar: null } = { foo: null, bar: null };
let array: string[] = [];

if (a.foo !== null) {
    array.push(a.foo);  // Works
}

if (a.bar !== null) {
    array.push(a.bar); // Error, a.bar is considered null
}
```

**Expected behavior:**
No error.
**Actual behavior:**
An error `Argument of type 'null' is not assignable to parameter of type 'string'.`
**Playground Link:** https://www.typescriptlang.org/play/#src=let%20a%3A%20%7B%20foo%3A%20string%20%7C%20null%2C%20bar%3A%20null%20%7D%20%3D%20%7B%20foo%3A%20null%2C%20bar%3A%20null%20%7D%3B%0D%0Alet%20array%3A%20string%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0Aif%20(a.foo%20!%3D%3D%20null)%20%7B%0D%0A%20%20%20%20array.push(a.foo)%3B%0D%0A%7D%0D%0A%0D%0Aif%20(a.bar%20!%3D%3D%20null)%20%7B%0D%0A%20%20%20%20array.push(a.bar)%3B%0D%0A%7D  (with strictNullChecks=true)

**Comment by MartinJohns** [comment]
According to the type definition `a.bar` can **only** be `null`. What type do you suggest it should narrow down to? I think the behavior is correct as it is.

**Comment by weswigham** [comment]
We don't currently narrow non-uniom types to `never`, generally speaking. That's why there's a difference here - we don't really see single types as "unions of one element" in flow control right now.
