### ISSUE TITLE
No Space between empty Brackets

### ISSUE THREAD

**Issue by KirschbaumP** [microsoft/TypeScript#28678]
The current state is that the autoformatter places an space between the brackets "{ }"
```
constructor() { }
```
I want an option that the result should be:
```
constructor() {}
```

In the settings are options for turining on/off "typescript.format.insertSpaceAfterOpeningAndBeforeClosing**Nonempty**Brackets" but **not** for "typescript.format.insertSpaceAfterOpeningAndBeforeClosing**Empty**Brackets"

**Comment by KirschbaumP** [comment]
any news to this?

**Comment by jonathan-buttner** [comment]
A work around for this that I found was to use the Prettier code formatter extension for vscode: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by davidkwan95** [comment]
@DanielRosenwasser Hi, I've made a PR for this https://github.com/microsoft/TypeScript/pull/35427. Would you mind to take a look?
