### ISSUE TITLE
Rename prefix/suffix needs to be opt-in

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#28679]
I believe this is the main change: https://github.com/Microsoft/TypeScript/commit/0a97663843e11f745d9998d54db0970ee3bfb748

I believe the goal was to be able to rename `x` to `y` like this:
```ts
const x = 1;
export { x };
```
```ts
const y = 1;
export { y as x };
```

Since editors pre-dating this change don't know that prefix and suffix text might accompany the rename result, they don't apply it, resulting in
```ts
const y = 1;
export { y };
```
which breaks any importing file.

We probably need a `UserPreference` to make this behavior opt-in.

**Comment by minestarks** [comment]
@DanielRosenwasser @sandersn this changed in 3.2 and looks rather bad in VS - can we target fixing it sooner?
