### ISSUE TITLE
Loose typing for object with index signature

### ISSUE THREAD

**Issue by michelbitter** [Microsoft/TypeScript#28683]
**TypeScript Version:**  3.1.5

**Search Terms:**
Index Object Wrong Type Assertion

**Code**

```ts
const testObj: { [key: string]: string } = {
    'test': '423423423gwe',
    'fesgeg': 'yekwjfghkfhewk',
}

const test = testObj['fjdhsgjfhdg']
```

**Expected behavior:**
I expected that the type of the constant test is `string | undefined` or in best situation `undefined`. I could understand that typescript can't know of the key is available based on the index signature in the typing, but it doesn't make any sense to just assert that the given key name is available in the object.

**Actual behavior:**
the type of the constant test is `string`

**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/#src=const%20testObj%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20string%20%7D%20%3D%20%7B%0D%0A%20%20%20%20'test'%3A%20'423423423gwe'%2C%0D%0A%20%20%20%20'fesgeg'%3A%20'yekwjfghkfhewk'%2C%0D%0A%7D%0D%0A%0D%0Aconst%20test%20%3D%20testObj%5B'fjdhsgjfhdg'%5D)

**Related Issues:**

**Comment by michelbitter** [comment]
I made the example code much smaller and easier

**Comment by cpplearner** [comment]
See discussion in #13778
