### ISSUE TITLE
Part of the fullscreen API is no longer present in the type definitions

### ISSUE THREAD

**Issue by kayahr** [microsoft/TypeScript#28681]
**TypeScript Version:**  3.1.6 and 3.3.0-dev.20181122

**Search Terms:** fullscreen

**Code**

```ts
console.log(document.fullscreenElement);
```

**Expected behavior:**

Code should compile like it did with TypeScript 3.0

**Actual behavior:**

TypeScript does not know this property any longer:

```
$ tsc test.ts 
test.ts:1:22 - error TS2339: Property 'fullscreenElement' does not exist on type 'Document'.

1 console.log(document.fullscreenElement);
                       ~~~~~~~~~~~~~~~~~


Found 1 error.
```

I'm really confused why this type definition has been removed. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement) and the [WhatWG spec](https://fullscreen.spec.whatwg.org/#dom-document-fullscreenelement) `document.fullscreenElement` is still the proposed standard.

EDIT: Previously I also reported that the webkit-prefixed versions of the fullscreen API was also removed from the type definitions. And I said that the ms and moz prefixed versions are still working which was wrong. There were no ms/moz prefixed versions before and I found them in my own typings. So I guess removing the webkit-prefixes isn't a bug and I have to add them to my own typings, as well. But still the proposed standard property `document.fullscreenElement`  is no longer in the type definition and I still think this is a bug.

**Comment by weswigham** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by afeld** [comment]
cc https://github.com/Microsoft/TSJS-lib-generator/pull/597

**Comment by jakebailey** [comment]
Just checking old issues; this one was fixed a super long time ago. [Playground Link](https://www.typescriptlang.org/play?ts=5.1.6#code/MYewdgziA2CmB00QHMAUATEwCuBbWYALvAGbbTQTABOsBAonPkQJQDcQA)
