### ISSUE TITLE
Default values for parameter of a constrained generic type

### ISSUE THREAD

**Issue by DeTeam** [Microsoft/TypeScript#28686]
**TypeScript Version:**  3.1.4

**Search Terms:**

**Code**

```ts
function f<T extends boolean>(some: T = false) {}
```

**Expected behavior:**

TS would happily accept and type-check this code (leaving me solving type narrowing with guards later on)

**Actual behavior:**

> Type 'true' is not assignable to type 'T'.

**Playground Link:** [here is a link](https://www.typescriptlang.org/play/#src=function%20f%3CT%20extends%20boolean%3E(some%3A%20T%20%3D%20false)%20%7B%7D)

**Related Issues:**

**Comment by jack-williams** [comment]
Duplicate of #21521

**Comment by DeTeam** [comment]
Nice catch @jack-williams, thanks!

It's not exactly a duplicate. I'm providing a constraint for `T` and expecting no need to do `as T` for the default value.

**Comment by jack-williams** [comment]
@DeTeam Yes you're right that it's not exactly the same, sorry about that. I think the reasoning will still be the same. You can get into situations like this:
```ts
f<true>();
```

I think this is a duplicate, or at least related: #28154

**Comment by DeTeam** [comment]
Yup, that one seem related.

We can close this one and continue in the original thread then :)
