### ISSUE TITLE
Resolve references using tsconfig??

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2868]
Currently you need to do a main references file when dealing with multiple typescript files. This can become a pain to manage. Could we just use the files from tsconfig.json or better yet use all typescript files in all directories under where the resolved tsproject.json is found.

**Comment by mhegazy** [comment]
This is the [semantics of tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json). by adding an empty tsconfig to your directory, all .ts files in this directory will be considered part of a "project". you can build using `tsc --p` or just `tsc` in your root directory.
alternatively you can specify a set of `files` in the tsconfig file and build the same way.

**Comment by niemyjski** [comment]
Yes, but what I'm talking about is not having to do 
/// <reference path="../references.ts" /> in every file.. this is really annoying.

**Comment by mhegazy** [comment]
you are talking about building or the editing experience in VS?

**Comment by niemyjski** [comment]
In this case editing but I'd think it should work for both. The problem is when you have tsconfig.json files... then, I'd want to be able to select the configuration I'm working on in my editor much like debug / release in vs.. Otherwise default to all files in that folder.

**Comment by niemyjski** [comment]
That's why I think it would be nice to support a naming convention where you have:

* \tsconfig-es5.json
* \tsconfig-es6.json

and then you could apply those rules under the specific target (es5 or es6)..

**Comment by mhegazy** [comment]
tsconfig support is not in VS yet. it should be in soon though. Until this is done you would want to keep your /// references to keep your editing experience in VS.

**Comment by mhegazy** [comment]
@niemyjski can you file a suggestion making "--p" take a full path to tsconfig.json as well as a directory. (i.e. check if it is a file, use it if not look for tsconfig.json within that directory).

**Comment by niemyjski** [comment]
Yes, I'll make this suggestion. Do you think I should add a request for making it also support tsconfig.json first and if it can't find one it looks for the first tsconfig*.json?

**Comment by mhegazy** [comment]
I would say only file support in --p. this way we do not have to worry about order, when there are multiple ones

**Comment by mhegazy** [comment]
looks like this is already tracked by #2869.
