### ISSUE TITLE
Why Type 'number' is not assignable to type 'T'?

### ISSUE THREAD

**Issue by coder-sango** [Microsoft/TypeScript#28697]
`function say3<T>(a: T): T {
    return a + 1;
}
let speak = say3<number>(1)
`

i try the demo,but it say " Type 'number' is not assignable to type 'T'.'
T isn't a number?

**Comment by RyanCavanaugh** [comment]
Cross-post of https://stackoverflow.com/questions/53511050/typescriptwhy-type-number-is-not-assignable-to-type-t
