### ISSUE TITLE
--p command line option should support taking a full path or directory.

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2869]
This would allow you to specify a tsconfig.json that has a different name. 

If you specify a directory, it should first try to resolve tsconfig.json. If it can't find it, it should find the first tsconfig*.json file

References: https://github.com/Microsoft/TypeScript/issues/2868#issuecomment-95262429

**Comment by SaschaNaz** [comment]
What benefit can we get when tsc automatically search tsconfig*.json files? What should happen when there are multiple tsconfig* files except tsconfig.json?

**Comment by aleksey-bykov** [comment]
since my request #5705 got closed I am writing here:

- let's add a parameter that points to whatever configuration file we please: `--configuration c:\foo\bar\myproject.csproj`

**Comment by mhegazy** [comment]
> let's add a parameter that points to whatever configuration file we please: --configuration c:\foo\bar\myproject.csproj

@aleksey-bykov can you elaborate on what is the expectation here? do you expect tsc to read the .csproj? where would the infrormation be stored?

**Comment by aleksey-bykov** [comment]
i am saying the developer should be free to specify any file that has a valid tsconfig JSON content even if the name itself doesn't make any sense

**Comment by mhegazy** [comment]
i see, so why not use `--project` as in the OP?

**Comment by aleksey-bykov** [comment]
because it's already taken it would be a breaking change

**Comment by mhegazy** [comment]
not really, we can check if it is a file path use it, if it is a directory append "tsconfig.json" before reading the file.

**Comment by aleksey-bykov** [comment]
true, good catch

**Comment by RyanCavanaugh** [comment]
Thanks @SaschaNaz ! :tada:
