### ISSUE TITLE
Auto import completions not returned in TS 3.2-rc for non-checked js files

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#28696]
**TypeScript Version:**  3.2.0-rc

**Search Terms:**
- javascript
- auto imports

**Code**
For a js project :

`jsconfig`
```js
{
    "compilerOptions": {
        "target": "es6",
        "baseUrl": ".",
        "jsx": "react"
    },
    "include": [
        "src/**/*.js"
    ]
}
```

`src/components/index.js`

```js
export const abc = 123;
```

`src/bla.js`
```js
abc
```

1. Trigger completions on `abc` in `bla.js`

**Expected behavior:**
Auto import completion for `abc` is returned

**Actual behavior:**
No completion returned

**Comment by mjbvz** [comment]
Hey @DanielRosenwasser  @andy-ms can you please take a look at this. I also see this in 3.1.6 but it seems like an important regression

Here's the ts server log: [tsserver.log](https://github.com/Microsoft/TypeScript/files/2622486/tsserver.log)

**Comment by sheetalkamat** [comment]
@DanielRosenwasser We do not offer completions if we think file could be non module. In js files with non ts check we always say do not offer auto import. In that we check if its javascript file. Should we move this as last check? After all the options are verified to be non module? 
https://github.com/Microsoft/TypeScript/blame/master/src/services/completions.ts#L1054
