### ISSUE TITLE
Editor configuration support based on a tsconfig.json naming convention.

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2870]
This would resolve a problem when you have tsconfig.json files in a folder. It would be cool if you could select the configuration (Think Debug or Release). By default it would just be the default configuration.

That's why I think it would be nice to support a naming convention where you have:

* \tsconfig-es5.json
* \tsconfig-es6.json

and then you could apply those rules under the specific target (es5 or es6)..

Reference https://github.com/Microsoft/TypeScript/issues/2868#issuecomment-95262429

**Comment by mhegazy** [comment]
There is a large number of possible combinations of options that would be hard to satisfy them all in names, e.g. tsconfig-es5-commonjs-noImplicitAny.json, i would expect instead you would have `tsconfig-debug.json` or `debug\tsconfig.json` and your build system will check the debug/release flags to know which one to build.

I believe  #2869 would make this even easier by allowing you to specify a full path to a json file.
