### ISSUE TITLE
Why must two methods with the same name be identical when inheriting them from different interfaces?

### ISSUE THREAD

**Issue by benjamin-hg** [Microsoft/TypeScript#2871]
declare class Super {
        set(property:string, value:any);
    }

    declare class SubA extends Super {
        set(property:string, value:any); // don't know why this is needed, as it should be inherited
        set(property:"name", value:string);
    }

    declare class SubB extends Super {
        set(property:string, value:any); // okay, I repeat myself.
        set(property:"size", value:number);
    }

    interface BothA extends SubA, SubB {

    }

Gives me:
Error:(16, 15) TS2320: Interface 'BothA' cannot simultaneously extend types 'SubA' and 'SubB'.
  Named properties 'set' of types 'SubA' and 'SubB' are not identical.

I'm working with Dojo, where `SubA` and `SubB` are two Widgets and `Both` is the type of a mixin.

Ironically, this prevents the error:

    interface BothA extends SubA, SubB {
        set(property:string, value:any); 
    }

**Comment by RyanCavanaugh** [comment]
If they're not identical, we don't have any good way to "merge" them in an order that's predictable and meaningful. The workaround you posted is the intended one -- when two inherited properties aren't identical, the fix is to specify how they should be merged.

**Comment by benjamin-hg** [comment]
@RyanCavanaugh Can you give an example, why merging declarations in this case can't be done in a predictable and meaningful way? Where is the conceptual difference to the merging described here: http://www.typescriptlang.org/Handbook#declaration-merging ?

**Comment by benjamin-hg** [comment]
Or maybe, my question could be boiled down to: "Where can I find explained the difference between two interfaces with the same name getting merged and one interface extending two interfaces at a time"

**Comment by ip** [comment]
@RyanCavanaugh 
> If they're not identical, we don't have any good way to "merge" them in an order that's predictable and meaningful.

Last one wins, maybe?
