### ISSUE TITLE
"Subsequent variable declarations must have the same type." occurs in a nested package.

### ISSUE THREAD

**Issue by anurbol** [microsoft/TypeScript#28712]
**TypeScript Version:**  3.1.6 (tested 3.3.0-dev.20181128 as well, but it brings other errors)

**Search Terms:**
 Subsequent variable declarations must have the same type.  Variable 'xxx' must be of type 'nnn', but here has type 'yyy'.

**The problem:**
When having two projects in which one is placed inside the other, and running `tsc` in the child one, for some reason the compiler takes into account the types from the parent project.

**Steps to reproduce:**
```
# 1. install vscode extension boilerplate
yo code # installs VSCode extension boilerplate with the help of the wizard. Let's provide the name of the project "vscode-extension".
# 2. install react app in another folder
npx create-react-app react-app --scripts-version=react-scripts-ts # from here https://github.com/wmonk/create-react-app-typescript
cd react-app
tsc // ok
npm run build // (runs tsc) ok
# 3. move react-app to a subfolder of vscode-extension
cd ..
mv react-app vscode-extension/react-app
cd vscode-extension/react-app
tsc // 3.1.6 gives: "Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'Describe', but here has type 'IContextDefinition'." and 3.3.0-dev gives maximum call stack exceeded
npm run build // 3.1.6 gives: Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'Describe', but here has type 'IContextDefinition'. and 3.3.0-dev gives maximum call stack exceeded

```
When reproducing, keep in mind `npm run build` uses locally installed typescript version.

**Expected behavior:**
Not takes into account types from parent directories.

**Actual behavior:**
Takes into account types from parent directories.

**Comment by anurbol** [comment]
FWIW, adding this helped:
```
    "typeRoots": [
      "node_modules/@types"
    ]
```

**Comment by RyanCavanaugh** [comment]
I believe this has been fixed; please log a new issue with a repo or something if not (commandline steps like this tend to age out very quickly). Thanks!
