### ISSUE TITLE
Adding Regex to string literal typing

### ISSUE THREAD

**Issue by pdaniel3** [Microsoft/TypeScript#28713]
## Suggestion

I would like to see string literal types have the ability to specify a regular expression as an alternative to a static string

## Use Cases

Any time when a string should only match a certain regex. 

Preventing exhaustive string literal union types that could be better described by regex

## Examples

`type EmailLiteral = '/\S+@\S+\.\S+/'`

Could be used like this

```
public submitEmail(email: EmailLiteral) : void
{
   ...
}

submitEmail('johndoe@gmail.com') // okay
submitEmail('asdf') //error
```

**Comment by j-oliveras** [comment]
Duplicated of #6579.

**Comment by DanielRosenwasser** [comment]
Please use the search tool for duplicate issues in the future.
