### ISSUE TITLE
Type parameter inference seems to break using async function

### ISSUE THREAD

**Issue by MLoughry** [Microsoft/TypeScript#28721]
**TypeScript Version:**  3.2.0-rc

**Search Terms:**
type parameter async 

**Code**
```ts
interface Foo {
    a: number;
    b: boolean;
}

function inner<T extends Foo>(): T {
    return {a: 1, b: true} as T;
}

async function outer<T extends Foo>(): Promise<T> {
    return inner();
}
```

**Expected behavior:**
No error, as the type parameter is inferred correctly (as in 3.1.6)

**Actual behavior:**
```
src/example.ts:23:5 - error TS2322: Type 'Foo' is not assignable to type 'T'.

23     return inner();
```

**NOTE: This does have a workaround**. However, I figured it would be worthwhile to open a bug anyway in case this change was not intended:
```ts
function inner<T extends Foo>(): T {
    return {a: 1, b: true} as T;
}

async function outer<T extends Foo>(): Promise<T> {
    // passing the type parameter explicitly fixes the bug.
    return inner<T>();
}
```

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=%0D%0Ainterface%20Foo%20%7B%0D%0A%20%20%20%20a%3A%20number%3B%0D%0A%20%20%20%20b%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Afunction%20inner%3CT%20extends%20Foo%3E()%3A%20T%20%7B%0D%0A%20%20%20%20return%20%7Ba%3A%201%2C%20b%3A%20true%7D%20as%20T%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20outer%3CT%20extends%20Foo%3E()%3A%20Promise%3CT%3E%20%7B%0D%0A%20%20%20%20return%20inner()%3B%0D%0A%7D

**Related Issues:** 
#28529

**Comment by AnyhowStep** [comment]
How is this a bug?

```ts
//Expected type: Promise<{ a: 45, b: false }>
const x = outer<{ a: 45, b: false }>();
```

The thing is, you can't say that `Foo` is assignable to `T`, just because `T` is assignable to `Foo`

**Comment by MLoughry** [comment]
At the very least, it's a change in behavior.

**Comment by RyanCavanaugh** [comment]
This is the expected behavior now
