### ISSUE TITLE
Customised Operators

### ISSUE THREAD

**Issue by puppy0cam** [Microsoft/TypeScript#28726]
## Search Terms
label:Suggestion operators 
label:Suggestion typeof 
label:Suggestion instanceof 

### Customized operators
Note: for readers to understand the concept, keywords that already exist are defined in the example. 

Conditional operations are a major part of computational operations. They allow a programmer to evaluate information and do a different action depending on the value of a variable. Within JavaScript, there exist a few keywords that would be implemented as a function if it were replicated. For example, the `instanceof` keyword tests the first parameter to see if it's constructor is the second parameter.
```typescript
if (data instanceof MyClass) {
    // Do something
} else {
    // it didn't meet my conditions!
}
```
This code is extremely readable and tells you exactly what it means in roughly english terms. However if you did not have the `instanceof` keyword, then your implementation would look more like this:
```typescript
if (data.constructor === MyClass) {
    // Do something
} else {
    // it didn't meet my conditions!
}
```
This code could break if `data` was a value such as `null` which actively blocks attempts to read it's properties by throwing a `TypeError` when you attempt to access a property in it. So then, a programmer might create a function so that it can have a try catch block.
```typescript
function instanceof(data, constructor) {
    try {
        return data.constructor === constructor;
    } catch {
        return false;
    }
}
if (instanceof(data, MyClass)) {
    // Do something
} else {
    // it didn't meet my conditions!
}
```
Suddenly your if statement is harder to read because you have turned a readable statement into an action that is being executed and maintaining this code has become that much harder.

These keywords are readable and very useful, but they are limited because it would be ridiculous to try to implement every single edge case as their own keyword. This proposal suggests that functions could be placed next to data to evaluate them and return a value.
```typescript
function instanceof(data, constructor) {
    try {
        return data.constructor === constructor;
    } catch {
        return false;
    }
}
if (data instanceof MyClass) {
    // Do something
} else {
    // it didn't meet my conditions!
}
```
Syntax-wise, the if statement is identical to current readable syntax. The difference is that rather than being an inbuilt keyword, `instanceof` could be changed to an inbuilt function. To make this work with things like `typeof`, your function could be defined as so:
```typescript
function instanceof(before, after) {
    try {
        return before.constructor === after;
    } catch {
        return false;
    }
}
function typeof(before, after) {
    if (after instanceof String) {
        return "string";
    } else if (after instanceof Number) {
        return "number";
    } else if (after instanceof Function) {
        return "function";
    } else if (after instanceof Boolean) {
        return "boolean";
    } else if (after instanceof Symbol) {
        return "symbol";
    } else if (after === null || after instanceof Object) {
        return "object";
    } else if (after === undefined) {
        return "undefined";
    }
}
if (typeof data === "object") {
    // Do something
} else {
    // it didn't meet my conditions!
}
```
The defined functions in this example have not specified a type in the parameters. This could be used to provide additional compile time type checks on the parameters the function is able to take. This allows you to have an all purpose modifier or a modifier that you only plan to apply in certain situations. It could be used to quickly switch logging on or off without having to add and remove extra lines.
```typescript
const debugMode = true;
function thenTellMe(before: any, after: any) {
    if (debugMode && before) {
        console.warn(before, after, new Error().stack);
    }
    return before;
}

function isHello(before: any, suffix: string) {
    /*
        I'm handling the problem by returning false so that
        the evaluation fails without having to throw.
    */
    if ((suffix.toLowerCase() !== "world") thenTellMe "improper hello world") {
        return false;
    } else {
        return true;
    }
}

if (isHello Symbol()) {
    // This code won't compile because the the isHello after typ
}
```
With these function, here is some examples of how it would react. with this
```typescript
// This evaluates to true, which runs the code in the if block
if (isHello "world") {
    console.log(":)");
}
```
```typescript
// This evaluated to false, so it won't run the code in the if block
if (isHello "fail") {
    console.log(":)");
}
```
```typescript
// This would fail in the compiler because it fails the type check for calling the isHello function
if (isHello Symbol()) {
    console.log(":)");
}
```
Compiled code would be as if it were just being called like a regular function
```javascript
const debugMode = true;
function thenTellMe(before, after) {
    if (debugMode && before) {
        console.warn(before, after, new Error().stack);
    }
    return before;
}
function isHello(before, suffix) {
    if (thenTellMe((suffix.toLowerCase() !== "world"),"improper hello world")) {
        return false;
    } else {
        return true;
    }
}
if (isHello(undefined, "world")) {
    console.log(":)");
}
if (isHello(undefined, "fail")) {
    console.log(":)");
}
```

**Comment by DanielRosenwasser** [comment]
This doesn't meet [the design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) of TypeScript since it involves runtime-oriented syntax that's not a part of ECMAScript.
