### ISSUE TITLE
Support decimal values and arithmetic

### ISSUE THREAD

**Issue by BalassaMarton** [Microsoft/TypeScript#2872]
TypeScript should support decimal values and arithmetic, similar to .NET's `Decimal` and/or Java's `BigDecimal` type. This would solve some serious problems when writing business applications in JavaScript. 

For the following TS code:

```ts
var a = 0.1m; // notation is totally ad-hoc, just for the sake of the example code
var b = 0.2m;
var c = a + b;
if (c === 0.3m) {
    console.log("OK");
}
```

the JS output should be something like this:

```javascript
    var a = new Decimal("0.1");
    var b = new Decimal("0.2");
    var c = Decimal.add(a, b);
    if (Decimal.compare(c, new Decimal("0.3") === 0) {
        console.log("OK");
    }
```

where `Decimal` is the class that implements the decimal arithmetic and conversions.
There are a number of JS decimal implementations to take inspiration from:
https://github.com/MikeMcl/decimal.js
https://github.com/MikeMcl/bignumber.js
https://www.npmjs.com/package/jsdecimal
https://github.com/iriscouch/bigdecimal.js

**Comment by DanielRosenwasser** [comment]
See [TypeScript's non-goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

As you've said:

> There are a number of JS decimal implementations to take inspiration from:
https://github.com/MikeMcl/decimal.js
https://github.com/MikeMcl/bignumber.js
https://www.npmjs.com/package/jsdecimal
https://github.com/iriscouch/bigdecimal.js

As our non-goal suggests, those libraries are sufficiently usable from TypeScript itself. DefinitelyTyped currently currently has typings for [decimal.js](https://github.com/borisyankov/DefinitelyTyped/blob/master/decimal.js/decimal.js.d.ts)

**Comment by fletchsod-developer** [comment]
Does Typescript have like bool.parse(), decimal.parse(), etc.?  Does Typescript have datatype conversion features?  Just wondering cuz we don't want to have baggage issues we're struggling with, from adding too many 3rd party libraries.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't provide any built-in run-time libraries.

**Comment by VsMaX** [comment]
> As our non-goal suggests, those libraries should be sufficiently usable from TypeScript itself. DefinitelyTyped currently currently has typings for decimal.js

Looks like it's significantly outdated. Any alternative to this issue so far?

**Comment by karsunke** [comment]
I found this typings

https://www.npmjs.com/package/@types/decimal.js

for this library:

https://www.npmjs.com/package/decimal.js
