### ISSUE TITLE
fill default generic types by usage.

### ISSUE THREAD

**Issue by dudubs** [Microsoft/TypeScript#28731]
When I have a interface with multiple generic types, I don't want to determine a default generic types because at I expand that interface I will can forget to fill the required type - this can produce errors later on.
because that I suggest a syntax of fill all types of generic types by coefficient of type.
example:
`
interface A<T,U,I> ...
interface B extends A<....

let a: any A // equals to let a: A<any,any.any>.
let b: string B // equals to B<string,string...>
..
// for beautiful and short code.
any Array
any Record
...
`

**Comment by nmain** [comment]
If I have a `MyInterface<T, U>` then there's no general expectation that `T` and `U` are at all related.  If a previous version of the code had a `MyInterface<T>` then the new `MyInterface<T, U>` is a major change in the behavior and specification of `MyInterface` and I wouldn't have any expectation that uses of `MyInterface<Foo>` in the old version could be seamlessly replaced with `MyInterface<Foo, Foo>` in the new version.

I'm sure there are a few canned scenarios in which this makes sense, but I can't see it being generally useful.

If the change from `MyInterface<T>` to `MyInterface<T, U>` is only adding new properties on `U` disjoint from the properties on `T`, what about declaring it like this?

```
interface MyInterface<T, U = unknown> {
    prop1: T;
    prop2: U;
}
```

Then existing code could continue referring to `MyInterface<T>` and continue using `prop1` as before, but the consumer would be forced to make a type assertion or switch to `MyInterface<T, U>` if they wanted to consume `prop2`.
