### ISSUE TITLE
completions don't include primitives for type arguments inside a function

### ISSUE THREAD

**Issue by ChuckJonas** [microsoft/TypeScript#28737]
- VSCode Version: 1.29.1 (1.29.1)
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. create a node typescript project
2. `npm install querystring`
3. `type let m = new Map<string,`

**Expected:**
I would have a Map with string key.  No autocomplete would be preformed since I already have a valid statement

**Result:**
When you type the `,` vscode will autocomplete to `let spMap = new Map<stringify,` and add an import for `import { stringify } from 'querystring';`.

I haven't tested this with other primitive types, so I only know for sure that it fails with `string`. 

Does this issue occur when all extensions are disabled?: Yes

![wrong import](https://user-images.githubusercontent.com/5217568/49125081-fb8cad80-f27b-11e8-81dd-beedf1f46461.gif)

**Comment by mjbvz** [comment]
Confirmed that `string` is not returned inside a function with TS 3.3.0-dev.20181129

@ChuckJonas Set `"editor.acceptSuggestionOnCommitCharacter": false` to disable commit on `,` in VS Code

**Comment by ChuckJonas** [comment]
@mjbvz so... this will be tagged as a bug? Setting  `"editor.acceptSuggestionOnCommitCharacter": false` is less than ideal because now I also won't get completions on `.` or `;`

**Comment by sandersn** [comment]
Notably, this only happens for *values*: `let m = new Map<string/**/`
It doesn't happen for *types*: `let m: Map<string/**/`
