### ISSUE TITLE
Typescript intellisense not providing proper suggestion

### ISSUE THREAD

**Issue by PratimGhosh86** [microsoft/TypeScript#28738]
- VSCode Version: 1.28.2 (user setup)
- OS Version: Windows 10 Pro 1809 17763.107

Steps to Reproduce:

1. Setup an Angular 7 project using angular cli
2. Open a module file and attempt to add HttpClient

![snip-2018-11-12 232210](https://user-images.githubusercontent.com/17795322/48365774-dd4a7d80-e6d1-11e8-90a6-99d68041a793.jpg)

Does this issue occur when all extensions are disabled?: Yes

I tried using the Auto Imports extensions but that doesn't work either. The only extension that is able to provide proper suggesting is Typescript Toolbox, but the import process is rather lengthy with it.

**Comment by weswigham** [comment]
Very likely - afaik typeRoots directly overrides our automatic search paths.
