### ISSUE TITLE
JSDoc + Array declaration can break tsserver (high cpu)

### ISSUE THREAD

**Issue by phil294** [microsoft/TypeScript#28736]
**TypeScript Version:**  typescript@3.3.0-dev.20181129

**Search Terms:** CPU, tsserver

**Code**

Consider global extension of `Array`
```ts
declare global {
  interface Array<T> extends ...
}
```

And the following Javascript file:
```js
import { all } from 'rsvp';
/**
 * @param {Array<String>} x
 */
function laggy(x) {
  all(x); // all() accepts a string array
}
```

**Expected behavior:**
Nothing special

**Actual behavior:**
CPU usage of tsserver goes to 100%, entire Typescript Intellisense freezes.

**Repo Link:**
clone `https://github.com/phil294/tsserver_lag_demo`,
`yarn`,
open up VSCode,
open *both* `laggy.js` and `index.d.ts`,
CPU goes insane

Could only reproduce with the javascript one, seems to not affect a laggy.ts

**Comment by sandersn** [comment]
I got it to repro. A few notes so far:

1. Doesn't repro with tsc.
2. I left it running over lunch and it eventually returned.
3. Both pieces, the call to `all` and the new base class of Array, are required to make the
4. The real culprit so far is ember's Observable.
5. Essentially, this code assigns a complex type (Array extends Observable) to a function with 10 overloads. That might be the problem, but I'm not sure why it doesn't manifest from the command line.

@phil294 Also the title mentions "invalid JSDoc". Is `Array<String>` invalid somehow? That's the only jsdoc I see.

**Comment by amcasey** [comment]
Nathan's repro takes 18 seconds with TS 3.3 and 0.4 seconds with TS 3.4, so I suspect this may have been fixed.  Please let us know if you're still seeing this issue.

**Comment by phil294** [comment]
Seems to be fixed. The opening example is smooth now.
Cheers
