### ISSUE TITLE
Typechecker improperly infers nested string type if no type annotation is provided

### ISSUE THREAD

**Issue by AlexPikalov** [Microsoft/TypeScript#28734]
**TypeScript Version:**  3.2.0

**Search Terms:**
nested string type casting, type casting

**Code**

```ts
type S = 'a' | 'b';

interface Typed { 
    nested: S;
}

const checker = (a: Typed) => { };

// no type annotation in const declaration
const obj = { nested: 'a' };

// compiler error
checker(obj);
// works
checker({ nested: 'a' });
```

**Expected behavior:**
Type casted to a string type `S`.

**Actual behavior:**
Type casted to `string` with error

```
Argument of type '{ nested: string; }' is not assignable to parameter of type 'Typed'.
  Types of property 'nested' are incompatible.
    Type 'string' is not assignable to type 'S'.
```

**Playground Link:** 

[Link](http://www.typescriptlang.org/play/#src=type%20S%20%3D%20'a'%20%7C%20'b'%3B%0D%0A%0D%0Ainterface%20Typed%20%7B%20%0D%0A%20%20%20%20nested%3A%20S%3B%0D%0A%7D%0D%0A%0D%0Aconst%20checker%20%3D%20(a%3A%20Typed)%20%3D%3E%20%7B%20%7D%3B%0D%0A%0D%0Aconst%20obj%20%3D%20%7B%20nested%3A%20'a'%20%7D%3B%0D%0A%0D%0Achecker(obj)%3B%0D%0Achecker(%7Bnested%3A%20'a'%7D))

**Comment by ahejlsberg** [comment]
This is working as intended. When inferring a type for a mutable location (such as a property in an object literal), we widen literal types to their base primitive type unless there is a _contextual type_ to indicate you want them preserved. In the `const` declaration for `obj` there is no contextual type for the object literal, so we widen. However, in the call expression, the parameter type serves as a contextual type that causes us to preserve the literal type.

You can observe the difference by adding a type annotation to the `const` declaration for `obj`:

```ts
const obj: Typed = { nested: 'a' };
```

This provides a contextual type that causes us to preserve the literal type.

**Comment by AlexPikalov** [comment]
@ahejlsberg 

Thanks for your clarification. Basically adding a context via type annotation is exactly how I solved this issue in my project.

I supposed that it may be working as intended, but wasn't 100% sure because in case of "not nested" string types it works in a both ways.

```typescript
type S = 'a' | 'b';

const checker = (x: S) => { };

const arg = 'a';

checker(arg);
checker('a');
```
Would you be able please to explain what is type transformation logic in an example above?
