### ISSUE TITLE
Hande CouchDB JavaScript functions that use top level anonymous function

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/TypeScript#28735]
- VSCode Version: 1.29.1
- OS Version: macOS 10.14.1

CouchDB views use a top level anonymous functions. When you save those as a file and try to edit them using VS Code, it will fail to parse it with an "Identifier expected" diagnostic. This probably disables the JavaScript language features for such files.

Steps to Reproduce:
1. Create a JS file like this:
```js
function(doc) {
    if (doc.name) {
        emit(doc.name);
    }
}
```
2. VS Code will error with "Identifier expected" on such a file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
That is not valid javascript. It would be an error if you are not using CouchDB

**Comment by segevfiner** [comment]
> That is not valid javascript. It would be an error if you are not using CouchDB

Yeah, I know. I'm not sure how CouchDB parses this so that it is valid in it's context...

**Comment by weswigham** [comment]
Yeah - that's just not valid JS. I guess couchdb is probably concatenating to the input to force it to be evaluated as an expression, but that's in no way standard. You can at least contain the strangeness to only your query entrypoint file by making use of couchdb's commonjs module support to put your heavyweight code into a separate, more normal file.
