### ISSUE TITLE
Module exports not overriding when exporting same function from multiple modules

### ISSUE THREAD

**Issue by arahansen** [microsoft/TypeScript#28741]
My understanding of es6 modules is that overriding exports is supported as described below. TypeScript appears to only be using the first export, and ignoring additional exports. Is this intended behavior?

**Search Terms:**
- duplicate exports
- override exports

**Code**

```ts
// index.ts
import { myFunc } from "./combined";

myFunc();

// combined.ts
export * from "./moduleA";
export * from "./moduleB";

// moduleA.ts
export function myFunc() {
  console.log("this came from module A");
}

// moduleB.ts
export function myFunc() {
  console.log("this came from module B");
}
```

**Expected behavior:**
`myFunc()` will log "This came from module B"

**Actual behavior:**
`myFunc()` logs "This came from module A"

**Playground Link:** 
https://codesandbox.io/s/43wmw0o3p0

**Related Issues:** 
Could not find anything related.

**Comment by weswigham** [comment]
Actually, it should be an error - when more than one `*` export resolves the same name, accessing that name results in an error. AFAIK we have an error for this:

![image](https://user-images.githubusercontent.com/2932786/49309383-db353c80-f48f-11e8-854f-1f9b1a2bcd31.png)
