### ISSUE TITLE
Broken download link for 3.2.1 on https://www.microsoft.com/en-us/download/details.aspx?id=48593

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/TypeScript#28759]
The "TypeScript for Visual Studio 2015" download page (https://www.microsoft.com/en-us/download/details.aspx?id=48593) has a download link for 3.2.1

TypeScript 3.2.1 for Visual Studio 2015 — November 29, 2018 (release notes)[Download]

The Download link points to http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/3.2.1-TS-release-dev14-update3-20181129.3/TypeScript_Dev14Full.exe which doesn't exist

**Comment by minestarks** [comment]
I'm looking into it. Will restore the link shortly

**Comment by minestarks** [comment]
@flcdrg fixed! Sorry about that.
