### ISSUE TITLE
[bug?] Cannot find name 'EventEmitter', property 'channel' of exported interface has or is using private name 'EventEmitter'.

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#28754]
**TypeScript Version:**  3.3.0-dev.20181129

**Search Terms:**

The search results led to issues like this one: https://github.com/Microsoft/TypeScript/issues/6307

**Code**

```ts
// ./Events.ts
class EventTypes {
  constructor(
    public SOME_EVENT: any,
    public OTHER_EVENT: any,
  ) {}
}

export const Events = {} as { [k in keyof EventTypes]: k }

for (const key in new (EventTypes as any)) {
    Events[key] = key
}

import * as events from 'events' // definitions are from `@types/node`

// our own (better, more type-safe) definition of EventEmitter
interface BetterEventEmitter<EventTypes> {
  new(): BetterEventEmitter<EventTypes>
  addListener<EventName extends keyof EventTypes> (event: EventName, listener: (arg: EventTypes[EventName]) => void);
  on<EventName extends keyof EventTypes> (event: EventName, listener: (arg: EventTypes[EventName]) => void);
  once<EventName extends keyof EventTypes> (event: EventName, listener: (arg: EventTypes[EventName]) => void);
  removeListener<EventName extends keyof EventTypes> (event: EventName, listener: (arg: EventTypes[EventName]) => void);
  removeAllListeners<EventName extends keyof EventTypes>(event?: EventName): this;
  emit<EventName extends keyof EventTypes>(event: EventName, arg: EventTypes[EventName]): boolean;
  eventNames<EventName extends keyof EventTypes>(): Array<EventName>;
  setMaxListeners(n: number): this;
  getMaxListeners(): number;
  listeners<EventName extends keyof EventTypes>(event: EventName): (arg: EventTypes[EventName]) => void[];
  listenerCount<EventName extends keyof EventTypes>(type: EventName): number;
  prependListener<EventName extends keyof EventTypes>(event: EventName, listener: (arg: EventTypes[EventName]) => void): this;
  prependOnceListener<EventName extends keyof EventTypes>(event: EventName, listener: (arg: EventTypes[EventName]) => void): this;
}

// override Node EventEmitter with our definition
export const EventEmitter = events.EventEmitter as unknown as BetterEventEmitter<EventTypes>
```

```js
// consumer.ts
import { Events, EventEmitter } from './models/Events' // ERROR: `EventEmitter` is declared but its value is never read.

const channel = new EventEmitter // works fine, no error!

class Foo {
  channel: EventEmitter // ERROR, Cannot find name 'EventEmitter'
}

export interface Bar {
  channel: EventEmitter // ERROR, Cannot find name 'EventEmitter', property 'channel' of exported interface has or is using private name 'EventEmitter'.
}
```

**Expected behavior:**

I expect not to get the `ERROR`s I've marked in the above comments.

**Actual behavior:**

I'm getting those errors.

**Playground Link:** 

I can't put multiple files in Playground or install dependencies.

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/6307

**Comment by trusktr** [comment]
(My `tsconfig` includes `    "declaration": true`)

**Comment by weswigham** [comment]
You
```ts
export const EventEmitter
```
but you also need to export a type named `EventEmitter` if you want to reference one as such.

**Comment by trusktr** [comment]
Ah I see, yep it works. It's not so intuitive though. Isn't it obvious that I'm exporting a constructor (therefore a type)? Seems like the compiler should be able to pick that up.

**Comment by trusktr** [comment]
I'll close this though, as that's indeed how to make it work, but curious what you think about the compiler being able to detect that I'm exporting a constructor (and therefore a type).

**Comment by trusktr** [comment]
This declaration stuff is funky. I'm on typescript `3.3.0-dev.20181129`.

Now that I fixed that problem by adding the export of the type, not just the runtime value, I now have an error in another file:

> Parameter 'channel' of constructor from exported class has or is using name 'BetterEventEmitter' from external module "/path/to/Events.ts" but cannot be named.

Looks like maybe https://github.com/Microsoft/TypeScript/issues/9944 is not fixed.

However, this only happens to me in one file, but I can't reproduce it in another file. So something is weird here.

**Comment by trusktr** [comment]
I was able to fix the previous comment's error by changing

```ts
interface BetterEventEmitter<EventTypes> {
```

to 

```ts
export interface BetterEventEmitter<EventTypes> {
```

but I shouldn't have to do that, I'm not importing that name anywhere, it is only ever used in the definition of what `EventEmitter` is.

**Comment by weswigham** [comment]
Use `export { BetterEventEmitter as EventEmitter }` instead of `export type EventEmitter = BetterEventEmitter` - the first establishes a usable alias, while due to some design limitations, the second isn't something we usually can locate for declaration emit.

**Comment by trusktr** [comment]
It's hard to understand why, as with my eyes I can locate it just fine. Thanks for that tip!
