### ISSUE TITLE
Missing Type_0_is_not_assignable_to_type_1 on variable declaration

### ISSUE THREAD

**Issue by bigaru** [Microsoft/TypeScript#28767]
**TypeScript Version:**  3.3.0

**Search Terms:**
variable declaration error code Type_0_is_not_assignable_to_type_1

**Code:**
```ts
interface foo { a: string }
let bar: foo = {}
```
I'm currenlty working on the issue #16755. For that issue I make use of following error codes:
* `Type_0_is_not_assignable_to_type_1`
* `Argument_of_type_0_is_not_assignable_to_parameter_of_type_1`

But since the PR #28298 the error code `Type_0_is_not_assignable_to_type_1` doesn't appear anymore. It seems that the PR has accidentally changed this behavior.

**Expected behavior:**
```ts
interface foo { a: string }
let bar: foo = {}     //Type '{}' is not assignable to type 'foo'.
```

**Actual behavior:**
missing the error code `Type_0_is_not_assignable_to_type_1`

**Playground Link:**
http://www.typescriptlang.org/play/index.html#src=interface%20foo%20%7B%20a%3A%20string%20%7D%0D%0Alet%20bar%3A%20foo%20%3D%20%7B%7D%09%2F%2F%20Type%20'%7B%7D'%20is%20not%20assignable%20to%20type%20'foo'.

**Related Issues:**

**Comment by weswigham** [comment]
Yah, we replaced it with the more specific `Property 'a' is missing in type '{}' but required in type 'foo'.` message (and there's some other new ones for other scenarios). If you must rely on errors and error codes, be ready to update as we do, because we in no way guarantee that what's an error today will be the same error tomorrow (we reserve the freedom to remove of improve errors).

**Comment by bigaru** [comment]
As I started developing the quick-fix, I tried different error codes out. As a result, I found out that a quick-fix can only be triggered by some error codes. In my case the quick-fix cannot be triggered by `Property_0_is_missing_in_type_1`. That's why I decided to use following error codes: 
* `Type_0_is_not_assignable_to_type_1`
* `Argument_of_type_0_is_not_assignable_to_parameter_of_type_1`

After the PR #28298 the Property error message was replaced with more specific messages (as shown below). The error message `Type_0_is_not_assignable...` stopped to appear. Since the error message `Argument_of_type_0_...` still appears, it felt strange to me. That's why I thought it might have happened accidentally.

I even tried with the new error codes, but my quick-fix cannot be triggered with the new error messages. I do not insist on the old error message. However, I am not really sure if this was a deliberate decision. If it was a deliberate decision, I am happy if someone could show me how the new error codes can be used to trigger a quick-fix.

### available error messages before PR
```ts
interface One { a: number }
interface Two { a: number, b: boolean }
function FnWithOne(arg: One) {}
function FnWithTwo(arg: Two) {}

let foo: One = {}
/* 
 * Type '{}' is not assignable to type 'One'.
 * Property 'a' is missing in type '{}'.
 */

let bar: Two = {}
/* 
 * Type '{}' is not assignable to type 'Two'.
 * Property 'a' is missing in type '{}'.
 */

FnWithOne({})
/* 
 * Argument of type '{}' is not assignable to parameter of type 'One'.
 * Property 'a' is missing in type '{}'.
 */

FnWithTwo({})
/*
 * Argument of type '{}' is not assignable to parameter of type 'Two'.
 * Property 'a' is missing in type '{}'.
 */
```
### available error messages after PR
```ts
interface One { a: number }
interface Two { a: number, b: boolean }
function FnWithOne(arg: One) {}
function FnWithTwo(arg: Two) {}

let foo: One = {};
/* 
 * ---
 * Property 'a' is missing in type '{}' but required in type 'One'.
 */

let bar: Two = {}
/* 
 * ---
 * Type '{}' is missing the following properties from type 'Two': a, b
 */

FnWithOne({})
/* 
 * Argument of type '{}' is not assignable to parameter of type 'One'.
 * Property 'a' is missing in type '{}' but required in type 'One'.
 */

FnWithTwo({})
/*
 * Argument of type '{}' is not assignable to parameter of type 'Two'.
 * Type '{}' is missing the following properties from type 'Two': a, b
 */
```
