### ISSUE TITLE
Path mapping breaks 'forceConsistentCasingInFileNames' option

### ISSUE THREAD

**Issue by mbrowne** [Microsoft/TypeScript#28769]
**TypeScript Version:**  3.3.0-dev.20181130

**Search Terms:**
"differs from already included file name"

**Details:**

If you use are using a path mapping option and also have `forceConsistentCasingInFileNames` set to `true` in `tsconfig.json`, then if you are using TypeScript with the default watch behavior for create-react-app-typescript, changing any source file can trigger an error like the following:

> File name '/Users/mbrowne/_temp/ts-issue/src/shared/theme.ts' differs from already included file name '/users/mbrowne/_temp/ts-issue/src/shared/theme.ts' only in casing

Note how the only part that differs in casing is the path to the project itself.

**Expected behavior:**

Demo repository showing the issue:
https://github.com/mbrowne/typescript-issue-repro

With a path mapping set up to recognize `~`, it should be possible to use these two imports in two different files and the code should recompile successfully when changed:

https://github.com/mbrowne/typescript-issue-repro/blob/master/src/shared/App.tsx:
`import * as theme from './theme'`

https://github.com/mbrowne/typescript-issue-repro/blob/master/src/shared/pages/NotFound.tsx:
`import * as theme from '~/theme'`

Note: My demo repo probably contains some things that are irrelevant, but I tried to make it as minimal as possible. (I initially tried to make it even more minimal but wasn't able to reproduce the issue.)

**Actual behavior:**

Initial compilation is successful, but when you change any file in `src/shared`, the following error occurs:

> Failed to compile.
>
> /users/mbrowne/_temp/ts-issue/src/shared/pages/NotFound.tsx
> (4,24): File name '/Users/mbrowne/_temp/ts-issue/src/shared/theme.ts' differs from already included file name '/users/mbrowne/_temp/ts-issue/src/shared/theme.ts' only in casing.

**Debugging Info:**

I did some debugging in `node_modules/typescript/lib/typescript.js` and was able to find the cause of the issue, although I'm not sure of the correct way to fix it. It seems the issue is caused by some recent changes to src/compiler/program.ts, specifically the introduction of the `file.originalFileName` property:
https://github.com/Microsoft/TypeScript/blob/8d5d9005679901d3e68e63b970fe44ac2ab8c0f6/src/compiler/program.ts#L2292

When I replaced all references to `file.originalFileName` with `file.fileName` (for example [this one](https://github.com/Microsoft/TypeScript/blob/8d5d9005679901d3e68e63b970fe44ac2ab8c0f6/src/compiler/program.ts#L2437)), it started working correctly again—that is, I could once again change the source files and it would recompile successfully.

**Related Issues:** 

https://github.com/TypeStrong/ts-node/issues/728 looks similar, so perhaps has the same cause.

**Comment by sheetalkamat** [comment]
@mbrowne Can you please let me know if I am missing some steps since I am not able to repro this.
Here are the steps I did

1. Clone repo
2. npm I
3. npm run build
4. edited src/shared/environment.ts to add `export const x = 10;`
5. npm run build
I do not get any error and see this:
```
ts-loader: Using typescript@3.3.0-dev.20181130 and c:\temp\typescript-issue-repro\tsconfig.json
no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
Compiled successfully.
```

**Comment by mbrowne** [comment]
Ah, I thought it would happen when editing any file but apparently editing environment.ts doesn't trigger it. If you edit src/shared/App.tsx or src/shared/pages/NotFound.tsx you should be able to reproduce it, even just by adding an empty line.

But I'm glad you mentioned the warning about the TSLint `no-unused-variable` rule...that is expected behavior for our app since we're currently still relying on that rule (it allows for easier development while still enforcing this rule as an error in our pre-commit hook). I was going to remove it just now for the purposes of the demo repo and then discovered that the issue doesn't happen without it! I tried using the `no-unused` from [tslint-consistent-codestyle](https://github.com/ajafff/tslint-consistent-codestyle) as an alternative and it works fine, so I think we will switch to that.

So I'm no longer sure if this is a TS issue or just a TSLint issue, but I do know that the actual compiler error that ultimately caused the build to fail was coming from `node_modules/typescript/lib/typescript.js` as I described above.

**Comment by ajafff** [comment]
`no-unused-variable` messes with compiler internals and modifies the state of immutable data structures. There's nothing TypeScript can do about that.

**Comment by mbrowne** [comment]
Ah ok, that must be why they deprecated it - thanks.
