### ISSUE TITLE
Contextual type assertion operator

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#2876]
A contextual type assertion expression, `<?>`, is like a regular type assertion (e.g. `<string>`), but asserts to the contextual type of the expression.

About half of all type assertions can be rewritten this way with no loss of type safety.

Example:
```ts
declare function setDivText(div: HTMLDivElement): void;

// Error
setDivText(document.getElementById('myDiv'));
// OK, but a lot of typing
setDivText(<HTMLDivElement>document.getElementById('myDiv'));
// OK and easy
setDivText(<?>document.getElementById('myDiv'));
```

It is an error to use a contextual assertion when no contextual type exists:
```ts
<?>foo; // Error
var x: number = <?>foo; // OK
```

This should nearly eliminate assertions to `<any>` due to people not wanting to type out large type literals.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/compare/master...RyanCavanaugh:contextualAssert

**Comment by benjamin-hg** [comment]
So in contrast to `<any>`, `<?>` would just narrow down the type to the required derived type?

    setDivText(<?>"not a super type of HTMLDivElement"); // expected to fail

**Comment by RyanCavanaugh** [comment]
Correct

**Comment by stephanedr** [comment]
Instead of `<...>`, I often use a function which checks the object is really of the expected type.
So:
```
function cast<T>(type: { new (...args: any[]): T }, object: Object): T { ... }
setDivText(cast(HTMLDivElement, document.getElementById('myDiv')));
```
I would be really interested in using your `<?>` shortcut, but I don't see how I can in the context of an intermediate function call.
Ideally I would like to write something like:
```
setDivText(cast(?, document.getElementById('myDiv')));
setDivText(autocast(document.getElementById('myDiv')));
```
`autocast()` would have access to the contextual target type, but also its constructor to be able to use `instanceof`.

**Comment by RyanCavanaugh** [comment]
Function arguments are contextually typed by the corresponding parameter types, so `setDivText(<?>someElement);` would work (assuming `function setDivText(x: HTMLDivElement)`, of course)

**Comment by paulvanbrenk** [comment]
:+1:

**Comment by stephanedr** [comment]
Indeed, but my case is different.
I want to go through an intermediate function to confirm `someElement` is really of type `HTMLDivElement`.
Today I would use `setDivText(cast(HTMLDivElement, someElement));`

I would like to be able to perform the same, but without mentioning the corresponding parameter type.
Something like:
```
setDivText(cast(?, document.getElementById('myDiv')));
setDivText(autocast(document.getElementById('myDiv')));
```

**Comment by Griffork** [comment]
:+1: for <?>
Perfect solution for a frustration I had.

**Comment by RyanCavanaugh** [comment]
General take on this was that users are unlikely to be able to correctly reason about what this operator is doing (given that most people don't work on compilers all day like I do :smiley: ).

Some better solution for an "automatic downcast" would be neat, but it's hard to imagine what that would be.
