### ISSUE TITLE
Extending a class using interface and ES6 Proxy

### ISSUE THREAD

**Issue by JimmyPruitt** [microsoft/TypeScript#28776]
I checked the FAQ and didn't see anything related to this problem and didn't find anything I thought looked related. I'll admit that the code snippet below doesn't come from a place of _complete_ comprehension of Typescript and inheritance, so it's possible that a language feature exists I'm not aware of, but as it stands I can't get my code to compile.

**Search Terms:**
- `typescript es6 proxy interface`
- `typescript interface missing property`

**Code**

```ts
interface IArrayProxy<T> extends Array<T> {}

// @ts-ignore I'm okay with needing this because the case is somewhat exceptional
class ArrayProxy<T> implements IArrayProxy<T> {
  constructor(protected array: T[]) {
    return new Proxy(this, this);
  }

  public get(target: any, prop: string) {
    return this.hasOwnProperty(prop) ? this[prop] : this.array[prop];
  }

  // More functions below
}

const arrayProxy = new ArrayProxy([]);
console.log(arrayProxy['length']); // <--- Compiles and gives desired output
console.log(arrayProxy.length); // <-- Gives desired output but doesn't compile
```

**Expected behavior:** The entire block compiles and runs correctly

**Actual behavior:** The block doesn't compile because of the final line

**Playground Link:** [link to playground](http://www.typescriptlang.org/play/#src=interface%20IArrayProxy%3CT%3E%20extends%20Array%3CT%3E%20%7B%20%7D%0D%0A%0D%0A%2F%2F%20%40ts-ignore%0D%0Aclass%20ArrayProxy%3CT%3E%20implements%20IArrayProxy%3CT%3E%20%7B%0D%0A%20%20constructor(protected%20array%3A%20T%5B%5D)%20%7B%0D%0A%20%20%20%20return%20new%20Proxy(this%2C%20this)%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20get(target%3A%20any%2C%20prop%3A%20string)%20%7B%0D%0A%20%20%20%20return%20this.hasOwnProperty(prop)%20%3F%20this%5Bprop%5D%20%3A%20this.array%5Bprop%5D%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20%2F%2F%20More%20functions%20below%0D%0A%7D%0D%0A%0D%0Aconst%20arrayProxy%20%3D%20new%20ArrayProxy(%5B%5D)%3B%0D%0Aconsole.log(arrayProxy%5B'length'%5D)%3B%0D%0Aconsole.log(arrayProxy.length)%3B)

**Related Issues:** N/A

**Comment by weswigham** [comment]
Have you considered adding `extends Array<T>` to the class and a `super()` call in the constructor before constructing and returning the proxy? The issue is simply that, unlike `extends`, `implements` doesn't actually mixin the members from the implementing type into the new type - it just asserts that they _are_ implemented (which is the error you're suppressing). By using `extends` instead, you get the properties mixed in, and you no longer need the ts-ignore.

**Comment by JimmyPruitt** [comment]
So if I change it to
```ts
class ArrayProxy<T> extends Array<T> {
  constructor(protected array: T[]) {
    super(...array);

    this.customFunction();
  }

  customFunction() {}

  // More functions below
}

const arrayProxy = new ArrayProxy([]);
```

I get an exception:
> VM100:19 Uncaught TypeError: _this.customFunction is not a function
    at new ArrayProxy (<anonymous>:19:15)
    at <anonymous>:25:18
    at HTMLButtonElement.excuteButton.onclick (http://www.typescriptlang.org/play/playground.js:247)

**Comment by weswigham** [comment]
Naw naw, I mean still using the proxy, along the lines of
```ts
class ArrayProxy<T> extends Array<T> {
  constructor(protected array: T[]) {
    super();
    return new Proxy(this, this);
  }

  public get(target: any, prop: string) {
    return this.hasOwnProperty(prop) ? this[prop] : this.array[prop];
  }

  // More functions below
}

const arrayProxy = new ArrayProxy([]);
console.log(arrayProxy['length']); // <--- Compiles and gives desired output
console.log(arrayProxy.length); // <-- Gives desired output but doesn't compile
```

**Comment by JimmyPruitt** [comment]
Yeah sorry this was a follow up question. I used a reduced example to illustrate what I thought was the problem but I need to call instance functions from inside the constructor. Returning a proxy or not wouldn't change that. My actual use case is more akin to 
```ts
class ArrayProxy<T> extends Array<T> {
  constructor(protected array: T[]) {
    super();
    this.customFunction();
    return new Proxy(this, this);
  }

  public get(target: any, prop: string) {
    return this.hasOwnProperty(prop) ? this[prop] : this.array[prop];
  }

  public customFunction() {}

  // More functions below
}

const arrayProxy = new ArrayProxy([]);
console.log(arrayProxy['length']); // <--- Compiles and gives desired output
console.log(arrayProxy.length); // <-- Gives desired output but doesn't compile

```

**Comment by weswigham** [comment]
Mmmm... I think that might be because our downlevel emit doesn't work for extending builtins (although since you're using proxies you should be targeting es6 anyway and not be downleveling classes).

**Comment by JimmyPruitt** [comment]
Oh I didn't notice the Playground wasn't targeting ES6. Is there a way to change it? I only see a couple compiler options and `target` ain't one of them.

**Comment by weswigham** [comment]
Not right now, no. :( Our playground is missing a lot of features we wish it had.

**Comment by JimmyPruitt** [comment]
And I assume there aren't any workarounds for extending builtins when downleveling (and not using ES6 features)?

**Comment by weswigham** [comment]
The core of the issue with builtins downlevel is that a super call translates to `_super.apply(this, otherArg)` where `_super` is, eg `Array`. Unfortunately, Array, Error, and friends don't respect the `this` passed in when called and ignore it (not being sure how to allocate the backing runtime object for an arbitrary js object). It's not really fixable downlevel, since, at best, you ignore what the super constructor returns and hope it's not important - but that causes other problems with other valid code.

**Comment by JimmyPruitt** [comment]
Okie doke. Thanks for your help.
