### ISSUE TITLE
Auto import in angular typescript is not working

### ISSUE THREAD

**Issue by micobarac** [microsoft/TypeScript#28773]
- VSCode Version:
Version 1.29.1
Typescript 3.1.4

- OS Version:
macOS 10.14.1 

Steps to Reproduce:

1. Create new angular app:
`ng new app`

2. Add new library:
`yarn add @datorama/akita`

3. Create session.model.ts:
```typescript
export interface Session {
  id: ID;
  firstName: string;
  lastName: string;
  token: string;
}
```
Auto import is not working. I get this error:

```
[ts] Cannot find name 'ID'. [2304]
any
```

Starting VSCode with `code --disable-extensions` didn't help :(

**Comment by mjbvz** [comment]
I confirmed this by using TS 3.3.0-dev20181130.

The `index.d.ts` from `akita` has `export * from './api/types';` which has an `ID` type. I see this error after trying to open the `api/types` file directly:

```
Err 403   [11:12:21.819] Exception on executing command {"seq":65,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/matb/projects/san/node_modules/@datorama/akita/src/api/types.d.ts","startLine":1,"startOffset":1,"endLine":1,"endOffset":1}}:

    Could not find file: '/Users/matb/projects/san/node_modules/@datorama/akita/src/api/types.d.ts'.

    Error: Could not find file: '/Users/matb/projects/san/node_modules/@datorama/akita/src/api/types.d.ts'.
        at getValidSourceFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117240:23)
        at Object.getApplicableRefactors (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118017:24)
        at IOSession.Session.getApplicableRefactors (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125638:53)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:124512:61)
        at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125857:88
        at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125848:28)
        at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125857:33)
        at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125879:35)
        at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:127139:27)
        at emitOne (events.js:116:13)
        at Interface.emit (events.js:211:7)
        at Interface._onLine (readline.js:282:10)
        at Interface._normalWrite (readline.js:424:12)
        at Socket.ondata (readline.js:141:10)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:250:11)
        at Socket.Readable.push (_stream_readable.js:208:10)
        at Pipe.onread (net.js:594:20)
```

**Comment by sheetalkamat** [comment]
@mjbvz I don't get that exception. Note that when I create app and add that library it is not included in the project (because its not referenced from anywhere and hence completion wont show up for it as we only look for symbols in files included in the program). Opening the types.d.ts doesn't throw any expression. If I add `import a from "@datorama/akita"` to my test file, then it correctly shows `ID` in the completion list doing auto import if selected.

**Comment by sheetalkamat** [comment]
@mjbvz I am seeing the exceptions with that call stack when there is ordering mismatch in sending the requests from code-insiders. I was looking into  #28389 this and I noticed that exception and log is:
```
Info 100  [14:57:17.992] request:
    {"seq":15,"type":"request","command":"close","arguments":{"file":"c:/temp/o2sql/lib/ast-translator.js"}}
Info 115  [14:57:17.992] request:
    {"seq":16,"type":"request","command":"getApplicableRefactors","arguments":{"file":"c:/temp/o2sql/lib/ast-translator.js","startLine":16,"startOffset":32,"endLine":16,"endOffset":32}}
```

**Comment by mjbvz** [comment]
@sheetalkamat I can't repo the exception anymore on latest `@next`.

I still don't get quick fix though in a simple ts file though because `@datorama/akita` can't be resolved:

```ts
import a from '@datorama/akita'

ID;
```

[tsserver.log](https://github.com/Microsoft/TypeScript/files/2641439/tsserver.log)

And shouldn't imports quick fixes pick up the`ID`  type from the module even without import?

**Comment by mjbvz** [comment]
Even once the  import is resolved though, the quick fix still doesn't work for `ID`

**Comment by mjbvz** [comment]
Man, i should stop trying to repo this bug. Yes that was the issue.

Going back to the original repo steps:

* Everything works for me on TS 3.2.1, provided you have a tsconfig (which ng should create)
* Without a tsconfig, no quick fix. Most user are going to have a tsconfig but this seems like a bug to me

**Comment by micobarac** [comment]
The same problem occurs even when I try to import some `Angular modules`. For instance, if I want to autoimport `OverlayModule` from `@angular/cdk`, autoimport is not giving any suggestions either :(.

**Comment by ChristopherKiss** [comment]
I'm having the same issue for Angular Material.

```
import { NgModule } from '@angular/core';

const modules = [MatButtonModule, MatToolbarModule, MatSidenavModule];

@NgModule({
    declarations: [],
    imports: modules,
    exports: modules,
    providers: []
})
export class MaterialModule {}
```

The suggestion for `MatSidenavModule` and the other 2 modules never show up, no light bulb either.

**Comment by micobarac** [comment]
This is still not working, even with the latest VSCode version :(

**Comment by sheetalkamat** [comment]
@RyanCavanaugh @DanielRosenwasser This shouldn't be a bug but working as intended? WIthout the files being included in the project how can we know the symbol 'ID' is from `@datorama/akita` to offer it?

**Comment by smx-smx** [comment]
Is it possible to force tsserver to lookup all files up-front?

If i'm using a lot of dependencies, or a large project with many dependencies, i would prefer to have tsserver scan all files up-front, so i don't have to find where every symbol is defined every time.

As a user, i could choose between
- performance (i know where symbols are, i am going to do a few imports only)
- completeness (i can accept an initial performance tradeoff to get more pertinent results)

I can see how doing this by default would make the process slower, so could this be an opt-in setting that forces tsserver to parse all files up-front eagerly? (user be warned: 'it will be slow', or something among those lines)

Thank you
