### ISSUE TITLE
docCommentTemplate not returned for assigned method in class

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#28786]
From https://github.com/Microsoft/vscode/issues/64097

**TypeScript Version:**  3.3.0-dev.20181130

**Search Terms:**
- DocCommentTemplate

**Code**
In the js file:

```js
export default class abc {
    /** */
    myfunc = (myparam) => {
        return myparam;
    }
}
```

Trigger a `docCommentTemplate` server request inside the comment.

**Expected behavior:**
Comment template returned

**Actual behavior:**
`No content available.` returned

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
This is a property declaration, which is not supported yet in JS. That might be the reason it fails to give the comment.

**Comment by mjbvz** [comment]
Looks like our IntelliSense understands this pattern (even if not all runtimes support it). Any more feedback needed?

**Comment by sandersn** [comment]
The owner of the comment is incorrectly identified as the containing class &mdash; getCommentInfo doesn't even handle property declarations.
