### ISSUE TITLE
Visual Studio - Format on Enter no longer removes extra whitespace

### ISSUE THREAD

**Issue by jessetrinity** [Microsoft/TypeScript#28781]
**TypeScript Version:**
typescript@3.3.0-dev.20181130

**Search Terms:**
formatting whitespace

**Expected behavior:**
Format on Enter previously removed extra whitespace inserted *after* the indentation on the empty line below **var bar;**. Caret represents the termination of whitespace on the previous line.
```
function foo()
{
    var bar;
    
    ^
}
```
**Actual behavior:**

Format on Enter no longer removes extra whitespace.
```
function foo()
{
    var bar;
        
        ^
}
```
Similar behavior is observed for non-empty lines.
**Expected:**
```
var foo;
        ^
``` 
**Actual:**
```
var foo;     
            ^
```

**Related Issues:** 
Introduced by #27978

**Comment by minestarks** [comment]
@sandersn This is blocking our tests and I believe it exists in 3.2 which will ship with VS. My understanding is it causes a visible formatting issue in VS. Would you prioritize it accordingly?

**Comment by sandersn** [comment]
Here's a fourslash repro:


```ts
/// <reference path="fourslash.ts" />
////function foo()
////{
////    var bar;
////    /*1*/
////}
goTo.marker('1')
edit.insertLine("");
verify.currentFileContentIs(`function foo()
{
    var bar;


}`);
```

The two whitespace-only lines should both have 0 spaces. After #27978 merged, the first one still has 4 spaces.

**Comment by sandersn** [comment]
Selectively reverting #27978 shows that the regression was introduced by the change in trimTrailingWhitespacesForRemainingRange.
