### ISSUE TITLE
Add an error when doing Refactor->Rename on a lib.d.ts value

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#2878]
Do a Refactor->Rename on some identifier defined in lib.d.ts. Ideally you'd get an error that this isn't allowed and why. I think we used to have an error to this effect. Now we just pop up a Save As dialog to try to save lib.d.ts elsewhere since it's marked read only.

**Comment by mhegazy** [comment]
@jramsay fixed this already... it should give you  "Error 8001: You cannot rename elements that are defined in the standard TypeScript library."

**Comment by danquirk** [comment]
I tried it in the latest RC build and saw no such error.

**Comment by mhegazy** [comment]
marking as bug for now to ensure the fix makes it to the next release.

**Comment by DickvdBrink** [comment]
For Reference the PR wit the error handeling is this one #1990
