### ISSUE TITLE
Regression in type inference for Promise.all()

### ISSUE THREAD

**Issue by Tatamo** [Microsoft/TypeScript#28792]
**TypeScript Version:**  3.2.1 & 3.3.0-dev.20181201

**Search Terms:**
type inference, promise, tuple

**Code**

```ts
async function f(x: number): Promise<number>{
    return x + 1;
}

async function g(s: string): Promise<string>{
    return s + "\n";
}

async function h(): Promise<string> {
    const [a, b] = await Promise.all([f(1), g("x")]).catch(() => [null, null]);
    if (a === null || b === null) throw new Error();
    return b.trim();
}
```

**Expected behavior:**
no compile error, as in TS3.1

**Actual behavior:**
```
test.ts:12:12 - error TS2339: Property 'trim' does not exist on type 'string | number'.
  Property 'trim' does not exist on type 'number'.

12   return b.trim();
              ~~~~

```

In TS3.1:
```
a: number | null
b: string | null
```

In TS3.2:
```
a: string | number | null
b: string | number | null
```

**Playground Link:** 
[here](http://www.typescriptlang.org/play/#src=async%20function%20f(x%3A%20number)%3A%20Promise%3Cnumber%3E%7B%0D%0A%20%20%20%20return%20x%20%2B%201%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20g(s%3A%20string)%3A%20Promise%3Cstring%3E%7B%0D%0A%20%20%20%20return%20s%20%2B%20%22%5Cn%22%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20h()%3A%20Promise%3Cstring%3E%20%7B%0D%0A%20%20%20%20const%20%5Ba%2C%20b%5D%20%3D%20await%20Promise.all(%5Bf(1)%2C%20g(%22x%22)%5D).catch(()%20%3D%3E%20%5Bnull%2C%20null%5D)%3B%0D%0A%20%20%20%20if%20(a%20%3D%3D%3D%20null%20%7C%7C%20b%20%3D%3D%3D%20null)%20throw%20new%20Error()%3B%0D%0A%20%20%20%20return%20b.trim()%3B%0D%0A%7D%0D%0A)
(Enable strictNullChecks to reproduce it)

**Related Issues:**

**Comment by Tatamo** [comment]
It looks like the problem of destructuring assignment with an union between tuple and null[] types.
simplified code:
```ts
function f(): [number, string] | null[] { // when using [null, null] instead of null[], it works properly
    return Math.random() < 0.5 ? [1, "x"] : [null, null];
}

const [a, b] = f(); // a:string|number|null, b:string|number|null
```

**Comment by weswigham** [comment]
cc @DanielRosenwasser
