### ISSUE TITLE
typedef downleveling to use with typesVersions

### ISSUE THREAD

**Issue by mikehaas763** [microsoft/TypeScript#28797]
## Search Terms

typedef
downleveling
typesVersions

## Suggestion

@RyanCavanaugh mentioned in https://github.com/Microsoft/TypeScript/issues/22605#issuecomment-379007218 regarding the `typesVersion` feature for typedef files that he "would expect these files to be either hand-created, or generated through some downleveling process". I think it'd be a great addition if the compiler would optionally emit the typedef files for any versions specified. I _really_ don't want to manage my typedef files by hand. 🙂 

## Examples

For example, using `tsc --build --downlevel-version 2.8` with typescript 3.1 would emit something like this dir structure

```
index.d.ts
ts3.0/index.d.ts
ts2.9/index.d.ts
ts2.8/index.d.ts
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dball-adashi** [comment]
I personally would like this change to be practically transparent and instantly applied.   I had not found all of these suggestions when I suggested the following:  #31907

**Comment by RyanCavanaugh** [comment]
We've created `downlevel-dts`, which is as far as we intend to go in this space.
