### ISSUE TITLE
Spread operator function arguments (regression)

### ISSUE THREAD

**Issue by sheley1998** [Microsoft/TypeScript#28794]
**TypeScript Version:**  3.2.1

**Search Terms:** spread, arguments

**Code**

```ts
function test(a: number, b: number, c: number, d: number) {
    console.log(a, b, c, d);
}

const nums = [0, 1, 2, 3];

test(...nums);
```

**Expected behavior:**
the snippet above should compile without error

**Actual behavior:**
Error TS2556: Expected 4 arguments, but got 0 or more

**Comment by ahejlsberg** [comment]
This is working as intended and is not a regression. We infer type `number[]` for `nums` and therefore we have to assume that the array may have as few as zero elements. It would be nice to infer a tuple type, but the reality is that arrays are mutable (the only thing that is `const` in the example is the array reference--the contents of the array are not). There are many similar issues already logged, e.g. #28336, #20899, #16389, #3369.

**Comment by sheley1998** [comment]
Thank you for the clarification :)
