### ISSUE TITLE
Bug in Pick and Discriminated Unions

### ISSUE THREAD

**Issue by cliedeman** [Microsoft/TypeScript#28791]
**TypeScript Version:**  3.2.1

**Search Terms:** Discriminated Unions, Pick, Exclude

```ts
interface BaseTextFieldProps {
    name?: string
}

export interface StandardTextFieldProps extends BaseTextFieldProps {
    variant?: 'standard';
}

export interface FilledTextFieldProps extends BaseTextFieldProps {
    variant: 'filled';
}

export type TextFieldProps = StandardTextFieldProps | FilledTextFieldProps;

export type FieldProps = {
    someProps: string
};

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export type Props1 = FieldProps & Omit<TextFieldProps, 'name'>

export const func1 = ({...props}: Props1): TextFieldProps => {

    return {
        ...props,
    };
};

export type Props2 = FieldProps & TextFieldProps

export const func2 = ({...props}: Props2): TextFieldProps => {

    return {
        ...props,
    };
};
```

**Expected behavior:**
Compiles

**Actual behavior:**
Errors with incompatible types for variant

[**Playground Link:** ](http://www.typescriptlang.org/play/#src=interface%20BaseTextFieldProps%20%7B%0D%0A%20%20%20%20name%3F%3A%20string%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20StandardTextFieldProps%20extends%20BaseTextFieldProps%20%7B%0D%0A%20%20%20%20variant%3F%3A%20'standard'%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20FilledTextFieldProps%20extends%20BaseTextFieldProps%20%7B%0D%0A%20%20%20%20variant%3A%20'filled'%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20TextFieldProps%20%3D%20StandardTextFieldProps%20%7C%20FilledTextFieldProps%3B%0D%0A%0D%0Aexport%20type%20FieldProps%20%3D%20%7B%0D%0A%20%20%20%20someProps%3A%20string%0D%0A%7D%3B%0D%0A%0D%0Aexport%20type%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0A%0D%0Aexport%20type%20Props1%20%3D%20FieldProps%20%26%20Omit%3CTextFieldProps%2C%20'name'%3E%0D%0A%0D%0Aexport%20const%20func1%20%3D%20(%7B...props%7D%3A%20Props1)%3A%20TextFieldProps%20%3D%3E%20%7B%0D%0A%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20...props%2C%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%3B%0D%0A%0D%0Aexport%20type%20Props2%20%3D%20FieldProps%20%26%20TextFieldProps%0D%0A%0D%0Aexport%20const%20func2%20%3D%20(%7B...props%7D%3A%20Props2)%3A%20TextFieldProps%20%3D%3E%20%7B%0D%0A%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20...props%2C%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%3B)

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/27201#issuecomment-423701127
https://github.com/Microsoft/TypeScript/issues/28274
but these were related to generics so I could not be sure if this is a duplicate or not

**Comment by ahejlsberg** [comment]
This is working as intended. You are using `Omit` to remove the `name` property from `TextFieldProps` so the resulting type is no longer assignable to `TextFieldProps` (because the `name` property is missing).

**Comment by cliedeman** [comment]
Hi, Thanks for the reply but I don't quite understand. The error is not related to name but to variant?

**Comment by ahejlsberg** [comment]
@cliedeman Please post a complete repro. The current example starts with two undefined types.

**Comment by cliedeman** [comment]
Updated

**Comment by que-etc** [comment]
@ahejlsberg I have a somewhat related issue and I wonder if it's worth opening a separate ticket.

In the following example, when excluding some keys from a generic type, the resulting type doesn't contain properties which are meant to be there according to the base type constraint:

``` typescript
function excludeTag<T extends { tag: string, foo: string }>(obj: T) {
    let { tag, ...rest } = obj;
    let manual: Pick<T, Exclude<keyof T, "tag">>

    // 'foo' doesn't exist
    rest.foo;

    // 'foo' doesn't exist
    manual.foo;

    return rest;
}

const result = excludeTag({
    tag: 'point',
    foo: 'bar'
});

// 'foo' exists
result.foo;
```

[Playground](https://www.typescriptlang.org/play/index.html#src=function%20excludeTag%3CT%20extends%20%7B%20tag%3A%20string%2C%20foo%3A%20string%20%7D%3E(obj%3A%20T)%20%7B%0D%0A%09let%20%7B%20tag%2C%20...rest%20%7D%20%3D%20obj%3B%0D%0A%09let%20manual%3A%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20%22tag%22%3E%3E%0D%0A%0D%0A%09%2F%2F%20'foo'%20doesn't%20exist%0D%0A%09rest.foo%3B%0D%0A%0D%0A%09%2F%2F%20'foo'%20doesn't%20exist%0D%0A%09manual.foo%3B%0D%0A%0D%0A%20%20%20%20return%20rest%3B%0D%0A%7D%0D%0A%0D%0Aconst%20result%20%3D%20excludeTag(%7B%0D%0A%09tag%3A%20'point'%2C%0D%0A%09foo%3A%20'bar'%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20'foo'%20exists%0D%0Aresult.foo%3B).

Please, note that it used to work in `v3.1.6`.

**Comment by blazkovicz** [comment]
Why, the hell, this is "intended behaviour"??!!!

**Comment by colinrobertbrooks** [comment]
Ran into this today; [this article](https://davidgomes.com/pick-omit-over-union-types-in-typescript/) was helpful.
