### ISSUE TITLE
Syntactic 'use strict' support

### ISSUE THREAD

**Issue by breyed** [microsoft/TypeScript#288]
A nice feature would be if the TypeScript language understood 'use strict' and made it easy to apply. Although TypeScript can't help regarding the semantics of strict mode, it can help make the code cleaner and prevent a mistyping of the magic string from silently changing run-time behavior. 

Currently, I often put 'use strict' as the first line a module, like this:

```
module Foo {
    'use strict';
    // ... rest of Foo ...
}
```

It would be a nice parallel with the built-in-error checking of TypeScript's type safety if I could instead use a language keyword to indicate my intent:

```
strict module Foo {
    // ... rest of Foo ...
}
```

where the latter TypeScript snippet would generate the same JavaScript as the former.
#### Importance of strict mode:
- Per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions_and_function_scope/Strict_mode), "strict mode fixes mistakes that make it difficult for JavaScript engines to perform optimizations: strict mode code can sometimes be made to run faster than identical code that's not strict mode".
- tsLint has a  ["use strict" rule](https://github.com/palantir/tslint/issues/52).

**Comment by weitzhandler** [comment]
I'd say there should be a use strict feature that doesn't allow plain JS, I guess this is probably not an option. JS is a hard coded language by nature.
