### ISSUE TITLE
Spreading array into object should not be assignable to array

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#28801]
**TypeScript Version:**  3.3.0-dev.20181129

**Search Terms:** spread array object

**Code**

```ts
const x: number[] = [1, 2, 3, 4];
//Oh, look, a typo.
//Really meant [...x]
//But used     {...x}
const y: number[] = { ...x };

//undefined
console.log(y.length);
//Uncaught TypeError: y.indexOf is not a function
console.log(y.indexOf(3));
```

**Expected behavior:**

`{ ...x }` should not be assignable to `number[]`

**Actual behavior:**

`{ ...x }` is assignable to `number[]` and results in run-time errors.

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=const%20x%3A%20number%5B%5D%20%3D%20%5B1%2C%202%2C%203%2C%204%5D%3B%0D%0A%2F%2FOh%2C%20look%2C%20a%20typo.%0D%0A%2F%2FReally%20meant%20%5B...x%5D%0D%0A%2F%2FBut%20used%20%20%20%20%20%7B...x%7D%0D%0Aconst%20y%3A%20number%5B%5D%20%3D%20%7B%20...x%20%7D%3B%0D%0A%0D%0A%2F%2Fundefined%0D%0Aconsole.log(y.length)%3B%0D%0A%2F%2FUncaught%20TypeError%3A%20y.indexOf%20is%20not%20a%20function%0D%0Aconsole.log(y.indexOf(3))%3B)

-----

I actually ran into this problem because I was refactoring some code and decided to use arrays instead of objects. However, I missed a few spots. Luckily, I had unit tests to scream at me.

**Comment by ajafff** [comment]
The main problem is that builtin types are declared as interface in lib.xxx.d.ts. If `Array` was declared as class instead, instance methods would be removed from the spreaded type.

Unfortunately class declarations of the same name are not able to merge, which makes it impossible to add `Array.prototype.includes` in `lib.es2016.array.include.d.ts`.

**Comment by AnyhowStep** [comment]
I think `Event` might have a similar problem?

Or `MouseEvent`, at least.

```
function foo (evt : MouseEvent) {
    const copy = {...evt};
    console.log(copy.x + 1); //undefined + 1 = NaN
}
```

**Comment by PodaruDragos** [comment]
isn't `undefined + 1 = NaN` correct ?

**Comment by AnyhowStep** [comment]
The problem is that `MouseEvent.x` should be a `number`.

**Comment by RyanCavanaugh** [comment]
Tracking at #9726

**Comment by emlynmac** [comment]
I just ran into this same thing, so created a test code case:
`interface IObjectB {
  name: string;
  value: number;
}

interface IObjectA {
  title: string;
  arrayOfThings: IObjectB[];
}

interface IObjectC {
  objectA: IObjectA;
}

const thingThatShouldNotHappen: IObjectC = {
  objectA: {
    arrayOfThings: {
      ...[{ name: "thing", value: 8 }, { name: "otherThing", value: 9 }]
    },
    title: "Test"
  }
};

const thingThatShouldHappen: IObjectC = {
  objectA: {
    arrayOfThings: [
      ...[{ name: "thing", value: 8 }, { name: "otherThing", value: 9 }]
    ],
    title: "Test"
  }
};

console.log(thingThatShouldHappen);
console.log(thingThatShouldNotHappen);
`

I should get a compile warning on the thingThatShouldNotHappen; I don't. TS 3.5.3
