### ISSUE TITLE
union type not recognised when using inheritance/interface

### ISSUE THREAD

**Issue by Burgov** [Microsoft/TypeScript#28805]
**TypeScript Version:**  3.2.0

**Search Terms:**
union, interface, extends

**Code**

```ts
interface i {
    getSomething(): 'a' | 'b';
}

class B implements i {
    getSomething() {
        return 'a';
    }
}
```

**Expected behavior:**
Compiles just fine

**Actual behavior:**
Gives error:

```
Property 'getSomething' in type 'B' is not assignable to the same property in base type 'i'.
  Type '() => string' is not assignable to type '() => "a" | "b"'.
    Type 'string' is not assignable to type '"a" | "b"'.
```

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=interface%20i%20%7B%0D%0A%20%20%20%20getSomething()%3A%20'a'%20%7C%20'b'%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20implements%20i%20%7B%0D%0A%20%20%20%20getSomething()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'a'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:** 
No

**Comment by weswigham** [comment]
See #23911 for discussion here. We'd like to change our behavior here, but we know it could be breaking.
