### ISSUE TITLE
Array spread creating wrong union-ish type when spreading union of arrays

### ISSUE THREAD

**Issue by Andarist** [Microsoft/TypeScript#28813]
**TypeScript Version:**  
3.2.0

**Search Terms:**
array, union, spread

**Code**
```ts
function interpolate(output: number[] | string[]) {
    const spread = [...output]
    output = spread  
}
```

**Expected behavior:**

`spread` having `number[] | string[]` type

**Actual behavior:**

`spread` having `(number | string)[]` type

**Playground Link:**
https://www.typescriptlang.org/play/#src=function%20interpolate(output%3A%20number%5B%5D%20%7C%20string%5B%5D)%20%7B%0D%0A%20%20%20%20const%20spread%20%3D%20%5B...output%5D%0D%0A%20%20%20%20output%20%3D%20spread%20%20%0D%0A%7D%0D%0A

**Comment by DanielRosenwasser** [comment]
Looks like, as usual, the solution is to distribute across unions.

**Comment by bre1470** [comment]
We have a similar problem. Example:
```
interface SeriesColumnOptions {
    data?: [(number|[(number|string), number]|object)];
    type: "column";
}
var series: SeriesColumnOptions = {
    type: 'column',
    data: [1, 2, 3, 4, 5] // <- complains about wrong type
}
```

**Comment by bre1470** [comment]
Update to the problem. It is solved for me in latest dev package.

**Comment by Kingwl** [comment]
some question: 
what the type expected after i spread `number[] | string[]` and `number[] | boolean[]`?
- `(number | string | boolean)[]`    
- `(number[] | string[]) | (number[] | boolean[]) | number[]`

**Comment by Andarist** [comment]
Keep in mind that Im not expert at all, but IMHO...

> what the type expected after i spread number[] | string[] and number[] | boolean[]?

The type should not change at all, if we spread type T we should receive the same type T.

Same thing for the latter example.

**Comment by Kingwl** [comment]
@Andarist i mean:
```ts
[...([] as (number[] | string[])), ...([] as (number[] | boolean[]))]   
```

**Comment by Andarist** [comment]
Oh, then IMHO it should have union semantics, like [here](https://www.typescriptlang.org/play/#src=const%20a%20%3D%20(%5B%5D%20as%20(number%5B%5D%20%7C%20string%5B%5D))%0Aconst%20b%20%3D%20(%5B%5D%20as%20(number%5B%5D%20%7C%20boolean%5B%5D))%0Aconst%20c%20%3D%20%5B...a%2C%20...b%5D%0Alet%20d%3A%20typeof%20a%20%7C%20typeof%20b%20%20%0A). So it should be:
```js
number[] | string[] | boolean[]
```

**Comment by Andarist** [comment]
Oh, yeah - you are right ofc.

**Comment by Kingwl** [comment]
@DanielRosenwasser what should we do 🤣

**Comment by RyanCavanaugh** [comment]
This seems WIA IMHO; it's effectively the same as this example:
```ts
// Return type is { a: string | number }, not { a: string } | { a: number }
function fn(x: { y: string } | { y: number }) {
  return { a: x.y };
}
```
In other places where we would have to special-case a union type only existing in one place, we don't

**Comment by Andarist** [comment]
@RyanCavanaugh I'm a layman, so I might be missing something, but those cases arent IMHO the same.

With the object example it really might be seen as unpacking `x.y` first (resulting in `string | number`) and then putting this as object property's value - thus indeed resulting in `{ a: string | number }`.

OTOH `[...arr]` is **idiomatic** way to copy an array. And when copying changes the type then it's surprising to the user.

**Comment by RyanCavanaugh** [comment]
If you had written `[arr[0], arr[1], arr[2], arr[3]]` with the foreknowledge that the array had exactly 4 elements, what type would be expected? Isn't that exactly what `[...arr]` does?

FWIW `arr.slice()` is equally idiomatic and will return the desired type.

**Comment by Andarist** [comment]
> If you had written [arr[0], arr[1], arr[2], arr[3]] with the foreknowledge that the array had exactly 4 elements, what type would be expected? Isn't that exactly what [...arr] does?

But rest is not splitted into multiple nested expressions like this. The same argument could be made other way around for the mentioned, by you, slice method. We can always rewrite code to different lines which lead to the same result, but the road matters - in this case it matters for the compiler 😉 

> FWIW arr.slice() is equally idiomatic and will return the desired type.

Yeah, I've fixed my issue with that (or the concat) - reported this issue as seemed to me worthwhile to fix.

**Comment by jcalz** [comment]
Looks the work done for [variadic tuples](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types) supports distributive spread:

```ts
function interpolate(output: readonly number[] | readonly string[]) {
    const spread = [...output] as const;
    output = spread // 👍
}
```
[Playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDMUCmAnADnANgQ3QAo4QosyAuRDNfAEwVwE9EwQBbAI0wG0BdRAB8adRmBaIAzlAwoA5gICUiAN4AoRFsQQEM6VloNEAXkS8AdFdLkyg-FJ16oAbk3abFKKYNH66gF91IA)

So I wonder if this is worth revisiting?
