### ISSUE TITLE
Symbol prototype missing description property

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [Microsoft/TypeScript#28812]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**
symbol prototype properties description
**Code**

```ts
const x = Symbol('hello')
const y: string = x.description // errors here with property description does not exist on type unique symbol
// T0 should be 'toString' | 'valueOf' | 'description', but is only 'toString' | 'valueOf'
type T0 = keyof symbol
```

**Expected behavior:**
x.description should exist, since it is [defined on the Symbol prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Symbol_prototype)

**Actual behavior:**
we receive an error when trying to access the description property of a symbol

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=const%20x%20%3D%20Symbol('hello')%0D%0Aconst%20y%3A%20string%20%3D%20x.description%20%2F%2F%20errors%20here%20with%20property%20description%20does%20not%20exist%20on%20type%20unique%20symbol%0D%0A%2F%2F%20T0%20should%20be%20'toString'%20%7C%20'valueOf'%20%7C%20'description'%2C%20but%20is%20only%20'toString'%20%7C%20'valueOf'%0D%0Atype%20T0%20%3D%20keyof%20symbol)

**Related Issues:**

**Comment by j-oliveras** [comment]
Duplicated of #24484.

**Comment by WhiteAbeLincoln** [comment]
Ah sweet. That one didn't show up in any of my searches. Sorry for the duplicate

— Abe White

**Comment by j-oliveras** [comment]
It can be used already if you set target to `esnext` or adding [esnext.symbol](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.esnext.symbol.d.ts) or `esnext` to lib option.

**Comment by WhiteAbeLincoln** [comment]
Yeah, I had set my target to es2018, but didn't think to try esnext. Thanks!
