### ISSUE TITLE
Type cast of non sealed class that exactly matches interface should not compile

### ISSUE THREAD

**Issue by davityle** [Microsoft/TypeScript#28819]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**
generic, narrowing, Conversion of type <> to type <> may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first, sealed, final
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

export abstract class Foo { abstract doSomething(): number; }

export class ExactImplFoo { doSomething(): number { return 0; } }
export class ExactImplFoo2 extends ExactImplFoo { doSomethingElse() { return 5; }}

function a<T extends Foo>(thing: T): T {
    if (thing instanceof ExactImplFoo) {
        return new ExactImplFoo() as T;
    }
    return thing;
}

const x = new ExactImplFoo2();
const b = a(x);
b.doSomethingElse();
```

**Expected behavior:**

This code should not compile. If I add any other members to the class `ExactImplFoo` it correctly fails to compile. Example: http://www.typescriptlang.org/play/#src=export%20abstract%20class%20Foo%20%7B%20abstract%20doSomething()%3A%20number%3B%20%7D%0D%0A%0D%0Aexport%20class%20ExactImplFoo%20%7B%20doSomething()%3A%20number%20%7B%20return%200%3B%20%7D%20foobar%3A%20number%20%3D%205%3B%20%7D%0D%0Aexport%20class%20ExactImplFoo2%20extends%20ExactImplFoo%20%7B%20doSomethingElse()%20%7B%20return%205%3B%20%7D%7D%0D%0A%0D%0Afunction%20a%3CT%20extends%20Foo%3E(thing%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20if%20(thing%20instanceof%20ExactImplFoo)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20ExactImplFoo()%20as%20T%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20thing%3B%0D%0A%7D%0D%0A%0D%0Aconst%20x%20%3D%20new%20ExactImplFoo2()%3B%0D%0Aconst%20b%20%3D%20a(x)%3B%0D%0Ab.doSomethingElse()%3B

**Actual behavior:**

It compiles and then crashes at run time.

**Playground Link:** 

http://www.typescriptlang.org/play/#src=export%20abstract%20class%20Foo%20%7B%20abstract%20doSomething()%3A%20number%3B%20%7D%0D%0A%0D%0Aexport%20class%20ExactImplFoo%20%7B%20doSomething()%3A%20number%20%7B%20return%200%3B%20%7D%20%7D%0D%0Aexport%20class%20ExactImplFoo2%20extends%20ExactImplFoo%20%7B%20doSomethingElse()%20%7B%20return%205%3B%20%7D%7D%0D%0A%0D%0Afunction%20a%3CT%20extends%20Foo%3E(thing%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20if%20(thing%20instanceof%20ExactImplFoo)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20ExactImplFoo()%20as%20T%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20thing%3B%0D%0A%7D%0D%0A%0D%0Aconst%20x%20%3D%20new%20ExactImplFoo2()%3B%0D%0Aconst%20b%20%3D%20a(x)%3B%0D%0Ab.doSomethingElse()%3B

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is working as intended. To determine whether two types are sufficiently related, a type assertion uses the heuristic that one of the types has to be assignable to the other. In your first example that is true and in the second it is not. But either way, with an assertion you are explicitly overriding the type checker and there is no guarantee that it will be correct at run-time.

**Comment by davityle** [comment]
Can I change this to a feature request then?
