### ISSUE TITLE
Unable to retain generic types when defining a type guard

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#28814]
**TypeScript Version:**  3.1

**Search Terms:**
type guard generic types 

**Code**

```ts
interface IInit<TInit>{
    init?: (value: TInit) => void;
}

function isInit(value: any): value is Required<IInit<any>>{
    return true;
}

const unChecked: IInit<string>[] = [];

unChecked
    .filter(isInit)
    .forEach(item => {
        item.init("string"); // OK
        item.init(12345); // Also OK (should not be)
```
I did try this as a way to get it to work:

```
function isInit<T extends IInit<any>>(value: T): value is (T extends IInit< infer U> ? Required<IInit<U>> : Required<IInit<any>>){
    return true
}
```
Throws error:  "A type predicate must be assignable to it's parameter's type"

**Expected behavior:**
should be possible to retain the generic type (in this case `string`)

**Actual behavior:**
Returned type from the guard is `IInit<any>`

**Playground Link:**
https://www.typescriptlang.org/play/#src=%0D%0Ainterface%20IInit%3CTInit%3E%7B%0D%0A%20%20%20%20init%3F%3A%20(value%3A%20TInit)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isInit(value%3A%20any)%3A%20value%20is%20Required%3CIInit%3Cany%3E%3E%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Aconst%20unChecked%3A%20IInit%3Cstring%3E%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0AunChecked%0D%0A%20%20%20%20.forEach(item%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20item.init(%22string%22)%3B%20%2F%2F%20error%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0AunChecked%0D%0A%20%20%20%20.filter(isInit)%0D%0A%20%20%20%20.forEach(item%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20item.init(%22string%22)%3B%20%2F%2F%20OK%0D%0A%20%20%20%20%20%20%20%20item.init(12345)%3B%20%2F%2F%20Also%20OK%20(should%20not%20be)%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0AunChecked%0D%0A%20%20%20%20.filter(isInit%20as%20((value)%20%3D%3E%20value%20is%20Required%3CIInit%3Cstring%3E%3E))%0D%0A%20%20%20%20.forEach(item%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20item.init(%22string%22)%3B%20%2F%2F%20OK%0D%0A%20%20%20%20%20%20%20%20item.init(12345)%3B%20%2F%2F%20Not%20OK%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0A 

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/12908 

I did find a few related issues but they were all closed so I thought it was worth posting again.

**Comment by jack-williams** [comment]
Does this not work?

```ts
function isInit<T extends IInit<any>>(value: T): value is Required<T> {
    return true;
}
```

**Comment by Roaders** [comment]
Well that compiles but does not do what I want. My actual situation is:

```
interface IMyActualInterface extends IInit<ICustomInit>{
    someOtherOptionalFunc?: () => void
}
```

so that when you do `isInit<IMyActualInterface>` ALL of the optional properties are now marked as required

**Comment by jack-williams** [comment]
What about this?

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
type RequiredP<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>


function isInit<T extends IInit<any>>(value: T): value is T & RequiredP<T,"init"> {
    return true;
}
```

**Comment by Roaders** [comment]
I suppose that would work but it's pretty nasty. It's working round the issue rather than fixing it IMHO.

Thanks for the help anyway BTW :-)

**Comment by eugengarkusha** [comment]
this may be related:
http://www.typescriptlang.org/play/#src=%0D%0Atype%20Omit%3CT%2C%20K%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0A%0D%0Atype%20Identity1%3CT%3E%20%3D%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20Identity2%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20%7B%0D%0A%20%20%5BP%20in%20%20K%5D%3A%20T%5BP%5D%3B%0D%0A%7D%20%26%20Omit%3CT%2C%20K%3E%20%3B%0D%0A%0D%0A%0D%0A%0D%0A%2F%2F%20works%0D%0Aconst%20identity1%20%3D%20%3CT%2C%20S%20extends%20keyof%20T%3E(item%3A%20T)%3A%20item%20is%20Identity1%3CT%3E%20%3D%3E%20true%0D%0A%2F%2F%20compiler%20bug%20(Type%20Identity2%3CT%2C%20S%3E%20is%20not%20assignable%20to%20type%20T)%0D%0Aconst%20identity2%20%3D%20%3CT%2C%20S%20extends%20keyof%20T%3E(item%3A%20T)%3A%20item%20is%20Identity2%3CT%2C%20S%3E%20%3D%3E%20true%0D%0A%0D%0A%2F%2F%20proof%3A%20%0D%0Ainterface%20X%20%7B%20%0D%0A%20%20a%3A%20number%0D%0A%20%20b%3A%20number%0D%0A%7D%0D%0Atype%20ID2%20%3D%20Identity2%3CX%2C%20%22a%22%3E%20%0D%0A%0D%0Aconst%20x%3A%20ID2%20%3D%20%7B%20a%3A%201%2C%20b%3A%202%20%7D%0D%0A%2F%2F%20Type%20ID2%20_IS_%20assignable%20to%20type%20X%0D%0Aconst%20x1%3A%20X%20%3D%20x
