### ISSUE TITLE
Non-strict null checking causes union of string and type

### ISSUE THREAD

**Issue by justinbc820** [Microsoft/TypeScript#28829]
**TypeScript Version:**  ^3.3.0-dev.20181201

**Search Terms:**
TS2322, boolean assignment, nullable, type union, inferred type, non-strict null checks, empty string

**Code**
A simple [gist](https://gist.github.com/justinbc820/aad073d07c4dafdd0ef2f9c5028be9e1) that demonstrates the issue.
```ts
/* package.json */
{
  "name": "ts-error",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "typescript": "^3.3.0-dev.20181201"
  }
}

/* ts-error-example.ts */
type ContentType = 'TYPE_1' | 'TYPE_2';

interface ContentObject {
	type: ContentType;
}

function returnContentType(contentObject?: ContentObject): ContentType {
	return contentObject && contentObject.type;
}
```

**Testing:**
Test this by creating these two files in the same directory. Run yarn install. Then run `node ./node_modules/typescript/bin/tsc ts-error-example.ts` on the command-line.

**Expected behavior:**
Shouldn't output errors. The runtime return type of the function is `ContentType | null` or in other words `ContentType`. However, typescript is saying that

```
ts-error-example.ts(8,2): error TS2322: Type '"" | "TYPE_1" | "TYPE_2"' is not assignable to type 'ContentType'.
  Type '""' is not assignable to type 'ContentType'.
```

For some reason, when using the `&&` operator, it creates a union of `ContentType | ""` instead of a union of `ContentType | null` which is just `ContentType`.
It seems to only be an issue without non-strict null checking.

**Actual behavior:**
The return of the function should satisfy the declared `ContentType` return type because it can either return `ContentType | null`.

**Playground Link:**
[Link](http://www.typescriptlang.org/play/#src=type%20ContentType%20%3D%20'TYPE_1'%20%7C%20'TYPE_2'%3B%0D%0A%0D%0Ainterface%20ContentObject%20%7B%0D%0A%09type%3A%20ContentType%3B%0D%0A%7D%0D%0A%2F*%20This%20solution%20doesn't%20work%20*%2F%0D%0Afunction%20returnContentType(contentObject%3F%3A%20ContentObject)%3A%20ContentType%20%7B%0D%0A%09return%20contentObject%20%26%26%20contentObject.type%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%2F*%20Both%20of%20these%20solutions%20work%20even%20though%20they%20are%20doing%20the%20same%20thing%20*%2F%0D%0A%0D%0A%2F%2F%20function%20returnContentType(contentObject%3A%20ContentObject)%3A%20ContentType%20%7B%0D%0A%2F%2F%20%20%20%20%20let%20type%3A%20ContentType%3B%0D%0A%2F%2F%20%20%20%20%20if%20(contentObject)%20%7B%0D%0A%2F%2F%20%09%09%20%20type%20%3D%20contentObject.type%3B%0D%0A%2F%2F%20%09%20%20%20%7D%0D%0A%2F%2F%20%09%20%20%20return%20type%3B%0D%0A%2F%2F%20%7D%0D%0A%0D%0A%2F%2F%20function%20returnContentType(contentObject%3A%20ContentObject)%3A%20ContentType%20%7B%0D%0A%2F%2F%20%20%20%20%20return%20contentObject%20%3F%20contentObject.type%20%3A%20undefined%3B%0D%0A%2F%2F%20%7D%0D%0A)

**Related Issues:**
Couldn't find any

**Comment by justinbc820** [comment]
If you write the above as

```
function returnContentType(contentObject: ContentObject): ContentType {
    return contentObject ? contentObject.type : undefined;
}
```

*OR*

```
function returnContentType(contentObject: ContentObject): ContentType {
    let type: ContentType;
    if (contentObject) {
	type = contentObject.type;
    }
    return type;
}
```

It works just fine.

**Comment by ahejlsberg** [comment]
The issue here is the way we check the `&&` operator in classic mode (i.e. without `--strictNullChecks`). We say that the type of the operation `x && y` is a union of the type of `y` and the possible falsy values of the primitive type of `y` (in this case `""`). This isn't exactly correct (as you've discovered) but we can't fix it for backwards compatibility reasons. Instead, we strongly recommend you use `--strictNullChecks` (or even better the full `--strict` mode) where we reason correctly about `null` and `undefined`.

**Comment by antmdvs** [comment]
@ahejlsberg

Is this related? The following errors occur without `--strictNullChecks`, but this compiles *with* `--strictNullChecks`.

```typescript
const x = { hi: 123 };
const y = x || {}
const { hi } = y; // "Property 'hi' does not exist on type '{}'
y.hi // "Property 'hi' does not exist on type '{}'
```

WITHOUT `--strictNullChecks`, the type of `y` is inferred as `{}`
WITH `--strictNullChecks`, the type of `y` is inferred as `{hi : number}`

https://www.typescriptlang.org/play/#src=const%20y%20%3D%20%7B%20hi%3A%20123%20%7D%3B%0D%0Aconst%20x%20%3D%20y%20%7C%7C%20%7B%7D%0D%0Ax.hi%0D%0A
