### ISSUE TITLE
organizeImports does not respect comment pragma

### ISSUE THREAD

**Issue by neezer** [Microsoft/TypeScript#28827]
- VSCode Version: 1.30.0-insider
- OS Version: macOS Mojave 10.14 (18A391)

Steps to Reproduce:

1. Clone [this repo](https://github.com/neezer/vscode-organize-imports-pragma).
1. Open `src/app.tsx`.

    **NOTE** The keyword `jsx` in the import statement is not greyed out, suggesting some part of VSCode recognizes it as a used import.

1. Save the file.

    ##### Expected Result

    ```js
    /** @jsx jsx */

    import { css, Global, jsx } from '@emotion/core';
    ```

    ##### Actual Result

    ```js
    /** @jsx jsx */

    import { css, Global } from '@emotion/core';
    ```

Does this issue occur when all extensions are disabled?: Yes

---

~I know I can work around this by changing my import to~

```diff
- /** @jsx jsx */
+ /** @jsx Emotion.jsx */

- import { css, Global, jsx } from '@emotion/core';
+ import * as Emotion from '@emotion/core';
```

~... but that means all my other imports from that module need the module prefix, which breaks some syntax highlighting for embedded CSS in tagged template literals: for example, `` css`background: red;` `` will highlight correctly but `` Emotion.css`background: red;` `` will not.~

Nope, this doesn't work. If the pragma is the only reference to the import, the statement disappears entirely:

```diff
/** @jsx Emotion.jsx */

// on save
- import * as Emotion from '@emotion/core';
```

**Comment by mjbvz** [comment]
See https://github.com/Microsoft/TypeScript/issues/9582

Try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) at the root of your project with the contents:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve",
        "jsxFactory": "jsx"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```


`jsxFactory` is the important setting here.

**Comment by neezer** [comment]
@mjbvz Some issues with this approach:

- `jsxFactory` does not seem to be supported with `jsconfig.json`:

    ![screen shot on 2018-12-03 at 14 20 58](https://user-images.githubusercontent.com/29997/49405239-ada5f880-f706-11e8-915c-3138945f0b9a.png)

- Changing `jsxFactory` in [`tsconfig.json`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) (as it seemed reasonable to do so considering [`jsconfig.json` is a descendent of `tsconfig.json`](https://code.visualstudio.com/docs/languages/jsconfig)) does not yield the same compiled code:

    With your changes: 

    ```js
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const core_1 = require("@emotion/core");
    const globalStyles = core_1.css `
      * {
        box-sizing: border-box;
      }
    `;
    const styles = {
        color: "hotpink"
    };
    exports.App = _ => (<core_1.Global styles={globalStyles}>
        <h1>Hello!</h1>
      </core_1.Global>);
    ```

    Emitted file is `app.jsx`

    With `/** @jsx jsx */` comment pragma (edited with `organizeImports` disabled):

    ```js
    "use strict";
    /** @jsx jsx */
    Object.defineProperty(exports, "__esModule", { value: true });
    const core_1 = require("@emotion/core");
    const globalStyles = core_1.css `
      * {
        box-sizing: border-box;
      }
    `;
    const styles = {
        color: "hotpink"
    };
    exports.App = _ => (core_1.jsx(core_1.Global, { styles: globalStyles },
        core_1.jsx("h1", null, "Hello!")));
    ```

    Emitted as `app.js`.

- Changing `jsxFactory` in compiler options alters my pragma project-wide, which I do not want. I want to opt-in to `Emotion.jsx` in select files, and fall back to `React.createElement` otherwise. Comment pragma allows me to do this, the TypeScript compiler supports this, the syntax highlighter in VSCode works correctly... it's just that `organizeImports` does the wrong thing by deleting the import on save.

---

The issue you linked to is about specifying a custom pragma for a project, not (AFAICT) overriding a project's configured pragma on a per-file basis using comment pragmas.

Unless I'm missing something, this still feels like a bug to me. Simplifying my example even further:

![screen shot on 2018-12-03 at 14 47 31](https://user-images.githubusercontent.com/29997/49406436-720d2d80-f70a-11e8-9066-45115f567eb8.png)

Notice that `css` is dimmed because IntelliSense (or whatever) detects that it's not being used, but that `jsx` is not dimmed because it's referenced by the comment pragma.

I can remove the comment pragma and see it dim:

![screen shot on 2018-12-03 at 14 49 25](https://user-images.githubusercontent.com/29997/49406523-a4b72600-f70a-11e8-83b6-10bf3aa15830.png)

This makes sense to me. Were I to save the file with `organizeImports` enabled, I'd expect the whole line to disappear, which it does:

![screen shot on 2018-12-03 at 14 51 04](https://user-images.githubusercontent.com/29997/49406599-e47e0d80-f70a-11e8-8a1a-e5a7fa6b7351.png)

But if I save the first version of this file with the comment pragma, I still see the whole line disappear--even though IntelliSense (or whatever) has visually told me it recognizes `jsx` as being used:

![screen shot on 2018-12-03 at 14 52 30](https://user-images.githubusercontent.com/29997/49406664-12635200-f70b-11e8-8f84-12ccbc4a9a17.png)

... which leads to compiler errors:

![screen shot on 2018-12-03 at 14 52 59](https://user-images.githubusercontent.com/29997/49406689-2444f500-f70b-11e8-918e-f0f7ac484c9e.png)

**Comment by travikk** [comment]
I found this to still be the issue if the pragma declaration is not the first line in the file.

```typescript
import {css, jsx} from '@emotion/core'
/** @jsx jsx */
```

Organizing imports above would still remove `jsx` from import list, even though it's a valid syntax and order.
