### ISSUE TITLE
Nested `Exclude` has unexpected behavior

### ISSUE THREAD

**Issue by davidk01** [Microsoft/TypeScript#28824]
**TypeScript Version:**
```
$ tsc --version
Version 3.3.0-dev.20181122
```

**Search Terms:**
unexpected, exclude
**Code**

```ts
/*
  Some basic definitions of unions
*/
type Union = 'a' | 'b';
type Product<A extends Union, B> = { f1: A, f2: B};
type ProductUnion = Product<'a', 0> | Product<'b', 1>;

/*
  These work as I would expect. Each element in the union is mapped
  the complement or the double complement with nested Exclude
*/
type UnionComplement = {
  [K in Union]: Exclude<Union, K>
};
// {a: "b"; b: "a"}
type UnionComplementComplement = {
  [K in Union]: Exclude<Union, Exclude<Union, K>>
};
// {a: "a"; b: "b"}

/*
  This also works as I would expect
*/
type ProductComplement = {
  [K in Union]: Exclude<ProductUnion, { f1: K }>
};
// {a: Product<'b', 1>; b: Product<'a', 0>}

/*
  Double complement on the other hand doesn't work
*/
type ProductComplementComplement = {
  [K in Union]: Exclude<ProductUnion, Exclude<ProductUnion, { f1: K }>>
};
// {a: ProductUnion; b: ProductUnion}

/*
  Explicit inlining works as I would expect
*/
type First = Exclude<ProductUnion, Exclude<ProductUnion, { f1: 'a' }>>;
// {f1: 'a'; f2: 0}
type Second = Exclude<ProductUnion, Exclude<ProductUnion, { f1: 'b' }>>;
// {f1: 'b'; f2: 1}

/*
  Making parametrized types works as I would expect
*/
type Complementor<T> = {
    [K in Union]: Exclude<T, { f1: K }>
};
type DoubleComplementor<T> = {
    [K in Union]: Exclude<T, Exclude<T, { f1: K }>>
};
type Complement = Complementor<ProductUnion>;
// {a: Product<'b', 1>; b: Product<'a', 0>}
type DoubleComplement = DoubleComplementor<ProductUnion>;
// {a: Product<'a', 0>; b: Product<'b', 0>}
```

**Expected behavior:**
I would expect the parametrized and non-parametrized type to work the same way but that's not
the case.

**Actual behavior:**
See the comments.

**Playground Link:**  [link](https://www.typescriptlang.org/play/#src=%2F*%0D%0A%20%20Some%20basic%20definitions%20of%20unions%0D%0A*%2F%0D%0Atype%20Union%20%3D%20'a'%20%7C%20'b'%3B%0D%0Atype%20Product%3CA%20extends%20Union%2C%20B%3E%20%3D%20%7B%20f1%3A%20A%2C%20f2%3A%20B%7D%3B%0D%0Atype%20ProductUnion%20%3D%20Product%3C'a'%2C%200%3E%20%7C%20Product%3C'b'%2C%201%3E%3B%0D%0A%0D%0A%2F*%0D%0A%20%20These%20work%20as%20I%20would%20expect.%20Each%20element%20in%20the%20union%20is%20mapped%0D%0A%20%20the%20complement%20or%20the%20double%20complement%20with%20nested%20Exclude%0D%0A*%2F%0D%0Atype%20UnionComplement%20%3D%20%7B%0D%0A%20%20%5BK%20in%20Union%5D%3A%20Exclude%3CUnion%2C%20K%3E%0D%0A%7D%3B%0D%0A%2F%2F%20%7Ba%3A%20%22b%22%3B%20b%3A%20%22a%22%7D%0D%0Atype%20UnionComplementComplement%20%3D%20%7B%0D%0A%20%20%5BK%20in%20Union%5D%3A%20Exclude%3CUnion%2C%20Exclude%3CUnion%2C%20K%3E%3E%0D%0A%7D%3B%0D%0A%2F%2F%20%7Ba%3A%20%22a%22%3B%20b%3A%20%22b%22%7D%0D%0A%0D%0A%2F*%0D%0A%20%20This%20also%20works%20as%20I%20would%20expect%0D%0A*%2F%0D%0Atype%20ProductComplement%20%3D%20%7B%0D%0A%20%20%5BK%20in%20Union%5D%3A%20Exclude%3CProductUnion%2C%20%7B%20f1%3A%20K%20%7D%3E%0D%0A%7D%3B%0D%0A%2F%2F%20%7Ba%3A%20Product%3C'b'%2C%201%3E%3B%20b%3A%20Product%3C'a'%2C%200%3E%7D%0D%0A%0D%0A%2F*%0D%0A%20%20Double%20complement%20on%20the%20other%20hand%20doesn't%20work%0D%0A*%2F%0D%0Atype%20ProductComplementComplement%20%3D%20%7B%0D%0A%20%20%5BK%20in%20Union%5D%3A%20Exclude%3CProductUnion%2C%20Exclude%3CProductUnion%2C%20%7B%20f1%3A%20K%20%7D%3E%3E%0D%0A%7D%3B%0D%0A%2F%2F%20%7Ba%3A%20ProductUnion%3B%20b%3A%20ProductUnion%7D%0D%0A%0D%0A%2F*%0D%0A%20%20Explicit%20inlining%20works%20as%20I%20would%20expect%0D%0A*%2F%0D%0Atype%20First%20%3D%20Exclude%3CProductUnion%2C%20Exclude%3CProductUnion%2C%20%7B%20f1%3A%20'a'%20%7D%3E%3E%3B%0D%0A%2F%2F%20%7Bf1%3A%20'a'%3B%20f2%3A%200%7D%0D%0Atype%20Second%20%3D%20Exclude%3CProductUnion%2C%20Exclude%3CProductUnion%2C%20%7B%20f1%3A%20'b'%20%7D%3E%3E%3B%0D%0A%2F%2F%20%7Bf1%3A%20'b'%3B%20f2%3A%201%7D%0D%0A%0D%0A%2F*%0D%0A%20%20Making%20parametrized%20types%20works%20as%20I%20would%20expect%0D%0A*%2F%0D%0Atype%20Complementor%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20Union%5D%3A%20Exclude%3CT%2C%20%7B%20f1%3A%20K%20%7D%3E%0D%0A%7D%3B%0D%0Atype%20DoubleComplementor%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20Union%5D%3A%20Exclude%3CT%2C%20Exclude%3CT%2C%20%7B%20f1%3A%20K%20%7D%3E%3E%0D%0A%7D%3B%0D%0Atype%20Complement%20%3D%20Complementor%3CProductUnion%3E%3B%0D%0A%2F%2F%20%7Ba%3A%20Product%3C'b'%2C%201%3E%3B%20b%3A%20Product%3C'a'%2C%200%3E%7D%0D%0Atype%20DoubleComplement%20%3D%20DoubleComplementor%3CProductUnion%3E%3B%0D%0A%2F%2F%20%7Ba%3A%20Product%3C'a'%2C%200%3E%3B%20b%3A%20Product%3C'b'%2C%200%3E%7D)

**Related Issues:**  Some issues related to `Pick` and `Exclude` but didn't seem to apply.

**Comment by riggs** [comment]
I've run into a similar (likely related) issue, probably also having to do with distribution over `Exclude`:

```
const f = <U extends Exclude<any, Function>>(a: U | ( () => U )): U => {
    if (typeof a === "function" ) {
        return a(); // Cannot invoke an expression whose type lacks a call signature.
                    // Type '(() => U) | (U & Function)' has no compatible call signatures.
    }
    return a;
};
```
My understanding is that `U & Function` would expand into `Exclude<any, Function> & Function`, which would presumably be `never`.

**Comment by davidk01** [comment]
@riggs I'm confused by what `Exclude<any, Function>` can mean? I think your intent is to exclude function types. Woldn't a conditional type be better in that case?

```typescript
type NonFunction<U> = U extends Function ? never : U;
```

**Comment by riggs** [comment]
From the library:
```
type Exclude<T, U> = T extends U ? never : T;
```

**Comment by jack-williams** [comment]
I think this is a smaller repro:
```ts
type Union = 'a' | 'b';
type Z<K extends Union> = false extends ([Union] extends [K] ? never : false) ? 'LEFT' : 'RIGHT';
```
If you hover over `Z` it appears to have already resolved to `RIGHT`.

**Comment by jack-williams** [comment]
Essentially the compiler is trying to eagerly resolve the conditional type using wildcard types, substituting type parameters for `any`. For example:  `K ==> any`, or `[K] ==> [any]`. The compiler knows that any conditional type with a wildcard `extends` type resolves to the wildcard type, but it misses the case when the wild card is wrapped in a 1-tuple.


(I think).

**Comment by davidk01** [comment]
Amazing turnaround. Thanks @ahejlsberg and team.
