### ISSUE TITLE
Completion interferes with typeing a "type alias".

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#2882]
Completion shouldn't appear after "type" when typing a type alias.

**Comment by DanielRosenwasser** [comment]
Sounds like a duplicate of #2520, though as @CyrusNajmabadi pointed out offline, there shouldn't even be a builder since this is a declaration position.

**Comment by paulvanbrenk** [comment]
Fixed with PR #2979
