### ISSUE TITLE
Error when constructing "sealed" (by private constructor) class that matches generic type

### ISSUE THREAD

**Issue by davityle** [Microsoft/TypeScript#28820]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**
generic, narrowing, Conversion of type <> to type <> may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first, sealed, final
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

export abstract class Foo { abstract doSomething(): number; }

export class Bar extends Foo {

    private constructor() {
        super();
    }

    public static factory() {
        return new Bar();
    }

    doSomething(): number{
        return 0;
    }

    somethingElse() {
        return '';
    }
}

// should work because the type T is gauranteed to be Bar and not a sub class of Bar
function a<T extends Foo>(thing: T): T {
    if (thing instanceof Bar) {
        return Bar.factory();
    }
    return thing;
}

// should work because the type T is gauranteed to be Bar and not a sub class of Bar
function b<T extends Foo>(thing: T): T {
    if (thing instanceof Bar) {
        return Bar.factory() as T;
    }
    return thing;
}


```

**Expected behavior:**

Since you can make it impossible for a class to be extended you can gaurantee that a class "sufficiently overlaps" with a generic type. This code should compile.

**Actual behavior:**

The code does not compile.

**Playground Link:** 

http://www.typescriptlang.org/play/#src=export%20abstract%20class%20Foo%20%7B%20abstract%20doSomething()%3A%20number%3B%20%7D%0D%0A%0D%0Aexport%20class%20Bar%20extends%20Foo%20%7B%0D%0A%0D%0A%20%20%20%20private%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20static%20factory()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20Bar()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20doSomething()%3A%20number%7B%0D%0A%20%20%20%20%20%20%20%20return%200%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20somethingElse()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20''%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20should%20work%20because%20the%20type%20T%20is%20gauranteed%20to%20be%20Bar%20and%20not%20a%20sub%20class%20of%20Bar%0D%0Afunction%20a%3CT%20extends%20Foo%3E(thing%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20if%20(thing%20instanceof%20Bar)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20Bar.factory()%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20thing%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20should%20work%20because%20the%20type%20T%20is%20gauranteed%20to%20be%20Bar%20and%20not%20a%20sub%20class%20of%20Bar%0D%0Afunction%20b%3CT%20extends%20Foo%3E(thing%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20if%20(thing%20instanceof%20Bar)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20Bar.factory()%20as%20T%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20thing%3B%0D%0A%7D

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/8306
https://github.com/Microsoft/TypeScript/issues/8306#issuecomment-378434818
https://github.com/Microsoft/TypeScript/issues/28819

**Comment by ahejlsberg** [comment]
This is working as intended. We don't have the concept of "sealed" or "final" types (that discussion is already taking place in #8306), and we never consider a zero order type (such as `Bar` in your example) to be assignable to a higher order type (such as `T` in your example).

**Comment by davityle** [comment]
Can I change this to a feature request then?
