### ISSUE TITLE
Suggestion: Types Day/Week

### ISSUE THREAD

**Issue by mrmckeb** [Microsoft/TypeScript#28838]
## Search Terms

definitely-typed, typings, types, community

## Suggestion

One of the most cumbersome and frustrating things about using TypeScript is having to download separate types for projects. Many projects include types, which is great, but many more do not.

Definitely Typed is a great community, but it's clearly not the ideal scenario, and types there can become outdated and need maintaining - and to be fair, writing types can be complex for many developers.

I propose to organise an official day/week where the community reaches out to projects that don't include types, and ask them to bring those types into their repositories. This could be supported by a website, official support (maybe a Slack/Discord server set up for discussion and "how can I write a type for x?").

## Use Cases

This could be an annual or biannual event, until definitely typed can become a thing of the past.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> until definitely typed can become a thing of the past.

You forget here that it's a legitimate decision of many projects to not use TypeScript. DefinitelyTyped and the types-packages are a solution for exactly that case: Augment libraries without type information with type information.

**Comment by mrmckeb** [comment]
@MartinJohns, I didn't say they should write in TypeScript, only to provide definitions - even if that means folding those provided on definitely typed into the project.

**Comment by MartinJohns** [comment]
That's what I meant. In order to provide types they need to use TypeScript and write the definition files. That can be a lot of overhead for a project that does not care about TypeScript. It's a legitimate decision to neither use TypeScript nor spend time on providing TypeScript type declartation files. And that's exactly what DefinitelyTyped is for.

**Comment by mrmckeb** [comment]
I understand @MartinJohns, and thanks for your feedback.

I wasn't saying this was Microsoft's job :) Or anyone in particular, but asking if there would be support from the team involved in this project for an effort to get more libraries to include types out-of-the-box, which is a better DX and much better for the growth of TypeScript.

**Comment by weswigham** [comment]
We moderate/review `DefinitelyTyped` constantly, so we already do a little bit of this - we wouldn't be opposed to the community setting something like this up (who'd ever be opposed to what amounts to a community day that brings a focus on documentation?); but I don't think we on the team have the bandwidth available to do any of the work involved ourselves.

**Comment by mrmckeb** [comment]
OK thanks for the update @weswigham. I'll give it some more thought - as it's something I think is important, but I'm still not 100% sure of how to get traction on an idea like this.
