### ISSUE TITLE
Non-module file does't offer import fixes

### ISSUE THREAD

**Issue by Venthe** [microsoft/TypeScript#28831]
- VSCode Version: 1.29.1; 1-30.0-insider (2018-11-30)
- OS Version: Windows 10 1809

Steps to Reproduce:
Use this zip 
[callWithTimeout.zip](https://github.com/Microsoft/vscode/files/2635841/callWithTimeout.zip)
or
1. Create new project through NPM
  1. npm init
  2. npm add --save-dev rxjs typescript
2. Create tsconfig.json
```
{
    "compilerOptions": {
      "rootDir": "./",
      "target": "es6",
      "module": "commonjs",
      "declaration": true,
      "outDir": "./dist",
      "strict": true
    },
    "include": ["src"],
    "exclude": ["node_modules", "**/__tests__/*"],
  }
```
3. create any file with .ts extension with content:
`let a: Observable<any>;`
4. Press `ctrl+.` with cursor on observable

Does this issue occur when all extensions are disabled?: Yes

Current behaviour: No actions available
Expected behaviour: import from...

What is worth noting, if I add empty import like so `import {} from "rxjs"` it will suggest to add to existing import
![image](https://user-images.githubusercontent.com/1686874/49327939-5f5af300-f568-11e8-88bc-6b6ddd00f0a0.png)
![image](https://user-images.githubusercontent.com/1686874/49327943-641fa700-f568-11e8-8538-c51b529d48df.png)

**Comment by mjbvz** [comment]
Confirmed on typescript@3.3.0-dev.20181201

**Comment by DanielRosenwasser** [comment]
@sheetalkamat, I'm pretty sure that you fixed this in the nightly, right?

**Comment by sheetalkamat** [comment]
@DanielRosenwasser We did that for completions.. We need to do that for suggestion diagnostics as well.

**Comment by sheetalkamat** [comment]
@DanielRosenwasser We look for code fix from program files because the program in the current scenario does not contain `rxJs` its not going to be able to look for the import fix that contains symbol for `observable` so this seems like by design?
```
Info 53   [10:16:15.912] Project 'c:/temp/callWithTimeout/tsconfig.json' (Configured) 0
Info 53   [10:16:15.912] 	Files (17)
	c:/typescript/built/local/lib.es6.d.ts
	c:/typescript/built/local/lib.es5.d.ts
	c:/typescript/built/local/lib.es2015.d.ts
	c:/typescript/built/local/lib.dom.d.ts
	c:/typescript/built/local/lib.dom.iterable.d.ts
	c:/typescript/built/local/lib.webworker.importscripts.d.ts
	c:/typescript/built/local/lib.scripthost.d.ts
	c:/typescript/built/local/lib.es2015.core.d.ts
	c:/typescript/built/local/lib.es2015.collection.d.ts
	c:/typescript/built/local/lib.es2015.generator.d.ts
	c:/typescript/built/local/lib.es2015.iterable.d.ts
	c:/typescript/built/local/lib.es2015.promise.d.ts
	c:/typescript/built/local/lib.es2015.proxy.d.ts
	c:/typescript/built/local/lib.es2015.reflect.d.ts
	c:/typescript/built/local/lib.es2015.symbol.d.ts
	c:/typescript/built/local/lib.es2015.symbol.wellknown.d.ts
	c:/temp/callWithTimeout/src/index.ts
```

**Comment by DanielRosenwasser** [comment]
Let's chat tomorrow, but I would've figured we'd search through the `typeRoots`.

**Comment by sheetalkamat** [comment]
This is working as intended? As mentioned in https://github.com/microsoft/TypeScript/issues/28831#issuecomment-444202202 the program does not contain rxjs so it cannot offer the fix? (@DanielRosenwasser rxjs is installed in node modules and not as `@types/rxjs` so its not typeroots)
