### ISSUE TITLE
Error: TS2393: Duplicate function implementation.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#28833]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** Duplicate function implementation.

**Code**

```ts
// => Error: TS2393: Duplicate function implementation.
function f()
{
	if (true)
	{
		throw new Error();
	}
}
console.log(1);
f();
console.log(2);
```

---

i know in https://github.com/Microsoft/TypeScript/issues/24925#issuecomment-414609525

it say can add `export {};`

> but with follow code, work as Expected => ReferenceError: f is not defined

so there is no `f` in global

```ts
console.log(1);
f();
console.log(2);
```

**Expected behavior:**

> should not have error

**Actual behavior:**

> Error: TS2393: Duplicate function implementation.

**Playground Link:** 

**Related Issues:**

**Comment by bluelovers** [comment]
@weswigham 

2 file all have `f`

video https://www.youtube.com/watch?v=rj8wdubGmf8&feature=youtu.be

```
ts\index.d.ts
ts\index.js
ts\index.ts

uglify\index.d.ts
uglify\index.js
uglify\index.ts
```

**Comment by weswigham** [comment]
Oh. Well, yeah. Both of those files are interpreted as being globally scoped, so we see two definitions of `f` in the global scope, which isn't good.

**Comment by bluelovers** [comment]
but they didn't use together

i think should not check this

**Comment by Ln2be** [comment]
Yes This must be a bug why all the files in the same folder are globally scopes
