### ISSUE TITLE
import statement not emitted in declaration file

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#28847]
**Search Terms:**
import statement not emitted

**Code**

```sh
git clone https://github.com/ant-design/ant-design
cd ant-design
npm install
npm run compile
ed lib/input/TextArea.d.ts # [1]
```

**Expected behavior:**
lib/TextArea.d.ts has a property, TextArea.resizeObserver, that refers to ResizeObserver from 'resize-observer-polyfill', so the file should have an import statement for it. (components/input/TextArea.tsx is the origin of the d.ts file)

**Actual behavior:**
No import statement

[1] [ed is the standard text editor](https://www.gnu.org/fun/jokes/ed-msg.html)

**Comment by weswigham** [comment]
Was caused by a bug in the type declarations of a dependency of antd.
