### ISSUE TITLE
Errors using lib.d.ts from 1.0

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#2884]
Using lib.d.ts from 1.0, against 1.5 you get errors for missing types:

> error TS2318: Cannot find global type 'ClassDecorator'.
> error TS2318: Cannot find global type 'MethodDecorator'.
> error TS2318: Cannot find global type 'ParameterDecorator'.
> error TS2318: Cannot find global type 'PropertyDecorator'.
> error TS2318: Cannot find global type 'TypedPropertyDescriptor'.

The missing types are all related to decorators, and for users not using decorators the error should be suppressed.

**Comment by DanielRosenwasser** [comment]
Why has it not complained over `TemplateStringsArray`?

**Comment by mhegazy** [comment]
we only look for `TemplateStringsArray` if you are in e `--t=es6`
