### ISSUE TITLE
Record is K extends string in the documentation, but K extends keyof any in the definition

### ISSUE THREAD

**Issue by DaveEWrk** [Microsoft/TypeScript#28841]
The disparity was introduced with:  https://github.com/Microsoft/TypeScript/pull/23844/commits/42dee28025c9d8152806047a7bf7875dc86e3e3d#diff-6b0fdf6ed57a8252e88e968768986ae2

```
-type Record<K extends string, T> = {
+type Record<K extends keyof any, T> = {
```

The handbook https://www.typescriptlang.org/docs/handbook/advanced-types.html

```
type Record<K extends string, T> = {
    [P in K]: T;
}
```

Tried searching for definitions, keyof any, record

I'd expect the handbook and the library to match.

I can do Record<number, SomeType> in typescript@latest, but the handbook says that I shouldn't be able to.

**Comment by DanielRosenwasser** [comment]
Should be in the next website publish.

**Comment by DanielRosenwasser** [comment]
(and thanks for filing!)
