### ISSUE TITLE
Define function type without overriding given parameters

### ISSUE THREAD

**Issue by C-Higgins** [microsoft/TypeScript#28852]
In the below example, type returnsStringFunc attempts to describe a function which takes anything, and returns an inner function like `(innerParam: string) => string`. This type could then be applied to functions A-D, and the type of `innerParam` would be known. To accomplish this, as far as I can tell, you must write the params as `(...args: any[])`. However, you then lose the specific param information of the functions you apply this type to.

```typescript
type returnsStringFunc = (...args: any[]) => (innerParam: string) => string

// This function knows innerParam is a string
const funcA: returnsStringFunc = () => {
	return (innerParam) => innerParam
}

// This function doesn't know what innerParam is (implictly 'any')
const funcB = () => {
	return (innerParam) => innerParam
}


// This function knows innerParam is a string
const funcC: returnsStringFunc = (prefix: string) => {
	return (innerParam) => prefix + innerParam
}

// This function doesn't know what innerParam is (implictly 'any')
const funcD = (prefix: string) => {
	return (innerParam) => prefix + innerParam
}


funcA(1) // No error, passing argument to function which should have none
funcB(1) // Expected 0 arguments, but got 1
funcC(1) // No error, passing number when prefix should be string
funcD(1) // 1 is not string
```

Once the type `returnsStringFunction` is applied to a function, that function's params are cast as any[]. It would be useful for the params of funcA-D to stay visible to the compiler somehow, while still being able to define their type signature.

**Comment by AnyhowStep** [comment]
It doesn't make sense for `funcB` to be inferred to be `returnsStringFunc`.
Maybe `() => <T>(innerParam : T) => T` or something similar.

Neither does it make sense for `funcD` to be inferred to be `returnsStringFunc`.
Maybe `(prefix : string) => (innerParam : any) => string`

-----

What is your specific use case?

Does the following code snippet help in any way?

```ts
type StringFunctionFactory = (
    (...args: any[]) => (
        (innerParam : string) => string
    )
);
declare function foo<T extends StringFunctionFactory>(t: T): (
    T
);

//() => (innerParam: string) => string
const funcA = foo(() => {
    return (innerParam) => innerParam
});
//(prefix: string) => (innerParam: string) => string
const funcC = foo((prefix: string) => {
    return (innerParam) => prefix + innerParam
});

```

**Comment by C-Higgins** [comment]
I know it doesn't make sense for them to be inferred as that type, but I'd like a way to apply that type to the function without losing the params definitions. Your code snippet essentially works, but it requires calling the functions like `funcA()('a')` and isn't really idiomatic. 
Of course I can simply define the return value, such as 
```typescript
const funcA = (): (innerParam: string) => string => {
	return (innerParam) => innerParam
}
```
This will do what I want. But I'd like a way to generalize and apply this information to the outer function itself, rather than just defining the return value. Then I could use that type definition in interfaces etc, as a whole function type rather than just a return type.

**Comment by zanona** [comment]
Same here...based on my understanding, I have:

### file1.ts
```ts
export type DocChangeCallback = (changeType: DocumentChangeType, doc: object) => void;
```

### file2.ts

```ts
import {DocChangeCallback} from './file1';

const cb:DocChangeCallback = function (changeType, doc) {
   ...
}
```

So I really don't want to redefine the exact same interface as for `DocChangeCallback` again but I keep getting the warning: `expected ... to have a typedef` first for the call signature and then the function params.

Because at the moment I would be required to do this:

```ts
import {DocumentChangeType} from './whatever';
import {DocChangeCallback} from './file1';

const cb:DocChangeCallback = function (changeType: DocumentChangeType, doc: object): void {
   ...
}
```

which would basically require defining the same interface defined in __file1.ts__ again.

Is there any way to having the type of the function and its params be inferred from its type?
