### ISSUE TITLE
type detect fail when member overwrite with function

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#28855]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**

**Code**

when `IOptions<T>` have `sortCompareFn`, overwrite not as expected
it should know as function, and popup as function

```ts
export declare type ITSDiff<T extends keyof any, U extends keyof any> = ({
	[P in T]: P;
} & {
	[P in U]: never;
} & {
	[x: string]: never;
})[T];

export declare type ITSOverwrite<T, U> = Pick<T, ITSDiff<keyof T, keyof U>> & U;

export interface IOptions<T>
{
	sortCompareFn?: boolean | ((a: T, b: T) => number),
}

export type IOptionsRuntime<T> = ITSOverwrite<IOptions<T>, {
	sortCompareFn?(a: T, b: T): number,
}>

export let o: IOptionsRuntime<string>

// should know as function, and popup as function
o.sortCompareFn('', '')
```

**Expected behavior:**

> everything should same as when `IOptions<T>` didn't have `sortCompareFn`

```ts
export interface IOptions<T>
{
	//sortCompareFn?: boolean | ((a: T, b: T) => number),
}
```

![image](https://user-images.githubusercontent.com/167966/49480603-4ef59180-f862-11e8-83f9-02cd88c0bf82.png)

**Actual behavior:**

video https://www.youtube.com/watch?v=xhgvIZx-zkg

![image](https://user-images.githubusercontent.com/167966/49480630-63d22500-f862-11e8-8005-bc4efc5267ea.png)

**Playground Link:** 

**Related Issues:**

**Comment by weswigham** [comment]
What version of the compiler are you using? your example checks just fine [in the playground](http://www.typescriptlang.org/play/#src=export%20declare%20type%20ITSDiff%3CT%20extends%20keyof%20any%2C%20U%20extends%20keyof%20any%3E%20%3D%20(%7B%0D%0A%09%5BP%20in%20T%5D%3A%20P%3B%0D%0A%7D%20%26%20%7B%0D%0A%09%5BP%20in%20U%5D%3A%20never%3B%0D%0A%7D%20%26%20%7B%0D%0A%09%5Bx%3A%20string%5D%3A%20never%3B%0D%0A%7D)%5BT%5D%3B%0D%0A%0D%0Aexport%20declare%20type%20ITSOverwrite%3CT%2C%20U%3E%20%3D%20Pick%3CT%2C%20ITSDiff%3Ckeyof%20T%2C%20keyof%20U%3E%3E%20%26%20U%3B%0D%0A%0D%0Aexport%20interface%20IOptions%3CT%3E%0D%0A%7B%0D%0A%09sortCompareFn%3F%3A%20boolean%20%7C%20((a%3A%20T%2C%20b%3A%20T)%20%3D%3E%20number)%2C%0D%0A%7D%0D%0A%0D%0Aexport%20type%20IOptionsRuntime%3CT%3E%20%3D%20ITSOverwrite%3CIOptions%3CT%3E%2C%20%7B%0D%0A%09sortCompareFn%3F(a%3A%20T%2C%20b%3A%20T)%3A%20number%2C%0D%0A%7D%3E%0D%0A%0D%0Adeclare%20let%20o%3A%20IOptionsRuntime%3Cstring%3E%0D%0A%0D%0A%2F%2F%20should%20know%20as%20function%2C%20and%20popup%20as%20function%0D%0Aif%20(o.sortCompareFn)%20%7B%0D%0A%20%20o.sortCompareFn(''%2C%20'')%0D%0A%7D)

**Comment by bluelovers** [comment]
`3.3.0-dev.20181204`

this issue not about compile output code

can see video for what i mean https://www.youtube.com/watch?v=xhgvIZx-zkg

i use `ITSOverwrite<T, U>` overwrite `sortCompareFn` in `IOptions<T>`, make a new `IOptionsRuntime<T>`


```ts
export type IOptionsRuntime<T> = ITSOverwrite<IOptions<T>, {
	sortCompareFn?(a: T, b: T): number,
}>
```

should same as

```ts
export type IOptionsRuntime<T> = {
	sortCompareFn?(a: T, b: T): number,
}
```

but at `o.sortCompareFn` it not popup same thing

```
Process: TypeScript service version: 3.3.0-dev.20181204
Process: Default service options: {"module":1,"target":6,"moduleResolution":2,"allowJs":false,"sourceMap":true,"inlineSourceMap":true,"inlineSources":true,"declaration":true,"experimentalDecorators":true,"allowSyntheticDefaultImports":true,"resolveJsonModule":true,"noImplicitUseStrict":true,"strict":false,"locale":"zh-TW","pretty":true,"removeComments":false,"traceResolution":true,"newLine":1,"configFilePath":"D:/Users/Documents/The Project/nodejs-yarn/ws-ts-uglify/tsconfig.json"}
```

**Comment by weswigham** [comment]
I'm pretty sure the same completions are returned in both cases, just a different order.

**Comment by bluelovers** [comment]
alright...

any way can know what type is typescript service return for ide

for next time i can check it is ide issue or typescript issue?

**Comment by weswigham** [comment]
Most IDE issues are our issues, I'm just not sure the exact order of apparent type members is something we actually monitor, since I think by default it'll just be sorted based on the order the properties were found (if we have nothing in particular informing relevance).
