### ISSUE TITLE
TS2304: Cannot find name 'JSON'

### ISSUE THREAD

**Issue by sdeering** [Microsoft/TypeScript#28858]
Potential bug when upgrading to Angular 7 and Typescript 3.2.0. Using IntelliJ.

TS2304: Cannot find name 'JSON'

<img width="632" alt="screen shot 2018-12-05 at 3 08 26 pm" src="https://user-images.githubusercontent.com/1787454/49492088-969c0d80-f8a2-11e8-9808-74b5b471ee26.png">

**Comment by sdeering** [comment]
Deleting node_modules and npm install seems to have fixed it.

**Comment by rhythm010** [comment]
Even after deleting node modules and then doing npm install, the error persists.
![image](https://user-images.githubusercontent.com/17495625/53408673-17bbfa00-39e5-11e9-9030-a65bf7c5d57c.png)

**Comment by makkasi** [comment]
Same for me. Reinstall with npm doesn't work.

**Comment by geiseri** [comment]
I just hit this too for a new project.  I have another project that works, but I am running `code-server` with typescript 3.4.4 building with webpack for node 8.  So there are a lot of moving parts.  I am going to try to break it down and see if there is rhyme or reason.  I see this reported on other projects, and usually, the solution for some people involves a mixture of `tsconfig.json` tweaks to the library target and installing specific `@type/` packages.  There doesn't seem to be consistency though, so I think it is a tooling configuration problem.

**Comment by strass** [comment]
I'm hitting the same issue as @geiseri 
I also see `Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.ts(2584)` even when my `lib` entry in `tsconfig.json` includes `dom`

**Comment by silasdavis** [comment]
I fixed this on an `es5` project by adding `es5` to `tsconfig.json`:

```json
{
  "files": [
    "src/index.ts"
  ],
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "declaration": true,
    "outDir": "lib/",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "lib": [
      "es5",
      "dom"
    ]
  }
}
```

**Comment by RahulBenzeen** [comment]
Cannot find name 'getJSON'.ts(2304)

**Comment by Ak-0024** [comment]
Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
/* To learn more about this file see: https://angular.io/config/tsconfig. */
 {
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "noImplicitOverride": true,
    "noImplicitAny":false, 
    "noPropertyAccessFromIndexSignature": false, 
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "strictPropertyInitialization": false,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "lib": [
      "DOM",
      "es2020"         
    ],   
    "target": "es2020",
    "module": "es2020",   
 
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
