### ISSUE TITLE
Inconsistent inferred overloads in conditional types for no-arg signatures with strictFunctionTypes

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript#28867]
**TypeScript Version:**  3.3.0-dev.20181205

**Search Terms:**
conditional type, infer, overload, no-arg, zero arguments, strictFunctionTypes

Note that this issue is not about the behavior where the last overload is examined in conditional type inference of a single signature, where some might expect [a union](https://github.com/Microsoft/TypeScript/issues/26591) or [an argument-based choice](https://github.com/Microsoft/TypeScript/issues/27027).  

**Code**
```ts
// turn on --strictFunctionTypes

type InferTwoOverloads<F extends Function> = 
  F extends { (...a1: infer A1): infer R1, (...a0: infer A0): infer R0 } ? 
  [(...a1: A1) => R1, (...a0: A0) => R0] : 
  never;

type Expected = InferTwoOverloads<((x: string) => number) & (() => string)>
// [(x: string) => number, () => string]    

type JustOneSignature = InferTwoOverloads<((x: string) => number)>;
// never

type JustTheOtherSignature = InferTwoOverloads<(() => string)>;
// [(...a1: unknown[]) => {}, () => string]
```

**Expected behavior:**
I would expect that either both `JustOneSignature` and `JustTheOtherSignature` would be `never`, or both `JustOneSignature` and `JustTheOtherSignature` would evaluate to a two-tuple where the first signature is... something.  I suppose `(...a1: unknown[])=>{}`?  Or maybe it should be a copy of one of the other overloads?  Or something in between?

**Actual behavior:**
It looks a zero-argument function is being treated pathologically during conditional type inference; if a type is callable with zero arguments, it will be considered assignable to any number of overloads with what looks like failed inference for the types of the arguments (`unknown[]`) and the return (`{}`).  Otherwise, if a type is only callable with at least one argument, it will only be considered assignable to the matching number of overloads.

This distinction only seems to happen with `--strictFunctionTypes` on.  If you turn it off, `JustOneSignature` above becomes `[(...a1: unknown[]) => {}, (x: string) => number]`, which is at least consistent with the zero-argument situation.  

**Playground Link:** 
[🔗](https://www.typescriptlang.org/play//#src=%2F%2F%20turn%20on%20--strictFunctionTypes%0A%0Atype%20InferTwoOverloads%3CF%20extends%20Function%3E%20%3D%20%0A%20%20F%20extends%20%7B%20%28...a1%3A%20infer%20A1%29%3A%20infer%20R1%2C%20%28...a0%3A%20infer%20A0%29%3A%20infer%20R0%20%7D%20%3F%20%0A%20%20%5B%28...a1%3A%20A1%29%20%3D%3E%20R1%2C%20%28...a0%3A%20A0%29%20%3D%3E%20R0%5D%20%3A%20%0A%20%20never%3B%0A%0Atype%20Expected%20%3D%20InferTwoOverloads%3C%28%28x%3A%20string%29%20%3D%3E%20number%29%20%26%20%28%28%29%20%3D%3E%20string%29%3E%0A%2F%2F%20%5B%28x%3A%20string%29%20%3D%3E%20number%2C%20%28%29%20%3D%3E%20string%5D%20%20%20%20%0A%0Atype%20JustOneSignature%20%3D%20InferTwoOverloads%3C%28%28x%3A%20string%29%20%3D%3E%20number%29%3E%3B%0A%2F%2F%20never%20%28turn%20on%20--strictFunctionTypes%2C%20I%20said%29%0A%0Atype%20JustTheOtherSignature%20%3D%20InferTwoOverloads%3C%28%28%29%20%3D%3E%20string%29%3E%3B%0A%2F%2F%20%5B%28...a1%3A%20unknown%5B%5D%29%20%3D%3E%20%7B%7D%2C%20%28%29%20%3D%3E%20string%5D)

**Related Issues:** 
* Not the same issue as #26591 or #27027, or the choose-last-overload behavior described in #21496
* Maybe related to #27439?
* Or maybe #22615?

**Comment by sirian** [comment]
As i mentioned in duplicate issue - problem not only in no arg function. also with `(x: unknown) => any`,  `(x: any) => any`, `(...args: unknown[]) => any` etc.

```ts
type Overloads<F> =
    F extends {
          (...args: infer A1): infer R1
          (...args: infer A2): infer R2;
      } ? {rule: 2, variants: [A1, R1] | [A2, R2]} :
    F extends {
          (...args: infer A1): infer R1;
      } ? {rule: 1, variants: [A1, R1]} :
    never;

declare const ok1: Overloads<(x: number) => boolean>;
// {rule: 1, variants: [[number], boolean]}

declare const ok2: Overloads<{(): 1; (x: number): 2}>;
// {rule: 2, variants: [[], 1] | [[number], 2]}

declare const wrong1: Overloads<() => boolean>;
// {rule: 2, variants: [[], boolean] | [unknown[], {}]}
// expected {rule: 1, variants: [[], boolean]}

declare const wrong2: Overloads<(...args: unknown[]) => boolean>;
// {rule: 2, variants: [unknown[], boolean] | [unknown[], {}]}
// expected {rule: 1, variants: [unknown[], boolean]}

declare const wrong3: Overloads<(x: unknown) => boolean>;
// {rule: 2, variants: [[unknown], boolean] | [unknown[], {}]}
// expected {rule: 1, variants: [[unknown], boolean]}

declare const wrong4: Overloads<(x: any) => boolean>;
// {rule: 2, variants: [[any], boolean] | [unknown[], {}]}
// expected {rule: 1, variants: [[any], boolean]}
```

**Comment by jcalz** [comment]
Relevant SO question: [How to use Parameters type on overloaded functions?](https://stackoverflow.com/questions/58773217/how-to-use-parameters-type-on-overloaded-functions)

**Comment by ahejlsberg** [comment]
When inferring between types with multiple signatures, we match the signatures pairwise from the bottom up. This is a fine strategy when the source and target have matching arities (number of signatures) and when the source arity is greater than the target arity. But when the source arity is less than the target arity we never make inferences to the excess signatures in the target. That is a suboptimal strategy because in the absence of inference candidates we infer the constraint (which in turn defaults to `unknown`) and that may end up producing very restrictive signatures.

We want to ensure that every signature in the target is matched with some signature in the source, so a better strategy is to infer between signatures pairwise from the bottom up and then infer from the first source signature to each of the excess target signatures. I will put up a PR to that effect.
