### ISSUE TITLE
Generic type inferred incorrectly for union of function types

### ISSUE THREAD

**Issue by alexfoxgill** [Microsoft/TypeScript#28862]
**TypeScript Version:**  3.2.1 (playground)

**Search Terms:** generic, infer, function return

**Code**

```ts
type Foo<A> = {
    type: "foo"
    (): A[]
}

type Bar<A> = {
    type: "bar"
    (): A
}

type FooBar<A> = Foo<A> | Bar<A>

type InferA<T> = T extends FooBar<infer A> ? A : never

type FooA = InferA<Foo<number>> // number | number[]
```

**Expected behavior:**
`FooA` is `number`

**Actual behavior:**
`FooA` is `number | number[]`

**Playground Link:** 
http://www.typescriptlang.org/play/#src=type%20Foo%3CA%3E%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22foo%22%0D%0A%20%20%20%20()%3A%20A%5B%5D%0D%0A%7D%0D%0A%0D%0Atype%20Bar%3CA%3E%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22bar%22%0D%0A%20%20%20%20()%3A%20A%0D%0A%7D%0D%0A%0D%0Atype%20FooBar%3CA%3E%20%3D%20Foo%3CA%3E%20%7C%20Bar%3CA%3E%0D%0A%0D%0Atype%20InferA%3CT%3E%20%3D%20T%20extends%20FooBar%3Cinfer%20A%3E%20%3F%20A%20%3A%20never%0D%0A%0D%0Atype%20FooA%20%3D%20InferA%3CFoo%3Cnumber%3E%3E%20%2F%2F%20number%20%7C%20number%5B%5D

**Related Issues:** 
None

**Comment by ahejlsberg** [comment]
We should check discriminants during type inference and only infer from types that match. Wouldn't be too hard to do.

**Comment by ahejlsberg** [comment]
A simpler repro:

```ts
type Item<T> = { kind: 'a', data: T } | { kind: 'b', data: T[] };

declare function foo<T>(item: Item<T>): T;

let x1 = foo({ kind: 'a', data: 42 });  // Ok, inferred T is number
let x2 = foo({ kind: 'b', data: [1, 2] });  // Error, inferred T is number[]
```
