### ISSUE TITLE
JS emitting stops in builder mode on simple errors (like unused code)

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#28877]
Steps to reproduce:

- close https://github.com/Microsoft/vscode-languageserver-node.git
- cd vscode-languageserver-node
- git co dbaeumer/projectReferences
- npm install
- npm run symlink
- open code
- npm run watch
- in code go to file protocol\src\main.ts
- at the beginning insert something like this
```
let dirk: string = 'dirk';

export function foo() {

}
```
- go to protocol\lib\main.js
- observe that neither dirk nor foo appears in the file.
- removing the `let dirk` makes it work.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior, otherwise we'd be unable to reliably do an up-to-date check later. TS doesn't have a concept of simple vs important errors.

**Comment by dbaeumer** [comment]
@RyanCavanaugh I would really like to see this addressed. It makes project references very hard to use since it makes compilation stop even on things like unused locals. Since tools might render those as warnings and not errors this is a very frustrating experience.
