### ISSUE TITLE
Assignment of generic class fails when return type of method has index signature

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#28876]
**TypeScript Version:**  3.3.0-dev.20181129

**Search Terms:** assignment, generic, return, method, index signature

**Code**

I don't even know how to describe this problem. Or how to title it.

Below is the smallest repro I could create.

```ts
type AssertDelegate<T> = () => T;

interface ColumnData {
    readonly tableAlias : string;
    readonly assertDelegate : AssertDelegate<any>;
}
type As<ColumnT extends Column<any>> = (
    {
        //If I comment this part, it works.
        //If I uncomment this part, it says the assertDelegate is the problem
        [tableAlias in ColumnT["tableAlias"]] : string
    }
);
export class Column<DataT extends ColumnData> {
    readonly tableAlias: DataT["tableAlias"];
    readonly assertDelegate: DataT["assertDelegate"];

    constructor(
        data: DataT
    ) {
        this.tableAlias = data.tableAlias;
        this.assertDelegate = data.assertDelegate;
    }
    returnThing () : As<this> {
        return null as any;
    }
}

declare const a : Column<{
    readonly tableAlias: "someAlias";
    readonly assertDelegate: AssertDelegate<string>;
}>;
declare const b : Column<{
    readonly tableAlias: "someAlias";
    readonly assertDelegate: AssertDelegate<string|null>
}>;

//Enable strictNullChecks AND strictFunctionTypes
//Expected: Assignment works
//Actual: Does not work
const c: typeof b = a;

const objA = a.returnThing();
const objB = b.returnThing();

//These assignments work whether the line above is commented or not 
const bAssignFromA: typeof objB = objA;
const aAssignFromB: typeof objA = objB;
```

**Expected behavior:**

With `strictNullChecks` and `strictFunctionTypes` enabled,
The assignment `const c: typeof b = a;` should work.

**Actual behavior:**

The assignment `const c: typeof b = a;` does not work.

It's weird because comment/uncommenting the specified line above triggers the problem. So, one would expect that the problem is with the index signature. However, the errors are pointing at the assert delegate.

This is breaking code for me because, intuitively, it should be assignable. But the reality is that it is not and I cannot figure out why.

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=type%20AssertDelegate%3CT%3E%20%3D%20()%20%3D%3E%20T%3B%0A%0Ainterface%20ColumnData%20%7B%0A%20%20%20%20readonly%20tableAlias%20%3A%20string%3B%0A%20%20%20%20readonly%20assertDelegate%20%3A%20AssertDelegate%3Cany%3E%3B%0A%7D%0Atype%20As%3CColumnT%20extends%20Column%3Cany%3E%3E%20%3D%20(%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%2F%2FIf%20I%20comment%20this%20part%2C%20it%20works.%0A%20%20%20%20%20%20%20%20%2F%2FIf%20I%20uncomment%20this%20part%2C%20it%20says%20the%20assertDelegate%20is%20the%20problem%0A%20%20%20%20%20%20%20%20%5BtableAlias%20in%20ColumnT%5B%22tableAlias%22%5D%5D%20%3A%20string%0A%20%20%20%20%7D%0A)%3B%0Aexport%20class%20Column%3CDataT%20extends%20ColumnData%3E%20%7B%0A%20%20%20%20readonly%20tableAlias%3A%20DataT%5B%22tableAlias%22%5D%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20DataT%5B%22assertDelegate%22%5D%3B%0A%0A%20%20%20%20constructor(%0A%20%20%20%20%20%20%20%20data%3A%20DataT%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20this.tableAlias%20%3D%20data.tableAlias%3B%0A%20%20%20%20%20%20%20%20this.assertDelegate%20%3D%20data.assertDelegate%3B%0A%20%20%20%20%7D%0A%20%20%20%20returnThing%20()%20%3A%20As%3Cthis%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20null%20as%20any%3B%0A%20%20%20%20%7D%0A%7D%0A%0Adeclare%20const%20a%20%3A%20Column%3C%7B%0A%20%20%20%20readonly%20tableAlias%3A%20%22someAlias%22%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20AssertDelegate%3Cstring%3E%3B%0A%7D%3E%3B%0Adeclare%20const%20b%20%3A%20Column%3C%7B%0A%20%20%20%20readonly%20tableAlias%3A%20%22someAlias%22%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20AssertDelegate%3Cstring%7Cnull%3E%0A%7D%3E%3B%0A%0A%2F%2FEnable%20strictNullChecks%20AND%20strictFunctionTypes%0A%2F%2FExpected%3A%20Assignment%20works%0A%2F%2FActual%3A%20Does%20not%20work%0Aconst%20c%3A%20typeof%20b%20%3D%20a%3B%0A%0Aconst%20objA%20%3D%20a.returnThing()%3B%0Aconst%20objB%20%3D%20b.returnThing()%3B%0A%0A%2F%2FThese%20assignments%20work%20whether%20the%20line%20above%20is%20commented%20or%20not%20%0Aconst%20bAssignFromA%3A%20typeof%20objB%20%3D%20objA%3B%0Aconst%20aAssignFromB%3A%20typeof%20objA%20%3D%20objB%3B)

**Comment by AnyhowStep** [comment]
It looks like I can have an object as a type param and get it to work... But only if I add an extra type parameter that `extends string` and pass that extra parameter to `As<>`

```ts
type AssertDelegate<T> = () => T;

interface ColumnData {
    readonly tableAlias : string;
    readonly assertDelegate : AssertDelegate<any>;
}
type As<TableAliasT extends string> = (
    {
        //OK Now
        [tableAlias in TableAliasT] : string
    }
);
//Introduced an extra type parameter TestT
export class Column<DataT extends ColumnData, TestT extends string> {
    readonly tableAlias: DataT["tableAlias"];
    readonly assertDelegate: DataT["assertDelegate"];

    constructor(
        data: DataT
    ) {
        this.tableAlias = data.tableAlias;
        this.assertDelegate = data.assertDelegate;
    }
    //Passed TestT as type arg
    returnThing () : As<TestT> {
        return null as any;
    }
}

declare const a : Column<{
    readonly tableAlias: "someAlias";
    readonly assertDelegate: AssertDelegate<string>;
}, "test">;
declare const b : Column<{
    readonly tableAlias: "someAlias";
    readonly assertDelegate: AssertDelegate<string|null>
}, "test">;

//OK Now
const c: typeof b = a;

const objA = a.returnThing();
const objB = b.returnThing();
 
const bAssignFromA: typeof objB = objA;
const aAssignFromB: typeof objA = objB;
```

[Playground](http://www.typescriptlang.org/play/#src=type%20AssertDelegate%3CT%3E%20%3D%20()%20%3D%3E%20T%3B%0A%0Ainterface%20ColumnData%20%7B%0A%20%20%20%20readonly%20tableAlias%20%3A%20string%3B%0A%20%20%20%20readonly%20assertDelegate%20%3A%20AssertDelegate%3Cany%3E%3B%0A%7D%0Atype%20As%3CTableAliasT%20extends%20string%3E%20%3D%20(%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%2F%2FOK%20Now%0A%20%20%20%20%20%20%20%20%5BtableAlias%20in%20TableAliasT%5D%20%3A%20string%0A%20%20%20%20%7D%0A)%3B%0A%2F%2FIntroduced%20an%20extra%20type%20parameter%20TestT%0Aexport%20class%20Column%3CDataT%20extends%20ColumnData%2C%20TestT%20extends%20string%3E%20%7B%0A%20%20%20%20readonly%20tableAlias%3A%20DataT%5B%22tableAlias%22%5D%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20DataT%5B%22assertDelegate%22%5D%3B%0A%0A%20%20%20%20constructor(%0A%20%20%20%20%20%20%20%20data%3A%20DataT%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20this.tableAlias%20%3D%20data.tableAlias%3B%0A%20%20%20%20%20%20%20%20this.assertDelegate%20%3D%20data.assertDelegate%3B%0A%20%20%20%20%7D%0A%20%20%20%20%2F%2FPassed%20TestT%20as%20type%20arg%0A%20%20%20%20returnThing%20()%20%3A%20As%3CTestT%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20null%20as%20any%3B%0A%20%20%20%20%7D%0A%7D%0A%0Adeclare%20const%20a%20%3A%20Column%3C%7B%0A%20%20%20%20readonly%20tableAlias%3A%20%22someAlias%22%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20AssertDelegate%3Cstring%3E%3B%0A%7D%2C%20%22test%22%3E%3B%0Adeclare%20const%20b%20%3A%20Column%3C%7B%0A%20%20%20%20readonly%20tableAlias%3A%20%22someAlias%22%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20AssertDelegate%3Cstring%7Cnull%3E%0A%7D%2C%20%22test%22%3E%3B%0A%0A%2F%2FOK%20Now%0Aconst%20c%3A%20typeof%20b%20%3D%20a%3B%0A%0Aconst%20objA%20%3D%20a.returnThing()%3B%0Aconst%20objB%20%3D%20b.returnThing()%3B%0A%20%0Aconst%20bAssignFromA%3A%20typeof%20objB%20%3D%20objA%3B%0Aconst%20aAssignFromB%3A%20typeof%20objA%20%3D%20objB%3B)

**Comment by AnyhowStep** [comment]
I found a workaround I can use for now but I'm still confused about the original error I was getting.

```ts
type AssertDelegate<T> = () => T;

interface ColumnData {
    readonly tableAlias : string;
    readonly assertDelegate : AssertDelegate<any>;
}
type As<ColumnT extends Column<any>> = (
    //Added this 
    ColumnT extends Column<infer DataT> ?
    {
        //OK now
        [tableAlias in DataT["tableAlias"]] : string
    } :
    never
);
export class Column<DataT extends ColumnData> {
    readonly tableAlias: DataT["tableAlias"];
    readonly assertDelegate: DataT["assertDelegate"];

    constructor(
        data: DataT
    ) {
        this.tableAlias = data.tableAlias;
        this.assertDelegate = data.assertDelegate;
    }
    returnThing () : As<this> {
        return null as any;
    }
}

declare const a : Column<{
    readonly tableAlias: "someAlias";
    readonly assertDelegate: AssertDelegate<string>;
}>;
declare const b : Column<{
    readonly tableAlias: "someAlias";
    readonly assertDelegate: AssertDelegate<string|null>
}>;

//OK now
const c: typeof b = a;

const objA = a.returnThing();
const objB = b.returnThing();
 
const bAssignFromA: typeof objB = objA;
const aAssignFromB: typeof objA = objB;
```
For some reason, the conditional type works

[Playground](http://www.typescriptlang.org/play/#src=type%20AssertDelegate%3CT%3E%20%3D%20()%20%3D%3E%20T%3B%0A%0Ainterface%20ColumnData%20%7B%0A%20%20%20%20readonly%20tableAlias%20%3A%20string%3B%0A%20%20%20%20readonly%20assertDelegate%20%3A%20AssertDelegate%3Cany%3E%3B%0A%7D%0Atype%20As%3CColumnT%20extends%20Column%3Cany%3E%3E%20%3D%20(%0A%20%20%20%20%2F%2FAdded%20this%20%0A%20%20%20%20ColumnT%20extends%20Column%3Cinfer%20DataT%3E%20%3F%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%2F%2FOK%20now%0A%20%20%20%20%20%20%20%20%5BtableAlias%20in%20DataT%5B%22tableAlias%22%5D%5D%20%3A%20string%0A%20%20%20%20%7D%20%3A%0A%20%20%20%20never%0A)%3B%0Aexport%20class%20Column%3CDataT%20extends%20ColumnData%3E%20%7B%0A%20%20%20%20readonly%20tableAlias%3A%20DataT%5B%22tableAlias%22%5D%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20DataT%5B%22assertDelegate%22%5D%3B%0A%0A%20%20%20%20constructor(%0A%20%20%20%20%20%20%20%20data%3A%20DataT%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20this.tableAlias%20%3D%20data.tableAlias%3B%0A%20%20%20%20%20%20%20%20this.assertDelegate%20%3D%20data.assertDelegate%3B%0A%20%20%20%20%7D%0A%20%20%20%20returnThing%20()%20%3A%20As%3Cthis%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20null%20as%20any%3B%0A%20%20%20%20%7D%0A%7D%0A%0Adeclare%20const%20a%20%3A%20Column%3C%7B%0A%20%20%20%20readonly%20tableAlias%3A%20%22someAlias%22%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20AssertDelegate%3Cstring%3E%3B%0A%7D%3E%3B%0Adeclare%20const%20b%20%3A%20Column%3C%7B%0A%20%20%20%20readonly%20tableAlias%3A%20%22someAlias%22%3B%0A%20%20%20%20readonly%20assertDelegate%3A%20AssertDelegate%3Cstring%7Cnull%3E%0A%7D%3E%3B%0A%0A%2F%2FOK%20now%0Aconst%20c%3A%20typeof%20b%20%3D%20a%3B%0A%0Aconst%20objA%20%3D%20a.returnThing()%3B%0Aconst%20objB%20%3D%20b.returnThing()%3B%0A%20%0Aconst%20bAssignFromA%3A%20typeof%20objB%20%3D%20objA%3B%0Aconst%20aAssignFromB%3A%20typeof%20objA%20%3D%20objB%3B)

**Comment by weswigham** [comment]
> The workaround for my specific use-case required me to create an interface that only had all the data of the class (so no methods, except for assertDelegate).

This has to do with type argument variance - variance is measured on a per-type-parameter basis and its measured based on how it's used. In the case of `Column`, `DataT` is _invariant_ because it is used both in a contravariant position (the `As<this>` in a return position), and in a covariant (the two member types) position. Thanks to this, neither is `a`'s type assignable to `'b'` or vice-versa. That's why splitting up the type parameters helped - then the variances were split between each member. The conditional type works around strict variance measurement by replacing the type parameter with an inferred copy - the variance measurement isn't copied with the type.

**Comment by AnyhowStep** [comment]
I think I'll need some time to digest this but thank you!
