### ISSUE TITLE
tsc --build emits into outDir AND next to source files

### ISSUE THREAD

**Issue by danielrentz** [Microsoft/TypeScript#28875]
**TypeScript Version:**  3.2.1

I have tried https://github.com/RyanCavanaugh/project-references-demo

and ``tsc -b tsproject.json`` emits the output files into the /lib directory as expected, but additionally generates (some of) these files again next to the *.ts source files which seems unexpected.

Example session:
```
> git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

> tsc --build tsproject.json

> git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        animals/animal.d.ts
        animals/animal.js
        animals/dog.d.ts
        animals/dog.js
        zoo/zoo.d.ts
        zoo/zoo.js
nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by sheetalkamat** [comment]
I think in the demo projects we need to add 
```
"files": [],
```

**Comment by danielrentz** [comment]
> I think in the demo projects we need to add
> 
> ```
> "files": [],
> ```

That leads to generating the embedded files only, but not the `lib` directory. :)

**Comment by sheetalkamat** [comment]
Need to have tsconfig-base that contains extending compiler options apart from this. Since @RyanCavanaugh is oof and I don't have permission to push changes to that branch, we will have to wait for him to fix this. Moving this issue to the demo repo

**Comment by sheetalkamat** [comment]
RyanCavanaugh/project-references-demo#4 created
