### ISSUE TITLE
Weird compilation peculiarity

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#28881]
I have this question on SO which isn't getting much love:

https://stackoverflow.com/questions/53648845/typescript-tsc-module-resolution-peculiarity

basically, I have a folder called `"express"` with an `index.ts` file in that folder. In several files, when I call:

```typescript
import {RequestHandler} from 'express';
```

it resolves to the `express/index.ts` file in my project instead of resolving to  `node_modules/express`, this seems very strange considering `from 'express'` is not referencing a relative path and therefore should look inside the nearest node_modules folder. Is there something about ts module resolution that I don't know about? It seems like a bug with `tsc` but maybe it's not.

**Comment by weswigham** [comment]
DO you have `moduleResolution` set to `node`?

**Comment by ORESoftware** [comment]
I think this is what I had:

```js
{
  "compilerOptions": {
    "allowJs": false,
    "pretty": true,
    "resolveJsonModule": true,
    "sourceMap": false,
    "skipLibCheck": true,
    "declaration": true,
    "baseUrl": ".",
    "target": "es6",
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "allowUnreachableCode": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017"
    ]
  },
  "compileOnSave": false,
  "exclude":  [
    "node_modules"
  ]
}

```

**Comment by sheetalkamat** [comment]
You can run tsc with —traceResolution to diagnose what’s happening
