### ISSUE TITLE
Type Guards on `this` should affect type parameters

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#28889]
**TypeScript Version:**  3.2.1-insiders.20181128

**Search Terms:** type guard this generic

**Summary**

In a `class MyClass<T>`, a type guard of the form `this is MyClass<T & Foo>` should constrain `T` to extend `Foo`.

**Alternative**

It might make more sense to instead allow type guards on generic parameters; eg, `isFoo(): T is Foo`.

**Code**

```ts
class FooBuilder<TWith> {
    private bar?: number;
    private qux?: number;

    private whatIsTWith?: TWith

    private hasBar(): this is FooBuilder<TWith | WithBar>{
        return !!this.bar;
    }
    private hasQux(): this is FooBuilder<TWith | WithQux>{
        return !!this.qux;
    }

    public specify(options: Options<TWith>) {
        if (this.hasBar()) {
            options.bar;
            this.whatIsTWith;
        }
        if (this.hasQux()) {
            options.qux;
        }
    }
}

class WithBar { private noStructuralTyping: undefined; }
class WithQux { private noStructuralTyping: undefined; }

type Options<TWith> =
      (WithBar extends TWith ? { bar: string } : {})
    & (WithQux extends TWith ? { qux: string } : {});

// Usage:
new FooBuilder<WithBar | WithQux>().specify({ bar: '', qux: '' });
```

**Expected behavior:**

Inside `if (this.hasBar())`, `TWith` should be constrained to extend `WithBar` and `options.bar` should exist.

**Actual behavior:**

`options` still has no properties.

With stricter compilation options, `this.whatIsTWith` has conflicting definitions.

**Playground Link:**  [Link](https://www.typescriptlang.org/play/#src=class%20FooBuilder%3CTWith%3E%20%7B%0A%20%20%20%20private%20bar%3F%3A%20number%3B%0A%20%20%20%20private%20qux%3F%3A%20number%3B%0A%0A%20%20%20%20private%20whatIsTWith%3F%3A%20TWith%0A%0A%20%20%20%20private%20hasBar()%3A%20this%20is%20FooBuilder%3CTWith%20%7C%20WithBar%3E%7B%0A%20%20%20%20%20%20%20%20return%20!!this.bar%3B%0A%20%20%20%20%7D%0A%20%20%20%20private%20hasQux()%3A%20this%20is%20FooBuilder%3CTWith%20%7C%20WithQux%3E%7B%0A%20%20%20%20%20%20%20%20return%20!!this.qux%3B%0A%20%20%20%20%7D%0A%0A%0A%20%20%20%20public%20specify(options%3A%20Options%3CTWith%3E)%20%7B%0A%20%20%20%20%20%20%20%20if%20(this.hasBar())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20options.bar%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.whatIsTWith%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20if%20(this.hasQux())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20options.qux%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20WithBar%20%7B%20private%20noStructuralTyping%3A%20undefined%3B%20%7D%0Aclass%20WithQux%20%7B%20private%20noStructuralTyping%3A%20undefined%3B%20%7D%0A%0Atype%20Options%3CTWith%3E%20%3D%0A%20%20%20%20%20%20(WithBar%20extends%20TWith%20%3F%20%7B%20bar%3A%20string%20%7D%20%3A%20%7B%7D)%0A%20%20%20%20%26%20(WithQux%20extends%20TWith%20%3F%20%7B%20qux%3A%20string%20%7D%20%3A%20%7B%7D)%3B%0A%0A%2F%2F%20Usage%3A%0Anew%20FooBuilder%3CWithBar%20%7C%20WithQux%3E().specify(%7B%20bar%3A%20''%2C%20qux%3A%20''%20%7D)%3B)
**Related Issues:**  #14817

**Comment by weswigham** [comment]
`options` is unrelated to `this` - there's no dependency between them. Narrowing `this` won't narrow `options`.

**Comment by SLaks** [comment]
If I move `options` to a field, `this.options` still isn't narrowed.

I'm expecting it to affect the `TWith` type parameter, in all usages.
