### ISSUE TITLE
export let variable in namespace should be compile error

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#28891]
## Outline
  - **TypeScript Version**: 3.3.0-dev.20181206
  - **Expected behavior**: Declaring `export let` variable in `namespace` be compile error.
  - **Actual behavior**: No compile error yet.

## Bug Report
```typescript
namespace Global
{
    export const OK = "It's ok";
    export var name: string = "It's possible";
    export let comment: string = "It should be compile error";
}
```

The `let` statement represents a *block scoped local variable*. However, in TypeScript, it is possible to declare `export let` variable in an `namespace`. If an `export` variable is defined in an `namespace`, I think it means a *global variable*. Considering spec of the `let` statement, I think `Global.commnet` should be compile error.

**Comment by weswigham** [comment]
A `export let` simply indicates a mutable exported binding, instead of a constant one.
