### ISSUE TITLE
this.__extends in wrapper-function

### ISSUE THREAD

**Issue by vasa-c** [Microsoft/TypeScript#2889]
The code

```typescript
class A {}

class B extends A {}
```

Compiled to

```javascript
var __extends = this.__extends || function (d, b) {
    // ...
};

var A = (function () {
    // ...
})();

var B = (function (_super) {
    // ...
})(A);
```

Often resulting files can be handled in a specific way.
For example, CommonJS module:

```javascript
"use strict";

define("moduleName", function (exports, require, module) {
    var __extends = this.__extends || function (d, b) {
        // ...
    };
    var A = (function () {
        // ...
    })();    
    // ...
});
```

In the strict mode `this` inside functions is NULL.
`this.__extends` leads to `cannot read property __extends of undefined`.

My solution: `__extends = (this && this.__extends) || function`.
Or delete `this.__extends` completely (why do we need it?).

**Comment by RyanCavanaugh** [comment]
Please see #1622 (specifically Ron's comment at the bottom)
