### ISSUE TITLE
Why `window.location.reload(true)` is deprecated?

### ISSUE THREAD

**Issue by dizys** [microsoft/TypeScript#28898]
It seems in 3.2.1 deprecated is added to `window.location.reload(boolean)` in `lib.dom.d.ts`. I couldn't find anything related in the What's new doc or the release note.

Could I please know why it is deprecated and what is the alternative way to do it?

```ts
    /** @deprecated */
    reload(forcedReload: boolean): void;
```

**Comment by weswigham** [comment]
Only the `forcedReload` flag overload is deprecated. I can't speak as to why, however = that info is pulled from the webIDL. If i had to guess, it's because the parameter isn't in the actual [spec](https://www.w3.org/TR/html50/browsers.html#dom-location-reload).

**Comment by dizys** [comment]
Thanks for replying. That will explain it. Though in browser context, `forcedReload` flag seems to be pretty irreplaceable. I'm not sure if `@deprecated` suits it. Now my solution is to simply disable tslint for this usage. I hope there's a better workaround.

**Comment by jkon** [comment]
Can anyone tell me another way to get the same result as using the ``` forcedReload ``` parameter here? I want to force the cache to be ignored when a new version of my application is discovered by a polling function and to let the user click a button that will reload the app with the new version. using the ``` forcedReload ``` parameter seems like the best solution, but I'm not sure why it would be deprecated.

**Comment by hktr92** [comment]
from the spec:
> User agents **may allow the user to explicitly override any caches when reloading**. If browsing context's active document's reload override flag is set, then **the user agent may instead perform an overridden reload** rather than the navigation described in this paragraph (with the browsing context being reloaded as the source browsing context).

to me it appears that it refers to "forceGet" flag of the method. or did i understand badly?

**Comment by jkon** [comment]
> to me it appears that it refers to "forceGet" flag of the method. or did i understand badly?

I'm not sure I understand what you're trying to explain. And it doesn't help me find another solution if forceReload or forceGet as you say is deprecated. @hktr92, can you give me an example?

**Comment by hktr92** [comment]
@jkon 

in [this spec](https://www.w3.org/TR/html50/browsers.html#dom-location-reload), the `forceGet` parameter is loud and clear.

but in this ["latest" spec](https://html.spec.whatwg.org/#dom-location-reload), there's no mention of it at all, not even deprecation one, but there's a subtle reference that the parameter might be present:

> User agents may allow the user to explicitly override any caches when reloading.

**Comment by estradanic** [comment]
Why does there seem to be a vendetta from nearly every web technology organization against any way to invalidate cache reliably?

**Comment by dimitridumont** [comment]
I created a small package in order to have a solution to clean the cache and reload the page if necessary 😅 : https://www.npmjs.com/package/clear-cache

**Comment by HolgerJeromin** [comment]
> I created a small package in order to have a solution to clean the cache and reload the page if necessary 😅 

Off topic, but your code not not clean the internal browser cache and does not reload the page (on a non secure origin). 
ref https://github.com/dimitridumont/clear-cache/issues/1

**Comment by ronaldgevern** [comment]
The reload() function takes an optional parameter that can be set to true to force a reload from the server rather than the cache. Since window.location.reload(true) has been deprecated, changing location.reload(true) to location.reload() to resolve your issue. Also, you can use:

`window.location.href = window.location.href;`

There are multiple ways to [Refresh](http://net-informations.com/jq/events/refresh.htm)/Reload a page with jQuery/JavaScript, some are:

```
location.replace(location.pathname)
window.location = window.location
window.self.window.self.window.window.location = window.location
```
