### ISSUE TITLE
Please consider colourising aliases (Visual Studio)

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#2890]
In the image below, I would like to see `bar` in `var b: bar.Baz` to have colour.

![image](https://cloud.githubusercontent.com/assets/1106823/7299670/35acd42c-e9cf-11e4-8f7e-90732cca885f.png)

The alias declaration itself should also be colourised: `import bar /*here*/ = foo.bar`

**Comment by mhegazy** [comment]
@NoelAbrahams i assume you want to have a different class as well for aliases? is that correct?

**Comment by NoelAbrahams** [comment]
@mhegazy, did you mean "a different ***colour*** as well for aliases"? If so I don't think that would be necessary, because semantically an alias is exactly the same as the type it represents, no?

**Comment by mhegazy** [comment]
make sense.

**Comment by paulvanbrenk** [comment]
Another issues here is that the bars in the `import bar = foo.bar;` statement both should be colorized the same (as a module in this case).

**Comment by mhegazy** [comment]
@CyrusNajmabadi this can be related to Quick infor changes for aliases in #3025

**Comment by PFight** [comment]
It's very actual when using ES6 modules. For example, I have class `NormalRandomNumber` in `common/random-number.ts`. So, I use this class in other places like this:

    import { NormalRandomNumber } from "./common/random-number";
   
    let myNumber = new NormalRandomNumber(); // Not highlighted as a class!

Because I use ES6 modules for every class (following the standard and SystemJS requirements), none of my classes highlighted as calsses at all. It should be priporitized, thought.

**Comment by Odiriuss** [comment]
Is there any plans at all to implement this? It's very frustrating to work with code that's not properly highlighted...

**Comment by scottdurow** [comment]
I am using TypeScript Intellisense 2.3 and I see that aliases are still not highlighted as types - is there an ETA on this feature?

**Comment by nazar-kuzo** [comment]
TypeScript 2.4.2 still have same issues in VS 2015, VS 2017, VS Code. @mhegazy, is there an ETA on this improvement?
