### ISSUE TITLE
Auto complete custom element tags in TSX not working with hyphen in name

### ISSUE THREAD

**Issue by Cammisuli** [microsoft/TypeScript#28905]
When using tsx to develop components for custom elements (web components), auto complete does not show element names that have a `-` in it's name.

I'm using https://stenciljs.com/ to create these components, and custom element names are added to an extended `InstrinsicElements` interface. Which looks like this:
```typescript
interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'app-tester': Components.AppTesterAttributes;
    'tester2': Components.Tester2Attributes;
  }
```

- VSCode Version: 
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS: Windows 10

Steps to Reproduce:
Repo here - https://github.com/Cammisuli/tsx-completion-bug

Preview of issue discussed:
- Not working
![auto-complete-tsx-hyphen](https://user-images.githubusercontent.com/4332460/49653609-7899ee80-fa03-11e8-8d94-da9cc9f7f579.gif)

- Working
![auto-complete-tsx](https://user-images.githubusercontent.com/4332460/49653703-c1ea3e00-fa03-11e8-8394-5b479c8bee36.gif)

After either element is added, hovering over it shows the proper type of the element. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Cammisuli** [comment]
This is actually something I would like to see fix. If help is needed to get this going, I'm more than willing to try to create a PR; I would just need to get some direction on where to look/debug. 

Thanks!

**Comment by zavr-1** [comment]
WHY ARE YOU NOT FIXING THIS MICROSOFT.

[The Software Engineering Code of Ethics and Professional Practice](https://ethics.acm.org/code-of-ethics/software-engineering-code/)

> 1.07. Consider issues of physical disabilities, allocation of resources, economic disadvantage and other factors that can diminish access to the benefits of software.

All React's _Aria_ tags use hyphens. When people start typing `aria` for an attribute, they cannot discover it in VSCode because of this BUG! People are less likely to discover and pay attention to accessibility because of that. 

STOP BREAKING SOFTWARE ENGINEERING CODE AND IMPLEMENT ESSENTIAL FUNCTIONALITY!!!

**Comment by Jack-Works** [comment]
I think I can fix it. Let me have a try...
The reason of this bug is https://github.com/microsoft/TypeScript/blob/f9945f5acfe24664c446e990eeecc7c00f700c99/src/services/completions.ts#L2415 here filter out the hyphened name because TypeScript thinks it isn't a valid identifier name.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/76981423-8a43a300-6975-11ea-87a7-936d36591137.png)

OK I get it

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/76981580-c414a980-6975-11ea-9418-322855b471f3.png)

Another screenshot

**Comment by bkelley13** [comment]
This would be very helpful to fix, Jack-works!  Many thanks for your efforts.
