### ISSUE TITLE
TypeScript compiler fails in ES5 environment

### ISSUE THREAD

**Issue by arktronic** [Microsoft/TypeScript#28918]
The TypeScript compiler fails to run in the latest stable version of Jint (an ES5 environment) as of version 3.1 and above. The apparent issue is the use of `Set`, which does not exist prior to ES2015. [Additional context tweet.](https://twitter.com/drosenwasser/status/1071221131552538624)

**TypeScript Version:**  3.2.2

**Code**

[Executing the compiler in Jint issue reproduction](https://github.com/arktronic/jint-ts-issue/blob/master/jint-ts-issue/Program.cs)

The repro app executes the same trivial compilation code against TypeScript 3.0.3, which works, and then 3.2.2, which fails. The failure occurs while executing the `typescriptServices` JS [file itself](https://github.com/arktronic/jint-ts-issue/blob/master/jint-ts-issue/Program.cs#L31), not while running the `ts.transpileModule` code.

Output from repro app:

```
--Works--
Result: var x = 'string';

--Fails--
Exception: ReferenceError: Set is not defined
```

**Expected behavior:**

Compiler executes successfully in Jint.

**Actual behavior:**

Jint throws an exception (see above for exception message).

**Comment by j-oliveras** [comment]
Git blame says that all uses of Set are from PR #26588 by @andy-ms:
https://github.com/Microsoft/TypeScript/blob/fe1ba9bee37e54dad7a08d3d98c39d1e770e918f/src/compiler/inspectValue.ts#L41-L44

https://github.com/Microsoft/TypeScript/blob/fe1ba9bee37e54dad7a08d3d98c39d1e770e918f/src/compiler/inspectValue.ts#L107-L110

**Comment by DanielRosenwasser** [comment]
Thanks everyone!
