### ISSUE TITLE
lib.esnext.bigint.d.ts not found

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#28910]
**TypeScript Version:**  3.2
If you try to compile with this .tsconfig
```
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": false,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "noEmit": true,
    "strict": true,
    "baseUrl": ".",
    "lib": [
      "es2017",
      "esnext",
      "dom"
    ]
  },
  "exclude": [ "node_modules" ]
}
```

**Search Terms:** bigint esnext

**Expected behavior:**
Compiles without errors
**Actual behavior:**
```TS6053	Build:File 'C:/Users/Olmo/.nuget/packages/microsoft.typescript.msbuild/3.2.1/tools/tsc/lib.esnext.bigint.d.ts' not found```

Digging inside, the lib.esnext.d.ts contains:
```
/// <reference lib="es2018" />
/// <reference lib="esnext.asynciterable" />
/// <reference lib="esnext.array" />
/// <reference lib="esnext.bigint" />
/// <reference lib="esnext.symbol" />
/// <reference lib="esnext.intl" />
```
But esnext bigint is not there,

![image](https://user-images.githubusercontent.com/720953/49674492-7a4ecb00-fa72-11e8-8b6f-dfd78f9efb14.png)

Same thing in C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.2

**Comment by olmobrutall** [comment]
BTW: Removing "esnext" from the tsconfig.json solves de problem for now.

**Comment by weswigham** [comment]
@DanielRosenwasser can you doublecheck that our published VS SDK actually has all the lib files? o.O

**Comment by weswigham** [comment]
@minestarks should have a 3.2 SDK build out with the fix in the near future.

**Comment by minestarks** [comment]
TS 3.2.2 up on Nuget now which should fix the issue.
