### ISSUE TITLE
type of generic enum

### ISSUE THREAD

**Issue by ranouf** [microsoft/TypeScript#28914]
Hi,

I would like to create a master class which will help to display list and avoid repetitive code.

```
export enum NotificationSorting {
    SortByAction = "SortByAction", 
    SortByCreatedAt = "SortByCreatedAt", 
    SortByCreatedBy = "SortByCreatedBy", 
}
```

If i do this in my child class, I can see that notificationSorting is typeof NotificationSorting

```
public notificationSorting = NotificationSorting;
```

But if i decide to do that in a master class, i have an error:
```
export abstract class ListComponent<T>
  public sorting = T;
```

> T only refers to a type but it uses as a value.

Is there a way to do that?

Thanks

**Comment by weswigham** [comment]
You want a `:` and not an `=` - in the first example, you're setting the `notificationSorting` member equal to the object containing all the enum members, not declaring it as having a type of the enum.

**Comment by ranouf** [comment]
hi,

i really want to use =, : is completely different. try you will see :).

**Comment by AnyhowStep** [comment]
You want `public sorting : T;`

Then, instantiate with this,

`ListComponent<typeof NotificationSorting>`

Because this should work,

```ts
const t : typeof NotificationSorting = NotificationSorting;
```

**Comment by fatcerberus** [comment]
I’m going to go out on a limb here and guess that he wants to extract the enum *as a value* from it being passed in as a type parameter.  In which case... I don’t think that’s possible?

**Comment by ranouf** [comment]
Yes this works:
![image](https://user-images.githubusercontent.com/1764519/49955091-fb252100-fecf-11e8-9ef2-2b8c967fd4c3.png)

Now try to do that:
```
export class MyComponent extends MyBaseComponent<SampleSorting>{

}

export abstract class MyBaseComponent<T>{

  public t = T;
}
```

And you will have:

it could be nice to have:
`export abstract class MyBaseComponent<T extends enum>{ }`

But this is not possible ...

So, I m looking for an alternative way to do it. 

Do you have an idea?

**Comment by AnyhowStep** [comment]
Yeah, you can't "extract" the value from the type like that.

That would require something akin to reflection.
