### ISSUE TITLE
Unexpected space character between function call and tagged literal

### ISSUE THREAD

**Issue by NeekSandhu** [Microsoft/TypeScript#28925]
Assume the following code being compiled with target `es6` or `esnext`:

```typescript
const StyledDiv = styled.div`
	background: red
`
```
**Expected behavior:**
```javascript
const StyledDiv = styled_components_1.default('div')`
	background: red
`
```
**Actual behavior:**
```javascript
const StyledDiv = styled_components_1.default('div') `
	background: red
`
```
Because of the space character between function and template literal <code>...('div')█`...</code> StyledComponents don't work

**Comment by DanielRosenwasser** [comment]
What do you mean by "StyledComponents don't work"?

**Comment by NeekSandhu** [comment]
My apologies! there was an error in my own setup. Probably a `styled-components` <-> `react` version incompatibility. Maybe I wasn't using the latest version for either of them and thus tagged literals weren't behaving as expected.

**Comment by cedeber** [comment]
It looks like this is definitely a bug with the version 3.3.3333 while exporting to es2017

```
function test(...args) {}

const t = test`template literals`;
```

compiles to
```
function test(...args) { }
const t = test `template literals`;
```

**Comment by DanielRosenwasser** [comment]
That's just how our compiler formats its output, and that's not semantically different either, so it's not a bug.

**Comment by cedeber** [comment]
There is a space between `test` and `template literals` in the output. It won't work as tagged template literal.

**Comment by DanielRosenwasser** [comment]
Can you open a separate issue and show it not working in a JavaScript runtime?

**Comment by cedeber** [comment]
Ok, you're right, it works. I didn't know a space is allowed here. At least I learned something 😅. I was fighting with a bug related to that this morning - even this simple exemple didn't work - and after reopening the site to see the bug again, no more bug 🧐⁉️ Sorry for the waste of time.
