### ISSUE TITLE
enum member didn't show jsdoc desc 

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#28928]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:** enum desc

**Code**

enum member didn't show jsdoc desc 

```ts
export enum POSTAG {
	/**
	 * desc is name
	 */
	A_NR = 0x00000080,
}
```

**Expected behavior:**

when over POSTAG.A_NR show `desc is name`

**Actual behavior:**

only show value

![image](https://user-images.githubusercontent.com/167966/49695289-cfeeb900-fbd3-11e8-880f-5a6a69a25317.png)

**Playground Link:** 

**Related Issues:**

**Comment by aminpaks** [comment]
@bluelovers are you sure we're not missing `@`?
```js
export enum POSTAG {
	/**
	 * @desc is name
	 */
	A_NR = 0x00000080,
}
```
