### ISSUE TITLE
Allow overwriting types within projects

### ISSUE THREAD

**Issue by aminpaks** [microsoft/TypeScript#28922]
## Search Terms

- overwrite
- type definition

## Suggestion

I would like to have a way to overwrite an existing type (d.ts) provided by a module within `node_module` folder.

## Use Cases

Recently we put some effort to update jest types within DefinitelyType project but the maintainers are against the changes cause it adds more constraints and their argument is not everyone wants to strongly type their tests.  

This opens up for discussion what if some want to not copy the whole definition and just overwrite some? So it would be very useful to overwrite provided types within project.
## Examples

The main type definition would be using `any` to ease the use of library for everyone
```js
// node_modules/@types/jest/index.d.ts
...
interface SpyInstance<T, Y extends any[]> extends MockInstance<any, Y> {}
```

and we overwrite it within our project as following to benefit all the types:
```js
// Syntax could be different, I won't suggest any
declare namespace jest {
  interface SpyInstance<T, Y extends any[]> extends MockInstance<T, Y> {} 
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
> This opens up for discussion what if some want to not copy the whole definition and just overwrite some? So it would be very useful to overwrite provided types within project.

You can always just fork the `@types` package in situations like this. Generally, what you do is take the folder for the types you're intrested in, say, `@types/jest`, then copy that `jest` folder into a `types` folder within your project (not in `node_modules`, where you found it). Then adjust your dependency version  in your `package.json` from the number to the local path, eg `"@types/jest": "file:./types/jest"`. Then install packages again to let your local copy override/be symlinked over the one in `node_modules`, and edit as you please. The exact behavior is a little different depending on which `npm` version you use (older ones copy the folder rather than symlink it - on some versions the `file:` url fragment may not be required), but the process is generally the same.

This isn't necessarily perfect, but it works today and gets you the flexibility you want.

**Comment by aminpaks** [comment]
Of course it will work. My request is actually a design improvement and not a solution to incompatibility problem.
We could keep the maintanance to the minimum not because we didn’t like the way the library was typed but because it was intentionally done like that. The customization details to type more strongly should come from the maintainers of the project.

To me your solution simply burden the end user without discussion

**Comment by nasreddineskandrani** [comment]
@weswigham

what we can do is to add the ability to inherit a namespace and overwrite inside...
( "overwrite" and not "override" please)

//@types/jest
declare namespace jest {
 interface SpyInstance<T, Y extends any[]> extends MockInstance<any, Y> {}
}

// a library
declare namespace customJestForLibrary inherit jest {
 interface SpyInstance<T, any> extends MockInstance<T, Y> {} 
}

// project
declare namespace customJestForProject inherit jest {
 interface SpyInstance<T, Y extends any[]> extends MockInstance<T, Y> {} 
}


In my project i need to make sure to use `customJestForProject ` namespace for jest types.

One problem i see:
Alias seems to always fallback to the initial one
https://www.typescriptlang.org/play/index.html#src=declare%20namespace%20jest%20%7B%0D%0A%20interface%20BLA%3CT%3E%20%7B%20t%3A%20T%20%7D%20%0D%0A%7D%0D%0A%0D%0Adeclare%20namespace%20rot%20%7B%0D%0A%20interface%20BLA%3CT%3E%20%7B%20c%3A%20T%20%7D%20%0D%0A%7D%0D%0A%0D%0Adeclare%20type%20BLA%3CT%3E%20%3D%20jest.BLA%3CT%3E%3B%0D%0Adeclare%20type%20BLA%3CT%3E%20%3D%20rot.BLA%3CT%3E%3B%0D%0A%0D%0Aconst%20t%3A%20BLA%3Cnumber%3E%20%3D%20%7B%20c%20%3A%201%20%7D%3B

Which means we are depending on the Alias of `jest` if declared in @types/jest
so we need a way to overwrite those also.

I saw also one person posted here about namespace overwrite (another proposal)
https://github.com/Microsoft/TypeScript/issues/10187#issuecomment-238052919

thank you
