### ISSUE TITLE
`this` type in constructor interface will not be extended in sub class

### ISSUE THREAD

**Issue by ktsn** [Microsoft/TypeScript#28930]
**TypeScript Version:**  3.3.0-dev.20181208

**Search Terms:** constructor interface this extends sub class

**Code**

```ts
interface AConstructor {
    new (): AInstance
    a(): this
}

interface AInstance {
    a: string
}

declare const A: AConstructor 

declare function test<T extends typeof A>(a: T): T

class B extends A {
    b: string
}

const B1: typeof B = B.a() // Unexpected: Return type is AConstructor
const B2: typeof B = test(B) // Unexpected: Type parameter is inferred to AConstructor
```

**Expected behavior:**
The return type of `B.a()` and `test(B)` is `typeof B`.

**Actual behavior:**
The return type of `B.a()` and `test(B)` is `AConstructor`.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=interface%20AConstructor%20%7B%0D%0A%20%20%20%20new%20()%3A%20AInstance%0D%0A%20%20%20%20a()%3A%20this%0D%0A%7D%0D%0A%0D%0Ainterface%20AInstance%20%7B%0D%0A%20%20%20%20a%3A%20string%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20A%3A%20AConstructor%20%0D%0A%0D%0Adeclare%20function%20test%3CT%20extends%20typeof%20A%3E(a%3A%20T)%3A%20T%0D%0A%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%20%20%20%20b%3A%20string%0D%0A%7D%0D%0A%0D%0Aconst%20B1%3A%20typeof%20B%20%3D%20B.a()%20%2F%2F%20Unexpected%3A%20Return%20type%20is%20AConstructor%0D%0Aconst%20B2%3A%20typeof%20B%20%3D%20test(B)%20%2F%2F%20Unexpected%3A%20Type%20parameter%20is%20inferred%20to%20AConstructor

**Related Issues:** 
https://github.com/vuejs/vue-class-component/issues/294

Background: I've found this behaviour while investigating the above issue. This is caused by [recent changes for Vue's type declaration](https://github.com/vuejs/vue/commit/c711ec189aaf46399756e34d933ba5e0b6576c36#diff-fbf414ec0ed230cce681d1bb2c9b2d5dR114). It looks like the extending class does not match with the decorator type because `this` type is still base constructor type.

I'm still not sure if my guess is correct. If it is not true, please just let me know about that.

**Comment by HerringtonDarkholme** [comment]
It works when only interface involves. 

```ts
interface AConstructor {
    new (): AInstance
    a(): this
}

interface AInstance {
    c: string
}

declare const A: AConstructor 

declare function test<T extends AConstructor>(a: T): T

interface BConstructor extends AConstructor {
    b: string
}

declare const B: BConstructor

const B1: typeof B = B.a() // Good
const B2: typeof B = test(B) // Good
```

https://www.typescriptlang.org/play/#src=interface%20AConstructor%20%7B%0D%0A%20%20%20%20new%20()%3A%20AInstance%0D%0A%20%20%20%20a()%3A%20this%0D%0A%7D%0D%0A%0D%0Ainterface%20AInstance%20%7B%0D%0A%20%20%20%20c%3A%20string%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20A%3A%20AConstructor%20%0D%0A%0D%0Adeclare%20function%20test%3CT%20extends%20AConstructor%3E(a%3A%20T)%3A%20T%0D%0A%0D%0Ainterface%20BConstructor%20extends%20AConstructor%20%7B%0D%0A%20%20%20%20b%3A%20string%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20B%3A%20BConstructor%0D%0A%0D%0Aconst%20B1%3A%20typeof%20B%20%3D%20B.a()%20%2F%2F%20Unexpected%3A%20Return%20type%20is%20AConstructor%0D%0Aconst%20B2%3A%20typeof%20B%20%3D%20test(B)%20%2F%2F%20Unexpected%3A%20Type%20parameter%20is%20inferred%20to%20AConstructor

I

**Comment by fenying** [comment]
Maybe it same as this issue https://github.com/Microsoft/TypeScript/issues/26206#issuecomment-411233513

**Comment by DanielRosenwasser** [comment]
I believe what you really want is #5863.

**Comment by DanielRosenwasser** [comment]
I would suggest patching over https://github.com/vuejs/vue/pull/8595 to return `VueConstructor<V>` instead of `this`.

**Comment by DanielRosenwasser** [comment]
...like in https://github.com/vuejs/vue/pull/9173 😄

**Comment by ktsn** [comment]
Oh, I didn't realize #5863 is related. Thank you for pointing it out and suggestion!
Yes, it looks better to patch Vue side 🙂
