### ISSUE TITLE
A confusion about interface

### ISSUE THREAD

**Issue by shexm** [Microsoft/TypeScript#28934]
hello, i am studying typescript now.It is pretty good.However, there are some confusion in the process.
`interface Counter {
    (start: number): string;
    interval: number;
    reset(): void;
}
function getCounter(): Counter {
    let counter = <Counter>function (start: number) {};
    counter.interval = 123;
    counter.reset = function () { };
    return counter;
}`
`interface Counter {
    (start: number): void;
    interval: number;
    reset(): void;
}
function getCounter(): Counter {
    let counter = <Counter>function (start: number) {return '12'};
    counter.interval = 123;
    counter.reset = function () { };
    return counter;
}`
Why the first one performs well but the second meets a error.what is the mean for <interface> foo(){}?Is it  mean that a interface can be consider as a class and serves every class.Hope someone can understand what i mean.Thanks a lot.

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).
