### ISSUE TITLE
Provide Visual Studio LightBulb style fixup support for <reference> and import statements

### ISSUE THREAD

**Issue by gautamsi** [Microsoft/TypeScript#2893]
It would be really helpful to be able to fix import statements in editor by using ctrl+. or clicking lightbulb style in visual studio 2015. 

example from 2013 style c# using statement fix support.

![typescript_github_lightbulb](https://cloud.githubusercontent.com/assets/5769869/7305162/bf950872-e9b0-11e4-9078-bd31e0de2fd4.png)

TypeScript is being adapted for many large projects, being modular is also a goal for large projects. it would be nice to have these features.

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/11768
