### ISSUE TITLE
New Website Logo: Ecocion, Inc.

### ISSUE THREAD

**Issue by TomTom1229** [Microsoft/TypeScript#2894]
- Name: Ecocion, Inc.
- Homepage URL: http://Ecocion.com
- Brand Guidelines/Licensing: 
Must remain above 100px X 100px
Must remain square
Trademark Ecocion, Inc.
- Logo: https://ecocionacts.com/acts/images/vector/leafDark.svg

**Comment by jonathandturner** [comment]
Added.
