### ISSUE TITLE
Compilation errors for runtime exceptions caused by circular imports

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#28947]
## Search Terms

circular imports
circular dependency
dependency injection

## Suggestion

In a single file, you cannot use a variable before it is declared.

```ts
const a = b // Block-scoped variable 'b' used before its declaration. [2448]
const b = a
```

However, if these variables are split between multiple files, there is no compilation error, but there is a runtime error.

```ts
// a.ts
import { b } from "./b"
export const a = b

// b.ts
import { a } from "./a"
export const b = a
```

## Use Cases

The above example is contrived, but this sort of thing can become a big problem in a large project. I have a large project with 292k lines of TypeScript. We rely **heavily** on the type system for confidence that our application is going to work when we build and deploy. However, we have become increasingly plagued by runtime exceptions caused by circular dependencies.

Here's a slightly less contrived example to give a better understanding of how these problems arise. Suppose I have three files, in this case, representing people, but it practice, representing some logical separation between components of an application.

```ts
// tom.ts
export const favoriteColor = "red"

// joe.ts
import { favoriteColor as tomsFavoriteColor } from "./tom"
export const favoriteColor = "dark " + tomsFavoriteColor

// devon.ts
import { favoriteColor as joesFavoriteColor } from "./joe"
export const favoriteColor = joesFavoriteColor

// people.ts
import * as devon from "./devon"
import * as tom from "./tom"
import * as joe from "./joe"
console.log({ devon, tom, joe })

// Run the application
❯❯❯ ./node_modules/.bin/ts-node people.ts
{ devon: { favoriteColor: 'dark red' },
  tom: { favoriteColor: 'red' },
  joe: { favoriteColor: 'dark red' } }
```

Now suppose we want to add a `favoriteFood` to each person.

```ts
// devon.ts
import { favoriteColor as joesFavoriteColor } from "./joe"
export const favoriteColor = joesFavoriteColor
export const favoriteFood = "watermelon"

// joe.ts
import { favoriteColor as tomsFavoriteColor } from "./tom"
import { favoriteFood as devonsFavoriteFood } from "./devon"
export const favoriteColor = "dark " + tomsFavoriteColor
export const favoriteFood = "fried " + devonsFavoriteFood

// tom.ts
import { favoriteFood as devonsFavoriteFood } from "./devon"
export const favoriteColor = "red"
export const favoriteFood = devonsFavoriteFood


❯❯❯ ./node_modules/.bin/ts-node people.ts
{ devon: { favoriteColor: 'dark red', favoriteFood: 'watermelon' },
  tom: { favoriteColor: 'red', favoriteFood: undefined },
  joe:
   { favoriteColor: 'dark red', favoriteFood: 'fried undefined' } }
```

We just created a circular dependency which lead to tom's favorite food being undefined rather than a string which is what the type system expects it to be.

In practice, imagine you have 20-30 imports at the top of each of these files. And after you merge two branches that both worked independently, you end up breaking the application. This is really tedious to figure out.

I've read around about how to manage circular dependency issues and I haven't found anything terribly satisfying. None of them demonstrate how to organize your code in a way that the type system can verify for you. More than anything, I want to stress that I think it should be a goal that if a program compiles with TypeScript in strict mode, then the program should not crash due to an unexpected error.

## Ideas

Not sure what the best solution here is. But ideally, TypeScript should be able to analyze the import order of a program and look for errors similar to "Block-scoped variable 'b' used before its declaration. [2448]" based on the order the imports.

Furthermore, it would be really nice if there were a refactoring (maybe this is more of a VSCode feature request) which would suggest moving variables to different files to avoid the circular import. For example, we could separate favoriteFood and favoriteColor for each person into separate files which would fix the issue in that example.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
See discussion in #21780 around circular imports. There's a handful of `tslint` plugins which can help you detect and manage these cycles if they're problematic at execution time for your environment.

**Comment by ccorcos** [comment]
Hmm. @RyanCavanaugh has a good point in that PR -- I think throwing a compiler exception on a circular dependency is a bit too opinionated. However, throwing an exception on a circular dependency error is a bit less opinionated.

**Comment by ccorcos** [comment]
I've looked into the tslint plugin. Its been running for an hour on my project without halting...

Also everything I've looked at takes too extreme of an approach about this. I'm not interested so much in prevented ALL circular imports. I'm only interested in preventing runtime exceptions caused by circular imports. 

I think thats much more pragmatic approach that hasn't been considered in the other issues. For that reason, maybe you can consider removing the duplicate label to get some other eyes on this. It would be a really nice feature if TypeScript could solve this.

**Comment by weswigham** [comment]
> Also everything I've looked at takes too extreme of an approach about this. I'm not interested so much in prevented ALL circular imports. I'm only interested in preventing runtime exceptions caused by circular imports.

That still requires marking all circular imports as the lint rule does (and have you filed an issue on it saying it doesn't work well on large projects?). And, get this: We don't _know_ if a given circular import will cause an exception (and generally can't). The detailed runtime execution behavior of a circular import depends on the output module format, and, on top of that, execution order between modules can't actually be guaranteed, since modules may end up getting loaded in an arbitrary order (beyond satisfying dependency requirements) depending on environment, entrypoint, and runtime import cacheing.

**Comment by ccorcos** [comment]
> We don't know if a given circular import will cause an exception (and generally can't). The detailed runtime execution behavior of a circular import depends on the output module format, and, on top of that, execution order between modules can't actually be guaranteed, since modules may end up getting loaded in an arbitrary order (beyond satisfying dependency requirements) depending on environment, entrypoint, and runtime import cacheing.

Wow. So you're making this sound like a problem with the module system then, right?
