### ISSUE TITLE
String literal type should validate string during the cast

### ISSUE THREAD

**Issue by vovikdrg** [Microsoft/TypeScript#28955]
**Search Terms:**

**Code**

```ts
type MyLiteralType = 'prop1' | 'prop2' | 'prop3';

const property: MyLiteralType = 'prop4'; <-- I can see error here
const property2 = <MyLiteralType>'prop4';  <- but this will compile without any warnings
const property3 = 'prop4' as MyLiteralType; <- same as this
```

**Expected behavior:**
Casting should validate string 
**Actual behavior:**

Allow compile invalid string

**Comment by MartinJohns** [comment]
This would violate the TypeScript design principles, as it would require to output additional code for the type check.

This is also not a cast, it's a [type assertion](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions). It's a way of telling the compiler "shh little baby... trust me.. I know what I'm doing..".

> Type assertions are a way to tell the compiler “trust me, I know what I’m doing.” A type assertion is like a type cast in other languages, but performs no special checking or restructuring of data. It has no runtime impact, and is used purely by the compiler. TypeScript assumes that you, the programmer, have performed any special checks that you need.

It works as intended.
