### ISSUE TITLE
Copy asset files (e.g image, icon, etc) to the output folder

### ISSUE THREAD

**Issue by hanct** [Microsoft/TypeScript#28958]
Current typescript version: 3.1.6

Hi, I would like to request to provide an option in the tsconfig.js to include a list of static files (such as image, icon, etc), so that during transpilation, these files will also be copied over to the output directory.
**Use case:**
I am creating an electron app using typescript. Once transpiled the source codes, I also need to copy the package.json over to the output directory, which is a requirement as i wanted to package the output files into an executable program using a third party utility called electron-builder.

**Comment by DanielRosenwasser** [comment]
This isn't in the scope of TypeScript. You'll need to use an external build system for this.

**Comment by ShaMan123** [comment]
+1
