### ISSUE TITLE
Can't assign existing property to the rest of generic

### ISSUE THREAD

**Issue by klimashkin** [Microsoft/TypeScript#28952]
**TypeScript Version:**  3.2.2 and 3.3.0-dev.20181208

**Search Terms:**
- generic
- pick
- exclude
- spread

**Code**
```ts
interface AB {
  a: string;
  b: string;
}

function excludeA<T extends AB>(obj: T) {
  const {a, ...rest} = obj;

  rest.b = '3';

  return rest;
}

excludeA({ a: '1', b: '2', c: 'test' });
```

**Expected behavior:**
No errors

**Actual behavior:**
`Property 'b' does not exist on type 'Pick<T, Exclude<keyof T, "a">>'.`

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=interface%20AB%20%7B%0D%0A%20%20a%3A%20string%3B%0D%0A%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20excludeA%3CT%20extends%20AB%3E(obj%3A%20T)%20%7B%0D%0A%20%20const%20%7Ba%2C%20...rest%7D%20%3D%20obj%3B%0D%0A%0D%0A%20%20rest.b%20%3D%20'3'%3B%0D%0A%0D%0A%20%20return%20rest%3B%0D%0A%7D%0D%0A%0D%0AexcludeA(%7B%20a%3A%20'1'%2C%20b%3A%20'2'%2C%20c%3A%20'test'%20%7D)%3B

**Related**
https://github.com/Microsoft/TypeScript/issues/28821

**Comment by weswigham** [comment]
@klimashkin - Consider:
```ts
interface AB {
  a: string;
  b: string;
}

function excludeA<T extends AB>(obj: T) {
  const {a, ...rest} = obj;

  rest.b = '3';

  return rest;
}

interface ExactlyAB extends AB {
  a: "a";
  b: "b"
}

declare var exactAB: ExactlyAB;

excludeA(exactAB).b; // claims to be of type "b", but will be the value "3" with your implementation 
```

**Comment by weswigham** [comment]
(But in general yes, #28821 is the reason why the assignment doesn't work, even when you correctly assign a `T["b"]` - I just wanted to let you know that that code is unsafe from a typesystem perspective, even once that bug is fixed)

**Comment by que-etc** [comment]
@weswigham 
Does it mean that any reassignment of an object's property, which has a generic type, should be considered invalid?

```typescript
const test = <T extends {foo: string}>(obj: T): T => {
    // No errors as for v3.2.2. Is it a bug?
    obj.foo = 'bar';

    return obj;
};
```
[Playground](https://www.typescriptlang.org/play/index.html#src=const%20test%20%3D%20%3CT%20extends%20%7Bfoo%3A%20string%7D%3E(obj%3A%20T)%3A%20T%20%3D%3E%20%7B%0D%0A%20%20%20%20obj.foo%20%3D%20'bar'%3B%0D%0A%0D%0A%20%20%20%20return%20obj%3B%0D%0A%7D%3B).

**Comment by weswigham** [comment]
Yea - it's a known hole that gets closed when you use indexed access types. It's quite troublesome, really, since the only reason we haven't fixed it, AFAIK, is for backwards compatibility (and to make mutating patterns "easier" to type).

**Comment by klimashkin** [comment]
The issue has been fixed:
http://www.typescriptlang.org/play/?allowJs=true&target=6#code/JYOwLgpgTgZghgYwgAgJIHkBGArZBvAKGWOTgC5kQBXAW02gG4iTMLq7HniE3b6omAXwIEYVEAjDAA9iGSQAzmAA8AFWQQAHpBAATBWizYANMgDSG7RD0H0NYCtWmA5HGfIAPsmeZnAPmQAMnxkAC9eDgFkQT8ACmkcClUASgoLQhJkBFklfDhTTFMAOhKoCCVBZABeZATsJkzskFyACxp26uQy3LgDMyYuZDb2otDOgGYAJgHMsrAqKDlhmiERRTBYvHJkAEYCiknTHmRx010KABZBZKLdBiA
