### ISSUE TITLE
nominal typing in class

### ISSUE THREAD

**Issue by xiaoxiangmoe** [Microsoft/TypeScript#28956]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

class, nominal typing, structural typing
**Code**

```ts
interface A {
  color:string
}

interface B {
  color:string
}

const b:B = {
  color:'red'
}



function foo(a:A){
  return String(a)
}

foo(b)


class AA{
  constructor(color:string){
    this.color=color
  }
  color:string
}
class BB{
  constructor(color:string){
    this.color=color
  }
  color:string
}

const bb = new BB('red')


function bar(a:AA){
  return String(a)
}

bar(bb)
```

**Expected behavior:**

class should be nominal typing,
show error in `bar(bb)`

**Actual behavior:**

class be structural typing,
no error

**Playground Link:** 

[structural typing & nominal typing](https://www.typescriptlang.org/play/index.html#src=%0D%0Ainterface%20A%20%7B%0D%0A%20%20color%3Astring%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20color%3Astring%0D%0A%7D%0D%0A%0D%0Aconst%20b%3AB%20%3D%20%7B%0D%0A%20%20color%3A'red'%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0Afunction%20foo(a%3AA)%7B%0D%0A%20%20return%20String(a)%0D%0A%7D%0D%0A%0D%0Afoo(b)%0D%0A%0D%0A%0D%0Aclass%20AA%7B%0D%0A%20%20constructor(color%3Astring)%7B%0D%0A%20%20%20%20this.color%3Dcolor%0D%0A%20%20%7D%0D%0A%20%20color%3Astring%0D%0A%7D%0D%0Aclass%20BB%7B%0D%0A%20%20constructor(color%3Astring)%7B%0D%0A%20%20%20%20this.color%3Dcolor%0D%0A%20%20%7D%0D%0A%20%20color%3Astring%0D%0A%7D%0D%0A%0D%0Aconst%20bb%20%3D%20new%20BB('red')%0D%0A%0D%0A%0D%0Afunction%20bar(a%3AAA)%7B%0D%0A%20%20return%20String(a)%0D%0A%7D%0D%0A%0D%0Abar(bb))

**Comment by j-oliveras** [comment]
Duplicate/related to #202, #12936 and PR #28749.

**Comment by DanielRosenwasser** [comment]
P.S. @j-oliveras I really appreciate you helping out with these issues
