### ISSUE TITLE
Default values overwrite destructured function parameter type with basic type inference

### ISSUE THREAD

**Issue by seanmcintyre** [Microsoft/TypeScript#28963]
**TypeScript Version:**  3.2.2 and 3.3.0-dev.20181211

**Search Terms:** destructure, parameters, default, assignment, overload, sfc, react, tsx

**Code**

```ts
interface SFC<P = {}> {
  (props: P & { children?: any }): any | null;
}

interface Props {
  name: "Apollo" | "Artemis" | "Dionysus" | "Persephone";
}

const Parent: SFC<Props> = ({
  children,
  name = "Artemis",
  ...props
}) => <Child name={name} {...props} />;

const Child: SFC<Props> = ({
  children,
  name = "Artemis",
  ...props
}) => <div {...props}>{name}</div>;
```

**Expected behavior:**
`name` should be type `"Apollo" | "Artemis" | "Dionysus" | "Persephone"`.

**Actual behavior:**
Assigning a default value for `name` overwrites the type to `string`.
```
index.tsx:13:23 - error TS2322: Type 'string' is not assignable to type '"Apollo" | 
"Artemis" | "Dionysus" | "Persephone"'.

13 }) => <Child name={name} {...props} />;
                ~~~~
```

**Playground Link:** 

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/27927 https://github.com/Microsoft/TypeScript/issues/28835 https://github.com/Microsoft/TypeScript/issues/18191

**Comment by seanmcintyre** [comment]
However, this works correctly:
```
interface Props {
  children?: any;
  name: "Apollo" | "Artemis" | "Dionysus" | "Persephone";
}

const Parent = ({
  children,
  name = "Artemis",
  ...props
}: Props) => <Child name={name} {...props} />;

const Child = ({
  children,
  name = "Artemis",
  ...props
}: Props) => <div {...props}>{name}</div>;
```
but it is not tenable in many real-world React use cases.

**Comment by weswigham** [comment]
Destructuring initializer contextual types should be lower priority than any other contextual type. Right now in `getContextualTypeForInitializerExpression`, the `isBindingPattern(declaration.parent)` case doesn't actually recurse into `getContextualType` on the `.parent` - it only looks for annotations.
