### ISSUE TITLE
LanguageService Plugin cannot intercept 'getSupportedCodeFixes'

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#28966]
**TypeScript Version:**  3.3.0-dev.20181208

**Search Terms:**

getSupportedCodeFixes

**Expected behavior:**

`GetSupportedCodeFixes` calls `LanguageService#getSupportedCodeFixes`. LS plugins can intercept this call and add their own error codes for code fixes.

**Actual behavior:**

`GetSupportedCodeFixes` (indirectly) calls `codefix.getSupportedErrorCodes()` completely bypassing the LanguageService

**Comment by ajafff** [comment]
I wanted to fix this, but it turns out `getSupportedCodeFixes` doesn't get a fileName and therefore doesn't know which LanguageService to use. I'll open an issue with VSCode for that.

**Comment by mjbvz** [comment]
Plugins can already intercept this: https://github.com/Microsoft/typescript-tslint-plugin/blob/f4e06b17d0bb4db8a834af63dc1c8faa1c20bbea/src/plugin.ts#L72

Not correct but it does work

**Comment by mjbvz** [comment]
You may want to consider using the workaround. This change will require both a tsserver api change and editor adoption, which could take a while

**Comment by DanielRosenwasser** [comment]
Sounds like there's two changes

1. make this API take an optional `fileName` and `projectName`
2. make this API proxy-able
