### ISSUE TITLE
Mimicking JSX attributes behaviour with object types

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#28960]
## Search Terms

jsx object invalid data attribute nested component react

## Suggestion

We have this behaviour for JSX:

> Note: If an attribute name is not a valid JS identifier (like a data-* attribute), it is not considered to be an error if it is not found in the element attributes type.

https://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking

``` ts
import React, { FC } from 'react';

const MyComponent: FC<{ myProp: string }> = props => null;
<MyComponent myProp="foo" data-test="foo" />;
```

I want this same behaviour but for object types. This is necessary for times when we want to pass some props as a nested object (for whatever reason). Currently this errors:

``` ts
const MyComponent2: FC<{ props: { myProp: string } }> = props => null;
<MyComponent2 props={{ myProp: 'foo', 'data-test': 'foo' }} />;
```

As far as I'm aware, there's currently no way to extend the above props type to allow for this behaviour.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
You want a combination of #6579 (#21044) and #26797. Today, the logic is hardcoded into how we check jsx literals, but with those you could define, eg, `type Props<P> = P & {[index: /^data-/]: unknown}`

**Comment by eps1lon** [comment]
It seems like this can be solved in TypeScript 4.4 with template literal types as object keys:

```tsx
import * as React from 'react';

type DataAttributeKey = `data-${string}`;

interface HTMLAttributes extends React.HTMLAttributes<any> {
    [dataAttribute: DataAttributeKey]: any;
}

function Component(props: { host: HTMLAttributes }) {
    return <div {...props.host} />
}

<Component host={{
    'data-testid': 'component',
    'role': 'generic',
    // @ts-expect-error
    shouldError: 1
}} />
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnACLIzICCMMUYACMArjCwBpLEzgBeOAAMAJl2QBaACQBvVAOAA7AOYBfBfToHxUAnjYAJACoBZADJ89o8eiwAPcfqV0bDwYADpHV3dBTyxUAB5kfSYAPjgtOjhMuABtFW4o4TEsAC4OVQKYqSYAXVLEpnpjBgIRfXxgCH04AGESSH0sfRgACjBiMFRSrTgACwhdUoi3fmii9GMASjSMrMoYESguuKVgADc00MuxiAnQud1jOAB6ZLomujje8E7B+HuYWRadJZch5dReGDAJRkUpkXB9H5DMgAGh2mQoEAANlgYeRDIMsIJcCi0c8nnAAAIwVBqXysfC0qDEKCk1BzESYpQAUSZ0FKAEY3o8XkA)

**Comment by TrevorBurnham** [comment]
Possibly related: #47211

**Comment by RahelSiddiqi** [comment]
in vue3 typescript I am having some property does not exist in the HtmlElement error. please help me to solve this issue.

(property) dataButtons: string

(property) data-buttons: string

Type '{ class: string; dataButtons: string; "data-buttons": string; }' is not assignable to type 'HTMLAttributes<HTMLDivElement>'.

 Property 'dataButtons' does not exist on type 'HTMLAttributes<HTMLDivElement>'.ts(2322)

**Comment by OliverJAsh** [comment]
https://github.com/microsoft/TypeScript/issues/28960#issuecomment-903519759

**Comment by amitbeck** [comment]
Together with [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) it can be defined once in a global type definitions module, e.g. `src/types/react.d.ts`:

```ts
import 'react';

declare module 'react' {
  export interface HTMLAttributes<T> {
    [dataAttribute: `data-${string}`]: any;
  }
}
```

**Comment by eps1lon** [comment]
Nobody proposed the change yet. It may not be trivial to do since adding properties may break existing typechecking. Somebody just needs to own this change.
