### ISSUE TITLE
Const enum initializer type

### ISSUE THREAD

**Issue by riggs** [Microsoft/TypeScript#28977]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**
`const enum initializer` `ts2474`
**Code**

```ts
// lib.ts
const enum STATIC_KEYS {
    ZERO,
    ONE,
    TWO,

    LAST
}

export const STARTING_NUMBER = STATIC_KEYS.LAST;

// consumer.ts
const enum MORE_STATIC_KEYS {
    ONE = STARTING_NUMBER, // error TS2474; STATIC_KEYS.LAST works as expected
    TWO,
    THREE,
}
```

**Expected behavior:**
Code compiles with `MORE_STATIC_KEYS.ONE === STATIC_KEYS.LAST`.

**Actual behavior:**
`error TS2474: In 'const' enum declarations member initializer must be constant expression.`
TS recognizes that `STARTING_NUMBER` has the type `STATIC_KEYS.LAST`, but doesn't consider it a 'constant expression.'

If this is expected behavior, clarity in the error message would be appreciated.

**Playground Link:** [link](http://www.typescriptlang.org/play/#src=%2F%2F%20lib.ts%0D%0Aconst%20enum%20STATIC_KEYS%20%7B%0D%0A%20%20%20%20ZERO%2C%0D%0A%20%20%20%20ONE%2C%0D%0A%20%20%20%20TWO%2C%0D%0A%0D%0A%20%20%20%20LAST%0D%0A%7D%0D%0A%0D%0Aexport%20const%20STARTING_NUMBER%20%3D%20STATIC_KEYS.LAST%3B%0D%0A%0D%0A%2F%2F%20consumer.ts%0D%0Aconst%20enum%20MORE_STATIC_KEYS%20%7B%0D%0A%20%20%20%20ONE%20%3D%20STARTING_NUMBER%2C%20%2F%2F%20STATIC_KEYS.LAST%20works%20as%20expected%0D%0A%20%20%20%20TWO%2C%0D%0A%20%20%20%20THREE%2C%0D%0A%7D%0D%0A%0D%0A)

**Related Issues:** 
Multiple discussions about merging/intersecting of const enums, of which the above is my attempted workaround.

**Comment by zhmushan** [comment]
`const enum` will be fully erased after compilation, which means you can't index it by an arbitrary value.

**Comment by weswigham** [comment]
A `const` value isn't a constant expression in the sense that error message is indicating, unfortunately. It's trying to say that you need the initializer to be a simple number or string, or the result of arithmetic of those - references to other variables (which may have been calculated using functions and other things we won't precalculate and inline) don't count as "constant" in the same sense. Maybe we need to be more clear here. @DanielRosenwasser ?

**Comment by DanielRosenwasser** [comment]
```
const enum member initializers can only contain literal values and other const enums values.
```

**Comment by riggs** [comment]
I think I was also confused by this language from [the handbook](https://www.typescriptlang.org/docs/handbook/enums.html) explaining what constitutes a 'constant expression':
> 2. a reference to previously defined constant enum member (which can originate from a different enum).

At any rate, thanks for clarifying.

**Comment by DanielRosenwasser** [comment]
Thanks @alisabzevari!

**Comment by xgqfrms** [comment]
const enum member initializers can only contain literal values and other computed enum values.


```ts

// 👍 computed enum
const enum Dynamic {
  role = Roles.User,
  level = Level.A,
  // time = Math.random(),
  value = 1 + 2,
}

```
