### ISSUE TITLE
Only publish stable version to "latest" dist-tag

### ISSUE THREAD

**Issue by jasonwilliams200OK** [Microsoft/TypeScript#2898]
Run the following and see what is going wrong with TS package on npm:

```bash
npm info typescript
npm dist-tag ls typescript
# only one dist-tag: latest which points to alpha release..
```

If you are the person having access to publish TypeScript npm package, please consider running the following commands to remedy it:

```bash
# optionally cd into/typescript-source-directory
npm dist-tag add typescript@1.4.1 latest
npm dist-tag add typescript@1.5.0-alpha alpha
```
Once the issue is fixed, in future, to publish beta, for example 1.5.0-beta:

```
npm publish --tag=beta
```

For stable, it would be just a matter of:

```bash
npm publish  # only run this for stable releases. thank you!
```

So, as a consumer, I will run:

```bash
npm install typescript
# which is same as
npm install typescript@latest
```

to install stable version and:

```bash
npm install typescript@alpha
# or
npm install typescript@beta
# or even @rc, @rc1, @rc2 ..
```

to install respective preview build.

https://docs.npmjs.com/cli/dist-tag

Keywords: love-semver, adapt-semver, semver-rocks, semver-get-ready, I-trust-semver

**Comment by mhegazy** [comment]
thanks @jasonwilliams200OK for the feedback. this issue has been discussed in #2650. We will consider adding tags as we ship newer versions.

**Comment by jasonwilliams200OK** [comment]
Thanks @mhegazy, and sorry for the dup. :)
