### ISSUE TITLE
Language Service API review

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2899]
I just updated to latest. Would like API equivalents for the following: 

```ts
ts.typeToDisplayParts
ts.getTokenAtPosition
sourceFile.getNamedDeclarations
```

Error log: 
```
/fixmyts/addClassMember.ts(5,31): error TS2305: Module '"typescript"' has no exported member 'typeToDisplayParts'.
/fixmyts/equalsToEquals.ts(5,31): error TS2305: Module '"typescript"' has no exported member 'typeToDisplayParts'.
/fixmyts/quoteToTemplate.ts(5,31): error TS2305: Module '"typescript"' has no exported member 'typeToDisplayParts'.
/fixmyts/quotesToQuotes.ts(5,31): error TS2305: Module '"typescript"' has no exported member 'typeToDisplayParts'.
/projectService.ts(736,38): error TS2339: Property 'getNamedDeclarations' does not exist on type 'SourceFile'.
/projectService.ts(922,36): error TS2339: Property 'getTokenAtPosition' does not exist on type 'typeof "typescript"'.
```

**Comment by basarat** [comment]
@mhegazy FWIW I don't need this anymore :) https://github.com/TypeStrong/atom-typescript/tree/master/lib/typescript but leaving it open as other people might need it.

[Worth mentioning](https://github.com/TypeStrong/atom-typescript/tree/master/lib/typescript#notes) `"../compiler/diagnosticInformationMap.generated.ts",` needs to be in output js before `"../compiler/commandLineParser.ts",` but is listed in reverse in `tsconfig.json`. As mentioned previously [here](https://github.com/Microsoft/TypeScript/issues/2472#issuecomment-85330803) the order of `files` in the presence of `out` is significant and in this case it is wrong .. just thought I'd point it out :rose:

**Comment by basarat** [comment]
> Worth mentioning

I've sent a PR : https://github.com/Microsoft/TypeScript/pull/2917

**Comment by mhegazy** [comment]
Since these are not needed i am going to close this issue. We wanted to limit the public API surface area, for support and maintenance reasons. so unless you need them, I would keep them hidden :)
