### ISSUE TITLE
Lib.d.ts `ClipboardEventInit` does not match the W3C specification

### ISSUE THREAD

**Issue by Brcrwilliams** [microsoft/TypeScript#28998]
**TypeScript Version:**
3.3.0-dev.20181212

**Search Terms:**
ClipboardEvent
ClipboardEventInit
clipboardData is null

**Code**

```ts
new ClipboardEvent('paste', { clipboardData: new DataTransfer() });
```

**Expected behavior:**
[According to the W3C spec this should be a valid constructor.](https://www.w3.org/TR/clipboard-apis/#clipboard-event-interfaces)

[Chromium currently does not initialize the clipboardData](https://bugs.chromium.org/p/chromium/issues/detail?id=800742) so it is currently impossible to create an ClipboardEvent and add data to it when using TypeScript with Chromium.

**Actual behavior:**
TS fails to compile with an error:

test.ts:1:31 - error TS2345: Argument of type '{ clipboardData: DataTransfer; }' is not assignable to parameter of type 'ClipboardEventInit'.
  Object literal may only specify known properties, and 'clipboardData' does not exist in type 'ClipboardEventInit'.

1 new ClipboardEvent('paste', { clipboardData: new DataTransfer() });
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

**Playground Link:** <!-- A link to a TypeScript Playground "Share" link which demonstrates this behavior --> https://www.typescriptlang.org/play/#src=new%20ClipboardEvent('paste'%2C%20%7B%20clipboardData%3A%20new%20DataTransfer()%20%7D)%3B%0D%0A

**Comment by nguyenbathanh** [comment]
I have got the same issue:
```
error TS2345: Argument of type '{ clipboardData: any; }' is not assignable to parameter of type 'ClipboardEventInit'. 
Object literal may only specify known properties, and 'clipboardData' does not exist in type 'ClipboardEventInit'.
```

**Comment by Brcrwilliams** [comment]
The PR is ready @ Microsoft/TSJS-lib-generator#628. Maybe this will get included in the next release.

**Comment by Brcrwilliams** [comment]
I just realized that this is still open. microsoft/TSJS-lib-generator#628 was merged on January 24. @RyanCavanaugh @sandersn Do you know if this made it into a TypeScript release?

**Comment by Brcrwilliams** [comment]
This looks to be fixed. Closing this issue.

```
$ tsc --version
Version 3.4.5
$ echo 'new ClipboardEvent("paste", { clipboardData: new DataTransfer() });' > test.ts
$ tsc test.ts
$ cat test.js
new ClipboardEvent("paste", { clipboardData: new DataTransfer() });
```
