### ISSUE TITLE
undefined not assignable error within "if" statement, when member of Readonly<T>

### ISSUE THREAD

**Issue by captain-igloo** [microsoft/TypeScript#28997]
**TypeScript Version:**  3.3.0-dev.20181212

readonly if

**Code**

```ts
interface IProps {
    foo1?: string;
    foo2: string;
}

class Foo<P> {
    protected props: Readonly<P>;

    constructor(props: Readonly<P>) {
        this.props = props;
    }
}

class Bar<P extends IProps> extends Foo<P> {

    private test1() {
        const { foo1, foo2 } = this.props;

        if (foo1) {
            foo1.toUpperCase(); // fine
            this.test2(foo1); // error "Type undefined is not assignable to type string"
        }
        this.test2(foo2); // fine
    }

    private test2(foo: string): void {
    }
}
```

**Expected behavior:**
I expect the above to compile without error
**Actual behavior:**
There's an error - Type 'undefined' is not assignable to type 'string'

"foo1" above can't be undefined because it's within an "if (foo1) {}".

**Playground**
[link](https://www.typescriptlang.org/play/#src=interface%20IProps%20%7B%0D%0A%20%20%20%20foo1%3F%3A%20string%3B%0D%0A%20%20%20%20foo2%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%3CP%3E%20%7B%0D%0A%20%20%20%20protected%20props%3A%20Readonly%3CP%3E%3B%0D%0A%0D%0A%20%20%20%20constructor(props%3A%20Readonly%3CP%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.props%20%3D%20props%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%3CP%20extends%20IProps%3E%20extends%20Foo%3CP%3E%20%7B%0D%0A%0D%0A%20%20%20%20private%20test1()%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20%7B%20foo1%2C%20foo2%20%7D%20%3D%20this.props%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20if%20(foo1)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20foo1.toUpperCase()%3B%20%2F%2F%20fine%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.test2(foo1)%3B%20%2F%2F%20error%20%22Type%20undefined%20is%20not%20assignable%20to%20type%20string%22%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20this.test2(foo2)%3B%20%2F%2F%20fine%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20test2(foo%3A%20string)%3A%20void%20%7B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Comment by jakebailey** [comment]
This one was fixed back in #43183, but probably deserves a test (I didn't see any that were similar in the PR).
