### ISSUE TITLE
JSDoc support for object literal fields

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/TypeScript#290]
When inside a definition file (eg jquery.d.ts) and hovering over an interface member which has been JSDoc'd then intellisense is presented to the user in Visual Studio.

However, when in a different file which is making use of those definitions the same rich interface intellisense is not presented. Just the type and name - none of the JSDoc stuff flows through. 

It would be good if it did.

Migrated from http://typescript.codeplex.com/workitem/2463

**Comment by orta** [comment]
Pretty sure that this issue is what I'm hitting with this type of code:

```ts repro
const someFunc = () => {
    return {
        /** This JSDoc comment doesn't leave the function */
        one: "1",
        /** Neither does this */
        two: "2"
    }
}

const a = someFunc()

a.one
// ^?

type A = ReturnType<typeof someFunc>
//   ^?
```

Both 

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBBIFsCmAxArmYMC8MAUAlDgHwwDeAUDNTAE5JRq1jlU3sD0AVFzAIwwuHNu2rgkALhgAiPtIA0I0d14AmQcNE0oAdxBTpq6UoC+FMxVCRYAQxxxEqDMEIUKNgHTiKHDjAB6APxuUACeAA5IMACC9gBKDExgACoRSAA8YZEgAGYOyOiYxD5+1EFAA)

**Comment by orta** [comment]
I realize now that the `// ^?` doesn't show JSDoc anyway, so the repro is useless 🍡

**Comment by DanielRosenwasser** [comment]
@johnnyreilly do you remember what this was about? I would imagine this:

```ts
interface Foo {
    /**
     * Hallo this is JSDoc
     */
    yadda(): void
}

let x: Foo = {
    yadda() {

    }
}
```

which seems to be fixed.

**Comment by DanielRosenwasser** [comment]
@orta if I hover on that in the playground, that seems to work.

**Comment by johnnyreilly** [comment]
Wow - this an old issue! I do vaguely remember raising it - but not more than that. The way intellisense is powered in Visual Studio has radically changed now I understand. I should say I haven't used VS in about four years though. Apologies

**Comment by Andarist** [comment]
@DanielRosenwasser @johnnyreilly I've tried a couple of things in VS Code and all basic cases seem to work just fine nowadays. It's probably best to close this issue as it was most likely fixed along the way.

**Comment by jakebailey** [comment]
Just looking at old issues; given nobody knows what this is about anymore and everyone keeps trying things and they work, it's probably better to report new things when we find them, yeah.

**Comment by johnnyreilly** [comment]
I raised this and I have no memory of doing so. It was 2014 - there's a lot of water under the bridge since then. I support this decision 🫡
