### ISSUE TITLE
Problem infer return type of function with nullable argument

### ISSUE THREAD

**Issue by MrFesgheli** [Microsoft/TypeScript#29001]
**TypeScript Version:**  3.2.0

**Code**

```ts
interface U { }
function test(Us?: U[] | null | undefined) {
    if (!Us)
        return;
    else return []
}


```

**Expected behavior:**
Return type should be `void | any[]`
**Actual behavior:**
`any[]`
**Playground Link:** 
[Playground](https://www.typescriptlang.org/play/#src=interface%20U%20%7B%20%7D%0D%0Afunction%20test(Us%3F%3A%20U%5B%5D%20%7C%20null%20%7C%20undefined)%20%7B%0D%0A%20%20%20%20if%20(!Us)%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20else%20return%20%5B%5D%0D%0A%7D%0D%0A%0D%0A)

**Comment by cpplearner** [comment]
`void` means "I don't care the return type", which seems not the case here. `undefined | any[]` might make more sense.

And since `strictNullChecks` is not enabled, `any[]` _is_ the same as `undefined | any[]`.
