### ISSUE TITLE
scrollInfoView ScrollOptions wrong type definition

### ISSUE THREAD

**Issue by movedoa** [Microsoft/TypeScript#29004]
**TypeScript Version:**  3.2.2

**Search Terms:** scrollIntoView

**Code**

```ts
element.scrollIntoView({ behavior: "instant", inline: "center" });
```

**Expected behavior:**
The property behaviour should accept "instant" but doesn't
http://docs.w3cub.com/dom/element/scrollintoview/

**Actual behavior:**
"Type '"instant"' is not assignable to type '"auto" | "smooth" | undefined'"

This did work in TS 3.1 and before

**Comment by fatcerberus** [comment]
According to MDN, `behavior` can only be `auto` or `smooth`:
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

This is apparently an experimental API.  I’m thinking the specification changed at some point so TS realigned.

**Comment by movedoa** [comment]
Ok...i was looking at the german MDN, which has "instant"
https://developer.mozilla.org/de/docs/Web/API/Element/scrollIntoView
Nevermind then

**Comment by cpplearner** [comment]
See https://github.com/Microsoft/TSJS-lib-generator/commit/fe01c9a6d6afde86bd15f2588dc9360416a2beb4#r31507840
