### ISSUE TITLE
Destructuring assignment can't judge type

### ISSUE THREAD

**Issue by zhouhaoxiang** [Microsoft/TypeScript#29005]
![lark20181213223351](https://user-images.githubusercontent.com/18625494/49945728-72869f00-ff28-11e8-8ff5-e4b98f27e803.png)

But when i don't use Destructuring assignment, it is in line with expectations.
![image](https://user-images.githubusercontent.com/18625494/49945885-ca250a80-ff28-11e8-838a-9b85d64c5d77.png)

**Comment by j-oliveras** [comment]
Can you follow the bug issue template? Is much better to paste the code inside a code block.

Anyway, I think this is duplicate of #28981 and #27497: typescript don't track related variables (for example when destructuring).

**Comment by weswigham** [comment]
@j-oliveras is correct.
