### ISSUE TITLE
Exclude keys of union type returning incorrect type

### ISSUE THREAD

**Issue by hisuwh** [Microsoft/TypeScript#29023]
**TypeScript Version:**  3.3.0-dev.20181214

**Search Terms:** Exclude, union

**Code**
I have an input component from an external library with props something like this:

```ts
interface InputProps {
    value: string;
    label: string;
    onChange: (value: string) => void;
}
```

I want to strongly type this for certain types - so I have wrapped it and defined an interface like this (with example for number input):
```ts
interface TypedInputProps<T> {
    value: T;
    onChange: (value: T) => void;
}

type NumberInputProps = Exclude<InputProps, keyof TypedInputProps<number>>
    & TypedInputProps<number>; // = { value: number, label: string, onChange: (value: number) => void }
```
This is working as I would expect - giving me the correct props.

I then have HOC to connect these to React context and defined the following types.  These aren't working and are giving me weird union types.  This is where I think the bug is.
```ts
type ConnectedInputProps<T, TProps> = Exclude<TProps, keyof TypedInputProps<T>>;

type ConnectedNumberInputProps = Exclude<NumberInputProps, keyof TypedInputProps<number>>;

// Expected: { label: string }
// Actual: { value: string & number, label: string, onChange: ((value: string) => void) & ((value: number) => void) }

const props: ConnectedNumberInputProps = {
    label: "something"
};
// Type '{ label: string; }' is missing the following properties from type 'InputProps': value, onChange [2322]
```

**Expected behavior:**
Expected it to return the result of Excluding the properties of the specified interface from the unioned types

**Actual behavior:**
returns an obscure, with all the properties, and the types of thos properties unioned.

[**Playground Link**](https://www.typescriptlang.org/play/#src=interface%20InputProps%20%7B%0D%0A%20%20%20%20value%3A%20string%3B%0D%0A%20%20%20%20label%3A%20string%3B%0D%0A%20%20%20%20onChange%3A%20(value%3A%20string)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20TypedInputProps%3CT%3E%20%7B%0D%0A%20%20%20%20value%3A%20T%3B%0D%0A%20%20%20%20onChange%3A%20(value%3A%20T)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Atype%20NumberInputProps%20%3D%20Exclude%3CInputProps%2C%20keyof%20TypedInputProps%3Cnumber%3E%3E%0D%0A%20%20%20%20%26%20TypedInputProps%3Cnumber%3E%3B%20%2F%2F%20%3D%20%7B%20value%3A%20number%2C%20label%3A%20string%2C%20onChange%3A%20(value%3A%20number)%20%3D%3E%20void%20%7D%0D%0A%0D%0Atype%20ConnectedInputProps%3CT%2C%20TProps%3E%20%3D%20Exclude%3CTProps%2C%20keyof%20TypedInputProps%3CT%3E%3E%3B%0D%0A%0D%0Atype%20ConnectedNumberInputProps%20%3D%20Exclude%3CNumberInputProps%2C%20keyof%20TypedInputProps%3Cnumber%3E%3E%3B%0D%0A%0D%0A%2F%2F%20Expected%3A%20%7B%20label%3A%20string%20%7D%0D%0A%2F%2F%20Actual%3A%20%7B%20value%3A%20string%20%26%20number%2C%20label%3A%20string%2C%20onChange%3A%20((value%3A%20string)%20%3D%3E%20void)%20%26%20((value%3A%20number)%20%3D%3E%20void)%20%7D%0D%0A%0D%0Aconst%20props%3A%20ConnectedNumberInputProps%20%3D%20%7B%0D%0A%20%20%20%20label%3A%20%22something%22%0D%0A%7D%3B%0D%0A%2F%2F%20Type%20'%7B%20label%3A%20string%3B%20%7D'%20is%20missing%20the%20following%20properties%20from%20type%20'InputProps'%3A%20value%2C%20onChange%20%5B2322%5D)

**Related Issues:** no

**Comment by jack-williams** [comment]
I think this is best asked on StackOverflow first, unless you are sure this is a bug. One thing that stands out is:
```ts
Exclude<InputProps, keyof TypedInputProps<number>>
```
You are excluding properties from an interface type, but that isn't how exclude should really be used. You need to explicitly exclude the keys of one from the other, then repick the keys you want. Somethink like:
```ts
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>
type NumberInputProps = Omit<InputProps, keyof TypedInputProps<number>> & TypedInputProps<number>;
```

**Comment by hisuwh** [comment]
@jack-williams I have updated my post to provide some context to what I am triying to achieve.
The thing you are saying stands out is working fine, thats not the bit I'm questioning.

**Comment by jack-williams** [comment]
I'm not sure it is working fine (unless I'm missing something). The type
-  `Exclude<InputProps, keyof TypedInputProps<number>>`

is equivalent to `InputProps` because it is excluding string keys from an object type, which does not do anything. Anyway, here is a version using `Omit` which seems to do what you want, I think.
```ts

interface InputProps {
    value: string;
    label: string;
    onChange: (value: string) => void;
}

interface TypedInputProps<T> {
    value: T;
    onChange: (value: T) => void;
}

type Omit<T, K> = Pick<T, Exclude<keyof T, K>>
type NumberInputProps = Omit<InputProps, keyof TypedInputProps<number>> & TypedInputProps<number>;
type ConnectedInputProps<T, TProps> = Exclude<TProps, keyof TypedInputProps<T>>;
type ConnectedNumberInputProps = Omit<NumberInputProps, keyof TypedInputProps<number>>;
const props: ConnectedNumberInputProps = {
    label: "something"
};
```

**Comment by hisuwh** [comment]
OK I understand now - it just appears to work because the of the union
`Exclude<InputProps, keyof TypedInputProps<number>> & TypedInputProps<number>` is equivalent to:
`InputProps & TypedInputProps<number>`
