### ISSUE TITLE
Allow overloading of JSX element constructors

### ISSUE THREAD

**Issue by ferdaber** [Microsoft/TypeScript#29025]
## Search Terms
jsx overload conditional component react

## Suggestion
Allow for some kind of overload mechanism for JSX element construction, that is: determine contextual types for the allowable attributes for a JSX expression based on attributes already passed in.
## Use Cases
There are times when we want to conditionally render based on the type of a certain property in a props object, or the existence/non-existence of a certain property in a props object. A very common use case is rendering clickable elements as anchor tags if a `href` attribute is present:

```tsx
type AnchorProps = JSX.IntrinsicElements['a']
type ButtonProps = JSX.IntrinsicElements['button']
declare function Buttonish(props: ButtonProps): JSX.Element
declare function Buttonish(props: AnchorProps): JSX.Element
declare function Buttonish(props: AnchorProps | ButtonProps): JSX.Element

const myAnchor = <Buttonish href="typescriptlang.org" onClick={event => {}} /> 
// `event` is inferred to be React.MouseEvent<HTMLAnchorElement> because `href` is already there
```
The above is one suggestion though I don't know we could resolve that with class-based components.

I know right now that this is partially solved with generic components + conditional types, but it's kind of odd DX:
```tsx
type EitherProps<T> = T extends string ? { href?: T } & AnchorProps : { href?: undefined } & ButtonProps
declare function Buttonish<T>(props: EitherProps<T>): JSX.Element

const myAnchor = <Buttonish href="typescriptlang.org">
// generic type inferred, but looks weird since T = string which doesn't tell you much
```

## Examples
Unsure what the best approach would be. I think one good DX I was hoping for was for the autocomplete list to be narrowed as attributes are added to a JSX expression, when the compiler gets more contextual information to infer, so that after `href` is added in the above example, the event handlers are narrowed to just be handlers related to anchor elements, for example.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
So this actually works as requested in `3.2`. While some things broke in the great JSX migration, this is something that was fixed by it.
![image](https://user-images.githubusercontent.com/2932786/50305861-fbca3400-0448-11e9-880d-3175a06e0019.png)

Are you using `3.2`?

**Comment by ferdaber** [comment]
Revisiting this, it looks like the overload signature works for function-type components, but is failing for class-type components, such as this example:
```tsx
function isPropsForAnchorElement(props: ButtonProps | AnchorProps): props is AnchorProps {
  return 'href' in props
}

class Clickable extends React.Component<ButtonProps | AnchorProps> {
  constructor(props: ButtonProps)
  constructor(props: AnchorProps)
  constructor(props: ButtonProps | AnchorProps) {
    super(props)
  }

  render() {
    if (isPropsForAnchorElement(this.props)) {
      return <a { ...this.props } />
    } else {
      return <button { ...this.props } />
    }
  }
}

const aClickable = <Clickable href='abc' onClick={event => {}} /> // implicit 'any' on event
const btnClickable = <Clickable onClick={event => {}} /> // implicit 'any' on event
```

I'm assuming it's because it's using the `JSX.ElementAttributesProperty` functionality to identify the allowable attributes instead of the first parameter in the constructor call signature?

**Comment by weswigham** [comment]
> I'm assuming it's because it's using the JSX.ElementAttributesProperty functionality to identify the allowable attributes instead of the first parameter in the constructor call signature?

Yup. The irony is that if that jsx namespace member isn't present, we'll use the parameter type, just like functions nowadays.

**Comment by ferdaber** [comment]
I wonder if it's better to just remove that specific interface in the JSX namespace then 🤔 

I think this answers all my questions for now, thanks for the help!

**Comment by OliverJAsh** [comment]
I just ran into this. @ferdaber What needs to happen so we can support overloading class components?

**Comment by ferdaber** [comment]
Removing the `ElementAttributesProperty` interface declaration in the `JSX` namespace of React's type definitions should do the trick, like my above comment.

**Comment by OliverJAsh** [comment]
Is this something we need to fix upstream in the React types, or are you suggesting doing this by patching the types locally?

**Comment by ferdaber** [comment]
Either will work, but if you choose to patch it it does need to be a literal patch, since you can't remove declarations via declaration merging

**Comment by OliverJAsh** [comment]
Thinking about this some more, why do you need overloads in your class example? Isn't the union parameter sufficient? Related: https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-union-types

**Comment by ferdaber** [comment]
Union parameter types are subtly different, and it may be a bug honestly (unsure). Consider the following:
```ts
type AElement = HTMLAnchorElement
type BElement = HTMLButtonElement

interface A {
    a: 'a'
    onClick(el: AElement): void
}

interface B {
    onClick(el: BElement): void
}

declare function AorB(props: A | B): JSX.Element
declare function AorBOverload(props: A): JSX.Element
declare function AorBOverload(props: B): JSX.Element

// TS error: `el` is inferred to be `any` even though it should be narrowed to `AElement`
const foo = <AorB a='a' onClick={el => {}} />

// this works fine and `el` is inferred to be `AElement`
const bar = <AorBOverload a='a' onClick={el => {}} />
```

**Comment by OliverJAsh** [comment]
@ferdaber Interesting, thanks. Opened an issue: https://github.com/microsoft/TypeScript/issues/34590.
