### ISSUE TITLE
Possible clue as to why intellisense occasionally stops working

### ISSUE THREAD

**Issue by foxbunny** [Microsoft/TypeScript#29040]
This is related to #46557, #48916, #26237.

I've been using VS Code extensively on Windows, and observed the sporadict issues with intellisense in JavaScript both with and without extensions, sometimes even fresh out of the box. The issue only happens on a (relatively) big project I'm working on, never on toy projects with small code bases.

 After switching to Linux, I see that:

- The issue does not happen at all
- VS Code is much faster

My suggestion is to investigate whether the intellisense issue occurs because VS code is simply not able to keep up with the workload (i.e., slow) on (slow) Windows PCs.

- VSCode Version: 1.30 and most previous versions (1.2x+)
- OS Version: Windows 10

Steps to Reproduce: n/a

Does this issue occur when all extensions are disabled?: Yes

**Comment by foxbunny** [comment]
It's hard to tell what exactly causes it. I just notice that after a while I'm unable to get code hints and intellisense suggestions, or Ctrl+click to find a definition. This can happen within minutes or more than an hour of starting VS Code.

**Comment by sheetalkamat** [comment]
@foxbunny First step would be to get us tsserver logs from the session you  are having trouble with. We can take a look at the logs and see if we can find something.

**Comment by foxbunny** [comment]
@sheetalkamat I'm not sure if you guys are following what I'm saying here. I *do not* have any issues right now. I *used to* have issues on Windows *on the same machine*. I switched to Linux, and problems went away. I cannot produce logs "from the session you are having trouble with" because I do not have such sessions.

**Comment by sheetalkamat** [comment]
@foxbunny In that case I am not sure we can take any action on this issue till we have more information on what was causing the issue or the logs. Closing for now but can be reopened if you have more information later. Thanks.

**Comment by foxbunny** [comment]
> In that case I am not sure we can take any action on this issue till we have more information on what was causing the issue or the logs.

Sorry to hear that. Anyway, just thought tossing it out might give you a new way to look at the older issues that went unresolved is all. Happy hacking.
