### ISSUE TITLE
Issue a custom error message when trying to assign constraint type to generic type parameter

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#29049]
**TypeScript Version:** master

**Search Terms:** generic constrained type parameter error

**Code**

People are regularly confused why code like this doesn't work:
```ts
function fn1<T extends string>(x: T): T {
  return "hello world!";
}

function fn2<T extends HTMLElement>(obj: T): T[] {
  return [obj, new HTMLDialogElement()];
}

function fn3<T extends boolean>(obj: T = false) {
}
```

**Actual behavior:** Unelaborated error like "Can't assign `false` to `T`"

**Expected behavior:**

If the source type is assignable to the constraint of a type parameter, we should issue a more specific error that attempts to explain the situation:

🚲 🏠 
> ```
> Type "false" is not assignable to type "T"
>   "false" is assignable to the constraint type "boolean", but "T" could be a different more-specific type during a call
> ```

**Playground Link:** [Link](http://www.typescriptlang.org/play/#src=function%20fn1%3CT%20extends%20string%3E(x%3A%20T)%3A%20T%20%7B%0D%0A%20%20return%20%22hello%20world!%22%3B%0D%0A%7D%0D%0A%0D%0Afunction%20fn2%3CT%20extends%20HTMLElement%3E(obj%3A%20T)%3A%20T%5B%5D%20%7B%0D%0A%20%20return%20%5Bobj%2C%20new%20HTMLDialogElement()%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20fn3%3CT%20extends%20boolean%3E(obj%3A%20T%20%3D%20false)%20%7B%0D%0A%7D%0D%0A)

**Comment by DanielRosenwasser** [comment]
more-specific type during an invocation?

**Comment by DanielRosenwasser** [comment]
Agree with @jack-williams since this can happen in a class too. I think the following might cut to the chase though:

```
'{0}' is assignable to the constraint of type '{1}', but '{1}' could be instantiated with a different type.
```

Also, when not assignable, or when there's an implicit constraint, but the RHS is not instantiable, I could see an elaboraron like

```
Concrete types are never assignable to uninstantiated types.
```

Or something like that.

**Comment by RyanCavanaugh** [comment]
I think the problem with *could be instantiated with a __different__ type* is that the user reaction would probably be "You mean the constraint doesn't do anything?".

What about:
```
'{0}' is assignable to the constraint of type '{1}', but '{0}' could be instantiated with a different subtype of `{1}`.
```

**Comment by jack-williams** [comment]
That's a good point @RyanCavanaugh. I'm not sure if I've substituted in the placeholders correctly; is this right?

```
'false' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of 'boolean'.
```
In that instance I would probably make it explicit that boolean is the constraint, as I feel it pops out of nowhere abit. So:
```
'false' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'boolean'.
```

**Comment by RyanCavanaugh** [comment]
> 'false' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'boolean'.

❤️ !

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Can I work on this issue?

**Comment by DanielRosenwasser** [comment]
Since you're just specializing the error, `target.flags & TypeFlags.TypeVariable` is probably a good first approximation. I haven't been deep in the codebase in a while, but others reviewing might be able to help you iterate on that.

**Comment by jack-williams** [comment]
@a-tarasyuk I think `structuredTypeRelatedTo`is probably where you want to look.

**Comment by JoshuaKGoldberg** [comment]
@a-tarasyuk are you still interested in this? I'm interested in it going in, but don't want to snatch it out from under you. 😊

**Comment by a-tarasyuk** [comment]
@JoshuaKGoldberg Never mind :). I wanted to make PR at the end this week. however, I see you have started work and ready to send PR. I'll take another issue :).

**Comment by JoshuaKGoldberg** [comment]
@a-tarasyuk no-no, this one's all you! I'll wait a week before looking into it.

**Comment by moccaplusplus** [comment]
Current message: [ts] Type 'false' is not assignable to type 'T'. [2322]
is perfectly OK.
Making it too verbose does not make it better. ;)

**Comment by jack-williams** [comment]
@moccaplusplus I agree that there is a fine balance between being informative and concise. IMO the extra information is helpful; as you can see I've been collating issues that trigger this error, so it's something people definitely come across.

Generics are a hard subject, subtyping is a hard subject, and variance is a hard subject---this error is a combination of all three. I think spelling out the problem in a more concrete way is a definite improvement.

**Comment by RyanCavanaugh** [comment]
@JoshuaKGoldberg your commit there is looking pretty nice; is there an associated PR?

**Comment by JoshuaKGoldberg** [comment]
Oh hey I forgot about this thread! Thanks for the reminder. Will send now and fix up merge conflicts soon.

Maybe "Although " should be prepended to the front of the message to make it more clear it's useful?

**Comment by LucasBrd** [comment]
Is it relevant to include some sort of "you should consider doing X, Y or Z to resolve this problem" ? 

It could speed up the process of finding a solution for new comers, as it is not really easy to understand, and there are not many available resources online,

I managed to found this : https://stackoverflow.com/a/56701587/6790372

Could you at least modify your first post in this issue, to explain why each case does not work, and what could be done instead ?

**Comment by dagda1** [comment]
I find this error message undecipherable.  I have lots of this type of error message:

> 'A' is assignable to the constraint of type 'B', but 'B' could be instantiated with a different subtype of constraint '{}'.

The last placeholder is always, the `{}`.  I have no idea what this means or what the fix is.

**Comment by DanielRosenwasser** [comment]
@dagda feel free to help us iterate with that on https://github.com/microsoft/TypeScript/issues/33436

**Comment by Dema** [comment]
I have a question related to this error. I'm trying to implement "Slaying UI antipattern in...", but I'd like to have a separate state for pending but when we already have some data. It gives an error because I use two unrelated generic parameters. Could you help me a bit with how can I constrain Data param to be the same on both success and pendingWithData?

http://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbzgEQKarAJVQQwCYQB2ANgJ4A0cAqoVLgMYAWOARsagMI4DOqAolCjQ4AXzgAzISDgAiGNwC0qbr0IxgOYtxkBuAFChIsRNhz0YAOQh5UYyRGkByOmZiO9e1AA8j8VIQBXaWwQCBhUZBwYHABlaJgA7kQ9ODgASUJgdU1gAC9UPDgAXlkMrI1iPIKZchS4AAV-PGBCAHNi2UbCZraauq6e1oAJHAA3CKicDpkBluGxiei+1IAxHGBiALpptY2t1GW4GID6emUkkplj0-OZPREPb184GFIwVHTM7Mr8wpKkFwEEikODceKJABccBCYUWsXB3AAdGVvlVCiJ9E9oPBXu8Gk05h0EHVAUQyKCEVCYeFItE4lFEojZm19BjPD5sS83h9mfNxrScAAeAUAPiJJNwQPJYIZ3CpqFCNMm9ISSN5I35k30qVJwLgeEmUIFrMxHOMuI+u02dEFAiEUDF-wl+DJIJlqvlirhKsZVv22rguvJqEE0ChdugJvZzwtRxOZxUwsmjuSOslropss9sIFPqR1wT3ADQZBBuiRq191NMe50IVOcmSeilAjUA6YKgc0ddQAPp9yjlfr38d05sP1QsBU2cCLh36ba3Z6k+wXztORfpo5zxAFCOZgEQ4C0Bz8CtOW6G2yUO12ABQASiN6Cw6eBgrq1Lh57gi70YuJaYJFAhCIJmHp1l6uYIsiXwVGioisluxg7nu6iHu8o5tN+rbtjAnZtCKD7Zkq0TYZe-4SkBIFIO6kIQQ2dLQbyCH3I8ZrwCh+7oQSbQal+AoXvauH4a0hF1GWOAVtEeiPvRJFCgJP7kamgaoFRoG0XKcnekxPF8nClASSxDxIRxu5cSB4jrNaqBkUJ154XedQhva4aXjJxH8ZMgnQBRgFbNRYF0Z+UGyoi86oJQLnCGyDxYsh5loSB3Dxmuik4Q5IliakElSTgtSpBhgxQiwEAQOwOCEB52lTulykAap6k0ZSNXKtBq4qIZkzGWxzycUlEjlXgdnCJlcyUNgKXEPAJSmOYVg2NloKpSoUK3rlKDeXARVzAA-CVZUVYQ97FGKk0BNNBVHrBg4FGtJ1FGdygXTAV07W092nXWU2vXUVl7HQa3RVAbn2g9T0-TJKl0Op62Gq1pF1faIqyed01fQ1qTcAA7lkTBwHD0SIppJ2Y6kcD0DwHwhW1YUonBvwQnU5PkzDAXXSeaIPgGLOU7wCPwmFvJMyzLNs8B216dzzPk3z1P1vJeZMnpfECiLov+RLKU3CohP5S8UABKg9487LVMC0rEXqxr4uWdZ+x64iwMmzLqRyxb7UrXKrus2p7Pa4WjsSZQVlaMbps5agVkvdboswIwQjY3AhCoEnNAuEwrDsFwvCtnrLssw8qSxb126JQeIF0F6ACyOBgIKaOvZtzZKcjt5-eZa0bQK4PfS9V0bTTiNbb+qMK1+jc+Q6KnAOIBMScTCLFEUs3j6FqqIh13CkzLtvLTr3C3pxQeTPeIeaLwBeiHAqBh0ec+O5py+r5BtMbxOmrRDvYt+1rXtH+ZE+X9KB4SNlfMQt9+Zkz3hJAMDwTLxTMqhCucAQA4FICwCez1LrN31ouduWNb6oHMGGee8Me5fUnuJKOOAXoADVNBG3lD9Ae8Mh4KRHuRaqjcZ4PwXk-FeL8GKCw3lvb+vt1K8HYCQqAQCcDgJvnfaBv8QI2GjtNBhmxUBwNYkAA

**Comment by derakhshanfar** [comment]
any workaround?

**Comment by fvilante** [comment]
**ARTICLE ABOUT THIS ERROR MESSAGE**

 I wrote a text decomposing and explaining each part of this error message. Hope the text can carry you [up to the point](https://stackoverflow.com/questions/56505560/could-be-instantiated-with-a-different-subtype-of-constraint-object/59363875#59363875).

**Comment by KostyaTretyak** [comment]
@RyanCavanaugh says:
> People are regularly confused why code like this doesn't work:
> ```ts
> function fn1<T extends string>(x: T): T {
>  return "hello world!";
> }
>
> function fn2<T extends HTMLElement>(obj: T): T[] {
>  return [obj, new HTMLDialogElement()];
> }
>
> function fn3<T extends boolean>(obj: T = false) {
> }
> ```

So, did confused reduce after https://github.com/microsoft/TypeScript/pull/30394? I highly doubt it.
Please describe this case in the documentation. At the moment you can find a sea of questions about this.

**Comment by akopchinskiy** [comment]
> {1} is assignable to the constraint of type {2}, but {2} could be instantiated with a different subtype of constraint 'any'
Oh, really? Can you give me an example of how that's possible?

**Comment by mikew** [comment]
I'm bumping into this a lot recently, and I'm not quite sure how to solve it. Currently trying to do something on top of `RESTDataSource.didReceiveResponse ` from `apollo-server`:

```ts
class SomethingOutsideOfOurControl {
    didReceiveResponse<TResult = any>(): Promise<TResult> {
        return Promise.resolve({}) as Promise<TResult>
    }
}

class Implementation extends SomethingOutsideOfOurControl {
    // Property 'didReceiveResponse' in type 'Implementation' is not assignable to the same property in base type 'SomethingOutsideOfOurControl'.
    //   Type '<T>() => Promise<{ data: any; somethingElse: boolean; }>' is not assignable to type '<TResult = any>() => Promise<TResult>'.
    //     Type 'Promise<{ data: any; somethingElse: boolean; }>' is not assignable to type 'Promise<TResult>'.
    //       Type '{ data: any; somethingElse: boolean; }' is not assignable to type 'TResult'.
    //         'TResult' could be instantiated with an arbitrary type which could be unrelated to '{ data: any; somethingElse: boolean; }'.(2416)
    async didReceiveResponse() {
        const data = await super.didReceiveResponse()
        return {
            data,
            somethingElse: true,
        }
    }
}
```

What would be the correct way of going about things? Seems like I have to throw in a `return ... as any` in `Implementation.didReceiveResponse`

**Comment by Thomazella** [comment]
My 2cents on this matter is that TS seems to punish you for using default params. Makes sense to me for this to be a warning instead.

**Comment by wbt** [comment]
@tcodes0 I agree, there seems to be a TypeScript penalty prohibiting use of default values on parameters used to infer generic types (that e.g. then are used to determine a return type, or which are passed through as the generic type parameter to a called function).
