### ISSUE TITLE
Extremely slow TypeScript server on lowdb types

### ISSUE THREAD

**Issue by proteriax** [microsoft/TypeScript#29044]
**TypeScript Version:**  3.2.2
**Visual Studio Code Version:** 1.30.0

**Search Terms:** slow, server

**Code**

Download the [gist here](https://gist.github.com/proteriax/a07dfd09c8913db2ac085ad0e1c11898). This is a single-file TypeScript project.

**Steps to Reproduce:**
1. Open project above in Visual Studio Code and install dependencies.
2. Open `index.ts`
3. Move cursor over any identifier, like `Memory`, `low.lowdbSync<T>`, or one after the other

**Expected behavior:**
TypeScript deduces a type and show it in hover. If you cannot reproduce this, try to add a statement like `let a = 0` somewhere in the file.

**Actual behavior:**
Types take up to 35 seconds to show up.

`tsc --diagnostics` results:

```
Files:            38
Lines:         57828
Nodes:        291629
Identifiers:  108726
Symbols:     1177592
Types:       1095357
Memory used: 869000K
I/O read:      0.03s
I/O write:     0.00s
Parse time:    0.62s
Bind time:     0.30s
Check time:    7.27s
Emit time:     0.02s
Total time:    8.21s
```

**Related Issues:** #21221

**Comment by amcasey** [comment]
Updated [gist URL](https://gist.github.com/proteriax/a07dfd09c8913db2ac085ad0e1c11898) (I think).

**Comment by amcasey** [comment]
@proteriax Are you still seeing this?  I tried with both TS nightly and TS 3.2.2 (from your package.json), but couldn't reproduce the delay in VS Code or the command line build.

It seems possible that the `lowdb` type declarations have been refined since then and no longer have this issue.

**Comment by proteriax** [comment]
@amcasey I can’t reproduce this issue either.

**Comment by amcasey** [comment]
@proteriax Glad to hear it.  Sorry it took so long to get you an update.
