### ISSUE TITLE
Function or value overload type guard does not default to the function definition given

### ISSUE THREAD

**Issue by davhdavh** [Microsoft/TypeScript#29057]
**TypeScript Version:**  3.2.2

**Search Terms:**
function, overload, type constraint, type guard

**Code**

```ts
function findIdx<T>(arr: T[], elementOrPredicate: T | ((item: T) => boolean)) {
   let idx = -1;
   if (typeof elementOrPredicate === "function") {
      for (let i = 0; i < arr.length; i++) {
         if (elementOrPredicate(arr[i])) { //<--- error here!!
            idx = i;
            break;
         }
      }
   } else
      idx = arr.indexOf(elementOrPredicate);
   return idx;
}
```

**Expected behavior:**
No compile error, as it had before 3.0

**Actual behavior:**
Error TS2349: Build:Cannot invoke an expression whose type lacks a call signature. Type '((item: T) => boolean) | (T & Function)' has no compatible call signatures.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=function%20findIdx%3CT%3E(arr%3A%20T%5B%5D%2C%20elementOrPredicate%3A%20T%20%7C%20((item%3A%20T)%20%3D%3E%20boolean))%20%7B%0D%0A%20%20%20let%20idx%20%3D%20-1%3B%0D%0A%20%20%20if%20(typeof%20elementOrPredicate%20%3D%3D%3D%20%22function%22)%20%7B%0D%0A%20%20%20%20%20%20for%20(let%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20if%20(elementOrPredicate(arr%5Bi%5D))%20%7B%20%2F%2F%3C---%20error%20here!!%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20idx%20%3D%20i%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%7D%20else%0D%0A%20%20%20%20%20%20idx%20%3D%20arr.indexOf(elementOrPredicate)%3B%0D%0A%20%20%20return%20idx%3B%0D%0A%7D

**Related Issues:** 
No

**Comment by weswigham** [comment]
If `T` itself is a function type, the call is unsafe.

**Comment by weswigham** [comment]
(Also this is a [known breaking change](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#narrowing-functions-now-intersects--object-and-unconstrained-generic-type-parameters))
