### ISSUE TITLE
Closure Array Compilation Error Code TS2322.

### ISSUE THREAD

**Issue by salmankhann** [Microsoft/TypeScript#29058]
**TypeScript Version:**  3.2.2

**Search Terms:**
error TS2322: Types of property 'length' are incompatible. Type '2' is not assignable to type '1'.

**Code**
```

type ProxyComponent {
   simulate() {
       //Some Implementation
    }
}

type UserStory = {
    setup: () => [(component: ProxyComponent) => void]
};


//Compiles perfectly!
let userStory: UserStory = {
   setup: () => [(component) => component.simulate()]                   
}

```

```
//Fails to Compile!
/*
error TS2322: Type '[(component: ProxyComponent) => void, (component: ProxyComponent) => void]' is not assignable to type '[(component: ProxyComponent) => void]'.
      Types of property 'length' are incompatible.
        Type '2' is not assignable to type '1'.
*/
let userStory1: UserStory = {
   setup: () => [(component) => component.simulate(), (component) => component.simulate()]                   
}
```

I tried multiple things:
1. Creating a Type for the closure and using it as the type of the setup property but that gives the same error. like ```type SetupStatement = () => [(component: ProxyComponent) => void];``` but that didn't work either.
2. Declaring the value of the setup method.

**Expected behavior:**
Code should compile correctly because the return types of the array match. It works perfectly for a single element but fails for multiple elements.

**Actual behavior:**
Compilation fails with the following error

```
error TS2322: Type '[(component: ProxyComponent) => void, (component: ProxyComponent) => void]' is not assignable to type '[(component: ProxyComponent) => void]'.
      Types of property 'length' are incompatible.
        Type '2' is not assignable to type '1'.
```
**Playground Link:** 
[Link to Playground](https://www.typescriptlang.org/play/#src=type%20ProxyComponent%20%3D%20%7B%0D%0A%20%20%20simulate()%20%7B%0D%0A%20%20%20%20%20%20%20%2F%2FSome%20Implementation%0D%0A%7D%3B%0D%0A%0D%0Atype%20UserStory%20%3D%20%7B%0D%0A%20%20%20%20setup%3A%20()%20%3D%3E%20%5B(component%3A%20ProxyComponent)%20%3D%3E%20void%5D%0D%0A%7D%3B%0D%0A%0D%0A%0D%0A%2F%2FCompiles%20perfectly!%0D%0Alet%20userStory%3A%20UserStory%20%3D%20%7B%0D%0A%20%20%20setup%3A%20()%20%3D%3E%20%5B(component)%20%3D%3E%20component.simulate()%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%7D%0D%0A%0D%0A%2F*%0D%0Aerror%20TS2322%3A%20Type%20'%5B(component%3A%20ProxyComponent)%20%3D%3E%20void%2C%20(component%3A%20ProxyComponent)%20%3D%3E%20void%5D'%20is%20not%20assignable%20to%20type%20'%5B(component%3A%20ProxyComponent)%20%3D%3E%20void%5D'.%0D%0A%20%20%20%20%20%20Types%20of%20property%20'length'%20are%20incompatible.%0D%0A%20%20%20%20%20%20%20%20Type%20'2'%20is%20not%20assignable%20to%20type%20'1'.%0D%0A*%2F%0D%0Alet%20userStory1%3A%20UserStory%20%3D%20%7B%0D%0A%20%20%20setup%3A%20()%20%3D%3E%20%5B(component)%20%3D%3E%20component.simulate()%2C%20(component)%20%3D%3E%20component.simulate()%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%7D)

**Related Issues:**

**Comment by j-oliveras** [comment]
In:
```ts
type UserStory = {
    setup: () => [(component: ProxyComponent) => void]
};
```
you declares a setup method that return a tuple with only one element.

If you want an array without limits declare it as:
```ts
type UserStory = {
    setup: () => ((component: ProxyComponent) => void)[]
};
```

**Comment by salmankhann** [comment]
Oops didn't know that that was the tuple syntax! There could be better error message from the compiler though.

Thanks for helping!
