### ISSUE TITLE
[Compiler API] How to hoist variable to the top scope

### ISSUE THREAD

**Issue by longlho** [Microsoft/TypeScript#29065]
Hi there, I'm trying to write a transformer that hoist constant variable decl to the top scope:
```
function () {
  const FOO = 1
  return FOO + 1
}
```
to
```
const FOO = 1
function () {
  return FOO + 1
}
```

I've been digging through the existing transformers but could not find an example that does this. Any pointer would be great!

Thanks!

**Comment by weswigham** [comment]
The `extract constant` quickfix does this - see `src/services/refactors/extractSymbol.ts` for reference. It's more a bit involved than a simple syntactic transform.

**Comment by longlho** [comment]
Thanks for the pointer! I'll take a look!

**Comment by longlho** [comment]
@weswigham I'm tracing through the code and am having trouble how to replicate that using the transformer API. Please correct me if I'm wrong, but looks like after extracting the constant, change tracker (private API) is able to find the top of the file (while advancing through things like prologue directives & top level comments) and insert the node there.

From a transformer API, which from what I understand is per-node visitor pattern, does this sound like roughly what I should do:
```
function createVisitor(ctx: ts.TransformationContext, sf: ts.SourceFile): ts.Visitor {
  const visitor: ts.Visitor = node => {
   // Find 1st non-prologue in sf.statements
  // Mark that as insertion node (say, topNode)
  // Manually traverse down every statement to find constant decl
  // Once found, return [...hoistedVarStatements, topNode]
  };
  return visitor;
}
```

The `Manually traverse down every statement to find constant decl` seems inefficient to me, but idk if it's possible to traverse back up to append the hoisted var since it might be so far down the tree. Am I on the wrong path?

Thanks!

**Comment by weswigham** [comment]
Nope, traversing the tree to find the references is usually the way to go.

**Comment by longlho** [comment]
would it be ok if I make a PR to extract out https://github.com/Microsoft/TypeScript/blob/master/src/services/textChanges.ts#L1003 to a public API?

**Comment by weswigham** [comment]
...I don't think so? What you probably just want is to parse your input file into an AST, transform it, then print iit with `createPrinter`. Text change ranges are an optimization layer over that basic API for slightly better editor support (so we can layer multiple changes without reparsing).

**Comment by longlho** [comment]
Ah sorry since I had to replicate the logic to find the right position to insert the hoisted node (below prologue + triple slash directive + shebang + comment) and that code block seems to do what I'm looking for so I thought it can be extracted out.

Also things like `isPrologueDirective` (or the type itself) are private. Any chance of bringing some of those public?

**Comment by weswigham** [comment]
Hmm `isPrologueDirective` is private because it's a super simple internal helper - it's just checking if the thing is an expression statement where the expression is a string (because that's all a prologue directive is). Triple slash/shebangs and other comments aren't represented as nodes, so simply replacing nodes via a transformer is usually sufficient.

**Comment by weswigham** [comment]
Hmm `isPrologueDirective` is private because it's a super simple internal helper - it's just checking if the thing is an expression statement where the expression is a string (because that's all a prologue directive is). Triple slash/shebangs and other comments aren't represented as nodes, so simply replacing nodes via a transformer is usually sufficient.

**Comment by longlho** [comment]
Ah gotcha! Thanks a lot for the help!! Feel free to close this issue :)
