### ISSUE TITLE
Automatically resolve class dependency

### ISSUE THREAD

**Issue by J-F-Liu** [Microsoft/TypeScript#2906]
For example two class in two files:
`class A extends B{}`
`class B{}`
Compile with `tsc -t ES5 --out out.js A.ts B.ts`, generate js is:
~~~~~~~~~~~~~
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var A = (function (_super) {
    __extends(A, _super);
    function A() {
        _super.apply(this, arguments);
    }
    return A;
})(B);
var B = (function () {
    function B() {
    }
    return B;
})();
~~~~~~~~~~~~~~~
The code won't run since B is not defined when defining A.
Can the compiler automatically resolve class dependency and place the generated B code before A?

**Comment by vasa-c** [comment]
/// <reference path="b.ts" />
it should help

**Comment by J-F-Liu** [comment]
It is tedious to specify reference for lots of files.

**Comment by RyanCavanaugh** [comment]
If you want to compile all the files in a directory, just use tsconfig.json.
