### ISSUE TITLE
Type 'void' is not assignable to type 'string'. with overloads

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#29074]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
export interface Interface
{
	fn(): string
	fn(): void
}

export function f(opt: Interface)
{

}

f({
	fn()
	{

	},
});
```

**Expected behavior:**

> no error

**Actual behavior:**

> TS2322: Type '() => void' is not assignable to type '{ (): string; (): void; }'.
  Type 'void' is not assignable to type 'string'.

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
When assigning a source *S* to a target *T*, each signature in *T* must have a compatible signature in *S*.
