### ISSUE TITLE
lib.dom.d.ts: IndexedDB typings: "IDBValidKey | IDBKeyRange" used instead of just "IDBValidKey" in several places

### ISSUE THREAD

**Issue by mikelehen** [Microsoft/TypeScript#29070]
**TypeScript Version:**  3.3.0
**Search Terms:** IDBValidKey, IDBKeyRange
**Code**

```ts
let x: IDBCursor;
const y: IDBValidKey = x.primaryKey;
```

**Expected behavior:**
No compile errors.

**Actual behavior:**
```
typescript-indexeddb-bug.ts:2:7 - error TS2322: Type 'string | number | Date | ArrayBuffer | ArrayBufferView | IDBArrayKey | IDBKeyRange' is not assignable to type 'IDBValidKey'.
  Type 'IDBKeyRange' is not assignable to type 'IDBValidKey'.
    Type 'IDBKeyRange' is missing the following properties from type 'IDBArrayKey': length, pop, push, concat, and 16 more.

2 const y: IDBValidKey = x.primaryKey;
```

**Related Issues:** 

Doing a manual audit of lib.dom.d.ts, the following properties and methods contain incorrect usages of `IDBValidKey | IDBKeyRange` and should just be `IDBValidKey` instead:
* IDBCursor.key
* IDBCursor.primaryKey
* IDBCursor.continue()
* IDBCursor.continuePrimaryKey() [both parameters]
* IDBObjectStore.add()
* IDBObjectStore.put()

I would be happy to send a PR, but my impression is that these typing files are auto-generated.

**Comment by DanielRosenwasser** [comment]
PRs welcomed. You can find more information about contributing `lib.d.ts` fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mikelehen** [comment]
@DanielRosenwasser Thanks!  The file in question is https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts and the last commit to it says "Nov 2018 DOM update" And I don't see any recent commits to it that seem like manual fixes.  So can you just reconfirm that I really can just send a PR against that file directly?  Thanks.

**Comment by DanielRosenwasser** [comment]
@sandersn will eventually sync up the files for the next release for 3.3, which is slated for the end of January.

**Comment by kitsonk** [comment]
>  So can you just reconfirm that I really can just send a PR against that file directly?

Just to clarify, no you can't send a PR directly to that file.  You have to follow the process outlined in the: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by mikelehen** [comment]
@kitsonk Ahh! I see, thanks.
