### ISSUE TITLE
JavaScript infer types from usage inserts jsdoc in wrong location for const arrow function

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#29072]
**TypeScript Version:**  3.3.0-dev.20181214

**Search Terms:**
- javascript
- jsdocs
- quick fix
- infer types from usage

**Code**
For the JavaScript:

```ts
// @ts-check

const a = (x) => x.y + 1;
```
1. Run the infer types from usage quick fix on `x`

**Expected behavior:**

```ts
// @ts-check

/**
 * @param {{ y: number; }} x
 */
const a =  (x) => x.y + 1;
```

**Actual behavior:**

```ts
// @ts-check

const a = /**
 * @param {{ y: number; }} x
 */
 (x) => x.y + 1;
```
**Playground Link:** 

**Related Issues:**

**Comment by piotrzarycki** [comment]
Ok, working on this :)

**Comment by peanutenthusiast** [comment]
I'm interested in working on this!

**Comment by fuafa** [comment]
Hi, I submitted a pull request, but it does not work for (more then) the following situations, should I need to consider these situations as well?
```ts
const foo = x => y => x + y // infer on y
const l = [x => x + 1]
const o = { f: x => x + 1 }
bar(1, x => console.log(x))
```
