### ISSUE TITLE
Cannot union with undefined/null in ambient declaration

### ISSUE THREAD

**Issue by aleclarson** [Microsoft/TypeScript#29077]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:** union undefined ambient declaration

**Code**

```ts
// example.d.ts
type T = string | null | undefined
```

**Expected behavior:**

Type `T` should be `string | null | undefined`.

**Actual behavior:**

Type `T` is only `string`.

**Playground Link:** N/A

**Related Issues:** None

**Comment by AnyhowStep** [comment]
strictNullChecks? Just checking

**Comment by aleclarson** [comment]
I was missing a `tsconfig.json`, which meant no `strictNullChecks`. Thanks @AnyhowStep!
