### ISSUE TITLE
Modules imports

### ISSUE THREAD

**Issue by KhaosTheory1012** [Microsoft/TypeScript#2907]
I am currently trying out typescript 1.5 alpha but the compiler always tells me:

src\Person.ts(4,1): 1128 Declaration or statement expected.
src\Person.ts(4,8): 1109 Expression expected.
src\Person.ts(4,13): 1005 ';' expected.
src\Person.ts(4,22): 1005 ';' expected.
src\Person.ts(4,27): 1005 ';' expected.

when trying to import modules like that:

 import {  } from "angular2/angular2";

EDIT: fixed it but now:
src/Person.ts(4,25): error TS2307: Cannot find external module 'angular2/angular2'.

**Comment by RyanCavanaugh** [comment]
Do you have a .d.ts file defining `angular2` ?

**Comment by KhaosTheory1012** [comment]
No there is no .d.ts file in there

**Comment by RyanCavanaugh** [comment]
You will need some definition for `angular2/angular2` in order to not get that error.

**Comment by KhaosTheory1012** [comment]
How do I get those, they arent included in the modules folders I get from npm and github

**Comment by FalloutPL** [comment]
http://definitelytyped.org/

2015-04-24 19:57 GMT+02:00 KhaosTheory1012 <notifications@github.com>:

**Comment by mhegazy** [comment]
courtesy of @alexeagle, here is the Angular2 https://github.com/rkirov/ng2-ts-hello/blob/master/typings/angular2/angular2.d.ts

**Comment by alexeagle** [comment]
Note, that is a minimal .d.ts for our demos, we are working right now to publish one for the whole angular2 library.

**Comment by KhaosTheory1012** [comment]
I am sorry to bother you but I don't get it. I am trying to setup a project for a little tryout at university for a lecture and we are supposed to use recent angular2 and typescript alpha releases. Problem is, none of us have worked with it before so we are kind of new to the whole js world. Is there any way of getting a version of angular2 with those definitions or a stepbystep guide. My team and I are searching since a week now to set something up, we can start working with. We looked at the ngconf demo but for our own project we can't use any of those angular2 versions. At least we always get some kind of error. I know it is all in development right now and I would work with angular 1.x but like I mentioned before we are supposed to work with angular2 and typescript.

**Comment by mhegazy** [comment]
can you try the steps in here: https://github.com/rkirov/ng2-ts-hello

**Comment by mhegazy** [comment]
I will update ngconf2015demo to follow the same as well

**Comment by mhegazy** [comment]
@KhaosTheory1012, https://github.com/Microsoft/ngconf2015demo is now updated as well.

Thanks @alexeagle and @rkirov for the help!

**Comment by KhaosTheory1012** [comment]
Thank you very much, I appreciate your help!

**Comment by mhegazy** [comment]
Glad this helped. Please let us know if run into other issues.

**Comment by KhaosTheory1012** [comment]
We came to another problem. We want to import a module to fetch some data from our RESTapi but the angular2.d.ts file doesn't describe how to get there. So I wonder how can we edit it so we can import stuff like zone and xhr.

**Comment by mhegazy** [comment]
@KhaosTheory1012 i will need more information about the issue you are running into. Is this similar to #2920, you will need to define the shape of the module you are importing. I would look for typings of popular libraries on http://definitelytyped.org/; if it is your own library you will need to hand author your .d.ts for it. here are some documentation to get you started: https://github.com/Microsoft/TypeScript/wiki/Writing%20Definition%20Files

**Comment by KhaosTheory1012** [comment]
Okay so we are trying to import modules other than the ones defined in angular2.d.ts (https://github.com/Microsoft/ngconf2015demo/tree/master/angular2) We are using this version of angular2 because every other one we wanted to use with typscript didn't work or at least we didn't know where to get already written .d.ts files from. 
But everything we are trying to import is from angular2. No library of our own.
At the moment we are meant to build an app that is fetiching data from a RESTapi. So we wanted to access the modules from angular2: zone and xhr to get the functionality of $http $resource

**Comment by mhegazy** [comment]
@alexeagle, any recommendations here?

**Comment by alexeagle** [comment]
The angular2.d.ts is very minimal, so it's expected that you fall off a cliff right now as soon as you try to do something beyond the demo. For now, you can just use type `any` to short-circuit the type-checking in the TypeScript compiler as a workaround.

We need to figure out what will be in the .d.ts we publish, and what won't. For example, zone is a third party library Angular depends on, so the typings for it ought to be published independently (but I don't see them on DefinitelyTyped). We also need to figure out the mechanics of generating and bundling the angular2.d.ts from our sources. I plan to investigate https://github.com/TypeStrong/dts-bundle today, and Mohamed I might have some questions for you along the way...

**Comment by KhaosTheory1012** [comment]
Is there a way to use the actual angular2 repository with typescript 1.5 beta now?
Or will it only work when the transition from atscript/es6 to .ts is done?`
Because we are currently running into the problem of not being able to use things like EventEmitter or other things like forms.

**Comment by alexeagle** [comment]
The build system for the angular2 repo is pretty complex. The whole thing is already parsed by typescript compiler, but for some parts we use the emit from tsc and for other parts still traceur. More complex yet, that mix depends if you are in node or targeting a browser. And it will change a lot next week.
I'm not sure the status of forms but I think that is still pre-alpha. Everything that's ready to use should be shipped in the two bundles we distributed (eg. the one included in the quickstart repo).
Please file a separate issue on the angular/angular repo if you find features which should be part of developer preview release, but which you cannot use through the bundle we distribute. Thanks for sticking with us during the early pre-beta days :)

**Comment by KhaosTheory1012** [comment]
@alexeagle I tried to use alpha .22 with typescript in my Angular2 project (https://github.com/KhaosTheory1012/Angular2_Prototype) and I am getting type errors for all my local variables. For example "TypeError: Cannot read property 'value' of undefined in [!index.value in null]"
I used the new .d.ts you uploaded on DefinitelyTyped aswell as the old one with ts 1.5 beta but I can't figure out whats the problem.
