### ISSUE TITLE
Suggestion: Add a special key that would disable resolving files that are missing in file list passed to the compiler

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#2908]
Currently a compiler can be given one single file from where it can resolve all dependencies by looking at the file system. Most of the time it is a very convenient feature, but when I need to clearly separate one set of files from another I wish I could turn it off. So that unless a file is explicitly in the list passed to the compiler, I don't want it to be resolved.

**Comment by mhegazy** [comment]
use `--noResolve`.

**Comment by aleksey-bykov** [comment]
Thanks!
