### ISSUE TITLE
the union type in  operational character

### ISSUE THREAD

**Issue by yegao** [Microsoft/TypeScript#29098]
The following is the code I wrote while debugging, but I got an error.
```
function fn (x: number | string,y: number | string){
    return x+y 
}
```

But there is no problem writing this way.
```
function fn (x: number,y: string){
    return x+y 
}
```

The following writing method will also give an error.
```
function fn (x: number | string,y: number){
    return x+y 
}
```

In my understanding, the `+` operation is an operation symbol common to number and string. Why is it wrong? Is this a bug?

**Comment by ahejlsberg** [comment]
Applying `+` to `number` and `string` always performs the same operation (concatenating the string representation of the number to the other string) and is a very common operation. Applying `+` to `number | string` operands, on the other hand, will either concatenate strings or perform an addition. That is very unlikely to be what you want, so we error.

**Comment by yegao** [comment]
> Applying `+` to `number` and `string` always performs the same operation (concatenating the string representation of the number to the other string) and is a very common operation. Applying `+` to `number | string` operands, on the other hand, will either concatenate strings or perform an addition. That is very unlikely to be what you want, so we error.

That's cool,  I got it !  Thank you!
