### ISSUE TITLE
Autocompletion in typeof expressions does not work

### ISSUE THREAD

**Issue by hediet** [Microsoft/TypeScript#29099]
**TypeScript Version:**  3.3.0-dev.20181219

**Search Terms:**
Autocompletion, typeof, parameter, function
**Code**

```ts
const x = "str";

function test(arg: typeof x./* | */length) {
}
```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/2931520/50231314-cf61d980-03ae-11e9-8dba-9dc6e75c80eb.png)
Even though parenthesis aren't allowed, autocompletion works in them. It should also work for the example above.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/2931520/50231325-d5f05100-03ae-11e9-905a-9c5f6f785174.png)
Autocompletion does not work for the members of x in the typeof expression.

**Comment by DanielRosenwasser** [comment]
Thanks @Kingwl!
