### ISSUE TITLE
New Website Logo: AssureSign

### ISSUE THREAD

**Issue by jbrantly** [Microsoft/TypeScript#2909]
- Name: AssureSign
- Homepage url: https://www.assuresign.com/
- Logo: https://assuresignmedia.blob.core.windows.net/public/AssureSign_Logos_Final.svg

We use TypeScript in our SaaS product. We also maintain the webpack TypeScript loader at https://github.com/jbrantly/ts-loader

**Comment by jonathandturner** [comment]
Added.
