### ISSUE TITLE
Allow all modules in a namespace to be aliased with a single directive

### ISSUE THREAD

**Issue by IanKemp** [Microsoft/TypeScript#29104]
We have a bunch of TS interfaces and classes that we autogenerate from C# code:

```ts
namespace Foo.Bar.Quux {
    export interface MyClass {
    }

    export interface AnotherClass {
    }
}
```

The file that these are defined in, is imported into the global scope via `tsconfig.json` and we then use the classes as needed:

```ts
export class Something extends React.Component<Foo.Bar.Quux.MyClass> {
    doThe(thing: Foo.Bar.Quux.MyClass) {
    }

    doAnother(thing: Foo.Bar.Quux.AnotherClass) {
    }
}
```

Problem: the C# namespace changes due to refactoring, so the autogenerated TS file changes, and every TypeScript file that relies on those classes being in that namespace breaks. Then we have to do a manual exercise to fix up our TS files.

A partial way to alleviate this pain is via aliases:

```ts
import MyClass = Foo.Bar.Quux.MyClass;
import AnotherClass = Foo.Bar.Quux.AnotherClass;

export class Something extends React.Component<MyClass> {
    doThe(thing: MyClass) {
    }

    doAnother(thing: AnotherClass) {
    }
}
```

Now when a rename happens and the TS code breaks, we only have to update the aliases at the top of each file.

Problem: if there are a lot of aliases, each one has to be updated. In this example there are only 2, but in some of our files there are many. And having to specify an alias for each class in the same namespace seems redundant and wasteful.

Solution: `import * = <Namespace>` (syntax is up for debate, I just went with a blend of current TS alias declarations + C# `using`). This construct essentially expands to multiple import aliases, one for every class in the namespace (i.e. it's syntactic sugar for the previous example I gave).

```ts
import * = Foo.Bar.Quux; // imports all classes (MyClass, AnotherClass) from this namespace into the current scope

export class Something extends React.Component<MyClass> {
    doThe(thing: MyClass) {
    }

    doAnother(thing: AnotherClass) {
    }
}
```

Now the C# namespace can be changed as many times as required and all that is required in our TS files is to fix a single line at the top of the file.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
We have a general stance that we won't enhance or expand the non-ECMAscript expression-level language features of the language (including namespaces and namespace import constructures). this way we don't expand the area where we may conflict with future spec updates.

Have you considered solving the root of your problem - you should consider modifying your refactoring tools to do cross-language refactorings within your codebase.
