### ISSUE TITLE
Allow type 'any' be assignable to type 'unique symbol'

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#29108]
## Search Terms

Type 'any' is not assignable to type 'unique symbol'.ts(2322)

## Suggestion

Sometimes we just need a `unique value` for distinguishing whether a value is a specific unique value. Using an object instance meets this situation just like the `Symbol` does. Using `Symbol` requires the executing environment support ES6 `Symbol`, so we tend to use a simple replacement just like `new String('simulate Symbol')`.

I propose **allow us to assert an `any` type value to be `unique symbol` type.**

```ts
const timeoutSignal: unique symbol = new String('@@timeoutSignal@@') as any    // tsc complains
```

At present, the TSC complains:
```ts
// Type 'any' is not assignable to type 'unique symbol'.ts(2322)
```

It's unlike the other primitive value type. I know it has runtime risk, but it is what the manually assert a type means for.

```ts
// not safe, but the types are compatible with the asserted type 'any' 
const fakeNumber: 42 = 'whatever' as any   // tsc allows us to assign 'any' type to 42 type
const fakeString: 'foo' = 'whatever' as any    // tsc allows us to assign 'any' type to 'foo' type
```

## Use Cases

```ts
const timeoutSignal: unique symbol= new String('tiemout') as any
const haltSignal: unique symbol = new Number(1) as any

async function request <T>() {
    const ret = await Promise.race(
         sleep(5000).then(() => timeoutSignal),
         mayTriggerHaltSignalInAnyTime().then(() => haltSignal),
         requestRemoteData<T>(),
    )
    if (ret === timeoutSignal) {
           // retry
           return request<T>()
     }

      if (ret === haltSignal) {
          throw Error('Cancele by a halt signal')
      }

      return ret
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
@rbuckton Our rule
```
if (s & TypeFlags.UniqueESSymbol || t & TypeFlags.UniqueESSymbol) return false;
```
is higher priority than the source-is-any-and-its-an-assignability-or-comparability-check rule. Is this intentional? A `false` return in `isSimpleTypeRelatedTo` just prevents the following checks - even with a `false` return the rest of relationship checking (including structural checking of apparent types) still takes place.

cc @ahejlsberg

**Comment by rbuckton** [comment]
@weswigham: You are correct, there's no apparent need for this early exit.
