### ISSUE TITLE
class（set and get）'code tsc compiler error

### ISSUE THREAD

**Issue by houxingx** [microsoft/TypeScript#29103]
![image](https://user-images.githubusercontent.com/41282498/50275113-a9553b80-0479-11e9-89f8-67b5f71f4511.png)
![image](https://user-images.githubusercontent.com/41282498/50275170-bd00a200-0479-11e9-93c1-b06970e2f616.png)
![image](https://user-images.githubusercontent.com/41282498/50275333-11a41d00-047a-11e9-8df1-1fc169b03059.png)

**Comment by j-oliveras** [comment]
Probably in your tsconfig you don't defines the target and that defaults to ES3 (that not supports get/set). Set target to ES5 or higher and should solve it.

See [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by weswigham** [comment]
Indeed, I don't know what editor that is, but editor settings don't usually affect command line compiler errors. You probably need to add ` tsconfig` specifying the `target`.
