### ISSUE TITLE
Cannot cast to type after instanceof operator check

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/TypeScript#2912]
In below code, the line ```var vaaa = <Aaa>v;``` reports error: ```error TS2352: Build: Neither type 'T' nor type 'Aaa' is assignable to the other.```. I should be able to even access Aaa members without case because of this guard check.

Is this bug or I'm doing something against specification?

```ts
interface IHolder<T> {
  base: T;
  variant1: T;
  variant2: T;
}
class Holder<T> implements IHolder<T> {
  base: T;
  variant1: T;
  variant2: T;
}

class Aaa {
  item: string;
}
class Test {
  someValue: IHolder<Aaa>;

  constructor() {
    this.someValue = new Holder<Aaa>();
    this.aaa(this.someValue);
  }

  aaa<T>(vv: IHolder<T>): void {
    var v = vv.base;

    if (v instanceof Aaa) {
      var vaaa = <Aaa>v;
    }
  }
}
```

**Comment by wgebczyk** [comment]
Can someone confirm bug or deny?

**Comment by RyanCavanaugh** [comment]
It's not a bug according to the spec -- we don't narrow variables of a generic type parameter type, so the `instanceof` check does nothing in terms of modifying the assignability of `v` inside the `if` block.

**Comment by wgebczyk** [comment]
OK. I understand that in some cases the guard/if statement is meaningless.
As the language is young, could we get warning whenever such meaningless "thing" is spotted in sources? Writing IF usually express some assumptions and having kind compiler that reminds on silly code would be beneficial!

**Comment by danquirk** [comment]
The problem is that there're a lot of valid uses of this code. To make it an error would break a lot of peoples' current codebases.

**Comment by wgebczyk** [comment]
1. That's why I suggest to have warning.
2. Can you tell me in my example with generics, that it might be valid?

**Comment by mhegazy** [comment]
as noted by @danquirk, a warring is not appropriate here. you need to constrain T:

```ts
    aaa<T extends Aaa>(vv: IHolder<T>): void {
        var t: T;
        var a: Aaa;

        a = t; // OK
        t = a; // still not OK, T is Aaa but Aaa is not guaranteed to be T
        
        (<Aaa>t) // OK, as T is assignable to Aaa
    }
```
