### ISSUE TITLE
Share types across function/method scopes

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#29124]
This is a feature request, might be tricky to implement or might not be a good idea not sure.

Basically I have this situation:

This callback type definition

```typescript
export type EVCb<T = any, E = any> = (err: E, T?: any) => void;
```

and then some methods on an object/class

```typescript
method_A(cb: EVCb<{foo:string, pack: typeof pack}>){
   const pack = {...}
},

method_B(input:{foo:string, pack: typeof pack}){

}
```

what's going on here is that I want the type definition of the object pack declared inside method_A to be referenced by method_B somehow.

But this is what I am getting atm:

![screenshot from 2018-12-21 18-39-35](https://user-images.githubusercontent.com/11139560/50369845-877ab800-0550-11e9-95e9-0a6c18c9634b.png)

**Comment by weswigham** [comment]
Define an interface in the enclosing scope and use it in both locations?
