### ISSUE TITLE
[i18n] Intl getCanonicalLocales / RelativeTimeFormat / ListFormat > 2339 error

### ISSUE THREAD

**Issue by dtruffaut** [microsoft/TypeScript#29129]
**TypeScript Version:**  3.2.2

**Search Terms:**
Intl.getCanonicalLocales TS TypeScript Error 2339 undefined i18n

**Code**

```ts
Intl.getCanonicalLocales('EN-US');
```

**Expected behavior:**
Code works, and returns ["en-US"]
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Intl/getCanonicalLocales

**Actual behavior:**
TS Error 2339, the property getCanonicalLocales does not exists on Intl

**Comment by dtruffaut** [comment]
Same thing with

**Code**
```
new Intl.RelativeTimeFormat('en-US');
```
**Expected behavior:**
Code works
https://developers.google.com/web/updates/2018/10/intl-relativetimeformat

Actual behavior:
TS Error 2339, the property getCanonicalLocales does not exists on Intl

**Comment by dtruffaut** [comment]
Same thing with

**Code**
```
new Intl.ListFormat('en');
```
**Expected behavior:**
Code works
https://developers.google.com/web/updates/2018/12/intl-listformat

**Actual behavior:**
TS Error 2339, the property ListFormat does not exists on Intl

**Comment by dtruffaut** [comment]
It appears to not be possible to extend the Intl object in a types.d.ts file.
There is no trick to bypass this, until this bug is fixed.

**Comment by j-oliveras** [comment]
Drafts are not included into libs. You can declare a `d.ts` file with the definitions:

```ts
declare namespace Intl {
    function getCanonicalLocales(locales: string | string[]): string[];

    class RelativeTimeFormat {
        constructor(locale: string);

        // TODO Add other properties/methods
    }
    // const RelativeTimeFormat: any; // Use this instead of the class if you don't want to declare al properties/methods

    class ListFormat {
        constructor(locale: string);

        // TODO Add other properties/methods
    }
    // const ListFormat: any; // Use this instead of the class if you don't want to declare al properties/methods
}
```

**Comment by Dassderdie** [comment]
Is there any update on this? RelativeDateTime should is now more than a draft: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat

**Comment by longlho** [comment]
It’s not stage 4 yet

**Comment by jessamp** [comment]
Has Intl.ListFormat been added for support?

**Comment by proteriax** [comment]
It is now stage 4.

**Comment by noinkling** [comment]
One of the polyfills for `Intl.ListFormat` has [a declaration file](https://github.com/wessberg/intl-list-format/blob/master/src/typings.d.ts) that you can use in the meantime.

`RelativeTimeFormat` has already been added.

#39662 is pending for `getCanonicalLocales`

**Comment by blessanm86** [comment]
I tried adding the target as `ES2021` mentioned in the linked issue but still get an error for `ListFormat`.
I am using typescript version v4.6.2

**Comment by longlho** [comment]
Try adding esnext & upgrade to 4.7

**Comment by wycats** [comment]
What's the deal with this?

**Comment by cvkline** [comment]
Everything appears to be updated and available in one of the compiler lib.d.ts versions such as ES2020.Intl... except for `getCanonicalLocales`. That seems strange to me.

**Comment by AkaraChen** [comment]
Any update on it?

**Comment by gurmeet-bluesheets** [comment]
A workaround 

declare namespace Intl {
  type Key = 'calendar' | 'collation' | 'currency' | 'numberingSystem' | 'timeZone' | 'unit';
  type DateTimeFormatOptions = {
    localeMatcher?: "best fit" | "lookup";
    weekday?: "long" | "short" | "narrow";
    era?: "long" | "short" | "narrow";
    year?: "numeric" | "2-digit";
    month?: "numeric" | "2-digit" | "long" | "short" | "narrow";
    day?: "numeric" | "2-digit";
    hour?: "numeric" | "2-digit";
    minute?: "numeric" | "2-digit";
    second?: "numeric" | "2-digit";
    timeZoneName?: "long" | "short";
    formatMatcher?: "best fit" | "basic";
    hour12?: boolean;
    timeZone?: string;
  }
  function supportedValuesOf(input: Key): string[];
  class DateTimeFormat {
    constructor(locales?: string | string[], options?: DateTimeFormatOptions);
    format(date?: Date | number): string;
  }
}

**Comment by PindaPixel** [comment]
I see this is merged, what version can we expect this in? It doesn't seem to be in 5.3.2.

**Comment by sandersn** [comment]
Must have been after the 5.3 cutoff, because it's only in `main` branch, not `release-5.3`.
