### ISSUE TITLE
Referencing ReturnType<FooT> in generic param, and passing a function that has one param causes incorrect type inference...

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#29133]
**TypeScript Version:**  3.3.0-dev.20181129

**Search Terms:** ReturnType, Generic Param, Generic Function Argument

**Code**

```ts
//Innocent enough.
//Take a T, return a T
type Foo<T extends number> = (t: T) => T;

//=== NOT using ReturnType<FooT> in Generic Parameters ==
declare function bar<
    T extends number,
    FooT extends Foo<T>
>(t: T, foo: FooT): ReturnType<FooT>
//OK! `barResult` is of type `3`
const barResult = bar(
    3 as (3|5),
    () => 3
);
//OK! `barResult2` is of type `3`
const barResult2 = bar(
    3 as (3|5),
    //`t` is of type `3|5`
    //Return type is 3 
    t => 3
);

//=== Using ReturnType<FooT> in Generic Parameters ==
declare function baz<
    T extends number,
    FooT extends Foo<T>,
    //The same as bar<> but we reference ReturnType<FooT> here
    Ret extends ReturnType<FooT>
>(t: T, foo: FooT, ret: Ret): ReturnType<FooT>
//OK! `bazResult` is of type `3`
const bazResult = baz(
    3 as (3|5),
    () => 3,
    3
);
//NOT OK! `bazResult2` is of type `3|5`!
const bazResult2 = baz(
    3 as (3|5),
    //`t` is of type `3|5`
    //Return type is `3`
    t => 3,
    3
);

//NOT OK! `bazResult3` is of type `3|5`!
const bazResult3 = baz(
    3 as (3|5),
    //`t` is of type `3|5`
    //Return type is `3`
    //We *force* the return type to be 3
    (t) : 3 => (3 as 3),
    3
);
```

**Expected behavior:**

`bazResult2` and `bazResult3` should be of type `3`, the same as `bazResult`

**Actual behavior:**

`bazResult2` and `bazResult3` are of type `3|5`, different from `bazResult` (which is of type `3`)

The difference between `bazResult` and `bazResult2` is literally 3 characters but it causes the inferred types to be very different.

**Playground Link:** [Here](http://www.typescriptlang.org/play/#src=%2F%2FInnocent%20enough.%0A%2F%2FTake%20a%20T%2C%20return%20a%20T%0Atype%20Foo%3CT%20extends%20number%3E%20%3D%20(t%3A%20T)%20%3D%3E%20T%3B%0A%0A%2F%2F%3D%3D%3D%20NOT%20using%20ReturnType%3CFooT%3E%20in%20Generic%20Parameters%20%3D%3D%0Adeclare%20function%20bar%3C%0A%20%20%20%20T%20extends%20number%2C%0A%20%20%20%20FooT%20extends%20Foo%3CT%3E%0A%3E(t%3A%20T%2C%20foo%3A%20FooT)%3A%20ReturnType%3CFooT%3E%0A%2F%2FOK!%20%60barResult%60%20is%20of%20type%20%603%60%0Aconst%20barResult%20%3D%20bar(%0A%20%20%20%203%20as%20(3%7C5)%2C%0A%20%20%20%20()%20%3D%3E%203%0A)%3B%0A%2F%2FOK!%20%60barResult2%60%20is%20of%20type%20%603%60%0Aconst%20barResult2%20%3D%20bar(%0A%20%20%20%203%20as%20(3%7C5)%2C%0A%20%20%20%20%2F%2F%60t%60%20is%20of%20type%20%603%7C5%60%0A%20%20%20%20%2F%2FReturn%20type%20is%203%20%0A%20%20%20%20t%20%3D%3E%203%0A)%3B%0A%0A%2F%2F%3D%3D%3D%20Using%20ReturnType%3CFooT%3E%20in%20Generic%20Parameters%20%3D%3D%0Adeclare%20function%20baz%3C%0A%20%20%20%20T%20extends%20number%2C%0A%20%20%20%20FooT%20extends%20Foo%3CT%3E%2C%0A%20%20%20%20%2F%2FThe%20same%20as%20bar%3C%3E%20but%20we%20reference%20ReturnType%3CFooT%3E%20here%0A%20%20%20%20Ret%20extends%20ReturnType%3CFooT%3E%0A%3E(t%3A%20T%2C%20foo%3A%20FooT%2C%20ret%3A%20Ret)%3A%20ReturnType%3CFooT%3E%0A%2F%2FOK!%20%60bazResult%60%20is%20of%20type%20%603%60%0Aconst%20bazResult%20%3D%20baz(%0A%20%20%20%203%20as%20(3%7C5)%2C%0A%20%20%20%20()%20%3D%3E%203%2C%0A%20%20%20%203%0A)%3B%0A%2F%2FNOT%20OK!%20%60bazResult2%60%20is%20of%20type%20%603%7C5%60!%0Aconst%20bazResult2%20%3D%20baz(%0A%20%20%20%203%20as%20(3%7C5)%2C%0A%20%20%20%20%2F%2F%60t%60%20is%20of%20type%20%603%7C5%60%0A%20%20%20%20%2F%2FReturn%20type%20is%20%603%60%0A%20%20%20%20t%20%3D%3E%203%2C%0A%20%20%20%203%0A)%3B%0A%0A%2F%2FNOT%20OK!%20%60bazResult3%60%20is%20of%20type%20%603%7C5%60!%0Aconst%20bazResult3%20%3D%20baz(%0A%20%20%20%203%20as%20(3%7C5)%2C%0A%20%20%20%20%2F%2F%60t%60%20is%20of%20type%20%603%7C5%60%0A%20%20%20%20%2F%2FReturn%20type%20is%20%603%60%0A%20%20%20%20%2F%2FWe%20*force*%20the%20return%20type%20to%20be%203%0A%20%20%20%20(t)%20%3A%203%20%3D%3E%20(3%20as%203)%2C%0A%20%20%20%203%0A)%3B)

-----

I don't even know how to describe this...

My real use case is more complicated than the above example but I *need* the return type of a generic function to be inferred correctly to perform stronger compile-time type checks.

The strange thing is that `() => 3` will give me the correct return type, but `t => 3` will not.
In my own code, using the argument `t` is absolutely necessary.

As far as I've seen, this problem only occurs both the following are true,

1. `ReturnType<FooT>` is used in a generic param constraint
2. The concrete type of `FooT` has parameters (Like `t => 3` has parameters, `() => 3` does not)

If either of the above are false, this problem does not occur

**Comment by AnyhowStep** [comment]
This is a different repro,

It doesn't use `ReturnType<FooT>` in the generic params. It uses it in the function param.

```ts
//Innocent enough.
//Returns a T
type Foo<T> = (...args : any[]) => T;

//=== NOT using ReturnType<FooT> in Generic Parameters ==
declare function bar<
    FooT extends Foo<3|5>
>(foo: FooT): ReturnType<FooT>
//OK! `barResult` is of type `3`
const barResult = bar(
    () => 3
);
//OK! `barResult2` is of type `3`
const barResult2 = bar(
    //`t` is of type `3|5`
    //Return type is 3 
    t => 3
);

//=== Using ReturnType<FooT> in Generic Parameters ==
declare function baz<
    FooT extends Foo<3|5>,
>(
    foo: FooT & (
        ReturnType<FooT> extends 3 ?
        unknown :
        [
            "Only 3 allowed, received",
            ReturnType<FooT>
        ]
    )
): ReturnType<FooT>
//OK! `bazResult` is of type `3`
const bazResult = baz(
    () => 3
);
//NOT OK! `bazResult2` is of type `3|5`!
const bazResult2 = baz(
    //`t` is of type `3|5`
    //Return type is `3`
    //Error, ["Only 3 allowed, received", 3 | 5]
    t => 3
);

//NOT OK! `bazResult3` is of type `3|5`!
const bazResult3 = baz(
    //`t` is of type `3|5`
    //Return type is `3`
    //We *force* the return type to be 3
    //Error, ["Only 3 allowed, received", 3 | 5]
    (t) : 3 => (3 as 3)
);
```

[Playground](http://www.typescriptlang.org/play/#src=%2F%2FInnocent%20enough.%0A%2F%2FReturns%20a%20T%0Atype%20Foo%3CT%3E%20%3D%20(...args%20%3A%20any%5B%5D)%20%3D%3E%20T%3B%0A%0A%2F%2F%3D%3D%3D%20NOT%20using%20ReturnType%3CFooT%3E%20in%20Generic%20Parameters%20%3D%3D%0Adeclare%20function%20bar%3C%0A%20%20%20%20FooT%20extends%20Foo%3C3%7C5%3E%0A%3E(foo%3A%20FooT)%3A%20ReturnType%3CFooT%3E%0A%2F%2FOK!%20%60barResult%60%20is%20of%20type%20%603%60%0Aconst%20barResult%20%3D%20bar(%0A%20%20%20%20()%20%3D%3E%203%0A)%3B%0A%2F%2FOK!%20%60barResult2%60%20is%20of%20type%20%603%60%0Aconst%20barResult2%20%3D%20bar(%0A%20%20%20%20%2F%2F%60t%60%20is%20of%20type%20%603%7C5%60%0A%20%20%20%20%2F%2FReturn%20type%20is%203%20%0A%20%20%20%20t%20%3D%3E%203%0A)%3B%0A%0A%2F%2F%3D%3D%3D%20Using%20ReturnType%3CFooT%3E%20in%20Generic%20Parameters%20%3D%3D%0Adeclare%20function%20baz%3C%0A%20%20%20%20FooT%20extends%20Foo%3C3%7C5%3E%2C%0A%3E(%0A%20%20%20%20foo%3A%20FooT%20%26%20(%0A%20%20%20%20%20%20%20%20ReturnType%3CFooT%3E%20extends%203%20%3F%0A%20%20%20%20%20%20%20%20unknown%20%3A%0A%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22Only%203%20allowed%2C%20received%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20ReturnType%3CFooT%3E%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20)%0A)%3A%20ReturnType%3CFooT%3E%0A%2F%2FOK!%20%60bazResult%60%20is%20of%20type%20%603%60%0Aconst%20bazResult%20%3D%20baz(%0A%20%20%20%20()%20%3D%3E%203%0A)%3B%0A%2F%2FNOT%20OK!%20%60bazResult2%60%20is%20of%20type%20%603%7C5%60!%0Aconst%20bazResult2%20%3D%20baz(%0A%20%20%20%20%2F%2F%60t%60%20is%20of%20type%20%603%7C5%60%0A%20%20%20%20%2F%2FReturn%20type%20is%20%603%60%0A%20%20%20%20%2F%2FError%2C%20%5B%22Only%203%20allowed%2C%20received%22%2C%203%20%7C%205%5D%0A%20%20%20%20t%20%3D%3E%203%0A)%3B%0A%0A%2F%2FNOT%20OK!%20%60bazResult3%60%20is%20of%20type%20%603%7C5%60!%0Aconst%20bazResult3%20%3D%20baz(%0A%20%20%20%20%2F%2F%60t%60%20is%20of%20type%20%603%7C5%60%0A%20%20%20%20%2F%2FReturn%20type%20is%20%603%60%0A%20%20%20%20%2F%2FWe%20*force*%20the%20return%20type%20to%20be%203%0A%20%20%20%20%2F%2FError%2C%20%5B%22Only%203%20allowed%2C%20received%22%2C%203%20%7C%205%5D%0A%20%20%20%20(t)%20%3A%203%20%3D%3E%20(3%20as%203)%0A)%3B)

Of note is `bazResult3` where I went all-out and explicitly said that it returns `3` but the type checker still thinks it's `3|5`

**Comment by AnyhowStep** [comment]
Poked around a bit more and  it looks like if I explicitly say what type the parameters are, it infers the return type just fine.

```ts

//OK! `bazResult2` is of type `3`
const bazResult2 = baz(
    (t : number) => 3
);

//OK! `bazResult3` is of type `3`
const bazResult3 = baz(
    (t : number) : 3 => (3 as 3)
);
```

But in my actual use-case, the parameter type is pretty complicated because it depends on chaining many generic types, and it uses a builder pattern.

**Comment by AnyhowStep** [comment]
I've gotten TS to infer the return type of a generic function correctly, only in one part of my code.
I've been trying to dissect it and figure out what makes it work, when so many others fail.

Haven't made any headway, though. It's the most complicated of my types but it works for some reason ._.

**Comment by AnyhowStep** [comment]
After poking around a bit more, it seems to work fine with classes.
As in, the return type is inferred correctly.

```ts
class C<T> {
    constructor(readonly t : T) {
        
    }
    baz<FooT extends ((t : T) => (T | undefined))>(
        foo: FooT & (
            ReturnType<FooT> extends 1|2?
            ["1|2 is not allowed, received", ReturnType<FooT>] :
            unknown
        )
    ) : C<ReturnType<FooT>> {
        return new C(foo(this.t) as ReturnType<FooT>);
    }
}
const c = new C(1 as 1|2|3);
const c2 = c.baz(() => undefined);
const c3 = c.baz(() => 3);
//'() => 2' is missing the following properties from type '["1|2 is not allowed, received", 2]'
const c4 = c.baz(() => 2);
//'(1|2|3) => 2' is missing the following properties from type '["1|2 is not allowed, received", 2]'
const c5 = c.baz(t => 2);
//'() => 1' is missing the following properties from type '["1|2 is not allowed, received", 1]'
const c6 = c.baz(() => 1);
//'(1|2|3) => 1' is missing the following properties from type '["1|2 is not allowed, received", 1]'
const c7 = c.baz(t => 1);
```

**Comment by AnyhowStep** [comment]
Seems like classes really do run on different rules.

```ts
class C<T> {
    constructor(readonly t : T) {
        
    }
}

function baz<
    CType extends C<any>,
    FooT extends ((t: CType["t"]) => (CType["t"] | undefined)
)>(
    c : CType,
    foo: FooT & (
        ReturnType<FooT> extends 1|2?
        ["1|2 is not allowed, received", ReturnType<FooT>] :
        unknown
    )
) : C<ReturnType<FooT>> {
    return new C(foo(c.t) as ReturnType<FooT>);
}
const c = new C(1 as 1|2|3);
const c2 = baz(c, () => undefined);
const c2b = baz(c, t => undefined);
const c3 = baz(c, () => 3 as 3);
const c3b = baz(c, t => 3 as 3);
//Need to use `as 2` here but the error message is as expected
//'() => 2' is missing the following properties from type '["1|2 is not allowed, received", 2]' 
const c4 = baz(c, () => 2 as 2);
//Need to use `as 2` here but the error message is as expected
//'(1|2|3) => 2' is missing the following properties from type '["1|2 is not allowed, received", 2]'
const c5 = baz(c, t => 2 as 2);
//Need to use `as 1` here but the error message is as expected
//'() => 1' is missing the following properties from type '["1|2 is not allowed, received", 1]'
const c6 = baz(c, () => 1 as 1);
//Need to use `as 1` here but the error message is as expected
//'(1|2|3) => 1' is missing the following properties from type '["1|2 is not allowed, received", 1]'
const c7 = baz(c, t => 1 as 1);
```

**Comment by AnyhowStep** [comment]
Okay. So, not all classes/interfaces are different. A bunch of my own code uses classes/interfaces and functions and `ReturnType<FooT>` but it just doesn't work =/

**Comment by AnyhowStep** [comment]
So, I decided to play with `3.5.0-dev.20190523`,

I ran the above code samples, and only this one still fails,

```ts
//Innocent enough.
//Returns a T
type Foo<T> = (...args : any[]) => T;

//=== NOT using ReturnType<FooT> in Generic Parameters ==
declare function bar<
    FooT extends Foo<3|5>
>(foo: FooT): ReturnType<FooT>
//OK! `barResult` is of type `3`
const barResult = bar(
    () => 3
);
//OK! `barResult2` is of type `3`
const barResult2 = bar(
    //`t` is of type `3|5`
    //Return type is 3 
    t => 3
);

//=== Using ReturnType<FooT> in Generic Parameters ==
declare function baz<
    FooT extends Foo<3|5>,
>(
    foo: FooT & (
        ReturnType<FooT> extends 3 ?
        unknown :
        [
            "Only 3 allowed, received",
            ReturnType<FooT>
        ]
    )
): ReturnType<FooT>
//OK! `bazResult` is of type `3`
const bazResult = baz(
    () => 3
);
//NOT OK! `bazResult2` is of type `3|5`!
const bazResult2 = baz(
    //`t` is of type `3|5`
    //Return type is `3`
    //Error, ["Only 3 allowed, received", 3 | 5]
    //Typescript thinks `t` is of type `any`
    t => 3
);

//NOT OK! `bazResult3` is of type `3|5`!
const bazResult3 = baz(
    //`t` is of type `3|5`
    //Return type is `3`
    //We *force* the return type to be 3
    //Error, ["Only 3 allowed, received", 3 | 5]
    //Typescript thinks `t` is of type `any`
    (t) : 3 => (3 as 3)
);
```

I believe #30215 is what fixes most of whatever was error'ing before.

However, it would be nice if the above sample was fixed, too. I love putting error messages in parameters because it pinpoints the exact location of the problem.

**Comment by AnyhowStep** [comment]
I've been playing with this a bit more and a cumbersome workaround is,

```ts

//Innocent enough.
//Returns a T
type Foo<T> = (...args : any[]) => T;

//=== Using ReturnType<FooT> in Generic Parameters ==
declare function baz<
    FooT extends Foo<3|5>,
>(
    foo: FooT
): (
    (this: (
        ReturnType<FooT> extends 3 ?
        unknown :
        [
            "Only 3 allowed, received",
            ReturnType<FooT>
        ]
    )) => ReturnType<FooT>
)
//OK! `bazResult` is of type `3`
const bazResult = baz(
    () => 3
);

//OK! `bazResult2` is of type `3`
const bazResult2 = baz(
    t => 3
)();

//OK! `bazResult3` is of type `3`
const bazResult3 = baz(
    (t) : 3 => (3 as 3)
)();

/*
    OK! `bazResult4` is of type `5`
    
    Error as expected,
    
    The 'this' context of type 'void' is not assignable to
    method's 'this' of type '["Only 3 allowed, received", 5]'.
*/
const bazResult4 = baz(
    //Return type is `3`
    //Error, ["Only 3 allowed, received", 3 | 5]
    t => 5
)();
```

[Playground](http://www.typescriptlang.org/play/#src=%0D%0A%2F%2FInnocent%20enough.%0D%0A%2F%2FReturns%20a%20T%0D%0Atype%20Foo%3CT%3E%20%3D%20(...args%20%3A%20any%5B%5D)%20%3D%3E%20T%3B%0D%0A%0D%0A%2F%2F%3D%3D%3D%20Using%20ReturnType%3CFooT%3E%20in%20Generic%20Parameters%20%3D%3D%0D%0Adeclare%20function%20baz%3C%0D%0A%20%20%20%20FooT%20extends%20Foo%3C3%7C5%3E%2C%0D%0A%3E(%0D%0A%20%20%20%20foo%3A%20FooT%0D%0A)%3A%20(%0D%0A%20%20%20%20(this%3A%20(%0D%0A%20%20%20%20%20%20%20%20ReturnType%3CFooT%3E%20extends%203%20%3F%0D%0A%20%20%20%20%20%20%20%20unknown%20%3A%0D%0A%20%20%20%20%20%20%20%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%22Only%203%20allowed%2C%20received%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20ReturnType%3CFooT%3E%0D%0A%20%20%20%20%20%20%20%20%5D%0D%0A%20%20%20%20))%20%3D%3E%20ReturnType%3CFooT%3E%0D%0A)%0D%0A%2F%2FOK!%20%60bazResult%60%20is%20of%20type%20%603%60%0D%0Aconst%20bazResult%20%3D%20baz(%0D%0A%20%20%20%20()%20%3D%3E%203%0D%0A)%3B%0D%0A%0D%0A%2F%2FOK!%20%60bazResult2%60%20is%20of%20type%20%603%60%0D%0Aconst%20bazResult2%20%3D%20baz(%0D%0A%20%20%20%20t%20%3D%3E%203%0D%0A)()%3B%0D%0A%0D%0A%2F%2FOK!%20%60bazResult3%60%20is%20of%20type%20%603%60%0D%0Aconst%20bazResult3%20%3D%20baz(%0D%0A%20%20%20%20(t)%20%3A%203%20%3D%3E%20(3%20as%203)%0D%0A)()%3B%0D%0A%0D%0A%2F*%0D%0A%20%20%20%20OK!%20%60bazResult4%60%20is%20of%20type%20%605%60%0D%0A%20%20%20%20%0D%0A%20%20%20%20Error%20as%20expected%2C%0D%0A%20%20%20%20%0D%0A%20%20%20%20The%20'this'%20context%20of%20type%20'void'%20is%20not%20assignable%20to%0D%0A%20%20%20%20method's%20'this'%20of%20type%20'%5B%22Only%203%20allowed%2C%20received%22%2C%205%5D'.%0D%0A*%2F%0D%0Aconst%20bazResult4%20%3D%20baz(%0D%0A%20%20%20%20%2F%2FReturn%20type%20is%20%603%60%0D%0A%20%20%20%20%2F%2FError%2C%20%5B%22Only%203%20allowed%2C%20received%22%2C%203%20%7C%205%5D%0D%0A%20%20%20%20t%20%3D%3E%205%0D%0A)()%3B)

Since `ReturnType<FooT>` does not work when using it in the function parameter list, we move it to the return type annotation.

We make the return type a function that uses `ReturnType<FooT>` in its `this` parameter, that becomes an impossible to fulfill type when some condition is fulfilled.

It's cumbersome because we now have to do perform an extra function call,

`baz(t => result)()` vs `baz(t => result)`.

But the extra function call has the benefit of making the error message much shorter and easier to read.

```
The 'this' context of type 'void' is not assignable to
    method's 'this' of type *Error Type*
```

vs, potentially,

![image](https://user-images.githubusercontent.com/5655961/58364131-5561df00-7e7d-11e9-9788-7b57b79fd907.png)

Notice the length of the scroll bar on that tooltip... It's all just saying that one type is not assignable to aonther type.

**Comment by AnyhowStep** [comment]
@jack-williams
What do you think of my last two comments?

**Comment by RyanCavanaugh** [comment]
@AnyhowStep please log a concise issue if needed. Thanks!
