### ISSUE TITLE
[API Question] Union types in error output changes order of elements arbitrarily

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#29146]
![image](https://user-images.githubusercontent.com/5655961/50411913-e307a880-07d1-11e9-9d0e-1a62f1b7accd.png)

I'm writing a library and have a crude compile-time test system set up. I run the test and it compiles a bunch of snippets and compares the actual compiled output (declarations and errors) to the expected compiled output.

However, I've noticed that, every once in a while, when adding new features, the compiled output changes like in the above screenshot. The output isn't *wrong* per se. It's correct but adding a new file shouldn't change the compiled output (in my opinion).

It's just shuffling the elements of the union types in the error messages.

When the output *does* change, I just accept the change and subsequent compiles match the new output. So, I know the compile output is deterministic. It just seems like adding a new file and not modifying every other file has the possibility of changing the compile output... Of code that doesn't use the new file.

-----

1. Code A uses File A
2. I add File B, I do not modify Code A or File A
3. I compile
4. Code A's output changes

I guess my question is "Why is it doing this?"

-----

Below is how I'm compiling the snippets,

```ts
const rootNames = getAllTsFiles(inputRoot);
const program = ts.createProgram({
    rootNames,
    options : compilerOptions,
});
const emitResult = program.emit(
    /*snip*/
);
const allDiagnostics = ts
    .getPreEmitDiagnostics(program)
    .concat(emitResult.diagnostics);
```

**Comment by weswigham** [comment]
The order or types in members is determined by those types IDs. Type IDs are assigned on a first-checked basis. So adding a file can cause they type to be checked sooner and thus it's order in a union change.

**Comment by AnyhowStep** [comment]
Ah. That makes sense to me. Thanks for the response!

Merry Christmas!

**Comment by Blasz** [comment]
Relates to #17944

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/32224
