### ISSUE TITLE
New Website Logo: Heat Rivals - Android Game

### ISSUE THREAD

**Issue by NickTsitlakidis** [Microsoft/TypeScript#2914]
Please fill the following out:

- Name: Heat Rivals
- Homepage url: https://play.google.com/store/apps/details?id=com.perfectedz.heatrivals
- Brand Guidelines/Licensing: Nothing specific
- Logo: http://heatrivals.com/images/about-logo.png

Heat Rivals is built using Typescript, Angular.js and the Ionic Framework. It's a typical card game and it's targeted in Android devices.

**Comment by jonathandturner** [comment]
Added.
