### ISSUE TITLE
ts.TypeLiteralNode gives incomplete set of members

### ISSUE THREAD

**Issue by abhijitparkhi1983** [microsoft/TypeScript#29142]
**TypeScript Version**: 3.2.2

**Search Terms**: 
ts.TypeLiteralNode
members
... more ...

**Description**:

We are trying to use typescript compiler for getting the variable's type and for the purpose we utilize following code: 

```
getApparentType(node : ts.Node) : {type : ts.Type, typeNode : ts.TypeNode} {
        let type : ts.Type = this.checker.getTypeAtLocation(node);
        let typeNode = this.checker.typeToTypeNode(type);

        if(ts.isTypeLiteralNode(typeNode))
        {
            var memberCount = typeNode.members.length;
            var name : string;
            typeNode.members.forEach(member => {
                name +=  member.name;
                name += " , ";
            });
        }
        return {type, typeNode}
    }
```

The above code, especially the code  `typeNode.members.length` returns the required members count as expected in most cases. 

There is a specific case where a local variable is assigned to the value returned from a function. This function internally creates a object (**emulsion** in this case) and adds about 27 properties and 20 functions on this object and finally returns this anonymous object. 
So essentially, the type of the local variable (**emulsionTest** in this case) to which the return type of the function (object created ) is assigned should be a object type with 47 members in it. 

But the `typeNode.members.length` returns only 9 as count which implies that there are only 9 members associated to this locally created object which is not right. 
Additionally, the first 7 elements of members match the first 7 properties/functions attached to the anonymous object getting returned from the function ( till **notifications** in this case); the 8th element of the members array has a strange name with following text **... 39 more..** and the 10th element shows the last property/function attached to the anonymous object ( **isIE** in this case) getting returned from the function.

The sample file for the above scenario is attached with this message (**testFile_TypeLiteralExample.txt**)
Also a screenshot of the  **... 39 more..**  behavior is attached while in debug mode using VS Code.

**Expected behavior**: 
All the 47 members should be displayed; `typeNode.members.length` should return the actual count (which in this case should be 47) and all the 47 members should be itterable .

![39_more](https://user-images.githubusercontent.com/7124615/50401896-205f3c80-07b8-11e9-9745-f3495675eef5.jpg)

[testFile_TypeLiteralExample.txt](https://github.com/Microsoft/TypeScript/files/2707448/testFile_TypeLiteralExample.txt)

**Comment by weswigham** [comment]
You wanna pass the `NoTruncation` flag into the type builder.
