### ISSUE TITLE
Tagged Templates: TemplateStringsArray vs. string

### ISSUE THREAD

**Issue by isdn** [microsoft/TypeScript#29149]
tsc v. 3.2.2

**Code**

```ts
'use strict';

const a = ['a', 'b', 'c'].join``;

console.log(a);

```

**Expected behavior:**

It should be compiled correctly.

**Actual behavior:**

```
$> tsc test.ts
test.ts:3:31 - error TS2345: Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'string'.

3 const a = ['a', 'b', 'c'].join``;
                                ~~


Found 1 error.
```

I know that a "normal" tagged template  "desugars" into an array, but `` has no elements in it, and it should be an empty string, I suppose.

**Comment by weswigham** [comment]
While a neat trick, this isn't actually typesafe - this only works because the `.toString` of a single-element array is the `.toString` of the first element.

**Comment by isdn** [comment]
> While a neat trick, this isn't actually typesafe - this only works because the `.toString` of a single-element array is the `.toString` of the first element.

As far as I understand, it works in the following way:
```js
fn`a ${b} c ${d}`
```
is transformed to
```js
fn(['a ', ' c '], b, d)
```
In our case it will be just `['']`, i.e. that is a single element array with an empty string in it. It is always an empty string there.

**Comment by weswigham** [comment]
Ya, as I said - it only works because the string representation of an array containing the empty string and the empty string itself are the same. It is not generally acceptable to pass an array (or template string array, as here) where a string is expected.
