### ISSUE TITLE
Autocomplete: Exports from module are not available after augmentation

### ISSUE THREAD

**Issue by kyranet** [Microsoft/TypeScript#29153]
**TypeScript Version:**  3.2.2

**Search Terms:** autocompletion, augmentation, autoimport

**Code**

Consider a module called `a` (from `node_modules`) which exports a class being `Foo`. When writing `Foo`, TypeScript effectively auto-completes and suggests to auto-import. However, if I do an augmentation (with the following code), it'll stop from showing in the autocompletion.

```typescript
declare module 'a' {
	export interface Foo {
		prop: string;
	}
}
```

The class Foo will indeed have Foo.prototype.prop, as far as Intellisense and TypeScript tell me, but if I type `Foo` again, it doesn't show unless I comment out the augmentation.

My comment from https://github.com/Microsoft/vscode/issues/62339#issuecomment-442911051 leaves more details.

**Expected behavior:** Auto-completion and auto-import would work effectively, suggesting the class from the module.

**Actual behavior:** When writing Foo, it's not shown in auto-complete nor auto-import.

**Playground Link:** Cannot reproduce in playground due to the lack of IntelliSense.

**Related Issues:** None.

**Comment by Kovensky** [comment]
Make sure you add at least one top-level import or export; right now your code example is not an augmentation but a completely new declaration.

**Comment by kyranet** [comment]
> Make sure you add at least one top-level import or export (outside the declare module); right now your code example is not an augmentation but a completely new declaration.

What do you mean? I'm sorry, it's my first time using augmentations and not everything was very clear to me. However, IntelliSense detects the module from both locations (from node_modules and from my augmentation).

**Comment by kyranet** [comment]
`skipLibCheck` was not specified in my `tsconfig.json`, I have set it to `false` and still does nothing.

In `.d.ts`, I can't use `declare` in `module 'foo' {}` because it's already ambient. In the comment I linked in this PR description, I also linked this [chunk of code](https://github.com/dirigeants/klasa/blob/8496d45db52a01727e5d3fd8b0b81450df77efbf/typings/index.d.ts#L1000-L1257), and due to this, I don't get autocomplete from the module I'm trying to augment. However, IntelliSense recognizes all of them:

![image](https://user-images.githubusercontent.com/24852502/50478945-321d2b80-09d4-11e9-93b3-22b554b949c4.png)

(`Message` is a class defined in `discord.js`, augmented in `klasa` (as shown in the link above), and augmented again in my project, they're all shown when I do Ctrl + Click in VSC).

As for the ES module, this is a Node.js project, I'm compiling the code to CJS but all imports are done with ESM syntax, all augmentations are written after a `export default`, using the following [code pattern](https://gist.github.com/kyranet/678f2ba5f5afe24ff5df69cbad57cc81).

**Comment by Kovensky** [comment]
I see what's the problem, then; you're trying to _nest_ `module` declarations.

For starters, there is no need for you to wrap your entire module in `declare module`. Just write it inline. As soon as you do that, your declaration file will no longer be a global script but will become a module which can augment other modules.

Note that you will have to declare at least a peerDependency on the `discord.js` types. Augmentations cause a build error when the module they're trying to augment doesn't already have a base declaration.

**Comment by kyranet** [comment]
I had them nested so I didn't have to import everything from `klasa` to `discord.js`, but after doing the change, it finally works! Autocompletion for anything inside `discord.js` works now, but anything from `klasa` is still not suggesting anything. All `declare module 'klasa' {}` is written in the same pattern as the ones from `declare module 'discord.js' {}` (like in the last link from my previous message).

For context, I edited klasa's declaration file to 
![image](https://user-images.githubusercontent.com/24852502/50479961-7e1e9f00-09d9-11e9-8164-3a598add1e4f.png)

Also, `discord.js` is already a peerDependency of `klasa` [here](https://github.com/dirigeants/klasa/blob/82819b611d98fbb46f2788d2269f3ef985447529/package.json#L25-L27)

**Comment by kyranet** [comment]
**Update**: using a `.d.ts` file for all my project's augmentations to both modules indeed solved my issues with the completion lists not suggesting `klasa`, however, I do not understand why do the autocompletion lists work for the `discord.js` ones if they all use the same pattern.
