### ISSUE TITLE
Typescript API type analysis not working on Javascript code

### ISSUE THREAD

**Issue by brentshermana** [microsoft/TypeScript#29157]
I'm applying the Typescript API to get the type of variables in JS code. Although in many cases Typescript is not guaranteed to work well on plain JS, this particular case is trivial. I get the same results whether the 'else' clause of example.js is commented out or not.

**TypeScript Version:**  3.3.0-dev.20181222

**More Search Terms:** -> "TypeFlags not correct", "TypeFlags.object"

To set up the project...
* make an empty dir
* cd into it
* `npm install typescript`
* *copy the two files below*
* `tsc main.ts`
* `node main.js`

**Code**
```javascript
// example.js
let notObject= {someKey: "someValue"};

if (rand()) {
    notObject = "not object";
}
else {
   notObject = "also not object";
}

console.log(notObject) // <- just an arbitrary function call
```

```ts
// main.ts
import {
    Type,
    TypeFlags,
    ModuleKind,
    ScriptTarget,
    createProgram,
    SyntaxKind,
    CallExpression,
    forEachChild,
    Node
} from "typescript";

let createProgramOptions = {
    target: ScriptTarget.ES2018,
    module: ModuleKind.CommonJS,
    allowJs: true,
};

function isObjectType(t: Type): boolean {
    return (t.flags & TypeFlags.Object) != 0;
}

let program = createProgram(["example.js"], createProgramOptions);

let checker = program.getTypeChecker();

function visitAst(root: Node, f: (descendent: Node) => any) {
    let stack = [root];
    while (stack.length > 0) {
        let n = stack.pop()!;
        f(n);
        forEachChild(n, (child: Node) => {stack.push(child)})
    }
}

function checkCallExpressionArgs(node: Node) {
    if (node.kind == SyntaxKind.CallExpression) {
        let call = <CallExpression> node;
        for (let arg of call.arguments) {
            let type = checker.getTypeAtLocation(arg);
            console.log(isObjectType(type));
        }
    }
}

// iterate through arguments of (top level) call sites,
// printing out whether typescript thinks each is an object
for (let file of program.getSourceFiles()) {
    if (!file.isDeclarationFile) {
        visitAst(file, checkCallExpressionArgs);
    }
}
```

**Expected behavior:**
prints `false`

**Actual behavior:**
prints `true`

**Playground Link:**
^^^ I could be wrong but I don't think this applies

**Comment by ajafff** [comment]
If a variable declaration has an initializer, TypeScript assume that variable to be of its initializer's type.
The following assignments would be flagged as errors if you were in a TypeScript file or had a `// @ts-check` comment at the start of the file. That means the type of the variable doesn't change on assignment and hence the API always returns the "declared" type.

If you want control flow analysis to change the type of the variable on assignment, you should first declare your variable and then assign the initial value:

```js
// example.js
let notObject;
notObject = {someKey: "someValue"}

if (rand()) {
    notObject = "not object";
}
else {
   notObject = "also not object";
}

console.log(notObject) // <- just an arbitrary function call
```

**Comment by weswigham** [comment]
@ajaff has it.
