### ISSUE TITLE
Distinguish interfaces based on mutual exclusivity of their property type

### ISSUE THREAD

**Issue by NeekSandhu** [Microsoft/TypeScript#29158]
## Suggestion

If two (or more) interfaces have a property with the same name, but in none of those said interfaces does the property share same type. TS should be able to differentiate between those interface(s) when inside conditional blocks where the said property being compared against its possible types is part of the condition

## Use Cases

It would eliminate having to use type casting and/or other ugly methods.

## Examples

Described in [Playground](https://www.typescriptlang.org/play/#src=interface%20INetworkError%20%7B%0D%0A%20%20%20%20uri%3A%20string%0D%0A%20%20%20%20httpCode%3A%20number%0D%0A%7D%0D%0A%0D%0Ainterface%20IFileSystemError%20%7B%0D%0A%20%20%20%20path%3A%20string%0D%0A%20%20%20%20user%3A%20number%0D%0A%7D%0D%0A%0D%0Aenum%20ErrorType%20%7B%0D%0A%20%20%20%20NetworkError%2C%0D%0A%20%20%20%20FileSystemError%2C%0D%0A%7D%0D%0A%0D%0A%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0D%0A%0D%0Ainterface%20INetworkErrorDesc%20%7B%0D%0A%20%20%20%20errorType%3A%20ErrorType.NetworkError%2C%0D%0A%20%20%20%20error%3A%20INetworkError%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20IFileSystemErrorDesc%20%7B%0D%0A%20%20%20%20errorType%3A%20ErrorType.FileSystemError%2C%0D%0A%20%20%20%20error%3A%20IFileSystemError%2C%0D%0A%7D%0D%0A%0D%0Atype%20IErrorDesc%20%3D%20INetworkErrorDesc%20%7C%20IFileSystemErrorDesc%0D%0A%0D%0A%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0D%0A%0D%0Afunction%20logError(%7B%20errorType%2C%20error%20%7D%3A%20IErrorDesc)%3A%20any%20%7B%0D%0A%20%20%20%20if%20(errorType%20%3D%3D%3D%20ErrorType.NetworkError)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20Here%20TSC%20should%20know%20that%20%60errorType%60%20is%20mutually%20exclusive%20among%20two%20possible%20outcomes%0D%0A%20%20%20%20%20%20%20%20const%20httpCode%20%3D%20error.httpCode%20%2F%2F%20%3C---%20Error%3F%3F%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20I%20know%20I%20can%20do%20%60(error%20as%20INetworkError).httpCode%60%20but%20I%20think%20it%20shouldn't%20have%20to%20be%20that%20way%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20I%20also%20know%20I%20can%20do%20%60if('httpCode'%20in%20error)%20%7B%20%7D%60%2C%20but%20again%20not%20very%20neat%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20You%20might%20say%20checks%20are%20recommended%20anyway%20but%20believe%20me%2C%20I%20trust%20the%20source%20I'll%20be%20getting%20this%20data%20from%20so%20double%20checking%20is%20unnecessary%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
The analyzer simply doesn't track that information.  It's no different than if you assign the result of a type check to a variable; that variable *won't* act as a type guard later.
