### ISSUE TITLE
experimentalDecorators compiler option is not respected by transpileModule

### ISSUE THREAD

**Issue by jraoult** [Microsoft/TypeScript#29152]
**TypeScript Version:**  3.2.2

**Search Terms:**
decorator, experimentalDecorators, transpileModule

**Expected behavior:**
I was expecting the `transpileModule` API to not generate the `__decorate` helpers and not wrap the property when `experimentalDecorators` is set to `false`.

**Actual behavior:**
`transpileModule` seems to ignore `experimentalDecorators` option and behaves as if it was set to `true`.

**Playground Link:** Please see the following runkit: https://runkit.com/5c228001c8da760013d17b4b/5c22800ac8da760013d17b51

**Comment by weswigham** [comment]
`experimentalDecorators` doesn't affect emit - it just squelches the warning we emit on decorator usage.

**Comment by jraoult** [comment]
@weswigham I see, what would be the way to turn transformation off for decorators so that I can leave it to the next stage (babel)?

**Comment by weswigham** [comment]
I don't think it can be disabled - I think it's part of the TS transform which is unconditional. But if you're running your code thru Babel, you should probably just be able to use the babel-typescript plugin with your input TS, and only run the compiler with `noEmit` on for type errors (unless you use const enums... Then you may be outta luck).
