### ISSUE TITLE
Array Type Inference 

### ISSUE THREAD

**Issue by cinderblock** [Microsoft/TypeScript#29163]
**TypeScript Version:**  3.3.0-dev.20181222

**Search Terms:**
- array
- type
- inference
- index

**Code**
[Playground Link](http://www.typescriptlang.org/play/#src=const%20typed%20%3D%20%5B'a'%2C%201%5D%20as%20%5Bstring%2C%20number%5D%3B%0D%0Atyped%5B0%5D.length%3B%20%2F%2F%20Works%0D%0Atyped%5B1%5D.toPrecision()%3B%20%2F%2F%20Works%0D%0Atyped%5B2%5D%3B%20%2F%2F%20Errors%20as%20expected%0D%0A%0D%0Aconst%20array%20%3D%20%5B'a'%2C%201%5D%3B%0D%0Aarray%5B0%5D.length%3B%20%2F%2F%20Error%0D%0Aarray%5B1%5D.toPrecision%3B%20%2F%2F%20Error%0D%0Aarray%5B2%5D%3B%20%2F%2F%20Should%20error)
```ts
const typed = ['a', 1] as [string, number];
typed[0].length; // Works
typed[1].toPrecision; // Works
typed[2]; // Errors as expected

const array = ['a', 1];
array[0].length; // Error
array[1].toPrecision; // Error
array[2]; // Should error
```

**Expected behavior:**

TypeScript infers type of `array` as `[string, number]`.

**Actual behavior:**

TypeScript infers type of `array` as `(string | number)[]`.

**Related Issues:** 
#25516

**Comment by fatcerberus** [comment]
Known issue - array literals are inferred as a union of their member types.  I don't think it's considered a bug.

**Comment by cinderblock** [comment]
I see. I looked through the FAQ pages of other bugs and did not find exactly equivalent.

I'll let them close this if this is desired behavior.

I'm curious what reasons there are for this not being the desired behavior!

**Comment by fatcerberus** [comment]
It's been discussed on the TypeScript gitter several times in the past, and I was pretty sure there was a GitHub issue that described the design challenges at length, but I can't find it now...

See also #27179, #16656.
