### ISSUE TITLE
Program created with createSemanticDiagnosticsBuilderProgram writes files to disk.

### ISSUE THREAD

**Issue by 0xorial** [microsoft/TypeScript#29176]
**Search Terms:**
incremental program watcher createSemanticDiagnosticsBuilderProgram 

I tried example from [here](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher) and the version with createSemanticDiagnosticsBuilderProgram still writes files to disk. Also it is much slower than version with createEmitAndSemanticDiagnosticsBuilderProgram. 
(project ~140 files, size ~1MB. full compile ~8s, 'semantic' incremental compile ~3s, 'emitAndSemantic' incremental compile <0.5s)

**Expected behavior:**
No files written to disk. Performance is approximately same between createSemanticDiagnosticsBuilderProgram and createEmitAndSemanticDiagnosticsBuilderProgram

**Actual behavior:**
Files are written to disk and performance is much worse with createSemanticDiagnosticsBuilderProgram .

**Related**
https://github.com/tildeio/broccoli-typescript-compiler/issues/57
https://github.com/Microsoft/TypeScript/pull/20234

**Comment by sheetalkamat** [comment]
The default `afterCreateProgram` for the `watchHost` is `emitFilesAndReportErrorUsingBuilder` and that's the reason you are seeing this because the example  calls on that (`origPostProgramCreate!(program);`) You would need to instead Report errors from program your self you do not want to emit the program. Note that SemanticDiagnosticsBuilder is only caching semantic diagnostics and does not handle emit and just redirects it to the original program.
```ts
  // Between `createEmitAndSemanticDiagnosticsBuilderProgram` and
  // `createSemanticDiagnosticsBuilderProgram`, the only difference is emit.
  // For pure type-checking scenarios, or when another tool/process handles emit,
  // using `createSemanticDiagnosticsBuilderProgram` may be more desirable.
```

**Comment by 0xorial** [comment]
Unfortunately, it seems that there is a performance-related issue linked to emitting. I tried to copy emitFilesAndReportErrors function from watch.ts and simply remove writing and I immediately had performance drop. 
I noticed that there is some performance tracing inside the code. Is there some documentation regarding which tools I can use to benefit from that tracing?

**Comment by weswigham** [comment]
The `extendedDiagnostics` flag enables collection of the data.

**Comment by 0xorial** [comment]
@sheetalkamat, I have spent some time debugging the performance-related part of the issue and found a difference in [this method](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/builder.ts#L869). For SemanticDiagnosticsBuilderProgram this method goes into emit method from program.ts, which ends up checking ALL files of the project, instead of only checking the modified ones.

Is it necessary to have different behavior in this method between EmitAndSemanticDiagnosticsBuilderProgram and SemanticDiagnosticsBuilderProgram  ?

**Comment by sheetalkamat** [comment]
@0xorial This is on purpose. Please see https://github.com/microsoft/TypeScript/blob/master/lib/typescript.d.ts#L4376 to see how the emit works. Emit is optimized only for `EmitAndSemanticDiagnosticsBuilderProgram` which is used to emit and get optimized semantic diagnostics. If you don't want to emit or know which files to emit (like many tools already do eg. webpack loaders) you don't need to have emit logic in there and hence `SemanticDiagnosticsBuilderProgram` is provided to just optimize the diagnositcs

**Comment by 0xorial** [comment]
Sorry, I still do not understand - what is the purpose of _not_ giving a performance optimization to SemanticDiagnosticsBuilderProgram ? It would work much faster this way, right?

BTW, the reason I dig into this so persistently is because I [was working](https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/198) on a webpack integration and I believe this is the fastest integration there is, with performance similar to running `tsc --watch`. Unfortunately, to achieve that I had to hack around a some of compiler internals: use EmitAndSemanticDiagnosticsBuilderProgram and make a fake writeFile function among others. I would really love to see a public API that would allow integrations with same performance.

**Comment by sheetalkamat** [comment]
@0xorial  I am not sure what you are asking. If you need performant emit then use `EmitAndSemanticDiagnosticsBuilder`. Emit is only difference between those two builders and as I mentioned it was intentionally designed that way. Otherwise we could have had just one builder. We are giving control to api users with these two builders to either use builder to determine what files to emit and cache semantic diagnostics or just cache semantic diagnostics when they already know which files to emit by themselves.
