### ISSUE TITLE
Imports in index.ts file are not getting correctly resolved.

### ISSUE THREAD

**Issue by sanketdhoble** [microsoft/TypeScript#29171]
"typescript": "3.2.2"

Imports in index.ts file are not getting correctly imported.
Inside engine folder, I have files as

- engine
   - index.ts
   - engine.ts
   - test.ts 

Inside index.ts, 
I have

> export { Engine } from './engine';
> export { Test } from './test';

When I try to import, `Engine` class in another file using
import {Engine} from '../engine';
engine is not defined

I get it correct if I write this way.
`import {Engine} from '../engine/engine';`
This was working fine previously, but after resent ts version upgrade it is giving this error.

**Comment by sanketdhoble** [comment]
@ajafff It is already set

> "compilerOptions": {
>     "allowJs": true,
>     "target": "es2017",
>     "module": "commonjs",
>     "moduleResolution": "node",
>     "isolatedModules": false,
>     "jsx": "react",
>     "experimentalDecorators": true,
>     "emitDecoratorMetadata": true,
>     //"declaration": false,
>     "noImplicitAny": false,
>     "removeComments": false,
>     "noLib": false,
>     "preserveConstEnums": true,
>     "skipLibCheck": true,
>     "skipDefaultLibCheck": true,
>     "suppressImplicitAnyIndexErrors": true,
>     "sourceMap": true,
>     "outDir": "release/",
>     "rootDir": "./",
>     "watch": true
>   },

**Comment by sanketdhoble** [comment]
@sheetalkamat It gives tons of logs in vscode terminal. Not sure how to find the useful one.

**Comment by sheetalkamat** [comment]
The full log would be more informative. It would tell you why ../engine was resolved to the file you are seeing.

**Comment by fatcerberus** [comment]
Presuming that your folder structure looks something like this:
```
engine
    \index.ts
    \engine.ts
    \test.ts
other-file.ts
```
Then shouldn't `other-file.ts` be doing:
```ts
import { Engine } from './engine';
```

`..` means "the parent directory of the one that contains this module".

**Comment by sanketdhoble** [comment]
engine
     \index.ts
     \engine.ts
     \test.ts
routes
    \tracker.ts

Inside tracker , I am doing,
import { Engine as BotEngine } from '../engine';
Which is shown correct path in vscode as well.

**Comment by fatcerberus** [comment]
Hmm...  it seems a bit questionable from a structural point of view to import from the `index.ts` at your own level by way of the parent directory, but yeah, I don’t see any reason that shouldn’t work.

**Comment by sanketdhoble** [comment]
- engine
        -  \index.ts
        -  \engine.ts
        -  \test.ts
     -  routes
        -  \tracker.ts
  - server.ts (base level)

In server.ts, I changed, 
`import {Engine} from './engine/engine';`
to
`import {Engine} from './engine';`
And it started working.

**Comment by Kalagon** [comment]
I have also run into this problem when incorporating unit testing into our project.
I'll just use the given example to expand a bit on it.

Usually everything outside the  'engine' folder uses 
`import {Engine} from './engine'`

Since the test files live inside an 'engine/test' folder in our project, we used 
`import {Engine} from '../engine'`
instead of
`import {Engine} from '../../engine'`

When the tests are run, the first import of _Engine_ is done via
`import {Engine} from '../engine'`
in the test file.

This causes the
`export * from './engine'`
inside _index.ts_ to fail.

When running the project normally, the calling order is reversed as all external files import via _index.ts_ so everything works as expected.
It can be fixed by importing through _index.ts_ in the tests, but isn't this something TypeScript should solve on a compiler level?
I don't think importing the way we originally did is a counterintuitive approach and it leads to quite hard to debug issues.

To help understanding, this is the directory structure as a whole:
```
 - engine
    -  \index.ts
    -  \engine.ts
    -  \test
        - \test.spec.ts
 -  server.ts
```

**Comment by Manish3323** [comment]
Any recommendations available for writing exports in index.ts and using the exported modules internnally ? ..
this issue is really frustrating to debug : (..

**Comment by coderbuzz** [comment]
You have to add a slash in the folder (module) name, this will treat index.ts as the folder index.

`import {Engine} from '../engine/';`

**Comment by cbdeveloper** [comment]
I'm having a similar issue when using `baseUrl: "src"`

Obs: the error is shown when the file is open, but the code runs smoothly. The import actually works. Maybe VSCode TS intellisense is the one to blame here.

Project structure:

```
constants
  foo.ts
  bar.ts
  index.ts // Re-exports from foo and bar
  xxx.ts // Re-exports from foo and bar (this was a test(

other-folder
  component.tsx  // Trying to import from 'constants'
```

Test results from `component.tsx`

```
import { FOO } from 'constants';  // ERROR
import { FOO } from 'constants/xxx';  // WORKS
import { FOO } from '../constants';  // WORKS
import { FOO } from 'constants/foo';  // WORKS
```

This is the error:

![image](https://user-images.githubusercontent.com/43407798/163111361-cb10e589-fb2e-4519-889c-57c8e3a2e55e.png)

This is my `tsconfig.json` file:

TS version: `"typescript": "^4.5.5"`

```
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": "src",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["dom", "dom.iterable", "esnext"],
    "noEmit": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
  },
  "exclude": [
    "node_modules",
  ]
}
```

Obs: This is happening inside my `packages/admin` project. This is a monorepo using Yarn workspaces. Not sure if this is related or not. TypeScript is installed at the root of the workspace (but I think this error is coming from VSCode TS itself).

**Comment by cmdruid** [comment]
This problem just hit me as well. Code works fine, tests all pass, literally no issues with import / export within the project. But when I build / publish to npm, and import to another project from npm package, typescript can't figure out how index.ts works.

**Comment by coderbuzz** [comment]
> > You have to add a slash in the folder (module) name, this will treat index.ts as the folder index.
> > `import {Engine} from '../engine/';`
> 
> @coderbuzz first of all, thank you. You've saved my sanity.
> 
> Second of all, are there docs/is this common knowledge/where is this learned if you had not been here? I certainly didn't see it in module resolution docs.

There is no docs, I resolved it by trying any possibilities  ;)

**Comment by mukundhan94** [comment]
@cbdeveloper did you find any resolution for this ? apart from importing from current directory

**Comment by abhijit-chikane** [comment]
![image](https://github.com/microsoft/TypeScript/assets/50770619/4d907d92-4cc4-4711-bc6c-e6a606d66fe2)

For me putting the import in proper order fixes this issue.
(import those which are not depend on other's first and then dependent's)
