### ISSUE TITLE
Web worker onmessage signature is weird.

### ISSUE THREAD

**Issue by cyyyu** [microsoft/TypeScript#29185]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

Web worker onmessage signature doesn't match. Check out the code or the playground link below.

**Code**

```ts
const worker = new Worker('./somewhere.js')

function cb(_this: Worker, ev: MessageEvent) { }

const cb2 = function (_this, cv) { }

const cb3 = function (_this: Worker, cv: MessageEvent) { }

const cb4 = function (this: Worker, cv: MessageEvent) { }

worker.onmessage = cb // error
worker.onmessage = cb2 // error
worker.onmessage = cb3 // error
worker.onmessage = cb4 // This works but I can't bind cb4 to any other context

const whateverObj = {}
worker.onmessage = cb4.bind(whateverObj) // this won't work because 'this' inside cb4 refers to its first param

```

**Expected behavior:**

All the errors above don't make any sense to me. Can anyone explain why I have to define my callback function with the first param to be a 'this' keyword. 

**Actual behavior:**

**Playground Link:** 

https://www.typescriptlang.org/play/index.html#src=%0D%0Aconst%20worker%20%3D%20new%20Worker('.%2Fsomewhere.js')%0D%0A%0D%0Afunction%20cb(_this%3A%20Worker%2C%20ev%3A%20MessageEvent)%20%7B%20%7D%0D%0A%0D%0Aconst%20cb2%20%3D%20function%20(_this%2C%20cv)%20%7B%20%7D%0D%0A%0D%0Aconst%20cb3%20%3D%20function%20(_this%3A%20Worker%2C%20cv%3A%20MessageEvent)%20%7B%20%7D%0D%0A%0D%0Aconst%20cb4%20%3D%20function%20(this%3A%20Worker%2C%20cv%3A%20MessageEvent)%20%7B%20%7D%0D%0A%0D%0Aworker.onmessage%20%3D%20cb%20%2F%2F%20error%0D%0Aworker.onmessage%20%3D%20cb2%20%2F%2F%20error%0D%0Aworker.onmessage%20%3D%20cb3%20%2F%2F%20error%0D%0Aworker.onmessage%20%3D%20cb4%20%2F%2F%20This%20works%20but%20I%20can't%20bind%20cb4%20to%20any%20other%20context%0D%0A%0D%0Aconst%20whateverObj%20%3D%20%7B%7D%0D%0Aworker.onmessage%20%3D%20cb4.bind(whateverObj)%20%2F%2F%20this%20won't%20work%20because%20'this'%20inside%20cb4%20refers%20to%20its%20first%20param%0D%0A

**Related Issues:**

**Comment by weswigham** [comment]
A `this` parameter defines the type of `this` within the body of the function - it's not a _real_ parameter - it's a typesystem hint.
