### ISSUE TITLE
Infer return type when returning result of overloaded function.

### ISSUE THREAD

**Issue by martinheidegger** [microsoft/TypeScript#29182]
## Search Terms

overloading, result, return, inference, automatic

## Suggestion

The return type of an overloaded function is clear in its usage. Any method passing the return type should have its return type inferred.

## Use Cases

I would like to specify my API by optionally giving a callback and it returns void or if the callback is missing should create and return a Promise:

```typescript
function init (): Promise<void>
function init (cb: (err: Error) => void): void
function init (cb?: (err: Error) => void): any {
  if (cb) {
    setTimeout(cb, 10)
    return
  }
  return new Promise((resolve, reject) => {
    init((err: Error) => err ? reject(err) : resolve())
  })
}
```

Now if I want to use this examplary init function in an logAndInit function, I need to specify all overloads of types:

```typescript
function logAndInit (): Promise<void>
function logAndInit (cb: (err: Error) => void): void
function logAndInit (cb?: (err: Error) => void): any {
   console.log('Initing')
   return init(cb)
}
```

## Examples

My thinking is that it should be possible to infer the return type:

```typescript
function logAndInit(cb?: (err: Error) => void) {
   console.log('Initing')
   return init(cb)
}

const a = logAndInit()
a.then() // should validate as a's type can be inferred as `Promise`

const b = logAndInit(() => {})
b // should be infered as void, because the callback is passed to the init
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
See also #28021.  Adding overloads completely breaks return type inference right now.
