### ISSUE TITLE
Lack of type inference in the TS2322 error messages

### ISSUE THREAD

**Issue by michalczaplinski** [Microsoft/TypeScript#29184]
**TypeScript Version:**  3.3.0-dev.20181222

**Search Terms:**
- type inference
- is not assignable to type

**Code**

The compiler should be able to infer the type of the value to show in the error message.

```ts
const x: number = 123

const y: string = 123   // The error is: Type '123' is not assignable to type 'string'.
const z: string = x     // The error is: Type 'number' is not assignable to type 'string'.
```

**Expected behavior:**
The error message should be 
```Type 'number' is not assignable to type 'string'```

**Actual behavior:**
```Type '123' is not assignable to type 'string'```

[playground link](http://www.typescriptlang.org/play/#src=const%20x%3A%20number%20%3D%20123%0D%0A%0D%0Aconst%20y%3A%20string%20%3D%20123%0D%0Aconst%20z%3A%20string%20%3D%20x%0D%0A)

**Comment by fatcerberus** [comment]
This is not due to lack of type inference - rather, it's using a literal type for the initializer (since it's a primitive literal, the type doesn't need to be any wider than the actual value of the literal).  It's the same as if you did:

```ts
const x: 123 = 123;
const y: string = x;  // Type '123' is not assignable to type 'string'
```

**Comment by fatcerberus** [comment]
As a matter of fact, literals *have* to have literal type otherwise you couldn't assign them to a literal-typed variable!

**Comment by michalczaplinski** [comment]
@fatcerberus You're right! 😅 
Thanks for the explanation and sorry for the noise!
