### ISSUE TITLE
Missed imports when transpiling in IE11 (but not in Chrome/Edge/FF)

### ISSUE THREAD

**Issue by alexi2014** [Microsoft/TypeScript#29193]
**TypeScript Version:**  3.2.2
**Browser**: IE11

**Search Terms:**

**Code**

```ts
// Source
import * as theModule from 'someModule';
let myObj = {
    handler: () => {
        let f = function(val) {
            return theModule.someFunction();
        }
        f();
    }
};    

// Output in IE11 begins with (missed dependency, incorrect):
System.register([], function (exports_1, context_1) {
// Output in Chrome/Edge/FF begins with (dependency is present, correct):
System.register(["someModule"], function (exports_1, context_1) {
```

**Expected behavior:**
Source code is transpiled in run-time in a browser. It imports 'someModule' module, and uses a function from it (theModule.someFunction()), so the transpiled code for the System module type should reference 'someModule' in the System.register call, like here:
```ts
System.register(["someModule"], ...
```
**Actual behavior:**
This is how it works in Chrome/Edge/FF browsers, but not in IE11. In IE11 the module reference is missed, like here:
```ts
System.register([], ...
```

**Repro sample:** 
Clone the following repo:
[https://github.com/alexi2014/TS-IE-Missed-Import](https://github.com/alexi2014/TS-IE-Missed-Import)
> npm install
> npm run start

The page will be opened in the default browser. The top text area contains source code, and the bottom one contains transpiled code.
Depending on the browser where you open the page (Chrome/Edge/FF vs IE11), the transpiled result will be different.

**Related Issues:**

**Comment by alexi2014** [comment]
This can also be seen in the [playground](http://www.typescriptlang.org/play/index.html#src=import%20*%20as%20theModule%20from%20'someModule'%3B%0D%0A%0D%0Alet%20myObj%20%3D%20%7B%0D%0A%20%20%20%20handler%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20f%20%3D%20function(val)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20theModule.someFunction()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20f()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%3B%20%20%20%20%0D%0A%20%20%20%20)

**Comment by weswigham** [comment]
This is _probably_ indicative of an issue in our internal `Map` polyfill.

**Comment by weswigham** [comment]
Probably related: #26090
