### ISSUE TITLE
Missing Parcel on website typescriptlang.org/samples/

### ISSUE THREAD

**Issue by Ivanca** [microsoft/TypeScript#29195]
## Search Terms

parcel

## Suggestion

By far the easiest way to get started with a TypeScript project (for the browser) is parcel (https://parceljs.org/) and its not mentioned on the TypeScript main website.

**Comment by orta** [comment]
I'm going to close this for now, I think there will be a better spot to showcase tools like parcel in the new site and at that point we can figure out how to decide what goes in there ( I use parcel, it's great! )
