### ISSUE TITLE
Publishing web project fails when custom output folder is used

### ISSUE THREAD

**Issue by oliverw** [microsoft/TypeScript#292]
A web project that includes typescript and makes use of the "Redirect Javascript output to folder" option can currently not be published (local file system) because Microsoft.TypeScript.targets does not honor TypeScriptOutDir when populating FilesForPackagingFromProject and/or other MSBuild variables.

This is a small snippet extracted from my .csproj file:

``` xml
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptModuleKind>amd</TypeScriptModuleKind>
    <TypeScriptOutDir>$(ProjectDir)Scripts\ts</TypeScriptOutDir>
  </PropertyGroup>
```

The offending option is TypeScriptOutDir. If I remove it, publishing works as expected.

**Comment by mcintyre321** [comment]
I think this is still broken - I've tried updating to Update 4 with no luck, and it happens on Azure Websites/Kudu

Inside Host.csproj:

     <TypeScriptOutDir>.\obj\jsoutput</TypeScriptOutDir>

`Copying file .\obj\jsoutput\Host.js to obj\Debug\Package\PackageTmp\.\obj\jsoutput\Host.js failed. Could not find a part of the path '.\obj\jsoutput\Host.js'.`

**Comment by DanielRosenwasser** [comment]
Hi @mcintyre321, can you file a new issue and refer back to this one? It will make the discussion/diagnosis easier for the team.
