### ISSUE TITLE
Allow "interface typeof ClassName"

### ISSUE THREAD

**Issue by mikehofm** [Microsoft/TypeScript#29201]
## Search Terms

interface typeof class

## Suggestion

Allow declaration merging for the static side of classes using "interface typeof ClassName {}".

## Use Cases

I have a class, Foo, in a library. I need to add a static method to it. It, unfortunately, does not use a FooConstructor interface.

## Examples
```
// in some library
class Foo { }

// In my code:
// I can currently add instance methods like this:
interface Foo {
    someInstanceMethod():void;
}

// I'd like to be able to add static methods like this:
interface typeof Foo {
    someStaticMethod():void;
}

Foo.someStaticMethod = function() { /* do something */ };
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
You can sort of do this with namespace merging, so are there any major advantages with `interface` merging?

```ts
// in some library
class Foo { }

// Can add static methods like this:
declare namespace Foo {
    export function someStaticMethod(): void;
}

Foo.someStaticMethod = function() { /* do something */ };
```

**Comment by mikehofm** [comment]
When I do this, I seem to lose the original definition of Foo (i.e. let foo = new Foo() no longer works).

**Comment by DanielRosenwasser** [comment]
You'll likely have multiple definitions, but the same would happen with interface merging. If you're unable to do class/namespace merging with project references, that's likely a bug.

However, if you're using modules (i.e. files with top-level `import`s/`export`s), then it's likely because each of your files have different scopes. In that case you'll have to use something called a module augmentation.

```ts
// ./a.ts
export class Foo {

}

// ./b.ts
// Ensure this file is a module.
import { Foo } from "./a"

// Augment a
declare module "./a" {
  export declare namespace Foo {
    export function someStaticMethod(): void;
  }
}

Foo.someStaticMethod = function() { /* do something */ };
````

**Comment by DanielRosenwasser** [comment]
Interesting. I'll file a separate bug. But if you're not using modules, you shouldn't need the example I used.

**Comment by mikehofm** [comment]
Right. So to recap, I have a node.js project which does use modules and a library which does not. Foo is a class declared in the library. If I try to add a static method in the node.js project like so:

```
declare namespace Foo {
    export function someStaticMethod(): void;
}
```

It loses the original definition of class Foo and I get errors anywhere I try to use any of the methods defined in the library. Module augmentation also doesn't work, presumably because my library is not using modules.

Is this a bug caused by referencing a project not using modules from a project that is using modules?

**Comment by DanielRosenwasser** [comment]
Yeah, you'd need to use a global augmentation:

```ts
declare global {
    declare namespace Foo {
        export function someStaticMethod(): void;
    }
}
```

**Comment by mikehofm** [comment]
That worked perfectly. Thank you for your help!
