### ISSUE TITLE
Enum in Switch - Error:() TS2678: Type 'x' is not comparable to type 'y'.

### ISSUE THREAD

**Issue by danielsedlacek** [Microsoft/TypeScript#29204]
**TypeScript Version:**  
3.2.1, plus whatever runs on typescriptlang.org playground.

**Search Terms:**
enum, enum comparable

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
See Playground Link.

**Expected behavior:**
No error.

**Actual behavior:**
Error:() TS2678: Type 'Backend.kinvey' is not comparable to type 'Backend.static'.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=enum%20Backend%20%7B%0D%0A%20%20%20%20%20%20%20%20url%2C%0D%0A%20%20%20%20%20%20%20%20kinvey%2C%0D%0A%20%20%20%20%20%20%20%20static%0D%0A%7D%0D%0A%20%20%20%20%0D%0Avar%20backend%3A%20Backend%3B%0D%0A%0D%0Abackend%20%3D%20Backend.static%3B%0D%0Acompare()%3B%0D%0A%0D%0Afunction%20compare()%20%7B%0D%0A%20%20%20%20backend%20%3D%20Backend.static%3B%0D%0A%0D%0A%20%20%20%20switch%20(backend)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Backend.static%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20case%20Backend.kinvey%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20case%20Backend.url%3A%0D%0A%20%20%20%20%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:** 
Of course in the example some branches of the Switch are unreachable but that should not throw an error. If you delete the statement "backend = Backend.static;" on line 13, while keep the same statement outside the function on line 9, the situation is identical but no error is thrown.

**Comment by danielsedlacek** [comment]
What is the point of TypeScript compiler linting the code? Also, I am not getting a warning, I am getting an error.

**Comment by fatcerberus** [comment]
All TypeScript errors are warnings by definition because it still emits code (unless you use `--noEmitOnError`)

**Comment by fatcerberus** [comment]
It’s a type for the same reason as:
```ts
let x: 1 | 2 | 3 = 1;
x = 4;  // error
```

**Comment by ahejlsberg** [comment]
See #9998 for a lengthy discussion on this topic.

**Comment by danielsedlacek** [comment]
¯\_(ツ)_/¯

**Comment by fatcerberus** [comment]
To summarize the points in #9998: Canceling type narrowings across a function call causes more problems than not doing so, so the current behavior is the lesser of two evils.
