### ISSUE TITLE
Html import es6

### ISSUE THREAD

**Issue by DominicBoettger** [Microsoft/TypeScript#2920]
When creating a es6 based angular project i stumbled about one functionality i have in es6, but i think it's not provided by typescript or i did not find it in the documentation.

Here is a example:
https://github.com/lookfirst/systemjs-material-start/blob/master/src/app/users/UsersController.js

In line 1:
```javascript
import contactSheetTpl from 'app/users/contactSheet.tpl';
```

How can i achieve that typescript creates an output like this and don't thinks that i want to load an external module?

Thanks.

**Comment by igl** [comment]
I can't quote the specs but i don't think its possible to use es6 modules to load other files than javascript code.
It's also not possible to use conditional imports `if (foo) { import ...} else { import ...}`
or by template strings ```import foo from `lib/${bar}````.

Your case is only possible in node with commonjs via the deprecated api `require.extensions` or by browserify plugin for the browser. ES6 is not a dynamic module system.
I remember reading a post from npm-isaac criticising the limited behavior of es6 modules before and i concur.

**Comment by DominicBoettger** [comment]
Systemjs solves this issue by creating javascript files which embeds the templates but i think it's not possible to use this approach with typescript.

**Comment by mhegazy** [comment]
TypeScript has nothing to do with what you are loading at run time; that is the job of your module loader.

All the TypeScript compiler needs is the shape of the thing you are importing. So for your case, in one of your file, say "myModuleDefinitions.d.ts":
```ts
declare module "app/users/contactSheet.tpl" {
    var contanct: {
        name: string;
        email: string;
    };

    export default contanct;
}
```

then in your other file (module.ts):
```
import contactSheetTpl from 'app/users/contactSheet.tpl';

var name = contactSheetTpl.name;
var email = contactSheetTpl.email;
```

> tsc module.ts myModuleDefinitions.d.ts --m amd

should result in no errors.

**Comment by DominicBoettger** [comment]
Okay, i understand and realized that the tpl file is getting compiled by ng2htmljs to a angular templateCache definition file. So i should create a job which automatically adds definition files for every template.
Do you know a gulp job which already does something like that?

**Comment by mhegazy** [comment]
@alexeagle would know more about this than I do.

**Comment by alexeagle** [comment]
Sorry, I don't know much about that either. Simple web search finds https://www.npmjs.com/package/gulp-ng-html2js - have you already tried that?

**Comment by DominicBoettger** [comment]
Hi @alexeagle, thanks for your answer. I am already using this module with systemjs. My problem is that i have to define every template in typescript. I think that might be a lot of overhead.... Do you have any ideas? Isn't that something you solved in angular 2.0?

**Comment by alexeagle** [comment]
Like I said, I don't know much about this so I'm not sure what you're describing that's a lot of overhead, or what the alternative would look like.
Going back to your OP it seems like you just want System to load your template as a fake module at runtime. I've had some occasions while migrating code to continue using the
`var tmpl = require('file.tpl')` syntax, where require implies the commonjs module loader is present. Since it's not `import` syntax, the TypeScript complier just emits that statement as-is.
Maybe you could do that (or use System module loading API rather than commonjs)?

**Comment by mtraynham** [comment]
If you're using Webpack to bundle, you can use the [html-loader](https://github.com/webpack/html-loader) with `require` syntax.  Typescript, I think complains about requiring non-ts files, but the work around is to just declare a function that says it's valid:
```
declare function require(path: string): string;
```
Then you can do:
```
var x: string = require('../templates/messagedialog.tpl.html');
```
html-loader will transform html template's into a module that looks like `module.export = <template>;`  Adding to the template cache is unnecessary if you can just require the "module" (i.e. file).

**Comment by mhegazy** [comment]
closing this issue for now, please reopen if there further details needed.

**Comment by GabrielGil** [comment]
That is part of my solution tho @mtraynham. 

I am building an angularJS app (migrating better said), that uses `html-loader` ang `ngtemplate-loader` to use the templates on my components. Before using Typescript I was just importing the template as follows:

```js
import templateUrl from './path.html';
const componentDefinitionObject = {
  templateUrl
}
```

Now this seems to not be so pleasant for TS so have to use:

```js
const componentDefinitionObject = {
  templateUrl: require('./path.html')
}
```

Is this the only way? Are the imports not expected to work?
