### ISSUE TITLE
Attaching property to exported function creates invalid definition file

### ISSUE THREAD

**Issue by SimenB** [Microsoft/TypeScript#29206]
**TypeScript Version:**  3.3.0-dev.20181229

**Search Terms:**
default export function property namespace

**Code**

```ts
export default function someFunc() {
    return 'hello!';
}

someFunc.someProp = 'yo';
```

**Expected behavior:**
The declaration file should be valid

**Actual behavior:**
```
packages/proj-1/build/index.d.ts:2:26 - error TS1005: ';' expected.

2 export default namespace someFunc {
                           ~~~~~~~~

packages/proj-1/build/index.d.ts:2:35 - error TS1005: ';' expected.

2 export default namespace someFunc {
```

**Playground Link:** Cannot be reproduced in the playground as the issue is in the `d.ts` file, not the JS. However, I've setup a repository: https://github.com/SimenB/tsc-b-auch

**Related Issues:** None found

**Comment by SimenB** [comment]
Note that the file is generated successfully, it's only when trying to consume it things fall apart

**Comment by DanielRosenwasser** [comment]
Haven't tried this, but you can probably get around this by writing

```ts
function someFunc() {
    return 'hello!';
}

someFunc.someProp = 'yo';

export default someFunc;
```

**Comment by SimenB** [comment]
Yeah, that works! Thanks 🙂

**Comment by DanielRosenwasser** [comment]
Thanks @Kingwl!

**Comment by Diokuz** [comment]
Have the same issue.
Is this by design?

**Comment by DanielRosenwasser** [comment]
This is scheduled for 3.5.0.
