### ISSUE TITLE
In JS, completion list suggests TypeScript syntax

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#29212]
**TypeScript Version:**  3.3.0-dev.20181222

**Search Terms:**

**Code**

```ts
// trigger completion list anywhere in a JS file
```

**Expected behavior:**

Completion list doesn't contain TypeScript specific syntax in JS files.

**Actual behavior:**

In JS files it suggests `enum`, `interface`, `namespace`, `type`, `declare`, `abstract`, `readonly`, `public`, `protected`, `private`.

**Playground Link:** 

**Related Issues:**

**Comment by suhailsinghbains** [comment]
Hi, Can I please work on this issue, I am new here.

**Comment by sheetalkamat** [comment]
@suhailsinghbains Please go ahead..

**Comment by suhailsinghbains** [comment]
Hi @sheetalkamat 
Can you please guide me as to which file(s) need to be changed, will be great help :)

**Comment by sheetalkamat** [comment]
You would want to add another filter kind at https://github.com/Microsoft/TypeScript/blob/master/src/services/completions.ts#L32 and handle set it to true if its js file. Look for usage of the other keyword filters to see how that is handled. You would also want to add test in `tests/cases/fourslash/` which tests this. `completionInJsDoc.ts is example for that`
