### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by asurance** [Microsoft/TypeScript#29229]
**TypeScript Version:**  3.1.4

**Search Terms:**

**Code**

```ts
class bug{
    private static pool: { [id: number]: (val: any) => void } = {};
    public static bug<T extends { id: number }, K extends { id: number }>(msg: T) {
        return new Promise<K>((resolve) => {
            this.pool[msg.id] = resolve;
        });
    }
}

async function test() {
    let msg: { id: number, str: string } = await bug.bug({ id: 1, str: "hello" });
    console.log(msg.str);
}
test();
```

**Expected behavior:**
working well and pass compile
**Actual behavior:**
can't pass compile;
throw error:
Type '{ id: number; }' is not assignable to type '{ id: number; str: string; }'.
  Property 'str' is missing in type '{ id: number; }'.

149             let msg: { id: number, str: string } = await bug.bug({ id: 1, str: "hello" });
but no warning or error tips;tip shows that type of function is 
(method) bug.bug<{
    id: number;
    str: string;
}, {
    id: number;
    str: string;
}>(message: {
    id: number;
    str: string;
}): Promise<{
    id: number;
    str: string;
}>
i don't know what happens when compiling;
**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=class%20bug%7B%0D%0A%20%20%20%20private%20static%20pool%3A%20%7B%20%5Bid%3A%20number%5D%3A%20(val%3A%20any)%20%3D%3E%20void%20%7D%20%3D%20%7B%7D%3B%0D%0A%20%20%20%20public%20static%20bug%3CT%20extends%20%7B%20id%3A%20number%20%7D%2C%20K%20extends%20%7B%20id%3A%20number%20%7D%3E(msg%3A%20T)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20Promise%3CK%3E((resolve)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.pool%5Bmsg.id%5D%20%3D%20resolve%3B%0D%0A%20%20%20%20%20%20%20%20%7D)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aasync%20function%20test()%20%7B%0D%0A%20%20%20%20let%20msg%3A%20%7B%20id%3A%20number%2C%20str%3A%20string%20%7D%20%3D%20await%20bug.bug(%7B%20id%3A%201%2C%20str%3A%20%22hello%22%20%7D)%3B%0D%0A%20%20%20%20console.log(msg.str)%3B%0D%0A%7D%0D%0Atest()%3B
**Related Issues:**

**Comment by j-oliveras** [comment]
I don't see errors on playground (that uses version 3.2.1). Seems solved on version 3.2.x.
