### ISSUE TITLE
Simplify hybrid type creation

### ISSUE THREAD

**Issue by starksm64** [Microsoft/TypeScript#2922]
The vast majority of JavaScript libraries I'm trying to use TypeScript with require what the handbook refers to as a hybrid type. The creation of these types as far as I can tell requires a detyped function definition that in addition to being awkward for someone coming from a Java/C# background, it also allows one to fail to implement the hybrid type properly. Here is a simple example that is an extension of the SearchFunc interface function type from the handbook.

```javascript
interface SearchFunc {
  (source: string, subString: string): boolean;
}

interface ISearchFuncExt extends SearchFunc {
  cancel(promise: any): boolean;
}

function getISearchFuncExt() : ISearchFuncExt {
    var searchFunExt: any = function (source:string, subString:string) : boolean {
        var result = source.search(subString);
        if (result == -1) {
            return false;
        }
        else {
            return true;
        }
    };
    // This is not required, if commented out one gets a runtime error due to cancel being undefined
    searchFunExt.cancel = function (promise: any):boolean {
        return false;
    };
    return searchFunExt;
}

var mySearchExt : ISearchFuncExt = getISearchFuncExt();
mySearchExt("input", "put");
console.log(mySearchExt.cancel);
mySearchExt.cancel(null);
```

Using the 1.5.0-alpha tsc compiler and node runtime, this runs as expected:
```
/usr/local/bin/node SearchFuncExt.js
() invoked
[Function]
cancel(...) invoked
```

However, if I comment out the searchFunExt.cancel definition, the code compiles, but fails with a runtime error:
```
/usr/local/bin/node SearchFuncExt.js
() invoked
undefined
/Users/starksm/Dev/JavaScript/TypeScript/tests/SearchFuncExt.js:23
mySearchExt.cancel(null);
            ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/starksm/Dev/JavaScript/TypeScript/tests/SearchFuncExt.js:23:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

What would be great is if one could simply implement such a hybrid type interface using a syntax like the following:
```javascript
class HybridSearchFuncImpl implements ISearchFuncExt {

    constructor() {
    }
    function(source:string, subString:string) : boolean {
        var result = source.search(subString);
        if (result == -1) {
            return false;
        }
        else {
            return true;
        }
    }
    cancel(promise: any):boolean {
        return false;
    }
}

var testSearchFunc : ISearchFuncExt = new HybridSearchFuncImpl();
testSearchFunc("input", "put");
testSearchFunc.cancel(null);
```

**Comment by ahejlsberg** [comment]
It is already possible to do this with a merged function and module:

```typescript
interface SearchFunc {
    (source: string, subString: string): boolean;
}

interface ISearchFuncExt extends SearchFunc {
    cancel(promise: any): boolean;
}

function mySearchFunc(source: string, subString: string): boolean {
    var result = source.search(subString);
    if (result == -1) {
        return false;
    }
    else {
        return true;
    }
}
module mySearchFunc {
    export function cancel(promise: any): boolean {
        return false;
    }
}

var mySearchExt: ISearchFuncExt = mySearchFunc;
mySearchExt("input", "put");
console.log(mySearchExt.cancel);
mySearchExt.cancel(null);
```

However, it is currently not possible to nest a merged function/module within another function. That's something we very likely to remedy when we implement support for local classes and class expressions as required by ES6.

Your suggestion of using a class declaration for this is problematic in that once `new` allocates an object it is not possible to make it callable afterwards. In order to be callable, an object has to have been allocated by a function declaration or function expression.

**Comment by starksm64** [comment]
Ok, I see this concept in the declaration merging section in the handbook now. Using a module to extend a type just isn't a natural notion coming primarily from Java, but so be it.

**Comment by mhegazy** [comment]
Looks like the original issue has already been handled. callable constructors should be supported in a future release as the [ES proposal](https://github.com/tc39/ecma262/blob/master/workingdocs/callconstructor.md) advances to higher stages.
