### ISSUE TITLE
Invalid completion entries returned after open paren + dot

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#29234]
From https://github.com/Microsoft/vscode/issues/65684

**TypeScript Version:**  3.3.0-dev.20190101

**Search Terms:**
- suggestions
- completions

**Code**
For the TypeScript:

```ts
const [foo, bar] = [Math.min(.)]
```

Request completions after the `.` inside `min`

**Expected behavior:**
No  entries returned

**Actual behavior:**
The following entries are returned:

```
[Trace  - 11:27:08 AM] Response received: completionInfo (152). Request took 2 ms. Success: true 
Result: {
    "isGlobalCompletion": false,
    "isMemberCompletion": true,
    "isNewIdentifierLocation": false,
    "entries": [
        {
            "name": "toExponential",
            "kind": "method",
            "kindModifiers": "declare",
            "sortText": "0"
        },
        {
            "name": "toFixed",
            "kind": "method",
            "kindModifiers": "declare",
            "sortText": "0"
        },
        {
            "name": "toLocaleString",
            "kind": "method",
            "kindModifiers": "declare",
            "sortText": "0"
        },
        {
            "name": "toPrecision",
            "kind": "method",
            "kindModifiers": "declare",
            "sortText": "0"
        },
        {
            "name": "toString",
            "kind": "method",
            "kindModifiers": "declare",
            "sortText": "0"
        },
        {
            "name": "valueOf",
            "kind": "method",
            "kindModifiers": "declare",
            "sortText": "0"
        }
    ]
}
```

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
What's happening is that as soon as our parser encounters a `.`, it freaks out and jumps out of the current "parsing context" (i.e. parsing arguments in an argument list).

So it ends up parsing `Math.min(` as an incomplete call expression, followed by a `.`, thinking that you're trying to write `Math.min().` which gives you the property of a `number`.

**Comment by cartok** [comment]
Is it back? 
![image](https://user-images.githubusercontent.com/22181589/94146055-afa8f080-fe73-11ea-99dc-91a5f1fa40bf.png)

**Comment by DanielRosenwasser** [comment]
Not clear, try disabling IntelliCode. If that does't fix it, please file a separate bug.
