### ISSUE TITLE
Why object destructuring compiles as vars assignments?

### ISSUE THREAD

**Issue by gsbelarus** [Microsoft/TypeScript#29230]
TSC v.3.2.2

source line of code:
```
const { a, b, c} = obj;
```
compiles as:
```
var a = obj.a, b = obj.b, c = obj.c;
```
Why? Don't all modern js engines support object destructuring?

tsconfig.json

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "lib": ["esnext"],
    "strict": false,
    "esModuleInterop": true
  }
}
```

**Comment by j-oliveras** [comment]
I cannot reproduce it:
index.ts
```ts
declare const obj: any; // added to avoid compilation errors

const { a, b, c} = obj;
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "lib": ["esnext"],
    "strict": false,
    "esModuleInterop": true
}
```
package.json
```json
{
    "private": true,
    "devDependencies": {
        "typescript": "^3.2.2"
    },
    "dependencies": {
        "@types/node": "^10.12.12"
    }
}
```

I compile it with `.\node_modules\.bin\tsc.cmd -p .` (after `npm i`).

Make sure you use the defined tsconfig file: if you call it as `.\node_modules\.bin\tsc.cmd index.ts` the tsconfig will ignored.

**Comment by gsbelarus** [comment]
I use tsc installed globally. Will recheck with tsc installed locally.

**Comment by gsbelarus** [comment]
yes. it works with a command:

`.\node_modules\.bin\tsc.cmd -p .`

it is strange, that even after have installed typescript locally command

`tsc ds.ts`

generates old .js ignoring settings from tsconfig.json.

**Comment by MartinJohns** [comment]
> it is strange, that even after have installed typescript locally command
> 
> `tsc ds.ts`
> 
> generates old .js ignoring settings from tsconfig.json.

That is not strange, that is the documented behavior: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

> When input files are specified on the command line, tsconfig.json files are ignored.

And you are specifying input files.

**Comment by gsbelarus** [comment]
Sorry, I missed this point. Thanks for the information.
