### ISSUE TITLE
New Website Logo: Wallaby.js

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/TypeScript#2924]
- Name: Wallaby.js
- Homepage url: http://wallabyjs.com/
- Logo: http://wallabyjs.com/assets/img/logoWithText.svg

Wallaby.js is an intelligent test runner for JavaScript that continuously runs your tests. It reports code coverage and other results directly to your code editor immediately as you change your code. Currently supports WebStorm, [Visual Studio integration](https://twitter.com/ArtemGovorov/status/577956450053451776) is in progress.

[Wallaby.js supports TypeScript](http://dm.gl/2015/04/13/wallaby-expanding/) (using Language Service API) for browser and node.js

![ts](https://cloud.githubusercontent.com/assets/979966/7340713/2cf0f510-ecd7-11e4-8c7a-954ebab2ac16.gif)

**Comment by jonathandturner** [comment]
Cool to see test runners that support TypeScript!  Good stuff.

For the logo, since it's fairly simple, it may be hard for people to understand what it is at a glance.  You may want to do what some of the other logos have done and put the name of the project as part of the .svg.  You can see examples on the "Friends of TypeScript" site where other projects have done this.

**Comment by ArtemGovorov** [comment]
@jonathandturner Thanks for your response! I have added the logo version with some text - http://wallabyjs.com/assets/img/logoWithText.svg, also edited the original post to update the logo link.

**Comment by jonathandturner** [comment]
Added.

**Comment by ArtemGovorov** [comment]
@jonathandturner Hello, it seems like I have used an incorrect font in the logo and the png version doesn't look nice and crisp. I have updated it, here the png - http://wallabyjs.com/assets/img/logoWithText.png (I have updated the existing svg as well), could you please replace it on the website? Sorry for that, thanks.

**Comment by jonathandturner** [comment]
Updated.
