### ISSUE TITLE
[API Question] Only `x` and `y` types getting switched after updating

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#29255]
Just a curious observation.

I was on TS `3.3.0-dev.20181129`. Then, I discovered a bug and was about to file a report but realized it was fixed in `3.3.0-dev.20190103`.

So, I updated. After updating, about half of my compile-time tests (190 files) started failing, because the compiled output is now different. No biggie. I expected this to happen. Probably characters getting shuffled around, since I do a character-by-character comparison.

I looked at the diffs and it looks like most, if not all, are some variant of the following,

![image](https://user-images.githubusercontent.com/5655961/50674509-0c37ee00-0fb5-11e9-8e3a-55a3aa8fc9ff.png)
![image](https://user-images.githubusercontent.com/5655961/50674515-135efc00-0fb5-11e9-9b4f-7d0c5d71ebbc.png)
![image](https://user-images.githubusercontent.com/5655961/50674519-1a860a00-0fb5-11e9-8fad-6b6f61e98a11.png)

It's just anywhere with `x`, and `y` gets switched. So far, it looks like all other fields/string literals do not get switched around.

I wouldn't be so confused if *all* fields were getting swapped around, somehow. Or if things were getting randomly shuffled. But it looks like it's only `x` and `y`.

I have some objects where the fields are `a`, `b`, `c`, etc. but only `x` and `y` seem to be flipped. (I'll stop repeating myself ad nauseam)

-----

Does anyone have any insight as to why it's just those two characters and nothing else?

**Comment by AnyhowStep** [comment]
![image](https://user-images.githubusercontent.com/5655961/50674967-ced55f80-0fb8-11e9-8350-2e9a473e2733.png)

Slightly longer string with only `x` and `y` switched.

I've also seen something like,

```ts
{ x : SomeTypeA }|{ y : SomeTypeB }
```

become,

```ts
{ y : SomeTypeB }|{ x : SomeTypeA }
```

So, even objects containing `x` and `y`, in a union type get switched.

**Comment by AnyhowStep** [comment]
I added a few new tests without modifying the original tests and it switched the x and y of all the other 190 files back to how they were before ._.

I'm guessing it's a duplicate of #29146, which I opened before but, in this case, something changed between the two versions that just acted weird =/

**Comment by AnyhowStep** [comment]
Actually, maybe it's slightly different. Before, it was always a small number of files, and object properties wouldn't get switched. This one had them flipped. I'm sure it's related to the other question but I'm not 100% sure.

**Comment by weswigham** [comment]
Definitely still #29146 - union order is _solely_ determined by the order the types were originally materialized in the checker. It's entirely possible that somewhere we now find a `"y"` type before a `"x"` one.

TBH, I'd prefer if string literal types were sorted lexicographically... maybe we can change how their IDs are assigned to support that...

**Comment by AnyhowStep** [comment]
All right, thanks for clarifying ><
