### ISSUE TITLE
createProgram() options lib values should match --lib values

### ISSUE THREAD

**Issue by paulmedynski** [microsoft/TypeScript#29258]
**TypeScript Version:**
3.1.3

**Search Terms:**
lib target

**Code**
```json
{
  "compilerOptions":
  {
    "lib":"ES2017,DOM",
    "target":"ES2017"
  }
}
```

```js
const ts = require('typescript');
const compilerOptions = require('tsconfig.json').compilerOptions;

const host = ts.createCompilerHost(options);
const prog = ts.createProgram('my_file.ts', options, host);
```

**Expected behaviour:**
The compiler options docs use upper-case names when providing the possible `lib` values:

> List of library files to be included in the compilation.
> Possible values are:
> ► ES5
> ► ES6
> ► ES2015
> ► ES7
> ► ES2016
> ► ES2017
> ► ES2018
> ...

However, you must use the actual lower-case lib filenames, such as `lib.es5.d.ts`, `lib.es2017.d.ts`, `lib.dom.d.ts`, in order for the `lib` compiler option to work as expected.

**Actual behaviour:**
Using the documented `--lib` values doesn't work for the `lib` compiler option.

The `createProgram()` function could be updated to perform the documented value to filename value mapping, or the internal `libMap` array could be exposed.

**Comment by weswigham** [comment]
If you're using the API, you want to use `getParsedCommandLineOfConfigFile` to get the config values from the tsconfig - those do all the proprocessing and looking-up you need to do (including supporting `extends`). `lib` is far from the only compiler option that has a different, "friendly" representation in a tsconfig than it has in our internal `CompilerOptions` type (it's just one of only a few where the friendly version and the internal version share a type).

**Comment by paulmedynski** [comment]
Thanks for pointing me to the `getParsedCommandLineOfConfigFile` function.  I didn't see it documented on the wiki in the Compiler API section, so I probably never would have found it otherwise :)

In my case, I already have a JavaScript object that contains the options from `tsconfig.json`, so would `parseJsonSourceFileConfigFileContent` be a better option for me?  I'm working on some updates to the `typescript-brunch` plugin, so I don't have the original `tsconfig.json` filename, and the Brunch config may have added options anyway, so I definitely need to use the JavaScript options object that the plugin is given.

Thoughts?
