### ISSUE TITLE
Unexpected behavior with defaults when using inheritance and Object.assign

### ISSUE THREAD

**Issue by bmass02** [Microsoft/TypeScript#29268]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**
Inheritance, Defaults, Object.assign, Compiled TypeScript

**Code**

```ts
interface IGParent {
    prop5: number;
}

class GParent implements IGParent {
    prop5 = 0;
    _sourceData;

    constructor(data?: Partial<IGParent> | IGParent | GParent) {
        Object.assign(this, data);
        this._sourceData = data;
    }

    works() {
        return Object.keys(this).reduce((working, propName) => {
            if (propName === '_sourceData') {
                return working;
            }
            return working && this.hasOwnProperty(propName)
                && this[propName] === (this._sourceData && this._sourceData.hasOwnProperty(propName) ? this._sourceData[propName] : (this.constructor())[propName])
        }, true)
    }
}

interface IParent extends IGParent {
    prop3: number;
    prop4: string;
}

class Parent extends GParent implements IParent {
    prop3: number;
    prop4 = '';

    constructor(data?: Partial<IParent> | IParent | Parent) {
        super(data);
    }
}

interface IChild extends IParent {
    prop1: number;
    prop2: string;
}

class Child extends Parent implements IChild {
    prop1 = 10;
    prop2: string;
    prop5 = 20;

    constructor(data?: Partial<IChild> | IChild | Child) {
        super(data);
    }
}

let defaultChild = new Child();
let existingChild = new Child({ prop1: 50, prop4: 'will be overwritten' });

console.log(defaultChild.works()); // true
console.log(existingChild.works()); // false
```

**Expected behavior:**
The compiled JavaScript should not overwrite any existing values with defaults.

**Actual behavior:**
The compiled JavaScript overwrites existing values with defaults.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=interface%20IGParent%20%7B%0D%0A%20%20%20%20prop5%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20GParent%20implements%20IGParent%20%7B%0D%0A%20%20%20%20prop5%20%3D%200%3B%0D%0A%20%20%20%20_sourceData%3B%0D%0A%0D%0A%20%20%20%20constructor(data%3F%3A%20Partial%3CIGParent%3E%20%7C%20IGParent%20%7C%20GParent)%20%7B%0D%0A%20%20%20%20%20%20%20%20Object.assign(this%2C%20data)%3B%0D%0A%20%20%20%20%20%20%20%20this._sourceData%20%3D%20data%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20works()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20Object.keys(this).reduce((working%2C%20propName)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(propName%20%3D%3D%3D%20'_sourceData')%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20working%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20working%20%26%26%20this.hasOwnProperty(propName)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%26%26%20this%5BpropName%5D%20%3D%3D%3D%20(this._sourceData%20%26%26%20this._sourceData.hasOwnProperty(propName)%20%3F%20this._sourceData%5BpropName%5D%20%3A%20(this.constructor())%5BpropName%5D)%0D%0A%20%20%20%20%20%20%20%20%7D%2C%20true)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20IParent%20extends%20IGParent%20%7B%0D%0A%20%20%20%20prop3%3A%20number%3B%0D%0A%20%20%20%20prop4%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Parent%20extends%20GParent%20implements%20IParent%20%7B%0D%0A%20%20%20%20prop3%3A%20number%3B%0D%0A%20%20%20%20prop4%20%3D%20''%3B%0D%0A%0D%0A%20%20%20%20constructor(data%3F%3A%20Partial%3CIParent%3E%20%7C%20IParent%20%7C%20Parent)%20%7B%0D%0A%20%20%20%20%20%20%20%20super(data)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20IChild%20extends%20IParent%20%7B%0D%0A%20%20%20%20prop1%3A%20number%3B%0D%0A%20%20%20%20prop2%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Parent%20implements%20IChild%20%7B%0D%0A%20%20%20%20prop1%20%3D%2010%3B%0D%0A%20%20%20%20prop2%3A%20string%3B%0D%0A%20%20%20%20prop5%20%3D%2020%3B%0D%0A%0D%0A%20%20%20%20constructor(data%3F%3A%20Partial%3CIChild%3E%20%7C%20IChild%20%7C%20Child)%20%7B%0D%0A%20%20%20%20%20%20%20%20super(data)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20defaultChild%20%3D%20new%20Child()%3B%0D%0Alet%20existingChild%20%3D%20new%20Child(%7B%20prop1%3A%2050%2C%20prop4%3A%20'will%20be%20overwritten'%20%7D)%3B%0D%0A%0D%0Aconsole.log(defaultChild.works())%3B%0D%0Aconsole.log(existingChild.works())%3B

**Possible solution:** 
Use something similar to below to set defaults (by checking for existence first)
```javascript
setDefault = (_this, propName, defaultVal) => {
    if (_this[propName] === undefined) {
		_this[propName] = defaultVal;
    }
}
```

**Comment by AnyhowStep** [comment]
Related to #29113 ?

**Comment by DanielRosenwasser** [comment]
Property initializers run after the `super()` constructor, so this is working as intended.
