### ISSUE TITLE
Mapped type does not work with conditional type

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#29269]
**TypeScript Version:**  3.2.2

**Search Terms:**
Exclude
Mapped type
Conditional types

**Code**

```ts
// `T extends undefined ? never : T` is working correctly in arguments
function acceptNoUndefined<T>(actual: Exclude<T, undefined>) { return actual }

type RequiredPick<T, U extends keyof T> = {
  [P in keyof T]: P extends U ? Exclude<T[P], undefined> : T[P]
}

type Foo = {
    a?: number,
    b?: number,
    c: number
  }

let y: RequiredPick<Foo, 'a'> = {} as any

acceptNoUndefined(y.a)  // error, y.a is still 'number | undefined'
```

**Playground Link:**
[Playground link](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20%60T%20extends%20undefined%20%3F%20never%20%3A%20T%60%20is%20working%20correctly%20in%20arguments%0Afunction%20acceptNoUndefined%3CT%3E(actual%3A%20Exclude%3CT%2C%20undefined%3E)%20%7B%20return%20actual%20%7D%0A%0Atype%20RequiredPick%3CT%2C%20U%20extends%20keyof%20T%3E%20%3D%20%7B%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20P%20extends%20U%20%3F%20Exclude%3CT%5BP%5D%2C%20undefined%3E%20%3A%20T%5BP%5D%0A%7D%0A%0Atype%20Foo%20%3D%20%7B%0A%20%20%20%20a%3F%3A%20number%2C%0A%20%20%20%20b%3F%3A%20number%2C%0A%20%20%20%20c%3A%20number%0A%20%20%7D%0A%0Alet%20y%3A%20RequiredPick%3CFoo%2C%20'a'%3E%20%3D%20%7B%7D%20as%20any%0A%0AacceptNoUndefined(y.a)%20%20%2F%2F%20error%2C%20y.a%20is%20still%20'number%20%7C%20undefined')

**Comment by ajafff** [comment]
You need to remove the optionality as well:

```ts
{
[P in keyof T]-?: P extends U ? Exclude<T[P], undefined> : T[P]
}

**Comment by jack-williams** [comment]
The mapped type in `RequiredPick` retains the optional modifier so the type still comes out as undefined. I think the best you can do is something like this:
```ts
type RequiredPick<T, U extends keyof T> = {
    [P in U]-?: Exclude<T[P], undefined>;
} & {
    [P in Exclude<keyof T, U>]: T[P];
}
```

**Comment by unional** [comment]
> You need to remove the optionality as well:

Cannot do that because that would affect keys that are not `U`.

**Comment by unional** [comment]
@jack-williams  That's a good catch, but seems to be not the cause:

```ts
  type Foo = {
    a: number | undefined,
    b?: number,
    c: number
  }
```

Gives the same error. So this failure is not because it is optional (`?`).

**Comment by jack-williams** [comment]
> IMO this is still an issue as the user would expect the type in the OP should work as is.

There are definitely some pain points around optionality. This thread seems relevant if you want to look further into it #13195

**Comment by unional** [comment]
Thank. https://github.com/unional/type-plus/compare/required?expand=1
