### ISSUE TITLE
Imports are not elided when they are used in computed properties in interfaces

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#29263]
Imports are not elided when they are used in computed properties in interfaces. This issue was discovered an a SO question: https://stackoverflow.com/questions/54042545/typescript-compiler-generates-unused-variable-when-using-enum-value-as-an-interf

**TypeScript Version:**  3.3.0-dev.20190104

**Search Terms:**
computed enum elided
**Code**

```ts
// props.ts
export enum PROPS {
    A = 'PROP_A',
    B = 'PROP_B',
}

// usage.ts
import { PROPS } from './props';

export declare interface ISomething {
    [PROPS.A]: string;
}
```

**Expected behavior:**

Since PROPS.A is only used in a type the `./props` import should be elided. 

**Actual behavior:**

The import is included in the emitted JS code:

```js
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const props_1 = require("./props");

```

**Related Issues:** 
This issue seems to be the closest but is the the exact opposite, some imports were elided when the should not be: https://github.com/Microsoft/TypeScript/pull/19430
This is about const enums and the actual value is used: https://github.com/Microsoft/TypeScript/issues/4690

**Woraround**
If we declare a local const for the `PROPS` the import is elided as expected:

```ts
import { PROPS } from './props';

declare const LOCAL_PROPS: typeof PROPS
export declare interface ISomething {
    [LOCAL_PROPS.A]: string;
}
```

**Comment by j-oliveras** [comment]
If the enum is declared as const then the import are elided:
```ts
// props.ts
export const enum PROPS {
    A = 'PROP_A',
    B = 'PROP_B',
}

// usage.ts
import { PROPS } from './props';

export declare interface ISomething {
    [PROPS.A]: string;
}
```

**Comment by dragomirtitian** [comment]
@j-oliveras Yes but const enum imports  are aggressively elided  anyway, even if used in expressions. For example, the import is elided here as well:

```ts
import { PROPS } from './props';
const s = PROPS.A;
```
This example is more analogous to a class being imported and only being used in types annotations, sure usually the import should not be elided, but if there is no runtime reason for the import to exist it should be elided.

**Comment by dragomirtitian** [comment]
Seems to have been fixed
