### ISSUE TITLE
Enhanced Object Literals error

### ISSUE THREAD

**Issue by lucasmciruzzi** [Microsoft/TypeScript#2926]
If I write this code combining computed properties with shorthand properties:

    var greet = "hi",
        object = {
            greet, // Shorthand for greet: greet
            ["fare" + "well"]: "bye" // Computed
        };

I get this output, that a bad assign on it:

    var greet = "hi", object = (_a = {
        greet: greet
    },
        _a.greet = , // ERROR
        _a["fare" + "well"] = "bye",
        _a);
    var _a;

That's it :)

**Comment by DanielRosenwasser** [comment]
Hi @lucasmciruzzi, this looks to be fixed in branches `release-1.5` and `master`. Thanks for filing, happy hacking!

**Comment by lucasmciruzzi** [comment]
Ok, the problem then is that release-1.5 is not yet available in NPM, because the latest version there is 1.5.0-alpha .... I'll clone the 1.5 branch for now.

Thanks!
