### ISSUE TITLE
Having literals operations returning literals

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#29271]
## Search Terms

enumassignmentcompat5.ts, ts2535

## Suggestion

Currently, operations between literals are not considered as literals. It would bring much more flexibility to have this feature.

## Use Cases

Operations on literals could help having better declarations and would help having more complex enums

## Examples

```js
// extract of enumassignmentcompat5.ts (which is not anymore in the repo BTW)
enum E {
    A, B, C
}
enum Computed {
    A = 1 << 1,
    B = 1 << 2,
    C = 1 << 3,
}
let ca: Computed.A = 1; // ok, because 1( left hand side operand) and 1 (right hand side operand) are literals, therefore, 1<<1 is also a literal.

```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by NN---** [comment]
#15645 #26382

**Comment by weswigham** [comment]
See #15645 #26382 - thanks @NN---

**Comment by npenin** [comment]
indeed, thanks
