### ISSUE TITLE
Error TS2304: Cannot find name 'XDomainRequest'.

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2927]
I just pulled down the master branch and tried to compile my project but got the error:

[TsProject] src/submission/DefaultSubmissionClient.ts(76,25): error TS2304: Cannot find name 'XDomainRequest'.
[TsProject] src/submission/DefaultSubmissionClient.ts(77,19): error TS2304: Cannot find name 'XDomainRequest'.

https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/src/submission/DefaultSubmissionClient.ts#L76-L77

It appears to be a bug because this should be a known type...

**Comment by RyanCavanaugh** [comment]
This was intentional (1dacb54fbd) -- `XDomainRequest` is an IE-only type and was removed from lib.d.ts. You can `declare var XDomainRequest;` (or grab the definition from an old version of lib.d.ts) if you want to do some IE-specific stuff.

**Comment by niemyjski** [comment]
Thanks for the heads up. Is this in the change log anywhere?

**Comment by RyanCavanaugh** [comment]
We should put this in the release notes.

**Comment by niemyjski** [comment]
I had to define it as declare var XDomainRequest: { new (): XDomainRequest;
prototype: XDomainRequest; create(): XDomainRequest; }; or I got an error.

Thanks
-Blake Niemyjski
