### ISSUE TITLE
Does Microsoft typescript compiler produce symbol table and, if so, it can be serialized 

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/TypeScript#29279]
## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ajafff** [comment]
You probably want to be a bit more specific to get some useful answers.

Yes it does build symbol tables. These *could* be serialized, but why would you want to do that?
Anyways, most symbol tables are internal so an API user is not supposed to access that information directly.

**Comment by PavelSosin** [comment]
If typescript module depends on several very big libraries off-line generation and import serialized Symbol table may improve performance. Changes in API of such libraries is very rare event but regeneration of library module which provides library component interfaces is very expensive.

**Comment by weswigham** [comment]
Declaration files are pretty much (human readable/editable) serialized symbol tables.
