### ISSUE TITLE
Defining types which are inlined in declaration files

### ISSUE THREAD

**Issue by Airblader** [Microsoft/TypeScript#29275]
## Search Terms

inline type alias typealias declaration

## Suggestion

Type aliases are currently exported into the `*.d.ts` file as-is. I would like to propose an option such as `inline type T = …` (or whatever syntax works) to mark types which should be inlined when creating the declaration file, i.e., replaced with their definition and thus erased from the file.

## Use Cases

I am writing a library in which I have type aliases for a couple things to prevent duplication within my library. This includes things like

1. function types: `type DomainFunction = (param1: number) => void;`
2. utility types: `type Unpack<T> = T extends (infer U)[] ? U : T`

I don't (want to) document or export these types and would like them to be replaced with their corresponding definition for the declaration file.

## Examples

Let's say we have

```
type Unpack<T> = T extends (infer U)[] ? U : T;

export function foo<T>(param1: T, param2: Unpack<T>): void {
}
```

Then this is the declaration file created versus what I would like to see:

```
// Created
declare type Unpack<T> = T extends (infer U)[] ? U : T;
export declare function foo<T>(param1: T, param2: Unpack<T>): void;

// Proposed
export declare function foo<T>(param1: T, param2: T extends (infer U)[] ? U : T): void;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Airblader** [comment]
@cevek Do you have a specific comment against this or did you just downvote it out of hate because I downvoted your issue for not following the issue template?

**Comment by cevek** [comment]
because inline is not always possible to use
```ts
type A<T> = T extends 1 ? T : never;
declare function foo(x: A<1 | 2>): void; // === function foo(x: 1): void; 
// if we inline A it would be
declare function bar(x: (1 | 2) extends 1 ? (1 | 2) : never): void;  // === function bar(x: never): void;
```

**Comment by Airblader** [comment]
Yeah, that's also a good point, for sure. Thanks!

**Comment by weswigham** [comment]
Yeah, because of how distributivity of conditional types is calculated, they aren't unconditionally inlinable (since subtituting the type parameter for a concrete type expression loses the distributivity), sorry 'bout that.

**Comment by Airblader** [comment]
I'll just close this then, it isn't that critical and it wouldn't be worth the effort to think about it much further. Thanks!
