### ISSUE TITLE
Narrow to `Exclude` type in conditional code

### ISSUE THREAD

**Issue by ranma42** [Microsoft/TypeScript#29280]
## Search Terms

conditional else exclude narrow

## Suggestion

TypeScript should infer `Exclude` types in conditional expressions and statements.
Specifically, whenever the positive branch (`if`, or the `x` in `c ? x : y`) has a more specific type thanks to a type guard, the negative branch (`else`/`y`) should have the relevant `Exclude` type.

## Use Cases

This would provide a natural way to infer `Exclude` types and it would generalise in a natural way the current behaviour of conditional statements over union and finite-domain types.
Apparently right now the only way to have a value of type `Exclude` is to assert it manually (either through type guards or type assertions).

## Examples
```TypeScript
function partition<A, B extends A>(items: A[], f: (x: A) => x is B): [B[], Array<Exclude<A, B>>] {
    const bs: B[] = [];
    const others: Array<Exclude<A, B>> = [];
    for (const x of items) {
        if (f(x)) {
            bs.push(x);
        } else { // with the proposed feature, x: Exclude<A, B> in this branch
            others.push(x); // while currently this fails because TSC infers x: A
        }
    }
    return [bs, others];
}
```

[Playground link](https://www.typescriptlang.org/play/#src=function%20partition%3CA%2C%20B%20extends%20A%3E(items%3A%20A%5B%5D%2C%20f%3A%20(x%3A%20A)%20%3D%3E%20x%20is%20B)%3A%20%5BB%5B%5D%2C%20Array%3CExclude%3CA%2C%20B%3E%3E%5D%20%7B%0D%0A%20%20%20%20const%20bs%3A%20B%5B%5D%20%3D%20%5B%5D%3B%0D%0A%20%20%20%20const%20others%3A%20Array%3CExclude%3CA%2C%20B%3E%3E%20%3D%20%5B%5D%3B%0D%0A%20%20%20%20for%20(const%20x%20of%20items)%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(f(x))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20bs.push(x)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%20%2F%2F%20with%20the%20proposed%20feature%2C%20x%3A%20Exclude%3CA%2C%20B%3E%20in%20this%20branch%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20others.push(x)%3B%20%2F%2F%20while%20currently%20this%20fails%20because%20TSC%20infers%20x%3A%20A%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20%5Bbs%2C%20others%5D%3B%0D%0A%7D)

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behaviour of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I am unsure if this could break existing code.
Making the typing more accurate could reveal dead code, which could result in compilation errors.

**Comment by ajafff** [comment]
This should be covered by https://github.com/Microsoft/TypeScript/pull/22348

**Comment by ranma42** [comment]
Possibly a duplicate of https://github.com/Microsoft/TypeScript/issues/23764

**Comment by ranma42** [comment]
Notice that this is consistent with the fact that the positive branch infers the `Extract` type (already resolved to the non-`never` type, thanks to the constraints on type guards).

**Comment by weswigham** [comment]
#22348 would be what this needs, yeah. Conditional types still have a few problems that make the current behavior by-design, though 😦

**Comment by ranma42** [comment]
I built #22348 locally and the example above fails to compile with the same error:
```error TS2345: Argument of type 'A' is not assignable to parameter of type 'Exclude<A, B>'.```

**Comment by ranma42** [comment]
This issue is likely a duplicate of https://github.com/Microsoft/TypeScript/issues/23764, but while that was a bug report (and thus closed as "not a bug"), this is a feature request, proposing an improvement to type narrowing.
