### ISSUE TITLE
addTypeToIntersection shouldn't use `contains`

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#29289]
Right now it uses `contains` to test for membership in the `typeSet` - this is a linear time membership check (so makes intersection construction exponential at best). Unions are sorted so at least use `binarySearch` which is a bit better - we should probably be building a membership map while constructing the intersection to keep intersections of a large number of objects performant.

**Comment by miloszpp** [comment]
Hi @weswigham! I had a quick look into the source code, could you give me a little hint?

In what sense `typeSet` is sorted? As I see, it's an array of `Type`. Are those `Type`s sorted by some property?

**Comment by weswigham** [comment]
An intersection `typeSet` is not sorted - it keeps input order so overload order is predictable (which is why it uses `contains` right now). What I've proposed is building a map/set journaling membership while the intersection is being constructed, so membership testing is cheaper.

**Comment by miloszpp** [comment]
You mentioned `binarySearch` - that's why I assumed `typeSet` is sorted.

So, the solution would be to maintain a separate `Set` that would contain all items that are inside `typeSet` and use it only for membership checking?

Would it make sense to change `typeSet` into an actual `Set` and later convert it into an array (inside `getIntersectionType`)?

**Comment by weswigham** [comment]
Possibly - maps and sets are defined to preserve insertion order, so that should be OK.

**Comment by ajafff** [comment]
IIRC it caused issues to use ES6 features like `Map` and `Set` in the compiler because some users expect it to run in ES5 environments. @weswigham I know you investigated dropping support for ES5 runtimes. Is there already a decision?

**Comment by weswigham** [comment]
Our `createMap` helper function polyfills `Map` on runtimes without it already~

**Comment by miloszpp** [comment]
Thanks, I can take a look at it then.

I saw in the guidelines that every change should have test coverage. Do you have a framework for testing performance changes, such as this one?

**Comment by weswigham** [comment]
Sadly, no, not formally. We can run `@typescript-bot perf test` on the PR to validate that it doesn't regress perf in the compilations we track, at least.

**Comment by fatcerberus** [comment]
> exponential

If membership check is linear time O(n) and each intersection member added has to do this check O(m * n) then shouldn’t the overall complexity be roughly quadratic?

**Comment by weswigham** [comment]
The point is moreso that it's not linear or logarithmic, so larger sets of things perform significantly worse. My language is imprecise, yes.

**Comment by fatcerberus** [comment]
Ah, that makes sense, thanks.  But yeah, there's a world of difference between quadratic (n^2) and exponential (2^n) growth - the former can sometimes be acceptable; the latter almost never is.  So it was important (to me) to pin down which one it actually was. :smile:

**Comment by miloszpp** [comment]
@weswigham should I somehow mark the PR as ready for review?
