### ISSUE TITLE
Several issues with the current //@ts-ignore functionality

### ISSUE THREAD

**Issue by doberkofler** [Microsoft/TypeScript#29284]
## Search Terms

ts-ignore

## Suggestion

Improve `//@ts-ignore` functionality to match the functionality of current lint tools like tslint and eslint by allowing to disable and enable specific rules for a file, a block of code or a specific line.

## Use Cases

Especially when migrating to TypeScript it is necessary to suppress some of the error messages reported by the TypeScript compiler. Currently TypeScript offers a very rudimentary way to do so and it should be improved to match what the current lint tools like tslint and eslint currently offer.

## Examples

1) disable or enable warnings for specific rules
//@ts-disable TS1234 TS1235
//@ts-enable TS1234 TS1235

2) disable specific rules on a specific line
//@ts-disable-line TS1234 TS1235

3) disable specific rules on next line
//@ts-disable-next-line TS1234 TS1235

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
Duplicate of #19139 ❤️

**Comment by doberkofler** [comment]
@weswigham In my understanding #19139 only covers what I described unter 3 and I really believe, that a more complete and consistant solution should be adopted. My suggestion is based on eslint and has been proven to be very comprehensive.

**Comment by weswigham** [comment]
What you have here is a proposal for fixing the request at the root of #19139 - I'd try to keep discussion there, if possible.

**Comment by doberkofler** [comment]
@weswigham I understand and moved my suggestion to #19139 and would love to see some progress in this area.
Thank you!
