### ISSUE TITLE
DefinitelyTyped largely incompatible with ES6 emit due to export syntax

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#2929]
DefinitelyTyped is full of the old `export =` syntax. One random example I ran into:
https://github.com/borisyankov/DefinitelyTyped/blob/master/selenium-webdriver/selenium-webdriver.d.ts#L4847

But when I want to emit ES6, the compiler tells me I need to update that definition file to the new `export default` syntax. That might be fine for .d.ts files I own, but it's not reasonable to expect all of DefinitelyTyped to be updated by contributors.

I think one of these would be a good fix, in order:
1. Make a commit across all of DefinitelyTyped to update `export =` to `export default`. (assuming there is no legacy config where `export default` doesn't work.)
2. Allow `export =` syntax all the time, emit the right thing anyway
3. like 2. but using a compiler flag to opt-in

**Comment by danquirk** [comment]
This is definitely something we've talked about a bunch in relation to the ES6 module changes. In an ideal world we don't break what exists but also help pull people forward to ES6 style modules asap.

**Comment by alexeagle** [comment]
For now I think my only choice is to fork DefinitelyTyped and fix this in
all the typings I use.

**Comment by mhegazy** [comment]
The restriction in the compiler is not needed for ambient modules. we should remove it.

**Comment by mhegazy** [comment]
handled in #2929

**Comment by lazutkin** [comment]
:+1:

**Comment by ivogabe** [comment]
@mhegazy I think you meant #2935, since #2929 is this issue..

**Comment by mhegazy** [comment]
@ivogabe yes, you are correct. updating the comment. thanks!
