### ISSUE TITLE
SourceMaps do not correctly map external source files line and col values

### ISSUE THREAD

**Issue by petebacondarwin** [Microsoft/TypeScript#29300]
**TypeScript Version:**  3.2.2

The line in error is still in place on the master branch, so I expect this bug is still an issue on the latest TypeScript version.

**Search Terms:** sourcemaps, external file, emitPos, emitSourcePos, setSourceMapRange, invalid line col, synthesized nodes

**Issue**

While developing SourceMapped templates for the new Ivy renderer in Angular, I came across this problem.

We are using `setSourceMapRange(node, sourceMapRange)` to specify that synthesized nodes should map to spans in external template files. I.E. the `sourceMapRange.source` property is not the current `SourceFile` being transformed.

The code at 
https://github.com/Microsoft/TypeScript/blob/4a0bc59f77265ea116be8d9c5f16bb5185663a8c/src/compiler/emitter.ts#L4392
is computing the `line` and `character` positions based on the `currentSourceFile` rather than on the `sourceMapSource` file.

```ts
function emitPos(pos: number) {
  if (sourceMapsDisabled || positionIsSynthesized(pos) || isJsonSourceMapSource(sourceMapSource)) {
    return;
  }

  const { line: sourceLine, character: sourceCharacter } = getLineAndCharacterOfPosition(currentSourceFile!, pos);
  sourceMapGenerator!.addMapping(
    writer.getLine(),
    writer.getColumn(),
    sourceMapSourceIndex,
    sourceLine,
    sourceCharacter,
    /*nameIndex*/ undefined);
}
```

I believe that the call should be:

```ts
getLineAndCharacterOfPosition(sourceMapSource, pos);
```

**Expected behavior:**

The mapped `line` and `column`, computed from the `offset`, should be relative to the external file.

**Actual behavior:**

The mapped `line` and `column`, computed from the `offset`, are relative to the current source file, rather than the external file.

**Related Issues:** 

This functionality was originally created here https://github.com/Microsoft/TypeScript/issues/15935 to support the same use case in Angular.

**Comment by sheetalkamat** [comment]
@rbuckton How do we verify this? The original PR doesn't have any test.

**Comment by weswigham** [comment]
I think you could write a unittest with a custom transformer (like `unittests:: customTransforms` in `customTransforms.ts`) that integrates node whose origin is a different file into the tree. Probably.
