### ISSUE TITLE
tsconfig: using out option results in really ugly/duplicated output.

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2930]
I'm using a tsconfig file in our project: https://github.com/exceptionless/Exceptionless.Javascript and I'm  seeing the following behavior (Everything is in the same module, but multiple files..).

![image](https://cloud.githubusercontent.com/assets/1020579/7353128/e3f0da9c-ecd6-11e4-8efb-ad52791af2b2.png)

![image](https://cloud.githubusercontent.com/assets/1020579/7353130/e7d4585a-ecd6-11e4-9414-7207118fb70b.png)

I feel that all code should be placed into the same module region when it's generated.

**Comment by DanielRosenwasser** [comment]
That would be incorrect because we need to respect initialization order.

```TypeScript
module m {
    export var x = 10;
}

var y = 20;

function f(x: number) {
    return 2 * x;
}

module m { 
    export var z = f(x + y);
}
```

It would be inappropriate to place the initialization of `z` at the same location as `x` given that its value relies on `y`, which was initialized before it.

**Comment by niemyjski** [comment]
I'm not saying you shouldn't respect the initializing order, I'm just saying it feels insane that I need to have duplicated 

![image](https://cloud.githubusercontent.com/assets/1020579/7353729/726cc7fa-ecdb-11e4-8caf-e31546bc9261.png)

in my single module (one of those per file)... It could just place one around everything in that module file.. Please reopen this.. As you've just increased by javascript file size by N.

**Comment by mhegazy** [comment]
@niemyjski it is true that `var Exceptionless;

**Comment by niemyjski** [comment]
I'm talking about var Exceptionless and extra function wrappers

**Comment by niemyjski** [comment]
I wonder what the extra `var Exceptionless;` will do in existing/order browsers

**Comment by mhegazy** [comment]
fixing my comment. @niemyjski it is true that `var Exceptionless;` can be dropped. and it would make the code look cleaner. I am not sure i see the implementation cost vs the aesthetic return value .

**Comment by niemyjski** [comment]
It doesn't look like code I would write... And that is what typescripts supposed to do..

![image](https://cloud.githubusercontent.com/assets/1020579/7354152/b4c962ea-ecde-11e4-8d5c-f86c295c7081.png)

**Comment by mhegazy** [comment]
We have maintained an axiom not to change user code when possible. the problem with merging these scopes, is we will have to rename declarations if they conflict.

**Comment by niemyjski** [comment]
But you are using my tsconfig of all my dependencies so you should have all the info in the parse result to make the right decision.

**Comment by mhegazy** [comment]
closing in favor of #447
