### ISSUE TITLE
Invalid jsx preserved when `--jsx preserve` is specified

### ISSUE THREAD

**Issue by lizongze** [Microsoft/TypeScript#29304]
reappear case：
https://runkit.com/yuche/5c3339f07f9c020012d3e134

 ![image](https://user-images.githubusercontent.com/7202516/50807687-37646980-1336-11e9-8b5c-917f7b107a05.png)

in JSX preserve mode, TypeScript cannot emit the desired code. the emitted file contains invalid fragments.
```js
const instance: IFly = new (<any>Fly)();
```
`</>`left, causes syntax error
```js
42 |
43 | export default instance;

44 | </>);
| ^
45 |
```

**Comment by trotyl** [comment]
You're writing invalid TypeScript source code, the emission works well. See http://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-6.html#new-tsx-file-extension-and-as-operator for more information.

**Comment by lizongze** [comment]
Oh, I get it now. Thank you !
