### ISSUE TITLE
Function overload breaks generics

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#29312]
**TypeScript Version:**  3.1.6

**Search Terms:** overload function generic

**Code**

```ts
declare function identity <T extends unknown>(t: T): T
declare function identity (): undefined

declare class Option<A> {
  chain<B>(f: (a: A) => Option<B>): Option<B>;
}

// Actual type: <T>(option: Option<Option<T>>) => Option<{}>
// Expected type: <T>(option: Option<Option<T>>) => Option<T>
// Disabling second `identity` overload fixes it for some reason.
const optionFlatten = <T>(option: Option<Option<T>>) => option.chain(identity)
```

**Comment by Bludator** [comment]
I have yet another example:
```typescript
function Wrap<O extends (...any) => any>(a: O, params: Parameters<O>): void { }

let Bar: {
    Foo<K extends "FooBar">(a: K, b: number): void;
    //comment out this ↓ line:
    Foo(a: never): never;
};

//This should work:
Wrap(Bar.Foo, ["FooBar", 78])
```
[link to playground.](https://www.typescriptlang.org/play/#src=function%20Wrap%3CO%20extends%20(...any)%20%3D%3E%20any%3E(a%3A%20O%2C%20params%3A%20Parameters%3CO%3E)%3A%20void%20%7B%20%7D%0D%0A%0D%0Alet%20Bar%3A%20%7B%0D%0A%20%20%20%20Foo%3CK%20extends%20%22FooBar%22%3E(a%3A%20K%2C%20b%3A%20number)%3A%20void%3B%0D%0A%20%20%20%20Foo%3CK%20extends%20%22FooBar2%22%3E(a%3A%20K%2C%20b%3A%20boolean)%3A%20void%3B%0D%0A%20%20%20%20%2F%2Fcomment%20out%20this%20%E2%86%93%20line%3A%0D%0A%20%20%20%20Foo(a%3A%20never)%3A%20never%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2FThis%20should%20work%3A%0D%0AWrap(Bar.Foo%2C%20%5B%22FooBar%22%2C%2078%5D)%0D%0AWrap(Bar.Foo%2C%20%5B%22FooBar2%22%2C%20true%5D))

Again it uses just the last overload.

**Comment by jack-williams** [comment]
@Bludator That is a separate issue linked to the design of conditional type inference. When inferring from an overloaded function the last overload is always picked, so `Parameters` just picks up the last case which happens to be `never`.

See #21496

**Comment by RyanCavanaugh** [comment]
Inference only works with the last overload
