### ISSUE TITLE
Implicit type conversion of tuple [...T[]] to array T[]

### ISSUE THREAD

**Issue by egormkn** [microsoft/TypeScript#29311]
**TypeScript Version:**  3.3.0-dev.20190108

**Search Terms:** spread, rest, type conversion, tuple, array length

**Code**

```ts
type test1 = [...number[]]           // number[]     <-- Is it a feature?
type test2 = [number, ...number[]]   // [number, ...number[]]
type test3 = [number?, ...number[]]  // [number?, ...number[]]

type fixed1 = test1 & { length: 2 }  // number[] & { length: 2 }
type fixed2 = test2 & { length: 2 }  // [number, ...number[]] & { length: 2 }
type fixed3 = test3 & { length: 2 }  // [number?, ...number[]] & { length: 2 }

let var1: fixed1 = [0, 0]
/*  error TS2322: Type 'number[]' is not assignable to type 'fixed1'.
    Type 'number[]' is not assignable to type '{ length: 2; }'.
        Types of property 'length' are incompatible.
        Type 'number' is not assignable to type '2'. */
let var2: fixed2 = [0, 0] // OK
let var3: fixed3 = [0, 0] // OK
```

**Expected behaviour:**
Expected `[...number[]]` and `[number, ...number[]]` to have the same behaviour except that the latter requires at least one element in tuple.

**Actual behavior:**
`[...number[]]` is implicitly converted to `number[]` with the `length: number` field, that is incompatible with `length: 2` 
```
Error TS2322: Type 'number[]' is not assignable to type 'fixed1'.
    Type 'number[]' is not assignable to type '{ length: 2; }'.
        Types of property 'length' are incompatible.
        Type 'number' is not assignable to type '2'.
```

**Playground Link:** [:link:](https://www.typescriptlang.org/play/#src=type%20test1%20%3D%20%5B...number%5B%5D%5D%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20number%5B%5D%0D%0Atype%20test2%20%3D%20%5Bnumber%2C%20...number%5B%5D%5D%20%20%20%2F%2F%20%5Bnumber%2C%20...number%5B%5D%5D%0D%0Atype%20test3%20%3D%20%5Bnumber%3F%2C%20...number%5B%5D%5D%20%20%2F%2F%20%5Bnumber%3F%2C%20...number%5B%5D%5D%0D%0A%0D%0Atype%20fixed1%20%3D%20test1%20%26%20%7B%20length%3A%202%20%7D%20%20%2F%2F%20number%5B%5D%20%26%20%7B%20length%3A%202%20%7D%0D%0Atype%20fixed2%20%3D%20test2%20%26%20%7B%20length%3A%202%20%7D%20%20%2F%2F%20%5Bnumber%2C%20...number%5B%5D%5D%20%26%20%7B%20length%3A%202%20%7D%0D%0Atype%20fixed3%20%3D%20test3%20%26%20%7B%20length%3A%202%20%7D%20%20%2F%2F%20%5Bnumber%3F%2C%20...number%5B%5D%5D%20%26%20%7B%20length%3A%202%20%7D%0D%0A%0D%0Alet%20var1%3A%20fixed1%20%3D%20%5B0%2C%200%5D%0D%0A%2F*%20%20error%20TS2322%3A%20Type%20'number%5B%5D'%20is%20not%20assignable%20to%20type%20'fixed1'.%0D%0A%20%20%20%20Type%20'number%5B%5D'%20is%20not%20assignable%20to%20type%20'%7B%20length%3A%202%3B%20%7D'.%0D%0A%20%20%20%20%20%20%20%20Types%20of%20property%20'length'%20are%20incompatible.%0D%0A%20%20%20%20%20%20%20%20Type%20'number'%20is%20not%20assignable%20to%20type%20'2'.%20*%2F%0D%0Alet%20var2%3A%20fixed2%20%3D%20%5B0%2C%200%5D%20%2F%2F%20OK%0D%0Alet%20var3%3A%20fixed3%20%3D%20%5B0%2C%200%5D%20%2F%2F%20OK)

**Related Issues:** Haven't found anything about the same problem.

**Comment by weswigham** [comment]
In _theory_ they're the same, but in practice the simplification we do deletes the fact that the type should be a tuple at all, which causes the error. So, because of that, it might be best not to perform the inlining so as to preserve the tupleness of the type.

**Comment by weswigham** [comment]
> To fix the issue we should instead consider types that are array-like and have a length property of a numeric literal type to be tuple-like

And/or having numeric-named members (eg, `0: Thing`), as is our internal tuplish criteriea?

**Comment by Andarist** [comment]
The simplification at hand makes it hard to create a tuple constraint:
```ts
declare function test<T extends [...any[]]>(a: T): T

const res1 = test([1, 2]) 
//        ^? actual: number[], expected: [number, number]
```

There are different ways of dealing with this:
- the old weird trick of `T[] | [T]`
- `[T, ...T[]]` - it doesn't allow an empty tuple
- `[T?, ...T[]]` - it might look OK at first glance but when passing `T[K]` through a mapped type to some other type, it will assume that it might be `undefined` too, so this solution has some unintended caveats
- `const` type params in 5.0+ - this implies constness which isn't always desirable
- using the spread at argument position: `declare function test<T extends any[]>(a: [...T]): T`. This works exactly as expected but requires moving the "hint" to the argument position

It seems that the most "complete" way of defining a tuple constraint using tuple types is... `[T, ...T[]] | []`. It's quite cumbersome.
