### ISSUE TITLE
Treat NoSubstitutionTemplateLiteral same as a StringLiteral in import statement

### ISSUE THREAD

**Issue by ericbf** [microsoft/TypeScript#29318]
**TypeScript Version:** 3.2

**Search Terms:** NoSubstitutionTemplateLiteral, import template literal

**Code**

```ts
import * as ts from `typescript`
```

**Expected behavior:**

No error, as the NoSubstitutionTemplateLiteral should be treated just as a StringLiteral. Or potentially cannot find module error, depending on whether the module is installed.

**Actual behavior:**

Throws the error: "String literal expected"

**Playground Link:** 
[playground link](https://www.typescriptlang.org/play/#src=import%20*%20as%20ts%20from%20%22typescript%22)

**Related Issues:** 
This idea was touched on by #17704, but I guess this use case slipped through the cracks.

**Comment by ericbf** [comment]
@andy-ms @rbuckton you guys were involved in that other PR. Thoughts here?

**Comment by DanielRosenwasser** [comment]
The ECMAScript grammar currently only permits double- and single-quoted string literals in module specifiers:

https://tc39.github.io/ecma262/#prod-ImportDeclaration

> *ImportDeclaration* ::
> &nbsp;&nbsp;`import` *ModuleSpecifier*

https://tc39.github.io/ecma262/#prod-ModuleSpecifier

> > *ModuleSpecifier* ::
> &nbsp;&nbsp;*StringLiteral*

https://tc39.github.io/ecma262/#prod-StringLiteral

> > *StringLiteral* ::
> &nbsp;&nbsp;`"`*DoubleStringCharacters*<sub>opt</sub>`"`
> &nbsp;&nbsp;`'`*SingleStringCharacters*<sub>opt</sub>`'`

**Comment by ericbf** [comment]
This would be very useful for teams that opt to use template strings only rather than mixing quote marks (see [template literals are strictly better strings](https://ponyfoo.com/articles/template-literals-strictly-better-strings) for some reasoning).

I'll log a request with ECMA to add their [`NoSubstitutionLiteral`s](https://tc39.github.io/ecma262/#prod-NoSubstitutionTemplate) to their [`StringLiteral`](https://tc39.github.io/ecma262/#prod-StringLiteral) definition, but for the meantime, this change can safely be done in TS.

By safely, I mean that no matter their decision, it won't introduce breaking changes in the future to realign the grammars. If they decide to incorporate the suggestion, then TS is already up to date and can remain as is (possibly translating `NoSubstitutionTemplateLiteral`s in imports to standard strings). If they reject it, then TS has another benefit that "vanilla" ECMA does not.

TS treats its `NoSubstitutionTemplateLiteral`s the same as `StringLiteral`s elsewhere. From my research, this may be the remaining use case preventing teams from exclusively using template strings.

I'd implore you to explore this as something actually worth doing, rather than dismissing it solely on the fact that ECMA currently does not allow their equivalent token to be used this way.

**Comment by ericbf** [comment]
Created [#1399](https://github.com/tc39/ecma262/issues/1399) on the ECMA page.
