### ISSUE TITLE
Compiler Conditionals

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2931]
I'm currently using the tsconfig file in our project and I want to have two of them one that outputs es5 and one that outputs es6. Things are working great until I try and target es6 and run into the issue where I'm supplying a definition file for ES6-Promises.

```
[TsProject] Compiling Project Files...
[TsProject] c:/Code/Exceptionless.JavaScript/node_modules/typescript/bin/lib.es6.d.ts(4727,11): error TS2300: Duplicate identifier 'Promise'.
[TsProject] c:/Code/Exceptionless.JavaScript/node_modules/typescript/bin/lib.es6.d.ts(4812,13): error TS2300: Duplicate identifier 'Promise'.
[TsProject] typings/es6-promise/es6-promise.d.ts(10,15): error TS2300: Duplicate identifier 'Promise'.
[TsProject] typings/es6-promise/es6-promise.d.ts(40,16): error TS2300: Duplicate identifier 'Promise'.
[TsProject] typings/es6-promise/es6-promise.d.ts(70,2): error TS1203: Export assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'export default' instead.
[TsProject] Build completed with errors. Outputs generated.
[12:17:44] Finished 'typescript' after 2.76 s
```

**Comment by niemyjski** [comment]
What would be the best way to get around this?

**Comment by RyanCavanaugh** [comment]
It sounds like you're using a polyfill for ES6 promises?

One fix would be to pass the `--noLib` compiler flag and manually specify the ES5-only `lib.es5.d.ts` file as a compilation input. That ensures you're not using any other ES6-only features.

Alternatively, you could not include the ES6 polyfill .d.ts file in your ES6 build configuration.

**Comment by niemyjski** [comment]
Yes, I need to use promises in es5 land and most people have them but I just wanted the definition file imported. But when my build targets es6 that definition already exists and hence the error. I need to conditionally exclude it based on my target. How would I do this from a tsconfig.json file?? This work around doesn't seem end user friendly / straightforward and would make build setups more complicated.

**Comment by niemyjski** [comment]
I have no option to not include it as I'm putting it in my references.d.ts file and it's required for es5 or I get a ton of errors.

**Comment by RyanCavanaugh** [comment]
Another option is to include a reference to the ES5 lib.d.ts file in your references.d.ts file. That way you have the same set of input files between both compilation targets.

**Comment by niemyjski** [comment]
I don't want to do that because I want a fully targeted es6 build :(.

**Comment by RyanCavanaugh** [comment]
I don't understand how that's possible at the same time as wanting an ES5 build from the same codebase. Can you give some examples of constructs you want to compile one way in ES5 and another way in ES6 that *doesn't* work with any of the suggested fixes?

**Comment by niemyjski** [comment]
I have one set of files written in typescript. I want to target es5 and es6. The reason for this is because my library needs to be self contained and references an external es6 js library. In this scenario my es5 build will polyfil things but my es6 build won't (much smaller). So with this said when my build targets es5 via tsconfig.json I get a million errors saying No such promise definition but es6 target works. When I add the es6 promise definition to my references.ts file es5 build succeeds but my es6 build fails with duplicate def.

**Comment by niemyjski** [comment]
I was assuming that since things are transpiled that I could have one target es6 and it would just use the es6 syntax but if I targeted es5 it would convert it to use the es5 compliant code. For example the of operator...

**Comment by mhegazy** [comment]
in your tsconfig for es5, include your promise .d.ts, in your tsconfig for es6 do not. would that work?

**Comment by niemyjski** [comment]
That works!. Thank you.. Case of the mondays.

**Comment by niemyjski** [comment]
This seems to work but broke other things like unit tests which haven't been updated to the new format.
