### ISSUE TITLE
Incorrect type of 'this' of ES6 parent class static method in JS files

### ISSUE THREAD

**Issue by jameskeane** [Microsoft/TypeScript#29319]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Code**
The following is legal in JS, and correctly returns true (in the engines I've tested): 
```javascript
// example.js
class Base {
  static proof() {
    return (this === SubClass) && this.in_subclass();
  }
}

class SubClass extends Base {
  static in_subclass() {
    return true;
  }
}

console.log(SubClass.proof()); // === true
```
Run with: `tsc --checkJS --allowJS --noEmit --target es6 example.js`

**Expected behavior:**
No error, and correct types

**Actual behavior:**
```
example.js:3:40 - error TS2339: Property 'in_subclass' does not exist on type 'typeof Base'.
```
**Related Issues:** #20264, #24018 

**Workaround?**
The issue is more pronounced when the method or getter returns a dependant type (metaclass-esque). I've also tried the C++ style curiously recurring template pattern; doesn't work either. 
i.e.
```javascript
// neither works
declare class Base<T> {
  static proof(): Promise<T>;
  static proof(this: T): Promise<T>;
  static readonly proof_get: Promise<T>
}
declare class SubClass extends Base<SubClass> {
  subclass_method();
}

const sub = await SubClass.proof();
sub.subclass_method();

// error TS2302: Static members cannot reference class type parameters.
```

**Comment by weswigham** [comment]
See #5863 static this isn't currently polymorphic - you should go chime in there.

**Comment by jameskeane** [comment]
@weswigham Thanks, they are definitely related, but not quite the same.

This issue is reporting a bug in the TypeScript compiler's `--checkJS` mode (i.e. tsc incorrectly throws an error when evaluating the above (valid) JavaScript). This is an issue with the tsc compiler, _not_ the TS language.

If I'm not mistaken, #5863 is suggesting a change to the TypeScript language's semantics, which isn't necessary or prerequisite to fix this issue. Since (unlike TypeScript) ES6 static members _already have_ polymorphic `this`.

**Comment by weswigham** [comment]
The TS v JS distinction is non-existent for expression behavior - they're the same. You do seem to want `this` to behave like it's polymorphic in a static context (which yes, is how it works at runtime), and I'm saying there's an issue tracking that already~

**Comment by jameskeane** [comment]
> The TS v JS distinction is non-existent for expression behavior - they're the same.

Thanks for clarifying. It's the "Suggestion" and "In discussion" labels on #5863 that threw me off. Maybe they should be removed and have it relabeled as a Bug?

**Comment by weswigham** [comment]
Possibly. I'm not really familiar with why it was originally categorized as a suggestion.
