### ISSUE TITLE
Compiler should prevent assigning a function that takes a richer parameter

### ISSUE THREAD

**Issue by angelo-mollame** [Microsoft/TypeScript#29320]
**TypeScript Version:**  3.2.2

**Search Terms:** function parameter type check 

**Code**

```ts
interface Interface1 {
    a: string;
}

interface Interface2 extends Interface1 {
    b: string;
}

let function1: (x: Interface1) => string;

function1 = (x: Interface2) => x.b.toLowerCase();

const value = function1({a: "foo"}); // Error: Unable to get property 'toLowerCase' of undefined or null reference
```

**Expected behavior:**
The compiler prevents assigning to function1 a function that takes a richer parameter (of type Interface2) than the one that function1 will support (of type Interface1).

**Actual behavior:**
Compilation successful.

**Playground Link:** http://www.typescriptlang.org/play/#src=interface%20Interface1%20%7B%0D%0A%20%20%20%20a%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Interface2%20extends%20Interface1%20%7B%0D%0A%20%20%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Alet%20function1%3A%20(x%3A%20Interface1)%20%3D%3E%20string%3B%0D%0A%0D%0Afunction1%20%3D%20(x%3A%20Interface2)%20%3D%3E%20x.b.toLowerCase()%3B%0D%0A%0D%0Aconst%20value%20%3D%20function1(%7Ba%3A%20%22foo%22%7D)%3B%20%2F%2F%20Error%3A%20Unable%20to%20get%20property%20'toLowerCase'%20of%20undefined%20or%20null%20reference

**Comment by j-oliveras** [comment]
Already works: enable `strictFunctionTypes` (you can test it on playground). I see the error:
```
Type '(x: Interface2) => string' is not assignable to type '(x: Interface1) => string'.
  Types of parameters 'x' and 'x' are incompatible.
    Property 'b' is missing in type 'Interface1' but required in type 'Interface2'.
```
on function1 reassignment,

**Comment by ahejlsberg** [comment]
For reasons of backwards compatibility we default to bi-variant checking of parameter types, however we strongly recommend that new projects use `--strict` mode in which this is an error.

**Comment by angelo-mollame** [comment]
Thanks! What about this case?

```ts
interface Interface1 {
    a: string;
}

interface Interface2 extends Interface1 {
    b: string;
}

interface Interface3 {
    f1(x: Interface1): string;
}

function f2(x: Interface2): string {
    return x.b.toLowerCase()
}

const a: Interface3 = {
    f1: f2
}

const value = a.f1({a: "foo"}); // Error: Unable to get property 'toLowerCase' of undefined or null reference
```

The compiler doesn't seem to catch this case, even with strictFunctionTypes on.

http://www.typescriptlang.org/play/#src=interface%20Interface1%20%7B%0D%0A%20%20%20%20a%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Interface2%20extends%20Interface1%20%7B%0D%0A%20%20%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Interface3%20%7B%0D%0A%20%20%20%20f1(x%3A%20Interface1)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20f2(x%3A%20Interface2)%3A%20string%20%7B%0D%0A%20%20%20%20return%20x.b.toLowerCase()%0D%0A%7D%0D%0A%0D%0Aconst%20a%3A%20Interface3%20%3D%20%7B%0D%0A%20%20%20%20f1%3A%20f2%0D%0A%7D%0D%0A%0D%0Aconst%20value%20%3D%20a.f1(%7Ba%3A%20%22foo%22%7D)%3B%20%2F%2F%20Error%3A%20Unable%20to%20get%20property%20'toLowerCase'%20of%20undefined%20or%20null%20reference

**Comment by Nathan-Fenner** [comment]
Here's a reduced example, and it looks like a bug to me:

```ts
interface FuncPair {
    okay: (x: "a" | "b") => string;
    nope(x: "a" | "b"): string;
}

const example: FuncPair = {
    okay: (x: "a") => x, // error, like expected
    nope: (x: "a") => x, // no error!
}
```

It seems that "methods" on interfaces (as opposed to "function fields") don't have strict type checking, even with `strictFunctionTypes` enabled!
