### ISSUE TITLE
Narrowing 'this' type with multiple type predicates makes private properties inaccessible

### ISSUE THREAD

**Issue by sethfowler** [microsoft/TypeScript#29337]
**TypeScript Version:**  3.2

**Search Terms:** narrowing type predicates type guards intersection types union types private properties private members

**Code**

```ts
type DivElementlike = Elementlike & { tag: 'div' };
type SpanElementlike = Elementlike & { tag: 'span' };

class Elementlike {
    public tag: string;
    private _content: string;

    hasTag(t: 'div'): this is DivElementlike;
    hasTag(t: 'span'): this is SpanElementlike;
    hasTag(t: string): boolean { return this.tag === t; }

    doSomething() {
        if (this.hasTag('div')) {
            console.log(`_content is accessible here: "${this._content}"`);
        }
        if (this.hasTag('span')) {
            console.log(`_content is accessible here: "${this._content}"`);
        }
        if (this.hasTag('div') || this.hasTag('span')) {
            console.log(`_content is not accessible here, but it should be: "${this._content}"`);
        }
    }
}
```

**Expected behavior:**
This program should type check, and `this._content` should be accessible in the body of the last `if` statement in `doSomething()`.

**Actual behavior:**
`this._content` isn't accessible at that point in the program. The compiler complains that "Property '_content' does not exist on type '(this & Elementlike & {tag: 'div'}) | (this & Elementlike & {tag: 'span'})'."

Note that using these definitions for `DivElementlike` and `SpanElementlike` produces the same error (but without `Elementlike &` in the types), so the intersection type is not the source of the problem:
```ts
type DivElementlike = { tag: 'div' };
type SpanElementlike = { tag: 'span' };
```

**Playground Link:**  [A Playground demonstration of the problem is here.](http://www.typescriptlang.org/play/#src=type%20DivElementlike%20%3D%20Elementlike%20%26%20%7B%20tag%3A%20'div'%20%7D%3B%0D%0Atype%20SpanElementlike%20%3D%20Elementlike%20%26%20%7B%20tag%3A%20'span'%20%7D%3B%0D%0A%0D%0Aclass%20Elementlike%20%7B%0D%0A%20%20%20%20public%20tag%3A%20string%3B%0D%0A%20%20%20%20private%20_content%3A%20string%3B%0D%0A%0D%0A%20%20%20%20hasTag(t%3A%20'div')%3A%20this%20is%20DivElementlike%3B%0D%0A%20%20%20%20hasTag(t%3A%20'span')%3A%20this%20is%20SpanElementlike%3B%0D%0A%20%20%20%20hasTag(t%3A%20string)%3A%20boolean%20%7B%20return%20this.tag%20%3D%3D%3D%20t%3B%20%7D%0D%0A%0D%0A%20%20%20%20doSomething()%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.hasTag('div'))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(%60_content%20is%20accessible%20here%3A%20%22%24%7Bthis._content%7D%22%60)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20if%20(this.hasTag('span'))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(%60_content%20is%20accessible%20here%3A%20%22%24%7Bthis._content%7D%22%60)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20if%20(this.hasTag('div')%20%7C%7C%20this.hasTag('span'))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(%60_content%20is%20not%20accessible%20here%2C%20but%20it%20should%20be%3A%20%22%24%7Bthis._content%7D%22%60)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:**  There seem to be many issues around type predicates and type narrowing, but I couldn't find an existing example of this specific issue.

**Comment by weswigham** [comment]
Looks like unions need to include private/protected members if every union element contains them.

**Comment by RyanCavanaugh** [comment]
Works as expected now
