### ISSUE TITLE
Child method does not validate return type

### ISSUE THREAD

**Issue by gregolai** [Microsoft/TypeScript#29343]
**TypeScript Version:** latest

**Search Terms:** interface return type not being validated in derived class

**Code**

```ts
interface A {
	a: number;
}

function func(): A {
	return {
		a: 10,
		b: 'xyz' // correctly shows an error - 'b' does not exist in type 'A'
	}
}

abstract class Parent {
	abstract m(): A;
}

class Child extends Parent {
	m() {
		return {
			a: 10,
			b: 'xyz' // incorrectly shows NO error
		}
	}
}
```

**Expected behavior:**
`Child`s `m()` method should fail to validate as type 'A', similar to `func()` - please see the playground link below.

**Actual behavior:**
No error. Strange thing is, if I return a non-object, such as a number, in `Child`s `m()` method it shows a validation error. Please see playground link below.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0D%0A%09a%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20func()%3A%20A%20%7B%0D%0A%09return%20%7B%0D%0A%09%09a%3A%2010%2C%0D%0A%09%09b%3A%20'xyz'%20%2F%2F%20correctly%20shows%20an%20error%20-%20'b'%20does%20not%20exist%20in%20type%20'A'%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aabstract%20class%20Parent%20%7B%0D%0A%09abstract%20m()%3A%20A%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Parent%20%7B%0D%0A%09m()%20%7B%0D%0A%09%09return%20%7B%0D%0A%09%09%09a%3A%2010%2C%0D%0A%09%09%09b%3A%20'xyz'%20%2F%2F%20incorrectly%20shows%20NO%20error%0D%0A%09%09%7D%0D%0A%09%7D%0D%0A%7D)

**Comment by DanielRosenwasser** [comment]
`m()` in `Child` isn't affected by the type declared in `Parent`. The type of `m` in `Child` is inferred from the body, and then TypeScript checks to see if the inferred type is compatible with that of `m` in `Parent`.

**Comment by gregolai** [comment]
Ok, I'm reading about type widening and I see what's going on now. Basically what you said...`Child`s `m()` method doesn't specify a return type, so the type's being inferred from its content as `{ a: number, b: string }`. If I change `Child`s `m()` to `m(): A` I get the type validation, similar to `func()`.

It would be nice if `Child` was able to inherit expected return types without explicitly supplying them, but I suppose even traditional languages require specifying them.

I'll close the ticket.
Thank you.
