### ISSUE TITLE
brotli compression algorithm support for Typescript

### ISSUE THREAD

**Issue by psiva581** [Microsoft/TypeScript#29345]
Hi team,

Can you please provide compression and decompression support through brotli compression algorithm ?

https://www.npmjs.com/package/brotli

Regards,
Siva.

**Comment by j-oliveras** [comment]
What the relation with brotli and typescript compiler?

Is you want the type definitions ask to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/).
