### ISSUE TITLE
Promise typing incompatible between ES5 and ES6 emit

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#2934]
For `-t ES5`, I use the es6-promise typing here:
https://github.com/borisyankov/DefinitelyTyped/blob/00e7f3fede5f2df55b56c72f40a144824f0f0bfa/es6-promise/es6-promise.d.ts
which looks like
```
interface Thenable<R> {
	then<U>(onFulfilled?: (value: R) => U | Thenable<U>,  onRejected?: (error: any) => U | Thenable<U>): Thenable<U>;
}

declare class Promise<R> implements Thenable<R> {
	then<U>(onFulfilled?: (value: R) => U | Thenable<U>,  onRejected?: (error: any) => U | Thenable<U>): Promise<U>;
...
}
```

For `-t ES6` the Promise API is now in the `lib.es6.d.ts` distributed with TypeScript, which has:
```
interface Promise<T> {
    then<TResult>(onfulfilled?: (value: T) => TResult | Promise<TResult>, onrejected?: (reason: any) => TResult | Promise<TResult>): Promise<TResult>;
...
}
```

The main difference being the type inheritance from Thenable.

Now code that works against `-t ES5` gets a compile error with `-t ES6`:
```
angular2/src/facade/async.ts (31,25): Argument of type '(value: any) => T | Thenable<T>' is not assignable to parameter of type '(value: T) => T | Promise<T>'.
  Type 'T | Thenable<T>' is not assignable to type 'T | Promise<T>'.
    Type 'Thenable<T>' is not assignable to type 'T | Promise<T>'.
      Type 'Thenable<T>' is not assignable to type 'Promise<T>'.
        Types of property 'then' are incompatible.
          Type '<U>(onFulfilled?: (value: T) => U | Thenable<U>, onRejected?: (error: any) => U | Thenable<U>) =>...' is not assignable to type '<TResult>(onfulfilled?: (value: T) => TResult | Promise<TResult>, onrejected?: (reason: any) => T...'.
            Type 'Thenable<any>' is not assignable to type 'Promise<any>'.
```

and here is our use-site:
https://github.com/angular/angular/blob/master/modules/angular2/src/facade/async.ts

Also, it is a problem that the es6-promise.d.ts declares Promise as a class rather than an interface; that collides with the identifier declared in lib.es6.d.ts.

What is the right general strategy to deal with typings such that the same code can target both ES5 and ES6?

For this specific issue, it seems like the right answer is to change the DefinitelyTyped `es6-promise.d.ts` to match the shape declared in `lib.es6.d.ts`. Sound right?

**Comment by niemyjski** [comment]
+1

**Comment by mhegazy** [comment]
@rbuckton this will need to go in release-1.5 branch as well as master.

**Comment by mhegazy** [comment]
@niemyjski  and @alexeagle can you give the latest library file a try? https://github.com/Microsoft/TypeScript/blob/master/bin/lib.es6.d.ts

**Comment by Guria** [comment]
I have got a simmilar problem with `1.9.0-dev.20160429`.
I want to use es5 as target but rely on existing native Promise or polyfilled one.
So I started with this config (lib option here is reason to use 1.9.0): 
```json
{
  "compilerOptions": {
    "declaration": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "outDir": "lib",
    "target": "es5",
    "listFiles": true,
    "lib": ["es5", "dom", "es2015.promise"]
  },
  "exclude": [
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts",
    "lib",
    "tests"
  ]
}
```

It works fine until I try to pass array of promises to `Promise.all()`. I got an error:
```
error TS2345: Argument of type 'Promise<T>[]' is not assignable to parameter of type '[T | PromiseLike<T>, T | PromiseLike<T>]'.
  Property '0' is missing in type 'Promise<T>[]'.
```

**Comment by Guria** [comment]
just found a fix:
```ts
interface PromiseConstructor {
  all<T>(values: PromiseLike<T>[]): Promise<[T]>;
}
```
