### ISSUE TITLE
null check impact type infer cause strange error

### ISSUE THREAD

**Issue by meritozh** [microsoft/TypeScript#29367]
**TypeScript Version:**  3.2.2

**Search Terms:** type system null checker

**Code**

https://gist.github.com/meritozh/d36408e50e96b85d17d879b6e2a0334f#file-image-tsx-L78

**Expected behavior:**

Enable `strictNullChecks` with no error.

Type of specialized `R.findIndex` is:

```
(method) R.Static.findIndex<string>(fn: (a: string) => boolean, list: ReadonlyArray<string>): number (+1 overload)
```

**Actual behavior:**

Enable `strictNullChecks` with error:

```
Argument of type 'string[]' is not assignable to parameter of type 'ReadonlyArray<ReadonlyArray<string | undefined>>'.
  Type 'string' is not assignable to type 'ReadonlyArray<string | undefined>'. [2345]
```

Type of specialized `R.findIndex` is:

```
(method) R.Static.findIndex<ReadonlyArray<string | undefined>>(fn: (a: ReadonlyArray<string | undefined>) => boolean, list: ReadonlyArray<ReadonlyArray<string | undefined>>): number (+1 overload)
```

**Comment by meritozh** [comment]
Is there any progress?

**Comment by RyanCavanaugh** [comment]
@meritozh if you can give us an isolated repro we can look at this more quickly, but cloning external repos to investigate what is honestly unlikely to be a bug isn't our highest priority.

**Comment by meritozh** [comment]
Here is the demo repo. https://github.com/meritozh/ts-ramda-issue-demo.

I can understand it should pass `pattern.content!`, but why ts infer a two-dimensional array type?

**Comment by RyanCavanaugh** [comment]
We don't control the Ramda typings, which are extremely complex, and don't have resources to investigate issues that rely on them. Please log a new issue with a self-contained repro if you have evidence that a bug in TypeScript exist. Thanks!
