### ISSUE TITLE
Make strictNullCheck type checker smarter

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/TypeScript#29360]
## Search Terms

strictNullChecks
undefined is not assignable

## Suggestion
Have the strictNullChecker be smarter about types that the value could not be between when assigned and when the type is used.

## Use Cases

I have a number of functions where, instead of using a try/catch to handle something that's not there, I'd rather like to return undefined (e.g. pulling a non-existent key from a dictionary). While I appreciate the strictness it imposes, with the strictNullCheck on, my example as follows doesn't work

## Examples

```
function getVal(): string | undefined {
	return undefined;
}

function IsUndefined(obj) {
	return typeof obj === "undefined";
}

function stringFunction(val: string): string {
	return val + " example";
}

const val = getVal();
if (!IsUndefined(val)) {
	const strVal = val as string; //Would like to do without an explicit cast
	stringFunction(strVal);
}
```

The getVal function returns either a string or undefined, I tend to put check in place to see which it is and handle accordingly. Since the IsUndefined function will always return a boolean value, the Typescript type checker should be smart enough to realize that I've tested against the undefined type in IsDefined and that since we're in the true branch, it can only be a string value. As it is, val continues to be understood to be a string|undefined, so I have to cast to a string explicitly to use a string at that point.

Since I could replace the last four lines above with the following and it identify the type as being only a string at this point, this is already possible to a degree, but I'd like to see it taken further so I can put that check in another function and have the same effect.

```
if (typeof val !== "undefined") {
	stringFunction(val); //Correctly identifies this as a string
}
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by kitsonk** [comment]
This is already supported:

```ts
function IsUndefined(obj): obj is undefined {
	return typeof obj === "undefined";
}
```

See: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

**Comment by WhitWaldo** [comment]
@kitsonk I hadn't realized that was implemented, but I guess I'm looking for something a little less involved on my end. I've already written the original function that can return an undefined or string (as in the above example), or other type on my end.

Rather than create a whole separate function for each of the appropriate types, I'd instead like to see that TypeScript realize that the check was already done against the type and narrow from the existing logic instead of me providing that hint in a type guard.

The last paragraph of that section of the documentation appears to indicate that this would be done automatically and gives the example of an inline check:

> However, having to define a function to figure out if a type is a primitive is kind of a pain. Luckily, you don’t need to abstract typeof x === "number" into its own function because TypeScript will recognize it as a type guard on its own. That means we could just write these checks inline.

```
function padLeft(value: string, padding: string | number) {
    if (typeof padding === "number") {
        return Array(padding + 1).join(" ") + value;
    }
    if (typeof padding === "string") {
        return padding + value;
    }
    throw new Error(`Expected string or number, got '${padding}'.`);
}
```

What I'm looking for then is exactly this, but in a way that lets me put the type guard logic a separate reusable function.

**Comment by kitsonk** [comment]
@WhitWaldo what you are talking about is then covered by #9998.  The larger the scope of keeping type information, the larger memory footprint, etc.

But there are lots of other tools, like generics, which can be used to that user type guard functions don't require one for every type.  Couple that with conditional types and there is very little you can do.  I think you need to explore advanced types a bit more.

**Comment by WhitWaldo** [comment]
@kitsonk The explanation given in #9998 makes a lot of sense and given that I wasn't aware of type guards, I'll review the remaining documentation before responding more fully.
