### ISSUE TITLE
Why aren't static classes supported?

### ISSUE THREAD

**Issue by GarkGarcia** [Microsoft/TypeScript#29370]
I was just wondering why aren't static classes support, besides the lack of a real necessity (since they can be simply expressed as regular classes). Is there any issues that would arise from their implementation or is it just a case of avoiding to add unnecessary complexity to the language?

**Comment by DanielRosenwasser** [comment]
What do you mean by static classes? There are at least 2 languages I know of that define them differently. 🙂

**Comment by GarkGarcia** [comment]
> What do you mean by static classes? There are at least 2 languages I know of that define them differently. 🙂

Fair point hehe. I was thinking something along the lines of C#, basically just a class which whose methods and members are necessarily static.

**Comment by AnyhowStep** [comment]
A namespace?

**Comment by GarkGarcia** [comment]
> A namespace?

Almost, the difference is you can create custom getters and setters.

For example:
```ts
namespace Foo {
    // The user has complete access to Foo.baa1
    export let baa1: Baa;

    // The user has no access to Foo.baa2
    let baa2: Baa;

    /* The user can only read Foo.baa3, but at the same time it's 
    value cannot be altered by any of Foo's internal methods */
    export const baa3: Baa = new Baa();
}
```
As opposed to:
```ts
class Foo {
    // The user can only read Foo.baa, but it's value can be altered by Foo's internal methods
    private static _baa: Baa;

    static get baa(): Baa {
        return Foo._baa;
    } 

    static myMethod() {
        let newFoo: Baa;

        // Do some stuff

        Foo._baa = newFoo;
    }
}
```

**Comment by AnyhowStep** [comment]
A class with a private constructor?

**Comment by GarkGarcia** [comment]
> A class with a private constructor?

In C# (which is what I was thinking about when I made the question), static classes don't have constructors. The idea is that they are unique, they cannot be instantiated or inherited, they are sort of _object like_ classes.

>Static getters work.
>Static variables work.
>Static methods work.

Sure they do, as I sad in my original comment, static classes _can be simply expressed as regular classes_. I think the point of then is to be able to create custom setters and setter on _namespace like_ objects.

Anyway, this is not a feature request. I'm just asking the team what is the reason that prevented then from implementing it...

**Comment by AnyhowStep** [comment]
Having a private constructor that isn't used is the same as making the class uninstantiable and uninheritable.

Getters and setters on namespaces don't work but I don't know why, either =P

**Comment by GarkGarcia** [comment]
I think the reason you can't create getters and setters in a namespace is that TS namespaces are based on ES6 modules, which don't present such feature. @DanielRosenwasser maybe someone from the team can provide a clearer explanation.

**Comment by GarkGarcia** [comment]
> Having a private constructor that isn't used is the same as making the class uninstantiable and uninheritable.

Not really, you can still inherit from classes with a private constructor. Also, C# static classes can't inherit from any other class, for example:
```cs
public static class Foo : Baa {
    // No good. Static classes cannot inherit from any other class
} 
```
```cs
public static class Foo {
    // Some static stuff
}

public class Baa : Foo {
    // No good. No class can inherit from a static class
}
```
As opposed to:
```cs
public class Foo : Baa {
    private Foo() {
        // Some private constructor stuff
    }
    // Works just fine
} 
```
```cs
public class Foo {
    private Foo() {
        // Some private constructor stuff
    }
    // Some other stuff
}

public class Baa : Foo {
    // Works just fine
}
```
[Here](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members) are the docs. Anyway, @DanielRosenwasser I hope my question is now clearer...

**Comment by AnyhowStep** [comment]
In TypeScript, making the constructor private and not using the constructor achieves the same thing,

```ts
class A {
    private constructor () {}
}

//Constructor of class 'A' is private and only accessible within the class declaration.
const a = new A();
//Cannot extend a class 'A'. Class constructor is marked as private.
class B extends A {

}
```

**Comment by DanielRosenwasser** [comment]
Part of it is just that it's not part of ECMAScript, so adding it would've been compatibility hazard.

Then part of it is user demand - we haven't gotten a ton of it for this feature.

But mostly (and tying into the last point) I think it just doesn't seem that useful in JavaScript, where you can model this with an object literal anyway (which does support getters/setters), or a module or namespace if you really need that.

**Comment by RyanCavanaugh** [comment]
>  I'm just asking the team what is the reason that prevented then from implementing it...

C# has static classes because *all* code must live inside a class and not all code necessarily belongs inside an instantiable object. It's not "prevented from implementing", it's that the motivating reason for the concept doesn't exist in JS.

TS namespaces are sugar over the JavaScript [revealing object pattern](https://gist.github.com/zcaceres/bb0eec99c02dda6aac0e041d0d4d7bf2), not ES6 modules.
