### ISSUE TITLE
Add a "name" property to tsconfig.json to allow for naming of a project

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#2938]
This is an editor only addition to the tsconfig.json project, which allows an IDE to show a custom name for a tsconfig.json based project.

```json
{
    "name": "Language Service Server",
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "out": "../../built/local/tsserver.js",
        "sourceMap": true
    },
    "files": [
        "node.d.ts",
        "editorServices.ts",
        "protocol.d.ts",
        "server.ts",
        "session.ts"
    ]
}```

**Comment by mhegazy** [comment]
Tsconfig is based on directory based project system ideas; the name of the directory vibrating tsconfig should be your project name; this way we are not creating a set of parallel concepts.

**Comment by niemyjski** [comment]
I think you should support this suggestion and the concept of multiple tsconfig files by default. If we continue to go down this path, it kind of enforces two concepts:

1. Monolithic huge apps as you're telling vendors to only ever support one file in the root.
2. Use multiple repos / folders for shared code with copy and pasting.

**Comment by mhegazy** [comment]
I do not really understand the issue.. why would it be hard to configure your projects to have one per project? there are already parallels to this in npm with package.json, and git repos; these seem to be working fine with users, and do not lead to such issues.

the suggestion here is to add an additional "name" field. i am arguing that it is redundant as there is only a single tsconfig file allowed in a folder, so why have two "names" if you can have one. The suggestion to have multiple tsconfig files is tracked in another issue.

**Comment by paulvanbrenk** [comment]
My reasoning was that users may prefer a friendly name for their projects, since foldernames are usually short and may be artificially shortened due to max. path limitation on windows.

No strong preference either way, if others chime in I'll make the change..

**Comment by niemyjski** [comment]
@mhegazy you can have more than one per folder:https://github.com/Microsoft/TypeScript/issues/2869

**Comment by mhegazy** [comment]
but #2869 does not affect "project name" that would be used in an editor. with #2869, you are providing a custom tsconfig.json file, and the editors have no way of automatically picking these up. i would expect you are using some sort of .csproj in VS or a sublime project in sublime or other editor-specific project system to manage these, and in this case you can provide the name separably.

**Comment by mhegazy** [comment]
Adding an additional property to tsconfig should not be an issue. I do not think there is an action item here. please reopen if this is not the case.
