### ISSUE TITLE
Intellisense uses type's value instead of name.

### ISSUE THREAD

**Issue by Griffork** [Microsoft/TypeScript#2939]
We do some math stuff, and I've found that I'd like to provide more information about types to the other programmers by using the `type` keyword to rename/alias commonly used expressions:
E.g.
``` Typescript
type Vec2 = Array<number>|Float32Array;
```

The current problem is that if you hover over a variable that was typed using a `type`d type, you get the expanded declaration not the type name:

Expected:
``` Typescript
this.myvec2 //on hover shows type as Vec2
```
Actual Output:
``` Typescript
this.myvec2 //on hover shows type as Array<number>|Float32Array
```
Which means that we can't tell the difference between a vec2 and a mat3 at run time when we're using 20-odd variables for calculations.

<hr/>
Proposals:
Show type name & type.
``` Typescript
this.myvec2 //on hover shows type as Vec2(Array<number>|Float32Array)
```
Show only type name and have a way to "jump" to type:
``` Typescript
this.myvec2 //on hover shows type as Vec2, Vec2 is a hyper-link to the definition of the type.
//Alternatively have a button that "jumps to type definition"
```

The second is better for long type definitions, e.g. a definition of possible JSON values.

**Comment by bluong** [comment]
This has annoyed us a bit when coding in VSC. :+1: on this feature

**Comment by mhegazy** [comment]
This is unfortunately by design. type aliases are just, as the name suggests, aliases. they do not introduce new types, they just give them shorter names. you can have multiple type combinations using different type aliases, and doing a global search to find if this specific type combination has ever been given a name is not a feasible solution.

**Comment by OliverJAsh** [comment]
@mhegazy I'm seeing some odd behaviour around when TypeScript will and won't use the type alias. Here is an example:

Given:

``` ts
// test.ts
import {
    Response,
    // Either,
} from './test-dep';

let x: Response<string>;
x;
```

and

``` ts
// test-dep.ts
type Left<L> = { _L: L };
type Right<A> = { _A: A };
export type Either<L, A> = Left<L> | Right<A>;
export type Response<T> = Either<string, T>;
```

If you inspect the type of `x` in `test.ts`, the longform type will be shown:

```
let x: {
    _L: string;
} | {
    _A: string;
}
```

However, if `Either` is imported, the following will be shown:

```
let x: Either<string, string>
```

- Is this intended? If so, is this documented anywhere?
- How come the `Either` alias is used, but the `Response` alias is not?
- Could the type alias be used without requiring the import?

**Comment by mhegazy** [comment]
Type aliases are really alias.. they do not exist as types per say. in some cases if the type is only used throughout the code base only through the alias, we cache the alias name on the type, and use that to reverse lookup the alias when we write the type out.
