### ISSUE TITLE
Intersection of two generic params to form a third is not recognized as equivalent

### ISSUE THREAD

**Issue by ChuckJonas** [microsoft/TypeScript#29399]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

Intersection of generics

**Code**

```ts
let connect = <R1,R2, R = R1&R2 >(mapState2Props: (state) => R1, mapDispatch2Props: (dispatch: any) => R2): R => {
  let state = {};
  let dispatch = () => { };
  return { ...mapState2Props(state), ...mapDispatch2Props(dispatch)}
}
```

**Expected behavior:**
I would expect that this would be valid because I have defined `R = R1&R2` in the generic signature.   

**Actual behavior:**

Get an error `Type 'R1 & R2' is not assignable to type 'R'.` on the return statement.  I've also tried `R extends R1&R2` and I get the same error.

**Playground Link:** 

[Link](http://www.typescriptlang.org/play/#src=let%20connect%20%3D%20%3CR1%2CR2%2C%20R%20%3D%20R1%26R2%20%3E(mapState2Props%3A%20(state)%20%3D%3E%20R1%2C%20mapDispatch2Props%3A%20(dispatch%3A%20any)%20%3D%3E%20R2)%3A%20R%20%3D%3E%20%7B%0D%0A%20%20let%20state%20%3D%20%7B%7D%3B%0D%0A%20%20let%20dispatch%20%3D%20()%20%3D%3E%20%7B%20%7D%3B%0D%0A%20%20return%20%7B%20...mapState2Props(state)%2C%20...mapDispatch2Props(dispatch)%7D%0D%0A%7D)

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/5823

**Comment by ChuckJonas** [comment]
hmm ya that's a good point.  The goal here was to eventually get to where you could just specify the return type `R` and get type safety that `mapState2Props` & `mapDispatch2Props` combined would result in a valid `R` Object.

EG: 

```
interface IComponentProps{
  foo: string;
  doFoo: ()=>void
}
let props: IComponentProps = connect<IComponentProps>(
  (state) => { foo: state.foo },
  (dispatch) => {doFoo: () => dispatch('FOO')}
)
```

However... I'm not sure if that is even possible... Seem like you would need to instead define R1 & R2 as some subset of `R`, but they are dependent on each other...

**Comment by nmain** [comment]
Note that `R` could also be a completely unrelated type.  Default type arguments in generics are not constraints.

```ts
connect<{ a: string }, { b: number }, { c: boolean[] }>(() => ({ a: "a" }), () => ({ b: 3 }))
```
