### ISSUE TITLE
isNewIdentifierLocation is wrong in certain case, which messes up autocomplete

### ISSUE THREAD

**Issue by highco** [microsoft/TypeScript#29402]
**TypeScript Version:**  3.2.2

**Search Terms:** isNewIdentifierLocation, completion, autocomplete, typescriptServices

**Expected behavior:**
![image](https://user-images.githubusercontent.com/373616/51112513-2f596d80-17ff-11e9-97b3-bf3d80a665b4.png)
In this situation, `isNewIdentifierLocation` should be true, which means that typing “(“ in VS Code should not insert the autocomplete match.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/373616/51112783-21f0b300-1800-11e9-94e9-cf2b2dc3eae3.png)

`isNewIdentifierLocation` is false and VS Code incorrectly inserts the autocomplete match after typing “(“. This leads to a very annoying user experience in this situation.

In contrast, after adding a semicolon after “x = 7” in the previous example, the behaviour is correct.

**Comment by fatcerberus** [comment]
In general I've found VSCode's JS/TS autocomplete to be far too aggressive.  This is just the tip of the iceberg for over-eager completions in my experience.  My favorite is when writing a type annotation for a type I haven't defined/imported yet and it changes it to something completely unrelated behind my back...
