### ISSUE TITLE
TS allows typeof foo === undefined & typeof foo === null

### ISSUE THREAD

**Issue by tommytroylin** [Microsoft/TypeScript#29405]
**TypeScript Version:**  3.2.2

**Search Terms:** typeof 

**Code**

```ts
typeof window == null
typeof window == undefined
```

**Expected behavior:**
compiler error
> This condition will always return 'false' since the types '"string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"' and 'null' have no overlap.

**Actual behavior:**
no error

**My opinion:**

This behavior allows quick `null/undefined` checks regardless of type information.

but  `typeof foo === undefined` needs to be considered as a typo much more.

**Comment by jack-williams** [comment]
Duplicate of #29200

**Comment by fatcerberus** [comment]
> but `typeof foo === undefined` needs to be considered as a typo much more.

The compiler doesn't special-case `typeof` in an expression for the purpose of type checking.  It looks the same to the compiler as, e.g., `stringVar === undefined` (which is deliberately allowed, as you've pointed out).

**Comment by tommytroylin** [comment]
thanks @jack-williams for references
