### ISSUE TITLE
White screen of death on iOS caused by PushSubscription used as an interface

### ISSUE THREAD

**Issue by Shiroh1ge** [Microsoft/TypeScript#29419]
My app stopped working on iOS (I just get white screen when opening the site) and I've been debugging it for the last couple of days. Turns out one of the interfaces from `lib.webworker.d.ts` - `PushSubscription` has been causing it to crash for some reason. I'm not exactly sure what's happening, and I'm not sure if it's a bug at all and whether this is the right place to post it, but if it helps someone else facing the same issue it's fine for me. This is an example of my code:

```
    pushSubscriptionUpdate(subscription: PushSubscription) {
        return {
            type: this.actions.PUSH_SUBSCRIPTION_UPDATE,
            payload: subscription
        };
    }
```

As soon as I changed the type to `subscription: any` my app worked again on iOS.

**Expected behavior:**
My app to work on iOS

**Actual behavior:**
I get white screen when I tried to load it.

**Comment by RyanCavanaugh** [comment]
Changing the type annotation doesn't change the emitted JS, which is the only thing that matters in terms of runtime behavior.

If you find a concrete case where the JS emit is different, then there's a (serious) bug here, but most likely when we see issues like this, it's just a stale build running and changing some code the editor and rebuilding "fixed" it.
