### ISSUE TITLE
Cannot extract/filter property keys from this.

### ISSUE THREAD

**Issue by superamadeus** [microsoft/TypeScript#29413]
**TypeScript Version:**  3.3.0-dev.201xxxxx (tested with `typescript@next` -v: 3.3.0-dev.20190112)

**Search Terms:** keyof this, mapped this type, filter this properties, filter this property keys

**Code**

```ts
/**
 * Get the property keys of properties on T which are of type U.
 */
type ExtractPropKeysOfType<T, U> = {
  [k in keyof T]: T[k] extends U ? k : never
}[keyof T];

/**
 * Pick the properties on T which are of type U.
 */
type PickPropsOfType<T, U> = Pick<T, ExtractPropKeysOfType<T, U>>;

function pickNumericProps<T>(t: T): PickPropsOfType<T, number> {
  return {} as any;
}

class Example {
  public a!: number;
  public b!: string;
  public c!: 11;

  public ownNumericProps(): PickPropsOfType<this, number> {
    return pickNumericProps(this);
  }

  public consumerMethod(): void {
    type OwnNumericPropKeys = ExtractPropKeysOfType<this, number>; // it seems that TS cannot resolve this type when applied to `this`.

    pickNumericProps(this).a; // ERROR: Property 'a' does not exist on type 'Pick<this, { [k in keyof this]: this[k] extends number ? k : never; }[keyof this]>'.
    this.ownNumericProps().a; // ERROR: Property 'a' does not exist on type 'Pick<this, { [k in keyof this]: this[k] extends number ? k : never; }[keyof this]>'.
  }
}

const example = new Example();
example.ownNumericProps().a; // works as expected
pickNumericProps(example).a; // works as expected
```

**Expected behavior:**
The type of `pickNumericProps(this)` should be `{ a: number, c: 11 }`.

**Actual behavior:**
The type of `pickNumericProps(this)` is unresolved (? not sure how to describe it).

**Playground Link:** [Playground link](https://www.typescriptlang.org/play/index.html#src=%2F**%0D%0A%20*%20Get%20the%20property%20keys%20of%20properties%20on%20T%20which%20are%20of%20type%20U.%0D%0A%20*%2F%0D%0Atype%20ExtractPropKeysOfType%3CT%2C%20U%3E%20%3D%20%7B%0D%0A%20%20%5Bk%20in%20keyof%20T%5D%3A%20T%5Bk%5D%20extends%20U%20%3F%20k%20%3A%20never%0D%0A%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Pick%20the%20properties%20on%20T%20which%20are%20of%20type%20U.%0D%0A%20*%2F%0D%0Atype%20PickPropsOfType%3CT%2C%20U%3E%20%3D%20Pick%3CT%2C%20ExtractPropKeysOfType%3CT%2C%20U%3E%3E%3B%0D%0A%0D%0Afunction%20pickNumericProps%3CT%3E(t%3A%20T)%3A%20PickPropsOfType%3CT%2C%20number%3E%20%7B%0D%0A%20%20return%20%7B%7D%20as%20any%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Example%20%7B%0D%0A%20%20public%20a!%3A%20number%3B%0D%0A%20%20public%20b!%3A%20string%3B%0D%0A%20%20public%20c!%3A%2011%3B%0D%0A%0D%0A%20%20public%20ownNumericProps()%3A%20PickPropsOfType%3Cthis%2C%20number%3E%20%7B%0D%0A%20%20%20%20return%20pickNumericProps(this)%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20consumerMethod()%3A%20void%20%7B%0D%0A%20%20%20%20type%20OwnNumericPropKeys%20%3D%20ExtractPropKeysOfType%3Cthis%2C%20number%3E%3B%20%2F%2F%20it%20seems%20that%20TS%20cannot%20resolve%20this%20type%20when%20applied%20to%20%60this%60.%0D%0A%0D%0A%20%20%20%20pickNumericProps(this).a%3B%20%2F%2F%20ERROR%3A%20Property%20'a'%20does%20not%20exist%20on%20type%20'Pick%3Cthis%2C%20%7B%20%5Bk%20in%20keyof%20this%5D%3A%20this%5Bk%5D%20extends%20number%20%3F%20k%20%3A%20never%3B%20%7D%5Bkeyof%20this%5D%3E'.%0D%0A%20%20%20%20this.ownNumericProps().a%3B%20%2F%2F%20ERROR%3A%20Property%20'a'%20does%20not%20exist%20on%20type%20'Pick%3Cthis%2C%20%7B%20%5Bk%20in%20keyof%20this%5D%3A%20this%5Bk%5D%20extends%20number%20%3F%20k%20%3A%20never%3B%20%7D%5Bkeyof%20this%5D%3E'.%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20example%20%3D%20new%20Example()%3B%0D%0Aexample.ownNumericProps().a%3B%20%2F%2F%20works%20as%20expected%0D%0ApickNumericProps(example).a%3B%20%2F%2F%20works%20as%20expected%0D%0A)

**Related Issues:** 
Couldn't find any

**Comment by RyanCavanaugh** [comment]
> The type of `pickNumericProps(this)` should be `{ a: number, c: 11 }`.

That step of logic isn't correct. `this` could be, for example,
```ts
class Example2 extends Example {
  a: 10;
  b: number;
}
```
which means `pickNumericProps(this)` would "actually" be `{ a: 10, b: number, c: 11 }`.

**Comment by superamadeus** [comment]
@RyanCavanaugh Correct. That's the desired behavior I'm looking for when extending the base class. Still, the type seems unable to resolve itself. Is there a term for that?

**Comment by weswigham** [comment]
The type _is_ resolved - it's generic, since `this` could be any arbitrary subtype, so any code you write needs to handle any arbitrary subtype.

**Comment by superamadeus** [comment]
@weswigham Well, shouldn't it be safe to assume that in my example the type of `pickNumericProps(this)` should _extend_ `{ a: number, c: 11 }`? So accessing `a` or `c` should not throw an error?

**Comment by Nathan-Fenner** [comment]
I think this is essentially the same as #29225.

- `this` types are really generic parameter types under-the-hood
- `this` has a constraint: `this extends {a: number, c: 11}`
- but constraints are (at least currently, due to a design limitation) ignored when simplifying conditional types:

```ts
type Example<T extends string> = T extends string ? "yes" : "no";
```
This example is "stuck" until you actually instantiate it with a particular `T`.

The result is that you get a "stuck" type that cannot be simplified, and therefore the compiler can't determine that it actually has the key you're expecting.

The problem is really caused by situations like:

```ts
type Example2<T extends {x: any}> = T extends {x: string} ? "yes" : "no"
```

The problem here is that if `T = {x: number}`, then `T extends {x: any}` but the conditional should evaluate to *no*, even though `{x: any}` is a subtype of `{x: string}`. This is basically brought about by `any` making the type system unsound, but I think it may possibly be extended toward other cases as well.

I think it may be possible to lift this design limitation, but only in some cases (where the constraint-bound can be fully simplified with no "stuck" mapped or conditional types, where no "`any`" types occur, ...).

**Comment by superamadeus** [comment]
@Nathan-Fenner I appreciate the reference and explanation. 

I'd love to see some of the more straightforward constraints handled more thoroughly, but I understand why the design limitation is there.

I mean, I'd __really__ love to see that. I have been working on an api that depends on being able to conditionally map against `keyof this` but for now instead of omitting properties I'm just mapping them to `never`, so I end up with this: `PickNumericProps<this>; // { a: number, b: never, c: 11 }`.
