### ISSUE TITLE
Enums don't work with TypeScript 1.5.0-alpha properly

### ISSUE THREAD

**Issue by panuhorsmalahti** [Microsoft/TypeScript#2941]
I noticed a breaking change while testing TypeScript 1.5.0-alpha. In 1.4.1, the enum's are replaced with numerical values in the JavaScript output. In 1.5.0-alpha, they're not compiled at all.

```
// mylib.d.ts
declare module Test {
	export enum MyEnum {
		foo = 0,
		bar = 1
	}
}
```

```
// test.ts
var value = Test.MyEnum.bar;
```

Expected output test.js (using TypeScript 1.4.1):
```
var value = 1 /* bar */;
```

Actual output test.js (using TypeScript 1.5.0-alpha):
```
var value = Test.MyEnum.bar;
```

If this is not a bug, I'm not sure how I can use enums which are in a module with TypeScript 1.5.x. I compiled with 'node node_modules\typescript\bin\tsc test.ts mylib.d.ts'.

**Comment by jonathandturner** [comment]
Have you tried using const enums?  Because of the cleanup in enums, some of the automatic inlining was moved out.  You can get it back by using a 'const enum', which always inlines:

```TypeScript
// mylib.d.ts
declare module Test {
    export const enum MyEnum {
        foo = 0,
        bar = 1
    }
}

var x = Test.MyEnum.bar;
```

**Comment by RyanCavanaugh** [comment]
See http://stackoverflow.com/a/28818850/1704166, specifically the "Common Errors" section.

**Comment by panuhorsmalahti** [comment]
Thanks, adding 'const' fixed the issue. I think there should be a breaking change documentation for 1.5.0 release.

**Comment by mhegazy** [comment]
Please see the breaking change documentation for TypeScript 1.5: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#enum-reference-in-lining-changes
