### ISSUE TITLE
Investigate setting the default resolution strategy to Node

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#29416]
* [ ] Investigate existing `tsconfig.json`s that target esXXXX` and have no explicit/implied resolution strategy.
* [ ] Determine the downstream effects to a change to defaults
* [ ] Determine if this change outweighs the potential breakage
* [ ] Implement if appropriate

**Comment by TheLarkInn** [comment]
// subscribe

**Comment by DanielRosenwasser** [comment]
Duplicate of #11434.

**Comment by RyanCavanaugh** [comment]
@TheLarkInn FYI

![image](https://user-images.githubusercontent.com/6685088/51210272-32b82c00-18c7-11e9-96e6-478b867e3ef2.png)

(this cuts down on Notifications we have to read)
