### ISSUE TITLE
Function return value types not inferred in some cases

### ISSUE THREAD

**Issue by psavur** [Microsoft/TypeScript#29411]
**TypeScript Version:**  3.3.0-dev.20190112

**Search Terms:** function return type

**Code**
 See code below which has a function returning a Promise<HelloInterface | undefined>
The calling code only infers the type to be HelloInterface.

```ts
class Example1 {
  public testFunction1(): void {
    this.getResponse().then((value: HelloInterface) => {  // Expected tsc to infer this to be value: HelloInterface | undefined 

      console.log(value.property1);  // Potential runtime error as value can be undefined.
    });
  }

  private getResponse(): Promise<HelloInterface | undefined> {
    return Promise.resolve({ "property1": "value1" });
  }
}

interface HelloInterface {
  "property1": string;
}

```

**Expected behavior:**
1) value should have inferred type as HelloInterface | undefined. 
This will force me to handle the case where it is undefined in the caller.

**Actual behavior:**
value has type HelloInterface
There will be a runtime error when we access say value.property1 when value is undefined.

**Playground Link:** 
Paste above code in vscode editor. 
I would expect vscode editor to indicate an error for value possibly being undefined.

** Other Observations **
 The same works if the function return type is say Promise<HelloInterface | string>
 It appears this is seen when we have 'undefined' as one of the return value types.

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Sounds like you have `strictNullChecks` off - enable this option to have TS check for `null` / `undefined` values

**Comment by ajafff** [comment]
And do you have `strictFunctionTypes` enabled?

**Comment by psavur** [comment]
@ajafff  Yes, it was `strictFunctionTypes`. Thanks, closing this.
