### ISSUE TITLE
Create JSX Text with factory

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#29425]
## Search Terms
Tsx, Factory

## Suggestion
i'd like to create a tsx ast by factory, but i cann't make it easy

1. JSXText Node have not the factory and there are not text hold in it 
2. JsxFragmentOpenning and JSXFragmentClose*** Node do not have the factory too 

- could we extend JSXText that such a JSXTextWithText?
- could we writeup more factory (JsxFragmentOpenning )

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ajafff** [comment]
To correctly create synthesized JsxText Nodes, there needs to be a `text` property on `JsxText`. Currently there's no property with information about the content of this node.

Adding such a property also requires changes in the parser.

**Comment by weswigham** [comment]
(It's probably correct to move JSX text into the category of literals and give it an updatable `value` member.)
