### ISSUE TITLE
Renaming of string literal types

### ISSUE THREAD

**Issue by SebastianSolidwork** [Microsoft/TypeScript#29429]
I'd like to rename foo1 to foo3 and see it replaced anywhere its been used.

![image](https://user-images.githubusercontent.com/22794134/51185150-a57cd380-18d6-11e9-900c-c6fc05e449e2.png)
```
    function renamefoo(bar: 'foo1' | 'foo2') {
        console.log(bar);
    }

    renamefoo('foo1');
```
Renaming just one is reconignized by the transpiler/compiler
![image](https://user-images.githubusercontent.com/22794134/51186003-dd851600-18d8-11e9-8c44-a78e56a2a5f3.png)

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Here's the response I see with TS 3.3:

```
[Trace  - 10:45:09 AM] Response received: rename (145). Request took 2 ms. Success: true 
Result: {
    "info": {
        "canRename": false,
        "localizedErrorMessage": "You cannot rename this element."
    },
    "locs": [
        {
            "file": "/Users/matb/projects/san/x.ts",
            "locs": [
                {
                    "start": {
                        "line": 1,
                        "offset": 11
                    },
                    "end": {
                        "line": 1,
                        "offset": 15
                    }
                },
                {
                    "start": {
                        "line": 7,
                        "offset": 12
                    },
                    "end": {
                        "line": 7,
                        "offset": 16
                    }
                }
            ]
        }
    ]
}
```

Looks like we have both an error and a set of `locs`

**Comment by RyanCavanaugh** [comment]
It's extremely unclear what should happen to other instances of the same string literal type, or exactly which expression-space string literals should be changed. Rejecting renames at both locations is the intended behavior to prevent confusion.

A text-level search/replace for `"foo1"` is the suggested thing for people to do so they understand exactly what's going to happen.

**Comment by RyanCavanaugh** [comment]
> Would you provide me a link so i can dive deeper into that topic?

Which topic?

**Comment by SebastianSolidwork** [comment]
@RyanCavanaugh A link to the scenarios, best with code examples, you wrote about.
Replacing the same string 20-100 times isn't that fun.

**Comment by aleclarson** [comment]
> It's extremely unclear what should happen to other instances of the same string literal type, or exactly which expression-space string literals should be changed.

Can this be elaborated on please?

**Comment by braebo** [comment]
Adding this feature is a no-brainer from where I'm sitting — the current behavior feels like it _should_ be a bug... but like @aleclarson, I don't really understand what the explanation is supposed to mean.
