### ISSUE TITLE
this context in Ajax 

### ISSUE THREAD

**Issue by ppumkin** [Microsoft/TypeScript#2942]
I am using jQuery AJAX to pass in additional data with the settings. I have read various post but nothing that solved this problem.

       .ajax({
            url: priceUrl,
            type: "GET",
            datatype: "json",
            contentType: "application/json; charset=utf-8",
            aadvancedPayments: this.AdvancedPayments(),
            aadvancedPayments: this.SubsequentPayments(),
            success: (price) => {
                var _n: number = price;

                if (_n != 0) { 

                    if (this.aadvancedPayments === undefined)
                        this.AdvancedPayments(_.findWhere(_advancedPayments, { Value: "6" }).Key);
                    if (this.ssubsequentPayments === undefined)
                        this.SubsequentPayments(_.findWhere(_subsequentPayments, { Value: "23" }).Key);

I get an error in TypeScript "Squiggly Line" that aadvancedPayments and aadvancedPayments does not belong the viewmodel, in the success method. I am working in. I admit, I am a newbie here going through somebody elses mess.

I save it and it generates the JS and in debug, low and behold, as I expected the additional settings are there while debugging in Chrome as the AJAX context not the viewmodel context...?! Confucius say, whaaa? 

But I CANNOT compile the Solution Now because of those two errors.

I know this is not an actual bug **but it is a problem**. Is there a way to tell TS in VS that I am accessing a `dynamic` property and it should just ignore any VS errors.

something like dynamic keyword somewhere ...

`(dynamic)this.aadvancedPayments `

**Comment by hogan** [comment]
(<any>this).aadvancedPayments is equivalent of dynamic in C#, but that will not solve your problem.

I suggest you to make regular properties before .ajax (or inside the response handler):
```
var aadvancedPayments = this.AdvancedPayments();
var aadvancedPayments = this.SubsequentPayments();
```
Then in the response handler you use these variables.

**Comment by ppumkin** [comment]
Thanks for response. I put those two lines Before AJAX but still errors in the success.
If I put those in the success, then they always 'undefined'

Is it something to do with the fat arrow?

`success: (price) => {`

I read a suggestion to just use

`success: function(price) { `

but that looses the TS model context.. so how would I call a function back since VS doesn't error anymore but the this context is now the AJAX one in chrome without the viewmodel properties... ?

**Comment by ppumkin** [comment]
Ahhh, smoke and mirrors :8ball: 

                   if (this['aadvancedPayments'] === undefined)
                        this.AdvancedPayments(_.findWhere(_advancedPayments, { Value: "6" }).Key);
                    if (this['ssubsequentPayments']  === undefined)
                        this.SubsequentPayments(_.findWhere(_subsequentPayments, { Value: "23" }).Key);

This solved the VS compilation issue and JavaScript is just fine and dandy with string key accessors.

So simple.

**Comment by ppumkin** [comment]
nope. this is really doing my nutter in.

When I run the code normally the assigned value is undefined, but in the console, when I copy and past and run the code, straight after the line of code that was just executes... it assigns the value!!! WTF?! :((((((((((((((
I keep getting NaN or undefined. Is there no end to this chaos.

So annoying

**Comment by hogan** [comment]
`this` in TS is usually different from `this` in JS. You can see that in JS file generated from TS.

If you really want to use it the way you posted, change `(price) => {` to `function(price) {`.

Anyways, you are missing the benefits of static code analysis in TS.

**Comment by mhegazy** [comment]
Looks like there is on action/information needed in this issue. closing.
