### ISSUE TITLE
Doc bug in function section.

### ISSUE THREAD

**Issue by EvanCarroll** [Microsoft/TypeScript#29436]
In the docs, it says

> In playing with the example, you may notice that the TypeScript compiler can figure out the type if you have types on one side of the equation **but not the other**:
> ```
> // myAdd has the full function type
> let myAdd = function(x: number, y: number): number { return  x + y; };
> 
> // The parameters 'x' and 'y' have the type number
> let myAdd: (baseValue: number, increment: number) => number =
>     function(x, y) { return x + y; };
> 
> ```

It seems to me that *"not the other"* is incorrect. I think what is meant to be said is *"not both"*. It seems from the documentation that typescript can infer the type of `myAdd` from the function, or infer the type of the arguments in the function from the type of `myAdd`, but not infer the types of `x` and `y` in isolation of any type declaration.

It may be worth mentioning the reason here too: why it can't infer the types of both -- presumably because the `+` operator is polymorphic.

**Comment by RyanCavanaugh** [comment]
If types are present on both sides, then there's nothing left to figure out.

It's like saying in a room full of a dozen people, I can figure out the last name if given a first name, or the first name if given a last name, ... but not both?

**Comment by EvanCarroll** [comment]
Interesting and compelling example. Perhaps that's the oversight -- I don't read "but not the other" to mean that TypeScript just accepts explicit typing on both sides. For me the wording is just awkward and causes confusion. Consider,

> It's like saying in a room full of a dozen people, I can figure out the name if you provide the first name, or last name **but not the other**.

That's how I read it currently. Perhaps though we could skirt the whole issue by rewording entirely,

> In playing with the example, you may notice that the TypeScript compiler can figure out the types absent from either side, with the types present on the other.

**Comment by ypercube** [comment]
Suggestion:

> In playing with the example, you may notice that the TypeScript compiler can figure out the type if you have types on one side of the equation.

**Comment by fatcerberus** [comment]
This is a pretty common turn of phrase, I tought.  "There's something on side of the fence, but not the other".  The general meaning is that there are two pigeonholes, but only one has something in it--without specifying which one that is (because it's not relevant).

**Comment by fatcerberus** [comment]
I'll agree the wording in this case is awkward, though.  This would probably be clearer:
> In playing with the example, you may notice that the TypeScript compiler can figure out the type **even if you only have types on one side of the equation:**
