### ISSUE TITLE
Signature assignability doesn't check for Function-conflicting properties

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#29449]
```ts
declare const f: { (): number, length: string, call: number };
function useF(g: () => number) {
  g.call(g.length)
}
```

**Expected behavior:**
`f` is not assignable to `g` because its `length` and `call` properties are not assignable to `Function.length` and `Function.call`.

**Actual behavior:**
No error. Typescript's signature assignability check ignores Function properties.

**Comment by sandersn** [comment]
This has been a hole forever so I'm not sure whether it's worth fixing. But it's definitely wrong!

**Comment by fatcerberus** [comment]
I assume the cause of the problem here is that TypeScript sees that both types have call signatures, those turn out to be compatible and the typechecker gives the all-clear without the usual structural compatibility checks?

**Comment by sandersn** [comment]
Yep, `length` and `call` are treated as excess properties. The fact that `g: () => number` inherits length and call from Function is ignored.

**Comment by RyanCavanaugh** [comment]
Looks like no one has really hit this.
