### ISSUE TITLE
Support InputEvent interface in libs

### ISSUE THREAD

**Issue by Christian24** [Microsoft/TypeScript#29441]
## Search Terms

input event
InputEvent

## Suggestion
TypeScript so far does not have a type definition of InputEvent (https://developer.mozilla.org/en-US/docs/Web/API/InputEvent). Even though there are some bugs concerning browser support, I would still say it is supported widely enough (https://caniuse.com/#feat=input-event) to be part of TypeScript's libs. So, far there only is a type definition available through `@types/dom-inputevent` 

## Use Cases
Working with input elements in HTML5. It's a feature of HTML5 and thus should be supported.

## Examples

```typescript
(event: InputEvent) => this.value = event.currentTarget.value;
```

## Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [x ] This could be implemented without emitting different JS based on the types of the expressions
* [x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We don't add definitions into the built-in lib.dom until they leave the Experimental phase.

**Comment by Christian24** [comment]
Okay, thanks. I understand. However, in this case I do not really agree, InputEvent is available since IE9, so web developers have had lots of time to use it, so it is desirable to have typing support for it.

**Comment by akoidan** [comment]
Edge 15 doesn't have it :(

**Comment by michahell** [comment]
Why is this something that is in 'Experimental' phase?
