### ISSUE TITLE
Support 3rd-party Assertion Libraries

### ISSUE THREAD

**Issue by jedmao** [Microsoft/TypeScript#2944]
There's a library written by @gcanti called [tcomb-ats](https://github.com/gcanti/tcomb-ats), which is a 3rd-party assertion library for AtScript. Now that [AtScript has been replaced with TypeScript](http://blogs.msdn.com/b/typescript/archive/2015/03/05/angular-2-0-built-on-typescript.aspx), does that change the [TypeScript Design Non-Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals) in any way? Would support for 3rd-party assertion libraries like [tcomb-ats](https://github.com/gcanti/tcomb-ats) be possible?

If configured the same way, it would go in the [tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) file as such:
```json
{
  "typeAssertionModule": "path/to/tcomb-ts"
}
```

**Comment by danquirk** [comment]
As far as I can tell this is basically asking for a pluggable type system, which essentially no languages do (well). This doesn't look like an assertion library (in the sense of common uses of the term like chai, should, etc), it looks like an entirely new set of primitive types and assignability rules. This isn't something we'd support.

**Comment by iisaduan** [comment]
Sorry about the spam-- bot's posting to the wrong repo :/. I think I fixed it but might take a bit to register
