### ISSUE TITLE
Allow comments in options file?

### ISSUE THREAD

**Issue by JoshMcCullough** [Microsoft/TypeScript#2945]
E.g. when running `tsc @TSCOptions.txt`, it would be cool if there was a way to include comments in the options file since they can become very long. For instance:

    --sourcemap
    -t ES5                 # ECMAscript 5
    -d                     # Generate declarations.
    --out Output\MyModule.js
    
    # First set of files.
    FileA1.ts
    FileA2.ts
    ...

    # Second set of files.
    FileB1.ts
    FileB2.ts
    ...

Comments in this example are preceded with a `#` and can be inline or on their own line. Antything after a `#` would be stripped prior to compilation.

**Comment by mhegazy** [comment]
what about using tsconfig.json instead?
though that does not allow comments, it is more self describing.

**Comment by JoshMcCullough** [comment]
I haven't heard of that - will do some research.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

**Comment by JoshMcCullough** [comment]
Yes. It doesn't solve the problem, but it is nice to know. :+1:

**Comment by jasonwilliams200OK** [comment]
JSON specification does not allow having comments. It was removed at some point from specification as an "improvement", to which many people objected.

Nonetheless, it would be really handy to have `.tsrc` file, in conformity to `.jshintrc`, `.jscsrc`, and many other [*resource configuration files (wikipedia)*](http://en.wikipedia.org/wiki/Configuration_file). The format of such file can be JSON with single-line comments, e.g. https://github.com/oryband/dotfiles/blob/master/jshintrc. For a Unix person, this will be a treat!

@madskristensen has also managed to validate and provide intellisense for .jshintrc, .jscsrc etc. in VS2013 and VS2015 via extensions, which signifies that it is a very viable option! (only Windows team needs to allow creating a `.` file in File Explorer and when saving from notepad's save as dialog, so we don't have to rename the file using cmd or powershell..)

**Comment by mhegazy** [comment]
tsconfig now supports comments, see https://github.com/Microsoft/TypeScript/issues/4987
