### ISSUE TITLE
Property 'groups' does not exist on type 'RegExprMatchArray' for named captured groups

### ISSUE THREAD

**Issue by mytee306** [Microsoft/TypeScript#29465]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// Property 'groups' does not exist on type 'RegExprMatchArray
console.log("john_doe".match(/^(?<first>[a-z]+).+$/).groups.first) // john

console.log((<any>"john_doe".match(/^(?<first>[a-z]+).+$/)).groups.first) // john
```

**Expected behavior:**

Not type error

**Actual behavior:**

Type mismatch: `Property 'groups' does not exist on type 'RegExprMatchArray'`

**Playground Link:** 

[reproduced on stackblitz using the default typescript project](https://stackblitz.com/edit/named-captured-groups?file=index.ts)

**Comment by j-oliveras** [comment]
You should set target to es2018 or higher (for example esnext) or add `es2018.regexp` into lib config.

**Example 1** (target to es2018 or higher): `tsconfig.json` and using your sample code as is
```json
{
  "compilerOptions": {
    "target": "es2018"
  }
}
```

**Example 2** (using lib config): `tsconfig.json` and using your sample code as is
```json
{
  "compilerOptions": {
    "target": "es2015",
    "lib": [ "es2015", "es2018.regexp" ]
  }
}
```

**Example 3** (adding reference lib on code):
`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es2015"
  }
}
```

`file.ts`
```ts
/// <reference lib="es2018.regexp" />

console.log("john_doe".match(/^(?<first>[a-z]+).+$/).groups.first) // john

console.log((<any>"john_doe".match(/^(?<first>[a-z]+).+$/)).groups.first) // john
```

Note: I tested all of this with version 3.3.0-dev.20190118.

**Comment by weswigham** [comment]
stackblitz is running an older version of TS that doesn't even understand the `lib` reference directive syntax - so prior to [3.0](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#-reference-lib--reference-directives).

**Comment by liudonghua123** [comment]
I still got this error in the latest 3.7.3, see more on https://github.com/microsoft/TypeScript/issues/35604.

**Comment by liorama** [comment]
Happens in the Typescript sandbox (target set to ES2020, Module ESNext).
https://www.typescriptlang.org/play/?target=7#code/MYewdgziA2CmB00QHMAUAiAViAFmA+gCYizrwC2AhgC7A6oD0AeqgPwA8AZgJYBOE1AHwBtSgFoAXgF0A1AEp4MgCQMFyXiACuABwjwe-anIAEDBsex4AUFdCQYCJGlTtKYAJ6CsuAsVIUaOkYWDgMBEXFpeUUVOTUNHT0wo1NzSzArIA

**Comment by miccies3** [comment]
Mismatch still happens even with compiler target and lib set to ESNext, ES2018 etc.

```typescript
const ip = "127.0.0.1";

const ipRegex = new RegExp(/(?<firstOctet>\d{1,3})\.(?<secondOctet>\d{1,3})\.(?<thirdOctet>\d{1,3})\.(?<fourthOctet>\d{1,3})/);

if(!ipRegex.test(ip)) {
    return "UNRECOGNIZED_FORMAT";
}

const { groups } = ipRegex.exec(ip);

console.log(groups.firstOctet);
console.log(groups.secondOctet);
console.log(groups.thirdOctet);
console.log(groups.fourthOctet);
```

**Comment by MartinJohns** [comment]
@miccies3 Works fine. [Playground link](https://www.typescriptlang.org/play?target=9#code/MYewdgzgLgBAlgBxgXhgIgIwCYDsA6ABkLwzQG4BYAKGtElkQCUBTAc2YA8UYxmB3GC1YBRDggAUAenEB+ADwAzOACdoAeWBRmUAHwAdACYBvDABoAzAF8AlHryy5EZnQMatuwyYs27DqAAsVV01tfWMzK1t7eQUQAFdlALdQzwibSWtKGio4BXEAQiY2TjwtaHFEa2sYI2oYepgA5RABNABVADlGYQBhNQBxDoBJAC1hABEAfQAxNUYAWQBBABVyaktqWnBoGphWZriECBhLbiL2DjxOZwqEa3ysrcgQABtmPBeQVnF9+KP8vBKVRQZJQTJPCCvd6fb6-Q4QAFOFyg8FUOiQt4fL4-A7-UqBZTBdyo9FQrGw3EIwHxRL+FGPKhAA)
