### ISSUE TITLE
can not infer return type of methods in class extended from abstract class with generic types

### ISSUE THREAD

**Issue by taoalpha** [microsoft/TypeScript#29474]
**TypeScript Version:**  3.1

**Search Terms:**

```ts
type TC = B | C;
abstract class A<T extends TC> {
    constructor(private client: T) {

    }
    list() {
        return this.client.list();
    }
}

class B {
    list(): string[] {
        return ["123"];
    }
}

class C {
    list(): number {
        return 123;
    }
}

class AOne extends A<B> {
    constructor() {
        super(new B());
    }
}

class ATwo extends A<C> {

    constructor() {
        super(new C());
    }
}

const a1 = new AOne();
const a2 = new ATwo();

// error on number doesn't have slice
a1.list().slice(2);

// error on Operator '+' cannot be applied to types 'number | string[]' and '1'.
a2.list() + 1;
```

**Expected behavior:**

should be able to infer `a1.list()` will return `string[]` and `a2.list()` will return `number`

**Actual behavior:**

both `list()` return type `number | string[]`

**Playground Link:**

http://www.typescriptlang.org/play/index.html#src=type%20TC%20%3D%20B%20%7C%20C%3B%0D%0Aabstract%20class%20A%3CT%20extends%20TC%3E%20%7B%0D%0A%20%20%20%20constructor(private%20client%3A%20T)%20%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20list()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.client.list()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20%7B%0D%0A%20%20%20%20list()%3A%20string%5B%5D%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%5B%22123%22%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20C%20%7B%0D%0A%20%20%20%20list()%3A%20number%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20123%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20AOne%20extends%20A%3CB%3E%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super(new%20B())%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ATwo%20extends%20A%3CC%3E%20%7B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super(new%20C())%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a1%20%3D%20new%20AOne()%3B%0D%0Aconst%20a2%20%3D%20new%20ATwo()%3B%0D%0A%0D%0Aa1.list().slice(2)%3B%0D%0A%0D%0Aa2.list()%20%2B%201%3B

**Comment by taoalpha** [comment]
```
abstract class A<T extends TC> {
    constructor(private client: T) {

    }
    list() {
        return this.client.list() as ReturnType<T["list"]>;
    }
}
```

can fix it, but not ideal...

**Comment by RyanCavanaugh** [comment]
@taoalpha's suggestion is the preferred thing to do. Return types of classes aren't deferred like this automatically because there isn't a reliable way to translate that behavior into a .d.ts file.
