### ISSUE TITLE
TypeScript's GitHub Releases page has incorrect links to fixed issues

### ISSUE THREAD

**Issue by mmorearty** [Microsoft/TypeScript#29475]
cc @DanielRosenwasser 

**TypeScript Version:**  3.2.2, 3.2.4

**Search Terms:** releases, fixed, github

**Expected behavior:**

Your [Releases page on GitHub](https://github.com/Microsoft/TypeScript/releases) has some incorrect links. For 3.2.2 and 3.2.4, where it says, "For the complete list of fixed issues, check out the fixed issues query for Typescript <version>", the link takes you to the list of _open_ issues for that version, not the list of _fixed_ issues. All the interesting stuff is in the list of _fixed_ issues.

**Actual behavior:**

List of open issues, which is usually empty.

**Playground Link:** N/A

**Related Issues:** #27946

**Comment by DanielRosenwasser** [comment]
Fixed for 3.2.4; I'll make sure the patches go to the closed issues area in the future. Thanks!
