### ISSUE TITLE
Returning Promise.all from async function not correctly assignable

### ISSUE THREAD

**Issue by stefda** [microsoft/TypeScript#29472]
**TypeScript Version:**  3.2.2

**Search Terms:**
Promise.all is not assignable
Promise.all

**Code**

```ts
async function parse(text: string): Promise<number> {
  return parseInt(text);
}

async function mapParse<T>(phrases: string[], parse: (text: string) => T): Promise<T[]> {
  return Promise.all(phrases.map(parse));
}

const numbers: number[] = await mapParse(['1', '2', '3'], parse);
```

**Expected behavior:** Code compiles and runs.

**Actual behavior:** ERROR: Unable to compile TypeScript: src/test.ts(13,9): error TS2322: Type 'Promise<number>[]' is not assignable to type 'number[]'. Type 'Promise<number>' is not assignable to type 'number'.

**Playground Link:** http://www.typescriptlang.org/play/#src=(async%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20async%20function%20parse(text%3A%20string)%3A%20Promise%3Cnumber%3E%20%7B%0D%0A%20%20%20%20return%20parseInt(text)%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20async%20function%20mapParse%3CT%3E(phrases%3A%20string%5B%5D%2C%20parse%3A%20(text%3A%20string)%20%3D%3E%20T)%3A%20Promise%3CT%5B%5D%3E%20%7B%0D%0A%20%20%20%20return%20Promise.all(phrases.map(parse))%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20const%20numbers%3A%20number%5B%5D%20%3D%20await%20mapParse(%5B'1'%2C%20'2'%2C%20'3'%5D%2C%20parse)%3B%0D%0A%7D)()

**Inconsistency:**
Removing the type in the assignment fixes the issue, i.e.
```
const numbers = await mapParse(['1', '2', '3'], parse);
```
compiles and runs as expected.

**Comment by AnyhowStep** [comment]
Change `parse(text: string): Promise<number> {`

To `parse(text: string): number {`

**Comment by weswigham** [comment]
I'd define `mapParse` as 
```ts
async function mapParse<T>(
  phrases: string[],
  parse: (text: string) => (Promise<T> | T)
): Promise<T[]> {
  return Promise.all(phrases.map(parse));
}
```
