### ISSUE TITLE
strictBindCallApply put perf penality on function.apply

### ISSUE THREAD

**Issue by LiangMingChen** [Microsoft/TypeScript#29483]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

const call: typeof Function.call = FunctionGlobal.call;
const apply: typeof FunctionGlobal.apply = FunctionGlobal.apply;
type AnyFunction = (...args: any[]) => any;
function _uncurryThis(f: AnyFunction): AnyFunction {
  /* tslint:disable-next-line:only-arrow-functions */
  return function unbindThis(): any {
    return call.apply(f, arguments);
  };
}

compiled javascript is expected, it doesn't unwrap arguments and pass through the apply.

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
no compiler error.

**Actual behavior:**
Argument of type 'IArguments' is not assignable to parameter of type '[{}, ...any[]]'.
  Type 'IArguments' is missing the following properties from type '[{}, ...any[]]': 0, pop, push, concat, and 24 more.ts(2345)

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
We don't type `arguments`, even in `strictBindCallApply`. For that see #29055.

Also, in the future please use code fences to format code before filing issues.
