### ISSUE TITLE
lib.dom.d.ts Document interface missing createNSResolver method.

### ISSUE THREAD

**Issue by evxn** [Microsoft/TypeScript#29487]
**TypeScript Version:**  3.3.0-dev.20190119

**Search Terms:** XPathEvaluator, Document, lib.dom.d.ts, createNSResolver 

**Code**

```ts
document.createNSResolver(document);
```

**Expected behavior:**
`Document` should have the method `createNSResolver`.

Actually, according to w3c `Document` interface should extend `XPathEvaluator` interface (which has 3 methods: `createExpression`, `createNSResolver` and `evaluate`). Right now  lib.dom.d.ts `Document` interface contains only `evaluate` method, the other two are missing.

"The evaluation of XPath expressions is provided by XPathEvaluator. In a DOM implementation which supports the XPath 3.0 feature, as described above, the XPathEvaluator interface will be implemented on the same object which implements the Document interface"

https://www.w3.org/TR/DOM-Level-3-XPath/xpath.html#XPathEvaluator
https://developer.mozilla.org/en-US/docs/Web/API/XPathEvaluator

**Actual behavior:**
Error: TS2339: Property 'createNSResolver' does not exist on type 'Document'.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=document.createNSResolver(document)%3B

**Related Issues:** #26437

**Comment by weswigham** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by VisibleMarkov** [comment]
I would love to work on this if it's still open (^_^)

**Comment by evxn** [comment]
@VisibleMarkov sure! Bonus points if you could implement is as a mixin, so it would be obvious that `interface Document extends XPathEvaluator ` (I got totally lost in the codebase on my first attempt to do this). But even adding the missing methods signatures to the Document should do the job.

**Comment by VisibleMarkov** [comment]
Thanks for the tip and the heads up. Will got on it ASAP (^_^)

**Comment by saschanaz** [comment]
Note that the old XPath spec doesn't have Web IDL but an older IDL syntax, [maybe this wiki document would help](https://wiki.whatwg.org/wiki/DOM_XPath).

**Comment by evxn** [comment]
@saschanaz `XPathEvaluator` interface is already implemented in typescript. It's just not the part of the `Document` interface.

**Comment by VisibleMarkov** [comment]
@saschanaz, should I replace the current older syntax with the newer Web IDL syntax?

**Comment by saschanaz** [comment]
@VisibleMarkov, I update the aforementioned wiki document so that it can be directly added to idlSources.json in TSJS-lib-generator. So now there should be no need to manually write anything.
