### ISSUE TITLE
[Feature request] Pluggable TypeScript compiler modules

### ISSUE THREAD

**Issue by CreatorVilius** [microsoft/TypeScript#29491]
## Search Terms

typescript compiler modules
typescript modules

## Suggestion

What about having TypeScript modules? Modules could change how compiler works and add some stuff.

## Use Cases

Modules would be able to modify these:
- Add new keywords
- Add new operators
- Add how something works
- Modify existing things and change how they compile

## Examples

Let's say we have Module called `typescript-operator-overloading`. This is an example of TypeScript code:
```ts
class A {
    public C: number
    operator +(other: A) {
        return this.C + other.C
    }
    constructor(B: number) {
        this.C = !!B ? B : 0
    }
}
const D: A = new A(10)
const E: A = new A(20)
D + E
```
This would compile to JavaScript's code:
```js
// ...
Symbol.operatorPlus = Symbol('+');
Symbol.operatorMinus = Symbol('-');
// ...
var A = /** @class */ (function () {
    function A(B) {
        this.C = !!B ? B : 0;
    }
    A.prototype[Symbol.operatorPlus] = function (other) {
        return this.C + other.C;
    };
    return A;
}());
var D = new A(10);
var E = new A(20);
D[Symbol.operatorPlus](E);
```

CLI Usage:
`tsc something.ts --out something.js --using="typescript-operator-overloading, ..."`

Inside-JS usage:
```js
const ts = require('typescript')
const tsOpOv = require('typescript-operator-overloading')

const tsCode = ts.compile(code, {
    // some compiler options
   modules: [tsOpOv]
})
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nickbclifford** [comment]
It looks to me like:
- this specific example does not meet the "this could be implemented without emitting different JS based on the types of the expressions" guideline
- you're looking for something similar to Babel plugins. To me, this sounds out of scope for the TS compiler. I'm fairly sure this is already possible by making your own Babel plugin for the syntax additions you want (keywords, operators, whatever) and just using TypeScript for the type checking.

**Comment by DanielRosenwasser** [comment]
Allowing pluggable syntax isn't likely something we'll be pursuing as part of the TypeScript project (even Babel doesn't truly support this AFAIK). Part of this is that there are technical requirements around things providing incremental parsing for the language service (which would be hard to achieve with a pluggable syntax system). But the main issue is in the interest of keeping one core language that aligns with ECMAScript.

Also, pluggable emitters are possible using our APIs, though not via `tsc` itself.
