### ISSUE TITLE
spec for call signatures is incorrect

### ISSUE THREAD

**Issue by fuafa** [microsoft/TypeScript#29495]
[3.9.2.1 Type Parameters ](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3921-type-parameters)

> Type parameters may be referenced in parameter types and return type annotations, but not in type parameter constraints, of the call signature in which they are introduced.

is incorrect. The following code is permitted, so type parameters can also be referenced in type parameter constrains.

```ts
interface I {
    <T, U extends T>(x: T, y: U): T | U
}
```

**Comment by j-oliveras** [comment]
It is a known: the spec is for version 1.8 (released on January 2016).

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
