### ISSUE TITLE
Ability to group unions in conditional types rather than splitting

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#29494]
## Search Terms
conditional type unions

## Suggestion

I need the ability to retain a union type and pass it on in a conditional type rather than have it be split

## Use Cases

To be able to pass `string | undefined` on in a conditional type to produce `Output<string | undefined>` rather than have `Output<string> | Output<undefined>`

## Examples

I want to make a class for editing properties on an object:
```
type primitives = string | number | boolean;

interface IPrimitiveEditor<T>{
    updateProperty: (value: T) => void;
}

interface ICompexEditor<T> extends IPrimitiveEditor<T> {
    editor: Editor<T>;
}

type PropertyEditor<T> = T extends primitives ? IPrimitiveEditor<T> : ICompexEditor<T>

class Editor<T>{

    withProperty<P extends keyof T>(name: P): PropertyEditor<T[P]> {
        return {} as any
    }
}
```

this works fine for non optional properties:

```
interface IMyInterface{
    stringProperty: string;
    complexType: {
        complexString: string;
    }
}

const editor = new Editor<IMyInterface>();

editor.withProperty("stringProperty").updateProperty(""); 

editor.withProperty("complexType").updateProperty({complexString: ""})
editor.withProperty("complexType").editor.withProperty("complexString").updateProperty("");
```

but with optional properties it all breaks down:

```
interface IMyInterface{
    stringProperty: string;
    optionalStringProperty?: string;
    complexType: {
        complexString: string;
    }
    optionalComplex?: {
        complexString: string;
    }
}

editor.withProperty("optionalStringProperty").updateProperty("");
editor.withProperty("optionalStringProperty").updateProperty(undefined);


editor.withProperty("optionalComplex").updateProperty({complexString: ""})
editor.withProperty("optionalComplex").editor.withProperty("complexString").updateProperty("");
```
[Full Playground Link](http://www.typescriptlang.org/play/#src=%0D%0Atype%20primitives%20%3D%20string%20%7C%20number%20%7C%20boolean%3B%0D%0A%0D%0Ainterface%20IMyInterface%7B%0D%0A%20%20%20%20stringProperty%3A%20string%3B%0D%0A%20%20%20%20booleanProperty%3A%20boolean%3B%0D%0A%20%20%20%20optionalStringProperty%3F%3A%20string%3B%0D%0A%20%20%20%20complexType%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20complexString%3F%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20optionalComplex%3F%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20complexString%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20IPrimitiveEditor%3CT%3E%7B%0D%0A%20%20%20%20updateProperty%3A%20(value%3A%20T)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ICompexEditor%3CT%3E%20extends%20IPrimitiveEditor%3CT%3E%20%7B%0D%0A%20%20%20%20editor%3A%20Editor%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20PropertyEditor%3CT%3E%20%3D%20T%20extends%20primitives%20%3F%20IPrimitiveEditor%3CT%3E%20%3A%20ICompexEditor%3CT%3E%0D%0A%0D%0Aclass%20Editor%3CT%3E%7B%0D%0A%0D%0A%20%20%20%20withProperty%3CP%20extends%20keyof%20T%3E(name%3A%20P)%3A%20PropertyEditor%3CT%5BP%5D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%7D%20as%20any%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20editor%20%3D%20new%20Editor%3CIMyInterface%3E()%3B%0D%0A%0D%0Aeditor.withProperty(%22stringProperty%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22booleanProperty%22).updateProperty(true)%3B%0D%0A%0D%0Aeditor.withProperty(%22optionalStringProperty%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22optionalStringProperty%22).updateProperty(undefined)%3B%0D%0A%0D%0Aeditor.withProperty(%22complexType%22).updateProperty(%7BcomplexString%3A%20%22%22%7D)%0D%0Aeditor.withProperty(%22complexType%22).editor.withProperty(%22complexString%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22complexType%22).editor.withProperty(%22complexString%22).updateProperty(undefined)%3B%0D%0A%0D%0Aeditor.withProperty(%22optionalComplex%22).updateProperty(%7BcomplexString%3A%20%22%22%7D)%0D%0Aeditor.withProperty(%22optionalComplex%22).editor.withProperty(%22complexString%22).updateProperty(%22%22)%3B%0D%0A) (turn on strict null checks)

The problem is that `editor.withProperty("optionalStringProperty")` does not produce `IPrimitiveEditor<string | undefined>` but instead produces `IPrimitiveEditor<string> | IComplexEditor<undefined>`.

This isn't helped if I add undefined to the primitives list. I then get `IPrimitiveEditor<string> | IPrimitiveEditor<undefined>`.

## Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [x ] This could be implemented without emitting different JS based on the types of the expressions
* [x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Roaders** [comment]
I've just discovered that my previous belief that this works fine with non optional primitives is wrong. It also doesn't work with booleans.
For some odd reason a boolean is spread to `true | false` so in the [updated example](http://www.typescriptlang.org/play/#src=%0D%0Atype%20primitives%20%3D%20string%20%7C%20number%20%7C%20boolean%3B%0D%0A%0D%0Ainterface%20IMyInterface%7B%0D%0A%20%20%20%20stringProperty%3A%20string%3B%0D%0A%20%20%20%20booleanProperty%3A%20boolean%3B%0D%0A%20%20%20%20optionalStringProperty%3F%3A%20string%3B%0D%0A%20%20%20%20complexType%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20complexString%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20optionalComplex%3F%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20complexString%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20IPrimitiveEditor%3CT%3E%7B%0D%0A%20%20%20%20updateProperty%3A%20(value%3A%20T)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ICompexEditor%3CT%3E%20extends%20IPrimitiveEditor%3CT%3E%20%7B%0D%0A%20%20%20%20editor%3A%20Editor%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20PropertyEditor%3CT%3E%20%3D%20T%20extends%20primitives%20%3F%20IPrimitiveEditor%3CT%3E%20%3A%20ICompexEditor%3CT%3E%0D%0A%0D%0Aclass%20Editor%3CT%3E%7B%0D%0A%0D%0A%20%20%20%20withProperty%3CP%20extends%20keyof%20T%3E(name%3A%20P)%3A%20PropertyEditor%3CT%5BP%5D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%7D%20as%20any%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20editor%20%3D%20new%20Editor%3CIMyInterface%3E()%3B%0D%0A%0D%0Aeditor.withProperty(%22stringProperty%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22booleanProperty%22).updateProperty(true)%3B%0D%0A%0D%0Aeditor.withProperty(%22optionalStringProperty%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22optionalStringProperty%22).updateProperty(undefined)%3B%0D%0A%0D%0Aeditor.withProperty(%22complexType%22).updateProperty(%7BcomplexString%3A%20%22%22%7D)%0D%0Aeditor.withProperty(%22complexType%22).editor.withProperty(%22complexString%22).updateProperty(%22%22)%3B%0D%0A%0D%0Aeditor.withProperty(%22optionalComplex%22).updateProperty(%7BcomplexString%3A%20%22%22%7D)%0D%0Aeditor.withProperty(%22optionalComplex%22).editor.withProperty(%22complexString%22).updateProperty(%22%22)%3B%0D%0A) `updateProperty` becomes `(value: true) => void | (value: false) => void` which means I get more compile errors...

**Comment by cpplearner** [comment]
From https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/:

> In case you ever need to avoid distributing on unions, you can surround each side of the extends keyword with square brackets:
> ```typescript
> type Foo<T> = [T] extends [any] ? T[] : never;
>
> // Boils down to Array<string | number>
> type Bar = Foo<string | number>;
> ```

**Comment by Roaders** [comment]
Thanks but that doesn't seem to work. Even in the example given the square brackets don't seem to make any different. It seems to give `(string | number)[]` with or without the square brackets.

**Comment by Roaders** [comment]
Yes I did! Many thanks. Working now:

[Updated Playground](http://www.typescriptlang.org/play/#src=type%20nullDefined%20%3D%20string%20%7C%20undefined%3B%0D%0Atype%20primitives%20%3D%20%5Bstring%20%7C%20nullDefined%20%5D%20%7C%20%5Bnumber%20%7C%20nullDefined%20%5D%20%7C%20%5Bboolean%20%7C%20nullDefined%20%5D%3B%0D%0A%0D%0Ainterface%20IMyInterface%7B%0D%0A%20%20%20%20stringProperty%3A%20string%3B%0D%0A%20%20%20%20booleanProperty%3A%20boolean%3B%0D%0A%20%20%20%20optionalStringProperty%3F%3A%20string%3B%0D%0A%20%20%20%20complexType%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20complexString%3F%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20optionalComplex%3F%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20complexString%3F%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20IPrimitiveEditor%3CT%3E%7B%0D%0A%20%20%20%20updateProperty%3A%20(value%3A%20T)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IComplexEditor%3CT%3E%20extends%20IPrimitiveEditor%3CT%3E%20%7B%0D%0A%20%20%20%20editor%3A%20Editor%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20PropertyEditor%3CT%3E%20%3D%20%5BT%5D%20extends%20primitives%20%3F%20IPrimitiveEditor%3CT%3E%20%3A%20IComplexEditor%3CNonNullable%3CT%3E%3E%0D%0A%0D%0Aclass%20Editor%3CT%3E%7B%0D%0A%0D%0A%20%20%20%20withProperty%3CP%20extends%20keyof%20T%3E(name%3A%20P)%3A%20PropertyEditor%3CT%5BP%5D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%7D%20as%20any%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20editor%20%3D%20new%20Editor%3CIMyInterface%3E()%3B%0D%0A%0D%0Aeditor.withProperty(%22stringProperty%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22stringProperty%22).editor%20%2F%2F%20correctly%20fails%0D%0Aeditor.withProperty(%22booleanProperty%22).updateProperty(true)%3B%0D%0A%0D%0Aeditor.withProperty(%22optionalStringProperty%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22optionalStringProperty%22).updateProperty(undefined)%3B%0D%0A%0D%0Aeditor.withProperty(%22complexType%22).updateProperty(%7BcomplexString%3A%20%22%22%7D)%0D%0Aeditor.withProperty(%22complexType%22).editor.withProperty(%22complexString%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22complexType%22).editor.withProperty(%22complexString%22).updateProperty(undefined)%3B%0D%0A%0D%0Aeditor.withProperty(%22optionalComplex%22).updateProperty(%7BcomplexString%3A%20%22%22%7D)%0D%0Aeditor.withProperty(%22optionalComplex%22).editor.withProperty(%22complexString%22).updateProperty(%22%22)%3B%0D%0Aeditor.withProperty(%22optionalComplex%22).editor.withProperty(%22complexString%22).updateProperty(undefined)%3B%0D%0Aeditor.withProperty(%22optionalComplex%22).editor.withProperty(%22complexString%22).updateProperty(5)%3B%20%2F%2F%20correctly%20fails%0D%0A)
