### ISSUE TITLE
Declaration merge between two modules stopped working

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/TypeScript#29498]
**TypeScript Version:**  3.2.4

**Search Terms:**

_"declaration merging"_

**Code**

See this chunk here:
https://github.com/atrauzzi/protoculture/blob/master/src/Data/ApiConnections.ts#L6-L9

Then this here:
https://github.com/artmoi/artmoi-js-sdk/blob/master/src/ArtMoiApiConfiguration.ts#L4-L11

**Expected behavior:**

Declaration merges in `@artmoi/artmoi-js-sdk` to augment types found in `protoculture`.

**Actual behavior:**

I'm seeing this error:

![image](https://user-images.githubusercontent.com/115199/51441853-c01ac800-1c9b-11e9-82e9-1189a81a1105.png)

The weird thing is that if I move the exact equivalent ambient declaration into the same file as where I'm using this code (or any other file as part of my build), the error goes away, but now obviously the augmentation is in the wrong place.

**Comment by RyanCavanaugh** [comment]
Without a reduced repro this looks more like a question or setup issue than a bug report - certainly other people are doing declaration merging without issue. If you can reduce this to something that is clearly a bug we can investigate.
