### ISSUE TITLE
TypeScript decorators in derived classes are broken

### ISSUE THREAD

**Issue by highco** [Microsoft/TypeScript#29506]
I create a decorator called “serialize”
```
function serialize(target: any, key: string)
{
}
```
and then use it like this:
```
class Fruit
{
	name = "Fruit"	
}

class Apple extends Fruit
{
	@serialize name = "Apple"
}

class Orange extends Fruit
{
	@serialize name = "Orange"
}
```
This is the code the TypeScript compiler generates:
```
__decorate([serialize], Apple.prototype, "name", void 0);
__decorate([serialize], Orange.prototype, "name", void 0);
```
The problem is that TypeScript passes the **prototype** of the type (“Fruit” in this example) instead of the type itself (“Apple” and “Orange”) to my decorator function. 

How can I distinguish between Apple and Orange in my decorator function? I just get passed in the **prototype**, which is “Fruit” in both cases. My serialize function basically gets called twice with the exact same values as arguments and has no idea which type (Apple or Orange) it should decorate.

**Comment by rbuckton** [comment]
Note that `Orange.prototype` is _not_ `Fruit`, but an object whose prototype is `Fruit.prototype`. You should be able to distinguish them via `target.constructor`, i.e.: `Orange.prototype.constructor === Orange` and `Apple.prototype.constructor === Apple`
