### ISSUE TITLE
Generic constraint enforced inconsistently 

### ISSUE THREAD

**Issue by mattsjones** [Microsoft/TypeScript#29519]
**TypeScript Version:**  3.3.0-dev.20190119

**Search Terms:**
"Generic constraints"

**Code**

```ts
interface ComplexThing {
    thing1?: string;
    thing2?: number;
}

interface ThingInterface {
    [key: string]: ComplexThing;
}

const doStuff = <MyThing extends ThingInterface>(
    param: MyThing
): { [K in keyof MyThing]: string } => {
    return Object.assign(
        {},
        ...Object.keys(param).map(key => ({ [key]: 'some value' }))
    );
};

// doStuff param type is ThingInterface, throws error (desired behaviour)
const stuff1 = doStuff({
    key1: {
        otherThing: ''
    },
});

// doStuff param type is ThingInterface, throws error (desired behaviour)
const stuff2 = doStuff({
    key1: {
        otherThing: '',
        thing1: ''
    },
    key2: {
        thing1: '',
        thing2: ''
    }
});

// doStuff param type is forced to ThingInterface, throws error (desired behaviour)
const stuff3 = doStuff<ThingInterface>({
    key1: {
        otherThing: '',
        thing1: ''
    },
    key2: {
        thing1: '',
        thing2: 2
    }
});

// doStuff param type is whatever is passed in, no error (undesired behaviour)
const stuff4 = doStuff({
    key1: {
        otherThing: '',
        thing1: ''
    },
    key2: {
        thing1: '',
        thing2: 2
    }
});
```

**Expected behaviour:**
The `doStuff` parameter type should be inferred consistently to `ThingInterface`, causing errors when unexpected properties are passed and allowing autocomplete of properties in your editor.

**Actual behaviour:**
In some (seemingly random) scenarios, the `doStuff` parameter type is no longer type `ThingInterface` and extra properties are allowed. This also breaks the editor autocomplete experience. 

I understand that inference is hard in this scenario as all properties are optional however, it seems quite random when the type is inferred as expected and when not. 

I also would be interested if there are any ways to force TypeScript to only allow this interface. The generic needs to be inferred for the key extraction being performed in the return type which means passing the generic at call time is not an option.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=interface%20ComplexThing%20%7B%0D%0A%20%20%20%20thing1%3F%3A%20string%3B%0D%0A%20%20%20%20thing2%3F%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ThingInterface%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20ComplexThing%3B%0D%0A%7D%0D%0A%0D%0Aconst%20doStuff%20%3D%20%3CMyThing%20extends%20ThingInterface%3E(%0D%0A%20%20%20%20param%3A%20MyThing%0D%0A)%3A%20%7B%20%5BK%20in%20keyof%20MyThing%5D%3A%20string%20%7D%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20Object.assign(%0D%0A%20%20%20%20%20%20%20%20%7B%7D%2C%0D%0A%20%20%20%20%20%20%20%20...Object.keys(param).map(key%20%3D%3E%20(%7B%20%5Bkey%5D%3A%20%27some%20value%27%20%7D))%0D%0A%20%20%20%20)%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20doStuff%20param%20type%20is%20ThingInterface%2C%20throws%20error%20(desired%20behaviour)%0D%0Aconst%20stuff1%20%3D%20doStuff(%7B%0D%0A%20%20%20%20key1%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20otherThing%3A%20%27%27%0D%0A%20%20%20%20%7D%2C%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20doStuff%20param%20type%20is%20ThingInterface%2C%20throws%20error%20(desired%20behaviour)%0D%0Aconst%20stuff2%20%3D%20doStuff(%7B%0D%0A%20%20%20%20key1%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20otherThing%3A%20%27%27%2C%0D%0A%20%20%20%20%20%20%20%20thing1%3A%20%27%27%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20key2%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20thing1%3A%20%27%27%2C%0D%0A%20%20%20%20%20%20%20%20thing2%3A%20%27%27%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20doStuff%20param%20type%20is%20forced%20to%20ThingInterface%2C%20throws%20error%20(desired%20behaviour)%0D%0Aconst%20stuff3%20%3D%20doStuff%3CThingInterface%3E(%7B%0D%0A%20%20%20%20key1%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20otherThing%3A%20%27%27%2C%0D%0A%20%20%20%20%20%20%20%20thing1%3A%20%27%27%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20key2%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20thing1%3A%20%27%27%2C%0D%0A%20%20%20%20%20%20%20%20thing2%3A%202%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20doStuff%20param%20type%20is%20whatever%20is%20passed%20in%2C%20no%20error%20(undesired%20behaviour)%0D%0Aconst%20stuff4%20%3D%20doStuff(%7B%0D%0A%20%20%20%20key1%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20otherThing%3A%20%27%27%2C%0D%0A%20%20%20%20%20%20%20%20thing1%3A%20%27%27%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20key2%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20thing1%3A%20%27%27%2C%0D%0A%20%20%20%20%20%20%20%20thing2%3A%202%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A

**Related Issues:** 
Unsure

**Comment by dragomirtitian** [comment]
Why should `T` be inferred to `ThingInterface`? The whole point is that `T` can be any type, that is a subclass of `ThingInterface`. 

The only issue I see is that excess property checks kick in when inference fails and can lead to some confising messages. If `T` can't be inferred from parameters (because the parameter type does not extend `ThingInterface`) then `T` will default to `ThingInterface`. If `T` is `ThingInterface` then the parameter type gets checked against `ThingInterface`. This will yield both the error that is causing the parameter type to be incompatible with `ThingInterface` but also will show up some excess property errors, since when you are assigning an object literal to an specific type, it gets checked for excess properties.

Just to be clear why inference fails in each case: 

```ts
const stuff1 = doStuff({
    key1: {
        otherThing: ''
    },
});
```
`ComplexThing` is a weak type, it is an error to assign an object literal to a weak type when there is no property overlap ([read here about weak types](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#weak-type-detection)). 

```ts
const stuff2 = doStuff({
    key1: {
        otherThing: '',
        thing1: ''
    },
    key2: {
        thing1: '',
        thing2: ''
    }
});
```

`thing2` is a string so the parameter type can't be a subclass of `ComplexThing`

If you specify the `T` explicitly then the compiler will raise errors on excess properties as the object literal is assigned to a parameter of a specific type.

**Comment by RyanCavanaugh** [comment]
I agree with @dragomirtitian's analysis.

There are many factors leading to this behavior, any individual one of which is not negotiable:
 * In the presence of inference failure, the constraint type is used to validate the parameters
 * Types with excess properties are, of course, allowed to be inference candidates when they're subtypes of the type parameter's constraint
 * Weak types are a thing

I think the only plausible tweak here would be that the error message *could* be nested under a "Failed to find a suitable `T`"-type error, but it's not really clear that this would be a net improvement - most of the time if your expression arguments don't produce a successful inference in the presence of a constraint, you do indeed have a simple assignability error in one of the parameters, not a weird inference-specific situation.
