### ISSUE TITLE
Show default arguments in signature help

### ISSUE THREAD

**Issue by Andy-QT** [Microsoft/TypeScript#29527]
- VSCode Version: 1.30.2
- Language: JavaScript

Missing (=1) as parameter hint.

![grafik](https://user-images.githubusercontent.com/2870154/51480619-c0958a80-1d91-11e9-8688-7ffe33704464.png)

**Comment by mjbvz** [comment]
Related to #27442

**Comment by mjbvz** [comment]
Duplicate of #16665
