### ISSUE TITLE
Visual Studio hangs on project load.

### ISSUE THREAD

**Issue by Griffork** [Microsoft/TypeScript#2952]
I isolated it to having the following text within the `.csproj` file:
```
  <ItemGroup>
    <Service Include="{4A0DDDB5-7A95-4FBF-97CC-616D07737A77}" />
  </ItemGroup>
```
I created the project in Visual Studio 2015, and tried to open it in Visual Studio 2013 (which is where it hung).
According to [this link](http://stackoverflow.com/a/22917902/2020425) it has something to do with the project being identified as a test project. 
It is a new project that has had two folders and a handful of .ts files added to it.

**Comment by mhegazy** [comment]
@Griffork is this still an issue with TypeScript 1.6?

**Comment by Griffork** [comment]
I have no idea. I stopped using Typescript a while ago.

**Comment by paulvanbrenk** [comment]
Based on the link you posted this is not a TypeScript specific issue, but related to the unit testing integration. It doesn't like there is anything we can do.
