### ISSUE TITLE
Destructured syntax for imported types.

### ISSUE THREAD

**Issue by bySabi** [Microsoft/TypeScript#29522]
I had been using typescript `import` in place of ES6 imports in order of be more explicit on what is a type a what is javascript.

Ex:
```
import { Foo, Bar } from './classes';  // Javascript classes

type FooType = import('./types').FooType;
type BarType = import('./types').BarType;

```

Would be nice to have destructuring for type imports just like ES6 imports.
Ex:
```
import { Foo, Bar } from './classes';  // Javascript classes

type { FooType, BarType } = import('./types');
```

This is possible or will never be?

**Comment by ajafff** [comment]
Duplicate of #13135

**Comment by bySabi** [comment]
You are right @ajafff is a duplicate.
I close this in favour of https://github.com/Microsoft/TypeScript/issues/13135
