### ISSUE TITLE
Missing error when passing unconstrained generic to imported type

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#29530]
**TypeScript Version:**  3.2.2

**Search Terms:** generic import types extends constraint constrained

**Code**

```ts
// ./lib.ts
export type Foo<T extends string> = { foo: T }

// ./index.ts
type Foo<T> = import('./lib').Foo<T>;
// Should require matching constraint:
// type Foo<T extends string> = import('./lib').Foo<T>;
```

**Comment by apendua** [comment]
@OliverJAsh I first observed this behavior for JSDocs where the usage of `import(...).Type<T>` is generally much more frequent and I thought it would only be JSDoc related, but it seems like this is a more generic problem, isn't it?
