### ISSUE TITLE
JSX children props type are ignored

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#29537]
## Search Terms

react jsx children element props type

https://stackoverflow.com/questions/44475309/how-do-i-restrict-the-type-of-react-children-in-typescript-using-the-newly-adde

## Suggestion

Support for typed `children` was added in https://github.com/Microsoft/TypeScript/pull/15160, however it seems that for some reason you cannot restrict the children to elements _with specific prop types_ -- which for me at least was the main use case I was wanting typed `children` for. Example:

```
type RequiredProps = { required: string; };

declare class Parent extends Component<{ children: ReactElement<RequiredProps> }> {}

declare class Child extends Component<{ foo: string; }> {}

// Rendered:
  <Parent>
    <Child foo="bar" />
  </Parent>

```

I expect an error on `<Child foo="bar" />` because `Child` component does not have the props of `RequiredProps`, but it passes without compile error.

## Use Cases

A parent component may expect a specific child component to work properly. This could be something like a `menu` with child `menu items`, or decorator like component that augments the props of rendered children, like `onClick` or `width` and `height`.

## Examples

```
type RequiredProps = { required: string; };

declare class Parent extends Component<{ children: ReactElement<RequiredProps> }> {}

declare class ChildWithRequiredProps extends Component<{ required: string; }> {}

declare class ChildWithoutRequiredProps extends Component<{ foo: string; }> {}

// Renders without error:
  <Parent>
    <ChildWithRequiredProps required="bar" />
  </Parent>

// Error:
  <Parent>
    <ChildWithoutRequiredProps foo="bar" />
  </Parent>
```

Would really like the generic case to work:

```
declare class Parent<ChildProps extends RequiredProps> extends Component<{ children: ReactElement<ChildProps> }> {}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
Duplicate of #21699.

**Comment by aaronbeall** [comment]
@DanielRosenwasser Just read through that story, sounds like it would solve this issue. Thanks.
