### ISSUE TITLE
What does Microsoft going to do with Monaco?

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#2954]
I used to think Monaco is great, but just find it awesome! And the features it has are definitely far beyond the range of a playground. Is Microsoft going to release some kind of Web IDE (or cross-platform IDE based on web techniques)?

**Comment by RyanCavanaugh** [comment]
Unfortunately we can't use the issue tracker to disclose non-public information :wink:

**Comment by vilic** [comment]
Now, it's public. Congrats!

**Comment by tinganho** [comment]
:+1: http://techcrunch.com/2015/04/29/microsoft-shocks-the-world-with-visual-studio-code-a-free-code-editor-for-os-x-linux-and-windows/#.monxpv:moa5
