### ISSUE TITLE
Missing error for trailing comma in dynamic import arguments

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#29545]
**TypeScript Version:**  3.3.0-dev.20190119

**Search Terms:**

**Code**

```ts
import('foo',);
```

**Expected behavior:**

Error on the trailing comma as the spec/proposal currently disallows it: https://github.com/tc39/proposal-dynamic-import/issues/15

**Actual behavior:**

No grammar error, instead this results in a parse error when executed after transpiling with `module: ESNext`

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Thanks @fuafa and congrats on your first contribution 😄
