### ISSUE TITLE
--build and --showConfig don't work together

### ISSUE THREAD

**Issue by doomsower** [microsoft/TypeScript#29557]
**TypeScript Version:**  3.3.0-dev.20190124

**Search Terms:** showConfig

**Code**

I have 3 ts config files:
1. `<rootDir>/tsconfig.json`
2. `<rootDir>/packages/pkg/tsconfig.json`, which extends the first one (`"extends": "../../tsconfig.json"`)
3. `<rootDir>/packages/pkg/tsconfig.build.json`, which extends the second one (`"extends": "./tsconfig.json"`)

Then I run `tsc --build tsconfig.build.json --showConfig` in `<rootDir>/packages/pkg/` directory.

**Expected behavior:**

I expect to get three configs merged together. `tsc --showConfig` works fine for two configs.

**Actual behavior:**

`error TS5072: Unknown build option '--showConfig'.`

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
You need to not pass the `--build` option. `--build` can build multiple projects but `--showConfig` can only display one project's config at atime.

**Comment by ecraig12345** [comment]
Why can't `--build` with `--showConfig` show the configs of all the projects that will be built? I'm seeing some issues where I'm pretty sure that the config is getting generated differently (and possibly incorrectly) in build mode and normal mode, and being unable to see the final config in build mode makes it hard to debug.
