### ISSUE TITLE
Include module names in add-import fixIds

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#29550]
Suppose the code contains an identifier `abc` that could be resolved by importing it from either module `a` or module `b`.  Presently, `getCodeFixes-full` returns two code fixes - one each for `a` and `b` - with the same fixId.  This causes two problems:
 1. VS de-dupes fixes with the same fixId so only the fix for `a` is shown.
 2. If fix-all is applied with the given fixId, the _first_ fix with that fixId at each diagnostic span is used, which is somewhat arbitrary.

We can resolve both problems by including the module name in the fixId:
 1. The fixIds will differ and neither fix will be dropped by VS.
 2. fix-all will add an import to a single module and update all the diagnostic spans that can be resolved with an import from that module.

**Comment by tomo-it** [comment]
In my opinion this is a bug, not a suggestion. This worked before in older versions of the Typescript compiler. Because it is not working anymore intellicense is unusable if you have multiple classes in the same project with the same name.

**Comment by amcasey** [comment]
@tomo-it IntelliSense and Code Fixes are implemented separately.  I believe the IntelliSense version of this bug was fixed in a VS 2019 preview and already worked correctly in VS Code.

**Comment by tomo-it** [comment]
Do you know if the intellisense thing is gonna be fixed in the 2017 version as well?

**Comment by amcasey** [comment]
At the moment, the only fix I'm aware of is for 2019.

**Comment by RyanCavanaugh** [comment]
@amcasey is this fixed, then? Can the issue be closed?

**Comment by amcasey** [comment]
@RyanCavanaugh, I don't know the current state of the product, but my reading of my earlier comments is that there were two parallel bugs (IntelliSense and Code Fix) and the one not tracked by this issue (IntelliSense) has already been fixed.

**Comment by amcasey** [comment]
This idea didn't work out as well as I thought, since there are several kinds of import code fix.  Since no one is asking for a rationalization of add-import fix-all, I'm going to address this in VS instead (VS Code already handles it).
