### ISSUE TITLE
vscode intellisense not identical

### ISSUE THREAD

**Issue by Bennes** [Microsoft/TypeScript#29552]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
p1-on function tip like p1
![image](https://user-images.githubusercontent.com/1115079/51651060-801e5280-1fc5-11e9-9ed9-e94d41da3f1e.png)

p2-in function tip like p2
![image](https://user-images.githubusercontent.com/1115079/51651068-87456080-1fc5-11e9-94b8-d6dce97b565a.png)

on p1 and p2,this isn't work correct;

my vcode version like
![image](https://user-images.githubusercontent.com/1115079/51651180-e3a88000-1fc5-11e9-9174-525ac2b24b89.png)

help me thank you

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is too far from a usable bug report for us to expend effort probing further.
