### ISSUE TITLE
ts.TypeChecker.typeToTypeNode goes in infinite loop eating up CPU and Memory.

### ISSUE THREAD

**Issue by abhijitparkhi1983** [microsoft/TypeScript#29564]
TypeScript Version: 3.2.2

Search Terms:
ts.TypeChecker.typeToTypeNode, 
ts.TypeLiteralNode,
ts.NodeBuilderFlags.NoTruncation

Description:

We are trying to use typescript compiler for getting the type of ObjectLiteralExpression and for the purpose we utilize following code:

```
getApparentTypeForObjectLiteralExpression(node : ts.Node) : {type : ts.Type, typeNode : ts.TypeNode} {
        let type : ts.Type = this.checker.getTypeAtLocation(node);
        let typeNode = this.checker.typeToTypeNode(type, undefined, ts.NodeBuilderFlags.NoTruncation);

        if(ts.isTypeLiteralNode(typeNode))
        {
            var memberCount = typeNode.members.length;
            var name : string;
            typeNode.members.forEach(member => {
                name +=  member.name;
                name += " , ";
            });
        }
        return {type, typeNode}
    }
```
When we run the above code over the attached file SEA3DAmmo.txt (rename file to SEA3DAmmo.js), the line this.checker.typeToTypeNode goes into infinite loop and the application consumes high CPU and Memory and the call does not return back atall.

This is an absolute blocker, may be i am doing some mistake. 
I also tried running with following options:
this.checker.typeToTypeNode(type, node, ts.NodeBuilderFlags.NoTruncation);
or
this.checker.typeToTypeNode(type, node.parent, ts.NodeBuilderFlags.NoTruncation);

**Expected behavior:**
It should return value and should not go in infinite loop.

[SEA3DAmmo.txt](https://github.com/Microsoft/TypeScript/files/2793068/SEA3DAmmo.txt)

**Comment by abhijitparkhi1983** [comment]
@weswigham , it will be very helpful if you can guide me on this blocker issue.  
The compilation options which i am adding while creating the ts.createProgram 

```
var options: ts.CompilerOptions = {
                noEmitOnError: true
                , strict: true
                , target: ts.ScriptTarget.Latest
                , module: ts.ModuleKind.CommonJS
                , skipLibCheck: true
                , experimentalDecorators: true
                , emitDecoratorMetadata : true
                , allowJs: true
                , noErrorTruncation : true
              };
```

**Comment by weswigham** [comment]
As a workaround, I'd try setting `noErrorTruncation: false` and seeing if you get some (truncated) output.

**Comment by abhijitparkhi1983** [comment]
If i do not pass `ts.NodeBuilderFlags.NoTruncation`, it does work but then the problem is that i do not get all the properties which i actually want.

**Comment by weswigham** [comment]
Try gradually bumping up the `(ts as any).defaultMaximumTruncationLength` value so you get more type-literal output so you can see what type is making us take so long to print.

**Comment by abhijitparkhi1983** [comment]
it stops at the property at line 87 from the file attached.

```
getGravity: function () {

		return this.gravity;

	},
```

**Comment by weswigham** [comment]
That's with the default length, yeah? With a larger truncation length (eg, 1000), where's the truncation occur (that'll be more indicative of where the problem is when truncation is off)?

**Comment by abhijitparkhi1983** [comment]
Ya thats with the default length i guess. But i am not aware how to set `defaultMaximumTruncationLength`.
Where do we set it ? In compilation options?

**Comment by abhijitparkhi1983** [comment]
Without setting the above value and without passing `ts.NodeBuilderFlags.NoTruncation` , `this.checker.typeToTypeNode(type)` returns with 12 members where 11th member has an entry for 23 more.

When i set `(ts as any).defaultMaximumTruncationLength = 1000` before calling `this.checker.typeToTypeNode(type)`, the number of members now shown is 19 where 18th member has 17 more.

If i bump the value of `(ts as any).defaultMaximumTruncationLength = 1000` any further, i am still getting 19 members alone

**Comment by weswigham** [comment]
> the number of members now shown is 19 where 18th member has 17 more.

What's the actual display of this type?

**Comment by abhijitparkhi1983** [comment]
I am not sure what do u mean by display of this type?
Its a ObjectLiteralExpression getting created, and the members are properties/functions.

**Comment by weswigham** [comment]
If you make a printer with `ts.createPrinter` and print the type, what's
the textual representation you get.

**Comment by abhijitparkhi1983** [comment]
Any ideas to go ahead with this problem ?

**Comment by weswigham** [comment]
Hmmm, well - if you explicitly give the return type with a type annotation of some kind it'll at least short circuit the printout.

**Comment by weswigham** [comment]
@sandersn I suspect this is identical to the issue you were looking at with js object printback and `this`?

**Comment by weswigham** [comment]
@abhijitparkhi1983 I've closed this, but if you could validate that your full example works in your  local setup with our next nightly (ie, the nightly from anytime after tomorrow), that'd be swell.
