### ISSUE TITLE
Rename symbol replaces default keyword for  defaut export of anonymous function

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/TypeScript#29567]
**TypeScript Version:**  3.3.0-dev.20190124

**Search Terms:**
rename, rename symbol, default, export, anonymous default export
**Code**

`a.ts`
```ts
import log from './b';

log('test'); // use Rename Symbol on `log` here with `test`
```

`b.ts`
```ts
export default function(a: string) {
    console.log(a);
};
```

**Expected behavior:**
When I use `Rename symbol` in VS Code on `log` function call - `log`  should be replaced with `test` only in `src/a.ts`

VS Code uses TypeScript version from local `node_modules`. When I install `typescript@latest` (`3.2.4`) it works as supposed.

**Actual behavior:**
`default` is replaced with `test` in `src/b.ts`
```ts
export test function(a: string) {
    console.log(a);
};
```

Same for `export default class {};` and `export default () => {}`

I don't see any error in TS Server logs.

**Playground Link:** Doesn't work for multiple files

**Related Issues:** #11308

**Comment by fatcerberus** [comment]
`export default function`
`export test function`

That’s kind of amusing, actually. :smile:  But probably really, really annoying in practice.

**Comment by IllusionMH** [comment]
After recent tests with latest stable and nightly versions of TS and VS Code I'm unable to reproduce this issue.
