### ISSUE TITLE
Suggestion: interface to allow overloading variables (similar to unions in C lang)

### ISSUE THREAD

**Issue by sandeepkalra** [Microsoft/TypeScript#2958]
Hi,

I have code that I want to rewrite in typescript, and for that I want to do few things that looks like this:
```ts
interface msg {
    x: number;
    Run: ()=>string;
    Run: (number) => string;
}

interface msg {
    Code: number;
    Message: string;
    Message: Object;
}
```
and many more similar things. Typescript has concept of 'overload' for functions. This is almost in same lines and more probably in line with "C" 'unions' style.

Is it possible to accept this as a feature request if this is not present and/or proposed yet for Typescript? 

Thanks,

**Comment by RyanCavanaugh** [comment]
This has been implemented as Union types, see #805 for an overview. Basically, you can write `var x: string|number` to mean "x is a `string` or a `number`"

**Comment by danquirk** [comment]
```ts
interface msg {
    x: number;
    Run: { 
		(): string;
		(number): string 
	}
}

interface msg {
    Code: number;
    Message: string|Object;
}
```

But note that string|Object likely doesn't do what you want because everything is an Object.

**Comment by sandeepkalra** [comment]
Thanks.
