### ISSUE TITLE
Object rest includes non-enumerable Symbols

### ISSUE THREAD

**Issue by planttheidea** [microsoft/TypeScript#29616]
**TypeScript Version:**  3.2.4

**Search Terms:** object rest, rest symbols

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const object = { visible: true };

Object.defineProperty(object, 'does not appear', {
  enumerable: false,
  value: 'hidden key',
});

Object.defineProperty(object, Symbol('appears on rest'), {
  enumerable: false,
  value: 'hidden symbol',
});

// does not include non-enumerable symbol or key
console.log({ ...object });

const { visible, ...rest } = object;

// includes non-enumerable symbol, but excludes key
console.log(rest);
```

**Expected behavior:**

Non-enumerable symbols are not include in Object rest operations.

**Actual behavior:**

Non-enumerable symbols are included in Object rest operations.

**Playground Link:** 

[Playground](https://www.typescriptlang.org/play/#src=%0D%0Aconst%20object%20%3D%20%7B%20visible%3A%20true%20%7D%3B%0D%0A%0D%0AObject.defineProperty(object%2C%20'does%20not%20appear'%2C%20%7B%0D%0A%20%20enumerable%3A%20false%2C%0D%0A%20%20value%3A%20'hidden%20key'%2C%0D%0A%7D)%3B%0D%0A%0D%0AObject.defineProperty(object%2C%20Symbol('appears%20on%20rest')%2C%20%7B%0D%0A%20%20enumerable%3A%20false%2C%0D%0A%20%20value%3A%20'hidden%20symbol'%2C%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20does%20not%20include%20non-enumerable%20symbol%0D%0Aconsole.log(%7B%20...object%20%7D)%3B%0D%0A%0D%0Aconst%20%7B%20visible%2C%20...rest%20%7D%20%3D%20object%3B%0D%0A%0D%0A%2F%2F%20does%20includes%20non-enumerable%20symbol%0D%0Aconsole.log(rest)%3B)

**Related Issues:** 

I believe this was introduced with this PR => https://github.com/Microsoft/TypeScript/pull/12248.

This included Symbols in rest, but uses `Object.getOwnPropertySymbols` without using `Object.prototype.propertyIsEnumerable` check in the loops. You can see this in the generated output in the playground above.

**Comment by NicholasLYang** [comment]
I decided to give this a crack. I [added](https://github.com/Microsoft/TypeScript/compare/master...NicholasLYang:fixObjectRestEnumeration) an `Object.prototype.propertyIsEnumerable` check to`__rest` in `destructuring.ts`. 

I attempted to fix the baseline tests, but I'm not entirely sure about how to do that. Should I just change the reference files manually? Or is there a better way of doing that? @weswigham

**Comment by weswigham** [comment]
Run a difftool over the directories and use the tool to copy over the changes (if you have a DIFFTOOL environment variable specified, `jake diff` should launch it with the correct folders). Failing that, `jake baseline-accept` should just copy over them all.
