### ISSUE TITLE
Better errors for non-exported types

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#29624]
```ts
// @filename a.ts

declare function foo(): any

declare function bar(): any;

export { bar };

// @filename b.ts

import { foo, bar } from "./a";
```

Currently we provide the following error messages:

```
Module '"./a"' has no exported member 'foo'.
Module '"./a"' has no exported member 'bar'.
```

We could instead provide the errors:

```
Module '"./a"' declares 'foo' locally, but it is not exported.
Module '"./a"' declares 'bar' locally', but it is exported as 'baz'.
```

Also using the

```
'{0}' is declared here.
```

related span.

Later on, we could provide quick fixes to respectively

* Export `foo` from ./a.
* Correct the usage of `bar` to `baz`.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Is there any way to check if a variable was declared in a module? I mean, in order to show message `Module '"./a"' declares 'foo' locally, but it is not exported.`, need to check if it was declared in a module locally.

**Comment by DanielRosenwasser** [comment]
There should be a symbol table for `sourceFile.locals` if it's non-exported (as opposed to `sourceFile.symbol.exports`.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
