### ISSUE TITLE
typescript class declaration private bug??

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#29631]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

**Code**

i don't sure this is idea bug or typescript bug

see this video for what i mean
https://www.youtube.com/watch?v=paEZCrRZ1Mw

when private it didn't output type <====== bug here
when protected it output type

idea: 2018.3.4
typescript: Version 3.3.0-dev.20190126

https://github.com/bluelovers/regexpp/blob/363adbbd762ea93fcf9ec6f0460de7cd204781e1/src/validator.ts#L555-L569

```ts
    private get ecmaVersion() {
        return this._options.ecmaVersion || 2018
    }


    private onLiteralEnter(start: number): void {
        if (this._options.onLiteralEnter) {
            this._options.onLiteralEnter(start)
        }
    }


    private onLiteralLeave(start: number, end: number): void {
        if (this._options.onLiteralLeave) {
            this._options.onLiteralLeave(start, end)
        }
    }
```

**Expected behavior:**

```ts
private onLiteralEnter(start: number): void;
```

**Actual behavior:**

```ts
private onLiteralEnter;
```

**Playground Link:** 

**Related Issues:**

**Comment by fatcerberus** [comment]
Not positive but I think that's probably by design.  The `.d.ts` is meant to just be the public API; since the private stuff can't be accessed from outside the class implementation anyway (or at least, it isn't *supposed* to be :wink:), there's no need for outside code to care about the type of private members.  Technically they don't even have to be included in the declaration file.

Is there a specific reason you need the type to be included?

**Comment by RyanCavanaugh** [comment]
You can't do anything with a private member, so its type is irrelevant

**Comment by RyanCavanaugh** [comment]
> Technically they don't even have to be included in the declaration file.

Almost true - private members are included so you don't (unknowningly) try to use the same property name for something else

**Comment by fatcerberus** [comment]
Oops, I took too long and got ninja'd 😝

**Comment by bluelovers** [comment]
i think should output private too like old version do, because need to check type is correct or as expected

**Comment by bluelovers** [comment]
im not wanna call it from outside, but i wanna see the type declaration

because i still will use it inside at current class

if thinking private member is no need to show, why show it name at class, why not just hidden name too?

**Comment by fatcerberus** [comment]
The `.d.ts` isn’t for your internal use - it’s for outside callers to get the type info.  If you’re calling something from inside the class then the info comes directly from the `.ts`.

**Comment by bluelovers** [comment]
the javascript already will stop we use same name in class member

but anyway , hope can have a option display private type

```ts
private onLiteralEnter(start: number): void;
```

or at least should show sign like old version

```ts
private onLiteralEnter(start);
```

not only the name

```ts
private onLiteralEnter;
```

**Comment by ganymedes01** [comment]
> You can't do anything with a private member, so its type is irrelevant

That's not true @RyanCavanaugh.

This properly catches the error:
```ts
class MyClass<T> {
  private field: T;
}

// Type 'MyClass<number>' is not assignable to type 'MyClass<string>'.
//  Type 'number' is not assignable to type 'string'
const value: MyClass<string> = new MyClass<number>();
```

This doesn't:
```ts
class MyClass<T> {
  private field;
}

// all good 👌
const value: MyClass<string> = new MyClass<number>();
```
