### ISSUE TITLE
ts.Declaration : how to get the actual declaration if same named variable is declared in 3 different files

### ISSUE THREAD

**Issue by abhijitparkhi1983** [microsoft/TypeScript#29635]
**TypeScript** Version: 3.2.2

**Search Terms:**
ts.Declaration
getSymbolAtLocation

**Description:**

We have 3 .ts, **A.ts, B.ts and C.ts**.
All these files have a variable test declared inside them as global variable as follows:

```
var test : number = 100 ;
test  = 200;
```
Note: All the 3 files have same above code declared globally (outside any class or any structure.)
We are trying to use typescript compiler for getting the variable declaration and variable usage and we are trying to resolve the usage with the actual declaration.

For resolving the actual declaration for a variable getting used (like line 2 above in any of the 3 files), we use following code:

 ```
var options: ts.CompilerOptions = {
                noEmitOnError: true
                , strict: true
                , target: ts.ScriptTarget.Latest
                , module: ts.ModuleKind.CommonJS
                , skipLibCheck: true
                , experimentalDecorators: true
                , emitDecoratorMetadata : true
                , allowJs: true
                , noErrorTruncation : false
              };
        
            var compilerHost = ts.createCompilerHost(options);
            this.program = ts.createProgram(this.sourceFilesToParse, options, compilerHost);            
            this.typeChecker = this.program.getTypeChecker(); 
....
....
getDeclarationFromUsageNode(node: ts.Node) : ts.Declaration {
       var symbol = this.typeChecker.getSymbolAtLocation(node);
       if(symbol) {
          var declarations = symbol.getDeclarations();
          ....
      }
}
```
**Expected behavior:**
When we are trying to get the declaration of usage of test variable inside file A.ts at the second line (test  = 200;), the above code should return only one declaration which is specific to A.ts file declared at first line (var test : number = 100 ;)

**Actual behavior:**
Now the problem with the above code is that **declarations** variable always has 3 entries in it (**possibly because variable test has been declared in 3 files**). 

This is a kind of blocker. I am sure I am missing setting some configuration, some flag. It will be helpful if some one from the TS compiler team can help me with this issue.

**Comment by ajafff** [comment]
This is working as intended. If you declare a variable using `var` in a global script, you are declaring *the same variable* multiple times. TypeScript only creates one Symbol with multiple declarations in such a case.

If you only want the declaration in the same file as the usage, you could use `declarations.filter(d => d.getSourceFile() === node.getSourceFile())`.

As an alternative, if you only want to analyze a single file at a time and don't need type information, you could use the function `collectVariableUsage` from my library `tsutils`. (It's not very well documented - actually it's not documented at all, so you might want to look up how it's used in `tslint`: https://github.com/palantir/tslint/search?q=collectvariableusage&unscoped_q=collectvariableusage)

**Comment by abhijitparkhi1983** [comment]
@ajafff , Thanks a lot for your quick response. 

I had thought of the same approach of filtering based on source file. 
That approach will work in most cases. But there is a different similar case which is related to overloaded methods, mapping its usage with the actual declaration.

So if there are 3 overloaded methods in a class A under file A.ts with names Method1 and different parameters to it.  Then if say i call the 2nd overloaded method of Method1 declared in class A from say class B, the ts.Declaration gives 3 declarations. Mapping to the actual declaration will then involve comparing parameters with arguments I believe or may be there is some better way for it.

Thanks for sharing the `tsutils` library. It looks promising and will explore the same right away along with the `collectVariableUsage `option.

**Comment by ajafff** [comment]
For the method overload use case, you probably want to use `typeChecker.getResolvedSignature` instead of `typeChecker.getSymbolAtLocation`. That should give you the method overload you are looking for.

**Comment by abhijitparkhi1983** [comment]
@ajafff `typeChecker.getResolvedSignature` did help in resolving the overloaded methods issue.

I would require one more help related to mapping of variable usage and its actual declaration from my original question.

I did add a check on `declarations.filter(d => d.getSourceFile() === node.getSourceFile())` which does help to a great extent but there is one more issues to it which i need some inputs on:

Assume following structure below in say file abc.js
```
var x = 5;
function alex() {
var x = 6;
}
function joe() {
var x = 7;
y = x + 1;
}
var x = 8;
``` 
in the above code, when i have to resolve declaration of **x** while using it at **y = x + 1;** again i get 5 declarations in all. By the way a **var** works, **x** usage at **y = x + 1;** should get resolved to **x** declared at line **var x = 7;**. Is there any way in which I can infer this from the 5 declarations i get. 

Looking forward to your inputs.

**Comment by ajafff** [comment]
You are right, `x` within `function joe` is a different symbol. You should only get one declaration for it.

I quickly tried it out in https://ts-ast-viewer.com/ and it seems to only yield a single declaration
<img width="1677" alt="screenshot 2019-01-31 at 08 56 39" src="https://user-images.githubusercontent.com/11968040/52039964-435ada00-2536-11e9-8c30-bd9ae2774ecb.png">

Are you sure there's no syntax error in your code that might confuse the typechecker?

**Comment by abhijitparkhi1983** [comment]
Thats the exact code which I am using for checking the declaration and usage test case. 
but for line **y = x + 1;**, **x** gets 5 declarations

**Comment by abhijitparkhi1983** [comment]
May be i am getting the declarations in a wrong way. The way i do it is as follows : 

getDeclarationFromUsageNode(node: ts.Node) : ts.Declaration {
      var symbol = this.typeChecker.getSymbolAtLocation(node);
      if(symbol) {
         var declarations = symbol.getDeclarations();
         ....
     }
}

May be the way i am getting the symbol is not right. is it ?

**Comment by abhijitparkhi1983** [comment]
@ajafff sorry for coming late on this thread. I was verifying the behavior with multiple scenarios and i am getting the same behavior as i have described above. There is no compilation error certainly.

Please find a running code attached with this msg.
In this code, **ResolveUsageSample.js**  file represents the code I am using to reproduce the scenario. under the **visitJavaCode.ts** file, if you debug the code and keep a break point at line 70, it gives value to be **100** using code `initializer.getText()` even for the code `test1 = 101;` on line 6 from file **ResolveUsageSample.js**. 

Ideally it should have given value **101** but the declaration is taking the declaration from line 1 instead of line 5 from the same file.

Any thought on this will be very useful.
[testTSCompiler.zip](https://github.com/Microsoft/TypeScript/files/2856318/testTSCompiler.zip)

**Comment by abhijitparkhi1983** [comment]
@ajafff  any inputs ?
