### ISSUE TITLE
How to task the problem, implements interface model?

### ISSUE THREAD

**Issue by pasapsi** [Microsoft/TypeScript#29644]
export interface IEntity {
    get Id(): string;
    get Type(): string;
    get TypeEntityName(): string;
    get Name(): string;
    get Interval(): string;
}

export class Entity implements IEntity {
    constructor(
        private id: string,
        private type: string,
        private typeEntityName: string,
        private name: string,
        private interval: string,
        private changeName?: string,
        private params?: any
    ) {}

    get Id(): string {
        return this.id;
    }

    get Type(): string {
        return this.type;
    }

    get TypeEntityName(): string {
        return this.typeEntityName;
    }

    get Name(): string {
        return this.name;
    }

    set Name(value: string) {
        this.name = value;
    }

    get Interval(): string {
        return this.interval;
    }

}

How to make the model fit the interface contract?
example link: https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/interface-properties

**Comment by Mcfloy** [comment]
Short answer: Not possible, even with a readonly property,

You can still use `getId` instead of `get Id`, sorry if you were that fond of C# notation.

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!
