### ISSUE TITLE
readonly type modifier doesn't work with array and tuple types selected by conditional types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#29649]
cc @ahejlsberg 

**TypeScript Version:**  3.4.0-dev.20190130

**Search Terms:**

**Code**

```ts
export type Readonly<T> =
  T extends ReadonlyArray<any> ? readonly T :
  T extends ReadonlySet<any> | ReadonlyMap<any, any> ? T :
  { readonly [P in keyof T]: T[P]; };
```

**Expected behavior:**

pass

**Actual behavior:**

'readonly' type modifier is only permitted on array and tuple types.

**Playground Link:** 

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is working as intended. The `readonly` modifier is only permitted on actual array and tuple types, it is not a full fledged type operator (for that, use the predefined `Readonly<T>` type or declare your own equivalent).

**Comment by falsandtru** [comment]
I should have written as follows instead, thanks.

```ts
export type Readonly<T> =
  T extends ReadonlySet<any> ? T extends Set<infer V> ? ReadonlySet<V> : T :
  T extends ReadonlyMap<any, any> ? T extends Map<infer K, infer V> ? ReadonlyMap<K, V> : T :
  { readonly [P in keyof T]: T[P]; };
```
