### ISSUE TITLE
Error message related to JSDoc for non-JSDoc syntax error

### ISSUE THREAD

**Issue by FabianLauer** [microsoft/TypeScript#29648]
**TypeScript Version:**
- 3.4.0-dev.20190130
- 3.2.4

**Search Terms:**

- ts8020 
- "jsdoc types can only be used" 
- "JSDoc types can only be used inside documentation comments"

**Code**

```ts
function isString(str: string): str is string! {
  return typeof str === 'string';
}
```

**Expected behavior:**

Error message should not mention JSDoc syntax. IMHO it should be `TS1144: '{' or ';' expected.`, which is the case with this code for example:

```ts
function isString(str: string): str is string? {
  return typeof str === 'string';
}
```

**Actual behavior:**

Error message states that this is JSDoc syntax (am not sure it even is). Full output of `tsc`:

```
> tsc test.ts
test.ts:1:40 - error TS8020: JSDoc types can only be used inside documentation comments.

1 function isString(str: string): str is string! {
                                         ~~~~~~~


Found 1 error.
```

**Playground Link:** 
[here](https://www.typescriptlang.org/play/#src=function%20isString(str%3A%20string)%3A%20str%20is%20string!%20%7B%0D%0A%20%20return%20typeof%20str%20%3D%3D%3D%20'string'%3B%0D%0A%7D)

**Related Issues:** 
- PR #17250

**Comment by pbrahmbhatt3** [comment]
can i work on it?

**Comment by DanielRosenwasser** [comment]
I don't understand why the suggested error message is better. Maybe we shouldn't mention JSDoc to begin with and that's the issue. The error message should probably be something like

```
Adding a postix '!' to the end of a type is not valid TypeScript syntax.
```

and

```
Adding a postix 'Foo' to the end of a type is not valid TypeScript syntax. Did you mean to write 'Foo | null | undefined'?
```

Generalized to

```
Adding a postix '{0}' to the end of a type is not valid TypeScript syntax. Did you mean to write '{1}'?
```

**Comment by FabianLauer** [comment]
@DanielRosenwasser My words exactly, JSDoc shouldn't be mentioned here 🙂 

@pbrahmbhatt3 I'm not sure if your PR fixes the same bug that this issue is about

**Comment by pbrahmbhatt3** [comment]
Any suggestions on fixing this issue @FabianLauer

**Comment by FabianLauer** [comment]
I think besides type guards this can also be repdocued in type assertions. Any expression such as this...
```ts
1 as any!;
```
... seems to produce TS8020 as well. [Playground example here.](https://www.typescriptlang.org/play/#src=1%20as%20any!%3B)

**Comment by arthurgeron** [comment]
when I mistakenly declared a function parameter as ` options:? ParseUrlOptions` I also got the `JSDoc types can only be used inside documentation comments` error message which was very confusing to me, I don't think JSDoc should be mentioned instead of the actual error.

**Comment by 0akl3y** [comment]
+1

**Comment by Quelklef** [comment]
+1 to removing a mention of JSDoc (or lessening it); I had gotten this error from typing `let val: Type!` instead of `let val!: Type`; the reference to JSDoc confused me until I found this issue.

**Comment by techieshark** [comment]
Yeah coming from Flow (which uses `?` for [`Maybe` types](
https://flow.org/en/docs/types/maybe/)), I found the mention of JSDoc confusing.

![image](https://user-images.githubusercontent.com/1072292/91648401-7b2b5a00-eaaa-11ea-8c14-54f1e5591d30.png)

+1 for saying which character is unexpected and perhaps a "did you mean" comment like @DanielRosenwasser  suggests above.

**Comment by hmanalai** [comment]
I would like to work on this issue if no one else is already.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser I'm curious, is it ok to extend the parser with this kind of message? Or is it better to avoid adding error handling to the `parser` to avoid problems with `incremental` builds?

**Comment by DanielRosenwasser** [comment]
Do you mean incremental parsing issues? I would hope this doesn't affect either, but the change should be at the same place where the current message is probably issued.

**Comment by a-tarasyuk** [comment]
> Do you mean incremental parsing issues?

Yes

**Comment by arjun-menon** [comment]
Not to necrobump this. but @DanielRosenwasser [has made some good suggestions here]( https://github.com/microsoft/TypeScript/issues/29648#issuecomment-469474803). This issue is still present, and confusing initially, for folks coming from Flow.  Hope Daniel's ideas are implemented at some point in the future.

**Comment by 0xdevalias** [comment]
Another example case where I ran into this just now was with the following code:

```
const foo: string? = process.env['FOO'];
```

![image](https://user-images.githubusercontent.com/753891/176807704-084fccf6-c7f1-4d1d-8e6c-d57cf95e296d.png)
![image](https://user-images.githubusercontent.com/753891/176807804-aff579fe-f201-4534-ba53-f1ca4bd7ea8d.png)

My brain was thinking of optional parameter syntax (though got that wrong too) when I ran into this:

- https://www.typescriptlang.org/docs/handbook/2/functions.html#optional-parameters

**Comment by AndrewEastwood** [comment]
+1
