### ISSUE TITLE
Incorrect inference for generic in conditional type

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#29659]
**TypeScript Version:**  3.2.4

**Search Terms:**

**Code**

```ts
type MapDispatchToPropsFunction<TDispatchProps> = () => TDispatchProps;
type MapDispatchToPropsFactory<
    TDispatchProps
> = () => MapDispatchToPropsFunction<TDispatchProps>;
type MapDispatchToPropsParam<TDispatchProps> =
    | MapDispatchToPropsFunction<TDispatchProps>
    | MapDispatchToPropsFactory<TDispatchProps>;

type GetDispatchProps<
    M extends MapDispatchToPropsParam<any>
> = M extends MapDispatchToPropsParam<infer DispatchProps>
    ? DispatchProps
    : never;

type DispatchProps = { foo: () => {} };
type OwnProps = { bar: 1 };
declare const mapDispatchToProps: MapDispatchToPropsParam<DispatchProps>;

// Expected: `DispatchProps`
// Actual: `DispatchProps | MapDispatchToPropsFunction<DispatchProps>`
type DispatchPropsInferred = GetDispatchProps<typeof mapDispatchToProps>;
```

**Comment by jack-williams** [comment]
I think this works if you turn off distribution. Does this give the expected result?
```ts
type GetDispatchProps<
    M extends MapDispatchToPropsParam<any>
> = [M] extends [MapDispatchToPropsParam<infer DispatchProps>]
    ? DispatchProps
    : never;
```

**Comment by OliverJAsh** [comment]
> are you expected `MapDispatchToPropsParam<DispatchProps>` to _not_ return a union type?

No, I expect it to return a union type.

I can't understand why my original example would return `DispatchProps | MapDispatchToPropsFunction<DispatchProps` for `infer DispatchProps` when the explicit generic we provide is only `DispatchProps`.

**Comment by Mcfloy** [comment]
Probably because the MapDispatchToPropsParam will always return a union type. You could try to put a `| String` just after and in both cases you'll still get your union anyway (which I agree, is odd)

**Comment by OliverJAsh** [comment]
> Probably because the MapDispatchToPropsParam will always return a union type.

This behaviour still doesn't make sense to me.

Could someone from the TS team indicate whether this is a bug or expected behaviour?

**Comment by jack-williams** [comment]
Is `MapDispatchToPropsParam` not defined as
```ts
type MapDispatchToPropsParam<T> = (() => T) | (() => () => T)
```
after inlining the aliases?

**Comment by OliverJAsh** [comment]
Yes, that's correct. I would expect `GetDispatchProps<typeof mapDispatchToProps>` to return `DispatchProps` only because that's how we created `mapDispatchToProps`:

``` ts
declare const mapDispatchToProps: MapDispatchToPropsParam<DispatchProps>;
```

**Comment by jack-williams** [comment]
I think due to the nature of the structural type system, the nature of how `mapDispatchToProps` was created---by alias or by literal---is largely irrelevant; the conditional types just sees the union of function types.

**Comment by RyanCavanaugh** [comment]
Rewriting the names a bit makes this a lot clearer:
```ts
type Func<T> = () => T;
type Func2<T> = () => Func<T>;
type FuncOrFunc2<T> = Func<T> | Func2<T>;

type GetFuncResult<M extends FuncOrFunc2<any>> =
    M extends FuncOrFunc2<infer Output>
    ? Output
    : never;
```

`GetFuncResult` sees two candidates for `Output` when given a `FuncOrFunc2` and returns a resulting union type. You need to conditionalize on the indirected function first:
```ts
type GetFuncResult2<M extends FuncOrFunc2<any>> =
    M extends Func2<infer Output>
    ? GetSimpleFuncResult<Output>
    : GetSimpleFuncResult<M>;
type GetSimpleFuncResult<T> = T extends Func<infer U> ? U : never;
// Correct
type DispatchPropsInferred2 = GetFuncResult2<typeof mapDispatchToProps>;
```

**Comment by OliverJAsh** [comment]
Thanks @RyanCavanaugh
