### ISSUE TITLE
Allow generic type parameters to be inferred from an argument's default value

### ISSUE THREAD

**Issue by jfirebaugh** [microsoft/TypeScript#29652]
## Search Terms

generic inference infer argument parameter default value

## Suggestion

I'd like either or both of the following to be accepted by TypeScript, with `A` inferred as `1` or `number` for `f0()` and `f1()`:

```ts
function f0<A>(p: A = 1): A {
    return p;
}

function f1<A = number>(p: A = 1): A {
    return p;
}
```

This seems like the natural behavior one would expect from the composition of two features: generic type inference and argument default values.

The current behavior is that both functions are rejected with the error "Type '1' is not assignable to type 'A'".

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jfirebaugh** [comment]
Thanks for the detailed explanation @Nathan-Fenner! `super` constraints may work for my particular use case; I'll look into that.

One question:

> Consider `f1`. What exactly is its type?

Could we define it to be `(() => number) & (<A>(a: A) => A)`? Then we have:

```ts
function f1<A>(x: A = 4 as any): A {
  return x;
}

const g: (() => number) & (<A>(x: A) => A) = f1;
g(); // Ok
g("foo"); // Ok
g<string>(); // $ExpectError
```

**Comment by jack-williams** [comment]
This sorta works..
```ts
function f1(): number;
function f1<A>(x: A): A;
function f1<A = number>(p: A | 1 = 1): A | number {
    return p;
}
```

**Comment by xialvjun** [comment]
> This sorta works..
> 
> ```ts
> function f1(): 1;
> function f1<A>(x: A): A;
> function f1<A = number>(p: A | 1 = 1): A | number {
>     return p;
> }
> ```

But this doesn't help on infer generic type:
```ts
function f1<A = number>(p: A = (1 as 1)): A {
    return p;
}

const a = f1(); // here I want a's type is 1
const b = f1(2); // here I want a's type is number
const c = f1(2 as 2); // here I want a's type is 2
const d = f1('3'); // here I want ts complain
```

**Comment by xialvjun** [comment]
> This means that (e.g.) it's a subtype of `() => number` and `(x: number) => number`.

That's right. But:

```ts
function foo<A>(x: A = 4):A { // in your code this line is `function foo<A>(x: A = 4 as any):A {`, but we just want ts compiler allow us not to add a `as any`
  return x;
}
type T = typeof foo; // here T should be '<4 extends A>(x?: A) => A'
```

**Comment by xialvjun** [comment]
@Nathan-Fenner sorry, I didn't see this:
```ts
function foo<A super 4>(x?: A = 4): A {
    return x;
}
```

This is just what I want. But ts complain `'super' can only be referenced in members of derived classes or object literal expressions.`. Do you know what's the right code? Or will ts support code like this in the future?
