### ISSUE TITLE
Weird behavior when checking class type with `typeof`

### ISSUE THREAD

**Issue by Rokt33r** [Microsoft/TypeScript#29656]
**TypeScript Version:**  3.2.4

**Search Terms:**

typeof, class, extends

**Code**

```ts
class Person {
    constructor(public name: string) {

    }
}

class Employer extends Person {
    constructor(public name: string, public title: string) {
        super(name)
    }
}

const APersonClass: typeof Person = Employer
```

**Expected behavior:**

There should be no error.

**Actual behavior:**

Throw `Type 'typeof Employer' is not assignable to type 'typeof Person'.` error on the last line.

To fix this error, I need to make constructor like the below.

```ts
class Person {
    constructor(public name: string, ...others: any[]){
    }
}
```

I'm not sure that it is intended or not.

**Playground Link:** 

http://www.typescriptlang.org/play/index.html#src=class%20Person%20%7B%0D%0A%20%20%20%20constructor(public%20name%3A%20string)%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Employer%20extends%20Person%20%7B%0D%0A%20%20%20%20constructor(public%20name%3A%20string%2C%20public%20title%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20super(name)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20PersonClass%3A%20typeof%20Person%20%3D%20Employer%0D%0A

**Comment by RyanCavanaugh** [comment]
```ts
class Person {
    constructor(public name: string) {

    }
}

class Employer extends Person {
    constructor(public name: string, public title: string) {
        super(name)
    }
}

const APersonClass: typeof Person = Employer
```
On the very next line you could write
```ts
const q = new APersonClass("");
```
and observe an illegal `undefined` in the resulting `Employer` instance's `title` property

**Comment by Rokt33r** [comment]
Sounds reasonable! Thanks!
