### ISSUE TITLE
completion list doesn't suggest 'const' in type assertion

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#29658]
**TypeScript Version:**  3.4.0-dev.20190131

**Search Terms:**

**Code**

```ts
1 as con/**/
```

**Expected behavior:**

Completion list should contain `const`

**Actual behavior:**

Completion list doesn't contain `const`.

In VSCode if the completion list is open, it automatically uses the first entry when typing certain characters like comma or semicolon. That's annoying as it replaces `const` with `ConstantSourceNode` or something like that.

**Playground Link:** 

**Related Issues:**

**Comment by Sammons** [comment]
I don't see why const should be in the list? 1 as const; isn't really valid in normal typescript code is it?

**Comment by ajafff** [comment]
@Sammons that feature was merged a few days ago and is already in the the nightly release. It will ship officially with the next stable release.

**Comment by Sammons** [comment]
@ajafff thanks for explaining, sorry for the rookie interjection

**Comment by tanhauhau** [comment]
can i work on this one?
