### ISSUE TITLE
Conditional Type with Infer and union/intersection type marked as unused

### ISSUE THREAD

**Issue by AmirTugi** [microsoft/TypeScript#29657]
**TypeScript Version:**  Playground

**Search Terms:**

**Code**
You should open the code in the [playground](https://www.typescriptlang.org/play/#src=type%20MargheritaToppings%20%3D%20%7B%0D%0A%20%20%20%20mushrooms%3F%3A%20boolean%3B%0D%0A%20%20%20%20olives%3F%3A%20boolean%3B%0D%0A%20%20%20%20onion%3F%3A%20boolean%3B%0D%0A%20%20%20%20basil%3F%3A%20boolean%3B%0D%0A%7D%3B%0D%0A%0D%0Aclass%20Pizza%3CT%2C%20S%3E%20%7B%0D%0A%20%20%20%20errornousFn(toppings%3A%20T%20%26%20S)%3A%20T%20%26%20S%20%7B%20return%20null%3B%20%7D%20%2F%2F%20%3C--%20This%20will%20NOT%20work%0D%0A%20%20%20%20errornousFn2(toppings%3A%20T%20%7C%20S)%20%7B%7D%20%2F%2F%20%3C--%20This%20will%20NOT%20work%0D%0A%20%20%20%20%2F%2F%20workingFn(toppings%3A%20T%20%7C%20S)%3A%20S%20%7B%20return%20null%3B%20%7D%20%2F%2F%20%3C--%20This%20works%0D%0A%7D%0D%0A%0D%0Aclass%20PizzaMargherita%20extends%20Pizza%3CMargheritaToppings%2C%20number%3E%20%7B%20%7D%0D%0A%0D%0A%0D%0A%2F*%20This%20works%20fine%20*%2F%0D%0A%0D%0A(new%20PizzaMargherita).errornousFn(null)%3B%20%2F%2F%20Funny%20enough%2C%20this%20works.%20Cmd%20%2B%20hover%20over%20%60errornousFn%60%20will%20show%20types%20correctly.%0D%0A%0D%0A%0D%0A%2F*%20Here's%20the%20problem%20*%2F%0D%0A%0D%0Atype%20ExtractSecond%3CP%3E%20%3D%20P%20extends%20Pizza%3Cany%2C%20infer%20T%3E%20%3F%20T%20%3A%20never%3B%0D%0A%0D%0Alet%20a%3A%20ExtractSecond%3CPizzaMargherita%3E%3B%20%2F%2F%20%3C--%20%60a%3A%20%7B%7D%60%20for%20%60A%60%20if%20%60errornousFn%60%20is%20uncommented%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%20%20%20%20and%20%60a%3A%20number%60%20if%20%60workingFn%60%20is%20uncommented%20)

```ts
type MargheritaToppings = {
    mushrooms?: boolean;
    olives?: boolean;
    onion?: boolean;
    basil?: boolean;
};

class Pizza<T, S> {
    errornousFn(toppings: T & S): T & S { return null; } // <-- This will NOT work
    errornousFn2(toppings: T | S) {} // <-- This will NOT work
    // workingFn(toppings: T | S): S { return null; } // <-- This works
}

class PizzaMargherita extends Pizza<MargheritaToppings, number> { }


/* This works fine */

(new PizzaMargherita).errornousFn(null); // Funny enough, this works. Cmd + hover over `errornousFn` will show types correctly.


/* Here's the problem */

type ExtractSecond<P> = P extends Pizza<any, infer T> ? T : never;

let a: ExtractSecond<PizzaMargherita>; // <-- `a: {}` for `A` if `errornousFn` is uncommented
                                       //     and `a: number` if `workingFn` is uncommented 
```

**Expected behavior:**
I expected the conditional type to work just as calling one of the `errornousFn`s works with typings.

**Actual behavior:**
I guess that something is off when using union/intersection types and conditional types with `infer`.
`S` is somehow marked as `unused` and thus we get the default `{}` type.
This is backed up by [this](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot), but I guess this is a bug since the same code works for what is not a conditional type.

**Playground Link:** [Here](https://www.typescriptlang.org/play/#src=type%20MargheritaToppings%20%3D%20%7B%0D%0A%20%20%20%20mushrooms%3F%3A%20boolean%3B%0D%0A%20%20%20%20olives%3F%3A%20boolean%3B%0D%0A%20%20%20%20onion%3F%3A%20boolean%3B%0D%0A%20%20%20%20basil%3F%3A%20boolean%3B%0D%0A%7D%3B%0D%0A%0D%0Aclass%20Pizza%3CT%2C%20S%3E%20%7B%0D%0A%20%20%20%20errornousFn(toppings%3A%20T%20%26%20S)%20%7B%20%7D%20%2F%2F%20%3C--%20This%20marks%20%60S%60%20as%20unused%0D%0A%20%20%20%20errornousFn2(toppings%3A%20T%20%7C%20S)%20%7B%20%7D%20%2F%2F%20%3C--%20This%20marks%20%60S%60%20as%20unused%0D%0A%20%20%20%20%2F%2F%20workingFn(toppings%3A%20T)%3A%20S%20%7B%20return%20null%3B%20%7D%20%2F%2F%20%3C--%20This%20works%0D%0A%7D%0D%0A%0D%0Aclass%20PizzaMargherita%20extends%20Pizza%3CMargheritaToppings%2C%20number%3E%20%7B%20%7D%0D%0A%0D%0Atype%20ExtractSecond%3CP%3E%20%3D%20P%20extends%20Pizza%3Cany%2C%20infer%20T%3E%20%3F%20T%20%3A%20never%3B%0D%0A%0D%0Alet%20a%3A%20ExtractSecond%3CPizzaMargherita%3E%3B%20%2F%2F%20%3C--%20%60a%3A%20%7B%7D%60%20for%20%60A%60%20if%20%60errornousFn%60%20is%20uncommented%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%20%20%20%20and%20%60a%3A%20number%60%20if%20%60workingFn%60%20is%20uncommented%20)

**Related Issues:** Only something similar yet not quite the same IMO in [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot)

**Comment by jcalz** [comment]
Maybe @RyanCavanaugh has some authoritative explanation for the following behavior:

```ts
type FromUnion<T> = [T] extends [infer U | infer V] ? [U, V] : never
type U = FromUnion<{a: 0} | {b: 0}>; 
// type U = [{a: 0} | {b: 0}, {a: 0} | {b: 0}] 

type FromIntersection<T> = [T] extends [infer U & infer V] ? [U, V] : never
type I = FromIntersection<{a: 0} & {b: 0}>; 
// type I = [unknown, unknown]
```
[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgTgewLYFUB2BLBaA8AVAPigF4oBtPAXSggA9gI0ATAZ3IzQDMI4oUoAPlA7deANWoB+cigA0UCVABcUNBABuPAFChIfErESpM2HAG8AhioAMAX0FQzAIxu2CAbihaA9N6i7oflIyS1cHZ1d5UKg7cJcY20otHXBoeGQASTQGOBYIAGNgLFxCAwpqOgZmNjIRHn0AMmEuesVpMjkFahU1TTgUvQyDdKQsnLzC4vMrBKgmiISPL19-VKgh4IBXNABrNAQAdzR5bb3DtEogA)

Obviously you can't reliably recover `A` and `B` from either `A | B` or `A & B`.  But I'm surprised that `FromIntersection<T>` doesn't produce the same `[T, T]` output that `FromUnion<T>` does.  The compiler is free to do whatever it likes in such inferences, but if completely forgetting about `T` in `[T] extends [infer U & infer V]` is intentional (and why) or if it just happens to be that way.  I'm used to the union behavior but this is the first time I've seen the intersection behavior.

I'm trying to find a good canonical answer for [this SO question](https://stackoverflow.com/q/72078498/2887218), and while I'm happy to give the advice "you should never be writing `infer U | infer V` or `infer U & infer V`", it would be nice to have an explanation for why it goes wrong the way it goes wrong.
