### ISSUE TITLE
New Website Logo: Abacus

### ISSUE THREAD

**Issue by thomasmost** [microsoft/TypeScript#29663]
- Name: Abacus
- Homepage url: https://www.abacus.com/
- Brand Guidelines/Licensing: not currently published online, just don't alter the SVG, please :)
- Logo: https://www.abacus.com/img/logo/abacusNewLogo.svg

**Comment by EvanCarroll** [comment]
Are you just spamming the issue system?

**Comment by DanielRosenwasser** [comment]
Nope https://github.com/Microsoft/TypeScript/labels/Website%20Logo

**Comment by thomasmost** [comment]
lol, thanks @DanielRosenwasser

**Comment by thomasmost** [comment]
We may want to add 'Apply the Website Logo label' to the template instructions linked to from the website, here: https://github.com/microsoft/typescript/issues/new?title=New+Website+Logo%3A+%5Binsert+name%5D%0A&body=Please+fill+the+following+out%3A%0A%0A-+Name%3A+%28correctly+formatted%29%0A-+Homepage+url%3A+%28homepage%2Fprimary+entry+point+for+users%29%0A-+Brand+Guidelines%2FLicensing%3A+%28or+anything+we+need+to+know+before+using+your+logo%29%0A-+Logo%3A+%28svg+if+possible%2C+pngs+over+500x200px+with+transparent+backgrounds+are+also+acceptable%29%0A%0A%3E+Example%3A%0A%3E%0A%3E+Name%3A+Microsoft%0A%3E+Homepage+url%3A+https%3A%2F%2Fmicrosoft.com%0A%3E+Brand+Guidelines%2FLicensing%3A+https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Flegal%2Fintellectualproperty%2Ftrademarks%2Fusage%2Flogo.aspx%0A%3E+Logo%3A+https%3A%2F%2Fnews.microsoft.com%2Fmicrosoft-news-center-photos%2Fmsft_logo_rgb_c-gray%2F%0A

**Comment by DanielRosenwasser** [comment]
External users can't add labels - maybe we can get the bot to automate this.

**Comment by thomasmost** [comment]
Any update on this?

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
