### ISSUE TITLE
Expose the applyChangedToOpenFiles internal TS Server command

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#29667]
**Request**
VS Code would like to use the  `applyChangedToOpenFiles` TS Server command in order to more efficiently perform batch files changes #29598. This command is currently marked internal

(Possibly also change the command name to `applyChangesToOpenFiles`)

**Comment by sheetalkamat** [comment]
@mjbvz as part for this, I am assuming you are going to be sending changes to be applied to the existing files as well. Currently changed Open file takes list of file name and corresponding list of text span and new string to be applied in the file. But `ChangeRequest` that vscode uses takes start and end line and offset. What do you intend to use here ? Start and End positions or their line and offset positions?
```ts
    /**
     * Arguments to ApplyChangedToOpenFilesRequest
     */
    /* @internal */
    export interface ApplyChangedToOpenFilesRequestArgs {
        /**
         * List of newly open files
         */
        openFiles?: ExternalFile[];
        /**
         * List of open files files that were changes
         */
        changedFiles?: ChangedOpenFile[];
        /**
         * List of files that were closed
         */
        closedFiles?: string[];
    }


    /**
     * Arguments for change request message.
     */
    export interface ChangeRequestArgs extends FormatRequestArgs {
        /**
         * Optional string to insert at location (file, line, offset).
         */
        insertString?: string;
    }
```

**Comment by sheetalkamat** [comment]
Also the changes are applied in reverse order in the current request format. Is that what is expected for new command?

**Comment by mjbvz** [comment]
I think start/end positions would be the most consistent. This is how `change` and `format` work. There's a `CodeEdit` type in the server protocol that may work for this.

I would also expect that the changes are made in array order, instead of in reverse order
