### ISSUE TITLE
api/tsserverlibrary.d.ts generated by jake and gulp differ

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#29664]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

when running tests for api, the baseline for `api/tsserverlibrary.d.ts` is different with jake and gulp.
Jake generates `ExternalProject::getExcludedFiles()` return type as 
```
getExcludedFiles(): readonly NormalizedPath[];
```

while gulp generates it as:
```
getExcludedFiles(): ReadonlyArray<NormalizedPath>;
```
Note the return type is inferred so seems like one is using `lib/tsserver.js` and other is using `built/local/tsserver.js`
**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
@rbuckton @weswigham can you please look.

**Comment by ahejlsberg** [comment]
Wes and I were looking at this yesterday. It's because gulp uses the LKG compiler to generate the API files where jake uses the locally built compiler. I think we should just use the LKG compiler always and then make sure to update LKG before we release anything.
