### ISSUE TITLE
Required<T> not working

### ISSUE THREAD

**Issue by imcotton** [microsoft/TypeScript#29675]
**TypeScript Version:** 
- 3.4.0-dev.20190131
- 3.3.1

**Search Terms:**
```required in:title```

**Code**
> in `strict` mode
```ts
const n = Math.random() > 0.5 ? 42 : undefined;

const obj = { n };

type Req = Required<typeof obj>;
```

**Expected behavior:**
`Req` should be `{ n: number }`

**Actual behavior:**
`Req` is `{ n: number | undefined }`

**Playground Link:** 
[link](https://www.typescriptlang.org/play/index.html#src=const%20n%20%3D%20Math.random()%20%3E%200.5%20%3F%2042%20%3A%20undefined%3B%0A%0Aconst%20obj%20%3D%20%7B%20n%20%7D%3B%0A%0Atype%20Req%20%3D%20Required%3Ctypeof%20obj%3E%3B)

**Comment by AnyhowStep** [comment]
`Required` only removes the `?` (optional modifier) from a type's fields.

It doesn't change the data type.

**Comment by fatcerberus** [comment]
I thought `?` was just shorthand for `| undefined` in practice?  Does the compiler treat them differently?

**Comment by AnyhowStep** [comment]
I personally treat them differently.

For example, a setting/config that is dangerous to not set but may have situations where not setting it is appropriate.

```ts
interface Config {
    dangerousToNotSet : number|undefined,
    safeToNotSet? : number,
}

//Error, field dangerousToNotSet must be present
const config : Config = {};
```

**Comment by fatcerberus** [comment]
I know they are different at runtime, I was pointing out that in most cases TypeScript treats the two cases as equivalent for the purpose of type checking, so it’s surprising that they differ here.
