### ISSUE TITLE
Different behavior between inline type and type alias

### ISSUE THREAD

**Issue by ozum** [Microsoft/TypeScript#29677]
**TypeScript Version:**  3.4.0-dev.20190131

I'm trying to find base types of some class properties. For example, for a given `X[]`, trying to find `X`.

I use same definition inline and as a type alias. Type alias has error whereas inline type works.

**Search Terms:** Type alias, different behavior, conditional

**Code**

Below is simplified version of the actual code. Generics `A1` and `A2` in class method `whereRelated` are equal, except `A1` uses inline type and `A2` uses a type alias.

```ts
interface RelationFields {
  x: A;
  y: A[];
  z: A[];
}
type Name = keyof RelationFields;
type ShouldA<RF extends RelationFields, N extends Name> = RF[N] extends A[] ? RF[N][0] : never;

class A {
  x: A;
  y: A[];
  z: A[];

  whereRelated<
    RF extends RelationFields = RelationFields,
    N extends Name = Name,
    A1 extends A = RF[N] extends A[] ? RF[N][0] : never, // Works
    A2 extends A = ShouldA<RF, N> // Type is same as A1, but is not assignable to type A
  >(): number {
    return 1;
  }
}

```

**Expected behavior:**

Either both `A1` and `A2` work or both have errors.

**Actual behavior:** 

`A1` works, but `A2` has an error: `... Type 'RelationFields[N][0]' is not assignable to type 'A'.`

**Playground Link:** [See here](https://www.typescriptlang.org/play/#src=interface%20RelationFields%20%7B%0D%0A%20%20x%3A%20A%3B%0D%0A%20%20y%3A%20A%5B%5D%3B%0D%0A%20%20z%3A%20A%5B%5D%3B%0D%0A%7D%0D%0Atype%20Name%20%3D%20keyof%20RelationFields%3B%0D%0Atype%20ShouldA%3CRF%20extends%20RelationFields%2C%20N%20extends%20Name%3E%20%3D%20RF%5BN%5D%20extends%20A%5B%5D%20%3F%20RF%5BN%5D%5B0%5D%20%3A%20never%3B%0D%0A%0D%0Aclass%20A%20%7B%0D%0A%20%20x%3A%20A%3B%0D%0A%20%20y%3A%20A%5B%5D%3B%0D%0A%20%20z%3A%20A%5B%5D%3B%0D%0A%0D%0A%20%20whereRelated%3C%0D%0A%20%20%20%20RF%20extends%20RelationFields%20%3D%20RelationFields%2C%0D%0A%20%20%20%20N%20extends%20Name%20%3D%20Name%2C%0D%0A%20%20%20%20A1%20extends%20A%20%3D%20RF%5BN%5D%20extends%20A%5B%5D%20%3F%20RF%5BN%5D%5B0%5D%20%3A%20never%2C%20%2F%2F%20Works%0D%0A%20%20%20%20A2%20extends%20A%20%3D%20ShouldA%3CRF%2C%20N%3E%20%2F%2F%20Type%20is%20same%20as%20A1%2C%20but%20is%20not%20assignable%20to%20type%20A%0D%0A%20%20%3E()%3A%20number%20%7B%0D%0A%20%20%20%20return%201%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Related Issues:** #15973 seems similar, but I can not be sure. If this is an expected behavior, an advise how to use a type alias is appreciated.

Thanks,

**Comment by AnyhowStep** [comment]
I've run into similar problems before. Not quite your exact situation, though.


Myack-y workaround is to add a comment saying I'm about to use a workaround, and then do,

```ts
//For some reason, I need to surround this with Extract<>
//TODO Investigate
A2 extends A = Extract<ShouldA<RF, N>, A>
```

**Comment by ozum** [comment]
@AnyhowStep Thanks for the tip for `Extract`. I will wrap original alias with `Extract` until finding a direct solution:

`type ShouldA<RF extends RelationFields, N extends Name> = Extract<RF[N] extends A[] ? RF[N][0] : never, A>;`

**Comment by jack-williams** [comment]
I'm wondering if #29698 is also fundamentally related to this---inlining `Record` produces the correct errors.

**Comment by weswigham** [comment]
@jack-williams nope.
