### ISSUE TITLE
"Import star" syntax malfunctions with modules, that expose non-enumerable API properties (commonjs)

### ISSUE THREAD

**Issue by Veetaha** [Microsoft/TypeScript#29687]
**This issue rises when specifying `"esmoduleInterop": true` option**
Tried to reproduce the issue with `typescript@next`, but that didn't fix it.

**Search Terms:**
* import star bug
* esmoduleInterop bug
* modules with not enumerable properties
* __importStar

It may seem ridiculous, but there exist modules that define their exports as not enumerable properties.
I've stumbled this issue with a simple npm ['colors'](https://www.npmjs.com/package/colors) module for colorizing console log output. I don't think we should blame their code as this library was written in pure JavaScript, but it defines some of its functions in the [following way](https://github.com/Marak/colors.js/blob/master/lib/colors.js#LC93), like:

```js
descriptor[key] = {
  get: function() {
      return build(key);
  },
};
Object.defineProperties(module.exports, descriptor);
```
 I would have never browsed their JavaScript code, but when I tried to export `'colors'` module and use its function `Colors.gray()` exported in the way explained above I got `'TypeError: Colors.gray is not a function'`.

**Code**

```ts
import * as Colors from 'colors';
Colors.gray('');
```

**Expected behavior:**
`Colors.gray('')` should just return a string as it is supposed to.

**Actual behavior:**
`'TypeError: Colors.gray is not a function'`

**Core problem**
With `esmoduleInterop` option all `import * Foo from 'mod'` statements transfigure into `__importStar(require('mod'))`, but this function is defined like so:
```ts
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
}
```
Thus returned object doesn't contain non-enumerable properties exposed by `mod`.
With `"esmoduleInterop": false` there is no `__importStar()` function generated, so the issue doesn't arise.

**Comment by RyanCavanaugh** [comment]
The alternative - exposing all non-enumerable properties as if they were own properties - seems much worse (and would be a runtime breaking change). Probably best to leave that flag off if you have modules which behave very differently from ES modules in terms of ownness/enumerability.

**Comment by khuttun** [comment]
This behavior can actually cause nasty surprises as it might silently break your code when converting a module from JS to TS. I don't have any concrete proposal on how to fix it, but I'm thinking whether it would make more sense to use `esModuleInterop: false` to avoid this in the future.

**Comment by khuttun** [comment]
The docs now warn about this behavior: https://www.typescriptlang.org/tsconfig#esModuleInterop
