### ISSUE TITLE
Outdated example code in typescript/gulp docs

### ISSUE THREAD

**Issue by AdrianSchneble** [microsoft/TypeScript#29683]
In the [typescript + gulp docs](https://www.typescriptlang.org/docs/handbook/gulp.html), there's an error in the example code.

The existing code, which defines a task that should depend on another task called `copy-html`, looks like this:

`gulp.task("default", ["copy-html"], function () {...});`

Since gulp 4, dependencies work differently. To achieve the same result, the following code would be correct:

`gulp.task("default", gulp.series("copy-html", function () {...}));`

If someone could fix this problem (which occurs more than once in the linked docs; use CTRL+F), you'd probably save numerous beginners from identical google searches ^^

**Comment by jakebailey** [comment]
This was fixed in the website a long time ago.
