### ISSUE TITLE
Function return-type with decomposition not inferred correctly

### ISSUE THREAD

**Issue by donnut** [Microsoft/TypeScript#2968]
```typescript
interface IAddressBook {}
interface INavModel {}

function foo() {
    let a: IAddressBook = {};
    let b: INavModel[] = [];
    return [a, b];
}

let [p, q] = foo();

let x: IAddressBook = p;
let y: INavModel[] = q;  // <- error
```
tsc (1.5.0-alpha) complains: 
```shell
destruction.ts(13,5): error TS2322: Type 'IAddressBook' is not assignable to type 'INavModel[]'.
  Property 'length' is missing in type 'IAddressBook'.
```
atom-typescript shows that foo has signature `foo(): IAddressBook[]` and both `p` and `q` have type `IAddressBook`

The error is solved when specifying the return type of `foo` explicitly like:
```typescript
function foo():  [IAddressBook, INavModel[]] {...}
```

Is this a known/explainable issue?

**Comment by RyanCavanaugh** [comment]
We don't infer tuple types from array literals.

If you write code like this:
```ts
var x = [cat, dog, animal];
x[0] = new Dog(); // OK or not?
```
We could either infer `x`'s type as `[Cat, Dog, Animal]`, or `Animal[]`. If we do the former, the next line of code is an error; if we do the latter, it's not.

It's arguable in the abstract which behavior is preferable (you can make convincing examples either way just by changing the names of the variables), but we shipped the `Animal[]` behavior and didn't want to have a breaking change.
