### ISSUE TITLE
Object.setPrototypeOf doesn't return the right type?

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#29693]
I am on on tsc 3.2.1

```typescript
export class ResolveCallback extends Function {
  resolve = true;
}

export class RejectCallback extends Function {
  reject = true;
}


const runResolve = function (cb : ResolveCallback) {};
const runReject = function (cb : RejectCallback) {};

runResolve(Object.setPrototypeOf(() => {}, ResolveCallback));
runReject(Object.setPrototypeOf(() => {}, ResolveCallback));  // this compiles, but shouldn't

// but that last line should be error, it should only compile if it's RejectCallback, isn't that right?

```

**Comment by ORESoftware** [comment]
Technically it should look like this:

```typescript
export class ResolveCallback extends Function {
  resolve = true;
}

export class RejectCallback extends Function {
  reject = true;
}


const runResolve = function (cb : ResolveCallback) {
 console.log(cb.resolve);
 cb();
};

const runReject = function (cb : RejectCallback) {
  console.log(cb.reject);
  cb();
};

runResolve(Object.setPrototypeOf(() => {
   console.log('cats');
}, new ResolveCallback()));

runReject(Object.setPrototypeOf(() => {
  console.log('dogs');
}, new ResolveCallback()));
```

but the same problem remains AFAICT

**Comment by ORESoftware** [comment]
@lucasbasquerotto yeah ultimately the goal is simple and common - to give a type to a vanilla callback function. 99.99% of vanilla callback functions are only defined by their return type and parameters. But if we could give those functions unique properties, we could "tag" them - thereby differentiate between two functions with the same return type and same parameter types!! :)

**Comment by ORESoftware** [comment]
Instead of Object.setPrototypeOf returning any, why doesn't it return the type of the second argument? Or the union of the first and second arguments?

**Comment by ORESoftware** [comment]
@lucasbasquerotto ftr, this seems to work:

```typescript
const wrap = function<T>(x: object, v: T) :  T {
  return Object.setPrototypeOf(x, <any>v);
};

runResolve(wrap(() => {
   console.log('cats');
}, new ResolveCallback()));

runReject(wrap(() => {
  console.log('dogs');
}, new RejectCallback()));
```

but I agree, I don't think it will be useful because most people will not want to adopt this pattern

**Comment by Veetaha** [comment]
Maybe it's not too mush related, but since 3.1 you may assign new properties to functions (only functions) dynamically in your code without creating boilerplate namespace and interface, and tsc will catch that extensions (as you call them tags) very gracefully. See [3.1 list of changes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html)

**Comment by ORESoftware** [comment]
I have a solution to this, but it's unlikely TS will implement it anytime soon. I have been doing some Java recently, and TS could use their style of lambdas in order to have types for otherwise vanilla/naked callbacks.

It just looks like:

```ts
interface HasOnlyOneMethod {
  public run(cb: HasOnlyOneMethod);
}

const usesACallbackFunction  = (cb: HasOnlyOneMethod) => {
  cb(); // firing cb() is the same as cb.run()
};
```

and then you could use it like so:

```ts
usesACallbackFunction(new HasOnlyOneMethod(){
   public run(cb){

   }
});
```

and with the TS compiler, that would be the same as:

```ts
usesACallbackFunction(cb => {
   // you can fire cb();
   // or you can fire cb.run(); 
   // those two calls are the same
});
```

**Comment by qm3ster** [comment]
@ORESoftware you can specify the call signature like this: 
```ts
interface HasOnlyOneMethod {
  (cb: HasOnlyOneMethod): "called"
  (): "overloaded"
  new(): "new chungus"
  /* other properties here */
  [key: string]: 0
}

declare const a: HasOnlyOneMethod

const called = a(a) // "called"
const overloaded = a() // "overloaded"
const newed = new a() // "new chungus"
const indexed = a['']  // 0
```
[Try it online!](https://www.typescriptlang.org/play/#src=interface%20HasOnlyOneMethod%20%7B%0D%0A%20%20(cb%3A%20HasOnlyOneMethod)%3A%20%22called%22%0D%0A%20%20()%3A%20%22overloaded%22%0D%0A%20%20new()%3A%20%22new%20chungus%22%0D%0A%20%20%2F*%20other%20properties%20here%20*%2F%0D%0A%20%20%5Bkey%3A%20string%5D%3A%200%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20a%3A%20HasOnlyOneMethod%0D%0A%0D%0Aconst%20called%20%3D%20a(a)%20%2F%2F%20%22called%22%0D%0Aconst%20overloaded%20%3D%20a()%20%2F%2F%20%22overloaded%22%0D%0Aconst%20newed%20%3D%20new%20a()%20%2F%2F%20%22new%20chungus%22%0D%0Aconst%20indexed%20%3D%20a%5B''%5D%20%20%2F%2F%200)

**Comment by ORESoftware** [comment]
@qm3ster  I got a is not defined

**Comment by kwasimensah** [comment]
I just ran into this working with IndexedDB. It doesn't save protoypes across a set/get from an objectstore which kinda makes sense. 

Happy to do an explicit cast but it seems repetitive
