### ISSUE TITLE
`Extract<keyof T, string>` breaks inference for deep keys.

### ISSUE THREAD

**Issue by FrogTheFrog** [Microsoft/TypeScript#29692]
**TypeScript Version:**  3.4.0-dev.20190201

**Search Terms:**
Extracting string from key breaks inference;
`Extract<keyof T, string>` breaks inference;
`Extract<keyof T, string>` breaks inference for deep keys;

**Code**

```ts
interface DeepObject {
    [k1: string]: {
        [k2: string]: any
    };
}

type keys2broken<O extends DeepObject, K1 extends keyof O> =
    O[K1] extends object ? Extract<keyof O[K1], string> : never;

type keys2working<O extends DeepObject, K1 extends keyof O> =
    O[K1] extends object ? keyof O[K1] : never;

type keys2workaround<O extends DeepObject, K1 extends keyof O> =
    Extract<O[K1] extends object ? keyof O[K1] : never, string>;

interface Foo extends DeepObject {
    "a": {
        "1": 123;
        "2": string;
        "3": boolean;
    };
}

class Bar<O extends DeepObject>{
    broken<
        K1 extends keyof O,
        K2 extends keys2broken<O, K1>,
        V extends O[K1][K2]
    >(k1: K1, k2: K2, value: V) {
    }

    working<
        K1 extends keyof O,
        K2 extends keys2working<O, K1>,
        V extends O[K1][K2]
    >(k1: K1, k2: K2, value: V) {
    }

    workaround<
        K1 extends keyof O,
        K2 extends keys2workaround<O, K1>,
        V extends O[K1][K2]
    >(k1: K1, k2: K2, value: V) {
    }
}

const bar = new Bar<Foo>();
bar.broken("a", "1", true); // broken - 2nd argument is of type "1" | "2" | "3".
bar.working("a", "1", true); // ok - true is not allowed
bar.workaround("a", "1", true); // ok - true is not allowed
```

**Expected behavior:**
`bar.broken("a", "1", true);` should infer type `"1"`.

**Actual behavior:**
`bar.broken("a", "1", true);` infers type `"1" | "2" | "3"`.

**Playground Link:** 
[some smart text, a.k.a. bad sense of humour](https://www.typescriptlang.org/play/index.html#src=interface%20DeepObject%20%7B%0D%0A%20%20%20%20%5Bk1%3A%20string%5D%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bk2%3A%20string%5D%3A%20any%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Atype%20keys2broken%3CO%20extends%20DeepObject%2C%20K1%20extends%20keyof%20O%3E%20%3D%0D%0A%20%20%20%20O%5BK1%5D%20extends%20object%20%3F%20Extract%3Ckeyof%20O%5BK1%5D%2C%20string%3E%20%3A%20never%3B%0D%0A%0D%0Atype%20keys2working%3CO%20extends%20DeepObject%2C%20K1%20extends%20keyof%20O%3E%20%3D%0D%0A%20%20%20%20O%5BK1%5D%20extends%20object%20%3F%20keyof%20O%5BK1%5D%20%3A%20never%3B%0D%0A%0D%0Atype%20keys2workaround%3CO%20extends%20DeepObject%2C%20K1%20extends%20keyof%20O%3E%20%3D%0D%0A%20%20%20%20Extract%3CO%5BK1%5D%20extends%20object%20%3F%20keyof%20O%5BK1%5D%20%3A%20never%2C%20string%3E%3B%0D%0A%0D%0Ainterface%20Foo%20extends%20DeepObject%20%7B%0D%0A%20%20%20%20%22a%22%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%221%22%3A%20123%3B%0D%0A%20%20%20%20%20%20%20%20%222%22%3A%20string%3B%0D%0A%20%20%20%20%20%20%20%20%223%22%3A%20boolean%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%3CO%20extends%20DeepObject%3E%7B%0D%0A%20%20%20%20broken%3C%0D%0A%20%20%20%20%20%20%20%20K1%20extends%20keyof%20O%2C%0D%0A%20%20%20%20%20%20%20%20K2%20extends%20keys2broken%3CO%2C%20K1%3E%2C%0D%0A%20%20%20%20%20%20%20%20V%20extends%20O%5BK1%5D%5BK2%5D%0D%0A%20%20%20%20%3E(k1%3A%20K1%2C%20k2%3A%20K2%2C%20value%3A%20V)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20working%3C%0D%0A%20%20%20%20%20%20%20%20K1%20extends%20keyof%20O%2C%0D%0A%20%20%20%20%20%20%20%20K2%20extends%20keys2working%3CO%2C%20K1%3E%2C%0D%0A%20%20%20%20%20%20%20%20V%20extends%20O%5BK1%5D%5BK2%5D%0D%0A%20%20%20%20%3E(k1%3A%20K1%2C%20k2%3A%20K2%2C%20value%3A%20V)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20workaround%3C%0D%0A%20%20%20%20%20%20%20%20K1%20extends%20keyof%20O%2C%0D%0A%20%20%20%20%20%20%20%20K2%20extends%20keys2workaround%3CO%2C%20K1%3E%2C%0D%0A%20%20%20%20%20%20%20%20V%20extends%20O%5BK1%5D%5BK2%5D%0D%0A%20%20%20%20%3E(k1%3A%20K1%2C%20k2%3A%20K2%2C%20value%3A%20V)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20bar%20%3D%20new%20Bar%3CFoo%3E()%3B%0D%0Abar.broken(%22a%22%2C%20%221%22%2C%20true)%3B%20%2F%2F%20broken%20-%20true%20is%20allowed%2C%20because%202nd%20argument%20is%20of%20type%20%221%22%20%7C%20%222%22%20%7C%20%223%22.%0D%0Abar.working(%22a%22%2C%20%221%22%2C%20true)%3B%20%2F%2F%20ok%20-%20true%20is%20not%20allowed%0D%0Abar.workaround(%22a%22%2C%20%221%22%2C%20true)%3B%20%2F%2F%20ok%20-%20true%20is%20not%20allowed%0D%0A) 

**Related issues:**
https://github.com/Microsoft/TypeScript/issues/25065

**Comment by jack-williams** [comment]
This is fixed in master, presumably by #30010.
