### ISSUE TITLE
Can't compare subtypes to a type constrained by base types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#29697]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
function f<E extends Element>(el: E) {
  el === document.body; // error
  el as Element === document.body; // ok
}
```

**Expected behavior:**

pass

**Actual behavior:**

This condition will always return 'false' since the types 'E' and 'HTMLElement' have no overlap.

**Playground Link:** 

http://www.typescriptlang.org/play/index.html#src=function%20f%3CE%20extends%20Element%3E(el%3A%20E)%20%7B%0A%20%20el%20%3D%3D%3D%20document.body%3B%20%2F%2F%20error%0A%20%20el%20as%20Element%20%3D%3D%3D%20document.body%3B%20%2F%2F%20ok%0A%7D

**Related Issues:** 

#27910, #23132

**Comment by falsandtru** [comment]
At least that error message is wrong. 'E' and 'HTMLElement' have much overlap.

@DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
I believe this is the same as #20821 but again, just curious what the use case is where using `Element` isn't okay.

**Comment by falsandtru** [comment]
Why this basic usage is not enough? FYI, this problem was discovered as follows:

https://github.com/falsandtru/typed-dom/blob/v0.0.120/src/dom/manager.ts#L219

>#20821

I'm not sure comparing and casting should be treated as the same thing in fixing.
