### ISSUE TITLE
Add option for nesting TypeScript output in project

### ISSUE THREAD

**Issue by SeriousM** [Microsoft/TypeScript#297]
When I save a TypeScript file it generates the javascript and map file as it should be. The problem is that the generated files are NOT automatically added to the project file references. This is a big problem since we're using T4MVC which doesn't create links to those files. Another problem is that the web-publish doesn't publish js files since they are unknown (not in project). 

Are there any plans to nest the .js and .map files under the .ts files on generation?

As a back reference to codeplex: https://typescript.codeplex.com/workitem/2497

**Comment by chrismbarr** [comment]
I would also love to see an **option** for this added.  Since there are good reasons on both sides, why not just keep the current behavior as the default, and add options in the Visual Studio preferences (`Options > Text Editor > TypeScript > General`).

* An option to have these file auto-included
* Another option to also auto-nest the generated files

**Comment by paulvanbrenk** [comment]
It's curious that the publishing doesn't work, since it we made changes to make it work with regular asp.net projects. 

I'll investigate to see if can find something, but a small sample project which shows the problem would be greatly appreciated!

**Comment by mhegazy** [comment]
@paulvanbrenk we probably should open an new issue for this for 1.5

**Comment by mhegazy** [comment]
JS files (as well as .map, .d.ts) are considered outputs and thus not included in the project. Building, publishing, etc.. should all work correctly, if not these are bugs we need to fix.
Nesting output files under sources is a feature that can be achieved manually or using a tool like WebEssetials, but it is out of scope of the TypeScript project.
