### ISSUE TITLE
Extending class method and "this" scoped Return Values

### ISSUE THREAD

**Issue by reggi** [microsoft/TypeScript#29709]
I created a `FileHandler` class with methods to read a file or many files like this.

```
export class FileHandler {
    private static async readFileFromFileQuery (fq: FileQuery): Promise<File> {
        const { path, encoding, flag } = FileQueryHandler.make(fq);
        const content = await promisify(fs.readFile)(path, { encoding, flag })
        return { path, encoding, flag, content };
    }
    static async readFile (a: Path | FileQuery, b?: Omit<FileQuery, 'path'>): Promise<File> {
        if (typeof a === 'string') a = FileQueryHandler.getFromPath(a, b);
        return FileHandler.readFileFromFileQuery(a);
    }
    static async readFiles (a: (Path | FileQuery)[] | Directory, b?: Omit<FileQuery, 'path'>): Promise<File[]> {        
        if (a instanceof Array) return Promise.all(a.map(p => this.readFile(p, b)));
        return FileHandler.readFiles(PathHandler.getFromDirectory(a), b);
    }
    static async readFilesFromDirectory(a: Path | FileQuery, b?: Omit<FileQuery, 'path'>): Promise<File[]> {
        const ps = await DirectoryHandler.readDirectory(a);    
        if (typeof a === 'string') return await FileHandler.readFiles(ps, b);
        return await FileHandler.readFiles(ps, a);
    }
}
```

This is a class with `static` methods because I don't need them to be public.

What I would like to do now is expand upon this class.

I would like to wrap the `FileHandler.readFile` in a try catch and possibly return null, something like this, where the method is named `readFile` but the return value is different from the original.

```
export class FileOrNullHandler {
    async readFile (a: Path | FileQuery, b?: Omit<FileQuery, 'path'>): Promise<File | null> {
        return orNull(() => FileHandler.readFile(a, b));
    }
}
```

I would also like to get all the other methods for free because what I see is all the original `FileHandler` are based on `FileHandler.readFile`.

I've tried some ways of converting both to not use `static` methods, and I've also experimented with return types, but nothing is jumping out at me as the simple way to do this.

What I need is the following:

* Have parity between methods within both classes
* Have all the return values represent the class functionality

I am looking for the best way to do this.

Ideally, the first thing that comes to mind would be I would be able to use 

* `static` methods that call `this`
* `ReturnType<this.method>`

But both of those things do not exist.

What I want is the following result:

* `FileHandler.readFile` that returns `File `
* `FileHandler.readFiles` that returns `File[]`
* `FileHandler.readFilesFromDirectory` that returns `File[]`
* `FileOrNullHandler.readFile` that returns `(File | null)`
* `FileOrNullHandler.readFiles` that returns `(File | null)[]`
* `FileOrNullHandler.readFilesFromDirectory` that returns `(File | null)[]`

I'm not 100% what I am advocating here. I am looking for recommendations on how someone would achieve this API, and how possible typescript might come up short. 

## Search Terms

classes, class, es6, method, static this, return type method, return type this

## Suggestion

* `ReturnType<this.method>`

## Use Cases

Compositionally extending classes

## Examples

Above

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by reggi** [comment]
However, this does not work:

```ts
class Example {
    static alpha (color: string): boolean {
        return (color === 'red') ? true : false;
    }
}

type AlphaReturn = ReturnType<Example['alpha']>
```

**Comment by reggi** [comment]
The functionality I want from typescript is the following:

This would allow all the new methods within `FileOrNullHandler` to have the proper return types.

```
export class FileHandler {
    static async readFileFromFileQuery (fq: FileQuery): Promise<File> {
        const { path, encoding, flag } = FileQueryHandler.make(fq);
        const content = await promisify(fs.readFile)(path, { encoding, flag })
        return { path, encoding, flag, content };
    }
    static async readFile (a: Path | FileQuery, b?: Omit<FileQuery, 'path'>): Promise<ReturnType<this.readFileFromFileQuery>> {
        if (typeof a === 'string') a = FileQueryHandler.getFromPath(a, b);
        return this.readFileFromFileQuery(a);
    }
    static async readFiles (a: (Path | FileQuery)[] | Directory, b?: Omit<FileQuery, 'path'>): Promise<ReturnType<this.readFileFromFileQuery>[]> {
        if (a instanceof Array) return Promise.all(a.map(p => this.readFile(p, b)));
        return this.readFiles(PathHandler.getFromDirectory(a), b);
    }
    static async readFilesFromDirectory(a: Path | FileQuery, b?: Omit<FileQuery, 'path'>): Promise<ReturnType<this.readFileFromFileQuery>[]> {
        const ps = await DirectoryHandler.readDirectory(a);    
        if (typeof a === 'string') return await this.readFiles(ps, b);
        return await this.readFiles(ps, a);
    }
}

export class FileOrNullHandler extends FileHandler {
    static async readFileFromFileQuery (fq: FileQuery): Promise<File | null> {
        return orNull(() => FileHandler.readFileFromFileQuery(fq));
    }
}
```

I don't believe this functionality exists, now within TypeScript.

How can I even get this working without these features?

**Comment by fazouane-marouane** [comment]
With your requirements, you cannot have this: `FileOrNullHandler extends FileHandler`. Otherwise `(File | null) extends File` which not possible (you cannot assign null to File).

How about using interfaces and mapped types?

If you absolutely need static methods, then I'd suggest the follwing:

```ts
class File{}
// For simplicity sake, let's keep the example to a minimum
class FileHandler {
  static readFile(): Promise<File> {
    return {} as any;
  }
  static readFiles(): Promise<File[]> {
    return {} as any;
  }
}

// Here is what you want to have
interface FileOrNullHandlerConstructor extends NullifyConstructor<typeof FileHandler> {
  new (...args: any[]) : any;
}

const FileOrNullHandler = (function FileOrNullHandler() {} as any) as FileOrNullHandlerConstructor;
implementStaticMethods(FileOrNullHandler, FileHandler);
// use it however you want

// has signature readFiles(): Promise<(File | null)[]>
FileOrNullHandler.readFiles() //...

// helpers

// Transforms Promise<Stuff[]> into Promise<(Stuff | null)[]>
type Nullify<T> = T extends Promise<Array<infer A>>
  ? Promise<Array<A | null>>
  : T extends Promise<infer A>
  ? Promise<A | null>
  : T extends Array<infer A>
  ? Array<A | null>
  : T | null;
// transforms {method(a: number): Promise<Stuff[]>} into {method(a: number): Promise<(Stuff| null)[]>} using mapped types
type NullifyConstructor<T> = {
  [Key in keyof T]: T[Key] extends (
    ...args: infer TArgs
  ) => infer TResult
    ? ((...args: TArgs) => Nullify<TResult>)
    : T[Key];
};

// manually implement static methods on the deriving class using the parent's class static methods
// so, classic js stuff
type Constructor = { new (...args: any[]): any };
function implementStaticMethods(
  derivingClass: Constructor,
  parentClass: Constructor
) {
  for (const staticPropName of Object.getOwnPropertyNames(parentClass)) {
    if (!["name", "length", "prototype"].includes(staticPropName)) {
      const parentPropDescription = Object.getOwnPropertyDescriptor(
        parentClass,
        staticPropName
      );
      if (
        parentPropDescription &&
        typeof parentPropDescription.value === "function"
      ) {
        // Auto-generate static methods
        Object.defineProperty(derivingClass, staticPropName, {
          ...parentPropDescription,
          value: function(...args: any[]) {
           // use orNull() here
            try {
              return parentPropDescription.value.apply(this, args);
            } catch (e) {
              return null;
            }
          }
        });
      } else {
        Object.defineProperty(derivingClass, staticPropName, {
          ...parentPropDescription
        });
      }
    }
  }
}

```

Side note, you may want to transform `Promise<File[]>` into `Promise<(File[]) | null>` (either an array of files or `null`). `Promise<(File|null)[]>` would mean an array of files or null values. Also, IMO, stackoverflow would be a better fit for this question since it's not a feature request per-se nor a bug report.

**Comment by fazouane-marouane** [comment]
@reggi don’t forget to close this issue if it has been answered 😉

**Comment by reggi** [comment]
Are we not considering `ReturnType<this.method>`? To be a viable thing?

**Comment by fazouane-marouane** [comment]
I don't know what do you mean, but if you're referring to the following,

> However, this does not work:
> 
> > Property 'alpha' does not exist on type 'Example'.
> 
> ```ts
> class Example {
>     static alpha (color: string): boolean {
>         return (color === 'red') ? true : false;
>     }
> }
> 
> type AlphaReturn = ReturnType<Example['alpha']>
> ```

then you can use this (`typeof Example` instead of `Example`):
```ts
class Example {
  static alpha (color: string): boolean {
      return (color === 'red') ? true : false;
  }
}

// AlphaReturn would be a boolean
type AlphaReturn = ReturnType<(typeof Example)['alpha']>;
```

If you're still thinking about inheritance (I guess this is why you're saying `this`?), know that it won't work since `File | null` does not  extend `File`

**Comment by RyanCavanaugh** [comment]
> `Are we not considering `ReturnType<this.method>`? To be a viable thing?`

Two things - first the syntax would be `ReturnType<typeof this.method>`. Second, #5863.
