### ISSUE TITLE
Import statement includes preceding comment

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#2970]
(Using Typescript 1.5 Beta) With the source file below, when I walk through the nodes looking for import declarations, the first node I find is foo. The node.pos and node.end are (0,86). Why is the reference comment being lumped together with the foo import? Is there no node for the /// reference?

     /// reference path="../../definitions/chalk.d.ts" / ( Edited to show )

     import { foo } from "./foo";
     import chalk = require( 'chalk' );

     export class plugin {
         public plugFoo = new foo();
         public run( context: any ): any {
             return chalk.black( "somestring" );
         }
     }

**Comment by ToddThomson** [comment]
A follow up question is:

What is the guidance for importing 3rd party libraries using ES6 module syntax ( and compiling down to  ES5 AMD )? The only way to compile the above source file was to include a triple slash reference which seems wrong. Should I just pass a reference file with all 3rd party library dependencies to the compile context?

**Comment by DanielRosenwasser** [comment]
Hey @ToddThomson 

> Is there no node for the /// reference?

No, reference comments are themselves comments, and are considered [trivia](https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview#trivia), so they have no representation in the TypeScript core AST, though you can grab them from [`referencedFiles`](https://github.com/Microsoft/TypeScript/blob/54ef1bf93da5da56601ede26086e0f81452fda7f/src/compiler/types.ts#L1005) from the `SourceFile` type.

If you want to grab comments, you probably want to `getLeadingCommentRanges` on the *full start* of the first node in the file.

> The only way to compile the above source file was to include a triple slash reference which seems wrong.

You should also be able to pass the .d.ts file to the compiler the same way you pass in your .ts files. If you're looking for your editor to pick up on the shape of a module according to a d.ts, but you're really not big on reference comments, look into [tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json).

Does that answer your questions?

**Comment by ToddThomson** [comment]
Thanks @DanielRosenwasser . I do use the tsconfg.json project config file and I now add a reference.d.ts to the "files" list for my 3rd party libs.
I also use the tsconfig.json file for bundling my library into external AMD modules ( a shameless plug for the [TsProject](https://github.com/ToddThomson/tsproject) compiler ). I thought that I needed to utilize the referenced file to grab some dependencies, but then realized that tsconfig.json could be used as you have pointed out.
Looking forward to the 1.5 beta!

**Comment by DanielRosenwasser** [comment]
Awesome, glad to help! 1.5 beta should be on npm now, so give it a spin and keep us in the loop.
