### ISSUE TITLE
[Javascript] Go to definition doesn't work for functions in objects passed as parameters

### ISSUE THREAD

**Issue by csnv** [Microsoft/TypeScript#29716]
VSCode version: 1.30.2
OS: Mac OS 10.13.6

Search terms: Go to definition, object functions, function arguments

Steps to reproduce:
With the following code, right click on this.funcA() and choose "Go to definition".

Code:
```
var testFn = function(myProps) { };

testFn({
	funcA: function() {},
	funcB: function() {
		this.funcA();
	}
});
```
Expected behavior:
Editor jumps to funcA definition.

Actual result:
Editor does nothing.

The same example works fine if the object is outside the function call:
```
var testObj = {
	funcA: function() {},
	funcB: function() {
		this.funcA();
	}
};
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Mcfloy** [comment]
How does it concern Typescript ?

**Comment by RyanCavanaugh** [comment]
The TS/JS inference engine doesn't assume that `this` in an object literal refers to the surrounding object - this isn't at all guaranteed and will vary by how the function is called.

**Comment by csnv** [comment]
Can we have it as an option? Or maybe can we assume that this is refering to the object itself, if nothing else is found?
WebStorm (for example) identifies this case pretty well.
