### ISSUE TITLE
Proposal: Parallel async

### ISSUE THREAD

**Issue by repinvv** [Microsoft/TypeScript#29722]
## Search Terms
parallel async

## Suggestion
idea is to automatically parallelize async calls, reduce overhead of having to write Promise.all and such constructs

## Examples

Typical function
async myFunc(): Promise<Result>{
var result1 = await getResult1();
var result2 = await getResult2();
var result3 = await getResult3(result1);
return combineResult(result2, result3);
}

it might be preprocessed to something like this. 
async myFunc(): Promise<Result>{
var __result1 = getResult1();   //1
var result1 = await __result1;  
var __result2 = getResult2(); // 2
var result2 = await __result2;
var __result3 = getResult3(result1); //3
var result3 = await __result3;
return combineResult(result2, result3);
}

suggestion is to make those function calls float up during compilation, until there is a curly bracket found or an assignment to variable used as a parameter to function call
async myFunc(): Promise<Result>{
var __result1 = getResult1(); // 1
var __result2 = getResult2(); // 2
var result1 = await __result1;
var __result3 = getResult3(result1); // 3
var result2 = await __result2;
var result3 = await __result3;
return CombineResult(result2, result3);
}
Here 1 and 2 will automatically run in parallel, 3 will execute once 1 is finished.

This would be a breaking change, so new keyword might be used. Did not think it all through.

## Checklist

My suggestion meets these guidelines:

* [+/-] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [+] This wouldn't change the runtime behavior of existing JavaScript code
* [?] This could be implemented without emitting different JS based on the types of the expressions
* [+] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [?] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
I think the same effect ca be easily achieved using `Promise.all` without the need for extra syntax and with greater developer control (and without a he syntactic burden): 

```ts
async myFunc(): Promise<any> {
    var result1 = await getResult1();
    var [result2,result3] = await Promise.all([getResult2(), getResult3(result1)]
    return combineResult(result2, result3);
}
```

Adding syntax for this is also contrary to the guideline of "This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)". This would be a non-standard syntax, that is not in any ECMAScript standard, and is related to the JS output.

**Comment by fazouane-marouane** [comment]
I don't know if this would be desirable since it changes a lot the semantics. Imagine you have the following:

```ts
const doStuff = async (id: string) => {
  // I doubt that we want to run both calls in parallel.
  await createStuffToDb({ id, name: "Codesmith" });
  await deleteStuffFromDb(id);
};
```

PS: Also, it may happen that `Promise.all`/`Promise.race` does too much parallelism and that you may want to [batch](http://caolan.github.io/async/) async calls. For instance, you may have only 4 concurrent calls to db (simplistic example) or 2 simultaneous fetch calls on frontend and running, say, 10 calls may produce timeout errors etc. Or even if you run a Promise.all and one call errors, you would still need to wait for the other calls to finish, unless you have a CancellationToken mechanism of some sorts.

**Comment by WORMSS** [comment]
@fazouane-marouane I may have misinterpreted what you said.  
Did you say `Promise.all()` Promise.all waits for the other calls to finish if one of them errors? 
It was my understanding that it 'failed fast' ? or did I understand wrong?

**Comment by fazouane-marouane** [comment]
@WORMSS `Promise.all` fails as soon as one promise rejects, but the other promises won't get _cancelled_. So if you make 100 slow fetch calls and one of them fails fast, `await Promise.all(...)` would raise an exception but you're still need to be waiting for 99 pending network calls (but the browser will run 2 by 2 or 4 by 4 etc, depending on your browser). Which also means that you can make any other network calls until all the previous ones are finished.

**Comment by WORMSS** [comment]
I get what you mean now, thank you.
