### ISSUE TITLE
Map constructor should accept readonly tuples

### ISSUE THREAD

**Issue by ark120202** [Microsoft/TypeScript#29721]
**TypeScript Version:**  3.4.0-dev.20190202

**Search Terms:**

Readonly tuple, map, as const, const context

**Code**

```ts
const pairs = [['1', 1], ['2', 2]] as const
new Map(pairs);
```

**Expected behavior:**

No error

**Actual behavior:**

```
TS2345: Argument of type 'readonly [readonly ["1", 1], readonly ["2", 2]]' is not assignable to parameter of type 'readonly [{}, {}][]'.
  Type 'readonly ["1", 1] | readonly ["2", 2]' is not assignable to type '[{}, {}]'.
    Type 'readonly ["1", 1]' is missing the following properties from type '[{}, {}]': pop, push, reverse, shift, and 6 more.
```

**Playground Link:** 

**Related Issues:** 

---

The same issue applies to some libraries on DefinitelyTyped. Maybe readonly tuples should be added to [Common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes), like arrays?

**Comment by ark120202** [comment]
@sheetalkamat the same issue also applies to `WeakMap`, could it be fixed as well or should I open a new issue?

**Comment by chharvey** [comment]
@ark120202 @sheetalkamat — Can we follow up on this with `WeakMap`? I’m having the same issue as OP where I’m trying to pass a readonly array to the `WeakMap` constructor and getting a TypeError.

```diff
interface WeakMapConstructor {
-    new <K extends object = object, V = any>(entries?: readonly [K, V][] | null): WeakMap<K, V>;
+    new <K extends object = object, V = any>(entries?: readonly (readonly [K, V])[] | null): WeakMap<K, V>;
    readonly prototype: WeakMap<object, any>;
}
declare var WeakMap: WeakMapConstructor;
```
