### ISSUE TITLE
Goto Implementation should suggest all subtypes

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#29724]
Steps to reproduce:

```typescript
interface Person {
}

class Teacher implements Person {
}

class SeniorTeacher extends Teacher {
}
```

Goto implementation on `Person` only lists `Teacher`. It should list `SeniorTeacher` as well.

**Comment by fuafa** [comment]
In the situation below (it is a fourslash test in TypeScript), trigger goto implementation at `x.hello()`

![image](https://user-images.githubusercontent.com/20750310/52961344-ac1ad100-33d5-11e9-96a7-8ae86288d757.png)

jetbrains team member considers `hello` is a method of `SuperBar`, so, `NotBar.hello` should be returned, while TypeScript said `NotBar` and `Bar` are not structurally equal, so `NotBar.hello` should not be returned. Do you accept jetbrains' approach? If so, I can submit a pr for this.
