### ISSUE TITLE
readonly function arguments

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#29742]
## Search Terms

readonly parameters, readonly arguments, read only, function
## Suggestion

Allow specifying a `readonly` modifier to function and method arguments 

```ts
function foo(mutableString: string, readonly immutableString: string) {
    mutableString = 'bar' // ok
    immutableString = 'bar' // not ok
}
```
 
With https://github.com/Microsoft/TypeScript/pull/29435 we can do this for rest arguments too:

```ts
function foo(readonly ...immutableStrings: string[]) {}
// the same as
function foo(...immutableStrings: readonly string[]) {}
```

## Use Cases

There is a ESLint rule for not allowing overriding incoming function argument [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #18497
