### ISSUE TITLE
Typeguard in conditional statement wrongly types the else case. 

### ISSUE THREAD

**Issue by jawensi** [Microsoft/TypeScript#29745]
**TypeScript Version:**  3.4.0-dev.20190202

**Search Terms:** Type guard

**Code**

```ts
interface SampleStru<T> {
    decision: boolean; // Has decision about the data type.
}

class SampleClass<T, U>{

    public isTtype(input: SampleStru<T | U>): input is SampleStru<U> {
        return (input as SampleStru<U>).decision;
    }

    public sampleBug() {
        const data: SampleStru<T | U>;
        if (this.isTtype(data)) {
            // data is SampleStru<U>
        } else {
            // data is never. Expected behaviour SampleStru<T>
        }
    }
}
```

**Expected behavior:**
Since there are only two options (either data is `SampleStru<T>` or ` SampleStru<U>`) the else case should correctly type data.
**Actual behavior:**
Data is typed as never.

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=interface%20SampleStru%3CT%3E%20%7B%0D%0A%20%20%20%20decision%3A%20boolean%3B%20%2F%2F%20Has%20decision%20about%20the%20data%20type.%0D%0A%7D%0D%0A%0D%0Aclass%20SampleClass%3CT%2C%20U%3E%7B%0D%0A%0D%0A%20%20%20%20public%20isTtype(input%3A%20SampleStru%3CT%20%7C%20U%3E)%3A%20input%20is%20SampleStru%3CU%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20(input%20as%20SampleStru%3CU%3E).decision%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20sampleBug()%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20data%3A%20SampleStru%3CT%3E%20%7C%20SampleStru%3CU%3E%3B%0D%0A%20%20%20%20%20%20%20%20if%20(this.isTtype(data))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20data%20is%20SampleStru%3CU%3E%0D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20data%20is%20never.%20Expected%20behaviour%20SampleStru%3CT%3E%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A)

**Related Issues:**

**Comment by jack-williams** [comment]
This is the correct behaviour: all instantiations of `SampleStru` are structurally identical because the type parameter is never used in the body of the type. See [here](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--).

**Comment by dragomirtitian** [comment]
@jack-williams Fully agree with the structurally identical part. My guess is some structure got lost when creating the sample for the issue. 

Even if they are not structurally identical,  type-guards need a union in order to narrow the type on the else (essentially removing the member from the union). `Samnple<T | U>` is not a union. It is a generic type that happens to have a union as the type argument. Typescript will not attempt to do any narrowing in such cases:

```ts
interface SampleStru<T> {
    decision: boolean; // Has decision about the data type.
    value: T
}

class SampleClass {

    public isTtype(input: SampleStru<string | number>): input is SampleStru<number> {
        return typeof input.value === "number";
    }

    public sampleBug(data: SampleStru<string | number>) {

        if (this.isTtype(data)) {
            data.value // number
        } else {
            data.value //  string | number
        }
    }
}
```

You can think of `data` being typed on the este as `Exclude<SampleStru<string | number>, SampleStru<number>>` this will still `SampleStru<string | number>` .

**Comment by JAciv** [comment]
So, am I correct in understanding that, in this case,  `SampleStru<T> | SampleStru<U>` and  `SampleStru<T | U>` are not the same?

**Comment by dragomirtitian** [comment]
@JAciv Exactly, they are not the same. (Assuming you actually use the type parameter, unlike your original code where you do not use it)

This narrows as expected:

```ts

interface SampleStru<T> {
    decision: boolean; // Has decision about the data type.
    value: T
}

class SampleClass<T, U>  {

    public isTtype(input: SampleStru<T> | SampleStru<U>): input is SampleStru<T> {
        return typeof input.value === "number";
    }

    public sampleBug(data: SampleStru<T> | SampleStru<U>) {

        if (this.isTtype(data)) {
            data.value // number
        } else {
            data.value //  string | number
        }
    }
}

```

Depending  on what position a type parameter appears in, the different instantiations may relate co-variant or contra-variant  way, and this has implications for assignability 

```ts

interface SampleStru<T> {
    decision: boolean; // Has decision about the data type.
    value: T
}

// string extends string | number, T is in a covarinat position so co = Y
type co =  SampleStru<string> extends SampleStru<string | number> ? "Y": "N"
//but contra is "N"
type contra =  SampleStru2<string> extends SampleStru2<string | number> ? "Y": "N"
let a!:  SampleStru<string>;
let b!:  SampleStru<string | number>; 
a = b; /// not compatible
b = a; /// compatible


interface SampleStru2<T> {
    decision: boolean; // Has decision about the data type.
    value: (c:T) => void
}

// string extends string | number, T is in a contravariant position so co2 = N
type co2 =  SampleStru2<string> extends SampleStru2<string | number> ? "Y": "N"
// but o3 is "Y"
type contr2 =  SampleStru2<string | number> extends SampleStru2<string> ? "Y": "N"
let a2!:  SampleStru2<string>;
let b2!:  SampleStru2<string | number>;
a2 = b2; /// compatible
b2 = a2; /// not compatible
```
Side Note: An easy way to remember co vs contra variant is if the relationship is if the sub-type relationship is in the same direction for the type parameter and for the instantiation of the generic type. If `Cat` is a subclass of `Animal` then if `G<Cat>` is a subtype of `G<Animal>` the they are covariant. If `G<Animal>` is a subtype of `G<Cat>` the they are contravariant.

**Comment by jack-williams** [comment]
@dragomirtitian 

> It is a generic type that happens to have a union as the type argument. Typescript will not attempt to do any narrowing in such cases:

Strictly speaking this is mostly right, but there are exceptions. A type guard will also _narrow by assertion_. This basically amounts to replacing the source type by a direct subtype, or by adding an intersection of the predicate type. 

In the case of a negated type guard, the source type will be filtered by all types assignable to the predicate type. In the OP, `SampleStru<T | U>` is assignable to `SampleStru<U>`, for reasons discussed, which means `SampleStru<T | U>` filters itself out and produces the `never` in the false branch.
