### ISSUE TITLE
CustomEvent is missing for the list of specialized signatures on document.createEvent

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#2975]
Coppied from @NekR  coment in: https://github.com/Microsoft/TypeScript/issues/2029#issuecomment-97964753

This:
```typescript
var event = document.createEvent('CustomEvent');
event.initCustomEvent('test', true, true, void 0);
this.node.dispatchEvent(event);
```
produces this error:
```error TS2339: Property 'initCustomEvent' does not exist on type 'Event'.```

This:
```typescript
var event:CustomEvent = document.createEvent('CustomEvent');
event.initCustomEvent('test', true, true, void 0);
this.node.dispatchEvent(event);
```
produces this error:
```error TS2322: Type 'Event' is not assignable to type 'CustomEvent'.
  Property 'detail' is missing in type 'Event'.```

And only casting works:
```typescript
var event = <CustomEvent>document.createEvent('CustomEvent');
event.initCustomEvent('test', true, true, void 0);
this.node.dispatchEvent(event);
```

First case worked just fine ~~30 mins~~2 hours ago when I was on TS1.5-Alpha.

**Comment by mhegazy** [comment]
@NekR can you give this file a try: https://github.com/Microsoft/TypeScript/blob/a46a6106a8f01131ef208fa51fe69b3d06574507/bin/lib.d.ts

sorry for the hassle.

**Comment by NekR** [comment]
@mhegazy Yep, it works for me know, thank you!

**Comment by mhegazy** [comment]
Thanks.

**Comment by QuinntyneBrown** [comment]
@mhegazy "composed" is missing from the CustomEvent definition.

**Comment by mhegazy** [comment]
please file a new issue for this.
