### ISSUE TITLE
Generic auto-completion missing primitive types

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#29769]
**TypeScript Version:**  3.2.4

This is kinda hard to reproduce, but I was working on a slower laptop for a while now and repeatedly ran into the following issue:
1. Type the following quicker than autocompletion can keep up (its easier on slow machines):  
`const foo = Record<string`
2. Press `,` to enter the 2nd type argument

**Expected behavior:**
`const foo = Record<string,`

**Actual behavior:**
`const foo = Record<stringify,`

It seems like `string` is being added to the autocompletion list later, so by the time I press `,` it is not there yet and autocompletion resorts to filling `stringify`.

**Comment by ajafff** [comment]
I experience the same on a rather fast machine as well.

**Comment by AlCalzone** [comment]
I second this. It has been happening on my main machine aswell. This did not happen in older TS versions.

**Comment by AlCalzone** [comment]
@RyanCavanaugh what more info do you need? I can try to screencap it it that helps.

**Comment by AlCalzone** [comment]
Any plan when this is going to be worked on? It is really annoying.

**Comment by RyanCavanaugh** [comment]
I guess a video would be helpful? This is also going to be dependent on which editor you're using, which was unspecified

**Comment by AlCalzone** [comment]
@RyanCavanaugh The editor is VSCode - I'll try to record a video to show the issue. Or would some language server log be more helpful?

**Comment by RyanCavanaugh** [comment]
A video and the accompanying log when the bad behavior is occurring would be best

**Comment by AlCalzone** [comment]
@RyanCavanaugh Unfortunately, I can't get the recording to work on this computer - I'll have to try again on another machine. For now here's a screenshot:
![grafik](https://user-images.githubusercontent.com/17641229/58160721-4d3c5080-7c7f-11e9-92e7-df180e62a0a3.png)
and the tsserver log:
[tsserver.log](https://github.com/microsoft/TypeScript/files/3206509/tsserver.log)

I did not do anything further after the screenshot.

**Comment by AlCalzone** [comment]
@RyanCavanaugh I can reproduce the issue the following way:
1. `git clone https://github.com/AlCalzone/node-zwave-js`
2. `git checkout d80778a`
3. `npm ci`
4. open `src/lib/commandclass/ConfigurationCC.ts`
5. go to line 781, start typing before the final closing brace (inside the function body):
    ```ts
    const foo: Record<string
    ```

**Comment by RyanCavanaugh** [comment]
Repro is straightforward - requesting completions as shown below misses the keyword-based type names (`number`, `string`, etc). Failing test that should pass:
```ts
/// <reference path="fourslash.ts" />

//// function f() {
//// 	const k: Record</**/
//// }

goTo.marker();
verify.completions({
    includes: [
        { name: "string" }
    ]
});
```
Inserting an "s" at the marker position makes the test pass; probably the tree is malformed in a way that the LS doesn't currently account for.
