### ISSUE TITLE
Documentation: Declaration Merging rationale or motivation 

### ISSUE THREAD

**Issue by omeid** [microsoft/TypeScript#29767]
The TypeScript documentation only explains how Declaration Merging works, it does not explain why such a novel --and arguably surprising-- behaviour is required, nor does it provide any practical reason or examples of how it is used.

I feel some documentation explaining the rationale and trade-offs* or at least providing practical or production examples of using declaration merging would be very useful.

\* For example, with declaration merging, it is not possible to detect *duplicate* declarations, which kind of doesn’t exist, what do I get in return for this?

**Comment by AlCalzone** [comment]
A good real-world example would be adding typed events to classes extending `EventEmitter`:

```ts
interface Foo {
  on(event: "bar", handler: (a: string, b: number) => void): this;
}

class Foo extends EventEmitter {
  // ...
}

// later:
const foo = new Foo();
foo.on("bar", /* get intellisense here */);
```

**Comment by omeid** [comment]
@AlCalzone As one is already required to extend `EventEmitter` in this case, I am struggling to see how the `on` method overloading couldn't have been done as part of this extension rather than a what seems to be a discrete specification on how the extensions of `EventEmitter` should behave.

**Comment by AlCalzone** [comment]
@omeid I don't follow?! I merely provided an example where declaration merging is useful.
