### ISSUE TITLE
sourcemap changed when current file didn't change , but other file changed

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#29776]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

sourcemap changed when current file didn't change , but other file changed

DictOptimizer.js , DictOptimizer.js.d.td, DictOptimizer.ts didn't change, but DictOptimizer.js soutrcemap changed

file: DictOptimizer.js
https://github.com/bluelovers/node-segment/commits/master/lib/submod/DictOptimizer.js

commit log
https://github.com/bluelovers/node-segment/commit/53bc9423945a10fe6d0ca30cae7b26fd24615807#diff-1e6da6b7e3cadff440075e639670976a

**Expected behavior:**

1. sourcemap didn't change when current source file didn't change
2. or know why it changed

**Actual behavior:**

sourcemap changed

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Bugs in source map emit aren't uncommon; we probably fixed one. "Something changed" isn't an actionable bug report for us.
