### ISSUE TITLE
extend of Array get wrong instance

### ISSUE THREAD

**Issue by kafai97** [Microsoft/TypeScript#29772]
If I do this in TypeScript
```
class Vector extends Array { }
let v = new Vector(1, 2, 3)

v instanceof Vector  // false
```

v is actually an Array
If I do it in javascript, it give me a correct `true` result for the `instanceof` checking

**Comment by dragomirtitian** [comment]
This is not really a typescript issue, it has to do with the runtime you are running the script on. On modern browsers `v instanceof Vector`  will be true, but on older runtimes subclassing `Array` posses difficulties.  

Subclassing `Array` is part of [ES2015 standard](http://www.ecma-international.org/ecma-262/6.0/#sec-array-constructor).  You can read about issues with subclassing `Array` for example [here](http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array)

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work
