### ISSUE TITLE
[website] Website hasn't been updated for Typescript 3.3

### ISSUE THREAD

**Issue by lemoinem** [Microsoft/TypeScript#29784]
**TypeScript Version:**  N/A
**Search Terms:** Website What's New 3.3

**Code**
N/A

**Expected behavior:**
The website should be up-to-date and follow closely the actual release of new versions

**Actual behavior:**
It's been about a week since Typescript 3.3 has been out (https://blogs.msdn.microsoft.com/typescript/2019/01/31/announcing-typescript-3-3/), but the website still hasn't been updated:
The homepage still announces "TypeScript 3.2 is now available. Download our latest version today!"
The documentation "What's New" section doesn't have a Typescript 3.3 section (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html)

**Playground Link:** N/A

**Related Issues:** N/A

**Note:**
I'm sorry if this isn't the correct way to open an issue related to the website. I wasn't able to find better and several issues on this repo seem to be related to the website.

**Comment by DanielRosenwasser** [comment]
Thanks for the nudge!

**Comment by lemoinem** [comment]
Wow, that was fast!
Thanks!
