### ISSUE TITLE
Conditionals not being distributed with complex types objects/tuples

### ISSUE THREAD

**Issue by augustobmoura** [microsoft/TypeScript#29781]
**TypeScript Version:**  3.4.0-dev.20190206

**Search Terms:**
conditional distribuition distributed object tuple error

**Code**

```ts
type unionError = ({ foo: number } | { bar: string }) extends ({ foo: infer T })
    ? T
    : never
```

**Expected behavior:**
`unionError` to be distributed to
``` ts
type distributed = ({ foo: number } extends { foo: infer T} ? T : never) | ({ bar: string } extends { foo: infer T } ? T : never

// then to
type evaluatedCondition = number | never;
// then
type neverUnionIdentity = number;
```

**Actual behavior:**
`unionError` get evaluated to `never`. I don't know if it's intended, but reading the [official docs](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types) it looks like a bug.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=%0Atype%20a%20%3D%20(%7B%20foo%3A%20number%20%7D%20%7C%20%7B%20bar%3A%20string%20%7D)%20extends%20(%7B%20foo%3A%20infer%20T%20%7D)%20%3F%20T%20%3A%20never%0A

**Related Issues:** 
None easily searchable

**Comment by dragomirtitian** [comment]
The docs also mention that distribution only occurs over naked type parameters. So it will not distribute if you have a concrete union like in your example.

 Introduce a type parameter and distribution occurs as expected:


type a = ({ foo: number } | { bar: string }) extends infer U ? U extends ({ foo: infer T }) ? T : never : never;

**Comment by jack-williams** [comment]
This is an exact use case for #23188.

**Comment by augusto-moura** [comment]
> The docs also mention that distribution only occurs over naked type parameters. So it will not distribute if you have a concrete union like in your example.
> 
> Introduce a type parameter and distribution occurs as expected:
> 
> ```ts
> type a = ({ foo: number } | { bar: string }) extends infer U ? U extends ({ foo: infer T }) ? T : never : never;
> ```

Right, changing the source of problem then. I don't think "naked type parameter" is a good description for not concrete/literal/writtenbyhand types

Maybe we should make it more clear
