### ISSUE TITLE
Use generic defaults for "empty" constructors of Array, Map, Set

### ISSUE THREAD

**Issue by aleclarson** [microsoft/TypeScript#29786]
**TypeScript Version:**  3.4.0-dev.20190202

**Search Terms:**
- assignment expression
- RHS infer

**Code**

```ts
class Test {
    foo?: Map<object, string>

    getFoo(obj: object) {
        // "foo" is inferred as "Map<any, any>" instead of "Map<object, string>"
        const foo = this.foo || (this.foo = new Map())
        foo.set(obj, 1) // No error!
    }
}
```

**Expected behavior:** Infer `foo` to be `Map<object, string>`

**Actual behavior:** Infers `foo` to be `Map<any, any>`

**Playground Link:** [Click here][1]

**Related Issues:** Maybe #7782

[1]: http://www.typescriptlang.org/play/#src=class%20Test%20%7B%0A%20%20%20%20foo%3F%3A%20Map%3Cobject%2C%20string%3E%0A%0A%20%20%20%20getFoo(obj%3A%20object)%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20%22foo%22%20is%20inferred%20as%20%22Map%3Cany%2C%20any%3E%22%20instead%20of%20%22Map%3Cobject%2C%20string%3E%22%0A%20%20%20%20%20%20%20%20const%20foo%20%3D%20this.foo%20%7C%7C%20(this.foo%20%3D%20new%20Map())%0A%20%20%20%20%20%20%20%20foo.set(obj%2C%201)%20%2F%2F%20No%20error!%0A%20%20%20%20%7D%0A%7D

**Comment by DanielRosenwasser** [comment]
This is working as intended. JS always returns the RHS, which you can observe by making `this.foo` a getter that returns something unrelated.

The real problem is that `new Map()` creates an instantiation with `any`. I think we could remove that overload and give it default type arguments.

```diff
 interface MapConstructor {
-    new(): Map<any, any>;
-    new<K, V>(entries?: ReadonlyArray<[K, V]> | null): Map<K, V>;
+    new<K = any, V = any>(entries?: ReadonlyArray<[K, V]> | null): Map<K, V>;
     // ...
 }
```

**Comment by aleclarson** [comment]
It's worth noting that array literals are special-cased to work according to my expectations in the OP. 

[See here](http://www.typescriptlang.org/play/#src=class%20Test%20%7B%0A%20%20%20%20foo%3F%3A%20Array%3Cstring%3E%0A%0A%20%20%20%20getFoo(obj%3A%20object)%20%7B%0A%20%20%20%20%20%20%20%20const%20foo%20%3D%20this.foo%20%7C%7C%20(this.foo%20%3D%20%5B%5D)%0A%20%20%20%20%20%20%20%20foo.push(1)%20%2F%2F%20Error%20as%20expected!%0A%20%20%20%20%7D%0A%7D)

**Comment by andrewbranch** [comment]
It’s not possible to make this work without breaking other things, primarily preventing people from writing `Map<string>` and omitting the second type parameter. See #45648 for more detailed notes.
