### ISSUE TITLE
Parameter of a callback without a specified type next to it breaks code.

### ISSUE THREAD

**Issue by anurbol** [Microsoft/TypeScript#29799]
**TypeScript Version:**  3.4.0-dev.20190207, 3.3.0

**Search Terms:**
type parameter, callback

**Code**

```ts
interface Bar<T> {
    <B_RETURN>(
        a: (aParam: B_RETURN) => any,
        b: (bParam: T) => B_RETURN // B_RETURN is supposed to be inferred from here
        ): any
}

declare const bar: Bar<any>

bar((aParam) => 1, () => 'abc') // OK! `aParam` is `string`
bar((aParam) => 1, (bParam) => 'abc') // `aParam` is `{}`. Why?
bar((aParam) => 1, (bParam: any) => 'abc') // `aParam` is `string`. Again, why?
let arg2 = (bParam) => 'abc' ; bar((aParam ) => 1, arg2) // `aParam` is `string`. Again, why?
```

**Expected behavior:**
`aParam` should be `string` in each of the four examples

**Actual behavior:**
`aParam` is for some reason `{}` instead of `string` in the second example

**Playground Link:** [link](http://www.typescriptlang.org/play/index.html#src=interface%20Bar%3CT%3E%20%7B%0D%0A%20%20%20%20%3CB_RETURN%3E(%0D%0A%20%20%20%20%20%20%20%20a%3A%20(aParam%3A%20B_RETURN)%20%3D%3E%20any%2C%0D%0A%20%20%20%20%20%20%20%20b%3A%20(bParam%3A%20T)%20%3D%3E%20B_RETURN%20%2F%2F%20B_RETURN%20is%20supposed%20to%20be%20inferred%20from%20here%0D%0A%20%20%20%20%20%20%20%20)%3A%20any%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20bar%3A%20Bar%3Cany%3E%0D%0A%0D%0Abar((aParam)%20%3D%3E%201%2C%20()%20%3D%3E%20'abc')%20%2F%2F%20OK!%20%60aParam%60%20is%20%60string%60%0D%0Abar((aParam)%20%3D%3E%201%2C%20(bParam)%20%3D%3E%20'abc')%20%2F%2F%20%60aParam%60%20is%20%60%7B%7D%60.%20Why%3F%0D%0Abar((aParam)%20%3D%3E%201%2C%20(bParam%3A%20any)%20%3D%3E%20'abc')%20%2F%2F%20%60aParam%60%20is%20%60string%60.%20Again%2C%20why%3F%0D%0Alet%20arg2%20%3D%20(bParam)%20%3D%3E%20'abc'%20%3B%20bar((aParam%20)%20%3D%3E%201%2C%20arg2)%20%2F%2F%20%60aParam%60%20is%20%60string%60.%20Again%2C%20why%3F)

I would be *very* grateful if someone can give me some quick directions (Is it a bug? What am I missing?). My work depends on it in a great degree.

P.S. [Asked](https://stackoverflow.com/questions/54575969/typescript-parameter-of-a-callback-without-a-specified-type-next-to-it-breaks-c) on stackoverflow and got no answer.

**Comment by RyanCavanaugh** [comment]
This is basically the dual of #29791 - inference on functions proceeds left-to-right, so during the inference of `aParam` in the first function we have not yet examined the body of the second function expression to determine its return type (which we *believe* will be context-sensitive, in other words depends on its parameter type).

**Comment by anurbol** [comment]
@RyanCavanaugh Thank you, made it very clear for me. Except one part: 

> which we _believe_ will be context-sensitive, in other words depends on its parameter type
I am not sure how the return type can depend on parameter type if it's clear that the function returns `string`, because it returns string literal. Moreover, I am confused by the fact that unknown parameter `bParam` and parameter of type any (`bParam: any`) lead to different results. Maybe this is worth fixing? I feel that it's wrong. Just a suggestion, I am satisified with the provided answer already and this issue can be closed.

**Comment by RyanCavanaugh** [comment]
> I am not sure how the return type can depend on parameter type if it's clear that the function returns `string`, because it returns string literal.

We don't have a separate pass to say "Go dive into the function and check to see if all its return statements don't rely on its parameter type" - doing so would be expensive in light of the fact that *extremely* few real-world functions actually behave like that in practice.

> Moreover, I am confused by the fact that unknown parameter (`bParam`) and parameter of type any (`bParam: any`) lead to different results.

An unannotated parameter isn't the same as `any` -- it's one that we're going to try to infer a type for. Functions with type annotations aren't context-sensitive, thus get treated differently in the inference process.

**Comment by anurbol** [comment]
@RyanCavanaugh Wow. That's another valuable insight of how the compiler works, thank you so much! If only there would be a way to know these algorithms of TS compiler without looking at it's source code and bothering you in issues. 

I think I will close this issue as I don't have other questions and a "Design Limitation" badge probably means I should close it.

Thanks again!
