### ISSUE TITLE
inconsistent inference of empty array with --strict flag

### ISSUE THREAD

**Issue by tao-cumplido** [Microsoft/TypeScript#29795]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
const foo = []; // any[]

class Foo {
    bar = []; // never[]
}
```

**Expected behavior:**
`const foo = []` is type `never[]`

**Actual behavior:**
`const foo = []` is type `any[]`

**Playground Link:** 
https://typescript-play.js.org/?noImplicitReturns=false#code/MYewdgzgLgBAZiEMC8MDaBdA3DA9LmAQzAE9MAoc4AG0IghgDFEYBvcmTmAI0ICcU6bHgJgApgDcxfCgF8gA

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is working as intended, but can be a bit surprising.

In general, in `--strict` mode we consider the type of the expression `[]` to be `never[]`. This logically follows from the inferred type of an array literal being a union of the types of the elements, and `never` is the same as an empty union.

Now, in certain situations we can use control flow analysis to determine a better type for a variable that was initialized with `[]`. For more details see #11432. That's what's happening in the `const foo = []` case.

**Comment by tao-cumplido** [comment]
Ok, I see the difference, thanks for the explanation.
