### ISSUE TITLE
TSServer CodeEdits: Return edits in order of execution

### ISSUE THREAD

**Issue by mhartington** [Microsoft/TypeScript#29801]
## Search Terms

tsserver, getCodeEdits, CodeEdits. CodeActions

## Suggestion

Based on observations, when requesting codeEdits from tsserver, it returns an array of codeEdits that appears to be in either an arbitrary order, or based on the `start.line`/`start.offset` value. 

It should instead return the array in an the order the edits should be applied.

## Use Cases

Currently in [nvim-typescript](https://github.com/mhartington/nvim-typescript), we have to sort through the array and apply these changes any time getCodeEdits is requested. It would be great to just have this built in.

## Examples

Take the following code:

```ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'song-item',
  templateUrl: './song-item.component.html',
  styleUrls: ['./song-item.component.scss']
})
export class SongItemComponent {
  constructor() {}
}
``` 

With `"noUnusedLocals"`, and `"noUnusedParameters` set in the compiler options, `ChangeDetectionStrategy` should be removed. 

After making the request, the codeEdits array is ordered as such: 

```js
[{"start":{"line":1,"offset":26},"end":{"line":1,"offset":28},"newText":""},
{"start":{"line":1,"offset":28},"end":{"line":1,"offset":51},"newText":""}]
```

If I apply the edits in this order, I end up with

```ts
import { Component, InputCh from '@angular/core';
```

Which is incorrect. Currently as a work around, I have this sort function applied to the code edits.

```ts
function compare(text1: protocol.CodeEdit, text2: protocol.CodeEdit) {
  if (text1.start.line !== text2.start.line) {
    return text2.start.line - text1.start.line;
  }
  
  if (text1.start.offset !== text2.start.offset) {
    return text2.start.offset - text1.start.offset;
  } 
    return !isInsert(text1) ? -1 : isInsert(text2) ? 0 : 1;

}

const isInsert = (range: protocol.CodeEdit) => range.start.line === range.end.line && range.start.offset === range.end.offset;
```

It would be great if this could be applied on the response before being returned to the editor plugin.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sheetalkamat** [comment]
We explicitly order the changes in their location in file. Currently this works well with vscode since they apply the changes in reverse order and so does it work in vs but I am not sure what happens in vs as much.
I don't think we want to change this order.
The better question would be when these changes are applied in single call with new API added as part of #30107 we would want to apply in the reverse order just like how our currently internal API does (I think vs uses that but @amcasey would have more info on that)

Adding @mjbvz  and @amcasey  for their input.

**Comment by mjbvz** [comment]
Internally I believe that VS Code sorts the edits within a single file by their starting position but then applies them as a single operation rather than sequentially (or we adjust the edit offsets as changes are applied)

**Comment by amcasey** [comment]
For code actions and refactorings, the TS language service in VS hands off to `SourceText.WithChanges` (http://source.roslyn.io/#Microsoft.CodeAnalysis/Text/SourceText.cs,615), which - to my surprise - does not appear to sort the changes.  

In completion, we sort them in ascending order of start position (which seems backwards to me).  I'm guessing that we always get at most 1, so it doesn't matter?

Intuitively, I would have expected descending order of start position to be the appropriate application order and I didn't have the impression that the server guaranteed a particular order (which means that the client would still need sorting logic for all server versions preceding the introduction of a guarantee).

**Comment by sheetalkamat** [comment]
@amcasey it does sort the changes: http://source.roslyn.io/#Microsoft.CodeAnalysis/Text/SourceText.cs,636 
So reversing the order wont pose issue to VS side right?
@mjbvz is the reverse default action or does it check if the changes need to be reversed?

@amcasey do you think it would be better to check in applyChanges..api to see if the changes are in descending order of their position in the source file?

**Comment by amcasey** [comment]
@sheetalkamat Thanks, I missed the sorting code.  I agree that that means VS is unlikely to be affected by a change to the order in the response, but I'm happy to validate.

As for checking the order, maybe we could do what Roslyn does and validate the order before attempting to sort?

**Comment by sheetalkamat** [comment]
This would need to change: Handling of applying changes when it comes in random order as well as part of this.

**Comment by sheetalkamat** [comment]
@amcasey  @mjbvz @RyanCavanaugh @DanielRosenwasser Upon further thought I think we shouldn't change the current behaviour. API user should apply changes in reverse order so use our new API to apply changes in one shot. The main reason that this cannot be done is that when our current apis to apply changes (UpdateOpen and internal api ApplyChangedToOpen) always reverse the order. Adding a check to see if the changes need to be applied in straight order would mean to check if change at first location starts at the end of file and last change location is before that location. But what if the changes are at same location, how can we determine if we got the change in correct order or wrong order? So for simplicity i would  recommend retaining current behavior that the changes are applied in reverse order.
Any thoughts?

**Comment by mjbvz** [comment]
This is good with me for VS Code

**Comment by DanielRosenwasser** [comment]
Wouldn't this just break everyone who isn't currently sorting before applying the edits at all?

**Comment by sheetalkamat** [comment]
@DanielRosenwasser But if we do this change it would be a breaking change and all the clients using tsserver would need to update. As I mentioned we cant just determine if you want to apply changes in reverse or correct order when updating them in bulk (currently we reverse the order) because there could be two changes for same span:

current fileText = `const x = a => 10;`
change `pos: 11,  length: 0, newText: ": number"`
change `pos: 11, length: 0, newText: ")"`

In same order it becomes: `const x = a): number => 10;`
In reverse order the text becomes: `const x = a: number) => 10;`
```

**Comment by DanielRosenwasser** [comment]
Right, I'm saying that if today, the API returns the correct sequential order, then returning the reverse would break everyone. I recently fixed Sublime to apply renames in reverse - but with no prior sorting.

I dunno, seems like we should decide if we already have a correct ordering guarantee. If so, nvim-typescript could just avoid sorting and do a reverse operation as well. Would that work @mhartington?

**Comment by mhartington** [comment]
Yeah that would work in nvim-typescript's case.

**Comment by sheetalkamat** [comment]
Then closing this issue. @RyanCavanaugh @DanielRosenwasser can you please label as per guidance, not sure what to label this. Thanks.
