### ISSUE TITLE
JSON.parse interface should accept null as first argument

### ISSUE THREAD

**Issue by Yiin** [Microsoft/TypeScript#29807]
JSON.parse() accepts null as valid first argument (null is returned in that case), but TypeScript shows an error, because currently it expects string value to be provided as first argument.

**Search Terms:**
JSON parse null typings

**Code**

```ts
JSON.parse(null);
```

**Expected behavior:**
No linting error is shown

**Actual behavior:**
[ts] Argument of type 'null' is not assignable to parameter of type 'string'. [2345]

**Playground Link:**
https://www.typescriptlang.org/play/#src=console.log(JSON.parse(null)%20%3D%3D%3D%20null)%3B%0D%0A

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/11842

**Comment by sahin52** [comment]
If this issue is not resolved as wanted. So, just use "!" after null expression like 
https://www.typescriptlang.org/play/#src=console.log(JSON.parse(null!)%20%3D%3D%3D%20null)%3B%0D%0A
