### ISSUE TITLE
TS2367: This condition will always return 'false'

### ISSUE THREAD

**Issue by lonereck** [Microsoft/TypeScript#29822]
**TypeScript Version:** 3.3.3

**Search Terms:** TS2367

```typescript
class Scanner {
    private _index: number;
    private _input: string;

    public get current() { 
        return this._input[this._index];
    }

    constructor(input: string) {
        this._input = input;
        this._index = 0;
    }

    public Scan() {
        if (this.current == "A") {
            this._index++;
            // error TS2367: This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.
            if (this.current == "B") {
                // do something
            }
        }
    }
}
```

**Expected behavior:**
No compilation errors

**Actual behavior:**
error TS2367: This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.

**Playground Link:** 
[Here](https://www.typescriptlang.org/play/index.html#src=class%20Scanner%20%7B%0D%0A%20%20%20%20private%20_index%3A%20number%3B%0D%0A%20%20%20%20private%20_input%3A%20string%3B%0D%0A%0D%0A%20%20%20%20public%20get%20current()%20%7B%20%0D%0A%20%20%20%20%20%20%20%20return%20this._input%5Bthis._index%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20constructor(input%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this._input%20%3D%20input%3B%0D%0A%20%20%20%20%20%20%20%20this._index%20%3D%200%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Scan()%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.current%20%3D%3D%20%22A%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this._index%2B%2B%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20error%20TS2367%3A%20This%20condition%20will%20always%20return%20'false'%20since%20the%20types%20'%22A%22'%20and%20'%22B%22'%20have%20no%20overlap.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(this.current%20%3D%3D%20%22B%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20do%20something%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by jack-williams** [comment]
Relevant comment and issue [here](https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-235963457).

**Comment by fatcerberus** [comment]
Hmm, this is a bit different than https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-235963457 though since `.current` is a getter and that should be known by the compiler.  It’s surprising that it performs any narrowing on it in the first place.

**Comment by jack-williams** [comment]
I don't know if TypeScript distinguishes properties obtained literally or via getters, but I'm not sure it would help much. Even if that information was made available the choices are between performing some inline effect analysis, assuming all getters are mutable, or assuming all getters are immutable.
The first two seem impractical in the general case.

**Comment by fatcerberus** [comment]
That’s true, I guess it comes down to real-world tradeoffs as discussed in #9998 (is it bad I know this issue number by heart?).  I guess what I find surprising is that `this.getterProp` is assumed to be stable and is therefore narrowed, while `this.getterFunc()` will never be narrowed.  Since they are both function calls in the end, the inconsistency strikes me as jarring.

**Comment by slaneyrw** [comment]
sorry, but this is a mistake.  Getter properties should not be narrowed.  How do you "convert" to a function call if I can't invoke the property as a function
