### ISSUE TITLE
Superfluous `/index` on Auto Imported modules

### ISSUE THREAD

**Issue by chasms** [microsoft/TypeScript#29835]
Utilizing the Auto Import feature, import a module that is scoped to a folder where the exports of that folder-scoped module are declared in an `index.ts/js/tsx/jsx` file

Expected:
```
import { Button } from "../components/Button";
```
Result:
```
import { Button } from "../components/Button/index"
```

[Mentioned in issue #63780](https://github.com/Microsoft/vscode/issues/63780#issuecomment-459779562) but is an issue altogether different than that of the OP in that issue.

Looking at @mjbvz's [changes that implement the Auto Import feature](https://github.com/Microsoft/vscode/commit/a8fdcc4a6d4f71f75c6689cad4439eb106f60665) seems like the text edit string may come straight from the TS langauge server, so may not be in your interest to parse – but I don't have even close to full context, I'll leave that up to you.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clock|Com|0.0.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
gitlens|eam|9.4.1
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
flow-for-vscode|flo|1.0.1
vscode-yarn|gam|1.6.0
vscode-redux-devtools|jin|0.0.11
Angular2|joh|7.0.1
vscode-styled-components|jpo|0.0.25
solidity|Jua|0.0.49
terraform|mau|1.3.7
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
node-debug2|ms-|1.31.3
color-highlight|nau|2.3.0
vscode-docker|Pet|0.5.2
ruby|reb|0.21.0
gitconfig|sid|2.0.0
vscode-react-native|vsm|0.8.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by mjbvz** [comment]
@chasms Can you please share you jsconfig or tsconfig. I see this working properly for a very simple `jsconfig.json` project:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

Please also test using VS Code 1.31

**Comment by chasms** [comment]
@mjbvz Tried your config and it works. Looks like this is purely an issue with the rootDirs flag; after removing only that flag my config works as expected

**Comment by RyanCavanaugh** [comment]
We shouldn't ever add `/index` when `module` is `commonjs`.

**Comment by DanielRosenwasser** [comment]
or when `moduleResolution` is `node`

**Comment by omarzion** [comment]
This is related... I think?  type `<List` hit tab for auto import and get 
```import { List } from 'node_modules/semantic-ui-react/index';```

only been happing the last couple days

in js files
typescript version: 3.4.3
vscode version 1.33.1
