### ISSUE TITLE
Type inference for maps inside generic functions

### ISSUE THREAD

**Issue by domoritz** [Microsoft/TypeScript#29831]
I'd like type inference inside generic functions to infer precise types for elements of maps.

In the screenshot below, you can see that TS does not infer that `val` is a `number`. I'm proposing to improve the type inference so that the types will be inferred correctly. 

<img width="499" alt="screen shot 2019-02-07 at 12 13 29" src="https://user-images.githubusercontent.com/589034/52439988-cef1df00-2ad1-11e9-98a1-fa7256e23eba.png">

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** maps generic inference 

**Code**

```ts
type Names = 'foo' | 'bar';

function func<T extends string>(arg: T) {
  const a: { [key in T]?: number } = {};
  const val = a[arg];

  // I'm expecting `val`` to be of type number here
  type ShouldBeNumber = typeof val;

  return val;
}

// `val`` is number here
const val = func<Names>('foo');
type IsNumber = typeof val;
```

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20Names%20%3D%20'foo'%20%7C%20'bar'%3B%0D%0A%0D%0Afunction%20func%3CT%20extends%20string%3E(arg%3A%20T)%20%7B%0D%0A%20%20const%20a%3A%20%7B%20%5Bkey%20in%20T%5D%3F%3A%20number%20%7D%20%3D%20%7B%7D%3B%0D%0A%20%20const%20val%20%3D%20a%5Barg%5D%3B%0D%0A%0D%0A%20%20%2F%2F%20I'm%20expecting%20%60val%60%60%20to%20be%20of%20type%20number%20here%0D%0A%20%20type%20ShouldBeNumber%20%3D%20typeof%20val%3B%0D%0A%0D%0A%20%20return%20val%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20%60val%60%60%20is%20number%20here%0D%0Aconst%20val%20%3D%20func%3CNames%3E('foo')%3B%0D%0Atype%20IsNumber%20%3D%20typeof%20val%3B%0D%0A

**Related Issues:**  no, but I'm probably not using the right keywords

**Comment by azizhk** [comment]
Hi @domoritz, it is actually `number`.
`{ [key in T]?: number; }[T]` resolves to `number`.
The playground is showing you how it is actually resolving it. Typescript keeps this information till it is not needed (i.e. within the function scope.) Any type checking that happens will be with `number` only.

Or if you want you can use a `Map` directly.
```ts
type Names = 'foo' | 'bar';

function func<T extends string>(arg: T) {
  const a = new Map<T, number>();
  const val = a.get(arg);

  // ShouldBeNumber is number here.
  type ShouldBeNumber = typeof val;

  return val;
}
```

(All of this is assuming that you have `strictNullChecks` turned off. When you turn it on, `number` will become `number | undefined`)

**Comment by domoritz** [comment]
Ahh, I see. Thanks!
