### ISSUE TITLE
Improve enum code generation

### ISSUE THREAD

**Issue by polkovnikov-ph** [Microsoft/TypeScript#29838]
## Search Terms

enum generation

## Suggestion

Strings are unnecessarily duplicated. Should change

```javascript
var Direction;
(function (Direction) {
    Direction[Direction["Left"] = 0] = "Left";
    Direction[Direction["Right"] = 1] = "Right";
    Direction[Direction["Down"] = 2] = "Down";
    Direction[Direction["Up"] = 3] = "Up";
})(Direction || (Direction = {}));
console.log(Direction);
```

to

```javascript
var Direction;
(function (Direction) {
    Direction[Direction[0] = "Left"] = 0;
    Direction[Direction[1] = "Right"] = 1;
    Direction[Direction[2] = "Down"] = 2;
    Direction[Direction[3] = "Up"] = 3;
})(Direction || (Direction = {}));
console.log(Direction);
```

## Use Cases

Arrrgh, why it is even made vice versa

## Examples

https://www.typescriptlang.org/docs/handbook/enums.html

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
Is this #2655 and/or #19848?

**Comment by fatcerberus** [comment]
It’s the same issue as #19848 but that one has been closed and locked.

**Comment by polkovnikov-ph** [comment]
```
let p = 0;
const f = () => p++;
enum A { 
    b = f(),
    c = f(),
}
console.log(A.b, A.c);
```

compiles to

```
var p = 0;
var f = function () { return p++; };
var A;
(function (A) {
    A[A["b"] = f()] = "b";
    A[A["c"] = f()] = "c";
})(A || (A = {}));
console.log(A.b, A.c);
```

Prints `0 1`, but otherwise

```
var p = 0;
var f = function () { return p++; };
var A;
(function (A) {
    A[A[f()] = "b"] = f();
    A[A[f()] = "c"] = f();
})(A || (A = {}));
console.log(A.b, A.c);
```

prints `1 3`.

**Comment by fatcerberus** [comment]
Yep, was just going to link to https://github.com/Microsoft/TypeScript/issues/19848#issuecomment-344994172 to explain the rationale but it seems you beat me to it. :smile:
