### ISSUE TITLE
HTMLCanvasElement.getContext('2d') incorrectly returns union type in 1.5 beta

### ISSUE THREAD

**Issue by IanYates** [Microsoft/TypeScript#2984]
I've got a bunch of TypeScript code that calls `getContext('2d')` on HTML canvas elements.

Since the update to 1.5 beta this morning I now get a union type of `CanvasRenderingContext2D` and `WebGLRenderingContext`.  That makes sense for the general call to getContext(...) since either could be returned.

However if I'm specifically calling `getContext('2d')`, I know I'm getting back a `CanvasRenderingcontext2D`.
I worked around it by creating this little interface in a file
```
interface HTMLCanvasElement {
    getContext(contextId: '2d'): CanvasRenderingContext2D;
}
```
(using syntax from `section 3.8.2.4 - Specialized Signatures` in the TypeScript language reference)

Could we get this added to lib.d.ts perhaps?

**Comment by IanYates** [comment]
I should add that this was a breaking change (I wouldn't have noticed it otherwise).  It's not a "big deal" breaking change, as arguably it's an improvement since it's closer to the real-world, but I figured I should add that it caused existing TS 1.4 code to fail to compile in TS 1.5.

**Comment by hraban** [comment]
+1

**Comment by mhegazy** [comment]
yup. that is a bug alright. the correct definition should be:

```ts
   getContext(contextId: "2d"): CanvasRenderingContext2D;
   getContext(contextId: "experimental-webgl"): WebGLRenderingContext;
   getContext(contextId: string, ...args: any[]): CanvasRenderingContext2D | WebGLRenderingContext;
```

Thanks for reporting this issue, we should have a correct version out for you today to try. sorry for the hassle.

**Comment by mhegazy** [comment]
@IanYates  and @hraban, can you give this file a try and see if you are still running into issues: https://github.com/Microsoft/TypeScript/blob/892bc6d7cb9db654395cf3489b9b61aa099fb433/bin/lib.d.ts

**Comment by hraban** [comment]
I was reporting on this for @reaxis (still on 1.4 myself). I'll ask him.

**Comment by Sharpiro** [comment]
i replaced the old lib.d.ts with the one you posted.  Looks like it now successfully builds.  However, Visual Studio is still displaying it as an error, which will be too annoying to deal with.

**Comment by DanielRosenwasser** [comment]
@Sharpiro you can replace your lib.d.ts in `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript`, though I'd keep a backup available.

**Comment by Sharpiro** [comment]
@DanielRosenwasser Thank you for the tip that removed the error notification.  Looking forward to trying out 1.5.

**Comment by DanielRosenwasser** [comment]
Glad to hear it, let us know of any other snags you run into!

**Comment by NekR** [comment]
Just ran into this problem too, thank you for such a fast fixing!

**Comment by IanYates** [comment]
I was just going to give a team member of mine a reference to this post as he's updated to TypeScript 1.5 beta today.  I couldn't find it since I was checking the open issues list.  Thanks for fixing so fast!  I'll write back if I have any problems :100:

**Comment by IanYates** [comment]
Should it also replace the lib.d.ts file at `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5`?

**Comment by mhegazy** [comment]
@IanYates. yes this is what is used when you build from the command line / F5.
