### ISSUE TITLE
Download link outdated in typescriptlang.org

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#29844]
In https://www.typescriptlang.org/#download-links the download stills point to TS 3.2 (https://www.microsoft.com/en-us/download/details.aspx?id=55258) insted of TS 3.3 in marketplace (https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-331-vs2017).

By the way, why the change to marketplace?

**Comment by DanielRosenwasser** [comment]
Hmm, we'll also have to remove the VS2015 link at some point soon..

I believe the rationale was that using the marketplace means we only have to upload once in one place (less release process), and if we had to pick one then the marketplace was better for reasons around updating within VS itself. I might have the details fuzzy and @minestarks and @weswigham would know better.

**Comment by weswigham** [comment]
Yeah, that'd be it. The marketplace APIs are what populate the extension browser in the IDE (so are more broadly useful) while download center is just a generic ms-wide download page.
