### ISSUE TITLE
Error on generic type inference (which is extended)

### ISSUE THREAD

**Issue by samchon** [Microsoft/TypeScript#29849]
```typescript
interface IPointer<T>
{
    value: T;
}
namespace IPointer
{
    export type ValueType<Pointer extends IPointer<any>> =
        Pointer extends IPointer<infer T> 
            ? T : any;
}

function test_generic_type_inference<Iterator extends IPointer<number>>(): void
{
    // DETECT TYPE BY ACCESSING PROPERTY
    let it: Iterator;
    let value = it.value; // BE "number"

    // INFERENCE TYPE
    type ValueT = IPointer.ValueType<Iterator>; // FAILED TO INFER, WHY NOT "number" ?
    type NumberT = IPointer.ValueType<IPointer<number>>; // BE "number"
}
```

  - **TypeScript Version**: 3.4.0-dev.20190209
  - **Expected behavior**: type `IteratorValueT` be `number`
  - **Actual behavior**: Failed to infer the exact type

In the `test_generic_type_inference` function, a generic parameter named `Iterator` is extending the `IPointer<number>` type. Thus, value type of the `Iterator` must be `number` and it seems okay on the *ACCESSING PROPERTY* part. Local variable has been successfully detected as a `number` type; `it.value: Iterator.value`.

In the *INFERENCE TYPE* part, `ValueT := IPointer.ValueType<Iterator>` is targeting the same thing like the `let value: number = it.value;`. Thus, the `ValueT` must be `number` type, but the result is not. `ValueT` fails to infer its exact type; `number`.

In contrary, `NumberT := IPointer.ValueType<IPointer<number>>` infers the exact type `number`.  `Iterator` type is extension of `IPointer<number>`, thus `ValueT` should be `number` type, or something extended from the `number` type, at least.

**Comment by RyanCavanaugh** [comment]
> Thus, value type of the `Iterator` must be `number`

It'd be unsound to short-circuit your type parameter to its constraint, because you could write code like this:
```ts
function test_generic_type_inference<Iterator extends IPointer<number>>(): Iterator
{
    type ValueT = IPointer.ValueType<Iterator>;
    const val: ValueT = 10;
    return {
        value: val;
    };
}


// x is 10, but should be 5.
const x = test_generic_type_inference<IPointer<5>>().value;
```
