### ISSUE TITLE
Breaking change in 3.x with types on callback functions defined in d.ts file

### ISSUE THREAD

**Issue by jcubic** [microsoft/TypeScript#29845]
**TypeScript Version:**  3.3 / 3.4.0-dev.20190209

**Search Terms:**
* function breaking change
* callback d.ts file
* types callback

**Code**

short version of my real code, the affected are `interpterFunction` where types are not enforced in user code. 

```ts
// d.ts file
declare namespace JQueryTerminal {
    type interpterFunction = (this: JQueryTerminal, command: string, term: JQueryTerminal) => any;
    type terminalObjectFunction = (this: JQueryTerminal, ...args: (string | number | RegExp)[]) => (void | PromiseLike<echoValue>);
    type Interpterer = string | interpterFunction | ObjectInterpreter;
    type ObjectInterpreter = {
        [key: string]: ObjectInterpreter | terminalObjectFunction;
    }
    ...
    type echoValue = string | string[] | (() => string | string[]);
    ...
}
interface JQuery<TElement = HTMLElement> {
    terminal(interpreter?: TypeOrArray<JQueryTerminal.Interpterer>, options?: TerminalOptions): JQueryTerminal;
    ...
}
interface JQueryStatic {
    ...
    terminal: JQueryTerminalStatic;
}
interface JQueryTerminal<TElement = HTMLElement> extends JQuery<TElement> {
   ....
}
// ts file
/// <reference path="./js/jquery.terminal.d.ts" />
$('.term').terminal(["foo.php", obj_interpreter, function(command) {
    this.echo(command);
}]);
```

**Expected behavior:**

This was working in 3.0 I'm expecting command to be string and this JQueryTerminal without specifying the types. It works if I add types in ts file but it was working without it in 3.0.

**Actual behavior:**

No types for `command` and `this` inside callback function and they are set as implicit any.

**Playground Link:** 

**Related Issues:** 

I've [asked in StackOverflow](https://stackoverflow.com/q/54610380/387194) but with no response.
And here is [travis log](https://travis-ci.org/jcubic/jquery.terminal/builds/491034927) that shows errors after upgrade from 3.0 to 3.3

**Comment by jcubic** [comment]
It was version 3.2 that break my code, but this page https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-32 shows nothing that could cause this. I've downgraded to 3.1 but this should be put in breaking changes list.

**Comment by RyanCavanaugh** [comment]
Sorry for the break! Please post a **self-contained** example so we can investigate further and document it properly.

**Comment by jcubic** [comment]
Sorry for the delay, I finally tried to reproduce the issue in repo with both versions and it works, I've also tested on my repo jQuery Terminal where I got the issue and after updating `@types/jquery` it seems it works so the problem was with jQuery Types. It was affecting version `3.3.29` but it works with `3.3.31`.
