### ISSUE TITLE
[Compiler API] transform import when module is set to commonjs

### ISSUE THREAD

**Issue by longlho** [Microsoft/TypeScript#29848]
Hi there,

I'm writing a TS transformer that inline some `import` depending on certain file type. For example:

```
import {foo, bar} from 'static-file'
const baz = foo + bar
// Transform into
const foo = 1, bar = 2
const baz = foo + bar
```

When I set `tsconfig`'s module to `ESNext`, the example above works. However, when the `module` config is `CommonJS`, import `namedBindings` seem to get aliased.

```
import {foo, bar} from 'static-file'
const baz = foo + bar
// Transform into
const foo = 1, bar = 2
const baz = static_file_1.foo + static_file_1.bar
```

I'd love to learn more about the context of why it behaves that way and potentially how to solve my issue.

Thank you so much!

LH

**Comment by RyanCavanaugh** [comment]
ES6 module bindings are "live" - they always observe the value of the property as it exists in the imported module, not just grab the value once at file startup time and then not change again.

**Comment by longlho** [comment]
gotcha thanks!
