### ISSUE TITLE
`undefined` type should not be a subtype of `object` type even when not enabling strictNullChecks

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#29846]
**TypeScript Version:**  3.3.0

**Search Terms:**

**Code**

```ts
type a = undefined extends object ? 1 : 0;
type b = void extends object ? 1 : 0;
type c = null extends object ? 1 : 0;
```

**Expected behavior:**

```
a = 0
b = 1 | 0
c = 1
```

**Actual behavior:**

```
a = 1
b = 0
c = 1
```

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=type%20a%20%3D%20undefined%20extends%20object%20%3F%201%20%3A%200%3B%0D%0Atype%20b%20%3D%20void%20extends%20object%20%3F%201%20%3A%200%3B%0D%0Atype%20c%20%3D%20null%20extends%20object%20%3F%201%20%3A%200%3B

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
First, `void` is sort of like an opaque `unknown` whose value can/should never be narrowed/introspected on, so I think that's orthogonal.

But even the original spec says this is the behavior:

https://github.com/Microsoft/TypeScript/blob/bbf559b9c7fd21b984d7cb538140c74e3d6a6b45/doc/spec.md#326-the-null-type
https://github.com/Microsoft/TypeScript/blob/bbf559b9c7fd21b984d7cb538140c74e3d6a6b45/doc/spec.md#327-the-undefined-type

> ### <a name="3.2.6"/>3.2.6 The Null Type
> 
> The Null type corresponds to the similarly named JavaScript primitive type and is the type of the `null` literal.
> 
> The `null` literal references the one and only value of the Null type. It is not possible to directly reference the Null type itself.
> 
> ***The Null type is a subtype of all types***, except the Undefined type. This means that `null` is considered a valid value for all primitive types, object types, union types, intersection types, and type parameters, including even the Number and Boolean primitive types.
> 
> Some examples:
> 
> ```TypeScript
> var n: number = null;   // Primitives can be null  
> var x = null;           // Same as x: any = null  
> var e: Null;            // Error, can't reference Null type
> ```
> 
> ### <a name="3.2.7"/>3.2.7 The Undefined Type
> 
> The Undefined type corresponds to the similarly named JavaScript primitive type and is the type of the `undefined` literal.
> 
> The `undefined` literal denotes the value given to all uninitialized variables and is the one and only value of the Undefined type. It is not possible to directly reference the Undefined type itself.
> 
> ***The undefined type is a subtype of all types***. This means that `undefined` is considered a valid value for all primitive types, object types, union types, intersection types, and type parameters.
> 
> Some examples:
> 
> ```TypeScript
> var n: number;          // Same as n: number = undefined  
> var x = undefined;      // Same as x: any = undefined  
> var e: Undefined;       // Error, can't reference Undefined type
> ```
>

**Comment by falsandtru** [comment]
Indeed. BTW, you are called at #29697. Can you also take a look?
