### ISSUE TITLE
[3.2.2] `keyof` expanded to fixed properties in the ambient declaration of a mixin

### ISSUE THREAD

**Issue by canonic-epicure** [microsoft/TypeScript#29859]
Lets say we have some property in the class (`FIELDS` below), that "mirrors" all other properties using the `keyof this`, but with different fixed type. This enables nice type-safety when accessing properties of the `FIELDS`. The type of the `FIELDS` property in the generated declaration file is correct - it is same.

```ts
export class Field {}

export class Example {
    someProperty        : number
    anotherProperty     : string

    // collection of "fields"
    FIELDS              : { [s in keyof this] : Field }
}

const ex1       = new Example()

ex1.FIELDS.anotherProperty // valid
ex1.FIELDS.nonsense // invalid


// export declare class Example {
//     someProperty: number;
//     anotherProperty: string;
//     FIELDS: {
//         [s in keyof this]: Field;  ALL IS FINE HERE
//     };
// }
```
However, when same approach is used in the mixin class, the type of `FIELDS` in the generated declaration file is different - its been expanded from the `keyof this` to a fixed set of properties. Naturally this does not work for subclasses. 

```ts
// supporting definitions for mixin pattern
export type AnyFunction<A = any>      = (...input: any[]) => A
export type AnyConstructor<A = any>   = new (...input: any[]) => A
export type Mixin<T extends AnyFunction> = InstanceType<ReturnType<T>>

// mixin function
export const SampleMixin = <T extends AnyConstructor<object>>(base : T) =>

class SampleMixin extends base {
    someProperty        : number

    anotherProperty     : string

    FIELDS              : { [s in keyof this] : Field }
}
// mixin type
export type SampleMixin = Mixin<typeof SampleMixin>


const cls       = SampleMixin(Object)

const ex2       = new cls

ex2.FIELDS.anotherProperty // valid
ex2.FIELDS.nonsense // invalid

// export declare const SampleMixin: <T extends AnyConstructor<any>>(base: T) => {
//     new (...input: any[]): {
//         [x: string]: any;
//         someProperty: number;
//         anotherProperty: string;
//         FIELDS: {        
//             [x: string]: Field;
//             someProperty: Field;      <-- `keyof this` TYPE EXPANDED
//             anotherProperty: Field;
//             FIELDS: Field;
//         };
//     };
// } & T;
// export declare type SampleMixin = Mixin<typeof SampleMixin>;
```

As a result of this, if you use mixins and such approach, it is not possible to use composite projects (`--build`), because the types are all incorrect. 

And the irony is, that if you use mixins extensively (as we do in our project, because its a very clean and type-safe way to compose features), the compilation time significantly increases at some point, so we would really want to use the composite projects..

**Comment by RyanCavanaugh** [comment]
This seems more like an observation than a bug report or a suggestion. What's being proposed?

**Comment by SamuraiJack** [comment]
@RyanCavanaugh The expected and proposed behavior is of course to not expand the `keyof` in the mixin declarations - in the same way as it happens in regular classes.

**Comment by dragomirtitian** [comment]
Related issue: https://github.com/Microsoft/TypeScript/issues/27171

**Comment by RyanCavanaugh** [comment]
The only invariant of declaration emit is it emits an equivalent type as existed in the input program, not necessarily an equivalent representation.
