### ISSUE TITLE
tsc --build ignores `noEmitOnError=false`

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/TypeScript#29851]
**TypeScript Version:**  3.3.1

**Search Terms:**
--build 
noEmitOnError 
generates
emit
error

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

tsc --build 
```

**Expected behavior:**
The output JS file should be emitted with the syntax error included.
Note:  When calling  `tsc` it works as expected.

**Actual behavior:**
No files are emitted 

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
This is working as intended. Refer to https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Project%20References.md#caveats

**Comment by GordonSmith** [comment]
@sheetalkamat apologies, I should have read that document more thoroughly!

However I am still seeing this issue when there are only "warnings" which is not covered by the caveat - should I open a new issue?

**Comment by octref** [comment]
But no emit on unused local is straight counter-productive. While writing programs unused locals will exist all times. Am I obliged to comment them out to just get TS to emit?
