### ISSUE TITLE
about ParamType

### ISSUE THREAD

**Issue by CN-YUANYU** [Microsoft/TypeScript#29857]
I want a tool type ParamType, similar to a ReturnType, that takes a list of the parameter types of the target function

**Comment by citycide** [comment]
Do you mean [`Parameters<T>`](https://github.com/Microsoft/TypeScript/blob/17d16d1bbb943e4c5ead1dfb50d0da53cc499693/src/lib/es5.d.ts#L1451-L1454)?

**Comment by CN-YUANYU** [comment]
@citycide  very thanks  ,  Do you know how to loop  Parameters<T>  Return value

**Comment by CN-YUANYU** [comment]
@citycide 

like this


```typescript

type s = Parameters<typeof fn>

    type p = {
      [s for in p]:s
    }


```
