### ISSUE TITLE
[loc][Query][TypeScript] Localizability of 0; "ImportModuleCompletionsLabel"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/TypeScript#29853]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Module Completions

File Name:
LanguageService\TypeScriptLanguageService\Windows\bin\Release\localize\ENU\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll

Resource ID:
0; "ImportModuleCompletionsLabel"

Query:
We understood "completion" as in "completion list" here, please confirm or advise.

**Comment by DanielRosenwasser** [comment]
@minestarks @uniqueiniquity @jessetrinity

**Comment by jessetrinity** [comment]
@PDostalek Yes, "completion" as in "completion list." In this case, completions for automatically imported modules. "Module Completions" Is the header for the settings section where that setting is enabled / disabled.

**Comment by PDostalek** [comment]
Thanks for now
