### ISSUE TITLE
configuration of ts 1.5 beta with vs 2015 rc

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#2985]
Hi, I installed 2015 rc and ts 1.5 beta. 
I created a sample ts file, and I see that source map is disabled: I would like to configure the map source to create a single file and deploy in the wwwroot so I can debug the code.
I added a tsconfig file in the root of the project with the following settings

>   "compilerOptions": {
>        "module": "amd",
>        "noImplicitAny": false,
>        "noEmitOnError": true,
>        "removeComments": false,
>        "sourceMap": true,
>        "target": "es5",
>        "out": "~/wwwroot/application.js",
>        "watch": true
>    }

but seems that the settings are ignored. How can I configure vs and ts to work as described above?

**Comment by lucamorelli** [comment]
removing the ~/ from out and running it using visual studio Code compiles and deploys correctly, but not from vs

**Comment by mhegazy** [comment]
VS 2015 does not support tsconfig at the point. The support should be available in the next public release.

Meanwhile in VS to set configuration properties:
- create a new project using File> New Project
- use tempalte TypeScript > HTML Application with TypeScript
- got to project property pages > TypeScript Build
![capture](https://cloud.githubusercontent.com/assets/8000722/7433637/487fc02c-efe8-11e4-8add-0f0715883f98.PNG)

**Comment by designxtek** [comment]
will vs2013 support tsconfig?

**Comment by mhegazy** [comment]
@designxtek this is not planed at the moment.
