### ISSUE TITLE
Suggestion: Multiple js files from one tsconfig.json

### ISSUE THREAD

**Issue by AbubakerB** [Microsoft/TypeScript#2986]
Hi guys, i'd like to talk about creating multiple js files from one tsconfig.json:

Would it be possible to have the "out" accept object(in addition to string ofc) so that the following tsconfig.json:
```json 
"compilerOptions": {
    "out": { 
		"services": "../../built/local/services.js",
		"utils": "../../built/randomName.js",
	}
},
"files": {
    "services" : [
        "a.ts",
        "b.ts",
        "c.ts"
    ],
	"utils" : [
        "d.ts",
        "e.ts",
        "a.ts"
    ]
}
```
generates ```../../built/local/services.js``` and ```../../built/randomName.js```

How feasible would this be? And could this feature be useful?
I, personally, would like it because building frameworks and such with TS is lovely but sometimes you'd want to divide the outputted files.

**Comment by mhegazy** [comment]
Currently you can  achieve that by having multiple .ts configs, and calling the compiler once for each output file.

The other alternative is to call the compiler with no `--out` and have a post build task to concatenate different files.

I understand that it would be convenient for the compiler to do the mapping for you, I am not sure if the value we would match the cost and complexity of implementing this system.

**Comment by AbubakerB** [comment]
I see, i just didn't think that it would be that complex - and i find it very useful.
I wouldn't want to manage many different different tsconfig.json files. I'd want to have one main tsconfig.json file where everything about my project is managed from there.

I currently have a VS extension that I've built that does this for me (since 1.1), but using non-VS editors, of course, it won't work.

I guess you guys know the weight of this more than me, but i just thought i'd ask/suggest :) - least i could do. 
Thanks

**Comment by danquirk** [comment]
This looks a little like it's getting into Grunt task territory.

**Comment by Pogix3m** [comment]
9
