### ISSUE TITLE
Issue an error when numeric literals can incur precision loss

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#29863]
In JavaScript, you can write out a really really big (non-`bigint`) integer literal and get a completely different value.

```
0x6A09E667F3BCC908n == 0x6A09E667F3BCC908n // true

0x6A09E667F3BCC908n == 0x6A09E667F3BCC908  // false!?
```

It's worth asking whether or not a really really big integer values which have different observed and specified values are erroneous, and whether we can give users an error.

This would be a breaking change, but it's not clear who benefits from the current behavior.

See https://github.com/tc39/proposal-bigint/issues/170 for where this came up (CC @littledan)

**Comment by littledan** [comment]
This is a great idea! However, this behavior been part of JS forever, so it might be good to start with a warning and see how it goes.

**Comment by DanielRosenwasser** [comment]
We don't have warnings 😄🔥🌎🔥😄

**Comment by Kingwl** [comment]
Witch behavior will be accepted? 

1. numerical compare to bigint literal
2. numerical literal compare to bitint literal
3. numerical literal compare to bigint
4. numerical literal compare to bigint literal

**Comment by DanielRosenwasser** [comment]
It's actually not about the comparisons themselves - it's about writing out an integer numeric literal whose value is too large to be represented accurately. In this specific case, I think we'd expect to error on a number like `0x6A09E667F3BCC908` with

```
This numeric literal's value is too large to be represented accurately.
```

I don't necessarily think we'd want the error for any numeric literal with a fractional component (e.g. no error on `9000000000000000000000000000.000000009`).

**Comment by JoshuaKGoldberg** [comment]
> `This numeric literal's value is too large to be represented accurately as an integer.`

This is nice, but most don't know that 2<sup>53</sup> is the maximum for these. Perhaps a friendly error message would be something like:

> `Numeric literal values greater than 2^53 are too large to be represented accurately as integers.`

**Comment by JoshuaKGoldberg** [comment]
> This is a great idea! However, this behavior been part of JS forever, so it might be good to start with a warning and see how it goes.

How about a quick fix to add an `n` to the end of the numeric literal, if possible?

**Comment by DanielRosenwasser** [comment]
Feel free to add a quick fix to insert the bigint suffix.

**Comment by DanielRosenwasser** [comment]
Feels like this is better off as some sort of lint rule. :sad:

Thanks for the PR though @JoshuaKGoldberg.

**Comment by fatcerberus** [comment]
IMO if I write out a numeric *literal* in the source text and assign it to a variable, without manipulating it in any way, and then observe a different value at runtime, I would wonder why the compiler didn’t yell at me (after spending probably several minutes debugging it :P)

Only literals which can be exactly represented should be accepted.

(Note that a codefix to change large numbers to bigint isn’t necessarily safe - mixing them with regular numbers in operations will produce runtime errors.)

**Comment by fatcerberus** [comment]
Then again, `1.1` can’t be exactly represented in IEEE double either so it then becomes a question of *how much* precision loss you want to accept.  Hmm.
