### ISSUE TITLE
No typings support for absolute ES6 module imports

### ISSUE THREAD

**Issue by fskpf** [microsoft/TypeScript#29869]
- VSCode Version: 1.30.2
- OS Version: Win 10 Home

I'm trying to get my typings file picked up by IntelliSense but cannot get it to work as long as I import the ES6 modules with an absolute path.
It seems like that as long as the path to the imported JS file resolves to an actual file, it prefers the documentation (if any) of the actual JS files instead of my typings (.d.ts) file.

Therefore, in this configuration
![no-patter-matching](https://user-images.githubusercontent.com/17721806/52555813-11296200-2deb-11e9-9936-7e45dc612734.png)
'MyClass' is 'any' and the properties on it won't have IntelliSense support

Since I'm defining my *.d.ts file with a wildcard, I'd assume that the .d.ts file is preferred, actually providing the proper typings.

On the other hand, if the import does not resolve to an actual file, the pattern matching of the .d.ts file is picked up (see the tooltip on the import path) and IntelliSense works as expected:
![pattern-matching](https://user-images.githubusercontent.com/17721806/52555949-72513580-2deb-11e9-8ae5-9710d10ba92c.png)
(Note: There is no core.js file in the project, therefore the import does not resolve to an actual file)

I'm not entirely sure if this is actually a bug. If not, how can I get the typings file to work when importing from an absolute path? For reference, please find attached the project of the screenshots:
[code-completion-test-vscode.zip](https://github.com/Microsoft/vscode/files/2850501/code-completion-test-vscode.zip)

**Comment by mjbvz** [comment]
Thanks for the example project!

IN your project example, I can confirm that that `MyClass` always goes to the definition of `MyClass` in `lib.js`. The definition of `MyClass` in the d.ts is not being merged in. 

Someone on the TS team should be able to provide more information about this. I'm not sure if this is the expected behavior or not, or if you just need to tweak the d.ts files to make this work

**Comment by RyanCavanaugh** [comment]
Actual files are always preferred over wildcard matches. Otherwise people who wrote
```ts
declare module "*" {
  const a: any;
  export = a;
}
```
to silence untyped module warnings would never get any intellisense.

**Comment by fskpf** [comment]
I see, thank you for clarifying it.
As far as I understand it now, there is no way to get the typings file picked up when the imports resolve to an actual JavaScript file, or is there some way to get it working in this scenario?

However, the explanation lets me think that the current behavior punishes libraries that provide proper typings through a *.d.ts file. So IMO, if there is a matching *.d.ts file, it should always be considered.
