### ISSUE TITLE
Support async iterable DOM types

### ISSUE THREAD

**Issue by MattiasBuelens** [microsoft/TypeScript#29867]
## Search Terms

asynciterator asynciterable async iterable iterator

## Suggestion

Add a `dom.asynciterable` option to `--lib` to support DOM types that define a `Symbol.asyncIterator` method.

## Use Cases

The [streams spec](https://streams.spec.whatwg.org/) has [recently been updated](https://github.com/whatwg/streams/commit/bf2cac8a52664df3e6da7a48755890e87b00953a) to add a `Symbol.asyncIterator` method to `ReadableStream`, making it the first DOM type to implement the [ES2018 `AsyncIterable` interface](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-asynciterable-interface).

I would like to update the type definitions for streams in [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator/) to include this new async iterator method. However, this requires `Symbol.asyncIterator`, which is not available before ES2018 and thus cannot be readily used in the DOM type definitions.

Previously, a `dom.iterable` option was added to support DOM types that define a `Symbol.iterator` method. I think it would make sense to use this same strategy to support `Symbol.asyncIterator`.

## Examples
TypeScript would have (generated) type definitions in `lib/lib.dom.asynciterable.d.ts`:
```typescript
interface ReadableStream<R = any> {
  [Symbol.asyncIterator](): AsyncIterator<R>;
}
```

Users could then use a `ReadableStream` in a `for await..of` loop by compiling with `--target es2018`:
```typescript
const readable = new ReadableStream<Uint8Array>();
for await (const chunk of readable) {
  console.log(chunk);
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by espindola** [comment]
Hi, I just stumbled upon this. I noticed forEach was removed from ReadableStream in src/lib/dom.generated.d.ts in 4e237ed66fd1293602aaf5836087ba5d3108c5ea, but async iteration was not added. The ReadableStream in lib/lib.dom.d.ts still has a forEach and no async iteration.

Is there anything I can do to help?

**Comment by MattiasBuelens** [comment]
The `forEach` method was mistakenly added to the `ReadableStream` type definition. It never existed in the specification nor in any implementation. This was fixed in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1134, and should no longer be in `lib.dom.d.ts`. (Maybe double-check that you're on the latest version of TypeScript?)

At the moment, `ReadableStream` is not yet marked as an async iterable because [it is not implemented by any browser](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1135#issuecomment-913061542), and thus it does not meet [the criteria for being added to the DOM type definitions](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/9c8c65810ae4e7ef403caa6e12ac86e04fdbd69e/README.md#why-is-my-fancy-api-still-not-available-here).

> Is there anything I can do to help?

Not a whole lot. You can try to convince Chromium ([#929585](https://bugs.chromium.org/p/chromium/issues/detail?id=929585)), Gecko ([#1496770](https://bugzilla.mozilla.org/show_bug.cgi?id=1496770)) and/or WebKit ([#194379](https://bugs.webkit.org/show_bug.cgi?id=194379)) to implement async iteration on `ReadableStream`, because we need at least two of them to implement it before we can add an official TypeScript type definition. 😅

**Comment by espindola** [comment]
> The `forEach` method was mistakenly added to the `ReadableStream` type definition. It never existed in the specification nor in any implementation. This was fixed in [microsoft/TypeScript-DOM-lib-generator#1134](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1134), and should no longer be in `lib.dom.d.ts`. (Maybe double-check that you're on the latest version of TypeScript?)

I have a current clone, but the last commit to change that file is from Jul 1, 2021 and forEach is still there:

https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L11924
 
> At the moment, `ReadableStream` is not yet marked as an async iterable because [it is not implemented by any browser](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1135#issuecomment-913061542), and thus it does not meet [the criteria for being added to the DOM type definitions](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/9c8c65810ae4e7ef403caa6e12ac86e04fdbd69e/README.md#why-is-my-fancy-api-still-not-available-here).

I guess that explains why deno has its own .d.ts :-)

> > Is there anything I can do to help?
> 
> Not a whole lot. You can try to convince Chromium ([#929585](https://bugs.chromium.org/p/chromium/issues/detail?id=929585)), Gecko ([#1496770](https://bugzilla.mozilla.org/show_bug.cgi?id=1496770)) and/or WebKit ([#194379](https://bugs.webkit.org/show_bug.cgi?id=194379)) to implement async iteration on `ReadableStream`, because we need at least two of them to implement it before we can add an official TypeScript type definition. sweat_smile

I would be more likely to try to convince "TSC" of the value of having a deno mode :-)

Thanks for the explanation, the situation makes a lot more sense now.

**Comment by MattiasBuelens** [comment]
> I have a current clone, but the last commit to change that file is from Jul 1, 2021 and forEach is still there:
> 
> https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L11924

Huh, strange. It looks like TypeScript's `main` branch is *behind* the latest [v4.5.5](https://github.com/microsoft/TypeScript/blob/v4.5.5/lib/lib.dom.d.ts#L10999-L11006) tag (committed on 12 November 2021). Not sure what's going on with that, you'd have to ask the TypeScript team. 😛

**Comment by dglazkov** [comment]
Yup, this just bit me. Have to do a weird thing like:

```typescript
const stream = response.body as unknown as AsyncIterable<ConcreteType>;
```

Because `fetch` is already implemented in Node v18+, people stumbling over this will likely be more common.

**Comment by nickmccurdy** [comment]
This is now supported in three runtimes (Node, Deno, and Bun). Can we merge this?

**Comment by saschanaz** [comment]
`dom.asynciterable` generation from the lib side is [done in Sept 2022](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1403) (thanks Mattias!), we need to add a corresponding option from TypeScript side.

**Comment by jedwards1211** [comment]
@saschanaz @sandersn `lib.dom.asynciterable.d.ts` doesn't seem to many of the intended type defs.  I'm confused but in Mattias' PR it only has

```
interface FileSystemDirectoryHandle {
    [Symbol.asyncIterator](): AsyncIterableIterator<[string, FileSystemHandle]>;
    entries(): AsyncIterableIterator<[string, FileSystemHandle]>;
    keys(): AsyncIterableIterator<string>;
    values(): AsyncIterableIterator<FileSystemHandle>;
}
```

I can't find `ReadableStream[Symbol.asyncIterator]()` etc anywhere in TS 5.4.5.  Can we reopen?

**Comment by saschanaz** [comment]
That's added later because of browser support state and should be added in a future TS version.

**Comment by jedwards1211** [comment]
@saschanaz as people have mentioned, this has been supported in many runtimes for over a year, so shouldn't we have a way to opt into these type defs already?

**Comment by saschanaz** [comment]
I mean asyncIterable support is [already there](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/cfd647637df06ae7a828b4e3d1459cb9480cf0f0/baselines/dom.asynciterable.generated.d.ts#L12-L15), what we need is just a new TS release.

ReadableStream.from problem is real and it's still Firefox only. Opting in is not available as we don't have conditional types in TS 😞 and declaration merge is also blocked by web-interfaces-not-being-actual-classes 😭.

**Comment by MattiasBuelens** [comment]
As @saschanaz said, it's already in TypeScript Nightly. You can [try it in the Playground](https://www.typescriptlang.org/play/?target=5&ts=5.5.0-dev.20240425#code/IYZwngdgxgBAZgV2gFwJYHsI2QUxMgCgEoYBvAWACgYaYpN8YAnPABwZxgF4ZgB3YKmTwcyKAAsCAInHJkrEAC4A9MriiJAOhCscUTX3HBkfAOab0TU8qlEA3FVrxLvAUJgF6ERhKQBrGHQ4ZjYOTQAjdAATMABCEgpqJ1ovEHQAGxxNdPRTT3F-CLBcABkcCFNkcXtHWgBfKgbKKlx8YjsgA).

**Comment by jedwards1211** [comment]
I'm not sure I'm understanding correctly - are the new type defs going to be included in the next release, or are they being delayed until environment support is more widely available?  This was implemented awhile ago so I was assuming it's the latter...

If they're being delayed I just wish TS would officially release some lib def we can opt into (in compilerOptions.lib) now even though environment support is still behind, so we wouldn't have to use a nightly build.

**Comment by mobs001** [comment]
Another year here. 
Come to here from some electron project. 
Gemini and cursor told me over and over again. Typescipt all ready has this type years ago, it is me messed up config. They told me some settings like "lib": ["DOM", "DOM.Iterable", "ESNext"]," should fix this. But seems it is an illusion.
It seems that although there is no official documentation, async iterable types are still not added? Is manually defining d.ts the only way?

**Comment by saschanaz** [comment]
Gemini is wrong, dom.asynciterable should be added too. Doesn't seem like it's listed in https://www.typescriptlang.org/tsconfig/#individual-library-components btw. (We should really change DOM to something else, as DOM is only subset of the web APIs.)
