### ISSUE TITLE
Typescript debugging in Visual Studio with IE and grunt uglify concat

### ISSUE THREAD

**Issue by damienbod** [Microsoft/TypeScript#2987]
Typescript debugging does not work when the JS files produced from the TS files are uglified and concated using grunt. (TS map files are ok!). If each file is used separately, the degugging works. Once uglified and concated, typescript debugging in Visual studio no longer works. maps exists for these files.

Is there a way to define the map files so that production code can be debugged using typescript files and Visual Studio?

Greetings Damien

**Comment by mhegazy** [comment]
how is concatenation happening? if itis simple string concatenation or are you using something like grunt-concat-sourcemap? just concatenating the spruces would break the source maps.

**Comment by damienbod** [comment]
grunt.loadNpmTasks('grunt-contrib-uglify');
grunt.loadNpmTasks("grunt-contrib-concat");

I tried all combinations with the two. As soon as more than one .ts file is concatted or uglified to a single source, the Visual Studio debugging does not work for the source typescript file. 

Workflow

1.	Typescript source files 
2.	Produces javascript files with source maps
3.	Uglify direct or concat and then uglify with source maps
4.	Production file (single uglified javascript file. (Debugging for the source typescript files does not work))


How can typescript be used to produce a single uglified javascript file from n-typescript source files which can be debugged in Visual Studio?

Is it not possible to debug typescript in Visual Studio for production javascript files?

Greetings Damien

**Comment by damienbod** [comment]
This doesn't work either
http://stackoverflow.com/questions/25792954/grunt-concat-uglify-with-sourcemaps

Doesn't map back to the .ts files

**Comment by danquirk** [comment]
Does uglify/grunt support concatenating source maps like this? The TypeScript compiler has done its job insofar as there are source maps for each file (or the single --out target). Additional tools that modify the source need to also support modifying the source maps appropriately.

**Comment by mhegazy** [comment]
pinging @nycdotnet and @basarat for this.

**Comment by basarat** [comment]
> Additional tools that modify the source need to also support modifying the source maps appropriately

Agreed. 

> Does uglify/grunt support concatenating source maps like this

Seems like it: https://github.com/gruntjs/grunt-contrib-uglify#sourcemapin

> As soon as more than one .ts file is concatted or uglified to a single source, the Visual Studio debugging does not work for the source typescript file

Just my experience: I don't use VS debugging, I've used chrome debug tools and firebug. Note that based on my testing there is no issue with `concatenation`. I've had success debugging concatenated files, however *uglification* can result in a tricky experience in that you don't get good resume support at breakpoints (i.e. `breakpoints` are mapped correctly but step over jumps over all the remaining lines in the function). So I just concat and not uglify during `dev`.

**Comment by nycdotnet** [comment]
I also don't use VS debugging for JavaScript.  Sadly I have found it to be buggy with regards to missing breakpoints and to have very bad performance in the immediate window.  Very bad performance means that Visual Studio might take *several seconds* to register each keystroke in the immediate window (clearly some sort of bug - I was assuming Perf Watson would figure it out).  Plus, I have had a few instances where `this` in the debugger in VS pointed to the wrong `this`.  ( Old issue from CodePlex site https://typescript.codeplex.com/workitem/1655 ).

So maybe at this time it would be good to give it an exercise again in the VS 2015 beta while there's still a little time to fix stuff.

I did issue a connect item regarding the IE dev tools and Uglify - not sure if this is a problem in VS too:  https://connect.microsoft.com/IE/feedback/details/1186333

@damienbod I have experienced some problems with SourceMaps, Uglify, and TypeScript - but actually *only when using the mangle option*.  Mangle changes locally scoped variable names and it's possible that VS is getting confused with that.

Are you using `sourceMapIn` with Uglify?

**Comment by danmosemsft** [comment]
>> I also don't use VS debugging for JavaScript. 

@nycdotnet -- couple questions as this issue is new to me.

1) Is this debugging IE from VS, or Chrome from VS?
2) What version of VS?
3) If you use the built in browser tools instead (either IE or Chrome as applicable) is the experience better?

**Comment by nycdotnet** [comment]
Hi @danmosemsft - This is debugging IE 11 from VS 2013 Update 4 with TypeScript 1.4 on a fully patched Windows 7 x64 computer (Quad core i5, 16 GB RAM, SSD).

It's been happening long enough that I didn't bother reporting again.  I can repro it right now on a small demo project (~fifty lines of JS across 5 files).  The IE 11 debugging tools work fine so I just stick with them.

**Comment by basarat** [comment]
> Plus, I have had a few instances where this in the debugger in VS pointed to the wrong this

Still an issue. Being tracked here : https://github.com/Microsoft/TypeScript/issues/2859

**Comment by damienbod** [comment]
Thanks for all your replies.

@nycdotnet 
I tried most of the different source map options with uglify as well as this, and none worked so that the src typescript files could be debugged with VS.

I haven't tried the mangle option yet. I will try this and also try grunt-ts instead of using the default typescript build. 

Feature Request: VS debugging with Typescript and production files (concat and uglify with maps)
-----------
I think debugging is something which should just work in VS for Typescript. It should be possible to debug a production build in Visual Studio using one selected browser. 

It's not important which browser, just one. And it's not important how the concat and the uglify is done, it should work for one per default in Visual Studio. I would switch to gulp or any other build automation, if this would work.

If this would work in VS, I could debug both frontend and backend together which would improve the developer experience and save development time.

Greetings Damien

**Comment by mhegazy** [comment]
@damienbod, are you saying that you can debug the same files in IE/chrome but not in VS? Or you just can not debug the at all?

**Comment by damienbod** [comment]
hi mhegazy, thanks for you reply.

I haven't tried debugging in chrome, I debug in VS because I also can debug the backend code. 

I have created an example, which demonstrates the problem. (Also the CPU problem in VS 2015 RC):

https://github.com/damienbod/AspNet5TypescriptProductionGrunt

No maps are included for uglify, how would you recommend debugging this?

At present, I have to create a index_debug.html which links the ts/js files directly.

greetings Damien

**Comment by mhegazy** [comment]
Sorry for the delay.. recovering from a log vacation :D

I just want to know which component to blame. if you are not using the minifier, are you able to debug?

**Comment by mhegazy** [comment]
@damienbod has this issue been resolved?

**Comment by damienbod** [comment]
@mhegazy Hi

No, I use a workaround, I have a second index_debug.html which links all the single files and this is used to debug. Each new file has to be linked twice, in the grunt file and in the index_debug file. The index_debug will be deleted in a none debug deployment. Not very pretty, but works. 

The problem happens when the src files get reduced to one file, maybe typescript could provide this functionality; n typescript files which produced one javascript min file with a map. This would be great.

Greetings Damien

**Comment by mhegazy** [comment]
closing this for now, minification support is tracked by https://github.com/Microsoft/TypeScript/issues/8
