### ISSUE TITLE
Nested assignment declaration doesn't merge with imported symbol

### ISSUE THREAD

**Issue by ArtyMaury** [microsoft/TypeScript#29870]
Hi, 
I was using axios, which includes typings. It worked well unitl I changed the value of an attribute.
Then I lost intellisense on the axios object.
Here are the screenshots to reproduce:

![image](https://user-images.githubusercontent.com/22880181/52300749-f2f5d900-2988-11e9-9032-23b3ff4cd76f.png)

![image](https://user-images.githubusercontent.com/22880181/52300892-58e26080-2989-11e9-9b82-e05b991a5750.png)

I tried with and without intellicode.
I don't know if it's due to typescript of vscode.

- VSCode Version: 1.30.2

**Comment by mjbvz** [comment]
I confirmed this with the example code:

```js
// @ts-check
import a from 'axios';

a.defaults.x = 1;
```

This produces the error `Import declaration conflicts with local declaration of 'a'.`. After the assignment,  `a` only has a `default` property:

<img width="885" alt="screen shot 2019-02-11 at 5 26 05 pm" src="https://user-images.githubusercontent.com/12821956/52605072-253c8600-2e22-11e9-91d8-214290b6dbff.png">

**Comment by sandersn** [comment]
Fixed by #32626
