### ISSUE TITLE
Error: Debug Failure (tsc.js:1296)

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/TypeScript#29875]
**TypeScript Version:**  3.3.3

**Search Terms:**
build 
watch 
crash
**Code**
`tsc --build --watch` is crashing occasionally (I have not been able to spot a pattern) - just editing and saving files (with and without errors):
```
C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:1296
            throw e;
            ^

Error: Debug Failure.
    at Object.assertDefined (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:1301:24)
    at C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:11765:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:11765:21)
    at createCompilerDiagnostic (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:11805:20)
    at reportStatus (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:75365:74)
    at formatUpToDateStatus (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:76072:24)
    at verboseReportProjectStatus (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:76029:20)
    at buildSingleInvalidatedProject (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:75702:13)
    at Timeout.buildInvalidatedProject [as _onTimeout] (C:\Users\gordon\git\hpcc-js\node_modules\typescript\lib\tsc.js:75656:17)
The terminal process terminated with exit code: 1
```

**Expected behavior:**
No crash and burn

**Actual behavior:**
watch process terminates

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@GordonSmith If you're able to attach a debugger at the `formatStringFromArgs` call and report the values of the parameters there when it crashes, that would save us a huge amount of time. Thanks!

**Comment by GordonSmith** [comment]
Here are the args:
```
{
  "0": {
    "code": 6350,
    "category": 3,
    "key": "Project_0_is_out_of_date_because_oldest_output_1_is_older_than_newest_input_2_6350",
    "message": "Project '{0}' is out of date because oldest output '{1}' is older than newest input '{2}'"
  },
  "1": "tsconfig.json",
  "3": "../../packages/marshaller/tsconfig.json"
}
```

**Comment by RyanCavanaugh** [comment]
@GordonSmith Perfect. Thanks!

**Comment by sheetalkamat** [comment]
@GordonSmith I have looked through code and cant seem to figure out where the issue lies as the parameter seem to be always defined. Do you mind if you share how and what project you were building, what files you were editing, may be that will help diagnose this.

**Comment by GordonSmith** [comment]
* Setup dev environment:
```
git clone https://github.com/hpcc-systems/Visualization
cd Visualization
git checkout candidate-2.x.x
npm install
npm run build-dev
```
* Then in VS Code open:  `demos/dashy/dashy.code-workspace`
* Press ctrl+shift+b and select `watch dashy` to kick off the main build watch process

Now is the tricky bit as you will need to reproduce the error, I would suggest opening:
* `marshaller/src/ddl2/dashboard.ts`
* `ddl2-shim/src/upgrade.ts`
* `dashy/src/index.ts`
And making random white space changes (some with errors, some without) and saving the docs as you go...

I typically see the issue a few times a day with the above setup - so don't expect an instant reproducible scenario...

(and I have seen it with v3.3.3)

**Comment by sheetalkamat** [comment]
@GordonSmith Thank you for repro steps, I see how this is pretty inconsistent and was able to repro it couple of times. Will investigate this further. Thanks.
