### ISSUE TITLE
Unexpected behavior when assigning class object to its interface and using spread operator

### ISSUE THREAD

**Issue by tejas-patel** [Microsoft/TypeScript#29882]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
interface A {
    readonly b: number;
    getB(): number;
}

class B implements A {
    readonly b: number;
    constructor(b: number) {
        this.b = b;
    }
    getB() {
        return this.b;
    }
}

class C implements A {
    readonly b: number;
    constructor(b: number) {
        this.b = b;
    }

    getB() {
        return this.b;
    }
}

const c: A = new C(4);
const d: A = {...c, b:5};
// This should fail typecheck but doesn't fail and javascript throws .getB() doesn't exist
console.log(d.getB());

```

**Expected behavior:**
Typecheck catches above error
**Actual behavior:**
Javascript throws error
**Playground Link:**  https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%20%20%20%20readonly%20b%3A%20number%3B%0D%0A%20%20%20%20getB()%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20implements%20A%20%7B%0D%0A%20%20%20%20readonly%20b%3A%20number%3B%0D%0A%20%20%20%20constructor(b%3A%20number)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.b%20%3D%20b%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20getB()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.b%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20C%20implements%20A%20%7B%0D%0A%20%20%20%20readonly%20b%3A%20number%3B%0D%0A%20%20%20%20constructor(b%3A%20number)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.b%20%3D%20b%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20getB()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.b%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20test(a%3A%20A)%20%7B%0D%0A%20%20%20%20if%20(a%20instanceof%20B)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('instance%20of%20B')%3B%0D%0A%20%20%20%20%7D%20else%20if%20(a%20instanceof%20C)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('instance%20of%20C')%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20c%3A%20A%20%3D%20new%20C(4)%3B%0D%0Aconst%20d%3A%20A%20%3D%20%7B...c%2C%20b%3A5%7D%3B%0D%0Aconsole.log(d.getB())%3B%0D%0A

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Root cause is lack of #9726
