### ISSUE TITLE
"Failable constructors" - Allow constructors to return undefined with "strictNullChecks" enabled.

### ISSUE THREAD

**Issue by danielvy** [Microsoft/TypeScript#29893]
## Search Terms
Failable, constructor,  undefined, strictNullChecks

## Suggestion

When `strictNullChecks` compiler option is set, constructors can not return `undefined` (or `null`).

The request is to allow marking a constructor as _"failable"_, which will negate the `strictNullChecks` for that constructor, adding `undefined` to the possible return type of the constructor. 

## Use Cases

Similar to other languages (like Swift's `init?()`).

It is often useful to return `undefined` from the constructor, indicating that an object can not be created with given parameters. 

This is possible in Javascript and Typescript unless `strictNullChecks` is set. 

`strictNullChecks` is very useful feature and often is the desired default behavior for the project but with `strictNullChecks`, returning `undefined` is not possible and there is no way to modify consturctor's return type to include `undefined` as with regular function.

The alternative in this case is to throw errors from within the constructor. Which is less elegant and flexable.

## Examples

```
class DictionaryWord {
  constructor(public word: string) {
    if(!isWordInDictionary(word)) {
      return undefined; // This is an error with "strictNullChecks"
    }
  }
}

const dictWord: DictionaryWord | undefined  = new DictionaryWord("word");
```

Possible way to mark the constructor failable is like this:
`constructor?(public word: string)`

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
It's because that's not how ECMAScript classes work.

```js
class Foo {
    constructor() {
        this.x = 100;
        return undefined
    }
}

let foo = new Foo();         // not 'undefined'
console.log(foo.x);          // prints '100'
foo.constructor;             // is 'Function'
foo.constructor === Function // true
```

**Comment by danielvy** [comment]
Oh my bad, I feel stupid now.

I actually knew this and completely overlooked the fact that JavaScript just silently ignores any primitives returned from the constructor. 

The good news is that I can use `strictNullChecks` without losing anything.

What would be a better "cleaner" practice to achieve a failable constructor in Typescript? Just throwing an error or returning an empty (or some sort of wrapper) object from the constructor?

Personally, I don't like using errors for program logic and reserve them for cases where the execution flow needs to be disrupted. Returning `undefined` / `null` would be better in this case. But returning an empty/dummy object doesn't seem ideal either.

**Comment by RyanCavanaugh** [comment]
Static factory methods would be the logical alternative if the constructor can meaningfully fail without "needing" to throw an exception.

**Comment by DanielRosenwasser** [comment]
Don't feel stupid, the entire behavior here is surprising to anyone unfamiliar with JS classes.

**Comment by igorsantos07** [comment]
This issue was returned from a google search about returning `undefined` from constructors - as the JS error might make you think it's acceptable as "normal return values".

[MDN explains (search for "return value")](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor) what exactly are the return values used in JS constructors and why this weird behavior exists. I was under the same impression it was possible to create failable constructors, but it's not :)
