### ISSUE TITLE
JSX: "extract to constant" generates invalid code

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#29890]
**TypeScript Version:**  3.3.1

**Search Terms:** jsx extract constant refactoring quick fix

**Code**

```tsx
<Foo><Bar /></Foo>;
```

when selecting `<Bar />` and actioning "extract to constant in enclosing scope"

**Expected behavior:**

``` tsx
const newLocal = <Bar />;
<Foo>{newLocal}</Foo>;
```

**Actual behavior:**

(missing braces)

``` tsx
const newLocal = <Bar />;
<Foo>newLocal</Foo>;
```

**Comment by Lenne231** [comment]
When using "Extract to function in module scope" the braces are missing as well.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by OliverJAsh** [comment]
This still happens when using fragments: https://github.com/microsoft/TypeScript/issues/44249

**Comment by a-tarasyuk** [comment]
@OliverJAsh Ok, will check

**Comment by OliverJAsh** [comment]
@a-tarasyuk I think I figured it out: https://github.com/microsoft/TypeScript/pull/44252
