### ISSUE TITLE
Function type argument inference indirectly lost with generic function

### ISSUE THREAD

**Issue by andykais** [Microsoft/TypeScript#29900]
**TypeScript Version:**  3.4.0-dev.20190213 (and 3.3.3)

**Search Terms:** generic function currying ArgumentTypes infer

**Code**

```ts
type ArgumentTypes<F extends Function> = F extends (...args: infer A) => any
  ? A
  : never

const safeCurry = <
  F extends (...args: any[]) => any,
  G extends (fResult: ReturnType<F>) => any
>(
  gFn: G,
  fFn: F
) => (...args: ArgumentTypes<F>): ReturnType<G> => gFn(fFn(...args))


// (x:number) => number
const curried = safeCurry(
  (x: string) => parseInt(x),
  (x: number) => x.toString()
)

// (...args: any[]) => any
const curried2 = safeCurry(
  <T>(x: T) => x,
  (x: number) => x
)
```

**Expected behavior:**
the `curried2` function should at least have the signature `(x: number) => any`, at best it would infer `(x: number) => number`

**Actual behavior:**
The args to the `currried2` function are incorrect. 

The reason why this is the case is confusing to me. Despite `gFn` being generic, and therefore harder for the compiler to understand what its `ReturnType` should be, the weird part is that this affects what `fFn`'s argument type inference is. The type signature `gFn` should not affect how `fFn` is inferred.

**Playground Link:** [playground link](https://www.typescriptlang.org/play/index.html#src=type%20ArgumentTypes%3CF%20extends%20Function%3E%20%3D%20F%20extends%20(...args%3A%20infer%20A)%20%3D%3E%20any%0D%0A%20%20%3F%20A%0D%0A%20%20%3A%20never%0D%0A%0D%0Aconst%20safeCurry%20%3D%20%3C%0D%0A%20%20F%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%2C%0D%0A%20%20G%20extends%20(fResult%3A%20ReturnType%3CF%3E)%20%3D%3E%20any%0D%0A%3E(%0D%0A%20%20gFn%3A%20G%2C%0D%0A%20%20fFn%3A%20F%0D%0A)%20%3D%3E%20(...args%3A%20ArgumentTypes%3CF%3E)%3A%20ReturnType%3CG%3E%20%3D%3E%20gFn(fFn(...args))%0D%0A%0D%0A%0D%0A%2F%2F%20(x%3Anumber)%20%3D%3E%20number%0D%0Aconst%20curried%20%3D%20safeCurry(%0D%0A%20%20(x%3A%20string)%20%3D%3E%20parseInt(x)%2C%0D%0A%20%20(x%3A%20number)%20%3D%3E%20x.toString()%0D%0A)%0D%0A%0D%0A%2F%2F%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%0D%0Aconst%20curried2%20%3D%20safeCurry(%0D%0A%20%20%3CT%3E(x%3A%20T)%20%3D%3E%20x%2C%0D%0A%20%20(x%3A%20number)%20%3D%3E%20x%0D%0A))

**Related Issues:**

**Comment by andykais** [comment]
Found another way to express `safeCurry` with the same type signature that almost gets there. It correctly discovers the argument type of `curried2` now, but the return type is still not inferable.

```ts
type ArgumentTypes<F extends Function> = F extends (...args: infer A) => any
  ? A
  : never

const safeCurry = <
  T,
  F extends (...args: any[]) => T,
  G extends (fResult: T) => any
>(
  gFn: G,
  fFn: F
) => (...args: ArgumentTypes<F>): ReturnType<G> => gFn(fFn(...args))


// (x:number) => number
const curried = safeCurry(
  (x: string) => parseInt(x),
  (x: number) => x.toString()
)

// (x: number) => {}
const curried2 = safeCurry(
  <T>(x: T) => x,
  (x: number) => x
)
```
[playground link](https://www.typescriptlang.org/play/index.html#src=type%20ArgumentTypes%3CF%20extends%20Function%3E%20%3D%20F%20extends%20(...args%3A%20infer%20A)%20%3D%3E%20any%0D%0A%20%20%3F%20A%0D%0A%20%20%3A%20never%0D%0A%0D%0Aconst%20safeCurry%20%3D%20%3C%0D%0A%20%20T%2C%0D%0A%20%20F%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20T%2C%0D%0A%20%20G%20extends%20(fResult%3A%20T)%20%3D%3E%20any%0D%0A%3E(%0D%0A%20%20gFn%3A%20G%2C%0D%0A%20%20fFn%3A%20F%0D%0A)%20%3D%3E%20(...args%3A%20ArgumentTypes%3CF%3E)%3A%20ReturnType%3CG%3E%20%3D%3E%20gFn(fFn(...args))%0D%0A%0D%0A%0D%0A%2F%2F%20(x%3Anumber)%20%3D%3E%20number%0D%0Aconst%20curried%20%3D%20safeCurry(%0D%0A%20%20(x%3A%20string)%20%3D%3E%20parseInt(x)%2C%0D%0A%20%20(x%3A%20number)%20%3D%3E%20x.toString()%0D%0A)%0D%0A%0D%0A%2F%2F%20(x%3A%20number)%20%3D%3E%20%7B%7D%0D%0Aconst%20curried2%20%3D%20safeCurry(%0D%0A%20%20%3CT%3E(x%3A%20T)%20%3D%3E%20x%2C%0D%0A%20%20(x%3A%20number)%20%3D%3E%20x%0D%0A))

**Comment by RyanCavanaugh** [comment]
Tracking at #30134
