### ISSUE TITLE
typeof abstract class do not allow typeof inherited classes

### ISSUE THREAD

**Issue by endel** [Microsoft/TypeScript#29909]
**TypeScript Version:**  3.3.3

**Search Terms:** typeof abstract class

**Code**

```ts
// Definition
export declare type PrimitiveType =
    "string" |
    "number" |
    "int8" |
    "uint8" |
    "int16" |
    "uint16" |
    "int32" |
    "uint32" |
    "int64" |
    "uint64" |
    typeof Schema;

export declare type DefinitionType = (PrimitiveType | PrimitiveType[] | {
    map: typeof Schema;
});

export declare type Definition = {
    [field: string]: DefinitionType;
};

export declare abstract class Schema {
    static _schema: Definition;
}

export declare function type(type: DefinitionType): (target: any, field: string) => void;

// Usage
class Player extends Schema {
    @type("string")
    name: string;

    constructor(param:string) { // this contructor creates the bug
        super();
    }
}

class State {
    @type({ map: Player }) // this doesn't work
    mapOfPlayers: { [id: string]: Player } = {};
}
```

**Expected behavior:**

Allow using `{ map: Player }` with different constructor signature, as it calls `super()` properly

**Actual behavior:**

```
TSError: ⨯ Unable to compile TypeScript:
src/server/rooms/State.ts(13,9): error TS2345: Argument of type '{ map: typeof Entity; }' is not assignable to parameter of type '"string" | "number" | typeof Schema | "int8" | "uint8" | "int16" | "uint16" | "int32" | "uint32" | "int64" | "uint64" | PrimitiveType[] | { map: PrimitiveType; }'.
  Type '{ map: typeof Player; }' is not assignable to type '"string"'.
```

**Playground Link:** 

https://typescript-play.js.org/?experimentalDecorators=true#code/PTAEBEFMDMEsDtYBdYHt4ChIA8AOqAnJUAE0gGMAbAQwMlCQE9d6AFA2AW2VgDdIAKs3oBeDKAmgARAGckHeAHMpoAD7jJU+AFdOAI0gEV6ydIRIAHMY0Sp281bU2z8JAEYAbNdN3zn75rmAMwATAG29q6h4S5IHgAsMb6uCTFMLKjQoADK5AAWkJzUANwYWHiExGRUtPTp9FBwiCjoQiygIqAAFOxcPPxt9KqgvdwoA8IA2gC6aqAA3s5FuABcDMKZOfmFJRgAvgCUpeX4RKQUNHTr7Y0IPOgdC86TcJCUJGtyCorTa7fNaHgg1Ke2OOFOVQutVA1D0X2o5GINRkMi2BSKT1McmoKHIoAA+jJtkU-jA7i14CCyuDKucaldoNp4IjAddIF16qSmvcgcIDmsObRFJAkGtqPBGAAaUCvd6feQIRQHDoAPlAvFQsBIxxAoAAqjJqMKMMjUawaIxDKAcEhIPASKjcujqJjJAABepdWQKpRSA7OeDUTiQeXfY6mcjoL7aRGELq4WhBlZfRXKxamLHaFgELpHMqmPb7MqmnJIHH0dPuz3zUDLNbm6iWgigQ5Lai4ADy0AbTZkaxrky1ocVvxGFqte0e81B+yAA

**Related Issues:** 

- https://github.com/Microsoft/TypeScript/issues/5843
- https://github.com/Microsoft/TypeScript/issues/5236

**Comment by endel** [comment]
I've edited my original post with an updated playground link!

**Comment by endel** [comment]
This has been fixed defining a permissive constructor on `Schema`:

```typescript
export declare abstract class Schema {
    static _schema: Definition;
    constructor (...args:any[]);
}
```

Not sure it's a bug though, hope you guys know :)

**Comment by dragomirtitian** [comment]
This is the expected behavior. Typescript issues an error because the constructor `Schema` takes no arguments, while the constructor of `Player` requires one. If your code were allowed this would be valid:

```ts
let cls: typeof Schema = Player;
class newCls extends cls {
    constructor() {
        super() // super call with no args, wops Player requires name
    }
}
```

The better approach to hold constructors that return `Schema` would be to use a constructor signature:

```ts
type Constructor<T> = new (...a:any[]) => Schema
export declare type PrimitiveType =
    "string" |
    "number" |
    "int8" |
    "uint8" |
    "int16" |
    "uint16" |
    "int32" |
    "uint32" |
    "int64" |
    "uint64" |
    Constructor<Schema>;

export declare type DefinitionType = (PrimitiveType | PrimitiveType[] | {
    map: Constructor<Schema>;
});
```
Although that will not allow abstract classes to be passed in. Or you can constrain `prototype` to allow abstract classes as well  (note: `Schema` as defined right now is equivalent to `{}` so any class will be accepted unless you define some members):
```ts
type AbstrctConstructor<T> ={ prototype: Schema }
```

**Comment by endel** [comment]
thanks for clarifying @dragomirtitian <3
