### ISSUE TITLE
Adjust Type guard behavior in iterators

### ISSUE THREAD

**Issue by crymis** [Microsoft/TypeScript#29916]
**TypeScript Version:** 3.2.2

**Search Terms:** Conditional Types, Type Guards, iterators, loop, callback functions

**Suggestion:**
When having values that are of union type and conditions result in telling the Typescript Type Guards to adjust the type, in basic Javascript iterator functions this adjusted type is reset to its initial type.

**Code Example:**
```
const myFunc = () => {
  let myVal: string | undefined;
  if (!myVal) return;
  myVal; // Type = string
  new Array(2).forEach(x => myVal); // Type = string | undefined
}
```

**Expected behavior:**
The type of `myVal` in the last line should only be of type `string`.
This would be nice for all iterators (e.g. for, while, map, …)

**Actual behavior:**
The type of `myVal` is `string | undefined`

**Playground Link:**
https://www.typescriptlang.org/play/#src=const%20myFunc%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20let%20myVal%3A%20string%20%7C%20undefined%3B%0D%0A%20%20%20%20if%20(!myVal)%20return%3B%0D%0A%20%20%20%20myVal%3B%20%2F%2F%20Typ%20%3D%20string%0D%0A%20%20%20%20new%20Array(2).forEach(x%20%3D%3E%20myVal)%3B%20%2F%2F%20Typ%20%3D%20string%20%7C%20undefined%0D%0A%7D

_Info:_
I don't know why, but the playground does not show the correct typing, please test in your code.

**Checklist:**
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment]
>I don't know why, but the playground does not show the correct typing, please test in your code.

You need to enable strictNullChecks in the options on the playground to see your issue reproduced there.

**Comment by j-oliveras** [comment]
Same as #29805 and duplicated/related to #9998.

Basically, typescript don't know if the predicate on `forEach` is called synchronously or not.

Workaround:
```ts
const myFunc = () => {
  let myVal: string | undefined;
  if (!myVal) return;
  const v =  myVal; // Type = string
  new Array(2).forEach(x => v); // Type = string
}
```
[Playground](https://www.typescriptlang.org/play/#src=%0D%0Aconst%20myFunc%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20let%20myVal%3A%20string%20%7C%20undefined%3B%0D%0A%20%20if%20(!myVal)%20return%3B%0D%0A%20%20const%20v%20%3D%20%20myVal%3B%20%2F%2F%20Type%20%3D%20string%0D%0A%20%20new%20Array(2).forEach(x%20%3D%3E%20v)%3B%20%2F%2F%20Type%20%3D%20string%0D%0A%7D) (enable `strictNullChecks`).

**Comment by crymis** [comment]
Thank you @j-oliveras for pointing the relations. 

I read about the workaround with the `const` declaration, thanks for that.

My feature-request here is to add logic for basic Javascript iterators. So, if it is a standard callback-function (not overwritten), then you could teach Typescript that these functions run synchronously, right?
