### ISSUE TITLE
transpileModule cannot transform JSON properly

### ISSUE THREAD

**Issue by leidegre** [microsoft/TypeScript#29911]
**TypeScript Version:**  `3.4.0-dev.20190214`

**Search Terms:** transpileModule JSON

**Code**

```ts
import {
  transpileModule,
  ScriptTarget,
  ModuleKind,
  TransformationContext,
  SourceFile,
  visitEachChild,
  isStringLiteral,
  VisitResult,
  Node,
  createStringLiteral
} from "typescript";

const transpileOutput = transpileModule(`{ "hello": "world" }`, {
  compilerOptions: {
    target: ScriptTarget.JSON,
    module: ModuleKind.None,
    removeComments: true
  },
  transformers: {
    after: [
      (ctx: TransformationContext) => {
        return (sourceFile: SourceFile) => {
          function visitor(node: Node): VisitResult<Node> {
            if (isStringLiteral(node)) {
              if (node.text === "world") {
                return createStringLiteral("JSON!");
              }
              return node;
            }
            return visitEachChild(node, visitor, ctx);
          }

          const sourceFile2 = visitEachChild(sourceFile, visitor, ctx);

          return sourceFile2;
        };
      }
    ]
  }
});

console.log(transpileOutput.outputText);
```

**Expected behavior:**

```json
{ "hello": "JSON!" }
```

**Actual behavior:**

```js
({ "hello": "JSON!" })
```

**Workaround:**

I've tracked this issue down to the fact that TypeScript internally wraps the `ObjectLiteralExpression` with a `ParenthesizedExpression` even though it produces illegal JSON in the end.

I use the TypeScript compiler to process JSON because it can strip comments and I'm familiar with its interface. It struck me as a surprise that it would NOT allow me to use custom transformers without going through additional steps.

I currently use this utility function to *fix* the problem but I don't think TypeScript should make me **have** do this.

I could have missed something here but I spent a good chunk of time analysing the problem and this was the only way I could make it work for me in the end.

```ts
function deParenthesize(sourceFile: SourceFile) {
  const statements = sourceFile.statements
  if (statements.length === 1) {
    const statement = statements[0]
    if (isExpressionStatement(statement)) {
      const expression = statement.expression
      if (isParenthesizedExpression(expression)) {
        // we cannot use the "createExpressionStatement" helper
        // it would just reintroduce the ParenthesizedExpression

        const replacement = createNode(
          SyntaxKind.ExpressionStatement,
          -1,
          -1
        ) as ExpressionStatement
        replacement.flags |= NodeFlags.Synthesized
        replacement.expression = expression.expression

        sourceFile.statements = createNodeArray([replacement])
      }
    }
  }
}
```
Additionally, if I include `fileName: "module.json"` in the transpilation options, I get, `Error: Debug Failure. Output generation failed` and this wasn't the case before. This behavior changed between TypeScript 3.1 and 3.3 but I'm not sure of which version exactly.

If I dump the `sourceFile.languageVersion` it will show up as `ES2015` despite using the `compilerOptions` `target: ScriptTarget.JSON`.

**Comment by RyanCavanaugh** [comment]
`target: ScriptTarget.JSON` is not a valid value (you can't specify this in a tsconfig file or on the commandline); emitting to JSON files isn't a supported scenario.

**Comment by leidegre** [comment]
@RyanCavanaugh it would be good to know if there was some manner in which I could depend on TypeScript for JSON processing. I don't fully understand why the `ScriptTarget.JSON` exist if it cannot be used. I would also probably have wished for a more meaningful error message.

I know you guys are super busy but any kind of insight would be greatly appreciated.
