### ISSUE TITLE
Project references with path aliases

### ISSUE THREAD

**Issue by DataTables** [Microsoft/TypeScript#29918]
**TypeScript Version:**  typescript@3.4.0-dev.20190214

**Search Terms:** TS2307 `Project reference` `alias` `paths` `Cannot find module`.

**Code**  https://github.com/DataTables/project-references-demo .

The repo is cloned from https://github.com/RyanCavanaugh/project-references-demo and slightly modified to demonstrate the issue. It appears to be related to the fact that I am storing my source files in a `src` sub-directory for each component and using a `path` alias to reference between them. Running:

```
npm install
node node_modules/typescript/bin/tsc -p animals --traceResolution
```

Produces output that includes:

```
======== Resolving module '@core/utilities' from '/home/allan/Downloads/project-references-demo-master/animals/src/dog.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to '/home/allan/Downloads/project-references-demo-master/', using this value to resolve non-relative module name '@core/utilities'.
'paths' option is specified, looking for a pattern to match module name '@core/utilities'.
Module name '@core/utilities', matched pattern '@core/*'.
Trying substitution 'core/src/*', candidate module location: 'core/src/utilities'.
Loading module as file / folder, candidate module location '/home/allan/Downloads/project-references-demo-master/core/src/utilities', target file type 'TypeScript'.
File '/home/allan/Downloads/project-references-demo-master/core/src/utilities.ts' exist - use it as a name resolution result.
```

indicating that the file was correctly resolved. However, I get:

```
animals/src/dog.ts:2:32 - error TS2307: Cannot find module '@core/utilities'.

2 import { makeRandomName } from '@core/utilities'
```

from tsc. The reason I've filed this as a bug is that the two don't appear to align - it is correctly resolved, but then tsc says it can't be found.

**Expected behavior:** 

No error. The aliased module is imported.

**Actual behavior:**

The TS2307 error is given. VS Code also shows the same error.

**Related Issues:**

#26823 Seems very similar, but there the module resolver does not resolve. Here it does, but it still ultimately showing as cannot be found.
#26819 _might_ be related, but I'm not sure and the suggested resolution there doesn't work.

**Comment by sheetalkamat** [comment]
This is working as intended since core is not built as per your steps, because you aren't building using `--build`
`tsc --build` works correctly by first building core and then animals and thus making sure dependency is built and when module resolution matches to `core/src/utilities.ts` the corresponding output file is present. (you are getting error in your repro because the output file for `core/src/utilities.ts` does not exist)
May be we should give better error message here.
cc @DanielRosenwasser @RyanCavanaugh

**Comment by DataTables** [comment]
Argh - thank you! Yup - completely user error. I even read that part of the documentation which said that it needs the dependencies to be built first, but I got myself all confused.

I'll leave open for you to decide what to do with this (error messages or not).
