### ISSUE TITLE
Why index signature type should be assignable to all known members? 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#29924]
I want to define an object type where I explicitly define types of known members and then have a different type for unknown members (type of the index signature):

```ts
interface Known {
    foo?: () => boolean;
}

interface Unknown {
    [k: string]: () => number;
}

type All = Known & Unknown;

let a: All = {
    foo: () => true
}

let b: All = {
    randomKey: () => 1
}
```
With above code, TypeScript complains that "Property `foo` is incompatible with index signature". 

**Why type of property `foo` has to be compatible with index signature? 

This issue originally came up here: https://github.com/typescript-eslint/typescript-eslint/pull/272#discussion_r256669440

**Comment by RyanCavanaugh** [comment]
> Why type of property `foo` has to be compatible with index signature?

That's what an index signature means - it applies to *all* properties, not just those not declared. See #17867 and related issues for more discussion.
