### ISSUE TITLE
Experimental decorators error when opening a vscode from the project folder

### ISSUE THREAD

**Issue by arunap2509** [microsoft/TypeScript#29925]
I am working on a vue project with vuetify and typescript in it, and .net core 2.1 as backend, when opening the file from the folder that has the client side code the **Experimental decorators** error is not appearing, but we are now developing the entire project in vscode  for both client side and server side, so when I open the root folder which has both client and server side file in it, the **Experimental decorators** error is throwing, and here is my 
    **tsconfig.json** 
{

>   "compilerOptions": {
>     "target": "esnext",
>     "module": "esnext",
>     "strict": true,
>     "jsx": "preserve",
>     "importHelpers": true,
>     "moduleResolution": "node",
>     "experimentalDecorators": true,
>     "esModuleInterop": true,
>     "allowSyntheticDefaultImports": true,
>     "sourceMap": true,
>     "baseUrl": ".",
>     "types": [
>       "webpack-env"
>     ],
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     },
>     "lib": [
>       "esnext",
>       "dom",
>       "dom.iterable",
>       "scripthost"
>     ]
>   },
>   "include": [
>     "src/**/*.ts",
>     "src/**/*.tsx",
>     "src/**/*.vue",
>     "tests/**/*.ts",
>     "tests/**/*.tsx"
>   ],
>   "exclude": [
>     "node_modules"
>   ]
> }

        And I also enabled the experimental decorators in vscode user settings, and also have an 
      **settings.json** file as 
            {
                      "editor.wordWrap": "on",
                        "typescript.tsdk": "node_modules/typescript/lib"
             }
               and also I tried deleting the source code from _typescript/lib/tsserver.js_, even that didnt help.
         is there any way to stop this error from happening when opening from the main root folder.

**Comment by BryanCrotaz** [comment]
I think you also need to have `allowJs: true`
(https://ihatetomatoes.net/how-to-remove-experimentaldecorators-warning-in-vscode/)

**Comment by arunap2509** [comment]
@BryanCrotaz   even  I read that blog you shared, I tried the same thing, it still didnt work
