### ISSUE TITLE
Conditional type is deferred because narrow-as-assertion on constrained type parameter has no effect

### ISSUE THREAD

**Issue by jack-williams** [microsoft/TypeScript#29939]
Sorry for the gratuitous title.

**Code**

```ts
type IsString<X> = [X] extends [string] ? true : false

function isString<X extends string, Y>(x: X, y: Y)  {
    if (typeof x === "string") {
        const a: IsString<typeof x> = true; // error: conditional type is deferred
    }
    if (typeof y === "string") {
        const b: IsString<typeof y> = true;
    }
}
```

**Expected behavior:**

The two to behave the same; probably, they should both be OK.

**Actual behavior:**

The type of `x` does not get narrowed by assertion, presumably because the assertion adds no information. Conditional type resolution ignores parameter constraints when attempting to resolve using the most restrictive instantiation, and therefore `IsString<typeof x>` does not resolve.

Essentially `T extends string`, and `T & string` where `T` is unconstrained, do not behave the same in conditional check types. The former has its constraint ignored, while the latter gets to use its intersection proof.

**Playground Link:**  [link](https://www.typescriptlang.org/play/#src=type%20IsString%3CX%3E%20%3D%20%5BX%5D%20extends%20%5Bstring%5D%20%3F%20true%20%3A%20false%0D%0A%0D%0Afunction%20isString%3CX%20extends%20string%2C%20Y%3E(x%3A%20X%2C%20y%3A%20Y)%20%20%7B%0D%0A%20%20%20%20if%20(typeof%20x%20%3D%3D%3D%20%22string%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20a%3A%20IsString%3Ctypeof%20x%3E%20%3D%20true%3B%20%2F%2F%20error%3A%20conditional%20type%20is%20deferred%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20if%20(typeof%20y%20%3D%3D%3D%20%22string%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20b%3A%20IsString%3Ctypeof%20y%3E%20%3D%20true%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:**

**Comment by jack-williams** [comment]
I understand why type parameter constraints are ignored by the restrictive instantiation. Using transitive reasoning with `any` breaks a whole load of things, as shown from the example in `checker.ts`.

```ts
type Foo<T extends { x: any }> = T extends { x: string } ? string : number
```
A question I have is: are there other examples that do not involve `any`, where ignoring constraints is necessary? I can think of another one:

```ts
type Bar<T extends Object> = T extends object ? string : number
```

Would it be fair to say that the restrictive instantiation is currently necessary purely because conditional type resolution uses assignability, a non-transitive relation?

I know that `definitelyAssignable` was a thing at one point; was that crafted with the intent to be a transitive type relation?

**Comment by jack-williams** [comment]
I think I know enough about this now to say that it's a design limitation.

- It is correct that a type parameter `T extends string` does not get narrowed to `T & string` upon `typeof` because the intersection adds no information: the type parameter is already a subtype of `string`.
- The only other vector of change would be to consider constraints in conditional types but there are multiple reasons why this is difficult (and incorrect in some cases).

This leads me to the conclusion that this is just an awkward composition of concepts, but one that few people seem to face.

**Comment by newlukai** [comment]
> 
> 
> I think I know enough about this now to say that it's a design limitation.
> 
>     * It is correct that a type parameter `T extends string` does not get narrowed to `T & string` upon `typeof` because the intersection adds no information: the type parameter is already a subtype of `string`.
> 
>     * The only other vector of change would be to consider constraints in conditional types but there are multiple reasons why this is difficult (and incorrect in some cases).
> 
> 
> This leads me to the conclusion that this is just an awkward composition of concepts, but one that few people seem to face.

@jack-williams Would be really great to learn something here. Currently I'm trying to use a conditional type as return type of a function. Inside the function I'm narrowing down on the constraints of the conditional type to return the corresponding value (similar to [this SO post](https://stackoverflow.com/questions/50642020/typescript-how-to-write-a-function-with-conditional-return-type).

As I read your posts here I'm wondering about the square bracket notation in your `IsString` type. What does it do?

And you wrote considering constraints in conditional types would sometimes be incorrect. I assume this is the reason why writing a function with conditional return type is not possible. Right? And could you explain why?
