### ISSUE TITLE
Compiler API: createPropertySignature ignores initializer expression

### ISSUE THREAD

**Issue by vicpro** [Microsoft/TypeScript#29946]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**
return ts.createPropertySignature(
    [ts.createToken(ts.SyntaxKind.ExportKeyword), ts.createToken(ts.SyntaxKind.ConstKeyword)],
    "abc",
    undefined,
    undefined,
    ts.createLiteral(5)
  );
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
export const abc = 5;

**Actual behavior:**
export const abc;
**Playground Link:** 

**Related Issues:**

**Comment by dragomirtitian** [comment]
A property signature node is created as part of an interface. For example this would create a property signature:

```ts
declare interface T {
  prop: number // props signature for this
}
```

If you want to create an exported variable you will need to create a variable statement with a declaration list.

```ts
ts.createVariableStatement(ts.createModifiersFromModifierFlags(ts.ModifierFlags.Export),
    ts.createVariableDeclarationList([
        ts.createVariableDeclaration("abc", undefined, ts.createLiteral(5))
]))
```
You can use [this](https://astexplorer.net/#/gist/a554349d3234afff2154a4b0b735a25e/ac5936c11259bba8414999df17b0c447ff03f38b) to find out what nodes are generated for a piece of code.

Answered [here](https://stackoverflow.com/questions/54724840/how-to-create-exported-constant-using-typescript-ast/54731608#54731608) as well, you need to give the SO elves a bit more time to work :)

**Comment by vicpro** [comment]
`
ts.createVariableStatement(ts.createModifiersFromModifierFlags(ts.ModifierFlags.Export),
    ts.createVariableDeclarationList([
        ts.createVariableDeclaration("abc", undefined, ts.createLiteral(5))
], ts.NodeFlags.Const)) //to raplace var to const
`
Thank you @dragomirtitian ! Do you know any Compiler API examples which will help to avoid such stupid bugreports?

**Comment by dragomirtitian** [comment]
@vicpro  For creating ASTs if I already know the shape of the code  I usually use [ast explorer](https://astexplorer.net) like I said in my previous comment. As far as docs, I don't think there is more than the [wiki page](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)
