### ISSUE TITLE
Conditional type narrowing works wrong

### ISSUE THREAD

**Issue by vshab** [Microsoft/TypeScript#29942]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** conditional type narrowing

**Code**

```ts
type IfNull<T, U> = T extends null ? U : string;

function foo(error: Error | null) {
  // OK - a: string | number
  let a: IfNull<typeof error, number>;

  if (error) {
    // OK - b: string
    const b: IfNull<typeof error, number> = "";

    // SHOWS WRONG - a: string | number
    // but compiles
    a = "";

    return;
  }

  // SHOWS OK - c: number
  // but doesn't compile: "error TS2322: Type '1' is not assignable to type 'string'"
  const c: IfNull<typeof error, number> = 1;

  // WRONG - a: string | number
  // doesn't compile: "error TS2322: Type '1' is not assignable to type 'string'."
  a = 1;
}
```

**Expected behavior:**
Type condition should account type-narrowing-if so the code above should be correct. VSCode popups should show narrowed types after `if` statement.

**Actual behavior:**
Type condition doesn't get resolved after if (definition of `c` and  assignment `1` to `a` cause errors). VSCode popups show wrong unnarrowed types for `a` after `if` statement.

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20IfNull%3CT%2C%20U%3E%20%3D%20T%20extends%20null%20%3F%20U%20%3A%20string%3B%0D%0A%0D%0Afunction%20foo(error%3A%20Error%20%7C%20null)%20%7B%0D%0A%20%20%2F%2F%20OK%20-%20a%3A%20string%20%7C%20number%0D%0A%20%20let%20a%3A%20IfNull%3Ctypeof%20error%2C%20number%3E%3B%0D%0A%0D%0A%20%20if%20(error)%20%7B%0D%0A%20%20%20%20%2F%2F%20OK%20-%20b%3A%20string%0D%0A%20%20%20%20const%20b%3A%20IfNull%3Ctypeof%20error%2C%20number%3E%20%3D%20%22%22%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20SHOWS%20WRONG%20-%20a%3A%20string%20%7C%20number%0D%0A%20%20%20%20%2F%2F%20but%20compiles%0D%0A%20%20%20%20a%20%3D%20%22%22%3B%0D%0A%0D%0A%20%20%20%20return%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20%2F%2F%20SHOWS%20OK%20-%20c%3A%20number%0D%0A%20%20%2F%2F%20but%20doesn't%20compile%3A%20%22error%20TS2322%3A%20Type%20'1'%20is%20not%20assignable%20to%20type%20'string'%22%0D%0A%20%20const%20c%3A%20IfNull%3Ctypeof%20error%2C%20number%3E%20%3D%201%3B%0D%0A%0D%0A%20%20%2F%2F%20WRONG%20-%20a%3A%20string%20%7C%20number%0D%0A%20%20%2F%2F%20doesn't%20compile%3A%20%22error%20TS2322%3A%20Type%20'1'%20is%20not%20assignable%20to%20type%20'string'.%22%0D%0A%20%20a%20%3D%201%3B%0D%0A%7D%0D%0A

**Related Issues:** Didn't find

VSCode screenshots:
<img width="785" alt="screenshot 2019-02-16 at 20 38 57" src="https://user-images.githubusercontent.com/6755908/52900664-117e8e80-322b-11e9-8e69-48f83206b210.png">
<img width="784" alt="screenshot 2019-02-16 at 20 38 47" src="https://user-images.githubusercontent.com/6755908/52900665-117e8e80-322b-11e9-9125-0611ced83d2b.png">
<img width="833" alt="screenshot 2019-02-16 at 20 38 31" src="https://user-images.githubusercontent.com/6755908/52900666-117e8e80-322b-11e9-97fe-9b009b9f113a.png">

**Comment by jack-williams** [comment]
Are you running `--strictNullChecks`?

**Comment by vshab** [comment]
@jack-williams my bad. Sorry. It was in `tsconfig.json` but seems like I need to pass in compiler implicitly. 
I'll close for now and try another case. 
Thank you!
