### ISSUE TITLE
typename() intrinsic function to emit the type as a string literal

### ISSUE THREAD

**Issue by ryan-haksi** [Microsoft/TypeScript#29944]
## Search Terms

type instance stringizing name

## Suggestion

It would be really useful to get the type of something as a string so it can be evaluated later at runtime. 

typename() intrinsic function,

returns whatever your typescripts sees as the type as a string, this is emitted as a string constant in the output javascript.

## Use Cases

- Runtime logging in a generic where its desirable to log the interface name for debugging purposes.
- Anywhere you have a strict separation between data and logic (ie it came from JSON, redux etc), there is no constructor to use a proxy for a type instance.
- would allow implementation of a reflection system without touching the compiler.

## Examples

```
const s = typename(string); // "string"

// the above would be emitted in javascript as:
const s = "string";

const s = "hello world";
const typename = typename(s) // "string"

const stringOrNumber: string | number = 9;
const typename = typename(stringOrNumber); // string | number

interface MyInterface { name: string, email: string };
const typename = typename( {} as MyInterface ); // "MyInterface"
const typename = typename( null as MyInterface ); // "MyInterface"
const typename = typename( undefined as MyInterface ); // "MyInterface"

// This would also allow construction of descriptor object literals that can 
// survive transfer through JSON serialization
interface TypeInstance<T> {
  _t: string;
  _keys: string;
}

function TypeInstanceOf<T>(): TypeInstance<T> {
  return { _t: typename(T), _keys: typename(keyof T) } 
}

const typeinstance = TypeInstanceOf<MyInterface >(); // { _t: "MyInterface", _keys: "name | email" }

const typestring = JSON.stringify(typeinstance); // "{ _t: "MyInterface", _keys: "name | email" }"
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
Unfortunately this doesn't check out with with the 3rd/4th items in the checklist.

```ts
* This could be implemented without emitting different JS based on the types of the expressions
* This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
```

Any reason quick-info in the editor doesn't work?

**Comment by ryan-haksi** [comment]
That would completely defeat the goal.

I want to make the type information available to the runtime as a string
literal, this means you can avoid doing things like:

myFunction<T>(typename: string, arg: string) {
  console.log( typename + " says " + arg );
}

example code:
myFunction<MyType>("MyType", "hello world"); // yuck, no inference, had to
double enter type constant, no safety on typename, could have a typo

With the typename intrinsic this would be first some standard boilerplate
for reference:
interface TypeTunnel<T> { typeName: string; }
myTypeTunnel<T>() { return { typename T } as TypeTunnel<T>; }

// now exercise the new functionality
myFunction( myTypeTunnel<T>(), "hello world" );

Also note this sort of thing is very common in most languages, see
stringizing operator, token pasting operator and so forth, and it requires
no new runtime functionality, its just saves having to enter all the type
literals manually as strings by declaring a string literal for you.
