### ISSUE TITLE
Incorrect types for native errors subtypes

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/TypeScript#29943]
**TypeScript Version:**  master (3.4.0)

**Search Terms:** ErrorConstructor

**Code**
```ts
// In Node, ErrorConstructor is augmented with extra properties. Excerpted below.
interface ErrorConstructor {
  captureStackTrace(targetObject: Object, constructorOpt?: Function): void;
}

function myFunction(x: ErrorConstructor) { return true; }
myFunction(Error); // OK

// Error: Property 'captureStackTrace' is missing in type 'RangeErrorConstructor' 
// but required in type 'ErrorConstructor'.
myFunction(RangeError); 
```

**Actual behavior:**
Errors, as indicated in the comment.

**Expected behavior:**

I would expect calling `myFunction(RangeError)` to work. 

[According to the spec](https://tc39.github.io/ecma262/#sec-properties-of-the-nativeerror-constructors), the constructor functions for the native errors (`RangeError`, `SyntaxError`, etc) have the base `Error` constructor as their [[Prototype]]. Therefore, I would expect that any augmentations to the base `ErrorConstructor` type would be visible on the interfaces for the other native error constructors. My first instinct was that this would be accomplished by setting up those child interfaces in `lib.es5.d.ts` to extend `ErrorConstructor`, i.e.:

```ts
// Proposed lib.es5.d.ts
interface RangeErrorConstructor extends ErrorConstructor { /* ... */ } 
interface SyntaxErrorConstructor extends ErrorConstructor { /* ... */ } 
// etc.
```

Today, the other error constructor interfaces don't extend `ErrorConstructor`, so the type system doesn't know that `RangeErrorConstructor` also has a `captureStackTrace` function.

However, when I tried to edit `lib.es5.d.ts` to set up the `extends` clause, I ran into this error, from the Node typings:

```
error TS2510: Base constructors must all have the same return type.

1861     export class Recoverable extends SyntaxError {
                                          ~~~~~~~~~~~
```

I'm not sure what the right way to fix this is, but I do think the behavior in my first code snippet is a bug, and I would hope there's some way to address it (that also still allows the various native error constructors to themselves be subclassable).

**Playground Link:** 
[Here](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20In%20Node%2C%20ErrorConstructor%20is%20augmented%20with%20extra%20properties.%20Excerpted%20below.%0D%0Ainterface%20ErrorConstructor%20%7B%0D%0A%20%20captureStackTrace(targetObject%3A%20Object%2C%20constructorOpt%3F%3A%20Function)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Afunction%20myFunction(x%3A%20ErrorConstructor)%20%7B%20return%20true%3B%20%7D%0D%0AmyFunction(Error)%3B%20%2F%2F%20OK%0D%0AmyFunction(RangeError)%3B%20%2F%2F%20Error%0D%0A%0D%0Ainterface%20Error%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20message%3A%20string%3B%0D%0A%20%20%20%20stack%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20This%20is%20my%20proposed%20fix%2C%20but%20see%20the%20error%20it%20causes%20with%20Recoverable.%0D%0Ainterface%20SyntaxErrorConstructor%20extends%20ErrorConstructor%20%20%7B%0D%0A%20%20%20%20new(message%3F%3A%20string)%3A%20SyntaxError%3B%0D%0A%20%20%20%20(message%3F%3A%20string)%3A%20SyntaxError%3B%0D%0A%20%20%20%20readonly%20prototype%3A%20SyntaxError%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Recoverable%20extends%20SyntaxError%20%7B%0D%0A%0D%0A%7D)

**Comment by sandersn** [comment]
@DanielRosenwasser @rbuckton Making RangeErrorConstructor a subtype of ErrorConstructor seems reasonable, but I remember some problems with error subclassing a few years ago. Do you remember what they were?

**Comment by DanielRosenwasser** [comment]
Our ES5 emit doesn't work for it, but no problems with the type system itself.

**Comment by rbuckton** [comment]
I concur with @DanielRosenwasser. Custom subclasses of `Error` in `--target ES5` and earlier do not work without some extra effort, but having the native error constructors properly extend `ErrorConstructor` seems fine.

**Comment by sandersn** [comment]
All right, I'll move this out to 3.7 then. It's a bit late to put lib changes into 3.6.
