### ISSUE TITLE
Function declaration is exported

### ISSUE THREAD

**Issue by marjune163** [Microsoft/TypeScript#29940]
**Search Terms:**
function declaration, export

**Code**

```ts
declare function myfunc(): any
interface MyInterface {}

export {
	myfunc,
	MyInterface
}
```

```bash
tsc --module es2015 test.ts
cat test.js
```

**Expected behavior:**
(empty)

**Actual behavior:**
```javascript
export { myfunc };
```

**Playground Link:** 
https://typescript-play.js.org/?target=2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsBPFdACgEoAueKVIgKC1QxBkSjAQFkiBJFmw5d4AbwC+DBiAAeABxwwMYhgEhipMABo1vAa3acQDSUA

**Console info**
```bash
$ cat test.ts 
declare function myfunc(): any
interface MyInterface {}

export {
	myfunc,
	MyInterface
}

$ tsc --version
Version 3.4.0-dev.20190216
$ tsc --module es2015 test.ts 
$ cat test.js 
export { myfunc };
```

**Comment by dragomirtitian** [comment]
A function declaration is not the same as the interface. The function declaration tells Typescript that somehow (not Typescript's problem how) that function will exist at runtime. After the declaration the function will behave as any other function would and thus gets exported.

If you just want a function type, use a type alias :

```ts

type myfunc = () => any

```

**Comment by marjune163** [comment]
I see. Thanks.
