### ISSUE TITLE
Type inference is down after upgrade to 3.2/3.3 from 3.1

### ISSUE THREAD

**Issue by Brooooooklyn** [microsoft/TypeScript#29958]
**TypeScript Version:**  3.3.3

**Search Terms:**

**Code**
In this pull request https://github.com/LeetCode-OpenSource/rxjs-hooks/pull/28

https://github.com/LeetCode-OpenSource/rxjs-hooks/blob/master/src/__test__/use-event-callback.spec.tsx#L148

`useEventCallback` is work fine here in `typescript 3.1`, but breaks after `typescript 3.2`

**Expected behavior:**
`factory` inferred to 
```ts
(eventSource$: Observable<MouseEvent<HTMLButtonElement>>, inputs$: Observable<[number]>, state$: Observable<number>) => Observable<number>
```
**Actual behavior:**

`factory` inferred to 
```ts
(eventSource$: Observable<MouseEvent<HTMLButtonElement>>, inputs$: Observable<[number]>, state$: Observable<number[]>) => Observable<number[]>
```

## Self-contained repo
https://github.com/Brooooooklyn/ts-bug-29958

**Comment by RyanCavanaugh** [comment]
Please provide a self-contained repro

**Comment by Brooooooklyn** [comment]
@RyanCavanaugh https://github.com/Brooooooklyn/ts-bug-29958

**Comment by Kingwl** [comment]
A minimum version: 

https://www.typescriptlang.org/play/index.html#src=export%20type%20RestrictArray%3CT%3E%20%3D%20T%20extends%20any%5B%5D%20%3F%20T%20%3A%20%5B%5D%0Aexport%20type%20VoidAsNull%3CT%3E%20%3D%20T%20extends%20void%20%3F%20null%20%3A%20T%0A%0A%0Aexport%20type%20EventCallbackState%3CEventValue%2C%20State%2C%20Inputs%20%3D%20void%3E%20%3D%20%5B%0A%20%20(val%3A%20EventValue)%20%3D%3E%20void%2C%0A%20%20%5B%0A%20%20%20%20State%20extends%20void%20%3F%20null%20%3A%20State%2C%0A%20%20%20%20State%20%7C%20null%2C%0A%20%20%20%20RestrictArray%3CInputs%3E%20%7C%20null%0A%20%20%5D%0A%5D%0Aexport%20type%20ReturnedState%3CEventValue%2C%20State%2C%20Inputs%3E%20%3D%20%5B%0A%20%20EventCallbackState%3CEventValue%2C%20State%2C%20Inputs%3E%5B0%5D%2C%0A%20%20EventCallbackState%3CEventValue%2C%20State%2C%20Inputs%3E%5B1%5D%5B0%5D%0A%5D%0A%0Aexport%20type%20EventCallback%3CEventValue%2C%20State%2C%20Inputs%3E%20%3D%20Inputs%20extends%20void%0A%20%20%3F%20(%0A%20%20%20%20%20%20eventSource%24%3A%20EventValue%2C%0A%20%20%20%20%20%20state%24%3A%20State%0A%20%20%20%20)%20%3D%3E%20State%0A%20%20%3A%20(%0A%20%20%20%20%20%20eventSource%24%3A%20EventValue%2C%0A%20%20%20%20%20%20inputs%24%3A%20RestrictArray%3CInputs%3E%2C%0A%20%20%20%20%20%20state%24%3A%20State%0A%20%20%20%20)%20%3D%3E%20State%0A%0Aexport%20declare%20function%20useEventCallback%3CEventValue%3E(%0A%20%20callback%3A%20EventCallback%3CEventValue%2C%20void%2C%20void%3E%0A)%3A%20ReturnedState%3CEventValue%2C%20void%20%7C%20null%2C%20void%3E%0Aexport%20declare%20function%20useEventCallback%3CEventValue%2C%20State%3E(%0A%20%20callback%3A%20EventCallback%3CEventValue%2C%20State%2C%20void%3E%2C%0A%20%20initialState%3A%20State%0A)%3A%20ReturnedState%3CEventValue%2C%20State%2C%20void%3E%0Aexport%20declare%20function%20useEventCallback%3CEventValue%2C%20State%2C%20Inputs%3E(%0A%20%20callback%3A%20EventCallback%3CEventValue%2C%20State%2C%20Inputs%3E%2C%0A%20%20initialState%3A%20State%2C%0A%20%20inputs%3A%20RestrictArray%3CInputs%3E%0A)%3A%20ReturnedState%3CEventValue%2C%20State%2C%20Inputs%3E%0Aexport%20declare%20function%20useEventCallback%3CEventValue%2C%20State%20%3D%20void%2C%20Inputs%20%3D%20void%3E(%0A%20%20callback%3A%20EventCallback%3CEventValue%2C%20State%2C%20Inputs%3E%2C%0A%20%20initialState%3F%3A%20State%2C%0A%20%20inputs%3F%3A%20RestrictArray%3CInputs%3E%0A)%3A%20ReturnedState%3CEventValue%2C%20State%20%7C%20null%2C%20Inputs%3E%0A%0A%0Adeclare%20const%20factory%3A%20(%0A%20%20event%24%3A%20Object%2C%0A%20%20inputs%24%3A%20number%5B%5D%2C%0A%20%20_state%24%3A%20number%2C%0A)%20%3D%3E%20number%0A%0Aconst%20initialValue%20%3D%201000%0A%0AuseEventCallback(factory%2C%20initialValue%2C%20%5B0%5D)

**Comment by Kingwl** [comment]
Found in the tracking: It may be because conditional type inferred the type for different branches, even if it was not used, And the type inference is not `no effect`
