### ISSUE TITLE
Generic  type extending base interface, cannot assign object of same shape

### ISSUE THREAD

**Issue by ChristopherKiss** [Microsoft/TypeScript#29952]
**TypeScript Version:**  3.4.0-dev.201xxxxx
3.2.4

**Search Terms:**
Generic constraints
Generic inheritance object literal

**Code**

Given the below code, `const test` will throw an error, however as you can see from `let test2`. The property of the generic matches.

Maybe it's an issue with my understanding, but scouring https://www.typescriptlang.org/docs/handbook/generics.html, I can't seem to find why this isn't assignable. The error doesn't offer any help. It says what is wrong, but WHY can't it be assigned?

This is a stripped down example.
```ts
interface IBase { 
    id: string;
}

interface ITest extends IBase { }

class Test<T extends IBase> { 
    public save() {
        const test: T = { id: '123' };

        let test2: T;
        test2.id = '';
    }
}
```

**Expected behavior:**
I would expect that I can assign { id: string } to a generic that extends an interface of { id: string }

**Actual behavior:**
I receive an error:
`Type '{ id: string; }' is not assignable to type 'T'.`

**Playground Link:** 
https://www.typescriptlang.org/play/#src=interface%20IBase%20%7B%20%0D%0A%20%20%20%20id%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ITest%20extends%20IBase%20%7B%20%7D%0D%0A%0D%0Aclass%20Test%3CT%20extends%20IBase%3E%20%7B%20%0D%0A%20%20%20%20public%20save()%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20test%3A%20T%20%3D%20%7B%20id%3A%20'123'%20%7D%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20let%20test2%3A%20T%3B%0D%0A%20%20%20%20%20%20%20%20test2.id%20%3D%20''%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/29519 - Possibly related?

**Comment by dragomirtitian** [comment]
Inside the `Test` class `T` is not fully known. All the compiler knows about `T` is that it must be a subtype of `IBase`. But a subtype of `IBase` could have more mandatory properties than `id`. Even in your sample code `ITest` has a required property `test` which is not assigned when creating the object literal you assign inside `save`.

If what you want were allowed, this could happen:
```ts

interface IBase { 
    id: string;
}

interface ITest extends IBase { test: string; }

class Test<T extends IBase> { 
    public save() {
        const test: T = { id: '123' }; // if this were alowed we get wierd behavior in otehr places
        return test;
    }
}


new Test<ITest>().save().test // surprise! why is test undefined here ?! 

```

So to sum up, the compiler can't prove that the object literal `{ id: '123'} ` is assignable to `T` because as we have seen it might not always be assignable. You can access and set a property if you already have an instance of `T` that is not a problem, but you just don't know enough about `T` to create it.

**Comment by ChristopherKiss** [comment]
@dragomirtitian,

Ok, so that makes sense now that it can't pick up the type.

But how do I tell the compiler more information to prove that it is IBase.

My use case is that I'll have several interfaces all extending IBase.

Inside the Test class, all I care about is the id property, but inside this class the other properties will need to exists, but obviously can't be inferred until I type guard T which is fine, I just want the one property which could always be inferred, the id, to be available without a type guard, hence wanting to extend IBase.

**Comment by dragomirtitian** [comment]
@ChristopherKiss 

You can always use a type assertion to get the object literal to be assignable to `T` (although you are risking the behavior I outlined in the previous comment) or you can pass in a callback that initializes an object will all required properties:

```ts

interface IBase { 
    id: string;
}

interface ITest extends IBase { test: string; }

//type Omit<T, K> = 
class Test<T extends IBase> {
    public save() {
        const test: T = { id: '123' } as T;
        return test;
    }
}

class Test2<T extends IBase> {
    constructor(private ctor: () => T) { }
    public save() {
        const test = {
            ...this.ctor(),
            id: "123"
        }
    }
}

new Test2<ITest>(() => ({ id:'', test:'' }))

```

**Comment by ChristopherKiss** [comment]
@dragomirtitian,

Thanks for the help, makes a lot of sense, yeah I'd want to avoid type assertion as the point is to keep proper type safety to avoid these types of errors, rather than just getting around them.

I'll need to rethink my approach, but your callback suggestion is something I'll look into.

Many thanks for the help.

**Comment by tday** [comment]
I ran in to this recently and came up with a workaround for safe types:

```typescript
interface IBase { 
    id: string;
}

interface ITest extends IBase { test: string; }

class Test<T extends IBase> {
    public save() {
        const test: IBase = { id: '123' };
        return test as T;
    }
}
```

This is only safe if you know that `test` will in fact be of just IBase
