### ISSUE TITLE
Infer right operand type from assignment

### ISSUE THREAD

**Issue by bios21** [Microsoft/TypeScript#29968]
## Search Terms
- infer
- infer right
- infer operand
- type of operand
- type not null
- not null assignment

I found this issue: #1656 but it's a pretty basic and old one.

## Suggestion
The `infer` keyword is really great, but it could be more useful to use it on the **right** operand during variable assignment.  
I know that for primary type, it's already built-in:
```ts
interface I1 {
  foo: string;
}

let a: I1 = null;
a.foo = true; // will fail as expected
a.foo = null; // will not fail with --strictNullCheck=false
```

But what if we can infer the right operand ourselves for nullable type?

## Use Cases
Can be very useful for strictNullCheck micro management or lite version of TypeGuard.

## Examples

```ts
interface I1 {
  foo: string;
}

// suggestion is "infer right" keyword for example (or "infer operand" ?)
type NotNull<T> = {
  [P in keyof T]: T[P] extends infer right R ?
    R extends null ? never : R
  : T[P]
}

let a: NotNull<I1> = null;
a.foo = true; // will fail as expected
a.foo = null; // would fail *without* the need of --strictNullCheck=true
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). <= I guess.

**Comment by RyanCavanaugh** [comment]
The suggestion seems to be predicated on a lot of misconceptions about how the type system works. Expressions like `R extends null` are nearly meaningless in `strictNullChecks: false`. The checking of an assignment doesn't really proceed through a conditional type like that.

This mostly to say that we don't plan on adding anything for the sake of making "some" strict null checking work outside of real strict null checks mode.
