### ISSUE TITLE
Missing suggestions for composite objects in typescript

### ISSUE THREAD

**Issue by yarastqt** [microsoft/TypeScript#29974]
This trouble found after update typescript in VSCode to 3.x.x version

- VSCode Version: 1.31.1
- OS Version: macOS Mojave 10.14
- Typescript Version: 3.3.3

So, we have some code:
```ts
type Theme1 = { theme?: '1' };
type Theme2 = { theme?: '2' };

type Size1 = { size?: '1' };
type Size2 = { size?: '2' };

type Shared = { view?: '1' };

type Props = Shared & (Theme1 | Theme2) & (Size1 | Size2);

const data: Props = { view: '1', theme: '1' }
```

Steps to Reproduce:

1. Start typing property `view` and get suggestion for autocomplete
2. Start typing property `size` or `theme` and to get nothing

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I'm not able to reproduce this using the latest VS Code 1.32 insiders build with TypeScript 3.3.3:

![screen shot 2019-02-19 at 11 35 32 am](https://user-images.githubusercontent.com/12821956/53042157-7cea7b00-343a-11e9-8bb7-ce5585a0486b.png)

Do you see this issue if you open that TS file in an empty project, or does it only happen if that file is part of a larger project?

**Comment by yarastqt** [comment]
Hi, i'm testing at empty project, have two files `tsconfig.json & index.ts`, but if set `strict=true` in `tsconfig` then everything breaks.

**Comment by yarastqt** [comment]
Option `strictNullChecks=true` breaks this.

**Comment by yarastqt** [comment]
@mjbvz Have any ideas? :)

**Comment by yarastqt** [comment]
@mjbvz ping

**Comment by Kingwl** [comment]
![image](https://user-images.githubusercontent.com/6831019/55150580-621ccc00-5187-11e9-909a-d67c7575d251.png)

cannot reproduce in current 3.4.0-20190308 with empty project and strictNullChecks

**Comment by yarastqt** [comment]
Yup, i can't reproduce too for actual version 3.7
