### ISSUE TITLE
Inferred return type is wrong when using async function

### ISSUE THREAD

**Issue by P4sca1** [Microsoft/TypeScript#29979]
**TypeScript Version:**  3.3.1

**Code:**

```ts
import * as Joi from 'joi'

interface ISettings {
  [key: string]: boolean | string | number | null
}

async function test(settings: ISettings) {
  const result = Joi.validate(settings, Joi.object().keys())
  return result
}
```

**Expected behavior:**
The return type of `test` should be `Promise<Joi.ValidationResult<ISettings>>`

**Actual behavior:**
The return type is `Promise<ISettings>`

**More info:**
Removing the `async` does correctly infer the return type. Adding `async` just removes `Joi.ValidationResult`.

Here's a picture to demonstrate the problem, which really got me crazy:
Hovering over the returned variable.
![](https://imgur.com/9fY3OQT.png)

Hovering over the inferred return type.
![](https://i.imgur.com/aIs7QiX.png)

As you can see on the pictures, TypeScript just messes up the return type somehow.

**Comment by jack-williams** [comment]
`ValidationResult` is `thenable` right?

**Comment by P4sca1** [comment]
@jack-williams I don't know what that means, tbh. Could you point me to the documentation for `thenable`?

Here are the relevant `joi` types extracted from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/joi/index.d.ts.

```ts
interface ValidationResult<T> extends Pick<Promise<T>, 'then' | 'catch'> {
    error: ValidationError;
    value: T;
```

```ts
validate<T>(value: T, options?: ValidationOptions): ValidationResult<T>;
```

**Comment by jack-williams** [comment]
Sorry I think the correct term is `PromiseLike`.
```ts
interface PromiseLike<T> {
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): PromiseLike<TResult1 | TResult2>;
}
```
You can't constructed nested promises like `Promise<Promise<number>>` at run time.
```ts
declare const x: Promise<Promise<number>>;

async function foo()  {
    const result: number = await x;
    return result;
}
```
Anything that is `PromiseLike` gets unpacked down to some non-promise like think. I think a validation result has a `then` method on it, which means it recursively gets unpacked by async. 

I'm not entirely sure on this, so welcome any corrections.

**Comment by P4sca1** [comment]
I can’t find anythink including the PromiseLike type in the definition file.

**Comment by jack-williams** [comment]
```ts
interface ValidationResult<T> extends Pick<Promise<T>, 'then' | 'catch'> {
    //                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    error: ValidationError;
    value: T;
}
```
It seems that validation result has the `then` and `catch` methods from `Promise`. Have you executed your `test` function? What is the result of `test(settings).then(x => console.log(x))`.

**Comment by P4sca1** [comment]
Yeah what it does it, it provides the result in 3 ways, even if the function itself is sync.
```ts
const result = Joi.validate(value, schema)
// or
const result = await Joi.validate(value, schema)
// or
Joi.validate(value, Schema, (result) => {})
```

So if I get you right, because the returned type included `then` and `catch` it is automatically considered of type `PromiseLike`?
And because of that it gets unpacked by `async`.
If I would actually use it as a promise (e.g. `await Joi.validate()`) then it should work because the result is no longer `PromiseLike` right?
Going to test that asap.

**Comment by P4sca1** [comment]
Actually handling `Joi.validate()` as a promise fixed the issue. Thank you for your help @jack-williams !
