### ISSUE TITLE
typescript 1.5 beta in webstorm 10.0.2, get an error: TS2304-Cannot find name 'DataView'

### ISSUE THREAD

**Issue by raregrass** [Microsoft/TypeScript#2998]
What steps will reproduce the problem?
1. Use custom typescript 1.5 beta compiler.
2. Type a code snippet:    let a: typeof DataView.
3. Get an error:   Error:(1, 15) TS2304: Cannot find name 'DataView'.

What is the expected result?
It should be right.

What happens instead?
Get an error.

Please provide any additional information below.
When I use bounded typescript 1.4 compiler and the new typescript 1.5 alpha compiler, everything is OK. I don't know where I should put this issue, so I put it both in webstorm and typescript issue track platform. Please check and tell me what should I do.
![image](https://cloud.githubusercontent.com/assets/3363650/7439704/b84f4406-f0b8-11e4-9860-53822efd817e.png)

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #2953, which is fixed in #2960.

@mhegazy #2953 says the fix is slated for 1.5.2, but #2960 was merged into `master`. Just want to make sure I give a correct release timeframe for this.

**Comment by raregrass** [comment]
Thanks for your help! @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Glad to help!
