### ISSUE TITLE
Files ending with comments causes generated code to append the original code.

### ISSUE THREAD

**Issue by blackening** [Microsoft/TypeScript#2999]
See screenshot for repro code, its much clearer.
![minimal repro code](https://cloud.githubusercontent.com/assets/1753927/7439840/db615cf0-f0c1-11e4-8c1d-4e29e33a6e5b.png)

Generated using grunt-typescript 0.6.1/typescript 1.4.1 with the following config:
```
typescript: {
			base: {
				src: ["src/**/*.ts"],
				options: {
					module: "commonjs", 
					target: "es5", 
					basePath: "src",
					sourceMap: false, 
					declaration: false,
					references:[
						"typings/**/*.d.ts"
					]
				}
			}
		}
```

Assuming its unlikely that grunt-typescript will produce this kind of bug.

**Comment by DanielRosenwasser** [comment]
Duplicate of #1714, and has been fixed since. If you try out our recently released [TypeScript 1.5 beta](http://blogs.msdn.com/b/typescript/archive/2015/04/30/announcing-typescript-1-5-beta.aspx), you'll get the correct behavior.

**Comment by blackening** [comment]
All right, thanks!

**Comment by DanielRosenwasser** [comment]
No prob, let us know how 1.5 works for you!
