### ISSUE TITLE
Incorrect tuple union type deduction

### ISSUE THREAD

**Issue by pavel** [Microsoft/TypeScript#29998]
**TypeScript Version:**  3.3.3 and 3.4.0-dev.20190220 with `--strictNullChecks`

**Search Terms:**
tuple, union, type deduction, destructuring

**Code**

```ts
function fn(): [null, number] | [string, null] {
  if (Math.random() > 0.5) {
    return [null, 2]
  }
  return ["Str", null]
}

// l: string | null (correct)
// r: number | null (correct)
const [l, r] = fn()
if (l === null) {
  // r: number | null (incorrect)
  console.log(r + 2)
} else {
  // l: string (correct)
  // r: number | null (incorrect)
  console.log(l.toLowerCase(), r === null)
}
```

**Expected behavior:**
No compilation errors. Correct type hints.

**Actual behavior:**
Compilation error:
> TS2531: Object is possibly 'null'.

at `console.log(r + 2)`. Incorrect type hints.

**Playground Link:** 
[Playground link](https://www.typescriptlang.org/play/#src=function%20fn()%3A%20%5Bnull%2C%20number%5D%20%7C%20%5Bstring%2C%20null%5D%20%7B%0D%0A%20%20if%20(Math.random()%20%3E%200.5)%20%7B%0D%0A%20%20%20%20return%20%5Bnull%2C%202%5D%0D%0A%20%20%7D%0D%0A%20%20return%20%5B%22Str%22%2C%20null%5D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20l%3A%20string%20%7C%20null%20(correct)%0D%0A%2F%2F%20r%3A%20number%20%7C%20null%20(correct)%0D%0Aconst%20%5Bl%2C%20r%5D%20%3D%20fn()%0D%0Aif%20(l%20%3D%3D%3D%20null)%20%7B%0D%0A%20%20%2F%2F%20r%3A%20number%20%7C%20null%20(incorrect)%0D%0A%20%20console.log(r%20%2B%202)%0D%0A%7D%20else%20%7B%0D%0A%20%20%2F%2F%20l%3A%20string%20(correct)%0D%0A%20%20%2F%2F%20r%3A%20number%20%7C%20null%20(incorrect)%0D%0A%20%20console.log(l.toLowerCase()%2C%20r%20%3D%3D%3D%20null)%0D%0A%7D). Make sure to enable "strictNullChecks".

**Related Issues:**
Did not find anything exactly like this issue.

**Comment by jack-williams** [comment]
This is tracked by this #12184. If you go to the linked issue #28981 the example is more-or-less the same as the one you provide.

**Comment by pavel** [comment]
Thanks.
