### ISSUE TITLE
Typescript API: change Typescript code programmatically ?

### ISSUE THREAD

**Issue by frankps** [Microsoft/TypeScript#29993]
I already tried StackOverflow for this question, but no real answer there...

Basically we're searching for an API to change Typescript code 
(intput is Typescript & output is also Typescript)

Background:
We're writing a code generator/builder for the community that helps generating code for basic use cases (like building forms and  menus). 

I have written myself a library to parse & extend existing Typescript files (such as adding properties & methods to classes, updating arrays, ...), but it has its limitations.

Does there exist a library that can help? (change Typescript code programmatically)

**Comment by AlCalzone** [comment]
TypeScript itself can do that. I'm not sure where all of this is documented, but you can see an example here:
https://github.com/fimbullinter/wotan/issues/488#issuecomment-452443888

**Comment by frankps** [comment]
OK, thanks: I will check this out!

**Comment by ajafff** [comment]
I guess you are looking for something like "transforms" that change the AST of a file which you can then write back to a disk.
https://dev.doctorevidence.com/how-to-write-a-typescript-transform-plugin-fc5308fdd943

**Comment by agentcooper** [comment]
Useful links:
- http://ts-ast-viewer.com
- https://ts-creator.js.org/

**Comment by Kingwl** [comment]
And: https://astexplorer.net/ :XD

**Comment by dsherret** [comment]
@frankps my library might help. The API will probably be a bit more natural to pick up and make your code more maintainable: https://github.com/dsherret/ts-morph

**Comment by frankps** [comment]
Thx a lot everybody: I will check it out!
@dsherret your library was already on my shortlist: I check it out this weekend!
