### ISSUE TITLE
Always assigning to an un-initialized variable in an exhaustive switch

### ISSUE THREAD

**Issue by apexskier** [microsoft/TypeScript#30000]
**TypeScript Version:** 3.4.0-dev.20190220

**Search Terms:**
switch case exhaustive assignment assign undefined TS2322

**Code**
Compile with the flags `--noImplicitReturns --noImplicitAny --strictNullChecks`

```ts
enum Test {
    A,
    B,
    C
}

// this example correctly understands that all possible values of t are handled
function foo(t: Test): number {
    switch (t) {
        case Test.A:
            return 1;
        case Test.B:
            return 2;
        case Test.C:
            return 3;
    }
}

// this should be identical to foo, since a is always assigned as the switch is exhaustive
function bar(t: Test): number {
    let a;
    switch (t) {
        case Test.A:
            a = 1;
        case Test.B:
            a = 2;
        case Test.C:
            a = 3;
    }
    return a; // I don't expect an error here
}
```

**Expected behavior:**
Code compiles with no errors. When `a` is returned in `bar`, its type is `number`. Typescript understands that an exhaustive switch with each case assigning to a type-inferred variable means that the variable's type is the union of each assigned value's type. I'd expect this to work because returns within an exhaustive switch are understood in a similar manner.

**Actual behavior:**
When `a` is returned in `bar`, its type is `number | undefined`
```
TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

**Playground Link:**
[link here](https://www.typescriptlang.org/play/#src=enum%20Test%20%7B%0D%0A%20%20%20%20A%2C%0D%0A%20%20%20%20B%2C%0D%0A%20%20%20%20C%0D%0A%7D%0D%0A%0D%0A%2F%2F%20this%20example%20correctly%20understands%20that%20all%20possible%20values%20of%20t%20are%20handled%0D%0Afunction%20foo(t%3A%20Test)%3A%20number%20%7B%0D%0A%20%20%20%20switch%20(t)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Test.A%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.B%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%202%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.C%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%203%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20this%20should%20be%20identical%20to%20foo%2C%20since%20a%20is%20always%20assigned%20as%20the%20switch%20is%20exhaustive%0D%0Afunction%20bar(t%3A%20Test)%3A%20number%20%7B%0D%0A%20%20%20%20let%20a%3B%0D%0A%20%20%20%20switch%20(t)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Test.A%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20a%20%3D%201%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.B%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20a%20%3D%202%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.C%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20a%20%3D%203%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20a%3B%20%2F%2F%20I%20don't%20expect%20an%20error%20here%0D%0A%7D)
Turn on `noImplicitReturns`, `noImplicitAny`, and `strictNullChecks`.

**Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/22470 (different, since the default doesn't assign)
- https://github.com/Microsoft/TypeScript/issues/18362 (this is pretty old, from TS 2.4.2. Since `foo` in my example works I think the closure reason might be invalid)

**Comment by RyanCavanaugh** [comment]
Comments in #18362 still apply. We have some special-casing we're capable of doing for `return`, but it doesn't generalize to assignments.

**Comment by aleksey-bykov** [comment]
how is it not covered by officially recommended:
```ts
declare function noMore(never: never): never;

// this should be identical to foo, since a is always assigned as the switch is exhaustive
function bar(t: Test): number {
  let a;
  switch (t) {
    case Test.A:
      a = 1;
      break;
    case Test.B:
      a = 2;
      break;
    case Test.C:
      a = 3;
      break;
    default: return noMore(t);
  }
  return a; // I don't expect an error here
}
```
?

**Comment by aleksey-bykov** [comment]
![image](https://user-images.githubusercontent.com/937933/55368067-ec359f00-54bd-11e9-8599-09386dde281d.png)

http://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by aleksey-bykov** [comment]
duplicate of #8545?
