### ISSUE TITLE
type guards for Enums

### ISSUE THREAD

**Issue by ackvf** [microsoft/TypeScript#30002]
This is a feature suggestion explained on a use case with a menu and a filter controlled by the menu items.

I have a list of items of an enum type called `Items`, the `Items` enum is source for a filter menu that adds two additional options `enum Side = { ALL_LEFT= 'ALL_LEFT' | ALL_RIGHT= `ALL_RIGHT` }

When the filter value is matching the type of `Items`, the item type is being filtered.
When the filter value matches `Side`, different logic for filter will be applied.

    // this is the Item types
    enum AA {
      A= 'A',
      B= 'B',
      C= 'C',
    }

    // These are the additional options
    enum XX {
      X = 'X',
      Y = 'Y',
    }

    // workaround for enum merging. These are all the valid values for filter.
    export const AX = { ...XX, ...AA } // const AX: { A: AA.A; B: AA.B; C: AA.C; X: XX.X; Y: XX.Y;  }
    export type AX = AA | XX;

    // Now none of these have worked obviously :( , but this one looked promising in the IDE
    function isType<T>(arg: any, e?: T): arg is T {
      return arg in e!
    }

    // This would be the preferred way, but how do I tell it that I do have an enum that has both, a type and a value?
    // function isType<T>(arg: any): arg is T {
    //   return arg in T // 'T' only refers to a type, but is being used as a value here.
    // }

    // function isType<T>(arg: any, e: T): arg is T { // later: Argument of type 'typeof XX' is not assignable to parameter of type 'XX'
    //   return arg in e 
    // }

    function test(value: AA, filter: AX) {
      if (isType<XX>(filter)) {
        filter // XX
        if (filter === XX.X) filter // XX.X
        else filter // XX.Y
      } else {
        filter // AA
      }

      if (isType(filter, XX)) { // Argument of type 'typeof XX' is not assignable to parameter of type 'XX'
        filter // XX
        if (filter === XX.X) filter // XX.X
        else filter // XX.Y
      } else {
        filter // AA
      }

      if (isType(filter, XX)) { // Argument of type 'typeof XX' is not assignable to parameter of type 'XX'
        filter // (AA.A & typeof XX) | (AA.B & typeof XX) | (AA.C & typeof XX) | (XX.X & typeof XX) | (XX.Y & typeof XX)
        if (filter === XX.X) filter // XX.X & typeof XX
        else filter // (AA.A & typeof XX) | (AA.B & typeof XX) | (AA.C & typeof XX) | (XX.X & typeof XX) | (XX.Y & typeof XX)
      } else {
        filter // AX
      }

      if (filter in XX) {
        filter // AX
        if (filter === XX.X) filter // XX.X
        else filter // AA | XX.Y
      } else {
        filter // AX
      }
    }

I am still just learning the typescript way, so forgive me if I am missing something obvious. Thanks!

**Comment by ackvf** [comment]
I still care for this question though.

**Comment by pheliperocha** [comment]
I would like to know about this question also

**Comment by Semigradsky** [comment]
@ackvf @pheliperocha try this https://github.com/microsoft/TypeScript/issues/30611#issuecomment-570773496

**Comment by maxwellainatchi** [comment]
Hi, I believe this answers the original question (snippet from from https://stackoverflow.com/questions/52661835/casting-strings-to-enum-in-typescript)

```typescript
function isPropertyValue<T>(object: T, possibleValue: any): possibleValue is T[keyof T] {
  return Object.values(object).includes(possibleValue);
}
```

**Comment by playerony** [comment]
I didn't find such a package on npm and I thought it would be nice to create one: https://www.npmjs.com/package/is-some-enum. I think it will help someone :)
