### ISSUE TITLE
TypeScript: Formatter deletes comment

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/TypeScript#30003]
```ts
const result = Event.any<any>(fromKeydown, fromKeyup,/*  fromMouse */);
```

1. Format Document

I end up with

```ts
const result = Event.any<any>(fromKeydown, fromKeyup);
```

**Comment by mjbvz** [comment]
Confirmed on typescript@3.4.0-dev.20190220

**Comment by fuafa** [comment]
Can a formatter delete non-whitespace character? What is the expected behavior for `foo('', )`

**Comment by a-tarasyuk** [comment]
This rule applies to the provided example and the issue in training comma.
https://github.com/microsoft/TypeScript/blob/b8b59489e1040c288d6cf4593bd561d14770bbe7/src/services/formatting/rules.ts#L261 

Without training comma formater works properly 

```ts
foo(1 /* comment */);
```

**Comment by TRCYX** [comment]
Not completely fixed it seems.
```ts
fu(
    5, /*afsd*/);
```
The formatter still removes comments for the above code. It looks like that the fixing PR https://github.com/microsoft/TypeScript/pull/36674 only handles the case where ',' is on the same line as '(', while if ',', the comment, or ')' begins a new line, some other mechanism makes the comment stay.

Yes, in reality no one writes code like this, but it still seems wrong.
