### ISSUE TITLE
Signature safety when overriding methods

### ISSUE THREAD

**Issue by nebrius** [Microsoft/TypeScript#30006]
## Search Terms

default implementation, override, abstract, abstract implementation, override keyword

## Suggestion

I would like to suggest we add an `override` keyword, similar to the [override keyword in C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/override). This way, we can ensure the type safety of overriding methods in TypeScript while allowing for default implementations in base classes.

## Use Cases

I specifically want to use this for the recently created [Abstract IO](https://github.com/nebrius/abstract-io). This module is part of the [Johnny-Five](http://johnny-five.io/) Node.js robotics library and ecosystem. It provides a base class that [IO Plugin](https://github.com/rwaldron/io-plugins) authors can use to implement their IO Plugins. I am transitioning [Raspi IO](https://github.com/nebrius/raspi-io/) to it, the IO Plugin that adds support for the Raspberry Pi to Johnny-Five, and it is written in TypeScript. Other IO Plugin authors are also interested in transitioning to it.

Each IO Plugin implements as much of the IO Plugin spec as possible, but due to hardware limitations on various boards, it's rare for an IO Plugin to implement _every_ method in the IO Plugin spec. As such, there is a mixture of methods with custom implementation for the given platform, and methods that throw with a generic "method foo is not supported on platform bar" Error. Because of this, abstract methods aren't useful in practice. In addition, some consumers of this module will be writing their code in vanilla JavaScript, and so wouldn't see the abstract methods anyways since they are compiled out.

In this case, it is necessary for the base class to have an implementation that looks like:

```TypeScript
public digitalWrite(pin: string | number, value: number): void {
  throw new Error(`digitalWrite is not supported by ${this.name}`);
}
```

Then, when I override in a TypeScript, I manually copy the signature over to the derived class, and have to manually ensure that the signatures match.

I would like for a system to be implemented that compiles fine when not overriding the method at all, but throws a compile error if the overridden signature does not match, which I believe is best accomplished with an `override` keyword.

## Examples

```TypeScript
class A {
  public isValid(name: string): boolean {
    throw new Error(`The "isValid" method is not supported by this class`);
  }
}

class B extends A {}
(new B()).isValid('B'); // throws an exception

class C extends A {
  public override isValid(name: string): boolean {
    return name == 'C';
  }
}
(new C()).isValid('C'); // return "true"

class D extends A {
  public override isValid(notName: number): number {} // compile error
}

```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #13217 ?

**Comment by nebrius** [comment]
@RyanCavanaugh ah yes, it would appear to be a duplicate. Guess I didn't search back far enough 😅
