### ISSUE TITLE
Class method can be used in spread syntax before declaration

### ISSUE THREAD

**Issue by scottcheng** [Microsoft/TypeScript#30001]
**TypeScript Version:**  3.3.1

**Search Terms:** class, spread

**Code**

```ts
class C {
    state = {
        ...this.makeState()
    };
    makeState = () => ({});

    log() {
        console.log(this.state);
    }   
}

(new C).log();
```

**Expected behavior:**
Fails to compile, because `this.makeState` is used before declaration.

**Actual behavior:**
It compiles, and crashes in runtime.

**Playground Link:** <http://www.typescriptlang.org/play/#src=class%20C%20%7B%0D%0A%20%20%20%20state%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20...this.makeState()%0D%0A%20%20%20%20%7D%3B%0D%0A%20%20%20%20makeState%20%3D%20()%20%3D%3E%20(%7B%7D)%3B%0D%0A%0D%0A%20%20%20%20log()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this.state)%3B%0D%0A%20%20%20%20%7D%20%20%20%0D%0A%7D%0D%0A%0D%0A(new%20C).log()%3B%0D%0A>

**Related Issues:** N/A

**Comment by ajafff** [comment]
I recently landed a PR that fixes this issue. Can you please try `typescript@next`?

**Comment by RyanCavanaugh** [comment]
```ts
C:/throwaway/clipboard.ts:3:17 - error TS2729: Property 'makeState' is used before its initialization.

3         ...this.makeState()
                  ~~~~~~~~~

  C:/throwaway/clipboard.ts:5:5
    5     makeState = () => ({});
          ~~~~~~~~~
    'makeState' is declared here.
```

**Comment by RyanCavanaugh** [comment]
Thanks for the spot @ajafff
