### ISSUE TITLE
Type narrowing fails when type changes implicitly

### ISSUE THREAD

**Issue by Wayofthesin** [Microsoft/TypeScript#30011]
```ts
class SomeParser {
    private pos: number;
    private input: string;

    private get curChar(): string {
        return this.input[this.pos];
    }

    public constructor() {
        this.input = 'whatever';
    }

    public parse() {
        this.pos = 0;

        if (this.curChar !== 'w') {
            return;
        }

        this.pos++;
        if (this.curChar === 'h') { // This will actualy return true
            console.log('oops');
        }

        // ...
    }
}
```

**Expected behavior:**
`if( this.curChar === 'h')` should be valid comparison

**Actual behavior:**
 > This condition will always return 'false' since the types '"w"' and '"h"' have no overlap.

[**Playground Link**](https://www.typescriptlang.org/play/#src=class%20SomeParser%20%7B%0D%0A%20%20%20%20private%20pos%3A%20number%3B%0D%0A%20%20%20%20private%20input%3A%20string%3B%0D%0A%0D%0A%20%20%20%20private%20get%20curChar()%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.input%5Bthis.pos%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.input%20%3D%20'whatever'%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20parse()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.pos%20%3D%200%3B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20if%20(this.curChar%20!%3D%3D%20'w')%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20this.pos%2B%2B%3B%0D%0A%20%20%20%20%20%20%20%20if%20(this.curChar%20%3D%3D%3D%20'h')%20%7B%20%2F%2F%20This%20will%20actualy%20return%20true%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('oops')%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20...%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Workaround**
Use `any` casting in condition that narrows type. As per [playground](https://www.typescriptlang.org/play/#src=class%20SomeParser%20%7B%0D%0A%20%20%20%20private%20pos%3A%20number%3B%0D%0A%20%20%20%20private%20input%3A%20string%3B%0D%0A%0D%0A%20%20%20%20private%20get%20curChar()%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.input%5Bthis.pos%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.input%20%3D%20'whatever'%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20parse()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.pos%20%3D%200%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20if%20((%3Cany%3Ethis.curChar)%20!%3D%3D%20'w')%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20this.pos%2B%2B%3B%0D%0A%20%20%20%20%20%20%20%20if%20(this.curChar%20%3D%3D%3D%20'h')%20%7B%20%2F%2F%20This%20will%20actualy%20return%20true%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('oops')%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20...%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

Search Terms:
type guard getters
narrowing type getters
implicit type change

**Comment by yortus** [comment]
See #9998.

This is pretty much the same example as #12070 which was marked as a duplicate of #9998.

For a workaround, see https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-235963457.
