### ISSUE TITLE
DocumentOrShadowRoot.adoptedStyleSheets is missing in lib.dom.d.ts (constructible style sheets spec)

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/TypeScript#30022]
**TypeScript Version:**  3.4.0-dev.20190220

**Search Terms:**
CSS constructable stylesheets adoptedStyleSheets shadow root

Shipped in Chrome and polyfillable.

Spec: https://wicg.github.io/construct-stylesheets/
Blog post: https://developers.google.com/web/updates/2019/02/constructable-stylesheets

**Comment by RyanCavanaugh** [comment]
Draft/experimental APIs should be provided as out-of-band lib files, not in the shipping DOM. We'll revisit when this leaves experimental phase

**Comment by jogibear9988** [comment]
Also shipped in FireFox

**Comment by meyfa** [comment]
I'm pretty sure this is a standard thing by now, see the [Compatibility Table on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets#browser_compatibility) and the [Specification by CSSWG](https://drafts.csswg.org/cssom/#dom-documentorshadowroot-adoptedstylesheets). May we revisit?

**Comment by RyanCavanaugh** [comment]
Sure

**Comment by meyfa** [comment]
Seems to be fixed in TS 4.8! 🎉

**Comment by cedx** [comment]
Confirmed on my side: with TS 4.8.2, it's OK.

**Comment by jakebailey** [comment]
This was fixed in #49596.
