### ISSUE TITLE
lib.d.ts - XMLHttpRequest - send

### ISSUE THREAD

**Issue by janousek** [Microsoft/TypeScript#3002]
Current definition allows only string and Document argument. But it should allows BodyInit defined as:
typedef (Blob or BufferSource or FormData or URLSearchParams or USVString) BodyInit;

https://fetch.spec.whatwg.org/#bodyinit
https://xhr.spec.whatwg.org/#the-send()-method

**Comment by d3trax** [comment]
+1

**Comment by mhegazy** [comment]
This regressed since 1.4, we need an additional overload:
```ts
    send(data?: Document): void;
    send(data?: string): void;
    send(data?: any): void;
```

**Comment by mhegazy** [comment]
@janousek and @d3trax can you give this file a try: https://github.com/Microsoft/TypeScript/blob/master/bin/lib.d.ts

**Comment by MaceWindu** [comment]
Could you clarify why it's closed? I don't see overload with other BodyInit types and I receive error on latest master trying to pass FormData object to send
