### ISSUE TITLE
Unexpected behavior in for...in loop

### ISSUE THREAD

**Issue by adam987** [Microsoft/TypeScript#30023]
**TypeScript Version:**  3.4.0-dev.20190220

**Search Terms:**
for...in statement, generic parameter
**Code**

```ts
function trimValues<TValue extends { [K: string]: string }>(value: TValue) {
	for (const key in value) {
		if (value.hasOwnProperty(key)) value[key] = value[key].trim();
	}
}
```

**Expected behavior:**
Assignment should be allowed as it is in the examples below:

```ts
function trimValues<TValue extends { [K: string]: string }>(value: TValue) {
	for (const key in value) {
		if (value.hasOwnProperty(key)) value[key as string] = value[key].trim();
	}
}
```

```ts
function trimValues<TValue extends { [K: string]: string }>(value: TValue) {
	Object.keys(value).forEach((key) => {
		value[key] = value[key].trim();
	});
}
```

**Actual behavior:**
Error is thrown:
&nbsp;&nbsp;&nbsp;&nbsp;TS2322: Type 'string' is not assignable to type 'TValue[Extract<keyof TValue, string>]'.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=function%20trimValues%3CTValue%20extends%20%7B%20%5BK%3A%20string%5D%3A%20string%20%7D%3E(value%3A%20TValue)%20%7B%0D%0A%09for%20(const%20key%20in%20value)%20%7B%0D%0A%09%09if%20(value.hasOwnProperty(key))%20value%5Bkey%5D%20%3D%20value%5Bkey%5D.trim()%3B%0D%0A%09%7D%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is a correct error. Your signature says it allows invocations such as
```ts
trimValues<{ [k: string]: "Hello    " }>(someObj);
```
but the body violates the constraint that all properties have the value `"Hello    "`.

Probably the function should simply not be generic.

**Comment by adam987** [comment]
Yes, you're right. Thank you very much for the answer.
