### ISSUE TITLE
Unnecessary self module references in d.ts files

### ISSUE THREAD

**Issue by alexi2014** [microsoft/TypeScript#30021]
**TypeScript Version:**  3.3.3

self module reference typings

**Code**

```ts
// test1.ts, imports itself
import * as selfModule from './test1';
export class MyClass1 {
    theProp = 'abc';
}
export var v1: MyClass1;
export var v2 = new MyClass1();
```

**Expected behavior:**
The `selfModule` module reference is never used in code, so it should not appear in the type references in the generated d.ts. Specifically, in the `v2` variable type annotation.
```ts
// test1.d.ts
import * as selfModule from './test1';
export declare class MyClass1 {
    theProp: string;
}
export declare var v1: MyClass1;
export declare var v2: /*selfModule.*/MyClass1;
```

**Actual behavior:**
The type annotation for the `v2` variable includes `selfModule` specifier, despite of the fact that the original source code doesn't use it.
```ts
// test1.d.ts
import * as selfModule from './test1';
export declare class MyClass1 {
    theProp: string;
}
export declare var v1: MyClass1;
export declare var v2: selfModule.MyClass1;
```
The generated d.ts is formally correct, but adding unnecessary selfModule specifiers can have some practical negative consequences. For example, it screws up TypeDoc output.

**Repro sample**
Clone the following repo:
[https://github.com/alexi2014/ts-self-module-ref-typings](https://github.com/alexi2014/ts-self-module-ref-typings)
Run the command to compile test1.ts:
`npx typescript@3.3.3`
Check the output in test1.d.ts.

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This doesn't seem like a bug. As you say the output is correct, and importing yourself seems like a very edge case scenario. TypeDoc not being able handle the situation seems like a TypeDoc bug, not a reason for TypeScript to massage its own output.

**Comment by alexi2014** [comment]
Sorry, it was my mistake to call this output formally correct. It's incorrect. When consumer of such a d.ts looks at this `var v2: selfModule.MyClass1` via VSCode/VisualStudio Intellisense, one sees exactly this `selfModule.MyClass1`, and he has no idea what is this selfModule. And what VSCode shows is absolutely correct - it shows exactly what is written in d.ts.
I'm like an author of this line of code didn't use selfModule when I declared this var, so I expect that the consumer of my d.ts will see MyClass1 but not selfModule.MyClass1 (through VSCode, TypeDoc, and any other tool that will be screwed up by this code).

I's sorry but I didn't get the idea about "very edge case scenario". Self module references are permitted by ESM spec. What else parts of EcmaScript standard TypeScript doesn't honor and treats as very edge scenarios?

**Comment by RyanCavanaugh** [comment]
> It's incorrect.

I agree the hover on this isn't *ideal*, but the type system behavior is still correct.

> What else parts of EcmaScript standard TypeScript doesn't honor and treats as very edge scenarios?

Please don't over-read responses here and dig for bad faith. Something people do rarely is an edge case, nearly by definition. A module importing itself, as far as I know, is very rare. "doesn't honor" implies we're simply refusing to support it at all, which isn't the case - this code got parsed, checked, and emitted.

The workaround is to just annotate `v2`:
```
var v2: MyClass1 = new MyClass1();
```

**Comment by alexi2014** [comment]
Your workaround is not perfect. Writing type name twice in a distance of 7 characters between names is a bad coding style. It's a waste of developer's time, it bloats the code with the useless info, and the main problem is that it's very difficult to enforce this rule. For the record, my team maintains a library comprising 100+ npm modules, and each of them is affected by this problem. And I see also that TypeScript sources don't use unnecessary type annotations.

d.ts services at least two main purposes, both are important:
1. Provides type checking to the consumer's code
2. Provides Intellisense

The functionality that I'm complaining about breaks 2. From the consumer perspective it's not clear what is selfModule, it looks like a garbage. I didn't write this selfModule in my code, and I expect that it will not appear in d.ts. So the generated d.ts is **incorrect**.

> Something people do rarely is an edge case, nearly by definition.

I don't understand the "rare case" terminology being applied to a programming language and its compiler. Programming language is very fundamental part of the application, and it's semantics should be treated very formally and accurately. I understand that the rare case can explain why you have a bug here (i.e. why you didn't notice it before), but I can't understand how it can explain the refusal to fix it.

Let me explain what I mean on a small example. I investigate the possibility to use more advanced typing syntax in the library public API (keyof and related things). I quickly hit against the bug arising under some specific conditions. Before this discussion I thought that this is "just a bug", I'll report it and it will be eventually fixed. But now I'm not sure if it's the case. Maybe I stepped on this edge case area, and it'll not be fixed? How can I know whether this is a rare case or not? If your decision on this matter is made based on the "rear case" criteria, I just can't rely on the language specs when I take my decisions. So such a criteria looks unacceptable to me in the programming languages/compilers realm.
This is the gist of my question about "what else TypeScript doesn't honor". This is not a sarcasm or offence, this is the absolutely serious question. Because if I can't take a decision based on the specs, but instead I have to take into account considerations about expected usage frequency, which are naturally very subjective, then I believe that these rare cases should at least be documented. Otherwise, I have big doubts about if I can safely use this compiler, because it's syntax and semantics is informal.

**Comment by RyanCavanaugh** [comment]
Okay

**Comment by alexi2014** [comment]
Thanks!

**Comment by RyanCavanaugh** [comment]
I'm moving this to the Dormant milestone and closing it. If you're still affected by this and still need a fix, a PR would be gladly appreciated.
