### ISSUE TITLE
What's on version 3.3.3333?

### ISSUE THREAD

**Issue by dashmug** [Microsoft/TypeScript#30032]
_My apologies if this is not the right issue type. I just think that needs urgent attention as it could mean npm is compromised (which is not unheard of)._

I got this from my project.

![screen shot 2019-02-22 at 10 53 14 am](https://user-images.githubusercontent.com/1972844/53209906-20809900-3690-11e9-9a3e-2670e7f4022d.png)

Surprised, I went to the npm page for typescript and got this.

<img width="1189" alt="screen shot 2019-02-22 at 10 52 25 am" src="https://user-images.githubusercontent.com/1972844/53209956-57ef4580-3690-11e9-8ac2-87970a09dd23.png">

Is this expected?

**Comment by tkausl** [comment]
https://github.com/Microsoft/TypeScript/commit/2c02f13fb2f0a8f36e75d370f97da15678b7d252

**Comment by RyanCavanaugh** [comment]
We published `3.3.3333` because, unfortunately, npm rejected our PR to allow versions with an infinite number of repeating digits.

**Comment by dashmug** [comment]
Thank you for the response. It is expected then. I'll close this then.

**Comment by fictitious** [comment]
@RyanCavanaugh you'd have better chances with npm if you went with PR allowing such versions to be published on GitHub first

**Comment by RyanCavanaugh** [comment]
We had an offline conversation, but couldn't come to an agreement about whether `4.9999...` should be equivalent to `5.0` or not.

**Comment by jacobwgillespie** [comment]
Sorry if I'm just missing a joke here, but I'm probably not the only one still confused. 🙃 

Given that automated tools like Greenkeeper/Dependabot etc are now recommending upgrading from `3.3.3` to `3.3.3333`, is this new version legit?  We're trying to audit this from a security perspective, and this kind of release is unusual behavior for semver, etc.  

Besides this issue, I can't find anything relating to what this is or why it was published, and there are actual code changes in the diff between the the `3.3.3` and `3.3.3333` versions.

**Comment by DanielRosenwasser** [comment]
Sorry, humor aside, the new version is legit.

**Comment by jacobwgillespie** [comment]
Does that mean there will be no version `>=3.3.4 <3.3.3333`?

**Comment by RyanCavanaugh** [comment]
Correct. Any future version on the `3.3` line will be something like `3.3.4000`

**Comment by weswigham** [comment]
Or more likely `3.3.33333` given what we've already done tbh.

**Comment by Jessidhia** [comment]
Missed an opportunity to have `3.1.4159` 🤔

**Comment by qiaodaima** [comment]
🤔

**Comment by alexeagle** [comment]
I know you guys don't believe in semver but now you have to introduce floating point errors into it? I feel like this change is just 1/3 whimsical.

**Comment by zaoqi** [comment]
@qiaodaima
> thinking

讓我想起了Microsoft Windows版本號，雖然我現在不用Microsoft Windows，也不用wine，同時也在試圖刪除GNU和Linux和BSD（指我可能將實現一個運行於ARM,Intel芯片之上的整個內核作為一個我設計的編程語言解釋器所以不一定需要MMU的內核及操作系統）。

**Comment by chase-moskal** [comment]
@Jessidhia 

> Missed an opportunity to have `3.1.4159`

we can still have hope for `3.14.1592`

**Comment by welladamm** [comment]
This version number is in no way a joke I can appreciate because I literally spent a few minutes reading this issue and https://github.com/Microsoft/TypeScript/commit/2c02f13fb2f0a8f36e75d370f97da15678b7d252 trying to figure it out only to find out it's really meaningless.

Can we stop this from happening again, please? Thanks! @DanielRosenwasser

**Comment by TheReincarnator** [comment]
Not very professional, misleading, irritating. And not consistent in terms of semver. This is why people outside the JS/TS community are taking it not serious.

**Comment by jkoepcke** [comment]
I would really like to know how many developer hours have been wasted worldwide investigating about this version number... with great power comes great responsibility :)

**Comment by KissBalazs** [comment]
Nice to see that other professionals still use their highschool homework versioning systems as well.

**Comment by sysmat** [comment]
Probably in semantic versioning is legit, but it is strange

**Comment by forresthopkinsa** [comment]
So many complainers. I came across this issue because I saw the joke in my NPM logs and I wanted to know where to direct my appreciation. Made me chuckle. We don't need to be so serious all the time.

**Comment by parzh** [comment]
@forresthopkinsa Well, if their tools are now broken because of this change, you can't blame them for giving a shout about that.

On the other hand though, I couldn't think about anything that would seriously break after this kind of change.
