### ISSUE TITLE
Poor error messages for properties mis-handled as shorthand property declarations

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#30037]
```ts
declare function foo(option: { abcd: number }): void;

foo({
    abcd
})
```

**Today**

```
Cannot find name 'abcd'.
```

*Ideal**

```
This shorthand property declaration is invalid because a local declaration could not be found for 'abcd'. Either declare one or provide an initializer.
```

**Comment by Manish-Giri** [comment]
Hi! I'd like to give this a shot.

**Comment by DanielRosenwasser** [comment]
Go for it! Messages in `diagnosticMessages.json`, `gulp generate-diagnostics` creates a new entry in the `Diagnostics` map, and you can specialize the message in `checker.ts`.

**Comment by pbrahmbhatt3** [comment]
Hi,

Can I work on it too?

**Comment by DanielRosenwasser** [comment]
Check with @manish-giri first to see if he's still working on it. If not sure!

**Comment by pbrahmbhatt3** [comment]
@Manish-Giri  are you still working on it?

**Comment by Manish-Giri** [comment]
@pbrahmbhatt3 Hi, yes I'm working on it. Thanks.

**Comment by karthikkp** [comment]
@DanielRosenwasser This has been open for a while now. Shall I work on this?

**Comment by DanielRosenwasser** [comment]
Sure unless anyone else here is

**Comment by DanielRosenwasser** [comment]
Better message:

```
No value exists in scope for the shorthand property '{0}'. Either declare one or provide an initializer.
```

**Comment by karthikkp** [comment]
@DanielRosenwasser Out of curiosity, how many approvers are required to merge a PR?

**Comment by DanielRosenwasser** [comment]
Typically 2, but 1 may be fine if it's small enough.

Thanks for the PR!
