### ISSUE TITLE
Declaring a method should not add return type any

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#30044]
TypeScript should never generate code that adds `any`. When declaring a method, add `:void` instead.

**Comment by DanielRosenwasser** [comment]
I'm lacking context on this - do you mean in a quick fix?

**Comment by bpasero** [comment]
@DanielRosenwasser yeah. TypeScript should be about enforcing to use types and not ever suggest to use `any`.

**Comment by bpasero** [comment]
Maybe it could just return `:never` given it throws in the implementation.

**Comment by RyanCavanaugh** [comment]
@bpasero can you make the report a bit more actionable please? Right now it's just one sentence and is really unclear which feature area you're referring to

**Comment by bpasero** [comment]
@RyanCavanaugh I recorded a video:

![before](https://user-images.githubusercontent.com/900690/53258592-4c6e3f80-36cd-11e9-89dc-9ec5acb7b448.gif)

**Comment by RyanCavanaugh** [comment]
Ah, indeed. No return type annotation at all would be preferable.

**Comment by bpasero** [comment]
Thanks for the prompt fix!
