### ISSUE TITLE
"postMessage" declartion in 'lib.dom.d.ts' may have a little problem

### ISSUE THREAD

**Issue by asurance** [Microsoft/TypeScript#30042]
**TypeScript Version:**  3.3.3
* `postMessage` declartion in `lib.dom.d.ts` is
```typescript
declare function postMessage(message: any, targetOrigin: string, transfer?: Transferable[]): void;
```
Its second parameter `targetOrigin` is set as a must.
But I found samples on [MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Workers_API/Using_web_workers) about `postMessage` don't pass it.
There may lack a `?` after `targetOrigin`.
When I set `use strict` of comile options true and don't pass `targetOrigin`, compiler will warn me ,which makes me X﹏X.

**Comment by AviVahl** [comment]
Indeed optional according to the living "whatwg" specs.

https://html.spec.whatwg.org/multipage/web-messaging.html#posting-messages

"A target origin can be specified using the targetOrigin member of options. If not provided, it defaults to "/". This default restricts the message to same-origin targets only."

The fix probably needs to come from https://github.com/Microsoft/TSJS-lib-generator

**Comment by asurance** [comment]
OK,Thank you.

**Comment by AviVahl** [comment]
The relevant location, I think, is:
https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json#L474

or, if `master` changes and the line isn't relevant, open `overridingTypes.json` and search for `postMessage`.

**Comment by sandersn** [comment]
Actually, as @saschanaz points out, https://html.spec.whatwg.org/multipage/window-object.html#the-window-object:dom-window-postmessage shows that the *parameter* targetOrigin is required. When you provide an options object instead, the options object has an optional *property* named targetOrigin.

**Comment by AviVahl** [comment]
@saschanaz  @sandersn could you please check it out again? The docs you linked to say:
```
  void postMessage(any message, USVString targetOrigin, optional sequence<object> transfer = []);
  void postMessage(any message, optional WindowPostMessageOptions options);
```
which means `postMessage([anything])` is a valid call. Perhaps the real issue is the types missing the overloaded signature (that has the optional `options` object).

**Comment by sandersn** [comment]
@AviVahl I think @saschanaz fixed this in Microsoft/TSJS-lib-generator#679. Mind taking a look to see if that's the case?

**Comment by AviVahl** [comment]
@sandersn issue does seem to be fixed in @saschanaz's PR.
you guys are awesome.

**Comment by sandersn** [comment]
All thanks go to @saschanaz ! I am just a newbie in this space.
