### ISSUE TITLE
[spec] tsc accepts a TypeAliasDeclaration inside a AmbientExternalModuleDeclaration, the spec doesn't

### ISSUE THREAD

**Issue by sedwards2009** [Microsoft/TypeScript#3004]
According to the grammar in the spec a TypeAliasDeclaration not permitted to appear inside a AmbientExternalModuleDeclaration. 

For example, on DefinitelyTyped acl.d.ts contains:

    declare module "acl" {
      type strings = string|string[];
    }

This doesn't conform to the grammar, but tsc 1.5.0-beta is happy to accept it though.

TypeAliasDeclaration just needs to be added to the production of AmbientModuleElement in the spec as far as I can tell.

**Comment by ahejlsberg** [comment]
Fixed in #4033.
