### ISSUE TITLE
no type inference for generic function variable assignment ?

### ISSUE THREAD

**Issue by connectdotz** [Microsoft/TypeScript#30048]
**TypeScript Version:**  3.3.1

**Search Terms:** generic function assignment, generic type infer

**Code**

```ts
interface A<T> {
    foo: T;
}

const a: A<number> = { foo: 13 };

let getA: <T>() => A<T> = () => a; // <== error here
```

**Expected behavior:**
no compile error

**Actual behavior:**
compile error:
```
Type 'A<number>' is not assignable to type 'A<T>'.
  Type 'number' is not assignable to type 'T'.
```

**Playground Link:** [here](https://www.typescriptlang.org/play/index.html#src=interface%20A%3CT%3E%20%7B%0A%20%20%20%20foo%3A%20T%3B%0A%7D%0A%0Aconst%20a%3A%20A%3Cnumber%3E%20%3D%20%7B%20foo%3A%2013%20%7D%3B%0A%0Alet%20getA%3A%20%3CT%3E()%20%3D%3E%20A%3CT%3E%20%3D%20()%20%3D%3E%20a%3B%20%2F%2F%20%3C%3D%3D%20error%20here%0A)

**Related Issues:** 

#17574 
#26871

**Comment by jack-williams** [comment]
This is the right behaviour. The generic parameter `T` is rigid inside the definition of the function so it won’t pick up inferences. It’s better to think of `T` as a fixed, but unknown type; you can’t just assign a number to it.

If you want type inference you should leave type annotation off the declaration of the function.

**Comment by connectdotz** [comment]
the idea is to let `getA()` to take any function so long as it's compliant to the generic interface. If I leave out the signature of `getA()`, it basically became "fixed" after the first assignment: 
```ts
interface A<T> {
    foo: T;
}

const a: A<number> = { foo: 13 };

//let getA: <T>() => A<T> = () => a; 
let getA = () => a; 

const b: A<string> = { foo: "13" };
getA = () => b; // <== now error here
```
[playground](https://www.typescriptlang.org/play/index.html#src=interface%20A%3CT%3E%20%7B%0A%20%20%20%20foo%3A%20T%3B%0A%7D%0A%0Aconst%20a%3A%20A%3Cnumber%3E%20%3D%20%7B%20foo%3A%2013%20%7D%3B%0A%0A%2F%2Flet%20getA%3A%20%3CT%3E()%20%3D%3E%20A%3CT%3E%20%3D%20()%20%3D%3E%20a%3B%20%0Alet%20getA%20%3D%20()%20%3D%3E%20a%3B%20%0A%0Aconst%20b%3A%20A%3Cstring%3E%20%3D%20%7B%20foo%3A%20%2213%22%20%7D%3B%0A%0AgetA%20%3D%20()%20%3D%3E%20b%3B%20%2F%2F%20%3C%3D%3D%20now%20error%20here%0A)

this is a common pattern that a system assigned a default initial value/logic but later refined with actual implementation that are not known at compile time other than the generic interface they are conformed... maybe there are other ways to accomplish this?

**Comment by Nathan-Fenner** [comment]
You want an existential type. You've written that `getA` has a universal (generic) type.

The easiest way would be to make `getA: () => A<unknown>`, because that's all that it could be used as. If the caller doesn't know what type they'll get out, then `unknown` is the best you can do (in most circumstances- if the parameter is used contravariantly you'd want `never` instead, I guess).
