### ISSUE TITLE
No error for absent constructor

### ISSUE THREAD

**Issue by pltnkv** [Microsoft/TypeScript#30045]
**Code**
```ts
class ClassWithCorrectConstructor {
    constructor(message: string) {
        
    }
    hi() {
        
    }
}

class ClassWithWrongConstructor {
    constructor(message: number) {
        
    }
}

class ClassWithoutConstructor {
}

interface ConstructorType {
    new (message: string): any
}

// I want to check constructor type only 
function foo(cls: ConstructorType) {
}

foo(ClassWithCorrectConstructor) // Its ok
foo(ClassWithWrongConstructor) // Its ok. Error as expected
foo(ClassWithoutConstructor) // Its NOT ok. I expected error that custructor is absent, but TypeScript is silent

```

**Expected behavior:**
I expected error that constructor is absent, but TypeScript is silent

**Actual behavior:**
No error

**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=class%20ClassWithCorrectConstructor%20%7B%0D%0A%20%20%20%20constructor(message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20hi()%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ClassWithWrongConstructor%20%7B%0D%0A%20%20%20%20constructor(message%3A%20number)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ClassWithoutConstructor%20%7B%0D%0A%7D%0D%0A%0D%0Ainterface%20ConstructorType%20%7B%0D%0A%20%20%20%20new%20(message%3A%20string)%3A%20any%0D%0A%7D%0D%0A%0D%0Afunction%20foo(cls%3A%20ConstructorType)%20%7B%0D%0A%7D%0D%0A%0D%0Afoo(ClassWithCorrectConstructor)%20%2F%2F%20Its%20ok%0D%0Afoo(ClassWithWrongConstructor)%20%2F%2F%20Its%20ok.%20Error%20as%20expected%0D%0Afoo(ClassWithoutConstructor)%20%2F%2F%20Its%20NOT%20ok.%20I%20expected%20error%20that%20custructor%20is%20absent%2C%20but%20TypeScript%20is%20silent%0D%0A

**Comment by dragomirtitian** [comment]
This is the expected behavior. Function and by extension constructor assignability rules allow a function with fewer parameters to be assigned to a function reference that has more parameters ([docs](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#comparing-two-functions))

So for example 

```ts
let fn: (a: number)=> void  = () => console.log("Don't care about args");

fn(1) // param ignore but so what no runtime error
```

In your case the class `ClassWithoutConstructor ` still has a default constructor, so the constructor signature is `new ()=> ClassWithoutConstructor` which is assignable to the parameter type (`new (message: string): any`)

**Comment by DanielRosenwasser** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

**Comment by pltnkv** [comment]
Thanks for the explanation.
I understood that JavaScript allows that behavior which is simplify work with built in api like 'forEach'

But our TypeScript project codebase has about half million lines of code. 
And I dont remember using omitted args practice in our application code. (Excluding built in api usage)

It may be worth thinking about introducing additional annotations for catching such errors.
For example:
`forEach(callback: (element*: T, index*: number, array*: T[]))`

Where * means that you can omit this arg.

```
let items = [1, 2, 3];
items.forEach(arg => console.log(arg));
```

And enable this behavior with flag `--strictFunctionArgs`

**Comment by PushkinTyt** [comment]
so as not to break backward compatibility, you need to strengthen the typing by checking the arguments of the function.
`
type SomeConstructor = new (...args: any[]) => any
type ConstructorWithArgs<T extends SomeConstructor, Args> = (T extends new (...args: infer U) => any ? U extends Args ? T : never : never) & T

// I want to check constructor type only
function foo<T extends SomeConstructor>(cls: ConstructorWithArgs<T, [string]>) {
}

foo(ClassWithCorrectConstructor) // ok
foo(ClassWithWrongConstructor) // error
foo(ClassWithoutConstructor) // error
`
