### ISSUE TITLE
Documentation: Interfaces:Difference between the static and instance sides of classes

### ISSUE THREAD

**Issue by nbhaohao** [Microsoft/TypeScript#30040]
I am a beginner of TypeScript. I think this example in documentation is confused.
[interfaces](https://www.typescriptlang.org/docs/handbook/interfaces.html)
```
interface ClockConstructor {
    new (hour: number, minute: number): ClockInterface;
}
interface ClockInterface {
    tick();
}

function createClock(ctor: ClockConstructor, hour: number, minute: number): ClockInterface {
    return new ctor(hour, minute);
}

class DigitalClock implements ClockInterface {
    constructor(h: number, m: number) { }
    tick() {
        console.log("beep beep");
    }
}
class AnalogClock implements ClockInterface {
    /* notice me */
    /* AnalogClock constructor */ 
    constructor(h: number, m: number) { } 
    tick() {
        console.log("tick tock");
    }
}

let digital = createClock(DigitalClock, 12, 17);
let analog = createClock(AnalogClock, 7, 32);
```
documentation says **it checks that AnalogClock has the correct constructor signature.**
but when I have this change **(I remove the m param in the constructor),** the compiler is no error, means everything is ok, but I think the constructor is not match the ClockConstructor's new defined.
```
// ...
class AnalogClock implements ClockInterface {
    /* notice me */
    /* AnalogClock constructor */ 
    constructor(h: number) { } 
    tick() {
        console.log("tick tock");
    }
}
// ...
```
another example result also confused me.

when I want to check the Class if match the Interface defined constructor, If the Class do not defined the constructor, the compiler will say: everything is ok, no error.
```
interface MyInterface {
  new (name: string);
}

class A {
  constructor(name: number) {}
}

class B {
  constructor(name: string) {}
}

class C {}

function test(fn: MyInterface) {}

test(A); /* error TS2345: Argument of type 'typeof A' is not assignable to parameter of type 'MyInterface'.   Types of parameters 'name' and 'name' are incompatible.     Type 'string' is not assignable to type 'number'.
*/

test(B); // good,

test(C); // good too, I do't understand this one

```
I really wish that anyone can help me to understand this result. Thanks.

I am not sure this Issue can be a  Question Tag, If It's wrong, I am sorry.

**Comment by DanielRosenwasser** [comment]
See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

**Comment by nbhaohao** [comment]
Thank you very much for the reply.
The FAQ example is very convictive, I got a lot.
I should not ignore the FAQ and should read it.

**Comment by DanielRosenwasser** [comment]
It's kinda hard to read the whole thing :)
