### ISSUE TITLE
Cannot find module: a.module.css when tsconfig "include" is specific file rather than full directory

### ISSUE THREAD

**Issue by yang** [Microsoft/TypeScript#30055]
**TypeScript Version:**  3.4.0-dev.20190222

**Search Terms:** import cannot find module declare module include tsconfig 

**Code**

```ts
import styles from "./a.module.css";
console.log(styles.foo);
```

Link to full repo for repro: https://github.com/yang/sandbox-ts-imports

**Expected behavior:**
No Typescript errors.

**Actual behavior:**
```
Cannot find module 'a.module.css'.ts(2307)
```

But when I change tsconfig "include" from "src/index.tsx" to "src", the error goes away.

This seems inconsistent with the behavior for normal source files, which can be imported fine even if not in the "include" set.

**Comment by RyanCavanaugh** [comment]
How is tsc supposed to know that `global.d.ts` defines that module? By writing an `include` that doesn't include it, you've prevented TS from finding the definition file. TypeScript can't form a reverse mapping from module name to `.d.ts` file for `.d.ts` files which are not included in the compilation in the first place.

**Comment by yang** [comment]
Makes sense - the problem wasn't that the .css was missing, but that the .d.ts was missing (I mistakenly assumed ambient declarations were always automatically included).  I can confirm that adding global.d.ts to the `include` in tsconfig fixes the error.  Thanks.
