### ISSUE TITLE
Generics don't work with this in classes

### ISSUE THREAD

**Issue by nickmessing** [Microsoft/TypeScript#30069]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
generics, class, this

**Code**

```ts
class Cmp {
  $events: {
    click: (arg: string) => boolean
  }

  constructor (fn: (arg: string) => boolean) {
    this.$events = {
      click: fn
    }
  }

  created() {
    const a: ReturnType<this['$events']['click']> = true
    console.log(a)
  }
}

const a = new Cmp(arg => arg === 'hello')
a.created()
```

**Expected behavior:**
Should compile successfully

**Actual behavior:**
```
error TS2322: Type 'true' is not assignable to type 'ReturnType<this["$events"]["click"]>'.
```

[**Playground Link**](https://www.typescriptlang.org/play/#src=class%20Cmp%20%7B%0D%0A%20%20%24events%3A%20%7B%0D%0A%20%20%20%20click%3A%20(arg%3A%20string)%20%3D%3E%20boolean%0D%0A%20%20%7D%0D%0A%0D%0A%20%20constructor%20(fn%3A%20(arg%3A%20string)%20%3D%3E%20boolean)%20%7B%0D%0A%20%20%20%20this.%24events%20%3D%20%7B%0D%0A%20%20%20%20%20%20click%3A%20fn%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%0D%0A%20%20created()%20%7B%0D%0A%20%20%20%20const%20a%3A%20ReturnType%3Cthis%5B'%24events'%5D%5B'click'%5D%3E%20%3D%20true%0D%0A%20%20%20%20console.log(a)%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20Cmp(arg%20%3D%3E%20arg%20%3D%3D%3D%20'hello')%0D%0Aa.created()%0D%0A)

**Comment by nickmessing** [comment]
If I don't use Generics - it works fine.
```ts
class Cmp {
  $events: {
    click: (arg: string) => boolean
  }

  constructor (fn: (arg: string) => boolean) {
    this.$events = {
      click: fn
    }
  }

  created() {
    const a: this['$events']['click'] = arg => arg === 'hello'
    console.log(a)
  }
}

const a = new Cmp(arg => arg === 'hello')
a.created()
```

**Comment by NN---** [comment]
You can workaround it simply by specifying class name instead of 'this':

```
const a: ReturnType<Cmp['$events']['click']> = true
```

Your sample can be simplified:

```ts
type R<T> = T extends (...args: any[]) => infer R ? R : any;

class Cmp {
  click: (arg: string) => boolean;

  a: R<this['click']> = true;
  b: R<Cmp['click']> = true;
}
```

Maybe the problem here is with polymorphic this.

**Comment by nickmessing** [comment]
@NN---, that won't help if you use `this` in a parent class that refers to a property from the child class.

**Comment by RyanCavanaugh** [comment]
When you have a `this` *type* involved (not a `this` *value*, as in the later comment), the compiler correctly accounts for the fact that you might be violated a derived class contract to return a more specific value -- a class derived from `Cmp` might legally define `$events: { click: (arg: string) => false; };`, which `a` would be breaking.

The "fix" if you don't care about that (which would be totally reasonable!) would be to just write
```ts
const a: ReturnType<Cmp['$events']['click']> = true
```
instead of
```ts
const a: ReturnType<this['$events']['click']> = true
```
