### ISSUE TITLE
Show Unused Promises

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/TypeScript#30061]
Customer request from https://dev.to/mokkapps/why-i-switched-from-visual-studio-code-to-jetbrains-webstorm-939

## Suggestion

Not waiting for promises can be really tricky if you expect the subsequent code to run only after the promise has been resolved. WebStorm shows if there are unresolved promises (in this case for a TypeScript application):

## Use Cases

![image](https://user-images.githubusercontent.com/173559/53279164-fe543e80-36c2-11e9-9fbf-e5861faa7fe5.png)

VS Code has currently no possibility to show this information:

![image](https://user-images.githubusercontent.com/173559/53279170-07dda680-36c3-11e9-9f12-ea56e46513ed.png)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by NN---** [comment]
TSLint rule: https://palantir.github.io/tslint/rules/no-floating-promises/

**Comment by felixfbecker** [comment]
Also note that there are many situations where it is okay to not handle Promises because you know they cannot reject, or if they rejected, there isn't anything you could do other than logging. So I would rather have this in a TSLint rule, where it's easy to configure and ignore as needed.

**Comment by RyanCavanaugh** [comment]
Duplicate #13376
