### ISSUE TITLE
Intersection Types/function (something like `assert`): TS7030 TS2345

### ISSUE THREAD

**Issue by zaoqi** [Microsoft/TypeScript#30064]
**TypeScript Version:**  3.3.3333

**Search Terms:**

**Code**

```ts
    const assert: ((x: false) => nerver) & ((x: true) => void) = (x: boolean) => {
        if (x === false) {
            return error()
        }
    }
```

**Expected behavior:**

**Actual behavior:**
```
lang.ts:1257:66 - error TS7030: Not all code paths return a value.

1257     const assert: ((x: false) => nerver) & ((x: true) => void) = (x: boolean) => {

lang.ts:1345:20 - error TS2345: Argument of type 'boolean' is not assignable to parameter of type 'true'.

1345             assert(!eof())
```
**Playground Link:** 

**Related Issues:**

**Comment by yortus** [comment]
This CFA-based approach to handling `assert` functions is covered in #8655. E.g. see https://github.com/Microsoft/TypeScript/issues/8655#issuecomment-296909203.

That was closed as a design limitation. There is some reasoning and a future possible solution described in https://github.com/Microsoft/TypeScript/issues/8655#issuecomment-412685082
