### ISSUE TITLE
error: 'static is a reserved identifier' when running in strict mode

### ISSUE THREAD

**Issue by frankwallis** [Microsoft/TypeScript#3006]
I am running the latest [code](https://github.com/Arnavion/typescript-github) compiled from master, but when trying to compile in the browser under strict mode it is throwing this error.

The problem is caused by a function parameter in [emitter.ts](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L3484) called 'static' which needs to be renamed to something else. 

```
function getInitializedProperties(node: ClassLikeDeclaration, static: boolean) {
                let properties: PropertyDeclaration[] = [];
                for (let member of node.members) {
                    if (member.kind === SyntaxKind.PropertyDeclaration && static === ((member.flags & NodeFlags.Static) !== 0) && (<PropertyDeclaration>member).initializer) {
                        properties.push(<PropertyDeclaration>member);
                    }
                }

                return properties;
            }
```

**Comment by mhegazy** [comment]
thanks @frankwallis
