### ISSUE TITLE
=>nerver /error TS7030: Not all code paths return a value.

### ISSUE THREAD

**Issue by zaoqi** [Microsoft/TypeScript#30065]
**TypeScript Version:**   3.3.3333

**Search Terms:**

**Code**

**Actual behavior:**

```ts
// make_nerver : () => nerver
make_nerver() // Not all code paths return a value.
return make_nerver() // OK
```

**Expected behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by AnyhowStep** [comment]
Kind of vague but I assume your function is supposed to return *something* but you made it return `never` and it compiled.

But you feel like `never` is not of type *something*, so it should get an error?

**Comment by DanielRosenwasser** [comment]
Control flow analysis doesn't look at every call in the program because it would be prohibitively expensive. See a similar issue at @8655.

**Comment by DanielRosenwasser** [comment]
also in the future please post a **full reproducible example of some code that works.**
