### ISSUE TITLE
Proposal: emit files without `.ts` extension to get custom file extension

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#30076]
## Search Terms

- file extension
- .mjs
- .esm

## Suggestion

It is very useful if you can customize the output extension.
But mapping extension is boring and painful.
Maybe there is another way to make this easier.
If we don't map the extension, we just erase the `.ts` or `.tsx` extension to achieve it.
A compilerOptions is needed to prevent break existing TypeScript code.

## Use Cases

- Output the `.mjs` file for Node Module,
- Output `.es` or other file extensions without additional steps. (e.g. useful for tsc watching mode)

## Examples

input:

```ts
// src/lib.js.ts
export const result = 42;
```

```ts
// src/index.js.ts
import { result } from "./lib.js";

console.log(result);
```

output:

```ts
// build/lib.js
export const result = 42;
```

```ts
// build/index.js
import { result } from "./lib.js";

console.log(result);
```

---

input:

```ts
// src/lib.mjs.ts
export const result = 42;
```

```ts
// src/index.mjs.ts
import { result } from "./lib.mjs";

console.log(result);
```

output:

```ts
// build/lib.mjs
export const result = 42;
```

```ts
// build/index.mjs
import { result } from "./lib.mjs";

console.log(result);
```

---

input:

```ts
// src/lib.myext.ts
export const result = 42;
```

```ts
// src/index.myext.ts
import { result } from "./lib.myext";

console.log(result);
```

output:

```ts
// build/lib.myext
export const result = 42;
```

```ts
// build/index.myext
import { result } from "./lib.myext";

console.log(result);
```

## Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by magic-akari** [comment]
Related issue: 
- https://github.com/Microsoft/TypeScript/issues/27957
- https://github.com/Microsoft/TypeScript/issues/18442

**Comment by xialvjun** [comment]
just add a compiler option `--outSuffix` so `tsc --module es6 --outSuffix mjs`...
https://github.com/microsoft/TypeScript/issues/32373

**Comment by viT-1** [comment]
Problem is wider, I need in `--outSuffix /index.js` =)
