### ISSUE TITLE
AutoComplete for string literal types fails when the type union contains a generic <string>

### ISSUE THREAD

**Issue by bd82** [Microsoft/TypeScript#30085]
## Description:
When a string literal type union also includes the general string type.
content assists stops working in VSCode (and the playground).

### Code to reproduce the issue:
```typescript

  function define(deps: depItemOrString[], Function) {}
  type depItemOrString = string | "ima/aba/bamba" | "winter/is/coming" | "there/can/be/only/one";

  // Intelli-sense for the string literals does **not** work here.
  define(["bamba"], () => {})

  function define2(deps: depItem[], Function) {}
  type depItem =  "ima/aba/bamba" | "winter/is/coming" | "there/can/be/only/one";

  // Everything works perfectly when the literal type union does not include a "general" string type.
  define2(["ima/aba/bamba"], () => {})
```

[Try this code in the Playground](https://www.typescriptlang.org/play/#src=%0D%0A%20%20function%20define(deps%3A%20depItemOrString%5B%5D%2C%20Function)%20%7B%7D%0D%0A%20%20type%20depItemOrString%20%3D%20string%20%7C%20%22ima%2Faba%2Fbamba%22%20%7C%20%22winter%2Fis%2Fcoming%22%20%7C%20%22there%2Fcan%2Fbe%2Fonly%2Fone%22%3B%0D%0A%0D%0A%20%20%2F%2F%20Intelli-sense%20for%20the%20string%20literals%20does%20**not**%20work%20here.%0D%0A%20%20define(%5B%22bamba%22%5D%2C%20()%20%3D%3E%20%7B%7D)%0D%0A%0D%0A%20%20function%20define2(deps%3A%20depItem%5B%5D%2C%20Function)%20%7B%7D%0D%0A%20%20type%20depItem%20%3D%20%20%22ima%2Faba%2Fbamba%22%20%7C%20%22winter%2Fis%2Fcoming%22%20%7C%20%22there%2Fcan%2Fbe%2Fonly%2Fone%22%3B%0D%0A%0D%0A%20%20%2F%2F%20Everything%20works%20perfectly%20when%20the%20literal%20type%20union%20does%20not%20include%20a%20%22general%22%20string%20type.%0D%0A%20%20define2(%5B%22ima%2Faba%2Fbamba%22%5D%2C%20()%20%3D%3E%20%7B%7D))

### Expected Behavior 
I would expect that in **both** function (define and define2) auto-complete suggestion
would be provided based on the literal string union type.

### Actual Behavior 
The auto-complete suggestions are only provided for a "pure" string literal type.
Meaning one that does not include a "generic" string as well:
```typescript
type pureLiteralStringType = "a" | "b" | "c"
type impureLiteralStringType = string | "a" | "b" | "c"
```

**Comment by jack-williams** [comment]
Duplicate of #29729

**Comment by bd82** [comment]
Oh sorry I will close this.
