### ISSUE TITLE
Inferred return types checked against extended (as opposed to specific) declaration's return type.

### ISSUE THREAD

**Issue by Hashbrown777** [Microsoft/TypeScript#30096]
**TypeScript Version:**  typescript@3.4.0-dev.20190223

**Search Terms:** return types accept extra properties

**Code**

```ts
interface IOnlyBob {bob :string};

//this errors as we expect
//const _errors :IOnlyBob = {bob:'hi', steve:'there'};

//this works fine but should error
let _returnsBob :() => IOnlyBob;
_returnsBob = () => ({bob:'hi', steve:'there'});

//I'd expect this to be the way to do the above, if that's what someone actually wanted
let _returnsNotJustBob :<T extends IOnlyBob>() => T;
_returnsNotJustBob = () => ({bob:'hi', steve:'there'} as any); //have to do any, see https://github.com/Microsoft/TypeScript/issues/28154
```

**Expected behavior:**
Line 8 should fail.
```
Type '{ bob: string; steve: string; }' is not assignable to type 'IOnlyBob'.
  Object literal may only specify known properties, and 'steve' does not exist in type 'IOnlyBob'.
```

**Actual behavior:**
Works fine.

**Playground Link:** [here](https://www.typescriptlang.org/play/#src=interface%20IOnlyBob%20%7Bbob%20%3Astring%7D%3B%0A%0A%2F%2Fthis%20errors%20as%20we%20expect%0A%2F%2Fconst%20_errors%20%3AIOnlyBob%20%3D%20%7Bbob%3A'hi'%2C%20steve%3A'there'%7D%3B%0A%0A%2F%2Fthis%20works%20fine%20but%20should%20error%0Alet%20_returnsBob%20%3A()%20%3D%3E%20IOnlyBob%3B%0A_returnsBob%20%3D%20()%20%3D%3E%20(%7Bbob%3A'hi'%2C%20steve%3A'there'%7D)%3B%0A%0A%2F%2FI'd%20expect%20this%20to%20be%20the%20way%20to%20do%20the%20above%2C%20if%20that's%20what%20someone%20actually%20wanted%0Alet%20_returnsNotJustBob%20%3A%3CT%20extends%20IOnlyBob%3E()%20%3D%3E%20T%3B%0A_returnsNotJustBob%20%3D%20()%20%3D%3E%20(%7Bbob%3A'hi'%2C%20steve%3A'there'%7D%20as%20any)%3B%20%2F%2Fhave%20to%20do%20any%2C%20see%20https%3A%2F%2Fgithub.com%2FMicrosoft%2FTypeScript%2Fissues%2F28154%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate / root-cause #241

**Comment by Hashbrown777** [comment]
Oh ta! "Widening", I guess if I knew the lingo I'd've found that.
Thanks, I'll watch that space.
