### ISSUE TITLE
Control flow analysis fails to account for possible assignments to captured variables in closures.

### ISSUE THREAD

**Issue by AndrewGlynn** [Microsoft/TypeScript#30097]
**TypeScript Version:**   3.4.0-dev.20190223

**Search Terms:**
union narrow control flow closure

**Code**

```ts
// with strictNullChecks enabled

let x: number | null = null;

const f = () => { x = 3; };

f();
// at this point x is a number (3), but typescript thinks it has type null (NOT number | null)

Math.abs(x as number); // type error
````
**Expected behavior:**

Compilation succeeds. Inferred type of `x` at the line marked "type error" should be `number | null`. (In a perfect world the inferred type would actually be `number`, but I'm not expecting that.)

**Actual behavior:**

Compiler emits the following error message:

`error TS2352: Conversion of type 'null' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.`

Hovering over the `x` in the line with the type error shows the inferred type as `x: null`.

Note that, unlike (most of?) the related issues below, the problem here is not that the inferred type is less specific than expected, but rather that it is _more_ specific, and specifically wrong. Because the captured variable `x` is assigned a number in the closure, the compiler should assume the assignment _might_ happen at any time, and should not narrow the type `number|null` to `null`.

**Playground Link:** 
(Make sure 'strictNullChecks' is checked in Options.)

https://www.typescriptlang.org/play/index.html#src=%2F%2F%20with%20strictNullChecks%20enabled%0D%0A%0D%0Alet%20x%3A%20number%20%7C%20null%20%3D%20null%3B%0D%0A%0D%0Aconst%20f%20%3D%20()%20%3D%3E%20%7B%20x%20%3D%203%3B%20%7D%3B%0D%0A%0D%0Af()%3B%0D%0A%2F%2F%20at%20this%20point%20x%20is%20a%20number%20(3)%2C%20but%20typescript%20thinks%20it%20has%20type%20null%20(NOT%20number%20%7C%20null)%0D%0A%0D%0AMath.abs(x%20as%20number)%3B%20%2F%2F%20type%20error%0D%0A

**Related Issues:** 

#9263, #7719, #8541, #8552, #9491 (and others)

**Comment by jack-williams** [comment]
This is the canonical thread for CFA: #9998
