### ISSUE TITLE
Type compatibility works incorrectly with strictFunctionTypes flag and variables declared using typeof keyword

### ISSUE THREAD

**Issue by roman-g** [Microsoft/TypeScript#30098]
**TypeScript Version:**  3.3

**Search Terms:**
strictFunctionTypes typeof

**Code**

```ts
// with strictFunctionTypes enabled

class Class {
    public static method1(e: string | number): void { }
    public static method2 = (e: string | number) : void => { };
}
    
function test() {
    let f1 : typeof Class.method1;
    let f2 : typeof Class.method2;
    let f = (x: string) => { };

    f1 = f; //Ok
    f2 = f; //Fail
}
```

**Expected behavior:**
Both assignments shouldn't be allowed in the function `test`, because `strictFunctionTypes` flag is enabled

**Actual behavior:**
The first asignment is allowed

**Playground Link:** 
The playground requires manual enabling `strictFunctionTypes` flag
https://www.typescriptlang.org/play/index.html#src=class%20Class%20%7B%0D%0A%20%20%20%20public%20static%20method1(e%3A%20string%20%7C%20number)%3A%20void%20%7B%20%7D%0D%0A%20%20%20%20public%20static%20method2%20%3D%20(e%3A%20string%20%7C%20number)%20%3A%20void%20%3D>%20%7B%20%7D%3B%0D%0A%7D%0D%0A%20%20%20%20%0D%0Afunction%20test()%20%7B%0D%0A%20%20%20%20let%20f1%20%3A%20typeof%20Class.method1%3B%0D%0A%20%20%20%20let%20f2%20%3A%20typeof%20Class.method2%3B%0D%0A%20%20%20%20let%20f%20%3D%20(x%3A%20string)%20%3D>%20%7B%20%7D%3B%0D%0A%0D%0A%20%20%20%20f1%20%3D%20f%3B%20%2F%2FOk%0D%0A%20%20%20%20f2%20%3D%20f%3B%20%2F%2FFail%0D%0A%7D

**Related Issues:** 
Not found

**Comment by dragomirtitian** [comment]
This is the expected behavior, `strictFunctionTypes` does not apply to function signatures that originate in class methods. From [pr](https://github.com/Microsoft/TypeScript/pull/18654):

>  The stricter checking applies to all function types, except those originating in method or construcor declarations. 


This is even used as a hack to allow bivariant signatures in some cases ([ex](https://stackoverflow.com/questions/52667959/what-is-the-purpose-of-bivariancehack-in-typescript-types/52668133#52668133))

**Comment by roman-g** [comment]
Wow, that's tricky. Could you please explain what's the reason to introduce different behaviors for handling methods and other functions? If possible, provide a simple example, please.

**Comment by dragomirtitian** [comment]
@roman-g  The rationale is spelled out in the linked PR in the next sentence:

> The stricter checking applies to all function types, except those originating in method or constructor declarations. **Methods are excluded specifically to ensure generic classes and interfaces (such as Array<T>) continue to mostly relate covariantly. The impact of strictly checking methods would be a much bigger breaking change as a large number of generic types would become invariant (even so, we may continue to explore this stricter mode).**
