### ISSUE TITLE
`gulp local` doesn't generate some language service files

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#30090]
These files used to be generated by `jake local` but are missing from the output when `gulp local` is run.

This currently breaks two things:
1. We package and ship these in the sdk + nuget package, and with the switchover to `gulp` in the sync script they are not getting updated anymore
2. Our dev workflow of running `tsserver.js` from the local `built/local` doesn't work so well anymore

Outputs missing:
`typingsInstaller.js`
`watchGuard.js`
`cancellationToken.js`
`typesMap.json` (this one's disappearance seems to predate the gulp switchover, though it's still needed)

**Comment by minestarks** [comment]
FYI @weswigham @RyanCavanaugh

**Comment by weswigham** [comment]
PR is out. Although I do still think that running `LKG` and copying the `lib` folder is more similar to our own nightly publish and likely more correct, though. As-is, these files being copied from the `local` folder are missing copyright headers, for example. Then again, `typesMap` isn't copied into `lib` by `LKG` for whatever reason so... eh?

**Comment by minestarks** [comment]
Thanks! No objections to using `LKG` (as long as we're actually running `LKG` each time, and not just picking up `lib` from the last time it was run manually). Including everything `local` is still nice for the run-tsserver.js-from-local-build scenario.

Weird, `typesMap.json` is even in the npm package. Have we just been picking up the copy that happened to be sitting in `lib`? (File hasn't been actually been touched in a long time, so I guess this was harmless)

**Comment by weswigham** [comment]
Yeah, I think we must be. TBH, I think the first step of `prepareLKG` should be deleting the lib folder so files _can't_ stick around like that...
