### ISSUE TITLE
.git directory is packaged into release package

### ISSUE THREAD

**Issue by link89** [Microsoft/TypeScript#30100]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
git clean package

**Code**
```sh
git init
npm install typescript
git add package-lock.json
git commit -m "init"
git clean -xdf
```
**Expected behavior:**
clean node_module folder

**Actual behavior:**
fatal: Not a git repository: /home/daniel/shared/TypeScript/.git/worktrees/TypeScript3
The git version is 1.8, which is the default version install by centos 7. 
I think .git file should not be included in release package
 
**Playground Link:** 

**Related Issues:**

**Comment by AlCalzone** [comment]
Is this a version that includes https://github.com/Microsoft/TypeScript/pull/30078 ?

**Comment by RyanCavanaugh** [comment]
See #30078 / #30077
