### ISSUE TITLE
Issue with type inference

### ISSUE THREAD

**Issue by mcjazzyfunky** [Microsoft/TypeScript#30105]
The following demo shows an issue with TypeScript's type inference (tested with typescript@3.3.3333 and typescript@3.4.0-dev.20190226).
I do not know whether this should really be considered a bug but at least the same is working fine with Flow.
Pardon me, in case this has already been issued somewhere else in the past.

The following is working properly with Flow => types of `store` and `self` are properly inferred as `{ count: number, increment(): void }`.
Check [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqJgE4CmAhtqQMraxkA8AKgHwAUu6u2AXKGwGdS0SHyYBKUAF4WoCWNABvRKCIEB2UGV5zp-NooC+fcugCe4seJWgQocgIGoAtqVADYrogAtTAczcAE1IqHHpQOD9cTFBvUjIbO0EAa1wABzTSQNA6UGTSUjTQYOdYd1xnNOhSa1UAeQAjACtSHAA6BwFcP3Q2bQAaUE5uPpDxWq0Q1GJCbURDZEx1TQ16NykiMkoaOjJBYUhpWWVVbWnCE9VVJYwdAAZ+5CvVThJSV3RsNklL5-cDto3T4AamBNiuC1UC0M1kQS3QHmqbUigl2pEBsFukjsaWInGwAlAmM0d0QqzIbVeZA+X2s8MR6JR5PRQOw2LAuPxhOJoAAjIggA) to see that the Flow code is fine.

```javascript
// @flow

function createStore<T>(init: (self: T) => T): T {
  const ret: T = (({}: any): T)
  // assume some change detector logic here
  // (skipped to keep demo simple)
  Object.assign(ret, init(ret))
  return ret
}

const store = createStore(self => {
  return {
     count: 0,

     increment() {
       self.count++
     }
  }
})

console.log(store.count) // prints out 0
store.increment()
console.log(store.count) // prints out 1
```

Unfortunatelly the same is NOT working with TypeScript => types of `store` and `self` are inferred to `{}` instead of `{ count: number, increment(): void }`.
TypeScript live demo: https://stackblitz.com/edit/typescript-sjuimf

```typescript
function createStore<T>(init: (self: T) => T): T {
  const ret: T = {} as T
  // assume some change detector logic here
  // (skipped to keep demo simple)
  Object.assign(ret, init(ret))
  return ret
}

const store = createStore(self => {
  return {
     count: 0,

     increment() {
       self.count++ // <------ type error!!!
     }
  }
}) // return type is {} instead of { count: number, increment(): void }

// Type errors in each of the following three lines!!!
console.log(store.count) // prints out 0
store.increment()
console.log(store.count) // prints out 1
```

**Comment by mcjazzyfunky** [comment]
FYI: The following modification works fine in TypeScript
TS live demo: https://stackblitz.com/edit/typescript-xyfjcg

```typescript
function createStore<T>(init: () => T): T {
  const ret: T = {} as T
  // assume some change detector logic here
  // (skipped to keep demo simple)
  Object.assign(ret, init())
  return ret
}

const store = createStore(() => {
  return {
     count: 0,

     increment() {
       store.count++
     }
  }
})

console.log(store.count) // prints out 0
store.increment()
console.log(store.count) // prints out 1})
```

**Comment by RyanCavanaugh** [comment]
TypeScript's inference algorithm is not as good at dealing with argument-return value circularity.

**Comment by mcjazzyfunky** [comment]
@RyanCavanaugh Everything has its limitations - so if this is an already known minor limitation of TypeScript and there are no plans to enhance this in near future, then that's okay for me, of course. In that case, feel free to close this issue (in my particular use case I have already implemented an alternative that works fine with TypeScript's type inference as-is).
