### ISSUE TITLE
Using allowJS and checkJS should allow type aliases

### ISSUE THREAD

**Issue by avaly** [Microsoft/TypeScript#30115]
**TypeScript Version:**  3.4.0-dev.20190226

**Search Terms:** type aliases allowJS checkJS

**Code**

```ts
type Foo = { foo: number };

const test = { foo: 123 } as Foo;

test.foo;
```

Sample files: https://gist.github.com/avaly/0b700b2093b59a2a3f8223e0555e4248

**Expected behavior:**

When using both `--allowJS` and `--checkJS` options, there is an expectation that we can use the full TypeScript language in `.js` files.

**Actual behavior:**

```
$ tsc --allowJs --checkJs --noEmit *.{js,ts}
type-assertion.js:1:6 - error TS8008: 'type aliases' can only be used in a .ts file.

1 type Bar = { bar: number };
       ~~~

type-assertion.js:3:30 - error TS8016: 'type assertion expressions' can only be used in a .ts file.

3 const test = { bar: 123 } as Bar;
                               ~~~


Found 2 errors.
```

The errors are only reported in the `.js` file.

**Comment by RyanCavanaugh** [comment]
> When using both `--allowJS` and `--checkJS` options, there is an expectation that we can use the full TypeScript language in `.js` files.

These files won't run in any JS runtime and thus aren't JS files.

**Comment by avaly** [comment]
Using Babel and [`@babel/preset-typescript`](https://babeljs.io/docs/en/babel-preset-typescript), it's possible to have types in `.js` files.

**Comment by RyanCavanaugh** [comment]
Not sure what to say - Babel's wrong to accept non-JS syntax in JS files. ¯\\\_(ツ)\_/¯

**Comment by RyanCavanaugh** [comment]
Duplicate #12199
