### ISSUE TITLE
Type inference of object property not propagated to object

### ISSUE THREAD

**Issue by cdimitroulas** [Microsoft/TypeScript#30126]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
object, inference, property, inference, switch, case, propagate

**Code**

```ts
enum E {
  A = 'a',
  B = 'b'
}

const createSpecificThing = (input: { otherStuff: string } & { enumValue: E }): void => {
  switch (input.enumValue) {
    case E.A:
      input.enumValue // inferred as E.A correctly
      specificThingA(input) // Type E is not assignable to E.A
      break
    case E.B:
      input.enumValue // inferred as E.B correctly
      specificThingB(input) // Type E is not assignable to E.B
      break
    default:
      input.enumValue // inferred correctly as never
  }
};

const specificThingA = (input: { otherStuff: string } & { enumValue: E.A }): void => {
  // do stuff
}

const specificThingB = (input: { otherStuff: string } & { enumValue: E.B }): void => {
  // do stuff
}
```

**Expected behavior:**
Expect that an object property whose type is inferred to correctly update the overall type of the object in which it exists.

**Actual behavior:**
The object property has the correct type however, the overall object type is unchanged.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=enum%20E%20%7B%0D%0A%20%20A%20%3D%20'a'%2C%0D%0A%20%20B%20%3D%20'b'%0D%0A%7D%0D%0A%0D%0Aconst%20createSpecificThing%20%3D%20(input%3A%20%7B%20otherStuff%3A%20string%20%7D%20%26%20%7B%20enumValue%3A%20E%20%7D)%3A%20void%20%3D%3E%20%7B%0D%0A%20%20switch%20(input.enumValue)%20%7B%0D%0A%20%20%20%20case%20E.A%3A%0D%0A%20%20%20%20%20%20input.enumValue%20%2F%2F%20inferred%20as%20E.A%20correctly%0D%0A%20%20%20%20%20%20specificThingA(input)%20%2F%2F%20Type%20E%20is%20not%20assignable%20to%20E.A%0D%0A%20%20%20%20%20%20break%0D%0A%20%20%20%20case%20E.B%3A%0D%0A%20%20%20%20%20%20input.enumValue%20%2F%2F%20inferred%20as%20E.B%20correctly%0D%0A%20%20%20%20%20%20specificThingB(input)%20%2F%2F%20Type%20E%20is%20not%20assignable%20to%20E.B%0D%0A%20%20%20%20%20%20break%0D%0A%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20input.enumValue%20%2F%2F%20inferred%20correctly%20as%20never%0D%0A%20%20%7D%0D%0A%7D%3B%0D%0A%0D%0Aconst%20specificThingA%20%3D%20(input%3A%20%7B%20otherStuff%3A%20string%20%7D%20%26%20%7B%20enumValue%3A%20E.A%20%7D)%3A%20void%20%3D%3E%20%7B%0D%0A%20%20%2F%2F%20do%20stuff%0D%0A%7D%0D%0A%0D%0Aconst%20specificThingB%20%3D%20(input%3A%20%7B%20otherStuff%3A%20string%20%7D%20%26%20%7B%20enumValue%3A%20E.B%20%7D)%3A%20void%20%3D%3E%20%7B%0D%0A%20%20%2F%2F%20do%20stuff%0D%0A%7D

**Related Issues:** 
No

**Comment by dragomirtitian** [comment]
Typescript will not narrow the type of `input`, it will only narrow the type of the field `enumValue`. To get the desired behavior you need `input` itself to be union and then the switch type guards will work like you expect them to: 

```ts
enum E {
  A = 'a',
  B = 'b'
}
type DistributeEnumToUnion = { enumValue: E.A } | { enumValue: E.B };
const createSpecificThing = (input: { otherStuff: string } & DistributeEnumToUnion: void => {
  switch (input.enumValue) {
    case E.A:
      input.enumValue // inferred as E.A correctly
      specificThingA(input) // Type E is not assignable to E.A
      break
    case E.B:
      input.enumValue // inferred as E.B correctly
      specificThingB(input) // Type E is not assignable to E.B
      break
    default:
      input // now
  }
};

const specificThingA = (input: { otherStuff: string } & { enumValue: E.A }): void => {
  // do stuff
}

const specificThingB = (input: { otherStuff: string } & { enumValue: E.B }): void => {
  // do stuff
}

``` 

Or if you can obtain the union from a uniform transformation of all enum members you could leverage the distribution behavior of conditional types. This can be useful if you have a lot of enum memebrs. The type below is equivalent with the type with the same name above:
```ts
type DistributeEnumToUnion = E extends infer T ? T extends any ? { enumValue: T } : never : never; 
```

**Comment by RyanCavanaugh** [comment]
See #10065

**Comment by cdimitroulas** [comment]
Thanks @dragomirtitian for the details solutions/workarounds - I see a similar issue is already being tracked so feel free to close this in favor of the other one if you wish @RyanCavanaugh 

As always, thanks for the quick responses on new issues!
