### ISSUE TITLE
Allow interfaces to extend types generated from other interfaces

### ISSUE THREAD

**Issue by xeoneux** [microsoft/TypeScript#30121]
## Search Terms

Interface Extend Types

## Suggestion

Suppose I have an object like 
```
const obj = {
  browser: "Chrome",
  version: "27",
  supportsVR: true
  ...(other properties)...
}
```

I'd try to create a new interface with same properties as a type:
```
type Chrome = 'Chrome'
type Firefox = 'Firefox'
type Opera = 'Opera'

type ChromeVersion = '27' | '28' | '29'
type FirefoxVersion = '15' | '16' | '17'
type OperaVersion = '4' | '5' | '6'

interface IChromeBrowser {
  browser: Chrome;
  version: ChromeVersion
}
interface IFirefoxBrowser {
  browser: Firefox;
  version: FirefoxVersion
}
interface IOperaBrowser {
  browser: Opera;
  version: OperaVersion
}

type IBrowser = IChromeBrowser | IFirefoxBrowser | IOperaBrowser

interface NewInterface extends IBrowser { // Not supported
  // ...IBrowser properties
  supportsVR: boolean
}

const abc: NewInterface {
  supportsVR: true,
  browser: 'Chrome'
  version: '4' // Error because version '4' is not a Chrome Version!
}
```

## Use Cases

I don't think there's a current approach at the moment without involving generics perhaps?

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
Unions can't be extended by interfaces (at least not currently). You can just use an type alias with an intersection type to achieve a similar functionality:
```ts

type NewInterface = IBrowser & { 
  supportsVR: boolean
}

const abc: NewInterface = { //err 
  supportsVR: true,
  browser: 'Chrome',
  version: '4' 
}
```

[link](https://typescript-play.js.org/#code/C4TwDgpgBAwgFgJwPYFtoF4oHJ7LVgKFEigDEBLBCAMyQA8pMsKra7DjoB5SBAQ0bYeEfoSLhouVBABqIgM7kkAO0FYATAHYsUAD7Z1ADh36NATg4SylGvTkJFKtQEYArCezOAbB6zPt4iTC-PaOqkwALL7uetg+BATkysAi1HwAxtAAklJoAELIAO7yIlAA3gRQUABGRSUIAFywiNIA3JVQAG4KSspNubI9KgQAvonJqRnZLLZ0BUjFpRVVtQv1TTNs7VXdDr0bNmyhvaPjKQhpmVBZwXzziwjlHasPTbfbXUN9ULfHw2OBbL3eqCHItfJ1Ur6LKbejAqHXW7whAJThQAByEEKWQmFymoORUAAZOUoB15ABXMBgJAIYDyGQAJSa1SQSAANhA+MpTgR0ip5MAoHxqukmpjsbjLhgnlVKdTafSmU1gAgKRAADTPSGNbADLBanZfJpYKJQAD05qgAFEEMhHtUIOk+BSSp89k5TTpyPIoMokEKBAMoH9lABCUZAA)

**Comment by xeoneux** [comment]
Thanks @dragomirtitian, this looks a good alternative till unions can't be extended by interfaces. 👍

**Comment by RyanCavanaugh** [comment]
It's not obvious from the declaration what this would even do - you could see it either as creating a new union, or only bringing down the properties in common amongst the union, or some other behavior. An intersection type is the clearer way of writing what you intend to do.
