### ISSUE TITLE
Generic parameters inference in interface

### ISSUE THREAD

**Issue by MasGaNo** [Microsoft/TypeScript#30120]
**TypeScript Version:**  3.4.0-dev.20190226

**Search Terms:**
Generic parameters inference

**Code**

```ts
interface IFoo {
    id: string;
}

interface ITest<T extends IFoo | IFoo[]> {
    data: T;
};

interface ITest2<T extends IFoo | IFoo[]= IFoo> {
    data: T;
}

const test1: ITest = { // Generic type 'ITest<T>' requires 1 type argument(s). ts(2314)
    data: [{
        id: ''
    }]
}

const test2: ITest2 = {
    data: [{ // Property 'id' is missing in type '{ id: string; }[]' but required in type 'IFoo'. ts(2741)
        id: 'fds'
    }]
}
```

**Expected behavior:**
I expect the interface `ITest` to understand that `data` is typeof `Array<IFoo>` like for generic method inference.
If I precise a default value for generic parameter (`ITest2`), I can understand that in my `test2` implementation, it will take `IFoo` as a default implementation, even if I found the error explanation a little bit weird to understand.

**Actual behavior:**
As describe in the `code` section, I get some errors because I ***must*** provide the expected type.
The thing is, sometime, in some third party library definition, they don't export some `type`, so I cannot easily pick the expected variant of the generic type I want to have.
A  way to fix it, is to recreate a `type` by mimicking the structure of the original `type`, but I increase the number of source of truth, so as soon as the third party update the definition, it breaks my duplicated `type`.

**Playground Link:** 
[Playground link](http://www.typescriptlang.org/play/#src=interface%20IFoo%20%7B%0D%0A%20%20%20%20id%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ITest%3CT%20extends%20IFoo%20%7C%20IFoo%5B%5D%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ITest2%3CT%20extends%20IFoo%20%7C%20IFoo%5B%5D%3D%20IFoo%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aconst%20test1%3A%20ITest%20%3D%20%7B%0D%0A%20%20%20%20data%3A%20%5B%7B%0D%0A%20%20%20%20%20%20%20%20id%3A%20''%0D%0A%20%20%20%20%7D%5D%0D%0A%7D%0D%0A%0D%0Aconst%20test2%3A%20ITest2%20%3D%20%7B%0D%0A%20%20%20%20data%3A%20%5B%7B%0D%0A%20%20%20%20%20%20%20%20id%3A%20'fds'%0D%0A%20%20%20%20%7D%5D%0D%0A%7D)

**Related Issues:** 
Well... I found lot of issues but related with generic method (that works like a charm today), not really just for interface...

**Comment by RyanCavanaugh** [comment]
Working on this area at #26242

**Comment by MasGaNo** [comment]
Oh! true, I miss this one!
Great news! I'm looking forward this issue.

**Comment by ianstormtaylor** [comment]
Still would really love to see this for defining plain objects that map to a generic type! Would be really helpful for creating inputs that a framework expects without having to use extra factory functions everywhere.
