### ISSUE TITLE
typescriptServices.d.ts in 1.5-beta is missing Scanner interface

### ISSUE THREAD

**Issue by ashwinr** [Microsoft/TypeScript#3012]
Hello: TSLint is using the scanner interface for a few things -- like walking through all tokens for enabling/disabling rules [selectively](https://github.com/palantir/tslint/blob/master/src/enableDisableRules.ts#L25) or for enforcing [indentation](https://github.com/palantir/tslint/blob/master/src/rules/indentRule.ts#L51). Since the scanner is no longer exported in the d.ts. in beta, this breaks TSLint. Can you please tell us what the alternative to using a scanner is, or if there's any way to have the scanner exported in typescript's d.ts? Thanks!

**Comment by mhegazy** [comment]
We just wanted to limit the API surface area. I can expose the scanner again if you have dependency on it. Just curious why not use Node.getChildren(),

**Comment by gscshoyru** [comment]
We need the scanner because Node.getChildren doesn't cover comments or whitespace -- both of which we need to access for the linter. There's no other good way to scan all the comment nodes, for instance.
