### ISSUE TITLE
Doc Update: add reference to react+typescript cheatsheet project

### ISSUE THREAD

**Issue by foxyblocks** [microsoft/TypeScript#30137]
## Search Terms

- cheatsheet
- react .md

## Suggestion

Documentation addition request.

I'd like a reference to https://github.com/sw-yx/react-typescript-cheatsheet added to the ["React & Webpack" section of the typescript documentation](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html)

I think it would be invaluable for people of all experience levels who use react + typescript.

I would have made this change in the form of a PR but I can't find a reference to the doc in this repo's codebase or anywhere else.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by karol-majewski** [comment]
https://github.com/piotrwitek/react-redux-typescript-guide is also an excellent resource (it's even recommended by the one from the original post).

**Comment by RyanCavanaugh** [comment]
We're trying to scope down the official documentation to be simply about TS itself instead of *TS + (every ecosystem thing under the sun)*; this would belong in the latter camp.

**Comment by wordofchristian** [comment]
> We're trying to scope down the official documentation to be simply about TS itself instead of _TS + (every ecosystem thing under the sun)_; this would belong in the latter camp.
@RyanCavanaugh 

Wouldn't the existence of this react section in the typescript docs mean that you are already breaking out of that focused scope? I believe it's possible to maintain a focused scope while still offering links to helpful resources for further research on topics that, while techically out of scope, are still likely to be useful to the reader.

**Comment by wordofchristian** [comment]
@RyanCavanaugh Perhaps this is an opportunity to actually clean up the existing docs. I think it's a little odd that there is a react section and not a vue section, or whatever else. Maybe the best thing to do would be to get rid of the react section entirely and instead replace it with a section called something like "Framework specific resources". Then it could just be an aggregate of links to external guides. I think this could have the benefit of tightening the scope of the typescript docs and reduce the maintenance burden.

**Comment by RyanCavanaugh** [comment]
> Wouldn't the existence of this react section in the typescript docs mean that you are already breaking out of that focused scope? I

Yes. We intend to not port this content forward as part of the ongoing handbook rewrite effort.
