### ISSUE TITLE
Shorthand for types/interfaces with properties of same type

### ISSUE THREAD

**Issue by knomdlo** [microsoft/TypeScript#30149]
## Search Terms
Interface shorthand, sugar syntax, interfaces of same type, types of same type

## Suggestion
Can a shorthand be added to create  interfaces/types that have all keys of same type.

## Use Cases

Reduce the no of lines & also help in readability.
## Examples

`export interface AllStrings {
    prop1: string;
    prop2: string;
}`

to something like

`export interface AllStrings<type: string> {
    prop1,prop2;
}`
## Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x ] This wouldn't change the runtime behavior of existing JavaScript code
* [x ] This could be implemented without emitting different JS based on the types of the expressions
* [x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [- ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
What about:
```ts
type AllStrings = Record<"prop1" | "prop2", string>
```
