### ISSUE TITLE
Distinguish declaration and usages when matching references in Visual Studio

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/TypeScript#3014]
When matching references of a symbol, display the declaration and the usages slightly differently in Visual Studio.

As I can see you already support this (the Monaco editor):
![monaco-ts-declaration](https://cloud.githubusercontent.com/assets/9047283/7446597/baf7dcb0-f1dd-11e4-88cc-530279abffad.PNG)

But in Visual Studio the declaration and the usages of a symbol look the same:
![vs-ts-declaration](https://cloud.githubusercontent.com/assets/9047283/7446596/baf5c286-f1dd-11e4-8f40-9d48625af0b3.PNG)

The C# language service in Visual Studio takes a difference, which is the desired behavior:
![vs-cs-reference](https://cloud.githubusercontent.com/assets/9047283/7446598/bb1f1b86-f1dd-11e4-863f-b75446e365f5.PNG)

**Comment by mhegazy** [comment]
@CyrusNajmabadi can you follow up with the @roslyn team on this. The language service API supports this, we just do not have a visualization in vs for it.

**Comment by CyrusNajmabadi** [comment]
This should work by VS2015 RTM.  We've plumbed the relevant information through, all the way from the compiler to Roslyn.   Roslyn then allows you to visualize this difference with the following options:

![image](https://cloud.githubusercontent.com/assets/4564579/7450323/69b07842-f1f8-11e4-8599-49e566105d2a.png)

Note that there are three different types of highlights you can color differently:

1. The definition.
2. A non-written reference.
3. A written reference (coming at RTM).

Note that by default all these colors are the same.  But you can totally change the colors to be whatever you want.  They'll even be saved and roamed across your VS instances if you've logged into VS.

**Comment by danquirk** [comment]
@CyrusNajmabadi why are these 3 things all colored the same by default? I think that will just lead to the majority of people never discovering this new feature exists. If we believe the feature is valuable we should just turn it on by default by designing some useful colored defaults.

**Comment by Peter-Juhasz** [comment]
@danquirk The declaration looks slightly different (in C#/VB). It has a thin border around (as you can see on the third screenshot). The border is not configurable, but I'm perfectly fine with it. I just want to see it in the TypeScript editor as well.

**Comment by CyrusNajmabadi** [comment]
You should ping DustinCa about this. I personally agree. It's also of that they have differing colors when in the dark theme.  I'm keeping us consistent with Roslyn. But I think all the Roslyn languages would benefit here.

Note,I also liked Dustin so we found meet about improvements once I'm back from vacation (and he I'd back from ignite). Du you want to come along?

    -- Cyrus
________________________________

**Comment by CyrusNajmabadi** [comment]
I have fixed things so that TypeScripy will have the same behavior as VB/C#. You will see this fix in VS2015 RTM.

    -- Cyrus
________________________________

**Comment by danquirk** [comment]
@CyrusNajmabadi yeah ping me when you're back and we can sync up with him. I'll try to remember to send him something after Ignite so it doesn't risk getting lost in the shuffle.
