### ISSUE TITLE
Warning: #27697 will break a lot of libraries at the next release

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#30142]
At least breaking of a very basic pattern #30118 will break existing typings.

**Comment by j-oliveras** [comment]
It was reverted yesterday, see #30133

**Comment by falsandtru** [comment]
Looks like not added any regression tests.

**Comment by RyanCavanaugh** [comment]
@falsandtru you could at least give **one** example so we have some clues to go off of. Please make an effort before clicking the green button.
