### ISSUE TITLE
Default value of the constructor argument - does not typecheck

### ISSUE THREAD

**Issue by SamuraiJack** [Microsoft/TypeScript#30157]
Currently (3.3.3333) this code typechecks fine:
```ts
class Some {}

const func = <T extends typeof Some = typeof Some> (arg : T) => {}
```
However, this, produces compilation error:
```ts
class Some {}

const func = <T extends typeof Some = typeof Some> (arg : T = Some) => {}
```
`TS2322: Type 'typeof Some' is not assignable to type 'T'.`

The error message seems to contradict to the compiler behavior in the first place - the default value of the `T` is `typeof Some`. Looks like an inconsistency? If some type extends another type, in some unknown way, it can always extend it w/o any modifications, right? In such case the, in the TypeScript "structural typing" spirit, its the same type, so it should be assignable?

**Comment by jack-williams** [comment]
See #21521

**Comment by SamuraiJack** [comment]
The #21521 seems to first start with the case where the `T` argument is unrestricted type, but has a default value `<T = number>`. In this case the  @mhegazy's comment [here](https://github.com/Microsoft/TypeScript/issues/21521#issuecomment-362124024) is valid.

However then the thread continues, with the suggestion from @zaclummys to restrict the type: `
<T extends number>`. That changes the picture completely and there's no "official" comments from the maintainers team after it. So this issue is valid, and #21521 should be revised too. 

Again, the compiler itself acknowledges, that `typeof Some` is a valid element in the type `T` - the default one. In fact it seems the `Some` is the only possible default value for the `arg` - any other would assume some fixed implied constraint on the `T`. But the constructor value `Some` is the "minimal" possible value of the `T` type.

**Comment by jack-williams** [comment]
True! I think this is a closer fit: #28154

**Comment by SamuraiJack** [comment]
Right, the #28154 is quite close to this one. The current issue can be rewritten in this way, (copied from the #28154 and modified - the alternative in `Z` removed):

```ts
type Z = "a"

// Error: Type '"a"' is not assignable to type 'T'.
function func<T extends Z>(arg: T = 'a') { }
```

Here the `'a'` is the only possible default value for `arg`

**Comment by jack-williams** [comment]
You're implicitly assuming that the type `"a"` has a single inhabitant `"a"` which is unnecessarily unrestrictive and leads to an unstable type-system. 

The technical issue with that assumption is that it violates parametricity; the practical issue with that assumption is that it is future-incompatible.

The type `"a"` could equally be an infinite set of `"a"`'s each associated with a name. This could happen if TypeScript ever added name subtyping like flow.
```ts
export opaque type A_ID: "a"= "a";

function func<T extends "a">(arg: T = "a") { }

func<A_ID>() // A_ID is assignable to "a", but "a" is not assignable to A_ID
```
This [paper](https://www.irif.fr/~gc/papers/icfp11.pdf) explains the details of this far better than I ever could.

**Comment by SamuraiJack** [comment]
Is the `opaque` modifier something like `newtype` in Haskell, that creates a type alias basically, but the alias is considered different from the type itself? But then its a different case completely - it even involves the new special keyword. 

By default type alias `type A = B` creates an "identical" type, whatever it means isn't it?

**Comment by jack-williams** [comment]
Yes the flow `opaque` modifier creates something like a newtype, but if you specify a type after the `:` you can define a super type for the new alias. That is: `A_ID <: "a"`.

The point being that allowing `function func<T extends "a">(arg: T = "a") { }` to type check makes the assumption that the only non-empty subtype of `"a"` is itself. This assumption is will fail if TypeScript ever supports name-subtyping.

**Comment by SamuraiJack** [comment]
In such case I think TypeScript need "opaque extends" or something similar. The semantic of `extends` (not very well documented btw) becomes very overloaded and supposed to work the same way with normal types and opaque types.

The `function func<T extends "a">(arg: T = "a") { }` feels very natural.

**Comment by jack-williams** [comment]
There is no need for a new `opaque extends`. An opaque type is simply related to itself, and optionally a supertype. This discussion has gone-somewhat off track and fixate on literal types. In the original case it should be clear that the default is unsafe:
```ts
class Some {
    x!: number
}

class SomeMore extends Some {
    y!: boolean;
}

const func = <T extends typeof Some = typeof Some>(arg: T = Some) => {
    return arg;
}

const res: boolean = (new (func<typeof SomeMore>())).y // oops
```

**Comment by RyanCavanaugh** [comment]
Even if you accept the argument that `"a"` is forever a unit type, then the function *ceases to be generic anyway*, so it's an entirely moot example.

**Comment by SamuraiJack** [comment]
@jack-williams Hm.. Ok, not sure I'm completely convinced, but probably it make sense. Whats the exclamation mark after the property name? Non-nullable type?

**Comment by jack-williams** [comment]
> Whats the exclamation mark after the property name? Non-nullable type?

It's a [definite assignment assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions). I just put it there so I could add a property without the checker complaining.

**Comment by SamuraiJack** [comment]
I see, thanks for explanation.
