### ISSUE TITLE
Wrong type inference for inherited static class factory

### ISSUE THREAD

**Issue by Raiondesu** [Microsoft/TypeScript#30151]
**TypeScript Version:**  3.4.0-dev.20190228

**Search Terms:**
static property this as constructor type inference (in any order/inclusion)

**Problem:**
Let's say, we have a class that must be instantiated using a static factory function:
```ts
class Test {
  private constructor(public x: number) {}

  static create(x: number) {
    // As `this` here is of type `typeof Test` (constructor), this code is perfectly valid.
    return new this(x);
  }
}
```
Then:
```ts
class TestChild extends Test {
  // Here, we introduce a property only `TestChild` has to trigger an error later
  get xIsNumber() {
    return typeof this.x === 'number';
  }
}

const testChild = TestChild.create(2);

testChild; // TS tells that testChild is of type `Test`.
// Actual console output:
// ▶ TestChild {x: 2}

console.log(testChild.xIsNumber); // TS tells that "Property 'xIsNumber' does not exist on type 'Test'."
// Actual console output:
// => true
```

**Expected behavior:**
`testChild` should be of type `TestChild`, because the static method `create` uses realtive `this` to construct the instance of a class. When the method `create` is invoked from the `TestChild`, it uses `TestChild`'s constructor as `this`, not `Test`'s. For `TestChild`, `this` in the inherited method `create` is of type `typeof TestChild`.

**Actual behavior:**
However, TS has solidified the return type as `Test` for some reason.
Therefore, `testChild` is of type `Test`.

**Playground Link:**
https://www.typescriptlang.org/play/#src=class%20Test%20%7B%0D%0A%20%20constructor(public%20x%3A%20number)%20%7B%7D%0D%0A%0D%0A%20%20static%20create(x%3A%20number)%20%7B%0D%0A%20%20%20%20return%20new%20this(x)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20TestChild%20extends%20Test%7B%0D%0A%20%20get%20xIsNumber()%20%7B%0D%0A%20%20%20%20return%20typeof%20this.x%20%3D%3D%3D%20'number'%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20testChild%20%3D%20TestChild.create(2)%3B%0D%0A%0D%0Aconsole.log(testChild.xIsNumber)%3B

**Related Issues:** Found none...

**Comment by dragomirtitian** [comment]
You can easily get this to work using a generic type parameter to the `create` function and a type annotation for `this`. 

```ts
class Test {
  constructor(public x: number) {}

  static create<T>(this: new (x: number)=> T, x: number) {
    return new this(x);
  }
}

class TestChild extends Test{
  get xIsNumber() {
    return typeof this.x === 'number';
  }
}

const testChild = TestChild.create(2);

console.log(testChild.xIsNumber); // ok

````

**Comment by Raiondesu** [comment]
@dragomirtitian, this is a perfectly valid workaround, yes. But this workaround requires to retype constructor in the factory every time there was a change to this constructor. And if the factory is introduced to the inheritance chain sometime later (in hypothetical `ChildOfTestChild`, for example), refactoring this can quickly become a pain.

The issue is, anyway, related to the implicit type inference. In this workaround, however, the constructor's return type is explicitly stated, thus the resulting type not being a properly inferred one anyway.

This can be demonstrated by this code:
```ts
class Test {
  constructor(public x: number) {}

  // This example shows that TS cannot properly infer the return type of a constructor,
  // because type argument `U` falls back to `Test` in any case, whereas type `T` is inferred correctly
  static create<U extends Test, T extends new (x: number) => U>(this: T, x: number): U {
    return new this(x);
  }
}

/// ... TestChild here ...


const testChild = TestChild.create(2);

console.log(testChild.xIsNumber); // Error here again
```

Thus, the offered workaround kinda explicitly "shows" TypeScript where to look for the constructor's return type, which only demonstrates the issue in question: lack of type inference.

**Comment by RyanCavanaugh** [comment]
Duplicate #5863

**Comment by Raiondesu** [comment]
Oh. Okay.
Gonna add my case to the issue then.
