### ISSUE TITLE
[...someNodeList] doesn't expand to Array in TypeScript

### ISSUE THREAD

**Issue by ststeiger** [microsoft/TypeScript#30164]
TypeScript Version: 3.1

`[...this.$svg.querySelectorAll('.bar-wrapper')]`
transpiles to
`this.$svg.querySelectorAll('.bar-wrapper').slice()`
instead of
`Array.prototype.slice.call(this.$svg.querySelectorAll('.bar-wrapper'))`

Which leads to bugs
https://github.com/ststeiger/gantt/commit/360ae2e701687097ea09c5cf8ee183d35f0b3b33

https://github.com/ststeiger/WebCAD/blob/master/WebCAD/TypeScript/Gantt/index.ts#L949

https://stackoverflow.com/a/33822526/155077

**Comment by NN---** [comment]
Interesting that ES5 target doesn't allow such [code](https://typescript-play.js.org/?target=1#code/MYewdgzgLgBAhjAvDAJiYBXAtgUzFAOgEcMcAnATwGUcAbHYKEMgQVtoAoByOLgSgDcAKFCRYAIyQwA2gTlwAugKA):

```ts
const a = document.querySelectorAll('a');
const b = [...a]; // Error a is not an array
```

**Comment by LukasLSC** [comment]
Open `tsconfig.json` - TypeScript configuration file.

First, you have to __include `"dom", "dom.iterable"` library files__ in the compilation using the `lib` option: `"lib": ["esnext", "dom", "dom.iterable"]`.

`"esnext"` isn't necessary in your example, however, without it, you won't be able to use any ESNext (at the time of writing - ES2018) and below functionality in your TS project, e.g. `Array` constructor.

Then, to provide the full support for iterables in `for-of`, spread, and destructuring, __enable the `downLevelIteration` option__: `"downlevelIteration": true`.

Note that `lib` option __requires TypeScript 2.0 or later__ to work, while `downLevelIteration` __requires TypeScript 2.3 or later__ to work.

That's how it should look like (red area):
![Image of the fix](https://i.imgur.com/LWieADq.png)

---

More details:
* [Compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

* [`lib` option](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib)

* [`domLevelIteration` option](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#new---downleveliteration)

**Comment by RyanCavanaugh** [comment]
Something about your project is misconfigured relative to your runtime, because you should either see an error or get a longer downlevel iteration helper that does the right thing.

**Comment by ststeiger** [comment]
@LukasLSC: That's a nice catch. Ok that way it works. 
But then the TS-compiler should throw an error, like ... not allowed etc.

**Comment by RyanCavanaugh** [comment]
> But then the TS-transpiler should throw an error, like "spread operator not allowed in ES5" etc.

![image](https://user-images.githubusercontent.com/6685088/53824195-4166ab00-3f28-11e9-9426-bb09c50e8691.png)

**Comment by ststeiger** [comment]
@RyanCavanaugh: Never seen that, it just transpiled to spread, which would have been correct, had it used array.prototype.spread, instead of calling spread on nodelist.
