### ISSUE TITLE
Add `extendsExact: bool` property to tsconfig.json

### ISSUE THREAD

**Issue by nodkz** [microsoft/TypeScript#30163]
## Search Terms

Lerna monorepo, extends, config inheritance, disable relative path.

## Suggestion

According to [design choise](https://github.com/Microsoft/TypeScript/issues/24851#issuecomment-398573713) of `extends` property to make paths relative - it brings some problems for monorepos with multiple packages with different configs.

**I suggest to add `extendsExact: bool` property to `tsconfig.json` which will keep paths as is (without resolving relative paths)**

It quite simple to implement with current codebase and allows to developers use different scenarios.

## Use Cases

We cannot use base template for all packages (we have 20 packages and need to fix in every config `includes` and `excludes` sections). It quite hard to track. If we add something to base template, we should to change all tsconfigs in every package.

My real use case is quite complex. We have boilerplate repo, where defined all configs, dev packages and code conventions. I maintain this MAIN repo. All other developers fork my repo and adds their code to `packages` folder (in [Lerna](https://github.com/lerna/lerna) way) where use some of config from root folder for their packages. So at any time I may update my boilerplate (MAIN repo) and all other teams may easily merge my changes without affecting their code in `packages` folder.

## Examples

We have a base configs:

```js
// tsconfig.server.json
{
  excludes: ["node_modules"],
  includes: ["src/**/*.ts", "server.globals.ts"]
}
```

```js
// tsconfig.client.json
{
  excludes: ["node_modules", "__tests__"],
  includes: ["src/**/*.ts"]
}
```

And in Lerna  monorepo developers may use these tsconfig as real dumb template:

```text
tsconfig.server.json
tsconfig.client.json
lerna.json
packages/
 - pkg1-server
     - tsconfig.json { extends: '../../tsconfig.server.json', extendsExact: true } 
 - pkg1-client
     - tsconfig.json { extends: '../../tsconfig.client.json', extendsExact: true }      
 - pkg1-client-admin
     - tsconfig.json { extends: '../../tsconfig.client.json', extendsExact: true } 
 - pkg2-node-driver
     - tsconfig.json { extends: '../../tsconfig.server.json', extendsExact: true } 
 - ... tons of other packages ...
```

So with such monorepo I can just change root config file, and all packages gets new config with EXACT paths for (`files`, `includes`, `excludes`) like they are in root config files.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by NoelAbrahams** [comment]
I think this will also fix #29172.

**Comment by SgtPooki** [comment]
I would love to see this implemented. @nodkz have you looked into creating a PR for this? We might be able to get this in more easily if we have code ready for them to import.

**Comment by zheeeng** [comment]
It is useful to the monorepo project which its sub packages all have a same tsconfig.json configuration but need they own outDir and typeRoot

**Comment by rhyek** [comment]
I have a related use-case where I am also using lerna and every package is basically running some sort of filewatcher that executes a tsc compilation on its respective source code. I'm running all of them from my monorepo root with `lerna run --parallel dev` and whenever I have an error in any of the packages the paths I see in the terminal are relative and therefore these are not showing up in VSC under the `Problems` tab and I can't cmd+click the file path in the terminal to navigate to it either.
