### ISSUE TITLE
Intellisense not working on nested or the indirect value having objects

### ISSUE THREAD

**Issue by LukasLSC** [Microsoft/TypeScript#30173]
**TypeScript Version:**  3.4.0-dev.201xxxxx.

                                                                                     
**Search Terms:** Nested objects have no intellisense, nested objects lose intillisense, objects with indirect value have no intellisense, even if the type is directly set.

**Code**
```ts
// Setup to check the diff between the direct (no variable) / indirect (using variable) types

type t = { instance?: string } & (
    | { lengths: object }
    | { values: object }
    | { lengths: object; values: object });

const obj = {
    instance: 'a',
    values: { min: { amount: 1 } },
    lengths: { min: { amount: 54 } }
};
```

```ts
// Not working when 'type direct, value indirect', too 
const notWorkingBothIndirect: t = obj;
notWorkingBothIndirect. // <-- Only 1 autocomplete item given: `instance?`

/**
 * Not working when 'indirect type nested, value direct', 'direct type nested,
 * value direct', 'both direct nested', too.
 */

const notWorkingNested: { exchange: t } = { exchange: obj };
notWorkingNested.exchange. // <-- Only 1 autocomplete item given: `instance?`

// Working when 'type and value direct', too
const workingIndirectTypeDirectValue: t = {
    values: { min: { amount: 1 } },
    lengths: { min: { amount: 54 } }
};

// 3 autocomplete items given: `instance:`, `lengths`, `values`.
workingIndirectTypeDirectValue.
```

**Expected behavior:** All the not working examples above should work identically to the last working example - show __3__ autocomplete items.

**Actual behavior:** Nested and indirect value having objects show only a type combined by the intersection `&` (`instance?`) and not the union `|` (`lengths`, `values`).

**Playground Link:** [TS Playground](https://www.typescriptlang.org/play/#src=type%20t%20%3D%20%7B%20instance%3F%3A%20string%20%7D%20%26%20(%0D%0A%20%20%20%20%7C%20%7B%20lengths%3A%20object%20%7D%0D%0A%20%20%20%20%7C%20%7B%20values%3A%20object%20%7D%0D%0A%20%20%20%20%7C%20%7B%20lengths%3A%20object%3B%20values%3A%20object%20%7D)%3B%0D%0A%0D%0Aconst%20obj%20%3D%20%7B%0D%0A%20%20%20%20instance%3A%20'a'%2C%0D%0A%20%20%20%20values%3A%20%7B%20min%3A%20%7B%20amount%3A%201%20%7D%20%7D%2C%0D%0A%20%20%20%20lengths%3A%20%7B%20min%3A%20%7B%20amount%3A%2054%20%7D%20%7D%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20Not%20working%20when%20'type%20direct%2C%20value%20indirect'%2C%20too%20%0D%0Aconst%20notWorkingBothIndirect%3A%20t%20%3D%20obj%3B%0D%0AnotWorkingBothIndirect.%0D%0A%0D%0A%2F%2F%20Not%20working%20when%20'indirect%20type%20nested%2C%20value%20direct'%2C%20'direct%20type%20nested%2C%20value%20direct'%2C%20'both%20direct%20nested'%2C%20too%0D%0Aconst%20notWorkingNested%3A%20%7B%20exchange%3A%20t%20%7D%20%3D%20%7B%20exchange%3A%20obj%20%7D%3B%0D%0AnotWorkingNested.exchange.%0D%0A%0D%0A%2F%2F%20Working%20when%20'type%20and%20value%20direct'%2C%20too%0D%0Aconst%20workingIndirectTypeDirectValue%3A%20t%20%3D%20%7B%0D%0A%20%20%20%20values%3A%20%7B%20min%3A%20%7B%20amount%3A%201%20%7D%20%7D%2C%0D%0A%20%20%20%20lengths%3A%20%7B%20min%3A%20%7B%20amount%3A%2054%20%7D%20%7D%0D%0A%7D%3B%0D%0AworkingIndirectTypeDirectValue.).

**Related Issues:** All these issues were closed because as said in the port, it has been fixed in the newer release of TypeScript, however, it doesn't seem to fix an issue in my case (using newest TS version):

- https://github.com/Microsoft/TypeScript/issues/1038
- https://github.com/Microsoft/TypeScript/issues/12290
- https://github.com/Microsoft/TypeScript/issues/16781

**Comment by RyanCavanaugh** [comment]
There are about a billion trade-offs for whether you get the *declared type* or the *control-flowed type* at any given point in a program. The behavior you see here reflects the current set of decisions and we can't really change them without breaking a ton of code.

For example, if `obj` had a `foo` property, should that be visible at `notWorkingBothIndirect.` ? Clearly no, because that's not a property of any constituent of `t`, but *by what logic* would `foo` not show up but we would still allow the members of `obj` ? It's not obvious how to do this without synthesizing new types at all control flow points in the program, and this is rarely what you actually want anyway.

**Comment by LukasLSC** [comment]
Thank you for the answer, however, I still don't quite understand what do you mean by saying _synthesizing new types at all control flow points_?

Why it's so hard to understand that both properties `a` and `b` should be shown in this example?:

```ts
const a: {forms: {a: string} | {b: string} | {a: string; b: number} } = {forms: { a: 'q', b: 4}};

// No autocomplete
a.forms.
```

But using this variable without the `forms` property:

```ts
const a: {a: string} | {b: string} | {a: string; b: number} = { a: 'q', b: 4};

// Works perfectly, 2 items shown
a.
```

Not sure what I could do in this situation.
