### ISSUE TITLE
Conversion of type 'boolean' to type 'number' may be a mistake

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#30172]
retracted

**Comment by nmain** [comment]
`boolean` contains `true` and `false`, but `number` contains well, numbers, so neither one has any values in common with the other.

**Comment by RyanCavanaugh** [comment]
Writing a comparator function that can't return `-1` is a really good way to *not* sort a list

**Comment by ackvf** [comment]
true :)
