### ISSUE TITLE
LanguageService.getReferencesAtPosition reports wrong references for named imports

### ISSUE THREAD

**Issue by adidahiya** [Microsoft/TypeScript#3017]
I'm seeing some strange results from calling `LanguageService.getReferencesAtPosition()` on a named import.

I have `file.ts` which starts with these lines:

```ts
import  $ = require("jquery");
import  _ = require("underscore");
import  xyz = require("xyz");
import {createReadStream, createWriteStream} from "fs";
```

and calling `LanguageService.getReferencesAtPosition()` on the position of the node that represents `createReadStream` returns these references:

```
[ { fileName: 'lib.d.ts',
    textSpan: { start: 115, length: 16 },
    isWriteAccess: true },
  { fileName: 'fs.ts',
    textSpan: { start: 115, length: 16 },
    isWriteAccess: true },
  { fileName: 'xyz.ts',
    textSpan: { start: 115, length: 16 },
    isWriteAccess: true },
  { fileName: 'underscore.ts',
    textSpan: { start: 115, length: 16 },
    isWriteAccess: true },
  { fileName: 'jquery.ts',
    textSpan: { start: 115, length: 16 },
    isWriteAccess: true },
  { fileName: 'file.ts',
    textSpan: { start: 115, length: 16 },
    isWriteAccess: true } ]
```

I can hack around this behavior, but this seems like a bug.

(using latest `v1.5.0-beta`)

**Comment by mhegazy** [comment]
I am not getting this to repro locally. i am assuming this is the latest jquery.d.ts and node.d.ts from definitely typed.. correct?

**Comment by mhegazy** [comment]
looks like this has been fixed. closing. please reactive if that is not correct.
