### ISSUE TITLE
Union type is not compatible to second union type, even with full overlap.

### ISSUE THREAD

**Issue by noblica** [Microsoft/TypeScript#30170]
**TypeScript Version:**  3.3.3

**Search Terms:**
Union types overlapping

**Code**

```ts
interface Blue {
    color: 'blue'
}
interface Yellow {
    color?: 'yellow',
}
function draw(val: Blue | Yellow) { }

function drawWithColor(currentColor: 'blue' | 'yellow' | undefined) {
    // The following line throws the type error: Type '"blue"' is not assignable to type '"yellow"'.
    return draw({ color: currentColor });
}
```
**Expected behavior:**
No type errors exist, because there is an interface which would accept 'blue'.

**Actual behavior:**
An error is thrown:
```
Argument of type '{ color: "blue" | "yellow"; }' is not assignable to parameter of type 'Blue | Yellow'.
  Type '{ color: "blue" | "yellow"; }' is not assignable to type 'Yellow'.
    Types of property 'color' are incompatible.
      Type '"blue" | "yellow"' is not assignable to type '"yellow"'.
        Type '"blue"' is not assignable to type '"yellow"'.
```

**Playground Link:** 
[Link to the playground example](https://www.typescriptlang.org/play/#src=interface%20Blue%20%7B%0D%0A%20%20%20%20color%3A%20%27blue%27%0D%0A%7D%0D%0Ainterface%20Yellow%20%7B%0D%0A%20%20%20%20color%3F%3A%20%27yellow%27%2C%0D%0A%7D%0D%0Afunction%20draw%28val%3A%20Blue%20%7C%20Yellow%29%20%7B%20%7D%0D%0A%0D%0Afunction%20drawWithColor%28currentColor%3A%20%27blue%27%20%7C%20%27yellow%27%20%7C%20undefined%29%20%7B%0D%0A%20%20%20%20return%20draw%28%7B%20color%3A%20currentColor%20%7D%29%3B%0D%0A%7D%0D%0A%0D%0A)

**Comment by jack-williams** [comment]
It might be the case that a literal with type `{ x : A | B }` is assignable to `{ x: A } | { x: B }`, but this does not hold when you have more properties. TypeScript wont special-case for single property objects.

**Comment by RyanCavanaugh** [comment]
#8289 / #12052 /  #18421
