### ISSUE TITLE
Better inference on logical operators

### ISSUE THREAD

**Issue by RMHonor** [Microsoft/TypeScript#30186]
## Search Terms

logical, operator, inference

## Suggestion

When a value is known to have a falsy or truthy type, the compiler should return an error if it is involved in a logical expression which causes unreachable code.

## Use Cases

This would prevent redundant code when the developer is trying to write a logical expression, or highlight that they may be using the wrong variable.

## Examples

```typescript
const A: object = {};
const B = A || 'never returned';
```

```typescript
const A = false; // A is of type 'false'
const B = A && 'never returned';
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ajafff** [comment]
You might want to use this lint rule to detect such conditions: https://github.com/fimbullinter/wotan/blob/master/packages/mimir/docs/no-useless-predicate.md
[CLI and configuration docs](https://github.com/fimbullinter/wotan/blob/master/packages/wotan/README.md)

**Comment by RyanCavanaugh** [comment]
#9041 Disallow truthiness coercions on known-true/known-false values

**Comment by RMHonor** [comment]
Closing at this is a duplicate
