### ISSUE TITLE
Quick info returns wrong jsdoc tag for function overload

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#30181]
**TypeScript Version:**  3.4.0-dev.20190301

**Search Terms:**
- quickInfo
- jsdoc
- tags

**Code**

```ts
declare function foo(): void;

/**
 * @deprecated
 */
declare function foo(x: number): void;

foo()
```

1. Hover on `foo` on the last line

**Expected behavior:**
No deprecation tag shown since we are using the non deprecated

**Actual behavior:**
A deprecation tag is returned in the quickinfo response:

```
[Trace  - 5:08:21 PM] Response received: quickinfo (311). Request took 2 ms. Success: true 
Result: {
    "kind": "function",
    "kindModifiers": "declare",
    "start": {
        "line": 8,
        "offset": 1
    },
    "end": {
        "line": 8,
        "offset": 4
    },
    "displayString": "function foo(): void (+1 overload)",
    "documentation": "",
    "tags": [
        {
            "name": "deprecated"
        }
    ]
}
```

**Playground Link:** 

**Related Issues:**

**Comment by jeanp413** [comment]
Hi, I'll like to take this.

**Comment by karfau** [comment]
@RyanCavanaugh Should Milestone now be changed to 3.8.0?

**Comment by sandersn** [comment]
@karfua Confusingly, 3.8.0 is the version for the beta, which is already out. 3.8.1 is the full release.

I think we do this for compatibility with versioning in Visual Studio.

**Comment by karfau** [comment]
@sandersn
OK, I was not aware there is a milestone for every patch version.
But currently this issue is part of the "community" milestone.
I just wanted to know if fixed issues are moved to the milestone of the version they are fixed in or not.

**Comment by sandersn** [comment]
I don't think so. I haven't been doing it and I don't think @RyanCavanaugh has a policy or bot to do so.
