### ISSUE TITLE
String literal downgrades to string for `Promise<T> | T` even with `async` keyword

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#30185]
**TypeScript Version:** 3.4.0-dev.20190301

**Search Terms:** literal type, degrade, downgrade, union, async, promise

**Code**

```ts
interface FooCallbackResult {
  value: 'foo';
}

type FooCallback = () => Promise<FooCallbackResult> | FooCallbackResult;

declare function foo(callback: FooCallback): void;

foo(async () => {
  return {
      value: 'foo'
  };
});
```

**Expected behavior:**

No error.

**Actual behavior:**

```
test.ts:9:5 - error TS2345: Argument of type '() => Promise<{ value: string; }>' is not assignable to parameter of type 'FooCallback'.
  Type 'Promise<{ value: string; }>' is not assignable to type 'FooCallbackResult | Promise<FooCallbackResult>'.
    Type 'Promise<{ value: string; }>' is not assignable to type 'Promise<FooCallbackResult>'.
      Type '{ value: string; }' is not assignable to type 'FooCallbackResult'.
        Types of property 'value' are incompatible.
          Type 'string' is not assignable to type '"foo"'.

9 foo(async () => {
      ~~~~~~~~~~~~~


Found 1 error.
```

**Playground Link:** https://www.typescriptlang.org/play/#src=interface%20FooCallbackResult%20%7B%0D%0A%20%20%20%20value%3A%20'foo'%3B%0D%0A%7D%0D%0A%0D%0Atype%20FooCallback%20%3D%20()%20%3D%3E%20Promise%3CFooCallbackResult%3E%20%7C%20FooCallbackResult%3B%0D%0A%0D%0Adeclare%20function%20foo(callback%3A%20FooCallback)%3A%20void%3B%0D%0A%0D%0Afoo(async%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20value%3A%20'foo'%0D%0A%20%20%20%20%7D%3B%0D%0A%7D)%3B%0D%0A

**Related Issues:** None.

**Comment by nickbclifford** [comment]
I believe you'll need an `as 'foo'` or `as const` assertion on that return value.

**Comment by vilic** [comment]
@nickbclifford I was trying to avoid this though. It works for `Promise<T>`, and hoping it works for `Promise<T> | T` sounds reasonable to me.

**Comment by RyanCavanaugh** [comment]
I believe the only thing we need to do here is say when an async function is contextually typed by a union, only apply a contextual type from the Promise-like types from that union instead of seeing the union and giving up early.

**Comment by vilic** [comment]
No longer an issue since 3.8.
