### ISSUE TITLE
Why getCombinedModifierFlags() requires Declaration instead of just Node

### ISSUE THREAD

**Issue by eldargab** [microsoft/TypeScript#30189]
Hello.

I noticed, that `getCombinedModifierFlags(node: Declaration)` can perfectly work with just `node: Node`. Why it requires `Declaration` instead?

As per use case, I'm building a small code generator which analyses some interface definitions and generates boilerplate code and I'd like to check whether definition is exported or not.

**Comment by RyanCavanaugh** [comment]
My reading is that this function only makes sense on declarations - only declarations are affected by their outer declarations' modifiers in the first place.
