### ISSUE TITLE
`umd` format `export as namespace MyLib` does not work without `@types/*`

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#30199]
**TypeScript Version:**  3.4.0-dev.20190302

**Search Terms:** `export as namespace`, `umd`

**Code**

```ts
// file: node_modules/my-lib/index.d.ts , manually added

export = MyLib

export as namespace MyLib

declare namespace MyLib {
  class A {}
}

// file: my-lib.test.ts
const x = new MyLib.A() // umd MyLib does not work here
```

**Expected behavior:**

`export as namespace` works for `umd` format

**Actual behavior:**

There is an error: `error TS2304: Cannot find name 'MyLib'.`

But if I move `node_modules/my-lib/index.d.ts` to `node_modules/@types/my-lib/index.d.ts`, there will be no error any more.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
What does "manually added" mean? Is there a tsconfig file? What is your tsc commandline?

**Comment by JounQin** [comment]
@RyanCavanaugh `my-lib` is a test module, which I manually created in `node_modules` directory.

And my tsc command is simple `tsc my-lib.test`

**Comment by JounQin** [comment]
@RyanCavanaugh 
![image](https://user-images.githubusercontent.com/8336744/59727917-50206600-926a-11e9-9418-6c68e778cd94.png)

**Comment by JounQin** [comment]
I've found out how to make it work: namespaced file should be in a specific .d.ts file with root level declare namespace, and then declare module in another .d.ts file.

```ts
// placeholder.js.d.ts
declare namespace placeholder {
  type PlaceholderOptions = Partial<{
    size: string;
    bgcolor: string;
    color: string;
    text: string;
    fstyle: string;
    fweight: string;
    fsize: string;
    ffamily: string;
  }>;

  interface Placeholder {
    getCanvas(options?: PlaceholderOptions): HTMLCanvasElement;
    getData(options?: PlaceholderOptions): string;
    render(force?: string): void;
  }
}

declare const placeholder: placeholder.Placeholder;

export = placeholder;

export as namespace placeholder;
```

```ts
// typings.d.ts
declare module 'placeholder.js' {
  export = placeholder;
}
```
