### ISSUE TITLE
Decorators used in classes that are returned from arrow functions not valid

### ISSUE THREAD

**Issue by alshdavid** [Microsoft/TypeScript#30195]
I have the following decorator

```typescript
function test(t, key) {
    console.log(t, key)
}
```

When wrapping a class in an arrow function, the compiler tells me that
```
Decorators are not valid here. ts(1206)
```
```typescript
const personCreator = (
    dependencyA: any,
    dependencyB: any
) => class Person {
    @test
    private thing: any

    @test
    private someMethod() {

    }
}
```

However this works
```typescript
const personCreator = (
    dependencyA: any,
    dependencyB: any
) => {
     class Person {
        @test
        private thing: any

        @test
        private someMethod() {

        }
    }
    return Person
}
```

**Comment by ajafff** [comment]
That's not limited to arrow function return.
There are two different flavors of classes: class declarations and class expressions. Typescript only allows decorators in the former. 
This looks intended. Maybe the decorators proposal specified it that way.

**Comment by RyanCavanaugh** [comment]
The error `Decorators are not valid here` is issued because that is not a valid location for a decorator.

**Comment by nin-jin** [comment]
Why?
