### ISSUE TITLE
Poor type inference for unique symbol

### ISSUE THREAD

**Issue by pauldraper** [microsoft/TypeScript#30196]
**TypeScript Version:**  3.3

**Search Terms:** unique symbol, inference, generic

**Code**

```ts
class Item<T> {
    constructor(readonly type: T) {}
}

const a1 = Symbol();
const a1Item = new Item(a1);
const a2 = Symbol();
const a2Item = new Item(a2);

a1Item.type === a2Item.type; // error

const b1Item = new Item(Symbol());
const b2Item = new Item(Symbol());

b1Item.type === b2Item.type; // no error
```

**Expected behavior:**

I expected both `a1Item.type === a2Item.type;` and `b1Item === b2Item;` to produce type errors.

**Actual behavior:**

Only `a1Item.type === a2Item.type;` produces a type error.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=class%20Item%3CT%3E%20%7B%0D%0A%20%20%20%20constructor(readonly%20type%3A%20T)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a1%20%3D%20Symbol()%3B%0D%0Aconst%20a1Item%20%3D%20new%20Item(a1)%3B%0D%0Aconst%20a2%20%3D%20Symbol()%3B%0D%0Aconst%20a2Item%20%3D%20new%20Item(a2)%3B%0D%0A%0D%0Aa1Item.type%20%3D%3D%3D%20a2Item.type%3B%20%2F%2F%20compile%20error%0D%0A%0D%0Aconst%20b1Item%20%3D%20new%20Item(Symbol())%3B%0D%0Aconst%20b2Item%20%3D%20new%20Item(Symbol())%3B%0D%0A%0D%0Ab1Item.type%20%3D%3D%3D%20b2Item.type%3B%20%2F%2F%20no%20compile%20error%0D%0A)

**Related Issues:** -

---

No amount of only type annotations is able to make the second example work like the first (casting, explicit types, etc.).

**Comment by RyanCavanaugh** [comment]
The uniqueness of a symbol is tracked through its declaration, and there's no declaration for the `Symbol()` expression in the argument positions. Supporting arbitrary locations of unique symbols isn't something we intend to tackle given the complexity required vs the value it'd deliver.
