### ISSUE TITLE
[COMPILER API] ts.setSyntheticLeadingComments doesn't remove existing comments

### ISSUE THREAD

**Issue by Weakky** [microsoft/TypeScript#30191]
## Description

Hey there,

I'm trying to build something that would add comments on top of a function.
Unfortunately, it seems like `ts.setSyntheticLeadingComments` does not allow me to replace existing comments.

I have tried:

- `ts.setSyntheticLeadingComments(node, [])`
- `ts.setSyntheticLeadingComments(node, undefined)`
- `node = ts.setSyntheticLeadingComments(node, [])`

But none of these works. Ultimately, my goal was to be able to replace existing comments that I would have generated by the new ones.

Any idea ? Thanks 🙏

## Reproduction

```ts
const transformFactory = (context: ts.TransformationContext) => (
  rootNode: ts.SourceFile
): ts.SourceFile => {
  const visit = (node: ts.Node) => {
    node = ts.visitEachChild(node, visit, context);

    ts.setSyntheticLeadingComments(node, []);

    return node;
  };

  return ts.visitNode(rootNode, visit);
};

const sourceFile = ts.createSourceFile(
  path,
  source,
  ts.ScriptTarget.ESNext,
  true,
  ts.ScriptKind.TS
);
const result = ts.transform(sourceFile, [transformFactory]);
const resultPrinter = ts.createPrinter({ removeComments: false });

console.log(resultPrinter.printFile(result.transformed[0]));
```

Try the following transformer, and see how no comments are removed at all

Using `ts.createPrinter(..., { substituteNode(hint, node) { ... } })` doesn't help either

## Side note

It seems like `ts.getSyntheticLeadingComments()` doesn't work the way I expect it to either. It always returns `undefined`, which lead me to use the following utils although I'm not sure to entirely understand the purpose of it (borrowed from https://github.com/angular/tsickle/blob/6f5835a644f3c628a61e3dcd558bb9c59c73dc2f/src/transformer_util.ts#L257-L266)

```ts
/**
 * A replacement for ts.getLeadingCommentRanges that returns the union of synthetic and
 * non-synthetic comments on the given node, with their text included. The returned comments must
 * not be mutated, as their content might or might not be reflected back into the AST.
 */
export function getAllLeadingComments(node: ts.Node):
    ReadonlyArray<Readonly<ts.CommentRange&{text: string}>> {
  const allRanges: Array<Readonly<ts.CommentRange&{text: string}>> = [];
  const nodeText = node.getFullText();
  const cr = ts.getLeadingCommentRanges(nodeText, 0);
  if (cr) allRanges.push(...cr.map(c => ({...c, text: nodeText.substring(c.pos, c.end)})));
  const synthetic = ts.getSyntheticLeadingComments(node);
  if (synthetic) allRanges.push(...synthetic);
  return allRanges;
}
```

**Comment by Weakky** [comment]
### UPDATE

Seems like this is working with the `ts.transform` API.

Keeping the issue opened for some explananation 🙏

**Comment by RyanCavanaugh** [comment]
`setSyntheticLeadingComments` doesn't affect existing comments, because existing comments are not synthetic.

The use case for the function is this:
```ts
/** Neat */
class A {

}
```
generates
```ts
/** Neat */
var A = /** @class */ (function () {
    function A() {
    }
    return A;
}());
```
Keeping the `/** Neat */` comment there is 100% intentional - the synthetic comments are purely additive.

**Comment by dragomirtitian** [comment]
@RyanCavanaugh  I suggested using `setTextRange` in the [SO version of this question](https://stackoverflow.com/questions/55172827/ts-setsyntheticleadingcomments-doesnt-remove-existing-comments/55173278#55173278). In the code there I use `setTextRange` to set the full start of the node with the value of the actual start of the node (`node.getStart()`).

This seems to exclude the comments but I was wondering if it is a "sactioned" use of `setTextRange`
