### ISSUE TITLE
typescript not finding break in interface when type constructed from conditional type

### ISSUE THREAD

**Issue by dagda1** [Microsoft/TypeScript#30198]
**TypeScript Version:** 

3.3.1

**Search Terms:**
conditional types default
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
I want to give the user the ability to supply their own interface or default to a different structure:
```
export interface Config {
  [key: string]:
    | number[]
    | string[]
    | number
    | string
}


export type AddArrayLike<T> = unknown extends T ? Config | Config[] : {
  [P in keyof T]: T[P] | T[P][]
}

export interface INodeGroupProps<T = unknown, State = unknown> {
  data: T[];
  keyAccessor: (data: T, index: number) => string | number;
  start: (data: T, index: number) => unknown extends State ? Config : State;
  enter?: (data: T, index: number) => AddArrayLike<State>;
  update?: (data: T, index: number) => AddArrayLike<State>;
  leave?: (data: T, index: number) => AddArrayLike<State>;
}
```
So I have a State type argument that defaults to unknown. If it is unknown then it should be Config.

Everything works fine in this example of supplying your own State.
```
export type Point = {x: number, y: number};

export interface NodesState {
  top: number;
  left: number;
  opacity: number;
}

const points: Point[] = [
  {x: 0, y: 0},
  {x: 1, y: 2},
  {x: 2, y: 3}
] 

const Test: INodeGroupProps<Point, NodesState> = {
    data: points,
    keyAccessor: (d) => {
    return d.x
    },
    start: (point) => {
        return {
            top: point.y,
            left: point.x,
            opacity: 0
        };
    },
    enter: (point) => {
        return {
            top: [point.y],
            left: [point.x],
            opacity: [0]
        };
    },
    update: (point) => {
        return {
            top: [point.y],
            left: [point.x],
            opacity: 0
        };
    },
    leave: (point) => {
        return {
            top: [point.y],
            left: [point.x],
            opacity: 0
        };
    },
};
```
I get type safety if I change one of the types from the NodeState interface to be not a number, e.g.
```
return {
  top,
  left,
  opacity: true
};
```
But if I add a prop that is not part of the NodeState interface then this is not recognised as a break.

e.g.
```
return {
  top,
  left,
  opacity: 0,
  fook: 'blah' // not part of NodeState
};
```

**Expected behavior:**

`fook` should be identified as not part of the `NodeState` interface

**Actual behavior:**

No type error

**Playground Link:** 

[playground](https://www.typescriptlang.org/play/#src=export%20interface%20Config%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%0D%0A%20%20%20%20%7C%20number%5B%5D%0D%0A%20%20%20%20%7C%20string%5B%5D%0D%0A%20%20%20%20%7C%20number%0D%0A%20%20%20%20%7C%20string%0D%0A%7D%0D%0A%0D%0A%0D%0Aexport%20type%20AddArrayLike%3CT%3E%20%3D%20unknown%20extends%20T%20%3F%20Config%20%7C%20Config%5B%5D%20%3A%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20%7C%20T%5BP%5D%5B%5D%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20INodeGroupProps%3CT%20%3D%20unknown%2C%20State%20%3D%20unknown%3E%20%7B%0D%0A%20%20data%3A%20T%5B%5D%3B%0D%0A%20%20keyAccessor%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20string%20%7C%20number%3B%0D%0A%20%20start%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20unknown%20extends%20State%20%3F%20Config%20%3A%20State%3B%0D%0A%20%20enter%3F%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20AddArrayLike%3CState%3E%3B%0D%0A%20%20update%3F%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20AddArrayLike%3CState%3E%3B%0D%0A%20%20leave%3F%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20AddArrayLike%3CState%3E%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Point%20%3D%20%7Bx%3A%20number%2C%20y%3A%20number%7D%3B%0D%0A%0D%0Aexport%20interface%20NodesState%20%7B%0D%0A%20%20top%3A%20number%3B%0D%0A%20%20left%3A%20number%3B%0D%0A%20%20opacity%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aconst%20points%3A%20Point%5B%5D%20%3D%20%5B%0D%0A%20%20%7Bx%3A%200%2C%20y%3A%200%7D%2C%0D%0A%20%20%7Bx%3A%201%2C%20y%3A%202%7D%2C%0D%0A%20%20%7Bx%3A%202%2C%20y%3A%203%7D%0D%0A%5D%20%0D%0A%0D%0Aconst%20Test%3A%20INodeGroupProps%3CPoint%2C%20NodesState%3E%20%3D%20%7B%0D%0A%20%20%20%20data%3A%20points%2C%0D%0A%20%20%20%20keyAccessor%3A%20(d)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20d.x%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20start%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20point.y%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20point.x%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%200%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20enter%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%5Bpoint.y%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%5Bpoint.x%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%20%5B0%5D%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20update%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%5Bpoint.y%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%5Bpoint.x%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%200%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20leave%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%5Bpoint.y%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%5Bpoint.x%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%200%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20fook%3A%20'blah%20blah'%20%20%2F%2F%20not%20part%20of%20node%20state%20but%20no%20error%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%7D%3B%0D%0A%0D%0A%0D%0A%0D%0A)

**Related Issues:**

**Comment by jack-williams** [comment]
Duplicate of #241 / #29390. Excess property checking isn't being performed in the body of the function expression. Smaller repro:
```ts
interface Foo {
  x: () => { x: 'hello' };  
}

const a: Foo = {
  x: () => {
    return { x: 'hello', excess: 3 }; // no error
  }
}
```

**Comment by dagda1** [comment]
@jack-williams I see they use neverize as one solution.

Is this possible, I tried [this](https://www.typescriptlang.org/play/#src=export%20interface%20Config%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%0D%0A%20%20%20%20%7C%20number%5B%5D%0D%0A%20%20%20%20%7C%20string%5B%5D%0D%0A%20%20%20%20%7C%20number%0D%0A%20%20%20%20%7C%20string%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20NodesState%20%7B%0D%0A%20%20top%3A%20number%3B%0D%0A%20%20left%3A%20number%3B%0D%0A%20%20opacity%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Neverise%3CA%20extends%20%7B%7D%2C%20B%20extends%20%7B%7D%3E%20%3D%20%7B%0D%0A%20%20%20%5BP%20in%20keyof%20B%5D%3A%20P%20extends%20keyof%20A%20%3F%20(B%5BP%5D%20extends%20A%5BP%5D%20%7C%20undefined%20%3F%20A%5BP%5D%20%3A%20never)%20%3A%20never%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20AddArrayLike%3CT%3E%20%3D%20unknown%20extends%20T%20%3F%20Config%20%7C%20Config%5B%5D%20%3A%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20%7C%20T%5BP%5D%5B%5D%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20INodeGroupProps%3CT%20%3D%20unknown%2C%20State%20%3D%20unknown%3E%20%7B%0D%0A%20%20data%3A%20T%5B%5D%3B%0D%0A%20%20keyAccessor%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20string%20%7C%20number%3B%0D%0A%20%20start%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20unknown%20extends%20State%20%3F%20Config%20%3A%20State%20%26%20Neverise%3CState%2C%20%7Btop%3A%20number%2C%20left%3A%20number%2C%20opacity%3A%20number%7D%3E%3B%0D%0A%20%20enter%3F%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20AddArrayLike%3CState%3E%0D%0A%20%20update%3F%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20AddArrayLike%3CState%3E%3B%0D%0A%20%20leave%3F%3A%20(data%3A%20T%2C%20index%3A%20number)%20%3D%3E%20AddArrayLike%3CState%3E%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Point%20%3D%20%7Bx%3A%20number%2C%20y%3A%20number%7D%3B%0D%0A%0D%0Aconst%20points%3A%20Point%5B%5D%20%3D%20%5B%0D%0A%20%20%7Bx%3A%200%2C%20y%3A%200%7D%2C%0D%0A%20%20%7Bx%3A%201%2C%20y%3A%202%7D%2C%0D%0A%20%20%7Bx%3A%202%2C%20y%3A%203%7D%0D%0A%5D%20%0D%0A%0D%0Aconst%20Test%3A%20INodeGroupProps%3CPoint%2C%20NodesState%3E%20%3D%20%7B%0D%0A%20%20%20%20data%3A%20points%2C%0D%0A%20%20%20%20%20%20%20%20keyAccessor%3A%20(d)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20d.x%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20start%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20point.y%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20point.x%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%200%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20enter%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%5Bpoint.y%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%5Bpoint.x%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%20%5B0%5D%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20update%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%5Bpoint.y%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%5Bpoint.x%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%20%5B0%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20fook%3A%20'fuck'%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20shite%3A%20'cumt'%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20leave%3A%20(point)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%5Bpoint.y%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%5Bpoint.x%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%20%5B0%5D%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%7D%3B%0D%0A%0D%0A%0D%0A%0D%0A) but the extra properties are not flagged.
