### ISSUE TITLE
[TypeScript compiler Bug?] subclass function return value's specific type incorrectly recongnized as parent interface more general return type

### ISSUE THREAD

**Issue by reactma** [Microsoft/TypeScript#30197]
I am developing a tiny Option/Either library and found out this problem. Not sure if it is a bug with TypeScript compiler.

TSC version: 3.0.3

The observation here is that the line `console.log('plusedA is Option? ', plusedA instanceof Option)` says `plusedA is Option ? true`

but when I add following line `const ra = plusedA.get()`, compiler complained: `error TS2339: Property 'get' does not exist on type 'Applicative<any>'.`

When I explicitly cast it to Option, as `const ra = (plusedA as Option<number>).get()`. Compilation passed and code worked as expected.

The test code:

```
const triplePlusF = (a: number) => (b: number) => (c: number) => a + b + c
const triplePlus = new Some(triplePlusF)
const a = new Some(2)
const b = new Some(3)
const c = new Some(4)
const d = new None()

const plusedA = triplePlus
  .applyMap(a)
  .applyMap(b)
  .applyMap(c) // plusdA = Some( 2 + 3 + 4 )

console.log(plusedA) // plusedA = Some(9)

console.log('plusedA is Option? ', plusedA instanceof Option)
const ra = plusedA.get() // Compilation error: error TS2339: Property 'get' does not exist on type 'Applicative<any>'.
const ra = (plusedA as Option<number>).get() // works
console.log(ra)

```

Below is the code for the Option library. [typecat](https://github.com/reactma/typecat)

```
export const id = (a: any) => a

export interface Functor<T> {
  fmap<S>(f: (a: T) => S): Functor<S>
}

export interface Applicative<T> extends Functor<T> {
  applyMap(a: Applicative<T>): Applicative<any>
}

export interface Monad<T> extends Applicative<T> {
  flatMap<S>(f: (a: T) => Monad<S>): Monad<S>
}

export abstract class Option<T> implements Monad<T> {
  abstract _value?: T
  abstract fmap<S>(f: (a: T) => S): Functor<S>
  abstract applyMap(a: Applicative<T>): Applicative<any>
  abstract flatMap<S>(f: (a: T) => Monad<S>): Monad<S>
  abstract [Symbol.iterator](): IterableIterator<T>
  abstract get(): T
  abstract getOrElse(defaultValue: T): T
}

export class Some<T> extends Option<T> {
  _value?: T
  constructor(a: T) {
    if (a === undefined || a === null)
      throw TypeError("Some can't be initated with undefined or null")

    super()
    this._value = a
  }

  fmap<S>(f: (a: T) => S): Some<S> {
    return new Some<S>(f(this._value!))
  }

  applyMap(a: Option<any>): Option<any> {
    if (a instanceof None) return new None()

    const f = (this as any)._value as (a: any) => any

    return new Some(f!(a._value))
  }

  flatMap<S>(f: (a: T) => Option<S>): Option<S> {
    return f(this._value!)
  }

  get(): T {
    return this._value!
  }

  getOrElse(defaultValue: T): T {
    return this._value!
  }

  *[Symbol.iterator](): IterableIterator<T> {
    yield this._value!
  }
}

export class None<T = any> extends Option<T> {
  _value?: T
  constructor() {
    super()
  }

  fmap<S>(f: any): Some<S> {
    return new None()
  }

  applyMap(a: any): Option<any> {
    return new None()
  }

  flatMap(f: any): Option<any> {
    return new None()
  }

  get(): T {
    throw TypeError('Value not exist in None')
  }

  getOrElse(defaultValue: T): T {
    return defaultValue
  }

  *[Symbol.iterator](): IterableIterator<T> {
    return
  }
}
```

**Comment by jack-williams** [comment]
This doesn't look like a bug. The return values in your class:
```ts
export abstract class Option<T> implements Monad<T> {
  abstract _value?: T
  abstract fmap<S>(f: (a: T) => S): Functor<S>
  abstract applyMap(a: Applicative<T>): Applicative<any>
  abstract flatMap<S>(f: (a: T) => Monad<S>): Monad<S>
  abstract [Symbol.iterator](): IterableIterator<T>
  abstract get(): T
  abstract getOrElse(defaultValue: T): T
}
```
are returning the interface type, not the `Option` type. As soon you you call `applyMap` on an `Option` you get back an `Applicative`, losing the type `Option`.

If you write:
```ts
export abstract class Option<T> implements Monad<T> {
  abstract _value?: T
  abstract applyMap(a: Applicative<T>): Option<any>
}
```
then you wont lose the `Option` type.

The issue tracker is not really meant for general questions. I would recommend trying StackOverflow first; @dragomirtitian or @jcalz will give better answers than me there anyway. If it really does start to look like a language bug then the issue tracker is correct location.

**Comment by reactma** [comment]
@jack-williams applyMap is called at the type Some according to the test code. And Some's applyMap signature is `applyMap(a: Option<any>): Option<any>`. I suppose the return type should be Option.
And also it is inconsistent between run-time `instanceof` type check and compiler type check. 

But after I changed the signature of applyMap defined at Option to `abstract applyMap(a: Option<T>): Option<any>`, the compiler stop complaining. 

And thanks for the advice on where to post the issue. It is the inconsistency between `instanceof` type check and compiler that made me wondering if it is a bug.

**Comment by RyanCavanaugh** [comment]
In general 60+-line reports are due to user confusion, not type system bugs.

If you track this down to what you believe to be a bug, please post a *small* repro.
