### ISSUE TITLE
outFile may reference invalid files

### ISSUE THREAD

**Issue by Tiross** [microsoft/TypeScript#30206]
**TypeScript Version:**  
- 3.3.3
- 3.4.0-dev.20190302

**Search Terms:**
- amd
- outFile

**Code**

```ts
// File test.ts
import './polyfill';

class A {
}

export default A;
```

```ts
// File polyfill.ts
interface ArrayConstructor {
  from (source: any): any[];
}

if (!Array.from) {
  // Code based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from
}
```

```json
{
  "compilerOptions": {
    "module": "amd",
    "outFile": "./out.js"
  },
  "files": [
    "test.ts"
  ]
}
```

**Actual behavior:**
Out file contains an include to an external (and not rendered) file.
```js
define("test", ["require", "exports", "./polyfill"], function (require, exports) {
  // ...
});
```

Actual rendered code
```js
if (!Array.from) {
    // Code based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from
}
define("test", ["require", "exports", "./polyfill"], function (require, exports) {
    "use strict";
    exports.__esModule = true;
    var A = /** @class */ (function () {
        function A() {
        }
        return A;
    }());
    exports["default"] = A;
});

```

**Expected behavior:**
No external reference.

```js
if (!Array.from) {
    // Code based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from
}
define("test", ["require", "exports"], function (require, exports) {
    "use strict";
    exports.__esModule = true;
    var A = /** @class */ (function () {
        function A() {
        }
        return A;
    }());
    exports["default"] = A;
});

```

**Comment by RyanCavanaugh** [comment]
A few things are going on here to produce this outcome.

`import "./polyfill";` - this import "should" fail because there's no module with this name, but we don't issue errors on bare imports such as this one (i.e. those which don't create local identifiers)

The polyfill file is not a module because it doesn't contain any imports or exports, so is global code (which is correctly placed at the top-level of the outfile)

The `polyfill.ts` file should just have an `export {};` statement in it.

**Comment by Tiross** [comment]
> `import "./polyfill";` - this import "should" fail because there's no module with this name, but we don't issue errors on bare imports such as this one (i.e. those which don't create local identifiers)

Can't you emit a warning for this case ? 

> The polyfill file is not a module because it doesn't contain any imports or exports, so is global code (which is correctly placed at the top-level of the outfile)
> 
> The `polyfill.ts` file should just have an `export {};` statement in it if you want the output described in the OP

With an `export {}`, compiler shows 2 errors:

```sh
polyfill.ts:8:14 - error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.

8   if (!Array.from) {
               ~~~~

polyfill.ts:9:11 - error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.

9     Array.from = (() => {
            ~~~~


Found 2 errors.
```

The out file shows now a module "polyfill".
