### ISSUE TITLE
Typescript crashes in watch mode

### ISSUE THREAD

**Issue by hediet** [Microsoft/TypeScript#30201]
**TypeScript Version:**  3.3.1 - 3.4.0-dev.20190302

**Code**
https://github.com/hediet/ts-typed-sql/tree/ts-bug

**Expected behavior:**
`tsc --watch` does not crash.

**Actual behavior:**
`tsc --watch` crashes:
![image](https://user-images.githubusercontent.com/2931520/53696252-7ad2d580-3dc5-11e9-990b-acf703311a72.png)

**Comment by DanielRosenwasser** [comment]
Likely a declaration emit bug based on the call stack.
