### ISSUE TITLE
Get type of variable over the course of lifetime from TypeChecker

### ISSUE THREAD

**Issue by eatonphil** [microsoft/TypeScript#30202]
Calling `getTypeAtLocation().getFlags()` on  the identifier `b` at its declaration in the following example returns `ts.TypeFlags.Number` however the type (to me) should be `ts.TypeFlags.Number` or `ts.TypeFlags.Any` since it is later reassigned to a variable of unknown type.

```
function a(c) { // c is implicit any
  let b = 1; // getTypeAtLocation(b).getFlags() is ts.TypeFlags.Number
  b = c; // getTypeAtLocation(b = c).getFlags() is no longer ts.TypeFlags.Number
}
```

Is it possible to get this information at the declaration of `b` or do I need to accumulate this type information myself?

**Comment by DanielRosenwasser** [comment]
I'm not totally clear on the intent but if you're asking about the type of `b = c`, that's because the `=` operator always returns the left-hand side.

**Comment by eatonphil** [comment]
I'm going to change the example slightly but the intent is still the same. The inferred type of `b` in this example should be `number | string` (or `any`, I guess). Because the following would be right:

```javascript
function a(c: string) {
  let b: number | string = 1;
  b = c;
}
```

And the following would be wrong:

```javascript
function a(c: string) {
  let b: number = 1;
  b = c;
}
```

But whether I explicitly annotate the type of `b` as `b: string | number` at the declaration or not, I cannot seem to get that information from the TypeChecker via `getTypeAtLocation()`.

Does that make sense?

**Comment by RyanCavanaugh** [comment]
There isn't an API that's going to give you answer you want there, because TypeScript's inference algorithm doesn't work like that. You'd have to accumulate the RHSes of all assignments yourself to get the `number | string` result.

**Comment by eatonphil** [comment]
Got it, thank you!
