### ISSUE TITLE
An instance of parent class is returned while calling new on child class.

### ISSUE THREAD

**Issue by RedTailBullet** [Microsoft/TypeScript#30204]
**TypeScript Version:**  3.3.3333

**Search Terms:** new, child class, parent class, inherit.

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
class HttpError extends Error {
  status: number;

  constructor(message?: string, status: number = 500) {
    super(message);
    this.status = status;
  }
}

const error = new HttpError();

if (error instanceof HttpError) {
  console.log("Got an instance of HttpError");
} else if (error instanceof Error) {
  console.log("Got an instance of Error");
} else {
  console.log("Got something that's not an instance of HttpError or Error");
  
}
```

**Expected behavior:**
It logs out "Got an instance of HttpError".

**Actual behavior:**
It logs out "Got an instance of Error".

**Playground Link:** 
https://www.typescriptlang.org/play/#src=class%20HttpError%20extends%20Error%20%7B%0D%0A%20%20status%3A%20number%3B%0D%0A%0D%0A%20%20constructor(message%3F%3A%20string%2C%20status%3A%20number%20%3D%20500)%20%7B%0D%0A%20%20%20%20super(message)%3B%0D%0A%20%20%20%20this.status%20%3D%20status%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20error%20%3D%20new%20HttpError()%3B%0D%0A%0D%0Aif%20(error%20instanceof%20HttpError)%20%7B%0D%0A%20%20console.log(%22Got%20an%20instance%20of%20HttpError%22)%3B%0D%0A%7D%20else%20if%20(error%20instanceof%20Error)%20%7B%0D%0A%20%20console.log(%22Got%20an%20instance%20of%20Error%22)%3B%0D%0A%7D%20else%20%7B%0D%0A%20%20console.log(%22Got%20something%20that's%20not%20an%20instance%20of%20HttpError%20or%20Error%22)%3B%0D%0A%20%20%0D%0A%7D

**Related Issues:** 
Not really.

**Comment by j-oliveras** [comment]
See [Why doesn't extending built-ins like Error, Array, and Map work?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work).

**Comment by RedTailBullet** [comment]
@j-oliveras Right then... Thanks.
