### ISSUE TITLE
100% CPU when installing node_modules while a file is open

### ISSUE THREAD

**Issue by phil294** [microsoft/TypeScript#30208]
**TypeScript Version:**  typescript@3.4.0-dev.20190302

**Search Terms:** tsserver cpu ember reload

**Steps to reproduce**

This is super-verbose; the relevant steps are bold and should be easy to reproduce

- Tested in MacOS
- Clone https://github.com/phil294/tsserver_lag_demo2. (It includes just a few dependencies with which the issue can be reproduced)
- Open it up in vscode
- Open process explorer so you can see the CPU usage of `tsserver`
- Do *not* open `main.js` (if you already have, close the tab & reload)
- Run `rm -rf node_modules && yarn`
- Wait for it to finish
- Open `main.js`
- `tsserver` cpu goes up to 50% for ~1 second. *This is how it should be*
- **Keep `main.js` open**
- **Run `rm -rf node_modules && yarn`**
- **Wait for it to finish**

**Expected behavior:**

`tsserver` should not go mad

**Actual behavior:**

`tsserver` cpu goes up to 100% and stays like this for a long time. It varies, but I've had both 30 seconds and 15 minutes. It renders the entire intellisense and go-to mechanics useless. Reinstalling `node_modules` is one of the most common things to do in a JS/TS project. This bug makes developing Ember.js applications with vscode & typescript intellisense support effectively impossible. For example, in our team, we all had to go back to Sublime Text because of this. The CPU usage is probably related to some dependency in package.json, but I have not been able to narrow it down. Either way, it is a Typescript bug.

**Related Issues:**
There are multiple tsserver CPU related issues. [This](https://github.com/Microsoft/TypeScript/issues/25629) one was the most similar but is missing details and is also closed, so probably not related.

**Comment by sheetalkamat** [comment]
@phil294 Would you be able to try out https://github.com/microsoft/TypeScript/pull/35615#issuecomment-564263744 to see if it helps.
