### ISSUE TITLE
For `T extends M` where `M` is a mapped type, `T[keyof T]` doesn't consider `M` 

### ISSUE THREAD

**Issue by rkirov** [microsoft/TypeScript#30217]
**TypeScript Version:**  3.4.0-dev.201xxxxx and 3.3.3333 (used to work in TS 3.2)

**Search Terms:** Mapped type, T[keyof T]

**Code**

```ts
// Takes type -> {a: string}
// returns type -> {a: string | null} 
type Nullable<T extends object> = {
  [P in keyof T]: T[P] | null;
};

// This function should only accept objects, such that all props can be assigned null.
function f<T extends Nullable<T>>(t: T, key: keyof T) {
  let x = t[key];
  x = null;
}
```

**Expected behavior:**
`x = null` to be accepted as T's lower type bound is `Nullable<_>` thus all properties have `| null`.

**Actual behavior:**
This was accepted up to TS 3.2, but started erring with TS 3.3 with the error:

```
ERROR(11,3): : Type 'null' is not assignable to type 'T[keyof T]'.
```

** Some notes **
There is nothing special about `Nullable`, same error happens with other mapped types.

This is not my code and there is a valid question why even bother writing `f` as written, since TS accepts:
```ts
let x: {a: string} = {a: ''}; 
f(x, 'a');
```
I.e. the `Nullable` lower bound doesn't seem to be checked at the call-site.

**Comment by weswigham** [comment]
You have your bounds confused - `extends Nullable<O>` doesn't force the properties of `T` to include `null`, it merely states that they _can_ - this is a valid instantiation of `f`:
```ts
f<{ x: string }, { x: string }>({x: ""}, "x");
```
the argument for `T` does not allow `x` to be `null` - allowing the assignment within the body would be erroneous.

**Comment by jack-williams** [comment]
This checks the call site, but does not work correctly in the body.
```ts
function f<T extends [Record<keyof T, null>] extends [T] ? unknown : never>(t: T, key: keyof T) {
  let x = t[key];
  x = null;
}
```

**Comment by rkirov** [comment]
@weswigham My bad, I had I typo, I should read `extends Nullable<T>`. Fixed the description, still succeeds in TS 3.2 and fails in TS 3.3

**Comment by rkirov** [comment]
> You have your bounds confused - extends Nullable<O> doesn't force the properties of T to include null, it merely states that they can - this is a valid instantiation of f:

I think I see your reasoning here. Let me try to paraphrase it (please correct me if you meant something else):

For a concrete type, e.g. `type A = {a: string}`, `Nullable<A> = {a: string | null}`, so `Nullable<A>` is the supertype and `A` is the subtype, thus `A extends Nullable<A>`. In fact that is trivially true for every type A, the bound doesn't put any constraint on A. Given that A is any type, it is reasonable to reject setting a prop to `null`.

But, I can't seem to square off that reasoning with the following simpler behavior in TS (which succeeds without an error): 

```ts
function f<T extends {a:string|null}>(x: T) {
  x.a = null;
}

f<{a: string}>({a: ''});
```

**Comment by rkirov** [comment]
Also, maybe important for the discussion - I am not emotionally invested in this pattern (or https://github.com/Microsoft/TypeScript/issues/30218). These are just the only two errors we saw went we upgrade google's internal codebase to TS 3.3.3333 from TS3.2.

**Comment by rkirov** [comment]
I found another instance, of what I think is the same issue in our codebase:

```ts
export function setValue<V, T extends {[KeyT in keyof T]: V}>(
    obj: T, key: keyof T, value: V) {
  obj[key] = value;
}
```

I tried to narrow it down so it is more readable at a glance, but let me know if you prefer the "real-world" code to understand why the devs are even writing these type of types.

**Comment by jack-williams** [comment]
I think the root of the issue might be this fix PR #27490?

**Comment by weswigham** [comment]
Probably, yeah. @rikov isn't this the much simpler way to write that?:
```ts
export function setValue<T, K extends keyof T>(
    obj: T, key: K, value: T[K]) {
  obj[key] = value;
}
```
as written, that `setValue` can be invoked with type params which would make that assignment unsound, eg:
```ts
export function setValue<V, T extends {[KeyT in keyof T]: V}>(
    obj: T, key: keyof T, value: V) {
  obj[key] = value;
}

setValue<number, { "ok": 6 }>({ ok: 6 }, "ok", 0); // allows setting `0` because `V` can be less specialized than T[keyof T]
```

**Comment by weswigham** [comment]
By the way, as for a way to write your original example in a typesafe way:
```ts
function f<K extends string | number | symbol>(
    t: Record<K, null>,
    key: K
) {
  let x = t[key];
  x = null;
}
```
should work?

**Comment by agopshi** [comment]
@weswigham 

> Probably, yeah. @Rikov isn't this the much simpler way to write that?:
> 
> ```ts
> export function setValue<T, K extends keyof T>(
>     obj: T, key: K, value: T[K]) {
>   obj[key] = value;
> }
> ```
> 

The real world example is this utility function:

```ts
export function appendToOptionalArray<
    K extends string, V, U extends V, T extends {[KeyT in K]?: V[]}>(
    object: T, key: K, value: U) {
  const array = object[key];
  if (array) {
    array.push(value);
  } else {
    object[key] = [value] as unknown as T[K];
  }
}

// e.g.
const foo: {x?: number[]; y?: string[]; } = {};
appendToOptionalArray(foo, 'x', 123);
appendToOptionalArray(foo, 'y', 'bar');
```

What's to correct way to rewrite this?

**Comment by rkirov** [comment]
Thanks, #27490 provides enough context for me to understand what is changing and why. The change in TS3.3.3333 is intentional and there is a soundness justification for it. It is surprising that it only affects `T[keyof T]` types.

In terms of impact this affected 3 code locations in our giant repo, so as far as I am concerned this is a very minor change.

@agopshi is one of the original authors of one of the affected code snippetes, so you can continue the discussion on a proper way to express the authors intent in types.

**Comment by weswigham** [comment]
@agopshi I'd have written it like so:
```ts
// Using a homomorphic mapped type over `T`
// Produces a lower-priority inference for `T` than other
// positions, allowing one to override the priority the argument
// order would usually imply
type Lower<T> = { [K in keyof T]: T[K] };

export function appendToOptionalArray<
  K extends string | number | symbol,
  T
>(
  object: { [x in K]?: Lower<T>[] },
  key: K,
  value: T
) {
  const array = object[key];
  if (array) {
    array.push(value);
  } else {
    object[key] = [value];
  }
}

// e.g.
const foo: {x?: number[]; y?: string[]; } = {};
appendToOptionalArray(foo, 'x', 123);   // ok
appendToOptionalArray(foo, 'y', 'bar'); // ok
appendToOptionalArray(foo, 'y', 12);    // should fail
appendToOptionalArray(foo, 'x', "no");  // should fail
```
(and I will fully admit that knowing how to create a lower priority inference target is arcane typesystem knowledge) - except doing so has exposed a bug in our inference algorithm (where successive inferences higher-priority to the same type parameter fail to reset the flag used to control inference result literal-ness), which I've opened #30265 to fix.

Anyways, the core of it is that you can't let the type of `object` itself be generic, because then the members would be allowed to vary to subtypes of array (which is why attempting to assign an array should fail) - so you need to describe the shape of the relevant part of `object` instead, without letting `object` be a type parameter itself.

**Comment by agopshi** [comment]
@weswigham Hm... so, if I understand correctly, your example [doesn't currently work either](https://www.typescriptlang.org/play/#src=%2F%2F%20Using%20a%20homomorphic%20mapped%20type%20over%20%60T%60%0D%0A%2F%2F%20Produces%20a%20lower-priority%20inference%20for%20%60T%60%20than%20other%0D%0A%2F%2F%20positions%2C%20allowing%20one%20to%20override%20the%20priority%20the%20argument%0D%0A%2F%2F%20order%20would%20usually%20imply%0D%0Atype%20Lower%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20%7D%3B%0D%0A%0D%0Aexport%20function%20appendToOptionalArray%3C%0D%0A%20%20K%20extends%20string%20%7C%20number%20%7C%20symbol%2C%0D%0A%20%20T%0D%0A%3E(%0D%0A%20%20object%3A%20%7B%20%5Bx%20in%20K%5D%3F%3A%20Lower%3CT%3E%5B%5D%20%7D%2C%0D%0A%20%20key%3A%20K%2C%0D%0A%20%20value%3A%20T%0D%0A)%20%7B%0D%0A%20%20const%20array%20%3D%20object%5Bkey%5D%3B%0D%0A%20%20if%20(array)%20%7B%0D%0A%20%20%20%20array.push(value)%3B%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20object%5Bkey%5D%20%3D%20%5Bvalue%5D%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20e.g.%0D%0Aconst%20foo%3A%20%7Bx%3F%3A%20number%5B%5D%3B%20y%3F%3A%20string%5B%5D%3B%20%7D%20%3D%20%7B%7D%3B%0D%0AappendToOptionalArray(foo%2C%20'x'%2C%20123)%3B%20%20%20%2F%2F%20ok%0D%0AappendToOptionalArray(foo%2C%20'y'%2C%20'bar')%3B%20%2F%2F%20ok%0D%0AappendToOptionalArray(foo%2C%20'y'%2C%2012)%3B%20%20%20%20%2F%2F%20should%20fail%0D%0AappendToOptionalArray(foo%2C%20'x'%2C%20%22no%22)%3B%20%20%2F%2F%20should%20fail), right?

Is there a way to write this - right now - that works, and is more correct than `[value] as unknown as T[]`?

Lastly, is there documentation on lower priority inference targets? A quick search reveals a StackOverflow answer that quotes #14829 in a not-so-reassuring way: _"I would move this from the "definitely don't depend on this" column to the "it's probably going to work for the foreseeable future" column."_

**Comment by weswigham** [comment]
The code I wrote above should work just dandy in the next nightly and beyond. 💓

**Comment by weswigham** [comment]
> Lastly, is there documentation on lower priority inference targets?

We've never formalized it, since we've oft debated making an explicit `noinfer` position which would be preferable in the future.
