### ISSUE TITLE
Getting "Maximum call stack size exceeded" when using "getDocumentHighlights" with reference paths and modules in 1.5.0-beta

### ISSUE THREAD

**Issue by gscshoyru** [Microsoft/TypeScript#3021]
If I have code that looks something like this: 

```typescript
/// <reference path="nounreachable.test.ts" />

module S {
  var template = '';
}
```

and I try to do getDocumentHighlights on "template" in just that one file, I get a "Maximum call stack size exceeded" error. Am I doing something wrong? Or can you guys fix this, please? Thanks!

**Comment by DanielRosenwasser** [comment]
Hey @gscshoyru, is the definition file required to reproduce this error?

**Comment by gscshoyru** [comment]
The definition file isn't necessary, it's just the existence of a reference path that causes the bug. It's the combination of the module and the reference path that does it for some reason, if you don't have have one or the other the bug doesn't happen.

**Comment by DanielRosenwasser** [comment]
Got it, I'll try to look into it as soon as I get in.

**Comment by DanielRosenwasser** [comment]
Not able to repro - can you supply both a call stack and the original call that's triggering it? What set of parameters are you passing in when calling?

**Comment by gscshoyru** [comment]
Ok, sorry, I apparently I copied the wrong thing since it was failing that way before. Now it's failing if there's a ../ in the reference path, like ```/// <reference path="../nounreachable.test.ts" /> ```. It may also have something to with how we're doing it, though, since we are creating our own language service host and whatnot -- I can add the code for that if it's necessary, and you still can't repro.

**Comment by gscshoyru** [comment]
Actually, here:

```typescript
module Lint {
    export function createLanguageServiceHost(fileName: string, source: string) {
        var host: ts.LanguageServiceHost = {
            getScriptFileNames: () => [fileName],
            getScriptVersion: () => "1",
            getScriptSnapshot: () => {
                return {
                    getText: (start, end) => source.substring(start, end),
                    getLength: () => source.length,
                    getLineStartPositions: () => ts.computeLineStarts(source),
                    getChangeRange: (oldSnapshot) => undefined
                };
            },
            getCurrentDirectory: () => "",
            getScriptIsOpen: () => true,
            getCompilationSettings: () => Lint.createCompilerOptions(),
            getDefaultLibFileName: () => "lib.d.ts",
            log: (message) => { /* */ }
        };

        return host;
    }
}

var documentRegistry = ts.createDocumentRegistry();
var languageServiceHost = Lint.createLanguageServiceHost("file.ts", sourceFile.getFullText());
var languageService = ts.createLanguageService(languageServiceHost, documentRegistry);
languageService.getDocumentHighlights("file.ts", position, ["file.ts"]);
```

This is what we're doing (paraphrased a little) that's causing the issue.

**Comment by DanielRosenwasser** [comment]
Still not able to repro.

> `ts.computeLineStarts(source)`

Doesn't seem to be publicly exposed anymore, how are you doing this?

> `Lint.createCompilerOptions()`

Not sure what we get back from this, could be useful for the repro

-----------------------

Here's what I'm currently working with:

```TypeScript
/// <reference path="built/local/typescript.d.ts" />

import * as ts from "typescript"

module Lint {
    export function createLanguageServiceHost(fileName: string, source: string) {
        var host: ts.LanguageServiceHost = {
            getScriptFileNames: () => [fileName],
            getScriptVersion: () => "1",
            getScriptSnapshot: () => {
                return {
                    getText: (start, end) => source.substring(start, end),
                    getLength: () => source.length,
                    getLineStartPositions: () => (<any>ts).computeLineStarts(source),
                    getChangeRange: (oldSnapshot) => undefined
                };
            },
            getCurrentDirectory: () => "",
            getScriptIsOpen: () => true,
            getCompilationSettings: () => ({}),
            getDefaultLibFileName: () => "lib.d.ts",
            log: (message) => { /* */ }
        };

        return host;
    }
}

var sourceText = "/// <reference path=\"../TypeScript3/foo.ts\" />\n\nmodule m {\n    var s;\n}\n";

var documentRegistry = ts.createDocumentRegistry();
var languageServiceHost = Lint.createLanguageServiceHost("boo.ts", sourceText);
var languageService = ts.createLanguageService(languageServiceHost, documentRegistry);

for (var i = 0; i < sourceText.length; i++) {
    console.log(JSON.stringify(languageService.getDocumentHighlights("boo.ts", i, ["boo.ts"])));
}
```

I'm asking for highlights at every position in the document and I'm still not running into any problems.

**Comment by gscshoyru** [comment]
Sorry, create compiler options is just 
```typescript
export function createCompilerOptions(): ts.CompilerOptions {
        return {
            target: ts.ScriptTarget.ES5
        };
    }
```
so shouldn't be anything special.

You're right that it doesn't blow up that way, but it does blow up if you do ```/// <reference path=\"../foo.ts``` instead. Not entirely sure why. 

It also seems to blow up without reference paths if you have imports with the same problem, such as ```import xyz = require("../xyz");``` instead of the reference path.

**Comment by DanielRosenwasser** [comment]
@gscshoyru the problem is that your `getScriptSnapshot` is not actually using its given parameters, nor is it trying to appropriately resolve the filenames it is given.

**Comment by ashwinr** [comment]
@DanielRosenwasser Thanks for the reply. Is there any way to ignore imports/references when calling this LS API (or other LS APIs in general)? TSLint doesn't actually need to resolve imports since it works on a file-by-file basis. Thanks again!

**Comment by DanielRosenwasser** [comment]
@ashwinr you should be able to just return an empty string if it's not one of the files you're interested in. Let us know how that works out.

**Comment by vladima** [comment]
@ashwinr you can set `noResolve` to `true` in compilation options to tell compiler that it should not do any file resolutions except files that were provided explicitly

**Comment by DanielRosenwasser** [comment]
^^^ Do what Vlad said.

**Comment by gscshoyru** [comment]
Looks like setting noResolve to true does the trick. Thanks ever so much, and sorry for the confusion!
