### ISSUE TITLE
target:"es5" should respect the quoting of property identifiers

### ISSUE THREAD

**Issue by brett-shwom** [Microsoft/TypeScript#30222]
**TypeScript Version:**  3.3333

**Search Terms:** Object.defineProperties, Object.defineProperty, getter, setter, es5, quoted

**Code**

```ts
class Foo {
    get bar(): number {
        return 1;
    }
}
```

**Expected behavior:**

Given: ```compilerOptions.target === 'es5'```

```
var Foo = /** @class */ (function () {
    function Foo() {
    }
    Object.defineProperties(Foo.prototype, {
        bar: { //property `bar` is unquoted
            get: function () {
                return 1;
            },
            enumerable: true,
            configurable: true
        }
    });
    return Foo;
}());
```

**Actual behavior:**
```
var Foo = /** @class */ (function () {
    function Foo() {
    }
    Object.defineProperty(Foo.prototype, "bar", { //property `bar` is quoted
        get: function () {
            return 1;
        },
        enumerable: true,
        configurable: true
    });
    return Foo;
}());
```

If the property identifier is quoted, 

```ts
class Foo {
    get 'bar'(): number {
        return 1;
    }
}
```

then either the current behavior:

```
var Foo = /** @class */ (function () {
    function Foo() {
    }
    Object.defineProperty(Foo.prototype, 'bar', {
        get: function () {
            return 1;
        },
        enumerable: true,
        configurable: true
    });
    return Foo;
}());

```

or

```
var Foo = /** @class */ (function () {
    function Foo() {
    }
    Object.defineProperties(Foo.prototype, {
        'bar': { //property `bar` is quoted
            get: function () {
                return 1;
            },
            enumerable: true,
            configurable: true
        }
    });
    return Foo;
}());
```

would work.

**Rationale**

Property names specified as string literals are syntactically different to property names specified as unquoted identifiers. This distinction is lost during es5 transpilation and that loss can have meaningful consequences on how the resulting code is interpreted.

Example use case:

Closure Compiler's [property renaming](http://closuretools.blogspot.com/2011/01/property-by-any-other-name-part-1.html) treats string references ```foo['bar']``` and dot-syntax references ```foo.bar``` differently. The lack of control over quoted / unquoted property names during the ts -> es5 transpilation increases the difficulty of passing the es5 output through Closure Compiler without further code transformations, Closure Compiler externs, or other workarounds.

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%0D%0A%20%20%20%20get%20bar()%3A%20number%20%7B%0D%0A%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20FooQuoted%20%7B%0D%0A%20%20%20%20get%20'bar'()%3A%20number%20%7B%0D%0A%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Comment by DanielRosenwasser** [comment]
They are syntactically different, but not semantically different except to the Closure Compiler. If you're looking to link the two up, have you looked at https://github.com/angular/tsickle?

**Comment by RyanCavanaugh** [comment]
Consistently emitting the same JS code for the same semantic input is a feature, not a bug.

Closure has a *lot* of rules that rely on subtle clues and we're generally not going to spend our complexity budget to transfer inferred user intent into Closure's interpretive worldview.
