### ISSUE TITLE
export function implicit export return type bug

### ISSUE THREAD

**Issue by tangjfn** [Microsoft/TypeScript#30221]
**TypeScript Version:**  3.3.3333

**Search Terms:**

**Code**

```ts

// a.ts
enum E1 {
  A,B
}

interface E1Map {
   [name: string]: E1;
}

export function x(): E1Map {
// do some thing
}

// b.ts

import a;

 if (x == a.E1.A) // a.E1 is undefined

// ...
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Please provide an actual repro, not a loose transcription.
