### ISSUE TITLE
Add ability to `JSON.parse` function to specify the return type

### ISSUE THREAD

**Issue by AhmedMKamal** [Microsoft/TypeScript#30220]
## Search Terms

- JSON
- JSON.parse
- JSON.parse return type

## Suggestion

Add the ability to `JSON.parse` function to specify the return type, I already opened a PR [#30219](https://github.com/Microsoft/TypeScript/pull/30219), implementing this feature

## Use Cases
```
let parsedObj = JSON.parse<TypeObj>("{ prop: 'val' }"); // parsedObj is TypeObj
```
is way better than
```
let parsedObj = JSON.parse("{ prop: 'val' }"); // parsedObj is any
```
## Examples

that said in the use cases ¯\_(ツ)_/¯

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by hejkerooo** [comment]
While `JSON.parse` returns `any`, you can simply do 
`let parsedObj: Interface = JSON.parse("{ prop: 'val' }"); // parsedObj is any`

So there will be no difference between adding generic type to `JSON.parse` and mine "solution"

**Comment by AhmedMKamal** [comment]
@hejkerooo here's a real-world example
```
export const getCurrentUserDataAsync = () => SecureStore.getItemAsync(SESSION_KEY).then(data => data ? JSON.parse<LoginData>(data) : undefined);
```
How can your solution solve it?

**Comment by hejkerooo** [comment]
```
type ReturnType = LoginData | undefined;
export const getCurrentUserDataAsync = (): ReturnType => SecureStore.getItemAsync(SESSION_KEY).then(data => data ? JSON.parse(data) : undefined);
```

But you shouldn't return undefined, consider throwing an error or try nullable pattern
[Nullable pattern](https://en.wikipedia.org/wiki/Null_object_pattern)

**Comment by AhmedMKamal** [comment]
@hejkerooo so, for a service file that contains about ten methods like this one I'm going to define ten types separately!!!

**Comment by cpplearner** [comment]
I think this is what a type assertion is for:
```
JSON.parse(data) as LoginData
// or: <LoginData>JSON.parse(data)
```

**Comment by hejkerooo** [comment]
> @hejkerooo so, for a service file that contains about ten methods like this one I'm going to define ten types separately!!!

I think, this is a point of strongly typed languages

**Comment by j-oliveras** [comment]
Already discussed and rejected as Working as intended: #26993 and #26994.

**Comment by AhmedMKamal** [comment]
@j-oliveras but [#26994](https://github.com/Microsoft/TypeScript/pull/26994/files) and [#28416](https://github.com/Microsoft/TypeScript/pull/28416/files) discussing solutions that don't make sense,  can you please refer to [#30219](https://github.com/Microsoft/TypeScript/pull/30219/files), see the changes and tell me what you think?!
anyways it's up to the community to decide whether this update is useful or not ¯_(ツ)_/¯

**Comment by RyanCavanaugh** [comment]
> `JSON.parse<TypeObj>("{ prop: 'val' }");`

There's already a place to put that:

> `<TypeObj>JSON.parse("{ prop: 'val' }");`

**Comment by AhmedMKamal** [comment]
@RyanCavanaugh you're right 😅
