### ISSUE TITLE
Strict Null: unexpected complaint about type being possibly undefined when checked before

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#30224]
**Steps:**
* use TS 3.3 (latest)
* enable all strict checks
* have code such as this:

```ts

function foo(): string | undefined {
    return "";
}

function bar(): void {
    let a = foo();
    if (a) {
        setTimeout(() => {
            console.log(a.toString());
        }, 0);
    }
}
```

There is an error: `Object is possibly 'undefined'.` in `console.log(a.toString());`. I feel like TS could be smarter here and figure out that no-one is changing the value of `a` in the method body, so `a` can never turn into `undefined` after the check.

**Comment by RyanCavanaugh** [comment]
We'd have to do another full walk to detect lets-which-should-actually-be-consts, which would be a fairly substantial perf penalty.
