### ISSUE TITLE
Disallow global namespace from imported types.

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#30230]
It's really annoying that simply installing Jest will create global types that pollute the global namespace, not just in my type files, but the actual application files as well which makes my code less type-safe...

I think it would make sense if all global types had to be declared from your ts config so you can scope them to specific files.

I see other issues about this but I'm not sure a proper solution has been lofted.

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/5808

**Comment by DanielRosenwasser** [comment]
You can configure this by creating a separate `tsconfig.json` for `tests` and `src` and setting

```json5
"types": []
```

in the `tsconfig.json` for your src.

**Comment by RyanCavanaugh** [comment]
The dual of this issue is "Installing `@types/node` should automatically make `Buffer` available without more configuration", which is by far the more common scenario here.

**Comment by ccorcos** [comment]
Interesting. You're right, but now I'm even more confused how all of this is supposed to work. These three things seems to have a lot of conflated functionality.
- `npm install @types/node`
- `lib: ["dom"]` 
- `types: []`

Ideally importing node types would be similar to importing dom types.

**Comment by ccorcos** [comment]
For others who are having this same pain, my current workaround is just to rewrite the type definition files in post-install...

```
// No global exports from Jest. Use jestShim.ts.
rewrite("node_modules/@types/jest/index.d.ts", str => {
	return str
		.replace(/declare const/g, "export const")
		.replace(/declare var/g, "export var")
		.replace(/declare function/g, "export function")
})

rewrite("node_modules/@types/mocha/index.d.ts", str => {
	return str
		.replace(/declare const/g, "export const")
		.replace(/declare var/g, "export var")
		.replace(/declare function/g, "export function")
		.replace(/declare module "mocha"[^\}]+\}/m, "")
})

rewrite("node_modules/cypress/types/index.d.ts", str => {
	return str
		.replace(/declare const/g, "export const")
		.replace(/declare var/g, "export var")
		.replace(/declare function/g, "export function")
		.replace(
			`/// <reference types="sinon-chai" />\r\n\r\n`,
			`/// <reference types="sinon-chai" />\r\nimport { Mocha } from "mocha"\r\n`
		)
		.replace(
			`/// <reference types="sinon-chai" />\n\n`,
			`/// <reference types="sinon-chai" />\nimport { Mocha } from "mocha"\n`
		)
})
```

Then I just have to import the stuff I want from this `jestShim.ts` file which grabs the globals and gives them types.

```
/*

Jest exposes these functions in the global namespace, but we don't want
them to leak into the rest of the application so you have to import them
here and we use tools/fixGlobalTypes.ts post-install to cleanup.

Put this at the top of your test file and let ts-lint cleanup unused.

import {
	beforeAll,
	beforeEach,
	afterAll,
	afterEach,
	describe,
	fdescribe,
	xdescribe,
	it,
	fit,
	xit,
	test,
	xtest,
	expect,
	spyOn,
	pending,
	fail,
} from "./jestShim"

*/

import * as jest from "jest"

export const beforeAll: typeof jest.beforeAll = global["beforeAll"]
export const beforeEach: typeof jest.beforeEach = global["beforeEach"]
export const afterAll: typeof jest.afterAll = global["afterAll"]
export const afterEach: typeof jest.afterEach = global["afterEach"]
export const describe: typeof jest.describe = global["describe"]
export const fdescribe: typeof jest.fdescribe = global["fdescribe"]
export const xdescribe: typeof jest.xdescribe = global["xdescribe"]
export const it: typeof jest.it = global["it"]
export const fit: typeof jest.fit = global["fit"]
export const xit: typeof jest.xit = global["xit"]
export const test: typeof jest.test = global["test"]
export const xtest: typeof jest.xtest = global["xtest"]
export const expect: typeof jest.expect = global["expect"]
export const spyOn: typeof jest.spyOn = global["spyOn"]
export const pending: typeof jest.pending = global["pending"]
export const fail: typeof jest.fail = global["fail"]
```

As for this actual issue... `Buffer` is an interesting case, but that in fact leaks to the client in my codebase... Ideally it would use something more like `lib` so I can extend types in certain subdirectories.
