### ISSUE TITLE
vscode typescript monorepo error

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#30245]
- VSCode Version: Version 1.31.1 (1.31.1) 1b8e8302e405050205e69b59abb3559592bb9e60
- OS Version: macOS Version 10.14.3 (18D109)

Steps to Reproduce:

see : https://github.com/xiaoxiangmoe/vscode-typescript-monorepo-error

Does this issue occur when all extensions are disabled?: Yes

**Comment by duro** [comment]
@xiaoxiangmoe Simply importing type script from a module into another typescript file will not work. The other projects typescript must be compiled first. I think you need to look into Project References:

https://www.typescriptlang.org/docs/handbook/project-references.html

This will tell the tsc compiler to build that other project along side the main project.

**Comment by xiaoxiangmoe** [comment]
@duro I use parcel and it will work. Because it support something like https://github.com/parcel-bundler/parcel/pull/1101 

---

If you'd like to compile it first, run `yarn workspace the-answer-to-life-the-universe-and-everything build`.

**Comment by mjbvz** [comment]
Closing due to lack of recent activity
