### ISSUE TITLE
proper declaration for class decorator?

### ISSUE THREAD

**Issue by cmichaelgraham** [Microsoft/TypeScript#3024]
i'm having difficulty figuring out the correct declaration for a class decorator.

here is the `.d.ts` i have:

```javascript
	export function autoinject(target: any): void | ((target: any) => void);
```

here is the autoinject class decorator in use:

```javascript
import {autoinject} from 'aurelia-framework';
import {HttpClient} from 'aurelia-http-client';

@autoinject
export class Flickr{
  heading = 'Flickr';
  images = [];
  url = 'http://api.flickr.com/services/feeds/photos_public.gne?tags=rainier&tagmode=any&format=json';
  http:HttpClient;
  constructor(http:HttpClient){
    this.http = http;
  }
```

and here is the compiler error i get:

Error	29	Build: Type '(target: any) => void | ((target: any) => void)' is not assignable to type '(target: typeof Flickr) => void | typeof Flickr'.	C:\a\aurelia-typescript\skel-nav-esri-vs-ts\skel-nav-esri-vs-ts\views\flickr.ts	4	1	skel-nav-esri-vs-ts

**Comment by mhegazy** [comment]
Pinging @rbuckton 

here is the complete one.
```ts
type ClassDecorator = <TFunction extends Function>(target: TFunction) => TFunction | void;

// so autoinject would be:
declare function autoinject<T>(target: T): void |T;
```

for your case, if you are always returning a value:

```ts
declare function autoinject<T extends Function>(target: T): T;
```
or just:
```ts
declare function autoinject(target: any): any;
```

**Comment by cmichaelgraham** [comment]
works: 1,000 thank you's !!! :+1:

**Comment by mhegazy** [comment]
glad that helped.

**Comment by cmichaelgraham** [comment]
made my day :+1:
