### ISSUE TITLE
CTRL+Click -> go to file is weird

### ISSUE THREAD

**Issue by MathiasKandelborg** [microsoft/TypeScript#30246]
- VSCode Version: 1.32.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. CTRL+click a react component being used somewhere
2. Now CTRL+click on a TS definition in the same file.

No. 1 opens a definition thingy, which has begun to pop up almost all the time.
No. 2 opens the definition file and shifts focus.

I have no idea what has been changed or why. CTRL+clicking is not the same anymore and has gotten seriously frustrating. I've no idea what to do besides making this really bad issue that doesn't explain anything properly. I'm just sure something has changed and in my perception to the worse.. Atleast I'd like some better update messages for such core functionality.

I used to be able to CTRL+click and continue working. Now I have to spendd upwards of 30 seconds to figure everything out.

Here's what I think should happen: CTRL+click has the same functionality no matter where you do it... that's it. Make a setting to 'peek' definition or whatever you call it and an option to open the file in which the clicked entity exists.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Tested with typescript@3.4.0-dev.20190306

I confirmed that for the example code, a `definition` request on `Component` returns two entires:

```
[Trace  - 2:13:55 PM] Sending request: definitionAndBoundSpan (46). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/x.js",
    "line": 3,
    "offset": 2
}
[Trace  - 2:13:55 PM] Response received: definitionAndBoundSpan (46). Request took 2 ms. Success: true 
Result: {
    "definitions": [
        {
            "file": "/Users/matb/projects/san/x.js",
            "start": {
                "line": 1,
                "offset": 14
            },
            "end": {
                "line": 1,
                "offset": 23
            }
        },
        {
            "file": "/Users/matb/projects/san/x.js",
            "start": {
                "line": 3,
                "offset": 1
            },
            "end": {
                "line": 3,
                "offset": 10
            }
        }
    ],
    "textSpan": {
        "start": {
            "line": 3,
            "offset": 1
        },
        "end": {
            "line": 3,
            "offset": 10
        }
    }
}
```

**Comment by MathiasKandelborg** [comment]
Is there any way to get info in order to contribute? I'd love to help but haven't played with VSCode source before - do you have any tips, suggestions or places to go in order to begin helping out? I'll, of course, try myself, I'm just thinking I might get a great boost by asking. :slightly_smiling_face:
