### ISSUE TITLE
Add Logic Negation to Type Unions and Intersections to Improve Type Narrowing, Conditional Types and Generic Constraints 

### ISSUE THREAD

**Issue by krisselden** [Microsoft/TypeScript#30248]
## Search Terms

"type negation", "not constraint", "inverse", "non matching type", "noncallable", "non callable", "inverse constraint", "inverse type", "inverse union"

## Suggestion

The ability to specify a Type as describing what it shouldn't match structurally, so that a constraint can say what something doesn't extend so that a generic can be used in a union and narrowed.

Also `T & ~U` would allow the else side of a constraint to be evaluated the same way T & U allows the positive side to be (example below).

Basically adding negation`~` in addition to `&` and `|` in types also allows for identities like `~(T & U) = (~T) | (~U)` and `~(T | U) = (~T) & (~U)`.  This would allow for conditionals to be applied and simplified in more cases than are today.

## Use Cases

Better type narrowing with unions and constrained generics.

## Examples

Non generic version works today:
```ts
function force(x: {} | (() => {})): {} {
    if (typeof x === "function") {
        return x();
    } else {
        return x;
    }
}
```

Trying to make it generic is missing a way to express the constraint that T has no call signatures
```ts
function force<T>(x: T | (() => T)): T {
    if (typeof x === "function") {
        // Type error because type is (T & Function) | (() => T)
        // would have to cast to () => T and
        // would not catch an error if someone passed a function
        // that didn't match () => T
        return x();
    } else {
        return x;
    }
}
```

```ts
function force<T, U extends T extends Function ? T extends () => infer R ? R : never : T>(x: T): U {
    if (typeof x === "function") {
        // conditional can be applied to T & Function so this works now
        return x();
    } else {
        // but now the conditional will not have been applied because
        // there is no inverse to the narrowing `T & ~Function`
        // so the conditional remains unevaluated here thus T can't be assigned to U here.
        return x;
    }
}
```

Proposed:
```ts
function force<T extends ~Function>(x: T | (() => T)): T {
    if (typeof x === "function") {
        // now it is can be narrowed because `(T & ~Function)`
        return x();
    } else {
        return x;
    }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by wycats** [comment]
I've encountered roughly this problem before and would appreciate some sort of solution to this problem.

**Comment by yortus** [comment]
Is #29317 what you are after?

**Comment by weswigham** [comment]
This looks like my negated types PR which @yortus has linked. You should probably try that out.

**Comment by krisselden** [comment]
@weswigham yes, that is what I'm after, I swear I searched for it.
