### ISSUE TITLE
Somtimes generating inline imports for d.ts files instead of using globally imported symbols

### ISSUE THREAD

**Issue by CarstenLeue** [Microsoft/TypeScript#30258]
**TypeScript Version:**  typescript@3.2.4
I cannot use a more recent version, since I am using the Angular build process that requires `>=3.1.1 <3.3`.

I am opening this issue as requested by defect
https://github.com/Microsoft/web-build-tools/issues/1067

The problem looks related to  https://github.com/Microsoft/TypeScript/issues/25511 but that issue has been closed, still the problem persists for me.

**Problem statement:**

The `d.ts` file generated during my compile step looks like this:
```typescript
export declare const authContentFeatureReducer: {
    [AUTH_CONTENT_FEATURE]: import("redux").Reducer<Record<string, import("@ibm-wch-sdk/api").AuthoringContentItem>, import("..").PayloadAction<string> | import("..").PayloadAction<import("@ibm-wch-sdk/api").AuthoringContentItem>>;
};
```

It references types from other modules via **inline** import statements. This causes a problem when generating documentation via the https://www.npmjs.com/package/@microsoft/api-documenter tool, because these inline import statements appear as is in the generated documentation. Instead of just the types they point to. This renders the documentation basically unreadable.

**Expected behaviour**
I would expect output similar to this:
```typescript
import { Reducer } from 'redux';
import { AuthoringContentItem} from '@ibm-wch-sdk/api';
import { PayloadAction } from '..'

export declare const authContentFeatureReducer: {
    [AUTH_CONTENT_FEATURE]: Reducer<Record<string, AuthoringContentItem>, PayloadAction<string> | PayloadAction<AuthoringContentItem>>;
};

```

The actual source code looks like this:
```typescript
import { authoringContentReducer } from './auth.content.reducer';

export const AUTH_CONTENT_FEATURE = 'authContent';

export const authContentFeatureReducer = {
  [AUTH_CONTENT_FEATURE]: authoringContentReducer
};
```

**Comment by RyanCavanaugh** [comment]
We intentionally don't synthesize imports; writing an inline import is more predictable on our end and doesn't require any name collision logic.

If you add those imports to the file yourself, they'll be used, so I'd recommend doing that.
