### ISSUE TITLE
Type check failed when call function via apply with array arguments

### ISSUE THREAD

**Issue by galenyuan** [Microsoft/TypeScript#30252]
**TypeScript Version:**  3.4.0-dev.20190306、3.3.333333

**Search Terms:**

**Code**

```ts
function add (num1: number, num2: number, ...others: number[]) {
}

add.apply(null, [1, 2, 3, 4]) // right
const arr = [1, 2, 3, 4] 
add.apply(null, arr) // Argument of type 'number[]' is not assignable to parameter of type '[number, number, ...number[]]'
```

**Expected behavior:**
compile success

**Actual behavior:**
Argument of type 'number[]' is not assignable to parameter of type '[number, number, ...number[]]'

but when I set `strict` to `false` in `tsconfig.json` it works fine

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=function%20add%20(num1%3A%20number%2C%20num2%3A%20number%2C%20others%3A%20number%5B%5D)%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Aadd.apply(null%2C%20%5B1%2C%202%2C%203%2C%204%5D)%0D%0A%0D%0Aconst%20arr%20%3D%20%5B1%2C%202%2C%203%2C%204%5D%0D%0Aadd.apply(null%2C%20arr)%0D%0A

**Related Issues:**

**Comment by galenyuan** [comment]
looks like `(num1:number, num2: number, ...others: number[])` means should have at least 2 arguments, but `number[]` can have any length(less than 2 prob), right?

**Comment by dragomirtitian** [comment]
The problem as you correctly guessed is that `arr` has the type `number[]` which can't be guaranteed to have more that 2 elements. You want `arr` to be a tuple type. Tuples are similar to arrays (in fact at runtime they are arrays) but they are of a fixed length. Typescript will not however infer tuples for array literals by default. 

You have several options to get around this:

Soo, in 3.4 you will be able to write `as const`, to get the compiler to infer a readonly tuple for `arr`:

```ts
const arr = [1, 2, 3, 4] as const
```

An option for before 3.4 is to use a function that hints at the compiler you want a tuple:

```ts
const arr = (<T extends any[]>(...o:T)=>o)(1, 2, 3, 4)
```

Or you can just manually type the tuple: 
```ts
const arr: [number,number,number,number] = [1, 2, 3, 4]
```
