### ISSUE TITLE
Narrowing string intersection type with typeof check 

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#30257]
**TypeScript Version:**  3.4.0-dev.20190307

**Search Terms:**
type narrowing intersection

**Code**

```ts
type A<T extends object> = {
    stringProp: keyof T & string
};

export function it<T extends object>(stringPropOrObj: A<T> | keyof T & string) {
  const obj: A<T> = typeof stringPropOrObj === "string"
    ? { stringProp: stringPropOrObj }
    : stringPropOrObj;
}
```

**Expected behavior:**
No error. The type of `stringPropOrObj` is narrowed by the typeof check in both branches of the ternary.

**Actual behavior:**
In the else condition of the ternary, `stringPropOrObj` isn't correctly narrowed to `A<T>`, so we get an assignability error:

```
type 'A<T> | (keyof T & string)' is not assignable to type 'A<T>'.
  Type 'keyof T & string' is not assignable to type 'A<T>'.
    Type 'string' is not assignable to type 'A<T>'.
```

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=type%20A%3CT%20extends%20object%3E%20%3D%20%7B%0A%20%20%20%20stringProp%3A%20keyof%20T%20%26%20string%0A%7D%3B%0A%0Aexport%20function%20it%3CT%20extends%20object%3E(stringPropOrObj%3A%20A%3CT%3E%20%7C%20keyof%20T%20%26%20string)%20%7B%0A%20%20const%20obj%3A%20A%3CT%3E%20%3D%20typeof%20stringPropOrObj%20%3D%3D%3D%20%22string%22%0A%20%20%20%20%3F%20%7B%20stringProp%3A%20stringPropOrObj%20%7D%0A%20%20%20%20%3A%20stringPropOrObj%3B%0A%7D

**Comment by jack-williams** [comment]
This is a design limitation in the type facts system that controls narrowing under inequality. In the else clause of the ternary the union type is filtered based on whether the type contains the fact: _not a string_. 

The facts of the intersection type ` keyof T & string` are the facts of  `keyof T` and the facts of  `string`.

The facts of ` keyof T` are the facts of the base constraint, which are the type `string | number | symbol`.

The facts of `string | number | symbol` are the facts of each part, and as `symbol` and `number` are _not strings_, then ` keyof T & string` is _not a string_. Consequently, the branch ` keyof T & string` is not filtered from the union.

One possible fix might be to apply subtyping reduction on `(number | string | symbol) & string` before collecting the facts, but this is likely a significant change.

The better fix is to wait for #29317 (and latter narrowing changes) such that  ` keyof T & string` gets narrowed to  ` keyof T & string & not string` which collapses to `never`, avoiding the facts system.
