### ISSUE TITLE
Typecheck failing when making assignment with generics

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/TypeScript#30254]
**TypeScript Version:**  3.4.0-dev.20190307

**Search Terms:**
typecheck failing generic assignment

**Code**

```ts
let x: FieldResolver<Treatment> = new FieldResolver<DrSpotlight>(DrSpotlight);
```

**Expected behavior:**

This would cause a type exception as `Bar` does not meet the requirements of `Foo`.  

**Actual behavior:**

It's allowing me to make this assignment without complaining.  Oddly, I do get the error if I change it to:

```ts
let x: FieldResolver<Treatment> = new FieldResolver<Treatment>(DrSpotlight);
```

![vzjiop2rod](https://user-images.githubusercontent.com/5217568/53940935-17220400-4074-11e9-9165-516b7e012f79.gif)

It seems like it maybe has something to do with the way my code is built.  `FieldResolver` is coming from a separate package.  When I run similar code inside that package, it fails as expected.

Also, when I try to recreate a minimal reproduction it throws a type error as expected.  

What might be causing this issue?

**Comment by barld** [comment]
Does `DrSpotlight` mayby has the the same properties as `Treatment` ? Typescript is looking for the structure of the type. Not for the same name.

```
class Foo<T> {
  constructor(public value: T) { }
}

let bar: Foo<boolean> = new Foo<true>(true);
```

this for example does also compile because because it met the same contrains as `foo<boolean>`

**Comment by ChuckJonas** [comment]
@barld they properties are different, and typescript doesn't seem to mind no matter what I put as the generic parameter on the left hand side:

```ts
//no error
let x: FieldResolver<Boolean> = new FieldResolver<DrSpotlight>(DrSpotlight);
```

It's like it's losing it type check once it's assigned.... And even weirder because it DOES throw errors when I run the same code inside the npm package... It's just after it's been installed in a different project that it loses type safety.

**Comment by RyanCavanaugh** [comment]
With only a single line of code and no repro, I have to assume this is just a misconfiguration or misunderstanding of some sort. StackOverflow is probably a better venue for this.

**Comment by ChuckJonas** [comment]
@RyanCavanaugh I just figured it out... I'm not sure if it's a bug or not.  It seems like maybe the bug is that it WAS throwing an error when I reproduced in the internal package.

Here's a [reproducible link where it does](https://www.typescriptlang.org/play/#src=interface%20SObjectStatic%3CT%3E%20%7B%0D%0A%20%20%20%20new()%3A%20T%3B%0D%0A%20%20%20%20API_NAME%3A%20string%3B%0D%0A%20%20%20%20FIELDS%3A%20%7B%20%5Bkey%20in%20keyof%20T%5D%3A%20string%3B%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20FieldResolver%3CT%3E%7B%0D%0A%20%20%20%20private%20readonly%20_traversed%3A%20string%5B%5D%3B%0D%0A%20%20%20%20private%20readonly%20_obj%3A%20SObjectStatic%3CT%3E%3B%0D%0A%0D%0A%20%20%20%20constructor%20(obj%3A%20SObjectStatic%3CT%3E%2C%20traversed%3F%3A%20string%5B%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20this._obj%20%3D%20obj%3B%0D%0A%20%20%20%20%20%20%20%20this._traversed%20%3D%20traversed%20%7C%7C%20%5B%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%7B%0D%0A%20%20%20%20static%20API_NAME%20%3D%20'abc'%3B%0D%0A%20%20%20%20static%20FIELDS%3A%20%7B%20%5Bkey%20in%20keyof%20Foo%5D%3A%20string%3B%20%7D%20%3D%20%7B%20%22foo%22%3A%20'abc'%20%7D%3B%20%0D%0A%20%20%20%20public%20foo%20%3D%20'abc'%3B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%7B%0D%0A%20%20%20%20static%20API_NAME%20%3D%20'2'%3B%0D%0A%20%20%20%20static%20FIELDS%3A%20%7B%20%5Bkey%20in%20keyof%20Bar%5D%3A%20string%3B%20%7D%20%3D%20%7B%20%22bar%22%3A%20'abc'%20%7D%3B%0D%0A%20%20%20%20public%20bar%20%3D%20'abc'%3B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Alet%20x%3A%20FieldResolver%3CFoo%3E%20%3D%20new%20FieldResolver(Bar)%3B) throw an error.

It had to do with my scope declaration of the properties in `FieldResolver`.  I guess since `_obj` was marked as `private` that in terms of interface contract, actually IS no difference between a `FieldResolver<X>` vs `FieldResolver<Y>`...

If I update that member to `public` or `protected` I now get an error in the project using this package.

So now it almost seems like there IS a bug in that an error shouldn't be thrown in my link above?

**Comment by RyanCavanaugh** [comment]
Sounds like you're encountering #20979

**Comment by ChuckJonas** [comment]
that is definitely it.  Closing as duplicate of #20979
