### ISSUE TITLE
TypeScript unexpectedly inferring 'any' type.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#30250]
Given the following code:

```ts
interface Widget { x: number }

declare type Unwrap<T> = T extends Promise<infer U1> ? UnwrapSimple<U1> : UnwrapSimple<T>;
declare type primitive = Function | string | number | boolean | undefined | null;

declare type UnwrapSimple<T> = T extends primitive ? T : T extends Array<infer U> ? UnwrappedArray<U> : T extends object ? UnwrappedObject<T> : never;

export interface UnwrappedArray<T> extends Array<Unwrap<T>> {
}

export declare type UnwrappedObject<T> = {
    [P in keyof T]: Unwrap<T[P]>;
};

declare var w: Widget;
declare type TupleType = [Widget, string];
declare var o: UnwrappedObject<TupleType>;
```

TypeScript oddly infers a type of `[any, string]` for `o`. This is surprising to us given how we would think these type operators would work.  First, given the definition `UnwrappedObject` i would expect `UnwrappedObject<TupleType>` to expand like so:

```
UnwrappedObject<TupleType>  ->
UnwrappedObject<[Widget, string]> ->
[Unwrap<Widget>, Unwrap<string>] ->
[UnwrappedObject<Widget>, string] ->
[{ x: Unwrap<number> }, string] ->
[{ x: number }, string]
```

HOwever, instead of getting `{ x: number }` (which is just the Widget type), we end up with 'any'.  Cany anyone shed any light on this?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Tagging @DanielRosenwasser

**Comment by CyrusNajmabadi** [comment]
@RyanCavanaugh do you have any ideas here?  Thanks!

**Comment by RyanCavanaugh** [comment]
This problem was fixed by #29740

**Comment by CyrusNajmabadi** [comment]
@RyanCavanaugh Thanks!  Is there a way to tell what release of TS that may have made it out into?

**Comment by RyanCavanaugh** [comment]
The PR was 3 days ago, so it'd be in any nightly starting approximately yesterday

**Comment by CyrusNajmabadi** [comment]
@RyanCavanaugh wasn't it almost a month ago?

![image](https://user-images.githubusercontent.com/4564579/53986407-f8068f00-40d2-11e9-9b62-b6a3cbcf4ed2.png)

This is part of github that i'm not really familiar with!

**Comment by RyanCavanaugh** [comment]
I thought today was February 7th 🤦‍♂️

This fix wasn't in 3.3, so "nightly" is still the right answer.

The incantation (if you have a local TS repo) to check is
```ts
D:\github\TypeScript>git branch -r --contains d9ee867
  origin/HEAD -> origin/master
  origin/master
  origin/no-mkdir-race
  upstream/add-globalThis
  upstream/applyChangesToOpenFiles
  upstream/circularConstraintErrors
  upstream/contextualGenericRestParameter
  upstream/convert-to-named-parameters
  upstream/incrementalBuildInfo
  upstream/master
  upstream/perfTimeStamp
  upstream/revertExecFileSync
  upstream/usePrependToSkipBuild
  upstream/weswigham-patch-1
```

**Comment by CyrusNajmabadi** [comment]
> I thought today was February 7th 🤦‍♂️

That's ok.  I still think it's 2017 occasionally.  :D

**Comment by CyrusNajmabadi** [comment]
Thanks.  Have confirmed this is fixed in the latest nightly.  I'm going to keep this issue open though until that is released.  

@RyanCavanaugh @DanielRosenwasser Any general idea of when 3.4 might be released?  Trying to make plans depending on if it's more like in a week or so, or more like a month.  Thanks much!

**Comment by RyanCavanaugh** [comment]
See https://github.com/Microsoft/TypeScript/issues/30281
