### ISSUE TITLE
Typescript refactor Pick type

### ISSUE THREAD

**Issue by wyattjoh** [Microsoft/TypeScript#30263]
- VSCode Version: 1.32.0
- OS Version: macOS 10.14.3

Steps to Reproduce:

```typescript
interface BigInterface {
  a: number;
  b: number;
  c: number;
  d: number;
}

type PartialBigInterface = Pick<BigInterface, "a">;
```

1. Clone the basic typescript project: https://github.com/wyattjoh/basic-typescript (source located below for reference)
2. Open the project in VSCode
3. Open the typescript file located at `src/index.ts`
4. Select the `a` symbol on line 2, select F2 (or equivalent key) to refactor.
5. Change the symbol to `e`, press enter to start the refactor.

**Notice that the `PartialBigInterface` type does not have it's picked key `a` changed to an `e`. Instead yielding:**

```diff
 interface BigInterface {
-  a: number;
+  e: number;
   b: number;
   c: number;
   d: number;
}

type PartialBigInterface = Pick<BigInterface, "a">;
```

I would expect that during refactors, that this property refactor would propagate across all the `Pick` types as well, yielding the following instead:

```diff
 interface BigInterface {
-  a: number;
+  e: number;
   b: number;
   c: number;
   d: number;
}

- type PartialBigInterface = Pick<BigInterface, "a">;
+ type PartialBigInterface = Pick<BigInterface, "e">;
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Moving upstream for more feedback.

I'm not sure i would expect renames to work this way, especially for more complex types.  What you'd probably want here is something like c#'s `nameof` operator so you can explicitly link the `Pick` key to the interface:

```ts
type PartialBigInterface = Pick<BigInterface, nameof(BigInterface.a)>;
```

**Comment by NN---** [comment]
There is some workaround for nameof: https://www.npmjs.com/package/ts-nameof

**Comment by RyanCavanaugh** [comment]
"What should happen here" quickly gets extremely confusing when you have something like e.g. `Pick<BigInterface | SomethingElse, "a">`. The only **consistent** behavior we can offer is to *not* rename string literals in type positions.

**Comment by ackvf** [comment]
Can we rename literals when the type is simple enough to avoid ambiguity?

**Comment by Maxim-Mazurok** [comment]
> Can we rename literals when the type is simple enough to avoid ambiguity?

I like this idea. There are lots of pretty simple use-cases, such as:

```ts
export interface Credentials {
  name: string;
  email: string;
  password: string;
}

type LoginUser = Pick<Credentials, 'email' | 'password'>;
type ResetPassword = Pick<Credentials, 'email'>;
```
([source](https://ultimatecourses.com/blog/using-typescript-pick-mapped-type))

@RyanCavanaugh do you think it'd be a good idea to handle this for when we're picking from a single interface and not a union type?
