### ISSUE TITLE
If map.has() returns true than map.get should not be possibly undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/TypeScript#30268]
Typescript 3.3
Strict null checking turned on 

```
if (map.has(key)) {
 map.get(key).attr   -> TS complains this might be null
}
```

TS shuold somehow undertsand that the key is in the map (which as value does not have undefined elements).

I searched for duplicates and could not find any.

**Comment by jack-williams** [comment]
Duplicate of #9619

**Comment by isidorn** [comment]
Yeah, it is a duplicate, closing. Thank you
