### ISSUE TITLE
Union types not correctly handled in array.map

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#30271]
**TypeScript Version:**  playground / 3..3.333

**Search Terms:**
union type, array map

**Code**

```ts
function flattenStringArrays(values: string | string[] | string[][]): string{

    if (Array.isArray(values)) {
        return values.map(value => flattenStringArrays(value)).join("");
    } else {
        return values;
    }
}
```

**Expected behavior:**
here the `value` in the map expression should be of type `string[] | string[][]`

**Actual behavior:**
Compilation error thrown: 

> Cannot invoke an expression whose type lacks a call signature. Type '(<U>(callbackfn: (value: string, index: number, array: string[]) => U, thisArg?: any) => U[]) | (<U>(callbackfn: (value: string[], index: number, array: string[][]) =>
U, thisArg?: any) => U[])' has no compatible call signatures.

**Playground Link:** 
[link](https://www.typescriptlang.org/play/#src=%0D%0Afunction%20flattenStringArrays(values%3A%20string%20%7C%20string%5B%5D%20%7C%20string%5B%5D%5B%5D)%3A%20string%7B%0D%0A%0D%0A%20%20%20%20if%20(Array.isArray(values))%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20values.map(value%20%3D%3E%20flattenStringArrays(value)).join(%22%22)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20values%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:**

**Comment by Roaders** [comment]
This is a workaround for the issue:

```
function flattenStringArrays(values: string | (string | string[])[]): string{

    if (Array.isArray(values)) {
        return values.map(value => flattenStringArrays(value)).join("");
    } else {
        return values;
    }
}
```

[link](https://www.typescriptlang.org/play/#src=%0D%0Afunction%20flattenStringArrays(values%3A%20string%20%7C%20(string%20%7C%20string%5B%5D)%5B%5D)%3A%20string%7B%0D%0A%0D%0A%20%20%20%20if%20(Array.isArray(values))%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20values.map(value%20%3D%3E%20flattenStringArrays(value)).join(%22%22)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20values%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by jack-williams** [comment]
This is a design limitation because it's trying to combine two generic union signatures. See [these](https://github.com/Microsoft/TypeScript/pull/29011#issuecomment-451212987) [comments](https://github.com/Microsoft/TypeScript/issues/7294#issuecomment-465801362)

**Comment by gilbert** [comment]
Here's a workaround:

```ts
/** Type workaround for https://github.com/Microsoft/TypeScript/issues/7294#issuecomment-465794460 */
type ArrayElem<A> = A extends Array<infer Elem> ? Elem : never

export function elemT<T>(array: T): Array<ArrayElem<T>> {
  return array as any
}
```

Example usage:

```ts
type A = { x: number, y: string }
type B = { x: number, z: string }
type Subject = A[] | B[]

function foo (items: Subject) {
  // items.map(item => item.x) // Type error
  elemT(items).map(item => item.x) // Works!
}
```

**Comment by Robula** [comment]
This is still an ongoing issue.
@DanielRosenwasser What issue does this duplicate?
