### ISSUE TITLE
TypeScript can't find its own typings. Trying to work with the compiler API as described here => https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

### ISSUE THREAD

**Issue by CyriacBr** [Microsoft/TypeScript#30275]
**TypeScript Version:**  3.3.3333

**Search Terms:** compiler API, cannot find module 'typescript', typescript typings

**Code**

```ts
npm install -g typescript
npm link typescript
```

**Expected behavior:** Can use properly TS compiler API as described here: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API.

**Actual behavior:** `cannot find module 'typescript'`.
The TS module gets indeed linked locally but VSCode cannot find its typings. It's as if typescript doesn't provide its won typings, like it claims to do when trying to install @types/typescript.

**Comment by j-oliveras** [comment]
I'm guessing, but probably setting `moduleResolution` option to `node` value solve it.

**Comment by CyriacBr** [comment]
@j-oliveras That was it...Thank you.
