### ISSUE TITLE
Issue to enrich Window object

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/TypeScript#30285]
Hey there,

If i test this code, i got an error on  `doesntwork` which is not defined : 
```js
// => /types/window.ts
interface Window {
  something: () => void;
}

// => /index.ts
window.alert('its ok');  // works
window.something();      // works
window.doesntwork();     // don't works
```

But as soon as i try to import some types from `node_modules` in any way, i got an error `Property 'something' does not exist on type 'Window'.` not defined : 

```js
// => /types/window.ts
import * as LibTypes from 'lib-with-types';

interface Window {
  something: () => void;
  // whatIWant: LibTypes.type;   <= even without this, it does not work
}

// => /index.ts
window.alert('its ok');   // works
window.something();       // does not works 🤪
window.doesntwork();      // don't works
```

What i'm trying to do is setting the [raven-js](https://www.npmjs.com/package/raven-js) type to `window.Raven` but declare it globally, but it seems never work, because i'm unable to import this type.

**Comment by dragomirtitian** [comment]
If the file is a module you need to declare the type in global 


```ts
declare global {
    interface Window {
        something: () => void;
        // whatIWant: LibTypes.type;   <= even without this, it does not work
    }
}
export {}

window.alert('its ok');   // works
window.something();       // ok
window.doesntwork();
```

**Comment by DavidBabel** [comment]
Ow ! thanks for your answer, it actually does the trick. I cannot get why this `export {}` is enough to make it work.

It's not really for a sharable module, it's in my app code base. I now notice this two behaviors working : 
```js
declare global {
    interface Window {
        // anything
    }
}
export {}
```
or 
```js
import Raven from 'raven-js';

declare global {
    interface Window {
       Raven: Raven.RavenStatic;
    }
}
```
Since i import something it's automatically considered as module ? It wasn't very clear in the doc.

**Comment by dragomirtitian** [comment]
@DavidBabel  Yes anything that has an import or an export is automatically a module.

**Comment by DavidBabel** [comment]
Looks like a world of exception. I did not make it work to add a "valid field" in React / Typescript.
I wanted to add the field `"space"` in `svg` tag, but i did never make it work : 

```js
declare global {
  interface SVGAttributes {
    space?: string;
  }
}
export {};
```

My guess here is that I try to override React.SVGAttributes, but it's not clear in the doc either.

**Comment by dragomirtitian** [comment]
@DavidBabel  It's sometimes a bit tricky. You have to find the exact interface you are extending and see where it is defined. In this case `SVGAttributes` is defined in the `React` global namespace. To augment it this should work:

```ts
declare global {
    namespace React {
        interface SVGAttributes<T> {
            space?: string;
        }
    }
}

```
It has to be generic because the interface defined in `React` is generic and we need to have the same number of type parameters to any augmented interfaces. 

The topic of module augmentation is covered [here](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)

**Comment by DavidBabel** [comment]
It' actually working. Thanks for the trick and all the help.
This doc really miss a search field :)

I close the issue.
