### ISSUE TITLE
Unexpected splitting of "boolean" type in conditional types.

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/TypeScript#30280]
**TypeScript Version:**  3.4.0-dev.20190308

**Search Terms:** splitting boolean.

**Code**

```ts
interface Model<T> {}
type ConditionalType<T> = T extends never ? never : Model<T>;
type Result = ConditionalType<boolean>; // Model<false> | Model<true>
```
But without a conditional type works as expected:

```ts
interface Model<T> {}
type ConditionalType<T> = Model<T>;
type Result = ConditionalType<boolean>; // Model<boolean>
```

**Expected behavior:**
Not splitting boolean.

**Actual behavior:**
Splitting boolean.

[Playground Link](https://www.typescriptlang.org/play/index.html#src=interface%20Model%3CT%3E%20%7B%7D%0D%0Atype%20ConditionalType%3CT%3E%20%3D%20T%20extends%20never%20%3F%20never%20%3A%20Model%3CT%3E%3B%0D%0Atype%20Result%20%3D%20ConditionalType%3Cboolean%3E%3B%20%2F%2F%20Model%3Cfalse%3E%20%7C%20Model%3Ctrue%3E)

**Comment by jack-williams** [comment]
This is a design limitation: #22596. Booleans are just unions, and conditional types distribute over them accordingly.

**Comment by KostyaTretyak** [comment]
Wow! It's very unexpected, very...
