### ISSUE TITLE
Autocompletion in Classes when Implementing an Interface after Initial Fields 

### ISSUE THREAD

**Issue by hediet** [microsoft/TypeScript#30290]
**TypeScript Version:**  3.3.1

**Search Terms:** Refactoring, Interface Implementation Autocompletion

**Code**
```ts
interface X {
    bla: string;
}
class Y implements X {
    // autocomplete here (1)
	private readonly blub = "";
    // autocomplete here (2)
}
```
**Expected behavior:**
When autocompleting at 1 in vscode, is suggests the member `foo`.
When autocompleting at 2 in vscode, is suggests the member `foo`.

**Actual behavior:**
When autocompleting at 1 in vscode, is suggests the member `foo`.
When autocompleting at 2 in vscode, is suggests nothing.

![image](https://user-images.githubusercontent.com/2931520/54070996-827ff780-4267-11e9-884f-011ec37b2543.png)

![image](https://user-images.githubusercontent.com/2931520/54071010-a6433d80-4267-11e9-9f91-8b66b886108b.png)

[Playground link](https://www.typescriptlang.org/play/#src=interface%20X%20%7B%0D%0A%20%20%20%20bla%3A%20string%3B%0D%0A%7D%0D%0Aclass%20Y%20implements%20X%20%7B%0D%0A%20%20%20%20%2F%2F%20autocomplete%20here%20(1)%0D%0A%09private%20readonly%20blub%20%3D%20%22%22%3B%0D%0A%20%20%20%20%2F%2F%20autocomplete%20here%20(2)%0D%0A%7D%0D%0A)

It works however, when `blub` is not private.

**Comment by RyanCavanaugh** [comment]
This should be a fairly easy fix

**Comment by Kingwl** [comment]
Related: #30536?

**Comment by DanielRosenwasser** [comment]
Thanks @fuafa!
