### ISSUE TITLE
API: how to get TypeParameters of inferred higher order function

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#30296]
**TypeScript Version:**  3.4.0-dev.20190309

**Code**

```ts
// from #30215
declare function pipe<A extends any[], B, C>(ab: (...args: A) => B, bc: (b: B) => C): (...args: A) => C;

declare function list<T>(a: T): T[];
declare function box<V>(x: V): { value: V };

const listBox = pipe(list, box);  // <T>(a: T) => { value: T[] }

listBox(1); // <-- want to get TypeParameters here
```

Given a CallExpression, I want to get all type parameters of the resolved signature.
Before higher order function type inference, I could simply use `ts.getEffectiveTypeParameterDeclarations(checker.getResolvedSignature(node).declaration)`.

This doesn't work in the example above, because `signature.declaration` is `(...args: A) => C` which obviously has no declared type parameters.

I noticed there's `signature.typeParameters`, but that seems to always be `undefined` on instantiated signatures.
Using the debugger I could see that `signature.target.typeParameters` contains what I need, but `target` is internal.

Currently I'm trying to work around this by getting the type of `listBox` first and using the uninstantiated signature iff there's only one call signature. Otherwise I fall back to my previous solution because inferred higher order functions currently only work with a single call signature.
Is that the recommended way to solve my problem?

**Comment by RyanCavanaugh** [comment]
Doesn't look like there's a way to do it with the available public API. To really get the right answer you'd also need the `.mapper` and then instantiate the type with the provided the mapper.

More details on your use case would be useful if you'd like to see changes in the public API to accommodate some scenario.
