### ISSUE TITLE
TypeScript misses type of this

### ISSUE THREAD

**Issue by mike-marcacci** [Microsoft/TypeScript#30305]
**TypeScript Version:**  3.4.0-dev.20190310

**Search Terms:**
- static method this 
- reference constructor this
- this non class

**Code**

```ts
class Parent {
    static create() {

        // TypeScript always treats `new this()` as an instance of `Parent`, rather than
        // performing recursively bounded quantification 
        return new this();
    }
}

class Child extends Parent {
    foo: string = "bar"
}

// TypeScript thinks that the result of `Child.create()` will be an instance of `Parent`,
// but not of `Child`
const child: Child = Child.create();

// In fact, `child` is an instance of `Child`
console.log(child.constructor.name, child.foo)
```

**Expected behavior:**
TypeScript should use F-bounded polymorphism for `this` variables found in static methods, just as it does for instance methods. In this example, it should know that `child` is an instance of `Child`.

**Actual behavior:**
TypeScript incorrectly thinks that `child` is an instance of `Parent`, and *not* an instance of `Child`.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=class%20Parent%20%7B%0D%0A%20%20%20%20static%20create()%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20TypeScript%20treats%20%60this%60%20as%20%60Parent%60%2C%20rather%20than%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20performing%20recursively%20bounded%20quantification%20%0D%0A%20%20%20%20%20%20%20%20return%20new%20this()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Parent%20%7B%0D%0A%20%20%20%20foo%3A%20string%20%3D%20%22bar%22%0D%0A%7D%0D%0A%0D%0A%2F%2F%20TypeScript%20thinks%20that%20the%20result%20of%20%60Child.create()%60%20will%0D%0A%2F%2F%20be%20an%20instance%20of%20%60Parent%60%2C%20but%20not%20of%20%60Child%60%0D%0Aconst%20child%3A%20Child%20%3D%20Child.create()%3B%0D%0A%0D%0A%2F%2F%20In%20fact%2C%20%60child%60%20is%20an%20instance%20of%20%60Child%60%0D%0Aconsole.log(child.constructor.name%2C%20child.foo))

**Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/6331
- https://github.com/Microsoft/TypeScript/issues/29709

**Comment by dragomirtitian** [comment]
The issue seems covered by https://github.com/Microsoft/TypeScript/issues/5863 and the workaround presented there (or a variation of it) should work fine for the example you present. 


````ts
class Parent {
    static create<T extends  Parent>(this:new () =>T): T {

        // TypeScript treats `this` as `Parent`, rather than
        // performing recursively bounded quantification 
        return new this();
    }
}

class Child extends Parent {
    foo: string = "bar"
}

// TypeScript thinks that the result of `Child.create()` will
// be an instance of `Parent`, but not of `Child`
const child: Child = Child.create();

// In fact, `child` is an instance of `Child`
console.log(child.constructor.name, child.foo)
````

**Comment by mike-marcacci** [comment]
@dragomirtitian thanks for the lightning response! Yes, this is indeed a duplicate of #5863.
