### ISSUE TITLE
Computed Properties with Other Properties

### ISSUE THREAD

**Issue by rgrzywinski** [Microsoft/TypeScript#30309]
**TypeScript Version:** 3.4.0-dev.20190310

**Search Terms:**
computed properties

**Code**

```ts
export enum Role {
  admin = 'admin'
}
export type ThisWorks = {
  [R in Role]: boolean;
};
export type ThisDoesntWork = {
  uid: string;
  [R in Role]: boolean;
};
```

**Expected behavior:**
`ThisDoesntWork` compiles to effectively:
```ts
export type ThisDoesntWork = {
  uid: string;
  admin: boolean;
};
```

**Actual behavior:**
A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.
A computed property name must be of type 'string', 'number', 'symbol', or 'any'.

**Playground Link:** [Playground](https://typescript-play.js.org/#code/KYDwDg9gTgLgBMAdgVwLZwEoQDbDgbwCg44BDAE1QEtE4BeOAcgusUcIF9DRJY4YAnmDwAVABZUAzgHVoAa0n0CxOAG0McGphzAAugC44AIwg7SiANycrPaPEHC44qQBEIwSYhiyocpURJkKnJDSRgoGgBzKxJ1TVosXANjU1xzKw4LIA)

**Related Issues:** #29259

**Comment by jack-williams** [comment]
Should be covered by #26797.
