### ISSUE TITLE
New Listener typings on Document but not Element

### ISSUE THREAD

**Issue by simPod** [microsoft/TypeScript#30311]
On `Document`, there was added this listener typings

https://github.com/Microsoft/TypeScript/blob/b145eaf160e6b2729aaacb89856bc2346f85ac4c/lib/lib.dom.d.ts#L4571

However, it was not defined the same on `Element`

https://github.com/Microsoft/TypeScript/blob/b145eaf160e6b2729aaacb89856bc2346f85ac4c/lib/lib.dom.d.ts#L4925

Why I'm asking: When adding event listener on Element, I cannot type the event properly

`addEventListener('click', (e: MouseEvent) => {` is not possible, I have to do `addEventListener('click', (e: Event) => {`

Why is it so? Thanks!

**Comment by lemnis** [comment]
The [Element interface](https://dom.spec.whatwg.org/#interface-element) doesn't include the GlobalEventListeners as stated in the specification, where the [HTMLElement interface](https://html.spec.whatwg.org/multipage/dom.html#elements-in-the-dom) and [SVGElement interface](https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement) does.

Still, the browsers maybe support the specific events on a Element instance, but this is only relevant for MathML elements.
