### ISSUE TITLE
Unification with a null property works wrong

### ISSUE THREAD

**Issue by worudso** [Microsoft/TypeScript#30313]
**TypeScript Version:**  3.3.3333

**Search Terms:**

**Code**
```typescript
type A = {
  b: string,
} | {
  b: null,
};

let a: A;
```

**Expected behavior:**
`a.b`'s type is `string | null`.
**Actual behavior:**
It's `string`.
It works well when it has `b: number` instead of `b: null`.
**Playground Link:**  https://www.typescriptlang.org/play/#src=type%20A%20%3D%20%7B%0D%0A%20%20b%3A%20string%2C%0D%0A%7D%20%7C%20%7B%0D%0A%20%20b%3A%20null%2C%0D%0A%7D%3B%0D%0A%0D%0Alet%20a%3A%20A%3B

**Related Issues:**

**Comment by j-oliveras** [comment]
I see no problems:
![imatge](https://user-images.githubusercontent.com/15308683/54115146-3ca06c00-43ec-11e9-97dd-392b1b371453.png)
Did you enabled `strictNullChecks`?
