### ISSUE TITLE
Proposal: Support defaulting to string enum in tsconfig

### ISSUE THREAD

**Issue by sanchitgn** [Microsoft/TypeScript#30318]
## Suggestion

I find myself using `string enums` more often than not. It would be easier if I could configure TS (tsconfig - `stringEnums`) to default to string enums and allow for numbers as overrides

```
enum FetchStatus {
  SUCCESS,
  PENDING,
  FAILED,
  TODO
}
```

### Current Behaviour
```
(function (FetchStatus) {
    FetchStatus[FetchStatus["SUCCESS"] = 0] = "SUCCESS";
    FetchStatus[FetchStatus["PENDING"] = 1] = "PENDING";
    FetchStatus[FetchStatus["FAILED"] = 2] = "FAILED";
    FetchStatus[FetchStatus["TODO"] = 3] = "TODO";
})(FetchStatus || (FetchStatus = {}));
```

### Configured behaviour
```
var FetchStatus;
(function (FetchStatus) {
    FetchStatus["SUCCESS"] = "SUCCESS";
    FetchStatus["PENDING"] = "PENDING";
    FetchStatus["FAILED"] = "FAILED";
    FetchStatus["TODO"] = "TODO";
})(FetchStatus || (FetchStatus = {}));
```

## Use Cases
It would make it easier to 
1. debug/log enums
2. Share types between server & client

## Search Terms

default string enum, tsconfig string enum

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We really don't do features where the core meaning of a block of code depends on what the tsconfig says. This also creates problems with .d.ts files - these would have to be left alone, and it's confusing to have one behavior for enums in .d.ts files and another for enums in .ts files.
