### ISSUE TITLE
CFA doesn't work with generic constraint type

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#30316]
**TypeScript Version:**  3.4.0-dev.20190307

**Search Terms:**

**Code**

```ts
function foo<K extends 'a' | 'b'>(k: K) {
  if (k === 'a') {
     const x: 'a' = k; // Type 'K' is not assignable to type '"a"
  }
}
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by jack-williams** [comment]
Related: #20375
