### ISSUE TITLE
Allow `export as namespace` alongside commonJS's export =

### ISSUE THREAD

**Issue by tnrich** [Microsoft/TypeScript#30327]
## Search Terms
export as namespace lodash umd commonjs

## Suggestion
This is coming from this issue: 
https://github.com/Microsoft/TypeScript/issues/29039

Basically vscode auto-import won't work with lodash's .d.ts file because, and I quote @aleclarson:
>When `export =` is used, a CommonJS module is implied, which means named exports (eg: `export const`) are no longer allowed (since that's an ESM feature). The problem is that named exports are required for auto-import to work.

He suggested that I open a new proposal for:
> `export as namespace` to be used as a hint that auto-import can suggest the namespace's properties. 

## Use Cases
This would allow lodash to be auto-completed because named exports would then be allowed side-by-side with commonJS.

## Checklist

My suggestion meets these guidelines:

* [?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [?] This wouldn't change the runtime behavior of existing JavaScript code
* [?] This could be implemented without emitting different JS based on the types of the expressions
* [?] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [?] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Thanks!

Linked issues: 
https://github.com/Microsoft/TypeScript/issues/10907
https://github.com/Microsoft/TypeScript/issues/24719
https://github.com/Microsoft/TypeScript/issues/26299

**Comment by RyanCavanaugh** [comment]
#29039 is completely off the rails 😢

`export as namespace` has nothing to do with `import _ = require("lodash")`, and UMD-ness doesn't affect whether or not auto-imports are available from a file. The ability to destructure from a module that purports to be a CommonJS module via an `export = ` declaration is a feature that would occur based on the *loader*, not the *module*.
