### ISSUE TITLE
output declaration type random change order

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#30328]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

output declaration type random change order

case 1

- https://github.com/bluelovers/node-novel-downloader/commit/fdc477ffdbe79b16c4a9de8de81b9e00061f97c2

case 2

- https://github.com/bluelovers/novel-travis-test/commit/3b88745e187736797d9a30d4f4bbd927b0c6dd30#diff-3006c96d8657ccca5b9b3618a256314c
- https://github.com/bluelovers/novel-travis-test/commit/d33c4a61602a8536d1414d36e027eb99845104f1#diff-3006c96d8657ccca5b9b3618a256314c
- https://github.com/bluelovers/novel-travis-test/commit/2d749195c39ef386e6c4bad1ae6e19d007c03e93#diff-3006c96d8657ccca5b9b3618a256314c

**Expected behavior:**

output order should always is same

**Actual behavior:**

![image](https://user-images.githubusercontent.com/167966/54166011-1935f980-449e-11e9-983d-3f0522203fdd.png)

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
These are all equivalent and the compiler is allowed to produce different outputs for different inputs.
