### ISSUE TITLE
Free type parameter no longer inferred in context of target

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#30324]
From https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33704

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Code**

```ts
declare function identity<T>(a: T): T;
declare function times<T>(fn: (i: number) => T): (n: number) => T[];
const a2 = times(identity)(5); // => [0, 1, 2, 3, 4]
```

**Expected behavior:**
No error.

**Actual behavior:**
```
Argument of type '<T>(a: T) => T' is not assignable to parameter of type '(i: number) => T'.
  Type 'number' is not assignable to type 'T'.
```

From @googol
> I would have thought though that in R.times(R.identity) the type parameter T would be hoisted from R.identity to the composition such that R.times(R.identity): <T>(n: number) => T[]

I, personally, am surprised the `times` call fails - `<T>(x: T) => T` obviously satisfies `(i: number) => T`; The free `T` in `identity` should infer to `number` (due to instantiating the method in the context of the target), which should then provide an inference for the `T` on the target side (as now the return type should be instantiated to `number`). This is definitely [what used to happen](http://www.typescriptlang.org/play/#src=declare%20function%20identity%3CT%3E(a%3A%20T)%3A%20T%3B%0D%0Adeclare%20function%20times%3CT%3E(fn%3A%20(i%3A%20number)%20%3D%3E%20T)%3A%20(n%3A%20number)%20%3D%3E%20T%5B%5D%3B%0D%0Aconst%20a2%20%3D%20times(identity)(5)%3B%20%2F%2F%20%3D%3E%20%5B0%2C%201%2C%202%2C%203%2C%204%5D) (or something similar), so seems like a significant break.

cc @ahejlsberg - this seems like a sideffect of the better `pipe`-like checking we added last week.

**Comment by googol** [comment]
I'm still getting the same errors on my ramda PR (that I rebased on master and force pushed).
Am I missing something?

PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33799
Latest test log: https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/508092409?utm_source=github_status&utm_medium=notification

**Comment by weswigham** [comment]
We merged the fix this morning, it won't hit `@next` till tomorrow ❤️

**Comment by googol** [comment]
Ah, of course! Thanks for all the awesome stuff on TS!
