### ISSUE TITLE
Expose new module targets in Project properties and build targets

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3033]
We have added two new module targets, umd and system, we need to expose both in:

-  [x] Project properties in C#/VB project -- Dev12 
-  [x] Project properties in C#/VB project -- Dev14
-  [x] Project properties in JSProj project -- Dev12
-  [x] Project properties in JSProj project -- Dev14
-  [x] build targets -- Dev12
-  [x] build targets -- Dev14
-  [x] tools\options page -- Dev12
-  [x] tools\options page -- Dev14

One thing to figure out, is if `TypeScriptToolsVersion` is below 1.5, do we still pass in the module value, should it be an error?

**Comment by mhegazy** [comment]
updates to expose new flags tracked by #3034

**Comment by paulvanbrenk** [comment]
We allow the user to specify unsupported modules even if they target an older version of the compiler, the compiler will display a useful error when that happens.

**Comment by paulvanbrenk** [comment]
Should be in 1.5 RTM for VS 2013 and VS 2015
