### ISSUE TITLE
Incorrect type inference when conditionally inferring multiple types

### ISSUE THREAD

**Issue by ylibrach** [Microsoft/TypeScript#30341]
**TypeScript Version:**  3.4.0-dev.20190312

**Code**

The following code throws the indicated error:

```ts
type Action<T extends string, P> = { readonly type: T; payload: P; }
type ActionCreator<T extends string, P> = { readonly type: T, (payload: P): Action<T, P> };
type Reducer<S, T extends string, P> = (state: S, action: Action<T, P>) => S;
type ReducerFor<S, AC> = AC extends ActionCreator<infer T, infer P> ? Reducer<S, T, P> : never;

declare function handleAction<AC>(action: AC, reducer: ReducerFor<{ value: string }, AC>): void;
declare const SomeAction: ActionCreator<"TestAction", string>;

handleAction(SomeAction, (state, action) => ({ ...state, value: action.payload }));
/*                               ^ resolved as Action<string, {}>      ^ error appears here:
Type '{}' is not assignable to type 'string'.ts(2322)
The expected type comes from property 'value' which is declared here on type '{ value: string; }'
*/
```
As indicated in the comments, `action` is being resolved as `Action<string, {}>` instead of `Action<"TestAction", string>`.

However, if I write the conditional inference in a different way, then this will work:

```ts
type ReducerFor<S, AC> = 
   Reducer<S, AC extends ActionCreator<infer T, any> ? T : never, 
              AC extends ActionCreator<any, infer P> ? P : never>;

declare const SomeAction: ActionCreator<"TestAction", string>;

handleActionTest(SomeAction, (state, action) => ({ ...state, value: action.payload }));
//                                   ^ correctly resolved as Action<"TestAction", string>
```

**Expected behavior:**
The compiler should correctly handle the type inference and return a type of `Action<"TestAction", string>`

**Actual behavior:**
Incorrect type inference to `Action<string, {}>`

**Playground Link:** 
[Link with issue](https://www.typescriptlang.org/play/index.html#src=type%20Action%3CT%20extends%20string%2C%20P%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20type%3A%20T%0D%0A%20%20%20%20payload%3A%20P%3B%0D%0A%7D%0D%0A%0D%0Atype%20ActionCreator%3CT%20extends%20string%2C%20P%3E%20%3D%20%7B%20%0D%0A%20%20%20%20readonly%20type%3A%20T%2C%20%0D%0A%20%20%20%20(payload%3A%20P)%3A%20Action%3CT%2C%20P%3E%20%0D%0A%7D%3B%0D%0A%0D%0Atype%20Reducer%3CS%2C%20T%20extends%20string%2C%20P%3E%20%3D%20(state%3A%20S%2C%20action%3A%20Action%3CT%2C%20P%3E)%20%3D%3E%20S%3B%0D%0A%0D%0Atype%20ReducerFor%3CS%2C%20AC%3E%20%3D%20AC%20extends%20ActionCreator%3Cinfer%20T%2C%20infer%20P%3E%20%3F%20Reducer%3CS%2C%20T%2C%20P%3E%20%3A%20never%3B%0D%0A%0D%0Adeclare%20const%20SomeAction%3A%20ActionCreator%3C%22TestAction%22%2C%20string%3E%3B%0D%0Adeclare%20function%20handleActionTest%3CAC%3E(action%3A%20AC%2C%20reducer%3A%20ReducerFor%3C%7B%20value%3A%20string%20%7D%2C%20AC%3E)%3A%20void%3B%0D%0A%0D%0AhandleActionTest(SomeAction%2C%20(state%2C%20action)%20%3D%3E%20(%7B%20...state%2C%20value%3A%20action.payload%20%7D))%3B)

[Link with workaround](https://www.typescriptlang.org/play/index.html#src=type%20Action%3CT%20extends%20string%2C%20P%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20type%3A%20T%0D%0A%20%20%20%20payload%3A%20P%3B%0D%0A%7D%0D%0A%0D%0Atype%20ActionCreator%3CT%20extends%20string%2C%20P%3E%20%3D%20%7B%20%0D%0A%20%20%20%20readonly%20type%3A%20T%2C%20%0D%0A%20%20%20%20(payload%3A%20P)%3A%20Action%3CT%2C%20P%3E%20%0D%0A%7D%3B%0D%0A%0D%0Atype%20Reducer%3CS%2C%20T%20extends%20string%2C%20P%3E%20%3D%20(state%3A%20S%2C%20action%3A%20Action%3CT%2C%20P%3E)%20%3D%3E%20S%3B%0D%0A%0D%0Atype%20ReducerFor%3CS%2C%20AC%3E%20%3D%20Reducer%3CS%2C%20AC%20extends%20ActionCreator%3Cinfer%20T%2C%20any%3E%20%3F%20T%20%3A%20never%2C%20AC%20extends%20ActionCreator%3Cany%2C%20infer%20P%3E%20%3F%20P%20%3A%20never%3E%3B%0D%0A%0D%0Adeclare%20const%20SomeAction%3A%20ActionCreator%3C%22TestAction%22%2C%20string%3E%3B%0D%0Adeclare%20function%20handleActionTest%3CAC%3E(action%3A%20AC%2C%20reducer%3A%20ReducerFor%3C%7B%20value%3A%20string%20%7D%2C%20AC%3E)%3A%20void%3B%0D%0A%0D%0AhandleActionTest(SomeAction%2C%20(state%2C%20action)%20%3D%3E%20(%7B%20...state%2C%20value%3A%20action.payload%20%7D))%3B)

**Comment by RyanCavanaugh** [comment]
The preferred signature would be
```ts
declare function handleAction<Q extends string, U>(action: ActionCreator<Q, U>, reducer: ReducerFor<{ value: string }, ActionCreator<Q, U>>): void;
```
which works as expected and will give you better errors when incorrectly invoked

@ahejlsberg here's a simplified repro
```ts
type InnerBox<T> = {
  value: T;
}

type OuterBox<T> = {
  inner: InnerBox<T>
};

type BoxConsumerFromOuterBox<TProducer> =
  TProducer extends OuterBox<infer TContent> ?
      (box: InnerBox<TContent>) => void :
      never;

declare function passContentsToFunc<T>(outerBox: T, consumer: BoxConsumerFromOuterBox<T>): void;

declare const OuterBoxOfString: OuterBox<string>;
passContentsToFunc(OuterBoxOfString, box => {
  // Error, but should be OK
  // Note: LS shows desired types in many locations!
  const p: string = box.value;
});
```
