### ISSUE TITLE
Index signature required in interface but not in object type

### ISSUE THREAD

**Issue by calebmer** [Microsoft/TypeScript#30345]
**TypeScript Version:**  3.3.3

**Search Terms:** index signature, interface, object type

**Code**

```ts
interface A {
    p: number,
    q: string,
}

type B = {
    p: number,
    q: string,
};

type JSONObjectValue = {
    [key: string]: number | string,
};

declare const a: A;
declare const b: B;

const jsonA: JSONObjectValue = a;
const jsonB: JSONObjectValue = b;
```

**Expected behavior:** Both `a` should be assignable to `jsonA` and `b` should be assignable to `jsonB`.

**Actual behavior:** `jsonA = a` errs but `jsonB = b` does not err.

[**Playground Link**](http://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0A%20%20%20%20p%3A%20number%2C%0A%20%20%20%20q%3A%20string%2C%0A%7D%0A%0Atype%20B%20%3D%20%7B%0A%20%20%20%20p%3A%20number%2C%0A%20%20%20%20q%3A%20string%2C%0A%7D%3B%0A%0Atype%20JSONObjectValue%20%3D%20%7B%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20number%20%7C%20string%2C%0A%7D%3B%0A%0Adeclare%20const%20a%3A%20A%3B%0Adeclare%20const%20b%3A%20B%3B%0A%0Aconst%20jsonA%3A%20JSONObjectValue%20%3D%20a%3B%0Aconst%20jsonB%3A%20JSONObjectValue%20%3D%20b%3B%0A)

---

**Use case:** I have a type `JSONValue` (which I’ve seen before in some DefinitelyTyped libraries) to make sure an object is a valid JSON value. Which would mean it doesn’t contain functions or other problematic properties.

```ts
export type JSONValue = null | boolean | number | string | JSONArrayValue | JSONObjectValue;
export interface JSONArrayValue extends ReadonlyArray<JSONValue> {}
export type JSONObjectValue = {readonly [key: string]: JSONValue};
```

I also have some interfaces which inherit from each other using `extends` which should be valid JSON values. Which is why I would prefer to use an interface over an object type in this case.

**Comment by jack-williams** [comment]
Is this covered by #15300?

**Comment by calebmer** [comment]
Yes it is!
