### ISSUE TITLE
Expose new compiler flags in the .targets file

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3034]
We have added a set of new flags over the course of this release, we need to add MSBuild properties for them in VS 2013 and VS 2015 in .target files as well as in the project properties.

**VS 2013**
- [x] [--rootDir](https://github.com/Microsoft/TypeScript/pull/2772)
- [x] [--noEmitHelpers](https://github.com/Microsoft/TypeScript/pull/2901)
- [x] [--inlineSourceMap](https://github.com/Microsoft/TypeScript/pull/2484)
- [x] [--inlineSources](https://github.com/Microsoft/TypeScript/pull/2484)
- [x] [--newLine](https://github.com/Microsoft/TypeScript/pull/2921)
- [x] [--separateCompilation](https://github.com/Microsoft/TypeScript/pull/2550) 
- [x] [--emitDecoratorMetadata](https://github.com/Microsoft/TypeScript/pull/2589)

**VS 2015**
- [x] [--rootDir](https://github.com/Microsoft/TypeScript/pull/2772)
- [x] [--noEmitHelpers](https://github.com/Microsoft/TypeScript/pull/2901)
- [x] [--inlineSourceMap](https://github.com/Microsoft/TypeScript/pull/2484)
- [x] [--inlineSources](https://github.com/Microsoft/TypeScript/pull/2484)
- [x] [--newLine](https://github.com/Microsoft/TypeScript/pull/2921)
- [x] [--separateCompilation](https://github.com/Microsoft/TypeScript/pull/2550) 
- [x] [--emitDecoratorMetadata](https://github.com/Microsoft/TypeScript/pull/2589)

> Note: `separateCompilation` flag name could change based on the design meeting discussion for #2499

**Comment by mhegazy** [comment]
@paulvanbrenk, i do not know if any of these need to be in the UI as well.

**Comment by mhegazy** [comment]
Updates to the new module targets tracked by #3033

**Comment by danquirk** [comment]
Include emitDecoratorMetadata too (see #3061)?

**Comment by mhegazy** [comment]
updated to include emitDecoratorMetaData.

**Comment by cmichaelgraham** [comment]
is there a way to know when this becomes available in the beta install for vs 2013?  i'm working on some aurelia samples for the typescript samples repo :+1:

**Comment by mhegazy** [comment]
it is going to be in the next public VS release. for now you can set these in TypeScriptAdditionalFlags:
```XML
<TypeScriptAdditionalFlags> $(TypeScriptAdditionalFlags) --emitDecoratorMetaData </TypeScriptAdditionalFlags>
```

**Comment by cmichaelgraham** [comment]
@mhegazy oh that is soooooo cool !!!

**Comment by cmichaelgraham** [comment]
@mhegazy it works as you say, but there is a very small typo in the compiler flag:

this: `emitDecoratorMetaData` should be this: `emitDecoratorMetadata`

so the entire tag looks like this:

```xml
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
    <TypeScriptModuleKind>amd</TypeScriptModuleKind>
    <TypeScriptAdditionalFlags> $(TypeScriptAdditionalFlags) --emitDecoratorMetadata </TypeScriptAdditionalFlags>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TypeScriptRemoveComments>true</TypeScriptRemoveComments>
    <TypeScriptSourceMap>false</TypeScriptSourceMap>
    <TypeScriptAdditionalFlags> $(TypeScriptAdditionalFlags) --emitDecoratorMetadata </TypeScriptAdditionalFlags>
  </PropertyGroup>
```

**Comment by mhegazy** [comment]
thanks @cmichaelgraham for the correction.

**Comment by paulvanbrenk** [comment]
edit: made 2 lists

**Comment by mhegazy** [comment]
PR #3208 updates the remaining flag (--isolatedModules)

**Comment by paulvanbrenk** [comment]
This should be in 1.5 RTM for both VS 2013 and VS 2015

**Comment by atsu85** [comment]
Hi,
Everything works as expected when i do "Build" or "Rebuild" on the project,
but when i just save typescript file, then during compilation decorator metadata is not added to the js file as if "--emitDecoratorMetadata" compiler flag isn't taken into account.

Expected:
SomeClassWithAutoinject = decorate([
aurelia_framework_1.autoinject, metadata('design:paramtypes', [aurelia_router_1.Router, app_state_1.AppState])
], SomeClassWithAutoinject );

Actual:
SomeClassWithAutoinject = __decorate([
aurelia_framework_1.autoinject
], SomeClassWithAutoinject );

I can reproduce this issue with @cmichaelgraham sample project without any modifications:
1) open https://github.com/cmichaelgraham/aurelia-typescript/blob/typescript-1-5-port/skel-nav-esri-vs-ts/skel-nav-esri-vs-ts.sln
with Visual Studio (same problem with 2015 and 2013) with TS 1.5 plugin
2) change (i.e. adding a space) https://github.com/cmichaelgraham/aurelia-typescript/blob/typescript-1-5-port/skel-nav-esri-vs-ts/skel-nav-esri-vs-ts/views/flickr.js
3) save

Any ideas what do I have to configure to make it work on save just as it is working on manual build/rebuild?

I haven't found a way through VS settings dialogs to tell VS2015 compiler to use "--emitDecoratorMetadata", but this flag is added to the Debug and Release configurations:
https://github.com/cmichaelgraham/aurelia-typescript/blob/typescript-1-5-port/skel-nav-esri-vs-ts/skel-nav-esri-vs-ts/skel-nav-esri-vs-ts.csproj#L129
as described above.

**Comment by rsnider19** [comment]
I am seeing the same problem as @atsu85 where the metadata won't get created with a simple save. Any updates on that?

**Comment by billti** [comment]
Reopening this for investigation. @paulvanbrenk , can you verify if the compiler options in question are being honored when using compile-on-save? Thanks.

**Comment by paulvanbrenk** [comment]
This happens because in the project @atsu85 refers to the compiler flags for the metadata are specified as part of the `<TypeScriptAdditionalFlags>` element in the project file. If you replace that element with the following:
```xml
    <TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators>
    <TypeScriptEmitDecoratorMetadata>true</TypeScriptEmitDecoratorMetadata>
```
Compile on save will work as expected.

**Comment by rsnider19** [comment]
Thanks @paulvanbrenk that works perfectly. Now I don't have to rebuild every time I make a change which means that I can just leave the project debugging and open in my browser.

**Comment by mhegazy** [comment]
for future searches, MSBuild properties mapping to compiler flags are documented in https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects
