### ISSUE TITLE
Intersection type does not subtype with union type that contains the same intersection

### ISSUE THREAD

**Issue by calebmer** [microsoft/TypeScript#30340]
**TypeScript Version:**  3.3.3

**Search Terms:** intersection type, union type

**Code**

I was trying to simulate nominal types with `unique symbol` like this:

```ts
export type AccountID = number & typeof AccountID;
declare const AccountID: unique symbol;

declare const id: AccountID;
const test: AccountID | undefined = id;
```

A narrower reproducing case is this:

```ts
declare const a: number & string;
const b: (number & string) | undefined = a;
```

**Expected behavior:** This example should pass type checking.

**Actual behavior:**

This example fails with:

```
Type 'number & string' is not assignable to type 'undefined'.
```

[**Playground Link**](https://www.typescriptlang.org/play/index.html#src=declare%20const%20a%3A%20number%20%26%20string%3B%0Aconst%20b%3A%20(number%20%26%20string)%20%7C%20undefined%20%3D%20a%3B)

**Comment by calebmer** [comment]
Interestingly, intersecting with an object type works:

```ts
declare const a: number & {};
const b: (number & {}) | undefined = a;
```

Which solves my original use case:

```ts
export type AccountID = number & {type: typeof AccountID};
declare const AccountID: unique symbol;

declare const id: AccountID;
const test: AccountID | undefined = id;
```

Still posting a report in case this behavior was unknown.

**Comment by RyanCavanaugh** [comment]
`number & string` is `never`, same as `number & symbol` - values of that kind cannot exist. Naturally you cannot assign *from* such a value into any type.

See #202 for alternate workarounds.

**Comment by calebmer** [comment]
In this case, I’m using intersection types for their algebraic properties and not their set-theoretic properties. Replacing `number & string` with `never` does not error. Should the `never` case error or the `number & string` one pass?

```ts
declare const a: never;
const b: never | undefined = a;
```

**Comment by RyanCavanaugh** [comment]
When encountering `(number & string) | undefined`, the expansion of `(A & B) | C` to `(A & C) | (B & C)` occurs before the `number & string` -> `never` reduction. So TS sees
```ts
declare const a: never;
const b: (number & undefined) | (string & undefined) = a;
```
