### ISSUE TITLE
TypeScript type validation

### ISSUE THREAD

**Issue by potapovDim** [Microsoft/TypeScript#30353]
TypeScript type validation

Type validation does not work if parameter null or undefined

**TypeScript Version: 3.3.3333**

**Search Terms:**

**Code**

```ts

class TestClassExampleNull {
  constructor() {/** */}
  public exec(data: {a: string}) {
    console.log(data)
  }
}

const testClassExampleNull = new TestClassExampleNull()
testClassExampleNull.exec({a: null})


class TestClassExampleUndefined {
  constructor() {/** */}
  public exec(data: {a: string}) {
    console.log(data)
  }
}

const testClassExampleUndefined = new TestClassExampleUndefined()
testClassExampleUndefined.exec({a: undefined})

```

**Expected behavior: Should fail because of Type 'null' is not assignable to type 'string'**
**Expected behavior: Should fail because of Type 'undefined' is not assignable to type 'string'**

**Actual behavior: Works without error**

**Comment by dragomirtitian** [comment]
This works as expected if `strictNullChecks` are enabled, or am I missing something ?

[Link to sample with error](https://typescript-play.js.org/#code/MYGwhgzhAEAqCmEAuBhcUCiAPMBbADiPAHICuII0A3gFDTTAD2AdsgE6nBKNsAUAlNQD0AKhHQRQgL51o+UgCMQAS2DR4WeMF4ATMEjAAuakejtlzAOZTBtevSatGRAHQhGl3frD9ZMmTSOyNBIiKjoENh4hCTklAC80MzwAO5wYWiQkTgERGQUAjShyJmYOTH5IC4aWrxUpsxxNjQtoFnpJRFRufAAqsw68ABmFvA61LJBSBxcPALCYhLSsvJKquqa2noGxvXG5lY2E-YMLBDO8G4eXga+9P6tZ0ghGV3lRP2DI8njiclpCE6WW6MU+w1GOkKxXCwPefQG4J+1U2dVMpAR3zGNiAA)

**Comment by potapovDim** [comment]
@dragomirtitian yes, thanks, works as expected
