### ISSUE TITLE
Remove `undefined` from generic type with optional field.

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#30352]
**TypeScript Version:**  3.3.3.3333xxxxx

**Search Terms:**

**Code**

```ts
interface Prop { 
    foo: number,
    bar?: 'apple' | 'banana',
}

type Fn<T> = (p: T) => T

// Type works like ({ foo, bar }: Prop) => { foo: number; bar: "apple" | "banana" | undefined; }
const test1: Fn<Prop> = ({ foo, bar = 'apple' }) => ({ foo, bar })
// Type is ({ foo, bar }: Prop) => { foo: number; bar: "apple" | "banana"; }
const test2 = ({ foo, bar = 'apple' }: Prop) => ({ foo, bar })
```

**Expected behavior:**

The return type of `test1` should remove the `undefined` from the input type, just like `test2` does.

**Actual behavior:**

We have provided the default value to the `bar` filed, non-generic `test2` eliminated `undefined` but `test1` doesn't.

**Playground Link:** 

[Playground](http://www.typescriptlang.org/play/index.html#src=interface%20Prop%20%7B%20%0D%0A%20%20%20%20foo%3A%20number%2C%0D%0A%20%20%20%20bar%3F%3A%20'apple'%20%7C%20'banana'%2C%0D%0A%7D%0D%0A%0D%0Atype%20Fn%3CT%3E%20%3D%20(p%3A%20T)%20%3D%3E%20T%0D%0A%0D%0A%2F%2F%20Type%20works%20like%20(%7B%20foo%2C%20bar%20%7D%3A%20Prop)%20%3D%3E%20%7B%20foo%3A%20number%3B%20bar%3A%20%22apple%22%20%7C%20%22banana%22%20%7C%20undefined%3B%20%7D%0D%0Aconst%20test1%3A%20Fn%3CProp%3E%20%3D%20(%7B%20foo%2C%20bar%20%3D%20'apple'%20%7D)%20%3D%3E%20(%7B%20foo%2C%20bar%20%7D)%0D%0A%2F%2F%20Type%20is%20(%7B%20foo%2C%20bar%20%7D%3A%20Prop)%20%3D%3E%20%7B%20foo%3A%20number%3B%20bar%3A%20%22apple%22%20%7C%20%22banana%22%3B%20%7D%0D%0Aconst%20test2%20%3D%20(%7B%20foo%2C%20bar%20%3D%20'apple'%20%7D%3A%20Prop)%20%3D%3E%20(%7B%20foo%2C%20bar%20%7D)%0D%0A%0D%0A%2F%2F%20%7B%20foo%3A%20number%3B%20bar%3A%20%22apple%22%20%7C%20%22banana%22%20%7C%20undefined%3B%20%7D%0D%0Aconst%20i%20%3D%20test1(%7B%20foo%3A%2042%2C%20bar%3A%20'banana'%20%7D)%0D%0A)

**Comment by jack-williams** [comment]
This is unrelated to generics. The same behaviour occurs using a non-generic type annotation.
```ts
type Fn = (p: Prop) => Prop
const test1: Fn = ({ foo, bar = 'apple' }) => ({ foo, bar })
// { foo: number; bar: "apple" | "banana" | undefined; }
const i = test1({ foo: 42, bar: 'banana' })
```

The behaviour seems reasonable to me; you are annotating `test1` with an explicit type and TypeScript is simply using the function at that type. If you don't want `test1` to have the type it does you can either remove the annotation (as you have done), or change the annotation.
```ts
type Fn = (p: Prop) => Required<Prop>
```

**Comment by RyanCavanaugh** [comment]
Duplicate #30488
