### ISSUE TITLE
Unexpected literal widening when using generic function return type

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#30354]
**TypeScript Version:**  3.3.3333

**Search Terms:** type literal function generic widen

**Code**

```ts
const identity = <A>(arg: A) => arg;

const anything: any = {};

{
    // value has type `'foo'`
    const value: 'foo' = anything;
    // Expected and actual type: { size: 'foo' }
    const test = { value };
}

{
    // value has type `'foo'`
    const value = identity('foo');
    // Expected type: { value: 'foo' }
    // Actual type: { value: string }
    const test = { value };
}
```

**Comment by RyanCavanaugh** [comment]
This is the difference between a widening literal and a non-widening literal, which isn't a distinction we show in the type display. Soon™ we'll have a documentation page that explains what's going on in more detail.

**Comment by MartinJohns** [comment]
With TypeScript 3.4 this can be slightly improved using #29510 [const contexts for literal expressions](https://github.com/Microsoft/TypeScript/pull/29510):

    identity('foo' as const);
