### ISSUE TITLE
Cannot assign constrained value to generic type

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#30361]
**TypeScript Version:**  3.4.0-dev.20190313

**Search Terms:**

**Code**

```ts
function foo<T extends { id: string }>() {
   const x: { [P in keyof T]?: T[P] } = { id: '' };
   // Type '{ id: ""; }' is not assignable to type '{ [P in keyof T]?: T[P] | undefined; }
}
// or 
function foo<T extends { id: string }>(x: Partial<T> = {id: ''}) {}
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by jack-williams** [comment]
The error is right here. To copy from another comment:

The constraint `T extends { id: string }` says that whatever type `T` gets selected to be, it must be at least as specific as `{ id: string }`, but it could be more specific. For example, you could instantiate `T` with a type that has known properties of literal type, such as:
```ts
foo<{ id: "not empty" }>()
```
In this case assigning `''`  to `id` would not respect the type of `T`.

In general, using a generic type that does not appear in the input types is usually wrong. Is there a specific reason for needing `foo` to be generic?

**Comment by cevek** [comment]
Yeah, you're right. Thank you!
