### ISSUE TITLE
Incorrectly deprecated methods on SVGSVGElement

### ISSUE THREAD

**Issue by jabrouwer82** [Microsoft/TypeScript#30368]
There are five methods on SVGSVGElement that I believe are falsely marked as deprecated. setCurrentTime, pauseAnimations, unpauseAnimations, animationsPaused, and getCurrentTime.

They're not directly listed on the [SVG 2 candidate spec](https://www.w3.org/TR/SVG2/) nor the [SVG 1.1 to 2 changes document](https://svgwg.org/svg-next/changes.html), but are instead listed in the [SVG 2 Animation Candidate Document](https://svgwg.org/specs/animations/#InterfaceSVGSVGElement) that both of the previously mentioned documents reference.

**TypeScript Version:** 
I'm noticed the issue in 3.1.6, but they seem to be marked deprecated in the repo right now.

**Search Terms:**
svg SVGSVGElement deprecated setCurrentTime getCurrentTime animationsPaused unpauseAnimation pauseAnimation

**Code**

```ts
const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
svg.setCurrentTime(4)
```

**Expected behavior:**
No lint warnings about deprecated methods

**Actual behavior:**
A linter warning about setCurrentTime being deprecated.

**Playground Link:**
[I don't think the playground shows deprecation messages, but here's a link.](https://www.typescriptlang.org/play/#src=const%20svg%20%3D%20document.createElementNS('http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%2C%20'svg')%3B%0Asvg.setCurrentTime(4))

**Related Issues:**
None that I can tell.

**Comment by Fabianopb** [comment]
Hi @jabrouwer82 I could work on this one!
the deprecation flag has to be removed from `setCurrentTime`, `pauseAnimations`, `unpauseAnimations`, and `getCurrentTime`
However it seems to me that `animationsPaused` is not even implemented, so it has to be implemented, am I correct?

**Comment by jabrouwer82** [comment]
I believe that is the case, thanks!

**Comment by Fabianopb** [comment]
PR created in TSJS-lib-generator!
https://github.com/Microsoft/TSJS-lib-generator/pull/682
