### ISSUE TITLE
Broken Source Maps

### ISSUE THREAD

**Issue by hediet** [microsoft/TypeScript#30364]
**TypeScript Version:**  3.4.0-dev.20190311

**Search Terms:** Sourcemap

**Code**

```ts

function test(f: Function): { a: string } {
    f();
    return { a: "test" };
}

const { a: b } = test(() => {
    console.log("foo1");
    console.log("foo2");
});

const data = test(() => {
    console.log("foo3");
    console.log("foo4");
});

```
tsconfig.json
```json
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */

    "strict": true,                           /* Enable all strict type-checking options. */

    "esModuleInterop": true,
    "sourceMap": true,
    "outDir": "out",
  },
  "include": ["index.ts"]
}
```

**Expected behavior:**
Both arrow functions are mapped properly.

**Actual behavior:**
Only the second arrow function is mapped properly.

**Playground Link:**
[Source-Map-Visualization](https://sokra.github.io/source-map-visualization/#base64,InVzZSBzdHJpY3QiOw0KZnVuY3Rpb24gdGVzdChmKSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KdmFyIGIgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMSIpOw0KICAgIGNvbnNvbGUubG9nKCJmb28yIik7DQp9KS5hOw0KdmFyIGRhdGEgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMyIpOw0KICAgIGNvbnNvbGUubG9nKCJmb280Iik7DQp9KTsNCi8vIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi9pbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0EsU0FBUyxJQUFJLENBQUMsQ0FBVztJQUNyQixDQUFDLEVBQUUsQ0FBQztJQUNKLE9BQU8sRUFBRSxDQUFDLEVBQUUsTUFBTSxFQUFFLENBQUM7QUFDekIsQ0FBQztBQUVPLElBQUE7OztJQUFJLENBR1Q7QUFFSCxJQUFNLElBQUksR0FBRyxJQUFJLENBQUM7SUFDZCxPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQ3BCLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUM7QUFDeEIsQ0FBQyxDQUFDLENBQUMifQ==,DQpmdW5jdGlvbiB0ZXN0KGY6IEZ1bmN0aW9uKTogeyBhOiBzdHJpbmcgfSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KDQpjb25zdCB7IGE6IGIgfSA9IHRlc3QoKCkgPT4gew0KICAgIGNvbnNvbGUubG9nKCJmb28xIik7DQogICAgY29uc29sZS5sb2coImZvbzIiKTsNCn0pOw0KDQpjb25zdCBkYXRhID0gdGVzdCgoKSA9PiB7DQogICAgY29uc29sZS5sb2coImZvbzMiKTsNCiAgICBjb25zb2xlLmxvZygiZm9vNCIpOw0KfSk7DQo=)

**Comment by orta** [comment]
OK, confirming that this is [still legit with 3.9.0 master](https://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gdGVzdChmKSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KdmFyIGIgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMSIpOw0KICAgIGNvbnNvbGUubG9nKCJmb28yIik7DQp9KS5hOw0KdmFyIGRhdGEgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMyIpOw0KICAgIGNvbnNvbGUubG9nKCJmb280Iik7DQp9KTsNCmI7DQovLyMgc291cmNlTWFwcGluZ1VSTD1zb3VyY2VNYXBWYWxpZGF0aW9uQ29uc3RGdW5jdGlvblJlbmFtaW5nLmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic291cmNlTWFwVmFsaWRhdGlvbkNvbnN0RnVuY3Rpb25SZW5hbWluZy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInNvdXJjZU1hcFZhbGlkYXRpb25Db25zdEZ1bmN0aW9uUmVuYW1pbmcudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsU0FBUyxJQUFJLENBQUMsQ0FBVztJQUNyQixDQUFDLEVBQUUsQ0FBQztJQUNKLE9BQU8sRUFBRSxDQUFDLEVBQUUsTUFBTSxFQUFFLENBQUM7QUFDekIsQ0FBQztBQUVPLElBQUE7OztJQUFJLENBR1Q7QUFFSCxJQUFNLElBQUksR0FBRyxJQUFJLENBQUM7SUFDZCxPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQ3BCLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUM7QUFDeEIsQ0FBQyxDQUFDLENBQUM7QUFFSCxDQUFDLENBQUEifQ==,Ly8gQHNvdXJjZW1hcDogdHJ1ZQ0KLy8gQHRhcmdldDogZXM1DQpmdW5jdGlvbiB0ZXN0KGY6IEZ1bmN0aW9uKTogeyBhOiBzdHJpbmcgfSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KDQpjb25zdCB7IGE6IGIgfSA9IHRlc3QoKCkgPT4gew0KICAgIGNvbnNvbGUubG9nKCJmb28xIik7DQogICAgY29uc29sZS5sb2coImZvbzIiKTsNCn0pOw0KDQpjb25zdCBkYXRhID0gdGVzdCgoKSA9PiB7DQogICAgY29uc29sZS5sb2coImZvbzMiKTsNCiAgICBjb25zb2xlLmxvZygiZm9vNCIpOw0KfSk7DQoNCmINCg==)

**Comment by orta** [comment]
The decision not to emit source maps for this seems to be an [explicit choice](https://github.com/microsoft/TypeScript/blob/master/src/compiler/transformers/destructuring.ts/#L109-L115):

> ```ts
>
> function emitExpression(expression: Expression) {
>      // NOTE: this completely disables source maps, but aligns with the behavior of
>    //       `emitAssignment` in the old emitter.
>      setEmitFlags(expression, EmitFlags.NoNestedSourceMaps);
>      aggregateTransformFlags(expression);
>      expressions = append(expressions, expression);
> }  
> ```

**Comment by orta** [comment]
This does fix the bug though

[before](https://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gdGVzdChmKSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KdmFyIGIgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMSIpOw0KICAgIGNvbnNvbGUubG9nKCJmb28yIik7DQp9KS5hOw0KdmFyIGRhdGEgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMyIpOw0KICAgIGNvbnNvbGUubG9nKCJmb280Iik7DQp9KTsNCmI7DQovLyMgc291cmNlTWFwcGluZ1VSTD1zb3VyY2VNYXBWYWxpZGF0aW9uQ29uc3RGdW5jdGlvblJlbmFtaW5nLmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic291cmNlTWFwVmFsaWRhdGlvbkNvbnN0RnVuY3Rpb25SZW5hbWluZy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInNvdXJjZU1hcFZhbGlkYXRpb25Db25zdEZ1bmN0aW9uUmVuYW1pbmcudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsU0FBUyxJQUFJLENBQUMsQ0FBVztJQUNyQixDQUFDLEVBQUUsQ0FBQztJQUNKLE9BQU8sRUFBRSxDQUFDLEVBQUUsTUFBTSxFQUFFLENBQUM7QUFDekIsQ0FBQztBQUVPLElBQUE7OztJQUFJLENBR1Q7QUFFSCxJQUFNLElBQUksR0FBRyxJQUFJLENBQUM7SUFDZCxPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQ3BCLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUM7QUFDeEIsQ0FBQyxDQUFDLENBQUM7QUFFSCxDQUFDLENBQUEifQ==,Ly8gQHNvdXJjZW1hcDogdHJ1ZQ0KLy8gQHRhcmdldDogZXM1DQpmdW5jdGlvbiB0ZXN0KGY6IEZ1bmN0aW9uKTogeyBhOiBzdHJpbmcgfSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KDQpjb25zdCB7IGE6IGIgfSA9IHRlc3QoKCkgPT4gew0KICAgIGNvbnNvbGUubG9nKCJmb28xIik7DQogICAgY29uc29sZS5sb2coImZvbzIiKTsNCn0pOw0KDQpjb25zdCBkYXRhID0gdGVzdCgoKSA9PiB7DQogICAgY29uc29sZS5sb2coImZvbzMiKTsNCiAgICBjb25zb2xlLmxvZygiZm9vNCIpOw0KfSk7DQoNCmINCg==) - [after](https://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gdGVzdChmKSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KdmFyIGIgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMSIpOw0KICAgIGNvbnNvbGUubG9nKCJmb28yIik7DQp9KS5hOw0KdmFyIGRhdGEgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMyIpOw0KICAgIGNvbnNvbGUubG9nKCJmb280Iik7DQp9KTsNCmI7DQovLyMgc291cmNlTWFwcGluZ1VSTD1zb3VyY2VNYXBWYWxpZGF0aW9uRGVzdHJ1Y3R1cmluZ0Zvck9iamVjdEJpbmRpbmdQYXR0ZXJuSGkuanMubWFw,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic291cmNlTWFwVmFsaWRhdGlvbkRlc3RydWN0dXJpbmdGb3JPYmplY3RCaW5kaW5nUGF0dGVybkhpLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsic291cmNlTWFwVmFsaWRhdGlvbkRlc3RydWN0dXJpbmdGb3JPYmplY3RCaW5kaW5nUGF0dGVybkhpLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLFNBQVMsSUFBSSxDQUFDLENBQVc7SUFDckIsQ0FBQyxFQUFFLENBQUM7SUFDSixPQUFPLEVBQUUsQ0FBQyxFQUFFLE1BQU0sRUFBRSxDQUFDO0FBQ3pCLENBQUM7QUFFTyxJQUFHLENBQUMsR0FBSyxJQUFJLENBQUM7SUFDbEIsT0FBTyxDQUFDLEdBQUcsQ0FBQyxNQUFNLENBQUMsQ0FBQztJQUNwQixPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0FBQ3hCLENBQUMsQ0FBQyxFQUhVLENBR1Q7QUFFSCxJQUFNLElBQUksR0FBRyxJQUFJLENBQUM7SUFDZCxPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQ3BCLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUM7QUFDeEIsQ0FBQyxDQUFDLENBQUM7QUFFSCxDQUFDLENBQUEifQ==,ZnVuY3Rpb24gdGVzdChmOiBGdW5jdGlvbik6IHsgYTogc3RyaW5nIH0gewogICAgZigpOwogICAgcmV0dXJuIHsgYTogInRlc3QiIH07Cn0KCmNvbnN0IHsgYTogYiB9ID0gdGVzdCgoKSA9PiB7CiAgICBjb25zb2xlLmxvZygiZm9vMSIpOwogICAgY29uc29sZS5sb2coImZvbzIiKTsKfSk7Cgpjb25zdCBkYXRhID0gdGVzdCgoKSA9PiB7CiAgICBjb25zb2xlLmxvZygiZm9vMyIpOwogICAgY29uc29sZS5sb2coImZvbzQiKTsKfSk7CgpiCg==)
