### ISSUE TITLE
Workaround for Optional Chaining in TypeScript

### ISSUE THREAD

**Issue by nodkz** [Microsoft/TypeScript#30365]
## Autosuggestion for input 😱
<img width="788" alt="Screen Shot 2019-03-13 at 8 59 35 PM" src="https://user-images.githubusercontent.com/1946920/54289297-1688f080-45d3-11e9-85cc-c86436376826.png">
 
## Static analysis for non-existed keys 🚀

<img width="540" alt="Screen Shot 2019-03-13 at 8 59 59 PM" src="https://user-images.githubusercontent.com/1946920/54289341-2c96b100-45d3-11e9-9768-282641e7df8a.png">
 
## Pros: a quite broken result type (without null & undefined) 😭

<img width="628" alt="Screen Shot 2019-03-13 at 8 15 07 PM" src="https://user-images.githubusercontent.com/1946920/54289380-42a47180-45d3-11e9-9da4-593953d8627f.png">
 

## https://twitter.com/RIP212/status/1105841844070633474

**Comment by nodkz** [comment]
Duplicate #30167 #16

**Comment by RIP21** [comment]
What about result types for nested objects, it's possible to solve by passing generics. There are 2 parameters.
Anyway, maybe there is a way to solve it even more elegant, but it will require some CRAZY MAD typings that I can't handle myslef. So PR welcome.

**Comment by RyanCavanaugh** [comment]
This isn't a discussion forum - please keep reports specific and actionable
