### ISSUE TITLE
DT nightly: many new excessively deep instantiation errors

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#30372]
Could be the result of a react-redux change, but we should have caught it in CI then.

* fluent-react
* mirrorx
* next-redux-saga
* next-redux-wrapper
* react-intl-redux
* react-lifecycle-component

Running tsc from react-lifecycle-component, next-redug-saga or mirrorx gives:

```
../react-redux/index.d.ts:113:61 - error TS2589: Type instantiation is excessively deep and possibly infinite.

113     ) => ConnectedComponentClass<C, Omit<GetProps<C>, keyof Shared<TInjectedProps, GetProps<C>>> & TNeedsProps>;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Same for fluent-react, except the invocation is in its own code.

Unsurprisingly, doesn't repro on 3.3.3333. Edit: Haven't tried to bisect it though.

**Comment by sandersn** [comment]
@weswigham Mind taking a look while @ahejlsberg is out?

**Comment by weswigham** [comment]
Cause _looks_ to be #30334 - reverting it removes the error.

**Comment by weswigham** [comment]
TFW a seemingly innocent refactoring breaks the world. 😿

**Comment by RyanCavanaugh** [comment]
> TFW a seemingly innocent refactoring breaks the world

0 baselines changed, we have great coverage, must be good right

**Comment by ahejlsberg** [comment]
See #30334 for the real fix for this issue.

**Comment by Veetaha** [comment]
If I am not mistaken, you limit type nesting level to 50, but this is really too tight, I wish there was no limit at all, but currently this error has appeared in my library code in `3.4.0-dev.20190322`. It is so tight that when I manually expand one level of my type the error goes away.

<details>
  <summary>Demonstration</summary>

  `Foo` fails, but `Bar` doesn't, even though they are the same, except `Bar` has one level of indirection less.

  ![image](https://user-images.githubusercontent.com/36276403/54847155-509a7680-4ce6-11e9-9a3e-fa851cfcf70e.png)

</details>

 [Original code](https://github.com/Veetaha/ts-typedefs/blob/e3765021ee7dd5aa34535c9fb704fbaccd91d57a/lib/types/objects.ts#L99)
