### ISSUE TITLE
Cannot import a JSON module across a project boundary

### ISSUE THREAD

**Issue by MLoughry** [Microsoft/TypeScript#30382]
**TypeScript Version:**  3.4.0-dev.20190313, 3.3.3333

**Search Terms:**
json project reference

**Code**
Minimal repro at https://github.com/MLoughry/typescript-json-project-repro

**Expected behavior:**
Importing a json module from a project dependency should work without error, similar to referencing a typescript file from a project dependency.

**Actual behavior:**
`error TS6307: File 'd:/vso/typescript-json-project/src/strings/foo.json' is not in project file list. Projects must list all files or use an 'include' pattern.`

**Comment by ysneo** [comment]
same problem

**Comment by MLoughry** [comment]
Thanks for the quick fix!
