### ISSUE TITLE
Remove "Atomic Game Engine" from Friends of TypeScript

### ISSUE THREAD

**Issue by Cerlancism** [Microsoft/TypeScript#30391]
![Atomic Game Engine](http://www.typescriptlang.org/assets/images/friends/Atomic/logo.png "Atomic Game Engine1")[Atomic Game Engine](http://atomicgameengine.com/) from <http://www.typescriptlang.org/community/friends.html> leads to advertisement and potentially malicious websites.

Its [GitHub Repository](https://github.com/AtomicGameEngine/AtomicGameEngine) says it is no longer maintained.

**Comment by Potapy4** [comment]
cc @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up. We'll likely be removing the page entirely in the near future.
