### ISSUE TITLE
Suggestion: Improve documentation for compiler options

### ISSUE THREAD

**Issue by alexmiddeleer** [microsoft/TypeScript#30399]
Background: the point of this suggestion is to reduce the learning curve for users who are very new to typescript (e.g. me). I am learning typescript and Angular together, and it seemed like a good idea to read the default angular tsconfig file (generated by `angular new foo`) to gain a better understanding of the build process.

The documentation for compiler options may be sufficient for users that are already familiar with typescript concepts, but in my opinion assumes too much prior knowledge for beginners. For several of the options (i.e. "lib" and "typeRoots"), the explanation was confusing. 

The quick solution is to add a "prior knowledge assumed" disclaimer at the top of the [compiler options page](https://www.typescriptlang.org/docs/handbook/compiler-options.html). Additional links and brief summaries in the description column would be even better.

**Comment by RyanCavanaugh** [comment]
On second read, this wasn't very actionable, and doesn't really match other feedback we've gotten
