### ISSUE TITLE
Can't exponentiate BigInts

### ISSUE THREAD

**Issue by msafi** [microsoft/TypeScript#30398]
In normal JavaScript, this works `BigInt(2) ** BigInt(2)`

But writing the above in TypeScript, compiles to `Math.pow(BigInt(2), BigInt(2))`, which doesn't work.

According to MDN:

> [BigInt] cannot be used with methods in the built-in Math object

---

TypeScript code

```ts
BigInt(2) ** BigInt(2)
```

**Expected behavior:**
Return 4.

**Actual behavior:**

```
TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
```

**Comment by ajafff** [comment]
Why is this an issue? Environments that support BigInt also know the exponentiation operator.
Therefore you don't need to downlevel your code. The only target that makes sense for BigInt is ESnext.
IIRC there's even a compile error if you use BigInt with a different target.

**Comment by msafi** [comment]
@ajafff Oh, it didn't occur to me that I was downleveling. I just ran `tsc` without any configurations. Maybe that's why I was running into this issue. I'll test again later  today after setting the target to ESNext.

**Comment by DanielRosenwasser** [comment]
Technically I guess we could give an error when using `bigint`s in exponentiation expressions when targeting anything earlier than ES2017.

**Comment by santoshyadav198613** [comment]
Hi @DanielRosenwasser ,

can i take this up.

**Comment by DanielRosenwasser** [comment]
yup

**Comment by santoshyadav198613** [comment]
Hi @DanielRosenwasser ,

When we target es5 , we are getting "error TS2304: Cannot find name 'BigInt'.", if we change the error code to TS2737 which stands for "BigInt literals are not available when targeting lower than ESNext." it will fix the issue, let me know if we can change.

**Comment by JoshuaKGoldberg** [comment]
This looks like it was separately already solved. With this file:

```ts
3 ** 4n;
BigInt(2) ** BigInt(2);
```

Targeting `es5`, you get these errors:

```
index.ts:1:1 - error TS2365: Operator '**' cannot be applied to types '3' and '4n'.

1 3 ** 4n;
  ~~~~~~~

index.ts:1:6 - error TS2737: BigInt literals are not available when targeting lower than ESNext.

1 3 ** 4n;
       ~~

index.ts:2:1 - error TS2304: Cannot find name 'BigInt'.

2 BigInt(2) ** BigInt(2);
  ~~~~~~

index.ts:2:14 - error TS2304: Cannot find name 'BigInt'.

2 BigInt(2) ** BigInt(2);
               ~~~~~~
```
