### ISSUE TITLE
Add HTMLMediaElement.fastSeek to dom.d.ts

### ISSUE THREAD

**Issue by MekliCZ** [Microsoft/TypeScript#30392]
## Search Terms

fastseek

## Suggestion

HTMLMediaElement.fastSeek() should be added dom.d.ts as it's already LS (https://html.spec.whatwg.org/multipage/media.html#dom-media-fastseek)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We don't add experimental DOM APIs to the built-in lib. It's for widely-available features only. Please open a new issue later when the API is stabilized. Thanks!
