### ISSUE TITLE
MouseEvent defines no constructor arguments, takes two

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#3040]
According to MDN, `MouseEvent` takes two arguments, type and an initializer object.

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent

`lib.d.ts` only defines a zero-argument ctor.

**Comment by mhegazy** [comment]
This is fixed in release 1.5-beta as well as master: https://github.com/Microsoft/TypeScript/blob/release-1.5/bin/lib.d.ts#L11308
