### ISSUE TITLE
TS fails to understand guard for Array.prototype.pop()

### ISSUE THREAD

**Issue by jaredh159** [microsoft/TypeScript#30406]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
* array.pop
* Object is possibly 'undefined'

**Code**

```ts
const arr: string[] = [];

if (Math.random() > 0.5) { // <-- simulate runtime unknown array length
    arr.push('hi');
}

if (arr.length > 0) {
    arr.pop().toLowerCase(); // <-- error `Object is possibly 'undefined'`
}
```

**Expected behavior:**
No error, because we tested that the array's length was greater than zero.

**Actual behavior:**
Error: `Object is possibly 'undefined'`

**Playground Link:**
_Note: turn on all strict checks in "options" (the link doesn't preserve these settings)_
http://www.typescriptlang.org/play/index.html#src=const%20arr%3A%20string%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0Aif%20(Math.random()%20%3E%200.5)%20%7B%0D%0A%20%20%20%20arr.push('hi')%3B%0D%0A%7D%0D%0A%0D%0Aif%20(arr.length%20%3E%200)%20%7B%0D%0A%20%20%20%20%2F%2F%20NOTE%3A%20turn%20on%20all%20strict%20checks!%0D%0A%20%20%20%20arr.pop().toLowerCase()%3B%0D%0A%7D%0D%0A

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/29642 -- maybe? 🤔

**Comment by jack-williams** [comment]
I think is essentially the same thing as #9619.

**Comment by RyanCavanaugh** [comment]
This isn't something we're capable of tracking

**Comment by tadhgmister** [comment]
you just need an interface that represents a non-empty array and a type guard function:

```
const arr: string[] = [];
interface NonEmptyArray<T> extends Array<T> {
    // would need to implement all relevant functions.
    pop: () => T;
}

function isNonEmpty<T>(arr: Array<T>): arr is NonEmptyArray<T> {
    return arr.length > 0;
}
if (isNonEmpty(arr)) {
    // here we are sure arr.pop() will return a value!
    arr.pop().toLowerCase();
}
```

**Comment by MartinJohns** [comment]
@tadhgmister This would require something like #29346, #27568, #25679, #8655, #10421. A way to indicate that a function will mutate and change the type of an argument.

**Comment by basvanmeurs** [comment]
A simple way to let Typescript know that it can assume 'not undefined':
`if (arr.length > 0) {
    (arr.pop() as string).toLowerCase(); // <-- error `Object is possibly 'undefined'`
}
`

**Comment by dragomirtitian** [comment]
@basvanmeurs A not null assertion:

```ts
if (arr.length > 0) {
    arr.pop()!.toLowerCase();
}
```

**Comment by roeniss** [comment]
Is this relevant?

```ts
class Stack<T> {
  private data: T[] = [];
  constructor() {}
  push(item: T): void {
    this.data.push(item);
  }
  pop(): T | 0 {
    if (this.data.length > 0) return this.data.pop(); // Error : Type 'undefined' is not assignable to type '0 | T'.
    else return 0;
  }
}
```

**Comment by wbt** [comment]
TypeScript already [recognizes an index signature property type](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) which must be either ‘string’ or ‘number’. In addition to that, TypeScript could keep track of `minLength` and `maxLength` as part of an Array-like's type definition, which changes dynamically through operations like push/pop/shift/unshift/splice etc.  Unless otherwise specified or guarded, the default is minLength 0 and maxLength of the largest UINT32. Then you could do things like this:
```ts
if (arr.length > 0) { //guard: arr.minLength is now 1
    arr.pop().toLowerCase(); //this would be fine; arr.minLength drops by 1 to 0
    arr.pop().toLowerCase(); //this second call would have a type error, fixed by setting 0 to 1 in check.
}
```
Though it is not a trivial implementation, I think Typescript would be much more useful with that enhancement.

**Comment by Rudxain** [comment]
Related: #31376
