### ISSUE TITLE
Compile errors for VS Code codebase with TS 3.4

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#30419]
**TypeScript Version:**  3.4.0-dev.20190311

**Issue**
After updating to build VS Code with TS 3.4, I ran into a handful of problems that had to be worked around. [Here's the change](https://github.com/Microsoft/vscode/commit/50ee8c5fa50f5ba85a130975e41a43dc06f554a0) that added the workarounds.

To repo original issues:

1. In VS Code project
1. `git checkout 50ee8c5fa50f5ba85a130975e41a43dc06f554a0~1`
1. Build VS Code using 3.4.0-dev.20190311: `tsc -p src/tsconfig.json --watch`

I have not been able to create more minimal repos yet

**Comment by RyanCavanaugh** [comment]
I've tracked these all down to root causes
