### ISSUE TITLE
Node.js process.on does not recognize string as Signal if taken from array

### ISSUE THREAD

**Issue by nudabagana** [Microsoft/TypeScript#30426]
**TypeScript Version:**  3.3.3333

**Search Terms:** process.on Signals

**Code**

```ts
// define Signal strings
const sign1 = 'SIGTERM';
const sign2 = 'SIGINT';
// make array
const signArray = [sign1, sign2];

// on signal, do something (works as expected)
process.on(sign1, () => console.log("do function..."));

//on signal, do something (doesn't work)
// gives Error: [ts] Argument of type 'string' is not assignable to parameter of type 'Signals'. [2345]
process.on(closeOnSignal[0], () => console.log("do function..."));
```

**Expected behavior: to be able to pass Signals from array to node's process.on function.

**Actual behavior: Typescript does not recognize string (does not convert to signal), when it is in array.

**Playground Link:** 

**Related Issues:**

**Comment by AlCalzone** [comment]
`signArray` is widened to `string[]`, whereas the other constants have a literal type. In the coming version 3.4 you will be able to write
```ts
const signArray = [sign1, sign2] as const;
```
and get the expected/desired behavior.

**Comment by zalouma1** [comment]
Insted of `as const` try type `NodeJS.Signals`.

Example: `const termSignals: NodeJS.Signals[] = ['SIGTERM', 'SIGINT'];`

**Comment by zalouma1** [comment]
Insted of as const try type NodeJS.Signals.

Example: const termSignals: NodeJS.Signals[] = ['SIGTERM', 'SIGINT'];
