### ISSUE TITLE
Feature Request  --noAnyProperties 

### ISSUE THREAD

**Issue by Jojoshua** [Microsoft/TypeScript#30420]
What I would like is a compiler option that throws an error if an object (even if typed as any) tries to access a property. This would allow overriding 3rd party declarations that use the any type to force a more specific type.

$.ajax({
    type: "POST",    
    success: function(response:any) {     
        let columns: response.columns    <==compiler error
    },  
  });

**Comment by kitsonk** [comment]
This is already well covered by linting rules in both eslint and tslint:

- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md
- https://palantir.github.io/tslint/rules/no-any/

**Comment by Jojoshua** [comment]
I want the any type to be possible but I don't want to allow accessing properties from an "any" type. I believe those lint rules deny the any type all together.

**Comment by kitsonk** [comment]
Then what you are looking for is the `unknown` type.  `any` means `any`, which allows intentional unfettered access to the variable, breaking that would be a horrible idea.

**Comment by Jojoshua** [comment]
Thanks @kitsonk , that is what I need.
