### ISSUE TITLE
JSDoc preview not showing object keys description

### ISSUE THREAD

**Issue by negebauer** [Microsoft/TypeScript#30432]
- VSCode Version: 1.32.3
- OS Version: macOS Mojave 10.14.2

Intellisense doesn't show an object's keys description when the object description is present.

![demo bug](https://user-images.githubusercontent.com/11860880/54447061-2e718900-4727-11e9-87f4-78cfce8731a1.gif)

Steps to Reproduce:

1. Create a file `test.js`
2. Paste this code
```js
/**
 * @param {Object} options options for foo
 * @param {String} options.o1 an option for foo
 * @param {String} options.o2 another option for foo
 */
function foo(options) {

}
```
3. Hover over `foo`, you will see only the description for `options`
4. Remove the line ` * @param {Object} options options for foo`
5. Hover over `foo`, you will see the description of each key

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
As part of the `quickinfo` response, we could consider including all parameters in the `tags` field (including those for objects). This may add a lot of noise though for larger objects

**Comment by RyanCavanaugh** [comment]
We'd have to interleave JS Doc with the type display for the parameters object, then have VS Code format it with some kind of table formatting -- really not something worth the amount of effort required here.

**Comment by rb-ntnx** [comment]
I didn't see much activity on this. I still see this as an issue in 2023.

Can we assume that following is expected behaviour :

> @negebauer :  Intellisense doesn't show an object's keys description when the object description is present. 

@mjbvz @RyanCavanaugh  ?

**Comment by cvharris** [comment]
@rb-ntnx this was exactly the issue here, I simply removed the `@param {Object} options` line and the other `@param` descriptions appeared
