### ISSUE TITLE
Add support for "exclude" in tsconfig.json

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3043]
tsconfig.json picks all files in the containing folder by default, this is problematic with "node_modules" that contain .ts/.d.ts that are not relevant to the project. "files" is not useful here because of the lack of support for globs (see #1927).

Proposal:
* support a new property "exclude" that specifies a list of directories/files to exclude.
* "exclude" is ignored if "files" is present.

```JSON
{
    "compilerOptions": {
        "out": "../../built/local/tsc.js",
        "sourceMap": true
    },
    "exclude": [
        "script/helper.ts",
        "node_modules"
    ]
}
```

Note: This is needed if we want any of gulp/grunt/task runner/ProjectK support in VS .

**Comment by briandipalma** [comment]
Would glob support be enough not to require this feature? I've also had this issue where `node_modules` was being built but with glob support I'd be fine.
