### ISSUE TITLE
Confused function signature in 3.3.3333. ...args: string[]

### ISSUE THREAD

**Issue by dekz** [microsoft/TypeScript#30435]
**TypeScript Version:**  3.3.3333
**TypeScript Version:**  3.4.xx

**Search Terms:**
`...args: (string | number | Partial<any> | undefined)[]`
`...args: string[]`
`TS2684`

**Code**
Full gist is [here](https://gist.github.com/dekz/ab230c897a1005315d85a9a3df42d155).

```ts
export class TestContract {
    public safeTransferFrom = {
        async sendTransactionAsync(
            from: string,
            to: string,
            id: number,
            value: number,
            data: string,
            txData: Partial<any> = {},
        ): Promise<string> {
            const self = this as any as TestContract;
            self.safeTransferFrom.estimateGasAsync.bind(self, from, to, id, value, data);
            return '';
        },
        async estimateGasAsync(
            from: string,
            to: string,
            id: number,
            value: number,
            data: string,
            txData: Partial<any> = {},
        ): Promise<number> {
            return 1;
        },
    };
}
```

**Expected behavior:**
Code compiles

**Actual behavior:**
Compiler fails to compile:

```
test_args.ts:12:13 - error TS2684: The 'this' context of type '(from: string, to: string, id: number, value: number, data: string, txData?: Partial<any>) => Promise<number>' is not assignable to method's 'this' of type '(this: TestContract, ...args: string[]) => Promise<number>'.
  Types of parameters 'id' and 'args' are incompatible.
    Type 'string' is not assignable to type 'number'.
12             self.safeTransferFrom.estimateGasAsync.bind(self, from, to, id, value, data);
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```

**Playground Link:** [Playground link](https://www.typescriptlang.org/play/#src=export%20class%20TestContract%20%7B%0D%0A%20%20%20%20public%20safeTransferFrom%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20async%20sendTransactionAsync(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20from%3A%20string%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20to%3A%20string%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20number%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20number%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20data%3A%20string%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20txData%3A%20Partial%3Cany%3E%20%3D%20%7B%7D%2C%0D%0A%20%20%20%20%20%20%20%20)%3A%20Promise%3Cstring%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20self%20%3D%20this%20as%20any%20as%20TestContract%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20self.safeTransferFrom.estimateGasAsync.bind(self%2C%20from%2C%20to%2C%20id%2C%20value%2C%20data)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20''%3B%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20async%20estimateGasAsync(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20from%3A%20string%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20to%3A%20string%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20number%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20number%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20data%3A%20string%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20txData%3A%20Partial%3Cany%3E%20%3D%20%7B%7D%2C%0D%0A%20%20%20%20%20%20%20%20)%3A%20Promise%3Cnumber%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%7D%3B%0D%0A%7D). Doesn't seem to reproduce in here.

**Related Issues:**

**Comment by j-oliveras** [comment]
Using this `tsconfig.json`:
```json
{
  "compilerOptions": {
      "module": "commonjs",
      "target": "es2017",
      "allowSyntheticDefaultImports": true,
      "strict": false
  },
  "include": [
      "./*.ts"
  ]
}
```
Generates the same code without types (typescript 3.3.3333):
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class TestContract {
    constructor() {
        this.safeTransferFrom = {
            async sendTransactionAsync(from, to, id, value, data, txData = {}) {
                const self = this;
                self.safeTransferFrom.estimateGasAsync.bind(self, from, to, id, value, data);
                return '';
            },
            async estimateGasAsync(from, to, id, value, data, txData = {}) {
                return 1;
            },
        };
    }
}
exports.TestContract = TestContract;
```
But this fails on runtime (using node 8.11.1):
```js
var t = require(".") // or the path needed to import the compiled file
var c = new t.TestContract()
c.safeTransferFrom.sendTransactionAsync("f", "t", 1, 2, 3, {})
```
Outputs an error:
```
Promise {
  <rejected> TypeError: Cannot read property 'estimateGasAsync' of undefined
    at Object.sendTransactionAsync (C:\code\test\index.js:8:39)
    at repl:1:20
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10),
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
```

In conclusion, typescript warns you correctly about suspicious code.
Set `strict` to `true` to show the error compiling it.
