### ISSUE TITLE
Quick fix produces incorrect file casing on windows

### ISSUE THREAD

**Issue by eJuke** [Microsoft/TypeScript#30434]
Issue Type: <b>Bug</b>

Example code to reproduce issue: [example.zip](https://github.com/Microsoft/vscode/files/2822385/example.zip)

Steps to reproduce:
- Extract attached archive and open directory in editor
- Open Flow.ts file
- Point yout cursor to 'SharedModule' word
- Call Quick fix (Ctrl+.) 
- Click Import 'Shared Module' from ..

<b>Expected behavior:</b>
Import row is added to the top of the Flow.ts file

<b>Actual behavior:</b>
New flow.ts (pay attention to the F char case) tab is opened. This tab contains initial file content with expected import row. 
TypeScript features becomes unresponsive in initial Flow.ts tab (until tab is reopened)

![vscode-bug](https://user-images.githubusercontent.com/7329397/52135420-d25f1380-2656-11e9-98dd-031317742e04.gif)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Tested with typescript@3.4.0-dev.201903111

The TS server seems to be the one that converts `Flow.ts` to `flow.ts` (). Here are the logs:
[tsserver.txt](https://github.com/Microsoft/TypeScript/files/2972361/tsserver.txt)

VS Code initially keeps wokring with uppercase `Flow.ts`, and it's only the `getCodeFixes` response that first introduces the lowercase `flow.ts`

**Comment by sheetalkamat** [comment]
It isn't anything about code fix. If you run `tsc -p . --listFiles ` you will see that `flow.ts` is listed as file of the program. That's because `Dependencies.ts` has module reference to 'flow.js' which resolves to "flow.ts" file and since that's same as `Flow.ts` on case insensitive os, you will see that program prefers flow.ts over "Flow.ts"

**Comment by mjbvz** [comment]
How do you propose that we handle this? VS Code normalizes file names before sending them to TS, but we trust the responses we get back from TS.

**Comment by sheetalkamat** [comment]
I think you need to check if these two are same files. Also from user side to avoid such mistakes one can add `--forceConsistentCasingInFileNames` to get these as errors instead of surprise.

**Comment by eJuke** [comment]
@sheetalkamat 
Flow.ts and flow.js files are different. We rewrite our app using ts and convert old camel-cased file names into Pascal. 
Is it possible to pass this flag into ts server from my editor?

**Comment by sheetalkamat** [comment]
@eJuke you can add it to you tsconfig file.
