### ISSUE TITLE
Transpile TypeScript-based type/value guards of declared variables to guaranteed-safe checks where possible

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/TypeScript#30448]
*I apologize in advance if this has already been discussed. It was very hard to winnow down the results of the applicable search terms.*

## Search Terms

typeof, variable is declared, undefined, javascript type system, runtime types

## Suggestion

JavaScript "out of the box" has virtually no type support, which is why TypeScript exists. Currently, TypeScript's type support is 100% virtualized and independent of the resulting compiled JavaScript, all type info is stripped at runtime. **I am not proposing any changes in this regard**; compiling TypeScript in strict mode takes care of almost all runtime issues concerning type safety. However, there is still one corner case that is not addressed (so far as I can tell) by TypeScript's type safety features, and remains extremely unergonomic to use, which necessitates falling back to JavaScript's primitive type system in addition to whatever TypeScript-based safety measures are in place.

In particular, when dealing with variables both defined and referenced within TypeScript, it is sufficient to use `foo !== undefined` to check that a value has been assigned (putting aside `null` for a minute). 

However, that same code is **unsafe** when referencing a variable that has been declared with a type-definition-only `declare let/const/var/function/class ....`, because while TypeScript has been primed to believe the variable exists, it cannot prove its existence and that assumption may be invalidated at runtime.

This is a proposal to make "type safety" checks along the lines of `foo !== undefined`, `foo instanceof ...`, etc. expand to a runtime-safe equivalent regardless of whether or not the variable is defined (e.g. `typeof(foo) !== "undefined" && <previous expression>`) in cases where TypeScript cannot provably assert that the variable declaration exists. 

More specifically, many cases of type-only declarations are for global variables, where a runtime-unsafe `foo !== undefined` becomes safe if converted to `globalThis.foo !== undefined` (or `window.foo !== undefined` for in-browser uses). This is basically a **free** safety upgrade in such cases, as the global this (or `window`) is guaranteed to exist and checking for the existence of a potentially undeclared property on an existing object is safe via `object.foo !== undefined`.

Existing safety checks along the lines of `foo !== undefined` can also be much more safely transpiled to `typeof(foo) !== "undefined"` since `typeof(foo) === "undefined"` can only hold if `foo === undefined` (and vice-versa), regardless of the scope of `foo`.

Additionally, runtime `typeof` checks are discouraged since they are not capable of distinguishing anything beyond JS primitive types, but at the same time, they are absolutely required since TypeScript does not provide a safe way of detecting whether or not an external variable actually exists before accessing it, except by shelling out to JS' crippled `typeof` operator.

## Use Cases

* Anywhere typeguards are used with variables that are assumed to exist but not provably so
* Checking for the existence of global variables imported into the global `this` via external scripts
* Interop with JS-imported variables and declarations

## Examples

I've found a common pitfall for "type-safe" developers is in believing this code is safe:

```typescript
declare var foo; // this is defined globally by a <script></script> tag

...

// Make sure the script loaded OK and init'd the object in question
if (foo !== undefined) {
    foo.doSomething();
}
```

but it's not safe at all (even in strict mode) since even comparing an undeclared variable with `undefined` is not a safe operation. The correct syntax is *extremely* verbose, repetitive, and unergonomic: 

```typescript
if (typeof(foo) !== "undefined") {
   // ...
}
```

This is an example of why this *needs* to be implemented via TypeScript:

After tiring of writing out the above, it is natural to want to abstract that ugliness away. Well, TypeScript has typeguards, so why not use those?

```typescript
declare var foo;
function isDefined(o: any): pet is Exclude<any, undefined|null> {
    return typeof(o) !== "undefined" && o !== undefined && o !== null;
}

if (isDefined(foo)) {
    foo.doSomething();
}
```

The code fragment above is of course 100% wrong, since the initial reference to `foo` in the call to `isDefined(foo)` will trigger the error, before `isDefined` itself even gets a chance to execute. TypeScript's lack of macros means that this needs to be implemented as a function, JavaScript's eager expansion/evaluation of function parameters means there's no safe way to do that.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code as errored code would never have reached the next statement
* [X] This wouldn't change the runtime behavior of existing JavaScript code, rather it would provide a bridge between the two type systems
* [?] This could be implemented without emitting different JS based on the types of the expressions. I'm not sure what this means.
* [-] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.). It does expand to runtime code, but that code would be inline with the compilation typescript does in this case anyhow, only safer.
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). I believe it does as it enforces type safety and does not require the existence of a runtime type system *beyond that which JS already primitively provides*.

**Comment by DanielRosenwasser** [comment]
I think there are two possibilities here:

# Always emit `typeof foo === "undefined` wherever `foo === undefined` is used.

This is meaningfully different and I don't think one of our goals is to preserve what the user wrote. Specifically, it doesn't meet this item in the checklist.

> This wouldn't change the runtime behavior of existing JavaScript code

and doesn't meet the following goals:

> * Use a consistent, fully erasable, structural type system.
> * Preserve runtime behavior of all JavaScript code.

and falls into one of our non-goals

> * Introduce behaviour that is likely to surprise users. Instead have due consideration for patterns adopted by other commonly-used languages.

While current code might error, this does have different behavior, and having different "better" behavior could make it harder for users to move back to JavaScript if that's their choice.

# Emit `typeof foo === "undefined"` when `foo === undefined` is used if `foo` is an ambient declaration

Apart from the problems mentioned above, this specifically depends on information fed to the type system and violates the following non-goals:

> * Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

**Comment by mqudsi** [comment]
If I may, I think a case may be argued. 

I wasn't able to find it in the EMCAScript specification, but I am wondering if the specified behavior when a variable that was never and does not exist is accessed leaves room for either implementation-defined or undefined behavior. You would know better than I in this regard.

However, with regards to the run-time type system, I respectfully disagree. I do not think this falls under that clause; as I attempted to distinguish in my original post, there are two type systems at play here, TypeScript's and JavaScript's own. Most feature requests that I've seen declined here have been attempts to extend the lifetime or concept of a TypeScript type into the transpiled code or runtime execution. This definitely does not fall under that umbrella. I would respectfully argue that the quote you supplied "Instead, encourage programming patterns that do not require run-time metadata" further backs this, since this particular usecase can *only* be handled safely by falling back on JavaScript's runtime type system.

I also don't believe the contract to "Use a consistent, fully erasable, structural type system" is broken with this proposal. No TypeScript-defined type persists in the transpiled/runtime code, nor are any references to TypeScript types involved in the transpilation I'm proposing.

Moreover, I would argue that there is leeway here since this specifically falls into the boundary of JS interop, and I believe is an attempt at addressing a fundamental issue with deploying TypeScript in mixed TS/JS environments.

I'm truly not trying to be stubborn or a hard-head here and I would sincerely appreciate if we could work together to identify a way that the actual, underlying issue could be tackled, as I believe it's an extremely prevalent and under-addressed issue deserving of a TypeScript solution.

For example, presuming the answer to all the above is still "nope," would you be open to having this feature behind a configuration option that defaults to disabled (e.g. `runtimeUndefinedChecks` in `tsconfig.json`)? Or would you be open to at least extending `strictNullChecks` (or adding a new check) that didn't transpile anything but *did* generate an error or a warning when `tsc` encounters `foo === undefined` or `foo !== undefined` and `foo` cannot be provably assumed to exist at runtime?

**Comment by rjamesnw** [comment]
I understand the reasoning, but I can't help think it is a bit flawed.   The nature of JS is very dynamic, and one cannot presume what `declare var foo;` means.  Who's to say that it is defined by a script tag?  It could very well be lazy loaded at a later time, then this logic will cause problems.

**Comment by mqudsi** [comment]
@rjamesnw I'm not sure if that was aimed at myself or not, but that was my point. JS is dynamic so it's hard to guarantee what will be ready/loaded when. My "loaded by a script tag" was merely an example; the goal is to have some way of checking whether or not a variable exists *at all* before accessing it (not whether or not it has a value), which necessitates the usage of `typeof(xxx) !=== "undefined"` leading me to seek a more ergonomic alternative.

**Comment by rjamesnw** [comment]
There is a simple solution.  Don't use `declare var foo;`.  There is no reason not to simply use `var foo;`. It won't erase anything set prior, and won't cause the errors you mentioned.

**Comment by mqudsi** [comment]
That's a good idea. The problem is some of these are defined in type-only libraries pulled in as dependencies, but I suppose additional declarations can be made.
