### ISSUE TITLE
Unary Function Type Inference Support

### ISSUE THREAD

**Issue by mytee306** [Microsoft/TypeScript#30444]
**TypeScript Version:**  2.6.2 ( based on [stackblitz](https://github.com/stackblitz/core/issues/483) ) and 3.4.0-rc

**Search Terms:** unary,function

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

```ts
const a = 1

const f = (a: number) => a + 1
const g = (a: number) => a * 2

type Compose = <A, B, C>(f: (a: A) => B, g: (a: B) => C) => (a: A) => C
const compose: Compose = (f, g) => a => g(f(a))

const fg = compose(
  f,
  g,
)

const r = fg(a) // type "number"

type ComposeU = <A, B, C>(f: (a: A) => B) => (g: (a: B) => C) => (a: A) => C
const composeU: ComposeU = f => g => a => g(f(a))

const fgU = composeU(f)(g)

const rU = fgU(a) // type "{}"

```

**Expected behavior:**

The type of the result is inferred correctly ( expected to be "number" in the example )  

**Actual behavior:**

Type is inferred as "{}"

**Playground Link:** 

[stackblitz](https://stackblitz.com/edit/typescript-unary-function-support?file=index.ts)

[repo](https://github.com/mytee306/typescript-unary-function-support)

**Related Issues:**

**Comment by tadhgmister** [comment]
types are inferred from parameters, `composeU` can only infer A and B from the initial arguments so it leaves C as `{}`, instead you would only infer A and B from arguments then return a function that infers C:

`type ComposeU = <A, B>(f: (a: A) => B) => <C>(g: (a: B) => C) => (a: A) => C;`

**Comment by tadhgmister** [comment]
also would be cleaner to just write as a function with more verbose names, current version is really hard to read:

```
function composeU<A,B>(callback1: (arg: A) => B) {
    return function secondLayer<C>(callback2: (arg: B) => C){
        return (arg: A) => callback2(callback1(arg));
    };
}
```
