### ISSUE TITLE
Type parameter inference regression in 3.4

### ISSUE THREAD

**Issue by ark120202** [Microsoft/TypeScript#30442]
**TypeScript Version:**  3.4.0-rc

**Search Terms:** Type parameters, generics, inference, regression

**Code**

```ts
const foo = <T>() => {};
const assign = <T, U>(a: T, b: U) => Object.assign(a, b);
const result: (() => void) & { foo: any } = assign(() => {}, { foo });
```

**Expected behavior:**

No error

**Actual behavior:**

```
Argument of type '{ foo: <T>() => void; }' is not assignable to parameter of type '(() => void) & { foo: any; }'.
  Type '{ foo: <T>() => void; }' is not assignable to type '() => void'.
    Type '{ foo: <T>() => void; }' provides no match for the signature '(): void'.
```

**Playground Link:**
https://www.typescriptlang.org/play/#src=const%20foo%20%3D%20%3CT%3E()%20%3D%3E%20%7B%7D%3B%0D%0Aconst%20assign%20%3D%20%3CT%2C%20U%3E(a%3A%20T%2C%20b%3A%20U)%20%3D%3E%20Object.assign(a%2C%20b)%3B%0D%0Aconst%20result%3A%20(()%20%3D%3E%20void)%20%26%20%7B%20foo%3A%20any%20%7D%20%3D%20assign(()%20%3D%3E%20%7B%7D%2C%20%7B%20foo%20%7D)%3B

**Related Issues:** 

---

Removing `<T>` from `foo` makes this code valid.

**Comment by ark120202** [comment]
Reproducible in 3.4.1

**Comment by RyanCavanaugh** [comment]
@ahejlsberg contextual typing strikes again? Moving the initializer to its own expression resolves its problem

```ts
const foo = <T,>() => {};
const assign = <T, U>(a: T, b: U) => Object.assign(a, b);
// No error
const res = assign(() => {}, { foo });
const result: (() => void) & { foo: any } = res;
```

**Comment by ahejlsberg** [comment]
This is an effect of #29847. Previously we'd only make inferences to single naked type parameters in unions and intersections. We now infer to each naked type parameter. That works well for union types, but not for intersection types as this example illustrates. I think we should revert to the previous behavior for intersection types and only infer to multiple naked type parameters in union types.
