### ISSUE TITLE
Language Service(?) is abbreviating types too aggressively

### ISSUE THREAD

**Issue by JasonKleban** [microsoft/TypeScript#30450]
I have a project with some pretty complicated types - generics with function signatures as type parameters, themselves returning generic types of all sorts.  I've noticed in using 3.3.3333 with vscode 1.32.3 that my tooltips types are abbreviated in a new way with ellipses throughout.  I understand the intent but these abbreviations are too aggressive.  I'm trying to debug my types and I can't tell whether/where some of the nested type inferences are getting dropped (to `{}` or `any`, for example).

I don't know how to repro this issue because it is specifically related to the size and complexity of the types involved.  Maybe others can contribute anecdotes of this happening with popular libraries?  Or maybe someone with knowledge of the code can call out the culprit more actionably.

I guess that there's some algorithm that assigns weights to the various parts of the type tree and adds ellipses to keep the rendered length under some limit.  Is there a way to tinker with this limit as a user to allow me to see longer or even complete signatures, even if they're a mile long?  Or maybe there's a usability nuance that the weightings aren't accounting for.  All I know is that I'm unable to see the inferred types that I need to see to debug my types.

**Comment by ajafff** [comment]
You can try the `noErrorTruncation` compiler option. Despite the name it seems to also work for quickinfo.

There's a proposal (here or in the VSCode repo) to make quickinfo tooltips interactive, so you can click on the ellipsis to expand it. Unfortunately I cannot find it right now.

**Comment by AnyhowStep** [comment]
`noErrorTruncation` doesn't help. It'll still show the ellipsis.

**Comment by weswigham** [comment]
The `...` is also used for reverse mapped types where we used to incorrectly print `any` (we actually still have strong types for the thing all the way down, the structure just expands potentially forever).
