### ISSUE TITLE
Compile on save don't work when tsconfig.json specifies 'out' relative path 

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#3045]
Open 'emitter.ts' in compiler code and try to save it. 

**Expected**: single output file is written
**Actual**: nothing happens. 

Result of 'get emit output' request that is returned from the script side has a relative path so when VS tries to save it it gets `UnauthorizedAccessException` because presumably it attempted to save this file somewhere at the root of 'C:' drive. Exception is later swallowed and user observes nothing - there are no errors but file is not saved.

**Comment by mhegazy** [comment]
@paulvanbrenk?

**Comment by paulvanbrenk** [comment]
This is similar to what happens in msbuild projects

**Comment by paulvanbrenk** [comment]
Checked into Visual Studio
