### ISSUE TITLE
Return something as Exclude<T, false>[] resolved `true[]`

### ISSUE THREAD

**Issue by rockmandash** [Microsoft/TypeScript#30458]
I found out some strange bugs, if some function return `something as Exclude<T, false>[]`, it resolved `true[]`

```typescript
function compact<T>(arr: T[]) {
  return arr.filter(Boolean) as Exclude<T, false>[];
}

const result = compact([false])
// => const result: true[]
```

![image](https://user-images.githubusercontent.com/7580792/54518531-77337700-499f-11e9-81a7-31920f3a0ad6.png)

**Comment by dragomirtitian** [comment]
It may be surprising but it is not a bug, it's just an unfortunate intersection of several other behaviors:
1. Typescript will not infer literal types preserve literal types unless is has to, so the array literal `[false]` will not be typed as `false[]` (or `[false]`  depending if you were expecting tuples or arrays). It will be typed as `boolean[]`
2.  `boolean` is seen by the compiler as the union `true | false` so when you use `Exclude<T, false>` you will be removing from `T` , the literal type `false`, that woks out as follows: `Exclude<boolean, false> => Exclude<true | false , false> => true

If you use `as const` in 3.4 or if you constrain `T` to extend `boolean` you will get `never[]` which is probably what you were expecting. 

```ts
function compact<T extends boolean>(arr: T[]) {
  return arr.filter(Boolean) as Exclude<T, false>[];
}

const result = compact([false])
```
[Playground](https://typescript-play.js.org/#code/GYVwdgxgLglg9mABBOBbADgQ2gHgCqICmAHlIWACYDOiARnHADaGZgB8AFJgE7cBciPAG0AugEpEAbwBQiRN0JQQ3JD24A6YDEZluHAEINmrCZhoBRYhEYgKhfABpEwTIyqE2ogNzSAvtOkUMCooeUIqEB1EAF5kNCxoDiEXN0JxaQB6DJi2OODQhQidAShuEEJRIA)

**Comment by rockmandash** [comment]
Your explanation is so clear and well.
Thank you!!
