### ISSUE TITLE
Possibly bug, TS cannot infer narrow type properly 

### ISSUE THREAD

**Issue by alexeypetrushin** [Microsoft/TypeScript#30454]
**TypeScript Version:**  3.3

**Code**

```ts
function size<T>(list: T[]): number
function size<T>(map: { [key: string]: T }): number
function size<T>(o: any): number { return 0 }

function isEmpty<T>(list: T[]): boolean
function isEmpty<T>(map: { [key: string]: T }): boolean
function isEmpty<T>(o: T[] | { [key: string]: T }) {

  const s = size(o) // ERROR

  // Works, although it's exactly the same
  const s2 = o instanceof Array ? size(o) : size(o)

  return s
}
```

**Expected behavior:**

Should compile

**Actual behavior:**

TS cannot figure out that the code is correct.

**Playground Link:** [code](https://www.typescriptlang.org/play/#src=function%20size%3CT%3E(list%3A%20T%5B%5D)%3A%20number%0Afunction%20size%3CT%3E(map%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20T%20%7D)%3A%20number%0Afunction%20size%3CT%3E(o%3A%20any)%3A%20number%20%7B%20return%200%20%7D%0A%0Afunction%20isEmpty%3CT%3E(list%3A%20T%5B%5D)%3A%20boolean%0Afunction%20isEmpty%3CT%3E(map%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20T%20%7D)%3A%20boolean%0Afunction%20isEmpty%3CT%3E(o%3A%20T%5B%5D%20%7C%20%7B%20%5Bkey%3A%20string%5D%3A%20T%20%7D)%20%7B%0A%0A%20%20const%20s%20%3D%20size(o)%20%2F%2F%20ERROR%0A%0A%20%20%2F%2F%20Works%2C%20although%20it's%20exactly%20the%20same%0A%20%20const%20s2%20%3D%20o%20instanceof%20Array%20%3F%20size(o)%20%3A%20size(o)%0A%0A%20%20return%20s%0A%7D)

**Comment by kitsonk** [comment]
Why did you not fill out the template properly before opening the issue.  In particular, you did not provide search terms you used.

This is a duplicate of #1805 and many many other issues (which are linked in that issue).

**Comment by kitsonk** [comment]
This is also covered in the Do's and Don'ts of TypeScript [Union Types](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-union-types).

**Comment by alexeypetrushin** [comment]
Thanks for info. Sorry for being lazy, I googled it quickly but didn't found anything similar. 

> This is a duplicate of #1805 and many many other issues

`many many other issues` seems like many people having that problem...

> This is also covered in the Do's and Don'ts of TypeScript

No, it won't work with literal types as proposed in `Do's and Don'ts of TypeScript`. I posted simplified example here, just to highlight the problem. The actual code use different return types (like snippet below), that would be impossible to achieve with literal types.

```
function f<T>(list: T[]): A
function f<T>(map: { [key: string]: T }): B
function f<T>(o: any): any { return 0 }
```

**Comment by AlCalzone** [comment]
> After reading another issue it seems like that feature is not easy to implement

You are looking for conditional types:
```ts
type A = "A";
type B = "B";

function size<T>(o: T):
  T extends any[] ? A :
  T extends Record<string, any> ? B :
  never {
  return null as any
}

function isEmpty<T>(o: T):
  T extends any[] ? A :
  T extends Record<string, any> ? B :
  never {

  // works
  const s = size(o);
  return s
}

isEmpty([]); // has type A
isEmpty({}); // has type B
```

**Comment by alexeypetrushin** [comment]
Haven't thought about conditional types. Thank you. Closing the issue.
