### ISSUE TITLE
Discriminate unions on assignment

### ISSUE THREAD

**Issue by weijarz** [Microsoft/TypeScript#30464]
## Suggestion

Narrow unions on assignment.

## Examples

```typescript
type State = { state: 'LOADING' } | { state: 'LOADED', data: string }
let state: State = { state: 'LOADING' }

function loadData (data: string) {
  state.state = 'LOADED'
  // Below line is required but it seems redundant
  if (state.state !== 'LOADED') throw new Error()
  state.data = data
}
```

**Comment by jack-williams** [comment]
I don't think narrowing `state` on assignment would be sound here. Consider:
```ts
function loadData (data: string) {
  state.state = 'LOADED'
  return state;
}
```
Should the return type of the function be narrowed to `{ state: 'LOADED', data: string }`? That doesn't seems correct to me.

**Comment by RyanCavanaugh** [comment]
If anything, the assignment to `state.state` should be illegal, but we don't have that kind of tracking yet.
