### ISSUE TITLE
Update tsconfig.json schema on SchemaStore for new commandline options for TypeScript 1.5

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3046]
here is the schema: http://json.schemastore.org/tsconfig
here is the store: https://github.com/SchemaStore/schemastore

and here are the new flags:
* [--rootDir](https://github.com/Microsoft/TypeScript/pull/2772)
* [--module umd](https://github.com/Microsoft/TypeScript/issues/2036)
* [--module system](https://github.com/Microsoft/TypeScript/issues/2616)
* [--noEmitHelpers](https://github.com/Microsoft/TypeScript/pull/2901)
* [--inlineSourceMap](https://github.com/Microsoft/TypeScript/pull/2484)
* [--inlineSources](https://github.com/Microsoft/TypeScript/pull/2484)
* [--newLine](https://github.com/Microsoft/TypeScript/pull/2921)

**Comment by kfranqueiro** [comment]
The `module` value for the systemjs format is actually just `system` right now, isn't it?  (Noticed this misprint in the roadmap as well.)

**Comment by mhegazy** [comment]
thanks @kfranqueiro for the correction. fixed.

**Comment by mhegazy** [comment]
I will hold off on this until we ship 1.5 to avoid confusion.

**Comment by paulvanbrenk** [comment]
Didn't see this issue, so I already submitted a pull request to the schemastore repo.
