### ISSUE TITLE
Auto complete not working for packages except those under @types folder

### ISSUE THREAD

**Issue by EnixCoda** [Microsoft/TypeScript#30474]
- VSCode Version: 1.30.2
- OS Version: macOS v10.13.6

Auto complete is one of my favorite features of VS code. But sometimes it doesn't provide what I need.

Steps to Reproduce:

1. Create a project with create-react-app: `npx create-react-app test-auto-complete --typescript`
2. Create a empty file `src/test.tsx`.
3. Make sure auto complete works: type `isvalid` and get following suggestions
  ![image](https://user-images.githubusercontent.com/7480839/51429916-fc740700-1c4e-11e9-9e0f-5a214689b458.png)
  Then confirm:
  ![image](https://user-images.githubusercontent.com/7480839/51429924-144b8b00-1c4f-11e9-9f1b-7e6ba8ed46af.png)
4. Install a typed package from npm. (I made one - [safe-touch](https://www.npmjs.com/package/safe-touch)
5. See if auto complete works for the package(type `safe` and expect suggestion of `safeTouch`):
  ![image](https://user-images.githubusercontent.com/7480839/51430054-5aedb500-1c50-11e9-9556-995ae6b0fb63.png)
  Negative :(
6. There is a difference between the types file of safe-touch and react. Safe-touch's is directly under `node_modules` while react's is under `node_modules/@types/`. Then I tried to make a folder under `@types` for the package, simply `cp -r node_modules/safe-touch node_modules/@types`.
7. See if auto complete works now:
  ![image](https://user-images.githubusercontent.com/7480839/51430120-46f68300-1c51-11e9-81af-4d002d0fdada.png)
  It works! 🎉🎉

So it seems that VS code is not able to auto complete types of `node_modules/[package]` even if the package is correctly typed?

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by mjbvz** [comment]
Confirmed with 3.4.0-dev.20190316

I believe this may be the same issue as #30033. Once you add `import safeTouch from "safe-touch";` anywhere in the project, then we start suggesting it as an auto import in all ts/tsx files.

**Comment by EnixCoda** [comment]
@mjbvz 
> Once you add import safeTouch from "safe-touch"; anywhere in the project, then we start suggesting it as an auto import in all ts/tsx files.

This makes sense and it works. Thank you!
