### ISSUE TITLE
Inconsistent behaviour with Object.values and enums with number values

### ISSUE THREAD

**Issue by BennoDev** [Microsoft/TypeScript#30487]
**TypeScript Version:**  

Version used: `3.3.3333`

I have reproduced this using `typescript/@next` which at the time of writing is `3.4.0-dev.20190319` 

**Search Terms:**

object.values
object.values enum
enum values

**Code**

``` ts
enum DirectionNumber {
    Down,
    Neutral,
    Up
}

console.log(Object.values(DirectionNumber);

// output ["Down", "Neutral", "Up", 0, 1, 2]
```

**Expected behavior:**

Expecting consistent output, logging the enum values correctly.

This expected behaviour is also shown in the provided playground where I compare it with the erroneous behaviour. 

**Actual behavior:**

When `Object.values` gets passed an enum with numbers as values, the resulting array contains both these numbers AND the keys. This seems unintuitive and unintended behaviour.

**Playground Link:** 

[Playground link](https://www.typescriptlang.org/play/#src=%2F**%0D%0A%20*%20Executing%20Object.values%20passing%20an%20enum%20with%20number%20as%20values%0D%0A%20*%20returns%20an%20array%20containing%20both%20key%20and%20value%0D%0A%20*%0D%0A%20*%20This%20behaviour%20seems%20weird%20and%20unintended%3F%0D%0A%20*%2F%0D%0A%0D%0Aenum%20DirectionNumber%20%7B%0D%0A%20%20%20%20Down%2C%0D%0A%20%20%20%20Neutral%2C%0D%0A%20%20%20%20Up%0D%0A%7D%0D%0A%0D%0Aenum%20DirectionString%20%7B%0D%0A%20%20%20%20Down%20%3D%20'DOWN'%2C%0D%0A%20%20%20%20Neutral%20%3D%20'NEUTRAL'%2C%0D%0A%20%20%20%20Up%20%3D%20'UP'%0D%0A%7D%0D%0A%0D%0Aconsole.log('Enum%20with%20number%20value%3A')%3B%0D%0Aconsole.log(Object.values(DirectionNumber))%0D%0A%0D%0Aconsole.log('Enum%20with%20string%20value%3A')%3B%0D%0Aconsole.log(Object.values(DirectionString)))

**Related Issues:**

**Comment by jcready** [comment]
This is well documented and intended behavior. [See documentation for reverse mappings in enums.](https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings)

**Comment by BennoDev** [comment]
Ah alright, thanks, I skimmed over that part of the documentation.

I have no doubt that the generated code is intended, however to me this behaviour conflicts with what is also documented ''enums are real objects that exist at runtime". 

Given the fact that enums in typecript have been around longer than `Object.values()` in ES the statement that 'enums are objects' that statement has always been true, up to this point.

If the intention is for people to be able to use enums as 'just objects' in runtime, then it should function correctly with all methods on the Object constructor.

**Comment by nmain** [comment]
I don't see a conflict there.  In order for `DirectionNumber.Down == 0` and `DirectionNumber[0] == "Down"` to be true, then in the transpiled js `DirectionNumber` _has_ to have a shape that looks something like:
```js
var DirectionNumber = { Down: 0, 0: "Down" };
```
But then, without any typescript involvement you get:
```js
console.log(Object.values(DirectionNumber)); // ["Down", 0]
```

And this is exactly what you'd expect out of any plain javascript object that obeyed `obj.Down == 0 && obj[0] == "Down"`

**Comment by BennoDev** [comment]
I understand the logic and reasoning behind the generated code, and why they currently appear in these arrays, but I disagree that this behaviour is desirable. 
The fact is that 2 very similar and valid uses of enums behave quite differently. 
On top of that it doesn't seem intuitive that a method called `Object.values` returns an array containing both key and values (and the other way around for `Object.keys`), for something that is for all intents and purposes designed to behave just like a normal object/key-value pair.

It's possible to skip enumeration of these key/value pairs generated for reverse mapping using `Object.defineProperty`, and still have perfectly function reverse-mapping. [Demonstration here](https://codepen.io/CloseDdog/pen/Mxqep)

**Comment by RyanCavanaugh** [comment]
The codegen for enums was chosen when ES3 targets (which don't have `defineProperty`) were still very common. Generating substantially different code between ES3 and ES5 targets is a worse inconsistency than someone's first-guess interpretation of `Object.keys(E)` being wrong.
