### ISSUE TITLE
3.4.0-rc - behaviour changed from 3.3 (regression?)

### ISSUE THREAD

**Issue by xaviergonz** [Microsoft/TypeScript#30489]
I found a case where types yielded differ between 3.3 and 3.4, but I'm not sure if it is a regression or it is intended

```ts
interface I<T> {
    a: T
}

// this is different between 3.3 and 3.4
type O<T> = T extends I<any> ? T : never
type B = O<I<number>> // I<number> in TS3.3, I<any> & I<number> in TS3.4 (which boils down to I<any>

// this however is the same
type O2<T> = T extends I<infer _> ? T : never
type B2 = O2<I<number>> // I<number> in both
```

**Comment by jack-williams** [comment]
This is caused by #29437 I think. Not sure I would class this as a regression: is it causing negative behaviour?

**Comment by xaviergonz** [comment]
At least for me :) , I use it like this

```ts
type ExtendIfI1<T> = T extends I1<any> ? T & Something : T
```

I can't use `T extends I1<infer X> ? I1<X> & Something : T` since if I1 had more stuff than I1 it would be lost, and having to write infer on the left for it to work was hard to find out

I think it boils down to the generic being inside the template part, this is
```
type A<T> = T extends any ? T : never
type B = A<number> // this is any & number, which is number

type O<T> = T extends I<any> ? T : never
type B = O<I<number>>
// could this be changed so it generates I<any & number>, which is I<number>
// rather than I<any> & I<number> ?
```

**Comment by RyanCavanaugh** [comment]
This is the intended behavior to improve inference elsewhere by "collapsing" conditional types.

One option is to use
```ts
type O<T> = T extends I<unknown> ? T : never
```
This will produce the type `I<unknown> & I<number>` which is indistinguishable from `I<number>` but also a little ugly.

You can also make the conditional non-distributive by writing
```ts
type O<T> = [T] extends [I<unknown>] ? T : never
```

**Comment by weswigham** [comment]
While the original behavior was intended, its interaction with `any` is undesirable - to reduce breakage and make better output types, in #30592 we introduce supertype reduction on substitution type instantiation, which should eliminate needless `any`'d up intersection members in most cases.
