### ISSUE TITLE
compilerOptions.rootDirs - folder list order should define the copying order.

### ISSUE THREAD

**Issue by moccaplusplus** [Microsoft/TypeScript#30497]
Folder list order in `rootDirs` should define the copying order (e.g. which file overwrites which, in case the same filename exists in more than one of `rootDirs` folder).

```
"rootDirs": ["src/gen/ts", "src/main/ts"], 
```
```
src
├── gen/ts     
   └── other.ts
├── main/ts              
   └── index.ts   # imports ./other.ts
   └── other.ts
```

now, no matter the order in which `rootDirs` folders are provided, the import "prefers" the file in the same folder.

Why its important? Consider we have some decorator based generator which enhances the source classes (like java's lombok). In this case we need to impose higher precedence on generated classes.

**Comment by RyanCavanaugh** [comment]
Debates about which behavior constitutes "correct" aside, this would be an extremely confusing and disruptive breaking change to roll out after the fact.

**Comment by moccaplusplus** [comment]
So maybe add a new option like `rootDirsOrdered`? This feature would be useful for "annotation" based generators.

**Comment by moccaplusplus** [comment]
@RyanCavanaugh 
Should I create a new issue (feature request) for option like `rootDirsResolveStrategy = DEFAULT | ORDERED`?
At first glimpse it seems I would be able to provide patch for this.

**Comment by RyanCavanaugh** [comment]
We can start with a suggestion if you like. Just to set expectations, I don't think we'd be inclined to complicate file resolution even further unless it was very often-requested.

**Comment by moccaplusplus** [comment]
Hi,

The name of the option (or if there is an additional option at all) does not matter. We just need something like java's compiletime classpath (with possibilty to impose resolve order to make generated files obscure the sources).

Of course, we could copy the files accordingly before build, but doing this manually we could drive IDE like vscode into confusion (the IDE should follow the settings of actual build). For this reason the "standard" classpath behavior would be appreciated.

To make sure I understood You properly, Should I create a new feature request?

**Comment by RyanCavanaugh** [comment]
A new issue clearly outlining the suggestion would be the next step, yes

**Comment by moccaplusplus** [comment]
@RyanCavanaugh 
Thanks for the information, I finally found time to write a proper feature request.
[Suggestion: Introduce possibility to control rootDirs resolve order](https://github.com/microsoft/TypeScript/issues/31703)
