### ISSUE TITLE
Problems with incremental build (3.4rc)

### ISSUE THREAD

**Issue by prettydiff** [Microsoft/TypeScript#30501]
I installed Version 3.4.0-rc about 12 hours ago and experimented with the new incremental build flag.  The build time in my application dropped from about 5.5s to about 2.5 seconds, but the compiled code was not updated.  After each compile the application performed exactly as written before all the incremental compiles not matter how many times I ran the compiler.

The application I used is https://github.com/unibeautify/sparser

I experimented with three different approaches:

1. compiler direct `tsc --pretty`
1. application build `node js/services build`
1. automatic build from node's fs.watch `node js/services server`

Not only did the incremental feature not produce new output, but the command line flag `--incremental` threw an error and told me to instead update the tsconfig.json file.  I strongly recommend allowing a flag via stdin irrespective of changes to tsconfig.json.  In my use case when I deliberately rebuild my application I want to go through the full compile to ensure everything is compiled fresh for fidelity.  When any sort of file system watch is active I want to have the fastest builds possible, such as from incremental compile.  I cannot conditionally chose incremental compile versus complete compile if the flag is set in the tsconfig.json.

**Comment by ajafff** [comment]
> The build time in my application dropped from about 5.5s to about 2.5 seconds, but the compiled code was not updated. After each compile the application performed exactly as written before all the incremental compiles not matter how many times I ran the compiler.

I experienced the same. I had no time to investigate further. 

In my case there are symlinks involved and the compiled output is placed in the same folder as the source. The

**Comment by prettydiff** [comment]
In my personal app where I experienced the problem here are the steps to reproduce:

1. git clone https://github.com/Unibeautify/sparser.git
1. cd sparser
1. npm install
1. tsc
1. node js/services build

At that point application is built and ready with a known good compile state.  Now to make it *incremental*.

1. Add `incremental: true` to the *tsconfig.json* file.

Now the application is ready for experimentation with incremental builds.  Perhaps the most direct way to see a quick change is:

1. Convert  `"use strict";` of the services.ts file to `"use strict";console.log("some random text here");`
1. Rebuild with `tsc`
1. Run the application `node js/services`

I did experiment with incremental builds in that way as a primitive means of testing when I realized changes weren't reflected in my code.  A way to test changes with a file watch is:

1. `node js/services server`
1. Open your browser to address *http://localhost:9999/demo/?scrolldown* and open the developer tools to the console tab
1. Covert `"use strict";` of demo/demo.ts to `"use strict";console.log("some random text here");`

In that manner any code change to any *ts* file in the project will cause the application to rebuild and refresh that demo tool.  The text in the console.log method will output to the browser's console.  What's interesting is that you can terminate the server, modify the tsconfig.json to remove incremental, and rerun the server to see everything working correctly.

**Comment by ajafff** [comment]
I just tested with the latest nightly: it fixed the issue in my repo.

**Comment by prettydiff** [comment]
@ajafff is that still `npm install typescript@rc -g` or do I have to specify something different?

**Comment by ajafff** [comment]
@prettydiff `typescript@next` is for nightly releases

**Comment by prettydiff** [comment]
I also confirm the nightly has resolved my defect and the performance improvement is also present.  I am not closing this issue just yet since the resolution is not yet in a stable release in case there is anything else that needs investigation.  Please close this issue as the project dictates.

**Comment by unstubbable** [comment]
I’m guessing this was fixed by #30605?

**Comment by prettydiff** [comment]
@unstubbable Hard to say.  I don't run `tsc --watch` on my applications though.  When I need filesystem watch I use Node because there is more that happens on top of the code compile.

**Comment by sheetalkamat** [comment]
Yes I think the problem described is fixed with #30605

**Comment by prettydiff** [comment]
With that fix I am noticing some strange behavior.  It seems the incremental compile appends to the generated JavaScript instead of overwriting it.  I am debugging a problem in my application when I noticed a console.log message I removed continues to output to the browsers terminal after a build.  Then I looked at the where in the code this is coming from and noticed it said line number 496904.

This is an exponential growth problem in that the size of the file grows faster with each build.

**Comment by sheetalkamat** [comment]
@prettydiff please provide the repro - using `tsc`. I am not sure what happens in `node js/services build` in your earlier repro step., It just shows me 
```
TypeScript Compilation

[00:00:02.240888500] TypeScript build completed without warnings.
[00:00:02.195398099] Total section time.
________________________________________________________________________
```
which I am not sure comes from tsc or uses which tsc as there I no typescript in `node_modules`. I don't think its issue with tsc since it overwrites new output and could be issue with the additional tools you are using in that step? If this repros with bare `tsc`, provide those steps

**Comment by prettydiff** [comment]
I don't include TypeScript with the application as its not needed for executing the application via NPM package.  I have TypeScript installed globally and suggest others do the same for modifying this application as a git clone.

As for the TypeScript step in the application's build process it is simply a node child process:

```javascript
node.child("tsc --pretty", {
    cwd: projectPath
}, function node_apps_build_typescript_callback(err:Error, stdout:string, stderr:string):void {
```
* https://github.com/Unibeautify/sparser/blob/master/services.ts#L1490

That is the only TypeScript compile instruction in the entire application.  I generally reserve using `tsc` manually when either I break the build code or download from github onto a fresh computer.

**Comment by sheetalkamat** [comment]
Without concrete steps using `tsc` to generate output and verify the repro, we cant investigate this further.

**Comment by prettydiff** [comment]
I have tracked down the exact behavior difference in my code from incremental builds.

https://github.com/Unibeautify/sparser/blob/master/services.ts#L1208

The `tsc` command happens in an earlier step and appears to work the same **provided that the compiled output is never modified** aside from the tsc command.  In my build process I read from the compiled output, the JavaScript files, and put them together from smaller library files into large singular application files.  The difference between incremental builds and static builds is the state of the JavaScript files at compile time.

In the old static builds the existing JavaScript code is written over from the current TypeScript code so that the JavaScript is always reflective of the TypeScript source.  You can modify the JavaScript and make any manner of changes, but at the next static build those changes gone like they never existed.

The incremental build provides partial changes to the JavaScript files.  It does not appear to look at the modifications of the TypeScript code for knowing which changes to make, but instead looks to modifications in the JavaScript output.  If that JavaScript is modified after a `tsc` compile this modified code becomes the frame of reference to make incremental changes during the next `tsc` build.

The evidence I used to make this distinction is file size from reading file data in my build process immediately between the `tsc` compile and the modifications from my build process.  In the old static builds that file size remains constant with each build such that the output is always the same.  In the incremental builds the file size is reflective of the file size following the previous build regardless of the `tsc` compile in between.

As a user I must make one of the following assumptions as a forced dichotomy:

1. The JavaScript output is generated entirely from the TypeScript source and thus the `tsc` resets that code in reflection to the TypeScript source.  That JavaScript **must not** be protected from manipulation, so that TypeScript can overwrite it as necessary.
1. The JavaScript output is the base from which the `tsc` command applies modifications.  This JavaScript code **must** be protected from modification so that only the `tsc` command imposes changes.

**Comment by SudharsanSukumar** [comment]
Is there an eta / good place to track adding --incremental to the command line?

**Comment by sheetalkamat** [comment]
@SudharsanSukumar --incremental on commandline is for 3.5

**Comment by RyanCavanaugh** [comment]
@prettydiff it sounds like your build setup violates some of our requirements. Basically if you modify the JS the compiler emits, it's not possible for `--build` (without `--force`) or `incremental` (in any capacity) to do the right thing; this is an unsupported scenario.

I'd recommend having TS build to an intermediate folder and having your own post-build steps only *read* from those outputs if you want to use `--build` / `incremental`.

**Comment by prettydiff** [comment]
I will use new file names for the things I am modifying then.  Thanks for the reply.
