### ISSUE TITLE
Please add searching capability to the Typescript Docs website

### ISSUE THREAD

**Issue by mdebeus** [Microsoft/TypeScript#30500]
## Search Terms
Search

## Suggestion
The Typescript Docs, at https://www.typescriptlang.org/docs/home.html, do not have any searching facility. Please add a way to search within these docs for the various Typescript keywords and concepts.

## Use Cases
The ability to search for documentation regarding a specific keyword or concept. For example search all of the docs for the keyword Enum or search for the concept Type Guard.

## Examples
See above

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlexWang-16** [comment]
Hello, I'm new to this project, but I would like to contribute to this issue. If any maintainers would provide me with a bit of help to get started, I will be grateful. Please let me know how I can help, thanks.

**Comment by RyanCavanaugh** [comment]
#12466
#26956 

![image](https://user-images.githubusercontent.com/6685088/54644516-b1138480-4a56-11e9-9084-c02d82aa3b6f.png)
