### ISSUE TITLE
Noneffective sourceMap

### ISSUE THREAD

**Issue by LongTengDao** [Microsoft/TypeScript#30504]
**TypeScript Version:**  3.3.3

**Search Terms:** sourceMap error, empty line, indent

**Code**

```
1|
2|export default function () {
3|throw Error();
4|}
```

**Expected behavior:**

When I use `require('source-map-support').install()` before I run my program packed by `require('rollup').rollup()`, I usually got error log like this:

```
1|
2|export default function () {
3|throw Error();
        ^
4|}
```

**Actual behavior:**

But when I write all my files with ts, and use `require('typescript').transpileModule` to transform each of them to js before bundling, and then run the bundled file, I got error log like this:

```
1|
2|export default function () {
            ^
3|throw Error();
4|}
```

If we manually correct and count the wrong line and column number, we will easily found, things happened as if the ts source code is:

```
1|export default function () {
2|    throw Error();
3|}
```

No empty line, 4 spaces indent -- is simply the compiled js code!

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment]
That sounds like an issue with your bundler, and not with TypeScript.
