### ISSUE TITLE
Type of generic function parameter not being inferred from interface generic type.

### ISSUE THREAD

**Issue by pikax** [microsoft/TypeScript#30505]
**TypeScript Version:**  3.4.0@rc

**Search Terms:**

**Code**

```ts
export type Prop<T> = { (): T }
export type PropType<T> = Prop<T>;
export type PropDefaultValue<T> = T;


export type PropValidatorFunction<T> = (value: T) => boolean;
export type PropValidator<T> = PropOptions<T>;


export type PropOptions<T> = {
    type: PropType<T>;

    value?: PropDefaultValue<T>,
    required?: boolean;
    validator?: PropValidatorFunction<T>;
}

export type RecordPropsDefinition<T> = {
    [K in keyof T]: PropValidator<T[K]>
}
export type PropsDefinition<T> = RecordPropsDefinition<T>;


declare function extend<T>({ props }: { props: PropsDefinition<T> }):  PropsDefinition<T>;

interface MyType {
    valid: boolean;
}

const r = extend({
    props: {
        // gets resolved to PropOptions<any> but should be PropType<MyType>
        notResolved: {
            type: Object as PropType<MyType>,

            // type not inferred 
            validator: (x) => {
                return x.valid;
            }
        },
        // gets resolved currectly to PropType<MyType>
        // on typescript@3.4rc doest resolve to PropType<MyType>
        explicit: {
            type: Object as PropType<MyType>,

            // type not inferred 
            validator: (x: MyType) => {
                return x.valid;
            }
        }
    }
})

// return type on 3.4@rc doesn't get resolved
r.explicit
r.notResolved
r.explicit.required
r.notResolved.required
```

**Expected behavior:**
The `validator` parameter as typescript `type` inferred from `T`.
Props record values to be resolved with the interface of PropType<T>
Return type to be `PropsDefinition<T>`

**Actual behavior:**
Getting validator parameter resolved as `any`/`unknown`.
Record types are not getting resolve to the type `PropOptions<T>` in 3.4@rc but working in 3.3.x
The return type not working in 3.4@rc

**Playground Link:** 
[playground](http://www.typescriptlang.org/play/index.html#src=export%20type%20Prop%3CT%3E%20%3D%20%7B%20()%3A%20T%20%7D%0D%0Aexport%20type%20PropType%3CT%3E%20%3D%20Prop%3CT%3E%3B%0D%0Aexport%20type%20PropDefaultValue%3CT%3E%20%3D%20T%3B%0D%0A%0D%0A%0D%0Aexport%20type%20PropValidatorFunction%3CT%3E%20%3D%20(value%3A%20T)%20%3D%3E%20boolean%3B%0D%0Aexport%20type%20PropValidator%3CT%3E%20%3D%20PropOptions%3CT%3E%3B%0D%0A%0D%0A%0D%0Aexport%20type%20PropOptions%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20PropType%3CT%3E%3B%0D%0A%0D%0A%20%20%20%20value%3F%3A%20PropDefaultValue%3CT%3E%2C%0D%0A%20%20%20%20required%3F%3A%20boolean%3B%0D%0A%20%20%20%20validator%3F%3A%20PropValidatorFunction%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20RecordPropsDefinition%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20keyof%20T%5D%3A%20PropValidator%3CT%5BK%5D%3E%0D%0A%7D%0D%0Aexport%20type%20PropsDefinition%3CT%3E%20%3D%20RecordPropsDefinition%3CT%3E%3B%0D%0A%0D%0A%0D%0Adeclare%20function%20extend%3CT%3E(%7B%20props%20%7D%3A%20%7B%20props%3A%20PropsDefinition%3CT%3E%20%7D)%3A%20%20PropsDefinition%3CT%3E%3B%0D%0A%0D%0Ainterface%20MyType%20%7B%0D%0A%20%20%20%20valid%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aconst%20r%20%3D%20extend(%7B%0D%0A%20%20%20%20props%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20gets%20resolved%20to%20PropOptions%3Cany%3E%20but%20should%20be%20PropType%3CMyType%3E%0D%0A%20%20%20%20%20%20%20%20notResolved%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20Object%20as%20PropType%3CMyType%3E%2C%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20type%20not%20inferred%20%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20validator%3A%20(x)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20x.valid%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20gets%20resolved%20currectly%20to%20PropType%3CMyType%3E%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20on%20typescript%403.4rc%20doest%20resolve%20to%20PropType%3CMyType%3E%0D%0A%20%20%20%20%20%20%20%20explicit%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20Object%20as%20PropType%3CMyType%3E%2C%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20type%20not%20inferred%20%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20validator%3A%20(x%3A%20MyType)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20x.valid%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20return%20type%20on%203.4%40rc%20doesn't%20get%20resolved%0D%0Ar.explicit%0D%0Ar.notResolved%0D%0Ar.explicit.required%0D%0Ar.notResolved.required%0D%0A%0D%0A)

**Comment by RyanCavanaugh** [comment]
This hasn't worked particularly well in any version, but this seems to be regressing:
```ts
type Box<T> = {
    contents: T;
    contains?(content: T): boolean;
};
type Mapped<T> = {
    [K in keyof T]: Box<T[K]>;
}
declare function id<T>(arg: Mapped<T>): Mapped<T>;

// obj1: Mapped<{ foo: string }> ✔
const obj1 = id({
    foo: {
        contents: ""
    }
});

// 3.3 obj2: Mapped<{ foo: any }> ❌
// 3.4 obj2: Mapped<{}> ❌❌
const obj2 = id({
    foo: {
        contents: "",
        // k: implicit any ❌
        contains(k) {
            return k.length > 0;
        }
    }
});
```

**Comment by ahejlsberg** [comment]
The key issue here is that during the initial pass in type inference where we defer context sensitive function expressions and arrow functions, we never perform reverse mapped type inference on types that contain anything context sensitive. That is too conservative because, as illustrated by the examples, there are cases where we want to infer from the properties that aren't context sensitive and then apply those inferences to the context sensitive locations. I will be putting up a PR that does this.
