### ISSUE TITLE
Compile On Save performs unnecessary compilation in global projects

### ISSUE THREAD

**Issue by uniqueiniquity** [microsoft/TypeScript#30508]
Originally reproduced in 3.1, but appears to still occur in `typescript@next`.

**Search Terms:**
compile on save, global, recompilation, compilation
**Scenario**
In a project using global scope (rather than modules) and files `file1.ts`, `file2.ts`, and `file3.ts`, trigger compile on save in `file1.ts`, then `file2.ts`.

**Expected behavior:**
The first invocation of compile on save compiles all three files, and the second only compiles `file2.ts`.

**Actual behavior:**
Both invocations compile all three files.

**Comments**
We appear to determine whether or not to compile all files in a project by hashing the declaration emit of the file being saved. Since is done exclusively for the file being saved, saving multiple files in a project causes repeated recompilation of the whole project.
Would it be reasonable to consider an option to calculate the hash for every affected file on the first invocation of compile on save?

**Comment by sheetalkamat** [comment]
I think we should do this only if the project enables .d.ts emit as otherwise we would be doing unnecessary d.ts emit
