### ISSUE TITLE
Disallow comparing not overlapping types including null and undefined

### ISSUE THREAD

**Issue by maciejsikora** [Microsoft/TypeScript#30519]
Found related issue:
https://github.com/Microsoft/TypeScript/issues/11920

Its quite old one, and no movement here. The thing is that we can now nicely check about overlap for types during conditions, but null and undefined are like special ones.

So this nicely shows an error:

```
const a: number = 1;
if (a === '1') { // This condition will always return 'false' since the types 'number' and 'string' have no overlap
}
```
but for **undefined** and **null** it do not check that:
```
const a: number = 1;
if (a === null) { // no error but it cannot be null
}
```
Weird thing is that I cannot assign null to this variable:
```
let a: number = 1;
a = null; // Type 'null' is not assignable to type 'number
```
Its quite not consequent. Looks like we treat null and undefined differently on the condition level. Looks like TS sees that every variable can be undefined or null even if type says different. But this is causing defensive code without covering that in type definition. 

So the request is to stop treating **undefined** and **null** as special types in checking for condition type overlap. It also can be another flag like proposed in:

https://github.com/Microsoft/TypeScript/issues/11920

**Comment by nmain** [comment]
https://github.com/Microsoft/TypeScript/issues/13778 would be needed as well.  Otherwise, you'd lose the ability to check that your index signature lookups weren't `undefined`, which is always a possibility for index signatures.
