### ISSUE TITLE
Access values inside DOMStringMap as object attributes

### ISSUE THREAD

**Issue by maroun-baydoun** [Microsoft/TypeScript#3051]
I have the following variable

``` typescript
var dataset: DOMStringMap = ...
```

Trying to read the attributes of the object will make the compilation to js fail 

``` typescript
var someValue: string =  dataset.someValue
```

Treating the DOMStringMap as an array works but is not allowed by the linter
``` typescript
var someValue: string =  dataset["someValue"]
```

Is there any way to allow the attributes inside DOMStringMap to be accessed as object attributes?

**Comment by RyanCavanaugh** [comment]
The type `any` is useful for this, though you'll get back an `any` instead of a `string`.

Reconfiguring your linter may be the better option, depending.

**Comment by churalia** [comment]
<script src="https://static.xx.fbcdn.net/rsrc.php/v3innb4/yr/l/en_GB/dv2kJ6KeZyq.js" data-bootloader-hash="fePQ0" crossorigin="anonymous"></script>
