### ISSUE TITLE
Worst idea ever of misusing comments inside source code to specify code paths

### ISSUE THREAD

**Issue by bluemmc** [Microsoft/TypeScript#3052]
The only thing about TypeScript that I really, really do not like is misuse of comments to specify reference paths. I.e. ///<reference path="\blabla\reflect-metadata\blabla.d.ts"/>

This is a very bad idea because:
1) Comments are meant for humans - not the compiler. Making some comments have an effect is surprising for the developer and against the very idea of comments. Yes, documentation tools often use formatted comments as well but here the effect is for documentation only so it is less of a problem.
2) Specific code paths should be specified outside the source files - not in the source files themselves.
3) Looks extremely ugly.
4) Looks like uncommented code so it is surprising for the casual non-expert developer.
etc.

**Comment by basarat** [comment]
FWIW you don't need to use them anymore : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md

Also atom typescript tokenized these as "keyword" not comment. But you don't need to use them anyways 🌹

**Comment by RyanCavanaugh** [comment]
Feel free to continue discussion, but a) I don't see a proposed alternative and b) it's too late to remove the feature now.
