### ISSUE TITLE
Typescript should not be doing code removal for non TS code

### ISSUE THREAD

**Issue by hulkish** [Microsoft/TypeScript#30525]
Please see https://github.com/babel/babel/issues/9723#issuecomment-475022396

This code removal is actually unsafe. For example, if `foo` had [side effects](https://stackoverflow.com/questions/49160752/what-does-webpack-4-expect-from-a-package-with-sideeffects-false/49203452#49203452) - how can typescript know its safe to remove the import, without processing that file first? Aka, this is a task for a bundler/compiler.

**Search Terms:**
`remove import`, `code remove`

**Code**
```ts
import foo from 'foo';
export bar from 'bar';
export * as baz from 'baz';

export default class Foobar {}
```

**Expected behavior:**
```js
import foo from 'foo'; // why is this line is removed?
import _bar from 'bar';
export { _bar as bar };
import * as _baz from 'baz';
export { _baz as baz };
var Foobar = function Foobar() {};
export { Foobar as default };
```

**Actual behavior:**
```js
import _bar from 'bar';
export { _bar as bar };
import * as _baz from 'baz';
export { _baz as baz };
export default class Foobar {}
```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=import%20foo%20from%20'foo'%3B%0D%0Aexport%20bar%20from%20'bar'%3B%0D%0Aexport%20*%20as%20baz%20from%20'baz'%3B%0D%0A%0D%0Aexport%20default%20class%20Foobar%20%7B%7D

**Related Issues:** 
https://github.com/babel/babel/issues/9723#issuecomment-475022396

**Comment by RyanCavanaugh** [comment]
Duplicate #9191 and dozens of other issues discussing this

**Comment by hulkish** [comment]
@RyanCavanaugh Fair enough, however - I landed here after looking to fix this in `@babel/plugin-transform-typescript`. And, that issue you've referenced hasn't had activity in months. What do you recommend?

**Comment by RyanCavanaugh** [comment]
`import "foo";` if you need the side effects

**Comment by hulkish** [comment]
But, this doesn't remove the problem of typescript incorrectly doing code removal.

**Comment by RyanCavanaugh** [comment]
You can write

`foo;`

if you're depending on the specific identifier being in the file
