### ISSUE TITLE
Update repo URL to HTTPS

### ISSUE THREAD

**Issue by lgarron** [Microsoft/TypeScript#30527]
The URL at the top of https://github.com/Microsoft/TypeScript is currently HTTP:

<img width="878" alt="Screen Shot 2019-03-21 at 14 35 24" src="https://user-images.githubusercontent.com/248078/54786670-b30c4d80-4be6-11e9-99b6-85383cff0cd9.png">

It should be safe to update to https://www.typescriptlang.org :-D

**Comment by lgarron** [comment]
(Also, I noticed that https://typescriptlang.org/ (no www) seems to hang. The HTTP version of it redirects. HTTPS + HSTS + preloading would be super awesome. :-D https://hstspreload.org/?domain=typescriptlang.org)

**Comment by weswigham** [comment]
Your initial comment has been fixed~

I refer you to @DanielRosenwasser for your remaining website suggestions~

**Comment by lgarron** [comment]
> I refer you to @DanielRosenwasser for your remaining website suggestions~

Thanks! I've moved that to a separate issue: #30529.
