### ISSUE TITLE
[Feature request] add overwrite keyword for extend and without write body for change type

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#30533]
## Suggestion

```ts
export class ClassParent
{
	fn1(inputArgv: string): string
	{
		// do something return value
		return inputArgv.toLowerCase();
	}
}

export enum Enum1
{
	a = 'BIG5',
}

export enum Enum2
{
	a = 'big5',
}

export class ClassSub1 extends ClassParent
{
	overwrite fn1(inputArgv: Enum1): Enum2
}

export class ClassSub2 extends ClassParent
{
	overwrite fn1(inputArgv: string): number
	{
		return parseInt(inputArgv)
	}
}
```

## Use Cases

1. this make we can't extends a type but without copy `parent fn body` or use `return super.fn1(xxx)`
2. allow change return type in sub class

## Examples

expected type

```ts
export declare class ClassSub1 extends ClassParent {
    fn1(inputArgv: Enum1): Enum2;
}
export declare class ClassSub2 extends ClassParent {
    fn1(inputArgv: string): number;
}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by tadhgmister** [comment]
when you are extending a class it is expected methods you override are still compliant to the base class methods. Like lets say we had this class:

```
class Base {
    public doAThing(x: string) {
        return 'hello ' + x;
    }
    public doOtherThing(){
        const a = this.doAThing('human');
        // a has type string here because we defined the method to return a string
        return a;
    }
}
```

If you want to override `doAThing` and it doesn't follow the same call signature then the other method `doOtherThing` would break!  A major part of inheritance is you provide the same interface as the base class, If you are changing the call signature without providing original signature as well then you aren't really providing the same signature.

**Comment by bluelovers** [comment]
in `ClassSub1` it is follow old signature, just only limit input and output value, so it not break

in `ClassSub2` that is why this keyword call as `overwrite`

**Comment by tadhgmister** [comment]
In `ClassSub1` you are saying the input does not accept any string like the parent did but only values in a specific enum, so you don't provide a compliant interface since `ClassSub1.fn1('hello')` isn't valid where it was valid in base class. What is more likely is that you should provide both the new call signature as well as the old one with something like this:

```
export class ClassSub1 extends ClassParent {
    public fn1(inputArgv: Enum1): Enum2; // override for extended behaviour
    public fn1(inputArgv: string): string; // support original behaviour as well
    public fn1(inputArgv: Enum1 | string): Enum2 | string {
        if(inputArgv in Enum1) {
            // do custom logic here
        } else {
            // for non Enum values use default behaviour
            return super.fn1(inputArgv);
        }
    }
}
```

As for `ClassSub2` I really don't think only changing the return value is a good idea, you cannot be compliant with base class interface!  The documentation does say you can get around the type checker by using a double conversion which you can accomplish the same thing here by using a intermediate class that removes all type checks on the call signature:

```
class Wrapper extends ClassParent {
    public fn1(inputArgv: any): any {
        return super.fn1(inputArgv);
    }
}
export class ClassSub2 extends Wrapper {
    // now this is allowed
    public fn1(inputArgv: string): number {
        return parseInt(inputArgv, 10);
    }
}
```
but like I already said, this means you do not provide the original interface, so this code which is universally expected to work with inheritance would not work:
```
let x: ClassParent = new ClassSub2() as any;
let y = x.fn1('hello'); // y is typed to be a string here but will actually be a number!!!!
```

So work arounds for both your cases already exist, you are basically asking to override the type checker to allow you to break the nature of inheritance. I don't think it's a good idea but there are options if you are absolutely sure this is a good idea.

**Comment by RyanCavanaugh** [comment]
Our model of classes is that *inheritance is subtyping*; there are other composition mechanisms available to you if you want to reuse parts of another class without forming a subtype relationship.

**Comment by bluelovers** [comment]
other use case

https://github.com/bluelovers/node-opds/blob/eeba1eb885fdec818c7d22df444b72054ded8f6e/lib/class.ts#L53-L65

class Base
```ts


		static deserialize<T extends Base>(json: Partial<T>, options?: IParseOptions): T
		static deserialize<T extends Base, J extends Base.TSTYPE | Partial<T>>(json: J, options?: IParseOptions): T & Base
		static deserialize<T extends Base, J extends Base.TSTYPE | Partial<T>>(json: J, options?: IParseOptions): T & Base
		{
			return TaJson.deserialize<T>(json, this, options) as any;
		}


		static parse<T extends Base>(json: string, options?: IParseOptions): T
		{
			return TaJson.parse<T>(json, this, options)
		}

```

https://github.com/bluelovers/node-opds/blob/eeba1eb885fdec818c7d22df444b72054ded8f6e/lib/v1/core.ts#L505-L515

class Feed extends Base
```ts


	static deserialize<T extends Feed, J extends Feed.TSTYPE>(json: J, options?: IParseOptions): T
	{
		return TaJson.deserialize<T>(json, this, options);
	}


	static parseJSON<T extends Feed>(json: string, options?: IParseOptions): T
	{
		return TaJson.parse<T>(json, this, options)
	}


```

`deserialize` can't use `super`, because it is `static` method

but only wanna change it return type with out copy same function body

## expected code

class Feed extends Base
```ts


	overwrite static deserialize<T extends Feed, J extends Feed.TSTYPE>(json: J, options?: IParseOptions): T

```

**Comment by bluelovers** [comment]
```ts
import util = require('util')

export class P
{
	fn1(v: string)
	{
		return 1
	}

	static create()
	{
		console.log('P', util.inspect(this));
		return new this
	}
}

export class A1 extends P
{
	fn1(v: string | number)
	{
		return 1
	}

	fn2(v: string | number)
	{
		return 1
	}
}

export const a1 = A1.create();

A1.create().fn1(1)
```

**Comment by bluelovers** [comment]
@tadhgmister it make we need copy everything from parent
