### ISSUE TITLE
Type inference doesn't work in `if` statement if its condition is provided as a variable.

### ISSUE THREAD

**Issue by Rokt33r** [Microsoft/TypeScript#30539]
**TypeScript Version:** 3.3.3

**Search Terms:**

const condition type inference
boolean variable condition

**Code**

```ts
let maybeNumber: number | null = null as any

if (maybeNumber != null) {
    Math.floor(maybeNumber) // ts know it is a number
}

const isNumber = maybeNumber != null
if (isNumber) {
    Math.floor(maybeNumber) // ts still doesn't know it is a number
}
```

**Expected behavior:**

No error

**Actual behavior:**

Error occurs in the second `if` statement.

```
Argument of type 'number | null' is not assignable to parameter of type 'number'.
  Type 'null' is not assignable to type 'number'.
let maybeNumber: number | null
```

**Playground Link:** 

https://www.typescriptlang.org/play/#src=let%20a%3A%20number%20%7C%20null%20%3D%20null%0D%0A%0D%0Aif%20(a%20!%3D%20null)%20%7B%0D%0A%20%20%20%20Math.floor(a)%0D%0A%7D%0D%0A%0D%0Aconst%20aIsNumber%20%3D%20a%20!%3D%20null%0D%0Aif%20(aIsNumber)%20%7B%0D%0A%20%20%20%20Math.floor(a)%0D%0A%7D%0D%0A

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/29323

**Comment by j-oliveras** [comment]
Typescript don't track related variables.

This is duplicate of a lot of issues (with this case or others). See #9998.

**Comment by Rokt33r** [comment]
@j-oliveras Thanks!
