### ISSUE TITLE
No member suggestions after class property definition without  semicolon

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#30536]
From https://github.com/Microsoft/vscode/issues/69897

**TypeScript Version:**  3.4.0-rc

**Search Terms:**
- suggestion, suggest, completions

**Code**
For the javascript

```js
// @ts-check

import React from 'react';

class X extends React.Component {
    x = 1
    comp
}
```

1. Trigger suggestions after `comp`

**Expected behavior:**
Suggestions for the react `componentDid...` methods returned

**Actual behavior:**
Global suggestions returned

If you add a semicolon after `x = 1;`, you get the correct suggestions:

```ts
// @ts-check

import React from 'react';

class X extends React.Component {
    x = 1
    comp
}
```
**Playground Link:** 

**Related Issues:**

**Comment by Kingwl** [comment]
I‘m not sure why we do not findAncestor in `tryGetObjectTypeDeclarationCompletionContainer`? the performance？
