### ISSUE TITLE
Allow "this.constructor" in a constructor before super

### ISSUE THREAD

**Issue by ricmoo** [Microsoft/TypeScript#30537]
What I want to be able to do is ultimately have access to the class inside a constructor. Accessing this.constructor should be safe (I think?), and would allow for sub-classes to call their own static methods before calling the super:

```javascript
class BaseProvider {
    constructor(url: string) { ... };
}

abstract class GenericProvider {
    constructor(something: any) {
        let url = this.constructor.getUrl(something);
        super(url);
    }
    static getUrl(something: any): string {
        throw new Error("subclass must implement this");
    }
}

class SpecificProvider {
    // This class does not need to override the constructor, just the static method

    static getUrl(something: any): string {
        return "https://helloworld"
    }
}
```

I have not been able to find a way to get around this, but if it already exists, awesome. Otherwise, this would go a long way to improving the use of static methods in TypeScript, and a the standard way to handle things [like this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static).

Thanks!

**Comment by ajafff** [comment]
It's a ReferenceError to reference `this` in the constructor of a derived class before calling `super()`.
This has been that way since the introduction of classes in ES6

**Comment by DanielRosenwasser** [comment]
I think you want `new.target`, right?

**Comment by ricmoo** [comment]
You are absolutely correct, that is **exactly** what I was looking for, and it works great!

Thanks! :)

**Comment by ricmoo** [comment]
(quick note for others that find this issue; when compiled for the ES5 target, the generated code replaces `new.target` with `this.constructor` :))

**Comment by DanielRosenwasser** [comment]
Yeah, my understanding is that that's why `new.target` exists. `¯\_(ツ)_/¯`
