### ISSUE TITLE
Global `name` in lib.dom.d.ts should be unknown instead of never

### ISSUE THREAD

**Issue by jchv** [Microsoft/TypeScript#30534]
**TypeScript Version:**  3.3.3333 (`master` appears to be affected as well)

**Search Terms:** `name: never`

**Code**

```ts
// This should definitely not work, but it does.
window.setInterval(name, name);
```

**Expected behavior:**
`name` should not be assignable to every possible type. The `never` type is used to attempt to prevent users from using `name` when they meant `this.name`, but actually it does exactly the opposite, allowing the user to use `name` even when a type other than string is called for, making `name` even less safe.

>The never type is a subtype of, and assignable to, every type

The type `unknown` seems to prevent this problem since it is not assignable to any other type. `never` seems to be explicitly geared towards values that can't possibly be reached.

**Actual behavior:**
`name` is never, and therefore assignable to anything.

**Playground Link:**
https://www.typescriptlang.org/play/#src=window.setInterval(name%2C%20name)%3B%0D%0A

**Related Issues:**
  * #15424: It seems someone raised the issue but it was not realized that the `never` type didn't fix the problem. The issue correctly summarizes the problem: "`name` global variable is still assignable to `string` type."
  * #28982: Explains the rationale for why `never` is assignable to every type. (My take: makes sense, but it also makes me wonder if `never` should be allowed to be _explicitly_ specified as anything other than a return type. I don't think it ever will work as intended for anything else.)

**Comment by RyanCavanaugh** [comment]
See #18433

**Comment by jchv** [comment]
Oops. This issue is tough to search for.
