### ISSUE TITLE
High CPU for Visual Studio 2015 RC (TS 1.5 Beta)

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#3054]
Hi,

The VS editor is close to unusable after the upgrade to 1.5 Beta. CPU utilisation is running at 70% plus constantly. This makes the editor extremely sticky. Here's a side-by-side shot of the experience:

![a](https://cloud.githubusercontent.com/assets/1106823/7495269/d5a3bf4c-f404-11e4-9df2-6d40b8cd57e4.gif)

**Task Manager**
![b](https://cloud.githubusercontent.com/assets/1106823/7495271/d9756558-f404-11e4-90c7-a2a8ba70fd33.gif)

In the first shot, I'm typing as fast as possible, and attempting to select from the completion list as quickly as possible. However, it takes ages for the completion list to show up, and once it does it's very stick navigating the list items. After the enter key is hit, it takes a further 2-3 seconds for the selection to actually register.

The CPU stays high constantly sometimes even when there is no editing occurring.

**Comment by NoelAbrahams** [comment]
Hi, what is the recommended way to get TS version 1.4 working with Visual Studio 2015 RC?

I want to try to get back to the last stable version, but using VS 2015 RC, since I'd rather not spend half a day uninstalling 2015 RC and installing 2015 CTP 5.

**Comment by mhegazy** [comment]
I believe Uninstalling TS 1.5 and repairing VS 2015 RC.should do the trick.. @paulvanbrenk is this correct?

**Comment by CyrusNajmabadi** [comment]
Can you share your project with us so we can investigate?

**Comment by NoelAbrahams** [comment]
@CyrusNajmabadi, I'm happy to try out any debugging without actually sharing the project, as that won't be possible. It's not one project it's a collection of them inside a VS solution.

**Comment by vladima** [comment]
As an easy thing to try, can you start the VS, open a .ts file, attach a script debugger to it, make a screenshot of what you see in solution navigator and put it here?

**Comment by NoelAbrahams** [comment]
@vladima,

> can you start the VS, open a .ts file, 

Okay, opened the solution, and a .ts file

> attach a script debugger to it 

I started another VS instance, went to Debug > Attach to Process. Clicked on 'Select' checked 'Script'. Then clicked on 'Attach'.

![image](https://cloud.githubusercontent.com/assets/1106823/7516917/00ba4d20-f4ca-11e4-837b-e25bb5228632.png)

> make a screenshot of what you see in solution navigator

There's nothing in the solution explorer:

![image](https://cloud.githubusercontent.com/assets/1106823/7517078/cb1c06f8-f4ca-11e4-9669-9612840c1f8b.png)

I think you want me to do something else altogether, but a literal reading of your instructions doesn't produce anything interesting.

**Comment by wgebczyk** [comment]
Hi, I have very similar problem, but not on such scale. Probably the code base is much smaller.
I've attached second instance of VS and profiled that.

I can privately provide profiling results or source code, but I don't want to publish it.

### cloc stats
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                     176           3791           5427          54088
Javascript                      66           6741           5713          33257
CSS                             14           2249            237          18099
HTML                            49            170             24           5125
C#                               9            126             37           1315
MSBuild script                   6              0              0            751
JSON                             6              2              0            339
ASP.Net                          5             11              0             80
XAML                             2              4              0             30
DOS Batch                        1              2              0             14
XML                              1              0              0              6
-------------------------------------------------------------------------------
SUM:                           335          13096          11438         113104
-------------------------------------------------------------------------------
```

**Comment by vladima** [comment]
We've made a number of changes that should drop CPU usage\reduce the lag when completion is requested both on the script side(#3183, #3131, #3117) and on VS side.

**Comment by NoelAbrahams** [comment]
@vladima, is there a way for me to test the fix to see the problem has gone away?

**Comment by vladima** [comment]
Unfortunately not, you'll need changes on the VS side that are not released yet.

**Comment by NoelAbrahams** [comment]
Okay. I just wanted to say that the problem wasn't with the DevMode flag being set: it still exists. It occurs on the CommonJS projects - so if the fixes were to do with reading files off the file system then that may explain why (because of the import paths - I'm assuming). Basically, the minute I start working on a CommonJS project the CPU starts climbing, and I don't see a let off until a OOM crash at some point.

I do not know why other's haven't run into this problem. It might have to do with the large scale/CommonJS combination that we have.

Feel free to mail me a patch to try out.

**Comment by vladima** [comment]
Fixes helped to reduce the typing lags and make overall editor experience smoother.  I'm still looking into the possible interaction issues with NTVS however since I cannot repro the problem locally having a heap dump from you will be very helpful.

**Comment by NoelAbrahams** [comment]
@mhegazy, I've sent you and @vladima an email or two but don't seem to have got through. Did you receive anything from me today?

**Comment by mhegazy** [comment]
@NoelAbrahams no. nothing today.

**Comment by NoelAbrahams** [comment]
@vladima, @mhegazy, I've sent you the links to the dump. Please let me know if you have everything you need.

**Comment by NoelAbrahams** [comment]
@vladima, I sent across the diagnostics from NTVS yesterday. Let me know if you need another dump.

**Comment by NoelAbrahams** [comment]
I've also noticed that when the IDE is left unattended for a couple of hours (e.g. lunch break) it just becomes ultra slow and unresponsive upon returning, and often crashes soon after.

**Comment by sgireddy** [comment]
Was a non-issue in windows 7, this issue popped up as soon as I upgraded to Windows 10. Tried everything disabled intellisense, disabled analysis for node modules etc. Reinstalled VS & NTVS. Nothing helped. CPU is at constant 15-20% on a six core server. takes about 5 minutes to load then everything is fine.

**Comment by danquirk** [comment]
@NoelAbrahams this is with 1.5 (not beta) now yes? Should we be re-opening this issue or filing something new?

**Comment by NoelAbrahams** [comment]
I'm not having any performance issues with Windows 10 using VS 2015 RTM/TS 1.5.4.

So I would say that @sgireddy is probably experiencing a separate issue.

**Comment by mhegazy** [comment]
@sgireddy can you provide more information about your project? a proc dump? also can you please file a new issue.
