### ISSUE TITLE
IntelliSense and autocomplete are broken after a period of time

### ISSUE THREAD

**Issue by Disane87** [microsoft/TypeScript#30546]
Versions:
```
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Datum: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17763
```

Steps to Reproduce:

1. Starting VS code
2. Working a time
3. Then IntelliSense (and autocomplete and other stuff) is not working anymore

Does this issue occur when all extensions are disabled?: Yes

Additionally I've reinstalled NPM, Typescript and previous Version of VS Code and the Insider-Build, nothing worked. This problem occuredyesterday the first time.

Are there any logs I can check or other stuff, which can help me to solve this?

Our project is an Angular 7 project.

**Comment by mjbvz** [comment]
I haven't been able to repro this with just that single file so I'm guessing that more context is required to trigger the error. Can you share the project or the full logs? You can email them too if you are concerned about posting them publicly: matb at microsoft

**Comment by Disane87** [comment]
Sharing the entire project would be against our business privacy policy but I can send you the full logs next week when I‘m back at work.

**Comment by Disane87** [comment]
Apparently now it seems to work again since two weeks and I don‘t know why, because I didn‘t changed anything. Really confusing.

**Comment by johnsoncodehk** [comment]
I have the same problem, and I noticed that when the problem occurred, VSCode's CPU usage reached 100% (the heatsink sound became very large), did TS Server enter an infinite loop?

Although this is not a workaround, you can run ```TypeScript: Restart TS Server``` to continue using it for the time being.

**Comment by Disane87** [comment]
@mjbvz unfortunatly I can't repdouce the error at the moment. Apperently something has changed since tweo weeks, but I can't say what. At the moment it works fine. I gonna report back when it occurs again.

**Comment by Disane87** [comment]
@mjbvz problem occured now an another file. I've just send you the entire (uncensored) logfile to your mail.

**Comment by Link-69** [comment]
Really frequent issue on my side since multiple months, on multiple ASP.NET Core/React(js) projects.

**Comment by Disane87** [comment]
Now its crashing on almost every file. Pretty annoying :-(

**Comment by ManAnRuck** [comment]
i have the issue, that my intellisense stop working after adding `title` as property 🧐

![ezgif com-optimize](https://user-images.githubusercontent.com/2183135/64486698-94e7e780-d230-11e9-98c6-e3b4769b823f.gif)

**Comment by Disane87** [comment]
I've wrote @mjbvz a mail with the detailed log file in april. Any updates on this? This problem is stll occuring.

**Comment by mjbvz** [comment]
Closing this issue as out of date

If you are still seeing issue with the current TypeScript release, please open a new issue so that we can investigate
