### ISSUE TITLE
Building a typescript &  react library

### ISSUE THREAD

**Issue by TacB0sS** [Microsoft/TypeScript#30556]
I am unsure how to categorize this, but it is either a bug in the dependency resolving mechanism or it is working exactly as intended and I am doing something wrong and it doesn't cover my case...

I am developing a typescript & react boilerplate for frontend and backend, and while the backend seems to be working just fine with link library sources, the frontend will not compile while I work with linked library sources.

After long and frustrating experimentation, I realized it is the symlink at `node_modules\${my-lib}` that prevents my code from **compiling only the frontend**.

I say the symlink because if I manually copy my project folder content into the `node_modules\${my-lib}` as a folder.. everything works just fine. 

You can use the full boilerplate repo [here](https://github.com/nu-art-js/typescript-boilerplate) to reproduce the issue, follow the readme.. the first time without library sources everything works just fine, with sources.. everything breaks.

My setup:
```
I develop on Mac.
npm: 6.4.1
node: 8.15.0
typescript: 3.3.3333
webpack: 4
``` 

## Checklist

My suggestion meets these guidelines:

* [v] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [v] This wouldn't change the runtime behavior of existing JavaScript code
* [v] This could be implemented without emitting different JS based on the types of the expressions
* [v] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [v] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by TacB0sS** [comment]
You can also see that my scriptology workaround on branch dev/frontend is working..

**Comment by MartinJohns** [comment]
That seems to be an issue with your additional tooling (webpack), not with TypeScript.

**Comment by TacB0sS** [comment]
if I run tsc... does it use webpack configuration as well?

**Comment by RyanCavanaugh** [comment]
We'll need some concise explanation of what's going on here in order to treat this as a bug; we are not staffed to investigate build failures that may be due to configuration error on the user's part.

**Comment by TacB0sS** [comment]
Copied from [SO](https://stackoverflow.com/questions/55307783/create-a-typescript-react-common-library):

I try to create a common React and Typescript common library, and I run into too many difficulties in configuring the project workspace in order to develop both library and app altogether

```
project
├─ app
│  ├─ package.json
│  ├─ tsconfig.json
│  ├─ webpack.config.js
│  ├─ ... (other config files)
│  ├─ node_modules
│  │  ├─ ...
│  │  ├─ @types
│  │  │  ├─ ...
│  │  │  └─ react
│  │  └─ symlink(lib A)
│  └─ src
│     ├─ *.ts files
│     ├─ *.tsx files
│     └─ index.ts
│
└─ libA
   ├─ package.json
   ├─ tsconfig.json
   ├─ other config files
   ├─ node_modules
   │  ├─ ...
   │  └─ @types
   │     ├─ ...
   │     └─ react
   └─ src
      ├─ *.ts files
      ├─ *.tsx files
      └─ index.ts
```

* If the sources from **libA** are in the **app** everything compiles builds and run as expected.

* Under this configuration **libA** is build(tsc) successfully. 

* Under this configuration **app** does not compile with the following:

```
../libA/node_modules/@types/react/index.d.ts:2963:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'view' must be of type 'SVGProps<SVGViewElement>', but here has type 'SVGProps<SVGViewElement>'.
```

some Googling suggested that I should delete the react types from the node_modules in **libA**, but that would break the convenience of the development process as **libA** will not compile.

-----

More details:

```
I develop on Mac.
npm: 6.4.1
node: 8.15.0
typescript: 3.3.3333
webpack: 4
```

tsconfig libA:

```json
{
  "compilerOptions": {
    "strict": true,
    "noUnusedLocals": true,
    "declaration": true,
    "sourceMap": true,
    "target": "es5",
    "module": "commonjs",
    "outDir": "dist",
    "moduleResolution": "node",
    "jsx": "react",
    "experimentalDecorators": true,
    "baseUrl": "src"
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

tsconfig app:

```
{
  "compilerOptions": {
    "strict": true,
    "noUnusedLocals": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es5",
    "module": "commonjs",
    "outDir": "dist",
    "moduleResolution": "node",
    "jsx": "react",
    "lib": [
      "es5",
      "es6",
      "es7",
      "dom"
    ],
    "baseUrl": "src"
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

I do **not** want to use the **skipLibCheck**, cause the types are the reason I fell in love with typescript in the first place...

It is safe to assume I am doing something completely wrong.. cause I am at it for almost a week on and off and cannot figure the correct configuration.. any guidance is welcome... 


-----

After further investigation I found out that the only thing that made a difference is whether or not I used a symlink to **libA** by using npm link to it

**Comment by TacB0sS** [comment]
sorry for bothering you guys.. but for now this seems to have magically resolve itself after a few iterations... I'll reopen if I learn more!
