### ISSUE TITLE
Suggestion: Display a honest message when inference cannot be done correctly

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#3055]
Currently (TS v.1.5.2) the compiler does not do inference correctly for certain cases:

https://github.com/Microsoft/TypeScript/issues/3038

Although it is by design, reflected in the spec and there is no viable way for doing it correctly, I think the compiler has to be honest to the developer and instead of generating faulty code, it has to break with an error message that would say that the inferred types cannot be resolved.

**Comment by RyanCavanaugh** [comment]
This would be throwing a lot of babies out with very little bathwater. There is tons of code that hits that part of the spec where the types *are* correct and it would be counterproductive to issue an error in those cases.

**Comment by aleksey-bykov** [comment]
For those parts that are correct no issues is necessary, for other parts that cannot be resolved properly such issue would be very much appreciated. Is there a problem with detecting what can and what cannot be inferred ahead, so that both correct cases with generated code and incorrect ones with error messages are properly covered?

**Comment by RyanCavanaugh** [comment]
The entire problem is that we don't have an algorithm for determining what's an error and what isn't.

We didn't have that capability and then randomly decide to not issue errors in some cases, of course.

**Comment by aleksey-bykov** [comment]
So we might want to keep this issue open please, don't we? It is certainly a problem that the compiler doesn't work property and this problems deserves some attention from the community. There are a lot of open requests that ask for much sillier features than this one and yet that don't get closed.

**Comment by JsonFreeman** [comment]
This is a duplicate of #3038.
