### ISSUE TITLE
Breaking Change in 3.4: Corrected inference priority of contravariant positions under all compiler settings

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#30554]
Consider the following code:
```ts
type HasX = { x: number };
type HasY = { y: number };

declare const source: HasX | HasY;
declare const properties: SomeKey<HasX>;

interface SomeKey<T> {
    key: keyof T;
    blah: Record
}
function read1<T>(source: T, prop: SomeKey<T>) {
    console.log(source[prop.key])
}
// This call should be rejected, because we might
// incorrectly be reading 'x' from 'HasY'
read1(source, properties);

// Same as read1, but inlines 'SomeKey' in second parameter
function read2<T>(source: T, prop: keyof T) {
    console.log(source[prop])
}

// This call *is* correctly rejected
read2(source, properties.key);
```

When TypeScript infers a generic type parameter, as happens twice in this example, it first collects a set of candidates. These candidates can either produced from *covariant* or *contravariant* positions; you can effectively think of these as *read* and *write* positions, respectively. TypeScript then chooses the best candidate according to both the relationship amongst the candidates and their position (co- or contraviant).

In TypeScript 3.3 with `--strictFunctionTypes` off, generic types declared with `interface` were assumed to always be covariant with respect to their type parameter. For function types in programs with `--strictFunctionTypes` disabled, this behavior is generally not observable. However, for generic types declared with `interface` which only used their type parameter in `keyof` positions (a contravariant use), these types behaved incorrectly, and also behaved inconsistently with their "inline expansion".

In TypeScript 3.4, variance of types declared with `interface` is now correctly measured in all cases.

This causes an observable breaking change for interfaces that used a type parameter only in `keyof` (including places like `Record<K, T>` which is an alias for a type involving `keyof K`). The example above is one such possible break.

**Comment by RyanCavanaugh** [comment]
Removing array from the equation:
```ts
interface MetaData<T> {
    key: keyof T;
    // co: () => T;
    // contra: (x: T) => void;
    // inv: (x: T) => T;
    // prop: T;
}

type Box<T> = {
    content: T;
};

declare function _assignProperties<T>(source: T, properties: Box<MetaData<T>>): void;

declare const source: string | number;
declare const properties: Box<MetaData<string>>;
_assignProperties(source, properties);
```

**Comment by RyanCavanaugh** [comment]
Object types:
```ts
interface MetaData<T> {
    key: keyof T;
}

type Box<T> = {
    content: T;
};

declare function _assignProperties<T>(source: T, properties: Box<MetaData<T>>): void;

type Point1 = { x: number };
type Point2 = { y: number };

declare const source: Point1 | Point2;
declare const properties: Box<MetaData<Point1>>;
_assignProperties(source, properties);
```

**Comment by RyanCavanaugh** [comment]
```ts
interface MetaData<T> {
    key: keyof T;
}

declare function f<T>(source: T, properties: MetaData<T>): void;

type Point1 = { x: number };
type Point2 = { y: number };

declare const source: Point1 | Point2;
declare const properties: MetaData<Point1>;
f(source, properties);

```

**Comment by RyanCavanaugh** [comment]
This is due to correctly using the variance of `MetaData<T>` when determining inference candidate priority

**Comment by aleksey-bykov** [comment]
after updating TS to the most recent, this has bitten us already, not too bad though, like 10 places in a 4000 files codebase:
```ts
interface StringX { (value: string | number | boolean): string; }
declare const StringX: StringX;
declare function fn<T, U>(
    value: T,
    instead: (value: T) => U,
    nameOf: (value: T) => string,
): U;
const x: string = fn(0, bounce, StringX); // 'string | number | boolean' is not assignable to type 'string'
```

**Comment by RyanCavanaugh** [comment]
@aleksey-bykov Is that a correct error? I'm curious what the semantics of `fn` are

**Comment by aleksey-bykov** [comment]
not sure how to answer it, here some real code: (`toSelectItemInstead` is `fn`)
```
export interface SelectItem<Kind> {
    kind: Kind;
    name: string;
    isUtility: false;
    className: string | undefined;
    canBeSelected: boolean;
}
export function toSelectItemInstead<T, U>(
    value: T,
    instead: (value: T) => U,
    nameOf: (value: T) => string,
): SelectItem<U> {
    return {
        kind: instead(value),
        name: nameOf(value),
        className: undefined,
        canBeSelected: true,
        isUtility: false,
    };
}
const xxx: SelectItem<number> = [1, 2, 3].map(index => toSelectItemInstead(index, bounce, String));
/*
Type 'SelectItem<string | number | boolean>[]' is not assignable to type 'SelectItem<number>[]'.
  Type 'SelectItem<string | number | boolean>' is not assignable to type 'SelectItem<number>'.
    Type 'string | number | boolean' is not assignable to type 'number'.
      Type 'string' is not assignable to type 'number'.ts(2322)
*/
```

**Comment by RyanCavanaugh** [comment]
Initial write-up updated (it was rather inaccurate due to a misunderstanding of the original behavior)
