### ISSUE TITLE
Object union with optional property

### ISSUE THREAD

**Issue by Reeywhaar** [Microsoft/TypeScript#30563]
**TypeScript Version:**  3.3.4000-dev.201xxxxx

**Search Terms:**
Object union, intersection, matching, type narrowing

**Code**
[Playground link](https://www.typescriptlang.org/play/#src=type%20Pr%20%3D%20%7B%20type%3A%20%22a%22%20%7D%20%7C%20%7B%20type%3A%20%22b%22%20%7D%20%7C%20%7B%20type%3A%20%22c%22%2C%20optional%3A%20string%20%7D%3B%0D%0A%0D%0A%2F*%20just%20test%20function%2C%20content%20is%20irrelevant%20*%2F%0D%0Afunction%20act(p%3A%20Pr)%20%7B%0D%0A%20%20if%20(p.type%20%3D%3D%3D%20%22c%22)%20%7B%0D%0A%20%20%20%20console.log(p.optional)%3B%0D%0A%20%20%7D%0D%0A%20%20console.log(p.type)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20t%3A%20%22a%22%20%7C%20%22b%22%20%3D%20%22a%22%20as%20any%3B%0D%0A%0D%0Aact(%7B%20type%3A%20%22a%22%20%7D)%20%2F%2F%20works%20fine%0D%0Aact(%7B%20type%3A%20t%20%7D)%20%2F%2F%20errors)
```ts
type Pr = { type: "a" } | { type: "b" } | { type: "c", optional: string };

/* just test function, content is irrelevant */
function act(p: Pr) {
  if (p.type === "c") {
    console.log(p.optional);
  }
  console.log(p.type);
}

const t: "a" | "b" = "a" as any;

act({ type: "a" }) // works fine
act({ type: t }) // errors
```

**Expected behavior:**
There must be no error, as type of `t` is well defined and can be analyzed statically.
Even if error legit, error message is rather confusing.

**Actual behavior:**
Error raises:
```
Argument of type '{ type: "a" | "b"; }' is not assignable to parameter of type 'Pr'.
  Property 'optional' is missing in type '{ type: "a" | "b"; }' but required in type '{ type: "c"; optional: string; }'.
```

**Playground Link:** [Playground link](https://www.typescriptlang.org/play/#src=type%20Pr%20%3D%20%7B%20type%3A%20%22a%22%20%7D%20%7C%20%7B%20type%3A%20%22b%22%20%7D%20%7C%20%7B%20type%3A%20%22c%22%2C%20optional%3A%20string%20%7D%3B%0D%0A%0D%0A%2F*%20just%20test%20function%2C%20content%20is%20irrelevant%20*%2F%0D%0Afunction%20act(p%3A%20Pr)%20%7B%0D%0A%20%20if%20(p.type%20%3D%3D%3D%20%22c%22)%20%7B%0D%0A%20%20%20%20console.log(p.optional)%3B%0D%0A%20%20%7D%0D%0A%20%20console.log(p.type)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20t%3A%20%22a%22%20%7C%20%22b%22%20%3D%20%22a%22%20as%20any%3B%0D%0A%0D%0Aact(%7B%20type%3A%20%22a%22%20%7D)%20%2F%2F%20works%20fine%0D%0Aact(%7B%20type%3A%20t%20%7D)%20%2F%2F%20errors)

**Related Issues:** #21599

Sorry if it's duplicate, tried to find similar, but issue is hard to describe. Thank you!

**Comment by jack-williams** [comment]
Duplicate of #8289

**Comment by Reeywhaar** [comment]
@jack-williams thank you, I think now I understand that this is too much for type checker :-)
