### ISSUE TITLE
Type guard inference of object's properties is lost in nested scopes

### ISSUE THREAD

**Issue by quassnoi** [Microsoft/TypeScript#30576]
**TypeScript Version:**  3.4.0-dev.201xxxxx

```
$ node_modules/.bin/tsc --version
Version 3.4.0-dev.20190323
```

**Search Terms:**

type inference scope object property

**Code**

```ts
interface Complex {
    typed: string | number;
}

const lambda = (complex: Complex) => {
    if (typeof complex.typed === "string") {
        const { typed } = complex;

        const str: string = typed;
        const str2: string = complex.typed;
        const handler = () => {
            const str: string = typed;
            const str2: string = complex.typed;
            // Expected: complex.typed to be string
            // Observing: complex.typed is string | number
        }
    }
}
```

**Expected behavior:**

Inferred type of `complex.typed` is preserved in nested scope

**Actual behavior:**

Inferred type of `complex.typed` is lost in nested scope

**Playground Link:** 

https://www.typescriptlang.org/play/#src=interface%20Complex%20%7B%0D%0A%20%20%20%20typed%3A%20string%20%7C%20number%3B%0D%0A%7D%0D%0A%0D%0Aconst%20lambda%20%3D%20(complex%3A%20Complex)%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(typeof%20complex.typed%20%3D%3D%3D%20%22string%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20%7B%20typed%20%7D%20%3D%20complex%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20const%20str%3A%20string%20%3D%20typed%3B%0D%0A%20%20%20%20%20%20%20%20const%20str2%3A%20string%20%3D%20complex.typed%3B%0D%0A%20%20%20%20%20%20%20%20const%20handler%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20str%3A%20string%20%3D%20typed%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20str2%3A%20string%20%3D%20complex.typed%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Expected%3A%20complex.typed%20to%20be%20string%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Observing%3A%20complex.typed%20is%20string%20%7C%20number%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/10065

The bug above, however, deals with passing the objects with inferred properties' types as arguments, while this one passes them through scope, which is arguably more simple to track.

**Comment by AlCalzone** [comment]
TS doesn't know when the handler will be called. `typed` is a const, but `complex.typed` can be modified.
```ts
interface Complex {
    typed: string | number;
}

const lambda = (complex: Complex) => {
    if (typeof complex.typed === "string") {
        const { typed } = complex;

        const str: string = typed;
        const str2: string = complex.typed;
        const handler = () => {
            const str: string = typed;
            const str2: string = complex.typed; // complex.typed might actually be a number here!
        }
        setTimeout(handler, 100);
        complex.typed = 1; // This changes the type of `complex.typed` before the handler is invoked
    }
}
```

**Comment by quassnoi** [comment]
> TS doesn't know when the handler will be called. `typed` is a const, but `complex.typed` can be modified.

Changing `complex` to `const` (or `typed` to `let`) does not change anything.

**Comment by quassnoi** [comment]
You're right!

**Comment by quassnoi** [comment]
Upon further reflection, shouldn't marking `typed` as `readonly` preserve its inferred type?

```ts
interface Complex {
    readonly typed: string | number;
}

const lambda = (complex: Complex) => {
    if (typeof complex.typed === "string") {
        const { typed } = complex;

        const str: string = typed;
        const str2: string = complex.typed;
        const handler = () => {
            const str: string = typed;
            const str2: string = complex.typed; // complex.typed might actually be a number here!
        }
        setTimeout(handler, 100);
        complex.typed = 1;
        // This changes the type of `complex.typed` before the handler is invoked...
        // but you can't do this anymore!  
    }
}
```

**Comment by AlCalzone** [comment]
No, because `complex` can still be reassigned:
```ts
interface Complex {
    readonly typed: string | number;
}

const lambda = (complex: Complex) => {
    if (typeof complex.typed === "string") {
        const { typed } = complex;

        const str: string = typed;
        const str2: string = complex.typed;
        const handler = () => {
            const str: string = typed;
            const str2: string = complex.typed; // complex.typed might actually be a number here!
        }
        setTimeout(handler, 100);
        complex = {typed: 1}; // This changes the type of `complex.typed` before the handler is invoked
    }
}
```

**Comment by quassnoi** [comment]
And what if it can't?

```ts
interface Complex {
    readonly typed: string | number;
}

const complex = { typed: "string" } as Complex;

if (typeof complex.typed === "string") {
    const { typed } = complex;

    const str: string = typed;
    const str2: string = complex.typed;

    const handler = () => {
        const str: string = typed;
        const str2: string = complex.typed;
    }
}
```

**Comment by RyanCavanaugh** [comment]
`readonly` is not the same as `const` - you might have a `readonly` view of an underlying mutable object, for example.

**Comment by smartinio** [comment]
How about this example with constants? Why can't TS figure out that c is A in the first function, but it can in the second one?

```typescript
const A = { nested: { prop: 'A' }, foo: 'foo' } as const;
const B = { nested: { prop: 'B' }, bar: 'bar' } as const;

function thisFails(c: typeof A | typeof B) {
  if (c.nested.prop === 'A') {
    const foo: 'foo' = c.foo // error: foo does not exist in A | B
  } else {
    const bar: 'bar' = c.bar // error: bar does not exist in A | B
  }
}

function thisWorks(c: typeof A | typeof B) {
  if ('foo' in c) {
    const A: 'A' = c.nested.prop
  } else {
    const B: 'B' = c.nested.prop
  }
}
```
