### ISSUE TITLE
Param decorator in constructor assignment

### ISSUE THREAD

**Issue by bios21** [Microsoft/TypeScript#30573]
**TypeScript Version:**  3.4.0-dev.20190323

**Search Terms:**
- decorator
- constructor decorator
- param constructor decorator
- decorator constructor assignment

**Code**

```ts
function Deco(...args: any[]) {}

class C1 {
    constructor(@Deco public foo) {}
}
```

generates: 
```js
function Deco(...args) { }

let C1 = class C1 {
    constructor(foo) {
        this.foo = foo;
    }
};
C1 = __decorate([
    __param(0, Deco)
], C1);
```

**Expected behavior:**
Should be the same as:
```ts
class C2 {
    @Deco
    public foo;
    constructor(@Deco foo) {
        this.foo = foo;
    }
}
```

with this generated JS:
```js
let C2 = class C2 {
    constructor(foo) {
        this.foo = foo;
    }
};
__decorate([
    Deco
], C2.prototype, "foo", void 0);
C2 = __decorate([
    __param(0, Deco)
], C2);
```

**Actual behavior:**
As it is for now, `__decorate` helper is only generated for the param decorator instead of both member AND param (in that order)

**Potential caveat:**
This maybe *is not* a bug since we end up dealing with two-usages decorator for both member and param.  
So maybe this was intended to give priority to param decorator over member.

**Playground Link:** 
Basic example: https://typescript-play.js.org/?experimentalDecorators=true&target=5#code/GYVwdgxgLglg9mABAEQKYTgCgHS4IYBOA5gM4BcieYAngNoC6AlIgN4C+AUBwPTeIC0grhAA2eEiUQBhAIysOiRYgxgSUAiGhwCmAAJoMiAA4gARiJgREwOHApVqzdh048+g-sLETpAJnmK+uhwCsZmFlY2dpQ0ANxciipqGlo6QYZR9jROoYpQABYwJNhRiAC81rbxipyuXPUNjQ1AA

Complex example: https://typescript-play.js.org/?experimentalDecorators=true&target=5#code/GYVwdgxgLglg9mABAEQKYTgCmAJzgWwC5EBnKHGMAcwEpEBvAKEUR1ShByVElgUUoATdFgB04gIY4qJYhLABPANoBdGnMUNmLHRjAk4AG1SjDcKtjz4ANInGipMmgG5tAX0YfGEQxJIlEAGVUHAA3GAhULR0dAAE0DEwAcnxUfAAjEKSabRYABwpQiSgoyhgSwUQAXkRgCUMSVFcYgpgiktIoYojEAEkAOUCAFQBBfoBhAFFiYLCIptzEVvaovTIcEGg4HExFlniRZLypCVTspcLiqOA4OGJ1yiprPcQDxKTjnFPUc4K4EugqEq6SkxGQV2eMX2CSwHxO+EQPj8JAi5wkAC9UPdyI9IVC3rDPt9fiB0oYeiD0cR0rdjPJqohyCBUHi6EwYlAABYwEiiMpQTAuRZrIwmMwWJLjADygyGACUAKrjIbZdyMbTLK4CMDlQXRHQwYCITBcnl8nUVNkvNgcLjNHQeDnc3n8oEMpkLFhefKk8kQTrdf1UdjasjySKCmYhcKRfUsG2cJAm52iAbDMZTd0ptOjCaTF4AfkZ2dlGfzUMQxDAqAA7sWeZgAESc1CGMyN2zVuvgkqYHsmMBwGuCmi2JIKODZIVe9UxAnJVJcuCCVU+sk9YNQRkwVJ69lQhNceu8kE4e0eLwi4ymcyYWYxkyUMOQEywVJC9Wfr-fn+MIA

**Related Issues:**

**Comment by AlCalzone** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/10777 I think

**Comment by bios21** [comment]
Yep, totally. Didn't look up for the "shortand" search term. My bad. Closing this in favor of #10777.
