### ISSUE TITLE
make code commenting smarter

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#30578]
1. select some text in the middle of your line of code
![image](https://user-images.githubusercontent.com/937933/54922492-a89bcd80-4ede-11e9-92d9-9d56a9dca885.png)
2. hit `Ctrl + K`, `Ctrl + C`
3. observe the entire line commented out
![image](https://user-images.githubusercontent.com/937933/54922512-b7828000-4ede-11e9-97db-b7d70506a365.png)
4. should be: only the selected part should be commented out
![image](https://user-images.githubusercontent.com/937933/54922556-cec16d80-4ede-11e9-94bb-f6dc879dcb59.png)

**Comment by DanielRosenwasser** [comment]
I think this is a VS Code issue, right @mjbvz?

**Comment by mjbvz** [comment]
That is the `line comment` command. Use the `block comment` command if you want to comment the selected text

**Comment by aleksey-bykov** [comment]
it's not exactly the same, i wish we could reopen it

i do not want to pick between block comments and line comments i wish vs was smart enough to choose between the two

please reopen

**Comment by RyanCavanaugh** [comment]
@aleksey-bykov you're just asking to break other users' muscle memories. Rebind your keys if you want `Ctrl-K Ctrl-C` to comment the selection.

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh Maybe? If I have something selected, it seems weird that I'd ever want a line-comment.

@aleksey-bykov I'd encourage you to file a separate issue on VS Code (since I don't have rights to transfer this over).

**Comment by aleksey-bykov** [comment]
@mjbvz can "where" property of a keybinding definition sense text being selected? if so, then i will make just 2 bindings to Ctrl + K, Ctr + W with block and line commands respectively

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh it's not about certain bindings, it's about picking either one of ways hitting the same keychord

**Comment by RyanCavanaugh** [comment]
I agree an "auto" comment feature makes sense, it's just not what "Comment Line" means

**Comment by aleksey-bykov** [comment]
sorry, for the sake of historical correctness, it was never about "comment lines"
