### ISSUE TITLE
Have instances of a generic function

### ISSUE THREAD

**Issue by f3c0** [Microsoft/TypeScript#3057]
Can I have an instance of a generic function?

For example I have a function like this:
```javascript
function pushType<T>(item: T, list: T[]): T[]{
    list.push(item);
    return list;
}
```

If I would like to use with number parameter in multiple places, I have to do this:
```javascript
pushType<number>(12, [3, 4, 5]);
pushType<number>(1, [4, 5]);
```
Can I have an instance of this function for numbers instead of?
Something like this:
```javascript
var pushNumber = pushType<number>; // this is syntax error now
pushNumber(12, [3, 4, 5]);
pushNumber(1, [4, 5]);
```

`var pushNumber = pushType<number>;` is now synax error and compiles to `var pushNumber = pushType();`
It would be nice I guess to compile it to `var pushNumber = pushType;`

**Comment by CyrusNajmabadi** [comment]
You can just do:

```ts
var pushNumber: (i: number, list: number[]) => number[] = pushType;
```

**Comment by danquirk** [comment]
Note there's no need to explicitly specify the generic type argument here.

```ts
function pushType<T>(item: T, list: T[]): T[]{
    list.push(item);
    return list;
}

pushType(12, [3, 4, 5]); // ok
pushType(1, [4, 5]); // ok
pushType(1, ['']); // error
```

**Comment by f3c0** [comment]
Thanks danquirk. No need to explicit specify in that case, I agree.
However if I have the `var pushNumber = pushType<number>;` than a `pushNumber('1', ['2']);` is an error while the `pushType('1', ['2']);` is fine, so it's like a restricted version of a generic function.

CyrusNajmabadi's comment looks a solution for now, thanks. But I feel my my suggesion more elegant. Do you think is it against any language design or can it be a valid suggestion to implement later?

**Comment by danquirk** [comment]
You might also be interested in https://github.com/Microsoft/TypeScript/issues/1616 

The problem right now is that the system is not designed in such a way that you can instantiate a generic with a particular type and then 'finish' using it later (ie provide arguments). Certainly people are accustomed to doing something like what you are proposing in certain other languages with different implementations of generics. Given that there are a couple good workarounds (Cyrus' as well as defining a separate function constrained specifically to number which then forwards the call to a more generic version) we would likely need some more compelling use cases to consider complicating the type system like this.
