### ISSUE TITLE
TS4078 brings for destructured varaible, but not for just variable

### ISSUE THREAD

**Issue by timocov** [microsoft/TypeScript#30598]
**TypeScript Version:**  typescript@3.4.0-dev.20190326

**Search Terms:** "declaration emit", "has or is using private name"

**Code**

```ts
const a = 123;
const { b } = { b: 123 };

export function foo(
    d: typeof a, // no error
    e: typeof b // error TS4078: Parameter 'e' of exported function has or is using private name 'b'.
): void {}
```

`./node_modules/.bin/tsc --declaration true`

**Expected behavior:**

Error for both `d` and `e` args.

**Actual behavior:**

Error for `e` arg only.

**Related Issues:** #23127, #22798, #20080, #5284

If I comment `e: typeof b` and `const { b } = { b: 123 }` then this may produce runtime error as soon all members from declaration file can be imported (but there is no export with name `a`), but it looks like `export {};` statement does something that disabled it, right? Could you please point what does it mean for TypeScript (link or description)? (I found only [one mention](https://github.com/Microsoft/TypeScript-Handbook/blob/524ed56fe88045a0234e84dc6838b9c5e202d4c5/pages/declaration%20files/templates/global-modifying-module.d.ts.md) in handbook, but it says about "exports nothing" only). When I should use it when write declaration by myself?

**Comment by a-tarasyuk** [comment]
```ts
// @declaration: true

const a = 1;
const { b } = { b: 1 };
interface c {}
function d(): string | number { return 1 };
class e {}

export function foo(
    a1: typeof a,  // ok
    a2: typeof b,  // error
    a3: c,         // ok 
    a4: typeof d,  // ok
    a5: e          // ok
): void {}
```

@RyanCavanaugh What the right behavior for this kind of error? Should all parameters throw the error `TS4078`?  Or `a2` shouldn't have the error `TS4078`?

cc @DanielRosenwasser
