### ISSUE TITLE
Strick Null Checker Loophole

### ISSUE THREAD

**Issue by airportyh** [Microsoft/TypeScript#30597]
```ts
type Getter<S, D> = (source: S) => D;

interface IPerson {
    name: string;
    spouse?: IPerson;
}

const klara: IPerson = {
    name: "Klara"
};

const paul: IPerson = {
    name: "Paul",
    spouse: klara
};

const spouseGetter: Getter<IPerson, IPerson | undefined> = (person) => person.spouse;
const nameGetter: Getter<IPerson, string> = (person) => person.name;

function chain<T1, T2, T3>(getter1: Getter<T1, T2>, getter2: Getter<T2, T3>): Getter<T1, T3> {
    return (source) => getter2(getter1(source));
}

const spouseNameGetter = chain(spouseGetter, nameGetter);
const paulSpouseName = spouseNameGetter(paul);
const klaraSpouseName = spouseNameGetter(klara);
```

Test it:

```
npx tsc getter.ts  --strictNullChecks
```

**Expected behavior:**

The definition of the `chain` function specifies as a constraint that the output type of getter1 (`D`) should be the same as the input type of getter2 (`S`) - both of which are named as `T2`. In this case, since the output type of `spouseGetter` could potentially be `undefined` (`IPerson | undefined`), and the input type of `nameGetter` is never undefined (`IPerson`), I expect the line `chain(spouseGetter, nameGetter)` to fail at compile time.

**Actual behavior:**

TypeScript seems to infer the type of `T2` to be the union of the 2 types, thus: `IPerson | undefined` rather than strictly forcing them to be the same:

<img width="1093" alt="Screen Shot 2019-03-26 at 11 27 37 AM" src="https://user-images.githubusercontent.com/54303/55010223-38fb1080-4fba-11e9-8404-b9792136b10f.png">

The program compiles successfully, but when run, it fails at runtime with: 

```
var nameGetter = function (person) { return person.name; };
                                                   ^

TypeError: Cannot read property 'name' of undefined
```

**Playground Link:** 

<https://www.typescriptlang.org/play/#src=type%20Getter%3CS%2C%20D%3E%20%3D%20(source%3A%20S)%20%3D%3E%20D%3B%0D%0A%0D%0Ainterface%20IPerson%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20spouse%3F%3A%20IPerson%3B%0D%0A%7D%0D%0A%0D%0Aconst%20klara%3A%20IPerson%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20%22Klara%22%0D%0A%7D%3B%0D%0A%0D%0Aconst%20paul%3A%20IPerson%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20%22Paul%22%2C%0D%0A%20%20%20%20spouse%3A%20klara%0D%0A%7D%3B%0D%0A%0D%0Aconst%20spouseGetter%3A%20Getter%3CIPerson%2C%20IPerson%20%7C%20undefined%3E%20%3D%20(person)%20%3D%3E%20person.spouse%3B%0D%0Aconst%20nameGetter%3A%20Getter%3CIPerson%2C%20string%3E%20%3D%20(person)%20%3D%3E%20person.name%3B%0D%0A%0D%0Afunction%20chain%3CT1%2C%20T2%2C%20T3%3E(getter1%3A%20Getter%3CT1%2C%20T2%3E%2C%20getter2%3A%20Getter%3CT2%2C%20T3%3E)%3A%20Getter%3CT1%2C%20T3%3E%20%7B%0D%0A%20%20%20%20return%20(source)%20%3D%3E%20getter2(getter1(source))%3B%0D%0A%7D%0D%0A%0D%0Aconst%20spouseNameGetter%20%3D%20chain(spouseGetter%2C%20nameGetter)%3B%0D%0Aconst%20paulSpouseName%20%3D%20spouseNameGetter(paul)%3B%0D%0Aconst%20klaraSpouseName%20%3D%20spouseNameGetter(klara)%3B%0D%0A>

**Comment by nmain** [comment]
This is correctly flagged when you also enable `strictFunctionTypes`.

**Comment by airportyh** [comment]
> This is correctly flagged when you also enable `strictFunctionTypes`.

Wow! I had no idea. Thank you for this info. I will use `--strict` from now on which includes all the strict options. I played around more and found a narrower problem which I will document here: https://github.com/Microsoft/TypeScript/issues/30600. But now I have workaround.

**Comment by DanielRosenwasser** [comment]
Yup, use full `--strict` mode and you'll get more desirable results. Otherwise we always compare function parameters bivariantly.
