### ISSUE TITLE
allow type morphing

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#30601]
considering a certain (better constrained generic) type in current TS, there is no easy way to:

- add/replace/remove a property
- add/replace/remove a parameter

it makes it extremely hard to get the resulting types out of builders

```ts
// what is the type of result?
const result = building<A>().addProp<string>('x').replaceProp<number>('y').removeProp('z');
```

sure you can do:
```ts
type Result = typeof result;
```

but only if there are **no functions** and **no generics involved**

```ts
function make<X, Y>() {
     const result = building<A>().addProp<X>('x').replaceProp<Y>('y').removeProp('z');
     return result;
}
type Result<X, Y> = typeof make<X, Y>; // <-- dang! now what?
```

without types you **cannot pass stuff around**, so the results of the builders are **not transferable**, so it limits the composability of the code and overall design of the application

it's a super major headache with higher order components in React:

-  they are easy to build, but very hard to type

**so i wish there was something as convenient as builders, but for the _type domain_**

please consider these use cases:

```ts
interface A {
    x: number;
    y: { z: string; };
}
type B = /* some magic here */ A;
```
-------------------
1. type `B` same as `A` but without property `y`
```ts
type B = { x: number; };
```
current answer: 
```ts
type B = Omit<A, 'y'>;
```
-------------------
2. type `B` same as `A` but with property `x` of type `string`
```ts
type B = { x: string; y: string; };
```
current answer: 
```ts
type B = Omit<A, 'x'> | { x: string };
```
-------------------
3. type `B` same as `A` but with property `y.z` removed:
```ts
type B = { x: string; y: {}; };
```
current answer: 
```ts
type B = Omit<A, 'y'> & { y: Omit<A['y'], 'z'> };
```
-------------------
4. type `B` same as `A` but with property `y.z` of type `boolean`
```ts
type B = { x: string; y: { z: boolean; }; };
```
current answer
```ts
type B = Omit<A, 'y'> & { y: Omit<A['y'], 'z'> & { z: boolean; }; };
```
-------------------
... see where i am going?

now...
```ts
interface A {
    m(x: string, y: number): void;
}
type B = /* some magic here */ A;
```
-------------------
5. type `B` same as `A` but with first parameter removed
```ts
type B = { m(y: number): void; };
```
current answer
```
// NOT SURE IF IT IS DOABLE, SOME VERY UGLY CODE
```
-------------------
6. type `B` same as `A` but with first parameter of type `boolean`
```ts
type B = { m(x: boolean, y: number): void; };
```
current answer
```
// SOME VERY UGLY CODE
```
-------------------
7. type `B` same as `A` but with with extra parameter of type `boolean`
```ts
type B = { m(x: string, y: number, z: boolean): void; };
```
current answer
```
// NOT SURE IF IT IS DOABLE, IF IT IS IT WILL BE VERY UGLY
```

-------------------
7. type `B` same as `A` but with with extra parameter of type `boolean` after 1st one
```ts
type B = { m(x: string, z: boolean, y: number): void; };
```
current answer
```
// NOT SURE IF IT IS DOABLE, IF IT IS IT WILL BE VERY UGLY
```
-------------------
...etc

**Comment by RyanCavanaugh** [comment]
For properties
```ts
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>;
type Change<T, K, P> = { [S in keyof T]: S extends K ? P : T[S] };

interface A {
    x: number;
    y: { z: string; };
}
type B1 = Omit<A, "y">;
const b1: B1 = { x: 10 };

type B2 = Change<A, "y", string>;
const b2: B2 = { x: 10, y: "" };

type B3 = Change<A, "y", Omit<A["y"], "z">>;
const b3 = { x: "", y: {} };

type B4 = Change<A, "y", Change<A["y"], "z", boolean>>;
const b4 = { x: "", y: { z: true } };
```

Parameters work roughly the same but with tuples

**Comment by aleksey-bykov** [comment]
ok, i need to add `w: string, v: boolean` inside `x.y.z`

**Comment by RyanCavanaugh** [comment]
I'm not sure what you're proposing, then. The primitives are there, and any highly complex operation expressed in terms of smaller primitives is going to look kind of ugly regardless of what order the operands go in. What kind of sugar would be understandable and also meaningfully better?

**Comment by aleksey-bykov** [comment]
i am not sure, but

1. being able to get a type of a generic function result: `type Result<X, R> = typeof make<X, Y, Z>;` (`make` is a generic function `function make<X, Y, Z>(...)`)

2. some sort of first class support for this from the language:
```
type B = remove A.x, remove A.y, add 'x': number, change 'z': string
```
3. macros (to generate all this mess of primitive operations behind the scene)

**Comment by krryan** [comment]
I agree with this. Particularly in the deeper cases, it’s pretty painful to omit or replace things.

I’d comment also that `Omit` isn’t very smart. We have at least one place in our code where we have, effectively,

```ts
function foobar<Foo extends { bar: string; }>(
    fooBarless: Omit<Foo, 'bar'>,
    bar: Foo['bar'],
): Foo {
    const foo = { ...fooBarless, bar };
    return foo;
}
```

and of course that doesn’t work. I have no idea if Aleksey’s proposal would allow something about that to be done or if it’s the same problem either way, but it seems like it might be related. I could imagine an interface being unable to make the same guarantees that this would.
