### ISSUE TITLE
Function can return wrong values despite type

### ISSUE THREAD

**Issue by bjornua** [Microsoft/TypeScript#30603]
**TypeScript Version:**  3.4.0-dev.20190326

**Search Terms:** Function Generic Extends Keyof Property

**Code**

```ts
interface Type {
  a: 123;
  b: "some string";
}

function get123<K extends keyof Type>(): Type[K] {
  return 123;
}
```

**Expected behavior:**
The function `get123` would yield an error as the return type might not be correct as it depends on `K`.

**Actual behavior:**
No error for `get123`. That function would obviously always return 123. 

**Playground Link:** [Example on TypeScript Playground](https://www.typescriptlang.org/play/#src=interface%20Type%20%7B%0D%0A%20%20a%3A%20123%3B%0D%0A%20%20b%3A%20%22some%20string%22%3B%0D%0A%7D%0D%0A%0D%0Afunction%20get123%3CK%20extends%20keyof%20Type%3E()%3A%20Type%5BK%5D%20%7B%0D%0A%20%20return%20123%3B%0D%0A%7D%0D%0A)

**Comment by jack-williams** [comment]
I think this is an unsoundness that exists to support index access types on `this`. The assignability rules for `Type[K]` are defined as:
```
// A type S is related to a type T[K], where T and K aren't both type variables, if S is related to C,
// where C is the base constraint of T[K]
```
The base constraint of `Type[K]` is the type you get when indexing into `Type` using the base constraint of `K` which is `"a" | "b"`. So the checker sees that `123` is assignable to `Type[K]` as:
- `123` is assignable to `123 | "some string"`
- and `Type[K] ==> Type["a" | "b"] ==> 123 | "some string"`

The way to prevent the unsoundness would be to write it using two variables, though I'm not sure this actually solves your problem.
```ts
function get123<K extends keyof Type, T extends Type = Type>(): T[K] {
  return 123;
}
```

**Comment by jack-williams** [comment]
See this [comment](https://github.com/Microsoft/TypeScript/issues/27470#issuecomment-426073500) by Anders for (much) more detail.

**Comment by DanielRosenwasser** [comment]
Feels bad - but does that mean we should mark this as a duplicate @ahejlsberg?

**Comment by jack-williams** [comment]
Would it be too much to restrict the unsoundness to cases where the object type is generic, but the key type is concrete? This example would be the converse and use the sound path.

**Comment by ahejlsberg** [comment]
@jack-williams I'll give it a try.
