### ISSUE TITLE
Strick Null Checker Loophole #2

### ISSUE THREAD

**Issue by airportyh** [Microsoft/TypeScript#30600]
```ts
export interface Getter<S, D> {
    get(source: S): D;
}

export interface IPerson {
    name: string;
    spouse?: IPerson;
}

const klara: IPerson = {
    name: "Klara"
};

const paul: IPerson = {
    name: "Paul",
    spouse: klara
};

const spouseGetter: Getter<IPerson, IPerson | undefined> = {
    get: (person) => person.spouse
};
const nameGetter: Getter<IPerson, string> = {
    get: (person) => person.name
}

function chain<T1, T2, T3>(getter1: Getter<T1, T2>, getter2: Getter<T2, T3>): Getter<T1, T3> {
    return {
        get: (source) => getter2.get(getter1.get(source))
    }
}

const spouseNameGetter = chain(spouseGetter, nameGetter);
const paulSpouseName = spouseNameGetter.get(paul);
const klaraSpouseName = spouseNameGetter.get(klara);
```

Test it:

```
npx tsc getter.ts  --strict
```

**Expected behavior:**

The definition of the `chain` function specifies as a constraint that the output type of getter1 (`D`) should be the same as the input type of getter2 (`S`) - both of which are named as `T2`. In this case, since the output type of `spouseGetter` could potentially be `undefined` (`IPerson | undefined`), and the input type of `nameGetter` is never undefined (`IPerson`), I expect the line `chain(spouseGetter, nameGetter)` to fail at compile time.

**Actual behavior:**

TypeScript seems to infer the type of `T2` to be the union of the 2 types, thus: `IPerson | undefined` rather than strictly forcing them to be the same:

The program compiles successfully, but when run, it fails at runtime with: 

```
var nameGetter = function (person) { return person.name; };
                                                   ^

TypeError: Cannot read property 'name' of undefined
```

Note: if we change the definition of `Getter` to an arrow function syntax instead of a method definition syntax:

```ts
interface Getter<S, D> {
    get: (source: S) => D;
}
```

then we get the desired behavior.

**Playground Link:** 

<https://www.typescriptlang.org/play/#src=export%20interface%20Getter%3CS%2C%20D%3E%20%7B%0D%0A%20%20%20%20get(source%3A%20S)%3A%20D%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20IPerson%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20spouse%3F%3A%20IPerson%3B%0D%0A%7D%0D%0A%0D%0Aconst%20klara%3A%20IPerson%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20%22Klara%22%0D%0A%7D%3B%0D%0A%0D%0Aconst%20paul%3A%20IPerson%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20%22Paul%22%2C%0D%0A%20%20%20%20spouse%3A%20klara%0D%0A%7D%3B%0D%0A%0D%0Aconst%20spouseGetter%3A%20Getter%3CIPerson%2C%20IPerson%20%7C%20undefined%3E%20%3D%20%7B%0D%0A%20%20%20%20get%3A%20(person)%20%3D%3E%20person.spouse%0D%0A%7D%3B%0D%0Aconst%20nameGetter%3A%20Getter%3CIPerson%2C%20string%3E%20%3D%20%7B%0D%0A%20%20%20%20get%3A%20(person)%20%3D%3E%20person.name%0D%0A%7D%0D%0A%0D%0Afunction%20chain%3CT1%2C%20T2%2C%20T3%3E(getter1%3A%20Getter%3CT1%2C%20T2%3E%2C%20getter2%3A%20Getter%3CT2%2C%20T3%3E)%3A%20Getter%3CT1%2C%20T3%3E%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20get%3A%20(source)%20%3D%3E%20getter2.get(getter1.get(source))%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20spouseNameGetter%20%3D%20chain(spouseGetter%2C%20nameGetter)%3B%0D%0Aconst%20paulSpouseName%20%3D%20spouseNameGetter.get(paul)%3B%0D%0Aconst%20klaraSpouseName%20%3D%20spouseNameGetter.get(klara)%3B%0D%0A>

**Comment by jack-williams** [comment]
Method signatures are still checked bivariantly, even under `--strict`. You need to write `Getter` like:
```ts
export interface Getter<S, D> {
    get: (source: S) => D;
}
```

**Comment by ahejlsberg** [comment]
@jack-williams beat me to it. But still...

This is by design. Methods are always checked bi-variantly. More details in #18654, in particular:

> The stricter checking applies to all function types, except those originating in method or construcor declarations. Methods are excluded specifically to ensure generic classes and interfaces (such as Array<T>) continue to mostly relate covariantly. The impact of strictly checking methods would be a much bigger breaking change as a large number of generic types would become invariant (even so, we may continue to explore this stricter mode).

**Comment by airportyh** [comment]
Thank you for the info!
