### ISSUE TITLE
emitDecoratorMetadata in Visual Studio

### ISSUE THREAD

**Issue by abakirov** [Microsoft/TypeScript#3061]
In TypeScrip 1.5 beta, is it possible to set `emitDecoratorMetadata` flag in Visual Studio 2013?

I can see the `__metadata` call in the generated JS code when compile from command line but I cannot find corresponding option in VS.

Thanks!

**Comment by danquirk** [comment]
Sounds like you wanted it added to the list here: https://github.com/Microsoft/TypeScript/issues/3034

**Comment by mhegazy** [comment]
tracked by #3034 now.
