### ISSUE TITLE
Paths not resolving

### ISSUE THREAD

**Issue by oleersoy** [Microsoft/TypeScript#30619]
I setup [an MCVE](https://github.com/oleersoy/typescript-paths) and provided a link to it in this [SO post](https://stackoverflow.com/questions/55383929/typescript-paths-not-resolving).  Many of the comments from other SOers were that the original example should work per the typescript specification, but does not.

[Also trying to convert this project to use paths](https://stackoverflow.com/questions/55387238/trouble-converting-project-to-typescript-paths), but it Typescript will not resolve the paths even though I'm following the approach demoed in the first SO answer.

**Comment by RyanCavanaugh** [comment]
Please log an issue that describes the behavior and the problem in the body of the post. We can't find duplicates, re-use this issue to help other people, etc, if it's just a link to some off-site content.
