### ISSUE TITLE
Call signatures on unions with generic constraints

### ISSUE THREAD

**Issue by JanFelixReuter** [Microsoft/TypeScript#30613]
**TypeScript Version:**  3.3.4

**Search Terms:**
union, no compatible call signature, generics, constraints

**Code**

```ts
function test1() {
    interface Temp1 {
        getValue<T extends string>(name: T): number;
    }

    interface Temp2 {
        getValue<T extends string>(name: T): string;
    }

    function test(t: Temp1 | Temp2) {
        const z = t.getValue("foo"); //expect number|string        
    }
}
```

**Expected behavior:**
The call to `getValue` should be allowed and the result should be of type `number|string`

**Actual behavior:**
Compiler error: 
Cannot invoke an expression whose type lacks a call signature. Type '(<T extends string>(name: T) => number) | (<T extends string>(name: T) => string)' has no compatible call signatures.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=function%20test1()%20%7B%0D%0A%20%20%20%20interface%20Temp1%20%7B%0D%0A%20%20%20%20%20%20%20%20getValue%3CT%20extends%20string%3E(name%3A%20T)%3A%20number%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20interface%20Temp2%20%7B%0D%0A%20%20%20%20%20%20%20%20getValue%3CT%20extends%20string%3E(name%3A%20T)%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20function%20test(t%3A%20Temp1%20%7C%20Temp2)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20z%20%3D%20t.getValue(%22foo%22)%3B%20%2F%2Fexpect%20number%7Cstring%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** 
#7294

**Comment by jack-williams** [comment]
Call signatures for generic union types are not currently supported: [comment](https://github.com/Microsoft/TypeScript/issues/7294#issuecomment-465801362).

**Comment by JanFelixReuter** [comment]
@jack-williams Thanks, I missed that comment.
