### ISSUE TITLE
Enum can be assigned out-of-bounds values

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#30629]
**TypeScript Version:**  3.4.0-rc

```
const enum Fonum  {
    a = 1,
    b = 2
}

let value: Fonum = 12; // no error?
let value2: 1 | 2 = 12; // error
```

https://www.typescriptlang.org/play/#src=const%20enum%20Fonum%20%20%7B%0D%0A%20%20%20%20a%20%3D%201%2C%0D%0A%20%20%20%20b%20%3D%202%0D%0A%7D%0D%0A%0D%0Alet%20value%3A%20Fonum%20%3D%2012%3B%20%2F%2F%20no%20error%3F%0D%0A%0D%0Alet%20value2%3A%201%20%7C%202%20%3D%2012%3B%20%2F%2F%20error

**Comment by dragomirtitian** [comment]
I believe this is by design as stated by @DanielRosenwasser in #26362 to allow for bitwise operations on flag enums: 

>The behavior is motivated by bitwise operations. There are times when `SomeFlag.Foo | SomeFlag.Bar` is intended to produce another `SomeFlag`. Instead you end up with number, and you don't want to have to cast back to `SomeFlag`.
I think if we did TypeScript over again and still had enums, we'd have made a separate construct for bit flags.

**Comment by jrieken** [comment]
> bitwise operations on flag enums:

That makes sense but then they should geek out and understand that you cannot produce `12` with `1` and/or `2`

**Comment by dragomirtitian** [comment]
@jrieken Challenge accepted 😄 : 

```ts
let value: Fonum = Fonum.a << Fonum.b << Fonum.a  |  Fonum.a << Fonum.b; // 12
```
I think it is difficult to tell if the resulting number is valid or not if we consider flag enums and the whole range of bitwise operations.

**Comment by jrieken** [comment]
haha - fair point. There should probably be `strict enum` that doesn't allow these things...
