### ISSUE TITLE
configFileDiag response not generated until after config file is saved

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#30623]
From https://github.com/Microsoft/vscode/issues/69880

**TypeScript Version:**  3.4.0-rc

**Search Terms:**
- configFileDiag

**Repo**
1. Create a simple jsconfig project with a `jsconfig.json`:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
    ],
    "files": []
}
```

And a single js file

1. Open the workspace in vscode

**Expected behavior:**
A config file configFileDiag result is generated when the project is first loaded

**Actual behavior:**
No such request is generated until the file is saved

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
That's because for config file change we are watching disk for changes and there is currently no notion of open config file. Probably that's what we would need to be able to detects such changes.

**Comment by mjbvz** [comment]
@sheetalkamat As a first step, could TS Server send us a `configFileDiag` error when it initially reads the `tsconfig` file from the disk?

I've opened #30674 to track synchronizing unsaved config files (mainly for error reporting)

**Comment by sheetalkamat** [comment]
@mjbvz we send the `configFileDiag` whenever file is opened from configured project (where it reads first) is that not what you see?

**Comment by mjbvz** [comment]
In this specific case, since `files` is empty, we never get `configFileDiag` until the `jsconfig` is saved. From the TS server logs, I do see that TS detects the config file:

```
Opened configuration file /Users/matb/projects/san/jsconfig.json
```

But all the js files in the workspace go into an inferred project

**Comment by sheetalkamat** [comment]
Should we send this event only when the file list we find for configured project is empty ?

**Comment by mjbvz** [comment]
That would be a good starting point. There are other config errors that can cause this too, such as using an invalid file in `files` (such as trying to use a glob pattern there)
