### ISSUE TITLE
Default values of object destructuring of Generic type 

### ISSUE THREAD

**Issue by Pomar81** [Microsoft/TypeScript#30628]
Hi, TypeScript Team

**Version: 3.3.4**

I have a problem with default values of destructed variables inside a generic function. If I don't specify type for destructuring construction I could set anything as default values.

```ts
type HeaderTypes = 'h1' | 'h2' | 'h3'

type HeaderProps<H extends HeaderTypes> = {
    abc?: H,
    className?: string,
}

const Header = <H extends HeaderTypes>(props: HeaderProps<H>) => {
    const { abc = 'h1' }: HeaderProps<H> = props;
   // ......
}  
```
**Expected behavior:**
abc can be assigned to 'h1'
**Actual behavior:**
TS2322:Type 'h1' is not assignable to type 'H'

**Playground Link:** [example](https://www.typescriptlang.org/play/index.html#src=type%20HeaderTypes%20%3D%20'h1'%20%7C%20'h2'%20%7C%20'h3'%0A%0Atype%20HeaderProps%3CH%20extends%20HeaderTypes%3E%20%3D%20%7B%0A%20%20%20%20abc%3F%3A%20H%2C%0A%20%20%20%20className%3F%3A%20string%2C%0A%7D%0A%0Aconst%20Header%20%3D%20%3CH%20extends%20HeaderTypes%3E(props%3A%20HeaderProps%3CH%3E)%20%3D%3E%20%7B%0A%20%20%20%20const%20%7B%20abc%20%3D%20'h1'%20%7D%3A%20HeaderProps%3CH%3E%20%3D%20props%3B%0A%20%20%20%2F%2F%20......%0A%7D%20%20)

**Comment by jack-williams** [comment]
Essentially the same problem as: #29528 and #30157

**Comment by Pomar81** [comment]
Hi @jack-williams 
Yes.  #29528 is very close. But is there any solution on how to fix my problem?

**Comment by jack-williams** [comment]
I don't understand your use-case fully but I would write something like:
```ts
const Header = <H extends HeaderTypes>(props: HeaderProps<H>) => {
    const { abc = 'h1' }: HeaderProps<H | "h1"> = props;
   // ......
}  
```

**Comment by Pomar81** [comment]
In my current context, it is ok. Thank you. 
But in general, it will be great to somehow determine that General T is assignable to extends subtype
