### ISSUE TITLE
narrow array type with `.filter(Boolean)`

### ISSUE THREAD

**Issue by mmkal** [Microsoft/TypeScript#30621]
## Search Terms

narrow, array, filter

## Suggestion

add this overload to `Array<T>.filter`:
```typescript
filter(fn: typeof Boolean): Array<Exclude<T, null | undefined | 0 | ''>>
```
This may be considered too specific - but the use case is very common so hopefully worth it.

## Use Cases

This will allow using `array.filter(Boolean)` to get rid of null/undefined/falsy values, and have the type system track it correctly even with `strictNullChecks`.

Right now the options are to use `lodash.compact` or write a similar function (not ideal to add a dependency), or to use `!` (`myArray.filter(Boolean).map(val => val!.foo(...))`) which is a little dangerous.

## Examples

Example
```typescript
const maybeStrings = ['foo', null, 'bar']
const definitelyStrings = maybeStrings.filter(Boolean)
```

`definitelyStrings` is of type `(string | null)[]` even though it's impossible for `null`s to be in it.

current behaviour:
![image](https://user-images.githubusercontent.com/15040698/55116615-44376480-50be-11e9-89cd-edc678f2a04e.png)

proposed behaviour:
![image](https://user-images.githubusercontent.com/15040698/55116142-c9ba1500-50bc-11e9-911b-6ce828d78e50.png)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code (_I don't think so - types would become more specific_)
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
See #29955

**Comment by mmkal** [comment]
@jack-williams interesting, it'd be great if this could be solved by modifying the type of `Boolean` rather than `filter`. But I just tried manually putting in @ForbesLindesay 's signature in `typescript@next` and it doesn't allow using `.filter(Boolean)` without explicitly supplying the generic i.e. `.filter<string>(Boolean)`. That's fine-ish for strings but when it's a complex inferred type that wouldn't be feasible.

**Comment by ForbesLindesay** [comment]
@mmkal That can be fixed, but will require improvements to the inference engine.
