### ISSUE TITLE
Type inference with symbols

### ISSUE THREAD

**Issue by marco6** [Microsoft/TypeScript#30630]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
type inference, symbol, symbols, type, types
**Code**

Take this simple piece of typescript:

``` typescript
interface A {
  ['sym']: 1;
  b: string;
}

interface B {
  ['sym']: 2;
  b: number;
}

type C = A|B;

function doSomethingIfA(c: C): string {
  if (c['sym'] === 1) {
    return c.b; // b is string
  } else {
    return c.b.toString();
  }
}
```
It compiles without any problems (and it's great!). However, I would have expected this to work as well, but it doesn't:

``` typescript
const sym = Symbol();

interface A {
  [sym]: 1;
  b: string;
}

interface B {
  [sym]: 2;
  b: number;
}

type C = A|B;

function doSomethingIfA(c: C): string {
  if (c[sym] === 1) {
    return c.b; // b *should* be string, but is string|number...
  } else {
    return c.b.toString();
  }
}
```

I compiled this with:
`tsc --lib es2015 prova.ts`

**Expected behavior:**

It should compile.

**Actual behavior:**
Doesn't compile, I'm getting (with version 3.4.0-dev.20190328):

```
error TS2322: Type 'string | number' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.

     return c.b; // b is string|number...
```
**Playground Link:**

https://www.typescriptlang.org/play/#src=%0D%0Aconst%20sym%20%3D%20Symbol()%3B%0D%0A%0D%0Ainterface%20A%20%7B%0D%0A%20%20%5Bsym%5D%3A%201%3B%0D%0A%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20%5Bsym%5D%3A%202%3B%0D%0A%20%20b%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20C%20%3D%20A%7CB%3B%0D%0A%0D%0Afunction%20doSomethingIfA(c%3A%20C)%3A%20string%20%7B%0D%0A%20%20if%20(c%5Bsym%5D%20%3D%3D%3D%201)%20%7B%0D%0A%20%20%20%20return%20c.b%3B%20%2F%2F%20b%20is%20string%7Cnumber...%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20return%20c.b.toString()%3B%0D%0A%20%20%7D%0D%0A%7D

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #23135
