### ISSUE TITLE
Property not checked in union of objects

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#30631]
**TypeScript Version:**  3.3.3333

**Search Terms:**

**Code**

```ts
type MyPhotoA = { id: number };
type MyPhotoB = MyPhotoA & { userId: number };

type MyPhoto = MyPhotoA | MyPhotoB;

declare const myPhoto: MyPhoto;

const myPhoto2: MyPhoto = {
    ...myPhoto,
    // Expected type error but got none. `userId` should be string
    userId: {},
};

if ('userId' in myPhoto2) {
    // No type error, but runtime exception!! Very bad…
    myPhoto2.userId.toFixed();
}
```

IIUC, this is because TS considers `myPhoto2` assignable to `MyPhotoA` with an excess property `userId`.

Shouldn't TS check that the excess property is not used in other members of the union?

**Comment by jack-williams** [comment]
Think this is a duplicate of #20863. 

The real design issue here is that excess property checking runs exclusively before further type-checking, delivering a yes/no answer. To correctly check this case you need excess property checking to effectively prune off `MyPhotoA` from the union `MyPhoto` when comparing the types of the properties. For that to work you either need excess property checking to work in tandem with type-checking, or you need excess property checking to return more than just yes/no.

**Comment by OliverJAsh** [comment]
Closing due to duplicate
