### ISSUE TITLE
Incorrect parse of parenthesized expression in second ternary operator operand

### ISSUE THREAD

**Issue by ronnievdc** [Microsoft/TypeScript#30635]
**TypeScript Version:**  3.4.0-dev.20190328

**Search Terms:**
expression expected, Ternary operation, shorthand

**Code**

```ts
let a;
let b;
const c = true ? (a = 1, b = 2) : function () { return true; };
```

**Expected behavior:**
```javascript
var a;
var b;
var c = true ? (a = 1, b = 2) : function () { return true; };
```

**Actual behavior:**
```javascript
var a;
var b;
var c = true ? function (a, b) {
    if (a === void 0) { a = 1; }
    if (b === void 0) { b = 2; }
    return true;
} : ;
```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=let%20a%3B%0D%0Alet%20b%3B%0D%0Aconst%20c%20%3D%20true%20%3F%20(a%20%3D%201%2C%20b%20%3D%202)%20%3A%20function%20()%20%7B%20return%20true%3B%20%7D%3B

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/16241
https://github.com/Microsoft/TypeScript/issues/11582

**Comment by dragomirtitian** [comment]
A simpler repro is just to have () in the then of the ternary expression. This also causes weird parsing to occur:
```ts
 true ? (a): function () { return true; }
```

Transpiled as

```js
true ? function (a) { return true; } : ;
```

**Comment by weswigham** [comment]
Looks like this stems from us parsing JSDoc function types `function()`, (or `function(number, string)` or `function(number): number`)  outside of JSDoc. We should probably just disable that.

**Comment by andrewbranch** [comment]
Yep, that's exactly what's happening @weswigham. But disabling it outright prevents this quick fix from working:

![image](https://user-images.githubusercontent.com/3277153/55348713-b0beb480-546c-11e9-9f23-9e63f777575f.png)

Any suggestions? 🤔

**Comment by weswigham** [comment]
The quickfix is opportunistic in nature - we don't actually expect anyone to write `let x: function(): void`, since that's never been valid in anything. It's moreso for catching things like `let x: string?` (since postfix questionmark is a thing in flow/jsdoc but not TS)
