### ISSUE TITLE
Inconsistent type display with unions of equivalent types

### ISSUE THREAD

**Issue by jack-williams** [Microsoft/TypeScript#30636]
**TypeScript Version:**  3.3

**Search Terms:**

type display union subtype reduction

**Code**

```ts
const bar: { a: {} } | { a: {} } = { a: {} };
const foo = {
    ...bar,
    b: {}
}
foo // { a: {}, b: {} } | {a: {}, b: {} }
foo.a // {}
foo.b // {} | {}
```

**Expected behavior:**

I guess `a` and `b` should be consistent.

**Actual behavior:**

`a` is `{}`, `b` is `{} | {}`.

**Playground Link:** 

[playground](https://www.typescriptlang.org/play/#src=const%20bar%3A%20%7B%20a%3A%20%7B%7D%20%7D%20%7C%20%7B%20a%3A%20%7B%7D%20%7D%20%3D%20%7B%20a%3A%20%7B%7D%20%7D%3B%0D%0Aconst%20foo%20%3D%20%7B%0D%0A%20%20%20%20...bar%2C%0D%0A%20%20%20%20b%3A%20%7B%7D%0D%0A%7D%0D%0Afoo%20%2F%2F%20%7B%20a%3A%20%7B%7D%2C%20b%3A%20%7B%7D%20%7D%20%7C%20%7Ba%3A%20%7B%7D%2C%20b%3A%20%7B%7D%20%7D%0D%0Afoo.a%20%2F%2F%20%7B%7D%0D%0Afoo.b%20%2F%2F%20%7B%7D%20%7C%20%7B%7D)

**Related Issues:** 
#16582

**Comment by jcalz** [comment]
In case anyone cares, I ran into #16582 again and to work around it I wrote a union reducer which will explicitly perform subtype reduction by removing elements from the union if they are assignable to the union-without-that-element.  The implementation is not pretty.

```ts
type BarType = typeof bar; // {a: {}} | {a: {}}
type ReducedBar = UnionReduce<BarType>; // {a: {}}

type FooType = typeof foo; // {b: {}, a: {}} | {b: {}, a: {}}
type ReducedFoo = UnionReduce<FooType>; // {b: {}, a: {}}

type Baz = { a: string } | { a: "a", z: 3 } | { a: number }
type ReducedBaz = UnionReduce<Baz> // {a: string} | {a: number}
```

<details>
<summary><code>UnionReduce</code> implementation</summary>

```ts
type LastOf<T> = (((T extends any ? (x: () => T) => void : never) extends infer U ?
    U : never) extends ((x: infer I) => void) ? I : never) extends () => (infer R) ?
    R : never;

type UnionReduce<T> = LastOf<T> extends infer L ? Exclude<T, L> extends infer X ?
    [X] extends [L] ? L : Exclude<L, X> | UnionReduce<X> : never : never
```

`LastOf`: Extract the "last" element of the union by transforming the union members to the return types of an overloaded function... so `"a" | "b"` becomes `{ () => "a", () => "b" }` and then just getting the return type of that will naturally only consult the last one, so `"b"`:

`UnionReduce`: take the union `T` and break it into the last member `L` and `Exclude<T, L>` which we'll call `X`.  From `L` and `X` we can recursively reduce the union by either returning `L` (if `X` is empty or narrower than `L`) or a function of `UnionReduce<X>`.  

</details>

[Playground link to code](https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBAIwIYCcBccDeckcwXzkIB8sc9DCBeM3LSgblEljgDMww4bNg5+4AOmHIUAGj4CEFYPmAcuAekW0KYxBSJxSmOgXXT6ReZ0FI4y+ibCCEFlQW1XgwGAE8ADgFM4AIVQAKp4+NO7eYGyIqAz2WHr4JHEUcmE+AEpeACYAriBZ-ijccACqEACWkBk5eQA8BUHeAHwxlrrJLqlwAGKcDSFwqRHsnC0Ohvrk9ImY4-jq8SnBcFW5WT1cNKUVECu1633NsTNqkwRyrkv+AF5F2HSwKGUQAOZaOpMAREgf6lcYAMxvVRwCDZAC2CC8hUW3mWWVWmWuRS2lXhtWujSO9xgjxe0zooIhUPOLlJZJclgyMGyKAgAwAFj4PgAbJCwD5wLzMrxgrwQeBDczZcqQC6wgAybJgAHk2DUApiaAAKFUBTkADxgfMyUBwEDccAA-HAleqMEqAJTcTEBK1UTEANzAZUycAwEC8DqhVq8mu1uqebChJSNkn4xTdIM93o1WogOpNpowgeDAEk7Y7nZkrcbU5GPV6UD6-fHdZbrSaU4U0jmw8t89GUEwxT4UTs0V55Yq4JLYLKu7H-XAqz2jXAAKLqkDM7KZTsBdTizG+uMJkcADVDAjgAG11wBdQel3fiw-G8WRyfT2ed8XqdeY0ht3adh8NwvvqHAIA)
