### ISSUE TITLE
How to get intellisense for already initialized Function Constructor 

### ISSUE THREAD

**Issue by yln99517** [Microsoft/TypeScript#30643]
Hi team,
First, thanks for open sourcing this amazing compiler.

We are using (fully) customized internal javascript engine running in our cloud environment.
We have below pattern for all of our javascript ( nearly 5000 files).  

```
//@ts-check
/**
@type {FunctionConstructor}
*/
var Point = createPlainFnType() // returns plain javascript function constructor after initializing  internal scopes, GC stuff and some internal c++ objects
// function Point() {}  // This statement gives full intellisense and no errors but we can't use it.
Point.staticMethod = function() {
}
Point.prototype.memberMethod = function() {
}

Point.staticMethod(); // error here
new Point().memberMethod() // error here
```
 Now the problem is, how do we get intellisense just like normal FunctionConstructor?. or at least is it possible by using out of the box typescript compiler?

Thanks

**Comment by RyanCavanaugh** [comment]
We only support tacking on additional properties if the initializer was a function expression. I don't think it's possible for JS inference to handle this properly without allowing *all* arbitrary writes, which isn't something we want to do.

**Comment by yln99517** [comment]
Thank you @RyanCavanaugh.
