### ISSUE TITLE
Untranslated Content In The Chinese Document

### ISSUE THREAD

**Issue by DaKoala** [Microsoft/TypeScript#30649]
There is a seemingly untranslated English paragraph in the TypeScript Chinese document.

Link to the document page: https://www.tslang.cn/docs/handbook/functions.html

![image](https://user-images.githubusercontent.com/23213763/55262630-c5206880-5244-11e9-95ae-b25e4c50f9e6.png)

I would like to translate the document but wonder how can I contribute to the Chinese website

**Comment by RyanCavanaugh** [comment]
I don't know. We don't own tslang.cn
