### ISSUE TITLE
Compiler ignores const variables

### ISSUE THREAD

**Issue by methodbox** [Microsoft/TypeScript#30652]
**TypeScript Version:**  3.4.0-dev.201xxxxx
3.4.1

**Search Terms:**
"Compiler ignores const, let"

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
The compiler would take the following code:

```typescript
function addNumbers(a: number, b: number) {
  return a + b;
}

const sum: number = addNumbers(10, 15);
console.log('Sum of the numbers is: ', sum);


const bob: string = 'bob';

console.log(bob)
```

And output the following JavaScript, **retaining the const declarations**:

```javascript
function addNumbers(a, b) {
  return a + b;
}

const sum = addNumbers(10, 15);
console.log('Sum of the numbers is: ', sum);

const bob = 'bob';
console.log(bob);
```

**Actual behavior:**
The code that is returned refuses to retain `const`. I've tried this about 50 different ways, it always compiles to `var` instead. I'll admit, I'm new @ typescript, so I'm sure I'm doing something wrong, but I feel like if that's the case, a **warning from the compiler** would be welcome.

Note: I'm using Visual Studio Code and it's default TS settings for this.

```javascript
function addNumbers(a, b) {
    return a + b;
}
var sum = addNumbers(10, 15);
console.log('Sum of the numbers is: ', sum);
var bob = 'bob';
console.log(bob);
```

**Playground Link:** 

**Related Issues:**

**Comment by j-oliveras** [comment]
What `target` did you set in the compiler options?

By default uses `es3` and you should use `es2015` or higher to retain `const`s.

**Comment by methodbox** [comment]
> What `target` did you set in the compiler options?
> 
> By default uses `es3` and you should use `es2015` or higher to retain `const`s.

I did not set it differently, but the default was actually ES5.

I've tried "ES201x" and "ESNEXT" - none of them made any difference.

**Comment by DanielRosenwasser** [comment]
Even if you explicitly list everything on the command line? File name and options?

**Comment by MartinJohns** [comment]
@methodbox You are very likely calling `tsc yourFile.ts`, and you changed the target in your tsconfig file. When you pass filenames to the `tsc` compiler then the tsconfig file is not used (as the documentation mentions).

**Comment by methodbox** [comment]
> @methodbox You are very likely calling `tsc yourFile.ts`, and you changed the target in your tsconfig file. When you pass filenames to the `tsc` compiler then the tsconfig file is not used (as the documentation mentions).

You're right. That was the issue. Though I'd argue if you want people to know that you might want to put it in your Quick Start or Tutorial. https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

There's no indication this is the case. In fact, the tutorial suggests otherwise:

> Compiling your code
We used a .ts extension, but this code is just JavaScript. You could have copy/pasted this straight out of an existing JavaScript app.

At the command line, run the TypeScript compiler:

tsc greeter.ts
The result will be a file greeter.js which contains the same JavaScript that you fed in. We’re up and running using TypeScript in our JavaScript app!

Thanks for the help, though. Maybe consider updating the documentation.
