### ISSUE TITLE
Type simultaneously does and does not have property

### ISSUE THREAD

**Issue by jwalton** [Microsoft/TypeScript#30657]
**TypeScript Version:**  3.4.1 and 3.2.2

**Code**

```ts
interface TextChannel {
    id: string;
    type: 'text';
    phoneNumber: string;
}

interface EmailChannel {
    id: string;
    type: 'email';
    addres: string;
}

type Channel = TextChannel | EmailChannel;

export type ChannelType = Channel extends { type: infer R } ? R : never; // 'text' | 'email'

// Stolen from lodash.
type Omit<T, K extends keyof T> = Pick<
    T,
    ({ [P in keyof T]: P } & { [P in K]: never } & { [x: string]: never })[keyof T]
>;

type ChannelOfType<T extends ChannelType, A = Channel> = A extends { type: T }
    ? A
    : never;

/**
 * A NewChannel is a Channel with a 'type', a 'localChannelId', with no id,
 * and every other field is optional.
 */
export type NewChannel<T extends Channel> = Pick<T, 'type'> &
    Partial<Omit<T, 'type' | 'id'>> & { localChannelId: string };

/**
 * Create a NewChannel of the specified type, ready to hand off to, for example,
 * a react form which can fill it in with values and turn it into a real Channel.
 */
export function makeNewChannel<T extends ChannelType>(type: T): NewChannel<ChannelOfType<T>> {
    const localChannelId = `blahblahblah`;
    return { type, localChannelId };
}

// Here's the exciting bit:

const newTextChannel = makeNewChannel('text');
// Property 'phoneNumber' does not exist on type 'NewChannel<TextChannel>'. ts(2339)
newTextChannel.phoneNumber = '613-555-1234';

const newTextChannel2 : NewChannel<TextChannel> = makeNewChannel('text');
// But this works!
newTextChannel2.phoneNumber = '613-555-1234';
```

**Expected behavior:**

Since `newTextChannel` and `newTextChannel2` are both of type `NewChannel<TextChannel>`, I'd expect them both to have a `phoneNumber` property (or both to not have a `phoneNumber` property).

**Actual behavior:**

`newTextChannel` does not have this property, and `newTextChannel2` does, even though these two seem to be of the same type!

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=interface%20TextChannel%20%7B%0D%0A%20%20%20%20id%3A%20string%3B%0D%0A%20%20%20%20type%3A%20'text'%3B%0D%0A%20%20%20%20phoneNumber%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20EmailChannel%20%7B%0D%0A%20%20%20%20id%3A%20string%3B%0D%0A%20%20%20%20type%3A%20'email'%3B%0D%0A%20%20%20%20addres%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Channel%20%3D%20TextChannel%20%7C%20EmailChannel%3B%0D%0A%0D%0Aexport%20type%20ChannelType%20%3D%20Channel%20extends%20%7B%20type%3A%20infer%20R%20%7D%20%3F%20R%20%3A%20never%3B%20%2F%2F%20'text'%20%7C%20'email'%0D%0A%0D%0A%2F%2F%20Stolen%20from%20lodash.%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3C%0D%0A%20%20%20%20T%2C%0D%0A%20%20%20%20(%7B%20%5BP%20in%20keyof%20T%5D%3A%20P%20%7D%20%26%20%7B%20%5BP%20in%20K%5D%3A%20never%20%7D%20%26%20%7B%20%5Bx%3A%20string%5D%3A%20never%20%7D)%5Bkeyof%20T%5D%0D%0A%3E%3B%0D%0A%0D%0Atype%20ChannelOfType%3CT%20extends%20ChannelType%2C%20A%20%3D%20Channel%3E%20%3D%20A%20extends%20%7B%20type%3A%20T%20%7D%0D%0A%20%20%20%20%3F%20A%0D%0A%20%20%20%20%3A%20never%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20A%20NewChannel%20is%20a%20Channel%20with%20a%20'type'%2C%20a%20'localChannelId'%2C%20with%20no%20id%2C%0D%0A%20*%20and%20every%20other%20field%20is%20optional.%0D%0A%20*%2F%0D%0Aexport%20type%20NewChannel%3CT%20extends%20Channel%3E%20%3D%20Pick%3CT%2C%20'type'%3E%20%26%0D%0A%20%20%20%20Partial%3COmit%3CT%2C%20'type'%20%7C%20'id'%3E%3E%20%26%20%7B%20localChannelId%3A%20string%20%7D%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Create%20a%20NewChannel%20of%20the%20specified%20type%2C%20ready%20to%20hand%20off%20to%2C%20for%20example%2C%0D%0A%20*%20a%20react%20form%20which%20can%20fill%20it%20in%20with%20values%20and%20turn%20it%20into%20a%20real%20Channel.%0D%0A%20*%2F%0D%0Aexport%20function%20makeNewChannel%3CT%20extends%20ChannelType%3E(type%3A%20T)%3A%20NewChannel%3CChannelOfType%3CT%3E%3E%20%7B%0D%0A%20%20%20%20const%20localChannelId%20%3D%20%60blahblahblah%60%3B%0D%0A%20%20%20%20return%20%7B%20type%2C%20localChannelId%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Here's%20the%20exciting%20bit%3A%0D%0A%0D%0Aconst%20newTextChannel%20%3D%20makeNewChannel('text')%3B%0D%0A%2F%2F%20Property%20'phoneNumber'%20does%20not%20exist%20on%20type%20'NewChannel%3CTextChannel%3E'.ts(2339)%0D%0AnewTextChannel.phoneNumber%20%3D%20'613-555-1234'%3B%0D%0A%0D%0Aconst%20newTextChannel2%20%3A%20NewChannel%3CTextChannel%3E%20%3D%20makeNewChannel('text')%3B%0D%0A%2F%2F%20But%20this%20works!%0D%0AnewTextChannel2.phoneNumber%20%3D%20'613-555-1234'%3B%0D%0A)

**Related Issues:** No

**Comment by jwalton** [comment]
Argh.  Github appears to have eaten my bug report's description.  Hang on, I'll edit it.

**Comment by jwalton** [comment]
It even works if you do:

```
const newTextChannel3 : NewChannel<ChannelOfType<'text'>> = makeNewChannel('text');
newTextChannel3.phoneNumber = '613-555-1234';
```

**Comment by ahejlsberg** [comment]
There's definitely something odd going on here. It appears related to the `ChannelOfType` type. For example, it works if you change `ChannelOfType` to:

```ts
type ChannelOfType<T extends ChannelType> =
  T extends 'text' ? TextChannel :
  T extends 'email' ? EmailChannel :
  never;
```

**Comment by weswigham** [comment]
OK, so this is only strange because we have two completely different types which instantiate to the same alias symbol and alias type arguments; under the hood we actually are talking about two _completely separate types_. `NewChannel<ChannelOfType<T>>` instantiates to `NewChannel<TextChannel>` alias-wise, however `NewChannel<ChannelOfType<T>>` is really `NewChannel<ChannelOfType<T, TextChannel> | ChannelOfType<T, EmailChannel>>` if you stop printing `ChannelOfType`'s alias, which is in turn 
```ts
type NewChannel<ChannelOfType<T, TextChannel> | ChannelOfType<T, EmailChannel>> = 
  & Pick<ChannelOfType<T, TextChannel> | ChannelOfType<T, EmailChannel>, "type">
  & Partial<Pick<ChannelOfType<T, TextChannel> | ChannelOfType<T, EmailChannel>, (
    | ({ [P in keyof ChannelOfType<T, TextChannel>]: P; } & { type: never; id: never; } & { [x: string]: never; })
    | ({ [P in keyof ChannelOfType<T, EmailChannel>]: P; } & { type: never; id: never; } & { [x: string]: never; })
  )[keyof ChannelOfType<T, TextChannel> & keyof ChannelOfType<T, EmailChannel>]>>
  & { localChannelId: string; }
```
if you stop printing `NewChannel`'s alias. When `T="text"`, a bunch of stuff reduces like so:
```ts
type NewChannel<TextChannel> = 
  & Pick<TextChannel, "type">
  & Partial<Pick<TextChannel, (
    | ({ [P in keyof TextChannel]: P; } & { type: never; id: never; } & { [x: string]: never; })
    | ({ [P in keyof never]: P; } & { type: never; id: never; } & { [x: string]: never; })
  )[keyof TextChannel & never]>>
  & { localChannelId: string; }
```
OK, now what's gone wrong should be obvious - `keyof ChannelOfType<T, TextChannel> & keyof ChannelOfType<T, EmailChannel>` instantiates to `never`, causing us to index that `Pick` by `never` and thus pull out no keys. The root cause is `keyof never` reducing to `never` - it should be `string | number | symbol` (or `unknown`).
