### ISSUE TITLE
propertyIsDefined() type guard doesn't work with array.filter() in 3.4 anymore

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#30651]
**TypeScript Version:**  3.4.0

**Search Terms:** type guard property 3.4 filter

**Code**
I have this wonderful helper widely used in our codebase:
```ts
/**
 * Returns a function that returns `true` if the given `key` of the object is not `null` or `undefined`.
 */
export const propertyIsDefined = <T extends object, K extends keyof T>(key: K) => (
    val: T
): val is K extends any ? T & { [k in K]: NonNullable<T[k]> } : never => !!val[key]

interface Foo {
  str?: string
}

const foos: Foo[] = []
foos.filter(propertyIsDefined('str')).map(foo => foo.str.toUpperCase())
```

**Expected behavior:**
No type error - the type of `foo.str` should be narrowed to be non-undefined (as pre-3.4).

**Actual behavior:**

Since 3.4, this gives a type error, the type of `foo` is still `string | undefined`.

**Playground Link:** Playground is not on 3.4 yet, copy-paste the above code into an editor

**Related Issues:**

**Comment by weswigham** [comment]
Haven't looked into it yet, but as a workaround here's a slightly less elegant version that still works:
```ts
export const propertyIsDefined = <T extends object, K extends keyof T>(key: K) => (
  val: T | {}
): val is { [k in Exclude<keyof T, K>]: T[k] } & {[k in K]-?: NonNullable<T[k]>} => !!(val as any)[key]

interface Foo {
  str?: string
}

const foos: Foo[] = []
foos.filter(propertyIsDefined('str')).map(foo => foo.str.toUpperCase())
```

**Comment by weswigham** [comment]
@felixfbecker if you replace `K extends any` with `K extends unknown` (which tbh I will always reccomend instead anyway) it also still works.

**Comment by felixfbecker** [comment]
Which version would you recommend? Tbh I don't remember what the `extends any` was for but there was some reason

I also tried using the `Overwrite<T, U>` type from [utility-types](https://www.npmjs.com/package/utility-types#overwritet-u) which should be doing the same as your first example but that didn't work either

**Comment by weswigham** [comment]
`any` behaves both like `never` and `unknown`, depending on context, so once it flows into something what you get out isn't always what you expect. `unknown`, on the other hand, is always just the top. I'd much rather always write `extends unknown` (or types containing `unknown` and `never` positioned correctly according to variance). For the convenience `any` gives, its  behavior in, eg, intersections almost always becomes problematic.

The simple change to `extends unknown` is all you need, tho, the longer thing I wrote isn't needed, I just thought it may have been required until I saw that it was only `any` that'd changed.

**Comment by weswigham** [comment]
Ahhhh, @felixfbecker even smaller change:
```ts
export const propertyIsDefined = <T extends object, K extends keyof T>(key: K) => (
    val: T
): val is K extends any ? T & { [k in K]-?: NonNullable<T[k]> } : never => !!val[key]

interface Foo {
  str?: string
}

const foos: Foo[] = []
foos.filter(propertyIsDefined('str')).map(foo => foo.str.toUpperCase())
```
the `undefined` was actually being reintroduced by the optionality of the property being mixed in in the second mapped type.

**Comment by weswigham** [comment]
Errr, @felixfbecker you should probably just write
```ts
export const propertyIsDefined = <T extends object, K extends keyof T>(
  key: K
) => (
  val: T
): val is T & { [k in K]-?: NonNullable<T[k]> } =>
  !!val[key];

interface Foo {
  str?: string;
}

const foos: Foo[] = [];
foos.filter(propertyIsDefined("str")).map(foo => foo.str.toUpperCase());
```

the conditional seems pretty gratuitous.

**Comment by felixfbecker** [comment]
I remembered again why the `extends unknown` is needed. Without it the helper is not type guards when passing a union type.
```ts
const key: keyof Foo = condition ? 'prop1' : 'prop2'
arr.filter(propertyIsDefined(key))
```

When the passed key is a variable that could be either one or another key, the result should be a union of the type with one key non-optional, or the type with the other key non-optional. This happens with the `extends unknown`. But without it, it would make _both_ keys non-optional (at the same time), which is not correct, because only one of the keys (whatever the variable's value was) is guaranteed to be defined.

I don't know exactly why it behaves this way though.

**Comment by weswigham** [comment]
Well, in any case, the `-?` I'm pretty sure is really what's missing from that type. I think the reason it wasn't needed before was the substitution of `K` in the true branch prevented us from noticing that the mapped type is homomorphic (meaning it depends on a `keyof` type for its keys), so we didn't attempt to preserve optionality. (We made some changes to substitutions specifically on `any` to prevent substitutions on `any` from ever forming, since they do... bad things.) I think the new behavior is expected and all you should need to do is ass the `-?` into the mapped type to explicitly state that you want the required form of the property.

**Comment by felixfbecker** [comment]
Cool, thanks for the help!
