### ISSUE TITLE
tsc will not compile 3 lines of code with "allowJs" option

### ISSUE THREAD

**Issue by arogg** [Microsoft/TypeScript#30668]
**TypeScript Version:**  3.4.1 and typescript@next

**Search Terms:**
allowJs

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

// index.js:

function mymethod(name, cb) {
   exports.Core.cfg.dev_name = name;
};
  
// tsconfig.json:

{
    "compilerOptions": {
        "allowJs": true,
        "outDir": "dist"
    },
    "files": ["./index.js"]
}
```

**Expected behavior:**
compiles

**Actual behavior:**
"Debug Failure" as cmd line output, does not compile

**Playground Link:** 
problem seems to rely on "allowJs", that's why i don't provide playground link

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@andrewbranch I found you a binder bug!
