### ISSUE TITLE
Allowing accessors in deconstructed constructor parameters for classes

### ISSUE THREAD

**Issue by mrtt1000** [Microsoft/TypeScript#30665]
## Search Terms

Accessors, deconstruct, constructor, parameter, class

## Suggestion

Typescript has great support for setting accessors in the constructor e.g.

```typescript
class Animal {
    constructor(private name: string, private type: string, private race: string) { /* empty */ }

     public toString(): string {
         return `the animal is a ${this.type} with the race ${this.race} and is named ${this.name}`;
     }
 }
```

being able to write `private` directly in the `constructor` is such a nice feature introduced in TypeScript, and it would be nice to also be able to that for a deconstructed object.

Lets take the above code and change it, so it works for a deconstructed object.

```typescript
interface IAnimal {
    name: string;
    type: string;
    race: string;
}
```

```typescript
class Animal {
    private name: string;
    private type: string;
    private race: string;

    constructor({name: string, type: string, race: string} : IAnimal) {
         this.name = name;
         this.type = type;
         this.race = race;
    }
     public toString(): string {
         return `the animal is a ${this.type} with the race ${this.race} and is named ${this.name}`;
    }
}
```
The current way for changing deconstructed parameters to private accessors for the `class` requires a lot of extra code and can be a bit tedious to write.

So i came up with two suggestions that possible could solve this problem

### Suggestion 1

```typescript
class Animal {
    constructor({private name: string, private type: string, private race: string} : IAnimal) { /* empty */ }

     public toString(): string {
         return `the animal is a ${this.type} with the race ${this.race} and is named ${this.name}`;
    }
}
```

This suggestion looks very similar to the current way of setting assessors in the `constructor` and allows a developer to choose the accessor for each property of the object.

### Suggestion 2

```typescript
class Animal {
    constructor(private {name: string, type: string, race: string} : IAnimal) { /* empty */ }

     public toString(): string {
         return `the animal is a ${this.type} with the race ${this.race} and is named ${this.name}`;
     }
}
```

This solution would force each deconstructed property to have the same accessor, which matches the current non-deconstructed version of a property (Assuming it's a model object). if the object is private, then it's properties are private, if the object is public, then all the properties would be public.

**Comment by RyanCavanaugh** [comment]
Duplicate #5326

**Comment by mrtt1000** [comment]
Aww shoot, thanks for leading me in the right direction
