### ISSUE TITLE
Another inference bug

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#3067]
Not sure if this one relates to #3038 

```typescript
interface A {
	x: string;
}

interface B {
	x: string;
	y: string;
}

function copyB(value: B): B {
	return undefined;
}

var values: A[] = [];

values.map(value => copyB(value)) // fails as expected
values.map(copyB); // <-- expected to fail, but it does not
```

Can seen at playground: [link](http://www.typescriptlang.org/Playground#src=interface%20A%20%7B%0A%09x%3A%20string%3B%0A%7D%0A%0Ainterface%20B%20%7B%0A%09x%3A%20string%3B%0A%09y%3A%20string%3B%0A%7D%0A%0Afunction%20copyB(value%3A%20B)%3A%20B%20%7B%0A%09return%20undefined%3B%0A%7D%0A%0Avar%20values%3A%20A%5B%5D%20%3D%20%5B%5D%3B%0A%0Avalues.map(value%20%3D%3E%20copyB(value))%20%2F%2F%20fails%20as%20expected%0Avalues.map(copyB)%3B%20%2F%2F%20%3C--%20expected%20to%20fail%2C%20but%20it%20does%20not%0A%0A)

**Comment by ahejlsberg** [comment]
That is by design. For purposes of assignment compatibility, parameters in signatures are bi-variant. We do this more by necessity than choice . There is good discussion of the issue in #1394. As @RyanCavanaugh points out in that thread, without this rule `Array<Dog>` wouldn't be a structural subtype of `Array<Animal>`.

**Comment by aleksey-bykov** [comment]
@ahejlsberg, this is a very sad news to me, we are not using array methods (they are commented out in our lib.d.ts), is there a way to detect this pattern in code using compiler API?

**Comment by danquirk** [comment]
@aleksey-bykov  See #274. It's definitely possible to change the compiler's behavior to disallow this, and we've considered it already as you can see in that issue. It would simply need to be opt in behavior or else it breaks too much existing code (including core JS idioms).
