### ISSUE TITLE
Array type allows empty arrays, but treats them as always filled

### ISSUE THREAD

**Issue by ArmorDarks** [Microsoft/TypeScript#30678]
**Search Terms:**

* `array empty`
* `array void`
* `array empty type guard`
* `array void type guard`
* `no error empty array`

**Code**

```ts
interface TestObject {
  id: string
}

interface Test {
  items: Array<TestObject>
}

const t: Test = { items: [] }

// Expected: to be `TestObject | undefined`
// Actual: `TestObject`
const item0 = t.items[0]

// Expected: to error that `undefined` does not have `id` property
// Actual: no errors
const id = item0.id
```

**Expected behavior:**

To treat `Array<T>` as `T | undefined`, since empty arrays are actually assignable to `Array<T>`. TS should force type guarding of the Array members before accessing their properties. Otherwise, TS should forbid assign an empty array to the `Array` type.

**Actual behavior:**

Attempts to access array members treated by TS as always successful despite they might not exist, and TS allows to assign empty array.

**Playground Link:** https://www.typescriptlang.org/play/#src=interface%20TestObject%20%7B%0D%0A%20%20id%3A%20string%0D%0A%7D%0D%0A%0D%0Ainterface%20Test%20%7B%0D%0A%20%20items%3A%20Array%3CTestObject%3E%0D%0A%7D%0D%0A%0D%0Aconst%20t%3A%20Test%20%3D%20%7B%20items%3A%20%5B%5D%20%7D%0D%0A%0D%0A%2F%2F%20Expected%3A%20to%20be%20%60TestObject%20%7C%20undefined%60%0D%0A%2F%2F%20Actual%3A%20%60TestObject%60%0D%0Aconst%20item0%20%3D%20t.items%5B0%5D%0D%0A%0D%0A%2F%2F%20Expected%3A%20to%20error%20that%20%60undefined%60%20does%20not%20have%20%60id%60%20property%0D%0A%2F%2F%20Actual%3A%20no%20errors%0D%0Aconst%20id%20%3D%20item0.id

**Related Issues:** I tried, really

**Comment by MartinJohns** [comment]
This is a known issue and it's intentional. You can vote for #13778 for a compiler flag that will make array index safer.

**Comment by ArmorDarks** [comment]
Thanks. That's a duplicate then.
