### ISSUE TITLE
Different behaviour of declaration files in typeRoots and node_modules/@types

### ISSUE THREAD

**Issue by SlNPacifist** [Microsoft/TypeScript#30677]
**TypeScript Version:**  3.4.1, 3.4.0-dev.20190330

**Search Terms:** typeRoots

**Code**
Demonstration available at https://github.com/SlNPacifist/typings-issue-example
ts-config.json:
```json
{
    "compilerOptions": {
        "strict": true,
        "typeRoots": ["./external-typings"]
    }
}
```
src/index.ts
```ts
import ask = require('asker');
console.log('Imported', ask);
```

external-typings/asker/index.d.ts
```ts
export = ask;
declare function ask(): number;
```

**Expected behavior:**
Code compiles
**Actual behavior:**
error TS7016: Could not find a declaration file for module 'asker'

However, if I place asker/inde.d.ts in `node_modules/@types/asker/index.d.ts`, code compiles successfully.

This code also compiles with next config:
```
{
    "compilerOptions": {
        "strict": true,
        "baseUrl": ".",
        "paths": {
            "asker": ["./external-typings/asker"]
        }
    }
}
```

I expect that this project compiles all three cases.

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/23185
https://github.com/Microsoft/TypeScript/issues/26900
https://github.com/Microsoft/TypeScript/issues/26732

**Comment by RyanCavanaugh** [comment]
`typeRoots` doesn't affect module resolution.

See #13581, #30599, etc
