### ISSUE TITLE
Array reduce callback (reducer) and default parameters

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#30686]
**TypeScript Version:**  3.0.3, 3.3.3333, 3.3.4000, 3.4.1

**Search Terms:** redux reducer default parameter state undefined generic

**Code**

Originally posted in https://github.com/Microsoft/TypeScript/issues/27277, but that was incorrectly closed as fixed.

When `strictNullChecks` is enabled and `strictFunctionTypes` is disabled:

```ts
type Action = { type: string };
type State = { counter: number };
type Reducer = (state: State | undefined, action: Action) => State;

declare const actions: Array<Action>;
declare const reducer: Reducer;
declare const seed: State;

// Expected `State` but got `State | undefined`
const result = actions.reduce(reducer, seed);
```

**Comment by MartinJohns** [comment]
The issue template contains a section "Playground Link" - you should make use of it.

https://www.typescriptlang.org/play/#src=type%20Action%20%3D%20%7B%20type%3A%20string%20%7D%3B%0D%0Atype%20State%20%3D%20%7B%20counter%3A%20number%20%7D%3B%0D%0Atype%20Reducer%20%3D%20(state%3A%20State%20%7C%20undefined%2C%20action%3A%20Action)%20%3D%3E%20State%3B%0D%0A%0D%0Adeclare%20const%20actions%3A%20Array%3CAction%3E%3B%0D%0Adeclare%20const%20reducer%3A%20Reducer%3B%0D%0Adeclare%20const%20seed%3A%20State%3B%0D%0A%0D%0A%2F%2F%20Expected%20%60State%60%20but%20got%20%60State%20%7C%20undefined%60%0D%0Aconst%20result%20%3D%20actions.reduce(reducer%2C%20seed)%3B%0D%0A (manually enable the options)

Or with the better TypeScript playground:  
https://typescript-play.js.org/#code/C4TwDgpgBAggxsAlgewHZQLxQN5VJALigGdgAnRVAcygF8BuAKH2gGVgBDYaLXOZAK6puZIqgEBbAEYQydJiygAlCABMBcWZigAKUlwhF2BqAB8oQ1RABmlNQBooHBClRF4SNAEpMAPijG3EyMVnAANhxk0PyopE4uaMTuZGQcIAA8Hq6+TKERUVAxcVHqmqLKahqyuRDhkdGJwCQQakacQYyMAPRdUACiAB6QCGpQAAaBEGNQUgJNVMhNE+3Q5pY2dqpjjEVNUcQCYU1Yzp6xAHQlVTpXZY7ELapeTEA

In both playgrounds the type is as expected `State`, not `State | undefined`.

**Comment by OliverJAsh** [comment]
@MartinJohns You forgot to disable `strictFunctionTypes`. https://typescript-play.js.org/?strictFunctionTypes=false#code/C4TwDgpgBAggxsAlgewHZQLxQN5VJALigGdgAnRVAcygF8BuAKH2gGVgBDYaLXOZAK6puZIqgEBbAEYQydJiygAlCABMBcWZigAKUlwhF2BqAB8oQ1RABmlNQBooHBClRF4SNAEpMAPijG3EyMVnAANhxk0PyopE4uaMTuZGQcIAA8Hq6+TKERUVAxcVHqmqLKahqyuRDhkdGJwCQQakacQYyMAPRdUACiAB6QCGpQAAaBEGNQUgJNVMhNE+3Q5pY2dqpjjEVNUcQCYU1Yzp6xAHQlVTpXZY7ELapeTEA

**Comment by MartinJohns** [comment]
I indeed completely over-read that part. Yes, that is the issue, and it was not mentioned in the previous issue. My mistake.
