### ISSUE TITLE
Suggestion: Const contexts for generic type inference

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript#30680]
## Search Terms

const contexts; literals; narrowing; generics; 

## Suggestion

Allow const contexts for generic type parameter inference.

Often I've written and seen generic functions where the type parameter inference is intended to be as narrow as possible.  Accomplishing this involves several "tricks" with generic constraints.  It is more reminiscent of alchemy than I would like, and places quite a burden on the function signature and anyone with the misfortune of having to read and understand it:

```ts
// 🧙 what sorcery is this?? 🧙‍ 
type Narrowable = string | number | boolean | symbol | object | undefined | void | null | {};
declare function foo<N extends Narrowable, T extends { [k: string]: N | T | [] }>(x: T): T; 

foo({ a: 1, b: "c", d: ["e", 2, true, { f: "g" }] });
// T inferred as { a: 1; b: "c"; d: ["e", 2, true, { f: "g"; }]; }
```

Const contexts (#29510) are exactly the knob we want to turn here, and the "`as const`" syntax 
is succinct, understandable, and non-mind-bending.  Unfortunately, the only way to use this in
generic functions is from the caller's side, which is hard to guarantee:

```ts
declare function bar<T extends object>(x: T): T; 
bar({ a: 1, b: "c", d: ["e", 2, true, { f: "g" }] } as const); // burden on function caller
// T inferred as { 
//   readonly a: 1; readonly b: "c"; d: readonly ["e", 2, true, { readonly f: "g"; }]; 
// }

bar({ a: 1, b: "c", d: ["e", 2, true, { f: "g" }] }); // oops!!
// T inferred as { 
//   a: number; b: string; d: (string | number | boolean | { f: string; })[]; 
// } 😢

```

The suggestion here is to get the best of both worlds by allowing a const context to be specified in the generic type parameter declaration:

```ts
declare function baz<T extends const object>(x: T): T; // 🤔
declare function baz<T extends object as const>(x: T): T; // 🤷
declare function baz<const T extends object>(x: T): T; // 😵
declare function baz<const T const extends readonly object as const>(x: T): T; // 🧠💥🤪

// also possible, see #46937:
declare function baz<T extends object>(x: const T): T; 



baz({ a: 1, b: "c", d: ["e", 2, true, { f: "g" }] });
// T inferred as { 
//   readonly a: 1; readonly b: "c"; d: readonly ["e", 2, true, { readonly f: "g"; }]; 
// } ❤🎉
```

## Related issues

#29510: const contexts

#10676: generics infer literals "T extends string | number | boolean"
#27179: generics infer tuples "T extends U[] | [U]"
#13347: probably can't make generics infer readonly 

#16896: please narrow all object literals as much as possible

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

EDIT: mentioning slightly different approach from #46937 where modifier goes on the type parameter instead of its constraint.  It's not obvious to me if one has an advantage over the other.

**Comment by aleclarson** [comment]
This would allow for generic function parameters to be inferred as tuples. 👍

**Comment by aleclarson** [comment]
This would allow forcing a generic parameter to be inferred as a tuple instead of an array. 👍

**Comment by sberan** [comment]
This would be incredible. I have an API for json schema which currently requires the caller to type `as const` everywhere:

```
// $ExpectType Schema<string>
schema({
  type: ['string']
} as const)

// $ExpectType Schema<string | number>
schema({
  type: ['string', 'number']
} as const)

```

**Comment by jcalz** [comment]
Relevant SO question: [Dynamically generate return type based on array parameter of objects in TypeScript](https://stackoverflow.com/questions/59440453/dynamically-generate-return-type-based-on-array-parameter-of-objects-in-typescri)

My current answer involves adding a dummy  type parameter `S extends string` to get string literal narrowing to happen in a different type parameter `T extends {fieldName: S}`; it reminded me that it would be so nice to have some more transparent syntax like `T extends {fieldName: const string}` (or something) here.

**Comment by arciisine** [comment]
Closed #35821 in lieu of this.  To expand upon this issue,  I would also like to have support for this in Javascript, as `as const` is not applicable outside of `.ts` files.

**Comment by dirkluijk** [comment]
@jcalz Thank you for the `Narrowable` workaround.

I need this as well, to infer string literals or enum values in generics.

**Comment by jwulf** [comment]
Another relevant SO question: https://stackoverflow.com/questions/64056538/type-signature-that-infers-all-values

**Comment by cyrilletuzi** [comment]
What is the status of this? I have the same issue as @sberan: inferring the type from a JSON Schema would currently require `as const` everywhere on the caller side:

```ts
interface JsonSchemaNumber {
  type: 'number';
}

interface JsonSchemaString {
  type: 'string';
}

type JsonSchema = JsonSchemaNumber | JsonSchemaString;

type SchemaToType<Schema extends JsonSchema> =
  Schema extends { type: 'string' } ? string :
  Schema extends { type: 'number' } ? number :
  unknown;

function test<T extends JsonSchema>(schema: T): SchemaToType<T> | void {
  if (schema) {}
}

const int = { type: 'number' };
test(int);
```

Fails on function calling parameter with error:

```
Argument of type '{ type: string; }' is not assignable to parameter of type 'JsonSchema'.
  Type '{ type: string; }' is not assignable to type 'JsonSchemaString'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"string"'.
```

While the following work:

```ts
const int = { type: 'number' } as const;
test(int);
```

Meaning the caller must do `as const` everywhere.

**Comment by millsp** [comment]
Hi all,

I think that I have finally solved this puzzle. We can now control const contexts on the behalf of the user. There we go:

```ts
type Narrowable =
| string
| number
| bigint
| boolean
| symbol
| object
| undefined
| void
| null
| {}
| [];

type Const<N> = {
    [K in keyof N]: N[K] extends Narrowable
                    ? N[K] | Const<N[K]>
                    : never
};

// 🧙 what sorcery is this now?? 🧙‍
declare function foo<A>(x: Const<A>): A;

const test0 = foo({a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]});
// `A` inferred : {a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]}
```

[Play it](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcghgJwQewO5wEYBtoF4BQAPlAM7AICWAdgOZFRUCuAthhAvRhTdcJ8shxwq9EiFaD6yDACsIAYz7FGVACYQAZtQir6AN2QVdxJliz0A3gF96AbQC6Abnz5QkKAGFkVMgB4YAHxQuFAW+FARULYA0lDUUADWECDIGrD2AFywMfZQEAAewBBqJLCIKOjYEOGRtXX1UAD82dG5xF4+wP45ATUN-ZFZVBB67PhWzvgA9FNQgHwbgJu7UKgAFnDApMgI8uwgcaXAKxSlVGiNzYuAsAT46vJYiNAaKooU3lAaAr4AggEAFPlZDp+H4ASiyX0m8m8ZCgRTIAAZgu8BL8LHAsgBGAA0UAwWQA5PJ8TjVFlbPiIMSoAAmHHkRgQHEWDRk-E0fH2KyckHOGZQAAGX35cSoGnYCB0UCyaMxOLxUEJVNJUQpVNpsIQDKZLJV7M5nKAA)

This will land soon in https://github.com/millsp/ts-toolbelt

**Comment by millsp** [comment]
I just reworked the code above to fully support what @jcalz suggested in https://github.com/microsoft/TypeScript/issues/30680#issuecomment-568223968. I'm doing it the other way around instead. We can specify which specific fields are going to widen - and this is possible precisely and at any depth, within any structure:

```ts
type Narrowable =
| string
| number
| bigint
| boolean
| [];

type Widen<A = unknown> = {type: A};

type Const<A, W = {}> = A & (
W extends Widen<infer T> ? T :
A extends Narrowable ? A & W : {
    [K in keyof A]: K extends keyof W
                    ? Const<A[K], W[K]>
                    : Const<A[K], {}>
});

declare function foo<A>(x: Const<A, {a: number, c: Widen<unknown[]>}>): A;
declare function bar<A>(x: Const<A, {a: Widen<number>, c: [Widen<unknown>, number]}>): A;
declare function baz<A>(x: Const<A>): A;

const test0 = foo({a: 1, b: 2, c: [3, 4, [5]]});
// `A` inferred : {a: 1, b: 2, c: (number | number[])[]}

const test1 = bar({a: 1, b: 2, c: [1, 4]});
// `A` inferred : {a: number, b: 2, c: [number, 4]}

const test2 = baz({a: 1, b: 2, c: [3, 4]});
// `A` inferred : {a: 1, b: 2, c: [3, 4]}

const test3 = baz('hello jcalz <3');
// `A` inferred : 'hello jcalz <3'
```

As you can see it's also possible to validate against the desired structure and set a field as widening or not widening.

**Comment by KisaragiEffective** [comment]
maybe `type Narrowed<T> = intrinsic` and implement in tsc? then, `function x<T>(a: Narrowed<T>): foo` can be made?

**Comment by jcalz** [comment]
Another SO question: [Converting values in a dictionary to literal values](https://stackoverflow.com/questions/67879983/converting-values-in-a-dictionary-to-literal-values)

**Comment by leoblum** [comment]
+1

**Comment by jcalz** [comment]
Edited to reflect slightly different approach as mentioned in #46937

**Comment by captain-yossarian** [comment]
It would be great and make TS less verbose

**Comment by Shigma** [comment]
#48240 provides an excellent example of type annotations. Now I would prefer `<const T>`.

**Comment by PEZO19** [comment]
@jcalz this might be related too (SO): https://stackoverflow.com/questions/70632106/how-to-infer-recursive-container-types-with-dependent-types-in-typescript?noredirect=1#comment124955483_70632106

**Comment by yujiosaka** [comment]
@millsp 's [solution](https://github.com/microsoft/TypeScript/issues/30680#issuecomment-752725353) solved most of my problems like a charm!

But I want to share one corner case to push this issue forward, which is providing a library to anonymous people.

Although the `Narrow` type works when you pass the argument directly to functions,
it does not work, of course, when the argument is defined beforehand without const assertion.

```ts
declare function foo<A>(x: Narrow<A>): A;
declare function bar<A extends object>(x: Narrow<A>): A;

const param0 = {a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]};
const test0 = foo(param0);
// not inferred as : {a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]}
// but inferred as : {a: number, b: string, d: (string | number | boolean | {f: string[]})[]}

type Cast<A, B> = A extends B ? A : B;

type Narrowable =
| string
| number
| bigint
| boolean;

type Narrow<A> = Cast<A,
| []
| (A extends Narrowable ? A : never)
| ({ [K in keyof A]: Narrow<A[K]> })
>;
```
[Playground](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4BBAPgAoAPALngDlYYcB3UsgSjpIG4AoUJFgIU6bHngAjWKXggqGEKmABneDkkArcBkq0GTVuy7xefPmDwqM8AA6woAWwAM8ALzwA3lDoBGADRSdADkYMGBwHQA2sEg4fAATIEYMMgggZ6I0cEA5sEAugC+RfyWqNbwitauHoiEFPYwTs4c-AD0bfCoODZYqIggMHDA8FBqdN5+gZIhYRHZcYFJlanpXlnwMXlFRXwdUsi9-YPDo+NePl3IjpKD03TWMH058-AUj8-wAD5XN4PfUkIEBAUHwP0yDxSzyiRQ4MMK5gwAE9bAgAMJjDCkQIAITI7lMcgUSlU8Bx8AA-IS6Dj+HxkaiDENWFBJMD3Hwfh9UDlOb9bjA+ZIsDk+hghUCQag6QyEIxmWxyASMdZsXyYXyKCQiYplGp5cwWKz2VTtXRUCAAG6DDiazybADS8D68AA1iAkThEKZ8nQDUYSFEHfl8YVbWR+EA)

If it's an internal project, you can ask your teammates to always pass arguments directly.
It's certainly much easier than forcing them to pass `as const` in every function call.

But when you are providing a library, people may not follow your advice always.

What I expect with this proposal is that following code fails to compile because passed argument can be modified (thus the types cannot be narrowed).
```ts
declare function baz<const T extends object>(x: T): T; // I don't have a preference in which style
const param0 = {a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]};
const test0 = foo(param0); // it shouldn't compile
```

It should accept const argument.
```ts
declare function baz<const T extends object>(x: T): T;
const param0 = {a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]} as const;
const test0 = foo(param0); // inferred as : {a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]}
```

Also it would be nice if it automatically asserts argument as const when it's passed directly to the function (as originally proposed in this issue).
```ts
declare function baz<const T extends object>(x: T): T;
const test0 = foo({a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]}); // inferred as : {a: 1, b: 'c', d: ['e', 2, true, {f: ['g']}]}
```

**Comment by stephenh** [comment]
Fwiw I'm upgrading my project to TypeScript 4.9 and @millsp 's `Const` solution is no longer working for me...

I had been using:

```
    const a1 = await em.load(Author, "1", { publisher: {}, books: { reviews: "book" } });
    expect(a1.publisher.get).toEqual(undefined);
```

With using `Const`:

```
  public async load<T extends Entity, H extends LoadHint<T>>(
    type: EntityConstructor<T>,
    id: string,
    populate: Const<H>,
  ): Promise<Loaded<T, H>>;
```

But the `a1` is no longer inferring as `Loaded<Author, { publisher: {}, books: ... }>` but is instead inferring as `Loaded<Author, LoadHint<Author>>`.

I don't suppose anyone has ran into this / found a fix? As-is I'm having to fix it by adding `as const` at call sites:

```
    const a1 = await em.load(Author, "1", { publisher: {}, books: { reviews: "book" } } as const);
```

Which is going to be really verbose. Thanks!

**Comment by Andarist** [comment]
It would be best if you could share a full inspectable TS playground with a report like this. It's hard to know what exactly might have changed if you don't share a repro case.

**Comment by stephenh** [comment]
Ah hey @Andarist ! Yeah, that's a very fair ask; I was admittedly being lazy and hoping someone would have already hit an error and had a new/updated snippet.

I'll work on a playground-able repro of my issue.
