### ISSUE TITLE
Allow const assertion to be use on enum types 

### ISSUE THREAD

**Issue by dragomirtitian** [Microsoft/TypeScript#30690]
## Search Terms

A 'const' assertion can only be applied to a string, number, boolean, array, or object literal

## Suggestion

Allow const assertion to be use on enum types. Currently the const assertion can be applied to `string` and `number` literals to get the compiler to keep literal types. But enums, which also can also produce literal types are not allowed in const assertions.

This seems inconsistent.

## Use Cases

The use case I wanted to use it for is creating an object that could be assigned to a discriminated union (inspired by this [SO question](https://stackoverflow.com/questions/55458995/why-does-enum-value-need-to-be-coerced-before-object-type-is-recognized-properly/55459079#55459079))

## Examples

```ts
enum AorB { A = 'a', B = 'b' };
const arg = { type: 1 as const }; // { type: 1 }
const arg2 = { type: "1" as const }; // { type: "1" }
const arg3 = { type: AorB.A as const }; // Expected: { type: AorB.A; }, Actual: A 'const' assertion can only be applied to a string, number, boolean, array, or object literal.

```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
>  This wouldn't be a breaking change in existing TypeScript/JavaScript code

Note that `as const` is recursive, so this would be a potential break

**Comment by dragomirtitian** [comment]
@RyanCavanaugh  I don't think it would be because literal types are already inferred for enums in objects. It's just that if the const assertion is directly on the enum we get an error.

```ts
const arg3 = { type: AorB.A  } as const // typed as  { readonly type: AorB.A; }
const arg3 = { type: AorB.A as const };  // but error here
```

**Comment by RyanCavanaugh** [comment]
Accepting PRs for this. It should be allowed only in the case E.P where E is a literal enum; PR should include negative tests for other cases which should be disallowed (e.g. `O.P` where `O` is *not* a literal enum).

**Comment by Kingwl** [comment]
![image](https://user-images.githubusercontent.com/6831019/55385281-55b9ba00-555f-11e9-861b-72924109faaf.png)
![image](https://user-images.githubusercontent.com/6831019/55385299-5fdbb880-555f-11e9-9b3e-144bb0da5682.png)  
I'm not sure current behavior is expected....
