### ISSUE TITLE
Bundling non-ts modules

### ISSUE THREAD

**Issue by duzenko** [microsoft/TypeScript#30709]
I can't get a text module to get included in the output bundle.

Minimal repro case attached. The relevant code is

```
import text from 'text.dat'
console.log( text )
```

Running this javascript code in my web browser I get
```
Error: Fetch error: 404 Not Found
  Instantiating http://localhost:8082/text.dat
  Loading http://localhost:8082/main
  Loading main
```

And looking into bundle.js it seems that it assumes text.dat to be in the public folder as a separate file, however typescript does not copy it from the src folder.

What am I missing? What is the right way to use text modules and output bundles at the same time?

[tstextassets.zip](https://github.com/Microsoft/TypeScript/files/3034924/tstextassets.zip)

**Comment by DanielRosenwasser** [comment]
You need a bundler (like Webpack, Rollup, or browserify) or a runtime loader (like Require.js, System.js), neither which TypeScript provides. StackOverflow may be able to assist better.

**Comment by duzenko** [comment]
> 
> 
> You need a bundler (like Webpack, Rollup, or browserify) or a runtime loader (like Require.js, System.js), neither which TypeScript provides. StackOverflow may be able to assist better.

What would that do? Copy the text module to the output folder? Is there no way to include the text module content in the typescript output .js?

**Comment by duzenko** [comment]
Closed without solution and possibility to reopen. Great support...
