### ISSUE TITLE
focusin/focusout events missing in lib.dom.d.ts

### ISSUE THREAD

**Issue by SetTrend** [microsoft/TypeScript#30716]
In contrast to issue #21822, `focusin` and `focusout` are missing as event types for `element.addEventListener()`.

**TypeScript Version:**  3.3.4000

**Search Terms:**

focusin focusout

**Code**

![image](https://user-images.githubusercontent.com/9283914/55426858-13f03a00-5586-11e9-9477-c4a33419cbfa.png)

![image](https://user-images.githubusercontent.com/9283914/55426937-4306ab80-5586-11e9-8105-31eae1507b84.png)

**Expected behavior:**

Both, `focusin` and `focusout`, should be available, taking an `FocusEvent` as their parameter.

**Actual behavior:**

Both, `focusin` and `focusout`, are unknown to TypeScript.

**Related Issues:**

#21822

**Comment by Fabianopb** [comment]
Hi! Yep, it seems they are missing!
I can contribute to this one, will submit a PR soon.

**Comment by Fabianopb** [comment]
Should `onfocusin` and `onfocusout` be also included as properties of the interface `GlobalEventHandlers`? e.g.:
```ts
onfocusin: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null;
onfocusout: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null;
```

**Comment by Fabianopb** [comment]
Created a PR, still kind of WIP, so I'd be glad to get some feedback!

**Comment by Fabianopb** [comment]
Just for information here, the PR should be good to be merged now.

**Comment by Fabianopb** [comment]
@RyanCavanaugh sorry to nag again, but the PR has been open for a month and it's approved, but not yet merged. Is something still missing?

**Comment by SetTrend** [comment]
@Fabianopb : Just out of curiosity: In the PR @saschanaz writes: "those IDL attributes are not implemented in any browsers nor included in any spec."

But, in fact ...
- they are implemented in all common browsers, incl. Firefox, Chrome and IE 11
- they are listed in this [W3C UI Events](https://www.w3.org/TR/uievents/#event-type-focusin) spec.

Have I been missing something?

And, most importantly, are these two events now added to the lib?

**Comment by saschanaz** [comment]
@SetTrend By "those IDL attributes" I meant `on*` IDL attributes including `onfocusin` and `onfocusout`. They are not in the spec nor implemented anywhere, although I filed https://github.com/whatwg/html/issues/4542 to add them.

**Comment by Fabianopb** [comment]
Yes, @saschanaz is right. But anyway `focusin` and `focusout` are now added and merged to `master`, I dunno when the patch will be released though.

**Comment by SetTrend** [comment]
Ah, great! Thanks for clarifying!
