### ISSUE TITLE
Method returning index type breaks type interference of union types

### ISSUE THREAD

**Issue by thammi** [microsoft/TypeScript#30717]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** union, index type

**Code**

```ts
class Test<Props extends Object> {
  constructor(public o: Props) {}
  get<K extends keyof Props>(k: K) : Props[K] { return this.o[k]; }
}

interface A {t: "A";};
interface B {t: "B";};
type u = Test<A> | Test<B>;

const tmp = new Test<B>({t: 'B'}) as u;

switch(tmp.get('t')) {
  case 'A': break;
  case 'B': break;
}
```

**Expected behavior:**

Code compiles with `tmp.get('t')` having type `"A" | "B"`.

This works for:

* [simple objects/interfaces](https://www.typescriptlang.org/play/#src=interface%20A%20%7B%20t%3A%20'A'%3B%20%7D%3B%0D%0Ainterface%20B%20%7B%20t%3A%20'B'%3B%20%7D%3B%0D%0Atype%20u%20%3D%20A%20%7C%20B%3B%0D%0A%0D%0Aconst%20tmp%20%3D%20%7B%20t%3A%20'B'%20%7D%20as%20u%3B%0D%0A%0D%0Aswitch(tmp.t)%20%7B%0D%0A%20%20case%20'A'%3A%20break%3B%0D%0A%20%20case%20'B'%3A%20break%3B%0D%0A%7D)
* [classes](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20get()%20%7B%20return%20%22A%22%3B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20%7B%0D%0A%20%20get()%20%7B%20return%20%22B%22%3B%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20u%20%3D%20A%20%7C%20B%3B%0D%0A%0D%0Aconst%20tmp%20%3D%20new%20B()%20as%20u%3B%0D%0A%0D%0Aswitch(tmp.get())%20%7B%0D%0A%20%20case%20'A'%3A%20break%3B%0D%0A%20%20case%20'B'%3A%20break%3B%0D%0A%7D)
* [classes with generics](https://www.typescriptlang.org/play/#src=class%20Test%3CT%3E%20%7B%0D%0A%20%20constructor(public%20v%3A%20T)%20%7B%7D%0D%0A%20%20get()%20%7B%20return%20this.v%3B%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20u%20%3D%20Test%3C%22A%22%3E%20%7C%20Test%3C%22B%22%3E%3B%0D%0A%0D%0Aconst%20tmp%20%3D%20new%20Test%3C%22B%22%3E(%22B%22)%20as%20u%3B%0D%0A%0D%0Aswitch(tmp.get())%20%7B%0D%0A%20%20case%20'A'%3A%20break%3B%0D%0A%20%20case%20'B'%3A%20break%3B%0D%0A%7D)

**Actual behavior:**

Compilation fails with error:

    Type '"B"' is not comparable to type '"A"'.

Type of `tmp.get('t')` is only `"A"`.

Problem is not contained to string literals, but also [other types](https://www.typescriptlang.org/play/#src=class%20Test%3CProps%20extends%20Object%3E%20%7B%0D%0A%20%20constructor(public%20o%3A%20Props)%20%7B%7D%0D%0A%20%20get%3CK%20extends%20keyof%20Props%3E(k%3A%20K)%20%3A%20Props%5BK%5D%20%7B%20return%20this.o%5Bk%5D%3B%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Num%20%7Ba%3A%20number%3B%7D%3B%0D%0Ainterface%20Str%20%7Ba%3A%20string%3B%7D%3B%0D%0Atype%20u%20%3D%20Test%3CNum%3E%20%7C%20Test%3CStr%3E%3B%0D%0A%0D%0Aconst%20tmp%20%3D%20new%20Test%3CStr%3E(%7Ba%3A%20'test'%7D)%20as%20u%3B%0D%0A%2F%2F%20type%20is%20'number'%2C%20not%20'number%20%7C%20string'%0D%0Aconst%20res%20%3D%20tmp.get('a')%3B). Enountered this bug using immutable-js Record.get().

**Playground Link:** [playground](https://www.typescriptlang.org/play/#src=class%20Test%3CProps%20extends%20Object%3E%20%7B%0D%0A%20%20constructor(public%20o%3A%20Props)%20%7B%7D%0D%0A%20%20get%3CK%20extends%20keyof%20Props%3E(k%3A%20K)%20%3A%20Props%5BK%5D%20%7B%20return%20this.o%5Bk%5D%3B%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20A%20%7Bt%3A%20%22A%22%3B%7D%3B%0D%0Ainterface%20B%20%7Bt%3A%20%22B%22%3B%7D%3B%0D%0Atype%20u%20%3D%20Test%3CA%3E%20%7C%20Test%3CB%3E%3B%0D%0A%0D%0Aconst%20tmp%20%3D%20new%20Test%3CB%3E(%7Bt%3A%20'B'%7D)%20as%20u%3B%0D%0A%0D%0Aswitch(tmp.get('t'))%20%7B%0D%0A%20%20case%20'A'%3A%20break%3B%0D%0A%20%20case%20'B'%3A%20break%3B%0D%0A%7D%0D%0A)

**Related Issues:**  None found

**Comment by RyanCavanaugh** [comment]
Simplified very slightly
```ts
declare class Test<T> {
  obj: T;
  get<K extends keyof T>(k: K): T[K];
}

interface A { t: "A" }
interface B { t: "B" }

declare const tmp: Test<A> | Test<B>;

switch(tmp.get('t')) {
  case 'A': break;
  case 'B': break;
}
```
Not a regression - this has been the behavior since 2.1.

**Comment by RyanCavanaugh** [comment]
We don't even understand why the `tmp.get` call was allowed in the first place? Generic signatures should not have unified across union type boundaries... 😕

**Comment by weswigham** [comment]
I have a PR open here, but IIRC a recent change anders made should have also fixed this - I'll check.

**Comment by RyanCavanaugh** [comment]
This now works the way we want it to - the call to `get` is flagged as an error.

**Comment by weswigham** [comment]
@RyanCavanaugh there is some additional code in #31023 that makes the call not-an-error, as the type parameters and argument lists in use are identical.
