### ISSUE TITLE
Undefined "exports" when nothing is exported 

### ISSUE THREAD

**Issue by cawoodm** [Microsoft/TypeScript#30718]
I'm going to be brave and revive the perennial and duplicated `ReferenceError: exports is not defined` issue. I have read the duplicate issues and seen no solution.

TLDR: TypeScript compiles .js files which contain an extraneous reference to exports which breaks apps.

Example:

app.ts
```typescript
import {sayHello} from "./func";
sayHello("you")
```

func.ts
```typescript
export function sayHello(name){console.log("Hello " + name)}
```

app.js
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tmp_1 = require("./func");
tmp_1.sayHello("you");
```

Line 2 of app.js is rejected by platforms like electron which don't know "exports".

I think the impasse is:

1. The electron guys say: Typescript should use `modules.exports` which we do support.
2. The typescript guys say: Electron should support `exports`

Workaround: Manually change the references (be the post-compiler) from `Object.defineProperty(exports, "__esModule", { value: true });` to `Object.defineProperty(module.exports, "__esModule", { value: true });`

Would be nice if `tsc` would play nice with electron: as things stand I see no way of using `tsc` with electron without manually post-compiling the JS.

Electron v4.0.6 (Windows) with node v10.11.0
TSC Version 3.4.1

**Comment by cawoodm** [comment]
Also, just removing the apparently* unneccessary line solves the issue:

```javascript
Object.defineProperty(exports, "__esModule", { value: true });
```

~* Yes, we have `"module": "commonjs",` but that doesn't mean every file is a module exporting something (app.js above definitely isn't).

**Comment by RyanCavanaugh** [comment]
I'm running this in the sample electron app on both the client and server pieces with no problems.

Maybe some repro steps would be useful

**Comment by cawoodm** [comment]
OK, to reproduce you include your primary/app script as a script tag in the html of the electron app. In this context "exports" is undefined and the code above breaks. This is admittedly atypical behaviour but it's done for apps which need to run in the browser AND in electron. Or, put another way, my app was working perfectly until I switched to typescript and got this extraneous code.

You could pull https://github.com/cawoodm/powowshell and notice it works perfectly in electron and the browser: that's because I've commented out line 2 in [pipeline-manager.js](https://github.com/cawoodm/powowshell/blob/master/ide/js/pipeline-manager.js). If you uncomment it, electron and the browser break.

I feel that tsc is adding code I don't want or need and making me choose between typescript OR some transpiler which accepts ES6.

**Comment by RyanCavanaugh** [comment]
The CommonJS spec says that a variable named `exports` exists and that's the module system you told TypeScript you were using. You can't take a file you said is built for a CommonJS environment and run it in a non-CJS-compliant environment - it *might* work by accident, but TS can't guarantee anything there.

> I feel that tsc is adding code I don't want or need

The `__esmodule` marker is required for spec compliance when the file is imported by an ES6 loader.

I've seen some workarounds where people put a dummy `var exports` in an app-wide script tag. You can also use `export = ` in your modules, which will make them not-possibly-ES6-compliant and make the `__esmodule` helper code go away

**Comment by cawoodm** [comment]
Ja, I've gone for the `var exports` hack for the moment and will probably end up dropping support for the browser or diving into webpack.
Thanks so far.
