### ISSUE TITLE
isFunctionLike cases contains duplicates

### ISSUE THREAD

**Issue by Connoropolous** [Microsoft/TypeScript#3072]
for example:

FunctionExpression is checked for on line 4547 and also 4559

![screen shot 2015-05-07 at 3 24 45 pm](https://cloud.githubusercontent.com/assets/1409121/7524024/523b49bc-f4cd-11e4-8a01-638c3ed5dc2c.png)

**Comment by mhegazy** [comment]
thanks @Connoropolous for reporting this. should be fixed in master now.

**Comment by Connoropolous** [comment]
No problem. Speedy fix!
