### ISSUE TITLE
Add "concrete subclass of given abstract class"

### ISSUE THREAD

**Issue by Ginden** [Microsoft/TypeScript#30729]
## Search Terms

subclass, typeof abstract class, subclass of abstract class

Related issue: #9302

## Suggestion

Allow to define type like:
```typescript
declare function bar<AbstractFoo>();
const Foo: not abstract extends AbstractFoo = someSource();
new Foo;

```
## Use Cases

I have some code like:
```typescript
async function getInstance(className: string):  AbstractFoo {
    const Ctor: any = await loadClass(className); // assume that loadClass returns "any"
    return new Ctor(1, 'a', 'b');
}
```

I would like to allow typechecking of Ctor arguments.  I tried to use:
```
const Ctor: typeof AbstractFoo = ...;
return new Ctor();
```

But it fails with error message "cannot create instance of abstract class".

For general case, this can be unsafe (all possible subclasses have to keep constructor signature from base class), but it provides better safety than `any`.

Currently there is option to use:
```typescript
const Ctor: { new(/* repeat signature from constructor and keep it synchronized*/): AbstractFoo }
```

But it requires code duplication.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
But the constructor of your base class says nothing about the constructor of your derived class. The arguments can be the same, but they can also be entirely different.

**Comment by RyanCavanaugh** [comment]
`new(the signature you are going to call) => AbstractBase` is the intended way to do this. As @MartinJohns points out, the derived class ctors may have different arguments, so specifying the signature you intend to invoke makes sure you end up with a correct derived class constructor call
