### ISSUE TITLE
typescript@next version number still at 3.4.0?

### ISSUE THREAD

**Issue by jcalz** [Microsoft/TypeScript#30733]
Today in [npm](https://www.npmjs.com/package/typescript?activeTab=versions) the `@latest` version is [`typescript@3.4.1`](https://www.npmjs.com/package/typescript/v/3.4.1) but the `@next` version is [`typescript@3.4.0-dev.20190403`](https://www.npmjs.com/package/typescript/v/3.4.0-dev.20190403).  Is that expected or should we be up to `typescript@3.5.0-dev.XXXXXXXX`?  or `3.4.2-dev` or something?  Thanks!

**Comment by DanielRosenwasser** [comment]
Fixed, thanks!

**Comment by DanielRosenwasser** [comment]
(You'll see a new version tonight)

**Comment by jcalz** [comment]
`typescript@3.5.0-dev.20190404` 👍
