### ISSUE TITLE
compileOnSaveEmitFile silently failing

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#30739]
I believe this behavior is by-design but it's very surprising and the user experience is poor.  The original context was Visual Studio, but I wouldn't be surprised to learn that VS Code is also affected.

tsconfig.json
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "test",
    "noEmitOnError": true,
    "declaration": true,
    "noImplicitAny": false,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

(I've left the properties as originally reported in the VS bug, but moved the important ones to the top - `compileOnSave`, `outDir`, `noEmitOnError`, and `declaration`.)

file1.ts
```ts
const x = 1;
```

file2.ts
```ts
const y = 2;
```

If you edit and save `file2.ts` (e.g. 2 -> 3), VS sends `compileOnSaveAffectedFileList` and the response indicates that both files need to be emitted (since everything is global).

There are some guesses in this next bit.

First, VS sends a `compileOnSaveEmitFile` request for `file1.ts`.  It succeeds and `test\file1.js`, `test\file1.js.map` and `test\file1.d.ts` are emitted.  (Possibly, file2.ts is also supposed to be emitted?)

Once `test\file1.d.ts` exists, it becomes part of the configured project.  From this point on, any attempt to emit `file1.ts` (even for `file2.ts`) will fail, since `file1.d.ts` is both an input and an output.  Since `noEmitOnError` is true, the emit will be skipped.  At this point, compile-on-save is effectively broken and the set of output files will depend on the exact sequence of edits and saves.

The smallest possible mitigation would be to surface the/a diagnostic that caused emit to be skipped.  A better mitigation would be to alert the user that their configuration is invalid, ideally, before emitting anything.

**Comment by sheetalkamat** [comment]
I think when someone does not specify exclude in their config, we exclude `outDir` and `declarationDir` but otherwise we dont. May be we should add suggestion diagnostics if exclude in config file doesn't specify `outDir` or `declarationDir` and code fix to add them there?

**Comment by sheetalkamat** [comment]
After looking this over, reporting error if file is from outDir is not a solution that will fit all and seems like it may break existing projects out in the wild. So better thing to do would be to report error.. 
Currently `CompileOnSaveEmitFileRequest` returns response as `boolean` value if its failed or passed. Can that be changed to return Response that contains { emitSkipped: boolean; diagnostics: Diagnostics[]}` instead without breaking VS ?

**Comment by sheetalkamat** [comment]
@uniqueiniquity @amcasey can return response of CompileOnSaveEmitFileRequest be changed without breaking VS ?

**Comment by amcasey** [comment]
@sheetalkamat sorry, I missed your question the first time.  I suspect that, yes, that would break VS, but I can confirm.

**Comment by uniqueiniquity** [comment]
Yes, that would make it incompatible with non-updated versions of VS.

**Comment by amcasey** [comment]
I believe our usual approach is to have a configuration opt in for the new API shape (e.g. `richCompileOnSaveEmitFileResponse: true`).
