### ISSUE TITLE
Object.keys must use keyof of generic type <T extends object>, not just <T>

### ISSUE THREAD

**Issue by Boeny** [Microsoft/TypeScript#30749]
Despite the comment https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208
I would proceed the discussion with just a little suggestion:

the `Object.keys` function should look like:
`keys<T extends {}>(o: T): Array<keyof T>;`

**Comment by j-oliveras** [comment]
Duplicate and rejected multiple times: https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208, #30314, #13254. #30228, #28899, #28284, #26901.

[More info](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript)

**Comment by RyanCavanaugh** [comment]
Thanks @j-oliveras - much appreciated
