### ISSUE TITLE
Tsc compiler hangs (3.4.0-dev.20190226 and above)

### ISSUE THREAD

**Issue by martis347** [Microsoft/TypeScript#30745]
Hello, 

I've encountered to some issues after updating typescript to the latest stable version. With versions 3.3.4000, 3.4.0-dev.20190223 it's working, with every later version it just hangs.
It is using styled components, but the issue seems not to be there.

**TypeScript Version:**  3.4.0-dev.20190226 and above (up until 3.5.0-dev.20190404)

**Search Terms:** typescript 3.4.0 hangs, typescript 3.4.0 no response, typescript 3.4.0 compiler unresponsive

**Code**

```ts
import baseStyled, { ThemedStyledInterface } from 'styled-components';

interface Theme {
	color: string;
}

const styled = baseStyled as ThemedStyledInterface<Theme>;
console.log(styled);
```

**Expected behavior:**
It compiles in <5 seconds

**Actual behavior:**
Tsc does not compile, just hangs and uses a lot of CPU power.

**Playground Link:** I've created a github repo with a minimal reproduction  https://github.com/martis347/typescript-error

**Comment by AlCalzone** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/30663 ?

**Comment by martis347** [comment]
@AlCalzone Yep, looks like it. Sorry for not finding it and creating a duplicate. I'll close this one.
