### ISSUE TITLE
Support for programmatically using

### ISSUE THREAD

**Issue by dagadbm** [Microsoft/TypeScript#30751]
## Search Terms

tsconfig js tsconfig programatically

## Suggestion

I would like for TypeScript to add suport for tsconfig.js instead of tsconfig.json (similar to what babel/jest/prettier have.

## Use Cases

I have some alias.js file which contains an object with all of my aliases which I then import on 3 different places: babel.config.js , webpack.config.dev.js, webpack.config.prod.js. (In case it is not obvious, this is a CRA ejected project).
I then want to be able to use VSCode navigation capabilities but I cannot because he does not find the aliases. After some research I believe you could create a tsconfig.json which VSCode would then look for the paths there and make path resolution work (plus vs-code would not complaint about unresolved module errors from eslint).

If I was able to do a tsconfig.js file I would be able to fix this and vscode would then just read from that file automatically.

## Checklist

My suggestion meets these guidelines:

* [ X ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ X ] This wouldn't change the runtime behavior of existing JavaScript code
* [ X ] This could be implemented without emitting different JS based on the types of the expressions
* [ X ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ X ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplciate of #30400

**Comment by dagadbm** [comment]
same idea. different use case (im not talking about adding comments but actual code execution).
Is this a very complex thing to do?

**Comment by MartinJohns** [comment]
> same idea.

Same suggestion, yes, just with a different intention.

> Is this a very complex thing to do?

The TypeScript team deemed it as too complex. The different intention of your proposal does no change the complexity.

Here's another issue that requested the same: #25271

**Comment by dagadbm** [comment]
alright. there is a fair point there indeed regarding not all tools being able to read a js instead of a json for configuration. thanks Martin. I will close this issue. 
Funny how I could not find it after searching, my issue search foo is still very young.

**Comment by rasenplanscher** [comment]
For anybody still interested in this feature: https://www.npmjs.com/package/tsconfig.js
