### ISSUE TITLE
Unable to define env/scope of *only* service-worker file in JS project

### ISSUE THREAD

**Issue by wilsonpage** [microsoft/TypeScript#30750]
I'm working on a JS (not TS) project and using VSCode/Typecripts checkjs feature to check/lint the project.

I'm unable to find a way of defining the scope of just the service-worker file to `ServiceWorkerGlobalScope` without changing the scope of the other files from `Window`.

I've tried various combinations of sibling `.d.ts` files and `/// <reference lib="…" />` but many of them seem to operate on the project in a 'global' manner, changing the default-lib/scope of all .js files causing loads of errors.

---

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

"How to define env/scope of service-worker file in VSCode"

**Code**

https://github.com/wilsonpage/vscode-scope-test-case

**Expected behavior:**

Should be able to define lib/env of a single file without impacting entire project.

**Actual behavior:**

When adding `/// <reference types="node_modules/types-serviceworker" />` it appears to change the default-lib of all other `.js` files in the project.

**Playground Link:** 

This is a checkjs issue, not related to typescript project.

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/14877

**Related Repo:** 

https://github.com/shqld/types-serviceworker

**Comment by RyanCavanaugh** [comment]
You'd need to have different config files or similar. Settings such as lib are per-project, not per file

**Comment by wilsonpage** [comment]
@RyanCavanaugh I now have 2 different `jsconfig.json` files in the [reduced test-case](https://github.com/wilsonpage/vscode-scope-test-case). Two issues:

1. Service worker file still thinks it's a `worker`, meaning it's erroring on use of ServiceWorker specific APIs (eg. `self.skipWaiting()`).
2. How can I run Typescript's `checkjs` on the entire project in one go?
