### ISSUE TITLE
interface Geolocation (lib.d.ts) has the wrong type for watchId

### ISSUE THREAD

**Issue by yebrahim** [Microsoft/TypeScript#3075]
This is the definition of Geolocation in lib.d.ts:
```javascript
interface Geolocation {
    clearWatch(watchId: number): void;
    getCurrentPosition(successCallback: PositionCallback, errorCallback?: PositionErrorCallback, options?: PositionOptions): void;
    watchPosition(successCallback: PositionCallback, errorCallback?: PositionErrorCallback, options?: PositionOptions): number;
}
```

watchId variables in watchPosition() and clearWatch() are declared as numbers, but actually the Cordova [documentation on Geolocation](http://docs.phonegap.com/en/edge/cordova_geolocation_geolocation.md.html#geolocation.watchPosition) states it's a string.

**Comment by mhegazy** [comment]
@zhengbli can you take a look.

**Comment by zhengbli** [comment]
Both ``watchId`` and ``clearWatch()`` are indeed number in the spec. And they are also defined as ``long`` in the [w3c spec](http://dev.w3.org/geo/api/spec-source.html#geolocation).

**Comment by mhegazy** [comment]
Looks like by design then.
