### ISSUE TITLE
Object literal array type inconsistently inferred when using spread

### ISSUE THREAD

**Issue by ssynix** [microsoft/TypeScript#30761]
**TypeScript Version:**  3.3.3333

**Search Terms:**
* object literal array type 
* object array property does not exist
* spread object literal array 

**Code**

Playground: http://tinyurl.com/y65n9b3o
```ts
const array1 = [
    { a: 'a', b: 'b' },
    { a: 'a', c: 'c' },
] // inferred: Partial<{ a, b, c }>[]

array1.map(({ c }) => c); // works ✅


const array2 = [
    { a: 'a', b: 'b' },
    { a: 'a', ...{ c: 'c' } },
]

array2.map(({ c }) => c); // suddenly error? ❌

```

**Expected behavior:**
I'm not sure if this is a bug but I expect both map calls to type-check identically. If it's not a bug, it's very unintuitive why the spread syntax completely changes how the array type is inferred. The only workaround I have is to explicitly write the full type (which isn't as concise as the example above).

**Comment by RyanCavanaugh** [comment]
We have "special" logic for unifying object literals in these cases; the spread syntax interferes with that.

If you post a more representative sample where it's not just spreading for the sake of spreading, we may be able to advise more.

**Comment by ssynix** [comment]
[Here's almost the same code](https://www.typescriptlang.org/play/#src=const%20testId%20%3D%20(id%3A%20string)%20%3D%3E%20(%7B%20'data-testid'%3A%20id%20%7D)%3B%0A%0A%0A%2F%2F%20In%20Semantic%20UI%20(component%20library)%2C%20the%20headers%20of%20a%20%3CTable%3E%20can%20be%20passed%0A%2F%2F%20to%20the%20component%20as%20an%20array%20of%20header%20props%0A%0Aconst%20headerProps%20%3D%20%5B%0A%20%20%20%20%7B%20key%3A%20%22title%22%2C%20content%3A%20%22Titles%22%2C%20sortField%3A%20%22title%22%2C%20...testId(%22title-sort%22)%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%22id%22%2C%20content%3A%20%22IDs%22%2C%20sortField%3A%20%22id%22%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%22actions%22%2C%20content%3A%20%22%22%2C%20className%3A%20%22actions-header%22%20%7D%2C%0A%5D.map(header%20%3D%3E%20%7B%0A%20%20%20%20%2F%2F%20Non-sortable%20field%0A%20%20%20%20if%20(!header.sortField)%20return%20header%3B%0A%0A%20%20%20%20const%20%7B%20sortField%2C%20className%2C%20...headerRest%20%7D%20%3D%20header%3B%0A%20%20%20%20%2F%2F%20Add%20classNames%20and%20onClick%20for%20sortable%20fields%0A%20%20%20%20return%20header%3B%0A%7D)%0A%0A%0A%0A%0Aconst%20headerPropsMoreTestIds%20%3D%20%5B%0A%20%20%20%20%7B%20key%3A%20%22title%22%2C%20content%3A%20%22Titles%22%2C%20sortField%3A%20%22title%22%2C%20...testId(%22title-sort%22)%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%22id%22%2C%20content%3A%20%22IDs%22%2C%20sortField%3A%20%22id%22%2C%20...testId(%22id-sort%22)%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%22actions%22%2C%20content%3A%20%22%22%2C%20className%3A%20%22actions-header%22%20%7D%2C%0A%5D.map(header%20%3D%3E%20%7B%0A%20%20%20%20%2F%2F%20Non-sortable%20field%0A%20%20%20%20if%20(!header.sortField)%20return%20header%3B%0A%0A%20%20%20%20const%20%7B%20sortField%2C%20className%2C%20...headerRest%20%7D%20%3D%20header%3B%0A%20%20%20%20%2F%2F%20Add%20classNames%20and%20onClick%20for%20sortable%20fields%0A%20%20%20%20return%20header%3B%0A%7D)%0A%0A%2F*%0A%0A%3CTable%20headers%3D%7BheaderProps%7D%20%7B...tableProps%7D%20%2F%3E%0A%0A%20*%2F) that reproduces the error.

Is the special logic documented somewhere? It would help avoid surprises and confusion if the logic is more explicitly defined, or if there are ways to control the inference.
