### ISSUE TITLE
Generic Function Regression with React JSX since 3.2+

### ISSUE THREAD

**Issue by cvle** [Microsoft/TypeScript#30762]
**TypeScript Version:**  3.2.1 – 3.5.0--dev.20190404

**Search Terms:** arrow function generic react jsx regression hoc

The following code worked in 3.1.6 but since 3.2+ it fails. I'm using this sort of construct in various Higher-Order-Component functions.

**Code**

```ts
import React from "react";

function test<T extends { a: string }>(TestComponent: React.ComponentType<T>) {
  return <TestComponent a="test" />;
}
```
Not exactly sure what's happening there. Because. Typescript seem somewhat inferring it correctly but when I put it into the `JSX` it fails.

![image](https://user-images.githubusercontent.com/14221600/55594204-ff0ad680-573e-11e9-9021-b1592780853f.png)

**Expected behavior:**
To compile without errors.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/14221600/55594034-65dbc000-573e-11e9-82ce-d540fbf4aa0b.png)

**Comment by RyanCavanaugh** [comment]
This is a correct error. Your function says that this is a legal call:

```ts
declare const comp: React.ComponentType<{ a: "foo" }>;
test(comp);
```

but your implementation provides `"test"` where `"foo"` is required

**Comment by cvle** [comment]
@RyanCavanaugh I'm not sure if we are on the same page. Your answer looks a bit unrelated. Maybe I'm just missing something.

The example you gave me looks like this, which works:

```ts
const Foo: React.ComponentType<{ a: "foo" }>;
<Foo a="foo" />
```

But this doesn't:
```ts
function createElementFromComponent<T extends { a: "foo" }>(
  Foo: React.ComponentType<T>
) {
  return <Foo a="foo" />;
}
```

And I get `Type '{ a: "foo"; }' is not assignable to type 'T'.`

**Comment by SuperOleg39** [comment]
Also have this problem with HOCs
