### ISSUE TITLE
Possible regression for 3.4 for recursive generic type

### ISSUE THREAD

**Issue by TRCYX** [microsoft/TypeScript#30772]
**TypeScript Version:**  3.4.1 / 3.5.0-dev.20190405

**Search Terms:** Recursive generic type, circular reference

**Code**

```ts
type Cons<H, T extends any[]> = ((h: H, ...t: T) => void) extends ((...a: infer A) => void) ? A : never;

type Elem = { [key: string]: Elem[] };

// All possible paths consisted of keys from an Elem or an Elem[]

type PathFromElem<T extends Elem> = {
    [K in keyof T]: PathFromArr<T[K]> extends infer U ? U extends any[] ? Cons<K, U> : never : never;
}[keyof T];

type PathFromArr<T extends Elem[]> = [] |
    (T[keyof T] extends infer U ? U extends Elem ? PathFromElem<U> : never : never);

type ExtendsArr = [{
    a1: [{ b1: []; }], a3: []
}, {
    a4: []
}];

// expected [] | ["a1"] | ["a1", "b1"] | ["a3"] | ["a4"]
type Test = PathFromArr<ExtendsArr>;
```

**Expected behavior:** Test to be [] | ["a1"] | ["a1", "b1"] | ["a3"] | ["a4"]

**Actual behavior:** type alias 'PathFromArr' circular references itself

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=type%20Cons%3CH%2C%20T%20extends%20any%5B%5D%3E%20%3D%20((h%3A%20H%2C%20...t%3A%20T)%20%3D%3E%20void)%20extends%20((...a%3A%20infer%20A)%20%3D%3E%20void)%20%3F%20A%20%3A%20never%3B%0D%0A%0D%0Atype%20Elem%20%3D%20%7B%20%5Bkey%3A%20string%5D%3A%20Elem%5B%5D%20%7D%3B%0D%0A%0D%0A%2F%2F%20All%20possible%20paths%20consisted%20of%20keys%20from%20an%20Elem%20or%20an%20Elem%5B%5D%0D%0A%0D%0Atype%20PathFromElem%3CT%20extends%20Elem%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20keyof%20T%5D%3A%20PathFromArr%3CT%5BK%5D%3E%20extends%20infer%20U%20%3F%20U%20extends%20any%5B%5D%20%3F%20Cons%3CK%2C%20U%3E%20%3A%20never%20%3A%20never%3B%0D%0A%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0Atype%20PathFromArr%3CT%20extends%20Elem%5B%5D%3E%20%3D%20%5B%5D%20%7C%0D%0A%20%20%20%20(T%5Bkeyof%20T%5D%20extends%20infer%20U%20%3F%20U%20extends%20Elem%20%3F%20PathFromElem%3CU%3E%20%3A%20never%20%3A%20never)%3B%0D%0A%0D%0Atype%20ExtendsArr%20%3D%20%5B%7B%0D%0A%20%20%20%20a1%3A%20%5B%7B%20b1%3A%20%5B%5D%3B%20%7D%5D%2C%20a3%3A%20%5B%5D%0D%0A%7D%2C%20%7B%0D%0A%20%20%20%20a4%3A%20%5B%5D%0D%0A%7D%5D%3B%0D%0A%0D%0A%2F%2F%20expected%20%5B%5D%20%7C%20%5B%22a1%22%5D%20%7C%20%5B%22a1%22%2C%20%22b1%22%5D%20%7C%20%5B%22a3%22%5D%20%7C%20%5B%22a4%22%5D%0D%0Atype%20Test%20%3D%20PathFromArr%3CExtendsArr%3E%3B)

**Related Issues:** Not sure

The above code works fine with typescript 3.3.4000. Sorry that I am unable to simplify the code much further while keeping it work in 3.3. These recursive path types are for checking if paths are correctly written at compile time.

If the "circular reference" error is intended, I would like to know if there are any workarounds in the new version of typescript, since I haven't found any. Also, a thorough explanation on what is considered cirular reference and what is not is appreciated.

**Comment by RyanCavanaugh** [comment]
A workaround is probably possible but will require a long investigation.

The thing going on here is that you have (in 3.4) a "simplifying" conditional type of the form
```ts
type T<U> = U extends V ? W : never;
```
or
```ts
type T<U> = U extends V ? never : W;
```
These get treated differently and require that `T` not appear in `W`.

The fact that you were able to use `T` in 3.3 was actually a bug, though it's understandable that it seemed to work.

**Comment by weswigham** [comment]
Even if you were the remove the trigger for resolving the inner bits of the mapped type that's usually going to defer things and "hide" the circularity by avoiding generic mapped type substitution during identity checking, the example above would still trigger

>Type instantiation is excessively deep and possibly infinite.

in TS 3.4. (Which means it bottomed out silently to `any` in 3.3, we just toss an error on it now)

**Comment by TRCYX** [comment]
Thanks for your replies!

Currently this is what I've got. It does not work at all in 3.3; the type checker seems to be indirected.

In 3.4 and 3.5, well... it kinda works, but not fully as expected:
```ts
// The following are unchanged.
type Cons<H, T extends any[]> = ((h: H, ...t: T) => void) extends ((...a: infer A) => void) ? A : never;

type Elem = { [key: string]: Elem[] };

type PathFromElem<T extends Elem> = {
    [K in keyof T]: PathFromArr<T[K]> extends infer U ? U extends any[] ? Cons<K, U> : never : never;
}[keyof T];

// The above are unchanged.
// CHANGED; a mapped tuple type is used, and the normal Array keys are excluded.
type PathFromArr<T extends Elem[]> = [] | ({
    [K in keyof T]: T[K] extends Elem ? PathFromElem<T[K]> : never;
})[Exclude<keyof T, keyof any[]>];

type ExtendsArr = [{
    a1: [{ b1: []; }], a3: []
}, {
    a4: []
}];

// expected [] | ["a1"] | ["a1", "b1"] | ["a3"] | ["a4"]
// got [] | ["a1", ...never[]] | ["a1", ..."b1"[]] | ["a3", ...never[]] | ["a4", ...never[]]
type Test = PathFromArr<ExtendsArr>;

// These work fine:
const eps: Test = [];
const a1: Test = ["a1"];
const a3: Test = ["a3"];
const a4: Test = ["a4"];
const a1b1: Test = ["a1", "b1"];
// The following produces errors as expected:
const a1a1: Test = ["a1", "a1"];
const a1b1c1: Test = ["a1", "b1", "c1"];
const a1b2: Test = ["a1", "b2"];
const a5: Test = ["a5"];

// UNEXPECTED: Slipped through checker! (or it should be the checker letting it pass)
const a1b1b1: Test = ["a1", "b1", "b1"];
```

This seems to be related to a problem with `Cons` inside a conditional:
```ts
type Helper<T> = T extends any[] ? Cons<"a", T> : never;

// ["a", ...never[]]; whereas normal Cons<"a", []> yields ["a"]
type Problem = Helper<[]>;

// ["a", ..."a"[]], which is effectively "a"[]
type Problem2 = Helper<Problem>;

// Identical to Problem2, also ["a", ..."a"[]]
type Problem3 = Helper<Problem2>;
```

Are there any ideas on this?

**Comment by mheiber** [comment]
I'm a little confused about the present and desired state of this sort of error.
Typelevel recursion is pretty useful, but it seems we'll often get errors when using it.
What is the workaround for this sort of case? Is the recommendation to avoid this sort of recursion, or is it explicitly supported (rather than being a happy accident)?
