### ISSUE TITLE
No error report when using compound assignment operator with literal types.

### ISSUE THREAD

**Issue by Veetaha** [Microsoft/TypeScript#30783]
**TypeScript Version:**  3.4.2

* literal type shorthand assignment 
* shorthand assignment

**Code**

```ts
let ten = 10 as const;

// no error reports
ten += 2;
ten -= 2;
ten *= 2;
ten /= 2;
ten **= 2;
ten %= 2;
ten |= 2;
ten &= 2;
ten ^= 2;
ten >>= 2;
ten >>>= 2;
ten <<= 2;

// all errors as expected
ten = ten + 2;
ten = ten - 2;
ten = ten * 2;
ten = ten / 2;
ten = ten ** 2;
ten = ten % 2;
ten = ten | 2;
ten = ten & 2;
ten = ten ^ 2;
ten = ten >> 2;
ten = ten >>> 2;
ten = ten << 2;

let pinkie = 'Pinkie' as const;

// no error report
pinkie += 'Pie';

// error as expected
pinkie = pinkie + 'Pie';
 ```

**Expected behavior:**

Shorthand assignment to a literal type where the resulting assigned value may not always be of that literal type should generate a compile-time error likewise its expanded form.

**Actual behavior:**
There is no error report for using shorthand assignment operators that might store an invalid value for that literal type. But the expanded form of those operators works as expected.

**Playground Link:** 

[Klick me](https://www.typescriptlang.org/play/index.html#src=let%20ten%20%3D%2010%20as%20const%3B%0D%0A%0D%0A%2F%2F%20no%20error%20reports%0D%0Aten%20%2B%3D%202%3B%0D%0Aten%20-%3D%202%3B%0D%0Aten%20*%3D%202%3B%0D%0Aten%20%2F%3D%202%3B%0D%0Aten%20**%3D%202%3B%0D%0Aten%20%25%3D%202%3B%0D%0Aten%20%7C%3D%202%3B%0D%0Aten%20%26%3D%202%3B%0D%0Aten%20%5E%3D%202%3B%0D%0Aten%20%3E%3E%3D%202%3B%0D%0Aten%20%3E%3E%3E%3D%202%3B%0D%0Aten%20%3C%3C%3D%202%3B%0D%0A%0D%0A%2F%2F%20all%20errors%20as%20expected%0D%0Aten%20%3D%20ten%20%2B%202%3B%0D%0Aten%20%3D%20ten%20-%202%3B%0D%0Aten%20%3D%20ten%20*%202%3B%0D%0Aten%20%3D%20ten%20%2F%202%3B%0D%0Aten%20%3D%20ten%20**%202%3B%0D%0Aten%20%3D%20ten%20%25%202%3B%0D%0Aten%20%3D%20ten%20%7C%202%3B%0D%0Aten%20%3D%20ten%20%26%202%3B%0D%0Aten%20%3D%20ten%20%5E%202%3B%0D%0Aten%20%3D%20ten%20%3E%3E%202%3B%0D%0Aten%20%3D%20ten%20%3E%3E%3E%202%3B%0D%0Aten%20%3D%20ten%20%3C%3C%202%3B%0D%0A%0D%0Alet%20pinkie%20%3D%20'Pinkie'%20as%20const%3B%0D%0A%0D%0A%2F%2F%20no%20error%20report%0D%0Apinkie%20%2B%3D%20'Pie'%3B%0D%0A%0D%0A%2F%2F%20error%20as%20expected%0D%0Apinkie%20%3D%20pinkie%20%2B%20'Pie'%3B%0D%0A%0D%0A%0D%0A)

**Related Issues:**

**Comment by Veetaha** [comment]
Quick inline proposal: compute literal types expressions at compile-time so that `ten * 2` would be of type `20` but not `number` or type of `'Pinkie' + 'Pie'` expression is `'PinkiePie'` instead of `string`.

**Comment by DanielRosenwasser** [comment]
Potentially related to #13865, but I feel like we have another issue about this.

**Comment by RyanCavanaugh** [comment]
Duplicate #14745
