### ISSUE TITLE
Indexing a mapped type does not return the expected type.

### ISSUE THREAD

**Issue by justjake** [microsoft/TypeScript#30784]
**TypeScript Version:**  typescript@3.4.1, typescript@3.5.0-dev.20190405
**Search Terms:** indexing mapped type inference constraint

**Code**

```ts
type BlockValue = "a" | "b" | "c"

type BlockRenderer<B extends BlockValue> = (blockValue: B) => number

type BlockRenderers = {
    [B in BlockValue]: BlockRenderer<B>
}

// Problem case that I expect to work.
function renderBlockBad<B extends BlockValue>(block: B, renderers: BlockRenderers) {
    // render has type BlockRenderers[B] instead of BlockRenderer<B>.
    const render = renderers[block]
    return render(block)
}

// To satisfy the typechecker I must use a cast.
function renderBlockGood<B extends BlockValue>(block: B, renderers: BlockRenderers) {
    const render = renderers[block] as (blockValue: B) => number
    return render(block)
}
```

**Expected behavior:**
In this case, I should see `render` to be inferred as type `BlockRenderer<B>`, because the BlockRenderers mapped type should map `{ B: BlockRenderer<B> }`.

**Actual behavior:**

The type of `render` is inferred as `BlockRenderers[B]` which expects its argument to satisfy all the types in the union. This results in the following error:

```
case.ts(9,19): error TS2345: Argument of type 'B' is not assignable to parameter of type '"a" & "b" & "c"'.
  Type 'BlockValue' is not assignable to type '"a" & "b" & "c"'.
    Type '"a"' is not assignable to type '"a" & "b" & "c"'.
      Type '"a"' is not assignable to type '"b"'.
        Type 'B' is not assignable to type '"a"'.
          Type 'BlockValue' is not assignable to type '"a"'.
            Type '"b"' is not assignable to type '"a"'.
```

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20BlockValue%20%3D%20%22a%22%20%7C%20%22b%22%20%7C%20%22c%22%0D%0A%0D%0Atype%20BlockRenderer%3CB%20extends%20BlockValue%3E%20%3D%20(blockValue%3A%20B)%20%3D%3E%20number%0D%0A%0D%0Atype%20BlockRenderers%20%3D%20%7B%0D%0A%20%20%20%20%5BB%20in%20BlockValue%5D%3A%20BlockRenderer%3CB%3E%0D%0A%7D%0D%0A%0D%0Afunction%20renderBlockBad%3CB%20extends%20BlockValue%3E(block%3A%20B%2C%20renderers%3A%20BlockRenderers)%20%7B%0D%0A%20%20%20%20const%20render%20%3D%20renderers%5Bblock%5D%20%2F%2F%20Got%20BlockRenderers%5BB%5D%20instead%20of%20BlockRenderer%3CB%3E%0D%0A%20%20%20%20return%20render(block)%0D%0A%7D%0D%0A%0D%0Afunction%20renderBlockGood%3CB%20extends%20BlockValue%3E(block%3A%20B%2C%20renderers%3A%20BlockRenderers)%20%7B%0D%0A%20%20%20%20const%20render%20%3D%20renderers%5Bblock%5D%20as%20(blockValue%3A%20B)%20%3D%3E%20number%0D%0A%20%20%20%20return%20render(block)%0D%0A%7D%0D%0A

**Related Issues:** 

cc @ccorcos

**Comment by RyanCavanaugh** [comment]
From our perspective, this is a correct error, because we can't tell this example apart from a correctly-erroring:

```ts
type BlockValue = "a" | "b" | "c"
type BlockRenderer<B extends BlockValue> = (blockValue: B) => number
type BlockMap = {
    [B in BlockValue]: BlockRenderer<B>
}

function renderBlockBad<B extends BlockValue>(block1: B, block2: B, renderers: BlockMap) {
    const render = renderers[block1]
    return render(block2);
}

declare const map: BlockMap;
renderBlockBad<"a" | "b">("a", "b", map);
```

We'd need some new concept for "indexed operation with **this value**" instead of "indexed operation with **this type**"

**Comment by ccorcos** [comment]
Hmm. That seems like it should work as well right? both block 1 and block 2 have the same type...

**Comment by ccorcos** [comment]
Oh, I see what going on here. The type itself is a union. Yeah, thats a problem....

Ideally there's some sort of non-union version of `B extends BlockValue` where B has to be one of the union, on just a sub-union.

**Comment by justjake** [comment]
> We'd need some new concept for "indexed operation with **this value**" instead of "indexed operation with **this type**"

That would be great; or:

> Ideally there's some sort of non-union version of B extends BlockValue where B has to be one of the union, on just a sub-union.

For indexing types it would be helpful to write this kind of strict constraint:

```typescript
function renderBlockBad<B in BlockValue>(block: B, renderers: BlockMap) {
```

something something covariance

**Comment by justjake** [comment]
@RyanCavanaugh was there any progress on https://github.com/microsoft/TypeScript/issues/33014 ?
