### ISSUE TITLE
"esModuleInterop":true does not work with tsc when specified in tsconfig.json

### ISSUE THREAD

**Issue by localmonalisa** [Microsoft/TypeScript#30795]
**TypeScript Version:**  3.4.1

tsc ignoring esModuleInterop: true option when set from tsconfig.json
**Code**

tsconfig.json
{
  "noImplicitAny": true,
  "compilerOptions": {
    "baseUrl": "../../../",
    "paths": {
      "jquery": ["node_modules/jquery/dist/jquery"]
    },
    "typeRoots": [
      "node_modules/@types"
    ],
    "module": "commonjs",
    "target": "es5",
    "lib": [ "es2015", "dom" ],
    "sourceMap": true,
    "declaration": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "exclude": [
    "node_modules"
  ]
}

test.ts

import $ from 'jquery';

$(function(){
   console.log("jquery loaded");
});

It worked fine when I used.
tsc --esModuleInterop  test.ts

but not working when I use
tsc test.ts

**Expected behavior:**
It should compile ts file

**Actual behavior:**
error TS1192: Module '"jquery"' has no default export.
Does't compile the ts file.

**Comment by j-oliveras** [comment]
If you define files in command line, the `tsconfig.json` file is ignored. See the [documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson).
