### ISSUE TITLE
Suggestion: tsc init to generate tsconfig.json

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#3079]
I know the tsconfig.json file is small, but it's a distraction to have to go look up a copy-paste example while you're starting a new project in VSCode. And that makes the screencast not as cool :)

`npm` and other javascripty tools have an init command which creates your basic config file structure. Ideally it would contain all the default options explicitly spelled out, and including documentation inline on how to set the knobs correctly (but I know this is challenging in raw JSON)

the TypeStrong atom editor plugin generates the tsconfig.json, but I didn't find another way (at least in a couple minutes of searching, which is all an end user would do at this point)

**Comment by alexeagle** [comment]
Wider tool support for http://json.schemastore.org/tsconfig might be another way to satisfy this

**Comment by RyanCavanaugh** [comment]
Accepted, accepting PRs. This would be super useful.

Ideally you could write e.g. `tsc --init --module amd foo.ts` and have a tsconfig.json file be emitted that was equivalent to the command line. That opens up an easy migration path.

 :bike: :house: - should the generated file have all the defaults emitted into it so it's easier to change, or be minimal so it's not so large? Or some subset of the common options people want to change?

**Comment by alexeagle** [comment]
for painting the bikeshed: I think the ideal would be to mimic the VSCode
settings UI: a file with comments explaining the settings. That means tsc
needs to pipe the file through JSMin before parsing it (
http://www.quora.com/How-do-I-write-comments-inside-a-JSON-document)
But I think that's a good idea anyway: since a team shares the
`tsconfig.json` as a means to collaboratively configure the build, they
ought to be able to add comments there to explain reasoning, point to bugs,
etc.

Not sure I'll have the time to prepare a PR myself though...

**Comment by mhegazy** [comment]
I do not think we need JSMin, we already have a JS parser/emitter :D

**Comment by mhegazy** [comment]
Thanks @tinganho!
