### ISSUE TITLE
HTMLStyleElement.type is deprecated even though it should not be

### ISSUE THREAD

**Issue by aurelijusrozenas** [Microsoft/TypeScript#30791]
What steps will reproduce the problem?
When using `HTMLStyleElement.type` in javascript it is marked as deprecated
```javascript
const styleElement  = document.createElement('style');
styleElement.type = 'text/css';
```

What is the expected result?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement/type
There is no information that this field is deprecated.

See attachments in https://youtrack.jetbrains.com/issue/WEB-38252

**Comment by cpplearner** [comment]
It's an obsolete feature per the HTML Standard: https://html.spec.whatwg.org/multipage/obsolete.html#dom-style-type

**Comment by MartinJohns** [comment]
TypeScript generally has no way to indicate deprecated elements, and removing it would be a hefty breaking change. #390 is related.

**Comment by chharvey** [comment]
> It's an obsolete feature per the HTML Standard

However, it is not obsolete in the [W3C Recommendation](https://www.w3.org/TR/html52/document-metadata.html#dom-htmlstyleelement-type).

Which specification does TypeScript adhere to: WHATWG or W3C?

**Comment by RyanCavanaugh** [comment]
This is data is sourced from an IDL file we get from the browser. Not really interested in resolving W3C vs WHATWG discrepancies here for the sake of what shows up in the JS Doc.

**Comment by renancaraujo** [comment]
Just for anyone who will come to this thread just like me, as of today, the last HTML spec is this one:
https://html.spec.whatwg.org/multipage/

W3C does not provide HTML specs anymore and HTML 5.2 is no longer valid.

So yeah, it is deprecated.

**Comment by renancaraujo** [comment]
Just for anyone who will come to this thread just like me, as of today, the last HTML spec is this one:
https://html.spec.whatwg.org/multipage/

W3C does not provide HTML specs anymore and HTML 5.2 is no longer valid.

So yeah, it is deprecated as it should be.

**Comment by unphased** [comment]
What does this mean? I'm using the DOM APIs to assemble style tags and want them to be interpreted as CSS by the browser. It definitely still works when omitting setting type. Presumably it's deprecated because CSS is the only type of style that matters ever. Does this mean we should stop setting style="text/css" in our HTML as well?

**Comment by renancaraujo** [comment]
@unphased yes
