### ISSUE TITLE
Generic callable namespace (genric function as namespace)

### ISSUE THREAD

**Issue by akihikodaki** [Microsoft/TypeScript#30792]
## Search Terms

Generic callable namespace (genric function as namespace)

## Suggestion

A namespace will be callable if there is a function with the same name. It would be nice if it is possible with a generic function.

## Use Cases

I think a generic function is as likely as a normal function to have an arbitrary property, and a callable namespace is essential for such a case.

## Examples

For example, consider the following code:

```TypeScript
function n<T>(): T;

namespace n
{
  __promisify__<T>(): Promise<T>;
}
```

It should be equivalent with the following:

```TypeScript
const n: (<T>() => T) & { __promisify__<T>(): Promise<T>; };
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
?

This is already legal:
```ts
function n<T>(x: T): T {
  return x;
}

namespace n
{
  export const m = () => {
    return 5;
  }
}

const a = n(0);
const b = n.m();
```

**Comment by akihikodaki** [comment]
I was running an old version of TypeScript. Sorry for bothering.
