### ISSUE TITLE
regression on `this` type for extended generics

### ISSUE THREAD

**Issue by poseidonCore** [Microsoft/TypeScript#30802]
**TypeScript Version:**  3.4.2

**Search Terms:**
regression on `this` type for extended generics

**Code**
Simplified version of original code:

```ts
// A basic structure whereby a table has records and fields

class Table<IData extends Data> {
    records: IData[];
    fields: Fields<IData>;
}

class Data { 
    s: string;
    b: boolean;
    _table: Table<this>;
}

class Fields<IData extends Data> {
    [key:string]:Field<IData>;
}

class Field<IData extends Data> {
	name: keyof IData;
}

// ----------------------------------------

class SomeData extends Data { 
    n: number;
}

class SomeTable extends Table<SomeData> {
}

/* ERROR blurb
Type 'SomeData' does not satisfy the constraint 'Data'.
  Types of property '_table' are incompatible.
    Type 'Table<SomeData>' is not assignable to type 'Table<Data>'.
      Property 'n' is missing in type 'Data' but required in type 'SomeData'.
*/

```

**Expected behavior:**
Works without error in TS3.3.

**Actual behavior:**
Returns error as above for `class SomeTable extends Table<SomeData> {}`.

When `_table: Table<this>` is changed to `_table: Table<any>`, the problem goes away, but creates loss of type restrictions.

This regression may be related to [this breaking change](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#propagated-generic-type-arguments), but I can't figure out how.

**Playground Link:** 

[TS3.4 Playground @ 07 APR 2019](https://www.typescriptlang.org/play/#src=%2F%2F%20A%20basic%20structure%20whereby%20a%20table%20has%20records%20and%20fields%0D%0A%0D%0Aclass%20Table%3CIData%20extends%20Data%3E%20%7B%0D%0A%20%20%20%20records%3A%20IData%5B%5D%3B%0D%0A%20%20%20%20fields%3A%20Fields%3CIData%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Data%20%7B%20%0D%0A%20%20%20%20s%3A%20string%3B%0D%0A%20%20%20%20b%3A%20boolean%3B%0D%0A%20%20%20%20_table%3A%20Table%3Cthis%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Fields%3CIData%20extends%20Data%3E%20%7B%0D%0A%20%20%20%20%5Bkey%3Astring%5D%3AField%3CIData%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Field%3CIData%20extends%20Data%3E%20%7B%0D%0A%09name%3A%20keyof%20IData%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20----------------------------------------%0D%0A%0D%0Aclass%20SomeData%20extends%20Data%20%7B%20%0D%0A%20%20%20%20n%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20SomeTable%20extends%20Table%3CSomeData%3E%20%7B%0D%0A%7D%0D%0A)

**Related Issues:**

https://github.com/Microsoft/TypeScript/issues/8740

https://github.com/Microsoft/TypeScript/issues/26688

**Comment by jack-williams** [comment]
Think the problem is described here: #30554. Specifically the problem is the name property in Field that flips the variances.

**Comment by poseidonCore** [comment]
Confirmed: using `name: string` instead will circumvent this issue, but does not really resolve the headache.

Thanks, superman.

**Comment by poseidonCore** [comment]
I have put in a bizarre self-referencing hack that shows one way to circumvent the problem with the `this` type:

```ts
// A basic structure whereby a table has records and fields

class Table<IData extends Data<IData>> {
    records: IData[];
    fields: Fields<IData>;
}

class Data<IData extends Data<IData>> { 
    s: string;
    b: boolean;
    _table: Table<IData>;
}

class Fields<IData extends Data<IData>> {
    [key:string]:Field<IData>;
}

class Field<IData extends Data<IData>> {
    name: keyof IData;
    type: "string"|"number"|"boolean";
}

// ----------------------------------------

class SomeData extends Data<SomeData> { 
    n: number;
}

class SomeTable extends Table<SomeData> {
}

var st: SomeTable = new SomeTable();

// This correctly derives from Data:
st.fields.s = {
    name: "s",
    type: "string"
};

// This correctly derives from SomeData:
st.fields.n = {
    name: "n",
    type: "number"
};

// This correctly throws an error:
st.fields.wrong = {
    name: "wrong",
    type: "null"
};
```

[TS Playground](https://www.typescriptlang.org/play/#src=%2F%2F%20A%20basic%20structure%20whereby%20a%20table%20has%20records%20and%20fields%0D%0A%0D%0Aclass%20Table<IData%20extends%20Data<IData>>%20%7B%0D%0A%20%20%20%20records%3A%20IData%5B%5D%3B%0D%0A%20%20%20%20fields%3A%20Fields<IData>%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Data<IData%20extends%20Data<IData>>%20%7B%20%0D%0A%20%20%20%20s%3A%20string%3B%0D%0A%20%20%20%20b%3A%20boolean%3B%0D%0A%20%20%20%20_table%3A%20Table<IData>%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Fields<IData%20extends%20Data<IData>>%20%7B%0D%0A%20%20%20%20%5Bkey%3Astring%5D%3AField<IData>%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Field<IData%20extends%20Data<IData>>%20%7B%0D%0A%20%20%20%20name%3A%20keyof%20IData%3B%0D%0A%20%20%20%20type%3A%20"string"%7C"number"%7C"boolean"%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20----------------------------------------%0D%0A%0D%0Aclass%20SomeData%20extends%20Data<SomeData>%20%7B%20%0D%0A%20%20%20%20n%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20SomeTable%20extends%20Table<SomeData>%20%7B%0D%0A%7D%0D%0A%0D%0Avar%20st%3A%20SomeTable%20%3D%20new%20SomeTable()%3B%0D%0A%0D%0A%2F%2F%20This%20correctly%20derives%20from%20Data%3A%0D%0Ast.fields.s%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20"s"%2C%0D%0A%20%20%20%20type%3A%20"string"%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20This%20correctly%20derives%20from%20SomeData%3A%0D%0Ast.fields.n%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20"n"%2C%0D%0A%20%20%20%20type%3A%20"number"%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20This%20correctly%20throws%20an%20error%3A%0D%0Ast.fields.wrong%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20"wrong"%2C%0D%0A%20%20%20%20type%3A%20"null"%0D%0A%7D%3B%0D%0A%0D%0A)

**Comment by RyanCavanaugh** [comment]
This is a correct error from the type system's POV - `keyof` is contravariant, which fundamentally makes it very difficult to implement a sound class hierarchy that also uses `this` types. I would just replace the definition in `Data` with `_table: Table<Data>;`

**Comment by poseidonCore** [comment]
Thanks for your efforts, Ryan, but this does not really solve the problem.

The mystery is that the type system does actually still do the same inferences and restrictions in the original code as it does in TS3.4, even if it does throw an error here:
```ts
class SomeTable extends Table<SomeData> {}
```
and yet strangely, the error can be overcome without loss of functionality by simply putting in a redundant expression like this:
```ts
class SomeTable extends Table<SomeData & Data> {}
```
Given that `SomeData` is derived from Data, I would have thought that `SomeData & Data` would be just `SomeData `.

[TS3.4 Playground](https://www.typescriptlang.org/play/#src=%2F%2F%20A%20basic%20structure%20whereby%20a%20table%20has%20records%20and%20fields%0D%0A%0D%0Aclass%20Table<IData%20extends%20Data>%20%7B%0D%0A%20%20%20%20records%3A%20IData%5B%5D%3B%0D%0A%20%20%20%20fields%3A%20Fields<IData>%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Data%20%7B%20%0D%0A%20%20%20%20s%3A%20string%3B%0D%0A%20%20%20%20b%3A%20boolean%3B%0D%0A%20%20%20%20_table%3A%20Table<this>%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Fields<IData%20extends%20Data>%20%7B%0D%0A%20%20%20%20%5Bkey%3Astring%5D%3AField<IData>%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Field<IData%20extends%20Data>%20%7B%0D%0A%09name%3F%3A%20keyof%20IData%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20----------------------------------------%0D%0A%0D%0Aclass%20SomeData%20extends%20Data%20%7B%20%0D%0A%20%20%20%20n%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20SomeTable%20extends%20Table<SomeData%20%26%20Data>%20%7B%7D%0D%0A%0D%0Avar%20st%3A%20SomeTable%20%3D%20new%20SomeTable()%3B%0D%0A%0D%0A%2F%2F%20This%20correctly%20derives%20from%20Data%3A%0D%0Ast.fields.s%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20"s"%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20This%20correctly%20derives%20from%20SomeData%3A%0D%0Ast.fields.n%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20"n"%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20This%20correctly%20throws%20an%20error%3A%0D%0Ast.fields.wrong%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20"wrong"%0D%0A%7D%3B)

But apparently, this is correct from the type system's POV, and given the complexities of contravariant vs covariant, I'll leave that to greater minds.

Thanks again.

**Comment by poseidonCore** [comment]
Is there any answer to the inconsistency in my previous comment? Or is this odd/broken state "working as intended" too?
