### ISSUE TITLE
Missing override rule on "lib/lib.es5.d.ts: FunctionConstructor".

### ISSUE THREAD

**Issue by yunbookf** [Microsoft/TypeScript#30806]
**TypeScript Version:**  3.4.1

**Search Terms:**  new Function, FunctionConstructor

**Code**

```ts
interface FunctionConstructor {
    /**
      * Creates a new function.
      * @param args A list of arguments the function accepts.
      */
    new(...args: string[]): Function;
    (...args: string[]): Function;
    readonly prototype: Function;
}
```

**Expected behavior:**

```ts
interface FunctionConstructor {
    /**
      * Creates a new function.
      * @param args A list of arguments the function accepts.
      */
    new(...args: string[]): Function;
    new(args: string[], functionBody: string): Function;
    (...args: string[]): Function;
    readonly prototype: Function;
}
```

**Actual behavior:**

The following code will report an error:

```ts
let func = new Function(["a", "b"], `return a + b`);
```

Error message: Argument of type 'string[]' is not assignable to parameter of type 'string'.

In fact, this writing is allowed, refer to the link:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

I use the Chrome test and I don't have any problems.

**Comment by cpplearner** [comment]
``let func = new Function(["a", "b"], `return a + b`);`` works because `["a", "b"]` is coerced to a string. But it's still a type mismatch, technically.
