### ISSUE TITLE
Generic typing inference composition work as variable not as function

### ISSUE THREAD

**Issue by MasGaNo** [microsoft/TypeScript#30808]
**TypeScript Version:**  3.4.2

**Search Terms:**
Generic variable vs generic function
Generic composition
Generic inference parameter in function 

**Code**
Let's consider this code
```ts
/**
 * Extract object props by a specific value
 */
type PickByValue<T, ValueType> = Pick<T, {
  [Key in keyof T]: T[Key] extends ValueType ? Key : never
}[keyof T]>;

/**
 * Map keys by value-compatibility. Non-recursive.
 */
type MatchKeys<T, U> = {
  [P in keyof T]: keyof PickByValue<U, T[P]>;
};

/**
 * Like keyof, but for value
 */
type ValueOf<A extends Object> = Exclude<A[keyof A], undefined>;

/**
 * The src props we have
 */
export interface SrcPropsInterface {
  srcAttributeString: string;
  srcAttributeNumber: number;
}

/**
 * The dest props we want to apply
 */
export interface DestPropsInterface {
    destAttributesString: string;
    anotherAttributesString: string;
    destAttributesNumber: number;
    anotherAttributesNumber: number;
}
```
In a variable approach, the following code works perfectly with all completion:
```ts
/**
 * Here it's perfectly constraint
 */
type Combi = Partial<MatchKeys<SrcPropsInterface, DestPropsInterface>>;
const comb: Combi = {
    srcAttributeNumber: "anotherAttributesNumber",
    srcAttributeString: 'destAttributesString',
    // toto: 'test' // Error as expected
};
```
![image](https://user-images.githubusercontent.com/5469433/55717810-32818580-5a0b-11e9-8c9d-2ac1ecd000c3.png)

With a generic function approach, we get some weird things:
```ts
declare const obj: DestPropsInterface;

// Try generic way + inference
/**
 * Return a object that exposed the missing attributes that still need to be fill somewhere
 */
function map<
    DestProps,
    T extends Partial<MatchKeys<SrcPropsInterface, DestProps>>
    >(data: DestProps, map: T) {

    // Consider the Proxy code here
    const obj = {} as Pick<DestProps, Exclude<keyof DestProps, ValueOf<T>>>;
    return obj;
}
```
##### Case 1: no completion anymore
```ts
const target = map(obj, {
});
```
![image](https://user-images.githubusercontent.com/5469433/55717588-b129f300-5a0a-11e9-9c35-cf6c0f941c5a.png)
But as soon as I write blindly a known attribute from `SrcPropsInterface`, the type checking work:
```ts
const target = map(obj, {
    srcAttributeNumber: 'anotherAttributesNumber',
    srcAttributeString: 'badValue' // error as expected
});
```
![image](https://user-images.githubusercontent.com/5469433/55717612-c0a93c00-5a0a-11e9-8d97-cf01cc136217.png)
##### Case 2: any-like
We can put any kind of value and there is no complaint (and naturally no completion):
```ts
const target = map(obj, {
    srcAttributeNumber: 'anotherAttributesNumber',
    foo: 'bar',
    bar: 42
});
```
##### Case 3: no output anymore
As soon as the `map` object is correctly fill, the `target` object get correctly all remaining attribute:
```ts
const target = map(obj, {
    srcAttributeNumber: 'anotherAttributesNumber',
});
target.anotherAttributesString; // Ok
target.destAttributesNumber; // Ok
target.destAttributesString; // Ok
target.anotherAttributesNumber; // Error as expected: we already remove it
```
![image](https://user-images.githubusercontent.com/5469433/55717963-96a44980-5a0b-11e9-8b1c-a237b05658db.png)
But if we provide a wrong map because the type checker doesn't provide the correct feedback, `target` is converted as `never`:
```ts
const target = map(obj, {
    srcAttributeNumber: 'anotherAttributesNumber',
    foo: 'bar'
});
```
![image](https://user-images.githubusercontent.com/5469433/55718114-031f4880-5a0c-11e9-98d6-5bbc20b4e4ff.png)

**Expected behavior:**
Case 1: get correct type checker in the `map` parameters like for the `variable` approach
Case 2: I suppose it's just a side-effect of Case 1, but I expect to have TypeScript wiping me by attempting to introduce unknown parameters.
Case 3: I suppose it's just a side-effect of Case 1 and 2.

**Actual behavior:**
Check Case 1, Case 2 and Case 3: no type checking on the generic `map` parameter whereas in a `variable` approach, it works.

**Playground Link:** 
[Playground @ 2019-04-08](https://www.typescriptlang.org/play/#src=%2F**%0D%0A%20*%20Extract%20object%20props%20by%20a%20specific%20value%0D%0A%20*%2F%0D%0Atype%20PickByValue%3CT%2C%20ValueType%3E%20%3D%20Pick%3CT%2C%20%7B%0D%0A%20%20%5BKey%20in%20keyof%20T%5D%3A%20T%5BKey%5D%20extends%20ValueType%20%3F%20Key%20%3A%20never%0D%0A%7D%5Bkeyof%20T%5D%3E%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Map%20keys%20by%20value-compatibility.%20Non-recursive.%0D%0A%20*%2F%0D%0Atype%20MatchKeys%3CT%2C%20U%3E%20%3D%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20keyof%20PickByValue%3CU%2C%20T%5BP%5D%3E%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Like%20keyof%2C%20but%20for%20value%0D%0A%20*%2F%0D%0Atype%20ValueOf%3CA%20extends%20Object%3E%20%3D%20Exclude%3CA%5Bkeyof%20A%5D%2C%20undefined%3E%3B%0D%0A%0D%0A%0D%0A%2F**%0D%0A%20*%20The%20src%20props%20we%20have%0D%0A%20*%2F%0D%0Aexport%20interface%20SrcPropsInterface%20%7B%0D%0A%20%20srcAttributeString%3A%20string%3B%0D%0A%20%20srcAttributeNumber%3A%20number%3B%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20The%20dest%20props%20we%20want%20to%20apply%0D%0A%20*%2F%0D%0Aexport%20interface%20DestPropsInterface%20%7B%0D%0A%20%20%20%20destAttributesString%3A%20string%3B%0D%0A%20%20%20%20anotherAttributesString%3A%20string%3B%0D%0A%20%20%20%20destAttributesNumber%3A%20number%3B%0D%0A%20%20%20%20anotherAttributesNumber%3A%20number%3B%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Here%20it's%20perfectly%20constraint%0D%0A%20*%2F%0D%0Atype%20Combi%20%3D%20Partial%3CMatchKeys%3CSrcPropsInterface%2C%20DestPropsInterface%3E%3E%3B%0D%0Aconst%20comb%3A%20Combi%20%3D%20%7B%0D%0A%20%20%20%20srcAttributeNumber%3A%20%22anotherAttributesNumber%22%2C%0D%0A%0D%0A%7D%3B%0D%0A%0D%0Adeclare%20const%20obj%3A%20DestPropsInterface%3B%0D%0A%0D%0A%2F%2F%20Try%20generic%20way%20%2B%20inference%0D%0A%2F**%0D%0A%20*%20Return%20a%20object%20that%20exposed%20the%20missing%20attributes%20that%20still%20need%20to%20be%20fill%20somewhere%0D%0A%20*%2F%0D%0Afunction%20map%3C%0D%0A%20%20%20%20DestProps%2C%0D%0A%20%20%20%20T%20extends%20Partial%3CMatchKeys%3CSrcPropsInterface%2C%20DestProps%3E%3E%0D%0A%20%20%20%20%3E(data%3A%20DestProps%2C%20map%3A%20T)%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Consider%20the%20Proxy%20code%20here%0D%0A%20%20%20%20const%20obj%20%3D%20%7B%7D%20as%20Pick%3CDestProps%2C%20Exclude%3Ckeyof%20DestProps%2C%20ValueOf%3CT%3E%3E%3E%3B%0D%0A%20%20%20%20return%20obj%3B%0D%0A%7D%0D%0A%0D%0Aconst%20target%20%3D%20map(obj%2C%20%7B%0D%0A%20%20%20%20srcAttributeNumber%3A%20'anotherAttributesNumber'%2C%0D%0A%7D)%3B%0D%0A)

**Related Issues:** 
#28938

**Comment by MasGaNo** [comment]
Btw, everything work perfectly when I set explicitly all generic parameters:
```ts
const target = map<DestPropsInterface, Partial<MatchKeys<SrcPropsInterface, DestPropsInterface>>>(obj, {
    srcAttributeNumber: 'anotherAttributesNumber',
    srcAttributeString: 'destAttributesString',
    foo: 'bar' // Error as expected
});
```

**Comment by MasGaNo** [comment]
Actually, with this approach, I get another strange thing:
```ts
function inject<DestProps>(data: DestProps) {
    return function <SrcProps>() {
        return function <Map extends Partial<MatchKeys<SrcProps, DestProps>>>(map: Map) {
            // Consider the Proxy code here
            const obj = {} as Pick<DestProps, Exclude<keyof DestProps, ValueOf<Map>>>;
            return obj;
        }
    }
}

inject<DestPropsInterface>(obj)<SrcPropsInterface>()({
    srcAttributeNumber: 'anotherAttributesNumber',
    foo: 'bar' // Still doesn't throw error
});
```
I still don't have any completion, but as soon as I write some letters, I remove the hint and ask again for the completion, I get some suggestion:
![chrome-capture](https://user-images.githubusercontent.com/5469433/55720223-61025f00-5a11-11e9-92cc-4322469c0d20.gif)

**Comment by RyanCavanaugh** [comment]
There's a lot going on here I don't understand which part(s) you consider to be the "bug" here - can you simplify this down into a basic example of a small amount of setup + what code you'd expect to error/not error?

**Comment by MasGaNo** [comment]
Ok, I will try to simplify and to isolate which part of the code creates the bug.

**Comment by MasGaNo** [comment]
Just simplified the code, and I think I just figured out the problem, a problem from my side 😓 
So there is no bug directly... I will try to explain with this piece of code:
```ts
function map<T, P extends Partial<T>>(data: T, map: P) {
    return {};
}

interface Props {
    foo: string;
    bar: string;
}
declare const dest: Props;
```
Here if I just write something like, I have as expected some errors:
```ts
map(dest, {
    unknownProps: '',
});
// Argument of type '{ unknownProps: string; }' is not assignable to parameter of type 'Partial<Props>'.
//  Object literal may only specify known properties, and 'unknownProps' does not exist in type 'Partial<Props>'.
```
But as soon as I put a "known" attribute, everything is okay, as it fill the contract of the type as it `extends` the `Partial` type:
```ts
map(dest, {
    bar: '', // Adding at least 1 known property make everything fine
    unknownProps: '', // even adding unknown property
});
```
And changing the definition with this approach:
```ts
function map<T, P = Partial<T>>(data: T, map: P) {
    return {};
}
```
is not helpful at all, as at this moment, P works with inference.

Actually, I wanted to have this effect, but without creating another sub-function and/or passing explicitly all Generic Parameters, but correct me if I'm wrong, seems not to be possible, don't it?: 
```ts
function map<T>(data: T) {
    return function (map: Partial<T>) { };
}

map(dest)({
    bar: '', // Only known attributes are admit
    foo: '',
    // unknownProps: '', // And unknown attribute are correctly rejected as expected
});
```
![image](https://user-images.githubusercontent.com/5469433/55826341-e02e8a80-5b18-11e9-9d87-8efe8244edf9.png)

Buuuuuut, there is still one bug IMHO with the first implementation:
```ts
function map<T, P extends Partial<T>>(data: T, map: P) {
    return {};
}
```
Why don't I have any suggestion?:
![image](https://user-images.githubusercontent.com/5469433/55826032-20d9d400-5b18-11e9-99ea-241ddee61657.png)
Except if I write at least, one letter:
![image](https://user-images.githubusercontent.com/5469433/55826074-3949ee80-5b18-11e9-8eb1-2893ad20da8f.png)
?

**Comment by RyanCavanaugh** [comment]
```ts
function map<T, P extends Partial<T>>(data: T, map: P) {
    return {};
}
```
You don't get suggestions here because `{}` is a valid `P` / `Partial<T>`, so the call is considered 100% valid. Probably you want to define this as `map<T>(data: T, map: Partial<T>)` if possible

**Comment by MasGaNo** [comment]
Yes, I can understand that `{}` is a valid `P`/`Partial<T>`, like when we say:
```ts
interface Props {
    foo: string;
    bar: string;
}

const test: Partial<Props> = {}; // Valid
```
But here, I still having all potential known values:
![image](https://user-images.githubusercontent.com/5469433/55831382-073e8980-5b24-11e9-8fd9-2c09ef819a95.png)
But for development purpose and suggestion, it's very surprising to not having suggestion on all potential values.
It's like with this approach:
```ts
function map<T, P extends (Partial<T> & { a: string })>(data: T, map: P) {
    return {};
}

interface Props {
    foo: string;
    bar: string;
}

declare const dest: Props;
map(dest, {
   // It throws an error as we expect to have at least the required `a: string` attribute 
})
```
Here, we get the full suggestion list:
![image](https://user-images.githubusercontent.com/5469433/55831688-c5faa980-5b24-11e9-978e-dcb7dfc1b77d.png)
But after providing the `a` attribute, suggestion disappear:
![image](https://user-images.githubusercontent.com/5469433/55831721-dca10080-5b24-11e9-930c-01bfb6f9cd89.png)
It's a little bit weird as experience IMHO, and that's make me confused about my first post, as I wasn't focus on the main problem.

What do you think?

**Comment by RyanCavanaugh** [comment]
It's vexing. The language service is asking the checker what the type of the surrounding object literal is in order to show completions. The *valid and correct answer* is `{ a: string }`, so the completion list is *valid and correctly* empty because `a` has already been provided.

Basically we'd need an entirely different *kind* of operation here where the language service would ask the checker, *What property values *would* be valid here?*, which almost requires a sort of counterfactual reasoning that we're really not capable of. For the specific case of `U extends Partial<T>` this is human-understandable, but the type system can't reasonably work backwards through that relationship to understand that the set of property keys for `U` falls back to `T`.

**Comment by MasGaNo** [comment]
> It's vexing.
Sorry, it wasn't my intention ^^" 

I don't really know how exactly the language service works under the hood.

I'm trying a different approach that provide us all what we need. So it's absolutely not a priority in comparison of what you already have in the roadmap 🙂 

Especially when I see the evolution of TypeScript since I started to use it in 2014, it's absolutely fantastic, and I start all my project with it 😀 

Keep continue like that, and we can close this issue if you want 👍

**Comment by johnrom** [comment]
I think I found another instance of this issue. Check out this [TypeScript Playground](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210514&ssl=1&ssc=1&pln=21&pc=30#code/PQKhFgCgAIWhlApgF2gQ2gNzQGwK6LQCWAdumQPYBGAVogMbIA0xJAZogE6ekDm0yABaEADmiHQ2nCgFsBwrLgLpkyRDJHI+AitCqi0AZ0OIAJgDoosaAHVhZMce0AiZyyGFeiElyL1ihtCciIYUOJhm6IEABobIPCS80eSm8niB9GhkPhGc0DLi9ILyhNFoXsmk0AAKXKEkljAgwFDIAJ4ihEjIAGJEiDimAGpKiD0kADwj+CEAfNAAvNBTo0yzABRW0CRoMogAXDXiggAyRADWiNMEKzMs13NMW9gzhw9PkACUi-OYFESmADcUCgpDUnDYaHohFqnHq0AA3ltygdtngZPo8gAfaCuYGQAC+IMg9AoJDi0BMvX6gweh26fQGw1G4wmsPq8yW6x2exYLwI3wW8wRRMgUGAwHkREC0qCITCmG0yF0sRQjNpowmcQSvA2zhRblxzk+gOiLHFktIcUQaFSFDY0FV1KZDwmrj1BpYrhN0SgVPVzJm631XkN3vxFvyWTwuBwbQEHW0RFQAHcKJxzoE2KREH61TTAzd3cHPUaTcSJSU5RS0xnDHnnRqgyHEIaAIzlyD+gsPEuhr3OKJl-Hdl2jPutlhtockdGY6A48MNgOu2cYrgLo0e-vQadGNHr7HD5c9zVr+eL5zbye7zujps3c8by-XsPGkf5sczCZPo-Fltvnen4PogP5zlwr5Tp2FqRgAkhoODqN4yDiEQZLQKYKBoEQOD1pAEqRgAorkbRCNo+g4BQKZSoEtaZu4ChknGUqJPI4gYRQITbBQqbpucARsagAnBKE4RKiq2p8JU5JqLa0D2o6rjRI0BFivhYBWHAADiKCBFk8ZiBICkYLwRARGQDyBNQdCMOY0BaWZ3j7JpmmOpZiyItsuyogikhEHCyCHJJrEEtABJmi5TSOtUxwAPJsLcBCGJyuI8q2m7OGl5jZgFzi+k0LSQIgAAeIjpqg7SdEcQjxYlcwedZDCoCVagkKYgSWVsAD85BtFshw9Dg4itTFQgACp4CIiGGBMABKDB4HCjlxhNU2IKNggzZZszzAAZJS8R8BG6kQFFOnIIEHjQA8KjoNsIRqKkG12Q55nOU0rnRO5Sy+Wlhy+TlcRBYdIVhRFH1RV9owALKFIIfAbXVhhellgPIFeHnBUkmmFSVZWcBVHSEA8sPIEUCPHEjLAbdALXeO11WCLV22clsWO08VrUMxtWzQNAlZEA6NOyvp8l5DkXAsMEyCLWQQjsfu-K5jAfPQD1+m89AhyNYwHNcx1ox4arqsCw67kiyQbRSygsu9ZrfPq5b9ta9dht6-TgTBLaTHxuspAcHk8B8IhDyfAA2gAus7DuM+7bUxAAJAiv4EuYSf+xuAByLUbeF0eqz12eczTdPx4zzOG2Hv4R7M+fGz1JNwxTQhI1X4GcBHLBF8gG21yrxsDy7EucHXLtB4kIejPnhwl5zHvQJcbQKZ1-eD2rrszIYYcbVHq+DzPxxxwz0Tp+wG4ANKIG0qenwH0Dd7n+VrwPPWX-GpcM4vy+G6P9f3znh8P6BA2hXTeYc3411-i-DeBBSbk0SIjSy4Cr6d3-sXY4fdn7P0OMPKBfMcGIFyFAghuRjqgFOtYc6wC4oJW2tAFM8MihHyrMEAAjklR6CZOh2QAII4EoimPSTheAkG0DsbgVENxK0uroSiFATB5EqiEOyABVEwbA8A4EkOmR095CyIGDL+WKnB4Ag14BtQ0v5PjKXso5Eg71YCfW+p5P6B0dQsBRDg9um4sYsCkP0NqABhCgeASCBQPPOcKHxHGQw2mcS4q5273ENilACGV-H02CaE9GT9mhWDxuVLhMJjjxKuJqd4MD6oLCsDrZqc8y4rwLnbfuAsz55FIKYMyAIYxaMMptXmB8aq0JSUfQIfs2mM0+PbSsXsRBTXjKSGSnBsJhPtj1We+ty7DM3pgweDdRijMqXA+GCDKaWWphguu6zjh1xIVwaOdyR570eWQwqlYABCAwqICSIAhJCYTULoUwihHCeFVLig0lFea9BFqGGWgsskuRUC1JkQISa00WA4AuAcSK1hoi-W8v9PyAVgY6jCmDaAABaeY0Qw4AHI0p0ojpueljKWB0rRky3JhUlHQGhbC+Fq1EIbS2iMpY7kgHQHGXfcevBJ4zHDrvB2mtKwpkQHS-h6BTCpAwIYTo9AiC4GgJkEw2jxbt2RpSXQarjVZDlFQPAOFUgeDkCmZMxQAAMRtVY4jDs4D1zglU+ugH6gNLBzARv5UtCIK10XrWODNWV8qCCzCDXzX11dNYZqSdACN5go1wpjW0IV8ahCJuDmUmYqb+qVMCJK6F6ZTBajMR4y2uzlV7xZV-M2hs03BqRJ242yD4xVG7bWiOhxh3hsjQtaNAxi1xpFa3CB1bB1hTDoRTmyzGATDHectxfBV3G0nRHMhkLrCDWGt4NFa0Mhe04VQeMBbBVxrfjKMJugMChLQpQB0fTLVYsuA4ihcBaUMu8kyll4G9h0vZZy6AzLqXQGg+qzcKHsr+TiHS7lrQibQEvaobwG0S0zS2MRuNdb6kM30pHZJWLTDwDwFQJRlHNnsxxL+TGZjNy-igClcjt7DmR26vdIhKtBmCBI0JjOgcK0701j1JNpbiiSumACRjzGiber-ifBESnH7O0eZrCTUnJVhxkzUYI2ZirTvMBZ+acQ+0x2qFZogxVDlqYY0xlj+ceq6Zc4gazN8EQEZGscEjExN3xChMgOaD06Pqe81pyOO085rqM520lR0gA)
