### ISSUE TITLE
Suggestion - Obtaining property type with dot notation on index type

### ISSUE THREAD

**Issue by shivawu** [Microsoft/TypeScript#30815]
## Search Terms

dot notation, index type

## Suggestion

Enable accessing object property type in the type domain, when possible

```
type Obj = {
    x: number;
    y: number;
}

type X = Obj['x'];
// This would be an error, but it's a much more concise/intuitive syntax
type X2 = Obj.x;
```

Note this is not the same as #12596, which is a breaking change.
I'm only suggesting allowing `Obj.propertyName` to be a **type**, 
or as an alias of `Obj['propertyName']`.
`propertyName` must have been known to the compiler, as in the old index type.

One possible drawback is it might cause confusion with accessing objects,
but not that much since when reading TS code, people tend to first look
at which part is the typing and which part is the runtime.

## Use Cases

This applies to all cases where index type is used without mapped types.
It would improve the readability and reduce a lot of syntax noise.

## Examples

Shamelessly copied the code from #17588, and image how this code will look better
with the new syntax :)

[CODE](http://www.typescriptlang.org/play/#src=%2F%2F%20Note%3A%20I've%20specifically%20removed%20the%20fragment-related%20types%20and%20some%20of%20the%0D%0A%2F%2F%20more%20specific%20constraints%20for%20simplicity%0D%0A%0D%0Aexport%20type%20VNode%20%3D%20DOMVNode%3CAttributes%3E%20%7C%20ComponentVNode%3CComponent%3E%3B%0D%0A%0D%0Ainterface%20_Lifecycle%20%7B%0D%0A%09_VNode%3F%3A%20VNode%3B%0D%0A%09_State%3F%3A%20this%3B%0D%0A%0D%0A%09oninit%3F(this%3A%20this%5B%22_State%22%5D%2C%20vnode%3A%20this%5B%22_VNode%22%5D)%3A%20void%3B%0D%0A%09oncreate%3F(this%3A%20this%5B%22_State%22%5D%2C%20vnode%3A%20this%5B%22_VNode%22%5D)%3A%20void%3B%0D%0A%09onbeforeremove%3F(this%3A%20this%5B%22_State%22%5D%2C%20vnode%3A%20this%5B%22_VNode%22%5D)%3A%20Promise%3Cany%3E%20%7C%20void%3B%0D%0A%09onremove%3F(this%3A%20this%5B%22_State%22%5D%2C%20vnode%3A%20this%5B%22_VNode%22%5D)%3A%20void%3B%0D%0A%09onbeforeupdate%3F(this%3A%20this%5B%22_State%22%5D%2C%20vnode%3A%20this%5B%22_VNode%22%5D%2C%20old%3A%20this%5B%22_VNode%22%5D)%3A%20boolean%20%7C%20void%3B%0D%0A%09onupdate%3F(this%3A%20this%5B%22_State%22%5D%2C%20vnode%3A%20this%5B%22_VNode%22%5D)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20Attributes%20extends%20_Lifecycle%20%7B%0D%0A%09_VNode%3F%3A%20DOMVNode%3Cthis%3E%3B%0D%0A%09_Attrs%3F%3A%20this%3B%0D%0A%09_ChildType%3F%3A%20Children%3B%0D%0A%20%20%20%20_Element%3F%3A%20Element%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Children%20types%0D%0Atype%20Foo%3CT%3E%20%3D%20T%3B%0D%0Aexport%20type%20Child%20%3D%20%22A%22%20%7C%20%22B%22%20%7C%20%22C%22%3B%0D%0Aexport%20type%20Children%3CT%20extends%20Child%20%3D%20Child%3E%20%3D%20Foo%3CT%3E%3B%0D%0A%0D%0Ainterface%20_Virtual%3CT%20extends%20string%20%7C%20C%2C%20C%20extends%20Attributes%20%7C%20Component%3E%20%7B%0D%0A%09tag%3A%20T%3B%0D%0A%09attrs%3A%20C%5B%22_Attrs%22%5D%3B%0D%0A%09state%3A%20C%5B%22_State%22%5D%3B%0D%0A%09children%3A%20C%5B%22_ChildType%22%5D%3B%0D%0A%09dom%3A%20C%5B%22_Element%22%5D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20DOMVNode%3CA%20extends%20Attributes%3E%20extends%20_Virtual%3Cstring%2C%20A%3E%20%7B%7D%0D%0Ainterface%20ComponentVNode%3CC%20extends%20Component%3E%20extends%20_Virtual%3CC%2C%20C%3E%20%7B%7D%0D%0A%0D%0Aexport%20type%20ComponentAttributes%3CT%20extends%20Component%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5B%22_Element%22%5D%5D%3A%20T%5B%22_Element%22%5D%5BP%5D%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20Component%20extends%20_Lifecycle%20%7B%0D%0A%09_Element%3F%3A%20HTMLElement%3B%0D%0A%09_Attrs%3F%3A%20ComponentAttributes%3Cthis%3E%3B%0D%0A%09_ChildType%3F%3A%20Child%3B%0D%0A%09_VNode%3F%3A%20ComponentVNode%3Cthis%3E%3B%0D%0A%0D%0A%09view(this%3A%20this%5B%22_State%22%5D%2C%20vnode%3A%20this%5B%22_VNode%22%5D)%3A%20Children%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Later%3A%0D%0Ainterface%20VideoComponent%20extends%20Component%20%7B%0D%0A%20%20%20%20_Element%3F%3A%20HTMLVideoElement%2C%0D%0A%20%20%20%20_Attrs%3F%3A%20ComponentAttributes%3Cthis%3E%20%26%20%7B%20playing%3A%20boolean%20%7D%3B%0D%0A%20%20%20%20_State%3F%3A%20this%20%26%20%7B%20playing%3A%20boolean%20%7D%3B%0D%0A%20%20%20%20_VNode%3F%3A%20ComponentVNode%3Cthis%3E%3B%0D%0A%7D%0D%0Aexport%20const%20Video%3A%20VideoComponent%20%3D%20%7B%0D%0A%20%20%20%20oninit()%20%7B%20this.playing%20%3D%20false%20%7D%2C%0D%0A%20%20%20%20oncreate(vnode)%20%7B%20if%20(this.playing)%20vnode.dom.play()%20%7D%2C%0D%0A%20%20%20%20onupdate(vnode)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20playing%20%3D%20!!vnode.attrs.playing%0D%0A%20%20%20%20%20%20%20%20if%20(playing%20!%3D%3D%20this.playing)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.playing%20%3D%20playing%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(playing)%20vnode.dom.play()%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20else%20vnode.dom.pause()%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%2C%0D%0A%0D%0A%20%20%20%20view(vnode)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20attrs%20%3D%20%7B%7D%0D%0A%20%20%20%20%20%20%20%20for%20(const%20key%20in%20Object.keys(vnode.attrs))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(key%20in%20HTMLVideoElement)%20attrs%5Bkey%5D%20%3D%20vnode.attrs%5Bkey%5D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20return%20m(%22video%22%2C%20attrs)%0D%0A%20%20%20%20%7D%2C%0D%0A%7D%0D%0A)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
This would still be a breaking change, in that this notation conflicts with types inside namespaces or modules:
```ts
declare interface Foo {
    bar: number;
}
declare namespace Foo {
    type bar = string;
}
type FooBar = Foo['bar']; // number
type FUBAR = Foo.bar; // string
```

**Comment by shivawu** [comment]
That's good call. Makes sense.

I was 70% sure there was a reason for not doing this, just failed to find it out via searching. If sharing namespace and local interface/types are a common practice, then we should probably close this.

On the other hand, looks to me that defining a type name starting a lower-case letter is a bad practice already. So maybe practically they shouldn't conflict :)

**Comment by Veetaha** [comment]
I agree with @shivawu there is no need to tolerate such bad practices. Yes, it does is a breaking change, but it doesn't imply that we must drop this proposal. I think that this syntax is more intuitive and concise than indexing with a string literal. When I started with TypeScript I always wanted to extract a property type from some interface with a "dotname" notation and always disappointed when this didn't work.

**Comment by RyanCavanaugh** [comment]
Multiple meanings of the same name are actually pretty common when you import a module, e.g.
```ts
import k from './k';

const t1: k.g = ...; // g means what?
```
The real stickler here is a multiply-dotted name, e.g. `k.a.b.c.d.e` could refer to up to 16 different entities. Name resolution really needs to be unambiguous.

**Comment by shivawu** [comment]
Thanks for explaining! On a side note I would guess the issue was name resolution happens before type checking, so probably at the time of resolution, we don't have the info of "what is this name's, a type, or a module, or something else". Not sure if that's right though :)
