### ISSUE TITLE
Constrained type parameter using indexed access does not satisfy constraint

### ISSUE THREAD

**Issue by Smibu** [Microsoft/TypeScript#30811]
**TypeScript Version:**  3.5.0-dev.20190407

**Search Terms:** constraint constrained type satisfy indexed access parameter

**Code**

```ts
class Class<S extends string> {
    s!: S;
}

type T<Derived extends Class<Derived["s"]>> = Class<Derived["s"]>;
```

**Expected behavior:** Unsure, but TS versions 2.7 through 3.3 report no errors.

**Actual behavior:**

```
test.ts:5:30 - error TS2344: Type 'Derived["s"]' does not satisfy the constraint 'string'.

5 type T<Derived extends Class<Derived["s"]>> = Class<Derived["s"]>;
                               ~~~~~~~~~~~~

test.ts:5:53 - error TS2344: Type 'Derived["s"]' does not satisfy the constraint 'string'.

5 type T<Derived extends Class<Derived["s"]>> = Class<Derived["s"]>;
                                                      ~~~~~~~~~~~~
```

**Playground Link:** https://www.typescriptlang.org/play/#src=class%20Class%3CS%20extends%20string%3E%20%7B%0D%0A%20%20%20%20s!%3A%20S%3B%0D%0A%7D%0D%0A%0D%0Atype%20T%3CDerived%20extends%20Class%3CDerived%5B%22s%22%5D%3E%3E%20%3D%20Class%3CDerived%5B%22s%22%5D%3E%3B%0D%0A

**Related Issues:** Maybe https://github.com/Microsoft/TypeScript/issues/30554 and https://github.com/Microsoft/TypeScript/issues/30802.

**Comment by RyanCavanaugh** [comment]
Circular type constraints are illegal and are now more often correctly detected as of 3.4.
