### ISSUE TITLE
inheritance of generic methods

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#30810]
**TypeScript Version:**  3.3.3

**Search Terms:** inheritance inherits generic generics methods functions

**Code**

```ts
class A
{
    public f<T, TMember extends keyof T>(x:T, y:TMember)
    {

    }
}

class B extends A
{
    public f<T, TMember extends keyof T>(x:T, y:TMember)
    {
        
    }
}
```

**Expected behavior:**
Compiles fine
**Actual behavior:**
compilation error ts 2416
**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment]
Duplicate of #25373?

**Comment by npenin** [comment]
indeed, I did not see this one
