### ISSUE TITLE
JS intellisense is slow for alias imports

### ISSUE THREAD

**Issue by askerpro** [microsoft/TypeScript#30820]
- VSCode Version: 1.23.3
- OS Version: windows 10 64

Steps to Reproduce:

1.Add path aliases to jsconfig.json

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {

      "Components/*": ["./app/Components/*"],
      "Pages/*": ["./app/Pages/*"],
      "GlobalElements/*": ["./app/Components/Globals/elements/*"],
      "Utils/*": ["./app/Utils/*"]
    }
  },
  "include": [
    "app/**/*.js"
  ]
  
}

```
2.Try to import one of aliases (takes about 30sec)

![alias](https://user-images.githubusercontent.com/8836553/55447017-b9c59800-55ca-11e9-9f34-e2097bd6b220.gif)

Does this issue occur when all extensions are disabled?: Yes

And import example with no alias takes about 0.1s
![no_alias](https://user-images.githubusercontent.com/8836553/55447024-c1853c80-55ca-11e9-9695-06b8faae4b94.gif)

And here ts server log files (zipped)
[tsserver.zip](https://github.com/Microsoft/vscode/files/3036494/tsserver.zip)

**Comment by mjbvz** [comment]
Moving upstream as I do see a very long running `completionInfo` request from the logs:

```
Info 2518 [4:6:17.634] request:
    {"seq":392,"type":"request","command":"completionInfo","arguments":{"file":"d:/Dev/Web/berta-react/client/app/index.js","line":14,"offset":31,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}
Info 2519 [4:6:17.635] Starting updateGraphWorker: Project: d:/Dev/Web/berta-react/client/jsconfig.json
Info 2520 [4:6:26.607] Finishing updateGraphWorker: Project: d:/Dev/Web/berta-react/client/jsconfig.json Version: 64 structureChanged: true Elapsed: 8972ms
...
Perf 2523 [4:6:26.622] 392::completionInfo: elapsed time (in milliseconds) 8987.6608
```

This was with TS 3.3.3

**Comment by askerpro** [comment]
> Moving upstream as I do see a very long running `completionInfo` request from the logs:
> 
> ```
> Info 2518 [4:6:17.634] request:
>     {"seq":392,"type":"request","command":"completionInfo","arguments":{"file":"d:/Dev/Web/berta-react/client/app/index.js","line":14,"offset":31,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}
> Info 2519 [4:6:17.635] Starting updateGraphWorker: Project: d:/Dev/Web/berta-react/client/jsconfig.json
> Info 2520 [4:6:26.607] Finishing updateGraphWorker: Project: d:/Dev/Web/berta-react/client/jsconfig.json Version: 64 structureChanged: true Elapsed: 8972ms
> ...
> Perf 2523 [4:6:26.622] 392::completionInfo: elapsed time (in milliseconds) 8987.6608
> ```
> This was with TS 3.3.3

In addition, i've noticed that, intellisense stops working (or starts lagging) only on import statements.
It works pretty well before I'll try to import some of my aliases, and sometimes it shows aliases suggestions really fast (0.1 - 0.5s), but sometimes it just stop showing any suggestions, and after it doen's work at all, not only with imports.
I've noticed that it happens only in my project, when I opened react-create-app with vscode, everything worked fast. But when I mooved my project files into react create app, intellisense suggestions started lagging. My project is not really big (about 50 js files). If you wold like, I can share my repo in a private.

**Comment by askerpro** [comment]
> Moving upstream as I do see a very long running `completionInfo` request from the logs:
> 
> ```
> Info 2518 [4:6:17.634] request:
>     {"seq":392,"type":"request","command":"completionInfo","arguments":{"file":"d:/Dev/Web/berta-react/client/app/index.js","line":14,"offset":31,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}
> Info 2519 [4:6:17.635] Starting updateGraphWorker: Project: d:/Dev/Web/berta-react/client/jsconfig.json
> Info 2520 [4:6:26.607] Finishing updateGraphWorker: Project: d:/Dev/Web/berta-react/client/jsconfig.json Version: 64 structureChanged: true Elapsed: 8972ms
> ...
> Perf 2523 [4:6:26.622] 392::completionInfo: elapsed time (in milliseconds) 8987.6608
> ```
> This was with TS 3.3.3

What is the possible reason of this long requests?

**Comment by liyuanqiu** [comment]
I met the same problem, `completionInfo` costs a very long time, any solution?

My environment:
- VS Code: 1.33.1
- Typescript: 3.4.5
- Project: create-react-app 3.0 for typescript

**Comment by padys** [comment]
Try to change source of TypeScript SDK for VSCode -> add this line to your VSCode settings:
```
"typescript.tsdk": "node_modules/typescript/lib"
```
It uses TS directly from your project.

**Comment by sheetalkamat** [comment]
@askerpro The original logs shared are from 3.3.3. We would want you try 
using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) and see if this issue still repros. If it does, please share new logs. Thanks

**Comment by AkhmedovValikhan** [comment]
Having the same but with non-relative import in typescript, for new files it is not even working, until I restart vscode or in 10-15 mins

**Comment by mjbvz** [comment]
Closing this issue as out of date

If you are still seeing issue with the current TypeScript release, please open a new issue so that we can investigate
