### ISSUE TITLE
Intellisense for TypeScript Monorepo stops working after a few mintues

### ISSUE THREAD

**Issue by christiango** [microsoft/TypeScript#30822]
The Office Online team has a TypeScript monorepo managed by [Rush](https://rushjs.io/). The repository has over 50 packages in it, some of which are interconnected. References to other packages in the repo are not handled with TypeScript project references, but are instead linked by Rush using symbolic links.

Very recently, we started noticing that after just a few minutes the intellisense for Typescript in VSCode stops working and our developers are having to reboot constantly to get intellisense back in a good state.

We're using Typescript 3.2.2 and all our developers are on Windows machines.

**Comment by mjbvz** [comment]
Moving upstream as this appears the be a TS issue. I can't repo it though by making random edits and opening random files in the project

One thing I noticed is that the root tsconfig does not have an excludes/includes section. May be worth adding one just to ensure that any file that is not part of a project does not trigger TS to try loading a very large number of files into a single project

Also, the TS Server logs may be helpful to identify when and why the stall happens:


1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

If you can send the logs by email I can see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this

**Comment by christiango** [comment]
Fair enough, it seems to happen less after we moved to project references.
