### ISSUE TITLE
collections framework for TS

### ISSUE THREAD

**Issue by MikeMitterer** [microsoft/TypeScript#30827]
## Search Terms
collection framework map hashmap dictionary linkedlist queue 

## Suggestion
I know it should't be a language designers task to provide a collection framework but compared to other languages TS has really poor support for collections. Only pure JS Array or Map. Thats a joke if you are coming from another language. There are some third party libs out there but such a fundamental lib should come directly from MS 

## Examples
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/index.html
https://api.dartlang.org/stable/2.2.0/dart-collection/dart-collection-library.html

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> [x] This feature would agree with the rest of TypeScript's Design Goals.

No, it would not. It would directly go against the [non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals) number 6:

> Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

**Comment by Veetaha** [comment]
It is not the TypeScript concern, it only provides static type information and some rudimental runtime type information like `emitDecoratorMetadata`. Some 3-d parties have even stronger typing than vanilla collections, so I personally use ['typescript-collections'](https://www.npmjs.com/package/typescript-collections) when canon collections are not enough.

**Comment by MikeMitterer** [comment]
Hmmm, yea thanks. I'm also using typescript-collections but I thought at least such a fundamental thing like (basic) collections should be part of the language.
