### ISSUE TITLE
Poor error message elaborations for array-like types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#30839]
```ts
let point = [3, 4] as const;

function distanceFromOrigin([x, y]: [number, number]) {
    return Math.sqrt(x ** 2 + y ** 2);
}

distanceFromOrigin(point);
```

```
Argument of type 'readonly [3, 4]' is not assignable to parameter of type '[number, number]'.
  Type 'readonly [3, 4]' is missing the following properties from type '[number, number]': pop, push, reverse, shift, and 6 more.
```

![image](https://user-images.githubusercontent.com/972891/55844253-727b6200-5b0a-11e9-970f-88ec5ba25339.png)

This is bad to show to beginners. Here's a few things we could be doing better.

1. If a source type is a `ReadonlyArray` (for all `E`), and a target type is an `Array`, then give a specialized error message that `ReadonlyArray`s can't be assigned to `Array`s.

   ```
   A 'ReadonlyArray' cannot be assigned to an 'Array' because 'Array's can be mutated.
   ```

2. If the source type is a `readonly` tuple, and the target is a plain tuple or array-like type...

   ```
   A 'readonly' tuple cannot be assigned to a mutable array-like type.
   ```

3. If one side is a tuple type, and the other isn't array-like, just don't elaborate at all. Nobody cares about missing `push`, `pop`, and 6 other members...

**Comment by jack-williams** [comment]
Fix up: #30916
