### ISSUE TITLE
Multi-catch support

### ISSUE THREAD

**Issue by brunoc107** [microsoft/TypeScript#30830]
Hello, everyone

I've been working with typescript quite a wile since i've first found it, and it's one of the coolest piece of technology i've ever used. But I think it could be cooler if we had a better way of handling errors. I mean, we could leverage the functionality of the language's try-catch.
Sometimes we need to handle some errors in specific ways that do not apply to others and the current language does not support a more strait forward way of doing it.
Today, we need to do something like this:
``` typescript
try {
	// Here we throw CustomError
	someOperation();
	// Here we throw AnotherCustomError
	anotherOperation();
} catch (e) {
	if (e instanceof CustomError) {
		// Custom handling
	} else if (e instanceof AnotherCustomError) {
		// Another custom handling
	} else {
		// Default error handling
	}
}
```
I think it could be better. We could add support to "multi-catch" to the language. The code that follows should be transpiled to the code seen before:
``` typescript
try {
	// Here we throw CustomError
	someOperation();
	// Here we throw AnotherCustomError
	anotherOperation();
} catch (e: CustomError) {
	// Custom handling
} catch (e: AnotherCustomError) {
	// Another custom handling
} catch (e) {
	// Default error handling
}
```
What do you think about it, guys?
I think it would be a joy to see it working!

Regards :)

**Comment by nmain** [comment]
This fails on at least two points from the template that you deleted:

* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)

As it would require both extra runtime code to be emitted (generating if...else instanceof code for you) and for that generated code to depend on the type annotations in the source.

**Comment by brunoc107** [comment]
I did read the template, and I was aware of that violations, but I thought the benefit of this approach to write error handling code should be exposed. 
Anyway, its understandable that a feature can't enter to the project if it violates the project rules.
Just thought I should give it a try :)

**Comment by mikoloism** [comment]
@brunoc107 I think this is nice proposal but in parsing we can manage developer code and parsed code!

But maybe we can add another new try/catch keyword like try/match or anything else, what do you thinks?

**Comment by brunoc107** [comment]
@mikoloism It could be a valid way of allowing "multi-catch" support. I think that would solve the "problem" I had when I first open this issue.
