### ISSUE TITLE
Disallow method calls from within constructors

### ISSUE THREAD

**Issue by HaKr** [Microsoft/TypeScript#30834]
## Search Terms
call virtual methods from a constructor

## Suggestion

The typescript compiler should give an error when a method call is made in a constructor, or at least it should be a configurable error.

## Use Cases

Calling (virtual) functions from a constructor is dangerous, and in Javascript, all functions can be virtual. This could be also lead to errors when someone extends a class from a class that was made outside his project's code base.

## Examples
Even with all private members and methods, it can go wrong, see [the Typescript implementation of the Hitchhiker's supercomputer](https://www.typescriptlang.org/play/#src=class%20DeepThought%0D%0A%7B%0D%0A%20%20%20%20private%20sixTimesNine%3A%20number%0D%0A%20%20%20%20private%20calculatedAnswer%3A%20number%0D%0A%0D%0A%20%20%20%20constructor()%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this.calculatedAnswer%20%3D%20this.computeAndCheck()%0D%0A%20%20%20%20%20%20%20%20this.sixTimesNine%20%3D%2042%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20get%20answerToTheUltimateQuestionOfLifeUniverseAndEverything()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.calculatedAnswer%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20computeAndCheck()%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.sixTimesNine%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20deepThought%20%3D%20new%20DeepThought()%0D%0A%0D%0Aconst%20message%20%3D%20%22The%20answer%20to%20the%20Ultmate%20question%20about%20Life%2C%20%22%20%2B%0D%0A%20%20%20%20%22the%20Universe%20and%20Everything%20is%22%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0Aconsole.log(%60%24%7Bmessage%7D%3A%20%24%7BdeepThought.answerToTheUltimateQuestionOfLifeUniverseAndEverything%7D%60)%0D%0A)
or [this more abstract example that generates a type error](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20private%20b%3A%20number%5B%5D%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.c()%0D%0A%20%20%20%20%20%20%20%20this.b%20%3D%20%5B%5D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20c()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.b.push(1)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Anew%20A())

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code,
        when it's made a configurable error
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by zpdDG4gta8XKpMCd** [comment]
i see the problem but how you define "virtual" in typescript?

**Comment by RyanCavanaugh** [comment]
I don't see how this could get turned into anything useful in practice. You can arrange a similar sequence of incorrect calls outside of a constructor, too, but the problem here is the contractual relationship between the base class and its derived classes, not the location of those calls.

**Comment by zpdDG4gta8XKpMCd** [comment]
lastly it's rather a straightforward thing to do for a linter: to prevent calling methods from a constructor
i bet i can write this rule for $50, what's your bet?

**Comment by HaKr** [comment]
> You can arrange a similar sequence of incorrect calls outside of a constructor, too

How could you do that, without the compiler complaining?

**Comment by HaKr** [comment]
Why would you want to delegate this to a linter? 
The compiler does not allow 
`class C { x:T; constructor(){} }`
as it leaves the x being `undefined`.
Similarly, the es6 compiler does allow, but it will give a runtime error
`class E extends C { y:Y; constructor() { this.y=42; super() } }`
because the `this` isn't yet fully defined

So, since all methods are possibly `virtual`, this need not be explicitly defined, nor is it a problem. But you can end with runtime errors, although you think you do keep up with the contractual relationship between the base class and its derived classes.

**Comment by HaKr** [comment]
> what's your bet?

I honestly would not have a clue as how to write a linter rule, so I better not bet ;-)

**Comment by zpdDG4gta8XKpMCd** [comment]
linting rules are generally easy to write, they have a huge return on investment ratio, i say if you spend an evening of your weekend writing a rule you will save hours of worry free time down the road

try it
