### ISSUE TITLE
Disallow default parameter values before required parameters

### ISSUE THREAD

**Issue by JakeTunaley** [Microsoft/TypeScript#30842]
## Search Terms

default required parameter parameters value values

## Suggestion

TS infers `foo` in the following code to have the type `(bar: string, b: any) => void`:

```ts
var a = 'var a';
var b = 'var b';

function foo (bar = a, b) {}
```

i.e. it considers `bar` to be a required argument, even though a default value was specified. We get the standard "too few arguments" errors if we try to omit `bar` at call-time.

```ts
foo('arg1');
// ~~~~~~~~ Expected 2 arguments, but got 1.

foo('arg1', 'arg2');
```

A more useful error to have here would be at the function definition:

```ts
function foo (bar = a, b) {}
//                     ~ A required parameter cannot follow an optional parameter.
```

This is the error we would get if we specified bar as an optional parameter instead of using a default argument:

```ts
function foo (bar?: any, b) {}
//                       ~ A required parameter cannot follow an optional parameter.
```

## Use Cases

With this extra error we now know we've made a mistake while we're writing the function, instead of whenever it gets used (which may not be anywhere in your code if it's a library function).

This also disambiguates this case of two parameters from using the comma operator in a default value expression, without having to rely on syntax highlighting to make operator precedence clear:

```ts
function foo (bar = (a, b)) {}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

For functions that get defined and not used anywhere this will be a breaking change (an error now exists where there previously was none), but this is a good break because TS would have generated an error as soon as someone tried to use the function with only one argument anyway.

**Comment by trotyl** [comment]
> We get the standard "too few arguments" errors if we try to omit `bar` at call-time.

You're responsible to maintain the argument position in any case, so that if the first parameter is optional, then an explicit `undefined` is needed:

```javascript
foo(undefined, 'arg2');
```

Also this is a common and valid design, all Redux reducer have the first optional parameter.

**Comment by RyanCavanaugh** [comment]
As mentioned above, this has well-defined semantics in JavaScript.

**Comment by JakeTunaley** [comment]
Ah, I see, I forgot to turn on strict null checks while testing this. I understand now, thanks @trotyl!

**Comment by cpplearner** [comment]
`function foo (bar = a, b) {}` is transpiled to `function foo (bar, b) { if (bar === void 0) { bar = a; } }`when targeting ES5, so `foo(undefined, 'arg2');` works. But in ES6 and above, the default argument is not used and `bar` is `undefined`.

This seems to be an undesirable surprise when targetting ES6 or above.
