### ISSUE TITLE
TS does not auto-detect static method return type from "return" statement

### ISSUE THREAD

**Issue by DmitryKoterov** [Microsoft/TypeScript#30859]
...although for e.g. non-static methods it works.

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** typescript static method return type automatic (and other variants)

**Code**

```ts
class Base {
  static ff(): "aa" | "bb" {
    return "aa";
  }
}

const BaseEx = Base as typeof Base & { ff(): "aa" | "bb" };

// Does not work
class Derive extends BaseEx {
  static ff() {
    return "bb";
  }
}

// Works only when ff() return type is manually specified
class Derive2 extends BaseEx {
  static ff(): "bb" {
    return "bb";
  }
}
```

**Expected behavior:** Both Derive and Derive2 should be correct: they do the same thing, and also it would work if the method was not static.

**Actual behavior:** Derive doesn't compile, the error is:

```
Class static side 'typeof Derive' incorrectly extends base class static side 'typeof Base & { ff(): "aa" | "bb"; }'.
  Type 'typeof Derive' is not assignable to type 'typeof Base'.
    Types of property 'ff' are incompatible.
      Type '() => string' is not assignable to type '() => "aa" | "bb"'.
        Type 'string' is not assignable to type '"aa" | "bb"'.
```

**Playground Link:** https://bit.ly/2IqtKnA

**Related Issues:** found nothing

**Comment by RyanCavanaugh** [comment]
The example is overcomplicated. You can observe the same thing here:
```ts
class Base {
  ff(): "aa" | "bb" {
    return "aa";
  }
}

// Does not work
class Derive extends Base {
  ff() {
    return "bb";
  }
}
```
The issue here is that the `return "bb";` statement isn't affected by the base class type, so TS treats `Derived#ff()` as returning the widened form `string` (which isn't assignable *to* `"aa" | "bb"`.

You can write `return "bb" as const;` to indicate that the return type should be treated as a literal.

See also #1373

**Comment by DmitryKoterov** [comment]
Thank, sorry for the duplicate. 

In the future, shouldn't `return "bb"` be automatically treated as `return "bbb" as const` in all cases, since `"bb"` as a type is always castable to a string, but strings are not castable to such variant types? Or it will break compatibility?

```ts
function fun() {
  return "aa";
}
const res = fun();
// res is string
```

**Comment by RyanCavanaugh** [comment]
Consider if you wrote something like this:
```ts
class A {
  getDefaultName() { return "Q" };
}
const a = new A();
const b = { name: a.getDefaultName()) };
if (someCond) {
  b.name = "Something else";
}
```
Is it appropriate to error here and say `Cannot assign "something else" to "Q"` ? Not really. Functions returning strings are usually returning *arbitrary* strings that should be treated as having unknown content; you should generally have to "opt in" to a literal meaning.

**Comment by RyanCavanaugh** [comment]
Or alternatively:
```ts
class A {
  getDefaultName() { return "A" }
}
class B extends A {
  getDefaultName() { return "B" }
}
```
Does `B` illegally violate `A`'s contract by failing to return the literal value `"A"` from its overriding method? Really doesn't seem like it...

**Comment by DmitryKoterov** [comment]
Thanks.
