### ISSUE TITLE
Object spreading restrictions are inconsistent "Spread types may only be created from object types."

### ISSUE THREAD

**Issue by vartan** [microsoft/TypeScript#30851]
**TypeScript Version:**  3.3.3

```ts
function unsafeSpread<T extends number>(arg: T) {
  return {...arg}; // why isn't this an error
}
let val = 1;
let spreadVal = {...val}; // but this is
let unknownVal: unknown = 1;
let unknownSpreadVal = {...unknownVal}; // and this is not

```

**Expected behavior:**
"Spread types may only be created from object types." should be thrown whenever non-objects are spread.

**Actual behavior:**
unknown and generics can be spread regardless

**Playground Link:** 
https://www.typescriptlang.org/play/#src=function%20unsafeSpread%3CT%20extends%20number%3E(arg%3A%20T)%20%7B%0D%0A%20%20return%20%7B...arg%7D%3B%20%2F%2F%20why%20isn't%20this%20an%20error%0D%0A%7D%0D%0Alet%20val%20%3D%201%3B%0D%0Alet%20spreadVal%20%3D%20%7B...val%7D%3B%20%2F%2F%20but%20this%20is%0D%0Alet%20unknownVal%3A%20unknown%20%3D%201%3B%0D%0Alet%20unknownSpreadVal%20%3D%20%7B...unknownVal%7D%3B%20%2F%2F%20and%20this%20is%20not%0D%0A

**Related Issues:** 

did not find any in the first couple pages when searching

**Comment by jack-williams** [comment]
Also raised [here](https://github.com/Microsoft/TypeScript/pull/28234/files#r230465223). I suspect this might be a bug?

**Comment by collin5** [comment]
I've created a PR that attempts to resolve the first scenario (spread on `T`) https://github.com/Microsoft/TypeScript/pull/31185. However, I'm still a little concerned about restricting spreading for `any` and `unknown` types as there is a possibility of this being a breaking change.

**Comment by orta** [comment]
I think it's fine to allow spreading on an `any` - `unknown` I think should fail. No need to add that in https://github.com/microsoft/TypeScript/pull/31185 (but if you, dear reader, might be interested in raising your own PR for that - I'd help get that in )

**Comment by collin5** [comment]
Sure. I can have a PR for this by end of this weekend. Thank you.

**Comment by fatcerberus** [comment]
`any` in almost all contexts means "disable all type checking for this"; it would IMO be weird if it disabled spreading.
