### ISSUE TITLE
{} should not be equivalent to any

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#30862]
**TypeScript Version:**  3.4.3

**Search Terms:** `{} object` `{} non-primitive` `empty interface object` `empty interface non-primitive`

**Code**

```ts
type EmptyObject1 = {};
let a: EmptyObject1;
a = { a: 1, b: 2, c: 3 };
a = [1, 2, 3];
a = 123;
a = '123';
a = true;
a = null;
a = undefined;

interface EmptyObject2 { };
let b: EmptyObject2;
b = { a: 1, b: 2, c: 3 };
b = [1, 2, 3];
b = 123;
b = '123';
b = true;
b = null;
b = undefined;
```

**Expected behavior:**
Compiled error.
Type `{}` should only be assignable by value `{}` (empty Object).

**Actual behavior:**
Compiled successfully.
Just like type `{}` is equivalent to type `any`

**Playground Link:** 

**Related Issues:**

**Comment by jack-williams** [comment]
`{}` is not equivalent to `any` in many ways, including the fact that `undefined` and `null` are assignable to `any`, but not `{}` (under `--strictNullChecks`).

The type `{}` should not be read as the empty object type; it should be read as the type that puts exactly zero constraints on the value, other than it must be defined (non-null). This is why primitive values are assignable to `{}`.

In modern typescript `{}` is almost never the right type you want, so if you find yourself using it, it might be worth trying to replace it with something like `unknown`, `any`, or `object`.

FAQ: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces
