### ISSUE TITLE
how can i get a contextual type of a function result?

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#30865]
```ts
function thusMyClass() {
    return class {
    };
}
```

now, using typescript api, i am given `declaration: ts.FunctionDeclaration` node of the `thusMyClass` function with `declaration.type` being undefined, how can i get the contextual type of a function declaration?

**Comment by RyanCavanaugh** [comment]
`getContextualType` would be the function to call, but function declarations aren't subject to contextual typing. The expression of the return statement would be contextually typed by a return type annotation if one existed, though.

**Comment by zpdDG4gta8XKpMCd** [comment]
...bad day

**Comment by zpdDG4gta8XKpMCd** [comment]
what if i have 10 return statements, how do i get the resulting type combining them all?

**Comment by RyanCavanaugh** [comment]
Call `getTypeAtLocation` either on each return statement expression (and combine them using whatever "combine" means to you), or call it on the declaration to and inspect the return type (to get the compiler's view of the world)
