### ISSUE TITLE
Detect + Prevent Problematic Files on DefinitelyTyped

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#30866]
## Overview

We experienced a bad UX break in 3.4 because a couple of correctness fixes related to conditional types resulted in more eager evaluation of some types in `styled-components` that caused typing delays of 2.5 seconds or longer, even in JS files.

Distributive conditional types are making it pretty easy these days to accidentally introduce `O(n^2)` or even `O(n^3)` type instatiations or comparisons on objects of `n` properties, and React in particular presents a commonly-used type with `n > 100`. We need to detect files that potentially introduce large performance hits, and prevent them from ending up on `@types`

## Metrics

Key things we care about, in priority order:
 1. Typing performance. Including a .d.ts file and consuming it through normal means should not introduce edit delays > 100ms in any case. A "good" definition for a simple library can easily achieve < 10ms completions, for example.
 2. Batch performance in implementation files: A consuming ts/js file should not incur long build time impact. This is important for `// @ts-check` and TS editing scenarios since semantic diagnostic fetching for a file is effectively a batch compile operation.
 3. Memory pressure: .d.ts files under normal use shouldn't allocate "too many" types or relational comparisons
 4. Batch performance in declaration files: Somewhat less important because it doesn't affect JS interactivity or TS consumption with `--skipLibCheck`, the .d.ts file itself should be relatively fast to check

We can't measure some of these things without representative implementation files. Having a test file that exercises the full range of behavior described by the .d.ts file is important. We need to also provide a way to measure the "code coverage" of a test file; making this information easily surfaced and consumed to PR authors should also encourage better test authoring.

## Informing Correctness/Performance Trade-offs

Some libraries are legitimately more complex than others, but the key thing here is definition authors are *informed* about how much a change they make increases the perf cost of consuming the definition. We should install some hard gates (no frequent typing delays over 500ms, for example), but generally the goal here is to simply allow everyone to make these trade-offs in an informed way.

## Version-to-version behavior

With any of these metrics, we'll want the ability to get version-over-version metrics on an as-needed basis. This will become one of our release activities - ensuring that we don't incur the same regression we did in 3.4.

**Comment by andrewbranch** [comment]
Putting out a rough plan to solicit feedback:

## Goal: Make sure a new TypeScript version is ok

- When a PR to DefinitelyTyped is merged (or on frequent schedule):
  - Find changed packages and their dependencies (like types-publisher)
  - Run benchmarks against those with latest stable TS version
  - Maybe: re-run benchmarks with typescript@next and warn if it’s wildly worse—if a problematic change to TypeScript itself occurs, this will help narrow down when the regression occurred
  - Publish benchmark results
- When we want to make sure a new version of TypeScript won’t have perf regressions with DT:
  - Run one-off benchmark with typescript@master against sample of packages that have a benchmark from the latest stable
  - Compare benchmark results from master with results for latest stable

## Goal: Make sure a DefinitelyTyped PR is ok

- When a PR to DefinitelyTyped is opened:
  - Pull latest benchmarks for that package and its dependencies
  - Install same version of TypeScript as last run
  - Run benchmarks on PR source
  - Compare with latest benchmark
  - Warn/fail if anything regressed too much or went over hard limits

## Components

- Benchmark a single package with a given TS version (wrote most of this already)
  - [x] Expose type count and relation cache sizes from checker
  - [x] Measure language service execution times for quick info and completions _N_ times at every identifier in every test file
  - [x] Calculate means, standard deviations, etc. and captures more info about the worst location for quick info and completions
  - [ ] Measure/expose how well the type definitions are covered by the tests
- Azure Pipelines build definition to run benchmarks against changed packages periodically with latest stable TypeScript version
   - Detect changed packages and dependencies (exists in types-publisher)
   - Write results to JSON
   - Should also be able to be manually triggered with a specific set of packages and/or specific TypeScript version
- Publish benchmark results
   - Choose storage—Cosmos DB or blob storage? Blob storage is cheaper, and JSON blobs are accessible without any API layer for easier inspection. But, we’d like to be able to index both by TypeScript version and DefinitelyTyped version. Without doing that, certain queries could be really slow.
   - Design schema or file structure
   - Write script to do the upload
- Benchmark retrieval
   - Likely minimal work is needed here—we can use public REST APIs for either blob storage or Cosmos DB
- Benchmark comparison
   - Decide what thresholds (relative and absolute) should trigger warnings / build failures etc.
   - Write script to run comparison and generate summary
- Azure Pipelines build definition to run benchmarks against PR’d package and compare
   - Query existing benchmarks and pull
   - Do similar process outlined in other build definitions
   - Probably don’t want to block builds at first—maybe post a comment on the PR with results?
- Determine test coverage of a definition file
   - Probably needs work in the checker to be exposed
   - Surfaced by dts-lint: `$ExpectCovered ./index.d.ts`?
- Some interface to analyze/summarize/explore existing data (another place where it helps to have benchmark data easily queryable)

## Concerns

- Benchmarks can take a long time to run (it would take several days to benchmark all of DefinitelyTyped).
  - Could prioritize popular packages
  - Could limit how many positions language service is tested, sampling deterministically
  - Could parallelize aggressively (how many agents can we use?)
- Determining coverage seems complex—@sandersn has helped toss around some ideas, but I don't have a solid idea of how this will work yet
- Cost of compute time and data storage
- Lots of useful code that could contribute to this is distributed between dtslint, dtslint-runner, and types-publisher. dtslint-runner and types-publisher already have some effort duplicated between them. It would be great to have a generalized “DefinitelyTyped-harness” package that can run arbitrary things against certain matrices of DefinitelyTyped versions, DefinitelyTyped packages, and TypeScript versions. types-publisher is fairly complex though, and extracting useful stuff out of it might be a bigger task than it’s worth.

## Next steps

If this plan sounds like it’s heading in the right direction, my first steps will be to set up:

1. a place for storing benchmarks
2. a script for publishing benchmarks to that place
3. a build definition (manually triggered for now) that can run a benchmark of package _X_ of DefinitelyTyped@master with TypeScript version _Y_.

**Comment by RyanCavanaugh** [comment]
This looks like a solid plan. Obviously still there are some open questions to be hammered out, but I think the important part is to get something up and running that can detect large regressions (either from user PRs or our own changes) sooner rather than later. The coverage aspect is only something I really care about because the improvements in the test file will almost certainly cause type counts to go up without actually indicating a regression in the .d.ts file performance, so we need to be able to identify when thant's happening.

For handling the large size of DT, we can probably get away with running the popular packages nightly and running less-popular packages on a rolling basis (e.g. divide into sevenths and run on a given day).

The other high-order bit is surfacing the data in a way that the DT bot can quickly consume it and publicize those results in the PR description. I don't have a lot of context on the various Azure storage options, so I just mention it as something to keep in mind.

I'd recommend talking with Wes and Ron about their work on the typescript-bot RWC / DT runners as well, since that's been a successful model so far.

**Comment by weswigham** [comment]
> a place for storing benchmarks

@rbuckton has some blob storage setup for our existing internal benchmarks - maybe we should get in on that? I know we'd probably like some kind of the aggregated results on the same dashboard at least.

> a build definition (manually triggered for now) that can run a benchmark of package X of DefinitelyTyped@master with TypeScript version Y.

Our [definition for running DT with an arbitrary TS version that we trigger for PRs](https://typescript.visualstudio.com/TypeScript/_build?definitionId=18) is probably a good place to start/clone from.
