### ISSUE TITLE
Filter narrowing down its output type without type guards

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/TypeScript#30863]
I have come across issues such as #7657, #20812 and #20218 as well as SO questions such as [this one](https://stackoverflow.com/a/43011375/2715716), but they all deal with type guards.

Could it be made so that the following code:

```ts
const items: (number | null)[] = [1,2,3,null];
const numbers = items.filter(i => i !== null);
```

…just works - infers that `numbers` is `number[]` with `--strictNullChecks` on? I think this should be out of the box behavior with TypeScript and `lib.d.ts` typings. Is this possible?

**Comment by jack-williams** [comment]
Duplicate of #16069

**Comment by TomasHubelbauer** [comment]
Indeed, thank you. Hopefully that issue gets more attention soon.

**Comment by jmarceli** [comment]
I was having a similar problem, did you try:

```
const items: (number | null)[] = [1, 2, 3, null];
const numbers = items.filter((i): i is number => i !== null);
```

Here is a working example: 
https://typescript-play.js.org/#code/MYewdgzgLgBAllApgWwgLhgCjAV2QI0QCcYAfGXAG0oEoBtAXRgF4Y6BGAGhgCZuBmblUoMA3ACgA9JNCRYuAsQgt4SVADoAZnEpIimOCwB88GAEJmrYTXXIAhgAcDx0wCpeNCbOgU8hIsqsCCgQWjp6mAY0GIZwygr+LoYWVjjUNvZOhswmhu48nuLi3iCUiOqUIADm2H5KhUA

**Comment by TomasHubelbauer** [comment]
I did end to doing that. I raised this issue to see if there is a future where we won't have to spell this out to the compiler. Looks like the mentioned issue is tracking the progress towards that.
