### ISSUE TITLE
Smarter flow-typing with || 

### ISSUE THREAD

**Issue by Nathan-Fenner** [microsoft/TypeScript#30869]
## Search Terms

- mutually exclusive

- flow typing

## Suggestion

The following code doesn't type-check today. I think it would be nice if it did:

```ts
function getThing(): null | object {
  return {};
}
function example() {
  const thing1: null | object = getThing();
  const thing2: null | object = getThing();

  if (!thing1 && !thing2) {
    return;
  }


  // error: Type 'object | null' is not assignable to type 'object'.
  const either: object = thing1 || thing2;
}
```

[playground link (enable strict null checks)](http://www.typescriptlang.org/play/#src=function%20getThing()%3A%20null%20%7C%20object%20%7B%0D%0A%20%20return%20%7B%7D%3B%0D%0A%7D%0D%0Afunction%20example()%20%7B%0D%0A%20%20const%20thing1%3A%20null%20%7C%20object%20%3D%20getThing()%3B%0D%0A%20%20const%20thing2%3A%20null%20%7C%20object%20%3D%20getThing()%3B%0D%0A%0D%0A%20%20if%20(!thing1%20%26%26%20!thing2)%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20const%20either%3A%20object%20%3D%20thing1%20%7C%7C%20thing2%3B%0D%0A%7D)

We know that it's impossible for *both* `thing1` *and* `thing2` to be falsey because of the earlier check, so it would be nice if the inferred type were `object` instead of `object | null`.

## Use Cases

The above is basically the use-case I had in mind. In my case, they were regexp match objects, but the general idea still applies no matter what they area.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code [more-accurate types might cause some conditionals to be marked as redundant, but that should just help clean up code]
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Design Limitation Concerns

This doesn't exactly fit in with TypeScript's existing flow-typing *implementation*, since it requires typing `thing1` and `thing2` *together*. Doing this everywhere (for all pairs or triplets of objects) would be prohibitively costly.

The kind of reasoning I'd prefer, which is more scalable, goes roughly like the following:

- when evaluating `thing2` in the expression `thing1 | thing2`, we *know* that `thing1` is falsy [since otherwise we wouldn't have gotten here]
- there's a recent "still-valid" flow-typing check that requires `!truthiness(thing1) && !truthiness(thing2)` to be `false`
- we can now "learn" a more-precise flow-type on `thing2` since the `thing1` and `thing2` both appear in a relevant flow-type condition

 My hope is that this is merely a limitation of the existing implementation, rather than the overall design. I would hope this kind of feature could be added to the existing implementation in a nice and elegant way without impacting type-checking preciseness or performance elsewhere.

**Comment by RyanCavanaugh** [comment]
It's easy enough to counterfactually reason through the 2-variable case, but generalizing this is [really quite difficult](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem) and doesn't come up often enough for us to want to start trying to writing heuristic algorithms for NP-complete problems.

**Comment by r1si** [comment]
@RyanCavanaugh 
Indicate with a specific warning, all type evaluations within a if scope with an OR logic?
That is, the design limitation is clear, but if not indicated it is questionable
