### ISSUE TITLE
Typescript 1.5 import module

### ISSUE THREAD

**Issue by gotenxds** [Microsoft/TypeScript#3086]
Hi, I'm not using any external libraries in my project but when I try to re export some modules I get this errors:

src/layer/layers.ts(1,14): error TS1005: ';' expected.
src/layer/layers.ts(1,19): error TS1005: ';' expected.
src/layer/layers.ts(2,1): error TS1128: Declaration or statement expected.
src/layer/layers.ts(2,24): error TS1005: ';' expected.
src/layer/layers.ts(2,29): error TS1005: ';' expected.

How can I fix this ?

**Comment by fletchsod-developer** [comment]
Can you show us the script, for easier reproducing of the bug.

**Comment by gotenxds** [comment]
There is not much to show really.

```javascript
// Layer.ts
export default class Layer {
// Methods and ctor
}

//layers.ts
export * as Layer from "./Layer"; // Errors here
```

**Comment by gotenxds** [comment]
Also I get similer errors for file like this:

```javascript
export default interface MyInterface<V>{
    method():V;
}
```

MyInterface.ts(1,26): error TS1005: ';' expected.

**Comment by danquirk** [comment]
What version of tsc/VS are you using?

**Comment by gotenxds** [comment]
tsc -version
message TS6029: Version 1.5.0-beta

**Comment by arthurc** [comment]
Shouldn't it be as follows?

    export { Layer } from "./Layer";

**Comment by josecasimiro** [comment]
Check your PATH env variable. If you have multiple versions of Typescript, you might have multiple paths on there for all the versions.

**Comment by mhegazy** [comment]
@gotenxds are you still running into this issue? I can not get a repro for this on the [playground](http://www.typescriptlang.org/Playground#src=export%20default%20class%20Layer%20%7B%0D%0A%2F%2F%20Methods%20and%20ctor%0D%0A%7D)

**Comment by mhegazy** [comment]
Seems there is no action items here. closing.
