### ISSUE TITLE
'this' in type

### ISSUE THREAD

**Issue by 2A5F** [Microsoft/TypeScript#30860]
## Search Terms
this in type

## Suggestion
Let the type definition carry an unknown this
Let `this` be available in `type`

## Use Cases
```typescript
type Some = { xxx(): this }
interface A extends Some { }
class A { }
class B extends A { }

let b = new B
b.xxx() // return this B
```
```typescript
type Some = { xxx(): this }

let x: Some
x.xxx() // return this Some
```
```typescript
type A = { xxx(): this }
type B = A & { val: string }

let x: B
x.xxx() // return this B
```

This is easy to implement in js
```typescript
function some() {
    const o = {
        xxx() {
            return o
        }
    }
    return o
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by mivanovaxway** [comment]
@2A5F, but you can already achieve that with an interface instead of type:

```
interface A {
    xxx(): this;
}
type B = A & { val: string }
```
Personally it seems bizarre for `type` to be `this` aware since `this` itself is not a `type`, but a `value` that can have many types so it depends on how we infer the type.

Regards

**Comment by 2A5F** [comment]
@mivanovaxway 
If there is already one
```typescript
interface X {
    xxx(): string
}
```
You want to convert it to xxx
```typescript
interface Some {
    xxx(cb: () => string): this
}
```
This is a solution
```typescript
type foo = { [K in keyof X]: (cb: X[K]) => this }
interface Some extends foo {
    
}
```

**Comment by 2A5F** [comment]
And in this case, the type is `...`
```typescript
function some() {
    const o = {
        xxx() {
            return o
        }
    }
    return o
}
```
[Playground](http://www.typescriptlang.org/play/index.html#src=function%20some()%20%7B%0D%0A%20%20%20%20const%20o%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20xxx()%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20o%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20o%0D%0A%7D)

**Comment by mivanovaxway** [comment]
@2A5F I get your point now, indeed you can't do this:
`type foo = { [K in keyof X]: (cb: X[K]) => this }`
So you can't define a higher order transformational type like foo. 
And if you do:
`type foo = { [K in keyof X]: (cb: X[K]) => Z }`
And then we have `interface Stuff extends Z`, we always get `xxx()` to return `Z`.

So I see your point, to evade repeating `type foo = { [K in keyof X]: (cb: X[K]) => Z }`
every time we want to extend.

I came up with a repetitive workaround like this:
```
type ArgumentTypes<T> = T extends (...args: infer U) => infer R ? U : never;
interface X {
    xxx(): string
}

type foo = { [K in keyof X]: (cb: X[K]) => Some }
interface Some extends foo {

}
type moo = { [K in keyof Some]: (...args: ArgumentTypes<Some[K]>) => Dum }
interface Dum extends moo {

}
```

**Comment by RyanCavanaugh** [comment]
This is an intentional restriction because otherwise it's confusing/ambiguous. For example:

```ts
type K = {
  prop: number;
  (): { self: this, body: string };
}
declare const k: K;
// Which of these is legal?
k().self.prop
k().self.body
```

You can say "Well just do what interfaces do" but interfaces and type aliases are actually rather different in terms of how and where they are inlined -- expanding out a type alias is a "safe" operation in our type system and this does occur frequently; expanding out an interface is *not* safe and is never done.

**Comment by 2A5F** [comment]
I originally wanted to have type contain an unknown this placeholder
only determined by interface extends
```typescript
type K = {
  prop: number;
  (): { self: this, body: string }; // this is any
}
interface IK extends K { } 
declare const k1: IK; // this is IK
k1().self.prop
```
Or for variable definition
use typeof x
```typescript
declare const k2: K; // this is typeof k2
k2().self.prop
```
---
And if want subranges, make a interface and extends
```typescript
type KReturn = { self: this, body: string }
interface IKReturn extends KReturn;
type K = {
  prop: number;
  (): IKReturn; // this is IKReturn
}
k2().self.body
```
can even make an anonymous interface
```typescript
type K = {
  prop: number;
  (): interface extends { self: this, body: string }; // this is anonymous interface
}
k2().self.body
```

<br>

---

And, how about let `interface`'s `[key:xxx]` be able to use any `keyof`

```typescript
interface X {
    xxx(): string
}
interface Some extends foo {
    [key: K in keyof X]: (cb: X[K]) => this
}
```

@RyanCavanaugh 

And what does 'expanding out' mean?
