### ISSUE TITLE
VS is unexpectedly receiving diagnostics with category "message"

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#30872]
Telemetry shows that the diagnostic codes are 4090 and 6096.  Presumably, this explains the latter:

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json#L3421

Not sure about the former though.

Context: as I understand it, `message` means "this is not diagnostic text, it's just a string we needed localized".  That's why VS doesn't expect to receive them as diagnostics.  Repercussions are minor - they'll be treated as `Info`-severity VS diagnostics.

**Comment by sheetalkamat** [comment]
Good find. Its incorrectly reported when trying to find getExtendedConfigFile. It was meant to be for resolution tracing (which is suppose to be message and not error)
