### ISSUE TITLE
Record / Object prototype fields not considered by type inference if field name is not literal match

### ISSUE THREAD

**Issue by andytuba** [Microsoft/TypeScript#30875]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

Record type inference
prototype type inference

**Code**

```ts
type SomeRecord = Record<string, number>;
const record: Record<string, number> = {a: 1};
const actuallyAFunction: number = record["constructor".toString()];
```

**Expected behavior:**
`record["constructor".toString()]` should be inferred as potentially `number | any` and require explicit type-checking before assigning or using it as a `number` (or whatever Record's T is).

**Actual behavior:**
Although TypeScript catches obvious errors like `const someNumber: number = someRecord["constructor"]`, mangling `'constructor'` a little causes TypeScript to infer the returned value as the Record's T.

**Playground Link:** 

https://www.typescriptlang.org/play/#src=type%20SomeRecord%20%3D%20Record%3Cstring%2C%20number%3E%3B%0D%0Aconst%20record%3A%20Record%3Cstring%2C%20number%3E%20%3D%20%7Ba%3A%201%7D%3B%0D%0Aconst%20actuallyAFunction%3A%20number%20%3D%20record%5B%22constructor%22.toString()%5D%3B%0D%0A

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/29501

**Comment by RyanCavanaugh** [comment]
We're aware of the problems you can construct doing this, but the current trade-off is intentional

**Comment by andytuba** [comment]
Thanks for the attention. I can empathize with TypeScript not going through the extensive effort of mixing every property from the prototype chain into the `Record` type.

Would you recommend any mitigations for this trade-off? My ideas are to explicitly add run-time type-checking on the value and add a tslint to require the code to include some minimal checking.  Is there a different way to write the type that would educate the developer about this pitfall?

---

For more color, here's a less contrived example to illustrate the bug we're stumbling on in production:

```typescript
const input = document.querySelector('input#search');
const output = document.querySelector('div#results');

input.addEventListener('change', e => {
  renderSearchResults();
  fetchSearchResults();
});

const searchResults = {};

function fetchSearchResults() {
  const query = input.value;
  api.fetchSearchResults(query).done(results => {
      searchResults[query.toLowerCase()] = results;
      renderSearchResults();
    });
}

function renderSearchResults() {
  const query = input.value;
  const results = searchResults[query.toLowerCase()];
  output.textContent = results.join(', ');
}
```

If the user types `constructor` into the text input, then `results.join` throws "cannot call undefined as function" since `results = searchResults.__proto__.constructor`, a function.

**Comment by weswigham** [comment]
> Would you recommend any mitigations for this trade-off?

Personally, I'd just avoid map-like objects and use the es6 `Map` class instead, which neatly avoids the issue of having builtin "reserved keys".
