### ISSUE TITLE
[Compiler API] `emitBuildInfo` not public in `typescript.d.ts`

### ISSUE THREAD

**Issue by longlho** [Microsoft/TypeScript#30886]
Hi guys,

3.4 with `incremental` build support is awesome, but it doesn't seem to get exposed in `Program` type definition so I cannot use it programmatically. Is this intended?

Thanks,

LH

**Comment by longlho** [comment]
Nevermind seems like it needs builder API, or is there a way for me to stub `getProgramBuildInfo` somehow?

**Comment by MartinJohns** [comment]
Duplicate of #29978.
