### ISSUE TITLE
Type inference for implementations of interface with optional property

### ISSUE THREAD

**Issue by edgarnansen** [Microsoft/TypeScript#30884]
## Search Terms
Type inference implementation interface optional property 

## Suggestion
When using an implementation of an interface with an optional property (typescript 3.4.3)
```typescript
interface Wibble<T = any> {
  flob: number;
  wobble?: (arg: T) => void;
}
const wibbleImplementationWithWobble: Wibble<Spam> = {
  flob: 1,
  wobble: (arg) => {
    console.log(`Keep on wobbling the ${arg.eggs}`);
  },
};
```
Typescript should be able to infer that the property exists
```typescript
// I should not need to check
if (wibbleImplementationWithWobble.wobble) {
  wibbleImplementationWithWobble.wobble({
    eggs: "eggs over easy",
    ham: false,
  });
}
```

## Use Cases
We generate a lot of interfaces for graphql resolvers, and we use the concrete implementations somewhere. Not having to check if the concrete implementation has any given resolver (that we know it does) would help us keep zen.

## Examples

```typescript
interface Spam {
  eggs: string;
  ham: boolean;
}

interface Wibble<T = any> {
  flob: number;
  wobble?: (arg: T) => void;
}

interface Foo {
  bar: Wibble;
}

const wibbleImplementationWithWobble: Wibble<Spam> = {
  flob: 1,
  wobble: (arg) => {
    console.log(`Keep on wobbling the ${arg.eggs}`);
  },
};

const wibbleImplementationWithoutWobble: Wibble = {
  flob: 1,
};

const thisIsNice = (foo: Foo) => {
  if (foo.bar.wobble) {
    foo.bar.wobble("flob");
  }
};

const thisIsNot = () => {
  // I should not need to check
  if (wibbleImplementationWithWobble.wobble) {
    wibbleImplementationWithWobble.wobble({
      eggs: "eggs over easy",
      ham: false,
    });
  }
  // I should maybe not even get this suggestion
  if (wibbleImplementationWithoutWobble.wobble) {
    wibbleImplementationWithoutWobble.wobble("flob");
  }
};
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by edgarnansen** [comment]
Not quite sure whether to put this as a feature request or a bug, though I now see that it might seem like I have a suggestion for how to solve this. I don't 😬

**Comment by MartinJohns** [comment]
Objects are mutable. The `wobble` property could be set to `undefined`. Even when the interface marks the property `readonly`, that doesn't mean the implementation has to be read-only as well.

This works as intended.

**Comment by RyanCavanaugh** [comment]
Non-union targets don't get narrowed on assignment/initialization, which is admittedly annoying, but also a large performance savings since many assignments to non-unions *are* of an irrelevantly-more-specific type.

There are also correctness/breaking-change cases to consider:
```ts
interface Options {
    name: string | number;
    lastName?: string;
}

function getDefaultOptions() {
    const opts: Options = { name: "bob" };
    return opts;
}

// Legal or no?
const p = getDefaultOptions();
p.name = 100;
p.lastName = "smith";
```
If we narrowed `opts` according to its initializer, then the return type is `{ name: string }` and the property assignments on the last lines would be illegal, even though the intuitive return type of `getDefaultOptions` is `Options`

**Comment by edgarnansen** [comment]
You're both right, and I hadn't considered those points. However, I know when I want the type to narrow, and when I'd like it not to. Being able to somehow communicate this would be very beneficial. It might be too late on a friday night in Norway, but something like `Narrow<T>` or even `as const`?

**Comment by RyanCavanaugh** [comment]
What you want is #7481 so that you can write

```ts
interface Wibble<T = any> {
  flob: number;
  wobble?: (arg: T) => void;
}
const wibbleImplementationWithWobble = {
  flob: 1,
  wobble: (arg) => {
    console.log(`Keep on wobbling the ${arg.eggs}`);
  },
} magicsyntax Wibble<Spam>;
```

**Comment by edgarnansen** [comment]
Sounds good, I'll follow that issue then. Thanks!
