### ISSUE TITLE
Incorrect callback parameter type inference!

### ISSUE THREAD

**Issue by fenying** [microsoft/TypeScript#30889]
**TypeScript Version:**  3.4.3

**Search Terms:**

**Code**

```ts
interface A {

    a(a: string): void;

    b(a: string, b: number): void;
}

function test<K extends keyof A>(name: K, c: A[K]) {

    // do something.
}

/**
 * ERROR: Parameter 'a' implicitly has an 'any' type.ts(7006)
 *
 * Because it infer `a` as `any`. Why here can not infer the type of `a`?
 *
 * VSCode tips: function test<"a">(name: "a", c: (a: string) => void): void
 */
test("a", function(a): void {
    console.log(a);
});

test("b", function(a, c): void {
    console.log(a);  // this is okay. the types of a and c is fine.
});

```

**Expected behavior:**

The `test` function should able to infer the parameter `a` as type `string`.

**Actual behavior:**

As you see above, it reports an error.

**And, before v3.4.x, at least before 3.3.4000, it's okay.**

**Playground Link:** 

https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%0D%0A%20%20%20%20a(a%3A%20string)%3A%20void%3B%0D%0A%0D%0A%20%20%20%20b(a%3A%20string%2C%20b%3A%20number)%3A%20void%3B%0D%0A%0D%0A%20%20%20%20c()%3A%20void%3B%0D%0A%0D%0A%20%20%20%20d(a%3A%20string%2C%20b%3A%20number%2C%20c%3A%20Date)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test1%3CT%20extends%20Function%3E(c%3A%20T)%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20do%20something.%0D%0A%7D%0D%0A%0D%0Afunction%20test2%3CK%20extends%20keyof%20A%3E(name%3A%20K%2C%20c%3A%20A%5BK%5D)%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20do%20something.%0D%0A%7D%0D%0A%0D%0Atest1%3C(a%3A%20string)%20%3D%3E%20void%3E(function(a)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest1%3C(a%3A%20string%2C%20c%3A%20Date)%20%3D%3E%20void%3E(function(a%2C%20c)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a%2C%20c)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest1%3C()%20%3D%3E%20void%3E(function()%3A%20void%20%7B%0D%0A%20%20%20%20console.log(%22okay%22)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Parameter%20'a'%20implicitly%20has%20an%20'any'%20type.ts(7006)%0D%0A%20*%0D%0A%20*%20VSCode%20Tips%3A%20function%20test2%3C%22a%22%3E(name%3A%20%22a%22%2C%20c%3A%20(a%3A%20string)%20%3D%3E%20void)%3A%20void%0D%0A%20*%2F%0D%0Atest2(%22a%22%2C%20function(a)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a)%3B%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22c%22%2C%20function()%3A%20void%20%7B%0D%0A%20%20%20%20console.log(%22okay%22)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Parameter%20'a'%20implicitly%20has%20an%20'any'%20type.ts(7006)%0D%0A%20*%20Parameter%20'c'%20implicitly%20has%20an%20'any'%20type.ts(7006)%0D%0A%20*%0D%0A%20*%20VSCode%20Tips%3A%20function%20test2%3C%22b%22%3E(name%3A%20%22b%22%2C%20c%3A%20(a%3A%20string%2C%20b%3A%20number)%20%3D%3E%20void)%3A%20void%0D%0A%20*%2F%0D%0Atest2(%22b%22%2C%20function(a%2C%20c)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a%2C%20c)%3B%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22d%22%2C%20function(a%2C%20b%2C%20c)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a)%3B%20%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This has always been the case:
```
=== latest ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 3.3 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 3.2 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 3.1 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 3.0 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.9 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.8 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.7 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.6 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.5 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.4 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.3 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
=== 2.2 ===

clipboard.ts:20 test("a", function(a): void {
                                   ~
  TS7006: Parameter 'a' implicitly has an 'any' type.
```

That said, this feels like something that should work - a context-sensitive function should be getting deferred here during inference.

**Comment by fenying** [comment]
Oh, yes you are right. I didn't check it carefully, because I only use v3.3.3 at company but 3.4.3 at home.

Anyway, I've found a temporary solution for it, just wrap the `A[K]` with this generic type.

```ts
type TRebuildFn<T extends (...args: any[]) => any> = (...v: Parameters<T>) => ReturnType<T>;
```

Check it here: https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%0D%0A%20%20%20%20a(a%3A%20string)%3A%20void%3B%0D%0A%0D%0A%20%20%20%20b(a%3A%20string%2C%20b%3A%20number)%3A%20void%3B%0D%0A%0D%0A%20%20%20%20c()%3A%20void%3B%0D%0A%0D%0A%20%20%20%20d(a%3A%20string%2C%20b%3A%20number%2C%20c%3A%20Date)%3A%20void%3B%0D%0A%0D%0A%20%20%20%20e(a%3A%20number)%3A%20string%3B%0D%0A%0D%0A%20%20%20%20f()%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20TRebuildFn%3CT%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3E%20%3D%20(...v%3A%20Parameters%3CT%3E)%20%3D%3E%20ReturnType%3CT%3E%3B%0D%0A%0D%0Afunction%20test1%3CT%20extends%20Function%3E(c%3A%20T)%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20do%20something.%0D%0A%7D%0D%0A%0D%0Afunction%20test2%3CK%20extends%20keyof%20A%3E(name%3A%20K%2C%20c%3A%20TRebuildFn%3CA%5BK%5D%3E)%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20do%20something.%0D%0A%7D%0D%0A%0D%0Atest1%3C(a%3A%20string)%20%3D%3E%20void%3E(function(a)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest1%3C(a%3A%20string%2C%20c%3A%20Date)%20%3D%3E%20void%3E(function(a%2C%20c)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a%2C%20c)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest1%3C()%20%3D%3E%20void%3E(function()%3A%20void%20%7B%0D%0A%20%20%20%20console.log(%22okay%22)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22a%22%2C%20function(a)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22c%22%2C%20function()%3A%20void%20%7B%0D%0A%20%20%20%20console.log(%22okay%22)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22b%22%2C%20function(a%2C%20c)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a%2C%20c)%3B%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22d%22%2C%20function(a%2C%20b%2C%20c)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(a)%3B%20%20%2F%2F%20this%20is%20okay.%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22e%22%2C%20function(a)%3A%20string%20%7B%0D%0A%20%20%20%20console.log(a)%3B%20%20%2F%2F%20this%20is%20okay.%0D%0A%20%20%20%20return%20a.toString()%3B%0D%0A%7D)%3B%0D%0A%0D%0Atest2(%22f%22%2C%20function()%3A%20number%20%7B%0D%0A%20%20%20%20return%20123%3B%0D%0A%7D)%3B%0D%0A

**Comment by jcalz** [comment]
This is fixed now, right?

**Comment by fenying** [comment]
@jcalz Yep, it's fixed. Thanks.
