### ISSUE TITLE
The type of private fields in a class cannot be used in generic

### ISSUE THREAD

**Issue by worudso** [microsoft/TypeScript#30882]
**TypeScript Version:**  3.4.1

**Search Terms:**
generic, class, private field
**Code**
```ts
class Foo<T> {
    private a!: T; // when it is public, no error occurs below
}

type Bar<T extends Record<string, Foo<any>>> = T[keyof T]["a"]; // ts(2536) occurs, while autocomplete works well.
type A = Foo<number>["a"]; // it works always!
```

**Expected behavior:**
Not treating it as an error. If it is inteneded, at least the error message should be more helpful.
**Actual behavior:**
ts(2536) occurs.
[**Playground Link**](https://www.typescriptlang.org/play/#src=class%20Foo%3CT%3E%20%7B%0D%0A%20%20%20%20private%20a!%3A%20T%3B%20%2F%2F%20when%20it%20is%20public%2C%20no%20error%20occurs%20below%0D%0A%7D%0D%0A%0D%0Atype%20Bar%3CT%20extends%20Record%3Cstring%2C%20Foo%3Cany%3E%3E%3E%20%3D%20T%5Bkeyof%20T%5D%5B%22a%22%5D%3B%20%2F%2F%20ts(2536)%20occurs%2C%20while%20autocomplete%20works%20well.%0D%0Atype%20A%20%3D%20Foo%3Cnumber%3E%5B%22a%22%5D%3B%20%2F%2F%20it%20works%20always!) 
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@sandersn not 100% convinced it's a bug per se, but it well might be. The error is indeed weird

**Comment by andrewbranch** [comment]
This isn’t a bug, but I improved the error message to make it clear that it’s on purpose:

```
Private or protected member 'a' cannot be accessed on a type parameter.
```
