### ISSUE TITLE
Display differs between tsc and tsserver

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#30891]
TypeScript:3.4.3
VSCode:1.32.3

```ts
//src/main.ts
import { HKT } from "./hkt";

const sym = Symbol();

declare module "./hkt" {
  interface HKT<T> {
    [sym]: { a: T }
  }
}

type A = HKT<number>[typeof sym];
```

```ts
//src/hkt.ts
export interface HKT<T> { }
```

```json
//tsconfig.json
{
  "compilerOptions": {
    "rootDir": "src",
    "lib": [
      "es2015"
    ]
  }
}
```

```
$ tsc
// Compile successfully
```

tsserver(VSCode):
![image](https://user-images.githubusercontent.com/17868838/56054064-c0090080-5d90-11e9-836d-5e300737a225.png)

**Comment by sheetalkamat** [comment]
This seems to happen when doing incremental build with just checking main.ts without typechecking `hkt.ts` Was able to repro this by modifying tsconfig.json to have `incremental` as true and building. Edit main.ts to add say `const x = 10` and build again and it reports the error.
