### ISSUE TITLE
Perf issues with @material-ui/icons

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#30908]
Server synced to 4fee62844777c23cf37b6d4594f65b393b27b4dd

Repro: In VS, create a new TypeScript Node Console App.  Add npm references to `@material-ui/icons` and `@material-ui/core` (a peer dependency).  Add the following import at the top of app.ts:

```ts
import * as icons from "@material-ui/icons";
```

Looks like the first updateGraph takes ~10 seconds.

[code.zip](https://github.com/Microsoft/TypeScript/files/3075429/code.zip)
[vs.zip](https://github.com/Microsoft/TypeScript/files/3075430/vs.zip)

The log files are huge, but only because each project listing has ~5300 files.  The Code log is for opening the same folder with

```
Version: 1.34.0-insider (user setup)
Commit: d234937aedcbc265d2272ba5861125293239f9c7
Date: 2019-04-05T05:18:43.251Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by sheetalkamat** [comment]
Running tsc with `--extendedDiagnostics --noEmit` on this project shows we are taking 7+s for creating program. (Ignore check time since from tsserver checking is not done as part of updateGraphWorker)
```
Files:            5509
Lines:           64552
Nodes:          216323
Identifiers:     59606
Symbols:        152254
Types:           76084
Memory used:   234582K
I/O Read time:   1.46s
Parse time:      1.13s
Program time:    7.22s
Bind time:       0.85s
Check time:     12.81s
Total time:     20.88s
```

**Comment by sheetalkamat** [comment]
This seems to have gotten better with 3.7
```
Info 62   [13:25:41.644] Finishing updateGraphWorker: Project: c:/Users/shkamat/source/repos/NodejsConsoleApp4/NodejsConsoleApp4/tsconfig.json Version: 1 structureChanged: true Elapsed: 3826ms
```

**Comment by amcasey** [comment]
@sheetalkamat How did the file count drop so much?

**Comment by amcasey** [comment]
I don't recall whether the original repro compiled cleanly, but this time I had to add `@types\react`, `@types\react-dom`, and `@types\jsdom`.

**Comment by amcasey** [comment]
Updating the metadata to reflect the fact that, while I am currently investigating, this is not yet an expected milestone for an actual fix.

**Comment by amcasey** [comment]
I think this is too stale to be useful.
