### ISSUE TITLE
Infer optional property type from empty object

### ISSUE THREAD

**Issue by aleclarson** [Microsoft/TypeScript#30912]
This bug is already fixed in `typescript@next`, but I'm posting it for posterity.

**TypeScript Version:**  3.4.1 *(Fixed in 3.5.0-dev.20190413)*

**Search Terms:**
- empty object extends
- infer optional property type

**Code**
```ts
// unknown 👍
type T1 = {} extends { to: infer U } ? U : unknown

// {} 👎
type T2 = {} extends { to?: infer U } ? U : unknown
```

**Expected behavior:**
The inferred property type in `T2` should be `undefined` or `never`

**Actual behavior:**
The inferred type is `{}`

**Playground Link:** [click here](https://typescript-play.js.org/#code/PTAEFcDsGtIewO6VIXg3CyOwKAC4E8AOApqACoCMoAvKAN4C+oBAHlgZACYDONoWcAXKACWkAGYEATqACqoegH5poAVFiJIGDCBr0UgOR3s+IsQBMlbQ2atO3XnIHCxkmfMXKY8JEA)

**Related Issues:** None?

**Comment by RyanCavanaugh** [comment]
Thanks!
