### ISSUE TITLE
assignment of string union defined in class interface should allow without casting

### ISSUE THREAD

**Issue by Kotarski** [Microsoft/TypeScript#30911]
**TypeScript Version:**  3.4.1

**Search Terms:**
Class string union from interface
union type does not work in classes

**Code**

```ts
interface namedperson {
    name: "george"|"elaine"|"jerry"|"cosmo"
}

class person implements namedperson {
    name = "george"
} 
```

**Expected behavior:**
No errors
I would expect the behaviour to work as it does outside classes, e.g:
```TS
let person: namedperson = {
    name: "george"
}
```

**Actual behavior:**
Error:
```
Property 'name' in type 'person' is not assignable to the same property in base type 'namedperson'.
  Type 'string' is not assignable to type '"george" | "elaine" | "jerry" | "cosmo"'.
```

**Playground Link:** [TypeScript Playground](https://www.typescriptlang.org/play/#src=interface%20namedperson%20%7B%0D%0A%20%20%20%20name%3A%20%22george%22%7C%22elaine%22%7C%22jerry%22%7C%22cosmo%22%0D%0A%7D%0D%0A%0D%0Aclass%20person%20implements%20namedperson%20%7B%0D%0A%20%20%20%20name%20%3D%20%22george%22%0D%0A%7D%20)

I'm aware that this can be worked around by using either:
```TS
class person implements namedperson {
      name:"george" = "george"
}
```
or:
```TS
class person implements namedperson {
    name = "george" as "george"
}
```
however I find these both heinously ugly and would rather stab myself in the face.

**Comment by RyanCavanaugh** [comment]
`"george" as const` is the new way to write that

See https://github.com/Microsoft/TypeScript/issues/10570#issuecomment-296860943

**Comment by Kotarski** [comment]
Oh that's a bit nicer, thanks!
