### ISSUE TITLE
means to find excessive types 

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#30927]
given a function

```ts
function fn(x: A | B | C): void { }
```

which is called from some 30 places in the code

of those 30 places each one is called like 15 times from somewhere else

after hours of thorough investigation it turned out that 
 - the `A` case is effectively unused because it's not passed from any of those 30 x 15 = 450 places

case `A` makes up the good part of function `fn` and represents a piece of dead code that should be erased

problem:
-  it is extremely hard to prove by hands that a type is excessive

suggestion:

- allow querying the code to find excessive types

**Comment by RyanCavanaugh** [comment]
The information you'd need to compute this isn't something that's derivable from the current typechecking algorithm. Pretty much the only guaranteed way to detect correctly this would be to iteratively remove constituents, recompile, and see what happened.
