### ISSUE TITLE
Add ES2019 Object.fromEntries function

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/TypeScript#30933]
## Search Terms

fromEntries

## Suggestion

`lib: es2019` should add `Object.fromEntries()` type.

## Use Cases

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by iugo** [comment]
https://github.com/tc39/proposal-object-from-entries

**Comment by waynevanson** [comment]
HI Guys,

Is this live yet and if so, which version? I can't get it to find it as `Property 'fromEntries' does not exist on type 'ObjectConstructor'.`

What versions of TS and NODEJS should I be running to make this work?

**Comment by waynevanson** [comment]
The file is available in my node_modules under `lib.es2019.object.d.ts` but it won't read from it?

Any link to any issue regarding how to resolve a similar issue is welcomed.

``` ts
/// <reference no-default-lib="true"/>


/// <reference lib="es2015.iterable" />

interface ObjectConstructor {
    /**
     * Returns an object created by key-value entries for properties and methods
     * @param entries An iterable object that contains key-value entries for properties and methods.
     */
    fromEntries<T = any>(entries: Iterable<readonly [PropertyKey, T]>): { [k in PropertyKey]: T };

    /**
     * Returns an object created by key-value entries for properties and methods
     * @param entries An iterable object that contains key-value entries for properties and methods.
     */
    fromEntries(entries: Iterable<readonly any[]>): any;
}

```

**Comment by waynevanson** [comment]
> HI Guys,
> 
> Is this live yet and if so, which version? I can't get it to find it as `Property 'fromEntries' does not exist on type 'ObjectConstructor'.`
> 
> What versions of TS and NODEJS should I be running to make this work?

It looks to me that in `tsconfig.json`, the setting to use is `target: "es2019"`  or greater. This means it won't work in all browsers and typescrcipt does no magic to use this.

**Comment by bennypowers** [comment]
this is what I did

```ts
declare global {
  interface ObjectConstructor {
    fromEntries(xs: [string|number|symbol, any][]): object
  }
}

const fromEntries = (xs: [string|number|symbol, any][]) =>
  Object.fromEntries ? Object.fromEntries(xs) : xs.reduce((acc, [key, value]) => ({...acc, [key]: value}), {})

```

**Comment by tsujp** [comment]
Extending @bennypowers to sort an object similar to this:

```
{
  foo: 'bar',
  baz: 'boo',
  alpha: 'beta',
}
```

use

```typescript
Object.keys(input).sort().reduce((acc, cur) => ({ ...acc, [cur]: input[cur] }), {})
```

**Comment by caseyhoward** [comment]
I ended up just defining my own functions for what I needed. They're pretty gross since they use any, but they get the job done for me I think:

```typescript
function fromEntries<T>(entries: [keyof T, T[keyof T]][]): T {
  return entries.reduce(
    (acc, [key, value]) => ({ ...acc, [key]: value }),
    <T>{}
  );
}

function toEntries<T>(obj: T): [keyof T, T[keyof T]][] {
  const entries: [string, any][] = Object.entries(obj);
  const entriesWithKeysLookedUp: [keyof T, T[keyof T]][] = entries.map(item => {
    const keyString = item[0];
    const value = item[1];
    return [<keyof T>keyString, value];
  });
  return entriesWithKeysLookedUp;
}
```

All I wanted to do was map an objects values. Ended up being way more annoying than it should have been. Does anyone know a better way? It's annoying that `Object.entries` returns `[string, T]` and not a keyof type since you know the first element in each of the array elements is a keyof something and not just a string.

**Comment by MrCheater** [comment]
@caseyhoward , Hi.  I have a problem with the <T> {} construct. TypeScript 3.8.3. http://www.typescriptlang.org/v2/en/play?useDefineForClassFields=true&allowUnreachableCode=true&allowUnusedLabels=true&downlevelIteration=true&target=99
```
Cannot use JSX unless the '--jsx' flag is provided.(17004)
'T' only refers to a type, but is being used as a value here.(2693)
JSX element 'T' has no corresponding closing tag.(17008)
```
Do you know the solution?

**Comment by javiermrz** [comment]
Go into `tsconfig.json`, and inside `compilerOptions` properties search for a property named `lib`. Add the string "esnext" in the array. It should look something like: 
````
"lib": ["es2018", "dom", "esnext"]
````

**Comment by iwanttobealight** [comment]
Add ["esnext"] to the lib worked for me! Thank u

**Comment by mapurba** [comment]
Hi All,
I am seeing this issue with chrome version 70 line , Angular  TS  
 tsconfig : `  
"lib": [
      "es2018",
      "dom",
      "esnext"
    ]
`
one thing to notice the vendor js in lazy loaded as the .

with the uses of `Object.fromEntries` in `.ts` throws the same error in chrome 70 line .

case `.ts` : `main.ts:12 TypeError: Object.fromEntries is not a function
    at new AppComponent (app.component.ts:15)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:18)
    at getNodeInjectable (core.js:5993)
    at instantiateRootComponent (core.js:12873)`

case Vendor : `VM547 vendor.js:98199 Uncaught TypeError: Object.fromEntries is not a function
    at Module.<anonymous> (VM547 vendor.js:98199)
    at i (VM547 vendor.js:98199)
    at push../node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor.js (VM547 vendor.js:98199)
    at VM547 vendor.js:98199
    at VM547 vendor.js:98199
    at Object../node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor.js (VM547 vendor.js:98199)
    at __webpack_require__ (VM542 runtime.js:85)
    at __webpack_require__ (VM542 runtime.js:85)
    at Module../src/app/shared/shared.module.ts (VM545 main.js:2147)`

**Comment by sadeghmasoomi** [comment]
go to "tsconfig.json" and adding :

`"lib": ["es2019"];`
