### ISSUE TITLE
Use 'Omit' instead of 'Pick<Exclude<...>>' for object rest

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#30948]
```ts
function f<T extends { a, b }>(x: T) {
    let { a, b, ...rest } = x;
}
```

Today, we type `rest` as `Pick<T, Exclude<keyof T, "a" | "b">>`. We should try to type this as `Omit<T, "a" | "b">` if `Omit` is defined.

**Comment by rpgeeganage** [comment]
Hi @sandersn,
Can I take this? I like to contribute.
Thank you

**Comment by sandersn** [comment]
Sure, go ahead! Start by looking at `let deferredGlobalPickSymbol` in checker.ts, and see where and how it's used.

**Comment by rpgeeganage** [comment]
@sandersn , 
Thank you so much. I’ll start to work on this from today itself.
Thank you so much.
