### ISSUE TITLE
Constraint type automatically

### ISSUE THREAD

**Issue by rabbitooops** [Microsoft/TypeScript#30959]
One of advantages of Javascript is dynamic. It's delightful to write code without caring about type. It's tired to write type and rewrite it over and over at the beginning of developing.

But I know type is necessary when develop a huge app.

So, can Typescript provide a way to constraint type automatically after I finish my code? I just need to check if it's right which Typescript compiled then fix it.

### example
my code:
```ts
function foo({name, age, country}) {
  // ...
}
foo({name: 'my-name', age: 0, country: 'my-country'})
foo({name: 'her-name', age: '10'})
```

Typescript compiles code to:
```ts
interface Interface1 {
  name: string;
  age: number | string;
  country?: string;
}
function foo({name, age, country}: Interface1): void {
  // ...
}
foo({name: 'my-name', age: 0, country: 'my-country'})
foo({name: 'her-name', age: '10'})
```

Then I fix compiled code:
```ts
interface Info {
  name: string;
  age: number;
  country?: string;
}
function foo({name, age, country}: Info): void {
  // ...
}
foo({name: 'my-name', age: 0, country: 'my-country'})
foo({name: 'her-name', age: 10})
```

**Comment by nmain** [comment]
This seems potentially viable as a codefix.  You could highlight any one function which took an `any` and the codefix could look at all calls to that function, the types at each callsite, and try to infer a type out of all of it.

**Comment by RyanCavanaugh** [comment]
This is just the existing "Infer from usage codefix", which doesn't yet work on destructured arguments

**Comment by rabbitooops** [comment]
Can "infer from usage" compiles "no type code" to "type code"? I think it's delightful to write typescript without handle type manually.

**Comment by RyanCavanaugh** [comment]
You seem to be using the word "compile" in a non-standard way - TS never emits TS implementation files. Can you clarify?

**Comment by rabbitooops** [comment]
Oops, I give an example here. (It's like "git rebase")

## example
1. I finished my code: main.ts (But no type, I need type for better maintainability)
2. I use typescript to compile main.ts from no-type-file to typed-file. Imagine there is a command: "tsc type main.ts".
3. I fix and rename some interface or something in typed-file. then "tsc type --continue".
4. Typescript finishes all work and apply all changes.

**Comment by RyanCavanaugh** [comment]
That's kind of a weird workflow (and a ton of extra implementation work) compared to using the codefix/refactor workflow already available in most editors. We're also looking in to making language service operations available from the commandline, so you could potentially write something like (syntax 100% tbd):

 > `ts-refactor foo.ts --fix-all infer-from-usage`

**Comment by rabbitooops** [comment]
Thx :)
