### ISSUE TITLE
TypeScript Compiler grabs modules I included on a different branch

### ISSUE THREAD

**Issue by HermannGruber** [Microsoft/TypeScript#30957]
**TypeScript Version:**  TypeScript SDK 3.4.1.0 and Visual Studio 2019 

**Expected behavior:**
I have two different branches in my aspnetcore project using Visual Studio 2019. 
On the main branch, I make use of TypeScript, but do not use a module system.
As a temporary workaround, I declare '$' as a global variable of type 'any' - being well aware that this is in principle a bad thing.
On the feature branch, I made commits to switch to using ES2015 modules, and switch the typescript compilation from msbuild to webpack.

I expect that switching to the feature branch and then returning to the main branch does not change the outcome of the build. 

**Actual behavior:**

When I return after a build on the feature branch to the main branch and do a build, the build outputs a TS2451 error (twice, but let's ignore this for now).

1>------ Rebuild All started: Project: WebApplication1, Configuration: Debug Any CPU ------
1>C:\1_Projects\TypeScriptNode\WebApplication1\WebApplication1\node_modules\@types\jquery\misc.d.ts(6536,15): error TS2451: Build:Cannot redeclare block-scoped variable '$'.
1>C:\1_Projects\TypeScriptNode\WebApplication1\WebApplication1\scripts\hello.ts(2,13): error TS2451: Build:Cannot redeclare block-scoped variable '$'.
1>C:\1_Projects\TypeScriptNode\WebApplication1\WebApplication1\node_modules\@types\jquery\misc.d.ts(6536,15): error TS2451: Build:Cannot redeclare block-scoped variable '$'.
1>C:\1_Projects\TypeScriptNode\WebApplication1\WebApplication1\scripts\hello.ts(2,13): error TS2451: Build:Cannot redeclare block-scoped variable '$'.
1>Done building project "WebApplication1.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

Minimal repro example is here:
https://github.com/HermannGruber/TypeScriptNpmAndBranches

To reproduce the error, open the solution in Visual Studio 2019, do a build on the master branch (successful), switch to the branch feature/modules, build again (successful), switch to the master branch, and build again (fails).

**Comment by RyanCavanaugh** [comment]
TypeScript can't possibly be reading files from the "wrong branch" - it doesn't have a built-in git implementation or anything remotely like that.

You should be able to reproduce the problem using a simple series of file operations - we can maybe look at the repo eventually, but we don't have the resources to do long investigations on user repos.

**Comment by HermannGruber** [comment]
Okay, I see :-) I looked again into this issue and managed to reproduce the problem without Visual Studio. I have the following tsconfig.json in the root folder:

`{
    "compilerOptions": {
        "module": "none",
        "strict": true,
        "noEmitOnError": true,
        "sourceMap": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "target": "es5",
        "lib": [
            "es2015",
            "es5",
            "dom"
        ],
        "outDir": "wwwroot/js"
    },
    "exclude": [ "node_modules, wwwroot" ],
    "include": [ "scripts/**/*" ],
    "compileOnSave": true
}
`
in the scripts/ folder, I have a file "hello.ts", which looks as follows:

`//import * as $ from "jquery"
declare var $ : any;
$(() => {
    document.body.innerHTML += "<i>Hello TypeScript using jQuery</i>";
});`

Furthermore, I have a node_modules folder, which contains all sorts of stuff. But this folder is listed in my .gitignore (by default for Visual Studio solutions). Nothing else is in my root folder. Now if I run

`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\NodeJs\node.exe" "C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.4\tsc.js"  --project ".\tsconfig.json" --listEmittedFiles --locale en-US`

I get the following output:

`node_modules/@types/jquery/misc.d.ts:6536:15 - error TS2451: Cannot redeclare block-scoped variable '$'.

6536 declare const $: JQueryStatic;
                   ~

  scripts/hello.ts:2:13
    2 declare var $ : any;
                  ~
    '$' was also declared here.

scripts/hello.ts:2:13 - error TS2451: Cannot redeclare block-scoped variable '$'.

2 declare var $ : any;
              ~

  node_modules/@types/jquery/misc.d.ts:6536:15
    6536 declare const $: JQueryStatic;
                       ~
    '$' was also declared here.


Found 4 errors.`

**Comment by HermannGruber** [comment]
Addendum: In particular, I have no files package.json and no package-lock.json. Such files exist on the feature branch, where I inited npm.

**Comment by RyanCavanaugh** [comment]
Intentionally, `exclude` doesn't prevent `node_modules/@types` from being auto-included. Add `"types": []` to your tsconfig.json if you don't want the jquery `@types` definition included.

**Comment by HermannGruber** [comment]
Thanks a lot! I was not aware of that. I can imagine that auto-including those type definitions helps in many situations. Adding `"types": []` to the `"compilerOptions"` in tsconfig.json is a solution in my situation.
