### ISSUE TITLE
Proposal:type-level `in` operator 

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#30950]
## Search Terms
in

## Suggestion

```ts
type X="x" in Obj?Obj["x"]:never;
```

In `P extends keyof T` , when key is a number literal, it does not operation well.

```ts
type A="1" extends keyof {1:number}?true:false; //false
type B={1:number}["1"];//ok(B is number)

type C=1 extends keyof {"1":number}?true:false; //false
type D={"1":number}[1]//ok(D is number)
```

## Use Cases
Check before type level index access.

## Examples
`false` if index access results in an error, `true` if compilation succeeds

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Wouldn't this just be:

    type IsIn<T, Key extends string | number> = T extends { [P in Key]: any } ? true : false

    type A = IsIn<{ 1: number }, 1> // true
    type B = IsIn<{ foo: string }, 1> // false
    type C = IsIn<{ foo: string }, "foo"> // true
    type D = IsIn<{ bar: string }, "foo"> // false
    type E = IsIn<{ foo: string, bar: number }, "bar"> // true

**Comment by RyanCavanaugh** [comment]
Alternatively
```ts
type IsIn<T, Key extends string | number> = T extends Record<Key, unknown> ? true : false
```
This doesn't seem like something we need special sugar for

**Comment by kgtkr** [comment]
I did not know that there was a solution.
Thank you very much.
