### ISSUE TITLE
Backtick literals in enumerations

### ISSUE THREAD

**Issue by arcanis** [microsoft/TypeScript#30962]
**TypeScript Version:**  3.4.3

**Search Terms:** backticks / literals / enums

**Code**

```ts
enum Foo {
  hello = `foo`,
};
```

**Expected behavior:**

It should work.

This is especially important because the `backticks` mode of the `quotes` rule from ESLint breaks programs (cf https://github.com/yarnpkg/berry/pull/70 for an example). While it could be seen as an ESLint bug, I think it *should* be possible for TS to use raw template string interchangeably with regular strings as long as they don't contain variables.

**Actual behavior:**

It throws an error (`type "foo" is not assignable to type 'Foo'`).

**Playground Link:**

https://www.typescriptlang.org/play/index.html#src=enum%20Foo%20%7B%0D%0A%20%20%20%20%20%20%20%20hello%20%3D%20%60foo%60%2C%0D%0A%7D%3B%0D%0A

**Related Issues:**

I think fixing this should have been part of #21476, but it focused on the case of `"a" + "b"` rather than the simpler case of a literal without variables.

**Comment by RyanCavanaugh** [comment]
Would take a PR for it - should be fairly easy

**Comment by arcanis** [comment]
I'll take a look end at the end of May unless someone beats me to it 🙂

**Comment by IllusionMH** [comment]
Any objections if I take a try on this issue during this week?

Do I understand correctly that only `NoSubstitutionTemplateLiteral` should be added to the list of allowed literals?
Should it support concatenations like `` `backtic` + `backtic` `` and `` `backtic` + 'single' `` ?

**Comment by arcanis** [comment]
No objection from my side! In my use case the simple literal would be enough, but I guess that given the initial context of #21476 concatenations would be useful too.

**Comment by RyanCavanaugh** [comment]
`NoSubstitutionTemplateLiteral` should be as good as `StringLiteral` anywhere here IMO
