### ISSUE TITLE
Error when passing generic function to a function

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript#30964]
**TypeScript Version:**  3.4.1

**Search Terms:**

generic, function, parameter

**Code**

```ts
const f = <T>() => {
	return { v: '' as any as T };
};

foo(f);

function foo(f: <T>() => { v: T }): { v: string } {
	return f<string>();
}
```

**Expected behavior:** It should compile

**Actual behavior:**

It doesn't:

```
Argument of type '<T>() => { v: T; }' is not assignable to parameter of type '<T>() => { v: T; }'.
  Type '{ v: {}; }' is not assignable to type '{ v: T; }'.
    Types of property 'v' are incompatible.
      Type '{}' is not assignable to type 'T'.ts(2345)
```

Note that expected and actual on the first line is the same 🤔 

**Playground Link:** https://www.typescriptlang.org/play/#src=const%20f%20%3D%20%3CT%3E()%20%3D%3E%20%7B%0D%0A%09return%20%7B%20v%3A%20''%20as%20any%20as%20T%20%7D%3B%0D%0A%7D%3B%0D%0A%0D%0Afoo(f)%3B%0D%0A%0D%0Afunction%20foo(f%3A%20%3CT%3E()%20%3D%3E%20%7B%20v%3A%20T%20%7D)%3A%20%7B%20v%3A%20string%20%7D%20%7B%0D%0A%09return%20f%3Cstring%3E()%3B%0D%0A%7D

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@weswigham I'm officially confused why `fB` and `fC` below are distinguishable. This compiled in 2.3 and earlier. Here's a matrix:

```ts
declare const fA: <T>() => { v: T };
const fB = <T>() => {
    return { v: '' as any as T };
};
const fC = <T>() => {
    return {} as any as { v: T };
};

// Hover display is identical on all of these
type TA = typeof fA;
type TB = typeof fB;
type TC = typeof fC;
type TL = <T>() => { v: T }; 

declare function accA(x: TA): void;
declare function accB(x: TB): void;
declare function accC(x: TC): void;
declare function accL(x: TL): void;

accA(fA); accA(fB); accA(fC);
//             ~~ Error
accB(fA); accB(fB); accB(fC);
//             OK
accC(fA); accC(fB); accC(fC);
//             ~~ Error
accL(fA); accL(fB); accL(fC);
//             ~~ Error
```
