### ISSUE TITLE
[BUG] union extend behavior not the same into a type

### ISSUE THREAD

**Issue by lifaon74** [microsoft/TypeScript#30960]
**TypeScript Version:**  3.1.6, 3.3.4000, 3.4.3, and next

**Search Terms:**
union extends type

**Code**

```ts
const a: (('a' | 'b') extends 'a' ? boolean : never) = null; // inferred type is never, cannot assign => correct

type C<A, B> = (A extends B ? boolean : never);
const b: C<'a' | 'b', 'a'> = null; // inferred type is boolean => incorrect

function foo<B, A extends B>() {}
foo<'a', 'a' | 'b'>(); // properly handle the constraint

function bar<A, B>(c: C<A, B>) {}
bar<'a' | 'b', 'a'>(null); //inferred type is boolean => incorrect
```

**Expected behavior:**
The type C is not properly inferred. I expect `C<'a' | 'b', 'a'>` is *never*

**Actual behavior:**
It seems that a type doesn't properly handle `extends` with union

**[Playground Link](https://www.typescriptlang.org/play/#src=const%20a%3A%20(('a'%20%7C%20'b')%20extends%20'a'%20%3F%20boolean%20%3A%20never)%20%3D%20null%3B%20%2F%2F%20inferred%20type%20is%20never%2C%20cannot%20assign%20%3D%3E%20correct%0D%0A%0D%0Atype%20C%3CA%2C%20B%3E%20%3D%20(A%20extends%20B%20%3F%20boolean%20%3A%20never)%3B%0D%0Aconst%20b%3A%20C%3C'a'%20%7C%20'b'%2C%20'a'%3E%20%3D%20null%3B%20%2F%2F%20inferred%20type%20is%20boolean%20%3D%3E%20incorrect%0D%0A%0D%0Afunction%20foo%3CB%2C%20A%20extends%20B%3E()%20%7B%7D%0D%0Afoo%3C'a'%2C%20'a'%20%7C%20'b'%3E()%3B%20%2F%2F%20properly%20handle%20the%20constraint%0D%0A%0D%0Afunction%20bar%3CA%2C%20B%3E(c%3A%20C%3CA%2C%20B%3E)%20%7B%7D%0D%0Abar%3C'a'%20%7C%20'b'%2C%20'a'%3E(null)%3B%20%2F%2Finferred%20type%20is%20boolean%20%3D%3E%20incorrect)**

---

**My ideas:** 

Maybe some details and normalization should be done about union and intersection for the primitives. Currently they are not really well explained for primitive types and there is no real documentation with theses types and the *extends* keyword.

I'll call an *unionSet* a union type: ex `'a' | 'b' | 'c'`,
and an *intersectionSet* a intersection type: ex `'a' & 'b' & 'c'`

This is what I have inferred:
```
  // ('a' | 'b' | 'c') extends ('a' | 'b') => false
  // ('a' | 'b' | 'c') extends ('a' | 'b' | 'c') => true
  // ('a' & 'b' & 'c') extends ('a' & 'b') => true
  // ('a' & 'b') extends ('a') => true
  // ('a') extends ('a' & 'b') => false
  
  // string extends ('a' & 'b') => false
  // ('a' & 'b') extends string => true
  
  // string extends ('a' | 'b') => false
  // ('a' | 'b') extends string => true
  
  // ('a' | 'b' | 'c') extends ('a' & 'b') => false
  // ('a' | 'b') extends ('a' & 'b') => false
  // ('a') extends ('a' & 'b') => false
  // (('a' & 'b') | ('a' & 'b' & 'c')) extends ('a' & 'b') => true
  // ('a' & 'b') extends ('a' | 'b') => true
```

*unionSet1* extends *unionSet2* only if unionSet1 is a subset of unionSet2 (all values of unionSet1 must be present in unionSet2)

*intersectionSet1* extends *intersectionSet2* only if intersectionSet1 is a superset of intersectionSet2 (all values of intersectionSet2 must be present in intersectionSet1)

But some strange behavior occurs with string: 
```
  // string extends ('a' | 'b') => false
  // ('a' | 'b') extends string => true

  // string extends ('a' & 'b') => false => should actually be true because a string is a superset of 'a' & 'b'
  // ('a' & 'b') extends string => true => should actually be false because the intersection set 'a' & 'b' is not a superset of string.
```

This could be really interesting to have a proper documentation about this behaviors, maybe debug the `string extends ('a' & 'b')` problem, or create a new syntax, something like: `('a' | 'b') subset of ('a' | 'b' | 'c') ? boolean : never` and `('a' | 'b' | 'c') superset of ('a' | 'b') ? boolean : never` which could act as a constraint too.

Just putting here some ideas.

**Comment by RyanCavanaugh** [comment]
Conditional types are *distributive* when the type to the left of `extends` is a bare type parameter.

**Comment by lifaon74** [comment]
@RyanCavanaugh : What do you mean by distributive ? Could you give an example ?

And It doesn't explain this:

```ts
const a: (('a' | 'b') extends 'a' ? boolean : never) = null; // inferred type is never, cannot assign => correct

type C<A, B> = (A extends B ? boolean : never);
const b: C<'a' | 'b', 'a'> = null;
```
C is same as the type on `a` but the inference is not...

**Comment by RyanCavanaugh** [comment]
Distributivity explains the behavior in your example. Here are some docs you can read:

https://artsy.github.io/blog/2018/11/21/conditional-types-in-typescript/
https://mariusschulz.com/blog/typescript-2-8-conditional-types
https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by JoshRosenstein** [comment]
Should do:
```ts
type C<A, B> = ([A] extends [B] ? boolean : never);
```

Here's an old related issue regarding Distributivity #23182

the second article in @RyanCavanaugh post, makes it clear with their NonNullable example.

> Since `NonNullable<T>` checks a naked type parameter, it is distributed over a union type `A | B`. This 
> means that `NonNullable<A | B>` is resolved as `NonNullable<A> | NonNullable<B>`


So in your C example, `C<'a' | 'b', 'a'>` resolves as 
`('a' extends 'a'? boolean: never  | 'b' extends 'a'? boolean : never)` = `boolean | never` = **boolean**

Wrapping in array prevents the distribution and will resolve like your `const a`. `['a' | 'b'] extends ['a']`= **never**
