### ISSUE TITLE
User defined type guard ignored when same interface

### ISSUE THREAD

**Issue by francois-appliware** [microsoft/TypeScript#30961]
**TypeScript Version:**  The one from playground, I assume is the latest ?

**Search Terms:**
guard narrowing user defined
**Code**
```ts
interface Action {
  type: string
}
const ActionTypes = {
  EXPAND: 'expand',
  RELOAD: 'reload'
}
class Expand implements Action {
  readonly type = ActionTypes.EXPAND
  constructor(public id: string) { }
}
class Reload implements Action {
  readonly type = ActionTypes.RELOAD
  constructor(public id: string) { }
}

const isExpand = (action: Action): action is Expand => action.type === ActionTypes.EXPAND

function testSomething(action: Expand | Reload) {
  return isExpand(action) ? `Expand action, id = ${action.id}` : `Reload action, id = ${action.id}` 
}
```

**Expected behavior:**
The `action` variable in the `testSomething` method should have the `Reload` type in the 'else' part of the ternary if. (Same with normal if {} else {})

**Actual behavior:**
The `action` variable is seen as `never` by typescript, and thus the `id` property throws a `Property 'id' does not exists on type 'never'` error.

**Playground Link:**
https://www.typescriptlang.org/play/index.html#src=interface%20Action%20%7B%0D%0A%20%20type%3A%20string%0D%0A%7D%0D%0Aconst%20ActionTypes%20%3D%20%7B%0D%0A%20%20EXPAND%3A%20'expand'%2C%0D%0A%20%20RELOAD%3A%20'reload'%0D%0A%7D%0D%0Aclass%20Expand%20implements%20Action%20%7B%0D%0A%20%20readonly%20type%20%3D%20ActionTypes.EXPAND%0D%0A%20%20constructor(public%20id%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0Aclass%20Reload%20implements%20Action%20%7B%0D%0A%20%20readonly%20type%20%3D%20ActionTypes.RELOAD%0D%0A%20%20constructor(public%20id%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20isExpand%20%3D%20(action%3A%20Action)%3A%20action%20is%20Expand%20%3D%3E%20action.type%20%3D%3D%3D%20ActionTypes.EXPAND%0D%0A%0D%0Afunction%20testSomething(action%3A%20Expand%20%7C%20Reload)%20%7B%0D%0A%20%20return%20isExpand(action)%20%3F%20%60Expand%20action%2C%20id%20%3D%20%24%7Baction.id%7D%60%20%3A%20%60Reload%20action%2C%20node%20%3D%20%24%7Baction.id%7D%60%20%0D%0A%7D%0D%0A

**Related Issues:**
An old issue (2 yo) seems to talk about a similar problem:
https://github.com/Microsoft/TypeScript/issues/12646
Another one that does not really explain why it works that way ?
https://github.com/Microsoft/TypeScript/issues/18560

Also, the FAQ does not explain why (yet), or how to have typescript work as expected ?
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-isfoox-narrow-x-to-foo-when-isfoo-is-a-type-guard

**Comment by RyanCavanaugh** [comment]
You've made two completely identical classes because the `ActionTypes` enum made two `string`s instead of two literal types. Try this:
```ts
const ActionTypes = {
  EXPAND: 'expand',
  RELOAD: 'reload'
} as const;
```

**Comment by francois-appliware** [comment]
I did not know of the `as const` assertion (new feature from TS 3.4), which is good because it works as intended this way.

I understand that I made 2 identical classes (with `type: string`) but I though that user defined guards were used for this kind of case : when Typescript cannot make the difference, it uses what the user defined guard tells it what to do (even though the test inside the guard could be completely wrong).

If I have a type `A | B` and a guard telling me `action is A`, then in my `else` statement, action would be everything else but A, whatever the classes or interfaces behind.

Anyway, thanks for the answer as this closes my issue and is better as my ActionTypes are indeed const !
Cheers.

**Comment by francois-appliware** [comment]
Hello again,

What would be the right way to handle the problem if ActionTypes would not be seen as a const ?
If we take the following example, things continue to break :
```typescript
interface Action {
  type: string
}
const makeSomeActionTypes = (name: string) => ({
  EXPAND: `${name}/expand`,
  RELOAD: `${name}/reload` 
})

const ActionTypes = {
  ...makeSomeActionTypes('my-feature'),
  FIXED: 'Typescript knows me'
} as const // Does not really work anymore, except for FIXED property

class Expand implements Action {
  readonly type = ActionTypes.EXPAND
  constructor(public id: string) { }
}
class Reload implements Action {
  readonly type = ActionTypes.RELOAD
  constructor(public id: string) { }
}
const isExpand = (action: Action): action is Expand => action.type === ActionTypes.EXPAND

function testSomething(action: Expand | Reload) {
  // Property 'id' does not exist on type 'never'
  return isExpand(action) ? `Expand action, id = ${action.id}` : `Reload action, node = ${action.id}` 
}
```

I understand we are back with EXPAND and RELOAD of type string, and I understand that Typescript cannot understand the type `${name}/expand`, but the code is valid and working as Javascript is concerned. How would one solve the problem ?

If I add a property `isExpand = true` to my Expand class, then Typescript is happy again. But isn't there a proper way to handle this use case ? I feel like this is a specific bug on how user defined guard works ?
I'll reopen the issue to wait for your feedback.

Playground link: 
https://www.typescriptlang.org/play/index.html#src=interface%20Action%20%7B%0D%0A%20%20type%3A%20string%0D%0A%7D%0D%0Aconst%20makeSomeActionTypes%20%3D%20(name%3A%20string)%20%3D%3E%20(%7B%0D%0A%20%20EXPAND%3A%20%60%24%7Bname%7D%2Fexpand%60%2C%0D%0A%20%20RELOAD%3A%20%60%24%7Bname%7D%2Freload%60%20%0D%0A%7D)%0D%0A%0D%0Aconst%20ActionTypes%20%3D%20%7B%0D%0A%20%20...makeSomeActionTypes('my-feature')%2C%0D%0A%20%20FIXED%3A%20'Typescript%20knows%20me'%0D%0A%7D%20as%20const%0D%0A%0D%0Aclass%20Expand%20implements%20Action%20%7B%0D%0A%20%20readonly%20type%20%3D%20ActionTypes.EXPAND%0D%0A%20%20constructor(public%20id%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0Aclass%20Reload%20implements%20Action%20%7B%0D%0A%20%20readonly%20type%20%3D%20ActionTypes.RELOAD%0D%0A%20%20constructor(public%20id%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0Aconst%20isExpand%20%3D%20(action%3A%20Action)%3A%20action%20is%20Expand%20%3D%3E%20action.type%20%3D%3D%3D%20ActionTypes.EXPAND%0D%0A%0D%0Afunction%20testSomething(action%3A%20Expand%20%7C%20Reload)%20%7B%0D%0A%20%20return%20isExpand(action)%20%3F%20%60Expand%20action%2C%20id%20%3D%20%24%7Baction.id%7D%60%20%3A%20%60Reload%20action%2C%20node%20%3D%20%24%7Baction.id%7D%60%20%0D%0A%7D
