### ISSUE TITLE
Copying arrays using spread operator

### ISSUE THREAD

**Issue by maryo** [Microsoft/TypeScript#3096]
```js
let a = ['a', 'b', 'c'];
let b = [...a]; // should create an array copy
console.log(a === b); // should be false but it's true when compiled to <ES6
```

**Comment by DanielRosenwasser** [comment]
I think this needs to be fixed for 1.5 proper.

I assume the emit for the declaration of `b` becomes something like

```TypeScript
let b = [].concat(a);
```

**Comment by ahejlsberg** [comment]
@DanielRosenwasser It would be more efficient to emit
```javascript
var b = a.slice();
```
That way you're not creating and throwing away an empty array.

**Comment by kitsonk** [comment]
Yes, slice appears to be more efficient: https://jsperf.com/array-copy-slice-concat
