### ISSUE TITLE
Property "prototype" is missing.

### ISSUE THREAD

**Issue by yakimchuk** [Microsoft/TypeScript#3097]
When i'm trying to get a prototype of constructor, which is passed as method option, compiler is throwing error 'Property "prototype" is missing,'.

Link: http://www.typescriptlang.org/Playground#src=declare%20class%20Foo%20%7B%0A%09bar%3A%20number%0A%7D%0A%0Aclass%20Baz%20%7B%0A%0A%20%20%20%20something(Constructor%3A%20Foo)%20%7B%0A%0A%09%09Constructor.prototype%3B%20%2F%2F%20prototype%20not%20found%0A%0A%20%20%20%20%7D%0A%0A%7D

```typescript
declare class Foo {
	bar: number
}

class Baz {

    something(Constructor: Foo) {

		Constructor.prototype; // prototype not found

    }

}
```

What's wrong? Why it error has appeared?

**Comment by DanielRosenwasser** [comment]
In your example, the parameter named `Constructor` is not actually typed as a constructor function, it's an *instance* of `Foo`. If you want to access the constructor of `Foo` itself, you should type the parameter as `typeof Foo`:

```TypeScriot
declare class Foo {
    bar: number
}

class Baz {
    something(Constructor: typeof Foo) {
        Constructor.prototype; // works
    }
}
```

Does that help?

**Comment by yakimchuk** [comment]
Daniel,

Yes, you right. Thank you.
Please, close this case, it's not a issue.
