### ISSUE TITLE
Const context does not work for symbols

### ISSUE THREAD

**Issue by Lodin** [Microsoft/TypeScript#30974]
**TypeScript Version:**  3.5.0-dev.20190416

**Search Terms:** symbol, const context, literal

**Code**

```ts
const test = {
    foo: Symbol(), // still "symbol" instead of "unique symbol"
} as const;

interface Bar { 
    // Error: A computed property name in an interface must
    // refer to an expression whose type is a literal type or a
    // 'unique symbol' type.
    [test.foo]: 1;
}
```

**Expected behavior:**
No error since const context makes literals immutable and prevents type widening. 

**Actual behavior:**
Error is thrown:
```
Error: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
```

**Playground Link:** 
[link](http://www.typescriptlang.org/play/index.html#src=const%20test%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20Symbol()%2C%0D%0A%7D%20as%20const%3B%0D%0A%0D%0Ainterface%20Bar%20%7B%20%0D%0A%20%20%20%20%5Btest.foo%5D%3A%201%3B%0D%0A%7D)

**Related Issues:** 
#29510

**Comment by RyanCavanaugh** [comment]
This was an intentional scoping of `as const`. Unique symbols don't really behave the same way as literal types.

**Comment by Lodin** [comment]
@RyanCavanaugh, what is the exact difference? This issue blocks the whole area of possible solutions which can be freely used with JavaScript. For now, symbols that are not defined in the module's root cannot be used as a computed property without dirty hacks, and that's kind of frustrating.
