### ISSUE TITLE
Docs are wrong: export = and import = require(), says latter is required incorrectly

### ISSUE THREAD

**Issue by marcospgp** [microsoft/TypeScript#30976]
The documentation regarding `export = and import = require()` at https://www.typescriptlang.org/docs/handbook/modules.html is wrong. It says:

```
When exporting a module using export =, TypeScript-specific import module = require("module") must be used to import the module.
```

Whereas I've been able to `import from` and `import as` for modules that export using `export =`.

**Comment by hiteshvijayhv** [comment]
Can I work on this?

**Comment by hiteshvijayhv** [comment]
#2700

**Comment by hiteshvijayhv** [comment]
@marcospgp does it look right?

**Comment by marcospgp** [comment]
I'm not sure this is correct as looking back I was using a custom implementation of a TS to JS transpiler. Maybe the docs were actually correct here.
