### ISSUE TITLE
Paths not resolving

### ISSUE THREAD

**Issue by oleersoy** [Microsoft/TypeScript#30972]
First I cloned this project:
`git clone git@github.com:fireflysemantics/validator.git`

Then updated the the `tsconfig.json` with this path configuration:

```
"baseUrl": "./",                          /* Base directory to resolve non-absolute module names. */
"paths": {
  "@fs": ["./src"], 
  "@test": ["./test"]
}, 
```

Then I tried editing the src/container/error/index.ts so that it looks like this:
```
export { ObjectErrors } from "@fs/container/error/ObjectErrors";
export { ValidationError } from "./ValidationError";
```
When I compile Typescript still generates this error:

> src/container/error/index.ts:1:30 - error TS2307: Cannot find module '@fs/container/error/ObjectErrors'.

I have links to comments from SO people in the previous issue I filed.  IIUC this should work.

https://github.com/Microsoft/TypeScript/issues/30619#issuecomment-483831098

**Comment by RyanCavanaugh** [comment]
It seems like you're describing a problem that requires three files (an exporter, an importer, a tsconfig file) and this repo has 400 files.

We really, really do need minimal repos we can read from here to proceed

**Comment by sheetalkamat** [comment]
You can also use `--traceResolution` to see what paths compiler is looking at and why it doesnt find module to see if there is any configuration error.

**Comment by oleersoy** [comment]
@sheetalkamat thanks for the `--traceResolution` heads up.  I'll try that out.  This is the output I get from a fresh clone and compile:
```
ole@mki:~$ git clone git@github.com:fireflysemantics/validator.git
Cloning into 'validator'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 925 (delta 131), reused 150 (delta 109), pack-reused 751
Receiving objects: 100% (925/925), 545.30 KiB | 3.01 MiB/s, done.
Resolving deltas: 100% (670/670), done.
ole@mki:~$ cd validator/
ole@mki:~/validator$ npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 745 packages from 777 contributors and audited 852357 packages in 8.223s
found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
ole@mki:~/validator$ code .
ole@mki:~/validator$ npm run compile

> @fireflysemantics/validator@1.1.11 compile /home/ole/validator
> del-cli target && tsc

ole@mki:~/validator$ 

```

@RyanCavanaugh are you seeing something else?

**Comment by oleersoy** [comment]
The person who answered my SO question said this:

> Your solution is weirdly supposed to work, but the docs use no globs and there have been some reported intellisense bugs when using globs.

So I'm trying to figure out whether first whether what I'm doing is supported (At least by the Typescript spec)?  Should removing the Glob patterns work?

**Comment by oleersoy** [comment]
I think I see what's going on now.  Compiling works, but it seems like the Jest setup does not understand how to resolve `paths`.  I'll just close this for now and file and issue with Jest.
