### ISSUE TITLE
Property 'fonts' does not exist on type 'Document'

### ISSUE THREAD

**Issue by leinov** [Microsoft/TypeScript#30984]
when i use document.fonts.ready to load web fonts ,the console show error tell me  

> Property 'fonts' does not exist on type 'Document'

and when i use new FontFace() the console show 

> Cannot find name 'FontFace

**Comment by RyanCavanaugh** [comment]
Experimental APIs aren't in the lib file.

**Comment by leinov** [comment]
> Experimental APIs aren't in the lib file.

yes so i solve it by use 
`(documentas any).fonts.ready `

**Comment by bennypowers** [comment]
For those arriving from Google who just want it to work, add this to an ambient declaration file

```ts
type CSSOMString = string;
type FontFaceLoadStatus = 'unloaded'|'loading'|'loaded'|'error';
type FontFaceSetStatus = 'loading'|'loaded';

interface FontFace {
  family: CSSOMString;
  style: CSSOMString;
  weight: CSSOMString;
  stretch: CSSOMString;
  unicodeRange: CSSOMString;
  variant: CSSOMString;
  featureSettings: CSSOMString;
  variationSettings: CSSOMString;
  display: CSSOMString;
  readonly status: FontFaceLoadStatus;
  readonly loaded: Promise<FontFace>;
  load(): Promise<FontFace>;
}

interface FontFaceSet {
  readonly status: FontFaceSetStatus;
  readonly ready: Promise<FontFaceSet>;
  check(font: string, text?: string): Boolean;
  load(font: string, text?: string): Promise<FontFace[]>
}

declare global {
  interface Document {
    fonts: FontFaceSet
  }
}
```

**Comment by ixrock** [comment]
@bennypowers thank for the help!

Here is a bit extended and working (for me) version of these declarations (just drop a file in project's folder):

```ts
// File: project/src/types/font-face.d.ts
// https://www.w3.org/TR/css-font-loading/
export {}

declare global {
  const FontFace: FontFace;

  interface Document {
    fonts: FontFaceSet
  }

  type CSSOMString = string;
  type FontFaceLoadStatus = 'unloaded' | 'loading' | 'loaded' | 'error';
  type FontFaceSetStatus = 'loading' | 'loaded';

  interface FontFace extends FontFaceDescriptors {
    new(family: string, source: string | ArrayBuffer, descriptors?: FontFaceDescriptors): FontFace;
    readonly status: FontFaceLoadStatus;
    readonly loaded: Promise<FontFace>;
    variationSettings: CSSOMString;
    display: CSSOMString;
    load(): Promise<FontFace>;
  }

  interface FontFaceDescriptors {
    family: CSSOMString;
    style: CSSOMString;
    weight: CSSOMString;
    stretch: CSSOMString;
    unicodeRange: CSSOMString;
    variant: CSSOMString;
    featureSettings: CSSOMString;
  }

  interface FontFaceSet extends Iterable<FontFace> {
    readonly status: FontFaceSetStatus;
    readonly ready: Promise<FontFaceSet>;
    add(font: FontFace): void;
    check(font: string, text?: string): Boolean; // throws exception
    load(font: string, text?: string): Promise<FontFace[]>
    delete(font: FontFace): void;
    clear(): void;
  }
}
```

**Comment by tomasdev** [comment]
@RyanCavanaugh @leinov `document.fonts` is not technically an experimental API anymore https://caniuse.com/font-loading -- could we add its defs to TS?

**Comment by thw0rted** [comment]
Trackback to https://github.com/Microsoft/TypeScript/issues/13569, which links to `@types/css-font-loading-module`

**Comment by imrishabh18** [comment]
For someone noob like me who still couldn’t make out what to do even after these answers above 😅. You just have to run this command `npm i -S @types/css-font-loading-module` and you are good to go.

**Comment by BenRacicot** [comment]
@RyanCavanaugh could we get the team's attention on the now-accepted font modules?

**Comment by tvkit** [comment]
@imrishabh18   thanks!

In my case, this too within the given TS file:

`import "@types/css-font-loading-module";
`

**Comment by Sergiobop** [comment]
@tvkit I also needed this to avoid:
`error TS2339: Property 'fonts' does not exist on type 'Document'.`

After the install suggested by @imrishabh18

**Comment by pzrq** [comment]
For me using `@testing-library/react` and Jest downstream, I was still getting errors like:

```
Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined

**Comment by pzrq** [comment]
For me using `@testing-library/react` and Jest downstream, I was still getting errors like:

```
Cannot read property 'ready' of undefined
TypeError: Cannot read property 'ready' of undefined
```

I finally got to a state that makes TypeScript happy, thanks @imrishabh18 for the npm-based variant:

    yarn add -D @types/css-font-loading-module


```
  beforeEach(() => {
    document.fonts = {
      ...document.fonts,
      ready: {
        ...((document.fonts && document.fonts.ready) || {}),
        then: jest.fn()
      }
    };
  });
```

Improvements welcome 😄

**Comment by calebwaldner** [comment]
> For someone noob like me who still couldn’t make out what to do even after these answers above 😅. You just have to run this command `npm i -S @types/css-font-loading-module` and you are good to go.

THANK YOU! I also had to add `css-font-loading-module` to my types array in `tsconfig.json`

**Comment by 205g0** [comment]
@ahejlsberg @RyanCavanaugh would be awesome if anyone of the team could take care and/or give an update, thanks 🙂
