### ISSUE TITLE
The behavior is different for two code that looks the same

### ISSUE THREAD

**Issue by kgtkr** [microsoft/TypeScript#30988]
**TypeScript Version:**  3.4.2

**Search Terms:**
`conditional type`

**Code**

OK
```ts
type F<X> = <T>() => T extends X ? 1 : 2;

declare const x: F<any>;
const y: F<number> = x;
```

Error
```ts
declare const x: <T>() => T extends any ? 1 : 2;
const y: <T>() => T extends number ? 1 : 2 = x;
```

**Expected behavior:**
The two codes do the same thing

**Actual behavior:**
Different behavior

**Playground Link:** 

**Related Issues:**

**Comment by jack-williams** [comment]
I think the effect of the type alias `F` is causing reduction in the body of the alias, in particular, I think it's simplifying the return type to the constraint of the conditional `1 | 2`. Once this happens, the type parameter `X` no longer appears in the type and the two signatures are related.
```ts
type F<X> = <T>() => T extends X ? 1 : 2;
declare const x: F<number>;
const y: F<string> = x; // no error

type F2<X> = <T>() => T extends X ? 1 : 2;
const y2: F2<string> = x; // error
```
Haven't got as far as tracking down _where_ exactly this behaviour comes from, but I'm guessing there is some instantiation business going on.

**Comment by kgtkr** [comment]
Related code

![image](https://user-images.githubusercontent.com/17868838/56331746-9dc81600-61c8-11e9-8673-714f8c60807b.png)

**Comment by RyanCavanaugh** [comment]
These samples are quite different and it's not apparent why they must behave identically.
