### ISSUE TITLE
Allow types that can be inferred to not be explicitly defined when with generic type that must be defined

### ISSUE THREAD

**Issue by ClickerMonkey** [Microsoft/TypeScript#30986]
## Search Terms

- infer extends keyof
- extends keyof default
- type default inferred

## Suggestion

(sorry If I'm not using the proper terminology)

Allow a type specified on a generic function to not be required when it's inferred based on what the user has entered. Not sure if new syntax would be needed, perhaps.

## Use Cases

I'm writing complex types for popular libraries and some functions can't be represented with Typescript without unnecessary verboseness.

## Examples

[Link to Playground](https://www.typescriptlang.org/play/#src=%0D%0A%2F%2F%20You%20have%20to%20have%20T%20and%20the%20following%20types%20separate%2C%20to%20allow%20K%20to%20be%20inferred%20while%20requiring%20T%0D%0Atype%20Mapper%3CT%3E%20%3D%20%3CK%20extends%20keyof%20T%2C%20U%20%3D%20%7B%20%5BP%20in%20K%5D%3A%20T%5BP%5D%20%7D%3E%20(keys%3A%20K%5B%5D)%20%3D%3E%20U%3B%0D%0A%0D%0Ainterface%20Test%20%7B%0D%0A%20%20num%3A%20number%3B%0D%0A%20%20str%3A%20string%3B%0D%0A%20%20bool%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Alet%20mapperTest%3A%20Mapper%3CTest%3E%3B%0D%0A%0D%0A%2F%2F%20Works%20perfectly%0D%0Aconst%20a%20%3D%20mapperTest(%5B'num'%2C%20'str'%5D)%3B%0D%0A%2F%2F%20a%20%3D%20%7B%20num%3A%20number%2C%20str%3A%20string%20%7D%0D%0A%0D%0A%2F%2F%20What%20I%20actually%20need%20to%20do%3A%0D%0Alet%20mapperDesired%20%3D%20function%20%3CT%2C%20K%20extends%20keyof%20T%2C%20U%20%3D%20%7B%20%5BP%20in%20K%5D%3A%20T%5BP%5D%20%7D%3E(keys%3A%20K%5B%5D)%3A%20U%20%7B%0D%0A%20%20return%20%7B%7D%20as%20U%3B%20%2F%2F%20implementation%20unimportant%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Desired%20(does%20not%20work%20without%20specifying%20K)%0D%0Aconst%20b%20%3D%20mapperDesired%3CTest%3E(%5B'num'%2C%20'bool'%5D)%3B%0D%0A%2F%2F%20b%20%3D%20%7B%7D%0D%0A%0D%0A%2F%2F%20Works%2C%20definitely%20not%20desired%0D%0Aconst%20c%20%3D%20mapperDesired%3CTest%2C%20'num'%20%7C%20'bool'%3E(%5B'num'%2C%20'bool'%5D)%3B%0D%0A%2F%2F%20c%20%3D%20%7B%20num%3A%20number%2C%20bool%3A%20boolean%20%7D)

```typescript
// simplified example
function mapperDesired <T, K extends keyof T, U = { [P in K]: T[P] }>(keys: K[]): U {
  return {} as U; // implementation unimportant
}

// desired use (doesn't work)
interface Test { str: string, num: number, bool: boolean }
const a = mapperDesired<Test>(['str', 'num']);
// expected a = { str: number, num: number }
// Works, but definitely not ideal for users
const b = mapperDesired<Test, 'str' | 'bool'>(['str', 'bool']);

// this works, but is not an option unfortunately
type Mapper<T> = <K extends keyof T, U = { [P in K]: T[P] }> (keys: K[]) => U;
const mapperTest: Mapper<Test> = ...
// works, but requires another layer of types
const c = mapperTest(['num', 'bool']);

// if you try to set a default value for K, the function no longer returns the proper type.
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
#26242 ?

**Comment by ClickerMonkey** [comment]
Yeah basically, but more so the related https://github.com/Microsoft/TypeScript/issues/10571

Looks like a duplicate, my apologies
