### ISSUE TITLE
Missing WebGL2 and Bitmap Renderer in Canvas and OffscreenCanvas definitions in latest build

### ISSUE THREAD

**Issue by jeffreytgilbert** [microsoft/TypeScript#30998]
**TypeScript Version:**  3.5.0

**Search Terms:** Canvas, OffscreenCanvas, WebGL2, Bitmap Renderer

**Expected behavior:**
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/getContext#Return_value

**Actual behavior:**
Missing WebGL2 and Bitmap Renderer in Canvas and OffscreenCanvas definitions in latest 3.5.0 build of typescript. EventTarget definitions incorrectly refer to HTMLCanvasElement, which OffscreenCanvas does not support. Instead, event listeners should use the EventTarget definition: https://dom.spec.whatwg.org/#interface-eventtarget

**Comment by jeffreytgilbert** [comment]
Also, texImageSource should be updated to include OffscreenCanvas 

https://www.khronos.org/registry/webgl/specs/latest/1.0/#WEBGLRENDERINGCONTEXT

**Comment by jeffreytgilbert** [comment]
![Screen Shot 2019-04-17 at 4 12 57 PM](https://user-images.githubusercontent.com/54642/56321230-b0d8d880-612b-11e9-8e0f-825cc834e76a.png)

I was thinking this was initially thinking this was a bug ticket, but then i switched it to a feature request when i saw WebGL 2 support was not present, but now I'm thinking there might also be bugs. Full disclosure: I'm no typescript expert.

**Comment by jeffreytgilbert** [comment]
![Screen Shot 2019-04-17 at 4 19 07 PM](https://user-images.githubusercontent.com/54642/56321553-905d4e00-612c-11e9-8aaa-8f67cb23a33d.png)
Just to be clear, what I keep running into right now is Typescript can't distinguish between the available signatures and pick the right one. That in turn results in errors in the IDE and through the build actions.

**Comment by jeffreytgilbert** [comment]
Under index.d.ts, there is only 1 signature, and it's for WebGL2. Why wouldn't that be alongside the webgl, 2d, and bitmaprenderer signatures in lib.dom.d.ts?

**Comment by jeffreytgilbert** [comment]
Hi @nkemnitz @karhu can you help me reason through this.

**Comment by nkemnitz** [comment]
Until it's fixed, you can try avoiding those ambiguity-related errors by being a lot more explicit:
```ts
function getWebGLRenderingContext(webGLVersion: number): WebGLRenderingContext {
  const WEBGL_ATTRIBUTES = {};

  const canvas = typeof OffscreenCanvas === 'function' ?
    new OffscreenCanvas(1, 1) :
    document.createElement('canvas');

  if (webGLVersion === 1) {
    if (canvas instanceof OffscreenCanvas) {
      return (canvas.getContext('webgl', WEBGL_ATTRIBUTES)) as WebGLRenderingContext;
    } else {
      return (canvas.getContext('webgl', WEBGL_ATTRIBUTES) ||
              canvas.getContext('webgl-experimental', WEBGL_ATTRIBUTES)) as WebGLRenderingContext;
    }
  } else {
    if (canvas instanceof OffscreenCanvas) {
      return (canvas.getContext('webgl2', WEBGL_ATTRIBUTES)) as WebGLRenderingContext;
    } else {
      return (canvas.getContext('webgl2', WEBGL_ATTRIBUTES)) as WebGLRenderingContext;
    }
  }
}
```

The OffscreenCanvas+WebGL2 path however will still fail. The [WebGL2 typings from DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webgl2/index.d.ts) that you use don't override `OffscreenCanvas.getContext`, yet.

**Comment by jakebailey** [comment]
This was all done in the linked https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/698 and pulled in here in #40500.
