### ISSUE TITLE
Cannot type flatMap polyfill

### ISSUE THREAD

**Issue by texastoland** [Microsoft/TypeScript#31015]
**TypeScript Version:**  3.4.3

**Search Terms:**

**Code**

```ts
Array.prototype.flatMap = function(f, that?) {
  type ElementType<T> = T extends readonly any[] ? T[number] : T
  const ys: ElementType<ReturnType<typeof f>>[] = []
  this.forEach((x, i, xs) => {
    const y = f.call(that!, x, i, xs)
    Array.isArray(y) ? ys.push(...y) : ys.push(y)
  })
  return ys
}
```

**Expected behavior:**

This an umbrella issue. I ran into multiple issues trying to polyfill `Array#flatMap` without duplicating the type signature from `"lib": ["esnext"]`:

```ts
interface Array<T> {
    flatMap<U, This = undefined> (
        callback: (this: This, value: T, index: number, array: T[]) => U|ReadonlyArray<U>,
        thisArg?: This
    ): U[]
}
```

**Actual behavior:**

1. `ReturnType<typeof Array.prototype.flatMap>` types as `{}[]`.
2. `ElementType<ReturnType<typeof f>>` types as `U | ElementType<U>` instead of unifying on `U`.
3. `f.call(that, x, i, xs)` errors with `Argument of type 'This | undefined' is not assignable to parameter of type 'This'.`.
4. Type guards don't appear to work in `Array.isArray(y) ? ys.push(...y) : ys.push(y)`. The inferred types are `(U | readonly U[]) ? (any[]) : (U | readonly U[])`. I suspect it has to do with `readonly`.

**Playground Link:** 

Not reproducible on the Playground, because it requires `"lib": ["esnext"]`. I could share a CodeSandbox, though.

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
What is the **bug** here?

**Comment by texastoland** [comment]
The 4 numbered under _Actual behavior_ I would all qualify as bugs. I'm trying to track down related tickets, but it's the first time ever using TypeScript that I've encountered several at once. I reported it as an umbrella issue, because it's not at all contrived code. I'm just trying to implement a type in the standard lib.

**Comment by RyanCavanaugh** [comment]
1: I don't see this in 3.4
2: This is the correct behavior; the resolution needs to be deferred until instantiation
3: That's a correct error
4: #17002

**Comment by texastoland** [comment]
Thank you!

1. I'm on `3.4.3`:
    ```ts
    type MapRet = ReturnType<typeof Array.prototype.map>
    // => type MapRet = {}[]
    // type MapRet<T> = ReturnType<typeof Array.protot ype.map<T>>
    // => error: '>' expected.
    ```
2. 👍
3. Does that mean the library signature is unimplementable? I couldn't find any documentation on `<This = undefined>` and I couldn't make it work with an explicit signature, either.
4. 🙏

**Comment by noinkling** [comment]
As a TS newbie I'm not actually sure this is related (apologies if it's not) but I just ran into the below issue with `flatMap` and `flat`:

```typescript
// Map<string, number[]>
const myMap = new Map([
  ['foo', [1, 2, 3]],
  ['bar', [4, 5, 6]]
]);

// string[]
const myArray = ['foo', 'bar', 'baz'];

// (key: any) => number[] | undefined
const mapFn = key => myMap.get(key);

const flatMapped = myArray.flatMap(mapFn);
```
```
Argument of type '(key: any) => number[] | undefined' is not assignable to parameter of type '(this: undefined, value: string, index: number, array: string[]) => number | readonly number[]'.
  Type 'number[] | undefined' is not assignable to type 'number | readonly number[]'.
    Type 'undefined' is not assignable to type 'number | readonly number[]'. ts(2345)
```

If I do the two operations separately:

```typescript
// (number[] | undefined)[]
const mapped = myArray.map(key => myMap.get(key));

const flattened = mapped.flat();
```
`flattened` is inferred as `any[]`.

I would expect the type for `flatMapped`/`flattened` to be inferred as `(number | undefined)[]`. Am I just missing something?

- TS version: 3.4.3
- VS Code version: 1.33.1
- `strictNullChecks` on

**Comment by texastoland** [comment]
It's a different issue. `flatMap` expects a function that returns a type `U | `readonly U[]` (some type or an array of that type). Your function returns `undefined | number[]`. `undefined` doesn't match with `number`.

**Comment by noinkling** [comment]
Yup my apologies, I reread the original issue again and realized too late. I've created a new issue over at #31033

**Comment by texastoland** [comment]
> 1\. `ReturnType<typeof Array.prototype.flatMap>` types as `{}[]`.

#28655 et al. with [workaround](https://dev.to/busypeoples/notes-on-typescript-returntype-3m5a).

> 3\. I couldn't find any documentation on `<This = undefined>`

[Release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults).

> I couldn't make `call(that, ...)` work with an explicit signature, either.

`call<?This, Blabbity, Bloop>(that, ...)`.

> 3\. Does that mean the `flatMap<U, This = undefined>` signature is unimplementable?

Not without dancing around null checks, no.
