### ISSUE TITLE
Should `keyof` string mapped type equal `keyof` string index signature?

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#31013]
**TypeScript Version:**  3.4.1

**Search Terms:** mapped types keyof index signatures

**Code**

I understand that `keyof` on a `string` index signature returns `string | number` as per:

> If X contains a string index signature, keyof X is a union of string, number, and the literal types representing symbol-like properties, otherwise

- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html
- https://stackoverflow.com/a/51808262/5932012

```ts
declare const key1: keyof { [key: string]: unknown }; // string | number
```

However, I want to ask why the same behaviour doesn't apply to `Record<string, T>` aka `{ [K in string]: T }`:

```ts
declare const key2: keyof Record<string, unknown>; // string
```

I would expect `keyof` on the mapped type example to behave similarly to how it does with index signature example, because both objects can be used in the same way (`number` keys are coerced to `string`s):

``` ts
{
    // number keys are coerced to strings when writing
    const obj1: { [key: string]: unknown } = {
        1: 'foo',
        foo: 'bar',
    };
    
    // number keys are coerced to strings when reading
    obj1['1'];
    obj1[1];
}

{
    // number keys are coerced to strings when writing
    const obj1: Record<string, unknown> = {
        1: 'foo',
        foo: 'bar',
    };

    // number keys are coerced to strings when reading
    obj1['1'];
    obj1[1];
}
```

**Comment by RyanCavanaugh** [comment]
The root cause here is #13715 and the assignability of numeric index signatures to string index signatures.

As for that behavior not applying to mapped types, well, producing different behavior is why we add different syntax.

For deeper research, start at #23592

**Comment by jcalz** [comment]
Searching for an answer to [this SO question](https://stackoverflow.com/questions/56960841) brought me here.

Oddly enough, IntelliSense seems to hide the distinction between the mapped type and the string index signature:

```ts
type Index = { [x: string]: number };
// IntelliSense:
// type Index = {
//    [x: string]: number;
// }

type Mapped = { [x in string]: number };
// IntelliSense:
// type Mapped = {
//    [x: string]: number;
// } 
```
[Playground](https://www.typescriptlang.org/play/#code/C4TwDgpgBAkgdgEwgDygXigbygbWQLigGdgAnASzgHMBdQuAVwFsAjCUqAXwG4BYAKAD0g2HGAQANhPIBlCHCIR8A4VFCRRSVBkwqRUA3kIkK1OlEat2fISM4CB66AFkAhmEgJ0WXKkrEySlp6ZjYOHj1RcSlZeUVlWzVwF3dPb11Eg19jQLMQq1IbVU4gA)
