### ISSUE TITLE
Copyright notice on helper code can easily be misunderstood as applying to the whole output

### ISSUE THREAD

**Issue by marijnh** [Microsoft/TypeScript#31016]
When compiling any code that requires helper shims (say `class X extends Y {}`, which will pull in `__extends`), your output file will start big a big loud copyright notice (pasted below). This is fair, I guess, since those 10 lines of code _are_ owned by Microsoft, but I've had several people get confused when looking at the file and concluding the whole thing is owned by Microsoft and released under Apache.

Would it be possible to adjust the comment structure a bit so that it's more obvious that it's only referring to the helpers? Maybe move the bottom asterisk separator _below_ the helpers and add a few words to the effect of "this _section_ copyright (c) Microsoft etc ..."?

```javascript
/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
```

**TypeScript Version:**  3.4.3

**Comment by RyanCavanaugh** [comment]
It sounds like you're using a concatenating build system of some sort? This isn't emitted by TypeScript itself; it's just the top of https://github.com/Microsoft/tslib/blob/master/tslib.js

You'd see the same behavior for pretty much any licensed file, e.g. https://unpkg.com/react@16.8.6/cjs/react.development.js -- it seems like your bundler should be the one adding sectional headers if this is creating an undesirable output for you.

**Comment by marijnh** [comment]
Ah, indeed, that (rollup-plugin-typescript2) was the issue! Sorry for the noise.
