### ISSUE TITLE
Wrong `this` type infered in spread objects.

### ISSUE THREAD

**Issue by DeividasBakanas** [microsoft/TypeScript#31010]
**TypeScript Version:**  3.5.0-dev.20190418

**Search Terms:** `spread infer`.

**Code**

```ts
export const y = {
  ...{
    getPropertyA() {
      return this.property;
    },
    property: 'propertyValue',
  },
  ...{
    getPropertyB() {
      return this.property;
    },
  },
};
```

**Expected behavior:**
`this.property` should be reachable in `getPropertyB`.

**Actual behavior:**

Error `Property 'property' does not exist on type '{ getPropertyB(): any; }'.`, when `noImplicitThis` compiler option is selected.

**Playground Link:** 
http://www.typescriptlang.org/play/#src=export%20const%20y%20%3D%20%7B%0D%0A%20%20...%7B%0D%0A%20%20%20%20getPropertyA()%20%7B%0D%0A%20%20%20%20%20%20return%20this.property%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20property%3A%20'propertyValue'%2C%0D%0A%20%20%7D%2C%0D%0A%20%20...%7B%0D%0A%20%20%20%20getPropertyB()%20%7B%0D%0A%20%20%20%20%20%20return%20this.property%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%7D%2C%0D%0A%7D%3B

P.S.: please select `noImplicitThis` in the playground, because it's not selected by default.

**Comment by RyanCavanaugh** [comment]
Unless this becomes a common coding pattern, it doesn't really seem worth the cost/complexity to detect this case. You can always add a `this` parameter to specify what's going on
