### ISSUE TITLE
Support ReadonlyArray.includes as a type guard

### ISSUE THREAD

**Issue by ExE-Boss** [Microsoft/TypeScript#31018]
## Search Terms

- ReadonlyArray type guard

## Suggestion

For cases where `ReadonlyArray`'s type argument is a subtype of string or some other type handled by `as const`, it’s useful to be able to do:
```ts
const VALID_VALUES = ['a' | 'b'] as const;
function doStuffIfValid(x: string) {
	if (VALID_VALUES.includes(x)) {
		// $ExpectType 'a' | 'b'
		x
	}
}
```
Note that the above produces an error on line 3 about `string` not being assignable to `'a' | 'b'` in the `VALID_VALUES.includes(x)` call.

## Use Cases

I want to use this to improve type guards within code that interacts with untyped third‑party JavaScript.

### some-module/index.ts
```ts
export type ValidValues = 'a' | 'b';
const VALID_VALUES = ['a' | 'b'] as const;

export function doStuffIfValid(thing: Record<string, string>, x: ValidValues): void;
export function doStuffIfValid(thing: Record<ValidValues, Record<string, string>>): void;

export function doStuffIfValid(thing: unknown, x?: unknown) {
	if (typeof x === 'string') {
		if (!VALID_VALUES.includes(x)) {
			throw new TypeError(`x must be one of ${VALID_VALUES} or undefined, got ${x}`);
		}
		// Do something where x is 'a' | 'b'
	} else if (typeof x !== 'undefined') {
		throw new TypeError(`x must be one of ${VALID_VALUES} or undefined, got ${x}`);
	}
}
```

#### Right now, `VALID_VALUES` has to be expressed as:
```ts
const VALID_VALUES = ['a' | 'b'] as unknown as TypeGuardReadonlyArray<ValidValues>;
interface TypeGuardReadonlyArray<T> extends ReadonlyArray<T> {
	includes(searchElement: unknown, fromIndex?: number): searchElement is T;
}
```
for the above to not cause compilation errors and the type guard to work properly.

Note that this only works correctly when `T` is a literal union type.

### untyped-third-party-code.js
```js
const stuff = require('some-module');

// Doesn't throw
stuff.doStuffIfValid({}, 'a');
stuff.doStuffIfValid({}, 'b');
stuff.doStuffIfValid({a: {}, b: {}});

// Throws during runtime, as this file is untyped third-party code.
stuff.doStuffIfValid({}, 'c');
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Without #15048, this is a problematic change. Consider:
```ts
const someStrings: ReadonlyArray<string> = ["a", "b", "c"];

function fn(x: number | string) {
  if (someStrings.includes(x)) {
    //
  } else {
    // here, x is assumed to be 'number', but that's wrong!
  }
}
fn("d");
```

**Comment by ExE-Boss** [comment]
That’s why I only want this to apply when `T` is a literal union type (i.e. the result of `as const`).

**Comment by RyanCavanaugh** [comment]
That has the same problem though. A type is always a bound on a value, not an exact specification
```ts

const someStrings: ReadonlyArray<"a" | "b" | "c"> = ["a"];

function fn(x: "b" | "x") {
  if (someStrings.includes(x)) {
    //
  } else {
    // here, x is wrongly assumed to be "x"
  }
}
fn("b");
```

**Comment by ExE-Boss** [comment]
Yeah, but you probably shouldn't be doing `const someStrings: ReadonlyArray<"a" | "b" | "c"> = ["a"];`, which is why I suggested this.

My use case is `const someStrings = ["a"] as const`.

**Comment by dacapo1142** [comment]
I encountered the same case.
Here is my workaround:

```typescript
const OS_TYPE = ['Linux', 'macOS', 'Windows'] as const
type OSType = typeof OS_TYPE[number]

//user defined type guard
function isOSType(s: string):s is OSType{
    if ((OS_TYPE as any as string[]).includes(s))
        return true;
    return false;
}
```

`as any as string[]` seems like a poor idea? Is there a better way?

**Comment by ExE-Boss** [comment]
Try `as readonly string[]`, or if that fails, `.includes(s as any)`.

**Comment by finnmerlett** [comment]
Here is a generic version of the typeguard:
```typescript
const isInArray = <T, A extends T>(
  item: T,
  array: ReadonlyArray<A>
): item is A => array.includes(item as A);
```

**Comment by artem-popov** [comment]
I'm using workaround:
`
type Status = 'idle' | 'loading' | 'ready' | 'error';
const statuses: Status[] = ['idle', 'loading', 'ready', 'error'];

const setStatus = status => {
          const domStatus = script.getAttribute('data-status');
          const domStatusGuarded = statuses.filter(item => item === domStatus).find(Boolean);

          return domStatusGuarded || status;
 };

`

**Comment by frux** [comment]
I faced the same issue and found a workaround which is very simillar to the one @artem-popov suggested. But I use one `.find` method instead of `.filter + .find`.

```ts
const myList = ['1', '2'] as const;

function doSomething(value: string) {
    // dirty hack to check if the value is one of entries of the list
    const _value = myList.find(key => key === value);

    if (_value) {
        // _value is "1" | "2"
    } else {
        // _value is any other string
    }
}
```

**Comment by frux** [comment]
BTW I don't understand why this issue was closed. Is there any sensible reasons why `Array.prototype.includes` can not be a typeguard?

**Comment by Sleepful** [comment]
Facing this right now, instead I have to do this work-around:

```ts
    const valid = ARRAY_OF_VALID_VALUES.find(
      (c): c is typeof ARRAY_OF_VALID_VALUES[number] => c === conn.key,
    )
```

so verbose...

**Comment by f0rmat1k** [comment]
@Sleepful `is` is not a cool in my opinion. Almost `any`

**Comment by fcostarodrigo** [comment]
```ts
interface ReadonlyArray<T> {
    /**
     * Determines whether an array includes a certain element, returning true or false as appropriate.
     * @param searchElement The element to search for.
     * @param fromIndex The position in this array at which to begin searching for searchElement.
     */
    includes(searchElement: T, fromIndex?: number): boolean;
}
```

The type of `searchElement` in the `includes` function shouldn't be `T`.

This type locks you on only passing values that belong to the array and the return of `includes` becomes only `true` instead of `boolean`. But you want to do things like `[1, 2].includes(x)`, you know that the array only has 1 and 2 and maybe the type of `x` is `number` and you just want to check if `x`, besides being a `number`, is actually 1 or 2.

So maybe a better type is

```ts
interface ReadonlyArray<T> {
    /**
     * Determines whether an array includes a certain element, returning true or false as appropriate.
     * @param searchElement The element to search for.
     * @param fromIndex The position in this array at which to begin searching for searchElement.
     */
    includes(searchElement: any, fromIndex?: number): searchElement is ReadonlyArray<T>[number];
}
```

**Comment by doronhorwitz** [comment]
This article explains the issue nicely and offers a pretty good helper as a workaround: https://fettblog.eu/typescript-array-includes/ (see under the _"Option 2: A helper with type assertions"_ header)

**Comment by f0rmat1k** [comment]
> This article explains the issue nicely and offers a pretty good helper as a workaround: https://fettblog.eu/typescript-array-includes/ (see under the _"Option 2: A helper with type assertions"_ header)

it uses `el as T` so it's not fair check

**Comment by doronlh** [comment]
> > This article explains the issue nicely and offers a pretty good helper as a workaround: https://fettblog.eu/typescript-array-includes/ (see under the _"Option 2: A helper with type assertions"_ header)
> 
> 
> 
> it uses casting `el as T` so it's not fair check

It doesn't need to be a fair check since it's a **workaround**. What's important is that the article explains well this particular shortcoming of Typescript and offers a cute workaround that's helpful until this shortcoming is fixed.

**Comment by doronhorwitz** [comment]
> > This article explains the issue nicely and offers a pretty good helper as a workaround: https://fettblog.eu/typescript-array-includes/ (see under the _"Option 2: A helper with type assertions"_ header)
> 
> it uses casting `el as T` so it's not fair check

It doesn't need to be a fair check since it's a **workaround**. What's important is that the article explains well this particular shortcoming of Typescript and offers a cute workaround that's helpful until this shortcoming is fixed (or not).

**Comment by f0rmat1k** [comment]
@doronhorwitz my point is any workaround is bad in typescript. Since you use `as Something` you can just cheat cast like:
```ts
const VALID_VALUES = ['a', 'b'];

function doStuffIfValid(x: string) {
	if (VALID_VALUES.includes(x)) {
		(x as unknown as typeof VALID_VALUES) // now x is typeof VALID_VALUES
	}
}
```
If you hid the casting somewhere deep, it's not better then any casting 'in place'. And this issue is from people, who don't like casting, because its' turning off fair checks. So pls stop offering cheats. We like typescript because it offers fait check (is most situation :))

**Comment by doronhorwitz** [comment]
> @doronhorwitz my point is any workaround is bad in typescript. Since you use `as Something` you can just cheat cast like:
> 
> ```ts
> const VALID_VALUES = ['a', 'b'];
> 
> function doStuffIfValid(x: string) {
> 	if (VALID_VALUES.includes(x)) {
> 		(x as unknown as typeof VALID_VALUES) // now x is typeof VALID_VALUES
> 	}
> }
> ```
> 
> If you hid the casting somewhere deep, it's not better then any casting 'in place'. And this issue is from people, who don't like casting, because it's turning off fair checks and you can get runtime error. So pls stop offering cheats. We like typescript because it offers fair check (is most situations :-) )

"Cheats"... well that escalated quickly.

**Comment by julian-kingman-lark** [comment]
> @RyanCavanaugh i would like to make that:
> 
> ```ts
> const someStrings: = ["a", "b", "c"] as const;
> 
> function fn(x: number | string) {
>   if (someStrings.includes(x)) {
>     // 'a' | 'b' | 'c'
>   } else {
>     // ok, still string | number, why not?
>   }
> }
> fn("d");
> ```

Love this solution, IMO this makes intuitive sense, any chance this could be opened?

**Comment by loberton** [comment]
> > @RyanCavanaugh i would like to make that:
> > ```ts
> > const someStrings: = ["a", "b", "c"] as const;
> > 
> > function fn(x: number | string) {
> >   if (someStrings.includes(x)) {
> >     // 'a' | 'b' | 'c'
> >   } else {
> >     // ok, still string | number, why not?
> >   }
> > }
> > fn("d");
> > ```
> 
> Love this solution, IMO this makes intuitive sense, any chance this could be opened?

Bumping this. Still aggravating that we have to cast around a very legitimate use case for `includes`. Closing this with the reasoning given so far is not sufficient, please do better for the TS community.

**Comment by RyanCavanaugh** [comment]
The reasoning is correct, not sure why people are mad at me. The feature described in that comment is #15048. Without that functionality, *there's no way to do what's being proposed* -- `includes` is just a method same as any that you might write in your code; there is no special sauce in the type system that causes `includes` to be/not be a type guard, and we don't intend to start adding weird special-cases like that which aren't reproducible in user types.

**Comment by loberton** [comment]
> ```ts
> interface ReadonlyArray<T> {
>     /**
>      * Determines whether an array includes a certain element, returning true or false as appropriate.
>      * @param searchElement The element to search for.
>      * @param fromIndex The position in this array at which to begin searching for searchElement.
>      */
>     includes(searchElement: T, fromIndex?: number): boolean;
> }
> ```
> 
> The type of `searchElement` in the `includes` function shouldn't be `T`.
> 
> This type locks you on only passing values that belong to the array and the return of `includes` becomes only `true` instead of `boolean`. But you want to do things like `[1, 2].includes(x)`, you know that the array only has 1 and 2 and maybe the type of `x` is `number` and you just want to check if `x`, besides being a `number`, is actually 1 or 2.
> 
> So maybe a better type is
> 
> ```ts
> interface ReadonlyArray<T> {
>     /**
>      * Determines whether an array includes a certain element, returning true or false as appropriate.
>      * @param searchElement The element to search for.
>      * @param fromIndex The position in this array at which to begin searching for searchElement.
>      */
>     includes(searchElement: any, fromIndex?: number): searchElement is ReadonlyArray<T>[number];
> }
> ```

The issue I and I believe several others have in this discussion is that `searchElement` is not inherently a type that is defined by the const array that `includes` is being called on. There's a legitimate use case where the parameter is of the same primitive type (`string`, `number`, etc) but is otherwise unknown.

In other words, I do not believe that this should result in a compiler error
```ts
const myArr = ["one", "two", "three"] as const;
const someString: string = "three";

myArr.includes(someString);
```

**Comment by RyanCavanaugh** [comment]
That's a different problem than whether or not `includes` is a type guard. See #26255 and https://github.com/microsoft/TypeScript/issues/26255#issuecomment-736680802

**Comment by spoike** [comment]
To be more precise/dynamic in this case the argument may be of type `unknown` (as `includes` pretty much don't need to know what the type is) and type predicate so TS may infer the argument to the type you want:

```
interface ReadonlyArray<T> {
    includes(arg: unknown, fromIndex?: number): arg is T
}
```

[Playground sample](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoTgEwPYgDYCeAglFHAQDwAqAfMgN4BQyLyoCeArphAM4AUcKAHMAXMk4gA1iGwB3EABpkMKNgC2ASRA8AHgH5xITuoBG0AJTihwtr2RVGAX0aM8EMMjjIAvMn4A2gCMygBMygDMygBEAELRALpe9gi4vGAWANyu7p4w2JxQvsjRRNHZwDD+cAB07Fw8AvmFFhYMzKypILzY7jV42ML8zVBZzkA)

**Comment by loberton** [comment]
Oh duh. Yeah, `unknown` appears to be what I needed. I refactored your sample a touch to use constants and a little stricter typing, but the `includes` definition is unchanged and what I intend to use. Thank you @spoike!! 😊

[Playground sample](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoTgEwPYgDYCeAglFHAQDwAqAfMgN4BQyLyoCeArphAM4AUcKAHMAXMk4gA1iGwB3EABpkMKNgC2ASRA8AHgH5xITuoBG0AJTihwtr2RVGAX0aMEuXmGRxkAXmQA2gCMygBMygDMygBEAELRALre9u4gngDcjGAEAA4oRABqcFx8fsjZedgw3gHGZtAJmW4eXjDYnFBl0UTRmcDVggB07Fw8Am0dFhYMzKypnsim4oXFnKX+E1DpyAD0OyrtncD20SAQAG7Q0bMs89h4EIN42ML80TilI9wQ0cqmFpknMgIHheCgmKxkPMvAhlkUSvYNodtntkARyMp3OocsAHp1oGpOmAABZwaT2MDYZDRY4OaIAQhuUI890ez1e72wpVkXi+PF+UIBziAA)

**Comment by karlismelderis-mckinsey** [comment]
I was burned by same issue

would it make sense to update public node `ReadonlyArray` & `Array` include types to accept `unknown`?

**Comment by Oblarg** [comment]
This should be reopened; this is a feature gap and there's absolutely no reason other than "we don't feel like prioritizing this" not to address it.

**Comment by btoo** [comment]
instead of hoping for the typescript maintainers to address this, i've decided to use `some` instead of `includes`:
```ts
const itemIsIncluded = array.some(item => item === itemToSearchForInclusion)
```

**Comment by RyanCavanaugh** [comment]
> This should be reopened; this is a feature gap and there's absolutely no reason other than "we don't feel like prioritizing this" not to address it.

It's been pointed out multiple times that this behavior would be wrong; it is true that we do not prioritize features that provide wrong behavior but I think that should be unobjectionable.

**Comment by msdsk-quinyx** [comment]
The solution I use and that doesn't include explicit casting:

```typescript
export const isInTuple = <A extends ReadonlyArray<K>, K>(
  tuple: A,
  key: K,
): key is A[number] => tuple.includes(key);
```

**Comment by fabien0102** [comment]
I’m just commenting for future reference (I always endup in this topic, frustrating that I can’t do such an easy task)

The "best" solution to deal with those type guards is to use a runtime validation library like zod


Example:
```ts
import { z } from "zod";

const FishEnum = z.enum(["Salmon", "Tuna", "Trout"]);
type FishEnum = z.infer<typeof FishEnum>;

const myFish = FishEnum.parse("myFish");
```

No type assertions or `any` are needed, so the code is very clean. As a bonus point, you have a nice error if the value is not correct!

![Image](https://github.com/user-attachments/assets/de85ee7b-17f1-420d-97b8-790af81a1ace)

(you can also choose to use `safeParse` if you want an easy way to handle the error, this is just an example)

I hope that helps the next person that comes here! Have a nice day :)

**Comment by MaxWoodDev** [comment]
+1 for reopen / reconsider

**Comment by RyanCavanaugh** [comment]
> +1 for reopen / reconsider

Scrolling up 3 comments:

> This should be reopened; this is a feature gap and there's absolutely no reason other than "we don't feel like prioritizing this" not to address it.

It's been pointed out multiple times that this behavior would be wrong; it is true that we do not prioritize features that provide wrong behavior but I think that should be unobjectionable.
