### ISSUE TITLE
TypeScript doesn’t properly handle a constructor with a quoted name

### ISSUE THREAD

**Issue by j-f1** [microsoft/TypeScript#31020]
**TypeScript Version:**  3.5.0-dev.20190418

**Search Terms:** typescript quoted constructor

**Code**

```ts
class Foo {
    constructor(name: string) {
      this.name = name
    }
}
class Bar {
    "constructor"(name: string) {
      this.name = name
    }
}

new Foo("hello")
new Bar("hello")
```

**Expected behavior:**
Compiles without error

**Actual behavior:**
The `new Foo` call compiles properly, but the `new Bar` call produces a type checking error:

```ts
test.ts:9:9 - error TS2554: Expected 0 arguments, but got 1.

9 new Bar("hello")
          ~~~~~~~
```

Note that running the code (with the type assertions stripped) [results in both constructors being called](https://observablehq.com/d/9ed31ae49ec56ac8), but TypeScript’s ES5 transpilation instead sets the second constructor as a method named `constructor`, which causes it not to be run.

**Playground Link:** [Open playground ↗️](https://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%0D%0A%20%20%20%20constructor(name%3A%20string)%20%7B%7D%0D%0A%7D%0D%0Aclass%20Bar%20%7B%0D%0A%20%20%20%20%22constructor%22(name%3A%20string)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Anew%20Foo(%22hello%22)%0D%0Anew%20Bar(%22hello%22)%0D%0A)

**Related Issues:** Encountered in https://github.com/prettier/prettier/issues/6063.

**Comment by MartinJohns** [comment]
The second code snippet does not create a constructor, it creates a property named `constructor`.

If you expect otherwise, then how would you expect to be able to define a property with that name?

**Comment by jcalz** [comment]
Issues #3841 (see [comment](https://github.com/Microsoft/TypeScript/issues/3841#issuecomment-163350868)) and #5989 (see [comment](https://github.com/Microsoft/TypeScript/issues/5989#issuecomment-163066313)) might be related in that they use this syntax as a workaround so that class instances could have strongly typed `constructor` properties.

**Comment by RyanCavanaugh** [comment]
We guessed wrong what the ES class semantics would be, which is pretty unfortunate now.

Not clear how to proceed since this will be a runtime breaking change for people who chose their method/property names extremely poorly.

**Comment by RyanCavanaugh** [comment]
Plan: Issue an error in 3.5 if we see this and `target` is `<= ES5`, then change the ES5 emit in 3.6.

**Comment by andrewbranch** [comment]
> Plan: Issue an error in 3.5 if we see this and target is <= ES5, then change the ES5 emit in 3.6.

Moving the milestone since the grammar error part is done. This issue now tracks

> change the ES5 emit
