### ISSUE TITLE
unable compile with clear type, got `property 'data' does not exist on type 'T' `

### ISSUE THREAD

**Issue by SilverLeaves** [Microsoft/TypeScript#31030]
**TypeScript Version:**  3.4.4

**Search Terms:**

https://github.com/ReactiveX/rxjs/issues/4718

**Code**

```json
{
  "scripts": {
    "dev": "ts-node ."
  },
  "dependencies": {
    "axios": "^0.18.0",
    "rxjs": "^6.4.0",
    "ts-node": "^8.1.0",
    "typescript": "^3.4.4"
  }
}

```

```ts
import * as rxjs from "rxjs";
import axios from "axios"

interface res {
    data: any[],
    count: number
}

let promiseSource$ = rxjs.from(axios.get<res>("http://govapi.pinza.com.cn/newsList"))

promiseSource$.subscribe((res) => { console.log(res.data.count) })
```

**Expected behavior:**
compiled

the answer
https://github.com/ReactiveX/rxjs/issues/4718#issuecomment-484744324

> 
> 
> It's working in the IDE - TypeScript is inferring the type of `data` - so the problem is most likely related to the version of TypeScript that you are using with `ts-node`, etc.
> 
> In short, this does not seem to be an issue with RxJS.

**Actual behavior:**

![图片](https://user-images.githubusercontent.com/31165554/56401545-fb716680-628b-11e9-82f2-39e8d2170ab9.png)

**Related Issues:** 
https://github.com/ReactiveX/rxjs/issues/4718

**Comment by MartinJohns** [comment]
It's working in the IDE - TypeScript is inferring the type of `data` - so the problem is most likely related to the tool that you are using: ts-node.

In short, this does not seem to be an issue with TypeScript.

**Comment by SilverLeaves** [comment]
@MartinJohns  run `tsc index.ts`， I got this
```bash
PS C:\Users\MI\Desktop\temp> tsc index.ts
node_modules/rxjs/internal/Observable.d.ts:89:59 - error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

89     toPromise<T>(this: Observable<T>, PromiseCtor: typeof Promise): Promise<T>;
                                                             ~~~~~~~

node_modules/rxjs/internal/types.d.ts:41:84 - error TS2304: Cannot find name 'Iterable'.

41 export declare type ObservableInput<T> = SubscribableOrPromise<T> | ArrayLike<T> | Iterable<T>;
                                                                                      ~~~~~~~~

node_modules/rxjs/internal/types.d.ts:45:6 - error TS2585: 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

45     [Symbol.observable]: () => Subscribable<T>;
        ~~~~~~


Found 3 errors.
```

**Comment by MartinJohns** [comment]
Run `tsc`, not `tsc index.ts`. When you specify source files, then your `tsconfig.json` is ignored.

**Comment by SilverLeaves** [comment]
@MartinJohns Thank you very much!
