### ISSUE TITLE
Importing a type with same name as an export

### ISSUE THREAD

**Issue by jmendeth** [microsoft/TypeScript#31031]
**TypeScript Version:**  3.5.0-dev.20190419

**Search Terms:** import export conflict priority

**Code**

```ts
/// foo.ts
export interface Foo { a: number; }

/// test.ts
import { Foo } from './foo'
export interface Foo { b: number; }
let foo: Foo = { a: 2 }
```

**Expected behavior:** Declaration conflict on `test.ts` (imported Foo vs exported Foo).

**Actual behavior:** No error. Instead, (see last line) `Foo` refers to the imported Foo, and the exported Foo becomes unaccessible. Is this expected?

If `export interface` is changed to `export class`, then a declaration conflict appears.  
If `export` is removed in initial case, a declaration conflict also appears.

**Playground Link:** I don't know how to reproduce this with one file.

**Related Issues:** I searched issues, stackoverflow and docs (declaration merging, imports and exports, namespaces) but couldn't find any references to this behaviour.

**Comment by collin5** [comment]
Hmm, I see. Will be taking a crack at this by end of the week.

**Comment by collin5** [comment]
Same with 
```typescript
/// test1.ts
export interface Foo { a: number }  // does not error
export interface Foo { a: number  } // does not error

/// test2.ts
export class Foo { a: number }  // errors
export class Foo { a: number  } // errors

/// test3.ts
interface Foo { a: number }  // does not error
interface Foo { a: number  } // does not error

/// test4.ts
export interface Foo { a: number }  // errors
interface Foo { a: number  } // errors
```

**Comment by collin5** [comment]
Raised a PR to resolve this here (https://github.com/Microsoft/TypeScript/pull/31231). One thing to note is that this was introduced by https://github.com/Microsoft/TypeScript/pull/7591 because of possible breakage by https://github.com/Microsoft/TypeScript/pull/7583. Not sure if this still holds though.
