### ISSUE TITLE
Issue narrowing tagged unions with temporary const

### ISSUE THREAD

**Issue by kyleshay** [Microsoft/TypeScript#31037]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** Narrowing, "Tagged Unions"

**Code**

```ts
interface Square {
    kind: 'square';
    size: number;
}
interface Circle {
    kind: 'circle';
    radius: number;
}
type Shape = Square | Circle;

// works as expected (s.kind) does the correct narrowing
function areaWorking(s: Shape) {
    switch (s.kind) {
        case 'square': return s.size * s.size;
        case 'circle': return Math.PI * s.radius ** 2;
    }
}

// When saving s.kind to a const variable, narrowing does not work
function area(s: Shape) {
    const {kind} = s; // same as const kind = s.kind;
    switch (kind) {
        case 'square': return s.size * s.size; // Property 'size' does not exist on type [Shape|Circle].
        case 'circle': return Math.PI * s.radius ** 2; // Property 'radius' does not exist on type [Shape|Square].
    }
}
```

**Expected behavior:**
I would expect to be able to pull the `kind` property from the `Shape` object into a const and the narrowing to work as expected.

**Actual behavior:**
Narrowing does not work, I need have the switch() go off of the variable passed in.

**Playground Link:** [TS Playground](https://typescript-play.js.org/#code/JYOwLgpgTgZghgYwgAgMoEcCucooN4BQyxyA1qACYBcyA5AM5Y4S0DcRJ9wAXhDSJgC2AI2jsAvgVCRYiFAGFgUBABt8HYuRDU6CJapbsSyKHArBM9fkNFQJBMAE8ADilQALOK+QBeNE1xkAB9kRWU1dgIYTBAEMGAAexBkZjgACis0T1cASmRCYwQk+jB8rQpxX2R6VmQAejrquEEUOHpkIpASskoq+gA6cqNOAHdgMAR3ZDTyvILjEgQ2lAYAlhpcMEwoZIGuXmQAKmr+-YhahuQABSgE1ygnOjPaZAoEiHaQBNKIAA9gbpJZBObwAbQ8XggQTCBgAuv0NAslvQVnpwusTBAtjtkABZOBgdz9K4ASSOJ1M5ksR2OACYLo0bndoI9aJSLPQXm8Psgvj9-oDkiCUODslCMNhcPDEZJJFEYnFEslUgB1BJQLQAcwyNAhuXyiPoYwmUwyg0oc0RhWWTzWtA2WO2u1OPBQxz2ruGCw6NtoaIM9sx2OS+MJxLJ7v67OphzpXuQsqAA)

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/18758

**Comment by jack-williams** [comment]
Narrowing isn’t tracked across variables; the issue tracking this is here: #12184. You’ll find related/duplicate issues linked to that one.

**Comment by kyleshay** [comment]
Thanks!
