### ISSUE TITLE
Poor error message/span trying to assign array to string

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#31038]
**TypeScript Version:**  3.4.0

**Search Terms:** array assign string span indexer

**Code**

The error span and message here imply that the array element is to blame, but really it's the entire expression

```ts
const s: string = [0];
                   ~ Cannot assign 'number' to 'string'
```

**Expected behavior:** Cannot assign `number[]` to `string`

**Actual behavior:** As indicated 

**Playground Link:** http://www.typescriptlang.org/play/#src=const%20s%3A%20string%20%3D%20%5B0%5D%3B%0D%0A%0D%0A

**Comment by IllusionMH** [comment]
Maybe useful for anyone who will work on issue (it wasn't obvious for me)

```ts
const s: string = [0]; // Error: Type 'number' is not assignable to type 'string'.

const n: number = [0]; // Error: Type 'number[]' is not assignable to type 'number'.
const s2: string = ['0']; // Error: Type 'string[]' is not assignable to type 'string'.

type test = string[0]; //string
```
Looks like `sting` type has its element with `0` index as `string` and error is roughly `Type '(number[])[0]' is not assignable to type 'string[0]'.` during elementwise type comparison.

**Comment by IllusionMH** [comment]
Also looks like same problem can be reproduced for objects with numeric keys
```ts
const so1: string = { 0: 1 };
                      ~ Type 'number' is not assignable to type 'string'.
// Expected results
const so2: string = { "0": 1 };
      ~~~ Type '{ "0": number; }' is not assignable to type 'string'.

const so3: string = { 0: "1" };
      ~~~ Type '{ 0: string; }' is not assignable to type 'string'.

const no1: number = { 0: 1 };
      ~~~ Type '{ 0: number; }' is not assignable to type 'number'.
```

**Comment by IllusionMH** [comment]
Compiled all test cases and possible fix in commit https://github.com/IllusionMH/TypeScript/commit/26c5f4a53effebc3e54684906ccfac30627c1941

Only 3 existing tests were affected by additional check. I think that 2 tests regarding `for..of` has correct error now, that will match erros for `number` type. However not sure about new error for  https://github.com/IllusionMH/TypeScript/commit/26c5f4a53effebc3e54684906ccfac30627c1941#diff-c732439e70f1eb29bb9ed22c9521bb4a

Is this appropriate solution?

**Comment by RyanCavanaugh** [comment]
@IllusionMH looks pretty good, I'd say put up a PR
