### ISSUE TITLE
Union type inference doesn't distinguish types with constant values if any of them has a non-constant value

### ISSUE THREAD

**Issue by jj101k** [Microsoft/TypeScript#31045]
**TypeScript Version:**  3.4.4-dev.201xxxxx, 3.5.0-dev.20190420

**Search Terms:** Type inference, type union, constant values, variable values, property does not exist on type

**Code**

```ts
type _0 = {foo: string}

type _01 = _0 & {foo: "1"}
type _02 = _0 & {foo: "2", bar: string}
type _03 = _0 & {foe: "3", bar: string}

type _04 = _01 | _02 | _03
function ex(ample: _04) {
    if(ample.foo == "2") {
        console.log(ample.bar)
    }
}
```

**Expected behavior:**
Compiles successfully

**Actual behavior:**
Compilation fails:
```
ast.ts:10:27 - error TS2339: Property 'bar' does not exist on type '_04'.
  Property 'bar' does not exist on type '_01'.

10         console.log(ample.bar)
                             ~~~


Found 1 error.

```

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20_0%20%3D%20%7Bfoo%3A%20string%7D%0D%0A%0D%0Atype%20_01%20%3D%20_0%20%26%20%7Bfoo%3A%20%221%22%7D%0D%0Atype%20_02%20%3D%20_0%20%26%20%7Bfoo%3A%20%222%22%2C%20bar%3A%20string%7D%0D%0Atype%20_03%20%3D%20_0%20%26%20%7Bfoe%3A%20%223%22%2C%20bar%3A%20string%7D%0D%0A%0D%0Atype%20_04%20%3D%20_01%20%7C%20_02%20%7C%20_03%0D%0Afunction%20ex(ample%3A%20_04)%20%7B%0D%0A%20%20%20%20if(ample.foo%20%3D%3D%20%222%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(ample.bar)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:** None found

If a union of types is distinguished by values on a property `foo` and one of the types has a variable value for that property, none of them are distinguished in an `if` statement and as a result the body of that statement hasn't inferred any specific type. Please note that the example here is phrased to highlight a likely trigger: a subtle mistake in code where there's a "parent" type defining a variable value for the property and a "child" type incorrectly overriding it.

At a lower level, for the `console.log(...)` line the compiler is inferring `_01 | _02 | _03` (or more strictly not inferring from `_04`) but should be inferring `_02 | _03`. In the case where this situation is due to a mistake in the code it may still produce an error message but at least it'd be an error message referring to the errant type.

If nothing else, it would be nice to have a compiler warning that the value that the expression is testing isn't constant for all members of the union.

**Comment by jack-williams** [comment]
foe —> foo
