### ISSUE TITLE
Skip parsing / binding in `--incremental` mode to match `--watch` performance.

### ISSUE THREAD

**Issue by Raynos** [Microsoft/TypeScript#31044]
I have a reasonably small typescript project ( 4000 lines of `.ts` and `.d.ts` ).

When I run the compiler with `incremental` and no `build/` folder it outputs

```
Files:           299
Lines:        315224
Nodes:           NaN
Identifiers:     NaN
Symbols:      209829
Types:          3516
Memory used: 340092K
I/O read:      0.07s
I/O write:     0.01s
Parse time:    2.00s
Bind time:     1.22s
Check time:    0.45s
Emit time:     0.42s
Total time:    4.09s

real	0m4.620s
user	0m6.393s
sys	0m1.003s
```

4.6s including 0.45s check, 0.45s emit time.

When I run the compiler again it outputs

```
Files:           299
Lines:        315224
Nodes:           NaN
Identifiers:     NaN
Symbols:      205565
Types:            71
Memory used: 320064K
I/O read:      0.06s
I/O write:     0.00s
Parse time:    2.17s
Bind time:     1.20s
Check time:    0.00s
Emit time:     0.01s
Total time:    3.37s

real	0m3.843s
user	0m5.576s
sys	0m0.748s
```

No check / emit time; clock time reduced from 4.5s => 3.8s.

When I run the compiler in `--watch` mode and it detects a file change it shows

```
Files:           299
Lines:        315226
Nodes:           NaN
Identifiers:     NaN
Symbols:      209091
Types:          2792
Memory used: 398749K
I/O read:      0.00s
I/O write:     0.00s
Parse time:    0.01s
Bind time:     0.01s
Check time:    0.21s
Emit time:     0.15s
Total time:    0.38s
```

It's rechecking & reemitting a single file which takes 0.4s and the parse/bind time is effectively 0 ( the time to parse one file instead of 300. )

```
raynos at raynos-Precision-5530  
~/nodesource/nsolid-ingress on incremental*
$ tsc -v
Version 3.5.0-dev.20190420
```

**Expected behavior:**

I expected the total time of `tsc` with `incremental: true` to be the same as the total time of `tsc --watch` when a single file is changed

**Actual behavior:**

The total time of `tsc` with `incremental: true` is longer because it still parses & binds all the files even though they have not changed.

```
raynos at raynos-Precision-5530  
~/nodesource/nsolid-ingress on incremental*
$ cat tsconfig.json 
{
  "compilerOptions": {
    "rootDir": ".",
    "incremental": true,
    "outDir": "build",
    "target": "ES2017",
    "types": ["node"],
    "lib": ["es2017"],
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowJs": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noStrictGenericChecks": false,
    "checkJs": true,
    "strict": true,
    "baseUrl": "./",
    "paths": {
      "@ns-private/nsolid-integration": [
        "./types/ns-private__nsolid-integration"
      ],
      "*" : ["./types/*"]
    },
    "strictNullChecks": true,
    "strictFunctionTypes": true
  },
  "include": [
    "types/**/*.d.ts",
    "src/**/*",
    "test/**/*"
  ]
}
```

**Comment by RyanCavanaugh** [comment]
TS can't not parse/bind files; a typecheck of a single file just isn't really a thing

**Comment by Raynos** [comment]
When you mention “checking a single file is not a thing”

Is this due to the implementation architecture or because you have to resolve all require and import statements in the single file ?

I presume watch is snappy due to in memory caching between file changes.

**Comment by RyanCavanaugh** [comment]
TypeScript has to know what's in the global scope to do proper analysis, and the global scope is only known by parsing and binding every file.

Parse+bind results can be re-used between checker instances, so watch mode can save the work there on files which have already been loaded for a prior compilation

**Comment by Raynos** [comment]
Thanks for the explanation.
