### ISSUE TITLE
Multiple return variables

### ISSUE THREAD

**Issue by DeepRobin** [Microsoft/TypeScript#31047]
## Search Terms

+ Multiple Return Variables
+ Multi Return vars

## Suggestion

Add multiple return variables and Promises with more T's like in go.

## Use Cases

It replaces for example callbacks -> in compiled JavaScript code it could be a callback

## Examples 

For ex. `name, err = await this.getName()`
And if one variable isn't use `name, * = await this.getName()`
And with types `(name: string) = await this getName()`

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment]
You can do it with [`array`](https://www.typescriptlang.org/docs/handbook/variable-declarations.html#array-destructuring) or [`object`](https://www.typescriptlang.org/docs/handbook/variable-declarations.html#object-destructuring) destructuring.

**Comment by DeepRobin** [comment]
@j-oliveras Yes, but a easier language is a better language.

**Comment by ClickerMonkey** [comment]
Can you provide a more complete example on the desired syntax and usage?

**Comment by DeepRobin** [comment]
@ClickerMonkey I think the same like in go lang in Go is it for ex. `obj, _ := getObject()` and my idea for TypeScript is `obj: any, * = await getObject()`

And a function in a class for example could be something like this: ```
async getObject(): Promise<Object, Error> {
...
}```

**Comment by MartinJohns** [comment]
@DeepRobin That would violate this point:

> [x] This could be implemented without emitting different JS based on the types of the expressions

And what if someone provided their own `Promise<T1, T2>` type?

**Comment by Mcfloy** [comment]
I see your point, yes Go is a very powerful language, but this kind of feature in TS/JS would be either a syntactic sugar or an "anti-pattern" as the language was designed to work with "objects" (not in a OOP way though)

**Comment by nmain** [comment]
From [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> Align with current and future ECMAScript proposals.

What if Javascript adds its own multiple return values in the future?

> Avoid adding expression-level syntax.

That's what this would be.

**Comment by MartinJohns** [comment]
> What if Javascript adds its own multiple return values in the future?

If ECMAScript is adding a feature and it reaches an advanced stage then a feature will be supported by TypeScript as well. I think currently the TypeScript team considers stage 3 (candidate) a necessary maturity. And I can't find **any** ECMAScript proposal for this. It seems everyone considers array and object destructuring enough.

**Comment by nmain** [comment]
Sorry, I didn't state what I was thinking.  My internal thought was more "What if Javascript adds its own multiple return values in the future, but Typescript has already added them from this request, and the two proposals don't align?"

**Comment by RyanCavanaugh** [comment]
Sorry, we should make this more clear: the checkboxes are requirements
