### ISSUE TITLE
The Incremental API aka "The Greedy File Watcher"

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/TypeScript#31048]
Heya!

Maintainer of the [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) here.  Under the covers, the plugin uses the TypeScript incremental API.  Various issues have been raised when using this with the level of CPU usage on idle; i.e. it's high!

- https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/236
- https://github.com/facebook/create-react-app/issues/6792

The marvellous @NeKJ did some digging and discovered that this could be remedied by setting an environment variable: `TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling`.

This changes the behaviour of TypeScripts approach to file watching in a highly desirable fashion.  You can see details of @NeKJ's investigation here:

https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/256

As you'll see, this is a PR for `fork-ts-checker-webpack-plugin` that changes the `TSC_WATCHFILE` environment variable.  If we merge it the users of `fork-ts-checker-webpack-plugin` should gain a better experience on the resources front.  

However, it feels like this is potentially the wrong place to make this change.  So before we merge and ship this I wanted to throw it back to you.  If this affects users of `fork-ts-checker-webpack-plugin` then I'd hazard a guess other people who use the API are being burned too.  Changing the default in `fork-ts-checker-webpack-plugin` won't help them.

Should the default file watching approach used by TypeScript be switched to `TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling` or similar?  So all users of this API have a better experience?

**Comment by DanielRosenwasser** [comment]
@sheetalkamat, thoughts? We did chat with VS Code a bit about this. Did they see improvements?

**Comment by johnnyreilly** [comment]
Hey @DanielRosenwasser / @sheetalkamat,

I was just wondering if there's been any discussion around this? I can certainly testify to lots of people who use create-react-app / fork-ts-checker-webpack-plugin logging issues related to this. 

It would be great to know if this is something you're looking to address?

In the meantime (time permitting) I may blog about this to spread the word on the workaround that people can already use. 

Thanks for all your excellent work! ♥️🤗

**Comment by DanielRosenwasser** [comment]
I remember chatting with Sheetal about this in person, but it's been a couple of weeks. My understanding is that this really is something that can only be determined by the end-user because different setups can affect this (e.g. operating system, file system, remote file system, etc.)

Is that accurate @sheetalkamat? @RyanCavanaugh?

**Comment by johnnyreilly** [comment]
> My understanding is that this really is something that can only be determined by the end-user because different setups can affect this (e.g. operating system, file system, remote file system, etc.)

Would it be possible for you to share the reasoning behind why the current default is the one used?

I ask as, to quote @nekj:

> TS uses internally the `fs.watch` and `fs.watchFile` API functions of nodejs for their watch mode. The latter function [is even not recommended by nodejs documentation](https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener) for performance reasons, and urges to use `fs.watch` instead.

**NodeJS doc:**
> Using fs.watch() is more efficient than fs.watchFile and fs.unwatchFile. fs.watch should be used instead of fs.watchFile and fs.unwatchFile when possible.

He suggests that the present default is a choice that node themselves advocate against using.

Also, there seems to a good number of people who are  finding the present default problematic.

It would great to understand the rationale for the current choice 😀

**Comment by DanielRosenwasser** [comment]
So my only qualification here is that I wrote the initial implementation of `--watch` so I don't know as much as Sheetal (and probably you) on this. That said, we had the same choice 4 years back as well - `watch` or `watchFile`.

The problem that came up is that last part:

> Using `fs.watch()` is more efficient than `fs.watchFile` and `fs.unwatchFile`. `fs.watch` should be used instead of `fs.watchFile` and `fs.unwatchFile` **when possible**.

To be more specific, you'll find this under the docs for `watch`:

> The `fs.watch` API is not 100% consistent across platforms, and is unavailable in some situations.

So back then we just always went with `watchFile`. Not sure what, if anything, has changed since then, and I'm not familiar with what we do by default.

**Comment by johnnyreilly** [comment]
I'm no expert either to be honest. Node moves pretty fast and so I wouldn't be surprised if things have changed but I don't actually know that.

Obviously it's a real subset of people that have come back with positive feedback. It would be awesome if someone with more node knowledge in the watch space could share more information so it would be clear if making a change is unwise.

I wanted to make a bit of noise about this as I'm certainly hearing it in the various projects I'm involved with. 😄

**Comment by mk0x9** [comment]
> ... means?

Few corner cases, like when you have docker container with webpack running and the source files are mounted in a volume. Or you have source files mounted via network share (NFS/SMB/WEBDAV).

**Comment by johnnyreilly** [comment]
Thanks @mk0x9 - that's helpful!

If these are as niche as it sounds I feel it's worth considering changing the default. People will always be able to change it if there's problems; and by the sounds of it that may be a problem that never arises anyway....

**Comment by sheetalkamat** [comment]
@johnnyreilly We use `watchFile` for the important files like files in your program and defer to `watch` to watch directories. This makes us more accurate in almost all cases and hence the decision. 
`watch` has many consistency issues apart from accuracy issues. Eg on Linux there is limit on number of things you want watch using this. Given that this differs so much with environment we cant change the default as that would make us loose accuracy. 
Because usage of `watch` needs much deeper understanding with compromises you are making on accuracy, we suggest that users make informed decision to use it instead. Making it default is asking everyone to know those details.

**Comment by johnnyreilly** [comment]
Thanks for the detailed explanation @sheetalkamat. So is it the plan that this won't be changed? 

I'm assuming the answer to that question is "yes" - but I want to be sure.

Users of both fork-ts-checker-webpack-plugin and create-react-app app have expressed interest in this issue. 

@nekj has raised a PR which would change the default behaviour using the environment variable.

https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/256

I haven't merged the PR as I thought it would make more sense for this change to be made in TypeScript itself. It sounds like that's not going to happen and for good reasons.

From what you've said, it sounds like you'd recommend not merging that PR. Is that fair?

It sounds like if we did we'd potentially solve one problem and create another. So I'm thinking about just documenting this clearly in order that people will know the configuration is possible. But here be dragons 🐉 and all that 😁

**Comment by sheetalkamat** [comment]
@johnnyreilly We document this in https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Configuring%20Watch.md#background 
In general that page is for more advanced users, so to answer your question we wont be changing default behavior.

**Comment by OneCyrus** [comment]
if the default doesn't get changed, any chance we get this as a tsconfig option instead of just an env variable?

**Comment by johnnyreilly** [comment]
I really like @OneCyrus suggestion - the environment variable approach works but the developer experience isn't great; friction is high. I think making this part of `tsconfig.json` is a great idea!

Also, it being part of the `tsconfig.json` means this feature will be much more discoverable. At the moment the file watching approach is not well known

**Comment by OliverJAsh** [comment]
I hope I'm not adding noise to this issue, but I've discovered something odd which seems to relate to the choice of `fs.watch`/`fs.watchFile`: when you `git commit` a change to a watched file, `tsc`'s watch will be triggered and `tsc` will recompile. That's odd because `git commit` doesn't actually change the file.

This is concerning because I'm now wondering how many wasted recompiles are happening during advanced git operations, like rebasing.

I was curious whether this was a `tsc` thing or something deeper. It turns out this is the behaviour of `fs.watch` (which is what `tsc --watch` uses, IIUC):

``` js
const fs = require('fs');

fs.watch(__dirname + '/main.ts', () => {
    console.log('watch');
});
```

If you run that script and `git commit` a change to the watched file, you'll see `watch` logged.

OTOH, if you use `fs.watchFile`, you will not see this logged:

``` ts
fs.watchFile(__dirname + '/main.ts', () => {
    console.log('watchFile');
});
```

Is this a known bug? Is there a recommended workaround?

**Comment by mk0x9** [comment]
Sounds like an issue in the node; IIRC fs.watch* is a platform dependent. Would be interesting to test this issue on the different platforms and compare fs.Stats objects in the callback.

**Comment by deftomat** [comment]
I would rather think about introducing it in `tsconfig.json` again. Looks like this issue really depends on specific configuration, so using some flag which every member of team pull from repo is probably not a good experience either.

**Comment by jasonwilliams** [comment]
@sheetalkamat Is it possible to re-open this issue with an option to set the tsconfig.json?
Having all devs set an environment variable isn't the nicest experience, especially when other watch tools let you choose via config (like watchpack or webpack watch etc).

**Comment by makranelhoucine** [comment]
@johnnyreilly thank you so much **you saved my day**

I use create react app, this line helped me to fix CPU 100% problm 
"start": "cross-env TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling react-scripts start",

**Comment by LucasMatuszewski** [comment]
@DanielRosenwasser / @sheetalkamat - please, would you consider @OneCyrus suggestion? Or/and could you add some information about this issue to documentation and help to reach more developers?

Finding that my CPU load is connected with TS and solving it took many hours of my life + my company IT Support time. Many people have the same problem. It still occurs with TypeScript 3.7.2

**Comment by sceutre** [comment]
Some people on my team were complaining about their batteries getting drained during a work day, and I took a look at the way we were using typescript watching.  On my Windows 10 machine the typescript watcher watching a tree containing about 1500 ts/tsx files was using about 10% CPU while idle.

I saw in the docs linked from this issue
> TSC_WATCHDIRECTORY. Note that on platforms that support native recursive directory watching (e.g windows) the value of this environment variable is ignored.

However for me, setting `TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling` dropped the CPU usage to about 0% while idle.  I saw the same behavior with nodejs version 8.15.1 and then 14.8.0.

**Comment by nicoburns** [comment]
@DanielRosenwasser @sheetalkamat Would you consider switching to [Chokidar](https://github.com/paulmillr/chokidar)? It's a battle tested solution used very widely throughout the Node ecosystem. We're in the process of switching to TypeScript at work, and the watch processes are taking ~45% cpu each on my 2015 MacBook Pro. As far as I am aware Node's built-in file watching capabilities are generally considered broken and not suitable for production use.

**Comment by jasonwilliams** [comment]
> As far as I am aware Node's built-in file watching capabilities are generally considered broken and not suitable for production use.

@nicoburns I'm not sure this is true anymore. Webpack 5 have just moved from Chokidar to Node's native fs system
> The watcher used by webpack was refactored. It was previously using chokidar and the native dependency fsevents (only on OSX). Now it's only based on native Node.js fs
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#new-watching

I don't think they would have made that change if it was broken.
