### ISSUE TITLE
Union type not act as mutual exclusion

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#31055]
**TypeScript Version:**  3.4.3

**Search Terms:**
union mutual exclusion

**Code**

```ts
type A = { A: string };
type B = { B: string };
let ab: A | B = {
    A: 'xxxxxxxxx',
    B: 123
}
```

**Expected behavior:**
Compiled error.
`ab` should be a mutual exclusion between `A` and `B`.

1. there should be only 1 field: `A` or `B`, shouldn't have 2 fields at the same time.
2. type of field `B` is wrong

**Actual behavior:**
Compiled succ.

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment]
I'd expect a EPC error (excess property checks) as well.   But besides that your object literal fulfills the contract of type `A` and of type `B`, so the assignment is valid.

**Playground link:** [https://typescript-play.js.org/#code/...](https://typescript-play.js.org/#code/C4TwDgpgBAglC8UDesBcUDOwBOBLAdgOZQC+A3AFCiRQBCCyd6WeRplANhMFAIYBG6OAB86DJBShS0UAOQAPRUqWyANJOm10ARgBMAZgokKQA)

**Related Issues:** #12936 and https://github.com/Microsoft/TypeScript/issues/12936#issuecomment-284590083 and #14094.

**Comment by jack-williams** [comment]
The issue tracking this particular problem in #20863 --- there is no discriminant property for the union type.

**Comment by RyanCavanaugh** [comment]
Union types are not intended to be automatically mutually exclusive

**Comment by k8w** [comment]
@RyanCavanaugh `ab.B === 123` is also working as intended?
Neither `type A` nor `type B` define `property B` could be a `number`

**Comment by RyanCavanaugh** [comment]
For an assignment `S` to `T | U`, the assignment is valid if `S` is a valid assignment to either type. `{ A: string, B: number }` is a valid ` { A: string }`, therefore the assignment is valid.

**Comment by k8w** [comment]
@RyanCavanaugh 
`{ B: number }` never defined in `A` and `B`.

So can I understand this as:
- If: part of `S` is valid to `A` or `B`
- Then: `S` is valid to `A|B`, 

But why `{A: 'XXXXX', C: 12345}` is not valid?

**Comment by RyanCavanaugh** [comment]
The things that excess property checking warns about aren't things related to subtyping or assignability.

**Comment by AlCalzone** [comment]
@Ryan Cavanaugh is it intended for VSCode intellisense to provide auto completion for B if A is already declared in an object literal?
I would guess not, but I stumbled across this today. Given my type was a bit more complicated than the one in this issue, it could be an entirely different issue though.

**Comment by EduardoRFS** [comment]
@RyanCavanaugh it doesn't make any sense, *code above* because it doesn't fulfill A, neither does it fulfill B, it only fulfill A & B, union isn't exclusively but it should fulfill at least one of them, in this case it doesn't full anyone of them.

```typescript
type A = { a: string };
type B = { b: string };
type T = A | B;
const t: T = {
    a: 'xxxxxxxxx',
    b: 123
};
```
