### ISSUE TITLE
Proposal: Declaring an enum restricted by a number,string or boolean set

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#3105]
Withdrawn

**Comment by danquirk** [comment]
I'm not sure this adds enough value for the complexity it introduces. Are there any other languages that support this kind of feature? It just adds bounds checking to numeric enums but doesn't scale to other enum spaces. We've had requests for string based enums for example which couldn't use this, we use bit flag enums ourselves a lot, and it's not unreasonable to imagine 'illegal' values within a contiguous bound which this wouldn't protect against.

**Comment by jbondc** [comment]
@danquirk It's not too complex, it doesn't only bounds checking to numeric enums. Started a patch here:
https://github.com/Microsoft/TypeScript/commit/4dc4814769a4e9f893c875bde7ed925a84b021a2

The idea is that constant enums is just a finite set of numeric values. You can constrain that set to a set of bounded integers or floats or whatever. It's a form of semantic subtyping from what I read. This same form of subtyping, you can apply to string enums:
```
type someStrings = "a" || "b" || "c";
const enum ofStrings {
   "a",
   "b",
   "c"
}
enum bounded<someStrings> {
   "a",
   "b",
}
var a : someStrings;
var b : ofStrings;
var c: someStrings;
a = b; // ok (same finite set)
b = a; // ok (same finite set)
a = c; // only ok because bounded
c = a; // error 
```

**Comment by jbondc** [comment]
On second thought, it will be more elegant to use a 'stringIndexType':
```
const enum ofNumbers {
   [x: string]: number,
   "a", // 1
   "b", // 2
   "c"  // 3
}
const enum ofStrings {
   [x: string]: string,
   "a", // "a"
   "b", // "b"
   "c" // "b"
}
const enum ofBoolean {
   [x: string]: boolean,
   True = true,
   False = false,
   YES = true,
   NO = false,
}
```

**Comment by jbondc** [comment]
@danquirk About your mention of other languages, made a weird discovery Pascal has 'set types':
http://en.wikipedia.org/wiki/Pascal_(programming_language)#Set_types

Updated the proposal with links. This should be super familiar to @ahejlsberg :open_mouth:

**Comment by Gaelan** [comment]
@danquirk `"a" | "b" | "c"` syntax would be insanely helpful for writing `.d.ts` files (lots of JS libraries use magic strings).

**Comment by Gaelan** [comment]
@jbondc Why the withdrawal? This was a good idea.

**Comment by jbondc** [comment]
@Gaelan I'm sure the TS team will come up with something. I've left the link to ```set types```, maybe they will call it ```collection types``` or something. When philosophies diverge too much, it's best to part ways.
