### ISSUE TITLE
issues about idea + typescript + vue cli + auto create declaration

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#31057]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

- demo project https://github.com/bluelovers/my-vue-project-base
- tsconfig https://github.com/bluelovers/ws-node-bluelovers/tree/master/packages/tsconfig
- TypeScript: typescript@next

> this issues also post in https://youtrack.jetbrains.com/issue/WEB-38508

![image](https://user-images.githubusercontent.com/167966/56496556-81134180-652c-11e9-8af5-f2305ec3b693.png)

**Expected behavior:**

> no error

**Actual behavior:**

![image](https://user-images.githubusercontent.com/167966/56496473-28dc3f80-652c-11e9-8e70-56d47138c655.png)

```
Error:(2, 17) TS2306: File 'my-project-base/src/App.vue.d.ts' is not a module.
```

![image](https://user-images.githubusercontent.com/167966/56496490-37c2f200-652c-11e9-9b51-2bd65bf7e8ab.png)

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Why is this a TypeScript bug?

**Comment by bluelovers** [comment]
because it throw error
