### ISSUE TITLE
[Feature request] Improve function overloading, make the compiler smarter. 

### ISSUE THREAD

**Issue by tulayang** [Microsoft/TypeScript#31069]
## Suggestion

Support intelligent function overloading, write functions does not need to worry about naming conflict. 

_I really hate object-oriented, and hate to bind data and functions together --- there are always some functions that operate on multiple objects and these functions should not belong to any object, they just work and don't care about saving data._  

## Examples

```ts
interface A {
}

interface B {
}

function f(a: A) {
}

function f(b: B) {
}
```

In Nim-lang programming language, the compiler generates a suffix hash for each overloaded function  to distinguish function names. When compiling to js, ​​it could be like this:

```js
function f_123abc(a) {
}

function f_456efg(b) {
}
```

I know that the compiler keeps function names unchanged after compiling into JS is to maintain compatibility with other JS libraries. I think TS can provide some compiler-level decorators,, such as ``@Compile()``, to allow users to specify the name of the compiled function:

```
@Compile('f1')
function f(a: A) {
}

@Compile('f2')
function f(b: B) {
}
```

When compiled into JS：

```js
function f1(a) {
}

function f2(b) {
}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
But why? Function overloading is fundamentally different in TypeScript from Nim. You don't have multiple functions based on different types, you have a single function that can accept different types. Your proposal would additionally require for all call-sites to be known during compilation, which is not possible for ambient or exported functions.

**Comment by RyanCavanaugh** [comment]
Previously suggested at #3442 and others. The *This could be implemented without emitting different JS based on the types of the expressions* goal is non-negotiable.
