### ISSUE TITLE
Compiling to ES5 with module type system breaks declare.

### ISSUE THREAD

**Issue by Zoltu** [Microsoft/TypeScript#3106]
ts
```
declare class Promise { }
export var foo = Promise;
```
js
```
System.register([], function(exports_1) {
	var Promise, foo;
	return {
		setters:[],
		execute: function() {
			exports_1("foo", foo = Promise);
		}
	}	
});
```
The important bit is the `var Promise`.  This hides the global `Promise` which makes code that tries to use it fail.
![image](https://cloud.githubusercontent.com/assets/886059/7557416/04d79678-f746-11e4-8aef-40808c59ef30.png)
![image](https://cloud.githubusercontent.com/assets/886059/7557419/0ee81660-f746-11e4-8b73-9800f340c369.png)

**Comment by vladima** [comment]
Ugh, yes, we should not hoist ambient classes\functions

**Comment by mhegazy** [comment]
note: this needs to be ported to release-1.5
