### ISSUE TITLE
Local JavaScript objects are not recognized

### ISSUE THREAD

**Issue by thoughtsunificator** [Microsoft/TypeScript#31061]
- VSCode Version:1.33.1
- OS Version:

Steps to Reproduce:

1. Create a javascript file "selection.js" with the following content:

```
(function() {
  SelectionUtils.insertBBcode = (tagOpen, tagClose, textarea) => {
	
  }
  SelectionUtils.format = (name, parameters) => {
	
  }
}).call(SelectionUtils = {})
```

2. Create a javascript file "another.js" in the same folder

3. Open the folder in VScode

4. Open "another.js" and type in SelectionUtils

5. Our SelectionUtils object is not recognized

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This example code is very dynamic and supporting proper intellisense is likely out of scope. Modern constructs like `class` are generally much better supported for our IntelliSense

**Comment by RyanCavanaugh** [comment]
This is much too complex for our current logic, and doesn't seem like a common enough pattern

**Comment by thoughtsunificator** [comment]
I don't see why you had to move the issue this has nothing to do with typescript this is JavaScript that I am writing. And all of this to tell me that the code makes no sense.. Come on.. It's not like I am telling you to force yourself to work on it but at least aknowledge the issue. Why am I even going out of my way to write issues on VS code... I should know better. Good thing I won't be posting anything else.

**Comment by mjbvz** [comment]
The TypeScript project powers VS Code's javascript intellisense. 

We reviewed at your issue and determined that fixing it is worth the significant cost of fixing it

**Comment by thoughtsunificator** [comment]
This is simply creating an object and binding the scope to it how is this complex compared to your so-called TypeScript?
