### ISSUE TITLE
Always need to tag the function which have optional parameters return type as any

### ISSUE THREAD

**Issue by ArrayZoneYour** [Microsoft/TypeScript#31068]
**TypeScript Version:**  3.4.4

> "strictNullChecks": true

**Search Terms:** function optional parameters

**Code**

```ts
type IF = {
  (x: number): string
  (x: number, y: number): number
}
const f: IF = (x: number, y?: number) => {
  if (y) {
    return x + y
  }
  else {
    return 'no y'
  }
}
```

**Expected behavior:**

No error

**Actual behavior:**

![image](https://user-images.githubusercontent.com/21001457/56553549-70f97180-65c1-11e9-8375-e361e6269106.png)

I need to tag return type as any to fix it. Is it expected ?

```typescript
type IF = {
  (x: number): string
  (x: number, y: number): number
}
const f: IF = (x: number, y?: number): any => {
  if (y) {
    return x + y
  } else {
    return 'no y'
  }
}
```

**Comment by MartinJohns** [comment]
You should declare a function with the same overloads as described in your `IF` type. Then it will work correctly.

**Comment by ArrayZoneYour** [comment]
@MartinJohns Official Docs always use any to make it work ;)

https://www.typescriptlang.org/docs/handbook/functions.html

```typescript
function pickCard(x: {suit: string; card: number; }[]): number;
function pickCard(x: number): {suit: string; card: number; };
function pickCard(x): any {
    // Check to see if we're working with an object/array
    // if so, they gave us the deck and we'll pick the card
    if (typeof x == "object") {
        let pickedCard = Math.floor(Math.random() * x.length);
        return pickedCard;
    }
    // Otherwise just let them pick the card
    else if (typeof x == "number") {
        let pickedSuit = Math.floor(x / 13);
        return { suit: suits[pickedSuit], card: x % 13 };
    }
}
```
But I will lose type safety in my pickCard function scope.
It made me annoyed. 😭

**Comment by MartinJohns** [comment]
Official docs are not always the best resource. When having proper functions with the overloads you can use a union as the return type instead of `any`:

    type IF = {
    (x: number): string
    (x: number, y: number): number
    }

    function myIf(x: number): string;
    function myIf(x: number, y: number): number;
    function myIf(x: number, y?: number): string | number {
    if (y) {
        return x + y
    }
    else {
        return 'no y'
    }
    }

    const f: IF = myIf;

But note that overloads are always posing a danger because the compiler will not verify if what you do in your function makes sense.

For example:

    function numberOrString(kind: 'number'): number;
    function numberOrString(kind: 'string'): string;
    function numberOrString(kind: 'number' | 'string'): number | string {
        return 'always a string';
    }

You are responsible to make sure the implementation matches the overloads.
