### ISSUE TITLE
Remove value inspection code

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#31074]
It's not reachable anymore and is generating some test problems

**Comment by weswigham** [comment]
By "not reachable anymore" do we mean "never reachable", since we never actually finished the quickfix? Should we be looking into completing it?

**Comment by weswigham** [comment]
Wait, no, the `fixCannotFindModule.ts` ostensibly was able to invoke it?

**Comment by RyanCavanaugh** [comment]
Due to some bugs, the fix was apparently never offered in practice
