### ISSUE TITLE
Wrong type inferred from extended class

### ISSUE THREAD

**Issue by Runjuu** [Microsoft/TypeScript#31073]
**TypeScript Version:**  3.4.4

**Search Terms:**
Conditional Types

**Code**

```ts
abstract class A<State> {
  abstract defaultState: State
}

interface BState {
  unionType: number | null
}

class B extends A<BState> {
  defaultState = {
    unionType: null
  }
}

type GetStateType<T> = T extends A<infer S> ? S : never

type InferredStateType = GetStateType<B>

const state1: InferredStateType = { unionType: 1 } // Error: Type 'number' is not assignable to type 'null'.
const state2: InferredStateType = { unionType: null }
```

**Expected behavior:**
`InferredStateType` should be  `BState` I guess

**Actual behavior:**
`InferredStateType` is `{ unionType: null }`
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/12002941/56586724-cad65780-6612-11e9-8a8b-bc5e87b077d4.png">

**Playground Link:** [Link](https://www.typescriptlang.org/play/index.html#src=abstract%20class%20A%3CState%3E%20%7B%0D%0A%20%20abstract%20defaultState%3A%20State%0D%0A%7D%0D%0A%0D%0Ainterface%20BState%20%7B%0D%0A%20%20unionType%3A%20number%20%7C%20null%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%3CBState%3E%20%7B%0D%0A%20%20defaultState%20%3D%20%7B%0D%0A%20%20%20%20unionType%3A%20null%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20GetStateType%3CT%3E%20%3D%20T%20extends%20A%3Cinfer%20S%3E%20%3F%20S%20%3A%20never%0D%0A%0D%0Atype%20InferredStateType%20%3D%20GetStateType%3CB%3E%0D%0A%0D%0Aconst%20state1%3A%20InferredStateType%20%3D%20%7B%20unionType%3A%201%20%7D%0D%0Aconst%20state2%3A%20InferredStateType%20%3D%20%7B%20unionType%3A%20null%20%7D)

**Comment by RyanCavanaugh** [comment]
See #10570
