### ISSUE TITLE
Subsequent usage of square bracket notation does not recognize type check

### ISSUE THREAD

**Issue by VSDekar** [Microsoft/TypeScript#31084]
**TypeScript Version:**  
3.4.3

**Code**

```ts
export const search = <T, K extends keyof T>(term: string, objects: T[], keys: K[]): T[] => {
  return objects.filter(x =>
    keys.some(key => x.hasOwnProperty(key) && typeof x[key] === 'string' && x[key].toLowerCase().includes(term)),
  );
};
```

**Expected behavior:**
It does recognize the type check.

**Actual behavior:**
Gives me the following error: `error TS2339: Property 'toLowerCase' does not exist on type 'T[K]'.`

When i rip this apart and store the value in a variable it works just fine.
```ts
export const search = <T, K extends keyof T>(term: string, objects: T[], keys: K[]): T[] => {
  return objects.filter(x => {
    return keys.some(key => {
      if (x.hasOwnProperty(key) === false) {
        return false;
      }
      const val = x[key];
      if (typeof val === 'string' && val.toLowerCase().includes(term)) {
        return true;
      }
      return false;
    });
  });
};
```

**Playground Link:** 
[Playground](https://www.typescriptlang.org/play/#src=export%20const%20search%20%3D%20%3CT%2C%20K%20extends%20keyof%20T%3E(term%3A%20string%2C%20objects%3A%20T%5B%5D%2C%20keys%3A%20K%5B%5D)%3A%20T%5B%5D%20%3D%3E%20%7B%0D%0A%20%20return%20objects.filter(x%20%3D%3E%0D%0A%20%20%20%20keys.some(key%20%3D%3E%20x.hasOwnProperty(key)%20%26%26%20typeof%20x%5Bkey%5D%20%3D%3D%3D%20'string'%20%26%26%20x%5Bkey%5D.toLowerCase().includes(term))%2C%0D%0A%20%20)%3B%0D%0A%7D%3B)

**Related Issues:**
Maybe related issue:
https://github.com/Microsoft/TypeScript/issues/28081

**Comment by RyanCavanaugh** [comment]
Duplicate #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal

**Comment by VSDekar** [comment]
Ok sorry, i did not see this...
Will this be fixed somewhere in the near future? There are so many duplicates referenced...
