### ISSUE TITLE
proposal-promise-allSettled

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#31083]
## Search Terms
esnext, allSettled, Promise

## Suggestion

https://github.com/tc39/proposal-promise-allSettled is Stage 3 now

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by SimonSchick** [comment]
Giving this a bump since I intend to add this to the `node` type definitions.

**Comment by csvn** [comment]
Also, the description for this issue says Stage 3, but it was moved to Stage 4 roughly 2 months ago (https://github.com/tc39/proposals/blob/master/finished-proposals.md). It should probably be added to `es2020`, and not `esnext`.

**Comment by khaosdoctor** [comment]
This is already supported in Node 12.9.0, I think it should be added to TS natively. There's a @types definition for this but I didn't manage to get it to work though...

**Comment by Pomar81** [comment]
Why I can try these types in the playground

http://www.typescriptlang.org/play/index.html?target=99&module=5&ts=3.9.0-dev.20200215&ssl=2&ssc=20&pln=2&pc=1#code/MYewdgzgLgBAhjAvDACgJxAWwJYQKYB0cANsQMp5RTF4AmAFANrpa6Fp4QjEBue9ARgCUAXSEBYAFBSgA

**Comment by orta** [comment]
The playground has a constant single dts file for all the lib files. This hasn't been updated per version, and I've not got around to _an expensive to download but more accurate_ version yet - you can follow https://github.com/microsoft/TypeScript-Website/issues/82 for updates there
