### ISSUE TITLE
Use keyof in Object keys

### ISSUE THREAD

**Issue by aliazizi** [Microsoft/TypeScript#31087]
## Search Terms

keyof, object

## Suggestion

It's not better we use `key of` in Object.keys? So its very use keys to access data from original object.

## Examples

`keys<T>(o: T): (keyof T)[];`

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplicate and rejected multiple times: https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208, #30314, #13254. #30228, #28899, #28284, #26901, 30749.

[More info](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript)
