### ISSUE TITLE
Enter Release Notes/Releases for 3.4.4 / 3.4.5

### ISSUE THREAD

**Issue by rdunlop** [Microsoft/TypeScript#31088]
According to [npm](https://www.npmjs.com/package/typescript), version 3.4.4 was released on 4/18/2019, and 3.4.5 was released 4/23/2019.

I would like to upgrade my project, but I do not know what the contents of these releases are.

I checked [releases](https://github.com/Microsoft/TypeScript/releases), and the last release listed there is 3.4.3 on 4/9/2019.

There was also [not a "tag" for the release](https://github.com/Microsoft/TypeScript/tags)

**Expected behavior:**
- Each release should be tagged with the version before being published to npm.
- Each release should be listed on the Releases page before being published to npm.

**Actual behavior:**
- Some releases are NOT tagged, nor listed on the releases page, but are published in npm.

**Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/17487

**Comment by ashleyw** [comment]
Not sure on the specifics, but here's a diff between 3.4.3 and 3.4.5: https://diff.intrinsic.com/typescript/3.4.3/3.4.5
