### ISSUE TITLE
[docs] project configuration -> tsconfig.json link is duplicated

### ISSUE THREAD

**Issue by aamorozov** [microsoft/TypeScript#31092]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
site, duplicated link, docs, tsconfig.json duplicated link

**Page to replicate:**
https://www.typescriptlang.org/docs/home.html and then expand `Project Configuration` dropdown.

**Actual behavior:**

<img width="266" alt="Screen Shot 2019-04-24 at 12 28 47 PM" src="https://user-images.githubusercontent.com/10227658/56676706-e7af7100-668c-11e9-95e8-277b475a7848.png">

**Comment by garritfra** [comment]
Can't confirm. Did you mess around with the docs to somehow trigger this bug?
<img width="950" alt="Bildschirmfoto 2019-10-22 um 16 21 03" src="https://user-images.githubusercontent.com/32395585/67295914-0f6e7d00-f4e8-11e9-9a9d-1038547e2d34.png">

**Comment by aamorozov** [comment]
I did not at the time, but I cannot replicate it anymore either - closing the issue. @garritfra
