### ISSUE TITLE
Typescript's Doc webpage has layout issue on Chrome

### ISSUE THREAD

**Issue by cyphueus** [Microsoft/TypeScript#31108]
**device:** MacBook Pro 13
**browser:** Chrome 73.0.3683.103
### This is on Chrome:
![image](https://user-images.githubusercontent.com/23122353/56725360-51a84300-677f-11e9-8c16-5d3450af0061.png)
### This is on Safari: 
![image](https://user-images.githubusercontent.com/23122353/56725526-9633de80-677f-11e9-855e-a62a69c67300.png)

[Basic Types](https://www.typescriptlang.org/docs/handbook/basic-types.html)

**Comment by j-oliveras** [comment]
I see no errors on Windows 10 and the same Chrome version.

**Comment by RyanCavanaugh** [comment]
@andrewbranch also saw no problems in Chrome on Mac

If you can point us at some specific rule that's causing the problem, we can maybe investigate, but it doesn't seem like it's the website's fault

**Comment by andrewbranch** [comment]
@cyphueus can you give it a try with browser extensions disabled?
