### ISSUE TITLE
Strict equals false type guard doesn't work

### ISSUE THREAD

**Issue by hansott** [microsoft/TypeScript#31105]
**Code**

```ts
interface A {
  a: string;
}

interface B {
  b: string;
}

type MyType = A | B;

function isA(x: MyType): x is A {
  return "a" in x;
}

function someFn(x: MyType) {
  if (!isA(x)) {
    console.log(x.b);
    //            ^ <- works perfectly
  }

  if (isA(x) === false) {
    console.log(x.b);
    //            ^ <- here's the problem
  }
}
```

**Expected behavior:**

Being able to access `x.b` in this if statement:

```ts
if (isA(x) === false) {
  console.log(x.b);
}
```

**Actual behavior:**

Error: Property b does not exists on type `A`.

**Playground Link:**

[Playground](https://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0D%0A%20%20a%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20MyType%20%3D%20A%20%7C%20B%3B%0D%0A%0D%0Afunction%20isA(x%3A%20MyType)%3A%20x%20is%20A%20%7B%0D%0A%20%20return%20%22a%22%20in%20x%3B%0D%0A%7D%0D%0A%0D%0Afunction%20someFn(x%3A%20MyType)%20%7B%0D%0A%20%20if%20(!isA(x))%20%7B%0D%0A%20%20%20%20console.log(x.b)%3B%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%5E%20%3C-%20works%20perfectly%0D%0A%20%20%7D%0D%0A%0D%0A%20%20if%20(isA(x)%20%3D%3D%3D%20false)%20%7B%0D%0A%20%20%20%20console.log(x.b)%3B%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%5E%20%3C-%20here's%20the%20problem%0D%0A%20%20%7D%0D%0A%7D)

**Comment by jcalz** [comment]
Note that this is a duplicate of #9508 which was closed as "won't fix".  Not sure what changed between that and this, although the fact that this is languishing in the backlog might be functionally equivalent to "won't fix" 😅
