### ISSUE TITLE
Node 12: "tsc --watch" stops working

### ISSUE THREAD

**Issue by juergenzimmermann** [Microsoft/TypeScript#31111]
**TypeScript Version:** 
3.4.5 and 3.5.0-dev.20190425

**Search Terms:**
typescript watch node 12

**Code**

```ts
tsc --watch
```

**Expected behavior:**
No error

**Actual behavior:**
After upgrading from Node 11 to Node 12 `tsc` without any option (in addition to tsconfig.json) works as expected. However, `tsc --watch` produces this output:

```cmd
#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 00000093307CD6A0
```

**Playground Link:**
Unpack attached testcase.zip, and invoke `tsc` resp. `tsc --watch`

**Related Issues:**
no
[testcase.zip](https://github.com/Microsoft/TypeScript/files/3116686/testcase.zip)

**Comment by sheetalkamat** [comment]
Seem to be working correctly
```
c:\temp\testcase>node -v
v12.0.0

c:\temp\testcase>node node_modules\typescript\lib\tsc.js -v
Version 3.5.0-dev.20190425

c:\temp\testcase>node node_modules\typescript\lib\tsc.js -w
[3:17:03 PM] Starting compilation in watch mode...

[3:17:05 PM] Found 0 errors. Watching for file changes.

```

**Comment by hibas123** [comment]
I get the same Error on Windows and Linux while using NodeJS 12.

Tested Versions:
3.4.5 and 3.5.0-dev.20190425

Got the same error message:

```
#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffc98e77040fish: 'tsc --watch' terminated by signal SIGILL
```

While looking at the syslog (on Linux) I could detect the following message:

`kernel: [  723.962466] traps: node[10648] trap invalid opcode ip:18ad9b9 sp:7fffb11fa018 error:0 in node[400000+2214000]`

To me, it appears as if it is a bug inside Node that is somehow triggered by the typescript compiler.

**Comment by luozhihua** [comment]
Same as #27379 

`webpack --watch` also has the same issue.

**Comment by abenhamdine** [comment]
same here on Windows and typescript 3.4.5 with nodejs 12

**Comment by juergenzimmermann** [comment]
After upgrading to Node 12.1.0 the issue is gone.
