### ISSUE TITLE
Incremental build with changes to tsconfig's target does not regenerate js files

### ISSUE THREAD

**Issue by konpikwastaken** [Microsoft/TypeScript#31118]
**TypeScript Version:**  3.4.5, 3.5.0-dev.20190425

**Search Terms:** incremental, build, target, tsc, tsconfig

**Code**

**bar.ts**
```ts
const bar = class foo {
  private str: string;
}
export default bar;
```
**tsconfig.json**
```json
{
... // ommitted for brevity
  "target": "esnext"
...
}
```

**Expected behavior:**
Once you build, then change the tsconfig `target` field to, say, `commonjs`, TSC should regenerate all of the output JS files.

**Actual behavior:**
TSC runs, but does not regenerate the JS files

It would seem that some tsconfig values should be part of the `tsconfig.tsbuildinfo` hash/checksum, but are not. Not sure if this is meant to be by design, but could be misleading.

**Comment by indiejoseph** [comment]
Also having this problem here, whenever I removed the output directory and regenerate, I have to delete the tsconfig.tsbuildinfo, otherwise nothing happen.

**Comment by sheetalkamat** [comment]
@indiejoseph Please open another issue if it repros with typescript@next .I don't see why you should have that behavior since we do handle `outDir`
