### ISSUE TITLE
Please add Notification.requestPermission()

### ISSUE THREAD

**Issue by kk80805588** [Microsoft/TypeScript#3111]
https://developer.mozilla.org/zh-CN/docs/Web/API/notification/Using_Web_Notifications
![unf _n c9y b 1_n 3phz h](https://cloud.githubusercontent.com/assets/3072571/7559928/4c1e3906-f7f0-11e4-8e1b-97c619972410.png)

**Comment by RyanCavanaugh** [comment]
We try not to put non-standardized things in lib.d.ts.

You can always include a .d.ts file yourself that includes definitions for these APIs.

**Comment by heruan** [comment]
Isn't the Notification API actually a standard? https://notifications.spec.whatwg.org/

**Comment by kitsonk** [comment]
This was closed over 13 months ago, when `Notification` was from standard.

This can be addressed by [contributing to the TS-Lib-Generator](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes).

**Comment by heruan** [comment]
Thank you @kitsonk I had a look to the TS-Lib-Generator to contribute but I couldn't guess the correct approach to add the Notification type in the `addedTypes.json` file (as the contribution guidelines state), since the interface has static/readonly properties not covered by the build script.

**Comment by kitsonk** [comment]
I am a little bit surprised that it hasn't come over yet, though I haven't looked at master.  It is in Edge 14, so the IDLs for Edge should reflect that, which should generate it without overrides... I don't know enough, about the specifics, but do new APIs automagically appear when added to Edge's IDLs and what version of the IDLs are used when building (is it only released)?

**Comment by kitsonk** [comment]
Ah, I see, the browser IDLs are currently 4 months old... which means it is likely they are "Edge 13" ones. @zhengbli how often/when do you update them?

**Comment by zhengbli** [comment]
We used to take the Edge spec files along with official windows 10 releases, therefore the last update was the same as TH2. However, it makes more sense to do a more frequent update to avoid wasted efforts from the community, we are taking to the Edge team trying to make a monthly update happen. Also, `NotificationOptions` is indeed available in the latest Edge build. It should be covered next update, which should be soon.

**Comment by FranklinWhale** [comment]
@zhengbli Is there any update on this issue?

**Comment by FranklinWhale** [comment]
By the way, I have made an updated defintion for `Notification`:

```ts
type NotificationPermission = "default" | "denied"| "granted";

type NotificationDirection = "auto" | "ltr" | "rtl";

interface NotificationPermissionCallback {
	(permission: NotificationPermission): void;
}

interface NotificationOptions {
	dir?: NotificationDirection;
	lang?: string;
	body?: string;
	tag?: string;
	image?: string;
	icon?: string;
	badge?: string;
	sound?: string;
	vibrate?: number | number[],
	timestamp?: number,
	renotify?: boolean;
	silent?: boolean;
	requireInteraction?: boolean;
	data?: any;
	actions?: NotificationAction[]
}

interface NotificationAction {
	action: string;
	title: string;
	icon?: string;
}

declare class Notification extends EventTarget {
	constructor(title: string, options?: NotificationOptions);
	
	static readonly permission: NotificationPermission;
	static requestPermission(): Promise<NotificationPermission>;
	static requestPermission(deprecatedCallback: NotificationPermission): void;

	static readonly maxActions: number;

	onclick: EventListenerOrEventListenerObject;
	onerror: EventListenerOrEventListenerObject;

	readonly title: string;
	readonly dir: NotificationDirection;
	readonly lang: string;
	readonly body: string;
	readonly tag: string;
	readonly image: string;
	readonly icon: string;
	readonly badge: string;
	readonly sound: string;
	readonly vibrate: number[];
	readonly timestamp: number;
	readonly renotify: boolean;
	readonly silent: boolean;
	readonly requireInteraction: boolean;
	readonly data: any;
	readonly actions: NotificationAction[]
}
```

**Comment by marcovdb** [comment]
Great work! I improved it a bit: the 'close' method on the Notification class was missing, and the definition for the deprecated requestPermission method wasn't entirely correct.

```
type NotificationPermission = "default" | "denied" | "granted";

type NotificationDirection = "auto" | "ltr" | "rtl";

interface NotificationPermissionCallback {
	(permission: NotificationPermission): void;
}

interface NotificationOptions {
	dir?: NotificationDirection;
	lang?: string;
	body?: string;
	tag?: string;
	image?: string;
	icon?: string;
	badge?: string;
	sound?: string;
	vibrate?: number | number[],
	timestamp?: number,
	renotify?: boolean;
	silent?: boolean;
	requireInteraction?: boolean;
	data?: any;
	actions?: NotificationAction[]
}

interface NotificationAction {
	action: string;
	title: string;
	icon?: string;
}

declare class Notification extends EventTarget {
	constructor(title: string, options?: NotificationOptions);
	
	static readonly permission: NotificationPermission;
	static requestPermission(): Promise<NotificationPermission>;
	static requestPermission(deprecatedCallback: (permission: NotificationPermission) => void): void;

	static readonly maxActions: number;

	onclick: EventListenerOrEventListenerObject;
	onerror: EventListenerOrEventListenerObject;

	close(): void;

	readonly title: string;
	readonly dir: NotificationDirection;
	readonly lang: string;
	readonly body: string;
	readonly tag: string;
	readonly image: string;
	readonly icon: string;
	readonly badge: string;
	readonly sound: string;
	readonly vibrate: number[];
	readonly timestamp: number;
	readonly renotify: boolean;
	readonly silent: boolean;
	readonly requireInteraction: boolean;
	readonly data: any;
	readonly actions: NotificationAction[]
}
```

**Comment by tusharshuklaa** [comment]
@marcovdb I made a notification.d.ts out of your code but it shows me error in this section: <br />
`readonly title: string;
    readonly lang: string;
    readonly body: string;
    readonly tag: string;
    readonly icon: string;
    readonly timestamp: number;
    readonly silent: boolean;
    readonly requireInteraction: boolean;
    readonly data: any;`

<br />
I'm getting this error for all above properties.
All declarations of 'propertyName' must have identical identifiers
<br />
Can you please help me with this issue?

**Comment by mhegazy** [comment]
Should be added in the next release. See https://github.com/Microsoft/TSJS-lib-generator/blob/cd60588b72a9188e89346b3c440a76508b4c0e76/baselines/dom.generated.d.ts#L8360-L8381

**Comment by mwent-cray** [comment]
How do you watch for a action click?

**Comment by wonea** [comment]
@mwent-cray StackOverflow is the place for questions.

**Comment by Shavindra** [comment]
@marcovdb is Notification definitions still in TS 2.4? Because I can't seem to find it there :-|

https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts

**Comment by marcovdb** [comment]
Yes. It's in a different file.

https://github.com/Microsoft/TypeScript/blob/master/src/lib/webworker.generated.d.ts

**Comment by Shavindra** [comment]
@marcovdb is there a reason why the interface is different from code mentioned in your last post in thread?

**Comment by marcovdb** [comment]
Sorry, no idea. You'd have to ask the person that actually contributed the definitions. That would be @zhengbli.

**Comment by ialexryan** [comment]
@zhengbli why were all but 5 of the `NotificationOptions` omitted? 😞

**Comment by mhegazy** [comment]
@ialexryan please file a new issue and give us some context about the issue, and i would be happy to look into it.
