### ISSUE TITLE
Type check error by providing union to function that declared for every part of this union

### ISSUE THREAD

**Issue by bogem** [Microsoft/TypeScript#31130]
**TypeScript Version:**  3.3.4000, also reproducible on typescript@next

**Search Terms:**

union type, no match for signature

**Code**

```ts
type A = { a: 1 };
type B = () => { b: 2 };
type Union = A | B;

interface Func {
    (a: A): string;
    (b: B): number;
}

// f ist example of Func and should implement Func,
// but if you uncomment this line, you become an error. Is it expected? 
// const f: Func = (u: Union) => isA(u) ? "A" as string : 2 as number;  

const isA = (u: Union): u is A => "a" in u;

const g = (f: Func) => (u: Union) => f(u);
```

**Expected behavior:**

No error

**Actual behavior:**
```
const g = (f: Func) => (u: Union) => f(u);
                                       ^

Argument of type 'Union' is not assignable to parameter of type 'B'.
  Type 'A' is not assignable to type 'B'.
    Type 'A' provides no match for the signature '(): { b: 2; }'.
```

**Workaround:**
```ts
interface Func {
    (a: A): string;
    (u: Union): number;
}
```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=type%20A%20%3D%20%7B%20a%3A%201%20%7D%3B%0D%0Atype%20B%20%3D%20()%20%3D%3E%20%7B%20b%3A%202%20%7D%3B%0D%0Atype%20Union%20%3D%20A%20%7C%20B%3B%0D%0A%0D%0Aexport%20interface%20Func%20%7B%0D%0A%20%20%20%20(a%3A%20A)%3A%20string%3B%0D%0A%20%20%20%20(b%3A%20B)%3A%20number%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20f%20ist%20example%20of%20Func%20and%20should%20implement%20it%2C%0D%0A%2F%2F%20but%20if%20you%20uncomment%20this%20line%2C%20you%20become%20an%20error.%20Is%20it%20expected%3F%20%0D%0A%2F%2F%20const%20f%3A%20Func%20%3D%20(u%3A%20Union)%20%3D%3E%20isA(u)%20%3F%20%22A%22%20as%20string%20%3A%202%20as%20number%3B%20%20%0D%0A%0D%0Aconst%20isA%20%3D%20(u%3A%20Union)%3A%20u%20is%20A%20%3D%3E%20%22a%22%20in%20u%3B%0D%0A%0D%0Aconst%20g%20%3D%20(f%3A%20Func)%20%3D%3E%20(u%3A%20Union)%20%3D%3E%20f(u)%3B%0D%0A

**Comment by jcalz** [comment]
Duplicate of #14107

**Comment by bogem** [comment]
@jcalz thank you! I knew that this would be duplicate but couldn't find the issue 😬
