### ISSUE TITLE
Transitive dependency version not respected

### ISSUE THREAD

**Issue by irond13** [microsoft/TypeScript#31140]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
different transitive dependency versions

Our use case uses a sub-module to provide dependant modules with the latest versions of certain 3rd party dependencies, while allowing them to use older versions directly depended on throughout the rest of the code base. 

This works perfectly fine from a pure JS perspective and allows a nice upgrade mechanism. Unfortunately, we can't get this working from a TS perspective. Depending on configuration, either the top-level types are used throughout - which is incorrect with reference to the corresponding JS - or we get version conflict compile errors.

**Expected behavior:**

(Referenced repos created solely to demonstrate the issue)

This shouldn't compile: https://github.com/irond13/dep-test-consumer/blob/with-dep/src/with-dep.ts#L10 (referenced method `indexBy` doesn't exist in transitive version of lodash @ 4.x.x)
This should compile: https://github.com/irond13/dep-test-consumer/blob/should-compile/src/with-dep.ts#L10

**Actual behavior:**

This does compile: https://github.com/irond13/dep-test-consumer/blob/with-dep/src/with-dep.ts#L10
This doesn't compile: https://github.com/irond13/dep-test-consumer/blob/should-compile/src/with-dep.ts#L10 (referenced method `keyBy` does exist in transitive version of lodash, but doesn't exist in directly depended on version of loads @ 3.x.x)

**Comment by irond13** [comment]
Another variation of the above is where _both_ versions of the lodash types are parsed in the same context for some reason, which causes compile errors due to conflicts.

This branch demonstrates: https://github.com/irond13/dep-test-consumer/tree/compile-fail-conflict
It fails with the following compile errors:
```
node_modules/@types/lodash/index.d.ts(6,1): error TS6200: Definitions of the following identifiers conflict with those in another file: ListIterator, ObjectIterator, StringIterator, MemoVoidIterator, MemoIterator, MemoVoidArrayIterator, MemoVoidDictionaryIterator, List, LoDashImplicitArrayWrapper, LoDashImplicitObjectWrapper, LoDashImplicitNumberArrayWrapper, LoDashImplicitStringWrapper, LoDashExplicitArrayWrapper, LoDashExplicitObjectWrapper, LoDashExplicitNumberArrayWrapper, LoDashExplicitStringWrapper, DictionaryIterator, NumericDictionaryIterator
node_modules/@types/lodash/index.d.ts(41,26): error TS2314: Generic type 'LoDashImplicitWrapper<T, TValue>' requires 2 type argument(s).
node_modules/@types/lodash/index.d.ts(43,27): error TS2314: Generic type 'LoDashImplicitWrapper<T, TValue>' requires 2 type argument(s).
node_modules/@types/lodash/index.d.ts(47,23): error TS2314: Generic type 'LoDashImplicitWrapper<T, TValue>' requires 2 type argument(s).
...
```
[compile_fail.txt](https://github.com/Microsoft/TypeScript/files/3130874/compile_fail.txt)

**Comment by weswigham** [comment]
You need a version of `@types/lodash` that doesn't unconditionally dump its types into the global scope. :(

Since its types are global, they can conflict when multiple versions are installed - this is fine in a browser environment, since it'd indicate they you have multiple conflicting global lodash includes, but in the module context it's just unpleasant, since the two copies of lodash don't really interact.
