### ISSUE TITLE
Periodic build emit errors when concurrently compiling projects to a single bin folder

### ISSUE THREAD

**Issue by Bebo2345** [Microsoft/TypeScript#3114]
We are seeing this issue mentioned on [codeplex workitem 2281](https://typescript.codeplex.com/workitem/2281). I'm pulling it forward to GitHub since it is still an issue for us. We are using TypeScript 1.4.

We get the emit errors on *.js.map files.

Original Description from [codeplex workitem 2281](https://typescript.codeplex.com/workitem/2281):

> I have been using 9.1.1 without issue. Since upgrading to 1.0RC, I occasionally receive the following error: 

> Build: Emit Error: Write to file failed..

> The file that fails always has the .js extension, but the failure is never for the same file. 

> Most of the time, the error goes away when I build the solution again (using VS 2013 Professional on Windows 8.1). However, sometimes it fails two or more times. The max consecutive failures has been three. All failures were on different files. 

> There is one thing that is somewhat unique about my solution. I am using a common ts project that is shared with a couple of other projects in the solution. I am using links from the consuming projects for the .ts files. This may or may not have anything to do with the failures. 

> Has anyone else experienced this? 

> Thanks...

Comment from @RyanCavanaugh

> I was able to reproduce this with a common project ("Common") and two referring projects ("ClientA" and "ClientB") which refer to a large file in Common.
>
> When the build processes launch, each tsc instance from ClientA and ClientB runs concurrently and both try to re-compile the files in Common. Sometimes they finish compiling a file at the same time and try to write to the file at the same time, causing this error.
>
>Unfortunately we can't address this comprehensively for 1.0. There are a few things you can do in the meantime:
> 1. Use .d.ts references instead of .ts references so that the leaf node projects aren't recompiling things. This is probably the best solution.
> 2. Turn off concurrent build (set number of concurrent builds to 1: http://msdn.microsoft.com/en-us/library/y0xettzf(v=vs.90).aspx). This is easy, but will increase your build times.
> 3. Use -outdir settings on each project so that they write to different output folders, then use a post-build step to reconstruct the correct file layout.

**Comment by mhegazy** [comment]
The description from @RyanCavanaugh is still accurate. There are two build processes that are competing to lock the files. you need to serialize these builds to break the race condition. see the 3 options that @RyanCavanaugh mentioned erlier.

Another thing to note here, you are building (reading, parsing, typechecking, and emitting) the same set of files multiple times, this affects your general build time. i would say you need to break off the common files in a separate compilation to save on your overall build time.
