### ISSUE TITLE
Unsound generalization of function application

### ISSUE THREAD

**Issue by susisu** [microsoft/TypeScript#31152]
**TypeScript Version:**  3.4.5, 3.5.0-dev.20190427

**Search Terms:** type parameter generalization, value restriction 

**Code**
When a type parameter of a function is also generic in the type of its argument, the function application (`ref(id)` in the code) will be incorrectly generalized wrt that type parameter.

```ts
const ref = <T>(f: (x: T) => T) => {
  const r = { val: f };
  return () => r;
};
const id = <T>(x: T) => x;

// r: <T>() => { val: (x: T) => T }
const r = ref(id);
// unsafe instantiations of r
const r1 = r<number>();
const r2 = r<string>();
// update r1.val with a function specific to numbers
r1.val = (x: number) => x * 2;
// using r2.val will cause runtime failure
r2.val("foo");
```

**Expected behavior:**
`r` in the above code should not be generalized.
It should have type `() => { val: (x: unknown) => unknown }`, or `() => { val: (x: U) => U }` if `id` has type parameter `T extends U` for some type `U`.

**Actual behavior:**
`r` has a generalized type `<T>() => { val: (x: T) => T }`.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=const%20ref%20%3D%20%3CT%3E(f%3A%20(x%3A%20T)%20%3D%3E%20T)%20%3D%3E%20%7B%0D%0A%20%20const%20r%20%3D%20%7B%20val%3A%20f%20%7D%3B%0D%0A%20%20return%20()%20%3D%3E%20r%3B%0D%0A%7D%3B%0D%0Aconst%20id%20%3D%20%3CT%3E(x%3A%20T)%20%3D%3E%20x%3B%0D%0A%0D%0A%2F%2F%20r%3A%20%3CT%3E()%20%3D%3E%20%7B%20val%3A%20(x%3A%20T)%20%3D%3E%20T%20%7D%0D%0Aconst%20r%20%3D%20ref(id)%3B%0D%0A%2F%2F%20unsafe%20instantiations%20of%20r%0D%0Aconst%20r1%20%3D%20r%3Cnumber%3E()%3B%0D%0Aconst%20r2%20%3D%20r%3Cstring%3E()%3B%0D%0A%2F%2F%20update%20r1.val%20with%20a%20function%20specific%20to%20numbers%0D%0Ar1.val%20%3D%20(x%3A%20number)%20%3D%3E%20x%20*%202%3B%0D%0A%2F%2F%20using%20r2.val%20will%20cause%20runtime%20failure%0D%0Ar2.val(%22foo%22)%3B%0D%0A

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This doesn't seem different from other basic unsoundness induced by TS's covariant-by-default type system. You're basically doing a write through a supertype alias, e.g.
```ts
type A = { x: number | string };
type B = { x: number };
const b: B = { x: 3 };
const a: A = b;
a.x = "";
```

**Comment by susisu** [comment]
Yes and no. The results are very similar, but they have different roots.
In my case, it is related to the generalization, not the variance of types, and newly introduced in 3.4.x.
