### ISSUE TITLE
condition types not working

### ISSUE THREAD

**Issue by vipcxj** [Microsoft/TypeScript#31157]
**TypeScript Version:**  3.4.5

type guard, condition type

**Code**

```ts
interface Test {
  a: number;
  b: string;
}
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

type CTest<T> = T extends Test
  ? {
      props: Omit<T, keyof Test>;
      children: Test;
    }
  : null;

function Test<T extends Test>(t: T | null): CTest<typeof t> {
  if (t === null) {
    return null;
  } else {
    const { a, b, ...props } = t;
    return {
      children: {
        a,
        b
      },
      props
    };
  }
}
```

**Expected behavior:**
no error

**Actual behavior:**
The second return type wrong.

**Playground Link:** https://codesandbox.io/s/j4723x371y

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
TypeScript can't infer that you correctly followed the test condition of the conditional type by examining the control flow of the function

**Comment by vipcxj** [comment]
@RyanCavanaugh TypeScript can't recognize `t === null`?
