### ISSUE TITLE
Add quick fix to add explicit return type to method

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#31163]
## Search Terms
return type quick fix

## Suggestion

A quick fix to explicitly add the inferred return type to a function signature.

## Use Cases

![grafik](https://user-images.githubusercontent.com/17641229/56918704-0794c980-6abf-11e9-8cb5-460bfbb058c2.png)
ESLint complains about a missing explicit return type. TypeScript can infer a return type. Instead of having to look it up and type it out, a quick fix would be nice to automatically add it.

### Example 1
```ts
// Before quick fix:
function foo() {
    const bar = 1+1;
}

// After quick fix
function foo(): void {
    const bar = 1+1;
}
```

### Example 2:
```ts
// Before quick fix:
function foo() {
    return 1+1;
}

// After quick fix
function foo(): number {
    return 1+1;
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is coming from ES Lint, so we'd have to do something other than a quick fix (these always need associated errors), but yeah

**Comment by AnyhowStep** [comment]
I have a use case for such a "quick fix".

```ts
function foo () {
  return /*complicated expression*/;
}
function bar () {
  /*TS Error: Type instantiation excessively deep, potentially infinite*/
  /*complicated expression using foo()*/
}
```

When I explicitly add a return type to `foo()`, the error goes away because now the compiler doesn't have to check the implementation to get the return type of `foo()`. (In my case, the return type of foo is like 3 lines of code, not difficult to add)

**Comment by nick-lvov-dev** [comment]
Hey guys, just wanted to mention, I had the same issue and made an extension for this.
Check it out and send me your feedback!
https://marketplace.visualstudio.com/items?itemName=nick-lvov-dev.typescript-explicit-types

**Comment by AlCalzone** [comment]
This seems to be implemented in TypeScript 4.3 👏🏻

**Comment by AbdealiJK** [comment]
@AlCalzone could you point to how/where this is added ? If I want to make all the implicit types for my functions into explicit types - do I need to run with some flags ? Or do I still need to manually copy them and add them explicitly ?

**Comment by AlCalzone** [comment]
I put the cursor behind the closing `)` of the function, trigger refactors `CTRL+.` (for me) and choose the option mentioning the types.

**Comment by styfle** [comment]
Some additional details:

I had to put the cursor on the `function` keyword (or the name) to see the yellow light bulb.

It also works with <key>CMD</key>+<key>.</key> (macOS) or <key>CTRL</key>+<key>.</key> (Windows) instead of the light blub.

Under "Rewrite...", you'll see select the "Infer function return type" option.

<img width="222" alt="image" src="https://user-images.githubusercontent.com/229881/216340454-75e248ce-968c-45c5-830a-4ccbfb7d0554.png">

(technically its not considered a "Quick Fix" but a "Rewrite")
