### ISSUE TITLE
TypeScript language features frequently dying on large project

### ISSUE THREAD

**Issue by lemonmade** [microsoft/TypeScript#31162]
Issue Type: <b>Bug</b>

I work on our largest TypeScript project at Shopify (a node + React application). The project has about 6000 source files (I am not sure if this is uncommon, but we have to run `tsc` with more memory to avoid a dedicated type check process running out of memory). Many developers working on the project report frequent cases where editor functionality like autocomplete, go to definition, and in-editor type feedback dissapear. This happens across a range of different setups (different versions, regular and insider, different sets of extensions). 

Are there steps we can take to mitigate this? I am happy to give any other details that would help diagnose, as well as provide more detailed logs, if it would be useful.

VS Code version: Code - Insiders 1.34.0-insider (63c1ff218ecf3c2b3df8df1eab8e963d3c1f1a50, 2019-04-24T06:06:38.011Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.32GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rails|bun|0.13.0
vscode-gemfile|bun|0.0.2
solargraph|cas|0.19.6
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
url-encode|fle|1.1.0
vscode-pull-request-github|Git|0.6.0
vscode-graphql|Pri|0.1.7
ruby|reb|0.22.3
code-settings-sync|Sha|3.2.9
stylelint|shi|0.49.0
slim|sia|0.1.2
guides|spy|0.9.3
code-spell-checker|str|1.7.5
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.1.5
quokka-vscode|Wal|1.0.209
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Moving upstream. The TypeScript team should better know what type of information would be helpful to investigate this.

Some quick questions: what version of TypeScript are you using? Are developers using a workspace version of typescript in VS Code?

**Comment by AnyhowStep** [comment]
When you run `tsc` with `--diagnostics`, what's the output?

**Comment by lemonmade** [comment]
Thanks @mjbvz. Yes, developers are using a workspace version of TypeScript in VSCode. We're currently a bit behind on the TS version side of things: we're at 3.1.6. Updating isn't super trivial but I can go through with it if you feel there are changes that might help, but I have experienced the same issues locally when testing out TS 3.2.x as well.

@AnyhowStep here is the output (I need to run it with a bit more heap, otherwise I OOM before type checking completes):

```
$ node --max-old-space-size=2000 ./node_modules/.bin/tsc --noEmit --diagnostics
Files:           7932
Lines:         814763
Nodes:        3113440
Identifiers:   997351
Symbols:      1627426
Types:         785025
Memory used: 1752701K
I/O read:       0.51s
I/O write:      0.00s
Parse time:    12.42s
Bind time:      1.89s
Check time:    32.02s
Emit time:      0.00s
Total time:    46.33s
```

**Comment by mjbvz** [comment]
Yes please test using the latest TypeScript version 3.4.5 in workspace. This ships as the bundled version the current [VS Code insiders build](https://code.visualstudio.com/insiders/). You don't have to change the typescript version you are using to compile the project

**Comment by AnyhowStep** [comment]
I get OOM's, too, with some projects. I've had moments where type checking would take me 15+ minutes!
I've also had to wrestle with long check times, OOM's, and other weird compile issues for a while now.

The TS team can help you better but I figured I'd throw in my anecdotes that may (or may not) help you.

---

For one of my projects, when I run,
`find . -type f | sed 's/.*\.//' | sort | uniq -c`,

I get,
```
  11 md
2010 ts
```

What do you get when you run that command on your source folder?

-----

And my diagnostics with `--noEmit --diagnostics`,
```
Files:           5178
Lines:         453729
Nodes:        1811212
Identifiers:   626016
Symbols:      2127140
Types:         513976
Memory used: 2092972K
I/O read:       0.25s
I/O write:      0.00s
Parse time:     3.99s
Bind time:      1.15s
Check time:    45.58s
Emit time:      0.00s
Total time:    50.71s
```

I'd say my project is really heavy on generics, conditional types, type trickery, etc.
And that definitely adds to the long check times.
I've had cases where simply changing a *class method* to a *non-class function* dramatically sped up check times (Don't ask me why that worked). So, the solution is not always intuitive. 

Does your project have a lot of that? Or does it use any libraries that tend to be heavy with type manipulations?

What are your dependencies, and dev dependencies?

-----

One thing that jumps out at me is that your parse time is `12.42s`. That's *really* long for just parsing.
How many lines of code is your project?

When I run,
```
find . -name '*.ts' -o -name '*.tsx'  | xargs wc -l
```

I get,
```
/*snip*/
66187 total
```

**Comment by mjbvz** [comment]
I'm closing this issue as it is out of date.

If you are seeing performance issue when using current versions of TypeScript, please open a new issue so that we can investigate
