### ISSUE TITLE
No error for block-scoped declaration in different case-clause

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#31167]
Found from https://github.com/angular/angular-cli/issues/14290

Compile this with `"target": es2015`

```ts
let t = 'b';

switch (t) {
  case 'a':
    let numberMin = 1;
    console.log(numberMin)
    break;

  case 'b':
    numberMin = 2;
    console.log(numberMin)
    break;
}
```

TypeScript doesn't error, but at runtime this gives

```
ERROR ReferenceError: numberMin is not defined
```

**Comment by RyanCavanaugh** [comment]
Is there a reason Angular devs might be more likely to hit this?

**Comment by ajafff** [comment]
Duplicate of #19503

**Comment by daniel19801** [comment]
Unsubscribe to all stop Sent from my Sprint Samsung Galaxy S10+.
null

**Comment by alan-agius4** [comment]
@RyanCavanaugh, in version 8 we are going to use es2015 as a target for both new and old projects.

**Comment by fatcerberus** [comment]
Looks like a TDZ error.  That's tricky to detect at compile-time in general, as it depends on when control-flow actually hits the `let` statement (so kind of like the halting problem).  We can probably easily detect simple cases like this though.

**Comment by DanielRosenwasser** [comment]
In a sense, it's "more likely" for Angular users because they will be switching to `--target: es2015` in the near future. That means existing code will be broken at runtime with little warning.
