### ISSUE TITLE
TypedArray.subarray incorrectly expects at least 1 argument

### ISSUE THREAD

**Issue by paulmedynski** [microsoft/TypeScript#31174]
**TypeScript Version:**
3.4.3

**Search Terms:**
subarray

**Code**
```ts
const a = new Uint8Array(50);
const b = a.subarray();
```

**Expected behavior:**
No compiler error.  As per the ES6 spec:

https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.prototype.subarray

`TypedArray.subarray()` doesn't require any arguments - both `begin` and `end` are optional according to the prototype declaration.  However, reading the functional steps shows `end` being explicitly called out as optional, whereas `begin` is not.  At the least, the functional steps are inconsistent with the prototype declaration, but I believe TypeScript should adhere to the prototype in such a case.

**Actual behavior:**
```
src/foo.ts:566:20 - error TS2554: Expected 1-2 arguments, but got 0.

566     const result = input.subarray();
                       ~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es5.d.ts:2180:14
    2180     subarray(begin: number, end?: number): Uint8Array;
                      ~~~~~~~~~~~~~
    An argument for 'begin' was not provided.
```

**Comment by magic-akari** [comment]
Same issue. Can I take this?

**Comment by paulmedynski** [comment]
Yes, please do!  I'm using a `@ts-ignore` as a workaround for the moment.

Should I open a bug against the spec itself?  The prototype declaration and functional steps don't seem to match.  Any thoughts?

**Comment by cpplearner** [comment]
Per https://github.com/tc39/ecma262/issues/1528#issuecomment-489868427:

> Every function can always be called with any number of arguments in the language - whether a "required" argument throws when omitted, or has a default value, is a different consideration.

**Comment by paulmedynski** [comment]
True, but the functional steps for `subarray()` don't describe the behaviour when the `begin` argument isn't supplied.  They do explicitly describe the behaviour when `end` isn't supplied though.  Seems like a simple omission.

**Comment by cpplearner** [comment]
Well the spec does cover this case: Clause 17 says an omitted argument has the value `undefined`, and the abstract operation `ToInteger` returns `0` for `undefined` value.

**Comment by magic-akari** [comment]
I thought I have fixed this issue in the commit https://github.com/magic-akari/TypeScript/commit/82c297eb70fd6e200d65bec2bf4f81209a12feb8

May I take this bug for PR? @RyanCavanaugh
