### ISSUE TITLE
Mismatch order causes Type 'RegExpMatchArray' is not assignable to type 'boolean'.

### ISSUE THREAD

**Issue by tarsupin** [Microsoft/TypeScript#31171]
Note: This does not appear to be related to ticket 15450.

**Search Terms:**
matching regex string
RegExpMatchArray
.match

**Code**

```ts
static someMethod( str: string ): boolean {

    // This return would return true:
    return (str.match(/^[0-9a-z_]+$/i) && true);

    // This return throws the following error:
    // ERROR: Type 'RegExpMatchArray' is not assignable to type 'boolean'.
    return (true && str.match(/^[0-9a-z_]+$/i));
}
```

**Expected behavior:**
Both of these should return `true`, since the only difference is which command was on the left side of the && operator.

**Actual behavior:**
One of them throws the error `Type 'RegExpMatchArray' is not assignable to type 'boolean'.`

--------------------
Hope this helps!

**Comment by fatcerberus** [comment]
This is a quirk of JavaScript and not a TypeScript bug:
```js
console.log(false && 812);  // false
console.log(true && 812);  // 812
```

`&&` evaluates to whatever is on the right-hand side of the operator if the first operand is truthy.  Likewise if the first operand is falsy:
```js
console.log(null && true);  // null
console.log(0 && true);  // 0
```

**Comment by tarsupin** [comment]
Interesting. In that case, I'll close the issue. Thanks for the response :)
