### ISSUE TITLE
Why are optional arguments not typed with undefined?

### ISSUE THREAD

**Issue by ycmjason** [Microsoft/TypeScript#31170]
Sorry for this really stupid question. 🙏  I am pretty sure this is a design choice. But I don't get the reasons behind and couldn't seem to find the answer.

In this [example](https://www.typescriptlang.org/play/index.html#src=function%20buildName(firstName%3A%20string%2C%20lastName%3F%3A%20string)%20%7B%0D%0A%20%20%20%20if%20(lastName)%0D%0A%20%20%20%20%20%20%20%20return%20firstName%20%2B%20%22%20%22%20%2B%20lastName%3B%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20%20%20return%20firstName%20%2B%20%22%20%22%20%2B%20lastName%3B%0D%0A%7D%0D%0A%0D%0Alet%20result1%20%3D%20buildName(%22Bob%22)%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20works%20correctly%20now%0D%0Alet%20result2%20%3D%20buildName(%22Bob%22%2C%20%22Adams%22%2C%20%22Sr.%22)%3B%20%20%2F%2F%20error%2C%20too%20many%20parameters%0D%0Alet%20result3%20%3D%20buildName(%22Bob%22%2C%20%22Adams%22)%3B%20%20):

```ts
function buildName(firstName: string, lastName?: string) {
    if (lastName)
        return firstName + " " + lastName;
    else
        return firstName + " " + lastName;
}

let result1 = buildName("Bob");                  // works correctly now
let result2 = buildName("Bob", "Adams", "Sr.");  // error, too many parameters
let result3 = buildName("Bob", "Adams");  
```

`lastName` is an optional argument and shouldn't typescript type `lastName` as `string | undefined` instead of `string`? In this example, typescript should be able to spot the error in the `else` case but it didn't.

**Comment by RyanCavanaugh** [comment]
It is typed that way, but `string + undefined` is considered legal.

Please use StackOverflow for questions, as indicated by the templates. Thanks!

**Comment by ycmjason** [comment]
But if you hover on the `lastName` in the playground, it shows `string` instead of `string | undefined`?

**Comment by j-oliveras** [comment]
In playground, StrictNullChecks are disabled by default, enable it on Options.

**Comment by ycmjason** [comment]
Thank you @j-oliveras . I will close the issue.
