### ISSUE TITLE
Add a flag to automatically insert `const` to variable declarations

### ISSUE THREAD

**Issue by mksmtn** [Microsoft/TypeScript#31186]
## Search Terms

const, const only, automatic const, constants, constants only

## Suggestion

Add a compiler flag (e.g. `--autoConsts`, `--constOnly`, I'll call it just Flag latter) to auto insert `const` keyword before variable declarations, and disallow 1) manually writing `let`, `const`, or `var`, 2) variable reassignment

## Use Cases

This will make TS stricter and will make variable declarations denser, saving some time and energy for developers and making code less polluted.

## Examples

    foo = 'foo';
    function bar() {
        baz = 'baz';
    }

would generate the following code if Flag is enabled

    const foo = 'foo';
    function bar() {
        const baz = 'baz';
    }

the following code would result in a compilation error

    // not able to reassign a variable
    foo = 'foo';
    foo = 'next foo';

    // same for function/method arguments
    function bar(arg) {
        arg = transform(arg);
    }

All mutations will reside in objects, i.e.

    // this would work
    foo = { name: 'John' };
    foo.name = 'Jane';

    // as well as this
    class Bar {
        constructor(private counter = 0) { }
        increment() {
            this.counter++;
        }
    }    

## Checklist

For Flag should be enabled, and generated code would be normal JS code, so

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by lll000111** [comment]
This starts down a path where you mix in a linter into the language.  What is the advantage? It works well having that separate. If you can force people to use your tsconfig you can also force them to use your eslintrc. Creating a huge monolith that does everything is not good if there is no actual reason for such tight integration.

**Comment by mksmtn** [comment]
@lll000111 I agree that we shouldn't mix linter and compiler. I classify the proposed functionality as compiler job, not linter. Because it not only emits errors if `let`, `var`, or `const` are used, but it transforms code TS without `const` into JS code with `const`.

**Comment by RyanCavanaugh** [comment]
This violates the "changes the behavior of JS code" rule.
