### ISSUE TITLE
strictNullChecks, typeof variable of T|undefined is undefined when initialized to undefined

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#31187]
**TypeScript Version:**  3.4.1

**Search Terms:** strictNullChecks, typeof, undefined, union

**Code**

```ts
//--strictNullChecks

//Hover over `x`
//Actual: let x: { k: string; } | undefined
//As expected
let x: { k: string } | undefined = undefined;

//Hover over `y`
//Actual: let y: undefined
//Expected: let y: { k: string; } | undefined
let y: (
    //Hover over `typeof x`
    //Actual: let x: undefined
    //Expected: let x: { k: string; } | undefined
    typeof x
) = undefined;

//Actual: Type '{ k: string; }' is not assignable to type 'undefined'.
//Expected: Assign OK
y = { k: "v" };
```

**Expected behavior:**

Assignment to work

**Actual behavior:**

Assignment does not work

If you change it to `let x: { k: string } | undefined = { k : "" };`, then `y = undefined` fails.

**Playground Link:** [Here](http://www.typescriptlang.org/play/#src=%2F%2F--strictNullChecks%0D%0A%0D%0A%2F%2FHover%20over%20%60x%60%0D%0A%2F%2FActual%3A%20let%20x%3A%20%7B%20k%3A%20string%3B%20%7D%20%7C%20undefined%0D%0A%2F%2FAs%20expected%0D%0Alet%20x%3A%20%7B%20k%3A%20string%20%7D%20%7C%20undefined%20%3D%20undefined%3B%0D%0A%0D%0A%2F%2FHover%20over%20%60y%60%0D%0A%2F%2FActual%3A%20let%20y%3A%20undefined%0D%0A%2F%2FExpected%3A%20let%20y%3A%20%7B%20k%3A%20string%3B%20%7D%20%7C%20undefined%0D%0Alet%20y%3A%20(%0D%0A%20%20%20%20%2F%2FHover%20over%20%60typeof%20x%60%0D%0A%20%20%20%20%2F%2FActual%3A%20let%20x%3A%20undefined%0D%0A%20%20%20%20%2F%2FExpected%3A%20let%20x%3A%20%7B%20k%3A%20string%3B%20%7D%20%7C%20undefined%0D%0A%20%20%20%20typeof%20x%0D%0A)%20%3D%20undefined%3B%0D%0A%0D%0A%2F%2FActual%3A%20Type%20'%7B%20k%3A%20string%3B%20%7D'%20is%20not%20assignable%20to%20type%20'undefined'.%0D%0A%2F%2FExpected%3A%20Assign%20OK%0D%0Ay%20%3D%20%7B%20k%3A%20%22v%22%20%7D%3B)

-----

I can see why it works this way, because of flow analysis. At the point in time where I use `typeof x`, the type of its value is, indeed, `undefined`.

However, I expect `typeof` to give the type of the variable. Not the type of the value of the variable, as derived by flow analysis.

The workaround isn't terrible, just declare the type elsewhere `type T = { k:string }`, and use `T|undefined` explicitly but this behaviour of `typeof` just struck me as odd

**Comment by RyanCavanaugh** [comment]
It's perhaps debatable whether `typeof expr` should give you the flow-control type or the declared type, but the former is certainly more powerful and isn't something you can do a workaround to get.

**Comment by AnyhowStep** [comment]
Makes sense to me! Thank you
