### ISSUE TITLE
Quick info on 'new' keyword should be the same as that of resolved expression

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31180]
```ts
class C {
    /**
     * NOTE: this constructor is private! Please use the factory function
     */
    private constructor() { }
    static makeC() { new C(); }
}

new C();
```

**Expected**: Quick info on `C` and `new` in `new C()` should be the same.
**Actual**: no quick info on `new`

### Why it matters

It'd be nice if hovering over the error at any point could also give you better quick info.

![image](https://user-images.githubusercontent.com/972891/56998994-4760bd00-6b62-11e9-978f-a14b1eb09361.png)

![image](https://user-images.githubusercontent.com/972891/56999003-52b3e880-6b62-11e9-8b4b-9643e8133e76.png)

**Comment by DanielRosenwasser** [comment]
(Courtesy of @jonathandturner)

**Comment by rpgeeganage** [comment]
@DanielRosenwasser , 
May I work on this please?

**Comment by DanielRosenwasser** [comment]
Yes you certainly may! This one will be in the language service. Start [here](https://github.com/Microsoft/TypeScript/blob/d1646c74fdeef09bdc3688a709b37a42c2859349/src/services/services.ts#L1459) in `getQuickInfoAtPosition`.

Tests can be found in `tests/cases/fourslash`. I'd make a `quickInfoOnNewKeyword01.ts` file there.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser 
Thanks a lot. I’ll start working on this.

**Comment by rpgeeganage** [comment]
I have started working on this. Will open a PR as soon as I finished it.
Thanks.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
Can you please help me on viewing the quick info?
I started with a test case. I added new file `quickInfoOnNewKeyword01.ts` in `tests/cases/fourslash`.
The content of the test file is as follows.
```ts
/// <reference path='fourslash.ts' />

////class C {
////    /**
////     * NOTE: this constructor is private! Please use the factory function
////     */
////    private constructor() { }
////    static makeC() { new C(); }
////}
////
////new C();

debug.printCurrentQuickInfo();
``` 
After that I ran the test as `gulp runtests --tests=quickInfoOnNewKeyword01`.
The only output was:
`Quick Info: class C`
How can I print the entire quick info ?

**Comment by DanielRosenwasser** [comment]
I'm not sure since it's been a while and I don't develop in the codebase as much anymore - but you'll have to look for where quick info is resolved for overloads (e.g. what code path is it taking for when you hover on the identifier?). Then, when the quick info target is a `NewKeyword`, find a way to dispatch the same logic.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
Thanks a lot. I'll look into it.

**Comment by rpgeeganage** [comment]
@sandersn ,
Can you please give me a small help on this please?
I have to debug till this line.
My test case:
```ts
////class Cat {
////  /**
////   * NOTE: this constructor is private! Please use the factory function
////   */
////  private constructor() { }
////
////  static makeCat() { new Cat(); }
////}

////ne/*1*/w C/*2*/at();

goTo.marker('2');
debug.printCurrentQuickInfo();
debug.printErrorList();

goTo.marker('1');
debug.printCurrentQuickInfo();
debug.printErrorList();
```
for the `marker 2`,
expression in below line evaluate as `false`
https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L1472
so,
`symbol` value is not null, so it goes to the following function.
https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L1484
```ts
const { symbolKind, displayParts, documentation, tags } = typeChecker.runWithCancellationToken(cancellationToken, typeChecker =>
  SymbolDisplay.getSymbolDisplayPartsDocumentationAndSymbolKind(typeChecker, symbol, sourceFile, getContainerNode(node), node)
);
```
but for the `marker 1`, `symbol` is `undefined` so, it doesn't go through the above function.
as a result, `documentation` is not properly generated.

**Comment by rpgeeganage** [comment]
@RyanCavanaugh,
Will you be able to help me regarding this ticket, please?
Thanks.

**Comment by rpgeeganage** [comment]
I have opened a PR (https://github.com/Microsoft/TypeScript/pull/31262).
Please review and give me feedback. Thanks a lot.

**Comment by DanielRosenwasser** [comment]
Thanks @rpgeeganage!
