### ISSUE TITLE
`Omit` from #31115 makes all properties required

### ISSUE THREAD

**Issue by InExtremaRes** [microsoft/TypeScript#31190]
Since the changes of #31115, `Omit<T, K>` makes all properties of `T` required.

***

**TypeScript Version:**  3.5.0-dev.20190501, 3.4.5

**Search Terms:** omit optional

**Code**

```ts
type A = {
    a: number;
    b?: string;
};

type B = Omit<A, 'a'>;
```

**Expected behavior:** `B` is `{ b?: string }` (`{ b?: string | undefined }` with `strictNullChecks`).

**Actual behavior:** `B` is `{ b: string }` (`{ b: string | undefined }` with `strictNullChecks`), with property `b` required.

**Playground Link:**  [link](https://www.typescriptlang.org/play/index.html#src=type%20Omit1%3CT%2C%20K%20extends%20keyof%20any%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0Atype%20Omit2%3CT%2C%20K%20extends%20keyof%20any%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20Exclude%3Ckeyof%20T%2C%20K%3E%5D%3A%20T%5BP%5D%0D%0A%7D%3B%0D%0A%0D%0Atype%20A%20%3D%20%7B%0D%0A%20%20%20%20a%3A%20number%3B%0D%0A%20%20%20%20b%3F%3A%20string%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20B1%20%3D%20Omit1%3CA%2C%20'a'%3E%3B%0D%0A%2F%2F%20B1%20%3D%20%7B%20b%3F%3A%20string%3B%20%7D%0D%0A%0D%0Atype%20B2%20%3D%20Omit2%3CA%2C%20'a'%3E%3B%0D%0A%2F%2F%20B2%20%3D%20%7B%20b%3A%20string%3B%20%7D%0D%0A)

pin @DanielRosenwasser

**Comment by InExtremaRes** [comment]
Just I'd like to remark that, as the playground link shows, when `Omit` is defined in terms of `Pick` the produced type preserves optional properties as optional; when it is changed to is own mapped type all properties become required.

**Comment by jcalz** [comment]
Can we reopen #31104 then?   I had some [other ideas](https://github.com/Microsoft/TypeScript/issues/31104#issuecomment-489152038) about it, if it matters
