### ISSUE TITLE
tsc --strict is allowing me to use an assigned var.

### ISSUE THREAD

**Issue by StokeMasterJack** [microsoft/TypeScript#31198]
**TypeScript Version:**  3.4.5

**Search Terms:**

**Code**

```ts
let aaa: string | null;
function getAaa(): string {
    if (aaa === null) {  aaa = 'hello'; }
    return aaa;
}
console.log(getAaa().length);
```

**Expected behavior:**
I expected a compile error (when using --strict). Something like this:
error TS2454: Variable 'aaa' is used before being assigned.

**Actual behavior:**
No compile error. But got this runtime error: 
Cannot read property 'length' of undefined

**Playground Link:** https://www.typescriptlang.org/play/#src=let%20aaa%3A%20string%20%7C%20null%3B%0D%0A%0D%0Afunction%20getAaa()%3A%20string%20%7B%0D%0A%20%20%20%20if%20(aaa%20%3D%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20aaa%20%3D%20'hello'%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20aaa%3B%0D%0A%7D%0D%0A%20%0D%0A%0D%0Aconsole.log(getAaa().length)%3B

**Comment by nmain** [comment]
See https://github.com/Microsoft/TypeScript/issues/28013
