### ISSUE TITLE
TS2339 error in union types containing void when there is a short circuiting

### ISSUE THREAD

**Issue by DaKoala** [Microsoft/TypeScript#31197]
## Search Terms

short circuit, void, union types

## Suggestion

Not throwing a TS2339 error in union types containing `void` when all cases of the `void` condition are checked and there is a short-circuiting.

## Use Cases

See example. Currently there will be a TS2339 error, which requires more code to handle different situations.

However, in this case, if `uncertainUser` is neither `undefined` nor `null`, it must be of type `User` and will have attribute `username`

## Examples

```typescript
interface User {
    username: string;
    password: string;
}

function userOrNothing(): User | void {
    if (Math.random() > 0.5) {
        return {
            username: 'foo',
            password: 'bar',
        };
    }
    return undefined;
}

const uncertainUser = userOrNothing();
// TS2339: Property 'username' does not exist on type 'void | User'. 
// Property 'username' does not exist on type 'void'
if (uncertainUser === undefined || uncertainUser === null || uncertainUser.username === 'baz') {
    console.log('user is undefined!');
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
Relevant comment by @RyanCavanaugh [here](https://github.com/Microsoft/TypeScript/issues/24852#issuecomment-396321058).

This is unsafe because value returning functions are assignable to void returning functions.
```ts
function num(): number {
    return 3;
}

function str(): string {
    return "string";
}

const ignore: () => void = str;
const unsafe: () => number | void = () => Math.random() > 0.5 ? num() : ignore();
const val: number | void = unsafe(); // Will be 3 or "string";
```
Knowing that `val` is not `undefined` or `null` is not enough to guarantee that it is a number, because the value may actually be a string at runtime.

I would just write your function with a return type of `User | undefined` instead.

**Comment by DaKoala** [comment]
@jack-williams 
Thanks for your example and advice. I changed it to `User | undefined` and everything was good.
