### ISSUE TITLE
Suggestion: Preserve JSDoc comments on class properties

### ISSUE THREAD

**Issue by Laguana** [Microsoft/TypeScript#3119]
I wanted to document some properties of a class, and be able to iterate over the properties to automatically produce help information documenting its use at runtime. I had something like

```
class Foo {
  /** JSDoc documentation here */
  public bar: string;
  /** more JSDoc Documentation here */
  public baz: number;
// [...]
}
```

When I compiled this file, the JSDoc documentation only made it into the .d.ts file. Unfortunately since I wanted to access this information at runtime I couldn't find any libraries like jsdoc-parse which can cope with .d.ts files, and the comments are missing from the compiled .js file.

**Comment by mhegazy** [comment]
> When I compiled this file, the JSDoc documentation only made it into the .d.ts file.

JavaScript does not have property declaration, nor classes. so what is the proposed emit for the above code sample?

> Unfortunately since I wanted to access this information at runtime I couldn't find any libraries like jsdoc-parse which can cope with .d.ts files

you can use the typescript compiler to parse your .d.ts, it is javascript :D see [using the compiler API wiki page](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)  for more details.
