### ISSUE TITLE
Array element inferred type from destructure does not recognize properties unless explicitly declared

### ISSUE THREAD

**Issue by williamtroy** [Microsoft/TypeScript#31193]
**TypeScript Version:**  3.3.3, 3.4.3, 3.4.5

**Search Terms:**
"does not exist on type"
"does not exist on type" bivariant

**Explanation**
It seems like when an array with elements of multiple types is not explicitly declared, and the elements do not overlap at all, the component type does not correctly evaluate which type it is. Output errs like shown below.
This does not happen if the array is cast as following or declared as return type on the function. `[{attributeA:boolean}, ReactComponent]`

e.g.
```ts
return [...] as [{attributeA:boolean}, ReactComponent]
```

**Code**

```ts
interface ReactComponent {
    attributeB: any;
}

const getArray = () => {
    return [
        {
            attributeA: true
        },
        {
            attributeB: true
        } as ReactComponent
    ];
};

const [item1, item2] = getArray();

const itema = item1.attributeA;
const itemb = item2.attributeB;
```

**Expected behavior:**
No errors

**Actual behavior:**
testScript1.tsx:18:21 - error TS2339: Property 'attributeA' does not exist on type 'ReactComponent | { attributeA: boolean; }'.
  Property 'attributeA' does not exist on type 'ReactComponent'.

18 const itema = item1.attributeA;
                       ~~~~~~~~~~

testScript1.tsx:19:21 - error TS2339: Property 'attributeB' does not exist on type 'ReactComponent | { attributeA: boolean; }'.
  Property 'attributeB' does not exist on type '{ attributeA: boolean; }'.

19 const itemb = item2.attributeB;
                       ~~~~~~~~~~
Found 2 errors.

**Comment by MartinJohns** [comment]
In your working example you declare a tuple that contains two items: one type A, one type B. So when you destructure it the compiler knows: The first element is A, the second one is B.

In your non-working example you declare an array that contains items that are either type A or type B. So how would the compiler know what it is? It could be both according to the array declaration.

This is by design and intended. You can have an easier way declaring your tuples by using const contexts from TypeScript 3.4:

    const getArray = () => {
        return [
            {
                attributeA: true
            },
            {
                attributeB: true
            } as ReactComponent
        ] as const; // <--
    };

`as const` will make it a const context and cause the compiler to infer it as a tuple, not an array.

**Comment by williamtroy** [comment]
> In your working example you declare a tuple that contains two items: one type A, one type B. So when you destructure it the compiler knows: The first element is A, the second one is B.

Your insight has been incredibly useful and I see now the error of my ways.

>In your non-working example you declare an array that contains items that are either type A or type B. So how would the compiler know what it is? It could be both according to the array declaration.

It feels like it should try to match both before giving up, but you're right. TS is strongly typed after all. Quite clear if you put it that way.

>You can have an easier way declaring your tuples by using const contexts from TypeScript 3.4
This is pure sorcery. Useful sorcery, nonetheless!
