### ISSUE TITLE
TypeScript snippets in VS

### ISSUE THREAD

**Issue by craigktreasure** [Microsoft/TypeScript#312]
Moving this over from CodePlex (23 votes, assigned to jonturner, http://typescript.codeplex.com/workitem/938):

I would really like to be able to use a TypeScript version of the JavaScript code snippets when writing TypeScript in Visual Studio.

**Comment by Mogikan** [comment]
Add TS language to Code Snippets Manager, please!

**Comment by gravidThoughts** [comment]
12 more votes for TS Code Snippets!!!!

I am repping my colleagues :)

**Comment by jon49** [comment]
An auto `curry` `interface` generator would be nice too:

http://stackoverflow.com/questions/28566969/create-programmable-snippet-for-visual-studio-with-node-js-code

**Comment by vilic** [comment]
Can we expect this to be in 1.5 tools?

**Comment by paulvanbrenk** [comment]
@vilic this looks like something we would add for 1.6, most of the work is probably in the creation of the snippet files (inc. translation, setup etc.).

**Comment by vilic** [comment]
Good to know, thanks! @paulvanbrenk

**Comment by NoelAbrahams** [comment]
I hope the new snippets are a bit radical - along the lines of @danquirk's suggestion:

>  Personally I don't think snippets should be in their own menu with a long, awkward key chord to invoke. There's no reason they can't be treated like any other completion result as many other languages/editors do.

I should just be able to start typing `my-custom-snippet` anywhere on a code file, and the snippet should be rendered at the point of the cursor upon selection.

**Comment by paulvanbrenk** [comment]
@NoelAbrahams unfortunately we (TypeScript) don't control that part of the snippet experience without a lot of customization (for `my-custom-snippet`), it will work that way for inbox-snippets. I will bring this up with the team that is responsible for the overall snippet experience, and you can add that as an item on http://visualstudio.uservoice.com.

**Comment by fpenarru** [comment]
+1

**Comment by araqiel-dev** [comment]
``region`` snippet missing in Visual Studio 2015 :'(

**Comment by drake7707** [comment]
Some others I'd like to see that aren't mentioned yet

````
forof -> for(let el of elements) { ... }
forr -> for(let i = length-1; i >= 0; i--) { ... }
```

**Comment by Neurothustra** [comment]
can we make this happen? As in, all of it?

**Comment by sebdoucet** [comment]
This is a real problem, from your team but also from VS Team. Why snippets need to be activated or whatever other limitation. Code snippet should always be accessible for all language supported by VS... From C#, I never write a complete for or property accessor...even javascript have a better support on Visual Studio!

Sublime already have snippets for Typescript and from to long time Typescript run better on sublime...

**Comment by titobf** [comment]
+1 It would be really nice to have this feature. I was going to create my own snippet for TS and then realized that it's not possible.

**Comment by gildorwang** [comment]
+1

**Comment by sambres** [comment]
+1

**Comment by DarthDerrr** [comment]
+1 - how is this not already there, seriously?

**Comment by aleksey-bykov** [comment]
if anyone has time please consider implementing and sharing a working example of this:

- https://msdn.microsoft.com/en-us/library/ff926100.aspx

**Comment by paulvanbrenk** [comment]
Actually you'll want to reference the Roslyn implementation[0].. since that'll solve you a bunch of time.

[0] https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/VisualStudio/CSharp/Impl/Snippets/CSharpSnippetInfoService.cs

**Comment by ZenSoftware** [comment]
+1

**Comment by sstorie** [comment]
Man, I just assumed this would be supported in the latest version of Visual Studio 2015, and found this while starting to create some Angular 2 snippets. I can't believe this is something that VSCode handles perfectly, but the flagship product can't...

**Comment by MCKRUZ** [comment]
Which project do we need to post on to make this a feature in Visual studio 2015?

**Comment by mhegazy** [comment]
> Which project do we need to post on to make this a feature in Visual studio 2015?

you are in the right place.

**Comment by MCKRUZ** [comment]
sorry, is this something that is going to be incorporated into Visual Studio 2015 soon?

**Comment by mhegazy** [comment]
It is on the list of committed features. I do not have an ETA at the time being. there are other features/bugs that we are working on as well, and we are a small team.

**Comment by MCKRUZ** [comment]
Can the community help in any way?

**Comment by mhegazy** [comment]
> Can the community help in any way?

Unfortunately no. this is part of the VS plugin code that is not open source at the moment.

**Comment by AkosLukacs** [comment]
Just adding typescript in the list of languages supported by the built in snippet engine would allow the community,  or companies to define the snippets themselves. For example there are a bunch of JS snippets in the Side waffle pack. Not created by MS, but usable by anyone.

**Comment by sebdoucet** [comment]
Yep, totaly agree with that!! I've already make custom ones for JS and C# and it will take me 1h to get the most used like if,for's,get,set,class,namespace...

It's a huge lost of time to write a complete and boring for-i !!

Unlock it on VS or give the way to add a language.

**Comment by MCKRUZ** [comment]
I actually already added typescript snippets to side waffle, I'm just waiting for the typescript team to finish their piece.

**Comment by alois-wever** [comment]
+1

**Comment by jojogeyer** [comment]
+1

**Comment by omefire** [comment]
Thank you all for the suggestions.

So far, here's the list of snippets that are being added to VS:
- alert
- cl: console.log
- class
- do: do while
- else
- for
- forin
- forr
- function
- if
- iife : (function(x) { })();
- switch
- try
- while
- with

Please, let me know if you have further suggestions.

**Comment by MCKRUZ** [comment]
Omar,

 

It’s more the ability to “create new” snippets that is the real rub.  The community has a ton of snippets ready to go (me included).  Any idea of when that will be available?

**Comment by omefire** [comment]
Yes, included with these changes, will also be the ability to add custom snippets.

**Comment by AkosLukacs** [comment]
Omar,

IIFE on typescript feels kind of strange with namespaces and modul
systems...

But the main news is that ts snippets are coming to VS, thanks!

**Comment by KamyarNazeri** [comment]
@omefire 

> Please, let me know if you have further suggestions.

I would say `ctor` to create a constructor for the containing class, which is quite handy snippet in C#

**Comment by aleksey-bykov** [comment]
@omefire

consider allowing javascript or c# expressions in the scripts placeholders so that they are not just dumb templates but capable of some transformations

**Comment by paulvanbrenk** [comment]
@aleksey-bykov we will consider that, but not for the initial release... the snippet infrastructure in VS doesn't allow that, and we don't want to delay this feature further ;). Do you have an example where that would be useful.

**Comment by aleksey-bykov** [comment]
here is an example of regex transformations  https://manual.macromates.com/en/snippets

**Comment by paulvanbrenk** [comment]
@aleksey-bykov I was looking for a TypeScript specific example what is a case where you would use this?

**Comment by aleksey-bykov** [comment]
@paulvanbrenk, as far as see it snippets are language agnostic, because they just generate output text (that happened to be a piece of code) based on some input text or lack of thereof 

back to your question, in my pet project in TypeScript I use the following snippet a lot:

```typescript
export type SomeSingletonKind = 'some-singleton-kind';
export const someSingletonKind : SomeSingletonKind = 'some-singleton-kind';
```

Example: https://github.com/aleksey-bykov/commandlining/blob/master/failing.ts

```typescript
export type UnexpectedCharacter = 'unexpected-character';
export const unexpectedCharacter: UnexpectedCharacter = 'unexpected-character';

export type UnhandledState = 'unhandled-state';
export const unhandledState: UnhandledState = 'unhandled-state';

export type UnspecifiedParameterName = 'unspecified-parameter-name';
export const unspecifiedParameter: UnspecifiedParameterName = 'unspecified-parameter-name';

export type UnfinishedArgument = 'unfinished-argument';
export const unfinishedArgument: UnfinishedArgument = 'unfinished-argument';

export type UnspecifiedArgument = 'unspecified-argument';
export const unspecifiedArgument: UnspecifiedArgument = 'unspecified-argument';

export type UnspecifiedCommand = 'unspecified-command';
export const unspecifiedCommand: UnspecifiedCommand = 'unspecified-command';

export type UnexpectedEndOfInput = 'unexpected-end-of-input';
export const unexpectedEndOfInput: UnexpectedEndOfInput = 'unexpected-end-of-input';

export type UnspecifiedCommandOrParameter = 'unspecified-command-or-parameter';
export const unspecifiedCommandOrParameter: UnspecifiedCommandOrParameter = 'unspecified-command-or-parameter';

export type UnattendedCharacter = 'unattended-character';
export const unattendedCharacter: UnattendedCharacter = 'unattended-character';

export type UnexpectedCommand = 'unexpected-command';
export const unexpectedCommand: UnexpectedCommand = 'unexpected-command';

export type UnexpectedBuilderState = 'unexpected-builder-state';
export const unexpectedBuilderState: UnexpectedBuilderState = 'unexpected-builder-state';

export type UnexpectedParameterName = 'unexpected-parameter-name';
export const unexpectedParameterName: UnexpectedParameterName = 'unexpected-parameter-name';

export type ErrorCode = UnhandledState | UnspecifiedParameterName | UnfinishedArgument
    | UnspecifiedArgument | UnexpectedCharacter | UnattendedCharacter
    | UnexpectedEndOfInput | UnspecifiedCommand | UnspecifiedCommandOrParameter
    | UnexpectedCommand | UnexpectedBuilderState | UnexpectedParameterName;
```


As you can see the spellings of type-literal, type-alias-name and constant-identifier are all different: Pascal, Dashed, Camel

It means I cannot use snippets based solely on templates, because I need to apply a transformation to get the case I need. This is where I wish snippets had transformations.

**Comment by ruslanss** [comment]
i desperately need these for TypeScript: https://visualstudiogallery.msdn.microsoft.com/5d11e28f-0f7c-4f6e-ae50-699fcd5a3500

would save me a LOTTA of time

**Comment by aleksey-bykov** [comment]
for those who can't wait anymore, [VS Code](https://code.visualstudio.com/) can [do TypeScript very well](https://code.visualstudio.com/Docs/languages/typescript) and it has [snippets](https://code.visualstudio.com/Docs/customization/userdefinedsnippets)

**Comment by paulvanbrenk** [comment]
Snippets will be part of VS "15" post Preview 4. 

For smarter snippets I opened: #10309

**Comment by MaklaCof** [comment]
I installed Microsoft Visual Studio Enterprise 15 Preview 4, but I don't see any options to insert snippet.
Tried with:

- Edit -> InstalliSense -> Insert snippet (doesn't exist)

- Ctrl + k, Ctrl + x

- Right click -> Insert Snippet

In Tools -> Code Snippets Manager I don't see TypeScript in Language drop down.
How can I insert snippet?

**Comment by paulvanbrenk** [comment]
@MaklaCof Snippets for TypeScript is not available in Preview 4, but will be in the next release.

**Comment by MaklaCof** [comment]
Then someone should fix Milestone to avoid confusion.

**Comment by lorenlew** [comment]
@paulvanbrenk, as you mentioned "Snippets will be part of VS "15" post Preview 4."
what about VS 2015?
