### ISSUE TITLE
Do not emit helper function declarations on compilation

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#3120]
Is it possible to prohibit TS to emit helper function declarations (e.g. _extend, _decorate) into every compiled file?

I have a setup, when we storm is compiling every TS file separately and I end up with many isolated helper function declarations. Thanks.

**Comment by danquirk** [comment]
See #1350

**Comment by mhegazy** [comment]
In next release 1.5.2, you can use `--noEmitHelpers` to suppress emitting all hetpers.

btw. it is already in master
