### ISSUE TITLE
Easier debugging with smarter transpiled imports

### ISSUE THREAD

**Issue by astoilkov** [Microsoft/TypeScript#31208]
## Search Terms

transpiled names, transpiled imports, debug is hard, easier debugging

I have the feeling this has been discussed in the history of TypeScript but I couldn't find it. I am very sorry if that is the case.

## Suggestion

The example speaks for itself:
```typescript
// TypeScript
import utils from './utils';
import { join, dirname } from 'path';

// Transpiled Version
const utils_1 = require("./utils");
const path_1 = require("path");

// My Suggestion and a better version
const utils = require("./utils");
const path_1 = require("path");
const join = path_1.join;
const dirname = path_1.dirname;
```

My suggestion won't work when there is a local variable called `utils`. In this case the implementation can fallback to the `utils_1` solution.

## Use Cases

This design substantially improves debugging in some cases. Let me explain:
- I am debugging in Chrome DevTools
- I have found that the bug I am trying to fix currently is caused by a wrong value returned by the `getComputedValue()`
- Seeing this method I have no idea if `utisl.getRawValue(param)` or `compute()` method has the wrong calculation
- In order to know which method I should step into I decide to evaluate `utils.getRawValue()` and see if this is the function which returns the wrong value
- 🧨Here the problem comes. Copying `utils.getRawValue(param)` and evaluating it in the console throws an error because `utils` is undefined.

```typescript
function getComputedValue(param: string) {
	const rawValue = utils.getRawValue(param)
	const computedValue = compute(rawValue)

	return computedValue
}
```

This can seem like an edge case but this literally happens to me every day. I am motivated to provide more examples of how important this seems – just say it.

The alternatives for debugging this function are:
- stepping once through the code and then twice to actually debug the correct function - drawback here is that it can be very hard to get into this case, it can take a lot of time
- stepping into both functions - this as well is time-consuming
- rewriting the code to `utils_1.getRawValue(param)` - this is also time-consuming because you should figure if it is `_1` or `_2` and you should do it multiple times if you are using multiple imports like `utils.getPrettyPath(join(path, name))`

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
See #29848 - writing imports that way would break ES6 behavior quite badly.

**Comment by astoilkov** [comment]
Thanks for the explanation @RyanCavanaugh!

Can you think of any way of improving the debugging experience in this case?
