### ISSUE TITLE
const number and strings make automatic literals

### ISSUE THREAD

**Issue by TheDSCPL** [Microsoft/TypeScript#31211]
## Search Terms

const string typescript literals

## Suggestion

I was defining constants to be used as Redux action types and was surprised to see that constant strings had type `string`!
My suggestion is that variables declared with the `const` keyword should have the most specific type possible, which is, in the case of strings and numbers, literals.

Please, either make constant strings and numbers be literals by default or provide a keyword or operator which can be used to force the string or number to have the literal type

## Use Cases

```ts
const helloWorldActionType =  '@@reducerName/helloWorld';
const goodbyeWorldActionType =  '@@reducerName/goobyeWorld';
interface IAction<T extends string,P> {
    type: T;
    payload: P;
}
function helloWorld(name: string): IAction<typeof helloWorldActionType, string> {
    return {
        type: helloWorldActionType,
        payload:  `Hello world! I'm ${name}.`
    }
}
function goobyeWorld(name: string): IAction<typeof goodbyeWorldActionType, number> {
    return {
        type: goodbyeWorldActionType,
        payload: name.length
    }
}
type Actions = ReturnType<typeof helloWorld | typeof goobyeWorld>;
const reducer: Reducer<ThisReducersStateType,Actions> = (state, action) => {
    switch(action.type) {
        case helloWorldActionType:
            // this case doesn't make 'action' be considered as of type 'IAction<typeof helloWorldActionType, string>' because 'helloWorldActionType' is of type 'string'
            const str: string = action.payload; // "action.payload" is still "string | number", which creates an error...
    // ...
}
```

This can be fixed with
```ts
const helloWorldActionType =  '@@reducerName/helloWorld' as '@@reducerName/helloWorld';
```
but it makes no sense... `helloWorldActionType` should be of type `'@@reducerName/helloWorld'` instead of `string` without the cast because it's a constant and can never change to another string other than that one.

This is annoying because I really don't want to have to type the string twice (not DRY), once in the value and again in the cast, every time I create a constant string.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code (every code which declares a constant string or number can't change the value later on so there is no problem in TypeScript now considering such variables as literals)
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by TheDSCPL** [comment]
I just found a trick for this but it creates useless clutter in the runtime...
```ts
function makeLiteral<L extends string>(s: L): L {
    return s;
}
```
and then do
```ts
const helloWorldActionType = makeLiteral('@@reducerName/helloWorld');
```

I'm going to use this for now but I really hope you guys can find a way to do this in a cleaner way!
Thank you in advance!

**Comment by nmain** [comment]
> I just found a trick for this but it creates useless clutter in the runtime...

There is a cleaner way to do this:

```
const helloWorldActionType = '@@reducerName/helloWorld' as const;
```

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions

**Comment by TheDSCPL** [comment]
Uhm ok! That's nice and way better. Thanks.
But don't you still think const strings and numbers should automatically be literals?

**Comment by nmain** [comment]
I think it is?  Not sure what TS version you're on, but in the current playground `const helloWorldActionType = '@@reducerName/helloWorld'` has type "@@reducerName/helloWorld".  Which makes my previous bit of advice pointless for this case.

**Comment by jcalz** [comment]
Yeah, [I can't reproduce this issue either](http://www.typescriptlang.org/play//#src=const%20helloWorldActionType%20%3D%20'%40%40reducerName%2FhelloWorld'%3B%0D%0Aconst%20goodbyeWorldActionType%20%3D%20'%40%40reducerName%2FgoobyeWorld'%3B%0D%0Ainterface%20IAction%3CT%20extends%20string%2C%20P%3E%20%7B%0D%0A%20%20type%3A%20T%3B%0D%0A%20%20payload%3A%20P%3B%0D%0A%7D%0D%0Afunction%20helloWorld(name%3A%20string)%3A%20IAction%3Ctypeof%20helloWorldActionType%2C%20string%3E%20%7B%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20type%3A%20helloWorldActionType%2C%0D%0A%20%20%20%20payload%3A%20%60Hello%20world!%20I'm%20%24%7Bname%7D.%60%0D%0A%20%20%7D%0D%0A%7D%0D%0Afunction%20goobyeWorld(name%3A%20string)%3A%20IAction%3Ctypeof%20goodbyeWorldActionType%2C%20number%3E%20%7B%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20type%3A%20goodbyeWorldActionType%2C%0D%0A%20%20%20%20payload%3A%20name.length%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20add%20some%20types%20to%20make%20this%20standalone%0D%0Atype%20Reducer%3CS%2C%20A%3E%20%3D%20(s%3A%20S%2C%20a%3A%20A)%20%3D%3E%20any%3B%0D%0Atype%20ThisReducersStateType%20%3D%20%22whocares%22%3B%0D%0A%0D%0Atype%20Actions%20%3D%20ReturnType%3Ctypeof%20helloWorld%20%7C%20typeof%20goobyeWorld%3E%3B%0D%0Aconst%20reducer%3A%20Reducer%3CThisReducersStateType%2C%20Actions%3E%20%3D%20(state%2C%20action)%20%3D%3E%20%7B%0D%0A%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20case%20helloWorldActionType%3A%0D%0A%20%20%20%20%20%20const%20str%3A%20string%20%3D%20action.payload%3B%20%2F%2F%20okay%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20case%20goodbyeWorldActionType%3A%0D%0A%20%20%20%20%20%20const%20num%3A%20number%20%3D%20action.payload%3B%20%2F%2F%20okay%0D%0A%20%20%20%20%2F%2F%20...%0D%0A%20%20%7D%0D%0A%7D). 

I do see that the "suggestion" issue template doesn't ask for TS version or a Playground link, but maybe it should?

**Comment by RyanCavanaugh** [comment]
> provide a keyword or operator 

`"string" as const`
