### ISSUE TITLE
TSServer logs are cluttered from plugin loading

### ISSUE THREAD

**Issue by uniqueiniquity** [Microsoft/TypeScript#31222]
**TypeScript Version:**  3.4.5

**Search Terms:**
plugin, stack, global plugin
**Scenario**
Start up TSServer with a global plugin and probe location specified

**Expected behavior:**
Server log shows the plugin being loaded.

**Actual behavior:**
Server log shows a large stack trace from trying to resolve the plugin from the location of tsserver, then shows it properly loading it from the probe location.

Why are we trying to load from the tsserver location first?
Do we really need the full stack, or would it be ok to just do the first line (which shows what files we tried to resolve)?
Do we even care about this cluttering up the log?

**Comment by uniqueiniquity** [comment]
CC @amcasey @sheetalkamat

**Comment by sheetalkamat** [comment]
Duplicate of #30106 ?

**Comment by uniqueiniquity** [comment]
My mistake. I'll close this one.
