### ISSUE TITLE
Out of memory on React dynamic tag

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#31227]
**TypeScript Version:**  3.5.0-dev.20190503

**Search Terms:** performance, Out of memory, 3.4

**Code**

```ts
interface CompProps {
  tag: keyof JSX.IntrinsicElements;
}

const MyComponent: React.FunctionComponent<CompProps> = ({
  tag = "div",
  children
}) => {
  const Wrapper = tag;

  return <Wrapper>{children}</Wrapper>;
};
```

**Expected behavior:**
Code type checks

**Actual behavior:**
on 3.3: OK
on 3.4, 3.5: JavaScript heap out of memory

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=interface%20CompProps%20%7B%0D%0A%20%20tag%3A%20keyof%20JSX.IntrinsicElements%3B%0D%0A%7D%0D%0A%0D%0Aconst%20MyComponent%3A%20React.FunctionComponent%3CCompProps%3E%20%3D%20(%7B%0D%0A%20%20tag%20%3D%20%22div%22%2C%0D%0A%20%20children%0D%0A%7D)%20%3D%3E%20%7B%0D%0A%20%20const%20Wrapper%20%3D%20tag%3B%0D%0A%0D%0A%20%20return%20%3CWrapper%3E%7Bchildren%7D%3C%2FWrapper%3E%3B%0D%0A%7D%3B)

**Related Issues:** #30663 (which was closed), maybe #30819 or #30973 (not sure if same root cause with either)

**Note:** Found while answering this [SO question](https://stackoverflow.com/questions/55969769/typing-a-dynamic-tag-in-react-with-typescript/55970164#55970164)

**Comment by dragomirtitian** [comment]
@rgfoley `keyof JSX.IntrinsicElements` is an unusually large union, there were several some issues 3.4 with unions and distributive conditional over them. Maybe you could also post the code that is causing issues for you ?

**Comment by rgfoley** [comment]
@dragomirtitian Any usage of `keyof JSX.IntrinsicElements` is enough to cause the issue. I don't get any problems when using `keyof HTMLElementTagNameMap`. This code seems to reproduce it (the TSC language server bit of my editor stops providing autocompletion and memory usage spikes after adding it):
```typescript
interface IProps {
  isOpen: boolean;
  tag?: keyof JSX.IntrinsicElements;
}

const foo: IProps = {
  isOpen: true,
  tag: 'span',
};
```

**Comment by dragomirtitian** [comment]
Seems to have been fixed in latest nightly builds.
