### ISSUE TITLE
One-liner arrow functions are indented incorrectly

### ISSUE THREAD

**Issue by aleclarson** [microsoft/TypeScript#31237]
Repro: https://github.com/aleclarson/repro/tree/tslint-1

When a one-liner arrow function has its parameters span multiple lines, the return value is incorrectly indented.

```tsx
export const Bar = ({
  foo,
  bar,
}: any) => (
    <div>Hello world</div>
  )
```

**Comment by mjbvz** [comment]
Moving to typescript since this is not tslint related

**Comment by aleclarson** [comment]
Note: It seems to override any code fixes applied by other TSLint rules. (eg: [tslint-plugin-prettier](https://github.com/prettier/tslint-plugin-prettier))
