### ISSUE TITLE
"module" and "esModuleInterop" options should have affectsEmit set to true

### ISSUE THREAD

**Issue by glen-84** [microsoft/TypeScript#31233]
**TypeScript Version:**  3.4.5

**Search Terms:** tsbuildinfo

**Code**

n/a

**Expected behavior:**

Changing the `module` or `esModuleInterop` options should invalidate the tsbuildinfo file, because it affects the emit.

**Actual behavior:**

Emitted files remain unchanged even though the option value has been modified.

**Playground Link:**

n/a

**Related Issues:**

https://github.com/Microsoft/TypeScript/issues/31118

**Comment by austincummings** [comment]
I'd like to take a look at this if that's ok?
