### ISSUE TITLE
Wrong checking return type from function

### ISSUE THREAD

**Issue by snatvb** [microsoft/TypeScript#31235]
```typescript
type A = {
  a: boolean;
}
type B = (v: A) => A

const c: B = (a) => {
  return { a: true, asd: 235 }
}
```

Why I don't have error?

But if I will write such code, then I get error:
```typescript
const f = (v: A): A => {
  return { a: true, asd: 235 }
}
```

**Comment by jack-williams** [comment]
Duplicate of #241/#29390/#30198. (The first issue might not look immediately related but its the root cause).

**Comment by snatvb** [comment]
@jack-williams how i understand, this problem will not be solved, becouse first post was in 2014, right?
