### ISSUE TITLE
downlevel regexp named capture groups

### ISSUE THREAD

**Issue by jaredh159** [Microsoft/TypeScript#31241]
## Search Terms

"named capture"
regexp named capture groups

## Suggestion

Regexp named capture groups have been added to the ECMA spec. It would be great if typescript could compile these down based on the desired target. Babel already has a plugin to do so: 

https://github.com/babel/proposals/issues/35
https://github.com/babel/babel/pull/9345
https://github.com/tc39/ecma262/pull/1027

## Use Cases

Writing next-level javascript regular expressions! 😎

And because it's a great feature for readable, maintainable code, and is in the spec. 

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jaredh159** [comment]
Argh, my bad. It looks like you already do this.  I had an error I thought was failure to downlevel these named capture groups, but I was wrong. Sorry! 😬

**Comment by cascornelissen** [comment]
@jaredh159, do you, by any chance, remember what issue caused this for you back then?

I'm working on a project which has `es2018` in the `compilerOptions.libs` array in `tsconfig.js` and `es5` as `compilerOptions.target` but the compiled files still contain named capture groups.

This is an example of the regex that shows this issue:

```js
/^(?<name>[A-Za-z]+)/
```

**Comment by jaredh159** [comment]
@cascornelissen I can't remember, honestly, sorry. I know I was used named capture groups and was getting an error in Safari I think, so I assumed they weren't being transpiled, but I jumped the gun and I had some mostly unrelated other problem that just happened to crop up at the same time that I started using named capture groups, IIRC.
