### ISSUE TITLE
Default props not working in functional component

### ISSUE THREAD

**Issue by Mcat12** [microsoft/TypeScript#31247]
**TypeScript Version:**  3.4.5

**Search Terms:**
react default props defaultProps functional component stateless

**Code**
```ts
import React from "react";

interface Props {
  name: string;
  optional: string;
}

const Component = ({ name, optional = "default" }: Props) => (
  <p>{name + " " + optional}</p>
);

const Test = () => <Component name="test" />;
```

**Expected behavior:**
According to the [TypeScript 3.0 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx), the `optional` prop should not be required in `Test` as it has been defined with a default using the ES2015 default initializers feature in `Component`.

**Actual behavior:**
The following compile error is thrown:
> Property 'optional' is missing in type '{ name: string; }' but required in type 'Props'.

**Playground Link:**
[Link](https://www.typescriptlang.org/play/#src=import%20React%20from%20%22react%22%3B%0D%0A%0D%0Ainterface%20Props%20%7B%0D%0A%20%20name%3A%20string%3B%0D%0A%20%20optional%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20Component%20%3D%20(%7B%20name%2C%20optional%20%3D%20%22default%22%20%7D%3A%20Props)%20%3D%3E%20(%0D%0A%20%20%3Cp%3E%7Bname%20%2B%20%22%20%22%20%2B%20optional%7D%3C%2Fp%3E%0D%0A)%3B%0D%0A%0D%0Aconst%20Test%20%3D%20()%20%3D%3E%20%3CComponent%20name%3D%22test%22%20%2F%3E%3B)
It doesn't look like the playground supports TSX.

**Related Issues:**
#27425

**Comment by ilogico** [comment]
The documentation may not be clear on this, but you have to mark the property as optional in your `Props` interface:
```typescript
interface Props {
    name: string;
    optional?: string;
}
```

**Comment by Mcat12** [comment]
That doesn't seem to match what the release notes say:
```tsx
export interface Props {
    name: string;
}

// ...

function Greet({ name = "world" }: Props) {
    return <div>Hello {name.toUpperCase()}!</div>;
}
```

**Comment by Mcat12** [comment]
Making the prop optional also means that when you access the props outside of the component (in a test), the type system does not guaranteed that the prop exists even though it will always exist.

Example:
```tsx
const wrapper = shallow(<Test/>);

// optional is string | undefined instead of string
const optional = wrapper
        .find(Component)
        .props()
        .optional;
```

If `optional` was a function, you would have to check it exists before you execute it. An example is if you provide a default `onClick` prop which just calls `preventDefault`.

**Comment by tbassetto** [comment]
With [TypeScript 3.1 or above](https://blogs.msdn.microsoft.com/typescript/announcing-typescript-3-1/#easier-properties-on-function-declarations) you should be able to write:
```typescript
export interface Props {
    name: string;
}

function Greet(props: Props) {
    return <div>Hello {props.name.toUpperCase()}!</div>;
}
Greet.defaultProps = {
  name: "world",
}

const component = <Greet />; // no errors
```

**Comment by Mcat12** [comment]
Is it a bug that using the default initializer feature does not work for default props? It seems like a regression given that the example given in the release notes does not work on the latest TypeScript version.

**Comment by G-Rath** [comment]
@tbassetto The problem with that is that TS doesn't force you to actually provide a default value:

```
import React from 'react';

interface Props {
  myProp: string;
}

const Comp = (props: Props) => {
  return (
    <div>
      {props.myProp.toUpperCase()}
    </div>
  );
};

Comp.defaultProps = {

} as Pick<Props, 'myProp'>;

const comp = <Comp />;
```

The other annoying thing is the fact that you have to do this in the first place: If I type `Comp` as `React.FC<Props>`, then `defaultProps` is typed nicely, but other problems arise.

All in all, TypeScripts JSX/React support right now seems to be in a weird not-quite-perfect" state, but running as if everything is fine (at least in my eyes - Mainly, I can't seem to find any solid notes on what currently is the "Official" way to do stateless React components in a type safe manner for 3.4.5).

**Comment by tomspeak** [comment]
Although I see everyone referencing work arounds, I am unable to get any of them to work.

I am on version 3.3.3

```
export interface Props {
  shouldTruncateContent: boolean;
}

const Alert: React.FunctionComponent<Props> = ({
  children,
  shouldTruncateContent = false
}) => {
  return (
        <S.Content shouldTruncateContent={shouldTruncateContent} size="fill">
          {children}
        </S.Content>
  );
};

Alert.defaultProps = {
  shouldTruncateContent: false
} as Pick<Props, 'shouldTruncateContent'>;

export default Alert;
```

Does anyone have any insight into why this still throws the error

`TS2741: Property 'shouldTruncateContent' is missing in type '{ children: string; }' but required in type 'Props'.`

I have tried all the fixes proposed in #27425 and #519 too.

**Comment by dragomirtitian** [comment]
@tomspeak Either [my workaround](https://github.com/microsoft/TypeScript/issues/27425#issuecomment-473848082) or @Hotell's [woraround](https://github.com/microsoft/TypeScript/issues/27425#issuecomment-440936580) (although this one makes all props optional). Tested on 3.5 with your sample code.

**Comment by jamesBennett** [comment]
> Although I see everyone referencing work arounds, I am unable to get any of them to work.
> 
> I am on version 3.3.3
> 
> ```tsx
> export interface Props {
>   shouldTruncateContent: boolean;
> }
> 
> const Alert: React.FunctionComponent<Props> = ({
>   children,
>   shouldTruncateContent = false
> }) => {
>   return (
>         <S.Content shouldTruncateContent={shouldTruncateContent} size="fill">
>           {children}
>         </S.Content>
>   );
> };
> 
> Alert.defaultProps = {
>   shouldTruncateContent: false
> } as Pick<Props, 'shouldTruncateContent'>;
> 
> export default Alert;
> ```
> 
> Does anyone have any insight into why this still throws the error
> 
> `TS2741: Property 'shouldTruncateContent' is missing in type '{ children: string; }' but required in type 'Props'.`
> 
> I have tried all the fixes proposed in #27425 and #519 too.

You just need to make shouldTruncateContent: boolean; optional `shouldTruncateContent?: boolean;`

**Comment by ralexhassle** [comment]
> The documentation may not be clear on this, but you have to mark the property as optional in your `Props` interface:
> 
> ```ts
> interface Props {
>     name: string;
>     optional?: string;
> }
> ```

I am using this optional type everywhere. Why the down vote ? Could someone explain ?

**Comment by ilogico** [comment]
@ralexhassle, I can't explain the down votes, but I can explain that is certainly a correct way of typing a component's optional property.
You might prefer using `defaultProps`, which the example of the question isn't using, but as far as I'm concerned, marking optional properties as optional is probably perfectly fine...

**Comment by Mcat12** [comment]
The purpose of the issue is that the props are not optional, but have a default value (therefore can be eluded when using the component). If you mark the prop optional with `?` then TS assumes it could be undefined and forces you to handle that case. However, it will never be undefined because there is a default value. The downvotes are because the commentator did not seem to understand the issue and proposed something that contradicted the 3.0 release notes.

**Comment by flo-sch** [comment]
@RyanCavanaugh why has the bot closed this issue?

Perhaps I missed it but I do not see an actual answer, despite lot of workarounds?

**Comment by lakhmeranikita** [comment]
You can do it in this way, here properties is optional in Props interface and further used in component.

`import React, { ReactNode } from 'react';
import { View, Text } from '@upstox/upstox-ui';

interface Props {
  children: ReactNode;
  properties?: Record<string, unknown>;
}

const defaultProps: Props = {
  children: '',
  properties: {
    marginTop: 32,
    marginLeft: 0,
    marginBottom: 8,
    marginRight: 0,
  },
};

const RadioListLabel: React.FC<Props> = ({
  children,
  properties = defaultProps.properties,
}) => (
  <View
    margin={[
        Number(properties ? properties.marginTop : 0) as Spacings,
        Number(properties ? properties.marginLeft : 0) as Spacings,
        Number(properties ? properties.marginBottom : 0) as Spacings,
        Number(properties ? properties.marginRight : 0) as Spacings,
      ]}
  >
    <Text size="m" variant="heading2" lineHeight="body">
      {children}
    </Text>
  </View>
  );

export default RadioListLabel;
`

**Comment by lakhmeranikita** [comment]
You can do it in this way, here properties in Props are the optional parameter and further used in the component.

```
interface Props {
  children: ReactNode;
  properties?: Record<string, unknown>;
}

const defaultProps: Props = {
  children: '',
  properties: {
    marginTop: 32,
    marginLeft: 0,
    marginBottom: 8,
    marginRight: 0,
  },
};

const RadioListLabel: React.FC<Props> = ({
  children,
  properties = defaultProps.properties,
}) => (
  <View
    margin={[
properties ? properties.marginTop : 0
        properties ? properties.marginLeft : 0
        properties ? properties.marginBottom : 0
        properties ? properties.marginRight : 0
      ]}
  >
    <Text size="m" variant="heading2" lineHeight="body">
      {children}
    </Text>
  </View>
  )
```

**Comment by Mcat12** [comment]
@lakhmeranikita The purpose of this issue is to avoid marking a prop type as optional.

**Comment by lakhmeranikita** [comment]
Yes but by doing `properties ? properties.marginTop : 0` we can easily handle undefined case in typescript. And I personally think it is very useful in default value cases

**Comment by harjis** [comment]
I was unable to get function default arguments or other proposals to type check properly. The only workable solution I was able to find is this:

```ts
import React from "react";

type DefaultProps = { optionalProp: number };
type Props = {
  requiredProp: "some_string" | "other_string";
} & DefaultProps;

export const BaseComponent = (props: Props) => {
  const { requiredProp, optionalProp } = props;
  return (
    <div>
      {requiredProp} {optionalProp}
    </div>
  );
};

BaseComponent.defaultProps = {
  optionalProp: 0,
} as Partial<DefaultProps>;

const comp = <BaseComponent requiredProp="some_string" />;

```

**Comment by the-kenneth** [comment]
Any reason why this was closed? Still an issue on 4.1

**Comment by lorenzopicoli** [comment]
@the-kenneth what was causing my issue was that I was typing my variable as React.FunctionalComponent.

```
export interface ButtonProps
  extends React.HtmlHTMLAttributes<HTMLButtonElement> {
  size: ButtonSize;
}

Button.defaultProps = {
  size: ButtonSize.full,
};

const Button: React.FunctionalComponent<ButtonProps> = (props: ButtonProps) => {
  return <StyledButton {...props} />;
};
```

```
<Button>bla</Button> => doesn't work. It says it's missing property "size"
```

Now if I declare button like this:
```
const Button = (props: ButtonProps) => {
  return <StyledButton {...props} />;
};
```
it works.

Source: https://github.com/microsoft/TypeScript/issues/27425#issuecomment-478004521

I still think it's a bug (people explain better in the issue above), but it might be something that works for you

**Comment by mo-alaa** [comment]
@AzureMarker two years later, have you found any fix ? because as you said, we should avoid marking a prop type as optional.

**Comment by AzureMarker** [comment]
@mo-alaa I'm not using TypeScript/React in my current projects. I think I just went with the defaultProps approach.
