### ISSUE TITLE
Callable interface is inconsistent with single-function interface

### ISSUE THREAD

**Issue by shivawu** [Microsoft/TypeScript#31250]
**TypeScript Version:**  3.4.5

**Search Terms:**
Callable Interface, Indexed Type

**Code**

```ts
interface IO {
  input: unknown;
  output: unknown;
}

interface StringIO extends IO {
  input: string;
  output: string;
}

interface Func<F extends IO> {
  // Changing this to an callable interface (removing the name f) would fail typecheck on createHandler
  f(input: F['input']): F['output'];
}

interface Handler<F extends IO> {
  createIO(): Func<F>;
}

class Handler1 implements Handler<StringIO> {
  public createIO(): Func<StringIO> {
    throw new Error('Method not implemented.');
  }
}

function createHandler<F extends IO>(): Handler<F> {
  return new Handler1();
}
```

**Expected behavior:**

Callable interface and interface with a single function should have consistent behavior?
That would be more intuitive.

**Actual behavior:**
Callable interface fail type check while interface with single function passes.

**Playground Link:** 

http://www.typescriptlang.org/play/#src=interface%20IO%20%7B%0D%0A%20%20input%3A%20unknown%3B%0D%0A%20%20output%3A%20unknown%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20StringIO%20extends%20IO%20%7B%0D%0A%20%20input%3A%20string%3B%0D%0A%20%20output%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Func%3CF%20extends%20IO%3E%20%7B%0D%0A%20%20%2F%2F%20Changing%20this%20to%20an%20callable%20interface%20would%20fail%20typecheck%20on%20createHandler%0D%0A%20%20(input%3A%20F%5B'input'%5D)%3A%20F%5B'output'%5D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Handler%3CF%20extends%20IO%3E%20%7B%0D%0A%20%20createIO()%3A%20Func%3CF%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Handler1%20implements%20Handler%3CStringIO%3E%20%7B%0D%0A%20%20public%20createIO()%3A%20Func%3CStringIO%3E%20%7B%0D%0A%20%20%20%20throw%20new%20Error('Method%20not%20implemented.')%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20createHandler%3CF%20extends%20IO%3E()%3A%20Handler%3CF%3E%20%7B%0D%0A%20%20return%20new%20Handler1()%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by jack-williams** [comment]
Think this is by design, as explained here: #18654.

Under `strictFunctionTypes`, functions declared using method syntax are bivariant; callable interfaces are contravariant.

If you want consistency for between callable interfaces and named functions then use function types rather than methods:
```ts
interface Func<F extends IO> { 
  f: (input: F['input']) => F['output'];
}
```
