### ISSUE TITLE
Incorrect inferring of return type 

### ISSUE THREAD

**Issue by cevek** [microsoft/TypeScript#31254]
Version:  3.4.5
```ts
declare function abc<T>(q: T | [{id: 'Id'}]): T 
var x = abc([{id: 'Id'}]).map(v => v.id /* 'Id' */) // string[] 

var y = abc([{id: 'Id'}]).map(v => v.id as 'Id') // 'Id'[]
```

**Comment by NN---** [comment]
Related: #30680

It is due to widening.
If you want to narrow type you have to specify explicitly as you did or use some tricks.

**Comment by jcalz** [comment]
effort level matching answer: don’t see a bug here, try SO

**Comment by weswigham** [comment]
![wot-types-why](https://user-images.githubusercontent.com/2932786/57411149-91b8ee00-71a1-11e9-81de-4a1b4881ff8c.gif)

There's definitely some strange stuff going on here for quickinfo. @ahejlsberg does this fall into the bucket of oddness caused by the improper caching you mentioned today?

**Comment by weswigham** [comment]
(but yes, normally I'd refer to #341 for explaining away a return type being wider than expected, but regardless the quickinfo for the signature return and variable type shouldn't disagree like that and is a real bug)

**Comment by cevek** [comment]
Something strange happens here
```ts

declare function abc<T>(q: T | {id: 'Id'}[]): T 
var u = abc([{id: 'Id'}]) // -> {id: 'Id'}[]
var k:{id: 'Id'}[] = u; // no problem
var l:typeof u = k; // no problem
var p = k.map(v => v.id); // -> 'Id'[]
var t = l.map(v => v.id); // -> string[]
```

**Comment by weswigham** [comment]
`k`'s literal type isn't "fresh" since it came from a type position instead of an expression, so isn't widened.
