### ISSUE TITLE
SystemJS semantics for commonjs libraries failing

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#3125]
# What works
Using momentjs as an example. Note the following *compiles* and *runs* fine if `module:commonjs`

```ts
import * as _ from 'lodash';
```
# Whats broken
With `module:system`, 

the following compiles fine *but fails at runtime*: 
```ts
import * as _ from 'lodash';
```
the following *fails to compile* but works at runtime: 
```ts
import _ from 'lodash';
```

/cc reported by @Mitranim [here](https://gitter.im/borisyankov/DefinitelyTyped?at=55519545f853e7f14c2b719c)

**Comment by danquirk** [comment]
a.ts:
```ts
/// <reference path='lodash.d.ts'/>

import * as _ from 'lodash';
var r = _.filter([1, 2, 3], (x => x == 1));
console.log(r);
```
```
F:\test> tsc -m commonjs a.ts
F:\test> node a.js
[ 1 ]

F:\test> tsc -m system a.ts
F:\test> node a.js
F:\test\a.js:2
System.register(['lodash'], function(exports_1) {
^
ReferenceError: System is not defined
    at Object.<anonymous> (F:\test\a.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by mhegazy** [comment]
We believe this should work. @vladima is looking more into it.

**Comment by vladima** [comment]
Seems to work ok using the latest es6 module loader / systemjs - just tried `import * as _ from 'lodash'` and it works like charm. Code can be found [here](https://gist.github.com/vladima/c3d4647b277e85e266ab).

**Comment by basarat** [comment]
Thanks for testing :rose:
