### ISSUE TITLE
Cannot assign value to variable of the same type

### ISSUE THREAD

**Issue by profencer** [microsoft/TypeScript#31259]
**TypeScript Version:**  3.5.0-dev.20190504

**Search Terms:** 
Two different types with this name exist, but they are unrelated.

**Code**
```ts
type Type<G extends boolean, T> = G extends true ? (input: number) => T : (input: T) => number
type U = <T>(x: <G extends boolean>() => Type<G, T>) => void;
const i: U = <T>(x: <G extends boolean>() => Type<G, T>) => {};
```

**Expected behavior:**
No error

**Actual behavior:**
Error 
```
Type '<T>(x: <G extends boolean>() => Type<G, T>) => void' is not assignable to type 'U'.
  Types of parameters 'x' and 'x' are incompatible.
    Type 'Type<G, T>' is not assignable to type 'Type<G, number>'.
      Type '(input: number) => T' is not assignable to type '(input: number) => number'.
        Type 'T' is not assignable to type 'number'.
```

**Playground Link:** 
[link](https://www.typescriptlang.org/play/#src=type%20Type%3CG%20extends%20boolean%2C%20T%3E%20%3D%20G%20extends%20true%20%3F%20(input%3A%20number)%20%3D%3E%20T%20%3A%20(input%3A%20T)%20%3D%3E%20number%0D%0Atype%20U%20%3D%20%3CT%3E(x%3A%20%3CG%20extends%20boolean%3E()%20%3D%3E%20Type%3CG%2C%20T%3E)%20%3D%3E%20void%3B%0D%0Aconst%20i%3A%20U%20%3D%20%3CT%3E(x%3A%20%3CG%20extends%20boolean%3E()%20%3D%3E%20Type%3CG%2C%20T%3E)%20%3D%3E%20%7B%7D%3B)

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/26627
https://github.com/Microsoft/TypeScript/issues/25373

**Comment by jack-williams** [comment]
This is fixed: [playground](https://www.typescriptlang.org/play/#code/C4TwDgpgBAKuEB4DiUIA9gQHYBMDOUARgPbEA2EAhlgDSwB8UAvFCuprgcAE4Cu0AfigAKAJZYwvYAC4oWXgFtCEbgEpmjGFFliJU2THVNG8pSoBQoSFACqzKAhj1haWclQZs+IqQrVnRprwyHROgVAAbsSiOADc5gDGxFh4wFCisnYsjs6uDmyenD7kVFgBGrDBSKH04QDeAL6xQA)

**Comment by weswigham** [comment]
So it is.
