### ISSUE TITLE
support symbol and Exclude key type

### ISSUE THREAD

**Issue by LongTengDao** [Microsoft/TypeScript#31263]
## Search Terms

symbol key

## Suggestion

```ts
interface {
    [key :symbol] :object
}
```

```ts
interface {
    [key :Exclude<string, '_'>] :object
}
```

## Use Cases

```ts
const dict = {
    _ :Function
    [key :Exclude<string, '_'>] :object
    [key :symbol] :object
} = {
    _ () { }
};

dict.abc = {};

dict[Symbol()] = {};
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment]
Looks like this one should be covered by #26797
