### ISSUE TITLE
[Feature request] support `from 'module' import xxx`

### ISSUE THREAD

**Issue by NewFuture** [Microsoft/TypeScript#31260]
## Suggestion
support `from 'module' import xxx`

As the [ES6 `import` Statements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), the module is always at the end of the statements like this:
```ts
import {xxx} from 'module';
```
If we can declare the module name at first, it will be better for typing and IntelliSense.
Just like this:
```python
from 'module' import {xxx};
```
After compile，the results are the same.
Could we support it like this in TypeScript?

## Examples

before(TypeScript)
```python
from 'module' import {xxx};
```
after(JavaScript)
```ts
import {xxx} from 'module';
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by danvk** [comment]
@NewFuture The TS team generally doesn't implement syntax that isn't standard ECMAScript.

Autocomplete of imports is really nice, though. I usually wind up writing:

```ts
import {} from 'module';
```

and then go back inside the `{}` to get autocomplete.

**Comment by NewFuture** [comment]
@danvk  yes,  but
> TypeScript is a superset of JavaScript.

The second syntax will be much better for coding, just keep going forward with autocompletion.

I prefer ECMAScript to implement it😄 
```ts
import React,{Component} from 'react';
// go back
// then go next line
```
```ts
from 'react' import React,{Component};
// continue
```

**Comment by lll000111** [comment]
My IDE (WebStorm) has templates that can be used to insert the whole import statement line all at once, but then place the cursor immediately inside the {} Examples (not mine, just found the link to be able to post an example): https://medium.com/@drapegnik/useful-javascript-react-live-templates-for-webstorm-8a6c70aee207

**Comment by kitsonk** [comment]
Duplicate of #3127, #2370, #2371 (and possibly others)

This has been discussed and closed MANY times before.

**Comment by NewFuture** [comment]
thanks @kitsonk
