### ISSUE TITLE
wrong type inference in Promise

### ISSUE THREAD

**Issue by dislido** [microsoft/TypeScript#31266]
**TypeScript Version:**  3.4.3

**Search Terms:**

**Code**

```ts
let foo: string | undefined;
if (!foo) foo = 'hello';

foo.length; // ok

new Promise(resolve => resolve(foo.length));
//                              ^ should be string, but inferred as string | undefined
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by GongT** [comment]
No, that is not ok: foo.length -> [Object is possibly 'undefined']

**Comment by lll000111** [comment]
@GongT You mean the 3rd line? There is no error in the playground, with all optional checks enabled.

**Comment by j-oliveras** [comment]
Most likely, related to #9998.

**Comment by weswigham** [comment]
Yep, see #9998 - we cutoff control flow analysis on function boundaries (mostly), so `foo` only has it's declared type within the Promise callback. If you capture the narrowed value with a `const` before the callback is made, that'll capture the narrowed value.

**Comment by GongT** [comment]
![image](https://user-images.githubusercontent.com/2265048/57427252-b1115300-7255-11e9-9068-05813b055da3.png)
@lll000111

**Comment by fatcerberus** [comment]
> we cutoff control flow analysis on function boundaries (mostly)

Which makes perfect sense, because in general the compiler can't know when a function will be called--or even how many times.  In the specific case of `Promise` we know the function will be called only once, and immediately--but this isn't an assumption the compiler can make in the general case.

**Comment by dislido** [comment]
```typescript
let foo: string | undefined;
if (!foo) foo = 'hello';

new Promise(resolve => resolve(foo!.length));
```
ok,It seems that it is the correct solution
