### ISSUE TITLE
Add support for @inheritdoc

### ISSUE THREAD

**Issue by KnightYoshi** [microsoft/TypeScript#31267]
I have a base class that defines the @param types, names, and descriptions. I extend the base class that overrides one of the methods of the base class. However, when using `@inheritdoc` ESLint doesn't provide any information of the object from the parameter that I'm referencing.

_foo.js_
```
class Foo {
    
    /**
     * 
     * @param {Entity} entity -
     * @param {string} attribute -
     */
    something(entity, attribute) {
         // do stuff with the arguments, 
    }
}
```

_bar.js_
```
class Bar extends Foo {
    
    /**
     * 
     * @inheritdoc
     */
    something(entity, attribute) {
         // do other stuff with the arguments, 
    }
}
```

I would expect auto-complete and hints for the `Entity` type in `Bar#something` since it's defined in `Foo#something`. However, unless I copy the same comment block into _bar.js_ I don't get any hinting for the `entity` param type like I do in `Foo#something`

**Comment by Kingwl** [comment]
I'd like to start work on this

**Comment by hahanein** [comment]
It is common in React to group logical components as a single component.
A straight-forward way to accomplish this using TypeScript is the following:

```tsx
/** Groups {@link Item} components. */
const Group: FC<PropsWithChildren> = props => <div>{children}</div>;
/** An item of the {@link Group} component. */
const Item: FC<PropsWithChildren> = props => <div>{children}</div>;

export default Object.assign(Group, {Item});
```

However, this pattern swallows the documentation. With `@inheritDoc`, as [described in TSDoc](https://tsdoc.org/pages/tags/inheritdoc/), you could do the following:

```tsx
/** Groups {@link Item} components. */
const Group: FC<PropsWithChildren> = props => <div>{children}</div>;
/** An item of the {@link Group} component. */
const Item: FC<PropsWithChildren> = props => <div>{children}</div>;

/** {@inheritDoc Goup} */
export default Object.assign(Group, {
  /** {@inheritDoc Item} */
  Item
});
```

Without it, there is no work-around except for copy-pasting the documentation.

**Comment by Josmithr** [comment]
I would love to see some action on this. My team regularly has to make the tradeoff between proper generated docs (using api-extractor via `{@inheritdoc Foo}` or having usable intellisense in VSCode.

**Comment by HarelM** [comment]
Should this issue be opened for vscode or here?
I found the following "workarounds" to my problem:
1. Don't add any comments, so vscode will show the inherited comments - this is problematic since reading a method does not indicate that this method is basically an implementation of an interface.
2. use `/** @inheritdoc */` - this works for typedoc and for vscode, but it's not according to the tsdocs standard.

When adding `/** {@inheritDoc IControl.onAdd} */` vscode shows:
![image](https://github.com/microsoft/TypeScript/assets/3269297/3cb0c42c-1a92-4167-8a6e-90ee498844b5)

Which is not what I would expect.
Please let me know where is the right place to report this issue.

**Comment by markcellus** [comment]
> Should this issue be opened for vscode or here?

TypeScript should evaluate `@inheritdoc` in it's type-checking, which it doesn't appear to do. The `@inheritdoc` [documentation](https://jsdoc.app/tags-inheritdoc) states the use of `@inheritdoc` "implies the presence of the [`@override` tag](https://jsdoc.app/tags-override)". So, if I were to use `@inheritdoc`, then remove the method from the class on it extends, TypeScript should raise an error, which is doesn't do AFAICT. So I think this is the right repository to file this issue.

**Comment by markcellus** [comment]
Also, JSDoc doesn't support explicit inheritance from a specific symbol (e.g. `@inheritdoc Foo#bar`), but there's already [an issue](https://github.com/jsdoc/jsdoc/issues/846) to support it. So perhaps another issue should be opened on this repository for TypeScript to evaluate whatever syntax is decided on from that issue (`Foo#bar` vs `Foo.bar` vs `Foo['bar']`).

**Comment by rwalle** [comment]
@KnightYoshi why completed? Any linked pull request?

**Comment by KnightYoshi** [comment]
> @KnightYoshi why completed? Any linked pull request?

It's been 5 years with no progress. So I closed the issue, but it's not been done. I recently closed a number of outstanding issues I've had open for several years.
