### ISSUE TITLE
Declare that a function parameter is a type guard

### ISSUE THREAD

**Issue by danvk** [Microsoft/TypeScript#31261]
## Search Terms

- type guard parameter

Possibly related to #30542 though I couldn't get the conditional type there to work in my example.

## Suggestion

I'd like to be able to declare that a function parameter should be a type guard, e.g.:

```ts
function checkFoo<T>(x: any, isT: (x: any): x is T) { ... }
```

## Use Cases

I have an array with type `(A|B)[]` and would like to split it into two arrays of types `A[]` and `B[]`. It would be great if I could write a function like:

```ts
const isA = (x: any): x is A => 'a' in x;
const [as, bs] = partitionByType(abs, isA);
```

and have TypeScript check that the `isA` parameter is a type guard. Presumably passing an arrow function that TypeScript understands to refine the type (like `ab.tag === 'a'`) would also work.

## Examples

This came up in a code review and I was curious if it could be implemented in TS. I couldn't figure out how.
https://github.com/danvk/source-map-explorer/pull/115/commits/f0be25926dfa1aea56b3ee111583ba20cf7befa2#diff-45ec1a2ac33cf965ab5afde0254bd928R107

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
Is this what you mean?
```ts
function partition<T, U>(x: (T | U)[], isT: (x: any) => x is T, isU: (x: any) => x is U) { 
    const t = x.filter(isT);
    const u = x.filter(isU);
    return [t, u] as const;
}

function isNumber(x: any): x is number {
    return typeof x === "number";
}

function isBoolean(x: any): x is boolean {
    return typeof x === "boolean";
}

const [l, r] = partition([1, 2, true, false, 4], isNumber, isBoolean);
```

**Comment by jcalz** [comment]
Or this, if your single type guard has no false negatives?

```ts
type A = { a: string }
type B = { b: string }
declare const abs: (A | B)[];

function partitionByType<T, U extends T>(
  arr: T[], 
  guard: (x: T) => x is U
): [U[], Exclude<T, U>[]] {
  const ret: [U[], Exclude<T, U>[]] = [[], []];
  arr.forEach(el => guard(el) ? ret[0].push(el) : ret[1].push(el as Exclude<T, U>));
  return ret;
}

const [as, bs] = partitionByType(abs, (x: A | B): x is A => 'a' in x);
```

**Comment by danvk** [comment]
@jack-williams that is exactly what I mean! I had `:` when I should have had `=>`.

I really like @jcalz's implementation with `Exclude` since it's able to take only one type guard and infer the other type from it.

My version was:

```ts
function partitionByType<A, B>(xs: (A|B)[], isA: (x: any) => x is A): [A[], B[]] {
    const as: A[] = [];
    const bs: B[] = [];
    for (const x of xs) {
        if (isA(x)) {
            as.push(x);
        } else {
            bs.push(x);  // x's type narrowed to B
        }
    }
    return [as, bs];
}
```

But in @jcalz's example, the return type here is inferred as `[A[], {}[]]` whereas with his version it's inferred as `[A[], B[]]`.

I'm closing this since everything seems to be working perfectly!
