### ISSUE TITLE
Post-"if" statement code doesn't remove type nullability when using class templates

### ISSUE THREAD

**Issue by dko-slapdash** [microsoft/TypeScript#31274]
Despite `if (!val) return` line, in the below code `val` is still treated as nullable. This happens only when templates are involved.

**TypeScript Version:**
3.4.0-dev.201xxxxx

**Search Terms:**
typescript class template null

**Code**

```ts
function tst(s: string) { }

class Cls<TField extends string> {
  constructor(private field: TField) { }

  fff(rec: Record<TField, string | null>) {
    const val = rec[this.field]; // Record<TField, string | null>[TField]
    if (!val) {
      return;
    }
    tst(val); 
    // ^ Type 'null' is not assignable to type 'string'.
    // why? we had an if statement above
  }
}
```

**Expected behavior:**
It should compile, since val is checked to be non-null.

And it DOES compile if instead of `TField` template we e.g. use just `string`. 

**Actual behavior:**
Type 'null' is not assignable to type 'string'.

**Playground Link:**
[playground link](https://www.typescriptlang.org/play/index.html#src=function%20tst(s%3A%20string)%20%7B%20%7D%0D%0A%0D%0Aclass%20Cls%3CTField%20extends%20string%3E%20%7B%0D%0A%20%20constructor(private%20field%3A%20TField)%20%7B%20%7D%0D%0A%0D%0A%20%20fff(rec%3A%20Record%3CTField%2C%20string%20%7C%20null%3E)%20%7B%0D%0A%20%20%20%20const%20val%20%3D%20rec%5Bthis.field%5D%3B%20%2F%2F%20Record%3CTField%2C%20string%20%7C%20null%3E%5BTField%5D%0D%0A%20%20%20%20if%20(!val)%20%7B%0D%0A%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20tst(val)%3B%20%0D%0A%20%20%20%20%2F%2F%20%5E%20Type%20'null'%20ais%20not%20assignable%20to%20type%20'string'.%0D%0A%20%20%20%20%2F%2F%20why%3F%20%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/31245

**Comment by AnyhowStep** [comment]
I've had this problem multiple times and I think my workaround is just,

```ts
val2 = val as Exclude<typeof val, null>;
tst(val2);
```

**Comment by weswigham** [comment]
We have a postfix `!` cast operator that filters null and undefined - you don't need to write a huge null excluding cast yourself, FYI.

**Comment by dko-slapdash** [comment]
The intent was to signal about TS behavior which looks suspiciously. If TS complains that `val` can be null after the explicit check like:
```ts
if (!val) return;
tst(val); // <-- this is where it complains that val is nullable
```
, something is likely not working correctly?

For other examples (not related to `Record<TField, string | null>` and/or to indexing the object via `this.field`), TS correctly infers that `val` is non-nullable after the `if` check.

**Comment by RyanCavanaugh** [comment]
Generic indexed access types can't be narrowed at the moment; there are other issues tracking this.
