### ISSUE TITLE
.d.ts generation error behaviour

### ISSUE THREAD

**Issue by shrinktofit** [microsoft/TypeScript#31280]
**TypeScript Version:**  3.4.2

**Search Terms:**
.d.ts; import path

Suppose I have following project structure:

![image](https://user-images.githubusercontent.com/28807867/57271066-95287880-70c0-11e9-8c0b-a830e42b4488.png)

The codes are emplaced at https://github.com/shrinktofit/ts-issue .

The generated .d.ts will be:

```
declare module "nested/shared" {
    export class B {
    }
}
declare module "nested/base" {
    import { B } from "nested/shared";
    export function f(): B;
}
declare module "nested/derived" {
    export function g(): import("nested").B; // LINE 10
}
declare module "nested/index" {
    export * from "nested/base";
    export * from "nested/derived";
    export * from "nested/shared";
}
declare module "index" {
    export * from "nested/index";
}
```

In line 10, the `import("nested").B` is an error with message `nested is not a module`; If I change it to `import("nested/index").B`, it's fine,

**Comment by shrinktofit** [comment]
If I do not export `nested/shared` in module `nested/index`, generated code becomes:
```
declare module "nested/derived" {
    export function g(): import("nested/shared").B;
}
```
and the error disappear.

**Comment by orta** [comment]
Looking like `getSpecifierForModuleSymbol` in checker isn't taking into account the context where an import needs to instead match the result of `getExternalModuleNameFromPath` when linking inside a bundled DTS.

**Comment by orta** [comment]
Looks like the issue is more at the declaration transformer layer, there's a pass through the AST which converts the module identifiers. In this case the return types of  `g` is inferred, which means as the declaration transformer is checking the `case SyntaxKind.ImportType` it probably hasn't been inferred yet and so the transformation hasn't been applied.

> Need to call the existing visitor on the existing node in `ensureType`
