### ISSUE TITLE
Unable to append a type to an existing tuple

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#31286]
**TypeScript Version:**  3.2.4

**Search Terms:**
Tuple, merge, combine

**Code**

```ts
function combine<T, U extends any[]>(item: T, items: U): [T, ...U] {
    return [] as any;
}
const result = combine("hello", ["goodbye", 123, true]);
```

**Expected behavior:**
result should be typed as `[string, string, number, boolean]`.

**Actual behavior:**
Compile error: 
A rest element type must be an array type.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=function%20combine%3CT%2C%20U%20extends%20any%5B%5D%3E(item%3A%20T%2C%20items%3A%20U)%3A%20%5BT%2C%20...U%5D%20%7B%0D%0A%20%20%20%20return%20%5B%5D%20as%20any%3B%0D%0A%7D%0D%0A%0D%0Aconst%20result%20%3D%20combine(%22hello%22%2C%20%5B%22goodbye%22%2C%20123%2C%20true%5D)%3B%0D%0A)

**Related Issues:**

**Comment by lll000111** [comment]
Your playground link links to an empty Playground.

**Comment by lll000111** [comment]
You attempt spreading the *type*,, that does not work.

[This works.](https://www.typescriptlang.org/play/#src=const%20a%20%3D%201%3B%0D%0A%0D%0Afunction%20combine%3CT%2C%20U%20extends%20any%5B%5D%3E(item%3A%20T%2C%20items%3A%20U)%3A%20%5BT%2C%20U%5D%20%7B%0D%0A%20%20%20%20return%20%5B%5D%20as%20any%3B%0D%0A%7D%0D%0A%0D%0Aconst%20result%20%3D%20combine(%22hello%22%2C%20%5B%22goodbye%22%2C%20123%2C%20true%5D)%3B%0D%0A)

**Comment by Roaders** [comment]
sorry about that, link in original post fixed.

**Comment by jcalz** [comment]
Duplicates #5453 and fixed in TS3.0 by #24897 via [tuples in rest/spread positions](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#tuples-in-rest-parameters-and-spread-expressions):

```ts
type Cons<H, T extends any[]> = ((h: H, ...t: T) => void) extends ((
  ...r: infer R
) => void)
  ? R
  : never;

function combine<T, U extends any[] | [any]>(item: T, items: U): Cons<T, U> {
  const ret = items.slice() as Cons<T, U>;
  ret.unshift(item);
  return ret;
}
const result = combine("hello", ["goodbye", 123, true]);
// const result: [string, string, number, boolean]
```

**Comment by Roaders** [comment]
That's an ...interesting way of fixing this!

[Updated link](https://www.typescriptlang.org/play/#src=%0D%0Atype%20Cons%3CH%2C%20T%20extends%20any%5B%5D%3E%20%3D%20((h%3A%20H%2C%20...t%3A%20T)%20%3D%3E%20void)%20extends%20((...r%3A%20infer%20R)%20%3D%3E%20void)%20%3F%20R%20%3A%20never%3B%0D%0A%0D%0A%0D%0Afunction%20combine%3CT%2C%20U%20extends%20any%5B%5D%20%7C%20%5Bany%5D%3E(item%3A%20T%2C%20items%3A%20U)%3A%20Cons%3CT%2C%20U%3E%20%7B%0D%0A%20%20%20%20return%20%5B%5D%20as%20any%3B%0D%0A%7D%0D%0A%0D%0Aconst%20result%20%3D%20combine(%22hello%22%2C%20%5B%22goodbye%22%2C%20123%2C%20true%5D)%3B%0D%0A)

This is a hack though right? It's a very roundabout way of fixing the issue IMHO.

Very appreciative of the solution though :-)

**Comment by jcalz** [comment]
It's a hack in that it's roundabout, but that's probably a separate issue #26113.  But this definition of `Cons` uses all supported and documented language features, so it's not a hack in the sense that "it just happens to work".
