### ISSUE TITLE
Generate declarations for classes and imports as function

### ISSUE THREAD

**Issue by pofuk** [Microsoft/TypeScript#3128]
Hi! 
I was playing around with typescript and did't like that i have to put paths to references in order to specify order of files in single output file. My suggestion is that at beggining of single output file, compiler generates declaration for all classes i.e.:

```javascript
var com = function(){};
com.module = function(){};
com.module.view = function(){};
com.module.view.controllers = function(){};
com.module.view.controllers.ExampleComponentController = function(){};
```
And after that are all definitions of modules and classes (normal compiler output)

Now when i import other module:
```javascript
import ExampleComponentController = com.wuerth.view.controllers.ExampleComponentController;
```

it is rendered as:
```javascript
var ExampleComponentController = com.wuerth.view.controllers.ExampleComponentController;
```

I would suggest that is rendered as:
```javascript
var ExampleComponentController = function {
    return com.wuerth.view.controllers.ExampleComponentController
}
```

With this modifications it would not be necessary to specify orders of modules and remove 
```
/// <reference path='../../../../somefile.js' />
```

I can dom implementation of this I just need comments so I don't waste time if  idea is not good.

**Comment by danquirk** [comment]
We generally do not want to try to detect ordering issues or reorder code in surprising ways like this. You can use tsconfig.json, _references.ts, or /// references to order your project files in the way you require. If you like the organization where all your class definitions are in a single place then you should write your TS code in that style. If you prefer definitions closer to their usage (or some other pattern) then you can do that and we will respect that in the output.

**Comment by pofuk** [comment]
But as I see it if i have situation

File /com/a/A.ts
/// <reference path='../b/B.ts' />
module com.a {
   import B = com.b.B;
    
    export class A {
        constructor() {
            console.log(B);
        }
    }
}


File /com/b/B.ts
```javascript
/// <reference path='../a/A.ts' />
module com.b {
   import A = com.a.A;
    
    export class B {
        constructor() {
            console.log(A);
        }
    }
}
```


OUTPUT IS: 
```javascript
var com;
(function (com) {
    var a;
    (function (a) {
        var B = com.b.B;
        var A = (function () {
            function A() {
                console.log(B);
            }
            return A;
        })();
        a.A = A;
    })(a = com.a || (com.a = {}));
})(com || (com = {}));
var com;
(function (com) {
    var b;
    (function (b) {
        var A = com.a.A;
        var B = (function () {
            function B() {
                console.log(A);
            }
            return B;
        })();
        b.B = B;
    })(b = com.b || (com.b = {}));
})(com || (com = {}));
//# sourceMappingURL=compiled.js.map
```
There is error "Uncaught TypeError: Cannot read property 'B' of undefined"

If I only modify output to make 
```javascript
var B = com.b.B;
```
BE: 
```javascript
var B = function() {
        	com.b.B;
        }
```

Than it works.

**Comment by pofuk** [comment]
And I suppose only thing that has to be changed is compiler/emmiter.ts function emitImportEqualsDeclaration  with something like this (didn't test, writing it out of my head, workd on TS1.4 thought): 

``` javascript
    if (isES6ExportedDeclaration(node)) {
        write("export ");
        write("var ");
	emitModuleMemberName(node);
	write(" = ");
	emit(node.moduleReference);
	write(";");
    }
    else if (!(node.flags & NodeFlags.Export)) {
        write("var ");
        emitModuleMemberName(node);
        Write(" = ");
            emit(node.moduleReference);
        write(";");
        emitToken(81 /* FunctionKeyword */, node.pos);
        emitToken(13 /* OpenBraceToken */, node.pos)
        writer.writeLine();
        writer.increaseIndent();
        emitToken(88 /* ReturnKeyword */, node.pos);
        writer.write(" ");
        emit(node.moduleReference);
        writer.writeLine();
        writer.decreaseIndent();
        emitToken(14 /* CloseBraceToken */, node.pos);
    }
    emitEnd(node);
    emitExportImportAssignments(node);
    emitTrailingComments(node);

```
