### ISSUE TITLE
bug: Symbol.valueDeclaration is undefined for "Class.prototype" PropertyAccessExpression

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#31294]
**TypeScript Version:**  3.4.5.

**Search Terms:**
valueDeclaration symbol prototype constructor

**Code**

File to parse:
```ts
class CommunicationError {
	constructor() {
		const x = CommunicationError.prototype;
	}
}
```
(Note, also fails in the same way on this code)
```ts
class CommunicationError {}
const x = CommunicationError.prototype;
```

Code to get types:
```ts
const originalNode = PropertyAccessExpression; // traverse the parsed AST to get to the PropertyAccessExpression node on line 3
const checker = program.getTypeChecker();
const symbol = checker.getSymbolAtLocation(originalNode);
const kind = symbol.valueDeclaration; // typeof === undefined
```

**Expected behavior:**
As per the types for `Symbol`: https://github.com/microsoft/TypeScript/blob/master/lib/typescript.d.ts#L2144-L2152
```ts
    interface Symbol {
        flags: SymbolFlags;
        escapedName: __String;
        declarations: Declaration[];
        valueDeclaration: Declaration;
        members?: SymbolTable;
        exports?: SymbolTable;
        globalExports?: SymbolTable;
    }
```

`valueDeclaration` shouldn't ever be undefined.

**Actual behavior:**

`valueDeclaration` isn't even defined on the symbol object:
![image](https://user-images.githubusercontent.com/7462525/57315387-4c64c580-70a8-11e9-925d-8e349afb725b.png)

**Related Issues:** 
First reported by one of our users here: https://github.com/typescript-eslint/typescript-eslint/issues/496

**Comment by ajafff** [comment]
Duplicate of #24706

**Comment by bradzacher** [comment]
Ah, I searched for `valueDeclaration` and saw that issue but didn't open it, because I thought it was a bug instead of incorrect types.

Closing in favour of #24706 then
