### ISSUE TITLE
Wrong type "never" inferred for ParentNode.childNode when using --strictNullChecks (lib.dom.d.ts)

### ISSUE THREAD

**Issue by Zamralik** [microsoft/TypeScript#31293]
**Code**

```ts
const parent_node: HTMLDivElement = document.createElement("div");
const child_node: HTMLDivElement = document.createElement("div");

while (parent_node.firstChild !== null)
{
	parent_node.firstChild.remove();
}

parent_node.appendChild(child_node);

while (parent_node.firstChild !== null)
{
	parent_node.firstChild.remove(); // here
}
```

The issue occurs when the `strictNullChecks` option is enabled.

**Expected behavior:**
`tsc --strictNullChecks demo.ts`
Successful compilation.

**Actual behavior:**
`tsc --strictNullChecks demo.ts`
`error TS2339: Property 'remove' does not exists on type 'never'.`

**Playground Link:**
Toggle the `strictNullChecks` option.
https://www.typescriptlang.org/play/#src=const%20parent_node%3A%20HTMLDivElement%20%3D%20document.createElement(%22div%22)%3B%0D%0Aconst%20child_node%3A%20HTMLDivElement%20%3D%20document.createElement(%22div%22)%3B%0D%0A%0D%0Awhile%20(parent_node.firstChild%20!%3D%3D%20null)%0D%0A%7B%0D%0A%09parent_node.firstChild.remove()%3B%0D%0A%7D%0D%0A%0D%0Aparent_node.appendChild(child_node)%3B%0D%0A%0D%0Awhile%20(parent_node.firstChild%20!%3D%3D%20null)%0D%0A%7B%0D%0A%09parent_node.firstChild.remove()%3B%20%2F%2F%20here%0D%0A%7D%0D%0A

**Comment by nmain** [comment]
This is just https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-235963457

tsc doesn't understand that `Node.firstChild` is a getter whose returned value can change as a side effect of other options, so it keeps the narrowing on it.

**Comment by Zamralik** [comment]
I failed to find that issue, good catch.

It's still a bug because, even understood as a property, the call to any method could impact the value of the property internally.

Would be nice if we could tell TSC that calling method X can alter the value of the property Y.

**Comment by fatcerberus** [comment]
> It's still a bug because, even understood as a property, the call to any method could impact the value of the property internally.

This exact point was discussed in the OP of #9998.  It was concluded that neither being fully pessimistic (any function call can have *all possible side effects*) nor fully optimistic (functions have *no* side effects) were perfect, but optimism was the best compromise given the current limitations.  The control-flow analyzer isn't *quite* sophisticated enough to dig into function calls to see what they really do--and you probably wouldn't want it to anyway; compile times would likely go through the ceiling*.

* Then again, maybe that wouldn't be such a bad thing - https://xkcd.com/303/
