### ISSUE TITLE
Cannot call object method of class that explicitely extends Object

### ISSUE THREAD

**Issue by jmstark** [microsoft/TypeScript#31308]
**TypeScript Version**: 3.5.0-dev.20190508

**Search Terms:** TypeScript explicitely extend Object "not a function"

**Code**

```ts
class Example extends Object {
    constructor() {
        super();
    }
    public getHello() : string {
        return "Hello";
    }
}

let greeter = new Example();
console.debug(greeter.getHello());
```

**Expected behavior:**
Output "Hello" without errors.

**Actual behavior:**

```
console.debug(greeter.getHello());
                      ^
TypeError: greeter.getHello is not a function
at Object.<anonymous> (C:\Users\user\example.js:25:23)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=class%20Example%20extends%20Object%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20public%20getHello()%20%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%22Hello%22%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20greeter%20%3D%20new%20Example()%3B%0D%0Aconsole.debug(greeter.getHello())%3B

**Stackoverflow:**
https://stackoverflow.com/questions/56022190/why-is-it-not-possible-to-call-method-if-a-class-explicitely-extends-object

**Comment by j-oliveras** [comment]
This is working as intended.

See FAQs: [Why doesn't extending built-ins like Error, Array, and Map work?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work).

**Comment by jmstark** [comment]
Thank you, did not see that. Closing.
