### ISSUE TITLE
Autocomplete for string literal values fails when typing "/"

### ISSUE THREAD

**Issue by gr2m** [microsoft/TypeScript#31304]
**TypeScript Version:**  typescript@3.5.0-dev.20190507

**Search Terms:** [is:issue is:open slash in:title ](https://github.com/microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+slash+in%3Atitle), [autocomplete in:title ](https://github.com/microsoft/TypeScript/issues?q=autocomplete+in%3Atitle&utf8=%E2%9C%93), [is:open label:"Domain: Completion Lists"](https://github.com/microsoft/TypeScript/labels/Domain:%20Completion%20Lists?q=is%3Aopen+label%3A%22Domain%3A+Completion+Lists%22)

**Code**

```ts
type Options = "one/two/three" | "two/three/one" | "three/one/two" 

function test(option: Options) {}

test("")
```

**Expected behavior:**

The suggested options for `test()` should update as I type the string. It should not be interrupted when I type `"/"` and it should not match all options when I type "one/" and press control space to trigger the auto complete

**Actual behavior:**

When I start typing "one" it will correctly list the three possible options

![image](https://user-images.githubusercontent.com/39992/57335199-b6945f00-70d6-11e9-8cb5-2258e478eb66.png)

As soon as I type "one/" the autocomplete disappears

![image](https://user-images.githubusercontent.com/39992/57335222-c8760200-70d6-11e9-8633-95b1a78b4ee2.png)

When I continue typing "one/two" all the options appear again, although only one of them should match

![image](https://user-images.githubusercontent.com/39992/57335256-dcb9ff00-70d6-11e9-9040-49eff8c204fe.png)

When I then select the `"one/two/three"` option, it adds the whole string

![image](https://user-images.githubusercontent.com/39992/57335287-f3f8ec80-70d6-11e9-9798-5e1fad74717f.png)

**Playground Link:** [playground](https://www.typescriptlang.org/play/#src=type%20Options%20%3D%20%22one%2Ftwo%2Fthree%22%20%7C%20%22two%2Fthree%2Fone%22%20%7C%20%22three%2Fone%2Ftwo%22%20%0D%0A%0D%0Afunction%20test(option%3A%20Options)%20%7B%7D%0D%0A%0D%0Atest(%22%22))

**Related Issues:** follow up to https://github.com/octokit/endpoint.js/issues/23#issuecomment-490302663

**Comment by a-tarasyuk** [comment]
@weswigham I think it happens because the following condition is equal to`false` for the string enum values which include `/`

https://github.com/microsoft/TypeScript/blob/0c9db717add6b9e396accf92f5d2249d5ffb180e/src/services/completions.ts#L2124-L2127

What do you think about _ignoring_ `/` char for this case? Maybe there is helper which can be used to determine that it is string enum value.

**Comment by weswigham** [comment]
`isValidTrigger` should probably ignore unmatching quotes and all other triggers when within a string literal. Probably. I at least can't imagine why you'd want `@` to trigger while you're in a string literal already.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by gr2m** [comment]
😍 Thank you so much! 

Will you add a comment when the fix was released? Or is it automatically published to the `@next` dist-tag? I couldn’t find any documentation on your process here, apologies if I missed it

**Comment by DanielRosenwasser** [comment]
It'll be in the next nightly, but 3.5 should be out next week.
