### ISSUE TITLE
Same code got error in js file but no error in ts file

### ISSUE THREAD

**Issue by yubaoquan** [microsoft/TypeScript#31312]
- VSCode Version: 1.31.1
- OS Version: win10 family

Steps to Reproduce:

test.js
```
import axios from 'axios' // Import declaration conflicts with local declaration of 'axios'.ts(2440)
axios.defaults.timeout = 22
```
In js file, the second line causes an error showing on first line. 
But if this two lines are in ts file (change file suffix to ts), there is no error.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Confirmed this on 3.5.0-dev.20190508.

From f12, the other local declaration of `axios` seems to be caused by the second line

**Comment by orta** [comment]
Looks like this happens with anything using `import`:

```ts
// example.js
import * as anything from 'typescript' // 1 import * as anything from 'typescript' // Import declaration  conflicts with local declaration of 'axios'.ts(2440)
         ~~~~~~~~~~~~~

anything.defaults.timeout = 22

// tsconfig
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true
  }
}
```

**Comment by orta** [comment]
Looks related to the binder: inside `function checkAliasSymbol`

```
symbol
// JS: __debugFlags:"Module|AliasExcludes|Assignment"
// TS: __debugFlags:"AliasExcludes"
```

TS has module and assignment stripped away somewhere, whereas JS does not which triggers the error message.
