### ISSUE TITLE
Loop causes index method type inference to break for switch statements

### ISSUE THREAD

**Issue by cwlucas41** [microsoft/TypeScript#31317]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
loop
type inference
switch statement
indexing
**Code**

```ts
interface I {
    [key: string]: string | number
    a: string
    b: number
}

function goodDemo(obj: I, key: string) {
    switch (key) {
        case 'a':
            const good: string = obj[key]
    }
}

function badDemo(object: I, keys: Array<string>) {
    for (const key in keys) {
        switch (key) {
            case 'a':
                // Type 'string | number' is not assignable to type 'string'.
                //   Type 'number' is not assignable to type 'string'.
                const bad: string = object[key]
        }
    }
}
```

**Expected behavior:**
no compile error due to line `const bad: string = object[key]`
**Actual behavior:**
compile error: 
```
Type 'string | number' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.
```
**Playground Link:** 
[playground](https://www.typescriptlang.org/play/#src=interface%20I%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20number%0D%0A%20%20%20%20a%3A%20string%0D%0A%20%20%20%20b%3A%20number%0D%0A%7D%0D%0A%0D%0Afunction%20goodDemo(obj%3A%20I%2C%20key%3A%20string)%20%7B%0D%0A%20%20%20%20switch%20(key)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20'a'%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20good%3A%20string%20%3D%20obj%5Bkey%5D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20badDemo(object%3A%20I%2C%20keys%3A%20Array%3Cstring%3E)%20%7B%0D%0A%20%20%20%20for%20(const%20key%20in%20keys)%20%7B%0D%0A%20%20%20%20%20%20%20%20switch%20(key)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20case%20'a'%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Type%20'string%20%7C%20number'%20is%20not%20assignable%20to%20type%20'string'.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%20%20Type%20'number'%20is%20not%20assignable%20to%20type%20'string'.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20bad%3A%20string%20%3D%20object%5Bkey%5D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:**

**Comment by falsandtru** [comment]
Dup of/Related to #22046

**Comment by cmerighi** [comment]
Seems to me that you aimed to set up a `for..`**`of`** loop (instead of a `for.. in`).
In any case, either

```js
function notThatBadDemo1(object: I, keys: Array<string>) {
    for (const key of keys) {
        switch (key) {
            case 'a':
                const bad: string = object[key]
        }
    }
}
```
or
```js
function notThatBadDemo2(object: I, keys: {[name:string]:string}) {
    for (const key in keys) {
        switch (key) {
            case 'a':
                const bad: string = object[key]
        }
    }
}
```
seem to compile correctly.  
(Don't know if it may help).

**Comment by cwlucas41** [comment]
Awesome, `for.. of` fixes the issue. Resolving.
