### ISSUE TITLE
Program.getSourceFiles missing files imported from [dir]/index.ts

### ISSUE THREAD

**Issue by kevinwilde** [microsoft/TypeScript#31318]
**TypeScript Version:**  3.4.5

**Search Terms:**
`missing source files`, `tsc getSourceFiles`

**Code**
Let's say you have the following file structure
```
src/
  entry.ts
  a.ts
  b/
    index.ts
```
For example,
_src/entry.ts_
```ts
import sum from "./a";
import multiply from "./b";

// Works as expected
console.log(sum(1, 2));
console.log(multiply(1, 2));
```
_src/a.ts_
```ts
const sum = (a, b) => a + b;
export default sum;
```
_src/b/index.ts_
```ts
const multiply = (a, b) => a * b;
export default multiply;
```

_src/entry.ts_ runs as expected. But if you try to use `Program.getSourceFiles`, _src/b/index.ts_ is not included.
```ts

import * as tsc from "typescript";

const path = require("path");
const program = tsc.createProgram([path.resolve("./src/entry.ts")], {
  target: tsc.ScriptTarget.ES2015
});

const sources = program.getSourceFiles();
// sources doesn't include src/b/index.ts
```
**Expected behavior:**
`sources` would include _src/entry.ts_, _src/a.ts_, and _src/b/index.ts_

**Actual behavior:**
`sources` includes _src/entry.ts_ and _src/a.ts_, but not _src/b/index.ts_

**Example Repo:**
https://github.com/kevinwilde/tsc-missing-sources

**Comment by ajafff** [comment]
Try setting `moduleResolution` to Node in `compilerOptions`

**Comment by kevinwilde** [comment]
Ah thank you @ajafff ! That's what I was looking for
