### ISSUE TITLE
forceConsistentCasingInFileNames shouldn't compare drive letters

### ISSUE THREAD

**Issue by arcanis** [microsoft/TypeScript#31327]
**TypeScript Version:**  master

**Search Terms:** casing forceConsistentCasingInFileNames differs from already included file name only in casing

**Actual behavior:**

TypeScript checks whether two files are referenced through similar-but-different casings. This is useful because it prevents portability problems when a project moves from a case-insensitive filesystem to a case-sensitive one. Useful feature, I approve 😃

However, it doesn't special-case the drive letter on Windows. This causes problems where `D:/foo` is seen as different from `d:/foo` even though both paths are strictly the same - let my know if I'm missing something here, but afaik the drive letters are by design strictly case insensitive.

This obviously cause issues with resolvers, since they have to return one or the other. We could try to use whatever VSCode uses, but it's pretty fragile and undocumented (VSCode seems to use lowercase letters, but that behavior could likely change especially since the UI shows the paths with uppercase letters).

**Expected behavior:**

The `D:\foo` and `D:\Foo` paths should be reported as similar-but-different, but `D:\foo` and `d:\foo` shouldn't.

**Playground Link:** n/a

**Related Issues:** n/a

**Comment by RyanCavanaugh** [comment]
@sheetalkamat what do you think?

**Comment by alirobe** [comment]
Right now, I'm getting this error in my test suite in CI only (Azure DevOps). Have had to deal with this for a while. Very frustrating, completely useless, and completely out of my control.

 +1 👍

**Comment by sheetalkamat** [comment]
Sounds like this is something user cant control so we should fix this.
