### ISSUE TITLE
A question not answered on SO: Module resolution

### ISSUE THREAD

**Issue by basickarl** [microsoft/TypeScript#31323]
`DO NOT ASK QUESTIONS HERE`, I'm sorry. But if noone knows and can answer them then it is a legitimate question here. I did ask: https://stackoverflow.com/questions/56042441/typescript-importing-module-path noone has answered.

I'm trying to migrate to TypeScript but it does not support NODE_PATH which breaks my entire application. So I need to figure out how to configure this the TypeScript way.

I have two files:

myProjectRoot/app/server.ts
myProjectRoot/app/test.ts

My server.ts file has:

import test from 'test';

I want module resolution to always use ./app/ ass the root for this. How does one accomplish this.

**Comment by basickarl** [comment]
I'm using this:

        "baseUrl": "app",
        "paths": {
            "*": [
                "./*"
            ]
        }

Why does `import test from './test';` work and not `import test from 'test';`. I mapped the path.

**Comment by basickarl** [comment]
@trotyl By all means downvote without leaving a comment on why!

**Comment by lll000111** [comment]
You've got plenty of discussion on SO.

**Comment by RyanCavanaugh** [comment]
Whether or not you got an answer on SO doesn't change whether or not this is a support forum.

**Comment by basickarl** [comment]
It's a support question if it's supported. I'm asking is this possible to
do in the first place since the documentation shows no examples.

**Comment by basickarl** [comment]
To which none come to a conclusion that it is possible to achieve. Am I
correct in this assumption?

**Comment by basickarl** [comment]
To which none come to a conclusion that it is possible to achieve. Am I correct in this assumption?
