### ISSUE TITLE
Infer type from within an Inferred Type - Define Rule for an Inferred Type

### ISSUE THREAD

**Issue by kevupton** [microsoft/TypeScript#31322]
**TypeScript Version:**  3.4.5

**Search Terms:**
Double inferring types
Infer type within type
Infer type

**Code**
```ts
class Component<C> {
}

interface ComponentType<C> {
  new () : Component<C>
}

interface TValue {
  a : boolean;
}

class T extends Component<TValue> {
  public test = 'test';
}

interface AnyBool {
  [key : string]: boolean;
}

type Components<O> = {
  [key in keyof O]: Component<O[key]>;
}





function Test4<C, D extends ComponentType<C>>(a: D): C {
}

const p4 = Test4(T); // p4 should be TValue but its {}

function Test5<C>(a: ComponentType<C>): typeof a {
}

const p5 = Test5(T); // p5 should be T but its ComponentType<C>

function Test6<C, D extends ComponentType<C> = ComponentType<C>>(a: D): D {
}

const p6 = Test6<TValue>(T); // p5 should be T but its ComponentType<TValue>








function Test1<O extends Components<AnyBool> = {}>(o? : O, b? : Partial<O>) {
  return function<
    C extends ComponentValues<O>,
    D extends ComponentType<C>
    >(a: D): C {}
}

const p = Test1({ a : new Component() })(T); // This should be TValue

type ComponentValues<T> = {
  [Key in keyof T] : T[Key] extends Component<infer R> ? R : T[Key];
}


function Test2<O extends Components<AnyBool> = {}>(o? : O, b? : Partial<O>) {
  return function<
    C extends ComponentValues<O>,
    D extends ComponentType<C>
    >(a: D): C {}
}

const p2 = Test2()(T); // p2 should be TValue but its {}


function Test3() {
  return function<
    C,
    D extends ComponentType<C>
    >(a: D): C {}
}

const p3 = Test3()(T); // p3 should be TValue but its {}


````

**Expected behavior:**
Each output to be as described in each variable

Something like this:
```ts
function Test<A, B extends ComponentType<A extends SomeObj>>() {} 

// or

function Test<A extends SomeObj, B extends ComponentType<A>>() {}
```
I would just like to be able to define some rules that are enforced upon the object

### Rules: 
 - Inferred Type A is received from inferred type `B`
 - If `A` is defined then it should enforce `B` to have `A`: `B<A>`
 - If `A` extends `Obj`, it should enforce `B`'s `A` to extend `Obj` also.
 
Super hard to explain. Hopefully examples explain how it should work.

**Actual behavior:**
It is unable to infer the type to the second depth

But this no longer allows me to infer the type C

**Playground Link:** 
[PlayGround](https://www.typescriptlang.org/play/#src=class%20Component%3CC%3E%20%7B%0D%0A%7D%0D%0A%0D%0Ainterface%20ComponentType%3CC%3E%20%7B%0D%0A%20%20new%20()%20%3A%20Component%3CC%3E%0D%0A%7D%0D%0A%0D%0Ainterface%20TValue%20%7B%0D%0A%20%20a%20%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aclass%20T%20extends%20Component%3CTValue%3E%20%7B%0D%0A%20%20public%20test%20%3D%20'test'%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20AnyBool%20%7B%0D%0A%20%20%5Bkey%20%3A%20string%5D%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Atype%20Components%3CO%3E%20%3D%20%7B%0D%0A%20%20%5Bkey%20in%20keyof%20O%5D%3A%20Component%3CO%5Bkey%5D%3E%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20Test4%3CC%2C%20D%20extends%20ComponentType%3CC%3E%3E(a%3A%20D)%3A%20C%20%7B%0D%0A%7D%0D%0A%0D%0Aconst%20p4%20%3D%20Test4(T)%3B%20%2F%2F%20p4%20should%20be%20TValue%20but%20its%20%7B%7D%0D%0A%0D%0Afunction%20Test5%3CC%3E(a%3A%20ComponentType%3CC%3E)%3A%20typeof%20a%20%7B%0D%0A%7D%0D%0A%0D%0Aconst%20p5%20%3D%20Test5(T)%3B%20%2F%2F%20p5%20should%20be%20T%20but%20its%20ComponentType%3CC%3E%0D%0A%0D%0Afunction%20Test6%3CC%2C%20D%20extends%20ComponentType%3CC%3E%20%3D%20ComponentType%3CC%3E%3E(a%3A%20D)%3A%20D%20%7B%0D%0A%7D%0D%0A%0D%0Aconst%20p6%20%3D%20Test6%3CTValue%3E(T)%3B%20%2F%2F%20p5%20should%20be%20T%20but%20its%20ComponentType%3CTValue%3E%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20Test1%3CO%20extends%20Components%3CAnyBool%3E%20%3D%20%7B%7D%3E(o%3F%20%3A%20O%2C%20b%3F%20%3A%20Partial%3CO%3E)%20%7B%0D%0A%20%20return%20function%3C%0D%0A%20%20%20%20C%20extends%20ComponentValues%3CO%3E%2C%0D%0A%20%20%20%20D%20extends%20ComponentType%3CC%3E%0D%0A%20%20%20%20%3E(a%3A%20D)%3A%20C%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aconst%20p%20%3D%20Test1(%7B%20a%20%3A%20new%20Component()%20%7D)(T)%3B%20%2F%2F%20This%20should%20be%20TValue%0D%0A%0D%0Atype%20ComponentValues%3CT%3E%20%3D%20%7B%0D%0A%20%20%5BKey%20in%20keyof%20T%5D%20%3A%20T%5BKey%5D%20extends%20Component%3Cinfer%20R%3E%20%3F%20R%20%3A%20T%5BKey%5D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20Test2%3CO%20extends%20Components%3CAnyBool%3E%20%3D%20%7B%7D%3E(o%3F%20%3A%20O%2C%20b%3F%20%3A%20Partial%3CO%3E)%20%7B%0D%0A%20%20return%20function%3C%0D%0A%20%20%20%20C%20extends%20ComponentValues%3CO%3E%2C%0D%0A%20%20%20%20D%20extends%20ComponentType%3CC%3E%0D%0A%20%20%20%20%3E(a%3A%20D)%3A%20C%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aconst%20p2%20%3D%20Test2()(T)%3B%20%2F%2F%20p2%20should%20be%20TValue%20but%20its%20%7B%7D%0D%0A%0D%0A%0D%0Afunction%20Test3()%20%7B%0D%0A%20%20return%20function%3C%0D%0A%20%20%20%20C%2C%0D%0A%20%20%20%20D%20extends%20ComponentType%3CC%3E%0D%0A%20%20%20%20%3E(a%3A%20D)%3A%20C%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aconst%20p3%20%3D%20Test3()(T)%3B%20%2F%2F%20p3%20should%20be%20TValue%20but%20its%20%7B%7D%0D%0A%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
These all look as expected. Most of these functions have too many type parameters for the number of varying inputs they actually have, and the key class does not consume its type parameter which means it's not going to be a good inference source.
