### ISSUE TITLE
JSON file indentation changed

### ISSUE THREAD

**Issue by nolazybits** [microsoft/TypeScript#31320]
**TypeScript Version:**  3.4.2

**Search Terms:**
typescript json file indentation

**Code**
Just import a json file with for instance 2 space for indentation
```ts
import MyJSON from "./acls/grants.json";
[...]
```

**Expected behavior:**
The json file should keep the same indentation

**Actual behavior:**
The json file has its indentation changed

**Related Issues:** 
https://github.com/Microsoft/TypeScript/pull/2768
https://github.com/Microsoft/TypeScript/issues/4042

**Comment by RyanCavanaugh** [comment]
In general TypeScript is only concerned with the semantics of files it emits, not formatting.

**Comment by nolazybits** [comment]
@RyanCavanaugh well this file is going to be emitted. Problem is it has the same extension as the one it emits :) and could overwrite the source, which could lead to failure on linting on the next run for instance, or CI failing as there was a change to the source files

**Comment by kitsonk** [comment]
Well that is true for `.js` files as well, which can be transpiled by TypeScript when used with `--checkJs`.

There are many situations where someone can overwrite their input, but that is sort of like blaming the hammer because you smacked your thumb.

**Comment by sheetalkamat** [comment]
We give error if the file being emitted is going to overwrite input of the program (we can only see the program at any time so if another program overwrites it, that's something we cannot detect) and do not emit such output files be it `.js` or `.json`
