### ISSUE TITLE
Type inference not correct when extenting interface with string index type

### ISSUE THREAD

**Issue by VSDekar** [microsoft/TypeScript#31336]
**TypeScript Version:**  3.4.5

**Code**

```ts
interface State {
  isNice: boolean;
}

interface TypedStringIndexType<S> {
  [key: string]: (state: S) => any;
}

interface ErrorThatIsCorrect extends TypedStringIndexType<State> {
  foo: (state: boolean) => void; // Property 'foo' of type '(state: boolean) => void' is not assignable to string index type '(state: State) => any'.
}

interface NoErrorButNoInferrence extends TypedStringIndexType<State> {
  // vscode tells me here: Parameter 'state' implicitly has an 'any' type, but a better type may be inferred from usage.ts(7044)
  foo: (state) => void; // state is any type but should be of type State
}

interface NoErrorButDoubleDeclaration extends TypedStringIndexType<State> {
  foo: (state: State) => void; 
}

const bar: ErrorThatIsCorrect = {
  foo(state) {
    console.log(state.isNice) // does not exist on type boolean
  }
}

const fooBar: NoErrorButNoInferrence = {
  foo(state) {
    console.log(state.isNice); // state is any type but should be of type State
  }
}

const barFoo: NoErrorButDoubleDeclaration = {
  foo(state) {
    console.log(state.isNice);
  }
}
```

**Expected behavior:**
correctly infer type in:
```ts
interface NoErrorButNoInferrence extends TypedStringIndexType<State> {
  // vscode tells me here: Parameter 'state' implicitly has an 'any' type, but a better type may be inferred from usage.ts(7044)
  foo: (state) => void; // state is any type but should be of type State
}
```

**Actual behavior:**
Somehow the compliler knows that it is of type State otherwise i would not get an error when i try tell the compiler that it is a boolean. But i have to tell the compiler again that state is of type State which is not nice since he already knows what it is.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=interface%20State%20%7B%0D%0A%20%20isNice%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20TypedStringIndexType%3CS%3E%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20(state%3A%20S)%20%3D%3E%20any%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ErrorThatIsCorrect%20extends%20TypedStringIndexType%3CState%3E%20%7B%0D%0A%20%20foo%3A%20(state%3A%20boolean)%20%3D%3E%20void%3B%20%2F%2F%20Property%20'foo'%20of%20type%20'(state%3A%20boolean)%20%3D%3E%20void'%20is%20not%20assignable%20to%20string%20index%20type%20'(state%3A%20State)%20%3D%3E%20any'.%0D%0A%7D%0D%0A%0D%0Ainterface%20NoErrorButNoInferrence%20extends%20TypedStringIndexType%3CState%3E%20%7B%0D%0A%20%20%2F%2F%20vscode%20tells%20me%20here%3A%20Parameter%20'state'%20implicitly%20has%20an%20'any'%20type%2C%20but%20a%20better%20type%20may%20be%20inferred%20from%20usage.ts(7044)%0D%0A%20%20foo%3A%20(state)%20%3D%3E%20void%3B%20%2F%2F%20state%20is%20any%20type%0D%0A%7D%0D%0A%0D%0Ainterface%20NoErrorButDoubleDeclaration%20extends%20TypedStringIndexType%3CState%3E%20%7B%0D%0A%20%20foo%3A%20(state%3A%20State)%20%3D%3E%20void%3B%20%0D%0A%7D%0D%0A%0D%0Aconst%20bar%3A%20ErrorThatIsCorrect%20%3D%20%7B%0D%0A%20%20foo(state)%20%7B%0D%0A%20%20%20%20console.log(state.isNice)%20%2F%2F%20does%20not%20exist%20on%20type%20boolean%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20fooBar%3A%20NoErrorButNoInferrence%20%3D%20%7B%0D%0A%20%20foo(state)%20%7B%0D%0A%20%20%20%20console.log(state.isNice)%3B%20%2F%2F%20state%20is%20any%20type%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20barFoo%3A%20NoErrorButDoubleDeclaration%20%3D%20%7B%0D%0A%20%20foo(state)%20%7B%0D%0A%20%20%20%20console.log(state.isNice)%3B%0D%0A%20%20%7D%0D%0A%7D)

**Related Issues:**
Found no related issues but didn't know what to search for.

**Comment by RyanCavanaugh** [comment]
Declarations in interfaces aren't subject to contextual types from their heritage clauses
