### ISSUE TITLE
Function overloads MIGHT  have unexpected behaviour

### ISSUE THREAD

**Issue by francjpd** [microsoft/TypeScript#31333]
**TypeScript Version:**  3.4.5
**Search Terms:**
Function overload ,  function overload  optional parameters 
**Code**

Working example
```ts

// Function overload
export function pipe<V0, T1, T2>(
  fn0: (x0?: V0) => T1,
  fn1: (x: T1) => T2
): (x0?: V0) => T2;
export function pipe<V0, T1, T2>(
  fn0: (x0: V0) => T1,
  fn1: (x: T1) => T2
): (x0: V0) => T2;

// function definition
export function pipe(...fns: Function[]) {
  return fns.reduce((accum, fn: Function) => (...args: any[]) =>
    fn(accum(...args))
  );
}

const sum = (a: number = 0) => "string";
const stringFn = (a: string) => 3;
const sumString = pipe(
  sum,
  stringFn
);

sumString(); // works great
sumString(3); // works great
sumString(undefined); // works great
```

non working example, note the order from overloads 

``` ts
// Function overload
export function pipe<V0, T1, T2>(
  fn0: (x0: V0) => T1,
  fn1: (x: T1) => T2
): (x0: V0) => T2;
export function pipe<V0, T1, T2>(
  fn0: (x0?: V0) => T1,
  fn1: (x: T1) => T2
): (x0?: V0) => T2;

// function definition
export function pipe(...fns: Function[]) {
  return fns.reduce((accum, fn: Function) => (...args: any[]) =>
    fn(accum(...args))
  );
}

const sum = (a: number = 0) => "string";
const stringFn = (a: string) => 3;
const sumString = pipe(
  sum,
  stringFn
);

sumString(); // Boom
sumString(3); // works great
sumString(undefined); // works great
```
**Expected behavior:**

The official documentation  about function overloads says: 

> In order for the compiler to pick the correct type check, it follows a similar process to the underlying JavaScript. It looks at the overload list and, proceeding with the first overload, attempts to call the function with the provided parameters. If it finds a match, it picks this overload as the correct overload. For this reason, **it’s customary to order overloads from most specific to least specific.**

It makes sense that the optional overload has to be before the required parameter, how ever, it might be difficult to notice, since the official documentation doesn't, explictly mention this case, this could cause some unexpected headaches. 

**Playground Link:**

[working fine](https://typescript-play.js.org/#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVzJsYAHgDUAGAGjgBUBGK6gJgD4AKAKDkRTIC45WIMgH5+5AJRwAvMxr1O3Wv0H86kmTUbtxyoaLgTpspgG527UJFiJUGbLnyFSlOQxYcuCHrr4Gy643lPFCUBEFVaAM1tHzF-I00zcwB6ZJt0LBw4ABNgBEwUTEyUC3BoeGQM+zwCYFYAOkavAGd+ADFbYoBtAF1JAG8FKGAYJChcFvrh7KQ0OtYAQzQ0JABbKi92zvsohsaFqABzVrgFlABPXoCFYMXltb36g+PxcQVxMwBfczQcZvhmmtpAIFvwUGsAEbAKDA+IaABE-ygBUO8LMvxQ-zgSJRbVwUhB-BxKEOUQAzOi-gC1gBlGDIknAxx1BSA9as+m4kofcxsukMw6sD5wVJwADu0AA1s04IdhgsYOw+ZySawycLRRKoNLZfLFcqBaxULl8ihgNkNWktTq5cAFUA)

[Not working](https://typescript-play.js.org/?experimentalDecorators=true&emitDecoratorMetadata=true#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVzJsYAHgDUAGAGjgBUBGK6gJgD4AKAKDkRTIC45WIPnHIBKOAF5mNep261+g-nXFSajdqMVD+YydKYBudu1CRYiVBmy58hUpRkMWHLgh7ayAfl1lVB2TcUBQEQZVp-dU1PHxE-fXVjdgB6ZMt0LBw4ABNgBEwUTEyUU3BoeGQMmzwCYFYAOkb3AGd+ADErYoBtAF1xAG85KGAYJChcFvrh7KQ0OtYAQzQ0JABbKnd2zptIhsaFqABzVrgFlABPXv85IMXltb36g+PRUTlRYwBfEzQcZvhmmtJAIFvwUGsAEbAKDA+JqABE-ygBUO8OMvxQ-zgSJRbVwEhB-BxKEOkQAzOi-gC1gBlGDIknAux1OSA9as+m4kofExsukMw6sD5wVJwADu0AA1s04IdhgsYOw+ZySawycLRRKoNLZfLFcqBaxULl8ihgNkNWktTq5cAFUA)

**Comment by francjpd** [comment]
^

**Comment by RyanCavanaugh** [comment]
I'm not sure what the aim of this report is - as you noticed, the behavior is documented and acting according to its intended design. Programming is a subtle art 😉
