### ISSUE TITLE
Typescript does not consider array.shift() to modify the array

### ISSUE THREAD

**Issue by dylanrenwick** [microsoft/TypeScript#31334]
**TypeScript Version:**  3.5.0-dev.20190509

**Search Terms:** Array Shift Always True

**Code**

```ts
class A {
    public val: number;
    public constructor(val: number) {
        this.val = val;
    }
}

let arr: A[] = [
    new A(1),
    new A(2),
    new A(3)
];

if (arr[0].val === 1) {
    arr.shift();
    while (arr[0].val !== 3) {
        console.log(arr.shift().val);
    }
}
```

**Expected behavior:**
Code outputs `2` then terminates
**Actual behavior:**
Code fails to compile with the error `This condition will always return 'true' since the types '1' and '3' have no overlap.` on the while condition `arr[0].type !== 3`.
**Playground Link:** https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20public%20val%3A%20number%3B%0D%0A%20%20%20%20public%20constructor(val%3A%20number)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.val%20%3D%20val%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20arr%3A%20A%5B%5D%20%3D%20%5B%0D%0A%20%20%20%20new%20A(1)%2C%0D%0A%20%20%20%20new%20A(2)%2C%0D%0A%20%20%20%20new%20A(3)%0D%0A%5D%3B%0D%0A%0D%0Aif%20(arr%5B0%5D.val%20%3D%3D%3D%201)%20%7B%0D%0A%20%20%20%20arr.shift()%3B%0D%0A%20%20%20%20while%20(arr%5B0%5D.val%20!%3D%3D%203)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(arr.shift().val)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:** None I could find

**Comment by dylanrenwick** [comment]
Worth noting that this does *not* occur when operating directly on an array of numbers, eg:
https://www.typescriptlang.org/play/#src=let%20arr%3A%20number%5B%5D%20%3D%20%5B1%2C%202%2C%203%5D%3B%0D%0A%0D%0Aif%20(arr%5B0%5D%20%3D%3D%3D%201)%20%7B%0D%0A%20%20%20%20arr.shift()%3B%0D%0A%20%20%20%20while%20(arr%5B0%5D%20!%3D%3D%203)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(arr.shift())%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Comment by ahejlsberg** [comment]
This is a design limitation as covered in #9998.
