### ISSUE TITLE
TypeScript requiring declaration file for installed JS module containing JSDoc typings

### ISSUE THREAD

**Issue by DullReferenceException** [microsoft/TypeScript#31339]
It's unclear to me whether this is a bug (since it seems _others_ are able to import JS) or a feature request, but it appears importing JS for installed modules still requires declaration files, even if these modules have jsdocs. Importing _local_ JS files is working fine.

**TypeScript Version:**  3.5.0-dev.20190509

**Search Terms:** jsdoc, declaration file, import, JavaScript

**Code**

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "allowJs": true,
    "checkJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "preserve",
    "lib": ["dom", "es2017"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "sourceMap": true,
    "strict": true,
    "target": "esnext"
  }
}
```

```ts
// Importing code
import { someFunc } from "blah";

export default someFunc(2, 4);
```

```js
// node_modules/blah/index.js

/**
 * Does some things
 *
 * @param foo {number}
 * @param bar {number}
 * @returns {number}
 */
function someFunc(foo, bar) {
  return foo + bar;
}

module.exports = {
  someFunc
};
```

**Expected behavior:**
Import occurs without errors.

**Actual behavior:**
Error:

> Could not find a declaration file for module 'blah'. '.../node_modules/blah/index.js' implicitly has an 'any' type.ts(7016)

**Playground Link:** 

**Related Issues:** 
Possibly https://github.com/microsoft/TypeScript/issues/19145

**Comment by DullReferenceException** [comment]
Odd, if I add this compiler option:

```
"maxNodeModuleJsDepth": 1
```

...then `tsc` doesn't generate an error, but vscode still shows the error message.

**Comment by DullReferenceException** [comment]
So maybe this _is_ a duplicate of https://github.com/microsoft/TypeScript/issues/19145; will try to understand why vscode is showing incorrect error output.

**Comment by patarapolw** [comment]
> Odd, if I add this compiler option:
> 
> ```
> "maxNodeModuleJsDepth": 1
> ```
> 
> ...then `tsc` doesn't generate an error, but vscode still shows the error message.

Not OK for [appdirs](http://building5.github.io/appdirsjs/index.js.html). May need `depth: 2` or something.

Anyways, resorted to `jsdoc -t tsd-jsdoc/dist node_modules/appdirs/index.js`, which will generate `out/types.d.ts`

https://www.npmjs.com/package/tsd-jsdoc

**Comment by linonetwo** [comment]
Typescript now supports generate dts directly from JSDoc, don't need `jsdoc -t tsd-jsdoc/dist`. Just use `tsc`.

And I find https://github.com/sveltejs/svelte/ is writing JSDoc typing, and generate dts before publishing.
