### ISSUE TITLE
union type over generics inconsistency

### ISSUE THREAD

**Issue by bluescreen303** [microsoft/TypeScript#31340]
**TypeScript Version:**  3.5.0-dev.20190508

**Search Terms:** union generics

**Code**

```ts
type Foo1 = (e: string) => { bar: number, name: string } | { bar: number, label: string }
function t1(foo: Foo1): number {
    return foo("hello").bar + 1
}

type Foo2 = ((e: string) => { bar: number, name: string }) | ((e: string) => { bar: number, label: string })
function t2(foo: Foo2): number {
    return foo("hello").bar + 1
}
type Foo3 = <E>(e: E) => { bar: number, name: E } | { bar: number, label: E }
function t3(foo: Foo3): number {
    return foo("hello").bar + 1
}

type Foo4 = (<E>(e: E) => { bar: number, name: E }) | (<E>(e: E) => { bar: number, label: E })
function t4(foo: Foo4): number {
    return foo("hello").bar + 1
}
```

**Expected behavior:**
I would expect `t4` to work, because it is just a combination of `t2` and `t3`, which both work.
Clearly, typescript is able to process over function types in a union and isn't blocked by functions that have a generic type parameter.

**Actual behavior:**
```
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Foo4' has no compatible call signatures.
```

**Comment by jack-williams** [comment]
I think this is a current design limitation. Call signatures are not synthesized for unions of generic functions. See [here](https://github.com/Microsoft/TypeScript/issues/7294#issuecomment-465801362
).

**Comment by RyanCavanaugh** [comment]
Thanks @jack-williams for link to #7294

**Comment by jack-williams** [comment]
No problem @RyanCavanaugh!
