### ISSUE TITLE
Cannot create mapped tuple type with constrained generic type

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#31342]
**TypeScript Version:**  3.4.2

**Search Terms:** 

Mapped tuple type constrained

**Code**

```ts
// works:
export type Box<T> = { value: T };
export type Boxified<T extends any[]> = { [P in keyof T]: Box<T[P]> };

// fails:
export interface I { x: number; }
export type Box2<T extends I> = { value: T };
export type Boxified2<T extends I[]> = { [P in keyof T]: Box2<T[P]> };
```

**Expected behavior:**
`Boxified2` can be used to boxify tuples of types implementing `I`.

**Actual behavior:**
Error: `Type "I[][P]" cannot be assigned to type "I". ts(2344)` for `Box2<T[P]>`

**Comment by jack-williams** [comment]
I believe this is working as intended. The constraint `extends I[]` only says that the number keys of `T` are assignable to `I`, but `T` may be a type with non-number keys that are unassignable. For example:
```ts
const symbolKey = Symbol();
interface Foo extends Array<I> {
    [symbolKey]: string;
}

type FooBox = Boxified2<Foo>; // ok, but not all keys of Foo are assignable to I!

declare const fooElement: Foo[keyof Foo];
const i: I = fooElement; // error
```

You need to specify that only the number keys are being used in the mapped type:
```ts
export type Boxified2<T extends I[]> = { [P in (keyof T & number)]: Box2<T[P]> };
```

**Comment by danielrentz** [comment]
You are right, thank you very much for the explanation!

**Comment by danielrentz** [comment]
Thanks @jcalz indeed I was still having problems with my original code. I will give it a try!

**Comment by jcalz** [comment]
Cross-linking issue to #27351, of which this is probably a duplicate
