### ISSUE TITLE
Export of `declare class` generating invalid JavaScript export

### ISSUE THREAD

**Issue by halfnibble** [microsoft/TypeScript#31346]
**TypeScript Version:** Version 3.5.0-dev.20190509

**Search Terms:**
export declare, export declare class, export of export declare

**Code:**

```ts
// FooBarExports.ts
export default class FooExport {
    foo: number
}

/* DECLARE!! */
export declare class BarExport {
    bar: number
}

// index.ts
export { default as FooExport } from './FooBarExports'
export { BarExport } from './FooBarExports'
```

**Expected behavior:**
I expect the output JavaScript in `index.js` to not have any reference to  the **declare** class `BarExport`

**Actual behavior:**
Instead I get a reference to BarExport like this:
```js
...
var FooBarExports_2 = require("./FooBarExports");
exports.BarExport = FooBarExports_2.BarExport;
```
This does not work because FooBarExports.js does not have `BarExport` defined.

**Playground Link:** *All code is listed above. Must be in two separate files to reproduce.*

**Related Issues:**
Possibly related?
https://github.com/microsoft/TypeScript/issues/29263

**Comment by RyanCavanaugh** [comment]
`declare`ing the existence of something that doesn't exist create problems.

If something doesn't exist, it is incorrect to `declare` its existence.

**Comment by halfnibble** [comment]
@RyanCavanaugh That makes sense. I'm still new to TypeScript and the codebase, but I am assured that the type we are `declare`ing, in this example `BarExport`, is in fact defined somewhere. (Perhaps another library or a browser API? I'm not sure...)

Are you saying it is never correct to export a `declare`ed class? That one should only ever export the actual implementation?

**Comment by RyanCavanaugh** [comment]
`export declare` means "There is a thing here being exported, but the implementation of that thing is not provided by this declaration". It's *unlikely* that this is actually happening, but it's *definitely possible* (e.g. maybe you have a CommonJS module and are dynamically tacking stuff onto `module.exports`).

If you're trying to describe some class that's in another module or in the global scope, it would certainly be incorrect to `export` it
