### ISSUE TITLE
The current 1.8 spec should feature a more prominent warning about being outdated

### ISSUE THREAD

**Issue by slikts** [microsoft/TypeScript#31369]
This relates to issues like #15711 and #21477, and the suggestion is to add a more prominent notice that the [current spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md) is long out of date or legacy. A more visible notice is needed because the document's presence in the `master` branch under `doc/spec.md` suggests (at a glance) that the document would be current, and the version number and date at the top is easy to overlook and is bound to cause confusion (speaking from experience).

**Comment by jakebailey** [comment]
This is an old issue, but in #51791 I deleted the spec wholesale; I don't think it gets more prominent than "doesn't exist".
