### ISSUE TITLE
Literate programming support

### ISSUE THREAD

**Issue by filipesilva** [microsoft/TypeScript#31364]
## Search Terms

literate

## Suggestion

I would like to see some sort of [Literate programming](https://en.wikipedia.org/wiki/Literate_programming) support in TypeScript.

There's already a lot of tools for various languages around to extract both runnable code and the documentation from the "literate" source file. But since TypeScript has a very strong emphasis on tooling, it would be a shame to step outside tooling support to enable literate programming.

Haskell is an example of a language that ships with [native literate programming support](https://wiki.haskell.org/Literate_programming).

## Use Cases

Enabling users of TS to use literate programming seamlessly.

## Examples

I don't have a strong opinion on how the feature would be enabled, and what syntax would be used for the literate bits.

https://github.com/Rich-Harris/lit-node provides a good example of how literate programming could look like in the JS world:
```
# this is a markdown file!

It can have *all the usual markdown stuff*, but only the JavaScript code blocks will run:

``
// log a message
console.log('hello world');
``
```
(those double backticks in there should be triple backticks, but I made them just double to not exit the code block)

I imagine the file would be called something like `.tsl` (by comparison with the existing `.tsx`. Existing TS tooling would still provide completion and code hint for the code in the literate file, and `tsc` would properly compile this file as if it only contained the code. Perhaps a markdown file would be emitted side by side with the `.js`.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by kitsonk** [comment]
I highly doubt that this feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals), though you checked it.

This is clearly a potentially good idea for some community project harnessing the [TypeScript compiler APIs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) as part of the solution, not something that the TypeScript compiler itself should consider in my opinion.

**Comment by zpdDG4gta8XKpMCd** [comment]
enlighten me how jsdoc comments are not a good fit for it (given decent support to markdown)?

**Comment by filipesilva** [comment]
@kitsonk I read through the goals and thought goal 5 (Produce a language that is composable and easy to reason about) would be furthered by it, and that the other goals wouldn't be interfered with. It doesn't seem to be part of any non-goals either. Are there some of these you think are actually in conflict with literate programming?

@zpdDG4gta8XKpMCd I think the [Contrast with documentation generation](https://en.wikipedia.org/wiki/Literate_programming#Contrast_with_documentation_generation) part of the wiki page covers that well:
> Literate programming is very often misunderstood[9] to refer only to formatted documentation produced from a common file with both source code and comments – which is properly called documentation generation – or to voluminous commentaries included with code. This is the converse of literate programming: well-documented code or documentation extracted from code follows the structure of the code, with documentation embedded in the code; while in literate programming, code is embedded in documentation, with the code following the structure of the documentation.
> 
> This misconception has led to claims that comment-extraction tools, such as the Perl Plain Old Documentation or Java Javadoc systems, are "literate programming tools". However, because these tools do not implement the "web of abstract concepts" hiding behind the system of natural-language macros, or provide an ability to change the order of the source code from a machine-imposed sequence to one convenient to the human mind, they cannot properly be called literate programming tools in the sense intended by Knuth.

There is a key bit here that might be completely impractical though: 
> provide an ability to change the order of the source code from a machine-imposed sequence to one convenient to the human mind

It's definitely possible to do code reordering within the TS compiler, but it might be very onerous and impractical.

**Comment by kitsonk** [comment]
> Are there some of these you think are actually in conflict with literate programming?

> 6. Align with current and future ECMAScript proposals.

The place to start with all TypeScript syntax is get it accepted as part of the ECMA-262 standard.

> 8. Avoid adding expression-level syntax.

Supporting literate programming would be adding loads of expression level syntax.

From the non-goals:

> 1. Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.

TypeScript is JavaScript, TypeScript is not some other language, or various other languages.

I mean overall, it isn't an express goal to be something other than a superset of JavaScript, but it is strongly applied.  This suggestion is not a superset of JavaScript, it is something entirely different, which can be achieved by utilising the TypeScript compiler APIs as part of a solution if one so desired without diverting resources from the TypeScript core team, so they can work on actually building a language compiler.

**Comment by filipesilva** [comment]
Yes, now that you describe it like that, I agree that this would never be a JavaScript and that's probably a non-starter. Valid JS would not be valid literate TS because it would need to be enclosed in triple backticks (or something else).

> The place to start with all TypeScript syntax is get it accepted as part of the ECMA-262 standard

I don't really agree with this bit though: types and tsx syntax are present in TS but aren't part of the standard either. They might be proposed, but I didn't check. 

It might be possible to use the TS language service to get tooling support for only part of a file, thus addressing the main problem of foregoing TS tooling. I haven't tried it. But it seems like a great approach.

**Comment by orta** [comment]
I wonder if extending the [ts tooling support for mdx](https://mdxjs.com) might be enough to get what you're looking for?

**Comment by RyanCavanaugh** [comment]
If this sort of pattern starts catching on in the vanilla JS world, we would definitely take interest in adding a TypeScript variant, but this is a very big area for us to trailblaze into.

**Comment by mistlog** [comment]
I find a way to do code reordering, but I don't know whether it's good or not.  
see https://github.com/mistlog/typedraft

The basic idea is to still write typescript, but in a slightly different way with the help of JSX.

This project is a translator that output .ts from .tsx, and another tool [source-view](https://github.com/mistlog/source-view) is used to turn code into document.

I list some examples, such as the project [itself](https://github.com/mistlog/typedraft/wiki#typedraft), some [algorithms](https://github.com/mistlog/typedraft/wiki#algorithm) and a moderate sized [vm](https://github.com/mistlog/typedraft/wiki#jack-vm)

**Comment by johtela** [comment]
> This is clearly a potentially good idea for some community project harnessing the [TypeScript compiler APIs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) as part of the solution, not something that the TypeScript compiler itself should consider in my opinion.

[Here](https://github.com/johtela/litscript) is one community project that uses the compiler API to create documentation from TypeScript projects. It is not a bonafide literate programming tool, but rather a sophisticated documenation generation program. It might fit the bill if you are willing to give up the requirement of code reordering.

**Comment by mistlog** [comment]
> [Here](https://github.com/johtela/litscript) is one community project that uses the compiler API to create documentation from TypeScript projects. It is not a bonafide literate programming tool, but rather a sophisticated documenation generation program. It might fit the bill if you are willing to give up the requirement of code reordering.

Thanks for your litscript!

I reimplemented [Ray Tracing in One Weekend](https://raytracing.github.io/books/RayTracingInOneWeekend.html) in typedraft & litscript, see https://mistlog.github.io/ray-tracing/index.html, and I think it's a good example for demonstrating literate programming in typescript, or js world.
