### ISSUE TITLE
Improve error messages for method chains

### ISSUE THREAD

**Issue by ulrichb** [microsoft/TypeScript#31365]
## Search Terms

error call chain fluent api

## Suggestion

In call chains some errors like TS2554 ("Expected x arguments, but got y") are reported for the whole call chain.

Example:

![image](https://user-images.githubusercontent.com/388796/57589464-36ca2280-7524-11e9-9fef-de0242fe3860.png)

In this case the error is reported (starting) at line 5 where the actual error is in line 14.

*Suggestion:* Just highlight the concerned (last) method invocation in this case.  

## Use Cases

* Fluent APIs: These sub-optimal error reporting is misguiding in fluent APIs because the start line number can be off hundreds of lines. Further, way too much is highlighted in red squiggles (for a single missing argument as in the example above).

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by zpdDG4gta8XKpMCd** [comment]
indeed can we work on more precise/meaningful/drama-free error scopes?

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser This seems like pure win to me. Thoughts?

**Comment by RyanCavanaugh** [comment]
Daniel likes it per offline conversation. Accepting PRs to change the error span to just the method name + argument list.

**Comment by dhruvrajvanshi** [comment]
Can I try this?

**Comment by DanielRosenwasser** [comment]
Go for it.

**Comment by asicminer001** [comment]
we will

**Comment by DanielRosenwasser** [comment]
Thanks @dhruvrajvanshi!
