### ISSUE TITLE
Setting to Disable Outline Sidebar

### ISSUE THREAD

**Issue by nathanjd** [microsoft/TypeScript#31378]
## Search Terms

performance, outline, sidebar, settings, markdown, typescript

## Suggestion

A setting to disable the sidebar outline altogether.

```javascript
userSettings.outline.isDisabled = true;
workspaceSettings.outline.isDisabled = true;
```

Alternatively, if it could be hidden by default and the work could be deferred until the first expansion that would be satisfactory.

```javascript
userSettings.outline.shouldHideByDefault = true;
workspaceSettings.outline.shouldHideByDefault = true;
```

## Use Cases

- Outline sidebar can cause UI non-responsiveness. Particularly on large markdown documents.
- Personally, I dislike the visual noise so would at least like a setting to hide by default. Having to manually collapse it upon opening every window is frustrating.

## Examples

The following are bugs, but represent a few reasons why a developer might want to disable the outline to improve performance. At least until the plugin's performance issues are resolved.

- https://github.com/microsoft/TypeScript/issues/28389
- https://github.com/yzhang-gh/vscode-markdown/issues/42

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Seems like you mean to file this at https://github.com/microsoft/vscode

**Comment by nathanjd** [comment]
Err whoops, meant to put this into vscode. My bad.
