### ISSUE TITLE
TS2322 strictNullChecks JSDoc: optional value is not optional on destructuring with default values

### ISSUE THREAD

**Issue by ilyaigpetrov** [microsoft/TypeScript#31372]
**TypeScript Version:**  3.5.0-dev.20190512

**Search Terms:**
TS2322 strictNullChecks JSDoc destructuring

**Code**

```js
// tsc --NoEmit --StrictNullChecks --allowJs --checkJs ./this-file.js
'use strict'
/**
  @param {{
    handler?: (Function | undefined | void),
  }} _
*/
const installHandler = ({
  handler = undefined,
}) => console.log('All right.');

installHandler({
  handler: () => {},
});
```

**Expected behavior:**

No type checking error.

**Actual behavior:**

`error TS2322: Type 'undefined' is not assignable to type 'Function'.`

**Playground Link:** https://www.typescriptlang.org/play/index.html#src='use%20strict'%0D%0A%2F**%0D%0A%20%20%40param%20%7B%7B%0D%0A%20%20%20%20handler%3F%3A%20(Function%20%7C%20undefined%20%7C%20void)%2C%0D%0A%20%20%7D%7D%20_%0D%0A*%2F%0D%0Aconst%20installHandler%20%3D%20(%7B%0D%0A%20%20handler%20%3D%20undefined%2C%0D%0A%7D)%20%3D%3E%20console.log('All%20right.')%3B%0D%0A%0D%0AinstallHandler(%7B%0D%0A%20%20handler%3A%20()%20%3D%3E%20%7B%7D%2C%0D%0A%7D)%3B%0D%0A

**Related Issues:**

https://github.com/microsoft/TypeScript/issues/20287: Error with strictNullChecks when destructuring and renaming

**Comment by RyanCavanaugh** [comment]
JS Doc tags aren't interpreted in TypeScript files. Is this repro intended to be in a JS file?

**Comment by ilyaigpetrov** [comment]
@RyanCavanaugh Yes, the repro is intended to be in a JS file, see the first commented line of the repro above.

**Comment by ilyaigpetrov** [comment]
Without JSDoc there is no issue, the following code produces no errors:
```ts
// tsc --NoEmit --StrictNullChecks ./this-file.ts
'use strict';

const installHandler = ({
  handler  = undefined,
} : { handler?: Function}) =>
  console.log('All right.');

installHandler({
  handler: () => {},
});
```

**Comment by ilyaigpetrov** [comment]
Any plans on this issue? Which files in the source code should I look to get it fixed?

**Comment by ilyaigpetrov** [comment]
I've managed to reproduce a very similar error without any JSDoc:
```js
'use strict';

type numberOrUndefined = number | undefined;

const installHandler = ({
  handler : numberOrUndefined = undefined,
}) => console.log('All right.');

installHandler({
  handler : numberOrUndefined = 12,
});
```
Error: `Type 'number' is not assignable to type 'undefined'.(2322)`.

https://www.typescriptlang.org/play/index.html#code/OQVwzgpgBGAuBOBLAxrYBuAsAKB7AngA7QB2IAtgEYTwDy8AqiQCYQBmiJEzUAvFGSo0oAHyggW7Ttyy5syAPYk4UTnACGAG00AJdS03D+ACgDeOKFAAW+5ofhQAXAIrU6jSRy49+E1l+4AGhwAXwBKPgA+KEVlBUMAOk0FAHNjYABBbSgkFKtYBOAw2Rw1WC1dW3szC2sq4WdBN3omf2kfKABGACZg7HDZIA

**Comment by cwadrupldijjit** [comment]
I've seen a similar case with the following `tsconfig`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "module": "commonjs",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noEmit": true,
    "lib": ["es2018"],
    "target": "es2018"
  },
  "include": [
    "./src/**/*"
  ],
  "compileOnSave": true
}
```

And the following example (in a JS file):
```js
/**
 * @param {{ bar?: string|null }} _
 */
const baz = ({bar = null} = {}) => {
    return bar;
}

baz();
baz({bar: null});
baz({bar: "null"});
baz({});
```

The original `tsconfig` used the `strict` option enabled, but by disabling some of the options that it automatically enables, we figured out that was where it came from.

Having an equivalent TypeScript version with the exact same options enabled, there is no error.  The TypeScript version is like the following:

```ts
const foo = ({bar = null}: { bar?: string|null } = {}) => {
    return bar;
}

foo();
foo({bar: null});
foo({bar: "null"});
foo({});
```

It seems to ignore the JSDoc altogether in the JS file, though I imagine that if it didn't, it wouldn't show the error.  Oddly, it only seems to ignore the JSDoc when the strict null check option is enabled but the JSDoc is enough to work for the `noImplicitAny` option.

**Comment by cwadrupldijjit** [comment]
@RyanCavanaugh:  Is that additional information helpful?

**Comment by RyanCavanaugh** [comment]
This appears to be working now.
