### ISSUE TITLE
Unit test feature inside the language

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#3138]
D language has a great feature that allows to [write unit tests right in the class/module itself](http://dlang.org/unittest.html).

Could typescript have something similar? When defining a class one could inline testing code using the `unittest` block:

```js
class MyClass {

    myMethod() {
         // ...
    }

    unittest {
        // ...
    }

}
```

When transpiling the `unittest` blocks would be ignored/removed.

When transpiled with `--unittest` flag the unit tests would be put in a single `.test.js` file, while the rest of the code would be ignored.

The feature should be generic, so that one could choose their preferred testing framework: `mocha`, `sinon`, etc..

It could go along the following line:

```js
// Arithmetic.ts
unittest {
    var assert = require("assert");
}

class Arithmetic {

    add(a, b) {
         return a + b;
    }

    unittest {
        it("testing .add() method", () => {
            var arithmetic = new Arithmetic;
            assert.equal(2, arithmetic.add(1, 1));
        });
    }

}

export = Arithmetic;
```

Then running `tsc --unittest Arithmetic.ts`, would results in something like this:

```js
// Arithmetic.test.js
var Arithmetic = require("./Arithmetic.js");
var assert = require("assert");
it("testing .add() method", function() {
    var arithmetic = new Arithmetic;
    assert.equal(2, arithmetic.add(1, 1));
});
```

**Comment by DanielRosenwasser** [comment]
Could decorators not achieve similar results?

**Comment by mhegazy** [comment]
This is out of scope at the current time. marking as revisit.
