### ISSUE TITLE
Ability to supply object literal property types with JSDoc comments (like plain JS files)

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#31386]
## Search Terms

No search terms, I tried it and it didn't work (like it does with `.js` files).

## Suggestion

It may be useful to be able to type properties with JSDoc comments, even in `.ts` files.

## Use Cases

It just makes some things easier.

## Examples

F.e., 

```ts
function factory() {
  let o = {
    foo: 'foo', // `string` type
    /** @type {number | null} */
    bar: null,
  }

  o.bar = 42

  return o
}
```

Compared to the less DRY equivalent:

```ts
type Obj = {
  foo: string
  bar: number | null
}

function factory() {
  let o: Obj = {
    foo: 'foo',
    bar: null,
  }

  o.bar = 42

  return o
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
Just throwing this out there a type assertion could work although you loose some type safety:

```ts
function factory() {
  let o = {
    foo: 'foo',
    bar: null as number | null,
    obj: {a : 0 } as { a: number, b: number}, // type safery loss
    obj2: {a : "0" } as { a: number, b: number} // missmatched types are atill an error
  }
  o.bar = 42

  return o
}
```

Or if you don't mind the extra function call: 
```
    function check<T>(o: T): T {
        return o;
    }
    function factory() {
        let o = {
            foo: 'foo',
            bar: check<number | null>(null),
            obj: check<{ a: number, b: number }>({ a: 0 }), // error now 
            obj2: check<{ a: number, b: number }>({ a: "0" }) // still an error
        }
        o.bar = 42

        return o
    }
```

Neither version is ideal, but relying on jsdoc tags in .ts files seems alien to me. 

Ideally ts should be able to model this, maybe with a new type of type assertion. One that tells the compiler the expected  type of an expression and forces the compiler to check it as well. Something like `{ a: 0 } as infer { a: 0, b: string }` where the asserted expression is checked to be of the expected type. Maybe also add type parameters to it so we can avoid using extra functions when we create an object but want parts of it inferred: `{ a: 0, b: 0 } as infer <T>{ a: T, b: T }` . But enough with the day dreaming 😔

**Comment by RyanCavanaugh** [comment]
We don't want to conflate both kinds of assertions in the same file. There are other issues about "soft" assertions that would accomplish something close to what you're looking for

**Comment by trusktr** [comment]
Have an example of a "soft assertion"?
