### ISSUE TITLE
Optional types, shortcut to `... | undefined`

### ISSUE THREAD

**Issue by anurbol** [microsoft/TypeScript#31390]
## Search Terms
optional type, undefined

## Suggestion

I am soooo sorry if it has been suggested already (I am 99% sure it has).
```
let foo: string? // should produce string | undefined.
```
It's much shorter then `string | undefined` and also intuitive.
It is also consistent with the syntax of optional properties in interfaces.

## Use Cases
In my code I love to have my variables declared on top and initialzed later. So I am tired to write types like `... | undefined`

My suggestion meets these guidelines:

* ? This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
See: #7426

**Comment by anurbol** [comment]
@jack-williams Thank you so much, for the response, and a very quick one! With your help [I've found](https://github.com/microsoft/TypeScript/issues/31387) that it has already been implemented, but `null` is chosen instead of `undefined`..
