### ISSUE TITLE
infer type unexpect

### ISSUE THREAD

**Issue by foreverzmy** [microsoft/TypeScript#31391]
When I run code as :

```ts
type PayloadType =((s: number) => void) extends (arg1: any, payload?: infer U) => any ? U : never;
```

I got the `PayloadType = {}`

I think it's a bug, it should be `undefined` i wise.

**Comment by RyanCavanaugh** [comment]
`{}` is the type produced by generic inference when there are no inference candidates, which is what's happening here. I don't see a principled reason to produce `undefined` here - there is simply no corresponding parameter for `U` at all.

**Comment by foreverzmy** [comment]
Emmm, And how I get `undefined` when the second paramters is empty? 

Here is what i want todo：[tsplayground](https://www.typescriptlang.org/play/#src=interface%20State%20%7B%0D%0A%20%20%20%20count%3A%20number%0D%0A%7D%0D%0A%0D%0Aconst%20reducers%20%3D%20%7B%0D%0A%20%20increment%3A%20(state%3A%20State%2C%20payload%3A%20number)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%7B%20count%3A%20state.count%20%2B%20payload%20%7D%3B%0D%0A%20%20%7D%2C%0D%0A%20%20decrement%3A%20(state%3A%20State%2C%20payload%3A%20number)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%7B%20count%3A%20state.count%20-%20payload%20%7D%3B%0D%0A%20%20%7D%2C%0D%0A%20%20console%3A%20(state%3A%20State)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%7B%20count%3A%20state.count%20%7D%3B%0D%0A%20%20%7D%2C%0D%0A%7D%3B%0D%0A%0D%0Atype%20KeyT%20%3D%20string%20%7C%20number%20%7C%20symbol%3B%0D%0A%0D%0Atype%20Reducer%20%3D%20typeof%20reducers%3B%0D%0A%0D%0Atype%20ExtractPayload%3CT%3E%20%3D%20T%20extends%20(arg1%3A%20any%2C%20payload%3A%20infer%20U)%20%3D%3E%20any%20%3F%20U%20%3A%20never%3B%0D%0A%0D%0Atype%20ToReducerType%3CK%20extends%20KeyT%2C%20T%3E%20%3D%20%7B%20%22type%22%3A%20K%2C%20payload%3A%20T%20%7D%3B%0D%0A%0D%0Atype%20ToReducersType%3CT%3E%20%3D%20%7B%20%5BP%20in%20keyof%20T%5D%3A%20ToReducerType%3CP%2C%20ExtractPayload%3CT%5BP%5D%3E%3E%20%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0Atype%20ReducerTypes%20%3D%20ToReducersType%3CReducer%3E%3B%0D%0A%0D%0Aconst%20a%3A%20ReducerTypes%20%3D%20%7B%0D%0A%20%20%20%20%22type%22%3A%20%22console%22%0D%0A%7D)

**Comment by dragomirtitian** [comment]
@foreverzmy Since this turned into a question, maybe you should ask it on SO ?

**Comment by foreverzmy** [comment]
@dragomirtitian sorry, I misunderstand.
