### ISSUE TITLE
Method inferred as `any` due to self-reference when no self-reference is obvious

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#31399]
I ran into this while working on my `from.js` query library.  I tried to reduce the repro case as much as possible; what's below seems to be the minimum necessary to trigger the issue.

What's *really* bizarre is that if you hover over `selectMany`, TS *knows* that returns a `Query<R>`... and yet despite returning that directly, it can't infer the return type of the function?

**TypeScript Version:**  3.5.0-dev.20190514

**Search Terms:**
* any referenced directly indirectly

**Code**

```ts
type Queryable<T> = T[] | ArrayLike<T> | Query<T>;

type Aggregator<T, R> = (accumulator: R, value: T) => R;
type JoinPredicate<T, U> = (lValue: T, rValue: U) => boolean;
type Predicate<T> = (value: T) => boolean;
type Selector<T, R> = (value: T) => R;
type ZipSelector<T, U, R> = (lValue: T, rValue: U) => R;

class Query<T>
{
	aggregate<R>(aggregator: Aggregator<T, R>, seedValue: R)
	{
		return seedValue;
	}
	join<U, R>(innerSource: Queryable<U>, predicate: JoinPredicate<T, U>, selector: ZipSelector<T, U, R>) {
		return this.selectMany(lValue =>
			new Query<U>()
				.where(it => predicate(lValue, it))
				.select(it => selector(lValue, it)));
	}
	select<R>(selector: Selector<T, R>) {
		return new Query<R>();
	}
	selectMany<R>(selector: Selector<T, Queryable<R>>) {
		return new Query<R>();
	}
	toArray()
	{
		return this.aggregate((a, it) => (a.push(it), a), [] as T[])
	}
	where(predicate: Predicate<T>) {
		return new Query<T>();
	}
}
```

**Expected behavior:**
Compiles successfully.

**Actual behavior:**
TS7023 - `join` implicitly has return type `any` because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

**Playground Link:**
https://typescript-play.js.org/#code/C4TwDgpgBAigrhATiAhgIwDYQDwBUB8UAvFLgNoC6UAPlAIKKIogAyAlgNY4E2wLJ58AbgBQI0JHoBzKYghSUwAPaI8AGigAlQiQAUKAMYG4AWzgZFKgFxaNANxQYEN3AEpihTaInQAUkrYAOwAFOQATNgNFbg0AVR0oXQwANUdnUg1EVKcIG1j3IkI0JSUsFEDvcGhQiAio4G4E3QcclwKikrKK8SqoAGUILANlVVwNbWJElvS3Dy1KyQAtNjABoZH1KFjxppS03IyoLP289vmxAwsAZyu+JBBBEQBvEQBIFBk5BQbsbX1P+SWRA2OgA74qTbaDRXCC1bLpTSuN4vV6vOTAOCIQJQGFw-aiV4AXzeACsAoFsNstPhdEFAkg+kpMQYDvB7ugsJT8BowOFItEbP4gjU6tFNvFoYMIMNrFBlqspTLRnEdu4UWiIBisVBgAALNhXAB0MPWAFlyiAkvDoIU3qj6QB3O4CeK6JGo1GGh26pAQWnAOa82r8hpW-YaNjAVzuj3GxXAf1zE3SkZhnIRqPRgnE17J4a-Gl5kY2NYpiFjalqu3ozHYx3Oh5-VzZt5F82BRuF+Oy0tKzZs5AcnDafBV1E17X1gedt0t17KBhMS3u9UT7F6g2Gj6yQGh-QZs76Q1gOBXXX+1waFCXqCUKAoW7kCjunPe326IOiho2EUhxpjjUtTrCAnWnQRZzeYliSAA

**Related Issues:**
I *think* this might be #26623 but I'm not 100% positive.

**Comment by fatcerberus** [comment]
Here's something interesting: after reading through #26623 I thought the circularity might be due to TS looking at the type of `Query` as a whole, but that doesn't seem right either: changing the implementation of `join` in the Playground example to:

```ts
		return this.selectMany(lValue =>
			new Query<U>()
				.where(it => predicate(lValue, it))
				.select(it => selector(lValue, it))
				.toArray());
```

...makes the error go away.

**Comment by RyanCavanaugh** [comment]
The circularity observation occurs when we're trying to determine the type of `R` in `selectMany`. During this process, we're relating `Query<T>` to `T[] | ArrayLike<T> | Query<T>` to find inference candidates for `T` - this is a structural operation when we're seeing if there are correspondences for `T` between e.g. `T[]` and `Query<T>`, and we try to resolve the type of `join` during this operation (this is all correct - nothing that doesn't need to happen is happening).

This doesn't happen with the `.toArray` call because `toArray` returns `T[]`, so there's no resolving of `Query<T>`'s members when we're relating `T[]` to `T[] | ArrayLike<T> | Query<T>` to find candidates for `R`.

**Comment by RyanCavanaugh** [comment]
Here's the small(ish) version:

```ts
type Foo<T> = T[] | MyClass<T>;
class MyClass<T> {
	manifested!: T;

	foo1() {
		return this.bar(new MyClass<T>());
	}

	foo2() {
		return this.bar((new MyClass<T>()).toArray());
	}

	toArray(): T[] {
		return [];
	}

	bar<X>(arg: Foo<X>) { }
}
```

**Comment by fatcerberus** [comment]
What’s odd (to me) is that TS *knows* `.selectMany` returns a `Query<R>` if I hover over it... and yet somehow isn’t able to pass that through to the return type of `.join`?

**Comment by RyanCavanaugh** [comment]
Sure, there's no contradiction there. `join`'s return type was fixed to `any` during inference and everything proceeded as normal.

**Comment by fatcerberus** [comment]
Ah, that makes sense, thanks!  One more question though, why is this fine?  I'd expect the code below to suffer from the same kind of issue as `join` based on your description, but it doesn't:

```js
	groupJoin<U, R>(joinSource: Queryable<U>, predicate: JoinPredicate<T, U>, selector: ZipSelector<T, Iterable<U>, R>)
	{
		return this.select(lValue => {
			const rValues = from(joinSource)
				.where(it => predicate(lValue, it));
			return selector(lValue, rValues);
		});
	}
```

**Comment by RyanCavanaugh** [comment]
Can you express that in terms of the simpler example? It took me a really long time to figure that one out 😐

**Comment by fatcerberus** [comment]
That's the thing, as far as I can tell that `groupJoin` implementation is literally the same case as your `foo1` above (return a `.select` that returns a `Query<R>`), but apparently there's a subtle difference because TS infers everything just fine.

**Comment by fatcerberus** [comment]
Okay so this triggers the circularity error too:
```ts
	except(...blacklists: Queryable<T>[])
	{
		const blacklist = new Set(from(blacklists).selectMany(it => it));
		return new Query(new WithoutSeq(this.sequence, blacklist));
	}
```

The common thread here seems to be `selectMany`.  I assume it's something to do with its mapper being typed as `Selector<T, Queryable<R>>`

**Comment by fatcerberus** [comment]
Anyway, all issues fixed by redefining `Queryable` as:
```ts
type Queryable<T> = T[] | ArrayLike<T> | Iterable<T>;
```

As `Query` is already iterable, this breaks the type cycle without losing any functionality. 😃
