### ISSUE TITLE
Add a new `type Awaitable<T> = T | PromiseLike<T>`

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/TypeScript#31394]
## Search Terms

- `awaitable`

## Suggestion

Add an awaitable type for values that will be awaited.

```ts
type Awaitable<T> = T | PromiseLike<T>;
```

This is based on [my question and a comment on StackOverflow](https://stackoverflow.com/questions/56021581/awaitable-type-in-typescript#comment98890590_56021581)

## Use Cases

Two use cases come in mind immediately:

1. A function accepts a callback that may either return a value synchronously, or may return a promise value. This will then probably be awaited.
2. This is more of a specific version of 1, but this would be the return type of `Promise.then()` / `Promise.catch` / `Promise.finally` callbacks.

Also, this type could replace all 1334 occurrences that come up when running `git grep '| Promise'` in the current TypeScript code base.

## Examples

Callback example:

```ts
async function logAnswer(getAnswer: () => Awaitable<number>): Promise<void> {
  const answer = await getAnswer();
  console.log(answer);
}

logAnswer(() => 42);
logAnswer(() => Promise.resolve(42));
```

Promise example:

```ts
Promise.resolve('Hello, world!').then(
  // This type annotation is silly. This is really just to show promise callbacks should accept `Awaitable<T>`.
  (hello): Awaitable<string> => {
    console.log(hello);
    return hello;
  },
);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
At first I didn't see the utility of this since *everything* in JavaScript is awaitable, but I just realized it's good for type inference:

```ts
type Awaitable<T> = T | PromiseLike<T>;

declare function foo<T>(callback: () => T): Promise<T>;
declare function bar<T>(callback: () => Awaitable<T>): Promise<T>;

const fun = () => Promise.resolve(812);
let food = foo(fun);  // Promise<Promise<number>>, which is not actually a thing.
let bard = bar(fun);  // Promise<number> - yes!
```

**Comment by fabiospampinato** [comment]
I think `Promisable` would be a better name than `Awaitable`. 

Since any value is awaitable in TS this name seems too generic to me, `Promisable` on the other hand says to me that the value could be actually a Promise (Technically `PromiseLike`, but `PromiseLikeable` or `PromiseableLike` sound awful to me).

**Comment by Vandivier** [comment]
I think Promisable and Awaitable are both fair, but I notice that ForAwaitable is another type under discussion and recommend that these two types are aligned regardless of the direction we go.

https://github.com/microsoft/TypeScript/issues/36153

**Comment by remcohaszing** [comment]
Some feedback from future self: I have been using [`Promisable`](https://github.com/sindresorhus/type-fest/blob/v0.13.0/source/promisable.d.ts) a lot. I really hope this will be a builtin type.

**Comment by remcohaszing** [comment]
This was added in #45350 and will be part of TypeScript 4.5.

**Comment by remcohaszing** [comment]
I misinterpreted it. It’s not the same.

**Comment by MuTsunTsai** [comment]
I've been using this exact definition in many of my projects for years. It will be great if this is built in.

**Comment by xiBread** [comment]
Is this relevant anymore given https://github.com/microsoft/TypeScript/issues/51841#issuecomment-1344953135?

**Comment by camsteffen** [comment]
Another name idea is `PromiseOr<T>`. The Dart language has the same concept but called `FutureOr`.

**Comment by remcohaszing** [comment]
This issue predates that comment and its references. I still think a builtin `Awaitable` type would be useful, but the TypeScript team is free to close this issue if they feel otherwise.

**Comment by camsteffen** [comment]
I know this is closed, but I want to highlight one important argument for this type that hasn't been raised.

The `Awaitable` type allows you to define function type that is "optionally `async`". Optionally async functions is a very widely useful pattern.

```typescript
type NumberCallback = () => Awaitable<number>;

// these both work!
const x: NumberCallback = () => 42;
const y: NumberCallback = async () => 42;
```

**Comment by RyanCavanaugh** [comment]
The merits of an individual utility type aren't really relevant since our position is "No new utility types, at all". If the type is useful for you, you should definitely write it in your project with the definition you'd like it to have.

**Comment by btoo** [comment]
@RyanCavanaugh thanks for the update - just for my own learning, is there a decision record rationalizing the "No new utility types, at all" position I can read up on?

**Comment by MuTsunTsai** [comment]
@btoo Not only that there's no such a record, they literally just add a new `NoInfer` utility type in v5.4 so I have no idea that he's talking about.

**Comment by ritschwumm** [comment]
@MuTsunTsai i wouldn't call NoInfer a utility type as you cannot implement it yourself in library code.

**Comment by MuTsunTsai** [comment]
@ritschwumm Your opinion is irrelevant. They literally called it "[The NoInfer Utility Type](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#the-noinfer-utility-type)".

**Comment by jinyongp** [comment]
I think it should have been like this... After all, Promise and PromiseLike are different types.

```ts
type PromiseLikable<T> = T | PromiseLike<T>
type Promisable<T> = T | Promise<T>;
```

Since we can't change `Promisable` at this point, we also need a type for `Promise`. [We're already using `Awaitable` internally in `vueuse`](https://github.com/vueuse/vueuse/blob/a9b49f5bf8ca87540bcd4bf24e8bfa39905bd15c/packages/shared/utils/types.ts#L68)

```ts
export type Awaitable<T> = Promise<T> | T
```
