### ISSUE TITLE
List of open source projects in/for Typescript?

### ISSUE THREAD

**Issue by thingista** [microsoft/TypeScript#31396]
_Apologies in advance, I am not sure this is the right place but I just can't find one (none is referenced [here](https://www.typescriptlang.org/community/index.html))._

We recently released to open source an internal framework we created in and for Typescript. It's a fairly ambitious new "feature" for TS (it's an RPC implementation basically).
As any open source project, it only makes sense if other teams get to know it, use it and maybe contribute back. Yet, we can't seem to find the right forum to tell the community about it (https://www.typescriptlang.org/community/index.html). Is there one?

(For reference the repo is [here](https://aiden.github.io/rpc_ts/))

**Comment by RyanCavanaugh** [comment]
At this point ~40% of JS devs are using TypeScript, so you can readily use whatever forum people use to tell each other about JS projects.

**Comment by dragomirtitian** [comment]
@RyanCavanaugh  is that 40% based on a survey or just anecdotal? Asking for a presentation.

**Comment by RyanCavanaugh** [comment]
https://2018.stateofjs.com/javascript-flavors/overview/

https://blog.npmjs.org/post/180868064080/this-year-in-javascript-2018-in-review-and-npms
