### ISSUE TITLE
SourceBuffer.appendBuffer() is missing overload for ArrayBufferView param in lib.d.ts

### ISSUE THREAD

**Issue by milkisevil** [Microsoft/TypeScript#314]
According to the [MediaSource Candidate Recommendation Spec](http://www.w3.org/TR/media-source/#widl-SourceBuffer-appendBuffer-void-ArrayBufferView-data), there are two `SourceBuffer.appendBuffer()` method overloads.  

[MSDN](http://msdn.microsoft.com/en-us/library/ie/dn255054(v=vs.85).aspx) only mentions the `ArrayBuffer` overload, even though this is later contradicted in the example code, further down on the same page: 
```javascript
videoSource.appendBuffer(new Uint8Array(xhr.response));
```
(`Uint8Array` indeed inherits from `ArrayBufferView`, not `ArrayBuffer`).

My tests show that Chrome 36 currently only works with `ArrayBufferView` (as per the MSDN example code).

### Anyway, long story short:
Here is the `lib.d.ts` change request, as supported by the spec, MSDN example code and Chrome 36:

Existing:
```javascript
interface SourceBuffer extends EventTarget {
    updating: boolean;
    appendWindowStart: number;
    appendWindowEnd: number;
    buffered: TimeRanges;
    timestampOffset: number;
    audioTracks: AudioTrackList;
    appendBuffer(data: ArrayBuffer): void;
    remove(start: number, end: number): void;
    abort(): void;
    appendStream(stream: MSStream, maxSize?: number): void;
}
```

Suggested:
```javascript
interface SourceBuffer extends EventTarget {
    updating: boolean;
    appendWindowStart: number;
    appendWindowEnd: number;
    buffered: TimeRanges;
    timestampOffset: number;
    audioTracks: AudioTrackList;
    appendBuffer(data: ArrayBuffer): void;
    appendBuffer(data: ArrayBufferView): void;
    remove(start: number, end: number): void;
    abort(): void;
    appendStream(stream: MSStream, maxSize?: number): void;
}
```

**Comment by zhengbli** [comment]
For some issue in my script the overload of "ArrayBufferView" shows up as "any". Will fix soon.

**Comment by zhengbli** [comment]
Related PR #2827
