### ISSUE TITLE
Alias resolution does not account for symbol merging

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#3140]
Many features do not work correctly when an alias is merged with other things:
```ts
import foo = A.bar;

namespace A {
    export namespace bar { } // completion is fine if this namespace is removed

    export import bar = baz.boo;

    export namespace baz {
        export var boo = 1;
    }
}
foo./*no number completion here*/
```
The issue here is that when resolveAlias is called on foo, it finds bar and stops because bar is a namespace. But it should be looking for bar as a value, and should know to keep going down the alias chain until it finds a value.

There are lots of places in the compiler where we call resolveAlias, and many of them are likely wrong. resolveAlias gets you the most immediate non-alias target (or sometimes even an alias), but it does not keep going to find the meaning the caller wants. To address this properly, we need more specific functions like resolveAliasAsValue, resolveAliasAsType, resolveAliasAsNamespace, etc.

I have discussed this at length with @vladima and @DanielRosenwasser. This is also the fundamental issue behind #2933.

**Comment by ahejlsberg** [comment]
I'm not sure about this. Effectively this would allow an alias to reference as many as three distinct symbols (vs. one symbol with as many as three distinct meanings). There are many places where we resolve an alias, expecting to get a single symbol returned for which we can check meanings. That would no longer be possible. I will give it some thought, but we should discuss more today.

**Comment by JsonFreeman** [comment]
We've decided that the compiler behavior is correct, and the spec should be clarified to imply this behavior.

**Comment by JsonFreeman** [comment]
Corresponding spec issue #3158
