### ISSUE TITLE
can't find moudle but DefinitelyTyped has already exist when target option above es5

### ISSUE THREAD

**Issue by SilverLeaves** [microsoft/TypeScript#31405]
with es6 or above
![图片](https://user-images.githubusercontent.com/31165554/57762973-18864180-7733-11e9-9717-27d87030b395.png)
with es5
![图片](https://user-images.githubusercontent.com/31165554/57763029-32278900-7733-11e9-8dc0-7b81853045d8.png)

**Comment by SilverLeaves** [comment]
https://github.com/postcss/postcss/issues/1270

**Comment by j-oliveras** [comment]
Configure `moduleResolution` with value `node`.

**Comment by DanielRosenwasser** [comment]
You want https://github.com/microsoft/TypeScript/issues/11434

**Comment by SilverLeaves** [comment]
@j-oliveras Thanks, it's work for me.

**Comment by SilverLeaves** [comment]
@DanielRosenwasser I will close this issue, It's been bothering me for a long time.。
