### ISSUE TITLE
Tuple with conditional optional type

### ISSUE THREAD

**Issue by Krzyrok** [microsoft/TypeScript#31409]
**Summary:** 
I can define in typescript that tuple contains optional elements, e.g. `let array: [string?];` - I can assign empty array. But can I combine this with conditional (generic) type: when type is defined then value should be set. Otherwise, value is disallowed. Or at least optional if not disallowed.

**TypeScript Version:** 
3.5.0-dev.20190515

**Search Terms:**
tuple with conditional optional type 

**Code**

```ts
interface A<T = never> {
    array: [
        [T] extends [never] ? never : T, // how to make this `never` as optional?
        // smth like this does not work:
        // [T] extends [void] ? never? : T1, //error: `JSDoc types can only be used inside of documentation comments`
        // T? // optional works here correctly
    ]
}

let test1: A<string>;
test1.array = ["some string"]
test1.array = [] // error: correctly

let test2: A;
test2.array = [ "" ] // error: correctly
test2.array = [ undefined ] // error: correctly
test2.array = [ null ] // error: correctly
test2.array = []; // error: INCORRECTLY! `Property '0' is missing in type '[]' but required in type '[never]'.`
```

**Expected behavior:**
I can assign empty array to `test2.array`. Even more - I cannot assign not empty array.

**Actual behavior:**
I cannot assign empty array. I cannot assign also array with some value. I have to use some other type and pass it explicitly, e.g. undefined:
```ts
interface A<T = never> {
    array: [
        [T] extends [never] ? undefined : T
    ]
}

let test1: A<string>;
test1.array = ["some string"]
test1.array = [] // error: correctly

let test2: A;
test2.array = [ "" ] // error: correctly
test2.array = [ undefined ] // error: correctly
test2.array = [ null ] // no error: is it correct?
test2.array = []; // error: INCORRECTLY! `Property '0' is missing in type '[]' but required in type '[never]'.`
```

[**Playground Link**](https://www.typescriptlang.org/play/#src=interface%20A%3CT%20%3D%20never%3E%20%7B%0D%0A%20%20%20%20array%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%5BT%5D%20extends%20%5Bnever%5D%20%3F%20never%20%3A%20T%2C%20%2F%2F%20how%20to%20make%20this%20%60never%60%20as%20optional%3F%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20smth%20like%20this%20does%20not%20work%3A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20%5BT%5D%20extends%20%5Bvoid%5D%20%3F%20never%3F%20%3A%20T1%2C%20%2F%2Ferror%3A%20%60JSDoc%20types%20can%20only%20be%20used%20inside%20of%20documentation%20comments%60%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20T%3F%20%2F%2F%20%22plain%22%20optional%20works%20here%20correctly%0D%0A%20%20%20%20%5D%0D%0A%7D%0D%0A%0D%0Alet%20test1%3A%20A%3Cstring%3E%3B%0D%0Atest1.array%20%3D%20%5B%22some%20string%22%5D%0D%0Atest1.array%20%3D%20%5B%5D%20%2F%2F%20error%3A%20correctly%0D%0A%0D%0Alet%20test2%3A%20A%3B%0D%0Atest2.array%20%3D%20%5B%20%22%22%20%5D%20%2F%2F%20error%3A%20correctly%0D%0Atest2.array%20%3D%20%5B%20undefined%20%5D%20%2F%2F%20error%3A%20correctly%0D%0Atest2.array%20%3D%20%5B%20null%20%5D%20%2F%2F%20error%3A%20correctly%0D%0Atest2.array%20%3D%20%5B%5D%3B%20%2F%2F%20error%3A%20INCORRECTLY!%20%60Property%20'0'%20is%20missing%20in%20type%20'%5B%5D'%20but%20required%20in%20type%20'%5Bnever%5D'.%60)

**Comment by AlCalzone** [comment]
```ts
interface A<T = never> {
    array: [T] extends [never] ? [] : [T]
}
```
works

**Comment by Krzyrok** [comment]
OK, it works. There are more generic types and first one can be defined and second one omitted (and more types). But your response apply also to this. 

```ts
interface A<T1 = never, T2 = never> {
    array: [T1] extends [never] // if T1 is not defined, then T2 is also not defined by sure
        ? []
        : [T2] extends [never]
            ? [T1]
            : [T1, T2]
}

let test1: A<string>;
test1.array = ["some string"]
test1.array = [] // error: correctly

let test2: A;
test2.array = [ "" ] // error: correctly
test2.array = [ undefined ] // error: correctly
test2.array = [ null ] // error: correctly
test2.array = [];

let test3: A<string, number>;
test3.array = ["some string", 55]
test3.array = [] // error: correctly
```

[playground](https://www.typescriptlang.org/play/#src=interface%20A%3CT1%20%3D%20never%2C%20T2%20%3D%20never%3E%20%7B%0D%0A%20%20%20%20array%3A%20%5BT1%5D%20extends%20%5Bnever%5D%0D%0A%20%20%20%20%20%20%20%20%3F%20%5B%5D%0D%0A%20%20%20%20%20%20%20%20%3A%20%5BT2%5D%20extends%20%5Bnever%5D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3F%20%5BT1%5D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3A%20%5BT1%2C%20T2%5D%0D%0A%7D%0D%0A%0D%0Alet%20test1%3A%20A%3Cstring%3E%3B%0D%0Atest1.array%20%3D%20%5B%22some%20string%22%5D%0D%0Atest1.array%20%3D%20%5B%5D%20%2F%2F%20error%3A%20correctly%0D%0A%0D%0Alet%20test2%3A%20A%3B%0D%0Atest2.array%20%3D%20%5B%20%22%22%20%5D%20%2F%2F%20error%3A%20correctly%0D%0Atest2.array%20%3D%20%5B%20undefined%20%5D%20%2F%2F%20error%3A%20correctly%0D%0Atest2.array%20%3D%20%5B%20null%20%5D%20%2F%2F%20error%3A%20correctly%0D%0Atest2.array%20%3D%20%5B%5D%3B%0D%0A%0D%0Alet%20test3%3A%20A%3Cstring%2C%20number%3E%3B%0D%0Atest3.array%20%3D%20%5B%22some%20string%22%2C%2055%5D%0D%0Atest3.array%20%3D%20%5B%5D%20%2F%2F%20error%3A%20correctly)

This below maybe would be better looking but I'm happy that above one is working
```ts
interface A<T1 = never, T2 = never> {
    array: [
        [T1] extends [never] ? never? : T1,
        [T2] extends [never] ? never? : T2
    ]
}
```

**Comment by Krzyrok** [comment]
I've encountered another problem with new solution - I need to call `reduce` on `array` to create `string` (`T1` and `T2` extends string keys of another class - so it should be possible).  

Simplified code: 
```ts
class GenericTupple<T1, T2> {
    tupple: [T1] | [T1, T2];

    getString() {
        // This one does not work :/
        // error: `Type 'string' is not assignable to type 'T1'.
        return this.tupple.reduce((final, prev) => `${final}.${prev}`, '');
    }
}
```
[playground](https://www.typescriptlang.org/play/#src=class%20GenericTupple%3CT1%2C%20T2%3E%20%7B%0D%0A%20%20%20%20tupple1%3A%20%5BT1%5D%20%7C%20%5BT1%2C%20T2%5D%3B%0D%0A%20%20%20%20tupple2%3A%20%5BT1%2C%20T2%5D%3B%0D%0A%20%20%20%20tupple3%3A%20%5BT1%2C%20T2%3F%5D%3B%0D%0A%0D%0A%20%20%20%20getString1()%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20This%20one%20does%20not%20work%20%3A%2F%0D%0A%20%20%20%20%20%20%20%20return%20this.tupple1.reduce((final%2C%20prev)%20%3D%3E%20%60%24%7Bfinal%7D.%24%7Bprev%7D%60%2C%20'')%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20to%20make%20it%20work%2C%20I%20need%20to%20cast%20to%20%60%5BT1%2C%20T2%3F%5D%60%60%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20return%20(this.tupple1%20as%20%5BT1%2C%20T2%3F%5D).reduce((final%2C%20prev)%20%3D%3E%20%60%24%7Bfinal%7D.%24%7Bprev%7D%60%2C%20'')%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20getString2()%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.tupple2.reduce((final%2C%20prev)%20%3D%3E%20%60%24%7Bfinal%7D.%24%7Bprev%7D%60%2C%20'')%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20getString3()%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.tupple3.reduce((final%2C%20prev)%20%3D%3E%20%60%24%7Bfinal%7D.%24%7Bprev%7D%60%2C%20'')%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

casting helps: 
```ts
return (this.tupple as [T1, T2?]).reduce((final, prev) => `${final}.${prev}`, '');
```

This results from original code with conditional types:
```ts
class A<T1, T2 = never, T3 = never> {
    array: [T2] extends [never]
        ? [T1]
        : [T3] extends [never]
            ? [T1, T2]
        : [T1, T2, T3]

    getString(): string {
        return this.array.reduce((final, prev) => `${final}.${prev}`, '');
    }
}
```
[playground](https://www.typescriptlang.org/play/#src=class%20A%3CT1%2C%20T2%20%3D%20never%2C%20T3%20%3D%20never%3E%20%7B%0D%0A%20%20%20%20array%3A%20%5BT2%5D%20extends%20%5Bnever%5D%0D%0A%20%20%20%20%20%20%20%20%3F%20%5BT1%5D%0D%0A%20%20%20%20%20%20%20%20%3A%20%5BT3%5D%20extends%20%5Bnever%5D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3F%20%5BT1%2C%20T2%5D%0D%0A%20%20%20%20%20%20%20%20%3A%20%5BT1%2C%20T2%2C%20T3%5D%0D%0A%0D%0A%20%20%20%20getString()%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.array.reduce((final%2C%20prev)%20%3D%3E%20%60%24%7Bfinal%7D.%24%7Bprev%7D%60%2C%20'')%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

Is it possible without casting? As I can see, incorrect `reduce` is detected:
`reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T, initialValue: T): T;` instead of `reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;`.

Should I create new issue?
