### ISSUE TITLE
Function Arguments not being inferred as a tuple

### ISSUE THREAD

**Issue by IllusionElements** [microsoft/TypeScript#31418]
**TypeScript Version:**  3.4.3

**Search Terms:** 

**Code**

```ts
  const toPromise = <T extends AnyFunctor>(f: T) => {
    return (...args: T extends (...a: infer R) => any ? R : any[]) => {
      return new Promise<ReturnType<T>>((resolve, reject) => {
        setImmediate(() => {
          try {
            const result = f(...args)
            resolve(result)
          } catch (e) {
            reject(e)
          }
        })
      })
    }
  }
```

**Expected behavior:**
```ts  
  T extends (...args: infer R) => any ? R : any[]
  f(...args) // this should not be an error
```
the type of args should be some sort of array type or any[] but it isn't being inferred as such
**Actual behavior:**
```ts 
Type T extends (...a: infer R) => any ? R : any[]' must have a '[Symbol.iterator]()' method that returns an iterator
```
**Playground Link:**  

**Related Issues:**

**Comment by dragomirtitian** [comment]
This is generally a limitation of conditional types that contain unresolved type parameters, you can't do much with them. You can easily write a fully type-safe version of `toPromise` if you don't use conditional types:

```ts
type AnyFunctor = (...a: any) => any;
const toPromise = <P extends any[], R>(f: (...a: P) => R) => {
    return (...args: P) => {
        return new Promise<R>((resolve, reject) => {
            setTimeout(() => {
                try {
                    const result = f(...args)
                    resolve(result)
                } catch (e) {
                    reject(e)
                }
            }, 1)
        })
    }
}

let fn = toPromise((a: number) => a + 1);
fn(1)
fn("1") //err
```

**Comment by jcalz** [comment]
This still seems buggy to me.  There should be some way to convince the compiler that the type is an array.  Otherwise you would need to abandon `Parameters<F>` entirely and just fall back to `any[]`.

**Comment by LorenzHenk** [comment]
Why was this issue closed? What is the outcome here?

I have a similar problem using `Parameters`, see [this typescript playground](https://www.typescriptlang.org/play/#code/MYewdgzgLgBADgJxAIwDYFMC2MC8MA8AKjOgB5TpgAmEMAFAHRMCGCA5hAFwzNgCeASlwA+Hv2F0AZgFcwwboQA0MJg1YduABVbNM6CgghFhQnKIDeMGACgroSCAwNUINoxbsIAgNzWAvtbWiCgYmHR0FNCcYNKYyOgIpqIATDAAVDCRUMoAjD5AA).
