### ISSUE TITLE
Eclipse link on typescriptlang.org is old and out of date

### ISSUE THREAD

**Issue by wayneparrott** [microsoft/TypeScript#31411]
On the typescriptlang.org page, the Eclipse link refers to the 2 year old out of date Palantir plugin. The most popular and active TypeScript tooling in the Eclipse community for the past year is https://marketplace.eclipse.org/content/codemix-3

![image](https://user-images.githubusercontent.com/5588978/57793989-41dda800-7708-11e9-869b-f863c2e19cd1.png)

**Comment by orta** [comment]
Closed with https://github.com/microsoft/TypeScript-Website/commit/ce9248ca0a4481d89d39826f015937746bcca5cf - will get updated on next deploy
