### ISSUE TITLE
Function arguments allow unknown properties when passed as variables

### ISSUE THREAD

**Issue by seanmcintyre** [microsoft/TypeScript#31412]
**TypeScript Version:**  3.5.0-dev.20190502

**Code**

```ts
export interface ThemeVar {
  light: string;
  dark: string;
}

type Theme = keyof ThemeVar | { name: keyof ThemeVar };

function themed(
  styles: TemplateStringsArray,
  ...themedVars: ThemeVar[]
): any[] {
  const processedThemedVars = themedVars.map(
    themedVar => ({ theme }: { theme: Theme }) =>
      typeof theme === 'string'
        ? themedVar[theme]
        : themedVar[theme.name],
  );

  return styles.map((string, i) => [
    string,
    processedThemedVars[i] || '',
  ]);
}

const colors = {
  dark: '#FFF',
  light: '#000',
  shouldFail: 0
}

const test = themed`
  color: ${colors}; // VALID ???
`;

const test2 = themed`
  color: ${{
    dark: '#FFF',
    light: '#000',
    shouldFail: 0 // INVALID
    // Object literal may only specify known properties,
    // and 'shouldFail' does not exist in type 'ThemeVar'.
  }};
`;

function themedFn(themeVar: ThemeVar) {
  return themeVar;
}

themedFn(colors); // VALID ???

themedFn({
  dark: '#FFF',
  light: '#000',
  shouldFail: 0 // INVALID
  // Object literal may only specify known properties,
  // and 'shouldFail' does not exist in type 'ThemeVar'.
});
```

**Expected behavior:**

Object literals passed as variables should fail with unknown properties just as they do when passed directly.

**Actual behavior:**

Object literals passed as variables allow for unknown properties.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/#src=export%20interface%20ThemeVar%20%7B%0D%0A%20%20light%3A%20string%3B%0D%0A%20%20dark%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Theme%20%3D%20keyof%20ThemeVar%20%7C%20%7B%20name%3A%20keyof%20ThemeVar%20%7D%3B%0D%0A%0D%0Afunction%20themed(%0D%0A%20%20styles%3A%20TemplateStringsArray%2C%0D%0A%20%20...themedVars%3A%20ThemeVar%5B%5D%0D%0A)%3A%20any%5B%5D%20%7B%0D%0A%20%20const%20processedThemedVars%20%3D%20themedVars.map(%0D%0A%20%20%20%20themedVar%20%3D%3E%20(%7B%20theme%20%7D%3A%20%7B%20theme%3A%20Theme%20%7D)%20%3D%3E%0D%0A%20%20%20%20%20%20typeof%20theme%20%3D%3D%3D%20'string'%0D%0A%20%20%20%20%20%20%20%20%3F%20themedVar%5Btheme%5D%0D%0A%20%20%20%20%20%20%20%20%3A%20themedVar%5Btheme.name%5D%2C%0D%0A%20%20)%3B%0D%0A%0D%0A%20%20return%20styles.map((string%2C%20i)%20%3D%3E%20%5B%0D%0A%20%20%20%20string%2C%0D%0A%20%20%20%20processedThemedVars%5Bi%5D%20%7C%7C%20''%2C%0D%0A%20%20%5D)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20colors%20%3D%20%7B%0D%0A%20%20dark%3A%20'%23FFF'%2C%0D%0A%20%20light%3A%20'%23000'%2C%0D%0A%20%20shouldFail%3A%200%0D%0A%7D%0D%0A%0D%0Aconst%20test%20%3D%20themed%60%0D%0A%20%20color%3A%20%24%7Bcolors%7D%3B%0D%0A%60%3B%0D%0A%0D%0Aconst%20test2%20%3D%20themed%60%0D%0A%20%20color%3A%20%24%7B%7B%0D%0A%20%20%20%20dark%3A%20'%23FFF'%2C%0D%0A%20%20%20%20light%3A%20'%23000'%2C%0D%0A%20%20%20%20shouldFail%3A%200%0D%0A%20%20%7D%7D%3B%0D%0A%60%3B%0D%0A%0D%0Afunction%20themedFn(themeVar%3A%20ThemeVar)%20%7B%0D%0A%20%20return%20themeVar%3B%0D%0A%7D%0D%0A%0D%0AthemedFn(colors)%3B%0D%0A%0D%0AthemedFn(%7B%0D%0A%20%20dark%3A%20'%23FFF'%2C%0D%0A%20%20light%3A%20'%23000'%2C%0D%0A%20%20shouldFail%3A%200%0D%0A%7D)%3B)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/29578

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.

**Comment by fatcerberus** [comment]
@seanmcintyre See https://github.com/basarat/typescript-book/blob/master/docs/types/freshness.md#freshness

**Comment by poseidonCore** [comment]
You may easily enforce type constraints for your inputs before they are consumed to catch this type of error:

```ts
const colors:ThemeVar = {
  dark: '#FFF',
  light: '#000',
  shouldFail: 0 // Will show error.
}

/* ERROR
Type '{ dark: string; light: string; shouldFail: number; }' is not assignable to type 'ThemeVar'.
  Object literal may only specify known properties, and 'shouldFail' does not exist in type 'ThemeVar'.
(property) shouldFail: number
*/
```

**Comment by seanmcintyre** [comment]
@poseidonCore This for a library, and while it's simple enough to do that internally, it's a bad developer experience to need to import `ThemeVar` and repeatedly specify it manually. The actual use case is a convenience utility within styled-components:

```tsx
const Text = styled.p<Props>`
  font: 300 1.5rem / 2rem ${fontFamily};
  letter-spacing: 0.01rem;
  margin-bottom: 1.5rem;

  ${themed`
    color: ${colors};
    ${antialias};
  `}
`;
```

**Comment by fatcerberus** [comment]
I understand the frustration but the excess properties *must* be allowed; it’s not just a convenience, but actually **required** in a structural typing system in order to be able to express subclasses at all.

Excess is checked for in direct object literals because extra properties there are nearly *always* an error, but in general, if `class D extends C` with some extra stuff then disallowing excess properties across the board would prevent objects of type `D` from being assignable to `C`.  Not very practical.

**Comment by fatcerberus** [comment]
Hmm... though the more I think about it, I do wonder if the freshness checks could safely be extended... I might have an idea for a proposal.  I’ll give it some thought.

**Comment by poseidonCore** [comment]
@seanmcintyre, if you are willing to export a class from a library and import it repeatedly elsewhere, then you should be willing to do the same for an interface/type used in that class. This particular practice and developer experience is common throughout most strictly typed languages.

I feel your frustration with this issue because I used to feel the same, but applying the simple pattern that I described is the only real way around this. As @RyanCavanaugh has pointed out, this is a language feature and so we have to work with this.
