### ISSUE TITLE
Conditional type on enum is not inferring type in switch statement

### ISSUE THREAD

**Issue by allevaton** [microsoft/TypeScript#31419]
**TypeScript Version:**  3.5.0-dev.20190515

**Search Terms:** conditional type, enum, value, switch, inference

**Code**

I have a conditional type mapping an enum descriptor to real types:

```ts
export type PropertyDataToValue<T extends Forge.PropertyData>
  = T extends Forge.PropertyData.NONE ? null | undefined
  : T extends Forge.PropertyData.BoolProperty ? boolean
  : T extends Forge.PropertyData.FloatProperty ? number
  : T extends Forge.PropertyData.IntegerProperty ? number
  : T extends Forge.PropertyData.UnsignedIntegerProperty ? number
  : T extends Forge.PropertyData.StringProperty ? string
  : T extends Forge.PropertyData.Vector3Property ? Vector3
  : T extends Forge.PropertyData.Vector4Property ? Vector4
  : never;
```

Later, I want to switch on property data types, like so:

```ts
function valueToPropertyData<T extends Forge.PropertyData>(
  propertyType: T,
  value: PropertyDataToValue<T>,
) {
  switch (propertyType) {
    case Forge.PropertyData.StringProperty:
      // Here: `value` is of type PropertyDataToValue<T>
      return;
  }
}
```

**Expected behavior:**
In the "case", I'd expect `value` to be inferred as a `string` type. Similarly for each conditional type.

**Actual behavior:**

In the "case", `value` is of type PropertyDataToValue<T>

**Playground Link:** 

[Playground URL](http://www.typescriptlang.org/play/#src=export%20declare%20namespace%20Forge%20%7B%0D%0A%20%20enum%20PropertyData%20%7B%0D%0A%20%20%20%20NONE%20%3D%200%2C%0D%0A%20%20%20%20BoolProperty%20%3D%201%2C%0D%0A%20%20%20%20IntegerProperty%20%3D%202%2C%0D%0A%20%20%20%20UnsignedIntegerProperty%20%3D%203%2C%0D%0A%20%20%20%20FloatProperty%20%3D%204%2C%0D%0A%20%20%20%20Vector3Property%20%3D%205%2C%0D%0A%20%20%20%20Vector4Property%20%3D%206%2C%0D%0A%20%20%20%20StringProperty%20%3D%207%2C%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Vector3%20%3D%20%7B%20x%3A%20number%3B%20y%3A%20number%3B%20z%3A%20number%20%7D%3B%0D%0Aexport%20type%20Vector4%20%3D%20%7B%20w%3A%20number%3B%20x%3A%20number%3B%20y%3A%20number%3B%20z%3A%20number%20%7D%3B%0D%0A%0D%0Aexport%20type%20PropertyDataToValue%3CT%20extends%20Forge.PropertyData%3E%0D%0A%20%20%3D%20T%20extends%20Forge.PropertyData.NONE%20%3F%20null%20%7C%20undefined%0D%0A%20%20%3A%20T%20extends%20Forge.PropertyData.BoolProperty%20%3F%20boolean%0D%0A%20%20%3A%20T%20extends%20Forge.PropertyData.FloatProperty%20%3F%20number%0D%0A%20%20%3A%20T%20extends%20Forge.PropertyData.IntegerProperty%20%3F%20number%0D%0A%20%20%3A%20T%20extends%20Forge.PropertyData.UnsignedIntegerProperty%20%3F%20number%0D%0A%20%20%3A%20T%20extends%20Forge.PropertyData.StringProperty%20%3F%20string%0D%0A%20%20%3A%20T%20extends%20Forge.PropertyData.Vector3Property%20%3F%20Vector3%0D%0A%20%20%3A%20T%20extends%20Forge.PropertyData.Vector4Property%20%3F%20Vector4%0D%0A%20%20%20%20%3A%20never%3B%0D%0A%0D%0Afunction%20valueToPropertyData%3CT%20extends%20Forge.PropertyData%3E(%0D%0A%20%20propertyType%3A%20T%2C%0D%0A%20%20value%3A%20PropertyDataToValue%3CT%3E%2C%0D%0A)%3A%20void%20%7B%0D%0A%20%20switch%20(propertyType)%20%7B%0D%0A%20%20%20%20case%20Forge.PropertyData.StringProperty%3A%0D%0A%20%20%20%20%20%20%2F%2F%20Here%3A%20%60value%60%20is%20of%20type%20PropertyDataToValue%3CT%3E%0D%0A%20%20%20%20%20%20return%3B%0D%0A%20%20%7D%0D%0A%7D)

**Related Issues:** 

I found this that seems related, but not quite:  #23578

**Comment by jack-williams** [comment]
Duplicate of #24085

**Comment by allevaton** [comment]
> Duplicate of #24085

Thanks for finding that, I'll close this.
