### ISSUE TITLE
With @angular/languageservice, non-Angular HTML file report lots of errors as they're parsed as TypeScript

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/TypeScript#31423]
**TypeScript Version:**  2.8.3 (@angular/languageservice 7.2.9)

**Search Terms:** Language Service HTML parsing errors

**Context:** I'm starting the typescript-language-server (delegating to tsserver) adding the @angular/language-service as plugin to typescript.
**When** opening an HTML that does **not** have any Angular-specific content
**Expected behavior:** the typescript-language-server ignores the file, not specific errors are reported
**Actual behavior:** a lot of errors are reported for such non Angular HTML, the errors are TypeScript parser errors. It seems like tsserver decides to parse this `.html` file as a `.ts` one.

**Comment by RyanCavanaugh** [comment]
TypeScript can't prevent editors or external components from asking it to parse HTML files as if they were TS. Whoever is doing this needs to stop.

**Comment by mickaelistria** [comment]
See https://github.com/angular/vscode-ng-language-service/issues/317#issuecomment-493149361 . I don't really understand everything here as I'm more on the plain consumer side and don't know any detail about how Typescript-language-server works; but with the linked comment and yours, it seems to me the issue is fully on @angular/language-service, isn't it?
If it is so, feel free to close this ticket.
