### ISSUE TITLE
Extending empty tuple in generic functions causes compiler to infer arrays as tuples

### ISSUE THREAD

**Issue by ipotuzhnov** [microsoft/TypeScript#31434]
**TypeScript Version:**  3.4.5

**Search Terms:**
empty tuple, type inference, generic function

**Code**
Basically I'm writing a generic function with dynamic type mapping. I think this use case is pretty common for database drivers and JSON validators and I found some related issues. There is a workaround and I want to confirm whether it is intended behavior or a bug.
```ts
interface TypeMap { STRING: string; NUMBER: number;}
type MapTypes<T> = {
  [P in keyof T]: T[P] extends keyof TypeMap ? TypeMap[T[P]] : never
};

declare function fromArray<T extends ReadonlyArray<keyof TypeMap>>(
  types: T, params: MapTypes<T>): void;

fromArray(['STRING', 'NUMBER', 'STRING'], ['abc', 123, 'xyz']);  // ok
// the default behavior is to infer types in array as type union
fromArray(['STRING', 'NUMBER', 'STRING'], ['abc', '123', 'xyz']);  // no error
fromArray(['STRING', 'NUMBER', 'STRING'] as const, ['abc', '123', 'xyz']);  // error

declare function fromTuple<T extends([] | ReadonlyArray<keyof TypeMap>)>(
  types: T, params: MapTypes<T>): void;

fromTuple(['STRING', 'NUMBER', 'STRING'], ['abc', 123, 'xyz']);  // ok
// T extends([]|MyType) cases the compiler to infer array as tuple
fromTuple(['STRING', 'NUMBER', 'STRING'], ['abc', '123', 'xyz']);  // error
fromTuple(['STRING', 'NUMBER', 'STRING'] as const, ['abc', '123', 'xyz']);  // error
```

**Expected behavior:**
Type of the array literal is inferred as array of union type.

**Actual behavior:**
Type of the array literal is inferred as tuple when `T extends []|MyType` is used in generic function.
I'd prefer it to be the expected behavior, but I didn't find any tests for that use case.

**Playground Link:** 
[You can see the same behavior in the playground](https://www.typescriptlang.org/play/#src=interface%20TypeMap%20%7B%20STRING%3A%20string%3B%20NUMBER%3A%20number%3B%7D%0D%0Atype%20MapTypes%3CT%3E%20%3D%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20keyof%20TypeMap%20%3F%20TypeMap%5BT%5BP%5D%5D%20%3A%20never%0D%0A%7D%3B%0D%0A%0D%0Adeclare%20function%20fromArray%3CT%20extends%20ReadonlyArray%3Ckeyof%20TypeMap%3E%3E(%0D%0A%20%20types%3A%20T%2C%20params%3A%20MapTypes%3CT%3E)%3A%20void%3B%0D%0A%0D%0AfromArray(%5B'STRING'%2C%20'NUMBER'%2C%20'STRING'%5D%2C%20%5B'abc'%2C%20123%2C%20'xyz'%5D)%3B%20%20%2F%2F%20ok%0D%0A%2F%2F%20the%20default%20behavior%20is%20to%20infer%20types%20in%20array%20as%20type%20union%0D%0AfromArray(%5B'STRING'%2C%20'NUMBER'%2C%20'STRING'%5D%2C%20%5B'abc'%2C%20'123'%2C%20'xyz'%5D)%3B%20%20%2F%2F%20no%20error%0D%0AfromArray(%5B'STRING'%2C%20'NUMBER'%2C%20'STRING'%5D%20as%20const%2C%20%5B'abc'%2C%20'123'%2C%20'xyz'%5D)%3B%20%20%2F%2F%20error%0D%0A%0D%0Adeclare%20function%20fromTuple%3CT%20extends(%5B%5D%20%7C%20ReadonlyArray%3Ckeyof%20TypeMap%3E)%3E(%0D%0A%20%20types%3A%20T%2C%20params%3A%20MapTypes%3CT%3E)%3A%20void%3B%0D%0A%0D%0AfromTuple(%5B'STRING'%2C%20'NUMBER'%2C%20'STRING'%5D%2C%20%5B'abc'%2C%20123%2C%20'xyz'%5D)%3B%20%20%2F%2F%20ok%0D%0A%2F%2F%20T%20extends(%5B%5D%7CMyType)%20cases%20the%20compiler%20to%20infer%20array%20as%20tuple%0D%0AfromTuple(%5B'STRING'%2C%20'NUMBER'%2C%20'STRING'%5D%2C%20%5B'abc'%2C%20'123'%2C%20'xyz'%5D)%3B%20%20%2F%2F%20error%0D%0AfromTuple(%5B'STRING'%2C%20'NUMBER'%2C%20'STRING'%5D%20as%20const%2C%20%5B'abc'%2C%20'123'%2C%20'xyz'%5D)%3B%20%20%2F%2F%20error)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/13151
https://github.com/microsoft/TypeScript/issues/22679

**Related PR**
This PR includes a similar test, but it there is no test for empty tuple and array combination https://github.com/microsoft/TypeScript/pull/26676

**Comment by ahejlsberg** [comment]
This is working as intended. We only infer tuple types when the contextual type is or contains a tuple-like type.

**Comment by ipotuzhnov** [comment]
@ahejlsberg Great, thank you for confirming.

Can I add some tests for this behavior then? I wasn't able to find anything similar by grepping tests directory (`grep 'extends \[\]' -r tests/`).
There are [tests that check a combination of two tuples](https://github.com/microsoft/TypeScript/blob/master/tests/baselines/reference/genericRestParameters3.js#L51-L54), but not a combination of a tuple and array.

**Comment by ahejlsberg** [comment]
Yes, it is the intended behavior. See https://github.com/microsoft/TypeScript/issues/27179#issuecomment-422911925 for the recommended pattern.

**Comment by ipotuzhnov** [comment]
Thank you for the link. I think I've seen that issue, but didn't go through all comments.
