### ISSUE TITLE
Very bad performance of TS and JS Language Features

### ISSUE THREAD

**Issue by sarneeh** [microsoft/TypeScript#31431]
Issue Type: <b>Performance</b>

I struggle with a very bad performance (I mean mostly intellisense) in VS Code recently so I started to dig down to find the root cause of the problem.

What I found was:
- performance issues go away when I set `javascript.validate.enable` to `false`
- performance issues go away when I rename my `jsconfig.json` to `tsconfig.json`

What's weird is that the problems occur only when using the `jsconfig.json` configuration file. Here's how it looks like:

```js
{
  "compilerOptions": {
    "baseUrl": "./",
    "target": "es5",
    "paths": {
      "@page/*": ["src/page/*"],
      "@panel/*": ["src/panel/*"],
      "@shared/*": ["src/shared/*"]
    },
    "experimentalDecorators": true
  },
  "exclude": ["node_modules", ".next"]
}
```

When I rename the same file to `tsconfig.json` - the problems disappear.

The difference I in both approaches was visible in the TS Server Log - using `jsconfig.json`, the TS Server parsed ~400 more files than using the `tsconfig.json` version.

I attached the logs for specific configurations.

[jsconfig.json](https://github.com/microsoft/vscode/files/3169525/tsserver.log)
[tsconfig.json](https://github.com/microsoft/vscode/files/3169526/tsserver.log)

**Additional info**

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4326)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.61GB (3.97GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>

Extensions disabled

**Comment by mjbvz** [comment]
@sarneeh Thanks. When using a tsconfig, I believe that js files will not be processes (unless you set `allowJS`) so that would explain why perf improves when you rename the jsconfig to tsconfig

Can you try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions). The new TS release fixes a number of performance bugs that could be causing this.

Also, can you share your project so we can try reproducing this on our side?

**Comment by sarneeh** [comment]
@mjbvz Unfortunately this is a private project and I can't share it with you. But I'll try to follow your instructions and do whatever I can to help you investigate this issue.

**Comment by sarneeh** [comment]
I've just tried the newest `typescript` version and there's a HUGE difference in performance in my case. I've also reverted back to a `jsconfig.json` and there's no lag at all. 

I'll give myself a few days of work to find out how does it behave in the long-term to confirm that this solution solves this problem. Do you want this issue to be opened or can I close it if everything will work fine?

**Comment by fatcerberus** [comment]
AFAIK the only difference between `jsconfig.json` and `tsconfig.json` is that the former implies `allowJs: true` by default.

**Comment by sarneeh** [comment]
@fatcerberus Yes. I've learned about that after creating this issue. Also, it did make sense that it made VSCode performance even worse (as it parsed much more files than the `tsconfig`, as my project has only `js` files). Anyways, I guess that this and many other issues involving VSCode intellisense performance may be related to `typescript` itself (as upgrading to the `@next` version helped me to get rid of this problem completely).

**Comment by DanielRosenwasser** [comment]
Sounds like the issue has been addressed - it's likely a result of the regression we saw with `styled-components`.

**Comment by sarneeh** [comment]
@DanielRosenwasser Yes. Thank you, everyone, for help in my problem :smiley:
