### ISSUE TITLE
[Feature request] allow sourceMap with inlineSourceMap at same time

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#31442]
## Suggestion

>  TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.

allow sourceMap , inlineSourceMap exists at same time

when use `tsc`

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment]
A source map can only be embedded inside the output file (`inlineSourceMap`) or be a external file (`sourceMap`). It can not be both simultaneously.

**Comment by bluelovers** [comment]
@j-oliveras 
i mean when `inlineSourceMap` exists, then auto ignore `sourceMap`

don't not throw error for stop emit
