### ISSUE TITLE
3.5.0-dev.* breaks ts-loader from webpack

### ISSUE THREAD

**Issue by konpikwastaken** [microsoft/TypeScript#31447]
**TypeScript Version:**  3.5.0-dev.20190517

**Search Terms:**
webpack, ts-loader, incremental build

**Description:**
/edit: strikethrough what I thought was related issue

Doing a normal build with typescript@next as 3.4.5 has issues with `--incremental` flag and when sources get regenerated.  It appears we cannot move to 3.5.0 as it breaks our webpack bundling with the following errors for each ts(x) file encountered during the bundle process.

```
[tsl] ERROR
      TS5074: Option '--incremental' can only be specified using tsconfig, emitting to single file or when option `--tsBuildInfoFile` is specified.
```

Attempted with ts-loader versions
- 5.4.6
- 6.0.0

**Expected behavior:**
Error should not occur, as no error occurs in typescript@3.4.5

**Related Issues:** 
- Regarding new "incremental" flag from TS 3.4: TypeStrong/ts-loader#913
- ~Provide --build/--incremental APIs for build tools: Microsoft/TypeScript#29978~

**Comment by sheetalkamat** [comment]
Fixed already by  #30513

**Comment by konpikwastaken** [comment]
@sheetalkamat does this mean the linked issues are unrelated or does this mean that this is a ts-loader issue? Unsure why it would be a ts-loader issue as this occurs when upgrading typescript.

**Comment by konpikwastaken** [comment]
here's a minimal repro

https://github.com/konpikwastaken/broken-example-ts-loader-tsc

**Comment by konpikwastaken** [comment]
Still repro for `3.5.0-rc` && `3.5.0-dev.20190522`.

**Comment by sheetalkamat** [comment]
@konpikwastaken That's the issue with ts-loader where in it doesn't indicate that  compiler options are from config file. if you specify tsbuildinfo file path in your config file the error should go away

**Comment by konpikwastaken** [comment]
I see - this is change that ts-loader will need to implement it seems. Great, I'll open a bug there & reference this.

Also confirmed that specifying `tsbuildinfo` in my tsconfig file directly is indeed a workaround.
