### ISSUE TITLE
TS 1.4 compiler slower?

### ISSUE THREAD

**Issue by scriby** [Microsoft/TypeScript#3145]
I was going to upgrade a project at work from TS 1.1.0-1 to TS 1.4, and was surprised at the difference in compile times. Here are the results from our codebase (we're using grunt-ts to perform the compilation, so the output is generated by it).

```
TS 1.1.0-1: TypeScript compilation complete: 8.31s for 744 typescript files

TS 1.3: TypeScript compilation complete: 8.04s for 744 typescript files

TS 1.4.1: TypeScript compilation complete: 15.71s for 744 typescript files

1.5.0-beta: Errors out (accessing args from anon functions). I didn't want to take the time to fix these up, but by wall clock time it seems to be about the same speed as 1.4.1 before it prints the error.
```

I know there's not much you can do without seeing the exact codebase (which I'd have to jump through some hoops to share). But I'm curious if it's expected that performance with TS 1.4 would be basically halved, or if perhaps there's some special feature of our codebase that's causing things to be slower than expected.

One other data point I can share is that when grunt-ts does a conditional recompile (it passes only the changed files to the compiler based on a file watch), there is not a noticeable speed difference between 1.1.0-1 and 1.4.1. So, it may be related simply to the volume of files, or features of a particular file or set of files which is not included during the conditional recompile.

**Comment by ahejlsberg** [comment]
The 1.4 compiler may be up to 20% slower than the 1.3 compiler (and 1.5 should be about the same as 1.4), but 100% slower is certainly out of the ordinary. Could you try to compile with the `-diagnostics` compiler option and report back the results for 1.3 and 1.4.1? Also, because the 1.3 compiler is smaller than the 1.4.1 compiler it generally loads faster (fewer lines of code to load and JIT), so if your build system is set up to run the command-line compiler multiple times on small sets of files instead of once on all files, the load/JIT time may be a factor.

Hard to diagnose this further without access to the code base.

**Comment by scriby** [comment]
TS 1.4.1:

```
time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics

Files:             761
Lines:          147076
Nodes:          640058
Identifiers:    234462
Symbols:         86645
Types:           43289
Memory used:   336362K
Parse time:      2.79s
Bind time:       0.78s
Check time:      7.81s
Emit time:       3.32s
Total time:     14.71s

real	0m14.891s
user	0m15.648s
sys	0m0.411s
```

TS 1.3:

```
time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics
Files:             761
Lines:          147026
Nodes:          630842
Identifiers:    238140
Symbols:         86655
Types:           42117
Memory used:   424855K
Parse time:      1.88s
Bind time:       0.98s
Check time:      2.84s
Emit time:       2.49s
Total time:      8.19s

real	0m8.385s
user	0m8.901s
sys	0m0.413s
```

If someone on the TS team would be interested in seeing the actual codebase, I can start asking internally about providing it. I suspect that my company may require an NDA to be signed to receive the code, and I'm not sure whether that would be an issue or not.

**Comment by vladima** [comment]
Out of curiosity, what version of node are you using?

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, May 13, 2015 at 7:13 PM -0700, "scriby" <notifications@github.com<mailto:notifications@github.com>> wrote:


TS 1.4.1:

time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics

Files:             761
Lines:          147076
Nodes:          640058
Identifiers:    234462
Symbols:         86645
Types:           43289
Memory used:   336362K
Parse time:      2.79s
Bind time:       0.78s
Check time:      7.81s
Emit time:       3.32s
Total time:     14.71s

real    0m14.891s
user    0m15.648s
sys 0m0.411s


TS 1.3:

time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics
Files:             761
Lines:          147026
Nodes:          630842
Identifiers:    238140
Symbols:         86655
Types:           42117
Memory used:   424855K
Parse time:      1.88s
Bind time:       0.98s
Check time:      2.84s
Emit time:       2.49s
Total time:      8.19s

real    0m8.385s
user    0m8.901s
sys 0m0.413s


If someone on the TS team would be interested in seeing the actual codebase, I can start asking internally about providing it. I suspect that my company may require an NDA to be signed to receive the code, and I'm not sure whether that would be an issue or not.

-

**Comment by scriby** [comment]
```
node --version
v0.12.2
```

**Comment by vladima** [comment]
If it is possible can you roll back to older version of node (i.e. 0.10.35 or so) and try to run the experiment again?

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, May 13, 2015 at 7:38 PM -0700, "scriby" <notifications@github.com<mailto:notifications@github.com>> wrote:


node --version v0.12.2

-

**Comment by scriby** [comment]
I think you're on to something.

```
> node --version
v0.10.36
```

TS 1.4.1:

```
>time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics

Files:             761
Lines:          147076
Nodes:          640058
Identifiers:    234462
Symbols:         86645
Types:           43289
Memory used:   311628K
Parse time:      2.06s
Bind time:       0.71s
Check time:      2.85s
Emit time:       2.05s
Total time:      7.67s

real	0m7.837s
user	0m7.526s
sys	0m0.369s
```

TS 1.3:

```
> time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics

Files:             761
Lines:          147026
Nodes:          630842
Identifiers:    238140
Symbols:         86655
Types:           42117
Memory used:   285450K
Parse time:      1.62s
Bind time:       1.15s
Check time:      3.29s
Emit time:       4.58s
Total time:     10.64s

real	0m10.795s
user	0m10.424s
sys	0m0.441s
```

**Comment by ahejlsberg** [comment]
Welcome to the strange world of JavaScript optimizing JITs. We have pointed this regression out to the V8 team and I believe they're looking into it. This appears to be an excellent test case.

Sent from my Windows Phone
________________________________

**Comment by tinganho** [comment]
Maybe you can try iojs(>2.0) too then? To see if the issue is already fixed?

**Comment by vladima** [comment]
for the reference this is [issue 3817](https://code.google.com/p/v8/issues/detail?id=3817) in the v8 issue tracker

**Comment by scriby** [comment]
```
> node --version
v2.0.1
```

TS 1.4.1:

```
> time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics

Files:             761
Lines:          147076
Nodes:          640058
Identifiers:    234462
Symbols:         86645
Types:           43289
Memory used:   425004K
Parse time:      2.43s
Bind time:       0.90s
Check time:      4.25s
Emit time:       2.38s
Total time:      9.95s

real	0m10.295s
user	0m10.454s
sys	0m0.521s
```

TS 1.3:

```
> time find app -name "*.ts" -print0 | xargs -0 node node_modules/typescript/bin/tsc --sourcemap --module amd -noImplicitAny -t ES5 --outDir build/develop/ -diagnostics

Files:             761
Lines:          147026
Nodes:          630842
Identifiers:    238140
Symbols:         86655
Types:           42117
Memory used:   325238K
Parse time:      1.82s
Bind time:       0.71s
Check time:      3.46s
Emit time:       2.98s
Total time:      8.97s

real	0m9.187s
user	0m9.592s
sys	0m0.390s
```

To summarize:

```
             Node 0.10.36 | Node 0.12.2 | io.js 2.0.1
TS 1.3           10.64    |     8.19    |    8.98
TS 1.4.1          7.67    |    14.71    |    9.95
```

**Comment by vladima** [comment]
good to see io.js in a good shape. when I've filed the original bug in January its perf metrics were similar to node 0.12

**Comment by scriby** [comment]
I think we'll just roll back to node v0.10.x for now, since we're not using anything new in v0.12.x.

Thanks for the assistance. I'll go ahead and close the issue, but feel free to re-open if you'd like to use it for tracking or have me run some tests against different compiler / node combinations.
