### ISSUE TITLE
TS Completion is slow when opening another large file

### ISSUE THREAD

**Issue by octref** [microsoft/TypeScript#31452]
Version: 1.34.20-insider
Commit: 57b550c559b945eb9d871dbf2b2e4cb9e31e2551
Date: 2019-05-10T17:35:18.558Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.5.0

---

Try to trigger completion on this file:

```ts
const ts = require('typescript')

ts.|
```

If I only have this file open, completion will be fast.
If I have another large JS file open, completion will be slow.

Repro:

- `mkdir test && cd test`
- `yarn add typescript`
- Have the above code, do a completion. 🐇
- Open `node_modules/typescript/lib/typescript.js`, do a completion. 🐌

**Comment by mjbvz** [comment]
I confirmed that the tsserver seems to be taking a very long time with a `geterr` request in this case. VS Code attempts to cancel the request but the server continues processing it. Here's a quick profile after triggering `geterr`:

<img width="695" alt="Screen Shot 2019-05-17 at 3 46 59 PM" src="https://user-images.githubusercontent.com/12821956/57959938-0a632d00-78bb-11e9-9ce8-c0f76c026e08.png">
