### ISSUE TITLE
Provide info diagnostics/quick fixes for JSDoc/TS mismatches

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31451]
```ts
/**
 * @param foo {number} desc
 */
function stuff(bar: string) {
    // ...
}
```

We should consider popping up an info diagnostic in the editor when a parameter name/type mismatches that of the JSDoc, along with a quick fix. We already do this in `checkJs`.

**Comment by ajafff** [comment]
Duplicate of #11378?

**Comment by sandersn** [comment]
Yep. Duplicate of #11378
