### ISSUE TITLE
Unsoundness in coercion from object to boolean

### ISSUE THREAD

**Issue by uhyo** [microsoft/TypeScript#31464]
**TypeScript Version:**  3.4.3, typescript@3.5.0-dev.20190518

**Search Terms:** unsound coercion object boolean

**Code**

```ts
const obj: { toFixed: unknown } = 0;
// val has type "123"
const val = obj && "123";
console.log(val.slice()); // <- runtime error!
```

**Expected behavior:**
Compile error.

**Actual behavior:**
This code compiles and causes a runtime error when run.

TypeScript assumes that any value with object type (except `{}`) is truthy, but it's not *true* as illustrated above. If one of `0`, `""`, `false` or `0n` is assignable to an object type, it should not be considered truthy.

**Playground Link:** https://www.typescriptlang.org/play/#src=const%20obj%3A%20%7B%20toFixed%3A%20unknown%20%7D%20%3D%200%3B%0A%2F%2F%20val%20has%20type%20%22123%22%0Aconst%20val%20%3D%20obj%20%26%26%20%22123%22%3B%0Aconsole.log(val.slice())%3B%0A%0A%0A

**Related Issues:** #18196 (fixed by #27157)

**Comment by lll000111** [comment]
> Unsoundness in coercion from object to boolean

Isn't the unsoundness the very first line

    const obj: { toFixed: unknown } = 0;

Coercing a primitive (number) to an object?

**Comment by shqld** [comment]
At a single glance it seems TypeScript should distinguish `number` from `Number` instance?

E.g. when we annotate some object as Number specifically, TS should regard it as an object with some props & methods but otherwise as if it'd be a real primitive same as other languages.

**Comment by MartinJohns** [comment]
> Coercing a primitive (number) to an object?

It is not coercing a primitive to an object. The type `{ toFixed: unknonw }` does not constrain to objects. It just says whatever is passed has a `toFixed` property.

If you want to enforce having an object, then you can make use of the `object` type:

    const obj1: { toFixed: unknown } & object = 0; // Does not compile
    const obj2: { toFixed: unknown } & object = { toFixed: 0 }; // Does compile

**Comment by lll000111** [comment]
@MartinJohns 

> t just says whatever is passed has a toFixed property.

Which means it is an object. Primitives don't have properties. 

Do we really need to discuss the very basics of JS?

**Comment by MartinJohns** [comment]
I was not precise enough. It doesn't has to be a property, but anything with the name 'toFixed', and numbers have a function named like that.

    const n = 0;
    console.log(n.toFixed);

**Comment by lll000111** [comment]
@MartinJohns 

> but anything with the name 'toFixed',

OPs example has a **primitive** number!!

**Comment by MartinJohns** [comment]
My example has a primitive number as well. I just omitted the type information.

**Comment by lll000111** [comment]
Which is coerced to an object.

```
0.toFixed
VM121:1 Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by RyanCavanaugh** [comment]
@lll000111 take it down a notch; we don't need to be condescending to have a discussion.

Anyway, as to the OP: Types written as `{ p: T; }` are *not* constrained to be `object`-like. There is plenty of code that operates well on things that have `length` and are indexable (*including* strings) or things that have a `toString` (*including* numbers). This does create a soundness gap for the falsy primitive values, but it's not with any palatable solutions.
