### ISSUE TITLE
Negative numbers are not treated like type literals

### ISSUE THREAD

**Issue by parzh** [microsoft/TypeScript#31461]
**TypeScript Version:**  3.4.5

**Search Terms:** negative keys key

**Code**

```ts
type Value = {
    [-1]: any;
};
```

**Expected behavior:**
No compiler errors.

**Actual behavior:**
Compiler error: `A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol'`

**Playground Link:** [playground link][1]

**Related Issues:** #31460

  [1]: https://www.typescriptlang.org/play/#src=type%20Values%20%3D%20%7B%0D%0A%09%5B-1%5D%3A%20any%3B%0D%0A%7D%3B%0D%0A

**Comment by parzh** [comment]
While this error might seem sensible, notice how [this very similar code][1] does **not** produce any errors:

```ts
type Values = {
	[1]: any;
};
```

  [1]: https://www.typescriptlang.org/play/#src=type%20Values%20%3D%20%7B%0D%0A%09%5B1%5D%3A%20any%3B%0D%0A%7D%3B%0D%0A

**Comment by kitsonk** [comment]
And [this works as well](https://www.typescriptlang.org/play/#src=let%20MinusOne%3A%20-1%20%3D%20-1%3B%0D%0A%0D%0Atype%20Values%20%3D%20%7B%0D%0A%09%5B1%5D%3A%20any%3B%0D%0A%09%5BMinusOne%5D%3A%20any%3B%0D%0A%7D%3B%0D%0A):

```ts
const MinusOne = -1;

type Values = {
	[1]: any;
	[MinusOne]: any;
};
```

**Comment by andrewbranch** [comment]
I'm assigning myself since it's related to #31460, but if someone else had plans for it, feel free to take it back
