### ISSUE TITLE
New Website Logo: Basware

### ISSUE THREAD

**Issue by jaria** [Microsoft/TypeScript#3146]
Please fill the following out:

- Name: Basware
- Homepage url: www.basware.com
- Brand Guidelines/Licensing: 
- Logo: http://www.basware.com/elqNow/elqRedir.htm?ref=http://www.basware.com/sites/default/files/upload/basware_logo_rgb.jpg

**Comment by jonathandturner** [comment]
Please submit the logo as a png or svg

**Comment by jaria** [comment]
![basware_logo](https://cloud.githubusercontent.com/assets/12392987/8693624/2612b3ee-2ae1-11e5-8a5d-dd5a4473e250.png)

Png uploaded.
