### ISSUE TITLE
TypeChecker#getSymbolsInScope returns undefined symbol

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#31467]
This may be more a question and maybe not be a bug... why does the following code return the `undefined` symbol? Is there something special about it? I noticed this when providing `(ts.SymbolFlags as any)["All"]` as the `meaning` argument to `TypeChecker#getSymbolsInScope`... seems to have the `undefined` symbol in every case I've tried.

**Side question:** do you think there's a sensible default for `meaning` in `getSymbolsInScope`? Maybe `ts.SymbolFlags.Value`? Or is filtering by meaning always useful? What do you think about making `meaning` an optional parameter that defaults internally to `ts.SymbolFlags.All`? Thanks!

**TypeScript Version:**  3.5.0-dev.20190518

**Search Terms:** getSymbolsInScope undefined

**Code**

```ts
import * as ts from "typescript";

console.log(ts.version);

const testFilePath = "/file.ts";
const testFileText = `let t: number;`;
const testSourceFile = ts.createSourceFile(testFilePath, testFileText, ts.ScriptTarget.Latest, true);
const program = getProgram();
const typeChecker = program.getTypeChecker();

console.log(typeChecker.getSymbolsInScope(testSourceFile, ts.SymbolFlags.Property));

function getProgram() {
    const options: ts.CompilerOptions = { target: ts.ScriptTarget.ES5 };
    const host: ts.CompilerHost = {
        fileExists: filePath => filePath === testFilePath,
        directoryExists: dirPath => dirPath === "/",
        getCurrentDirectory: () => "/",
        getDirectories: () => [],
        getCanonicalFileName: fileName => fileName,
        getNewLine: () => "\n",
        getDefaultLibFileName: () => "",
        getSourceFile: filePath => filePath === testFilePath ? testSourceFile : undefined,
        readFile: filePath => filePath === testFilePath ? testFileText : undefined,
        useCaseSensitiveFileNames: () => true,
        writeFile: () => {}
    };
    return ts.createProgram({
        options,
        rootNames: [testFilePath],
        host
    });
}
```

**Expected behavior:** Outputs empty array?

**Actual behavior:**

Outputs:

```
[ SymbolObject {
    flags: 33554436,
    escapedName: 'undefined',
    checkFlags: 0,
    declarations: [],
    type:
     TypeObject {
       checker: [Object],
       flags: 32768,
       id: 7,
       intrinsicName: 'undefined',
       objectFlags: 131072 } } ]
```

**Comment by RyanCavanaugh** [comment]
`undefined` can be legally shadowed (😲) so it needs to go into a special global symbol table

**Comment by dsherret** [comment]
Hah, I did not know that!

```ts
(function () {
    const undefined = 5;
    console.log(undefined);
})();
```

Somewhat reminds me of these: https://twitter.com/jaredpar/status/981604285036208128 https://twitter.com/jaredpar/status/1115312773083189248?lang=en

Ok, thanks @RyanCavanaugh!

**Comment by dsherret** [comment]
Ah, ok... so `undefined` is a property of the global object (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#Description) and that's why it shows up when doing `ts.SymbolFlags.Property` (I was still wondering about that point).
