### ISSUE TITLE
Starter of TS

### ISSUE THREAD

**Issue by kadoyatsukasa** [microsoft/TypeScript#31463]
how can i start with TypeScript？

**Comment by scvnathan** [comment]
https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

**Comment by ruhelaanurag** [comment]
Doesn't looks like this question belongs here. 
There are resources available(handbook) on official TypeScript website and also a free course available on coursera.

https://www.typescriptlang.org/docs/handbook/basic-types.html
https://courses.edx.org/courses/course-v1:Microsoft+DEV273x+1T2019a/course/
