### ISSUE TITLE
Suggestion: output of JSXChildren

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#31462]
## Search Terms

-   JSX
-   JSXChildren
-   JSX code generation

## Suggestion

-   [The signature of createElement in React is React.createElement(type, props,...children).](https://reactjs.org/docs/react-api.html#createelement) [While React.createElement always transforms JSXChildren into an array if there are more than one child.](https://github.com/facebook/react/blob/31487dd82e82ef62243806b2e76b23a6fb21d0bc/packages/react/src/ReactElement.js#L336-L352)
-   [The signature of createElement in Vue is createElement(type, props,children).](https://vuejs.org/v2/guide/render-function.html#createElement-Arguments) [The children parameter have to be an array.](https://github.com/vuejs/vue/blob/06d4ad40a49e85e678ce2aa8fac0ecf2176f86e2/src/core/vdom/vnode.js#L6)

Therefore, it is better to allow the output of JSXChildren to be configured.

There will of course be a lot more details when we get started for real, but these sketches should give us a rough idea of the design.

We could add an option to tsconfig.json such as compilerOptions.JSXChildren:

```
compilerOptions.JSXChildren : "classic" | "onechild" | "array"
```

| "classic"             | "onechild"                   | "array"          |
| --------------------- | ---------------------------- | ---------------- |
| what tsc is doing now | what React is actually doing | what Vue accepts |

## Use Cases

It will improve compatibility with some JSX libraries.

## Examples

input

```tsx
const App = () => {
    return (
        <div className="app">
            <main>
                <header />
                <section />
                <footer />
            </main>
        </div>
    );
};
```

compilerOptions.JSXChildren : "classic"

```js
const App = () => {
    return React.createElement(
        "div",
        { className: "app" },
        React.createElement(
            "main",
            null,
            React.createElement("header", null),
            React.createElement("section", null),
            React.createElement("footer", null),
        ),
    );
};
```

compilerOptions.JSXChildren : "onechild"

```js
const App = () => {
    return React.createElement(
        "div",
        { className: "app" },
        React.createElement("main", null, [
            React.createElement("header", null),
            React.createElement("section", null),
            React.createElement("footer", null),
        ]),
    );
};
```

compilerOptions.JSXChildren : "array"

```js
const App = () => {
    return React.createElement("div", { className: "app" }, [
        React.createElement("main", null, [
            React.createElement("header", null),
            React.createElement("section", null),
            React.createElement("footer", null),
        ]),
    ]);
};
```

Please ignore the format style :)

## Checklist

My suggestion meets these guidelines:

-   [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
-   [x] This wouldn't change the runtime behavior of existing JavaScript code
-   [x] This could be implemented without emitting different JS based on the types of the expressions
-   [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
-   [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by magic-akari** [comment]
For consistency, maybe `compilerOptions.jsxChildren` is better.

Discussion is welcome.

**Comment by RyanCavanaugh** [comment]
We'd probably expose this via a configuration type in the `JSX` namespace rather than a compiler option (since it's the framework that decides, not the program author). I think React is actually thinking about moving to Vue's behavior anyway.

**Comment by magic-akari** [comment]
Sounds great. But does it mean `emitting different JS based on the types of the expressions`?

**Comment by magic-akari** [comment]
Related issue #34547

**Comment by plusgut** [comment]
Another related issue https://github.com/microsoft/TypeScript/issues/30918

**Comment by magic-akari** [comment]
Close issue by #39199 .
