### ISSUE TITLE
TypeScript type metadata symbols and interfaces

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#3148]
I have some questions about the metadata symbols that are added by the TypeScript compiler to the generated JavaScript code when using the `--emitDecoratorMetadata` flag and [decorators](https://github.com/Microsoft/TypeScript/issues/2249).

I'm aware of:

- `"design:type"` [The serialized form of the type of ?] the decorator target
- `"design:paramtypes"` [The serialized form of ?] the return type of the decorator target if it is a function type, undefined otherwise.
- `"design:returntype"` A list of [serialized ?] types of the decorator target’s arguments if it is a function type, undefined otherwise.

Is the `"design:name"` symbol is available?

- `"design:name"` The name of the decorator target

I'm hoping to find a symbol that will add the [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) that I need. I think I'm looking for something that is not available, something like `design:implementedtypes` or `design:interfaces`. 

What I want to be able to do is be to get the names of the implemented interfaces.

    @somedecorator
    class Ninja implements INinja, IWarrior {
       // ...
    }

The metadata that I would like to be added by the compiler is something would be  something like the following:

    Reflect.metadata("design:implementedtypes", ["INinja","IWarrior "]);

As an alternative (I don't know if that is the case) it would be OK for me if the `"design:type"` added the interfaces as well.

    Reflect.metadata("design:type", ["Ninja", "INinja","IWarrior"]);

Also, are the serialized form of the types emitted? 

    reflect.metadata("design:type", ["Ninja"]);

or the actual types?

    reflect.metadata("design:type", [Ninja]);
Thanks

**Comment by DanielRosenwasser** [comment]
Hey @remojansen, I'm not as familiar with decorators as some others on the team, but perhaps [this comment](https://github.com/Microsoft/TypeScript/issues/2305#issuecomment-78383163) may answer your question to some extent. If not, I can try to ping a few others from the team to help answer.

**Comment by remojansen** [comment]
@DanielRosenwasser thanks for the help. 

I had a few questions and now I have some answers:

- Are strings used as the serialized forms of a type? No, and interfaces are serialized to `Object`.
- Also, are the serialized form of the types emitted? Yes but serialization does not work as I expected. If somebody reach this page wondering the same please note that [the types are not serialized into strings](https://github.com/jonathandturner/brainstorming/blob/master/README.md#c3-type-serialization).

But I still have some questions:

- Is the `"design:name"` symbol is available? This will return a string I assume?

And I would like to get more people to think about this issue because in the issue above (https://github.com/Microsoft/TypeScript/issues/2305) I see that @giancarloa said:

> it all looks great EXCEPT the interfaces... don't you think it's a serious problem that there's no way to query metadata for interfaces? in my case for example I would never ever do the first example I gave above. Instead I would always do the second which is **program against an interface**.

Maybe more developer feel this way and we need to consider some solution. Maybe the solution is a new metadata symbols like the one I was making up in my original question `"design:interfaces"`. I understand that you cannot return the interface as an object so maybe we instead of `"design:interfaces"` need string versions of all the currently available symbols, something like "design:stringified_type" which would generate `["Ninja", "INinja","IWarrior"]` for

    @somedecorator
    class Ninja implements INinja, IWarrior {
       // ...
    }

Thanks

**Comment by DanielRosenwasser** [comment]
> Is the "design:name" symbol is available? This will return a string I assume?

The [types of our decorators](https://github.com/Microsoft/TypeScript/blob/ee6263d4767ec282dff4a1c76a4588fd60a60070/src/lib/core.d.ts#L1169) may help describe what you're interested in.

* For a property, you'll get the name of the property.
* For a method/accessor, you'll get the name of the method/accessor.
* For a parameter in a method/accessor, you'll get the name of the method/accessor.

@rbuckton can feel free to correct me.

> Maybe more developer feel this way and we need to consider some solution.

I think the following https://github.com/Microsoft/TypeScript/issues/3015#issuecomment-98852421 is relevant.

**Comment by rbuckton** [comment]
@remojansen We are considering adding more type information. My current proposal can be found [here](https://gist.github.com/rbuckton/4b8df4908aad49aac212).

**Comment by remojansen** [comment]
@rbuckton thanks for letting me know. I took a look to your proposal and I found what I need:
```
  /**
    * Implemented interfaces.
    */
  implements?: Type[];
```
Do you have an open issue somewhere that I can follow to keep an eye on the updates regarding this topic? 

Thanks

**Comment by DanielRosenwasser** [comment]
Hey @remojansen, I think the plan is to convert @rbuckton's proposal into a formal issue; not sure when we'll be doing that, so maybe we'll leave this open for now.

**Comment by mhegazy** [comment]
looks like this is already covered here: https://github.com/Microsoft/TypeScript/issues/3015#issuecomment-98852421
