### ISSUE TITLE
[Minor bug] Comment merging should be joined by a newline

### ISSUE THREAD

**Issue by sw-yx** [microsoft/TypeScript#31492]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** https://github.com/microsoft/TypeScript/search?p=4&q=comments+is%3Aissue&type=Issues

**Code**

this code:

```ts
/**
 * Lorem Ipsum
 * 
 * dolor sit amet
 */

/**
 * some comments here
 *
 * more comments here
 */
const mycode = () => 3
```

**Expected behavior:**

should generate these comments inside vscode/the language service (sorry i dont exactly know what the right terminology is) with a newline (or maybe even some separator):

```
Lorem Ipsum

dolor sit amet 

some comments here

more comments here
```

**Actual behavior:**

no newline

```
Lorem Ipsum

dolor sit amet some comments here

more comments here
```

**Playground Link:** https://www.typescriptlang.org/play/#src=%2F**%0D%0A%20*%20Lorem%20Ipsum%0D%0A%20*%20%0D%0A%20*%20dolor%20sit%20amet%0D%0A%20*%2F%0D%0A%0D%0A%2F**%0D%0A%20*%20some%20comments%20here%0D%0A%20*%0D%0A%20*%20more%20comments%20here%0D%0A%20*%2F%0D%0Aconst%20mycode%20%3D%20()%20%3D%3E%203

**Related Issues:**

first discussed on twitter https://twitter.com/atcb/status/1130336156522934273 and this was the main issue that introduced comment merging https://github.com/microsoft/TypeScript/pull/27978 and it seems like there is some form of whitespace trimming that is probably the cause https://github.com/microsoft/TypeScript/pull/28848

**Comment by sandersn** [comment]
We no longer join multiple comments, so this bug can't happen.

**Comment by sw-yx** [comment]
well thats one way to resolve it :)
