### ISSUE TITLE
Classes transpiled down to es5 can't extend native es6 classes

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#31509]
**TypeScript Version:**  3.4.1

**Search Terms:** extend class transpiled es5

**Code**

```ts
// Part 1
function extender ( myClass ) {
  return class extends myClass { }
}

// Part 2
const Extended = extender ( class {} );
new Extended ();
```

The following code:

- **Works**, if transpiled to es6+
- **Works**, if transpiled to es5 too
- **Doesn't work**, if the first part gets transpiled to es5 while the second part is still using es6. The first part may very well be a class decorator exported by some third-party package. The problem is that when transpiled down to es5 classes can't extend native classes.

**Playground Link:**  N/A, the playground is too limited for this

**Comment by DanielRosenwasser** [comment]
I believe this is a duplicate of #17088.

**Comment by fabiospampinato** [comment]
It looks like it is, thanks.
