### ISSUE TITLE
Omit in 3.5 breaking Discriminated Unions

### ISSUE THREAD

**Issue by aczekajski** [microsoft/TypeScript#31501]
**TypeScript Version:**  3.5.0-rc, 3.5.0-dev.20190521

**Search Terms:** discriminated union omit, tagged union omit

**Code**

```ts
// discriminated union
type Union =
    | { type: 'A', a: 'a', c: string }
    | { type: 'B', b: 'b', c: string };

// various Omit definitions
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>; // new omit copied from TS 3.5
type OmitBetter<T, K extends keyof any> = T extends any ? Pick<T, Exclude<keyof T, K>> : never;
type OmitBetterStrict<T, K extends keyof T> = T extends any ? Pick<T, Exclude<keyof T, K>> : never;

// Omit use-cases with Discriminated Union (DU)
type UnionMod = Omit<Union, 'whatever'>; // DU gets broken
type UnionMod2 = OmitBetter<Union, 'a'>; // DU remains unchanged
type UnionMod3 = OmitBetter<Union, 'a'>; // DU is still a DU but without field 'a'
type UnionMod4 = OmitBetterStrict<Union, 'c'>; // DU is still a DU but without common field 'c'
type UnionMod5 = OmitBetterStrict<Union, 'a'>; // error, because 'a' is not a common field of DU

// regular Omit use-cases (they all work properly)
type Regular = Omit<{ readonly a: 'a'; b?: 'b'; c: 'c'; }, 'whatever' | 'c'>;
type Regular2 = OmitBetter<{ readonly a: 'a'; b?: 'b'; c: 'c'; }, 'whatever' | 'c'>;
type Regular3 = OmitBetterStrict<{ readonly a: 'a'; b?: 'b'; c: 'c'; }, 'c'>;
```

**Expected behavior:**
`Omit` type should properly omit fields from objects but discriminated unions should still be discriminated unions. The expected behaviour is observed when using `Omit` from [type-zoo](https://github.com/pelotom/type-zoo) package. The same approach was also proposed by the Microsoft member here: https://github.com/microsoft/TypeScript/issues/28791#issuecomment-443520161.

**Actual behavior:**
Built-in `Omit` type which is being introduced in TypeScript 3.5 "merges" discriminated unions. When omitting field `c` from 
```ts
{ type: 'A', a: 'a', c: string } |
{ type: 'B', b: 'b', c: string }
```
the resulting type should be equivalent to
```ts
{ type: 'A', a: 'a' } |
{ type: 'B', b: 'b' }
```
but with Omit@3.5, we get
```ts
{ type: 'A' | 'B' }
```
which is no longer a discriminated union.

According to _Design Meeting Notes, 4/15/2019_ (https://github.com/microsoft/TypeScript/issues/30947), the resolution about making `Omit` stricter was based on "not worth breaking half the usages of `Omit` in the wild". When looking at ["type Omit" search results](https://github.com/DefinitelyTyped/DefinitelyTyped/search?p=6&q=%22type+Omit%22&unscoped_q=%22type+Omit%22), some of them also use the conditional type trick to distribute `Omit` over discriminated union. Following the same "not breaking the usages in the wild" principle, it might be a better idea to change the built-in `Omit` into the version with `T extends any ? ... : never`. Especially since it does not break the regular use-cases.

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=%2F%2F%20discriminated%20union%0D%0Atype%20Union%20%3D%0D%0A%20%20%20%20%7C%20%7B%20type%3A%20'A'%2C%20a%3A%20'a'%2C%20c%3A%20string%20%7D%0D%0A%20%20%20%20%7C%20%7B%20type%3A%20'B'%2C%20b%3A%20'b'%2C%20c%3A%20string%20%7D%3B%0D%0A%0D%0A%2F%2F%20various%20Omit%20definitions%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20any%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%20%2F%2F%20new%20omit%20copied%20from%20TS%203.5%0D%0Atype%20OmitBetter%3CT%2C%20K%20extends%20keyof%20any%3E%20%3D%20T%20extends%20any%20%3F%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%20%3A%20never%3B%0D%0Atype%20OmitBetterStrict%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20T%20extends%20any%20%3F%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%20%3A%20never%3B%0D%0A%0D%0A%2F%2F%20Omit%20use-cases%20with%20Discriminated%20Union%20(DU)%0D%0Atype%20UnionMod%20%3D%20Omit%3CUnion%2C%20'c'%3E%3B%20%2F%2F%20DU%20gets%20broken%0D%0Atype%20UnionMod2%20%3D%20OmitBetter%3CUnion%2C%20'a'%3E%3B%20%2F%2F%20DU%20remains%20unchanged%0D%0Atype%20UnionMod3%20%3D%20OmitBetter%3CUnion%2C%20'a'%3E%3B%20%2F%2F%20DU%20is%20still%20a%20DU%20but%20without%20field%20'a'%0D%0Atype%20UnionMod4%20%3D%20OmitBetterStrict%3CUnion%2C%20'c'%3E%3B%20%2F%2F%20DU%20is%20still%20a%20DU%20but%20without%20common%20field%20'c'%0D%0Atype%20UnionMod5%20%3D%20OmitBetterStrict%3CUnion%2C%20'a'%3E%3B%20%2F%2F%20error%2C%20because%20'a'%20is%20not%20a%20common%20field%20of%20DU%0D%0A%0D%0A%2F%2F%20regular%20Omit%20use-cases%20(they%20all%20work%20properly)%0D%0Atype%20Regular%20%3D%20Omit%3C%7B%20readonly%20a%3A%20'a'%3B%20b%3F%3A%20'b'%3B%20c%3A%20'c'%3B%20%7D%2C%20'whatever'%20%7C%20'c'%3E%3B%0D%0Atype%20Regular2%20%3D%20OmitBetter%3C%7B%20readonly%20a%3A%20'a'%3B%20b%3F%3A%20'b'%3B%20c%3A%20'c'%3B%20%7D%2C%20'whatever'%20%7C%20'c'%3E%3B%0D%0Atype%20Regular3%20%3D%20OmitBetterStrict%3C%7B%20readonly%20a%3A%20'a'%3B%20b%3F%3A%20'b'%3B%20c%3A%20'c'%3B%20%7D%2C%20'c'%3E%3B%0D%0A)

**Comment by dragomirtitian** [comment]
`Pick` isn't distributed either. Making all library types distributed can have severe performance implications. This was also discussed here: https://github.com/microsoft/TypeScript/issues/28339

**Comment by RyanCavanaugh** [comment]
All possible definitions of `Omit` have certain trade-offs; we've chosen one we think is the best general fit and can't really change it at this point without inducing a large set of hard-to-pinpoint breaks.

**Comment by unional** [comment]
@RyanCavanaugh it seems like this is not about choosing which implementation.

Discriminated unions are still broken because the fact that they mapped type are not distributed.

All of the types mentioned by @aczekajski does not work when the mapped type is used.

See #31899

**Comment by tantaman** [comment]
A workaround for this is to use mapped types.

E.g., 
```
type RemoveNameField<Type> = {
  [Property in keyof Type as Exclude<Property, "name">]: Type[Property];
};
```

instead of `Omit<Type, 'name'>`

[TS Playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAdgcwCoHsDWUC8UA3lMgIYC2EAXFAOQDOCKqtANFADaYDGpwimZDWQBXcgCMI8dt0HAIyYPRqMkaKAF8AUKEhQAcmMnwsuAsTKUatURKltOPPgKEkjU9gDdSHEdTd28JpaOuDQpviwTGgRAD4G7iY4IbrQAKrIXLzyACYRBADy5IjAADym7LRZzoK0AHwhHBDAUKQ0GdW5+UQkFP42iQ7evv4AjMFaTS3i7ZlOXTiRFn3Wtsa0E6lQAEoQ5JieEAAy8y4AYogQHDnlYXVLWlBQANoACvCYkPCgUChQ2BAQJgAGZQdBhVr0KAAUQAHtxfDkIKV3p8pKB2AAiTouTF1AC6NHBkDeHy+oHxAG4tBpqaE9B15hA8jgAEyRXb7Q4nbLnS7Xco4Op0qZQbizTrM0zs8y9Kx0Nb2Lw+Pw0ca0ybNKA5CVMlnYGVESz9RXwDa0oA) based on #39556

**Comment by micdah** [comment]
Found another workaround by using the fact that `T extends K` is applied per-member of a union, so we can actually define a re-usable `OmitUnion<T, K>` type which can omit any number of members

```typescript
interface Dog { type: 'dog', name: string, barks: boolean }
interface Cat { type: 'cat', name: string, meows: boolean }
type Pet = Dog | Cat

type PetWithoutName = Omit<Pet, 'name'>

// Cannot because PetWithoutName is reduced to {type: 'dog' | 'cat'}
let unnamedPet:PetWithoutName = { type: 'dog', barks: true }


type OmitUnion<T, K extends keyof any> = T extends any ? Omit<T, K> : never
// Uses the fact that `T extends K` is applied to _each union member_ of T in-turn

type PetWithoutName2 = OmitUnion<Pet, 'name'>
let unnamedPet2:PetWithoutName2 = { type: 'dog', barks: true }
```


So instead of ending up with the type `{ type: 'dog' | 'cat' }` when applying `Omit<Pet, 'name'>` we instead want `Omit<Dog, 'name'> | Omit<Cat, 'name'>` which we can get by using `T extends any` which ensures we apply `Omit<T, K>`on each member of the union, rather than the entire union.

It's kind of a hack - but I like that it enables us to have a generic re-usable `OmitUnion<T, K>`

**Comment by unional** [comment]
@micdah yes, that is the way to get around it in `type-zoo` and `type-plus`

https://github.com/unional/type-plus/blob/main/ts/object/omit.ts
https://github.com/pelotom/type-zoo/blob/master/types/index.d.ts#L26
https://github.com/microsoft/TypeScript/issues/28339#issuecomment-463577347

**Comment by micdah** [comment]
> @micdah yes, that is the way to get around it in `type-zoo` and `type-plus`
> 
> 
> 
> https://github.com/unional/type-plus/blob/main/ts/object/omit.ts
> 
> https://github.com/pelotom/type-zoo/blob/master/types/index.d.ts#L26
> 
> https://github.com/microsoft/TypeScript/issues/28339#issuecomment-463577347
> 
> 

Cool was not aware of those - but nice seeing multiple people coming up with the same workaround 👍

**Comment by IchordeDionysos** [comment]
This is a dangerous API design.

If someone designs an interface (as a non-discriminate union), dependents use it with Omit.
Then later, the interface changes and becomes a discriminate union.

There is a good chance that this will lead to software bugs, given the nature of the discriminate union is not propagated down to dependents (e.g. special handling of the discriminate union type for all cases).

People aren't aware of these specifics, and keeping this in mind, figuring out all of its consequences is a hellscape of complexity.

<details><summary>Problematic example code:</summary>
<p>

```typescript
export type Item = ItemTopic | ItemUserGeneratedTopic;

export interface ItemTopic {
  identifier: LearningPlanItemIdentifier;
  type: 'topic';
  item: TopicIdentifier;
}

export interface ItemUserGeneratedTopic {
  identifier: LearningPlanItemIdentifier;
  type: 'userGeneratedTopic';
  item: UserGeneratedTopicIdentifier;
}

// Results in a type error
const full: Item = {
  identifier: new LearningPlanItemIdentifier('foo'),
  type: 'topic',
  item: new UserGeneratedTopicIdentifier('sdf'),
};

// Does NOT result in a type error and in software bugs.
const partial: Omit<Item, 'identifier'> = {
  type: 'topic',
  item: new UserGeneratedTopicIdentifier('sdf'),
};

```

</p>
</details>

**Comment by RyanCavanaugh** [comment]
See https://github.com/microsoft/TypeScript/wiki/FAQ#add-a-key-constraint-to-omit
