### ISSUE TITLE
Parser doesn’t parse BinaryExpression with comma operator as JSXExpression

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#31510]
**TypeScript Version:**  9052804576cefbc239df539e3ddad522568cfb71

**Search Terms:** JSX comma expression BinaryExpression

Filing for discoverability. Discovered while working on #25487 that we don't parse either of these correctly:

```tsx
const x = <div x={p, p} />
const y = <div>{p, p}</div>
```

In both cases, we should parse a JSXExpression whose `expression` is a BinaryExpression with a CommaToken as the operator. Both Flow and Babel treat this as valid syntax (they call the expression a "SequenceExpression").

- [JSX Spec](https://facebook.github.io/jsx/)
- [Babel playground](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAHjAvDAPAEwJYDd6IN5wA0cAvjAPQB8AUKJLAJ5IwAU1MqmWNHHBh8Eu1TkuNAJTVa4aDABezdNkr9SKUcqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.4.4&externalPlugins=)
- [Flow playground](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzACUBTAQw3wC4wzsBPMAXjAG8BfAbkxwNubZceeQgA8BAHgAmASwBuYUU1ZkANGXZhgAPmF8AXpNlztrUatHsJwY9qA)
- [TypeScript playground](https://typescript-play.js.org/?jsx=2#code/CYUwxgNghgTiAEA3W8BKIpgC4C55QDsBPAbgChRJYECoBbEAZwAdMEApAZQA14BvMvCHwAlgSwgYAMzbwAkuJhjGIsAFEIIBuMb9Bwg8BGI8hUvqEBfMtbJkwAewKMs8AB7wAvPAA8RxO6efMwANPDMlvAA9AB89k4u8ERevv4xwWERPlFpQA)

**Comment by andrewbranch** [comment]
This seems to be an inconsistency between the JSX spec and implementation. The spec says that an [AssignmentExpression](https://tc39.github.io/ecma262/#prod-AssignmentExpression) is valid in those positions, which is exactly what we do. However, it seems they're allowing any [Expression](https://tc39.github.io/ecma262/#prod-Expression) there, since that's what covers the comma operator. I don't think this is the same parser they still use, but I found [some evidence](https://github.com/facebookarchive/esprima/blob/fb-harmony/esprima.js#L7072) showing that indeed, JSX expressions were filled with `parseExpression()`.

**Comment by weswigham** [comment]
https://github.com/babel/babel/issues/8604

**Comment by andrewbranch** [comment]
Ah, yep. Good call.
