### ISSUE TITLE
Better outlining spans for prototype method assignments

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31516]
Keywords: outline outlining spans navtree nav tree folding prototype

From: https://twitter.com/code/status/1130893425090256897

```ts
x.prototype.initialize = function() {};
y.prototype.initialize = function() {};
z.prototype.initialize = function() {};
```

Expected:

Outlining spans for navtree are something like

```
x.prototype.initialize
y.prototype.initialize
z.prototype.initialize
```

or potentially

![image](https://user-images.githubusercontent.com/972891/58128321-34bf2e00-7bcc-11e9-8fe6-bdf8bc450431.png)

Actual:

![image](https://user-images.githubusercontent.com/972891/58128316-2ffa7a00-7bcc-11e9-9a72-d23efbb85b49.png)

**Comment by xiata** [comment]
![image](https://user-images.githubusercontent.com/1434508/58187096-27fe1100-7c84-11e9-9107-3b3c79caae0b.png)

**Comment by dragomirtitian** [comment]
FYI: I have started working on this. 

@DanielRosenwasser I think the idea of doing `x.initialize` is actually less appealing than nesting the attached elements (as @xiata  suggests) from a UI perspective. 

I think I get get your version (`x.initalize`) done faster as from my digging, the changes required don't seem to be very big.

The nesting approach is a bit more complex, and we should consider several issues:

1. Do we change the type (ie the icon) of the item to class if there are any `prototype` assignments to a function ? I think yes.
2. Do we add a separate node for the original function as a constructor ? I think yes, in order not to mix any nested constructor functions with member functions.
3. What do we do about members directly attached to the function (not the prototype). Currently these are presented as  standalone elements that are not in any way related to the function they are getting attached to: 
![image](https://user-images.githubusercontent.com/8193316/59190799-52a60000-8b86-11e9-900b-227aac604ee2.png)

I would like to nest these under the function as well as long as I am doing work in this area.

**Comment by DanielRosenwasser** [comment]
@dragomirtitian looks like you're on the right track.

So to answer questions

1. Yes
2. I guess I'd have to see what that looks like - it'd be confusing to have two `Foo`s unless one was nested under the other.
3. Is there a way to mark one of those methods as static? I think they should be nested, but displayed the same as a static method in a class.

**Comment by dragomirtitian** [comment]
@DanielRosenwasser Yup, making good progress 😊

2. What I meant was creating an extra node under the function. With two cases: 
a. When there are prototype assignments, we consider this to be a class, so we add a `constructor` node with function locals nested under this:
![image](https://user-images.githubusercontent.com/8193316/59220371-7a6c8680-8bcd-11e9-9214-c39d46ac2908.png)
b. When there are no prototype assignments, we leave this as a function, maybe add a `locals` node for definitions actually inside the function, although this new `locals` node would be inconsistent with other functions. 
![image](https://user-images.githubusercontent.com/8193316/59220914-bce29300-8bce-11e9-85ec-0b4f861438df.png)
 Although I am not sure mixing the locals with the attached members would be a good experience either:
![image](https://user-images.githubusercontent.com/8193316/59221376-c7515c80-8bcf-11e9-8d71-d815e0503cb9.png)

3. There does not currently seem to be a visual distinction between static and non-static class members so they would not be visually different. Might be worth considering adding a static member icon in the future:
![image](https://user-images.githubusercontent.com/8193316/59219413-19dc4a00-8bcb-11e9-8ab4-74953c693b21.png)

**Comment by DanielRosenwasser** [comment]
Any thoughts @mjbvz 	@amcasey 	?

**Comment by amcasey** [comment]
@DanielRosenwasser I don't believe VS has a specific outline view.  Do you happen to know if the VS navbars are backed by the same command(s)?

**Comment by dragomirtitian** [comment]
@amcasey Yes the navbar is backed by the same commands (the changes I already made show up in both the outline view and the nav bar). 

Just to be clear what you mean by "I don't believe VS has a specific outline view", you mean that the same views are used for both navbars and outline, right ? Not that VS Code does not have an outline view by default, because I disabled all my extensions and I still have the outline view shown in the pictures above.

**Comment by amcasey** [comment]
@dragomirtitian my questions were about Visual Studio, rather than VS Code.  I'd be pleased to learn that (regular) VS has an Outline view, but I'm not aware of one.

**Comment by dragomirtitian** [comment]
@amcasey Wops, misread that, my bad.

**Comment by Taxman972** [comment]
Is there any chance to implement this in Visual Studio Code ?

**Comment by jessetrinity** [comment]
> Is there any chance to implement this in Visual Studio Code ?

VSCode already uses the navtree so you should see the corresponding changes whenever the shipped version updates appropriately. Alternatively, you can [experiment with the latest version of TypeScript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) yourself.

**Comment by DanielRosenwasser** [comment]
There's actually an extension to use the nightlies now: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by Taxman972** [comment]
@jessetrinity @DanielRosenwasser, Thank you very much.
