### ISSUE TITLE
Generic property of class not type-checked if the generic is `{}`

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#31513]
**TypeScript Version:**  3.4.1

**Search Terms:** generic empty object accepts anything

**Code**

```ts
class X<Y extends {[key: string]: number}> {
	x: Y
}

class A extends X<{}> {
	x = {a: "not a number!"}
}

class B extends X<{}> {
	x = "Whatever I want!"
}

```

**Expected behavior:**

I expect to be able to use `{}` to mean an object without any keys, not `any`.

**Actual behavior:**

I can define `x` to be whatever I want and there's no type error.

**Playground Link:**  [playground link](https://www.typescriptlang.org/play/#src=class%20X%3CY%20extends%20%7B%5Bkey%3A%20string%5D%3A%20number%7D%3E%20%7B%0D%0A%09x%3A%20Y%0D%0A%7D%0D%0A%0D%0Aclass%20A%20extends%20X%3C%7B%7D%3E%20%7B%0D%0A%09x%20%3D%20%7Ba%3A%20%22not%20a%20number!%22%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20X%3C%7B%7D%3E%20%7B%0D%0A%09x%20%3D%20%22Whatever%20I%20want!%22%0D%0A%7D%0D%0A)

**Related Issues:**

**Comment by fatcerberus** [comment]
The type you want is `object`.  `{}` is a structural type which means “anything structurally compatible an empty object”—i.e. everything that isn’t `null` or `undefined`.
