### ISSUE TITLE
Convert to class declaration suggested but not available

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#31528]
**TypeScript Version:**  3.4.3

**Search Terms:**

- 80002
- convert to class quick fix

**Code**

I assume the bug has something to do with the length of the file so I won't include full source here. But you can see the file for which it happens here: https://github.com/danvk/dygraphs/blob/73b78f00501e83a62b491953916c3188c156eedc/src/dygraph.js#L87

**Expected behavior:**

The desired quick fix (convert to class) is offered, but then not listed as an option:

![image](https://user-images.githubusercontent.com/98301/58139952-1a587500-7c0b-11e9-9dab-153a5c366248.png)

**Actual behavior:**

I'd like to be able to run the quick fix to convert this monster to a class!

**Playground Link:** 

**Related Issues:**

**Comment by a-tarasyuk** [comment]
@danvk The following line causes the issue https://github.com/danvk/dygraphs/blob/73b78f00501e83a62b491953916c3188c156eedc/src/dygraph.js#L378

If you remove `as any` QF action will be available. Why do you use type assertion here? As I know type assertion expressions can only be used in TypeScript files, or am I wrong?

cc @DanielRosenwasser @RyanCavanaugh

**Comment by danvk** [comment]
@a-tarasyuk thanks for taking a look. I tried to reproduce and this is all working better now. I only get offered the "convert to class" quickfix when I fix the error you pointed out. And when I fix the error, the quickfix works.

I'm on the same version of TypeScript as last July but perhaps a vscode update made this behavior more consistent?

In any case, I'll close this out.
