### ISSUE TITLE
Maximum call stack size exceeded in "instantiateTypes"

### ISSUE THREAD

**Issue by friedemannsommer** [microsoft/TypeScript#31538]
**TypeScript Version:**  3.4.5

**Search Terms:** `instantiateTypes`, `maximum`, `call stack` `exceeded`, `typescript`, `compiler`

**Code**
In the project we make heavy use of type parameters and type inheritance. This is an simplified example (which on its own compiles):
```typescript
interface Attributes extends Object {
    name: string
    description: string
    created_at: number
    updated_at: number
}

interface Relationship extends Object {
    id: Data['id']
    type: Data['type']
}

interface DataRelationships {
    [key: Data['type']]: Relationship
}

interface Data extends Object {
    id: string
    type: string
    attributes: Attributes
    relationships: DataRelationships
}

interface ExampleChildConfigA<T extends Attributes = Attributes> extends Object {
    attributeName: keyof T
}

interface ExampleChildConfigB<T extends Attributes = Attributes> extends Object {
    attributeNames: Array<keyof T>
}

export interface ExampleA<
    T extends Data = Data,
    TL extends Data[] = Data[]
> extends Object {
    resource: T['type']
    relations?: Array<keyof T['relationships'] | TL[number]['type']>
    ids?: Array<T['id']>
    sortBy?: ExampleChildConfigA<T['attributes']>
    search?: ExampleChildConfigB<T['attributes']>
}
```
I can't pinpoint the location for the error in the source code. But based on the call stack i would guess that this originates from type parameters for types? If you could give me a hint what to look for, i'll happily add examples.
**Expected behavior:**
The project compiles without compiler errors.
**Actual behavior:**
The compiler process crashes with the "Maximum call stack exceeded" error
```text
RangeError: Maximum call stack size exceeded
    at cloneTypeParameter ([redacted]/node_modules/typescript/lib/tsc.js:34163:26)
    at instantiateAnonymousType ([redacted]/node_modules/typescript/lib/tsc.js:34352:42)
    at [redacted]/node_modules/typescript/lib/tsc.js:34310:37
    at mapType ([redacted]/node_modules/typescript/lib/tsc.js:38231:24)
    at instantiateMappedType ([redacted]/node_modules/typescript/lib/tsc.js:34305:28)
    at getAnonymousTypeInstantiation ([redacted]/node_modules/typescript/lib/tsc.js:34258:56)
    at instantiateTypeWorker ([redacted]/node_modules/typescript/lib/tsc.js:34413:28)
    at instantiateType ([redacted]/node_modules/typescript/lib/tsc.js:34397:26)
    at instantiateList ([redacted]/node_modules/typescript/lib/tsc.js:34094:34)
    at instantiateTypes ([redacted]/node_modules/typescript/lib/tsc.js:34108:20)
```
**Playground Link:** 

**Related Issues:** 
#16331, #20330, #21611, #16233

**Comment by ahejlsberg** [comment]
It's really hard to speculate without code that actually reproduces the issue. Hopefully you can post something. Also, a deeper stack trace world be helpful. In particular it would be useful to see where the recursion originates (i.e. what happened at the bottom of the stack).

**Comment by friedemannsommer** [comment]
@ahejlsberg thank you for the quick response, i can't give you any _real_ example since the project contains around 50k LOC. If you could say what to look for, it might be possible to find an example. 

This file contains the full call stack
[tsc-call-stack.txt](https://github.com/microsoft/TypeScript/files/3212388/tsc-call-stack.txt)

**Comment by RyanCavanaugh** [comment]
@friedemannsommer the most useful thing would be if you can attach a debugger to the tsc process (`node --inspect-brk path/to/tsc.js -p path/to/your/proj` & attach with e.g. `about:inspect` in Chrome or whatever) 

At the bottom of the call stack you'll see this series of relevant calls:
```
isTypeRelatedTo (tsc.js:35194)
checkTypeRelatedToAndOptionallyElaborate (tsc.js:34586)
checkApplicableSignature (tsc.js:41775)
chooseOverload (tsc.js:42077)
resolveCall (tsc.js:41999)
resolveCallExpression (tsc.js:42255)
resolveSignature (tsc.js:42494)
getResolvedSignature (tsc.js:42514)
checkCallExpression (tsc.js:42585)
checkExpressionWorker (tsc.js:44393)
checkExpression (tsc.js:44320)
```

`checkExpression` has a `node` parameter; this is the originating call that's causing the problem. You can call `ts.getTextOfNode(node)` in the console to print the text of that call. If you're lucky, this alone would give you enough clues to extract an isolated repro.

`isTypeRelatedTo` takes two arguments `source` and `target`; for both of these you should call `ts.typeToString(source)` in the console to print the names or textual representations of the types being evaluated.

Checking those values in higher frames of `isTypeRelatedTo` should show you what the circularity the compiler is incorrectly descending into is.

**Comment by friedemannsommer** [comment]
@RyanCavanaugh The "types" vary sometimes they are type parameters, interfaces or `type`s. Based on that i can't tell what exactly is causing it, but the project compiles in `tsc` version 3.3.4000. As of `tsc` version 3.4.1 it doesn't compile anymore because of the maximum call stack exception. As far as i can tell based on what i've seen while debugging this, is that the `isTypeRelatedTo` recursively called because the same type gets a new type instance over and over again, but it changes which type it is.

**Comment by friedemannsommer** [comment]
@RyanCavanaugh I've tried to compile it with the newer 3.5.1 release and it compiles successful.

**Comment by RyanCavanaugh** [comment]
Thanks for the update!
