### ISSUE TITLE
Visual Studio 1.5 slow/ almost hangs on startup

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#3153]
I'm using the latest TypeScript Visual Studio 1.5 Beta plugin and VS almost always hangs on startup.

Noticed it scans tons of files:
![snap](https://cloud.githubusercontent.com/assets/199519/7617967/c319cd08-f97c-11e4-831c-5c7cd93e470f.png)

What's going on here? It this a change to the language service or the plugin?

**Comment by DanielRosenwasser** [comment]
@paulvanbrenk @vladima @CyrusNajmabadi

**Comment by jbondc** [comment]
So I used to have a junction --> the folder tests/ memory mapped to Z:\TypeScript\tests

Somehow it's gone now, so explains to slowness of scanning all files.

I guess this more of a question, how do I exclude the folder tests/ so that Visual Studio doesn't scan files in it? I currently have TypeScript setup as a 'Web Site' project. I've tried TypeScript / node.js but that's even worse in terms of scanning.

**Comment by jbondc** [comment]
It looks this is a probably a change in the LS, see below:

![snap](https://cloud.githubusercontent.com/assets/199519/7632161/52ace6b2-fa18-11e4-83a3-ed9c5d5ca1f6.png)

Even worse, it doesn't take into account my 'junction link' and looks for files in F:/
How can I disable this?

**Comment by paulvanbrenk** [comment]
I'm not sure what I'm looking at in these pictures and I'm not sure what you're trying to do? Are you trying to open _all_ the files in the github repro in VS at the same time?

What does your setup look like and which version of VS are you using?

**Comment by jbondc** [comment]
- Visual Studio 2013
- TypeScript plugin 1.4
- git clone from master branch of TypeScript
- jake (make sure to build so you get lots of extra files)

When I open up Visual Studio 2013 and open the TypeScript folder as a 'web project', it's very slow. Using a tool call 'procman', that's what I see above as the project is "Loading" and VS isn't responding for at least 10 seconds. Will try to make a video tomorrow.

**Comment by paulvanbrenk** [comment]
That's roughly 30.000 files, that's a little more than we expect to open all at once, though the performance of VS 2015 should be better.

I would stick to opening just the ~/typescript/src/compiler folder...

**Comment by jbondc** [comment]
But I'm no opening any files... what changed in the language service? What's AMD/LIB ?

**Comment by paulvanbrenk** [comment]
amd\lib seems to be part of the path for a testcase. 

Not sure what changed here, but this does work a lot better in VS 2015.

The easiest workaround is to stick to the _src_ folder in the root of the enlistment, and not include each test case in your project.

**Comment by mhegazy** [comment]
We have made a lot of changes in VS2015 to handle similar issues. can you give 2015 a try?
