### ISSUE TITLE
`this` parameter of union signatures should be the intersection of constituents’ `this` parameters

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#31547]
...but currently it’s the union. Discovered while looking at #31485.

Minimal repro:

```ts
type F1 = (this: void) => void;
type F2 = (this: number) => void;
declare var fn: F1 | F2;
fn(); // should error
```

Silly but understandable real-world-ish example ([playground](https://www.typescriptlang.org/play/#src=interface%20Car%20%7B%0D%0A%20%20%20%20odometer%3A%20number%3B%0D%0A%20%20%20%20drive()%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Cow%20%7B%0D%0A%20%20%20%20weight%3A%20number%3B%0D%0A%20%20%20%20eatGrass()%3A%20void%3B%0D%0A%20%20%20%20isARealCow()%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Afunction%20carWorks(this%3A%20Car)%3A%20boolean%20%7B%0D%0A%20%20%20%20this.drive()%3B%0D%0A%20%20%20%20return%20this.odometer%20%3E%200%3B%0D%0A%7D%0D%0A%0D%0Afunction%20cowWorks(this%3A%20Cow)%3A%20boolean%20%7B%0D%0A%20%20%20%20const%20prevWeight%20%3D%20this.weight%3B%0D%0A%20%20%20%20this.eatGrass()%3B%0D%0A%20%20%20%20return%20this.weight%20%3E%20prevWeight%3B%0D%0A%7D%0D%0A%0D%0Aconst%20cow%20%3D%20%7B%0D%0A%20%20%20%20weight%3A%20100%2C%0D%0A%20%20%20%20eatGrass()%20%7B%20this.weight%2B%2B%20%7D%2C%0D%0A%20%20%20%20%2F%2F%20Conditional%20expression%20creates%20a%20union%20type%20here%0D%0A%20%20%20%20isARealCow%3A%20Math.random()%20%3E%200.5%20%3F%20carWorks%20%3A%20cowWorks%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Runtime%20error%20~50%25%20of%20the%20time%3A%0D%0A%2F%2F%20TypeError%3A%20this.drive%20is%20not%20a%20function%0D%0A%2F%2F%20%20%20%20at%20Object.carWorks%20%5Bas%20isARealCow%5D%0D%0Acow.isARealCow()%3B%0D%0A)):

```ts
interface Car {
    odometer: number;
    drive(): void;
}

interface Cow {
    weight: number;
    eatGrass(): void;
    isARealCow(): boolean;
}

function carWorks(this: Car): boolean {
    this.drive();
    return this.odometer > 0;
}

function cowWorks(this: Cow): boolean {
    const prevWeight = this.weight;
    this.eatGrass();
    return this.weight > prevWeight;
}

const cow = {
    weight: 100,
    eatGrass() { this.weight++ },
    // Conditional expression creates a union type here
    isARealCow: Math.random() > 0.5 ? carWorks : cowWorks
}

// Runtime error ~50% of the time:
// TypeError: this.drive is not a function
//    at Object.carWorks [as isARealCow]
cow.isARealCow();
```

Since `cow.isARealCow` _might_ call `this.drive()` or _might_ call `this.eatGrass()`, the only thing that should be able to call it is something has a `weight`, `eatGrass()`, `odometer`, _and_ `drive()`—that is, the _intersection_ of the constitutents’ `this` parameter types. (Perhaps a mechanical cow of some kind would do.)

**TypeScript Version:**  6a559e37ee0d660fcc94f086a34370e79e94b17a

**Search Terms:** union signatures this parameter variance intersection

[**Playground Link**](https://www.typescriptlang.org/play/#src=type%20F1%20%3D%20(this%3A%20void%2C%20a%3A%20%7B%20foo%3A%20string%20%7D)%20%3D%3E%20void%3B%0D%0Atype%20F2%20%3D%20(this%3A%20number%2C%20a%3A%20%7B%20bar%3A%20string%20%7D)%20%3D%3E%20void%3B%0D%0Atype%20F%20%3D%20F1%20%7C%20F2%3B%0D%0Adeclare%20var%20fn%3A%20F%3B%0D%0A%0D%0A%2F%2F%20should%20error%2C%20because%20a%20function%20that%20might%20be%0D%0A%2F%2F%20F2%20shouldn’t%20be%20callable%20without%20%60this%60%20being%0D%0A%2F%2F%20assignable%20to%20%60number%60%0D%0Afn(%7B%20foo%3A%20''%2C%20bar%3A%20''%20%7D)%0D%0A%0D%0A%2F%2F%20With%20--strictFunctionTypes%2C%20this%20proves%20that%0D%0A%2F%2F%20%60this%60%20is%20correctly%20checked%20as%20contravariant%3B%0D%0A%2F%2F%20it’s%20just%20the%20union%20signature%20generation%20that’s%0D%0A%2F%2F%20broken.%0D%0Adeclare%20var%20f1%3A%20(this%3A%20%7B%20x%3A%20string%20%7D)%20%3D%3E%20void%3B%0D%0Adeclare%20var%20f2%3A%20(this%3A%20%7B%20x%3A%20string%2C%20y%3A%20string%20%7D)%20%3D%3E%20void%3B%0D%0Af1%20%3D%20f2%20%2F%2F%20errors%20correctly%0D%0Af2%20%3D%20f1%0D%0A)

**Related Issues:** #31485

**Comment by fatcerberus** [comment]
> Perhaps a mechanical cow of some kind would do.

:smile:
🤖🐄
