### ISSUE TITLE
Warning if properties of interfaces that are not marked as `readonly` are not assignable

### ISSUE THREAD

**Issue by surr34** [microsoft/TypeScript#31546]
## Search Terms

GetAccessor, SetAccessor, interface, readonly

## Suggestion

Issue a warning if properties of interfaces that are not marked as `readonly` are not assignable. 

## Use Cases

This might unveil and prevent future errors.

## Examples
Recently I had to work with an API that returned an Interface. That looked something like this.
```
interface IFoo<T> {
    entity: T
}
```
Not marking any of it's members as read-only I was trying to assign one of its properties which failed at runtime. Digging into the implementations of these interface revealed that entity was implemented as GetAccessor and a SetAccessor was not provided. Running in NodeJS failed with a crash, running in Chrome had no impact at all (effectively a noop).

~~Would it be possible to consider this ill-formed (probably not)~~, or issue a warning? Is there any reason to have this implementation without marking the property as readonly?
```
class Foo<T> implements IFoo<T> {
    entity_: T;
    constructor(value: T) {
        this.entity_ = value;
    }
    get entity(): T {
        return this.entity_;
    }
}
```
## Checklist

My suggestion meets these guidelines:
I think this will actually break code, Depending on the environment the current behavior may either fail silently or hard, I think issuing warnings / hints might improve API stability in the long run as this moves towards "_Statically identify constructs that are likely to be errors._"

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
I'm not positive, but I think this would be a pretty far-reaching breaking change because TypeScript didn't always have the `readonly` keyword.  Thus the lack of such keyword in existing code doesn't necessarily imply "this property is writable", just that it *may or may not* be writable.

**Comment by RyanCavanaugh** [comment]
@fatcerberus is correct on all counts
