### ISSUE TITLE
tsc OOM after update to `@types/react > 16.8.12`

### ISSUE THREAD

**Issue by Swatinem** [microsoft/TypeScript#31553]
This is basically a copy of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35514.
When updating the `@types/react` version of a *huge* monorepo, `tsc` dies after a few minutes due to OOM.

**TypeScript Version:**  3.4.5

**Search Terms:** react oom

**Code**

I can’t really post code here, since this is our huge-ass closed source monorepo, but here are some stats from a successful typecheck:

```
Files:           3866
Lines:         639057
Nodes:            NaN
Identifiers:      NaN
Symbols:       830297
Types:         318458
Memory used: 1073410K
I/O read:       0.19s
I/O write:      0.00s
Parse time:     5.87s
Bind time:      3.03s
Check time:    21.82s
Emit time:      0.00s
Total time:    30.72s
```

**Expected behavior:**

when updating `@types/react` to any version `> 16.8.12`, there should not be any big change in typechecking time or memory usage.

**Actual behavior:**

when updating `@types/react` to any version `> 16.8.12`, `tsc` dies due to OOM after a few minutes of runtime.

**Playground Link:** 

**Related Issues:** 

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35514

**Comment by jeremy-coleman** [comment]
I cant even compile local projects..

**Comment by ahejlsberg** [comment]
Would you mind trying with `typescript@next` (3.5.0-dev.20190524 or later). We have fixed several performance and OOM issues in the upcoming 3.5 release.

**Comment by jeremy-coleman** [comment]
i can confirm typescript @ "3.5.0-dev.20190524" solves the issues with react

ts 3.4.5 with @types/react 16.8.18 fails, but compiles with @types/react 16.8.11
ts 3.5 with @types/react 16.8.18 compiles, plus some new error messages

![image](https://user-images.githubusercontent.com/25135855/58346207-4ac92a80-7e28-11e9-8364-ea4e32ec30fa.png)

**Comment by ahejlsberg** [comment]
@jeremy-coleman FYI, the new "Expression produces a union type that is too complex to represent" error is issued when we detect that we're about to create a union type with >100,000 constituents.

**Comment by Swatinem** [comment]
# `typescript 3.4.5` with `@types/react 16.8.12`

```
> time tsc
Files:           3926
Lines:         643464
Nodes:            NaN
Identifiers:      NaN
Symbols:       844464
Types:         323685
Memory used: 1018110K
I/O read:       0.32s
I/O write:      0.00s
Parse time:     5.70s
Bind time:      3.36s
Check time:    15.52s
Emit time:      0.00s
Total time:    24.57s
tsc  40,58s user 1,11s system 164% cpu 25,301 total
```

# `typescript 3.4.5` with `@types/react 16.8.18`

```
> time tsc                         

<--- Last few GCs --->

[2316:0x32e58d0]    30684 ms: Scavenge 1387.8 (1423.4) -> 1387.3 (1424.4) MB, 4.5 / 0.0 ms  (average mu = 0.174, current mu = 0.063) allocation failure 
[2316:0x32e58d0]    31406 ms: Mark-sweep 1388.0 (1424.4) -> 1387.6 (1423.4) MB, 717.3 / 0.0 ms  (average mu = 0.111, current mu = 0.043) allocation failure scavenge might not succeed
[2316:0x32e58d0]    31415 ms: Scavenge 1388.3 (1423.4) -> 1387.9 (1424.4) MB, 4.8 / 0.0 ms  (average mu = 0.111, current mu = 0.043) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x38049b8dbe1d]
Security context: 0x22f6dbc1e6e9 <JSObject>
    1: getIntersectionType(aka getIntersectionType) [0xc5c80ae4701] […/node_modules/typescript/lib/tsc.js:~33181] [pc=0x38049c4c79a1](this=0x3cce635826f1 <undefined>,types=0x066b01d43ab9 <JSArray[10]>,aliasSymbol=0x3cce635826f1 <undefined>,aliasTypeArguments=0x3cce635826f1 <undefined>)
    2: arguments adaptor frame: 1->...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [node]
 2: 0x8dc55c  [node]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xec7bf2  [node]
 6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xea07f4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x114018e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x38049b8dbe1d 
[2]    2316 abort (core dumped)  tsc
tsc  66,70s user 2,89s system 189% cpu 36,746 total
```

surprisingly, this crashed quite quickly. before, it was running for more than 2 minutes before crashing

# `typescript 3.5.0-dev.20190525` with `@types/react 16.8.12`

```
Files:           3928
Lines:         649424
Nodes:            NaN
Identifiers:      NaN
Symbols:       856303
Types:         216994
Memory used: 1069758K
I/O read:       0.41s
I/O write:      0.00s
Parse time:     5.76s
Bind time:      2.06s
Check time:    13.05s
Emit time:      0.00s
Total time:    20.86s
tsc  34,82s user 1,07s system 166% cpu 21,581 total
```

there are 10 new errors that I need to look at more specifically.


# `typescript 3.5.0-dev.20190525` with `@types/react 16.8.18`

```
Files:           3928
Lines:         649432
Nodes:            NaN
Identifiers:      NaN
Symbols:       856502
Types:         217344
Memory used: 1064544K
I/O read:       0.26s
I/O write:      0.00s
Parse time:     5.79s
Bind time:      2.05s
Check time:    12.87s
Emit time:      0.00s
Total time:    20.70s
tsc  35,08s user 0,90s system 168% cpu 21,382 total
```

same 10 errors, none of which are the new `Expression produces a union type that is too complex to represent`, but different types.

plus, there seems to be a slight speedup, which is nice :-) Although the memory usage is still very high.

So thanks for the help, closing this :-)

**Comment by jeremy-coleman** [comment]
@ahejlsberg wow 100k constituent types is extreme. is there a preference (in terms of efficiency) for common patterns, such as using a type aliases vs extending an interface? or the proper use of wrappers like Pick , Omit and record type construction

**Comment by ahejlsberg** [comment]
@jeremy-coleman It typically occurs when large union types are turned into intersection types, which for example happens when you call through a union of function types or assign to an indexed access into an union of objects.

Say you have an object `obj` of type `A | B | C | D` where each of the types has a `foo` property of type `A1 | A2 | A3`, `B1 | B2 | B3`, `C1 | C2 | C3` and `D1 | D2 | D3` respectively. In an assignment `obj["foo"] = xxx` we construct the type `(A1 | A2 | A3) & (B1 | B2 | B3) & (C1 | C2 | C3) & (D1 | D2 | D3)` to represent the assignment target. This type normalizes to `A1 & B1 & C1 & D1 | A1 & B1 & C1 & D2 | A1 & B1 & C1 & D3 | A2 & B1 & C1 & D1 | ...` for a total of 3 * 3 * 3 * 3 = 81 constituents. Now imagine the type of `obj` is a union of over 100 types in the same pattern. That would produce a union with 3^100 elements which obviously is beyond our capability to represent.

Unfortunately this type of thing can happen with React's types, for example when you operate on unions that represent all React HTML elements (i.e. `React.ReactHTML[keyof React.ReactHTML]`).

**Comment by jeremy-coleman** [comment]
@ahejlsberg  Do you think there is a viable way to strip out a common type on each 'trial' of properties, in the above case of an object obj of type A | B | C | D, basically turn it into obj of type (A | B | C | D)+ React.HTMLProps<any>
