### ISSUE TITLE
A bug in Chinese Typescript Document.

### ISSUE THREAD

**Issue by JackieAnxis** [microsoft/TypeScript#31554]
I find one difference between the Chinese document and the origin document in the `Generics` section of Handbook which makes me confused.
In the [origin document](https://www.typescriptlang.org/docs/handbook/generics.html), it says:
```typescript
function getProperty<T, K extends keyof T>(obj: T, key: K) {
    return obj[key];
}

let x = { a: 1, b: 2, c: 3, d: 4 };

getProperty(x, "a"); // okay
getProperty(x, "m"); // error: Argument of type 'm' isn't assignable to 'a' | 'b' | 'c' | 'd'.

```

But in [Chinese document](https://www.tslang.cn/docs/handbook/generics.html), it says:
```typescript
function getProperty(obj: T, key: K) {
    return obj[key];
}

let x = { a: 1, b: 2, c: 3, d: 4 };

getProperty(x, "a"); // okay
getProperty(x, "m"); // error: Argument of type 'm' isn't assignable to 'a' | 'b' | 'c' | 'd'.
```

I would like to fix the document but I don't know how to  contribute to the Chinese website.

**Comment by nmain** [comment]
This is either a bug in the html generation or some sort of user error in the CMS.  If you look at the rendered output in browser devtools, the `<T, K extends keyof T>` is actually there as a dom element with tagName `T,` and attributes `k`, `extends`, `keyof`, `t`.

**Comment by JackieAnxis** [comment]
> This is either a bug in the html generation or some sort of user error in the CMS. If you look at the rendered output in browser devtools, the `<T, K extends keyof T>` is actually there as a dom element with tagName `T,` and attributes `k`, `extends`, `keyof`, `t`.
hhhh, I find that.
![image](https://user-images.githubusercontent.com/19246028/58314790-d059d400-7e42-11e9-9780-2e1d4d7d19f0.png)

**Comment by RyanCavanaugh** [comment]
We don't control tslang.cn

**Comment by fenying** [comment]
The site seems outdated for a long time...

If you wanna read the Chinese edition, see this https://legacy.gitbook.com/book/zhongsp/typescript-handbook/details

**Comment by JackieAnxis** [comment]
> The site seems outdated for a long time...
> 
> If you wanna read the Chinese edition, see this https://legacy.gitbook.com/book/zhongsp/typescript-handbook/details

Great! Thanks!

**Comment by GreatAuk** [comment]
> The site seems outdated for a long time...
> 
> If you wanna read the Chinese edition, see this https://legacy.gitbook.com/book/zhongsp/typescript-handbook/details

Is this the latest version?
