### ISSUE TITLE
Huge memory consumption due to default setup of tsconfig.json

### ISSUE THREAD

**Issue by jalchr** [microsoft/TypeScript#31550]
**TypeScript Version:**  any version

**Expected behavior:** consume normal memory amounts

**Actual behavior:** consume huge memory while building angular 7 app

**Details**:
I'm having huge memory issues, trying to publish an angular project with Visual Studio 2019.
Paging file size=3712MB and RAM=9GB. Running Windows 10 over Parallels (Mac)

![image](https://user-images.githubusercontent.com/295421/58226873-37876380-7d31-11e9-88ad-45afcaaf7e36.png)

After checking VS child processes, I noticed that “node server” is the primary consumer of memory (about 4.5 GB alone), due to typescript compilation.

**Solution**
After modifying tsconfig.json and excluding "node_modules" and "dist", the memory consumption of "Node.js server-side javascript process" went down from 4.5GB to 2GB (about 100%)

```
...
"exclude": [
        "node_modules",
        "dist"
        ]
```

![image](https://user-images.githubusercontent.com/295421/58226957-8cc37500-7d31-11e9-9e33-1a5e9d7fbc6f.png)

Perhaps, tsconfig.json should have those excludes by default

**Comment by jalchr** [comment]
Steps to reproduce:
- Use visual studio to create an angular project and publish it. 
- Check memory consumption during the process
- Now change the tsconfig.json and exclude node_modules 
- publish again and check memory

Of course, the larger the angular project (more dependencies), the clearer the problem appears.

Full details of the source of this issue: https://twitter.com/SeaRyanC/status/1131419372507975680

**Comment by RyanCavanaugh** [comment]
We'd need some actual project (zip or repo) in order to investigate. In general the file exclusion heuristics should prevent this from happening in VS Scenarios

**Comment by jalchr** [comment]
Perhaps, tsconfig.json should have those exclusions by default or providing the developer some hints when building the project

**Comment by RyanCavanaugh** [comment]
`node_modules` is excluded by default. Not sure what you were encountering here.
