### ISSUE TITLE
[Feature Request] Improve suggestion for String Literal Types + string-fallback

### ISSUE THREAD

**Issue by Shinigami92** [microsoft/TypeScript#31562]
When we define a type like this, we get full autosuggestion support:

![Unbenannt2](https://user-images.githubusercontent.com/7195563/58230863-d44c0000-7d35-11e9-901b-470366a7683e.jpg)

But if we define a type with a fallback to `string`, we get nothing intelligent:

![Unbenannt](https://user-images.githubusercontent.com/7195563/58230862-d44c0000-7d35-11e9-937a-6c1a57ec83e7.jpg)

**Comment by RyanCavanaugh** [comment]
From the type system's perspective, `"red" | "green" | "blue" | string` is a fancy way of writing `string`. The literals are lost. We don't have any mechanism for "A type plus some associated *suggestions*" nor plans to add one.

**Comment by Shinigami92** [comment]
But can we make this happen in the future?
It's only a Feature Request and maybe someone in the open source world can bring us this Feature.
It wont break anything but improve VS Code.

**Comment by Shinigami92** [comment]
Duplicate of #29729
