### ISSUE TITLE
API: inconsistent Type#getProperties involving index signature and union type order

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#31565]
**TypeScript Version:**  3.4.5, 3.5.0-dev.20190523

**Search Terms:**

**Code**

```ts
type IndexFirst = {[x: string]: string} | {x: string};
type IndexLast = {p: string} | {[p: string]: string};
```

**Expected behavior:**

`type.getProperties()` to return an array of one symbol for each of the type alias declarations.

**Actual behavior:**

For `IndexFirst` `type.getProperties()` returns an empty array.
For `IndexLast` `type.getProperties()` returns an array of one symbol.

AFAICT this is caused by an early break in `getPropertiesOfUnionOrIntersectionType`:

```ts
// The properties of a union type are those that are present in all constituent types, so
// we only need to check the properties of the first type
```

That's not quite correct if there are index signatures. Iterating through the rest of the union constituents would fix this. `getPropertyOfUnionOrIntersectionType` already strips properties not present in all constituents. So this is probably a performance optimization and shouldn't simply be removed. Maybe we could stop after the first constituent that has no index signature.

**Comment by RyanCavanaugh** [comment]
If there isn't a way to observe this during batch compilation or interactive scenarios, I would just call this a quirk of the API. It's not clearly a defect.

**Comment by ajafff** [comment]
> wouldn't accept a PR to "fix" this with any negative perf implications

@RyanCavanaugh 
As you already mentioned this is not observable via batch compilation or language service. From the compilers POV this is dead code as it's never hit by any of the tests. For API users this function is not usable with this "quirk" as I cannot synthesize `Symbol`s for union types.
Fixing this by iterating through all types with index signature will not have a perf impact since there's not way a user could ever notice it.

**Comment by ajafff** [comment]
Turns out this affects bug property access completions. I added a test case in PR #31979
