### ISSUE TITLE
Add ability to use yarn in typescript.npm

### ISSUE THREAD

**Issue by svipas** [microsoft/TypeScript#31561]
As the title says. Currently if I use `/usr/local/bin/yarn` in `typescript.npm` it doesn't work, but if I use `/usr/local/bin/npm` it works. I prefer `yarn` since it's faster and I'm using it everywhere.

**Comment by mjbvz** [comment]
`typescript.npm` is only used for the internal automatic typings acquisition

https://github.com/microsoft/TypeScript/issues/19269 tracks using npm vs yarn for your codebase
