### ISSUE TITLE
Official TypeScript badge for READMEs

### ISSUE THREAD

**Issue by trivikr** [microsoft/TypeScript#31569]
## Search Terms

badge, typescript badge

## Suggestion

Official TypeScript badge (just like jest has one in their [README](https://github.com/facebook/jest#badge))

## Use Cases

There's no official badge for projects that use TypeScript.
There's an unofficial repo which provides different options for typescript badges https://github.com/ellerbrock/typescript-badges

**Comment by DanielRosenwasser** [comment]
Would be interesting if we could get a **Bᴜɪʟᴛ Wɪᴛʜ TʏᴘᴇSᴄʀɪᴘᴛ** badge of some sort.

**Comment by MartinJohns** [comment]
@DanielRosenwasser I let my creative side flow free and created this badge for you: https://imgur.com/bLmkPCR

Feel free to use it!

**Comment by DanielRosenwasser** [comment]
***Damn that's good*** - it looks like it might say "BuiLt with TyreScrirt ❤", which I think kind of symbolizes how everyone sees something different in what they love about TypeScript.

**Comment by tonisostrat** [comment]
What about something like [this](https://imgflip.com/i/31tcyj)? :D

**Comment by DanielRosenwasser** [comment]
Okay, this is getting extremely competitive. I'm excited to see where the community goes with this.

**Comment by weswigham** [comment]
![TS Checked](https://img.shields.io/badge/%E2%9C%94%EF%B8%8F-TS%20Checked-blue.svg)

**Comment by trivikr** [comment]
![image](https://user-images.githubusercontent.com/16024985/58357531-093c7d80-7e30-11e9-83f1-ac8fc580b1c2.png)

**Comment by styfle** [comment]
![img](https://badgen.net/badge/built%20with/TypeScript/blue) or ![img](https://flat.badgen.net/badge/built%20with/TypeScript/blue)

https://badgen.net

**Comment by southpolesteve** [comment]
Can we have a special badge if the project enables strict mode? 🤗

**Comment by mceachen** [comment]
![badge](https://badgen.net/badge/TypeScript/strict/green)

**Comment by fatcerberus** [comment]
Does anyone actually use tsc in loose mode nowadays?  Other than for legacy reasons, of course.  Enabling all the strict flags is literally the first thing I do in any new project now.

**Comment by fkleuver** [comment]
> Does anyone actually use tsc in loose mode nowadays?

If you're being very nit-picky, [TypeScript itself](https://github.com/microsoft/TypeScript/blob/master/src/tsconfig-base.json) since they don't have the real 💪 strict mode enabled (`strictFunctionTypes` and `strictBindCallApply` are missing) ;)

**Comment by johnnyreilly** [comment]
How about a badge that is dynamically generated based upon your `tsconfig.json`. if it's completely `strict` then you get the black belt TypeScript badge?

**Comment by fenying** [comment]
Maybe this could be simple?

[![Strict TypeScript Checked](https://badgen.net/badge/TS/Strict "Strict TypeScript Checked")](https://www.typescriptlang.org)

```markdown
[![Strict TypeScript Checked](https://badgen.net/badge/TS/Strict "Strict TypeScript Checked")](https://www.typescriptlang.org)
```

**Comment by fkleuver** [comment]
> Maybe this could be simple?

Looks good, only thing it's missing is the 💪

**Comment by AnandChowdhary** [comment]
Jokes apart, some projects (including mine) use the convention “types | TypeScript” to signify that types are available. I think this is all that is necessary and we don’t need a badge specifically for projects written in TS.

[![Types](https://img.shields.io/npm/types/scrub-js.svg)](https://www.npmjs.com/package/scrub-js)

**Comment by orta** [comment]
I'm not really a README badges kinda person (I built my own markdown parser to get rid of them for CocoaPods) especially when it's duplicating GitHub chrome (like forks/stars/language...) 

Though I see most of the value here is in showing the npm page and other derived READMEs. 

Hopefully we can get npm to show types on their site like yarn does, but for now I think @AnandChowdhary probably has the right angle: showing folks they get types as they are exploring the ecosystem vs highlighting potential code quality improvements being created with TS.

Maybe this as the "official" one: 

> ![Typed with TypeScript](https://flat.badgen.net/badge/icon/Typed?icon=typescript&label&labelColor=blue&color=555555)

```md
![Typed with TypeScript](https://flat.badgen.net/badge/icon/Typed?icon=typescript&label&labelColor=blue&color=555555)
```

**Comment by Hongbo-Miao** [comment]
Found a badge used in Microsoft own repo [microsoft/fast](https://github.com/microsoft/fast), which is

[![TypeScript](https://img.shields.io/badge/%3C%2F%3E-TypeScript-%230074c1.svg)](http://www.typescriptlang.org/)

```
[![TypeScript](https://img.shields.io/badge/%3C%2F%3E-TypeScript-%230074c1.svg)](http://www.typescriptlang.org/)
```

**Comment by alex-hedley** [comment]
![Typescript](https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white)

`![Typescript](https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white)`

Source: https://dev.to/envoy_/150-badges-for-github-pnk

**Comment by RyelBanfield** [comment]
> @DanielRosenwasser I let my creative side flow free and created this badge for you: https://imgur.com/bLmkPCR
> 
> Feel free to use it!

I love that I came here looking for a badge and this is what I found.

**Comment by trivikr** [comment]
Closing this issue as the request was created three years ago, and there are multiple options for a TypeScript badge.

**Comment by prox2** [comment]
* [![Typescript][Typescript]][Typescript-url]
[Typescript]:https://img.shields.io/badge/typescript-ffffff?style=for-the-badge&logo=typescript&logoColor=blue
[Typescript-url]:https://www.typescriptlang.org/

**Comment by prox2** [comment]
[![Typescript][Typescript]][Typescript-url]
[Typescript]:https://img.shields.io/badge/typescript-ffffff?style=for-the-badge&logo=typescript&logoColor=blue
[Typescript-url]:https://www.typescriptlang.org/
