### ISSUE TITLE
Add a CLI option to output XML report on compilation. 

### ISSUE THREAD

**Issue by bencooper222** [microsoft/TypeScript#31566]
## Search Terms

JUnit, XML, test reporting
## Suggestion

Add a CLI option to output a JUnit XML that reports on typescript errors. 

## Use Cases
CI platforms like CircleCI can consume these reports to provide analytics on your codebase. This is especially useful when someone isn't using Typescript as a build tool but rather as a typechecking tool

## Examples

`tsc --report "report/ts.xml"` and outputs a JUnit XML. 

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
The TypeScript compiler API is public so that someone else can write this tool.

**Comment by matzeeable** [comment]
Hi @bencooper222! Did you found a solution for this? :-)

**Comment by glenjamin** [comment]
I've been taking a look into this, but it seems like the compiler API (at least as documented in https://github.com/microsoft/TypeScript-wiki/blob/master/Using-the-Compiler-API.md) is very low level and would require a consumer to re-implement a lot of what goes on in `tsc`/`tsserver` just to get access to the type checking results as data.

Is there a public high-level API that can be used to get type checking results directly?

**Comment by bencooper222** [comment]
I never did find a great solution :( and I agree, the TS compiler API is impractically low-level for this.

**Comment by glenjamin** [comment]
I cobbled this together this morning, I'll aim to tidy it up and publish to npm soonish

https://github.com/glenjamin/typescript-xunit-xml
