### ISSUE TITLE
Clarify spec regarding what symbol an alias refers to

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#3158]
``` ts
import foo = A.bar;

namespace A {
    export namespace bar { } // completion is fine if this namespace is removed

    export import bar = baz.boo;

    export namespace baz {
        export var boo = 1;
    }
}
foo./*no number completion here*/
```

This example is taken from #3140.
A user might think that foo should have a value meaning here, by following the alias all the way, past bar. But this is not how it works. Clarify in the spec that alias resolution stops as soon as a non-alias meaning is hit.

**Comment by CyrusNajmabadi** [comment]
@jsonfreeman Are you sure we want that behavior?  That actually seems non-intuitive to me (if i'm reading your post correctly).   In your example ```foo``` is an alias to ```A.bar```.  And ```A.bar``` is an export of of the ```A.baz.boo``` value.  So i would absolutely expect ```foo`` to have the ```A.baz.boo``` value.  

Is that not how things work at runtime?

**Comment by CyrusNajmabadi** [comment]
For example, if you removed ```export namespace bar { }``` then things would work as i outlined above, correct?  If that's the case, i'm not sure i understand why the inclusion of ```export namespace bar { }``` would change things.

Can you clarify here if my understanding is correct.  And, if so, what the virtue is of stopping alias traversal in this manner?  Thanks!

**Comment by JsonFreeman** [comment]
Yup, your understanding is correct. It's because this is how the compiler is designed, so the plan is to change the language design to match the compiler design.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
