### ISSUE TITLE
VS2017 Crashes when debugging typescript composite project.

### ISSUE THREAD

**Issue by Griffork** [microsoft/TypeScript#31589]
I don't know if this is where this bug should be reported because it's a problem with the Visual Studio 2017 Typescript plugin (it was occurring in typescript 3.2 and I upgraded to 3.4 and it's still occuring).

**TypeScript Version:**  3.4.1 Visual Studio Plugin
**Visual Studio Version:** 2017: 15.7.6

**Search Terms:** Typescript visual studio 2017 references crash, definitions map, composite project.

**Code**
I haven't been able to reproduce this in a test project but I can reproduce it 100% in my main project (which is still quite small). I can send the code privately to typescript devs who want to investigate.

My tsconfigs:
Client
``` json
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "amd",
    "target": "es6",
    "lib": [ "es6", "dom" ],
    "sourceMap": true,
    "strict": true,
    "build": true,
    "declaration": true,
    "declarationDir": "../ClientDeclarations",
    "baseUrl": "./",
    "paths": {
      "@Common/*": [ "../Common/*" ],
      "@Server/*": [ "../ServerDeclarations/*" ],
      "@Client/*": [ "./*"]
    }
  },
  "include": [
    "./*"
  ],
  "exclude": [
    "node_modules"
  ],
  "references": [
    { "path": "../Common" }
  ]
}

```
Common
``` json
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "umd",
    "target": "es6",
    "lib": [ "es6", "dom" ],
    "declaration": true,
    "composite": true,
    "rootDir": "./",
    "sourceMap": true,
    "strict": true
  },
  "exclude": [
    "node_modules"
  ]
}
```
Server
``` json
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "lib": [ "es6", "dom" ],
    "sourceMap": true,
    "strict": true,
    "build": true,
    "declaration": true,
    "declarationDir": "../ServerDeclarations",
    "baseUrl": "./",
    "paths": {
      "@Common/*": [ "../Common/*" ],
      "@Client/*": [ "../ClientDeclarations/*" ],
      "@Server/*": [ "./*" ]
    }
  },
  "include": [
    "./*"
  ],
  "exclude": [
    "node_modules"
  ],
  "references": [
    { "path": "../Common" }
  ]
}
```

Server starts an express app, and calls a function in common when a client connects. There's an error in common that I'm trying to debug but when I put a breakpoint or debugger statement on any of those lines then the app crashes.
Sometimes it crashes the other way around, when I've put a breakpoint in common and then another in the server and it crashes when trying to stop at the server breakpoint.
The execution path jumps between common and the server quite a bit, which may be what's causing the bug? It would explain why I'm struggling to reproduce it in a smaller example.

**Expected behavior:**
Node stops at the breakpoint and I can inspect variables in visual studio.

**Actual behavior:**
Visual studio freezes, then crashes and the only error on the node console is this:
```
Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)
```

**Related Issues:**  All related issues seem to be from the years 2015-2016 and typescript 2.x, and have generally been marked as fixed.

**Comment by Griffork** [comment]
Is this bug in the wrong place?

**Comment by RyanCavanaugh** [comment]
Sounds like a debugger issue. I'll have someone take a look

**Comment by EricCornelson** [comment]
Hey @Griffork! If you haven't yet, could you please submit a problem report from inside Visual Studio ([instructions here.](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) Check out "Record a repro", where you should be able to launch a new instance of VS to record the crash). That will get us the logs and other diagnostic we need to debug the issue for you.

I agree with Ryan that this sounds like an issue with the debugger rather than typescript itself. As soon as we get that crash report we can dig in and figure out what's happening and hopefully solve the issue for you.

Thanks!

**Comment by Griffork** [comment]
Sorry! I'd been checking back here for a couple of weeks after logging the issue and then figured it'd been buried.
I've changed the way my projects reference each other to get around this issue. 
I could probably get a old version of the code from my source control if you know what day I submitted the issue on?

**Comment by jessetrinity** [comment]
@Griffork Good that you have a workaround to move forward with, what did you do differently?

It looks like this GitHub issue was opened May 24. If you submit feedback [through VS](https://developercommunity.visualstudio.com/content/problem/post.html?space=8), you will be able to submit any attachments privately to our team.

**Comment by jessetrinity** [comment]
Closing this as I have not been able to repro. If you see the issue again or are able to provide more info I will be happy to take another look.
