### ISSUE TITLE
Private members are required when class is used as a parameter

### ISSUE THREAD

**Issue by MayhemYDG** [microsoft/TypeScript#31596]
**TypeScript Version:**  3.5.0-dev.20190525

**Search Terms:** private + error message excerpts

**Code**

```ts
interface Obj {
  data: string;
}

class Example implements Obj {
  private value: number = 1;
  public data: string = 'a';
}

function demo(arg: Example) {}
const obj: Obj = { data: 'b' };
demo(obj);
```

**Expected behavior:**
No issues, the private field is ignored, as the `test` function shouldn't be allowed to access it.

**Actual behavior:**
```
src/index.ts:12:6 - error TS2345: Argument of type 'Obj' is not assignable to parameter of type 'Example'.
  Property 'value' is missing in type 'Obj' but required in type 'Example'.

12 demo(obj);
        ~~~

  src/index.ts:6:11
    6   private value: number = 1;
                ~~~~~
    'value' is declared here.
```

I've started seeing this when testing out TS 3.5 rc in a react codebase:
https://github.com/adazzle/react-data-grid/pull/1659/files#diff-7904451b5b3999bb799849620264e75d
But the example above is still an issue in previous versions.

**Playground Link:** https://www.typescriptlang.org/play/#src=interface%20Obj%20%7B%0D%0A%20%20data%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Example%20implements%20Obj%20%7B%0D%0A%20%20private%20value%3A%20number%20%3D%201%3B%0D%0A%20%20public%20data%3A%20string%20%3D%20'a'%3B%0D%0A%7D%0D%0A%0D%0Afunction%20demo(arg%3A%20Example)%20%7B%7D%0D%0Aconst%20obj%3A%20Obj%20%3D%20%7B%20data%3A%20'b'%20%7D%3B%0D%0Ademo(obj)%3B%0D%0A

**Related Issues:** 
Didn't find any.

**Comment by DanielRosenwasser** [comment]
Because the private property is really an observable part of the type which can't be fulfilled structurally. Otherwise the following code would crash:

```ts
class Foo {
  private privateProp = "hello";

  count = 0;
  equals(other: Foo) {
    return this.privateProp.toLowerCase() === other.privateProp.toLowerCase();
  }
}

let x: Foo = {
  count: 0,
  equals(other: Foo) { return true; }
}
```
