### ISSUE TITLE
Provide some sort of diagnostics command in TSServer

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31592]
We often get feedback from VS/VS Code users that TSServer is slow, but the amount of time it takes to diagnose the issue is a bit much for them (e.g. enabling logging etc.)

The proposal here is for TSServer to provide some of the same information as `--listFiles` and `--extendedDiagnostics` which you can get from the command line. Editors could then open a buffer that could let them and our teams diagnose issues.

Here's an example of what we could return to the editor:

```json5
{
    diagnostics: {
        // ...
    },
    compilerOptions: {
        // ...
    },
    files: [
        { filePath: "...", size: 1234 }
    ]
}
```

The editor could choose to display this however it wants.

**Comment by DanielRosenwasser** [comment]
@mjbvz @amcasey

**Comment by DanielRosenwasser** [comment]
Things that might be useful

* Version
* Options (e.g. quote style) 
* Projects and what they contain
  * Project kinds (inferred, configured, etc.)
  * include/exclude?
  * file list
  * largest file and its size (maybe just sort files by size)
  * number of files
* number of errors reported 
* open file list
   * size, longest line length
* GUIDs of project kinds?

**Comment by DanielRosenwasser** [comment]
It sounds like editors can just maintain this information as well. Maybe we don't need to do anything in tsserver.

**Comment by sheetalkamat** [comment]
Since there was no work needed here, is it safe to close this?

**Comment by amcasey** [comment]
Fine by me.  We're tracking the VS work internally.
