### ISSUE TITLE
Type 'unknown' is not assignable to type 'A'.

### ISSUE THREAD

**Issue by hhelwich** [microsoft/TypeScript#31597]
**TypeScript Version:**  3.5.0-dev.20190525

**Code**

```ts
const compose = <X, Y, Z>(g: (y: Y) => Z, f: (x: X) => Y) => (x: X) => g(f(x))

const pipe = <X, Y, Z>(f: (x: X) => Y, g: (y: Y) => Z) => (x: X) => g(f(x))

const id = <A>(a: A) => a

const t0 = pipe(
  id,
  id
)

const t1 = compose(
  id,
  id // error here
)
```

**Expected behavior:**
I expected the code to transpile. Especially i expected the `pipe` and `compose` functions to behave similar because they are just different in the argument order.

**Actual behavior:**
I get a type error when calling `compose`:

> error TS2345: Argument of type '<A>(a: A) => A' is not assignable to parameter of type '(x: unknown) => A'.
>   Type 'unknown' is not assignable to type 'A'.

[Playground Link](https://www.typescriptlang.org/play/#src=const%20compose%20%3D%20%3CX%2C%20Y%2C%20Z%3E(g%3A%20(y%3A%20Y)%20%3D%3E%20Z%2C%20f%3A%20(x%3A%20X)%20%3D%3E%20Y)%20%3D%3E%20(x%3A%20X)%20%3D%3E%20g(f(x))%0D%0A%0D%0Aconst%20pipe%20%3D%20%3CX%2C%20Y%2C%20Z%3E(f%3A%20(x%3A%20X)%20%3D%3E%20Y%2C%20g%3A%20(y%3A%20Y)%20%3D%3E%20Z)%20%3D%3E%20(x%3A%20X)%20%3D%3E%20g(f(x))%0D%0A%0D%0Aconst%20id%20%3D%20%3CA%3E(a%3A%20A)%20%3D%3E%20a%0D%0A%0D%0Aconst%20t0%20%3D%20pipe(%0D%0A%20%20id%2C%0D%0A%20%20id%0D%0A)%0D%0A%0D%0Aconst%20t1%20%3D%20compose(%0D%0A%20%20id%2C%0D%0A%20%20id%20%2F%2F%20error%20here%0D%0A)%0D%0A)

**Comment by ahejlsberg** [comment]
This is a known design limitation. See #30215, in particular

> The above algorithm is not a complete unification algorithm and it is by no means perfect. In particular, it only delivers the desired outcome when types flow from left to right. However, this has always been the case for type argument inference in TypeScript, and it has the highly desired attribute of working well as code is being typed.

**Comment by hhelwich** [comment]
That is ok for me. Good to know. Thank you for the quick response!
