### ISSUE TITLE
Support type query for the function result

### ISSUE THREAD

**Issue by eos3tion** [microsoft/TypeScript#31594]
## Search Terms

* typeof function result

## Suggestion

Type Queries support for function result.
"typeof" can use for function result.

## Use Cases

With current version,if I want to get the type of function's result.
I need to execute `AAA()` like this:
```ts
function aaa(){
     //....Statement
    //....Statement
     return {
          a:true,
          b:1,
          c:"123"
    }
}
const resultAAA = aaa();
declare type TypeAAA = typeof resultAAA ;
```
then,you can use the type `TypeAAA`;
and TypeAAA equals :
```ts
interface TypeAAA {
a:boolean;
b:number;
c:string;
}
```
Why does  `type query` use for function result directly?
Like this:
```ts
declare type TypeAAA = typeof AAA();
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment]
You can do it:
```ts
declare type TypeAAA = ReturnType<typeof aaa>
```

It exists a `Parameters` generic type to get the parameters of a function.

[Playground](https://www.typescriptlang.org/play/#src=function%20aaa()%7B%0D%0A%20%20%20%20%20%2F%2F....Statement%0D%0A%20%20%20%20%2F%2F....Statement%0D%0A%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20a%3Atrue%2C%0D%0A%20%20%20%20%20%20%20%20%20%20b%3A1%2C%0D%0A%20%20%20%20%20%20%20%20%20%20c%3A%22123%22%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20resultAAA%20%3D%20aaa()%3B%0D%0Adeclare%20type%20TypeAAA_%20%3D%20typeof%20resultAAA%3B%0D%0Adeclare%20type%20TypeAAA%20%3D%20ReturnType%3Ctypeof%20aaa%3E%3B%0D%0A%0D%0A%0D%0Adeclare%20type%20paramsAAA%20%3D%20Parameters%3Ctypeof%20aaa%3E%3B%0D%0A).

**Comment by eos3tion** [comment]
@j-oliveras thank you!
