### ISSUE TITLE
Feature request: merge ttypescript

### ISSUE THREAD

**Issue by zaoqi** [microsoft/TypeScript#31593]
## Search Terms

* https://github.com/microsoft/TypeScript/issues/4892
* https://github.com/Microsoft/TypeScript/issues/16607
* https://github.com/microsoft/TypeScript/issues/28703

## Suggestion

https://github.com/cevek/ttypescript

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment]
Related to #14419.
