### ISSUE TITLE
Create infrastructure for experimental branches

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31591]
We'd like to create a vehicle for experimental branches that get merged into a temporary branch based off of `master` on a nightly basis, and published to npm. Presumably it'd be called something like `typescript@experimental`.

Users can use this branch to more-easily play with experimental features. This will allow us to keep branches in a reasonable state as they wait for the "feature" period of our release cycle, and will allow us to see how those features combine and interact.

This is a partial alternative to https://github.com/microsoft/TypeScript/issues/28152 - the main difference being that

* this allows features to not be merged into `master`
* experimental features aren't flagged because they're not even part of nightly

**Comment by weswigham** [comment]
FYI, the infra I actually already put in place mostly, I just need to prep and merge things into an experimental branch to test.

**Comment by DanielRosenwasser** [comment]
Great! But now you have an issue to track the work too 💯👍🏻💯🔥👌🏻💯👍🏻💯🔥👌🏻

**Comment by weswigham** [comment]
https://typescript.visualstudio.com/TypeScript/_build?definitionId=31
https://github.com/typescript-bot/TypeScript/tree/experimental

You'd like to see said experimental branch published, yes?

**Comment by DanielRosenwasser** [comment]
Yes, every night pls

**Comment by weswigham** [comment]
Opened #32411 and #32412 based on our discussion earlier to better service our prerelease build needs - I'll decommission the experimental branch build that's already been running once that's together.
