### ISSUE TITLE
ReturnType<> of function intersection inconsistent.

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31601]
**TypeScript Version:**  TS Playground version (3.4.1), 3.5.0-dev.20190523

**Search Terms:** ReturnType, function, intersection

**Code**

```ts

declare const f: & (() => { x: 4 }) & (() => { y: 3 });
//OK
//z is of type {x:4}
const z = f();
//OK
const hasX: { x: 4 } = z;
//Property 'y' is missing in type '{ x: 4; }' but required in type '{ y: 3; }'.
const hasY: { y: 3 } = z;

/**
 * Expected:
 * OK
 * z is of type {x:4}
 * 
 * Actual:
 * Property 'y' is missing in type '{ x: 4; }' but required in type '{ y: 3; }'.
 * z is of type {y:3}
 */
const z2: ReturnType<typeof f> = f();
/**
 * Expected: OK
 * Actual: Property 'x' is missing in type '{ y: 3; }' but required in type '{ x: 4; }'.
*/
const hasX2: { x: 4 } = z2;
/**
 * Expected: Property 'y' is missing in type '{ x: 4; }' but required in type '{ y: 3; }'.
 * Actual: OK
*/
const hasY2: { y: 3 } = z2;

```

**Expected behavior:**

Since function intersections are implemented as overloads,

always return the first return type.

**Actual behavior:**

Inconsistent return type.

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=%0D%0Adeclare%20const%20f%3A%20%26%20(()%20%3D%3E%20%7B%20x%3A%204%20%7D)%20%26%20(()%20%3D%3E%20%7B%20y%3A%203%20%7D)%3B%0D%0A%2F%2FOK%0D%0A%2F%2Fz%20is%20of%20type%20%7Bx%3A4%7D%0D%0Aconst%20z%20%3D%20f()%3B%0D%0A%2F%2FOK%0D%0Aconst%20hasX%3A%20%7B%20x%3A%204%20%7D%20%3D%20z%3B%0D%0A%2F%2FProperty%20'y'%20is%20missing%20in%20type%20'%7B%20x%3A%204%3B%20%7D'%20but%20required%20in%20type%20'%7B%20y%3A%203%3B%20%7D'.%0D%0Aconst%20hasY%3A%20%7B%20y%3A%203%20%7D%20%3D%20z%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Expected%3A%0D%0A%20*%20OK%0D%0A%20*%20z%20is%20of%20type%20%7Bx%3A4%7D%0D%0A%20*%20%0D%0A%20*%20Actual%3A%0D%0A%20*%20Property%20'y'%20is%20missing%20in%20type%20'%7B%20x%3A%204%3B%20%7D'%20but%20required%20in%20type%20'%7B%20y%3A%203%3B%20%7D'.%0D%0A%20*%20z%20is%20of%20type%20%7By%3A3%7D%0D%0A%20*%2F%0D%0Aconst%20z2%3A%20ReturnType%3Ctypeof%20f%3E%20%3D%20f()%3B%0D%0A%2F**%0D%0A%20*%20Expected%3A%20OK%0D%0A%20*%20Actual%3A%20Property%20'x'%20is%20missing%20in%20type%20'%7B%20y%3A%203%3B%20%7D'%20but%20required%20in%20type%20'%7B%20x%3A%204%3B%20%7D'.%0D%0A*%2F%0D%0Aconst%20hasX2%3A%20%7B%20x%3A%204%20%7D%20%3D%20z2%3B%0D%0A%2F**%0D%0A%20*%20Expected%3A%20Property%20'y'%20is%20missing%20in%20type%20'%7B%20x%3A%204%3B%20%7D'%20but%20required%20in%20type%20'%7B%20y%3A%203%3B%20%7D'.%0D%0A%20*%20Actual%3A%20OK%0D%0A*%2F%0D%0Aconst%20hasY2%3A%20%7B%20y%3A%203%20%7D%20%3D%20z2%3B%0D%0A)

**Related Issues:**

+ #25459 only had problems with `ReturnType<>` picking the return type of only one of the functions.

**Comment by jack-williams** [comment]
I think this is working as intended. Conditional type inference is done from the last overload not the first:

#21496: 

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types (this would require us to support typeof for arbitrary expressions, as suggested in #6606, or something similar).

**Comment by AnyhowStep** [comment]
Hmmm,

If the intention is to get the "most permissive catch-all case", wouldn't using the union of return types of each individual overload be better?

I'm pretty sure I've written overloads where each overload returned different types, and the last one wasn't a "permissive catch-all". Especially for generic functions, where allowing such an overload would makes type checks useless, because the result would be something like `unknown` or `unknown[]`.

-----

I guess I'll just treat this as a gotcha' and be careful with how I structure overloads from now on

**Comment by fatcerberus** [comment]
I’m assuming by the “last overload”, it means the *implementation signature*, which is the most permissive case by definition.

**Comment by AnyhowStep** [comment]
I just tested it,

```ts
function foo(x : 1): number;
function foo(x : 2): string;
function foo(x : 1|2): number | string {
    throw new Error("Not implemented");
}

//This is `string`
type r = ReturnType<typeof foo>;
```

[Playground](http://www.typescriptlang.org/play/#src=function%20foo(x%20%3A%201)%3A%20number%3B%0D%0Afunction%20foo(x%20%3A%202)%3A%20string%3B%0D%0Afunction%20foo(x%20%3A%201%7C2)%3A%20number%20%7C%20string%20%7B%0D%0A%20%20%20%20throw%20new%20Error(%22Not%20implemented%22)%3B%0D%0A%7D%0D%0A%0D%0A%2F%2FThis%20is%20%60string%60%0D%0Atype%20r%20%3D%20ReturnType%3Ctypeof%20foo%3E%3B)

**Comment by AnyhowStep** [comment]
Wait, what about this?

https://github.com/microsoft/TypeScript/issues/31601#issuecomment-496067284

Surely it's worth considering =/

It would be nice if `ReturnType_1<>` was `number` and not `never`.
Is there a reason to not make `ReturnType_1<>` return `number`?

**Comment by AnyhowStep** [comment]
I randomly came across this,
![image](https://user-images.githubusercontent.com/5655961/69897053-49674600-1314-11ea-8402-21fc272a96a0.png)

It made me think of how TS implements function overloads using intersection types.
It made me chuckle.
