### ISSUE TITLE
Generics; ReturnType<Function> not assignable to ReturnType<Function & (conditional type)>

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31602]
**TypeScript Version:**  TS Playground version (3.4.1), 3.5.0-dev.20190523

**Search Terms:** ReturnType, function, conditional type

**Code**

```ts
declare function doThing<
    F extends () => any
>(
    f: () => ReturnType<F>
): void;

//== This fails ==
type Bar<F extends () => any> = (
    & (() => ReturnType<F>)
    //Should be the same as `unknown`
    & (F extends any ? unknown : unknown)
);

function bar<F extends () => any>(f: F) {
    /*
        Fail
        
        Type 'ReturnType<F>' is not assignable to type
        'ReturnType<(() => ReturnType<F>) & (F extends any ? unknown : unknown)>'
        
        Type '() => any' is not assignable to type
        'F extends any ? unknown : unknown'
    */
    doThing<Bar<F>>(() : ReturnType<F> => {
        return f();
    });

    //Fail
    //Type '() => any' is not assignable to type 'F extends any ? unknown : unknown'
    const t: (
        F extends any ? unknown : unknown
    ) = ((): any => 3);

    //OK!
    const t2: (
        unknown
    ) = ((): any => 3);
}

//== This works ==
type Bar2<F extends () => any> = (
    & (() => ReturnType<F>)
    & unknown
);

function bar2<F extends () => any>(f: F) {
    //OK!
    doThing<Bar2<F>>(() : ReturnType<F> => {
        return f();
    });
}
```

**Expected behavior:**

All failures should work.

**Actual behavior:**

They do not work.

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=declare%20function%20doThing%3C%0D%0A%20%20%20%20F%20extends%20()%20%3D%3E%20any%0D%0A%3E(%0D%0A%20%20%20%20f%3A%20()%20%3D%3E%20ReturnType%3CF%3E%0D%0A)%3A%20void%3B%0D%0A%0D%0A%2F%2F%3D%3D%20This%20fails%20%3D%3D%0D%0Atype%20Bar%3CF%20extends%20()%20%3D%3E%20any%3E%20%3D%20(%0D%0A%20%20%20%20%26%20(()%20%3D%3E%20ReturnType%3CF%3E)%0D%0A%20%20%20%20%2F%2FShould%20be%20the%20same%20as%20%60unknown%60%0D%0A%20%20%20%20%26%20(F%20extends%20any%20%3F%20unknown%20%3A%20unknown)%0D%0A)%3B%0D%0A%0D%0Afunction%20bar%3CF%20extends%20()%20%3D%3E%20any%3E(f%3A%20F)%20%7B%0D%0A%20%20%20%20%2F*%0D%0A%20%20%20%20%20%20%20%20Fail%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20Type%20'ReturnType%3CF%3E'%20is%20not%20assignable%20to%20type%0D%0A%20%20%20%20%20%20%20%20'ReturnType%3C(()%20%3D%3E%20ReturnType%3CF%3E)%20%26%20(F%20extends%20any%20%3F%20unknown%20%3A%20unknown)%3E'%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20Type%20'()%20%3D%3E%20any'%20is%20not%20assignable%20to%20type%0D%0A%20%20%20%20%20%20%20%20'F%20extends%20any%20%3F%20unknown%20%3A%20unknown'%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20doThing%3CBar%3CF%3E%3E(()%20%3A%20ReturnType%3CF%3E%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20f()%3B%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0A%20%20%20%20%2F%2FFail%0D%0A%20%20%20%20%2F%2FType%20'()%20%3D%3E%20any'%20is%20not%20assignable%20to%20type%20'F%20extends%20any%20%3F%20unknown%20%3A%20unknown'%0D%0A%20%20%20%20const%20t%3A%20(%0D%0A%20%20%20%20%20%20%20%20F%20extends%20any%20%3F%20unknown%20%3A%20unknown%0D%0A%20%20%20%20)%20%3D%20(()%3A%20any%20%3D%3E%203)%3B%0D%0A%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20const%20t2%3A%20(%0D%0A%20%20%20%20%20%20%20%20unknown%0D%0A%20%20%20%20)%20%3D%20(()%3A%20any%20%3D%3E%203)%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%3D%3D%20This%20works%20%3D%3D%0D%0Atype%20Bar2%3CF%20extends%20()%20%3D%3E%20any%3E%20%3D%20(%0D%0A%20%20%20%20%26%20(()%20%3D%3E%20ReturnType%3CF%3E)%0D%0A%20%20%20%20%26%20unknown%0D%0A)%3B%0D%0A%0D%0Afunction%20bar2%3CF%20extends%20()%20%3D%3E%20any%3E(f%3A%20F)%20%7B%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20doThing%3CBar2%3CF%3E%3E(()%20%3A%20ReturnType%3CF%3E%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20f()%3B%0D%0A%20%20%20%20%7D)%3B%0D%0A%7D)

**Related Issues:**

+ #24277 is sort of similar?

**Comment by AnyhowStep** [comment]
Shorter repro, that shows it also fails for string assignments,

```ts
function bar<F>(f: F) {
    //Fail
    //Type '() => any' is not assignable to type 'F extends any ? unknown : unknown'
    const t: (
        F extends any ? unknown : unknown
    ) = ((): any => 3);

    //OK!
    const t2: (
        unknown
    ) = ((): any => 3);

    //Fail
    //Type 'string' is not assignable to type 'F extends any ? string : string'.
    const e: (
        F extends any ? string : string
    ) = ("test" as string);

    //Fail
    //Type 'string' is not assignable to type 'F extends any ? string : string'.
    const e2: (
        Extract<F extends any ? string : string, string>
    ) = ("test" as string);

    //OK!
    const e3: (
        string
    ) = ("test" as string);
}
```

[Playground](http://www.typescriptlang.org/play/#src=function%20bar%3CF%3E(f%3A%20F)%20%7B%0D%0A%20%20%20%20%2F%2FFail%0D%0A%20%20%20%20%2F%2FType%20'()%20%3D%3E%20any'%20is%20not%20assignable%20to%20type%20'F%20extends%20any%20%3F%20unknown%20%3A%20unknown'%0D%0A%20%20%20%20const%20t%3A%20(%0D%0A%20%20%20%20%20%20%20%20F%20extends%20any%20%3F%20unknown%20%3A%20unknown%0D%0A%20%20%20%20)%20%3D%20(()%3A%20any%20%3D%3E%203)%3B%0D%0A%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20const%20t2%3A%20(%0D%0A%20%20%20%20%20%20%20%20unknown%0D%0A%20%20%20%20)%20%3D%20(()%3A%20any%20%3D%3E%203)%3B%0D%0A%0D%0A%20%20%20%20%2F%2FFail%0D%0A%20%20%20%20%2F%2FType%20'string'%20is%20not%20assignable%20to%20type%20'F%20extends%20any%20%3F%20string%20%3A%20string'.%0D%0A%20%20%20%20const%20e%3A%20(%0D%0A%20%20%20%20%20%20%20%20F%20extends%20any%20%3F%20string%20%3A%20string%0D%0A%20%20%20%20)%20%3D%20(%22test%22%20as%20string)%3B%0D%0A%0D%0A%20%20%20%20%2F%2FFail%0D%0A%20%20%20%20%2F%2FType%20'string'%20is%20not%20assignable%20to%20type%20'F%20extends%20any%20%3F%20string%20%3A%20string'.%0D%0A%20%20%20%20const%20e2%3A%20(%0D%0A%20%20%20%20%20%20%20%20Extract%3CF%20extends%20any%20%3F%20string%20%3A%20string%2C%20string%3E%0D%0A%20%20%20%20)%20%3D%20(%22test%22%20as%20string)%3B%0D%0A%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20const%20e3%3A%20(%0D%0A%20%20%20%20%20%20%20%20string%0D%0A%20%20%20%20)%20%3D%20(%22test%22%20as%20string)%3B%0D%0A%7D)

**Comment by AnyhowStep** [comment]
For generics, I feel like if the true and false branches of a conditional type both extend some type `T`, the conditional type itself should also extend `T`.

I'm unsure how unfeasible it is, though.

**Comment by jack-williams** [comment]
> For generics, I feel like if the true and false branches of a conditional type both extend some type `T`, the conditional type itself should also extend `T`.

See #26933

**Comment by AnyhowStep** [comment]
Ah. I see there's a PR open for it already. I guess I can close this, and wait patiently for #30639 or some successor to get merged.
