### ISSUE TITLE
Array cannot infer multiple types with functions

### ISSUE THREAD

**Issue by Domino9697** [microsoft/TypeScript#31617]
**TypeScript Version:**  3.4.5 & 3.5.0-dev.20190525

**Search Terms:**
Array infer function generic types
**Code**

```ts
type ArgType<T> = {(): T}

type ArgTypes<T> = ArgType<T> | ArgType<T>[]

interface Test {
  test<T>(args: ArgTypes<T>): void
}

declare const Test: Test;

Test.test([() => "hello", () => 4])
```

**Expected behavior:**

I expect no errors and T should be inferred to `string | number`.

**Actual behavior:**

An error appears in the console:

```
Argument of type '((() => string) | (() => number))[]' is not assignable to parameter of type 'ArgTypes<string>'.
  Type '((() => string) | (() => number))[]' is not assignable to type 'ArgType<string>[]'.
    Type '(() => string) | (() => number)' is not assignable to type 'ArgType<string>'.
      Type '() => number' is not assignable to type 'ArgType<string>'.
        Type 'number' is not assignable to type 'string'.
```

**Playground Link:** 

https://www.typescriptlang.org/play/#src=type%20ArgType%3CT%3E%20%3D%20%7B()%3A%20T%7D%0D%0A%0D%0Atype%20ArgTypes%3CT%3E%20%3D%20ArgType%3CT%3E%20%7C%20ArgType%3CT%3E%5B%5D%0D%0A%0D%0Ainterface%20Test%20%7B%0D%0A%20%20test%3CT%3E(args%3A%20ArgTypes%3CT%3E)%3A%20void%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20Test%3A%20Test%3B%0D%0A%0D%0ATest.test(%5B()%20%3D%3E%20%22hello%22%2C%20()%20%3D%3E%204%5D)

**Comment by RyanCavanaugh** [comment]
This is an intentional trade-off so that generics can catch errors where you expect multiple objects to be of the same type, which is usually more common.

It doesn't seem like your function needs to be generic at all (it could just be `test(args: ArgTypes<unknown>)`, or you could specify `Test.test<string | number>(...`. If you have a more concrete use case I can advise on other ways to write the signature to accomplish what you're looking for.

**Comment by Domino9697** [comment]
Thank you for your answer @RyanCavanaugh ! I just provided a minimal reproduction of the issue.
I was actually working on Vue TypeScript and I need a generic function to infer the types of my component prop (to be used elsewhere).

I see your point but I did some more testing and I do not understand why my code above is not working while this code is:

```ts
type ArgType<T> = { (): T }

type ArgTypes<T> = ArgType<T> | ArgType<T>[]

type ArgDefinition<T> = {
  [K in keyof T]: ArgTypes<T[K]>
}

interface Test {
  test<T>(args: ArgDefinition<T>): void
}

declare const Test: Test;

Test.test({a: [() => "hello", () => 4]})
```

And T is correctly inferred as `{a: string | number}`.

**Comment by RyanCavanaugh** [comment]
It's a matter of whether inference collected multiple candidates or not. The OP has two inference sites, whereas the second example only has one because there's an object property "in the way".

**Comment by Domino9697** [comment]
Thank you @RyanCavanaugh for the explanation !

**Comment by nemosmithasf** [comment]
> It's a matter of whether inference collected multiple candidates or not. The OP has two inference sites, whereas the second example only has one because there's an object property "in the way".

@RyanCavanaugh, is there any documentation on the rules behind TS inferences? I've been playing around with the examples provided here for a while now, and I'm still not sure I fully understand what TS considers "multiple inference sites"

**Comment by xavdid** [comment]
@RyanCavanaugh re: concrete use case (that I _believe_ ties to this), we're trying to take a function and curry it to remove required properties. Something like:

```ts
// https://stackoverflow.com/a/61108377/1825390
type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>

interface Payload {
  a: number,
  b: number,
  c: number
}
const emit = (payload: Payload) => null

const addA = (payload: Optional<Payload, 'a'>): Payload => ({ a: 1, ...payload })
const addB = (payload: Optional<Payload, 'b'>): Payload => ({ b: 1, ...payload })

const wrappedEmit = (...funcs) => {
  return (partialPayload) => {
    const payload = funcs.reduce(...)
    return emit(payload)
  }
}

const emitWithOnlyC = wrappedEmit(addA, addB)

// only c is required in the payload object now
emitWithOnlyC({c: 1})
```

I've got a more complete [playground example](https://www.typescriptlang.org/play?#code/PTAEAsBdIBwZwFwjpAhgYwNYHsBuBTAJwDMAbbAdwDp1sBbYVYANgEZWAGADgGYB2PsFZcATAFYeATg4AoEKDqpM+UOiJoAlgDtQMQthjqN+OKAOQN2LalIzIAT0OgA8jAtWbAHgAqAGlAA0qD4AB6Q+FoAJqbK9tjEoN4AfKAAvKAAChpYnhmohBZeyf4BKQBkLnQakD4lSTIy2uEkGCp59uSokaAA3jKgoKgIoFoArnQARkT9oBPDY5PTA+jz41OEMgC+DfITqHAq+FWQI-j40YOkpIOEAOZwMrRaKMHHaaAAFDCoHdhdw+1OpEAJRpFJjK4NBxOABiAEkABoAWQAou9UFp7DswBQVBQMSdINhBpFulVSaR8PjCCpiKMtOh3M9QJBwKgTjS6HgVDSAI6jDQ07p6AxGEygYj6Oi6H5Ax5WF5dSIAQXeX1lf0iw1cTK8gM1-gA5KhDUlgQCNV0wZ8eoNhqx-FQnd9flbNsDsaAAAKQOAAWlChkZAcI+kIoD9I2JxsNoG0MtdkRkR2qH1tc1ADtUwxE-i1oB4oHdnvJkUp1JUNnIFFMMZZxKmCg0cDg2luyeOHyVyrTs3t-hWoBEReBHrkYC0lAHGNAuIUShU1VAtwiRGyAH55c8ThRCKgYIZIii3ukPk6qKXy-kTMN4ciUaDUik+gMaZBRoQdOqChobPr-pk+SFKQuSWpEZrWi+AygPIrLNqApDaIupisiosQRqoM5zooygsuAKjQio8Qyj+NgJkCoBwPQ+BwVotwIRouEAERVmYCSoWYbiWNY1yxKY8Ycd8e50KYxH4Bg4BxloMCjCcdIMkyTEzMsCpydof5ge8l5UtecBUEKoxqB8Xw0rgwwYvYA4fuZmKPs+ynQW+H46La57oB+Jn4LgoLbNBRb+EJwH-iCgymMFDlOZ+rypsQ6mkMFoLyF5RD2LR9HwXyApClGFAAIQzNs2xbi8KaQAActgqrpLu+6HseqbdmO8g+v6gb4MGRBhhhEygBU6CUeA2CjKQ3SNplgrnP4qADUNI2zERXEeLYpUVT2PTFuOiT4ao5AHC8uKGgQy7YNAER2I4KhIhoFI6TSML0ugng6txNgBPg9imKE4RRDE73EcFKSnjMLpAtqi08aBib+M9S1vR99R2YBpEgQDvWZNkmCQ0C0Pg6971wPUm1fXujJ4Qtuq8e9HxwKCkr0IMTY3RWEoPedTgomEJOQDDPFw3APiA4kwRhBEFxXUz173QynjaMQRCBCk66BKA8zJRsbMqMqpLKlL-XpOLZa3fguueDG9SESyrDvBzkBczzeMfZ4WsqrrKTyDJVyibJoAxp6VFkyyF1saA57aRWpioBM3KzrNo0qFRdA0eAbYMcom0ANrENg4YwlJgeGMRYe6cMNt27jpB854MJJAAup6ovHTYm1IrV5ylxgTKeOnBtXndD2myaST+D3Rsm4aEymsP12GxWY-oKaNcpH6KR1gAPj7E+gOvhrzzIQA) as well.
