### ISSUE TITLE
Type alias substitution does not work

### ISSUE THREAD

**Issue by polkovnikov-ph** [microsoft/TypeScript#31616]
**TypeScript Version:** 3.5.0-dev.20190525

**Search Terms:**
type substitution is incorrect

**Code**

```ts
const v = { test: { smth: 5 } };
type Field<A extends string, R> = { [K in A]: R } | {}
const f = <A extends string, B extends string, R>(x: { [K in A]: Field<B, R> } | {}): R => ({} as any);
const g = <A extends string, B extends string, R>(x: Field<A, Field<B, R>>): R => ({} as any);
const r1 = f(v); // number
const r2 = g(v); // unknown
```

**Expected behavior:**
Both should be `number`. 

**Actual behavior:**
`unknown`

**Playground Link:**
[Link](http://www.typescriptlang.org/play/#src=const%20v%20%3D%20%7B%20test%3A%20%7B%20smth%3A%205%20%7D%20%7D%3B%0D%0Atype%20Field%3CA%20extends%20string%2C%20R%3E%20%3D%20%7B%20%5BK%20in%20A%5D%3A%20R%20%7D%20%7C%20%7B%7D%0D%0Aconst%20f%20%3D%20%3CA%20extends%20string%2C%20B%20extends%20string%2C%20R%3E(x%3A%20%7B%20%5BK%20in%20A%5D%3A%20Field%3CB%2C%20R%3E%20%7D%20%7C%20%7B%7D)%3A%20R%20%3D%3E%20(%7B%7D%20as%20any)%3B%0D%0Aconst%20g%20%3D%20%3CA%20extends%20string%2C%20B%20extends%20string%2C%20R%3E(x%3A%20Field%3CA%2C%20Field%3CB%2C%20R%3E%3E)%3A%20R%20%3D%3E%20(%7B%7D%20as%20any)%3B%0D%0Aconst%20r1%20%3D%20f(v)%3B%20%2F%2F%20number%0D%0Aconst%20r2%20%3D%20g(v)%3B%20%2F%2F%20unknown)

**Related Issues:** 
Nope.

**Comment by RyanCavanaugh** [comment]
Regressed between 2.3 and 2.4

Removed suspect `| {}`:
```ts
const v = { test: { smth: 5 } };
type Field<A extends string, R> = { [K in A]: R };
const f = <A extends string, B extends string, R>(x: { [K in A]: Field<B, R> } ): R => ({} as any);
const g = <A extends string, B extends string, R>(x: Field<A, Field<B, R>>): R => ({} as any);
const r1 = f(v); // number
const r2 = g(v); // unknown
```

**Comment by weswigham** [comment]
Regression caused by https://github.com/microsoft/TypeScript/pull/15863 - potential fix is up at https://github.com/microsoft/TypeScript/pull/31633  - I need to run RWC to validate fp-ts doesn't OOM (which was what originally prompted the original change that caused the regression), since the change introducing the regression didn't come with any baked-in tests ❤️

**Comment by RyanCavanaugh** [comment]
These are both `number` now as expected
