### ISSUE TITLE
Extract type refactoring duplicates nearby comments

### ISSUE THREAD

**Issue by Tyriar** [microsoft/TypeScript#31629]
https://github.com/microsoft/vscode/issues/74310

![image](https://user-images.githubusercontent.com/2193314/58502969-858ad580-813c-11e9-86f5-57c6954c0caf.png)

![image](https://user-images.githubusercontent.com/2193314/58502989-8facd400-813c-11e9-9dc9-dba849e3e695.png)

**Comment by mjbvz** [comment]
Example code:

```ts
type a = { x: string } /* foo */ | string /* bar */;
```

Select the entire type and run `extract` type. Result:

```
type NewType = {
    x: string;
} /* foo */ | string /* bar */;

type a = NewType /* bar */;
```
