### ISSUE TITLE
False recursive inheritance error when paths are similar

### ISSUE THREAD

**Issue by troyji** [Microsoft/TypeScript#3162]
I have a TypeScript AMD class located at "/Scripts/App/MyClass.ts".  I have another class with the same relative file path inside of an MVC Area located at "/Areas/MyArea/Scripts/App/MyClass.ts" that inherits from the original class.

```typescript
// File: /Scirpts/App/MyClass.ts
class MyClass { ... }
export = MyClass;
```

```typescript
// File: /Areas/MyArea/Scirpts/App/MyClass.ts
import CoreMyClass = require("Scripts/App/MyClass");
class MyClass extends CoreMyClass { ... }
export = MyClass;
```

In the area's class, I receive the error "Type 'MyClass' recursively references itself as a base type".  Note that changing the name of one of the classes has no affect.  I speculate that the compiler assumes the two files are the same because they share a relative path, "/Scripts/App/MyClass.ts".  If I change one of the paths slightly (e.g. change App to App2), everything is happy.

Visual Studio 2015 RC
MVC5

**Comment by DanielRosenwasser** [comment]
I believe this resolution behavior is correct though perhaps @vladima can correct me. Have you tried `"../../Scripts/App/MyClass"`?

**Comment by troyji** [comment]
@DanielRosenwasser Yes, I have tried "../../Scripts/App/MyCLass".  The path is not recognized.

**Comment by vladima** [comment]
Currently module resolution in compiler is a mix of commonjs and requirejs and often if does not do the right thing. This is one of such cases - we should not do the folder walk to find the file in the first place. #2338 is a current proposal to improve the situation

**Comment by danquirk** [comment]
Will dupe against that.
