### ISSUE TITLE
Compiling with TSC vs Compiling in VisualStudio2013

### ISSUE THREAD

**Issue by josecasimiro** [Microsoft/TypeScript#3163]
Hey guys,

I'm trying out angular2, and I was having this issue where I could (while following the tutorials) use their dependency injection feature, but then in my project I kept getting errors.

I followed the tutorials just using the regular compiler tsc.exe, and for my project I'm on VisualStudio2013 with TypeScript 1.5 installed.

I'm using tsc.exe with the following parameters

`tsc --watch -m amd -t es5 --emitDecoratorMetadata jose-notes-list.ts`

This is What I get using tsc via command line

```javascript
if (typeof __decorate !== "function") __decorate = function (decorators, target, key, desc) {
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
    switch (arguments.length) {
        case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
        case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
        case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
    }
};
if (typeof __metadata !== "function") __metadata = function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
define(["require", "exports", 'angular2/angular2', "jose-notes-mockservice"], function (require, exports, angular2_1, jose_notes_mockservice_1) {
    // Annotation section
    var JoseNotesList = (function () {
        function JoseNotesList(joseNotesService) {
            this.notes = [];
            this.notes = joseNotesService.loadNotes();
        }
        JoseNotesList.prototype.hasNotes = function () {
            return this.notes.length > 0;
        };
        JoseNotesList = __decorate([
            angular2_1.Component({
                selector: 'jose-notes-list',
                injectables: [jose_notes_mockservice_1.JoseNotesMockService]
            }),
            angular2_1.View({
                templateUrl: 'Angular2/components/jose-notes-list.html',
                directives: [angular2_1.For, angular2_1.If]
            }), 
            __metadata('design:paramtypes', [jose_notes_mockservice_1.JoseNotesMockService])
        ], JoseNotesList);
        return JoseNotesList;
    })();
    exports.JoseNotesList = JoseNotesList;
});
```

This is what I get via VisualStudio2013 with TypeScript 1.5 plugin

```javascript
if (typeof __decorate !== "function") __decorate = function (decorators, target, key, desc) {
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
    switch (arguments.length) {
        case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
        case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
        case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
    }
};
define(["require", "exports", 'angular2/angular2', "jose-notes-mockservice"], function (require, exports, angular2_1, jose_notes_mockservice_1) {
    // Annotation section
    var JoseNotesList = (function () {
        function JoseNotesList(joseNotesService) {
            this.notes = [];
            this.notes = joseNotesService.loadNotes();
        }
        JoseNotesList.prototype.hasNotes = function () {
            return this.notes.length > 0;
        };
        JoseNotesList = __decorate([
            angular2_1.Component({
                selector: 'jose-notes-list',
                injectables: [jose_notes_mockservice_1.JoseNotesMockService]
            }),
            angular2_1.View({
                templateUrl: '../Shared/Views/Shared/JoseNotes/Angular2/components/jose-notes-list.html',
                directives: [angular2_1.For, angular2_1.If]
            })
        ], JoseNotesList);
        return JoseNotesList;
    })();
    exports.JoseNotesList = JoseNotesList;
});
//# sourceMappingURL=jose-notes-list.js.map
```

I'd like to bring your attention to the missing lines from 1st block to 2nd block

```javascript
if (typeof __metadata !== "function") __metadata = function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
```

and

```javascript
__metadata('design:paramtypes', [jose_notes_mockservice_1.JoseNotesMockService])
```

If I use the command line without the --emitDecoratorMetadata flag, then I get the same result with the TSC compiler as I do with visual studio. 

How do I make the plugin include that flag?

Thank you.

**Comment by DanielRosenwasser** [comment]
@josecasimiro that's odd; not sure how could've happend. Do you by chance have `tsc` installed through `npm`?

@JsonFreeman @paulvanbrenk

**Comment by JsonFreeman** [comment]
I think @paulvanbrenk has added an MSBuild property you can use in your project to turn this on. I think it's called TypeScriptEmitDecoratorMetadata, and if you set it to true, you should get the behavior you want.

**Comment by paulvanbrenk** [comment]
Yes, that option will be available in the final release of 1.5, until then you can add the compiler flag to an `<TypeScriptAdditionalFlags>` element.

**Comment by paulvanbrenk** [comment]
Did not mean to close it

**Comment by nycdotnet** [comment]
@paulvanbrenk Can you identify the complete list of MS Build tags added for 1.5?  I need them for csproj2ts and grunt-ts.

**Comment by paulvanbrenk** [comment]
@nycdotnet this is the complete list of MS Build tags we support in 1.5.

TypeScriptRemoveComments
TypeScriptNoImplicitAny
TypeScriptGeneratesDeclarations
TypeScriptModuleKind
TypeScriptOutFile
TypeScriptOutDir
TypeScriptSourceMap
TypeScriptTarget
TypeScriptNoResolve
TypeScriptAdditionalFlags
TypeScriptMapRoot
TypeScriptSourceRoot
TypeScriptCodePage
TypeScriptCharset
TypeScriptEmitBOM
TypeScriptNoLib
TypeScriptPreserveConstEnums
TypeScriptSuppressImplicitAnyIndexErrors 
TypeScriptNoEmitHelpers
TypeScriptInlineSourceMap
TypeScriptInlineSources
TypeScriptNewLine
TypeScriptSeparateCompilation
TypeScriptEmitDecoratorMetadata
TypeScriptRootDir

TypeScriptNoEmitOnError

**Comment by nycdotnet** [comment]
@paulvanbrenk Many thanks.  Is TypeScriptAdditionalFlags a catch-all for future use cases?  Like I could put `<TypeScriptAdditionalFlags>--foo</TypeScriptAdditionalFlags>` and it would pass `--foo` to the compiler?

**Comment by DanielRosenwasser** [comment]
For the record, we actually have a wiki page for this:

https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects

From the listed options, it's currently missing:

* TypeScriptEmitDecoratorMetadata
* TypeScriptInlineSourceMap
* TypeScriptInlineSources
* TypeScriptNewLine
* TypeScriptNoEmitHelpers
* TypeScriptRootDir
* TypeScriptSeparateCompilation

**Comment by nycdotnet** [comment]
Thanks @DanielRosenwasser .

**Comment by DanielRosenwasser** [comment]
> Is TypeScriptAdditionalFlags a catch-all for future use cases? Like I could put <TypeScriptAdditionalFlags>--foo</TypeScriptAdditionalFlags> and it would pass --foo to the compiler?

@nycdotnet just confirmed this is the case, though the language service won't pick up flags stuck in there.

**Comment by paulvanbrenk** [comment]
TypeScriptSeparateCompilation is renamed to TypeScriptSingleFile, @DanielRosenwasser can you update the wiki.

**Comment by DanielRosenwasser** [comment]
Done; has the flag itself been switched to `--singleFile`?

**Comment by paulvanbrenk** [comment]
We're terribly indecisive... it's TypeScriptIsolatedModule now

**Comment by nycdotnet** [comment]
If you add --allowSpecifyingAMDDefinitionFilePathSeparatelyFromRuntimeLocation, I'll forgive everything.

**Comment by mhegazy** [comment]
correction:) `--isolatedModules` with an `s` at the end. so probably `TypeScriptIsolatedModules` with an `s` as well

**Comment by paulvanbrenk** [comment]
Yes, @mhegazy  is correct..
