### ISSUE TITLE
Unable extract sub union object from a union object

### ISSUE THREAD

**Issue by calidion** [microsoft/TypeScript#31647]
**TypeScript Version:**  typescript@3.5.0-dev.20190529

**Search Terms:** 

union

**Code**

```ts
interface TypeA {
  a: number;
  b: string;
}

interface TypeB {
  a: number;
  b: number;
}

type TypeC = TypeA | TypeB;

interface d {
  i: number;
  c: TypeC;
}

const cd: TypeB = {
  a: 1,
  b: 1
};

const cd1: TypeA = {
  a: 1,
  b: "1"
};

function get(d: d) {
  const a: TypeA = d.c;
}

get({
  i: 1,
  c: cd
});

get({
  i: 1,
  c: cd1
});

```

**Expected behavior:**

passed

**Actual behavior:**

error:

```
29:9 - error TS2322: Type 'TypeC' is not assignable to type 'TypeA'.
  Type 'TypeB' is not assignable to type 'TypeA'.
    Types of property 'b' are incompatible.
      Type 'number' is not assignable to type 'string'.

29   const a: TypeA = d.c;
           ~

```

**Comment by dragomirtitian** [comment]
This a question, this forum is not intended for beginner questions, use stackoverflow to ask such questions and read the [docs](https://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types) on how union types work and type guards. This is the intended behavior, if something can be either `TypeA` or `TypeB` it is not safe to assign it so something typed as `TypeA`, what if at run-time it is actually `TypeB` ?

**Comment by calidion** [comment]
It is a problem of typescript, which declares to be the typed script and failed to check types at run time.

If union can not be exacted and recognized, then why union is introduced? 

use `any` instead then.

This can be a bug or a feature request, but will never be a question.

**Comment by jack-williams** [comment]
> If union can not be exacted and recognized, then why union is introduced?

That is what [narrowing](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types) is for. Unions let you be more specific about the possible types a value may take, enabling you to write correct run-time type checks.

**Comment by RyanCavanaugh** [comment]
Turns out we didn't ship a wrong implementation of union types for five years without noticing.

Seems we have some basic misunderstandings here. StackOverflow or the documentation would be a more appropriate venue to learn what unions do.

**Comment by calidion** [comment]
in effect

```
const a: TypeA = d.c; 
```
can be corrected by
```
const a: TypeA = d.c as TypeA; 
```

so why the compile can not deduce the type and force an `as` directive? when it is assigned to a specified type?
