### ISSUE TITLE
Support Visual Studio's "Add as Link" feature

### ISSUE THREAD

**Issue by IanKemp** [microsoft/TypeScript#31648]
I wanted to add a comment to #18755 but it's locked, so here it is again: the "Add as Link" feature in Visual Studio is very useful, but the VS/TS integration currently doesn't seem to support it, which IMO is a limitation of the tooling that should be able to be overcome.

Don't tell me to use symlinks; I don't want to, I want to use what's built into the IDE, thanks.

A naive way to accomplish this would be to perform a precompile pass to generate an "effective tsconfig" that explicitly pulls in all linked files in the csproj, then the TS compile uses that file instead of the project's one.

**Comment by RyanCavanaugh** [comment]
Yesterday's design limitation is also today's design limitation. We don't intend to support this.
