### ISSUE TITLE
Use keyof in Object.keys() when object is constant (as const) 

### ISSUE THREAD

**Issue by slorber** [microsoft/TypeScript#31652]
Hi,

Initial reasons for not using keyof in Object.keys: https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208

I know this subject is kind of a duplicate but I'd like to get it revisited as const assertions are a thing now.

If the object is constant, declared with a const assertion, wouldn't it make sense to return the Keys[] type instead of string[]?

## Use Cases

Get better typing with Object.keys() when possible

## Examples

```
const TestObject = {hey: "hoo",a: "bc"} as const;

const TestKeys = Object.keys(TestObject)
```

TestKeys should have type "hey" | "a"
## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
A type originating in an `as const` expression doesn't really imply that an object isn't aliased.

There'd have to be an entirely new way of writing signatures that only applied to "closed" objects, then new type system information for tracking which objects have a provably-closed set of keys and which don't. This is a lot of hoops to jump through for the sake of one built-in API.

What you're basically asking for is exact types, #12936

**Comment by slorber** [comment]
Thanks, didn 't know about those exact types ;)

**Comment by xprommer** [comment]
Maybe is there a way to define somehow properly `Object.keys(...)` to infer keys as `Array<keyof T>` for exact types and `string[]` otherwise? Because I didn't manage to find a solution how to combine these `Exact<...>` types with `Object.keys` ...
