### ISSUE TITLE
Clarify which project has missing reference

### ISSUE THREAD

**Issue by paulvanbrenk** [microsoft/TypeScript#31651]
While moving my TS project to using the new references I'm encountering a ton of the following errors.

`error TS6307: File '<path>/svgsurface.ts' is not in project file list. Projects must list all files or use an 'include' pattern.`

This error would be much more helpful if it included the name of the project this originates from... (I have approx 21 projects, and 450 of these errors)....

**Comment by paulvanbrenk** [comment]
@RyanCavanaugh I assume you would take a PR for this?

**Comment by DanielRosenwasser** [comment]
Thank you @paulvanbrenk!
