### ISSUE TITLE
void type field on class

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/TypeScript#3165]
This seems to be valid (tested in playground):

```
class Greeter {
    greeting1: void;
    greeting2: () => void;
}

var greeter = new Greeter();
```

Can you explain me what is gain to allow declaration of "greeting1" field?

**Comment by ahejlsberg** [comment]
`void` is treated just like any other type, so you can have variables, properties, parameters and so on of type `void` even though it isn't particularly useful. Because we allow `void` to be a type argument (which indeed is useful) we can't really treat `void` differently than other types. For example:
```typescript
class Greeter<T> {
    greeting1: T;
    greeting2: () => T;
}

var greeter = new Greeter<void>();
```
The `void` type is basically TypeScript's [Unit Type](http://en.wikipedia.org/wiki/Unit_type).

**Comment by wgebczyk** [comment]
Sure, but you could emit warning on such contructs as like you said "it isn't particularly useful". If you find reasonable useful usage, I would leave it as is.

This is one of reasons of having nice compiler - to find things that are potentially mistakes.

**Comment by RyanCavanaugh** [comment]
Some people like to use `void` to mean something akin to "this field is present, but always has the value 'undefined'". It's also useful for making "reserved" fields since nothing else is assignable to `void`

**Comment by wgebczyk** [comment]
Hmm... How can you have field in generated JS?
```
class Greeter {
    greeting: void;
    constructor(message: string) {
        // this.greeting = "aaa"; error
    }
}

var greeter = new Greeter("world");
var f = Object.getOwnPropertyNames(greeter);
document.write(`!${f.length}`);
```
The field is not generated, because there is no assignment. Can you point me to more practical example? Thanks!

**Comment by RyanCavanaugh** [comment]
```ts
class X {
	foo: void = undefined;
}
```

**Comment by wgebczyk** [comment]
OK, so first part answered, and examples of those people's libraries that do that? Thanks!

**Comment by RyanCavanaugh** [comment]
See comments deep in thread #185. Note: this is not an endorsement of using `T|void` :smiley:

**Comment by wgebczyk** [comment]
OK, so there might be reasonable use of field of void type. OK, bu it's so, so uncommon, that might be reasonable to generate warning for majority of situations and ask void-field users to wrap that with:
```javascript
// #pragma warning disable void-fields
someField: void;
// #pragma warning restore void-fields
```

This is like in c#
```csharp
private string _someField = "a";
```
generates: "warning CS0414: The field 'Aaa._someField' is assigned but its value is never used" and if necessary can be reflection accessed, so you can write:
```csharp
#pragma warning disable 0414
private string _someField = "a";
#pragma warning restore 0414
```
and access it via
```csharp
typeof(Aaa).GetField("_someField", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(this, "111");
```

If something is used only by 1% of people and for rest it usually means stinky mistake, put warning and everyone will be happy :)
