### ISSUE TITLE
Return type of a function gets incorrectly inferred when nesting a case in an if

### ISSUE THREAD

**Issue by archaeron** [microsoft/TypeScript#31653]
Return type of a function gets incorrectly inferred when nesting a case in an if.

I have reproduced this with `typescript@next` (`3.5.0-dev.20190529`)

**Search Terms:**
switch + return type
switch + noImplicitReturns 

**Code**

with the compiler option `noImplicitReturns`:

```ts
export type Q = { type: "A" } | { type: "B" };

export function f1(q: Q | undefined): string {
  if (q) {
    switch (q.type) {
      case "A":
        return "A";
      case "B":
        return "B";
    }
  } else {
    return "nothing";
  }
}

export function f2(q: Q | undefined): string {
  if (q) {
    return f2_help(q);
  } else {
    return "nothing";
  }
}

function f2_help(q: Q): string {
  switch (q.type) {
    case "A":
      return "A";
    case "B":
      return "B";
  }
}
```

**Expected behavior:**

I'd expect both `f1` and `f2` to compile, since I can get `f1` by inlining `f2_help` into `f2`.

**Actual behavior:**

But `f1` gives me an error:

Error:
```
testcase.ts:3:39 - error TS7030: Not all code paths return a value.

3 export function f1(q: Q | undefined): string {
                                        ~~~~~~

Found 1 error.
```

**Playground Link:**

NOTE: this only fails with `noImplicitReturns` turned on in the option (the option does not get saved in the url)

[Playground](https://www.typescriptlang.org/play/#src=export%20type%20Q%20%3D%20%7B%20type%3A%20%22A%22%20%7D%20%7C%20%7B%20type%3A%20%22B%22%20%7D%3B%0D%0A%0D%0Aexport%20function%20f1(q%3A%20Q%20%7C%20undefined)%3A%20string%20%7B%0D%0A%20%20if%20(q)%20%7B%0D%0A%20%20%20%20switch%20(q.type)%20%7B%0D%0A%20%20%20%20%20%20case%20%22A%22%3A%0D%0A%20%20%20%20%20%20%20%20return%20%22A%22%3B%0D%0A%20%20%20%20%20%20case%20%22B%22%3A%0D%0A%20%20%20%20%20%20%20%20return%20%22B%22%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20return%20%22nothing%22%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aexport%20function%20f2(q%3A%20Q%20%7C%20undefined)%3A%20string%20%7B%0D%0A%20%20if%20(q)%20%7B%0D%0A%20%20%20%20return%20f2_help(q)%3B%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20return%20%22nothing%22%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20f2_help(q%3A%20Q)%3A%20string%20%7B%0D%0A%20%20switch%20(q.type)%20%7B%0D%0A%20%20%20%20case%20%22A%22%3A%0D%0A%20%20%20%20%20%20return%20%22A%22%3B%0D%0A%20%20%20%20case%20%22B%22%3A%0D%0A%20%20%20%20%20%20return%20%22B%22%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Repository reproducing the issue**

https://github.com/archaeron/typescript-testcase

**Related Issues:** 

Might be related: https://github.com/microsoft/TypeScript/issues/31495

**Comment by RyanCavanaugh** [comment]
Duplicate #11572
