### ISSUE TITLE
Add Azure TS/JS SDK to user test suite

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31664]
In 3.5 we saw breakage in Azure's TS/JS SDK. Work with @jonathandturner to bring the Azure SDK into the user test suite so we can at least give an earlier warning of breaks.

https://github.com/Azure/azure-sdk-for-js

**Comment by jonathandturner** [comment]
cc @bterlson who was also meeting with other folks on the TS team about this
