### ISSUE TITLE
Experimental file watcher (or something else) doesn't seem to handle d.ts files properly.

### ISSUE THREAD

**Issue by haugerbr** [microsoft/TypeScript#31660]
Issue Type: <b>Bug</b>

If I have a .d.ts file that changes when I switch a branch in Git it causes the intellisense to show errors when a property is missing in that file that is referenced in the code which is the behavior I expect. However, when I build the project using an command line build task and the correct .d.ts gets generated, the files don't re-evaluate and find that there are on longer errors until I save the file or mess with it. This causes issues every time I pull a git branch from remote that causes changes in these files because I have to re-open vscode to get the errors to go away. 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (11.81GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.19.0
gitlens|eam|8.5.4
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
auto-run-command|gab|1.5.0
project-tasks|hau|1.0.0
vscode-test-explorer|hbe|1.1.0
docthis|joe|0.7.1
azure-account|ms-|0.4.2
azurecli|ms-|0.4.2
cpptools|ms-|0.17.7
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.2
vsliveshare|ms-|0.3.504
azurerm-vscode-tools|msa|0.4.2
debugger-for-chrome|msj|4.8.2
autolaunch|phi|2.0.2
project-snippets|reb|0.5.0
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.0.0
markdown-preview-enhanced|shd|0.3.5
save-and-run|wk-|0.0.21
JavaScriptSnippets|xab|1.7.0
livereload|zee|0.1.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
@haugerbr Are you using a task in VS Code to build, or building from the command line directly?

**Comment by iseekTo** [comment]
is a nice question

**Comment by sheetalkamat** [comment]
@haugerbr Please share your tsserver log for us to be able to investigate this.
You can upload logs using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) by following these steps:
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. You can share the logs using
    - either by sharing logs in the folder that gets opened by running `open tsserver log` from command palette 
    or
    - Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions and Then share the log file ID.

**Comment by haugerbr** [comment]
Thanks working on getting it to reproduce. Seems to only happen in certain conditions.

**Comment by haugerbr** [comment]
@sheetalkamat when I run `code --upload-logs` it just opens up a new vscode window and doesn't do anything else.

**Comment by haugerbr** [comment]
Closing as stale
