### ISSUE TITLE
Class Exspression cannot be used as Type

### ISSUE THREAD

**Issue by MarcelHeckel** [microsoft/TypeScript#31666]
**TypeScript Version:**  3.4.5

**Search Terms:**

typescript class expression TS2702 only refers to a type, but is being used as a namespace here

**Code**

```ts
class Foo {
  static Bar = class<T> {
  };

  blub ()
  // TS2702: 'Foo' only refers to a type, but is being used as a namespace here.
      : Foo.Bar {
      return new Foo.Bar(); // works !!!
  }
}


describe('inner classes tests', () => {
  test('1', () => {

    const foo = new Foo();
    const bar = new Foo.Bar(); // works!!!!


    if(!(foo instanceof Foo))
      throw new Error(("Foo.Bar"));
    if(!(bar instanceof Foo.Bar)) // works!!!!
      throw new Error(("Foo.Bar"));

    // TS2702: 'Foo' only refers to a type, but is being used as a namespace here.
    const bar2 : Foo.Bar = null;

  });

});
```

**Expected behavior:**

It should be possible to use the class expression name also in type declarations

**Actual behavior:**

Containing class of class expression is seen as namespace when used in type declarations

TS2702: 'Foo' only refers to a type, but is being used as a namespace here.

**Playground Link:** 

[code](https://www.typescriptlang.org/play/#src=class%20Foo%20%7B%0D%0A%20%20static%20Bar%20%3D%20class%3CT%3E%20%7B%0D%0A%20%20%7D%3B%0D%0A%0D%0A%20%20blub%20()%0D%0A%20%20%2F%2F%20TS2702%3A%20'Foo'%20only%20refers%20to%20a%20type%2C%20but%20is%20being%20used%20as%20a%20namespace%20here.%0D%0A%20%20%20%20%20%20%3A%20Foo.Bar%20%7B%0D%0A%20%20%20%20%20%20return%20new%20Foo.Bar()%3B%20%2F%2F%20works%20!!!%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%20%20%20%20const%20foo%20%3D%20new%20Foo()%3B%0D%0A%20%20%20%20const%20bar%20%3D%20new%20Foo.Bar()%3B%20%2F%2F%20works%20!!!%0D%0A%0D%0A%20%20%20%20if(!(foo%20instanceof%20Foo))%0D%0A%20%20%20%20%20%20throw%20new%20Error((%22Foo.Bar%22))%3B%0D%0A%20%20%20%20if(!(bar%20instanceof%20Foo.Bar))%20%2F%2F%20works%20!!!!%0D%0A%20%20%20%20%20%20throw%20new%20Error((%22Foo.Bar%22))%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20TS2702%3A%20'Foo'%20only%20refers%20to%20a%20type%2C%20but%20is%20being%20used%20as%20a%20namespace%20here.%0D%0A%20%20%20%20const%20bar2%20%3A%20Foo.Bar%20%3D%20null%3B%0D%0A)

**Related Issues:** 

no

**Comment by ilogico** [comment]
You mean `typeof Foo.Bar`.
As the error indicates, you're using `Foo` as if it were a namespace, but what you want is to extract the type of the expression `Foo.Bar`.

**Comment by MarcelHeckel** [comment]
Hi ilogico,

I'm not shout what you mean. With the fowlling code:

```ts
  blub() : typeof Foo.Bar {
    return new Foo.Bar();
  }
```
It complains about "TS2741: Property 'prototype' is missing in type '(Anonymous class)<{}>' but required in type 'typeof (Anonymous class)'."

Similar problem for

```ts
const bar2 : typeof Foo.Bar  = new Foo.Bar();
```
"TS2322: Type '(Anonymous class)<{}>' is not assignable to type 'typeof (Anonymous class)'."

**Comment by RyanCavanaugh** [comment]
You can refer to the instance type of the class by the name `InstanceType<typeof Foo.Bar>`

**Comment by weswigham** [comment]
It's proooobably worth noting that for some patterns, including the above, in JS it kinda works:
```ts
// @ts-check
class Foo {
	static Bar = class {
		/** @type {number} */
		x;
	};
  
	/** @return {Foo.Bar} */
	blub () {
		return new Foo.Bar(); // works !!!
	}
}

const x = new Foo().blub();
```
the quickinfo is all misleading `any` or `(Anonymous Type)`, but we're actually checking with the expected types.

**Comment by MarcelHeckel** [comment]
`InstanceType<typeof Foo.Bar>` works!
Thanks Ryan!
