### ISSUE TITLE
Assignment across the same type fails in TS 3.5

### ISSUE THREAD

**Issue by domoritz** [microsoft/TypeScript#31665]
I found an issue with assigning from one object to another when the types and key are the same. This issue did not occur in TS 3.4.

I understand that this is [fixing unsound assignments](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#breaking-changes) but I wonder what the right pattern is now.

**TypeScript Version:**  3.5

**Search Terms:** keyof, unsound, assigment

**Code**

```ts
type D = {
    foo?: number,
    bar?: string,
};

const a: D = {};
const b: D = {};

const k = "foo" as keyof D;

a[k] = b[k];
```

**Expected behavior:**

No error

**Actual behavior:**

```
Type 'string | number | undefined' is not assignable to type 'undefined'.
  Type 'string' is not assignable to type 'undefined'.
```

I have to write this to fix the issue (is there a better way?)

```ts
type D = {
    foo?: number,
    bar?: string,
};

const a: D = {};
const b: D = {};

const k = "foo" as keyof D;

a[k] = b[k] as any;
```

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
The safer version would be
```ts
(a[k] as D[keyof D]) = b[k];
```
This is probably an artifact of your repro reduction, but the cast-free initialization of `k` also checks without error:
```ts
const k: keyof D = "foo";
a[k] = b[k];
```

**Comment by domoritz** [comment]
Ahh, I see.

The specific use case for me was in an iteration over the keys of an object.

```ts
for (const k of Object.keyof(b) as (keyof D)[]) {
  a[k] = b[k];
}
```

Is there a different pattern that would make this code valid?

**Comment by domoritz** [comment]
I think may be related to problems with upgrading to TS 3.5 in https://github.com/vega/vega-lite/pull/5005 ([details](https://travis-ci.org/vega/vega-lite/jobs/539468408)).
