### ISSUE TITLE
[Proposal] Enum emitted code change

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/TypeScript#3167]
currently when using enums it is  impossible to resolve enum type at runtime because enum values are converted into nu=numbers

my proposal is change how  tsc generates enum into this:
```javascript
var Enum = (function () {
    function Enum(name, value) {
        this._name = name;
        this._value = value;
    }
    Enum.prototype.toString = function () { return this._name; };
    Enum.prototype.valueOf = function () { return this._value; };
    return Enum;
})();
var EnumName = (function (_super) {
    __extends(EnumName, _super);
    function EnumName() {
        _super.apply(this, arguments);
    }
    EnumName.item1 = new EnumName("item1", 0);
    EnumName.item2 = new EnumName("item2", 1);
    EnumName.item3 = new EnumName("item3", 2);
    return EnumName;
})(Enum);
```
**Enum** class will be generated by tsc(like function **__extends** currently is) and may have some usefull functions like **getNames**, **getValues**, etc.

[see this jsfiddle](http://jsfiddle.net/pcgmwc9y/2/) with some tests (basically just a proove of concept :)

cheers

**Comment by RyanCavanaugh** [comment]
This is too complex to justify building into the language.

Given an existing enum declaration and emit, you can already write code that will produce the kinds of structures you're describing automatically.
