### ISSUE TITLE
Consider allowing runtime error handling against object properties in switch default branches

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/TypeScript#31677]
## Search Terms

default switch object runtime never 

## Suggestion

Consider a way to allow runtime error handling of objects in `default` branch of a `switch` statement, possibly by allowing the switch condition even if it's been filtered to `never`?

## Use Cases

Handling unexpected data

## Examples

In this case `obj` gets filtered to `never`, but we still want runtime checking and error messages if, for example, an API returns an unexpected value.

```js
declare const obj: { value: 'A' } | { value: 'B' }; 

switch (obj.value) {
    case 'A': break;
    case 'B': break;
    default: throw new Error(`unhandled value: ${obj.value}`);
}
```

You can fix just the switch by switching on `const { value } = obj;`, but then `obj` isn't filtered in the switch for access to other keys.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
I don’t understand; this code should be fine since `never` is the bottom type and therefore assignable to everything?  So any error handling code should already work.  At least, this works in my experience...

**Comment by MarkKahn** [comment]
@fatcerberus -- `(obj: never).value` gives an error

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.

The only sane type to give `obj.value` would be `never` (since we know it's not `"A"` or `"B"`). And there's no principled reason that `obj.value` would be legal but not `obj.flarp`, since we clearly have no idea what `obj` actually is. Once you go down this rabbit hole, `never` would behave almost indistinguishably from `any`, which is *really* not what you want in code that should be unreachable. Having a value of type `never` indicates that something odd is happening and you should be made well aware of that fact.

**Comment by MartinJohns** [comment]
This is a use-case for the non-null assertion operator: `obj!.value`.

**Comment by fatcerberus** [comment]
If it were *just* narrowing `obj.value` to `never`, the code above would be just fine -  bottom type and all that.  It looks like the problem here is that the switch on `obj.value` is *also* narrowing `obj` due to discriminated union semantics, causing the error.

**Comment by MarkKahn** [comment]
Thanks for the explanations!
