### ISSUE TITLE
Omit and well-known symbols

### ISSUE THREAD

**Issue by sirian** [microsoft/TypeScript#31671]
Since `keyof T` doesn't contain well known symbols - it's hard to replace keys for arrays and other interfaces with well-known symbols

**TypeScript Version:**  3.5.1

**Search Terms:**
keyof symbol, well known symbols, omit symbols, exclude symbols

**Code**

```ts
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
type Replace<T, K extends keyof T, V> = Omit<T, K> & Record<K, V>;
type Foo = {
    x: string
    [Symbol.iterator](): any,
};

type Bar = {
    x: string,
};

type MustBe<T extends U, U> = T;
type Test = [
    MustBe<Replace<Foo, "x", string>, Foo>, // error
    MustBe<Replace<Bar, "x", string>, Bar>, // ok
    MustBe<Replace<true[], "length", number>, true[]> // error
];
```

[playground](https://www.typescriptlang.org/play/index.html#src=type%20Omit%3CT%2C%20K%20extends%20keyof%20any%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0Atype%20Replace%3CT%2C%20K%20extends%20keyof%20T%2C%20V%3E%20%3D%20Omit%3CT%2C%20K%3E%20%26%20Record%3CK%2C%20V%3E%3B%0D%0Atype%20Foo%20%3D%20%7B%0D%0A%20%20%20%20x%3A%20string%0D%0A%20%20%20%20%5BSymbol.iterator%5D()%3A%20any%2C%0D%0A%7D%3B%0D%0A%0D%0Atype%20Bar%20%3D%20%7B%0D%0A%20%20%20%20x%3A%20string%2C%0D%0A%7D%3B%0D%0A%0D%0Atype%20MustBe%3CT%20extends%20U%2C%20U%3E%20%3D%20T%3B%0D%0Atype%20Test%20%3D%20%5B%0D%0A%20%20%20%20MustBe%3CReplace%3CFoo%2C%20%22x%22%2C%20string%3E%2C%20Foo%3E%2C%0D%0A%20%20%20%20MustBe%3CReplace%3CBar%2C%20%22x%22%2C%20string%3E%2C%20Bar%3E%2C%0D%0A%20%20%20%20MustBe%3CReplace%3Ctrue%5B%5D%2C%20%22length%22%2C%20number%3E%2C%20true%5B%5D%3E%0D%0A%5D%3B%0D%0A)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/24622

**Comment by sirian** [comment]
Another tricky example is Rewrite
```typescript

```
![image](https://user-images.githubusercontent.com/897643/58622976-93c02980-82d5-11e9-836c-734cbc4ea1ce.png)


[playground](https://www.typescriptlang.org/play/index.html#src=type%20Rewrite%3CT%3E%20%3D%20%7B%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%7D%0D%0A%0D%0Ainterface%20A%20extends%20Array%3Cnumber%3E%20%7B%7D%0D%0A%0D%0Atype%20B%20%3D%20Array%3Cnumber%3E%3B%0D%0A%0D%0A%0D%0Aconst%20y%3A%20B%20%3D%201%20as%20any%20as%20Rewrite%3CB%3E%3B%0D%0Aconst%20x%3A%20A%20%3D%201%20as%20any%20as%20Rewrite%3CA%3E%3B%0D%0A)

**Comment by RyanCavanaugh** [comment]
This seems to be an observation, not a bug report.

**Comment by sirian** [comment]
https://github.com/microsoft/TypeScript/issues/31759
