### ISSUE TITLE
Undesirable(?) propagation of literal types with f-bounds

### ISSUE THREAD

**Issue by samskivert** [microsoft/TypeScript#31678]
**TypeScript Version:**  3.5.1

**Search Terms:** literal types, generic function or method, f-bounds

**Code**

```ts
class Box<A> {
  constructor (private value :A) {}
  get current () :A { return this.value }
  update (value :A) { this.value = value }
}

function box<A> (value :A) :Box<A> {
  return new Box(value)
}
const foo = box("a") // foo has type Box<string>
foo.update("b") // succeeds

type Data = void | boolean | number | string
function dbox<A extends Data> (value :A) :Box<A> {
  return new Box(value)
}
const dfoo = dbox("a") // dfoo has type Box<"a">
dfoo.update("b") // fails
```

**Expected behavior:**
`dfoo` has type `Box<string>`

**Actual behavior:**
`dfoo` has type `Box<"a">`

I include the `Data` type alias just to show how someone might fall into this trap. You can trigger the behavior with any f-bounds:

```ts
function dbox<A extends string> (value :A) :Box<A> {
  return new Box(value)
}
const dfoo = dbox("a") // dfoo has type Box<"a">
```

This is surely a gray area, in terms of prescribed behavior and even expected behavior, but I think it's a bit surprising that adding an f-bounds would change the way literal types are widened/propagated.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior - it turns out to be less surprising than *not* inferring literal types.

You can write something like this if you want to avoid a literal type being inferred:
```ts
type Data = void | boolean | number | string
type Widen<T> = T extends string ? string : T;
function dbox<A extends Data>(value: A) :Box<Widen<A>> {
  return new Box(value) as Box<Widen<A>>;
}
const dfoo = dbox("a") // dfoo has type Box<string>
dfoo.update("b") // ok
```

**Comment by ahejlsberg** [comment]
For more information on the rules for literal widening, see #10676.

**Comment by samskivert** [comment]
Many thanks for the prompt edification and pointing me to those two critical pieces of info (a: how to work around the too sharp inference, and b: the more detailed rules for inference of literal types, where I was able to find the explanation that inferred type parameters intentionally widen if the type parameter has no constraints).

Given that I scoured the internet for this information for at least half an hour prior to resorting to this bug report, I might humbly suggest that the tip on how to work around too sharp literal type inference be added to the _Advanced Types_ section of the TypeScript handbook and that a footnote be added to said section along the lines of "For detailed information on the inference of literal types, see [link to this Github PR]."

In any case thanks again for steering me in the right direction.
