### ISSUE TITLE
Disambiguating between module and variable when using `let`

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#3168]
Hi,

In the code below, I'm attempting to refer to the `foo` module, but the compiler issues an error:

```typescript
declare module foo {
	
	interface Bar {
		
	}
}

// Error: Block-scoped variable 'foo' used before its declaration.
let foo: foo.Bar; 
```

Is this expected? And how do I make this work without using `var'? I would like to use the same name for the module and the variable in order to avoid introducing unnecessary globals..

**Comment by danquirk** [comment]
The ```let foo``` and ```var foo``` behavior should just be the same, no error. We know a dotted identifier in type position has to be a container (like a namespace) and not the value foo.

**Comment by NoelAbrahams** [comment]
Here's another one taken from the NodeJS declarations:

```typescript

declare module "punycode" {
    interface ucs2 {
        decode(string: string): string;
        encode(codePoints: number[]): string;
    }

// error TS2448: Build: Block-scoped variable 'ucs2' used before its declaration
    export let ucs2: ucs2;
}

```
