### ISSUE TITLE
compiled(byte) code is failed to certify by Microsoft Windows APP certification process

### ISSUE THREAD

**Issue by soorireddy** [microsoft/TypeScript#31690]
**TypeScript Version:**  3.4.0-dev.201xxxxx
create a JS windows universal.
create new angular project and  ng build --prod , copy the artifact in WU App
create a package for App store.

in process of check it fails.

**Bytecode generation**
Error Found: The bytecode generation test detected the following errors:
runtime.741402d1d47331ce975c.js has JavaScript syntax or other problems.
polyfills.82883500a75c80c189dd.js has JavaScript syntax or other problems.

and
Error Found: The UTF-8 file encoding test detected the following errors:
main.554865c11d7a5138ceaf.js is not properly UTF-8 encoded. Re-save the file as UTF-8 (including Byte Order Mark).

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by j-oliveras** [comment]
If is a code generated by `typescript`, exist the option `emitBOM` to emit the BOM into generated files.

**Comment by RyanCavanaugh** [comment]
That error message is literally the only reason the `emitBOM` option exists 😁

**Comment by soorireddy** [comment]
it didn't work

here is the tsconfig
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "incremental":true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "emitBOM": true,
    "charset": "utf8",
    "alwaysStrict": true,
    "strict": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
