### ISSUE TITLE
Intellisense/TSServer bug with self reference of class in inheritance

### ISSUE THREAD

**Issue by lucasmciruzzi** [Microsoft/TypeScript#3170]
Given the following code:
````typescript
class Parent {
	public doStuff() {
		/* stuff */
		return this;
	}
}

class Child extends Parent {
	public doOtherStuff() {
		/* other stuff */
		return this;
	}
}

var child = new Child();
child.doStuff();
````
The last method returns the "this" from Parent (the doOtherStuff method doesn't exists), instead of Child, so extend becomes really anoying, because I have to workarounds (both bad):

**Workaround 1:**
````typescript
class Parent<Generic extends Parent<any>> {
	public doStuff(): Generic {
		/* stuff */
		return <Generic>this;
	}
}

class Child extends Parent<Child> {
	public doOtherStuff() {
		/* other stuff */
		return this;
	}
}

var child = new Child();
child.doStuff();
````
With this one, the result is the spected one, but the code is repetitive.

**Workaround 2:**
````typescript
class Parent {
	public doStuff() {
		/* stuff */
		return this;
	}
}

class Child extends Parent {
	public doStuff() {
		super.doStuff();
		/* stuff */
		return this;
	}
	public doOtherStuff() {
		/* other stuff */
		return this;
	}
}

var child = new Child();
child.doStuff();
````
With this one is even worst, because I need to write every inherited function again to recover the "this" of the child.

Is this a bug or a feature?. If not a bug, then could I ask for an explanation for this and a better workaround if there is one?

Thanks!

**Edit 1:**
I just tested the code in [Babel](https://babeljs.io), and in [io.js](http://iojs.org), and it works as excpected, so I think this is a TypeScript bug... [Check it here](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Parent%20%7B%0D%0A%20%20%20%20doStuff()%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F*%20stuff%20*%2F%0D%0A%20%20%20%20%20%20%20%20return%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Parent%20%7B%0D%0A%20%20%20%20doOtherStuff()%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F*%20other%20stuff%20*%2F%0D%0A%20%20%20%20%20%20%20%20return%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20child%20%3D%20new%20Child()%3B%0D%0Achild.doStuff()%3B)

**Edit 2:**
I use the TypeScript compiled code, and it works as excpected, so it's a problem with tsserver/intellisense.

**Comment by lucasmciruzzi** [comment]
I just tested the code in [Babel](https://babeljs.io), and in [io.js](http://iojs.org), and it works as excpected, so I think this is a TypeScript bug... [Check it here](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Parent%20%7B%0D%0A%20%20%20%20doStuff()%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F*%20stuff%20*%2F%0D%0A%20%20%20%20%20%20%20%20return%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Parent%20%7B%0D%0A%20%20%20%20doOtherStuff()%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F*%20other%20stuff%20*%2F%0D%0A%20%20%20%20%20%20%20%20return%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20child%20%3D%20new%20Child()%3B%0D%0Achild.doStuff()%3B)

**Comment by DanielRosenwasser** [comment]
I'm not sure if I understand correctly; is the issue you're having that without your workarounds, `child.doStuff()` returns type `Parent` instead of `Child`?

**Comment by DanielRosenwasser** [comment]
After looking more closely, I believe it is. If so, this is by design; however, we are issue #285 tracks a solution so that we can better serve you in what you're intending.

**Comment by CyrusNajmabadi** [comment]
The problem with the language currently is that there is no way to say "the result of this call is an instance of the value you called it on."   This makes chaining and fluent APIs difficult to write in the presence of subclassing.  This limitation is pretty common in many languages, though I'd definitely like to see some improvement here as well.

**Comment by danquirk** [comment]
See https://github.com/Microsoft/TypeScript/issues/513

**Comment by lucasmciruzzi** [comment]
@DanielRosenwasser edit the code to make it clear, the issue is that the Parent class is returned instead of Child.

@CyrusNajmabadi Agree, this is a bummer. I hope the TypeScript team can fix this, because is getting annoying pretty fast.

@danquirk great, I didn't found that early. Maybe this issue is related to #15 .... thanks!

**Comment by DanielRosenwasser** [comment]
As I've pointed out above #285 is indeed what you're looking for, with related issues linked to in #513.
