### ISSUE TITLE
FAQ typo in "Why is a file in the exclude list still picked up by the compiler?" question

### ISSUE THREAD

**Issue by gcox** [microsoft/TypeScript#31718]
**TypeScript Version:**  3.3.4

**Search Terms:**
"Why is a file in the exclude list still picked up by the compiler?"
"faq typo"

--- 

The FAQ question: [Why is a file in the exclude list still picked up by the compiler?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler) appears to contain a typo in the next-to-last paragraph. Unfortunately, the typo occurs at what is probably the most important part of the answer.

See the bolded segment and specifically the italicized consecutive occurrences of the word "all":
> So to exclude a file from the compilation, **you need to exclude and *all all* files** that have an import or /// <reference path="..." /> directives to them.

Seems like the first occurrence of "all" is covering up an important piece of information.

**Comment by RyanCavanaugh** [comment]
I fixed the typo but the section itself is still very confusingly written. The new Handbook will have a better section on this.
