### ISSUE TITLE
Error Stack Showing Typescript Files

### ISSUE THREAD

**Issue by Skillz4Killz** [microsoft/TypeScript#31727]
## Search Terms

error stack, error stack typescript, error stack path

## Suggestion

Can Typescript somehow return errors using the TS files? Stack errors being in the `output` folder is kinda annoying because based on tsconfig settings they can be massively different lines. I am not sure what the best way to achieve this behavior is or if its already possible. I have looked into it quite a bit but found no solution for trying to get errors reported to me based on the Typescript files.

## Use Cases

For example, take a well-commented file in TS where tsconfig removes the comments and the lines are completely different. Imagine having a library with JSDocs or other ways that lines of code becomes changed because of the compiler. 

It is quite annoying to have to go into the output folder which can be quite harder to read as compared to the TS files that most devs are used to looking at because that is what they code on daily.

## Examples
Current Stack Error Response
```js
filename.js:148:52
```

Suggested Stack Error Response
```js
filename.ts:360:52
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Thank You <3

**Comment by fatcerberus** [comment]
This isn't something TypeScript (being a compiler) has any control over.  Errors are produced by the runtime and/or debugger; TypeScript *can*, however, generate source maps so you should have `"sourceMap": true` in your tsconfig and also check that your development environment supports them.

**Comment by ajafff** [comment]
You probably want to emit sourceMaps as described above and then use https://www.npmjs.com/package/source-map-support at runtime to adjust the error stack.

**Comment by kitsonk** [comment]
Yes, TypeScript doesn't generate any runtime error messages.  Assuming you generate the source maps, most browsers will automatically remap the error stacks in the debug console and many of the bundlers/builders will remap source maps to the final bundle so you get source code positions.  VSCode when running the debugger will also allow you to set breaks and watches at source code.

**Comment by Skillz4Killz** [comment]
Thank you source maps for the win!

**Comment by nfmelendez** [comment]
Aftyer node 12,  the parameter --enable-source-maps is the best way to achieve  meanful stacktrace in typescript
