### ISSUE TITLE
[Question] Current emit for string literal type annotations

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#3172]
A string literal annotation currently emits:
https://github.com/Microsoft/TypeScript/blob/78197ed60b92ca54b6b88c044e7016d1f6090e09/tests/baselines/reference/parserErrorRecovery_IncompleteMemberVariable1.js#L41

Is this a bug?

If it is, good have the fix :smile:

**Comment by DanielRosenwasser** [comment]
A string literal annotation currently isn't syntactically valid TypeScript, and we don't make any guarantees of emit in the presence of syntactic invalidity, so it's not a bug.

**Comment by CyrusNajmabadi** [comment]
@DanielRosenwasser is right.  Your code is syntactically incorrect.  If you compile it, you should see:

```File.ts(12,21): error TS1110: Type expected.```

We emit the file as we interpreted it.  In this case, we interpreted the code as having a missing type annotation, with a string literal initializer.
