### ISSUE TITLE
'file' urls are improperly normalized

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#3173]
Compiler improperly normalizes filenames that are 'file' uri. In particular is 'host' part is omitted compiler removes mandatory slash that should be present after '://' so uri 
```
file:///a/b/c.txt
```
becomes
```
file://a/b/c
```

This issue is a blocks passing tests in the fork of es6 module loader where TypeScript is added as a fully supported transpiler

**Comment by mhegazy** [comment]
@vladima is this meged into release-1.5? if not we need to merge it in.

**Comment by vladima** [comment]
It is not merged yet.
Also there is a list of PRs that should get into 1.5, I'll send it to you shortly

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, May 18, 2015 at 11:01 AM -0700, "Mohamed Hegazy" <notifications@github.com<mailto:notifications@github.com>> wrote:


@vladima<https://github.com/vladima> is this meged into release-1.5? if not we need to merge it in.

-
