### ISSUE TITLE
Improve error message for stricter types not matching generic `T extends SomeInterface`

### ISSUE THREAD

**Issue by patrys** [microsoft/TypeScript#31739]
## Search Terms

generic type is not assignable to type error 

## Suggestion

It's impossible for a non-generic type to be assignable to a generic that `extends` an interface. This is understandable as at the time of type checking it's impossible to determine the generic type's fields. It would be nice if the error message explained that instead of just saying that the types are incompatible.

## Use Cases

See the example below:

## Examples

```typescript
interface Foo {
    bar: string;
}

function baz<T extends Foo> {
    const fizz: T = { bar: "hello world " };
}
```

Current error:

```
Type '{ bar: string; }' is not assignable to type 'T'.
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
This is fixed by #30394
