### ISSUE TITLE
3.5 regression concerning type inference for non-inferable types

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#31735]
**TypeScript Version:**  typescript@3.6.0-dev.20190603

**Search Terms:**
3.5, infer

**Code**

```ts
// mocked CssProperties type
type CssProperties = { position: "absolute" | "relative" };

type StylesObject<ClassKey extends string> = Record<ClassKey, CssProperties>;
type PropsBasedstyles<ClassKey extends string, Props extends object> = (
  props: Props
) => StylesObject<ClassKey>;
type Styles<ClassKey extends string, Props extends object> =
  | StylesObject<ClassKey>
  | PropsBasedstyles<ClassKey, Props>;

function createStyles<ClassKey extends string, Props extends object>(
  styles: Styles<ClassKey, Props>
): Styles<ClassKey, Props> {
  return styles;
}

const styles = createStyles({
  root: {
    position: "absolute"
  }
});
```

**Expected behavior:**
Behavior in 3.4.5
`typeof styles = Styles<'root', {}>`

**Actual behavior:**
Behavior in >=3.5.0
`typeof styles = Styles<'root', object>`

**Playground Link:** 
[playground](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20mocked%20CssProperties%20type%0Atype%20CssProperties%20%3D%20%7B%20position%3A%20%22absolute%22%20%7C%20%22relative%22%20%7D%3B%0A%0Atype%20StylesObject%3CClassKey%20extends%20string%3E%20%3D%20Record%3CClassKey%2C%20CssProperties%3E%3B%0Atype%20PropsBasedstyles%3CClassKey%20extends%20string%2C%20Props%20extends%20object%3E%20%3D%20(%0A%20%20props%3A%20Props%0A)%20%3D%3E%20StylesObject%3CClassKey%3E%3B%0Atype%20Styles%3CClassKey%20extends%20string%2C%20Props%20extends%20object%3E%20%3D%0A%20%20%7C%20StylesObject%3CClassKey%3E%0A%20%20%7C%20PropsBasedstyles%3CClassKey%2C%20Props%3E%3B%0A%0Afunction%20createStyles%3CClassKey%20extends%20string%2C%20Props%20extends%20object%3E(%0A%20%20styles%3A%20Styles%3CClassKey%2C%20Props%3E%0A)%3A%20Styles%3CClassKey%2C%20Props%3E%20%7B%0A%20%20return%20styles%3B%0A%7D%0A%0Aconst%20styles%20%3D%20createStyles(%7B%0A%20%20root%3A%20%7B%0A%20%20%20%20position%3A%20%22absolute%22%0A%20%20%7D%0A%7D)%3B%0A)

**Related Issues:** Did not find any

**Notes:**

Seems like the playground is still using 3.4.

Usage of this behavior is showcased in https://github.com/eps1lon/ts-inference-3.5/blob/master/index.ts with [a fix](https://github.com/eps1lon/ts-inference-3.5/commit/d5aea637aaa556324cce8d4d7f81769166c77568) for 3.5.

**Comment by ahejlsberg** [comment]
This is an effect of #30637, a known breaking change. In your example we make no inferences for the `Props` type parameter in the call to `createStyles`. This means we default to `unknown`, but since that doesn't satisfy the constraint `object`, we pick `object`. Previously we'd default to `{}` which did satisfy the constraint.

**Comment by eps1lon** [comment]
Suspected as much though I wasn't aware how this interacts with non-inferrable types. Thanks for the explanation.
