### ISSUE TITLE
Annotation of boolean type ignore in favor of narrowed type

### ISSUE THREAD

**Issue by drew-gross** [microsoft/TypeScript#31734]
**TypeScript Version:**  3.5.1

**Search Terms:**

Boolean explicit annotation ignore

**Code**

```ts
// Errors as expected
let bothInferred = true;
if (bothInferred == false) { }

// Doesn't error as expected 
let bothExplicit: boolean = true as boolean;
if (bothExplicit == false) { }

// Doesn't error as expected
let leftInferredRightExplicit = true as boolean;
if (leftInferredRightExplicit == false) { }

// Why error? Narrow rhs overrides explicit declaration.
let rigthInferredLeftExplicit: boolean = true;
if (rigthInferredLeftExplicit == false) { }
```

**Expected behavior:**

4th example above shouldn't error.

**Actual behavior:**

Error: This condition will always return 'false' since the types 'true' and 'false' have no overlap.

**Playground Link:** 

https://www.typescriptlang.org/play/#src=%2F%2F%20Errors%20as%20expected%0D%0Alet%20bothInferred%20%3D%20true%3B%0D%0Aif%20(bothInferred%20%3D%3D%20false)%20%7B%20%7D%0D%0A%0D%0A%2F%2F%20Doesn't%20error%20as%20expected%20%0D%0Alet%20bothExplicit%3A%20boolean%20%3D%20true%20as%20boolean%3B%0D%0Aif%20(bothExplicit%20%3D%3D%20false)%20%7B%20%7D%0D%0A%0D%0A%2F%2F%20Doesn't%20error%20as%20expected%0D%0Alet%20leftInferredRightExplicit%20%3D%20true%20as%20boolean%3B%0D%0Aif%20(leftInferredRightExplicit%20%3D%3D%20false)%20%7B%20%7D%0D%0A%0D%0A%2F%2F%20Why%20error%3F%0D%0Alet%20rigthInferredLeftExplicit%3A%20boolean%20%3D%20true%3B%0D%0Aif%20(rigthInferredLeftExplicit%20%3D%3D%20false)%20%7B%20%7D%0D%0A

**Related Issues:** 

Tried similar patterns with other types, could not find an error.

**Comment by ajafff** [comment]
Union types are narrowed on assignment. `boolean` is a union type `true | false` behind the scenes

**Comment by drew-gross** [comment]
Ah yeah I could reproduce the error with a different union type

```
type U = "a" | "b";

let u: U = "a";

if (u == "b") {
    console.log();
}
```

Seems like an explicit annotation should override narrowing though? Explicit seems like it should always win over any type of inference.

**Comment by RyanCavanaugh** [comment]
> Seems like an explicit annotation should override narrowing though? 

Intuitively, there should really not be a difference between
```ts
let u: U = "a";
/* some statement */
```
and
```ts
let u: U;
u = "a";
/* some statement */
```

**Comment by drew-gross** [comment]
Huh, intuitively I think of the things on the left of an assignment as happening _after_ the things on the right. Maybe this is my C++ background coming through (https://godbolt.org/z/VvVzbE). I guess for javascript both ways are equally valid though.

**Comment by jcalz** [comment]
Cross-linking to #8513, of which this issue is arguably a duplicate

**Comment by matt-tingen** [comment]
This behavior is unintuitive to me, as well. In particular, with aliased object types, adding a widening type annotation can actually result in narrowing:
```ts
type Open = { isOpen: true };
type Closed = { isOpen: false };
type Status = Open | Closed;

const openBare = { isOpen: true };
const openAnnotated: Status = { isOpen: true };

type Bare = typeof openBare; // { isOpen: boolean }
type Annotated = typeof openAnnotated; // { isOpen: true }
```
