### ISSUE TITLE
Values of string literal type are ignored in generic function

### ISSUE THREAD

**Issue by maxkomarychev** [microsoft/TypeScript#31732]
String literal types are ignored and treated as just "string" when working with generics.

Also the line ("Test 3") which is expectedly fails to compile the error message contains this:
```
        Type 'number' is not assignable to type '"three" | "four"'.
```
but actual problem in line "Test 2" seems to ignore this fact

**TypeScript Version:**  

```bash
$ tsc --version
Version 3.5.1
```

**Search Terms:**

**Code**

```ts
interface PropTypes {
    one: number,
    two: "three"|"four"
}

type ComponentType<P> = (props:P) => any

const MyCompnent = (props: PropTypes) => console.log(props)
MyCompnent({ one: 100, two: "three" })

function decorate<P>(props: P): (Wrapped: ComponentType<P>) => ComponentType<P> {
    return function wrap<P>(Wrapped: ComponentType<P>): ComponentType<P> {
        return (props: P) => console.log({ ...props })
    }
}

// Test 1: should work, all is good
const enhanced1 = decorate({ one: 42, two: "three" })(MyCompnent)
// Test 2: should not work because "two" only allows "three" or "four" as values
const enhanced2 = decorate({ one: 42, two: "wut" })(MyCompnent)
// Test 3: does not work because "two" should be "string", not "number"
const enhanced3 = decorate({ one: 42, two: 111 })(MyCompnent)

```

**Expected behavior:**

the following piece of code:

```ts
// Test 2: should not work because "two" only allows "three" or "four" as values
const enhanced2 = decorate({ one: 42, two: "wut" })(MyCompnent)
```

should not be compiled since `MyComponent` does not allow value "wut" for field "two".

**Actual behavior:**

```
Bug.ts:22:51 - error TS2345: Argument of type '(props: PropTypes) => void' is not assignable to parameter of type 'ComponentType<{ one: number; two: number; }>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type '{ one: number; two: number; }' is not assignable to type 'PropTypes'.
      Types of property 'two' are incompatible.
        Type 'number' is not assignable to type '"three" | "four"'.

22 const enhanced3 = decorate({ one: 42, two: 111 })(MyCompnent)
```

**Playground Link:** 

[playground](https://www.typescriptlang.org/play/#src=interface%20PropTypes%20%7B%0D%0A%20%20%20%20one%3A%20number%2C%0D%0A%20%20%20%20two%3A%20%22three%22%7C%22four%22%0D%0A%7D%0D%0A%0D%0Atype%20ComponentType%3CP%3E%20%3D%20(props%3AP)%20%3D%3E%20any%0D%0A%0D%0Aconst%20MyCompnent%20%3D%20(props%3A%20PropTypes)%20%3D%3E%20console.log(props)%0D%0AMyCompnent(%7B%20one%3A%20100%2C%20two%3A%20%22three%22%20%7D)%0D%0A%0D%0Afunction%20decorate%3CP%3E(props%3A%20P)%3A%20(Wrapped%3A%20ComponentType%3CP%3E)%20%3D%3E%20ComponentType%3CP%3E%20%7B%0D%0A%20%20%20%20return%20function%20wrap%3CP%3E(Wrapped%3A%20ComponentType%3CP%3E)%3A%20ComponentType%3CP%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20(props%3A%20P)%20%3D%3E%20console.log(%7B%20...props%20%7D)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Test%201%3A%20should%20work%2C%20all%20is%20good%0D%0Aconst%20enhanced1%20%3D%20decorate(%7B%20one%3A%2042%2C%20two%3A%20%22three%22%20%7D)(MyCompnent)%0D%0A%2F%2F%20Test%202%3A%20should%20not%20work%20because%20%22two%22%20only%20allows%20%22three%22%20or%20%22four%22%20as%20values%0D%0Aconst%20enhanced2%20%3D%20decorate(%7B%20one%3A%2042%2C%20two%3A%20%22wut%22%20%7D)(MyCompnent)%0D%0A%2F%2F%20Test%203%3A%20does%20not%20work%20because%20%22two%22%20should%20be%20%22string%22%2C%20not%20%22number%22%0D%0Aconst%20enhanced3%20%3D%20decorate(%7B%20one%3A%2042%2C%20two%3A%20111%20%7D)(MyCompnent)%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@ahejlsberg I think this would be covered by the reverse return type inference we were discussing yesterday?

**Comment by ahejlsberg** [comment]
@RyanCavanaugh No, generic return type inference doesn't cover this. When the result of a function call is the source of an assignment and we have a known type on the target side we'll perform generic return type inference. However, in this example, the result of the first function call is the function value for the second function call, so there is no contextual typing.

**Comment by ahejlsberg** [comment]
This is working as intended. In `--strict` mode all three calls are errors. Since there is no contextual type for the argument to `decorate` we infer type `{ one: number, two: string }` in the first two calls and `{ one: number, two: number }` in the last call. This is less specific than the `PropTypes` required by `MyCompnent` and thus an error. You can force inference of literal types using a `const` assertion:

```ts
const enhanced1 = decorate({ one: 42, two: "three" } as const)(MyCompnent)
const enhanced2 = decorate({ one: 42, two: "wut" } as const)(MyCompnent)
const enhanced3 = decorate({ one: 42, two: 111 } as const)(MyCompnent)
```

The first call then works and the second two fail as expected.

Now, the reason the first two calls aren't errors in non-strict mode is that we check parameter types bivariantly when relating function types (which is unsound). We default to non-strict for reasons of backwards compatibility, but we definitely recommend using `--strict` or at least `--strictFunctionTypes`.

**Comment by ahejlsberg** [comment]
Also, #31243 is a suggestion to perform generic return type inference for functions returning functions that are immediately invoked. That would cause us to contextually type the argument to `decorate` by `PropTypes` which would produce the expected outcome without `const` assertions.
