### ISSUE TITLE
VSCode [Insiders]: Javascript/TypeScript React IntelliSense not working

### ISSUE THREAD

**Issue by dalisoft** [microsoft/TypeScript#31749]
![](http://joxi.ru/brRkzqjc7nBVym?d=1)
![](http://joxi.ru/ZrJZzx4cwWQeNr?d=1)
![](http://joxi.ru/LmGd9O4cwYBbd2?d=1)
![](http://joxi.ru/YmE6zlYiwDG9W2?d=1)

### `jsconfig.json`
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es2017",
    "allowSyntheticDefaultImports": true
  },
  "exclude": ["node_modules"]
}
```

- VSCode Version: 1.35.0-insider (2019-05-31T21:19:51.263Z)
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Use any VSCode
2. Try add any React lifecycle methods on React class component

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur on Stable release?: Yes
Does this issue occur when using TypeScript?: Yes (just tested)

### Tried solution
- `npm i @types/react -D`
- `import * as React from 'react' // insteadof import React from 'react'`
- Resetting VSCode
- Clean reinstall project packages

**Comment by mjbvz** [comment]
Tested on TS-3.6.0-dev.20190603

**Repo steps**
1. `npm i @types/react react`
1. In a js file:

```js
import * as React from 'react';

class MyComponent extends React.PureComponent {
    static propTypes = {

	};

}
```

1. Trigger suggestions in the class body after the `propTypes` declaration

**Expected**
We get suggestions for the methods/props from `PureComponent`

**Actually**
We only get a suggestion for `contextType`:

![Screen Shot 2019-06-03 at 6 10 23 PM](https://user-images.githubusercontent.com/12821956/58844182-ef1e4e80-862a-11e9-8807-b0f60a883677.png)

**Comment by dalisoft** [comment]
Any news?

**Comment by mjbvz** [comment]
Tested with TS 4.0 nightly and TS 3.7.5. Both seem fixed:

<img width="1158" alt="Screen Shot 2020-07-29 at 4 45 59 PM" src="https://user-images.githubusercontent.com/12821956/88864834-fd2e1780-d1ba-11ea-89b3-ca76c1fb50ce.png">
