### ISSUE TITLE
Fix Pick type

### ISSUE THREAD

**Issue by sirian** [microsoft/TypeScript#31759]
Current version of pick works incorretly for interfaces with symbols

**TypeScript Version:**  3.5.1

```ts
type Arr = [1, 2];

type CorrectPick<T, K extends keyof T> = {[P in keyof T]: P extends K ? T[P] : never};
const p1: Arr = [] as any as Pick<Arr, keyof Arr>; // error
const p2: Arr = [] as any as CorrectPick<Arr, keyof Arr>; //ok

type CorrectOmit<T, K extends keyof T>= CorrectPick<T, Exclude<keyof T, K>>;
const o1: Arr = [] as any as Omit<Arr, never>; // error
const o2: Arr = [] as any as CorrectOmit<Arr, never>; //ok
```

[playground](https://www.typescriptlang.org/play/index.html#src=type%20Arr%20%3D%20%5B1%2C%202%5D%3B%0D%0A%0D%0Atype%20CorrectPick%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20%7B%5BP%20in%20keyof%20T%5D%3A%20P%20extends%20K%20%3F%20T%5BP%5D%20%3A%20never%7D%3B%0D%0Aconst%20p1%3A%20Arr%20%3D%20%5B%5D%20as%20any%20as%20Pick%3CArr%2C%20keyof%20Arr%3E%3B%20%2F%2F%20error%0D%0Aconst%20p2%3A%20Arr%20%3D%20%5B%5D%20as%20any%20as%20CorrectPick%3CArr%2C%20keyof%20Arr%3E%3B%20%2F%2Fok%0D%0A%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0Atype%20CorrectOmit%3CT%2C%20K%20extends%20keyof%20T%3E%3D%20CorrectPick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0Aconst%20o1%3A%20Arr%20%3D%20%5B%5D%20as%20any%20as%20Omit%3CArr%2C%20never%3E%3B%20%2F%2F%20error%0D%0Aconst%20o2%3A%20Arr%20%3D%20%5B%5D%20as%20any%20as%20CorrectOmit%3CArr%2C%20never%3E%3B%20%2F%2Fok)

**Comment by sirian** [comment]
But this would fail when mixing number/string keys
![image](https://user-images.githubusercontent.com/897643/58886380-767fc680-86ec-11e9-800f-7517b0090d40.png)

but this example could be handled with modified version:

```ts
type CorrectPick<T, K extends keyof T> = {[P in keyof T]: Record<P, any> extends Record<K, any>  ? T[P] : never};

const a1: Pick<[1], 0> = [1];
const a2: CorrectPick<[1], 0> = [1];

const a3: Pick<[1], "0"> = [1];
const a4: CorrectPick<[1], "0"> = [1];
```

**Comment by jcalz** [comment]
I wouldn't call what you're doing `Pick` anymore. If you try to assign a value to a type with required `never`-valued properties, you're gonna have a bad time:

```ts
interface A { a: string, b: number };
const a: Pick<A, "a"> = { a: "hey" }; // okay
const b: CorrectPick<A, "a"> = { a: "hey" }; // error?
```

There might be some merit in your `CorrectPick` type, but it would absolutely break all kinds of everything if we were to replace `Pick` with it. 

---

 But what are you trying to do here?  You mention symbols, but I don't think there's a problem with mapping symbols.  The problem I think you're having here is that [mapping arrays/tuples to arrays/tuples](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#mapped-types-on-tuples-and-arrays) is brittle when you map over a subset of the keys.  I don't know if that's fixable, though.

**Comment by fatcerberus** [comment]
+2 for “you’re gonna have a bad time” and “break all kinds of everything”.

**Comment by RyanCavanaugh** [comment]
We can't touch these definitions with a feather without breaking tons of code. `Pick` is `Pick`; use your own if you want behavior other than what the existing definition provides.
