### ISSUE TITLE
Add more types for promises

### ISSUE THREAD

**Issue by hejkerooo** [microsoft/TypeScript#31753]
## Search Terms
promise, array, type

## Suggestion

I really would like to see some built-in wrappers for promises, to increase code readability, for example
## Use Cases

Instead of having 
```TS
foo(): Promise<bar[]>
```

We will have
```TS
foo(): PromiseArray<T>
```

## Examples

```TS
type PromiseArray<T> = Promise<T[]>;
type ArrayOfPromises<T> = Array<Promise<T>>;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by goodmind** [comment]
Please close this, this is useless

**Comment by dragomirtitian** [comment]
I would avoid adding to may types in the default lib, especially types which are easy to write using existing syntax.

**Comment by fatcerberus** [comment]
Yeah, no.  The proposed type aliases have more characters than the types they replace!
