### ISSUE TITLE
[Feature request] keyword `export default as exports` for auto emit exports in .js

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#31750]
## Suggestion

keyword `export default as exports` for auto emit exports in .js when 

```json
  "compilerOptions": {
    "module": "esnext"
  }
```

## Use Cases

> at `module` not `esnext`

we can use this for auto make default = exports

```ts
export default exports as typeof import('./index');
```

> but when `module` is `esnext`

if we wanna do same thing
we need add all exports into default
```ts
export default {
  a,
  b,
  c,
  ....more
}
```

## Examples

if we have `export default as exports`

```ts
export const a = 1;
export const b = 1;
export const c = 1;

export default as exports
```

then auto emit this into .js

when `export default as exports`

```js
export const a = 1;
export const b = 1;
export const c = 1;

export default {
  a,
  b,
  c,
  ....more
}
```

> when other

```js
exports.a = 1;
exports.b = 1;
exports.c = 1;

exports.default = exports
```

and `declaration` still looks like this
only `.js` code is not same

```ts
export declare const a = 1;
export declare const b = 1;
export declare const c = 1;
declare const _default: typeof import(".");
export default _default;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
Considering we already have
```ts
import * as stuff from 'module';
stuff.a;
stuff.b;
stuff.c;
```

This doesn’t seem that valuable to me.  That goes double since it’s non-JS syntax producing JS output (see the Design Goals).

**Comment by bluelovers** [comment]
this can help we can allow use 

```ts
import * as stuff from 'module';
import stuff from 'module';
```

at same time, for user habit

**Comment by RyanCavanaugh** [comment]
Please no let's not make modules more confusing.
