### ISSUE TITLE
Generic conditional type T extends never ? 'yes' : 'no' resolves to never when T is never.

### ISSUE THREAD

**Issue by rickwebiii** [microsoft/TypeScript#31751]
**TypeScript Version:**  3.6.0-dev.20190603

**Search Terms:**
never, extends, generic, conditional type
**Code**
```
type MakesSense = never extends never ? 'yes' : 'no' // Resolves to 'yes'

type ExtendsNever<T> = T extends never ? 'yes' : 'no'

type MakesSenseToo = ExtendsNever<{}> // Resolves to 'no'
type Huh = ExtendsNever<never> // Expect to resolve to 'yes', actually resolves to never 
```

**Expected behavior:**
Huh should resolve to 'yes', as MakesSense does.

**Actual behavior:**
Huh resolves to never.

For another variant, you can change ExtendsNever to
```
type ExtendsNever<T extends never> = T extends never ? 'yes' : 'no'
```

and ExtendsNever<never> still resolves to never.

**Playground Link:** 
[Here](https://www.typescriptlang.org/play/index.html#src=type%20MakesSense%20%3D%20never%20extends%20never%20%3F%20'yes'%20%3A%20'no'%20%2F%2F%20Resolves%20to%20'yes'%0D%0A%0D%0Atype%20ExtendsNever%3CT%3E%20%3D%20T%20extends%20never%20%3F%20'yes'%20%3A%20'no'%0D%0A%0D%0Atype%20MakesSenseToo%20%3D%20ExtendsNever%3C%7B%7D%3E%20%2F%2F%20Resolves%20to%20'no'%0D%0Atype%20Huh%20%3D%20ExtendsNever%3Cnever%3E%20%2F%2F%20Should%20resolve%20to%20'yes'%2C%20actually%20resolves%20to%20never%20)

**Related Issues:** 
None

**Comment by dragomirtitian** [comment]
This is the expected behavior, `ExtendsNever` is a distributive conditional type. Conditional types distribute over unions. Basically if `T` is a union `ExtendsNever` is applied to each member of the union and the result is the union of all applications (`ExtendsNever<'a' | 'b'> == ExtendsNever<'a' > | ExtendsNever<'b'>`). `never` is the empty union (ie a union with no members). This is evident by its behavior in a union ` 'a' | never == 'a'`. So when distributing over `never`, `ExtendsNever` is never applied, since there are no members in this union and thus the result is never.

If you disable distribution for `ExtendsNever`, you get the behavior you expect:

```ts
type MakesSense = never extends never ? 'yes' : 'no' // Resolves to 'yes'

type ExtendsNever<T> = [T] extends [never] ? 'yes' : 'no'

type MakesSenseToo = ExtendsNever<{}> // Resolves to 'no'
type Huh = ExtendsNever<never> // is yes 
```

**Comment by rickwebiii** [comment]
Thanks for the clarification. I should really get around to reading my Homotopy Type Theory book.

**Comment by fatcerberus** [comment]
Why is `never` treated as an empty union but `unknown` isn’t treated as a “union of everything”?  For symmetry I would expect `T extends any ? ...` where `T = unknown` to take both branches of the conditional type, the same way `T = never` takes neither.

I understand that `any` works this way but `any` isn’t really a “union of all types” in the usual sense - it also behaves as an “intersection of all types” when placed in a contravariant position so it’s kind of its own thing entirely and I expect it to act weird. :wink:

**Comment by jack-williams** [comment]
@fatcerberus; Discussed in #27418

**Comment by Alexsey** [comment]
@dragomirtitian thank you for the explanation - it really makes sense and explains why we are seeing `never`. But it doesn't answer the question of why the types of `MakesSense` and `Huh` are different - if your explanation is true for TypeScript then both should be `never`. Even more, it doesn't explain why `TrueOrFalse1` works even without distributive conditional type:
```ts
type TrueOrFalse1 = Extract<T, any> extends never ? true : false
type IAmTrue = TrueOrFalse1<never> // true
```
and why it makes difference between `TrueOrFalse2` and `TrueOrFalse3`
```ts
type Self<S> = S
type MagicSelf<S extends string> = ${S} extends 'never' ? never : S

type TrueOrFalse2 = Self<T, any> extends never ? true : false
type TrueOrFalse3 = MagicSelf<T, any> extends never ? true : false

type IAmNever = TrueOrFalse2<never> // true
type IAmTrueThough = TrueOrFalse<never> // never
```

It really looks like the result depends on now `never` has been calculated: if it comes from above (parameters) - the result would be `never`. If it is declared within or calculated by another generic - truthy branch would be used

**Comment by Alexsey** [comment]
@ZhanghaoH you can think of the **type challenge** problem not as "isUnion" but as "isDistributiveUnion" or "isUnionOfMoreThenOneElement". `1` is also a union - a union of 1 element. And `neven` is a union - an empty union, or a union of 0 elements

Unions of 0 elements, 1 element, and 1+ elements behave differently in TS, and the problem is about detecting the third, non-singular case

**Comment by ZhanghaoH** [comment]
> 

I see...thanks for your reply !

**Comment by huih99** [comment]
> This is the expected behavior, `ExtendsNever` is a distributive conditional type. Conditional types distribute over unions. Basically if `T` is a union `ExtendsNever` is applied to each member of the union and the result is the union of all applications (`ExtendsNever<'a' | 'b'> == ExtendsNever<'a' > | ExtendsNever<'b'>`). `never` is the empty union (ie a union with no members). This is hinted at by its behavior in a union ` 'a' | never == 'a'`. So when distributing over `never`, `ExtendsNever` is never applied, since there are no members in this union and thus the result is never.
> 
> If you disable distribution for `ExtendsNever`, you get the behavior you expect:
> 
> ```ts
> type MakesSense = never extends never ? 'yes' : 'no' // Resolves to 'yes'
> 
> type ExtendsNever<T> = [T] extends [never] ? 'yes' : 'no'
> 
> type MakesSenseToo = ExtendsNever<{}> // Resolves to 'no'
> type Huh = ExtendsNever<never> // is yes 
> ```

emmm, in this case: `type A = never extends never ? true : false`, the A is `true`, why not `never`
