### ISSUE TITLE
High memory consumption with typesafe-actions

### ISSUE THREAD

**Issue by zdila** [microsoft/TypeScript#31756]
**TypeScript Version:**  3.5.1 (also with `next`)

**Search Terms:** typescript tsc out of memory high memory usage

**Code**

Please extract code from https://drive.google.com/open?id=1nO3g0yoedOG6syTLn2QGeCh4KXopKtoe. It is a simple code but contains many files not suitable to inline here. Project uses only single dependency: `typesafe-actions`. Could be related to https://github.com/piotrwitek/typesafe-actions/issues/158.

1. `npm i`
2. `node --max-old-space-size=8192 ./node_modules/typescript/lib/tsc.js --diagnostics`

**Expected behavior:**

Compilation should complete in couple of seconds.

**Actual behavior:**

Compilation fails with out of memory after couple of minutes. Tried with node 10 and node 12.

**Comment by oozusta** [comment]
We have the same problem. Reopening modules seems to be the big issue here.

**Comment by poseidonCore** [comment]
I have had the same issue too. Code that compiled under 3.4 does not under 3.5 due to memory issues only.

Luckily, substituting did work for me, although it did not help you. 

I had to substitute the node.exe version from the 32-bit version to the 64-bit version in "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\NodeJs".

**Comment by semenovDL** [comment]
Related issue in [typesafe-actions](https://github.com/piotrwitek/typesafe-actions/issues/164)

**Comment by RyanCavanaugh** [comment]
The pastefile link doesn't work anymore.

**Comment by zdila** [comment]
I've updated the link.

**Comment by liaoyinglong** [comment]
have any progress? 

`typescript 3.5.3` have the same problem

**Comment by sven-strothoff** [comment]
Actually the author of typesafe-actions has fixed something on his end. At least for me this solved the memory issues:
https://github.com/piotrwitek/typesafe-actions/issues/164

Have you tried a recent version of typesafe-actions?

**Comment by liaoyinglong** [comment]
@sven-strothoff 

in my project  `typesafe-action 4.4.2 ` still have problem.

But I tried `5.0.0-3`, it solve the memory problem for me
