### ISSUE TITLE
Type guard fails for a part of an object

### ISSUE THREAD

**Issue by tomfun** [microsoft/TypeScript#31755]
**TypeScript Version:**  3.4.5

**Search Terms:** type guard object destructuring, type guard object key

**Code**
```ts
export type GROUP_TYPE = 'group_1' | 'group_2';

export function isGroup(g: any): g is GROUP_TYPE {
    const allowedGroups: GROUP_TYPE[] = ['group_1', 'group_2'];
    return allowedGroups.indexOf(g) !== -1;
}

function getPermissions(query: { group: GROUP_TYPE }) {/* do something */ }

function goodFunction(query: { group: string }) {
    if (!isGroup(query.group))
        return;

    const { group } = query;

    return getPermissions({ ...query, group });
}

function sameFunction(query: { group: string }) {
    if (!isGroup(query.group))
        return;

    return getPermissions(query); // Error here
    //   _________________^^^^^
/*
Argument of type '{ group: string; }' is not assignable to parameter of type '{ group: GROUP_TYPE; }'.
 ...
*/
}
```

**Expected behavior:**
Both functions (goodFunction, sameFunction) should be valid typescript code

**Actual behavior:**
We see TS error
```
Argument of type '{ group: string; }' is not assignable to parameter of type '{ group: GROUP_TYPE; }'.
  Types of property 'group' are incompatible.
    Type 'string' is not assignable to type 'GROUP_TYPE'.
```
it thinks that `query.group` is steel a `string` when passing as arguments, but knows it is a `GROUP_TYPE` when gets it from object.

**Playground Link:** 
[link to playground](https://www.typescriptlang.org/play/#src=export%20type%20GROUP_TYPE%20%3D%20'group_1'%20%7C%20'group_2'%3B%0D%0A%0D%0Aexport%20function%20isGroup(g%3A%20any)%3A%20g%20is%20GROUP_TYPE%20%7B%0D%0A%20%20%20%20const%20allowedGroups%3A%20GROUP_TYPE%5B%5D%20%3D%20%5B'group_1'%2C%20'group_2'%5D%3B%0D%0A%20%20%20%20return%20allowedGroups.indexOf(g)%20!%3D%3D%20-1%3B%0D%0A%7D%0D%0A%0D%0Afunction%20getPermissions(query%3A%20%7B%20group%3A%20GROUP_TYPE%20%7D)%20%7B%2F*%20do%20something%20*%2F%20%7D%0D%0A%0D%0Afunction%20goodFunction(query%3A%20%7B%20group%3A%20string%20%7D)%20%7B%0D%0A%20%20%20%20if%20(!isGroup(query.group))%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%0D%0A%20%20%20%20const%20%7B%20group%20%7D%20%3D%20query%3B%0D%0A%0D%0A%20%20%20%20return%20getPermissions(%7B%20...query%2C%20group%20%7D)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20sameFunction(query%3A%20%7B%20group%3A%20string%20%7D)%20%7B%0D%0A%20%20%20%20if%20(!isGroup(query.group))%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%0D%0A%20%20%20%20return%20getPermissions(query)%3B%0D%0A%7D)

**Comment by jack-williams** [comment]
Type guards do not propagate type narrowings to parent objects. The narrowing is only applied upon access of the narrowed property which is why the destructing function works, but the reference function does not. Narrowing the parent would involve synthesizing new types which would be expensive. More detail in this [comment](https://github.com/microsoft/TypeScript/issues/30506#issuecomment-474802840).
