### ISSUE TITLE
"rootDir" and "include" properties in tsconfig.json conflict with eachother

### ISSUE THREAD

**Issue by KerimG** [microsoft/TypeScript#31757]
**TypeScript Version:**  3.5.1

**Search Terms:** rootDir, include, exclude, tsconfig.json

**Code**
```json
{
  "compilerOptions": {
    "target": "ES2018",                    
    "module": "commonjs",                  
    "declaration": true,                   
    "sourceMap": true,                     
    "outDir": "./build",                   
    "rootDir": "./src",                    

    "strict": true,                        

    "noUnusedLocals": true,                
    
    "esModuleInterop": true,               

    "experimentalDecorators": true,        
    "emitDecoratorMetadata": true,         
  },
  "include": [
    "vendor"
  ]
}
```

**Expected behavior:** Compiler compiles contents of src folder and vendor folder into build folder.

**Actual behavior:** Compiler ONLY compiles vendor folder into build folder while also complaining with the following error:
```
File 'c:/Users/KG/code/project/vendor/vend.ts' is not under 'rootDir' 'c:/Users/KG/code/obi/src'. 'rootDir' is expected to contain all source files.
```

I tried a few other things and got really weird behavior. If all source files need to be in `rootDir` then why does the compiler compile all my project's source files (including unit tests) that are outside of `rootDir`? 

I also noticed that if I use `include`, the compiler only ever compiles whatever is in `include` and not in addition to `rootDir`. Not only is this not documented anywhere, the tsconfig.json docs are outright wrong:  https://www.typescriptlang.org/docs/handbook/tsconfig-json.html 

With the current behavior, the example tsconfig.json is nonsensical, since using `include` already excludes everything outside of it, what's the `exclude` then good for?

**Comment by dingdongping** [comment]
i also don't complire 'rootDir'
