### ISSUE TITLE
control flow does not remove optional from Partial type

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#31767]
**TypeScript Version:**  3.4.5

**Search Terms:**
control flow, optional, partial

**Code**

```ts
type ChannelHandler = {
  stderr: (chunk: string) => void,
  stdout: (chunk: string) => void
}

function foo(h: Partial<ChannelHandler>) {
    if (h.stderr) {
        h.stderr // stderr?: (chuck: string) => void
        // should be: stderr: (chuck: string) => void
    }
}
```

**Playground Link:** 
http://www.typescriptlang.org/play/#src=type%20ChannelHandler%20%3D%20%7B%0A%20%20stderr%3A%20(chunk%3A%20string)%20%3D%3E%20void%2C%0A%20%20stdout%3A%20(chunk%3A%20string)%20%3D%3E%20void%0A%7D%0A%0Afunction%20foo(h%3A%20Partial%3CChannelHandler%3E)%20%7B%0A%20%20%20%20if%20(h.stderr)%20%7B%0A%20%20%20%20%20%20%20%20h.stderr%20%2F%2F%20stderr%3F%3A%20(chuck%3A%20string)%20%3D%3E%20void%0A%20%20%20%20%20%20%20%20%2F%2F%20should%20be%3A%20stderr%3A%20(chuck%3A%20string)%20%3D%3E%20void%0A%20%20%20%20%7D%0A%7D

**Comment by fatcerberus** [comment]
The IntelliSense will still show the question mark in this case but in my experience, the `undefined` *is* narrowed away, which is all that matters in practice.  Try assigning `h.stderr` to a non-`Partial`ized version inside that `if` and you should see it works without issue.

**Comment by unional** [comment]
It doesn't work correctly when it is consumed:

```ts
stderr.on('data', h.stderr) // TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type
undefined

**Comment by fatcerberus** [comment]
You’re getting a TypeError *at runtime*?  I’m not sure how adding a `!` fixes that... I’m baffled now.

**Comment by unional** [comment]
I'm not sure what exactly happened either. But `!` does fix it.
I'm running that in `jest` with `ts-jest`. So it could be `tsc` complaining, even-though it is not the typical TS XXXXX errror.

**Comment by fatcerberus** [comment]
I couldn't reproduce the type error in the playground with this at least (not even with `strictNullChecks`):

```ts
type ChannelHandler = {
  stderr: (chunk: string) => void,
  stdout: (chunk: string) => void
}

declare function bar(stderr: (chunk: string) => void): void;

function foo(h: Partial<ChannelHandler>) {
    if (h.stderr) {
        bar(h.stderr);  // <-- no error
    }
}
```

So yeah, I give up.  We'll wait and see if someone else has a better idea what could be wrong.

**Comment by RyanCavanaugh** [comment]
I don't know what your problem is, but it certainly isn't TypeScript causing a runtime error in a different component.
