### ISSUE TITLE
Conditional type coerces Enum to intersection of constituents

### ISSUE THREAD

**Issue by chcaru** [microsoft/TypeScript#31768]
**TypeScript Version:** 3.6.0-dev.20190604 (`typescript@next` at the time of writing this)

**Search Terms:**
conditional type enum intersection coercion error TS2345

**Code**
```ts
export enum E {
    A,
    B,
}

export interface CreatorWithInput<T> {
    (args: T): void;
}

export interface Creator {
    (): void
}

// Version A
// This works:
// export type PickCreator<T = undefined> = CreatorWithInput<T>;

// Version B
// But this does not (when T !extends undefined)
export type PickCreator<T> = T extends undefined
    ? Creator
    : CreatorWithInput<T>;

function A<T = undefined>() {
    const c = (t?: T) => { };
    return c as PickCreator<T>;
}

// Type of 'a'
// Version A: CreatorWithInput<E>
// Version B: CreatorWithInput<E.A> | CreatorWithInput<E.B>
const a = A<E>();

const b = A();

function Q(e: E) {

    a(e); // <--- Error when Version B is used (unexpected / incorrect). 

    // Constraints for the problem, unrelated to the error
    // a(); // Both should error (desired)
    b(); // Version A will error (undesired). Version B will not error (desired)
}
```

**Expected behavior:**
Version B should not error on `a(e)`.
- Reading the code backwards from `a(e);`, it seems very logical that this should be the correct behavior.
- To make this opinion more concrete, I've included `Version A`, which basically shows the same "path" that Version B takes in the conditional type, except that this works as expected and does not produce the error.

**Actual behavior:**
Version B errors on `a(e)` with error:
`error TS2345: Argument of type 'E' is not assignable to parameter of type 'E.A & E.B'.`

[**Playground Link**](https://www.typescriptlang.org/play/#src=export%20enum%20E%20%7B%0D%0A%20%20%20%20A%2C%0D%0A%20%20%20%20B%2C%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20CreatorWithInput%3CT%3E%20%7B%0D%0A%20%20%20%20(args%3A%20T)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20Creator%20%7B%0D%0A%20%20%20%20()%3A%20void%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Version%20A%0D%0A%2F%2F%20This%20works%3A%0D%0A%2F%2F%20export%20type%20PickCreator%3CT%20%3D%20undefined%3E%20%3D%20CreatorWithInput%3CT%3E%3B%0D%0A%0D%0A%2F%2F%20Version%20B%0D%0A%2F%2F%20But%20this%20does%20not%20(when%20T%20!extends%20undefined)%0D%0Aexport%20type%20PickCreator%3CT%3E%20%3D%20T%20extends%20undefined%0D%0A%20%20%20%20%3F%20Creator%0D%0A%20%20%20%20%3A%20CreatorWithInput%3CT%3E%3B%0D%0A%0D%0Afunction%20A%3CT%20%3D%20undefined%3E()%20%7B%0D%0A%20%20%20%20const%20c%20%3D%20(t%3F%3A%20T)%20%3D%3E%20%7B%20%7D%3B%0D%0A%20%20%20%20return%20c%20as%20PickCreator%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Type%20of%20'a'%0D%0A%2F%2F%20Version%20A%3A%20CreatorWithInput%3CE%3E%0D%0A%2F%2F%20Version%20B%3A%20CreatorWithInput%3CE.A%3E%20%7C%20CreatorWithInput%3CE.B%3E%0D%0Aconst%20a%20%3D%20A%3CE%3E()%3B%0D%0A%0D%0Aconst%20b%20%3D%20A()%3B%0D%0A%0D%0Afunction%20Q(e%3A%20E)%20%7B%0D%0A%20%20%20%20a(e)%3B%20%2F%2F%20Error%20when%20Version%20B%20is%20used%20(unexpected%20%2F%20incorrect).%20%0D%0A%20%20%20%20%2F%2F%20a()%3B%20%2F%2F%20Both%20should%20error%20(desirably)%0D%0A%20%20%20%20b()%3B%20%2F%2F%20Version%20A%20will%20error%20(undesirably).%20Version%20B%20will%20not%20error%20(desirably)%0D%0A%7D)

**Related Issues:**
Not able to find any related to this specific issue.

**Comment by fatcerberus** [comment]
`E` is exactly the type `E.A | E.B`, i.e. the union of its constituents.  This is similar to how `boolean` is exactly the union `true | false`.

Because `E` is a union, the conditional type:
```ts
type PickCreator<T> = T extends undefined
    ? Creator
    : CreatorWithInput<T>;
```

...when instantiated with `E`, distributes to:

```ts
type PickCreatorE = CreatorWithInput<E.A> | CreatorWithInput<E.B>;

/* and therefore... */
type PickCreatorE = ((args: E.A) => void) | ((args: E.B) => void);  // ...essentially
```

If the only thing we know about a function is that it's of type `PickCreatorE`, we can *only* safely call it with a hypothetical argument of type `E.A & E.B`.  So that's where the intersection is coming from.  This is by design and is the exact mechanism that makes the ever-popular `UnionToIntersection` work:
```ts
// roughly:
// convert a union to a union of functions, then ask what type of argument we need in order
// to call the function-union (fun with contravariance!)
type UnionToIntersection<U> =
    (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never;
```

**Comment by fatcerberus** [comment]
To prevent the distributive behavior:
```ts
type PickCreator<T> = [T] extends [undefined]
    ? Creator
    : CreatorWithInput<T>;
```

**Comment by chcaru** [comment]
Thanks!

For anyone else who finds this, here's some documentation on this:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html
Search for "Distributive conditional types"

The reason @fatcerberus's solution works is because TypeScript will only distribute the type parameter if the checked type is "naked". So by making it not "naked", as shown above, this will prevent the conditional type from being a distributive conditional type. The relevant part of the docs: 
> Conditional types in which the checked type is a naked type parameter are called distributive conditional types. Distributive conditional types are automatically distributed over union types during instantiation.

**Comment by fatcerberus** [comment]
> because TypeScript will only distribute the type parameter if the checked type is "naked"

This the way it’s documented but the reason it works this way is actually a bit more subtle (and IMO kind of elegant): wrapping `A | B` in a tuple types converts a union of types into a single, indivisible type: “array of A or B” is different from “array of A or array of B” for the same reason as the herbivore/carnivore thing above (yay contravariance!)

So it’s not that TS *won’t* distribute over an “embellished” type parameter but simply that it *can’t*—as there’s only one type. :smiley:
