### ISSUE TITLE
Go to definition enhancements

### ISSUE THREAD

**Issue by verydanny** [microsoft/TypeScript#31765]
- VSCode Version: 1.35-insdier
- OS Version: macOS 10.14.5

**Issue**

I was writing an extension to attempt and fix GoTo clicking for my aliased paths project (for faster navigation). Our project is about is about 30% Typescript and 70% Javascript. I know I can enable `{ allowJs: true, checkJs: true, }` and that speeds up GoTo for a WHILE, but then that slows to a crawl eventually.

- Our project uses moduleRoot aliasing in Webpack, as well as the `baseUrl` option in Typescript:
```js
...
resolve: {
  modules: [ 'src', 'node_modules' ]
}
```

I was attempting to write an extension that jumps to these aliased paths faster.

- When you open a Typescript file, give it time to configure TSServer, GoTo seems to work fine, although sometimes it slows to a crawl after opening a fair amount of files, and then I have to reload the TSServer. I'm guessing this is also tied with my next point. I'd say TS -> TS go to definition works "okay" until the server queue gets clogged up.

- After some investigation, when opening a JS file, it attempts to `configure` the project using `compilerOptionsForInferredProjects`, load the `navtree`, `getSupportedCodeFixes`, `getOutliningSpans`, etc, and that can take upward of 6-7 seconds(!!) for a single JS file in our large project.

This breaks my aliased imports extension because I'm guessing it reaches the `await` in the built-in Typescript extension before my Definition Provider has a chance to return a `Location`. I'm not really sure which subscribers are given priority, or much about how they work. My subscriber is certainly quicker than the built-in one.

Regardless, the TS extension first attempts to get `definitionAndBoundSpan`, once that fails, it goes to my Definition provider. This results in all imports' go to definition taking an extremely long time--relative and absolute imports taking 3-4s to open as well, not just aliased. The first few might open quick, then the server queue gets clogged up with more files being open, which just keeps making GoTo slower and slower (even for TS files). Enabling `{ allowJs: true, checkJs: true, }` only delays the inevitable.

The issues seems to be the server queue. Some things take longer than others, `configure` seems to take a while, also `navtree` (maybe? I haven't investigated it too much), and this causes blocking to processes that depend on the server, such as the Definition subscriber:

```js
// extensions/typescript-language-features/src/features/definitions.ts

const response = await this.client.execute('definitionAndBoundSpan', args, token)
```

**Solution ideas?**

- I would love to not have to write the alias extension in the first place. It'd be nice to just use 
`{ allowJs: true }` for a smooth Go To Definition experience, since TSServer knows the project structure, and the `baseUrl`. `checkJs` results in too many distracting errors although it seems to work the best.

- Would this be possible with giving a higher priority to things like `definitionAndBoundSpan`? 
- Maybe not sending so many heavy requests to the TSServer when it's not a TS file and there are no `{ allowJs: true, checkJs: true, }` options enabled?
- If TSServer can't be fixed, could the `vscode.languages.registerDefinitionProvider` be written to with an optional parameter for priority?

I've noticed many similar issues pop up here and I'm guessing they have more or less to do with the same problems with the TS Extension <--> TSServer.

It would save a lot of developing time to be able to go to definition quicker.

**Comment by mjbvz** [comment]
Moving to TS since I think this comes down to two core issues:

* Slow performance overall.

    @verydanny Can you share more info about your project structure and layout? The output of running `code --status` may be a helpful starting point

* Not being able to configure the jsconfig to match webpack?
 
    I don't really understand what is not working here? Have you tried configuring `paths` in the `compilerOptions` as a starting point?

**Comment by verydanny** [comment]
> Can you share more info about your project structure and layout?

```bash
|    Folder (ag.js): 4833 files
|      File types: js(2964) ts(545) scss(391) tsx(282) snap(175) svg(169)
|                  css(124) png(54) html(27) jpg(18)
```

It's mixed with about 1/3 Typescript, and the rest is JS. We're in the process of converting the whole project to Typescript. Here is our Typescript configuration:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "jsx": "react",
    "allowJs": false,
    "checkJs": false,
    "noEmit": true,
    "strict": true,
    "baseUrl": "./src",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "lib": [
      "esnext.asynciterable",
      "es2017",
      "dom"
    ]
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*"
  ],
  "include": [
    "./src/**/*"
  ]
}
```

An average `js` or `ts` file looks like this:

```js
import get from 'lodash/fp/get'
import getOr from 'lodash/fp/getOr'
import has from 'lodash/fp/has'
import pipe from 'lodash/fp/pipe'
import { createSelector } from 'reselect'

import { getEtc } from 'apps/selectors/etc'
import getOrN from 'lib/getOrN'
import { photoUrl } from 'lib/url/photoUrl'

// ETC
``` 

We use `webpack` and `@babel/preset-typescript` to compile our project. We use our `${workspaceRoot}/src` dir as a module root through webpack's resolve option:

```js
// webpack.shared.config.js

...
resolve: {
  modules: [ 'src', 'node_modules' ]
}
```

Which turns our `src` subdirectories into "modules" we can import from. In other words, it's basically the `tsconfig` paths option.

```bash
├── src
│   ├── apps
│   ├── components
│   ├── config
│   ├── gql
│   ├── lib
│   ├── types
│   └── ui
```

I'm not arguing this is good. I strongly opposed webpack moduleRoot aliasing, or any aliasing of that kind, even tsconfig `path`, but that's just how the project it set up.

Regardless, when I open a Typescript file, Goto Definition works very well (for a while) because of the tsconfig `baseUrl`. After about an hour of coding, it starts slowing down, until it takes 2-3s to open a file using Goto definition.

Because I didn't have this as my tsconfig:

```js
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "jsx": "react",
    "allowJs": true, // Allowing Javascript
    "checkJs": false,
    "noEmit": true,
    "strict": true,
    "baseUrl": "./src",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "lib": [
      "esnext.asynciterable",
      "es2017",
      "dom"
    ]
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*"
  ],
  "include": [
    "./src/**/*"
  ]
}
```

JS alias imports (`import blah from 'apps/blah/blah'`) don't work because I disable allowing JS. jsconfig.json` has no impact (because I assume we have a tsconfig file already).

If I have `allowJs: true`, after initial project initialization, and TSServer bootup, Goto is snappy, **all** the imports resolve perfectly, no issue...for about 30 minutes--then it craps out and it starts taking longer and longer to Goto.

If I have `allowJs: false` and open a file with relative imports (`import blah from './rightHere'`), not even aliased, and IMMEDIATELY try to Goto, then it takes like 6s+ to go to that file. Then inside the relative file if I try to go to another relative file, it takes 5+ seconds again.

I initially thought the issue was the definition provider for Typescript and if I wrote my own, then I could solve that issue. So I wrote a simple extension that converts all the aliased path imports to their proper absolute URI (`vscode.Location`). 

My extension returns the correct `vscode.Location` in about 0.05ms, but it hangs on opening the document in a new tab. So I went to investigate.

I downloaded `vscode` from `master` to try and understand how the built-in Typescript extension works, and I can see that the server queue gets bogged down when I hop around files with Goto Definition.

When I open a JS file with `allowJs: false` and try to Goto, I notice the TSServer queue pushes the 

```js
// this is vscode's built-in Typescript extension Definition Provider
const response = await this.client.execute('definitionAndBoundSpan', args, token
```

to the bottom of the queue while it's running other server tasks in the background, such as `configure` `compilerOptionsForInferredProjects`, `navtree`, `getSupportedCodeFixes`, `getOutliningSpans`, etc.

Then it finally processes `definitionAndBoundSpan` for the relative import, and proceeds to open the file.

I assume the built-in extension is subscribed to vscode much earlier than mine, so it reaches that await much quicker, but it bogs down the entire Goto functionality until the server queue is done.

Regardless, all the Goto slowdown issues, JS -> JS, TS -> JS, JS -> TS -> TS, aliased or not aliased, come from the built-in Typescript extension awaiting the result of `definitionAndBoundSpan`, which waits other things in the server queue.

**Comment by RyanCavanaugh** [comment]
We'd need a concrete repro to investigate further. It sounds like you have a lot of files in your program and there are ways to reduce this.

**Comment by verydanny** [comment]
I'll attempt to reproduce this in a repo. Give me a few days, I have to remove all confidential stuff

**Comment by karlhorky** [comment]
@verydanny did you ever come up with a solution here? Or is this no longer an issue in the newer versions of VS Code / TypeScript?
