### ISSUE TITLE
Visual Studio 2013 Compiler cleans .js file

### ISSUE THREAD

**Issue by Rian0702** [Microsoft/TypeScript#3176]
Hello, 
i downloaded the ToDoMvc Example. 
When i build with visual studio the "application.js" get compiled wrong... if i compile with "tsc --out" everythings fine.

**Comment by mhegazy** [comment]
the html file in the sample references a ["js\todo.js"](https://github.com/Microsoft/TypeScriptSamples/blob/master/todomvc/index.html#L56), so i am not sure i understand the issue. it is working fine for me. can you share your project file you are using to build in VS.

**Comment by mhegazy** [comment]
closing this issue for now, please reopen if there further details needed.
