### ISSUE TITLE
TS2349: Cannot invoke an expression

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#31764]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

> if remove ` as any as 'map' ` will get error

`map` and `mapSeries` is almost same, only `options?: Bluebird.ConcurrencyOption`

but it is `?:`

```ts
import Bluebird from 'bluebird'

let waitTime: boolean;
let urls: string[];

Bluebird
	.resolve(urls)
	[waitTime ? 'mapSeries' as any as 'map' : 'map'](async (url) =>
{
	return Bluebird.resolve(url)
})

/*
map<U, Q>(this: Bluebird<R & Iterable<Q>>, mapper: IterateFunction<Q, U>, options?: Bluebird.ConcurrencyOption): Bluebird<U[]>;

mapSeries<U, Q>(this: Bluebird<R & Iterable<Q>>, iterator: IterateFunction<Q, U>): Bluebird<U[]>;
 */
```

**Expected behavior:**

> no error

**Actual behavior:**

> Error:(10, 1) TS2349: Cannot invoke an expression whose type lacks a call signature. Type '(<U, Q>(this: Bluebird<string[] & Iterable<Q>>, iterator: IterateFunction<Q, U>) => Bluebird<U[]>) | (<U, Q>(this: Bluebird<string[] & Iterable<...>>, mapper: IterateFunction<Q, U>, options?: ConcurrencyOption) => Bluebird<...>)' has no compatible call signatures.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@bluelovers this isn't your first issue here -- you know that we ask for isolated repros. Please apply more effort when logging things; it's very time-consuming on our end.
