### ISSUE TITLE
Dead links in 'Release TypeScript 3.5.1'

### ISSUE THREAD

**Issue by mihailik** [microsoft/TypeScript#31776]
Release page: https://github.com/microsoft/TypeScript/releases/tag/v3.5.1

All these links are going to a non-existent page:

![image](https://user-images.githubusercontent.com/4041967/58966100-95905e00-87a9-11e9-80e8-1fcabaf480b1.png)

![image](https://user-images.githubusercontent.com/4041967/58966152-a8a32e00-87a9-11e9-8a35-9604f0684d9f.png)

**Comment by fatcerberus** [comment]
All the broken links point to:
https://github.com/microsoft/TypeScript/blob/v3.5.1

There are honestly so many things wrong with that release post I don't even know where to start.  Best I can tell @weswigham must have been drunk when he posted it :smile:

**Comment by mihailik** [comment]
Or automation script gone rogue?

Anyway, the list of fixed issues is also wrong, points here:
https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A%22TypeScript+3.3%22+is%3Aclosed+

![image](https://user-images.githubusercontent.com/4041967/58974176-b95ba000-87b9-11e9-966b-693bb91a3efc.png)


Whereas probably should go here:
https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A%22TypeScript+3.5.1%22+is%3Aclosed+

![image](https://user-images.githubusercontent.com/4041967/58974200-cbd5d980-87b9-11e9-9b43-a353fe341209.png)

**Comment by orta** [comment]
I've updated the release notes for 3.5.1 with these recommendations - thanks!
