### ISSUE TITLE
feed '(...args: any[]) => any' feeds to ID function becomes `any => any`

### ISSUE THREAD

**Issue by zheeeng** [microsoft/TypeScript#31772]
**TypeScript Version:**  3.5.1

**Search Terms:** constraints on Function type

**Code**

In most cases, we use `(...args: any[]) => any` as constraints type parameter to Function type.
But this case causes losing concrete type info such as below: 
```ts
const idForAllType = <I>(i: I) => i

const idForFunction = <F extends (...args: any[]) => any>(f: F) => f

const idForFunction2 = <F extends Function>(f: F) => f

// (i: any) => any
const result1 = idForFunction(idForAllType)
// <I>(i: I) => I
const result2 = idForFunction2(idForAllType)
```
After wrapping by `idForFunction`, `idForAllType` becomes `any => any`,
and after wrapping by `idForFunction2`, `idForAllType` is the expected type `I => I`

`(...args: any[]) => any` and `Function` which should us pick for adding constraints?

**Comment by fatcerberus** [comment]
That’s interesting; even though the constraint involves `any`, your return type should still be inferred as `F`, i.e. the original function type.  You *do* lose type safety *inside* the function, but losing it *outside* seems odd.  Maybe the generic is interacting badly with that somehow—not sure.

That said, `(...args: any[]) => any` is basically a free-for-all.  For maximum type safety you should pick a constraint which is analogous to `unknown` (assuming you’re not actually going to call it within the generic context, i.e. inside `idForFunction`).  For functions, `Function` would probably be the closest thing to a top type.

**Comment by fatcerberus** [comment]
It definitely seems to be the type parameter that's throwing it off because:
```ts
const idNumber = (n: number) => n;
const n1 = idForFunction(idNumber);
const n2 = idForFunction2(idNumber);
```

Both `n1` and `n2` are type `(n: number) => number`, as expected.

**Comment by RyanCavanaugh** [comment]
This doesn't seem wrong to me. `idForFunction` implies a specific thing about the signature of `f`, but `idForFunction2` only requires something satisfying the global type `Function` (which has no such signature implications).

**Comment by zheeeng** [comment]
> This doesn't seem wrong to me. `idForFunction` implies a specific thing about the signature of `f`, but `idForFunction2` only requires something satisfying the global type `Function` (which has no such signature implications).

What's the recommended constraint signature for function type when writing high order function?
