### ISSUE TITLE
default parameters breaks type inferring

### ISSUE THREAD

**Issue by zheeeng** [microsoft/TypeScript#31773]
**TypeScript Version:**  3.5.1

**Search Terms:**

**Code**

```ts
type A = {
  foo?: 'a' | 'b'
}

type F<P> = (p: P) => void


function wrap<P extends object>(p: F<P>): F<P> {
  return p
}

             // foo: 'a' | 'b' | undefined
const f0: F<A> = ({ foo }) => {
}

               // foo: 'a' | 'b'
const f1: F<A> = ({ foo = 'a' }) => {
}

                  // foo: 'a' | 'b' | undefined
const f2: F<A> = wrap(({ foo }) => {
})

                // foo: string
const f3: F<A> = wrap(({ foo = 'a' }) => {
})
```

The type of parameter `foo` of `f0`, `f1`, `f2` is expected, but `foo` of f3 is inferred as `string`.

What happened after adding a default value to `foo` of  the wrapped `f3` compares by `f1`'s`foo` which also has a default value and `f2` which wrapped by a generic function.

**Comment by RyanCavanaugh** [comment]
This is generally the correct behavior - widening when passing through an identity function is normal behavior and that's what's happening to the parameter type.

**Comment by zheeeng** [comment]
@RyanCavanaugh What is the correct way to set a default value to a sum type value?

Do we have to do in this way?
```ts
const f3: F<A> = wrap(({ foo: _foo }) => {
    const foo = _foo || 'a'
})
```
