### ISSUE TITLE
Control flow not working with discriminated unions in TypeScript 3.5.1

### ISSUE THREAD

**Issue by fruchtose** [microsoft/TypeScript#31781]
**TypeScript Version:**  3.5.1

**Search Terms:**
is:issue union 3.5 
is:issue discriminated union 3.5 

**Code**

```ts
interface BaseWidget {
    id: string | null;
}

interface WidgetA extends BaseWidget {
    kind: 'a';
    totalModels: number;
    models: [];
}

function AProcessor(props: {
    widget: WidgetA
}) {
    console.log(props.widget.totalModels);
}

interface WidgetB extends BaseWidget {
    kind: 'b';
    shortName: string;
    text: string;
}

function BProcessor(props: {
    widget: WidgetB
}) {
    console.log(props.widget.text);
}

type Widget = WidgetA | WidgetB;

function processWidget<T extends Widget>(widget: T) {
    switch (widget.kind) {
        /*
          Type 'WidgetB' is missing the following properties from type 'WidgetA': totalModels, models
        */
        case 'a': return AProcessor({ widget });
        /*
          Type 'WidgetA' is missing the following properties from type 'WidgetB': shortName, text
        */
        case 'b': return BProcessor({ widget });
    }
}
```

**Expected behavior:**
This kind of control flow worked in previous versions of TypeScript.

**Actual behavior:**
This kind of control flow no longer narrows down TypeScript types

**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=interface%20BaseWidget%20%7B%0D%0A%20%20%20%20id%3A%20string%20%7C%20null%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20WidgetA%20extends%20BaseWidget%20%7B%0D%0A%20%20%20%20kind%3A%20'a'%3B%0D%0A%20%20%20%20totalModels%3A%20number%3B%0D%0A%20%20%20%20models%3A%20%5B%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20AProcessor(props%3A%20%7B%0D%0A%20%20%20%20widget%3A%20WidgetA%0D%0A%7D)%20%7B%0D%0A%20%20%20%20console.log(props.widget.totalModels)%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20WidgetB%20extends%20BaseWidget%20%7B%0D%0A%20%20%20%20kind%3A%20'b'%3B%0D%0A%20%20%20%20shortName%3A%20string%3B%0D%0A%20%20%20%20text%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20BProcessor(props%3A%20%7B%0D%0A%20%20%20%20widget%3A%20WidgetB%0D%0A%7D)%20%7B%0D%0A%20%20%20%20console.log(props.widget.text)%3B%0D%0A%7D%0D%0A%0D%0Atype%20Widget%20%3D%20WidgetA%20%7C%20WidgetB%3B%0D%0A%0D%0Afunction%20processWidget%3CT%20extends%20Widget%3E(widget%3A%20T)%20%7B%0D%0A%20%20%20%20switch%20(widget.kind)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F*%0D%0A%20%20%20%20%20%20%20%20%20%20Type%20'WidgetB'%20is%20missing%20the%20following%20properties%20from%20type%20'WidgetA'%3A%20totalModels%2C%20models%0D%0A%20%20%20%20%20%20%20%20*%2F%0D%0A%20%20%20%20%20%20%20%20case%20'a'%3A%20return%20AProcessor(%7B%20widget%20%7D)%3B%0D%0A%20%20%20%20%20%20%20%20%2F*%0D%0A%20%20%20%20%20%20%20%20%20%20Type%20'WidgetA'%20is%20missing%20the%20following%20properties%20from%20type%20'WidgetB'%3A%20shortName%2C%20text%0D%0A%20%20%20%20%20%20%20%20*%2F%0D%0A%20%20%20%20%20%20%20%20case%20'b'%3A%20return%20BProcessor(%7B%20widget%20%7D)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:**

**Comment by fruchtose** [comment]
Works without the generics. I might be running into a library-related issue.

**Comment by fatcerberus** [comment]
Even more confusing:
![image](https://user-images.githubusercontent.com/4097841/58991385-210fec00-87b6-11e9-952d-c6df41c34f5e.png)

IntelliSense claims it was narrowed, but the compiler weirdly ignores the narrowing for the actual function call.
