### ISSUE TITLE
Local variable called 'name' conflicts with lib.d.ts 'name'

### ISSUE THREAD

**Issue by minkir014** [microsoft/TypeScript#31783]
I have a variable called `name` and it seems to be duplicated with a const in `lib.dom.d.ts` and this affects some functions in vs code like hovering and going to definition.
See this picture that shows the problem of hovering

![er1](https://user-images.githubusercontent.com/42807112/58959598-b8207800-87a5-11e9-8ee1-3ee989861fad.jpeg)

and this shows the problem of going to definition when I press `F12` It goes to this file

![er2](https://user-images.githubusercontent.com/42807112/58959774-0e8db680-87a6-11e9-9109-bf161e0082d0.jpeg)

**Comment by mjbvz** [comment]
If you are not targeting the web, you can disable dom typings by setting `"lib": ["es6"]` in your `jsconfig.json`:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve",
        "lib": ["es6"]
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by lll000111** [comment]
Just for background, this is where it comes from: https://developer.mozilla.org/en-US/docs/Web/API/Window/name &mdash; meaning it's unavoidable and not a TS issue.

**Comment by minkir014** [comment]
@mjbvz That wasn't a `typescript` file. It was a `javascript` file.

**Comment by minkir014** [comment]
@lll000111 This is my code and that what I have. I don't understand how it worked for you. Tell me what's your steps.


![58959598-b8207800-87a5-11e9-8ee1-3ee989861fad](https://user-images.githubusercontent.com/42807112/59031226-5de5ec80-8863-11e9-87e8-0730b351e719.jpeg)

**Comment by lll000111** [comment]
> Tell me what's your steps.

@minkir014 

I use WebStorm &mdash; but the TS language service. If that makes any difference it's not a TS issue anyway.

I added a `var name = "something";` to a random TS file I had open in a TS project and a `console.log(name);` statement. I queried the language server with CTRL-mouseover to see the inferred type(s). I removed `var` and checked again (plus I got a TS error now).

**Comment by minkir014** [comment]
Have you hovered over the name variable in the `console.log(name);` statement and gave you the same result? Plus, I think that it's a vs code problem. So, I opened an issue at vs code but it was transferred here.

**Comment by minkir014** [comment]
@lll000111 Are you here?

**Comment by lll000111** [comment]
@minkir014 

> Have you hovered over the name varia...

Yes.

> Are you here?

I'm not sitting in front of a computer 24x7...

**Comment by minkir014** [comment]
@lll000111 Can you transfer this issue back to vs code issues?

**Comment by lll000111** [comment]
@minkir014 Me???

**Comment by minkir014** [comment]
If you can't. I'll close this issue and start another one with the same name.

**Comment by kitsonk** [comment]
TypeScript provides all the language services to VSCode, so it being here is appropriate.

See #18433 for further information about the issue.

**Comment by minkir014** [comment]
@kitsonk Are you using vs code. If so, try that and tell me what's your solution and if not, this issue repeated many times with vs code.
https://github.com/microsoft/TypeScript/issues/18433
https://github.com/microsoft/TypeScript/issues/31800
Although they are in typescript repository but they are also a problem with vs code.

**Comment by mjbvz** [comment]
I don't know why this was closed. @minkir014 We explained why this is happening and are keeping this open to see if the experience can be improved

**Comment by minkir014** [comment]
but it's strange that it works in webstorm and also the compiler understands that.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior - without any other clues to the contrary, we assume you're editing a script file in a browser context.

**Comment by minkir014** [comment]
My project was targeting web with HTML, CSS and JavaScript and that works perfectly in web storm and also the browser evaluates that right. So, I think it must be a problem with vs code. So, reopen this issue,please.

**Comment by minkir014** [comment]
I think it's the same problem as #31800 and as what's said there the root problem is what my issue is talking about. So, reopen this issue and thank you.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior and we don't intend to change anything here. Issues that don't have concrete next steps are closed, so that's the state this one will remain in unless there is evidence to suggest concrete next steps that should be done from our side.

**Comment by minkir014** [comment]
I am not who will tell you what will you do.. I am reporting a bug. This is not a PR.
