### ISSUE TITLE
`jsx` and `noEmit` compilerOptions not respected from tsconfig.json

### ISSUE THREAD

**Issue by hellatan** [microsoft/TypeScript#31782]
**TypeScript Version:**  3.5.1

**Search Terms:**
compilerOptions, noEmit, jsx, allowJs, checkJs
**Code**
outputted config when running `tsc --showConfig`:
```ts
{
    "compilerOptions": {
        "target": "es2017",
        "module": "es6",
        "lib": [
            "dom",
            "esnext"
        ],
        "allowJs": true,
        "checkJs": true,
        "jsx": "preserve", // <= does not seem to do anything when not defined in the cli
        "noEmit": true, // <= does not seem to do anything when not defined in the cli
        "noImplicitAny": false,
        "preserveConstEnums": false,
        "strict": true,
        "esModuleInterop": true,
        "sourceMap": true,
        "strictNullChecks": true,
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "forceConsistentCasingInFileNames": true,
        "typeRoots": [
            "/Users/node_modules/custom/types",
            "/Users/node_modules/@types"
        ]
    },
    "files": [
        // lots of files in both `./apps` and `./packages` dirs
    ],
    "include": [
        "./apps/**/*",
        "./packages/**/*"
    ],
    "exclude": [
        "**/*.js",
        "**/*.jsx",
        "**/*.graphql.ts"
    ]
}
```
Also to note, I am extending from a base tsconfig file but I'm not sure if that would have any affect on this issue.

**Expected behavior:**
- Having `"jsx": "preserve"` defined in a tsconfig.json should not throw `Cannot use JSX unless the '--jsx' flag is provided.` errors in the terminal
- Having `"noEmit": true` defined in a tsconfig.json should not compile files to js
- Running just `tsc` should respect both flags above.

**Actual behavior:**
I need to define both flags above as apart of my command line command in order for both issues to go away:
```
tsc --jsx preserve --noEmit
```
I also tried with typescript@3.6.0 and the same behavior is observed.

**Comment by RyanCavanaugh** [comment]
If these options simply did nothing, you wouldn't be the first person to notice 😉. Can you provide an isolated repro that demonstrates the problem?

**Comment by hellatan** [comment]
lol yes, true. I'm not sure what my setup was like when i opened this issue, but it could have been the way we have our build system setup that was giving me issues. I'm seeing now I don't need any of the flags in the cli to get our ts build to work as expected.
