### ISSUE TITLE
Emitting type parameters (regression)

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#31792]
**TypeScript Version:**  master

**Search Terms:**

**Code**

```ts
export class MyMap<K, V> {
	constructor(
		private readonly Map_: typeof Map = Map
	) {
	}
	private readonly store = new this.Map_<K, V>();
}
```

**Expected behavior:**

```js
export class MyMap {
    constructor(Map_ = Map) {
        this.Map_ = Map_;
        this.store = new this.Map_();
    }
}
```

**Actual behavior:**

```js
export class MyMap {
    constructor(Map_ = Map) {
        this.Map_ = Map_;
        this.store = new this.Map_<K, V>();
    }
}
```

**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment]
Wow, yeah.  That's not great.

**Comment by fatcerberus** [comment]
Ouch.

**Comment by ahejlsberg** [comment]
Whatever the regression is, it causes 28 projects in the RWC test suite to break.

@andrewbranch I'd suggest bisecting this and reverting whichever PR caused the break.

**Comment by andrewbranch** [comment]
My theory is it's #30467. I'm stepping through now to see if there's a quick fix, but I'll revert the offending PR if I can't figure it out in the next 30 minutes or so.

**Comment by ahejlsberg** [comment]
@andrewbranch Yup, RWC looks to run clean on the last commit prior to #30467.

@rbuckton Ping.

**Comment by rbuckton** [comment]
I'll take a look. It looks like we didn't have a test for this case.

**Comment by andrewbranch** [comment]
@rbuckton I've got a fix incoming.

**Comment by falsandtru** [comment]
Can you also take a look at another regression #31277?

**Comment by falsandtru** [comment]
@ahejlsberg You don't still have a test for this case.
