### ISSUE TITLE
function loses generic type depending on return value

### ISSUE THREAD

**Issue by pedambr** [microsoft/TypeScript#31790]
**TypeScript Version:**  2.9.2, 3.4.5, ^3.6.0-dev.20190606

**Search Terms:** generic type argument

**Code**

```ts
class GenericClass<T> {
  prop: T;
}

class StringClass extends GenericClass<string> {
}

function testfunc1<T, C extends GenericClass<T>>(param: C): T {
  return null;
}

function testfunc2<T>(param: T): Array<T> {
  return null;
}

function testfunc3<T, C extends GenericClass<T>>(param: C): Array<T> {
  return null;
}

function testit() {
    const stringgen: StringClass = null;
    let test: string;

    test = testfunc1(stringgen);

    test = testfunc2('foo')[0];

    test = testfunc3(stringgen)[0];
}
```

**Expected behavior:**  
ts compiles, return values are assignable to string or string[]

**Actual behavior:**  
error on the last line in testit();  
`Type '{}' is not assignable to type 'string'.`  

ts seems to lose the type and replaces it with {}  
its funny because testfunc3 is a combination of testfunc1 & testfunc2

**Playground Link:** https://www.typescriptlang.org/play/#src=class%20GenericClass%3CT%3E%20%7B%0D%0A%20%20prop%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aclass%20StringClass%20extends%20GenericClass%3Cstring%3E%20%7B%0D%0A%7D%0D%0A%0D%0Afunction%20testfunc1%3CT%2C%20C%20extends%20GenericClass%3CT%3E%3E(param%3A%20C)%3A%20T%20%7B%0D%0A%20%20return%20null%3B%0D%0A%7D%0D%0A%0D%0Afunction%20testfunc2%3CT%3E(param%3A%20T)%3A%20Array%3CT%3E%20%7B%0D%0A%20%20return%20null%3B%0D%0A%7D%0D%0A%0D%0Afunction%20testfunc3%3CT%2C%20C%20extends%20GenericClass%3CT%3E%3E(param%3A%20C)%3A%20Array%3CT%3E%20%7B%0D%0A%20%20return%20null%3B%0D%0A%7D%0D%0A%0D%0Afunction%20testit()%20%7B%0D%0A%20%20%20%20const%20stringgen%3A%20StringClass%20%3D%20null%3B%0D%0A%20%20%20%20let%20test%3A%20string%3B%0D%0A%0D%0A%20%20%20%20test%20%3D%20testfunc1(stringgen)%3B%0D%0A%0D%0A%20%20%20%20test%20%3D%20testfunc2('foo')%5B0%5D%3B%0D%0A%0D%0A%20%20%20%20test%20%3D%20testfunc3(stringgen)%5B0%5D%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by pedambr** [comment]
the only workaround i came up with so far is to add an unused parameter with type T to testfunc3.  
i dont get why T works as a return type but Observable<T> doesnt.  
there has to be a better way

**Comment by dragomirtitian** [comment]
You don't need `T` you can extract it from `C` using an index type query.

```
class GenericClass<T> {
  prop: T;
}

class StringClass extends GenericClass<string> {
}

function testfunc3<C extends GenericClass<any>>(param: C): Array<C['prop']> {
  return null;
}

function testit() {
    const stringgen: StringClass = null;
    let test: string;
    test = testfunc3(stringgen)[0];
}
```

Typescript will not infer type parameters based on other type parameters, only based on arguments. This would also work, because we gaev the compiler an inference site for `T`:
```
function testfunc3<C extends GenericClass<T>, T>(param: C & GenericClass<T>): Array<T> {
  return null;
}

function testit() {
    const stringgen: StringClass = null;
    let test: string;
    test = testfunc3(stringgen)[0];
}
```
