### ISSUE TITLE
typescript official docs duplicate `tsconfig.json` link bug

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/TypeScript#31796]
# typescript official docs duplicate `tsconfig.json` link bug

![image](https://user-images.githubusercontent.com/7291672/59040677-c061db80-88a9-11e9-95fb-98bcb238ddee.png)

**TypeScript Version:**  

> TypeScript 3.4

**Expected behavior:**

> only need once

**Actual behavior:**

> duplicate

**Comment by orta** [comment]
This is now fixed 👍
