### ISSUE TITLE
as const when type is not inferred

### ISSUE THREAD

**Issue by jasonoverby** [microsoft/TypeScript#31791]
**TypeScript Version:**  3.6.0-dev.20190606

**Search Terms:**
* as const
* type widening

**Code**

```ts
interface Z {
  num: number;
}
const y = {
  num: 1,
} as const;
// y.num = 3; // this fails
const z: Z = {
  num: 1,
} as const;
z.num = 3; // this does not fail
```

**Expected behavior:**
Properties of objects designated `as const` should not be allowed to be reassigned.

**Actual behavior:**
When the type of an object is set explicitly and not inferred, reassignment is possible.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=interface%20Z%20%7B%0D%0A%20%20num%3A%20number%3B%0D%0A%7D%0D%0Aconst%20y%20%3D%20%7B%0D%0A%20%20num%3A%201%2C%0D%0A%7D%20as%20const%3B%0D%0Ay.num%20%3D%203%3B%20%2F%2F%20this%20fails%0D%0Aconst%20z%3A%20Z%20%3D%20%7B%0D%0A%20%20num%3A%201%2C%0D%0A%7D%20as%20const%3B%0D%0Az.num%20%3D%203%3B%20%2F%2F%20this%20does%20not%20fail

**Related Issues:** 
N/A

**Comment by jcalz** [comment]
If anything I'd expect the assignment of an object with a readonly property to a value with a read-write property would be the error (so the line `const z: Z = ...` should be an error).  Think of it like this:

```ts
interface ReadonlyZ {
  getNum(): number;
}

interface Z extends ReadonlyZ {
  setNum(num: number): void;
}

const y: ReadonlyZ = { getNum: () => 1 }
y.setNum(3); // this fails, of course, y doesn't have a setNum

const z: Z = { getNum: () => 1 } // error!
// can't assign this, setNum() is missing in z
z.setNum(3); // okay, too late to complain
```

I think by the time you get to `z.num = 3`, it's too late for the compiler to do anything about it.  The variable is of type `Z`, whose `num` property is mutable.  

Anyway, if *this* is the underlying issue, it's being tracked at #13347.  If not, uh... never mind.

**Comment by jasonoverby** [comment]
Yes - that is correct.  Thanks.

**Comment by fatcerberus** [comment]
The issue with these cases IIRC is that TS didn't always have `readonly` so the best it can say about unannotated properties in practice is basically just "well, it exists".  So disallowing the assignment would be a huge breaking change, and `readonly` is therefore a bit of a cruel joke as a result.  What we need is some kind of `writable` annotation to say "this property will definitely be mutated at some point".  If we had that then the assignment to `z: Z` above could then be an error without breaking anyone's code.
