### ISSUE TITLE
[website] Website hasn't been updated for Typescript 3.5

### ISSUE THREAD

**Issue by lemoinem** [microsoft/TypeScript#31795]
**TypeScript Version:**  N/A
**Search Terms:** Website What's New 3.5 typescriptlang.org

**Code**
N/A

**Expected behavior:**
The website should be up-to-date and follow closely the actual release of new versions

**Actual behavior:**
It's been about a week since Typescript 3.5 has been out (https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/), but the website still hasn't been updated:
The homepage still announces "TypeScript 3.4 is now available. Download our latest version today!"
The documentation "What's New" section doesn't have a Typescript 3.5 section (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html)

**Playground Link:**
Playgroung is also sitting at version 3.4.1 (as mentioned by @jcalz):
https://www.typescriptlang.org/play/index.html#src=type%20Person%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20age%3A%20number%3B%0D%0A%20%20%20%20location%3A%20string%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20QuantumPerson%20%3D%20Omit%3CPerson%2C%20%22location%22%3E%3B

**Related Issues:** N/A

**Note:**
This isn't the first time this happened (https://github.com/microsoft/TypeScript/issues/29784)
Maybe the steps used to release a new version should include updating the website?

**Comment by jcalz** [comment]
> **Playground Link**: N/A

Since the [Playground](https://www.typescriptlang.org/play//) is also sitting at version 3.4.1, I'd say it's pretty applicable.  😏

**Comment by lemoinem** [comment]
@jcalz Fair enough ;) , I've updated the description.

**Comment by metasansana** [comment]
I'm wondering if this is how releases are normally done (docs updated after the release)? Considering 3.5 has breaking changes, the website not being updated makes me think its not finalized yet.
I'm sticking to 3.4 for now.

**Comment by lemoinem** [comment]
Once VS Code Stable (https://code.visualstudio.com/updates/v1_35#_typescript-35) ships with the new version, I consider it finalized.
But the website not being updated prevents me from using it.

**Comment by JakeTunaley** [comment]
Since it hasn't yet been pointed out, it's worth noting that _What's New in Typescript 3.5_ is already available if you know the URL (http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html), but a link to that page doesn't exist under _What's New_.

**Comment by lemoinem** [comment]
The website has been updated. Closing this issue.

**Comment by HolgerJeromin** [comment]
> The website has been updated. Closing this issue.

http://www.typescriptlang.org/#download-links still (or again?) links to 
https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-341-vs2017
