### ISSUE TITLE
Wrong type infer for spread arrays

### ISSUE THREAD

**Issue by worudso** [microsoft/TypeScript#31809]
**TypeScript Version:**  3.6.0-dev.20190606

**Search Terms:**
spread, array
**Code**

```ts
const a = {
  ...[1, 2, 3],
};
a.slice // === undefined actually!
console.log(a.slice);
```

**Expected behavior:**
`a` doesn't have `slice` property
**Actual behavior:**
`a` has `slice` property for `Array` type.
**Playground Link:** 
https://www.typescriptlang.org/play/#src=const%20a%20%3D%20%7B%0D%0A%20%20...%5B1%2C%202%2C%203%5D%2C%0D%0A%7D%3B%0D%0Aa.slice%20%2F%2F%20%3D%3D%3D%20undefined%20actually!%0D%0Aconsole.log(a.slice)%3B
**Related Issues:**

**Comment by fatcerberus** [comment]
...wait, is that even a legal thing to do?  Spreading an array into an object like that?

**Comment by worudso** [comment]
It works. In that case, you got `{ a: 1, b: 2, c: 3 }` for a.
I know it's not recommended even possible, but I found a special use case for it. https://github.com/microsoft/TypeScript/issues/31575#issuecomment-495891534

**Comment by fatcerberus** [comment]
Yeah, arrays are just objects like almost everything else in JS, *of course* that would work.  Brainfart on my part, ignore my stupidity. 😄

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/28801

**Comment by RyanCavanaugh** [comment]
#9726
