### ISSUE TITLE
Allow module definitions to be declared as global variables

### ISSUE THREAD

**Issue by dfaivre** [Microsoft/TypeScript#3180]
I have the React type definition file (that is declared using an external module). In my source files, I usually do:
```typescript
import * as R from "react"
```
and can then happily use `R.createElement(...` etc in a strongly typed fashion.  I can even do:
```typescript
let _r = R;
_r.createElement(...
```

What I want is to not have to import R in every file, and instead have it as a global declaration (yes, I'm willing to polute the global namespace with a few variables). I've tried, in a `.d.ts`:
```typescript
import * as React from "react";
declare var R : React;
```
This doesn't work though, I get "Cannot find name 'React'". Is there another way to export the entire module as global, without having modify the underling react.d.ts?

**Comment by ahejlsberg** [comment]
It isn't possible to do this because the minute you add an `import` declaration to a source file it is considered an external module. Any reason you're not using the React definition file that uses a global?

https://github.com/borisyankov/DefinitelyTyped/blob/master/react/react-global.d.ts

Looks to me like this would solve the problem.

**Comment by dfaivre** [comment]
I actually tried `react-global.d.ts` as well, which obviously puts `React` in the global space, but how would I globally rename it and let Typescript know about it?

```typescript
declare var _r = React;  // error Cannot find name 'React';
```

My real use case would be to be able to hoist a utility/common type module to the global space so I don't have to use a bunch of relative path imports to get to it.  I can do this in Javascript, but am struggling on how I let the Typescript compiler know I've done it.

@ahejlsberg -- I'm sure you have way more import things to be doing than putting up with my musings on edge cases... :)

**Comment by ahejlsberg** [comment]
You could for example create an `r.d.ts` declaration file:
```typescript
/// <reference path="react-global.d.ts"/>
declare var R: typeof React;
```
and then just reference that file everywhere. Or even better:
```typescript
/// <reference path="react-global.d.ts"/>
import R = React;
```
which will allow you to also reference types from React as R.xxx.

**Comment by dfaivre** [comment]
I've never seen a use of `typeof` before -- pretty cool.  This works great for already defined modules from a `.d.ts`, but I'm still don't see a way to hoist an external module defined in Typescript to the global space and have Typescript know about it.  Maybe because it's an anti-pattern and I should just get over it...

**Comment by ahejlsberg** [comment]
We've had a few requests (e.g. #2357) to extend `typeof` to support external modules, but so far there hasn't been a lot of demand for the feature.

Generally speaking, programs are either written without external modules or exclusively with external modules. Other than the bootstrap part of an AMD browser app, there really is no execution environment where the mixed model is even possible. So yes, it is mostly an anti-pattern.

**Comment by dfaivre** [comment]
Thanks for taking all the time to humor me on this!  I've just started exploring external modules (to play with the upcoming Angular2 and Aurelia frameworks).  Issues like #17, #2338 and #2839 seem to be more of what I'm looking for in the end.  Hopefully I'll come up with clearer feedback as I dive deeper into my current project.

**Comment by Evertt** [comment]
Is this still not possible to do? I'm trying to use TypeScript with VueJS and I would very much appreciate if I could import a few things into the global namespace so that all components can use it without having to import those things. Has there been any progress or hacks made to make this work?

**Comment by geekflyer** [comment]
@Evertt 

I found a way which apparently works with typescript 2.x.x. In my case I want to expose the library ramda as global `R`.

1. `npm install ramda @types/ramda`
2. create file `typings/ramda.d.ts`
3. add the newly created `typings` folder to the includes in .tsconfig.json:  
```json
"include": [
    "typings/**/*",
     ...
]
``` 
4. add the magic to `typings/ramda.d.ts`:
```ts
import * as _R from 'ramda';

export as namespace RASD;
export = _R; 
```

**Comment by Evertt** [comment]
@geekflyer thank you that was very helpful
