### ISSUE TITLE
Rename symbol doesn't work in JS sometimes

### ISSUE THREAD

**Issue by john-cj** [microsoft/TypeScript#31800]
(Not sure is it a bug or not.)

There are no extensions installed, just a fresh install of VS Code. The "rename symbol" fails under some circumstances.

In this JS example you can successfully rename function name `foo` or variable name `name` to something different:

```js
function foo() {
    var name = "John", surname = "Doe";
    if (name == "John") {
        alert("The full name is " + name + " " + surname);
    }
}

// TODO: Change function name from foo to
//       something better!
foo()
```

However, if you remove the function:

* if you put the cursor on the first occurrence of `name` and then try to rename this symbol - it will be renamed only this occurrence
* if you put the cursor on the second occurrence of `name` - it will be a message "You cannot rename elements that are defined in the standard TypeScript library"

```js
var name = "John", surname = "Doe";
if (name == "John") {
    alert("The full name is " + name + " " + surname);
}
```

![vscode](https://user-images.githubusercontent.com/18004961/59033869-727db100-8872-11e9-8289-afa5e041ddec.png)

Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:18:19.664Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 6.1.7600

**Comment by mjbvz** [comment]
This issue has the same root cause as #31783. There is a global value  in the DOM typings called `name` conflicts with the local `name`. If you are working in a module this is not an issue but for global style javascript files, you hit this.

You can see this warning more easily by adding `//@ts-check` to the top of the file to enable type checking in it.

Moving upstream to see if the UX can be improved for this

**Comment by fatcerberus** [comment]
At first I was going to say "Shouldn't the global `name` be shadowed?" but then I realize that in this case it *is* the global `name` because top-level `var` puts things on the global object...
