### ISSUE TITLE
Mapped Tuple Type, removing optional modifier always removes undefined from property type

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31810]
**TypeScript Version:**  3.4.1, 3.5.1

**Search Terms:** mapped tuple type, remove optional, removes undefined

**Code**

```ts
//strictNullChecks
function foo (_0 : number, _opt? : string) {

}
type RemoveOpt<T> = {
    [index in keyof T]-? : undefined|T[index]
}
/*
	Expected: type p = [number | undefined, string | undefined]
	Actual  : type p = [number | undefined, string]
*/
type p = RemoveOpt<Parameters<typeof foo>>;
```

**Expected behavior:**

```ts
type p = [number | undefined, string | undefined]
```

**Actual behavior:**

```ts
type p = [number | undefined, string]
```

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=%2F%2FstrictNullChecks%0D%0Afunction%20foo%20(_0%20%3A%20number%2C%20_opt%3F%20%3A%20string)%20%7B%0D%0A%0D%0A%7D%0D%0Atype%20RemoveOpt%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bindex%20in%20keyof%20T%5D-%3F%20%3A%20undefined%7CT%5Bindex%5D%0D%0A%7D%0D%0A%2F*%0D%0A%09Expected%3A%20type%20p%20%3D%20%5Bnumber%20%7C%20undefined%2C%20string%20%7C%20undefined%5D%0D%0A%09Actual%20%20%3A%20type%20p%20%3D%20%5Bnumber%20%7C%20undefined%2C%20string%5D%0D%0A*%2F%0D%0Atype%20p%20%3D%20RemoveOpt%3CParameters%3Ctypeof%20foo%3E%3E%3B)

**Related Issues:**

#31025 Related, but somewhat different. This is for mapped tuple types.

The workaround by @jcalz will not work for mapped tuple types

-----

My original intent was to have `[number, string|undefined]` instead of `[number, (string|undefined)?]`

So, I tried to remove the optional modifier.

But it removed `undefined` as well.

So, I tried to add it back. But it refused to take it.

**Comment by AnyhowStep** [comment]
This workaround works,

```ts
//strictNullChecks
function foo (_0 : number, _opt? : string) {

}
type AddUndefined<T, OriginalT> = (
    {
        [index in keyof T] : (
            undefined extends OriginalT[Extract<index, keyof OriginalT>] ?
            undefined|T[index] :
            T[index]
        )
    }
);
type RemoveOpt<T> = (
    AddUndefined<
        {
            [index in keyof T]-? : T[index]
        },
        T
    >
)
type p = RemoveOpt<Parameters<typeof foo>>;
```

[Playground](http://www.typescriptlang.org/play/#src=%2F%2FstrictNullChecks%0D%0Afunction%20foo%20(_0%20%3A%20number%2C%20_opt%3F%20%3A%20string)%20%7B%0D%0A%0D%0A%7D%0D%0Atype%20AddUndefined%3CT%2C%20OriginalT%3E%20%3D%20(%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bindex%20in%20keyof%20T%5D%20%3A%20(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20undefined%20extends%20OriginalT%5BExtract%3Cindex%2C%20keyof%20OriginalT%3E%5D%20%3F%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20undefined%7CT%5Bindex%5D%20%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20T%5Bindex%5D%0D%0A%20%20%20%20%20%20%20%20)%0D%0A%20%20%20%20%7D%0D%0A)%3B%0D%0Atype%20RemoveOpt%3CT%3E%20%3D%20(%0D%0A%20%20%20%20AddUndefined%3C%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5Bindex%20in%20keyof%20T%5D-%3F%20%3A%20T%5Bindex%5D%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20T%0D%0A%20%20%20%20%3E%0D%0A)%0D%0Atype%20p%20%3D%20RemoveOpt%3CParameters%3Ctypeof%20foo%3E%3E%3B)

But I shouldn't have to use such a hack =/

**Comment by fatcerberus** [comment]
I might be wrong about this but I think that in general, TS doesn't make a distinction between "optional thing" and "thing that might be undefined" other than for the purpose of existence checks.  Other than that they treated as equivalent.

**Comment by AnyhowStep** [comment]
Except, I would expect the `-?` to be applied first, and then the `|undefined` to be applied second.
So, the resultant type should be required but can be optional.

**Comment by jcalz** [comment]
This is a duplicate of #31025 unless the code that excludes `undefined` from property values is implemented separately for mapped tuples, right?
