### ISSUE TITLE
HTMLInputElement type "file" change event.target type (EventTarget) has no files.

### ISSUE THREAD

**Issue by Domvel** [microsoft/TypeScript#31816]
Is there an event type for the HTMLInputElement change event? Currently is automatically resolved as general `Event` > `EventTarget`. Which has no `files` property. see `FileList`.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

Example:

```ts
const fileInput = document.createElement('input');
fileInput.type = 'file';
fileInput.addEventListener('change', (event: Event) => {
  handleFileLoad(event.target.files); // Error: files does not exist on EventTarget.
});
document.body.appendChild(this.fileInput);
```

tsconfig.json (typescript 3.4.5): 
```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": true,
    "sourceMap": true,
    "module": "esnext",
    "target": "es5",
    "moduleResolution": "node",
    "strict": true
  },
  "exclude": ["node_modules", "dist"]
}
```

If not, this is a feature request. :) e.g.

**Comment by hennihaus** [comment]
same problem

**Comment by leonelngande** [comment]
As per [this Stackoverflow answer](https://stackoverflow.com/a/44932086), you can cast `event.target` as `HTMLInputElement` to get around this.
```
document.getElementById("customimage").onchange= function(e: Event) {
    let file = (<HTMLInputElement>e.target).files[0];
    //rest of your code...
}
```

**Comment by DDeme** [comment]
I suggest extending EventTarget for optional property files.

**Comment by ZackDeRose** [comment]
For those that come behind, I liked this solution:

```ts
export type FileEventTarget = EventTarget & { files: FileList };

const fileInputNativeElement =
  fromEvent(fileInputNativeElement, 'change') as Observable<{ target: FileEventTarget }>;
```

**Comment by amatiasq** [comment]
I always wondered why `EventTarget` is not generic.

```ts
interface EventTarget<T = any> {
  target: T;
}
```

This can be made

**Comment by onlyprogrammer01** [comment]
*******************************
Don't put the type of event :)
*******************************

**Comment by infacto** [comment]
I'm working with TypeScript `~3.8.3` and `HTMLInputElement` contains now `files` (`FileList`).

```ts
const target = event.target as HTMLInputElement;
const files = target.files;
```

[See sources](https://github.com/microsoft/TypeScript/blob/v3.8.3/lib/lib.dom.d.ts#L7339) 👍

**Comment by onlyprogrammer01** [comment]
> I'm working with TypeScript `~3.8.3` and `HTMLInputElement` contains now `files` (`FileList`).
> 
> 
> 
> ```ts
> 
> const target = event.target as HTMLInputElement;
> 
> const files = target.files;
> 
> ```
> 
> 
> 
> [See sources](https://github.com/microsoft/TypeScript/blob/v3.8.3/lib/lib.dom.d.ts#L7339) 👍 


I was have the same problem and it worked when I quit use the type of element. Thank you for answer me.

**Comment by Domvel** [comment]
That's correct. It also exists in [TypeScript 3.4.5](https://github.com/microsoft/TypeScript/blob/v3.4.5/lib/lib.dom.d.ts#L6904). It also exists in the old version [TypeScript 2.0](https://github.com/microsoft/TypeScript/blob/v2.0.10/lib/lib.dom.d.ts#L5671)
I don't know what I was thinking back then. ... 🤦‍♂️

I close this issue as fixed. Thanks. The type `HTMLInputElement` has the property `files` which is nullable `FileList`. All fine.

```ts
const target = event.target as HTMLInputElement;
const files = target.files;
```

**Comment by amatiasq** [comment]
I understood the issue as `event.target` doesn't have files and that's because it requires casting.
We could take this opportunity to remove the casting step using generics

**Comment by Domvel** [comment]
```ts
const fileInput = document.createElement('input');
fileInput.type = 'file';
fileInput.addEventListener('change', event => {
  console.log(event.target.files);
});
```

This is acual resolved by the TypeScript in VS Code. (just hover the method to see it.)

```ts
HTMLInputElement.addEventListener<"change">(
  type: "change", 
  listener: (this: HTMLInputElement, ev: Event) => any, 
  options?: boolean | AddEventListenerOptions
): void
```
Means that the HTMLInputElement is detected and maybe available for a generic event type. 🤔 
Is there already a generic `Event` type? But anyway it is not resolved in this generic type. 
It's a good idea. If TypeScript detects the context of the event listener - in this case - why not?
But note that in my initial post, I use the fixed type `Event` for the `event` variable.

**Comment by stof** [comment]
the issue with making `target` generic here is related to bubbling events. Adding a listener somewhere will generally not guarantee you the type of `target` as it can actually be dispatched on a child node. For instance, clicking on a button might actually click on an icon inside that button instead.

**Comment by phfoxer** [comment]
> As per [this Stackoverflow answer](https://stackoverflow.com/a/44932086), you can cast `event.target` as `HTMLInputElement` to get around this.
> 
> ```
> document.getElementById("customimage").onchange= function(e: Event) {
>     let file = (<HTMLInputElement>e.target).files[0];
>     //rest of your code...
> }
> ```

 let files:FileList = (<FileList>(<HTMLInputElement>e.target).files);
console.log(files.item(0));

**Comment by egorovsa** [comment]
Just
```
function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    console.log(event.target.files);
}
```

**Comment by egorovsa** [comment]
if your typescript version is higher than 3.7 you can use "?"
like this 
``` const file = e.currentTarget.files?.[0]; // pay attention the type will be File | undefined ```

**Comment by egorovsa** [comment]
Just check it through: "?"
```const file = target.files?.[0];```
however pay attention that the type will be File | undefined

**Comment by egorovsa** [comment]
> How can I tell typescript that I exactly will get a file in this example? Does anybody know?
> 
> ```
> const upload = (e: React.ChangeEvent<HTMLInputElement>) => {
>     e.preventDefault();
>     const target = e.currentTarget as HTMLInputElement;
>     const file = target.files[0];
>     console.log(file)
> };
> ```
> 
> Is says on this line const file = target.files[0] that object is possibly null

Just check it through: "?"
```const file = target.files?.[0];```
however pay attention that the type will be File | undefined

**Comment by stevenKirill** [comment]
How can I tell typescript that I exactly will get a file in this example? Does anybody know?

    const upload = (e: React.ChangeEvent<HTMLInputElement>) => {
        e.preventDefault();
        const target = e.currentTarget as HTMLInputElement;
        const file = target.files[0];
        console.log(file)
    };

Is says on this line const file = target.files[0] that object is possibly null

**Comment by Dassderdie** [comment]
@stevenKirill 
You could use the [non-null-assertion-operator-postfix](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-), like this `const file = target.files![0];` if you are completely sure that `files` is defined.

**Comment by hejuhenryk** [comment]
> How can I tell typescript that I exactly will get a file in this example? Does anybody know?
> 
> ```
> const upload = (e: React.ChangeEvent<HTMLInputElement>) => {
>     e.preventDefault();
>     const target = e.currentTarget as HTMLInputElement;
>     const file = target.files[0];
>     console.log(file)
> };
> ```
> 
> Is says on this line const file = target.files[0] that object is possibly null

then check if it is not 
` if (e.target.files && e.target.files.length > 0) {
            const file = e.target.files[0]`

**Comment by ritikbanger** [comment]
`React.ChangeEvent<HTMLInputElement> `this doesn't work in case of `filelist`. It gives the error: Type 'FileList' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators

**Comment by umbrashia** [comment]
use "Types" for solution of that problem 
`  export type TGenericEvent<T> = Event & { target: T }; `

use like this 

`eventCall(evt?: TGenericEvent<HTMLInputElement>): void {
    console.log("event",evt?.target.value);
  }`

<img width="600" alt="image" src="https://user-images.githubusercontent.com/15147330/202502082-9fbc711f-a348-4057-808d-9296ed3be7cc.png">

**Comment by AntonyStone1** [comment]
```
  const onFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSelectedFile(event.target.files[0]);
  }
```

**Comment by guiled** [comment]
@umbrashia  and @amatiasq  suggestion should be implemented natively in ts

**Comment by rcollette** [comment]
Casting isn't helpful for unit tests.   Having the Event type be a generic would be more useful.

![image](https://user-images.githubusercontent.com/136476/218494694-5a2d3034-e40c-4b48-b9f2-bcf82c6cf047.png)

**Comment by vincerubinetti** [comment]
I ended up having to do this:

```typescript
type FileEvent = ChangeEvent<HTMLInputElement> & {
  target: EventTarget & { files: FileList };
};
```

🤪

**Comment by KraXen72** [comment]
i think a good option is this:
```ts
async function upload(e: InputEvent & { target: HTMLInputElement} ) {
	if (!e.target.files || e.target.files.length === 0) return;
	const file = e.target.files[0];
	//...
}
```
i'm on `typescript@^5.1.6` but unsure if that's relevant

**Comment by cassepipe** [comment]
It's kind sad to have to track down what the DOM events types are over there : https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/f85d145348fc853bc7fecea5e5925c66a2e0e0b6/inputfiles/addedTypes.jsonc#L193

Only to find out that the event you need does not exist in some issue
