### ISSUE TITLE
Suggestion: generate conversion from string to Date implicitly when casting

### ISSUE THREAD

**Issue by panesofglass** [Microsoft/TypeScript#3181]
Proposal: generate code to create a `Date` from a `string` when the specified TypeScript type expects a `Date`.

I noticed that TypeScript will implicitly cast a `number` to an enumeration type. I know this happens because enumerations are represented as `number`s in the generated JavaScript, but this is still incredibly useful. Another case where this would be useful is in the case of [casting from a parsed JSON string to an expected interface](http://www.typescriptlang.org/Playground/#src=interface%20Json%20%7B%0A%09name%3A%20string%3B%0A%09date%3A%20Date%3B%0A%7D%0A%0Avar%20result%20%3D%20%3CJson%3EJSON.parse('%7B%22name%22%3A%22Ryan%22%2C%22date%22%3A%222014-08-23T11%3A00%3A00Z%22%7D')%3B%0A%0Aconsole.log(result.date%20instanceof%20Date)%3B%0A%0A%2F%2Fvar%20actual%20%3D%20%3CJson%3E%7B%0A%2F%2F%20%20%20%20name%3A%20%22Someone%22%2C%0A%2F%2F%20%20%20%20date%3A%20%222014-08-23T11%3A00%3A00Z%22%0A%2F%2F%7D%3B%0A%0A%2F%2F%20e.g.%0A%0A%2F%2F%24.ajax(%7B%20type%3A%20'GET'%2C%20url%3A%20'%2Fapi%2Fdata'%20%7D).then((data%3A%20Json)%20%3D%3E%20%7B%0A%2F%2F%20%20%20%20console.log(data.date%20instanceof%20Date)%3B%20%2F%2F%20prints%20true%0A%2F%2F%7D)%3B):

``` typescript
interface Json {
	name: string;
	date: Date;
}

var result = <Json>JSON.parse('{"name":"Ryan","date":"2014-08-23T11:00:00Z"}');

console.log(result.date instanceof Date); // proposal: make this true

var actual = <Json>{
    name: "Someone",
    date: "2014-08-23T11:00:00Z"
}; // type checker fails

// example usage:

$.ajax({ type: 'GET', url: '/api/data' }).then((data: Json) => {
	console.log(data.date instanceof Date); // prints true
});
```

This of course could create runtime errors, but I think this would still be incredibly useful for dealing with JSON.

**Comment by orlandpm** [comment]
:+1: In general, more built in support for deserializing JSON would be helpful

**Comment by DanielRosenwasser** [comment]
I think this is out of scope and could easily be serviced with a helper function instead.

**Comment by danquirk** [comment]
This also seems to have as a prerequisite tracking the actual values of strings within any string typed variable (which would be useful for things like specialized signatures but isn't something we currently support).
