### ISSUE TITLE
Allow wildcards in interface implementation

### ISSUE THREAD

**Issue by amirsaleem-kn** [microsoft/TypeScript#31827]
Let us say I have a class Controller which has some set of methods. I want my controller class methods to have 3 parameters of some type. I want to ensure that every method in a class implement methods in a defined way

```
  /**
   * I want every method of the UserController class to
   * have req, res and next as parameters. Parameters
   * other than req, res and next should not be allowed
   */

   class UserController {
      // correct implementation, as this method has
      // req, res and next as a parameter
      public async login(req: Request, res: Response, next: NextFunction) {
         // do some login stuff here
      }

      // wrong implementation, as req, res and next are missing
      public async signup(username, password) {
         // do some signup stuff here
      }
   }
```

I know I can create an interface for UserController that defines each and every method of UserController with fixed set of parameters. But I want a more general solution which should force the developer to follow a set pattern. If I use interface, I will have to check for the correct implementation of Controller at each code review process.

Possible Solution:

```
  interace Controller {
    *(): (req: Request, res: Response, next: NextFunction) => Promise<void>;
  }

 class UserController implements Controller {
    // now every method in UserController must implement 3 parameters.
 }
```

**Comment by AnyhowStep** [comment]
Not on my computer right now but would this work?

```ts
interface Controller {
    [name : string] : (req: Request, res: Response, next: NextFunction) => void
}
```

**Comment by dragomirtitian** [comment]
An index signature is a possible solution (although that kind of turns of type checking when accessing class members). 

Another solution is to use `Record` and `keyof` for the current class:


```ts
class UserController implements Record<keyof UserController, (req: Request, res: Response, next: NextFunction)=> void>  {
    // correct implementation, as this method has
    // req, res and next as a parameter
    public async login(req: Request, res: Response, next: NextFunction) {
        // do some login stuff here
    }

    // err
    public async signup(username: string, password: string) {
        // do some signup stuff here
    }
}
```

**Comment by AnyhowStep** [comment]
Or,
```ts
type NextFunction = (err : any) => void;

type RequestHandlerOnly<T> = (
    {
        [name in keyof T] : (
            T[name] extends (...args: any[]) => any?
            (req: Request, res: Response, next: NextFunction) => void :
            T[name]
        )
    }
);

class UserController implements RequestHandlerOnly<UserController> {
    //OK, non-methods can be any type
    str: string = "test";
    //OK, non-methods can be any type
    buffer: Uint8Array | undefined = undefined;

    // correct implementation, as this method has
    // req, res and next as a parameter
    public async login(req: Request, res: Response, next: NextFunction) {
        // do some login stuff here
    }

    //Error, public methods must implement (req, res, next) => void
    public async signup(username: string, password: string) {
        // do some signup stuff here
    }

    //OK, private methods can have any signature
    private async privateSignup(username: string, password: string) {
        // do some signup stuff here
    }

    //OK, protected methods can have any signature
    protected async protectedSignup(username: string, password: string) {
        // do some signup stuff here
    }
}
```

[Playground](http://www.typescriptlang.org/play/#src=type%20NextFunction%20%3D%20(err%20%3A%20any)%20%3D%3E%20void%3B%0D%0A%0D%0Atype%20RequestHandlerOnly%3CT%3E%20%3D%20(%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bname%20in%20keyof%20T%5D%20%3A%20(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20T%5Bname%5D%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3F%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20(req%3A%20Request%2C%20res%3A%20Response%2C%20next%3A%20NextFunction)%20%3D%3E%20void%20%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20T%5Bname%5D%0D%0A%20%20%20%20%20%20%20%20)%0D%0A%20%20%20%20%7D%0D%0A)%3B%0D%0A%0D%0Aclass%20UserController%20implements%20RequestHandlerOnly%3CUserController%3E%20%7B%0D%0A%20%20%20%20%2F%2FOK%2C%20non-methods%20can%20be%20any%20type%0D%0A%20%20%20%20str%3A%20string%20%3D%20%22test%22%3B%0D%0A%20%20%20%20%2F%2FOK%2C%20non-methods%20can%20be%20any%20type%0D%0A%20%20%20%20buffer%3A%20Uint8Array%20%7C%20undefined%20%3D%20undefined%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20correct%20implementation%2C%20as%20this%20method%20has%0D%0A%20%20%20%20%2F%2F%20req%2C%20res%20and%20next%20as%20a%20parameter%0D%0A%20%20%20%20public%20async%20login(req%3A%20Request%2C%20res%3A%20Response%2C%20next%3A%20NextFunction)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20login%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2FError%2C%20public%20methods%20must%20implement%20(req%2C%20res%2C%20next)%20%3D%3E%20void%0D%0A%20%20%20%20public%20async%20signup(username%3A%20string%2C%20password%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20signup%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2FOK%2C%20private%20methods%20can%20have%20any%20signature%0D%0A%20%20%20%20private%20async%20privateSignup(username%3A%20string%2C%20password%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20signup%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2FOK%2C%20protected%20methods%20can%20have%20any%20signature%0D%0A%20%20%20%20protected%20async%20protectedSignup(username%3A%20string%2C%20password%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20signup%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by amirsaleem-kn** [comment]
> Or,
> 
> ```ts
> type NextFunction = (err : any) => void;
> 
> type RequestHandlerOnly<T> = (
>     {
>         [name in keyof T] : (
>             T[name] extends (...args: any[]) => any?
>             (req: Request, res: Response, next: NextFunction) => void :
>             T[name]
>         )
>     }
> );
> 
> class UserController implements RequestHandlerOnly<UserController> {
>     //OK, non-methods can be any type
>     str: string = "test";
>     //OK, non-methods can be any type
>     buffer: Uint8Array | undefined = undefined;
> 
>     // correct implementation, as this method has
>     // req, res and next as a parameter
>     public async login(req: Request, res: Response, next: NextFunction) {
>         // do some login stuff here
>     }
> 
>     //Error, public methods must implement (req, res, next) => void
>     public async signup(username: string, password: string) {
>         // do some signup stuff here
>     }
> 
>     //OK, private methods can have any signature
>     private async privateSignup(username: string, password: string) {
>         // do some signup stuff here
>     }
> 
>     //OK, protected methods can have any signature
>     protected async protectedSignup(username: string, password: string) {
>         // do some signup stuff here
>     }
> }
> ```
> 
> [Playground](http://www.typescriptlang.org/play/#src=type%20NextFunction%20%3D%20(err%20%3A%20any)%20%3D%3E%20void%3B%0D%0A%0D%0Atype%20RequestHandlerOnly%3CT%3E%20%3D%20(%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bname%20in%20keyof%20T%5D%20%3A%20(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20T%5Bname%5D%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3F%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20(req%3A%20Request%2C%20res%3A%20Response%2C%20next%3A%20NextFunction)%20%3D%3E%20void%20%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20T%5Bname%5D%0D%0A%20%20%20%20%20%20%20%20)%0D%0A%20%20%20%20%7D%0D%0A)%3B%0D%0A%0D%0Aclass%20UserController%20implements%20RequestHandlerOnly%3CUserController%3E%20%7B%0D%0A%20%20%20%20%2F%2FOK%2C%20non-methods%20can%20be%20any%20type%0D%0A%20%20%20%20str%3A%20string%20%3D%20%22test%22%3B%0D%0A%20%20%20%20%2F%2FOK%2C%20non-methods%20can%20be%20any%20type%0D%0A%20%20%20%20buffer%3A%20Uint8Array%20%7C%20undefined%20%3D%20undefined%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20correct%20implementation%2C%20as%20this%20method%20has%0D%0A%20%20%20%20%2F%2F%20req%2C%20res%20and%20next%20as%20a%20parameter%0D%0A%20%20%20%20public%20async%20login(req%3A%20Request%2C%20res%3A%20Response%2C%20next%3A%20NextFunction)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20login%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2FError%2C%20public%20methods%20must%20implement%20(req%2C%20res%2C%20next)%20%3D%3E%20void%0D%0A%20%20%20%20public%20async%20signup(username%3A%20string%2C%20password%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20signup%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2FOK%2C%20private%20methods%20can%20have%20any%20signature%0D%0A%20%20%20%20private%20async%20privateSignup(username%3A%20string%2C%20password%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20signup%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2FOK%2C%20protected%20methods%20can%20have%20any%20signature%0D%0A%20%20%20%20protected%20async%20protectedSignup(username%3A%20string%2C%20password%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20signup%20stuff%20here%0D%0A%20%20%20%20%7D%0D%0A%7D)

Yes, this is the correct implementation,

Mine looks something like this now
``
type ParamsLength<F extends (...args: any) => any> = Parameters<F>["length"];

type AcceptableMethod = (req: Request, res: Response, next: NextFunction) => Promise<void>;

type Invalid<T> = T & Error;
type ControllerConstraints<T> = { [K in keyof T]:
    T[K] extends (...args: any) => any ? (
        ParamsLength<T[K]> extends ParamsLength<AcceptableMethod> ? AcceptableMethod :
        T[K] extends AcceptableMethod ? Invalid <
            ["Expected", ParamsLength<AcceptableMethod>, "parameters, got", ParamsLength<T[K]>]
        > : AcceptableMethod
    ) : T[K]
};
