### ISSUE TITLE
Spread First/Infinite Generic Spreads in Function Arguments

### ISSUE THREAD

**Issue by wbhob** [microsoft/TypeScript#31832]
## Search Terms

spread, function, signature, lodash, ngrx, generic, arguments

## Suggestion

I looked through the issues, and it doesn't seem like anything quite like this has been proposed yet – however, it is a feature of JavaScript, and it would be great to see in TypeScript as well. 

The first part of this proposal is rest parameters coming first in a function signature, much like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8d217f368733b640b90ffc0c8d8224746733f6cf/types/lodash/common/array.d.ts#L2557-L2655) example from the lodash types on DT. You'll notice that the same function signature is repeated five times, since the "important" property (`iteratee`) comes last in the signature. Then, the spread operator is used in the last signature, but at the expense of better type checking (line 2653).

Ideally, a signature for this use case could look like this:

```ts
unionBy<T>(
    this: LoDashImplicitWrapper<List<T> | null | undefined>,
    ...arrays: List<T> | null | undefined,
    iteratee?: ValueIteratee<T>
): LoDashImplicitWrapper<T[]>;
```

I'm not quite sure how this would fit in to TypeScript, but it would be a great feature to have.

Similarly, in NgRx, the newest version has ten (*TEN*) signatures for the same function, before again giving up on perfect type checking. [Here's the function in reference.](https://github.com/ngrx/platform/blob/b59edc547a2982bbf6c0afe861ea4f9b025cc028/modules/store/src/reducer_creator.ts#L14-L170) You'll notice, it also has a final `reducer` argument, similar to the lodash example. Ideally, a solution to this issue would look something like this (similar to the spread generic proposal):
	
```ts
export function on<...E extends ActionCreator, S>(
  ...creators: ...E,
  reducer: OnReducer<S, ...E>
): On<S>;
```

These would both be great features to see in TypeScript that are already available in vanilla JS. I hope this is a feasible feature for TS!

## Use Cases

(in the text block above)

## Examples

(in the text block above)

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
> however, it is a feature of JavaScript

```
> function fn(...rest, other) {}
Thrown:
function fn(...rest, other) {}
                   ^

SyntaxError: Rest parameter must be last formal parameter
```

As this is not valid JavaScript syntax, it would require the use of type information to work out the proper signature for a call, and therefore represents type-directed emit (i.e. we have to know the type of the function in order to generate correct code to call it).

Anything that requires type-directed emit is a non-starter because of:
> 5. Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

**Comment by wbhob** [comment]
Great point @fatcerberus. I guess libraries like lodash just use the `arguments` object internally. Could this be part of the emit (losing type safety in the emission)?

```ts
// input (contrived example)
function fn(...rest: number[], final: string) {
	const total = sum(rest);
	console.log(final, ': ', total);
}
```

```ts
// output
function fn() {
	const total = sum(arguments.slice(0, arguments.length - 2);
	console.log(arguments.length - 1, ': ', total);
}
```

**Comment by RyanCavanaugh** [comment]
> This isn't a runtime feature 

This is a runtime feature
