### ISSUE TITLE
cannot merge namespaces from external files

### ISSUE THREAD

**Issue by xxyyzz2050** [microsoft/TypeScript#31835]
I have 2 files, both exports namespace types, and I expect both to be merged

index.d.ts:
```
export namespace types{
  export interface something{}
}
```

anotherfile.ts:
```
/// <reference types="./index" /> //even adding this line dosen't solve the problem

export namespace types{
 export interface something2 extends something{} //error: types has no exported member something
```
}

**Comment by RyanCavanaugh** [comment]
Please follow the issue template.

https://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules/30357635
