### ISSUE TITLE
Number literal should not extend enum of different value

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31834]
**TypeScript Version:**  3.4.1, 3.5.1

**Search Terms:** number literal, extend, enum

**Code**

```ts
enum E {
    A = 1,
    B = 2,
}
/**
    Expected: "y"
    Actual  : "y"
    OK!
*/
type oneShouldExtendA = 1 extends E.A ? "y" : "n";
/**
    Expected: "n"
    Actual  : "y"
    ???
*/
type oneShouldNotExtendB = 1 extends E.B ? "y" : "n";

/**
    Expected: "y"
    Actual  : "y"
    OK!
*/
type aShouldExtend1 = E.A extends 1 ? "y" : "n";
/**
    Expected: "n"
    Actual  : "n"
    OK!
*/
type bShouldNotExtend1 = E.B extends 1 ? "y" : "n";
```

**Expected behavior:**

`oneShouldNotExtendB` should be `"n"`

**Actual behavior:**

`oneShouldNotExtendB` is `"y"`

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=enum%20E%20%7B%0D%0A%20%20%20%20A%20%3D%201%2C%0D%0A%20%20%20%20B%20%3D%202%2C%0D%0A%7D%0D%0A%2F**%0D%0A%20%20%20%20Expected%3A%20%22y%22%0D%0A%20%20%20%20Actual%20%20%3A%20%22y%22%0D%0A%20%20%20%20OK!%0D%0A*%2F%0D%0Atype%20oneShouldExtendA%20%3D%201%20extends%20E.A%20%3F%20%22y%22%20%3A%20%22n%22%3B%0D%0A%2F**%0D%0A%20%20%20%20Expected%3A%20%22n%22%0D%0A%20%20%20%20Actual%20%20%3A%20%22y%22%0D%0A%20%20%20%20%3F%3F%3F%0D%0A*%2F%0D%0Atype%20oneShouldNotExtendB%20%3D%201%20extends%20E.B%20%3F%20%22y%22%20%3A%20%22n%22%3B%0D%0A%0D%0A%2F**%0D%0A%20%20%20%20Expected%3A%20%22y%22%0D%0A%20%20%20%20Actual%20%20%3A%20%22y%22%0D%0A%20%20%20%20OK!%0D%0A*%2F%0D%0Atype%20aShouldExtend1%20%3D%20E.A%20extends%201%20%3F%20%22y%22%20%3A%20%22n%22%3B%0D%0A%2F**%0D%0A%20%20%20%20Expected%3A%20%22n%22%0D%0A%20%20%20%20Actual%20%20%3A%20%22n%22%0D%0A%20%20%20%20OK!%0D%0A*%2F%0D%0Atype%20bShouldNotExtend1%20%3D%20E.B%20extends%201%20%3F%20%22y%22%20%3A%20%22n%22%3B)

**Related Issues:** 

Kind of feels like a different version of #28654 (where true extended false)

**Comment by AnyhowStep** [comment]
#12647 seems somewhat related

**Comment by AnyhowStep** [comment]
Just adding some code as a note to myself,

```ts
enum E {
    A = 1,
    B = 2,
}
declare const discriminated: (
    {
        d: E.A,
        value: "A",
    } |
    {
        //E.B is 2
        //2 is 2
        d: E.B | 2,
        value: "B",
    }
);
if (discriminated.d == 1) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"A"'.
    */
    const v: "A" = discriminated.value;
}
if (discriminated.d == 2) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"B"'.
    */
    const v: "B" = discriminated.value;
}

if (discriminated.d == E.A) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"A"'.
    */
    const v: "A" = discriminated.value;
}
if (discriminated.d == E.B) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"B"'.
    */
    const v: "B" = discriminated.value;
}
/////////////////////////////////////////////////////

declare const discriminated2: (
    {
        d: E.A,
        value: "A",
    } |
    {
        //E.B is 2
        d: E.B,
        value: "B",
    }
);
if (discriminated2.d == 1) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"A"'.
    */
    const v: "A" = discriminated2.value;
}
if (discriminated2.d == 2) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"B"'.
    */
    const v: "B" = discriminated2.value;
}

if (discriminated2.d == E.A) {
    /**
        Expected: Assignment works
        Actual  : Assignment works
    */
    const v: "A" = discriminated2.value;
}
if (discriminated2.d == E.B) {
    /**
        Expected: Assignment works
        Actual  : Assignment works
    */
    const v: "B" = discriminated2.value;
}
```

[Playground](http://www.typescriptlang.org/play/#src=enum%20E%20%7B%0D%0A%20%20%20%20A%20%3D%201%2C%0D%0A%20%20%20%20B%20%3D%202%2C%0D%0A%7D%0D%0Adeclare%20const%20discriminated%3A%20(%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20d%3A%20E.A%2C%0D%0A%20%20%20%20%20%20%20%20value%3A%20%22A%22%2C%0D%0A%20%20%20%20%7D%20%7C%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2FE.B%20is%202%0D%0A%20%20%20%20%20%20%20%20%2F%2F2%20is%202%0D%0A%20%20%20%20%20%20%20%20d%3A%20E.B%20%7C%202%2C%0D%0A%20%20%20%20%20%20%20%20value%3A%20%22B%22%2C%0D%0A%20%20%20%20%7D%0D%0A)%3B%0D%0Aif%20(discriminated.d%20%3D%3D%201)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22A%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22A%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0Aif%20(discriminated.d%20%3D%3D%202)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22B%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22B%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0A%0D%0Aif%20(discriminated.d%20%3D%3D%20E.A)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22A%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22A%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0Aif%20(discriminated.d%20%3D%3D%20E.B)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22B%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22B%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0A%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0D%0A%0D%0Adeclare%20const%20discriminated2%3A%20(%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20d%3A%20E.A%2C%0D%0A%20%20%20%20%20%20%20%20value%3A%20%22A%22%2C%0D%0A%20%20%20%20%7D%20%7C%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2FE.B%20is%202%0D%0A%20%20%20%20%20%20%20%20d%3A%20E.B%2C%0D%0A%20%20%20%20%20%20%20%20value%3A%20%22B%22%2C%0D%0A%20%20%20%20%7D%0D%0A)%3B%0D%0Aif%20(discriminated2.d%20%3D%3D%201)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22A%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22A%22%20%3D%20discriminated2.value%3B%0D%0A%7D%0D%0Aif%20(discriminated2.d%20%3D%3D%202)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22B%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22B%22%20%3D%20discriminated2.value%3B%0D%0A%7D%0D%0A%0D%0Aif%20(discriminated2.d%20%3D%3D%20E.A)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Assignment%20works%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22A%22%20%3D%20discriminated2.value%3B%0D%0A%7D%0D%0Aif%20(discriminated2.d%20%3D%3D%20E.B)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Assignment%20works%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22B%22%20%3D%20discriminated2.value%3B%0D%0A%7D)

**Comment by AnyhowStep** [comment]
More notes,

```ts
enum E {
    A = 1,
    B = 2,
    C = 3,
}
declare const discriminated: (
    {
        d: 1,
        value: "A",
    } |
    {
        d: 2,
        value: "B",
    }
);
if (discriminated.d == 1) {
    /**
        Expected: Assignment works
        Actual  : Assignment works
    */
    const v: "A" = discriminated.value;
}
if (discriminated.d == 2) {
    /**
        Expected: Assignment works
        Actual  : Assignment works
    */
    const v: "B" = discriminated.value;
}
/**
    Expected: Equality check not allowed
    Actual  : Equality check not allowed
*/
if (discriminated.d == 3) {
}

//Equality check is allowed, but narrowing not applied?
if (discriminated.d == E.A) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"A"'.
    */
    const v: "A" = discriminated.value;
}
//Equality check is allowed, but narrowing not applied?
if (discriminated.d == E.B) {
    /**
        Expected: Assignment works
        Actual  : Type '"A" | "B"' is not assignable to type '"B"'.
    */
    const v: "B" = discriminated.value;
}
/**
    Expected: Equality check not allowed
    Actual  : Equality check allowed
*/
if (discriminated.d == E.C) {
}
```

[Playground](http://www.typescriptlang.org/play/#src=enum%20E%20%7B%0D%0A%20%20%20%20A%20%3D%201%2C%0D%0A%20%20%20%20B%20%3D%202%2C%0D%0A%20%20%20%20C%20%3D%203%2C%0D%0A%7D%0D%0Adeclare%20const%20discriminated%3A%20(%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20d%3A%201%2C%0D%0A%20%20%20%20%20%20%20%20value%3A%20%22A%22%2C%0D%0A%20%20%20%20%7D%20%7C%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20d%3A%202%2C%0D%0A%20%20%20%20%20%20%20%20value%3A%20%22B%22%2C%0D%0A%20%20%20%20%7D%0D%0A)%3B%0D%0Aif%20(discriminated.d%20%3D%3D%201)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Assignment%20works%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22A%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0Aif%20(discriminated.d%20%3D%3D%202)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Assignment%20works%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22B%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0A%2F**%0D%0A%20%20%20%20Expected%3A%20Equality%20check%20not%20allowed%0D%0A%20%20%20%20Actual%20%20%3A%20Equality%20check%20not%20allowed%0D%0A*%2F%0D%0Aif%20(discriminated.d%20%3D%3D%203)%20%7B%0D%0A%7D%0D%0A%0D%0A%2F%2FEquality%20check%20is%20allowed%2C%20but%20narrowing%20not%20applied%3F%0D%0Aif%20(discriminated.d%20%3D%3D%20E.A)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22A%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22A%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0A%2F%2FEquality%20check%20is%20allowed%2C%20but%20narrowing%20not%20applied%3F%0D%0Aif%20(discriminated.d%20%3D%3D%20E.B)%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20Assignment%20works%0D%0A%20%20%20%20%20%20%20%20Actual%20%20%3A%20Type%20'%22A%22%20%7C%20%22B%22'%20is%20not%20assignable%20to%20type%20'%22B%22'.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20const%20v%3A%20%22B%22%20%3D%20discriminated.value%3B%0D%0A%7D%0D%0A%2F**%0D%0A%20%20%20%20Expected%3A%20Equality%20check%20not%20allowed%0D%0A%20%20%20%20Actual%20%20%3A%20Equality%20check%20allowed%0D%0A*%2F%0D%0Aif%20(discriminated.d%20%3D%3D%20E.C)%20%7B%0D%0A%7D)

**Comment by AnyhowStep** [comment]
I ended up just writing yet-another-script to generate the namespace+union enum workaround.

**Comment by fatcerberus** [comment]
Yeah, long story short: numeric enum types are secretly just aliases for `number`.

```ts
enum E { A = 1, B = 2, C = 3 };

let e: E = E.C;

e = E.A;            // this is perfectly kosher
let n: number = e;  // questionable, but makes sense
e = 812;            // no error. not cool, man!
```

They're about as typesafe as C enums - which is to say, not typesafe at all. 😛

**Comment by jcalz** [comment]
It seems that `oneShouldExtendA` should also be `"n"` and not `"y"`.  In the perfect parallel universe where bit flags never existed, `E` is *narrower* than `number`; `E.A` should be equivalent to `1 & E`.   (Of course that intersection doesn't even work for string enums, see #21998).

**Comment by AnyhowStep** [comment]
E is narrower than number. But E.A and the literal `1` should be assignable to each other (in my head anyway).

But I wouldn't mind your expected behavior if it's just applied consistently

**Comment by fatcerberus** [comment]
It's not narrower in practice though, because like he said, bitfields are a thing.  `E.A & E.B` (bitwise `AND`, not a type intersection) might yield a value not listed in the enum.  That said, `E.A` not being a literal `1` *is* kind of weird.
