### ISSUE TITLE
trimLeft and trimRight's doc comments are swapped

### ISSUE THREAD

**Issue by shibukawa** [microsoft/TypeScript#31830]
**TypeScript Version:**  3.5.1-

**Search Terms:**

trimLeft

**Code**

Comment issue. there is no code to reproduce it.

**Expected behavior:**

trimLeft is alias of trimStart. trimRight is alias of trimEnd.

**Actual behavior:**

trimLeft has a same comment of trimEnd and trimRight has a same comment of trimStart.

**Playground Link:** 

**Related Issues:** 

None

**Comment by DanielRosenwasser** [comment]
Thank you @shibukawa!
