### ISSUE TITLE
Calling overloaded method on union type

### ISSUE THREAD

**Issue by cojj90** [microsoft/TypeScript#31839]
**TypeScript Version:**  3.6.0-dev.20190608

**Search Terms:** method overloading on union type

**Code**
please refer to the playground link below

**Expected behavior:**
Should be able to call eat method since it matches one of the signature.
On playground link, line 27 should not be marked as error. 

Funny thing is, removing line 2 (the un-matching function signature) makes tsc happy.
I've added line 32 to show typescript is happy as long as union type is not used

**Actual behavior:**
TSC marks it as error (Cannot invoke an expression whose type lacks a call signature.)

**Playground Link:**
[playground link](https://www.typescriptlang.org/play/index.html#src=interface%20Eat%3CT%3E%20%7B%0D%0A%20%20%20%20(props%3A%20Partial%3CT%3E%2C%20options%3A%20string)%3A%20T%3B%0D%0A%20%20%20%20(props%3A%20Partial%3CT%3E%2C%20options%3A%20boolean)%3A%20Promise%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Fruit%3CT%3E%20%7B%0D%0A%20%20%20%20color%3A%20string%0D%0A%20%20%20%20eat%3A%20Eat%3CT%3E%3B%0D%0A%7D%0D%0Atype%20Apple%20%3D%20%7B%0D%0A%20%20%20%20special%3A%20boolean%0D%0A%7D%0D%0Atype%20Banana%20%3D%20%7B%0D%0A%20%20%20%20long%3A%20boolean%0D%0A%7D%0D%0Atype%20Orange%20%3D%20%7B%0D%0A%20%20%20%20seedless%3A%20boolean%0D%0A%7D%0D%0A%0D%0Atype%20GoodFruit%20%3D%20Fruit%3CApple%3E%20%7C%20Fruit%3CBanana%3E%20%7C%20Fruit%3COrange%3E%0D%0Aconst%20goodFruit%3A%20GoodFruit%20%3D%20%7B%0D%0A%20%20%20%20color%3A%20'purple'%2C%0D%0A%20%20%20%20%2F%2F%40ts-ignore%0D%0A%20%20%20%20eat%3A%20Function%0D%0A%7D%0D%0A%0D%0AgoodFruit.eat(%7B%7D%2C%20true)%0D%0A%0D%0A%2F%2F%40ts-ignore%0D%0Aconst%20apple%3A%20Fruit%3CApple%3E%20%3D%20%7B%7D%0D%0A%0D%0Aapple.eat(%7B%7D%2C%20true))

**Comment by jack-williams** [comment]
Duplicate that is tracked here: #7294. Unions of call signatures currently do not work for generic signatures.
