### ISSUE TITLE
tsserver log jsconfig.json messages

### ISSUE THREAD

**Issue by whitecolor** [microsoft/TypeScript#31846]
- VSCode Version: 1.35 Insiders
- OS Version: Windows 10
- TS version 3.5.1

Actually what I experience it the problem with high CPU taken by tsserver electron process.
There were already many issues on this problem, but it seems nobody actually knows what do do with this.

 in VSCode, I turned on tsserver logs and periodically try to look at them:

In the config there are many messages about `jsconfig.json` like that:

```
Info 15   [14:53:50.980] ConfigFilePresence:: Current Watches: :: File: d:/Code/chartify/apps/client/cycles/jsconfig.json
```

But Have no any `jsconfig.json` files in the project, only one `tsconfig.json`, is it normal that it logs about it?

Project's tsconfig:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es2015", "dom"],
    "outDir": "./out",
    "module": "commonjs",
    "strict": true,
    "strictFunctionTypes": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "allowJs": false,
    "noEmit": false,
    "incremental": true,
    "baseUrl": ".",
    "traceResolution": true,
    "plugins": [
      {
        "name": "typescript-tslint-plugin",
        "alwaysShowRuleFailuresAsWarnings": true
      }
    ]
  },
  "formatCodeOptions": {
    "indentSize": 2,
    "tabSize": 2
  },
  "exclude": [
    "**/.yalc/*",
    ".yalc",
    "node_modules",
    "**/node_modules/*",
    ".tmp/*"
  ]
}
```

**Comment by mjbvz** [comment]
Can you share the full log?

**Comment by whitecolor** [comment]
I use the following settings:

```json
"typescript.tsserver.log": "verbose",
"typescript.tsserver.trace": "verbose",  
```

Full log usually takes a few hundreds of megs by the time problem to begin to appear. I will try next time again.

**Comment by whitecolor** [comment]
@mjbvz You can download full tsserve log from https://github.com/whitecolor/tsserverLogCPU private repo, I added you as collaborator.

**Comment by sheetalkamat** [comment]
@whitecolor Can you please give me access to the log so I can investigate. Thanks

**Comment by whitecolor** [comment]
@sheetalkamat done

**Comment by sheetalkamat** [comment]
This is working as indented. We do watch jsconfig and tsconfig files that are in folders from file to the tsconfig we found because anything there may affect what program your file belongs to.
