### ISSUE TITLE
Prepending `true ||` confuses strict null checks, even with correct bracketing

### ISSUE THREAD

**Issue by robinmessage** [microsoft/TypeScript#31855]
OR-ing an expression which passes type checking with `true` causes that expression to fail type checking.

**TypeScript Version:**  3.6.0-dev.20190611

**Search Terms:** boolean logic strict null check confused or with true

**Code**

```ts
type Foo = { bar?: { baz?: string } };
const foo = (something: Foo) => (something.bar && something.bar.baz);
const quux = (something: Foo) => true || (something.bar && something.bar.baz);
```

**Expected behavior:**
`foo` and `quux` both pass type checking with strict null checks.

**Actual behavior:**
`foo` is fine, but tsc complains about `something.bar.baz` in `quux`. It is almost like it interprets it as `(true || something.bar) && something.bar.baz` which would indeed be unsafe.

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20Foo%20%3D%20%7B%20bar%3F%3A%20%7B%20baz%3F%3A%20string%20%7D%20%7D%3B%0D%0Aconst%20foo%20%3D%20(something%3A%20Foo)%20%3D%3E%20(something.bar%20%26%26%20something.bar.baz)%3B%0D%0Aconst%20quux%20%3D%20(something%3A%20Foo)%20%3D%3E%20true%20%7C%7C%20(something.bar%20%26%26%20something.bar.baz)%3B%0D%0A
— N.B. it only fails with strict null checks turned on

**Related Issues:** I did not find any.

**Comment by nmain** [comment]
Duplicate of #26914

**Comment by robinmessage** [comment]
Thanks, it didn't occur to me that the code was unreachable and that was why it didn't work, so I didn't see the other ticket.
