### ISSUE TITLE
3.5.1 breaks simple unambiguous type guards?

### ISSUE THREAD

**Issue by Ziriax** [microsoft/TypeScript#31853]
We get some unexpected regression compiler errors in our code base when upgrading to `tsc 3.5.1`. 

We simplified the code for this bug report.

If this isn't a bug, it would be nice to know why this is now expected behavior, and what would be the recommended workaround?

**TypeScript Version:**  3.5.1

**Search Terms:**
`3.5`, `3.5.1`, `type guard`

**Code**

```ts
enum PrimitiveKind {
  Float,
  Integer,
}

function test(kind: PrimitiveKind.Float) {
  console.log("bla");
}

function works(kind: PrimitiveKind) {
  if (kind === PrimitiveKind.Float) {
    test(kind);
  }
}

function kaput1<K extends PrimitiveKind>(kind: K) {
  if (kind === PrimitiveKind.Float) {
    test(kind);
  }
}

function kaput2<K extends PrimitiveKind>(kind: K & PrimitiveKind) {
  if (kind === PrimitiveKind.Float) {
    test(kind);
  }
}

function guard(kind: any): kind is PrimitiveKind {
  // Just for reporting the bug
  return true;
}

function kaput3<K extends PrimitiveKind>(kind: K & PrimitiveKind) {
  if (guard(kind) && kind === PrimitiveKind.Float) {
    test(kind);
  }
}
```

**Expected behavior:**

The compiles without errors (worked in 3.4.0)

**Actual behavior:**

Compiler error `Type 'PrimitiveKind' is not assignable to type 'PrimitiveKind.Float'.` for functions `kaput1`, `kaput2` and `kaput3`.

(As Siegrift found out below, it seems this behavior started from version 3.4.5)

**Playground Link:** 

[Demo](https://www.typescriptlang.org/play/#src=enum%20PrimitiveKind%20%7B%0D%0A%20%20Float%2C%0D%0A%20%20Integer%2C%0D%0A%7D%0D%0A%0D%0Afunction%20test(kind%3A%20PrimitiveKind.Float)%20%7B%0D%0A%20%20console.log(%22bla%22)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20works(kind%3A%20PrimitiveKind)%20%7B%0D%0A%20%20if%20(kind%20%3D%3D%3D%20PrimitiveKind.Float)%20%7B%0D%0A%20%20%20%20test(kind)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20kaput1%3CK%20extends%20PrimitiveKind%3E(kind%3A%20K)%20%7B%0D%0A%20%20if%20(kind%20%3D%3D%3D%20PrimitiveKind.Float)%20%7B%0D%0A%20%20%20%20test(kind)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20kaput2%3CK%20extends%20PrimitiveKind%3E(kind%3A%20K%20%26%20PrimitiveKind)%20%7B%0D%0A%20%20if%20(kind%20%3D%3D%3D%20PrimitiveKind.Float)%20%7B%0D%0A%20%20%20%20test(kind)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20guard(kind%3A%20any)%3A%20kind%20is%20PrimitiveKind%20%7B%0D%0A%20%20%2F%2F%20Just%20for%20reporting%20the%20bug%0D%0A%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Afunction%20kaput3%3CK%20extends%20PrimitiveKind%3E(kind%3A%20K%20%26%20PrimitiveKind)%20%7B%0D%0A%20%20if%20(guard(kind)%20%26%26%20kind%20%3D%3D%3D%20PrimitiveKind.Float)%20%7B%0D%0A%20%20%20%20test(kind)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Related Issues:**

#31833 #31837

**Comment by Siegrift** [comment]
I am not sure why this doesn't work (and to my newbie understanding it should)... But I have found these workarounds

[playground](https://www.typescriptlang.org/play/#src=enum%20PrimitiveKind%20%7B%0D%0A%20%20Float%2C%0D%0A%20%20Integer%2C%0D%0A%7D%0D%0A%0D%0Afunction%20test(kind%3A%20PrimitiveKind.Float)%20%7B%0D%0A%20%20console.log(%22bla%22)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20guard(kind%3A%20any)%3A%20kind%20is%20PrimitiveKind.Float%20%7B%0D%0A%20%20%2F%2F%20Just%20for%20reporting%20the%20bug%0D%0A%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Afunction%20kaput3%3CK%20extends%20PrimitiveKind%3E(kind%3A%20PrimitiveKind)%20%7B%0D%0A%20%20if%20(guard(kind))%20%7B%0D%0A%20%20%20%20test(kind)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20kaput4%3CK%20extends%20PrimitiveKind%3E(kind%3A%20PrimitiveKind)%20%7B%0D%0A%20%20switch%20(kind)%20%7B%0D%0A%20%20%20%20case%20PrimitiveKind.Float%3A%0D%0A%20%20%20%20%20%20test(kind)%3B%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Comment by Siegrift** [comment]
@Ziriax Btw. for me it won't compile even with TS version 3.4.5

**Comment by Ziriax** [comment]
@Siegrift 

Indeed, we were still using TS 3.4.0, it fails with 3.4.5, nice catch!

```ts
function kaput4<K extends PrimitiveKind>(kind: PrimitiveKind) {
  switch (kind) {
    case PrimitiveKind.Float:
      test(kind);
      break;
  }
}
```

Thanks for the working code, it is amazing that a `switch` statement does work! Semantically this should be the same code no?

**Comment by ahejlsberg** [comment]
The sample code above has the same errors in every version of TypeScript going back 2.5, so whatever problem you have updating to 3.5.1, this isn't it.

**Comment by Ziriax** [comment]
Ouch, then we oversimplified the code that broke, mea culpa, I will revise.

**Comment by ahejlsberg** [comment]
The new errors you're seeing are likely related to #30769 and may be intended.

**Comment by Ziriax** [comment]
@ahejlsberg You are 100% correct, the full signature of the code that breaks in our code is

```ts

`function valueAt<K extends PrimitiveKind>(curve: AnyCurve<K>, time: Time): PrimitiveKindToType[K] {...}`

**Comment by Siegrift** [comment]
@ahejlsberg @Ziriax Sorry, I am not able to see how it is related. And I am curious about why TS is able to infer the enum type when using `switch` but not when using `if`. Can you please explain? :)

**Comment by ahejlsberg** [comment]
> And I am curious about why TS is able to infer the enum type when using switch but not when using if. Can you please explain?

The example declares a type parameter but never uses it.

**Comment by Siegrift** [comment]
No, it uses it in the `test` function (which is ommited from the snippet). Here is a working [playground](https://www.typescriptlang.org/play/#src=enum%20PrimitiveKind%20%7B%0D%0A%20%20Float%2C%0D%0A%20%20Integer%2C%0D%0A%7D%0D%0A%0D%0Afunction%20test(kind%3A%20PrimitiveKind.Float)%20%7B%0D%0A%20%20console.log(%22bla%22)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20guard(kind%3A%20any)%3A%20kind%20is%20PrimitiveKind.Float%20%7B%0D%0A%20%20%2F%2F%20Just%20for%20reporting%20the%20bug%0D%0A%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Afunction%20kaput3%3CK%20extends%20PrimitiveKind%3E(kind%3A%20PrimitiveKind)%20%7B%0D%0A%20%20if%20(guard(kind))%20%7B%0D%0A%20%20%20%20test(kind)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20kaput4%3CK%20extends%20PrimitiveKind%3E(kind%3A%20PrimitiveKind)%20%7B%0D%0A%20%20switch%20(kind)%20%7B%0D%0A%20%20%20%20case%20PrimitiveKind.Float%3A%0D%0A%20%20%20%20%20%20test(kind)%3B%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Comment by ahejlsberg** [comment]
@Siegrift Your playground example declares `K` type variables in the two functions and then proceeds to not use them. It makes no sense, but is working as intended. The errors in the original example were due to variables of a generic type not being narrowed--which is expected.
