### ISSUE TITLE
BUG: `allowSyntheticDefaultImports: true` breaks Typescript auto-import

### ISSUE THREAD

**Issue by abhikp** [microsoft/TypeScript#31859]
- VSCode Version: 1.34.0
- OS Version: OS X 10.14.4
- Typescript Version: 3.4.5
- Create React App: 2.1.5

`tsconfig.json`:
```
{
  "compilerOptions": {
    "target": "es6",
    "allowJs": true,
    "skipLibCheck": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "lib": [
      "esnext",
      "dom"
    ]
  },
  "include": [
    "src"
  ]
}
```

#### Behavior when `true`:

![true](https://user-images.githubusercontent.com/336114/58603390-6c218080-8245-11e9-930b-9cb5e42019a5.gif)

#### Behavior when `false`:

![false](https://user-images.githubusercontent.com/336114/58603395-704d9e00-8245-11e9-9715-2ce5b9411bf9.gif)

We have another project that seems to work fine with `allowSyntheticDefaultImports: true`. The other project is an Express app and its `tsconfig.json` is:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "strict": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "outDir": "dist",
    "resolveJsonModule": true,
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/types/*"
      ]
    },
    "lib": [
      "esnext",
      "dom"
    ]
  },
  "include": [
    "src/**/*"
  ]
}
```

We've directly copied its `tsconfig.json`, but that doesn't seem to bring back auto-import. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by IskanderMustafin** [comment]
Since this issue taking too much time to fix, is there any workaround? Having really bad developer experience because always need to manually write import statements and remember paths to files

**Comment by abhikp** [comment]
@IskanderMustafin our team starts our watch scripts (create-react-app, storybook) and then we set the config to `false`, the watch scripts don't seem to pick up the change. To prevent accidentally committing the change we added a git pre commit hook:

```bash
#!/bin/bash

if git diff --cached | grep -q "+    \"allowSyntheticDefaultImports\": false" 
then 
  echo "ERROR: tsconfig.json cannot set allowSyntheticDefaultImports to false"
  exit 1
fi
```

It's not bulletproof but it helps a lot!

**Comment by IskanderMustafin** [comment]
@abhikp Hi, thanks for helping. 

Seems in my case after I change `allowSyntheticDefaultImports` to `false` VSCode automatically picks up changes from `tsconfig` and my default imports are highlighted: 

![image](https://user-images.githubusercontent.com/2435892/63552266-a94d9400-c550-11e9-887b-c25ab0341082.png)

This happens automatically - I don't restart ts-server manully (using ctrl+alt+k)

**Comment by abhikp** [comment]
We use `import * as React from "react";`

**Comment by orta** [comment]
It looks like there's people talking about the same thing but on both options of the boolean for `allowSyntheticDefaultImports`

I've created a repo which tries to replicate the code sample in the body: https://github.com/orta/31859.git

However, I've not been able to see the bug with TS 3.9 when `allowSyntheticDefaultImports` is true

![Screen Shot 2020-07-14 at 2 59 29 PM](https://user-images.githubusercontent.com/49038/87465768-33786e00-c5e3-11ea-8f5c-ad1e405b1df5.png)

Or when `allowSyntheticDefaultImports` is false

![Screen Shot 2020-07-14 at 3 00 10 PM](https://user-images.githubusercontent.com/49038/87465766-32474100-c5e3-11ea-87c7-ad5a660611a1.png)

--- 

Interesting to note, there are dupes in the GIF, in the true case you click on the 2nd result, but on the false case you click on the 1st result. Perhaps there is also a global called `Pipeline` also?
    ![Screen Shot 2020-07-14 at 3 05 12 PM](https://user-images.githubusercontent.com/49038/87465954-763a4600-c5e3-11ea-8728-d11f20fbe811.png)
 
I'm going to de-milestone this issue but not close to give it chance for some discussion, but can anyone provide a repro which happens in modern TypeScript? 3.9 (and 4.0) has some solid improvements in the way in which we provide better auto import recommendations.

**Comment by JimmyMultani** [comment]
I'm running into this same issue on my project with this `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "lib": ["dom", "dom.iterable", "esnext"],
    "downlevelIteration": true,
    "declaration": true,
    "outDir": "build"
  },
  "include": ["src", "tests"]
}
```

Commenting out `esModuleInterop` and `allowSyntheticDefaultImports` seems to fix it, but then I can't do things like:

```ts
import React, {
  ReactElement,
  useState,
  useEffect,
  useCallback,
  useContext,
} from 'react';
```

**Comment by Retsam** [comment]
We're seeing similar issues, on one of our larger codebases: but unlike the title of this issue it appears to actually be `esModuleInterop: true` that causes the auto-complete to fail - with `esModuleInterop: false`, `allowSyntheticDefaultImports: true` the autoComplete seems to work.  (Which is strange, as I didn't think `esModuleInterop` itself affected types, really)

But yet, in one of our smaller codebases, auto-imports work even with identical config (including `esModuleInterop: true`)  So it seems to be a combination of the config and something about the size (or another non-config aspect) of the codebase.

The `typescript.preferences.includePackageJsonAutoImports` setting did not seem to affect this behavior.

**Comment by jscheel** [comment]
This has suddenly started for me as well, on `next-4.1.20200927`. All of my auto-imports break with this error, even though it has found the proper source to import from.

**Comment by NickersWeb** [comment]
This is a pretty major issue. Is there not a work around??

**Comment by andrewbranch** [comment]
We need to know the contents of Pipeline.tsx, or have another full repro from someone, to do anything about this.

> But yet, in one of our smaller codebases, auto-imports work even with identical config (including `esModuleInterop: true`) So it seems to be a combination of the config and something about the size (or another non-config aspect) of the codebase.

Not size—it’s something about a specific module and what/how it’s exporting.

**Comment by gpsolarco** [comment]
This helped me:
https://stackoverflow.com/questions/71791347/npm-package-cannot-be-used-as-a-jsx-component-type-errors
Answer: 37


You will need to fix the version for @types/react package because many react libraries have dependency set as @types/react : "*", which will take the latest version of the package. (I suppose they just released version 18)

To do that you can add this in your package.json

"resolutions": {
  "@types/react": "^17.0.38"
}
It will just work fine with yarn, but if you are using npm, then you will also need to add this in "scripts" section of your package.json

"preinstall": "npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions"
This will simply use [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) package to fix versions from resolutions.

And then after doing npm install, your app should work just fine.

**Comment by andrewbranch** [comment]
So much has changed with auto-imports since I last heard any reports of this bug, I’m going to assume it got accidentally fixed. Repros, logs, and new reports can be sent to a new issue. Thanks!
