### ISSUE TITLE
incremental typing of objects

### ISSUE THREAD

**Issue by MarcWeber** [microsoft/TypeScript#31854]
## Search Terms

dictionary

## Suggestion

Sometimes I want to do something like:

```
const a = {}
a.foo = () => {}
a.bar = () => { a.foo(); }
```

-> but this is hard to type because the a.bar cannot change the type of a.
You can give a type with foo? bar? but its all a mess.

I tried quora, irc and gitter -> but didn't get a reply whether this is possible.

Its a eventually a complicated topic because if a was used somewhere else and
you do 'destructive' updates such as changing types other code might be affected.

So this would require introducing tracking what is being done with it.

In cases like above it looks trivial.

## Note

This could be a duplicate. Thus if you know a proposal/solution kindly point to it. I failed finding it.

**Comment by dragomirtitian** [comment]
This would be analogous to the way arrays are gradually typed under `noImplictAny`:

```ts
let a = [];
a.push(1);
a[0].toExponential // a is number[]
```

**Comment by RyanCavanaugh** [comment]
Duplicate #12416
