### ISSUE TITLE
Fallback to js-docs and js-declaration if no d.ts exists for import.

### ISSUE THREAD

**Issue by Domvel** [microsoft/TypeScript#31851]
I wondering why does TypeScript not fallback to JavaScript declarations e.g. using doc-comments and / or use just the declarations as any for imports. If no d.ts found in the directory or types-folder.

Currently in TypeScript, I get an error while importing a JavaScript-Libray which has not d.ts build in or from other source like DefinitelyTyped-repo. (ts 7016)

In JavaScript I can just import it with (in good case) a well documented declaration information. e.g. VS Code intellisense works great and list all possible methods with the doc comments. 

I just think alond, why does TypeScript not just fallback to js if d.ts is not found. Maybe only with a tsconfig-option and only show a warning (or not by option).

I can use the JavaScript library without a declaration file like e.g.:

```ts
// @ts-ignore
import TypeLessLib from `type-less-lib`
```
(a library installed by npm. location in node_modules)

I can build and use it without problems. But VS Code intellisense does not work like in a js-file. 
Maybe this is a VS Code issue? But I think not quite, because typescript should support it too without ts-comments to ignore it. 

What do you think? 
Did you understand my request? Any question? I'm glad to answer.
In my opinion this should works without huge changes. Maybe this is already possible?

Why should we do this? 
Because it's better than any-type and cleaner that workarounds.
With this solution, you don't need a d.ts in best case. Because modern JS and clean code library will have doc-comments. Including types. ...

But still, why should we do this? TypeScript is much better than JavaScript.
Ok, this is not a question about which language is better. I like JavaScript, I love TypeScript. 
This is not a request to uglify TypeScript. It's a request to make it better using external libraries. 
Technically, it would work. You can use import in js like in ts. And you'll get all the definitions and docs-comments. But the question is, how to implement this in ts? How to allow it? How to fallback?

TypeScript version 3.5.1
VS Code 1.35
Windows 10

Refs:
https://github.com/microsoft/typescript/issues/3019

**Comment by RyanCavanaugh** [comment]
We've investigated this venue multiple times and very few libraries (that aren't already on DT) are machine-understandable as-is without substantial special effort to e.g. unpack UMD wrappers, follow module loading, understand eccentric JS Doc syntax, and parse a lot of extra code. The net result would be a lot of bad performance hit trying to analyze large chunks of JS without actually finding much usable JS Doc.

**Comment by Domvel** [comment]
Sure, JavaScript (libraries) files will never work seamless for TypeScript. To many type lacks etc. 
I just expected VS Code intellisense and TypeScript tolerance on importing a js library which has no d.ts.
Maybe this is a VS Code issue? Because finally I just want the intellisense / autocompletion of VS Code and TypeScript could handle all with any type without further analysis. I could define the lib for TypeScript as `any` type. But then VS Code will also do this. Currently VS Code does not use intellisense for imported JavaScript libraries in a TypeScript file. But perhaps this is a VSCode issue. (?)

I found a tsconfig option `allowJs`. It sounds like it's doing exactly what I want. But actual not.
Maybe a (new) tsconfig option will help. `tolerateJsImport` which tread all js imports which have no d.ts files as `any` type. And VS Code's intellisense should work. (I should open an issue in VS Code repo).

Indeed, if this option is active you can import `js` libs (without d.ts) with (in best case) a well documented autocomplete. But this documentation is only for the editor. TypeScript will handle all types as any. This could be a missunderstanding feature. (We can warn the developer for this) Any finally primitive types like strings and numbers will still detected correctly I think. ... 

Summary, the current behavior of this issue is having a d.ts (build-in library or separate by myself) or handle all as `any` type. But if I could just say it to TS (handle all d.ts-less js as any type), without the VS will notice. Then at least I would have the intellisense function of VS code. But this is also a VS Code issue.

Anyway, that's just a suggestion. Maybe it brings some ideas.
You can close this issue if this idea is ridiculous. If it will never be possible in any way. whatever...
