### ISSUE TITLE
Feature: allow for generic functions with conformance

### ISSUE THREAD

**Issue by tal** [microsoft/TypeScript#31862]
## Search Terms

generic function conformance 

## Suggestion

Allow for functions to both be generic and conform to generic types.

## Use Cases

Many use cases can be thought of but the primary issue I can see of value is having a react function with generic `Props`.

## Examples

If I want to have generic props for a React render function it's not currently possible, something like this should be possible:

```ts
interface Props<T> {
  myProp: T
}

const Comp: React.FC<Props<T>> = <T>({myProp}) => <div>{JSON.stringify(myProp)}</div>
```

Currently the generic in the type declaration is not conformed to by the generic defined in the function.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #17574
