### ISSUE TITLE
[Bug] Parameters of callback not inferred when passed to overloaded function expecting different number of params

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31867]
**TypeScript Version:**  3.4.1, 3.5.1

**Search Terms:**

parameter, infer, generic, callback

**Code**

```ts
//--noImplicitAny
class Clazz<T> {
    /**
        MUST NOT switch the declarations of `foo()`.
        Run-time logic uses first `foo()` when
        `callback.length <= 3`.
        Run-time logic uses second `foo()` when
        `callback.length == 4`.
    */
    foo(callback: (a: "A", b: "B", t: T) => void): void;
    foo(callback: (a: "A", b: "B", c: "C", t: T) => void): void;
    foo() {
        console.log("blah");
    }
}
const clazz = new Clazz<"qwerty">();
clazz.foo((a, b, t) => {
    //OK!
    //a : "A"
    //b : "B"
    //t : "qwerty"
});
clazz.foo((a, b, c, t) => {
    //Expected: a : "A", b : "B", c : "C", t : "qwerty"
    //Actual  :
    //+ a implicitly has any type
    //+ b implicitly has any type
    //+ c implicitly has any type
    //+ t implicitly has any type
});

//If you switch the declarations of `foo()`
class Clazz2<T> {
    /**
        If you switch the declarations of `foo()`...
    */
    foo(callback: (a: "A", b: "B", c: "C", t: T) => void): void;
    foo(callback: (a: "A", b: "B", t: T) => void): void;
    foo() {
        console.log("blah");
    }
}
const clazz2 = new Clazz2<"qwerty">();
clazz2.foo((a, b, t) => {
    //Expected:
    //a : "A"
    //b : "B"
    //t : "qwerty"
    
    //Actual:
    //a : "A"
    //b : "B"
    //t : "C" <-- Undesirable
});
clazz2.foo((a, b, c, t) => {
    //OK!
    //a : "A"
    //b : "B"
    //c : "C"
    //t : "qwerty"
});

```

**Expected behavior:**

+ Callback of `clazz.foo((a, b, c, t) => {})` should be inferred correctly
+ TS should select second overload of `foo()`

**Actual behavior:**

+ Callback of `clazz.foo((a, b, c, t) => {})` **not** inferred correctly (not expected)
+ TS selects second overload of `foo()` (as expected)

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=%2F%2F--noImplicitAny%0D%0Aclass%20Clazz%3CT%3E%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20MUST%20NOT%20switch%20the%20declarations%20of%20%60foo()%60.%0D%0A%20%20%20%20%20%20%20%20Run-time%20logic%20uses%20first%20%60foo()%60%20when%0D%0A%20%20%20%20%20%20%20%20%60callback.length%20%3C%3D%203%60.%0D%0A%20%20%20%20%20%20%20%20Run-time%20logic%20uses%20second%20%60foo()%60%20when%0D%0A%20%20%20%20%20%20%20%20%60callback.length%20%3D%3D%204%60.%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20foo(callback%3A%20(a%3A%20%22A%22%2C%20b%3A%20%22B%22%2C%20t%3A%20T)%20%3D%3E%20void)%3A%20void%3B%0D%0A%20%20%20%20foo(callback%3A%20(a%3A%20%22A%22%2C%20b%3A%20%22B%22%2C%20c%3A%20%22C%22%2C%20t%3A%20T)%20%3D%3E%20void)%3A%20void%3B%0D%0A%20%20%20%20foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%22blah%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20clazz%20%3D%20new%20Clazz%3C%22qwerty%22%3E()%3B%0D%0Aclazz.foo((a%2C%20b%2C%20t)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20%2F%2Fa%20%3A%20%22A%22%0D%0A%20%20%20%20%2F%2Fb%20%3A%20%22B%22%0D%0A%20%20%20%20%2F%2Ft%20%3A%20%22qwerty%22%0D%0A%7D)%3B%0D%0Aclazz.foo((a%2C%20b%2C%20c%2C%20t)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FExpected%3A%20a%20%3A%20%22A%22%2C%20b%20%3A%20%22B%22%2C%20c%20%3A%20%22C%22%2C%20t%20%3A%20%22qwerty%22%0D%0A%20%20%20%20%2F%2FActual%20%20%3A%0D%0A%20%20%20%20%2F%2F%2B%20a%20implicitly%20has%20any%20type%0D%0A%20%20%20%20%2F%2F%2B%20b%20implicitly%20has%20any%20type%0D%0A%20%20%20%20%2F%2F%2B%20c%20implicitly%20has%20any%20type%0D%0A%20%20%20%20%2F%2F%2B%20t%20implicitly%20has%20any%20type%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2FIf%20you%20switch%20the%20declarations%20of%20%60foo()%60%0D%0Aclass%20Clazz2%3CT%3E%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20%20%20%20If%20you%20switch%20the%20declarations%20of%20%60foo()%60...%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20foo(callback%3A%20(a%3A%20%22A%22%2C%20b%3A%20%22B%22%2C%20c%3A%20%22C%22%2C%20t%3A%20T)%20%3D%3E%20void)%3A%20void%3B%0D%0A%20%20%20%20foo(callback%3A%20(a%3A%20%22A%22%2C%20b%3A%20%22B%22%2C%20t%3A%20T)%20%3D%3E%20void)%3A%20void%3B%0D%0A%20%20%20%20foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%22blah%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20clazz2%20%3D%20new%20Clazz2%3C%22qwerty%22%3E()%3B%0D%0Aclazz2.foo((a%2C%20b%2C%20t)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FExpected%3A%0D%0A%20%20%20%20%2F%2Fa%20%3A%20%22A%22%0D%0A%20%20%20%20%2F%2Fb%20%3A%20%22B%22%0D%0A%20%20%20%20%2F%2Ft%20%3A%20%22qwerty%22%0D%0A%20%20%20%20%0D%0A%20%20%20%20%2F%2FActual%3A%0D%0A%20%20%20%20%2F%2Fa%20%3A%20%22A%22%0D%0A%20%20%20%20%2F%2Fb%20%3A%20%22B%22%0D%0A%20%20%20%20%2F%2Ft%20%3A%20%22C%22%20%3C--%20Undesirable%0D%0A%7D)%3B%0D%0Aclazz2.foo((a%2C%20b%2C%20c%2C%20t)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20%2F%2Fa%20%3A%20%22A%22%0D%0A%20%20%20%20%2F%2Fb%20%3A%20%22B%22%0D%0A%20%20%20%20%2F%2Fc%20%3A%20%22C%22%0D%0A%20%20%20%20%2F%2Ft%20%3A%20%22qwerty%22%0D%0A%7D)%3B%0D%0A)

**Related Issues:** 

#31146 somewhat related but they don't have overloads

-----

#21525 has overloads where both overloads have the same number of parameters. However, I'm pretty sure my case is different. In that issue, TS selected the first overload and not the second one.

In my case, TS selected the second overload but doesn't realize the parameters of the callback are `"A", "B", "C", "qwerty"`.

From this comment https://github.com/microsoft/TypeScript/issues/21525#issuecomment-362349470 , I've tried variations on conditional typing but nothing seems to work.

-----

My current use-case is wrapping `express` and its middleware feature. Each middleware may have arguments of length 0,1,2,3,4.

If the length is 0-3, it is a request handler.
If the length is 4, it is an error handler.
Otherwise, it is ignored.

So, I need the overload with 3 params to be the first overload.
And the overload with 4 params to be the second overload.

-----

It's weird that it knows what overload is correct, but can't infer the parameters. It's not like my parameters have conditional types or anything complex.

**Comment by AnyhowStep** [comment]
Shorter repro,

```ts
//--noImplicitAny
function foo<T>(callback: (a: "A", b: "B", t: T) => void): void;
function foo<T>(callback: (a: "A", b: "B", c: "C", t: T) => void): void;
function foo() {
    console.log("blah");
}
foo<"qwerty">((a, b, t) => {
    //OK!
    //a : "A"
    //b : "B"
    //t : "qwerty"
});
foo<"qwerty">((a, b, c, t) => {
    //Expected: a : "A", b : "B", c : "C", t : "qwerty"
    //Actual  :
    //+ a implicitly has any type
    //+ b implicitly has any type
    //+ c implicitly has any type
    //+ t implicitly has any type
});
```

Again, it knows the second `foo<"qwerty">()` is referring to the second overload,
it just can't infer the parameter types.

[Playground](http://www.typescriptlang.org/play/#src=%2F%2F--noImplicitAny%0D%0Afunction%20foo%3CT%3E(callback%3A%20(a%3A%20%22A%22%2C%20b%3A%20%22B%22%2C%20t%3A%20T)%20%3D%3E%20void)%3A%20void%3B%0D%0Afunction%20foo%3CT%3E(callback%3A%20(a%3A%20%22A%22%2C%20b%3A%20%22B%22%2C%20c%3A%20%22C%22%2C%20t%3A%20T)%20%3D%3E%20void)%3A%20void%3B%0D%0Afunction%20foo()%20%7B%0D%0A%20%20%20%20console.log(%22blah%22)%3B%0D%0A%7D%0D%0Afoo%3C%22qwerty%22%3E((a%2C%20b%2C%20t)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20%2F%2Fa%20%3A%20%22A%22%0D%0A%20%20%20%20%2F%2Fb%20%3A%20%22B%22%0D%0A%20%20%20%20%2F%2Ft%20%3A%20%22qwerty%22%0D%0A%7D)%3B%0D%0Afoo%3C%22qwerty%22%3E((a%2C%20b%2C%20c%2C%20t)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FExpected%3A%20a%20%3A%20%22A%22%2C%20b%20%3A%20%22B%22%2C%20c%20%3A%20%22C%22%2C%20t%20%3A%20%22qwerty%22%0D%0A%20%20%20%20%2F%2FActual%20%20%3A%0D%0A%20%20%20%20%2F%2F%2B%20a%20implicitly%20has%20any%20type%0D%0A%20%20%20%20%2F%2F%2B%20b%20implicitly%20has%20any%20type%0D%0A%20%20%20%20%2F%2F%2B%20c%20implicitly%20has%20any%20type%0D%0A%20%20%20%20%2F%2F%2B%20t%20implicitly%20has%20any%20type%0D%0A%7D)%3B%0D%0A)

**Comment by AnyhowStep** [comment]
Even shorter repro. Seems like generics aren't causing the issue,

```ts
//--noImplicitAny
function foo(callback: (a: "A") => void): void;
function foo(callback: (a: "A", b: "B") => void): void;
function foo() {
    console.log("blah");
}
foo((a) => {
    //OK!
    //a : "A"
});
foo((a, b) => {
    //Expected: a : "A", b : "B"
    //Actual  :
    //+ a implicitly has any type
    //+ b implicitly has any type
});

```

[Playground](http://www.typescriptlang.org/play/#src=%2F%2F--noImplicitAny%0D%0Afunction%20foo(callback%3A%20(a%3A%20%22A%22)%20%3D%3E%20void)%3A%20void%3B%0D%0Afunction%20foo(callback%3A%20(a%3A%20%22A%22%2C%20b%3A%20%22B%22)%20%3D%3E%20void)%3A%20void%3B%0D%0Afunction%20foo()%20%7B%0D%0A%20%20%20%20console.log(%22blah%22)%3B%0D%0A%7D%0D%0Afoo((a)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FOK!%0D%0A%20%20%20%20%2F%2Fa%20%3A%20%22A%22%0D%0A%7D)%3B%0D%0Afoo((a%2C%20b)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2FExpected%3A%20a%20%3A%20%22A%22%2C%20b%20%3A%20%22B%22%0D%0A%20%20%20%20%2F%2FActual%20%20%3A%0D%0A%20%20%20%20%2F%2F%2B%20a%20implicitly%20has%20any%20type%0D%0A%20%20%20%20%2F%2F%2B%20b%20implicitly%20has%20any%20type%0D%0A%7D)%3B%0D%0A)

**Comment by AnyhowStep** [comment]
Seems like the same thing is happening with `@types/express`,

![image](https://user-images.githubusercontent.com/5655961/59323302-208cbf00-8ca8-11e9-8794-1956673f03ed.png)

**Comment by ahejlsberg** [comment]
Let me first say that's a pretty terrible API. Having _different_ types in the same positions of a callback based it on measuring the number of parameters in the callback just sounds like a recipe for confusion.

It wouldn't be easy to fix this. Generally overload resolution works by checking whether the types of the arguments are compatible with the signature. But to find the type of the lambda argument we need to contextually type the parameters, and once we do that we can't undo it. We'd need to somehow disqualify the signature _before_ we contextually type the lambda parameters. That would pretty much require a separate additional phase in overload resolution.

**Comment by AnyhowStep** [comment]
I agree that it's terrible API design. I had to dig into the source code to see what it's actually doing =/

For now, I've added an extra method that uses a different name, which only takes the error handler.
Side-stepping the overload problem, basically =x

**Comment by ahejlsberg** [comment]
I'm going to close this as a design limitation.
