### ISSUE TITLE
"Extract to function" does not re-use type aliases

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#31861]
**TypeScript Version:**  3.5.1

**Search Terms:**

**Code**

```ts
type Foo = { tag: 'A' } | { tag: 'B' };
const fn = () => {
    declare const foo: Foo;
    const bar = foo.tag;
};
```

If I select the line `const bar` and then action "extract to function", I get:

``` ts
type Foo = { tag: 'A' } | { tag: 'B' };
const fn = () => {
    declare const foo: Foo;
    const bar = newFunction(foo);
};

function newFunction(foo: Foo) {
    return foo.tag;
}
```

That works as expected. However, if `Foo` is defined dynamically:

``` ts
type MyRecord = {
    A: { tag: 'A' };
    B: { tag: 'B' };
}
type Foo = MyRecord[keyof MyRecord]
const fn = () => {
    declare const foo: Foo;
    const bar = newFunction(foo);
};
```

… then "extract to function" will not re-use the type alias for the `foo` parameter and instead inline the whole structure:

``` ts
// expected function newFunction(foo: Foo) {
function newFunction(foo: { tag: "A"; } | { tag: "B"; }) {
    return foo.tag;
}
```

This is particularly problematic for large types. I often see TS inlining deeply nested type structures.

My main use case for this is when using [Unionize](https://github.com/pelotom/unionize):

``` ts
const Foo = unionize({
    A: ofType<{}>(),
    B: ofType<{}>(),
});
type Foo = UnionOf<typeof Foo>;
const fn = () => {
    const foo = Foo.A();
    const bar = foo.tag;
};
```

However I suspect that is a subtly different use case and may not be addressed by fixing my previous example.

**Comment by Andarist** [comment]
The alias is correctly preserved nowadays - the issue can be closed
