### ISSUE TITLE
Classes do not infer types from interfaces they implement

### ISSUE THREAD

**Issue by danfinlay** [microsoft/TypeScript#31874]
When using the `implements` keyword with a class, it seems like the types are not inferred on that class. This is counter-intuitive, isn't `implements` meant to help ensure a class is being implemented according to that interface?

Example:
```typescript
interface ILivingThing {
    born: (when: Date) => void;
    die: (how: string) => void;
}

class Person implements ILivingThing {
    born() { } // Infers type of () => void, instead of (Date) => void.
    die() { }
}
```

**Comment by RyanCavanaugh** [comment]
Duplicate #1373
