### ISSUE TITLE
Could you update the documentation on your site "typescriptlang.org"? (Need to add features of 3.5 version)

### ISSUE THREAD

**Issue by siarhei-murkou** [microsoft/TypeScript#31871]
P.S: Now the last actual version on this site is `3.4`.

**Comment by Seally** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/31795, but yeah, I second this. :)

**Comment by siarhei-murkou** [comment]
> Duplicate of #31795, but yeah, I second this. :)

@Seally Thank you for your reply! I filtered issues by "typescriptlang.org" and didn't find issues related with 3.5 version 😄 

Maybe this issue should stay be opened before updating docs...

**Comment by lemoinem** [comment]
@siarhei-murkou I've updated my issue to include typescriptlang.org. It can now be found with a search.
If you have additional search terms to suggest, I'll be happy to add them.

**Comment by siarhei-murkou** [comment]
@DanielRosenwasser Could you please tell me when documantation is going to be updated?

**Comment by DanielRosenwasser** [comment]
When I get past my email backlog.

**Comment by siarhei-murkou** [comment]
@DanielRosenwasser Thank you for quick response! Good luck with your backlog 🌞 
All TypeScript fans are wating new features documentated by you 😃
