### ISSUE TITLE
TS 3.5 regression - objects aren't inferred

### ISSUE THREAD

**Issue by arcanis** [microsoft/TypeScript#31875]
**TypeScript Version:**  3.5

**Search Terms:** protobuf

**Code**

```ts
import * as protobuf from 'protobufjs/light';

const root = new protobuf.Root();

export const protobufRoot = root.addJSON({
    hello: {
        nested: {
            Foo: {
                fields: {
                    permission: {
                        keyType: 'string',
                        type: 'int32',
                        id: 1
                    },
                }
            }
        }
    }
});
```

**3.4 behavior:**

No errors

**3.5 behavior:**

It seems like TypeScript isn't able to infer anymore that `keyType` implies that the value is of type `IMapField`. It expects it to be a `IField`, which doesn't contain this field.

```
index.ts:11:25 - error TS2326: Types of property 'nested' are incompatible.
  Type '{ Auth: { fields: { permission: { keyType: string; type: string; id: number; }; }; }; }' is not assignable to type '{ [k: string]: INamespace | IEnum | IExtensionField | IExtensionMapField | IType
 | IService; }'.
    Property 'Auth' is incompatible with index signature.
      Types of property 'fields' are incompatible.
        Type '{ permission: { keyType: string; type: string; id: number; }; }' is not assignable to type '{ [k: string]: IField; }'.
          Property 'permission' is incompatible with index signature.
            Type '{ keyType: string; type: string; id: number; }' is not assignable to type 'IField'.
              Object literal may only specify known properties, and 'keyType' does not exist in type 'IField'.

11                         keyType: 'string',
                           ~~~~~~~~~~~~~~~~~
```

**Playground Link:**

I didn't reproduce it without the `protobufjs` dependency.

**Comment by arcanis** [comment]
Note that it might be a bug in the library - `IMapField` doesn't seem to be connected to `IField` so I would actually expect it to fail in both 3.4 and 3.5 .. but I'm not sure if I'm missing a TS feature that would explain why it works. I tried to repro with the following code, but it fails on both versions:

https://www.typescriptlang.org/play/#src=export%20interface%20IField%20%7B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20rule%20*%2F%0D%0A%20%20%20%20rule%3F%3A%20string%3B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20type%20*%2F%0D%0A%20%20%20%20type%3A%20string%3B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20id%20*%2F%0D%0A%20%20%20%20id%3A%20number%3B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20options%20*%2F%0D%0A%20%20%20%20options%3F%3A%20%7B%20%5Bk%3A%20string%5D%3A%20any%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%2F**%20Map%20field%20descriptor.%20*%2F%0D%0Aexport%20interface%20IMapField%20extends%20IField%20%7B%0D%0A%0D%0A%20%20%20%20%2F**%20Key%20type%20*%2F%0D%0A%20%20%20%20keyType%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Foo%20%3D%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20IField%3B%0D%0A%7D%3B%0D%0A%0D%0Afunction%20foo(foo%3A%20Foo)%20%7B%7D%0D%0A%0D%0Afoo(%7B%0D%0A%20%20test%3A%20%7B%0D%0A%20%20%20%20keyType%3A%20'string'%2C%0D%0A%20%20%20%20type%3A%20'int64'%2C%0D%0A%20%20%20%20id%3A%201%2C%0D%0A%20%20%7D%2C%0D%0A%7D)%3B

**Comment by RyanCavanaugh** [comment]
We need a reduced repro that doesn't depend on an external .d.ts file in order to investigate this

**Comment by arcanis** [comment]
Found a repro! I'm almost positive that it's a bug that got fixed, however. Replacing `keyType` with `foo` doesn't yield any error either in 3.4.

https://www.typescriptlang.org/play/#src=%2F**%20Field%20descriptor.%20*%2F%0D%0Aexport%20interface%20IField%20%7B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20rule%20*%2F%0D%0A%20%20%20%20rule%3F%3A%20string%3B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20type%20*%2F%0D%0A%20%20%20%20type%3A%20string%3B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20id%20*%2F%0D%0A%20%20%20%20id%3A%20number%3B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20options%20*%2F%0D%0A%20%20%20%20options%3F%3A%20%7B%20%5Bk%3A%20string%5D%3A%20any%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%2F**%20Map%20field%20descriptor.%20*%2F%0D%0Aexport%20interface%20IMapField%20extends%20IField%20%7B%0D%0A%20%20%20%20%2F**%20Key%20type%20*%2F%0D%0A%20%20%20%20keyType%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F**%20Namespace%20descriptor.%20*%2F%0D%0Aexport%20interface%20INamespace%20%7B%0D%0A%0D%0A%20%20%20%20%2F**%20Namespace%20options%20*%2F%0D%0A%20%20%20%20options%3F%3A%20%7B%20%5Bk%3A%20string%5D%3A%20any%20%7D%3B%0D%0A%0D%0A%20%20%20%20%2F**%20Nested%20object%20descriptors%20*%2F%0D%0A%20%20%20%20nested%3F%3A%20%7B%20%5Bk%3A%20string%5D%3A%20AnyNestedObject%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%2F**%20Any%20nested%20object%20descriptor.%20*%2F%0D%0Atype%20AnyNestedObject%20%3D%20(IType%7CINamespace)%3B%0D%0A%0D%0Afunction%20fromJson(json%3A%20INamespace)%20%7B%20%7D%0D%0A%0D%0A%2F**%20Message%20type%20descriptor.%20*%2F%0D%0Aexport%20interface%20IType%20extends%20INamespace%20%7B%0D%0A%0D%0A%20%20%20%20%2F**%20Field%20descriptors%20*%2F%0D%0A%20%20%20%20fields%3A%20%7B%20%5Bk%3A%20string%5D%3A%20IField%20%7D%3B%0D%0A%0D%0A%7D%0D%0A%0D%0AfromJson(%7B%0D%0A%20%20%20%20%20%20%20%20nested%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20Auth%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fields%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20permission%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20keyType%3A%20'string'%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'int32'%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%3A%201%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A

**Comment by RyanCavanaugh** [comment]
See "Improved excess property checks in union types" in the release notes https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/

**Comment by arcanis** [comment]
Seems like it - when I replace:

```ts
type AnyNestedObject = (IType|INamespace);
// By
type AnyNestedObject = IType;
```

I get the expected error in 3.4 as well. Thanks for the explanation! 👍
