### ISSUE TITLE
`Parameters<T>` doesn't work when `T extends Function`

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#31881]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
function enqueueJob<J extends Function>(job: J, ...args: Parameters<J>) {
}
```

**Expected behavior:**

It should work.

**Actual behavior:**

It doesn't.

**Playground Link:** 

http://www.typescriptlang.org/play/#src=function%20enqueueJob%3CJ%20extends%20Function%3E(job%3A%20J%2C%20...args%3A%20Parameters%3CJ%3E)%20%7B%0D%0A%7D%0D%0A

I can fix it if I provide my own `Parameters` implementation:

```ts
type Parameters<T extends Function> = T extends (...args: infer T) => any ? T : never
```

Playground won't let me show the working example, it complains about the duplicate definition. But I can write that version in my module, and it works.

Is there some limitation of using `extends Function` that I haven't ran into?

**Comment by trusktr** [comment]
I can also work around it by making my own type instead of using Function, so:

```ts
type Job = (...args: any[]) => any

function enqueueJob<J extends Job>(job: J, ...args: Parameters<J>) {
}
```

[playground](http://www.typescriptlang.org/play/#src=type%20Job%20%3D%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%0D%0A%0D%0Afunction%20enqueueJob%3CJ%20extends%20Job%3E(job%3A%20J%2C%20...args%3A%20Parameters%3CJ%3E)%20%7B%0D%0A%7D%0D%0A)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. `Function` is just the object side of function-like things; it does *not* imply something callable despite the name.

**Comment by RyanCavanaugh** [comment]
(For example, class constructors are structurally `Function`s, but cannot be called do not meet the constraint of `Parameters`)

**Comment by trusktr** [comment]
Why does the difference between callable/not-callable matter? Shouldn't we be able to take parameters from either?
