### ISSUE TITLE
MutationObserver should accept HTMLElement too

### ISSUE THREAD

**Issue by StefanKern** [microsoft/TypeScript#31889]
> Question asked on Stackoverflow (https://stackoverflow.com/questions/56546116/typescript-convert-htmlelement-to-node/56546557?noredirect=1#comment99675409_56546557 ), full credit to `Cristian Traìna` answer.

Inside the `lib.dom.d.ts` (the type definition library used by Angular), the MutationObserver object is not much correctly defined:
```
interface MutationObserver {
    disconnect(): void;
    observe(target: Node, options: MutationObserverInit): void;
    takeRecords(): MutationRecord[];
}
```

According to the MDN documentation, a HTML element is also accepted (seen in the demo: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver´, `document.getElementById('some-id')` returns a `HTMLElement` ).

So a better definition would be 
```
    observe<T extends Node>(target: T, options: MutationObserverInit): void;
```

The current workaround is to cast the HTMLElement to node via 
```
observer.observe((<Node> <any> errorElement), { 
....
});
```

**Comment by nmain** [comment]
All `HTMLElement`s are `Node`s, so this just works.  No workaround is needed, and no error is issued.

https://www.typescriptlang.org/play/#src=declare%20var%20a%3A%20HTMLElement%3B%0D%0A%0D%0Avar%20o%20%3D%20new%20MutationObserver(()%20%3D%3E%20%7B%20%7D)%0D%0A%0D%0Ao.observe(a)%3B%20%2F%2F%20No%20typescript%20error%0D%0A%0D%0A

**Comment by StefanKern** [comment]
Maybe resolved with the latest version, had "typescript": "~3.1.6"
