### ISSUE TITLE
apply higher order type to each type within an union type

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#31899]
## Search Terms

pick, union, transitive, type alias

## Suggestion

Provide a way to define higher order type alias (such as `Pick<>`) which can apply the type transformation on each type with an union type, instead of combining them together into one type.

## Use Cases

Using `Pick<>` or `Omit<>` on Discriminated Union types cause the result type no longer a discriminated union.

## Examples

```ts
type Action = InvokeAction | ReturnAction

type InvokeAction = {
  type: 'invoke',
  id: string,
  payload: string[]
}

type ReturnAction = {
  type: 'return',
  id: string,
  payload: string
}

type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

let actions: Action[] =[]
function push(action: Omit<Action, 'id'>) {
  actions.push(action) // <-- error 'invoke' cannot assign to 'return'
}
```

The problem is ` Omit<Action, 'id'>` creates this type:
```ts
{
  type: 'invoke' | 'return',
  payload: string | string[]
}
```
instead of
```ts
{  type: 'invoke', payload: string[] } | { type: 'return', payload: string }
```

Using `Pick<>` has the same problem, but use `Omit<>` in the example for a cleaner use-case.
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
Duplicate of #28339

**Comment by unional** [comment]
Thanks, it is.

**Comment by unional** [comment]
However, this issue demonstrate that it could break discriminated unions.

@RyanCavanaugh  can you comment on this before I close it again? thx 🌷

**Comment by unional** [comment]
dup of #31501
