### ISSUE TITLE
"Cannot find module" when importing a folder in ES6

### ISSUE THREAD

**Issue by alexilyaev** [microsoft/TypeScript#31896]
Issue Type: <b>Bug</b>

### Description

When importing a folder in ES6 which has an `index.js` file, I get "Cannot find module", which also means that "Go To Definition" is not working.

Given the following files structure:

```
some-folder/index.js
app.js
```

```js
// some-folder/index.js
export const foo = 123;
```

```js
// app.js
// @ts-check
import { foo } from './some-folder'
```

I know it's not super clear if ES6 imports should support folder imports, but ATM Webpack does support it and I have seen it being used on different teams.  
I'd expect VS Code to support it as well, especially if `jsconfig.json` is present with ES6 target.

```json
// jsconfig.json
{
  "compilerOptions": {
      "target": "ES6"
  },
  "exclude": [
      "node_modules",
      "**/node_modules/*"
  ]
}
```

### Notes

In WebStorm it does search for `index.js` when importing a folder and Cmd + Click on the import string jumps to that `index.js` properly.

### System Info

VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:17:56.032Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Just add ` "module": "commonjs"` to your jsconfig. Non common-js module systems do not support resolving `folder` imports to `folder/index.js`. The default module system used is `ES6`

Leaving open to see if we can improve the error information for cases like this

**Comment by alexilyaev** [comment]
@mjbvz That actually worked.  
Also fixed importing a library that has no typing under `@types` but rather an `index.d.ts` file as part of the package (`mobx-react`).

I don't see the `module` option in the [jsconfig docs](https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options) though.

Again, I'd wish VS Code would go the extra step of trying to find the module in common alternative places (as WebStorm does).
