### ISSUE TITLE
Type guard complement for functions

### ISSUE THREAD

**Issue by Barbiero** [microsoft/TypeScript#31901]
## Search Terms

type guard complement is not

## Suggestion

Add the possibility for the complement of a type guard. For example:

    function NotNull<T>(obj: T): obj is T {
      return obj !== null && obj !== undefined;
    }

is a simple and very useful type guard, however sometimes the complement might be useful:

    function isNully<T>(obj: T): obj is not T { // or !(obj is T)
      return !NotNull(obj);
    }

## Use Cases

Sometimes I want to return early or short-circuit when an object _is_ nully(null/undefined), but writing `!NotNull(obj)` is harder to read. 

It _is possible_  to write what I want with the current TS, but it requires a hack somewhat:

    type Nully = null | undefined;
    export function isNully<T>(obj: T | Nully): obj is Nully {
      return obj === null || obj === undefined;
    }

This works perfectly fine, but it feels weird to create a separate type for this. Plus, when hovering over the isNully function, the return type shows "obj is Nully" which might make the programmer question what does "Nully" mean in this context(and we know how JS can treat stuff like 0 and empty arrays as null, so they have the right to question that)

instead, allowing us to write a type guard complement on type guards would solve that issue.

I believe other use case would be something like so:

    function isSerializable(obj: string | number | object): T is not object {
        return typeof obj === 'string' || typeof obj === "number"
    }

to test whether you'd need to pass a certain variable into a serializing function before printing. I'm sure other use cases might exist.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

edit>
It has come to my attention that union types do actually work with type guards. Edited them out

**Comment by nmain** [comment]
Can you do that much with these without bringing in https://github.com/microsoft/TypeScript/pull/29317?

**Comment by Barbiero** [comment]
I wasn't aware of #29317, I suppose that if/when it's implemented then this one would be done too.

closing as duplicate.
