### ISSUE TITLE
Do not allow to define a static `name` property on classes

### ISSUE THREAD

**Issue by lazutkin** [Microsoft/TypeScript#3190]
Currently it is possible to redefine a static `name` property for classes which leads to some _unclear_ results in runtime - it returns class name at runtime.

```javascript
class A {
	static name = 'Some name'
	
	static getName() {
		return this.name
	}
}


alert(A.getName()) // Shows `A` instead of `Some name`
```

 So I think that there are two problems. 

 1. A type-system couldn't find a `name` as apparent member derived from Function type and as it follows removing a line `static name = 'Some name'` leads to compilation error.
 2. I suggest that TS should notify when I try to redefine a `name` by issuing error or warning (if they are) because a good-looking code would works incorrectly in runtime.

**Comment by tinganho** [comment]
Look at #442. I think it is impossible for TS to implement a static name property on classes.

**Comment by lazutkin** [comment]
Thanks, didn't know. I will continue discussion in that issue.
