### ISSUE TITLE
type infer different between typescript 3.4.5 and 3.5.1

### ISSUE THREAD

**Issue by OuyangQianba** [microsoft/TypeScript#31900]
**TypeScript Version:**  3.5.1

**Search Terms:**

(It's hard to summarize it to a couple of terms.)

**Code**

```ts

export type Unshift<T extends any[], X> = ((
  x: X,
  ...t: T
) => void) extends (...t: infer R) => void
  ? R
  : never


type T1 = Unshift<[1,2],3>    // T1 is [3,1,2] in both versions
type T2 = Unshift<Unshift<[1,2],3>,4> // T2 is [4,3,1,2] in both typescript version

// just make [1,2] in T2 as a type parameter
type T3<T extends any[]> = Unshift<Unshift<T,3>,4> 

// T4 is [4,3,1,2] in typescript 3.4.5 ,but it's [4, ...(1|2|3)[]] in typescript 3.5.1
type T4 = T3<[1,2]> 

```

**Expected behavior:**

T4 is [4,3,1,2] 

**Actual behavior:**

T4 is [4,...(1|2|3)[]]

**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment]
Are you sure?  Check the `--strictFunctionTypes` compiler option.

**Comment by OuyangQianba** [comment]
Thanks, @jcalz.

Actually, I'm using ts-check in a javascript project which don't include tsconfig.json. When I added tsconfig.json and set strictFunctionTypes to true. Types are what I expected.

BTW, ts-check works fine without tsconfig.json for my project until I upgrade vscode to 1.35.
