### ISSUE TITLE
TypeScript 3.5.2 release missing from GitHub releases/tags

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#31903]
```
❯ npm info typescript version
3.5.2
```

![image](https://user-images.githubusercontent.com/921609/59514611-1e4b8000-8eb5-11e9-8816-f266c6b8c40a.png)

**Comment by lll000111** [comment]
And the "What's new in TypeScript v3.5.1." link in the 3.5.1 notes leads to 404.

**Comment by EatonZ** [comment]
..and _TypeScript_ is repeated twice in that screenshot.😁

**Comment by weswigham** [comment]
It was [in draft state](https://github.com/microsoft/TypeScript/releases/tag/v3.5.2) 😄

**Comment by lll000111** [comment]
@weswigham The link to the "release announcement" again points to 404. The link "What's new in TypeScript v3.5.2." points to 404. The "fixed issues query for Typescript v3.5.2." is empty. The list of commits ONLY HAS CODE - the commit messages are all completely useless! If someone on my team writes such commit messages I'll take them aside for a talk.
