### ISSUE TITLE
strictNullChecks failed with a variable as property name when accessing

### ISSUE THREAD

**Issue by Liu233w** [microsoft/TypeScript#31919]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

strictNullChecks, optional interface, property, variable, nullable

**Code**

```ts
interface A {
    [props: string]: B
}

type R = Record<string, B>

interface B {
    c?: number
}

function checkA(a: A): void {
    const s='1'
    if (a[s] && a[s].c) {
        a[s].c.toString()
    }
}

function checkWithLiteral(a: A): void {
    if (a['1'] && a['1'].c) {
        a['1'].c.toString()
    }
}

function checkB(b: B) {
    if (b.c) {
        b.c.toString()
    }
}

function checkR(r: R) {
    const s = '1'
    if (r[s] && r[s].c) {
        r[s].c.toString()
    }
}
```

with strictNullChecks on

**Expected behavior:**
Compiles without error.

**Actual behavior:**
`checkA` and `checkR` report error `Object is possibility undefined`, while `checkWithLiteral` does not.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%20%20%20%20%5Bprops%3A%20string%5D%3A%20B%0D%0A%7D%0D%0A%0D%0Atype%20R%20%3D%20Record%3Cstring%2C%20B%3E%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20%20%20c%3F%3A%20number%0D%0A%7D%0D%0A%0D%0Afunction%20checkA(a%3A%20A)%3A%20void%20%7B%0D%0A%20%20%20%20const%20s%3D'1'%0D%0A%20%20%20%20if%20(a%5Bs%5D%20%26%26%20a%5Bs%5D.c)%20%7B%0D%0A%20%20%20%20%20%20%20%20a%5Bs%5D.c.toString()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20checkWithLiteral(a%3A%20A)%3A%20void%20%7B%0D%0A%20%20%20%20if%20(a%5B'1'%5D%20%26%26%20a%5B'1'%5D.c)%20%7B%0D%0A%20%20%20%20%20%20%20%20a%5B'1'%5D.c.toString()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20checkB(b%3A%20B)%20%7B%0D%0A%20%20%20%20if%20(b.c)%20%7B%0D%0A%20%20%20%20%20%20%20%20b.c.toString()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20checkR(r%3A%20R)%20%7B%0D%0A%20%20%20%20const%20s%20%3D%20'1'%0D%0A%20%20%20%20if%20(r%5Bs%5D%20%26%26%20r%5Bs%5D.c)%20%7B%0D%0A%20%20%20%20%20%20%20%20r%5Bs%5D.c.toString()%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #10530

**Comment by Liu233w** [comment]
Hi @RyanCavanaugh , I have just read the issue #10530 and its related issues, and it seems that they are all about literals in bracket notation. But literals work well in this situation, while variables (and constants) do not. So it is probably not a duplicate of #10530 .

**Comment by RyanCavanaugh** [comment]
@Liu233w that's the issue we're using to track non-literal access

**Comment by Liu233w** [comment]
ok then
