### ISSUE TITLE
Intellisense battles Jasmine unit testing suite it() function

### ISSUE THREAD

**Issue by JustinReinhart** [microsoft/TypeScript#31913]
Issue Type: <b>Bug</b>

When I attempt to type the function it() to perform unit testing with the popular Jasmine javascript unit testing suite, the intellisense keeps fighting me and wanting me to write "instanceof".  Ideally it should realize that the it function has been established in Jasmine.js and help me type it out rather than fight me.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3502)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.97GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
If you want proper intellisense for jasmine in a javascript file, you need to let VS Code know that you are using jasmine in some way. To do this, I believe you can:

* Install jasmine through npm: `npm install --save-dev jasmine`
* Install the jasmine typings: `npm install --save @types/jasmine`
* Create a [jsconfig.json](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) with a `typeAcquisition` section:
    ```
    {
        "compilerOptions": {
            "target": "es6"
        },
        "typeAcquisition": {
            "include": [
                "jasmine"
            ]
        },
        "exclude": [
            "node_modules",
            "**/node_modules/*"
        ]
    }
    ```

**Comment by RyanCavanaugh** [comment]
@mjbvz what is the TypeScript bug here?

**Comment by mjbvz** [comment]
I think it was a TS related question. Closing since we have not heard anything back in the past week
