### ISSUE TITLE
declare class within function?

### ISSUE THREAD

**Issue by cmichaelgraham** [Microsoft/TypeScript#3191]
i'm trying to port [Aurelia dependency-injection unit tests](https://github.com/aurelia/dependency-injection/blob/master/test/container.spec.js) to TypeScript 1.5 Beta.

I'm getting an error with the class declarations that are embedded within the unit test `it` functions:
![ts unit tests](https://cloud.githubusercontent.com/assets/10272832/7670157/0915e0a8-fc57-11e4-9bb8-3eaf184cae79.png)

is this expected?  is there a plan to support this?

here's a code snippet:

```javascript
import {Container, inject, transient, singleton, Lazy, All, Optional, Parent} from 'aurelia-dependency-injection';
import {Decorators, Metadata} from 'aurelia-metadata';

export var run = () => {
describe('container', () => {
    describe('injection', () => {
        it('instantiates class without injected services', function () {
            class App { }

            var container = new Container();
            var app = container.get(App);

            expect(app).toEqual(jasmine.any(App));
        });

        it('uses static inject method (ES6)', function () {
            class Logger { }

            class App {
                static inject() { return [Logger]; };
                constructor(logger) {
                    this.logger = logger;
                }
            }

            var container = new Container();
            var app = container.get(App);

            expect(app.logger).toEqual(jasmine.any(Logger));
        });
```

**Comment by kitsonk** [comment]
I believe at the moment, you cannot declare classes in TypeScript within another closure (within a function) and can only declare them in the root enclosure of the module.

**Comment by cmichaelgraham** [comment]
ok :+1:

**Comment by DanielRosenwasser** [comment]
Correct; local classes/class expressions are slated for 1.6. See [our roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap#16)
