### ISSUE TITLE
Can't install insiders

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#31929]
Can't install https://github.com/microsoft/TypeScript/pull/31277#issuecomment-502438862 and https://github.com/microsoft/TypeScript/pull/31880#issuecomment-501446922. I could install https://github.com/microsoft/TypeScript/pull/31880#issuecomment-501446922 with Win10 but can't now. I tried with the following environments:

Win10 Pro; Node 12.4.0; npm 6.9.0
Ubuntu 18.04; Node 10.8.0; npm 6.4.1

cc @weswigham 

**Expected behavior:**

**Actual behavior:**
```
$ npm i https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/33400/artifacts?artifactName=tgz&fileId=B10B0A88C3D1C8DCA0C6AA5DDED4DD385013554114808F4B3A5FBB56317A12D102&fileName=/typescript-3.6.0-in
siders.20190616.tgz
[1] 2310
[2] 2311
[2]+  Done                    fileId=B10B0A88C3D1C8DCA0C6AA5DDED4DD385013554114808F4B3A5FBB56317A12D102

npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/33400/artifacts?artifactName=tgz.
npm ERR! package.json npm can't find a package.json file in your current directory.
```
**Playground Link:** 

**Related Issues:**

**Comment by falsandtru** [comment]
I can install it only via package.json.

**Comment by weswigham** [comment]
Yeah, the URL contains special characters which have meanings in most shells :V
