### ISSUE TITLE
confusing error when not exporting types

### ISSUE THREAD

**Issue by robertIsaac** [microsoft/TypeScript#31927]
**TypeScript Version:**  3.6.0-dev.20190615

**Search Terms:** not exported types, dynamic types

**Code**
https://github.com/robertIsaac/tsc-dynamic-type-issue

auth-response.ts
```ts
type AuthResponse = SuccessResponse | FailResponse;

interface SuccessResponse {
    success: true;
    token: string;
}

interface FailResponse {
    success: true;
    message: string;
}
```

insert-response.ts
```ts
type InsertResponse = SuccessResponse | FailResponse;

interface SuccessResponse {
    success: true;
    insertedId: string;
}

interface FailResponse {
    success: true;
    message: string;
}
```

user-api.ts
```ts
class UserApi {
    insertUser(username: string, password: string): InsertResponse {
        return {
            success: true,
            insertedId: 'id'
        };
    }

    login(username: string, password: string): AuthResponse {
        return {
            success: true,
            token: 'asd'
        };
    }
}
```

**Expected behavior:**
it success and compile

or

it throw 

```
user-api.ts:2:53 - error TS2304: Cannot find name 'InsertResponse'.

2     insertUser(username: string, password: string): InsertResponse {
                                                      ~~~~~~~~~~~~~~

user-api.ts:9:48 - error TS2304: Cannot find name 'AuthResponse'.

9     login(username: string, password: string): AuthResponse {
                                                 ~~~~~~~~~~~~


Found 2 errors.
```

**Actual behavior:**

```
user-api.ts:3:9 - error TS2322: Type '{ success: true; insertedId: string; }' is not assignable to type 'InsertResponse'.
  Property 'token' is missing in type '{ success: true; insertedId: string; }' but required in type 'SuccessResponse'.

3         return {
          ~~~~~~~~
4             success: true,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~
5             insertedId: 'id'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6         };
  ~~~~~~~~~~

  auth-response.ts:5:5
    5     token: string;
          ~~~~~
    'token' is declared here.

user-api.ts:10:9 - error TS2322: Type '{ success: true; token: string; }' is not assignable to type 'InsertResponse'.
  Property 'insertedId' is missing in type '{ success: true; token: string; }' but required in type 'SuccessResponse'.

10         return {
           ~~~~~~~~
11             success: true,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~
12             token: 'asd'
   ~~~~~~~~~~~~~~~~~~~~~~~~
13         };
   ~~~~~~~~~~

  insert-response.ts:5:5
    5     insertedId: string;
          ~~~~~~~~~~
    'insertedId' is declared here.


Found 2 errors.
```
**Playground Link:** can't be done as it depend on multi-files

**Related Issues:** didn't find any

**notes**
exporting the types and importing them into the used files (user-api.ts in this case) does solve the issue as in this PR
https://github.com/robertIsaac/tsc-dynamic-type-issue/pull/1/files

i don't really understand how it doesn't throw the `Cannot find name 'InsertResponse'.` error but i think the tsc engine trying to figure it out on itself but when it encounter two SuccessResponse it can't figure which one to use

**Comment by nattthebear** [comment]
This is working correctly.

When the same exact interface is declared twice, the declarations are merged: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

The two declarations of `SuccessResponse` are considered the same interface because they're both at the global level.  When a file has no imports or exports, it's not treated as a module, and instead everything it does happens in the global scope: https://www.typescriptlang.org/docs/handbook/modules.html#introduction

Your code ends up creating the following declaration in the global scope:

```ts
interface SuccessResponse {
    success: true;
    token: string;
    insertedId: string;
}
```

Which the functions do not satisfy.  Exporting fixes it because once you have at least one `import` or `export` in a file it's now a module and the declarations are separate.

**Comment by robertIsaac** [comment]
thanks a lot @nattthebear i understand now
can you please share a reference to understand deeply the TS global scope
