### ISSUE TITLE
[bug] statements not allowed in front of super() call

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#31925]
**TypeScript Version:**  3.5.2

**Search Terms:**

**Code**

```ts
            constructor(options = {}) {
                console.log('hello')
                super(options)
            }
```

**Expected behavior:**

It should work. It's valid JavaScript.

Run the following in Chrome console (or one that support class fields):

```js
class A {
	foo = 'foo'
	constructor() {
		this.foo = 'bar'
	}
}

class B extends A {
	bar = 'bar'
	constructor() {
		console.log('hello')
		super()
		this.bar = 'foo'
	}
}

new B()
```

**Actual behavior:**

It complains:

> A 'super' call must be the first statement in the constructor when a class contains initialized properties or has parameter properties.

**Playground Link:** 

[playground link](http://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%09foo%20%3D%20'foo'%0D%0A%09constructor()%20%7B%0D%0A%09%09this.foo%20%3D%20'bar'%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%09bar%20%3D%20'bar'%0D%0A%09constructor()%20%7B%0D%0A%09%09console.log('hello')%0D%0A%09%09super()%0D%0A%09%09this.bar%20%3D%20'foo'%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Anew%20B()%0D%0A)

**Related Issues:**

**Comment by Epskampie** [comment]
Duplicates: #945 #8277 etc etc. Please search before posting!

**Comment by trusktr** [comment]
Ah, ok. Thanks. 🙏  Sorry!
