### ISSUE TITLE
Typescript includes installation directory typings (in AppData)

### ISSUE THREAD

**Issue by rsxdalv** [microsoft/TypeScript#31921]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Local module 'alt' uses local declaration file
Correction: importing 'alt' **never** resolves to TypeScript installation

**Actual behavior:**
Importing alt resolves to `C:\Users\username\AppData\Local\Microsoft\TypeScript\3.5\node_modules\@types\alt\index.d.ts`

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
We would need a complete repro to try to investigate this.

**Comment by pushkin-** [comment]
@RyanCavanaugh  I believe I started seeing this when I installed VS 2019. And now, `"C:\Users\username\AppData\Local\Microsoft\TypeScript\3.5\node_modules\@types\jasmine\ts3.1\index.d.ts"` is conflicting with VSCode's (or the node module in my project anyway) `.\node_modules\@types\jasmine\ts3.1\index.d.ts`.

Is it safe to delete the AppData Typescript folder?

**Comment by rsxdalv** [comment]
Reproduction: 
```js
import alt from 'alt';
```
in a file named `test.js`
![image](https://user-images.githubusercontent.com/6757283/60417322-c74de680-9be8-11e9-97e4-45058334c9e3.png)

**Comment by rsxdalv** [comment]
For the reference this goes into typescript, not just vscode - no error logged (or in my use case, I'd see false errors due to the wrong package):
![image](https://user-images.githubusercontent.com/6757283/60417498-42af9800-9be9-11e9-885c-76501f3b7bbb.png)

**Comment by rsxdalv** [comment]
I would like for this issue to be reopened, since I provided a clear reproduction.

**Comment by RyanCavanaugh** [comment]
@rsxdalv What exactly is wrong here?

**Comment by RyanCavanaugh** [comment]
@rsxdalv turn on the option `"typescript.disableAutomaticTypeAcquisition"` to disable automatically getting types from `@types`
