### ISSUE TITLE
Incrementing a property behind a private set/get accessor causes build to fail

### ISSUE THREAD

**Issue by paulheising** [microsoft/TypeScript#31934]
**TypeScript Version:**  ^3.6.0-dev.20190615

get set accessor increment build fail

**Code**

Repo, which can reproduce the issue:

https://gitlab.com/paul.heising/ts-problem-test

```ts
export class MyTest {
  private _foo = 0;

  private get foo() {
    return this._foo;
  }

  private set foo(value: number) {
    this._foo = value;
    // Do something special with foo...
  }

  public someFunction() {
    // This fails, because the get-accessor above is presumed to be unused:
    this.foo += 10;

    // But it's the same as this, which works:
    // this.foo = this.foo + 10;
  }
}
```

**Expected behavior:**

The code above should compile.

**Actual behavior:**

Typescript does not recognize that the `+=` operator implies *reading* the property before *writing* the new value. So, compile fails with: `index.ts:4:15 - error TS6133: 'foo' is declared but its value is never read.`

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Increments "don't count" for the purposes of identifying read locations, because a variable that is only ever incremented is still effectively unused.
