### ISSUE TITLE
Incorrect assumption inside `or` condition if using `type | undefined` and `strictNullChecks`

### ISSUE THREAD

**Issue by BrunnerLivio** [microsoft/TypeScript#31937]
**TypeScript Version:**  3.6.0-dev.20190615

**Search Terms:** or condition, undefined type, strictNullChecks 

**Code**

```ts
function aOrB(a: boolean | undefined, b: boolean | undefined) {
  let c: boolean;
  if (a || b) {
    c = a || b; // Type 'undefined' is not assignable to type 'boolean'.ts(2322)
  }
}
```

**Expected behavior:**
`c` should be assignable to `a || b` if the condition has already been checked in `if (a || b)`

**Actual behavior:**
Because of the if condition at line 3 `if (a || b)`, the code would not run the block in case either `a` or `b` is undefined. TypeScript still assumes that `a` or `b` could be undefined. Due to the second condition at line 4 `c = a || b;` either `a` or `b` **must** be defined, but TypeScript still throws an error if `strictNullChecks` is allowed:

```
index.ts:4:5 - error TS2322: Type 'boolean | undefined' is not assignable to type 'boolean'.
  Type 'undefined' is not assignable to type 'boolean'.

4     c = a || b; // Type 'undefined' is not assignable to type 'boolean'.ts(2322)
      ~
```

**Playground Link:** https://www.typescriptlang.org/play/#src=function%20aOrB(a%3A%20boolean%20%7C%20undefined%2C%20b%3A%20boolean%20%7C%20undefined)%20%7B%0D%0A%20%20let%20c%3A%20boolean%3B%0D%0A%20%20if%20(a%20%7C%7C%20b)%20%7B%0D%0A%20%20%20%20c%20%3D%20a%20%7C%7C%20b%3B%20%2F%2F%20Type%20'undefined'%20is%20not%20assignable%20to%20type%20'boolean'.ts(2322)%0D%0A%20%20%7D%0D%0A%7D%0D%0A

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/31603 (which this appears to be a duplicate of).

Long story short: `if (a || b)` doesn't prove anything individually about `a` or `b` so neither one is narrowed.  Narrowing is only done on a per-variable basis: the compiler isn't able to internally track e.g. "at least one of these is truthy".

**Comment by BrunnerLivio** [comment]
Oh oversaw that one, this issue is indeed a duplicate. Thanks a lot for the info @fatcerberus
