### ISSUE TITLE
Add a fixit for adding "jsx: true" to the tsconfig

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript#31938]
## Search Terms

fixit quick fix jsx flag tsconfig

## Suggestion

Hitting "Quick Fix" in this error could offer to add the flag for you
![{8446CBC8-3BA3-4F37-89F9-BD81DAEE9B26} png](https://user-images.githubusercontent.com/49038/59621991-48838480-90e5-11e9-80b5-fef5c5b62373.jpg)

## Use Cases

Anyone starting a reactproject

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by hoangpham95** [comment]
I would love to take this if possible.
