### ISSUE TITLE
Export default on interface not allowed

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#3194]
Raised on SO. The following is an error:

```ts
export default interface Foo {
}
```
By design or bug?

**Comment by ahejlsberg** [comment]
It's by design. You can accomplish the exact same effect with
```typescript
interface Foo {
    // stuff
}
export default Foo;
```
More discussion in #3095.

**Comment by clavecoder** [comment]
I'm OK with leaving it as is if the reasoning is that interfaces, et al, are not vaid **EcmaScript** and #3917 is implemented.

**Comment by cdaringe** [comment]
hi all,

i unexpectedly encountered this too.

@ahejlsberg, can you clarify on your remarks further?  the discussion in #3095 seems to be focusing more on the declaration collisions, which is all said and good.

@clavecoder, i don't fully see the rationale you point to. `Interface`s aren't valid ecmascript either, so why shed convention?

these remarks are (of course) stated in a cordial tone.  however, this decision feels very counterintuitive to me

**Comment by mhegazy** [comment]
Allowing `export default` + [`interface` / `abstract class` / `enum` / `namespace` / `type` ] is tracked by https://github.com/Microsoft/TypeScript/issues/3792

**Comment by cdaringe** [comment]
oh i see!  thanks.  i'll follow on over there.
