### ISSUE TITLE
Support IntelliSense for variables when requiring node modules

### ISSUE THREAD

**Issue by phobos101** [microsoft/TypeScript#31941]
Given a `require` statement in Node, I'd like to be able to provide a variable name and have IntelliSense provide me hints as if I required the module literally.

Assume a project with the following files:
```
lib/add.js
index.js
```

In `index.js` I declare the location of my `lib` directory like so:
`global.lib_root = path.join(__dirname, 'lib/')`

Then no matter where I am in my project, I can easily require files from my `lib` directory by writing `const add = require(lib_root + 'add')`

At this point in my file, I'd like to be able to have IntelliSense be fully aware of the JSDoc annotations that are on the exported function available as if I had written out the full path in the require statement.

**Comment by mjbvz** [comment]
We don't support intellisense for imports with dynamic paths (anything that is not `require('string')`)

I suggest you look into an alternative approach, but this will require changing your code. You should be able to configure a [`jsconfig`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) to handle most styles of imports

**Comment by phobos101** [comment]
Hi Matt,

Thanks for your reply! Would you say this is not suitable as a feature request? I'll take a look at using `jsconfig` as this style of dynamic module requires are common in our monolith!

**Comment by mjbvz** [comment]
Yes, take a look at the jsconfig; dynamic paths should generally not be required.

You cannot reliably resolve an expression based import without executing the code, so that feature is out of scope

**Comment by ttodua** [comment]
> You cannot reliably resolve an expression based import without executing the code
How is that true? 
```
const myDir = "./my_dir/"
var module1= require(myDir + "module1");
var module2= require(myDir + "module2");
```

how someone could say that code-execution is needed here?  I don't say directly dynamic variables, but `const`-ants should be supported at least. Strange hearing that this is not "even in scope of feature", not only the most suitable and even "must-to-be already implemented" feature.

**Comment by mjbvz** [comment]
@ttodua If you have feedback on old closed issues, open a new issues:

As for this issue, consider: 

```ts
const module = require(new Date()).getFullYear() + '/dir/file' )
```

Tooling can only reliably figure out contrived cases like your example, but contrived cases aren't the cases that would help real world users. Also based on the lack of feedback on this issue, not many people run into this limitation in the first place
