### ISSUE TITLE
type infer are different in d.ts and js file.

### ISSUE THREAD

**Issue by OuyangQianba** [microsoft/TypeScript#31951]
Hi,

I'm using ts-check in an old javascript project. I met a problem that type infer are different in d.ts and js file. I made a demo from this  as follow:

```typescript
// test.d.ts
export type Unshift<T extends any[], X> = ((
  x: X,
  ...t: T
) => void) extends (...t: infer R) => void
  ? R
  : never

export type Fn<Args extends any[],X,Y> = (...args: 
  Unshift<
  Unshift<Args,X>,Y>)=>void

// F1 is ( a:number,b:number,c: string) => void
export type F1 = Fn<[string],number,number> 
```

```javascript
// test.js
// @ts-check

/** @type {import ('./test').F1} */
const f1 = (a,b,c)=>{
 // a is number 
//  b is number | string , I think it should be number
//  c is number | string too, I think it should be string
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "strictFunctionTypes": true
  }
}
```

Is there any one can help on this ?

Thanks.

**Comment by rusev** [comment]
What I see as inferred type for `F1` is that only the first argument is of type `number`. The rest of the arguments are union type `string|number`. See the picture bellow:

![TS](https://user-images.githubusercontent.com/961035/59844353-6100d280-9363-11e9-9959-385b9fe9a22c.png)

VSCode: 1.35.1
tsc: 3.5.1

**Comment by sandersn** [comment]
I can't repro this on the latest Typescript. @OuyangQianba can you try with typescript@next?
