### ISSUE TITLE
Remove 'prerender' value from VisibilityState

### ISSUE THREAD

**Issue by kripod** [microsoft/TypeScript#31957]
## Search Terms

prerender, visibility

## Suggestion

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState), the value `'prerender'` has been deprecated and cannot be found in the [current version](https://www.w3.org/TR/page-visibility-2/) of the official Page Visibility API specification.

As mentioned in the document's introduction, "Without knowing the visibility state of a page, web developers have been designing web pages as if they are always `visible`". I would propose adhering to the standard and using the `'visible'` value by default.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code

Technically this is a breaking change for everyone who makes use of that value already.

Related: #390
