### ISSUE TITLE
Identifiers with Astral Unicode characters are unsupported

### ISSUE THREAD

**Issue by Alhadis** [microsoft/TypeScript#31963]
### TypeScript Version
3.5.1

### Search Terms
`utf8`, `unicode`

### Code
~~~js
const 𝑚 = 4;
const 𝑀 = 5;
console.log(𝑀 + 𝑚); // 9
~~~

### Expected behaviour
The above is legal JavaScript, so `9` should be printed to the console.

### Actual behaviour
The TypeScript compiler goes completely apeshit:

<details>
	<summary><b>(click to see warnings)</b></summary>

	test.ts:1:7 - error TS1127: Invalid character.

	1 const 𝑚 = 4;
	        

	test.ts:1:8 - error TS1127: Invalid character.

	1 const 𝑚 = 4;
	         

	test.ts:1:10 - error TS1134: Variable declaration expected.

	1 const 𝑚 = 4;
	           ~

	test.ts:1:12 - error TS1134: Variable declaration expected.

	1 const 𝑚 = 4;
	             ~

	test.ts:2:7 - error TS1127: Invalid character.

	2 const 𝑀 = 5;
	        

	test.ts:2:8 - error TS1127: Invalid character.

	2 const 𝑀 = 5;
	         

	test.ts:2:10 - error TS1134: Variable declaration expected.

	2 const 𝑀 = 5;
	           ~

	test.ts:2:12 - error TS1134: Variable declaration expected.

	2 const 𝑀 = 5;
	             ~

	test.ts:3:13 - error TS1127: Invalid character.

	3 console.log(𝑀 + 𝑚); // 9
	              

	test.ts:3:14 - error TS1127: Invalid character.

	3 console.log(𝑀 + 𝑚); // 9
	               

	test.ts:3:18 - error TS1127: Invalid character.

	3 console.log(𝑀 + 𝑚); // 9
	                   

	test.ts:3:19 - error TS1127: Invalid character.

	3 console.log(𝑀 + 𝑚); // 9
</details>

... and generates obviously unusable JavaScript:

~~~js
var ;
4;
var ;
5;
console.log(+); // 9
~~~

### More info
* ECMA-262, [§ 11.6 _Names and Keywords_](https://www.ecma-international.org/ecma-262/6.0/#sec-names-and-keywords).

**Comment by RyanCavanaugh** [comment]
Title is underspecific;  𝑚 is a surrogate pair which is why we don't recognize it. The broad class of other non-ASCII Unicode characters are correctly parsed.

**Comment by Alhadis** [comment]
> 𝑚 is a surrogate pair

Uhm, [no it isn't](https://graphemica.com/%F0%9D%91%9A).

If it was a *surrogate* character, then it wouldn't be valid UTF-8, let alone valid as a JavaScript identifier.

**Comment by Alhadis** [comment]
I've amended the title with what I think you meant.

**Comment by weswigham** [comment]
Our scanner is still only following the [5.1 spec](https://www.ecma-international.org/ecma-262/5.1/#sec-7.6) which lists explicitly accepted unicode groups for identifiers - the 6.0 spec allows `any Unicode code point with the Unicode property “ID_Start” or “Other_ID_Start”` as an `IdentifierStart` and `any Unicode code point with the Unicode property “ID_Continue”, “Other_ID_Continue”, or “Other_ID_Start” as an `IdentifierPart`.

cc @rbuckton  - we have to have looked at this before, right? I mean, it'd be nice if we could just use `/\p{ID_Start}/u`, `/\p{Other_ID_Start}/u, `/\p{ID_Continue}/u`, and `/\p{Other_ID_Continue}/u`, but that'd be host-dependent.

**Comment by weswigham** [comment]
Oh, our scanner also iterated by char code and not by code point, so every time we call `isIdentifierPart` we do so with only part of an astral plane character rather than the whole thing, in addition to the list of accepted charactersets being out of date.

**Comment by Alhadis** [comment]
> Oh, our scanner also iterated by char code and not by code point

Yup, and there's the culprit. 👍

Seems like a pretty easy fix if it's just swapping `string.charCodeAt` for `string.codePointAt`.

**Comment by weswigham** [comment]
> Seems like a pretty easy fix if it's just swapping string.charCodeAt for string.codePointAt.

Not quite - iterating by string index is by char code, so you need to handle the second "char code" of a multi-code code point - and to top it off, using exclusively the builtin `codePointAt` would cause us to break on es5 or below runtimes, so we need to polyfill it. In any case, #32096 should do juuuust enough to support parsing this all correctly.

**Comment by Alhadis** [comment]
Ah right, I forgot about supporting legacy environments. Makes sense, then.

Thanks for the fast PR!

**Comment by weswigham** [comment]
Ehhhh, it's just a first draft - it'll probably take us a bit to figure out how we want to take it.

**Comment by fatcerberus** [comment]
> Uhm, no it isn't.

To be fair, he did say surrogate *pair* - i.e. it would have to be encoded as two codepoints in UTF-16.  It's true that astral characters can't legally be encoded as surrogate pairs in UTF-8, though (that's what CESU-8 is for).

"Astral" is the correct term, of course, since "surrogate pair" describes a particular encoding scheme, not something inherent to the character itself.  But it is relevant here, as astral characters are represented in JS strings *per spec* as surrogate pairs--that's why we needed `fromCodePoint`.

**Comment by Alhadis** [comment]
I'm well aware of how surrogate pairs and Unicode transform formats work, thank you. But that's more-or-less unrelated to the issue I was reporting: it doesn't matter how a character is encoded bytewise, only that the grapheme itself is considered valid in an ECMAScript identifier (as dictated by Unicode).

So, yes, while `𝑚` may be a surrogate pair in the most *literal* sense, it's theoretically a single character (`U+1D45A`), not two (`U+F09D`. `U+919A`).

Let's not carry this discussion into the murky cesspool of what defines a "character" with relation to computer encoding schemes, please. :)

**Comment by fatcerberus** [comment]
Right, I was just pointing out the relevance of the surrogate pair comment, because that's how JS engines encode it (i.e. `"𝑚".length === 2`), which is thus also how the TS compiler sees it, which is (I think) what @RyanCavanaugh's point was in bringing it up.  It was kind of a "this is why the bug manifests", which is indeed useful information. :smiley:

> Let's not carry this discussion into the murky cesspool of what defines a "character" with relation to computer encoding schemes, please. :)

Yeah, I agree, that wasn't my intent.

**Comment by AnyhowStep** [comment]
Would this work?
![image](https://user-images.githubusercontent.com/5655961/63286324-bedb6900-c285-11e9-8c02-46800c3d2c88.png)

**Comment by weswigham** [comment]
Yeah, disappointing, right? Gotta petition tc39 to specifically add emoji ideographs to the `IdentifierPart` and `IdentifierStart` productions.

**Comment by StoneCypher** [comment]
> "Astral" is the correct term, of course

For the record, "astral planes" is slang that comes from a Dungeons and Dragons joke, and does not actually occur in [the Unicode specification](https://www.unicode.org/versions/Unicode14.0.0/UnicodeStandard-14.0.pdf)

They're properly called the "supplementary planes," and people of culture call them "the phlogiston"
