### ISSUE TITLE
Breaking change between 3.3 and 3.5 for object assignment

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/TypeScript#31968]
**TypeScript Version:**  3.5.2

**Search Terms:** never

I have a code snippet that typechecks in `3.3` but does not typecheck in `3.5`: [TS playground](https://typescript-play.js.org/#code/KYDwDg9gTgLgBDAnmYcDyYYEsIDsDOcAvHAN4BQcVcAFhPjLgIYC2wAXHA1FrgOYBuStQCu+YAHVgAIzCdpECABtgTXEIC+Q8gGM8DdAAUAKgEk0AOQDKAfQDCAQTsAJAKKcM2fcTLCqdBmY2TgByAMZWYBCAGj84MUkZOQQoEWByLXJyUEhYOAAzEVwdL1wuYBhPHAIAClxgAHcq-Q9MavwASl9qOBV4AGtgRE5BxAh89Db9bR786Dga0bheOHqmqYIuih6etBNza3snNwBtUYBdHzXmgjOh86EejQygA). It seems like it should be valid.

**Comment by jack-williams** [comment]
Changed by #30769. See the PR for rationale / discussion / related issues.

**Comment by NickHeiner** [comment]
Thanks! That's all the help I need on this issue for now.
