### ISSUE TITLE
`partial class` rationale

### ISSUE THREAD

**Issue by langpavel** [microsoft/TypeScript#31965]
## Search Terms

- partial class c# [google](https://www.google.com/search?q=partial+class+c%23)
- #563, #14913
- [When is it appropriate to use C# partial classes? (stack**overflow**)](https://stackoverflow.com/questions/3601901) — *"The biggest use of partial classes is to make life easier for code generators / designers"*

## Suggestion

- TS already have `namespace`. Why it cannot have `partial` class only valid in `namespace` and in same module (like *internal*)?
- Partial classes may be distinct from C# implementation.
  One partial class may *require declaration/implementation* from another, otherwise compilation should fail.

## Use Cases

- Code generation tools: ATM there is no way to extend TypeScript compiler with custom resolvers, build hooks or anything.
- Without this feature most of preconditions cannot be checked at build time and everything must be checked at boot or even worse at runtime.

## Examples

- There are nice examples in the wild, VS and C# can be one well known.
- My specific use case will be to *rendering* GraphQL schema into *partial classes*, you will only implement resolvers. All checked :heavy_check_mark:
(Yes. Current approaches are really bad on server.)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
You found #563 already, which has plenty of information

**Comment by langpavel** [comment]
Ok. I'm reading this as *Typescript will never have partial classes*

**Comment by RyanCavanaugh** [comment]
That's correct
