### ISSUE TITLE
New Website Logo: WebRx 

### ISSUE THREAD

**Issue by oliverw** [Microsoft/TypeScript#3196]
Name: WebRx
Homepage: http://webrxjs.org/
Brand Guidelines/Licensing: MIT License
Logo: http://webrxjs.org/images/Logo@512.png

Description:

WebRx is a browser-based MVVM-Framework that combines functional-reactive programming with declarative Data-Binding, Templating and Client-Side Routing.

The framework is written in Typescript and built on top of ReactiveX for Javascript (RxJs) which is a powerful set of libraries for processing and querying asynchronous data-streams that can originate from diverse sources such as Http-Requests, Input-Events, Timers and much more.

**Comment by jonathandturner** [comment]
Added.
