### ISSUE TITLE
What does "Awaiting More Feedback" mean?

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#31973]
[Several](https://github.com/microsoft/TypeScript/issues/31514) of my [issues](https://github.com/microsoft/TypeScript/issues/31514) were recently tagged "Awaiting More Feedback". It's unclear to me what this means. Is the issue waiting on action from me? What sort of feedback is it referring to? And from whom?

According to the [labels page](https://github.com/Microsoft/TypeScript/labels) it is quite common (428 issues), but undocumented. Please fill in that middle column with an explanation of what this label means!

![image](https://user-images.githubusercontent.com/98301/59724434-d51e6780-91f7-11e9-8fed-aa0b5c09c6b4.png)

**Comment by jack-williams** [comment]
[Comment](https://github.com/microsoft/TypeScript/issues/15266#issuecomment-333703020)

**Comment by danvk** [comment]
Thanks @jack-williams 

> This means we'd like to hear from more people who would be helped by this feature, understand their use cases, and possibly contrast with other proposals that might solve the problem in a simpler way (or solve many other problems at once).
>
> If this feature looks like a good fit for you, please use the 👍 reaction on the original post. Comments outlining different scenarios that would be benefited from the feature are also welcomed.

@RyanCavanaugh since you wrote that, you have the required permissions and this has come up multiple times, could you copy that description to the [labels page][1]? Thanks.

[1]: https://github.com/Microsoft/TypeScript/labels

**Comment by orta** [comment]
Added, thanks folks 👍

**Comment by danvk** [comment]
Thanks @orta!
