### ISSUE TITLE
Re-export issue with hasOwnProperty.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#3197]
It would be an issue if there is a method exported from the current module named `hasOwnProperty`:

```javascript
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
```

Personally I would write it as:

```javascript
function __export(m) {
    var hasOwnProperty = Object.prototype.hasOwnProperty;
    for (var p in m) if (!hasOwnProperty.call(exports, p)) exports[p] = m[p];
}
```

**Comment by RyanCavanaugh** [comment]
If anyone actually creates a property called `hasOwnProperty`, I have to assume they understand the implications and have implemented it in some reasonable way.
