### ISSUE TITLE
VS 2013 hangs when building in parallel process TS files

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/TypeScript#3198]
### Context
I have solution with multiple CsProj files. Each project has multiple TypeScript files that are generated to single JS and .d.ts.
No "Core" projects reference "Core.d.ts". The build is triggered from command line in same time, when solution is opened in Visual Studio.

### Result
From time to time VS hangs with "Visual Studio is Busy" from tray icon message.

### Observations
This is frequently reproducible. It seems to be related to the fact, that VS/TS detects that "Core.d.ts" has been removed (as part of gulp build step)
and recreated. In VS I can observe lot of errors appear and after some time disapear.

When attached in debugger I can see:

1. "!mwaits" shows that thread 18 has [SyncBlock] LockType. and callstack:
```
0:018> !clrstack
OS Thread Id: 0x56d4 (18)
Child SP       IP Call Site
12a3f0ac 775f013d [GCFrame: 12a3f0ac] 
12a3f184 775f013d [GCFrame: 12a3f184] 
12a3f1a0 775f013d [HelperMethodFrame_1OBJ: 12a3f1a0] System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
12a3f21c 504b2620 Microsoft.VisualStudio.Services.FileChangeService.AdviseFileChange(System.String, Microsoft.VisualStudio.Shell.Interop._VSFILECHANGEFLAGS, Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents)
12a3f258 504c459a Microsoft.VisualStudio.Services.FileChangeService+<>c__DisplayClass5.<Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEx.AdviseFileChange>b__2()
12a3f264 7790627b Microsoft.VisualStudio.ErrorHandler+<>c__DisplayClass1.<CallWithCOMConvention>b__0()
12a3f268 77900044 Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func`1<Int32>, Boolean, Boolean)
12a3f29c 77906265 Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Action, Boolean)
12a3f2b0 504b239b Microsoft.VisualStudio.Services.FileChangeService.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEx.AdviseFileChange(System.String, UInt32, Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents, UInt32 ByRef)
12a3f2ec 1c66a5a4 TypeScriptLanguageService.ScriptContext.FileChangeNotificationService.StartListening(System.String, System.EventHandler)
12a3f328 1c66a116 TypeScriptLanguageService.ScriptContext.DefaultClosedFilesProvider.GetEntry(System.String)
12a3f388 1a898612 TypeScriptLanguageService.ScriptContext.DefaultClosedFilesProvider.GetEncoding(System.String)
12a3f39c 1a8984af TypeScriptLanguageService.ScriptContext.Script.get_CurrentSnapshot()
12a3f3dc 1a8983f8 TypeScriptLanguageService.ScriptContext.DefaultScriptContext.<GetFileNameToScriptSnapshot>b__1(TypeScriptLanguageService.ScriptContext.Script)
12a3f3e0 6f33f264 System.Linq.Enumerable.ToDictionary[[System.__Canon, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
12a3f420 1a8983b0 TypeScriptLanguageService.ScriptContext.DefaultScriptContext.GetFileNameToScriptSnapshot()
12a3f430 1a8982ef TypeScriptLanguageService.ScriptContext.DefaultScriptContext.get_CurrentSnapshot()
12a3f440 1c57adfd TypeScriptLanguageService.Features.Outlining.OutliningController+<>c__DisplayClass3.<EnqueueGetOutliningRegionsTask>b__0()
12a3f450 1c57ad3e TypeScriptLanguageService.CompilerServices.TypeScriptLanguageServicesTask.Run()
12a3f460 1c57ac59 TypeScriptLanguageService.Threading.BackgroundThreadQueue+<>c__DisplayClass8.<ExecuteOneTask>b__4()
12a3f484 1c57ab88 GuardMethodClass.GuardMethod(System.Func`1<System.Object>, System.Func`2<System.Exception,Boolean>, System.Func`2<System.Exception,System.Object>)
12a3f4ac 1c57a3c6 TypeScriptLanguageService.VsErrorReport.ExceptionFilter.Guard(System.Func`1<System.Object>, System.Func`2<System.Exception,Boolean>, System.Func`2<System.Exception,System.Object>)
12a3f4c0 1c57a356 TypeScriptLanguageService.Threading.BackgroundThreadQueue.ExecuteOneTask(TypeScriptLanguageService.Threading.BackgroundTask)
12a3f4d8 1c579aa0 TypeScriptLanguageService.Threading.BackgroundThreadQueue.ExecuteTasks()
12a3f4e4 1896b8c9 TypeScriptLanguageService.Threading.BackgroundThreadQueue.Loop()
12a3f4f0 714913c7 System.Threading.Tasks.Task.InnerInvoke()
12a3f4fc 7149134a System.Threading.Tasks.Task.Execute()
12a3f520 71491319 System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
12a3f524 7145da07 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
12a3f590 7145d956 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
12a3f5a4 71491138 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
12a3f608 71491057 System.Threading.Tasks.Task.ExecuteEntry(Boolean)
12a3f618 71490fa3 System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
12a3f61c 7147e929 System.Threading.ThreadPoolWorkQueue.Dispatch()
12a3f66c 7147e7d5 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
12a3f894 721c2552 [DebuggerU2MCatchHandlerFrame: 12a3f894] 
```

2. The main thread is waiting on:
```
0:000> !clrstack
OS Thread Id: 0x53ec (0)
Child SP       IP Call Site
0034e738 775f013d [HelperMethodFrame_1OBJ: 0034e738] System.Threading.SynchronizationContext.WaitHelper(IntPtr[], Boolean, Int32)
0034e9dc 77cf7a8a System.Windows.Threading.DispatcherSynchronizationContext.Wait(IntPtr[], Boolean, Int32)
0034e9f0 71444a4e System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext, IntPtr[], Boolean, Int32)
0034ec28 721c2552 [GCFrame: 0034ec28] 
0034ed48 721c2552 [GCFrame: 0034ed48] 
0034eeec 721c2552 [GCFrame: 0034eeec] 
0034ee9c 721c2552 [HelperMethodFrame: 0034ee9c] System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
0034ef2c 1e7fe825 TypeScriptLanguageService.ScriptContext.DefaultClosedFilesProvider.OnFileChanged(System.String)
0034ef64 1e7fe7ce TypeScriptLanguageService.ScriptContext.DefaultClosedFilesProvider+<>c__DisplayClass3.<GetEntry>b__1(System.Object, System.EventArgs)
0034ef6c 1e7fe7a7 TypeScriptLanguageService.ScriptContext.FileChangeNotificationService+Listener.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents.FilesChanged(UInt32, System.String[], UInt32[])
0034ef78 1e7fe772 Microsoft.VisualStudio.Services.FileChangeSubscription+<>c__DisplayClass2.<Notify>b__0()
0034ef8c 77900044 Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func`1<Int32>, Boolean, Boolean)
0034efc0 1e7fe3d5 Microsoft.VisualStudio.Services.FileChangeSubscription.Notify(Microsoft.VisualStudio.Shell.Interop._VSFILECHANGEFLAGS)
0034efd8 506bd4cc Microsoft.VisualStudio.Services.FileChangeSubscription.Notify(System.IO.WatcherChangeTypes, Microsoft.VisualStudio.Services.FileProperties)
0034f000 504ca93d Microsoft.VisualStudio.Services.FileWatcher.Notify(Microsoft.VisualStudio.Services.ChangeStreamDigest)
0034f064 504c6a06 Microsoft.VisualStudio.Services.DirectoryWatcher.ProcessFileChanges(System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.VisualStudio.Services.ChangeStreamDigest>>, Int32)
0034f0a8 504c6671 Microsoft.VisualStudio.Services.DirectoryWatcher.ProcessChanges(System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.VisualStudio.Services.ChangeStreamDigest>>, Int32)
0034f0e8 504c67d2 Microsoft.VisualStudio.Services.DirectoryWatcher.ProcessChanges(System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.VisualStudio.Services.ChangeStreamDigest>>, Int32)
0034f128 504c65b2 Microsoft.VisualStudio.Services.DirectoryWatcher.OnChangedAsync()
0034f164 77cf8689 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
0034f184 77cf855a MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
0034f1c8 77cfac3c System.Windows.Threading.DispatcherOperation.InvokeImpl()
0034f200 77cfab88 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
0034f208 7145da07 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
0034f274 7145d956 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
0034f288 7145d921 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
0034f2a0 77cfaaab System.Windows.Threading.DispatcherOperation.Invoke()
0034f2d8 77cf742b System.Windows.Threading.Dispatcher.ProcessQueue()
0034f320 77cf75ca System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
0034f36c 77cf880b MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
0034f3a8 77cf875b MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
0034f3b8 77cf8622 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
0034f3d8 77cf855a MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
0034f41c 77cf6cfe System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
0034f470 77cf80e1 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

3. The observed sequence looks like:
a. The build starts and after building Core (or in moment of building), the UI freeze
b. Then red squiggles appears on lines with file references to Core.d.ts
c. Then either it will succeed and unfreeze OR
d. It hangs - ~0 CPU usage, etc

4. If TS file is not opened in VS editor during the build, if I remember I haven't observed hang. I'm almost sure that without opened TS file, it just work!

### Other info
No Resharper, Web Essentials disabled

**Comment by wgebczyk** [comment]
I've tried to reporoduce on VS 2015 RC, but it just works.

At same time opening VS2013 and rerunning gulp build from command line hangs VS13 almost always.

**Comment by mhegazy** [comment]
@CyrusNajmabadi fixed this issue for VS2015 RC. @CyrusNajmabadi can the change be ported to VS2013?

**Comment by wgebczyk** [comment]
Needs More Info - means you need more info from me, or its just internal your marker?

**Comment by mhegazy** [comment]
I need more information from @CyrusNajmabadi to see if fixing this is feasible for VS2013, or not.

**Comment by CyrusNajmabadi** [comment]
I can def look into it today.

**Comment by jasonwilliams200OK** [comment]
Any update on this one?

**Comment by ddotlic** [comment]
I'm sorry to pollute the discussion here, but it's been days if not weeks that the only items open are weird corner cases/bugs in Visual Studio 2013/2015.

I have a feeling that the 1.5 final release is blocked due to these items, yet TS itself has no blocking issues and could be used just fine from other editors like Code, Atom or Sublime.

Could someone from the compiler team please comment on this? It would be a shame to further delay 1.5 launch just because of the one editor/IDE.

And yes, it's a bit ironic that the **least comfortable** TypeScript editor IMHO (and _at the moment_, I'm hopeful things will improve) is Microsoft's own "main" IDE :wink:

**Comment by jasonwilliams200OK** [comment]
It seems like the release itself is aligned to VS2015 release, things are dramatic this way.. :smile:

**Comment by ddotlic** [comment]
@jasonwilliams200OK Darn, if true, this is exactly the kind of thing I hoped we would avoid. In the "old days" this is how it has been, but these days with so many editors to choose from and bizarrely having a better experience **out** of VS 2015, it's weird to align the releases together.

**Comment by danquirk** [comment]
@ddotlic don't worry, we're aware that the current system is... suboptimal. We also don't like how long 1.5 has taken as it exacerbates this problem. We're making an effort to keep the next release cycles shorter as well as some other engineering work to try to keep the VS experience top notch and up to date (while also allowing other editors to keep moving fast and be top notch).

**Comment by CyrusNajmabadi** [comment]
@jasonwilliams200OK We've fixed this for VS2013.  The next update of VS will hopefully include it.  This is not an issue with VS2015 as we've completely rewritten how these components work.

**Comment by ddotlic** [comment]
@danquirk Yeah, I'm sure you're aware this isn't great and I guess you would have changed things if you could. It's just silly that we all couldn't use 1.5 final sooner, but seeing how 2015 RC was quite some time ago, I'm hopeful you will be allowed to release soon. Thanks for an honest comment!

**Comment by CyrusNajmabadi** [comment]
@ddotlic 

> It's just silly that we all couldn't use 1.5 final sooner

You can use 1.5 sooner, if you're willing to use some of our beta bits.  It's not true that 1.5 is ready to ship.  As you can see from our commits, we're still addressing issues with it.

**Comment by ddotlic** [comment]
@CyrusNajmabadi 
> You can use 1.5 sooner, if you're willing to use some of our beta bits

I actually **am** using 1.5-beta, and a client of mine is running code in production based on this very beta :smile: . I had an impression based on the very, very low number of bugs _not_ related to VS 2013/2015 that the release is being held up due to obscure issues which aren't in the compiler itself.

Sorry if I sounded harsh, I just want to get ahold of the newer bits asap.

**Comment by jasonwilliams200OK** [comment]
@CyrusNajmabadi, thanks for the clarification. :+1: 

@ddotlic, and to get the latest/greatest/bleeding-edge bits via npm:

```bash
npm install Microsoft/TypeScript
# as npm can install directly from the GitHub source repo as well ;)
```

**Comment by ddotlic** [comment]
@jasonwilliams200OK I'm not willig to bleed that much :wink: Kidding aside, this is for a project of a client of mine, so a certain dose of stability is preferred over the totally latest and greatest.

Anyway, the only thing I'm sorta waiting for is the `namespace` keyword, I'm not aware of any issues actually affecting my codebase and my IDE (Sublime).

**Comment by ironside** [comment]
My position largely echoes @ddotlic . Indeed,  if TypeScript (the open source language implementation) is in *any* way tied to Visual Studio (including via release cadence) it will be a big turn off. 

For the record, I am another TS user with no interest in using VS for TS development - I use Webstorm.

**Comment by mhegazy** [comment]
Porting this fix to VS2013 does not seem be something we can take on in the time being; the code bases have diverged a lot, and to fix this we need to re-architect the language service, which we have done in VS2015 anyways; we believe the issue has been addressed in VS2015.
