### ISSUE TITLE
Discriminated union accessed via 'this' can have an incorrect type in subsequent uses

### ISSUE THREAD

**Issue by nickelya** [microsoft/TypeScript#31995]
**TypeScript Version:**
3.1.3
3.5.2
3.6.0-dev.20190619
2.0.10

**Search Terms:**
discriminated union this class method duplicate name TS2322

**Code**

```ts
type State = {
    type: "numberVariant";
    data: number;
} | {
    type: "stringVariant";
    data: string;
};

class SomeClass {
    state: State;
    method() {
        while (0) { }

        this.state.data;
        
        if (this.state.type === "stringVariant") {
            let s: string = this.state.data;
        }
    }
}
```

**Expected behavior:**
There should be no error.

**Actual behavior:**
ts-bug.ts:17:17 - error TS2322: Type 'string | number' is not assignable to type 'string'.

All the types look correct on hover (on the line with the error, hovering over `data` shows `(property) data: string`), but there's an error anyway.  It seems all subsequent uses of `this.state.data` use the type of its first use, e.g. if you wrap the first `this.state.data` in a check for numberVariant, it will change the type in the error to 'number', and [will even mistakenly let you use it as a number outside of the check](https://www.typescriptlang.org/play/#src=type%20State%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22numberVariant%22%3B%0D%0A%20%20%20%20data%3A%20number%3B%0D%0A%7D%20%7C%20%7B%0D%0A%20%20%20%20type%3A%20%22stringVariant%22%3B%0D%0A%20%20%20%20data%3A%20string%3B%0D%0A%7D%3B%0D%0A%0D%0Aclass%20SomeClass%20%7B%0D%0A%20%20%20%20state%3A%20State%3B%0D%0A%20%20%20%20method()%20%7B%0D%0A%20%20%20%20%20%20%20%20while%20(0)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20if%20(this.state.type%20%3D%3D%3D%20%22numberVariant%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.state.data%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20let%20n%3A%20number%20%3D%20this.state.data%3B%20%2F%2F%20This%20should%20be%20an%20error%0D%0A%20%20%20%20%7D%0D%0A%7D).

Commenting out the loop or the first usage of `this.state.data` makes the error go away.  It also works correctly when doing `const that = this;` at the start of the method and using `that` everywhere instead.  Not reusing property names for the different variants also avoids this issue, so it's easy to workaround.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=type%20State%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22numberVariant%22%3B%0D%0A%20%20%20%20data%3A%20number%3B%0D%0A%7D%20%7C%20%7B%0D%0A%20%20%20%20type%3A%20%22stringVariant%22%3B%0D%0A%20%20%20%20data%3A%20string%3B%0D%0A%7D%3B%0D%0A%0D%0Aclass%20SomeClass%20%7B%0D%0A%20%20%20%20state%3A%20State%3B%0D%0A%20%20%20%20method()%20%7B%0D%0A%20%20%20%20%20%20%20%20while%20(0)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20this.state.data%3B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20if%20(this.state.type%20%3D%3D%3D%20%22stringVariant%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20s%3A%20string%20%3D%20this.state.data%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** 
This has apparently been the case since 2.0, so there's probably issues already but I can't find them.  But between the loop, `this`, and reused property name it reminds me a lot of #14860, which was apparently some sort of caching issue.

**Comment by orta** [comment]
Interesting, still repros on master.

Removing [the explicit cast](https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200328&ssl=22&ssc=1&pln=1&pc=1#code/C4TwDgpgBAysCGxoF4oG8CwAoKuqkgC4oAiAOwFcBbAIwgCcA1eegS3jOBIG5s8oAJonjFKtBrywBfKAB90fPAQjESAZ2BsyAc2ZsOXSfyEJiGrdslTJ2AMYAbeGrWwA9lQgBhR84U48GogQAITEcEE2-rgewAAWrgIAFACUfvz8AO6xrPbQiQAMqWhQUtiK6fjZagB0gUjVJvBGFVDl6awAZlCJcaw1dRDVylDIo6TmrDp67JwkRW0tULnAUGpmmpPaI5V9tQj1jc0VpVEl2CdAA) tells the IDE that it's a `string`  but subsequent usage as [a string fails](https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200328&ssl=1&ssc=1&pln=23&pc=1#code/C4TwDgpgBAysCGxoF4oG8CwAoKuqkgC4oAiAOwFcBbAIwgCcA1eegS3jOBIG5s8oAJonjFKtBrywBfKAB90fPAQjESAZ2BsyAc2ZsOXSfyEJiGrdslTJ2AMYAbeGrWwA9lQgBhR84U48GogQAITEcEE2-rgewAAWrgIAFACUfvz8AO6xrPbQiQAMqWhQUtiK6fjZagB0gUjVJvBGFVDl6awAZlCJcaw1dRDVylDIo6TmrDp67JwkRW0tULnAUC6ovf0I9Y3Ni7g1NPaTANYpC3ilUSXYl0A)

**Comment by ShuiRuTian** [comment]
Looks interesting, I would have a look at this. 

But I am not sure I could deal with it. So, here are something I think useful, at least for me.

1. If disable the cache in function `getTypeOfExpression`, in the first case(the provided code), the type of `this.state.data` in the assignment expression is `string|number`.
    1.1 I think this implies `flowTypeCache` is used improperly?
