### ISSUE TITLE
Please include that typeRoots is used only for resolving <reference path=""/> tags

### ISSUE THREAD

**Issue by hwkd** [microsoft/TypeScript#31998]
I've wasted tons of time and was so frustrated because the typeRoots option wasn't working as I expected. The type definition file could not be found so I looked up the documentation multiple times, googled around, and finally managed to find an answer on github issues stating that it is only for resolving the `/// <reference path=""/>` tag and that I should use the `include` option instead.

The current description for the `typeRoots` option is "List of folders to include type definitions from." and this description is sloppy and misleading. I've seen multiple other users confused and asking the same questions I did. If this description can be updated to be more precise, it would really save a lot of users' time and frustrations.

**Comment by RyanCavanaugh** [comment]
Huh? This isn't true. Do you mean `<reference types` ?

**Comment by hwkd** [comment]
@RyanCavanaugh Okay perhaps it was `/// <reference types="..."/>`

**Comment by RyanCavanaugh** [comment]
We'll be writing up better docs on this as part of the new handbook effort
