### ISSUE TITLE
enum export and import issue

### ISSUE THREAD

**Issue by dabuside** [microsoft/TypeScript#31996]
**TypeScript Version:**  3.5.1

**Search Terms:** export enum typescript

**Code**
```
a.ts
export enum RequestStatus {
  FAILED = -1,
  NOT_STARTED = 0,
  LOADING = 1,
  SUCCESS = 2
}
b.ts 
import { RequestStatus } from "../index";
var example = RequestStatus.NOT_STARTED;
👆👆👆//ReferenceError: Cannot access 'RequestStatus' before initialization
setTimeout(() => {
  console.log(RequestStatus.SUCCESS);//it works!
}, 0);
```
**Expected behavior:**
example = 0;
no error
**Actual behavior:**
ReferenceError: Cannot access 'RequestStatus' before initialization
**Playground Link:** 
I am using latest create react app for typescript template
**Related Issues:** 
yes.they said use `const enum` but now it seems They're not supported

**Comment by RyanCavanaugh** [comment]
Sounds like your loader isn't doing something right. The emitted code is fine.

**Comment by EthanSK** [comment]
I have this problem too

**Comment by alaboudi** [comment]
I have this problem too

**Comment by edisonmatoso** [comment]
same issue here, this error appear in runtime, to compiler is ok. my app is using create-react-app configuration.

**Comment by SenCodeMaker** [comment]
May be a circular reference, the enum is imported from a file which also imported something in this file, error message should be better
