### ISSUE TITLE
Merge / Concat const arrays

### ISSUE THREAD

**Issue by benneq** [microsoft/TypeScript#32006]
## Search Terms

const array concat merge

## Suggestion

Merging const arrays should result in a new const array

## Use Cases

Convenience

## Examples

```typescript
const ARR1 = ['a', 'b'] as const; // type is: readonly ['a', 'b']
const ARR2 = ['x', 'y'] as const; // type is: readonly ['x', 'y']

const CONCAT = [...ARR1, ...ARR2] as const; // type is: readonly ('a', 'b', 'x', 'y')[]
// but should be: readonly ['a', 'b', 'x', 'y']
```

## Checklist

My suggestion meets these guidelines:

* [?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
I think there's an issue somewhere here that also asks for this, but I can't remember where.

I would personally also like this because the current way of emulating this with recursive types, or conditional types (or both) is clunky, and makes you reach the max instantiation depth sooner

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/26058

I know there are other issues also asking for this but this is the only one I could find on mobile
