### ISSUE TITLE
Wildcard `include` takes precedence over `exclude`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#32002]
**TypeScript Version:** 3.5.2

**Search Terms:** include exclude tsconfig json watch wildcard glob

**Code**

``` json
{
  "include": ["./*"],
  "exclude": ["./foo/"]
}
```

```
touch main.ts

tsc --watch
```

Then:

```
mkdir ./foo/
```

**Expected behavior:** No recompile when `./foo/` dir is created.

**Actual behavior:** Recompiles

> Files included using "include" can be filtered using the "exclude" property. 

– https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by sheetalkamat** [comment]
This is working as intended. We still need to watch the root directory for anything other than `foo` and hence the watch would be invoked but it will find that there is not change in program root files and use existing program.
