### ISSUE TITLE
Excess property allowed in union, even if it's invalid for each part of the union

### ISSUE THREAD

**Issue by thgreasi** [microsoft/TypeScript#32000]
**TypeScript Version:**  3.5.1

**Search Terms:** union type excess properties props invalid inference

**Code**

```ts
type FooDict = { [key: string]: string[] };
type BarBox = { bar: FooDict }

type FooBar = FooDict | BarBox;

const fooDict:FooDict = {
	arr: [],
	excessProp: 0,// errors as expected
}

const barBox:BarBox = {
	bar: {},
	excessProp: 0,// errors as expected
}

const fooBar:FooBar = {
	arr: [],
	bar: {},
	// no error, even though it's neither a string[] nor a Dict
	excessProp: 0,
}
```

**Expected behavior:**
The `excessProp` of the `fooBar:FooBar` example should be considered invalid, since it is invalid as a property for both types of the union.

**Actual behavior:**
No type errors are found in for the `excessProp` of the `fooBar:FooBar`, even though it's incompatible with both parts of the union

**Playground Link:** [here](https://www.typescriptlang.org/play/index.html#src=type%20FooDict%20%3D%20%7B%20%5Bkey%3A%20string%5D%3A%20string%5B%5D%20%7D%3B%0D%0Atype%20BarBox%20%3D%20%7B%20bar%3A%20FooDict%20%7D%0D%0A%0D%0Atype%20FooBar%20%3D%20FooDict%20%7C%20BarBox%3B%0D%0A%0D%0Aconst%20fooDict%3AFooDict%20%3D%20%7B%0D%0A%09arr%3A%20%5B%5D%2C%0D%0A%09excessProp%3A%200%2C%2F%2F%20errors%20as%20expected%0D%0A%7D%0D%0A%0D%0Aconst%20barBox%3ABarBox%20%3D%20%7B%0D%0A%09bar%3A%20%7B%7D%2C%0D%0A%09excessProp%3A%200%2C%2F%2F%20errors%20as%20expected%0D%0A%7D%0D%0A%0D%0Aconst%20fooBar%3AFooBar%20%3D%20%7B%0D%0A%09arr%3A%20%5B%5D%2C%0D%0A%09bar%3A%20%7B%7D%2C%0D%0A%09%2F%2F%20no%20error%2C%20even%20though%20it's%20neither%20a%20string%5B%5D%20nor%20a%20Dict%0D%0A%09excessProp%3A%200%2C%0D%0A%7D)

**Related Issues:**
* https://github.com/microsoft/TypeScript/issues/31655
* https://github.com/microsoft/TypeScript/issues/20863
* https://github.com/microsoft/TypeScript/issues/30175

**Comment by axiac** [comment]
It can be reproduced with TS 3.7 but it cannot be reproduced with TS 3.8 or later.
Apparently it has been solved.

**Comment by RyanCavanaugh** [comment]
@axiac thanks!
