### ISSUE TITLE
Type inference does not work correctly with generic

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#32019]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
Type inference

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
export type AnyArray<T> = T[] | ReadonlyArray<T>;

export type Arrayable<T, R extends boolean = false> =
  | T
  | (R extends never
      ? T[]
      : R extends true
      ? ReadonlyArray<T>
      : R extends false
      ? AnyArray<T>
      : never);

export const test: Arrayable<string, never> = ['']
```

**Expected behavior:**
No error

**Actual behavior:**
error TS2322: Type 'string[]' is not assignable to type 'string'.

**Playground Link:** 
[playground](https://www.typescriptlang.org/play/index.html#src=export%20type%20AnyArray%3CT%3E%20%3D%20T%5B%5D%20%7C%20ReadonlyArray%3CT%3E%3B%0D%0A%0D%0Aexport%20type%20Arrayable%3CT%2C%20R%20extends%20boolean%20%3D%20false%3E%20%3D%0D%0A%20%20%7C%20T%0D%0A%20%20%7C%20(R%20extends%20never%0D%0A%20%20%20%20%20%20%3F%20T%5B%5D%0D%0A%20%20%20%20%20%20%3A%20R%20extends%20true%0D%0A%20%20%20%20%20%20%3F%20ReadonlyArray%3CT%3E%0D%0A%20%20%20%20%20%20%3A%20R%20extends%20false%0D%0A%20%20%20%20%20%20%3F%20AnyArray%3CT%3E%0D%0A%20%20%20%20%20%20%3A%20never)%3B%0D%0A%0D%0Aexport%20const%20test%3A%20Arrayable%3Cstring%2C%20never%3E%20%3D%20%5B''%5D)

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is working as intended. The conditional type `(R extends never ? ... )` is a distributive conditional type, and instantiation of a distributive conditional type for the empty union `never` always produces `never`. If you don't want a distributive type, write (`[R] extends [never] ? ... )` and it behaves as you expect.

**Comment by JounQin** [comment]
Thanks for your reply.
