### ISSUE TITLE
Genericity with Partial types  doesn't working in  curry function

### ISSUE THREAD

**Issue by xckai** [microsoft/TypeScript#32020]
**TypeScript Version:**  3.5.1 stable

I want to got the key string of a nested object, so I writ a function to do this, but when I using a curry function to do the same thing , vscode could't get the type of my object.
here is a simple demo to reproduce this issue:
**Code**
```ts
interface IIdentify {
  name: string;
  birthDay: Date;
}
interface IStudent {
  school:string,
  identifyInfo: Partial<IIdentify>;
}
const david ={} as IStudent 

export function path<T, K extends keyof T, K1 extends keyof T[K]>(obj: T, key: K, nestKey: K1) {
  return key + '.' + nestKey;
} //  working fine
export function path2<T, K extends keyof T, K1 extends keyof T[K]>(obj: T, key: K) {
  return (nestKey: K1) => {
    return key + '.' + nestKey;
  };
} // working fine
export function path3<T, K extends keyof T, K1 extends keyof T[K]>(obj: T ) {
  return (key: K,nestKey: K1) => {
    return key + '.' + nestKey;
  };
}// doesn't work
```
------------------
path & path2 working fine:
![image](https://user-images.githubusercontent.com/5928422/59896110-d0d19480-9419-11e9-8c96-9e6768987852.png)

![image](https://user-images.githubusercontent.com/5928422/59896086-b5ff2000-9419-11e9-9d55-207d625cb3f0.png)

and curry function with two args doesn't work ，the 'nestKey' 's type is 'never'

![image](https://user-images.githubusercontent.com/5928422/59896163-070f1400-941a-11e9-831a-ce71d33833b5.png)

**Comment by dragomirtitian** [comment]
The type parameters `K` and `K1` are on the wrong function in `path3`. Since they are inferred in the call to the inner function they should go on the inner function.

This works as expected:

```ts
interface IIdentify {
  name: string;
  birthDay: Date;
}
interface IStudent {
  school:string,
  identifyInfo: Partial<IIdentify>;
}
const david ={} as IStudent 

export function path3<T>(obj: T ) {
  return <K extends keyof T, K1 extends keyof T[K]>(key: K,nestKey: K1) => {
    return key + '.' + nestKey;
  };
}

path3(david)("identifyInfo", "name") // ok
```

**Comment by xckai** [comment]
got it ，thx
