### ISSUE TITLE
Context isn't type checked for passed callbacks

### ISSUE THREAD

**Issue by mk0x9** [microsoft/TypeScript#32024]
**TypeScript Version:**  3.6.0-dev.20190621

**Search Terms:**
orphaned this
lost context in callback

**Code**

```ts
class A {
    node = document.createElement('div');

    foo = 'bar';

    constructor() {
        const { node } = this;

        // should not compile, because this inside handler
        // would have type HTMLDivElement
        node.addEventListener('click', this.handler);

        // same here
        node.addEventListener('click', this.handlerWithImplicitContext);
    }

    handler(this: A) {
        alert(this.foo);
    }

    handlerWithImplicitContext() {
        alert(this.foo);
    }
}
```

**Expected behavior:**
TypeScript will output error, as proposed in #15.

**Actual behavior:**
Code compiles.

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20node%20%3D%20document.createElement('div')%3B%0D%0A%0D%0A%20%20%20%20foo%20%3D%20'bar'%3B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20%7B%20node%20%7D%20%3D%20this%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20should%20not%20compile%2C%20because%20this%20inside%20handler%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20would%20have%20type%20HTMLDivElement%0D%0A%20%20%20%20%20%20%20%20node.addEventListener('click'%2C%20this.handler)%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20same%20here%0D%0A%20%20%20%20%20%20%20%20node.addEventListener('click'%2C%20this.handlerWithImplicitContext)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20handler(this%3A%20A)%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(this.foo)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20handlerWithImplicitContext()%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(this.foo)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** #15

**Comment by jcalz** [comment]
So, is the problem that the [definition of the `EventListener` interface](https://github.com/Microsoft/TypeScript/blob/v3.5.2/lib/lib.dom.d.ts#L1708-L1710), namely
```ts
interface EventListener {
    (evt: Event): void;
}
```
doesn't contrain its `this` parameter?  You can do that yourself:

```ts
interface EventListener {
    (this: Element, evt: Event): void; // or something
}
```
[Link to code](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20node%20%3D%20document.createElement('div')%3B%0D%0A%0D%0A%20%20%20%20foo%20%3D%20'bar'%3B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20%7B%20node%20%7D%20%3D%20this%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20should%20not%20compile%2C%20because%20this%20inside%20handler%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20would%20have%20type%20HTMLDivElement%0D%0A%20%20%20%20%20%20%20%20node.addEventListener('click'%2C%20this.handler)%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20same%20here%0D%0A%20%20%20%20%20%20%20%20node.addEventListener('click'%2C%20this.handlerWithImplicitContext)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20handler(this%3A%20A)%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(this.foo)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20handlerWithImplicitContext()%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(this.foo)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

but it won't do anything about the "implicit context" issue without #15 or its still-open proposal for `--strictThis` in #7968. 

So is this a duplicate of #7968 or is it a suggestion that the dom library be updated?

**Comment by mk0x9** [comment]
Thanks for the extensive reply!

> So is this a duplicate of #7968 or is it a suggestion that the dom library be updated?

I'm not sure, but I think library could be updated. Not sure if it's possible to do in a way that it doesn't break anything.

Probably `EventListener` interface could be redefined from:

https://github.com/microsoft/TypeScript/blob/7f47a08a5e9874f0f97a667bd81eebddec61247c/lib/lib.dom.d.ts#L1708-L1710

to:

```ts
interface EventListener<T = any> {
    (this: T, evt: Event): void;
}
```

same with `EventListenerObject`, from:

https://github.com/microsoft/TypeScript/blob/7f47a08a5e9874f0f97a667bd81eebddec61247c/lib/lib.dom.d.ts#L5162-L5164

to: 

```ts
interface EventListenerObject<T = any> {
    handleEvent(this: T, evt: Event): void;
}
```

then `EventListenerOrEventListenerObject` could be redefined from:

https://github.com/microsoft/TypeScript/blob/7f47a08a5e9874f0f97a667bd81eebddec61247c/lib/lib.dom.d.ts#L17675

to:

```ts
declare type EventListenerOrEventListenerObject<T = any> = EventListener<T> | EventListenerObject<T>;
```

so corresponding element's overloaded generic method (second `.addEventListener`) could be redefined from:

https://github.com/microsoft/TypeScript/blob/7f47a08a5e9874f0f97a667bd81eebddec61247c/lib/lib.dom.d.ts#L6341-L6351

to: 

```ts
addEventListener(type: string, listener: EventListenerOrEventListenerObject<HTMLDivElement>, options?: boolean | AddEventListenerOptions): void; 
```

and the same for the rest of the elements & other APIs like promise's `.then` and `.catch`, window's `.requestAnimationFrame` and others.

**Comment by mk0x9** [comment]
This is complete duplicate of #28548.

Can I ask maintainers to set proper labels and close this issue? Thanks

**Comment by RyanCavanaugh** [comment]
Thanks for tracking that down!
