### ISSUE TITLE
Visual Studio allow code completion with "." and "(" keys too

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#3202]
Currently in Visual Studio selection from the code-completion list can be done only with `Tab` and `Enter` keys, but in other Visual Studio supported languages (e.g. C#), code completion works also with `.` and `(`.

I think the plugin should be extended to allow such keys, making coding faster and providing an unified experience among all Visual Studio languages.

**Comment by CyrusNajmabadi** [comment]
This should work.  @DanielRosenwasser @paulvanbrenk Don't we have the same list of completion characters as C#?

**Comment by DanielRosenwasser** [comment]
Should work. @nippur72 what version of VS are you using?

**Comment by nippur72** [comment]
VS2013 is 12.0.40 Update 5 RC
TypeScript is 1.5.0-beta (plugin downloaded just today). 

As said above, only `tab` and `enter` work, and it's rather annoying (being me used to C#)

**Comment by danquirk** [comment]
The new behavior (complete is only in VS2015 with the new Roslyn based language service. See https://github.com/Microsoft/TypeScript/issues/315
