### ISSUE TITLE
Optimize compile-on-save if for code bases with modules

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3204]
For code bases using modules, it would be safe to emit only modules and their dependencies, but not the whole solution.

Moreover, the `--isolatedModules` flag ensures that the output is safe to only emit a single file.

**Comment by jonaskello** [comment]
I'm trying to do hot reloading with tsc -w but it seems impossible since all files are always updated, so the hot-reloader always reloads everything. Any news on this issue? Will it be in 2.0?

**Comment by myitcv** [comment]
@alexeagle - presumably any Angular 2 app uses modules and so there would be significant benefit to your users if this change were to land?

@mhegazy - this is tagged as 'Visual Studio' but I don't think it's specific to either Visual Studio or "compile-on-save"?

**Comment by mhegazy** [comment]
This should be done in https://github.com/Microsoft/TypeScript/pull/9837
