### ISSUE TITLE
HTMLMainElement interface/type declaration removed in 3.5.* and @next ... present in master and 3.4.5

### ISSUE THREAD

**Issue by mysterycommand** [microsoft/TypeScript#32042]
https://github.com/microsoft/TypeScript/blob/v3.4.5/lib/lib.dom.d.ts#L7184-L7194

**TypeScript Version:**  ^3.5 (including 3.6.0-dev.20190622)

**Search Terms:**
HTMLMainElement
main
dom
lib.dom

**Code**

```ts
const main = document.querySelector('main') as HTMLMainElement;
// error TS2304: Cannot find name 'HTMLMainElement'.
```

**Expected behavior:**

No error … `HTMLMainElement` defined as in [`3.4.5`](https://github.com/microsoft/TypeScript/blob/v3.4.5/lib/lib.dom.d.ts#L7184-L7194)

**Actual behavior:**

The `interface` and `declare var` are [missing](https://github.com/microsoft/TypeScript/blob/v3.5.1/lib/lib.dom.d.ts#L7262).

**Playground Link:** TypeScript Playground is still running TS 3.4.1 which does not exhibit the issue.

**Related Issues:** Couldn't find any with this specific issue.

**Comment by sandersn** [comment]
This is an intentional effect of microsoft/TSJS-lib-generator#655, since HTMLMainElement is not a standard element. You'll need to polyfill the type if you want to use it. `<main>` now uses the HTMLElement interface.

**Comment by mysterycommand** [comment]
Ah, I suspected it might be something like that but couldn’t find the issue/PR. Thanks for the info
