### ISSUE TITLE
show computed type

### ISSUE THREAD

**Issue by zhangenming** [microsoft/TypeScript#32040]
## Examples
```
type User = {
  id: number
  name: string
  birthday: number
}
var xxx: Partial<User>
```

show the type that computed type for xxx as blow 
```
{
  ?id: number
  ?name: string
  ?birthday: number
}

```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
It's difficult to make everyone happy with when type aliases are expanded or not. 

As a workaround, I've used an `Id` type to force expansion of a given type:

```ts
type User = {
  id: number
  name: string
  birthday: number
}
type Id<T> = {} & { [ P in keyof T]: T[P]}
var xxx: Id<Partial<User>>
// quick info: 
// var xxx: {
//     id?: number | undefined;
//    name?: string | undefined;
//     birthday?: number | undefined;
// }
```

This works at the moment, no guarantees about the future.

**Comment by zhangenming** [comment]
and does is a bug?
ts dont given a error
```
var q1: number[] = []

var ww1 = q1.pop()

ww1.toFixed()
```

ww1 was undefiend
@dragomirtitian

**Comment by AnyhowStep** [comment]
Turn on your `strictNullChecks` compiler option

**Comment by RyanCavanaugh** [comment]
> It's difficult to make everyone happy with when type aliases are expanded or not.

This x 1,000. For a large type, `Partial<T>` is much easier to comprehend.
