### ISSUE TITLE
dynamically exporting members dosent work in typescript, but works in Node.js

### ISSUE THREAD

**Issue by xxyyzz2050** [microsoft/TypeScript#32046]
just check the following self-explained example

test1.js

```
function exportAll(module){
Object.keys(module).forEach(key => {
    exports[key] = module[key]; //<--- dynamically export all module keys
  });
}

//for test:
const fs = require("fs")
exports.fs=fs
exportAll(fs)
```
test2.js
```
const {fs, exists} = require("./test1")
console.log(fs.exists === exists) //<--- true
```

but, when I run the same code in typescript, by just replacing .js with .ts and run `tsc`,  it reports an error: member 'exists' dosen't exist in ./test1.js

**edit**
it seems that the problem is with `ng build` but not in `tsc` phase

**Comment by sandersn** [comment]
Typescript does not understand dynamic export patterns right now, and in .ts files does not understand `module.exports` either. That's only in .js.

**Comment by xxyyzz2050** [comment]
what "Working as Intended" means?

**Comment by sandersn** [comment]
It means
1. The module resolution code is working according the design.
2. We don’t have any plans to change the design.

**Comment by khinmarthu** [comment]
I tried to dynamically export all my components. But unfortunately, I got an error "File '/src/components/index.tsx' is not a module. ts(2306)".

This is the link I posted in stackoverflow.
https://stackoverflow.com/questions/57784757/after-dynamically-export-files-typescript-cannot-find-module-file-index-tsx

Other than changing from .tsx to .js, is there any other way to solve this error?
