### ISSUE TITLE
Generics type inference is not working as expected with curried high order functions

### ISSUE THREAD

**Issue by lucarge** [microsoft/TypeScript#32041]
**TypeScript Version:**  3.5.1

**Search Terms:** Curried high order function, generics with high order functions, generic type inference high order function

**Code**

```ts
/**
 * Boilerplate to setup the example start
 */
const payload = {
  name: "Foo",
  age: 24,
  language: "typescript"
} as const;

type Payload = typeof payload;
type Result<T extends Array<keyof Payload>> = {
  [key in T[number]]: Payload[key]
};

const getPayload = <T extends Array<keyof Payload>>(
  ...args: T
): Result<T> =>
  args.reduce(
    (accumulator, value) => ({ ...accumulator, [value]: payload[value] }),
    {} as Result<T>
  );
/**
 * Boilerplate to setup the example end
 */

const memoize = <A extends unknown[], B>(routine: (...args: A) => B) => (
  cacheSize: number
) => {
  // Do something with the cache

  return (...args: A): B => {
    const result = routine(...args);

    return result;
  };
};

// Here the return type is correct: { age: number }
// But we're using the not-memoized version of the function
const result = getPayload('age')

const getPayloadMemoized = memoize(getPayload)(1);
/**
 * Return type is wrong!! Looks like A and B has been resolved with the second function invocation
 * not the third one
 */
const resultFromMemoized = getPayloadMemoized("age");

```

**Expected behavior:**
The return type of `getPayload('age')` and `getPayloadMemoized('age')` should be the same, and should be `{ age: number }`.

**Actual behavior:**
`getPayloadMemoized('age')` cannot resolve `A` and `B` correctly, and thus the return type is `{ name: string, age: number, language: string }`, which is incorrect.

**Playground Link:**
http://bit.ly/2Fsu6rv

**Related Issues:**
No, but the discussion inside this pull request might be relevant: https://github.com/microsoft/TypeScript/pull/30215

**Comment by ahejlsberg** [comment]
This is working as intended, but you could argue it is a design limitation. When we propagate a type parameter onto the result type in a higher order function, we always attach the type parameter to the outermost function in the result type. In order for your example to behave as you expect we'd need to attach the propagated type parameter to the inner function in the result type, but that would require analysis to prove that the type parameter isn't referenced in the outer parameter list or in the outer parts of the function body (the `// Do something with the cache` section in your example). We're not equipped to do this analysis and I imagine it would be rather complicated to do so.

**Comment by lucarge** [comment]
Hi @ahejlsberg, thanks for replying first of all.
As I imagined, looks like `A` and `B` were attached to the `(cacheSize: number) =>` function, and that explains the incorrect return type.

I'm still struggling to understand the reasons behind this though. Considering the following example of `memoize` (which returns the correct type):

```typescript
const memoize = <A extends unknown[], B>(routine: (...args: A) => B) => {
  // Do something with the cache

  return (...args: A): B => {
    const result = routine(...args);

    return result;
  };
};
```

doesn't the same concerns about _referencing `A` and `B` before they have been resolved_ still apply? How introducing a function in the middle changes everything?

Apart from that, is there a flag in the TypeScript compiler to disallow this pattern (since it's unsafe)?
