### ISSUE TITLE
Inconsistent checking of numeric index types with for-in

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#32047]
I was trying to wrap my head around what a `number` index signature is and ran into something that felt strange. This may be WAI but it is certainly surprising.

**TypeScript Version:**  3.5.1

**Search Terms:**

- number index type 
- 7015

**Code**

```ts
const xs: {[k: number]: number} = [1, 2, 3];  // acts same w/o explicit index signature
const x0 = xs[0];  // ok, type is number
const x1 = xs['1'];
          // ~~~~ Element implicitly has an 'any' type
          //      because index expression is not of type 'number'.

declare let key: string;
const x = xs[key];
          // ~~~ Element implicitly has an 'any' type
          //     because index expression is not of type 'number'.

for (const k of Object.keys(xs)) {
  const x = xs[k];  // also an error
}

for (const k in xs) {
  k;  // type is string
  const x = xs[k];  // ok, type is number (!)
}
```

**Expected behavior:**

I would have expected the access in the for loop to fail with a type error. `string` is not the index type for `xs`, `number` is.

**Actual behavior:**

The code in the last loop type checks.

Either `string` should be allowed as an index type or it should not. `k`'s type in the last loop is shown as `string` but it seems that it must be something else since this is permitted.

This code works, of course: at runtime `k`'s type _is_ `string` and `x`'s type in the loop _is_ `number`. But so does the `Object.keys` variant, as well as the direct access (`x['1']`).

for-in is a terrible way to iterate over an array. If you don't care about the index you should use for-of. If you do, you can use `forEach` or `for(;;)` to get a numeric index. 

**Playground Link:** [link](http://www.typescriptlang.org/play/#src=const%20xs%3A%20%7B%5Bk%3A%20number%5D%3A%20number%7D%20%3D%20%5B1%2C%202%2C%203%5D%3B%0D%0Aconst%20x0%20%3D%20xs%5B0%5D%3B%20%20%2F%2F%20ok%2C%20type%20is%20number%0D%0Aconst%20x1%20%3D%20xs%5B'1'%5D%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20~~~~%20Element%20implicitly%20has%20an%20'any'%20type%0D%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20%20%20%20%20%20because%20index%20expression%20is%20not%20of%20type%20'number'.%0D%0A%0D%0Adeclare%20let%20key%3A%20string%3B%0D%0Aconst%20x%20%3D%20xs%5Bkey%5D%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20~~~%20Element%20implicitly%20has%20an%20'any'%20type%0D%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20%20%20%20%20because%20index%20expression%20is%20not%20of%20type%20'number'.%0D%0A%0D%0Afor%20(const%20k%20in%20xs)%20%7B%0D%0A%20%20k%3B%20%20%2F%2F%20type%20is%20string%0D%0A%20%20const%20x%20%3D%20xs%5Bk%5D%3B%20%20%2F%2F%20ok%2C%20type%20is%20number%20(!)%0D%0A%7D%0D%0A%0D%0Afor%20(const%20k%20of%20Object.keys(xs))%20%7B%0D%0A%20%20const%20x%20%3D%20xs%5Bk%5D%3B%20%20%2F%2F%20also%20an%20implicit%20any%20error%0D%0A%7D)

**Related Issues:** 

- https://github.com/microsoft/TypeScript/issues/7241
- https://github.com/microsoft/TypeScript/issues/7259

**Comment by jcalz** [comment]
#6346 ?

**Comment by danvk** [comment]
Thanks @jcalz, [this comment](https://github.com/microsoft/TypeScript/issues/6346#issuecomment-170060573) in particular clarifies that there's a "huge" amount of code out there that uses this access pattern, so breaking it all would be jarring.

Fine to close this as WAI. What surprises me is just that I'm not aware of any other situations in TypeScript where there's hidden type information like this (`k`'s type is shown as `string` but it's actually a `string` with one special ability).

**Comment by fatcerberus** [comment]
I presume the type of `k` is actually `keyof xs`.  AFAICT `keyof` is not referentially transparent: as a type it seems to encode extra information about which object it came from which is what makes e.g. homomorphic mapped types work (i.e. it's how TS knows the difference between `[K in KeyUnion]` vs. `[K in keyof T]`).

**Comment by danvk** [comment]
@fatcerberus the type is `string`, not `keyof xs`. There's been much discussion of why, but the gist is that, because of structural typing, a value may have more properties at runtime than are declared on it. And these will be enumerated by for-in.

**Comment by fatcerberus** [comment]
No, I know how `for..in` works, I was speculating on why `k` behaves differently from an explicit `string` and my conclusion was that the compiler must be treating it internally as a `keyof` type despite the intellisense claiming it’s a regular string.

**Comment by jcalz** [comment]
It's treating it as the elusive ["`NumericString`"](https://github.com/microsoft/TypeScript/issues/6346#issuecomment-169086219), a type which turns into `string` when you look at it, but when you look away briefly it turns into a numeric index.  In my opinion it would be a great thing to surface this as a real and observable subtype of `string` which matches any string value `s` for which `s === ""+(+s)`.

**Comment by fatcerberus** [comment]
So it’s basically Schrödinger‘s String.  Gotta love all the hidden magic in the TS type system. :smile:
