### ISSUE TITLE
Unable to call string methods on unions of string types which are function parameters

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#32054]
**TypeScript Version:**  3.4.5

**Search Terms:**

call string method on union of string types

**Code**

```ts
function test(s: 'pcf' | 'pcfsoft' | 'basic') {
    s = s.toLowerCase()
}
```

**Expected behavior:**

It should work. If it can only be a string, then obviously `toLowerCase()` would work.

**Actual behavior:**

```
Type 'string' is not assignable to type '"foo" | "bar" | "baz"'.
```

**Playground Link:** 

[playground link](http://www.typescriptlang.org/play/#src=%0D%0Afunction%20test(s%3A%20%22foo%22%20%7C%20%22bar%22%20%7C%20%22baz%22)%20%7B%0D%0A%20%20%20%20s%20%3D%20s.toLowerCase()%0D%0A%7D)

**Related Issues:**

**Comment by jcalz** [comment]
What do you mean you can't call `s.toLowerCase()`?

```ts
function test(s: "foo" | "bar" | "baz") {
    s.toLowerCase(); // works
}
```

The error you have is in assigning the result back to `s`.

**Comment by poseidonCore** [comment]
You can call these functions, but you are just getting a type error because `String#.toLowerCase` will return type `string`, not type  `'pcf' | 'pcfsoft' | 'basic'`.

Since `s` requires type `'pcf' | 'pcfsoft' | 'basic'`, type `string` is just too wide.

You can coerce the offending type easily/laboriously like this:

```ts
function test(s: "foo" | "bar" | "baz") {
    s = <"foo" | "bar" | "baz">s.toLowerCase()
}
```
or
```ts

function test(s: "foo" | "bar" | "baz") {
    s = <typeof s>s.toLowerCase()
}
```

**Comment by trusktr** [comment]
> The error you have is in assigning the result back to s.

Oh, right. That's what I meant then. :) Seems like that should simply just work.

**Comment by trusktr** [comment]
> String#.toLowerCase will return type string, not type 'pcf' | 'pcfsoft' | 'basic'.

Ah, I see. Because if I were to use `toUpperCase()`, then it wouldn't make sense to assign `'PCF'` back to the same var.
