### ISSUE TITLE
Syntax sugar tuple sizes

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#32053]
## Suggestion

It'd be nice to be able to specify tuple sizes.

## Use Cases

To make code simpler to write

## Examples

I want an array of numbers, like a tuple, but from length 1 to length 3. So currently I can write:

```ts
type UpToThreeNumbers = [number] | [number, number] | [number, number, number]
```

It would be nice to have a shortcut for that. For example:

```ts
type UpToThreeNumbers = [number, ...3]
```

Or something (that's not the specific syntax I'm asking for, just suggesting the functionality but syntax could differ).

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
Or this, https://github.com/microsoft/TypeScript/issues/15480

**Comment by trusktr** [comment]
@AnyhowStep Ah, I missed that one. I updated the issue to be only about tuple sizes.

**Comment by RyanCavanaugh** [comment]
You can write this helper trivially yourself once in userspace; we don't need special syntax for it.
