### ISSUE TITLE
"abstract" interface

### ISSUE THREAD

**Issue by hfmanson** [Microsoft/TypeScript#3205]
Is it possible to create an interface which only can be extended and not instantiated like WebIDL's [NoInterfaceObject]?
e.g. at dom4 idl:

`  [NoInterfaceObject, Exposed=Window]
`
`  interface NonElementParentNode {  Element? getElementById(DOMString elementId);  };
`
`  Document implements NonElementParentNode;
`
`  DocumentFragment implements NonElementParentNode;
`

Here it would be nice that NonElementParentNode will not be suggested when declaring a variable

**Comment by danquirk** [comment]
See #6
