### ISSUE TITLE
Playground Header Obscures Error

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript#32058]
The playground header obscures error messages displayed in the tooltips from the Monaco editor:

<img width="705" alt="Screen Shot 2019-06-24 at 13 12 18" src="https://user-images.githubusercontent.com/1935696/60015725-70925b00-9684-11e9-8b25-cf65a1a593e4.png">

<br>
<br>

This is due to the `z-index` of `1030` on the `nav` element...

<img width="601" alt="Screen Shot 2019-06-24 at 13 29 49" src="https://user-images.githubusercontent.com/1935696/60015727-712af180-9684-11e9-9c38-6bb29cde674c.png">

<br>
<br>

...which outranks the `z-index: 6` in the Monaco tooltip:

<img width="469" alt="Screen Shot 2019-06-24 at 13 29 14" src="https://user-images.githubusercontent.com/1935696/60015726-70925b00-9684-11e9-9555-02bc1b588ae0.png">

I believe the playground website is not open source, if [this comment](https://github.com/Microsoft/TypeScript/issues/2246#issuecomment-273865515) from @RyanCavanaugh is still accurate:

> Bad news: The website currently isn't OSS.

**Search Terms:**

playground header fixed overlap overlapping z-index

**Expected behavior:**

The full error message is visible.

**Actual behavior:**

The header obscures the error message and the user cannot read it.

**Playground Link:**

https://www.typescriptlang.org/play/#src=let%20list%3A%20Array%3Cnumber%20%7C%20string%3E%20%3D%20%5B1%2C%20%22asdf%22%2C%203%5D%3B%0D%0Alet%20obj%3A%20%7B%20%5Bkey%3A%20number%5D%3A%20'AA'%20%7D%20%3D%20%7B%20'asdf'%3A%20'AA'%20%7D%3B%0D%0A%0D%0Aobj%5B2%5D%20%3D%20'AA'%3B%0D%0A

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/23266

**Code:** Not really relevant here.
**TypeScript Version:** Not really relevant, pertains to website.

**Comment by orta** [comment]
Cool, perfect report - thanks, I've fixed this on the upcoming playground. 👍

**Comment by karlhorky** [comment]
Awesome, thanks @orta! As per https://github.com/microsoft/TypeScript/issues/23266#issuecomment-505611112 I guess it's living here for now:

Repo: https://github.com/orta/typescript-play/tree/old-site-integration
Live: https://www.typescriptlang.org/play
