### ISSUE TITLE
feat request: Ability to import generic type functions without duplicating the parameters.

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#32055]
## Search Terms

typescript type import generic function

(too ambiguous, not sure what to search)

## Suggestion

Ability to import generic type functions, including the parameters.

## Use Cases

Make things easier.

## Examples

At the moment, if I want to import a generic type function, I have to do this:

```ts
type GenericType<A, B, C> = import ('./GenericType').GenericType<A, B, C>

// use it later:
declare const f: GenericType<number, string, boolean>
```

I need to write the parameters (`<A, B, C>`), otherwise it will tell me that the arguments to `import ('./GenericType').GenericType` are not being supplied. For example, here's an actual example:

<img width="753" alt="Screen Shot 2019-06-23 at 10 28 21 PM" src="https://user-images.githubusercontent.com/297678/59993842-8f520c80-9606-11e9-840c-9cc01882d2f8.png">

It would be nice to be able to assign the whole type (including the parameters) to a new alias, so that we could write something as simple as:

```ts
type GenericType = import ('./GenericType').GenericType

// use it later:
declare const f: GenericType<number, string, boolean>
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by trusktr** [comment]
Imagine if the type parameters are complicated, f.e. `<A extends Constructor<Foo, Bar[]>, B extends number, C extends Map<Constructor<Bar, Foo[]>>>`. Repeating all the parameters at the import site is not DRY.

**Comment by ilogico** [comment]
What's wrong with `import { GenericType } from './GenericType';`?
I don't understand the need for the type alias.

**Comment by trusktr** [comment]
@ilogico Will TypeScript remove the `import` statement from the output, in order _**not**_ to create a runtime execution of the `GenericType` module?

For example, if I write

```ts
import './GenericType'
```

I expect that the module will be evaluated (anything in the top level of the module will be executed). I would expect that

```ts
import { GenericType } from './GenericType';
```

would behave the same way, executing anything in the module (because that is how ES modules are spec'd).

So I am using `type Foo = import()` syntax in order to import the type at compile-time only, without runtime side-effects.

**Comment by trusktr** [comment]
@poseidonCore ^

**Comment by poseidonCore** [comment]
Generally speaking, TS compilation will remove all type references, unless they are conflated with real objective runtime references.

Hence, statements like 
```ts
import { GenericType } from './GenericType';
```
which are pure type references, are removed at compilation, and even statements like this
```ts
import * as GenericTypeLibrary from './GenericType';
import GenericType = GenericTypeLibrary.GenericType;
```
are removed, ... unless there is some real object that is also being exported (and imported) (like if the type is nested in a namespace in a library.

Hence, the general rule for TypeScript imports is that if the only effect that an import has is to reference a type (interface, etc), then it is excluded at compilation.

This does mean that sometimes, you may expect that just referencing via `import` will have side-effects (ie instantiation of the library), but it does not ... unless there is a 'real' export being imported and used.

**Comment by poseidonCore** [comment]
... The exception to this rule is, as you suspect, a legacy `import` statement, which functions rather like `require`. So just using 

```ts
import "./GenericType";
```
will transpile to a `require` statement, even if there is nothing referenced ... at all ... let alone just types.

If you need to use both guaranteed instantiation of a library AND just want to use easy referencing of exported types, you can just combine these patterns:

```ts
import "./GenericType";
import {GenericType} from "./GenericType";
```

**Comment by dragomirtitian** [comment]
@trusktr Import that only contain types will be elided (see [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit)).

**Comment by trusktr** [comment]
Thanks guys.

I was expecting `import {GenericType} from "./GenericType";` to execute the module, similar to ES Module spec.

**Comment by trusktr** [comment]
Webpack 4 has a way to specify modules with side-effects. However I don't think something like this (f.e. in tsconfig) would outweigh just writing both lines as in @poseidonCore's example.

Initially I thought `type foo = import('./foo').foo` was a nice way to distinguish between the two, where this form would not interfere with ES Module format, and is recognizable as TypeScript-only.

**Comment by trusktr** [comment]
I discovered another reason to need this feature: without it, I can not import a type into a global declaration file, because if I use the `import` syntax anywhere in the file, it becomes a "module", and no longer in the global scope.

So, I have to do something like the following to import a type, which is not ideal (and error prone):

```ts
// globals.d.ts
type Constructor<T = object, A extends any[] = any[], Static = {}> = import('somewhere').Constructor<T, A, Static>
// ...
```

**Comment by trusktr** [comment]
What about an alias syntax?

```ts
// globals.d.ts
alias Constructor = import("somewhere").Constructor
// ...
```

**Comment by trusktr** [comment]
Shoot, and the `type Constructor = import` also creates `Constructor` as a new global, which is what I don't want. Hmmm... 🤔
