### ISSUE TITLE
Better error for decorators on parameter properties

### ISSUE THREAD

**Issue by mhevery** [Microsoft/TypeScript#3206]
BROKEN: `constructor(@Parent() public graph: Graph)`
BROKEN: `constructor(public @Parent() graph: Graph)`
WORKS: `constructor(@Parent() graph: Graph)`, but missing `public` keyword

**Comment by mhegazy** [comment]
`constructor(public @Parent() graph: Graph)` is by design, though the error can be a bit more expressive.

**Comment by mhegazy** [comment]
sorry.. i beleive `constructor(@Parent() public graph: Graph)` is by desing as well.. as it is ambigious. graph here is both a parameter to the constructor and a property declaration. it is not clear which decorator needs to be invoked and at which order. this needs to be spelled out as:

```ts
public graph: Graph;
constructor(@Parent() graph: Graph) {
     this.graph = graph;
}
```
or as:
```
@Parent() 
public graph: Graph;
constructor(graph: Graph) {
     this.graph = graph;
}
```

The error needs to be expressive though. the error we give now is useless at best.

**Comment by danquirk** [comment]
Edited the title and tags to track the work to fix the error

**Comment by mhevery** [comment]
So you are saying it is not supported by design? What is the technical reason for not supporting it?

**Comment by mhegazy** [comment]
> So you are saying it is not supported by design because it is ambiguous.

The ambiguity is for the user, looking at the code, you can have either expectations, so it is confusing.

> Can we just chose one and say that it is always the case where the annotation goes as a parameter and not as a property?

that is probably the choice i would make as well as it what you would do in plain ES7.

**Comment by mhevery** [comment]
So can we make that choice? Who needs to convinced? @johnturner? :-)

**Comment by DanielRosenwasser** [comment]
As a heads up, I think you mean @jonathandturner :smile:

**Comment by rbuckton** [comment]
@mhevery, can you elaborate on what you mean by:

> BROKEN: constructor(@Parent() public graph: Graph)

I [tested this in our playground](http://www.typescriptlang.org/Playground#src=declare%20function%20dec(x%3A%20any)%3A%20any%3B%0A%0Aclass%20C%20%7B%0A%09constructor(%20%40dec%20public%20x%3A%20any)%20%7B%0A%09%09%0A%09%7D%0A%7D) which is running 1.5 beta and it works as expected, namely:

* Decorators must always come before other modifiers.
* Decorators on a constructor parameter only ever decorate the parameter, even if the parameter has an accessibility modifier (e.g. `constructor(@Parent() public graph: Graph)`.
* If you intended to decorate the property, you must create a property declaration.

Is there something you are seeing that I'm not seeing in the playground?

**Comment by mhegazy** [comment]
sorry for the confusion then..

```ts
constructor(@Parent() public graph: Graph)  // OK
constructor(public @Parent() graph: Graph) // Error, public should come after the decorator
constructor(@Parent() graph: Graph) // OK
```
