### ISSUE TITLE
Error while installing Typescript using npm

### ISSUE THREAD

**Issue by Satyanarauyana** [microsoft/TypeScript#32061]
**Related Issues:** 
![Capture](https://user-images.githubusercontent.com/36028428/60026269-e0223d80-96b8-11e9-84d3-6b86ca601e80.PNG)

When I am trying to install typescript using the following command I am getting error
npm -g install typescript@latest.

Thanks in advance

**Comment by DanielRosenwasser** [comment]
Not clear what we can do - I would check with npm support if it's the case that you're able to install other packages.
