### ISSUE TITLE
Persist type casts/annotations

### ISSUE THREAD

**Issue by jhpratt** [microsoft/TypeScript#32078]
## Search Terms

persist type annotation cast

## Suggestion

On occasion, the same property must have its type narrowed multiple times in a single function. 

Option 1 — Simply persist a type cast (until reassignment). This _might_ be a breaking change, though I can't think of a situation where it would break existing code.

Option 2 — A new type of statement in the form of `expression is type`, which would implicitly perform the cast for the remainder of the scope (unless reassigned).

## Use Cases

It would be great to avoid casting the same property multiple times over. It can make code easier to read while still providing the necessary type information in a clear manner.

## Examples

A partial sample of some code I am using in writing a Babel plugin:

```typescript
const namespace = (attribute.name as JSXNamespacedName)
    .namespace
    .name
    .toLowerCase();
const property = t.stringLiteral(
    (attribute.name as JSXNamespacedName).name.name,
);
```

could become

```typescript
attribute.name is JSXNamespacedName;

const namespace = attribute.name.namespace.name.toLowerCase();
const property = t.stringLiteral(attribute.name.name.name);
```

with option 2. With option 1, the second cast could simply be omitted.

Similar code examples surely wouldn't be hard to come by — any time a type assertion is used multiple times in a scope.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code **(option 2, option 1 unclear)**
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Two reasons this would be a breaking change:

 1. Upcasts are allowed (though you could argue that logic shouldn't apply
 2. Downcasts can cause inference to make further code more restrictive than before
```ts
function fn(s: number | string) {
  let k = s as string;
  let j = s;
  j = 10; // Error if implemented as proposed
}
```

Duplicate #10421

**Comment by jhpratt** [comment]
Gotcha. Though intuitively, if I'm saying that `s` is in fact a `string` in your example, I would also expect `j` to be set to a `string`.

Agreed on the dupe, closing.
