### ISSUE TITLE
Const assertion for enum member fails if enum is imported from another file

### ISSUE THREAD

**Issue by anilanar** [microsoft/TypeScript#32087]
**TypeScript Version:**  3.5.2

**Search Terms:**
enum member as const import ts(1355)

**Code**

```ts
// Foo.ts
export enum Foo {
  A,
}

// Bar.ts
import { Foo } from './Foo';

enum Bar {
  A,
}

// Error: A 'const' assertions can only be applied to references to enum members, 
// or string, number, boolean, array, or object literals.ts(1355)
const foo = Foo.A as const;

// compiles fine
const bar = Bar.A as const;
```

**Expected behavior:**
Const assertion for an enum member imported from another file/module should work.

**Actual behavior:**
Const assertion for an enum member imported from another file/module fails with ts(1355).

**Comment by ajafff** [comment]
PR is up at #32110
