### ISSUE TITLE
isn't "HTMLOrSVGElement.dataset" should be type "{ [key: string]: any }" ?

### ISSUE THREAD

**Issue by jason-chang** [microsoft/TypeScript#32099]
Certainly we know in the standard html5 dataset should be "DOMStringMap" type. 
But in the real development scenarios we tend to put different types data into it . Like 'number'、'boolean'、'object'... types .
So i think that, can you change "HTMLOrSVGElement.dataset" to type "{ [key: string]: any }" ?

**Comment by nmain** [comment]
But only strings come out of it.  So unless you really like `"[object Object]"`, you wouldn't want this.

**Comment by RyanCavanaugh** [comment]
Does seem like a bad idea.
```
$0.dataset["foo"] = { k: 10  }
> {k: 10}
$0.dataset["foo"]
> "[object Object]"
```

Anyway, please follow the template. We put a lot of work into it and ignoring it tells us that you don't respect our time.
