### ISSUE TITLE
Playground cannot run

### ISSUE THREAD

**Issue by WORMSS** [microsoft/TypeScript#32106]
On the playground https://www.typescriptlang.org/play the run button no longer runs the code. It says I need to press Ctrl + Enter.

This is impossible to do over some remote viewers (such as the one I am using)
It seems you guys have changed to using an "alternative" player which has added a lot of extra options, but has now left certain things broken due to a different interface.

Is there anyway to get back to the legacy play?

The new player no longer remembers previous input. It always returns you to hello world.
This is a major step down from the one that was there yesterday.

I am sorry for posting the issue here, but it seems there is no contact information that is correct on https://www.typescriptlang.org
It says to message @typescriptlang on https://www.typescriptlang.org/community but this account doesn't seem to exist on twitter

**Comment by AnyhowStep** [comment]
I'm sorry, I couldn't resist

https://xkcd.com/1172/

**Comment by WORMSS** [comment]
I can't see the image right now, but I am going to assume it's the enterkey causes the cpu to heat up vim script one?.. If it is.. I approve.

**Comment by jcalz** [comment]
Is the new Playground being maintained here?  Or is it at [agentcooper/typescript-play](https://github.com/agentcooper/typescript-play)?

**Comment by orta** [comment]
Hey folks, it's running off [my fork](https://github.com/orta/typescript-play/tree/old-site-integration) those requests seem reasonable - I'll take a look

**Comment by orta** [comment]
Alright cool, thanks for the the report - I've changed the menu layout. 

There's now a specific "run" button and a separate "shortcuts" menu. As well as bringing back storing the last code you used between sessions when you don't use query params. Via https://github.com/orta/typescript-play/commit/a750efa5a1079b92f25a8f569757c42fcad8bc35  and https://github.com/orta/typescript-play/commit/981c9ebde6887d518337695db9bfe546a179558b

**Comment by WORMSS** [comment]
Thank you everyone for the super quick replys and solutions.

A* would recommend to a friend.

**Comment by WORMSS** [comment]
Confirmed, Works perfectly.
