### ISSUE TITLE
Type 'Promise<{}>' is not assignable to type 'Promise<ActionParamDefinitionInfo[]>'.   Type '{}' is missing the following properties from type 'ActionParamDefinitionInfo[]': length, pop, push, concat, an

### ISSUE THREAD

**Issue by succezlijunyi** [microsoft/TypeScript#32104]
```
export function func1(dp: IActionParamDataProvider): Promise<Interface1[]> {
	return import('commons/extra').then(m => {
		let inputGrid = new m.InputGrid(inputGridArgs);
		return new Promise((resolve, reject) => 
		showDialog({
			onok: (event: SZEvent, dialog: Dialog) => {
				resolve(params);
			}
		}));
	});
}
```
error :Type 'Promise<{}>' is not assignable to type 'Promise<ActionParamDefinitionInfo[]>'.
  Type '{}' is missing the following properties from type 'ActionParamDefinitionInfo[]': length, pop, push, concat, and 35 more.ts(2322)

He used to be right, now he is wrong.

**Comment by nmain** [comment]
You probably won't get any bites on this unless you provide a self-contained reproducing example - there are a lot of types and values missing in there.

**Comment by fatcerberus** [comment]
Based on the issue title and the code snippet provided, I think the problem is here:
```ts
return new Promise((resolve, reject) =>   // <-- here!
		showDialog({
			onok: (event: SZEvent, dialog: Dialog) => {
				resolve(params);
			}
		}));
```

TS can't currently infer the type parameter of `Promise` from the `resolve()` call and therefore defaults to `Promise<{}>`; `{}` being close to a top type, is not directly assignable to anything.  You'll have to provide the type of the promise manually.

**Comment by succezlijunyi** [comment]
thanks @fatcerberus @nmain ,it may be vscode's problem, the problem is resolved,when I updated vscode.A little thing i forget that the code has error in vscode but not in tsc.
