### ISSUE TITLE
interface that extends Generic class

### ISSUE THREAD

**Issue by Pomar81** [microsoft/TypeScript#32108]
React + Typescript
TS: 3.5.2
React: 16.8
@types/react: 16.8.22

**Any** Class component extends  the next type from @types/React
```type JSXElementConstructor<P> = (new (props: P) => Component<P, any>)```
What type is extending **any**  Generic class component
ex. ```class Card<T extends 'div' | 'p'>  extends React.Component<CardProps<T>> {...}```

application:
-  in conditional types
- transfer constructor function as props
- extract props types of component

**Comment by RyanCavanaugh** [comment]
Please follow one of the available templates and provide more context and detail in the report.
