### ISSUE TITLE
New Website Logo: Language Zen

### ISSUE THREAD

**Issue by ofirgeller** [Microsoft/TypeScript#3210]
Name: Language Zen
Homepage: https://www.languagezen.com
Brand Guidelines: You can use the logo to represent us and to indicate we use Typescript exclusive for all our JavaScript needs.

Logo:
![language-zen-logo](https://cloud.githubusercontent.com/assets/4271135/7698126/58a6d7a6-fe16-11e4-9545-48a6f84e9373.png)

**Comment by jonathandturner** [comment]
Added.
