### ISSUE TITLE
Intellisense for Node.js doesn't work

### ISSUE THREAD

**Issue by VladimirMikulic** [microsoft/TypeScript#32118]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 19.04

![vscode_issue](https://user-images.githubusercontent.com/35997844/60107474-45cd0300-9767-11e9-9837-ae1f46c8f985.png)

Steps to reproduce:
Just open any JS project in VS Code, easy as that. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does your project have `package.json`?

Can you also try manually installing the node typings by running `npm install --save-dev @types/node` to see if that fixes the issue

**Comment by sandersn** [comment]
@VladimirMikulic can you unassign yourself when you tried the two things @mjbvz mentioned? We'll take another look then.

**Comment by VladimirMikulic** [comment]
@mjbvz yes it does. The question is, do I have to do this for every project? Isn't there an "easier" way?

**Comment by fatcerberus** [comment]
Yes you do - TS only includes bundled typings for built-in JS functions and web APIs (`dom`).  For Node.js development you need to install `@types/node`.

**Comment by mjbvz** [comment]
I believe this should happen automatically for JavaScript code: https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition

@VladimirMikulic Can you check the typings installer log to see why we did not install the node typings?

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a big log file in VS Code. In the same directory as that log file, there should be another file called `ti-xxx.log`. That is the typings installer log

If you can share that typings installer, we should be able to see why the types were not installed

**Comment by fatcerberus** [comment]
Hmm, I’ve personally never seen `@types/node` be installed automatically either.

**Comment by VladimirMikulic** [comment]
@mjbvz hmmm, interesting. I've reinstalled VS Code and now it works, but this issue is not solved yet.
I'll leave it as it is for a few more days and see if the issue will occur again.

**Comment by mjbvz** [comment]
Closing as not actionable without more information

If you see this again with VS Code 1.53+ and TypeScript 4.15+, please let us know
