### ISSUE TITLE
Using `require` in method or Class breaks JavaScript IntelliSense

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#32119]
Hi since 2017 this issue seem not fixed and can't find any solution!
Did you have a tips to fix this guys ?

The current problem is when I use. ex: `require('fs')` in a js Class. My class IntelliSense  become broken.
![requireIssusIntelli](https://user-images.githubusercontent.com/24865815/58312970-8210ea80-7dda-11e9-8a1e-12baf505a3ad.gif)

Hope i can get help.
Thanks

related to:
https://github.com/microsoft/vscode/issues/51758
https://github.com/microsoft/vscode/issues/37126

**Comment by mjbvz** [comment]
Thanks @djmisterjon. I confirmed this with TypeScript 3.6.0-dev.20190626 using your simple example

**Comment by fatcerberus** [comment]
@djmisterjon The issue was moved to the typescript repo because the TS language service handles the IntelliSense for TS and JS projects in VSCode.

**Comment by djmisterjon** [comment]
for now , alternative it use eval in dev :)
example:
`var fs = eval("require('fs')")`

will not break intellisence

**Comment by DanielRX** [comment]
After looking at the duplicated issue, this is just a case of you not exporting the class?
```js
export class File1 {
    constructor() {
    };

    stuff(){
        var r = require;
        var rr = require('fs');
    }
};
```
```js
import {File1} from './file1';

class file2 {
    constructor() {
        File1
    };
};
```
This works fine, but as the linked issue mentions, the class is not global when require exists in the file, as it is assumed to be a module, not a script.
Note: Puting a require *anywhere* in `file1.js` breaks the intellisense (because it's a module)

**Comment by djmisterjon** [comment]
import export crash my app with nwjs

**Comment by DanielRX** [comment]
@djmisterjon You use require, implying you are using modules? If you can use `require`, can't you use `require` and `module.exports` in your files?

**Comment by djmisterjon** [comment]
@DanielRX 
it not work 
![image](https://user-images.githubusercontent.com/24865815/60720848-071f1180-9efa-11e9-8a9f-92d9d1d645f5.png)

**Comment by DanielRX** [comment]
If you can use require, can't you use require and **module.exports** in your files?
You should swap it to say `module.exports.File1 = File1;` on line `32`and then use `const {File1} = require('./camera')`

**Comment by orta** [comment]
Hi folks, just took a look over this. I think what's happening is by including the `require` the IntelliSense declares that file not a Script (in the sense of a web script) and this toggles your Types to not be available inside the global scope. 

This means your other file can't just know about the other type without you providing some advice to the system.

For example:

```ts
// file1.ts
class File1 {
  constructor() {
  };

  stuff(){
      var r = require;
      var rr = require('fs');
  }
};

module.exports = {
  File1
}

// file2.js
const {File1} = require("./file1")

class File2 {
  constructor() {
      const a = new File1()
      a.stuff
  };
};

```

Auto-completes as you'd expect.

**Comment by orta** [comment]
Double checked and this is what we expect it to be, thanks for the issue, I’m going to close jt
