### ISSUE TITLE
how to judge two interface has no overlap

### ISSUE THREAD

**Issue by bgfist** [microsoft/TypeScript#32123]
THE ISSUE TRACKER IS NOT FOR QUESTIONS.

DO NOT CREATE A NEW ISSUE TO ASK A QUESTION.

IF YOU ARE HAVING PROBLEMS WITH YOUR TYPESCRIPT CODE, DO NOT ASK A QUESTION HERE.

Tens of thousands of TypeScript questions have been asked and answered on StackOverflow; see https://stackoverflow.com/questions/tagged/typescript . You can ask questions there or on other websites.

The only exception is if you have a question about *the TypeScript compiler API itself*. Please post a complete example of what you're trying to do and precisely describe what your question is.

```ts
interface A {
   name: string
}

interface B {
   name: string
   age: number
}

class C<P,D> {
}
```

I want compiler to check that the generic parameters of C don't overlap in properties. So the code below will issue an error: 
```ts
new C<A,B>
```

**Comment by Kingwl** [comment]
https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAcg9sA8gNwgJwDYEMwB4CCANFAEIB8UAvFAKIAewaWAxsLgNYQhwBmURUTtz7koEBhAB2AEwDOUSRFRooAfn5QAZKSgAuBUvQAoIwEtJwdDxbR8UAN5GozqDzhx9sxuYDmRgL4m5pZo1szQJA5OLgBGWGie3pJ+gWYWVjZQAMJRLq7uiWi+0c5xCVBeRckBJtIQzNho0Mxwkl5QWPrwSMrYeALkRnUN8c2t7TFdCCjofQTEWWRD9Y1jbcBQzFM9szi4JAtLRlgAdGVGMWfxRsxXaEZAA

**Comment by bgfist** [comment]
```ts
type NotOverlap<A, B> = Extract<keyof A, keyof B> extends never ? A & B : never

interface A {
    foo: string
}

interface B {
    bar: string
}

interface C {
    foo: string
    bar: string
}

declare const a: NotOverlap<A, B>
declare const b: NotOverlap<A, C>   // I want the error appears here
declare const c: NotOverlap<B, C>

a.bar
b.bar  // not here after I access the prop.
c.bar
```

**Comment by MartinJohns** [comment]
@bgfist Perhaps you want to read the issue template you chose to ignore? :-)  
https://github.com/microsoft/TypeScript/blob/master/.github/ISSUE_TEMPLATE/Question.md
