### ISSUE TITLE
Type inference for constant objects with string literal types

### ISSUE THREAD

**Issue by a-rodin** [microsoft/TypeScript#32139]
Hi!

Let's say that I have this code:

```typescript
interface Greeter {
    hello: 'world'
}

function hello() {
    const first: Greeter = {
        hello: 'world'
    };

    const obj = {
        hello: 'world'
    };

    const second: Greeter = obj;
}
```

For the `first` object the compiler can infer type of `hello` as a string literal type and outputs no errors. However, for the second object can't infer this, although `obj` is a constant object, and throws an error.

It would be nice to have automatic inference here. For example, in Flow types are inferred here automatically and the same code passes type checks without errors.

Addition: specifying the string type literal explicitly helps:

```typescript
const obj = {
    hello: 'world' as 'world'
}
```

but makes the code look verbose.

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> However, for the second object can't infer this, although obj is a constant object, and throws an error.

The variable `obj` is constant, but the object is not. You can re-assign a new value with `obj.hello = "fubar";` just fine.

What you want can be achieve with the "const contexts" feature introduced in tYpeScript 3.4: #29510

    const obj = { hello: 'world' } as const;

**Comment by a-rodin** [comment]
> What you want can be achieve with the "const contexts" feature introduced in TypeScript 3.4: #29510
Yes, "const contexts" make the code look better here, I didn't know about them.

> This would definitely be a breaking change in existing code. If it would infer obj.hello as the type 'world', then re-assigning a different string would not work anymore.
I agree, so what I was actually thinking about was more similar to automatic inference of "const context" in some cases. In my example "obj" cannot be changed from the outside of the function and it is not changed inside, so in this particular case the compiler could infer that `obj.hello` can never change.

**Comment by MartinJohns** [comment]
> I was actually thinking about was more similar to automatic inference of "const context" in some cases.

I see. Personally I think it's really not worth the additional code (complexity) and performance cost (the analysis), when we already have a very good feature to solve this without hassle: const contexts.
