### ISSUE TITLE
setTimeout incorrect typings browser

### ISSUE THREAD

**Issue by GoGoris** [microsoft/TypeScript#32133]
**TypeScript Version:**  3.4.5

**Search Terms:** setTimeout

**Code**

```ts
const timeout: number = setTimeout(() => console.log('anything'), 300);
```

**Expected behavior:**

It compiles correctly

**Actual behavior:**
```
Type 'Timeout' is not assignable to type 'number'.

1 const timeout: number = setTimeout(() => console.log('anything'), 300);
        ~~~~~~~


Found 1 error.
```

**Playground Link:** 

Not reproducable in playground

**Related Issues:** 

Possibly #19635, but this issue seems to be outdated because now the declaration of setTimeout looks like:

```
type TimerHandler = string | Function;
setTimeout(handler: TimerHandler, timeout?: number, ...arguments: any[]): number;
```
https://stackoverflow.com/q/45802988

**Comment by nmain** [comment]
Somewhere in your dependency tree is a package that works in both Node and the browser.  When used in Node, it probably supports some Node types like `Buffer`, and so it brings in `@types/node` to express that relationship, which causes Node globals to become available, and Node has a `setTimeout` with a different definition than the browser one.

As a workaround, you can use `window.setTimeout` which will only have the browser definition.

I think the best solution to this is to move forward with https://github.com/microsoft/TypeScript/issues/31894 and then change typings of all packages that optionally use Node to support them, but that's a ways off.

**Comment by AviVahl** [comment]
I found using `ReturnType<typeof setTimeout>` instead of `number` a cleaner workaround.
