### ISSUE TITLE
Access to static fields via constructor property

### ISSUE THREAD

**Issue by y-a-r-g** [Microsoft/TypeScript#3213]
This is example of correct code, though compiler raises an error `Property 'bar' does not exist on type 'Function'.`

```typescript
class A {
	static bar(): void {
		alert("Oh hi!");
	}
	
	foo(): void {
		this.constructor.bar(); //<-- compiler error
	}
}
```

**Comment by mhegazy** [comment]
pinging @rbuckton for this one. the main reason is that constructor is not guaranteed to be set to the right thing all the time; consider an ambient class from a .d.ts modeling an existing js class implementation.

**Comment by rbuckton** [comment]
Consider the following:
```ts
class A {
    static x() { return 1; }
    y() {
        let z = this.constructor.x(); // z: string;
        console.log(typeof z);
    }
}

class B extends A {
    static x() { return undefined; }
}

class C extends B {
    static x() { return "text"; }
}

let a = new A();
a.y(); // prints: "number";
let b = new B();
b.y(); // prints: "undefined";
let c = new C();
c.y(); // prints: "string";
```

If we made `constructor` have the type `typeof A` here, a derived type could return something unexpected.

**Comment by y-a-r-g** [comment]
Got it. Thank you.

I've found this workaround:
```typescript
class A {
	static bar(): void {
		alert("Oh hi!");
	}
	
	foo(): void {
		(<AStatic>this.constructor).bar();
	}
}

new A().foo();

interface AStatic {
	new (): A
	bar(): void
}
```
Is there any simpler solution?

**Comment by oxyflour** [comment]
Hi, I just found that using \<typeof A\> instead of \<AStatic\> is ok : )

    class A {
        static bar(): void {
            alert('hello')
        }
        foo(): void {
            (<typeof A> this.constructor).bar()
        }
    }
    new A().foo()

**Comment by y-a-r-g** [comment]
Wow, that's very nice! Thanks
