### ISSUE TITLE
Unable to assign `Pick<T, K>` to `Partial<T>`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#32132]
**TypeScript Version:** 3.5.2

**Search Terms:** generic pick partial keyof constraint extends subtype

**Code**

In the following example, I can't think of any situation where assigning `Pick<T, K>` to `Partial<T>` would not be sound, therefore I would expect this to be allowed.

Can anyone clarify why it is not currently allowed? Should it be allowed?

```ts
const fn = <T, K extends keyof T>(partial: Partial<T>, picked: Pick<T, K>) => {
  /*
    Type 'Pick<T, K>' is not assignable to type 'Partial<T>'.
        Type 'keyof T' is not assignable to type 'K'.
            'keyof T' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
    */
  partial = picked;
};
```

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/28884

**Comment by jcalz** [comment]
[Speak of the devil...](https://stackoverflow.com/a/56794513/2887218)

**Comment by OliverJAsh** [comment]
Will close this in favour of that explanation. Thanks! ❤️
