### ISSUE TITLE
Language service plugin: how to efficiently parse code and produce diagnostics?

### ISSUE THREAD

**Issue by anurbol** [microsoft/TypeScript#32141]
I am sorry for bothering, but there is nowhere I can get the answer to my question.. (I've asked many much, much simpler questions on SO with no answers). And the question is about TS Compiler API, I guess.

So, with this great tutorial: https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin I am writing an LS plugin. 

Everything's great, really! There is only concern about efficiency/performance (or consistency if I decide to sacrifice it).

So, in the name of simplicity, imagine I am making a JSDoc-like syntax that lives inside TS comments, but the syntax is strict and must not compile in production if incorrect. Therefore, I have to check syntactic and semantic correctness, also I need to show hover info and provide references between the symbols in this language. I am doing these things by decorating `getSyntacticDiagnostics`, `getSemanticDiagnostics`, `getQuickInfoAtPosition`, `getReferencesAtPosition`.

Here's the problem: 
1. Consider that the parsing is a costly operation (I have to parse the whole project tree, because the files have links to the each other's symbols and hence two files may become invalid even if only one has been modified). Now, given that fact, it would be quite inefficient to run parsing of the project tree everytime `getSyntacticDiagnostics` and `getSemanticDiagnostics` are called.
See the problem? Even if one file is modified once, I will run parsing twice (in order to provide both `syntacticDiagnostics` and `semanticDiagnostics`). That doesn't seem OK programmig, does it?
**So the questions related to this problem are:**
1.1. How do I prevent double parsing? 
1.2. What's the correct way to only do parsing once a file has been modified?
1.3. Is `getSyntacticDiagnostics` reliably called on every file modification? Is `getSemanticDiagnostics` always called after `getSyntacticDiagnostics` (from what I've observed, the answer is YES, unless the first function is cancelled by a new modification)?

My current solution is actually parsing once when `getSyntacticDiagnostics` is called and, assuming that `getSemanticDiagnostics` is always called immediately after that, reusing the last parsed results, but I don't like this, I feel that this can lead to non up-to-date `semantic errors` (if said assumption is not correct).

Other problem: 

2. I've seen `cancellationToken` here and there. What's that, can I use it in order to stop parsing when it is no longer needed? If yes how? If no, how do I know if a new file modification happened (and thus I need to restart parsing)?

P.S. I've done research of how things are done in TS compiler and language service, spent hours in TS source, but it didn't help... That's why I am here asking for your help. Sorry for long text.

**Comment by RyanCavanaugh** [comment]
Short answers but hopefully enough to go on.

`SourceFile` objects have a (internal) `version` property that monotonically increases, so you can weakly cache on this to detect if a file is modified.

There is no contract about the order of `getSyntacticDiagnostics` / `getSemanticDiagnostics`. Editors can ask for either at any time.

`cancellationToken` is used to stop longer-running operations during interactive scenarios so that the server can handle a higher-priority request. For example, getting errors can take a while, but you want completions during an editing operation right away. You should try to call `cancellationToken.throwIfCancellationRequested()` within any long-running portions of your code every so often (ideally maybe every 50ms, though you can call it *much* more frequently without meaningfully impacting perf) to keep the editor responsive. Note that this does *throw* if the current operation is cancelled, so you need to account for the fact that your current code stack will be terminated.

**Comment by anurbol** [comment]
@RyanCavanaugh thank you for quick repsonse! That `version` property is a real game changer! Knowing that there is no contract will save me a lot of time and nerves. I will try all the 3 things (including cancellationToken) shortly and will update this issue. Thanks again, it's really what I need!

**Comment by anurbol** [comment]
@RyanCavanaugh Hi! Can you please give a little more details on the `version` property? So it does indeed increment on every file change, however it is not a simple number, but a string of one of these formats:
`Text-1` or `SVC-1-X` where `X` is the incrementing number. 

SVC-format only appears in modified files AND in the first opened in editor one. Text-1 appears in the remaining files (unmodified or opened after the first file was opened) and the number `1` never changes after `Text-`. 

All of this is almost self-explaining, but I would be much more confident in my plugin if I would know:
What's `1` in `SVC-1-X`? Can it ever change or disappear, and if yes, what would that mean?

It would be also good to know what's the disambiguation of `SVC`. Thank you!

**Comment by anurbol** [comment]
Just for those who may need this (and if I am wrong, @RyanCavanaugh please correct me if I am wrong):

The `version` property is a string that can be of two formats (starts with one of the following): `SVC-{X}-{Y}` (stands for Script Version Cache) or `Text-{Z}`.
`SVC` is generated when the sourcefile is modified or sometimes (if it's the first file opened in editor?) on demand. `Text` is a guaranteed marker of unmodified file. For the real script version we should use the `Y` in `SVC-{X}-{Y}`, `X` is always 1, at least in my experience (and I don't understand the purpose of `X` yet). 
`Z` in `Text-{Z}` is the same, it is always 1 in my experience, and I don't understand its purpose as well.
