### ISSUE TITLE
Using --out with ES6 modules

### ISSUE THREAD

**Issue by filipstachura** [Microsoft/TypeScript#3214]
Is it possible to compile whole project to one file with `--out` when using ES6 modules? I've just completed a huge refactoring to find out that each file is compiled independently and one specified with `--out` is empty.

Small example:
*a.ts*
```
import {b} from "b"
console.log(b.test);
```

*b.ts*
```
export class b {
  public static test: string = "test";
}
```

After compiling with: `tsc *.ts --target ES5 --out main.js --module commonjs` we got:
*tree .*
```
.
├── a.js
├── a.ts
├── b.js
├── b.ts
└── main.js
```

*a.js*
```
var b_1 = require("b");
console.log(b_1.b.test);
```

*b.js*
```
var b = (function () {
    function b() {
    }
    b.test = "test";
    return b;
})();
exports.b = b;
```

And *main.js* is empty.

**Comment by marekrogala** [comment]
+1

**Comment by danquirk** [comment]
You probably want to look at https://github.com/Microsoft/TypeScript/issues/2568#issuecomment-103576583. The behavior you're seeing here is the same way TypeScript external modules (which map to ES6 modules) have always behaved.

**Comment by filipstachura** [comment]
@danquirk Thanks for your help!

Do you know if there are  any *state of the art* ways to merge all those files? My idea now is to compile to commonjs and use browserify after that.

**Comment by mhegazy** [comment]
there are different alternatives for bundling available based on your application, you can use browserify, JSPM, or r.js for instance..

**Comment by filipstachura** [comment]
@mhegazy Thanks for coming back to me. In the end I chose to use webpack. I'm closing this question right now.

**Comment by jpsfs** [comment]
Hi,

Sorry for digging up this issue.
I'm facing the same problem and right now we are following @mhegazy suggestion. It works, but the sourcemaps generation becomes a lot trickier to do.

So, right now the process is:
> tsc compiles all the es6 modules to a temp folder
> using systemjs bundler, we get all the *.js files and bundle them to a single .js

The issue is that if we use the systemjs bundler to generate the sourcemaps we will get the maps for all the .js files and not .ts.

Is there any plans on doing this bundle all together inside tsc?

Best regards,
