### ISSUE TITLE
Expand selection crashing tsserver 

### ISSUE THREAD

**Issue by loveloper44** [microsoft/TypeScript#32146]
- VSCode Version:1.35.1
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

1. Generate .ts file and write code below.
 <pre><code>
class User{
    private name: string;
}
// here
</code></pre>

2. Place cursor to `here` and use Expand selection.

3. Expand selection is not working anymore.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Confirmed with 3.6.0-dev.20190627
