### ISSUE TITLE
Strange behavior with Omit<Object, Union>

### ISSUE THREAD

**Issue by lucifer1004** [microsoft/TypeScript#32154]
**TypeScript Version:**  3.5.2 (also tested on latest dev)

**Search Terms:** Omit, Union

**Code**

```ts
type SimpleObject = {a: number, b: string, c: boolean}
type MyOmit<T, P> = P extends string | number | symbol
  ? Omit<T, P>
  : T;
type TestOmit = Omit<SimpleObject, "a" | "b">
type TestMyOmit = MyOmit<SimpleObject, "a" | "b">
```

**Expected behavior:**
`TestOmit` and `TestMyOmit` should equal to each other.

**Actual behavior:**
Below are the type inference shown in VS Code.

```ts
type TestOmit = {
    c:boolean
}

type TestMyOmit = Pick<{
    a: number;
    b: string;
    c: boolean;
}, "b" | "c"> | Pick<{
    a: number;
    b: string;
    c: boolean;
}, "a" | "c">
```

I do not know why the second result becomes a union. 

**Playground Link:**  [CodeSandBox](https://codesandbox.io/embed/priceless-shockley-dqyyl?fontsize=14)

**Related Issues:**

**Comment by fatcerberus** [comment]
Two words: Union distribution.

```ts
type MyOmit<T, P> = P extends string | number | symbol
  ? Omit<T, P>
  : T;

type TestMyOmit = MyOmit<SimpleObject, "a" | "b">;

// distributes over "a" | "b", therefore equivalent to:
type TestMyOmit2 = 
    | Omit<SimpleObject, "a">
    | Omit<SimpleObject, "b">;
```

**Comment by lucifer1004** [comment]
But what causes this distribution? I mean, `TestOmit` works just fine.

**Comment by fatcerberus** [comment]
`TestMyOmit` is conditional, with a naked type parameter `P`.  The whole ternary expression thus gets evaluated once for each member of `P` and the results are recombined into a new union at the end.  `TestOmit` just defers to `Omit` unconditionally so the distribution over `P` doesn’t happen.

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types

**Comment by lucifer1004** [comment]
> `MyOmit` is conditional, with a naked type parameter `P`. The whole ternary expression thus gets evaluated once for each member of `P` and the results are recombined into a new union at the end. `TestOmit` just defers to `Omit` unconditionally so the distribution over `P` doesn’t happen.
> 
> See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types

Thanks a lot. I just started to play with Typescript generics.
One more question, is there a way to avoid this distribution? Is it possible to pass `"a" | "b"` as a whole in `MyOmit`?

**Comment by fatcerberus** [comment]
@lucifer1004 Yes; as mentioned above, the distribution only happens over a “naked type parameter”, so you can write the conditional type’s constraint as e.g. `[T] extends [CheckType]` - because `[T]` is no longer a union (it’s a tuple-of-union which can’t be simplified any further), this disables the distributive behavior.
