### ISSUE TITLE
TS: Auto imports not working when overwriting a package's typings

### ISSUE THREAD

**Issue by didinele** [microsoft/TypeScript#32155]
- VSCode Version:
```shell
~ ➜ yay -Ss visual-studio-code-insiders
aur/visual-studio-code-insiders 1557850607-1
```

- OS Version: 4.19.49-1-MANJARO

Steps to Reproduce:

1. Overwrite a package's Typings, e.g.
```ts
declare module 'package-name' {
    interface someProperty {
       overwrittenProp: string;
    }
}
```
2. Starting to type the name of a property from said package no longer prompts you to auto import, even though this was working before step 1.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share a specific package and code sample that demonstrates this? I just tested with `@angular/core` for example but could not repo:

<img width="771" alt="Screen Shot 2019-06-27 at 5 15 00 PM" src="https://user-images.githubusercontent.com/12821956/60308748-2e288280-98ff-11e9-9c87-b0c3f52cf68c.png">

**Comment by didinele** [comment]
Well, I'm using a package that overwrite's another package's typings, the combination is currently the master branch for discord-akairo & discord.js

`npm i discord-akairo/discord-akairo discordjs/discord.js`

Akairo overwrites discord.js' typings, in its definition files.

Attempting to type `Message` (a property from discord.js) will no longer show the option to auto import

**Comment by didinele** [comment]
Where any changes regarding this pushed to Insiders? I have been noticing different behaivour in the last 2-3 weeks, it seems mostly okay but I've experienced it creating duplicate imports or just not auto importing a specific thing, I'll get back in touch and describe the issues I'm currently experiencing.
