### ISSUE TITLE
Typo in commandLineParser.ts

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#32171]
There is a typo in the `convertToTSConfig` function in _commandLineParser.ts_:

https://github.com/microsoft/TypeScript/blob/b4a1a5996f632a811fadaeba5008acf4acbde383/src/compiler/commandLineParser.ts#L1784

Should be `compileOnSave` not `compilerOnSave`.

Also, the `config` variable is not typed, which is why this wasn't caught:

https://github.com/microsoft/TypeScript/blob/b4a1a5996f632a811fadaeba5008acf4acbde383/src/compiler/commandLineParser.ts#L1764

**Comment by MartinJohns** [comment]
Perhaps add a type to detect typos at compile-time? :-)
