### ISSUE TITLE
TS Handbook Suggestion:  add code documentation generation info to the typescript website

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/TypeScript#32177]
## Search Terms
tsdoc, typedoc, code documentation

## Suggestion

There's a lot of solutions for code doc generation out there, especially with helpers allowing conversion to esdoc/jsdoc format.   Typedoc is the popular one, but it's output is not very good for code spanning more than 1 file.   There's also some Msft rolled Typescript specific solutions, which are very complex.

- https://typedoc.org/
- https://github.com/Microsoft/tsdoc
- https://api-extractor.com/
- https://dotnet.github.io/docfx/tutorial/universalreference/gen_doc_for_ts.html

They are all quite a lot of work to even try out.

How about the typescript team add a section to the website explaining the E2E workflow for a reasonable choice?   

## Use Cases

Easy way for people to learn how to generate code docs for a medium sized codebase.

**Comment by RyanCavanaugh** [comment]
We're trying to actually reduce the scope of what the Handbook in an effort to make it more exhaustive in terms of what it does actually cover

**Comment by jasonswearingen** [comment]
okie, sorry for the spam.
