### ISSUE TITLE
Tuples cannot be used as arrays

### ISSUE THREAD

**Issue by ftrimble** [microsoft/TypeScript#32175]
**TypeScript Version:**  3.5.1

**Search Terms:**
tuples
arrays
iterators

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
const TUPLE = ['a', 'b', 'c'] as const;

function map<T, V>(inputArray: T[], iteratee: (value: T, index: number) => Promise<V>): Promise<V[]> {
  return Promise.all(inputArray.map(iteratee))
}

async function run() {
  console.log(
    await map(
      TUPLE,
      (val: typeof TUPLE[number], index: number) => new Promise(resolve => resolve(val)),
      ),
  );
}
```

**Expected behavior:**

You should be able to use the tuple as an array in this example. If not there should be some type that can be used to use the values of a tuple

**Actual behavior:**

`readonly ['a', 'b', 'c'] is not assignable to parameter of type ('a' | 'b' | 'c')[]`

**Playground Link:** 

https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBAKgVQAoBkCiMC8MDaByAQzwBoY8AjEs4PAXRgIhlEigG4BYAKG4DMBXMMCgBLcDAC2BAA4AeOKQBqAPgAUIsNP5QAggCc9BAJ4AueDlqkRUAKaHbNs6oBuBADb9H8K2AAmNgA8zMH4JcjsASixlGCQ9EAkRCBtZFQizOISklMULGIBvbhgYPRsofj0wWPjE5IA6dzd1TW19QyM6qWl1W3sbGwiI7gBfbm5GIyEYASFRcT1BVSjCrmKWCBA3Gzq3EABzVSLihgB3AmtJGUPV4+LEVDRiI9uXdzMoI2kbEF54ZHQcCEwnZLDANP4gjAgeE9FFMDEwDYTtUsslVKUNm5nDZoiUbJjsa83IMnjdbhFScUIpwuKMeFwFmAlkA

**Related Issues:**

**Comment by dragomirtitian** [comment]
The real problem is that `as const` produces a readonly tuple. 

Type the tuple manually 

```ts
const TUPLE = ['a', 'b', 'c'] as ['a','b', 'c'];
```
Or change the function to take a readonly array 

```ts
function map<T, V>(inputArray: readonly T[], iteratee: (value: T, index: number) => Promise<V>): Promise<V[]> {
  return Promise.all(inputArray.map(iteratee))
}
```

And it all works

**Comment by ftrimble** [comment]
oh yup i'm a dunce; i messed up my test cases for the alternatives, and didn't actually test them all properly
