### ISSUE TITLE
type infer from generic function

### ISSUE THREAD

**Issue by Pomar81** [microsoft/TypeScript#32170]
**TypeScript Version:**  3.5.1-3.5.2

**Search Terms:**
infer type from generic function

**Code**

```ts
type genericProps<T> = {
  abcId: string
  count: number
  flag: boolean
  className?: string
  as?: T
}


declare function genericFC<T>(props: genericProps<T>): any 

type test<T> = typeof genericFC extends <T>(props: infer P) => any ? P : never
```

**Expected behavior:**

```
 {
    abcId: string
    count: number
    flag: boolean
    className?: string
    as?: T
  }
```

**Actual behavior:**
 ```
{
    abcId: string
    count: number
    flag: boolean
    className?: string
    as?: unknown
  }
```

**Playground Link:**  [link](https://www.typescriptlang.org/play/index.html?jsx=2#code/LAKA9GAEBmCGDWBTSAjAlgOwCaYOYGdQtEBjAG1gCdkNYBbRfAB1hOQCVFWAXSAb1CQYAVwwluaAPYZIJarG6IAomUQMM3ABQBKAFyRYGAJ4BuUAF9QVkNyNNkuRBkSU0JAAqVJTfAB4AKgB8kAC8-IIGKCQAklj6+NyuGLgRJJKi3PoYwnQoLhHQFLj6KJKSqoapFPj4AHL0iAD88Yl4EbD4zZD+FtZEpBTUImIS0pCOzq4kAGIAwgGBmkxePvoTLm6e3n5BegbGkNa29pCKCQuhp3aIktDjThszs5CIAB6K2PiQC0sr+PqYaAuSDubShYKGIyQRogyBZRAAN3yIFAYAAVBE3vZxIg4ocQEIBAShJEYniEkkUsShGkMlkcnlKBEhIVYMVUGUKhhmbJqnUGl0KW1qQZOvoesTLCA0WBrEA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is working as expected. There's no relation between the two `T`s in `test`'s declaration; i.e. you could equally have written
```ts
type test<T> = typeof genericFC extends <U>(props: infer P) => any ? P : never
``

I expect what you're trying to do is refer to a specific call instantiation of a generic function, which isn't currently possible.

**Comment by Pomar81** [comment]
Yes, I wanted to refer to specific call instantiation of a generic function

**Comment by ahejlsberg** [comment]
With #47607 it is possible to refer to specific instantiations of generic functions.
