### ISSUE TITLE
Error on runtime when using generic class with extension

### ISSUE THREAD

**Issue by billy-yoyo** [microsoft/TypeScript#32180]
**TypeScript Version:**  3.6.0-dev.20190629

**Search Terms:**
webpack typescript Object.setPrototypeOf: expected an object or null, got undefined

**Code**

Area.ts:
```ts
import { Space } from './space';
import { Pos } from './pos';

export class Area<T extends Space> extends Pos<T> {
    width: number;
    height: number;

    constructor(x: number, y: number, width: number, height: number, space: T) {
        super(x, y, space);

        this.width = width;
        this.height = height;
    }

    // ...

    // included this since it is possibled related to self-referential type?
    intersectsArea(area: Area<T>):boolean {
        return area.left <= this.right && this.left <= area.right && area.bottom <= this.top && this.bottom <= area.top;
    }

}
```

Pos.ts:
```ts
import { Space, Canvas, World } from './space';

export class Pos<T extends Space> {
    x: number;
    y: number;
    space: T;

    constructor(x: number, y: number, space: T) {
        this.x = x;
        this.y = y;
        this.space = space;
    }

    // ...
}
```

Space.ts
```ts
export abstract class Space { /* ... */ }
export class World extends Space { /* ... */ }
export class Canvas extends Space { /* ... */ }
```

tsconfig.json
```json
{
    "compilerOptions": {
        "module": "es6",
        "target": "es5",
        "sourceMap": true,
        "allowJs": true,
        "noImplicitAny": true,
        "outDir": "./dist/",
        "lib": [
            "dom",
            "es5"
        ]
    },
    "include": [
        "src/**/*"
    ],
    "compileOnSave": true
}
```

webpack.config.js
```
const path = require('path');

module.exports = {
    entry: './src/app.ts',
    devtool: 'inline-source-map',
    mode: 'development',
    module: {
        rules: [
          {
            test: /\.tsx?$/,
            use: 'ts-loader',
            exclude: /node_modules/
          }
        ]
    },
    resolve: {
        extensions: [ '.tsx', '.ts', '.js' ]
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
        library: 'MyApp'
    }
};
```

**Expected behavior:**
The program runs correctly without an error

**Actual behavior:**
After compiling with webpack `npx webpack --config webpack.config.js`, I then open my web app and get the following runtime error:

```
TypeError: Object.setPrototypeOf: expected an object or null, got undefined bundle.js:153:16
    extendStatics bundle.js:153
    __extends bundle.js:156
    Area area.ts:4
    ts area.ts:4
    Webpack 9
```

Where `area.ts:4` points to the class definition line.

**Playground Link:** 
I couldn't reproduce the issue in typescript playground, which makes me think it's potentially an issue with webpack / ts-loader rather than ts directly.

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/16506

**Comment by billy-yoyo** [comment]
I narrowed down the bug to a much smaller set of files:

pos.ts:
```ts
import { Area } from "./area";

export class Pos {
    x: number;
    y: number;
    
    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }

    createArea(x: number, y: number, width: number, height: number): Area {
        return new Area(x, y, width, height);
    }
}
```

area.ts:
```ts
import { Pos } from "./pos";

export class Area extends Pos {
    width: number;
    height: number;
    
    constructor(x: number, y: number, width: number, height: number) {
        super(x, y);

        this.width = width;
        this.height = height;
    }
}
```

It's related to the method which returns an `Area` inside `Pos`. If I remove this method it works. 
Also, if I move both these classes in to a single file it works, so it's definitely related to being in seperate files, and for this reason I can't reproduce it in TypeScript playground.

**Comment by nattthebear** [comment]
pos.ts depends on area.ts which depends on pos.ts which depends on area.ts which depends on pos.ts which depends on area.ts...

The es modules spec allows circular imports, but in those cases your code may run before the values it's importing exist, and `class C extends undefined` is not legal.

**Comment by billy-yoyo** [comment]
It runs fine without the function in Pos which returns Area, circular imports isn't the entire problem. The only reason I bothered raising it is that the classes work fine in a single file, which considering I'm compiling to a single file (so not actually using es modules) made me wonder if it should work.

**Comment by nattthebear** [comment]
Without the function in Pos which returns an Area, there is no longer a circular dependency so the whole thing is moot.

Even when compiling output to a single file, tsc still respects the fact that your input was modules.  Single file compilation either uses AMD or System.js; in either case, your runtime loader is left to replicate a vaguely-esm like environment, and when two module definitions reference each other, it has to do _something_.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't control webpack's loading order, which seems to be the root cause of the problem here.
