### ISSUE TITLE
How to use both boolean and string value in enum?

### ISSUE THREAD

**Issue by kingller** [microsoft/TypeScript#32192]
Hi,
When I write the code as bellow,
```
export enum TableResponsiveType {
    NO = false,
    NORMAL = true,
    WHOLE = 'whole',
}
```
An error happens,
```
TS2553: Computed values are not permitted in an enum with string valued members.
```
At first I had only Boolean values, but then I added a string value for the project. When I change the code to enum of TypeScript, an error happens. It is caused by the combination of Boolean values and strings.
Can you help me? thanks.

**Comment by dragomirtitian** [comment]
This is not about mixing `boolean` with `string` it's just that `boolean` is not supported in enums at all. This is also an error:

```ts
export enum TableResponsiveType {
    NO = false,
    NORMAL = true,
}
```
[Playground](https://typescript-play.js.org/#code/KYDwDg9gTgLgBMAdgVwLZwCoEMBGAbYAJWAGdJESBLAN2AwE8xg4BvAKDk7gDkB5OALxwAZljwlgAGg5c+hALIBBADKC4MKMilsAvkA)

Enums can contain `number` or `string` or both.

**Comment by kingller** [comment]
Will it be supported? What should I do?

**Comment by weswigham** [comment]
```ts
namespace TableResponsiveType {
    export const NO = false;
    export const NORMAL = true;
    export const WHOLE = 'whole';
}
type TableResponsiveType  = (typeof TableResponsiveType)[keyof typeof TableResponsiveType];
```

**Comment by kingller** [comment]
It's OK now. Thanks very much.

**Comment by benmed00** [comment]
> This is not about mixing `boolean` with `string` it's just that `boolean` is not supported in enums at all. This is also an error:
> 
> ```ts
> export enum TableResponsiveType {
>     NO = false,
>     NORMAL = true,
> }
> ```
> 
> [Playground](https://typescript-play.js.org/#code/KYDwDg9gTgLgBMAdgVwLZwCoEMBGAbYAJWAGdJESBLAN2AwE8xg4BvAKDk7gDkB5OALxwAZljwlgAGg5c+hALIBBADKC4MKMilsAvkA)
> 
> Enums can contain `number` or `string` or both.

Is it still true, rignt now ?

**Comment by xiBread** [comment]
Yes

**Comment by firofame** [comment]
boolean is not supported in enums. but why not?
