### ISSUE TITLE
Should rest parameters emit Array.prototype.slice instead of for loop?

### ISSUE THREAD

**Issue by bryanforbes** [Microsoft/TypeScript#3219]
Is there a reason that rest parameters emit a for loop instead of a slice call? For example:

```ts
function foo(...args: any[]): void {
}
function bar(first: number, ...args: any[]): void {
}
```

emits:

```js
function foo() {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i - 0] = arguments[_i];
    }
}
function bar(first) {
    var args = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        args[_i - 1] = arguments[_i];
    }
}
```

This could be very easily simplified to:

```js
function foo() {
    var args = Array.prototype.slice.call(arguments, 0);
}
function bar(first) {
    var args = Array.prototype.slice.call(arguments, 1);
}
```

As per [the spec](http://es5.github.io/#x15.4.4.10), `slice` is designed to be generic and will work on array-like objects (like `arguments`). Although there is a caveat that each implementation can determine if `slice` can be run on host objects, `arguments` is [not a host object](http://es5.github.io/#x10.6). Is there another reason not to use `slice` that I'm missing?

**Comment by RyanCavanaugh** [comment]
First reason, `slice.call` is generally found to be slower than the straight array copy.

Second reason, we avoid having to determine if `Array` actually points to the global value `Array` instead of a lexically-shadowing thing called `Array`.

See also the same discussion here https://github.com/babel/babel/issues/211

**Comment by bryanforbes** [comment]
All of those reasons make sense. Thank you!

**Comment by RyanCavanaugh** [comment]
Link is now https://phabricator.babeljs.io/T211
