### ISSUE TITLE
Remove/Fix 'Go To Declaration' from right click context menu in VS

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#322]
This option:
![image](https://cloud.githubusercontent.com/assets/7121557/3770715/e7e80e30-18ed-11e4-9756-e0a44f1595e4.png)
either returns no results or nonsense results. We haven't actually attempted to implement it. It should not appear on the context menu. C# has removed it from theirs.

**Comment by CyrusNajmabadi** [comment]
I cannot repro this with the latest VS2015 bits.  If you encounter this again, let me know!
