### ISSUE TITLE
Display down the name of a private method only used by unused private methods

### ISSUE THREAD

**Issue by stephaneeybert** [microsoft/TypeScript#32203]
If a private method is used only by, other private methods which are all unsed, then display down the name of this used private method.

**Comment by mjbvz** [comment]
I believe this is a duplicate of an issue in the TS repo but can't find the correct issue at the moment. Moving upstream to see if anyone else can track down the old issue or if there is any new feedback on this

**Comment by RyanCavanaugh** [comment]
I can't figure out what "display down" means from context here.

**Comment by dragomirtitian** [comment]
@RyanCavanaugh  most likely OP is referring to the graying/fading out of unused methods:

![image](https://user-images.githubusercontent.com/8193316/60543381-df278680-9d1e-11e9-9dee-85963015c824.png)

**Comment by RyanCavanaugh** [comment]
I don't think this is worth slowing down general editing for - it'd require a lot more computation (we effectively get unused data "for free" today vs having to do a smarter entrypoint-based painting algorithm).

**Comment by stephaneeybert** [comment]
Sorry for ma coming back late to this thread. As a frenchie, I could not guess the word to express the opposite of highlighting. I understand it is not so important and maybe not worth the computing power.
