### ISSUE TITLE
className is only included in HTMLElement, not Element

### ISSUE THREAD

**Issue by kfranqueiro** [Microsoft/TypeScript#3220]
@Arnavion pointed out to me that a recent update moved `classList` from `HTMLElement` up into `Element`, which is great.

However, `className` appears to still be only in `HTMLElement`.  Is there a reason why?  [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element#Properties) at least seems to indicate that both should be common to Element.

It'd be great if this were moved up as well, as we currently need to cast when writing class manipulation APIs that should have no problem supporting `Element` (both `HTMLElement` and `SVGElement`).  Given how these declarations are auto-generated though, I'm not sure what that would require.

**Comment by RyanCavanaugh** [comment]
Spec agrees: http://www.w3.org/TR/2015/WD-dom-20150428/#element

**Comment by kfranqueiro** [comment]
Tangentially, another colleague pointed out to me that the same problem exists with `id` (it's in the `HTMLElement` interface right now).

**Comment by duanyao** [comment]
The problem is, SVG elements has a different definition of `className`:

http://www.w3.org/TR/SVG/single-page.html#types-InterfaceSVGStylable
```
interface SVGStylable {
  readonly attribute SVGAnimatedString className;
}
interface SVGAnimatedString {
           attribute DOMString baseVal setraises(DOMException);
           readonly attribute DOMString animVal;
}
interface SVGElement : Element {}
interface SVGPathElement : SVGElement, SVGStylable { }
```

So it seems in `SVGPathElement` etc., `Element::className` is overridden by `SVGStylable::className`? This is not a big problem for JS, but TS currently don't allow overriding member's type of super interface. What to do?

I also discussed this issue here https://github.com/Microsoft/TypeScript/issues/424#issuecomment-102908565 .

**Comment by zhengbli** [comment]
Confirmed the current IE spec (from which the dom contents are generated) puts the ``className`` into ``HTMLElement``. Also it is good point that @duanyao mentions, it may worth discussing whether to change the behavior or not.

**Comment by mhegazy** [comment]
@zhengbli looks like an IE spec issue.

**Comment by duanyao** [comment]
Looked into [WebIDL spec](http://heycam.github.io/webidl/#idl-interfaces) and found that overriding of interface members is explicitly allowed:

> Interfaces may specify an interface member that has the same name as one from an inherited interface. Objects that implement the derived interface will expose the member on the derived interface. It is language binding specific whether the overridden member can be accessed on the object. 

Maybe it is desirable for TS to be aligned to this behavior, or sometimes it is awkward to translate WebIDL interfaces to TS ones.

**Comment by kfranqueiro** [comment]
It does seem like for practical purposes at least, `SVGElement` would need a unique typing for `className`, even if it is available on `Element` as per the spec.  My mistake for not realizing that initially.

(On the other hand, I think `id` could be safely raised into `Element`; it's a DOMString both for [Element](http://www.w3.org/TR/dom/#interface-element) and [SVGElement](http://www.w3.org/TR/SVG/single-page.html#types-InterfaceSVGElement) and is currently defined as a `string` for both `HTMLElement` and `SVGElement` in `dom.generated.d.ts`.)

**Comment by SaschaNaz** [comment]
`SVGElement` spec does not extend DOM3 `Element` but [DOM2 `Element`](http://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-745549614), which didn't have `className` property. Maybe we need something like `interface DOM2Element`...

**Comment by duanyao** [comment]
@SaschaNaz It looks like a bug of SVG2 spec for me, because the same spec references DOM4 in [another place](http://www.w3.org/TR/SVG2/svgdom.html): 

>The SVG DOM requires complete support for DOM4 [DOM4]

Additionally, there is no multiple DOM implementaions with different levels in browsers, and the following expressions are both true:

```
Element.prototype.isPrototypeOf(SVGElement.prototype)
Element.prototype.isPrototypeOf(HTMLElement.prototype)
```
