### ISSUE TITLE
Allow for static members to reference class type parameters (Error: TS2302)

### ISSUE THREAD

**Issue by geoyws** [microsoft/TypeScript#32211]
## Search Terms

1. [allow for static members to reference class type parameters] (https://github.com/microsoft/TypeScript/issues/24018)
2. ts2302

## Suggestion

Allow for static members to reference class type parameters because it saves typing.

Perhaps we could use a factory to dynamically create classes based on the generic type provided.

## Use Cases

```TypeScript
import Big from 'big.js';

// db column
class Column<T> {
  static readonly _name: string;
  static readonly comment: string;
  static readonly dataType: typeof T = T; // error: Static members cannot reference class type parameters ts(2302)

  constructor(readonly value: T) {}
}

class Bigint {
  constructor(readonly value: Big = new Big(0)) {}
}

class Amount extends Column<Bigint> {
  static readonly _name: string = '"amt"';
  //static readonly dataType: typeof Bigint = Bigint; // this would be unnecessary
}
														
class Quantity extends Column<BigInt> {
  static readonly _name: string = '"qty"';
  //static readonly dataType: typeof Bigint = Bigint; // this would be unnecessary
}

```

## Examples

See previous section.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by poseidonCore** [comment]
If so, then was type is `Column.dataType`, given that as a static property, it must exist even without any instance being generated?

This is basically the first question in #24018, and I can't see how you have answered it yet.

**Comment by geoyws** [comment]
The type would be provided by the subclass i.e.:

```TypeScript
class Amount extends Column<Bigint> { // <— here the generic type is provided
  static readonly _name: string = '"amt"';
  // (inherited) static readonly dataType: typeof T = T; // hence this would be `typeof Bigint = Bigint`
}
```

**Comment by poseidonCore** [comment]
I realise your intent, but what I am trying to say is that it does not make sense with existing TS patterns.

There is nothing about class `Column<T> {...}` that says it must be extended for `T` to be known.

Basically, at the point of consuming `Column.dataType`, is it `any` or `unknown` or (at best) a default class as in `Column<T extends Big = Big> {...}`?

If your proposal is "Allow for static members to reference class type parameters, defaulting to `any` | `unknown` | default type", then that might make sense, but as it is, it is not compatible with current expectations for consuming a static class that has not been extended.

**Comment by geoyws** [comment]
Hold on. Apologies, I was wrong about the use of `typeof`… I thought it was supposed to fetch me a function constructor but instead it’s TS’ way to get the type of a variable.

How about the below?

```TypeScript
import Big from 'big.js';

interface ICtor {
  new (...args: any[]) : {};
}

// db column
class Column<T> {
  static readonly _name: string;
  static readonly comment: string;
  static readonly dataType: ICtor = ({} as T).constructor; // error: Static members cannot reference class type parameters ts(2302)

  constructor(readonly value: T) {}
}

class Bigint {
  constructor(readonly value: Big = new Big(0)) {}
}

class Amount extends Column<Bigint> {
  static readonly _name: string = '"amt"';
  //static readonly dataType: ICtor = ({} as Bigint).constructor; // this would be unnecessary
}

class Quantity extends Column<BigInt> {
  static readonly _name: string = '"qty"';
  //static readonly dataType: ICtor = ({} as Bigint).constructor; // this would be unnecessary
}
```

**Comment by superamadeus** [comment]
@geoyws You still seem to be misunderstanding. You cannot use a _type_ to get a constructor for the type. Furthermore, `({} as BigInt).constructor` returns the same value as `({}).constructor`; the `Object` constructor. This is because [type assertions](https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html#type-assertion-vs-casting) do not actually create an instance of the type they specify, they're just hints to the compiler as to what type the value is supposed to be. 

So you could never take a generic parameter `T` and automatically get an instance or reference to a constructor of it in the first place.

To solve the case you've described, you could use [mixins](https://www.typescriptlang.org/docs/handbook/mixins.html) like so: 

```typescript
type Constructor<T, Args extends any[] = any[]> = new (...args: Args) => T;

export interface ColumnConstructor<T> {
  readonly _name: string;
  readonly comment: string;
  readonly dataType: Constructor<T>;

  new (value: T): Column<T>;
}

interface Column<T> {
  readonly value: T;
}

function Column<T>(dataType: Constructor<T>): ColumnConstructor<T> {
  return class Column {
    static readonly _name: string;
    static readonly comment: string;
    static readonly dataType = dataType;

    constructor(readonly value: T) {}
  };
}

class Bigint {
  constructor(readonly value: Big = new Big(0)) {}
}

class Amount extends Column(Bigint) {
  static readonly _name: string = '"amt"';
}

class Quantity extends Column(Bigint) {
  static readonly _name: string = '"qty"';
}
```
[Playground Link](https://www.typescriptlang.org/play/#code/MYGwhgzhAEBCCWBzaBvAUNawD2A7CALgE4CuwB2RAFAHR1hGIQBc0YuAngNoC6AlKgC+aYWgD0Y6ABUAFgFNoAImCQC8XIkXQO2EtGLw5AE2hHscmLmwEZ6xDTRoc+AqbAEwUjgAc5ARmgAXmhcOQB3aAB5ACMAKzlyKj4aZ0JSckoAbic8QjcPL18AJiChFNziMgoibNTXI3dPHzkAZlKqFEE2GDS7ZLr06tqK-KbfABZ2zu64JH6KwazHVOwQORoQbEQqDExRwv8gwOCGguaigBpdzFOxw+OTxoOWq7395oCH94nXvduDz7HKJxBIENB8TLQCT6UgKSpw2EwkhyRwEZrQADCCyqlAAPFILtAAIKMGByAAeBDkuCMMHY3B4pXpvAAfKVQhFaPRSawSUwBIE2VJsmgKd5KK51FSiAAzMDABRYkAkAC2uCxLkWRHxbPQmCIcjAZlwIA40AA+rgwCq5KxehpsvrDcbTVhsCqbbgCHaDA7dgajXhXf9mqwNWkcdqpCyRZgOdAqAA3MDK23SPhh1aq3A67KiKVyWXyxVZtU61D+51Bs3J1OsYUiRwyki4cjwPCY0s56NUEO+TOayM6jOd5Vq8OVDJR3WVggkIi4LDgKCj7MVt6EdzwYDQAMus2W61p+2IR17TdqHd76tuj3U73QE9nzAX7e7qsms19hSPM6+WN7AMkZUNen7QLWyL1gInS7IIebLMuMAIIgUrrm6g5TiBH6uhBabIey4SzNsAAMfDQcIoigJAMBEiquhetAFJUjSMBKtmVDIVK0G7K+V7YQeVo2j6RB2KUADkijWgQihifBTiIdAACKJDsGoaKMZS1K0quaocUgXFobx76BmBh5CY+vrIMEEkAI5ojJckrGsGxbFQtH0QQNDfkcwScV6EJQpIUiwjk+CrOsmzbMpqnwGiXlPOiXx+QQAXQsFyKOGgQA)

**Comment by fatcerberus** [comment]
Yeah, I don't see how this can work.  Until an instance of the class (or an instance of a subclass) is constructed, *you don't actually have a type `T`*--because it hasn't been passed in yet.  Effectively, you're trying to access a variable that's not in scope yet; it'd be like trying to ask for the value of a function parameter outside of the function: the question itself is meaningless.

**Comment by RyanCavanaugh** [comment]
Every attempt to do this is a conceptual confusion. Critically, the constructor object for a generic class *is not generic* -- it *contains* generic construct signatures, which is a completely different thing.

**Comment by geoyws** [comment]
@fatcerberus @RyanCavanaugh thanks for your time guys.

I was thinking perhaps TS could implement this via a class factory that churns out custom constructor functions fitted with the static properties and methods.

@superamadeus appreciate the clarification very much.

**Comment by nmain** [comment]
> I was thinking perhaps TS could implement this via a class factory that churns out custom constructor functions fitted with the static properties and methods.

You can certainly do something like that for yourself and [typescript will typecheck it](https://www.typescriptlang.org/play/?target=6#code/GYVwdgxgLglg9mABBATgUwIZTQYTgGxAFswd8MBnCgHgBUA+ACjAyLQC5EKoUYwBzADTI4RNmCiduvAcIAmaYBhD4oANQyEOiWgEpEAbwBQiU4nRQQKJBHJVEeQiUMmzb7lhgRzmOQnwAnogA+ixsiAC8iGFoANyubqYesN7oGH5ggSJiaBKR2eJQ8YlmyV4+6f5BCkoq6pog2rT5NcqqGlrFJSJg0iDQcCiMaRlZAG4NTfoGiAC+CXPx80YQCNyIAIJEcOBQ+aiY2I7EpHYUjABErFAXwhdbO3lwwFyWwMC3iAAMYLrxD7sAHStOodRqxRAAekhiAARjB+HwoEYwGgAO6bba7RgAFl+EOhiDgAGsjCs1nsAMqiNBQAAWfH4AFF8BQ0Ps0kcCCcyJRzhdgHA4J8LiA2ShEHxBSKABJofD4OA6OlodAXP5GalsemMlls4GKNr1TpQmHSRko9GILW0hkCPVoS4AcSFclhAXZYDgaIAhOqCTCSUYgA).

But any idea of typescript automatically inserting a factory like this and then calling it with different values each time you use a generic class with different parameters is type directed emit and out of scope.

**Comment by RyanCavanaugh** [comment]
It's also not what ES6 does.

**Comment by geoyws** [comment]
> > I was thinking perhaps TS could implement this via a class factory that churns out custom constructor functions fitted with the static properties and methods.
> 
> You can certainly do something like that for yourself and [typescript will typecheck it](https://www.typescriptlang.org/play/?target=6#code/GYVwdgxgLglg9mABBATgUwIZTQYTgGxAFswd8MBnCgHgBUA+ACjAyLQC5EKoUYwBzADTI4RNmCiduvAcIAmaYBhD4oANQyEOiWgEpEAbwBQiU4nRQQKJBHJVEeQiUMmzb7lhgRzmOQnwAnogA+ixsiAC8iGFoANyubqYesN7oGH5ggSJiaBKR2eJQ8YlmyV4+6f5BCkoq6pog2rT5NcqqGlrFJSJg0iDQcCiMaRlZAG4NTfoGiAC+CXPx80YQCNyIAIJEcOBQ+aiY2I7EpHYUjABErFAXwhdbO3lwwFyWwMC3iAAMYLrxD7sAHStOodRqxRAAekhiAARjB+HwoEYwGgAO6bba7RgAFl+EOhiDgAGsjCs1nsAMqiNBQAAWfH4AFF8BQ0Ps0kcCCcyJRzhdgHA4J8LiA2ShEHxBSKABJofD4OA6OlodAXP5GalsemMlls4GKNr1TpQmHSRko9GILW0hkCPVoS4AcSFclhAXZYDgaIAhOqCTCSUYgA).
> 
> But any idea of typescript automatically inserting a factory like this and then calling it with different values each time you use a generic class with different parameters is type directed emit and out of scope.

So it’s because TS’ [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) that prohibits her from type directed emit. That explains things. Thanks for the explanation guys.

**Comment by miguel-leon** [comment]
This is actually possible to do but with a lot of jumping around.
By inferring the type argument from `this` (which btw, the compiler also complains about with a different error).

```ts
class C_<T> {
    // static myStatic: T;
}

interface Ctor {
    myStatic: this extends typeof C_<infer T> ? T : never;
}

const C: typeof C_ & Ctor = C_ as any;


C.myStatic; // unknown
C<number>.myStatic; // number
```

[playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDCD6AeAKgPmgbwLAChr+gHpDoIAXMMgS2GgFsBPAZQuuAC5pkBuIkgUwBOggPaDoAJgDMABgm4CfUqxr1mKjtDIALKjH4APMvwB2AExhkGAB34iAZnCRUT9oV3QB+LtE4n+AG5CvMTQQqLiEgCsEgBsuAC+uLguxoL2YMD8cGRimAoEjCyUNJw6emFGphZaNnaOCIgubuJo0N7IvtD+QYLcick4wCIm5HBldQ5O0ABkOXkAvNOQ0GAmDP04g7AAdEUaISQAriYA1iYiAO4muLCIJkd0AEZCqHvqJcCH3Y8vgrhAA)

Admittedly, it might not make any sense for a static property like this. But it can be very useful for say, a parameter of a static method.

So if it is after all possible, it might as well be allowed with the simpler syntax and save us the hassle.
