### ISSUE TITLE
Fix identifier scanning per latest ECMAScript + Unicode spec

### ISSUE THREAD

**Issue by mathiasbynens** [microsoft/TypeScript#32213]
TypeScript still scans identifiers based on the old ES5 spec (which listed some specific Unicode categories to look for): https://github.com/microsoft/TypeScript/blob/c3a9429420452fdfad73e9d947e52ca825a4b8f7/src/compiler/scanner.ts#L202-L248

However, [since ES2015 this was changed](https://mathiasbynens.be/notes/javascript-identifiers-es6), and now instead of a mess of categories, identifiers are mostly `ID_Start` and `ID_Continue`.

ECMAScript also follows the latest version of the Unicode Standard (which is currently Unicode v12.1.0). TypeScript currently seems to be using Unicode v3 data.

TypeScript currently cannot handle certain valid identifiers and also handles certain invalid identifiers as if they were valid. Examples:

https://www.typescriptlang.org/play/?target=1#code/PTAEFEA8EMFsAcA2BTAzqALtA1sgdqAGYBOA9rAFwBQIoAFhhvKhSLNBnQJbSoBGATzz5UAOj7JgeUhjTAAVtABuvAMbEu8DAFouAE3wYuhLsmKptaAGxUaYAGrRE+0FwLgAygCYADAEYAVmoVYlAAHQBXAG8rPwBfUABeUAAWLwBuW1pHZz1Xdw8A0AAyUABVPC5VUgNQJQDRP1EfAGoAGlA+CIx8lVz8iG9-IKoQ0EB6OnTQWjKWr3AvADFQe3AAJQAVAEkAYQBBABlQbYOAEXBR6FDI+aWpmbmF5dXN3cPjrbOLu1AtvD6XG5BgEOl0egC8kDPL5AsErqBAAAbgHK9+5gWZ+HxePYAdlA+zWWz2ADlQAdwBsNutQHsvJdrtEMVjsXFUeUWoycXi9gTiaTyZS1tTaT8-hCBp4itA8HlocM4fTTgAOHw+SLnHGs9GYznEZDwXWoQzIPK8UDQUCoCLEMgAcw4yFA8GgXGIWTAoqcgIKkulgxhIM63QtEXg8FIxFkkIIpEQMsKoHwNrcaHldUiKtixEyQA

**Search Terms:**

ECMAScript, ES5, ES2015, identifier, IdentifierStart, IdentifierPart, Unicode, parsing, scanning

**Comment by jcalz** [comment]
Related to #31963 ?
