### ISSUE TITLE
Proposal: Promisable built-in type

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#32220]
## Search Terms

promisable

## Suggestion

I'd like to see a built-in "Promisable" type added.

## Use Cases

Some times we are just awaiting a function, so we don't really care if the returned value is actually a promise or not. Promisable would be defined like this:

```ts
type Promisable<T> = T | Promise<T>;
```

## Examples

With it I can write this:

```ts
type Foo = () => Promisable<string | number | null>
```

Rather than this:

```ts
type Foo = () => string | number | null | Promise<string> | Promise<number> | Promise<null>
```

I've found it to be fairly useful for writing cleaner code when dealing with `async`/`await`.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/31394

**Comment by fabiospampinato** [comment]
> Duplicate of #31394


Let's keep the discussion in the other issue then 👍

**Comment by fatcerberus** [comment]
Duplicate of #31394 (which is also IMO a better proposal as it includes `PromiseLike`, i.e. all thenables).

Note: Be careful - `Promise<string> | Promise<number>` is different from `Promise<string | number>` from the perspective of the type system (but equivalent in practice since the promise is covariant and only ever contains a single value).
