### ISSUE TITLE
Import codefix uses too-deep path

### ISSUE THREAD

**Issue by jpike88** [microsoft/TypeScript#32222]
**TypeScript Version:**  3.5.2

**Search Terms:** import @angular/compiler/src/core

When auto-importing ChangeDetectionStrategy in angular 8, this line gets pulled in, which breaks production builds.

**Expected behavior:**

```
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
```
**Actual behavior:**

```
import { Component, Input } from '@angular/core';
import { ChangeDetectionStrategy } from '@angular/compiler/src/core';
```

Might be related to this, which was marked as fixed and locked

https://github.com/microsoft/TypeScript/issues/19694

**Comment by sandersn** [comment]
@jpike88 Sounds like you might have a new repro of that bug. Can you provide a standalone example, or a pointer to a repo that exhibits the error?

**Comment by jpike88** [comment]
https://github.com/jpike88/quickstart

npm install in root dir for typescript, then npm install in client dir for angular dependencies.

open the example.code-workspace, then look for a file called app.module.ts

try the autocomplete, ChangeDetectionStrategy is suggested in two options. The top option is the path that breaks builds.

<img width="578" alt="Screen Shot 2019-07-03 at 9 57 28 AM" src="https://user-images.githubusercontent.com/9585787/60557894-c0a2a900-9d79-11e9-9fdc-e474cb2fbb9d.png">

I can't repro it with a fresh angular starter repo, but I'm using latest angular dependencies...

**Comment by RyanCavanaugh** [comment]
It's been a while, there are a bunch of new autoimport rules, and this hasn't been reported in any other form in the meantime. Assuming it's either fixed or working as intended.
