### ISSUE TITLE
Return type inference does not infer union

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#32237]
**TypeScript Version:**  3.5.1, 3.3.3

**Search Terms:**

return type, infer, union

**Code**

```ts
/**
 * + TS 3.5.1
 * + TS 3.3.3
 */
export interface CreateResult {
    contributors : (
        & {
            someType : string,
        }
        & {
            subObject : (
                | (
                    & {
                        someId : number,
                        prop0 : number,
                    }
                    & {
                        THIS_IS_REQUIRED_WHEN_SOME_ID_IS_SET : "BUT IT IS NOT SET",
                    }
                )
                | {
                    someId? : undefined,
                    prop0 : number,
                }
            ),
        }
    )[];
}

function foo (arg : { someType : string, subObject : { prop0 : number } }) {
    if (Math.random() > 0.5) {
        return arg;
    } else {
        const subObject = {
            someId : 0,
            prop0 : 0,
        };
        /*
            Expected and Actual are the same.
            {
                someType: string;
                subObject: {
                    someId: number;
                    prop0: number;
                };
            }
        */
        const result = {
            ...arg,
            subObject : {
                ...subObject,
            },
        };
        return result;
    }
}

/*
    Expected:
    | {
        someType: string;
        subObject: {
            prop0: number;
        };
    }
    | {
        someType: string;
        subObject: {
            someId: number,
            prop0: number;
        };
    }

    Actual:
    {
        someType: string;
        subObject: {
            prop0: number;
        };
    }
*/
const wtf = foo({
    someType : "",
    subObject : {
        prop0 : 0,
    }
});

/**
 * It is now possible for `wtf` to have `someId` be `number`,
 * but `THIS_IS_REQUIRED_WHEN_SOME_ID_IS_SET` is not set.
 */
const x : CreateResult["contributors"][number] = wtf;
```

**Expected behavior:**

`wtf` should be a union of types.

**Actual behavior:**

`wtf` is not a union of types.

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#code/PQKhCgAIUhqSAqBlSBmAdAVnQRijeZNdDVfYcAUwA8AHAewCcAXSASwDtnLGAzAQwDGlSAGFGlftwBKlAM4BXADasA3lEibB9LozYAjBcyZzIALkgAKDZtuQAZJHV2XtufQC2lBAE9aIizlmPQ4AcwAaGxcAXyi7R2dXF0V9AHl9ACtKQVYLaySCyAAfKzjC1wSy8oL3LwBJABNzSA4FD30eSOruyFpGeloABmbW9s6qntiepMrp8oQACTqkAH1llekAUQBFAFU6rYARFYB1Bc2AORWkVIBZTbXj9aRNhGaAIgAhXbe635QLqk3i8EO8unM7FM5gBKCYFEqJCGaWqURoAfmaCg4DUovE4lAa4KRvX6QxGbQ6jCJkzhtmh1MhUWhAG0ALoAbnAsXAvCxOTYOkgvHo9Cs-EYoWaqkgKN8-maQRCERlCjSmWyuScJIGwwso0pkGihuhTiibF4VluUgAFuhGPxsZ5LCaAHyQQZYE2IlwSZgKRgcSDi0KcyGQShKOQib12bQcIIqtVZHKQAC8pu6KMazUGDKSfR1ObzmmioaSoFpmk2dA1BKD2MgAEEcgp+EogxJIMxrSI5PwvOhKxm5rK-JRAsFOCGh3YUulk8wLDGR55UQ09RSeGXiQWhhuxoxt5MjwUoa4QBQCnGExJFCo08Pyuhn8Hi8lVfONVKZ7Zn+g5+qORvpCb6lhMvr+oGt7KMwR6xNyFZ2NW-g5ASZhRAiEyjv4E5KiebgfoBi6PoUu6DPulL4SWcEYSRs6rnK44ypOYRUYmn45EuQ5ZuuLSblSQ5kRRW4TGBjJRM2fptuhdjLsiDFjrhU5sQBC5cd0Ql8QebFibYsQXuA16sAA7swFrpsK9CWN62EBJA7xglEqlfup+akrq7rUvB0KcuAoAQNAkB1KwbCmBw9DGb09ByHIBhKCIwqMJAAAGpm8MlXaita-AAG4iMlPEZR0KX6jwyVdDAhisMlizrOsWx7AcmzHGclzXHcDx1E8qwghloUtPQrBRswg7QBQRmQNQzTiJIMjyDBzLvHGk5VSY7yssypWMKyD5peyQA)

**Related Issues:**

I'll keep searching but I couldn't find anything. There were a bunch with the same keywords but they seemed unrelated, focusing on literals and generics.

**Comment by AnyhowStep** [comment]
Smaller repro, `foo()` does not need to have arguments.

[Playground](http://www.typescriptlang.org/play/#code/FAUwHgDg9gTgLgAgJYDs4hgMwIYGMQIDCMI26ASiAM4CuANogN7AKsK5RoxIBGNcsKggBcCABQs2UgGQJmUhWypQAtiAAqATwgFRVONxQBzADSTFAX3MLZ8xQto8A8jwBWIXIlET7vhAB9xaz97W2CQv2U1AEkAExEEFBoVHgwzCIyECBgoCAAGBKSUtPDMhCsyxTDKv3UACWiAZQB9JubyAFEARQBVaM6AEWaAdTqOgDlmxqcAWQ7WobbGjvUEgCIAIR7V6J3GhHGnVeX1NfSatgrKgEpSv0C7C4QokDiAfgSaFFiQTFQQWLnJ7ZXIFURFVIwIGZK4ha7QqSwhDXADaAF0ANzAKzATBfTxITgITBQKDia5yawcFD6BDYGBGBAAXkpvheWh06zOd0cLncngSjz8IPyCTyCMu1gsWKkSEw4hmZAAFgA6GDYb6qMQUgB8CDyKoArBShVISHAaDAUHSGTLLggQHQqARTWxqbTeW4PIgWa7FC84mKJYoRWD9cHynbFAB6ABUdykHUg3oBdO+CAAgp4aNg6DaCHAlQQqNg1CqE2w-ZFVBptCA9AZUEYo5lPfy4KIqxkA7FwclIS2aqG+8UYIOItKK6wkVJY9G7u7ECRaAxmayIirN-TTFPnjRnF6BZ3d1JNyq296I4iI5PfObLdbl-Q4C2rDi49YkzpPADhNYHjyNYcvWzyNsY46sBenjHhkw6JP2GAQZGUr-uu-pAXWDaGM2PL7ny3owREPYjpCV5sHBEKIXct6StYWYWrmf5SFW7KYaB2FIVBHZocKOT5CRVG+DR07AHOwCLggADucDyiyJJQNqWLAHG8YILGCDRIgSBCCgUCSVkUBUFQvB0AQJIwAgAAG0mYJZCACAgSrYAAbgQlk9nZqRWZRMCWek6l8Igln1G0bSdL0-QdEMowTFMszzNEiwtCcdnaYkUCIM6cDlmp84SWACTEKQFDUM+KJrNSjaBYIaxoiiPlomuNkYkAA)

**Comment by AnyhowStep** [comment]
Interestingly enough, if you replace,

```ts
return arg;
```

with,

```ts
return {
    someType : "",
    subObject : {
        prop0 : 0,
    }
};
```

The inferred return type of `foo()` is correct.

**Comment by RyanCavanaugh** [comment]
This is normal subtype reduction - the type `T | U` when `U` is a subtype of `T` is reduced to `T` during most inference operations.

**Comment by AnyhowStep** [comment]
*Facepalms*
Right. That makes sense.

It makes for unsound code in this case but soundness was never a goal.

**Comment by AnyhowStep** [comment]
Wait, that doesn't explain why changing the return statement to a different form makes it infer the union

**Comment by jack-williams** [comment]
> Wait, that doesn't explain why changing the return statement to a different form makes it infer the union.

Maybe due to object literal freshness?

**Comment by AnyhowStep** [comment]
You're probably right but I wonder if it was a conscious decision and why. It seems like a rather obscure rule.
