### ISSUE TITLE
Readonly modifier doesn't work with type aliases for tuple or array

### ISSUE THREAD

**Issue by ikokostya** [microsoft/TypeScript#32234]
**TypeScript Version:**  3.5.1

**Search Terms:**

readonly, type alias, tuple, array

**Code**

```ts
type A = number[];
type T = [number, number];

type RA = readonly A;
type RT = readonly T;
```

**Expected behavior:**

There is no errors, like in the following example:

```ts
type RA = readonly number[];
type RT = readonly [number, number];
```

**Actual behavior:**

Compile errors:

```
test.ts:4:11 - error TS1354: 'readonly' type modifier is only permitted on array and tuple literal types.

4 type RA = readonly A;
            ~~~~~~~~

test.ts:5:11 - error TS1354: 'readonly' type modifier is only permitted on array and tuple literal types.

5 type RT = readonly T;
            ~~~~~~~~


Found 4 errors.

```

**Playground Link:**  http://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAglC8UB2BXAtgIwgJwNoF0BuAKFEigBUEpdVMcAaZdLbI408aAJTkWwgBDACYB7JABsQsEmR5V+QsZOkVCQA

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/12

**Comment by fatcerberus** [comment]
> array and tuple **literal** types

`A` and `T` are not array or tuple literals, they're type constants.  What you want is:

```ts
type RA = Readonly<A>;
type RT = Readonly<T>;
```

**Comment by ikokostya** [comment]
In the wiki `readonly` modifier is [proposed](https://github.com/microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improvements-for-readonlyarray-and-readonly-tuples) as new syntax for read-only arrays. 

With current restrictions need to mix `readonly` modifier and `Readonly` type:

```ts
type Position = [number, number];

function takeCoordinates(coords: readonly Readonly<Position>[]): void {}
```

**Comment by fatcerberus** [comment]
On the page you linked it shows that you can't use it with type aliases:
```ts
let err1: readonly Set<number>; // error!
let err2: readonly Array<boolean>; // error!

let okay: readonly boolean[]; // works fine
```

And in your example, you would still need to repeat yourself even if this were supported:
```ts
function takeCoordinates(coords: readonly (readonly Position)[]): void {}
```

**Comment by sandersn** [comment]
This is the current design. We have special syntax and semantics for these types only.
This might change in the future, but the most likely change is that `readonly` could be applied to any type.
