### ISSUE TITLE
How to merge class prototype into one object?

### ISSUE THREAD

**Issue by OnedayOf2010** [microsoft/TypeScript#32245]
Here is a test class below:
``` typescript
class Animal {
  name: string;
  constructor(name: string) {
    this.name = name;
  }
  sayHi(): string {
    return `My name is ${this.name}`;
  }
  sayHello(): string {
    return `hello`;
  }
}
```
It will compile to:

```javascript
var Animal = /** @class */ (function () {
    function Animal(name) {
        this.name = name;
    }
    Animal.prototype.sayHi = function () {
        return "My name is " + this.name;
    };
    Animal.prototype.sayHello = function () {
        return "hello";
    };
    return Animal;
}());
```

Because of "prototype" is a keywords in javascript ,  it will not uglify. Whether a complier options for tsc to merge class prototype together,  just like below:

```javascript
var Animal = /** @class */ (function () {
  function Animal(name) {
    this.name = name;
  }
  var _pro = {
    sayHi: function () {
      return "My name is " + this.name;
    },
    sayHello: function () {
      return "hello";
    }
  };
  //__extends  is typescript complie function
  __extends(Animal.prototype, _pro);
  return Animal;
}());
```

In my project, it find almost 5k words "prototype" in tsc compiler products , if I can do above , it may save many size.

**Comment by RyanCavanaugh** [comment]
Other tools depend on looking for assignments like this to do other stuff; we can't really change it. With the vanishing number of ES5 runtimes, it's not worth adding a compiler option for.

Do remember that if you're gzipping your JS, the actual cost of repeated uses of the same sequence of characters is much smaller than it might seem.
