### ISSUE TITLE
Missing generator's type parameter in functions and constructors

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#32248]
@rbuckton 

**TypeScript Version:**  master

**Search Terms:**

**Code**

```ts
export class Coroutine<T = unknown, R = unknown, S = unknown> {
  constructor(gen: (this: Coroutine<T, R, S>) => Generator<R, T, S> | AsyncGenerator<R, T, S>) {
  }
}
new Coroutine<0, 0, 1>(async function* g() {
  const a = yield 0;
  return 0;
});
```

**Expected behavior:**

Type g is AsyncGenerator<0, 0, 1>.
Type a is 1.

**Actual behavior:**

Type g is AsyncGenerator<0, 0, unknown>.
Type a is any.

**Playground Link:** 

**Related Issues:**

**Comment by rbuckton** [comment]
This is an issue with contextual typing. The contextual type from the constructor isn't flowing to the async generator.

**Comment by falsandtru** [comment]
Since the constructor has been given all type parameters the type of the parameter gen must be AsyncGenerator<0, 0, 1>. All type parameters are clearly decided. And the return type of yield must be unknown, as is defined by the context type.

**Comment by falsandtru** [comment]
Note that the type declaration for `this` doesn't affect this bug. This is one of the verbose elements for effectivity of regression tests.

**Comment by falsandtru** [comment]
Same also with functions.

```ts
export function f<T = unknown, R = unknown, S = unknown>(gen: () => Generator<R, T, S> | AsyncGenerator<R, T, S>) {
}
f<0, 0, 1>(async function* g() {
  const a = yield 0;
  return 0;
});
```

**Comment by falsandtru** [comment]
@rbuckton Why you still haven't fixed this bug?

**Comment by falsandtru** [comment]
Thanks @rbuckton !

**Comment by falsandtru** [comment]
@RyanCavanaugh Label this.
