### ISSUE TITLE
Cannot return unique symbol

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#32242]
**TypeScript Version:**  3.5.1

**Search Terms:**

function, return type, unique symbol

**Code**

```ts
const a = Symbol();
const b = Symbol();

function identity<T> (t : T) : T {
  return t;
}

/**
 * Mouseover `identity(a)`,
 * Tooltip shows,
 * 
 * ```
 * function identity<typeof a>(t: typeof a): typeof a
 * ```
 */
/**
 * Expected : typeof a
 * 
 * Actual   : symbol
 */
const actual = identity(a);
/**
 * Error
 * 
 * Type 'symbol' is not assignable to type 'unique symbol'.
 */
const expectA : typeof a = actual;

/////////////////////////////////////////////////

function giveTypeOfA () : typeof a {
  return a;
}

/**
 * Expected : typeof a
 * 
 * Actual   : symbol
 */
const actual2 = giveTypeOfA();
/**
 * Error
 * 
 * Type 'symbol' is not assignable to type 'unique symbol'.
 */
const expectA2 : typeof a = actual2;

```

**Expected behavior:**

`actual` and `actual2` should be `typeof a`

**Actual behavior:**

`actual` and `actual2` are `symbol`

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#code/MYewdgzgLgBAhjAvDAygTwLYCMQBsAUAlANwBQoksWSqmOBJppAZgK5jBQCW4MXAJgFMw3KGgA8AFQB8MfLABcMSYRhLJMAN6kYMAE6CorPWBhQyAXyYB6AFS2dtmAFkQrCIJAA3QXpgADAWFRNHw4Qn8AGkdlEDxuAAcYCAALEAB3CGiYJxj-fJi2Dm5eIJEuMXExBM9meGl5JWra+EImtBqQOrg8gpzrUjsHHJgAUQAPGs5BfjUzDpaekZiAQU5WOFxdOYg6PEcBimh4dc2aMpCwxiGY0b09ED0YmMkFmAByXew8d74IGDAIFgcAgEC4AHMwHAsLhBGYQPMah92FwAI6sOFfejvAB0B3I4GOgkmgk4KzmzS68BocFOuDIg2sTOZLNZbPZHM5zKYRU4PFM4K4PleNQA8sxyUQKQsqQhtLoDEYTPBLDZ7LcSdNZu1Ot1niM1kYzrolFj9v0CZQTkbcAAmGiC4ULcUrIhkG4jO4PJ7LEYiuGfPa4X5cf6A4GgiFQmFwqAI5rIsBojHJIO4-FHWDEqZQFb2nWLGl021kIA)

**Related Issues:** 

The very last comment of #24506 asks a question about intended behaviour but it goes unanswered.

**Comment by AnyhowStep** [comment]
The current workaround is,

```ts
const a = Symbol();

function giveTypeOfA () : { workaround : typeof a } {
  return { workaround : a };
}

/**
 * Expected : { workaround : typeof a }
 * 
 * Actual   : { workaround : typeof a }
 */
const actual2 = giveTypeOfA();
/**
 * Assignment OK!
 */
const expectA2 : typeof a = actual2.workaround;

```

[Playground](http://www.typescriptlang.org/play/#code/MYewdgzgLgBAhjAvDAygTwLYCMQBsAUAlANwBQpAZgK5jBQCW4MA5vQG4CmAKmgA4cB5CgEEYRGAC4YAbxgB3EACcA1nEUgaAE0kwofDiArwYAXxmkYMRRyhVFYGfKWr1WnQhNkT5APQAqPws-GABRAA9+Og5tKVkFFTUNMBjdfUNjbxhgoJhhOio4XEsdOOdEtyk9fnSPIJ9SUEhYOHzCgCYkFnZufSFhIjJ-QKzciAh6ZjAMDjBYAQBpAEI6hvBoGA4IjjphDsq0owRkFtt2gDp4lyTNMiA)

**Comment by RyanCavanaugh** [comment]
The uniqueness of a symbol goes away through widening.

**Comment by AnyhowStep** [comment]
Why would it widen for `foo () : typeof a` but not `foo() : [typeof a]`?

**Comment by artalar** [comment]
Sorry, but Im really "Cannot return unique symbol":
```typescript
function getSymbol() {
  const uniqueSymbol: unique symbol = Symbol()
  return uniqueSymbol
}

var a = getSymbol()
// no error??
var b: typeof a = getSymbol()
```

**Comment by coreh** [comment]
I know this ticket is closed and marked as "Working as Intended", but IMO the current behavior makes it a bit harder than necessary to create custom Unit types that are guaranteed to not clash with `string`/`number` literals and "survive" being passed through generic function calls without getting widened to just `symbol`.

I'm using @AnyhowStep's tuple "boxing" workaround for now (thanks for pointing that out!) but I would like to ask if y'all could reconsider, and change the `unique symbol` widening behavior to be the same as the one used for `string`/`number` literals.

I'm not sure if doing so could have additional implications to the type system... (Maybe something breaks because of it?) In that case, perhaps we could maybe opt out of the widening behavior via the `unique` type modifier?

```typescript
function identity<T> (t : T) : unique T {
  return t;
}
```

**Comment by RyanCavanaugh** [comment]
It's confusing to allow this because it's unclear if `: unique T` means "Returns the *same* unique symbol each time" or "Returns a *new* unique symbol each time".
