### ISSUE TITLE
Why is ProxyHandler set returns a boolean?

### ISSUE THREAD

**Issue by totszwai** [microsoft/TypeScript#32252]
According to MDN web docs, the handler `set` is not supposed to/don't need to return anything?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set

Why is the ProxyHandler's `set` expected to return a `boolean`?
https://github.com/microsoft/TypeScript/blob/e8bf9584aa74aabfecb51a02edb13e3657508274/src/lib/es2015.proxy.d.ts#L9

Using the latest typescript 3.5.2, I am getting this error:

![image](https://user-images.githubusercontent.com/4440365/60673585-12186a00-9e46-11e9-9a78-7be92f80b732.png)

Workaround is to just return true, but I think `ProxyHandler` should return `void`?

**Comment by j-oliveras** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set#Return_value

**Comment by totszwai** [comment]
Ah my bad.

**Comment by totszwai** [comment]
Wait... The keyword here is **SHOULD**.

> The set method should return a boolean value. Return true to indicate that assignment succeeded. If the set method returns false, and the assignment happened in strict-mode code, a TypeError will be thrown.

So we should not enforce it with a `boolean`, but perhaps a `boolean | void`

**Comment by j-oliveras** [comment]
If the script is in strict mode and you returns nothing or undefined, it throws a TypeError exception. Try running this script on node:

```js
"use strict";
var p = new Proxy({}, {
    set: function(target, prop, value, receiver) {
      target[prop] = value;
      console.log('property set: ' + prop + ' = ' + value);
    }
  })
  
  console.log('a' in p);  // false
  
  p.a = 10;               // "property set: a = 10"
  console.log('a' in p);  // true
  console.log(p.a);       // 10
```

Basically, in strict mode, **must** return true is succeeded.

**Comment by RyanCavanaugh** [comment]
TypeScript's *job* is to enforce the "SHOULD" aspects of JavaScript
