### ISSUE TITLE
Mapped type can't infer property types from `this`

### ISSUE THREAD

**Issue by kolodny** [microsoft/TypeScript#32258]
**TypeScript Version:**  3.5.1

**Search Terms:** mapped this

**Code**

```ts
export class MyClass {
  constructor() {
    getMethod(this, 'logoff') // Error
    getMethod(this as MyClass, 'logoff') // OK
  }

  logoff() {}
}

function getMethod<T, K extends keyof T = keyof T>(
  object: T,
  method: T[K] extends Function ? K : never,
) {
  return object[method];
}
```

**Expected behavior: ** Both lines in the constructor should be OK

**Actual behavior:** The first line is an error

**[Playground Link](https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAYwDYEMDOa4FkCeBhVDOAbwCg5EIA7NGKAVwRmgAoBKE8iuAc2Biz8AFhAAmLGEICWaADRwA5Egg8IAMzUKOAem1wAolCjQuFPgOFiJ0zOmz5CcxctUatcXXADyAaS4BfUi4XdTV2EkDA0jV6KiYpal5+QUkxAB4AFXkfOFAYYCpRTABrYBx1OAy4AF44UvK1SoA+Fi4IACMAK2AmAC5K2S4AW0tRfoyAbR8AXVyQfMLMADFY+MSAfjgc-qpgADdgKEGOMgoofnooKjgO7qYJkdTRaYBuUkCgA)**

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is just a case of `getMethod` being written incorrectly. Inference through conditional types is subject to a lot of constraints and should be avoided.
```ts
export class MyClass {
  constructor() {
    getMethod(this, 'logoff') // OK
    getMethod(this as MyClass, 'logoff') // OK
    getMethod(this, 'logon') // OK
    getMethod(this, 'blah') // Error
    getMethod(this, 'prop') // Error
  }

  logoff() {}
  logon() {}
  prop = 10;
}

function getMethod<T, K extends keyof T>(object: Record<K, Function>, method: K) {
  return object[method];
}
```

**Comment by JPtenBerge** [comment]
This issue has not been resolved and, in my opinion, should not have been labeled as a question. It's a bug.

@RyanCavanaugh
