### ISSUE TITLE
Improve Promise constructor return type

### ISSUE THREAD

**Issue by fregante** [microsoft/TypeScript#32254]
I tried looking for this, but didn't find anything related to it.

## Search Terms

new promise constructor return type generic inferred

## Suggestion

Currently: 
```ts
const promised4 = new Promise(resolve => resolve(4));
// typeof promised4 === 'Promise<unknown>'
// it should be `Promise<4>'
```

You can already use the generic for this, but this can be automated.

```ts
const promised4 = new Promise<4>(resolve => resolve(4));
// typeof promised4 === 'Promise<4>'
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code

Note: it would be a good break because Promises become typed.

* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by bfred-it** [comment]
It looks like the type should to that already, but I'm testing on 3.6.0-dev.20190704 and `Promise` needs the `<4>` assignment.

https://github.com/microsoft/TypeScript/blob/e8bf9584aa74aabfecb51a02edb13e3657508274/lib/lib.es2015.promise.d.ts#L33

You can also replicate the issue on the repl: https://www.typescriptlang.org/play/#code/MYewdgzgLgBAtgUwhAhgcwTAvDMCDuMACgE4hwCWECAFCUiADYBumWAfDPRE6zQCwBKQUA

But strangely the definition is different

<img width="582" alt="" src="https://user-images.githubusercontent.com/1402241/60681502-16826880-9ec2-11e9-8585-a2f746390c42.png">

**Comment by fatcerberus** [comment]
This is a known limitation of the type inference machinery - it can't infer the promise's `T` from the call to `resolve()` (i.e. the contents of a callback don't contribute to type inference).  For `new Promise` you unfortunately do have to provide the type of the promise explicitly.

**Comment by bfred-it** [comment]
That's weird, I'm almost pretty sure I did that once: https://github.com/bfred-it/webext-options-sync/blob/cbf837e6b2bd93e0e39fe0d43a8b47cdde9e53fd/source/index.ts#L60-L78

(The types for that function ultimately failed because I couldn't type `args` correcly.)

**Comment by fatcerberus** [comment]
I think that works just because `Promise<unknown>` is assignable to `Promise<TVal>` via covariance - and you don’t do anything else with the promise before returning it so you didn’t notice the too-wide inference.

**Comment by RB-Lab** [comment]
I faced another problem with generic promises:
```ts
const message = new Promise<4>(resolve => resolve()) // Promise<4> ! but in fact it is Promsie<void>!
```
