### ISSUE TITLE
Compiler API: Make Node.symbol non-internal

### ISSUE THREAD

**Issue by marijnh** [microsoft/TypeScript#32262]
## Suggestion

It seems hard to use `getExportsOfModule` (which takes a symbol) in external code if the `symbol` property of `SourceFile` (inherited from `Node`) is marked as `@internal`. Is there a reason `Type` object's symbols are accessible externally, but not those of `Node` objects? Or is there some other way to get at a `SourceFile` symbol?

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AviVahl** [comment]
const moduleSymbol = typeChecker.getSymbolAtLocation(sourceFile);

**Comment by marijnh** [comment]
Thanks!
