### ISSUE TITLE
How to use `resolveJsonModule` flag without emitting `.json` files?

### ISSUE THREAD

**Issue by siarhei-murkou** [microsoft/TypeScript#32268]
I need to have following structure (previously I have had it, before updating of `tsconfig`):
- app (folder which includes only ts files)
  - ...
    - *.ts
- dist (output for js files as compiled ones)
  - ...
    - *.js
- data (folder for any data which is not a code)
  - data1.csv
  - data2.json
  - ...

Updated `tsconfig.json`:
```
{
  "include": [
    "app"
  ],
  "compilerOptions": {
    ...
    "outDir": "dist",
    "resolveJsonModule": true,
  }
}
```

**Before:** When I didn't use `resolveJsonModule` flag , all data (all `ts` files) has been compiled and moved into `dist`

**Now:** When I'm adding `resolveJsonModule` flag, `dist` contains `app` folder where are located compiled JS files + contains `data` folder (containing json files)

**Question:**
_How can I stay with previous logic, when json files were not being moved into output?_

**Comment by RyanCavanaugh** [comment]
There currently isn't an option do that

**Comment by siarhei-murkou** [comment]
@RyanCavanaugh Which milestone (or TypeScript version) are you going to implement this feature at?

**Comment by RyanCavanaugh** [comment]
That isn't currently a planned feature. You should log a feature request issue if you'd like it to happen.
