### ISSUE TITLE
Recursive type shouldn't typecheck but it does

### ISSUE THREAD

**Issue by martinbooth** [microsoft/TypeScript#32279]
**TypeScript Version:**  3.5.1

**Search Terms:** Recursive Type Indexer

**Code**
```ts
type RecursiveType =
  | { [x: number]: string }
  | { [x: string]: RecursiveType };

const X: RecursiveType = {a:1};
```

**Expected behavior:**

This should fail to typecheck. `1` is not a subtype of `{ [x:number]: string}`, or if it is then `const X: RecursiveType = 1;` should typecheck, but it doesn't

**Actual behavior:**

The code typechecks

**Playground Link:** 

http://www.typescriptlang.org/play/#code/C4TwDgpgBAShDGBXATgZwJYDcIBVzQF4AoKKAHygG8oBtADwC4oA7RAWwCMJkBdJ1YMnTMA5lAC+JclVqMoAoaL6wEKDNjyQJAbiJF4Ae2YCoADSZwkaLLnxQCVAIYMAjOO1A

and equivalent code in flow which does the expected thing:

https://flow.org/try/#0C4TwDgpgBAShDGBXATgZwJYDcIBVzQF4AoKKAHygG8oBtAO0QFsAjCZAXQC4pVhl06AcygBfEuSq1e-IV1gIUGbHkiiA3ESLwA9nV5QAGtzhI0WXPigEqAQ04BGEWqA

**Comment by RyanCavanaugh** [comment]
Correctly errors now
