### ISSUE TITLE
Boolean type property access is not expanded into true | false in a conditional type.

### ISSUE THREAD

**Issue by calebmer** [microsoft/TypeScript#32274]
**TypeScript Version:**  3.5.1

**Search Terms:** boolean, property

**Code**

```ts
type MyOptions = {
  foo: boolean;
};

type MyType<Options extends MyOptions> = Options["foo"] extends true ? number : string;

declare const a: number | string;
const b: MyType<MyOptions> = a;
```

**Expected behavior:** This example should pass, `MyType<MyOptions>` should be `number | string`.

**Actual behavior:** This example fails, `MyType<MyOptions>` is `false`.

**Playground Link:** [TypeScript Playground](http://www.typescriptlang.org/play/#code/C4TwDgpgBAsiDyZgEsD2A7AzlAvFA3gFBRQBmqqAXFAEYUA2EAhugNyEC+7hoksIAFXAQAPIhQZsEAB7AI6ACbY44tFgB8uKKskBtAETlU+gLpQZcxdmAAnAK7QA-FHR2AtjQg2o1TLeToAObcChAAxvRMNtBhksBQTNSuHl5QAD5QfjYBwYSxWPE01HBCkCIqSGqYmnhM7EA)

**Related Issues:**

#30708 looks similarish. However, it is my understanding that nested union types will not be expanded when compared with a conditional. So `[boolean] extends [true]` would not be expanded to `[true | false] extends [true]` and would not be expanded to `[true] | [false] extends [true]`.

I‘d expect this example to pass since we are explicitly putting the union (in this case `boolean`) under the conditional’s test.

**Comment by calebmer** [comment]
cc @mdgozza who discovered this, I helped make a minimal repro

**Comment by jack-williams** [comment]
This is the right behaviour because `MyType` is not a distributive conditional type; `boolean extends true` will always be false as the union is viewed atomically.

It needs to be written as:
```ts
type Dist<T> = T extends true ? number : string;
type MyType<Options extends MyOptions> = Dist<Options["foo"]>;
```

**Comment by fatcerberus** [comment]
Yep, this is what the documentation means when it says distribution happens over a “naked type parameter”.  It’s also why you can easily disable distribution by writing the type as `[T] extends [U] ? ...`
