### ISSUE TITLE
Parameter not matching union type not recognized when passed by reference

### ISSUE THREAD

**Issue by mr-flannery** [microsoft/TypeScript#32270]
**TypeScript Version:**  3.3.3333, 3.4.2, 3.4.5, 3.5.2, 3.6.0-dev.20190704

**Search Terms:** union, union + object, union + object + bug

**Code**

```ts
interface A {
  a: string;
}

interface B {
  b: string;
}

const fn = (param: A | B) => param;

const obj = { a: "sdf", c: "sdf" };

fn({ a: "sd" });
fn({ b: "sd" });
fn({ a: "sd", b: "sfg" });
fn({ a: "sdf", c: "sdf" }); // this makes tsc fail
fn(obj); // this does not, but it should
```

**Expected behavior:**

`tsc` reports two errors, one for the last two lines respectively, as the parameters passed are essentially the same.

**Actual behavior:**

`tsc` only reports the second to last line as error, not the last one (or differently: if I comment the second to last line out, `tsc` does not fail, though it should)

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgILIN4ChnLgLmQGcwpQBzAbiwF8stRJZEUAhTHZAI0JLJCq16CAPYgSyGCGQBeZAAoADnChwAtoXQAfZKwCUsgHzJlqtdSyjxYZCK4ArWZjyEAREQAmMVwBpkCN09vZBoLKXkMF2R3D1cQvWpwyJ5ozziaBKwkqJjfbkCYcnTM7IJUrzyA8uCMxJB5O3tMoA

Thank you very much!

**Comment by fatcerberus** [comment]
`obj` is assignable to `A | B` by way of structural subtyping; in particular, it satisfies `A`.  Types are not closed: the error you *do* see is caused by passing in a fresh object literal with an excess property, which is checked for to catch typos and similar mistakes; it's not an actual typing violation.

I agree the error message is very misleading, see discussion starting here: https://github.com/microsoft/TypeScript/issues/32158#issuecomment-507089327

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by jcalz** [comment]
Documentation for [excess property checking](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks)

**Comment by mr-flannery** [comment]
Ah, I wasn't aware of this behavior! Thank you for the quick response!

**Comment by fatcerberus** [comment]
@mr-flannery Yeah, under structural typing, it’s the only behavior that makes sense, because otherwise you wouldn’t be able to have subclasses at all.
