### ISSUE TITLE
Is there any way to configure TypeScript differently for specific files?

### ISSUE THREAD

**Issue by jsmiith** [microsoft/TypeScript#32284]
Is there any way I can set my class file, `Client.ts`, to compile to ES6 whilst the rest compiles to ES5?

I was getting the error `Class constructor Client cannot be invoked without 'new'`, so I set out to find an answer. According to this answer, I need to set my target to es6, so I did. That meant that Node could not run my code due to the fact that it was in ES6. Apparently, Node supports ES6 classes though, so how would I go about making only that file compile to ES6?

**Comment by MartinJohns** [comment]
Kind of a duplicate of #8405 (or at least related).

**Comment by RyanCavanaugh** [comment]
Short answer is "no". Long answer is also "no" 😉

**Comment by MartinJohns** [comment]
@RyanCavanaugh Is there an answer between the short and the long one?
