### ISSUE TITLE
Cannot declare static method in interface

### ISSUE THREAD

**Issue by fmsouza** [Microsoft/TypeScript#3228]
When dealing with interfaces, I am not able to define a method as static within the interface. Example:

```ts
interface Foo{
   static bar():void;
}

class FooBar implements Foo{
   static bar():void{
      console.log("Foo bar");
   }
}
```

**Comment by danquirk** [comment]
This is by design. A class has an instance and static type introduced by its declaration. The implements clause restricts only the instance side. You should use a base class with a static or multiple interfaces for this pattern (the latter is how lib.d.ts defines many types).
