### ISSUE TITLE
describe primitive types

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#32288]
## Suggestion

```
const n :Exclude<number, object> = Object(0);// error
const o :Exclude<boolean, object> = Object(false);// error
const s :Exclude<string, object> = Object('');// error
```

## Use Cases

Currently, there is no way to limit api pass primitive value only.

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment]
That all works already:

```ts
declare function f(n: number): void;

// Argument of type 'Number' is not assignable to parameter of type 'number'.
//  'number' is a primitive, but 'Number' is a wrapper object. Prefer using 'number' when possible.
f(new Number(5));
```

The problem you're hitting is this overload declaration:

```ts
interface ObjectConstructor {
    (value: any): any;
}
```

More specific overloads could be added to `ObjectConstructor`.  My guess is there's not much demand for it?  It's certainly an odd thing to see in code.

**Comment by LongTengDao** [comment]
@nmain Thank you!

`new Number` is warned by my IDE, so I use `Object` which also shorter. That makes me didn't notice that `ObjectConstructor` made output `any`.

Then this feature request should be changed as you said, just more specific overload add to `ObjectConstructor`.

**Comment by RyanCavanaugh** [comment]
If you want a function that only takes primitives, you can just list them (there aren't many). If that's not what you're looking for, the suggestion is not phrased clearly enough to be actionable
