### ISSUE TITLE
Global Types from scoped packages are not automatically picked up without VSCode restart.

### ISSUE THREAD

**Issue by bd82** [microsoft/TypeScript#32285]
**TypeScript Version**
One used in TS-Server running in VSCode 2019 June release.

**Search Terms:**
I've looked at open issues topics names in:
- "typeRoots"
- "node_modules"
- "global types"

There are a great many of these, so perhaps I've missed a relevant existing issue 😢 

**Code**

Full reproducible repo is available here:
- https://github.com/bd82/bug_ts_server_scoped_global_types

It seems that TS-Server does not track changes to in the node_modules directory under certain conditions:

Specifically when using **scoped** npm package (not @types scope) which export d.ts files
with **global** signatures.

So this means VSCode has to be restarted after the initial `npm install` in a new
project using such types packages.

I do not think this is a VSCode issue because I have found some workarounds
by modifying the tsconfig.json compiler options. (See repo linked above for details).

I am not sure if the types I am using are in a scoped package is relevant to the issue
or if it simply the fact they are not provided in @types scope.

The fact these types are **global** seems to be a major contributing factor
because if I modify the project to have some kind of explicit import (even for other packages!) e.g:
- triple slash type directive.
- commonjs require

Then the problem is "resolved", except that when dealing with global types
these explicit imports should not be needed.

**Expected behavior:**
Types referenced by the `types` property in tsconfig.json should be automatically made available
to the language server once `npm install` is executed and node_module folder is created.

**Actual behavior:**
A restart of the language server (via VScode restart) is needed for new **global** types provided in
none @types **scoped** packages to become "available" after `npm install` is executed.

**Comment by RyanCavanaugh** [comment]
@sheetalkamat I believe this is one of our intentional perf trade-offs?

**Comment by LeeCheneler** [comment]
I'm currently suffering with this too and struggling to resolve it. I have a package and I want it to provide some global types when installed but I can't for the life of me get them to be found by the compiler 🤔

**Comment by bd82** [comment]
Hello and thanks for the fix 👍 

I think the fix is already in TypeScript 3.7, not in the future 3.8
- https://github.com/microsoft/TypeScript/blob/release-3.7/src/compiler/resolutionCache.ts#L673
