### ISSUE TITLE
Is it possible to add some reference to a type definitions file to the original source code?

### ISSUE THREAD

**Issue by rfgamaral** [microsoft/TypeScript#32286]
Imagine a CSS Modules class like this:

**styles.css:**

```css
.title {
    color: green;
}
```

I'm using a plugin for my bundler that will generate this type definitions file:

**styles.css.d.ts:**

```ts
declare const styles: {
  readonly "title": string;
};
export = styles;
```

Now I can do this:

**application.ts:**

```ts
import styles from './styles.css';
console.log(styles.title); // output css modules generated class name
```

My question is, is there any kind of reference I could place before the `readonly "title": string;` line to tell TypeScript "hey, that `title` property is located on file `styles.css` at line 1" so that when Alt+Click the `styles.title` reference I can go to `styles.css` instead of `styles.css.d.ts`?

**Comment by RyanCavanaugh** [comment]
TypeScript supports source maps and will follow them if it finds one for a `.d.ts` file.

**Comment by rfgamaral** [comment]
@RyanCavanaugh 

Thanks, exactly what I was looking for. However, since my `.d.ts` files are created manually (not by TypeScript compiler), can you point me to any resource explaining how to manually create source maps?

**Comment by RyanCavanaugh** [comment]
Source maps are a quasistandard maintained by Google and others. You can try the  https://github.com/mozilla/source-map library as a starter

**Comment by rfgamaral** [comment]
Thank you :)
