### ISSUE TITLE
Add a 'Replace unused destructured parameter with _' quick fix

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#32297]
From https://github.com/microsoft/vscode/issues/76583

**TypeScript Version:**  typescript@3.6.0-dev.20190704

**Search Terms:**
- quick fix
- remove destructuring
- parameter
- function

**Code**

```ts
function f({x}, y) { return y; }
```

Trigger quick fixes on `{x}`

**Bug:**
A quick fix which removes the destructing is returned, but there is no quick fix to convert the first paramter to a `_`. Replacing a parameter with `_` is available for normal parameters:

```ts
function f(x, y) { return y; }
```

**Comment by RyanCavanaugh** [comment]
@mjbvz seems like the OP is a complaint that we broke their code by observably changing the function parameter ordering

Changing `{ x }` to `_` has observable runtime effects (calling with `null` no longer throws, for example). We should change it to `{ }` and leave it alone after that; I don't see any *benefit* to changing it to `_` - it just creates new scope pollution

**Comment by infinnie** [comment]
Related: #32196

**Comment by a-tarasyuk** [comment]
```ts
function f({ x }, y) { return y; }
```
For the first parameter should be two quick-fix options
- Remove destructuring
- Remove unused declaration for: 'x'?

@RyanCavanaugh Is it true?

What about the following case?

```ts
function f({ x, x1, x2 }, y) { return y; }
```

**Comment by orta** [comment]
I think it should swap from singular to all available to remove:
 
 - Remove unused declaration for: 'x'?

to

- Remove unused declarations: 'x, x1, x2'?

and the remove destructuring should stick around
