### ISSUE TITLE
Checker API: Expose simplification of indexed access / conditional types

### ISSUE THREAD

**Issue by ulrichb** [microsoft/TypeScript#32293]
## Search Terms

conditional API checker conditional indexed infer resolve 

## Suggestion

For linting rules in ES/TSLint it would be nice to resolve/infer indexed access resp. conditional types to operate on the (by TS inferable) types.

Examples:

```ts
function exampleIdexedAccess<T extends { readonly type: string }>(
  someValue: T["type"]
): void {

  // Here I only get the type info 'T["type"]' instead of 'string':
  console.log(someValue);

  console.log(someValue.toUpperCase()); // <- TS correctly resolves 'string' internally
}

function exampleConditional<T extends {
  readonly [name: string]: string | null;
}>(someObj: T): void {

  for (const name in someObj) {

    // Here I only get the type info 'Extract<keyof T, string>' instead of 'string':
    console.log(name);

    console.log(name.toUpperCase()); // <- TS correctly resolves 'string' internally
  }
}
```

([Playground](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAUwB4EMC2AHANsgSQBM1kiBBCCZAZxoB4AVFVKZMImxAb0QCdk6IglwBPRFFHZkALkQ0ofGGADmiAL4A+ABQBYAFCJ5cTMgBq6XCFmJGAbQBEk6Q4C6BgJRyAbnBhEeAwMjAHoQxAAJZAFEAkQRcRVkKAkAC2QJKQzlYDhEAHJ7Jyy3fMRlBUEAuGAChSVVfJlgxAgEGjh8ADpcOBVtDtMLK2QPAG4gw1b2zuQevoGTc0trLqg4AFVsaT4AYXQaZG0PccQwxHoAWlsAZWm+AWgxflpO71o6xWUVMuU2PjAljEBnUk1AkFgCBYWDwyF2CCIMEhgNwTBYbA4XG4LQEQgSiDsgNMcnq31cJK+qkQAB9EGAQLhcBN9FpFqYAPIAIwAVnJGF5EL5-IF9C1cnxENo2mAFHSsNkkINkFzuR4RS1QuEojE4vikikoOlMtJymBcgUAKKsPjoaD0ADWyFENVsABp5JSVJpfjK2EJ4rV8qTGs0pkZpR1ur1+kTRsyNdMZbN5jH5WtNttovtDsdTucrrd7o8oM8BJH3lwg56ff8UcCpqCWQYgA))

Note that the non-simplified types mentioned above (`T["type"]` and `Extract<keyof T, string>`) can also be observed in the Playground Monaco Editor type info tool-tip.

## Use Cases

Static analysis tools which use the TS type checking API (`ts.TypeChecker`) and want to "step into" these kind of types.

## Examples

See above.

=> Please expose an API (within `ts.TypeChecker`) which allows to do this. Maybe `getSimplifiedType()` in `checker.ts`?

**Comment by ajafff** [comment]
Have you tried `getBaseConstraintOfType` or `getApparentType`?

**Comment by ulrichb** [comment]
Hi @ajafff!

`getBaseConstraintOfType()` works great. Many thanks for your support!
