### ISSUE TITLE
Typescript compiler allows me to use non-existent getter

### ISSUE THREAD

**Issue by mertdeg2** [microsoft/TypeScript#32302]
**Code**

```ts
class Foo {
  constructor() {
    const x = this.bar;
  }
  set bar(value: boolean) {

  }
  //get bar() {
    //throw new Error('error');
  //}
}
const y = new Foo();

```

**Expected behavior:**
The code above doesn't compile

**Actual behavior:**
The code above compiles

This might be a duplicate bug, sorry I couldn't find anything that resembles this.

**Comment by RyanCavanaugh** [comment]
Please search before logging new issues. #11596

**Comment by mertdeg2** [comment]
Thanks! Sorry about that.

For more context:
We were trying to refactor `@Input() type` to `@Input() set type`, forgot to change all `this.type` instances. As a result, error was hard to debug.. since `this.type` is undefined. i assumed  that would be a compile time error..
