### ISSUE TITLE
strictBindCallApply option is missing in TypeScript playground

### ISSUE THREAD

**Issue by goodmind** [microsoft/TypeScript#32316]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** strictBindCallApply

**Code**

```ts
function foo(a: number, b: string): string {
    return a + b;
}

let a = foo.apply(undefined, [10]);              // error: too few argumnts
let b = foo.apply(undefined, [10, 20]);          // error: 2nd argument is a number
let c = foo.apply(undefined, [10, "hello", 30]); // error: too many arguments
let d = foo.apply(undefined, [10, "hello"]);     // okay! returns a string
```

**Expected behavior:**

`--strictBindCallApply` option in Playground

**Actual behavior:**

No `--strictBindCallApply` option in Playground

**Playground Link:**  http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcAUBDAXIsIC2ARgKYBOANIoTgM5SkxgDmAlLfY04gN4BQiAxKWJQQpJBkQBqKgG5eAX168ANiMSSAvMlQA6DAAcDKgJ5pwAE2LBGxC5QDaARgAMAXRazB3nwID0fohkpHCkOFCoyMQA7hqkTARgUDSq6oSI2ihw+kam5mBWNmB2jq6UAEzunr7eAUGkIWGI5QVxCfjESYgwNBq4BCSkqVCIEBk62YbGZpbWtvaIzi6UAEQAFsQqKnArlADMVV51waHhkfgYYCZtBJ3Jw4gW41k50-mF86XLiOub2yseLy1QJwADWGBMAEIhCIxGBepI6AxmEA

**Related Issues:**

**Comment by jcalz** [comment]
I filed this in orta/typescript-play#11 a few days ago, but I'm not sure if there or here is the right place for Playground issues.  Either this issue or that one is a duplicate, I guess.

**Comment by orta** [comment]
I've created this issue on the website, so this can be closed https://github.com/microsoft/TypeScript-Website/issues/12
