### ISSUE TITLE
Where can I find release notes for 3.5.3?

### ISSUE THREAD

**Issue by cekvenich** [microsoft/TypeScript#32310]
eom

**Comment by sandersn** [comment]
3.5.3 isn't released yet and we didn't finalise what is in it until yesterday. Should be soon.

**Comment by sandersn** [comment]
My mistake, looks like @DanielRosenwasser released it last night. Daniel, when and where will the 3.5.3 release notes be?

**Comment by DanielRosenwasser** [comment]
[Available now](https://github.com/microsoft/TypeScript/releases/tag/v3.5.3)
