### ISSUE TITLE
A debugger was left in debug.ts

### ISSUE THREAD

**Issue by dye784** [microsoft/TypeScript#32313]
**TypeScript Version:**  3.6.0

**Search Terms:**
debugger
debug.ts

**Code**
`src/compiler/debug.ts`
```ts
        export function fail(message?: string, stackCrawlMark?: AnyFunction): never {
            debugger;
            const e = new Error(message ? `Debug Failure. ${message}` : "Debug Failure.");
            if ((<any>Error).captureStackTrace) {
                (<any>Error).captureStackTrace(e, stackCrawlMark || fail);
            }
            throw e;
        }
```

**Expected behavior:**
No debugger to be hit

**Actual behavior:**
Debugger is hit

**Comment by fatcerberus** [comment]
Given the nature of the function and the error message "Debug Failure", I'm thinking that's probably intentional.

**Comment by ajafff** [comment]
> that's probably intentional.

But it shouldn't be executed unless there's something wrong. However, this needs a repro to be actionable. The exact message and stack trace would also help

**Comment by fatcerberus** [comment]
Right, but it seemed like the issue was just about the `debugger;` statement being *there* (“a debugger was left in...”), which doesn’t look like a mistake to me.  It’s kind of ambiguous though.

**Comment by dye784** [comment]
Sorry should've been more clear. The debugger was hit when I attempted to launch TestCafe with VSCode debugger. It looks like it was hit when I introduce something that fails linting.

**Comment by fatcerberus** [comment]
Yeah, that’s a bug, this is basically the “internal error” code path.  If you could come up with a minimal reproduction that would probably help narrow down what’s going wrong.

**Comment by DanielRosenwasser** [comment]
Please open up a follow-up issue with a minimal repro.
