### ISSUE TITLE
TS5024: Compiler option 'target' requires a value of type string.

### ISSUE THREAD

**Issue by slavafomin** [microsoft/TypeScript#32317]
Hello!

Thank you for you hard work!

I'm trying to configure the compiler in JavaScript using it's API:

```typescript
import { CompilerOptions, ScriptTarget } from 'typescript';

const compilerOptions: CompilerOptions = {
  target: ScriptTarget.ES2015,
};
```
However, the `ScriptTarget` enum is exported like this from `typescript.d.ts`:

```typescript
enum ScriptTarget {
    ES3 = 0,
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES2017 = 4,
    ES2018 = 5,
    ES2019 = 6,
    ES2020 = 7,
    ESNext = 8,
    JSON = 100,
    Latest = 8
}
```

So, it gets evaluated to: `{ target: 2 }` instead of `{ target: 'ES2015' }`. And raises an error when this config is read by the compiler: `TS5024: Compiler option 'target' requires a value of type string.`.

And if I do set it to a string value:

```typescript
const compilerOptions: CompilerOptions = {
  target: 'ES2015',
};
```

I'm getting yet another error: `error TS2322: Type 'string' is not assignable to type 'ScriptTarget | undefined'.`.

**Comment by RyanCavanaugh** [comment]
More info would be needed. It sounds like you're trying to pass this `compilerOptions` value to an invalid function (e.g. trying to re-parse it)

**Comment by slavafomin** [comment]
I guess you are right @RyanCavanaugh, I'm passing options to the `ts-loader` for Webpack. Looks like they incorrectly typed their interface. Sorry for disturbance. I'm going to raise the issue there.
