### ISSUE TITLE
Narrowing doesn't work

### ISSUE THREAD

**Issue by xahon** [microsoft/TypeScript#32320]
**TypeScript Version:**  3.5.3

**Code**
```ts
validate: (actualValue: string | null): string | null => {
    if (isNullOrEmpty(actualValue)) {
       return "Value is required";
    }

    // Error here. TS2531. Value must be narrowed to `string`
    if (actualValue.length !== uuidPattern.length || 
        sanitizeUUID(actualValue) !== uuidPattern) {
        return "Doesn't match regular uuid pattern";
    }
    return null;
}

export const isNullOrEmpty = (str: string | null): boolean => {
  if (str == null) {
    return true;
  }
  return str.replace(/\s/g, "").length === 0;
};
```
If you inline check it will work as expected. See playground link below for examples

**UPD**
Same thing in chained methods
![image](https://user-images.githubusercontent.com/18731681/60940712-c96a2080-a31f-11e9-97de-d33571d30191.png)

**Expected behavior:**
no error of course

**Actual behavior:**
weird error

**Playground Link:** 
[playground](http://www.typescriptlang.org/play/#code/MYewdgzgLgBAbgQwDYEsAmCoFMYF4YAUCwUArsgGrKlYBcM0ATimAOYwA+MYpSSAlPSYt2XHnzwA+GAG8AUDBgoAZoRQQAcryQB5RgFEAtgAcoATyIlySKkhr9+shYpiMsZRmBgAiWzSUQrlgAjqQobmjeANzOAL5yzgD0iTD6jIwgjDAAFlhuAHQwACoAygBMAKwAzACMhX44hqTQMABGOGAI6SAA7lhoMFAgMAAGwmwjSSkuihxTM4oUigD1ADoA+gSAIwz864nLziqExGSU1Fj5SFhsUNkwAIS4+KRhaAAKmNiel9est5xzBYMBBgFBQFAALywAFVoQBJAAillONnOjkez1eHygXzAjmc8hmbg8Xm8CJAWAgYAA5LBDJhgHc3KxeF0YC90DBjJ88mBonFnMTSJ5uNoYrEYnJQJBYIhUBhsHCwKgwP0AMK5YAAazwxysZzsdAYUGYbE4or4gmNptEFqQUiciiOyOsDTw+HE9o4XBOrvO+TcxiQxCwBESqwgiVYABofN5+D8bncnvgAAyOQkuIUi3znAJBULhfr8xTxeZq8AQdB5bhdDI9ETzBaAmDJIFLQgwQCGwAAGmCAHWBAGlA3Z7-EOqhdBpoib+dwx7KxPO+VyTAOcMwgILBkJh8KRvqnWHRTwX6GxuLHikzimzpPJlJpdIZTKwLODWQ5A25ON5JZgZZvdxhS8T1xUlLAAA9jEyWBpRadQtD4PQjFMMxdQIJghBNERzU9K1WhAEArhBB1M1va13TtAFrQDLAgxDMMIyjWNvHjGd-hTGBUzAuQgA)

**Related Issues:**

**Comment by MartinJohns** [comment]
Your `isNullOrEmpty` function returns `boolean`. It does not tell the compiler anything about what the type of `str` is. What you are looking for is a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards). Change the return type of `isNullOrEmpty` from `boolean` to `str is null` and it will work. That syntax tells the compiler that the function can be used to narrow the type of the argument.

**Comment by xahon** [comment]
@MartinJohns I don't get the idea of type guard and why ts compiler cannot narrow type itself like rust compiler does?
