### ISSUE TITLE
`__proto__` as a computed property shouldn't set the prototype

### ISSUE THREAD

**Issue by mgol** [microsoft/TypeScript#32327]
**TypeScript Version:**  3.6.0-dev.20190710

**Search Terms:**

- `__proto__ computed`
- `__proto__ object literal`

**Code**

```ts
console.log(
  Object.getPrototypeOf({['__proto__']: []}) === Object.prototype
    ? 'PASS'
    : 'FAIL'
);
```

**Expected behavior:**

Compiled code should log `PASS`.

**Actual behavior:**

It logs `FAIL`. This is because it's compiled to a direct assignment to the `__proto__` property while the spec says a `__proto__` property should result in calling `[[SetPrototypeOf]]` only if it's not a computed property:
https://www.ecma-international.org/ecma-262/9.0/index.html#sec-__proto__-property-names-in-object-initializers

**Playground Link:** (press `RUN` & see `FAIL` in the console) https://www.typescriptlang.org/play/?target=1#code/MYewdgziA2CmB00QHMAUB5ARgK1sALvMrPgAoBOI+VAngA6zoBmqA3gNoDkA+t3ZdV6cAugC4ABO2EBfAJTiAvEvFZcBePyq0G4gPzjOpAIIBlE53ETOAMSMBJADKdZAbgBQQA

**Related Issues:** #13668

**Comment by nmain** [comment]
Babel seems to have the same issue:

https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUB5ARgK1sALvMrPgAoBOI-VAngA6zoBmqA3gNoDkA-t3ZdV6cAugC4ABO2EBfAJTiAvEvFZcBePyq0G4gPzjOpAIIBlE53ETOAMSMBJADKdZAbgBQQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.5.4&externalPlugins=

**Comment by RyanCavanaugh** [comment]
I don't see how we would reasonably fix this. You could equally have written an obfuscated version:
```ts
let m = '__PROTO__'.toLowerCase();
console.log(
  Object.getPrototypeOf({[m]: []}) === Object.prototype
    ? 'PASS'
    : 'FAIL'
);
```
This implies that *all* computed property names would have to go through some complicated helper process to detect `__proto__` and work around it.

Unless there's some non-adversarial scenario here I'm missing, this isn't worth the cost.

**Comment by mgol** [comment]
There's one potential security issue from the current behavior. Imagine converting a a user-provided string to an object representing key & value where value is wrapped with an array (e.g. `key=value` to `{key: ["value"]}):
```ts
const toKeyValue = (input: string) => {
  const pair = input.split('=');
  return {
    [pair[0]]: [pair[1]],
  };
}
```
That function, when called on `'__proto__="val"'` will produce a regular object when run non-transpiled while it will produce an object with a modified prototype when transpiled to ES5.

I understand fixing that would be a bigger task than fixing another open `__proto__` issue with similar security consequences: #13668.

**Comment by mgol** [comment]
@nmain Right, the Babel issue is https://github.com/babel/babel/issues/4188.

**Comment by mgol** [comment]
@RyanCavanaugh Thinking about it, what in particular would be complicated in the fix for this? Since it's only an issue for computed property names which are converted to assignments, it should boil down to comparing the property with `__proto__` & opting for `Object.defineProperty` in such a case; i.e. changing:
```js
var _a;
/* ... */
return (_a = {},
    _a[key] = [value],
    _a);
```
to something like:
```js
var _a;
/* ... */
return (_a = {},
    key === '__proto__'
      ? Object.defineProperty(_a, key, {
          value: value,
          configurable: true,
          enumerable: true,
          writable: true
        })
      : _a[key] = [value],
    _a);
```

**Comment by RyanCavanaugh** [comment]
"Why is my generated JS 10x larger for the sake of a property name I'm never going to set?" - everyone, immediately

**Comment by mgol** [comment]
The logic could be extracted to a helper function, then the size increase would be negligible.

**Comment by fatcerberus** [comment]
Looks like the security issue example is not to be as it gets transpiled to:
```js
"use strict";
const toKeyValue = (input) => {
    const pair = input.split('=');
    return {
        [pair[0]]: [pair[1]],
    };
};
let x = toKeyValue('__proto__="foo"');
console.log(Object.getPrototypeOf(x));  // Object
console.log(x['__proto__'] == Object.getPrototypeOf(x));  // false
```

https://www.typescriptlang.org/play/#code/MYewdgzgLgBFIGkCmBPAagQwDYFckwF4YAKASzAAccoAuGaAJ3IHMBKQgPhgG8AoGGKEiwKGUg0IxyVKADoIFLKSjEA5AVWsA3PxgMkUHAzA9dAgNqjx5gAwBdO3UtiG5gIwOANLoC+On7xYBjAAHpLwyOjYeGoA+rEUDCDw8QQARABmICBpmjpCECBBslggzMQA8gBGAFZIwHLMBgAKSfBQKBRIFRnEIazavAVFSCVlfeaq8YnJIPGqdoRE1XUNsk1QrbMdXT19AzpAA

**Comment by mgol** [comment]
Lodash internally uses the following helper to avoid related issues in its own APIs:
https://github.com/lodash/lodash/blob/master/.internal/baseAssignValue.js

**Comment by RyanCavanaugh** [comment]
Given the fact that Babel has had this bug sitting idle for three years with no one noticing, it's reasonably safe to take the correctness trade-off here. There's still nothing we could do for ES3, and ES5 targets are getting quite rare relative to ES6.

**Comment by mgol** [comment]
Most apps I dealt with still compile to ES5 to support IE 11, I don't see it getting rare at the moment. Another reason to compile to ES5 is minification as UglifyJS only supports ES5 & ES6-compatible solutions are less stable.

I understand your point, though; thanks for the consideration.

**Comment by joepie91** [comment]
FYI, this has been [fixed in Babel](https://github.com/babel/babel/pull/12664) since.

(I ran across this issue while investigating whether this is still an issue in widespread implementations, since the code I'm auditing would be affected by this from a security perspective.)
