### ISSUE TITLE
Object.keys should return `keyof T`

### ISSUE THREAD

**Issue by bfred-it** [microsoft/TypeScript#32321]
**TypeScript Version:**  3.6.0-dev.20190717

**Code**

```ts
const feature = {
	description: '',
	screenshot: '',
	disabled: ''
};

const list = Object.keys(feature);
```

**Expected behavior:**

```ts
keys<T extends object>(o: T): Array<keyof T>;
```

```ts
typeof list = Array<"description" | "screenshot" | "disabled">
```

**Actual behavior:**

```ts
keys(o: {}): string[];
```

```ts
typeof list = string[]
```

**Workaround:**

```ts
const feature = {
	description: '',
	screenshot: '',
	disabled: ''
};

const list = Object.keys(feature) as Array<keyof typeof feature>;
```

**Playground Link:** https://www.typescriptlang.org/play/#src=const%20feature%20%3D%20%7B%0D%0A%09description%3A%20''%2C%0D%0A%09screenshot%3A%20''%2C%0D%0A%09disabled%3A%20''%0D%0A%7D%3B%0D%0A%0D%0Aconst%20keys%20%3D%20Object.keys(feature)%3B

**Comment by j-oliveras** [comment]
Already rejected multiple times, search for Object.keys

**Comment by AnyhowStep** [comment]
`Object.keys()` does not return `(keyof T)[]` in the general case.

In some specific instances, it will. In most others, it will not.

```ts
declare const x : { a : number };
Object.keys(x);
```

You might expect the above to return `["a"]` but it's possible for it to return `["a", "b"]`, too.

Because `{a: number, b: number}` is assignable to `{a: number}`

**Comment by MartinJohns** [comment]
Duplicate and rejected multiple times: https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208, #30314, #13254. #30228, #28899, #28284, #26901, #30749, #31087.

[more info](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript)

**Comment by RyanCavanaugh** [comment]
Maybe we should make a template just for this. It'd save people a lot of time.

**Comment by MartinJohns** [comment]
@RyanCavanaugh I actually just copied my last comment and added the other issue. But this is a good candidate for the FAQ (but I doubt it's being checked before).

**Comment by bfred-it** [comment]
It’s because it sounds so obvious that I just checked the open issues before opening this one 😅 Nobody expects `keyof` to be different from `keys()`
