### ISSUE TITLE
error TS6054: File 'tsconfig.json' has unsupported extension.

### ISSUE THREAD

**Issue by wzup** [microsoft/TypeScript#32323]
### TS doesn't recognize `.json` extension for `tsconfig.json` file in CLI

**TypeScript Version:** 

```json
  "dependencies": {
    "@types/react": "^16.8.22",
    "@types/react-dom": "^16.8.4",
    "typescript": "^3.5.2"
  }
```

**Search Terms:**

1. error TS6054: File 'tsconfig.json' has unsupported extension.
2. error TS6054: File 'tsconfig.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

**Code**

My `tsconfig.json` file. It resides in app root folder. 
Please pay attention it is `.json` file.
```ts
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext",
      "es2015"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "sourceMap": true,
    "baseUrl": "./",
    "jsx": "preserve"
  },
  "include": [
    "./**/*",
    "*.tsx"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}

```

**Expected behavior:**

When I compile a file AND provide a config file, I expect it to be compiled according to TS config provided (`--project tsconfig.json`):

```bash
$ npm run tsc Classes.ts --project tsconfig.json 
```

**Actual behavior:**

TS throws error:
```
$ npm run tsc Classes.ts --project tsconfig.json 

> ts@1.0.0 tsc /Users/sergey/sbox/ts
> tsc "Classes.ts" "tsconfig.json"

error TS6054: File 'tsconfig.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

Found 1 error.
```

**Playground Link:** 

**Related Issues:** 

https://github.com/s-panferov/awesome-typescript-loader/issues/129
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29172#issuecomment-499970369

**Comment by MartinJohns** [comment]
> When I compile a file AND provide a config file, I expect it to be compiled according to TS config provided (--project tsconfig.json):

This is not supported. You either use a `tsconfig.json`, or you provide the list of files to compile. Combining the two is not supproted.

From the [tsconfig.json documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

> When input files are specified on the command line, tsconfig.json files are ignored.

Providing the `--project` flag does not change this. The flag is for having differently named tsconfig files, or when the file is in another directory.

When I try to combine files and the `project` flag I actually get this error with TypeScript 3.5.3:

> error TS5042: Option 'project' cannot be mixed with source files on a command line.

**Comment by wzup** [comment]
Thanks @MartinJohns 
Your detailed explanation is very appreciated

**Comment by VictorPullzz** [comment]
THIS NOT WORK FOR ME

**Comment by junhengDeng** [comment]
> 这对我不起作用。跆拳道？ ![图像](https://user-images.githubusercontent.com/23406402/127781748-98ca8aaf-cba3-4c94-9d2b-3f12e29133c3.png) ![图像](https://user-images.githubusercontent.com/23406402/127781752-2e961716-6332-4dcb-ba2e-d13b69c6f2a2.png)

tsc -p tsconfig.json --pretty --noEmit

**Comment by junhengDeng** [comment]
> THIS NOT WORK FOR ME. WTF? ![image](https://user-images.githubusercontent.com/23406402/127781748-98ca8aaf-cba3-4c94-9d2b-3f12e29133c3.png) ![image](https://user-images.githubusercontent.com/23406402/127781752-2e961716-6332-4dcb-ba2e-d13b69c6f2a2.png)

tsc -p tsconfig.json --pretty --noEmit

**Comment by MartinJohns** [comment]
@junhengDeng You forgot the `-p`. You're writing `tsc tsconfig.json` instead of `tsc -p tsconfig.json`.
