### ISSUE TITLE
Overload resolution

### ISSUE THREAD

**Issue by ttftw** [microsoft/TypeScript#32325]
**TypeScript Version:**  3.4.0-dev.20190710

**Search Terms:** overload

**Code**

```ts
interface Emittable {
    on(event: string, listener: Function): this;
    on(event: 'ready' | 'disconnect', listener: () => void): this;
    on(event: 'messageReactionAdd' | 'messageReactionRemove', listener: (message: string, emoji: string, userID: string) => void): this;
}

const client: Emittable;

client.on('messageReactionAdd', () => {});
```

**Expected behavior:** TS to detect the types from the declared interface based on signature.

**Actual behavior:** When `on(event: string, listener: Function)` is declared first, TS does not read the declared types from the interface overload for `client.on('messageReactionAdd', () => {});`, instead IntelliSense uses either the default overload, or an incorrect signature and the TS server complains about expected types.  If I move the default overload to the end of the list, TS reads the types correctly.  

This seems to be caused by having a pipe | between the expected strings in the signature.  `client.on('ready')` works fine regardless of if the default overload is listed first or not, but `'messageReactionAdd' | 'messageReactionRemove'` only works correctly if the default overload is listed last. 

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgKIFthjHARgGxQG8BYAKGWQHsQAKCANwnAC5kBnMKUAcwBpk+YJ2bQ2AMQCuIBGGA0AlGzAALYQG5ylGvSatkAIigQ4AEwCeBgUJEgxyWugjt2cHhDaduIHguQBeAD5kBipgUyVkVQ0tajpYykZmMDYDJxc3CAAlE1l5EABBU1MDZAAfQ3TXdxzEORoc9ComKwTBYUg7KDZHZ2qPDi5eAQgmgCtgTyGfAUl2aABJABEp718A4NDw2Mjo9k0yAF9ycgQaTmQEIWS2DCwcAggD0+vwADodNL7M2ryaIpKAlofiCyCIhwUByAA

**Related Issues:**

**Comment by dragomirtitian** [comment]
Overload order matters, overloads are considered in the order they appear in file with the first one that matches winning. This works as you expected it to: 

```ts
interface Emittable {
  on(event: "ready", listener: (message: string) => void): this;
  on(
    event: "messageReactionAdd" | "messageReactionRemove",
    listener: (message: string, emoji: string, userID: string) => void
  ): this;
  on(event: string, listener: Function): this;
}

declare const client: Emittable;

client.on("messageReactionAdd", () => {});
```

[Play](typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgKIFthjHARgGxQG8BYAKGWQHsQAKCANwnAC5kAiKCOAEwE92AGmT5gAZ0ghobWughixcAOYQ2EqKCUBKZAF4AfMgZVgPLWzAALcQG5ylGrXuVkjZmDbs5C5RABK3AhgwDQAgjw87MgAPhzeiioBiME0AehUTELOlKISzNLIsvIJqsjqmsIQ6QBWwGpgGiBKwgCuYtAAkgAi9Y3aeobGps7myFa2zo5urGUNFSLikgUAYi0gQSEgo+NidmQAvuTkPBAI+HBcyAg0Elei7mwYWDgEEHvkZ8DuAHSOXsW+JIbMIRISFHQGZBEfZaPZAA)

**Comment by ttftw** [comment]
I understand your code works as expected, I posted this in my original question as a solution.  But if this is the expected behavior, then why does signatures like `ready` work regardless of the location of the default overload and only signatures with pipes | fail?

**Comment by nmain** [comment]
This does seem weird.  Here's a simplified repro:

http://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEA3W8BmAueBvAsAKHkIAopMBnAFxgEsA7AcwEpMpaBPfQ+EzAIjijA2vZvFYc8AX3z4A9LPggAHgAdwFEMEwB7RCBgRtg+AEY5CqGAoBXKBB16DR4PABM+VEX4hBwxgG58IA

**Comment by ajafff** [comment]
Overloads where a parameter is a literal type are moved to the top. This doesn't include unions of literal types.

**Comment by ttftw** [comment]
Why wouldn’t this include unions? Is there some technical reason? It feels like inconsistent behavior.

**Comment by RyanCavanaugh** [comment]
"Literal signatures go to the top" was a rule that existed before union types existed. We're not super happy about the rule because it's confusing (as you can tell) and would prefer that overloads be plainly ordered by their declaration ordering, so the rule was not expanded to unions of literals.

**Comment by ttftw** [comment]
@RyanCavanaugh It makes sense to me that TS would return literals first, since it's more specific.  But I also see value in honoring the order.  I thought I found a bug, but I see now it was a conscious decision.  

Thanks for the reply.
