### ISSUE TITLE
Type inference not working in certain cases

### ISSUE THREAD

**Issue by david-cannady** [microsoft/TypeScript#32337]
**TypeScript Version:**  3.4.3

**Search Terms:**
discriminated union inference guard type
**Code**

```ts
interface TestV1 {
    version: 1;
    test: string;
}

interface TestV2 {
    version: 2;
    testProp: string;
}

type Test = TestV1 | TestV2;

const isTest = (x: unknown): x is Test => true;

const exampleFunction = (obj: any) => {
    if (!isTest(obj)) {
        throw new Error("Not of type 'Test'");
    }
    if (obj.version === 1) {
        return obj.test;
    } else {
        return obj.testProp;
    }
};
```

**Expected behavior:**
Type inferencing works appropriately and the source compiles.

**Actual behavior:**
The type of `obj` is inferred to `Test` after the `isTest()` type guard. However, compiler isn't able to infer that obj is `TestV1` on the line `return obj.test;` and complains that the property `test` doesn't exist. However, if I do the following:
```
const exampleFunction = (obj: any) => {
    if (!isTest(obj)) {
        throw new Error("Not of type 'Test'");
    }
    const testObj: Test = obj;
    if (testObj.version === 1) {
        return testObj.test;
    } else {
        return testObj.testProp;
    }
};
```
The compiler has no issues.

**Playground Link:** 
[Broken Example](http://www.typescriptlang.org/play/?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgCoQM5gGoEZkDeAsAFDLnIBu0GwA9iAFzK4DcpFykWzWUoAc3YkAvqVKhIsRCnRZsAJkIcK1KLQbMFwztzAAFKHQAOvMPxBDSYkqTABPY7MxhkAXjQu8yAD6f52uIkCAxYyMAYcq4eABQAHswAriAA1iB0AO4gAJTMceEY-tEAfFxQiRDCpCEgYRBxcAC2xgA2EABiyQhg9CDuyDF0AEYAVsxwIPbZ7qXEZBTAMAMAhBFRg6PZ03OcugAWRhnIIBBHAKJQRlAxAEQAcnSudEsOTsgA5FHvN9k6FDacRYDYYjAB0ag0fTc0JY2xUu2QUAgYESUD6INBej+5BEyAgLQwKB2CMRyNR6NGmJchhM2OQNhEwiAA)
[Working Example](http://www.typescriptlang.org/play/?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgCoQM5gGoEZkDeAsAFDLnIBu0GwA9iAFzK4DcpFykWzWUoAc3YkAvqVKhIsRCnRZsAJkIcK1KLQbMFwztzAAFKHQAOvMPxBDSYkqTABPY7MxhkAXjQu8yAD6f52uIkCAxYyMAYcq4eABQAHswAriAA1iB0AO4gAJTMceEY-tEAfFxQiRDCpCEgYRBxcAC2xgA2EABiyQhg9CDuyDF0AEYAVsxwIPbZ7qXEZBTAMAMAhBFRg6PZ03OcugAWRhnIIBBHAKJQRlAxAEQAcnSudEsOTsgA5FHvN9k6FDacGphPQAeVGzCi-WGIz+5EWA1BowAdGoNH03BiWNsVLtkFAIGBElA+oiRki9LDkCJkBAWhgUDtcXiCUSSS4wWS9IYTJSbCJhEA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #30593
