### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by oliverw** [Microsoft/TypeScript#3234]
```javascript
declare module wx {
    interface IComponentViewModelDescriptor {
        (params: any): any;
        require?: string;
        resolve?: string;
        instance?: any;
    }
    interface IComponentTemplateDescriptor {
        (params?: any): string | Node[];
        require?: string;
        resolve?: string;
        element?: string | Node;
    }
    interface IComponentDescriptor {
        require?: string;
        resolve?: string;
        template?: string | Node[] | IComponentTemplateDescriptor;
        viewModel?: Array<any> | IComponentViewModelDescriptor;
        preBindingInit?: string;
        postBindingInit?: string;
    }
    interface IComponent {
        template: Node[];
        viewModel?: any;
        preBindingInit?: string;
        postBindingInit?: string;
    }

    interface IComponentRegistry {
        component(name: string, descriptor: IComponentDescriptor): IComponentRegistry;
    }

    interface IModule extends IComponentRegistry {
        name: string;
        merge(other: IModule): IModule;
    }
    
    var app: IModule;
}

wx.app.component('state-monitor', {
    viewModel: { require: "js/components/state-monitor/ViewModel" },
    template: { require: "text!components/state-monitor/index.html" }
});
```

Compiling this with:

> node node_modules\typescript\bin\tsc repo.ts

Fails with:

> repo.ts(41,35): error TS2345: Argument of type '{ viewModel: { [x: number]: undefined; require: string; }; template: { [x: number]: undefined; re...' is not assignable to parameter of type 'IComponentDescriptor'.
  Types of property 'template' are incompatible.
    Type '{ [x: number]: undefined; require: string; }' is not assignable to type 'string | IComponentTemplateDescriptor | Node[]'.
      Type '{ [x: number]: undefined; require: string; }' is not assignable to type 'Node[]'.
        Property 'length' is missing in type '{ [x: number]: undefined; require: string; }'.

I have honestly no idea where the ...

> [x: number]: undefined

part is coming from that the compiler complains about. Unless I am mistaken this should compile just fine. Tested with 1.5 Beta.

**Comment by danquirk** [comment]
This is surely a bug. The ```undefined``` values should be widened to ```any``` before they come into view.

```ts
declare module wx {
    interface IComponentViewModelDescriptor {
        (params: any): any; // error goes away without this
        require?: string;
    }
    interface IComponentTemplateDescriptor {
        require?: string;
    }
    interface IComponentDescriptor {
        viewModel?: Array<any> | IComponentViewModelDescriptor;
    }
    interface IComponentRegistry {
        component(name: string, descriptor: IComponentDescriptor): IComponentRegistry;
    }

    interface IModule extends IComponentRegistry {
        name: string;
    }

    var app: IModule;
}

// ok
wx.app.component('state-monitor', {
     viewModel: []
});

// error
wx.app.component('state-monitor', {
     viewModel: { require: '' }
});
```

**Comment by mhegazy** [comment]
@danquirk your second example is missing the call signature, so this should be an error..

viewModel is `Array<any> | IComponentViewModelDescriptor`; `IComponentViewModelDescriptor` is expected to be a function, with an optional `viewModel` property. am i missing something here?

**Comment by danquirk** [comment]
Yeah you're right I don't know why I started looking at what was an error or not. I was just trying to narrow down the code that displays the real issue which is just the presence of ```undefined``` in the error. I was trying to see if there was some specific code related to why we weren't widening.

**Comment by mhegazy** [comment]
I believe this is the probelm:
```
interface IComponentViewModelDescriptor {
        (params: any): any;
        ...
}
```
so this is valid
```ts
wx.app.component('state-monitor', {
     viewModel: ()=>""
});
```
and this
```ts
var f = function(){};
f.require = "";
wx.app.component('state-monitor', {
     viewModel: f
});
```

but not this:
```ts
wx.app.component('state-monitor', {
     viewModel: { require: '' }
});
```

**Comment by danquirk** [comment]
Right, but the invalid cases should be saying things like:

```ts
  Types of property 'viewModel' are incompatible.
    Type '{ [x: number]: any; require: string; }' is not assignable to type 'any[] | IComponentViewModelDescriptor'.
```
not
```ts
  Types of property 'viewModel' are incompatible.
    Type '{ [x: number]: undefined; require: string; }' is not assignable to type 'any[] | IComponentViewModelDescriptor'.
```

**Comment by oliverw** [comment]
My mistake. I somehow missed the non-optional call signature.

**Comment by DanielRosenwasser** [comment]
Opening a separate issue to track the actual bug.
