### ISSUE TITLE
Inconsistent type inference for cases of one and multiple values

### ISSUE THREAD

**Issue by MJ-Max** [microsoft/TypeScript#32349]
To me it looks like tsc is able to infer the correct type in the first case as it tries hard to find a type that matches both possible return values. In the other two cases which return only one string it doesn't search and assumes the return value is a plain string, even though the intended type of the return value should indicate it is not.

**Search Terms:** Type Promise<string> is not assignable to type promise inconsistent 

**Code**

```ts

type DooDad = 'SOMETHING' | 'ELSE' ;

class Interesting {

	public compiles = () : Promise<DooDad> => {
		return Promise.resolve().then(() => {
			if (1 < 2) {
				return 'SOMETHING';
			}
			return 'ELSE';
		});
	};

	public doesnt = () : Promise<DooDad> => {
		// TS2322: Type Promise<string> is not assignable to type Promise<DooDad>
		// Type 'string' is not assignable to type 'DooDad'
		return Promise.resolve().then(() => {
		//return Promise.resolve().then(() : DooDad => { // specifying return type here fixes the issue
			return 'ELSE';
		});
	};

	public slightlyDifferentErrorMessage = () : Promise<DooDad> => {
		// TS2322: Type Promise<string> is not assignable to type Promise<DooDad>
		return Promise.resolve().then(() => {
		//return Promise.resolve().then(() : DooDad => { // specifying return type here fixes the issue
			if (1 < 2) {
				return 'SOMETHING';
			}
			return 'SOMETHING';
		});
	};

}
```

**Expected behavior:** All three functions compile and DooDad is inferred in all three cases ( alternatively, it is inferred in no case; this inconsistency is the worst case scenario IMO )

**Actual behavior:** First function compiles, the other two fail with TS2322

**Playground Link:** [here](http://www.typescriptlang.org/play/index.html#code/LAKALgngDgpgBAEQPZIQQwCZwLxwOQDKA8gLICiAKgBICSAcgOJ5wA++ZAMgWcwNyigAxgBs0AZzFwaAOzAwATjDFgAltIDmcAN4CQASCgBXAEbCVguIKQBbKCuFKccABQBKOAC44ABXk2VYjAAPMiomAB8OJE6+nqKYIby0j5+1gEwAHSKYkjCAG4wbhlgABYw0s5uUdqgenUqAGYuAIxwQXAATO4xdXXxicmEpJS0jHj8sXoAvrV9MAlJ7Fw8E3VTrqtTE7VGpuZwGEhKsk5VXr7+gSEo6BiR2NGzAPRPcBQEHQDMHR1eFNDwC5pK7KeRqdSRAJwaRIMBwcRiFTqaRoUzwMBIOCQWApS7BUK3cLPV7-HF4UHg5hQmFwhFIlForGY7HwPAEzB4Wb9RZA9JZJS5ApFUrlSruB41WIvbnJXmBfk5fKFVzFMoVM6IG6YapaOAvOBiWCCRoQcFwGVYgFwMqKOANFQAD0cIrgATEhhgszi8wGS2441m602230uzMFjEZnUJTAwggCEaDQU5TAZHkfnkJCUYjQ6nguA1cvxWruOuJbw+31+bytRaCFI0kMkNPhEnpqIcTMtOLr7LuXJ9PNSfOyguVqtFVQlPT00sHsuH8tHSuFarFnk1YSw071r0NMGNDVNGnN8+78Bt8HtTskLrdHq9jRabU63S93oWg2I5Go9CYqzWL0LSGH9Rn-QMNlqLZdBmEAgA)

**Comment by ahejlsberg** [comment]
A simpler repro:

```ts
declare function invoke<T>(f: () => T): T;

let xx: 0 | 1 | 2 = invoke(() => 1);  // Error, 'number' not assignable to '0 | 1 | 2'
```

The contextual type for the arrow function `() => 1` is `() => T`. We infer `0 | 1 | 2` for `T` through the generic return type, but we then fail to instantiate the `T` in `() => T` when checking whether `1` is a literal of the contextual type. And, because `1` doesn't appear to be a literal of the contextual type, we widen it to `number`.

The fix is to properly instantiate the contextual type.
