### ISSUE TITLE
unknown should be narrowable to {}

### ISSUE THREAD

**Issue by evmar** [microsoft/TypeScript#32347]
**TypeScript Version:**  3.6.0-dev.20190711

**Search Terms:** unknown narrow toString hasOwnProperty

**Code**

```ts
function f1(o: unknown) {
  if (o) {
    o.toString();
  }
}
function f2(o: {}|null|undefined) {
  if (o) {
    o.toString();
  }
}
```

**Expected behavior:**
Both succeed.

From user perspective I believe unknown behaves like an alias for the second type.  So another way of looking at this problem is that given f1's signature, it's hard to explain why to someone to need to switch it to f2's signature based on whether the body needs narrowing.

**Actual behavior:**
f1 invalid on the toString, Object is of type 'unknown'.

**Playground Link:** 
http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMAjACjgLkeA1mOAdzAEpEBvAKEURmEQzKpprgDoo4BlKAJxjABzNCQDc1RAF9K00JFgJkAJgzZykgD5gQAGx0bwAEwCmwAccNMJdBnCstE7Tj35CR4mtMlA

**Related Issues:**
In this comment
https://github.com/microsoft/TypeScript/issues/28131#issuecomment-433106959
@ahejlsberg says it's a limitation of the CFA.

This bug talks about other approaches to narrowing unknown:
https://github.com/microsoft/TypeScript/issues/25720
and in particular @andy-ms points out a bug that feels similar:
https://github.com/microsoft/TypeScript/issues/25720#issuecomment-407237691

**Comment by taralx** [comment]
Also running into this when dealing with JSON, as the result of unmarshaling is reasonably `unknown`, and `result ? result.toString() : ""` doesn't type check...

**Comment by DanielRosenwasser** [comment]
PR is out at #49119
