### ISSUE TITLE
Nested Condition Type over three layers will not correctly derive the correct type

### ISSUE THREAD

**Issue by Zcating** [microsoft/TypeScript#32348]
Hi, all:
I found this question as following:
```
type Detail<T> = T extends Apple ? AppleDetail :
T extends Banana ? BananaDetail :
T extends Orange ? OrangeDetail :
T extends Pear ? PearDetail :
T extends Peach ? PeachDetail :  never;

// Pear & Peach will never get correct detail
type T1 = Detail<Pear>;  // type is OrangeDetail
type T2 = Detail<Peach>; // type is OrangeDetail
```

**Comment by dragomirtitian** [comment]
Simple questions should be asked on stackoverflow. This probably works, but the behavior is dependent on the definitions of the fruit types.

**Comment by Zcating** [comment]
I think it is a bug & not dependent on the definitions.... any types except any may cause this problem...

**Comment by Zcating** [comment]
I have some solution to resolve it, thanks @dragomirtitian.

**Comment by Zcating** [comment]
I have some solution to resolve it, thanks @dragomirtitian.
