### ISSUE TITLE
string "ddd" not assignable to type '"ddd" | "dddd"'

### ISSUE THREAD

**Issue by rnickson** [microsoft/TypeScript#32355]
**TypeScript Version:** 3.6.0-dev.20190711

**Search Terms:** string not assignable to type string

**Code**

```ts
export class BaseChannel {
  type: 'text' | 'voice' | 'direct';
}

export class TextChannel extends BaseChannel {
  type = 'text';
}
```

**Expected behavior:** assign successfully

**Actual behavior:** TS2416 error: `Property 'type' in type 'TextChannel' is not assignable to the same property in base type 'BaseChannel'. Type 'string' is not assignable to type '"text" | "voice" | "direct"'.`

**Playground Link:** [⛓️](https://www.typescriptlang.org/play/index.html?strictPropertyInitialization=false#code/KYDwDg9gTgLgBAYwDYEMDOa4CF3AMIAWKAdscEnAN4BQccMAnmMAFxwDkMoM7cAPhwBuEAJYJgvAewAmIqMAQ8A3NQC+1aqEixEqDHAAq3QiTIVuwYtMw40+IqXJVa9JsDgBeDlxDK11IA) 

**Related Issues:**  did not find any

**Comment by orta** [comment]
This is an interesting case of the widening of `'text'` into `string` inside a mutable location.

While this is being discussed, `this.type` inside the constructor works:

```ts
export class BaseChannel {
  type: 'text' | 'voice' | 'direct';
}

export class TextChannel extends BaseChannel {
  // type = 'text';

  constructor() {
    super()
    this.type = 'text'
  }
}

```
[playground link](https://www.typescriptlang.org/play/index.html?strictPropertyInitialization=false#code/KYDwDg9gTgLgBAYwDYEMDOa4CF3AMIAWKAdscEnAN4BQccMAnmMAFxwDkMoM7cAPhwBuEAJYJgvAewAmIqMAQ8A3NQC+1aqEixEqDHAAq3QiTIVuwYtMw40+IqXJVacAPSv6TYHAC8HLiDKGnQIEMRoMFAArorQABQAlM50dGhRzFCJLnQwBCJoAHSMzL7+wDwu6upAA)

**Comment by AnyhowStep** [comment]
Or,
```
export class BaseChannel {
  type: 'text' | 'voice' | 'direct';
}

export class TextChannel extends BaseChannel {
  type = 'text' as const;
}
```
[Playground](http://www.typescriptlang.org/play/?strictPropertyInitialization=false#code/KYDwDg9gTgLgBAYwDYEMDOa4CF3AMIAWKAdscEnAN4BQccMAnmMAFxwDkMoM7cAPhwBuEAJYJgvAewAmIqMAQ8A3NQC+1aqEixEqDHAAq3QiTIVuwYtMw40+IqXJVa9JsDgBeDlxA846RAhiNBgVVSA)

**Comment by DanielRosenwasser** [comment]
See #32082 (also #340, #1373, #5749, #6118, #10570, #16944, #23911).
