### ISSUE TITLE
JsxAttributes - Add `kind` property

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#32364]
## Search Terms

JsxAttributes kind

## Suggestion

Change:

```ts
export interface JsxAttributes extends ObjectLiteralExpressionBase<JsxAttributeLike> {
    parent: JsxOpeningLikeElement;
}
```

To:

```ts
export interface JsxAttributes extends ObjectLiteralExpressionBase<JsxAttributeLike> {
    kind: SyntaxKind.JsxAttributes;
    parent: JsxOpeningLikeElement;
}
```

## Use Cases

Would help when people are narrowing down types while using the compiler api.

In my case, I'm analyzing nodes in the compiler and it couldn't figure out the kind of `JsxAttributes`. So I hardcoded a condition right now to properly return the kind.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dsherret** [comment]
Let me know and I will submit a PR.

**Comment by sandersn** [comment]
Seems right, and it builds. @weswigham, can you confirm?

**Comment by weswigham** [comment]
Looks right - surprised it was missing; guess we never use it in a union anywhere. 🤷‍♂
