### ISSUE TITLE
Use void as argument, sometimes error and sometimes no

### ISSUE THREAD

**Issue by liangshen001** [microsoft/TypeScript#32374]
`
function a(b: void) {

}
a();
`
There's an error here as follow:

- TS2554: Expected 1 arguments, but got 0

How do I fix it, Thank you in advance!!!

**Comment by dragomirtitian** [comment]
No error I can see [Playground](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAQwBQCMBciBucYAmAlIgN4BQ5AvuWkQNxA)

There are limitations around void params and conditional types and generics but simple stuff should work (https://github.com/microsoft/TypeScript/issues/29131)

**Comment by liangshen001** [comment]
> No error I can see [Playground](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAQwBQCMBciBucYAmAlIgN4BQ5AvuWkQNxA)
> 
> There are limitations around void params and conditional types and generics but simple stuff should work (#29131)

but I get errors using webstorm
![image](https://user-images.githubusercontent.com/22604816/61611236-e393ef00-ac8d-11e9-9912-1c7a72430621.png)

Is there a configuration problem?

**Comment by liangshen001** [comment]
> No error I can see [Playground](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAQwBQCMBciBucYAmAlIgN4BQ5AvuWkQNxA)
> 
> There are limitations around void params and conditional types and generics but simple stuff should work (#29131)

The reason is that my typescript version is too low, thank you very much
