### ISSUE TITLE
Diagnostics provided by Language Service Plugin are useless in CI.

### ISSUE THREAD

**Issue by anurbol** [microsoft/TypeScript#32371]
## Search Terms

Language Service Plugin, diagnostics.

## Suggestion

I've invested *a lot* of my time into LS Plugin development just to learn in the end that the diagnostics produced by my Plugin do not cause `tsc` to exit with error code. i.e. It doesn't matter if a plugin produces 1 or 10000 diagnostic errors, the compiler would still not show them when running `tsc` during CI (continuous integration) process. LS Plugin API is still mega-super-ultra cool thing! But I think it misses the essential part.

So the suggestion is that the compiler (`tsc`) should take account of the diagnostics produced by an LS plugin and should merge them with the native list of diagnostics.

## Use Cases

Whenever a user uses an LS Plugin for development with IDE he likely want to also be sure that some errors will not pass through CI process.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by anurbol** [comment]
Also this is already mentioned [here](https://github.com/Microsoft/TypeScript/issues/16607#issuecomment-491415950) and is personally [approved](https://github.com/Microsoft/TypeScript/issues/16607#issuecomment-491900783) by Daniel Rosenwasser

**Comment by RyanCavanaugh** [comment]
> I've invested a lot of my time into LS Plugin development just to learn in the end that the diagnostics produced by my Plugin do not cause tsc to exit with error code

This is addressed by the very first paragraph of https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

This was an intentional design decision. The goal of LS plugins is to allow for commandline-only tools (e.g. eslint) to provide in-editor errors, not the reverse.

**Comment by anurbol** [comment]
@RyanCavanaugh Thank you for reponse! Yep, I had read that several times but still plugin-produced diagnostics are much less usefull if they are not able affect CI process. Also, I've created this issue just as a place to start from, since Daniel Rosenwasser said it is a way to go. Soo, should I close this issue or let it be open?

**Comment by RyanCavanaugh** [comment]
What you're asking for *is* #16607, so I don't think we need a second issue tracking it.

**Comment by anurbol** [comment]
@RyanCavanaugh Hi! I think I changed my mind about this issue anyway, I think the design rules are good really. For CI process it's better to have a standalone `tsc`-like executable that does throw if there are any diagnostics. And an executable is also able to receive command line arguments. Also, I suspect it is a much more common case when LS plugin diagnostics shouldn't affect the build step, and should only provide recommendations while working in IDE. Anyway, thanks for response / sorry for bothering :smiley:
