### ISSUE TITLE
"Self" variable assumes window environment at the top level

### ISSUE THREAD

**Issue by ChimeraCoder** [Microsoft/TypeScript#3238]
I'm using Typescript to write a content script for a Firefox extension. These run in a [special environment](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Two_Types_of_Scripts#API_Access_for_Add-on_Code_and_Content_Scripts) in which a number of variables are pre-defined, `self` being one of them. I can use `declare var content;`, etc. to access them in TypeScript easily.

However, they do not run in the window environment (at least not directly), so `window` may not be defined, and `self` does not refer to window.self. Yet, when I do `declare var self;`, I get the following error:

````
error TS2403: Subsequent variable declarations must have the same type.  Variable 'self' must be of type 'Window', but here has type 'any'
`````

So far, I haven't been able to find a way to convince `tsc` that `self` is actually a different type. This surprised me, because as far as I know, Typescript is not specific to the browser context. Should there be a flag to specify the runtime environment (or absence of one)?

**Comment by DanielRosenwasser** [comment]
You could in theory customize our `lib.d.ts`, remove the declaration, include the new file into your source, and compile with `--noLib`. Not sure if we really have a better solution at this point.

**Comment by SaschaNaz** [comment]
I wanted `redeclare foo: Bar` thing every time I encountered this kind of problem.

**Comment by mhegazy** [comment]
looks like what you want is to explicitly reference `lib.code.d.ts`, this does not have any DOM definitions, so no self, no window, this would be what you need for node development. the file is available in the same location as your tsc.ex/tsc.js, just add a reference to it on your commandline or in your project, and you should be good to go.

**Comment by mhegazy** [comment]
also to add more context, we did split the lib into multiple smaller files(e.g. core, dom, webworkers, wscript, ...etc.), but we are still looking into easier ways to surface this change. it is on the list of work items for 2.0 (see [roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap#20)).

**Comment by ChimeraCoder** [comment]
Got it - thanks for clarifying. As per your comment in #2953, I think eventually a `--lib` flag would indeed solve this problem in the long run.

**Comment by mhegazy** [comment]
Looks like there is no further information needed at this point. closing.
