### ISSUE TITLE
Irrelevant and ambiguous error in implementing an interface with chaining purposes

### ISSUE THREAD

**Issue by hallaji** [microsoft/TypeScript#32394]
**TypeScript Version:**  3.5.2

**Search Terms:**
- Chaining methods and return type of `this` in a class
- Error type of not assignable to the same property in base type 

**Code**

I've got a `QueryBuilder` class that implements `Builder` interface. Some of the functions within the class return `this` for chaining purposes.

```ts
interface Builder<T> {
  where (prop: string, value: string): Builder<T>;  
  offset (value: number): Builder<T>;
}

class QueryBuilder<T> implements Builder<T> {
    public where (prop: string, value: string): Builder<T>  {
        // ...
        return this;
    }
}

class QueryBuilder2<T> implements Builder<T> {
    public where (prop: string, value: string): QueryBuilder2<T>  {
        // ...
        return this;
    }
}
```

**Expected behavior:**

I would expect to see an incorrectly implemented error only:
> Class 'QueryBuilder<T>' incorrectly implements interface 'Builder<T>'.

**Actual behavior:**

Irrelevant and ambiguous error is shown in different situations:

1. If I specify the return type as `Builder<T>`, I get this error:
> Type 'this' is not assignable to type 'Builder<T>'.

2. Specifying the return type as `QueryBuilder<T>` also results in an error:

> Property 'where' in type 'QueryBuilder<T>' is not assignable to the same property in base type 'Builder<T>'.

_I had to comment all the methods in the interface that have not been implemented yet to address this issue._

**Playground Link:** [Playground](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgEIFdgBsAm0A8AKgHzIDeAUMsgO4AW0KAFAA5QD2LAXMgM5hRQAcwA0yAG5ws6CD36CQQgJQ8M2PFCLEA3NSrJ2MGLwhhkTSdNnIQ6ALYAjaCrSZcBEtooBfChQRYcLy8yACKMlAAnmrumiTIwHYsWBB2EOAhMRpa5PrULOgOWMAItAxQzGyccgLCYpYyNQrKqm7Z8bnUXV0A9D3IAHRDed3IFWDoUCDIYHTAvF7dvr7+gcFhEdFt0ABMOYnJqelgmdtxpJTdBUUlZYzmVdx8tYr1Uo3PzS7h0FvquzlOqNqH1BsNgdRxpNprN5osuss-AEgiEflEstAAMz7JIpNIZVz-c5A-KFYqlej3VgcJ7yOoSd7WOmKFwY4kk0agoYDEbdKFTGZzBYjXzdQzGUzmBrWWyOZytIk5S4QrngiH8mFC+HUZZAA)

**Related Issues:** N/A

**Comment by nattthebear** [comment]
In all three of the error spans shown in that playground link, the final elaboration in the error message is:

```
Property 'offset' is missing in type * but required in type 'Builder<T>'
```

And in all of the cases, if you fix what the error message elaborates on, you will fix the problem; the missing `offset` implementation is what's stopping this all from working.

So I'm not seeing how these errors are irrelevant or ambiguous.

**Comment by hallaji** [comment]
@nattthebear Correct. I never noticed that error unless you mentioned. 

However, the initial explanation somehow makes a confusion specially because the error focus is on the function return or a function name in this case instead of class definition.
