### ISSUE TITLE
Be able to check the type of a generic

### ISSUE THREAD

**Issue by bluong** [Microsoft/TypeScript#3240]
Let's say I have the following class
```typescript
class Foo<A>
```

Now let's say in a function, we want to take action depending if `A` is `number`, for example.  Is there any way we can check the value of the generic?

**Comment by danquirk** [comment]
You will need to check on some property of the type which uses A since that's the only thing that will actually exist at runtime.

```ts
class Foo<A> {
    constructor(public bar: A) { }
    doStuff() {
		if (typeof this.bar === "number") {
			// ...	 
		} else if (typeof this.bar === "string") {
			// ...
		}   
    }
}
```
