### ISSUE TITLE
typescript class compilation to es5 doesn't work properly with Object.setPrototypeOf

### ISSUE THREAD

**Issue by 3axap4eHko** [microsoft/TypeScript#32409]
**TypeScript Version:**  3.6.0-dev.20190713
**Code**
jest unit test example
```ts
it('Should call parent mock constructor', () => {
    class A {}
    class B extends A {}
    const ParentMock = jest.fn();
    Object.setPrototypeOf(B, ParentMock);
    new B();
    expect(ParentMock).toHaveBeenCalled();
  });
```

**Expected behavior:**
`ParentMock` should be called

**Actual behavior:**
`ParentMock` is not called

**Comment by RyanCavanaugh** [comment]
I'd recommend using your own `__extends` helper if this is important for your application

**Comment by 3axap4eHko** [comment]
@RyanCavanaugh I just reported a bug that breaks js spec. I think it needs a label `Can't Fix` 🤣

**Comment by nmain** [comment]
You could also change your build workflow so that babel does the class transforms, as this works in it
