### ISSUE TITLE
TypeScript code generation from the Language Service

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/TypeScript#3241]
It would be great if we could generate TypeScript code using the Language Service.  This is a feature request continuing on #1651. A pretty printer is missing that consumes only the AST. Like #3136, a use case would be generating TypeScript code from a Swagger/RAML/REST api that is well defined.

**Comment by mhegazy** [comment]
@ctaggart can you provide more details? you want some AST factory functions to allow you to generate AST on the fly? 

> A pretty printer is missing that consumes only the AST

It is not missing, it is just hidden :) see [this example](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#pretty-printer-using-the-ls-formatter) for how it can be done. We would be open to accept a PR to add a new `beautify` function that takes a string and returns a string `beautify(input: string, options?: ts.FormatCodeOptions): string`

**Comment by ctaggart** [comment]
Also helpful here is @basarat 's Compiler Overview: http://basarat.gitbooks.io/typescript/content/docs/compiler/overview.html

@mhegazy Yes, I want to generate AST on the fly and then be able to print/emit the generated TypeScript. I could use some help getting started. Any idea what the tests might look like for this.

**Comment by ctaggart** [comment]
I attempted this again given some hints from @CyrusNajmabadi at the MVP Summit, but no luck. You can clone https://github.com/ctaggart/TsAst to see what I tried or just view the commit linked above. I would love a review and some help.

**Comment by CyrusNajmabadi** [comment]
I would not use the formatter.  I would call ```ts.emitFiles``` with your target source file.  Note: you'll need to pass in an EmitResolver and EmitHost as well.  EmitHost is very basic (and is just the way you provide the writer that the emitter will write into).  EmitResolver is much more complex unfortunately.  You'll probably want to just provide a dummy one that does almost nothing in all the functions (i.e. mostly returning 'false' or 'undefined').

Hope that helps!

**Comment by ctaggart** [comment]
@CyrusNajmabadi, I'm taking another look at the today. It looks like `ts.emitFiles` emits JavaScript, not TypeScript. 
https://github.com/ctaggart/TsAst/blob/65d8682e3ba70944b2b4960d587e1ee921b308eb/app.ts#L89-L96
![image](https://cloud.githubusercontent.com/assets/80104/11610263/0bf87eb2-9b52-11e5-96dc-3ee20da8cb97.png)

Any idea what the right function might be for emitting TypesScript source files? I'm going to take a look at `emitDeclarations` in `declarationEmitter.ts` next.

**Comment by ctaggart** [comment]
The `emitDeclarations` did do what its name implies. It exported the declaration:
https://github.com/ctaggart/TsAst/blob/91571a3e679d7c1f29a86ed6754daffd02a0f48d/app.ts
![image](https://cloud.githubusercontent.com/assets/80104/11610958/d6558bac-9b69-11e5-87a5-ae08e8153f65.png)
Pretty cool, and probably useful in the future, but not what I'm looking for just yet. I just want to create or manipulate `ts` files.

**Comment by DanielRosenwasser** [comment]
As a heads up @ctaggart, @rbuckton is working on tree transformation infrastructure and a pretty printer. It's to help us with general codegen between emit targets, but we're hoping that down the line it can be used in the language service as well. That might be useful for your purposes, so we'll try to keep you posted. :smiley:

**Comment by ctaggart** [comment]
Thanks @DanielRosenwasser, really looking forward to what @rbuckton puts together!

Meanwhile, I'm still hacking my way though. My current thought is that if I can build up the AST from scratch and get it to output `js`, may I will be able to get it to output `ts` afterwards. Here, I was hoping to produce `var a = 1;`, but got `var ;`. 

![image](https://cloud.githubusercontent.com/assets/80104/11611423/a8537012-9b81-11e5-85cd-3b176dc6b72d.png)
https://github.com/ctaggart/TsAst/blob/d6fcb49711defb7bd63c5fea83f62755b7c1afa8/app.ts#L28-L43

I'll see if I can make use of `parseVariableStatement` and the other parse functions. Clearly, I'm doing something wrong.

**Comment by ctaggart** [comment]
I'm giving up for now. @rbuckton, I'm interested in whatever you come up with.

**Comment by mhegazy** [comment]
this should be part of the work in https://github.com/Microsoft/TypeScript/issues/5595

**Comment by mhegazy** [comment]
closing in favor of #5595
