### ISSUE TITLE
Symbol.iterator

### ISSUE THREAD

**Issue by ronnievdc** [microsoft/TypeScript#32419]
**TypeScript Version:**  3.5.3

**Search Terms:**
Symbol.iterator 
@@iterator
for..of loop

**Code**
```ts
const iterable1 = new Object();
const items = [1, 2, 3];

iterable1[Symbol.iterator] = function () {
  return items[Symbol.iterator]();
};

for (const i of iterable1) {
  console.log(i);
}
```
Options: **target: ES5**

**Expected behavior:**
Output the numbers 1, 2 and 3

**Actual behavior:**
No output

**Playground Link:** 
http://www.typescriptlang.org/play/?target=1#code/MYewdgzgLgBAllApgJwIYCMA2iCMMC8MYiA7jAPLoBWiwUAFAJQDcAUKJLAogLYQEwA2jgA0MAExiAzAF02rbmiy5BAZQCePdCEwA6RaighkMgQDMArmDpxwMJjADerGDGSIoF5GHhI+azW09AyMTJjYAX3kzY3sOaHgYEDNfFAxsHEYnFxh4nURdTBAAc3o4FlYI1iA

**Related Issues:**

**Comment by fatcerberus** [comment]
This works if you enable `downlevelIteration`.

**Comment by ronnievdc** [comment]
That works, Thanks
