### ISSUE TITLE
Add a new bot trigger for publishing prereleases from a PR

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#32412]
Similar to `@typescript-bot pack this`, but will publish the packed release to a given tag on `npm`. For safety, it should forbid `latest`, `next`, and anything with `release` in the name.

For UX, I'm thinking `@typescript bot release this as (name)`, so for example: `@typescript bot release this as private-experiment`, publishes the PR head as `3.6.0-privateexperiment.07152018` under the `npm` tag `private-experiment`.

**Comment by RyanCavanaugh** [comment]
Yep
