### ISSUE TITLE
Question: How to test if is exhaustive? (getTypeAtArbitraryLocation?)

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#32415]
How can I go about testing if a switch statement is exhaustive?

The only approach I can think of is:
If there is a default case, its exhaustive. Otherwise, ensure the last case breaks out of the switch. Adding a default case to the bottom and test if the type of the discriminant is `never`.

However, I've got no idea if this approach is even possible. If it is how do I do it?

Example test code:

```ts
type T = "a" | "b";

function foo(bar: T) {
  switch (bar) {
    case "a":
      return 1;
    case "b":
      return 2;
  }
}
```

Sorry for asking a question here but as this is to do with the TypeScript Type Checking API I hope it is ok.

**Comment by ajafff** [comment]
```ts
type T = "a" | "b";

function assertNever(v: never) {
  throw new Error(`expected value '${v}'`);
}

function foo(bar: T) {
  switch (bar) {
    case "a":
      return 1;
    case "b":
      return 2;
    default:
      throw assertNever(bar); // gives a compile error if the switch is not exhaustive
  }
}
```

The above solution adds code that is loaded at runtime.

If you want to write a linter rule or similar for this purpose, there is currently no easy way to do this. You'd have to get all literal types from `bar` and subtract all literal types of the `case` clauses. If there are non-primitive types involved, there's no way to check for exhaustiveness.

**Comment by RebeccaStevens** [comment]
Thanks @ajafff.
I am writing a linting rule so I guess I'll just put this in the too hard basket for now.

Feel free to close this issue unless you want to leave it open as a feature request.
