### ISSUE TITLE
String literal that fits `keyof X` cannot be used as key of `X` in some cases

### ISSUE THREAD

**Issue by silverwzw** [microsoft/TypeScript#32427]
**TypeScript Version:**  3.5.3

**Search Terms:**
- keyof
- string literal
- extends

**Code**

```ts
type Config = { method: "POST" | "GET" };

<X extends Config>() => {
    type Mapper = { [ item in X["method"] ] : number };

    let mapper : Mapper;

    let a = { POST:1, GET:2 }; // `a` has type `{ POST: number, GET: number }`
    mapper = a; //  ✔, tsc think this is OK
    mapper = { POST:1, GET:2 };  //  ❌, but this is not

    let key : keyof Mapper;
    key = "FETCH"; // ❌, tsc think "FETCH" is not a valid key
    key = "POST"; //  ✔, but "POST" is a valid key
    mapper[key] = 0; //  ✔, tsc think mapper[key] is OK
    mapper["POST"] = 0; // ❌, but mapper["POST"] is not
};
```

**Expected behavior:**
tsc either reports no syntax error on the above code snippet. Or error on all four lines:
```
    mapper = a;
    mapper = { POST:1, GET:2 }; 
    mapper[key] = 0;
    mapper["POST"] = 0; 
```

**Actual behavior:**
tsc complains on the two marked above with `Object literal may only specify known properties, and 'POST' does not exist in type 'Mapper'.` But not reporting error on the other 2 lines.

**Playground Link:**
https://www.typescriptlang.org/play/?target=1#code/C4TwDgpgBAwg9gOwGYEsDmUC8UDeUC2EwAFnACYBcUARAAoDyAygCrVQA+NA4gKKtQBfANwAoEQB4AGlAgAPYBARkAzrESo0APgAUASiybcIqCaihIUALIBDMJABOWXFADaUFAvzuEUSS+qEJOTUALpQYVQIAK74AEYQjsJiplAANkQEtg5QVDZ2CaLGpunAUNZOeAwsFACMADRQvMwUAEyCQlAA9J1QAAbWvVDE1qrm0L2VTM1Q0XEJDU2RMfGJvUUm+FkJTtYd3SaAKOQNwMoAxmbEKAgA1hcoqvdQ9ADS65n5jtiT1fWNfK3tEz7KCAGXIGrEoqUSI9Hgg4MBksUMtcICAclAUSA4EgrFt7KIUpinNQAGJ8GAACWoex6YLMZzuNxoZOYlLYsPhZSgADdrKkUGQMai3kTsHQptSuj0oEcoBDSuKWOzVOVefzBZi3psPi5MWFsAAGGmHY4M6FM7UOXWosKPF5avH+KqsfVQI1S0HgyHvK2Kl3uVRwhHCIA

**Related Issues:**

**Comment by AnyhowStep** [comment]
```ts
const f = <X extends Config>() => {
  /* snip */
};
/**
 * Of course you **MUST NOT** set `mapper["POST"]`!
 * Because "POST" is not assignable to `X["method"]`
 */
f<{ method : "GET" }>();
```

**Comment by silverwzw** [comment]
@AnyhowStep This is a simplified example, just to illustrate the issue. The actual code that leads me to this is using the type parameter in the parameter list.

My point it that:
```ts
    let a = { POST:1, GET:2 }; // `a` has type `{ POST: number, GET: number }`
    mapper = a;
```
and
```ts
    mapper = { POST:1, GET:2 };
```
The two pieces of code shall both fail or pass the syntax check. It's weird that one passes the check while the other failed the check.

Same thing to:
```ts
    let key : keyof Mapper = "POST";
    mapper[key] = 0;
```
v.s.
```ts
    mapper["POST"] = 0;
```

**Comment by fatcerberus** [comment]
```ts
let a = { POST:1, GET:2 }; // `a` has type `{ POST: number, GET: number }`
mapper = a; //  ✔, tsc think this is OK
mapper = { POST:1, GET:2 };  //  ❌, but this is not
```

This is because of excess property checking, [which only applies to "fresh" object literals](https://basarat.gitbooks.io/typescript/docs/types/freshness.html).  Types are not closed, otherwise you wouldn't be able to have subtypes under structural typing.

I still believe the error message for this needs reworded because it seems to be very misleading to people as it is right now.  See discussion here: https://github.com/microsoft/TypeScript/issues/32158#issuecomment-507089327

**Comment by poseidonCore** [comment]
You can rewrite this as

```ts
type Config = {method:"POST"|"GET"};
type Mapper = {[item in Config["method"]]:number};

function fn<X extends Config>() {
    let mapper:Mapper;

    let a = {POST: 1, GET: 2}; // `a` has type `{ POST: number, GET: number }`

    mapper = a; //  ✔, tsc think this is OK

    mapper = {POST: 1, GET: 2}; // ✔

    let key: keyof Mapper;
    key = "FETCH"; // ❌, tsc think "FETCH" is not a valid key
    key = "POST"; //  ✔
    mapper[key] = 0; //  ✔, tsc think mapper[key] is OK
    mapper["POST"] = 0; // ✔
}
```
to overcome some of these issues.

Putting the type declaration inside the function to reference the generic may be problematic here.

[TS Playground](https://www.typescriptlang.org/play/?target=1#code/C4TwDgpgBAwg9gOwGYEsDmUC8UDeBbCYACzgBMAuAIgAUB5AZQBVKAfSgcQFFmBfAbgBQoSFACyAQzCQATllwBtFMAh4oKBLESo08ygWJlKAXSPkEAVzwAjCNP4CBScwgDGwFIihIEAHgAaUBAAHsoIpADOmsjoAHwAFACUuAJQqVAANoRQeJIy5BJStoIpaZnAUOJyOHRM5FAAjAA0UFyMdQBM-FAA9N1QAAbi-VBE4pHC0P04UDVtUBbWts2tdQs2sjz9DmnZubZy4nw9fVCAKOTNwOEuUMTqANY3RCiRz1C0ANLbaTmFstjVDDmTRa3A6XV6Zy+qTKUDuEBAdThIDgSDEe2kgh2SLklAAYtwYAAJShHCGAGXILldHvcoHiCcS1JEEHBypUAG7idIoUiw+ElVLY7A0QEk46pU783a-eRIoxyAAMpJO5xuVNuCAePxkMvhcteH0lWtsulmxgVSshPCAA)
