### ISSUE TITLE
Not reporting errors of undeclared variables in js file

### ISSUE THREAD

**Issue by yubaoquan** [microsoft/TypeScript#32437]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
JsCheck, js errors

**description**
Ts reports error in ts file, bug not in js file. Althouth I added allowjs in tsconfig.json.
I don't think `xxx` is a property of `window`.

**Code**

```js
console.info(xxx)
```

**Expected behavior:**
report error `Cannot find name 'xxx'.`

**Actual behavior:**
Compile passed.

**Playground Link:** 

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/9938

**Version**
- ts 3.5.2
- windows 10

**Comment by fatcerberus** [comment]
> Althouth I added allowjs in tsconfig.json.

`checkJs`?

**Comment by yubaoquan** [comment]
> > Althouth I added allowjs in tsconfig.json.
> 
> `checkJs`?

Thank you
