### ISSUE TITLE
import helpers from tslib.es6.js when module is >= es6 and moduleResolution = node

### ISSUE THREAD

**Issue by mgroenhoff** [microsoft/TypeScript#32431]
Currently Node supports ES6 modules behind the flag `--experimental-modules`. It also supports [customizing the module resolution](https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm). Just like TypeScript has compiler options that change the emit output.

When I set the `module` compiler option is to something newer than es5 (like es6 or esnext) and I set `moduleResolution` to `node`, I can run a module as follows and it all works out fine:
```
node --experimental-modules --es-module-specifier-resolution=node ./path/to/module.js
```

However when I enable the `importHelpers` option, the following import is emitted:
```js
import * as tslib_1 from "tslib";
// code is calling these helpers like so:
tslib_1.__decorate(...) // "TypeError: tslib_1.__decorate is not a function" because tslib_1 === { default: { __decorate: ... } }
```

I think using the file at `node_modules/tslib/tslib.es6.js` would be sufficient.

```js
import * as tslib_1 from "tslib/tslib.es6.js"; // I think this would do it
```

**Comment by dasa** [comment]
Related to https://github.com/microsoft/tslib/pull/44

**Comment by rbuckton** [comment]
I believe this is resolved by https://github.com/microsoft/tslib/pull/126. The latest version of `tslib` supports NodeJS conditional exports and will import tslib.es6.js automatically.
