### ISSUE TITLE
use `node` moduleResolution by default also for `module: es6`

### ISSUE THREAD

**Issue by tuures** [microsoft/TypeScript#32432]
## Search Terms

moduleResolution, es6

## Suggestion

Use `node` resolution strategy by default when `module` is `es6`/`ES2015`/`esnext`. Currently with these `module` options the default resolution strategy is `classic`, even thought it's described as a "backward compatibility" option.

Alternatively the default could be changed to `node` regardless of the selected `module` value, which would make the behaviour of TSC more consistent.

## Use Case / Example

I had a working project with automatically (`tsc --init`) generated `tsconfig.json` that had `module` set to `commonjs` and no `moduleResolution` explicitly set:

```
   "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
 //"moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
```

After I changed the `module` later to `es6`, I was baffled by multiple "cannot find module blah" errors that did not seem to make any sense. I tooks some time before I noticed from the documentation that using `es6` in `module` changes the default resolution strategy to `classic`.

Using the `classic` strategy by default feels especially counterintuitive in case of ES modules which are the "new" approach, whereas the `classic` strategy is described as:
> _Classic_
>This used to be TypeScript’s default resolution strategy. Nowadays, this strategy is mainly present for backward compatibility.

The documentation for this behaviour was improved in https://github.com/microsoft/TypeScript/issues/10433, but I suggest that the actual _default_ behaviour would be changed. Anyone wanting to use the `classic` strategy would then have to explicitly choose that. I think that `node` strategy is what most developers would expect as the default when starting with a new ES2015+ project.

**Comment by RyanCavanaugh** [comment]
This would be a very disruptive breaking change. ES6 does not specify a relationship between paths and files, so no module resolution algorithm is inherently better than the other.

**Comment by tuures** [comment]
@RyanCavanaugh Thanks for quick response.

To avoid breaking existing projects (what I think you were referring to), would you be then willing to consider changing the behaviour of `tsc --init` so that it would either ask about the desired module resolution strategy or just set `moduleResolution: node` (so that either way it would be explicitly set). If you don't see specific benefits in favouring `node` strategy per se, there's still the aspect of the value of `moduleResolution` changing "unexpectedly".
