### ISSUE TITLE
HTMLInputElement have incompatible type for "selectionDirection" and setSelectionRange

### ISSUE THREAD

**Issue by xileftenurb** [microsoft/TypeScript#32449]
**TypeScript Version:**  3.6.0-dev.20190717
**Search Terms:**
selectionDirection HTMLInputElement DOM definition
**Code**
```ts
const el : HTMLTextAreaElement = new HTMLTextAreaElement();
const direction = el.selectionDirection;
el.setSelectionRange(el.selectionStart, el.selectionEnd, direction );
```

**Expected behavior:**
No error, as el.selectionDirection is definitely a good value for selectionDirection

**Actual behavior:**
tsc throw an error because el.selectionDirection is of type "string" and el.setSelectionRange only accept "forward" | "backward" | "none"

solution : 
HTMLInputElement.selectionDirection should be of type : "forward" | "backward" | "none" instead of type string. in lib.dom.d.ts at line 7332.

**Related Issues:**
the bug was introduced by the fixing of setSelectionRange as discuted in issue #20419 and PR #20459

**Comment by BuckAMayzing** [comment]
@RyanCavanaugh - I put out a PR for this one a couple of weeks back. It doesn't look like it has had anyone look at it yet. Do you know if there's someone I should tag on the PR?

**Comment by ShuiRuTian** [comment]
@sandersn  Hi, I thought this issue has been fixed by the PR and could be closed.
