### ISSUE TITLE
Filter transpile diagnostics

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#3245]
I'm working on implementing the `isolatedModules` option using the transpile method in gulp-typescript. I get errors that `lib.d.ts` hasn't been found and that it cannot find global types:
```
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
error TS6053: File 'lib.d.ts' not found.
```
Is there a way to filter out these messages using the API? Or should I just implement something like `if (error.code === 2318 || error.code === 6053) { ... }`?

In my opinion these messages should be to filter out in the transpile method, as everyone who uses that method won't be interested in those messages.

**Comment by mhegazy** [comment]
@ivogabe, you are correct. these should not be added.

**Comment by basarat** [comment]
FWIW I just don't even look at the errors and just spit out the JS :+1: e.g. in https://github.com/basarat/typescript-script
