### ISSUE TITLE
lost intellisence in typescript@3.6.0-dev.20190717

### ISSUE THREAD

**Issue by coppyC** [microsoft/TypeScript#32464]
yesterday, inorder to resolve the problem #30471，I install the plug 
https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next
and then I found it lost intellisence in some files.

**TypeScript Version:**  3.6.0-dev.20190717
**VS Code Version:** 1.36.1 

**Search Terms:** intellisence

**Code**
to reproduction only need 3 file. (I only enable the plug [JavaScript and TypeScript Nightly] to use 3.6.0-dev.20190717)
* test1.ts
```ts
export default {}
```
* test2.ts
```ts
export { default } from './test1'
```
* tsconfig.json (tip: if don't have this file, it will work well)
```json
{}
```
**Expected behavior:**
type console in the test1.ts
![image](https://user-images.githubusercontent.com/25004510/61426402-dd7bd680-a94c-11e9-801c-fc9c8940ddc8.png)
tip: use typescript@3.5.2 or delete the file tsconfig.json can reproduction the Expected behavior

**Actual behavior:**
type console in the test1.ts
![image](https://user-images.githubusercontent.com/25004510/61426539-4fecb680-a94d-11e9-840d-9d14c4744f49.png)
but the test2.ts work well
![image](https://user-images.githubusercontent.com/25004510/61426565-64c94a00-a94d-11e9-8ecc-511c63400345.png)

**Comment by IllusionMH** [comment]
Looks like duplicate of #32441
Latest nightly `3.6.0-dev.20190718` should works as expected

**Comment by coppyC** [comment]
yes, the latest nightly work well
