### ISSUE TITLE
Cannot declare type for default export

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#32466]
Not sure how to search for this one.

```typescript
import {BunionConf} from "bunion";

export const conf : BunionConf = {
  
  consumer: {
    transform: {}
  },
  
  producer: {
    appName: process.env.app_name
  }
 
};
```

but when I try to declare a type for a default export instead of `const conf`:

```typescript

import {BunionConf} from "bunion";

export default : BunionConf = {   // <<< this does not work
  
  consumer: {
    transform: {}
  },
  
  producer: {
    appName: process.env.app_name
  }
  
};
```

**Comment by AnyhowStep** [comment]
I never use default exports but what about,

```ts
export default const conf : BunionConf = {
```

**Comment by AnyhowStep** [comment]
```ts
import {BunionConf} from "bunion";

function check<T> (t : T) : T {
    return t;
}
export default check<BunionConf>({
    consumer: {
        transform: {}
    },
    
    producer: {
        appName: process.env.app_name
    }
});
```

**Comment by AnyhowStep** [comment]
Or even,
```ts
const conf : { x : number } = { x : 1 };
export default conf;
```

I don't use `default` exports ever. So, I'm hazy on the details.

**Comment by ORESoftware** [comment]
@AnyhowStep yeah those are work-arounds, thanks, but I wonder why it can't be done directly

**Comment by ORESoftware** [comment]
yeah `export default` is nice for libaries b/c users dont have think about naming etc, of course `export =` could also work, but i prefer the former but I havent tried adding a type to `export =`

**Comment by Saulzi** [comment]
Note you can do the following,

``` ts
export default {   // this does work
  
        consumer: {
          transform: {}
        },
        
        producer: {
          appName: process.env.app_name
        }
        
} as BunionConf;
```

although the compiler will stop you if your default exports type does not overlap the type of bunionconf

consider the following
``` ts

interface X {
    needed() : void;
}

export default 
    {   // this does work
  
        consumer: {
          transform: {}
        }               

      } as X;

```

this will not work as the default export does not have needed defined

whereas 

``` ts
export default 
    {   // this does work
  
        consumer: {
          transform: {}
        },

        needed() {
        }

      } as X;

``` 

will compile because it has the 'needed' property

**Comment by ORESoftware** [comment]
@Saulzi the  `const conf : X = {}`   has a different meaning in TS land than `const conf = {} as X` and `const conf  = <X>{}` , the last 2 are different than the 1st.

**Comment by Saulzi** [comment]
@ORESoftware 

Yes they do have different meanings, but i think that your key point is

> but when I try to declare a type for a default export instead of const conf   ... //this does not work

It looks like 

From Typescript Deep Dive (https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html)

> as foo vs. <foo>
> Originally the syntax that was added was <foo>. This is demonstrated below:
> ``` ts var foo: any;
> var bar = <string> foo; // bar is now of type "string"
> ```
> However, there is an ambiguity in the language grammar when using <foo> style assertions in JSX:
> ``` jsx
> var foo = <string>bar;
> </string> 
>```
> Therefore it is now recommended that you just use as foo for consistency.

yes they are slightly different things i.e. with 
``` ts 
const conf : X = {} 
```
you are saying something like hey i have this constant it will be of type x and here's its value

whereas with 
``` ts 
const conf = {} as X
```
you are saying i have this constant infer its type from whats on the right, whats on the right cast as x
