### ISSUE TITLE
How to make the compiled decorator code not different from typescript and babel?

### ISSUE THREAD

**Issue by kingller** [microsoft/TypeScript#32476]
Hi,
I find the decorator code compiled in TypeScript and javascript are different.
Input Code
```
class Toolbar {
    @observable
    toolbar = 'XX';
}
```
The decorator code in TypeScript compiled to
```
var Toolbar = function Toolbar(toolbar, option) {
  var _this = this;
  (0, _classCallCheck2["default"])(this, Toolbar);
  this.toolbar = 'XX';  // here is different
};

__decorate([mobx_1.observable, __metadata("design:type", Object)], Toolbar.prototype, "toolbar", void 0);
```
but when not use TypeScript, the decorator code compiled to 
```
function TableExampleStore() {
    // ...
    (0, _initializerDefineProperty2["default"])(_this, "toolbar", _descriptor, (0, _assertThisInitialized2["default"])(_this));
    return _this;
  }
  // ...
  (_descriptor = (0, _applyDecoratedDescriptor2["default"])(_class.prototype, "toolbar", [_mobx.observable], {
  configurable: true,
  enumerable: true,
  writable: true,
  initializer: function initializer() {
    var _this2 = this;

    return 'XX'; // here is different
  }
})
```
I find it use `toolbar='XX'` when compile the `typescript` code, but use `initializer` when compile the javascript code by `babel`.
When I create a javascript class extends a typescript class, and overwrite a  decorator field as bellow, the initializer value is lost.
```
// This is javascript code, but class Toolbar is typescript
class TableExampleStore extends Toolbar {
    @observable
    toolbar = 'YY';
}
```
How can I make them compile to the same code?

Here is my `tsconfig.json` file
```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "strictNullChecks": false,
        "module": "commonjs",
        "target": "ESNext",
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "allowJs": true,
        "baseUrl": "."
    },
    "include": [
        "./src/**/*"
    ]
}
```
Can you help me please? Thanks.

**Comment by fatcerberus** [comment]
TypeScript's decorators currently work differently from ES decorators, hence the `experimental` flag.  If you need ES decorators you'll need to continue to process the code with Babel.

**Comment by kingller** [comment]
I have used Babel transformations, but the code they compile is still different.
···
{
                test: /\.tsx?$/,
                loader: 'awesome-typescript-loader',
                options: {
                    useCache: true,
                    useBabel: true,
                    babelCore: '@babel/core'
                }
            }
···

**Comment by nmain** [comment]
You can't actually do that right now.  See https://github.com/microsoft/TypeScript/issues/29299

Because Typescript's decorator specification is not quite the same as anyone else's, they are always transformed.

**Comment by trotyl** [comment]
The babel output is already configurable, see https://babeljs.io/docs/en/babel-plugin-proposal-decorators#legacy.

**Comment by kingller** [comment]
@trotyl Sorry，what do you mean? I've set legacy to true already. Maybe I need to overwrite this plugin?

Here is my `babel.config.js`
```
module.exports = {
    presets: ['@babel/preset-typescript', '@babel/preset-react', '@babel/preset-env', 'mobx'],
    plugins: [
        // Stage 0
        '@babel/plugin-proposal-function-bind',

        // Stage 1
        '@babel/plugin-proposal-export-default-from',
        '@babel/plugin-proposal-logical-assignment-operators',
        ['@babel/plugin-proposal-optional-chaining', { loose: false }],
        ['@babel/plugin-proposal-pipeline-operator', { proposal: 'minimal' }],
        ['@babel/plugin-proposal-nullish-coalescing-operator', { loose: false }],
        '@babel/plugin-proposal-do-expressions',

        // Stage 2
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        '@babel/plugin-proposal-function-sent',
        '@babel/plugin-proposal-export-namespace-from',
        // '@babel/plugin-proposal-numeric-separator',
        '@babel/plugin-proposal-throw-expressions',
        '@babel/plugin-proposal-object-rest-spread',

        // Stage 3
        '@babel/plugin-syntax-dynamic-import',
        '@babel/plugin-syntax-import-meta',
        ['@babel/plugin-proposal-class-properties', { loose: true }],
        // '@babel/plugin-proposal-json-strings',

        // Other
        '@babel/plugin-transform-runtime',
        '@babel/plugin-transform-modules-commonjs',
        'jsx-control-statements'
    ]
}
```

**Comment by trotyl** [comment]
@kingller That't **NOT** the legacy output:

![image](https://user-images.githubusercontent.com/6059170/61635534-5b7e0b80-acc6-11e9-8511-50decd9c7344.png)

I'm not sure why you don't get correct configuration, but that should supposed to be an issue for babel or its integration tools.

**Comment by nmain** [comment]
Let me state this more clearly:  You cannot do this right now unless you remove Typescript from the chain entirely.  It always transforms decorators, leaving nothing left for Babel to transform.  The only way to do this is with babel and babel alone, using `babel-plugin-transform-typescript` to handle the typescript and then whatever else you want to handle the decorators.  .ts => tsc => babel will not work.

**Comment by kingller** [comment]
Thanks very much. It's OK now.
I remove the `awesome-typescript-loader`, and use `babel` to compile `TypeScript` and `ECMAScript` both, then get the same code I wish.
It only need to add `@babel/plugin-transform-typescript` plugin to `babel.config.js` as bellow
```
['@babel/plugin-transform-typescript', { allowNamespaces: true }]
```

**Comment by shrinktofit** [comment]
> Thanks very much. It's OK now.
> I remove the `awesome-typescript-loader`, and use `babel` to compile `TypeScript` and `ECMAScript` both, then get the same code I wish.
> It only need to add `@babel/plugin-transform-typescript` plugin to `babel.config.js` as bellow
> 
> ```
> ['@babel/plugin-transform-typescript', { allowNamespaces: true }]
> ```

No, they may not "same".
Given two scripts:

a.ts
```ts
import { Tool } from "./b";
```

b.ts
```ts
export interface Tool {};
```

The babel would generate wrong code because it don't know that `b.ts` didn't export the `Tool` actually.

**Comment by kingller** [comment]
@shrinktofit  The code I write as you said works well. What's your mean?

**Comment by shrinktofit** [comment]
> @shrinktofit The code I write as you said works well. What's your mean?

Did you compile it using babel + @babel/preset-typescript  ?

**Comment by kingller** [comment]
Yes, I use webpack + babel-loader

**Comment by trusktr** [comment]
The problem with supporting both TypeScript and Babel 7 legacy decorators is that apparently returning a descriptor behaves differently in both:

- In TypeScript, with `useDefineForClassFields` set to `false`, then if a decorator returns a descriptor, `Object.defineProperty` is _never used_ to define the property, and the decorator's descriptor is defined on the class `prototype`.
- With Babel 7, if a decorator returns a descriptor, then `Object.defineProperty` is _always used_ (in the constructor), _regardless of the class-properties `loose` option being true or false_. :cry: 

So people compiling code with TypeScript are in for a surprise when they try compile with Babel and legacy decorators don't work.

Another difference is that Babel passes an `initializer` property on the descriptors, while TypeScript's passes the `value` property. If you're looking for `value` in TypeScript decorator code, it'll need an update to check for `initializer` in case `value` is not present.

What's the solution for writing a legacy decorator that work in both TypeScript and Babel?

**Comment by trusktr** [comment]
The legacy decorators situation really is a mess!
