### ISSUE TITLE
Create instance of abstract class using object param

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#32477]
Say I have an abstract class like so:

```typescript
export abstract class Transformer {

   identifyViaRawStr: () => boolean;
   identifyViaJSObject: (v: any) => boolean;
   getValue: (v:any) => string;
   transformToBunionFormat: (v: any) => BunionJSON

}

```

but if I try to do this:

```typescript
const t = new Transformer();
```

it says:

--------

<br>

<kbd>
<img width="482" alt="Screen Shot 2019-07-18 at 6 05 25 PM" src="https://user-images.githubusercontent.com/11139560/61502066-1f297300-a987-11e9-9a14-8eca6f2f5954.png">
</kbd>

<br>

--------

so I was thinking of doing this:

```typescript

export abstract class Transformer {

  constructor(t: Transformer){
    this.getValue = t.getValue;
    this.identifyViaJSObject = t.identifyViaJSObject;
    this.identifyViaRawStr = t.identifyViaRawStr;
    this.transformToBunionFormat = t.transformToBunionFormat
    
  }
  
   identifyViaRawStr: () => boolean;
   identifyViaJSObject: (v: any) => boolean;
   getValue: (v:any) => string;
   transformToBunionFormat: (v: any) => BunionJSON

}


const c = new Transformer({
    getValue(){
      return '';
    },
  identifyViaJSObject(){
      return true;
  },
  identifyViaRawStr(){
      return true;
  },
  transformToBunionFormat(){
      return <any>{}
  }
});
```

but it says:

----------

<br>

<kbd>
<img width="533" alt="Screen Shot 2019-07-18 at 6 07 52 PM" src="https://user-images.githubusercontent.com/11139560/61502074-28b2db00-a987-11e9-8d3c-f0439a31a653.png">
</kbd>

<br>

----------

so maybe the way to do this is:

```typescript

const c = new (class implements Transformer{
  
  getValue(){
    return '';
  }
  
  identifyViaJSObject(){
    return true;
  }
  
  identifyViaRawStr(){
    return true;
  }
  
  transformToBunionFormat(){
    return <any>{}
  }
  
});
```

the only problem with the above the syntax is hard to remember

**Comment by Saulzi** [comment]
I think you are a bit confused, you cannot instantiate a abstract class because it does not have implementations defined for x,y,z period

I have noticed that you also raised https://github.com/microsoft/TypeScript/issues/32478 which kind of points this out, look at other languages such as c# etc,

technically your example 
``` ts
export abstract class Transformer {

  constructor(t: Transformer){
    this.getValue = t.getValue;
    this.identifyViaJSObject = t.identifyViaJSObject;
    this.identifyViaRawStr = t.identifyViaRawStr;
    this.transformToBunionFormat = t.transformToBunionFormat
    
  }
  
   identifyViaRawStr: () => boolean;
   identifyViaJSObject: (v: any) => boolean;
   getValue: (v:any) => string;
   transformToBunionFormat: (v: any) => BunionJSON

}
``` 

is not really abstract as you are providing the delegates which will do the work, be careful here though as the this context may not be what you think in identifyViaRawStr,identifyViaJSObject,getValue,transformToBunionFormat
as you have assigned the functions to a different object.

**Comment by RyanCavanaugh** [comment]
@ORESoftware We've asked you many, many times to not use the issue tracker as a support forum. From this point forward I'm going to delete issues from you that aren't clearly-identified bugs.

**Comment by the1mills** [comment]
This appears to be a feature request, not a bug
