### ISSUE TITLE
I want to read a file from web URL in typescript.

### ISSUE THREAD

**Issue by vaithiya** [microsoft/TypeScript#32480]
I want to read a file. That file actually I put it in S3 bucket and gave access as a public. Using s3 I get the url of the file. https://tlc-test-public.s3-ap-northeast-1.amazonaws.com/public/member_id/xxx.txt. I am trying to read this file. I am getting error Error: ENOENT: no such file or directory, open 'https://tlc-test-public.s3-ap-northeast-1.amazonaws.com/public/member_id/xxx.txt'

const url = new URL('https://tlc-test-public.s3-ap-northeast-1.amazonaws.com/public/member_id/xxx.txt');
let stream = fs.createReadStream(url.href);

const url = new URL('https://tlc-test-public.s3-ap-northeast-1.amazonaws.com/public/member_id/xxx.txt');
let stream = fs.createReadStream(url.href);

var reader = rd.createInterface({input: stream });
 var lineArray: string[] = new Array;
reader.on('line', (memberId: string) => {
    lineArray.push(memberId);
    console.log(memberId);
});

I am expecting read this text file and print in console line by line.

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!
