### ISSUE TITLE
tsx/React - generic children behave differently than generic prop

### ISSUE THREAD

**Issue by Wexcode** [microsoft/TypeScript#32485]
Here is some code that is able to correctly determine when my types are incompatible using props:

```
type Option<T> = {
  value: T;
  text: string;
}

type SelectProps<T> = {
  value: T;
  options: Option<T>[];
}
```

    const options = [
      { value: 5, text: 'Five' },
      { value: 10, text: 'Ten'}
    ];
    return <Select value="Text" options={options} />; // ERROR: value isn't type number

Here is the same code, but using children I do not get type errors:

```
type OptionProps<T> = {
  value: T;
  children: string;
}

type SelectProps<T> {
  value: T;
  children: React.ReactElement<OptionProps<T>>;
}
```

    /* No errors here */

    <Select value="Text">
      <Option value={5}>Five</Option>
      <Option value={10}>Ten</Option>
    </Select>

I put together a more complete example in this codesandbox (the code from the sandbox can be found below): https://codesandbox.io/s/throbbing-sun-tg48b - Note how `renderA` correctly identifies the error, where as `renderB` incorrectly has no errors.

    import * as React from 'react';
    
    type OptionA<T> = {
      value: T;
      text: string;
    }
    
    type SelectAProps<T> = {
      value: T;
      options: OptionA<T>[];
      onClick: (value: T) => void;
    }
    
    class SelectA<T> extends React.Component<SelectAProps<T>> {
      renderOption = (option: OptionA<T>) => {
        const { value, text } = option;
        const onClick = () => {
          this.props.onClick(value)
        };
        return <div onClick={onClick}>{text}</div>
      }
    
      render(): React.ReactNode {
        return <div>{this.props.options.map(this.renderOption)}</div>
      }
    }
    
    type OptionBProps<T> = {
      value: T;
      children: string;
    }
    
    class OptionB<T> extends React.Component<OptionBProps<T>> {}
    
    type SelectBProps<T> = {
      value: T;
      children: React.ReactElement<OptionBProps<T>>[];
      onClick: (value: T) => void;
    }
    
    class SelectB<T> extends React.Component<SelectBProps<T>> {
      renderOption = (option: OptionB<T>) => {
        const { value, children } = option.props;
        const onClick = () => {
          this.props.onClick(value)
        };
        return <div onClick={onClick}>{children}</div>
      }
    
      render(): React.ReactNode {
        return <div>{React.Children.map(this.props.children, this.renderOption)}</div>
      }
    }
    
    class Main extends React.Component {
      onClick(value: string) {
        console.log(value);
      }
    
      renderA(): React.ReactNode {
        const options = [
          { value: 5, text: 'Five' },
          { value: 10, text: 'Ten'}
        ]
        return <SelectA value="Text" options={options} onClick={this.onClick} />
      }
    
      renderB(): React.ReactNode {
        return (
          <SelectB value="Text" onClick={this.onClick}>
            <OptionB value={5}>Five</OptionB>
            <OptionB value={10}>Ten</OptionB>
          </SelectB>
        );
      }
    }

**Comment by weswigham** [comment]
I believe https://github.com/microsoft/TypeScript/pull/29818 should fix this - a JSX tag, today always just is JSX.Element, (which is a `React.ReactComponent<any>` in the case of `react`), so `children` based on JSX tags can never have strongly checked types.
