### ISSUE TITLE
TS-Check: Property 'createEventObject' does not exist on type 'Document'

### ISSUE THREAD

**Issue by Friksel** [microsoft/TypeScript#32498]
Writing Javascript with `// @ts-check` on throws an error on `document.createEventObject()`:

![image](https://user-images.githubusercontent.com/3089978/61579381-8c164780-ab04-11e9-8898-0117fe3526e5.png)

Please fill in the *entire* template below.
-->

**TypeScript Version:**  Writing Javascript with VS Code v1.36.1

**Search Terms:** ts-check createEventObject

**Code**

![image](https://user-images.githubusercontent.com/3089978/61579381-8c164780-ab04-11e9-8898-0117fe3526e5.png)

**Expected behavior:**

Method recognised and marked as fine.

**Actual behavior:**

Code not recognised and marked as an error.

**Comment by j-oliveras** [comment]
[That is Internet Explorer specific and was removed on version 1.5](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#dom-interface-changes).

You can extend global Document interface to add it:
```ts
declare interface Document {
    createEventObject(): any;
}
```

**Comment by Friksel** [comment]
> [That is Internet Explorer specific and was removed on version 1.5](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#dom-interface-changes).
> 
> You can extend global Document interface to add it:
> 
> ```ts
> declare interface Document {
>     createEventObject(): any;
> }
> ```

Well if more definitions are needed than I'd say I could as well switch from Javascript to Typescript (which I don't want, I just want to check existing Javascript, which according to docs should be possible with Javascript). I don't really understand what's the use of being able to use `// @ ts-check` on Javascript if we need to define even build in DOM behaviour. Yes, this is an older method, but this is behind a conditional for older browsers only, so it makes sense to have older document methods there I'd say.

**Comment by Friksel** [comment]
> [That is Internet Explorer specific and was removed on version 1.5](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#dom-interface-changes).
> 
> You can extend global Document interface to add it:

Thanks for this workaround.
Well if more definitions are needed for build in document methods than I'd say I could as well switch from Javascript to Typescript (which I don't want, I just want to check existing Javascript, which according to docs should be possible with Javascript). 

In the docs it says `// @ ts-check` could be used on Javascript too. But if we need to define all kinds of even build in DOM methods in Javascript files / definition files than what's the use of writing Javascript instead of Typescript I wonder?

Yes, this is an older method, but this is behind a conditional for older browsers only, so it makes sense to have older document methods there I'd say.

**Comment by nattthebear** [comment]
> what's the use of writing Javascript instead of Typescript I wonder?

Maybe there isn't, for your use case.  Typescript's JS support is a "best effort" that attempts to do as much useful typechecking as possible while still letting you write plain JS.  It's not perfect, and your use case of supporting IE8 in 2019 is uncommon.

You can just ignore that warning, or add some IE8 specific types as needed, so there are solutions available.

**Comment by Friksel** [comment]
> ... and your use case of supporting IE8 in 2019 is uncommon. 
> You can just ignore that warning, or add some IE8 specific types as needed, so there are solutions available.

Thanks for your response. I guess you're right. I could better just remove that old code, because I don't support IE8 anymore anyhow. And just leave ts-check for Javascript. Guess I could add a ts-check, but should always take the results with a grain of salt when using it for Javascript then. So I just leave it and already use es-lint, so that's fine for now than.
