### ISSUE TITLE
Unclear type alias shown for node parameter hint

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#32493]
From https://github.com/microsoft/vscode/issues/76957
**TypeScript Version:**  typescript@3.6.0-dev.20190719

**Search Terms:**
- d.ts
- quick info
- hover

**Code**

For the following  javascript, trigger parameter hints on `createServer`
```ts
const http = require('http'); 
http.createServer(
```

**Expected behavior:**
The function signature of first parameter is shown.

**Actual behavior:**
We show a type alias: `http.RequestListener`. Node defines this type as:

```ts
    type RequestListener = (req: IncomingMessage, res: ServerResponse) => void;
```

**Playground Link:** 

**Related Issues:**

**Comment by mjbvz** [comment]
This would be solved by the interactive quick info proposals we've discussed

**Comment by RyanCavanaugh** [comment]
Duplicate #25784 ?

**Comment by mjbvz** [comment]
Yes. I can't find the interactive hover issue but that would fix these issues
