### ISSUE TITLE
VSCode does not find tsconfig for some new files

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#32508]
**TypeScript Version:**  3.5.3

**Search Terms:** decorator 1219

I have a [project](https://github.com/AlCalzone/node-zwave-js/tree/6371ef5e1f227ef2352e47aa57e2b2c0c70f3a79) which makes heave use of decorators. Very recently (I noticed it today), the language server in VSCode starts reporting that the option `experimentalDecorators` is missing - but only on new files. Also it seems like other options like `strictNullChecks` are also ignored.

Restarting the TSServer or VSCode does not help. tsc on the command line does not throw any errors:
![grafik](https://user-images.githubusercontent.com/17641229/61630036-e808d980-ac86-11e9-9d93-b689f5f8df27.png)

The file on the left is a new file, the one on the right an existing one. Both are in the same directory, and import and use the same decorators. I had the same happen on another new file, but that issue resolved itself after I fixed a strictNullChecks error that was reported only by `tsc`.

Spooky stuff :ghost:

**Comment by AlCalzone** [comment]
I just found this: https://github.com/Microsoft/vscode/issues/38201#issuecomment-344062504
When running the "go to project configuration" command in `LanguageCC.ts`, I get the error "File is not part of a TypeScript project". In `BasicCC.ts`, it works just fine.

**Comment by AlCalzone** [comment]
[tsserver.log](https://github.com/microsoft/TypeScript/files/3417258/tsserver.log)
Heres a TSServer log file where I first open LanguageCC, then BasicCC, in case that helps to track down the error.

**Comment by AlCalzone** [comment]
Interesting:
`"javascript.implicitProjectConfig.experimentalDecorators": true` in settings.json disables at least the TS1219 error, although the file in question has a TypeScript extension?!

**Comment by sheetalkamat** [comment]
This is working as intended. The tsconfig nearest to the file is picked up from vscode which happens to be [src/tsconfig.json](https://github.com/AlCalzone/node-zwave-js/blob/6371ef5e1f227ef2352e47aa57e2b2c0c70f3a79/src/tsconfig.json) which only include test files. If anything references source files then those would be included and that's what happens in case of `BasicCC.ts` which is imported by `BasicCC.test.ts` and hence in the program the new one isnt.
