### ISSUE TITLE
Better Generic Support with JSX

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/TypeScript#32505]
## Search Terms

generic, JSX

## Suggestion

allow for generics in JSX that work the same as function generics (because they are functions)

## Use Cases

Better type inference

## Examples

`name` would resolve to `firstName` instead of `string`

```jsx
import React from 'react';

interface Props<Values, N> {
    render?: (props: FieldProps<Values>) => React.ReactNode;
    children?: (props: FieldProps<Values>) => React.ReactNode;
    validate?: (value: N) => string | Promise<void> | undefined;
    name: N;
    type?: string;
    value?: any;
    innerRef?: (instance: any) => void;
}

export declare class Field<Values = any, N> extends React.Component<Props<Values, N>> {}


interface SignUpFormValues {
  firstName: string;
  lastName: string;
  phone: string;
  password: string;
  tosAgreement: boolean;
}

const MyField: React.SFC = () => (
  <Field<SignUpFormValues> name="firstName">
    {({ field }) => (
      <div className="Field">
        <label
          className="Label Label--fullWidth"
          form="sign-up-form"
          htmlFor="sign-up-form-first-name"
        >
          First name
        </label>
        <input
          id="sign-up-form-first-name"
          placeholder="John"
          type="text"
          {...field}
        />
      </div>
    )}
  </Field>
);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
I think you mean `Field<Values, N  = any>` instead of `Field<Values = any, N>`.

Regardless of this, what you seem to want is partial argument inference and this is not supported for functions either at the moment (see [PR](https://github.com/microsoft/TypeScript/pull/26349) for unfinished proposal to allow this)

For cases where a function would infer `N` to be a string literal type, inference for JSX elements does the same: 

```ts
interface Props<N> {
    name: N;
}

export declare class Field<N extends string> extends React.Component<Props<N>> {}

const MyField: React.SFC = () => ( //name below is inferred as "firstName"
  <Field name="firstName"> 
    
  </Field>
);
```
