### ISSUE TITLE
Include browser compatibility notes in lib.d.ts comments

### ISSUE THREAD

**Issue by flcdrg** [microsoft/TypeScript#3250]
After experiencing a problem caused by using [Element.classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Browser_compatibility) in some TypeScript code that was intended to run on IE8, I'm thinking it would be nice to include in the comments for methods known browser compatibility issues.

If this were done in a 'conventional' way, then it could also be interpreted by tooling much the way that the WebEssentials extension for Visual Studio can show browser support tooltips for CSS. eg.
![css browser support](https://cloud.githubusercontent.com/assets/384747/7763196/b07a7ec0-007c-11e5-8892-a4debf391a20.png)

**Comment by duanyao** [comment]
Seems we want something like this in `lib.d.ts`:
```
interface Element {
  @since("IE10", "Chrome8", "Firefox3.6", "DOM3")
  @deprecated("IE20", "Chrome80", "Firefox80", "DOM8") // just a joke
  @removed("IE30", "Chrome100", "Firefox100", "DOM10") // just a joke
  classList: DOMTokenList;
}
```

**Comment by flcdrg** [comment]
That looks interesting

**Comment by mhegazy** [comment]
We will need a proposal on how the annotations would be added, either JSDoc comments with some special tags, or using https://github.com/Microsoft/TypeScript/issues/2900 (proposed and not implemented yet).

**Comment by RyanCavanaugh** [comment]
We now copy in MDN comments, which should include the most relevant bits. `@deprecated` is also now available
