### ISSUE TITLE
Transform: updateSourceFileNode() with replacement node references old text

### ISSUE THREAD

**Issue by ToddThomson** [microsoft/TypeScript#32500]
I've run into an issue where I have 2 source files:

main.ts
```
import { s }  from "./test/importref"
```
and test/importref.ts
```
export var s = 7;
```
The transform on main gets the sourcefile of the referenced import in main and then calls:
```
return ts.updateSourceFileNode( mainSourceFile, importRefSourceFile.statements );
```
The output is:
```
"use strict";
Object.defineProperty( exports, "__esModule", { value: true } );
exports.s = fr; 
```
I expected the `exports.s = fr;` to be `exports.s = 7;`

It seems that the "fr" is coming from the original text in the original source node.
```
import { s }  from "./test/importref"
export var s = 7;
```

**Comment by ToddThomson** [comment]
When copying nodes from another source file the emitter function emitLiteral uses the currentSourceFile to obtain the numeric literal if the statements from the other source file are not synthesized.
The question is: how to read the statements from the other sourcefile and get a synthesized clone of each?
Any help would be greatly appreciated!

**Comment by RyanCavanaugh** [comment]
You need to clone nodes whenever you move them around; it's not safe to reparent (as you noticed).

We have several dozen existing refactors you can look at as a reference for how to handle this.

**Comment by ToddThomson** [comment]
@RyanCavanaugh Thanks. I'll take a look...

**Comment by ToddThomson** [comment]
@RyanCavanaugh Originally, I ran into issues because I assumed that calling ```ts.getMutableClone()``` on the statement from the referenced source file would "reparent" the statement node chain to the synthesized node. In my case this was the ```export var s = 7``` statement. The declarationList and child declaration still referenced the original parent node.
I can write my own getDeepMutableClone() which visits the node children and adjusts the parent nodes.
I am not sure that when creating a synthesized node array from mutable statements that the contained declarationList node and declaration node parent, pos and end make any sense. However, this scenario is likely not encountered much.

**Comment by ToddThomson** [comment]
@RyanCavanaugh Thanks for you help!

**Comment by ToddThomson** [comment]
Ok, recursively visiting the children of the synthesized clone and adjust the node.parent, node.pos and node.end works for me!
