### ISSUE TITLE
Chinese Document Error

### ISSUE THREAD

**Issue by MiduoWiki** [microsoft/TypeScript#32510]
Chinese Document Error？

`class Control {
    private state: any;
}

interface SelectableControl extends Control {
    select(): void;
}

class Button extends Control implements SelectableControl {
    select() { }
}

class TextBox extends Control {
    select() { }
}

// 错误：“Image”类型缺少“state”属性。
class Image implements SelectableControl {
    select() { }
}

class Location {

}`

`在Control类内部，是允许通过SelectableControl的实例来访问私有成员state的。 实际上， SelectableControl接口和拥有select方法的Control类是一样的。 Button和TextBox类是SelectableControl的子类（因为它们都继承自Control并有select方法），但Image和Location类并不是这样的。`

**Button和TextBox类是SelectableControl的子类（因为它们都继承自Control并有select方法）**

SelectableControl is Control。  

doc => interface =>doc end

Forgive me for my poor English expression，sorry。

**Comment by trotyl** [comment]
See https://github.com/microsoft/TypeScript/issues/31554#issuecomment-495813004

**Comment by MiduoWiki** [comment]
@trotyl  大兄弟，所以。。。我们应该看什么文档。。。这个文档过时很久啦？。。。。这么坑？
