### ISSUE TITLE
TypeScript unable to infer correct type of thisArg in Array.prototype.forEach()

### ISSUE THREAD

**Issue by Newbytee** [microsoft/TypeScript#32512]
**TypeScript Version:** 3.6.0-dev.20190720

**Search Terms:**
set, array, forEach, this

**Code**

```ts
class ClassThatUsesForEach {
    public add() {
        this.set.forEach(function(n: number)
            this.gatherer += n;
        }, this);
    }

    public getGatherer(): number {
        return this.gatherer;
    }

    private set = new Set([ 5, 10, 60 ]);
    private gatherer = 0;
}

function assertEqual(param1: number, param2: number) {
    return param1 === param2;
}

const cls = new ClassThatUsesForEach();

cls.add();

console.log(cls.getGatherer());

console.log(assertEqual(cls.getGatherer(), 5 + 10 + 60));
```

**Expected behavior:**
I expect this code to compile correctly, as it works and TypeScript should be able to infer the type of `this`.  

**Actual behavior:**
TypeScript does compile this, as long as `--strict` is set to false. However, with `--strict` set to true, theTypeScript compiler refuses to compile the code, citing TS2683 ('this' implicitly has type 'any' because it does not have a type annotation). I believe this should not be the case, as `this` should refer to the class, and not the function when the thisArg is set ([related MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)). 

**Playground Link:** 
[Here](https://www.typescriptlang.org/play/#code/MYGwhgzhAEDC5QCoAswBcCqECmEBiA9gE4CiYwy0A3gFDT3QAOArgEYgCWw0YAJrwAoAlNToNxaZBwgA6HGhkAzYmQoDFzAHbA0HApoGaAXNE3MAtq2xERtcfYaTpMgObpk169ADUAXlMA3GIOAL4ANNBOEEJB4iE0wUxsnNwu2GgA4u6eRMImZpZedg7QROnMRJqRUrJukjmxDPGJjEQcAG7o2NDy0P6a2ADu0ADK6QIA2tAArBEAjAAMEQBsC9AAujEtbZ1o3XUeZUR90AtBzRrauvo8UNZoJACOzGAgAoxgRGDmc-kWVkQIh8vuYAEx-Qo2UTiMpoCpVYHfOZ9Xz+RFg84JYD6CBoaCgGD9IZwBAQFDoLC4QikcjIYRBGgEmR8QRbRk4gggbAyEAEFwCJlpTLZI7CNnYzQQTnc3n8yA4IgPZ6vAUgWrpLL1UVCCLTHzQRb61ZCLZAA)

**Related Issues:** 
I have not found any.

**Comment by jack-williams** [comment]
This was previously implemented and then removed - the associated PR is here #16223.

**Comment by jcalz** [comment]
One workaround here would be to [merge in](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) your own declaration for that method:

```ts
// declare global { // uncomment if in a module scope
interface Set<T> {
  forEach<This>(
    callbackfn: (this: This, value: T, value2: T, set: this) => void,
    thisArg?: This
  ): void;
}
// } // // uncomment if in a module scope
```

That should make your code compile while you wait for (or in lieu of) an upstream change.

**Comment by Newbie13XD** [comment]
> This was previously implemented for Array and then removed - the associated PR is here #16223. The same reasoning probably applies to Set.

In other words, it most likely will not be resolved until someone figures out a more lightweight solution?

**Comment by danvk** [comment]
@jack-williams The reversion PR was merged in mid-2017. I wonder if anything has changed since then that would warrant revisiting? It is surprising that passing an explicit `this` argument to `Array.prototype.forEach` doesn't set the type of `this` in the callback.
