### ISSUE TITLE
Have to cast source file to definition file type even though they are the same thing

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/TypeScript#32516]
I have two projects, `@red5/server` and `@red5/session`, each of them reference each other, but basically `@red5/session` references the definition file and `@red5/server` references the source file and that gives me the following error:

```Argument of type 'this' is not assignable to parameter of type 'Client'.
  Type 'import("red5/framework/server/src/Client").Client' is not assignable to type 'import("red5/framework/server/node_modules/@red5/server/types/Client").Client'.
    Types have separate declarations of a private property '_post'.ts(2345)
```

The only way I can get around this is to cast it to the definition file type (`<import('@red5/server').Client><unknown>`) even though they are technically the same thing... Am I doing this an incorrect way or is there some underlying issue here?

I would however think that I shouldn't have to cast it because they are the same thing at least they are supposed to be.

**@red5/server/Server.ts**
```typescript
class Client {
  private _post: any = {}
  public async method() {
    // This line references a .d.ts file:
    let sess = await import('@red5/session')

    // This gives an error:
    let session = new sess.Session(this)

    // This doesn't give an error:
    let session = new sess.Session(<import('@red5/server').Client><unknown>this)
  }
}
```

**@red5/server/types/Client.d.ts**
```typescript
export declare class Client {
    private _post;
}
```

**@red5/session/types/Session.d.ts**
```typescript
import { Client } from '@red5/server';
export declare class Session {
    constructor(client: Client);
}
```

**Comment by RyanCavanaugh** [comment]
This is a correct error. There are two different classes; these two different classes may have different types or interpretation of `_post`, and it is not safe to use one in place of the other. It sounds like you need to fix your module resolution so that both imports resolve to the same place.

**Comment by TheColorRed** [comment]
Wouldn't that mean that the definition file would need to resolve to a source file?

**Comment by RyanCavanaugh** [comment]
I don't know enough about how you've set up your project to be able to advise further.

**Comment by TheColorRed** [comment]
I am using `npm link`, and as I am reading, the could be the cause of the issue as noted in other reports.

**Comment by TheColorRed** [comment]
So, I have setup `paths` in the `tsconfig.json`, and my source files all resolve correctly now, but my `.d.ts` files don't resolve the same way, shouldn't they also resolve the same as the source files?

**index.ts**
```
// Resolves: "/home/ryan/Documents/vscode/projects/red5/framework/server/types/index"
import { Plugin } from '@red5/server'
```

**index.d.ts***
```
// Resolves: "/home/ryan/Documents/vscode/projects/red5/framework/plugins/session/node_modules/@red5/server/types/index"
import { Plugin } from '@red5/server'
```

Thinking about this, would this be because the files are in two different locations and the `tsconfig.json` points to the `src` directory and the types are outside of that directory?
