### ISSUE TITLE
add api create validator from .d.ts content

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#32518]
## Suggestion

```js
const TypeScript = require('typescript');

const validator = TypeScript.Validator(`
    export const a :{
        x :1,
        y :2,
    };
`).default;// content of .d.ts

validator({ x: 1, y: 2 });// true
validator({ x: 2 });// false
```

## Use Cases

Then my bundler can use that API to verify the data with .d.ts file which kills two birds with one stone.

```
/a.ts
/b.ts
/c.json
/c.d.ts
/d.json5
/d.d.ts
/e.yaml
/e.d.ts
/f.toml
/f.d.ts
```

## Examples

See suggestion.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
https://github.com/YousefED/typescript-json-schema + https://github.com/epoberezkin/ajv ?
