### ISSUE TITLE
Constructor constraint not working for inherit classes

### ISSUE THREAD

**Issue by klaytoncbrito** [microsoft/TypeScript#32522]
I'm trying create a concrete rep class extending a generic abstract class rep, but I've shown a syntax error where I can't put a class that obey the rules:

```
Type 'Bar' does not satisfy the constraint 'new (c?: Foo | undefined) => Bar'.
  Type 'Bar' provides no match for the signature 'new (c?: Foo | undefined): Bar'."
```

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
Constructor constraint, Extends constructor in a abstract class

**Code**

```
interface Foo {

    a: number;
}

class Bar {

    b?: number;

    constructor(c?: Foo) {

        if (c) {

            this.b = c.a;
        }
    }
}


abstract class RepBase<F, B extends { new(c?: F): B }> {

    doSomething() {

    }
}

class RepConcrete extends RepBase<Foo, Bar> {

}
```

**Expected behavior:**
Compile successfully

**Actual behavior:**
Syntax error

**Playground Link:** 
https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQByxycAXMiAK4C2ARtANwEC+BBCANnAM4-IAhOFBzt8JZHQD8FavSZiJCdCB5goVBGHRQAFAhlpMASlGFxEksBjJ9pvOctPkYABbAeAOjrIAvMgRPOGYLJzZQ5HDwsTg6NShEMADuPmQAJQgAByEeCAAeVAAaQWQIAA9IEAATfmxKCAB3fUNUYwoBSIA+MyISKvQAZXQaCDdQAHNde0USKLEuXn4MzIBhFQQoUZRyypr0rJz8jHRioShuhzEWIA

**Comment by dragomirtitian** [comment]
This is a question, not an issue you should use [SO](https://stackoverflow.com/questions/tagged/typescript) 
for questions. 

Hint: For starters, you are using the instance type instead of the class type

**Comment by klaytoncbrito** [comment]
Sorry, I will close this issue.
