### ISSUE TITLE
Destructuring the arguments variable

### ISSUE THREAD

**Issue by tylergoodman** [Microsoft/TypeScript#3252]
Doesn't work because the IArguments interface isn't defined as an Array type. Is there a reason behind this?

Example:
```javascript
function test () {
  var [a] = arguments; // Error: Type 'IArguments' is not an array type.
}
```

One solution is doing this:
```javascript
function (...args) {
  var [ one, two, three ] = args;
}
```

**Comment by kitsonk** [comment]
Because arguments is not an array.  It is ["Array-like"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) but it isn't a true array.

**Comment by SaschaNaz** [comment]
`var [a] = Array.from(arguments)` should work here.

**Comment by DanielRosenwasser** [comment]
As a side question, why don't you use parameters instead of destructuring the `arguments` object? Is there a specific use-case you're trying to accomplish?

**Comment by kitsonk** [comment]
> `var [a] = Array.from(arguments)` should work here.

`Array.from` is only ES6 and only implemented in Firefox [actually](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from).  `var [a] = Array.prototype.slice.call(arguments)` is better for now.

**Comment by tylergoodman** [comment]
@kitsonk I understand that the arguments variable is an array-like. But aren't array-destructuring assignments of array-like objects valid javascript?

ES6 will only allow array-destructuring of an array-like if the object has an iterator.  Here's an example of what I mean:

```javascript
var obj = {
  0: 'foo',
  1: 'bar',
  2: 'baz',
  length: 3,

  // required
  * [Symbol.iterator]() {
    for (var i = 0, len = this.length; i < len; i++) {
      yield this[i];
    }
  }
};

var [a, b, c] = obj;
console.log(a, b, c); // 'foo bar baz'
```

Because `arguments` is supposed to be iterable in ES6, this should work too:

```javascript
function fun () {
  var [a, b, c] = arguments;
  console.log(a, b, c); // 'foo bar baz'
}

fun('foo', 'bar', 'baz');
```
I don't think anyone has this implemented `arguments` being iterable yet though as far as I know.

---

In Typescript, destructuring assignments made while in ES6 mode compile directly to ES6 destructuring assignments
```javascript
// this javascript and typescript are equivalent
var arr = ['foo', 'bar', 'baz'];
var [a, b, c] = arr;
```

And in ES3/5 mode the assignment is converted into a series of assignments
```javascript
var arr = ['foo', 'bar', 'baz'];
var a = arr[0], b = arr[1], c = arr[2];
```

In both modes, the resulting javascript works (or will work (right?)). Is there a reason that array-destructuring of `arguments` and other array-like objects isn't allowed? Is it just something that hasn't been fully looked at yet?

**Comment by kitsonk** [comment]
> I understand that the arguments variable is an array-like. But aren't array-destructuring assignments of array-like objects valid javascript?

But you are using TypeScript and using an implicit cast which doesn't work, ergo the `Error: Type 'IArguments' is not an array type.`

> In Typescript, destructuring assignments made while in ES6 mode compile directly to ES6 destructuring assignments
>

This is assigning an Array to an Array.  Not an array-like to an Array.  Destructing assignments !== breaking typing rules in TypeScript.

**Comment by jods4** [comment]
@kitsonk 
> But you are using TypeScript and using an implicit cast which doesn't work, ergo the  Error: Type 'IArguments' is not an array type.

I haven't checked the ES2015 spec, but if it says that the destructuring syntax can be applied to an array-like object with an iterator, then I think it should be valid TS. No implicit cast to array should be required here and that's the bug in the first place.

It is my understanding that TS is designed to be a superset of JS and it fails here. Not that I think this feature is mega-useful but just sayin'.

**Comment by SaschaNaz** [comment]
Chrome supports `arguments[Symbol.iterator]` but Firefox does not, so the code will cause an error on Firefox. Is this in the ES6 spec?

**Comment by DanielRosenwasser** [comment]
> Is this in the ES6 spec?

From my understanding, yes. See the [*CreateUnmappedArgumentsObject*](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-createunmappedargumentsobject) and [* CreateMappedArgumentsObject*](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-createmappedargumentsobject) abstract operations.

Given the direction that we've been taking with `arguments` recently, I'm inclined to liken this to "doctor it hurts when I use the `arguments` object". There's already a fairly sufficient way of destructuring `arguments`: formal parameters.

Still, as a matter of consistency, I'm going to ping @JsonFreeman because of he's done some recent work on destructuring that might need to be informed regarding this.

**Comment by jods4** [comment]
@DanielRosenwasser I agree 100% that `arguments` have no good use in ES6. But note that the real issue here is more general. It's not just `arguments` that doesn't work but any array-like, iterable object.

I have no good use-case and don't really care (right now), but this is a deviation from ES6 spec and it could be that some people find clever use for iterable objects. After all, this is still new and mostly unused stuff.

So the question is really: how compatible with ES2015 does TS want to be?

**Comment by SaschaNaz** [comment]
NodeList can be another example, while I don't know this is in spec or not. NodeList objects have iterator in Firefox but not in Chrome.

**Comment by JsonFreeman** [comment]
Does arguments have slice? In order to destructure with a rest element, you need slice.

**Comment by DanielRosenwasser** [comment]
@JsonFreeman in my mind, we'd permit destructuring arguments when targeting ES6 (because `IArguments` should have an iterator). Otherwise, don't bother.

**Comment by SaschaNaz** [comment]
Or use `Array.prototype.slice.call(arguments)`.

**Comment by JsonFreeman** [comment]
I guess we could support it in ES6 if there is enough demand.

**Comment by jods4** [comment]
Funny coincidence. Yesterday Mozilla has published the new part in their ES6 In Depth series, this time about destructuring:
https://hacks.mozilla.org/2015/05/es6-in-depth-destructuring/

This has quite some visibility and it talks about destructuring iterables. There is one chapter called *Destructuring arrays and iterables* and it ends with an explicit mention of array assignment pattern working for any iterable plus a code example (your classical fibonacci sequence).

> Note that destructuring assignment with an array assignment pattern also works for any iterable:
```js
function* fibs() {
  var a = 0;
  var b = 1;
  while (true) {
    yield a;
    [a, b] = [b, a + b];
  }
}
var [first, second, third, fourth, fifth, sixth] = fibs();
console.log(sixth);
// 5
```

**Comment by JsonFreeman** [comment]
This already works in typescript. The type system allows you to destructure an iterable into an array. The problem is that IArguments is not iterable in lib.d.ts. The fix is to make it iterable.

**Comment by DanielRosenwasser** [comment]
I have a PR (#3306) so that you'll be able to do this when using ES6 as a target.

**Comment by DanielRosenwasser** [comment]
The change is now in `master`.

**Comment by tylergoodman** [comment]
Thanks for the fix @DanielRosenwasser .  Concerning ES5-targeted code, is there any chance that array-destructuring of array-like objects will be implemented in the future?  TS would have to detect that it's an object and call the `.slice()` function on the prototype instead of calling it directly on the variable, I guess.  Something like this.

```javascript
// typescript
var arrayLike = {
	'0': 'foo',
	'1': 'bar',
	'2': 'baz'
};
var [foo, ...bar] = arrayLike;
console.log(foo, bar); // 'foo', ['bar', 'baz']
```

```javascript
// output
var arrayLike = {
    '0': 'foo',
    '1': 'bar',
    '2': 'baz'
};
var foo = arrayLike[0], bar = arrayLike.slice(1); // error
```

```javascript
// desired output
var arrayLike = {
	'0': 'foo',
	'1': 'bar',
	'2': 'baz'
};
var foo = arrayLike[0], bar = Array.prototype.slice.call(arrayLike, 1);
console.log(foo, bar); // 'foo', ['bar', 'baz']
```

**Comment by DanielRosenwasser** [comment]
@tylergoodman no problem - if you'd be willing to open up a separate issue as a suggestion, we could discuss the possibility among the team.

**Comment by JsonFreeman** [comment]
@tylergoodman If you open an issue for this, please mention the issue number here.

**Comment by tylergoodman** [comment]
#3389
