### ISSUE TITLE
Bad completions for `import.meta`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#32528]
```ts
let x = import.meta./**/
```

1. Go to `/**/` with an empty definition of the global `ImportMeta` type.
1. Request completions

**Expected**

No completion entry for `meta`

**Actual**

Completion entry for a bogus `meta` property.

**Comment by 9at8** [comment]
Hey @DanielRosenwasser, I would love to take this on!

**Comment by DanielRosenwasser** [comment]
Give it a shot!

**Comment by 9at8** [comment]
Update:

I was able to reproduce it using a stable version of vscode, but I'm trying to set up a dev build of vscode by following [this](https://github.com/microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code).

I'll take a look around [these lines](https://github.com/microsoft/TypeScript/blob/master/src/services/completions.ts#L793-L796) after setting up my env.

Let me know if you think I should be looking at something else! :slightly_smiling_face:

**Comment by sheonhan** [comment]
Hi, @DanielRosenwasser. Can I try working on this? 
I have a couple questions: 
1) Would this involve setting up dev VS Code with dev TSServer as it's mentioned above? 
2) Since I'm new to the project, any entry point or similar—or even mildly related—pull requests in the past would be super helpful.

**Comment by DanielRosenwasser** [comment]
Not by the codebase right now. I can't think of specific PRs - just dig around `src/services/completions.ts` if that's there.

You don't need to try out the language service locally, though you can set `typescript.tssdk` to the `built/local` folder to iteratre faster. You should have a test in `tests/fourslash` though.

Also make sure you read a bit on https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md

**Comment by sheonhan** [comment]
Hi @DanielRosenwasser, I have a PR up for this issue here: https://github.com/microsoft/TypeScript/pull/35844.
Thanks!

**Comment by DanielRosenwasser** [comment]
Thanks @sheonhan!
