### ISSUE TITLE
Generator: infer the type of yield expression based on yielded value

### ISSUE THREAD

**Issue by Retsam** [microsoft/TypeScript#32523]
## Search Terms

generator, iterator, yield, type inference, redux-saga, coroutine, co, ember-concurrency

## Suggestion

There are a number of JS patterns that require a generator to be able to infer the type of a `yield` statement based on the value that was `yield`ed from the generator in order to be type-safe.  

Since #2983 was something of a "catch-all" issue for generators, now that it has closed (🙌) there isn't a specific issue that tracks this potential improvement, as far as I can tell.  (A number of previous issues on this topic were closed in favor of that issue, e.g. #26959, #10148)

### Use Case 1 - coroutines

A coroutine is essentially `async/await` implemented via generators, rather than through special language syntax. [1]  There exist a number of implementations, such as [Bluebird.coroutine](http://bluebirdjs.com/docs/api/promise.coroutine.html), the [co library](https://github.com/tj/co), and similar concepts such as [ember-concurrency](http://ember-concurrency.com/docs/introduction/)  

In all cases, it's pretty much syntactically identical to `async/await`, except using `function*` instead of `async function` and `yield` instead of `await`:

```ts
type User = {name: string};
declare const getUserId: () => Promise<string>;
declare const getUser: (id: string) => Promise<User>;

const getUsername = coroutine(function*() {
    // Since a `Promise<string>` was yielded, type of `id` should be string.
    const id = yield getUserId(); 
    // Since a `Promise<User>` was yielded, type of `user` should be `User`
    const user = yield getUser(id);
    return user.name;
});
```

Currently, there really isn't a better approach than explicit type annotations on every yield statement, which is completely unverified by the type-checker:

```ts
const getUsername = coroutine(function*() {
    const id: string = yield getUserId(); 
    const user: User = yield getUser(id);
    return user.name;
});
```

The most correct we can be right now, with TS3.6 would be to express the generator type as `Generator<Promise<string> |  Promise<User>, string, string  |  User>`  - but even that would require every the result of every `yield` to be discriminated between `string` and `User`.

It's clearly not possible to know what the type of a yield expression is just by looking at the generator function, but ideally the types for `coroutine` could express the relationship between the value yielded and the resulting expression type: which is something like `type ResumedValueType<Yielded> = Yielded extends Promise<infer T> ? T : Yielded`.

### Use Case 2 - redux-saga

redux-saga is a (fairly popular) middleware for handling asynchronous effects in a redux app.  Sagas are written as generator functions, which can yield specific effect objects, and the resulting expression type (and the runtime behavior) depend on the value yielded. 

For example, the `call` effect can be used analogously to the coroutine examples above: the generator will call the passed function, which may be asynchronous, and return the resulting value:

```ts
function* fetchUser(action: {payload: {userId: string}}) {
   try {
      const user = yield call(getUser, action.payload.userId);
      yield put({type: "USER_FETCH_SUCCEEDED", user: user});
   } catch (e) {
      yield put({type: "USER_FETCH_FAILED", message: e.message});
   }
}
```

The relationship between the `yield`ed value and the resulting value is more complex as there are [a lot of possible effects that could be yielded](https://redux-saga.js.org/docs/api/index.html), but the resulting type could still hypothetically be determined based on the value that was yielded.

This above code is likely even a bit tricker than the coroutine as the saga generators aren't generally wrapped in a function that could hypothetically be used to infer the `yield` relationship: but if it were possible to solve the `coroutine` case, a wrapping function for the purposes of TS could likely be introduced:

```ts
// SagaGenerator would be a type that somehow expressed the relationship 
// between the yielded values and the resulting yield expression types.
function saga<TIn, TReturn>(generator: SagaGenerator<TIn, TReturn>) { return generator; }

const fetchUser = saga(function*() {
   //...
});
```

--- 

I imagine this would be a difficult issue to tackle, but it could open up a lot of really expressive patterns with full type-safety if it can be handled.  In any case, thanks for all the hard work on making TS awesome!

---

[1] As an aside, to the tangential question of "why would you use a coroutine instead of just using `async/await`?".  One common reason is cancellation - Bluebird promises can be cancelled, and the cancellation can propagate backwards up the promise chain, (allowing resources to be disposed or API requests to be aborted or for polling to stop, etc), which doesn't work if there's a native `async/await` layer.

**Comment by yortus** [comment]
For reference, there's some discussion and ideas about this in #30790 (e.g. https://github.com/microsoft/TypeScript/pull/30790#issuecomment-480478453).

**Comment by rbuckton** [comment]
This is not currently possible to model in the type system, as is mentioned in #30790, as it requires some mechanism to define a relationship between a TYield and a TNext to be preserved between separate invocations.

**Comment by treybrisbane** [comment]
Two additional use cases are:

- Emulation of Haskell's `do` syntax for sequencing monadic actions ([example](https://github.com/Microsoft/TypeScript/issues/2983#issuecomment-338435221))
- Emulation of Algebraic Effects ([explanation](https://overreacted.io/algebraic-effects-for-the-rest-of-us/), and [example](https://dev.to/yelouafi/algebraic-effects-in-javascript-part-4---implementing-algebraic-effects-and-handlers-2703))

**Comment by falsandtru** [comment]
You need Rank-2 types: https://prime.haskell.org/wiki/Rank2Types

**Comment by kingdaro** [comment]
```ts
type TestGen = {
  next<T>(value: T): IteratorResult<Promise<T>, any>
}

function* test(): TestGen {
  const value = yield Promise.resolve(123)
}
```
I just tried this, currently it errors on `Promise.resolve(123)`

```
Type 'Promise<number>' is not assignable to type 'Promise<T>'.
  Type 'number' is not assignable to type 'T'.
    'number' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
```

Would it be possible to support this use case this way?

**Comment by rbuckton** [comment]
> Would it be possible to support this use case this way?

No, it is not possible. Your definition of `TestAsyncGen` doesn't actually reflect what's happening in the generator. The definition `next<T>(value: T): IteratorResult<Promise<T>, void>` implies that calling `next` will with a value of `T` will produce a `Promise<T>`. However, what is actually happening is that you want the `Promise<T>` of one call to `next` to become the `T` of a *subsequent* call to `next`. The type system has no way to handle that today.

What you would need is something like https://github.com/microsoft/TypeScript/pull/32695#issuecomment-523733928, where calling a method can evolve the `this` type:

```ts
interface Start<R> {
  next<T>(): IteratorResult<Promise<T>, Promise<R>> & asserts this is Resume<T, R>;
}
interface Resume<T, R> {
  next<U>(value: T): IteratorResult<Promise<U>, Promise<R>> & asserts this is Resume<U, R>;
}
```

If such a feature were to make it into the language, *then* you would be able to inform the `T` of a *subsequent* call to `next` based on the return type of a *preceding* call to `next`.

**Comment by spion** [comment]
Another alternative is to have a richer model for generator functions.

```typescript
type GeneratorFunction2<IterType, ReturnType, YieldType extends Function> = {
  ():IterableIterator<IterType, ReturnType>
  __yield: YieldType; // replace with some TS only symbol maybe
}

type AwaitingYield = <T>(p:Promise<T>) => T;

declare let someFn:GeneratorFunction2<Promise<unknown>, Promise<string>, AwaitingYield>
```

**Comment by ccorcos** [comment]
I'm very interested in support for algebraic effects really just for one use-case: 

I have a database that I want to be able to run async with a backend or sync in memory.

I believe coroutines / generators are a perfect way to do this. The types don't quite work out but I feel like its pretty close:

```ts
export type API = {
	get: {
		request: { type: "get"; id: string }
		response: { id: string; value: any }
	}
	set: {
		request: { type: "set"; id: string; value: any }
		response: void
	}
}

function syncApi<T extends keyof API>(
	request: API[T]["request"]
): API[T]["response"] {
	return {} as any
}

async function asyncApi<T extends keyof API>(
	request: API[T]["request"]
): Promise<API[T]["response"]> {
	return {} as any
}

// Define a custom IterableIterator class.
interface APIGenerator {
	next<T extends keyof API>(
		response: API[T]["response"]
	): IteratorResult<API[T]["request"], void>
	[Symbol.iterator](): APIGenerator
}

// Some helpers
function get(id: string): API["get"]["request"] {
	return { type: "get", id }
}

function set(id: string, value: any): API["set"]["request"] {
	return { type: "set", id, value }
}

// Reusable logic that works for both sync and async code.
// It appears to typecheck, but the return value from yield doesn't resolve.
function* logic(): APIGenerator {
	const x = yield get("1") // const x: API[T]["response"]
	x.id // 💥
	x.value // 💥
	const y = yield set("2", 3) // const y: API[T]["response"]
}

// Here's how we can evaluate both sync and async
function runSync() {
	const gen = logic()
	let request = gen.next() // 🤔 what do we pass here?
	while (request.value !== undefined) {
		request = gen.next(syncApi(request.value))
	}
}

async function runAsync() {
	const gen = logic()
	let request = gen.next() // 🤔 what do we pass here?
	while (request.value !== undefined) {
		request = gen.next(await asyncApi(request.value))
	}
}
```

[playground](https://www.typescriptlang.org/play/#code/PTAEEEBsHMFMCMBOBDAlgY1AUQGY9ugC4DOEACgJIB0AULAB4AOA9ooaIQJ6OzkWgBeUAG8aASDiEAXCPFjEsAI4BXWMWkiO3WDIBEk3QG5QqACYz1iVADtooAL5yFxFteI7NZi4Su3jAN2RIVRlka04HcUcxdw1RMXklVXUZYS0ePVijE3NQSxtoAKCQ0DCI6MSXZjcPf2YzKJpHGhxlayJUarzOdvBGVAAeABVQBkJYa1NSAGtYTmYcPgA+AApxBRU1DXBKAG0hgF1d3Q3kwl0DmgBKGR2KfaOTtVd3C9lEwmVEaxF7UtIyk0aDRkMQephWu1CJ0fqDwX1BiMxhMpqBZvNFndVuskltbntDsdTlsLtcZGREMwALaodwDO4PInPaqvA5Ld4KT7fX7-UrhIE0ECgAAisBwNl4yFA6GU6mpoAo4xQ8EgsEVsBQhFY0sgoOItBsSpwyHQvDuAHEJhrkFrEO9rGNhqN6ONJjM5gtlmsEs4Xh4GYSnlUaqSxDcFUqbawAEpqZSQQj0gmPYnqC4AGlAdTMS3EuwAypwqfBmJAqKhI7aDitwxarZrWAKhfnqbwABawSA8RDEFptDpdSQrLx5HwFWt7fSwc4p3Fpg4c6dfH5pLgZUBT86ZsyRZqQgc-WLD3L5WyZwLBDxlCf3XRZWebeeLrkr9IeO-T3Tb0zn4q8RzNEKsaysgKq8JAzDQBgHBtjaoAAO6sNMpA4NqJaEG23TtHypj-OC0rMKYsC0EKiqlIwPDID2HDMG+6Adug0yZvAyjsBhvCcsuWZ-qAOCUlSoCcKgna4aYzBqNYADk7DOKW-jEX2UIwgAVKAEFQegNb4hQloOg2drxOgLLsPQgiCcJkC4UOugAIy6FcoBCkZbgmdpjJBn6ob0OWuFCoAvBuAKU74jeReqiOWAgXiM56iCWZQkiXk04rLoABMX6gAAzA5TnGYJbmBr6LKwKSgFgAAEhqsCSaQbbMPBCG8OgYSjKFNq8OhmFgthYS4XC7SKQeoCIG0hbtDW7zRewcA-EI6kYDW4iqjJc7sEI01UA6LrjUKgB8G4AKLsIbB7BiQ1oCMHqoAdgoAD84jwW2qCqqAKypoQVChbwACEAhCG0RHig6pgOfEiSPqtoDrZthArF16AIi9K3vX+VxXI0zR9RC-bQl0w3WOAsPjYZuXTWZc2aajYhLUNK1mZDYzbWA+2HXBJ3wbw53EDVlW3WI92PbwCNg0jl6gN9v2TGKEpA+8oNnLTEwbfTyDwWg7AY-Dr3C6oKNozQQA)

Two problems: 
1. the return type from yield isn't quite inferred correctly.
2. its unclear what to pass to the generator the first time calling `.next()`.

I understand that there is an internal technical limitation for this to work, but I thought I'd add my use-case here to try to motivate why it would be useful!

**Comment by ccorcos** [comment]
I came up with a simpler way to do it that involves a type-cast helper function. Seems like macros would be useful here.

(no playground link because it hadn't upgraded to 3.6 yet)

<details><summary>Code</summary>
<p>

```ts
// Algebraic Effects API.
//
// The goal here is to define a sync API and an async API for a database without having
// to duplicate logic.
//
// It seems to come with the overhead of duplicative syntax.
//

// The two sync API datase API functions
function get(args: { id: string }): { id: string; value: any } {
	return {} as any
}

function set(args: { id: string; value: any }): {} {
	return {} as any
}

const api = { get, set }
const apiNames = Object.keys(api) as Array<APIName>

type API = typeof api
type APIName = keyof API

type APIRequest<N extends APIName = APIName> = Parameters<API[N]>[0]

type APIResponse<N extends APIName = APIName> = ReturnType<API[N]>

// Generator yields Messages that the handler will process
type APIMessage<N extends APIName = APIName> = {
	apiName: N
	request: APIRequest<N>
}

// API handlers that service requests.
function syncApiHandler<N extends APIName>(
	message: APIMessage<N>
): APIResponse<N> {
	return {} as any
}

async function asyncApiHandler<N extends APIName>(
	message: APIMessage<N>
): Promise<APIResponse<N>> {
	return {} as any
}

/**
 * Using Typescript 3.6 Generator type.
 * - yields `Message`
 * - returns `any`
 * - next argument is `APIResponse`
 *
 * Note: we cannot define a type in Typescript that lets us infer:
 *
 * 	const result: APIResponse<T> = yielded (message as Message<T>)
 *
 * Thus, we use `n` and `m` helpers below.
 *
 */
type LogicGenerator = Generator<APIMessage, any, APIResponse>

/**
 * Helper function to narrow the response type from `yield`.
 * Needs to be used with the same `keyof m`.
 */
declare const n: {
	get(response: APIResponse): APIResponse<"get">
	set(response: APIResponse): APIResponse<"set">
}

/**
 * Helper to construct messages passed to `yield`.
 * Needs to be used with the same `keyof n`.
 */
declare const m: {
	get(request: APIRequest<"get">): APIMessage<"get">
	set(request: APIRequest<"set">): APIMessage<"set">
}

// Reusable logic that works for both sync and async code.
function* logic(): Generator<APIMessage, any, APIResponse> {
	// Plumbing is required to effectively `await` a sync or async interface using `yield`.
	const setRequest: APIRequest<"set"> = { id: "hello", value: "world" }
	const message: APIMessage<"set"> = m.set(setRequest)
	// After yield does not infer APIResponse<"message">
	const response: APIResponse = yield message
	// This is a cast so it's important that `n.[apiName]` is the same as `m.[apiName]`.
	const setResponse: APIResponse<"set"> = n.set(response)

	// We can chain these together to make it easier to read.
	const a = n.set(yield m.set({ id: "hello", value: "world" }))
	const { id, value } = n.get(yield m.get({ id: "hello" }))

	// prettier-ignore
	// Using custom indentation helps group together all of the redundant `set` that is
	// prone to human error.
	const b = n.set(
			yield m.set({ id: "hello", value: "world" }))

	// Ideally we could define a type for Generator that `yield` would understand how to infer.
	// Then we could get away with the code below.
	const c = yield m.set({ id: "hello", value: "world" })
}

// Here's how we can evaluate both sync and async
function runSync() {
	const gen = logic()
	let request = gen.next()
	while (request.value !== undefined) {
		request = gen.next(syncApiHandler(request.value))
	}
}

async function runAsync() {
	const gen = logic()
	let request = gen.next()
	while (request.value !== undefined) {
		request = gen.next(await asyncApiHandler(request.value))
	}
}

```

</p>
</details>

**Comment by ccorcos** [comment]
I just ran into this limitation again. @RyanCavanaugh what are your thoughts on implementing typed algebraic effects. Is this something that is realistically not going to happen anytime soon? As an avid TypeScript user, this issue as well has higher-kinded types are the only real roadblocks I've run into. But it sounds like it might be a fundamental limitation of the way TypeScript was designed...

**Comment by AndrewMorsillo** [comment]
Another popular library that runs into this issue is [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree). Asynchronous state updates are modeled with generators. This issue combined with https://github.com/microsoft/TypeScript/issues/35105 causes a bunch of `any` to creep into your MST actions quite easily without anyone noticing.

**Comment by pqnet** [comment]
While having a strong typechecking on the executor part would be great, the biggest limitation for implementing coroutines at the moment is that `yield` expression can't be polymorphic, i.e. in the expression
```const x = yield y```
the type of `x` is univocally determined by the type of the generator, and cannot depend in any way from the type of `y`.

On the executor side I would be happy to have a method `next(value: never): unknown` which I need to explicitly cast to the expected type if I could express that inside the `function*` body the `yield` expression is typed according to a certain polymorphic function type such as `<T>(yielded: MyPromise<T>): T`.

While this would have messier code on the executor side, the "client" side for coroutine libraries would stay clean.
For now the best you can do is this:

```
function* unwrap<T>(yieldExpr: MyPromise<T>): Generator<MyPromise<T>, T, T> {
    const unwrapped = yield yieldExpr;
    return unwrapped;
}
function* mygen(): Generator<unknown, void, never>{
    const x = yield* unwrap(MyPromise.resolve(5));
    const y = yield* unwrap(MyPromise.resolve('hello'));
}
```

**Comment by pqnet** [comment]
Also note that the type of `next` is already broken on executor side, since it can always be invoked without parameters although for generators which have a `NextT` it is legal to do so only the first time it is invoked.

**Comment by arcanis** [comment]
I've open a proposal for a fix here: 💡 Yield Overrides https://github.com/microsoft/TypeScript/issues/43632

It goes the other way around (the yielded expression includes the returned type, rather than the generator driving it), but I think it's a reasonable approach that mirrors the preexisting `ThisType` API, and solves most of the relevant use cases. An implementation is available in a branch as well, see the thread for details.

**Comment by nightlyherb** [comment]
Here's something that's type-safe and compatible with current Typescript.
Is it possible to make a decorator that converts a normal generator into this more specific type?

```ts
// Increment / Decrement from:
// https://stackoverflow.com/questions/54243431/typescript-increment-number-type

// We intersect with `number` because indexing operations want `number` subtypes

type ArrayOfLength<N extends number, A extends any[] = []> =
    A["length"] extends N ? A : ArrayOfLength<N, [...A, any]>;
type Inc<N extends number> = number & [...ArrayOfLength<N>, any]["length"]
type Dec<N extends number> = number & (ArrayOfLength<N> extends [...infer A, any] ? A["length"] : -1);

type RangeType<Start extends number, End extends number> =
    number & (
        Start extends End
        ? never
        : Start | RangeType<Inc<Start> & number, End>);


// Generator definition

type Yield<YieldValue, NextValue> = (_: YieldValue) => NextValue
type AnyYield = Yield<never, unknown>
type YieldValue<Y extends AnyYield> = Y extends Yield<infer YV, unknown> ? YV : never;
type NextValue<Y extends AnyYield> = Y extends Yield<never, infer NV> ? NV : never;

interface SpecificGenerator<Ys extends AnyYield[], R>
    extends Generator<YieldValue<Ys[number]>, R, NextValue<Ys[number]>> {
    next<I extends 0>(): IteratorYieldResult<YieldValue<Ys[0]>>;
    next<I extends RangeType<1, Ys["length"]>>(value: NextValue<Ys[Dec<I>]>):
        IteratorYieldResult<YieldValue<Ys[I]>>;
    next<I extends number>(value: NextValue<Ys[Dec<I>]>): IteratorReturnResult<R>;
    [Symbol.iterator](): this;
}

// Example 1

type ExampleGenerator = SpecificGenerator<[(_: number) => string, (_: number) => number], string>
const g = function* () {
    const a = (yield 3) as string;
    const b = (yield a.length) as number;
    return a + b.toString();
} as () => ExampleGenerator;

const gRunner = function (egf: () => ExampleGenerator) {
    const eg = egf();
    const { value: n } = eg.next<0>();
    const { value: m } = eg.next<1>("a".repeat(n));
    const { value: result } = eg.next<2>(m);
    return result;
}

// Example 2

// From https://curiosity-driven.org/monads-in-javascript#do

// Monad

type Monad<T> = {
    bind<U>(f: (t: T) => Monad<U>): Monad<U>
}

type MonadInnerType<MT extends Monad<any>> = MT extends Monad<infer T> ? T : never;


// Maybe

interface Maybe<T> extends Monad<T> { };

class Just<T> implements Maybe<T> {
    value: T;

    constructor(value: T) {
        this.value = value;
    }

    bind<U>(f: (value: T) => Monad<U>): Monad<U> {
        return f(this.value);
    }

    toString() {
        return `Just(${this.value})`;
    }
}

const Nothing = {
    bind<U>(_: (value: never) => Monad<U>): Monad<U> {
        return this as Monad<U>;
    },

    toString() {
        return "Nothing";
    },
} as Maybe<never>;


type MonadUnwrappers<Vs extends any[]> = { [I in keyof Vs]: (_: Monad<Vs[I]>) => Vs[I] };

function* doNotation<Vs extends any[], T>(genFunc: () => SpecificGenerator<MonadUnwrappers<Vs>, Monad<T>>) {
    const gen = genFunc();
    function step<I extends number>(value: Vs[Dec<I>]): Monad<T> {
        const result = gen.next<I>(value);
        if (result.done) {
            return result.value;
        }
        type V = Vs[I];
        return result.value.bind<T>((v: V) => step<Inc<I>>(v));
    }
    return step<0>(undefined);
}

const sampleDoBody = function* () {
    var value = (yield new Just(5)) as number;
    var value2 = (yield new Just(6)) as number;
    return new Just(value + value2);
} as () => SpecificGenerator<[(_: Just<number>) => number, (_: Just<number>) => number], Monad<number>>;

const result = doNotation(sampleDoBody);

```

**Comment by SamB** [comment]
@rbuckton wrote (https://github.com/microsoft/TypeScript/issues/32523#issuecomment-526300477):
> However, what is actually happening is that you want the `Promise<T>` of one call to `next` to inform the `T` of a _subsequent_ call to `next`:

Dang, and for a moment there I thought what we were missing was a way to parameterize Generator with the relationship between those two types, but you're right, those aren't even related to the same call.

Is there a programming language that can handle that?

**Comment by rixtox** [comment]
When you define a generator function in JavaScript, the semantics of the `yield` operator is determined at call site. For example, if the caller is an async-runner like `co`, then `yield` would work like `await`. This makes the `yield` keyword to behave more like function arguments or the `this` keyword.

We already have a way to type `this` in a way like it's part of the function's parameters. Maybe we can make a similar mechanism to type `yield`.

```ts
type Awaiter = {
    <T>(value: T): Awaited<T>;
};
function* example(yield: Awaiter) {
    const value1 = yield Promise.resolve(1); // infer typeof value1 = number
    const value2 = yield Promise.resolve('hello'); // infer typeof value2 = string
}
await co(example);
```

You can still explicitly type the generator type or rely on type inference to determine its type. The `example` above has inferred type `Generator<Promise<number> | Promise<string>, void, unknown>`.
