### ISSUE TITLE
Incorrect generic type inference with OR types

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/TypeScript#32526]
**TypeScript Version:**  3.5.2. Also reproduces on `typescript@next` (3.6.0-dev.20190723)

**Search Terms:** inference, or types

**Code**

```ts
interface IFoo<A> {
	foo(arg: A): void;
}

declare class Foo implements IFoo<string> {
	foo(_: string | number): void;
}

declare class Bar<A> {
	constructor(foo: IFoo<A>);
	bar: A;
}

let bar: Bar<string> = new Bar(new Foo());
console.log(bar);
```

**Expected behavior:**

This should compile just fine.

**Actual behavior:**

```
file.ts(14,5): error TS2322: Type 'Bar<string | number>' is not assignable to type 'Bar<string>'.
  Type 'string | number' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```

**Playground Link:** 

https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIDED2mA8BBAPmQG8AoASBmwAo4oBzALmTwEpmA3TYAEwG5SAX1KkeEBABs6KSXADOc5FkzJgAWwAOEiGojhFGbDjlgooekTKUaAfWYmzIesgA+yEAFc1AI2jtkXLwCwqLiUlAyUgrIAEJ0+JYUCJggDh4IYJhQ1FSYzIa4hKwC5N50zHjBItpgyGVQzHFQxqbmRAC87hAA7rF01CA9SjSsxaTJqZjaAHQSmPTU9WNAA

**Notes:** 

In the example, `new Bar(new Foo())` should be inferred to be of type `Bar<string>` yet the compiler infers it as `Bar<string | number>` due to the shape of `Foo`, despite its promise to implement `IFoo<string>`.

This affects us (VS Code) in several places where we're forced to cast some types:

- https://github.com/microsoft/vscode/blob/105f843840f7dff139f7d54eb37e0c4ca663598e/src/vs/workbench/contrib/debug/browser/repl.ts#L395
- https://github.com/microsoft/vscode/blob/105f843840f7dff139f7d54eb37e0c4ca663598e/src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts#L462
- https://github.com/microsoft/vscode/blob/105f843840f7dff139f7d54eb37e0c4ca663598e/src/vs/workbench/contrib/outline/browser/outlinePanel.ts#L331

cc @mjbvz

**Comment by RyanCavanaugh** [comment]
TypeScript's type system is structural, so inference of the `A` type parameter is based on the *structure* of the `foo` argument, and the only candidate here is `string | number`. This is the expected result.

In fact, an `implements` clause is not really observable outside a class - the `implements IFoo` clause is *only* a check on the class declaration itself and has no other effects.

**Comment by joaomoreno** [comment]
Yep that makes sense. Now, try removing the declaration of `bar: A` from the `Bar<A>` class:

```ts
interface IFoo<A> {
	foo(arg: A): void;
}

declare class Foo implements IFoo<string> {
	foo(_: string | number): void;
}

declare class Bar<A> {
	constructor(foo: IFoo<A>);
}

let bar: Bar<string> = new Bar(new Foo());
console.log(bar);
```

The compiler is now happy. Why is that?

**Comment by joaomoreno** [comment]
Or another one: remove the `foo` declaration from the `IFoo<A>` interface.

```ts
interface IFoo<A> {
}

declare class Foo implements IFoo<string> {
	foo(_: string | number): void;
}

declare class Bar<A> {
	constructor(foo: IFoo<A>);
	bar: A;
}

let bar: Bar<string> = new Bar(new Foo());
console.log(bar);
```

The compiler is also now happy.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--

**Comment by joaomoreno** [comment]
> [Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--)

@RyanCavanaugh I'm not sure if this addresses both exercises proposed above, can you explain a little bit better?

**Comment by RyanCavanaugh** [comment]
`interface IFoo<A> { }` is what's in the FAQ.

`declare class Bar<A> { constructor(foo: IFoo<A>); }` does not use its type parameter in its instance shape either. Note that the shape of `Bar<A>` is what comes *out* of the constructor, so type parameter usage in the constructor function doesn't result in `A` being manifest in the instance shape.

**Comment by joaomoreno** [comment]
@RyanCavanaugh I'm still not convinced this is expected behaviour, even knowing about structural typing... but I won't push further.

There are two options for our code base:

- Either purposefully change the shape of our types and have distinct methods to handle distinct types;
- Or leave the casts in and document the reason why they must exist.

I've decided to go with the second one, and moved the casts closer to where they need to be for now: https://github.com/microsoft/vscode/commit/b798ef9751b4359724dcc06d7721570209f18c69

**Comment by RyanCavanaugh** [comment]
It might not be what *you* expect, but it's what we intend to happen 😉
