### ISSUE TITLE
Crash when redeclaring a property from interface.

### ISSUE THREAD

**Issue by GabrielCastro** [microsoft/TypeScript#32524]
**TypeScript Version:**  3.5.1

**Search Terms:**
`Debug Failure. Unhandled declaration kind! GetAccessor for`
`Debug Failure. Unhandled declaration kind! 159 for `
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

export interface IHasAName {
  readonly name: string;
}

export class HasAName implements IHasAName {

  public readonly get name(): string {
    return 'foo';
  }

  constructor(
    public readonly name: string,
  ) {
  }

}
```

**Expected behavior:**

Should result in a duplicate-identifier error

**Actual behavior:**

tsc exits witout writing file and prints error to console
```
Debug Failure. Unhandled declaration kind! GetAccessor for { name: name; flags: Property|GetAccessor; declarations: GetAccessor,Parameter }
```

**Playground Link:** 

https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQAlMBnAQQDlMBbPAbwCg44phMATCJAGwE84kNYAC44JGFGQBzANwMAvgwahIsONm6kScYuSq1E1MN2C0U2oqUpC4jJnDABXAEbcE2Fm049+U4PEFaAAoASlFxSSQpW3tmVhhHKCQ4AHJ0CAgUuWZFe2wuCMdsGGgg2IcXNw9WDi4+ASFwiWkAGnsQmJylRSA

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/31225
https://github.com/microsoft/TypeScript/issues/27352

**Comment by RyanCavanaugh** [comment]
Thanks for the simple repro!

**Comment by tbhartman** [comment]
I was not aware of the use of access keywords in the constructor arguments.  It appears the error only occurs if the getter is defined in the class *before* the regular parameter.

Fails:
```typescript
interface IHasAName {
    readonly name:string
}
class HasAName implements IHasAName {
    get name() {
        return 'foo';
    }
    name:string
}
```

OK (gives `Duplicate identifier` error):
```typescript
interface IHasAName {
    readonly name:string
}
class HasAName implements IHasAName {
    name:string
    get name() {
        return 'foo';
    }
}
```
