### ISSUE TITLE
{[key:number|string]:sth}

### ISSUE THREAD

**Issue by zaoqi** [microsoft/TypeScript#32534]
**TypeScript Version:**  3.5.3

**Search Terms:**

**Code**

```ts
type sth=number
type map={[key:number|string]:sth}
```

**Expected behavior:**

**Actual behavior:**

```
lang.ts:856:29 - error TS1023: An index signature parameter type must be 'string' or 'number'.

856 type EnviromentTree=[true,{[key:number|string]:Enviroment}]
```

**Playground Link:** 

**Related Issues:**

**Comment by jack-williams** [comment]
Covered by #26797.

**Comment by RyanCavanaugh** [comment]
In most cases `{ [key: string]: T }` already does whatever you were expecting `{ [key: string | number]: T }` to do
