### ISSUE TITLE
Autocomplete fails for generic parameter that extends a partial object type

### ISSUE THREAD

**Issue by aleclarson** [microsoft/TypeScript#32530]
**TypeScript Version:**  3.6.0-dev.20190723

**Search Terms:** partial extends autocomplete autosuggest generic

## Code

```ts
interface Foo<T extends object> {
    <U extends Partial<T>>(arg: U): Foo<U>
}

declare const foo: Foo<{ bar: number }>

// Try using autocomplete for the "bar" property
foo({  })
```

**Expected behavior:** The "bar" property should be suggested for completion

**Actual behavior:** No suggestions

**Playground Link:** [Click here](https://typescript-play.js.org/#code/JYOwLgpgTgZghgYwgAgGIHt0B4AqyIAekIAJgM7LoBGAVhAmAHzIDeAUMp8lgKr5ERSFAApwoYYHAA2uRowAUYgOYAuZDwCUajNh6M2AXzZsS9KWJQJ0IMmGQxM2zFhbIqYtSACuAWyrRkA30HdHlXQI0gA)

**Related Issues:** None

## Workaround

Replace...
```ts
<U extends Partial<T>>(arg: U): Foo<U>
```
...with...
```ts
<U extends Partial<T>>(arg: U & Partial<T>): Foo<U>
```

**Comment by RyanCavanaugh** [comment]
Duplicate #28470
