### ISSUE TITLE
event deprecated in typescript 3.5.3

### ISSUE THREAD

**Issue by shmaram** [microsoft/TypeScript#32533]
**TypeScript Version:**  3.5.3

**Search Terms:** In Typescript version 3.5.3 I found that event is now marked as deprecated. this can be found in file lib.dom.d.ts. I didn't found any reference in JS documents that this is indeed deprecated.

**Code**

from lib.dom.d.ts
```ts
/** @deprecated */
declare var event: Event | undefined;
```

**Expected behavior:**
I dont think we should have event deprecated 

**Actual behavior:**
event is marked as deprecated 

**Playground Link:**  

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
The docs for `event` are pretty clear about whether or not you should be using it https://developer.mozilla.org/en-US/docs/Web/API/Window/event
