### ISSUE TITLE
[...new Map()] and [...new Set()]

### ISSUE THREAD

**Issue by rabbitooops** [microsoft/TypeScript#32547]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
[...new Map()]
```

**Expected behavior:**
```ts
Array.from(new Map())
```

**Actual behavior:**
```ts
new Map().slice()
```

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment]
Duplicate of #8856?

**Comment by RyanCavanaugh** [comment]
Downlevel ES6 spread syntax into a call to an ES6 Array API... 🤔
