### ISSUE TITLE
Please get on Gitter

### ISSUE THREAD

**Issue by markrendle** [Microsoft/TypeScript#3254]
It would be great if the TypeScript repo could follow the example of the [CoreCLR](https://gitter.im/dotnet/coreclr) and [CoreFx](https://gitter.im/dotnet/corefx) guys and create a Gitter room for general chatter.

**Comment by DanielRosenwasser** [comment]
I've brought this up with the team previously. I was personally up for it, but there was a concern over moderation.

I think that in practice, moderation wouldn't be a real issue. In my experience, the IRC channel is reasonably well-conducted. Also, we could always turn Gitter off if we weren't pleased.

**Comment by danquirk** [comment]
Ask and ye shall receive https://gitter.im/Microsoft/TypeScript

**Comment by markrendle** [comment]
Awesome, thanks!



On Fri, May 22, 2015 at 19:36, Microsoft/TypeScript
<reply@reply.github.com>
wrote:
Ask and ye shall receive https://gitter.im/Microsoft/TypeScript [https://gitter.im/Microsoft/TypeScript]

—
Reply to this email directly or view it on GitHub
[https://github.com/Microsoft/TypeScript/issues/3254#issuecomment-104739421] .[https://github.com/notifications/beacon/AAK4QhwifFE07DUQgBSTQRzi_dD1_h7zks5oL26UgaJpZM4Ek8AM.gif]
