### ISSUE TITLE
VS2015 can't turn off "format line after ENTER"

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#3255]
In Visual Studio 2015, the feature *"format line after ENTER"* is always active even if it's un-flagged in the Options->Text Editor->TypeScript->Formatting->General. That is, lines are always formatted after I press `Enter`. 

I tried refreshing the options, flagging/unflagging, etc.. but nothing seem to work.

The same happens for *"format after paste"*, it's always active, regardless of the check. 

Using VS2015 Community Edition RC V14.0.22823.1 (a pretty fresh install, used only for TypeScript).

In VS2013 it works correctly.

**Comment by vladima** [comment]
AFAIR this is something that @paulvanbrenk has recently fixed on the VS side

**Comment by paulvanbrenk** [comment]
Correct, both format on enter and format on paste will be fixed in the finale release of vs 2015.
