### ISSUE TITLE
Polymorphic this type does not work with conditional mapped types

### ISSUE THREAD

**Issue by mcsrobert** [microsoft/TypeScript#32550]
**TypeScript Version:**  3.5.3

**Search Terms:** Polymorphic this mapped conditional

**Code**

```ts
type NumberedKeys<T> = { [K in keyof T]:
    T[K] extends number ? K : never }[keyof T];

type X = NumberedKeys<Example>;

class Example {
    public a: number;
    public b: string;
    public c: number;

    public constructor() {
        this.a = 3;
        this.b = "hello";
        this.c = 42;
    }

    public getNumber(key: NumberedKeys<this>): number {
        return this[key];
    }
}
```

**Expected behavior:** `NumberedKeys<Example>` works fine, but `NumberedKeys<this>` does not.

**Actual behavior:** 
```
Type 'this[{ [K in keyof this]: this[K] extends number ? K : never; }[keyof this]]' is not assignable to type 'number'.
  Type 'this[this[keyof this] extends number ? keyof this : never]' is not assignable to type 'number'.
    Type 'this[keyof this]' is not assignable to type 'number'.
      Type 'this[string] | this[number] | this[symbol]' is not assignable to type 'number'.
        Type 'this[string]' is not assignable to type 'number'.
```

**Playground Link:** [link](https://www.typescriptlang.org/play/#code/C4TwDgpgBAcgrgWwEYQE4QCYGkIgM4A8AKgHxQC8UA3lANpZQCWAdlANa4D2AZlEQLoAuAFBQxfevygQAHsAjMMeKM0QpUUAPxQGglRABuaKAF9aHEDz78A3MOGhIUABoVYatJhz4CAURkAhghgADYQJHbCAMYhAXjK-kGh0FSi4mBwSCGMUVABeqrIaHbiUBlZOVBIenjAqCwA5iXpmdm5UQUeqJGl5W1QUZzMtahwUcCcqAAUAJTUaaViwAAWjHgAdAFuAMzNi1Ara+tIbgBEyxAhIZyne4uHG7mUACwATHcm9r2tlQ0QwPAitMLHpAeovLhCA8SDNOkD5vsxOhgHBUKwHuZcLYFqZhJ8gA)

**Related Issues:** n/a

**Comment by jack-williams** [comment]
I'm not sure if this approach is possible because a key type may not constrain the type of values it maps to, it can only say that is a key of some type. (If someone does have a solution I'd be interested to see it!)

Would this work for your use-case?
```ts
    public getNumber<K extends keyof this>(this: Record<K, number>, key: K): number {
        return this[key];
    }
```

**Comment by mcsrobert** [comment]
@jack-williams I cannot seem to get that to work. When constructing the class I get:
```
The 'this' context of type 'Example' is not assignable to method's 'this' of type 'Record<"getNumber", number>'.
  Types of property 'getNumber' are incompatible.
    Type '<K extends "a" | "b" | "c" | "getNumber">(this: Record<K, number>, key: K) => number' is not assignable to type 'number'.
```

**Comment by jack-williams** [comment]
Can you post an extended example?

Here is my version: [playground](https://www.typescriptlang.org/play/#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNf0KArgEYgCWw0YAXNAHZFInoBOA3HgcWZdCXQgAXVuXoBzTgUKkKVYHUbM2nLvh5zowAPb1hrIsCHbWACgCU2NdOhCAFuQgA6MNAC80AMxSb+e46cSd2gAIjt0EBBtEJ9ff2cqDwAWACZY6ABfHGsNPnF0IQA5JhZWAB4AaWh0eCF0egATGABrdABPbQAzWwcIAD5TeLoAJXQdVgbKgBoGErY+mda2ugrzRTnWK198VgKiVnoexwBtJYBddKys7J09IWpg+nQAdzhEVAwLVTAnfKKN0whEghczsaAAenB1VYrBMM2eDmAdmgjmgCLA92emGeYHoQicOB+f2KyjMITAILBkOg2manCAA)

**Comment by mcsrobert** [comment]
@jack-williams I got your example working eventually. The problem is that I need access to other properties of `this`. This is not possible with `Record`.

The problem I'm trying to solve is a generalised, inheritable version of [DataLoader priming](https://github.com/graphql/dataloader#loading-by-alternative-keys).

I can probably just use strings here, but I was trying to see if there was a way to have stricter typing for this, when I ran into the issue above. I've posted the extended example [here](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgIIAdgCUIIPZQAmyA3gFDKXLCEBcyAzmFKAOYDcZAvmWaJLEQoAcnAC2EQhmy4CxCAA9IIQgzSYc+IqQpUQ4iPSYsQHbrzABPdCgAicMHAAyeOIWgAeLAD5kAXmQACgBrCEsGI2Y2AG0AXQBKf18sOM4yKxtke0cXN2gAaTCGDwAVXwCSZGj86hBkUMs8GGQS2NpdShLq2ORFZVUsh2dXdygPOBBLXwB+ZBr6EAgAN2hkLmiGppbYtIQAGzgGNVzRr16lCBU1aU05X3IqZHQAVwAjPeAEZFfLAEk6QY5EaeHxpR4vd6fZD4EDGZ4IMAEQKJB6PKhgAAWwAYADofv9-EEaAx4vQUj0-L5MdicawIGBAgADGi-YQAEhIxK4jIANMgAET4wj8+KcR48DpPN4fL50hkAR2e0EskRMrD5DDwzygSGm9GywzyUEK4Q81IY3lJyHJOjRVAA9PbkABlPASZBQCBiPCQaFwPZ7SWPGFMZDPBjQNQBaJBu2kagA-kAVn5fP0Eno-NQMog-LWPNjdsqNEzADZU8h04YBQAhPCvPNcAtx5A9Q7ICaWMVx8049AsCQAeUxkcC4cjGq1OogosLHvp2rq46gDG7lB4yEl-Z9uEgxH7wCHI5XgU9WlUZLik+1uv1QxOBSKZqxFslVqWeBotrjwGagU1N4oAAhH4ASCn8woonOwZ4LCYDIHswJQISvZCmuLbII6CFIX2A4QKeshECS6HipKPASvshxqKIEiEA+YxYOc-TUQYUgaIRhC+H0lwDPRXj3Lw4LSlCPw0dWBp8aCglUBCMrQrBcIIkiUEtgwzw2FAyIkeiL54pYYmEoEVYkpeFJUrpcpMlWrIcsZ3J8uBYkiuhErglAO4IpITx4cOGKjmecgRNaV6MFOt6AoaowmsU5qWvQH5fqidpqRpuGHhAvn+RxDDXtOs4tr+QQAdOyAgWBokGCK34YfJcHYUaKG6RVEjaXaWGIUaaUSAR57EXOG5UORvBAA).

**Comment by RyanCavanaugh** [comment]
We can tell from inspection that `NumberedKeys` returns keys where the looked up property is of type `number`, but TypeScript can't do the kind of higher-order reasoning to realize that this means the resulting type, when indexed *back* in to the same type, has that effect in the general case.

**Comment by EduardoRFS** [comment]
I also hit that today when was trying to make an amazing type definition, minimum example:

```typescript
type PickProperties<T, P> = Pick<T, {
  [K in keyof T]: T[K] extends P ? K : never;
}[keyof T]>;
type Numbers<T> = PickProperties<T, number>;
type Identity<T extends number> = T;

const use = <T, K extends keyof Numbers<T>>(
  service: K,
  fn: Identity<Numbers<T>[K]>
): void => {}
```

@RyanCavanaugh  it's that hard to implement a constrain based on keyof? Because the constrain that `Numbers<T>` will always returns `{ [key: string]: number }` so + `keyof` will result in `T[K]` being always a `number`.
