### ISSUE TITLE
TS6133: errors on variables that are used as return type

### ISSUE THREAD

**Issue by chrisblossom** [microsoft/TypeScript#32556]
**TypeScript Version:**  `3.5.3`

**Search Terms:** `TS6133`

**Code**
```ts
// TS options noUnusedLocals: true, noUnusedParameters: true

type One = 1;
type Two = 2;

type Combined = One | Two;

function handleOne(table: One): One {
    return table;
}

function handleTwo(table: Two): Two {
    return table;
}

// Adding a leading _ to table removes error
function tableIsOne(data: number, table: Combined): table is One {
    return data === 1;
}

function example(data: number, table: Combined) {
    const result = tableIsOne(data, table)
        ? handleOne(table)
        : handleTwo(table);

    return result;
}
```

Actual use case example: [chrisblossom/jest/jest-each/src/bind.ts#L53-L56](https://github.com/chrisblossom/jest/blob/9084bc40325179edb8415c7a3ddbe18790f2511f/packages/jest-each/src/bind.ts#L53-L56)

**Expected behavior:**
I am not sure if this is a bug or expected but I thought I'd open an issue just in case.

No errors without adding leading `_`.

**Actual behavior:**
`TS6133: 'table' is declared but its value is never read.`

**Playground Link:** https://www.typescriptlang.org/play/index.html?strictPropertyInitialization=false&noUnusedLocals=true&noUnusedParameters=true#code/C4TwDgpgBA8gdtAvFAjAbgFCklAKgdwHspkAmTLcaAYUIFsAjASwQBMTYEoAfPIigGYBXOAGNgTQnCgALAIZxWAGwjwIACmByGKgFycIASn1qoAbwxQoAJwjAh16Vp0RMAXwzCxEqbIXKIAkJNbT0+QmNw80sbOwcnUNcMD08RcUkElwBJAGc1dVY5LX04IUYIawAaKGcw2kYWCFZI2ugmHINoq1t7RyhCrRJEZHRkjFTvDKgIAA85OjAVAqK5ErKGCurW-XrmNkMuqFEpHOBYnKElM+RW3PyBuS3Eg4B+P0UVfNaD-XkPwKIIRchgo3TifVsFyu7gwQA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/28620

**Comment by RyanCavanaugh** [comment]
This warning only concerns the usage of something in a value position, not a type position.

**Comment by chrisblossom** [comment]
Thanks for responding. I thought that might be the case...no objections from me!
