### ISSUE TITLE
Using TypeScript Compiler API to test generated type definitions

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/TypeScript#32567]
I am working on a tool to convert from GraphQL types to TypeScript declarations (this is specifically for serverside resolver definitions). I would like to write tests for this in a form like:

```ts
const sf = ts.transpileModule(
   generateTypes(...) + 'let a : GeneratedTypeFoo = { ... }', 
   {compilerOptions: { ... }}
);

// test something about sf.diagnostics to verify if the typing was valid or not
expect(sf.diagnostics).toBe(....)
``` 

However, `TranspileOutput#diagnostics` does not contain semantic errors, as per #4864. The proposed solution in that thread was to instead use `createProgram`, but it seems that does not accept string source inputs, instead it must read from the file system. 

Is there any way to use the Compiler API to get type errors from a single, independent, block of code, without needing to access the file system?

**Comment by JacksonKearl** [comment]
Now, trying to use a temporary file, it seems that `getGlobalDiagnostics` is not behaving as expected. What should I be using to get a list of type errors in a `Program`?

```ts
const test = async () => {
  await withFile(async file => {
    await write(file.path, "let a: never = 0");
    const program = ts.createProgram([file.path], {
      strict: true,
      target: ScriptTarget.ES2018
    });

    const diagnostics = await program.getGlobalDiagnostics();
    console.log(diagnostics); // []
  });
};
```

**Comment by dsherret** [comment]
@JacksonKearl yes, you'll need to use the program. You can get all the diagnostics from it with the helper function `ts.getPreEmitDiagnostics(program)` (see it's implementation [here](https://github.com/microsoft/TypeScript/blob/fb50920a67dfbe75a2f2fac363f8bd89a25cbb08/src/compiler/program.ts#L320)).

When using `ts.createProgram` you can provide a third argument that specifies a `ts.CompilerHost`. Using this, you will be able to keep everything in memory (but it's a lot of work 😄). Also, you will still have to load files from the file system such as the standard lib.d.ts-like files where all the lib declarations are stored from `node_modules/typescript/lib`.

**Comment by JacksonKearl** [comment]
@dsherret thanks for the response! Did `ts.getPreEmitDiagnostics(program)` and it gave me a massive list of errors, eventually figured out that it was including all my `node_modules/@types` for whatever reason, got things working in the end with:

```ts
const program = ts.createProgram([path], {
  strict: true,
  typeRoots: [],
  types: []
});
const diagnostics = await ts.getPreEmitDiagnostics(program);
```

Thanks!
