### ISSUE TITLE
newable/callable signatures dropped when wrapped with Readonly

### ISSUE THREAD

**Issue by rkirov** [microsoft/TypeScript#32566]
**TypeScript Version:**  3.5.2

**Search Terms:**
readonly and newable signature, readonly and callable signature.

**Code**

```ts
class C {}

let good: {new (): C} = C;
let bad: {new (): C} = {};  // type-checking error

let goodReadonly: Readonly<{new (): C}> = C;
let badReadonly: Readonly<{new (): C}> = {};
```

**Expected behavior:**
badReadonly should error the same way as 'bad',

**Actual behavior:**
Only `bad` line has a type-checking error.
**Playground Link:** 
http://www.typescriptlang.org/play/#code/LAKAxgNghgzjAEBheBvAvqUECmAXeA5gPZEAmAXKgHbYDu8AFAJSWJrwC8SA3FnvACMoFanUYsk7Lul4g++YmQBK2YUSoQAnpRVqNmgDwoa9ZqzQA+Tj3mDhu0uq07Vj-UZPjzV6WlmggA

Same behavior can be observed with a 'callable signature' too.

Note, this was found is some already quite suspicious code, so I don't think there is high priority here (Readonly is seldomly used).

**Comment by AnyhowStep** [comment]
Mapped types drop call signatures because there's no "key" associated with them
