### ISSUE TITLE
Intersection  types decorators have some problems

### ISSUE THREAD

**Issue by liangshen001** [microsoft/TypeScript#32570]
**There are two problems with Intersection types.**

_The typescript version I use is 3.5.3_

**Problem number one**

![image](https://user-images.githubusercontent.com/22604816/61921671-80a59f00-af90-11e9-9a69-0c53832d1e97.png)

But I solved this problem by using 'any',Why is that?

![image](https://user-images.githubusercontent.com/22604816/61921789-e5f99000-af90-11e9-8651-c1111c2c217c.png)

Here are the statements for both methods.

```
(function) public static DecoratorUtil.makePropertyDecorator<OP,V>(handler: (option: OP, target: Object, propertyKey: (string | symbol)) => V, metadataKey?: symbol | string): (option: OP) => PropertyDecorator

(function) public static DecoratorUtil.makeMethodDecorator<OM,V>(handler: <T>(option: O, target: Object, propertyKey: (string | symbol), descriptor: TypedPropertyDescriptor<T>) => V, metadataKey?: symbol | string): (option: OM) => MethodDecorator
```

**Problem number two**

![image](https://user-images.githubusercontent.com/22604816/61921871-35d85700-af91-11e9-8a8a-7dc69d623c2f.png)

![image](https://user-images.githubusercontent.com/22604816/61921901-4983bd80-af91-11e9-8298-af59b35c07d8.png)

![image](https://user-images.githubusercontent.com/22604816/61922029-b303cc00-af91-11e9-81af-915151182813.png)

Decorator A works on both properties and methods

Decorator B works on methods, but not on classes

How do I fix it, Thank you in advance!!!

**Comment by liangshen001** [comment]
![image](https://user-images.githubusercontent.com/22604816/61923380-4d660e80-af96-11e9-9e98-3da6764e2b47.png)
Strange, I changed the parameter type of the method, so the decorator doesn't report any errors

**Comment by RyanCavanaugh** [comment]
We can't work with screenshots of code. Please follow the template and post code as text.
