### ISSUE TITLE
custom transformer with module commonjs will cause a weird error

### ISSUE THREAD

**Issue by stkevintan** [microsoft/TypeScript#32575]
I was using a plugin called `ts-import-plugin` to help me to make some big dependencies import on demand 
it will create a custom transformer and simply tramsform the import statement `import { Icon } from 'antd'` to `import Icon from 'antd/lib/icon'`

this plugin works fine when `module: esnext`, but when I set module to 'commonjs', weird things happens:
**Code**
source code :
```ts
import {Icon} from 'antd'
<Icon />
```
after plugin transform:
```ts
import Icon from 'antd/lib/icon'
<Icon />
```
tsc will compiler the transformed code to:
```js
const Icon_1 = require('antd/lib/icon')
React.createElement(antd_1.Icon) // why?
```

if I directly use tsc to compile following code (same as the transformed code), the output will be correct: 
```ts
import Icon from 'antd/lib/icon'
<Icon />
```
tsc compile :
```js
const Icon_1 = require('antd/lib/icon')
React.createElement(Icon_1)
```

what should I do to solve this problem?

**TypeScript Version:**  3.5.2

**Search Terms:**

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:** 
https://github.com/Brooooooklyn/ts-import-plugin/issues/46

**Comment by RyanCavanaugh** [comment]
Sounds like you set `module` to `commonjs`; the plugin says you should set it to `ESNext`

**Comment by stkevintan** [comment]
@RyanCavanaugh thanks for your reply,  emmm... I know the plugin says I should use esnext, but unfortunately I need to make my package to support commonjs module. 

can I set this transformer before the module binding phase ?
