### ISSUE TITLE
CFA does not recognize boolean from NOT expression

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#32576]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
CFA boolean not expression

**Code**

```ts
type Test = { succ: true, res: any } | { succ: false, error: any };
let value: Test;
if (!value.succ) {
    console.log(value.error);
}
```

**Expected behavior:**
Compile succ

**Actual behavior:**
Property 'error' does not exist on type 'Test'.

And this works well:
```ts
type Test = { succ: true, res: any } | { succ: false, error: any };
let value: Test;
if (value.succ !== true) {
    console.log(value.error);
}
```

**Playground Link:** 

**Related Issues:**

**Comment by ajafff** [comment]
IIRC you just need to enable `strictNullChecks`

**Comment by fatcerberus** [comment]
Is that because, without `strictNullChecks`, `.succ` could be `undefined` for both cases and therefore a falsy check is not enough to distinguish them?

**Comment by jack-williams** [comment]
The issues stems from the lack of initialiser for `value`. Writing:
```ts
declare let value: Test;
```
fixes the problem, or just initialising it to something.
