### ISSUE TITLE
Inheriting class not calling super() when targeting ES6

### ISSUE THREAD

**Issue by Ixonal** [Microsoft/TypeScript#3257]
When I create a subclass and export it to ES6, then try to run it through Babel, it complains that super() has to be called before this is referenced. There is indeed no call to super in the outputted ES6 code. A quick google search turned up this document (http://www.2ality.com/2015/02/es6-classes-final.html) which states "In a derived class, you must call super() before you can use this" and "Implicitly leaving a derived constructor without calling super() also causes an error" so it looks like if the super constructor call isn't added to the constructor in the typescript version, it should be automatically inserted at the top of the constructor in the ES6 code.

**Comment by DanielRosenwasser** [comment]
Can you give us a specific code sample?

**Comment by Ixonal** [comment]
viewModelBase.ts:

    export default class ViewModelBase {
      $parent: any
    
      bind($parent) {
        this.$parent = $parent;
      }
    }


default.ts:

    import { autoInject } from "aurelia-framework";
    import { HttpClient } from "aurelia-http-client";
    import ViewModelBase from "viewModelBase";
    
    @autoInject()
    export class DefaultApp extends ViewModelBase {
      constructor(http : HttpClient) {
        this.http = http;
      }
      
      http : HttpClient
    
      message = "Hello World!"
    
      sayGoodbye() {
        this.message = "Goodbye!";
      }
    }

default.es6.js:

    if (typeof __decorate !== "function") __decorate = function (decorators, target, key, desc) {
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
        switch (arguments.length) {
            case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
            case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
            case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
        }
    };
    if (typeof __metadata !== "function") __metadata = function (k, v) {
        if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
    };
    import { autoInject } from "aurelia-framework";
    import ViewModelBase from "viewModelBase";
    export let DefaultApp = class extends ViewModelBase {
        constructor(http) {
            this.message = "Hello World!";
            this.http = http;
        }
        configureRouter(config, router) {
            config.title = "test";
            config.map([]);
            this.router = router;
        }
        sayGoodbye() {
            this.message = "Goodbye!";
        }
    };
    Object.defineProperty(DefaultApp, "name", { value: "DefaultApp", configurable: true });
    DefaultApp = __decorate([
        autoInject(), 
        __metadata('design:paramtypes', [(typeof HttpClient !== 'undefined' && HttpClient) || Object])
    ], DefaultApp);
    
    //# sourceMappingURL=default.es6.js.map

And here's what I'm using to compile it, from my gulpfile:

             .pipe(typescript({
               target: "ES6",
               declarationFiles: false,
               emitDecoratorMetadata: true,
               typescript: require("typescript")
             }))

**Comment by DanielRosenwasser** [comment]
Do you not get the error message "Constructors for derived classes must contain a 'super' call."?

[With a reduced repro in the playground, that's what I'm getting.](http://www.typescriptlang.org/Playground#src=interface%20HttpClient%20%7B%0A%09%0A%7D%0A%0Aclass%20ViewModelBase%20%7B%0A%20%20%24parent%3A%20any%0A%0A%20%20bind(%24parent)%20%7B%0A%20%20%20%20this.%24parent%20%3D%20%24parent%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20DefaultApp%20extends%20ViewModelBase%20%7B%0A%20%20constructor(http%20%3A%20HttpClient)%20%7B%0A%20%20%20%20this.http%20%3D%20http%3B%0A%20%20%7D%0A%0A%20%20http%20%3A%20HttpClient%0A%0A%20%20message%20%3D%20%22Hello%20World!%22%0A%0A%20%20sayGoodbye()%20%7B%0A%20%20%20%20this.message%20%3D%20%22Goodbye!%22%3B%0A%20%20%7D%0A%7D)

![image](https://cloud.githubusercontent.com/assets/972891/7779068/1f03e85a-0086-11e5-8af5-0a86dedd756b.png)

**Comment by Ixonal** [comment]
It didn't before, but I just closed all my visual studio instances and reopened the project and it is now. I just installed the TypeScript 1.5 beta stuff earlier, and it didn't tell me to restart the IDE, so it may have gotten temporarily borked.
