### ISSUE TITLE
Embed unit testing in production code

### ISSUE THREAD

**Issue by kasajian** [Microsoft/TypeScript#3258]
Okay, before you completely discount this idea, I just want to say that I think could be really useful.   For instance, Python has doc-tests, which are light-weight and much-constrained unit-tests.   I've also used compiler preprocessing to simulate this, where I have individual "functions" defined in a single file, and have the unit test for that function right below it.   The preprocess ensures that unit test code doesn't get into production assemblies.

I find that having the test code right where the production code is makes it a lot easier to write code.  One can argue that the test code is just as much part of the intellectual-property of the software as the code that it's testing.  Having them be side-by-side shows this explicitly.

Furthermore, production code is not absent of tests anyway, when you consider assertions and code-contracts.

Doc-tests are smarter assertions
Code-contracts are smarter doc-tests
and unit tests are smarter code-contracts.

We have, by convention, established that some of this belongs where the production code resides, and some of it does not.   I think that distinction is more historic and arbitrary than something that is a sacred cow that cannot be reevaluated. 

Thoughts?

**Comment by danquirk** [comment]
Something like https://github.com/Microsoft/TypeScript/issues/3138?

**Comment by kasajian** [comment]
#drool..  Yes!
