### ISSUE TITLE
Wrong `keyof` behaviour on objects

### ISSUE THREAD

**Issue by ClementNerma** [microsoft/TypeScript#32587]
**TypeScript Version:**  3.5.2 (WebStorm's bundled version)

**Code**

```ts
type A = keyof { [key: string]: any };
```

**Expected behavior:**

`A` should be equal to the `string` type.

**Actual behavior:**

`A` is equal to the `string | number` union type, although the object's keys can only be keys.

**Comment by jcalz** [comment]
This is [working as intended](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-number-and-symbol-named-properties-with-keyof-and-mapped-types).

**Comment by fatcerberus** [comment]
...and the reason for the above is that in JavaScript:
```ts
a[1] = 42;
a["1"] = 42;
```
...are 100% equivalent.

**Comment by ClementNerma** [comment]
Oh I see. So that's why it now works this way, I thought this was a bug. Thanks for the explanation :)
