### ISSUE TITLE
Add ability to overload methods in objects

### ISSUE THREAD

**Issue by pleerock** [microsoft/TypeScript#32588]
I think TypeScript must allow to define us method overloads in the objects too:

```ts
export const ProductManager = {
  async find(id: string): Promise<Product>
  async find(ids: string[]): Promise<Product[]>
  async find(idOrIds: string | string[]): Promise<Product | Product[]> {
  }
}
```

Such method overloads helps to define really complex cases when it's not possible to properly define everything in a single method signature.

**Comment by pleerock** [comment]
Is there already discussion around this feature and reason why it's declined? I don't suggest to introduce new language constructs, what I suggest is only related to type system.

**Comment by RyanCavanaugh** [comment]
Sorry, meant to leave a comment here (thought I had actually). There just isn't syntactic room in object literal syntax to allow for this in a way that would be guaranteed to not conflict with either current meanings or future ES features. This is already reasonable achievable today by annotating `ProductManager` with a type annotation.

**Comment by pleerock** [comment]
That's sad. Imagine some big class [like this one](https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts), if I'll write a type annotation in there, it just feels... feels like I'm writing a `.d.ts` code instead of writing a natural code...

We all know it's a tricky question when it comes to bring something new and predict that this feature won't appear in future ES versions, but we do need to bring new features... and since suggested syntax looks same as in `class` version of what we already have, and we already have an assumption that in class version it won't appear (since we already have implementation in place), plus assumption that same signatures of the same object property (`find` in this case) unlikely appear in future ES versions makes me think that it's safe to add this feature to the language.

It's what I think, of course you know better where I'm wrong and what to do.

**Comment by thw0rted** [comment]
This seems like a pretty reasonable workaround:

````ts
interface FooFunc {
    (n:number): number;
    (s:string): string;
    (sn: string | number): string | number;
}
interface Owner {
    foo: FooFunc;
}
const o: Owner = {
    foo: (sn: any) => {
        return sn;
    }
};

// Result is strongly typed
o.foo(1).toFixed(3);
o.foo("two").charAt(2);
````

The last overload in `MyFunc` is optional because you're not actually typing the method itself when you assign the object to the interface-typed `const`, if I understand correctly.

**Comment by pleerock** [comment]
You can always write a separate type definition, it just doesn't feel like its the most convenient and natural way to solve your problem.

**Comment by J3m5** [comment]
I feel the same need, especially for big objects.
In the case of objects with dozens of functions like front-end stores for example and
if we need to overload just one function, we must implement the whole interface just for that on function.
it seems unnecessarily cumbersome and repetitive.

Is there any solution for this case ? 
Like partially implement the interface without loosing the types of the others functions ?
