### ISSUE TITLE
Inconsistent "property does not exist" on F-bounded mapped type with intersection

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript#32581]
**TypeScript Version:**  3.6.0-dev.20190726 (reproducible all the way back to 2.4 afaict)

**Search Terms:** f-bounded polymorphic, intersection, mapped type, property

**Code**
```ts
type X<T> = { [K in keyof T]: string } & { b: string };
interface Y extends X<Y> {
  a: "";
}
declare const y: Y;
y.a; // "", okay
y.b; // hinted as string, but error!
//~ <--  Property 'b' does not exist on type 'Y'. 🤔

type KY = keyof Y; // "a" | "b"
type YA = Y["a"] // okay
type YB = Y["b"] // error!
//          ~~~ <-- Property 'b' does not exist on type 'Y'.
type B = Exclude<keyof Y, "a"> ; // "b"
type YB2 = Y[B]; // okay, string! 😵
```

**Expected behavior:**

I expect either no errors (`y.b` is type `string`), or I expect the particular F-bounded mapped type `Y extends X<Y>` to be disallowed.  

**Actual behavior:**

Split-personality weirdness where property `"b"` both *does* and yet *does not* exist on type `Y`.

**Playground Link:** 
[Link](http://www.typescriptlang.org/play/#code/C4TwDgpgBAGgPAFQHxQLxQN5QNoGkoCWAdlANYQgD2AZlAgLoBcUAzsAE7EDmUAvlADJMUAEbM2nIj14BuAFDFgEdtQCGAY2gBNKBAAeSogBMWsOFpQY5UKKuYAie-N5yjEdQBtV7aOspE2KBBmLXkQADpVGSgAehioRwAaKEpSVRA5CJFouKgAC0UII1tTCW5kkQBXYF12dkp2AEI5OIA-KDgAWk6bAAV6yHZQKAByERGoI0oIUyJKGv0CQP8oUEhRrRHwqEA+DcAUXbk5NehcHXRyKlpQ2Pj7VXsoAB8EkXsj8G0AQTQoLWw7+z0G4pNIZY6-ABCPz+9leQNyynqTRa8RsaPRrUxHW6UH6lEGwzGEymMygcwWeiWNRW4JGm3C73WUPQAFE9J5Km44BcaL9kgCUDlbq9GdoIQAmaHYCH0IUg9LJMpSRpQQC8G4BWPcOQAA)

**Related Issues:** Not really obvious to me, #18280 hits some of the same concepts but is not the same issue

---

I know that this is a weird construction, and I'm okay not using it (although something like it is useful in representing otherwise unrepresentable type constraints), but the resultant behavior is just so bizarre that I had to report it.  Especially how `Y["b"]` is an error, but `Y[B]` is not an error.

**Comment by fatcerberus** [comment]
> Split-personality weirdness where property "b" both does and yet does not exist on type Y.

That’s just the new undocumented “Schrödinger's properties”.  It’s not a bug, it’s a feature!

**Comment by jcalz** [comment]
Wait, maybe this is a duplicate of #23537?  Or close enough?

**Comment by ahejlsberg** [comment]
Would be nice to report a circularity error here. There are a few places where we defensively set lazy resolution caches to empty before invoking the resolution logic such that circular references don't trigger infinite recursion. Ideally we'd use our `pushTypeResolution` logic in those cases, but I'm concerned that might uncover circularity errors that really are harmless. Anyway, I don't think this is a pressing issue.
