### ISSUE TITLE
Infinite loop in documentation for JSDoc support in JavaScript

### ISSUE THREAD

**Issue by iansan5653** [microsoft/TypeScript#32589]
On this page: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html, the link "JSDoc support in JavaScript documentation" links to this page: https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript, which just redirects back to the original page. 

Of course the infinite loop needs to be fixed, but also is there any documentation anywhere for the list of tags that are supported?

**Comment by j-oliveras** [comment]
I think they are preparing a new unified documentation web. Probably they changed the wiki page to redirect to the page that will have that documentation when the new web is updated.

CC @orta I think you are working on it.

**Comment by orta** [comment]
That links should be deleted, all the docs for the tags are inside the original page you left - https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc
