### ISSUE TITLE
Existing check is lost after type union discrimination

### ISSUE THREAD

**Issue by princed** [microsoft/TypeScript#32598]
**TypeScript Version:** 2.4.1, 3.5.1, 3.6.0-dev.20190727

**Search Terms:**
type union discrimination, narrowing, widening

**Code**

```ts
interface Base { common?: string }

interface Sub1 extends Base { type: 'sub1' }

interface Sub2 extends Base { type: 'sub2' }

type Union = Sub1 | Sub2;

function test(u: Union) {
    if (u.common) {
        if (u.type === "sub1") {
			u.common.toString(); // <-- Object is possibly 'undefined'.
        }
    }
}
```

**Expected behavior:**
No error message, since `u.common` is already proved to exist.

**Actual behavior:**
Error message

**Playground Link:** 
[Playground link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgEJwM4oN7IQewFtD8QB+ALmQzClAHNkBfAKBdElkRQGUBXAEYBGZBAAekEABMMaTDmRgAngAcIVAOQZBQjczYdo8JMn4CATKIkRps9FmS5lazdot7WLZygCqIYKTIALymOsgAPqEWANxsMHwgCGABIIoQNAAUfFR+KQCUjizIxcjAMMhZAHQExKQF2EUlTWUVfJXewUEhAERuQt31LACQI201JCDt+Dy0DBl50cgA9EvIADwAtBvIAPICAFYQSaWyKvgYGMACADZKyBoJUhAwoBBSGpWNTcWsTaxMQA)

**Related Issues:** 
The closest report I could find was https://github.com/microsoft/TypeScript/issues/11787#issuecomment-498449508, but apparently, it's related to type guards, which impose some design limitation as far as I understand.

**Comment by fatcerberus** [comment]
Duplicate of #31495 (among others).

**Comment by princed** [comment]
Oh, I see, thanks.
