### ISSUE TITLE
Array<number>.sort() uses lexicographic comparator by default

### ISSUE THREAD

**Issue by greddyatpt** [microsoft/TypeScript#32593]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
typed arrays
default comparator
lexicographic comparator
numeric comparator

**Code**

```ts
let a: Array<number> = [12,4];
a.sort();
console.log(a);
```

**Expected behavior:**
[4, 12]
**Actual behavior:**
[12, 4]
**Playground Link:** 
https://codepen.io/greddyatpt/pen/aepoaN?editors=1111

**Related Issues:** 
#18286 is related but it recommends a breaking change.  Instead, the default comparator should take the element type into consideration.

**Comment by MartinJohns** [comment]
This is unrelated to TypeScript, it's up to the runtime.

Also this is the correct behavior: [MDN documentation of Array.prototype.sort()
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

> The default sort order is built upon converting the elements into strings, then comparing their sequences of UTF-16 code units values.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't change the behavior of JavaScript code.

**Comment by greddyatpt** [comment]
In that case, an emit-time warning would be very helpful.

**Comment by Rudxain** [comment]
What about enforcing [`require-array-sort-compare`](https://typescript-eslint.io/rules/require-array-sort-compare) unconditionally? This would only require making the declaration signature stricter. Yes, this is a breaking change, but a compiler option for a single `Array` method seems like "nuking a mosquito"
