### ISSUE TITLE
Feature Request: certain extend for indexable interface

### ISSUE THREAD

**Issue by fnknzzz** [microsoft/TypeScript#32590]
## Search Terms

indexable interface

## Suggestion

Add a method to extends an indexable interface with certain fields, So we get constrain from indexable interface, also get exact field constrain.

So we want a new way to extends indexable interface.
## Use Cases

If we define reducers like this:

```ts
interface Reducer<S> {
  [key: string]: (payload: any, state: S) => S
}

interface CertainReducer extends Reducer<State> {
  setName(payload: string, state: State) => State
}

const store = createStore({ reducer: CertainReducer }) // Ok
// when to use this...
declare const reducer: CertainReducer
reducer.whatYouWant // oop, should get error but it passed
```
If not `extends`, the reducers wouldn't be recognized a reducer.

## Examples

for `implement` keyword like this:
```ts
interface Reducer<S> {
  [key: string]: (payload: any, state: S) => S
}

interface CertainReducer implement  Reducer<State> {           // any other words is ok
  setName(payload: string, state: State) => State
}

const store = createStore({ reducer: CertainReducer }) // Ok, it's a reducer

declare const reducer: CertainReducer
reducer.whatYouWant // error, `whatYouWant` didn't exists in interface `CertainReducer`

```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
```ts
interface Reducer<S> {
  [key: string]: undefined|((payload: any, state: S) => S)
}
```

?

**Comment by fnknzzz** [comment]
> ```ts
> interface Reducer<S> {
>   [key: string]: undefined|((payload: any, state: S) => S)
> }
> ```
> 
> ?

Looks good. But `const t: Reducer = {a: undefined}` will also pass typing check

**Comment by fnknzzz** [comment]
Just replacing `interface` into `type` works fine.
