### ISSUE TITLE
Interfaces and types that use conditional types and inheritance no longer assignable

### ISSUE THREAD

**Issue by mtreder** [microsoft/TypeScript#32608]
**TypeScript Version:**  3.6.0-dev.20190727

**Search Terms:** conditional, generic, inheritance, variance

**Code**
Prior to the --strictFunctionTypes compiler flag in the strict suite, this previously worked fine.
```ts
type GetPropertyNamesOfType<T, RestrictToType> = { [PropertyName in Extract<keyof T, string>]: [T[PropertyName]] extends [RestrictToType] ? PropertyName : never }[Extract<keyof T, string>];
type GetAllPropertiesOfType<T, RestrictToType> = Pick<T, GetPropertyNamesOfType<Required<T>, RestrictToType>>;

export interface IRequestA<T extends object>{
    getValue(name: keyof GetAllPropertiesOfType<T, string>): string;
    getObject<ObjectType extends object = never>(name: keyof GetAllPropertiesOfType<T, ObjectType>): IRequestA<ObjectType>;
}

interface Base {
    BaseString: string;
    BaseNumber: number;
    BaseObject: Base;
}

interface Derived extends Base {
    DerivedString: string;
    DerivedNumber: number;
    DerivedObject: Base;
}

function main(a: IRequestA<Derived>): void {
    const a1: IRequestA<Base> = a;
    a1.getValue("BaseString");
    a1.getObject<Base>("BaseObject");
}
```
As the result of a suggestion in [Issue 28671](https://github.com/microsoft/TypeScript/issues/28671) the interface was switch to a type.  This worked until TypeScript version 3.5 where the assignment again started to fail when inheritance was involved with T.

```ts
type GetPropertyNamesOfType<T, RestrictToType> = { [PropertyName in Extract<keyof T, string>]: [T[PropertyName]] extends [RestrictToType] ? PropertyName : never }[Extract<keyof T, string>];
type GetAllPropertiesOfType<T, RestrictToType> = Pick<T, GetPropertyNamesOfType<Required<T>, RestrictToType>>;

export type IRequestB<T extends object> = {
    getValue(name: keyof GetAllPropertiesOfType<T, string>): string;
    getObject<ObjectType extends object = never>(name: keyof GetAllPropertiesOfType<T, ObjectType>): IRequestB<ObjectType>;
}

interface Base {
    BaseString: string;
    BaseNumber: number;
    BaseObject: Base;
}

interface Derived extends Base {
    DerivedString: string;
    DerivedNumber: number;
    DerivedObject: Base;
}

function main(b: IRequestB<Derived>): void {
    const b1: IRequestB<Base> = b;
    b1.getValue("BaseString");
    b1.getObject<Base>("BaseObject");
}
```
With some changes I got it to work by switching around the allowed property name list:
```ts
type GetPropertyNamesOfType<T, RestrictToType> = { [PropertyName in Extract<keyof T, string>]: [T[PropertyName]] extends [RestrictToType] ? PropertyName : never }[Extract<keyof T, string>];
type GetAllPropertiesOfType<T, RestrictToType> = Pick<T, GetPropertyNamesOfType<Required<T>, RestrictToType>>;

export type IRequestC<T extends object> = {
    getValue<K extends keyof GetAllPropertiesOfType<T, string>>(name: K): string;
    getObject<ObjectType extends object = never>(name: keyof GetAllPropertiesOfType<T, ObjectType>): IRequestC<ObjectType>;
}

interface Base {
    BaseString: string;
    BaseNumber: number;
    BaseObject: Base;
}

interface Derived extends Base {
    DerivedString: string;
    DerivedNumber: number;
    DerivedObject: Base;
}

function main(c: IRequestC<Derived>): void {
    const c1: IRequestC<Base> = c;
    c1.getValue("BaseString");
    c1.getObject<Base>("BaseObject");
}
```

**Expected behavior:**
I would expect b to be assignable to b1 in the example above to be able to work with the subset of properties that are specific to the base type.

**Actual behavior:**
The assignment doesn't work or I need to jump through hoops to make it work.

I don't know if I'm just trying to limp by staying one step ahead of type checker improvements that will again cause me to make changes or possibly disallow me from accomplishing what I'm looking for.

I'm also not sure about the inconsistency in the need to update the `getValue` method versus `getObject`.

**Playground Link:**
[Demo](http://www.typescriptlang.org/play/#code/C4TwDgpgBA4hwAUBOB7STQDkCGBbCAzgPIBmAKuBADxkA0UASocEgJYDGwZKFkAfFAC8UAN5QA2sjQQMIHPiisAdlACiADxbZOVANYQQKElDpQCLZQHM+AXQBcEspNToseCDZtQImiEoAmBBJM5myc3LweUAD8UFKucu5QDkoQAG4yUAC+4hpaOvqGxqahVrYA3ACwAFCgkLDwAIIANs3xMsCshKSRNPQhFuE8lALCCBy6fQ2ILh2J+MTklFRMAI4ArqxIEP40fP3MYVzD-HxV1TU+YCgYikrAMiTa0ACSa+vMjTTevgFBKAAjABWEE4fBENSgUKglngADVsM0PgAKJTuByFIzTFptWYYLqLXolCxKawASgcpVJ52hMPgRGBoOAVAZIPClB+Dz+UEBbOAQigqQySD4qPRUExxjgwBx7Xx3SWkCmrKZkT4FKgbwgG0+LMZ7P45yyNUu6mutzqr3ezAAQt8fFzAjz9cBRqJIdDYcAEUiIGL8BiDFjpbK8Z0FUT6FTyZSSZYaZ76S69XzIpy-E7eUyBUKZKK0QGJUGpU1WnLw4TlqYVQaIOqHFqdeY7TWuCMjSbqlcbvzLZrreYAML236Zl1uiHVWlen0fKgAaXT3Ml2LLYYJPSrUbjfHz4vnGujCahXtbKdVHIdGf+Lpz6Tz-oggaKq9x0nllaV1Zdao1jY+Q7nrWZw1MaFzVMoDxIE87DQDa2AENAk60vBiEAMpxrGbDUh6UKoRAmDrLgAIyCkREkUgx5QPhrYOPhHbgZBjzPFAAAiMisBk-hLk6+HulO0LsWwXEYdhlhYVYVFCZxOyEcRpGCuRMhSRxXG0dRCEQAxNQkOsSicKwKAqLg2DKMi2ANgOMpUNJXH7FAAKWdqAHAHatk7PZ7BOU2wDDu5-j1lAaQoKw3HIdC7BGeYUDYAAjN5LlfPhbrYFRcUAHQzoiKIAET4aJVg5WSaWxZlSZ8lQyXInlmmtkV5y4VAkVKNFALxf2zm2pVmlugCVFtWV3rZX6NXoXG9WNQNp7JlVo0QHVxWdrSzXRew7X-sww7JQK7BUWtg2ziN+XjYtAlQvt00VbNNEuhN1RZEAA)

**Related Issues:**
[Issue 28671](https://github.com/microsoft/TypeScript/issues/28671)
[Issue 24190](https://github.com/microsoft/TypeScript/issues/24190)

**Comment by RyanCavanaugh** [comment]
Is this the simplest possible repro?

**Comment by mtreder** [comment]
I can remove the extra layer of creating a type to pull property names from via keyof, but still see the error.

[Reproduction](http://www.typescriptlang.org/play/#code/C4TwDgpgBA4hwAUBOB7STQDkCGBbCAzgPIBmAKuBADxkA0UASocEgJYDGwZKFkAfFAC8UAN5QA2sjQQMIHPiisAdlACiADxbZOVANYQQKElDpQCLZQHM+AXQBcEspNToseCDZtQImiEoAmBBJM5myc3LweUAD8UFKucu5QDkoQAG4yUAC+4hpaOvqGxqahVrYA3ACwAFA1PmAoGFCgkFAAkkwAjgCuzABCNN6+AUEoAEYAVhCcAsIiNVCLUJbwAGrYADa9ABRK7g5wiC4ybvjE5JQ09KVK1gCUDjeWVdVLy-BEk9PAVJ9T4ZQhsA-IEoON-sAhFBUhkkHxdvtYPB4idEmdSJErlA-t9InwHu0ur1zAMcQD+C8sjUaspgUgSNpoH1sARoPNXktmayAMoWW6PPnPBaclkQTDdXBjGQpCVSpAvN5ciBk4AOJWU6nVWkyBnsaAAERkrAy-iBIKCStEwsWhrYJt5bH5ZkFCqWtuNEH84sl0uhspkrptRpNKrVoo1tWqJG6Sk4rBQKlw2GU2zGDg6EB6-So7pN+IcaRQrFN7Le7AT5igYwAjOmidmlbMq4Gq9WAHQrYDrLYQbYAIiVDqsfbuLZrHY+Xx0jf7SpVI8pQA)

**Comment by mtreder** [comment]
This issue sounded related, but I didn't see the error go away when I was using the under dev typescript version:

[Issue 31804](https://github.com/microsoft/TypeScript/issues/31804)

**Comment by RyanCavanaugh** [comment]
@ahejlsberg this looks like a possible incorrect variance measurement. `IRequestB` should be covariant in `T` but it's being treated as invariant because of the `T[PropertyName]` usage in the conditional type, but it seems like the check expression in a conditional isn't really a valid variance measurement site? Not sure

**Comment by jack-williams** [comment]
I think the issues here is with the simultaneous use of `keyof T` and `T[PropertyName]`, rather than the conditional type. Repro without conditional types that I think is roughly faithful:
```ts
type GetPropertyNamesOfType<T, K extends number> = {
    [PropertyName in keyof T & string]: [T[PropertyName], PropertyName][K]
}[keyof T & string];

type GetAllPropertiesOfType<T, K extends number> = Pick<T, GetPropertyNamesOfType<Required<T>, K> & keyof T>;

export type IRequestB<T extends object, K extends number> = {
    getValue(name: keyof GetAllPropertiesOfType<T, K>): string;
    getObject<ObjectType extends object = never>(name: keyof GetAllPropertiesOfType<T, K>): IRequestB<ObjectType, K>;
}

interface Base {
    BaseString: string;
}

interface Derived extends Base {
    DerivedString: string;
}

function main(b: IRequestB<Derived, 1>): void {
    const b1: IRequestB<Base, 1> = b;
}
```

Related to #32311 and #32674.

**Comment by mtreder** [comment]
> I think the issue here is with the simultaneous use of keyof T and T[PropertyName], rather than the conditional type. Repro without conditional types that I think is roughly faithful:
> type GetPropertyNamesOfType<T, K extends number> = {
>     [PropertyName in keyof T & string]: [T[PropertyName], PropertyName][K]
> }[keyof T & string];
> 
> type GetAllPropertiesOfType<T, K extends number> = Pick<T, GetPropertyNamesOfType<Required<T>, K> & keyof T>;
> 
> export type IRequestB<T extends object, K extends number> = {
>     getValue(name: keyof GetAllPropertiesOfType<T, K>): string;
>     getObject<ObjectType extends object = never>(name: keyof GetAllPropertiesOfType<T, K>): IRequestB<ObjectType, K>;
> }
> 
> interface Base {
>     BaseString: string;
> }
> 
> interface Derived extends Base {
>     DerivedString: string;
> }
> 
> function main(b: IRequestB<Derived, 1>): void {
>     const b1: IRequestB<Base, 1> = b;
> }
> Related to #32311 and #32674.

The intent in my example was to pull the property names for a property that matches a given data type.  The getValue method should only allow specifying a "name" of a property on T that is of type string (i.e. BaseNumber and BaseObject should be excluded).  It is also filtering out property names that aren't of type string, but my example doesn't have any property names that aren't strings.  The quoted example above looks to be a different way to express Extract<keyof T, string>.

**Comment by mtreder** [comment]
It is also a need for this to work with a list of objects of a given type.  My current workarounds don't seem to allow me to not produce an error.

```
type GetPropertyNamesOfType<T, RestrictToType> = { [PropertyName in Extract<keyof T, string>]: [T[PropertyName]] extends [RestrictToType] ? PropertyName : never }[Extract<keyof T, string>];
type GetAllPropertiesOfType<T, RestrictToType> = Pick<T, GetPropertyNamesOfType<Required<T>, RestrictToType>>;

export interface IRequestListOfObjects<T extends object>{
	length: number;
	getObject(index: number): IRequestC<T> | undefined;
}

export type IRequestC<T extends object> = {
    getValue<K extends keyof GetAllPropertiesOfType<T, string>>(name: K): string;
    getObject<ObjectType extends object = never>(name: keyof GetAllPropertiesOfType<T, ObjectType>): IRequestC<ObjectType>;
	getListOfObjects<ObjectType extends object = never>(name: keyof GetAllPropertiesOfType<T, ObjectType[]>): IRequestListOfObjects<T>;
}

interface Base {
    BaseString: string;
    BaseNumber: number;
    BaseObject: Base;
	BaseObjectList: Base[];
}

interface Derived extends Base {
    DerivedString: string;
    DerivedNumber: number;
    DerivedObject: Base;
	DerivedObjectList: Base[];
}

function main(c: IRequestC<Derived>): void {
    const c1: IRequestC<Base> = c;
    c1.getValue("BaseString");
    c1.getObject<Base>("BaseObject");
	c1.getListOfObjects<Base>("BaseObjectList");
}
```

[Example](http://www.typescriptlang.org/play/#code/C4TwDgpgBA4hwAUBOB7STQDkCGBbCAzgPIBmAKuBADxkA0UASocEgJYDGwZKFkAfFAC8UAN5QA2sjQQMIHPiisAdlACiADxbZOVANYQQKElDpQCLZQHM+AXQBcEspNToseCDZtQImiEoAmBBJM5myc3LweUAD8UFKucu5QDkoQAG4yUAC+4hpaOvqGxqahVrYA3ACwAFCgkLDwAIIANs3xMsCshKSRNPQhFuE8lALCCBy6fQ2ILh2J+MTklFRMAI4ArqxIEP40fP3MYVzD-HxV1TU+YCgYikrAMiTa0ACSa+vMADKs5qREAEYAKwgnAING8vgCQRQQJBwD4IhqAEhmn5LMAABYpda4f4yc5IyzwAHAzgACmU-h82NxMgAlA43hANswAMJ7KAAHyg6wCEBIyh25yyNUu6mutzqr3ebPBPgeUKgMNJ8KEohqUE1UCJwAAathmh8qABpCEKwJQQpGaYtNqzDBdRa9EoWJTWPhkpTuBzGhlmV2Wc5a7XE2E6ElwyJmvwW5VwtWpDJID1e-AOK3GODAW3tB3dJaQKYR8IjP1MlnmdnFrgjAk676-EjVsHVqPymPQsPABPpGQp72WgzWrM5+2dfPO+ityjiGx8Msy8wN4B-LtgshnGoii7VZQPJBPdjQABC2AI0ER1WDp-PAGUAw5Sm6g1qbxBMDi8UgaV+X5q39WDhvgSAFdsuQFnhAs7CqKu73I8zxQAAIjIrAZP40aKm+6pXlqKFsOh95sG6j4Bn+yGoehH60t+UBKJ++IanhlE7IBUDAci+FoaxYE-MAEHntBW6wSQvKcKwKAqLg2DKGS7CMouwDslx6Hzg4aQoKwGGXsG7CSeYUDsAAjApzIfJWVBvqMhnkcZAB0Or6oaEBkgARG+RFWK5dK2UZDmhiqlmQR67mQdW3kEvZ9Z8auKpglZbmgSqy4RVuQA)

**Comment by RyanCavanaugh** [comment]
Here's a *cough* simplified demo that the variance is measured incorrectly relative to a manual instantiation. `IRequestC<Base>` and `IRequestBase` should have the same respective relations to `IRequestC<Derived>` and `IRequestDerived`.

```ts
interface Base {
    BaseString: string;
    BaseObject: Base;
}

interface Derived extends Base {
    DerivedString: string;
    DerivedObject: Base;
}

type GetPropertyNamesOfType<T, RestrictToType> = {
    [PropertyName in keyof T]: T[PropertyName] extends RestrictToType ? PropertyName : never
}[keyof T];

export type IRequestC<T> = {
    getObject: (name: GetPropertyNamesOfType<T, object>) => void;
}

export type IRequestDerived = {
    getObject: (name: GetPropertyNamesOfType<Derived, object>) => void;
}
export type IRequestBase = {
    getObject: (name: GetPropertyNamesOfType<Base, object>) => void;
}

function concreteContravariant(base: IRequestBase) {
    let derived: IRequestDerived = base;
}

function concreteCovariant(derived: IRequestDerived) {
    let base: IRequestBase = derived;
}

function genericContravariant(base: IRequestC<Base>): void {
    const derived: IRequestC<Derived> = base;
}

function genericCovariant(derived: IRequestC<Derived>): void {
    const base: IRequestC<Base> = derived;
}
```

**Comment by jack-williams** [comment]
As check types are related bivariantly I would expect that variance measuring going wrong for the check type would make the measured types more assignable, rather than less. (False-negative)
```ts
type Alias<T> = [T] extends [number] ? true : false;

interface Foo<T> {
    x: Alias<T>;
}

const a: Foo<number> = { x: true };
const b: Foo<number | boolean> = a; // no error
const shouldBeFalse: false = b.x;

const c: Foo<number | boolean> = { x: false };
const d: Foo<number> = c; // no error
const shouldBeTrue: true = d.x;
```

Conversely, the extends types is invariant so that usually makes measured types less assignable, rather than more. (False-positive).
```ts
type Alias2<T> = [number] extends [T] ? true : false;

interface Foo2<T> {
    x: Alias2<T>;
}

const a: Foo2<number> = { x: true };
const b: Foo2<number | boolean> = a; // error
const shouldbeTrue: true = b.x;
```

I think trying to get any meaningful measurements from a conditional type is hard. When the true and false types are unrelated then measurements are just _wrong_ because the conditional type cannot be an order preserving function of its outer type parameters.

My concern is that removing measurements for conditional types would be a breaking change for many people that used `any` as the instantiation for a measured conditional type.

**Comment by mtreder** [comment]
I just wanted to check in on this to see if there was an idea on when this would be addressed.  I am trying to determine whether I should look at alternatives for my API.

**Comment by ahejlsberg** [comment]
This looks to be the same issue as #32674. When a type parameter appears in both a co- and contra-variant position within a type, as in `T[keyof T]`, we measure that type parameter as invariant. This is a conservative measurement and it may indeed not always be the case, as illustrated by my comment [here](https://github.com/microsoft/TypeScript/issues/32674#issuecomment-716192565). The only real fix here is to mark such occurrences as unmeasurable and force structural evaluation--but we know there are significant performance penalties associated with that.
