### ISSUE TITLE
TSconfig does not preserve directory structure

### ISSUE THREAD

**Issue by ianpaschal** [microsoft/TypeScript#32607]
I'm refiling #5134 because it's marked as fixed but it's still occurring in v3.5.3.

**TypeScript Version:**  3.5.3

**Search Terms:** tsc directory folder preserve outdir rootdir

**Code**

This is not testable with a single snippet of code.

Suppose I have the following project structure:

```
/
|- dist/
|
|- src/
|  |
|  |- images/
|     |
|     |- hardware/
|        |
|        |- thing-A.png
|        |- thing-B.png
|        |- thing-C.png
|        |- thing-D.png
|
|- tsconfig.json
```

My config is as follows:

```json
{
    "compilerOptions": {
        "declaration": true,
        "sourceMap": true,
        "target": "es5",
        "module": "commonjs",
        "noImplicitAny": false,
        "outDir": "dist",
        "jsx": "react",
        "lib": [
            "es6",
            "dom"
        ],
        "rootDirs": [
            "src"
        ],
        "baseUrl": "src",
        "allowJs": false
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "build",
        "scripts",
        "src/**/*.test.tsx",
        "src/__mocks__/**/*",
        "src/stories/**/*"
    ]
}
```

Finally, if you run simply `tsc`.

**Expected behavior:**

I expect the thing images to end up like so: `dist/images/hardware/thing-A.png`.

**Actual behavior:**

I expect the thing images to end up like so: `dist/images/thing-A.png`.

This breaks the distributable files because the compiled index.js is still pointing to `./images/hardware/thing-A.png` even though only `./images/thing-A.png` exists.

**More Info:**

As suggested in #5134, I've tried using the rootDir option. I've tried setting it to `.` and `./`, in both `tsconfig.json` as well as an argument when running `tsc`. It does not seem to have any effect on the discarding of directory structure.

**Playground Link:** 

**Related Issues:** 

As mentioned above, this is intended to be a duplicate of #5134.

**Comment by RyanCavanaugh** [comment]
I'm confused here - TypeScript doesn't copy .png files.

**Comment by ianpaschal** [comment]
Hmm. Right you are. This is actually probably a Parcel issue instead.

Sorry about that. I will double check if I'm also having it was .ts files tomorrow and close if not.

**Comment by ianpaschal** [comment]
Yup. `.ts` files do behave correctly, not other ones. I think I assumed that `.pngs` would be moved too if they're imported as modules within a compiled TypeScript file, but that was perhaps silly. Sorry to open the issue.
