### ISSUE TITLE
Make it possible to only export some overloads

### ISSUE THREAD

**Issue by erik-kallen** [microsoft/TypeScript#32609]
## Search Terms

export overload

## Suggestion

Make it possible to export overloaded signatures without exporting the function definition.

## Use Cases

Say I have a function whose intended use is one of:

```
doSomething(x: number, y: string): string;
doSomething(x: string, y: number): number;
```

The implementation of this function needs to have the signature ```doSomething(x: number | string, y: number | string): number | string;``` (or something even more generic)

However, this means that the function can be invoked as ```doSomething(1, 2)```, which is not the intended use. I do not suggest changing this within a single module, but if the function is exported I would want to be able to say

```
export function doSomething(x: number, y: string): string;
export function doSomething(x: string, y: number): number;
function doSomething(x: number | string, y: number | string): number | string {
   // ... implementation goes here, probably checking eg. typeof x
}
```

but in Typescript 3.5 this gives the error message "Overload signatures must all be exported or non-exported." My suggestion is to remove this restriction. This would mean that:

* code in the same module sees all the signatures, and
* code in other modules see only exported signatures.

For codegen, it would mean that the function is exported if any overload signature is exported.

## Examples

module1.ts
```
export function doSomething(x: number, y: string): string;
export function doSomething(x: string, y: number): number;
function doSomething(x: number | string, y: number | string): number | string {
   return typeof x === 'number' ? 'hello' : 42;
}
```

module2.ts
```
import { doSomething } from './module2';

const myString = doSomething(1, 'a'); // $ExpectType string
const myNumber = doSomething('a', 1); // $ExpectType number
doSomething('a', 'a'); // $ExpectError
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nattthebear** [comment]
This already works the way you'd want it to for this use case.  The implementation of an overloaded function is not callable, either from within the module or outside it.  https://www.typescriptlang.org/docs/handbook/functions.html#overloads

**Comment by fatcerberus** [comment]
> However, this means that the function can be invoked as doSomething(1, 2), which is not the intended use

Yeah, no, this isn't actually true.  The implementation signature isn't used to typecheck call sites, for exactly that reason--it's usually too permissive for that purpose.

**Comment by poseidonCore** [comment]
Please note there is a small typo in the original example:
```ts
// module2.ts

import { doSomething } from './module1'; // ##### NOT 'module2' #####

const myString = doSomething(1, 'a'); // $ExpectType string
const myNumber = doSomething('a', 1); // $ExpectType number
doSomething('a', 'a'); // $ExpectError
```
My feeling is that this feature would be an unnecessarily complication just to support a lazy coding practice.

**Comment by erik-kallen** [comment]
@poseidonCore in what way is it a "lazy coding practice"?

Anyway, closing since I didn't know that it already works the way I want

**Comment by poseidonCore** [comment]
@erik-kallen: Just put in the missing "export":

```ts
export function doSomething(x: number, y: string): string;
export function doSomething(x: string, y: number): number;
export function doSomething(x: number | string, y: number | string): number | string {
   // ... implementation goes here, probably checking eg. typeof x
}
``

**Comment by erik-kallen** [comment]
ehh, that was not what this feature request was about.

But, anyway, I was mistaken.

**Comment by poseidonCore** [comment]
@erik-kallen: Your feature request was about exporting only some overloads and you specifically wanted to leave out one of the "export" keywords to achieve this (which was based on a misunderstanding). 

You can already export selected signatures of a function by just exporting aliases for that function: eg

```ts
export function doSomething(x: number, y: string): string;
export function doSomething(x: string, y: number): number;
export function doSomething(x: number | string, y: number | string): number | string {
   return typeof x === 'number' ? 'hello' : 42;
}

export var doSomethingElse:(x:string, y:number)=>number = doSomething;
```

Or even just 
```ts
function doAnything(x: number, y: string): string;
function doAnything(x: string, y: number): number;
function doAnything(x: number | string, y: number | string): number | string {
   return typeof x === 'number' ? 'hello' : 42;
}

export var doSomething:(x:string, y:number)=>number = doAnything;
```

Leaving out an "export" keyword as you did was an unnecessary complication of the syntax to achieve something that you didn't quite understand originally, and seemed lazy when there was already an existing way of easily exporting a specific signature.

Sincerely, I wasn't criticising you: the TS issues list is sometimes littered with feature requests for shorthand syntax and new conventions for things that can easily be achieved by existing coding patterns, ... whereas in reality, there are so many outstanding important issues that are unresolved.

**Comment by lampuiho** [comment]
I don't think the above solution solved the problem where you don't want to expose the combined function signature, but only the individual signatures which can have conflicts.

To do this you can use an interface

```
function _foo (x: number | string, y: number | string): number | string {
   return typeof x === 'number' ? 'hello' : 42;
}
interface Foo {
  doSomething(x: number, y: string): string;
  doSomething(x: string, y: number): number;
}
export const foo: Foo = _foo;
```

**Comment by poseidonCore** [comment]
The original construction already does what you are suggesting without the need to use an interface: 

```
export function doSomething(x: number, y: string): string;
export function doSomething(x: string, y: number): number;
export function doSomething(x: number | string, y: number | string): number | string {
   // ... implementation goes here, probably checking eg. typeof x
}
```
If you want to export just a **single** signature, then use a wrapper as suggested.

**Comment by lampuiho** [comment]
> The original construction already does what you are suggesting without the need to use an interface:

No it doesn't . "export function doSomething(x: number | string, y: number | string): number | string" is exported, which is not desired.
The OP wants only "doSomething(x: number, y: string): string" AND "function doSomething(x: string, y: number): number;" to be exported.

**Comment by poseidonCore** [comment]
The base signature is exported, but it is not "usable" from the TypeScript perspective: only the 2 override signatures are useable from the TypeScript perspective.

From the JavaScript perspective, you can put any combo of string/number in the parameters when you call it.

You are confusing intentions. See this demo [here](https://www.typescriptlang.org/play/?#code/HYQwtgpgzgDiDGEAEAVaAXJBvAsAKCUKQgA8YB7AJ0wDMBXYedAS3OCQBNyBlcydABbNgAcwAUJAFxJgdMACMIlADRIAntKjpKwkQEpN23QG58RYmSq0GTVuy69+Q0RMM7RqjTLmLKB7wpKpgREpBTUSPSMLGycPHwQgrquAb5IAD5IWu4intKygZQZWUai-gVpmdm62GZEAPT1SAB0rUjMYDAANhCQwOggMewi5NBIAkoQqjCU5PIg8l1qSPAT8ADWNRAizUjoajAQ5DRIJHXmhJSJdJTsJMHmAL74z3j4aFrNDglJLgCMqgARCBAXpjEhGkgAOoAeQASgBpbjtdgobjNd4YL7xJzJYGA1R-MEQpqwxHI4SodGYz7fXEufFAkHEyEAERhAFFkQA5GEoaHwhEoqmqeR0TBcMaUgBS1LwH3Q2MciWc4gBSCJ4LZnJ5fIFiOFaNF4riUvYsoxeCAA).
