### ISSUE TITLE
Proper type assertion without temporary variable

### ISSUE THREAD

**Issue by Ginden** [microsoft/TypeScript#32604]
## Search Terms

"ensure literal type typescript", "force typecheck typescript", "force literal typecheck typescript"

This limitation is widely recognized: https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html

## Suggestion

I would like to have syntax to enforce typechecking without need to create temporary variable.

## Use Cases

Less code, better typechecking of object literals.

## Examples

Now I have to write:

```typescript
const foo: Foo = getFoo();
if (!foo.id) {
    const temp: Partial<Foo> = {
        id: generateId()
    };
    Object.assign(foo, temp);
}
```

I would like to write
```typescript
const foo: Foo = getFoo();
if (!foo.id) {
    Object.assign(foo, {
        id: generateId()
    } as! Partial<Foo>); // "as! type" is only idea
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
This seems like a good case for a helper function: 

```ts

function assignPartial<T>(o: T, p: Partial<T>) {
    Object.assign(o, p);
}
if (!foo.id) {
    assignPartial(foo, {
        id: generateId(),
    });
    
    assignPartial(foo, {
        id: 42 // err
    });
    
    assignPartial(foo, {
        notId: 42 // err
    });
}
```
Don't think special syntax is really warranted here.

**Comment by Ginden** [comment]
So let's add to situation other variations on `Partial`. Eg. TypeORM `QueryDeepPartialEntity<T>` or:
```
type PartialOrFunction<T> = {
   [K in keyof T]? T[K] | () => T[K]
}
```

Moreover, I tried to add some type safety to `joi` definitions by making eg.
```
const validator = object({

} as SchemaMapFor<IArticle>);
```

**Comment by RyanCavanaugh** [comment]
Duplicate #7481 ?

**Comment by Ginden** [comment]
@RyanCavanaugh Yes, it is.
