### ISSUE TITLE
The types when inherit from Error?

### ISSUE THREAD

**Issue by xnsua** [microsoft/TypeScript#32617]
Notice the value1 has Error and value2 is Ok.
I think value1 should be OK. 
 If value1 should be OK. Is there any workaround?
typescript version: 3.5.1
```
export interface ITypeOf<T> {
    new (): T;
}

class UserError extends Error {
    constructor(m: string) {
        super(m);
        // Set the prototype explicitly.
        Object.setPrototypeOf(this, UserError.prototype);
    }
}

// Error here
const value1: ITypeOf<Error> = UserError;

class Foo {}
class Foo2 extends Foo {
    public constructor() {
        super();
    }
}
// Ok here.
const value2: ITypeOf<Foo> = Foo2;
```

**Comment by j-oliveras** [comment]
Can you follow the template? If you not, the issue will be probably closed by a typescript team member without reading it.

**Comment by xnsua** [comment]
> Can you follow the template? If you not, the issue will be probably closed by a typescript team member without reading it.

I do not know there is a template.   When I create this issue.  The
 textbox show I should ask normal question on stackoverflow and compiler problem here. But I read some other issues. The template should be like, so I will close this issue.

Expected behavior
Actual behavior

**Comment by j-oliveras** [comment]
Creating a new issue I see:
![imatge](https://user-images.githubusercontent.com/15308683/62119720-6fc29980-b2c0-11e9-8d6a-cdf8787ef525.png)

Selecting `Bug report` it ask for `Expected behavior` and `Actual behavior`.
