### ISSUE TITLE
All incompatibility with ECMAScript should be listed as open issues

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#32614]
#3714 #27454 must be open. Lack of customer demand won't be the reason to ignore incompatibility.

**Comment by RyanCavanaugh** [comment]
Respectfully, stop filing issues telling us how to manage our issues.

We reserve the right to say that certain incompatibilities don't warrant fixing.

**Comment by falsandtru** [comment]
Developers have to know all traps to avoid them. You must provide a way to know them. I believe hiding the traps is the worst response.

**Comment by kitsonk** [comment]
Closing the issue with a definitive label of "won't fix" is much better than keeping an issue open and allowing someone to think it will eventually be fixed.  Then developers can avoid them.

Using an issue repository also as an authoritative guide to using a language also is not a good pattern.  An issue repository is for managing issues, nothing more or less.

**Comment by falsandtru** [comment]
I'm not limiting solutions to issue management but `won't fix` label is useless to find the traps. All issues which emit problematic code should have the dedicated label.

**Comment by RyanCavanaugh** [comment]
I'd be very happy to have a documentation page listing known problems. I'll include that in the new Handbook

**Comment by falsandtru** [comment]
Documentation is a very good way but basically it is a maintainer's task.

**Comment by kitsonk** [comment]
@RyanCavanaugh would be more than glad to contribute to such a thing in the handbook.  I know of a couple personally (like proper string iteration on downlevel emit #2585, and mixing of ES5/ES2015+ plus code causing issues in certain situations ref: #17088) and I guess not being able to extend built-ins in ES5 (which isn't really a TypeScript issue, more than TypeScript doesn't know it can't extend certain things in a down-emit).
