### ISSUE TITLE
Intellisense shows full internals of a type declaration but not of an interface declaration on hover

### ISSUE THREAD

**Issue by po35** [microsoft/TypeScript#32616]
1. Declare an interface
2. Consume that interface somewhere
3. Hover over where you consume it
=> Intellisense won't show any internals of that interface

Do 1, 2 and 3 with a type declaration and Intellisense shows all internals. Discussion on reddit: https://www.reddit.com/r/typescript/comments/cisi08/getting_intellisense_to_show_function_signatures/evejcy0/?context=3

**Expected behavior:**
Show all internals of any declaration on hover.

**Actual behavior:**
Just shows internals of type declarations.

**Playground Link:** 
https://codesandbox.io/s/small-bird-l13fg?fontsize=14

Hover with your mouse over `IDuck` and `RealDuck` in the respective `const` statement.

**Comment by jcalz** [comment]
Related to #25784?  Right now there is no way to selectively expand/collapse parts of a type definition.  If we could do this, then it would make sense to do this for interfaces as well as type aliases (with perhaps interfaces collapsed by default and type aliases expanded by default).  

Also, an actual [playground link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIBECuCDWyDeAUMsiHALYQBcyAzmFKAObHIID2ANu1DfYyBYBfQoTABPAA4oAShDicsuZAF4CrMpT4NmrDt150dgwiMIcQ9ZOXFKcNDNjxr8pCtWQByAApxMnTwAaNi4eGk8AI05EHE9kEQB6BOQAC3YAN2hkDKzHXBoAE3YIWlJ2MGQIAA9JOBAC0QsrGzkFOxpWxSdVAjctLwBBEDIgkINwqAgCuMTktMyobIXkTvbKmrqC0qA)

**Comment by RyanCavanaugh** [comment]
This is one of the differences between aliases and interfaces. Interactive expansion would definitely be nice; see the above linked issue

**Comment by po35** [comment]
Thanks for the fast feedback and he playground link!

>Related to #25784? 

Yes, but #25784 is more specific since it addresses collapsing. I just want to get the same info from an interface I get from type on hover.

I am still on the fence re TS. Yes it helps and there is a lot of good stuff but there are also some subpar things. If I already make the work, declare type/interfaces for all my stuff I want to be able to see their definition anywhere easily. Having to go to the definition of interfaces to get the interface is not that much better than just going to plain JS object and checking briefly its signature or its JSDoc. And there's actually no reason to treat interface differently than type.

So, I'd be happy to see a PR here. Thanks!

**Comment by brillout** [comment]
Related feature request: https://github.com/microsoft/TypeScript/issues/56010.
