### ISSUE TITLE
Returned type in index signature fails to get widened in error message

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3261]
See https://github.com/Microsoft/TypeScript/issues/3234#issuecomment-104003549.

**Comment by danquirk** [comment]
Think this was closed in error.

**Comment by DanielRosenwasser** [comment]
A (partial) fix might be available at thttps://github.com/Microsoft/TypeScript/commit/0b1db589bad2a73f606cb616159b9251e8036a53 (branch `indexersAndContextualTypesAndStuff`).

**Comment by mhegazy** [comment]
looks fixed in latest.
