### ISSUE TITLE
中文文档(基础类型中---元组 Tuple）越界问题是错误

### ISSUE THREAD

**Issue by yaogengzhu** [microsoft/TypeScript#32628]
###  中文文档(基础类型中---元组 Tuple）越界问题是错误   
[地址](https://www.tslang.cn/docs/handbook/basic-types.html)  

### 元组中定义的问题
当访问一个越界的元素，会使用联合类型替代：   
```js
// 错误位置 
x[3] = 'world'; // OK, 字符串可以赋值给(string | number)类型

console.log(x[5].toString()); // OK, 'string' 和 'number' 都有 toString
```

### 英文文档中；
```js
x[3] = "world"; // Error, Property '3' does not exist on type '[string, number]'.

console.log(x[5].toString()); // Error, Property '5' does not exist on type '[string, number]'.
```
经过实践， 英文文档是正确的～

**Comment by trotyl** [comment]
See https://github.com/microsoft/TypeScript/issues/31554#issuecomment-495813004

**Comment by jiangguangyao** [comment]
那什么，我刚开始学，我问一下，这块像中文文档的demo上的那种写法，那个数组除了一一对应，超出了的正常是能添加还是不能添加啊？比方元组 [number, string],赋值的时候是[0, 'a', 'b']，这样可以么？

**Comment by jiangguangyao** [comment]
> 那什么，我刚开始学，我问一下，这块像中文文档的demo上的那种写法，那个副本除了一一对应，超出了的正常是能添加还是不能添加啊？字符串]，赋值的时候是[0，'a'，'b']，这样可以么？

好吧  我的问题，网页上搜的中文文档最高是3.1版本的，这ts中文文档没人维护了吧
