### ISSUE TITLE
Tsc does not update output files even though the compilation succeeds

### ISSUE THREAD

**Issue by milottit** [microsoft/TypeScript#32620]
TypeScript Version:  Version 3.5.3

**Search Terms:**
Typescript tsc does not update output files after compilation

**Code**

Here the tsconfig.json

```json
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "allowJs": true,
        "resolveJsonModule": true,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "esnext"
        ],
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "target": "esnext",
        "traceResolution": false,
        "outDir": "dist",
        "esModuleInterop": true,
        "incremental": true // or false does not change anything
    },
    "include": [
        "src",
        "src/**/*.json"
    ],
    "exclude": [
        "node_modules",
        "**/*.bak.ts"
    ]
}
```

**Expected behavior:**
After compilation not being the first, outputDir should have js output files generated/updated accordingly to the new modification.

**Actual behavior:**

tsc compiles well without any complaints. But nothing in outputDir is updated.
If outputDir is deleted and compilation is done again, all files are well generated.

tsc or tsc --watch leads to the same result.
--incremental option is not changing a thing also.

**Comment by RyanCavanaugh** [comment]
Sure looks like you have a zero-input compilation going on there. Did you mean `src/*` ? Try running with `-listFiles`
