### ISSUE TITLE
Bad type checking inside typeguarded block

### ISSUE THREAD

**Issue by lonewarrior556** [microsoft/TypeScript#32625]
**TypeScript Version:**  3.5.1

**Search Terms:** Type Guard
```
interface FOO {
    [key:string]: number
}

declare var foo: FOO | null

if(foo) {
    var a =  foo['string'] // good
    Object.keys(foo).map(key => {
        var b =  foo[key]  // foo cannot possibly be null
    })
}

//related
foo && foo['string'] && Object.keys(foo).map(key => {
    var a = foo[key] // foo cannot possibly be null
})
```

**Expected behavior:**
Should know Object is not 'null'

**Actual behavior:**
Thinks Object is possibly 'null'

**Playground Link:** [ts-playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIHl3IN4ChkHIDaA1hAJ4BcAzmFKAOYC6lyIArgLYBG0uAvrlwATCAgA2cKCgBuU5DAD2i1hiwAfNu3HihwGAAoligJQ58hOVGRxkAXgLGiAclr0QDZ02QB6H8gZlYQsCdG4AKzEwADoycmojZRNozjgABwM4+wA+c0J85CtkbntHZVIKb19-Y2QEOBAQRTBkNMVqamBucXJilA4dEOR+EwEhP2lJSGDagDJZhXLXOkYvZHnkMMiEGLiE42TUjKy7XLx8otsHJzjvP0XFOoamlraOrp6+rUGRoA)

**Related Issues:**

**Comment by AnyhowStep** [comment]
It cannot know that `foo` won't become `null` inside the function, in the general case.

In this specific instance, you can say that the callback is invoked immediately and never invoked again after `.map()`, so, it cannot be `null`.

But the compiler can't know that for sure yet

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/11498

**Comment by fatcerberus** [comment]
Also see #9998.
