### ISSUE TITLE
Inconsistent enum type merging

### ISSUE THREAD

**Issue by zenorbi** [microsoft/TypeScript#32621]
**TypeScript Version:** typescript@3.6.0-dev.20190730 (same with 3.2.4, 3.5.2, 3.5.3)

**Search Terms:** enum hover ternary union merging
enum subtype reduction
getUnionType

**Code**

```ts
enum SomeEnum {
  APPLE = 'APPLE',
  ORANGE = 'ORANGE',
  BANANA = 'BANANA'
}

function test(inputEnumMember: SomeEnum) {
  // Correctly gives `const a: SomeEnum`
  const a: SomeEnum.BANANA | SomeEnum = inputEnumMember;

  // Incorrectly gives `const b: SomeEnum.APPLE | SomeEnum`
  const b = Math.random() < 0.5 ? SomeEnum.APPLE : inputEnumMember;

  // Incorrectly gives `const c: SomeEnum.APPLE | SomeEnum` (really weird)
  const c = Math.random() < 0.5 ? SomeEnum.ORANGE : inputEnumMember;

  // Incorrectly gives `const d: SomeEnum.BANANA | SomeEnum`
  const d = Math.random() < 0.5 ? SomeEnum.BANANA : inputEnumMember;
}
```

**Expected behavior:**
All declared variables have the type `SomeEnum` or at least are consistently "wrong" (see `const c` as showing `APPLE`)

**Playground Link:** 
https://www.typescriptlang.org/play/#code/KYOwrgtgBAyg9hYBRc0DeAoKUCCAFPAGSSgF4oByfIpCgGiygHkAlHAOQHETyLWPu9RgCEOYspVHsxFDAF8MGAGZgQAYwAuASzggoG4AGcNACi0gADmA0pIAWWAQARsABOALlgJkqAJRRMbAB6IKgAYThXV2BNABsATygAcy0ANyMoAAM1XWMoAENPeERbCEzGHJA8wq8S1AA6KXEAH1qfSAlzKxtUB2c3AG5FYNCASXVI6LjElPTDLMq8pyLvUvrqYihW4vayityNKCcJO3yNAAt613yQABMEE38AHigABnqAVigAfja1jZIni61lKfRcriGjBCUHGOSiMQ0CWSaQy2QOUDUKzqkHWBE221WqEyUBMAHdgFpXLdfPsqoc1CczpdrncHs83p8fn8GvwuICoMCevZHODISMYRN4dNkXMFujbljdo0xNIttzIOVsItDrdGRcrjd7hBHlAXu8vr8dmsmqqgZYQb0RYN5BggA

This is a really minor issue as it only applies to hover type information and the reported value while being weird isn't breaking anything.

**Comment by jack-williams** [comment]
This regressed between 3.0.1 -> 3.1.6.

**Comment by RyanCavanaugh** [comment]
Does this have observable effects other than quick info? I don't think it does?

**Comment by jack-williams** [comment]
I guess this should only have observable effects up to the extent that `SomeEnum` and `SomeEnum.APPLE | SomeEnum.ORANGE | SomeEnum.BANANA` are distinguishable.

**Comment by RyanCavanaugh** [comment]
Exactly when to perform subtype reduction is tricky business; there are some compromises we have to make in order for other scenarios to work. "Consistent" type display between different ways of generating observably-same types isn't something we can guarantee.
