### ISSUE TITLE
Missing export error messages are not recognized by MSBuild parser

### ISSUE THREAD

**Issue by qub1n** [microsoft/TypeScript#32629]
Missing export error messages are not recognized by MSBuild parser.

There is a source code with an invalid import:

The compiler message is 

197>./src/components/Wizards/UserWizard/EditUserWizard.tsx
197>1:1325-1340 './convert' does not contain an export named 'func2'.

It is readable for humans, but such error message is not recognized by MSBuild, because it does not contains "ERROR" string and it is not in the standard error format

In consequences the result of the build is:

error MSB3073: The command "yarn run build:myproject" exited with code 1.

Which is not user-friendly.

Furthermore, such a mising message is not recognized by TeamCity and is not shown in the Visual Studio Error Window. I mean Visual Studio Profesional 2017 not Visual Studio Code.

It is blocking our continuous integration process because email messages we receive about "process exited with code 1" tells you nothing unless you analyzed a build log which is quite large.

**TypeScript Version:**  3.4.0-dev.201xxxxx

TypeScript Version: 3.5.3

**Search Terms:**
"does not contains", "MSBuild", "MSBuild Error"

**Code**

import { func1, func2} from './convert';

Note that the func2 is missing in the imported file.

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

The expected behavior is that compiler will format error message in the standard way **including string "Error"** so MSBuild and Visual Studio can recognize it.

Please check the following resources and follow GNU Coding standard standards **or at least add please string "error" to the message**.

Following GNU Coding standard standards is a sugar that you allow to skip to the file and line, but having the string "ERROR" is here really important.

https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/
https://stackoverflow.com/questions/42955711/showing-errors-from-a-build-time-tool-with-source-file-line
https://stackoverflow.com/questions/48117302/does-the-msbuild-exec-task-search-stdout-for-the-string-error

**Actual behavior:**

The compiler message is 

197>./src/components/Wizards/UserWizard/EditUserWizard.tsx
197>1:1325-1340 './convert' does not contain an export named 'func2'.

**Playground Link:** 

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/14482
https://github.com/microsoft/TypeScript/issues/14183
https://github.com/microsoft/TypeScript/issues/14211

Please, guys, you are all from Microsoft, talk to each other. Microsoft was always able to deliver a compatible ecosystem.

**Comment by RyanCavanaugh** [comment]
Our error messages don't individually say "error" in front of them (the console outputter adds this automatically), so there's no reason that only one individual message would have this problem.

When I run a similar setup locally:
```ts
D:\Throwaway>tsc b.ts
b.ts:1:10 - error TS2305: Module '"../Throwaway/a"' has no exported member 'q'.
```

Can you provide a repo or zip file that demonstrates the problem in a more isolated way?
