### ISSUE TITLE
Class with Generics declare in function`s parameter,and renturn unknown

### ISSUE THREAD

**Issue by wszgrcy** [microsoft/TypeScript#32635]
**TypeScript Version:**  3.5.2

**Search Terms:T extends Generics <D> property type is unknown

**Code**

```ts
export class Config<T> {
    constructor(
        public classType?: Type<T>
    ) {
    }
}
export class SubClass {
    test: string = 'print out'
}
export class SubConfig extends Config<SubClass>{
    classType = SubClass
}
interface Type<T> {
    new(...args: any[]): T;
}
function f1<D, T extends Config<D>>(val: T) {
    return val
}
function f2<D, T extends Config<D>>(val: T) {
    return val.classType
}
/**
 * when `f1` return val,and classType=>SubClass
 * but `f2` return  val.config.classType and classType=>unknown
 * I want to use `f2` and also return `SubClass`
 * How to Change Code?
 * Or like a bug?
 */
let a = f1(new SubConfig())
let classA = new a.classType()
/**ok */
console.log(classA.test)
let b = f2(new SubConfig())
let classB = new b()
/**error */
// console.log(classB.test)
```

**Expected behavior:**
f2 return type is SubClass
**Actual behavior:**
f2 return type is unknown
**Playground Link:**

**Related Issues:**

**Comment by jack-williams** [comment]
Better to try stackoverflow first, unless you think there is a bug here.

```ts
function f2<T>(val: Config<T>) {
    return val.classType
}

let b = f2(new SubConfig())
let classB = new b!()
```

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; see above comment for solution

**Comment by wszgrcy** [comment]
> Better to try stackoverflow first, unless you think there is a bug here.
> 
> ```ts
> function f2<T>(val: Config<T>) {
>     return val.classType
> }
> 
> let b = f2(new SubConfig())
> let classB = new b!()
> ```

thanks!
Although  I don`t known declare more detail but get unknown,reverse,without extends and have return a right type.
