### ISSUE TITLE
Allow `undefined` type for `isNaN`

### ISSUE THREAD

**Issue by icl7126** [microsoft/TypeScript#32637]
## Search Terms
is:issue isNaN undefined 

## Suggestion

**First of all - I've seen those other similar issues and I totally agree this should not allowed for all types.** 
But having it for `undefined` feels like a common use case.
I mean, what other use case is there if I can call it wit numbers only? All numbers are numbers, right?

## Use Cases

I have a function that returns id of frame found on a page - if there is one - so the return type is `number | undefined`.
Using `isNaN` is a good way to check the returned value (which can be 0, which is still OK).
_(as a workaround I will use Option monad which is probably much better solution, but still this would be nice to have)_

## Examples

```
const x: number | undefined = Math.random() > 0.5 ? 0 : undefined;
const notNumber: boolean = isNaN(x);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [?] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment]
> I mean, what other use case is there if I can call it wit numbers only? All numbers are numbers, right?

Guess you haven't seen this before?

```js
var a = 0 / 0;
typeof a; // "number"
isNaN(a); // true
```

Detecting [NaN](https://en.wikipedia.org/wiki/NaN) is what `isNaN` is typically used for

**Comment by icl7126** [comment]
@nmain good point. I should have checked the the docs before posting:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN
>The isNaN() function determines whether a value is NaN or not.
