### ISSUE TITLE
Use `self` instead of `this` for compatibility reasons

### ISSUE THREAD

**Issue by SonofNun15** [Microsoft/TypeScript#3264]
One of our biggest pain points in implementing typescript has been the fact that TypeScript redefines `this` to point to the class for lambdas. This is especially complicated when interacting with external libraries that require callback functions. Now every member of our team must understand the differences between lambdas and anonymous functions and how they handle `this`. It's a big headache.

I feel like it would be much simpler if TypeScript declared a new keyword and assigned `this` to it in the constructor so you could be certain that `self` (or `instance` or whatever) always referred to the class instance instead of the ambiguity of JS's `this`. This is a very common pattern in JS: Save `this` to a local variable at the top of a component and referencing this stable `this` later to avoid any potential ambiguity.

**Comment by ahejlsberg** [comment]
It is definitely not feasible for TypeScript to implement different semantics for classes than ECMAScript 6. My rule of thumb for callbacks is actually pretty simple: Always use lambdas for callbacks, and never use class methods or function expressions. That way you never have to worry about having the correct `this`.

**Comment by SonofNun15** [comment]
Thanks for the response! I'll take a closer look at ES6 classes. I haven't really examined the details of how things like `this` will be handled in ES6. Obviously that will have far reaching ramifications on this issue, particularly since TypeScript is moving to encompass ES6 in the near future.

**Comment by SonofNun15** [comment]
Also, did not realize that preserving `this` for lambdas is also a feature in ES6, so at least this is standard behavior: https://github.com/lukehoban/es6features#arrows
