### ISSUE TITLE
Type predicated should eliminate execution path

### ISSUE THREAD

**Issue by ycmjason** [microsoft/TypeScript#32648]
**TypeScript Version:**  3.5.1

**Search Terms:**
- type predicate
- path
- eliminate

**Code**

```ts
type Awesome = 'i' | 'am' | 'awesome'

const isActuallyAwesome = (x: Awesome): x is 'awesome' => x === 'awesome'

const isNotReallyAwesome = (x: Awesome): x is 'i' | 'am' => x !== 'awesome'


const happyFunction = (a: Awesome): number => {
    if (isActuallyAwesome(a)) {
        return 0
    }

    if (isNotReallyAwesome(a)) {
        // typescript not be able to infer `isNotReallyAwesome(a)` always evaluates to true at this point?
        return 1
    }

    throw 'i need to throw :('
}
```

**Expected behavior:**
`isNotReallyAwesome` has type signature: `(x: Awesome) => x is 'i' | 'am'`. Shouldn't TS be able to tell when `x` is passed in as `'i' | 'am'` and therefore infer that it will always return true?

I hope this make sense.

**Actual behavior:**

**Playground Link:** 

https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAgg7hAzgewLbQLxQOQEttQA+OAhqgcdiQiutgFD0DGyAdosFLojE8AK4kANkJDwkaTFAAUADwBcsGpICUi2V0SlldKBgB8UDRhPaJdRi3aduAOWTAAShGGjxtKXMXvV6zTnwiUnI9Qw0AQlMqHQgGSzYOKAALEjAwEAAxflY+XDY9GRJvGLUoVn5UACMIACdQqABveigWrgAzGW5eAVcxGOkSFRVG5taxmogBGtYoAAZRloBfRjHcDuk7B2den3QBoZGxsYB6Y6gWfiEAEyhQSEQmGtwwTmqoEkqhaGBkLlY22qaexOFwiPrmCD7d5COAkEBaCAAN2EgmASFuv2ANX40BInGASW4UDAyFwrGAAH4FkcJlMZgBGanLakEmrIOABMoQCA3H63JJsjnyaQMZlAA

**Comment by jack-williams** [comment]
TypeScript _does_ infer that the conditional is always true.
```ts
const happyFunction = (a: Awesome): number => {
    if (isActuallyAwesome(a)) {
        return 0
    }

    if (isNotReallyAwesome(a)) {
        return 1
    }

    const whenAmIReachable: never = a
    return a;
}
```

**Comment by ycmjason** [comment]
i didn't mean code elimination in the compiled code.

I mean that typescript should be able to infer that whatever after the second conditional is dead code. 

I should not need to write `    throw 'i need to throw :('`

**Comment by ycmjason** [comment]
Let me give another example:

```ts
const coolFunction = (): number => {
    if (true) {
         return 1
    } 

     // typescript won't complain about the return type should be `number | undefined`
}
```

so shouldn't the my example have the same behaviour?

**Comment by jack-williams** [comment]
This issue explains why the literal `true` is treated differently: #29323.

**Comment by jack-williams** [comment]
Also covered here: #17358.

**Comment by ycmjason** [comment]
thanks @jack-williams !
