### ISSUE TITLE
Getter (with setter) that doesn't return on all paths doesn't have a correct error span

### ISSUE THREAD

**Issue by stevenfowler16** [microsoft/TypeScript#32642]
**TypeScript Version:** 3.5.2

**Search Terms:** 
ts2366
**Code**

```ts
export default class InputRadioButtonsWebComponent extends HTMLElement {
    private MapRadioButton: Map < HTMLInputElement, HTMLButtonElement > = new Map < HTMLInputElement, HTMLButtonElement > ();

    get Value() {
        for (const entry of this.MapRadioButton.entries()) {
            if (entry[0].checked === true) {
                return entry[0].value;
            }
        }

    }

    set Value(value: string) {
        if (value !== null) {
            this.setAttribute('value', value.toString());
        }
    }

}


let customElements = window.customElements;
if (customElements.get('radio-buttons') === undefined) {
    customElements.define('radio-buttons', InputRadioButtonsWebComponent);
}
```

**Expected behavior:**
Throw the error during the build process with the file and line specified.  

**Actual behavior:**
Function lacks ending return statement and return type does not include undefined is thrown at the bottom of the file. The build provides zero idea as to where the error could have come from.
Looks like ESLint only runs on open files which was one reason why finding the file was so difficult.   
**Playground Link:**  
https://www.typescriptlang.org/play/#code/FAUwHgDg9gTgLgAgCYgGYEMCuAbRBjbdAZyIQEkA7CTOAJXSQEsoAhGuKCogdRACMAwlAC20CiAqJwcCUlIAJACoBZADIBRbCGETEAb2AIjCCDEYA3dDITL0Eek1btOALht2APErWVqcTdq6ADQI3qpscBwUATqSAHwIALwI4gDu7hBeKqq+NDHBodkRUfnxABQAlADchsa1RgDmIIgAaujYmCCVCAYAkL2osAhleJxEUpIwAJ4IUKgIcAAWjEQAdLb2DMzFnKu6ZiBElRU9wP29jPNl+1MA2gAMALqreIsgeADWIEhJiclwME6Jz65xgzUwMAoCBuD2elg6IBqxmRKIAvuczr1UWdsWciM0EG0EWV4Z03OMzBQGsDMZdhqSQAgAIR-FI4bA085LFarfFwACCkTMfBoXQA5AyxSEGasOABlAGMKnHGr9bFY3rAYC44BafCYcYiUpwUjJVJKpBQVIvA0cYTGog1OkjW1GrSxE2rJpwMpimBbKAAWhFkTGYpOf2SmAoKFQSu+nLwrvt7t0a1j8d9-scwecXCl5CoNAc2zzPH4QlEnF01W1wCAA
**Related Issues:**
91

**Comment by RyanCavanaugh** [comment]
Shorter version
```ts
class A {
	get Value() {
		if (Math.random() > 0.5) {
  		return 0
		}
	}

	set Value(value: number) {
	}
}
```

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh 

If there is _return type_ TS refers to it, like this
![current](https://user-images.githubusercontent.com/509265/69413414-71a1e400-0d19-11ea-8d56-002de910ddfc.png)

What is the acceptable fix for the case if a method doesn't have a return type?

1. Highlight method's body
![body](https://user-images.githubusercontent.com/509265/69413693-fab91b00-0d19-11ea-963e-3857422324a3.png)
2. Highlight method's name
![name](https://user-images.githubusercontent.com/509265/69413694-fb51b180-0d19-11ea-81e6-69cd3c007871.png)

**Comment by MartinJohns** [comment]
If a method returns nothing, then it implicitly returns `undefined`. So the correct type would be `number | undefined`.

If you have the compiler option `noImplicitReturns` enabled, then you additionally need to explicitly return `undefined`.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
