### ISSUE TITLE
Conditional Type Not Propogating Correctly in Nested Function Call

### ISSUE THREAD

**Issue by DBTaylor** [microsoft/TypeScript#32644]
I'm prototyping a pipeline function that would behave like a pipeline operator. Below is a 2 or 3 arity example, but the idea is have optionally high arity to make useful pipelines. The problem is I don't get type errors when I would expect them even on the 2 or 3 arity version.

**Search Terms: Conditional Type Propogation**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
function pipe<A, B, C>( //takes a value to pipe in and at least one function to make a pipeline
    a: A,
    ab: (a: A) => B, 
    bc?: (b: B) => C
):
unknown extends C ? B : C {
    const b = ab(a)
    if(bc){
        return bc(b) as any
    }
    else
        return b as any
}

const x = pipe(
    '',
    _ => true
)

const y = pipe(
    '',
    _ => true,
    _ => 0
)

const add2 = (x: number) => x + 2

add2(x) //correctly errors: "Argument of type 'boolean' is not assignable to parameter of type 'number'"
add2(y) //no error
add2(pipe(
        '',
        _ => true
)) //also no type error. I expect: "Argument of type 'boolean' is not assignable to parameter of type 'number'"
```

**Expected behavior: that pipe call nested in add2 would be a type error**

**Actual behavior: the pipe call nested in in add2 is not a type error**

**Playground Link: https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABABxsgpgHgIIBpEBC+AwgHwAUiA9FVAIYDW6AzonYgG50A2I6iUOCjT8YSOmAAmbKIm7o6zWQn6hIsBAKEBbRv3aoM3MegBQiC2wBciPOct0ARjfJ0b2AJSIAvKUL57C0cIAH4XZ0IvX0RiUw8rU3AGMDgAdyR0AA8odClWYkQQwkQbAoBvQMQIBCVERx82R1cPSphgcmCPCssexAAndCgQPqRgjq9FNjAAT0qAX0r0bmYzXssBoZG6tlYJWYXTarBazIbDdHJKgHIr3EqAfR8-KD6+ONNDmtlps5FLnpudx6j2iLz4QMsIL8AAZ3p9jrI6JJJAAmBrkTI2MAgbSOdB9KJ+U4AakQKI+SNRGK8NGqfQG0G4P3xfTgfWYNgARNg+gBzHG5ZTAATTDCIK6OOBweQSK6IGCsFKI5jMGC8sBOeRaFB0Pp0bSDfGIODCqCi-hXbG4-FXTmmSko8jTGlUFKIFls+3Ix3nf5rcW3SrAp4CV5mDwunjMIRus1ij19AB0iAAku7MhhoFyefyDWAhSKxRKpTKwHKFYglTtVerNfxBDq9Qacn1jabzeKrXi+ragA
**

**Comment by jack-williams** [comment]
The behaviour that is occurring here is that the call to `add2` is contextually typing `pipe`, causing TypeScript to infer `number` for `C`.

The approach of relying on an inference failure (by inferring `unknown`) is probably not the most robust way to detect that the last function is missing. In particular, it can be unsound.
```ts
const returnTrue: () => boolean = () => true;
const returnNumber: () => unknown = () => 0;
const a: boolean = pipe('', returnTrue, returnNumber); // no error
```

I think using an overload may be better here:
```ts
function pipe<A, B>(a: A, ab: (a: A) => B): B;
function pipe<A, B, C>(a: A, ab: (a: A) => B, bc: (b: B) => C): C;
function pipe<A, B, C>(a: A, ab: (a: A) => B, bc?: (b: B) => C): B | C {
    const b = ab(a)
    if(bc){
        return bc(b) as any
    }
    else
        return b as any
}
```

**Comment by DBTaylor** [comment]
Ah I didn't know you could overload with different numbers of arguments. Thanks! I assume the inference can happen because nothing specifies C?

**Comment by jack-williams** [comment]
> I assume the inference can happen because nothing specifies C?

Not sure I follow this question fully: are you referring to your example?
