### ISSUE TITLE
Conditional type mistakenly turns union type into an intersection

### ISSUE THREAD

**Issue by Torvin** [microsoft/TypeScript#32645]
**TypeScript Version:**  3.6.0-dev.20190730

**Search Terms:** conditional type union function intersection 

**Code**
```ts
type Func<T> = (arg: T) => void
type AnotherFunc<T> = T extends void ? () => void : Func<T>
type MyFunc = AnotherFunc<string | number>
```

**Expected behavior:**
The resulting type of `MyFunc` should be `(arg: string | number) => void`

**Actual behavior:**
Instead the resulting type of `MyFunc` is `(arg: string & number) => void`

This doesn't happen if I don't use a conditional type. I.e. this works fine:
```ts
type Func<T> = (arg: T) => void
type MyFunc = Func<string | number>
```

**Playground Link:** 
https://www.typescriptlang.org/play/#code/C4TwDgpgBAYgrgOwMYB4AqA+KBeKAKAQwCcBzALijQEocsA3AewEsATAWAChRIoBBBBsAAWEIvGTosuNFAgAPYBAQsAzlEasoAfnw1s9ZiygVxqTJ04B6S1ABmTBBE63ESYEwYIoilcACMeLYIJq4ovkQOJFAAPlAIcAC2AEaiGDQA3pxQdgh4flScAL4WHNayREQMRM6u7p7eEL4ATIHBfALCoqZhwBEIUbHxyakZWTl5BRzFHEA

**Related Issues:**
nope

**Comment by AnyhowStep** [comment]
Conditional types distribute over union. This is intended behavior.

+ `string extends void` is false. So you get `(string) => void`
+ `number extends void` is false. So you get `(number) => void`

The end result is `((string) => void)|((number) => void)`

The only way to invoke this type, without knowing which of the two functions it is, is by passing an Arg of type `string & number`

-----

Use this instead,

```ts
type AnotherFunc<T> = [T] extends [void] ? () => void : Func<T>
```

The [T] is a tuple of one element. It prevents distribution

**Comment by Torvin** [comment]
@AnyhowStep Thank you for the workaround and for the explanation (it makes sense)! 

But are you saying we should close this as non-bug? To me the end result still looks wrong.

**Comment by RyanCavanaugh** [comment]
Conditional type distributivity is surprising ~30% of the time. Not much can be done about that.
