### ISSUE TITLE
Keep comments in the interface even there is no code generated

### ISSUE THREAD

**Issue by ksimple** [Microsoft/TypeScript#3265]
I found that my comments in interface is stripped out even I use -c option. It makes some issue when I use jsdoc to generate the document from the generated js file. All the interface doc is missing.

**Comment by RyanCavanaugh** [comment]
This is intentional. In most cases, having floating comments not attached to anything is confusing rather than helpful.

**Comment by danquirk** [comment]
The interfaces themselves are missing, as a result, so are their docs (as Ryan explained). If you want JSDoc comments generated for interfaces you'll probably need to find a tool that works over the TypeScript code directly rather than the JS, or else augment your JS based output yourself.

**Comment by ksimple** [comment]
Yes, it is the ideal case. But there is no jsdoc support for typescript now, and it seems that I can't get in a short term.

I can find the workaround to add the jsdoc related comments right after the interface declaration. But I still think it is wired that the comment before the interface is stripped out even I add empty line to separate them. It seems there is some implicit rule of -c argument. and it works not in the most straightforward way to just keep the comment.
