### ISSUE TITLE
Function/Variable selector gets expanded and can't be shortened back down

### ISSUE THREAD

**Issue by WaldemarH** [microsoft/TypeScript#32650]
Hi guys

After many many years (since probably 1.0) I've noticed this bug and hoped that it will get fixed in time, but unfortunately it's still here.

Anyway if you watch the video
https://1drv.ms/v/s!AulAg7BeKIMXgqNP_uScCUZliHBF4Q?e=dnsIMO
you will see that as soon as I edit the string the function/variable/... selector gets expanded (I assume to account for some html code or something???), but even if you select something else the window doesn't shrink back down. So the only way to shrink is to close and reopen the file again.

**Expected behavior:**
That the window doesn't get expanded in the first place. With all the languages I write in VS TypeScript is the only one that is causing this issue.

**Actual behavior:**
Selector window gets invalid height.

BrW

**Comment by RyanCavanaugh** [comment]
Looks very annoying, but I can't tell from the video what the code is, so can't figure out how to reproduce it locally. Can you post some code *as text*, or at least as a screenshot, that we could use as a basis for testing out a potential fix?

Thanks!

**Comment by WaldemarH** [comment]
Hi Ryan

Try to download the video it should be in full hd (online version is sometimes displayed in lower resolution)... if it's still not visible, we can talk locally and I can show you live (skype, teamviewer,...).

BrW

**Comment by RyanCavanaugh** [comment]
We can't spend all day transcribing code snippets from video freezeframes. If you're unable to provide a text-based example, then this report isn't something that can be taken as actionable.

**Comment by WaldemarH** [comment]
Hi Ryan

You don't have to be angry or anything as same as you I'm a programmer. And the first thing is that we are in service for other people.. that is what we do and that is how we earn our living.
And just for a side note I'm a programmer for 30+ years and one thing I know is that we have to have patience.
Now I've seen a lot of bad bug reports in my life to the extend that all I've got is "GUI doesn't work" where just the GUI alone had a million of lines.
Also from my experience seeing a video is 100 times better then seeing an image.
And as the issue is triggered in every class, just constructing a simple string in a similar form as on the video would trigger the bug.
Now to make your life easier here is a simple ts file that triggers the issue (at least on my VS2017.. it did on all the previous versions too and I assume it will in VS2019 too as it's a TS bug).

https://1drv.ms/u/s!AulAg7BeKIMXgqQ5z1b_kHAV9NEgfg?e=g8qP2L

The bug is as simple as opening the ts file and clicking on the right spot (described inside the ts file).

Now for a side note on how to get better, specially as you want to be a lead, is to read a small book named "How to win friends and influence people.". I've seen many arrogant leads that didn't come anywhere in life and have seen many normal programmers that became very successful professionals or managers... maybe on your side the perfect example would be Satya. And I can say 100% that he didn't come to the CEO position being arrogant and inpatient.

So peace and love as we are all trying to help other people and this is where the good feelings in life come from.

Best regards
Waldemar

**Comment by RyanCavanaugh** [comment]
```ts
namespace Privendo.Menu
{
//Enums
	namespace Enum_Filter_Command
	{
		export const enum Value
		{
			Cameras,
			Company,
			Connects,

			PinUnpin
		}
	}

	export class Test
	{
	//To trigger the bug: click with mouse on the right ' of the lower right + '" >''</span>\ section
	//                                                                              ▲
	//                                                                              click here on the lower right text



		private static		m_Page_Element_html =
			'<div id="CMenu_Base">\
				<div data-role="filter" >\
					<div>\
						<span data-filter-command="' + Enum_Filter_Command.Value.Company + '">{51460} Companies</span><input type="checkbox" name="companies" >|\
						<span data-filter-command="' + Enum_Filter_Command.Value.Connects + '">{51461} Connects</span><input type="checkbox" name="connects" >|\
						<span data-filter-command="' + Enum_Filter_Command.Value.Cameras + '">{51462} Cameras</span><input type="checkbox" name="cameras" >\
					</div>\
					<div>\
						<span data-filter-command="' + Enum_Filter_Command.Value.PinUnpin + '" >''</span>\
					</div>\
				</div>\
				<div data-role="tree" >\
					<ul>\
					</ul>\
				</div>\
			</div>';
	}
}
```

**Comment by WaldemarH** [comment]
Thanks Ryan for reopening the ticket.

Best regards
Waldemar
