### ISSUE TITLE
Property 'getDisplayMedia' does not exist on type 'MediaDevices' 

### ISSUE THREAD

**Issue by VaralakshmiP** [microsoft/TypeScript#32654]
I'm facing the above issue while compiling the angular project, but working fine in browser.
getDisplayMedia is not defined  in MediaDevices interface in lib.dom.t.ts
Adding :   'getDisplayMedia(constraints: MediaStreamConstraints): Promise<MediaStream>;'  in interface MediaDevices in lib.dom.t.ts fixed the issue.
Is the typescript module need to be updated?

**Comment by j-oliveras** [comment]
DOM types are generated from [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) repository. But I think that draft APIs are not included.

Link to [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#Specifications).
