### ISSUE TITLE
./.vscode > tasks.json contains deprecated API tasks.identifier

### ISSUE THREAD

**Issue by nataliemarleny** [microsoft/TypeScript#32665]
**TypeScript Version:**  3.6.0

**Search Terms:**
vscode, tasks.json, tasks, identifier

**Code**
`./.vscode` > `tasks.json` contains deprecated API `tasks.identifier`.

```js
    "tasks": [
        {
            "type": "shell",
            "identifier": "local", // deprecated
            "label": "gulp: local",
            "command": "gulp",
            "args": ["local"],
            "group": { "kind": "build", "isDefault": true },
            "problemMatcher": ["$gulp-tsc"]
        },
```
Note: `tasks.identifier` in `tasks.json` was introduced: 41567b2261 - Migrate tscWatchMode to vfs

**Expected behavior:**

`tasks.identifier` should not be present in `tasks.json`

Reference: https://github.com/microsoft/vscode/issues/57946
Further discussion see thread containing: https://github.com/Microsoft/vscode/issues/57707#issuecomment-418657645 
Schema for tasks.json: https://code.visualstudio.com/docs/editor/tasks-appendix

**Actual behavior:**
VSCode shows a warning for the `identifier` field

**_Suggested solution_** 

_Either:_
- Remove identifier as a parameter, (functionality is covered by label) 

_or_
- Remove `./.vscode` > `tasks.json` if configured tasks no longer needed
- Remove `.gitignore` reference: https://github.com/microsoft/TypeScript/blob/90afd6d620f30bc47e862970a931ca0e207e6b28/.gitignore#L62

_or_
- There was mention in the github issues thread on discussion of deprecation of `tasks.identifier` to update tasks API to new supported feature: `TaskDefinitions` in `package.json`: https://code.visualstudio.com/api/references/contribution-points#contributes.taskDefinitions

**Playground Link:** 
Not applicable

**Related Issues:** 
None found

**Comment by jakebailey** [comment]
This is an old issue, but this was fixed in #35282.
