### ISSUE TITLE
Cannot export { ... } interface when --isolatedModules is passed

### ISSUE THREAD

**Issue by rickbutton** [microsoft/TypeScript#32662]
**TypeScript Version:**  3.5.3

**Search Terms:** isolatedModules re-export

**Code**

```ts
interface MyInterface {}
export {
    MyInterface
}
```

**Expected behavior:**

This should compile regardless of whether `--isolatedModules` is passed.

**OR** the error message could indicate that this is not an accepted way to export an interface in an isolated module. (https://github.com/Microsoft/TypeScript/issues/28481)

**Actual behavior:**

This fails to compile with the error message: 
```
Cannot re-export a type when the '--isolatedModules' flag is provided.ts(1205)
```

when `--isolatedModules` is passed.

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/28481

**Comment by RyanCavanaugh** [comment]
The error message is slightly off; it should say `export` not `re-export`

**Comment by rickbutton** [comment]
As in `Cannot export a type when the '--isolatedModules' flag is provided.ts(1205)`?

I agree, that would make the error message more clear, but is it strictly true? You can safely export the interface inline regardless of the `--isolatedModules` flag, e.g.:

```
export interface MyInterface {}
```

which using `export` instead of `re-export` implies is not possible.

**Comment by DanielRosenwasser** [comment]
Error: A type cannot be exported in an 'export {...}' list under the '--isolatedModules' flag. 

Related error message on the original declaration: Consider adding an 'export' keyword here instead..

**Comment by mheiber** [comment]
@rickbutton , Ryan Cavanaugh pointed out that babel-plugin-typescript chokes on `export { Foo }` because it can't tell if the type originated in the current module or not.
So we do want an error message here, but likely a different one, like the one Daniel suggested ^.

**Comment by rickbutton** [comment]
makes sense to me! I will gladly submit a PR to update the error message, if the error message is agreed upon.

**Comment by robpalme** [comment]
This looks like a plain bug: the one-liner works but the equivalent two-liner does not.

```typescript
export interface MyInterface {}  // one-liner succeeds
```

```typescript
interface MyInterface {}; export { MyInterface }  // two-liner fails - how odd!
```

**Comment by vytautas-pranskunas-** [comment]
But how then we should export interfaces?

**Comment by DanielRosenwasser** [comment]
TypeScript 3.8+ will provide `export type` which is specifically for cases where you need to use an `export { ... }` statement with an interface declaration.

**Comment by DanielRosenwasser** [comment]
The current error message was changed to

```
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
```

so I think this is fixed.

**Comment by mheiber** [comment]
fwiw, I love this solution

**Comment by rickbutton** [comment]
yep, fixed!

**Comment by jankoboz** [comment]
Well i had the same issue but after i have noticed i forgot to put .d.ts extension.
