### ISSUE TITLE
Function arg of narrowed type shouldn't be compatible with Any type

### ISSUE THREAD

**Issue by IlyaKhD** [microsoft/TypeScript#32660]
**TypeScript Version:**  3.6.0-dev.20190801

**Search Terms:** Any, Type

**Code**

```ts
type Callback = (arg: any) => void

function Func(callback: Callback): void {
  // callback is expected to be called with argument of any type
  callback({ type: "smthComplex", value: "literal"});
}

const MyCallback : Callback = function(arg: number) { // no compile-time error?
  // unable to handle other types except for number
}

Func(MyCallback); // no compile-time error?
```

**Expected behavior:**
Compile-time error like  `Argument of type '(arg: number) => void' is not assignable to parameter of type 'Callback'.`

**Actual behavior:**
No error

**Comment by AnyhowStep** [comment]
You shouldn't think of `any` as the widest possible type. Think of it as the turn-off-type-checking type.

I'm not on my computer now but what happens when you turn on `strictFunctionTypes` and change `any` to `unknown`?

**Comment by IlyaKhD** [comment]
Yep, using `unknown` along with `strictFunctionTypes` turned on provides the type-checking I've talked about.
Thanks!
