### ISSUE TITLE
Type inference for generic type parameters of function

### ISSUE THREAD

**Issue by alexxxxOG** [microsoft/TypeScript#32678]
**TypeScript Version:**  3.5.1

**Search Terms:** Type inference

**Code**

```ts
interface Tree<T> {
    children: T[]
}

interface OrangeTree extends Tree<OrangeTree> {
  orange: string;
}

interface Bag {
  list: OrangeTree[]
}


function test<K extends { list: T[] }, T extends Tree<T>>(
    bag: K,
  ): K {
    return bag;
  }

  const bag: Bag = {
      list: [{
          orange: 'orange',
          children: []
      }]
  }

test(bag)
```

**Expected behavior:** 
```ts 
test(bag)
``` 
should have inferred type of

```ts  
<Bag, Tree<OrangeTree>>
```

**Actual behavior:** We get `<Bag, Tree<unknown>>`

**Playground Link:** https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCpQhAPKgfMgbwChlTkEALYAGwBMMQAuNAbQF0iBfIo0SWRCgDyUOCADmEdJmQQAHpBC0AzmgzYRYydIj5ipAPaiJEZsrBRQ4gNxcefaPCTIAQnHGESyasHPNNJjrsdjwwAK4gCGDABiDIkOZYANKyChBKqgTevmDMqOzInAA0aKmKKmqYOLi4ABRepABG7sxJRV4AlK2eZMgYYGFQcc02XtxeCLHmyCPMbh4AvD292X7ILPorvUZapsgA5Dsm++1bvZQ09OnMwVucHKTjCWC1Ix08Hx9AA

**Related Issues:** It is difficult to understand the limitations of the type inference related to generics.

The greatest and most entertaining type system I've used!

**Comment by RyanCavanaugh** [comment]
The constraints of type parameters don't serve as inference sites for other type parameters, so there's nothing to infer `T` from because there is no value of type `T` to form an inference for.
