### ISSUE TITLE
Assign named imports into namespace (alias)

### ISSUE THREAD

**Issue by trubit** [microsoft/TypeScript#32670]
## Suggestion

Allow aliasing a whole import statement into temporal namespace.

## Use Cases

Its now possible to do:

```typescript
import * as _ from 'lodash';
```
But that is not effective and not treeshakable, meaning we really import ALL lodash functions.

In case we want just some functions to save bundle size, we just need pick few.
But then we run into name collisions while importing members of diffrent modules.

```typescript
import { foo, bar } as alias from 'module';
```

```typescript
import { map, filter } as _ from 'lodash';
import { map, filter } as $ from 'rxjs';

$.map()
_.map();
```

## Examples

When using alias import for all member of module, final code in some cases may be more readable.

**Error and I really dont know which function is which**
```typescript
import { merge, map, filter } from 'rxjs';
import { isEqual, filter } from 'lodash'; // Throws error on name filter

merge([control.valueChanges, this.update$])
.pipe(
  map(data => filter(data, { isCool: false })),
  filter(isEqual)
)
.subscribe();
```

**So cool**
```typescript
import { merge, map, filter } as $ from 'rxjs';
import { isEqual, filter } as _ from 'lodash';

$.merge([control.valueChanges, this.update$])
.pipe(
  $.map(data => _.filter(data, { isCool: true })),
  $.filter(_.isEqual)
)
.subscribe();
```

I'm propably not first who thought about it but I couldn't find any discussion around this feature.
Is there any plan for this? Or am I missing something?

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
This would be new `non-ECMAScript syntax with JavaScript output`. This would require a proposal to [TC39](https://github.com/tc39) to advance to stage 3 before it would be considered for TS implementation.
