### ISSUE TITLE
Autocompletion doesn't suggest global variables exposed from dependent packages  (regression)

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#32675]
Hiding global variables from autocomplition is very annoying because other candidates make unnecessary import statements (We can't use autocompletion without making them).

**Search Terms:**

**Code**

1. clone https://github.com/falsandtru/spica
1. run `npm i`
1. open index.ts
1. type `asse`
1. suggests 2 candidates of `assert` but doesn't include global one.

Global `assert` is defined here: https://github.com/falsandtru/spica/blob/master/global.test.d.ts#L6

**Expected behavior:**

Suggests global assert and packaged assert.

**Actual behavior:**

Suggests packaged assert twice.

**Playground Link:** 

**Related Issues:**

**Comment by falsandtru** [comment]
This bug make user experience obviously worse. This must be fixed before being distributed by the next stable release 3.6.

**Comment by falsandtru** [comment]
@orta Can you fix? This bug is very stressful.

**Comment by orta** [comment]
You're welcome to take a look at fixing it @falsandtru - otherwise I will get to it for 3.7.0

**Comment by falsandtru** [comment]
I think this problem will appear on many projects and prevent their development if you distribute this bug via 3.6; 3.7 is too late.

**Comment by orta** [comment]
I think this is fixed in 3.7 by @andrewbranch with https://github.com/microsoft/TypeScript/pull/32517

**Comment by andrewbranch** [comment]
It looks like this is a bug specific to redeclaring a module as a global.

**Comment by orta** [comment]
Looks like it's the `export as namespace assert;` in `power-assert` which triggers this.

I've been struggling to get a repro in a fourslash test though, but I do have a minimal repro environment which should be:

```ts
// @Filename: /myAssert.d.ts
////declare function assert(value:any, message?:string):void;
////export = assert;
////export as namespace assert;

// @Filename: /ambient.d.ts
////import assert from './myAssert';
////
////type Assert = typeof assert;
////
////declare global {
////  const assert: Assert;
////}

// @Filename: /index.ts
/////// <reference path="./ambient.d.ts" />
////asser/**/;
```

**Comment by andrewbranch** [comment]
@orta make sure you set `// @esModuleInterop: true`, `// @target: esnext`, and pass `preferences: { includeCompletionsForModuleExports: true, includeInsertTextCompletions: true }` to the verify call.
