### ISSUE TITLE
Feature proposal: Async await forEach (emission of) observable syntax

### ISSUE THREAD

**Issue by ShacharHarshuv** [microsoft/TypeScript#32685]
## Search Terms
async, await, Observables, RxJS, subscribe

## Suggestion

Async await was invented to sugar-syntax the following code:
`somePromise.then((return) => { /* some code */ } )`
Into something more readable:
```
const return = await somePromise;
/* some code */
```
Promises was originally a library by bluebird, and than made it into the native JavaScript spec.
Let's talk about another library that handles async operation: RxJS.
Consider the simplest code in RxJS:
```
someObservable$.subscribe(value => console.log('value emitted', value));
```
This is exactly the kind of callback syntax "await" was trying to make cleaner and easier to use. I suggest using the same idea of "await", but with a loop (like forEach). See examples below.
## Use Cases

When subscribing to observable, handling errors, onComplete, or subscribe. The Goal is to the avoid the callback syntax and create a more readable one.

## Examples

Simple example for a code with "awaitForEach":
```
awaitForEach value of someObservable$ {
  console.log('value emitted!', value);
}
```
Will be translated to:
```
someObservable$.subscribe(value => console.log('value emitted!', value))
```
Example with error handling and on-completion handling:
```
try {
  awaitForEach emitValue of someObservable$ {
    console.log('a value was emitted', value)
  }
}
catch (error) {
    console.error('a error was thrown, error)
}
console.log('completed')
```
will be translated to:
```
someObservable$.subscribe(
  (value) => console.log('a value was emitted', value),
  (error) => console.error('a error was thrown, error),
  () => console.log('completed')
)
```

You can also ease the agony of unsubscribing with "break":
```
  awaitForEach value of someObservable$ {
    if (!value) break;
  }
```
Which is equivalent to that:
```
  const subscription = someObservable$.subscribe((value) => {
    if (!value) subscription.unsubscribe();
  }
```
 
## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
> This isn't a runtime feature

This is a runtime feature and should be raised with TC39 - we're committed to not adding new statement forms like this.

**Comment by ShacharHarshuv** [comment]
@RyanCavanaugh 
How is this a run-time feature? The sugar-syntax should be converted to RxJS **before running**. This is compilation time feature.

**Comment by RyanCavanaugh** [comment]
I'm not sure what "runtime feature" would mean if not exactly that.

**Comment by ShacharHarshuv** [comment]
Runtime means something that runs while your app run (in the browser). Typescript is about preprocessing the code. I don't understand why is this not aligned with what TypeScript does. It's exactly like async await which started as a TypeScript feature.

**Comment by RyanCavanaugh** [comment]
async/await was a proposal started in TC39: https://github.com/tc39/ecmascript-asyncawait
