### ISSUE TITLE
Whitespace for open curly ('{') after close bracket (']') is removed in function return types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3269]
For instance, in the following example where we declare the return type as an array type, we go from

```TypeScript
function foo(): blah[] {/**/
```

to

```TypeScript
function foo(): blah[]{
/**/
```

Notice the lack of whitespace between the `blah[]` and the `{`.

**Comment by DickvdBrink** [comment]
Refs #2628 (duplicaten)

**Comment by DanielRosenwasser** [comment]
Thanks @DickvdBrink!
