### ISSUE TITLE
Missing generator's type parameter in functions and constructors

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#32696]
#32433 was supposed to fix this bug but actually wasn't as follows:

https://github.com/microsoft/TypeScript/pull/32433/files#diff-8076f45062b7486b33be2ed7ecf1ea5dR9

@rbuckton Please fix it again.

**TypeScript Version:**  3.4.0-dev.20190802

**Search Terms:**

**Code**

```ts
export class Coroutine<T = unknown, R = unknown, S = unknown> {
  constructor(gen: (this: Coroutine<T, R, S>) => Generator<R, T, S> | AsyncGenerator<R, T, S>) {
  }
}
new Coroutine<0, 0, 1>(async function* g() {
  yield 0;
  return 0;
});

export function f<T = unknown, R = unknown, S = unknown>(gen: () => Generator<R, T, S> | AsyncGenerator<R, T, S>) {
}
f<0, 0, 1>(async function* g() {
  yield 0;
  return 0;
});
```

**Expected behavior:**
Type g is AsyncGenerator<0, 0, 1>.

**Actual behavior:**
Type g is AsyncGenerator<0, 0, unknown>.

**Playground Link:** 

**Related Issues:**

**Comment by falsandtru** [comment]
@rbuckton Take a look?

**Comment by rbuckton** [comment]
While I do see that the `TNext` of `g` is `unknown`, I'm not seeing where the type of `a` is `any`.

**Comment by falsandtru** [comment]
> I'm not seeing where the type of a is any.

I should have updated it. I'll fix it.
