### ISSUE TITLE
Optional argument decorator parentheses

### ISSUE THREAD

**Issue by dsherret** [Microsoft/TypeScript#3270]
I've noticed an easy area to make a mistake in the language because of this [SO question](http://stackoverflow.com/q/30467906/188246). Take this example:

```typescript
class MyClass {
    @SetDefaultValue
    filePath: string;
}

var c = new MyClass();
console.log(c.filePath);

function SetDefaultValue(defaultValue = "Example") {
    return function (target: Object, propertyKey: string | symbol) {
        target[propertyKey] = defaultValue;
    };
}
```

This compiles fine; however, this will output `undefined`. To fix this, the developer needs to remember to add parentheses:

```typescript
class MyClass {
    @SetDefaultValue()
    filePath: string;
}
```

Now it will output `Example`.

This seems too sneaky to me. I can see this leading to incredibly annoying bugs in applications. Is there any way the compiler could get both ways to work or throw a compile error for one of them?

**Comment by mhegazy** [comment]
looks like a duplicate of #3246

**Comment by dsherret** [comment]
Yes, it is. Sorry, didn't find it in my searching.
