### ISSUE TITLE
Missing error for keywords with escaped characters

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#32700]
**TypeScript Version:**  3.6.0-dev.20190804

**Search Terms:**

**Code**

```ts
v\u0061r a = 1;
// parses as: 'var a = 1;'
```

**Expected behavior:**
`Keyword must not contain escaped characters`

**Actual behavior:**
No parse/compile error. Instead Chrome gives `Uncaught SyntaxError: Keyword must not contain escaped characters`

**Playground Link:**  doesn't use the correct version yet

**Related Issues:**
#32096 made parsing the above code possible. cc @weswigham

**Comment by weswigham** [comment]
Hah, neat. I guess we need a dedicated error for this now.

**Comment by RyanCavanaugh** [comment]
![image](https://user-images.githubusercontent.com/6685088/62481223-b142c100-b766-11e9-9717-aa07cd13f3ac.png)

😅

**Comment by weswigham** [comment]
So we apparently already had a test for this - `scannerUnicodeEscapeInKeyword1.ts` - which has existed _since the compiler was uploaded to github_. It just has the wrong behavior.
