### ISSUE TITLE
JSDoc of base class/interface appears many times when using union of derived class/interface

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#32708]
**TypeScript Version:**  3.5.1

**Search Terms:**

JSDoc, duplicate, extends, implements

**Code**

```ts
interface InterfaceFoo<DataT extends { name : string }> {
    /**
     * Some comment
     * 
     * -----
     */
    name : DataT["name"]
}

class ClassFoo<DataT extends { name : string }> implements InterfaceFoo<DataT> {
    name! : DataT["name"]
}

///////////////////////
declare const arr2 : readonly (
    | ClassFoo<{name:"X"}>
    | ClassFoo<{name:"Y"}>
)[];
/*
Expected:
Some comment

Actual:
Some comment
-----
Some comment
-----
*/
arr2[0].name

///////////////////////
declare const arr3 : readonly (
    | ClassFoo<{name:"X"}>
    | ClassFoo<{name:"Y"}>
    | ClassFoo<{name:"Z"}>
)[];

/*
Expected:
Some comment

Actual:
Some comment
-----
Some comment
-----
Some comment
-----
*/
arr3[0].name
```

**Expected behavior:**

`Some comment` should only appear once

**Actual behavior:**

`Some comment` appears `n` times if the array contains `ClassFoo<>` `n` times

**Playground Link:**

[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJLmvJAxA9rgHgBE4w4AVZCAD0hABMBnZAb2RDgFsUAuZRsFFABzZAF8AfKwBQyOcgD0AKiWz5yJcgDKubsgS7u4NfM0m5mgLTXr5jQvMc9fEmXIBtAEROIngLrSYtLSCAA2cIzMAMLhkXiErhRUtBAMzGw+yHwCQiCiksjAnAAOoRBGYMzokLCIEPHEpBRSLI5cEACEWciJHt7t-oHBCiOjY+MTI9L0EGFwUCgGIALI81AATN0LcPS4IKEAnsgAFOYAPsgxEYwNLD48ngAanpLnl7E3+AR37Q8Ami8JNIAJTuPwAbmkymkAFFqMVZpB6DxpDo9AZOBVggBBBBgACucFCKLRi0MqTA0hstlJ+nJxmplmkSgca3W7gADH4AHQ+YaTAWTaazcILOnLMCrKBQADMWwgOz2hxObyucS+P24D2er3UFzVn0Imog-0Bqo+t3ungAWmbQRDhqo4Qi8RBkajdGTMRScXjCcSPej6ZTGYGvVjQ7SMRHqczWdKZZyeT4gA)

**Related Issues:** 

No idea

**Comment by AnyhowStep** [comment]
![image](https://user-images.githubusercontent.com/5655961/62448085-eafad400-b734-11e9-8fbe-96ca834139d7.png)

[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJLmvJAxA9rgHgBE4w4AVZCAD0hABMBnZAb2RDgFsUAuZRsFFABzZAF8AfKwBQyOcgD0AKiWz5yJcgDKubsgS7u4NfM0m5mgLTXr5jQvMc9fEmXIBtAEROIngLrSYtLSCAA2cIzMAMLhkXiErhRUtBAMzGw+yHwCQiCiksjAnAAOoRBGYMzokLCIEPHEpBRSLI5cEACEWciJHt7t-oHBCiOjY+MTI9L0EGFwUCgGIALI81AAWt0LcPS4IKEAnsgAFOYAPsgxEYwNLD48nuuekueXsTf4BHftD08v6hcrnFPt9uL9nhJXkCPoRQRBwf95ID3rd7o8IVCUSC0X9IQC3tdUT90Yi5MjCdjibjMRTYTiMfjoUSwSS8UiCcC6VSGeymZSWdTGViuQKeWSOTCvvTSchyZypdyXgBKdx+ADcw1UAFFqMVZpB6DxpAADHR6AycCrG-gAC1wAFdQvRVsU9fNkHskMEAIIIMD2uChI2m3SLQypMDWuCuiDzZicOAgI5gIoQRjSJQONbrdwABj8ADofEA)

**Comment by AnyhowStep** [comment]
It seems like it has something to do with the `extends` keyword.

**Comment by AnyhowStep** [comment]
In my current project, I end up having a very looooooong tooltip,
![image](https://user-images.githubusercontent.com/5655961/62448483-f39fda00-b735-11e9-8f73-f2ea1aee8c2a.png)

You can see the scroll bar on the right side of the tooltip.

**Comment by AnyhowStep** [comment]
Shorter repro,

```ts
interface InterfaceFoo<DataT extends { name : string }> {
    /**
     * Appear only once plz
     */
    name : DataT["name"]
}

class ClassFoo<DataT extends { name : string }> implements InterfaceFoo<DataT> {
    name! : DataT["name"]
}

///////////////////////
declare const unionType : (
    | ClassFoo<{name:"X"}>
    | ClassFoo<{name:"X"}>
);
/*
Expected:
Appear only once plz

Actual:
Appear only once plz Appear only once plz
*/
unionType.name

```
[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJLmvJAxA9rgHgBE4w4AVZCAD0hABMBnZAb2RDgFsUAuZRsFFABzZAF8AfKwBQyOcgD0AKiWz5yJcgCCABx0Q4UZLhAAbAJ7GQSZDtMAvNfKUKn7Lr2Qky5ANoAiDm5-AF1pMWlpBFM4RmYAYRi4vEJvCipaCAZmNiDPASEQUUlkYE47CG5wZnRIWEQIFOJSCikWNzyAQmQ+NL9Aj1DwyIVRsfGJydHpeghowxQEEwFkAFcQYBNyc30e5AAKNwAfZETYxiaWPJ5-AA1-SWPTpIv8AiuPG-vHgEoAbmkymkAFFqPoEJB6DxpLp9IYrBYrDY7I4YRDVnBTNDYQYjCZESZkQ5tHpcQjLISUCjpC5pOtNiBtvoAHR5aRAA)

**Comment by sandersn** [comment]
Oops. We dedupe non-inherited jsdoc but forgot to do the same for inherited jsdoc.
