### ISSUE TITLE
Insonsistent parsing of JsxIdentifier

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#32701]
**TypeScript Version:**  3.6.0-dev.20190804

**Search Terms:**

**Code**

```tsx
let a = <\u0061></a>; // works
let ab = <\u0061-b></a-b>; // works
let ac = <a-\u0063></a-c>; // reports mismatching closing tag
```

**Expected behavior:**

Consistent parsing of escaped characters in JSX Identifiers.
I don't know the JSX spec, so I cannot tell whether all should be valid or all should be invalid

**Actual behavior:**

`parseJsxIdentifier` is only responsible for everything after the first dash. It wasn't changed to support unicode characters. Therefore the regular Identifier parsing allows escaped characters in the first part.

**Related Issues:**

#32096 forgot to change `parseJsxIdentifier`. cc @weswigham

**Comment by ajafff** [comment]
Babel doesn't seem to parse escaped characters in JSX at all.

**Comment by weswigham** [comment]
JSXIdentifier is still defined in terms of the core IdentifierStart/IdentifierPart, which include Unicode escape sequences, so I suppose they should all work - Babel's wrong here, I suppose.

**Comment by RyanCavanaugh** [comment]
If the fix for this turns out to be at all nontrivial, this is going to Won't Fix unless there's a compelling scenario here I've overlooked 😅

```ts
let a = <\u0061></a>;
```
Do we know if this is supposed to be legal?

**Comment by weswigham** [comment]
> Do we know if this is supposed to be legal?

With the spec AST as written, yes.

JSXIdentifier is:
```
IdentifierStart
JSXIdentifier IdentifierPart
JSXIdentifier NO WHITESPACE OR COMMENT -
```
while ES6+ defined `IdentifierStart` and `IdentifierPart` as:
```
IdentifierStart::
    UnicodeIDStart
    $
    _
    \UnicodeEscapeSequence

IdentifierPart::
    UnicodeIDContinue
    $
    \UnicodeEscapeSequence
    <ZWNJ>
    <ZWJ>
```

so escape sequences being valid in jsx just falls out from the definitions.
