### ISSUE TITLE
Strange inference of union types

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/TypeScript#32709]
**TypeScript Version:**  3.6.0-dev.20190804

**Search Terms:** object type inference undefined

**Code**

I don't know how to create a full repro of this, sorry.

The problem occurs in a JSX project, attempting to assign the `box_style` value to the `style` attribute via JSX, e.g.: `<div style={box_style}>...</div>`.

```ts
function update(model: { x: number, y: number, w: number, h: number } | undefined) {
    const box_style = model
        ? {
            left: `${model.x * 100}%`,
            top: `${model.y * 100}%`,
            width: `${model.w * 100}%`,
            height: `${model.h * 100}%`
        }
        : {};

    // ...
}
```

**Expected behavior:**

The type of `box_style` should be inferred as `{left: string, top: string, width:string, height: string} | {}`, e.g. matching the inferred types of the two object literal alternatives in the expression.

**Actual behavior:**

The shape of the second object is incorrectly inferred as kind of implicit union with the first object (something like `Partial<...>`?) resulting in a union shape like `{left?: string, top?: string, width?: string, height?: string}`, which isn't assignable to the CSS style declaration, since those properties do not allow `undefined`.

There's a difference between e.g. `{}` and `{x:undefined}` in JavaScript, in that `x` is an actual value that can be iterated over, e.g. using `for..in` or `Object.keys()` - yet, it seems like TS3 treats these as having the same type in this case?

Because the non/presence of keys in object literals affects run-time behavior of JS code, There's a difference between having a key or not - if this is "by design" is TS3, that seems really problematic. I'm upgrading a project from TS2 to TS3 that was already using strict mode, and I have hundreds of errors because of this.

**Playground Link:** 

[Link](https://www.typescriptlang.org/play/index.html?jsx=2#code/GYVwdgxgLglg9mABCADgEwIZQKYAoC2ca2ANgFyIDeiAHhWCPgEbYBOANIgJ72MseIA7r2ZtOACxH9EAX0QAfZGGLAYYbGgCUVAFCJ9iCAgDOUREzg0A+qa4lsiALyJCxEnoOeA-Ls9+D9sBQFAAGACSUrqQAdDSIAFSIAIwADCkyAKQh7B7+nlBwKKERUSTRXAnJaZnZuXn6gjBoUJKI4ZFEMYKVqelZOfWe4tgwAObiwW0lnWXiPdVZdZ4ySwYUlDIA3Dp1APS7iNFHOitAA)

**Related Issues:** 

(Sorry, I have no idea what to search for...)

**Comment by ajafff** [comment]
This is intentional and introduced in #19513.
You can work around this by declaring intermediate variables for each object literal.

**Comment by RyanCavanaugh** [comment]
> Because the non/presence of keys in object literals affects run-time behavior of JS code, There's a difference between having a key or not 

TS doesn't currently have a way to model APIs which distinguish between missing properties and properties with the value `undefined`. See #13195

**Comment by mindplay-dk** [comment]
@RyanCavanaugh so #13195 would fix this? (I want to put a todo with the issue number in my code, if I'm going to use the work-around suggested by @ajafff )

**Comment by RyanCavanaugh** [comment]
It's a little tricky because we'd have to figure out some way to do things without causing a huge breaking change. Today it's assumed that you *can* provide `undefined` as an explicit property value when a property is optional, and very very few libraries actually break under this assumption. So we would need some way for `model: ` to be annotated with "I really care about own properties".

FWIW 7+ years of this not really mattering in practice makes this unlikely to be something we address anytime soon.

**Comment by mindplay-dk** [comment]
My example aside, the disctinction seems rather critical in the world of React / JSX and the majority of state management libraries - anything that accepts e.g. `Partial<State>` is going to behave very differently depending on whether the properties are present and `undefined` vs not present.

For example, `setState({ user: undefined, cart: [] })` might log out the user and clear a shopping cart - this behaves very differently from `setState({ cart: [] })` which would just clear the shopping cart. It might not matter in practice (if by that you mean "at run-time") but hovering over an inferred type in a ternary expression somewhere and seeing `{ user: undefined }` in the type signature would make you think the user is getting logged out, which isn't the case, since `user` isn't present in the object and wasn't declared by the object literal in question at all.

I can work around it of course - but I don't like it when the type-system dictates how I have to structure my code; I have reasons for structuring things the way I do, in terms of code readability and such, so it's annoying to have to refactor just to satisfy the compiler.

I don't know, maybe that's not a good enough reason to add more complexity, learning curve and breaking changes to the type-system. But learning to work around the compiler in situations like this is learning curve too, I think?

**Comment by mindplay-dk** [comment]
I guess I don't completely see how/when #19513 is an improvement - it hasn't helped me in two fairly large codebases, all it did was force me to work around issue.

In the case where I *wanted* two inferred object literal types merged, that was already easy enough to do explicitly, e.g. `{...object1, ...object2}` ... ternary expressions like `foo ? object1 : object2` are usually alternative values and types, not one common type.

I guess I've never come across a legitimate use case where #19513 helps, so maybe I don't understand how or what this change is supposed to help with.
