### ISSUE TITLE
Disallow getter that references itself

### ISSUE THREAD

**Issue by iansan5653** [microsoft/TypeScript#32713]
## Suggestion

There is never an instance (that I can think of) where a class getter function would need to reference itself. If it does so, attempting to call that function throws a [too much recursion error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion). So the TypeScript compiler should not allow this to happen.

## Use Cases

This would ensure that anyone who uses a private class member and adds a publicly accessible getter doesn't accidentally reference the public getter instead of the private member (see example below).

It also ensures that, if someone is refactoring and wants to change a private member to a public one, they can use "Rename Symbol" to change, say `_example` to `example` and any existing `get example()` would raise an error.

## Examples

The following would throw an error:
```ts
class Example {
  private _exampleProperty: string = "example";

  public get exampleProperty(): string {
    return this.exampleProperty; // Self-referential; should be this._exampleProperty
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
  - _I don't know about this? It might raise errors where errors don't exist currently but I can't think of an example where this _shouldn't_ be an error._
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
  - This aligns with goal 1: "Statically identify constructs that are likely to be errors."

**Comment by RyanCavanaugh** [comment]
Getters can behave like recursive functions. I can't come up with a non-silly example, but maybe someone has:
```ts
class Example {
    private _exampleProperty: string = "example";
    counter = 4;

    public get exampleProperty(): string {
        if (this.counter == 0) {
            return this._exampleProperty;
        } else {
            // Do something
            this.counter--;
            return "?" + this.exampleProperty;
        }
    }
}
```

**Comment by iansan5653** [comment]
Oh that's a good point. Maybe just error when the function _only_ returns itself? That seems like it would be the most common instance of this error anyway.

**Comment by nmain** [comment]
Would this make more sense (and be reasonably implementable) as a linter rule?

>Getters can behave like recursive functions. I can't come up with a non-silly example, but maybe someone has:

This example could be avoided by only raising an error when the recursive call was not inside a conditional.

**Comment by ajafff** [comment]
> linter rule?

https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/no-accessor-recursion.md

**Comment by fatcerberus** [comment]
I guess the tricky thing is that a getter is a nullary function so you can’t encode the termination condition without reference to some external data (global variable, instance property, etc.). A getter *could* be recursive in this sense, but it certainly wouldn’t be my first choice of how to implement one.

Definitely seems to be more in the domain of a lint rule than a tsc error, at any rate.

**Comment by rotu** [comment]
For simple recursion, typescript *sometimes* seem to infer the return type.

https://www.typescriptlang.org/play?target=99&ts=5.2.0-beta#code/GYVwdgxgLglg9mABHOAHAzgRgBQA8BcYIAtgEYCmATgJSID0diMYwVl5AJou1CJUlACeqcogC8iMOQBuVAFABvbuV79kaLHgDUmWgF85c0JFgJ1GAEx5CJCjXqNmrSuy48+A4aIkBDMIMVlVSQUSzxqHUQ9IA

That is:

```typescript
function oops1(x:number) // inferred return type = never
{ return oops1(x+1) }

function oops2(x:number) // inferred return type = any
{ return oops2(x)+1 }
```

Of course, `never` is assignable to every type, so a return type annotation would break this...

**Comment by RyanCavanaugh** [comment]
No upvotes in 4 years; I think this is safely assumed to not be a priority.
