### ISSUE TITLE
ChocolateChip-UI

### ISSUE THREAD

**Issue by chocolatechipui** [Microsoft/TypeScript#3271]
Please fill the following out:

- Name: ChocolateChip-UI
- Homepage url: http://chocolatechip-ui.com
- Brand Guidelines/Licensing: MIT
- Logo: http://chocolatechip-ui.com/images/CCUI-UI-Only-On-Light.svg

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by jonathandturner** [comment]
Added.
