### ISSUE TITLE
Extended unicode escapes in identifiers are not parsed

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#32717]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
const x\u{0061} = 12;
```

**Expected behavior:**
No error

**Actual behavior:**
Many errors.

[**Playground Link:**](http://www.typescriptlang.org/play/#code/MYewdgzgLgBAHgHQK4G8AMaBsBGAvjAXhmwCYBuIA)

`IdentifierPart` is defined to accept `\UnicodeEscapeSequence` which is defined as [both normal and extended unicode escapes](https://tc39.es/ecma262/#prod-UnicodeEscapeSequence) - right now we only handle normal (`\u0061`) and _not_ extended (`\u{0061}`) escapes.

**Comment by weswigham** [comment]
cc @rbuckton is this just an oversight in our `scanIdentifierParts` function? Or perhaps a more recent change to ecma262?

**Comment by ajafff** [comment]
duplicate of #5291?

**Comment by weswigham** [comment]
So it is.
