### ISSUE TITLE
Typescript versioning inconsitencies

### ISSUE THREAD

**Issue by olmobrutall** [microsoft/TypeScript#32729]
* Following [the blog](https://devblogs.microsoft.com/typescript/), looks like we are in Typescript **3.5**, and  TS 3.6 is in Beta
* But somehow the [Microsoft.TypeScript.MSBuild](https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild) **3.6** Nuget is already released for 18 days
* At the same time if you go to [www.typescriptlang.org download](https://www.typescriptlang.org/#download-links) for VS 2019, it recoments Typescript **3.4.1**

Is there any reason for the inconsistencies? It makes it hard to tell collegues what version of TS to install.

**Comment by RyanCavanaugh** [comment]
> Following the blog, looks like we are in Typescript 3.5, and TS 3.6 is in Beta

This is correct!

> But somehow the Microsoft.TypeScript.MSBuild 3.6 Nuget is already released for 18 days

This is the beta. NuGet does not support non-numeric version numbers, so this is kind of what we have to do.

> At the same time if you go to www.typescriptlang.org download for VS 2019, it recoments Typescript 3.4.1

The website needs a link update. This should point to https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-353

**Comment by MartinJohns** [comment]
> This is the beta. NuGet does not support non-numeric version numbers [..]

NuGet supports [pre-release packages](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages) with non-numeric characters in the pre-release version. You could use the version `3.6.0-beta`.

**Comment by RyanCavanaugh** [comment]
Sorry, misunderstood what my coworker wrote. Our publishing script doesn't *support* publishing version numbers like that 🙃. We're looking into that for next version.

**Comment by orta** [comment]
The website links are now automated on deploys 👍

**Comment by HolgerJeromin** [comment]
> The website links are now automated on deploys

http://www.typescriptlang.org/#download-links links to 
https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-353
and the What's New section is not updated
http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html

ref #31795

**Comment by orta** [comment]
This was all deployed, and maybe the site hadn't been updated at that point because it looks like everything is now up to date so I'm closing this issue

**Comment by olmobrutall** [comment]
@orta another TS version (3.7) and the Visual Studio 2019 download links in [https://www.typescriptlang.org/#download-links]() are pointing again to an outdated version [https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-364]()

**Comment by olmobrutall** [comment]
Cmon guys.... you go here https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html and looks like the page is updated

![image](https://user-images.githubusercontent.com/720953/70215559-07883680-173e-11ea-9f6b-9f637501fb01.png)

But then you click in Get and and the Visual Studio 2019 link is still pointing to https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-364

**Comment by orta** [comment]
Looks like the script to find the latest isn't finding 3.7.2, I Wonder why

**Comment by orta** [comment]
I've updated the script https://github.com/microsoft/TypeScript-Website/pull/146

**Comment by HolgerJeromin** [comment]
The page links to the newest vspackage. Thanks for that.
But what is the status of [3.7.3](https://github.com/microsoft/TypeScript/releases/tag/v3.7.3)?

cc @weswigham

**Comment by weswigham** [comment]
It's published to `npm` 🤷‍♀

**Comment by HolgerJeromin** [comment]
I am missing a `Typescript SDK` in Visual Studio Marketplace for VS2019 and nuget packages. Like the releases before...

**Comment by uniqueiniquity** [comment]
Hello @HolgerJeromin,

The NuGet package and TypeScript SDK will be available soon (within the next 30 minutes).
I apologize for the delay!

**Comment by HolgerJeromin** [comment]
Groundhog Day!
Again, no [release-notes](https://www.typescriptlang.org/docs/handbook/release-notes/overview.html) and no up to date link for [VisualStudio](https://www.typescriptlang.org/index.html#download-links). 8-(
3.8 was released 5 days ago...

**Comment by HolgerJeromin** [comment]
Perhaps the link should be replaced by this search:
https://marketplace.visualstudio.com/search?term=TypeScriptTeam&target=VS&vsVersion=vs2019&sortBy=UpdatedDate
