### ISSUE TITLE
Using noEmit in watch mode performance issue

### ISSUE THREAD

**Issue by hatamov** [microsoft/TypeScript#32724]
**TypeScript Version:**  3.5.2

**Search Terms:** performance, noEmit

**Problem**

Running compiler in _watch_ mode with `noEmit` and `extendedDiagnostics` flags shows that significant amount of time is spent of emit (based on "Emit time" metric):

```
tsc --noEmit --extendedDiagnostics  -p ./src --watch

Files:                        5969
Lines:                      585653
Nodes:                     2423881
Identifiers:                795150
Symbols:                   1520807
Types:                      692312
Memory used:              2428247K
Assignability cache size:   456052
Identity cache size:         16986
Subtype cache size:         107828
I/O Read time:               1.58s
Parse time:                  3.44s
Program time:               24.94s
Bind time:                   4.15s
Check time:                101.30s
transformTime time:         66.03s
commentTime time:            0.84s
printTime time:             72.31s
Emit time:                  72.55s
Total time:                202.94s
```

**Expected behavior:**

Since compiler was running with `--noEmit` option, "Emit time" (and probably printTime) should be zero.

**Actual behavior:**

Nothing is emitted (which is expected), but compiler spent 72.55 seconds on something emit related.

Is this expected considering that `--noEmit` flag is used ?
I apologize in advance if this isn't a bug, but rather an implementation detail.

**Comment by sheetalkamat** [comment]
This is intended since we need to do .d.ts emit to determine files to refresh the errors for.
