### ISSUE TITLE
"Property is used before its initialization" on recursive types

### ISSUE THREAD

**Issue by DavidANeil** [microsoft/TypeScript#32721]
**TypeScript Version:**  3.5.1

**Search Terms:** recursive property initialization outside constructor

**Code**

```ts
class Recursive {
    constructor(private readonly parent?: Recursive) {}
    
    private depth: number = this.parent ? this.parent.depth + 1 : 0;
}
```
**Expected behavior:**
The recursive type compiles

**Actual behavior:**
The type does compile in TS 3.3.3

The type does not compile in TS 3.5.1 with the error
`Property 'depth' is used before its initialization.`

*Note:* Moving the initialization of `depth` into the constructor produces identical output, and correctly passes the type-checker.

**Playground Link:** 
https://www.typescriptlang.org/play/?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false#code/MYGwhgzhAEBKCmwCuAnCBLAbvaBvAUNNMAPYB2EALiksJSSgBQAOKWYlOK8YAJuSACe0ZmG5lKAfgBccRKgzYAlHgC++QiLaYOOXvGaUAFrLJIAtgCN4KaAF5ox9BAB0o8ZWiTHR527HwEi76hkbQANTQAIzQsgAMANz46vigkDAIyGhY8ABy6MA4BESs7JzQIcamFtYoSUSkFNS09EylOuXcfALC7oFSspkKOfmFKsVEPn6VYQ5Orn0SXlMLAUEzEdGx0Ima6upAA

**Comment by RyanCavanaugh** [comment]
Thanks for the short repro and version history!
