### ISSUE TITLE
MsBuild.TypeScript uses Node 32bit by default

### ISSUE THREAD

**Issue by SlavkaOnline** [microsoft/TypeScript#32733]
I tried to use MSBuild.Typescript and discover that it uses only 32bit version of Node.
This is written in  Microsoft.TypeScript.targets
`    <NodePath Condition="'$(OS)' == 'Windows_NT' AND Exists('$(MSBuildExtensionsPath)\Microsoft\VisualStudio\NodeJs\\node.exe')">$(MSBuildExtensionsPath)\Microsoft\VisualStudio\NodeJs</NodePath>
`
But in this path we have win-x64 directory with 64bit version node.exe.
Is it correct?  When I use node from cmd I use 64bit Node

**Comment by RyanCavanaugh** [comment]
Correct. 32-bit Node tends to be faster than 64-bit.

**Comment by SlavkaOnline** [comment]
> Correct. 32-bit Node tends to be faster than 64-bit.
So could you help to resolve my problem?
I can build my project on the local environment (my PC) but when I try to build my project on the build server (with windows server 2008) I have a problem with memory for node. After use google, I discovered that if I set NODE_OPTIONS=--max_old_space_size=4096 and use 64bit Node it resolve my problem. But it all seems very strange to me.

**Comment by RyanCavanaugh** [comment]
It sounds like you were able to find the solution. Is there anything else we can help clarify?

**Comment by SlavkaOnline** [comment]
> It sounds like you were able to find the solution. Is there anything else we can help clarify?

I think in the future I will use NPM package for tsc.js. That's all, thank.

**Comment by RyanCavanaugh** [comment]
That's a good plan. Thanks!
