### ISSUE TITLE
Allow type deduction of values while allowing key declaration

### ISSUE THREAD

**Issue by lonewarrior556** [microsoft/TypeScript#32741]
## Search Terms
partial typings

## Suggestion
I suggest adding a way to allow someone to specify the keys on an object but allow typescript to figure out the type of value.

## Use Cases
One of the nicest feature of typescript is that when you declare an object, typescript can automatically deduce the right type without you needing the type it manually ie.
```
const a = {
  a: 'string',
  b: 10,
  c: Promise.resolve('string') 
}
```
is automatically of type 
```
{
  a: string;
  b: number;
  c: Promise<string>; 
}
```

However the second you try to specify any typing on the object ts stops deducing. 
[TS Playground](https://www.typescriptlang.org/play/#code/MYewdgzgLgBBIFsCmBRAHgQwQBwDZIHkAjAKxgF4YBvAWACgYYMAuGMAV11wBp7GjWHLrwYxggzjz4wkE4fQC+9elACe2JDADSSVRAowA1rpAAzGGo1m4iVJhz5iJFes1OA6gEsoACx16DKhgAbWNVGE8wbV0IAF1WDDBwhQBuZToAegyYABMkHPZgJH1QACdSpGBYS2KYa1MQEABGADUMXH0idlgzUyQK-TAQGB8kXGwLHwxYTU99BDmISIBzelBIWAbmwOkWGAByaFKV-ZF+ViaABjOxVgAFUsQ5pAA6AZBcADckAApDqGOYGW+wAlDBuDB6FlGLIYD8weQAHzUMTgeD4F64EDLP5EDClUEwJR0YlQ7L4KDzTSGIYAdwOSH2EXmixWEK6sCG1Vc+nxmjyBSKOTWaM2jQATKwPN4-DEdqI9v9AcCbgIYFcbuIYA8nhBXu8vr8lScwRDpLD4RRkUF1ujXlicfs8QSwcTSXRbdUfHMAJIQAAqrgAggBlAErAxbJovDAijaTX0B4NJSMSmMwaG0kCcHIwIiaMCeIoRcy+OaonN58I1ODhoFAA)

It would be nice especially for larger objects to allow keys to be typed while letting ts take care of the values
## Examples
Some suggestions.
1. allow typing just keys
```
type Keys = 'a' | 'b' | 'c'

var foo1: {[key in Keys]} = {
  a: 'string'
  b 10
} 

typeof foo // {a: string, b: number}

var foo2: {[key in Keys]} = {
  a: 'string'
  d: null     // type error 
} 
```

2.  having a `deduced`, `infered` or `auto` type
```
type Keys = 'a' | 'b' | 'c'
type ObjWithKeys = { [key in Keys]: auto};

var foo1: ObjWithKeys = {
  a: 'string'
  b 10
} 
typeof foo1 // {a: string, b: number}

var foo2: {[key in Keys]} = {
  a: 'string'
  d: null     // type error  
} 
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #7481 - with that you could write
```ts
let foo = {
  a: "foo",
  b: 30
} ??as?? Record<Keys, any>;
``

**Comment by lonewarrior556** [comment]
Duplicate depending on implementation..
It's important that `??as??` does not cast any on the values [seems like there was some back and forth on that]

But Duplicate of https://github.com/microsoft/TypeScript/issues/2876
```
type Keys = 'a' | 'b' | 'c'
type ObjWithKeys = { [key in Keys]: <?>};

var foo1: ObjWithKeys = {
  a: 'string'
  b 10
} 
typeof foo1 // {a: string, b: number}
```
