### ISSUE TITLE
Regression with `await` type extraction in strict mode

### ISSUE THREAD

**Issue by ulrichb** [microsoft/TypeScript#32752]
**TypeScript Version:** 3.6.0-dev.20190807 (worked up to 3.6.0-dev.20190804)

**Search Terms:** await type promise

**Code**

```ts
const containsPromises: unique symbol = Symbol();

type DeepPromised<T> =
    { [containsPromises]?: true } &
    {
        [TKey in keyof T]: T[TKey] | DeepPromised<T[TKey]> | Promise<DeepPromised<T[TKey]>>
    };

async function fun<T>(deepPromised: DeepPromised<T>) {

    const deepPromisedWithIndexer:
        DeepPromised<{ [name: string]: {} | null | undefined }> = deepPromised;

    for (const value of Object.values(deepPromisedWithIndexer)) {

        const awaitedValue = await value;

        if (awaitedValue)
            await fun(awaitedValue);
    }
}
```
(Compile with `--strict`!)

**Expected behavior:**
No compile error as in TS 3.5.3.

**Actual behavior:**

```plain
TypeScriptIssueNext.ts:21:23 - error TS2345: Argument of type '{} | ({ [containsPromises]?: true | undefined; } & {})' is not assignable to parameter of type 'DeepPromised<{ [containsPromises]?: undefined; }>'.
  Types of property '[containsPromises]' are incompatible.
    Type 'true | undefined' is not assignable to type '(true & Promise<never>) | undefined'.
      Type 'true' is not assignable to type '(true & Promise<never>) | undefined'.

21             await fun(awaitedValue);
                         ~~~~~~~~~~~~
```

**Playground Link:** [Here](https://www.typescriptlang.org/play/?target=6#code/MYewdgzgLgBKZQIYEtIAUBOIC2yIFMIAuGAVzGQEdT8YIBPbAIxABsYBeGAZUZdYAUASgDcAWABQkqPQAOtACL58szDjz4AJgB4AKgD5OkmCZgBvGAG14SVBDW4CEALoB+ElAw0YAXxgAyY1MzINNTS10AaXx6GFQYAGsYkAAzGF1nEl0I6PpnGAAfGCUVBw0dbKiY50MisoJtEtUsRy09HOr9fVDfcSkJRAYwYBgU8mAoZHBR8j19AU1lZvUCTRIm+raDIXNJHvhoGEXSlvKAdWQoAAsASTBFgA98DCIesI3T1e0LSzBEbHwJGgGFQAHNMuY-EUwKRWOwiuRFilUFpfIYuMdlq1NH0eikQBgYAIDrAAG6IVjeVIwADyTAAVvgJgA6cmUwgLJabTQXa53R7PIQ7EL9MJhEkwRAAdxQUC0ADUKd4uNLZTA2TRcRIxaZkGkBKrLgqlfghG8dZKZZcZmADVa5ZpFezRD0fJI3RIgA)
BTW: Please update the libs in the playground, `Object.values()` (ES2017) isn't available.

**Related Issues:** -

**Comment by ahejlsberg** [comment]
Simpler repro:

```ts
type Deep<T> = { [K in keyof T]: T[K] | Deep<T[K]> };

declare function foo<T>(dp: Deep<T>): T;
declare let xx: { a: string | undefined };

foo(xx);  // Error
```
