### ISSUE TITLE
toElement missing from MouseEvent in v3.6-beta/dev

### ISSUE THREAD

**Issue by bre1470** [microsoft/TypeScript#32751]
**TypeScript Version:**  3.6.0-dev.20190807

**Search Terms:** super parent property , super parent properties

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
interface Obj extends PointerEvent {
}
let o: Obj;
if (o && (o.relatedTarget || o.toElement)) {
    console.log(':)');
}
```

**Expected behavior:**
Inherited `toElement` from MouseEvent should be recognized like `relatedTarget`.

**Actual behavior:**
Error: Property 'toElement' does not exist on type 'Obj'.

**Playground Link:**
Lacking v3.6.

**Related Issues:**
Unknown

**Comment by sandersn** [comment]
@bre1470 can you explain how these are unstable? Do they vary over time as you interact with them in the editor?

(I hope they are just inconsistent, because it's usually a simpler bug in that case.)

**Comment by sandersn** [comment]
@bre1470 I can't find `toElement` anywhere in the PointerEvent class hierarchy. It doesn't even show up in lib.dom.d.ts. Was it there on an older version of Typescript?

**Comment by sandersn** [comment]
Looks like `toElement` is an old IE property. lib.dom.d.ts doesn't include these anymore, so you may need a shim to provide them (or cast to any if you're just doing feature detection).

**Comment by bre1470** [comment]
Thanks for the help! It was part of previous declarations (though with deprecated flag) and when I checked the declaration in the editor, it was still present - but this was pointing to editors declaration (3.5.1), what I obviously missed. Sorry for the false alarm.

**Comment by sod** [comment]
Chrome implements it for mouseenter & mouseleave events. It contains the element the cursor hit when the event emits. In case there is a mouseleave because the user enters a native element (like autosuggest dropdown) it contains `null`.

In firefox it's undefined.
