### ISSUE TITLE
Window props Blob and URL do not exist in v3.6 beta/dev

### ISSUE THREAD

**Issue by bre1470** [microsoft/TypeScript#32750]
**TypeScript Version:**  3.6.0-dev.20190807

**Search Terms:** window url, window blob, window property, window properties

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
declare global {
    const win: Window;
}
if (win.Blob && win.URL) {
    console.log(':)');
}
export {};
```

**Expected behavior:**

Compiles without a problem.

**Actual behavior:**

Errors:
> Property 'Blob' does not exist on type 'Window'.
> Property 'URL' does not exist on type 'Window'.

**Playground Link:**

3.6 is not available in playground.

**Related Issues:**

Nope.

**Comment by sandersn** [comment]
Removed by https://github.com/microsoft/TSJS-lib-generator/pull/715. The removal was intentional, but I'll revisit the decision. @saschanaz do you have an opinion on this?

**Comment by sandersn** [comment]
Never mind, I mis-remembered the change. `Blob` and `URL` are available globally, and can be referenced on `window`. However, in 3.6, `window: Window & typeof globalThis`. You'll need to update your declaration of `win` for 3.6 to match it.
