### ISSUE TITLE
Allow omitting 'this' keyword when field name reference is non-ambiguous

### ISSUE THREAD

**Issue by GabeKuslansky** [microsoft/TypeScript#32764]
## Search Terms
class this field keyword property

## Suggestion

We currently require the 'this' keyword to be prepended to the field name being referenced
```typescript
class UserService {
    private readonly _userRepository: UserRepository;

    constructor(userRepository: IUserRepository) {
        this._userRepository = userRepository;
    }

    public async getUser(id: number): Promise<User> {
        return await this._userRepository.getUser(id);
    }
}
```

When there is no ambiguity in the reference to the field name, the 'this' keyword should be allowed to be omitted
```typescript
class UserService {
    private readonly _userRepository: UserRepository;

    constructor(userRepository: IUserRepository) {
        _userRepository = userRepository;
    }

    public async getUser(id: number): Promise<User> {
        return await _userRepository.getUser(id);
    }
}
```

## Use Cases
It is syntactic sugar which eliminates redundancy and allows for more concise code

## Checklist

My suggestion meets these guidelines:

*  [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This isn't how JavaScript works and we don't want to change the runtime semantics of JavaScript code.

**Comment by nmain** [comment]
I started writing this before the official response came in, so I'll just leave a bit of reminder about the spec.

As far as the JS spec goes, the following code:

```js
new (class { _foo; constructor() { console.log(_foo) } })
```

will look for a `_foo` on the global scope (assuming there was no `_foo` in a closer scope), and so could throw a `ReferenceError` at runtime, or print the value of `Function("return this")()._foo`

So it's not invalid javascript even when there's no `_foo` in an enclosing scope, because global lookups are fully dynamic.
