### ISSUE TITLE
the types 'T' and (anything else) have no overlap

### ISSUE THREAD

**Issue by davidje13** [microsoft/TypeScript#32768]
**TypeScript Version:**  3.5.3

**Search Terms:**

* Generic "has no overlap"

**Code**

```ts
const num = 1;
function check<T>(x: T) {
  return x === num;
}
check(num);
```

**Expected behavior:**

No error; `check` returns `true` if given `num` (or an alias of it), and `false` otherwise.

**Actual behavior:**

> ```
> index.ts:3:10 - error TS2367: This condition will always return 'false' since the types 'T' and '1' have no overlap.
>
> 3   return x === num;
>            ~~~~~~~~~
>
>
> Found 1 error.
> ```

I observed this in a slightly more complex case but with the same idea:

```ts
const makeNum = () => 1;
function check<T>(f: () => T) {
  return f === makeNum;
}
check(makeNum);
```

**Playground Link:**
https://www.typescriptlang.org/play/#code/MYewdgzgLgBGCuBbGBeGBGA3AKAGbzGCgEtwZgALAU2AGsAeAFQD4AKADwC4ZGBKGAN7YYMAE5Uo8UWBjtUKNAkQ4Avtko1arJb0xA

**Comment by davidje13** [comment]
My use-case approximates to the following:

```ts
const isNum = (v: unknown) => {
  if (typeof v !== 'number') throw new Error('Not a number');
  return v;
};
const isString = (v: unknown) => {
  if (typeof v !== 'string') throw new Error('Not a string');
  return v;
};

function makeExampleValue<T>(validator: (v: unknown) => T): T {
  if (parser === isNum) return 42;
  if (parser === isString) return 'something';
  throw new Error('unknown type');
}
```

I'm considering restructuring to avoid the need for what is effectively a switch in a monolith function, but the reported error is incorrect in any case.

**Comment by AnyhowStep** [comment]
`T extends unknown`?

**Comment by davidje13** [comment]
@AnyhowStep that works, so I guess I'm confused why `<T>` and `<T extends unknown>` are different (i.e. why isn't `extends unknown` the default assumption?)

**Comment by AnyhowStep** [comment]
If it can't infer `T`, it should default to `unknown` in your case (since you didn't specify a constraint type).

As for why you need to explicitly add `extends unknown` for your equality check to work, even though `extends unknown` should be implicit...

¯\\_(ツ)_/¯

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser what's the reasoning behind the current comparability rules with type parameters?

**Comment by jack-williams** [comment]
@AnyhowStep 

> As for why you need to explicitly add extends unknown for your equality check to work, even though extends unknown should be implicit

Without an explicit constraint I think the default constraint used is the empty object type (if you do `extends {}` you get the same result as with no constraint).
```ts                     
const constraint = getConstraintOfType(<TypeVariable>source);
if (!constraint || (source.flags & TypeFlags.TypeParameter && constraint.flags & TypeFlags.Any)) {
    // A type variable with no constraint is not related to the non-primitive object type.
    if (result = isRelatedTo(emptyObjectType, extractTypesOfKind(target, ~TypeFlags.NonPrimitive))) {
        errorInfo = saveErrorInfo;
        return result;
    }
}
```

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh `number` is not comparable with `T`, and `T` isn't comparable to `number` (because `T`'s constraint isn't comparable to `number`).

We have another issue open about this, but if you tried to "fix" it, you might end up with weird behavior where two unrelated type parameters `T` and `U` can be checked for equality. While it's not unsound, it allows questionable code.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser 

> because unknown - T's constraint - isn't comparable to number

`unknown` is comparable to `number`, and the example works *if* `T` is explicit constrained to `unknown` (which should (???) be a no-op by my understanding).

**Comment by DanielRosenwasser** [comment]
> `unknown` is comparable to `number`

It's actually the other way around - `number` is comparable to `unknown`. Comparability is still a unidirectional relationship that we happen to apply in two directions.

> and the example works *if* `T` is explicit constrained to `unknown` (which should (???) be a no-op by my understanding).

I would consider that a bug, and I've opened #32814 to track it. I would guess it's likely either a bug in our `getApparentType` logic, or in the way we get implicit constraints.

**Comment by RyanCavanaugh** [comment]
We're going to track this at #32814 for clarity

**Comment by weswigham** [comment]
> Without an explicit constraint I think the default constraint used is the empty object type

FYI, the default base constraint is `unknown` nowadays - we swapped a few releases ago.

**Comment by jack-williams** [comment]
Yeah I knew the design had changed, but I wasn't sure if a case had been missed. That code looked related, though tbh, I'm not really sure what's going on.
