### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by andrey-furman** [microsoft/TypeScript#32762]
Check out the screen, please:
http://joxi.ru/1A5voQxcDRvL1r
Maybe you wrong with an interface name.
Best regards, Andrey.

**Comment by RyanCavanaugh** [comment]
There is no way I am clicking that link. Please include a screenshot inline with your post.

**Comment by MartinJohns** [comment]
@RyanCavanaugh https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types

> **keyof Car** is completely interchangeable with 'manufacturer' | 'model' | 'year'. The difference is that if you add another property to Car, say ownersAddress: string, then **keyof Person** will automatically update to be 'manufacturer' | 'model' | 'year' | 'ownersAddress'.

**Comment by RyanCavanaugh** [comment]
@MartinJohns thanks! 😅

**Comment by AnyhowStep** [comment]
Seems like joxi is a "free screen capture tool". Pretty sure all mainstream OS have those by default

**Comment by orta** [comment]
PR'd a fix 👍

**Comment by andrey-furman** [comment]
Thanks you too.
