### ISSUE TITLE
mjs

### ISSUE THREAD

**Issue by andrey-furman** [microsoft/TypeScript#32777]
## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment]
Wow, this is a very good issue description.

**Comment by orta** [comment]
Thanks for taking the time to write an issue @andrey-furman  - but as this isn't really actionable, an idea for discussion, nor filled out. I'm going to close it.

**Comment by andrey-furman** [comment]
Sorry about that. I was going to create a new report about scp->mjs, but
found already createt proposal. In a nutshell, it was mistake.
