### ISSUE TITLE
A strange problem with enum

### ISSUE THREAD

**Issue by KiraMaple** [microsoft/TypeScript#32775]
**TypeScript Version:**  3.5.3

**Search Terms:**
enums

**Code**

protocol.ts
```ts
export default namespace Protocol {
    export enum RetCode {
        None,
        Success,

        Max = 100,
    }
}
```

ProtocolLogic.ts
```ts
import Protocol from "./protocol";

export default namespace ProtocolLogic {
    export enum RetCode {
        None,
        Success = Protocol.RetCode.Success,
        Min = Protocol.RetCode.Max,        // If use this line, the output will be wrong.
        // Min = 100,        // If use this line, the output will be correct.
        InternalError,
        EmptyRequest,
        InvalidRequest,
        // more ...
    }
}

console.log(ProtocolLogic.RetCode);
```

*Run it in @vue/cli-service. It's no problem in node.js*
**Expected behavior:**
![image](https://user-images.githubusercontent.com/6917877/62752201-0b11f680-ba99-11e9-8f3f-c31d08bf8235.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/6917877/62752219-267d0180-ba99-11e9-86ad-bfbaddc0e7f2.png)

**Comment by AnyhowStep** [comment]
If `node` is fine, then wouldn't the problem be with `@vue/cli-service`?

I cannot seem to reproduce it on the [Playground](http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAOwIYFtgGcxIMbDgBSghgmwgBs4BvAWACg5G5RJZmEBXFOAJWBgDCEACZ5aDJpIByEBMAA09SZIDKHbLnTpFdJcsYBZJCDgBeOAEYADFZ2SAvvUd0W0eMjSYceQsVIUAGQgAcwBLbGo9Rlc2YE5uPkERMSjlGTk7fTg1DQx0MwIiEjJyADpEoVFSnM1tVMkDUIQC32KKcv5K4FKjEHksuAB6QbgASQAzOA50PBgAC1D88iaFOHm8CA4YMC24AHdQ8koAIzw9ogRg0vqmYbhG5vNrWwG7iamZtYWllf71uE2212ByOcFOcDIUCgwGwMGuEn0owQMGAUGQ5AAolDoJl9BiUGAYABPPgARw4GBguOUSIAbkhlsIyRT0FSbow7ihoHhSrzUs57EA)

![image](https://user-images.githubusercontent.com/5655961/62755771-500b3e00-ba43-11e9-8e02-222f42bfa303.png)

**Comment by RyanCavanaugh** [comment]
Sounds like an external tool problem. If you think this is a TypeScript problem, you'll need to provide a repro that works in a normal environment.
