### ISSUE TITLE
TS doesn't understand that NaN is a falsy number

### ISSUE THREAD

**Issue by Validark** [microsoft/TypeScript#32778]
**TypeScript Version:**  latest beta

**Search Terms:** NaN truthiness falsy 0 is not the only falsy number

**Code**

```ts
function f(a: number, b: string) {
    return a && b;
}

const x: string | 0 = f(0 / 0, "Hello"); // should error but doesn't
```

**Expected behavior:** function `f` should return a `string` or `number`, since there currently is no NaN type in TS. If there was, it would return `0 | NaN | string`

**Actual behavior:** function `f` returns `string | 0`

**Comment by RyanCavanaugh** [comment]
Duplicate #15135

**Comment by osyrisrblx** [comment]
@RyanCavanaugh I don't think this is actually a duplicate of that issue. The issue you linked is more along the lines of "these are terms in JavaScript and should exist in TypeScript".

Rather, this is a truthiness bug! [Here's a more simple example:](http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAIznANgCgJQC4VroCmAhkgN6IBORUIVSwJ6AzkQNyIC+AUKJLASIwIALbIiVHPhHjJiSjToNEAORKrOvHsSiISiALzCxEqdnY7aKIwQw5LPCAhZ6AHrYMAyLyk4B6f0QoAE8AByJbVAxSJAAfRAAGJxcYgDp0OABzTDcLREDEMKoYMCgWNQ0eIA)

```TS
function bool(): boolean { return false; }
function number(): number { return NaN; }

let a = number();
let b = bool();

const x = a && b; // type = boolean | 0
console.log(x); // prints NaN
```
