### ISSUE TITLE
Strange TS2339 Error

### ISSUE THREAD

**Issue by vipcxj** [microsoft/TypeScript#32773]
**TypeScript Version:**  3.5.3

**Search Terms:** TS2339 

```ts
import React from 'react'
const style: React.CSSProperties = {
    width: 10, // this is ok
    height: 10, // this is ok
}

style.width = 20 // TS2339: Property 'width' does not exist on type 'CSSProperties'
style.height= 20 // TS2339: Property 'height' does not exist on type 'CSSProperties'
```

**Expected behavior:**
no error
**Actual behavior:**
TS2339 error
**Playground Link:** 

**Related Issues:**

**Comment by AnyhowStep** [comment]
Can't seem to reproduce with 3.5.1 on the [Playground](http://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQLABQuEAdqvKwJ4A2WAXJlTAB0AYQDKogArEwWWMCzoAvHADe9OBrgB3YABMYACz4BGAAwAaOAHorcQ8HQO4EANbrNBrMADmBmCYtrW3tHdFd6AF96eg5uQR19AzhlACZTINEsLBB0AHkAaRiYLixBTx8-VPSbTOy8-KA)

**Comment by RyanCavanaugh** [comment]
Not reproing for me in a regular React project. Can you provide more details?

**Comment by vipcxj** [comment]
Process: TypeScript service version: 3.5.3
Process: Default service options: {"allowSyntheticDefaultImports":true,"declaration":true,"module":5,"noImplicitAny":true,"jsx":2,"target":1,"configFilePath":"D:/project/nodejs/react-mobile-style-picker/tsconfig.json"}
(node:12572) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

This is my config and typescript version

**Comment by vipcxj** [comment]
@AnyhowStep @RyanCavanaugh 
I found the problem. If I add a `moduleResolution: 'node'` to the tsconfig.json, it fix. I think this should be the default option.

**Comment by rpearce** [comment]
For what it's worth, I still get this in latest VSCode using the example code from OP on an OSS `react` project of mine https://github.com/rpearce/react-medium-image-zoom:

<img width="642" alt="imagen" src="https://user-images.githubusercontent.com/592876/235036448-92eb5c9a-3c69-4dcb-9692-dc50bafff18f.png">

<details>
  <summary>Expand to see <code>tsconfig.json</code></summary>

```json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": true,
    "emitDeclarationOnly": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["esnext", "dom"],
    "module": "esnext",
    "noImplicitAny": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist",
    "removeComments": true,
    "sourceMap": false,
    "strict": true,
    "target": "es2021"
  },
  "include": ["./source/index.ts"]
}
```

</details>

Running `typescript@5.0.4`, `@types/node@18.15.13`, `@types/react@18.0.38`, `@types/react-dom@18.0.11`

**Comment by dzek69** [comment]
I get exactly this after upgrading my monorepo from yarn to pnpm. TS 5.1.3. I'd have to do a really big cleanup to be able to provide reproduction repo, right now I will just leave it here.

**Comment by mshabarov** [comment]
Got the same error with:
- "react": "18.2.0",
- "typescript": "5.4.5",
- "vite": "5.2.10",
- Node.js v18.17.1

Here is my code snippet:
```
 const iconStyle: React.CSSProperties = {};
  if (isChild) {
    iconStyle.width = 'var(--lumo-icon-size-s)';
    iconStyle.height = 'var(--lumo-icon-size-s)';
    iconStyle.marginRight = 'var(--lumo-space-s)';
  }
```
Full codes example is [here](https://github.com/vaadin/docs/blob/aa3500ae311c0ab7e400a11d3ccc003bc0050820/frontend/demo/component/menubar/react/menu-bar-icons.tsx#L7-L26).

**Comment by RyanCavanaugh** [comment]
Please log a new issue with repro steps instead of commenting on issues that were closed 4 years ago 🥰
