### ISSUE TITLE
Allow SolutionBuilder API to force build projects

### ISSUE THREAD

**Issue by ToddThomson** [microsoft/TypeScript#32781]
@sheetalkamat Thank-you for your guidance on how to use getNextInvalidatedProject from the SolutionBuilder API to introduce transforms into the incremental build pipeline.

I would like to ask for a change to the SolutionBuilder API so that each project in the solution could be obtained ( in build order ); the status of the project obtained; a way to force build a project.

All of these things exist in the solution builder today, however they are not public.

**Comment by sheetalkamat** [comment]
This already exists today. If you create solution builder with { force : true} as build options it will force build of each project

**Comment by ToddThomson** [comment]
Thanks @sheetalkamat Yes, BuildOptions with { force: true } will cause all projects within the solution to be invalidated. That wasn't quite what I was asking for, but I believe it will suffice. I see finer control at the project level to be an improvement, but I may not need it.

A (really!) small point that you may want to consider: a status report message is generated mentioning that a project is up-to-date even when { force: true }. Also, the up-to-date message is really specific. It could be a case of too much information.

**Comment by sheetalkamat** [comment]
force: true does build everything as if no output exists on the disk. I don't think we want finer control than that without causing issues since every project and its build has implications on the other.
