### ISSUE TITLE
ConstructorParameters<T> doesn't work for optional arguments

### ISSUE THREAD

**Issue by redbaron** [microsoft/TypeScript#32784]
**TypeScript Version:**  3.5.3

**Search Terms:** ConstructorParameters, optional arguments

**Code**

```ts
class A {
    constructor (a: string, b?: number) {}
}

const test1 : ConstructorParameters<A> = ["a", 9];
const test2 : ConstructorParameters<A> = ["a"];

```

**Expected behavior:**
ConstructorParameters<A> should return `[string, number | undefined]` tuple 

**Actual behavior:**
```
[eval].ts(5,33): error TS2344: Type 'A' does not satisfy the constraint 'new (...args: any) => any'.
  Type 'A' provides no match for the signature 'new (...args: any): any'.
[eval].ts(5,39): error TS2322: Type 'string' is not assignable to type 'never'.
[eval].ts(5,44): error TS2322: Type 'number' is not assignable to type 'never'.
```

**Playground Link:**  https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAECC0G8BQ1XWAewHYQC4CcBXYXDfaACjAC5o98BLLAcwBpoAjAflq0IFsOAU3wBKRAF8kUpJhy5ouIXgCM0WgGFs9YqXwAFMPjD8hS-BAA8sAHzQAvNADaAIjAv2ATgC6AblnaCkp4AEzq0FryRCRkhsam5la2Ds5uLn5AA
**Related Issues:** 
Maybe https://github.com/Microsoft/TypeScript/issues/12400 ?

**Comment by AnyhowStep** [comment]
Try `typeof A`

**Comment by dragomirtitian** [comment]
`A` represents the instance type and does not itself have a constructor. `typeof A` is the type representing the class  and has the constructor signature. This will work as expected:

```ts
class A {
    constructor (a: string, b?: number) {}
}

const test1 : ConstructorParameters<typeof A> = ["a", 9];
const test2 : ConstructorParameters<typeof A> = ["a"];
```
[Play](https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAECC0G8BQ1XWAewHYQC4CcBXYXDfaACjAC5o98BLLAcwBpoAjAflq0IFsOAU3wBKRAF8kUpJhy5ouIXgCM0WgGFs9YqXwAFMPjD8hS-BAA8uAJ4AHIRgBmcAHzQAvNADaAIjC+7ACcALoA3LLaCkp4AEzq0FryRCRkhsam5la2Ds5unj7+vuFAA)

**Comment by redbaron** [comment]
I am so sorry, didn't think of `type of`
