### ISSUE TITLE
Exporting ES6 seems to strip comments

### ISSUE THREAD

**Issue by karimbeyrouti** [Microsoft/TypeScript#3278]
I am exporting my Lib to ES6, and for some reason it is stripping my comments from my code.

TSC command:

tsc --rootDir libtses6/ --outDir libtses6/ -t ES6 

Happy to include some source files it it helps.

**Comment by mhegazy** [comment]
@karinbeyrouti is this not an issue any longer?

**Comment by DanielRosenwasser** [comment]
Also if so @karimbeyrouti, what version of TypeScript were you on?

**Comment by karimbeyrouti** [comment]
Yes, sadly I was still having the issue - and was using the 1.5.0 Beta. However it was also giving me a load of export errors ( with code I had working ), so not sure if that was it. 

Here is the repo: https://github.com/karimbeyrouti/kurstTypeScript

**Comment by DanielRosenwasser** [comment]
> it now just prints the help menu

Was there different behavior you had before?

**Comment by karimbeyrouti** [comment]
Yes - it was emitting the whole directory. here is the output:
https://github.com/karimbeyrouti/kurstTypeScript/tree/master/export

or at least I was expecting it to export the folder...

**Comment by mhegazy** [comment]
@karimbeyrouti you need to include an empty tsconfig.json file at the root of your repo. this way the compiler knows it needs to walk all .ts files in the directory tree.

**Comment by karimbeyrouti** [comment]
Yep - that did it. thank you .
