### ISSUE TITLE
Watching files on network shares is too expensive

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#32796]
Some customers have complained that VS is unresponsive when their project is hosted on a network share (usually accessed via UNC).  For example, https://developercommunity.visualstudio.com/content/problem/553481/javascript-language-service-in-classic-old-asp-pro.html.  Would it be worthwhile to provide a mode (possibly even the default) where non-local files and directories are not watched?

**Comment by amcasey** [comment]
FYI @sheetalkamat

**Comment by sheetalkamat** [comment]
Looking at the logs we just need to handle directories to ignore when the root is network path, just like we ignore folders at root level. Eg. we do not watch directory "/" so we don't want "/tsconfig.json" either.

**Comment by amcasey** [comment]
@sheetalkamat That seems like a good solution.
