### ISSUE TITLE
Improve error on non-ambient class and function merge

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#32795]
In #32584, we're allowing ambient classes and functions to merge, but non-ambient classes and functions still issue the same `Duplicate identifier` error. An improved, more specific, error would be [useful](https://github.com/microsoft/TypeScript/pull/32584#discussion_r312631137). Something mentioning that either the function can have an implementation or both need to be ambient.

**Comment by austincummings** [comment]
I can work on this one.

**Comment by austincummings** [comment]
@weswigham here's the error message I've come up with. Any thought?

`Class declaration cannot implement overload list for '{0}'. Function may have implementation or both class and function declarations must be ambient.`

**Comment by weswigham** [comment]
At at glance I'd say that looks good, but I'm wondering if the term `ambient` is something we've used in an error message yet. @DanielRosenwasser ?

**Comment by DanielRosenwasser** [comment]
At a glance it's fine to say "ambient" as long as you have something actionable.

On the function: `Function with bodies can only merge with classes that are ambient."

Related span on the class: `Consider adding a 'declare' modifier to this class."

**Comment by austincummings** [comment]
@DanielRosenwasser would that look something like this then? Or should the "Function with bodies..." messages only appear when hovering over the function name?

![image](https://user-images.githubusercontent.com/3136967/64898640-c3086580-d63c-11e9-80dd-bb7a389b9958.png)

**Comment by weswigham** [comment]
`Function with bodies can only merge with classes that are ambient.` is supposed to be the primary error on the functions, instead of `Class declaration cannot implement overload list for '{0}'. Function may have implementation or both class and function declarations must be ambient.`. The related spans are both supposed to be referring to the same thing.

**Comment by austincummings** [comment]
> The related spans are both supposed to be referring to the same thing.

@weswigham sorry, I'm a bit confused as to what "same thing" refers to. Here's my understanding.

```ts
function Foo(): any;
function Foo(n: number): any {} 
//       ~~~  Function with bodies can only merge with classes that are ambient.
//       No related messages/spans?

class Foo {} 
//    ~~~ Class declaration cannot implement overload list for '{0}'
//    And related "Consider adding 'declare'..." referring to the span of this class?

```

**Comment by weswigham** [comment]
The `function Foo` should have the same related spans as the other error. Otherwise it looks good.
