### ISSUE TITLE
Support top-level await in SystemJS modules

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#32793]
> ### Top-level await
> 
> ```js
> console.log('sync');
> await new Promise(resolve => setTimeout(resolve));
> console.log('async');
> ```
> 
> ->
> 
> ```js
> System.register([], function (exports, context) {
>   return {
>     setters: [],
>     execute: async function () {
>       console.log('sync');
>       await new Promise(resolve => setTimeout(resolve));
>       console.log('async');
>     }
>   };
> });
> ```
> 
> Where in dependency graphs, SystemJS supports variant B of the top-level await proposal.

_Originally posted by @guybedford in https://github.com/microsoft/TypeScript/issues/26606_

**Comment by ExE-Boss** [comment]
This&nbsp;can&nbsp;now be&nbsp;closed.

**Comment by rbuckton** [comment]
Fixed in #35813
