### ISSUE TITLE
Default assignment of an empty array to known array type should keep type

### ISSUE THREAD

**Issue by zavr-1** [microsoft/TypeScript#32799]
**TypeScript Version:**  3.5.2

**Search Terms:** array type default

**Code**

```ts
/**
 * @param {Object} [opts]
 * @param {string[]} [opts.arr]
 */
function test(opts = {}) {
  const { arr } = opts
}
```

**Expected behavior:**

![Screenshot 2019-08-10 at 05 43 04](https://user-images.githubusercontent.com/21156791/62816529-c1291f00-bb31-11e9-8ed3-033697216c9c.png)

**Actual behavior:**

![Screenshot 2019-08-10 at 05 43 32](https://user-images.githubusercontent.com/21156791/62816531-d140fe80-bb31-11e9-9277-674d1d3ffa66.png)

Sure I can cast `{ arr = /** @type {string[]} */ ([]) }`but I shouldn't have to really.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Equivalent TypeScript code works, so the problem is likely something to do with JS Doc handling
```ts
function fn(obj: { arr?: string[] } = {}) {
    const { arr = [] } = obj;
    // arr: string[]
}
```

**Comment by RyanCavanaugh** [comment]
Works now
