### ISSUE TITLE
Allow `== null` to narrow `unknown` to `null | undefined`

### ISSUE THREAD

**Issue by ericyhwang** [microsoft/TypeScript#32798]
**TypeScript Version:**  typescript@3.6.0-dev.20190809

**Search Terms:** unknown, type guard, double-equals, ==, null

**Code**

Minimal repro case:

```ts
export function test(v: unknown) {
  let nullOrUndefined: null | undefined;
  if (v === null || v === undefined) {
    // This works, as `v` is narrowed to `null | undefined`.
    nullOrUndefined = v;
  }
  if (v == null) {
    // Error: Type 'unknown' is not assignable to type 'null | undefined'.
    nullOrUndefined = v;
  }
}
```

A more practical use-case for the narrowing would be something like this:

```ts
if (typeof v === 'string' || v == null) {
  // v should be `string | null | undefined` in here.
  if (v) {
    // v is a non-empty string
    doSearch(v);
  } else {
    // v is empty string, null, or undefined
    clearSearch();
  }
}
```

**Expected behavior:**

`v == null` narrows an `unknown` type to `null | undefined`, same as `v === null || v === undefined` does.

Reading [the ECMAScript spec on `==`](http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3), I believe that `== null` will guarantee that the value is either null or undefined. `== undefined` would do the same thing, though linters generally prefer the shorter `== null`.

**Actual behavior:**

Compile error:
```text
src/index.ts:11:5 - error TS2322: Type 'unknown' is not assignable to type 'null | undefined'.
  Type 'unknown' is not assignable to type 'null'.

11     nullOrUndefined = v;
       ~~~~~~~~~~~~~~~

Found 1 error.
```

**Playground Link:** https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVxsAZxgAoA3ALjlQGsUIB3FASjgG8AoOOAG2HhSTduAeSgBVFABNgCTCmCTKAoXAA+VKTLkKA3JziYEcMnAC85uMu5r1pMxdTTZ8ySw5cuAek9wAKgAtMAjh6aGoCADp9LitRCSdtSTM4Uj0uAF99Q2M7Cys3aLhvPwBPMGA4AHIaOkZKg2C6eABDAgJMAHMUZoAjXjwIPDKKyqs1DQSXSqiPS0ERcU1nBWTU-UzMoA

**Related Issues:**

* Triple-equal narrowing of `unknown` was added in https://github.com/microsoft/TypeScript/pull/26941
  * The PR specifically noted "Does not work with == because we would need to consider coercion rules."
  * That's true for the general case. Thankfully, the behavior of `== null` is well-defined and can be special-cased.
* There's a general issue https://github.com/microsoft/TypeScript/issues/25720 open for better narrowing of `unknown`.

**Comment by ericyhwang** [comment]
I'd be interested in submitting a PR for this, by the way.

Looking at checker.ts, `narrowTypeByEquality` already has handling for `== null`. Without having cloned down the code for testing, my guess: Perhaps `getTypeWithFacts` might not be narrowing down `unknown` based on `TypeFacts.EQUndefinedOrNull`?

**Comment by jack-williams** [comment]
@ericyhwang I think looking at the changes associated with #26941 is a good place to start—-that added a new code path for unknown and `===`. The right fix might be to split the code path for `===` and `==`.

**Comment by jack-williams** [comment]
@ericyhwang Are you working on this? I think it's a relatively simple fix, but it would also be nice for you to get a contributor badge.

Do you want to sketch out the solution here together and then you can open a PR?

**Comment by ericyhwang** [comment]
@jack-williams Ah, I thought bugs needed a help-wanted label first. Haven't started beyond initially looking at the code.

I'm still interested, though I may not have work-week time for a few weeks. If it's pretty simple, I might treat it like a mini weekend project and do it on my own time.

**Comment by jack-williams** [comment]
Oh yeah, forgot about that label. Well I'm sure @RyanCavanaugh would be happy to accept a PR on this given that it's on the backlog.

I'll leave it in your hands, but if you have any Q's just drop them in this issue.

**Comment by lkho** [comment]
hi everyone, I faced this same compilation error TS2322 (without strictNullChecks)

**Playground:**
https://www.typescriptlang.org/play/?strictNullChecks=false&ts=3.8-Beta#code/GYVwdgxgLglg9mABMAjACgB4C5EGcoBOMYA5gJQ5ggC2ARgKYGIDeAUIojMIpogLx9EVADbCyLdh0QF6UEASQYA3JIC+kmXIVCQoletahIsBMgBMmHPiKlEAHx2iKj4RI5ceGfgJfi2U6Vl5RRUOdQ5NYJd9ViA

Is it the same problem discussing in this thread?

Compilation error:
line 3:
```
(parameter) x: string
Type 'string' is not assignable to type 'number'.(2322)
```
line 10:
```
(parameter) x: string
Type 'string' is not assignable to type 'null'.(2322)
```

However, I saw from the AST viewer, both computed type of `x` at line 3 is `never` and line 10 is `null`, which are both correct (if strictNullChecks).
