### ISSUE TITLE
Empty interface extending type can give incorrect field type

### ISSUE THREAD

**Issue by KnutRyagerInmeta** [microsoft/TypeScript#32790]
It seems the field "name" has been resolved to BOTH number and string in my "Named" interface...

![image](https://user-images.githubusercontent.com/51314518/62811302-74c5eb00-bb01-11e9-97e8-718dfcf38035.png)

```
type AllPropsTo<K extends keyof any, T> = { [P in K]: T };

type AllPropsAre<T> = AllPropsTo<any, T>;

type AllNumberNamed = Omit<AllPropsAre<number>, 'name'> & { name: string };

interface Named extends AllNumberNamed {}
```

**Comment by RyanCavanaugh** [comment]
Please don't post text as a screenshot. It excludes people who need assistive technologies, and generates a lot of work for us in typing in code from an image.

It doesn't appear that this is a bug.

**Comment by KnutRyagerInmeta** [comment]
But what is the name property really resoved to? appears to be string for AllNumberNamed, yet number for Named.

**Comment by KnutRyagerInmeta** [comment]
I tried another approach, seems it just won't work if "any" is involved.

```
type AllNumberNamed2<T> = {
  [P in keyof T]: P extends 'name' ? string : number
};

const allNumberNamed2 = {} as AllNumberNamed2<any>;
allNumberNamed2.name = '';  // error: name is string
allNumberNamed2.n = 2; // works fine

type AllNumberNamedLimited = { n: number; name: number };
const allNumberLimited = {} as AllNumberNamed2<AllNumberNamedLimited>;
allNumberLimited.name = ''; // works fine
allNumberLimited.n = 2; // works fine
```

**Comment by jack-williams** [comment]
@RyanCavanaugh Sorry to hijack the thread. Regarding:

> Please don't post screenshots without also including the code as text in the report. *It excludes people who need assistive technologies, and generates a lot of work for us in typing in code from an image.*

Is this in the issue template? If not, I think it should be. IMO it’s good to remind everyone to make issues as accessible as possible, particularly in areas I think many of us take for granted.
