### ISSUE TITLE
JS Autocomplete does not work correctly when assigning into "this"

### ISSUE THREAD

**Issue by thecatontheflat** [microsoft/TypeScript#32806]
- VSCode Version: Version 1.36.1 (1.36.1)
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:
1. Create the following files:

**a.js**
```
import B from "./b";

class A {
    classPropB;
    constructor() {
        const localVarB = new B();
        this.classPropB = new B();

        
    }
}
```

**b.js**
```
export default class B {
    doSomething() {
        console.log('done');
    }
}
```

2. Go to **a.js** and start typing `localVarB.` — you can see correct autocomplete suggestions
3. Go to **a.js** and start typing `this.classPropB.` — autocomplete is not working

4. See screenshots with details:

![Screenshot 2019-07-29 at 15 30 21](https://user-images.githubusercontent.com/727581/62052482-d3dc5380-b215-11e9-9809-8a518d456472.jpg)

![Screenshot 2019-07-29 at 15 30 28](https://user-images.githubusercontent.com/727581/62052490-d76fda80-b215-11e9-85d0-bb4b0835dae8.jpg)

**Comment by IllusionMH** [comment]
It should provide proper suggestions if you explicitly declare type of `classPropB`
```ts
class A {
    classPropB: B; // otherwise it has type `any`
    constructor() {
        const localVarB = new B();
        this.classPropB = new B();
    }
}
```

http://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEBC0G8BQ1XQCYHsDKmC2ApgC4AWAlgHYDmAFAJSIprPCYUSYgEB0ImtAciwUCAugG4mqAL5JZSUJBgBBRi3BQACgCdMAB1gAuOJJZsIRbQFdgRTNvprmaVuyLQ+wMCABqYbfAAvNAiAO5w9KbOqKRkENyKWroG0MFhERJIUs6x8YkQOvqw3Nmy8vnQAPLaZFSU3qrI6kqFBuLQAPQd0ACyBHgARgTa0AL5rbAC0GR4eiBkwGREIACe0CSQ0GAUo9srU0QrejzQoUsk0AAGFJgAkrPzi0TKFCuX0AQUYANc6NmuFmstnsjia0WgAPcnm8fgCqRCBHCsEi2WYuQSGgKySCCKRKNRaHR42xJWYZSAA

**Comment by RyanCavanaugh** [comment]
`classPropB;` has the inferred type `any` because it has no initializer and no JS Doc annotation, and we don't show completions on `any` (nor narrow their type to a more specific one after an assignment)

**Comment by IllusionMH** [comment]
Opps, in JS files it should be `@type` JSDoc

```js
class A {
     /** @type {B} */
    classPropB;
    constructor() {
        const localVarB = new B();
        this.classPropB = new B();
    }
}
```
