### ISSUE TITLE
Typescript engine

### ISSUE THREAD

**Issue by nocord** [microsoft/TypeScript#32800]
Implement a Typescript engine

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/32780

**Comment by AnyhowStep** [comment]
```ts
class Engine {
  start () {
    console.log("Vroom!");
  }
}
```

**Comment by nocord** [comment]
Microsoft people aren't good

**Comment by trusktr** [comment]
Ok, that's just rude.

But anyways, TypeScript engine: https://github.com/denoland/deno

**Comment by nocord** [comment]
@MartinJohns, stop laughing

**Comment by RyanCavanaugh** [comment]
@nocord you've been banned from GitHub already under the 'catastrop' name and now you're back doing the same thing. Your behavior toward maintainers across the entire GitHub site is not constructive or helpful and needs to stop.
