### ISSUE TITLE
Default documentation page is broken

### ISSUE THREAD

**Issue by Damag3d** [microsoft/TypeScript#32805]
Link is broken - probably redirect issue at front door/cdn level:

[home](http://www.typescriptlang.org/docs/home.html)

Result: 
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by bysdxt** [comment]
same result,but in chinese

**Comment by LordJohn42** [comment]
same

**Comment by gaborluk** [comment]
Temporary workaround:

1. Navigate to https://www.typescriptlang.org/docs/index.html.
2. During a brief flash of content preceding the redirect to .../home.html, stop loading the page (by pressing `Esc` or clicking the ✖️ in your browser toolbar).

**Comment by gezeta-id** [comment]
You can also, as a temporary workaround, access some page of the handbook directly, like https://www.typescriptlang.org/docs/handbook/basic-types.html and then just avoid clicking on the link to the documentation index.

**Comment by fatcerberus** [comment]
Seems to be working now.  Looks like maybe they fixed it?

**Comment by RyanCavanaugh** [comment]
@orta any idea what happened?

**Comment by orta** [comment]
Ah yeah, I was tracking it on the website repo https://github.com/microsoft/TypeScript-Website/issues/42 - I deployed from a new computer, so I fixed it by deploying from the old one. Not diagnosed what specifically made that page not show up, it worked when I did a local dev server. 

I'll aim to move the entire deployment pipeline to run on CI so that it's can't happen again

**Comment by orta** [comment]
With https://github.com/microsoft/TypeScript-Website/pull/56 and subsequent commits to get it actually working, the website is now being deployed entirely by GitHub Actions 👍

**Comment by orta** [comment]
Ironically enough, the GitHub Actions deploy has the same bug which started this entire thing too - [the index](http://testsite-typescript-41eeb979-7eaa-4c74-9d47-9d182c7b61ab.azurewebsites.net/docs/home.html)

**Comment by orta** [comment]
Looks like that page didn't make it through the migration to the OSS repo, not sure how but it exists on the [private repo from before](https://github.com/microsoft/TypeScript-Website/tree/archived/src/_docs) - which makes this an easy fix.
