### ISSUE TITLE
Documentation unavailable

### ISSUE THREAD

**Issue by MartinJohns** [microsoft/TypeScript#32810]
**TypeScript Version:**  irrelevant - it's about the website

**Search Terms:** documentation unavailable

**Steps to reproduce:**

- Navigate to http://www.typescriptlang.org/
- Click on "Documentaton" in the navigation

**Expected behavior:**

I can read the documentation.

**Actual behavior:**

I get redirected to http://www.typescriptlang.org/docs/home.html, and here I get this error:

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Related Issues:** #31983

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/32805

**Comment by MartinJohns** [comment]
Closed as duplicate. 👍 Sometimes I'm blind.
