### ISSUE TITLE
Support readonly types with inference

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript#32812]
## Search Terms

readonly without type

## Suggestion

Today, in order to use a readonly type with inference you need to know `typeof` exists

```ts
const user = {
  name: "orta"
}

const readonlyUsers: readonly typeof user[] = [user] 
```

It would be nice to support shorthand syntax for this:

```ts
const user = {
  name: "orta"
}

const readonlyUsers: readonly = [user] 
```

Where the lack of a definition outside of `readonly` implies you want to keep the inferred type.

## Use Cases

Making it cheaper syntactically to use `readonly` more often without using _slightly_ more esoteric typescript features.

Could be negated by these though:

- https://github.com/microsoft/TypeScript/issues/32758
- https://github.com/microsoft/TypeScript/issues/32467

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Can you compare and contrast with how `as const` doesn't address this use case?

**Comment by jack-williams** [comment]
From the PR that added `readonly` (#29435) there was a question about the behaviour of types called `readonly` [here](https://github.com/microsoft/TypeScript/pull/29435#issuecomment-459381841). The following used to compile, but does not currently:
```ts
type readonly = string;
const q: readonly = 'hello';
```

I think there was a plan to fix this, but maybe though would need to be reviewed in light of this proposal.

**Comment by orta** [comment]
Hrm great point - I actually can't think of any reason why `as const` doesn't cover this other than for the exact case I was looking at (which was to show a particular error message )

I'm fine with this being considered closed 👍

**Comment by RyanCavanaugh** [comment]
As an aside I think we're happy with `readonly` being (unintentionally?) reserved for the time being - who knows what we might want with it later.
