### ISSUE TITLE
Typescript doesn't recognize type of rest variable

### ISSUE THREAD

**Issue by dragozin** [microsoft/TypeScript#32815]
**TypeScript Version:**  3.4.5

**Search Terms:**
Spread object typescript error
**Code**

```ts
function pick<T>(myArg: { myProp: boolean } & T): T {
    const { myProp, ...rest } = myArg;

    return rest;
}
```

**Expected behavior:**
there are no errors
**Actual behavior:**
Error: 
```
Type 'Pick<{ myProp: boolean; } & T, Exclude<keyof T, "myProp">>' is not assignable to type 'T'
```
**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Yep, good point
