### ISSUE TITLE
Organize Imports CLI command

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#32818]
https://github.com/microsoft/vscode/issues/78839

## Suggestion

Organize imports is a nice editor feature for VSCode, but if we start using it as an organization, we'll need to enforce that everyone is using it. 
- We need to be able to run this command on all files in our CI, otherwise people will fall out of sync. 
- People using other editors need to be able to run this command.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Could be implemented as a community tool today, but we should think about this use case as part of our longer-term thinking on LS tooling from the commandline

**Comment by weswigham** [comment]
cc @rbuckton related to the extension API: I think if we have one, we really shouldn't have separate tsc/service layers, if it can be avoided, and this is a mark towards moving everything towards the services-included model (so if that has perf issues, we should start fixing them!).

**Comment by thorn0** [comment]
see https://www.npmjs.com/package/organize-imports-cli

**Comment by ccorcos** [comment]
Thanks @thorn0 🎉
