### ISSUE TITLE
Assignment fails for types with conditional lookup for a union of a generic

### ISSUE THREAD

**Issue by smoogly** [microsoft/TypeScript#32816]
**TypeScript Version:**  Version 3.6.0-dev.20190810

**Search Terms:** union conditional lookup 

**Code**

```ts
type Target<T> = T extends null ? null : T;
type Target2<T> = { "one": null, "two": T }[T extends null ? "one" : "two"];
type Target3<T> = [null, T][T extends null ? 0 : 1];

function tst<T extends string>() {
    // These two pass as expected:
    const case0: Target2<T | null> = 1 as any as Target2<T | null>;
    const case1: { prop: Target<T | null> } = 1 as any as { prop: Target<T | null> };
    const case2: { prop: Target2<T> } = 1 as any as { prop: Target2<T> };
    const case3: { prop: Target3<T> } = 1 as any as { prop: Target3<T> };

    // These two fail as expected:
    const case4: { prop: Target2<T> } = 1 as any as { prop: Target2<T | null> };
    const case5: { prop: Target3<T> } = 1 as any as { prop: Target3<T | null> };

    // These two are expected to pass, but fail:
    const case6: { prop: Target2<T | null> } = 1 as any as { prop: Target2<T | null> };
    const case7: { prop: Target3<T | null> } = 1 as any as { prop: Target3<T | null> };
}
```

**Expected behavior:**
Expected cases 6 and 7 to pass, as both sides of assignment supposed to be structurally identical.

**Actual behavior:**
Cases 6 and 7 fail. Example output:
```
error TS2719: Type '{ prop: { "one": null; "two": T | null; }["one" | (T extends null ? "one" : "two")]; }' is not assignable to type '{ prop: { "one": null; "two": T | null; }["one" | (T extends null ? "one" : "two")]; }'. Two different types with this name exist, but they are unrelated.
  Types of property 'prop' are incompatible.
    Type '{ "one": null; "two": T | null; }[T extends null ? "one" : "two"] | null' is not assignable to type 'null & { "one": null; "two": T | null; }[T extends null ? "one" : "two"]'.
      Type '{ "one": null; "two": T | null; }[T extends null ? "one" : "two"]' is not assignable to type 'null & { "one": null; "two": T | null; }[T extends null ? "one" : "two"]'.
        Type 'T | null' is not assignable to type 'null & { "one": null; "two": T | null; }[T extends null ? "one" : "two"]'.
          Type 'T' is not assignable to type 'null & { "one": null; "two": T | null; }[T extends null ? "one" : "two"]'.
            Type 'string' is not assignable to type 'null & { "one": null; "two": T | null; }[T extends null ? "one" : "two"]'.
              Type 'string' is not assignable to type 'null'.
                Type 'T' is not assignable to type 'null'.
                  Type '{ "one": null; "two": T | null; }[T extends null ? "one" : "two"]' is not assignable to type 'null'.
                    Type 'T | null' is not assignable to type 'null'.
                      Type 'T' is not assignable to type 'null'.
                        Type 'string' is not assignable to type 'null'.
```

[**Playground Link**](https://www.typescriptlang.org/play/#code/C4TwDgpgBAKghgJwOYWAHhgPigXllCAD2AgDsATAZylIFcAbeqAfhoaYC5YBuAKFEixEKYACYM2PAG8oAIgD2pCLK51GAGjnAA7vJX4AvgG0YBYmSptGLOYuVQusnXoC6fAdHjJUAZgm4oIzV6TRgXEzMSCmpgmwAGBygARjdeXgAzWlIAY2AAS0UoYEp0UyIoyxKEPNIkTAAKAEooKV4odqgAek7YAAsISmhnKDA4Smoxs0hciHIONo7sxRKobLGIOK4vEXFTAB8reklkqEm4UhBT6m3UXagD4Mw+DtXl4FX1pK4ZMAR5MC2wlQGHuh2wBgCSSupwu0J+fwBQm8pVBjygBmeizeH0Gom+IwRgORu3BkOh50uk3h-yJO38GIW7SWpBWa0GPnxvxpSJEfiw6LJZ1hVIJ3JuwD54L4jK6PRg-UGRV0UHScDyTEmRGmJDmMuZrPWABZOYSebd6YKJsLqNTEeK7g92FK9di2RAAKwmsVAiUWvBQoWUm2iu0+vmop3o6Uvbp9AZDZWIaBaiAzchFeQjMaUTQAI1o71V6vmL317zdADYvaHiSDHYxSf7ydaWiHaeb9mCoy6WeX1gB2avt32dtEQpuBuFts0jiMN7sGXhAA)

**Related Issues:** #30152 looks similar

**Comment by AnyhowStep** [comment]
Feels *a little bit* like this https://github.com/microsoft/TypeScript/issues/32442

Except yours does not use function params.

**Comment by jack-williams** [comment]
This is a consequence of #30769 and fundamentally the same issue as discussed in #31833, however the trigger is slightly different.

The constraint of the distributive conditional type `T extends null ? "one" : "two"` is `"one" | (T extends null ? "one" : "two")` as the conditional distributes over the constraint. The union key causes the index access type in the target type to simplify to an intersection (despite the property never being assigned), as per #30769.
