### ISSUE TITLE
Semicolon detection not used for the `add missing super call` quick fix

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#32832]
**TypeScript Version:**  3.6.0-dev.20190810

**Search Terms:**
- semicolon
- quick fix
- code actions

**Code**

For the code

```ts
console.log(1)
console.log(2)
console.log(3)
console.log(4)
console.log(5)
console.log(6)

class A {}

class B extends A {
    constructor() {}
}
```

1. Trigger the quick fix in `B` for adding the missing super call

**Expected behavior:**
The added `super()` call should not have a semicolon. This is because the `console.log` statement expression at the start of the file do not have semicolons

**Actual behavior:**
The quick fix does include a semicolon:

```ks
class B extends A {
    constructor() {
        super();
    }
}
```

**Comment by DanielRosenwasser** [comment]
All of the "dumb" code actions that do string insertion instead of using factory functions will need to be adjusted.

**Comment by geppy** [comment]
This is working now (with `3.7.0-dev.20191015`, and with my local checkout).

**Comment by mjbvz** [comment]
Tested in 3.8.3 and also confirmed this is now fixed
