### ISSUE TITLE
instartlogic

### ISSUE THREAD

**Issue by gvaitheeswaran** [Microsoft/TypeScript#3284]
Please fill the following out:

- Name: instartlogic
- Homepage url: www.instartlogic.com
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: http://www.instartlogic.com/sites/all/themes/big01Theme/logo.png
![logo](https://cloud.githubusercontent.com/assets/5490836/7844365/bc5e2a66-0464-11e5-9837-04a53063b84c.png)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by jonathandturner** [comment]
Added.
