### ISSUE TITLE
Provide a better error message for "used before defined" on incorrectly annotated functions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#32846]
Based on #32836.

```ts
declare let cond: boolean;
let f: () => void | undefined;

if (cond) {
  f = () => { };
}

if (f) {
  f();
}
```

We should error here, but because `f` is

* annotated as a function that
* returns a union
* where the last constituent of the union is `undefined`

we should give a related span like

```
Did you mean to parenthesize this function type?
```

that only covers the beginning of the function type up until the end of the 2nd-to-last union constituent. e.g.

```
let f: () => void | undefined;
       ~~~~~~~~~~
Did you mean to parenthesize this function type?
```

**Comment by DiamondYuan** [comment]
I want to give it a try.

**Comment by Hardik500** [comment]
Can you please tell me in which folder the files should be edited?

**Comment by DanielRosenwasser** [comment]
`diagnosticMessages.json` is the place to add new errors, `checker.ts` is the place to issue that error.

**Comment by OzairP** [comment]
I'll take this, I have a prototype working on my machine locally.

**Comment by sterlingfs** [comment]
@DanielRosenwasser I wasn't able to pass checks due to this error in checker.ts....

![image](https://user-images.githubusercontent.com/5101692/64039216-1bf9d900-cb28-11e9-841e-15d79d3bc11c.png)

It seems like a simple fix. Can I fix it by adding the quotes?

**Comment by DanielRosenwasser** [comment]
Yes, the properties change based on the text.

**Comment by m-henderson** [comment]
@sterlingfs if the messages are updated in the diagnostics then you will need to reference the new message in checker.ts

**Comment by DanielRosenwasser** [comment]
Thanks @OzairP!
