### ISSUE TITLE
Do not strip end of file newlines in emit

### ISSUE THREAD

**Issue by uber5001** [microsoft/TypeScript#3287]
When using `tsc`, every file output does not have a newline at the end of the file. Is this intended? If so, it would be nice to have a flag to change this behavior.

**Comment by danquirk** [comment]
To what end? Can you not put newlines at the end of your source files if there's some need for this in your toolchain? Or are you saying your EOF newlines are getting removed?

**Comment by uber5001** [comment]
The original typescript files are formatted with newlines before EOF, and the output es5 files do not.

**Comment by RyanCavanaugh** [comment]
Happy to take a PR that patches this up

**Comment by jakebailey** [comment]
Just looking at old issues; I tested the emitter on inputs without a trailing newline all the way back to 0.8 and every version has added a trailing newline, so I'm pretty sure this is not a problem (and maybe never was). But if this really is still happening, happy to reopen.
