### ISSUE TITLE
Type error breaks contextual typing down the road

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#32889]
**TypeScript Version:**  3.5.2, 3.6.0-dev.20190814

**Search Terms:**

I had this strange case where a type error in one place can cause even more errors in seemingly unrelated places. It seems to be related to contextual typing:

**Code**

```ts
declare function getThing(param: string): string[];

function invoke(param: number) {
    return getThing(param); // type of argument doesn't match
}

invoke(1).map((e) => e) // 'e' implicitly has type 'any'
```

Hovering over `invoke` and `map` shows the correct inferred types.

**Expected behavior:**

There should be only one error at the call of `getThing`. `e` should be inferred as `string`.

**Actual behavior:**

`e` is not contextually typed, causing an noImplicitAny error.
If you fix the type of `param` both errors are gone.

So either the types displayed in QuickInfo (and completion lists) are wrong/misleading or something is affecting contextual typing.

**Playground Link:** https://typescript-play.js.org/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMAVACy1QIAoAHWKAWwC54BnDGSggSlY65UA2gF0A3ACgJKdNjzxKANxwBrEHQYt4qZIwBGIGD3gBvCfAvw4GZDHxFSFKhphMeY+AHpP8DAE9aBBxEeFgCXRBUDHhgHBA2VAByaMYoDDAyCQBfKSVVdQBGHgA6VNpqahBjAF4APngqrx9EkESFRloILDAsDAg-eDIoNl8AhESoVD9EoA

**Related Issues:**

**Comment by AnyhowStep** [comment]
Nice short repro!
I've experienced this too many times but never bothered to file it because the problem goes away after fixing the error

**Comment by AlCalzone** [comment]
I think this might be the issue for this strange beast:
![grafik](https://user-images.githubusercontent.com/17641229/63881593-7718b800-c9d0-11e9-833c-9f0060e0b2a3.png)
https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEEQBd4DMD2GBc8CuAdgNYEYDuBA3AFBgYEDOqAblBHiA-ALzwDyAIwBW4ZADoiIAJ4MAFJgwBKavFXwxAWygAHWdtgMQASQLJla9WgCWEZCBizWEHgD54AQgByeDQPtirBk8oT0c2RUVKIA

**Comment by RyanCavanaugh** [comment]
Works now
