### ISSUE TITLE
Forbid simultaneous `noEmit` and `incremental`

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#32882]
`noEmit` stops us from emitting any files (both bundle info and declarations). `incremental` needs both of those. When both are set together today, all it does is force on declaration emit and then discard all the extra work done. As such, using the two together should trigger an error.

Related: #30661

**Comment by RyanCavanaugh** [comment]
Should we just roll this up into the other bug?

**Comment by weswigham** [comment]
Maybe? That one had opinions like "we should emit the bundle info path if a path is expressly given" - I'd just like to see an error if these two options are simultaneously specified right now, as it definitely doesn't do what you want.

**Comment by sheetalkamat** [comment]
#33883 reverted the fix so this needs to be re opened

**Comment by sheetalkamat** [comment]
I am not sure if we want to do this or not.. Given that older vs versions will still use `--noEmit --listFiles` as part of build. I am not sure if distinguishing `listFiles` as special option is good or bad.

**Comment by sheetalkamat** [comment]
cc: @RyanCavanaugh @DanielRosenwasser @uniqueiniquity @amcasey @minestarks to chime in what we should do here..

**Comment by amcasey** [comment]
I frequently get confused about how this works (so @uniqueiniquity can correct me), but I think the msbuild code that passes those flags is rev'd with the compiler so there's no danger of running a new compiler (i.e. one that will warn/error) with an old build task/target (i.e. one that will trigger the warning/error).

**Comment by sheetalkamat** [comment]
Thanks.. Will add this fix then
