### ISSUE TITLE
Constrain inferred types in return type positions of type guards

### ISSUE THREAD

**Issue by jscheiny** [microsoft/TypeScript#32894]
## Search Terms

infer type guard generic conditional

## Suggestion

When using the `infer` keyword in the predicate position of a type guard, the inferred type should be constrained by the type of the variable upon which it is predicated.

## Use Cases

Recently ran into a case where we extended a simple type and wanted to extend an object of corresponding type guards to allow passing in this new type:

```ts
type MyType = "A" | "B" | "C";
type MyExtendedType = MyType | "D";

type ExtendGuards<T> = {
    [K in keyof T]:
        T[K] extends (value: MyType) => value is infer U
            ? (value: MyExtendedType) => value is U
            : T[K]
};
```
[See in playground](http://www.typescriptlang.org/play/#code/C4TwDgpgBAsiAq5oF4oCICCaoB90CFs80BhNAbgChRJYQBRAD2AgDsATCdxW1OH6MQAiFStSRQmLDgHEArgEMATuwDOAHngA+KKgDelKEagBtANJQAlqygBrCCAD2AMyjwAugC5Dx3-HPuUBDMbGpQABQAbgoANnIQnnQCAJS6OtFx0JaqVqzOEEpQAKo+vmVQAPwRGfGJcFKhXClpUDVZOSXl5Yn+Zu6UAL5UQA)

Currently this produces an error both on `infer U` and on its usage on the following line:

```
A type predicate's type must be assignable to its parameter's type.
  Type 'U' is not assignable to type 'MyType'.
    Type 'U' is not assignable to type '"C"'.
```

It seems that it should only be possible to extend this type guard if `U` extends `MyType`, so it should probably just be constrained by that by default.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
#32093?

**Comment by jscheiny** [comment]
Yup, that sounds like that should cover this issue, thanks!
