### ISSUE TITLE
Generic class's type param `T` errors if class contains a `keyof T` method

### ISSUE THREAD

**Issue by jorroll** [microsoft/TypeScript#32907]
**TypeScript Version:**  3.5.1

**Search Terms:**

error property is missing in type but required in type 

**Code**

```ts
class FormA<T extends { [key: string]: any }> {
  constructor(public value: T) {}
}

function testA(input: FormA<{ [key: string]: any }>) {}

// works as expected
testA(new FormA({one: 'two'}));

class FormB<T extends { [key: string]: any }> {
  constructor(public value: T) {}

  get(key: keyof T) {
    return this.value[key];
  }
}

function testB(input: FormB<{ [key: string]: any }>) {}

// Error!
// Argument of type 'FormB<{ one: string; }>' is not assignable to parameter of type 'FormB<{ [key: string]: any; }>'.
//  Property 'one' is missing in type '{ [key: string]: any; }' but required in type '{ one: string; }'.ts(2345)
testB(new FormB({one: 'two'}));
```

**Expected behavior:**

No error for `testB()`

**Actual behavior:**

Error for `testB()`

**Playground Link:** 

https://www.typescriptlang.org/play/#code/MYGwhgzhAEBiD2AnAtgQQDwBVoFMAeALjgHYAmMA3tANoDWOAngFzQQGICWxA5gLothiDaAF8AfNAoAoaNGDxibRAFdgBJAAoADsoBGIDsGgA3MCGU4WmAJSSRU+1IBmy4mo4LoRNqg1cdBCwIKBhUdIwsSlx8AkKiYrYUjt4EvsQ4AO5wSGgaFAqW0ADkBBnwRSLW1gDcUlKgkDDByABCWLiEJOSSNPTMrOzR-NCCwuKSMnIKSqrqiNp6Bkam5oU2dnWy3DgEGn0sffBO0OvSsrKIO8qIxF4AFhwQAHQrFuEMvLWy9o4ubgQeW4pFp+YgBII5NphfYDTg8YajeKJZI4Ngg9JZZog-LpFglMoVKq1IA

**Possibly Related Issues:** 

#32311

**Comment by thefliik** [comment]
Changing `FormB` to

```ts
class FormB<T extends { [key: string]: any }> {
  constructor(public value: T) {}

  get<K extends keyof T>(key: K) {
    return this.value[key];
  }
}

function testB(input: FormB<{ [key: string]: any }>) {}

testB(new FormB({one: 'two'}));
```

works as expected

**Comment by RyanCavanaugh** [comment]
When a class refers to `keyof T`, the correct variance measurement for `T` is contravariant (or invariant if `T` elsewhere has a covariant usage).

While it's not the code you wrote, the type system doesn't have any way to distinguish it from code like this, which is unsound:
```ts
class Foo<T> {
    key!: keyof T;
    constructor(public value: T) { }

    setKey(k: keyof T) {
        this.key = k;
    }

    getValue() {
        return this.value[this.key];
  }
}

function read(k: Foo<{ a: string }>) {
    // Unsound: value of type 'number' inhabits variable of type 'string'
    const s: string = k.getValue();
}

const ab = new Foo({a: "", b: 10});
ab.setKey("b");
read(ab);
```

**Comment by RyanCavanaugh** [comment]
Tagging Design Limitation only because we don't have a way to indicate or infer that this codepath *doesn't* happen in an actual class body (though, due to inheritance, we can never really disavow it)

**Comment by thefliik** [comment]
👍  Luckily, the workaround for this specific example is easy (`get<K extends keyof T>(key: K)`).

> While it's not the code you wrote, the type system doesn't have any way to distinguish it from code like this, which is unsound

Gotcha. And so an error is being raised because the type system isn't sure if the code is unsound or not (and so it's erroring on the side of caution)? Thanks for the background information ❤️
