### ISSUE TITLE
Don't let the declaration file break compilation

### ISSUE THREAD

**Issue by John0King** [microsoft/TypeScript#32908]
## Suggestion

Don't let the declaration file break compilation

## Use Cases

if you write a declaration file that use  `--nolib`, and others has duplicate global class name, 
or a package depends on  package depA,  then package depA  interface name has been renamed , then your app won't compile.

The unknowed type in .d.ts should map to `any`,  and show a warning instead of error

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
This would mean misspelled type names would resolve to `unknown` or `any` or whatever, which is undesirable. Consider adding a `:+1:` to #31894 which would allow you to state that some type name exists without knowing specifics about the implementation.

**Comment by John0King** [comment]
@DanielRosenwasser  I think #31894 is not for this case , 
What I want to  avoid is  declaration file error , declaration file normally from third party, and thire some case you app compile fine ,  your used third party declaration is compiled file,  but it'll error when you add the declaration to your app.
yes I can edit the downloaded declaration but it's from npm so next time you download from network  it won't compile again.

I think Typescipt should distinguish between source file and declaration file .  source file can not have error , but declaration file  can be tread like js （as long as it won't contains syntext error）

**Comment by John0King** [comment]
@DanielRosenwasser  I added a demo to show how this happend ,  it does not happend in your own source code , it happend when  multiple declarion library been merge to your project.
should this  be reopen ?

**Comment by fatcerberus** [comment]
Have you tried `--skipLibCheck`?

**Comment by John0King** [comment]
@fatcerberus   cool,  it solve my problem 😜 . Thanks.
I never notice this options before
