### ISSUE TITLE
vscode intellisense for node_modules packages is truncated at deep level 2 in nodejs project

### ISSUE THREAD

**Issue by tomasruizr** [microsoft/TypeScript#32906]
I have a javascript project with around 7 levels of depth de module.exports object.. something like
```javascript
levels.l1.l2.l3.l4.l5.l6.l7 = 'some value'
````
When working in that codebase the intellisense works like a charm, but when installing the dependency from another project with npm the intellisense gets truncated at level 2. Something like
```javascript
levels.l1.l2. ???
````
I found out about `jsconfig.json`file at the root of the project with a `compilerOptions.maxNodeModuleJSDepth` with no luck.

this is an example of the file I am using
```
{
  "compilerOptions": {
    "maxNodeModuleJsDepth": 10
  },
  "include": [
      "node_modules/my-deep-package"
  ]
}
```

Is there something that I can do to get that intellisense for the package when is in the node_modules?

Thanks

**Comment by mjbvz** [comment]
@tomasruizr or @codycuellar Do you have a small example project you could share that demonstrates this issue?

**Comment by codycuellar** [comment]
Create a fresh NPM project, then extract this .tgz and `npm link` it, then `npm link intellisense-jsdoc` in your other new project. Everything should work correctly. Then from your new project, `npm install /path/to/intellisense-jsdoc-1.0.0.tar.gz` from the other project and it should stop working.

[intellisense-jsdoc-1.0.0.tar.gz](https://github.com/microsoft/TypeScript/files/3571639/intellisense-jsdoc-1.0.0.tar.gz)

**Comment by RyanCavanaugh** [comment]
We haven't seen any other reports of this - either this is fixed, or very very niche. Please open a new standalone issue if you're seeing this on recent builds. Thanks!
