### ISSUE TITLE
removeEventListener not allow to pass passive option

### ISSUE THREAD

**Issue by vkrbt** [microsoft/TypeScript#32912]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
function listener() {
}

window.addEventListener('scroll', listener, {passive: true});
window.removeEventListener('scroll', listener, {passive: true});
                                                ^^^^^^^^^^^^^
```

**Expected behavior:**
`passive` can be provided to `removeEventListener`

**Actual behavior:**
`passive` can not be provided to `removeEventListener`

**Playground Link:** 
https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAGxgZygUzJgTgCgEpEBvAKAF8yyB3GMAEzhoDoBDBhgUQDdsoAMuiw4CAcjQRccZMjEAaFMOx5FJAA5s0aGHwBciKLhCYKhANy16TVrkwBbOH178hGFeMnTZCpe9Fqmtq6mAZGJmbmQA

**Related Issues:** 
#14196

**Comment by nmain** [comment]
This is correct.  Relevant spec:

https://dom.spec.whatwg.org/#dom-eventtarget-removeeventlistener

The only thing in `options` is `capture`.

MDN explains what's going on in more detail:

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#Matching_event_listeners_for_removal

**Comment by fatcerberus** [comment]
However, note that the MDN page also says this:
> It's worth noting that some browser releases have been inconsistent on this, and unless you have specific reasons otherwise, it's probably wise to use the same values used for the call to addEventListener() when calling removeEventListener().

The types are preventing that recommendation from being followed.

**Comment by RyanCavanaugh** [comment]
Types generally don't account for needing to work around browser bugs by passing invalid options around. Anyway if you want to pass the same *object* to both things (instead of writing the same thing twice and hoping they stay in sync, which seems extremely error prone):
```ts
// No error
const opts: AddEventListenerOptions & EventListenerOptions = { passive: true };
window.addEventListener('scroll', listener, opts);
window.removeEventListener('scroll', listener, opts);
```
