### ISSUE TITLE
Can't infer `void` from 0-arity function

### ISSUE THREAD

**Issue by goodmind** [microsoft/TypeScript#32915]
**TypeScript Version:**  3.7.0-dev.20190815

**Search Terms:** void, inference, mixed, unknown, arity, 0-arity, function

**Code**

```ts
export declare function infer<Params, Done, Fail = Error>(
  handler?: (params: Params) => any
): (params: Params) => void;

const f = infer(() => {});

f();
```

**Expected behavior:**

```
No errors!
```

**Actual behavior:**

```
Expected 1 arguments, but got 0. ts(2554)
```

**Playground Link:** [Link](http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAE2AYwDYEMrDgMwK4B2yMAlhAXCQTsFADwAKm6AtgM4A0cAIucFwDF0JVHAC8cAKJQo0AHwAKALAAoOHAAW6AglS0A-AC44CsM3bGmUVmwCU4uXG0BPVbeOnzbS1-tjHAG4QJAgA3KqqyORs8DjilNS0Cgp+jgDeAL624SqqOCk5QA)

**Comment by AlCalzone** [comment]
The way you wrote it, the function expects exactly one parameter with type `Params`. Try this instead:
```ts
export declare function infer<Params extends any[], Done, Fail = Error>(
  handler?: (...params: Params) => any
): (...params: Params) => void;

const f = infer(() => {});

f(); // works!
```

**Comment by goodmind** [comment]
@AlCalzone I need always 0 or 1 parameter

**Comment by goodmind** [comment]
It shouldn't infer `unknown`, but `void`

**Comment by goodmind** [comment]
Also your example doesn't work if I want to specify type and arity in generic

```ts
export declare function infer<Params extends any[], Done, Fail = Error>(
  handler?: (...params: Params) => any
): (...params: Params) => void;


const f = infer<[number]>(() => {}); // error about arity

f(); // works!
```

http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAE2AYwDYEMrDgMwK4B2yMAlhAXCQTsFADwAKm6AtgM5ygzAEIfoEAngG0AugBo4AEXLBJAMXQlUcALxwAolCjQAfAAoAsACg4cABYCEqWgH4AXHH0A6V2GbtHTKKzYBKNV04AUETP0cXNw82L2iA1SCANwgSBABuE0zjZHI2eBw1SmpaOmECPBYAI1pRA310R3Kq2niggG8AXz8M4xMcfW64AHohuAB3aABrNgBCIA

**Comment by goodmind** [comment]
I would argue that I have exactly one parameter of type `undefined` 😂

**Comment by AlCalzone** [comment]
> 
> 
> @AlCalzone I need always 0 or 1 parameter

I'm sure there is a nifty way to do it with a bunch of generics, but the easy way would be using overloads:
```ts
export declare function infer<Done, Fail = Error>(handler?: () => any): () => void;
export declare function infer<Param, Done, Fail = Error>(handler?: (param: Param) => any): (params: Param) => void;

const f1 = infer((a: number) => a+1);
f1(1);

const f2 = infer(() => {});
f2();
```

**Comment by goodmind** [comment]
@AlCalzone this means changing public interface of generics tho, instead of one type I would need to pass tuples

**Comment by goodmind** [comment]
@AlCalzone 

> the function expects exactly one parameter with type

If this was true, then it would error early on 
```ts
const f = infer(() => {}); // error would be here
```

**Comment by AlCalzone** [comment]
> If this was true, then it would error early on

No. The way you typed it, infer **returns** a function with exactly one argument of type `Params`. The error is raised at the call site.

**Comment by RyanCavanaugh** [comment]
> No. The way you typed it, infer returns a function with exactly one argument of type Params. The error is raised at the call site.

This 👆

**Comment by goodmind** [comment]
I don't think it should work like this, why not infer `void` as parameter type, instead of `unknown`?

**Comment by goodmind** [comment]
It isn't working as intended :\

**Comment by kitsonk** [comment]
It isn't working as you intended, but that doesn't mean it makes any sense to anyone else.  Sorry.
