### ISSUE TITLE
Infering type from usage does silly import

### ISSUE THREAD

**Issue by jpike88** [microsoft/TypeScript#32910]
**TypeScript Version:**  typescript@3.6.0-dev.20190814

myInterfaceFile.ts
```
export interface MyExportedInterface {
	something: number
}
```

another file, when using 'infer type from usage' option in VSCode
```
export async function someFunction(metricParams: { algebra: import("../../../../../../../../../blaa/bla/myInterfaceFile.ts").MyExportedInterface }) {

}
```

An 'import' function shouldn't be called.

**Comment by DanielRosenwasser** [comment]
We should always prefer an `import` statement at the top of the file.

**Comment by andrewbranch** [comment]
@jpike88 can you share the contents of that file pre-“infer type from usage” command?

**Comment by jpike88** [comment]
To reproduce, the file is empty other than the function I've defined, including any import statements.

```
export async function Test(test, user) {

}

```

Whats weird is this:

if I tell it to infer parameter types, I get this:

```

export async function Test(test: any, user: any) {

}

```
Which is correct I guess.

But if the function contains just one line of code, I get this:

```

export async function getPlantMetric(test: any, user: import("../../../../../../../../../project/some/path//shared/models/User").User) {
	if (!test) throw new Error('whatever!');
}
```

The second argument attempts to get at an import, but in doing so incorrectly inlines an import() function instead of pulling it in at the top.

**Comment by fatcerberus** [comment]
How is it even arriving at that type for `user` if the only thing in the function is just an unconditional `throw`?

**Comment by andrewbranch** [comment]
@jpike88 I can’t reproduce this with the info provided. I’m sure it must depend somewhat upon the file that exports some `User` type, and possibly upon project settings. Can you create or give me access to a repo that exhibits the issue, or describe more details about how to repro? Assume all details are relevant unless you can prove them otherwise.

**Comment by jpike88** [comment]
Sorry don't have the time, and I guess is an edge case.

But I think that there should be a VSCode setting that disables the import() function from being used at all when these sorts of judgements are being made.

**Comment by andrewbranch** [comment]
> How is it even arriving at that type for `user` if the only thing in the function is just an unconditional throw?

Somewhere else in the project, something is calling that function with an argument of type `User`. The code that triggers this issue isn’t shown.
