### ISSUE TITLE
getCompletionsAtPosition of ts.LanguageService does not respect the identifier at the current position

### ISSUE THREAD

**Issue by yunabe** [microsoft/TypeScript#32916]
**TypeScript Version:**  `3.5.3`, `3.7.0-dev.20190815`

**Search Terms:**

getCompletionsAtPosition

**Code**

https://github.com/yunabe/tsapi-completions/blob/a8020c20d5d2235c2443f34688d30c56eb9d5aad/src/completions.spec.ts#L27

- This test creates a `ts.LanguageService` using [the compiler API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API)
- Then, invokes `getCompletionsAtPosition` after `obj.lm[cursor]`.

```ts
setSrcContent(`
export {}
let obj = {
    xyz: 10,
    lmn: 13
};
obj.lm`);

const host = createLanguageServiceHost();
const service = ts.createLanguageService(host, ts.createDocumentRegistry());
const info = service.getCompletionsAtPosition(srcname, srcContent.length, {});
expect(info).toEqual({
  isGlobalCompletion: false,
  isMemberCompletion: true,
  isNewIdentifierLocation: false,
  entries: [
    {
      // Why is 'xyz' suggested here?
      name: "xyz",
      kind: "property",
      kindModifiers: "",
      sortText: "0",
      source: undefined,
      hasAction: undefined,
      isRecommended: undefined,
      insertText: undefined,
      replacementSpan: undefined
    },
    {
      name: "lmn",
      kind: "property",
      kindModifiers: "",
      sortText: "0",
      source: undefined,
      hasAction: undefined,
      isRecommended: undefined,
      insertText: undefined,
      replacementSpan: undefined
    }
  ]
```

**Expected behavior:**

- `getCompletionsAtPosition` suggests only `lmn` with `replacementSpan`, `isRecommended`, etc...
- Thus, the test passes unexpectedly: https://travis-ci.org/yunabe/tsapi-completions/builds/572277756

**Actual behavior:**

- Both `xyz` and `lmn` are suggested.
- `source`, `hasAction`, ... `replacementSpan` are undefined.

**Playground Link:**

**Related Issues:**

N/A

**Comment by RyanCavanaugh** [comment]
As far as I'm aware this is the expected behavior. We return the full list of suggestions based on the current entered text, and it's up to editors to decide how they want to filter the completion list. For example, if you hit Ctrl-J (list members) in VS, you see this:

![image](https://user-images.githubusercontent.com/6685088/63199233-11bce280-c032-11e9-93d7-1490221527cc.png)

Pre-filtering this list based on "what's typed so far" would make it impossible for editors like VS Code to implement camel-case completions, for example:

![image](https://user-images.githubusercontent.com/6685088/63199282-3a44dc80-c032-11e9-9e6b-1edfcb18ad9a.png)

Assigning @sheetalkamat to confirm

**Comment by yunabe** [comment]
IMHO, getCompletionsAtPosition here should be able to:
- Sort completion candidates by priority/importance. In my example, prioritize `lmn` over `xyz`.
- Tells the caller which text-spans should be replaced with candidates. In my case, `lm` should be replaced with `xyz` or `lmn`.

Of course, both of them can be handled by the caller-side theoretically. But these tasks require at least ASTs and I think it is natural to handle them inside `getCompletionsAtPosition`.

> As far as I'm aware this is the expected behavior. We return the full list of suggestions based on the current entered text, and it's up to editors to decide how they want to filter the completion list. For example, if you hit Ctrl-J (list members) in VS, you see this:

It's interesting. Can I see an example of the open-sourced editor-side code somewhere?

> 
> ![image](https://user-images.githubusercontent.com/6685088/63199233-11bce280-c032-11e9-93d7-1490221527cc.png)
> 
> Pre-filtering this list based on "what's typed so far" would make it impossible for editors like VS Code to implement camel-case completions, for example:
> 
> ![image](https://user-images.githubusercontent.com/6685088/63199282-3a44dc80-c032-11e9-9e6b-1edfcb18ad9a.png)
> 
> Assigning @sheetalkamat to confirm

In this case, I think `getCompletionsAtPosition` should return `alphaBravoDelta` to the editor rather than returning everything and letting the editor select `alphaBravoDelta`.

**Comment by sheetalkamat** [comment]
We do not prioritize the completions or filter it based on what you are typing. We prioritize based on locals, globals etc. Its upto editor what kind of filtering and further sorting it wants to do.

**Comment by yunabe** [comment]
I see. That design is a little suprising to me because I think many editors need to implement very similar logics. But, thank you for the clarification.
