### ISSUE TITLE
Array spread operator is being incorrectly transpiled in ES6 with Iterables

### ISSUE THREAD

**Issue by danielcardeenas** [microsoft/TypeScript#32927]
Spread operator should be able to handle iterators in ES6

`typescript@next` Throws error: `__spreadArrays is not defined`

**Search Terms: spread operator incorrect**

**Code**

```ts
const blocks: NodeListOf<Element> = document.querySelectorAll(...)
[...blocks].map(...)
```

**Expected behavior:**
It should be transpiled as spread operator when targeting es6
```
[...blocks].map(...)
```

**Actual behavior:**
It is being handled as an array
```
blocks.slice().map(...)
Error: blocks.slice is not a function
```

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/6874

**Comment by MartinJohns** [comment]
It's working fine in the playground: https://www.typescriptlang.org/play/?target=3#code/MYewdgzgLgBARgGxMA1hAXDAciAJgUwBkBLaAeQDMAeAUQXwFt8woA+GAXhl2QFcmWAOgCOvfACcAngGV89YFBDiAgggQAKAOS5iAN00BKAFChIsCpxgBtQbcTI0AXUEMAhgAd1AD07svxoA

How are you compiling your TypeScript code? Are you perhaps passing a list of filenames when executing `tsc`? Doing so will cause the compiler to ignore your `tsconfig.json`, and if you don't explicitly set the target language it will fall back to ES3.

**Comment by RyanCavanaugh** [comment]
@danielcardeenas it shouldn't be possible to produce this situation in an error-free compilation. Can you share a configuration file that reproduces the problem?

Please unassign yourself if you're able to provide a repro. Thanks!
