### ISSUE TITLE
Suggestion: Recognize JavaScript patterns for singletons

### ISSUE THREAD

**Issue by chrisdias** [microsoft/TypeScript#32926]
From twitter: https://twitter.com/mausmalone/status/1161616601109737474?s=20

> One thing I would love from @code would be if it could recognized JavaScript patterns for singletons. Would be nice if this wasn't a member of an anonymous function.

![image](https://user-images.githubusercontent.com/1487073/63135993-d3b5b500-bf84-11e9-8cd2-807014ff4752.png)

**Comment by chrisdias** [comment]
pls assign to @DanielRosenwasser

**Comment by RyanCavanaugh** [comment]
@chrisdias what specifically should be happening differently in this example?

**Comment by RyanCavanaugh** [comment]
Closing due to lack of follow-up.

**Comment by chrisdias** [comment]
I don't know what the answer is, I just copy/pasted in a twitter request :)

@DanielRosenwasser could you reach out to the person on twitter and try to get more details?
