### ISSUE TITLE
Add 'LKG this' to TypeScript Bot

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#32931]
Someone forgot to LKG after a cherry-pick before a release, and this means I had to do it on release day and re-run the VS build. Please add infrastructure to either cherry-pick and LKG or to at least run an LKG on a PR.

**Comment by weswigham** [comment]
`@typescript-bot cherry-pick this into <branchname> and LKG` is now a command~

**Comment by weswigham** [comment]
I can still add a raw LKG command, but I think having, eg, a teams bot that you could `@` with something like `@typescript-bot prepare a release` and have it walk you through all the information it needs to make _everything_ happen would be pretty good. Everybody likes chatbots for release management.

**Comment by DanielRosenwasser** [comment]
This has generally been good enough.
