### ISSUE TITLE
Problem with type inference. Caching?

### ISSUE THREAD

**Issue by Norm-** [Microsoft/TypeScript#3293]
Hello,

When I start a new .ts file and do;

```
var name:string;
name = "foo";
```

It compiles as expected.

Then I change name's type;

```
var name:string[];
name = ["foo","bar","baz"];
```

Compiler complains thus;

> test.ts(1,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'name' must be of type 'string', but here has type 'string[]'.
> test.ts(2,1): error TS2322: Type 'string[]' is not assignable to type 'string'.

This stops when I change the *name* to something else;

```
var spam:string[];
name = ["foo","bar","baz"];
```

When I try to reproduce it with different names other than *name*, problem seems to go away. I think this is either related to the var *name* (reserved word?) or some caching.

-d

**Comment by RyanCavanaugh** [comment]
The global `name` is exposed in TypeScript.

https://developer.mozilla.org/en-US/docs/Web/API/Window/name

When you write `var name` at top-level, that doesn't create a new variable:

```ts
var name: string;
console.log(name); // Expected: undefined, actual: "" (depending)
```

We don't let you write `var name: string[]` because that identifier already has a meaning at global scope.

**Comment by mhegazy** [comment]
This has been a common source if confusion. issue #1351 is tracking removing the definition of "name"  and "length" from the library to avoid these issues.
