### ISSUE TITLE
Mapped Type with generics display wrong type in IDE

### ISSUE THREAD

**Issue by ChristianGaertner** [microsoft/TypeScript#32932]
**TypeScript Version:**  3.5.1

**Search Terms:** mapped type generics hover dev tool typeToString

**Code**

```ts
interface Base {
  value: string | number;
}

const test = <T extends Base>(a: T, b: Readonly<T>) => {
  console.log(a.value, b.value);
}
```

**Expected behavior:**
When hovering over `value` I expect to see the following type hint:
```
(property) Base.value: string | number
```
**Actual behavior:**
For `a` I see the correct behaviour, but for b I only see this:
```
(property) value: T["value"]
```
The actual type system still "works", I can properly discriminate between the two values of the union, so I suspect this is only a "bug" in the routine which converts the type to a string for display purposes (and jump to definition also works...).

**Playground Link:** https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnIBucANgK4QBcyGYUoA5sgD7IhkC2ARtANy4BfXLgQB7ELWSRJAXmQAeACrIIAD0ggAJhjSYIAPgAUcaooA0yLtQBKEOJvEkAnkv0BKZDP3I8BMRNESCAA6ElEGY2DicggLLijSCjd+ASA

**Related Issues:** #15756 #18089 #18042

**Comment by RyanCavanaugh** [comment]
This in general is correct behavior given the limitations of the type system's ability to reason about mapped types - when a property key goes through a mapped type, there's no concrete way to "know" without higher-order reasoning what type comes out the other side.

**Comment by ChristianGaertner** [comment]
I think I do not fully understand your reason for this limitation, as this works if we are not dealing with generic types, as one can observe in [this playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnIBucANgK4QBcyGYUoA5sgD7IhkC2ARtANy4BfXLgQB7ELWSRJAXmQAeACrIIAD0ggAJhjSYIAPgAUcaooA0yLtQBKEOJvEkAnkv0WE1dFguabdhyDO8l4GAJTIMvrIeARiEqIkEAB0JKIMxknE5BAWXJmkFO752T7FFKH8AkA), so it cannot just be the "fault" of mapped types. Or am I missing something else?

**Comment by fatcerberus** [comment]
Because you don’t know what `T` is while still inside the generic function.  It could be any subtype of `Base`.
