### ISSUE TITLE
Explicit generic type argument gets lost when attempting to carry through member expression

### ISSUE THREAD

**Issue by jeffijoe** [microsoft/TypeScript#32937]
**TypeScript Version:**  3.5.3

**Search Terms:** inference nested member

**Code**

The Playground link reproduces this issue, but here is the whole code.

```ts
// Issue: the generics are not flowing all the way through.

// This works fine
const handler1 = CommandHandler.create<RespondToQuestion>(
    requireThat(
        isCollaboratorOnRequest()
    ),
    requireThat(
        subjectIs(allowedTo.fooTheBar, BasedOnClaims.fromMessageBody(b => b))
    ),
    async ({ body }) => {
        console.log(body.subject_id)
        return { version: 1 }
    }
)

// But when I start chaining the specifications, the type that has been specified to be `RespondToQuestion` is
// now `unknown`.
const handler2 = CommandHandler.create<RespondToQuestion>(
    requireThat(
        isCollaboratorOnRequest().or(
            subjectIs(allowedTo.fooTheBar, BasedOnClaims.fromMessageBody(b => b))
        ) 
    ),
    async ({ body }) => {
        console.log(body.subject_id)
        return { version: 1 }
    }
)

// Specifying the generic seems to do the trick though, but why do I have to? Shouldn't it flow through?
const handler3 = CommandHandler.create<RespondToQuestion>(
    requireThat(
        isCollaboratorOnRequest<RespondToQuestion>().or(
            subjectIs(allowedTo.fooTheBar, BasedOnClaims.fromMessageBody(b => b))
        ) 
    ),
    async ({ body }) => {
        console.log(body.subject_id)
        return { version: 1 }
    }
)


const msg: Message<RespondToQuestion> = { body: { type: 'RespondToQuestion', subject_id: '123' }, meta: null as any }
handler1(msg)
handler2(msg)

handler3(msg)



// Sorry for all the types 😅
export interface AsyncSpecification<T> {
  and(other: AsyncSpecification<T>): AsyncSpecification<T>;
  or(other: AsyncSpecification<T>): AsyncSpecification<T>;
  execute(value: T): Promise<T>;
}

export declare function isCollaboratorOnRequest<T>(): AsyncSpecification<Message<T>>;

export interface Message<T, M = unknown> {
  body: T;
  meta: M;
}

export interface Claims {
  subject_id: string;
}

export type ClaimsLookupStrategy<T> = (message: Message<T>) => Promise<Claims>;

export type AllowedToBasedOnClaims = (claims: Claims) => Promise<Claims>;

export declare function subjectIs<T>(
  checkAllowedToBasedOnClaims: AllowedToBasedOnClaims,
  claimsLookupStrategy: ClaimsLookupStrategy<T>
): AsyncSpecification<Message<T>>;

export interface AllowedTo {
    fooTheBar: AllowedToBasedOnClaims;
}

export declare type Handler<I, O = unknown> = (input: Message<I>) => Promise<O>;
export declare type Pipe<I, O = unknown> = (input: Message<I>, next: Handler<I, O>) => Promise<O>;

export interface CommandResult {
    version: number | null;
}

export interface Command { type: string }

export declare const CommandHandler: {
    create: <C extends Command>(...pipes: Pipe<C, CommandResult>[]) => Handler<C, CommandResult>;
};

export declare function requireThat<I, O>(specification: AsyncSpecification<Message<I>>): Pipe<I, O>;

export interface RespondToQuestion extends Command {
    type: 'RespondToQuestion'
    subject_id: string
}

export declare const allowedTo: AllowedTo

export declare type ClaimsWithOptionalSubjectId = Omit<Claims, 'subject_id'> & {
    subject_id?: string;
};
export declare const BasedOnClaims: {
    fromMessage<T>(messageBodyToClaims: (message: Message<T, unknown>) => ClaimsWithOptionalSubjectId): ClaimsLookupStrategy<T>;
    fromMessageBody<T>(messageBodyToClaims: (body: T) => ClaimsWithOptionalSubjectId): ClaimsLookupStrategy<T>;
};
```

**Expected behavior:**

The type argument `RespondToQuestion` passed to `CommandHandler.create<RespondToQuestion>()` should flow all the way through consistently.

**Actual behavior:**

When using certain patterns, TS will change the type to `unknown`.

Additionally, it seems it can't make up its' mind. 😅 The error says `body` can't be inferred, and yet the tip gets it right.

![image](https://user-images.githubusercontent.com/2505474/63194438-07084a80-c03e-11e9-94d9-4c87e48bb81d.png)

---

![image](https://user-images.githubusercontent.com/2505474/63194715-b9401200-c03e-11e9-8d75-f21d1236d102.png)

**Playground Link:**  [Playground](https://www.typescriptlang.org/play/index.html#code/PTAEEkGdIVwUwFygC4As6gOZwHZwE4CWAxpKAIb4Y4D2yoAZgDY0DuhOmFTTK6orcgE8++GjEyoAdACgZIUABVUhMqxr4A1mQYc4M4jRyR6qcjgAmTAgEZQAXlABhGgFtX5iwAlP1-FOIqcmQ4AB4AJThIAAcjC0UaAEV4E0IjAD4AChlQXNAqAEcYQiplYOy8ytBVFx5yACMNYI0AeRxIoqjkTIBKHLyegBp+3MLi0rNukarYeoArOGJkKEzyHjY4eJopBhoaZTgAIUpB0GPITbanJnJCV0gdsVcAWSjIcmxDmgshTPqHdKgeo9PqVIbTciQIQ4YigTIAbyB3xEAF8egDQPDppVDMYaNYpCxMH9kVJZgslgB9QgWUFVUZwZAwfA4TGgABuBEgaRwSDsKOmAr68jAhxg9FY6FZ4FAJko9GIZg4HC4aAwMUWhF0xGCPMgpzVKCE0QwaGCoDMZHqcFwspNxC1hE2KBoQIwAANIjE4glkl0ee7qpARaBaKxQO6YDhNGGcO7ZLiTBbfAQAEwOZxuDyWHyWPwBIIhCJRWKWX0pZA8rLTMYlOBlKb03I1fE3Rr4Zr4NodCu9KQaCpNyrkxbLSCrdasTYJHZ7A7HfCnc6XHDXW73R5uV7QD5HZF-DHAun09HTcGVSHQ2EIpE-UBojFYoeJ-FwQk0YmNH5kmDzUfU2lsTyKgmRZNlOXwbkjD5e9BRkYUFAAZXtLUhBVPgMGwPAiFhC44HuF1QAsV1DWQHDND4cRJFOepxQEVARGIiBk05F0AH5QEQ1BxCYCwcAAcnoQh6GYNhRCo1A2IMIwkzMPMCAAZgzFx3E8XMrAIAs4GCMIvVLLY-VSDJBwZIo6wbEyqhbOp207bs4E6Exi29MskgrKs+wHID6RHJYVjWFgpy2Wd9nQBcl0hFc1zuB4GCebd3k+fd-nsQEj280BTzBYYLyhGE4URL9UXRVLMQyl8CSJElv185AAOPKoQOZVlEQgqDeVAfk4OFaTjHoe5MCQBLd2c-Ty39DIM0K5EkERZBjUQUB+L0n03ImgTTlqgCkH4mxUwU-j71OVxGXIJAcBgHgKDIcxURkOSNPwGxMgGvoHr8VMXsgTBhXexSvp+uQ5CQjR8BEXZ8G4XhSIWshAF4NwBQPZkOAAA9YnwIScBCfAGHIYgMAAQTy4hkM1bVdSMUJFEBJ8KEsTI6HQfAkCJq9SYdcnK0p6mehZ4n2cdHUuZwKn0gAbn6AdGYIPm2ZQzmeVF3nQFZmEBYV7nxf6VHFnFOBMnZNZ4CQRRlYABSeVQwmpiWBWRtGNHoCxFhuKhGCjJYeSDWo2yaZBWnaByK1F3pZbV+WSApkXhuwUWtft9HMex3H8dAGPrdOZ4MyjGM2BwGn+iKk2JdyE7kDOtPbbkVHE+qLGCBTjBooI2mtppJATCITgq4Tx2jRNZwbhigAZPZNBgaJELInTMCEUWMxet5dyGpfY55jELbcK3QmbyB45rvv5oHgnJ2nGhlwsK4h4IxxMmIa-ICQXeSsBTfXG33f94djGiJdygMAYB7YWspfwUjHCHfoipFiaBPoFM+F8r7rkfirU+WwEGrgfjlUA98kGjxoOPSe08Qizyfg-PBBCp4dmIXPam8Ew4kwjkLRW6c44S17j-Dgyc8aE1QQkMqlRdihSOJQFmvDz6RUvhgpBPcD4-2djgt2R8MDqT8KEcApwWjZ2jLGQEt8ODRHFCvHcsdwDpBfqAN+28Wha1kU7P+iiFoWMICaNRGitG51YPnBe+jDFp1XmEUxpw8Ao2QEgFRBBXGgGseYyxFxQjWLYbYuuXDU4qWzBYL0l16C01yG1Hk50YCuGtJDAAPqGS6TAZHfyTg3bhmZVKWDZEojuZF0J2ySfI12GBEz0DSWpFMzN+F5ECNpEISAd6gFRiESwZA+mWCyFIRZ0RnFRCQGbFZO9ThzIyVELJ6QADaABdcx4T8CbPqekzJTBkBaxRIk6pv8FEAKAV7WsExgiROsZkDUHNI7C3oerP5zD-FqPSGYtZGz1FRK-rXThtTU4rVcoZYBUzcAWFmVmTwQzcjNKWoigy7kjD8WmG3CwLSu6YBkO0h5nT-7YJkvQAKGwtiiLgVsauNL7GmkcbvAA6sJVALRojCzWIhUBo5wAWAzC0d+yAd6YKWqS-igIABk2KQF-ipDSNi5KVS2wlh0rl9K+pnAkYgmKs1phxS3CC6mi9jF7h+AkXeSB7WJUWiwxQpwc46PMXygVQqRVMDFZq5YtJSG4LHhPShM8aFawEfFfxXwfghxOg65NQhnUP1dUXJQfqH78rQIGnkorxV+XDYPSN+Do1ELgLPUW+qgZAyAA)

**Related Issues:**  These look related: #30134, #16597

**Comment by fatcerberus** [comment]
One thing that might prevent type parameters from flowing through is this:
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot---

I don’t know if that’s your issue, but it’s the first thing that came to mind.

**Comment by jeffijoe** [comment]
@fatcerberus checked it out, if that was the case then my first example wouldn't work either, no?

**Comment by AnyhowStep** [comment]
`isCollaboratorOnRequest<T>()`

This piece of code is way too suspicious.

**Comment by jeffijoe** [comment]
@AnyhowStep it works fine on its' own without the chaining; and the `T` should be inferred from the return type?

**Comment by RyanCavanaugh** [comment]
This needs a reasonable-sized repro before we can look at it - once things get this long, 99 times out of 100 it is a problem with the code itself, not TS.

**Comment by jeffijoe** [comment]
@RyanCavanaugh fair, but why can't TS make up its' mind about what type `body` is in the screenshots I posted? One part says its implicitly any, another is perfectly aware of the correct type. 🤔

**Comment by AnyhowStep** [comment]
Your `handler1` working surprises me, honestly.
