### ISSUE TITLE
Generic function with rest parameter assignability not transitive

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#32948]
**TypeScript Version:** 
+ 3.5.1
+ typescript@3.7.0-dev.20190815
+ https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
  https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz

**Search Terms:**

**Code**

```ts
/**
 * --strictFunctionTypes
 */

export type ExtendedMapper<HandledInputT, OutputT, ArgsT extends any[]> = (
    (name : string, mixed : HandledInputT, ...args : ArgsT) => OutputT
);

//type a = (name: string, mixed: any, args_0: any) => any
type a = ExtendedMapper<any, any, [any]>;
//type b = (name: string, mixed: any, ...args: any[]) => any
type b = ExtendedMapper<any, any, any[]>;
//3.5.1, typescript@3.7.0-dev.20190815
//Expected: "y"
//Actual  : "y"
//https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz
//Expected: "y"
//Actual  : "n" <-- Intentional?
type test = a extends b ? "y" : "n"

type a2 = (name: string, mixed: any, args_0: any) => any
type b2 = (name: string, mixed: any, ...args: any[]) => any
//3.5.1, typescript@3.7.0-dev.20190815
//Expected: "y"
//Actual  : "y"
//https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz
//Expected: "y"
//Actual  : "y"
type test2 = a2 extends b2 ? "y" : "n"

//a extends b2 extends b
//However, a DOES NOT extend b
//It seems assignability is not transitive...

//"y" for all versions
type aExtendsB2 = a extends b2 ? "y" : "n"
//"y" for all versions
type b2ExtendsB = b2 extends b ? "y" : "n"

type TakeExtendedMapperRest<MapperT extends b> = (
    ["Blah", MapperT]
);

//Works in 3.5.1
//Fails for https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
export type ShouldWorkButFails<T extends a> = (
    //Type 'ExtendedMapper<any, any, [any]>' does not satisfy the constraint 'ExtendedMapper<any, any, any[]>'.
    //  Property '0' is missing in type 'any[]' but required in type '[any]'.ts(2344)
    //a -> b not allowed
    TakeExtendedMapperRest<T>
    //                     ~
);

//Works in 3.5.1
//Works in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
export type Workaround<T extends a> = (
    TakeExtendedMapperRest<
        //OK!
        //Takes advantage of a -> b2 -> b being allowed
        Extract<T, b2>
    >
);

//Works in 3.5.1
//Fails in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
type WorkaroundTest = TakeExtendedMapperRest<a>;

//Works in 3.5.1
//Works in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//type WorkaroundTest2 = ["Blah", ExtendedMapper<any, any, [any]>]
type WorkaroundTest2 = Workaround<a>; //Success
```

**Expected behavior:**

Build in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476 should behave the same as 3.5.1 and typescript@3.7.0-dev.20190815

Assignability should be transitive.

a -> b2 -> b should imply a -> b

**Actual behavior:**

Assignability is not transitive

a -> b2 -> b **but** not a -> b

**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/#code/PQKhCgAIUhaWDOAXATgSwMZIGIFcB2WaA9vgCoCeADgKYJQjDjg0AeVxKSkS1NkAUVZIa+ACY0xAWQCGVWigA8ACRniANpICS+KriRkANJADy+vQeMBBFAHMEZSGxHiEkNRQDaAXQB8kAF5IAAooSHDg-BkAW34ALkhkdHxbY2i0VklIBNUNbV19I0gAOlKZOzcEm3syAEpA-zMkCzJwWoBuZmBgXlp3QJCo2ISktBS0jMkEj2Ny+wB9AAZp-Ap6gP8PcF7+GQGhFwlpOQVFGfdV408PP07uncgAIwHImJoR1DHUyHTMsRWKMZSsU5ggAT51ptVts+E99sJREdZPIaEpzujVj5fHdgABmYoAVmKAEZjDsEBh0FQkAABfEAdmKi1gEgAbsUAEyLYkATkWAA5iQTwN0hLQsFNIAAiChSkXAKxYXAydThBIyuXdAAWSGaYO6tjQSC1uEexQwxGiwHSlOICGIADMkMBKLQAMqUtDU4B6dTqPEcnkcgAsAGI0AgELgaBborF8EhYASOcTBTzg-SAGzynV6uL3PgUqlIYqsiPK9TIXBiEjmy3ADAO+kyDDE4OZlnJgmwYPB3EYWCPDn92CLMQE-m43H0mgOmiPDDAeZyCPAR64NDqMRrjdbhDAYOLQ-B4DlJBoB0tpAIAD8Z4vV4Acm8AkhbAAvABkDs3NC0YgCKwABEeSAjkOQAYWwelFgJTNiQAIQEKxsAJekJwERZ4IQ+CgNxbBsH5HliWA7BM0zYMBGnCCCVxDlUP5QVcR5XEIIEekgIgycuQ5b9f2fWIAh6QtPWpWAGSZWAxgQNAJBQBBOW5PlBSJN933lMUYxEf5pVleVFSQCs1WlfApUgRR4EgHQXHPUgVRvGE+hEZABj2ZxETcZ4b10sz1VM5gHhkDkXiGd5Ek+cYfkmHT0QqJYAUhC4KEc-ghxCt4PmSb5fklc5gVBcFvESrZunxIlSR4ETizpYpGWZNlFN5AUhQ09gtMlDV9KVFVjM67VdSofVgENY1TTrK0bRQO1HWdV0aA9YsfVwP0AyDMMIyjGNLXjRNk1TXkM2zfq8wLWgiy9EsyyjFUqxrYhxobJsWzbDtxw5btexHIcRzHCcpxnOcFyXFd93XTdtzBvcDyPI9Ty4B8sFve9LywASaFfD8+M0f9AJAsDIOg2DsOQ1D0P5TDsNw-DCOI0jyMo6jaPoicmJYtiOK4ujFl4n9NDRoTyVExMJOZaTZNRBSuSalTijU1rxW09U9O6AyjOyHyUp4OgkGCoIgqcBFXCeYLvI1dWpX8+U3MNsRPOC9yjceeVlGIAB3GhWVRWZICAkwBDdSBHxMRwHbEJ55S0bgEBoGhojcGRIzQWwokeTcjQoSAI0gfBiG4VA1Bk89PeBLpgDNh1OHcP1IE9+SSHwehAoODyEN1-pQ7tyBTdlc3-O6cvK5VVVa5k0hG9hIdm9cBCBjSju4W73yTLlTWyBkABrGgp6RE5UQAJW1xRkQUEObc8-wglCcJwk8KUEPUGQtSlYxj9RMhvDaTp5QAdU4de3DGJAMqJJ5TYBkJuNwFcUCQFzINfMw0jQmjNLGa0mApr2idC6PgC0LpLRWnRNa4ZIzRljDtJMKY0yHRYOwTgedYRui1MQZaYhf4oHXghfQYCIGKFPoceOF8QhhHCN0OakAADk29JCvzRJcJKVwbi+DEZAMQxA6DZ1zokGQ54EAOgzsafgFoG75zGNwCRNspG7xkYCORSUsRiOKEIyA3RwgAAUpoKF4OIxYSis7pETikTO+BKp9DER4HwSj1zcBQDQAAjhuaJYdAEPDEdcVY3h7HXmCMOXstRHHdD2LAfwzwc7cCHm7SQji16b0kccFEKAD7IB4b4PJwBr5tPaR06+AA-T+pdWH-0CUAwkIDuj9IAUE2BQ0RpIIepNaamC5o4O9L6f0BCQxEM2qQ0Qu0KEHSzNQjgXBgn8H6eUJh4geEGz4e4ARV9r5VK3uY2pCgGlIEUI4tp3QTAAGkACEHzr4iI3momQYhWRqCQDIWw-BHT9EKcbOARSng0C+FXdQ5SxAAvCAcFAV4eHGCHM0tpzSOh9L-uMoZ5VQHgMrIMyZ8DpljRQXMjBs1sFCzwaswM6yNokO2ts8h+10z7IeKcqaBAxBkG1gMB5NTpGvLONiMlbCKXAOJD-cldKBpTMQUy+sLKZpYPdBylZq0eXEK2nGAVe1KH7NOicv+ZyJVSuQG3W+99H7P0EE86RZxZHnFSRQPwH9RWOvFeIF1OsBhivOWIRV7QnHADdLgDAGA6AICAA)

**Related Issues:** 

https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521826091

https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521834620

https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521930291

I'm not sure which commit introduced this problem.

@weswigham

**Comment by weswigham** [comment]
Assignability has never been transitive - see `{a?: number } -> {a?: number; b?: number } -> {b?: number}`.

The examples I gave in the thread you discovered it is more compelling - two nearly identical types (identical sans alias symbol) that do not yield identical comparison results.

**Comment by AnyhowStep** [comment]
Guess I'll include the no-alias version for completeness,

```ts
/**
 * --strictFunctionTypes
 */

export type ExtendedMapper<HandledInputT, OutputT, ArgsT extends any[]> = (
    //Using the no-alias example from,
    //https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521930291
    {x:(name : string, mixed : HandledInputT, ...args : ArgsT) => OutputT}["x"]
);

//type a = (name: string, mixed: any, args_0: any) => any
type a = ExtendedMapper<any, any, [any]>;
//type b = (name: string, mixed: any, ...args: any[]) => any
type b = ExtendedMapper<any, any, any[]>;
//3.5.1, typescript@3.7.0-dev.20190815
//Expected: "y"
//Actual  : "y"
//https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz
//Expected: "y"
//Actual  : "y" <-- Using the "no-alias" example, it works as intended
type test = a extends b ? "y" : "n"

type a2 = (name: string, mixed: any, args_0: any) => any
type b2 = (name: string, mixed: any, ...args: any[]) => any
//3.5.1, typescript@3.7.0-dev.20190815
//Expected: "y"
//Actual  : "y"
//https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz
//Expected: "y"
//Actual  : "y"
type test2 = a2 extends b2 ? "y" : "n"

```
[Playground](http://www.typescriptlang.org/play/#code/PQKhCgAIUhaWDOAXATgSwMZIGIFcB2WaA9vgCoCeADgKYJQjDjg0AeVxKSkS1NkAUVZIa+ACY0xAWQCGVWigA8ACRniANpICS+KriRkANJADy+vQeMBBFAHMEZSGxHiEkNRQDaAXQB8kAF5IAAooSHDgYABVBDR8Wx4AC358YlgZdTQZNzYZAFsqTUgAMxRiPMMwiOBEpCQqBAAuSNs0JETcACMAOgxy4DzMMoRiYqRgSloAZQx0KnG9dXVgAGYAJgBONYAWAGI0BARcGj68vNEkWABWNYBGDZWABk3bqsgAb1ZG4Px8-kbIMh0PFjINWJJIADVBptLp9EZIN0kTI7G4ATZ7GQAJSBfxmerwgC+ngARKwSd5wFiANzMSK8WjuQIhX7nAFAuK2UFocFiAEeYwo+wAfUe-PwFBxAX8HnADP4MmZQhcEmkcgUigF7glxk8Hj8tPpfEgnWZPz+7NQnO5vPFFGMSO6Qqa2q83ilMolcuNpqCytEqtk8hoSi1YYlPl8htW3Su3VuxnlCFmaHmAAEVt0AOzdR6wCQAN26a0e90eAA5bldwJEhLQsJIASSKCSa8ArFhcBlwk2W23avUmi02h0eqcBkNiCMxhM+DM5gtcEtVpsdvtDsdTud8JcbrdKxttlmAGz9uoNZrAJMp+bdAsHLvqZC4MQkXr9DDFLMyDC3bbH-MbiuWBtm2FYMFgTo1nA2BHjEK5yxWFYsxoYoaE6DBgGFOQDmATpcDQdQxDwgiiIQYBtkeSjtmAFEkDQYofyQBAAH46IYpiADk-gCJBbAALwAMmKQiaC0MQAisAARDYpLWNYAGFsCzR4rmPW4ACEBCsbArizBCBEedSNPUqSVmwbByw2W5pOwY9j22ARkIUq51l08tKxWB4FIELMpIUxCSzWYTRO484AivPhkwXWBMxzPM4liCQUAQYtSw2Csq26Pj+LbOsThEPlIGbVtIg7JBHx7YqW0gRR4EgGJOSSfgSVSdJMmyEknFYfJChoYw2kgAB3TgAGs3GySA4hVSRvUZERkGZRVnADNxTRY6quqbfBWzmhU1jNVkaEtYEuUgMFG1dQVUVFO0PVdPaTQOoJzTZQErRBc6eUurVHWdO0fHu2VIkzOMEx4KKbyQDNs1zfMaCLEsy0rata3YArLpKttysqyFNrPQdL1adounfPIJ1mKdRnGSYaHnVNF2XdYtj2A4jhOcpt13O4DyPU9IgHC8jVoaKGbvB8MmfV9iDJ4BP2-X9-0AtZgNAmCoJguCEKQlC0IwrCcPI-DCOI42yIoqiqNorgOKwVj2MYrAwpoXiBJCzRxMkmS5MU5TVOM7TdP08tDOM0zzMs6zbPsxznNctZ3M87zfP8wLnndmhnYi68YriuHErQZLUqRjKUeygS8vRhsiqxsrO27PGsflHg6CQZ73AOlbXCeyANpKxudvAIA)

It's weird to me that the no-alias version behaves as expected.
They both *should* resolve to the same type.

**Comment by jack-williams** [comment]
I think this stems from the special rules for `any[]` as a rest type.
```ts
const list: any[] = [];
const tuple: [any] = list;

const fn: (...args: any[]) => void = undefined as any as (...args: [any]) => void;
```

A list of type `any[]` _is not_ assignable to a tuple of type `[any]`, while a rest arg of type `any[]` _is_ assignable to a rest arg of type `[any]`.

The type alias does not track the context in which a type parameter was used so checking uses the first relationship, rather than the second.

**Comment by fatcerberus** [comment]
@jack-williams 

> A list of type any[] is not assignable to a tuple of type [any], while a rest arg of type any[] is assignable to a rest arg of type [any].

You say this is a "special rule" but... isn't that just a natural consequence of contravariance?

**Comment by jack-williams** [comment]
The assignment to `fn` requires that rest args of type `any[]` are assignable to the rest args if type `[any]`.

While the function assignment is allowed, a corresponding assignment of identifiers of those types would not be.

A correction in my wording: the special treatment does not apply specifically for `any`, but all function assignments with rest parameters.

This is effectively the same problem as #31698.

**Comment by fatcerberus** [comment]
Right, what I was getting at was it was it was the same as how `BaseType` is not assignable to `DerivedType` but a function type that *accepts* a `BaseType` as a parameter is assignable to one that accepts a `DerivedType` - i.e. the special treatment is just normal contravariance?

**Comment by jack-williams** [comment]
@fatcerberus 

The special treatment is that the normal rules of contravariance of function input are ignored in this particular case. Using the normals rules would suggest than assigning a function that expects a more precise arity (exactly one) to a function that expects a less precise arity (0 or more) would be an error.
```ts
const echo = (x: string) => console.log(x);
const fn: (...args: string[]) => void = echo; // no error
fn(); // no error, but echo is called without an argument;
```
However, the checker will not complain here because it assumes that `fn` will be called at the correct arity `echo` expects.

**Comment by fatcerberus** [comment]
Oh I see, it can lead to unsound *calls*.  That makes sense now.  I admit I hadn't considered the effect of the rest parameter on the function's arity (there's a word you don't see often!): I just saw that clearly, you can use a function that accepts a `T[]` in place of one that accepts a `[T]` and there was no problem with that.  But because it's a rest parameter that also affects arity, it's not necessary sound.

Thanks for being patient with me, I feel pretty dumb now. 🥴

**Comment by jack-williams** [comment]
@fatcerberus Any time - good questions and discussion make the tracker better for everyone that uses it.
