### ISSUE TITLE
Meetup Support

### ISSUE THREAD

**Issue by smashdevcode** [Microsoft/TypeScript#3295]
Back in March, my co-worker and I started a TypeScript Meetup here in Portland, Oregon (see [http://www.meetup.com/Portland-TypeScript-Meetup/](http://www.meetup.com/Portland-TypeScript-Meetup/)). We're now 67 members strong with our third meeting coming up on 6/11. We're having a lot of fun building interest in the local community around TypeScript.

Any chance of getting somebody from the core team to make a trip to Portland to give a talk at one of our upcoming meetings?

Thanks for everything that you do... we love TypeScript!

Thanks,
James Churchill

**Comment by danquirk** [comment]
Awesome to hear this. Pinging @jonathandturner since this might be in his wheelhouse sometime.

**Comment by smashdevcode** [comment]
Thanks Dan. I appreciate the response.

**Comment by jonathandturner** [comment]
Might also be good to have a place meetups for TypeScript and promote themselves so that other people can find them.
