### ISSUE TITLE
Type assertion breaks return type inference

### ISSUE THREAD

**Issue by birjolaxew** [microsoft/TypeScript#32957]
**TypeScript Version:**  3.5.3

**Search Terms:** type assertion breaks return type inference, type assertions change type inference, incorrect return type inferred with type assertion

**Code (note: edited after comment by @ajafff)**

```ts
// having a type assertion breaks the infered return type
// expected return type: HTMLImageElement | HTMLPictureElement
// actual return type:   HTMLPictureElement
function test(foo: HTMLImageElement | HTMLPictureElement) {
    if (foo instanceof HTMLImageElement) {
        const bar = foo.cloneNode() as HTMLImageElement;
        return bar;
    }
    return foo;
}
```

**Expected behavior:** The type of the function is correctly inferred, with the asserted type being one of the members of the returned union type. (i.e. `HTMLImageElement | HTMLPictureElement` in the above example)

**Actual behavior:** The return type is incorrectly identified as only the asserted type.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#code/PTAEAsEMDcEsDsDmpKgC4E8AOBTFBnfHAJzVgHt5QAjYnSAa33XDwQDMScATUOtAK7EqmXAFgAUCFA4AHrgDGaHnxyDh6bDgBcofGmIJkAH1AB5agCscSydMhKBkADar1IrbtDmrNtJPYBeCUKERx9AAp2cnJdAAkAFQBZABkASQBbSEQcAFFnHAyceDRQU0TUgAVYRzp8wuK0AEpQAG9Jb29YdlAomNAEfUhgnHIeivSsnPqikpb2iU6l0AVKfRpIYlAAXlBo8gA6BWdKHAA5cm4cCJbIZgnM7LyC2bQAbg7l734hKmpNj6LToAX0+3zUvz2MUBoIkdjAUCwuHgzBw0GKAx6aFYmlwBCIpFCA2YQToDig1AK8Jk8j8Kh+GlEOj0BiMZR81lsUjADkELjckKZXg5fgCQRClHQ4TQfVioAeU2eDRK7Im1VqSte8zBmN6+wGKLQwwUo3GyUmTxmjW1QK+DKo+0BX28q0NGy2u32RxO8HOl2ut3u5se0xejSdzvt7oj3lhSyjjskwKAA)

**Related Issues:**

**Comment by ajafff** [comment]
That's because `Object` is a supertype of `string`. This has nothing to do with type assertions or return type inference. Even if you explicitly declare the return type, it will still reduce to `Object`

**Comment by fatcerberus** [comment]
Indeed - subtype reduction

**Comment by birjolaxew** [comment]
@ajafff Is `HTMLPictureElement` also a supertype of `HTMLImageElement`? As you can see [here](https://www.typescriptlang.org/play/#code/PTAEAsEMDcEsDsDmpKgC4E8AOBTFBnfHAJzVgHt5QAjYnSAa33XDwQDMScATUOtAK7EqmXAFgAUCFA4AHrgDGaHnxyDh6bDgBcoABIAVALIAZAJIBbSIhwBRADY4LOeGlAAffcZMAFWEqE7R2dXSWlIAMh7VXURLV1QL1M-ALoHJxc0SXYBeCUKERx8NAAKdnJyXUNTS2sgjNcPJN9-dXqQtABKUABvSUTE2HZQMorQBGLIPJxyYerzKxt0ju6+iQGN0AVKYppIYlAAXlBy8gA6BXtKHAA5cm4cEu7IZnnapeDMgG5+zcT+IRUaj7H7rAYAX1+-zUgJOFVB4KAA), the same behavior is exhibited when using those.

**Comment by fatcerberus** [comment]
According to MDN, `HTMLPictureElement` has no specific properties or methods over its superclass `HTMLElement`.  Therefore under structural typing `HTMLPictureElement == HTMLElement` which in turn *is* a supertype of `HTMLImageElement`.  Huh. 🤯

**Comment by birjolaxew** [comment]
@fatcerberus Although it goes against everything my brain tells me, that *does* kinda make sense. A shame it isn't expressed in TypeScript in a less... confusing manner.
