### ISSUE TITLE
bug when use Exclude and object at the same time

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#32966]
**TypeScript Version:**  3.5.2

**Search Terms:**

**Code**

```ts
const { a } :Exclude<object & { a?: 1 }, any[]> = [];
```

```ts
const { a } :object & Exclude<{ a?: 1 }, any[]> = [];
```

**Expected behavior:**

warn

**Actual behavior:**

no warning, except remove the `object`:

```ts
const { a } :Exclude<{ a?: 1 }, any[]> = [];
```

**Playground Link:** 

**Related Issues:**

**Comment by LongTengDao** [comment]
I write `object & T` in my tsd, because `{}` only require non-nullable value, it's not same with `object`, which require non-primative value.

The examples in this issue which seem redundant is extracted from more complex use, to show the bug more accurate.

**Comment by weswigham** [comment]
See #29317 - today, `Exclude<object & { a?: 1 }, any[]>` is just `object & { a?: 1 }` - you can see as much in quick info in [the playground](http://www.typescriptlang.org/play/#code/C4TwDgpgBAglC8UCiAPAxgGwK4BMIB4B7AIwCsI1goAyKAbygEMB+ALigEYoBfAGiYB2IANoBdAHwBuIA).

**Comment by LongTengDao** [comment]
> See #29317 - today, `Exclude<object & { a?: 1 }, any[]>` is just `object & { a?: 1 }` - you can see as much in quick info in [the playground](http://www.typescriptlang.org/play/#code/C4TwDgpgBAglC8UCiAPAxgGwK4BMIB4B7AIwCsI1goAyKAbygEMB+ALigEYoBfAGiYB2IANoBdAHwBuIA).

@weswigham Thank you! I read the PR follow your guide. But I didn't find information about "Extract" "[]" and "object". Did I missed something? I still can't understand, if this is not a bug, why array can't be excluded from objected interface?

**Comment by weswigham** [comment]
The removal of `any[]` from the input type is only in effect thru the scope of the conditional type - outside of the conditional, we have no concept of what a lone negated bound looks or behaves like - that's what #29317 would provide.

**Comment by LongTengDao** [comment]
@weswigham I suddenly understood! Do you mean that, In typescript, `Exclude<T, U>` will only generate a new type from T removed U, but won't keep `never` information for all rest U properties (which is not in T)?
