### ISSUE TITLE
ThisParameterType always unknown when strictFunctionTypes is disabled

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#32964]
**TypeScript Version:**  3.5.1

**Search Terms:** thisparametertype unknown

**Code**

```ts
interface Foo { blub: string };
function fn(this: Foo) {}

// with strictFunctionTypes ENABLED, this evaluates to Foo.
// with strictFunctionTypes DISABLED, it evaluates to unknown.
type Test = ThisParameterType<typeof fn>; 
```

**Expected behavior:**
`ThisParameterType<typeof fn>` should be `Foo`, regardless of `strictFunctionTypes` setting.

**Actual behavior:**
`ThisParameterType<>` evaluates to `unknown`, always, when `strictFunctionTypes` is disabled. 

**Playground Link:**
https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIHt3IN7IEYA2ArngFzIDOYUoA5sgL4DcAUDESAmMOiMjCAAUYABbAK5DOgCUOBixYB6RcgDuwUZWrAuqDlx4gAKgE8ADhArIAogDkAggCEAMtYAiAGmSjxyCADc4YjhIKzAsKQA6JRV1TSoaXX1uXlMLKzcASQBlJ1dPZA0-QODQ7ywOAGsQdFUQaLBzFCNLMGQAXmQjMQoABTgoOABbCEgoNIgAHkaLdBh+EAA+JmQWIA

**Related Issues:**
404: related issue not found

**Comment by fatcerberus** [comment]
Thanks to @webstrand, the definition of `ThisParameterType`:
```ts
type ThisParameterType<T> = 
    T extends (this: unknown, ...args: any[]) => any 
        ? unknown 
        : T extends (this: infer U, ...args: any[]) => any 
            ? U
            : unknown;
```

The first conditional seems to be checking for functions *without* a `this` binding, but because function types are bivariant by default, this catches *all functions* and defaults to `unknown`.  The correct behavior of this type requires strict contravariance, i.e. `--strictFunctionTypes`.

**Comment by jack-williams** [comment]
What goes wrong if you delete the first conditional?

**Comment by fatcerberus** [comment]
Seems to work fine: [:football: Playground link](https://www.typescriptlang.org/play/?strictFunctionTypes=false#code/C4TwDgpgBAKgFgSwM4AUCGAnNBbCwIYA8MAfFALyxQQAe+AdgCZJQAUwiSAXFAvQGYEoAVQA0UAHRTMAc25Q09EAG0AugEoKZRSCgB+EVB4BXegGt6AewDu9ANwAoB33wZ+aAMbQAYpctQAbwcoKAAjABtjUJ4kYAw+GUcAXyd+Uw9gBEt6KH4-b3p2Th5fS00AlLT6DKyc+mNsAqLkHnrsUIJyyvTM7KgkRSR4ZFYup1BIWAhYgEYKWE50LFxXQgmIS35c-PoSR3Wp2IAmeeHUTBw8AjXwDa22gr2HA5hp4ABmU8WLlev1zf6gzOTyAA)

I was a bit baffled myself why it's implemented as a two-level conditional like this when both `Parameters` and `ReturnType` are only one level.

**Comment by ahejlsberg** [comment]
`ThisParameterType` was written as a two-level conditional in an earlier time when the default inference for type parameters was `any`. We've since changed the default inference to `unknown`, so we can and should simplify the type. Particularly seeing as it doesn't work in its current form with `--strictFunctionTypes` disabled.
