### ISSUE TITLE
transpile API error in 3.6/3.7 dev

### ISSUE THREAD

**Issue by whitecolor** [microsoft/TypeScript#32962]
3.7.0-dev.20190817
```js
const ts = require('typescript')
const source = `const fn = <T>(a: T) => a`
const result = ts.transpile(source, {})
```

`result` is  `var fn = <T>(a: T) => a</>;`
with latest 3.5.3 `result` is `var fn = function (a) { return a; };`

**Comment by IllusionMH** [comment]
Looks like it tries to compile it as JSX. Could you provide more details about your configuration?

**Comment by whitecolor** [comment]
What configuration do you mean? As far as I know, `transpile` here don't use `tsconfig.json` compiler options implicitly. So I believe it should behave this way on any setup with current dev TS servions.

**Comment by whitecolor** [comment]
Oh I managed to make it work if with
```
const result = ts.transpile(source, {jsx: false})
```

**Comment by IllusionMH** [comment]
Oh, forgot that `transpile` uses second argument as params and it was empty.
You can try
```ts
const result = ts.transpile(source, {fileName: 'file.ts'}) // .ts is important
```
so `transpile` won't parse `<T>` as JSX.

If `source` that you compile has JSX tags you can use `{fileName: 'file.tsx'}` instead.

**Comment by whitecolor** [comment]
It should look like this
```js
const result = ts.transpile(source, {}, 'file.ts')
```

Well, in this case, yes result as expected. 

Though I believe it is kind of breaking change in transpile API? But it seems to me that this actually is kind of parser bug, no?

**Comment by RyanCavanaugh** [comment]
This changed at https://github.com/microsoft/TypeScript/pull/31563 - the default JSX mode is `preserve` so we started to parse this as .jsx.

@rbuckton I think this is a fairly dangerous breaking change we should mitigate for 3.6

I'd propose changing line 69 of `transpile.ts`:
```
        const inputFileName = transpileOptions.fileName || (options.jsx ? "module.tsx" : "module.ts");

        const inputFileName = transpileOptions.fileName || (transpileOptions.jsx ? "module.tsx" : "module.ts");
```
so that the file name only gets `.tsx` extension if the caller explicitly opted in to a JSX mode. Thoughts?
