### ISSUE TITLE
Better imports

### ISSUE THREAD

**Issue by oleersoy** [microsoft/TypeScript#32963]
https://medium.com/@ole.ersoy/how-to-make-typescript-es6-imports-better-14e6c6affffb

from '@angular/material' import { MatToolbarModule };

This way we get auto complete while typing the import target.

**Comment by nmain** [comment]
This would be "non-ECMAScript syntax with JavaScript output", one of the no-nos in the template you deleted when you created this issue.

**Comment by RyanCavanaugh** [comment]
We totally agree that TC39 should have done it differently, but here we are. We're committed to not adding non-standard import syntax so this is out of scope for TS.

**Comment by oleersoy** [comment]
Not sure why Typescript cares because no matter what it needs to be compiled / interpreted.  Typescript adds non standard stuff all the time ...

**Comment by nmain** [comment]
Typescript's unique additions to ECMAScript _syntax_ are (almost all) only related to type annotations, its core feature.  In all other ways it leaves syntax up to ECMAScript so as not to conflict with potential future ECMAScript proposals.

**Comment by oleersoy** [comment]
I thought the point of Typescript is to:
- Make code easy to refactor because we have types
- Make developers more productive by providing better tooling

If you focus on improvements to user productivity and code base quality (Code written in Typescript), you'll get a lot more mileage out of Typescript as the user base will grow faster.

Also imports are imports.  In this case all we are doing is flipping the order of the two core segments of the structure.  Typescript can handle either case fine.  Typescript has added a million ways to massage Types.  Why not do this as well?

**Comment by oleersoy** [comment]
> We totally agree that TC39 should have done it differently, but here we are. We're committed to not adding non-standard import syntax so this is out of scope for TS.

[From the Typescript Design Goals (non goals)](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals)

Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.
