### ISSUE TITLE
Formatting of conditionals not consistent with JavaScript conventions

### ISSUE THREAD

**Issue by sourcebits-robertbiggs** [Microsoft/TypeScript#3297]
I know many users of TypeScript are from a C# background and expect to write conditionals like in that language. However, for JavaScript developers the standard for formatting conditionals is different. When TypeScript converts conditionals to JavaScript, it outputs the `else` and `else if` statements like so:
```
}
else if(whatever) {
}
else {
}
```
The normal JavaScript format is:
```
} else if (whatever) {
} else {
}
```
Most teams have coding rules and code review mechanisms in place to make sure these conventions are followed. For a reference on standard JavaScript formatting conventions, please consult Douglas Crockford's guide: http://javascript.crockford.com/code.html. About half way down you'll find the convention for conditionals.

At very least it would be nice to have a flag that we could set to get the expected formatting instead of the C/C# style you are currently producing.

**Comment by kitsonk** [comment]
The one challenge I would have is why would you focus your coding conventions on emitted JavaScript?  Wouldn't you want your linting tools to focus on the TypeScript, where the coders are actually coding?  That is almost akin to worrying about preserving your coding standards when you then concatenate and minimise your JavaScript too...

**Comment by mhegazy** [comment]
as @kitsonk mentioned, output js formatting has not been an area that we invest in; that applies to spaces, new lines, curly positioning, maximum line length... etc. if output formatting is something important to you, you can always add a JS beautifier to your tool chain.

**Comment by kitsonk** [comment]
And [plantir/tslint](https://github.com/palantir/tslint) is a decent linting tool for TypeScript.

**Comment by sourcebits-robertbiggs** [comment]
Actually, I'm the only one doing TypeScript at our company. All our other developers are full stack JavaScript developers. That's not going to change. Even if we use TypeScript for producing JavaScript, it needs to be JavaScript that follows the conventions of all the other thousands of lines of Javascript that we already have. People need to be able to open the JavaScript and quickly analyze it, whether for learning or debugging their own code. 
Besides, we create libraries and frameworks used by other developers. Many of them will use it unmagnified in development.
I'm surprised because I have my conditionals formatted properly in the TypeScript, but they came out differently in the resulting JavaScript. And yes, I can write a gulp task to parse the resulting JavaScript to search and replace all the conditions. Ugh! I'm sure you wouldn't want to have to write a PowerShell script to reformat your C# code because Visual Studio was messing up your formatting.

**Comment by sourcebits-robertbiggs** [comment]
Actually, jsbeautify does solve the problem without having to search and replace, so I'm good with that.

**Comment by llgcode** [comment]
As Robertbiggs, I'm the only one in my company to use typescript and javascript so formatting is important for others that read only the js. Jsbeautify is not a good solution for me cause I use generated sourcemap file .js.map to debug in the navigator. I've chosen typescript cause the generated javascript is pretty, so if you choose to not keep js readable. I'll drop typescript.

**Comment by mhegazy** [comment]
@llgcode tools like [uglify](https://github.com/mishoo/UglifyJS2/) support beautification and sourcemaps support using [--in-source-map](https://github.com/mishoo/UglifyJS2/#composed-source-map). hope that helps.
