### ISSUE TITLE
Generic variable reuse - end up with a wrong type

### ISSUE THREAD

**Issue by nenadvicentic** [microsoft/TypeScript#32971]
**TypeScript Version:**  3.5.3

**Search Terms:**
Generic variable reuse wrong type

**Code**

```ts
abstract class Animal {
    constructor() {
        console.log("Animal");
    }
}

class Penguin extends Animal {
    constructor() {
        super();
        console.log("Penguin");
    }
}

class Lion extends Animal {
    constructor() {
        super();
        console.log("Lion");
    }
}

class Zoo<T extends Animal> {

    constructor(public readonly AnimalClass: new () => T) {
        this.AnimalClass = AnimalClass;
    }
}

let zoo = new Zoo(Penguin);
const penguin = new zoo.AnimalClass(); // `penguin` is of `Penguin` type.

const lionZoo = new Zoo(Lion);
const lion = new lionZoo.AnimalClass(); // `lion` is `Lion` type.

// Error here, when reusing `zoo`.
zoo = new Zoo(Lion);
const lion2 = new zoo.AnimalClass(); // `lion2` is `Penguin` type.
```

**Expected behavior:**
Or `Zoo<Lion>` not to be assignable to `zoo: Zoo<Penguin>` variable, or `new zoo.AnimalClass()` to be infered correctly after variable reassigment.

**Actual behavior:**
TypeScript does not seem to update `zoo` variable generic type and therefore resovled `const lion2` gets resolved into wrong type: `Penguin`.

**Playground Link:** 
https://www.typescriptlang.org/play/#code/IYIwzgLgTsDGEAJYBthjAgggOwJYFthkEBvAKAUqQHttIoBXeaqACgEpSKqfZaxqyAKYA6ZNQDmrAEQ4CRaewDc3SgF8yGsijQYACkOwSGubAiEAPCIYAmGOYWLle-aEwgsOXHjzAMADkJsyqo+fHSCouJS0gZGJtiKKjwaWjroCAAyuLTmVrb2eI7eVOH07p6czj6UfoHByTU0EcJikjLZtEmhqWTaqBkAWtTUADwAKnnW2HZYRUQAfFyhZW7MbP4MIMi4sAhQQsA2tMgAnnPyyADCA2AAXAjYQgDuCF4AvEvjVaE8EAAWuDAIgcRBuugQ7wujnB6Ea6k0fQA9EiEAB1FizNB5QLwIQ2MjCRAALxGkMeLwQw2orDixlMIVWCEC8VM5Ker1J1BB82utw4KiZO1o1PZlOprE62EZrgQwrMUI5cpy2GpPMusLAAuRqIAolAoCwEP8gkIADQIZ4mswHBhgUwSBAAAy5ToQADdgFBcKBWmQuWLXhKpTK6Ih5QAmQMILnqmH85QIFHOyNuoHOukJN0QU6BERAA

**Related Issues:**

**Comment by jack-williams** [comment]
[FAQ: When and why are classes nominal](https://github.com/Microsoft/TypeScript/wiki/FAQ#when-and-why-are-classes-nominal)

**Comment by nenadvicentic** [comment]
@jack-williams Thanks for the clarification. I could not find anything based on my keywords, before I posted this. So nominal types.

It indeed creates error when extra property is added, indeed. I was pretty confused that IDE shows previous type on new variable.
