### ISSUE TITLE
watch mode does not watch json with resolveJsonModule

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#32988]
**TypeScript Version:**  3.5.2

**Search Terms:**
watch json resolveJsonModule

**Code**
run `tsc --watch` with `resolveJsonModule: true`.

```js
// tsconfig.json
{
  "compilerOptions": {
    "resolveJsonModule": true
  },
  "include": [
    "src",
    "src/artifacts/*.json"
  ]
 }
```

**Expected behavior:**
When an included json file is changed, `tsc` will detect it and copy the file to `outDir`.

**Actual behavior:**
didn't happen.

**Comment by sheetalkamat** [comment]
I cannot repro this.. First of all the tsconfig you mentioned only includes the json files from the artificats folder and there is no outDir mentioned and hence the file is not copied. If I add outDir to config it does copy the file to the outDir.
```
c:\temp\test3>node c:\TypeScript\built\local\tsc.js  --listFiles --listEmittedFiles -w
[11:14:00 AM] Starting compilation in watch mode...

TSFILE: c:/temp/test3/bin/something.json
c:/TypeScript/built/local/lib.d.ts
c:/TypeScript/built/local/lib.es5.d.ts
c:/TypeScript/built/local/lib.dom.d.ts
c:/TypeScript/built/local/lib.webworker.importscripts.d.ts
c:/TypeScript/built/local/lib.scripthost.d.ts
c:/temp/test3/src/artifacts/something.json
[11:14:01 AM] Found 0 errors. Watching for file changes.
```
 You would want to verify that your config and provide more details with the actual repro steps.

**Comment by unional** [comment]
When running `tsc`, the files are copied. it only does not copy when running watch mode.

You can check out an example in [`eslint-plugin-harmony`](https://github.com/unional/eslint-plugin-harmony)
