### ISSUE TITLE
tsc is slow to process lib.d.ts

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#3298]
tsc is pretty slow for me with an empty input file:
```
$ time tsc
real    0m0.450s
user    0m0.418s
sys    0m0.013s
$ touch in.ts
$ time tsc in.ts
real    0m2.796s
user    0m3.810s
sys    0m0.042s
```
but gets faster again with `--noLib`:

```
$ time tsc in.ts --noLib
real  0m0.591s
user  0m0.549s
sys  0m0.022s
```

Context: In my case I'm running tsc on independent libraries, chained together by generated `.d.ts` files, and with a remote filesystem. I observe 6-7s for each tsc invocation, and these are serialized to a 28s user-perceived latency for the build.

I noted that there are existing proposals to split up `lib.d.ts`, but assuming I am targetting a browser I think I'll have a `lib.dom.d.ts` that is not much smaller than the one in the current distro. So I think compressing the libs is not a strategy.

I wonder if we could run tsc with the current lib.d.ts already loaded, maybe using the snapshotting feature of the language services? I can see from profiling that even this null build is spending all its time type-checking the `lib.d.ts`. It would be better to start a compiler process that is already warmed up past that point.

**Comment by mhegazy** [comment]
What is the version of node are you using?

**Comment by tinganho** [comment]
I also encountered this. I think storing a "parsed" version of `lib.d.ts` would significantly improve the compiler speed. Like from `1.0` -> `1.1`.

**Comment by alexeagle** [comment]
`--noLibCheck` from https://github.com/Microsoft/TypeScript/pull/3049 looks pretty helpful.

This was with node 0.10.33

**Comment by mhegazy** [comment]
Most of the time spent compiling a program is typechcking, and every program has at least the library. so having most of the  time compiling an empty file spent in checking the library is what i expect. @DanielRosenwasser can add the `--noLibCheck` today, which should help with this. in general it not safe to skip checking the library, as interfaces can be reopened in a way that can make inheriticance hirarchy in the DOM generate errors. this is however is very rare to happen, and if you need a quick turnaround `--noLibCheck` should be good enough.

6-7 secs, however, seem alarming. on my machine it is in 1s range, which is what i expect. is there any thing special about your machine? have you seen this perf degradation in recent changes?

**Comment by DanielRosenwasser** [comment]
I was considering mentioning `--noLibCheck` here, but my impression was that it was going to be an "internal-ish experimental flag". Still, it should definitely help out pretty decently.

**Comment by alexeagle** [comment]
I don't have any hints about when this might have been introduced. I could
try reproducing with older versions - is there a particular SHA where I
should try that? Maybe just the last beta release to npm?

The machine where this is running is inside google's distributed build
system, so it's a prod machine in a datacenter with some extra sandboxing
and constraints wrapped around the process (tries to limit to one CPU for
example). The machine is likely loaded with many other users requests at
the same time.

**Comment by mhegazy** [comment]
latest beta would be a good reference point.

**Comment by alexeagle** [comment]
Yeah I can repro with https://github.com/Microsoft/TypeScript/tree/v1.5.0-beta as well.

**Comment by mhegazy** [comment]
@alexeagle give this a try https://github.com/Microsoft/TypeScript/commit/223d26f53566160153afc1b83f7e44b5a2eb390d

**Comment by alexeagle** [comment]
Thanks @mhegazy
I added `--skipDefaultLibCheck` to our internal distributed build system, and I'm still seeing about 6s to run the compiler on a very small input. But it's around 1s with `--noLib`.

Locally on my MacBook I have trouble reproducing the problem now, with various versions of node and tsc.

I think we need to gather more diagnostics on why our build environment is so slow.

**Comment by DanielRosenwasser** [comment]
@alexeagle sounds like you might be having an IO problem? From my understanding `--noLib` won't actually load `lib.d.ts` whereas `--skipDefaultLibCheck` will still read/parse, but lazily type-check. Still, that sounds strange.

**Comment by mhegazy** [comment]
we will need more info about what is happening on the machine, to see what can be done. if these machines have IO limitations, we can always have a long running process that parses lib.d.ts once and caches it.

**Comment by mhegazy** [comment]
looks like this was handled by `--skipDefaultLibCheck`, please reopen if this is not the case.

**Comment by alexeagle** [comment]
Indeed our compilations are now acceptably fast.
