### ISSUE TITLE
JS Crash: global type reference to constructor function

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#32997]
From chrome-devtools-frontend's failure in https://github.com/microsoft/TypeScript/pull/32991:

```js
// @Filename: test.js
var SDK = {}
SDK.SourceMap = function () { }
SDK.SourceMap.prototype = { compiledURL() {} }

// @Filename: other.js
/**
 * @param {SDK.SourceMap} sourceMap
 */
function no(sourceMap) {
  return sourceMap.wat
}
```

**Expected behavior:**
no crash and a bunch of errors

**Actual behavior:**
assert from merging a symbol into itself. it looks like both the `function () {}` and `SDK.SourceMap` lhs of assignment get the prototype method in the binder.

**Comment by sandersn** [comment]
Looks like we don't cache correctly and try to merge into the same symbol twice.

**Comment by sandersn** [comment]
Welp @weswigham, looks like I found a reason I need caching in mergeJSSymbols; you'll often want to get the `type` and `declaredType` both from a symbol, and both code paths call mergeJSSymbols. We want to avoid double-merging any particular symbol into the combined symbol.

**Comment by weswigham** [comment]
Thereeeeeeee we go. I figured there had to be a reason. XD

**Comment by sandersn** [comment]
Also, bonus crash, if you leave out `compiledURL` then the cloned target doesn't get an empty map for `members` and crashes in getIndexType.
