### ISSUE TITLE
Type Iterator#next() argument (yield expression)

### ISSUE THREAD

**Issue by pauldraper** [microsoft/TypeScript#32998]
## Search Terms

Iterator.next() type, yield expression type

## Suggestion

Type `Iterator.next()`/`yield`. I suggest Iterator<A, B>, where `A` is the input type, and `B` is the output type.

Mentioned in #10148 and #14883.

Required by #32283.

Alternative proposal in #32523, those this requires more drastic changes to TypeScript's type model.

## Use Cases

Pretty self-explanatory; I want typed expressions. It's why I use TypeScript.

And currently, all `yield ...` expressions have *no* typing. (They are typed as `any`).

## Examples

```ts
function* totalLength() {
  let result = 0;
  while (true) {
    result += (yield result).length;
}

const t = totalLength();
t.next('abc'); // 0
t.next('def'); // 3
t.return(''); // 6
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by pauldraper** [comment]
And actually, Iterator has additional problems, like `return?(value?: any): IteratorResult<T>` which is just simply wrong.

To be more concrete, the types should be

```
interface Iterator<T> {
    next(): IteratorResult<T>;
}

interface Generator<A, B> extends Iterator<B> {
    next(value?: A): IteratorResult<B>;
    return<T>(value?: T): IteratorResult<T>;
    throw(e?: any): IteratorResult<B>;
}
```

The optional argument is problematic for having non-undefined values inside the generator, but I don't have a better suggestion.

**Comment by AlCalzone** [comment]
> And currently, all `yield ...` expressions have _no_ typing. (They are typed as `any`).

I think you should take a look at the TS 3.6 release notes
https://devblogs.microsoft.com/typescript/announcing-typescript-3-6-rc/

**Comment by RyanCavanaugh** [comment]
See #30790 and its linked issues

**Comment by pauldraper** [comment]
Excellent, thanks @AlCalzone for linking to the 3.6 RC notes.

@typescript-bot I think you might not be working correclty.
