### ISSUE TITLE
Syntactic sugar for mapping public properties during class instantiation

### ISSUE THREAD

**Issue by GabeKuslansky** [microsoft/TypeScript#32994]
## Search Terms

syntactic sugar class instantiation constructor map

## Suggestion

When you instantiate a class, some situations call for mapping public fields, and it can often be a repetitive process. Rather than having an inherent distinction between instantiation and property assignments, like this code

```ts
// Step 1
const user = new User();

// Step 2
user.firstName = 'John';
user.lastName = 'Doe';
user.age = 21;
user.purchases = purchaseRepository.getPurchases(user);
```

Create this syntax that transpiles to the prior code
```ts
const user = new User() {
  firstName = 'John', // don't need to type user.firstName
  lastName = 'Doe',
  age = 21,
  purchases = purchaseRepository.getPurchases(user);
}
```

If it has a parameterless constructor, the parenthesis can be omitted
```ts
const user = new User { // don't need User()
  firstName = 'John',
  lastName = 'Doe',
  age = 21
  purchases = purchaseRepository.getPurchases(user);
}
```
## Use Cases
Code is more concise. It is extremely redundant to have to type the name of your reference to the instantiated class for each property you are mapping. In situations where you map DTO's, you can save a lot of time/space with mapping in the new syntax.

## Examples
Clean and concise
```ts
const userDto = new UserDto {
  firstName = 'John',
  lastName = 'Doe',
  age = 21,
  purchases = user.purchases.map(p => new purchaseDto {
      sku = p.sku,
      purchaseDate = p.purchaseDate
  }
}
```

Harder to read
```ts
const userDto = new UserDto();
userDto.firstName = 'John';
userDto.lastName = 'Doe';
userDto.age = 21;
userDto.purchases = user.purchases.map(p => {
  const purchaseDto = new PurchaseDto();
  purchaseDto.sku = p.sku;
  purchaseDto.purchaseDate = p.purchaseDate;
  return purchaseDto;
});
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #16737

**Comment by poseidonCore** [comment]
Jump straight to the end comment for the best resolve for this matter:

https://github.com/microsoft/TypeScript/issues/16737#issuecomment-506045131

It would be great to have, but it should really originate in underlying ECMAScript standards first.
