### ISSUE TITLE
Returning expression gives max depth error; assigning expression to temporary variable and returning that does not

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#33002]
**TypeScript Version:**  3.5.1

**Search Terms:**

return expression, return variable, max depth

**Code**

#### TODO: Add small repro

I know how you all **hate** issues without a simple repro.
The code is quite complex at the moment. So, I'll try and simplify it.
But I decided to file the issue first because I don't quite understand what I'm seeing.

![image](https://user-images.githubusercontent.com/5655961/63410002-49c07e80-c3c0-11e9-9807-68fcc611ca60.png)

For now, here is a link to my repo that has this problem,
https://github.com/AnyhowStep/tsql/blob/137590fe209f4f73034d13938ec90899919ff7af/test/compile-time/input/from-clause/inner-join/basic.ts#L23

1. Clone repo
1. Checkout commit `137590fe209f4f73034d13938ec90899919ff7af`
1. `npm install`
1. Open the file linked above (`test/compile-time/input/from-clause/inner-join/basic.ts#L23`)
1. Observe first snippet has max depth error
1. Observe second snippet **does not** have max depth error

**Expected behavior:**

Both snippets are the same, semantically.
The only difference is whether I return `tsql.eq()` directly or not.

So, both snippets should either resolve fine or both snippets should give me a max depth error.

**Actual behavior:**

+ Returning an expression gives me a max depth error.
+ Assigning the expression to a temporary variable and returning that resolves fine.

By the way, `tmp` resolves to,
```ts
const tmp: tsql.ExprImpl<tm.Mapper<unknown, boolean>, tsql.IUsedRef<{
    readonly myTable: {
        readonly myTableId: bigint;
    };
    readonly otherTable: {
        readonly otherTableId: bigint;
    };
}>>
```

**Playground Link:**

#### TODO Add small repro

**Related Issues:** 

I have no clue

**Comment by AnyhowStep** [comment]
I left my laptop charger at work and my laptop's battery died.

I think it has something to do with my `Comparison` type and the expected return type of the callback function `OnDelegate<>`

**Comment by AnyhowStep** [comment]
![image](https://user-images.githubusercontent.com/5655961/63447166-8bc1e280-c409-11e9-9f9b-e1afea1d2c7a.png)

Getting closer with that repro...

**Comment by AnyhowStep** [comment]
Seems like the max depth error only happens to the first instance of the problem.

![image](https://user-images.githubusercontent.com/5655961/63450585-51a80f00-c410-11e9-9750-91def16ef20c.png)

![image](https://user-images.githubusercontent.com/5655961/63450598-579df000-c410-11e9-96e8-f05ca1299f7e.png)

**Comment by AnyhowStep** [comment]
Closer and closer...

![image](https://user-images.githubusercontent.com/5655961/63450871-ff1b2280-c410-11e9-8298-697370b9bde8.png)

**Comment by AnyhowStep** [comment]
If I remove the explicit type annotation, it resolves to the same type with no max depth error,
![image](https://user-images.githubusercontent.com/5655961/63450933-1a862d80-c411-11e9-82a3-45e342279334.png)

**Comment by AnyhowStep** [comment]
Copy-pasting my thoughts from Gitter,

I think the problem is checking assignability
Not necessarily the type resolution

Because my initial problem was that a function was expecting a callback function to have a certain return type
And my callback function has no explicit type annotation

However, TS still has to check that the result of my return statement is assignable to the expected return type

When I did `const tmp = tsql.eq(); return tmp` it would somehow short-circuit the whole thing

It infers the type of tmp
It realizes tmp is assignable to the expected return type

Maybe it can only do type resolution on its own only, or assignability check only, but not both?
Both at the same time*
So, splitting into two statements is fine

**Comment by RyanCavanaugh** [comment]
A possible cause here is that the expression of a `return` statement gets contextually typed by the return type of the containing function (which in turn can come from another contextual type); this contextual type also serves as a generic inference candidate and can thus ultimately influence the type of any contextually-sensitive arguments to the function, as well as the overall type of the entire expression tree.

**Comment by AnyhowStep** [comment]
I've got it down to the point where I don't need a function or generics.
Well, I guess `eq` is a generic function.

```ts
/**
 * A column of a table
 */
declare const myTableId : tsql.IColumn<{
    tableAlias: "myTable";
    columnAlias: "myTableId";
    mapper: Mapper<unknown, bigint>;
}>;
type Expected = tsql.ExprImpl<
    Mapper<unknown, boolean>,
    tsql.IUsedRef<{
        readonly myTable: {
            readonly myTableId: bigint;
        };
    }>
>;
//Error, max depth error
const blah : Expected = eq(
    myTableId,
    myTableId
);
//Assign to temporary variable
//Let the type of the variable be inferred
const tmp = eq(
    myTableId,
    myTableId
);
//OK!
const blah2 : Expected = tmp;

```

**Comment by AnyhowStep** [comment]
So, I don't understand anything anymore.

While trying to expand the type manually and **simplify** the repro, I got desperate and thought to myself,
> What if I make the type **more complex**?

It worked. As in, I no longer get the max depth error after adding an extra layer of conditional types.

I... I just don't get it （ ＴДＴ）

-----

The `eq` function was basically,

```ts
export type Comparison =
    <
        LeftT extends RawExpr<NonNullPrimitiveExpr>,
        RightT extends RawExpr<RawExprUtil.TypeOf<LeftT>>
    >(
        left : LeftT,
        right : RightT
    ) => (
        Expr<{
            mapper : tm.SafeMapper<boolean>,
            usedRef : RawExprUtil.IntersectUsedRef<
                    | LeftT
                    | RightT
                >,
        }>
    )
;
declare const eq : Comparison;
```

So, you pass it a `LeftT` expression and a `RightT` expression.
Then, it returns a new expression of type `boolean` that references the columns of both `LeftT` and `RightT`.

If `LeftT` is an expression of type `1|2|3`, then `RightT` must be an expression that is a subtype of `1|2|3`. Simple enough.

-----

I changed the `RightT` constraint to,
```ts
RightT extends RawExpr<
  PrimitiveExprUtil.NonNullPrimitiveType<
    RawExprUtil.TypeOf<LeftT>
  >
>
```

If `LeftT` is an expression of type `1|2|3`, then `RightT` must be an expression that is a subtype of `number`.
Because, intuitively, the non-null primitive type of `1|2|3` is `number`.

-----

I don't know why this works. I have learned nothing from this experience =(

In trying to manually expand my types, I've found that I'm nesting about 10+ conditional types. But adding an extra one fixes it.

**Comment by RyanCavanaugh** [comment]
@AnyhowStep please unassign once you have something concrete you want us to look at. Thanks!
