### ISSUE TITLE
Can't export a property from a namespace

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#33005]
**TypeScript Version:**  3.5.3

**Search Terms:** export property from namespace

**Code**

```ts
namespace X {
	export const foo: string = '';
}

export { X.foo as foo };
```

**Expected behavior:**

Allows the export

**Actual behavior:**

Produces an error

**Playground Link:** 

https://www.typescriptlang.org/play/#code/HYQwtgpgzgDiDGEAEANJBvAUASAgDxgHsAnAFyXkOCnIDNDCAuJG4gS2AHMkBeJAcn4BuTAF9MmfETIZUAOnqEkIKEkVJRQoA

**Comment by RyanCavanaugh** [comment]
Dotted names are not allowed in this position, only identifiers. Refer to the ES spec:

https://www.ecma-international.org/ecma-262/10.0/index.html#prod-ExportDeclaration

**Comment by dbaeumer** [comment]
Thanks!
