### ISSUE TITLE
Missing references in some cases

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#33017]
**TypeScript Version:**  3.5.2

**Search Terms:**

**Code**

We have some code that looks like this:

`./main.ts`:

```ts
import { types } from './types';

type Test = types.Foo;
```

`./types/index.ts`:

```ts
import * as types from './types';
export { types };
```

`./types/types.ts`:

```ts
export type Foo = 1;
```

When I try to find references for `Foo`, I'm getting no results. "Go to definition" _does_  still work.

However, I can only reproduce this behaviour in our large TS project. I've tried and failed to create a reduced test case. If I start removing files from our large TS project, it will eventually begin to work, suggesting there's some sort of (memory?) threshold which we could be crossing.

Here is a video recording to demonstrate this: https://www.dropbox.com/s/xw7c3lk0mxhr5vj/Screen%20Recording%202019-08-21%20at%2021.40.59.mov?dl=0

I have also attached a TS server log, which was recorded at the same time as the above video.

Any ideas what could be going on here? What's the best way for me to debug this?

[tsserver.log](https://github.com/microsoft/TypeScript/files/3527222/tsserver.log)

**Comment by sheetalkamat** [comment]
Can you please share the screen recording and tsserverlog again. (The screen share link is not working so I cant figure out what you expect and what is happening.)

**Comment by OliverJAsh** [comment]
Just found another bug which _might_ be related: https://github.com/microsoft/TypeScript/issues/33489

**Comment by sheetalkamat** [comment]
@OliverJAsh From the log it looks like when finding references its hitting the assertion. We would need code sample to investigate so please provide small repro if you can or you can share your source code. We can get NDA for getting the repro project if you need to. Thanks.

**Comment by OliverJAsh** [comment]
I would be happy to share my code, it's in a private GitHub repository. I
guess I'll need an email address from you, for me to add to it?

I tried creating a reduced test case but it was too difficult unfortunately.

**Comment by sheetalkamat** [comment]
email is `shkamat at microsoft dot com`

**Comment by OliverJAsh** [comment]
Hi @sheetalkamat, I have sent an NDA to you and @DanielRosenwasser.

**Comment by OliverJAsh** [comment]
@sheetalkamat I have sent you an invite to access the repo.

To test this issue, the file I used in my video is located at `app/routes/Explore/LandingPage/components/PopularCategories/PopularCategories-helpers.ts`.

**Comment by OliverJAsh** [comment]
@sheetalkamat Sorry I forgot to mention, this is on the `maintenance/named-namespace-imports-landing-pages` branch.

**Comment by sheetalkamat** [comment]
@OliverJAsh Thank you for providing details. I was able to repro this and will look into this soon.
