### ISSUE TITLE
String enum by default

### ISSUE THREAD

**Issue by garrettmaring** [microsoft/TypeScript#33015]
## Search Terms

enum,string,string enum

## Suggestion

I find myself often writing something like this:

```typescript
enum ButtonType {
  Primary = "Primary",
  Secondary = "Secondary",
}
```

I believe some simple syntactic sugar around the above code would slightly boost productivity for those using TypeScript.

## Use Cases

For my use cases, I write most enums in the above fashion. Aside from debugging, my most common case is generating HTML tag class names from an enum.

Take the popular [classnames](https://github.com/JedWatson/classnames#dynamic-class-names-with-es2015) package from [Jed Watson](https://github.com/JedWatson). The documentation shows the following example:

```javascript
let buttonType = 'primary';
classNames({ [`btn-${buttonType}`]: true });
```

In TypeScript:

```typescript
enum ButtonType {
  Primary = "Primary",
  Secondary = "Secondary",
}
let buttonType = ButtonType.Primary
classNames({ [`btn-${buttonType.toLowerCase()}`]: true });
```

## Examples

I have no good ideas about what the syntax for this would look like. This suggestion comes purely from my experience programming in TypeScript and not from any principles (or lack thereof) of language design.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [-] This could be implemented without emitting different JS based on the types of the expressions. ***if opted in, the generated values would have strings(string enums)***
* [-] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.) ***if opted in, the enum values would have strings(string enums)***
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
Does this match your suggestion? #16464

**Comment by garrettmaring** [comment]
@jack-williams ah, it does. My searching failed me. We can close this ticket as a duplicate as there has already been discussion there.
