### ISSUE TITLE
Symbolic links are not followed when enumerating files

### ISSUE THREAD

**Issue by OleksandrChekhovskyi** [Microsoft/TypeScript#3301]
When using tsconfig.json without explicit `files` key, it's not possible to use symbolic links to share files across projects in a single source tree, as they will be skipped by the `readDirectory` function.

As a simple example of such a setup, see https://github.com/OleksandrChekhovskyi/ts-symlinks

The problem was introduced in this commit: https://github.com/Microsoft/TypeScript/commit/25e52a3975bfb7774323931bc1b5b7b438622dfa

**Comment by Ciantic** [comment]
Also `npm link` command, which uses symbolic links to allow sharing module especially for local development does not seem to work anymore, I think it worked before.

**Comment by danquirk** [comment]
To would be implementers note Anders comments in the referenced commit: https://github.com/Microsoft/TypeScript/commit/25e52a3975bfb7774323931bc1b5b7b438622dfa

**Comment by mhegazy** [comment]
fixed by @OleksandrChekhovskyi.
