### ISSUE TITLE
es3/es5 inheritance bug

### ISSUE THREAD

**Issue by elderapo** [microsoft/TypeScript#33023]
**TypeScript Version:**  all versions

**Search Terms:** es3 es5 inheritance bug

**Code**

```ts
class SomeClass extends Object {}

const instance = new SomeClass();

console.log(instance instanceof SomeClass);
console.log(instance instanceof Object);
```

**Expected behavior:**
For every compilation target desired output is:
```
true
true
```

**Actual behavior:**
If the compilation target is set to `es3` or `es5`:
```
false
true
```
**Playground Link:** https://typescript-play.js.org/?target=1#code/MYGwhgzhAEDKD2BbApgYXFayAeAXZAdgCYwDyARgFbLC7QDeAvgFAD0r0okMCK63DFs2DwCEOvGgBeaAWQB3OEjQYIACgCUAbmbDREeCGQA6EPADmayQEsxuMAWDJ4AMyV9V2vWMMmzlmzsHJ1doCmpaDSA

**Comment by elderapo** [comment]
Emitted code for `es5`:
```js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var SomeClass = /** @class */ (function (_super) {
    __extends(SomeClass, _super);
    function SomeClass() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return SomeClass;
}(Object));
var instance = new SomeClass();
console.log(instance instanceof SomeClass);
console.log(instance instanceof Object);
```

Changing 12th line from:
```js
d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
```

to

```js
d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype);
```
fixes the issue but not exactly sure what `new __()` is supposed to do there.

Also, it's probably worth mentioning that I only managed to reproduce this bug when extending native `Object`.

**Comment by nmain** [comment]
Is this just https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work ?

**Comment by elderapo** [comment]
Oh... I've seen that one before. I thought it was only the case when extending `Error`...

Any idea what is the point of `new __()` on 12th line? Without it above code works just fine. Also it seems to fix all the issues listed [here](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work).

**Comment by ExE-Boss** [comment]
`new __()` creates a new object with `b.prototype` as its prototype, which is necessary so that adding properties to `d.prototype` doesn't also add them to `b.prototype`.
