### ISSUE TITLE
Github is bought by Microsoft. So we don't have freedom of speech

### ISSUE THREAD

**Issue by nocord** [microsoft/TypeScript#33024]
They have banned two of my account

**Comment by AnyhowStep** [comment]
```sql
UPDATE
  `user`
SET
  `banned` = TRUE
WHERE
  `username` = 'nocord'
```

**Comment by nocord** [comment]
Microsoft sucks

**Comment by nocord** [comment]
Our country shamelessly use Microsoft's proprietary software. Shitty Government.
They teach us to use proprietary software in our schools and colleges, also in the books.

**Comment by nocord** [comment]
The government of .....

**Comment by nocord** [comment]
Sorry i can't tell. But it is so bad

**Comment by jack-williams** [comment]
This thread isn't constructive: locking this until Redmond and the team come online.

/cc @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
Amazing

**Comment by RyanCavanaugh** [comment]
Good morning @jack-williams 👋
