### ISSUE TITLE
Named tslib imports cause webpack bundle size increase

### ISSUE THREAD

**Issue by MLoughry** [microsoft/TypeScript#33035]
**TypeScript Version:**  3.6.1-rc

**Search Terms:**
tslib

**Expected behavior:**
#32742, which changes all `tslib` imports from namespace imports to named imports, would have decreased bundle size in webpack builds from typescript code

**Actual behavior:**
Due to a quirky workaround in `webpack`, all function invocations of named harmony imports are wrapped in an `Object()` constructor; as a result, #32742 actually *increases* bundle size (to the tune of ~9kB in Outlook Web boot bundles)

Since the PR was an attempt specifically to help webpack, and @sokra claims that tree-shaking works even with namespace imports, I think the change should be reverted.

**Related Issues:** 
webpack/webpack#9615

**Comment by MLoughry** [comment]
@rbuckton

**Comment by RyanCavanaugh** [comment]
Why isn't this a webpack bug?

**Comment by MLoughry** [comment]
I opened a bug against webpack (webpack/webpack#9615). However, they state that it's a needed workaround.

I figured that since this was a change in Typescript that had the opposite effect than intended, it was worth filing here.

**Comment by RyanCavanaugh** [comment]
Makes sense.

@tommytroylin @thelarkinn @RikkiGibson anyone care to weigh in? I don't like to flip-flop but it seems like we may have operated on some outdated advice?

**Comment by sokra** [comment]
``` js
import * as ns from "module";
import { abc } from "module";

console.log(ns.abc, abc);
```

Both can be tree-shaken equally. This has always been the case.

Some claims say that namespace objects are not tree-shake-able, but this is only true when using the namespace object directly, without accessing a property of it.

``` js
import * as ns from "module";

console.log(ns); // <- all exports of module are included, tree-shaking disabled
```

**Comment by sokra** [comment]
When calling imported variables the call context (`this` in the function) depends on the way you call a function. webpack do retain the way it's called, which leads to more generated code when called without namespace object.

``` js
import * as ns from "module";
import { abc } from "module";

ns.abc(); // -> MODULE.abc()
abc(); // -> Object(MODULE.abc)() or (0,MODULE.abc)()
```

**Comment by RikkiGibson** [comment]
Seems like if we can demonstrate that the expected tree-shaking occurs for consumers, using tsc targeting es2015 before #32742 and webpack, then we should revert the change.

If the unused tslib imports are not being tree-shaken then let's make sure we know why. Maybe some inadvertent misconfiguration or old versions of the tools was causing unused parts of tslib to be included in user bundles. I assume tsc will never generate code which passes the tslib import as an argument or something similar.

**Comment by sokra** [comment]
The tslib.es6.js file is fine, tree-shaking should work here. Note that webpack need to put into production mode to tree-shake it.

**Comment by RikkiGibson** [comment]
I created a demo https://github.com/rikkigibson/tslib-shake-test which seems to demonstrate that tslib imports can be shaken at least some of the time when the `import * as tslib_1` syntax is used.

Someone who knows the emit strategy for tslib helpers may want to take a deeper look to ensure that the imported module is used in a "shakeable" way as much as possible, i.e. the `tslib_1` or equivalent object is never passed as a method argument, etc.

**Comment by tommytroylin** [comment]
according to @sokra and my test based on @RikkiGibson 's demo

latest `webpack@4` has already support tree-shaking something like `tslib_1.__assign` 

@sokra I could barely remember when tree-shaking comes out on `webpack@2or3`, namespace imports are not shakeable. I'm not sure.

back to #16999, I can't reproduce that build now but we actually notice that behaviour years ago. 

IMO, if tests confirm that on `webpack@3or4` with proper configs tree-shaking works as expected. Reverting that outdated optimization is acceptable.
