### ISSUE TITLE
Narrow variable type with `in` operator on const asserted objects

### ISSUE THREAD

**Issue by JamesYFC** [microsoft/TypeScript#33039]
## Search Terms
`in` operator type narrow 

## Suggestion
I know that we can narrow the type of the object that we're looking at if we use
`if ('someKey' in someObject)`. 

Would it be possible to narrow the type of a variable we test against a const asserted object with the `in` operator?

eg.
```ts
let key: string = 'asdf';
 
const testObj = <const>{
    a: 'someVal',
    b: 'someVal'
}

if (key in testObj){
    // key type is still string, not 'a' | 'b'
    testObj[key] // error
}
```

example with type unions
```ts
let key: 'a' | 'b' | 'c' = ...;
 
const testObj = <const>{
    a: 'someVal',
    b: 'someVal'
}

if (key in testObj){
    key // key should be 'a' | 'b'
    testObj[key] // error
}
```

Perhaps this can be done for non-const asserted objects as well, not sure.

## Use Cases
If a variable I check with `in` against a const asserted object passes, then I can use that narrowed key. 

## Examples

See above

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This would be an incorrect narrowing because types aren't sealed:
```ts
function fn(x: { a: string, b: string }, y: string) {
  if (y in x) {
    const m: "a" | "b" = y;
  }
}
const obj = { a: 1, b: 2, c: 3 };
// Legal call causes value 'c' to be assigned to variable of type "a" | "b"
fn(obj, "c");
```

**Comment by JamesYFC** [comment]
In that situation yes, the case I'm citing is when the object is used directly though - when there is nothing between when it is created with a const assertion and where it is used. i.e. a direct `export const someObj`

Is there another solution to check and infer a value's type against a potentially large list of keys/constants? Neither manual casting nor a large series of literal comparisons seems ideal.

**Comment by JamesYFC** [comment]
Also same question regarding enums
