### ISSUE TITLE
ES6 export variable binding incorrect post increment

### ISSUE THREAD

**Issue by lkho** [microsoft/TypeScript#33044]
**TypeScript Version:**  3.5.1 (playground)

**Search Terms:**
export let binding variable reference

**Code**

```ts
let a = 1
export {a}
console.log(a++)
```

**Expected behavior:**
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAhhC8EEYBQIAeAHA9gJ0gbygF8kBjTAOwGdNQA6YTAcwAooBqNgSiSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.5.5&externalPlugins=

should output `1`

**Actual behavior:**
`2` is output
`a++` post-increment becomes `(a += 1)` pre-increment

**Playground Link:**
http://www.typescriptlang.org/play/?target=1#code/DYUwLgBAhhC8EEYCwAoEAPADgewE6QG8oBfVAY2wDsBnbUAOmGwHMAKKAag4EpUg

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/33043

**Comment by ajafff** [comment]
Fix is up at #35906
