### ISSUE TITLE
ReturnType<F> in parameter of generic function breaks inference when `F` has one implicitly typed param

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#33042]
**TypeScript Version:**  3.5.1

**Search Terms:**

+ ReturnType
+ Implicit type annotation
+ Generic function
+ Parameter

**Code**

This is me opening a new issue for https://github.com/microsoft/TypeScript/issues/29133

I have three separate code snippets, please bear with me =(

```ts
//Innocent enough.
//Returns a T
type Callback<T> = (...args : any[]) => T;

declare function noReturnTypeInParam<
    F extends Callback<3|5>
>(f: F): ReturnType<F>

//Expected: const noArg: 3
//Actual  : const noArg: 3
const noArg = noReturnTypeInParam(
    //Return type is 3 
    () => 3
);
//Expected: const withArg: 3
//Actual  : const withArg: 3
const withArg = noReturnTypeInParam(
    //Return type is 3 
    t => 3
);

```
[Playground](http://www.typescriptlang.org/play/#code/PTCSDtwewYwU3AFwAQKgVwOYAsB0BYAKBACU5F0AncAZ2QENkAVIxATwAc5kBhegG34AjejADWAHiYA+ZAF5kAClwr6lTHQBcDcGwDaAXQCU82UwDcRIgBM4Mfmu4AzdOBiIAllHDJoZCtRMnHAQAApq9AC2EkTIccgAYqgAHogI1nR8giLiEgDMAD4ArNJE0opO2glG2v5U4EFcEgmlhEQgAKLJXO5w1tow3jQo0ACC6tp57cCj7ugCcQNDI1DjmJNEg7Qra-K+UHWBwWERkYqx8aTk9cjsXMgedHnIF3GKJnKyU4RGlsTAXR6aX6yC2w2QAHcPIhsGsNv9ZhQFsglttIdDYRNkN8wSgoTDdgo-NcjlwTpQoudCPFkFcAj47txHtiXtT4ihPtiiL8iEA)

```ts
//Innocent enough.
//Returns a T
type Callback<T> = (...args : any[]) => T;

//Forgive the contrived example
declare function withReturnTypeInParam<
    F extends Callback<3|5>,
>(
    f: F & (
        ReturnType<F> extends 3 ?
        unknown :
        [
            "Only 3 allowed, received",
            ReturnType<F>
        ]
    )
): ReturnType<F>

//Expected: const noArg: 3
//Actual  : const noArg: 3
const noArg = withReturnTypeInParam(
    //Return type is 3 
    () => 3
);
//Expected: const withArg: 3
//Actual  : const withArg: 3|5
const withArg = withReturnTypeInParam(
    /*
        Expected: No error
        Actual  :
            Argument of type
            '(t: any) => 3'
            is not assignable to parameter of type
            'Callback<3 | 5> & ["Only 3 allowed, received", 3 | 5]'.
    */
    //Return type is `3`
    //function(t: any): 3
    t => 3
);

//Expected: const withArgAndExplicitReturnTypeAnnotation: 3
//Actual  : const withArgAndExplicitReturnTypeAnnotation: 3|5
const withArgAndExplicitReturnTypeAnnotation = withReturnTypeInParam(
    /*
        Expected: No error
        Actual  :
            Argument of type
            '(t: any) => 3'
            is not assignable to parameter of type
            'Callback<3 | 5> & ["Only 3 allowed, received", 3 | 5]'.
    */
    //We *force* the return type to be 3
    //Return type is `3`
    //function(t: any): 3
    (t) : 3 => (3 as 3)
);

//Expected: const withExplicitlyTypedArg: 3
//Actual  : const withExplicitlyTypedArg: 3
const withExplicitlyTypedArg = withReturnTypeInParam(
    /*
        Expected: No error
        Actual  : No error
    */
    //Return type is `3`
    //function(t: any): 3
    (t : any) => 3
);

```
[Playground](http://www.typescriptlang.org/play/#code/PTCSDtwewYwU3AFwAQKgVwOYAsB0BYAKBACU5F0AncAZ2QENkAVIxATwAc5kBhegG34AjejADWAHiYA+ZAF5kAClwr6lTHQBcDcGwDaAXQCU82UwDcRIiABiUdQEsAbt0TZuMKEkrO4AE1QAD3oAWw5+OCI-OBh+NW4AM3RwGEQHL2QAdwc3MgpqJk44CAAFNVCJImRq5BsgxAQ-Oj5BEXEJAGYAHwBWaQAaImlFKpqE7TqAMiVRmpq8qnBCrgkbWThAhvAm5A7kAH5ZueRksWhM8GRNI7m9G+PqgCIAeXB+Nl2GQShM-37kSgxOC+PyPQaEB4PBYFIqraT3aoGI5GIhGbTQpawtZWYjAACigS4qX82k8tBQ0AAguptB1rMBKal0AJqqSvDQKVBqZhaUQyRzkFT1PIsjlsBjlsVwGVKKERhCaqRyItkOwuMgHHQ9kdFCY5LI6YQjJZcQSiQ0-GzyaK3NzebjGRQWVdkPyUNlbTTdr0+ez3WLuSKPeLlTCuKVyiF5XNgAAqBHIM0xC3aAByUFQlEo9gTjuZ-FZCbm3PQIQQKCgCVVRSLNQA5IpENp6Lo9Qa67XqprBVAUPQaDQHJhwPQhBFVRmOJHyHBKMhK9WuJ3kHWWsJRJI9l1kH1kNM9C83h89gJ+D8-gCgSCwZ9tz0DHWCArqrHgEclflLmruN2AAYdX932AJIUjSLxG2bVt7TmFB9V2VETXpJNiUtV0-RtbBuUpbYzX4BwYByCUimw6BEHoMDwHtEA82dK0BWDLCcMJPCCMQIiuBI3tyPSSjvR6X1rQY9RsL8XD8MI0NMQ4yAuIooMxXYqUZTld942fY5kJTZB00zbNKFzJlaOXEsyyQecq2-ZcGybHQ2DbXYO3UyENToUiGAHIcRzHVxJ2nBo5wXSynMhVdTzaTdkDvWR90Pd5PlPc8-H+QF4Gvf4tx3B8nzmV8gIAdW4WMEnseBY1VdxL0-RcfOQIRuENGNgAxaqXOQf9APUkAQNSHiINstF4PUxsTFpUwlBPLUUSNRDTUJZMSTQwSxTE1j3klPw7UG6jDILF03QwlacjWooNq9Q19uDQ7EGOrhTsweTckkyUI1lKNVITTSFp02c9IMp1drTDMfpzdTcs6prJJav8AKA7qKL6ls7OgmpGxdRH7MNY0iCAA)

```ts
//Innocent enough.
//Returns a T
type Callback<T> = (...args : any[]) => T;

//Forgive the contrived example
declare function returnTypeAsTypeParam<
    T extends 3|5,
>(
    f: Callback<
        & T
        & (
            T extends 3 ?
            unknown :
            [
                "Only 3 allowed, received",
                T
            ]
        )
    >
): T

//Expected: const noArg: 3
//Actual  : const noArg: 3
const noArg = returnTypeAsTypeParam(
    //Return type is 3 
    () => 3
);
//Expected: const withArg: 3
//Actual  : const withArg: 3
const withArg = returnTypeAsTypeParam(
    /*
        Expected: No error
        Actual  : No error
    */
    //Return type is `3`
    //function(t: any): 3
    t => 3
);

//Expected: const withArgAndExplicitReturnTypeAnnotation: 3
//Actual  : const withArgAndExplicitReturnTypeAnnotation: 3
const withArgAndExplicitReturnTypeAnnotation = returnTypeAsTypeParam(
    /*
        Expected: No error
        Actual  : No error
    */
    //We *force* the return type to be 3
    //Return type is `3`
    //function(t: any): 3
    (t) : 3 => (3 as 3)
);
```
[Playground](http://www.typescriptlang.org/play/#code/PTCSDtwewYwU3AFwAQKgVwOYAsB0BYAKBACU5F0AncAZ2QENkAVIxATwAc5kBhegG34AjejADWAHiYA+ZAF5kAClwr6lTHQBcDcGwDaAXQCU82UwDcRIiABiUdQEsAbt0TZuMKEkrO4AE1QAD3oAWw5+OCI-OBh+NW4AM3RwGEQHL2RKcipwJk44AEEaPK4ABTVQiSJkGuYgxAQ-OgBmAB8AVgAaImlFatqE7T5BEXEqwlrJ5AAyZn6pmaV5hdqmesaW5AB+ZZXkZLFoAHdwZE1dlb0LvZqAIgB5cH42ZGaGQSgj-07MmLhfPy3boTG4LFgg0EGa7IIzLaREIzacHWYAAUUCXFS-m0nloKGgBXU2maKIKqXQAhqOK8NHxUEJmGJRFxtOQBPU8l+FGoJUKxXy5UooT6EOQpGy1GQ7C4yAcm2WihMclkJMIRksxDRGJiDT81LxyCODjcDKZmrJFEpZ2QLJQRpNRNezJpduN2AZnKy3Ny+SKvMFwuWwAAVND0ZjddoAHJQVCUSj2aEWin8KnIGNxhOUZbB4BB4Bkb1S-KyugAA2aZfzSRSaS8ikQ2noukRTtFKGVbfVVk14Z12JtLsNboZBXAfnD-AcMGNhZyvLH0EQ9Dr4DNIGTVv1rPt7vUY4nGKnM8Qc55vsgUGXq7NtuHDswB8n09nEp9XEXV5X6VOCi9899fkygqEIRUmEMw21LE9XTWM4HjRNRUmTdU2tDN4KzHM81FEAAHVuGDBJ7HgYMpXcLkcmLGVEFjIRuFVcCCzfKjuDlZAKyrHDgBrVIfwbJsWzNSYGxMYlTCUN56BaWE1XMIA)

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/29133

https://github.com/microsoft/TypeScript/issues/32540#issuecomment-515148517

-----

I hope this is concise enough ><
I've commented all the relevant locations with what is expected and what actually happens.

Snippets 2 (`withReturnTypeInParam`) and 3 (`returnTypeAsTypeParam`) are expected to have the same behaviour because they mean the same thing semantically (to me).

They are just expressed differently syntactically.

I just have trouble understanding **why** snippet 2 breaks unless I have an explicit type annotation. I'm 99% sure it has to be a bug.

And I have trouble understanding why snippet 3 is OK

**Comment by AnyhowStep** [comment]
There's a reason I want to use snippet 2 and **not** snippet 3,
https://github.com/microsoft/TypeScript/issues/32442

For snippet 2,
```ts
//Innocent enough.
//Returns a T
type Callback<T> = (...args : any[]) => T;

//Forgive the contrived example
declare function withReturnTypeInParam<
    F extends Callback<3|5>,
>(
    f: F & (
        ReturnType<F> extends 3 ?
        unknown :
        [
            "Only 3 allowed, received",
            ReturnType<F>
        ]
    )
): ReturnType<F>

declare function withReturnTypeInParam2<
    F extends Callback<3|5>,
>(
    f: F & (
        ReturnType<F> extends 3 ?
        unknown :
        [
            "Only 3 allowed, received",
            ReturnType<F>
        ]
    )
): ReturnType<F>

let x = withReturnTypeInParam;
//Expected: OK
//Actual  : OK
x = withReturnTypeInParam2;
```
[Playground](http://www.typescriptlang.org/play/#code/PTCSDtwewYwU3AFwAQKgVwOYAsB0BYAKBACU5F0AncAZ2QENkAVIxATwAc5kBhegG34AjejADWAHiYA+ZAF5kAClwr6lTHQBcDcGwDaAXQCU82UwDcRIiABiUdQEsAbt0TZuMKEkrO4AE1QAD3oAWw5+OCI-OBh+NW4AM3RwGEQHL2QAdwc3MgpqJk44CAAFNVCJImRq5BsgxAQ-Oj5BEXEJAGYAHwBWaQAaImlFKpqE7TqAMiVRmpq8qnBCrgkbWThAhvAm5A7kAH5ZueRksWhM8GRNI7m9G+PqgCIAeXB+Nl2GQShM-37kSgxOC+PyPQaEB4PBYFIqraT3aoGI5GIhGbTQpawtZWQjRWLxZBJFJpDLZXLkRbLYrgMqUUIAJkqEJqdQ2Wx2LWEokk3T64OGR3GtWQ0xGzKhFJhKzW9UadD2h3Fx1O50u1yVtwRxxebw+ewE-B+fwBQJBYK1cwxVLhWqRSpRhDRyCtWPhhCIERQgXkWRy2BdXFK5RClmIwAAooEuKl-NpngBpazAACCqXQAmqccThG9CjJ-slmMDNOD9PMQA)

For snippet 3,
```ts
//Innocent enough.
//Returns a T
type Callback<T> = (...args : any[]) => T;

//Forgive the contrived example
declare function returnTypeAsTypeParam<
    T extends 3|5,
>(
    f: Callback<
        & T
        & (
            T extends 3 ?
            unknown :
            [
                "Only 3 allowed, received",
                T
            ]
        )
    >
): T
declare function returnTypeAsTypeParam2<
    T extends 3|5,
>(
    f: Callback<
        & T
        & (
            T extends 3 ?
            unknown :
            [
                "Only 3 allowed, received",
                T
            ]
        )
    >
): T
let x = returnTypeAsTypeParam;
/*
    Expected: OK
    Actual:
        Type 
        '<T extends 3 | 5>(f: Callback<T & (T extends 3 ? unknown : ["Only 3 allowed, received", T])>) => T' 
        is not assignable to type 
        '<T extends 3 | 5>(f: Callback<T & (T extends 3 ? unknown : ["Only 3 allowed, received", T])>) => T'. 
        Two different types with this name exist, but they are unrelated.
*/
x = returnTypeAsTypeParam2;;
```
[Playground](http://www.typescriptlang.org/play/#code/PTCSDtwewYwU3AFwAQKgVwOYAsB0BYAKBACU5F0AncAZ2QENkAVIxATwAc5kBhegG34AjejADWAHiYA+ZAF5kAClwr6lTHQBcDcGwDaAXQCU82UwDcRIiABiUdQEsAbt0TZuMKEkrO4AE1QAD3oAWw5+OCI-OBh+NW4AM3RwGEQHL2RKcipwJk44AEEaPK4ABTVQiSJkGuYgxAQ-OgBmAB8AVgAaImlFatqE7T5BEXEqwlrJ5AAyZn6pmaV5hdqmesaW5AB+ZZXkZLFoAHdwZE1dlb0LvZqAIgB5cH42ZGaGQSgj-07MmLhfPy3boTG4LFgg0EGa7IIzLaREIzacHRWLxZBJFJpDJZCjUEqFYr5cqUUIAJnGkzWcECDXATVeHWBvWWg14AmEokk0Nm4L2sz6EJuVJpG1e22hkwOx1O50FeyuctByAeTxeb3Zn2+v3gAKBEpWvKVUMVNVhgvhhERc0IERQgXkv1xuXyRXxxNClmIACplgBRQJcVL+bT3ADSywKqXQAlle3xyGhAHIpOs6ZtWsh2r1WcMOWM1vzhbT6W8tvtwIdPjLkHoVc8xRqvn4flkdS5AT8mMZpCY5GZEwmTcgHHRoCh6DQaA5MOB6EIIshEFBF-lB3tk0XRW8M1nFDn2aNJAWlJu02Ky1Kq2ca3W1e9+Jrm9r-u2gcxu73+7g1wajsu-A4CQJHAWRICuXB0EcDhuIu2Ajsgs4hNw1IjogPxCOgKBuHALxoskWRxA0fgEIQXrAEQ9oKDiOT4q6RIVCEpLmOYQA)


The conditional type **must** be in the return type of `Callback<>`.
We want `Callback<T & /*myConditionalType*/>`.
We **do not** want `Callback<T> & /*myConditionalType*/` because I have seen it break type inference (especially over here: https://github.com/microsoft/TypeScript/issues/32540#issuecomment-515121682)

**Comment by ahejlsberg** [comment]
This is working as intended. In the call `withReturnTypeInParam(t => 3)`, the `t` parameter is contextually typed. This means we defer inferences from the `t => 3` argument and first infer from other arguments such that we can produce the best possible contextual type. However, there are no other arguments, so we make no inferences for `F`. Then, the use of `ReturnType<F>` in the contextual parameter type causes us to apply the inferences we've made so far, and since there aren't any we default to the constraint `3 | 5`. That subsequently produces an incompatible parameter type.

The core issue here is that you can't simultaneously infer from an argument and depend on the argument.

**Comment by AnyhowStep** [comment]
Doesn't `returnTypeAsTypeParam` basically do the same thing as `withReturnTypeInParam`, but in a different way?

What's the reason `returnTypeAsTypeParam` works? Can I rely on it working in the future as well?

**Comment by AnyhowStep** [comment]
I guess I'll close this issue.

> The core issue here is that you can't simultaneously infer from an argument and depend on the argument

I have seen cases where TS is able to infer the type of the argument, depend on it, and also correctly infer the `ReturnType<>`

But it probably only worked in those cases out of dumb luck, I guess
