### ISSUE TITLE
type check error

### ISSUE THREAD

**Issue by tangjfn** [microsoft/TypeScript#33053]
**TypeScript Version:**  3.5.3

**Search Terms:**

**Code**

```ts

class A {
}

interface B {
}

let b:B = {};

let a:A = b; // is OK?


```

**Expected behavior:**

let a:A = b; // error

**Actual behavior:**

let a:A = b; // OK

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Please read the FAQ https://github.com/Microsoft/TypeScript/wiki/FAQ

![image](https://user-images.githubusercontent.com/6685088/63611399-a8d4ed80-c590-11e9-9162-681af92cdfcc.png)
