### ISSUE TITLE
Type guard fails to refine due to the presence of another method

### ISSUE THREAD

**Issue by webstrand** [microsoft/TypeScript#33051]
**TypeScript Version:**  3.7.0-dev.20190823

**Search Terms:** type guard, refine, fail, assignment

**Code**

```ts
interface Map1<K, HK extends K> {
	has(key: K): this is Map2<K, any>;
	get(key: HK): any;
}
declare let map1: Map1<string, never>;
if(map1.has("foo")) {
	let x = map1.get("foo"); // okay
}

interface Map2<K, HK extends K> {
	has(key: K): this is Map2<K, any>;
	get(key: HK): any;

	// If you remove this line, Map2 behaves just like Map1
	behavior(): HK;
}
declare let map2: Map2<string, never>;
if(map2.has("foo")) {
	let x = map2.get("foo"); // fail: map is still Map2<string, never>
}
```

**Expected behavior:**
`map2.has` should refine the type just the same as `map1.has` does, regardless of the presence of other methods on the interface.

**Actual behavior:**
`map2.has` doesn't refine the type at all so long as `behavior` has the return type `HK`.

**Playground Link:** 
[playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgLJwA4EYA8BpAGmQAk9kIAPSEAEwGdk8A+ZAbwCgBIACzjoAoA1hACeALkYBKCWG7AG8tJgBM+InBAimAbi4BzCGCGiJpacg0jdAX3Y0ICADZwoKR4eQBbTFgnpsOHRgUKB6RCAQAG7QOuzAMPze2AB0vAIARDAA9lnpkpJsXO5gyBTIALxePskGRpk5edrIAPTNyFmCcCLstnHg0PBIShiqhCRklNT0jCwcPHzG4lIycgoM-qPqmrGctYumeOaWulytyACSMMgiWQCuyK6eWdHIsoqOoBBEG8gARhC8aIMABWtyCyA+wmGWC4-0BwCyUH45lINjsDmcrghHiSyj8KkCwVC4SiMV08USKlSC3quXyhU4xVKFSqIxqhn4tMaLTa8GAjgkSWQiiC-Mcw1UQRCIDCyAi0SgTB6QA)

**Comment by jack-williams** [comment]
In the first case the predicate type is a subtype of source type, so it narrows to the predicate.

This is not true in the second case: the additional method make the predicate unassignable to the source because any is not assignable to never.

The method has an effect because it means the predicate idoes not produce a more precise type: the type of behaviour is less precise in the predicate type.

**Comment by webstrand** [comment]
I was wondering if the problem wasn't related to assignability. I also tried `has(this: any, key: K): this is Map2<K, any>`, but that also has an issue even though `Map2<K, any>` is a more precise type than `any`.

**Comment by RyanCavanaugh** [comment]
As usual I don't have much useful to add to @jack-williams's analysis. `Map2` is invariant on `HK` so it'd be unsound to narrow it to `Map2<string, any>`

**Comment by webstrand** [comment]
The example above is a reduced version of:
```ts
// If T is a refinement of C (T !== C, T is a subtype of C), produce T, otherwise never.
type Refines<T extends C, C> = C extends T ? never : T;

interface Map2<K, HK extends K> {
	has<RK extends K>(key: RK): this is Map2<K, Refines<RK, K> | HK>;
	get(key: HK): number;
	get(key: K): number | undefined;
}

declare let map2: Map2<string, never>;
if(map2.has("foo")) {
	let x: number = map2.get("foo"); // fail: map is still Map2<string, never>
}
```
The issue goes away if I use `Refines<RK | HK, K>` or `RK | HK` in place of `Refines<RK, K> | HK`. I'm not sure if this is an unrelated issue compared to the above.

**Comment by jack-williams** [comment]
Not 100% sure on that, but what I think is happening:


First thing to note is that, as defined, `HK` is measured as covariant in `Map2`.

**Comment by jack-williams** [comment]
And I'll just add this as a piece of relevant work #30461: it's not related to your specific bugs/questions, but it is related to your wider goal --- maybe it's interesting.
