### ISSUE TITLE
Inference from arrow function parameters with default initializers is broken when passed to generic function

### ISSUE THREAD

**Issue by hjkcai** [microsoft/TypeScript#33072]
**TypeScript Version:** 3.7.0-dev.20190824

**Search Terms:** default parameter generic inference 

**Code**

```ts
declare function id<T>(value: T): T
declare function whatever(): number

// (x?: any) => void
const f = id((x = whatever()) => {})

// (x?: number) => void
const g = (x = whatever()) => {}
```

**Expected behavior:** the type of `x` of `f` is `number`

**Actual behavior:** TypeScript cannot correctly infer the type of `x` of `f` and TypeScript complains that `x` is implicitly any. But if the outer `id` function call is removed (`g` in the above example), the type inference will be correct.

**Playground Link:** https://typescript-play.js.org/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXy2AB4AVAPgAoA3KCZEALnhIEomSAoUSWBFdbHngB3ABZQMIKiBgU28VMgC2AIxkcOAek3wKADwD8TKKgCeLeAF4y8KjkIcweAM4YkVgsAr6PYiVJk5C2t4AG8AXxYNbV1DJkVVGWCbOwcnVFd4AHMPH0sRcUlpWRZksPCgA

**Comment by sandersn** [comment]
I believe this is a long-standing design limitation, but I couldn't find the original bug. We might be able to do better here though.
