### ISSUE TITLE
keyof doesn't narrow index type

### ISSUE THREAD

**Issue by saulshanabrook** [microsoft/TypeScript#33084]
Applying keyof to a generic type that extends a mapping  doesn't seem to narrow to just the type specified in the mapping. See this  example, where `keyof T`  doesn't properly narrow to a `string` type, but is instead `string | number |  symbol`.

**TypeScript Version:**  3.6.1-rc

**Search Terms:** keyof, generic, extends

**Code**

```ts
class SomeClass<T extends string> {
    constructor(public s: T) {}
}

type ObjectMapping  = {
    [key: string]: any
}

function fn<T extends ObjectMapping>(m: T, k:  keyof T): SomeClass<keyof T> {
    return m[k]
}
```

**Expected behavior:**

There should be no type errors

**Actual behavior:**

There is a `Type 'keyof T' does not satisfy the constraint 'string'.` type error in the function definition.

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/FAjGBsEMGdoAgMoHsC2BTAwlWAeAKnGgB4AuaAdgCbzQkBOAluQOYB8cA3sHD3KEuVp0ArqBJI6ACgAOwgEbgGoONABccPAEpOAX2B7gJAJ7S0cAPJyAVmjEBZSNOlNmPALyduvANoBrNEbqQi4AuuqQ5Eb6IMAAZsLkYgwCcLHk+ISkFNQW1rYkDk4urJIo6ngANHC+6tUBSLEamurI6Fgw0Dj+Rg0a7Fy8cHRoJMJ05HAofiH6QA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/24574

**Comment by poseidonCore** [comment]
Sometimes you can get around this with `Extract<keyof T, string>`

```ts
class SomeClass<T extends string> {
    constructor(public s: T) {}
}

type ObjectMapping  = {
    [key: string]: any
}


function fn<T extends ObjectMapping>(m: T, k:  keyof T): SomeClass<Extract<keyof T, string>> {
    return m[k]
}

```
[TS Payground](https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEDKD2BbApgYXFAPAFWsgHgC7IB2AJjBIQE4CWJA5gHzQDeAUNF9MPCVdQCuwQvGoAKAA6CARiFrBoEAFzRsASjYBfdjvaEAnpOTQA8jIBWyEQFkwkyfQZcAvG07cA2gGtkB1QJOALqqYCQGuuzsAGaCJCK0fNDRJDh4RKQUZpbWhHYOTkziiKrYADTQ3qqVfvDRauqqCCjokBCYAKJE1GAimL4GdWoVgYxMLBzc0NTIhILUJNCIPkGRQA)

**Comment by poseidonCore** [comment]
Snap ... we just posted that at the same time :-)
