### ISSUE TITLE
Object spread and Map

### ISSUE THREAD

**Issue by bs85** [microsoft/TypeScript#33081]
When spreading a `Map`, the resulting object is also considered a `Map`, allowing to call all the `Map` methods on it even though they aren't inherited.

```
const map: Map<number, string> = new Map();
const spread = { ...map };
spread.has(0)

// -> spread.has is not a function
```

Is this intended, and is there a compiler option that would result in an error here?

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/28801
