### ISSUE TITLE
JSDoc @enums cannot be used as Values in @typedef / @type

### ISSUE THREAD

**Issue by bmeck** [microsoft/TypeScript#33085]
**TypeScript Version:**  3.5.1

**Search Terms:**
enum, jsdoc, typedef, type, tagged union, enum value, type declaration

**Code**

```mjs
/** @enum {string} */
const Color = {
  Red: 'red',
};

/** @type {Color.red} */
var red;
```

**Expected behavior:**
`red` expects a value of `"red"`;

**Actual behavior:**
Type error because `Color.red` cannot be found

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/KYOwrgtgBAwg9gGzgJygbwFBSs4ATKAXigHJc8SAaDAXwG4MMA3AQ1XIC5ZEUA6cukA

**Related Issues:** N/A

**Comment by sandersn** [comment]
`@enum` does not define a typescript enum, just a jsdoc enum. `@enum {number}` is almost equivalent to the following:

```js
/** @typedef {Object<string, number>} Color */
/** @type {Color} */
const Color = { ...
```

Except that `Color` retains its original type.

The easiest way to get what you want is `/** @type {typeof Color.Red} */`. I think you can get even closer by using Typescript types, but it will be considerably wordier.

**Comment by bmeck** [comment]
Is there a document explaining what JSDoc tags map to what types in TS? This behavior is surprising to me

**Comment by sandersn** [comment]
https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#enum and https://jsdoc.app/tags-enum.html although I do not believe Typescript will let you override the type of individual members the way that jsdoc.app says.
