### ISSUE TITLE
Typing fails on destructuring function params

### ISSUE THREAD

**Issue by n1tin** [microsoft/TypeScript#33097]
**Typescript version:** 3.5.1

I was converting some of js files in React to ts when I faced this issue. I wanted to make some of props mandatory or optional based on value of a prop that is passed. The code in the component had destructed the variables from props causing this issue to occur. 

**Search Terms:** destructuring

**Code**

Example:

```ts
type ErrorObj = {
  isError: true,
  errorMessage: string,
} | { isError:false, errorMessage?: string }

const checkError: (error: ErrorObj) => void = (error) => {
  error.isError && logLength(error.errorMessage);
}
const checkErrorAgain: (error: ErrorObj) => void = ({ isError, errorMessage }) => {
  isError && logLength(errorMessage); // throws an error, Type 'undefined' is not assignable to type 'string'.
}
const logLength = (message: string) => console.log(message.length);
```

**Expected behavior:** Should correctly infer the type of errorMessage param

**Actual behavior:**  Incorrect type being inferred and an ts error is thrown

**Playground Link:** https://www.typescriptlang.org/play/index.html?jsx=2#code/C4TwDgpgBAogTnA9nA8gIwFZQLxQN4BQUUAlgM7xJwBcUwcArhADRFQQLICyEZZAhgHMItMvRIA7QawC+UAD75SFTjQBm-ADZkW7VTz5CIAflHipUGQQIBjRBLFQbACwg2A1pWS0AFByq0XqiYAJQ4AHxQAG6IJAAmOFB+qmHYkYTE-sgAdORBUABkBVCaiIIAMhBSwM7JVNlZcAYCwiEA3ARWdg7ATq4eQQCCgvySvo2BqugYqZEx8Yk+eMpBzHpUzUaWs-hseaqFxaUVVYI1ddy8LRDtnbb2jseV1c6LALZXRmZwkoI73WREJoINljj4PoZhKDTjVbkA

**Comment by jack-williams** [comment]
This is duplicate of #28599, which in turn is tracked here: #12184.

**Comment by n1tin** [comment]
Closing it then 🙂.
