### ISSUE TITLE
Support Multiple Themes on TypeScript Website

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/TypeScript#3310]
Would it be possible to support different themes on the TypeScript website?

The below is rather hard to read, especially when switching back and forth between pages:
![lightfontcolor](https://cloud.githubusercontent.com/assets/4054178/7898229/c1cd03f6-06b6-11e5-8999-4002a18d9ec0.jpg)

I do appreciate the beauty of it. . .but the color scheme is tough to read and makes it difficult to track back to my last position.

Thank you for considering my request.

**Comment by mhegazy** [comment]
We are in the process of updating the website. the new theme should be much more readable.
