### ISSUE TITLE
stricter jsdoc type resolution causes weird behaviour for value-only declarations

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#33106]
```js
/** @param {Image} image */
function process(image) {
}
```

**Expected behavior:**
1. Error "'Image' refers to a value, but is being used as a type here." and `image: any`, as TS does.
2. No error, and `image: typeof Image`, as we often do in JS.

I think I prefer (2), but after the stricter-jsdoc-type-resolution PR, I expected (1), which is also OK.

**Actual behavior:**
No error and `image: any`.

**Comment by ahocevar** [comment]
@sandersn Might #33575 be related?

**Comment by sandersn** [comment]
@ahocevar Yes, although the scenario still doesn't work completely, so it still needs work.
