### ISSUE TITLE
Get --analysisOnly to CLI that will only check for the type errors without building

### ISSUE THREAD

**Issue by viktor-ku** [microsoft/TypeScript#33114]
As said, should work like awesome `--transpileOnly` but instead of only transpiling it should do only type error checks and exit with 0 or 1 as before.

Should be relatively easy I guess since normal program run will do both: static checks and build. We just need to do the latter.

Maybe I can make a PR, but I'd like to get some feedback first.

Thanks

**Comment by j-oliveras** [comment]
[`noEmit` option?](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Comment by viktor-ku** [comment]
@j-oliveras yeah, sorry for the stupid question! Works great!
