### ISSUE TITLE
Inconsistent type checking behaviour for interface method declarations

### ISSUE THREAD

**Issue by sdc395biosite** [microsoft/TypeScript#33113]
**TypeScript Version:**  3.5.1

**Search Terms:** typescript interface method declaration syntax

**Code**

```ts
interface SomeMethod { (arr: string[] | undefined): number; }

interface SomeInterface {

	someMethod: SomeMethod;
	someOtherMethod: (arr: string[] | undefined) => number;
	anotherMethod(arr: string[] | undefined): number;
}

class SomeClass implements SomeInterface {

    someMethod(arr: string[]) {

        return arr.length;
    }

    someOtherMethod(arr: string[]) {

        return arr.length;
    }

    anotherMethod(arr: string[]) {

        return arr.length;
    }
}

const something: SomeInterface = new SomeClass();

something.anotherMethod(undefined);

```

**Expected behavior:** I expect the definition of SomeClass.anotherMethod to raise an error for exactly the same reason that someMethod and someOtherMethod do (parameter type mismatch).

**Actual behavior:** the definition of SomeClass.anotherMethod is accepted and leads to a runtime error if it is passed `undefined` as allowed by the interface's type.

**Playground Link:** http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgMoHsC2ECyEwAW6AJsgN7IAUcUUAXMgM5hSgDmA2gLrIA+yAVxDEIMUBGIBKBiAGYARtADcyAL4AodaEixEKDNgCS4aPCTlNASEZZc+IsQYG7hEkvXXbAeULQ8rxyoaeiYWdm4+QWFRcSlkAF4APmRZBWUPOBB0Xyh-B2paBmZWEE4efiERMRAJaRS5RSh3DXUEABs4RkY0WwBhDq7kYEwABzaIbHBu52MdMxQyTWRlpls8kgKQ4vCuSQt1FcPkKHwBKBBkYIA6cdLCd0OWw5tsHwI-ew3gorDS7j3FgcjssTmAzhdrrc2PcgcsnitMtl3rlPsRNj8SmUAUtgcdTudLrQbhA7gQHisNC0EOgQMxVthCOwnLZZqY9AkUhAAO49bD9TqMSiSdzqF72dhXRE5dZoyoxGpSdxAA

**Related Issues:** I have read the FAQ and attempted to search for known issues but found nothing relevant.

**Comment by jack-williams** [comment]
This is working as intended: `anotherMethod` is a method, while `someMethod` and `someOtherMethod` are properties of function type.

As per #18654, methods are always bivariant in their argument, while properties of function type are contravariant under `strictFunctionTypes`.

**Comment by sdc395biosite** [comment]
@jack-williams Thank you for the link.

Whilst I appreciate there are good reasons for the distinction, it wasn't one I was aware of.  [The documentation for interfaces](https://www.typescriptlang.org/docs/handbook/interfaces.html) doesn't appear to mention it and all examples use methods rather than properties of function type.  Surely properties of function type should be preferred in order to avoid having the compiler overlook what are clearly probable coding errors.

**Comment by jack-williams** [comment]
@sdc395biosite AFAIK there are lint rules that can be used to prefer method syntax or function syntax. Did you read this part of the FAQ [here](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)? If so, maybe that's an indication it should be updated to address method vs function property.

**Comment by sdc395biosite** [comment]
As someone with only a rudimentary understanding of type checking, I failed to connect "Why are function parameters bivariant?" with the problem I had encountered.  In my opinion, this difference is critical (my use of the method syntax led to a run-time error TypeScript would have caught had I used property syntax) and it should be front and centre within the "interfaces" section of the TypeScript documentation.
