### ISSUE TITLE
Implement Overloads by Generating Separate Functions

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#3312]
I have an idea for how to make function overloads work:

```typescript
function foo(bar: string) {};
function foo(bar: number) {};

foo('hi');
foo(42);
```
Compiles to:
```js
function foo__string(bar) {};
function foo__number(bar) {};
function foo() {
  throw Error('Overloaded functions cannot be called dynamically or from non-TypeScript code.')
}

foo__string('hi');
foo__number(42);
```

This seems relatively easy to implement. A few notes:
 - We would need a way to serialize complex type signatures to valid identifiers. If we have the machinery to serialize signatures to JSON, we could use slightly-modified base64.
 - If a overloaded function was called with a union type, we would probably need to expand the calling function into multiple overloads. This is an edge case, so we might just be able to error on code like this for now.
 - The stub function with the original name could be eliminated in production code, but it could save some headaches in development.

**Comment by kitsonk** [comment]
That sort of ties you to TypeScript and makes it essentially unusable in JavaScript.  Emitting essentially unusable JavaScript is not really what TypeScript is about.

What problem are you trying to solve that you currently can't?

The current overloading, with the onus upon the implementor to ascertain what arguments and there types being passed is perfectly fine in my opinion and a vast improvement over the sort of inline documentation you would have to do in native JavaScript to express your intent.

**Comment by mhegazy** [comment]
As @kitsonk mentioned, this would be out of scope of TypeScript aims to accomplish. the overloads serve as a way to declare legal signatures for the compiler to check against, similar in function to type casts and type annotations. type-directed code generation has not been something that TypeScript aimed to do.
