### ISSUE TITLE
VS Code: "editor.showUnused": true not working in `*.d.ts` files

### ISSUE THREAD

**Issue by gilluminate** [microsoft/TypeScript#33121]
I was asked by the VS Code team to move this bug report upstream to the TypeScript project.

- [x] searched existing issues to avoid creating duplicates
- [x] tested using the latest insiders build to make sure issue has not already been fixed
- [x] issue occurs when all extensions are disabled

- VSCode Version: 1.37.1
- VSCode Insiders Version: 1.38.0-insider
- OS Version: MacOS Mojave 10.14.6
- **TypeScript Version:**  3.7.0-dev.20190828

**Search Terms:**
"VS Code", "d.ts", "unused", "editor.showUnused"

Steps to Reproduce:

1. Ensure `editor.showUnused` is set to `true` for user, workspace, and folder.
1. Create a file with extension `.d.ts`
1. Add valid import statement such as
```import { User } from 'types/users';```

**Actual behavior**: Import statement is not faded even though it hasn't been used.
**Expected behavior**: Import statement should be faded out as per setting.

Additional steps:

1. convert filename to have only the `.ts` extension (drop the `.d`)
Note: import line is dimmed as expected. The issue appears to only be affected by `.d.ts` files.

**Related Issues:**
Possibly:
https://github.com/microsoft/TypeScript/issues/32196
https://github.com/microsoft/TypeScript/issues/30260

**Comment by andrewbranch** [comment]
It seems this is by design since https://github.com/microsoft/TypeScript/pull/9452 (https://github.com/microsoft/TypeScript/pull/9452/commits/4789ff0316f7a19e53fda55f07a54ff3aedaa26d). I personally think it would be nice to recognize unused identifiers, but should probably be excluded from being errors with `--noUnusedLocals`.
