### ISSUE TITLE
Was v3.6.2 released on npm on accident?

### ISSUE THREAD

**Issue by ethanneff** [microsoft/TypeScript#33122]
Has 3.6.2 been released? It shows up in NPM https://www.npmjs.com/package/typescript

In Github, version 3.6+ is still in RC https://github.com/microsoft/TypeScript/releases

**Comment by arutkowski00** [comment]
It looks like there's something strange going on in distribution tags.

**beta:** 3.6.0-beta
**rc:** 3.6.1-rc
**latest:** 3.6.2
**next:** 3.7.0-dev.20190828


There's no 3.6.0 or 3.6.1 in `latest`.
