### ISSUE TITLE
Unable to extend window in TS 3.6

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#33128]
**TypeScript Version:**  3.6.2

**Search Terms:**

- globalThis

**Code**

This code passed the type checker in TS 3.5:

```ts
interface MyWindow extends Window {
  foo: string;
}

(window as MyWindow).foo = 'bar';
```

but fails with this error in TS 3.6:

```
Conversion of type 'Window & typeof globalThis' to type 'MyWindow' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'foo' is missing in type 'Window & typeof globalThis' but required in type 'MyWindow'.ts(2352)
```

Following the [release notes][1], I can work around the issue by changing from `interface` to `type` and using an intersection:

```ts
type MyWindow = (typeof window) & {
  foo: string;
}

(window as MyWindow).foo = 'bar';
```

but this feels more obscure than the old way. Is this WAI? What's the rationale for the non-extendable Window?

**Expected behavior:**

An interface should be able to extend `Window`.

**Actual behavior:**

The error above.

**Playground Link:**  3.6 isn't on the playground yet.

**Related Issues:** 

[1]: https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#dom-updates

**Comment by danvk** [comment]
Perhaps unrelated, but I ran across this spectacularly weird error while trying to work around this:

```ts
type T = Window & typeof globalThis;
interface MyWindow extends T {
  foo: string;
}
```

Error:

```
interface MyWindow
Property 'Infinity' of type 'number' is not assignable to numeric index type 'Window'.ts(2412)
Property 'NaN' of type 'number' is not assignable to numeric index type 'Window'.ts(2412)
```

**Comment by ChristopherKiss** [comment]
Is there a reason you don't just merge declarations with Window?

```
interface Window {
    foo: string;
}

window.foo = '123';
```

**Comment by dragomirtitian** [comment]
Augmentation of `window` is usually done by using interface merging:

```ts
export {}
declare global {
  interface Window {
    foo: string;
  }
}

window.foo = 'bar';
```

or 
```ts
interface Window {
  foo: string;
}

window.foo = 'bar';
```
 For non-module scenarios.

**Comment by danvk** [comment]
The appeal of extending Window and using an assertion is that it's not global. Though I suppose if you're extending a global singleton, you don't have much ground to stand on!

**Comment by fatcerberus** [comment]
When using modules, the interface merge will be local to the file it occurs in, I believe.  It's true you can't make the scope any narrower than that, but at least it won't poison outside code.

**Comment by sandersn** [comment]
Why not include `globalThis` at the point of the assertion?

```ts
(window as MyWindow & typeof globalThis).foo = 'bar';
```

This is indeed working as intended. `window.foo = 'bar'`'s runtime behaviour is best represented by an interface merge, not a subtype. Can you actually even extend window? It seems like a convenient lie to the compiler.

As for the weird error, Window has a numeric index signature `{ [n: number]: Window }` so that `window[0] : Window`. But when making sure an `extends` is legal, the compiler checks that numeric properties from the other side of the intersection have type `Window`. *Normally*, that's properties with names like `'0'` and `'1'`, but guess what `NaN` and `Infinity` are also numbers, so we check that their types are compatible with Window's index signatures. Since `NaN: number` and `number` is not assignable to `Window`, the compiler reports that as an error.

**Comment by danvk** [comment]
Thanks @sandersn. The missing piece was that `window[0]` is a way of [accessing a frame][1] on the page.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Window/frames

**Comment by fatcerberus** [comment]
> Normally, that's properties with names like '0' and '1', but guess what NaN and Infinity are also numbers, so we check that their types are compatible with Window's index signatures. Since NaN: number and number is not assignable to Window, the compiler reports that as an error.

Wait, what.

The index signature `[n: number]: Window` doesn't match `NaN: number` or `Infinity: number` at all so their types shouldn't matter for that purpose.

**Comment by sandersn** [comment]
@fatcerberus the property is named `NaN`, which is definitely a number. The *funniest* number.

**Comment by fatcerberus** [comment]
Oh I see, I didn’t realize those were covered by a numeric index signature because they’re not valid array indices.  I know they are covered by `number` but for some reason I thought the signature was special-cased to only cover valid array indices (i.e. roughly the domain of `Number.isSafeInteger`).

**Comment by danvk** [comment]
@fatcerberus I don't believe this statement is correct:

> When using modules, the interface merge will be local to the file it occurs in, I believe. It's true you can't make the scope any narrower than that, but at least it won't poison outside code.

I put this in a new file in my project (`foo.ts`) that's not imported anywhere:

```ts
export {};
declare global {
  interface Document {
    /** documentation on foo */
    foo: string;
  }
}
```

Then, in another file, I can write:

```ts
document.foo;
```

without importing `foo`. There's no error and I see the documentation. So I do not believe the augmentation is scoped to the module at all. It is as global as the `declare global` implies.

**Comment by nextgenthemes** [comment]
> Augmentation of `window` is usually done by using interface merging:
> 
> ```ts
> export {}
> declare global {
>   interface Window {
>     foo: string;
>   }
> }
> 
> window.foo = 'bar';
> ```
> 
> or
> 
> ```ts
> interface Window {
>   foo: string;
> }
> 
> window.foo = 'bar';
> ```
> 
> For non-module scenarios.

@dragomirtitian 

"usually done" is funny because I based on what I have seen everyone is doing is differently. 

Where do I put this?

When I am compiling just one file `foo.js` I need to put this in `foo.d.ts`? The first is not working. I am importing normal modules and already setup for that.

I am new to TS and after spending **hours** browsing through many many **many** different stackoverflow answers different things keep coming. Solutions, do no longer work, ....

Seriously TS is supposedly a easy transition where you just add type checks for things as you go as you rename your `.js` file. Why is this such a fucking pain in the ass?

I just want to say `hey TS STFU about these globals: this, that, anythis` and I do not want to install any extra typings and deal with extra files **for now** I set `allowJS` and I just want to get going. FFS!

I do not want to declare and use my own globals but use other 3rd party globals that I expect to jsut be there so I do not want anything else for now.

**Comment by kaminskypavel** [comment]
quick and dirty 

``(window as any).foo = "bar";``

**Comment by Magiccwl** [comment]
> Augmentation of `window` is usually done by using interface merging:
> 
> ```ts
> export {}
> declare global {
>   interface Window {
>     foo: string;
>   }
> }
> 
> window.foo = 'bar';
> ```
> 
> or
> 
> ```ts
> interface Window {
>   foo: string;
> }
> 
> window.foo = 'bar';
> ```
> 
> For non-module scenarios.

Thx your answer, I just curious what the first line
```ts
export {}
```
for?

**Comment by orta** [comment]
To force the file to be registered as a module, not a script

**Comment by leepowelldev** [comment]
> To force the file to be registered as a module, not a script

@orta Can I ask why it needs to be registered as a module?

For me this doesn't work until the add the `export {}` - I'm just trying to understand why.

```
declare global {
  interface Window {
    myProp: string;
  }
}
```

**Comment by shicks** [comment]
@danvk wrote:

> @fatcerberus I don't believe this statement is correct:
> 
> > When using modules, the interface merge will be local to the file it occurs in, I believe. It's true you can't make the scope any narrower than that, but at least it won't poison outside code.
> 
> I put this in a new file in my project (`foo.ts`) that's not imported anywhere: `declare global { interface Foo { foo: string; } }`
> Then, in another file, I can write: `document.foo` without importing `foo`. There's no error and I see the documentation. So I do not believe the augmentation is scoped to the module at all. It is as global as the `declare global` implies.

Super-late response here, but there exist some TypeScript wrappers that will treat this differently.  In particular, at Google we redefine `declare` to mean "emit an externs file for all the world to see", mainly for the purpose of allowing folks to write `declare interface` in their modules to force property names to be externed and thus not mangled by the optimizer.  Unfortunately, this had the unintended consequence that _other_ legitimate uses of declare (e.g. locally-extending interfaces, or `declare const PRIVATE: unique symbol` to get a module-local type `typeof PRIVATE`) end up having globally-visible impact.

**Comment by eeckhardt-chwy** [comment]
If you want the type augmentation to be global and ambient, this works fine:
```
// somefile.d.ts
declare interface Window {
  foo: string
}
```
The trick is, you **must** put this in a file with the extension `.d.ts` (and there must not be a same-named file with just the extension `.ts` in the same directory. Then this will function as an ambient type and declaration merging will kick in. No import will be required.

**Comment by erikeckhardt** [comment]
If you want the type augmentation to be global and ambient, this works fine:
```
// somefile.d.ts
declare interface Window {
  foo: string
}
```
The trick is, you **must** put this in a file with the extension `.d.ts` (and there must not be a same-named file with just the extension `.ts` in the same directory. Then this will function as an ambient type and declaration merging will kick in. No import required.

**Comment by erikeckhardt** [comment]
@shicks Thanks for the tip! Makes sense. Some projects/packages are small enough and use of a global object pervasive enough that boosting a type to be globally ambient is useful (especially in packages that aren't consumed by other packages). But when polluting the global scope is harmful, this seems like a good technique to reduce the boilerplate and complexity of strongly typing at use-time.

**Comment by lizy0329-biubiubiu** [comment]
> If you want the type augmentation to be global and ambient, this works fine:
> 
> ```
> // somefile.d.ts
> declare interface Window {
>   foo: string
> }
> ```
> 
> The trick is, you **must** put this in a file with the extension `.d.ts` (and there must not be a same-named file with just the extension `.ts` in the same directory. Then this will function as an ambient type and declaration merging will kick in. No import required.

This is correct method for window type extend

**Comment by louwers** [comment]
Is it possible to extend Window with `type`? I want to use a mapped type.
