### ISSUE TITLE
/// <reference path="typings/angular2/angular2.d.ts" /> is considered relative external module

### ISSUE THREAD

**Issue by neermitt** [Microsoft/TypeScript#3313]
As per spec of tyepscript 1.5

External module names may be relative or top-level. An external module name is relative if the first term is "." or ".."

but current implementation interprets "typings/angular2/angular2.d.ts" as external because its not rooted (absolute)

```javascript
function processReferencedFiles(file: SourceFile, basePath: string) {
            forEach(file.referencedFiles, ref => {
                let referencedFileName = isRootedDiskPath(ref.fileName) ? ref.fileName : combinePaths(basePath, ref.fileName);
                processSourceFile(normalizePath(referencedFileName), /* isDefaultLib */ false, file, ref.pos, ref.end);
            });
        }
```

**Comment by mhegazy** [comment]
@neermitt can you provide some code samples of the issue you are running into?

**Comment by neermitt** [comment]
@mhegazy sorry my mistake in understanding typescript compiler module system
