### ISSUE TITLE
Cannot create a Partial<Generic> type in a one-liner

### ISSUE THREAD

**Issue by gewoonwoutje** [microsoft/TypeScript#33134]
**TypeScript Version:**  3.4.5; 3.7.0-dev.20190829

**Search Terms:**

Partial, Generic, inconsistent, 

**Code**

```ts
interface MyMap {
	field: string;
}

function someGenericFunction<T extends MyMap>(input: T) {
	let y: Partial<T>;

	// falsely not allowed: 
	// ts(2322): Type '{ field: ''; }'is not assignable to type 'Partial<T>'. 
	y = { field: '', };

	// similar, but allowed
	y = {};
	y.field = '';

	// correctly not allowed
	y.anything = ''; // anything is not defined in MyMap type
	y = {
		field: '',
		anything: 123, // anything is not defined in MyMap type
	}
}
```

**Expected behavior:**
Should be able to create the generic in a one-liner .

**Actual behavior:**

Can be done in two lines, not in one line.

**Playground Link:** 

http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgLIE9VwA7IN4CwAUAJAzAQA2AJgFzIDOYUoA5gNzEC+xxMAriARhgAexCNRAWwgBxCCGjAEAMUHCxIADwAVZBAAekENQZpMOAHwAKUNn5h6OgJT5iJShDDJ09AApwUCJwlLqWnETuAPRRyPCUDFToyCCi3iGUogDuEHTI0bFgDNYATADMJSXOTujYKADkeHEUNPT19ezIXPXAZqnpDAzArCBwAEaeyGCiU7UNAUHAIWH1AHT5pMkAvPjNVHntADRdEQWMwFL8lIHHYw7IGdm57tv4XBEk6Kvk+8g77adIqQYsgEKIoFAIMJKMl+g9KJkctQXqs4CB0GAABZsP7IAHIEE-Gh4tEY7EgVj1ZDUUQQPppfQGXreUCzOrmLDYF64wikMgtA71Q7uEikrFsegARnKx0JApJ6PFFKpNLpKQZhmZyFZYDmHJw7h4RCNQA

**Related Issues:** 
#28470

**Comment by jcalz** [comment]
Duplicate of #13442 

Note that `T` may be resolved with a type like

```ts
interface SomeoneElsesMap extends MyMap {
  field: "It's *my* map now";
}
```

So you can't safely assign `{field: ""}` to `Partial<T>`.  For that matter, you can't safely do the assignment `y.field = ""`, but for whatever reason that's allowed by the compiler.

**Comment by gewoonwoutje** [comment]
Okay, I see I did not do enough search in the issue history. This issue has a lot of history being closed as duplicate. In fact, item #23015 seems to be exactly the same. 

It's still a bug though, as it does not work like expected. Or it should accept both cases, or neither. But I understand that it would be a very breaking change in both cases.
