### ISSUE TITLE
Object.assign propagates ReadOnly modifier from source object

### ISSUE THREAD

**Issue by zbjornson** [microsoft/TypeScript#33149]
**TypeScript Version:**  3.7.0-dev.20190829

**Search Terms:** object freeze assign readonly 2540 TS2540

**Code**

```ts
const x = Object.freeze({a: 1});
const z = Object.assign({}, x);
z.a = 2; // Cannot assign to 'a' because it is a read-only property.
```

**Expected behavior:**
There should be no error.

**Actual behavior:**
> TS2540: Cannot assign to 'a' because it is a read-only property.

**Playground Link:** https://typescript-play.js.org/#code/MYewdgzgLgBAHjAvDA8gIwFYFNhQHQBmATllgF5YAUA3gIYBcMAjAL4CUA3AFCiSxlJUmHPloQIASwDmYGiwA08TlzJ5aggEzcgA

**Related Issues:**  None found

Oddly, this is fine, even though it does the same thing:
```ts
const x = { a: 1 };
Object.freeze(x);
const z = Object.assign({}, x);
z.a = 2;

```

**Comment by AnyhowStep** [comment]
It's not the same thing, though.
The types of `x` are different, aren't they?

I'm on mobile, so I can't check

**Comment by zbjornson** [comment]
I think they're the same. `freeze()` both modifies and returns the object that was passed in. (`console.log(z.a)` prints `2` in both cases.)

**Comment by AnyhowStep** [comment]
Your first `x` should be of type `{readonly a: number}` or something similar.

Your second `x` should be `{a: number}` or something similar.

Different types.

**Comment by zbjornson** [comment]
Maybe that's a typescript-ism that `Object.freeze` doesn't apply the `readonly` modifier, even though it actually becomes read-only in ECMAScript at runtime. But that's not the point of this issue: it's the second part of your comment, that `Object.assign` isn't stripping `readonly` when it should.

**Comment by fatcerberus** [comment]
> Maybe that's a typescript-ism that Object.freeze doesn't apply the readonly modifier

The type system can’t really model mutation.  If you do `Object.freeze(x);` (as opposed to assigning the return value to a new variable) there’s no way for it to add `readonly` to the type of `x` “after the fact”.

**Comment by fatcerberus** [comment]
Getting back on topic: It looks like `Object.assign` isn't even a mapped type, it just directly intersects the source and target types:
https://github.com/microsoft/TypeScript/blob/master/src/lib/es2015.core.d.ts#L266

A mapped type would solve it *in theory* because that would allow for removing the `readonly` modifier, but you run into issues when the *target type* has unrelated read-only properties:

```ts
type Assign2<T, U> = { -readonly [K in keyof (T & U)]: (T & U)[K] }
interface ObjectConstructor
{
    assign<T, U>(target: T, source: U): Assign2<T, U>
}

const x = Object.freeze({ a: 1 });
const z = Object.assign({ b: 2 as number } as const, x);
z.a = 2;  // this works now
z.b = 3;  // still should be an error but isn't
```

So this ultimately just moves the goalposts because as said above, TS can't model mutation. ☹️

**Comment by AnyhowStep** [comment]
Remove from U, preserve from T?

Mapped types might be more "correct".

If `U` is a function with properties, we don't want to have an intersection and make the result callable

**Comment by sandersn** [comment]
Works if you use `const z = { ... x }` instead of `Object.assign({}, x)`.

**Comment by zbjornson** [comment]
@sandersn I'm confused how having a workaround means this is working as intended. In environments where we're not down-targeting pre-ES2018 and have to use `Object.assign`, there is no workaround I see. (Specifically: using JSDoc annotations to type-check JS, not TS.)

**Comment by AnyhowStep** [comment]
Moreso a design limitation, I suppose (the Object.freeze() part)
And maybe a problem with Object.assign() as well (Not string readonly)

**Comment by sandersn** [comment]
Object.assign is Working As Intended. As @AnyhowStep points out, perhaps it's a Design Limitation, or more of a complexity-of-implementation limitation. We discussed and implemented spread types, but their usefulness was low, their composability was low, and people had been successfully using intersections for several years, so we decided not to merge them.
