### ISSUE TITLE
Dead link on typescriptlang.org

### ISSUE THREAD

**Issue by Ivan-Kouznetsov** [microsoft/TypeScript#33152]
https://www.typescriptlang.org/docs/handbook/compiler-options.html has a link to https://www.typescriptlang.org/docs/handbook/tutorials/tsconfig-json.html which does not exist.
The link text is "tsconfig.json".

**Comment by orta** [comment]
👍 thanks - fixed with https://github.com/microsoft/TypeScript-Handbook/commit/04158f34e59051f7f27f78a47dfcc64620353661
