### ISSUE TITLE
TSX Infinity compilation if add comment to jsx code in format /**/

### ISSUE THREAD

**Issue by gyerts** [microsoft/TypeScript#33159]
If I add comment in format /**/ into jsx code with {'word'} combination, we will meat infinity typescript compilation with no errors
`<span>{'word'}/*asd*/</span>`

**Comment by orta** [comment]
Hi - I'm afraid I can't reproduce this in either [the playground](https://www.typescriptlang.org/play/?strictNullChecks=false&jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQLABQ9uEAdqvAFaoAecAvHAAoAlHwB89OHAA8qMMmaiA3gHIA7tAAmygL4B6BGg0JdU3bPmigA) or locally via TSC with 3.6.2. 

Any chance you can provide a reproduction sample?

**Comment by gyerts** [comment]
It is not reproduceable in the other projects, only in my project... so I think it could be closed
