### ISSUE TITLE
Performance type, performance.memory and thereby: MemoryInfo type

### ISSUE THREAD

**Issue by DerkJanSpeelman** [microsoft/TypeScript#33155]
```
if (self.performance) {
    let memory: MemoryInfo = performance.memory;
    if (memory) {
        console.log('memory:', (memory.usedJSHeapSize / 1048576));
    }
}
```

 > Cannot find name 'MemoryInfo'
 > Property 'memory' does not exist on type 'Performance'

This error can easily be reproduced by copying these lines of code and run them.

Current fix: `// @ts-ignore`

Version: 3.6.2

**Comment by j-oliveras** [comment]
MDN says that [performance.memory](https://developer.mozilla.org/en-US/docs/Web/API/Performance) is not standard, so that the reason that is not defined.

**Comment by IwonaGorska** [comment]
Hi,

Anybody knows any workaround, different way to measure the memory programatically? Mentioned performance.memory works in React JS (JS) but doesn't work with Angular (TS).

Iwona
