### ISSUE TITLE
TS/JS extension does not underline missing members of imported objects

### ISSUE THREAD

**Issue by StasD** [microsoft/TypeScript#33153]
**Issue Move Notes**

Tested with: TS 3.7.0-dev.20190829

**Search Terms**
- js / javascript
- checkjs tscheck

---

**Original Issue**

- VSCode Version: 1.37.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. There is a Javascript project (RN) with a bunch of es6 modules referencing each other.
2. There is one module (say, consts.js) with code similar to this:
```
const a = 'a';
const b = 'b';
export default {
    a,
    b
}
```
3. It is used in another module like that:
```
import consts from '../utils/consts';
```
Then, somewhere in the same module
```
let res = some_function(consts.a);
```
So far, so good.

4. The problem is, if I try to use non-existent member of _consts_, e.g consts.**c**:
```
let res = some_function(consts.c);
```
VS Code, or rather its built-in TS/JS extension, does NOT underline it as a problem!
And in my opinion, it should (or, at least, there should be a setting which allows me to configure this behavior).

If I rewrite the export part like this:
```
export default class {
    static a = a
    static b = b
}
```
I get the desired behavior, but I don't think this should be necessary. Normal JS object should also work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Confirmed with 3.7.0-dev.20190829

Example repo: https://github.com/mjbvz/ts-33153

**Comment by sandersn** [comment]
In JS, all object literals behave as if they have an index signature `{ [s: string]: any }`. To turn off this behaviour, set `"noImplicitAny": true` in your jsconfig (`"strict"` will also work).

**Comment by StasD** [comment]
`"noImplicitAny": true` does not make much sense in jsconfig.json because then it starts complaining about valid JS code and pretty much forces to rewrite it in TypeScript. No, thanks...
I, of course, know that referring to a missing member of JavaScript object is also a valid code, but in 99% of cases it is just a mistake and any respectful IDE should underline it as a problem.
