### ISSUE TITLE
Incremental build does not seem to improve perf. in case "outFile" is used

### ISSUE THREAD

**Issue by pankleks** [microsoft/TypeScript#33163]
Hello,

To build my web app, I'm not using any modules, just `outFile` setting.
Using `incremental: true` works fine but does not improve perf.

When I remove `outFile` flag and use `outDir`, incremental build improve perf. significantly.

Of course as result I get individual files, which I must concat. manually to get final file - but I was wondering why `outFile` makes incremental build to not perform as expected - in the end - as far I understand - it works based on source `.ts` files "versioning" so it should be independent from `outFile` setting.

Tested on TSC 3.6.2 (but had same behavior on previous versions too).

**Comment by sheetalkamat** [comment]
This is intended behavior.. With `--out` option any change needs to emit all files and hence no imporvements

**Comment by marco2216** [comment]
Is this the same case if --declaration is specified? It doesn't seem to improve compile times at all.
