### ISSUE TITLE
Exhaustiveness check in switch under a compiler flag

### ISSUE THREAD

**Issue by drets** [microsoft/TypeScript#33160]
I suggest to bring a bit more type-safety in TypeScript. By having a compiler option (say, `noIncompleteCaseInSwitch`) a compiler error will be thrown in the following case:
```ts
type Type = 'a' | 'b' | 'c'

const func = (t: Type): number => {
    let a = 42
    switch (t) {
        case 'a': {
            a += 1
            break
        }
        case 'b': {
            a += 2
            break
        }
    }
    return a
}
```
(the `'c'` branch is not handled in the switch)

I know the exhaustiveness check can be added by writing additional code in default statement (see answers for https://stackoverflow.com/q/39419170/2517622) but it would be nice to have support by compiler. 

I hacked the feature in https://github.com/microsoft/TypeScript/commit/67a947dcbaf3f7337e246ae4aba37cd8da54691c. It throws the error for the code above and doesn't throw it with `case 'c'` branch. The prototype code is not complete:
• `isExhaustiveSwitchStatement` or/and `possiblyExhaustive` should be adjusted. I had to comment `possiblyExhaustive` check in `isExhaustiveSwitchStatement` method since `possiblyExhaustive = false` if one of the cases doesn't have `return` statement
• a better error message should be thrown, telling which branches are missing
• tests should be added 

Thank you for this incredible piece of technology. I was impressed how easy to build typescript compiler locally.

**Comment by orta** [comment]
Coming from Swift, I expected this as an option in strict mode - I'm a +1 for what it's worth, but I'm not sure of the history about why it's not been built and shipped.

**Comment by ahejlsberg** [comment]
I'm not sure about this one. How is it different than requiring every `if` statement to have an `else` clause? I think there are perfectly good and common uses for non-exhaustive `switch` statements and I don't think it is correct to _force_ every switch statement to be exhaustive.

**Comment by drets** [comment]
@ahejlsberg thank you one more time for this awesome project. :hugs: 

Just to clarify the proposal:
```ts
type Type = 'a' | 'b' | 'c' | 'd' | 'e'

const func = (t: Type): number => {
    let a = 42
    switch (t) {
        case 'a': {
            a += 1
            break
        }
        case 'b': {
            a += 2
            break
        }
        default: {
            a += 3
        }
    }
    return a
}
```
The code above doesn't throw the compiler error since `default` statement. So, if there is a use case where programmer doesn't need to consider all the cases − just write a `default` case.

This proposal mimics Haskell's `incomplete-patterns` feature:
```haskell
data Type = A | B | C

foo :: Type -> Int
foo A = 1
```
Warning since B and C branches are missing.
```haskell
data Type = A | B | C

foo :: Type -> Int
foo A = 1
foo _ = 2
```
No warning since `_` as a default branch.

I was proposing this feature under an optional flag. 

`if` _usually_ have 1 or 2 branches, with `switch` programmer may have a lot of cases to pattern-match. I just wanted to help such programmer to not forget any case. 

Have a good weekend. :wink:

**Comment by drets** [comment]
I improved my prototype implementation in https://github.com/microsoft/TypeScript/commit/853e40d3716150ed9b6b61f8cf60fb92dae43ddc: 
• better error message, but still not perfect
• don't throw the error if `default` clause present

**Comment by sandersn** [comment]
This should be a linter feature:

1. It has an number of possible settings, all of which might be select by reasonable people.
2. Some of those settings are expensive to run.
3. Some of those settings would produce errors even on code that was intentionally written that way, which will not be an error at runtime, even if the code is not necessarily a good idea.

Personally, I would use [the super-simple setting for the eslint rule](https://eslint.org/docs/rules/default-case).

**Comment by drets** [comment]
Hi @sandersn and thank you for your input.

It's NOT about having a `default` clause in every `switch`.

It's about helping a user to not forget to pattern match on every union type OR specifying a `default` clause to not pattern match on everything _explicitly_ and safely handle such situation.

Consider this simplified example:
```ts
type Color = 'red' | 'green' | 'blue'

function getStartingNumber(): number {
  return 42
}

function colorToNumber(color: Color): number {
  let number = getStartingNumber()
  switch(color) {
      case 'red': {
          number += 1
          break
      }
      case 'green': {
          number += 2
          break
      }
  }
  return number
}

console.log("The number of blue is ", colorToNumber('blue'))
```
It outputs `42` but I expected `45`. I just "forgot" to pattern match on `'blue'`:
```ts
case 'blue': {
  number += 3
  break
}
```
Of course, if I have only 3 branches it's not a real issue, but what if I have a lot of branches? I want help from the compiler to tell me what I forgot to pattern match.

Can eslint get a type of switch expression and a type of every clause expression? I don't think so.

**Comment by sandersn** [comment]
Typescript works with eslint now, so you can write type-aware rules: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/experimental-utils
