### ISSUE TITLE
3.6 regression: composite project build time is slower than in 3.5.3

### ISSUE THREAD

**Issue by dbrockman** [microsoft/TypeScript#33161]
`tsc --build` in a composite project is a lot slower in version 3.6 than in 3.5.3.

I compared version 3.5.3 with version 3.6.2 and `typescript@next` (the _next_ tag resolves to `3.7.0-dev.20190830` at the time of writing).

When I do a clean build, without any `*.tsbuildinfo` files, it takes about 65 seconds on all these versions.

When running the build step again, with the `*.tsbuildinfo` files, it takes about 6 seconds on version 3.5.3 and about 55 seconds on version 3.6.2 and `typescript@next`.

| version | clean build time | repeated build time |
| ------- | ---------------: | ------------------: |
| `3.5.3` |         ~ 65 sec |             ~ 6 sec |
| `3.6.2` |         ~ 65 sec |            ~ 55 sec |
| `@next` |         ~ 65 sec |            ~ 55 sec |

**Comment by AnyhowStep** [comment]
I've experienced this Heisenbug a bunch of times.

I've had moments where a clean build took `20s` but an incremental build (by modifying one line of code) took `80s` with 3.5.1

Whenever that happens, I just do a clean build.
Then, subsequent incremental builds take a short amount of time again.

I can never seem to reliably reproduce this behaviour.

**Comment by dbrockman** [comment]
I should add that I ran the build step 3-4 times on each version and got very consistent results. The build time only differed by < 1 sec.

**Comment by sandersn** [comment]
@dbrockman can you share your project? If you can share it privately, contact @sheetalkamat. When you've done that, unassign yourself so that we know to take a look at this.

@AnyhowStep if you find a reliable repro, we would appreciate that too.

**Comment by chrisnojima** [comment]
This happens to me also. you can checkout our project here
https://github.com/keybase/client
Master is 3.5 and incremental builds take ~7 seconds
https://github.com/keybase/client/pull/19190
This is a PR for 3.6 and incremental builds take ~120s

**Comment by sheetalkamat** [comment]
Can you please try build from https://github.com/microsoft/TypeScript/pull/33145#issuecomment-526361771 to see if its the same issue?

**Comment by sheetalkamat** [comment]
@chrisnojima I was able to repro with your instructions and  #33415 does not help it. I am looking into it.

**Comment by sheetalkamat** [comment]
Seems like regression from #31985 where we are not converting semanticDiagnostics to absolute paths when reading builder program.

**Comment by DanielRosenwasser** [comment]
Can you all give typescript@3.6.3-insiders.20190909 a try on npm?

**Comment by chrisnojima** [comment]
Works great for me
Initial build: 165s
Incremental build: 8s
