### ISSUE TITLE
Break point are not trigger in the correct file with option <TypeScriptOutFile> 

### ISSUE THREAD

**Issue by Masclaux** [Microsoft/TypeScript#3317]
Hi !

Actually I work on mobile application (  https://github.com/Masclaux/LightReader )  

When I start to debug break point are not trigger on the correct file.

This issue arrive only with "<"TypeScriptOutFile>app.js"</"TypeScriptOutFile">". If I remove and set all JavaScript references manually it work. 

Tools: 

- Visual Studio 2013  Tools for Apache Cordova 
- Typescript 1.4 and 1.5

**Comment by sheetalkamat** [comment]
@Masclaux : I tried opening and running your project by commenting out individual file reference and instead using scripts/app.js from the index.html. Also had to include <typescriptOutputFile> in project's debug config too. But I ran into build issues with jquery.d.ts and hence its not able to deploy and I cant go ahead with repro steps. Could you let me know what I need to do to get this to run.

**Comment by Masclaux** [comment]
HI, can you copy past your error ? 

PS ;  I'm just finished clean install of windows 10 and visual studio 2015.  My 40 Go  SSD cannot let me install another version of visual studio.

**Comment by sheetalkamat** [comment]
@Masclaux I installed vs2015 and now the project wont open saying its incompatible.It would be easier to get steps to repro this on vs2015. Thanks.

**Comment by Masclaux** [comment]
yes i'm working on it.

**Comment by Masclaux** [comment]
@sheetalkamat  hi 

you can try now with vs2015.

Bug reproductible.

**Comment by sheetalkamat** [comment]
I am getting this error:
![errorrunninglightreaderproject](https://cloud.githubusercontent.com/assets/8052792/9391414/7c111ba8-472b-11e5-9e11-5da4657b3ee8.JPG)

**Comment by Masclaux** [comment]
I try on 2 differents computer/install and I'm not getting this error. Look like related to your visual studio installation.

**Comment by sheetalkamat** [comment]
@Masclaux  Are you still having issues with debugging through <TypeScriptOutFile>? I was finally able to load your project and run but I am not sure what to update to enable TypeScriptOutFile.

**Comment by Masclaux** [comment]
Hi 

Did you use the original project with issue => https://github.com/Masclaux/LightReader_old 

or the new one => https://github.com/Masclaux/LightReader who are totqally different and option TypeScriptOutFile cannot be activated.

**Comment by sheetalkamat** [comment]
@Masclaux  I used the new project. Will give it a try with the old one to see if I can repro the issue

**Comment by sheetalkamat** [comment]
@Masclaux , Ok I got this working and it seems like the issue doesn't repro any more. I was able to debug the project and it did end up hitting breakpoint in index.ts correctly as shown here.
![debuggingworkingwithoutfile](https://cloud.githubusercontent.com/assets/8052792/11281902/8cd93af6-8eb1-11e5-937d-cb5815ab9cf1.JPG)

**Comment by Masclaux** [comment]
Hi 


if i remember correctly the issue appear when you continue to Step Over.

Try to break in Bakatuski.ts or MenuParser.ts . 

I test it at home and look like it work now. Maybe the issue was fix with cordova tools update.

**Comment by sheetalkamat** [comment]
@Masclaux, tried your suggestion and still no repro. As you mentioned this looks fixed. I am going to close this but feel free to open it again if you run into issues.

**Comment by Masclaux** [comment]
ok next time i provide video and a better repro :)
