### ISSUE TITLE
lib/.gitattributes is shipped in the tarball

### ISSUE THREAD

**Issue by SnarkBoojum** [microsoft/TypeScript#33172]
It doesn't belong in a release tarball.

**Comment by austincummings** [comment]
@SnarkBoojum I'm not seeing that file in any of the 3.6 release tarballs from GitHub, nor in `node_modules/typescript` when using npm. Am I missing it?

**Comment by SnarkBoojum** [comment]
$ wget -c https://github.com/microsoft/TypeScript/archive/v3.6.3.tar.gz
(downloads tarball)
$ tar taf v3.6.3.tar.gz |grep .gita
TypeScript-3.6.3/.gitattributes
TypeScript-3.6.3/lib/.gitattributes

**Comment by SnarkBoojum** [comment]
[This page](https://github.com/microsoft/TypeScript/releases) points to the link I gave as source code... hence that's what I use.

**Comment by orta** [comment]
That page will always link to the source code because those links are auto-generated by GitHub. We can't do anything about it I'm afraid.
