### ISSUE TITLE
Compile libraries with --strict=false, but compile src with --strict

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#33177]
## Search Terms

strict mode, strict, skipLibCheck

## Suggestion

Allow uses to use:

```
skipLibCheck: false,
libCheckMode: 'non-strict' 
```

what it means is users want to re-compile library code (for some reason?), but want to switch strict mode off for library code.

## Use Cases

I maintain a few libraries written in TS and sometimes users will say my library doesn't compile in strict mode. I prefer to not use strict mode. So I can tell my users to use `compilerOptions.skipLibCheck = true`, but sometimes they don't want to skipLibCheck, so it would be nice for them to skip strict checking for libraries, but do strict checking for their own code?

_important_: I may have a misunderstanding - it could be that `tsconfig.json` in node_modules projects override the end-user's settings, so perhaps I can prevent strict mode for library, in the case that my library only compiles in non-strict mode?

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sandersn** [comment]
No, you are right, all files in a compilation have to use the same settings. There is no way for a library to compile in non-strict, but have source compile in strict.

**Comment by ORESoftware** [comment]
Ok thanks.

Then this would be a feature request - it would be nice to compile libraries in strict and source in non-strict, or vice versa. Even compiling certain libraries as strict and certain ones as non-strict, perhaps according to their tsconfig.json files (if those are not excluded by .npmignore etc).

**Comment by sandersn** [comment]
I thought we had seen this request before but I can't find it. This is a surprisingly complex feature, so we need some kind of proposal that thinks through the issues.

**Comment by MartinJohns** [comment]
@sandersn You were probably thinking of #31035.

**Comment by sandersn** [comment]
Yep, that's it. Thanks @MartinJohns
