### ISSUE TITLE
extended type to never not saved

### ISSUE THREAD

**Issue by kolodny** [microsoft/TypeScript#33179]
This is related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36661

It appears that when a `K = keyof T` where `T` is `unknown`, `K` is `never`. However when trying to use that fact in a conditional type it fails. Here's an example (The last two lines are where the bug is highlighted):

```ts
declare function spyOn<T, K extends keyof T>(
    object: Record<K, Function>,
    method: keyof T extends never ? string : K,
): void;

declare function spyOn2<T, K extends keyof T>(
    object: Record<K, Function>,
    method: K extends never ? string : K,
): void;

class MyClass {
    myMethod() {}
    propShouldError = 123
}

spyOn(new MyClass, 'myMethod') // OK
spyOn2(new MyClass, 'myMethod') // OK

spyOn(new MyClass, 'propShouldError') // ERROR
spyOn2(new MyClass, 'propShouldError') // ERROR

spyOn(new MyClass, 'notExistingShouldError') // ERROR
spyOn2(new MyClass, 'notExistingShouldError') // ERROR

declare let a: any

spyOn(a, 'thisShouldWork') // OK
spyOn2(a, 'thisShouldAlsoWorkButDoesnt') // ERROR
```

https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwGcAHATwHlUAeAFQBp4BpeEADwxFWAPgGsQScieNQB8ACgBQ8afBwAjAFbgMALngAlcDhjBKDegDE0mXKhG0pMgLYgMACxzA1fAUOrM2HLvFQgAbiAw8AD8hBgwWKgA5vBq+hIAlGp+OFjAANwSEqCQsAgo6Nh4hKQUAEw09Eys7JzcLoLC4pbS8kqYappg2rr68EaFpuYt8Db2jnEetd6+AUGhBOGRMXEWSfApaZkSuQTcALIkAMLQe-AA3iNWJPu2DsBiCRcAviNEMDhEAMoOyBDAAFEYB8ggBeeAARjKAGYJK8JMRyKgxL4AO7wQ4nKB7egAcmut3GwFxTwA9KT4GQGAjSqgyiiQOjMacCHiCXdHCT4OTKdSaUiGUzjiy8e9Pj8cH9AcDtFyeQD1OoyOp+eVBRjhdjWfBcWLvr9-kCQXKKQqlSrVci0RqsTidagcBgASwsItlhKpUbZWTTYrlZb6dbmVq8Q6nS63dEPYaZTATfAzf7suBoHB4BBbPAoGooKgSFlERQxFA8fZXdHgAB1bQ8eNUgPF0t2csG4AAQQgBBw1ZgPAAQsgMAARHAgAioDDxxMqoA

**Comment by fatcerberus** [comment]
I'm pretty sure this is the work of distributive conditional types.  If `K` is `never` then distributing over it always produces `never` (it's treated as an empty union), so your `K extends never` check isn't doing what you think it is.

https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types

Distribution is generally useful and is therefore the default behavior, but can be disabled on a per-type basis.  The following disables the distributive behavior and makes the last line in your example work:
```ts
declare function spyOn2<T, K extends keyof T>(
    object: Record<K, Function>,
    method: [K] extends [never] ? string : K,
): void;
```

Distribution only happens over a "naked type parameter".  Give it some clothes to turn that off. :)
