### ISSUE TITLE
Iterables should be assignable to array-constrained type parameters

### ISSUE THREAD

**Issue by jason-chang** [microsoft/TypeScript#33173]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
String.fromCharCode.apply(null, new Uint8Array(buff))
String.fromCharCode.apply(null, new Uint16Array(buff))
String.fromCharCode.apply(null, new Uint32Array(buff))
```

**Expected behavior:**
Code like below should not get an error even with compiler option "--strict" is enabled.

```typescript
String.fromCharCode.apply(null, new Uint8Array(buff))
String.fromCharCode.apply(null, new Uint16Array(buff))
String.fromCharCode.apply(null, new Uint32Array(buff))
```

**Actual behavior:**

But now i got an error like this:

![image](https://user-images.githubusercontent.com/4367687/64062153-df0c1000-cc15-11e9-8971-282dbaf895cf.png)

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
This is a general problem with `apply`:

```ts
declare function f<T>(...xs: T[]): void
f(...new Uint8Array([1,2,3])  // ok
f.apply(null, new Uint8Array([1,2,3])) // error
```

**Comment by jason-chang** [comment]
close

**Comment by jason-chang** [comment]
close

**Comment by KuSh** [comment]
Hello,

Why was this issue closed ?
Problem still exists on latest typescript released version (and nightly). See [playground](https://www.typescriptlang.org/play?#code/MoFwTglgdg5gdAMzAewLYGEAWBDM7kAmApnNgA5kA2AngBRQCullANAARREDubAqtCAAcAQTBhsdAEYMECAJRyAUKEixEKDDjyES5KnUbN2nHvyggAjADZR4qTPlKV0eEjRZc+YqQo16TVg5uPgEAZgAmWwlaaVkFIA)
