### ISSUE TITLE
FormData vs Document

### ISSUE THREAD

**Issue by urbanhop** [Microsoft/TypeScript#3319]
This code

        var fd = new FormData();
        fd.append(file.name, file);
        var xhr = new XMLHttpRequest();
        //...
        xhr.send(fd);

does not work anymore with TS 1.5:

    Severity	Code	Description	Project	File	Line
Error	TS2345	Argument of type 'FormData' is not assignable to parameter of type 'string'.	web	H:\dev\snjupa\snjupa\Snjupa.Web\client\scripts\manager\service.ts	90

AFAIK FormData is still the right type for xhr.send(). Why did lib.d.ts change? Is it correct?

**Comment by rielz** [comment]
You are correct, FormData is a valid parameter for XHR's send, as is Blob, Document, string, ArrayBufferView and (depending on the spec) URLSearchParams and ArrayBuffer.

The FormData overload seems to be missing in the 1.5 (pre-)release shipped with VS15 PRE but the definition file here on GitHub is already fixed.

As a temporary solution you can add this definition to your source file: 

```typescript
interface XMLHttpRequest
{
	send(data?: FormData): void;
}
```

(I tend to create a fix.d.ts in my TypeScript projects for such things)

**Comment by mhegazy** [comment]
This should be fixed in the next release. can you give this file a try: https://raw.githubusercontent.com/Microsoft/TypeScript/release-1.5/bin/lib.d.ts

**Comment by urbanhop** [comment]
Thank you, very helpful and fast responses here.

Did a simple <any> cast to please the typescript compiler, no big deal. I just wondered if there is an HTML5 API change in the pipeline that forces me to change my code. Glad to hear this is not the case.

I leave it up to you to close this issue.
