### ISSUE TITLE
Never type is not inferred when used from helper function

### ISSUE THREAD

**Issue by Hurtak** [microsoft/TypeScript#33193]
**TypeScript Version:**  3.5.1

**Code**

```ts

type UnionType = "A" | "B"

function getSomething(foo: UnionType): number {
    switch (foo) {
        case "A":
            return 1;
        case "B":
            return 2
        default:
            const _: never = foo;
            return _;
    }
}

function getSomethingInlineNeverFail(foo: UnionType): number {
    switch (foo) {
        case "A":
            return 1;
        default:
            const _: never = foo; // Type '"B"' is not assignable to type 'never'.
            return _;
    }
}

function getSomethingHelperNeverNoFail(foo: UnionType): number {
    switch (foo) {
        case "A":
            return 1;
        default:
            return never(); // No type error
    }
}

function never(): never {
    throw new Error("Should never happen");
}
```

**Expected behavior:**
There is type error in getSomethingHelperNeverNoFail function

**Actual behavior:**
No type error in getSomethingHelperNeverNoFail function

**Playground Link:** http://www.typescriptlang.org/play/#code/FAFwngDgpgBAqgOwJYHsEBVKwLwwEQCCeMAPvgEJ7DABmArggMYioIwDmUIAyigLZcAFkgTsAFDRQoAXPGRpM0AJSyEdPgCMoAJxgBvYDCMwAzgHckIRoJgSpS-YePPGAQxOxCeaU+d+Y2lx02mwAjADcvn5uHhTeUf5GgSDBbABMCcYAJlA0rnQANiA+idFoJiAwAPqqUABuOjC4kiiRpc7JqdVtxgC+wP20DMysHFy8AiDCogCSCAUiUABy9ToAYq5IBXYycqyKUCowapqNBs7mlta2LQ7niTGeRCXtSUEhMBGZRjl5hcXfMoICrVWoNXTNKThGAAehhMAOMAA5HhKEiYEgTMcUJV3CYkOwEK4NAVYCAUDBwNBkQhVtokQA6QEdd5sKo9Iz9Qb0JgsNBjHj8IQidgACSgBWg2hW4KWKA2Wx2skQ+ywRxOWl09yMlysNh2d0Bj3wz2Zxk6Hy+pV++SKL1eFrYtPBYiU0LhMDllKwMB02hQ2iiXOoPJG-OdOldYLOUSm-rMxygCYAotp-doxHhuIIUIUsonwTBBK4INAEHg3QMgA

**Comment by IllusionMH** [comment]
Function should accept param of type `never`, otherwise there should be no checks and TS works correctly.

```ts
function getSomethingHelperNeverNoFail(foo: UnionType): number {
    switch (foo) {
        case "A":
            return 1;
        default:
            return never(foo); // you should pass param to function to enable type check
    }
}

function never(val: never): never {
    throw new Error("Should never happen");
}
```

http://www.typescriptlang.org/play/#code/FAFwngDgpgBAqgOwJYHsEBVKwLwwEQCCeMAPvgEJ7DABmArggMYioIwDmUIAyigLZcAFkgTsAFDRQoAXPGRpM0AJSyEdPgCMoAJxgBvYDCMwAzgHckIRoJgSpS-YePPGAQxOxCeaU+d+Y2lx02mwAjADcvn5uHhTeUf5GgSDBbABMCcYAJlA0rnQANiA+idFoJiAwAPqqUABuOjC4kiiRpc7JqdVtxgC+wP20DMysHFy8AiDCogCSCAUiUABy9ToAYq5IBXYycqyKUCowapqNBs7mlta2LQ7niTGeRCXtSUEhMBGZRjl5hcXfMoICrVWoNXTNKThGAAehhMAOMAA5HhKEiYEgTMcUJV3CYkOwEK4NAVYCAUDBwNBkQhVtokQA6QEdd5sKo9Iz9Qb0JgsNBjHj8IQidgACSgBWg2hW4KWKA2Wx2skQ+ywRxOWl09yMlysNh2d0Bj3wz2Zxk6Hy+pV++SKL1eFrYtPBBuhcJgcspWBgOm0KG0US51B5I35zp0YjqrgKYJ06rpjmcUz9ZmOUFTAFFtH7tGI8NxBChClk0+CYIJXBBoAg8EpIr0gA

**Comment by Hurtak** [comment]
"Function should accept param of type never, otherwise there should be no checks", but why? Shouldn't the never type be inferred from the return value of the function?

**Comment by fatcerberus** [comment]
`never` is the [bottom type](https://en.wikipedia.org/wiki/Bottom_type) and therefore assignable to all other types.  There is no type error in your code.

**Comment by IllusionMH** [comment]
There are no problem with returning `never` as described above.

As for handling functions with `never` - 
probably you are looking for https://github.com/microsoft/TypeScript/issues/12825

And you can see related discussion in comment: https://github.com/microsoft/TypeScript/issues/14490#issuecomment-284598510

**Comment by Hurtak** [comment]
Thanks for the links and explanation. Should I close this issue, since there is overlap with linked issues, or is there some value to keeping it open?

**Comment by IllusionMH** [comment]
Not sure if there are any actionable items left, so most likely this issue should be closed.

However if you are sure that there are some you can let if open for TS team to decide.
