### ISSUE TITLE
Strange behavior of mapped types when using with string

### ISSUE THREAD

**Issue by lorefnon** [microsoft/TypeScript#33196]
**TypeScript Version:** 3.7.0-dev.20190831

**Search Terms:** mapped types

**Code**

```ts
type M<T> = {
  [K in keyof T]: never;
}

type MStr = M<string>;
```

**Expected behavior:**

`MStr` is an object type where the corresponding value type for all properties of string type ("toString" | "charAt" | "charCodeAt" | "concat" | "indexOf" ...) will be never

**Actual behavior:**

type of `MStr` is `string`

**Playground Link:**  [Link](http://www.typescriptlang.org/play/#code/C4TwDgpgBAsgPAFQHxQLxQN4CgpQNoDSUAlgHZQDWEIA9gGZQIC6AXFKRAG4QBOA3FgC+WLKEiwAysB5pYcAM7SyAcyR8gA)

**Related Issues:** 

- https://github.com/microsoft/TypeScript/issues/32484

**Comment by jack-williams** [comment]
This is working as intended (though I'm not sure where this behaviour is explicitly documented...other than the source code [1]).

Your alias `M` defines what is known as a homomorphic mapped type, indicated by the key constraint being `keyof T` for some `T`. When a homomorphic mapped type is instantiated with a primitive type it passes through unmodified.

To get your desired behaviour you can write: `type MStr = Record<keyof string, never>`. The type alias `Record` defines a normal mapped type, not a homomorphic one.

[1]

```ts
// For a homomorphic mapped type { [P in keyof T]: X }, where T is some type variable, the mapping
// operation depends on T as follows:
// * If T is a primitive type no mapping is performed and the result is simply T.
```

**Comment by fatcerberus** [comment]
From a practical perspective, I would probably find it a bit odd if the mapped type silently promoted `string` to an object type, since `string` is not assignable to `object` (but is assignable to `{}` so... hm...)

**Comment by jack-williams** [comment]
`string` is assignable to `Object`, however.

**Comment by AnyhowStep** [comment]
I'm on mobile and can't test but what about, `{ [k in Extract<keyof T, string|number|symbol>] : never }`

I think that should work. If you only care about string keys, change it to extracting string

**Comment by lorefnon** [comment]
> Your alias M defines what is known as a homomorphic mapped type, indicated by the key constraint being keyof T for some T. When a homomorphic mapped type is instantiated with a primitive type it passes through unmodified.

@jack-williams Thanks for clarifying on this. 

I didn't about the above, and assumed that because mapped types use object notation `{ [...] : ... }` they can be expected to always be object types.

> To get your desired behaviour you can write: type MStr = Record<keyof string, never>. The type alias Record defines a normal mapped type, not a homomorphic one.

I had simplified my usage to come up with a reproducer, so the above is not exactly applicable. 

However the [solution](https://github.com/microsoft/TypeScript/issues/33196#issuecomment-527233721) by @AnyhowStep work quite well and solves my use case.

**Comment by fatcerberus** [comment]
Yeah, mapped types are essentially a form of type operator that just happens to use object notation.  It’s kind of confusing, I would agree.  TS gets *a lot* of mileage out of a small amount of syntax. :smile:

**Comment by lorefnon** [comment]
I'll close this as the team believes that this behavior is intended. Thanks a lot for the help.
