### ISSUE TITLE
Request for a way to import multiple external modules into same namespace 

### ISSUE THREAD

**Issue by karbroski** [Microsoft/TypeScript#332]
Very similar to the following issue, which I didn't find in Github: http://typescript.codeplex.com/workitem/305

As a NodeJS / TypeScript developer who:
* uses one class per file and compiles to separate files (i.e. uses external modules)
* uses namespaces to organize classes

I would like an elegant way to:
* reference imported namespaces without re-declaring them
* import multiple external modules into the same namespace

For example, if I have a `HouseFactory` class and I need to import `Door`, `Window`, and `House` classes which have been exported into the namespace `MyNamspace.Model`, I would like to be able to do something like the following:

```javascript
import '/src/model/door';
import '/src/model/window';
import '/src/model/house';
var myDoor = new MyNamespace.Model.Door();
var myWindow = new MyNamespace.Model.Window();
var myHouse = new MyNamespace.Model.House(myDoor, myWindow);
```

This would compile to something along the lines of:
```javascript
var MyNamespace = {};
MyNamespace.Model = {};
MyNamespace.Model.Door = require('/src/model/door');
MyNamespace.Model.Window = require('/src/model/window');
MyNamespace.Model.House = require('/src/model/house');
// ...
```

**Comment by sarooghi** [comment]
Any update for this issue? 
http://stackoverflow.com/questions/12882748/how-do-you-put-multiple-external-modules-into-the-same-namespace-in-typescript

**Comment by mhegazy** [comment]
Looking at this again, the recommendation here is to use ES6 module syntax:
```ts
import {Door} from "src/model/Door";
```

The tools also should help rename all your imports in one shot if you need to.

I would also recommend against using namespaces as an extra wrapper around modules, modules already give you encapsulation, unless you have a huge module that needs extra level of organization, i would not use it, see a more detailed discussion here: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md#do-not-use-namespaces-in-modules
