### ISSUE TITLE
Declaration merging leads to compile errors in dependency in a monorepo

### ISSUE THREAD

**Issue by Bessonov** [microsoft/TypeScript#33208]
**TypeScript Version:**  3.6.2, next

**Search Terms:**
declaration merging dependency 

**Code**

Reproduction example:
https://github.com/Bessonov/declaration-merging-bug/

```bash
yarn install
yarn build
```

Basically, there is a monorepo. Package `a` defines an interface and use it:

```ts
export interface Test {
}

export const test: Test = {}
```

Package `b` has a dependency to package `a` and try to extend the interface for own usage:

```ts
declare module '@test/package-a' {
	interface Test {
		breaks: boolean
	}
}
```

**Expected behavior:**

I'm not sure that is by design, but I would like to expect, that declarations in package `b` doesn't affect usage or declarations in the dependency, in this case in the package `a`.

**Actual behavior:**

Compilation of package `b` leads to compile errors in the dependency:

```
$ tsc
../package-a/index.ts:4:14 - error TS2741: Property 'breaks' is missing in type '{}' but required in type 'Test'.

4 export const test: Test = {}
               ~~~~

  index.ts:5:3
    5   breaks: boolean
        ~~~~~~
    'breaks' is declared here.
```

**Playground Link:** 
https://github.com/Bessonov/declaration-merging-bug/

**Related Issues:** 
I'm not sure, that [this proposal](https://github.com/microsoft/TypeScript/issues/8464) is related to my issue.

**Comment by sandersn** [comment]
Let me see if I can summarise: package-a builds OK, but package-b builds with errors. However, the errors are in package-a's code.

That's because Typescript's default compilation mode checks every file that is imported. It sounds like you need a more complex build that 

1. builds package-a first
2. generates package-a/index.d.ts
3. builds package-b, referring *only* to d.ts files in package-a, not the actual .ts files.

I think [project references can do this](https://www.typescriptlang.org/docs/handbook/project-references.html), but you might still need a separate build tool.

**Comment by Bessonov** [comment]
@sandersn Thank you very much for your response! Maybe it's better to describe my use case. TBH, I'm not sure, that my configuration is entirely correct, but except this error it works fine for me.

In my use case I don't actively build the package `a`. There are two phase involved:

1. Development phase

In this phase, I use [ts-node-dev](https://github.com/whitecolor/ts-node-dev) to bootstrap a [micro](https://github.com/zeit/micro) application in package `b`:

```ts
import http from 'http'
import micro from 'micro'
import { app } from '.'

const server = new http.Server(micro(app))

server.listen(3000)
```

The `app` imports functionality from package `a`. In this setup, I'm able to make any changes to package `a` or package `b`, server restarts and compile files on-the-fly. This is very enjoyable and doesn't need any "file system watcher".

2. Build phase

To deliver the app and reduce the start-up time, I compile the app to js in two steps. In the first step the compiler checks with `tsc --noEmit` for compile errors. In the second step everything is combined to one js file with webpack and ts-loader:
```ts
rules: [
	{
		test: /\.tsx?$/,
		loader: 'ts-loader',
		options: {
			transpileOnly: true,
		},
	},
],
```

> That's because Typescript's default compilation mode checks every file that is imported.

I'm total fine with it. But I'm wonder about the ordering of the checks, because package `a` doesn't have any reference to package `b`. Therefore I would expect, that the compiler process package `a` first. I'm not sure, that project refrences can help in this situation.

Regardless it's a bug or intended behavior, do you know a better way/example to reach my goal? I think this might be interesting for a wider group of ts and monorepo users.

**Comment by Bessonov** [comment]
OK, tomorrow is now :rofl: I've tried it [with project refrences](https://github.com/Bessonov/declaration-merging-bug/compare/master...projectReferences). Indeed, this helps with compilation.

But it creates a bunch of disturbing files like `.d.ts.map` (for vscode navigation), `*.js`, `*.d.ts`, that means I have now 4x more files and it's very difficult to open/navigate in IDE or vim.

The compilation feels now much slower as just with `ts-node-dev` alone.

**Comment by Bessonov** [comment]
@sandersn still, for me it's a bug that TypeScript joins code from downstream packages.
