### ISSUE TITLE
Different behavior of conditional types between in generic and not in generic

### ISSUE THREAD

**Issue by worudso** [microsoft/TypeScript#33209]
**TypeScript Version:**  3.6.2

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
type Foo = { a: string } | { b: number };
type Bar = Foo extends { a: any } ? Foo : never; // never
type ExtractA<T> = T extends { a: any } ? T : never;
type Qux = ExtractA<Foo>; // { a: string }

type Quz = Extract<Foo, { a: any }>; // { a: string }
```

**Expected behavior:**
`Bar`, `Qux` and `Quz` work the same.
https://gist.github.com/worudso/83909a621ff12a2c6b258a1d94c19dd2
I implemented it using the behavior of `Qux`. See `MysteriousGeneric`.
But I'm not sure it's right. I didn't expect it to work.

**Actual behavior:**
Only `Bar` works differently.
**Playground Link:** 
http://www.typescriptlang.org/play/#code/C4TwDgpgBAYg9nKBeKBvKBDAXFAzsAJwEsA7AcygF8oAfNKAIxxIFcBbBiAqgbgChQkKACEM3FPEQQAHsAgkAJrnrZMJEFSgB+WAijMIANy48oAejNQSRrgPDQAorIIYAxsACCAHgAqAPmQoHygZOUVldFUMdU0dYINjAn5BaABFFmlAp0I3Ty9JP1MLFRx8YnIqPjshdIAvLOdc-IQAGhK1DUpC80tI0sJSCkogA
**Related Issues:** 
generic, conditional types

**Comment by jack-williams** [comment]
This is working as intended. Here is the relevant handbook page:  https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types
