### ISSUE TITLE
Missing use-before-defined error for enums

### ISSUE THREAD

**Issue by asurance** [microsoft/TypeScript#33204]
**TypeScript Version:**  3.5.1
**Code**
```ts
class test {
  static log() {
    console.log(Const.value);
  }
}
test.log();
enum Const {
  value = 1
}
```
```ts
class test {
  static instance = new test();
  constructor() {
    console.log(Const.value);
  }
}
enum Const {
  value = 1
}
```
**Expected behavior:**
Run with no error
**Actual behavior:**
Uncaught TypeError: Cannot read property 'value' of undefined
**Playground Link:** 
http://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEAuCmFbQN4FgBQ1pLLAlsNCAPYDmAFAJSqbbbAkB2EJI8AdKZQMLNIcAbmBABXeFQDcdaAF9M8jAgHdq0jPCaiAttD4tk6LNGFj40ALzQAjAsxA
http://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEAuCmFbQN4FgBQ1pLLAlsNPgHa4nDzQC80J8A7nIrABQCUA3JtsAPZlYAJwCuwWHyEdUPbNH5k+IeADoQfAOasAwgKQqAbmBAj4XWQF9MVjPBIiAttF2CZWaEZNVaARmuYgA
**More Info**
Use const enum or use enum before class declaration can avoid this problem。
Maybe enum object should be moved ahead of file after complied。

**Comment by AnyhowStep** [comment]
I never understood why people liked to use declarations before their... Declaration.

Function hoisting is a language feature but I'm not sure if enum hoisting should be ¯\_(ツ)_/¯

**Comment by AlCalzone** [comment]
I used to have my enums at the bottom of source files but when I switched to `typescript-eslint` all those locations were marked as errors. Now I know why.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't enforce TDZ violations inside function bodies since this isn't really detectable apart from the cases where it always fails immediately anyway
