### ISSUE TITLE
[Question] Is there any way to transpile to vanilla js? No commonjs or adm.

### ISSUE THREAD

**Issue by ericmdantas** [Microsoft/TypeScript#3322]
Hello!

I'm trying to build a module that the user (developer) will consume by either using:
- Pure javascript: He'll have my ```class``` loaded in the global scope, for example.
- Commonjs: He'll be able to call it using ```require``` - and maybe with SystemJS.
- AMD: He'll be able to use it with RequireJS and maybe with SystemJS.
- ES6: He'll be able to use it with the ES6 syntax.

So, right now I'm using ```gulp-typescript``` to transpile my code to the ```dist``` folder. I transpile once for ```commonjs```, once for ```amd```, once for ```es6```.. but it seems that there's no way to transpile to pure Javascript (other than using the module syntax *inside* my ```.ts``` file).

Is there any way to accomplish this?

Thanks in advance!

**Comment by LPGhatguy** [comment]
For vanilla case, CommonJS and AMD, you could wrap your code in a [UMD](https://github.com/umdjs/umd) loader.

I'm fairly sure that detecting ES6 loading capability is still an unsolved problem.

**Comment by DanielRosenwasser** [comment]
As per #2036 we'll have the `umd` option for the `--module` flag in 1.5, but I don't think it covers the "standard JS" case.

**Comment by ericmdantas** [comment]
@LPGhatguy, @DanielRosenwasser: well, I'll have to wait for 1.5 then.

Do you guys know if ```SystemJS``` compatibility is also target for 1.5?

**Comment by DanielRosenwasser** [comment]
> Do you guys know if SystemJS compatibility is also target for 1.5?

Yes I do and [yes it is](https://github.com/Microsoft/TypeScript/wiki/Roadmap). :smile: 

Also see our [list of compiler options](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options).

**Comment by ericmdantas** [comment]
Awesome!

Thank you!
