### ISSUE TITLE
Optional parens for single argument arrow functions

### ISSUE THREAD

**Issue by samccone** [Microsoft/TypeScript#3323]
In es6 one can define an arrow function with optional parens

```js
[1, 2, 3].map( v => v + 1)
```

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=%5B1%2C2%2C3%5D.map(v%20%3D%3E%20v%2B%2B)%0A

In typescript (1.5.0beta) one can not

```typescript
[1, 2, 3].map( v:number => v + 1)
```

##### Error
```
foo.ts(1,17): error TS1005: ',' expected.
```

Ideally this would be supported given the es6 superset goals of typescript (unless I am mistaken)

------

Thanks for this great tool :+1:

**Comment by DanielRosenwasser** [comment]
You can do it; I just believe you can't supply a type annotation (i.e. you could write `v => v + 1`).

In practice, this is never a problem because of *contextual typing*<sup>[1][2]</sup>. For instance, in your example, since we know that `map` takes a function of type `(value: number, index: number, array: number[]) => number)`, we will contextually type the parameters of `v => v + 1` such that `v` is typed as `number` from the type of the parameter `value`.

See:
<sup>[1]</sup> [Contextual Typing in the TypeScript Specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#15-contextual-typing).
<sup>[2]</sup> [Contextual Typing in the TypeScript Handbook](https://github.com/Microsoft/TypeScript-Handbook/blob/d33b68c9c62fada2cbdbcdcea00e9c1655e0c5e8/pages/Type%20Inference.md#contextual-type).

**Comment by samccone** [comment]
> You can do it; you just can't supply a type annotation without the parens

I suppose that is my pain point, Ideally (whether it is needed or not) defining the type inside a paren-less  arrow function without an error being thrown seems like the ideal outcome, rather than a compile time error. 

What do you think?

**Comment by DanielRosenwasser** [comment]
> What do you think?

I think it was probably a parsing ambiguity issue. For instance:

```TypeScript
function f() { }
var cond = Math.random() < 0.5;
var thing = cond ? x : number => number
```

What is the right thing to do? Is that `cond ? (x) : (number => number)`? Or is it `cond ? ((x: number) => number)` with a missing false branch? I don't think we wanted to allow this sort of pitfall for users, nor deal with the associated parsing recovery rules/lookahead we'd have to think up.

Another issue I just thought of is that there's no place for the return type of a lambda with no parens.

```TypeScript
var x = (foo: number): number => foo;
var y = foo: number /*?*/ => foo
```

I think you'd introduce a certain awkward inconsistency between parameter types and the return type. But I don't know if that's necessarily all that important.

I'll defer to those who've been on the team for longer such as @CyrusNajmabadi, @RyanCavanaugh, @danquirk, and @mhegazy who probably were around for such decisions.

In general, I don't see this as particularly big issue; if you're willing to type out a type annotation, what's two extra keystrokes? :smile:

**Comment by RyanCavanaugh** [comment]
I think you got all the motivations -- even lacking other parser ambiguities, it's totally unclear whether this annotation would refer to the return type or the parameter type. And most arrow functions where you care about taking up characters are contextually typed anyway.

**Comment by samccone** [comment]
Just to be clear (not trying to be a pain) @RyanCavanaugh 

This seems like a compat issue as far as 1:1 es6 support goes.

Even so, I think the error message is unexpected, and unclear. As a user of typescript I expect to be able to type arguments in my functions, however in this one case I get a compile time error that is not aligned with my expectations. 

---

So sure, it may not be needed due to type inference however do you think people are simply not going to try this?

**Comment by DanielRosenwasser** [comment]
> This seems like a compat issue as far as 1:1 es6 support goes.

How so? Type annotations aren't part of ES6.

**Comment by samccone** [comment]
Let me clarify my logic

optional parens on arrow functions (with arguments) are a part of ES6
typescript adds type annotations for function arguments 

not supporting type annotations on arrow functions without parens seems like a compat issue

**Comment by RyanCavanaugh** [comment]
There's no compat issue here because you're never *required* to not have parens, nor are you ever *required* to have a type annotation.

We're not required to add type annotations to one production just because we added them to some other production that serves a similar purpose.
