### ISSUE TITLE
Allow passing of a Generic type without types specified to be used as a generic type factory

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#33231]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
Generic type factory 
pass generic type without generic types 

**Code**

```ts
/**
* Base interface for all Monads
*/
export interface IMonad<M extends IMonad<any, any>, T, E = never> {
    map(func: (value: T) => T | E): M<T, E>; // I want to be able to return a monad of a different type
    do(func: (value: T) => any): this;
    defaultTo(value: T): T;
    getError(): E;
}
 
export interface IMaybe<T> extends IMonad<MaybeFactory, T> {}
export type MaybeFactory<T, _E> = IMaybe<T>; // create a "factory" to allow base interface to return Maybe of different types
 
export interface IEither<T, E> extends IMonad<EitherFactory, T, E> {}
export type EitherFactory<T, E> = IEither<T, E>;
 
const maybe = {} as IMaybe<number>;
 
const returnedMaybe = maybe.do(() => console.log());
const maybeValue = maybe.defaultTo(6);
 
const either = {} as IEither<number, string>;

const returnedEither = either.do(() => console.log());
const eitherValue = either.defaultTo(6);
const eitherError = either.getError();

```

**Expected behavior:**
I would like to be able to pass `MaybeFactory` or `EitherFactory` (or some other type that I have not yet considered) to the `IMonad` interface so that `IMonad` can return Maybes or Eithers of different types

**Actual behavior:**
It is not possible to reference a Generic type without the Generics specified so at the moment I cannot see a way of achieving what I want to achieve.

**Playground Link:**  
http://www.typescriptlang.org/play/#code/PQKhCgAIUghBDAzgU0gSwHYBdkCcBm8AxqvgPa6TwA21kAsmRvACaJQjDjIAeADhSzpseQiUgBJRsxYAeepF44MbSdNaz4GAJ4AaKjoB8+gCr6AopAC8kDMgBueQ5ADeUSB4C28PgAp8AK4YRABckL72NAHIYSYAlNbOJpAAPpDmcWH0smbphu4eLGT+QaHhkdTRsQlWzlramZBYABZoiADcBZAsyIQB1FgmxRVVkPGxnR4eAObIWOa4uBS+jeadAL7g3PyCwjgExKhS8NoARsg5zkrIKohqTBr0J+cAYsRYFHpjzi6bvAK4IRYbR8VBPM7IN5ED64bQ5fQAfXMzhsxwhl062wBQkw+zER3MaBaeHheUUPGUqikDzkhOJuChMK+uWRrj+O0BTRBqDpzTwjM+pNZqN5JJZhkxRCYiCE3gh1jZVDuaPOsgwAU851wEq2UowMsguDmAVwdhY4POCrl5wAdEVfCtEpA9YgyNRkDbqGRpis4p0XbLnsgAGpRVA2a0enp9AZDXwANj9uulQmQRL5lBsvyVklFuDVGq1+hluEw0x14ADhuNpuQLDzCrT9LtxUdtWd0rdHq9PriSarTYzocq4cU6bwdt68H6g2Kif9KbH9IWS0zS4zNtm80Wyz9QA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Potential duplicate of https://github.com/microsoft/TypeScript/issues/1213

**Comment by Roaders** [comment]
Yes, that's what I want. closing. Thanks.
