### ISSUE TITLE
feature: Restrict abstract class type to non-abstract implementation

### ISSUE THREAD

**Issue by thefliik** [microsoft/TypeScript#33235]
## Search Terms

make abstract class non-abstract cast abstract class to non-abstract class remove abstract from abstract class

## Suggestion

I'd like the ability to restrict a type argument to a non-abstract implementation of an abstract class.

i.e.

```ts
export abstract class Adapter {}

export function change<T extends NonAbstract<typeof Adapter>>(
  adapterConstructor: T
): InstanceType<T> {
  return new adapterConstructor();
}
```

At the moment, typescript will correctly raise a ~ "cannot instantiate an abstract class" error if you attempt to call `new` on a variable typed as an abstract class. I'd like to restrict the variable to non-abstract classes which extend the abstract class. This would allow using `new` as well as `InstanceType<NonAbstract<T>>`.

At the moment, libraries wishing to instantiate a class extending an abstract class must forgo typing (i.e. cast to `any`) or must "fake" the abstract class by making the class non-abstract and making methods which should be abstract throw errors.

## Use Cases

I'd like to create a library with an abstract class which others must implement. I'd like the library to accept a constructor extending that abstract class as an argument, and I'd like the ability to create new instances of that constructor, all with proper typing. I'd also like the ability to declare a type which is an instance of a non-abstract class extending an abstract class (i.e. `InstanceType<NonAbstract<T>>` where `T extends typeof SomeAbstractClass`)

## Examples

```ts
abstract class Adapter {}

function change<T extends typeof Adapter>(
  adapterConstructor: NonAbstract<T>
): InstanceType<NonAbstract<T>> {
  return new adapterConstructor();
}

class MyAdapter extends Adapter {}

change(MyAdapter);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
You can achieve this already:

    export function change<T extends new () => any>(
      adapterConstructor: T
    ): InstanceType<T> {
      return new adapterConstructor();
    }

**Comment by thefliik** [comment]
@MartinJohns this is a request to restrict type `T` to non-abstract objects which extend an abstract class. `T extends new () => any` does not do that. It accepts any non-abstract constructor.

**Comment by MartinJohns** [comment]
@thefliik Whoops, my mistake. But that can also easily be achieved:

    export function change<T extends Adapter>(
        adapterConstructor: new () => T
    ): T {
        return new adapterConstructor();
    }

**Comment by thefliik** [comment]
@MartinJohns In my case, `T` extends `typeof Adapter`. Not `Adapter`. This allows both calling `new adapterConstructor()` as well as accessing static methods on adapterConstructor (more broadly, it correctly types `adapterConstructor` as `T`, rather than the less specific `new () => InstanceType<T>`).

Do you know of a way of constraining `T` to non abstract objects extending `typeof Adapter`?

**Comment by thefliik** [comment]
To provide a more concrete example: I have a [date recurrence library](https://gitlab.com/john.carroll.p/rschedule) which supports multiple javascript date implementations (i.e. Moment, Luxon, Date, etc). To do this, I export an abstract `DateAdapter` class which the library consumes. Date adapters can be made which wrap specific date implementations (e.g. `MomentDateAdapter`).

When someone uses the library, they provide a specific date adapter constructor. This constructor contains a static method `isDate()` for checking if an object is an instance of whatever date library the date adapter is wrapping (e.g. `MomentDateAdapter.isDate()` checks to see if an object is a `Moment` date).

A hypothetical function which my recurrence library exports may accept two arguments: a date adapter constructor and either a date instance or date adapter instance. This function returns a date adapter instance.

This would be the function signature

```ts
export function normalizeDateInput<T extends typeof DateAdapter>(
  adapterConstructor: T,
  date: T['date'] | InstanceType<T>,
): InstanceType<T> {
  if (adapterConstructor.isDate(date)) return new adapterConstructor(date);

  return date;
}
```

Unfortunately, in order to achieve this at the moment, `DateAdapter` must be not abstract.

**Comment by jcalz** [comment]
Hey, this looks familiar!  🙂  As I said in my [answer to your SO question](https://stackoverflow.com/a/57791735/2887218), I would give `change()` a signature like this:

```ts
declare function change<T extends Adapter>(
  adapterConstructor: typeof Adapter & (new() => T)
): T;
```

This constrains the argument to a non-abstract no-arg constructor of `Adapter` instances whose static side matches that of `Adapter` (except for the constructor).

**Comment by thefliik** [comment]
@jcalz Thank you! I had actually tried `typeof Adapter & (new () => Adapter)` before creating this issue and had received a "'DateAdapter' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'DateAdapter'" error which I couldn't shake. Your response made me try things over again.

Turns out the real problem (for me) was the type should be `typeof Adapter & (new (...args: any[]) => Adapter)`, which works as expected. The error I was receiving obfuscated this.

**Comment by danarmak** [comment]
The generic solution given [above](https://github.com/microsoft/TypeScript/issues/33235#issuecomment-527960981) has stopped working since Typescript 4.2; the compiler now produces the error `TS2511: Cannot create an instance of an abstract class`. You can see this in the example code written by @jcalz for the SO question; it works on 3.x, 4.0, 4.1 but not 4.2, 4.3: [code](http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAQQBMEwZgo4BvAWACg44B6VuACxhjBQC52AcwCWMTgFckAOkwQAtqwCyIzFAgoIAMxisAKgE8wwAMpqRlVgHcRAaxGsAYsQCKAYiucDAWlIRv4sAowN7A8pQ+eATBKN5IwJwIAG4haBgAdkLAuAZMLGDqYHAAvHAARGERcFGEQXDyCLbAcHomcKTASUSVMAZwQvi1RIB8G4DCu2UA3HlwaAgwqjMwc6pKwOIQpAAUAJR00yxy6Zq4wNK4EEKbZQASAJIt1wCiAEqPZdtTzHAAvky-jExQJBYHAtBJ0tgRBB0tVEplgAAePRwUBUdKkIhkChUKAAPk20wQ5Eo1AAwtC0hJsNB+HBesZtCRiTi4AAyOCbdLAKwc3bFXEtbZMXYML5E7FkinoKkwaDSWbzTCrdZbD7TKBrCRQGFcnniklQclHaXUqA7T7-JiHNDVBDpdIQGBGynYYiodBYeClXVMiVmj5sDjUdRQACEVrhWU2WINAfYKKgIdDtvtjsQhBEQhhyDSnrpEDgDvS3hzHuwTCtgyIpM4qia6RjLNRwHRmOZ1D2XzwVNsO07LAOFIgJzOFyuACEAOQAaWIAHVQ+9Pix-v9rTg7c6TV7C9y4DW6y3G9RzYG4BBbAhcox17DDw32zRSphI8BNgfMPXj1A4xwL1eI3vb9pAKCAwAmM9-2vF8gMfWRcB7U94ygisbyrfcICsb8URANEMV9A1+2qKUoBlaBNjAKRcAWORzigWk0hETIRX2GYJGMf1lx+VCWHkCAID7UUB2Io5h1Oc5LjKJRnhkgB5eTZOeJRFzVL5V1Q29OEwgA5TCSl3HlySwx8riQdQrHSJcrSlOAkAkGBtOAYAMWIBsoCECR5BbHcfSM78kKDRNoGTIFgGwZy4AARkQdzPO8iM7SjPzH1-BMkxYZK-V3ZyiAQWKvPSGAUA09DdJgVzsKExZlkwarFWVLTVTof4WAdcqHyy0ppWAC0NNfTYyoqlKIPjYNgqYdgAAVCmoXo4EnUCwEnOARCIeRVpQJihBWmF6WaSdBo6g1lrs+ANQARwkEQNVIHa6SMfbv0naQmCAA). I also checked locally with 4.3.5.

Is there a known issue to track this?

**Comment by jcalz** [comment]
Well, you can change `typeof Adapter` to `Pick<typeof Adapter, keyof typeof Adapter>` which discards the construct signature entirely and keeps the other static properties, although it's uglier.  Like [this](https://www.typescriptlang.org/play?ssl=10&ssc=23&pln=10&pc=65#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAQQBMEwZgo4BvAWACg44B6VuACxhjBQC52AcwCWMTgFckAOkwQAtqwCyIzFAgoIAMxisAKgE8wwAMpqRlVgHcRAaxGsAYsQCKAYiucDAWlIRv4sAowN7A8pQ+eATBKN5IwJwIAG4haBgAdkLAuAZMLGDqYHAAvHAARGERcFGEQXDyCLbAcHomcKTASUSVMAZwQvi1RIB8G4DCu2UA3HlwaAgwqjMwc6pKwOIQpAAUAJR00yxy6Zq4wNK4EEKbZQASAJIt1wCiAEqPZdtTzHAAvky-jExQJBYHAtBJ0tgRBB0tVEplgAAePRwUBUdKkIhkChUKAAPk20wQ5Eo1AAwtC0hJsNB+HAAAqqWwI3rGbQkYk4gA0cCaBjZLOAbKxJLxcAAZHBNulgFZJbtiriWtsmLsGF8idiyRT0FSYNBpLN5phVusth9plA1hIoDDpbKNSLyUcddSoDtPv8mIc0NUEOl0hAYE7KdhiKh0Fh4KU7ezNW6PmwONR1FAAIReuFZTbCnEJ9goqAp1O+-2BxCEERCGHINKRuB6uAB9LeGsR7BML2DIikziM4DpHPUFEgNEY2MivZfPBU2w7ScsA4UiAnM4XK4AIQA5ABpYgAdVT70+LH+-29OD9wZdUcbMrgPb7A451HdibgEFsCFyjHPsMfg5oUpMEzYBNgfTAmifOM8w4D8vwzf9nygaQCggMAJjfODv2AxC41kXAZ1ffMsI7H8u3vCArAA4dR0xJD52qbUoF1aBNjAKRcAWORzigWk0hETJVX2GYJGMeNjx+UiWHkCAIDnNUF0Yo5l1Oc5LjKJRni0gB5XTtOeJRD3NL5T1I39OEogA5SiSlvWVySopCriQdQrHSI8vW1OAkAkGBLOAYAMWIAcoCECR5H7G8YwcgCiKTQtoGLIFgGwQK4AARkQULwsijM-SzGKkJggsixYQq41vQKiAQbKIvSGAUDM8jrJgYLqIUxZlkwTqjRNCyzToSSvgDVqoInUodWAD0zJAzYWraoqMPzZNEqYdg6UKahejgTdULATc4BEIh5COlABKEQ6YQFHb5rGnEDp8+BLQARwkERLVIS76yMZpNwAzdpCYIA).

**Comment by sweetliquid** [comment]
It can work for me on typescript@4.6.4:

```ts
(new () => Adapter) & typeof Adapter 
```
