### ISSUE TITLE
Union of partial types: common super type of all union members is not assignable to union type

### ISSUE THREAD

**Issue by seansfkelley** [microsoft/TypeScript#33243]
**TypeScript Version:**  v3.5.1

**Search Terms:** union partial type assignable structure

**Code**

```typescript
// Data types

interface Key {
  type: "key";
  key: string;
}

interface KeyValue {
  type: "key-value";
  key: string;
  value: string;
}

type Either = Key | KeyValue;

type Common = Pick<Either, "type" | "key">;

// Test cases

// Structurally-compatible assignment
const either: PartialEither = null as any as Common;

// Type-guarding
if (either.type === "key-value") {
  either.value;
}

// Problematic type definitions

// Using this intermediate type so I can still rely on 'type' as the discriminant property of
// the PartialEither type. The naive
// Pick<Either, "type" | "key"> & Partial<Omit<Either, "type" | "key">>
// would lose the relationship between `type` and shape, causing the type guard above to fail.
type _PartialEither<T extends Either> = Pick<T, "type" | "key"> & Partial<Omit<T, "type" | "key">>;

type PartialKey = _PartialEither<Key>;
type PartialKeyValue = _PartialEither<KeyValue>;

type PartialEither = PartialKey | PartialKeyValue;

// This type seems to force the compiler to reinterpret the partial types into a slightly
// different representation that's logically equivalent but properly assignable. From:
// https://stackoverflow.com/questions/57780109/union-of-partial-types-in-typescript-cant-be-type-narrowed
type Expand<T> = T extends infer O ? { [K in keyof O]: O[K] } : never;
// Change the definition to this version to see the test cases above work.
// type PartialEither = Expand<PartialKey | PartialKeyValue>;
```

**Expected behavior:** Line 21, the structurally-compatible assignment, compiles, without a workaround. Using the `Expand` type has no effect on assignability.

**Actual behavior:** Line 21 does not compile, stating

```
Type 'Pick<Either, "key" | "type">' is not assignable to type 'PartialEither'.
  Type 'Pick<Either, "key" | "type">' is not assignable to type '_PartialEither<KeyValue>'.
    Type 'Pick<Either, "key" | "type">' is not assignable to type 'Pick<KeyValue, "key" | "type">'.
      Types of property 'type' are incompatible.
        Type '"key" | "key-value"' is not assignable to type '"key-value"'.
          Type '"key"' is not assignable to type '"key-value"'.
```

Using the `Expand` helper type workaround fixes the assignability problem.

**Playground Link:** [link](https://www.typescriptlang.org/play/#code/PTAEBEEMBdNaCeAHApgZwLAChsEsB20KATgGaQDGKoA0igqAN7ajzIoBcoARANb3cA3C1D8EXNNGIEA5sKwBfbHkIlyVWvQBqkADYBXasyytEqLn3oBaAG57DQkWIlTZ81nYOdQk6fjnYSjhYZtQAorjQABYkoAC8mgwAPok6XvLYoaAAwgD2ALb5ufjxoAAKuBS8ADwR0SQANDyh3KAplgjcAHwZWCCgACro0KAUkGjoyn1gAMpS+hTQ+sR6ughWFAVIMLgARrrU42i4Mvj5KITYm-iSoCiRMcRcZZDE0Lh6dY+l+Pq6uqBxoD8AwgXlCsVev0BuwrDJ9K8ACayPCkUAACnu9WIADosnECTwxLZ7ChuABKJgiLGPHGeQzyILYfplYi5fYofI7ChsVCgREoUgESK4YqYYL9ACqx388CiuDQoAIRGI52RMGoWTQuVAAElRpASpJcP9QMQUGtQMVQAByUI2wGK+r8hUUaT5AiGkZINmoN4MXKkZlgZ0vN4fXRfWKhHGDGKgfCQXA2FDB8qVGpR4hNbgtNpEgRdUAAMnKr3eemqAHkPdBag9Gs12K12mJul00wB3XJ-RGgXS5CZy6jm3Q7MXypCgXYoaCdlAXUAAA1CS+BfbQUUgqCaY30Mpkw951HhSMBu1yKfgOvIJpxmXYoAA+mGK5GG8RqgM7gAPIj4RFFSzIsEgqKovxzPNW0LEsy3DSsa0iCCm1QFsC06LoeimLJXwjOgGASF9ywjLNqnwrCQkfXC9HwtJDFKIj4PfbEyO0UkKIfPlqOY75QOImj6HzbjaNJKEwAGeUnUfCZOSdG9cmIDRnU2fIkBNaMdXNZUSB9Wcj22Jjj0VZUdTgNBdBOKJoDWNNkVIUgSAuEZzV0iZCHHEpohgG1FQHGRKlWBgUAAR30ZM9Cc6d9G9X0SEtI4TkTDlYwAMTZfIODTKzoCQNAOBASRKF4S81AHTscRU4BQuGUUbmAABWAB2RqAA4AAYAEY2oATmAfR8FqqxAysAy3ysUI0CsAhxvYNA3VwJBoA2L0rBnGbUCsRNiDZedEU48If22ACvxAwZf3-QClXwBziFAKtQAAfiYUAAG0aCu0R6EDO6AF0uCrN6ftABRQC4fAUBTYh5H6bIt38TV4wFIUBvea1oB1aIFVASHjjRnUZKPIhbjGCZFUgC8r27YheHvaZjzgt8s1KMJDsNRFqmEwSUk5hA6JQCigA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/18538, https://github.com/microsoft/TypeScript/issues/19927

**Comment by jack-williams** [comment]
You need `Common` to be defined using a distributive form of `Pick`, rather than the current one. 
```ts
type UnionKeys<T> = T extends any ? keyof T : never
type DistributivePick<T, K extends UnionKeys<T>> = T extends any ? Pick<T, Extract<keyof T, K>> : never;
```

See #28339.
