### ISSUE TITLE
Variables declared in array destructuring patterns can't be used in initializers of other variables in the same pattern

### ISSUE THREAD

**Issue by thorn0** [microsoft/TypeScript#33257]
**TypeScript Version:**  3.6.2

**Search Terms:** circular reference, array destructuring initializer

**Code**
```ts repro
// @strict
declare const x: number | undefined;
const [a, b = a] = [10, x];
```

**Expected behavior:** Should compile. Both `a` and `b` are of type `number`.

**Actual behavior:**
Error: `'a' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

**Playground Link:** [playground](http://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzxQFcBbAIxBngB95CVQAzASxRGAG4AoZdLAbSgAaeKXgBeeFAC64+HwCMABmHYpXIA)

**Related Issues:** #32950, #33191

**Comment by sandersn** [comment]
Pretty sure this is a design limitation of the way that Typescript checks types. It uses a simple strategy augmented by contextual typing, but that is simple too, and happens at the same time during checking every time. 

Still, it might be possible to tweak the order of checking in destructuring declarations to avoid the error.
