### ISSUE TITLE
error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'. node_modules/typeorm/repository/MongoRepository.d.ts(12,22): error TS2589: Type instantiation is excessively deep and possibly infinite. node_modules/typeorm/repository/MongoRepository.d.ts(45,5): error TS2321: Excessive stack depth comparing types '(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>) => Promise<Entity>' and '{ (id?: string | number | Date | ObjectID, options?: FindOneOptions<Entity>): Promise<Entity>; (options?: FindOneOptions<Entity>): Promise<Entity>; (conditions?: FindConditions<Entity>, options?: FindOneOptions<...>): Promise<...>; }'.

### ISSUE THREAD

**Issue by enzigma-monika-pingale** [microsoft/TypeScript#33259]
**TypeScript Version:**  3.5.3
Installed above typescript version. Work on local environment.
When we ran docker command to build project it throws above exception.
Guide us to resolve this issue ASAP.

**Comment by enzigma-ajinkya-kumbhar** [comment]
This issue is quite similar to [#29112 ](https://github.com/Microsoft/TypeScript/issues/29112)
I have tried the solutions mentioned in this...still it did not worked for me.

**Comment by enzigma-monika-pingale** [comment]
Following solution solved this issue for time being:
Added typescript as a global dependency.
For this added following commands inside docker-file.
RUN npm i -g  typescript@3.5.2 
RUN npm i -D typescript@3.5.2

**Comment by enzigma-ajinkya-kumbhar** [comment]
Worked for me too.
```
RUN npm i -g typescript@3.5.2
RUN npm i -D typescript@3.5.2
```
