### ISSUE TITLE
Exclude<T, U> type not working like it alias T extends U ? never : U

### ISSUE THREAD

**Issue by rfreydi** [microsoft/TypeScript#33258]
**TypeScript Version:**  3.5.1 and 3.6.2
**Code**

```ts
interface A {
  name: 'A';
  test: boolean;
}
interface B {
  name: 'B';
  test: boolean;
}
interface C {
  name: 'C';
}

type ABC = A | B | C;

// from the code here is how Exclude is defined
// type Exclude<T, U> = T extends U ? never : T
// -> Exclude<ABC, C> = ABC extends C ? never : ABC

function test(ab: Exclude<ABC, C>) {
  console.log(ab.name); // "A" | "B"
}

function test2(ab: ABC extends C ? never : ABC) {
  console.log(ab.name); // "A" | "C" | "B"
}
```

**Expected behavior:**
ab.name should suggest the same values
**Actual behavior:**
ab.name with the extends suggest all values (even the "excluded" C value)
**Playground Link:** 
https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgILIN4ChnJHAWwgC5kByVMgbh2UgGcxSAjAe1YBsI4QaBfLKEixEKAEKZa+IqTJjqtBk2RtO3XlgFDo8JMgDCk3NJLl9CgVjABPAA4pUYwwF40yAD7IJn-TSwB6f2QYKFYCOgALFARWABMUKKgUYHpkCNYAd2QAUQAPBA4AV3jkFOR4mFAIWICgm3sc-KL4gB4AFQAaZABVAD5kVzbkCFzIEFjU7uQAfjwIADdoZFI22uQAWn68guKIFsd9Lv1+1wPh0Yhx1MNZkAWl0gOsLBhCkAQwYFYQOghGAAo4MxSNtmnsDkdegBKIzIGIgehqAB0HFYAHNAcwkSYoVRkIFkAAiVCEjxEsSEzTPV7vT7fX6MABMmMeTnOYwmBhmc0WUGWaCcMOwuHhiK4KPRmOxhAguPxQWJpM8hP0SvJlL4QA

**Comment by jack-williams** [comment]
Duplicate of #33209.

**Comment by rfreydi** [comment]
@jack-williams Thank you figuring out the issue !
