### ISSUE TITLE
Regression: The overload getContext("experimental-webgl") was deleted a month ago

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#33255]
**TypeScript Version:**  3.6.2

**Search Terms:** WebGL, getContext, experimental-webgl, type definitions, lib.dom.d.ts

**Code**

```ts
const gl: WebGLRenderingContext = document.createElement('canvas').getContext('experimental-webgl')!;
```

**Expected behavior:**
No type errors.

**Actual behavior:**
I get a type error now:

```ts
foo.ts:1:7 - error TS2322: Type 'RenderingContext' is not assignable to type 'WebGLRenderingContext'.
  Type 'CanvasRenderingContext2D' is missing the following properties from type 'WebGLRenderingContext': drawingBufferHeight, drawingBufferWidth, activeTexture, attachShader, and 429 more.

1 const gl: WebGLRenderingContext = document.createElement('canvas').getContext('experimental-webgl')!;
        ~~
```

I discovered this because VSCode just updated. My project was working fine yesterday but now my project no longer compiles without type errors. The latest version of VSCode includes TypeScript 3.6.2, which has this error in the standard type definitions.

**Playground Link:** 
N/A (I can't reproduce on the playground)

**Related Issues:** 
This has already been reported in 2015: https://github.com/microsoft/TypeScript/issues/5773. It was fixed in 2016 here: https://github.com/microsoft/TSJS-lib-generator/pull/56. It looks like this fix was reverted by https://github.com/microsoft/TypeScript/pull/32578 a month ago.

**Comment by AviVahl** [comment]
"The experimental-webgl context is gone. Instead, use webgl or webgl2."

https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/

**Comment by evanw** [comment]
Ah, I see. Ok then I'll close this since it was intentional change.

Won't that always be necessary for older browsers though? I thought it was needed in older versions of Edge at least. It's no big deal since I can just cast to `any`. Just curious why it was removed.
