### ISSUE TITLE
typescript helper function wrong name 

### ISSUE THREAD

**Issue by dotnetautor** [microsoft/TypeScript#33269]
**TypeScript Version:** Version 3.7.0-dev.xxx, also 3.6.2

**Search Terms:** typescript helper function wrong name __decorate_1  __decorate  

**Code**

```ts
var __decorate = ( ) => { };

function d(ctor: Function) {    
}
@d
class C {
}

```

**Expected behavior:** The compiler creates the same name for the inserted helper function and the use of the helper function. (`__decorate_1`)

**Actual behavior:** If there is already a user-defined function that has by chance the same name as one of the TypeScript helper functions (like `__decorate` or `__metadata`), the ts compiler creates two different names for the declaration of the inserted helper and for the function call using the helper.  The same if there is just a variable global or in the same file declared with the same name as one of the TypeScript helper functions. (`declare var __decorate;` )

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./",
    "sourceMap": true,
    "newLine": "LF",
    "module": "esnext",
    "target": "es2017",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "jsx": "preserve",
    "lib": [
      "dom",
      "es2015",
      "es2016",
      "es2017"
    ]
  }
}
```

Result with ts compiler version 3.6.2:
```ts
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __decorate = () => { };
function d(constructor) {
}
let C = class C {
};
C = __decorate_1([
    d
], C);
```

**Comment by DanielRosenwasser** [comment]
It's weird to think about with `__decorate`, but this was done intentionally to support overriding the helpers - it's part of why we look up `this && this.__decorate`. See #1193 for an example of this.

**Comment by sandersn** [comment]
The reference `__decorate_1` at the end of the emitted code is still wrong, though.

**Comment by deregtd** [comment]
+1 on this.  We have to keep ReSub on v3.5.3 because 3.6.x blows up with this broken decorate reference issue.  If you want a super easy repro, pull the resub source (github/microsoft/resub) and update to a newer typescript, then observe the outputted javascript which will have a __decorate_1 reference with no matching function. :(
