### ISSUE TITLE
jake not compiling tsserver.js

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3326]
When I make a change (e.g. in emitter.ts or program.ts), sometimes tsserver.js is not updated. Other files (tsc.js, typescript.js, and typescriptServices.js) are.  If I delete the tsserver.js file and jake again, it will be created.

**Comment by mhegazy** [comment]
JakeFile.js does not list them as dependencies to this task. adding them should solve the issue. a PR would be appreciated.
