### ISSUE TITLE
An array of classes does not automatically detect the type

### ISSUE THREAD

**Issue by plohoj** [microsoft/TypeScript#33268]
**TypeScript Version:**  3.7.0-dev.20190905

**Search Terms:** Array of classes

**Code:**

```ts
class PerfectRunner {
    public run(): void {
        // ...
    }
}
class SimpleRunner {
    public run(): void {
        // ...
    }
}
class ExampleRunner {
    public run(): void {
        // ...
    }
}

const runners = [PerfectRunner, SimpleRunner];

runners.push(ExampleRunner);
```
I need to create a factory with some set of classes. The classes specified when creating the factory will be wrapped in some code without changing the class interface. Then, you can request from the factory an instance of the class that was specified at creation. If the factory did not receive the class constructor at creation, a type error is expected. But I met with the problem of automatically detecting the type of an array using class constructors.

**Expected behavior:**
* Variable `ranners` have type of `(typeof PerfectRunner | typeof 
 SimpleRunner)[]`
* `runners.push(ExampleRunner)` throw an exception

**Actual behavior:**
* Variable `ranners` have type of `(typeof PerfectRunner)[]`
* `runners.push(ExampleRunner)` not throw an exception

**Playground Link:** [Link](http://www.typescriptlang.org/play/#code/MYGwhgzhAEAKCmAnAZvYAXASgVwHa6WgG8Aoac6AekugDp6yKAHbAIxAEthpE8AKAJQAuaADcA9hwAmxRhQrU6DeQF8Sa0JBgBlDgFsmIeDnyFS8xfVpzoLdlx79hYyTPPyFNKzbUbwUaABRAA8wAyMTAkRZCy9lZjZObl5cQREJaRiPckt48l8SEmBxXAh0R1NEGABeaABtBBQ0LDwogBpoXXDjVqQAXQBuQpSoiFoWCAALPhCwwx7KgQGgA)

**Related Issues:** -

**Comment by AnyhowStep** [comment]
Your classes are structurally the same. So, the union type gets simplified.

The element you are trying to push is also structurally the same. So, it is permitted

**Comment by plohoj** [comment]
I understood, thanks

**Comment by AnyhowStep** [comment]
I agree it's unintuitive, though.

When you use classes, you almost assuredly want nominal typing.

It would be nice if interfaces were structurally typed but classes were nominally typed.

I'm unsure how much code this would break, though
