### ISSUE TITLE
Should commonSourceDirectory be undefined when outDir, sourceRoot, mapRoot is not specified?

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3327]
I'm writing some custom code in my fork and realize it is not populated.  If needed, I can create a pull request for it. (should be just 4 lines of change).

**Comment by mhegazy** [comment]
That is the only time it is used. if non of these options are defined, the commonSourceDirectory is not needed. what are you trying to do?

**Comment by unional** [comment]
I wrote a umd library that allow user to write code that can be used in browser global, requireJS, and commonJS as-is (i.e. without recompile, see [https://github.com/unional/write-umd]).  I use this internally so I create a fork of TypeScript to generate that (see [https://github.com/unional/TypeScript]).

The code will use `umdBaseDir` specified by the user or the `commonSourceDirectory` if `umdBaseDir` is not available.

For example, if I have a file at **C:\Users\me\codes\myProject\src\Company\app\common\MyClass.ts** and the `umdBaseDir` is specified as **C:\Users\me\codes\myProject\src\**, then the full path of MyClass will be Company.app.common.MyClass.

The `commonSourceDirectory` would work too as I specify `include` or `exclude` in the tsconfig.json to compile all files under **./src**.

**Comment by mhegazy** [comment]
looks like this is a change local to your fork then. up to you to decided what when is commonSourceDirectory needs to be evaluated.

**Comment by unional** [comment]
Ok. Thanks.

**Comment by basarat** [comment]
> see [https://github.com/unional/write-umd])

@unional I get that this is different ^ but we do have some `umd` support. See https://github.com/Microsoft/TypeScript/pull/2605 for details (and https://github.com/Microsoft/TypeScript/blob/378b5ffd1af2249658c8b7a3dc7465d911af93ff/tests/baselines/reference/umdDependencyCommentName2.js)

**Comment by unional** [comment]
Yes, I'm aware of the UMD pattern support.  The difficulty I have with the UMD pattern is that it doesn't not support browser global properly. e.g.:

You have a module under Company/app/components/compX.js which is Company.app.components.compX

You can require it by require('Company/app/components/compX'); in AMD or CommonJS.
But the code with this require will not work in environment that you loads the script files using script tags because the require method does not exist.  You can't create a global require method to fake the code and do resolution either because a lot of 3rd party library doesn't do AMD/CommonJS detection properly (i.e., they just check whether if window.require exists).

Therefore I wrote `write-umd` to solve that problem (and a much cleaner syntax IMO :P).

**Comment by unional** [comment]
And you encourage me to update the README. :)

**Comment by mhegazy** [comment]
@unional have you considered `///<amd-module name=".." />`?

**Comment by unional** [comment]
@mhegazy do you mean if I have a file `/Users/me/codes/projectx/src/Company/app/components/compX.ts` and in the file I specify `///<amd-module name="../../../"/>` then I can use that information to locate the root folder `/Users/me/codes/projectx/src`?

**Comment by mhegazy** [comment]
Possibly :)

**Comment by unional** [comment]
Currently I use `sys.getCurrentDirectory() + compilerOptions.umdBaseDir` to solve that problem (although I should consider renaming it to `umdxRootDir` where `umdx` is the monika I use in `--module umdx` so it live with the existing `umd` value).

It would be even better If I can get the path to the config file and do the right adjustments (e.g. `/Users/me/codes/projectX> tsc @app/tsconfig.json` would get the current directory as `/Users/me/codes/projectX/app`). :)
