### ISSUE TITLE
new Array(10).fill(0) transform wrong when target is ES5 ?

### ISSUE THREAD

**Issue by linxiaowu66** [microsoft/TypeScript#33277]
TypeScript Version: 3.5
Target: ES5

The following code:

new Array(10).fill(0)
translates into:

new Array(10).fill(0)
However,  in the Es5 browser, this translated syntax is can not be recognized. So this behavior is normal ?

**Comment by jcalz** [comment]
This is working as intended.  The *syntax* of `new Array(10).fill(0)` is acceptable in ES5, so it is transpiled as-is.  If your target environment doesn't support `Array.prototype.fill()`, then you should not specify the [ES2015 libraries](https://github.com/microsoft/TypeScript/blob/v3.6.2/lib/lib.es2015.core.d.ts#L53) in your config.  See [#26087](https://github.com/microsoft/TypeScript/issues/26087#issuecomment-409289653).

Also, there is a [template](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) you should fill out when creating an issue here.  Please do not ignore it; it is there for a reason.

**Comment by linxiaowu66** [comment]
@jcalz is something misunderstand in "ES5" ?  I check this syntax is supported from ES2015(ES6). [Array.fill](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/fill), Even though I set the target is "ES3". Typescript is still not transpiling.  As my code is run on the Android 5 device, if I am not applying the polyfill, this code can not run.

Thanks for your response

**Comment by kitsonk** [comment]
TypeScript is a syntax transpiler.  It does not polyfill functionality (e.g. fill in methods on built in classes).  This is explained in #26087, as mentioned.

Again, why did you ignore the issue template?
