### ISSUE TITLE
How to generate a lib.d.ts file to be used by `ts.createProgram`?

### ISSUE THREAD

**Issue by troygibb** [microsoft/TypeScript#33284]
I am trying to create a compilerHost with a trimmed down default library. For instance, I want to throw compile-time errors if a `Promise` is written. 

I came across the [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) as one possible workflow to generate type definitions, but as it says, it only generates `dom.generated.d.ts`, `webworker.generated.d.ts` and `dom.iterable.generated.d.ts`. Is there anything else out there for generating a basic, ES6 type-definition library?

A few limitations to keep in mind:
- I am running the Typescript Compiler API in the browser
- I need the type def to be written in javascript

Thanks in advance!!

**Comment by kitsonk** [comment]
Though this is a question, and this isn't the best forum to ask questions, in [Deno](https://deno.land), until recently we generated our default type library based on the run time environment code and referenced the other libs that matched our runtime environment.  We used `ts-morph` to do the manipulation of the AST.  Trying to remove dependencies from our build though, we have removed that generation functionality and are maintaining the default lib by hand, until we can restore the functionality by only having dependency on code within our repo.

**Comment by troygibb** [comment]
@kitsonk thanks for the background! It's too bad you have to maintain these typedefs by hand, although I guess they won't have to be changed very often. `ts-morph` looks neat, although I've found the Typescript compiler API fairly approachable. Maybe `ts-morph` was written before things got better?

I'll have to check out Deno! Sounds relevant to what I'm trying to accomplish. 

On a side note, where do you suggest I post this question?
