### ISSUE TITLE
Global completion / Auto import for JavaScript symbols from modules without typings included.

### ISSUE THREAD

**Issue by g3offrey** [microsoft/TypeScript#33289]
## Search Terms
"auto import",  "completion", "auto import global", "auto import cache"

## Suggestion

Hi, first of all good job for your awesome work.

My suggestion is simple : 
When the completion is triggered, we filter the results to exclude the ones that are not importable. As you can see in https://github.com/microsoft/TypeScript/blob/3c4276076595446ddefd24e16d549e1323a3ed8a/src/services/codefixes/importFixes.ts#L610
However in some cases we want symbols that are not directly importable.
For example, if a JavaScript dependency doesn't include a `.d.ts` file, and there is one available in the TypeScript cache folder (downloaded by VSCode Automatic Type Acquisition).

I think this would fix a lot of users issues.
For example : https://github.com/microsoft/TypeScript/issues/29039

## Use Cases
This would permit, to auto import the symbols from a JavaScript package that does not include a `.d.ts` in his sources.
For example : `react-redux`, `lodash`.

## Examples

I commented the code inside `isImportablePath` to have a hacky prototype.
This looks like this : 
![Kapture 2019-09-06 at 23 03 55](https://user-images.githubusercontent.com/11151445/64460457-b6df4e00-d0fa-11e9-9c23-b5c169c392e4.gif)
But a better version would be this (I simply copied the d.ts from the global cache to the `node_modules`) : 
![Kapture 2019-09-06 at 23 10 50](https://user-images.githubusercontent.com/11151445/64460769-9c59a480-d0fb-11e9-8c1d-39e18fd5ef3a.gif)
Today it looks like this (you can reproduce it creating a JavaScript project and installing react-redux) :
![Kapture 2019-09-06 at 23 07 06](https://user-images.githubusercontent.com/11151445/64460609-189fb800-d0fb-11e9-99a5-2e27b4fb52d5.gif)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by g3offrey** [comment]
Yes I suppose, I wasn't sure if it was done on purpose or not. 😄 
If you need help to fix this, don't hesitate to contact me. 👍

**Comment by smx-smx** [comment]
I'm not sure if this is the same issue, but i'll write here to avoid duplicates.

I'm having the same issue with `inversify`, where i want to write

```typescript
new ContainerModule(...)
```
but the symbol "ContainerModule" cannot be found and there is 'No code actions available'

I wasn't sure if this had to do with me originally using `yarn`, but i can repro this with `npm` too

Repro steps

1. `npm init`
2. `npm install --save inversify`
3. Create a new file: `test.ts`
4. Write `new ContainerModule` and ask for completion
5. Notice `No code actions available`

Can repro on VSCode-Insiders

Notice tho that `inversify` *DOES* have typings

```  "types": "./dts/inversify.d.ts",```
leading to
```typescript
export { AsyncContainerModule, ContainerModule } from "./container/container_module";
```

Interestingly, if i open `./dts/inversify.d.ts` in the same workspace, then VSCode will suggest me to import the `inversify` module

If this is related to an on-demand "lazy" loading mechanism, is there a way to bypass it and force tsserver to parse everything in `node_modules`?

Thank You

**Comment by andrewbranch** [comment]
@smx-smx that’s likely an instance of https://github.com/microsoft/TypeScript/issues/28773, which is expected behavior. Once you use it once somewhere in your program, you’ll get auto-imports everywhere, even in other files.

![Kapture 2019-09-16 at 12 18 26](https://user-images.githubusercontent.com/3277153/64986571-259b7480-d87c-11e9-89fc-357a61118fef.gif)

**Comment by smx-smx** [comment]
Thank you @andrewbranch. I sent a follow-up there
