### ISSUE TITLE
Loose file settings are not communicted to Script LS as expected

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3328]
As a result, I get an error whenever I try to for-of over an array.

![image](https://cloud.githubusercontent.com/assets/972891/7921280/4ccd3b26-0859-11e5-90d0-6c12e6fcee3c.png)

![image](https://cloud.githubusercontent.com/assets/972891/7921261/281ed8d4-0859-11e5-9ba5-32b202a6fe02.png)

**Comment by DanielRosenwasser** [comment]
Repro:

```TypeScript
let arr = [1, 2, 3];
for (let v of arr) {
}
```

**Comment by paulvanbrenk** [comment]
@DanielRosenwasser That actually works for ES3, ES5, and ES6.

This is a better example:
````TypeScript
for (var i of 'string') { }
````

**Comment by DanielRosenwasser** [comment]
I'm not sure how that's better. My settings are to use ES6, and we have an error message that communicates that we're not using the ES6 library. That's the bug I'm reporting.

**Comment by DanielRosenwasser** [comment]
Oh, I see, you mean just to confirm whether it's isolated to using an alternate library. Is it?

**Comment by paulvanbrenk** [comment]
The example you posted works in ES3, so it won't report the error even when we don't use the ES6 library.

**Comment by paulvanbrenk** [comment]
Fixed for VS 2015 RTM
