### ISSUE TITLE
Function type error in union type

### ISSUE THREAD

**Issue by joeskeen** [Microsoft/TypeScript#3329]
I have been having issues with union types when using a function type as the second type in the union.

According to the TypeScript 1.4 Language Specification: (3.4 Union Types, page 29)
* A | B is equivalent to B | A

The following example compiles correctly:
```typescript
function test(x: (y) => boolean | boolean) {
	//do something with x
}
```

But this one gives an error:
```typescript
function test(x: boolean | (y) => boolean) {
	//do something with x
}
```

**Comment by RyanCavanaugh** [comment]
The language in the spec is a specification of type system behavior, not grammar.

You can fix this with parens:
```ts
function test2(x: boolean | ((y) => boolean)) {
    //do something with x
}
```

**Comment by joeskeen** [comment]
Perfect, thanks

**Comment by btesser-r7** [comment]
```
function test(x: (y) => boolean | boolean) {
    //do something with x
}
```
looks like what you are trying to accomplish is this:
```
function test(x: (y) => (boolean | boolean)) {
    //do something with x
}
```
