### ISSUE TITLE
SetOf operator for TypeScript

### ISSUE THREAD

**Issue by splincode** [microsoft/TypeScript#33297]
## Search Terms

A set is a collection of elements of same type. Allows defining the set data type. The elements in a set are called its members. In mathematics, sets are represented by enclosing the members within braces{}. 

```ts
type Int = set of -32768..32767;
type Byte = set of 0..255;
type Word = set of 0..65535;
// ...
```

## Use Cases

If the backend supported data type is only `int`

```ts
type Int = set of -32768..32767;

class Model {
  fieldId: int;
  value: string;
}

const model = new Model();

function SizeOfCast(val: number): Int {
  if (val >= setOf(Int).start && setOf(Int).end <= val) {
    return val is Int;
  } else {
    throw new Error('val not integer');
 }

  return val;
}

fromEvent(element, 'input').subscribe((val: string) => {
  mode.fieldId = Number(val); // type error
  mode.fieldId = SizeOfCast(Number(val)); // no error, runtime check size of (-32768..32767)
})



```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by splincode** [comment]
https://github.com/microsoft/TypeScript/issues/15480

**Comment by MartinJohns** [comment]
> [x] This could be implemented without emitting different JS based on the types of the expressions

I'm pretty sure your suggestion of the `setOf(Int)` violates this.
