### ISSUE TITLE
No index signature error

### ISSUE THREAD

**Issue by webcoderkz** [microsoft/TypeScript#33307]
I asked this question on SO: https://stackoverflow.com/questions/57672886/using-global-filters-in-vue-with-typescript

But, 13 days have passed and nobody has the answer for my question, therefore i'm asking for a help here.

**Comment by AnyhowStep** [comment]
Have you tried Gitter?
https://gitter.im/Microsoft/TypeScript

**Comment by webcoderkz** [comment]
@AnyhowStep would try, thanks. So it's impossible to use `Object.keys()` with indexes?

**Comment by AnyhowStep** [comment]
If you are absolutely sure `Object.keys()` will return `(keyof T)[]`, then you can use this,
```ts
Object.keys(filters) as (keyof typeof filters)[]
```

Be aware that it might be fine in specific cases but is unsafe in general.

-----

```ts
interface Foo {
    x : string
}

const obj = { x : "hi", y : "bye" };
const foo : Foo = obj;

//Are you expecting `["x"]` ?
const keys = Object.keys(foo);

//Prints `["x", "y"]`, not `["x"]`
console.log(keys);
```
[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIAeyAXMgM5hSgDmuAvrrguiFcugEYBWyAvDmJlkAIgAWwUQBpkATxGiuciKOQMA3CzYcYmERiyDuPLbgD05gIJQUc9AFdkEIgAcICMHWQADANqiRKIAuj7IAPza7GDIANYQchQCyADyvB5gAHTxiQAUeugAlGaWAAo04En+gTJiciE+siDoMdVBoVEU6AA2EJnd6LS5ORTFQA)
