### ISSUE TITLE
What ECMAScript version and module system settings should be used with VS2019?

### ISSUE THREAD

**Issue by AaronLS** [microsoft/TypeScript#33301]
Can we get some documentation on what currently works with documented tutorials for "ECMAScript version" and "Module system" settings in project properties?

There's 7 "ECMAScript version" options in VS 2019 and 5 Module System options, making for 35 combinations.  I have spent hours every night trying different combinations, going through tutorials on docs.microsoft, for 2 weeks and have yet to get a single tutorial to compile successfully.  None of them specify what these settings should be set to.

Some of the errors I get, I look up and they say it is related to CommonJS, so I switch to a different Module System settings, but then none of my import statements can find modules, and the tutorials don't explain what import is actually doing.  I have the modules under node_modules, but there's no indication in errors as to where it's exactly looking or what it's looking for or why the behavior varies between the module systems.

It would take out alot of the guess work to specify at the beginning of a tutorial what settings should be used for these.

**Comment by fatcerberus** [comment]
> None of them specify what these settings should be set to.

That’s because what these should be set to depends on what environment you’re targeting, how old the browser/Node version is, etc.  There’s no one-size-fits-all setting for these, it entirely depends on your use case.

I *can* at least tell you that Node should always use `commonjs` for module type though, at least for the foreseeable future.

**Comment by fatcerberus** [comment]
To be clear: the `module` and `target` settings only affect what tsc produces as *output*, so if it’s failing to find imports at compile time, changing these settings is not likely to help.

**Comment by ilogico** [comment]
> so I switch to a different Module System settings, but then none of my import statements can find modules
When you use `commonjs` the default `moduleResolution` is `node`, but for other `module`, the default is `classic`.
https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies

**Comment by AaronLS** [comment]
> > None of them specify what these settings should be set to.
> 
> That’s because what these should be set to depends on what environment you’re targeting, how old the browser/Node version is, etc. There’s no one-size-fits-all setting for these, it entirely depends on your use case.
> 
> I _can_ at least tell you that Node should always use `commonjs` for module type though, at least for the foreseeable future.

In the context of a tutorial, those variables should be scoped for simplicity.  Trying to handle all those possible combinations is a pretty advanced topic.  That's not necessary for a tutorial.  Tutorials should be scoped to maximize chance of success.
