### ISSUE TITLE
Pick of enum keys

### ISSUE THREAD

**Issue by codercodingthecode** [microsoft/TypeScript#33308]
I came across a functionality I needed and I couldn't really find a solution out there. 
Interfaces have an easy Pick functionality. However, enums and types don't

This is what I had to do to Pick the keys out of an enum. [Which I used in a select/dropdown]
It would be nice to have a pick like that build in.

perhaps something like this:
```typescript
enum KeysToBePickedFrom {
    KEY_ONE = "Key One",
    KEY_TWO = "Key Number Two",
    KEY_THREE = "Another key n. 3",
    LAST_KEY= "Here is the last Key"
}

// desired pick functionality
interface Picked {
    y: Pick<keyof KeysToBePickedFrom, 'KEY_ONE', 'LAST_KEY'>
}

const z: Picked = {
    y: "KEY_ONE"     //  KEY_ONE | LAST_KEY
}
```

current workaround implementation:
```typescript
enum KeysToBePickedFrom {
    KEY_ONE = "Key One",
    KEY_TWO = "Key Number Two",
    KEY_THREE = "Another key n. 3",
    LAST_KEY= "Here is the last Key"
}

type KeysOfEnum_KeysToBePickedFrom = {[key in keyof typeof KeysToBePickedFrom]: string }

type Picked_KeysOfEnum = Pick<KeysOfEnum_KeysToBePickedFrom, 'KEY_ONE' | 'LAST_KEY' >

interface KeysPickedForType {
    keyone: Picked_KeysOfEnum
}

const picks: KeysPickedForType = {
    keyone: "KEY_ONE"   //  KEY_ONE | LAST_KEY
}
```

Anyone with a better approach or a point to a built-in functionality in the docs?
Thoughts?

**Comment by AnyhowStep** [comment]
Your workaround does not do what you think it does

**Comment by codercodingthecode** [comment]
@AnyhowStep , it does exactly what I think it does and does exactly what I need it to do with providing me with propper types on that property according to whatever enums I throw on my select/dropdown component with a reverse mapping on the parent enum

**Comment by AnyhowStep** [comment]
Your workaround does not do what you think it does.

![image](https://user-images.githubusercontent.com/5655961/64505697-c6010000-d2a2-11e9-8a01-329ff136ffb6.png)

-----

This is closer to what you want,

```ts
enum KeysToBePickedFrom {
    KEY_ONE = "Key One",
    KEY_TWO = "Key Number Two",
    KEY_THREE = "Another key n. 3",
    LAST_KEY= "Here is the last Key"
}

type PickKey<T, K extends keyof T> = Extract<keyof T, K>;

type Picked_KeysOfEnum = PickKey<typeof KeysToBePickedFrom, 'KEY_ONE' | 'LAST_KEY' >

interface KeysPickedForType {
    keyone: Picked_KeysOfEnum
}

const picks: KeysPickedForType = {
    keyone: "KEY_ONE"   //  KEY_ONE | LAST_KEY
}
```
[Playground](http://www.typescriptlang.org/play/#code/KYOwrgtgBA0sCeBnAKgewELAAoEsDGA1sACYBiATqtAN4BQUDsAogJoD6A8gHJNQC8UAERx4UDiGCCANPUYxWbZAHUO-ISKhdIAI2DkoyAO6ppshvPbIAEgCUmvAYICCIVABcAFnqhFRIAHRQAMymjFAAMk4AyshsFo5WesBQOIhQnskANgCGiG6wCIK0AL60tG7wAA7JuIQiADzIUrBQwAAebqDEab6oAGYGAHxqTB3k2Xhu9b0DTbCDANxlFdVQtUTEcQiIHH1M4NAC6w0rwP0FSGiY6yQUVM0A5BacPA9QAD5QD5ExcaxvgzKOBAnXIfQmyREiBuZFQ5GQVWSdDCvQkAC41vgNlskLt9pASmU8KgQHkoJUsYgMVCYaQ4QjVgJkYxUcAMcIFNwmIJGAB6XnmTk8D4RaKxCwlIA)

And the result,

![image](https://user-images.githubusercontent.com/5655961/64505795-19734e00-d2a3-11e9-9428-617a43f696db.png)

**Comment by korniychuk** [comment]
It looks like I found a kind of solution.

```typescript
export enum ECandleTimeFrame {
  S1  = 'S1',
  S3  = 'S3',
  S5  = 'S5',
  S15 = 'S15',
  S30 = 'S30',
  S45 = 'S45',

  M1  = 'M1',
  M3  = 'M3',
  M5  = 'M5',
  M7  = 'M7',
  M15 = 'M15',
  M30 = 'M30',
  M45 = 'M45',

  H1  = 'H1',
  H2  = 'H2',
  H3  = 'H3',
  H4  = 'H4',
  H6  = 'H6',
  H12 = 'H12',

  D1  = 'D1',
  W1  = 'W1',
  N1  = 'N1', /* Month 1 */
  Y1  = 'Y1',
}

export const EKunaCandleTimeFrame
  = _.pick(ECandleTimeFrame, ['M1', 'M5', 'M15', 'M30', 'H1', 'H2', 'H4', 'H6', 'D1', 'W1']);

export type EKunaCandleTimeFrame = keyof typeof EKunaCandleTimeFrame;

const a: EKunaCandleTimeFrame = EKunaCandleTimeFrame.M1; // valid
const b: EKunaCandleTimeFrame = ECandleTimeFrame.M1;     // valid
const c: EKunaCandleTimeFrame = ECandleTimeFrame.S1;     // error
```

[StackBlitz Live Demo](https://stackblitz.com/edit/typescript-slice-enum-demo?file=index.ts)

**Comment by alexfoxgill** [comment]
you'll want the values instead:

```typescript
type ValuesOf<T> = T[keyof T]
export type EKunaCandleTimeFrame = ValuesOf<typeof EKunaCandleTimeFrame>
```

**Comment by Rejke** [comment]
For me, better approach was:
```ts
type PickEnum<T, K extends T> = {
  [P in keyof K]: P extends K ? P : never;
};
```

Use case:
```ts
export type HttpInformationalStatus = PickEnum<
  HttpStatus,
  | HttpStatus.CONTINUE
  | HttpStatus.SWITCHING_PROTOCOLS
  | HttpStatus.PROCESSING
  | HttpStatus.EARLYHINTS
>;

const informationalStatus: HttpInformationalStatus = HttpStatus.CONTINUE; // OK
const badInformationalStatus: HttpInformationalStatus = HttpStatus.CREATED; // ERROR
```

**Comment by mattgstevens** [comment]
The above is nice, and behaves the same as utility type [Extract](https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union) which has been available since Typescript v2.8

```js
export type HttpInformationalStatus = Extract<
  HttpStatus,
  | HttpStatus.CONTINUE
  | HttpStatus.SWITCHING_PROTOCOLS
  | HttpStatus.PROCESSING
  | HttpStatus.EARLYHINTS
>;

const informationalStatus: HttpInformationalStatus = HttpStatus.CONTINUE; // OK
const badInformationalStatus: HttpInformationalStatus = HttpStatus.CREATED; // ERROR
```

https://www.typescriptlang.org/play?#code/KYOwrgtgBAEgLnADgZTgQzmAzlA3gKCigGEB5AOQBUBJcgVQFEAaQqZAdWsuJloHEA+gAUASqUqkyAGWQsioyQ2TJ+cqAwCCIqQE1eVWfgC++fHACeiYLASJqIAGYB7AE4QMASycg0AG1QY2FAAvOoAHnAuaADGcAA8rPBIAZhYagA+NsnoqQB0ZFS0jKyZSSg52LkcXDz8wmIS0sglWeWBWLkKxEoq5HwtZSmVmtp6tJTNAHwA3KbR3lhwUB6Oru5wXj7+FVgAXK32zm6e3n5DOKGDO-kUNPQM01AA9E9QpADS+PMgi1AARmgACaHNYnLbnfZlEHHDanbbtEKtc75ESaSgMAAijxe6hEYhEQA0

**Comment by jfcere** [comment]
If it can help anyone, using [Extract<Type, Union>](https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union) was enough to get a new type with picked enum values

```typescript
enum Key {
  KEY_ONE = 'Key One',
  KEY_TWO = 'Key Two',
  KEY_THREE = 'Key Three',
  LAST_KEY = 'Last Key',
}

export type Picked = Extract<
  Key,
  | Key.KEY_ONE
  | Key.LAST_KEY
>;

const goodPickedKey: Picked = Key.KEY_ONE; // OK
const badPickedKey: Picked = Key.KEY_TWO; // ERROR
```

**Comment by ulayab** [comment]
Is this one of a simple approach to use `Pick` in enum ?
```ts
enum KeysToBePickedFrom {
  KEY_ONE = "Key One",
  KEY_TWO = "Key Number Two",
  KEY_THREE = "Another key n. 3",
  LAST_KEY= "Here is the last Key"
}

type KeysToBePicked = typeof KeysToBePickedFrom

interface Picked {
  y: keyof Pick<KeysToBePicked, 'KEY_ONE' |'LAST_KEY'>
}

const z: Picked = {
  y: 'KEY_ONE'   //  KEY_ONE | LAST_KEY
}
```

**Comment by obouchari** [comment]
> ```ts
> type PickEnum<T, K extends T> = {
>   [P in keyof K]: P extends K ? P : never;
> };
> ```

What is the advantage of this over just doing:
```ts
export type HttpInformationalStatus = 
  | HttpStatus.CONTINUE
  | HttpStatus.SWITCHING_PROTOCOLS
  | HttpStatus.PROCESSING
  | HttpStatus.EARLYHINTS;
```

**Comment by VictorIstrati** [comment]
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import {
    ProjectActivityFilterInterface
} from 'app/modules/statistics/project-activity/project-activity-filter.interface';
import { BehaviorSubject, Observable } from 'rxjs';
import {
    ProjectActivityInterface
} from 'app/modules/statistics/project-activity/project-activity.interface';
import { HttpParamsBuilderService } from 'app/shared/services/searchers/http-params-builder.service';
import { environment } from 'environments/environment';
import { map, tap } from 'rxjs/operators';
import { ResponseInterface } from 'app/interfaces/responses';

@Injectable({
    providedIn: 'root'
})
export class ProjectActivityService {
    private counts: BehaviorSubject<ProjectActivityInterface | null> = new BehaviorSubject<ProjectActivityInterface | null>(null);

    public counts$ = this.counts.asObservable();
    public series$ = this.counts$.pipe(map(counts => counts.series ?? []));

    public constructor(
        private readonly httpClient: HttpClient,
        private readonly httpParamsBuilder: HttpParamsBuilderService
    ) {
    }

    public get(filter?: ProjectActivityFilterInterface): Observable<ProjectActivityInterface> {
        const url = `${environment.apiUrl}admin/statistics/project-activities`;
        const params = filter ? this.httpParamsBuilder.build(filter) : null;

        return this.httpClient.get(url, {params})
            .pipe(
                map((response: ResponseInterface<ProjectActivityInterface>) => (response.data)),
                tap((counts: ProjectActivityInterface) => this.counts.next(counts))
            );
    }
}

fix angular service
