### ISSUE TITLE
An import type in jsdoc should apply to an imported commonjs module

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33333]
From https://stackoverflow.com/questions/57845741/vscode-intellisense-from-files-loaded-with-a-wrapped-require

**TypeScript Version:**  3.7.0-dev.20190907

**Search Terms:**
- jsdoc
- types
- commonjs node

**Code**
For the javascript project:

`main.js`
```js
// @ts-check 
/** @type {import('./foo')} */ const foo = require("./foo");
foo.
```

`foo.js`
```js
module.exports = {
    bar: "asdf",
    baz(num) {
        return num * 2;
    }
}
```

**Expected behavior:**
We should be able to use `/** @type {import('./foo')} */ ` to give `foo` an explicit type. `foo` has the correct type if you remove the `@type` jsdoc comment

**Actual behavior:**
`foo` is `any`. I can't figure out any way to get `foo` to have the correct type using jsdoc comments. See [this question](https://stackoverflow.com/questions/57845741/vscode-intellisense-from-files-loaded-with-a-wrapped-require) for why this is needed

The code in `main.js` works if `foo.js` is converted to an es6 module:

```js
export const bar = "asdf";
export function baz(num) {
    return num * 2;
}
```

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
This probably doesn't work because module.exports doesn't construct a real alias.

**Comment by sandersn** [comment]
This is working in 3.8.
