### ISSUE TITLE
Required definition files create busy work for package maintainers

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/TypeScript#33334]
https://github.com/jcoreio/material-ui-popup-state/issues/12
A user claims that I just need to add this `index.d.ts` to support TS:
```ts
declare module 'material-ui-popup-state';
```
If this is all it takes then there's absolutely no excuse for TS not just doing the same thing if no `.d.ts` is present.
I don't care if this is a duplicate issue because I consider this an unnecessary waste of time that TS has caused me.  Be more considerate of your impacts on the ecosystem.

**Comment by weswigham** [comment]
The user is wrong. The above declaration is effectively an assertion to allow an untyped import - it should never be present in the package itself. I'd just ask the user to contribute a _real_ type definition file for the module (based on it's actual API and documentation) to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by jedwards1211** [comment]
Gotcha, thanks, it did seem surprising.
