### ISSUE TITLE
`tsc` will check typescript files which imported in d.ts file

### ISSUE THREAD

**Issue by Aqours** [microsoft/TypeScript#33342]
**TypeScript Version:**  3.6.2

**Search Terms:** tsconfig extends or tsc

**Code**

https://github.com/Charming-Imperfect/crazy-tsc/blob/master/types.d.ts#L1-L3

**Reproduce:**

1. `git clone https://github.com/Charming-Imperfect/crazy-tsc.git`
2. `cd crazy-tsc/strict-all && npm i`
3. `npm test`

**Expected behavior:**

NO errors.

**Actual behavior:**

Output errors.

```txt
../strict-non/index.ts:8:18 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

8         this.log(this.num);
                   ~~~~~~~~


Found 1 error.
```

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
All the files in the program are checked.. The program doesn't just include files listed in tsconfig.json but also modules resolved and hence the behavior..

**Comment by Aqours** [comment]
In my case, I want to share the type of `NonStrict` via global namespace and just use `./strict-non/index.ts` as types(not as modules) in d.ts file, so I do not need check its types, which maybe look like `skipLibCheck: true` to skip these files in d.ts file.

How to deal with different tsconfig.json in my case if you think tsc perform right behavior?
