### ISSUE TITLE
disallow abstract property declaration with value in class

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#33356]
## Suggestion

```ts
abstract class C {
    abstract method () :Type;// valid
    abstract property :Type;// valid
    abstract property :Type = value; // this should be invalid, because it doesn't make sense
}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Breaking changeness aside, I don't see by what logic we would disallow it. TS should always let you write
```ts
this.property = value;
```
in a method body. Disallowing you from using the sugar to do that in the constructor body would be entirely arbitrary

**Comment by LongTengDao** [comment]
@RyanCavanaugh abstract property assignment will always be overriden by sub class

**Comment by RyanCavanaugh** [comment]
A child class can have a bare property declaration without an initializer, thus falling back to the parent value.

Either way, we're not interested in taking a breaking change here.

**Comment by LongTengDao** [comment]
@RyanCavanaugh I see. There is difference between ECMAScript class proposal and TypeScript. In latest proposal, property declaration is define not set, and bare property declaration is equal to `= undefined`. Now that it's still a proposal, so the breaking problem may be handled together util the proposal be standard.
