### ISSUE TITLE
Mark class elements with "declare" to mark externally implemented methods

### ISSUE THREAD

**Issue by Ginden** [microsoft/TypeScript#33351]
## Search Terms

"TS2391", "Function implementation is missing", "typescript extern"

## Suggestion

Marking method with "extern" keyword should supress TS2391 error.

## Use Cases

Converting JS code with extensive use of mixins.

## Examples

```
function mix(klass)  {
   klass.prototype.bar = () => 42;
}
class Foo {
    extern bar(): number;
}
mix(Foo);

(new Foo).bar();
````

Another possible syntax is to use `declare` instead of `extern` (it's an error - `'declare' modifier cannot appear on a class element.`, so it won't break any code).

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). - hard to tell.

**Comment by fatcerberus** [comment]
```ts
declare function externalFoo(x: string);
externalFoo("fooey");  // no error, error at runtime if it doesn't actually exist
```

**Comment by Ginden** [comment]
@fatcerberus  Can I use `declare` with class methods?

**Comment by ilogico** [comment]
You can augment the interface.
```ts
class Foo {
}
interface Foo {
  bar(): number;
}
const x: number = new Foo().bar();
```

**Comment by RyanCavanaugh** [comment]
Already possible using existing syntax; this doesn't seem to come up often enough to warrant an extra way to do it. Marking a question for now.
