### ISSUE TITLE
checkJs: ts-nocheck won't turn off checking

### ISSUE THREAD

**Issue by Hotell** [microsoft/TypeScript#33359]
**TypeScript Version:**  3.6.2

**Search Terms:** checkJS, nocheck

Let's say I have following module structure 

```
root.js -> import {one} from './one'
 - one.js   -> export function one()
   - two.js  -> export function two()
     - three.js -> export function three()
```
> root imports `one` function  from `one.js`, 
>
>`one` uses `two` from `two.js` 
>
>and `two` uses `three` from `three.js`.

- three.js includes not type correct code

If `checkJs: true` is used and I wanna skip checking for three.js by providing `@ts-nocheck` to `two.js` typescript will still check whole path.

I need to add `// @ts-nocheck` to `three.js` ( this is quite tedious if, if let's say two.js would import dozens of modules, and we wanna turn checking off for that as we are in process of migration etc...)

**Expected behavior:**

adding `@ts-nocheck` to two.js should be sufficient to turn off type-checking in all dependant modules

**Actual behavior:**

module with type erorrs is still checked (three.js) when `nocheck` is used within parent.

**Demo:** 

https://codesandbox.io/embed/hopeful-night-tg3jy
- you need to download, install deps and run `npm run check-js`

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/24133, https://github.com/microsoft/TypeScript/issues/26887

**Comment by weswigham** [comment]
`//@ts-check` and `//@ts-nocheck` only toggle the file they're in - that's how they're intended to work.
