### ISSUE TITLE
Is there a list or library of this rule no-restricted-globals?

### ISSUE THREAD

**Issue by zytjs** [microsoft/TypeScript#33368]
## Search Terms

no-restricted-globals

## Use Cases

I want to use the eslint rule no-restricted-globals, but it accept a list of which variables you want to warning when you use. But there are many global variables, so i want to know, is there a list or library about this rule?

## Examples

such as some global variables, status, screen, screenX, and so on. You should be warned when you use directly.

sorry for my poor english

**Comment by RyanCavanaugh** [comment]
We don't maintain eslint and TypeScript isn't in a better position to answer this question than anyone else. Please ask questions elsewhere; this is a bug tracker, not a support forum.
