### ISSUE TITLE
'extract to function' for variable that is assigned in switch

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33362]
**TypeScript Version:**  typescript@3.7.0-dev.20190910

**Search Terms:**
- refactor
- extract

**Code**

```ts
let value: string;
switch (Date.now()) {
    case 1:
        value = 'one';
        break;
    default:
        value = 'other';
        break;
}

console.log(value);
```

Select everything from `let value` to the end of the switch statement

**Expected behavior:**
A refactoring for `extract to function` is offered. It should change the code to something like:

```ts
let value = newFunction();

console.log(value);

function newFunction() {
    let value: string;
    switch (Date.now()) {
        case 1:
            value = 'one';
            break;
        default:
            value = 'other';
            break;
    }
    return value;
}
```

**Actual behavior:**
No refactoring offered

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
