### ISSUE TITLE
Return types shouldn't be overshadowed by parameters for type parameter inference

### ISSUE THREAD

**Issue by Validark** [microsoft/TypeScript#33365]
**TypeScript Version:**  3.7.0-dev.20190905

**Search Terms:** return type type parameter inference infer generic overshadow parameter overshadows return type inference

**Code**

```ts
declare function Mutate<T>(callback: (a: T, b: number) => T): T;
Mutate((a, b) => b);
```
**Expected behavior:** assume `T` is `typeof b`, which is `number`

**Actual behavior:** `T` defaults to `unknown`

Another interesting thing about this example is that if you pay attention to the TS tooling, it detects `T` as `number` when you first type `=> b`. However, once it re-evaluates the entire statement it thinks `T` is `unknown`. I don't know the inner workings of TS, but I *guess* that when I typed `=> b` TS was waiting for me to make a better indication of what `T` is, or the Mutate call was already partially evaluated and TS picked up where it left off and this was a side effect of that.

![](https://user-images.githubusercontent.com/15217173/64661729-70943280-d40b-11e9-8a33-611900593002.gif)

**Playground Link:**  https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFlkMoMQAeAFQD4AKMKCCAIyjAGsAueWqbygDTxm3VMgC2zEDACU8ALzV4lGfwDcAKCIkytXkOZzFwmWqA

**Related Issues:**  https://github.com/microsoft/TypeScript/issues/14829 is similar, but I don't *necessarily* need a `NoInfer<>` generic

In fact, I posted it in a comment as well: https://github.com/microsoft/TypeScript/issues/14829#issuecomment-530189002. Feel free to delete/close whichever is more appropriate.

**Comment by RyanCavanaugh** [comment]
This is intentional - consider what any possible implementation of `Mutate` would look like:
```ts
function Mutate<T>(callback: (a: T, b: number) => T): T {
    return callback("????", 10);
    //              ~~~~~~
}
```
It's impossible absent other `T` candidates for `Mutate` to provide a valid value for `a`, so the correct bound is `unknown`.
