### ISSUE TITLE
completions for string literals don't follow quoteStyle preference

### ISSUE THREAD

**Issue by Worlor** [microsoft/TypeScript#33377]
*Template Info added by @mjbvz*

**TS Version**: 3.7.0-dev.20190910

**Search terms**
- intellisense
- suggest, suggestions
- quote
- quoteStyle

*Original report*

---

Steps to Reproduce:

1. In settings, set : "typescript.preferences.quoteStyle": "single"
2. Create a file like this : 

````typescript
export enum E {
    VALID, INVALID
}

export interface a {
    test: keyof typeof E;
}

const a: a = {
    // should suggest with simple quote
    test: 
}
````

3. Focus after 'test:' and launch suggestions with <kbd>Ctrl</kbd>+<kbd>Space</kbd>
4. Choose first

Does this issue occur when all extensions are disabled?: Yes

Is there a way to autocomplete this with single quotes ? I haven't found any settings of this kind, except quoteStyle preferences.
![Paramètres - Visual Studio Code 11_09_2019 15_49_24](https://user-images.githubusercontent.com/3814031/64703097-11d2c580-d4ac-11e9-855c-290bae0896de.gif)

**Comment by jessetrinity** [comment]
Adding on [feedback from Visual Studio](https://developercommunity.visualstudio.com/idea/596913/typescript-string-character.html).

related: we have [other inconsistencies](https://github.com/microsoft/TypeScript/issues/29881) in quote style / completion.

**Comment by sam-s4s** [comment]
Thanks @jessetrinity :D

Yes, I'm hoping for a fix for this one, we run single quotes only (linted).

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
