### ISSUE TITLE
TypeScript strict mode does not ignore node_modules folder 

### ISSUE THREAD

**Issue by vinodkpasi** [microsoft/TypeScript#33376]
I have written test script using third party npm libraray which is located under node_modules folder. I want to perform strict mode check for written test script but TypeScript validating test script as well as validating used third party npm library.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
