### ISSUE TITLE
JS Doc parameter comment description drops leading star

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33386]
From https://github.com/microsoft/vscode/issues/80082

**TypeScript Version:**  3.7.0-dev.20190911

**Search Terms:**
- jsdoc
- documentation
- quickinfo \ hover

**Code**
For the following code

```ts
/** yadayada
 * @param {number} var    **This highliting doesn't work**
 * @param {string} var2   But**This works!**
*/
const documented_function = () => {}

documented_function();
```
1. Hover over `documented_function`

**Expected behavior:**
The documentation for var is returned as `**This highliting doesn't work**`

**Actual behavior:**
The leading star of the description is dropped so the documentation ends up being: `*This highliting doesn't work**`

```
[Trace  - 8:33:46 PM] <semantic> Response received: quickinfo (31). Request took 2 ms. Success: true 
Result: {
    "kind": "const",
    "kindModifiers": "",
    "start": {
        "line": 5,
        "offset": 7
    },
    "end": {
        "line": 5,
        "offset": 26
    },
    "displayString": "const documented_function: () => void",
    "documentation": "yadayada",
    "tags": [
        {
            "name": "param",
            "text": "var *This highliting doesn't work**"
        },
        {
            "name": "param",
            "text": "var2 But**This works!**"
        }
    ]
}
```

**Comment by madacol** [comment]
The issue disappears if the hyphen-syntax is used to separate description
```js
/** yadayada
 * @param {number} var **Should be bold**
 * @param {string} var2 - **It's bold!**
*/
const documented_function = () => {}

documented_function();
```
![image](https://user-images.githubusercontent.com/6379896/68157082-f23fa280-ff1a-11e9-84e7-e264a924fe6b.png)
