### ISSUE TITLE
Annotation for compiler to check a statement that's not part of the emit

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/TypeScript#33384]
## Search Terms
compiler checked statement no emit

## Suggestion
Allow a program to contain a commented out + explicitly annotated statement that is checked as though it's part of the program, but is not emitted. Something like:

```ts
// @ts-only myStatementHere
```

This may be a horrible idea... I'm still not sure.

## Use Cases

Sometimes, you need to add some code just to get the compiler to do what you want, but you don't actually want this code to have an effect at runtime. 

For example, I remember seeing comments on the issues here proposing code like the following, before TS added the `ReturnType` helper:

```ts
const x = (null as true) && myFunction();
type ReturnTypeMyFunction = typeof x;
```

Under my proposal, you could instead have written:

```ts
// @ts-only const myFunctionRes = myFunction(); 
type ReturnTypeMyFunction = typeof myFunctionRes;
```

I think this fits with general structure of directives (for linters, TS, etc) in comments, but another option would be to use some sort of keyword, in case people would be confused by commented out code effecting the compiler (beyond suppressing errors):

```ts
MAGIC_KEYWORD_HERE const x = myFunction(); 
type ReturnTypeMyFunction = typeof x;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This really isn't the kind of thing we want to have - pushing the type system further to never need expression-level code is our primary goal.
