### ISSUE TITLE
Test issue please ignore

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#33382]
Just trying out a bot thing

**Comment by weswigham** [comment]
@typescript-bot please close this

**Comment by weswigham** [comment]
please close this

**Comment by weswigham** [comment]
please close this

**Comment by weswigham** [comment]
please close this

**Comment by andrewbranch** [comment]
@typescript-bot please ignore @weswigham

**Comment by weswigham** [comment]
😛 

Just proving that a thing is broken with the `Triage` role, is all. Lemme swap it back to the older permission...

**Comment by weswigham** [comment]
And now

**Comment by weswigham** [comment]
please close this

**Comment by weswigham** [comment]
Bam, see that? Works fine. `Triage` role is borked.

**Comment by weswigham** [comment]
FYI: I'm going to disable the `please close this` rule now, so don't go trying it elsewhere 😛

**Comment by weswigham** [comment]
thank

**Comment by jack-williams** [comment]
<a href="https://imgflip.com/i/3abaq5"><img src="https://i.imgflip.com/3abaq5.jpg" title="made at imgflip.com"/></a>

**Comment by DanielRosenwasser** [comment]
@typescript-bot please unsubscribe me.
