### ISSUE TITLE
Possible Regression: resolveJsonModule Projects must list all files or use an 'include' pattern.

### ISSUE THREAD

**Issue by duro** [microsoft/TypeScript#33399]
**TypeScript Version:**  3.7.0-dev.20190912

**Search Terms:** 

`resolveJsonModule` `Projects must list all files or use an 'include' pattern`

**Code**

tsconfig.json
```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": "./src",
    "strictNullChecks": true,
    "resolveJsonModule": true
  },
  "include": ["src/**/*.ts", "src/**/*.json"],
  "references": []
}
```

tsconfig.base.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "lib": ["es2017"],
    "composite": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "sourceMap": true,
    "skipLibCheck": true
  }
}
```

**Expected behavior:**

When `resolveJsonModule` is turned on, and json files have been included in the `includes` array, I should be able to import json files with no trouble.

**Actual behavior:**

When I use the above tsconfig options, and include a json file, I get the following error:

<img width="1239" alt="e2e_test_ts_—_serverless-mono" src="https://user-images.githubusercontent.com/17632/64816951-992c4180-d55d-11e9-8c72-914efd73c681.png">

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/31181

**Comment by Razzeee** [comment]
I'm seeing the same with this branch

**Comment by sheetalkamat** [comment]
@Razzeee https://github.com/elm-tooling/elm-language-server/blob/rank/tsconfig.json#L17 is not sufficient. You have to explicitly list json files to be included. Changing that to `"include": ["src", "src/**/*.json"]` fixes the issue.

**Comment by Razzeee** [comment]
Thank you, that fixes compilation, after restarting VSCode
