### ISSUE TITLE
explicit return function type produces error when generic function result is returned directly

### ISSUE THREAD

**Issue by Hotell** [microsoft/TypeScript#33394]
**TypeScript Version:**  3.6.3

**Search Terms:**
- generics with explicit return type error  

**Code**

```ts
// ======================================
// implementation of deepPick ( for 2 nested levels only )
// ======================================

type IfKey<T, K> = [K] extends [keyof T] ? Exclude<Required<T[K]>, undefined> : T
type NextKey<T, K = keyof any> = [K] extends [undefined] ? undefined :
  [keyof T | undefined] extends [K] ? keyof any : (keyof T | undefined)

  function deepPick<
 T0 extends object,
 K1 extends NextKey<T0>,
 T1 extends IfKey<T0,K1>,
 K2 extends NextKey<T1,K1>,
 T2 extends IfKey<T1,K2>,
>(value:T0,path:[K1?,K2?]): T2 | undefined {
  return path.reduce((result: any, key: any) => {
    return result!=null ? result[key] : result;
  }, value);
}

// ======================================
// DATA
// ======================================

type User = {nickname:string; fullName:string; age?:number}
const users: {john: User; doe:User} = {
  john: {
    nickname: 'jo5',
    fullName: 'Johny Five',
    age: 123,
  },
  doe: {
      nickname: 'doe',
      fullName: 'John Doe',
  }
}

// ======================================
// Usage
// ======================================

// 🚨 $ExpectError
/*
 error TS2322: Type '0 | { john: User; doe: User; }' is not assignable to type 'number'.
  Type '{ john: User; doe: User; }' is not assignable to type 'number'.
 return deepPick(users,['john','age']) || 0
*/
function getSomedata(): number {
  return deepPick(users,['john','age']) || 0
}

// 💥NO ERROR
function getSomedataNoErrorAssign(): number {
  const result = deepPick(users,['john','age']) || 0
  return result
}

// 💥NO ERROR
// properly inferred to return `number`
function getSomedataNoError() {
  return deepPick(users,['john','age']) || 0
}
```

**Expected behavior:**

Explicitly providing return type should work

**Actual behavior:**

When explicitly providing return type, TSC will error out on `deepPick` usage.

*In TS 3.5 there are 2 errors:*

1. `getSomedata`
```
 error TS2322: Type '0 | { john: User; doe: User; }' is not assignable to type 'number'.
  Type '{ john: User; doe: User; }' is not assignable to type 'number'.

107   return deepPick(users,['john','age']) || 0
```
2. `getSomedataNoErrorAssign`
```
error TS2322: Type '0 | { john: User; doe: User; }' is not assignable to type 'number'.
  Type '{ john: User; doe: User; }' is not assignable to type 'number'.

112   return result
```

**TS 3.5 vs TS 3.6**

![TS 3.5](https://user-images.githubusercontent.com/1223799/64784550-aa2f7f80-d56a-11e9-8086-f8cdd0a16c0c.png)

![TS 3.6](https://user-images.githubusercontent.com/1223799/64784587-ba475f00-d56a-11e9-85a3-1359d673ce61.png)

**Playground Link:** [Demo - NOTE that playground is using old ts 3.5.1](http://www.typescriptlang.org/play/#code/C4TwDgpgBAkgZgaQiAPAFQDRQQPigXigG0EBdKCAD2AgDsATAZ2IGtkB7OKNcgfigCilAMYAbAK70IKAEoQAjuICWAJwj10JUjiziGEOEtrq8ALm4AoC3D3DgS9rShSIYAApLhLFBe4AGCmo6Jih2ACMAKwg7DF8EAEZAmgZmNhBOfygAHyg9KUNjeljuRKpkkPgkVDQ-DASdOIAmJODUji40RJy8gyN1YrRmstbYRGR0eLrGhpwACgA3AEMJCFMarDBF4AALUxJ43ineUgBKc0GoAG9fKDVgcRUnTZ2AOjV6cWEIWYXl8VWoItaCAsGlzECQCcCHhrlA4bcIPdHlAlisoAAydEov4QIhpUgAbhuAF8sKj-icicSrKBIFAAKqMCAqAhXWieFi0RYAW1WjGAKiMAHMCTZRKIAHI8vkC4UExZCiC8Uy0cTcsLM6kWYSOfm5JkqRjmS4RdjbWjmRnMgn0dirK0qYms2FQU3m403OHsrxc3nmADkpoArP7ivCxZLpQGAFJm4FQABiSnmEFDnsBivM8UaAGYw6SbraAS74VBvZyo1B-UW06W4RGpX6q7HzVAACJ22t1hUAmC0ApKUAkixamy0OwOJyK4AAZXYvPoW0WszOZbVGpZLruDycLncHNm4gNjAwREDcdD-p7-tO2RyfhHVjHE8cUGnc4XS4l7AEKhU7BUABBRhGCUIVaBXcxVXVZkrhuHVaD1NRGHEURgFZPcPC8Q9j1Pc9zUva9byye8bm3ZFkNQ4BH2sWx7Ffd953UL8fz-ACVzguFyN3CBXCwlgcOZE8zzdWhCMVG8oRIqAH2JIA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/32937, https://github.com/microsoft/TypeScript/issues/33002

**Comment by RyanCavanaugh** [comment]
Is there a simpler reproduction of the difference here?

**Comment by Hotell** [comment]
@AnyhowStep 
> It seems like this deepPick type won't be needed once optional chaining comes in.

Yeah for most of the use cases it wont, although for non esNext browsers, transpilation of optional chaining is quiet heavy in terms of js bundle size.

> Overloads seem to work well,

Actually we use similar overload solution as you proposed, which errors out in  3.6
![image](https://user-images.githubusercontent.com/1223799/65165245-b28e2b80-da3e-11e9-9eee-6376f30ffaab.png)


![image](https://user-images.githubusercontent.com/1223799/65165214-a013f200-da3e-11e9-838e-32d7b67597db.png)

**Comment by Hotell** [comment]
So no difference @RyanCavanaugh  both implementation are producing same error in 3.6
