### ISSUE TITLE
ThisType doesn't work with objects in array

### ISSUE THREAD

**Issue by Akryum** [microsoft/TypeScript#33392]
**TypeScript Version:**  3.7.0-dev.20190912

**Search Terms:** thistype array

**Code**

```ts
interface Instance {
  foo: 'bar' | 'baar'
}

type Fn = () => any | any

interface Sub {
  vars: Fn
}

interface Options {
  subs: Sub | Sub[]
}

const meow: Options & ThisType<Instance> = {
  subs: {
    vars () {
      return this.foo === 'bar'
    }
  }
}

const meows: Options & ThisType<Instance> = {
  subs: [
    {
      vars () {
        // Error happens here
        return this.foo === 'bar'
      }
    }
  ]
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

```
error TS2339: Property 'foo' does not exist on type 'Sub'.
```

**Playground Link:** 

https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIgM5jiJyDeAUMsjAPZkBcyA5AEZxQ3IA+tDjNhAvoYWAE8ADigBiIZAF5kACgCUUgHzIcA1ipAC+oSLEQoAygFc6BYsgBujDNXE9t4aPDwB5IWGBlMZkhhM3kY1M2IIBtAF17QgQvLGQAWwgyAHdqNw9Y5AAyZAAVAAtgDFzhCAAedCwcJGVpIl9-anqSS2tZBWaW5CgIMCMoCTBCjAA6cjIpSWl6TnMSXnmomMwwBKTkgPTPbxyCopKRCpXqiFqfZD86ANC5866rKAx2u67u3v7B4bGKSemGJluiy6C2QkV4QA

**Related Issues:** 

-

**Comment by fatcerberus** [comment]
Pretty sure `ThisType` only affects the object directly assigned to it, not sub-objects, whose properties have their own types (and therefore don't inherit the `ThisType`).

**Comment by Akryum** [comment]
https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIgM5jiJyDeAUMsjAPZkBcyA5AEZxQ3IA+tDjNhAvoYWAE8ADigBiIZAF5kACgCUUgHzIcA1ipAC+oSLEQoAygFc6xugWLIAbowzVxPbeGjw8ZiyRAQsEACbUzM0dCHRd9ZAB5ITBgMkwPZAwTO2R3NjMAbQBdYIQ4rGQAWwgyAHdqKJj85AAyZAAVAAtgDHrhCAAedCwcJGVpIhIkuhTBkmQvH38E8etbWQUx2ZIoCDAjKAkwZowAOnIyKUlpek5LWd4Ly15eQjzMMCKS0pTK2Pi6ppa2kS6H3og-QSwxSGXOM3Gk0g0yWyxsUAwCwhy2Qq3Wm2Q2xa+woRxODCY4KuKMu41JOV4QA

**Comment by Akryum** [comment]
I guess it's necessary, otherwise Vue typings wouldn't work 😁

**Comment by RyanCavanaugh** [comment]
@fatcerberus is correct

**Comment by weswigham** [comment]
FYI, if you want a deeply bound `ThisType`, you can do something [like](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIgM5jiJyDeAUMsjAPZkBcyA5AEZxQ3IA+tDjNhAvoYWAE8ADigAiECEICCQoQBsBAFQAWwDIuEQAPIoA0yRSrUA+ZAF4CAbQDSyUMgDWEAWRgGAutXGSZ8pavVNHRt3fUMA425kADIDAI0RHSMMYwBuPkERZAAxEHNkAAoASnNTHAFWZHK+UEhYRBQAZQBXOha6AmJkADdGDGpcnhrwaHg8ds6SEAgsCAATanb2ocJa0YbkAHkhMGAyTEnkDFb+5Am2dst3FYR9rGQAWwgyAHcvCWlZBWSE7W3du76dBYHBIUwWIgkY50U6QkjIaazBaHeE9PqFEpw1EkKAQMDNKB5MABAB05DI5jMFnonC6qN49K6vF4hFumDAj2eL1O3k+fh+QX+e0wQPZoIg4MO0NOljpKPhiMgyKx2N6UAwGPl2OQuPxhOQxLUZIolOpDCYcsZ2oZ8Jt114QA)
```ts
type DeepApplyThisType<T, TThis> = {[K in keyof T]: DeepApplyThisType<T[K], TThis>} & ThisType<TThis>;
```
but it's on you to make sure your library can actually bind the `this`'s of those functions up to match that.

**Comment by Akryum** [comment]
@RyanCavanaugh I've put a link in [this message](https://github.com/microsoft/TypeScript/issues/33392#issuecomment-531282189) showing the inconsistency in nested objects.

**Comment by Akryum** [comment]
Could the issue be re-open? It causes me a lot of difficulties for [vue-apollo typings](https://github.com/Akryum/vue-apollo/releases/tag/v3.0.0-rc.6).

**Comment by dragomirtitian** [comment]
@Akryum  `DeepApplyThisType` works but does not cover all cases as it should. It should distribute over `T[K]` to correctly apply this in union, and should not perform the transformation on primitives. This works with your example:

```ts
type DistributionHelper<T, TThis> = T extends Function | string | number | boolean ? T: DeepApplyThisType<T, TThis>

type DeepApplyThisType<T, TThis> = {
  [K in keyof T]: DistributionHelper<T[K], TThis>
} & ThisType<TThis>;
```
[play](https://www.typescriptlang.org/play/#code/C4TwDgpgBAIglgZ2AJzgIwK7DgewHYASEANpMgDwAqANFJZQBaIB8UAvHVBAB7AR4ATBFABiGPAGNs+KAB8oSVHgDmcqHgwBbNBGRq0OHMQgBDPFAD8dAFywIEMAEEwYYiEaJK4CFVr0mCMwAUEGgkHYOzq7uAV6QvnQegexQAN5BUFAA2gDSUHDmANYQIDgAZnQAurbwiuhYuIQkZFS5lX5JwQC+UABkdLHeVJ0A3CEFfMhlJhLQAJJ4SGazaRlQZYa2AORoJshbajsme1tBXeN4k9MrMCbAJquZGzi2dSpnIWHQzkbEOADyYGkixSAAU9tgTMRyABlSASOBQwHA5L9ACKGF0IAAsiYwBcrjNoHCIAikUDGsJ0pkACQSYhwfjAV4oArKD5BCa6a7QDFY3FgR7ZYogFlKZTVBSslRqPnIEAwCBlApwYEcrlTIlQABqe0RaGMVLWWRFYrZkrMIHVl25WrlCqVKuBQoAbnqTAaIAgLLZdagPYa1AAKIMASnYrD9+sNobWGDAAjuEB9UCDifuNTuJnDbFYlo5Xyg9pSb1U8ntiuVeFVjRCEnwSCgeN+OAAjLYfsQ-sjKX0Bp4hgslpIIKwONSoHSGUztgAWABMW2oa2etgnmTd-s9wjDQsymWQEGAGGQ5nX+8yu2QtmAAQAdM81hfzs-lxf4+mILY01mc6x0yYD6GGs5znEE9aLMATZgC2841PYTguG4SRxD4nbdhSDa0EO9wjmOQpToylxzoub7rJse5QJu0Zeqm4bngeR4nmeT4XlAV43vej5sVAL77l0ZGZB+SbfgBf5QABQE4CBHLGFBwgcM2XY4POWQAERqZUQA)

Other corner cases may arise but they can probably be solved.

**Comment by Akryum** [comment]
Thanks, will try it

**Comment by Akryum** [comment]
It's still doesn't work, the types are still broken:

[Play](https://www.typescriptlang.org/play/#code/C4TwDgpgBAIglgZ2AJzgIwK7DgewHYASEANpMgDwAqANFJZQBaIB8UAvHVBAB7AR4ATBFABiGPAGNs+KAB8oSVHgDmcqHgwBbNBGRq0OHMQgBDPFAD8dAFywIEMAEEwYYiEaJK4CFVr0mCMwAUEGgkHYOzq7uAV6QvnQegexQAN5BUFAA2gDSUHDmANYQIDgAZnQAurbwiuhYuIQkZFS5lX5JwQC+UABkdLHeVJ0A3CEFfMhlJhLQAJJ4SGazaRlQZYa2AORoJshbajsme1tBXeN4k9MrMCbAJquZGzi2dSpnIWHQzkbEOADyYGkixSAAU9tgTMRyABlSASOBQwHA5L9ACKGF0IAAsiYwBcrjNoHCIAikUDGsJ0pkACQSYhwfjAV4oArKD5BCa6a7QDFY3FgR7ZYogFlKZTVBSslRqPnIEAwCBlApwYEcrlTIlQABqe0RaGMVLWWRFYrZkrMIHVl25WrlCqVKuBQoAbnqTAaIAgLLZdagPYa1AAKIMASnYrD9+sNobWGDAAjuEB9UCDifuNTuJnDbFYlo5Xyg9pSb1U8ntiuVeFVjRCEnwSCgeN+OAAjLYfsQ-sjKX0Bp4hgslpIIKwONSoHSGUztgAWABMW2oa2etgnmTd-s9wjDQsymWQEGAGGQ5nX+8yu2QtmAAQAdM81hfzs-lxf4+mILY01mc6x0yYD6GGs5znEE9aLMATZgC2841PYTguG4SRxD4nbdhSDa0EO9wjmOQpToylxzoub7rJse5QJu0b2PYO7hueB5HieZ5PheUBXje96PuxUAvvuXRkZkH5Jt+AF-lAAFATgIEcsYUHCBwzZdjg85ZAAROplRAA)

No error is thrown here:

```ts
const apollo2: DeepApplyThisType<ApolloOptions, Instance> = {
  $client: '42',
  foo: {
    // No error thrown here
    variableeees () {
      return {
        bar: this.foo
      }
    },
    update: (data) => data.foo
  }
}
```

**Comment by Akryum** [comment]
Please can this be reopen? :sweat_smile:

**Comment by Akryum** [comment]
:skull:
