### ISSUE TITLE
.c

### ISSUE THREAD

**Issue by live-user0001** [microsoft/TypeScript#33406]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by orta** [comment]
Closing as not being filled out
