### ISSUE TITLE
ES6 - stripping common / require imports from exported code

### ISSUE THREAD

**Issue by karimbeyrouti** [Microsoft/TypeScript#3341]
I know ES6 imports are different than the regular requireJS format, however the exporter currently strips regular import from exported ES6 JS:

I.e. the following is removed from resulting export:
import Matrix               = require("../../../libts/kurst/geom/Matrix");

I would at least expect it to transforms or keep the import, this should be expected output:

var BitmapData = require("../../kurst/display/BitmapData");

as it would still work with ES6 ( and common or require js ) .

**Comment by danquirk** [comment]
The non-ES6 style imports continue to use our original rules which elide imports when the imported value is only used in type position. You can use Matrix as an expression to force the import to be emitted or use the <amd-depedency ...> declaration.

**Comment by mhegazy** [comment]
you can also force loading the module using  
```ts
import "../../../libts/kurst/geom/Matrix";
```
this is not going to be removed by the compiler.
