### ISSUE TITLE
Statically guarantee presence of object key via string literal type

### ISSUE THREAD

**Issue by rix0rrr** [microsoft/TypeScript#33410]
## Search Terms

object key string literal

## Suggestion

I'm trying to write a function to set a field in an object using a string literal type. I can write the signature for it, but I can't write the body. A simplified version of it looks like this:

```ts
function foo1<N extends string>(key: N): {[key in N]: string} {
    return { [key]: 'foo' };
//  ~~~~~~~~~~~~~~~~~~~~~~~~
//  Type '{ [x: string]: string }' is not assignable to type '{[key in N: string}'
}


function foo2<N extends string>(key: N): {[key in N]: string} {
    return { [key]: 'foo' } as any; // Cast away the error
}


const x = foo2('henk');   // x :: { henk: string } as expected
```

I imagine this has something to do with the keys of an object literal being declared to be `string` and the stronger type `N extends string` getting dropped on the floor?

But the code feels like it is correct and it feels like the type system should be able to see that.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment]
Keys in mapped type are related contravariantly (in reverse), so even though `key` is related to `N`, it's not the case that `N` is related to the particular key denoted by `key`. As an example of why it is correct to flag an error, consider this usage.
```ts
const a = foo1<'x' | 'y'>('x');
const y: string = a.y // not really a string.
```

**Comment by poseidonCore** [comment]
The best that you could do is some constructive process, but this just illustrates the issue noted above:

```ts
function foo1<N extends string>(key: N): {[key in N]: string} {
    var result:{
        [key in N]: string
    } = <any>{}; 
   // ...
   // You would need to construct `result` so that it had all the keys of N, being passed by one of them.
    return result;
}

const x = foo1('henk');   // x = { henk: string }
const a = foo1<'x' | 'y'>('x'); // a = {x: string; y: string; }
```

**Comment by rix0rrr** [comment]
That's a fair point. I don't suppose there is a way to restrict N to not be a union?

**Comment by jack-williams** [comment]
#24085, #27808, #28430
