### ISSUE TITLE
Trouble implementing .then

### ISSUE THREAD

**Issue by maxnordlund** [microsoft/TypeScript#33416]
**typescript@3.7.0-dev.20190913**

I added to libraries: `$ tsc --lib es2018,dom --target es2018 test-case.ts`.

**Search Terms:**
AsyncIterator, AsyncGenerator, Then, Promise, PromiseLike

**Code**

```ts
/**
 * Promise.prototype.then onfufilled callback type.
 */
type Fulfilled<R, T> = ((result: R) => T | PromiseLike<T>) | null;

/**
 * Promise.then onrejected callback type.
 */
type Rejected<E> = ((reason: any) => E | PromiseLike<E>) | null;

class Waiter<T, TReturn, TNext> implements PromiseLike<T> {
  source: AsyncGenerator<T, TReturn, TNext | undefined>;

  constructor(
      source: () => AsyncGenerator<T, TReturn, TNext | undefined>,
  ) {
    this.source = source();
  }

  then(onfufilled?: Fulfilled<TReturn, T>, onrejected?: Rejected<T>): Promise<T> {
    return this.implementation().then(onfufilled, onrejected);
  }

  private async implementation(): Promise<TReturn> {
    // Drain the async iterator by hand since for-await-of would
    // discard the returned value.
    while (true) {
      const { done, value } = await this.source.next();

      // We know value will be a TReturn as the async iterator
      // has already been exhausted
      if (done) return value as TReturn
    }
  }
}

async function main() {
  let waiter = new Waiter(async function* gen() {
    yield 123;
    return "abc";
  });

  try {
    let result = await waiter;
    console.log(
      `expect ${JSON.stringify(result)} to equal "abc"`,
      result === "abc"
     );
  } catch (error) {
    console.error("Oh no", error)
  }

  let other = await waiter.then(() => 123);
  console.log(`expect ${JSON.stringify(other)} to equal 123`, other === 123);
}

main().catch(console.error)
```

**Expected behavior:**
The code to compile, and correctly infer the return type for `other` in the example above.

Running it with node gives the correct output:
```
expect "abc" to equal "abc" true
expect 123 to equal 123 true
```

**Actual behavior:**

```
test-case.ts(20,3): error TS2416: Property 'then' in type 'Waiter<T, TReturn, TNext>' is not assignable to the same property in base type 'PromiseLike<T>'.
  Type '<S, E>(onfufilled?: (result: TReturn) => S | PromiseLike<S>, onrejected?: (reason: any) => E | PromiseLike<E>) => Promise<S | E>' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: (value: T) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => PromiseLike<TResult1 | TResult2>'.
    Types of parameters 'onfufilled' and 'onfulfilled' are incompatible.
      Types of parameters 'value' and 'result' are incompatible.
        Type 'TReturn' is not assignable to type 'T'.
          'TReturn' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
```

When poking around in VS Code it correctly infers that `await waiter` is a string, which is nice. But `await waiter.then(() => 123)` becomes unknown instead of number. I'm guessing it's because of the type error above, but still pretty amazing that it can infer anything at all.

I also tried inlining the definitions of `Fulfilled` and `Rejected`, but no dice. I also tried changing all type parameters to `T`, but again nothing:

```
test-case.ts(20,3): error TS2416: Property 'then' in type 'Waiter<T, TReturn, TNext>' is not assignable to the same property in base type 'PromiseLike<T>'.
  Type '(onfufilled?: (result: TReturn) => T | PromiseLike<T>, onrejected?: (reason: any) => T | PromiseLike<T>) => Promise<T>' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: (value: T) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => PromiseLike<TResult1 | TResult2>'.
    Types of parameters 'onfufilled' and 'onfulfilled' are incompatible.
      Types of parameters 'value' and 'result' are incompatible.
        Type 'TReturn' is not assignable to type 'T'.
          'TReturn' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
```

**[Playground Link][playground]** 

**Related Issues:** 
#16993
#15599
#33239
#31264

[playground]: https://www.typescriptlang.org/play/index.html?target=5#code/PQKhCgAIUgFAnA9gWwJYGcCmA6ADkgF0QIE9ccCALTAO0kRoDMBXR1AG3cwBNIBjAIacARgL4BrSKXLYoIYOGmZIAMWbs2nHgB4ASgBpIAFQB8kALyQAFFfiZ06ggC5IugJQWzRyAB84SNCwAGVRxTG1TDz8adXYAbnBwUAhofxQMCmo6BjsAK0w+Ah5+IXZRCSkyHDkFJVdMfMKdAFEzSxs7AXQGFwEaEg9zM2bfNMDMELDtVqjIGM4E8D52LvRIAHUBVCL4CMMjXUwCZngafYA5TAAPAjNUZFwuZFoCNYR04NDw00gAbyhIN0TnxMC4AILoEg0PgAcVomHgAiIuyM+0Ox1OF2uBFGzBo3EwbBoPBMi0g-AY6AI8GYhUQ8CsAPJ5KB8BBLisgzMEKhsPhiORe2M6JOZ2MlxuuPxhNQxO4Jn0AI8-2ZUkoGGwrJBFkBiGBmE5CXJAF9EuSqLQrAwWJouNwAPwuNQaDh2iIizHGBX0Gh5ApFB0uQ6NAMRExuFzvcZhv5MyB2DF0Kga+6PTDPGgEJGoBic7AWmhWpisV08Qw5Br+nhuI2QU0A-CoABuSOUXV5kFTTxe2dzEbGGXdR1FZhVzOAwEgABFEbK1W3IdDOzskfTIMISJBKH1eOhZdrGPSALQCADuWwIR8QjEgp717G4cYnkG4GEE8F4Fvjw9OxRb7GYapVVPdUuGsalAOVONyT4SkcV+F8GEwQx-0AusdTPC81Q1LUcGJG5DTNVVIGfdZlHEGhEFPSBUOUU9XXXNthR-OgunnSB2yXbYEVXeBoJIydtzWIROm4TdhEwWhIGubdmCpHh+NQG8rG4JCPATUUaKENC2IOFi41NE1wHrTi+EgFhoQIHM6GQLZCyg8kuBxc9uPgHViWozZXKsUzzLxQprJgABzS0HOZEhUEwB9IAARgAJgAZlrckNNOSAACIBGEPh0trY0ayI6lNzHRyjm-Bx2BxSxMO2W8LwRZKKRobouGwdhECCxliMgAADa5yEKSAABJfgAKQAZQAeXOTVqVlIKlJIWx7EcNxjSkRBpIAR2YIQMqynKesVbq7AqqrzEsTLsvS6CCpNEoCD4ShrARJB4DCmDKUQVrXvpKx0sm57KPSwxfvegF61KnFiGoNzqpc5z6vgfMshsLlYsSu6mpanB2s6vqrgGnERom6bZvgebFqtC13vWohtt29gMYSo76BpiwLuZgr61s2U80ER7KCsWDmu+nAwbcIA

**Comment by rbuckton** [comment]
This doesn't seem to be a bug in TypeScript, but rather an issue with the definition of the type.

The `T` in `Waiter<T, TReturn, TNext>` isn't actually used in `implementation()`, and the type variable returned in `then` should be its own type variable rather than the `T` in `Waiter`.  Here's a version with types that match the implementation:

```ts
/**
 * Promise.prototype.then onfufilled callback type.
 */
type Fulfilled<R, T> = ((result: R) => T | PromiseLike<T>) | null;

/**
 * Promise.then onrejected callback type.
 */
type Rejected<E> = ((reason: any) => E | PromiseLike<E>) | null;

class Waiter<T, TReturn, TNext> implements PromiseLike<TReturn> {
  source: AsyncGenerator<T, TReturn, TNext | undefined>;

  constructor(
      source: () => AsyncGenerator<T, TReturn, TNext | undefined>,
  ) {
    this.source = source();
  }

  then<TResult1, TResult2 = TResult1>(onfufilled?: Fulfilled<TReturn, TResult1>, onrejected?: Rejected<TResult2>): Promise<TResult1 | TResult2> {
    return this.implementation().then(onfufilled, onrejected);
  }

  private async implementation(): Promise<TReturn> {
    // Drain the async iterator by hand since for-await-of would
    // discard the returned value.
    while (true) {
      // NOTE(rbuckton): The `T` in `AsyncGenerator<T, ...>` is never 
      //                 sent: ---------------------v
      const { done, value } = await this.source.next();

      // We know value will be a TReturn as the async iterator
      // has already been exhausted
      if (done) return value as TReturn
    }
  }
}

async function main() {
  let waiter = new Waiter(async function* gen() {
    yield 123;
    return "abc";
  });

  try {
    let result = await waiter;
    console.log(
      `expect ${JSON.stringify(result)} to equal "abc"`,
      result === "abc"
     );
  } catch (error) {
    console.error("Oh no", error)
  }

  let other = await waiter.then(() => 123);
  console.log(`expect ${JSON.stringify(other)} to equal 123`, other === 123);
}

main().catch(console.error)
```
[Playground link](https://www.typescriptlang.org/play?target=99#code/PQKhCgAIUgFAnA9gWwJYGcCmA6ADkgF0QIE9ccCALTAO0kRoDMBXR1AG3cwBNIBjAIacARgL4BrSKXLYoIYOGmZIAMWbs2nHgB4ASgBpIAFQB8kALyQAFFfiZ06ggC5IugJQWzRyAB84SNCwAGVRxTG1TDz8adXYAbnBwUAhofxQMCmo6BjsAK0w+Ah5+IXZRCSkyHDkFJVdMfMKdAFEzSxs7AXQGFwEaEg9zM2bfNMDMELDtVqjIGM4E8D52LvRIAHUBVCL4CMMjXUwCZngafYA5TAAPAjNUZFwuZFoCNYR04NDwg6OTmjMAN5QSDdE58TAuACC6BIND4AHFaJh4AIiLsjPtDsdThdrgRRswaNxMGwaDwTItIPwGOgCPBmIVEPArMCqVTQfBwS4rIMzNDYQikSi0XtjFi-ribgSiSTUGTuCZ9MCPEC2VJKBhsBzwRYQYgwZgeQkqQBfRJUqi0CKHBzsAgARkx9kcACZdT9bQ6TFYGCxNFxuAB+FxqDQcAPW344sXOu32xX0Gh5ApFIMuQ6NVORz0ukxuFzvcbZxz20Ye12A1mQOzYuhUTX3R6YZ40Aio1AMHnYS00H1MVjhniGHINFM8NzGyBm4H4VAAN1Ryi6AsgjaeL3bnfzYwykdrlbVwGAkAAIii5eqlzC4audqimZBhCRIJQ+rx0HKdYwmQBaAQAdy2Agf0QRhIH-fV2G4Ksj0gbgMEEeBeEtaso3lSAF3YZhqjVf8NS4aw6WwlUqypWDzgAeSMZpbGEBlxCIGhtyMahIAAAyMNjVzoNj+ThREyWFJlRWwUSTC4jA5kwOdkUgUjIFgtUlOUkEXhcH8NM0rTtJ0ud5L4Gl8QBOCGEwQxMOwqddQAoD1U1bUcDJG4jXNJTYPWZRxBoRB-wwoRLP-cNHyXGNa0gLpL3C68+FvZF73geTYNfNYhE6bhn2ETBaEga5X2YWkeHk1AwKsbhTI8Gs-j8rCr1Cv4qzNU1wGnZcbxYOECA7OhkC2XsSKpLh8UA7ZZMsMlfM2EbmVamL2sKLqYAAc1oHlIFVNkSFQTAoMge0XQAZknKlKtOSAACIBGEPgzsnE0J1culn3WgajlQz1rOGoagORI7qRobouGwdhEEWlllLY65yEKSAABIAQAKQAZQo84tTpOVFuKkhbFjAg3BNKREBygBHZghHOy7rrYpVlLsd7zAZimrrO0j7tNEoCD4ShrGRJB4H6tkDP+xBAd5pkrDOijue8s7DDF-ngWnF78WIah4A+2zPuRbsshsXldoOtm-oBnBgdBiGrih-E4aRlG0fgDGsZ9S1+YJogSbJ9gDf26n6BdixGb2-b7unHq5S7QROcoKwhZN7B5bccAgA)
