### ISSUE TITLE
Intl.PluralRulesOptions does not behave according to spec

### ISSUE THREAD

**Issue by longlho** [microsoft/TypeScript#33413]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
Intl.PluralRules
PluralRules

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
`Intl.PluralRules` type definition behaves according to spec
**Actual behavior:**
Missing attributes from `PluralRuleOptions`

**Comment by RyanCavanaugh** [comment]
Please include enough information in the report for it to be actionable. Which attributes? Which spec? Documentation? IDL? What code were you trying to write?

**Comment by longlho** [comment]
Sorry I created the PR and it told me I need a GH issue so I just made a dummy one. Details are in https://github.com/microsoft/TypeScript/pull/33414
