### ISSUE TITLE
auto import not working

### ISSUE THREAD

**Issue by necro42** [microsoft/TypeScript#33444]
ctrl + space  >> auto completion and auto import

my normal different project
![image](https://user-images.githubusercontent.com/42927365/64948913-0b30bd80-d8b3-11e9-9c3c-af8987c76900.png)

but my unusual project

![image](https://user-images.githubusercontent.com/42927365/64948191-78435380-d8b1-11e9-9726-7e05a514a791.png)

These projects are in the same environment.

I'm a beginner.
Need help

**Comment by RyanCavanaugh** [comment]
Please provide enough information when logging bugs such that we could feasibly reproduce the issue you're experiencing. Additionally, screenshots of code are *not* something we can work with - code needs to be provided in text form.

**Comment by necro42** [comment]
@RyanCavanaugh 
I would be grateful if you could tell me what to provide.

**Comment by RyanCavanaugh** [comment]
Ideally, just three files:
 * The file you're trying to auto-import *in* (would reasonably be blank minus the text you're trying to trigger with)
 * The file you're trying to auto-import *from*
 * Your `tsconfig.json`

plus the locations on disk of these files relative to each other

**Comment by necro42** [comment]
@RyanCavanaugh 
I did my best.
But please tell me if there is anything missing

**Comment by necro42** [comment]
my problem just export / import

a.ts
```
export const a = () => {
return "afile"
}
```
index.ts
`
export {default} from './a'
`


There was no default but it was an error caused by loading the default.
But this was not solved by vscode.

I hope this will help beginners like me.
