### ISSUE TITLE
function type extends behavier different in VSCode and playground.

### ISSUE THREAD

**Issue by Monsooon** [microsoft/TypeScript#33442]
**TypeScript Version:**  3.6.2

**Search Terms:** type，function, extend

**Code**

```ts
type A = {
  (p?: string): object
}

type B = {
    (p: string): object
}

type OptionalFirstArg = (a?: never) => unknown;

type IsOpt<F> = F extends OptionalFirstArg ? true : false;

type testA = IsOpt<A>;
type testB = IsOpt<B>;
```

**Expected behavior:** `testB` should be `false`? I don't know.

**Actual behavior:** In typescript [playground](http://www.typescriptlang.org/play/?target=6#code/C4TwDgpgBAglC8UDeAoK6oAowH4BcUAzsAE4CWAdgOYCUBA9gEYBWEAxsCgL4oqiRQAQgmRoM2AsXLU6UJqw7de-aAHkwwMvQoBDADYAxMiWIwSVEZh34oFCADcIJGggB8UAK4UA1hXoB3CgBuZXBoAElCdWAAHgN3RAMoCAAPYAgKABNCKGitXUNjU3MoHChSD2gCADN9QggQvjDyiFMRSOiYmFcgqAB6Ppa2shyKiCaBdOJhRA6NGMEe-sGp4GERqFq9eqA) with version 3.5.1 the `testB` is `false`. In VS Code with typescript@3.6.2 the `testB` is `true`.
![截图20190916141130](https://user-images.githubusercontent.com/22792671/64945813-fef13400-d8a3-11e9-96bc-f0fd05978da8.png)

**Playground Link:** http://www.typescriptlang.org/play/?target=6#code/C4TwDgpgBAglC8UDeAoK6oAowH4BcUAzsAE4CWAdgOYCUBA9gEYBWEAxsCgL4oqiRQAQgmRoM2AsXLU6UJqw7de-aAHkwwMvQoBDADYAxMiWIwSVEZh34oFCADcIJGggB8UAK4UA1hXoB3CgBuZXBoAElCdWAAHgN3RAMoCAAPYAgKABNCKGitXUNjU3MoHChSD2gCADN9QggQvjDyiFMRSOiYmFcgqAB6Ppa2shyKiCaBdOJhRA6NGMEe-sGp4GERqFq9eqA

**Related Issues:** None.

**Comment by MartinJohns** [comment]
Do you have `strictNullChecks` enabled in your project? In the playground it is enabled by default. If you disable it you get the behavior you expect (`testB` being `true`).

**Comment by RyanCavanaugh** [comment]
I don't think this behavior changed between 3.5 and 3.6 - looks like it's just a matter of strictNullChecks or possibly strictFunctionTypes being set differently in the Playground vs your edito

**Comment by Monsooon** [comment]
I haven't token notice of it. Sorry!
