### ISSUE TITLE
Type inference for custom type guards does not use/is not considered in control flow analysis

### ISSUE THREAD

**Issue by nicky1038** [microsoft/TypeScript#33449]
**TypeScript Version:**  3.6.3

**Search Terms:** 

- Custom type guard
- Ternary operator
- Contol flow
- TS2345

**Code**

```
function isNumber(v: unknown): v is number {
    return typeof v === 'number';
}

function isStringOrNumber(v: unknown): v is string | number {
    return typeof v === 'string' || typeof v === 'number';
}

const value = '5' as unknown;

const num = isNumber(value) ? value :
    isStringOrNumber(value) ? Number.parseFloat(value) :
    null;
```

**Expected behavior:**
No errors.

**Actual behavior:**
Compile error when passing `value` to `Number.parseFloat`. TypeScript thinks `value` can be a `number` there, but it actually cannot.
```
example.ts:12:49 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.
```

**[Playground link](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABDAzgORAWwEYFMBOAFAG4Bci4A1mHAO5gCU5xyKiYWe+iA3gFCJBifLigh8SKAE8ADrjjBELALyrEAcg44C6gNx8Avnz6hIsBKwDKUfDDABzAPL4M2omQphqdRs1aIUGzt7RAAfdk4CXgEhETEJRGk5BSVEVWUNQNsHdTDwpPlFFTVNSPw9Q2MIBEClAEMAGxBcNI0AVly6tioaen0+arBarVbUVy4SRuaGRAB+eqaW0hjBVGtspxcyycWZ+fGCADoZOvwUXAAxBrg6qB3pxGWhCIaG3SA)**

**Related Issues:**
#2388

**Comment by jack-williams** [comment]
Requires #29317.

There is currently no way to express negative narrowing's applied to atomic types like `unknown`. You really need `value` to be narrowed to `not number` after the first type-guard.

**Comment by nicky1038** [comment]
@RyanCavanaugh Why duplicate tag? I find this issue requiring #29317 to be implemented and merged but not duplicating it. I expect casting my `value` to `not number` to be done by TS compiler, not by myself. Or are there any similar issues not referenced before?

**Comment by jack-williams** [comment]
The issue #4183 is a more general feature that would subsume this.
