### ISSUE TITLE
keyof keyword type inferring?

### ISSUE THREAD

**Issue by jtenner** [microsoft/TypeScript#33440]
## Search Terms

keyof type inference

## Suggestion

The `keyof` keyword always seems to return `string | number | symbol` which is actually really great for the majority of use cases. It would be great, however, to use the `keyof` keyword with an `interface` so that I could infer that it returns a `string` only.

Given an interface like this:

```ts
interface Example {
  [key1: string]: any; // key1 is the only possible signature in the interface
}

interface SecondExample<T extends Example> {
  // key2 can only be a key of `T` which is garunteed to be a string in Example
  [key2: keyof T]: any; 
}
```

Currently `key2` is highlighted in my IDE with the following error:

```
An index signature parameter type must be 'string' or 'number'.ts(1023)
```

This of course is because `keyof T` returns `symbol` as one of the unioned types, even though that will never happen because `Example` can only have `string` keys.

## Use Cases

In some cases, I would like to define an interface with the same key of an interface, only have different outputs based on the `T[keyof T]` output.

## Examples

```ts
interface Definition {
  [name: string]: Int
    | UInt
    | Float
    | IntArray
    | UIntArray
    | FloatArray
    | Str;
}

interface Result<U extends Definition> {
  [name: keyof U]: U[keyof U] extends Int ? number :
                   U[keyof U] extends UInt ? number :
                   U[keyof U] extends IntArray ? Int8Array | Int16Array | Int32Array | BigInt64Array :
                   U[keyof U] extends UIntArray ? Uint8Array | Uint16Array | Uint32Array | BigUint64Array :
                   U[keyof U] extends FloatArray ? Float32Array | Float64Array :
                   U[keyof U] extends Str ? string :
                   null;
}
```

Currently this example does not compile. The idea is that it would result in an interface with a set of properties that result in either a number, string, or TypedArray value.

Returning a `Result<T>` has no output properties based on `T` and it's because the `name` index expects `keyof U` to be a string or a number.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
> garunteed to be a string in Example

It's not guaranteed.

```ts
interface Example {
  [key1: string]: any;
}

type KeyOfExample<T extends Example> = keyof T;

const sym = Symbol();

//type k = typeof sym | 1
type k = KeyOfExample<{
    1 : "hahaha, I am a number key",
    [sym] : "hahaha, I am a symbol key",
}>
```
[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgKIA84FsAOAbFAbwChlkBtAawgE8BGALmQGcwpQBzAXSbhBoDcxAL7FiYGjhQBpWgHkYGbPggAeACrII6SCAAmzNJlwEAfMgC8yajQD2MZOqHEEtkKxY0sl5AGUvAEa2eAAUAJTOAPSRElLWPrEQ9p7eAD7IdOKSKJQ+sjQKSiZqJGRkdMhMAEQAFnB1dQA0yACSyNjtyCAArlgB0Na0VY2kZeTMXlyVyLX1c81tHXApQXiDNMMipkA)

**Comment by jtenner** [comment]
Yeah it looks like there isn't much we can do about it. Sorry to post an issue. I'll close it.
