### ISSUE TITLE
noImplicitAny allows any types from declarations with errors when using skipLibCheck

### ISSUE THREAD

**Issue by asmundg** [microsoft/TypeScript#33459]
**TypeScript Version:**  3.7.0-dev.20190917

**Search Terms:**
implicit any skiplibcheck

**Code**

Full example: https://github.com/asmundg/typescript-noimplicitany-skiplibcheck-demo

decl.d.ts contents:
```ts
declare var foo: (arg: number) => notatype;

```

index.ts contentx:
```ts
// declare var foo: (arg: number) => notatype;
// Inferred type: var foo: (arg: number) => any
foo(1);

```

**Expected behavior:**

Compiling with --noImplicitAny and --skipLibCheck causes an error in index.ts when type checker fails in decl.d.ts, falling back to using `any` as the return type of `foo`.

**Actual behavior:**

Return type of `foo` silently becomes `any`. This voids the assumption that --noImplicitAny disables the use of `any` as a fallback type.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the trade-off you take when using `skipLibCheck` - if you use functions that aren't error-free, you will get `any` instead.

**Comment by asmundg** [comment]
I had a suspicion that it was by design, but couldn't fint any description of the behavior. Should this gotcha be mentioned in the skipLibCheck documentation?

Also, would it make sense to (optionally?) use unknown instead of any as the default case?
