### ISSUE TITLE
bug: optional property in overload signature prevents type inference

### ISSUE THREAD

**Issue by thefliik** [microsoft/TypeScript#33451]
**TypeScript Version:**  3.5.1

**Search Terms:**

overload bug

**Code**

```ts
class Success<T> {
    constructor(public value: T) {}
}

class Err {
    constructor(public msg: string) {}
}

class Decoder<R, I> {
    constructor(public fn: (value: I) => Success<R> | Err) {}
}

class AsyncDecoder<R, I> {
    constructor(public fn: (value: I) => Promise<Success<R> | Err>) {}
}

interface IsChainOfOptions {
    msg?: string;
}

function isChainOf<A,B>(
  a: Decoder<B,A>,
//   options?: IsChainOfOptions
): Decoder<B, A>;
function isChainOf<A,B,C>(
  a: Decoder<B,A>,
  b: Decoder<C,B>,
  options?: IsChainOfOptions
): Decoder<C, A>;
function isChainOf(
  a: Decoder<any, any>,
  b?: Decoder<any, any> | IsChainOfOptions,
  o?: IsChainOfOptions,
): any {
  return 0;
}

function isString(): Decoder<string, any> {
    return new Decoder((val) => {
        return typeof val === 'string' ? new Success(val) : new Err('not a string');
    })
}

function isMatchForPredicate<T>(fn: (val: T) => boolean): Decoder<T, T> {
    return new Decoder((val) => {
        return fn(val) ? new Success(val) : new Err('error');
    })
}

// expected type is `isChainOf<any, string, string>(): Decoder<string, any>`
isChainOf(isString(), isMatchForPredicate(value => true));
```

**Expected behavior:**

Uncommenting `//   options?: IsChainOfOptions` will have no effect on typescript's ability to infer the type of `isChainOf(isString(), isMatchForPredicate(value => true))`, and typescript can correctly infer that type.

**Actual behavior:**

If you uncomment `//   options?: IsChainOfOptions`, then typescript can no longer correctly infer the type of `isChainOf(isString(), isMatchForPredicate(value => true))`.

If you reverse the order of the overloads, then typescript can correctly infer the return type even with `//   options?: IsChainOfOptions` uncommented.

**Playground Link:** 

https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEDKCuxgFMoB4AqA+aBvAUNEdMAPYB2EALgE6JWk0AUADvAEYgCWw0AbmBDxkALmgYAlHgC++WflCQYAURo08hYmUq16jVh268AthADmY6jS7kzU3LPmKo0ACLIyAE2Q00AJQAaaABJHAJiEgorPWY2Th5oADNyMSYBIVEQqQBeHAQkVAh-HAAfaFUae0d8BXAXAEEIAE9yYHcvH38g0I0I7WjgBljDBOTU9OExYJycAAUaUmMuCGQ0fJR0P1LytSwquRqbKh9EsBQQiABhAAswGwB5RPuWKi4o3uJTMwB+S1obMwAbgO+AA9AAqcGEcEhRLQJqkeDQeCtRbGZDkKjQbjkZDQADMAEYglRrhjoFQmixUMBrC9oSQwORoORSNiKGYfJE1B4qCAmtAbIkuaS8ZTqdBSHCcXiAKwATgAdAyGfUQMcaOQwK8+Mh+UEuHCEUiaMhdTQVhSyZKaN51FKrXjSOaQKQwJ4IAzRcyzT4mqSAdB2MhbrqYJBoMgAB7UwbITzK6Dg0E1RIowZvZnLG53ciPND1AIAISwTE0YDE7VIdrQRYC9SwATBoOIpBemYgvwuOYeT3bUXwEkrHmrnTr0AbwLTrVeFEFV1uvYLxYCl1L5eHHV8dYbTaI7E3o98l2Ljc0bdnlC7wQXucez0vnqHbhHNZPE6wU-Tl-nPbziTLIgKxfLc0CZJognAs99y7Ksa3AyDyCabYbz-e9+0oPdJWvW9ewfDsm2fcCPlNKh4E1aAAAZgXkacMznZZYH+WwmGfODOisAFEOQj4iFI8jmVxAB3ECjyYNJBBmXiImgfiKPFZAHXSaBslU6AAHJONsdToG+FlkBE9ZCgkkApDEYSdmYdTWSxMBoC0sx1IkYEImkCQQTon9lgAWW1YBrgAMUYeZ4x4bVVmwJgxmgEyxEkFScHYUhSBAZAmTY19OgwIJsGkuTBIM0S7XE9IpPCGS+OQMiKOSEypD0iyjKgOroHMwqKiYdSfAWGgnJc4g3JBUEW2jWNjk8CkqTxZZoAAA2zRd-zApCggc1bmLMUsMtAtboCg2b8AWu8AMYjbWINCBfKofygpoELPDC44TOEBKKToZAJGcoA

**Related Issues:** 

- Issue #33101 is possibly related
  - Like that issue, this issue is solved by rearranging the overloads

**Comment by RyanCavanaugh** [comment]
Order does matter for overloads - the "more specific" ones (i.e. longer) do need to always go first. A call that *can* match on an earlier overload always *will*, even if the generic inference turns out different from what you'd like it to be.

**Comment by thefliik** [comment]
@RyanCavanaugh in both cases (i.e. no matter the overload order), the correct overload *is being matched* (as seen via intellisense). The problem does not appear to be related to which overload is matched, but rather what the resulting type inference is.

**Comment by thefliik** [comment]
@RyanCavanaugh I think you misinterpreted this issue and improperly closed it. [See my comment above](https://github.com/microsoft/TypeScript/issues/33451#issuecomment-532424302) clarifying what is happening here.
