### ISSUE TITLE
Cannot subtype Window with an interface (to augment in module scope)

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#33465]
**TypeScript Version:**  Version 3.7.0-dev.20190917

**Search Terms:** window augmentation global interface globalThis

**Code**

```ts
export {}

declare interface MyExtendedWindow extends Window {
  foo: number;
}

const extendedWindow = window as MyExtendedWindow;

let n: number = extendedWindow.foo;
```

**Expected behavior:**

This is a pattern that allows users to augment the global window object locally, for the scope of a module. This avoids polluting the global namespace.

**Actual behavior:**

```
test.ts:5:24 - error TS2352: Conversion of type 'Window & typeof globalThis' to type 'MyExtendedWindow' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'foo' is missing in type 'Window & typeof globalThis' but required in type 'MyExtendedWindow'.

5 const extendedWindow = window as MyExtendedWindow;
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

  test.ts:2:3
    2   foo(x: string): number;
        ~~~~~~~~~~~~~~~~~~~~~~~
    'foo' is declared here.

Found 1 error.
```

This is new in TypeScript 3.6.x+, due to `window` now being `const window: Window & typeof globalThis`.

**Playground Link:** 

[not really applicable, playground is still on 3.5](http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAbwL4CgUBNgGMA2BDKYOASwDsZgoAzPLIgWQE8BREC0zdAdTPQgHc4odugDOcHhwGIUcOFQgQAXHFIBXALYAjSgG4UqFFgilR8YcA7BuvaQF44-W4LzimrEdcl9++lDmB4UhV1bUo4BwsrGyl+ADoFCF0gA)

**Related Issues:**

**Comment by mprobst** [comment]
Workarounds:

```ts
// 1 cast through Window or {}
const extendedWindow = window as Window as MyExtendedWindow;
// 2 global augmentation (but causes name leakage)
declare global {
  interface Window { foo: number; }
}
// 3 create intersection type with window
// This requires a pretty complicated type for what seems like a relatively straightforward problem.
declare interface MyProps { bla: number }
declare type MyExtendedWindow = (typeof window) & MyProps;
// 4 declare a global variable in a module. Not sure if this is even intended to work? Seems hacky.
declare const bla: number;
```

**Comment by j-oliveras** [comment]
Duplicate/related to #33128 (found searching `window` on closed issues).

**Comment by mprobst** [comment]
Whoops, sorry. I searched, but didn't find that :-/
