### ISSUE TITLE
Problem with inferring types that contain null / undefined

### ISSUE THREAD

**Issue by kurone-kito** [microsoft/TypeScript#33461]
**TypeScript Version:**  3.6.3, 3.7.0-dev.20190917

**Search Terms:**

inference, nullable, non-optional, optional property, tsserver, undefined

**Code**

- _index.ts_

```ts
interface Params {
  foo: string | undefined;
}

export default (params: Params) => params.foo;
//     ^---- quickinfo here
```

- _commands.json_

```json
{ "type": "request", "seq": 0, "command": "open", "arguments": { "file": "index.ts" } }
{ "type": "request", "seq": 1, "command": "quickinfo", "arguments": { "file": "index.ts", "line": 5, "offset": 8 } }
```

- _...and do it_

```sh
tsserver < commands.json
```

**Expected behavior:**

```json
// ...(omission)
"displayString": "(property) default: (params: Params) => string | undefined"
// ...(omission)
```

**Actual behavior:**

```json
// ...(omission)
"displayString": "(property) default: (params: Params) => string"
// ...(omission)
```

**Playground Link:** 

https://github.com/kurone-kito/typescript-inference-problem

**Related Issues:**

**Comment by j-oliveras** [comment]
Most likely, you have `strictNullChecks` option to `false` (is the default value).

**Comment by kurone-kito** [comment]
Awesome! Love TypeScript more ❤️
I did not specify `strictNullChecks`, so it was the default value.
