### ISSUE TITLE
JavaScript IntelliSense working  strange。

### ISSUE THREAD

**Issue by lqu3j** [microsoft/TypeScript#33463]
I use `vue create demo` to crete a project. Then I edit `demo/src/main.js`. Here is code:
``` javascript
import Vue from "vue";
import App from "./App.vue";

Vue.config.productionTip = false;

let vm=new Vue({
  render: h => h(App)
});
```
I input `vm.` , Intellisense is not working,  After I delete `Vue.config.productionTip = false;` It will work normally. Or I rename `main.js` to `main.ts` directly, work normally too. I am not sure if this is a bug or have other reasons.

Please forgive my lame English

**Comment by deguich** [comment]
Same problem. 
I tried to disable vetur plugin but no change ... 

Did you found a explanation ?

**Comment by deguich** [comment]
I added this issue ti vscode :
https://github.com/microsoft/vscode/issues/96060
