### ISSUE TITLE
Typeguard wrongly assumed to be always true

### ISSUE THREAD

**Issue by sobkulir** [microsoft/TypeScript#33475]
**TypeScript Version:**  3.5.1
**Search Terms:**
typeguards never true

**Code**
```ts
class A {
  isB(): this is B {
    return this instanceof B
  }

  isC(): this is C {
    return this instanceof C
  }

}

class B extends A {}
class C extends A {}

const cObj = new C()

if (cObj.isB() || cObj.isC()) {
    console.log('why')
}
```

**Expected behavior:**
I'd expect this to compile without issues.

**Actual behavior:**
Compiler assumes that cObj.isB() is always true in the condition.

**Playground Link:**
http://www.typescriptlang.org/play/#code/FAYwNghgzlAECCsDexawJZQEIAoCUAXLAC4AWmGcWyqasATgKbECu9AdieXOu1MRHYhGAewBmsLLQC+wWpgDC+ImQoUFNOg2ZtOqnnwFDREhTLmzQkGJNiMAHsUbsAJnERJZ4aHA0Onru7IliAihrAgAPIARgBWsAC8sOyMAO6wSnhy6BI4UXEAdJi4eLAAPmURMbFFUJmlKFqhfCJgjAVgIgDmOADkqaQAnr1ZskA

**Related Issues:**
---

**Comment by AnyhowStep** [comment]
Your B and C are structurally the same

**Comment by fatcerberus** [comment]
> Your B and C are structurally the same

Yep, as far as the compiler is concerned they are the exact same type.  Therefore TS already knows *a priori* that if the object is not a `B`, it can't possibly be a `C` either.  [The error disappears if you do something to make the types distinguishable.](https://www.typescriptlang.org/play/#code/MYGwhgzhAECC0G8BQ1oEsICEAUBKAXNAC4AWG6MmiKq0ATgKZECudAdsWTGmxEWG2AMA9gDNomGgF8kNDAGE8hUuXLzqtek1YcV3Xv0Ejx86bJlJQkStAYAPIgzYATGPATRRw4dAC80ACIvYQYATwDoGSsoaHV7Rxc3RGgAIzA6P0C0umcIi2BhA2hgAHkUgCtMtgYAd1i8WTRxbFKKgDoMHFxoAB8e4rLyjohFXG7kTQLeYRAGNpBhAHNsAHIaklCV3CQZIA)

Refer to this FAQ entry:
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely
