### ISSUE TITLE
Overloading arrow function return type should allow union type

### ISSUE THREAD

**Issue by joshuaavalon** [microsoft/TypeScript#33482]
**TypeScript Version:**  v3.5.1 (On TypeScript Playground)

**Search Terms:**

Arrow function overload

**Code**

```ts
const foo1 : {
    (a: number): number;
    (a: string): string;
} = (a: number | string): number | string => a;

// Type '(a: string | number) => string | number' is not assignable to type '{ (a: number): number; (a: string): string; }'.
//   Type 'string | number' is not assignable to type 'number'.
//     Type 'string' is not assignable to type 'number'.

const foo2 : {
    (a: number): number;
    (a: string): string;
} = (a: number | string): number & string => a as any;

function foo3(a: number): number;
function foo3(a: string): string;
function foo3(a: number | string): number | string {
    return a;
}
```

**Expected behavior:**

The return value of implementation of overloading arrow function should be `number | string` which is allowed with function.

**Actual behavior:**

TypeScript expect the return value of implementation of overloading arrow function should be `number & string`.

**Playground Link:** 

[Link](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAZiEBGGAuGBvAsAKBvmACgEN0wBXAWwCMBTAJwEoyq76BuXAo0maegJZgA5sz5RBIzjgC+MALw8WNBjAA+4yaOVt1mocIUA+GMWm4A9BZgAVAJ4AHWjADkJdPwN6KKpsf0i3qwMLjACEDBgILDEEBACwmDE1AA2zlAgMFCOzi4YSpHBTDoM7AWeImIVwmUyLgB0ltb49k6u1UG+oeGR0aZxCUmp6ZnZbS4+bA1N3LY57RIG3RFRMQOJyWlZo-MTRdM4uKCQsAggAExomFwE7oW+YpOlN-h31VWLUrhyindP9Hp3iUAQAyAKGeQmYj9UxgOzmHBwchgYBQATgeCIADMfyKjyK0iRKLRGLOON4QPBhORqPRYExIHJwMBn20910AG0ALrXPAEei0KDkej0szfXBAA)

**Related Issues:**

**Comment by IllusionMH** [comment]
This is correct error.
If you check how you should use result of this function (result of the implementation, skip overloads for now because implementation has no knowledge of input->output types mapping) you would expect that implementation will support both of this cases without type errors.
```ts
const a: number = foo1(someNum);
const a: string = foo1(someStr);
```
this can be achieved only by a type that is assignable to `number` and `string` at the same time and this is `number & string`.
If you'll have function that has signature `(a: number | string) => number | string` e.g.
```ts
(a: number | string) => Math.random() > 0.5 ? Number(a) : String(a);
```
then it won't work in case described above.

In case of `foo1` you can use
```ts
const foo1 : {
    (a: number): number;
    (a: string): string;
} = (a: number | string): any => a;
                          ^^^
```
But users will see only 2 correct signatures.

**Comment by joshuaavalon** [comment]
@IllusionMH My problem is the result is not consistent with `function`. 

For example,
```ts
function foo3(a: number): number;
function foo3(a: string): string;
function foo3(a: number | string): number[] | string {
    return a;
}
```

It shows

> This overload signature is not compatible with its implementation signature.

The error is on the overload signature.

However, the error in arrow function overload is on the implementation signature. As a result, function can return `string | number` or `string & number ` without error.

If I use `any`, I will lose the type check on return type.

**Comment by IllusionMH** [comment]
It can't be consistent with functions with current syntax. Function overloads has special syntax and therefore can provide special handling of return types.

Your examples are regular function assignment and without special syntax are indistinguishable from incorrect implementations.

```ts
type Overloaded = {
    (a: number): number;
    (a: string): string;
};

declare function correct(a: number | string): number & string;
declare function incorrect(a: number | string): number | string;

const f1: Overloaded = correct;
const f2: Overloaded = incorrect; // correctly errors
```
You don't want to allow second case.

To request similarity you should create proper feature request/proposal with convincing use cases, instead of using Bug report template.

**Comment by craigphicks** [comment]
I can see no reason not to use the same algorithm which is used for a function overload declaration.  

It's true that the function declaration algorithm would be better if the return values in the implementation were type checked against the signatures in context.  We can even simulate it in user code:

```ts
function foo3(a: number): "num";
function foo3(a: string): "str";
function foo3(a: bigint): never;
function foo3(a: number | string | bigint): "num"|"str";
function foo3(a: number | string | bigint): "num"|"str" {
    if (typeof a === "string"){
        const ret = "str";
        // Conceptual simulation of type checking
        // Unfortunately we cannot write typeof foo3(a) in user code, 
        // but that lookup can be done in typescript internals.
        // Obviously would not deliberately enter infinite loop.
        const testret = foo3(a); 
        ret satisfies typeof testret;  // OK
        return ret;
    }
    else if (typeof a === "number"){
        const ret = "num";
        const testret = foo3(a);
        ret satisfies typeof testret; // OK
        return ret;
    }
    else if (typeof a === "bigint"){
        const ret = "num";
        const testret = foo3(a);
        ret satisfies typeof testret; // error
//          ~~~~~~~~~
//Type 'string' does not satisfy the expected type 'never'.(1360)
        return ret;
    }
    throw undefined;  // a==="bigint" should take this branch.
}
```

The obvious solution then is to unify the treatment of function declarations and assignment of arrow functions to overloads types,
and ALSO upgrade BOTH with the above return value checking.  This same reasoning applies to generic functions as well.

Setting the return type of the implementation with the intersection of return types just breaks the existing type checking (which although not perfect is still better than nothing).

**Comment by mp3por** [comment]
How is it possible that the "correct" function returns `string & integer` at the same time ? The `type C = A & B` in TS is used to tell the compiler that the variable of type C will be both A and B at the same time, correct ?
