### ISSUE TITLE
Typescript Compiler is unable to check whether relational operator is supplies to decision making statement(if ,else if)

### ISSUE THREAD

**Issue by nkch8054** [microsoft/TypeScript#33485]
Hi,
Thanks to typescript team for creating wonderful client side scripting language based on OOP's features. Typescript compiler is unable to check whether relational operator is supplies to decision making statement(if ,else if). Developer may make a mistake while supplying relational operator to decision making statement  . Usually they can supply assignment operator in place on equality operator. Thanks you!

**Comment by orta** [comment]
Thanks for the issue, can you please re-create this issue and follow the template, it's hard to understand what is actionable on our side with that structure.

**Comment by nkch8054** [comment]
Please
