### ISSUE TITLE
Logically equivalent functions return different Types when return is a `Promise | non Promise`

### ISSUE THREAD

**Issue by lonewarrior556** [microsoft/TypeScript#33499]
**TypeScript Version:**  3.2.x -> 3.5.x

**Search Terms:**
Typescript Promise async inconsisent

**Code**
[ts-playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoE8AOECMyDeAUMsnAFzIDOYUoA5gNyEC+hhoksiKG2ATAWKkK1WiEZCARhRABXALaToTVgHpVAWi3aduvdsIIA9iGrIYskAjwBeZAAo4UOhTgh0ASmQ2AfIJIAbk6k3sgAClBG8sCUEAB0UBCURgA2ARD2+MyklGhYuB5MgcGSoRFRMfGJyWkZWTl5-IVsJIlgslAgpM7IAPwhFJIMyOrhkdGxADy8uD4sTIYmZhZWOACClOhWoXCb247Oru5evv7IQVAhduUTVUmp6ZnZu40FReclZeOVCfe1Tw0ZnxmkI2h0uk46H0BsghiNVGMKlMZjg5swmOp9FjsYtTGBzJYEAI7AcXKRjt4-EQSCRjHiCdsSScqUIaTSLlcCM9cij3mzipdSnZ6i8gQt+TSwZ1ulD+nBkINhqzkKw2VKujcftUHhkPHEwAALCAgewrBBeUaa5H5VHzNh05aEvgbLYIHZ7N2ko6eSlnDny4Xc144d4coVcwH5Pji5DqmXQ+WK+GI27TG1ojGabHZnS4x1WADMoS95J9p2pNId+LNxeZZwl-tCIp5Nr5-LDXyRdxqj2br2BMYlcchCYVsKVbNVkog7WlVu7OvsesNxtNhItCLA+WQ0EiUDteerhILLsZOVdDkh3rrFcbgcj2BDQg712+sV+PbqQaBINaM-B8ZymOcKWm+EBpo+yAAD79hmhBAA)

```
interface Type1 {
  a: string;
}

interface Type2 {
  a: string;
  b: number;
}

const func1 = (arg: any) => {
  var a = Promise.resolve({} as Type1);
  var b = Promise.resolve({} as Type2);

  return arg ? a : b; // Promise<Type1>
};

const func1Async = async (arg: any) => {
  var a = Promise.resolve({} as Type1);
  var b = Promise.resolve({} as Type2);

  return arg ? a : b; // Promise<Type1>
};

const func2 = (arg: any) => {
    const func = () => {
        var a = {} as Type1;
        var b = {} as Type2;

        return arg ? a : b; 
    }
    return Promise.resolve().then(func) // Promise<Type1>
};

const func2Async = async (arg: any) => {
  var a = {} as Type1;
  var b = {} as Type2;

  return arg ? a : b; // Promise<Type1>
};

const func3 = (arg: any) => {
    const func = () => {
        var a = {} as Type1;
        var b = Promise.resolve({} as Type2);

        return arg ? a : b; 
    }
    return Promise.resolve().then(func) // typeError
};

const func3Async = async (arg: any) => {
  var a = {} as Type1;
  var b = Promise.resolve({} as Type2);

  return arg ? a : b; // Promise<Type1 | Type2>
};
```

**Expected behavior:**
Unless I made a mistake. Everyone of these function is equivalent. They should have equivalent type signatures

**Actual behavior:**
The return types differ and some have type errors.

This was an actual headache to fix. The logic apparently only works properly inside `func3Async` 
I can maybe live with typescript thinking the first return type is the return type of the function since that mistake is at least consistent. However func3 should not be type erroring.

**Playground Link:** 
http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoE8AOECMyDeAUMsnAFzIDOYUoA5gNyEC+hhoksiKG2ATAWKkK1WiEZCARhRABXALaToTVgHpVAWi3aduvdsIIA9iGrIYskAjwBeZAAo4UOhTgh0ASmQ2AfIJIAbk6k3sgAClBG8sCUEAB0UBCURgA2ARD2+MyklGhYuB5MgcGSoRFRMfGJyWkZWTl5-IVsJIlgslAgpM7IAPwhFJIMyOrhkdGxADy8uD4sTIYmZhZWOACClOhWoXCb247Oru5evv7IQVAhduUTVUmp6ZnZu40FReclZeOVCfe1Tw0ZnxmkI2h0uk46H0BsghiNVGMKlMZjg5swmOp9FjsYtTGBzJYEAI7AcXKRjt4-EQSCRjHiCdsSScqUIaTSLlcCM9cij3mzipdSnZ6i8gQt+TSwZ1ulD+nBkINhqzkKw2VKujcftUHhkPHEwAALCAgewrBBeUaa5H5VHzNh05aEvgbLYIHZ7N2ko6eSlnDny4Xc144d4coVcwH5Pji5DqmXQ+WK+GI27TG1ojGabHZnS4x1WADMoS95J9p2pNId+LNxeZZwl-tCIp5Nr5-LDXyRdxqj2br2BMYlcchCYVsKVbNVkog7WlVu7OvsesNxtNhItCPnaewtvR9qW1cJBZdjJyrockO9dYrjcDkZ3oc+12+sV+PbqQaBINaM-B8blY5wpaL4QNuuDIAAPv2GaEEAA
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
There's no error in the Playground?

**Comment by lonewarrior556** [comment]
type error is fixed with 3.6.3 (was not available in the playground at the time)

The type mismatch with `func3Async` still exisits

**Comment by RyanCavanaugh** [comment]
The problem here is that you have two types (`Type1` and `Type2`) that are subtype-relatable, so certain operations that reduce unions of the form `T | U` to `T` when `U` is a subtype of `T` trigger under certain conditions and not others. Ultimately this is really a type *display* issue; when these types are used in practice they're converted to their reduced forms. Adding a disjoint member to `Type1` causes behavior closer to what you might expect.

**Comment by lonewarrior556** [comment]
Here is an additional simpler example:

http://www.typescriptlang.org/play/?ts=3.6.3&ssl=9&ssc=3&pln=1&pc=1#code/MYewdgzgLgBAZiEMC8MAUBDAXDDYCeAlCgHwwAKATiALYCWEApgHSWMQgA2Abo5ocygALRmDRsIAB1IwA3gCgYMOnHQTJxBUqVsoAV0pgYAcmiU6YAObHFMAL4xGnJnNs7G+wxWr0mrdly8aALCouLs0shkWtrunkYAjAAMSQDcbvaEtnbydoRAA

```
const foo = (a: any) => Promise.resolve(a).then(resp => {
  if (resp) {
    return 'string'
  } else {
    return Promise.resolve().then(resp => {
      return 100;
    })
  }
})
```

yields error:
```
Argument of type '(resp: any) => "string" | Promise<number>' is not assignable to parameter of type '(value: any) => number | PromiseLike<number>'.
  Type '"string" | Promise<number>' is not assignable to type 'number | PromiseLike<number>'.
    Type '"string"' is not assignable to type 'number | PromiseLike<number>'.
```

Adding `async` fixes everything
```
const foo = (a: any) => Promise.resolve(a).then(async resp => {
  if (resp) {
    return 'string'
  } else {
    return Promise.resolve().then(resp => {
      return 100;
    })
  }
})
```
