### ISSUE TITLE
Typescript Compiler is unable to check whether relational operator is supplies to decision making statement(if ,else if)

### ISSUE THREAD

**Issue by nkch8054** [microsoft/TypeScript#33494]
Hi Team,
Thanks  typescript team for creating wonderful scripting language based on OOP's features. Typescript compiler is unable to check whether relational operator is supplies to decision making statement(if ,else if). Developer may make a mistake while supplying relational operator to decision making statement . Usually developer may supply assignment operator in place on equality operator. 

When I write the decision making statement  like below 
if(var variable=5){
//some code
}

Expected behavior:
The above code must show compiler error  that "if" statement only accept relational operator you are supplying an assignment operator .

Actual behavior:
It got compile . But at run time the value 5 is got assign to the variable it stops executing next block of code statement.

Thanks & Regards

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.
