### ISSUE TITLE
Regression for inferred unions in generic parameters

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#33490]
**TypeScript Version:**  3.7.0-dev.20190918

**Search Terms:** infer generic

**Code**

```ts
// simpler react types
declare class Component<P> {
  props: P;
}

export type ComponentClass<P> = {
  new (props: P): Component<P>;
};

export type FunctionComponent<P> = (props: P) => null;

export type ComponentType<P> = FunctionComponent<P> | ComponentClass<P>;

// simpler react-router.d.ts
export interface RouteComponentProps {
  route: string;
}

declare function withRouter<
  P extends RouteComponentProps,
  C extends ComponentType<P>
>(
  component: C & ComponentType<P>
): ComponentClass<Omit<P, keyof RouteComponentProps>>;

interface Props extends RouteComponentProps {
  username: string;
}

declare const MyComponent: ComponentType<Props>;

// If I define `ComponentType` as `ComponentClass<P> | FunctionComponent<P>`:
// Argument of type 'ComponentType<Props>' is not assignable to parameter of type 'ComponentClass<Props> | (ComponentClass<Props> & FunctionComponent<Props>)'.
// If I define `ComponentType` as `FunctionComponent<P> | ComponentClass<P>`:
// Argument of type 'ComponentType<Props>' is not assignable to parameter of type 'FunctionComponent<Props> | (FunctionComponent<Props> & ComponentClass<Props>)'.
withRouter(MyComponent);

```

`C & ComponentType<P>` helps inference. For a more comprehensive test suite check the react-router [declarations](https://github.com/eps1lon/DefinitelyTyped/blob/f4bb693c1170041ad3448a093aa97c2bd47c16e3/types/react-router/index.d.ts#L148) and [tests](https://github.com/eps1lon/DefinitelyTyped/blob/69cd1a3de889ee9bf252d0f2aadc39dce4bc24f2/types/react-router/test/WithRouter.tsx#L8-L9)

A fix getting rid of `C & ComponentType<P>` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38326) caused issues when using `strictFunctionTypes` 

**Expected behavior:**
No type error

**Actual behavior:**
Throws with a different error message depending on the order of the union members in `ComponentType`

**Playground Link:** 
[playground for 3.5.3](http://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgJQgFdUBhCAW0iWBQAUoIwBnOAbwFgAoOORk4AC44zGFGQBzANzcAvt24ATYNgA2mKHjWZmrclQg0UAHjoA+dt15hGLYXRld5XbqEiw4MAJ5g8+6rQwpOq6phYAvJY8cDQA7nAAFDZMzPYAlML+hoFhjrKOruDQ8N6+cABiREjYMAiGWUYwYXCRSbapcHRpLRZIRKqqBVxuxZ4+fpQBKAAq482RldW19ZPZJuZwAD5wDYHBOsy5ClwA9Cdw0wAWaHgIrJhwANZIELFIiLpEt++zvgDK2HEYBgABo4LFLghsJc4IoIMBmEgAOTwTADV6wlTQTAwaCsXFwaGYJASPAwa4iBASJA4oiaOAQdCeCnaXQI7hnZnALxwDR4ZTYbG1EkAOjgABEvp4IMy7mCEEyvMRefSiMxJHAAAKxBDkwgCKCYwVQHHQRDvJV0wkQZQgjnnS3ghADETAPAPABGVWhDKZaEYUFY6EYFAu4wBQJgYquWjpmhQ4Ogjw0xCQig+0rgarwOr1xFQUAS3R0vLg6G9y3e2DRqntDPeD2YwDAGhxeFUyG+omAmHTjN59yNQugIqUKnU9PLSzq71zl31BeMVk6cFAqDTrAXwF29HaduipFXIHXij0q0av2AYW4ZgSy8FBkamTgADIdufApfr1wMu-H3sQkOAB5ChdVMMFHm5fstx3GAGBSMwzCGZACywXBOnaI8T03fNtw-XcUiiXhsygGkKCEEQxEkPJjgFCctEMUQ4AAWS8WDMnwmAv3glgkOOTkAEkmQEzF0E7OAAANYMvCSB0k2D9lCDZtkWGoZ1gsIJMEOsAEEoAkIhyITftSjwJFpLmHjmDMJEMxeVFdCpGkPVUMkZRbE1yILX0xjKczOMUw4rIsbYEgUwDTHaCw31UysNOCtIkVHU5ziEuAROUMSaHkziZLkiTYvUzjmm2cKDk07SUrgPSDKM+ATPGOB-P-GZLKi2y7hiCAHPValMBcty4A8zAvLQHzTKawqVhappgq2RIpqQeKotfP8piCCKEqS7g5y3QtWNgtJHCAA)

**Related Issues:** 
* #33278
* Originally reported in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38271

/cc @OliverJAsh

**Comment by eps1lon** [comment]
Oh and 

```diff
-component: C & ComponentType<P>
+component: C & (C extends ComponentClass<P> ? ComponentClass<P> : FunctionComponent<P>)
```

fixes any error and passes the full test suite down until 3.0. 3.1 and above will pass while 3.0 will fail.

**Comment by waynebloss** [comment]
I'm just trying to use jsdoc in vscode (v1.38.1) to document types and the following doesn't work. Is this the same bug?

My issue is that Intellisense shows `function xxx(yyy: any): any` for:
```js
/** @param {string | number | (zzz:string)=>string} yyy */
function xxx(yyy) {
  return yyy;
}
```
Intellisense shows `function xxx(yyy: (zzz: string) => string): (zzz: string) => string` for:

```js
/** @param {(zzz:string)=>string} yyy */
function xxx(yyy) {
  return yyy;
}
```
Intellisense shows `function xxx(yyy: string | number): string | number` for:
```
/** @param {string | number} yyy */
function xxx(yyy) {
  return yyy;
}
```

**Comment by j-oliveras** [comment]
@waynebloss your first code should be wrote as (see the parenthesis around lambda):
```ts
/** @param {string | number | ((zzz:string)=>string)} yyy */
function xxx(yyy) {
    return yyy;
}
```

**Comment by weswigham** [comment]
I suspect this regressed because of #32558.

**Comment by ahejlsberg** [comment]
Simpler repro:

```ts
type AB<T> = { a: T } | { b: T };

// T & AB<U> normalizes to T & { a: U } | T & { b: U } below
declare function foo<T, U>(obj: T & AB<U>): [T, U];
declare let ab: AB<string>;

let z = foo(ab);  // Expect [AB<string>, string]
```
