### ISSUE TITLE
Generic for abstract class

### ISSUE THREAD

**Issue by hasezoey** [microsoft/TypeScript#33491]
I know [this has been discussed](https://github.com/microsoft/TypeScript/issues/5843), but i couldnt find a solution in these issues, so my use case is as following:

```ts
abstract class SomeClass {
  public array: object[]

  public async addCar<T extends SomeClass>(this: InstanceType<T> & mongoose.Document, car: object) {
    this.array.push(car);
  }
}
```

throws an typescript errors because `An abstract constructor type can not be assigned to a non-abstract constructor type ts(2344)`, but `InstanceType<T> & mongoose.Document` cannot be replaced by something like `Function`, so i wanted to ask if there is currently a solution to this

using:
- typescript 3.6.2
- node 12.10.0
- @types/node 8.10.53
- target: es6
- lib: esnext

---

PS: sorry if this is an question that should be on SO

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.

**Comment by hasezoey** [comment]
> This is the intended behavior.

why is this "as intended"? when using an abstract class as an base / "extends" it should work, shouldnt it?

**Comment by RyanCavanaugh** [comment]
If it was allowed abstract classes to be assignable to non-abstract construct signatures, then you could instantiate an abstract class through a trivial indirection.

**Comment by hasezoey** [comment]
is there then a workaround?
