### ISSUE TITLE
Partial allows non-existing properties in combination with object spread

### ISSUE THREAD

**Issue by TkDodo** [microsoft/TypeScript#33506]
**TypeScript Version:**  3.5.1

**Search Terms:**

Partial, Object Spread, Unknown properties

**Code**

```ts
type State = {
  foo: string
  bar: number
}

const x = { foo: 'foo', nonExisting: true }

const y: Partial<State> = {
  ...x,
}
```

**Expected behavior:**

A compile error, similar to what you get when you do:
`const y: Partial<State> = { foo: 'foo', nonExisting: true }`

```
Type '{ foo: string; nonExisting: boolean; }' is not assignable to type 'Partial<State>'.
  Object literal may only specify known properties, and 'nonExisting' does not exist in type 'Partial<State>'
```

**Actual behavior:**

No error - we can just assign non existing properties to objects this way.

**Playground Link:**

https://www.typescriptlang.org/play/#code/C4TwDgpgBAysCGxoF4oG8CwAoKUBmA9gQFxQDOwATgJYB2A5trgEbyWm0CuAtsxJdgC+2bAGMCtClAAeUVGnxFSAckIFlAGii0JAUWnUKdeqSqdowrGIlSQpAAptg1eABsAPHEQQAfHPRMUAB0IdIaQkA

**Related Issues:**

Maybe this one: #29701

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Excess property checks never occur when there is indirection like this.

**Comment by TkDodo** [comment]
> Excess property checks never occur when there is indirection like this.

You are right - this is also the behaviour when using `State` instead of `Partial<State>`, so it has nothing todo with `Partial`.

Is there a reason for this? Not that I prefer `flow` to `TypeScript`, but you will get an error in `flow` when using strict objects:

https://flow.org/try/#0C4TwDgpgBAysCGxoF4oG8A+AoKUBmA9gQFxQDOwATgJYB2A5gDQ5QBG8lptArgLasRKWDAF8sWAMYFaFKAA8oqNPiKkA5IQJrGUWtICic6hTr1SVbtDGTpskKQAkMABbxIAHjiIIAPkXoWADpguWYRIA

**Comment by RyanCavanaugh** [comment]
Types are closed by default in flow. See Exact Types #12936 for the corresponding feature request in TS

**Comment by TkDodo** [comment]
Thank you for the explanation!
