### ISSUE TITLE
Wrong type narrowing for variable updated in inner scope

### ISSUE THREAD

**Issue by disovi** [microsoft/TypeScript#33513]
**TypeScript Version:**  3.7.0-dev.20190919

**Search Terms:**
variable, type inference, narrowed, lost
**Code**

```ts
let a: boolean = false;
const modifyA = (): void => {
  a = true;
};
modifyA();
if (a) { // a is inferred as false
  console.log('a is true');
}
```
I'm not sure if it can lead to something bad inside typescript, but it creates problem for typescript-eslint (check related issue). 

**Expected behavior:**
a is inferred as boolean

**Actual behavior:**
a is inferred as false

**Playground Link:** 
https://www.typescriptlang.org/play/#code/DYUwLgBAhgXBBGB7RooDsIF4IDMrAGcQBuAKAGNE0DIBbRAEwEscBPAQSwgAoBKOAG6ImDLAD4IAb1IRoXMACcAriVIBfMvWZt2fMix5ReUiAHpTcpgQhM0OEAoUhRUa3kIgZEStRQgAdMCIAObcAORQEADurhBaLEzOYbxkaqRAA

**Related Issues:** 
https://github.com/typescript-eslint/typescript-eslint/issues/989

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/9998

**Comment by disovi** [comment]
Sure, sorry for duplicate
