### ISSUE TITLE
Return type of async functions which return un-awaited promises

### ISSUE THREAD

**Issue by jeff3yan** [microsoft/TypeScript#33516]
I'm not sure if it's possible to get an unresolved promise out of an async function. I understand that async produces a new `Promise().then()...` chain.

**Code**

```ts
async function getNumber(): Promise<number> {
  return 5;
}

async function getUnawaitedPromise(): Promise<Promise<number>> {
  // await for other functions here
  return getNumber();
}
```

**Expected behavior:**
```ts
const unawaitedPromise: Promise<number> = await getUnawaitedPromise();

// Eventually await the promise
```
Awaiting the function should return a promise which has not yet been resolved. This is because eventually the function `getNumber()` may return another type which extends the promise interface.

**Actual behavior:**

**Playground Link:** 
[Provided](http://www.typescriptlang.org/play/#code/IYZwngdgxgBAZgV2gFwJYHsIwOYFNkByCAtgEa4BOAFAJQBcMAChesaiLgDwQnkUB8MAN4AoGDAr4EFLAFYA3CIC+IkaEixEKDFjzIAqhGAB3YKmS4AJs1btctBjbYdOTu916V+g0eID0fjAmZsjw6BQw6MgAFpTwSFBomCAwsZJiElIyOPhEZJS0iipq4NDx2pgwxGYQtMIZ4lDJoUjB5lZuHI4szlw8+QIwALxBpuY5BkZjFtY9doXKIkA)

**Related Issues:**
This question looked similar:
https://stackoverflow.com/questions/43881192/returning-a-promise-in-an-async-function-in-typescript

**Comment by AnyhowStep** [comment]
No. Your best bet is to wrap it in another object.
```ts
async function getNumber(): Promise<number> {
  return 5;
}

async function getUnawaitedPromise(): Promise<[Promise<number>]> {
  // await for other functions here
  return [getNumber()];
}

async function main() {
    const unawaitedPromise: Promise<number> = (await getUnawaitedPromise())[0];
    unawaitedPromise.then(console.log)
}
main();
```

[Playground](http://www.typescriptlang.org/play/#code/IYZwngdgxgBAZgV2gFwJYHsIwOYFNkByCAtgEa4BOAFAJQBcMAChesaiLgDwQnkUB8MAN4AoGDAr4EFLAFYA3CIC+IkaEixEKDFjzIAqhGAB3YKmS4AJs1btctBjbYdOAbSd3uvSvwC6g0XEAeiCYEzNkeHQKGHRkAAtKeCQoNEwQGETJMQkpGRhXPSIySlpfRRU1cGhk7UwYYjMIWmEc8Sh0yKRw8ysPDkcWZy4eEoEYAF4YKh7IvUNZvqG7WhpXAAZytphu017rZY4AOgTcZo6IEHQAG1wj6-RsGmURRtRmmnkgA)

This isn't a TypeScript question. It's a JS question.

**Comment by jeff3yan** [comment]
Thanks, that's perfect
