### ISSUE TITLE
Intersections of types that do not have intersection do not collapse to never correctly

### ISSUE THREAD

**Issue by SCLeoX** [microsoft/TypeScript#33517]
**TypeScript Version:**  3.6.2

**Search Terms:**
TypeScript intersection collapse never auto narrowing auto collapse
**Code**

```ts
export type RuntimeValue = {
  type: 'number',
  value: number,
} | {
  type: 'boolean',
  value: boolean,
} | {
  type: 'string',
  value: string,
};

const a: RuntimeValue & { type: 'number' } = blackBox();

Math.abs(a.value);
```
**Expected behavior:**
No error, since the only intersection between { type: 'number' } and RuntimeValue is `{ type: 'number', value: number }`.

**Actual behavior:**
Error thrown on `Math.abs`.
`Argument of type 'string | number | boolean' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.ts(2345)`

**Playground Link:** 

**Related Issues:** 

P.S.

The type of a is:

```
({
    type: "number";
    value: number;
} & {
    type: "number";
}) | ({
    type: "boolean";
    value: boolean;
} & {
    type: "number";
}) | ({
    type: "string";
    value: string;
} & {
    type: "number";
})
```

which should collapse to

```
{
    type: "number";
    value: number;
} | never | never
```

which should be equivalent of

```
{
    type: "number";
    value: number;
}
```

Thus a.value should be number

**Comment by jack-williams** [comment]
In light of #33498
```ts
{
  type: 'number',
  value: number,
} | {
  type: never,
  value: boolean,
} | {
  type: never,
  value: string,
};
```
this should narrow under `.type === 'number'`.

**Comment by dragomirtitian** [comment]
@jack-williams Hm, it does not work in the nightly on the [playground](https://www.typescriptlang.org/play/index.html?ts=Nightly#code/KYDwDg9gTgLgBDAnmYcBKBXAdjAlgW2ADUBDAGw1QF44BvAKDgWWAC44ByLDfAI2CgcANIzgA3cpXbc+AkQF84AHzqikKdh14QIZYCSzDREimzjbd+rAuWqm6sxwDOMKLiwBzI0xNS4Lt08FAG56egATYABjMhIoVCiILBc4EnZMHAJiSVQAMjpmDU4ZfkE4eTCAWRIYAAsAOhJeJwAKEnqHOCpuuAAiEoFeuAB+VPrfVHYABgBKYKA) 😕

Either way just the act of intersecting will not narrow the type to what OP desires. Even if such a simplification would be considered I'm not sure what the rule would be, maybe something like: If a discriminating property is `never` remove it from the union. Not sure what else that would break.

`Extract` is the way to go here IMO.

**Comment by jack-williams** [comment]
Yeah it's not in the nighly...

but that is a moot point because it doesn't wory anyway as I just checked. The new PR works with `never` provided you have at least two defined cases. So this works:
```ts
function foo(x: RuntimeValue & ({ type: 'number' } | { type: 'string' })) {
    if (x.type === "number") {
        x.value // number
    } else {
        x.value // string
    }
}
```

but this doesn't:
```ts
function foo1(x: RuntimeValue & ({ type: 'number' })) {
    if (x.type === "number") {
        x.value // number | string | boolean
    } else {
        x
    }
}
```
This is an unfortunate artefact of the definition of `isDiscriminantProperty`.

> If a discriminating property is never remove it from the union. Not sure what else that would break.

This is what the new PR does, but only if the union is a discriminant union, which doesn't occur if you only have one defined case. That is abit weird, and I might look into handling the singular case.

Either way, this narrowing is lazily done upon access via discriminant, and not eagerly to the type.

In that regard `Extract` is better.

**Comment by SCLeoX** [comment]
I totally forgot about the existence of `Extract`. Using `Extract` does work, so thank you.

Should I leave this issue open? I mean, I do feel `{ type: never, value: number }` should collapse to never.

**Comment by jack-williams** [comment]
> Should I leave this issue open? I mean, I do feel { type: never, value: number } should collapse to never.

This has been discussed and declined: #26537. Laziness of object members is a key component in the implementation of the language. So if you feel like your original issue has been resolved I would close this up.
