### ISSUE TITLE
An update in a project reference dependency does not update diagnostics in IDE

### ISSUE THREAD

**Issue by calebmer** [microsoft/TypeScript#33514]
**TypeScript Version:**  3.6.3

**Search Terms:** project references, vscode, dependency, update, IDE, errors

I observed this issue in VSCode, but I assume it’s an issue with the TypeScript language server.

Steps:

1. Create projects A and B. A should have a project reference dependency on B.
2. Import a function from B into A and call that function. Open both files in VSCode.
3. Change the parameter type of the function in B to `never`.
4. Build project B from the command line.

**Expected Result:**

See an error in project A because you are calling a function in B with a parameter type of `never`.

**Actual Result:**

No new errors in project A.

---

Interestingly, when I open the `.d.ts` file generated for project B, then project A will update and I’ll see the errors in VSCode.

**Comment by sheetalkamat** [comment]
Should be fixed by #32028
