### ISSUE TITLE
"done" property of IteratorResult interface incorrectly being typed as "boolean | undefined"

### ISSUE THREAD

**Issue by acdibble** [microsoft/TypeScript#33519]
**TypeScript Version:**  3.7.0-dev.20190919

**Search Terms:**
IteratorResult done boolean | false
**Code**

```ts
const fn = <T>(it1: IterableIterator<T>, it2: IterableIterator<T>): boolean => {
  return it1.next().done && it2.next().done;
};
```

**Expected behavior:**
It compiles without error. The ECMAscript spec for the [IteratorResult interface](https://tc39.es/ecma262/#sec-iteratorresult-interface) defines the `done` property as either `true` or `false`. VS Code (1.37.1) doesn't flag this as an error, just when compiling.
**Actual behavior:**
```$ ./node_modules/.bin/tsc
index.ts:2:3 - error TS2322: Type 'boolean | undefined' is not assignable to type 'boolean'.
  Type 'undefined' is not assignable to type 'boolean'.

2   return it1.next().done && it2.next().done;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

```
**Playground Link:** 
http://www.typescriptlang.org/play/?ts=Nightly#code/MYewdgzgLgBAZmGBeGAeAKgPgBQEsoCMAXDAJJQCmATgIYBGANhedTVCFRpgDQz4BMJFrUbNKtdpywBKEnRAgmNREkwwA3gCgYMKhSgBXKonwEAdGAoAPKNmlmAJuAowAZK75R+F67ftPLAG5NAF9goA
**Related Issues:**

**Comment by yortus** [comment]
It's valid for the `done` property to be absent from the object (i.e. undefined). It says so in the spec you linked:

> If a done property (either own or inherited) does not exist, it is consider to have the value false.

**Comment by acdibble** [comment]
Is this ever the case for the built in generator function though? Is there an iterator result that can specify that the `done` property will always be present or does this require a customer interface then?

If that's the proper path forward then this can be closed, but it seems like if we can be certain that the `IteratorResult` is going to come from a generator function, then we can also be certain that the `done` property will be present.

**Comment by kitsonk** [comment]
> Is this ever the case for the built in generator function though?

But you don't have to have utilise the synatical sugar of a generator function to be able to have something that behaves like a generator, so `IteratorResult` type needs to match the spec.

**Comment by acdibble** [comment]
```typescript
function* gen() {
  yield 1;
  yield 2;
  yield 3;
}

const fn = (): boolean => {
  const it1 = gen();
  const it2 = gen();

  return it1.next().done && it2.next().done;
};
```
[Link](http://www.typescriptlang.org/play/?ts=Nightly#code/GYVwdgxgLglg9mAVAAgOYFMwAoCUyDeAUMsgJ4zoA2AJsgIwDcxZFNyATEyeVbQMxMAvoUIQEAZyjJgYZAF5kuAFzIARnDiV0AQ1lyAfAWZiwk5DCh15aTLi7ITZi+2sZsOJswBO6KCC+yFnQAdGDoAB5QuMHUCOjIAGQJ5lDsoRFRODFxQkxAA)

This example is closer to the issue I was encountering. You can see on the TypeScript playground, that generators implement this return type which isn't necessarily true for them. I can agree that an `IteratorResult` being passed into a function should match spec exactly, but is it possible to more closely match a built-in generator function's return type?

**Comment by kitsonk** [comment]
The spec says it can be `undefined` and still be valid.  You can hand craft an iterator, that returns an iterator result, that doesn't have to contain `.done`.  It means that while all the runtimes you are using always define `.done`, it doesn't mean that that behaviour has to be that way according to the spec, so TypeScript is ensuring that your code is safe against the spec, not against the potential runtime behaviour.

**Comment by acdibble** [comment]
Alright, fair enough, thanks.
