### ISSUE TITLE
Renaming a symbol used as a default argument in a destructured object function argument incorrectly applies property renaming

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33518]
From https://github.com/microsoft/vscode/issues/80521

**TypeScript Version:** 3.7.0-dev.20190919

**Search Terms:**
- rename
- destructured
- default value

**Repo**
For the JavaScript:

```ts
const FOO = true;
function f({ v = FOO }) {  }
```

1. Rename `FOO` on the first line too `BOO`

**Expected behavior:**
The default value is renamed in the function declaration:

```js
const BOO = true;
function f({ v = BOO }) {  }
```

**Actual behavior:**
End up with the invalid code:

```js
const BOO = true;
function f({ v = FOO: BOO }) {  }
```

**Comment by IllusionMH** [comment]
Any objections if I take this issue?

**Comment by RyanCavanaugh** [comment]
@IllusionMH would be happy to get a PR. Thanks!

**Comment by IllusionMH** [comment]
Fix is ready for review. I hope that there is time to fit it to 3.7 instead of currently assigned 3.8.

**Comment by RyanCavanaugh** [comment]
Thanks @IllusionMH ! Sorry for the delay 🐌
