### ISSUE TITLE
Duplicate definitions for simple file that uses module.exports

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33520]
From https://github.com/microsoft/vscode/issues/80678

**TypeScript Version:**  3.7.0-dev.20190919

**Search Terms:**
- 

**Repo**
For the JavaScript:
```js
module.exports.test = async () => {
    return 123;
}

module.exports.test();
```

Run `go to definition` on `test` in `test()`

**Expected behavior:**
It returns a single definition for the function

**Actual behavior:**
Two definitions are returned

```
[Trace  - 6:36:34 PM] <semantic> Sending request: definitionAndBoundSpan (260). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/m1.js",
    "line": 5,
    "offset": 17
}
[Trace  - 6:36:34 PM] <semantic> Response received: definitionAndBoundSpan (260). Request took 2 ms. Success: true 
Result: {
    "definitions": [
        {
            "file": "/Users/matb/projects/san/m1.js",
            "start": {
                "line": 1,
                "offset": 16
            },
            "end": {
                "line": 1,
                "offset": 20
            },
            "contextStart": {
                "line": 1,
                "offset": 1
            },
            "contextEnd": {
                "line": 1,
                "offset": 20
            }
        },
        {
            "file": "/Users/matb/projects/san/m1.js",
            "start": {
                "line": 1,
                "offset": 23
            },
            "end": {
                "line": 3,
                "offset": 2
            }
        }
    ],
    "textSpan": {
        "start": {
            "line": 5,
            "offset": 16
        },
        "end": {
            "line": 5,
            "offset": 20
        }
    }
}
```

**Related Issues:** 
- #33428

**Comment by elibarzilay** [comment]
@RyanCavanaugh suggested dropping a definition result if it's a parent of another, but this is not the case here.

I talked to @armanio123 who worked on this code in the past, and he noted that the same behavior is done on purpose in similar cases (some are even tested for the multiple results).  Some examples:

    let test = (() => { return () => {} })();
    test();

    let foo1 = () => 1, foo2 = foo1;
    foo2();

    // this is from an existing test
    const Bar;
    const Foo = Bar = function () {}
    Foo.prototype.bar = function() {}
    new Foo();

So it seems to me that this is either working as intended, or all of these should change (more likely the former since there is a bunch of code that finds these places).
