### ISSUE TITLE
Typescript Configuration does not ignore strict mode check for node_modules content

### ISSUE THREAD

**Issue by BhavikaRanoliya** [microsoft/TypeScript#33527]
I am using protractor and typescript to write automation test script using "core-framework" node module which is also implemented in protractor and typescript. My automation test scripts are located under "Projects" folder. Facing issue while using below typescript configuration to perform typescript strict mode check on my project. It is performing strict-mode check for used "core-framework" node module. My requirement is, how to exclude "core-framework" node module from strict mode check.

tsconfig.json
`{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "declaration": false,
    "noImplicitAny": false,
    "rootDir": "Projects"
    "strict": true,
    "noUnusedLocals": true, /* Report errors on unused locals. */
    "noUnusedParameters": true /* Report errors on unused parameters. */
  },
  "include": [
    ".\\Projects"
  ],
  "exclude": [
    ".\\node_modules\\core-framework"
  ]
}`

**Comment by vinodkpasi** [comment]
I am also facing similar kind of issue. TypeScript validating node_modules folder content if we have used in our project
