### ISSUE TITLE
esModuleInterop is getting out of hand

### ISSUE THREAD

**Issue by beckend** [microsoft/TypeScript#33531]
People are using this flag everywhere, and when new and old users creates new projects with typescript they are literally forced to turn this flag on if they are are going to generate declaration files.

And if they do not generate declaration files, they have to turn on the other flag skipLibCheck which I don't know, defeats the purpose of typings in general.

People are publishing npm packages with the flag on by default almost everywhere, I have made couples PRs here and there to convince them to turn it off since it is not a default flag, but every day the numbers grows larger and larger.

**Comment by weswigham** [comment]
On DT we enforce that an `export=`'d declaration is `import=`'d so the declarations behave both with and without the `esModuleInterop` flag. All we can do is reccomnd that anyone else who cares about their consumers do the same~
