### ISSUE TITLE
generator contextual typing problem

### ISSUE THREAD

**Issue by hardfist** [microsoft/TypeScript#33533]
**TypeScript Version:**  3.6.0

**Search Terms:**

**Code**

```ts
function* g1() {
    const x= 'abc'|| (yield 1)
    return 10
}
```

**Expected behavior:**
typeof g1: Generator<number, number, unknown> or warning ?
**Actual behavior:**
typeof g1: Generator<number, number, 'abc'>
**Playground Link:** 

**Related Issues:** 

It seems that generator yielded type is inferred using contextual typing ,but it's kind of unnatural to infer yielded type from left side of `||`,which cause problem when i update my lib to typescript@3.6, the following I think it's ok
```ts
function* g1() {
    const x: 'abc' = 'abc'|| (yield 1)
    return 10
}
```

**Comment by RyanCavanaugh** [comment]
Closing due to lack of other feedback on this. Playing with this, I can't find any bad behavior in non-degenerate code.
