### ISSUE TITLE
adding methods with decorator type does not exist

### ISSUE THREAD

**Issue by kyawswarthwin** [microsoft/TypeScript#33558]
Any native feature?

Current solution.
https://stackoverflow.com/questions/48599889/typescript-adding-methods-with-decorator-type-does-not-exist

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
