### ISSUE TITLE
Wrong type narrowing for type guard

### ISSUE THREAD

**Issue by metauro** [microsoft/TypeScript#33550]
**TypeScript Version:**  3.6.3

**Search Terms:**

**Code**

```ts
function isClass(target: any): target is new (...args: any[]) => any {
  return true;
}

function test<T extends object>(target: T) {
  if (isClass(target)) {
    console.log(target); // target is T & new (...args: any[]) => any
    // expect type is new (...args: any[]) => any
  }
}
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  
[here](http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABDAzgYQDYEMUoBRRYBOA5gKZQBciWYAngJTWGkXIqJhkDuieAdIOIkU1WnQDaAXQaIAvAD4a9RAG8AsAChEiIhRBEkUIiDIBuLQF8tW0JFgJEUMiigAeACqIyAD2dgAEw44ACMAKzJoBQJhCmoPWQ1tZGA+VEwcfBZyKAZErR0dCAQUOAwyfgw4EhjWXItky28MFDI1AsLisFLyyuranIYGnWtNSyA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. I don't know how to address your expectation since there's no provided rationale for it.
