### ISSUE TITLE
Unexpected parameter hint showing up for `log` in js file 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33565]
From https://github.com/microsoft/vscode/issues/80565

**TypeScript Version:**  3.7.20190922

**Search Terms:**
- javascript
- parameter hints / signature help

**Code**
In a js file:

```ts
//@ts-check

log(
```

Trigger parameter hints on `log`

**Expected behavior:**
Nothing shows up. `log` is undefined here and you can't run go to definition on it

**Actual behavior:**
![Screen Shot 2019-09-23 at 11 59 10 AM](https://user-images.githubusercontent.com/12821956/65454255-96e9a300-ddf9-11e9-9109-0f84ced72b65.png)

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
wat

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh I investigated the issue, and this error happens because

https://github.com/microsoft/TypeScript/blob/1bb6ea038f8ca7e3b2037f8c3209a19c097f1e3b/src/services/signatureHelp.ts#L125

returns `es5.d.ts` source file and

https://github.com/microsoft/TypeScript/blob/1bb6ea038f8ca7e3b2037f8c3209a19c097f1e3b/src/services/signatureHelp.ts#L126

returns `source File.getName Declarations()` all declarations and ignore namespaces. For instance `log` it is a name from `Math` object :).

Is there any reason why `getName Declarations()` is used here?

**Comment by DanielRosenwasser** [comment]
I think the idea is probably to try a best-effort signature help given that we're in JavaScript and we won't always have accurate types around.

If you're in ts-check, this behavior is probably extremely surprising because you're also getting an error that the identifier can't be found. Maybe the solution is to turn it off just there.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Do you mean disable/remove `createJSSignatureHelpItems`?

**Comment by DanielRosenwasser** [comment]
Yeah, if

* the current file belongs to a `tsconfig.json`
* the current file is checked
* the current file belongs to a project with `checkJs`

I think we should probably disable the functionality. Does that sound reasonable?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser It seems in this case, users who use JavaScript without TS checks will get weird suggestions. Or am I wrong?

https://github.com/microsoft/TypeScript/blob/ad8feb5f90e97bb9326133464968927254927fbb/src/services/signatureHelp.ts#L48

Returns correct info for global functions (parseInt, eval, etc), or Objects (Math.log, Date etc). I'm trying to understand where this heuristic can help :smiley: :eyes:

**Comment by mjbvz** [comment]
Would it be ok to only return signature help when we can properly resolve a symbol? This is what we do for quickInfo for example. 

The majority of VS Code users are on untyped JS so I’m wary of a fix that is specific to checkJs

**Comment by a-tarasyuk** [comment]
> Would it be ok to only return signature help when we can properly resolve a symbol?

@DanielRosenwasser What do you think?

**Comment by a-tarasyuk** [comment]
`createJSSignatureHelpItems` was added in this PR https://github.com/microsoft/TypeScript/pull/2641, and changed in this https://github.com/microsoft/TypeScript/pull/26025. Both PRs don't have tests - and it is difficult to understand which cases these changes cover, however, without `createJSSignatureHelpItems` tests work fine. 

cc @DanielRosenwasser @mjbvz

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser What solution do you think is acceptable for this problem?

**Comment by DanielRosenwasser** [comment]
My personal take is that in a checked JS file, or in a TypeScript project, we should not apply the heuristic. Otherwise, I think the heuristic is fine.

**Comment by DanielRosenwasser** [comment]
Ah, I just looked up and saw that reread the convo.

Uh, maybe this is something we should try to understand better - would it be easy to conduct a user study on this? Let's chat about this tomorrow @mjbvz

**Comment by mjbvz** [comment]
Sure. I'm still of the opinion that the behavior of parameter hints should match hover. It seems  confusing to show parameter hints on symbols that we can't resolve

**Comment by RyanCavanaugh** [comment]
Notes from meeting today:
 * Disable this behavior entirely for bare identifiers
 * Add some description of which declaration the description is coming from

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Thanks for the update.

What does mean _`bare identifiers`_? 😕 

> Add some description of which declaration the description is coming from

Do you mean to add an additional field to the server response?

**Comment by DanielRosenwasser** [comment]
@a-tarasyuk Ryan can comment on the second part.

To answer your first question, the idea is `foo` should not try to search for members named `foo` anywhere`, but `foo.bar` should still look for declarations named `bar`. That seems fairly reasonable to me.
