### ISSUE TITLE
Destructure and spread on generics not typing

### ISSUE THREAD

**Issue by saulshanabrook** [microsoft/TypeScript#33579]
**TypeScript Version:**  3.7.0-dev.20190924

**Search Terms:** destructure spread generic

**Code**

```ts
function test<T extends {key: number}>({key, ...rest}: T): T {
  return {key: 10, ...rest}
}
```

**Expected behavior:**

No type errors

**Actual behavior:**

```
Type '{ key: number; } & Pick<T, Exclude<keyof T, "key">>' is not assignable to type 'T'.
  '{ key: number; } & Pick<T, Exclude<keyof T, "key">>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{ key: number; }'.
```

**Playground Link:** https://www.typescriptlang.org/play/index.html?ts=Nightly#code/GYVwdgxgLglg9mABFApgZygHgCqJQD1TABM1EBvAaxQE8AuRMEAWwCMUAnAXwD4AKKrQA0iAHTiO6KFwbYAlLIoBYAFCJEkqCA5JB9RAEYADCPGjJGLqq5A

**Related Issues:**  https://github.com/microsoft/TypeScript/issues/26412 https://github.com/microsoft/TypeScript/issues/10727 https://github.com/microsoft/TypeScript/pull/28234 https://github.com/microsoft/TypeScript/pull/28312 https://github.com/microsoft/TypeScript/issues/18552

**Comment by Nathan-Fenner** [comment]
Perhaps you mean `{...rest, key: 10}` instead, since (if `rest: {key:number}` then `key: 10` gets overwritten)

This is behaving as expected, since you don't know that `10` is a valid value of type `T["key"]`. In particular, consider:

```typescript
const example: {key: 1 | 2, val: string} = {key: 1, val: "abc"};

// No type error! But it would be wrong:
const sameType: {key: 1|2, val: string} = test(example);
```

So you'd need to instead give a type like:

```typescript
function test<T extends {key: number}>({key, ...rest}: T): Omit<T, "key"> & {key: number} {
  return {...rest, key: 10};
}
```

or like (but this one TypeScript also rejects, which is a design limitation since its flow-sensitive typing is not smart enough):

```typescript
function test<T extends {key: number}>({key, ...rest}: T): number extends T["key"] ? T : Omit<T, "key"> & {key: number} {
  return {...rest, key: 10}
}
```
