### ISSUE TITLE
Types do not follow generic mixin composition

### ISSUE THREAD

**Issue by treffynnon** [microsoft/TypeScript#33571]
**TypeScript Version:**  3.7.0-dev.20190922

**Search Terms:**

* Generic mixin(s)
* Mixin composition
* Recursive mixin(s)

**Code**
```ts
// Apologies, but this is not entirely self-contained. It uses https://www.npmjs.com/package/conditional-type-checks for type assertions.

import { assert, IsExact } from 'conditional-type-checks'

/**
 * The basic source classes from which we want to clone the properties
 * and their types.
 */
class ClassA {
  public readonly a1: string = 'av1'
  public readonly a2: string = 'av2'
  public readonly a3: string = 'av3'
}
class ClassB {
  public readonly b1: string = 'bv1'
  public readonly b2: string = 'bv2'
  public readonly b3: string = 'bv3'
}
class ClassC {
  public readonly c1: string = 'cv1'
  public readonly c2: string = 'cv2'
  public readonly c3: string = 'cv3'
}

/**
 * A constructor type implementation that includes a prototype reference
 */
interface Constructor<T extends {} = {}> extends Function {
  readonly prototype: T
  new (...args: any[]): T
}

// ============== Single property cloning ================ //
// this works and forms the basis for multiple property cloning

/**
 * Takes a given property from a source class and includes it in the newly created
 * and returned class. This will also copy the type for the property from the source
 * class.
 * @param sourceClass the class from which the property should be cloned from
 * @param key the name of the property being cloned
 * @param Base either a class or another mixin in the case of composition
 */
function ClonePropertyMixin<
  S extends Constructor,
  K extends keyof S['prototype'],
  B extends Constructor
>(sourceClass: S, key: K, Base?: B) {
  const property: unique symbol = ((key as K) as symbol) as any
  class ClonePropertyMixinExtensionClass extends (Base || class DefaultBaseClass {}) {
    public [property]: S['prototype'][K] = sourceClass[key]
  }
  return (ClonePropertyMixinExtensionClass as unknown) as Constructor<Pick<S, K>> & B
}

// ~~~~~~~~~~~~~~ TESTS ~~~~~~~~~~~~~~ //
// these tests pass and work correctly

class TestCloneA extends ClonePropertyMixin(ClassA, 'a1') {}
assert<IsExact<keyof TestCloneA, 'a1'>>(true) // succeeds

class TestCloneB extends ClonePropertyMixin(
  ClassA,
  'a1',
  ClonePropertyMixin(ClassB, 'b1', ClonePropertyMixin(ClassC, 'c2'))
) {}
assert<IsExact<keyof TestCloneB, 'a1' | 'b1' | 'c2'>>(true) // succeeds


// ============== Multiple property cloning ================ //
// this does not

/**
 * Given a list of property keys - clone them into a new class along with their\
 * types.
 * @param sourceClass the class from which the property should be cloned from
 * @param keys the names of the properties being cloned
 * @param Base either a class or another mixin in the case of composition
 */
function ClonePropertyListMixin<
  S extends Constructor,
  K extends keyof S['prototype'],
  B extends Constructor
>(sourceClass: S, keys: K[], Base?: B) {
  return keys.reduce<Constructor<Pick<S, K>> & B>(
    (acc, key) => ClonePropertyMixin(sourceClass, key, acc),
    Base as B & any
  )
}

// ~~~~~~~~~~~~~~ TESTS ~~~~~~~~~~~~~~ //
// these tests do not pass once more than one `sourceClass`/call to `ClonePropertyListMixin()` is involved.

class TestListCloneA extends ClonePropertyListMixin(ClassA, ['a1', 'a2']) {}
assert<IsExact<keyof TestListCloneA, 'a1' | 'a2'>>(true) // succeeds

class TestListCloneB extends ClonePropertyListMixin(
  ClassA,
  ['a1', 'a2'],
  ClonePropertyListMixin(ClassB, ['b1'])
) {}
// Should pass, but does not:
assert<IsExact<keyof TestListCloneB, 'a1' | 'a2' | 'b1'>>(true) // fails
// Should fail, but does not:
assert<IsExact<keyof TestListCloneB, 'a1' | 'a2' | 'b1' | 'b2' | 'b3'>>(true) // succeeds

class TestListCloneC extends ClonePropertyListMixin(
  ClassA,
  ['a1'],
  ClonePropertyListMixin(ClassC, ['c1'], ClonePropertyListMixin(ClassB, ['b2']))
) {}
// Should pass, but does not:
assert<IsExact<keyof TestListCloneC, 'a1' | 'c1' | 'b2'>>(true) // fails
// Should fail, but does not:
assert<IsExact<keyof TestListCloneC, 'a1' | 'c1' | 'c2' | 'c3' | 'b1' | 'b2' | 'b3'>>(true) // succeeds
```

**Expected behavior:**

When cloning a list of properties from multiple classes the returned/composed class type should only contain the properties specified.

This is a diagram of what it would ideally be doing:

```
                                                                              +-----------------+
                                                                              |  FinalClass     |
                                                                              +-----------------+
+-----------------+                                                           |  * a1 [string]  |
|  ClassA         |                                                           |  * a3 [string]  |
+-----------------+    +---------------------------------------+              |  * b2 [string]  |
|  * a1 [string]  +--->+  ClonePropertyListMixin(['a1','a3'])  +------------->+  * c1 [string]  |
|  * a2 [string]  |    +------------------------------------+--+              |  * c2 [string]  |
|  * a3 [string]  |                                         ^                 +-----------------+
+-----------------+                                         |
                                                            +------+
+-----------------+                                                |
|  ClassB         |                                                | Composition
+-----------------+    +---------------------------------------+   |
|  * b1 [string]  +--->+  ClonePropertyListMixin(['b2'])       +---+
|  * b2 [string]  |    +------------------------------------+--+
|  * b3 [string]  |                                         ^
+-----------------+                                         |
                                                            +------+
+-----------------+                                                |
|  ClassC         |                                                | Composition
+-----------------+    +---------------------------------------+   |
|  * c1 [string]  +--->+  ClonePropertyListMixin(['c1','c2'])  +---+
|  * c2 [string]  |    +---------------------------------------+
|  * c3 [string]  |
+-----------------+
```

**Actual behavior:**

When the `ClonePropertyListMixin()` is composed to clone properties from multiple classes only the last invocation (composition order) has the correct type. Every previous call is given an incorrect type including all the properties of `sourceClass` where it should only be the listed keys that are included.

**Playground Link:** 
* [Example code on Playground](https://www.typescriptlang.org/play/?ts=Nightly#code/PTAEEEAcHsBtoOYEsCmBnANKARgVwC6j4AWSaoZoAdtISlfkgE4qwCeoarAZgLQDG0BgEMkVFABMAdKACShXF3LF8+SGgBcIAO66pVSAFsAVmimDDwSMP4BrYQhTBBVCUkZDhsXvjaQUAsQoduTc0ExEfiigwmhcTB5UZgBQyUiGMAmgAN4xcSgJWLJoAKIAHjaEAL6g3EzQhqAA5C5uiV4+UYHBtmhNqcAAVIPJoIOgACpBOLFI-JzQuEz80fywsUq19Y3apPzEoNrR2sIMRNCga0LRJNGQ9f4JqGij46cSREHMkf4pY8DJNYbUAAYXWcXAOWSAEhILhsLA5qAWMIJEJ2DEAIwaTj4JhiBCgAC8zWEADdMf1YfDEfMUWiqBjhAAmHFoPEE4mksnMqlwhFI+nojjCADMbI5VEJJKa5NF-SqgPB5DBGwAQlDqQK6ShUcKcNjcfipVymtgKXyaYLdQyMdhWUbOTLzbyYfzacibfrsOLHSbnWT5clFUC4qDlSDNe7rXrGRx+Ib2cbpc1+Ba3VadbGMfwHUmnameZbtZ7s-Hffn-YWg4rkkMRmMIJchEncPx8OEftF0pBYChDPR8MJEp9hxQqGtcBJ0DFQPdaLQop7uAV6CtXgCxPgCtwbNEQS28W2O0wADwTUAoMrb1zkbI1En3gB8l+v9Ak5AAYrgJyPsjChTjOd6g7Xx-BxCYYXEbRQAACikBDhCYBBNBiKg2AAbQAXQASgg4MBjAIliJI0jSNAABlAk+2A6BHl8S54CoJ0yNY8iQDrMASEobRwl6NCPjCJhDHIW4ZjQSghNAQxcFgRhezuB4CgYq5mKlAZhleSZhFsGdhFAZAyXoWj6I4OoGlnNBFmWVZlQE8dJ2nch3HHT5omgnMUW3CQtPeT18CWcQPlDMxJlIchtCQWBYBiWArObSAODEsDoiksT51MrYLLEqylnXRsQqkLSAAFrCYYRGlymzVTDMSQqynY9gOdKlISDg0GIRZYA+bBbOuQTthKsqKtAXSkumKgKuiaBuDckzlI4XrOVUyQhqQka1ViaIUHcIIIn0+rO1OWg9ukpAyjEVy6q20AZubDJoAkxIN2Sbgf3bJAhHDa4AAVWt8ABZc6xFPGEKNfG8P1BQ8mGPcIMBhABpCH33IMa7oojCmnnUCoiaLCEehDUr0hlUYbhphkifWCqpWGrUIorAxpxRGsE2rgAH4cTVHDNRcdl5ranEfyQABHXBojQNhDGwOAuVg2CxryUBEd52JOGl2XYDV8hTjYGF6rBX7-rYIGLqocobwkoR6ZR284PZ6IAB8ncY4EABEUF3WT8Ed23715-9oS1D0MIyhasJxTHsZAxd-HxjDEawrlaZQemMLGrCYUVaEWACpgqDgo3xD+uiFrNsRLfoa2qFt9Wf1sGhtCoHXoaSI923CU8frmWxT0ZlWnxfAAyUA1QIzjQAAPxn2e57nyYSgoiZwfntfZ9ADiQDcrgiHQfByGsMM-N4phbGbJgWHbdhUnqiZ9+LlBIRJ1HvpLk2K6oWD6fALBZUpQOioNjKVPMUcolRTzo1mvfdkj9f6kkpEPWCR4UC823mgNsKxJAvCVMCGB+BH7EzfPbR+pdTKf1gjCH+hN-5NEJqQj+wMv70zVH-bAlIsAMLLm1Ch9MQR-1zE0HCOFkiAOSMAhIoDSgVHbJAlAbA7r4MIX-YQlJQCuzNGojRgikEoLQWADB-AsEflSJPNibFQAAx9kgBSgsVJMRYuY1im8ATb24uQNEM4aD4A0g2cYABxJARlC76URALO64c2qjXkeQXgjFrhuUaFuC4+loJu2PkxQkkUSBuWYAAHS0ilP44xSrrUqtZOmdk6p2XMo1OYzVpiRIYh1LqPU+pBQamtcqjQxqiQmlNcgd0WrcMYDOJaJoVo+UbKU7pY8bo7VuPtdJgz9reNOoYJhV1pj8BundCwMAnqfSoC9N6v4jlvxQGQhaAAZMg+BP6g2hODF+JDyadyYITZGLyoZQMoljHGccUD40JkQ0mbdWzvKpjTCpadlRRyZjElm2E2ZbS5mPQOAEUD50Lr0qQLAJBthQKeA87dYbvO7r3fuWBEZD1AKPNU1MYTQlgjYfgCK2C8yJC+Lh5CmHQryrCjY7KsCspwoTImN11YalHnrGEIjazb3XuvRey9V5Kvni4yetxd7bnZB4i43i5zAiECsaS4QbjEFOLdcQoAAAGqd6a2ucF4GKHY7U8puXcihOFbUUGclQMkcAjLSFvnZfBtzYFMSfnbKGHq2oRvuXy6hoAsaqLoaSXkuEchAPyJIsBMj8ByIUdA-eCa4EqK0RmpoujYaoJcZwTBKBsGhrwaWu5hCY0qijVc+NXq+VUOVL-GEqaOFVoJgO42Iy2AJt4cqVhKbNH4xEWI7eFFOqyQ+EfTAOACCgE8eQbxGhxG5sLfmiBvzw3tqjfO2h6iq13sXTWiW+jaiiDipPNdrTX1RSwHgQg+7qC0CPRI090jz3yMUW2yN1wb1pofSyJoD72GIY0faFDzQfTVupno+thjjE4LvlBghUbIzfK7ZO0yM7+3QmocO2h46aPdpNlR8238IxYCxgmYFFye2+BY2INj6oONmkzcI0R2aP3ru6kauIv7d0AcPce+IoHwGyIvURx+-CEHoZaJWkTWHkG1pfbuKKLxV1ScEm+uT-7oBeKA0pkBZ61MQZLeyMtJGK06a4w+wRPn5RIb02hpD8on11vQY25tQA)

**Related Issues:** 
* [chained generic mixins fail #28594](https://github.com/microsoft/TypeScript/issues/28594)

**Comment by Nathan-Fenner** [comment]
I was able to get your type tests to appropriately pass/fail by changing the type for `ClonePropertyListMixin`:

```typescript
/**
 * Given a list of property keys - clone them into a new class along with their\
 * types.
 * @param sourceClass the class from which the property should be cloned from
 * @param keys the names of the properties being cloned
 * @param Base either a class or another mixin in the case of composition
 */
function ClonePropertyListMixin<
	S extends Constructor,
	K extends keyof S['prototype'],
	B,
>(sourceClass: S, keys: K[], Base?: Constructor<B>): Constructor<Pick<S, K>> & Constructor<B> {
	return keys.reduce<Constructor<Pick<S, K>> & Constructor<B>>(
		(acc, key) => ClonePropertyMixin(sourceClass, key, acc),
		Base as Constructor<B> & any
	)
}
```

**Comment by treffynnon** [comment]
Thank you for taking the time to review my code and describe the miss-step, @Nathan-Fenner I can confirm that your fix also works in my application code that is more complicated and involved than the code presented here. It also has a larger test suite, which passed nicely too.

The only caveat for anyone else who may come across this issue is that whilst this does work in typescript@next(3.7.0-dev.20190922) it does not in typescript@3.6.3. So, we are looking forward to the 3.7 release of TypeScript.
