### ISSUE TITLE
Destructuring assignment type widening seem not work

### ISSUE THREAD

**Issue by tkow** [microsoft/TypeScript#33572]
**TypeScript Version:**  3.6.3

**Search Terms:**

- destructuring assignment
- spread operator

**Code**
```typescript 


const test = {
  a: 1,
  b: '2'
}

function hoge(args: {[key:string]: string}) {
  return args
}

hoge(test)

const {a,...rest} = test

hoge(rest) // error
hoge(rest as {[key:string]: string} )  // error
hoge(rest as {b: string} )

const foo = {
  b: '2'
} as const

hoge(foo)
```

**Expected behavior:**

hoge(rest) and hoge(rest as {[key:string]: string} )  are resonable to cast.

**Actual behavior:**

const rest confined some prop types, but incompatible with  {[key: string]: string}

**Playground Link:** 

https://www.typescriptlang.org/play/index.html#code/FDDGHsDsGcBcAJYFM7wLzwN7HvAhgFzwCMANDvAEZEDkATDcAL4gBmArpKLAJZTwALcAHMkACjwAnYdCKYA2gGskATwJxJPSMIC6RDVuFMAlFgqSksdpMj5p0ZiCGixyOMZAQYCTHlIA6QIs4JnREFFgnEXFg2A9nGIj8aCwlVXVYTW09eANtUPjosVjkrGpczMMCzyhUVnBwMOxccvpGULwUrzgol3rwYyA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is a correctly-rejected cast since `test`'s type isn't sealed (i.e. its type does not disprove the existence of other non-string properties).
