### ISSUE TITLE
If-statements without block body breaks the statement

### ISSUE THREAD

**Issue by SiXoS** [Microsoft/TypeScript#3357]
Creating an if-statement in typescript without a block body moves the statement one line down which breakes the if-statement.

Minimal example:
The code:
```
if(false) console.log("Should not happen.");
```
Is compiled to: 
```
if (false)
    console.log("Should not happen.");
```

You would expect the source code not to log "Should not happen" but the compiled code will log "Should not happen".

**Comment by lbguilherme** [comment]
Are you saying this

    if (false) console.log("Should not happen.");

has a different behaviour than this?

    if (false)
        console.log("Should not happen.");

Could not reproduce here.

**Comment by SiXoS** [comment]
Ok, this is my fault, I must have done something wrong in my initial test. There is no bug.
