### ISSUE TITLE
Unable to properly define Type Guard

### ISSUE THREAD

**Issue by akopchinskiy** [microsoft/TypeScript#33590]
```ts
interface A {
    a: string
    b: string
}

interface B {
    b: string
    c: string
}


type AB = A & B;

function isA(obj: AB): obj is A {  // ERROR here
    return !!obj.a &&
        !!obj.b &&
        !obj.c;
}
```

Error:
![image](https://user-images.githubusercontent.com/39277134/65606493-4b76f680-dfab-11e9-8412-1dbfaa41016e.png)

**Comment by ilogico** [comment]
That is because type assertions cannot widen the type, only narrow it.
`AB` extends `A`, but `A` does not extend `AB`.
What you actually want is to say `obj is not B`, which is not currently possible.

**Comment by jack-williams** [comment]
Is this what you wanted?
```ts
type AB = A | B;

function isA(obj: AB): obj is A {
    return "a" in obj && "b" in obj && !("c" in obj);
}
```

**Comment by RyanCavanaugh** [comment]
The signature is nonsensical as written; its only valid return value is `true`. All `AB`s are `A`s.
