### ISSUE TITLE
Is it possible to prevent Automatic Typings Acquisition for a specific package?

### ISSUE THREAD

**Issue by jkovzels** [microsoft/TypeScript#33599]
I'm getting typing related error because definitions typescript/vscode resolves are out of date. 

More specifically, i'm using [`"paper": "^0.12.3"` ](https://www.npmjs.com/package/paper/v/0.12.3) which comes with it's own definitions in the package.

For some reason typescript/vscode thinks that it is necessary to get latest [`@types/paper`](https://www.npmjs.com/package/@types/paper) with slightly outdated definitions (current version: 0.11.14) which breaks my world. 

Is there a way to disable this behavior, or my configuration is somehow wrong?

**Comment by RyanCavanaugh** [comment]
You can turn off type acquisition globally ("Disable Automatic Type Acquisition"), but there isn't any control on a per-package basis.

See also https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#removing-a-package
