### ISSUE TITLE
Better error message for missing member in tslib

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#33603]
@amcasey brought this up while upgrading Yammer to 3.6/3.7.

```
This syntax requires an imported helper named '__spreadArrays', but module 'tslib' has no exported member '__spreadArrays'.
```

The error message tells us something that is technically correct, but which is not clearly actionable. The user has no idea why `__spreadArrays` gets imported during an upgrade.

We should indicate that the user should try upgrading `tslib`.

```
This syntax requires an imported helper named '__spreadArrays' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.
```

**Comment by m-henderson** [comment]
@DanielRosenwasser did upgrading tslib fix the error?

**Comment by amcasey** [comment]
@m-henderson yep.

**Comment by m-henderson** [comment]
@amcasey @DanielRosenwasser it looks like there are a lot of places that the message is referenced: 
<img width="2560" alt="Screen Shot 2019-09-26 at 1 30 21 PM" src="https://user-images.githubusercontent.com/16070192/65715115-18dc0500-e062-11e9-8af1-ff042734f2a7.png">

 Are we going to want to recommend a tslib upgraded on every instance of the message or only when tslib as no exported member of _spreadArrays ?

**Comment by DanielRosenwasser** [comment]
It should just be a matter of updating the message in `diagnosticMessages.json`, running `gulp generate-diagnostics` and updating the place where the error is issued in `src`.

**Comment by m-henderson** [comment]
@DanielRosenwasser I opened a PR. Just let me know if any changes need to be made to it and I will take care of it. 

https://github.com/microsoft/TypeScript/pull/33625

**Comment by DanielRosenwasser** [comment]
Thanks @m-henderson!

**Comment by m-henderson** [comment]
@DanielRosenwasser no problem! thank you for helping me out with the detailed comment : 

> It should just be a matter of updating the message in diagnosticMessages.json, running gulp generate-diagnostics, updating the place where the error is issued in src, and accepting new error message baselines. Please check out our CONTRIBUTING.md at the root of the repo.

**Comment by markterrill** [comment]
Thanks!
Upgraded to 1.10.0 and all ok. 

My error had been for ionic / cordova and the android logcat error was:
```
"Uncaught TypeError: tslib.__spreadArrays is not a function"
```
