### ISSUE TITLE
Generic type guard erroneously narrows to 'never'

### ISSUE THREAD

**Issue by koffmoff** [microsoft/TypeScript#33608]
**TypeScript Version:**
3.6.3 and 'Nightly' in playground

**Search Terms:**
type guard infer never narrow generic constructor class

**Code**

```ts
function isOfType<T>(obj: any, cls: new (...args:any[]) => T): obj is T {
    return false
}

class A {
}

function test(o: object) {
    if(isOfType(o, A))
        var x = o  // o is correctly inferred as "A"
    else
        var y = o  // o is erroneously inferred as "never"
}
```

**Expected behavior:**
y should be inferred as `object`

**Actual behavior:**
y is inferred as `never`

**Playground Link:**
https://www.typescriptlang.org/play/?ts=Nightly#code/GYVwdgxgLglg9mABDAzgeWAFQJ4AcCmAPJgHwAUcARgFYBciAhmNgDSIQA2K9Y+A7ojIA6EQwBOAc25NsAbQC6ASkQBeEokyL6VashQbEAbwBQiM4jH4oIMUmAMu+YwF9jxzgxT6AgkZdvQSFgERCh8FCgKbRp8aGUTc2RgMlQMHAIKNm9FRVNE8wA3cUQAD1VEODMAeiqKvXY4MUtoDmxkMGB8JvwAE0Z9ACJvAbyzfEdR-KKxRDaVOsQautRELrEEfDgQFFb2zu6+z0QB3gKukdcgA

**Related Issues:**
#12646 seems related

**Comment by AlCalzone** [comment]
Your class is empty:
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely

Add any member and it works:
https://www.typescriptlang.org/play/?ts=Nightly#code/GYVwdgxgLglg9mABDAzgeWAFQJ4AcCmAPJgHwAUcARgFYBciAhmNgDSIQA2K9Y+A7ojIA6EQwBOAc25NsAbQC6ASkQBeEokyL6VashQbEAbwBQiM4jH4oIMUmAMu+YwF9jxzgxT6AgkdPncMRgANwYofERgODh6cAATfGAYXjiAbhc3UEhYBERwlCgKbRp8aGUTc2RgMlQMHAIKNm9FRX9Ks1CxRAAPVUQ4MwB6Qf69djgxS2gObGQwYHxJ-DjGfQAibzW2xHxHbcrOxFmVUcRh0dRxpenZ5IWllc9+kugMoA

**Comment by koffmoff** [comment]
Indeed! Thanks!
