### ISSUE TITLE
Union type member order switches

### ISSUE THREAD

**Issue by cain-wang** [microsoft/TypeScript#33605]
We noticed TypeScript switches the order of the union type members in the error message. And we hope someone can shine a light on this. The error is for React Ref type.

The error message used to be:

```
"Type 'Ref<unknown>' is not assignable to type 'string | RefObject<HTMLDivElement> | ((instance: HTMLDivElement | null) => void) | null | undefined'."
```

Now it becomes: (**RefObject<HTMLDivElement>** and **((instance: HTMLDivElement | null) => void)** switches)

```
Type 'Ref<unknown>' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined
```

We did not change relevant code, but did add `react-transition-group` dependency.

What puzzles me is in @types/react, the ref type is defined as:

```
type Ref<T> = { bivarianceHack(instance: T | null): void }["bivarianceHack"] | RefObject<T> | null;
```

Why the order of the bivarianceHack and RefObject<T> would switch all of sudden?

**Comment by AnyhowStep** [comment]
It's just a thing that happens.

https://github.com/microsoft/TypeScript/issues/29255

**Comment by cain-wang** [comment]
Thanks a lot for the pointers! I've been searching a lot on the internet and even digging up TS code base to find an answer!!

**Comment by AnyhowStep** [comment]
One more,
https://github.com/microsoft/TypeScript/issues/32224
