### ISSUE TITLE
Flow analysis doesn't track variable type after conditional expression

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/TypeScript#33618]
**TypeScript Version:**  3.7.0-dev.20190926

**Search Terms:** conditional expression flow analysis

**Code**

```ts
interface iface {
    flag?: boolean;
}

function func1(param?: iface) {
    if (param ? param.flag : false) {
        param.flag.toString(); // errors: 1. 'param' is possibly 'undefined' 2. 'param.flag' is possibly 'undefined'.
    }

    if (param && param.flag) {
        param.flag.toString(); // ok
    }
}
```

**Expected behavior:**
Compiles without errors

**Actual behavior:**
Compiles with an error where param is checked using a conditional expression with a constant 'false' in the "else" branch, but not where param is checked using a similar logical-and expression.

**Playground Link:**  https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAmPJyDeBYAUMg5GAGzgHMB+ALmQCMB7e4iOEAbjwF888YBXEAjDB6IIgIQBGABQAHOFDgBbaqnQQAlFjyE1yOQuXIKyeYqUA6EuWQ14xAM6bt+XYTPKrpMhbD0AymBQoGTSGmzIAPSRyNBQ9FAONJIWyADkHkppqA6m9A4OwLTEAJ7pAgAmEDCgEBXZAEypGYaW1mTZwLmy+YXFZWmV1bX1FjqE3LjjBGj6mcgAZAumrV7kWjiubivmaz5+gcEgoeFRMfQA1tPIk5NAA

**Related Issues:** #9998

**Comment by RyanCavanaugh** [comment]
Narrowing patterns need to be identified syntactically, so we have to "pay for" all of them. Since there's an equivalent and more idiomatic way to write this, using `x ? e : false` isn't a recognized control flow pattern.

**Comment by RikkiGibson** [comment]
Thanks!
