### ISSUE TITLE
Recursive type reference of default type parameters

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#33616]
@ahejlsberg Can you also support the following patterns?

```ts
type A<T = A> = T;
type B<T extends B[] = B[]> = T;
```

**Comment by falsandtru** [comment]
This feature is required to remove any type with recursive type structures as follows:

```ts
type Tree1<T, U extends Tree1<T, any>[] = Tree1<T, any>[]> = [T, U];
type Tree2<T, U extends Tree1<T>[] = Tree2<T>[]> = [T, U];
```

**Comment by falsandtru** [comment]
@ahejlsberg thoughts?

However, the best solution for my example is https://github.com/microsoft/TypeScript/issues/26242#issuecomment-541252431.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
