### ISSUE TITLE
Properties that may be overridable as methods.

### ISSUE THREAD

**Issue by adamsea** [Microsoft/TypeScript#3361]
Hello,

I'm dealing with an issue specific to TypeScript on a Backbone project, but this seems more generic to any project using underscore/lodash and the return of the `_.result` method:

```
// With _.result you can work with an object property or function...
return _.isFunction(value) ? value.call(object) : value;
```

Is it possible to have a TypeScript interface definition that includes an instance property that can optionally be overridden with an instance method?  Example from Backbone's .d.ts file to include both:

```
url: any
url(): any
```

Currently this produces an error for a duplicate identifier.

Thanks!
-Eric

**Comment by RyanCavanaugh** [comment]
You can write ` x: string|(() => string)` to mean "a string or a function returning a string"

**Comment by adamsea** [comment]
Excellent - that was just what I was looking for.  Thank you!

**Comment by adamsea** [comment]
Reopening for one more question - is it possible to do the same thing in a class definition or will the base class require a more concrete definition of the type (e.g. "string vs. function returning a string")?

**Comment by danquirk** [comment]
Should be a few ways you could approach it. One example:

```ts
declare var _: any;

class Foo {
	url: string | (() => string);
	constructor(value, object) {
		this.url = _.isFunction(value) ? value.call(object) : value;
	}
}

var f = new Foo(1, 2);
var r = f.url; // need to copy to a local for type guards to work
if (r instanceof Function) {
	r();
} else if (typeof r === "string") {
	var s = r;
}
```

**Comment by adamsea** [comment]
Thanks @danquirk - the issue appears to be in classes that extends another class with a union type defined this way.  Here's an example I just threw up:

http://www.typescriptlang.org/Playground#src=class%20Foo%20%7B%0A%09bar%3A%20string%20%7C%20(()%20%3D%3E%20string)%3B%0A%09bat()%20%7B%0A%09%09let%20bar%20%3D%20this.bar%3B%0A%09%09if%20(bar%20instanceof%20Function)%20%7B%0A%09%09%09bar()%3B%0A%09%09%7D%0A%09%09else%20if%20(typeof%20bar%20%3D%3D%3D%20%22string%22)%20%7B%0A%09%09%09let%20b%20%3D%20bar%3B%0A%09%09%09b%20%3D%20%22b%22%3B%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Aclass%20MyFoo%20extends%20Foo%20%7B%0A%09bar()%3A%20string%20%7B%0A%09%09return%20%22bar%22%3B%0A%09%7D%0A%7D%0A

As long as I create that local copy the type guards work, but the very nature of extends means we don't create that local copy before the property/method definition.  It seems like the compiler should work within the realm of check if the definition satisfies one of the types in the union, and usage of the property/method would still require local copying.

Does that make sense or seem like a reasonable request?

Thanks,
Eric

**Comment by danquirk** [comment]
If you define bar as an instance member in MyFoo it will work:
```ts
class MyFoo extends Foo {
	bar = () => {
		return "bar";
	}
}
```
likewise using an interface:
```ts
interface hasURL {
	url: string | (() => string);
}

class Bar implements hasURL {
	constructor(public configured: boolean) { }
	url = () => '' // or could be url = ''
}
```

**Comment by mhegazy** [comment]
Looks like this issue has been addressed. please reopen if there more questions.
