### ISSUE TITLE
transpile function should provide the way to name generated module

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#3362]
Original issue: https://github.com/systemjs/builder/issues/181

**Comment by guybedford** [comment]
Great to see this in! Which release will this work in?

**Comment by vladima** [comment]
@guybedford it is fixed in master branch and currently we are waiting for approval to port the fix in 1.5.2 which is the upcoming TS release

**Comment by guybedford** [comment]
Excellent, please just let me know when I can continue to integrate the support. There seems to be a fair amount of interest in polishing this.
