### ISSUE TITLE
Implementing only a Setter is enough to implement an Interface

### ISSUE THREAD

**Issue by willemneal** [microsoft/TypeScript#33621]
**TypeScript Version:**  3.6.3

**Search Terms:** only setter in class implements interfaces.  Interface property bugs.

**Code**

```ts
interface Properties {
  val: number;
}

class BadProps implements Properties {
  private _val: number = 42;
  set val(newVal: number) {
    this._val = newVal;
  }
}
```

**Expected behavior:**
A type error that the implementing class is missing the getter.

**Actual behavior:**
Just runtime error of undefined.

**Playground Link:** 
[Above example](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgApQPYAdpmBAZ2QG8AoZZANzgBsAuZEAVwFsAjaAblIF9TSENOASIAhOABN02IsBZYaEFhHBFpOKHkIlyyLFGDVIyAPrV6jVhyjIAvMgAsAJm4UCEMFVoAKEBADuAGq0DMzs0ACUOhQUYAAWwAQAdGa0dowBwTSuyHx8AhggBJ5skurpADzquPgEAHwZ-sjiUphYBN4R3AVFnubppa3YSebctLje5l1AA)

**Related Issues:**

**Comment by j-oliveras** [comment]
Probably related to PR #33509 by @sandersn

**Comment by RyanCavanaugh** [comment]
Duplicate #30852; others
