### ISSUE TITLE
Call it "sloppy mode"

### ISSUE THREAD

**Issue by callumlocke** [microsoft/TypeScript#33634]
## Search Terms

strict mode, sloppy

## Suggestion

In the next major update:

- Make all 'strict' behaviours **on** by default.
- Invert the logic and names of relevant compiler options, like this:

|  Current | Proposed	|
|---	|---	          |
| `strict`  	|   `sloppy`          	|
|   `strictBindCallApply`	|     `sloppyBindCallApply`        	|
|   `strictNullChecks`	|     `sloppyNullChecks`        	|
|   `strictFunctionTypes`	|     `sloppyFunctionTypes`        	|
|   `strictPropertyInitialization`	|     `sloppyPropertyInitialization` |
|   `noImplicitAny`	|     `allowImplicitAny`        	|
|   `noImplicitThis`	|     `allowImplicitThis`        	|
|   `alwaysStrict`	|     `noStrictMode`        	|

## Why?

When I first saw the option `--strict` in the docs, I thought it must be intended for pedantic uber-geeks. Kind of like Babel's strict mode, which prioritises spec compliance above all else even in obscure corner cases.

But I learned the hard way that non-strict codebases always hide bugs that could have easily been avoided. On closer examination these 'strict' settings are all very sensible and they make TypeScript better at what it does. Most experienced TS coders seem to default to using `"strict": true`.

Having the ability to relax the TS compiler can be useful as a temporary measure when porting existing codebases to TypeScript. But I think the option names and default values should convey that non-strict behaviours are a crutch, and encourage their eventual retirement.

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
I am both for and against this. I feel like it won't happen, though.

I'm against this because it just changes the behavior of the compiler a lot. I wonder how many complaints they'll receive.

I'm for this because I love my strictness.

**Comment by nmain** [comment]
Based on the justification given, it seems like a lot of good could be done with just documentation improvements.

>But I learned the hard way that non-strict codebases always hide bugs that could have easily been avoided.

Documentation should bring up points like this, and generally steer users towards strict mode.

**Comment by RyanCavanaugh** [comment]
We appreciate the sentiment but this isn't the kind of change we would do.
