### ISSUE TITLE
Generic type arguments are sometimes also valid JavaScript comparison expressions

### ISSUE THREAD

**Issue by jasvir** [microsoft/TypeScript#33639]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
superset, syntactic, semantic, heuristic, parsing

**Code**

```ts
function f(x = {}) {
  document.body.innerText =
    `I'm ${
      arguments[1] === false ?
      "java" :
      "type"
  }script`;
}
let h = () => "";
f(h.apply<String, Object>("type"));
```

**Expected behavior:**
When run as JS (since it's valid JS) it should output the same as when run as TS.

**Actual behavior:**
The behavior is different in JavaScript and TypeScript

**Playground Link:** 
https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMAFAD0QXkQbwL4CUuAsAFCKIAmcEIAtgKZhQB0ARnJQJ4sxhgMATgBUGaKFjIUKAAwCSAcjqIAJDinSKAQ0EBzekygBnANoBGALpZM2YFoA2RhogD8GzQCIAVloBuWj0QALndpDyguAAcGDw08IwhBGEioGQBuMjwyewYJAAssRBQiTAA+RA8PDNJUPJYtSMj7LgAeAGUoJLBdABpEAHk2LwZoUpRwqJiCAmqgA

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/26179

**Note**

I wrote about this at some length https://medium.com/@jasvir/monoglots-when-a-subset-is-not-1604e3a51d9 because I thought it was just cute but not serious. I was inspired to file it here by a comment @erights made in a bug filed against TC39 (https://github.com/tc39/ecma262/issues/1681) on JS failing to be a superset of JSON that resulted in a security bug.

**Comment by RyanCavanaugh** [comment]
Nice construction!

**Comment by guyutongxue** [comment]
We can create a more interesting construction,

```ts
let as=()=>0,m=[].map<0>as(()=>[]);console.log(`I'm ${!m?'Java':'Type'}Script`)
```

This piece of code *won't* emit any error on a default-configured `tsc`, and the running result is `I'm TypeScript`. In a JS runtime, this code produces `I'm JavaScript`. 🤣

I've also tried some popular TS runtime. The result is:

```
$ deno
Deno 1.45.5
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> let as=()=>0,m=[].map<0>as(()=>[]);console.log(`I'm ${!m?'Java':'Type'}Script`)
I'm TypeScript
undefined
```

```
$ bun repl
Welcome to Bun v1.1.24
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> let as=()=>0,m=[].map<0>as(()=>[]);console.log(`I'm ${!m?'Java':'Type'}Script`)
I'm TypeScript
undefined
```

```
$ node --experimental-strip-types
Welcome to Node.js v22.6.0.
Type ".help" for more information.
> (node:6927) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
let as=()=>0,m=[].map<0>as(()=>[]);console.log(`I'm ${!m?'Java':'Type'}Script`)
I'm JavaScript
undefined
```

**Comment by jasvir** [comment]
Nice! There's a shorter construction due to @mikesamuel viz.
```console.log(`I'm ${ (0).toFixed.apply<Number, String>(1) ? 'Type' : 'Java' }Script`)```.

Semantic supersetting is hard - I think it's a dead horse not worth beating further.
