### ISSUE TITLE
In 3.7, there is no way to override `get`/`set` declaration emit for accessors

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#33640]
This is troublesome for producing declaration files that are compatible with versions of typescript less than 3.6. Most other emit changes you can override by writing an explicit type annotation, however there's no equivalent for changing getter/setter declaration emit. This comes up in our `docker` suite, as the `get`/`set` declaration emit breaks `azure-sdk`, as they test their declaration files against older versions of TS.

**Comment by bterlson** [comment]
@weswigham can you tell me more about the typings that are breaking here?

**Comment by weswigham** [comment]
When you have accessors in a class we now emit accessors in the corresponding declaration file. TS 3.6 supports this, but older versions of TS do not.
