### ISSUE TITLE
PartialRecursive<T> doesn't work for generics

### ISSUE THREAD

**Issue by Dimo99** [microsoft/TypeScript#33655]
**TypeScript Version:**  3.6.3

**Code**

```
type PartialRecursive<T> = T extends object
    ? PartialRecursiveObject<T>
    : T extends (infer U)[]
    ? PartialRecursiveArray<U>
    : T;

type PartialRecursiveObject<T> = {
    [P in keyof T]?: PartialRecursive<T[P]>;
};

interface PartialRecursiveArray<U> extends Array<PartialRecursive<U>> { }


const mergeDeep = <TLeft, TRight>(
    left: TLeft,
    right: TRight,
) => {
    let myVar: PartialRecursive<TLeft & TRight> = left;
};
```

**Expected behavior:** The `left` variable should be assigned to `myVar` as TLeft is subtype to TLeft & TRight. PartialRecursive<T> was tested and it works correct with any defined types but it fails with generics. The intention of the type is to work as PartialRecursive for any objects and arrays.

**Actual behavior:** error   Type 'TLeft' is not assignable to type 'PartialRecursive<TLeft & TRight>'. 

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBACghgJ2ASzgGwEoQMYFcEDOyAbhADwAqAfFALxQVQQAewEAdgCYFQD2ARgCscwALAAoKFKgB+WIhToseQiQgB5ISMpUJ0qAC4GTVh25QAFMnYAzCAigBVAJQBtALp7pc+ElSYcfCJSAEEEBDgQMkddSWkjCgBuCQlQSHk-JUDVUk1hbGAdOigAby8pVxgoaygAawgQXhsGdxkjX0UAlWDyCkr3KmTxAF8hiWs2BBs4bGgO-2UgtTCIqJiTNi4eFciyeazutWiqGhKoYZTxCWxedgJgKABbewBzCAARCAgwYsoAGQgNmAABoGBhkC8ABbAKgWcpQNCA4AJAFA4HwhAQ6EJcFQkESZx0U7wxEPNDtBQLbI9f5IqAAMjBWJhxURQKGo0uQA)

**Comment by RyanCavanaugh** [comment]
> TLeft is subtype to TLeft & TRight

This is backwards. `TLeft & TRight` is a subtype of `TLeft`. This only works in a non-generic position because the partialness causes bidirectional assignability of most types; it is a correct error in a generic position because type parameters can be instantiated with primitives.
