### ISSUE TITLE
Destructured variables shouldn't have access to subsequent variables

### ISSUE THREAD

**Issue by Validark** [microsoft/TypeScript#33659]
**TypeScript Version:**  3.7.0-dev.20190924

**Search Terms:** destructured order computed index

**Code**

```ts
const getLast = ({ [length - 1]: item, length }: Array<string>) => item;
console.log(getLast(["a", "b", "c"]));
```

**Expected behavior:** TS should error, since `length` is defined after its use. TS should force the developer to put `length` first.

**Actual behavior:** Run-time type error

**Playground Link:** https://www.typescriptlang.org/play/#code/MYewdgzgLgBA5gUygGQIbRgXhgCgN4wDaANgmHFABYwC0MAjALoBcMAllAgLYA0Mp5KjAC+rAIIAnCagCeAHmgS25AHwBKLCvacuAbgCwAKFCQQpAHTEQcHIhTooOQgCJUzvs4BG7mM+DPGNTUDQyA

Note: `length` is a global in some TS environments, but if you select the first length and hit f12 (go to definition) on my machine, it takes you to the second `length`. If you compile to JS which supports destructuring, it will error in Chrome saying that you attempted to use `length` before it was defined. If you switch to a version of JS which doesn't support destructuring, it leads to doing `arr[undefined]` and silently returning an `undefined`.

**Comment by RyanCavanaugh** [comment]
Now correctly errors
