### ISSUE TITLE
Implementing only a setter is enough to implement a getter

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#33650]
And vice-versa.

Inspired by #33621

**Code**

```ts
declare class Properties {
    set val(x: number);
}

class BadProps implements Properties {
    private _val: number = 42;
    get val() {
        return this._val;
    }
}

declare class Properties2 {
    get val(): number;
}

class BadProps2 implements Properties2 {
    private _val: number = 42;
    set val(x: number) {
        this._val = 2;
    }
}

const x: Properties = new BadProps();
x.val;
x.val = 12;

const x2: Properties2 = new BadProps2();
x2.val;
x2.val = 12;
```

**Expected behavior:**
Error on `BarProps` for incorrectly implementing `Properties`.
Error on `BarProps2` for incorrectly implementing `Properties2`.

**Actual behavior:**
No error, even with `"useDefineForClassFields": true`.

**Comment by RyanCavanaugh** [comment]
We have eleventydozen issues on this already; let's reopen an existing one if we want to change how it works.
