### ISSUE TITLE
Typescript not inferring object property types

### ISSUE THREAD

**Issue by zerongtonywang** [microsoft/TypeScript#33668]
I feel like TS has all necessary info to infer the types in this screenshot. 

Is there another way to achieve this?

![image](https://user-images.githubusercontent.com/5084735/65843975-a1ff7e80-e377-11e9-95ef-915e6880fabc.png)

**Comment by j-oliveras** [comment]
Please, don't use a screenshot as code, paste it as text.

Any key of type `Styles` can be either an object or a function. In line 19 typescript don't known witch one is so it warns you that it cannot be a function.

**Comment by RyanCavanaugh** [comment]
![image](https://user-images.githubusercontent.com/6685088/65911000-b431ea80-e380-11e9-9271-4bb0e6acdda2.png)
