### ISSUE TITLE
TSX Compiles Successfully, But Pure TS Does Not

### ISSUE THREAD

**Issue by serialprimate** [microsoft/TypeScript#33660]
**TypeScript Version:**  3.7.0-dev.20190928, 3.6.3 and earlier to 2.8 tested

**Search Terms:**

**Code**
Please use TSC command line.

```
import * as React from "react";
import * as ReactDOM from "react-dom";
import { Provider, ProviderProps } from "react-redux";
import { Action, createStore, Reducer, Store } from "redux";

interface IState {
    turns: string[];
}

type TAction1 = "ACTION_1";

interface IAction1 extends Action<TAction1> {
    payload: string;
}

type TAppAction = IAction1; // Assume other action interfaes will be added via union.

// The reducer here doesn't do anything.
const reducer: Reducer<IState, TAppAction> = (state: IState = { turns: [] }) => state;

// The Store type shown is the type returned by createStore.
// A workaround that works is to convert type to Store<IState> which appears to implicitly weaken the type of store.
const store: Store<IState, TAppAction> = createStore(reducer);

const MyApp = () => (React.createElement("div"));
ReactDOM.render(React.createElement(Provider, { store: store }, // ERROR
    React.createElement(MyApp)), document.getElementById("react-root"));

// Another workaround is to use TSX.
// const MyApp = () =>  (<div> </div>);
// ReactDOM.render(
//     <Provider store={store} >
//       <MyApp />
//     </Provider>,
//    document.getElementById("react-root")
// );
```

**Expected behavior:**

Pure TS gives the same result and type checking as for TSX.

**Actual behavior:**

No error for TSX but type resolution error for TS. See the message below. Notice that in the second last line that the assignable types suddenly switch position.
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ store: Store<IState, IAction1>; }' is not assignable to parameter of type 'Attributes & ProviderProps<Action<any>>'.
      Type '{ store: Store<IState, IAction1>; }' is not assignable to type 'ProviderProps<Action<any>>'.
        Types of property 'store' are incompatible.
          Type 'Store<IState, IAction1>' is not assignable to type 'Store<any, Action<any>>'.
            Types of property 'dispatch' are incompatible.
              Type 'Dispatch<IAction1>' is not assignable to type 'Dispatch<Action<any>>'.
                Type 'Action<any>' is not assignable to type 'IAction1'.ts(2769)
index copy.ts(13, 5): 'payload' is declared here.
```
The following dependencies can be used, but have tried various version combinations. The result is always that the TSX compiles but the TS does not.
```
  "dependencies": {
    "react": "^16.10.1",
    "react-dom": "^16.10.1",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4"
  },
  "devDependencies": {
    "@types/react": "^16.9.3",
    "@types/react-dom": "^16.9.1",
    "@types/react-redux": "^7.1.4",
    "typescript": "^3.6.3"
  }
```

**Playground Link:** 

Playground does not allow library dependencies needed for this case.

**Related Issues:** 
[stackoverflow](https://stackoverflow.com/questions/58143249/react-redux-provider-inference-w-typescript)

**Comment by AnyhowStep** [comment]
Just thought I'd bring up that the Playground can pull type declarations from DefinitelyTyped,
[Playground](http://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQoksiK62eMAIgPICycREuUocAtABMStBuGjwA3nAAKxAG7BxWKABplajVpUQw6AL4DipClRijK4gK4APaYzlxFAQXzAIAO11cERgsAGUYaCxdbEdcLV1wyLhzQSt7Z2kGPxCoAjwsOABJcOQQjzo4SrgYByg-VAAuOFQYKGA-AHMAbQBdelM6OhgATzACgBVvGF8-AEY4AF5yTwBhccLuADkAfVnM9py8uKKpmfmsJxC-cXRT-wAeSZ9-WYA+cqq4MGRhgBsIZDiJotNqdfqDEZjOCTMBgO5+RYnZ5zGhwAD0aLgnlQqAcIAKEBgAAstChkXADlo8lh0AB3YC-X5wABGBUBmnEcHUyDgDj8MwAdIMMdCSXB0nEoHASZQ4JIaX4AOTwSQoPzDYntDpC3D+FrirCxLRNGIOSX3YowUpRaGeWHw95LAAULWtTUt1sRihqdUacF6yQAlIt3q6QvQ6CLxmLErLIQVUESILSEcB0MSCvGDT6-IaWcM4EEcCFY1ghSLPHBadAANbIYh8znE0pV2voNPVCCF-yqLTwLMROCli0lELvWlE4C4IkoWE4KDpruMX5T4AwX4F2k4GtYBEZ6qjAkEZoRSg6vXwFqRJrDj0hXQwuHIx2F4JhU9YJ0SrSBiO6+rwLwwx2mAiJOsGCzvE67D4AKRbWgAor8WD4tkTpkOIwCqGQga-nQMFcHwAqUNcWjQTYcFvkhKG7jATpGOomg6B4J7XqxsqmLoIoIRgGDcBgFRVARlHFlg1GoXRQEgbhuiSLgeK0QKHRYDA4m0QAQsMhTiOhIj4HYECEjheGRpinh+ISMqtlAdYNtcFKLryqATKEAAa5aYv++pSbCYEQe8cBOvcmGqO89xoiFrx4SKBE8LwxG7kxTqmZ8cD3AxBhSlelALPI2VYOYrwpalaU+aBaJFSKnzhRlTGvNoxWVHJCnZEpKlqdkmnabpNgGUZgYpb+QA)

**Comment by RyanCavanaugh** [comment]
JSX isn't checked in terms of the underlying function calls precisely because JSX isn't very ergonomic if you do it that way.

The underlying problem here is that TypeScript is warning you that `Provider`'s default props say it can push an `Action<any>` value into an `IAction1` position because that's the default type argument for provider. One solution would be to write

```ts
React.createElement<ProviderProps<TAppAction>>(Provider, { store: store }
```

We don't control any of the react definition files so any particular call not working is a result of how those definitions are written.
