### ISSUE TITLE
tsc 3.6.3: WebGL incorrectly extends interface

### ISSUE THREAD

**Issue by JirkaDellOro** [microsoft/TypeScript#33672]
Situation
- updated tsc to 3.6.3, WebGL 0.0.7, @types/webgl2 0.0.5
- new error: Interface 'WebGL2RenderingContext' incorrectly extends interface 'WebGL2RenderingContextBase'.

Expected behaviour
- no error
- no workaround necessary

Workaround: 
- "skipLibCheck": true  in tsconfig

**Comment by richard-viney** [comment]
Having the same issue in TypeScript 3.6.4.

**Comment by RyanCavanaugh** [comment]
Someone will need to send a PR to DefinitelyTyped

**Comment by richard-viney** [comment]
Removing the `@types/webgl2` package from `package.json` fixed this error for me.

**Comment by RezaRahmati** [comment]
For me I had to add skipLibCheck in tsconfig.json

```
{
  "compilerOptions": {
    ...
    // skip error: Interface 'WebGL2RenderingContext' incorrectly extends interface 'WebGL2RenderingContextBase'.
    // https://github.com/tensorflow/tfjs/issues/4201
    "skipLibCheck": true
  },
  ...
}
```
