### ISSUE TITLE
TypeScrip 3.6 and VS 2019.

### ISSUE THREAD

**Issue by jurion** [microsoft/TypeScript#33677]
Last update completely broken our project. 
Here’s error we are getting : 

Error		Build:Cannot find type definition file for 'requirejs'.

We don’t even USE requirejs in the project. 

What’s goining on ? The only workaround I found is to downgrade TS to 3.1.

**Comment by RyanCavanaugh** [comment]
This isn't a support forum && there isn't enough information here for anyone to be able to help.
