### ISSUE TITLE
Fail to infer type of array elements with property types

### ISSUE THREAD

**Issue by zen0wu** [microsoft/TypeScript#33671]
**TypeScript Version:**  3.6.3

**Search Terms:** property types, fail to infer

**Code**

```ts
interface Base {
  input: unknown;
  output: unknown;
}
interface C1 extends Base {
  input: string;
  output: string;
}
interface C2 extends Base {
  input: number;
  output: number;
}

class G<T extends Base> {
  t: Array<T['input']> = [];
  x: string = '123';
}

const arr: Array<G<C1>> | Array<G<C2>> = [];
arr.map(g => g.x); // Should be able to extract '123' out of G
```

**Expected behavior:** Should compile

**Actual behavior:** It doesn't. `g` is inferred as `any`

**Playground Link:** https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnKgAOArmAFzIkgDWIA9gO4gDc+y9ZpFVtDzbAL65QkWIhQBhAIzIIAD0ggAJhjSYc7YmUoYwUUAHM2BTmG679RoSPDR4SZJIBMcxRBVr0WZHgLaeEBIAWwAjaBMOLh1kILCI3GFcBAAbTDUAcQAeABU3JVV1LAA+X3YeAEEoKDgAT1yAbQByAKaAXVKAXmQGtsj5SwMQQ2RupulnAGYmm2T6ED1kOGrKKpr67Jli0oAfZDW6rM3nbdGevtxlqAA6YLgiAAoRztLDa-kAShZkAHof5AAygALTgpZTIcJLUIpFBgej5GoIMDIcZTJpRZH0GDIDK4XBAA

**Related Issues:**

**Comment by nmain** [comment]
This is called out as a known limitation in the 3.3 release notes:  https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-behavior-for-calling-union-types

**Comment by zenozen** [comment]
Ah, I guess that makes sense. In my case, the type of `g` is really long, make it sorta infeasible to write.

Should we keep this issue around, or I should just close it for now?
