### ISSUE TITLE
Type narrowing fails when in unreachable code due to early return

### ISSUE THREAD

**Issue by TheWyo** [microsoft/TypeScript#33674]
**TypeScript Version:**  3.6.3 (also tested on nightly on playground)

**Search Terms:** unreachable code narrowing early return

**Playground Link:** [Playground demonstration](http://www.typescriptlang.org/play/index.html?allowUnreachableCode=true#code/GYVwdgxgLglg9mABAcwKZQApwM7ZgIwBtUBVMAE1WBjFXIAoBKALkWygCcblEAfRcJWq1yAWABQAbwmJZiDuhAckAIgBycKGSE06KgNwSAvhIk0oqDsACGEVIgCSAWQCeAeXwArVNAnTxcohQ1hxoUKzsXGDIhuIm4hKgkLAIiORwAIIAKgAW3Ex+MnIA9MUKUEpgsYEQCOyIcF6szu5ePlCIALyI-oGBwaHorCoWALYADgBu1oQgqCpFskaxi4i1YPXThF0o6Fi4BMTaVLoMjNVyMMCI9FuMq719so2eAHQDYTtbF0vGQA)

**Expected behavior:**
If you uncomment the early return in the doAThing function (common temp change to disable some stuff for debugging), nothing should happen (allowUnreachableCode is enabled in playground options)

**Actual behavior:**
TypeScript now fails to perform the type-narrow from the if statement, causing a type error on the assignment line within it. An early return should of course produce an unreachable code error, as it would if the option to allow it wasn't turned on, but I'd expect this to otherwise be side-effect free, TypeScript doesn't seem to stop any other type checks just because the code is unreachable.

**Related Issues:** 
There's a lot of narrowing-related issues so apologies if I happened to miss one, but I couldn't find anything quite related to this, as opposed to other types of narrowing issues.

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/26914

**Comment by TheWyo** [comment]
Ah, there we go, one I didn't manage to spot. I'll close this in favour of that then, thanks for finding it.
