### ISSUE TITLE
greater then for array of number should not be valid

### ISSUE THREAD

**Issue by gaspard** [microsoft/TypeScript#33682]
**TypeScript Version:**  3.4.0-dev.201xxxxx
Version 3.7.0-dev.20190928

**Search Terms:**
typescript number or array of number greater than

**Code**

```ts
const n: number | number[] = [4,3] as any
if (n > 4) { // <== TS is fine with this: (number | number[]) > number

}
```

**Expected behavior:**
Type error

**Actual behavior:**
Compiles to erroneous JS code:

```js
var n = [4, 3];
if (n > 4) {
}
```

**Playground Link:**
Don't know of any playground with share support.

**Related Issues:**
Found none...

**Comment by RyanCavanaugh** [comment]
> Don't know of any playground with share support.

[The TypeScript playground](http://www.typescriptlang.org/play/#code/MYewdgziA2CmB00QHMAUAiAEraSA0ABAO4gBO0AJgIToCUA3EA) 😉

This is the intended behavior. Relational comparisons between unions are allowed when the unions overlap in any way that produces a meaningful result.

**Comment by AnyhowStep** [comment]
I've never actually attempted to write such a thing before. I'd normally narrow first before trying to use relational operators.

Does it make sense to narrow `n` to `number` inside the if-statement's `then` block?
Or would that introduce too much overhead to CFA?

**Comment by ilogico** [comment]
> Does it make sense to narrow n to number inside the if-statement's then block?
Actually, `42 > []` is true!

**Comment by AnyhowStep** [comment]
I need to look up the spec regarding such comparisons but I was referring to your specific if-statement construction.

If there was a reasonably small list of cases, it might be worth adding them to CFA.
If the list of cases is large, compared to how often people write code like that, then it wouldn't be worth it.

**Comment by gaspard** [comment]
> > Don't know of any playground with share support.
> 
> [The TypeScript playground](http://www.typescriptlang.org/play/#code/MYewdgziA2CmB00QHMAUAiAEraSA0ABAO4gBO0AJgIToCUA3EA) 😉
> 
> This is the intended behavior. Relational comparisons between unions are allowed when the unions overlap in any way that produces a meaningful result.

Why would TS sometimes accept unions and sometimes not ?

And actually, this is not allowed either:

```ts
function test(x: number) {
    // do something
}

const v: number | number[] = [4,3] as any

test(v) // <== This is not allowed

if (v > 4) { // <== This is allowed ???

}
```

So why does `<` pass when a function call does not (and they would both produce errors at runtime) ?

PS: found how to get a link in the playground... 
http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABFApgZygCgB4C5FggC2ARigE4CUiA3gFCKOID0ziAJnImnESlAAsYYAOZ0AvnToQEGRADd8hUhUQAfAsTLkA2gF1EAXkQ6ALABoAzAYCGaRDbABPKagyZ51VogA8h4wAqQvYw9mBwUA4ANlFwAO4o7FIwwIgeiAB8iKbUNCxsfoHBiKHRsQnsiAD8NVLiQA

**Comment by ilogico** [comment]
```ts
declare const x: bigint;
x > 42 // allowed and makes sense

declare const y: bigint | string;
y > 42 // disallowed

declare const z: bigint | string | number;
z > 42 // allowed
```
The `y` case looks like a bug, since TS considers `bigint` alone to be valid.
I think the comparison operators should have the following overloads:
```ts
function lt(a: number | bigint, b: number | bigint): boolean;
function lt(a: string, b: string): boolean;
```
I don't see any advantage in accepting anything else.

**Comment by nmain** [comment]
> I don't see any advantage in accepting anything else.

I have used `function lt(a: boolean, b: boolean): boolean;` in real code.  Of course, that doesn't mean it was a good idea.  But I've found it to be an intuitive way to express some things:

```ts
declare var prevVal: boolean;
declare var currentVal: boolean;

if (prevVal < currentVal) {
  // val was false, and now it is true
} else if (currentVal < prevVal) {
  // val was true, and now it is false
}
```
