### ISSUE TITLE
Tuples constructed via array literals don't typecheck against tuple constraints

### ISSUE THREAD

**Issue by ccapndave** [Microsoft/TypeScript#3369]
```ts
type Point = [number, number]; var x = [1, 2]; var p: Point = x;
```

In this case `p` won't typecheck because x has been inferred as `number[]` instead of `[number, number]`.  It would be really nice if the type system could check against both types.

**Comment by mhegazy** [comment]
Tuple types are not inferred from arrays, they have to be specified explicitly. so in your example:
```ts
var x: [number, number] = [1, 2];
```
or the type alias way as you specified.

Changing how an array literal type being inferred would be a huge breaking change that would not be feasible at this point; also it is not clear if this would be more helpful than inferring an array in the general case.

**Comment by Arnavion** [comment]
@mhegazy Since tuple types decay to the corresponding array type, will it really be a breaking change?

**Comment by DanielRosenwasser** [comment]
@Arnavion what about the following case?

```TypeScript
var x = [1, 2];
x = [1]
```

**Comment by mhegazy** [comment]
tuples are more restrictive than arrays, since they have a size constraint. just like in @DanielRosenwasser example.

**Comment by Arnavion** [comment]
Ah, right.

**Comment by ccapndave** [comment]
I suppose at this point it could fall back to the least restrictive type, but I do see that its going to be pretty complicated (and maybe a bit unpredictable).

**Comment by mhegazy** [comment]
The problem is there is not really a fall back.. the type is either an array or a tuple.. inferring a tuple would enable some scenarios but would break others and vice versa.

**Comment by FranklinWhale** [comment]
If the length of an array is known and its type matches with a tuple declaration, should the assignment be allowed?

See also #6574 and #7799
