### ISSUE TITLE
Regression v3.6.3 - DeepPartial with flavoured types not working

### ISSUE THREAD

**Issue by majicmoo** [microsoft/TypeScript#33698]
**TypeScript Version:**  v3.6.3
It errors on v3.6.3 and also the nightly build on the playground
Does not error on v3.5.1

**Search Terms:**
nominal types 
deep partial
flavor
flavour

**Code**

```ts

interface Flavoring<FlavorT> {
  _type?: FlavorT
}
type Flavor<T, FlavorT> = T & Flavoring<FlavorT>


type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K]
}


type FlavouredEventId = Flavor<string, 'EventId'>

interface FlavouredEventSummary {
  id: FlavouredEventId
}

interface EventSummary {
  id: string
}


const flavourTest: DeepPartial<FlavouredEventSummary> = { id: 'id'} // Broken in 3.6.3
const test: DeepPartial<EventSummary> = { id: 'id'} // Works in 3.6.3


```

flavour code from here: https://spin.atomicobject.com/2018/01/15/typescript-flexible-nominal-typing/

**Expected behavior:**
It throws no errors
**Actual behavior:**
It throws 
```
Type 'string' is not assignable to type 'undefined'.
```

**Playground Link:** 
https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIBs4DcD2VQDmAPBtngCoB8yA3gFDLID6YAngA4QD8AXGprijkA3HQC+dNp35koRcgBoZgqsgC8ycsgBkyvIRICKlUZI4oAIhAjsACnChhgcdPOob6jANoBpZKGQAawhWHBhNAF1eTV8I5AgAD0gQABMAZ2QcACMAKwgEMGQuZCsbe0dnV3JY6j5qnwjxUykUUlwAVygIFIBRLAhwAEkU9T05NLB8EAIlACI+gbBh2ZM6OlBIWERWo07uhfAAZXaAWxOHVloGfxS+Npw93v6hlNEJdfBoeCRkA7Bjs4XK6MYC3ZATKYEN5rBA4EATZAwXZCCATPilOwOJwuQxkR5-AHnKCsdy0G58Wag2bIMTCZAAenpyAAQlAcMEQP5OQBmAB0ADZedy6LD4YVIGiStZMRUcQTTkSSaMaOTkJSUtTaQymQB1PCBDIBPmC4VAA 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
The updated behavior is more correct - a `string` primitive should not be considered assignable to `object`. You can rewrite as
```ts
type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends (string | boolean | number | symbol) ? T[K] : DeepPartial<T[K]>
};
```
to get the desired behavior
