### ISSUE TITLE
Headers interface missing properties in lib.dom.ts

### ISSUE THREAD

**Issue by Vardner** [microsoft/TypeScript#33697]
**TypeScript Version:**  3.6.3
Headers interface missing properties in lib.dom.ts: keys and values

**Search Terms:** Headers interface keys, values method

**Code**
const headers = new Headers();
headers.keys();
headers.values();

**Here is screenshot:** http://prntscr.com/pd915n;
**Link to mdn doc:** https://developer.mozilla.org/en-US/docs/Web/API/Headers/keys

**Comment by kettanaito** [comment]
If anyone still encounters this, _you have to add `dom.iterable` to `lib` in order for the iterable methods like `keys`, `values`, and `entries` to be defined on the `Headers` class:

```diff
// tsconfig.json
{
  "compilerOptions": {
    "lib": [
      "dom"
+     "dom.iterable"
    ],
  }
}
```
