### ISSUE TITLE
Help text in object-literal @property JSDoc missing from Intellisense when hovering over that property

### ISSUE THREAD

**Issue by justingrant** [microsoft/TypeScript#33695]
**TypeScript Version:**  typescript@3.7.0-dev.20190928

**Search Terms:**
typescript jsdoc object property help text intellisense

**Code**

```ts
/**
 * @typedef {Object} Works - This type shows property help
 */
interface Works {
  /** This is property `a` */
  a: number;
}
// If you hover over `a`, the JSDoc help text is shown
// (as expected) for that property.
const y: Works = { a: 1 };

/**
 * @typedef {Object} Broken - Property help is missing
 * @property {number} a - This help text never shows up
 */
interface Broken {
  a: number;
}
// If you hover over `a`, the JSDoc help text is missing
const x: Broken = { a: 1 };
```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/277214/65926656-24edfc80-e3ab-11e9-8fad-b927cb6d5751.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/277214/65926674-3d5e1700-e3ab-11e9-8abe-367eaf088971.png)

**Playground Link:**
https://codesandbox.io/s/autumn-architecture-m084y

https://www.typescriptlang.org/play/#code/PQKhFgCgAIWgBALgTwA4FMAm6Bm0DeA8gEYBW6AxogL7QDqA9gE4DWAztALTQAqAFgEsOKDNDZ8GAdw6omDDExTQ+6ADaoosYFAEA7ROiY4AhhXT1m7Apuig4-IdEez5hpQANj7rTeMAuaF0AVwBbYkMAbihqKGBgaABJPGQGIOUGADdDaEzsz3cAGmhEFWgAKQBlABEGCmU1VGL0AA9EJw5xKV1Y+IAKYw4WjCosAEpoHGZivmM2lwUUADooCgZdNjbkAMZWDgBeAmh-aABGaGooyFiwTTgkNCxcAhJyKloAITkWdF0uaAAFOQLZD1dTtaAhIRsPQAc1uCHmbhB+GCYUMtGMfwcHBUYIMrUC6CyTDEEmk0CCGhgIG0kD0BiMpnMnwY31++F8AVR4SYlxikDiiWSqXSxJyYvyRRK5kqNTquMa+LajkhbGhujhkFW6zazQCLLZ0AO+COATOFygUCAA

**Related Issues:** 
* #9620 seems to claim that this problem was fixed by #9621, but clearly it's not fully fixed.
* #18358 also seems to claim to have fixed this problem, but the "working" example shown uses the "per-property" help text (like `Works` in this task), not the help text in `@property` tags.

I also found other issues which seemed related to class properties or destructured properties, but I'm assuming that this object-literal-properties issue may be different.  Here's a few: #20894, #4261, #26611

**Comment by sandersn** [comment]
`@typedef` only works in JS files. Even if it worked in TS files, because `interface` is self-contained in Typescript, Typescript has no reason to look at jsdoc for additional info.
