### ISSUE TITLE
Compiler fails to infer type in overloaded functions

### ISSUE THREAD

**Issue by boris-kolar** [microsoft/TypeScript#33704]
**TypeScript Version:**  3.6.3
**Search Terms:** overload overloaded infer type flow

**Code**
```ts
function foo(): void
function foo(a: string, b: string): void
function foo(a?: string, b?: string): void {
    if (!a) return
    console.log(a.length + b.length)
}
```

**Expected behavior:**
The code compiles (the compiler deduces `b != null` from the set of possible overloads)

**Actual behavior:**
bug.ts:5:28 - error TS2532: Object is possibly 'undefined'.

**Playground Link:**
https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcAUBKAXIgbnGAEwChRJYFlU0BDHAZygCcYwBzAGkQCMHnW22PARJlo8JCnQ0A-Hxbsu3OYkYLBOfEUQBvYogOIYwRGgCENDIiYBTKCCZh9hiAnpwANjYB0HuG1pfG3YoAAtEAGoeIJDQjGIAXyA

**Related Issues:** N/A

**Comment by RyanCavanaugh** [comment]
Duplicate #14515

**Comment by AnyhowStep** [comment]
Overloads are a real pain in the butt, honestly.
Often times, if you're not dealing with generic functions, I find that you're better off using rest args on tuple types.

```
function foo(...args : []|[number, number]): void {
    if (args.length == 0) return;
    const [a, b] = args;
    console.log(a.length + b.length);
}

foo(); //OK
foo(1,2); //OK
foo(1); //Error
```

I'm on mobile now, so I might have made a mistake but the above should work

**Comment by AnyhowStep** [comment]
Another example I posted on Gitter earlier on,
```ts
interface Data {
    someUsefulPieceOfInfo : string
}
function callback (...args : [Error]|[null|undefined, Data]) {
    if (args[0] == undefined) {
        console.log(args[1].someUsefulPieceOfInfo);
    } else {
        console.error(args[0].message);
    }
}

callback(new Error("blah"));
callback(undefined, { someUsefulPieceOfInfo : "Hello, world" });
```

[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUMg5AZwHsBbCAVSIhgFcAbABWAiQHkYBJEGE5AFzEwUUAHNcAX1z0QCMMBIhkCOAwYAjRAGtkACgB0RuFDFFByANoBRKFBJQAugB9LIRg2d0QAE1qgIHwAaNAw4RwBKHHxCYBh9EzNLAAZHZABedORvPxgAnyi8QmKVJVIGCAMGEjE9RKJLAEZHA1IKalpGFjYITh4+CIBuGIJJZAgGGmiSwgQykgqDaHsoOtMG1IMKIiI4MQghkeRpaVxVdS0EbT0QCAB3ZFsVvQAiDQY4AAsXiMPzzR0ehy-luwRwxHIVBo9GYrA43F4-CELwAEhNqiE7g4GD4XschkA)

**Comment by afreix** [comment]
@AnyhowStep in response to https://github.com/microsoft/TypeScript/issues/33704#issuecomment-537123335

Is there any workaround for when you are using generics?
```
export function anyLoading<TData1>(
  responses: [Response<TData1>]
): responses is [ResponseSuccessful<TData1>];
export function anyLoading<TData1, TData2>(
  responses: [Response<TData1>, Response<TData2>]
): responses is [ResponseSuccessful<TData1>, ResponseSuccessful<TData2>];
export function anyLoading(responses: Response<any>[]) {
  return !responses.some(isLoading);
}
```

I'd like be able to define my overloads like above and be able to call `anyLoading` with a parameter of type `[Response<TData1>] | [ResponseSuccessful<TData1>, ResponseSuccessful<TData2>]`

**Comment by AnyhowStep** [comment]
Seems like the same pattern as `Promise.all()`
