### ISSUE TITLE
CI Status Thread

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#33716]
The bot will post _here_ when a rolling build (rather than a triggered PR associated build) fails; simply subscribe to this thread for updates.

**Comment by sandersn** [comment]
oh. I wondered why I stopped getting those mails!

**Comment by jakebailey** [comment]
I'm going to close this; these kinds of runs have been superseded by the new error deltas: https://github.com/microsoft/typescript-error-deltas

The only remaining test of this kind is the RWC tests, which aren't (yet) public and never posted here or used `typescript-bot`'s TS fork.
