### ISSUE TITLE
No errors for duplicate index signatures in global intrinsic types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3373]
From `tests\cases\conformance\types\members\duplicateNumericIndexers.ts`:

```TypeScript
interface Number {
    [x: number]: string;
    [x: number]: string;
}

interface String {
    [x: number]: string;
    [x: number]: string;
}

interface Array<T> {
    [x: number]: T;
    [x: number]: T;
}

class C {
    [x: number]: string;
    [x: number]: string;
}

interface I {
    [x: number]: string;
    [x: number]: string;
}

var a: {
    [x: number]: string;
    [x: number]: string;
}
```

The last 3 declarations will have at least one error on the index signatures. Notice there are no errors within the intrinsic types.

**Comment by YuichiNukiyama** [comment]
This issue already had been resolved.  See [duplicateNumericIndexers.errors.txt](https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/duplicateNumericIndexers.errors.txt).

**Comment by mhegazy** [comment]
thanks @YuichiNukiyama
