### ISSUE TITLE
Readonly-ness is lost in function call

### ISSUE THREAD

**Issue by thecotne** [microsoft/TypeScript#33748]
**TypeScript Version:**  3.6.3

**Search Terms:**

**Code**

```ts
type EditablePerson = {
    name: string
}
type ReadonlyPerson = {
    readonly name: string
}

const editablecotne: EditablePerson = {
    name: 'cotne'
}
const readonlycotne: ReadonlyPerson = {
    name: 'cotne'
}

function updateName (person: EditablePerson, newName: string) {
    person.name = newName
}

//ok
editablecotne.name = 'not so cotne'
updateName(editablecotne, 'not so cotne')

//err
readonlycotne.name = 'not so cotne'// ok
updateName(readonlycotne, 'not so cotne')//fuck!
```

**Expected behavior:**
you can't modify readonly property of object

**Actual behavior:**
you can pass object to function and edit it there

**Playground Link:**  [try](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAogJgS2AQwEYBsIAUICcDOA9gHZQC8UA3gLABQUDUxyAthAFxT7C4LEDmdAL51QkKACUIyOCXQgcBEuSp1GUXNNnF5TVhy48+g2iNp0AxiW5QIiFBghXgxA-CRpMioqQo16jMxsnADkzq4hwpbWwBpaciDhBlIyCd7KfmqB+qFJkaZ0dABmAK7EFsAIyiVgcMjAEABy+lAAFJBKxJzuDl54PgA0TBAA7s3BhrwCAJSqAQwdPgB0QdAUrmP6Uea0APS7hADWdHYejkkrLRQhxISxRFB5dDV1DeMQrae9TneuQzd3LiER6-CAhaaFPa7PC4OiaVI6RKgy5sFQA+7AvL7KBHZ61epNfSteHaeRJf63DEglxg6b7UoWQ4AQjoQA)

**Related Issues:**

**Comment by jack-williams** [comment]
Duplicate of #13347, I think.

**Comment by thecotne** [comment]
@jack-williams looks similar but i am not sure if it's same problem (description looks cryptic to me)

**Comment by jack-williams** [comment]
The issue description exactly matches your scenario.

> Interface with readonly property (`ReadonlyPerson`) is assignable to interface with mutable property (`EditablePerson`)

_Assignable_ in TypeScript applies both to assignment expressions (like in #13347) and passing arguments to functions (like in this issues).

**Comment by thecotne** [comment]
@jack-williams you are right...
