### ISSUE TITLE
"amd" missing from error message for error TS1323

### ISSUE THREAD

**Issue by dasa** [microsoft/TypeScript#33762]
**TypeScript Version:**  3.7.0-dev.20191002

**Search Terms:**
amd, dynamic import, error message

**Code**

```ts
import("./mymodule.js");
```

"module" set to "es2015" in `tsconfig.json`.

**Expected behavior:**

`error TS1323: Dynamic import is only supported when '--module' flag is 'amd' or  'commonjs' or 'esNext' or 'umd'.`

**Actual behavior:**

`error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.`

**Playground Link:** 

**Related Issues:**

**Comment by dasa** [comment]
Updated expected text to include "umd" since it's supported as well.

**Comment by DanielRosenwasser** [comment]
Agreed - also, let's just fix the grammatical issues too.

```
Dynamic imports are only supported when the '--module' flag is set to 'esnext', 'commonjs'  'amd', 'system', or 'umd'.
```

**Comment by dasa** [comment]
Missing comma 😉 

`Dynamic imports are only supported when the '--module' flag is set to 'esnext', 'commonjs', 'amd', 'system', or 'umd'.`

**Comment by DanielRosenwasser** [comment]
Fixed thanks!

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
