### ISSUE TITLE
Problem with type intersection and typeof

### ISSUE THREAD

**Issue by asfernandes** [microsoft/TypeScript#33760]
**TypeScript Version:**  3.6.3

```ts
interface Type {
	obj: {
		a: number,
		b: number
	}[];
}

function f1() {
	return {
		obj: [
			{
				a: 1,
				b: 2,
				c: 3
			},
			{
				a: 11,
				b: 22,
				c: 33
			}
		]
	};
}

function f2() {
	const ret = f1();

	return ret as Type & typeof ret;
}

const t = f2();

function f3(obj: typeof t['obj'][number]): number {
	return obj.c;
}

const z = t.obj.map(o => f3(o));
```

I expect that the code works but the last line results in compilation error:

```txt
Argument of type '{ a: number; b: number; }' is not assignable to parameter of type '{ a: number; b: number; } & { a: number; b: number; c: number; }'.
  Property 'c' is missing in type '{ a: number; b: number; }' but required in type '{ a: number; b: number; c: number; }'.ts(2345)
```

The variable `o` implicitly gets the wrong `{ a: number; b: number; }` type instead the correct `{ a: number; b: number; c: number; }`.

**Comment by RyanCavanaugh** [comment]
It's basically nonsensical to intersect a tuple type with a variable-length array type; did you mean to write this instead?
```ts
interface Type {
	obj: { a: number, b: number }[];
}
```

The error is correct; if you took `[]` (a valid `typeof ret`) and "intersected" it with `[{ a: 0, b: 0 }]` (a valid `Type["obj"]`, then the 0th element would lack a `c` property.

**Comment by asfernandes** [comment]
> It's basically nonsensical to intersect a tuple type with a variable-length array type; did you mean to write this instead?
> 

Yes, sure. Typo to create small reproducable test case. I edited it.

Note that type of `t` (viewing in vscode) is

```ts
Type & {
    obj: {
        a: number;
        b: number;
        c: number;
    }[];
}
```

And all of this is valid:

```ts
t.obj[0].a = 1;
t.obj[1].a = 1;
t.obj[2].a = 1;
t.obj[3].a = 1;
```

So `t.obj.map(o => f3(o))` should be valid.

**Comment by asfernandes** [comment]
It's also interesting that it works if you change

```ts
return ret as Type & typeof ret;
```

to

```ts
return ret as (typeof ret) & Type;
```

But that does not change in all situations.
