### ISSUE TITLE
 Argument of type '(error: ErrorHandler, res: Response) => void' is not assignable to parameter of type 'PathParams'.

### ISSUE THREAD

**Issue by slim-hmidi** [microsoft/TypeScript#33764]
**TypeScript Version:**  3.5.3

**Search Terms:**

**Code**
error.ts:
```ts
import { Response } from "express";

export class ErrorHandler extends Error {
  statusCode: number;
  message: string;
  constructor(statusCode: number, message: string) {
    super();
    this.statusCode = statusCode;
    this.message = message;
  }
}


export const errorMiddleware = (error: ErrorHandler, res: Response) => {

  const status = error.statusCode || 500;
  const message = error.message || 'Internal Server Error';
  res.status(status).send({
    message
  })

}
```

app.ts:
```ts
import express, { Express } from "express";
import bodyParser from "body-parser";
import cors from "cors";
import routes from "./routes/index";
import db from "./database/config";
import { errorMiddleware } from "./utils/error";

db.once("open", () => console.log("connected to the database"));

// checks if connection with the database is successful
db.on("error", console.error.bind(console, "MongoDB connection error:"));

const app = express();

app.use(cors());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use("/", routes);
app.use(errorMiddleware);

app.listen(5000, () => {
  console.log("Server runs on 127.0.0.1:5000");
});
 ```

**Expected behavior:**
No errors when I add the `errorMiddleware`
**Actual behavior:**
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(error: ErrorHandler, res: Response) => void' is not assignable to parameter of type 'PathParams'.
      Type '(error: ErrorHandler, res: Response) => void' is missing the following properties from type '(string | RegExp)[]': pop, push, concat, join, and 25 more.ts(2769)
index.d.ts(55, 5): The last overload is declared here.
```
**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This doesn't appear to be a TypeScript bug.

**Comment by antoanelenkov** [comment]
You are missing the request parameter in arguments of the middleware. It should be (error: ErrorHandler, req: Request, res: Response)

**Comment by nicolak** [comment]
I have the same problem. Did you manage to solve it?

**Comment by nicolak** [comment]
Function:

`const handleError = (error: Error, req: Request, res: Response, next: NextFunction) => { ... }`

Call, on `server.ts`:

`server.use(handleError);`

Error Typescript:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(error: Error, req: Request, res: Response, next: NextFunction) => Response<any, Record<string, any>>' is not assignable to parameter of type 'PathParams'.ts(2769)
```

If you do it like this, it works normally:

```
//@ts-ignore
server.use(handleError);
```

Can anyone help?

**Comment by srirampc** [comment]
This is not a typescript bug. But, I am adding here in response to the [comment above](https://github.com/microsoft/TypeScript/issues/33764#issuecomment-2504612589) case any one else faces the following issue (since googling for this issue leads to this page):

> Error Typescript:
> 
> ```
> No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '(error: Error, req: Request, res: Response, next: NextFunction) => Response<any, Record<string, any>>' is not assignable to parameter of type 'PathParams'.ts(2769)
> ```

One of the reasons why this might happen is when there is a different return type in the error handler function. For example, the return statement in the following error handler can cause this issue.

```typescript
 const errorHandler = (
  error: Error,
  request: e.Request,
  response: e.Response,
  next: e.NextFunction,
) => {
  if (error.name === 'ValidationError') {
    return response.status(400).send({ error: error.message })
  } 
  next(error)
}
```
Changing it to the following no longer produces the error:

```typescript
 const errorHandler = (
  error: Error,
  request: e.Request,
  response: e.Response,
  next: e.NextFunction,
) => {
  if (error.name === 'ValidationError') {
     response.status(400).send({ error: error.message })
  } else {
     next(error)
  }
}
```

It would be nice to have typescript produce a warning that different paths through a function lead to different return types instead of deducing a union type.
