### ISSUE TITLE
getTypeAtLocation fails for module-functions re-exported to global scope

### ISSUE THREAD

**Issue by aslatter** [microsoft/TypeScript#33763]
**TypeScript Version:**  3.7.0-dev.20191002

**Search Terms:** package module global export

**Code**

The repro requires multiple files.

If I have a TypeScript project which, in an ambient TypeScript file, imports from a module and then re-exports a portion of the module into the global-scope, when I use the re-exported portions of the module through the global-scope *getTypeAtLocation* returns a type of *any* (with *intrinsicName* set to `"error"`, if that means anything) for the functions.

The module I would like to make available through global-scope, `node_modules/demo-package/index.d.ts`:

```ts

export declare namespace Foo {
    /**
     * A function for doing cool things
     * @param p a parameter
     */
    export function bar(p: string): string;
}
```

The import-then-declare-globally of the demo-package (made available through the *typeRoots* option of my *tsconfig.json*) `node_modules/type-roots/custom/index.d.ts`:

```ts
import {
	Foo
} from "demo-package";

declare global {
	export {
		Foo
	};
}
```

And then in the file which uses the global-import `main.ts`:

```ts

import * as demo_package from "demo-package";

export function main() {
    Foo.bar("hello"); // inferred type of 'bar' is any
    demo_package.Foo.bar("goodbye"); // inferred type of 'bar' is string->string
}
```

**Expected behavior:**

I expected both functions referenced in the *main* function above to have the same inferred type. This worked in TypeScript 3.6 and earlier.

**Actual behavior:**

Calling *getTypeAtLocation* on the first *Foo.bar* in *main* returns *any*.

Demonstration use of TS APIs: https://github.com/aslatter/ts-demo-global-error/tree/127785c2204cbf6e60163bfebbb74b4738e85f0f

The 'input' folder represents the demo program above. The 'processor' folder attempts to use TypeScript APIs to call *getTypeAtLocation* on the two functions used in *main.ts*.

To run the demo program, check out the repo and then:

```sh
cd processor
npm install
npx tsc -p .
node out
```

**Playground Link:** 

**Related Issues:**

**Comment by aslatter** [comment]
A couple of work-arounds I'm going to experiment with.

Setting up the augmentation of the global-scope like this:

```ts
import {
	Foo as FooImported
} from "demo-package";

declare global {
	export const Foo = FooImported;
}
```

Or this:

```ts
import {
	Foo as FooImported
} from "demo-package";

declare global {
	export const Foo: typeof FooImported;
}
```

**Comment by weswigham** [comment]
While we shouldn't crash on it (so this is still an issue), for your own reference,
```ts
import {
	Foo
} from "demo-package";

declare global {
	export {
		Foo
	};
}
```
isn't a valid global augmentation. It reports `Exports and export assignments are not permitted in module augmentations.`.

**Comment by aslatter** [comment]
Okay, I'll take this as an opportunity to move to something supported.

If its helpful, I think I was using *export* instead of the alternatives I mentioned because it made for a better in-IDE experience as it pulls along the documentation for the root element.

**Comment by aslatter** [comment]
More details on why I thought *export* was a good idea: at the time I wanted to make a class globally available, and *export* pulls across the type the constructor and the documentation all in one go, which was super handy.

I'm not trying to make any classes globally-available any-more so I'm okay with the alternate approaches.
