### ISSUE TITLE
Incorrect declaration emit for allowJs JavaScript class with static members imported from other files

### ISSUE THREAD

**Issue by cspotcode** [microsoft/TypeScript#33777]
**TypeScript Version:**  3.7.0-dev.20191002

**Search Terms:**

**Code**

Emitted `index.d.ts` from these JS files using `--declaration --allowJs` has an avoidable semantic error.  It looks like the compiler usually avoids this error, but in this particular case it doesn't.

```ts
// foo.js
function foo() {}
export {foo}
```
```ts
// index.js
import {foo} from './foo'

export {MyClass}
function MyClass() {}
MyClass.prototype = {
  method() {}
}
MyClass.foo = foo
```

**Expected behavior:**

This declaration is emitted:

```ts
// index.d.ts
export function MyClass(): void;
export class MyClass {
    method(): void;
}
export namespace MyClass {
    export { foo };
    import { foo } from "./foo";
}
export {};
```

**Actual behavior:**

This declaration is emitted:

```ts
// index.d.ts
export function MyClass(): void;
export class MyClass {
    method(): void;
}
export namespace MyClass {
    export { foo };
}
declare var foo: typeof foo;     // <-- foo circularly references self
import { foo } from "./foo";     // <-- import foo conflicts with var foo
export {};
//# sourceMappingURL=index.d.ts.map
```

It appears to be triggered by the combination of both `function MyClass` and `MyClass.prototype = ` assignment.  Removing one or the other fixes the bug, so that the `import {foo} from './foo';` is nested within `export namespace MyClass` as in the "expected behavior" above.

**Playground Link:** 

**Related Issues:**

**Comment by weswigham** [comment]
To the OP: This should now be fixed on `master` and in the next 3.7 cut (which should be final), by #34786 

Your expected emit is a lil off though; we emit:
```ts
//// [foo.d.ts]
export function foo(): void;
//// [index.d.ts]
export function MyClass(): void;
export class MyClass {
    method(): void;
}
export namespace MyClass {
    export { foo };
}
import { foo } from "./foo";
```

you're not allowed to have an `import` statement in a namespace, and the top-level `export {};` is unneeded in your example (as something in the file is exported, so the file's definitely a module, and there's no privates which need their scoping preserved)~
