### ISSUE TITLE
Declared class + experimentalDecorators + emitMetadata causes a runtime error

### ISSUE THREAD

**Issue by BrighTide** [microsoft/TypeScript#33774]
This playground shows the issue 

https://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true&ts=3.7-Beta#code/CYUwxgNghgTiAEkoGdnwCoAsCWyDq2EEAQiAJIB2kArqMJViACK4AuAghcMXFANZZsFAOZoA3gF8AUFIBm1Kq2wB7CvBAVqAWxAwoAIwggAFADcoEaiABc8fcuVGoFAJTwxU+F-hxW1GGrGrLDCIKy2zgCeADTwAA4wynG6rJEA0iCRtsisMELCsaDIYHlxrMowtgAKickwqUwgxaXlMG4AvAB87p7efUUl2GUVAHQa2roGRvDt8OaWIL1e0tJSSKjwALKRAMLQGx59AALjOnqGJrlWLkvx1IbYYPBakehNrABiCmBKqsYutkE+EIJHIVEsdAYmGYbE43F4AhwInEtz6vn8agAjLcVkA

When a decorator is added to a class method it looks like typescript will automatically add the metadata design decorators to the method. This becomes an issue when the method decorator has a parameterType or returnType that's a declared class, as the Class will be referenced by the metadata decorator but won't actually exist.

Functions of interest (from what I could grok with the debugger in typescript 3.5.3)

- generateClassElementDecorationExpression: Makes the decision to add the designtime decoratiors
- serializeParameterTypesOfNode: Makes the final decision on what should end up in the metadata decorator
- isClassLike: Decides if something is a class, not sure if making this understand whether something is a real class or just declared would be the answer?

Thanks for all the hard work, on metadata and typescript in general!

**Comment by RyanCavanaugh** [comment]
The intent of the `declare` keyword is to *describe existing structures*. Writing `declare class X { }` when there isn't an `X` value present is a programmer error, the same way that you can't draw a bridge on a map and then drive your car over the water.

**Comment by BrighTide** [comment]
Hmmm, ok I guess that makes sense. We have a system where our microservices can bundle up their types and emit them as a module for other services to consume using a "declarations only" typescript job. I guess we'll just have to make sure the real class is emitted to.

Cheers!
