### ISSUE TITLE
New syntax for advanced typing array of arguments

### ISSUE THREAD

**Issue by sviat9440** [microsoft/TypeScript#33778]
## Search Terms
new syntax, advanced types, generic, array of arguments

## Suggestion
Hi, everybody!
I think it would be cool to create a solution to [this](https://stackoverflow.com/questions/58083412/advanced-typing-array-of-input-arguments) problem.

If you want to control the typing of the result of a function based on an unlimited number of incoming arguments, you will need a huge number of overloads.

## Use Cases
For example, you have a class that contains a property configuration:

```
class PropertyConstructor<T> {
  type: T;
}

class PropertyConfiguration<T, S extends keyof any> {
   constructor(
      public propertyKey: S,
      public propertyConstructor: new () => PropertyConstructor<T>,
   ) {}
}
```

Next, create several inheritors of constructors:

```
class StringPropertyConstructor extends PropertyConstructor<string> {
}

class NumberPropertyConstructor extends PropertyConstructor<number> {
}
```

Next, create function, that will build class with property configs:

```
type Join<T, S extends keyof any> = {[P in S]: T};

function CreateClass<T1, S1 extends keyof any>(p1: PropertyConfiguration<T1, S1>): new () => Join<T1, S1>;
function CreateClass<T1, S1 extends keyof any, T2, S2 extends keyof any>(
  p1: PropertyConfiguration<T1, S1>,
  p2: PropertyConfiguration<T2, S2>,
): new () => Join<T1, S1> & Join<T2, S2>;
// ... And so on. It's very uncomfortable and ugly.
function CreateClass(...properties: Array<PropertyConfiguration<any, keyof any>>): new () => any {
  class NewClass {}
  // Here was the logic of executing property constructors
  return NewClass;
}
```

And create some instances of PropertyConfiguration:

```
const property1 = new PropertyConfiguration('property1', StringPropertyConstructor);
const property2 = new PropertyConfiguration('property2', NumberPropertyConstructor);
```

Funnaly, Let's try to apply it:

```
class A extends CreateClass(property1, property2) {
}

const a = new A();
a.property1 // string;
a.property2 // number;
```

It's works! But, very uncomfortable and ugly. For example if you want to create class with ten properties, you need to implement corresponded overloads.

## Examples
As I see the solution to this problem:

```
type Join<T, S extends keyof any> = {[P in S]: T};

type Union<T extends Array<any>> = ... 
/*
built-in type for compare array types.
Example:
Union<[string, number]> => string & number
Union<[Join<string, 'property1'>, Join<number, 'property2'>]> => Join<string, 'property1'> & Join<number, 'property2'>
*/

function CreateClass<N extends number, T{N}, S{N} extends keyof any>(
  ...properties: [PropertyConfiguration<T{N}, S{N}>]
): new () => Union<[Join<T{N}, S{N}]> {
  class NewClass {}
  // Here was the logic of executing property constructors
  return NewClass;
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sviat9440** [comment]
Well, or a more simple example:

You can look at the typification of methods Promise.all or Promise.race...

![image](https://user-images.githubusercontent.com/13107421/66106424-876f1480-e5c6-11e9-8cac-dc0bc9b76399.png)

**Comment by AnyhowStep** [comment]
Rest arguments and tuple types?

**Comment by sviat9440** [comment]
@AnyhowStep +

**Comment by AnyhowStep** [comment]
I'm on mobile, so, I'm not too sure if this would work but your Promise.all thing can probably be written with far fewer overloads,

```ts
//We want T to distribute
type UnwrapPromiseLike<T> = T extends PromiseLike<infer U> ? U : T;
//snip

//for empty tuple
all () : Promise<[]>;
//for non-empty tuple
all<ArrT extends any[]> (arr : ArrT & {"0":any}) : Promise<{ [i in keyof ArrT] : UnwrapPromiseLike<ArrT[i]> }>;
//for non-tuple array
all<ArrT extends any[]> (arr : ArrT) : Promise<{ [i in keyof ArrT] : UnwrapPromiseLike<ArrT[i]> }>;
```

**Comment by sviat9440** [comment]
@AnyhowStep Promise.all is a method of Typescript npm lib. It is not my method.

**Comment by AnyhowStep** [comment]
I know. I'm just saying it can be written to handle tuples of arbitrary length

**Comment by sviat9440** [comment]
@AnyhowStep Is it possible to implement something like Union from the first example?

**Comment by AnyhowStep** [comment]
What you're looking for is `UnionToIntersection<U>`.

https://github.com/AnyhowStep/type-mapping/blob/master/src/type-util/union-to-intersection.ts

**Comment by AnyhowStep** [comment]
Sorry for the double post but,

https://github.com/microsoft/TypeScript/issues/29594#issuecomment-507701193

https://github.com/microsoft/TypeScript/issues/29594

**Comment by AnyhowStep** [comment]
Copy-pasting my comment on https://github.com/microsoft/TypeScript/pull/33707 over here.

This is better,
```ts
type Awaited<T> =
    T extends undefined ?
    T :
    T extends PromiseLike<infer U> ?
    U :
    T
;
declare function all<T extends readonly any[]>(
    values: T
): Promise<{ -readonly [P in keyof T]: Awaited<T[P]> }>;

declare const numArr: number[];

//const newAll0: Promise<never[]>
const newAll0 = all([]);
//const newAll1: Promise<(string | number | boolean)[]>
const newAll1 = all([1, "2", true]);
//const newAll2: Promise<number[]>
const newAll2 = all(numArr);

//const curAll0: Promise<never[]>
const curAll0 = Promise.all([]);
//const curAll1: Promise<(string | number | boolean)[]>
const curAll1 = Promise.all([1, "2", true]);
//const curAll2: Promise<number[]>
const curAll2 = Promise.all(numArr);

//for empty tuple
declare function betterAll (arr : []) : Promise<[]>;
//for non-empty tuple
declare function betterAll<ArrT extends readonly [any, ...any[]]>(
    arr: ArrT
): Promise<{ -readonly [i in keyof ArrT]: Awaited<ArrT[i]> }>;
//for non-tuple array
declare function betterAll<ArrT extends readonly any[]>(
    arr: ArrT
): Promise<{ -readonly [i in keyof ArrT]: Awaited<ArrT[i]> }>;

//const betterAll0: Promise<[]>
const betterAll0 = betterAll([]);
//const betterAll1: Promise<[number, string, boolean]>
const betterAll1 = betterAll([1, "2", true]);
//const betterAll2: Promise<number[]>
const betterAll2 = betterAll(numArr);
```
[Playground](http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=44&pc=38#code/C4TwDgpgBAgg7gQwJbAgEwDwBUB8UC8AsAFBRlRZQQAeqAdmgM5QCuDEAZknelAPwlyFKAC5B5SjXpMoABQBOAewC2SRhAAySANYQM3DhHlQAqngGlyJ0eLJYSAbhJoIAYwA2CedA5tXwJEU6KAR3d2wqWggGZm8ENCD3EBC6EABtAF0cAApbKAA3UJYIRhEKEgBKMoUVNT0AbygAWjiEuiSoNNkobihdEEUOCgyy+GRUTCwurKgAXxwnYmc3T28oVyDGYCg6FmUYeXky3eUAIyNMxZIAemuNui2diDgYMIAGaqVVdQwefIusiR7o8eC93gQQmFspkKotbsDtqDXu4AIyfWo-bJbeTcADmUAAPjs9udjETTopFO4IAg6BVMjggZtEc9kSiIaF3NCUQAaKAAIgATPy+cB5MUMrCbndmU8we5BejvnoTqSGUyHiz5YKOVCTgd5FKlsR4bLXCx5MiPnIvnVfhB-vJ1cQEesLVaITVlQA6TnQyVwmWat2WsJom0YvRYsV4wnEs5GOMUqk0unO13m0Ooz229S+qFpXkC4Wi8UQAPSjPusKKiPK34kgGMl1m6sKnOR-Nc-WHI3SjiKYwQZRgUBQYAsMDU5YeLw+PwBIJQc7AVBZqDZLzGMow0R1u0MwMD4x0IJNYej5ITqcQGered0fyBYIrtfIjAGyRRGJQVqJZJpLSIB8t6oFAZkWS5JYZBbqMhz2MQVT7j8jQtDSbQdGkSA9ME-SDLA8EjLAiAoOgH7wVhMzzEeg47Ge17UiEhwICAd5zlAviPouL4QKuRjvp+kTSLE6H-ik6SQXksEEfICFIV6dqoX+7QAdhvR4UMn5EWMpGYJ+lF4NRJCVrKr78e8SoHoCLbBmZWZvBCdnIv6RqmrZvFvmGlk-GkqpGHy2J4nyybUrS1muk5YaOR55lcoWfJCiK45lhWJpBo8kUKt5KqNk64WmTFWY6vgy6Fc5PaGg4QA)

See `all` (this PR) vs `Promise.all` (current impl) vs `betterAll` (mine)

**Comment by sviat9440** [comment]
Thank you for solution. It's really helps me!
