### ISSUE TITLE
Should not give suggestion when writing a method in a class.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#3377]
*Edit by @DanielRosenwasser:*

- [ ] Allow new identifiers (i.e. show a builder).
- [ ] Suggest "appropriate" completions.

Original:
________

![image](https://cloud.githubusercontent.com/assets/970430/7977419/76dc835c-0abd-11e5-81af-9ca6497a8486.png)

Certainly something like `constructor` should still be there (maybe methods/properties in parent class or implemented interface), but others should be hidden.

**Comment by mhegazy** [comment]
The problem is we do not know if you are typing a modifier or just an identifier. Ideally we should only show "public", "private", "protected" and "static"; but at least we should mark this as an identifier definition location to get the builder.

**Comment by mihailik** [comment]
This position in the

**Comment by mhegazy** [comment]
subsumed by https://github.com/Microsoft/TypeScript/issues/7158
