### ISSUE TITLE
[Type Validation] Arrays can be assigned to string indexed typed vars

### ISSUE THREAD

**Issue by mtrimolet** [microsoft/TypeScript#33786]
**TypeScript Version:**  3.6.3

**Search Terms:** Array, type validation, object, index, number, string

**Code**

```ts
const foo: { [key: string]: any } = [1, 2, 3];
```

**Expected behavior:** Build should fail because array indexes are not strings but numbers

**Actual behavior:** Everything builds and 'foo' effectively contains an Array, which mismatches string indexes based interface

**Playground Link:** https://www.typescriptlang.org/play/?target=99#code/FAYw9gdgzgLgBAQwFxwN4G0DWBTAni2AJwEsIBzAXRQQlwF84BeOdARgBo4AmTgZgoDcoSLDgAjFGDEArbCHjM2nHnH5Dw0eCBQAlOWEIATADxFSZTjVwA+Jiw7c+g4MOhgANtgB07sGQAUMLgADthgAGaIAJQCQA

**Related Issues:** I didn't find any

**Comment by MartinJohns** [comment]
This is valid JavaScript. An array is just an object as well, and the individual elements can be accessed via keys. `[1, 2, 3]["0"]` returns `1`.

**Comment by mtrimolet** [comment]
Ok, so I dug a little deeper and, following your expectations,  this snippet should work :
```typescript
const bar: { [key: string]: number } = [1, 2, 3];
```
Yet the build fails as I expected.

**Comment by RyanCavanaugh** [comment]
`{ [key: string]: any }` is special; any non-null/undefined type is assignable to it because it is trivially true that looking up any property on any object will produce a value compatible with `any`

**Comment by mtrimolet** [comment]
Oh, yeah, I get it. I thought it should constrain the type to string indexed types only, preventing arrays to be assigned to it. But it is an interface, i.e. a usage contract : technically you'll be able to access string indexed properties of an array, you'll just get an undefined.
Thanks, this closes the (nonexistent) issue, and clarifies my mind a lot.
