### ISSUE TITLE
Object is possibly undefined after filtering out undefined objects

### ISSUE THREAD

**Issue by Burgov** [microsoft/TypeScript#33781]
## Search Terms
object is possibly 'undefined' filter

## Suggestion
I have a list of possibly undefineds, but am using .filter to get rid of all undefined values. Would be pretty awesome if TypeScript was able to detect that, and not report that object could be undefined

## Use Cases

I now have to explicitly cast my list as having no undefined values, which seems unnecessary

## Examples
http://www.typescriptlang.org/play/?ts=3.7-Beta#code/DYUwLgBAhgTjEF4IG0DkVUBoKoEZYgFcA7AExADMBLYkUgXQG4AoZ2GZiLiAOgFsoABwAUAD0QA+CKID8PUMQDmYABYBKTtx7VgYEDDGTpEAIQIkJctVqkN3XgJHiEU8QGoIARjVA

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
This works as intended. The function you provide to the `filter` method just returns `boolean`, it does not tell the compiler anything about the types, it can't be used to narrow the types.

Instead you should make use of a type-guard, e.g.:

    .filter((x): x is number => x !== undefined)

**Comment by jack-williams** [comment]
Duplicate of #16069.

**Comment by Burgov** [comment]
makes sense @martinJohns, thanks
