### ISSUE TITLE
Contextually allow spread to create tuples from tuples

### ISSUE THREAD

**Issue by markusjohnsson** [microsoft/TypeScript#33783]
## Search Terms

tuple spread 

## Suggestion

Right now, I cannot create a 3-tuple from a 2-tuple using spread, like so:
```ts
type A = [number, number];
type B = [number, number, string];

const a: A = [1, 2];
const b: B = [...a, "asd"];

// Type '(string | number)[]' is missing the following properties from type '[number, number, string]': 0, 1, 2
```

But to me it seams that, given the expected type, TypeScript would be able to see that spreading a `[number,number]` and adding a `string` would create a `[number, number, string]`. 

## Use Cases

Right now to produce a correct type B, given a value of type A, I would need to destructure and recreate the type:
```ts
const [x, y] = a;
const b: B = [x, y, "asd"];
```
Which works for simple tuples like this, but does not scale well. 

## Examples

I was working on a piece of code that looked like this:
```ts
type Result = [A, B];
function majorOperation(args) : Result  {
   const a = stuff();
   return minorOperation(a);
}
```

I then needed to expand the result of majorOperation to include another result, not produced by `minorOperation()`, so I split the result type in two and expected typescript to allow me to combine them using spread:

```ts
type MinorResult = [A, B];
type MajorResult = [A, B, C];
function majorOperation() : MajorResult  {
   const a = stuff();
   const c = produceC();
   return [... minorOperation(a), c];
}
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ahejlsberg** [comment]
@RyanCavanaugh No, not an oversight. Currently, anything past the first spread expression is unioned into a rest element in the resulting tuple type; and if the spread is in the first position, the result is an array type (because `[...X]` is the same as `X[]`). See also #26350.

**Comment by markusjohnsson** [comment]
Works as of TS 4.0
