### ISSUE TITLE
TSServer: Unrecognized JSON command: typeDefinition

### ISSUE THREAD

**Issue by icholy** [Microsoft/TypeScript#3379]
I'm trying to send a `typeDefinition` request as defined [here](https://github.com/Microsoft/TypeScript/blob/113b7ed13d26e246d25d76c9f65f9a15c4997322/src/server/protocol.d.ts#L172)

``` json
{
  "seq": 5,
  "type": "request",
  "command": "typeDefinition",
  "arguments": {
    "line": 2,
    "file": "/home/icholy/code/test/foo.ts",
    "offset": 1
  }
}
```

It returns an error saying the command is not recognized.
I'm able to make `definition` requests without any issues.

``` json
{
  "seq": 0,
  "type": "response",
  "command": "unknown",
  "success": false,
  "request_seq": 5,
  "message": "Unrecognized JSON command: typeDefinition"
}
```

It sends the correct response after the error response.

``` json
{
  "seq": 0,
  "type": "response",
  "command": "typeDefinition",
  "success": false,
  "request_seq": 5,
  "message": "No content available."
}
```

**Comment by DanielRosenwasser** [comment]
Hi @icholy, what version of TypeScript are you using?

**Comment by icholy** [comment]
@DanielRosenwasser `1.5.0-beta`

**Comment by DanielRosenwasser** [comment]
It certainly appears that [it's in 1.5](https://github.com/Microsoft/TypeScript/blob/release-1.5/src/server/session.ts), but I'm not certain if it made it to 1.5 beta - @mhegazy do you know?

Could you also share the file that you're testing this out on and confirm that the definition request is working at that location as well?

**Comment by mhegazy** [comment]
As @DanielRosenwasser pointed out, this change was not in 1.5-beta; you can use the latest from release-1.5 branch, and that should have what you are looking for. this should be part of the next public release.

**Comment by icholy** [comment]
Ah, makes sense.
