### ISSUE TITLE
`SourceFile.getText` skips leading comments

### ISSUE THREAD

**Issue by Swatinem** [microsoft/TypeScript#33790]
While the distinction between `getText` and `getFullText` does make sense for normal AST nodes, to get *just* the node, or the node with any leading comments or whitespace, this distinction does *not* make sense for a `SourceFile`. I can’t think of any use case where you would *not* want to get *the complete text content* of your source file.

The way that `SourceFile.getText` skips leading comments and whitespace has caused multiple problems in https://github.com/Swatinem/rollup-plugin-dts already because it is super unintuitive.

**TypeScript Version:**  3.6.3

**Search Terms:**

sourcefile gettext

**Code**

```ts
const code = `
/**
 * some leading comment
 */
export function foo() {}
`;
const sf = ts.createSourceFile("foo.ts", code, ts.ScriptTarget.Latest, true);
assert(sf.getText() === sf.getFullText());
```

**Expected behavior:**

Both `SourceFile.getText` and `SourceFile.getFullText` should return *the complete source* of the file.

**Actual behavior:**

One of the two skips leading comments and whitespace, which is super unintuitive when you are dealing with `SourceFile`s.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
It doesn't seem worth it to possibly break existing users of this function for the sake of making the behavior *less* consistent because we can't immediately imagine a scenario for it.

**Comment by Swatinem** [comment]
Fair enough.
