### ISSUE TITLE
Comparisons on union types should error

### ISSUE THREAD

**Issue by Validark** [microsoft/TypeScript#33802]
**TypeScript Version:**  3.7.0-dev.20191003

**Search Terms:** compare comparison union types

**Code**

```ts
function f(a: string | number, b: number, c: string) {
    if (a < b) { // why is this fine?

    }

    if (b < c) { // but this is not?

    }
}
```

**Expected behavior:** both if-statements should have a compile-time error

**Actual behavior:** only the first if-statement has a compile-time error

**Playground Link:** https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMAFAQwFyIM5QE4xgDmiAPomCALYBGApngDSI1aW0PMRa4HECUiAN4BYAFCJJiGMETpEAHhaChiAPRrEAdwAWAT2nZEUHTCPBCdAPzjxUxAF9bEqTLk1FiCCvWaaIKGNTIzMKOCgbMTspJzEHIA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #33682
