### ISSUE TITLE
CFA with optional chaining

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#33806]
@rbuckton 

**TypeScript Version:**  master

**Search Terms:**

**Code**

```ts
declare const o: { x: 0 } | undefined;
if (o?.x === 0) {
  o.x;
}
declare const a: [0] | undefined;
if (a?.[0] === 0) {
  a[0];
}
```

**Expected behavior:**
pass
**Actual behavior:**
```
$ node built/local/tsc --noEmit --strict index.ts
index.ts:3:3 - error TS2532: Object is possibly 'undefined'.

3   o.x;
    ~

index.ts:7:3 - error TS2532: Object is possibly 'undefined'.

7   a[0];
    ~


Found 2 errors.
```
**Playground Link:** 

**Related Issues:**

**Comment by arciisine** [comment]
This looks to be tied to https://github.com/microsoft/TypeScript/issues/33736.

**Comment by falsandtru** [comment]
The same idea is commented there but that issue doesn't aim it.
