### ISSUE TITLE
Add iterator in NodeList interface

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#3381]
Would you please add iterator in NodeList interface as [DOM4 spec](https://dom.spec.whatwg.org/#old-style-collections) says?

```webidl
IDL[Exposed=Window]
interface NodeList# {
  getter Node? item(unsigned long index#);
  readonly attribute unsigned long length;
  iterable<Node>;
};
```

```javascript
NodeList.prototype[Symbol.iterator]
// gives `function [Symbol.iterator]()` in Firefox console
```

**Comment by mhegazy** [comment]
looks like duplicate of #2695

**Comment by SaschaNaz** [comment]
Oh, it really is. Sorry.

**Comment by mhegazy** [comment]
We would take a PR if you are interested.

**Comment by SaschaNaz** [comment]
Okay, I'll do some study to add tests before sending a PR.

**Comment by mhegazy** [comment]
as @Arnavion mentions in https://github.com/Microsoft/TypeScript/issues/2695#issuecomment-91377988, we need to have this as an extension in a separate file, so that it is included in lib.es6.d.ts but not in lib.d.ts. feel free to ping me if you have any questions.

**Comment by SaschaNaz** [comment]
lib.dom.es6.d.ts. I see :)
