### ISSUE TITLE
Type inference not working properly in certain case

### ISSUE THREAD

**Issue by mcjazzyfunky** [microsoft/TypeScript#33826]
**TypeScript Version:** 
3.6.3 (same for 3.7-beta)

**Code**
Please click on the playground link below and you will find three demos of things that should behave basically the same. While type inference is working fine in 'Demo 2' and 'Demo 3' it is not working properly in 'Demo 1'. The demo provides a simple fantasy API for implementing UI components - please ignore whether this demo API makes any sense or not - the semantic is completely unimportant here - it's only about the type system/inference here.

**Expected behavior:**
Type inference in 'Demo 1' should work the same as in 'Demo 2' and 'Demo 3' regarding functions `getState` and `setState` (see code).

**Actual behavior:**
In 'Demo 1' type inference fails for `getState` and `setState` (see code)

**Playground Link:** 
Please find the demo here: [DEMO](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=77&pc=1#code/C4TwDgpgBACgTgezAZygXigJQgYwXAEwB5lg4BLAOwHMAaKAQ0pAD4BYAKFEigGVgGwaBmx5CJMlTqNm7LuGgA1cnGABXBgBsAopogBbCJWDoopCjSgB6K1ABWa0lGAIoAawgQwzgBZTUyOT6YHqc3NAAwgjBCJRGwEQwUBAAHkKUBKjwSMgspgAUYIgoAFywAJToecqqGjp6hsacYQpQUTFxxlGUAGbk1InJaUaZsMXI9LxD6aP8ghB5GADenFBQVOTAc0IA-GVTAD5Q+YXjZTCVaHm85fQ2zq1UPRBwRjjQAO7kmppQlAgmD74NxQIpIF6aEDrHpQEAINSrNZI5Eo1Fo9HWWyOaDAHzQABEGy2AiE61QPTUlBwwHIsXxUCQNNiUE08zgzQ4a30DCo+URa2oEGA2VKx0ueRgtH5UEFxPmZXy4r4Us5SOQQu2EAVajABDZ5wYqnIWiIvDyRxOODUcFexk1+yVMENNJNZvKSoAbghyAREeUFUqauotLoDPFOABfDkUqlMyhQAgQPpxdpgWLxQapGZZcamJYRybTEaoTV5iMsPmqvC9fplVPprqxPoDSV8OT+trRNOdBIwPIrVWvdRweOKqpQADkABU8VBqzgh9AgiEw8ZBLT4+RUP8TMv8AJjFA8a8J5GOfcALRXqAz17QRP6BCoQ3QHoIH4IL6WK8-39--8AYBQFARy4RQAAIgYCAiqgyyIpQDCGGU5hSGeHCcPcaBYRB2gALIAPJQAAjMcO5QECcBuFIoLFBCIBlOEqAIDCsqlkwBBmBqJLQC+5GIDQlxYUJaDnrYMB6Aw6pzniOAgriOIIO+NIoFAABGUI+AgHovNRAAGrHcbpMgcbp6pykIRnsRhth4MEvFfLivjQGIrzIN2BDUS4SnkCpgiTpBj5QAATBOxn+VBUAAMyhRy1ZOAFCB1l2DYJAlMGLAmSZUBA9Y9vkA5rESmqnDklQFUiQ7WvGSzOFmZS6QAcohWqTgAJEsYIoAAdAhhgRkZUaqgWiKItyvKyjB9AGfM9BmZqZWYlARAXg8kBMSxXHzGFc3cYwrx8bE1AAITSjt8z5b4W4APrIJpaiaAQV04Aw2JXUwV0vIgcBlPiqlqCYBAIBAyCUBOwD0hGlT3MtK23fCD2+IgHzJDa+AnehqprJVI5iuOE4AIKaMgrjHhA9DyXOsQLkKS7BA08TrsyW5-AC6wxKoTDAKeQ2RuUonoNh4F4YRQXHBRVECQLwnSzLsty-LCuK-zU6PL0LxvNAACSUwAOr4ZgADSmsNQA4ke6slNZsASVJOAyXJCjrVA+mbRZxmma7EBGfk6rQI+2JaS8ziKZoyl8xjcUmAlQVJR0GZpeMGWJsmOXJXl5VFdxZTlWsQhpGUE7E4YtVpNzazDaqo08pQ+QTeMU2e7NntldK2OjkqBNEyT6vk7O86LmzK6NCSG5kizu7sweXOIoNkP80JOEEVFYvAlIgmKxvm9bwryuq88trvFA2tQHrhvG2bpOWxw9ziRAknOfbq3AwyPQu+ZXvu2dbs+54UD++qgc4DB28mAcOnAYzUlHkSBKkViqdWQGUBOpUoDlTbigkuwB6pNSQm1Dq4werNX6lAWesVYjxSgpFWO3Z45QXSqYZO2VcrxHyoiTO8p1iUE2DAzUKo1hV3GkKSaMpG6cXfi3TGUA0FjiuJOQmxNzavF7s5KmA9lz0zXHGMeZE9wc2MGXYhvNOBAA)

**Related Issues:** 
This may marginally be related to feature request #16597, as I would have written the demos slightly differently if that feature requested in  #16597 would already have been implemented. BTW, IMHO this 16597 feature is the most important missing feature in TS ... just saying ;-)

**Comment by RyanCavanaugh** [comment]
The example here would require unification to work; see #30134

**Comment by mcjazzyfunky** [comment]
Many thanks, Ryan.
As this is already handled in that "Full unification for generic interface" issue, I think it's best to close this issue here.
