### ISSUE TITLE
Indexed access writes - soundness check inconsistency

### ISSUE THREAD

**Issue by krnik** [microsoft/TypeScript#33834]
**Search Terms:**
- Different types between assignment and indexed property access
- Typescript unsound writes type check
- Typescript access and assignment types differ 

**Code**

```ts
interface NodeConfig {
  appName: string;
  port: number;
}

// Write function presented in TS 3.5 update notes.
function write<A, K extends keyof A>(arg: A, key: K, value: A[K]): void {
    arg[key] = value;
}

class NodeAppBuilder {
  private configuration: NodeConfig = {
    appName: 'NodeApp',
    port: 3000
  };

  config(config: Partial<NodeConfig>) {
    type NodeConfigKey = keyof NodeConfig;

    for (const key of Object.keys(config) as NodeConfigKey[]) {
      const updateValue = config[key];

      if (updateValue === undefined) {
        continue;
      }

      /**
       * In v3.5.1 left side of expression has type: string & number
       * In v3.6.3+ left side of expression has type: never
       */
      this.configuration[key] = updateValue; // Type 'string | number' is not assignable to type 'never'.
      write(this.configuration, key, updateValue); // OK
    }

    return this;
  }
}
```

**Expected behavior:**

Expression **A** `write(this.configuration, key, updateValue)` should be treated the same as expression **B** `this.configuration[key] = updateValue`. 

Since at compile time (thanks to the `write` function) we know that changing the `key` in `this.configuration` object to the `updateValue` is safe and sound we should be able to infer, that assignment (expression **B**) also is safe and sound.

Or, expression **A** should fail with the same error as expression **B** (although, I am yet to get to know why should it).

**Actual behavior:**

Expression **A** is OK but expression **B** fails with Incompatible Types error.

Also, Indexed property access has different type than indexed property assignment.
```ts
const t = this.configuration[key]; // string | number - OK
const t2 = this.configuration[key] /*  string & number or never - Why? */ = updateValue /* string | number */;
```

**Playground Link:** [TSPlayground](https://www.typescriptlang.org/play/?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&target=99&ts=Nightly&ssl=30&ssc=1&pln=31&pc=1#code/JYOwLgpgTgZghgYwgAgHIHsAmEDC6QzADmyA3gLABQyycADnanALYQBcyAzmFKEQNxUaddFDAcQAV2YAjaIMoBfKlQD0q5AHVekZDEkgEYYPmR0oEThHARMyUMgAqAZWQBmAHQBWZJLqY4XRB0SE4PKn1DY1MAdx0IAB4AQQAaZABpZAgAD0gQTE5kAGsIAE90GGQkgD4ACjgoIg5U4rKOdLSANzgAG0l2KoBtdIBdAEoOTvRgOwpqGlpGwZLSkeQAXmRuvogFZUoqBB64TkKMbCSGACFJYB7sKDIhM15u3QR8QiJJKECTEA451wn2IGye8xo9EYLAGAHIgZc6LCUs9hKJxO4AAzY56KBTPD4EYi1QlfDgABQaxl6CSBeCJRGqY3BC2QYFKdBQdJBRHSZTBKwqaCwwIZ+IhelEyBJ+G4rVKyCFAHkZAArCBGDwrTgyhnMk7C7D0r580qDcYs1nIQlyvwBSAANV6-TBpOIyzKI3FVvslVqdsCECdOw2602BmwhBAtmZcx9NEJxiku1RC32qZoqgAVFmMzQs8gAJIgLaeLweACMyB6EBgYC4MxQQpy5ksnH+yAAFgb2ZyONxeCASAAyZBSWTQPPIAvF0seABsHjcAGpq7X6+3sIrKi2LKcO93Cr2BtHOpOJQss6o82BO8Awm7vr9oiAPaswQHHc7dsh1E4OSgsIDnwyAAD5jtIchQLC9iFME9YnO2RAgHAMg1my6BsgByCwqe0CwuEF7IHEwCQLUt73h4j4-H8+BpCsaSfkG35jPwv4aEq6SpumEoWGAPwlhRnAKDQ+yKEAA)

**Related Issues:** No, unfortunately after spending quite some time on investigation none of the other issues touched this topic.

**Comment by jack-williams** [comment]
I believe this is working as intended, as discussed here: #30769.

To review the interactions:
- The body of `write` does not trigger an error because generic indexed access types are not subject to the sounder assignment rules.
- The application of `write` does not trigger an error because indexed access type are inferred and instantiated in _read_ mode. The is consistent with the above interaction.
- The assignment `this.configuration[key] = updateValue;` triggers an error because a _concrete_ indexed access type appears as the target of an assignment, and is therefore simplified in _write_ mode --- this means the assignment uses the intersection of the property types rather than the union.

**Comment by krnik** [comment]
Thanks for the PR link and really good explanation!

Indeed, this behavior looks fine in the light of the PR motivation.
