### ISSUE TITLE
auto-import with alphabetized order by default

### ISSUE THREAD

**Issue by lolimay** [microsoft/TypeScript#33839]
## Search Terms

auto-import; import; auto import 
## Suggestion

Support auto-import with alphabetized order by default

## Use Cases

![image](https://user-images.githubusercontent.com/32427260/66286800-8e1ec400-e905-11e9-9adc-3bb690f7a2f0.png)
Currently, Typescript auto-import by adding the new module at the end. But it does not obey tslint rule: **ordered-imports** It will be better if typescript can auto-import with alphabetized order by default :)

## Examples

```js
import { B } from 'moduleB';
...
const a = new A(); // Ctrl+. -> Do you want to import A?
```
then
```js
import { A, B } from 'moduleB'; // A is auto-imported in front of B
...
const a = new a();
...
classs ModuleA implements IModuleA { // Ctrl+. -> Do you want to import IModuleA?
...
```
then
```js
import { IModuleA } from 'moduleA'; // moduleA is auto-imported above moduleB
import { A, B } from 'moduleB';
...
const a = new a();
...
class ModuleA implements IModuleA {
...
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by mjbvz** [comment]
This issue should cover inserting imports in the right order for :

- Auto imports
- Add missing import quick fix
- The add all missing imports quick fix

Marking as a VS Code polish item
