### ISSUE TITLE
[Type inference] Inferred type does not consider modification inside of a local anonymous function

### ISSUE THREAD

**Issue by lexidor** [microsoft/TypeScript#33837]
**Search Terms:**
Type inference, lambda, no overlap

**Code**

```ts
let p = false;
[1].forEach(function (_) {
    p = true;
});

if (p === true) {
    console.log('Typescript says that this line will never execute, which is not true.');
}
```

**Expected behavior:**

No error, since the lambda may modify `p`. The inferred type should be `false|true` a.k.a. `boolean` instead of `false` in the `if` test.

**Actual behavior:**

```
file.ts:6:5 - error TS2367: This condition will always return 'false' since the types 'false' and 'true' have no overlap.

6 if (p === true) {
      ~~~~~~~~~~
Found 1 error.
```

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=9&ssc=1&pln=1&pc=1#code/DYUwLgBADhC8EDMCGwDOIDcAoA2gRgF0A6BAewCcBRJAYwAsAKBAVwDsawBLU1iBgfQCUEAN5YIE6HAhhyzTFgC+g7Fk4I+MWNplyQwsZIg0eqUqCLBSAcwYByACoBPKCFQ1ynKJFRInqGTokSDA6TgDgTlYQCAB3TmBgCGiANxByCBAADxAaZjAQABo4sPoIcOTSEL0iOxUlLCA

**Related Issues:**
If there are any, I haven't looked hard enough.

**Comment by jwbay** [comment]
See #9998

**Comment by lexidor** [comment]
Did not scroll far enough to find one that old. Closing, since this is a duplicate.
