### ISSUE TITLE
Proposal: Make constructor body optional

### ISSUE THREAD

**Issue by OlaviSau** [microsoft/TypeScript#33846]
## Search Terms
constructors, less code, no body constructor

## Suggestion
Since TypeScript constructor is very useful without a body - it should not be mandatory.

## Use Cases
This is purely a nice to have - it would make constructors look a bit cleaner and emphasize dependency injection. It seems that empty constructor bodies are very common.
## Examples
```
constructor(private example: ExampleDependency, ...)
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)

**Comment by AlCalzone** [comment]
> [x] This feature would agree with the rest of TypeScript's Design Goals.

Nope it wouldn't! Explicitly non-goal no. 6:

> Provide additional **runtime functionality** [...]

**Comment by OlaviSau** [comment]
The constructor would still be applied as normal in runtime.

**Comment by RyanCavanaugh** [comment]
This would be confusingly ambiguous with overload signatures which also lack bodies.
