### ISSUE TITLE
proposal-string-replaceall

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#33842]
## Search Terms
tc39

## Suggestion
https://tc39.es/proposal-string-replaceall/

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Stage 3 https://github.com/tc39/proposal-string-replaceall
