### ISSUE TITLE
re-infer (refresh) mapped parameters

### ISSUE THREAD

**Issue by pirix-gh** [microsoft/TypeScript#33848]
**TypeScript Version:**  3.7.0-dev

**Search Terms:**

TypeScript's intellisense seems to go out of sync when using mapped types on parameters.

**Code**

```ts
import {F} from 'ts-toolbelt'

declare function pipe<Fns extends F.Function[]>(...args: F.Piper<Fns>): F.Pipe<Fns>

pipe(
    () => ({a: 1, b: '2'}),
    (prev) => prev // no intellisense - `any`
)

pipe(
    () => ({a: 1, b: '2'}),
    (prev: string) => prev // has error, works
)
```

This has the disadvantage of having to re-specify the type that is already known (`prev`), but could be infered by the mapped type. In my case, this is blocking me from providing generic `pipe` & `compose` for ramda.

**Expected behavior:**

Intellisense should pick the mapped type up

**Comment by RyanCavanaugh** [comment]
Please provide an isolated repro; we can't work with samples that import types from other libraries.
