### ISSUE TITLE
Typescript 3.6.4 not on npm

### ISSUE THREAD

**Issue by IgorMinar** [microsoft/TypeScript#33854]
Could you please get 3.6.4 published on npm with the following fix that has already been merged to the 3.6 branch: https://github.com/microsoft/TypeScript/commit/46ccaa29d64dc7614de5e42a0ac20c6990f32210 thank you!

**TypeScript Version:**  3.6.3

**Search Terms:**
release, npm

**Related Issues:** 
blocks https://github.com/angular/angular/pull/32946

**Comment by mprobst** [comment]
Major bonus points if we can manage to include https://github.com/microsoft/TypeScript/pull/33847 :-)

**Comment by DanielRosenwasser** [comment]
Sorry about the delay! 3.6.4 is published, and we'll have a 3.6.5 out as soon as #33847 is merged.

**Comment by mprobst** [comment]
Thanks Daniel!

**Comment by DanielRosenwasser** [comment]
Ugh, there was a problem with the publish. I'm on it.

**Comment by DanielRosenwasser** [comment]
Done!

**Comment by IgorMinar** [comment]
thank you @DanielRosenwasser !
