### ISSUE TITLE
instantiating an object as union incorrectly behaves like an aggregate

### ISSUE THREAD

**Issue by dgreene1** [microsoft/TypeScript#33853]
I was unable to find a duplicate issue, but I suspect that this has been discussed before.

My hope is that someone can direct me to the issue where this has been discussed so i can get more information on why this behavior is occurring.

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
`"union"`, `"object literal"`, `"instantiation"`

**Code**

```ts
interface IA {
    value1: number,
}

interface IB {
    value2: number,
}

interface IC {
    value3: number,
}

type ABOrC = IA | IB | IC;

function getABOrC(): ABOrC {
    return {
        value1: 1,
        // I would expect it to not let me assign value2 or value3
        value2: 2,
        value3: 3,
    }
}
```

**Expected behavior:**
I would expect that the compiler produces an error that clarifies that the object can only have value1 or value2 but not both.

**Actual behavior:**
There is no compiler error.

**Playground Link:** 
http://www.typescriptlang.org/play/index.html?ts=Nightly&ssl=6&ssc=24&pln=5&pc=15#code/JYOwLgpgTgZghgYwgAgJIEFkG8CwAoZQ5ANzgBsBXCARgC5kQKBbAI2gBp8BfffUSWIhSoAQtnxES5KgCZ6jVh2688-aPCRoAwuIJFSlCAGZ5zNlE54eefGACeABxToRAeSg6AvGkwAfNGL+qFoA3CowFCAIYMAA9iDIAOYQYC7uWgAUAJT0aR66klApFFAJuHqShAZUdMjUlpX60hByyDINjVKGJshGHYTWXEA

**Related Issues:**

**Comment by jack-williams** [comment]
This is tracked here: #20863

**Comment by dgreene1** [comment]
Thank you @jack-williams. That covers it. I'll close this then.
