### ISSUE TITLE
Suggestion: Infer `{[key: string]: unknown` indexer for interface types

### ISSUE THREAD

**Issue by russelldavis** [microsoft/TypeScript#33861]
I'll refer to `{[key: string]: unknown` as `Dict<unknown>`.

Interface types currently don't get inferred indexers, because the inference would be incomplete [in cases of augmentation](https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024)). However, inferring `Dict<unknown>` would still be safe, and it would allow passing interface types to functions that require an indexer. (It also just seems like the right thing to do in terms of semantics and consistency.)

**Use case:** `Dict<unknown>` (or a generic `Dict<T>`) is a useful type for any function that wants to operate on a dict-like object without allowing types like primitives and functions. Calling such a function with an interface type requires either a type assertion at the call site, or adding a less restrictive overload, which eliminates some type safety.

For example, the declaration for `Object.entries` takes the latter approach, and so calls like `Object.entries(42)` and `Object.entries(console.log)` are allowed, when they should arguably be errors.

**Comment by RyanCavanaugh** [comment]
This would also allow arbitrary *writes* to objects, which would be very unsafe.

>  dict-like object without allowing types like primitives and functions

Functions are objects too! This is why index signatures are opt-in -- arbitrary values should not be treated as indexable without some hint toward that effect. You can write `: object` if you want to disallow primitives.

**Comment by russelldavis** [comment]
> This would also allow arbitrary writes to objects, which would be very unsafe.

Ah, right. To make it safe, the inferred indexer should be `readonly`. Side note: existing inferred indexers are unsafe in the same way: see this [playground example](https://www.typescriptlang.org/play/#code/C4TwDgpgBAsglgDwgEygXigbwFBSgZ2ACcAuA4uAOwHMAaXKSgVwFszmWAjCI7AX2zYAZk0oBjYHAD2lKKPwBDIRAAULRCjKYA2gGsIIMoSJVqAXSMUaAHw7cifAJRYG6pMgB0HdFABEAdwALKSkwfF9XDU8FIk44YhiQHwCIABswCIFsVIhgKDdNWCifTHJSP2NfWkZWMgAWACYoPgBubHklVQLkRzagA). It's out of scope for this issue, but should those be inferred as `readonly` as well?

> arbitrary values should not be treated as indexable without some hint toward that effect

That seems to be untrue for type aliases. And, referring again to #15300, it seems to only be untrue for interfaces because they can be augmented.

Thoughts on the revised `readonly` approach?
