### ISSUE TITLE
Suggestion: Allow static members to reference type parameters if they have default types

### ISSUE THREAD

**Issue by hdodov** [microsoft/TypeScript#33870]
## Search Terms

default type, default type parameters

## Suggestion

This is related to #32211 and especially, #24018. I would have commented on the latter, but it's limited to collaborators. @andy-ms [said](https://github.com/Microsoft/TypeScript/issues/24018#issuecomment-388071202):

> Without inheritance that wouldn't make much sense:
> ```ts
> class Super<T> {
>     static m(x: T): void;
> }
> Super.m(); // What's `T`?
> ```
> I see what you mean though, when a subclass is introduced:
> ```ts
> class Sub extends Super<number> {}
> Sub.m(); // T is number
> ```

My proposal is to allow type parameters in static members only if those parameters have default values. For example:

```ts
class Super<T> {
  // Error: Static members cannot reference class type parameters.
  // Proposition: Static members can only reference class type parameters with default type.
  static value: T
}

let val = Super.value // What's T
```

But if you specify a default value, everything makes sense:

```ts
class Super<T = number> {
  static value: T
}

let val = Super.value // number

class Sub extends Super { }
class Sub2 extends Super<string> {}

let subval = Sub.value // number
let subval2 = Sub2.value // string
```

## Use Cases

In my personal use case, I have an instance property `options` that merges input with data from a static `defaults` property:

```ts
class Component<O> {
  static defaults: O // Error: Static members cannot reference class type parameters.
  options: O

  constructor (settings: Partial<O>) {
    let ctor = this.constructor as typeof Component
    this.options = { ...ctor.defaults, ...settings }
  }
}
```

If I then extend the class, I get no type-checking for `defaults`:

```ts
interface SubOptions {
  foo: string
}

class SubComponent extends Component<SubOptions> {
  static defaults = {
    foo: 42 // not type-checked
  }
}
```

## Examples

With my proposal, you could define the base class like this:

```ts
interface DefaultOptions {
  element: HTMLElement,
  value: number
}

class Component<O = DefaultOptions> {
  static defaults: O
  options: O

  constructor (settings: Partial<O>) {
    let ctor = this.constructor as typeof Component
    this.options = { ...ctor.defaults, ...settings }
  }
}
```

The descendant like this:

```ts
interface SubOptions {
  foo: string
}

class SubComponent extends Component<SubOptions> {
  static defaults = {
    foo: 42 // Error: Type '42' is not assignable to type 'string'.
  }
}
```

And the final result would be:

```ts
let def = Component.defaults // DefaultOptions
let foodef = SubComponent.defaults // SubOptions
```

Everything is explicitly defined and typed.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This would be a massive soundness hole. Nothing about any particular instantiation of e.g. `O` is at all constrained by the default; literally any type might come out of that spread expression with no relation to the instantiated type.

**Comment by hdodov** [comment]
@RyanCavanaugh I don't think I understand.

>literally any type might come out of that spread expression

I'm combining `O` and `Partial<O>`, so the return type must be `O`? I'm fairly new to TS, but I checked this [in the playground](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgPLIN4Chm+ZAZzAC5kipQBzHPAGwhFJAFcBbAI2iwF8st6wyACYR4zWmAKl0AXkw1chEsgDkACwi1aAexUAaBcnqNkAFgBMPPgOSgADs2UAFOFDDA4tADyoAfMjlsPHwIIlIVAHdtKFohFSssAHpE-ABPOwhtGGRWaEoUYAI0fghBXKh8gMxkADo6kTEJAj1auvtHZF4gA) and it's correct:

```ts
interface O {
    test: string
    len: number
}

let defaults: O = {
    test: 'hello',
    len: 42
}

let input: Partial<O> = {
    test: 'world'
}

// typeof merge is O
let merge = { ...defaults, ...input }
```

Could you explain and perhaps give an example? I want to understand.
