### ISSUE TITLE
How to emitObjectLiteral with leading and trailing line breaks?

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3387]
Currently when I emitObjectLiteral(), the first element is on the same line as `{`:

```js
Ext.define('Tests.cases.compiler.extjsDefaultClass', { extend: "Boo",
    statics: { staticProp: "abc",
        static2: 3 } });
```

I want to make it breaks like this:

```js
Ext.define('Tests.cases.compiler.extjsDefaultClass', {
    extend: "Boo",
    statics: {
        staticProp: "abc",
        static2: 3
    }
});
```

I can see that it is possible from the test case 
https://github.com/Microsoft/TypeScript/blob/5a1c740ca864fd04f6d8fc4fac94658955eef93e/tests/baselines/reference/objectLiteralWithSemicolons2.js
but couldn't find out which code does it run to create that result.

**Comment by mhegazy** [comment]
write it on a new line in the .ts file?

```ts 
Ext.define('Tests.cases.compiler.extjsDefaultClass', { extend: "Boo",
    statics: {
        staticProp: "abc",
        static2: 3
    }
});
```

emits
```js
Ext.define('Tests.cases.compiler.extjsDefaultClass', { extend: "Boo",
    statics: {
        staticProp: "abc",
        static2: 3
    }
});
```

where as:

```ts
Ext.define('Tests.cases.compiler.extjsDefaultClass', {
	extend: "Boo",
    statics: {
        staticProp: "abc",
        static2: 3
    }
});
```

emits

```js
Ext.define('Tests.cases.compiler.extjsDefaultClass', {
    extend: "Boo",
    statics: {
        staticProp: "abc",
        static2: 3
    }
});
```

**Comment by unional** [comment]
@mhegazy , sorry I didn't clarify what I was trying to do.  I'm writing `--module extjs5` that would transpile

// in tests\cases\compiler.extjsDefaultClass.ts
```js
export default class A extends Boo {
   static staticProp: string = "abc";
   static static2: number = 3;
}
```
to
```js
Ext.define('Tests.cases.compiler.extjsDefaultClass', {
    extend: "Boo",
    statics: {
        staticProp: "abc",
        static2: 3
    }
});
```

**Comment by unional** [comment]
I'm trying to use an `ObjectLiteralExpression` or `FunctionExpression` to transform and collect all information needed and sent it to `emitObjectLiteral(..)` or similar functions to emit the result.  What do you think about this approach instead of manually emitting `write("Ext.define('" + fullClassPath + "', ...")`?

**Comment by mhegazy** [comment]
call `writeLine()` in the emitter

**Comment by mhegazy** [comment]
call `writeLine()` in the emitter

**Comment by unional** [comment]
I'm hesitate to add `writeLine()` to (or change in general)  `emitObjectLiteral(...)` because it is used by the core code.  I can either add additional param to tell `emitObjectLiteral(...)` to do the `writeLine()` or I can call another method (or write my own, violating DRY).

**Comment by DanielRosenwasser** [comment]
You're editing the core code, it hardly matters at this point. :smiley: 

I should mention as a word of caution, if you're doing this for your own personal uses, that's great, but I don't think extjs support is something we're willing to take on in the mainline TypeScript repo if that's your intention. Otherwise, feel free to continue hacking on the compiler!

**Comment by unional** [comment]
Sad.. :)  Even though it won't be in the mainline TypeScript, I still want to have the code separate as much as possible, while reusing the core code as much as possible so that I can pull in the latest changes with ease. :)
