### ISSUE TITLE
Regression in variance measurements for aliased recursive types: not falling back to structural checks when measuring

### ISSUE THREAD

**Issue by jack-williams** [microsoft/TypeScript#33872]
### Version. 3.7-beta

**Code**

```ts
export interface CalcObj<O> {
    read: (origin: O) => CalcValue<O>;
}

export type CalcValue<O> = CalcObj<O>;

function foo<O>() {
    const unk: CalcObj<unknown> = { read: (origin: unknown) => unk }
    const x: CalcObj<O> = unk;
}
```

**Expected behavior:**

No error on the assignment to `x`.

**Actual behavior:**

Error. `unknown` is not assignable to `O`. The parameter `O` is being measured as invariant.

This works correctly on 3.6.3 and below. The usual tricks to avoid variance-based comparisons let the assignment pass.

Also, removing the type alias works too:
```ts
export interface CalcObj<O> {
    read: (origin: O) => CalcObj<O>;
}

function foo<O>() {
    const unk: CalcObj<unknown> = { read: (origin: unknown) => unk }
    const x: CalcObj<O> = unk; // fine!
}
```

Probably caused by #33050.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=10&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYUwBtsB5AIwCsAeUgPjgG8AoONuKYTAEwApoEAc2QAuOKQCUYwiQBqxAK7BadANzMAvs2ahIsODACeYPDOzyiSlXAC8BYmSor1zdAqTYYCCEjjoIECq8Ekys7Ng+AM7w7gDW0g4UNHFIEADuSAx2jBxc3GL8UEKicCnpSCE2DHFwWuxwEUjRcCAJJEnWdnHqGkA)

**Comment by jack-williams** [comment]
The issue is that the flags for identifying types instantiated with markers are not being propogated fully. The comparison ends up doing a default covariant check on type arguments when it should be falling back to a structural check (because we're in the middle of a variance measurement). In this case:
```ts
function getAliasVariances(symbol: Symbol) {
    const links = getSymbolLinks(symbol);
    return getVariancesWorker(links.typeParameters, links, (_links, param, marker) => {
        const type = getTypeAliasInstantiation(symbol, instantiateTypes(links.typeParameters!, makeUnaryTypeMapper(param, marker)));
        type.aliasTypeArgumentsContainsMarker = true;
        return type;
    });
}
```

Getting the alias variance for `CalcValue` returns an object type (`CalcObj`) without the marker object flags set. This means the following check passes when it shouldn't:
```ts
 if (getObjectFlags(source) & ObjectFlags.Reference && getObjectFlags(target) & ObjectFlags.Reference && (<TypeReference>source).target === (<TypeReference>target).target &&
    !(getObjectFlags(source) & ObjectFlags.MarkerType || getObjectFlags(target) & ObjectFlags.MarkerType)) {
    // We have type references to the same generic type, and the type references are not marker
    // type references (which are intended by be compared structurally). Obtain the variance
    // information for the type parameters and relate the type arguments accordingly.
    const variances = getVariances((<TypeReference>source).target);
    const varianceResult = relateVariances(getTypeArguments(<TypeReference>source), getTypeArguments(<TypeReference>target), variances, isIntersectionConstituent);
    if (varianceResult !== undefined) {
        return varianceResult;
    }
}
```

Looking for `type.aliasTypeArgumentsContainsMarker` isn't sufficient because we can have union types that are later decomposed, with their constituents being lazily instantiated.

**Comment by jack-williams** [comment]
Smaller repro:
```ts
type A<T> = B<T>;

interface B<T> {
    prop: A<T>;
}

declare let a: A<number>;
declare let b: A<3>;
 
b = a; // error
```

**Comment by Jessidhia** [comment]
That looks like a correct error, though (`(T=3) = (T=number)`); `a = b;` (`(T=number) = (T=3)`) is the direction that I'd expect to be a bug if it errors.

**Comment by jack-williams** [comment]
The error is not correct because the type parameter is never materialised in the type, so the type-parameters of two instantiations of `A` are independent. The type `A<T>` is structurally equivalent to `C` for all `T`.
```ts
interface C {
    prop: C;
}

declare let a: A<number>;
declare let b: A<3>;
const c1: C = a;
const c2: C = b;
a = c1;
b = c2;
```
