### ISSUE TITLE
`Object.entries(any)` returns `never` inside `new Map`

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#33891]
**TypeScript Version:**  3.6.3

**Search Terms:** map entries never

**Code**

```ts
var x: any = {};
var y = Object.entries(x); // `[string, any][]` as expected
var z = new Map(Object.entries(x));
// Here it suddenly returns `[string, never][]`
// and thus causes `Map<string, never>`
```

**Expected behavior:** It should return `[string, any][]`

**Actual behavior:** The return type suddenly changes

**Playground Link:** It somehow can't get `Object.entries`, but anyway https://www.typescriptlang.org/play/?ssl=3&ssc=36&pln=1&pc=1#code/G4QwTgBAHgXBIDsCeEC8EDeBfA3AWAChRIV0B5AIwCsBTAYwBcA6GhBsASxoGcAKKAJT4i4CAC80EBDQDuEALIgADr0q1GLNpx78BQoA

**Related Issues:**

**Comment by MartinJohns** [comment]
@RyanCavanaugh This issue does not reproduce anymore can probably be closed. The resulting type is now `Map<string, unknown>`.

**Comment by jakebailey** [comment]
Yes, I can't reproduce this either.
