### ISSUE TITLE
tsserverlibrary.d.ts contains implicitAny error

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#33894]
**TypeScript Version:**  v3.7.0-dev.20191009

**Search Terms:**

**Code**

```sh
tsc --noEmit --strict node_modules/typescript/lib/tsserverlibrary.d.ts
```

**Expected behavior:**

No error

**Actual behavior:**

````
node_modules/typescript/lib/tsserverlibrary.d.ts:8559:21 - error TS7033: Property 'typingsCache' implicitly has type 'any', because its get accessor lacks a return type annotation.

8559         private get typingsCache();
                         ~~~~~~~~~~~~


Found 1 error.
````

**Comment by ajafff** [comment]
On second thought this is probably not a problem with `tsserverlibrary.d.ts`. It seems the check for implicitAny getters should exclude private ones.

**Comment by nmain** [comment]
Related to https://github.com/microsoft/TypeScript/issues/33877

**Comment by RyanCavanaugh** [comment]
Nice catch @ajafff
