### ISSUE TITLE
Static assignment fails in class expression with specified static side type

### ISSUE THREAD

**Issue by hdodov** [microsoft/TypeScript#33897]
**Search Terms:**

class static side nested object invalid type

**Code**

```ts
interface Ctor {
    opts: {
        len: 'foo' | 'bar'
    }
}

let myVar: Ctor = class MyClass {
    static opts = {
        len: 'foo'
    }
}

myVar.opts = {
    len: 'foo'
}
```

**Expected behavior:**

The `static opts` assignment should use the `Options` interface as type and the assigned object `{ len: 'foo' }` should be valid.

**Actual behavior:**

The static assignment fails with the error:

>Type 'typeof MyClass' is not assignable to type 'Ctor<Options>'.
>  The types of 'opts.len' are incompatible between these types.
>    Type 'string' is not assignable to type '"foo" | "bar"'.

If I assign the object outside of the class body, it works as expected.

This doesn't make sense since the two assignments accomplish the same thing, essentially. The static assignment is syntactic sugar for the other assignment. As you can see in the compiled code, they're the same thing:

```js
"use strict";
var _a;
let myVar = (_a = class MyClass {
    },
    _a.opts = {
        len: 'foo'
    },
    _a);
myVar.opts = {
    len: 'foo'
};
```

**Playground Link:** [Here](https://www.typescriptlang.org/play/index.html?ts=3.7-Beta&ssl=1&ssc=1&pln=15&pc=2#code/JYOwLgpgTgZghgYwgAgMJgPZWQbwLABQyxyGADmAM4BcuhJDyANhCLQOQwYbvIA+ydgCM4UdvRIBfQtIKEWYZAFsAngDVRtdFmQBeZAiZxKlZAFkVqIybpESlMHDDAEpCqf347jZqw5ceCWJZWUJVDSgAOnIqPVsGFjZBAPECSSA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@elibarzilay the issue here is that we're failing to contextually type the static member initializer by the surrounding type. There should be some better logic in `getContextualType` that recognizes a static initializer of a class expression to be typed by the corresponding property in the target type
