### ISSUE TITLE
Wrong typing for document.open

### ISSUE THREAD

**Issue by sirian** [microsoft/TypeScript#33898]
**TypeScript Version:**  3.6.3

document.open (lib.d.ts) typing is wrong:
```typescript
open(url?: string, name?: string, features?: string, replace?: boolean): Document;
```

correct is: 
```typescript
open(url: string, name: string, features: string): Window | null;
open(type?: string, replace?: string): Document;
```
https://developer.mozilla.org/en-US/docs/Web/API/Document/open

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/25495

**Comment by RyanCavanaugh** [comment]
See #31246

**Comment by sirian** [comment]
@RyanCavanaugh it's about document.open, not window.open

**Comment by RyanCavanaugh** [comment]
http://help.dottoro.com/ljvkwlod.php

> If more than two parameters are set for the document.open method, then it works like the window.open method. This page describes that case only if at most two parameters are set for the document.open method. For other cases, please see the page for the window.open method

I have no idea how all the different browsers behave here but don't really see the point in breaking people using the 4-argument variant for the sake of getting better argument names as proposed here (or maybe I'm missing something). Is there some case where you're getting an error that you shouldn't be?

**Comment by sirian** [comment]
@RyanCavanaugh Problem with return type. When `document.open` called with 3 (or more) arguments - 
return type should be `Window | null`. But now it returns `Document`

![image](https://user-images.githubusercontent.com/897643/66587014-495b8d00-eb92-11e9-955e-19750b4be202.png)

**Comment by jakebailey** [comment]
As of #44684, `Document`'s `open` is now:

```ts
open(unused1?: string, unused2?: string): Document;
open(url: string | URL, name: string, features: string): WindowProxy | null;
```
