### ISSUE TITLE
Give better error messages when properties are accessed on global empty DOM interfaces

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#33907]
https://twitter.com/rauschma/status/1181852019264503808

We should give a more helpful message when missing `"lib": ["dom"]`.

If accessing a property on a type that was

* empty and
* declared in the global scope and
* named after a pattern that matches `/^HTML\w+Element$/`

it is likely a forward declaration for DOM environments, and we should provide an error message like:

```
Property '{0}' does not exist on type '{1}'. Did you forget to include "dom" in your "lib" setting?
```

Bonus: would be awesome if we could provide related spans in a `tsconfig.json`/`jsconfig.json` to say

```
The 'lib' option was specified here.
```

**Comment by m-henderson** [comment]
@kyliau did you plan on picking this back up?

**Comment by kyliau** [comment]
> @kyliau did you plan on picking this back up?

I think you meant @kylejlin

**Comment by kylejlin** [comment]
@m-henderson No, I do not plan on picking this back up. You're welcome to take over, if that's why you're asking.

**Comment by m-henderson** [comment]
Sorry about that @kyliau, your names are similar at first glance. Thanks for the response @kylejlin

**Comment by kyeb** [comment]
I just spent 30+ minutes stuck on this error -- would love to see something like this get added so others don't go down that rabbit hole.

In my case, the cryptic error was `Property 'value' does not exist on type 'EventTarget & HTMLInputElement'`, for a simple React `onChange={(e) => setNewValue(e.target.value)}`.

**Comment by DanielRosenwasser** [comment]
Thanks @JoshuaKGoldberg!
