### ISSUE TITLE
Codefix + specific error for import/export collision error added in 3.7

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#33913]
```ts
import { X } from 'x'
export type X = X
let x: X
```

Errors with "Import declaration conflicts with local declaration of 'A'."

**Expected behavior:**
Codefix that adds an alias for `X`, then renames all occurences in the module:

```ts
import { X as XX } from 'x'
export type X = XX
let x: X
```

**Actual behavior:**
No codefix, and renaming `X` incorrectly renames the `x.X` in addition to the imported identifier. (in Emacs at least -- I think VS Code behaves better) 

It's probably possible to codefix this automatically in all cases, but the 3.7-urgent one is one where there is *also* an `export type X = X`.

@andrewbranch I'll take this for now but let's compare notes about 3.7-beta load to figure out who does it.

**Comment by andrewbranch** [comment]
For cross-referencing purposes: change adding the error was introduced in https://github.com/microsoft/TypeScript/pull/31231

**Comment by sandersn** [comment]
So...

1. I forgot to do this.
2. All the existing code I know of, except protractor, is now fixed.
3. I don't think this codefix would be that useful for new code.

@andrewbranch I'm going to close this unless you think it's worth doing.

**Comment by andrewbranch** [comment]
👍
