### ISSUE TITLE
Type PermissionName for Permission API doesn't contain correct types

### ISSUE THREAD

**Issue by maciekgrzybek** [microsoft/TypeScript#33923]
**TypeScript Version:**  3.6.3

**Search Terms:**
permission, permissionname, API, navigator, clipboard-write, clipboard-read, clipboard

**Code**

```ts
  const checkForPermission = (type: PermissionName) => {
    navigator.permissions
      .query({
        name: type,
      })
      .then(permissionStatus => {
        // Will be 'granted', 'denied' or 'prompt':
        console.log(permissionStatus);
        // permissionStatus.state = 'granted'
        // Listen for changes to the permission state
        permissionStatus.onchange = () => {
          console.log(permissionStatus.state);
        };
      });
  };

  checkForPermission('clipboard-read');
  checkForPermission('clipboard-write');
```

**Expected behavior:**
'clipboard-read' and 'clipboard-write' should be valid types for PermissionName type.

**Actual behavior:**
'clipboard-read' and 'clipboard-write' are not valid types for PermissionName type.
Typescript is showing error:
`Argument of type '"clipboard-read"' is not assignable to parameter of type 'PermissionName'.`

**Playground Link:** 
[TS Playground link](http://www.typescriptlang.org/play/?ssl=16&ssc=40&pln=1&pc=1#code/ATDGHsDsGcBcwBYFNQGsBi4BOAFJWBbAS2miKmAF5gAKWATwAckAuYPQksqAOQEMCSAJRUAfMADeAKBAhIfAG5EA5n1jYAdM06lyMGbJAaAjgFd89GtMOH5gtg2YAaA4YC+Q17I2xkkGtrEulAAyrBqptBikl6GAPRxwADqRAA2qcAARkjAAOTKWHyQsEgAJrlOeaVIkERlucDYeYxY4ASMsLkssbIQMOCpSBqp4MoB+EHckGER0EIA3D0gCcCBXHozsJEacGo51PmFxfVLwCsAMiQlkMAAZk2gCEXKSFHqwL45a8E3uyWn3ymm22UEez32tBElHE1hshj60AGQxGY0BG3CW2gOwxwkWcJAbjxNg8RMJBkeKAw2A4kz0NFyoFSREYmXAfCwpQAtFgkHxygsgA)

**Related Issues:** 

**Other comments:**
According to MDN PermissionName should have these types:
'accelerometer', 'accessibility-events', 'ambient-light-sensor', 'background-sync', 'camera'​, 'clipboard-read', 'clipboard-write', 'geolocation', 'gyroscope', 'magnetometer', 'microphone', 'midi', 'notifications', 'payment-handler', 'persistent-storage', and 'push'
[Source](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query)

**Comment by maciekgrzybek** [comment]
I've already made changes in my local fork, but not sure what's the exact workflow here? Should I create a PR or does it need to be confirmed first?

**Comment by RyanCavanaugh** [comment]
@maciekgrzybek thanks for asking! A PR would be great

**Comment by maciekgrzybek** [comment]
@RyanCavanaugh just pushed it here :) #34562

**Comment by maciekgrzybek** [comment]
PR added here  - https://github.com/microsoft/TSJS-lib-generator/pull/792

**Comment by iKethavel** [comment]
Looks like API for Clipboard was changed since previous PR. Now we have this - https://developers.google.com/web/updates/2018/03/clipboardapi

**Comment by jaredhan418** [comment]
pls fix this bug!

**Comment by lizy0329** [comment]
How about this bug ?

**Comment by NCC1701M** [comment]
As a workaround to avoid the error, you could do this:

```typescript
const permissionName = "clipboard-write" as PermissionName;
navigator.permissions.query({ name: permissionName }).then(result => {});
```

**Comment by haVincy** [comment]
This is working in typescript 4.0.5. 
Note: Safari doesn't support permissions API. You'll need to add check before using it in Safari case.
https://caniuse.com/?search=permission

**Comment by valerii15298** [comment]
This bag again occurs. Updated to typescript 4.4.2 and i see such error:
![permtype](https://user-images.githubusercontent.com/44531564/131379533-ee483a0b-403c-4dd0-915a-f998fc5eaeed.png)

But `microphone` must be allowed type!

**Comment by sbjovanovski** [comment]
Yes, I agree with @valerii15298 , this issue occurred again. 'microphone' is no longer part of the `name` types.
These are the current types in **Typescript 4.1.5:** 
```
"gamepad" | "geolocation" | "notifications" | "persistent-storage" | "push" | "screen-wake-lock"
```
However, luckily this workaround still works:
```
const permissionName = "microphone" as PermissionName;
navigator.permissions.query({ name: permissionName }).then(result => {});
```
This should be fixed.

**Comment by echocrow** [comment]
+1, seeing the same issue with `{ name: 'gyroscope' }`. Using type assertion via `as PermissionName` circumvents this for now.

The W3C Working Draft on the Permissions API lists a couple more `PermissionName` enums:
- https://www.w3.org/TR/permissions/#dom-permissionname

Note that this is not a complete list however: e.g. `gamepad` is not listed here. Instead, the draft does state:
> The APIs and features in scope for the Permissions Policy specification go beyond those identified in this specification's PermissionName enum (e.g., "sync-xhr" and "gamepad").

Merging the W3C `PermissionName` with the MDN list linked by the OP and the list TypeScript currently implements, we could expand to the following type:
```ts
type PermissionName = "accelerometer" | "accessibility-events" | "ambient-light-sensor" | "background-fetch" | "background-sync" | "bluetooth" | "camera" | "camera'" | "clipboard-read" | "clipboard-write" | "display-capture" | "gamepad" | "geolocation" | "gyroscope" | "magnetometer" | "microphone" | "midi" | "nfc" | "notifications" | "payment-handler" | "persistent-storage" | "push" | "screen-wake-lock" | "speaker-selection" | "sync-xhr" | "xr-spatial-tracking";
```
Unless we also allow any other string, this list will need to be continuously maintained as new Permissions get developed.

**Comment by Kreozot** [comment]
Ok, there is old PR to this #34562, which was closed because of necessity to make this changes in https://github.com/Microsoft/TSJS-lib-generator.
I've done some search in there and found this: https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/inputfiles/removedTypes.jsonc
So looks like all the missing properties are not just missing - they are **removed** for some reason. Any ideas why?

![image](https://user-images.githubusercontent.com/1423028/134336212-0fcee74d-ac52-477c-90e3-180578eef7f0.png)

**Comment by juliabmenezes** [comment]
Any updates please?

**Comment by jagregory** [comment]
+1'ing, also missing `camera` from `PermissionName`

**Comment by Mange** [comment]
Seems like they were removed in #1034. No idea why…

**Comment by batbrain9392** [comment]
This is such an old issue and no idea why it's still not addressed!

**Comment by AHRealift** [comment]
^^^ status? same err ...

**Comment by baaraak** [comment]
+1 same error with `michrophone`

**Comment by RyanCavanaugh** [comment]
@sandersn looks like no one has been able to send a PR for this - please see what we need to do

**Comment by sandersn** [comment]
We require implementation in two engines for something to be added to lib.dom.d.ts.

Chromium browsers support a lot more permissions, but neither Firefox nor Safari do. The table https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#permissions_interface shows that the current union in lib.dom.d.ts is correct (actually, it has two *extra* entries that don't show up in MDN's list.)

**Comment by v1shaL-b** [comment]
Same error here. I've used the workaround, but it doesn't actually let me record anything when actually getting the permission. Maybe the workaround doesn't work anymore.

**Comment by nathanredblur** [comment]
this list needs to be updated, Mozilla list is small but chrome is longer

https://searchfox.org/mozilla-central/source/dom/webidl/Permissions.webidl#10
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/third_party/blink/renderer/modules/permissions/permission_descriptor.idl
https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/permissions/PermissionName.idl

src: https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query

**Comment by GeoMarkou** [comment]
> We require implementation in two engines for something to be added to lib.dom.d.ts.

According to this rule, looking at the [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility), it seems like the type should be:

```ts
type PermissionName = "camera" | "geolocation" | "microphone" | "notifications" | "persistent-storage" | "push";
```

![image](https://user-images.githubusercontent.com/12272970/209241944-ad438fea-8655-474f-9e91-a81bacd90827.png)

**Comment by NiiyaDaiki** [comment]
What was the end result of this case?

> We require implementation in two engines for something to be added to lib.dom.d.ts.

Following the above rules, I think some types should be added.

**Comment by pepegmz** [comment]
in my case, I had a project where I imported several plugins directly that used a different version of typescript, so when I used vscode auto-import I imported the classes directly from the src folder instead of the package name

doing a build to the plugins and then proceeding to install them and making sure they were imported from their package name solved my problem.

**Comment by josheverett** [comment]
@sandersn this should be reopened as it is now available in all browsers (with the exception of mobile webviews).
