### ISSUE TITLE
Optional Chaining and Nullish Coalescing runtime helper

### ISSUE THREAD

**Issue by KhraksMamtsov** [microsoft/TypeScript#33933]
## Search Terms

optional chaining helper
nullish coalescing helper
optional chaining runtime helper
nullish coalescing runtime helper
## Suggestion

I wrote a helper that makes the code more readable and using it produces less code.
You may see it here http://jsfiddle.net/sjmkz81b/4/
It works like maybe monad, but it is light version for ?. and ??. 
No need to generate temporary variables like _a, _b, _c, and usage this helper emit more recognisable code with less length.
It works on demand - if ```null``` or ```undefined``` occurs in the chain, then further all calculations are stopped and the ```undefined``` is passed along the chain, so index access with index incrementation works fine.
Please check feedle for tests.
Of the minuses - the stack trace is bigger (in case of error) and it is probably bit slower than current version, although I did not take measurements, but i think it takes less memory usage.)
What do you think about that?

## Examples

```js
a?.[i++]?.c?.d?.(1, 2, 3) ?? 123
// becomes
// es6
__helper(a)(x => x[i++])(x => x.c)(x => x.d, [1, 2, 3])(() => 123)
// es5
__helper(a)(function(x) { return x[i++]; })(function(x) { return x.c; })(function(x) { return x.d; }, [1, 2, 3])(function() { return 123; })
// current version on playground
var _a, _b, _c, _d; _d = (_c = (_b = (_a = a) === null || _a === void 0 ? void 0 : _a[i++]) === null || _b === void 0 ? void 0 : _b.c) === null || _c === void 0 ? void 0 : _c.d, (_d !== null && _d !== void 0 ? _d : 123);
```
```js
a ?? 123
// becomes
// es6
__helper(a)(() => 123)
// es5
__helper(a)(function() { return 123 })
// current version on playground
(a !== null && a !== void 0 ? a : 123)
```
```js
a?.b
// es6
__helper(a)(x => x.b)()
// es5
__helper(a)(function(x) { return x.b })()
// current version on playground
var _a; (_a = a) === null || _a === void 0 ? void 0 : _a.b;
```
```js
// helper itself
function __helper(x) {
  return function(fn, args, _x = x) {
    if (_x !== void 0 && _x !== null) {
      if (fn === void 0) { // __h({ y: 1 })() => { y: 1 }
        return _x;
      }
      if (fn.length) { // get property __h({ y: 1 })(x => x.y) => __helper([[maybeValue]])
        if (args === void 0) {
          return __helper(fn(_x));
        } else {
          // get property and call __h({ y: 1 })(x => x.y, [1, 2, 3]) => __helper([[maybeValue]])
          return __helper(fn(_x).apply(_x, args));
        }
      } else { // get or default __h(1)(() => 2) => 1
        return _x;
      }
    }
    if (fn === void 0) { // __h(undefined | null)() => undefined
      return void 0;
    }
    if (fn.length) { // get property [[undefined]]?.y  __h(undefined | null)(x => x.y) => __helper(undefined | null)
      return __helper(_x);
    } else { // get or default __h(undefined | null)(() => 2) => 2
      return fn();
    }
}
```
```js
// minified version
function h(i) {return function(e, n, l) {return void 0 === l && (l = i), null != l ? void 0 === e ? l : e.length ? h(void 0 === n ? e(l) : e(l).apply(l, n)) : l : void 0 === e ? void 0 : e.length ? h(l) : e()}}
```

## Checklist

My suggestion meets these guidelines:

* [+] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [+] This could be implemented without emitting different JS based on the types of the expressions
* [+] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [+] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
There are a lot of trade-offs with either approach and we chose the non-function-based emit based on a variety of factors.

**Comment by ShanonJackson** [comment]
Can you elaborate on these factors? @RyanCavanaugh we have many internal libraries in our team and are debating adopting optional chaining but the transpiled output is just eye-gouging material; its a choice between terrible bundle size or gaining access to cleaner syntax.
