### ISSUE TITLE
Assigning to a unwrapped type doesn't work on Generics but works with Interface

### ISSUE THREAD

**Issue by pikax** [microsoft/TypeScript#33942]
**TypeScript Version:**  3.7.0-dev.20191009

**Search Terms:**

**Code**

```ts
// Types
export interface Ref<T = any> {
  value: UnwrapRef<T>
}
export function ref<T>(raw: T): Ref<T>{
    return null as any;
}

type BailTypes =
  | Function
  | Map<any, any>
  | Set<any>
  | WeakMap<any, any>
  | WeakSet<any>
  
export type UnwrapRef<T> = {
  ref: T extends Ref<infer V> ? UnwrapRef<V> : T
  array: T extends Array<infer V> ? Array<UnwrapRef<V>> : T
  object: { [K in keyof T]: UnwrapRef<T[K]> }
  stop: T
}[T extends Ref
  ? 'ref'
  : T extends Array<any>
    ? 'array'
    : T extends BailTypes
      ? 'stop' // bail out on types that shouldn't be unwrapped
      : T extends object ? 'object' : 'stop']

// /types

type Supa = {
    xx: number,
    x1: number
}
function setup(d: Supa, fn: () => Supa) {
  const r = ref(d);
  // assigning the value
  r.value = fn(); // works as expected
}

function setup2<T>(d: T, fn: () => T) {
  const r = ref(d)
  r.value = fn(); // ERROR
}
```

with simpler recursion 
```ts
export interface Ref<T = any> {
  value: UnwrapRef<T>
}
export type UnwrapRef<T> = T extends Ref<infer V>
  ? UnwrapRefProp<V>
  : UnwrapRefProp<T>
export type UnwrapRefProp<T> = { [K in keyof T]: UnwrapRefPropValue<T[K]> }

type BailTypes =
  | Function
  | Map<any, any>
  | Set<any>
  | WeakMap<any, any>
  | WeakSet<any>

// NOTE not fully tested
export type UnwrapRefPropValue<T> = T extends BailTypes
  ? T
  : T extends Array<infer V>
    ? UnwrapRef<V>[]
    : T extends Ref<infer VR> ? UnwrapRef<VR> : UnwrapRef<T> // we might need to return T at some point

export function ref<T>(raw: T): Ref<T>{
    return null as any;
}


type Supa = {
    xx: number,
    x1: number
}
function setup(d: Supa, fn: () => Supa) {
    const r = ref(d);
    r.value = fn(); // works as expected
}

function setup2<T>(d: T, fn: () => T) {
    const r = ref(d)
    r.value = fn(); // error `Type 'T' is not assignable to type 'UnwrapRef<T>'`
}
```

**Expected behavior:**
Both should be assignable to **value**, the generic should be able to infer the type.

**Actual behavior:**
When using inside of generics it doesn't work, on the first example show an huge error log, the second one is `error "Type 'T' is not assignable to type 'UnwrapRef<T>'"`

**Playground Link:** 
[example1](http://www.typescriptlang.org/play/?ts=3.7-Beta#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgJWHQB4AVOAXjkyQE8A+OAbwCg44A3TAGwFdgAXHACqSAO5RMYQiVL0WAXxYtQkWHHS8k2GAghI4UImXoAKSWKGkAlEJknW7dkZi8oBpL27dqAZ2p0ANyKyjC0YHgAQpgI3KThwP4UbHAAPnAAYlo6ekgp6QCyUsQ0tAA0AQz5cADKwDAldPLs6QDqwJgA1kVgjeWVzU5tHZ11DaWDKuDQ8GERIuKS0sZylMwpRuhWcKCoSAAm-vbI6GhwAGqMAPwLElL2l3BWKZhQkrTbu8AH-gCCb5haMQTmdHjd-u9iKI7ssSJdGM92BAAEYAK2AOiETDgAG0ANKIAydYC0CDoOCkAC6QmhS3spHxlMYSnYvhgEDAzwUOPIXx+BCIKRuAHJNsKUp8QHtDnAIYC+oN2CLXu9xU4nhSdlLvjLorF4hFfCl1SK2RzhXAAPSWuDImI+CC8eD6OBzRKugAWmHgvg9ju4+yQwvgyLwWhhEX2xqckul-hR6J0cBFCYxMAtQmFZrAwspyhYyFQGBweFIiRgACZ1s4iHZjJ4ALahqD0MopJDl4D7LHR7COlB1kiN5uDBRt9gqwFCHEARgqFYqAGZKeO4A2pEIen0KhNV756kIxsRh2h5EpVDM4H2kGyryAaYt7ityxXGFQmAo-JUWNgQAA6TYAGpAJ-f8OzZLs-z7LQYGA4JlAvdRr1vX8KwfGF7EcJxNkHY9eCbU9V3YcDUG7at1ScaCBwFId8JHaMx2jScPlxOc4AXOBlyItcNzgLdSh3JpuP3GBD3qPCCJbRQ32YT9MH8UpQIrACiGApS-xIyCqNgwD4PUzT9jWLD2G0oQKxCFhNG0XQXRE3hejkUwyNICp0CQIRTGsShGBsciTP0W8oDWTYnOsaMoD-Lg+DwKg3M8wI4Ast1anszAjOjEB7zgE8oG4kAZyEHKQisnJbPqeyKycw9Utc9y4E87yUrATAvOMq8AvgIKqBC-ZrGCdUIqi-g1jivqLJYIA)
[example2](http://www.typescriptlang.org/play/?ts=3.7-Beta#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgJWHQB4AVOAXjkyQE8A+OAbwCg44A3TAGwFdgAXHACqSAO5RMYQiVL0WAXxahIsODFpg8oiVJllGVcqFRIAJgGcCRYsnRo4ANXnsA-CPGTpRAApQIYMTObHBCOl4yfgEGyuDQ8BpaHrre6FGBcpTMcADaANKISHAA1sC0EOhwpAC6YZ56vv5gjjz8ZPnVjEosiXgAQpgI3KSawFYUIQA+cABivEjYMAgQSFNwALJSxDS0ADTUdC5w0wDKwDDbh2sA6sCYxZuBO-s7R9O392cXrywsAPR-OAAOQA8qQAKJwJAQeDoXjcbi0dRjVBmWKqBKjZIRRoBFp8YAGLLGECmSxwAZDEZaCwhdykEJCElkqwAQSgklotiQ9igTiObmxDRIzhy1RC7CZcBMwHMVn0dgcjnwjHc4WFQRVoSFqSJALgYjwAFsEABzAAW8CQwGAZnUEDgUHOvCgRXImHgFggRrwkGQMF+KnicDhCyWK0dNjkAApJGImQBKIT6OSsdjsJ0wF1FJDw7jUKw7ADcil+PSxJ14YEwWTT6ZAICEuaNACM0LsJXAQABGJu8VtoUuhxbLIoWZ1gaNmISV6v7dBIITRhOURizzAruvsbArCzwPlUJ3oKcJkvpx0AOi4BKyC+XRbg+rE0GKhasKmAi1tpZYw-DY4nAAmAwpyZedFzgZdVyqTdOx3JA90dLIjxPTsoCvVo8CoO9T0fQE0H8PkAANqTwAByUgyMQKxoXgTALAsM0kEwFtuDwGAHV6OAyPVXU5DIoif1+IA)

The first example the code comes from [vue-next](https://github.com/vuejs/vue-next/blob/master/packages/reactivity/src/ref.ts#L71-L82)

**Comment by RyanCavanaugh** [comment]
I'm reading the definition of `UnwrapRef<T>` and can't convince myself that an arbitrary `T` should be assignable to it. Things that are true at zero-order might not be true at higher-order and TypeScript doesn't have the necessary higher-order logic to prove that all `T`s going in to `UnwrapRef` eventually produce something assignable from another `T`.

**Comment by kaigregliu** [comment]
You may wanna try 
```
