### ISSUE TITLE
Exclude declaration for a typing file from build - Typescript

### ISSUE THREAD

**Issue by kushalmahajan** [microsoft/TypeScript#33941]
I've two files. For one I want to emit the declaration file and for another file which in itself are common typings file, I don't want that behaviour.

Fairly simple, here's what I tried in `tsconfig.json`

```
"exclude": ["src/type.ts"]
```

yes that's right. In my compiler options, of course, my "declaration: true" is set to true.  Is possible to achieve? If not, please tag it as a feature request.

**Comment by RyanCavanaugh** [comment]
We don't plan to implement per-file control of declaration emit, at least without much more relevant information about why someone would want that.
