### ISSUE TITLE
Dynamic property name in interface

### ISSUE THREAD

**Issue by thany** [microsoft/TypeScript#33946]
**TypeScript Version:**  3.6.2

**Search Terms:** interface dynamic property, ts1170

**Code**

```ts
function buildUtility<PropType>(propName: string) {
  return function utility<Props extends Partial<{ [propName]: PropType }>>(props: Props): string {
    // Do something with `props[propName]` and have it be of type `PropType`
  };
}

buildUtility<string>('foo');
// --> function<Props extends Partial<{ foo: string }>(props: Props): string;
```

**Expected behavior:**
I would expect the interface to take `propName` and build an appropriate interface at compile time, but perhaps limit `propName` to being a constant string, i.e. not anything calculated at runtime.

Perhaps achievable by some tag applied to parameter `propName` that limits the caller to suppling only a literal string (or at least a string that can be evaluated at compile-time), like so:
```ts
function buildUtility<PropType>(literal propName: string) {
```

**Actual behavior:**
On `propName`, getting error `ts1170` that says:
```
A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.
```
My uninformed head tells me that it *is* referring to a literal expression (`'foo'` in this case) perfectly fine.

**[Playground Link](https://www.typescriptlang.org/play/?ts=Nightly&ssl=1&ssc=1&pln=5&pc=2#code/GYVwdgxgLglg9mABAIxDANgEwKq3TKATwB4AFAJzgAcAVQqgUwD4AKKyqgOQEMBbBgFyIAzlHIwwAcwCUiAN4AoRInIMoIcklCRYCRCDwESFasMQMAHlAZhMZ0t3Kxu6YnMQBtdtR78AukImtPQMiAC+TKzeVMKBHMLSQqLiUvJKyogA9JmIACJwInD8UAAWEpKIAO4EJYgABtHCXhy+DH51iNy2iCXcAG6hBCihcMCIRIz1QXSMdelhANwKYQqrqBg4hkTEyeWsAOTAcHD70gtAA)** 

**Related Issues:** 
#21000 (referring to symbols, not string)

**Comment by Nathan-Fenner** [comment]
You can achieve this by adding a type parameter:

```typescript
function buildUtility<PropType, PropNameType extends string>(propName: PropNameType) {
  return function utility<Props extends Partial<{ [k in PropNameType]: PropType }>>(props: Props): string {
    // Do something with `props[propName]` and have it be of type `PropType`
    return '';
  };
}

const x = buildUtility<string, 'foo'>('foo');
```

To get better inference (so that you don't need to repeat `'foo`') you need to change your function slightly, since you can't partially specify parameters:

[Playground](https://www.typescriptlang.org/play/?ts=Nightly#code/GYVwdgxgLglg9mABAIxDANgEwKq3TKATwB4AFAJzgAcA5AQwFsBTAFUKqcSYA8omxMAZ0SCo5GGADmAPgAUVSrUZMAXIgrV6zNhwCUiAN4AoRInJMoIckjKKdTOfoC80xKEiwEiEHgIkNVMI8fALCpHTksHToxAaIANoA1ogS6oparOxMALpqAfaIAL7ScgrUgnmKgrpqouJShiamiAD0LYgAInAicMxQABYSkogA7gT9iAAGZYHxMxnZk4h0Aoj9dABunAQonHDAiEQcU-lZk02m5pbWiADktwDcTYVPhUZGEAiiiNyITihoLC4DB+WS3YBwOC3XTEOpDRwPIA):

```typescript
function buildUtility<PropNameType extends string>(propName: PropNameType) {
  return <PropType>() => function utility<Props extends Partial<{ [k in PropNameType]: PropType }>>(props: Props): string {
    // Do something with `props[propName]` and have it be of type `PropType`
    return '';
  };
}

const x = buildUtility('foo')<string>();
```

**Comment by ashikvarma11** [comment]
You can do it like this.
```
function buildUtility<PropType>(propName:'foo') {
  return function utility<Props extends Partial<{ [propName]: PropType }>>(props: Props) {
    // Do something with props[propName] and have it be of type PropType
  };
}

const a={
  bar:'foo' as 'foo'
};
buildUtility<string>(a.bar);
```
