### ISSUE TITLE
Symlinked repo gives TS2717: Subsequent property declarations must have the same type.

### ISSUE THREAD

**Issue by ackvf** [microsoft/TypeScript#33945]
I have all repos in home folder `/Users/Qwerty/repos` and linked to `C:\repos`.

```
C:\>dir
 Directory of C:\

27.09.2018  21:07    <JUNCTION>     repos [C:\Users\Qwerty\repos]
```

I access all of the repos via `C:\repos` in VSCode and in cmd.

**TypeScript Version:**  3.7.0-dev.20191011

**Search Terms:**
folder, junction, symlink, duplicate

**Expected behavior:**

no error

**Actual behavior:**

```
../../../Users/Qwerty/repos/notino/nushopweb/packages/client/src/containers/App/model.ts:154:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'role' must be of type 'Roles', but here has type 'Roles'.

154     role: Roles;
        ~~~~

  packages/client/src/containers/App/model.ts:154:5
    154     role: Roles;
            ~~~~
    'role' was also declared here.
```

**Comment by sheetalkamat** [comment]
@ackvf Can you please post a repro sample. Its just hard to figure out whats going on without folder structure and which files are referencing to symlink or other folders
