### ISSUE TITLE
3.6.4 Partial field matching does not work for conditional type

### ISSUE THREAD

**Issue by crisslion** [microsoft/TypeScript#33944]
**TypeScript Version:** 

3.6.4

**Search Terms:**
Partial field conditional matching
3.6.4 conditional partial
**Code**

```ts
export type QueryType = (
  { __typename?: 'TypeOne' } & { a: boolean }
) | (
  { __typename?: 'TypeTwo' } & { a: boolean }
) | (
  { __typename?: 'TypeThree' } & { a: boolean }
);

type PickFromUnion<Union, Typename> =
  Union extends { __typename?: Typename } ? Union : never;

type FirstType = PickFromUnion<QueryType, 'TypeOne'>;
```

**Expected behavior:**
FirstType would be of type `  { __typename?: 'TypeOne' } & { a: boolean }`
**Actual behavior:**
FirstType is of type `QueryType`

**Playground Link:** 
3.6.3 where it works
http://www.typescriptlang.org/play/?ts=3.6.3#code/KYDwDg9gTgLgBDAnmYcCKBXYVEBVmoC8cAFAFBxwDecA+rUigHYCGAtsAPwBccA5PhQB5JsD5wAvnABk1OC14AjCBAA2wFk0lkAlHAA+pCnPqNgrDj36DguAO4RxU2TQVxlajVom6DRyjSmBBZcvAIEuAAWUMBikjJybh7qmto6ANxkZGZwAAoAlgDGANYAYlAQbACqTPkQTAA8NXVMADRwNiEAfHCExs31cKAw5gAmAM4mDMHsoR0zHPGccANavKIAbtiZ2QRwpflQ4zA2vXlFZRXVtfUNmNh4BO3hwqJ8XelAA

3.7 where it does not work (3.6.4 not provided in playground)
http://www.typescriptlang.org/play/?ts=3.7-Beta#code/KYDwDg9gTgLgBDAnmYcCKBXYVEBVmoC8cAFAFBxwDecA+rUigHYCGAtsAPwBccA5PhQB5JsD5wAvnABk1OC14AjCBAA2wFk0lkAlHAA+pCnPqNgrDj36DguAO4RxU2TQVxlajVom6DRyjSmBBZcvAIEuAAWUMBikjJybh7qmto6ANxkZGZwAAoAlgDGANYAYlAQbACqTPkQTAA8NXVMADRwNiEAfHCExs31cKAw5gAmAM4mDMHsoR0zHPGccANavKIAbtiZ2QRwpflQ4zA2vXlFZRXVtfUNmNh4BO3hwqJ8XelAA

**Comment by ahejlsberg** [comment]
This was broken by #33213. Simple repro:

```ts
declare let x1: { __typename?: 'TypeTwo' } & { a: boolean };
let y1: { __typename?: 'TypeOne' } & { a: boolean} = x1;  // No error!
```

Before #33213 this was an error, after it isn't.

**Comment by sandersn** [comment]
This change happened in 3.6.4, so I'm going to move this into 3.8.

**Comment by sandersn** [comment]
@crisslion In the meantime, you can work around this by making the discriminant required.

Actually, why was the discriminant optional in the first place?

**Comment by sandersn** [comment]
For the minimal repro:

1. Is `{ t?: "Two" } & { a }` assignable to each type in `{ t?: "One" } & { a }`?
2. Some type in `{ t?: "Two" } & { a }` must be assignable to `{ t?: "One" }` and some type in `{ t?: "Two" } & { a }` must be assignable to `{ a }`.
3. `{ a }` is assignable to `{ t?: "One" }` (because we are checking an intersection, weak type checks are turned off) and `{ a }` is assignable to `{ a }`.

So `{ t?: "Two" } & { a }` is assignable to each type in `{ t?: "One" } & { a }`.

**Comment by crisslion** [comment]
@sandersn We are generating typescript types from graphQL types so we are using `__typename` to pick specific type from union. `__typename` is optional because then don't have to make it optional/omit it when we are using the type.

I guess more precise data type we want to pick from is:
```
export type QueryType = (
  { __typename?: 'TypeOne' } & { baz: boolean }
) | (
  { __typename?: 'TypeTwo' } & { foo: boolean }
) | (
  { __typename?: 'TypeThree' } & { bar: boolean }
);
```

So only convenient way to select the right type is using type name.
At the moment as a workaround we reverted to previous version we had `3.6.2`

**Comment by sandersn** [comment]
> ` __typename` is optional because then don't have to make it optional/omit it when we are using the type.

I don't understand this part. Can you show me an example of how you omit it when using the type? How would it look if the property weren't optional?

**Comment by sandersn** [comment]
Fix is available at https://github.com/microsoft/TypeScript/pull/34789
