### ISSUE TITLE
Inference from union type between extended interfaces

### ISSUE THREAD

**Issue by sergeyshmakov** [microsoft/TypeScript#33943]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** "infer Intersection generic typescript"

**Code**

```ts
interface IHocProps {
    hocProp: string;
}
interface IPropsWithHocProps extends IHocProps {
    ownProp: string;
}

const SomeComponent = (props: IPropsWithHocProps) => <div />;

function WithHoc<OwnProps>(Component: ComponentType<OwnProps & IHocProps>): React.FunctionComponent<OwnProps> {
    const hocProps = {} as IHocProps;
    return (props: OwnProps) => <Component {...hocProps} {...props} />;
}

const ComponentWithHoc = WithHoc(SomeComponent);
```

**Expected behavior:**  `OwnProps = Omit<IPropsWithHocProps, keyof IHocProps>`

**Actual behavior:** `OwnProps = IPropsWithHocProps`

**Playground Link:** https://bit.ly/32a8nOg

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/8801

**Comment by RyanCavanaugh** [comment]
Shorter:
```ts
interface A {
    a: string;
}
interface B extends A {
    b: string;
}
type Foo<T> = { value: T };
declare function fn<T>(c: Foo<A & T>): Foo<T>;
declare const v: Foo<B>;
const p = fn(v);
```

This is the intended behavior. Inference doesn't produce types like `Omit<T, K>` nor attempt to "undo" subtyping.

You can write this as (simplified a bit):
```ts
type PropsOf<T> = T extends React.ComponentType<infer U> ? U : never;
function WithHoc<T extends React.ComponentType<any>>(Component: T): React.FunctionComponent<Omit<PropsOf<T>, keyof IHocProps>> {
    const hocProps = {} as IHocProps;
    return (props: unknown) => { 
        return <Component {...hocProps as any} {...props} />;
    };
}

const ComponentWithHoc = WithHoc(SomeComponent);
// OK
const k = <ComponentWithHoc ownProp="" />;
```

**Comment by sergeyshmakov** [comment]
@RyanCavanaugh Thanks for your answer!
I guessed that the option I proposed might be "undo".
And have a couple of questions:

**First**

Why we can't write just:

```typescript
function WithHoc<T extends IHocProps>(
    Component: React.ComponentType<T>
): React.FunctionComponent<Omit<T, keyof IHocProps>>
```

**Second**

In my case I'm trying to do it without `unknown` and `any` types in returnable component.
Why this is OK to use `return (props: unknown)` and `<Component {...hocProps as any} {...props} />`?
