### ISSUE TITLE
TS adds unexpected reference to outDir in d.ts

### ISSUE THREAD

**Issue by SkeLLLa** [microsoft/TypeScript#33950]
**TypeScript Version:**  3.6.4

When ts compiles code it adds unexpected reference to outDir which configured in tsconfig.json. E.g. if outDir is set to `dist`

**Code**

tsconfig:
```json5
{ 
  // ...
  "outDir": "dist",
}
```

```compiled.d.ts

/// <reference types="dist" />
```

**Expected behavior:**

No outDir reference.

**Actual behavior:**

`outDir` reference is present in compiled file

**Comment by SkeLLLa** [comment]
Possibly related issues:
https://github.com/Microsoft/TypeScript/issues/30021

**Comment by RyanCavanaugh** [comment]
How do we reproduce this behavior?

**Comment by SkeLLLa** [comment]
@RyanCavanaugh you can use this repo: https://github.com/SkeLLLa/fastify-metrics.

**Comment by RyanCavanaugh** [comment]
Pretty sure this is fixed now; we no longer synthesize referenced directives
