### ISSUE TITLE
Latest TypeScript and Javascript Grammar is deprecated?

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#33992]
This extension was recommended for me here but it doesn't colorize nullish coalescing, although the language service colorizes it. Is this extension deprecated?

```ts
const a = 0 ?? 0;
const b = 0;
```

https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

**Comment by j-oliveras** [comment]
I think that the colorize is already available with VS Code Insider.

**Comment by falsandtru** [comment]
Since I'm using colorization via this extension and using typescript explicitly installed per project, VSCode's built-in features wouldn't be related. And I confirmed the correct colorization on the latest VSCode.

**Comment by JakeTunaley** [comment]
Make sure you have the latest version of VS Code installed - I got the same bug with no extensions installed, and upgrading fixed it.

**Comment by sheetalkamat** [comment]
It is not deprecated but is updated less frequently since there is not much churn.

**Comment by falsandtru** [comment]
> It is not deprecated but is updated less frequently since there is not much churn.
Update I have just published next version earlier this week.

I understand this extension is sometimes behind with the nightly releases and not recommended for nightly users.
