### ISSUE TITLE
Class declarations should implicitly implement interfaces

### ISSUE THREAD

**Issue by mwisnicki** [microsoft/TypeScript#340]
http://typescript.codeplex.com/workitem/1125

Following should be allowed:

``` typescript
interface IFoo {
    foo();
}

declare class Foo implements IFoo {}
```

If abstract classes are added in the future, they would inherit all interface methods as abstract (like in Java).

**Comment by RyanCavanaugh** [comment]
Note that in the latest version of TypeScript, you can use class/interface merging to do this:

```ts
interface Foo {
	a: number;
}

interface Baz extends Foo { }
class Baz {
    constructor() {
        console.log(this.a); // no error here
    }
}
```
hat tip @jeffreymorlan for reminding me of this
