### ISSUE TITLE
New Website Logo: Rayvarz Software Engineering Co.

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#3400]
- Name:  Rayvarz Software Engineering Co.
- Homepage url: http://en.rayvarz.com/
- Brand Guidelines/Licensing: http://en.rayvarz.com/about-rayvarz
- Logo: http://oi62.tinypic.com/3syo7.jpg

**Comment by jonathandturner** [comment]
Do you have a larger size logo?  We use logos that are at least 300x300 (or larger) or in SVG.

**Comment by AliShahrivarian** [comment]
Hi. Thanks for your reply.
I must search Rayvarz Co. website for logo or contact them for bigger logo. I'll contact you.

**Comment by AliShahrivarian** [comment]
I updated  the request with new path of logo.
Can I send you another logo in future?

**Comment by jonathandturner** [comment]
Sorry for the delay, just got back to this.

The logo link points to a jpeg image, which isn't going to look good because it's not as high resolution as other logos on the site.  

Please submit a png or svg logo (see the original instructions)

**Comment by AliShahrivarian** [comment]
Hi
I'm working on svg logo. tnx for your reply.

**Comment by mhegazy** [comment]
@ghost please resubmit with an update logo.
