### ISSUE TITLE
Cannot find module during runtests

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3405]
Put these two files under tests/cases/compiler, and run `jake runtests tests=Blade`

**BladeMaterial.ts**
```ts
//@module: amd

/**
 * The base blade material class.
 */
export default class BladeMaterial {
	stiffness: number
	hardness: number
	constructor(public name: string) {
	}
}
```

**BladeCompositeMaterial.ts**
```ts
//@module: amd

import BladeMaterial from "BladeMaterial";

/**
 * Composite material for blade.
 */
export default class BladeCompositeMaterial extends BladeMaterial {
	constructor(public name: string) {
		super(name);
	}
}
```

The **BladeCompositeMaterial.ts** fails with TS2307: Cannot find module 'BladeMaterial`.

I tap into `program.getSourceFile` and add:
```ts
console.log(`${fileName}, hasProperty(...) => ${hasProperty(filesByName, fileName)}, filesByName: ${filesByName[fileName]}`);
```
i.e.
```ts

function getSourceFile(fileName: string) {
    fileName = host.getCanonicalFileName(normalizeSlashes(fileName));
    console.log(`${fileName}, hasProperty(...) => ${hasProperty(filesByName, fileName)}, filesByName: ${filesByName[fileName]}`);
    return hasProperty(filesByName, fileName) ? filesByName[fileName] : undefined;
}
```

the output result of `jake runtests tests=Blade` shows the order of the file matters:
tests/cases/compiler/bladematerial.ts, hasProperty(...) => true, filesByName: undefined
tests/cases/compiler/bladematerial.d.ts, hasProperty(...) => true, filesByName: undefined
tests/cases/bladematerial.ts, hasProperty(...) => true, filesByName: undefined
tests/cases/bladematerial.d.ts, hasProperty(...) => true, filesByName: undefined
tests/bladematerial.ts, hasProperty(...) => true, filesByName: undefined
tests/bladematerial.d.ts, hasProperty(...) => true, filesByName: undefined
bladematerial.ts, hasProperty(...) => true, filesByName: undefined
bladematerial.d.ts, hasProperty(...) => true, filesByName: undefined

  ․․․․․․․․․tests/cases/compiler/bladematerial.ts, hasProperty(...) => true, filesByName: [object Object]
tests/cases/compiler/bladematerial.ts, hasProperty(...) => true, filesByName: [object Object]
tests/cases/compiler/bladematerial.ts, hasProperty(...) => true, filesByName: [object Object]

The caller of `program.getSourceFile()` which creates this problem is in checker.ts: 882, in function `resolveExternalModuleName`: `sourceFile = forEach(supportedExtensions, extension => host.getSourceFile(fileName + extension));`

**Comment by DanielRosenwasser** [comment]
Tests in `compiler` and conformance` are independent of one another. If I recall correctly, you can make a multifile test in one file as so:

```TypeScript
// @filename: BladeMaterial.ts
export function blah() {
}

// @filename: BladeCompositeMaterial
import { blah } from "BladeMaterial";
```

Let us know if that helps.

**Comment by unional** [comment]
Yeah, I found that out after digging through the harness, programs, for a few hours. :(.
It may help others if CONTRIBUTING.md would mention that. :)

**Comment by DanielRosenwasser** [comment]
Sorry about that - that's a good suggestion, I'll fix it up in a bit.

**Comment by danquirk** [comment]
Yeah we should probably put it in the wiki too.

**Comment by DanielRosenwasser** [comment]
Done in #3424.
