### ISSUE TITLE
Export function with public signature not allowed

### ISSUE THREAD

**Issue by mwisnicki** [microsoft/TypeScript#341]
This is my sub-case of https://typescript.codeplex.com/workitem/1312.

Consider trivial export of function:

``` ts
module foo {
    function bar() {}
    export var pub = bar;
}
```

Compiler will complain about exporting private type `bar`. I could type it explicitly as `()=>void` but it doesn't scale to real world usage like wrapping functions with potentially complex, generic signatures:

``` ts
module foo {
    function wrap<T extends Function>(f: T): T {
        /* complex wrapping */
        return f;
    }

    /* complex generic signature */
    function _bar<T>() {}

    export var bar = wrap(_bar);
}
```

**Comment by thrandre** [comment]
This feature is still not released, or am I mistaken? Running version 1.3 of the compiler.

**Comment by RyanCavanaugh** [comment]
This issue as described is fixed in 1.3. Can you post an example of something you'd expect to work that doesn't?

**Comment by thrandre** [comment]
```
class Foo {}

var foo = new Foo();

export = foo;
```

I don't know if this is supposed to work or not. I'm getting the old "Exported variable 'foo' has or is using private type Foo" message.

**Comment by RyanCavanaugh** [comment]
That code compiles for me in 1.3 as long as `--d` isn't specified, which is the expected behavior.

**Comment by thrandre** [comment]
@RyanCavanaugh My fault. You are totally right - it does compile. R# was giving me a hard time.

**Comment by asgerhallas** [comment]
@thrandre off topic, but do you know if there's a way to get rid of resharpers incorrect warning about this? :)
