### ISSUE TITLE
Generic react component (TSX) and intellisense not working

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#34110]
from https://github.com/microsoft/vscode/issues/82276

**TypeScript Version:**  3.7.0-dev.20191011

**Search Terms:**
- completions / suggestions
- react

**Code**
For a simple typescript react file:

```tsx
import * as React from 'react';

type Props = {
    name: string;
    isActive: boolean;
};

export const CustomComponent = <T extends {}>(props: Props) => {
    return <React.Fragment>{props.name}</React.Fragment>;
};

export const TestComponent = () => {
    return (
        <CustomComponent<string> |>
            <div></div>
        </CustomComponent>
    );
};
```

1. Place cursor at `|` in `<CustomComponent<string>`
1. Trigger completions

**Expected behavior:**
Completions for `name` and `isActive` returned

**Actual behavior:**
No completions are returned.

If you add a property such as `isActive={true}`, then a completion for `name` is returned

**Comment by varemenos** [comment]
A friend of mine recently tried using JSX generics and it seems like this fix worked for them.

Here is an oversimplified code snippet that replicates the issue. We've tried this in two different machines and neither worked:

```
import * as React from "react"

type Variations = "hello" | "baaaaa" | "click"

const MyGeneric = <T extends Variations>({  }) => {
  return <div></div>
}

const Issue = () => {
  return <MyGeneric<"">></MyGeneric>
}
```
