### ISSUE TITLE
Should treat const and enum (at least const enum) value the same as literals for indexers.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#3411]
```typescript
const DATA_END_INDEX = 2;

enum OptimizedDataIndex {
    start,
    data,
    end
}

interface OptimizedData {
    0: number;
    1: any[];
    2: number;
}

var data: OptimizedData;
var start = OptimizedData[OptimizedDataIndex.start];
var end = OptimizedData[DATA_END_INDEX];
// expecting no error. `start` and `end` should be numbers.
```

This should also apply to something like tuples directly written as `[TypeA, TypeB, ...]`.

**Comment by danquirk** [comment]
Presumably your example intended to index into ```data``` and not the interface type. This is sort of the simplest case of constant propogation/flow control since the compiler can at least assume the name<->value pairs here are immutable.

**Comment by vilic** [comment]
So can I take that as "this suggestion is reasonable"? :D

**Comment by RyanCavanaugh** [comment]
Summary: When we see a property access where the indexing expression is an enum member, we should resolve the property access as if the indexing expression were actually the computed value of the enum member's value.

In other words, `var x = Foo[E.bar]` is equivalent to `var x = Foo[2]` if we can resolve `E.bar` to its value `2`.

**Comment by vilic** [comment]
And also consts, I think.

**Comment by jbondc** [comment]
Added a patch for the const enum access. Would also like to see these work:
```
const one = 1;
module dot {
   export const one = 1; 
}
const enum numbers {
    one = 1
}
const oneRef = one;
 
interface OptimizedData {
    0: number;
    1: any[];
    2: number;
}
let data:OptimizedData 

// works
data[1] // any[]
data[numbers.one] // any[]

// should work
data[one] // any[]
data[dot.one] // any[]
data[oneRef] // any[]
```
The last 3 could work but require better tracking of constants and constant propagation like @danquirk mentioned. Don't think you need flow control to do it properly, have gotten it working without anyways.

**Comment by RyanCavanaugh** [comment]
Approved for `const enum` members only. @jbondc can you get your PR up-to-date?

**Comment by mhegazy** [comment]
@jbondc, we would appreciate it if you can keep it only for const enums, and not for generic constant propagation.

**Comment by mhegazy** [comment]
thanks @jbondc!
