### ISSUE TITLE
Import `export =` using `import X from "Y"` syntax

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3413]
** Y.ts **
```ts
var Y = { a: 1}
export = Y
```

** A.ts **
```ts
import X from "Y"
```
Would it work or I need to import it using `import X = require("Y")`?
Visual Studio Code underline `X` as error saying `Module 'Y' has no default export.`

Thanks,

**Comment by zhongsp** [comment]
> A module that uses `export =` to export a non-module entity in place of the module itself must be imported using the existing `import x = require("foo")` syntax as is the case today.

So in modify A.ts:
```ts
import X = require("Y");
```

Another way, as the error msg suggest, modify Y.ts:
```ts
var Y = { a: 1 };
export { Y as default };
```

**Comment by ahejlsberg** [comment]
Unless you're interfacing with existing CommonJS or AMD modules, I would avoid the `export =` construct. Instead, use the new module constructs introduced in ES6:
```typescript
// ------ y.ys ------
export default { a: 1 };

// ------ a.ts ------
import x from "./y";
console.log(x.a);
```
