### ISSUE TITLE
Dependency Map?

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/TypeScript#3415]
Hi,

Is there a "Dependency Map" export option in the ts compiler. I am working on a fairly large UI framework with many classes and modules. Applications using this framework are not going to use all the classes all the time. Next to that, many of these classes need their corresponding css files, for example: "My.Button" class needs "My.Button.css". It would be very useful to see which classes are "actually used" in the project so we can bundle only those classes/files when building the final .js file.

Any thoughts?

Regards,
Gevik.

**Comment by mhegazy** [comment]
The compiler does not provide this as a feature out-of-the box. there are tools that can do that for you. for instance @basarat's https://atom.io/packages/atom-typescript has a dependency graph view.

**Comment by danquirk** [comment]
You probably want to +1 this issue https://github.com/Microsoft/TypeScript/issues/1479

**Comment by basarat** [comment]
Note : alm has this as well : https://basarat.gitbooks.io/alm/content/features/dependency.html :rose:
