### ISSUE TITLE
Insane response from compiler regarding type

### ISSUE THREAD

**Issue by renjithspace** [microsoft/TypeScript#34164]
Hi, is anything wrong with this code snippet?

Why` greet` accepting `number` still set `name` as `string` in this code
```
function greet (name: string) {
  console.log(typeof name) // number, WTF
  const greeting = `Hello ${name}`
  return greeting
}

const user: any = 1
console.log(greet(user)) // Hello 1
```

Can anyone help me out with this?

**Comment by j-oliveras** [comment]
This is how `any` type works (is assignable to and from any others types). Removing the `any` type you will see an error.

PD: please follow issue template or is probably that your issue will be ignored.

**Comment by renjithspace** [comment]
@j-oliveras @ahejlsberg, Thanks 👍
