### ISSUE TITLE
modules import failed

### ISSUE THREAD

**Issue by sneerin** [Microsoft/TypeScript#3416]
I've got next linking issue:
sever.ts:
/// <reference path='./_server.ts' />
import restify = require('restify');
import mongodb = require('mongodb');
import debug = require('debug');
import utils = require('utils/utils');
import routz = require('routes/routes');

export module Backends {

      class Backend {
        public server:any;

        private dbUtils:utils.DbUtils;

        constructor() {
            debug.log("starting server");
            this.startServer();

            debug.log("init mongo");
            this.initDb();

            debug.log("init routes");
            this.initRoutes();

        }

        startServer():void {
            this.server = restify.createServer();
            this.server.use(restify.bodyParser());
            this.server.listen('8080', ()=> {
                debug.log('listening port: 8080');
            })
        }

        initRoutes():void {
            var rts:routz.routes.Routes = new routz.routes.Routes(this.server,this.dbUtils);
        }
...

/routes/routes.ts:

/// <reference path='../../server/_server.ts' />

import utils = require('../utils/utils');
import userRoutes = require('./userRoutes');

export module routes {
export class Routes {

    /**
     * Initialize all application routes
     * @param app
     */
    constructor(app:any,dto: utils.DbUtils) {
        var userRoutes = new userRoutes.UserRoutes(app,dto);
    }
}

}

_server.ts

/// <reference path='../bower_components/DefinitelyTyped/restify/restify.d.ts'/>
/// <reference path='../bower_components/DefinitelyTyped/mongodb/mongodb.d.ts'/>
/// <reference path='../bower_components/DefinitelyTyped/debug/debug.d.ts'/>
/// <reference path='../bower_components/DefinitelyTyped/node/node.d.ts'/>

/// <reference path='../server/routes/routes.ts'/>

/// <reference path='../server/utils/utils.ts'/>

/// <reference path='../server/routes/userRoutes.ts'/>

/// <reference path='../server/dto/usersDTO.ts'/>

/// <reference path='../server/server.ts' />

everything compiles fine, when starting nodejs I've got next issue:

[15:52:26] Error: Cannot find module 'routes/routes'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mdomarev/workspace/singularex/angular-typescript-gulp-seed/dist/server.js:88:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by sneerin** [comment]
I used require('./routes/routes') and  require('routes/routes') not of them helped.
ts version 1.4.1, 

compilining with next options 
function compileServerScripts() {
    var tsProject = $.typescript.createProject({
        target: 'ES5',
        module: 'commonjs',
        inlineSourceMap:true,
        inlineSources:true,
        separateCompilation:false,
        declarationFiles: true,
        noExternalResolve: false,
        sortOutput: true
    });
    var opt = {
        tsProject: tsProject,
        inPath: ['server/**/*.ts', '/typings/**/*.ts'],
        outDefPath: '.tmp/definitions/server',
        outJsPath: '.tmp/js/server',
        outJsFile: 'server.js'
    }
    return compileTS(opt);
}

**Comment by danquirk** [comment]
This seems better suited to StackOverflow unless you think this is likely a compiler bug.

**Comment by sneerin** [comment]
if it is compiled it should work fine, am I wrong, but after compilation It's failed to start because of require issue. That's what compiler should handle I think.

**Comment by mhegazy** [comment]
looks like node is trying to find a module "routes/routes", is it in your node_modules?
if you have an empty .js file with only `var r = require("routes/routes");` does it work if you run it with node?

**Comment by mhegazy** [comment]
Looks like the original issue has been answered. please reactivate if you are running into other issues.
