### ISSUE TITLE
Inconsistency in "declare" modifier ordering in class fields

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#34172]
**TypeScript Version:**  3.7-beta

**Search Terms:**
Inconsistent declare class field property order

**Code**

```ts
class A {
    declare public x: string; // ok
    readonly declare y: string; // ok?
    readonly declare public z: string; // error, ok
}
```

**Expected behavior:**

Some modifiers currently have a mandatory ordering: the first one must be a visibility modifer, then comes `static` and then `abstract`/`readonly`. On the other hand, the new `declare` modifier can appear anywhere.

I think that it would make sense to restrict it, wither in the same position as the visibility modifiers or before tham.

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=5&pc=2#code/MYGwhgzhAECC0G8CwAoa7oBMCmowCdtoAHAVwCMQBLYaADwC5oIAXfKgOwHMBuVDaITCYA9hxABPLLnCFoEpq3bc+aDENHipOPHLKUa0AF6K2nXqgC+QA

**Comment by RyanCavanaugh** [comment]
Maybe it should have been this way all along, but this doesn't warrant making a breaking change for.
