### ISSUE TITLE
Please release a new 1.5 beta/rc

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#3419]
It's been a long time since the last release with over 726 commits.. There are a ton of changes the community could benefit from...

**Comment by RichiCoder1** [comment]
I believe they're wrapping up 1.5.2. Lots of pressure to release a quality build, especially with VS RTM and Ang 2, I should imagine.

**Comment by niemyjski** [comment]
Yeah, I understand.. But it wouldn't hurt to do a second pre release with the latest code so others can report any issues since the first beta :).

**Comment by mhegazy** [comment]
Release schedules can get a bit complicated with VS in the picture. You can always update locally with the latest from release-1.5 or master using DevMode: https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio. We have always kept master in a ship-ready quality.
