### ISSUE TITLE
Config to compile `const enum` as `enum` in development / Get SyntaxKind during development

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3422]
Hi,

When I work on the code, I have to change `SyntaxKind` from `const enum` to `enum` so that I can do ``write(`kind: ${SyntaxKind[node.kind]}`)``.

Is there a way to config the compiler and jake to treat `const enum` as `enum` so this would work?
Or is there another way to get the SyntaxKind without doing `SyntaxKind[node.kind]`?

Thanks,

**Comment by DanielRosenwasser** [comment]
You can keep the mapping at runtime with `--preserveConstEnum` for debugging purposes, but this behavior is the point of const enums.

**Comment by unional** [comment]
jake already passes `--preserveConstEnums` to tsc.js, but it still fails compilation:

`error TS2476: A const enum member can only be accessed using a string literal`

**Comment by mhegazy** [comment]
these exist only for debugging purposes. if you really want to do that cast to any. `(<any>ts).SyntaxKind[node.kind]`

**Comment by unional** [comment]
great! That's exactly what I'm doing. Just to write out stuffs to understand about the node for debug purposes.

`(<any>ts).SyntaxKind[node.kind]` works because `(<any>ts)` suppress all type checks?

Thanks a lot!

**Comment by mhegazy** [comment]
yes.
