### ISSUE TITLE
Identifiers inappropriately parsed as accessibility modifiers 

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3425]
This is a follow-up to #2995. I did not batch these up in the original issue because I wanted to limit the scope of it.

In the following, we currently interpret `public` as a modifier to the function declaration, only to report that it is invalid to use said modifier.

```TypeScript
public
function f() {
}
```

As in the previous issue, ASI should take effect and you should have an identifier named `public` as an expression statement, followed by a function declaration.

**Comment by mhegazy** [comment]
I believe our current behavior is better, though restricting valid JS code. the chances that this pattern is intentional valid code are really slim.
