### ISSUE TITLE
Formatting for custom Typeguard

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#3426]
Once the custom typeguard is check-in, we should add support for its formatting

For example,
```ts
class B { }
function isB(b: any): b is     B {
    return true;
}
```

**Comment by mhegazy** [comment]
@tinganho wanna take a look at this next?

**Comment by tinganho** [comment]
Do you mean by formatting the compiled JS code has appropriate formatting? I just checked it and it does have proper formatting in the above scenario.

**Comment by mhegazy** [comment]
no, formatting in an editor, in the typescript code. this is driven by the language service in https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L6479

**Comment by tinganho** [comment]
@mhegazy I will check it out.

**Comment by tinganho** [comment]
Just tried to fix this. I think I'm too unfamiliar with the formatting code base.

**Comment by RyanCavanaugh** [comment]
This might help as a comparison point -- https://github.com/Microsoft/TypeScript/pull/3470/files#diff-c00fb970b520e73379126b81f2de14f5L472

**Comment by tinganho** [comment]
Just two lines of code :smile:

**Comment by mhegazy** [comment]
thanks @tinganho!
