### ISSUE TITLE
Support exclude property in tsconfig in the language service

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3427]
We have added support for excludes. this is to track this in the LS https://github.com/Microsoft/TypeScript/pull/3188

**Comment by johnpapa** [comment]
which version of TS is this in? my tsconfig.json has exclude for node_modules, but its not excluding.

where is the changelog that shows which version got this?

**Comment by kitsonk** [comment]
1.6 or Microsoft/TypeScript@next.  The milestone in the issue (TypeScript 1.6) indicates which release it will be in.

**Comment by johnpapa** [comment]
thanks, didnt see the milestone
