### ISSUE TITLE
Recursive types recursively expand their own definitions with readonly modifier

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#34272]
@ahejlsberg 

**TypeScript Version:**  3.7.x-dev.20191013

**Search Terms:**

**Code**

```ts
type Tree = readonly [HTMLHeadingElement, Tree][];
```

**Expected behavior:**
```ts
type Tree = readonly [HTMLHeadingElement, Tree][]
```
**Actual behavior:**
```ts
type Tree = readonly [HTMLHeadingElement, readonly [HTMLHeadingElement, readonly [HTMLHeadingElement, readonly [HTMLHeadingElement, readonly [...][]][]][]][]][]
```
![image](https://user-images.githubusercontent.com/3143368/66724145-4f38c300-ee5d-11e9-8c5a-a10e92ec74dd.png)

**Playground Link:** 

**Related Issues:**

**Comment by falsandtru** [comment]
Also with error messages.

**Comment by Jessidhia** [comment]
That seems correct to me; the `readonly` _is_ part of the definition of `Tree` itself.

However, if you had not used `readonly` in the definition, and only used it at the "usage site" (`readonly Tree` or, say, `type ReadonlyTree = readonly Tree`) it should not recurse; but it could be good to have a way to make it recurse.
