### ISSUE TITLE
Union type inferred for generic arguments

### ISSUE THREAD

**Issue by michalburger1** [microsoft/TypeScript#34335]
**TypeScript Version:**  3.6.3 (used to work fine in 3.5.1)

**Search Terms:**  generic inference union type

**Code**
```ts
declare type Set1<T, K1 extends keyof T> = Pick<T, Exclude<keyof T, K1>> & {
    [KK1 in K1]: T[K1]
}

declare type Set2<T, K1 extends keyof T, K2 extends keyof T[K1]> = Pick<T, Exclude<keyof T, K1>> & {
    [KK1 in K1]: Set1<T[K1], K2>
}

declare function set<T, K1 extends keyof T, K2 extends keyof T[K1]>(source: T, path: [K1, K2], value: T[K1][K2]): Set2<T, K1, K2>

type MyStruct = {
    foo: {
        bar: number
        other: {}
    }
    other: {}
}

function func(data: MyStruct): MyStruct {
    return set(data, ['foo', 'bar'], 123) // Error here
}
```

**Expected behavior:**
The `set` call's type arguments are inferred as `MyStruct`, `"foo"`, `"bar"` and the code produces no errors.

**Actual behavior:**
Arguments are inferred as `MyStruct`, `"foo"`, `"bar" | "other"` and produce a type error.

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=21&pc=2#code/CYUwxgNghgTiAEAXAngBwQZRIgjAHgBUAaeAaR3hAA9EQA7YAZ3gGsRkB7AM3gID54AXngAFAJZgWhEgFEqkAK6g8bTj2JkcfAQDJ4AbwBQ8E-ADapcvDF1NAXQBcvCzjuGAvocOhIsBCnR4LEQAJmlNShp6JlZ2bl4SUhDI2gZmVXiCFzsBYXFJcLlFZQz1RK1dA2NTCysbeydg-CzyO0SQvg8vH2g4eC4FOjBEMQ5bRmxwq2pUmNKEsmSZ6PS49Wy+AApGDgUYMBAnDVQoRAALJxd2tvgANygIBUPnVosQuwBKRuwwjXJ2zqGAIIACyyAwiBgCmGQiqpn6HA4TiM8PhACNYE46AoALZokAwaqo+Acc4E5GeeGU0yks7kgyeTyGAZDEZjfqDMCbYCnKBOMEQqHDL7wAWQ6GIOGmOCIPbjbDc3kkMwAci4iJVJBVGJgKpuOBCAGYPh4gA

**Related Issues:**

**Comment by michalburger1** [comment]
I do realize that the code seems a little convoluted. Our actual code is more complicated, this is just the minimum repro case that I was able to reduce it to.

**Comment by michalburger1** [comment]
(Everything works fine if I explicitly specify the type arguments or use `'bar' as const`).

**Comment by ahejlsberg** [comment]
This appears to work as expected with 3.7-beta and the current nightly build.

**Comment by michalburger1** [comment]
Oh that's great to hear, thanks for checking! I would have tested 3.7 in the playground but the playground was broken with that version for some reason... Now it works though.
