### ISSUE TITLE
Working with modules and external packages

### ISSUE THREAD

**Issue by gilamran** [Microsoft/TypeScript#3438]
I want to be able to work with the ES6 module syntax when loading external packages, for example:

I want to import angular (Version 1.4, not the TypeScript version), and use the angular.d.ts to be able to get the definitions.

How should I do it?

**Comment by mhegazy** [comment]
TypeScript does not bundle Angular code with it. so there is no version dependency here. you can find Angular 1.* definitions on definitelyTyped: https://github.com/borisyankov/DefinitelyTyped/tree/master/angularjs

you can also use [tsd](http://definitelytyped.org/tsd/) to search, download and update your .d.ts in general.
