### ISSUE TITLE
hourCycle option not recognized for Date.toLocaleString

### ISSUE THREAD

**Issue by MasterOdin** [microsoft/TypeScript#34399]
TypeScript fails to recognize the `hourCycle` parameter for toLocaleString, documented on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).

**TypeScript Version:**  `3.7.0-dev.20191014`

**Search Terms:** `toLocaleString`, `hourCycle`

**Code**: `TS2345`

```ts
const a = (new Date()).toLocaleString('en-US', {hourCycle: 'h24'});
console.log(a);
```

**Expected behavior:**
Compiles without error

**Actual behavior:**
```
test.ts:1:51 - error TS2345: Argument of type '{ hourCycle: string; }' is not assignable to parameter of type 'DateTimeFormatOptions'.
  Object literal may only specify known properties, and 'hourCycle' does not exist in type 'DateTimeFormatOptions'.

1 const a = (new Date()).toLocaleString('en-US', {hourCycle: 'h24'});
                                                  ~~~~~~~~~~~~~~~~


Found 1 error.
```
The generated code then runs fine under Node 12 (I think it's not supported below this version) and in browsers and prints the expected output of the date with requested hour cycle.

**Playground Link:** http://www.typescriptlang.org/play/?ts=Nightly&ssl=1&ssc=50&pln=1&pc=70#code/MYewdgzgLgBAhjAvDAFGApgdxgETldFASiIDooQAZEYOAG3QGUoAnASzAHMUBXMAE3QAzDun4AaGAG8YACxA8WAYQCewBgC4YAclkBGAEzaYAXyIBuIA

**Related Issues:** 
I did not find any.

**Comment by BPScott** [comment]
This issue can be closed.

as of typescripit 4.2 `hourCycle` is present on `DateTimeFormatOptions` - the interface used for the second parameter of `toLocaleString` - when you target `es2020` or include it in your lib.

[This is a TS playground demonstrating that no errors occur if you target es2020](https://www.typescriptlang.org/play?target=7&ts=4.2.3#code/MYewdgzgLgBAhjAvDAFGApgdxgETldFASiIDooQAZEYOAG3QGUoAnASzAHMUBXMAE3QAzDun4AaGAG8YACxA8WAYQCewBgC4YAclkBGAEzaYAXyIBuIA)
