### ISSUE TITLE
"Initializing JS/TS language features" stuck on the status bar with windows unc workspace

### ISSUE THREAD

**Issue by PL47ER** [microsoft/TypeScript#34402]
*TypeScript Template info added by @mjbvz*

**TypeScript Version**: 3.7.20191013

**Search Terms**
- network drive
- unc

*original report below*

--- 

Issue Type: <b>Bug</b>

Basically I recently started using VS Code from a week now. I am not sure why am I getting this error message. Looking at github Issues section, it confuses me more as there were different solutions provided or some reporters didn't provide more information and the issue was closed.

If more informatin is required, you have to guide me with step by step guide on how I can retrieve the information required to be able to resolve this issue.

Please help.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by mjbvz** [comment]
@PL47ER Thanks for checking. When you tested using the mounted drive, did it produce those same error messages?

Also, where those the first set of errors in the log or were them some errors before them? If possible, please share the first error that is printed

**Comment by PL47ER** [comment]
@mjbvz Sorry to take long for reply but I already unmounted the drive and so unable to provide the log. Would you like me to test it again and provide the logs ?

**Comment by orta** [comment]
Looking into this, it looks like we make the assumption that accessing the JSON text of a [tsconfig will always succeed](https://github.com/microsoft/TypeScript/blob/de849b9a6be003357b3a078893c361e8b2963cd3/src/server/editorServices.ts#L1892). 

When the file is on a network drive, perhaps that isn't a safe assumption.

**Comment by orta** [comment]
I'm struggling to reproduce this (at least on a Mac) - I've set up onedrive, and tried running both a TS project and a JS project with tsserver logs but I'm getting nothing abnormal. 

So I've got a few questions:

- Is it possible maybe that the project was shared to you and hadn't finished downloading all of the files yet?
- Does the project have a `tsconfig.json` or `jsconfig.json`?
- Can you think of anything which might have triggered the start of the error loop?

**Comment by mjbvz** [comment]
@orta I think you may need to use a windows network drive (specifically opening an unc path). Try opening a local folder using a unc path like so: https://stackoverflow.com/a/2790936/306149

**Comment by orta** [comment]
Thanks @mjbvz - I tried to get a repro today via:

- using windows
- using onedrive mapped to a network drive
- using the `\\microsoft-my.sharepoint...` path to open the project

And that still wouldn't reproduce, the TS tooling loaded up for a Ts project and I tested on a JS project separately too 

 ![Annotation 2020-01-10 043514](https://user-images.githubusercontent.com/49038/73024337-65123880-3dfb-11ea-966e-2930824222c8.jpg)

Any ideas on what I could be missing @PL47ER ?

**Comment by mjbvz** [comment]
Thanks for checking @orta. I can't repo this on TS 3.7.5 either. 

@PL47ER Are you still seeing this?

**Comment by orta** [comment]
I'm going to call this as working with 3.7.5

**Comment by Fischmuetze** [comment]
The issue appear also in 2019 ... now end of 2020 it isn't fixed on  1.50.0, macOS Catalina
Holy moly ...

**Comment by ghasemikasra39** [comment]
same here. Any solution?

**Comment by m1m6** [comment]
Same here

**Comment by NtkArt** [comment]
Same here.

**Comment by reifnotreef** [comment]
This is happening for me when connected to a Live Share session. It finishes pretty quick when working locally though.

**Comment by mjbvz** [comment]
If you are still seeing this, please open a new issue with steps to reproduce
