### ISSUE TITLE
emitDecoratorMetadata

### ISSUE THREAD

**Issue by berbar** [microsoft/TypeScript#34429]
It sets emitDecoratorMetadata is true in the 'tsconfig.json';

If the classes depend on one another, It will occur exception.

I think it will be better that it emit a function returning the type.

```js
function TestReflect(target, methodName) {
}
class CApple {
    Some(banana) {
    }
}
__decorate([
    TestReflect,
    __metadata("design:type", Function),

    // it occurrs error. The class CBanana is undefined.
    __metadata("design:paramtypes", [CBanana]),
    // if it emit a function callback, it will be ok
    __metadata("design:paramtypes:delay", [ () => CBanana]),

    __metadata("design:returntype", void 0)
], CApple.prototype, "Some", null);
let CBanana = class CBanana {
    constructor(apple) {
    }
};
CBanana = __decorate([
    TestReflect,
    __metadata("design:paramtypes", [CApple])
], CBanana);
```

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
