### ISSUE TITLE
ts.transpile fails with TypeError: Cannot read property "key" from undefined

### ISSUE THREAD

**Issue by lealgerardo** [Microsoft/TypeScript#3446]
Trying to evaluate this in Typescript 1.5.0 beta:

let result = ts.transpile(source, { module: ts.ModuleKind.CommonJS });

produces TypeError: Cannot read property "key" from undefined, this prevent the compilation from happening.

The error is caused by the ts.getLocaleSpecificMessage method:

 ts.getLocaleSpecificMessage = getLocaleSpecificMessage;
	    function createFileDiagnostic(file, start, length, message) {
	        var end = start + length;
	        Debug.assert(start >= 0, "start must be non-negative, is " + start);
	        Debug.assert(length >= 0, "length must be non-negative, is " + length);
	        Debug.assert(start <= file.text.length, "start must be within the bounds of the file. " + start + " > " + file.text.length);
	        Debug.assert(end <= file.text.length, "end must be the bounds of the file. " + end + " > " + file.text.length);
	        var text = getLocaleSpecificMessage(message.key);
	        if (arguments.length > 4) {
	            text = formatStringFromArgs(text, arguments, 4);
	        }
	        return {
	            file: file,
	            start: start,
	            length: length,
	            messageText: text,
	            category: message.category,
	            code: message.code
	        };
	    }

message.key, meesage.category and message.code calls will all fail because message is undefined. 

The only way around it that I have found is to edit the generated js code to add a message? message.key : "" type of hack. That enables the compiler to work.

**Comment by mhegazy** [comment]
@lealgerardo can you share the code sample that this happened on, or at least the call stack?

**Comment by lealgerardo** [comment]
The error happens even with the simplest code such as:

```
/// <reference path="typings/typescript/typescript.d.ts" />

import * as ts from "typescript";

const source = "let x: string  = 'string'";

let result = ts.transpile(source, { module: ts.ModuleKind.CommonJS });

console.log(JSON.stringify(result));
```
I am using tsc -t ES5 --module amd then using webpack to packge all the files and then running from nashorn inside the JVM. Thus the cryptic stacktrace:

```
Caused by: <eval>:1582 TypeError: Cannot read property "key" from undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.get(Undefined.java:152)
	at jdk.nashorn.internal.scripts.Script$Recompilation$487$85658AAAA$\^eval\_.L:590$L:592$L:1277$createFileDiagnostic(<eval>:1582)
	at jdk.nashorn.internal.scripts.Script$Recompilation$475$1732106$\^eval\_.L:590$L:592$L:29355$createProgram$verifyCompilerOptions(<eval>:29831)
	at jdk.nashorn.internal.scripts.Script$Recompilation$454$1712817AAA$\^eval\_.L:590$L:592$L:29355$createProgram(<eval>:29492)
	at jdk.nashorn.internal.scripts.Script$Recompilation$325$2108866AAAA$\^eval\_.L:590$L:592$L:35289$transpile(<eval>:36318)
```

However as I mentioned before I can get the transpile to work correctly without the error by going into the packaged source and changing this code:

```
ts.getLocaleSpecificMessage = getLocaleSpecificMessage;
function createFileDiagnostic(file, start, length, message) {
var end = start + length;
Debug.assert(start >= 0, "start must be non-negative, is " + start);
Debug.assert(length >= 0, "length must be non-negative, is " + length);
Debug.assert(start <= file.text.length, "start must be within the bounds of the file. " + start + " > " + file.text.length);
Debug.assert(end <= file.text.length, "end must be the bounds of the file. " + end + " > " + file.text.length);
var text = getLocaleSpecificMessage(message.key);
if (arguments.length > 4) {
text = formatStringFromArgs(text, arguments, 4);
}
return {
file: file,
start: start,
length: length,
messageText: text,
category: message.category,
code: message.code
};
}
```

to support an undefined message param. For example even doing this hack makes it work:

```
ts.getLocaleSpecificMessage = getLocaleSpecificMessage;
function createFileDiagnostic(file, start, length, message) {
message = message || {};
...
}
```

**Comment by lealgerardo** [comment]
Seems like this call passes the undefined message:

```
function verifyCompilerOptions() {
...	         ts.Diagnostics.Cannot_compile_non_external_modules_when_the_separateCompilation_flag_is_provided));
...	                
```
Although I see ts.Diagnostics defined int he packaged source:

ts.Diagnostics. 
```
...
	})(ts || (ts = {}));
	// <auto-generated />
	/// <reference path="types.ts" />
	/* @internal */
	var ts;
	(function (ts) {
	    ts.Diagnostics = {
	        Unterminated_string_literal: { code: 1002, category: ts.DiagnosticCategory.Error, key: "Unterminated string literal." },
...
```

And that error is defined:
```	        Cannot_compile_non_external_modules_when_the_separateCompilation_flag_is_provided: { code: 1208, category: ts.DiagnosticCategory.Error, key: "Cannot compile non-external modules when the '--separateCompilation' flag is provided." },
```

So there might be a scope issue.

**Comment by vladima** [comment]
just tried on the release-1.5 branch, works for me.

```typescript
import * as ts from "./typescript";
const source = "let x: string  = 'string'";
let result = ts.transpile(source, { module: ts.ModuleKind.CommonJS });
console.log(JSON.stringify(result));
```

compiling it to js produces 
```javascript
// run.js
var ts = require("./typescript");
var source = "let x: string  = 'string'";
var result = ts.transpile(source, { module: ts.ModuleKind.CommonJS });
console.log(JSON.stringify(result));
```

and running ```node run.js``` yields
```
"var x = 'string';\r\n"
```

**Comment by mhegazy** [comment]
@lealgerardo can you try the latest from branch release-1.5 as @vladima mentioned. you can find the latest at: https://github.com/Microsoft/TypeScript/tree/release-1.5/bin
If this still repros, then this there might be a nashorn-specific issue..

**Comment by lealgerardo** [comment]
Thanks for trying it, in node it works for me too. However I am trying to run this outside node. So if i take the above code (say in a file called Compiler.js) and run it through webpack:
```
module.exports = {
	context: __dirname + "/build/scripts",
	entry: { 
		compiler: "./Compiler"
	},
	output: {
		path: __dirname + "/build/dist",
		filename: "[name].js",
	},
	resolve: {
		extensions: ["", ".js"]
	},
	node: {
		fs: "empty"
	}
};
```

Then I get the same error.  And I can see the ts.Diagnostics being included in the packaged .js

```
	// <auto-generated />
	/// <reference path="types.ts" />
	/* @internal */
	var ts;
	(function (ts) {
	    ts.Diagnostics = {
```

**Comment by vladima** [comment]
Can you share the result of running compiler through webpack?

**Comment by lealgerardo** [comment]
Sure , here is a link: 

[compile.js](http://dropcanvas.com/pt7uq)

**Comment by mhegazy** [comment]
the file looks normal to me. i do not have access to nashorn installation to dig deeper though, so any help would be appreciated.

**Comment by vladima** [comment]
+1, file looks ok and it runs successfully on node.

**Comment by lealgerardo** [comment]
Well, turns out that it is then a nashorn issue, though i also see it in rihno with 1.4.

The problem seems to be that there are more than 255 properties on the ts.Diagnostics object

ts.Diagnostics = {
};

If i reduce the number of properties int hat object to 255 it works, if i add one more i see the error because the entire ts.Diagnostics gets undefined,

Of course this is strange, since it seems to relate to the number of properties and not the actual size of the object.

**Comment by mhegazy** [comment]
thanks for looking into this @lealgerardo. this is useful information. We need to file an issue for Nashorn for this one.

**Comment by lealgerardo** [comment]
Thanks guys. If anyone reading this needs to run the typescript compiler from the JVM you will run into this and for now my workaround is to modify the typescript.js from the ts node module directly adding the message = message || {} inside the first line of  createFileDiagnostic as follows:

```
function createFileDiagnostic(file, start, length, message) {
	message = message || {};
...
```

This will at least allow nashorn to run the compiler.

**Comment by mhegazy** [comment]
Please note that this means you will not get any errors from the compiler, as it will not be able to find any error messages.

**Comment by michel-kraemer** [comment]
Just for your information. The JVM bug is here:
https://bugs.openjdk.java.net/browse/JDK-8079426

It has been closed/solved so upcoming JVM versions should have the fix.

**Comment by michel-kraemer** [comment]
By the way, here is a working workaround which might be useful for other people trying to run the TypeScript compiler on the JVM:
https://github.com/michel-kraemer/vertx-lang-typescript/commit/89e168fb7d08ab721409f67116ce2d9621cb3c40

It basically replaces the following code

```javascript
    ts.Diagnostics = {
        Unterminated_string_literal: { code: 1002, ... },
        Identifier_expected: { code: 1003, ... },
        ...
    };
```

with

```javascript
    ts.Diagnostics = {};
    ts.Diagnostics.Unterminated_string_literal = { code: 1002, ... },
    ts.Diagnostics.Identifier_expected = { code: 1003, ... },
        ...
    ;
```

Works great in vertx-lang-typescript!

Cheers,
Michel
