### ISSUE TITLE
Object.keys incorrect return type

### ISSUE THREAD

**Issue by Connormiha** [microsoft/TypeScript#34498]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
const a = { a: 'foo' };

Object.keys(a).forEach((key) => {
    console.log(a[key]);
});
```

**Expected behavior:**
No error

**Actual behavior:**
```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ a: string; }'.
  No index signature with a parameter of type 'string' was found on type '{ a: string; }'.
```
**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=9&ssc=4&pln=6&pc=1#code/MYewdgzgLgBAhjAvDA3vAXDA5AMxCLGAXwG4BYAKEoHkAjAKwFNgoA6Aa0YE8IAKOAJSs8AJwCicYAAtevTlwFIAfKkox1MUJBAAbRqx0gA5vwDa8gLoDyFItcpA

**Related Issues:**

**Comment by dragomirtitian** [comment]
There are good reasons for the current types.

Read here for the explanation : [So answer](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript/55012175#55012175)

**Comment by RyanCavanaugh** [comment]
Search Terms:
