### ISSUE TITLE
Type assertion inconsistencies for objects with index signatures and arrays

### ISSUE THREAD

**Issue by jedster1111** [microsoft/TypeScript#34492]
Sorry in advance if this is a duplicate, I tried to find any one else mentioning this but couldn't see it.

**TypeScript Version:**  3.7-beta (The version currently on the Typescript Playground)

**Search Terms:**
assertion
empty array
index
key
property is missing in type but required in type assertion

**Code**

```ts
interface IndexExample {
  a: { [key: string]: string };
  b: string;
}

export const test = { a: { foo: "test" } } as IndexExample; // unhappy

/*
* Conversion of type '{ a: { foo: string; }; }' to type 'IndexExample' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'b' is missing in type '{ a: { foo: string; }; }' but required in type 'IndexExample'.(2352)
**/

const test2 = { a: {} } as IndexExample; // happy

interface ArrayExample {
    a: string[];
    b: string;
}

export const test3 = { a: [] } as ArrayExample // unhappy

/*
* Conversion of type '{ a: never[]; }' to type 'ArrayExample' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'b' is missing in type '{ a: never[]; }' but required in type 'ArrayExample'.(2352)
**/

export const test4 = { a: [""]} as ArrayExample // happy
```

**Expected behavior:**
I would have thought that all of the above examples `test1-4` wouldn't have complained.

**Actual behavior:**
- If the interface contains an index signature, seems to complain if you provide at least one key, but doesn't complain if you provide none.
- If the interface contains an array, seems to complain if the array is empty, but doesn't complain if there is at least one element in the array.

**Playground Link:** 
http://www.typescriptlang.org/play/?ts=3.7-Beta#code/JYOwLgpgTgZghgYwgAgJIgCYQB4FFtwC2ADgDYoDeAUMsnAFzIXIDaA1hAJ6MDOYUoAOYBdXvyHIAvgG4ayAEZiBIQbMlUqOYgHsoYZAm0g+ySCYC8TOo2Yxt2xgCIzYR1PdweaTDnxEyEBqGxvouAEzIlswMTJIeXuhYeAQk5BqgkLCIKACCUFBwnH6plHK0MXzKgizCsrS0isiVQmoaWrr6wSYuAMyRVjE18ch5BUUpAW3YOnoGRt0QfAAs-dGMLI6OwnGeI-mFxZNAA

**Context:**
The intention was to mock out large objects in tests while still maintaining a bit of type safety.

Give me a shout if you need any more information, or if I've missed something obvious. This behaviour seems a bit weird to me but maybe I'm wrong 😄

**Comment by RyanCavanaugh** [comment]
See comments in #9312, #7531, #16995, etc.

**Comment by Retsam** [comment]
Is there an issue that explains why `{[key: string]: string}` isn't assignable to `{foo: string}`?  The compiler complains that "foo" is missing in the index type, but doesn't the index type claim to have string values for any key, including "foo"?  

That's the underlying issue with the `IndexExample`.

**Comment by RyanCavanaugh** [comment]
> Is there an issue that explains why `{[key: string]: string}` isn't assignable to `{foo: string}`

No. It's definitely inconsistent, but preferable to having `{[key: string]: any}` be assignable to anything. Even  `{[key: string]: string}` -> `{foo: string}` would be an assignment that, in practice, would be very unlikely to be correct
