### ISSUE TITLE
Support for modules in Meteor

### ISSUE THREAD

**Issue by Nessphoro** [Microsoft/TypeScript#3450]
Good day,

As it currently stands Typescript's modules are not entirely compatible with Meteor's execution environment, which is caused by Typescript's  compilation procedure whereby modules are created as "var ModuleName". This prevents  Meteor from seeing modules as being global and hence modules are file-scoped. 

Currently in production we have to resort to the following hacks:
```typescript
module ModuleName
///<reference path="../../definitions/madhax.d.ts" />
{
    export class ClassName
    {
          ...
    }
}
```

This prevents typescript from removing the reference comment even if remove comment flag is turned on and instead injects the comment immediately after "var ModuleName;"  so that our internal js processor can detect the include of "madhax.d.ts" and patch the definition of "var ModuleName"  with "if (typeof ModuleName == 'undefined') { ModuleName = {}; }". Forcing ModuleName to be declared in the global scope.

Therefore, I suggest a new keyword "globalexport" that will cause the compiler to emit code without a var for declaration, and in the case of function to be emitted as "FunctionName = function() {}" to match the expected behaviour of global properties in Meteor and "globalexport".

So, the above would instead have
```typescript
globalexport module ModuleName
{
    export class ClassName
    {
          ...
    }
}
```
Which compiles to 
```javascript
(function(){if (typeof ModuleName == 'undefined') { ModuleName = {}; }
(function (ModuleName) 
{
    var ClassName = (function () {
        function ClassName() {
        }
        return ClassName;
    })();
    ModuleName.ClassName = ClassName;
})(ModuleName || (ModuleName = {}));
})();
```

**Comment by mhegazy** [comment]
Exporting to the global is not a uniform operation for all JS runtimes. e.g., it can be window, self, global, module, this etc..

moreover this emitted code pattern would fail in strict mode as the module has not been declared. looks like this is has already been discussed in a meteor issue: https://github.com/meteor/meteor/issues/1380#issuecomment-23577957; this looks like a meteor issue that is hiding/disabling a JS feature.
