### ISSUE TITLE
Allow functions with no return await

### ISSUE THREAD

**Issue by avalanche1** [microsoft/TypeScript#34510]
**TypeScript Version:** 
^3.7.0-beta

**Search Terms:**
- typescript function must return a value await
- typescript function must return a value eslint no-return-await  

**Code**
eslint is unhappy
```ts
async function foo(): Promise<string> {
  return await fnThatReturnsAPromise;
}
```
typescript is unhappy
```ts
async function foo(): Promise<string> {
  await fnThatReturnsAPromise;
}
```
I have eslint rule [`no-return-await`](https://eslint.org/docs/rules/no-return-await) which Disallows unnecessary return await. But it conflicts with typescript.
**Expected behavior:**
Should allow functions without `return`
**Actual behavior:**
If I remove the `return` - typescript throws:
>`Error:(8, 58) TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.`  

**Playground Link:** 
Cannot add `eslint` to playground :(

**Comment by AlCalzone** [comment]
What about
```ts
function foo(): Promise<string> {
  return fnThatReturnsAPromise();
}
```
?

**Comment by RyanCavanaugh** [comment]
> Should allow functions without return

You said your function returned something, then you didn't return anything. It's simply wrong to try to allow that.

**Comment by avalanche1** [comment]
Well, that's great. But what should I do with eslint's rule?

**Comment by avalanche1** [comment]
@AlCalzone , that seems like burying the problem one level deeper

**Comment by AlCalzone** [comment]
@avalanche1 Why?
```ts
async function foo(): Promise<string> {
  return await fnThatReturnsAPromise;
}
```
behaves identically to 
```ts
function foo(): Promise<string> {
  return fnThatReturnsAPromise;
}
```
`return await` creates and returns a new Promise that simply waits for the original one to be settled. Instead just returning the original Promise is better.

Removing `async` and `await` is also the first solution that is mentioned in the documentation for the eslint rule.

> Inside an async function, return await is seldom useful. Since the return value of an async function is always wrapped in Promise.resolve, **return await doesn’t actually do anything except add extra time** before the overarching Promise resolves or rejects. The only valid exception is if return await is used in a try/catch statement to catch errors from another Promise-based function.


> This rule aims to prevent a likely common performance hazard due to a lack of understanding of the semantics of async function.
> 
> Examples of incorrect code for this rule:
> 
> async function foo() {
>     return await bar();
> }
> 
> Examples of correct code for this rule:
> 
> async function foo() {
>     return bar();
> }
