### ISSUE TITLE
`asserts x is type` doesn't work when using arrow functions

### ISSUE THREAD

**Issue by mweststrate** [microsoft/TypeScript#34523]
**TypeScript Version:** 3.7.0-dev.20191016 

**Search Terms:** assertion signatures, asserts, asserts is type

**Code**

```ts
function isString1(val: any): asserts val is string {
    if (typeof val !== "string") throw "Nope"
} 

const isString2 = (val: any): asserts val is string => {
    if (typeof val !== "string") throw "Nope"
} 

const x: any = "3";

isString1(x);
isString2(x);

x.toUpperCase();
```

**Expected behavior:**

Compiles, infers that `x` is a string, both when using only `isString1` or `isString2`

**Actual behavior:**

Compile error on `isString2`:

```
Assertions require every name in the call target to be declared with an explicit type annotation.(2775)
```

**Playground Link:** [1⃣ playground](http://www.typescriptlang.org/play/?ts=Nightly&ssl=15&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABDAzgZSgJxmA5gRgAoA3AQwBsAuRUsATwEprSUUBTTKFRM85blFhy5EAbwBQiKcmCJCUOgAc2cWb0QBCALxbEAIkHY8ehoigALTHADu+gHJxle8QF9E48RASD+GI7gAmRF0SCmZ6JhpWDi4eCn5EQ2FggD4xSWkYWXklFTV47V0DIWNTCytbPQcnV3dPbyhEAA9wumD9AGY9AG4PVD9hIiaGXv6SwMJh3vEmgDooOABVRWVMAGEWNkIR8SA)

**Related Issues:** #33743 

**Context**

In principle the above problem is easy to work around, however, the result of it is when type checkers are stored on objects, the above error returns as is demonstrated in [2⃣ this playground](http://www.typescriptlang.org/play/?ts=Nightly#code/C4TwDgpgBAKuEGEAWEDGBrCAnAPDAfFALxQDeAUFFVABQBuAhgDYBcUDAdiAJRsMDO-bMH5RGTKAEtRMANzkAvuXIAzAK4dUwSQHsOUALYNMcSHnw1UegCZt6zPl27FCAIx06mETr1jxkaJi4BGSU1FgQwGpY+uqa2nq04o48odTpUiq0AIRWHNb2TNzOwEhYOgDuUBwQVQCiWOVYNABEAPI6YPwt3GFUCuyinCCKynn8wFL8AMrAWJIcAOZspogoGNg4E-NLhCRGJvA0hSnORISgkDpZ4sREJC3bC4s9Y3oTUKjrQfwAjMRkKazHaLKBKcaTL6BbD8ABMbFIQLmzxW-m+myeuzBAMR0mBzzB5Ahn3RWH4AGYEUiQWxLhBrtSCQMSLiZsiloTiVCNmSACw4xkcgYCT7vYBvDgfAAeKQBLXJLXk5Dx7MWNCl3Hk3J+vwAdCqQerNVAAPQmqD8JA6NRMazVHSTMDlaxqVDQKwGMCSLxQbBNImkuH6tmGjVawPk4P4pZG8PQvlR1Wx03my3W232x3O13unSe73QP06LDKKW64A6ACqYEgWAQAggNE15CAA). Note how the very same function fails when it is stored in an object, unless the type is provided explicitly.

**Comment by mweststrate** [comment]
Thanks for looking into it! Nothing I cannot work around in the end. Just felt surprising / inconsistent :)

**Comment by pstrh** [comment]
As mentioned here (https://github.com/microsoft/TypeScript/pull/33622#issuecomment-575301357) a workaround is:

```
const isString2: (val: unknown) => asserts val is string = (val) => {
    if (typeof val !== "string") throw new Error ("Nope");
};

const x: unknown = "3";

isString2(x);

x.toUpperCase();
```

**Comment by Pyrolistical** [comment]
A better error message on this design limitation would have been nice instead of the confusing TS 2775

**Comment by voltrevo** [comment]
> This is (perhaps unfortunately) working as intended, as per #33622.

Unfortunate indeed. Do you know the rationale behind this intention? What would be the complication of allowing arrow functions to have type assertions?

**Comment by kaspar-p** [comment]
Is there a way to type object literal members in the above way? I can't seem to get either to work:
```ts
const assertions = {
  isString(val: unknown): asserts val is string {
    if (typeof val !== "string") throw new Error("Nope");
  },

  isString2: (val: unknown): asserts val is string => {
    if (typeof val !== "string") throw new Error("Nope");
  }
}
```

**Comment by Moriarty47** [comment]
Just like [pstrh](https://github.com/pstrh) [this comment](https://github.com/microsoft/TypeScript/issues/34523#issuecomment-700491122) said.

```typescript
const assertions: {
  isString: (val: unknown) => asserts val is string;
  isString2: (val: unknown) => asserts val is string;
} = {
  isString(val) {
    if (typeof val !== "string") throw new Error("Nope");
  },
  isString2: (val) => {
    if (typeof val !== "string") throw new Error("Nope");
  }
}

const x: unknown = '123';
assertions.isString(x)

x.toLowerCase();
```
