### ISSUE TITLE
interface FunctionDeclaration missing jsDoc property  

### ISSUE THREAD

**Issue by IWANABETHATGUY** [microsoft/TypeScript#34532]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Looks like you hit "submit" too early - please refile with a complete report. Thanks!
