### ISSUE TITLE
class private attribute can be accessed

### ISSUE THREAD

**Issue by iEuJen** [microsoft/TypeScript#34533]
class Demo {
    private p: number
    constructor () {
        this.p = 233
    }
}
let demo = new Demo()
console.log(demo.p)
// error: Property 'p' is private and only accessible within class 'Demo'.
but---------------------------
class Demo {
    private p: number
    constructor () {
        this.p = 233
    }
}
let demo = new Demo()
let list:Array<any> = []
list.push(demo)
console.log(list[0].p) // 233
// Successfully passed, no error

**Comment by j-oliveras** [comment]
First, follow the issue template.

Second with the second code you have a compilation error on the type `Array` so it works as intended.

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs
