### ISSUE TITLE
Inferred returned type incorrect for input type with optional array property

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#34536]
**TypeScript Version:**  3.7.0-dev.20191017

**Search Terms:**

inferred return type optional property discriminated union

**Code**

```ts
type A = { type: 'foo' }
type B = { type: 'bar' }

type Union = A | B

type Parent = {
    other: string,
    buttons?: Union[]
}

// supposedly returning a Parent type which ain't true
const parse = (parent: Parent) => {
    if (parent.buttons) {
        return {
            ...parent,
            buttons: parent.buttons.map(b => {
                // correct type here
                const button = { ...b, disabled: true }
                return button
            })
        }
    }
    
    return parent
}

type Ret = ReturnType<typeof parse>

declare const ret: Ret

// no .disabled property here
ret.buttons![0]
```

**Expected behavior:**

The returned type shouldn't be a Parent but rather an expanded union of `Parent`

**Actual behavior:**

The returned type is Parent and information about conditionally added `.disabled` property gets lost.

**Playground Link:**

[Link](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAglC8UDeVSQFxQOQDMD2eWUAvgFBrQBCCyq4EmWARgIYBORZ59UAqgHYBLPPxpwAPlEqlukKAAV2EfsBpJSUTVDzAAFhDaYAzsDaD+AcwA0GrUwCuwYCKMB+TAOH8A2gF1SXAD0gVBG9mBgeEYQACYANiBQbBDA9mxCllAsCkoqdHIA7rqCAMa6WeZYqqb2EKQlLqpg7NE0ABTNySqYil3AAJQIAHzItpqCOFAducAAdA5OLoPqWqtJKWmiK2s7s3udysA2OzsLzvxGmAcq847nRrMAtixgbUzDoydfUMFQDWzJErVHj6ZJjb6rBoXVRnERqKB7eZWKAxQRGFhMOKxTA1aBkCE7ZKpdJQWH8cFfYj9ClafG08HgombKDXYABGQUKAAJRSNB5xP4ABV6AAeCh4SadaJDGQxCAlOJKP6NdbATD8mS-fh4BGo9GY2Isth4SBsUBQUF1Im3RYXACE3gADP4gA)

**Related Issues:** 

Couldn't find any

**Comment by RyanCavanaugh** [comment]
The return type isn't wrong, it's just not as precise as you may have wanted. The return type is (before simplification) `Parent | (Parent and some other stuff)`, which is subtype-reduced to `Parent`. You can add a return type annotation or type assertion in a variety of places to get the behavior you'd like.

**Comment by Andarist** [comment]
I can annotate this to make this work properly - sure. Would be great to leverage inference here though.

From a technical point of view, I guess you are right - this is not "incorrect", but certainly some info gets lost here somewhere and this doesn't even look like the most complex case (no fancy TS features involved). From a user's perspective, this might seem "broken".
