### ISSUE TITLE
vscode: File resolution in "node_modules/.bin" should be relative to the module

### ISSUE THREAD

**Issue by connorjclark** [microsoft/TypeScript#34544]
Please see https://github.com/microsoft/vscode/issues/82014.

Copy'd from above:
___

For an example, yarn add nyc and open node_modules/.bin/nyc. The relative requires do not link to the files that are required at runtime.

Would need to know which module installed each bin. Probably by parsing all the package.json's in node_modules. After a quick glance, I see there is not a way to query yarn or npm for this information.

![image](https://user-images.githubusercontent.com/4071474/67040017-75699780-f0d7-11e9-9065-ca32f50d799f.png)

VS Code version: Code 1.37.1 (f06011a, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0
___

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AviVahl** [comment]
Probably has to do with the fact that these are symlinks. Resolution context should be `dirname(realpathSync(requestingFilePath))` and not the link's containing directory.

**Comment by RyanCavanaugh** [comment]
I don't understand what the issue is here - what is/isn't happening that you expected?

**Comment by connorjclark** [comment]
Cmd+clicking on a `require(...)` usually opens the file that Node would load. This relies on VSCode knowing how to resolve these files based on Node conventions. This feature does not work when in a file in `node_modules/.bin`.

https://github.com/microsoft/vscode/issues/82014#issuecomment-543313265 says that this Node feature within VSCode is managed by TypeScript, so I open this issue.

**Comment by AviVahl** [comment]
@RyanCavanaugh a path such as `/project/node_modules/.bin/tsc` links to a file in `/projects/node_modules/typescript/bin/tsc`. When opening the file *via the link* imports are resolved as if the context was `/project/node_modules/.bin`, instead of the actual file's directory (`/project/node_modules/typescript/bin`).
This affects the behavior of ctrl+click on require calls and imports.
