### ISSUE TITLE
Propagate type parameter with constraint

### ISSUE THREAD

**Issue by marekscholle** [microsoft/TypeScript#34571]
## Search Terms
generic, generics, type inference

## Suggestion
Better type inference or convenient syntax to force compiler to infer advanced type instead of the default one.

## Problem

The following function declarations are inspired by `ramda` library, used by collegue of mine: 

```ts
function prop<P extends string>(p: P): (obj: Record<P, number>) => number;
function ascend<T>(fn: (obj: T) => number): (a: T, b: T) => number;
function sort<T>(fn: ((a: T, b: T) => number)): (list: readonly T[]) => T[];
```

These functions can be combined as `sort(ascend(prop('x')))`, to be read as "sort by property `x` , ascending". 

The actual array to be sorted is then passed in second parameter list as `sort(ascend(prop('x')))(arr)`. The problem with expression `sort(ascend(prop('x')))(arr)` is that `sort(ascend(prop('x')))` has to be parsed first. This is what compiler infers now (3.6.3):

```ts
// OK
const propX = prop('x'); // (obj: Record<"x", number>) => number

// OK
const ascend_propX = ascend(propX); // (a: Record<"x", number>, b: Record<"x", number>) => number

// OUCH
const sort_ascend_propX = sort(ascend_propX); // (list: readonly Record<"x", number>[]) => Record<"x", number>[]
```

Thus for

```ts
interface Point {
  x: number;
  y: number;
}
const point = {x: 1, y: 2};
const points: Point[] = [point];
```

we have

```ts
const sorted = sort_ascend_propX(points) // Record<"x", number>[]
```

altough clearly, `sorted` should be `Points[]`.

IMHO the compiler should infer the type for `sort_ascend_propX` as in: 

```ts
const sort_ascend_propX = function <T extends {x: number}>(ts: T[]) {
  return sort<T>(ascend_propX)(ts);
  // equivalently: return sort<T>(ascend(prop('x')))(ts);
}
```

That is, it is should "propagate" the `T` from `sort` with constraint that `T` is assignable to `Record<"x", number">`.

The alternative is to provide a syntax that will force compiler to infer this more complicated type. I'm not a JS/TS dev, so without my own daily experience it's hard to propose something reasonable. I imagine something like 

```ts
const sort_ascend_propX<T extends {x: number}> = sort<T>(ascend_propX);
const <T extends {x: number}>sort_ascend_propX = sort<T>(ascend_propX);
```

if we want to save the function object to variable.

```ts
const sorted = sort<>(ascend(prop('x')))(points);
```

If we want to force to "propagate `T`" on `sort`.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
Change the return type of `sort` to,
```ts
<ElementT extends T>(list: readonly ElementT[]) => ElementT[];
```

**Comment by marekscholle** [comment]
@AnyhowStep  Thank you, I missed that part. The actual declaration in ramda is 
```ts
sortWith<T>(fns: Array<((a: T, b: T) => number)>): (list: readonly T[]) => T[];
```
which is insufficient. I can imagine that even with this declaration, the compiler could be less aggresive and infer `const sort_ascend_propX = sort(ascend_propX)` to be `<T extends {x: number}> (list: readonly T[]) => T[]`, i.e. "propagate `T` with constraint as proposed in issue name or allow a client to "fix" this insufficient declaration with something like `const <T extends {x: number}>sort_ascend_propX = sort<T>(ascend_propX);` (see above), but this can be complicated and would need much more thought. I propose to close this issue.

**Comment by marekscholle** [comment]
@AnyhowStep  Playing a bit more with this example, I found things does not work exactly as I would expect, I tried to distill the problem to this example:

```
function prop<P extends string>(p: P): <T>(obj: Record<P, T>) => T { throw new Error() }
function descend<T>(fn: (obj: T) => any): (a: T, b: T) => number  { throw new Error() }
function sortWith<T>(fns: Array<(a: T, b: T) => number>): <U extends T>(list: readonly U[]) => U[] { throw new Error() }

interface Point {
    x: number
    y: number
}
const points: Point[] = [{x: 1, y: 1}]

// OK 
const sortFns = [descend(prop('x'))];
const sorted: Point[] = sortWith(sortFns)(points)

// NOT OK: can't inline sortFns
const sorted2: Point[] = sortWith([descend(prop('x'))])(points)
```

The declaration of `prop` and `ascend` are directly from ramda typings, `sortWith` is alredy fixed by recommendation above.

What's surprising that inlining `sortFns` definition directly to `sortWith` confuses compiler, in other words, introducing a local const (without annotation!) helps compiler. This may be a compiler bug, can you look at it?

[http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=1#code/GYVwdgxgLglg9mABABwE52QHgAqIKYAeUeYAJgM6LlSoxgDmAfABTIBci2AlB5gCos4AIwBWHAEp4IcVKRwAaRAK6IAvIyWIA3oigALdAHdEYPMYCiqdKmYqAvgChQkWAkSk85CCTkDmwMA5mYTElFXVEAEMwAE8eRGZIjj5FIWTwjTAQAFshPFREbV0DOGNTCysZW0RHZ2h4JHIZKAB1GH1+FgDyDgBBK0iYzETk1PS1TJy81EZ4zABVfCIfSj8AGxhqDlQ8SNIENZjEeYBtAF0M4-Oi-SMTM0RLa2rHBzpiVGBI7044d+0HIVCgQOFlcvlAUCYqCphDHNIwNQUH8wFAer93tdVIgTloQYgAIyKaGEuxnBwOAD0lMQAHkANKIBwIpFNVBQABiiLUOI8Xh8rHQyGYAHICCKuFwzgBuZkIVnNPCkDjYFFQLFUZptfTMNmcxFcVhq8hcCnUxAAOVpfDp9I4EGiIqgiDoG1MmvZXPIcsRzr1SoATCq1Rq9dq9MwTnzvGRBRhReLJRcje8TQ4gA](Playground)

**Comment by fatcerberus** [comment]
For what it's worth, the fact that a generic isn't automatically propagated during type inference doesn't strike me as particularly surprising: this case seems roughly analogous to the [monomorphism restriction](https://wiki.haskell.org/Monomorphism_restriction).  In general, type inference gets really complicated once you try to infer polymorphic types, so type systems tend to avoid it.

**Comment by marekscholle** [comment]
@AnyhowStep Should I create a separate issue for the problem described in  https://github.com/microsoft/TypeScript/issues/34571#issuecomment-544560436
namely that inlining variable definition leads to different result? This issue is not really related to original issue.

**Comment by AnyhowStep** [comment]
I feel like creating another issue for it might not be a bad idea, just to give it more visibility
