### ISSUE TITLE
No error when initializing a class field defined as a read-only getter in base class

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#34585]
**TypeScript Version:**  3.6.4

**Search Terms:**

"Related Issues" feature of GitHub uses the title as search terms.

**Code**

```ts
class Base {
  get foo() {
    return 5
  }
}

class Child extends Base {
  foo = 10
}

new Child // runtime error!
```

**Expected behavior:**

Type error during compile

**Actual behavior:**

No error until runtime.

**Playground Link:** 

[playground](http://www.typescriptlang.org/play/#code/MYGwhgzhAEBCkFNoG8CwAoa0DmCAu0AZgPbEAUAlChllgE74CudAdtAKw3QC+Gv6GUJBgBhABYBLEABNoCAB54ELaTHgQkaTEVLQAvNACMABj4YMLBAHdo4qbID0D6HUYs8EgLZIEdOsToAQiA)

**Related Issues:** 

Might be duplicate of https://github.com/microsoft/TypeScript/issues/13347, but not sure.

**Comment by AviVahl** [comment]
Checked this snippet of code directly in Chrome, and there's no runtime error when evaluating `new Child`. I get a new Child instance with a `foo` field === 10, and it is assignable (unlike instances of `new Base`).
do you mean you get a runtime error if you transpile this using typescript (to es5) and then run?

I believe this issue has to do with: https://github.com/microsoft/TypeScript/issues/27644

**Comment by fatcerberus** [comment]
I don't know how TypeScript is supposed to handle this, but classfields in ES use `[[Define]]` (think `Object.defineProperty`) which bypasses the setter in the base class, so this is legal JS; that's probably why you're not getting a runtime error in Chrome @AviVahl.

**Comment by trusktr** [comment]
@AviVahl Yeah, exactly, if TS compiles to the form

```ts
constructor() {
  this.foo = 10
}
```

then it doesn't work. This can happen with either `es5` target, or the new `"useDefineForClassFields": false` option (I haven't tested it with the latter).

**Comment by sandersn** [comment]
This is an error with useDefineForClassFields: true, which [will be the default target for target: "esnext" when class fields reach stage 4](https://github.com/microsoft/TypeScript/issues/34787). That's because it's quite confusing, even though it's legal [stage 3] JS. It could always be an error, but this is a problem that real code rarely encounters. [When I looked at our user test suite, the only examples I found were in old, pre-`readonly` code](https://github.com/microsoft/TypeScript/issues/27644#issuecomment-541780387), and I believe Google and Bloomberg found the same to be true on their internal code bases.

This would be a nice feature but not required, and fairly easy to implement since the error is already there, so I'm going to move this into the backlog and put the Help Wanted label on it. It's a good feature if you want to focus on identifying breaks in the ecosystem.

**Comment by trusktr** [comment]
@sandersn Thanks for the fix! Btw, I see the error message is

`'foo' is defined as an accessor in class 'Base', but is overridden here in 'Child' as an instance property.`

in [4-beta playground](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/MYGwhgzhAEBCkFNoG8BQ1oHMEBdoDMB7QgCgEoV0NoAnXAVxoDtoBWKgXyolwOJIBuALmhN6AWwBGCGhWRcuqUJBgBhABYBLEABNoCAB44ETHTHg9KGIoWgBeaAEYADKkVMEAd2gbtOoA) even if `useDefineForClassFields` is disabled and I have a `set`ter. Isn't that code legal when `useDefineForClassFields` is false?

That is amazing that when `useDefineForClassFields` is set to true that there is a type error on accessor overrides! Very nice in helping people avoid problems.

**Comment by sandersn** [comment]
We decided to disallow properties overriding accessors in 4.0 for everyone, so that when class fields finally do move to stage 4, any code that could get tripped up by the [[Set]] -> [[Define]] migration would have time to get fixed.

**Comment by ntucker** [comment]
what's wrong with this if the Child class marks it as readonly?

**Comment by sandersn** [comment]
There's still some kind of initialisation, and whether that affects base accessor depends if you are compiling with [[Set]] (classic TS) or [[Define]] (ESNext) semantics. For example:

```ts
class Base {
  get foo() {
    return 5
  }
}

class Child extends Base {
  readonly foo = 10
}
```

Still crashes with [[Set]] semantics, because the emitted code has a `this.foo = 10`:

```js
class Base {
    get foo() {
        return 5;
    }
}
class Child extends Base {
    constructor() {
        super(...arguments);
        this.foo = 10;
    }
}
```

**Comment by isral** [comment]
@sandersn 
I have **setter only** property
But the code that **get** the property is not considered compile error (return undefined at runtime).
Is this related to this bug? Or should I issue a new bug?
Typescript 4.3.2 (VS Code) 4.3.5 (Command Prompt).

**Comment by sandersn** [comment]
@isral Please do open a new bug. It's a lot easier with an example to look at.
