### ISSUE TITLE
Should the literal number value types of const-asserted arrays' indices be inferred?

### ISSUE THREAD

**Issue by btoo** [microsoft/TypeScript#34589]
## Search Terms

array tuple const assertion literal index number

## Suggestion, Use Cases, and Examples

I would like to infer the index type of a `const`-asserted array to be that of its position in the array, rather than just `number` (i.e. I want the literal number type). However, I can't seem to create a way to extract this into a `type`, even though I know TypeScript is holding onto this information _somewhere_.

For example, this code follows my intuition:
```typescript
const days = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'] as const;

/** "Mo" | "Tu" */
type FirstTwoDays = (typeof days)[1 | 2]

/** 7 */
type DaysCount = typeof days.length;

const impossibleDayIndex = 88;
/** Tuple type 'readonly [...]' of length '7' has no element at index '88' */
type CorrectlyErrors = (typeof days)[typeof impossibleDayIndex];
```
Yet here, `index` is of type `number`. Although this is understandable, given the signature of `Array['forEach']`, it begs the question - how could I assert, as the `as const` does, that `index` should be of type `0 | 1 | 2 | 3 | 4 | 5 | 6`?
```typescript
days.forEach((day, index) => {});
```

Likewise, how could I get this to "work"?
```typescript
const indexTypeLost = days.indexOf('Tu')
/** number, rather than 2 */
type IndexTypeLost = typeof indexTypeLost
```

The closest I can get to achieving my desired `type` is with
```typescript
/** number | "0" | "1" | "2" | "3" | "4" | "5" | "6" | "length" | "toString" | ... */
type IndicesOfDays = keyof typeof days;
```
but it's not perfect:
```typescript
const convertIndexToDay = (index: IndicesOfDays) => days[index]
convertIndexToDay(impossibleDayIndex) // incorrectly does not throw an error
```

## Checklist

My suggestion meets these guidelines:

* [?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
Partial workaround,
```ts
const days = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'] as const;

type Keys<T extends readonly any[]> = {
    [k in keyof T] : k
}[number];

type keys = Keys<typeof days>

/** "Mo" | "Tu" */
type FirstTwoDays = (typeof days)[1 | 2]

/** 7 */
type DaysCount = typeof days.length;

type PopFront<ArrT extends readonly any[]> =
    ((...arr: ArrT) => void) extends ((_: any, ...tail: infer TailT) => void)?
    TailT :
    never
;

type PushFront<TailT extends readonly any[], HeadT> =
    ((head : HeadT, ...arr: TailT) => void) extends ((...arr: infer ArrT) => void)?
    ArrT :
    never
;

type IndexOf<
    ArrT extends readonly any[],
    ValueT extends ArrT[number],
    IndexTHack extends readonly any[] = [],
    ResultT extends number = never
> =
    {
        0: number,
        1: ResultT,
        2: IndexOf<
            PopFront<ArrT>,
            ValueT,
            PushFront<IndexTHack, any>,
            ResultT|(ValueT extends ArrT[0] ? IndexTHack["length"] : never)
        >
    }[
        number extends ArrT["length"] ?
        0 :
        ArrT["length"] extends 0 ?
        1 :
        2
    ]
;

declare function indexOf<ArrT extends readonly any[], ValueT extends ArrT[number]>(
    arr: ArrT,
    value : ValueT
): IndexOf<ArrT, ValueT>;

//2
const tu = indexOf(days, 'Tu' as const)

//2|3
const tuWe = indexOf(days, 'We' as 'Tu' | 'We')

//0|5
const suFr = indexOf(days, 'Su' as 'Su'|'Fr')
```
[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=63&pc=46#code/MYewdgzgLgBAJgQwJ4RgXhgbQOQGUCu2ANDNgLIjGkAqhJ2A6gKZXbUAWrAYgE6u4JsAXRgJUoSFADcAKBlQkAByYwA0kxQAeajCYAPKEzBxUPJgjjgANklFgkmIQD50MAN4yYXrAGsYASzAYHw0QADMYahEALmCZAF9MMHwAWwAjJh4hWXklFRCUV3UtBWVw+GQIJzkAegAqOpgAIgommAAfZto2uprc5Rgufx5oagB3EAARStcAClKmcsQUAEpMAEYOmAAmIVqGmAB2GF7+lWmUAGEQfDBYDAWlyoA6KyMAcyh2HIWYAAUQIpeOAoJoAII8Hg6fSGYymcyWMA2OwOZzoTzeWazZ44hCQ2IQqErdAuABuIH8cGJMKMJhgWIA+rEEPYSDjnlAEP4rLFAmFMpEuVZqMS0GSKVSAPwYrzUIU6aIymBgJikzIyH55f74CDsYF3bTy3QGWnwizWWws1EkAASCOoLjQSqx7ARMFidos1DZuPxgu5IpJMHJlOpJrh9Oxvp4vLA-J4MEJgbFwYlK2l3kTkIVSpVap4GrkvwAksZ9AB5MKaJVJ42wulmc1Iy32RxEJUANQQVnwTGh4bpSaSqQyWXbmdLcH01BtCGAfhpEcbiORVscrjbSoASkwIPgrFB+-XUMl0gKMHn1Y6lR5M5mAAyxU+j8d3rzrWI7vcH71KzPbWJJwrKs-zff5AX1UEkycV8wO8Lsez7WC4O1XVIM0IC9BnOcfBIK0YNAt8v33Q92lmBDeyPU0syhTB7xESUYEw7D50wJo3jAT52CaGJlVVTIVkImBqkzRIhOfAVF0HbM2I4rieJgDMwPvd0hKHdiPi+BSpNQFSlLfTZFTg7YlT2HIp2AKw8RUMJbmAKB-HAAIyz0StwWzOtqOXC0UTbGAKL7TyIyHCSsicWYlTxGMaN-TNSW7Xt3X8hK+xkFZAJctykxIAKHRyGoahMiRoBgKB8FcQIp1csJZmWCB6FobBRHEcBoEEmQCu2doAGYZGK2AyuYCrMpqur6GYJqxBoQgtkYFh2oK+92gAVj61rYD3XhhqqytasqegCEm1A8EIdpsF4bAViAA)

**Comment by AnyhowStep** [comment]
For "number keys",
```ts
const days = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'] as const;

/** "Mo" | "Tu" */
type FirstTwoDays = (typeof days)[1 | 2]

/** 7 */
type DaysCount = typeof days.length;

type PopFront<ArrT extends readonly any[]> =
    ((...arr: ArrT) => void) extends ((_: any, ...tail: infer TailT) => void)?
    TailT :
    never
;

type PushFront<TailT extends readonly any[], HeadT> =
    ((head : HeadT, ...arr: TailT) => void) extends ((...arr: infer ArrT) => void)?
    ArrT :
    never
;

type NumberKeysOf<
    ArrT extends readonly any[],
    IndexTHack extends readonly any[] = [],
    ResultT extends number=never
> =
    {
        0: number,
        1: ResultT,
        2: NumberKeysOf<
            PopFront<ArrT>,
            PushFront<IndexTHack, any>,
            ResultT|IndexTHack["length"]
        >
    }[
        number extends ArrT["length"] ?
        0 :
        ArrT["length"] extends 0 ?
        1 :
        2
    ]
;

//type k = 0 | 1 | 2 | 3 | 4 | 5 | 6
type k = NumberKeysOf<typeof days>;
```
[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=44&pc=36#code/MYewdgzgLgBAJgQwJ4RgXhgbQOQGUCu2ANDNgLIjGkAqhJ2A6gKZXbUAWrAYgE6u4JsAXRgJUoSFADcAKBkB6AFSKYAIgqqYAHzW1Ni+TKhIADkxhcAlj2jUA7iAAiyVBgAUxsyABm8FwEpMAEZtGAAmITklFQB2GAMjU3NnFABhEHwwWAxPJh8-FAA6ABsmMABzKHZZRLMYAAUQE15wKAAeAEEeHmoYJgAPKDK4VB4mBDhwYqRRMCRMIQA+dBkYNZg3N0LthG6ALhgunv90ZYA3EEs4E4GhsBGNtwB9A4Q5km3CqARLYoPLMDeJg8GDUH7FagnNDnS7XAD8q3WYN+vT2iLWYCYZ2BMhquQa+Ag7BaWTayIhfUGw1G40mYGms3mQhIAAladRlmh0Y92LSYAc2RNqB8dvtQeDIacYBcrjcqfdUJtPrseP9AcDDt1JdDpbD-Aj1pqevzuZjsTxcXJ8QA5fAAWwARsCANJMFAAeW8bW5R16t2pMDGEymMzeTKI3IAkvcBtQWQhgABrSl3B5BukMsMLdBYZncgBKTAg+GKUD98oeYHtTp4aDNOM53IA3tzDQAGA5Vx3AiOGw1BA6F4ul4Wt9ZhA627s8V0er1jvsNJok9q+xa9xd9+qE4k8VptaNwWPxpMkMPrhd9oclstaQ-HhOJzCqUoVKqqSKbmCLbkAX0wl5djWKYBr6z6vpU7AfjABqbm2JpfmBL5lJB0H+gqMDwbBi4hGiX5hNykQ1PI8j4smGDwToIQ6GEoQAMyhAALKEACsoQAGy1OY5EwFONazhAnptLk+SICgixSEAA)

**Comment by btoo** [comment]
Damn. That was an astoundingly clever usage of spread function params as a vehicle for recursively building an array! Tried it out myself and it indeed works. Then I was reminded of a talk (i think) anders hejlsberg had where he mentioned [TypeScript having some internal recursion limit](https://github.com/Microsoft/TypeScript/issues/23024#issuecomment-377711022), and I was able to confirm: for me,`NumberKeysOf` breaks down for an array `as const` at around the length of 42 (intelligently defaulting to `number` because `Type instantiation is excessively deep and possibly infinite`)

I guess even if it had worked, it would've been a masterly albeit roundabout way of achieving what I thought would be a lightweight inference task. As you can see I am not a TypeScript expert lol

**Comment by AnyhowStep** [comment]
There are ways to work around the depth limit but those are a bit out of scope =x

I agree it would be nice to get TS to just give us the number literal keys of a tuple without hackery.

A nicer way to type `indexOf()` would be nice, too

The workarounds above are... Not great

**Comment by RyanCavanaugh** [comment]
This one is kind of problematic and would need a bunch of special handling, or new type system primitives we currently don't have.

Fundamentally, `keyof` is an operation that returns string literal types, because that's how JS properties work. But `forEach` gives *numeric* values to the `index` argument, and obviously only includes the array indices themselves.

**Comment by btoo** [comment]
getting the literal number types for `as const` arrays is a little easier with template literal types

https://x.com/mattpocockuk/status/1801625713272893750

[playground link](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAkgdgEwgDwgZwPIDMCCAnPAQxAB4AVKFYCRNKPCQhAezgBsQpC4QBtAXQB8UALxQyzAHIBXALYAjCHhIAoKFADWEEMyziVggNwqVoSOKlzFyilRoI6ABTzNIeUAGltwkWvGVkalooAAMAEgBvAEs4LCUoAFUAoIcoOCslAF8QqAB+RKgALjSIADclYwB6SqgAWnqAY2lgetqVasSAZRwAcQBREwbWNGA0wll0USheACJZQmBgGYAaKBm3BpAVtYRCUqiEGf4uOiG4EeNTcGhJcYh4JFQ6MQeUdGx8IlIzCF0xibQRnaNXUAD1ckA)

**Comment by btoo** [comment]
getting the literal number types for `as const` arrays is a little easier with template literal types

https://x.com/mattpocockuk/status/1801625713272893750

[playground link](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAkgdgEwgDwgZwPIDMCCAnPAQxAB4AVKFYCRNKPCQhAezgBsQpC4QBtAXQB8UALxQyzAHIBXALYAjCHhIAoKFADWEEMyziVggNwqVoSOKlzFyilRoI6ABTzNIeUAGltwkWvGVkalooAAMAEgBvAEs4LCUoAFUAoIcoOCslAF8QqAB+RKgALjSIADclYwB6SqgAWnqAY2lgetqVasSAZRwAcQBREwbWNGA0wll0USheACJZQmBgGYAaKBm3BpAVtYRCUqiEGf4uOiG4EeNTcGhJcYh4JFQ6MQeUdGx8IlIzCF0xibQRnaNXUAD1ckA)
