### ISSUE TITLE
Poor typing for array iterator

### ISSUE THREAD

**Issue by pauldraper** [microsoft/TypeScript#34581]
**TypeScript Version:**  3.6.3

**Search Terms:** Array iterator

**Code**

```ts
const array = [1];
const iterator = array[Symbol.iterator]();
const value: string = iterator.next().value; // compile error
```

**Expected behavior:**

A type check error that number cannot be string.

**Actual behavior:**

No type check error.

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=4&pc=1#code/MYewdgzgLgBAhgJwXAnjAvDA2gRgLoDcAsAFCiSwCWUApslCAhvEqlgMooC2ARiADYA6anTgMEeABQBKYmXDQYANzj8ArjQBcMaAkpgA5sxH1GgsDQAeUGYJXqaBGAHpnMUFwAOlfjRh0ERlIgA

**Related Issues:**

I do not that Iterators/Generators were changed recently. IDK if that is related.

**Comment by AviVahl** [comment]
You'll get correct type error if you verify that `!result.done`:
```
const array = [1];
const iterator = array[Symbol.iterator]();
const res = iterator.next()
if (!res.done) {
    const num: string = res.value
}
```

**Comment by fatcerberus** [comment]
Cause of this is that `IterableIterator<number>` is an alias for `Iterator<number, any, undefined>` (thanks to the changes to iterator typings in 3.6) so without checking the value of `done` first, `value` is typed as `number | any`, which collapses to just `any`.

**Comment by AviVahl** [comment]
I wonder whether it would have been possible to use `unknown` as default for the iterator's `TReturn` type..? @rbuckton might be able to clarify.

**Comment by AviVahl** [comment]
Oh, see discussion at https://github.com/microsoft/TypeScript/issues/33353

**Comment by rbuckton** [comment]
This is essentially a duplicate of #33353.
