### ISSUE TITLE
GetCompletionItems needs to be profiled.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#3458]
On Vlad's machine we're seeing that GetCompletions is taking longer than we would expect inside checker.ts.  Often times being >100ms, and sometimes up to 250ms.  We need to profile this to see where our time is going, and to see if there is low hanging fruit we can attack to speed things up.

Ideally we'd see a breakdown that is something like:
20-40ms parsing
5-10ms binding
20ms on completion itself.

So, top amount should be 70ms at most.

I recommend that @DanielRosenwasser take a look at this as he has indicated an interest in learning to profile and working on LS/compiler perf.

**Comment by mhegazy** [comment]
Since you guys are looking into perf anyways. can you and @vladima take this one as well.

**Comment by basarat** [comment]
FWIW calling `getCompletionEntryDetails` drastically slows stuff down. Therefore I only call it on the first 10 items for atom-typescript.

**Comment by CyrusNajmabadi** [comment]
@BASArat  You should only call getCompletionEntryDetails for the item currently selected in your completion list.  When a user selects another item, you call again.

**Comment by basarat** [comment]
Yeah I expected that but still wanted to point out a bottleneck, reason being that the atom API doesn't currently allow lazy loading description (the `description` needs to be presented upfront https://github.com/atom/autocomplete-plus/wiki/Provider-API)

Again not a problem. This was just info :)

**Comment by mhegazy** [comment]
@vladima any more work needed here, or should we close this?

**Comment by vladima** [comment]
we are done here, it can be closed
