### ISSUE TITLE
TS 3.7: optional chaining not working in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#34593]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
optional chaining

**Code**

```ts
function arrayHasLength(): boolean {
	const someArray = [] as any[] | null;
	return someArray?.length > 0;
}
```

**Expected behavior:**
It compiles.

**Actual behavior:**
Error: `Object is possibly 'undefined'.(2532)`

**Comment by MartinJohns** [comment]
This works correctly. `someArray?.length` is possible `undefined`, and you can't greater-compare `undefined` with `0`.

You can fix this by writing `(someArray?.length ?? 0) > 0` (or similar).

**Comment by bpasero** [comment]
@MartinJohns I like your proposed workaround

**Comment by romeobalta** [comment]
> @MartinJohns I like your proposed workaround, though all in all it does not read as nice, but I see the issue now.

I think this way looks cleaner:

```ts
!!(someArray?.length)
```
