### ISSUE TITLE
Property Access: no ts(2339) error while accessing enum indexed object

### ISSUE THREAD

**Issue by falsyvalues** [microsoft/TypeScript#34592]
**TypeScript Version:**  3.6.3

**Search Terms:** bracket notation enum ts(2339) property access

**Code**
From [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#413-property-access) on  property access:
> The rules above mean that properties are strongly typed when accessed using bracket notation with the literal representation of their name.

So at least one of `NO ERROR` shouldn't happen.

```ts 
enum IPiece {
    Id = "id",
    FirstName = "firstname",
    LastName = "lastname",
    Age = "age"
}

interface IPiecePerson {
    [IPiece.Id]: string | null;
    [IPiece.FirstName]: string | null;
    [IPiece.LastName]: string | null;
    [IPiece.Age]: number | null;
}

const test: Pick<IPiecePerson, IPiece.Age> = { [IPiece.Age]: 100 };
// Expected: Property 'lastname' does not exist on type 'Pick<IPiecePerson, IPiece.Age>' ts(2339)
test.lastname
// Expected: Property 'lastname' does not exist on type 'Pick<IPiecePerson, IPiece.Age>' ts(2339)
// NO ERROR
test[IPiece.LastName]
// Expected: Property 'lastname' does not exist on type 'Pick<IPiecePerson, IPiece.Age>' ts(2339)
// NO ERROR
test["lastname"]
```

**Expected behavior:**
Error: Property 'lastname' does not exist on type 'Pick<IPiecePerson, IPiece.Age>' ts(2339)

**Actual behavior:**
Error: no error :-(

**Playground Link:** [noImplicitAny:false](http://www.typescriptlang.org/play/?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false#code/KYOwrgtgBAkgCgS2AY2FA3gKCj2ATKAXigCIE8SAabXAMQQCcBnAFwDkBDCNYkgM0asQXYFRo4AMh1aduRUgBtpLYdzG4oAQQDmPUh10lMAX0yYEIFsAZ8OqWIhTA41pgHsQGcVADa8JKgAdDB4ALoAXFCsDBbaUAA+UOAKCgDc3n6OQfTM7CIRUSwxIHGJyWkZ-k6BUjL5kdGxCUlgKekamQHAgTrABeAQAEbWzeXpppjIHqxQVqyRiMgA1gA8VaguzB6UDl09ugB88ui+6929BQCMAAzXUMbpAPSPUACiAB4ADihWeAsMbm+DBYAE8oAByJRCETgqB4NzAJhJNwsKDAd4IGYeWYg74QxarM6bdwgHZnfbAA6wlhMAAUACYAMyMgCcAEpMHMWIEoSoRJhnm8vj9gH8oHAAUDQRDeapgLD4Yjkaj0ZjUdjQXjwQS1llnK5trtqr0qbM6UzWRyuZ1qrU8txQgKXh9vshfv9AdZpZDlHKFQikSAUWiMVjPJq0NqEMtdV1iYbySbqebmezOYiWD4SLKRCRQkA) vs [noImplicitAny:true](http://www.typescriptlang.org/play/?strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false#code/KYOwrgtgBAkgCgS2AY2FA3gKCj2ATKAXigCIE8SAabXAMQQCcBnAFwDkBDCNYkgM0asQXYFRo4AMh1aduRUgBtpLYdzG4oAQQDmPUh10lMAX0yYEIFsAZ8OqWIhTA41pgHsQGcVADa8JKgAdDB4ALoAXFCsDBbaUAA+UOAKCgDc3n6OQfTM7CIRUSwxIHGJyWkZ-k6BUjL5kdGxCUlgKekamQHAgTrABeAQAEbWzeXpppjIHqxQVqyRiMgA1gA8VaguzB6UDl09ugB88ui+6929BQCMAAzXUMbpAPSPUACiAB4ADihWeAsMbm+DBYAE8oAByJRCETgqB4NzAJhJNwsKDAd4IGYeWYg74QxarM6bdwgHZnfbAA6wlhMAAUACYAMyMgCcAEpMHMWIEoSoRJhnm8vj9gH8oHAAUDQRDeapgLD4Yjkaj0ZjUdjQXjwQS1llnK5trtqr0qbM6UzWRyuZ1qrU8txQgKXh9vshfv9AdZpZDlHKFQikSAUWiMVjPJq0NqEMtdV1iYbySbqebmezOYiWD4SLKRCRQkA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
These errors are configurable via the `noImplicitAny` flag, as you noted. We recommend you turn that flag on if you desire those errors.

**Comment by falsyvalues** [comment]
Hi @RyanCavanaugh!

If [this (playground)](http://www.typescriptlang.org/play/?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false#code/KYOwrgtgBAkgCgS2AY2FA3gKCj2ATKAXigCIE8SAabXAMQQCcBnAFwDkBDCNYkgM0asQXYFRo4AMh1aduRUgBtpLYdzG4oAQQDmPUh10lMAX0yY+YEMhYIA9iCgtgrABQAHAFyxEKYAEoMM1NMJ1cyCj8AbiA) works without `noImplicitAny ` flag I guess this one also should if possible.
