### ISSUE TITLE
It's not possible to assign to string to T[keyof T] where T extends { [key: string]: string }

### ISSUE THREAD

**Issue by blixt** [microsoft/TypeScript#34591]
**TypeScript Version:**  3.7.0-dev.20191018

**Search Terms:** keyof string index record not assignable

**Code**

```ts
function test<T extends { [key: string]: string }>(map: T) {
    const key: keyof T = "hello"
    map[key] = "hi there"
}
```

(see playground for a more real example)

**Expected behavior:** Infer that the types accepted by the function will allow string key assignment (to string value). Since an interface with members incompatible with the string->string signature is invalid, anything that extends `Record<string, string>` should also have string keys with string values.

**Actual behavior:** An error such as:

* `Type 'string' is not assignable to type 'T[keyof T]'.`
* `Type 'string' cannot be used to index type 'T'.`
* `Type 'string' is not assignable to type 'T[Extract<keyof T, string>]'.`

The last one is if you attempt to do the assignment inside of a `for (const key in map)` loop. In this case especially, you'd think that even if there were somehow other properties with other types on the object (eg symbol or number indices), that it's narrowed down to just strings.

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.7-Beta#code/GYVwdgxgLglg9mABFApgZygHgCqJQD1TABM1EBvRAbQGsUBPALkQwCcYwBzAXWbY86IAvgD4AFAFsAhgAdm2AJQUAUIjWIICDIjr1EAXkQAiABYoANubhHV6gPR2NWqDobNdcYIlyHTFqzbqiA5OYNq6fFDsXAbGZpbWtmrSMrQM3LGmMMhmrCg2QsrKIQCCiBJweaEQeah4+FISMuYojEWgkLAI5VJ0AGpS5iDoAKoyMiisOPVEpIgASiiarMSY-FwANCxRAiLiAG6Dw2jyCvIqQZphLnloIOZQzAAKUqywgzgiseSFQcCViDEV3CDEQHEQhyG6CU5CSQUQt3uUDS9AyhkhxxR3AAdFA4GMJqwAMJSNAoMQKOG-eyOADKMGIKDAcFQzAAkogAO4wNAmMEuTmkxAyOBoNAwABGLWQcEQnBArykYFQKAR6CRYLImiaLTquFyKGxRrhtRArCQiIeiCF2GUhWUwJcIHGk1i0n6R1GLtYYkoYEarWMACE4BKjFsZKxPOhxQhmEYg6S6FAJYNzIgnuYpPRJkZhJSgA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/29295 was similar but possible to work around.

**Comment by AnyhowStep** [comment]
This is not an error.
`T = { hello : "bye" }`

Now, your assignment,
`map["hello"] = "hi there"`

Is unsound

**Comment by blixt** [comment]
Hm fair enough. I also tried type intersection (`T & { [key: string]: string }`) which produces the same error. What mechanism is there to accept a type that fulfills the string->string index and then return that same type?

My attempted approaches to the example in the sandbox:

```typescript
// Type 'string' is not assignable to type 'T[Extract<keyof T, string>]
function makeValuesUpper<T extends Record<string, string>>(values: T): T { }
// Type 'string' cannot be used to index type 'T & Record<string, string>'
function makeValuesUpper<T>(values: T & Record<string, string>): T { }
// Removes all type information from the passed in value.
function makeValuesUpper(values: Record<string, string>): typeof values { }
```

**Comment by AnyhowStep** [comment]
Your input `map` should be immutable.
```ts
function makeValuesUpper<T extends Record<string, string>>(values: T): Record<Extract<keyof T, string>, string> { }
```

**Comment by blixt** [comment]
Yes it appears this works:

```typescript
function upperValues<T extends Record<string, string>>(values: T): Record<Extract<keyof T, string>, string> {
    const result: Record<string, string> = {}
    for (const key in values) {
        result[key] = values[key].toUpperCase()
    }
    return result
}

const upper = upperValues({ name: "Bob", profession: "Basketball Player" })
```

The return type does change (`Record<"name" | "profession", string>`) and it seems eliding `Record<...>` here with `{ [K in ...]: string }` causes type errors again. Although I think there should probably be an error in the above code, but somehow that `Record<string, string>` sneaks through and passes for the correct type to return...

Anyway maybe this is too much of an edge case though I had hoped there'd be a more obvious way to do something similar to `[…].map(…)` on objects, given you could show at compile time the object only contains string values.

For additional context, the real world use case here is to augment configuration objects. Examples would be making a map of config keys to relative paths into absolute paths, expanding variables, or otherwise modifying the values in the object while returning the exact same structure.

**Comment by jack-williams** [comment]
There is no type-safe way to iterate over an object with a generic set of keys. String indexers are unsound in certain cases, which is why you don't see an error. I tend to write functions like this as:
```ts
function upperValues<K extends string>(values: Record<K, string>): Record<K, string> {
    const result: Partial<Record<K, string>> = {}
    for (const key in values) {
        result[key] = values[key].toUpperCase()
    }
    return result as Record<K, string>;
}
```
The last case can be reasonably justified as the previous loop should iterate over each `K`, so going from partial to defined should be safe.

**Comment by AnyhowStep** [comment]
Gotta be careful of own properties vs not-own properties and enumerable vs non-enumerable properties =x

The TS type system can't quite represent the difference between those (yet?).

So, gotta be careful how you use `in values` (with/without hasOwnProperty check, with/without propertyIsEnumerable checks)
