### ISSUE TITLE
Array.prototype.reduce return type incorrectly inferred as 'any' when Array has type `any[]`

### ISSUE THREAD

**Issue by vp2177** [microsoft/TypeScript#34602]
**TypeScript Version:**  3.6.3

**Search Terms:** Array reduce type inferred bad|incorrect|any

**Code**

```ts
const s: Array<any> = []
const x = s.reduce((a, c) => a + '*', '')
```

**Expected behavior:** `x` should be inferred to be of type `string`

**Actual behavior:** `x` is inferred to be `any`

However, `x` is is correctly inferred to be type `string`, if using `[].reduce(...` as opposed to `s.reduce(...`.

Compare:
![Screenshot 2019-10-20 at 04 54 38](https://user-images.githubusercontent.com/451903/67154603-3580fb00-f2f7-11e9-80da-0b8a4e570c0c.png)
with
![Screenshot 2019-10-20 at 04 54 03](https://user-images.githubusercontent.com/451903/67154613-56495080-f2f7-11e9-9cb4-290ac369efdf.png)

Inferring `x`'s type even if `s` is polymorphic is possible and works in other languages:
![Screenshot 2019-10-20 at 04 52 38](https://user-images.githubusercontent.com/451903/67154620-809b0e00-f2f7-11e9-8bdb-ba4934657a4e.png)

**Playground Link:** 

**Related Issues:** 
#21061

**Comment by jcalz** [comment]
The [overloads of `reduce()`](https://github.com/microsoft/TypeScript/blob/v3.6.3/lib/lib.es5.d.ts#L1173-L1180) are in a suboptimal order when the array type is very wide like `any` or `unknown`, if the initial value is assignable to it.  If the generic call signature were moved to the front, this issue would not arise:

```ts
interface Array<T> {
  reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U
  reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T): T;
  reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T, initialValue: T): T;
}

const s: Array<unknown> = []
const x = s.reduce((a, c) => a + '*', ''); // string
```
[Playground link](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgIJSnAngHgCoB8yA3gFDIXJQQAmArkjgKoEAUCcANpwEaIDWMEAC5krAA7UAbsAD2dAM4A1LnQiimAGmQI6GCOBWc1ovNt37wASRA0IAD1Eg6AWx7RtcDNlMBtALoAlMgAvERayKDAYMBcRibITIEa5JTU9EjsXLwCQqIS0nKK8erIZjp61IaqpeUWVWA2do7Izm4eyF6YWH5BoUR4yWUA3KkU6QwQWdx8CIIiYpIQMvLKNabmlQZgJRsVlo22Dk6u7lCe3j1lAcFhZdpRMXHrZUN4owC+pAiyIApgyAUonQ3RwdBA-BAsgA7iAiCFkAFvr9-sh7KFAQA6CaZVhwcy3IhwZAAamQAHIAFTk7Tk8mBYbIAD0TMBYCgoAA5kA)

I'm not sure if this rises to the level of "bug"; in any case, you could always locally merge in the above declarations in your code base to resolve it (actually you only need the generic one).

**Comment by vp2177** [comment]
Thank you! 
Then I think this is a duplicate of #7014.
