### ISSUE TITLE
Proposal: support #line directive so we can use other tools and have sane line numbers for errors & outputs.

### ISSUE THREAD

**Issue by graph** [microsoft/TypeScript#34608]
## Search Terms

`#line` preprocessing directive

## Suggestion

the c++ preprocessor adds [#line directives](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-line-directive-c-cpp?view=vs-2019) and some other preprocessing tools do similar as well. And it's a good way to have multiple preprecossors act on a single file in a pipeline.

This proposal is just only supporting the '#line` directive so that other tools can do the job of preprocessing. Other existing issues such as [Preprocessor directives proposal](https://github.com/Microsoft/TypeScript/issues/4691) propose more kinds of directives and a more complete set of directives.

Additionally this proposal would support the [preprocessor output](https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html) of clang/gcc for line changes in the form of

`# 1 "some/path/file.ts 1`

which is very similar to #line directive.

## Use Cases

I want to run c preprocessor on my typescript file and feed it directly to tsc. By supporting this directive typescript will be able to give proper line numbers and generate a more sensible source mappings.

## Examples

```
#line 33 "../../../somedir/myfile.ts"
code.logic = 7;
```
Now for error reporting and generation of source maps I expect it to map to respective file and line number.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment]
https://github.com/microsoft/TypeScript/issues/13944 seems like a more sensible solution; it allows the same result as `#line`, it doesn't require intrusive syntax changes in source files, and is already supported by many parts of the js ecosystem.

**Comment by RyanCavanaugh** [comment]
Agree with @nmain - source maps are the standard for JS tooling so #13944 would be the preferred solution in this space.
