### ISSUE TITLE
isNaN is restricted to number as arguments only

### ISSUE THREAD

**Issue by bpazo** [microsoft/TypeScript#34609]
**TypeScript Version:**  3.3.3333

**Search Terms:**  isNaN

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

let someUnionType:string|number = "42";
if(isNaN(someUnionType)){
  // ..do something here if true
}else{
  // ..do something else if false
}
```

**Expected behavior:**
I expect `isNaN` to test a value to determine if it is `NaN` or not `NaN`, and return a boolean value accordingly.

I don't feel as though I should have to convert the union value to a number first and then test the result of that value, since `isNaN` will do the same without the added step. Converting a value to `NaN` or `number` using `Number(x)` then requires passing the result to `isNaN(Number(x))` to get a `true` or `false` result.

According to some examples found at [isNaN() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Examples), isNaN seems to handle such tests appropriately without first converting to number first.

Also, the polyfill for `isNaN` is:

credit: [MDN isNaN polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Confusing_special-case_behavior)
```
var isNaN = function(value) {
    var n = Number(value);
    return n !== n;
};
```
Since `Number` is permitted to take a value of type `any`, then it would seems as though `isNaN` should be permitted to do the same since it is basically just a different way to use `Number`. Also, I feel like it just breaks how `isNaN` was intended to be used. See this - ["Confusing_special-case_behavior"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Confusing_special-case_behavior) for more details.

One last note, please see [Useful special-case behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Useful_special-case_behavior) for one final reason why `isNaN` should accept the same type parameters as `Number`.

**Actual behavior:**
Typescript errors out at before test if argument isn't of type number.
```TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.```

**Playground Link:**  
[Playground Link](http://www.typescriptlang.org/play/index.html#code/DYUwLgBAzg9gtiAqgOwNbJgd2QFQJ4AOIAXFGAE4CWyA5gD7ICucARiORALwQBEALACYeAbgBQlAGYAKSlAByAQzlTYCFOiy5CIAJQ6A3qIgQA9CYgA6CwBMY0eOAAW1GhEfsQogL4hgUEIbGZpY2dqpOLhC+-t5AA)
**Related Issues:**

**Comment by bpazo** [comment]
Just realized there is a newer version of TypeScript v.3.6.3
Still get the same results. Here is a [playground](http://www.typescriptlang.org/play/index.html?ssl=6&ssc=2&pln=1&pc=1#code/DYUwLgBArgdglgexgLggZzAJzjA5hAHwhigFsAjETCAXggCIAWAJnoG4BYAKDgDMIAFHDQA5AIYiBsRDACUsiAG9uEVRAD06iABME6BKXAALHLm4BfCCGBoQSlWs069aA8dNWbIC0A) link

**Comment by AnyhowStep** [comment]
The problem you're encountering is essentially,
> Just because a function can accept an argument of type `T`, should we allow it during compile-time?

**Comment by bpazo** [comment]
@AnyhowStep 

Please see this quote from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Useful_special-case_behavior)
> Actually, isNaN(x), isNaN(x - 0), isNaN(Number(x)), Number.isNaN(x - 0), and Number.isNaN(Number(x)) always return the same and in JavaScript isNaN(x) is just the shortest possible form to express each of these terms.


Restricting `isNaN` isn't doing anything different than using `isNaN(Number(x))`. Code smell or not, the former is just a shorter way to do the same thing.

**Comment by trotyl** [comment]
+ https://github.com/microsoft/TypeScript/pull/3947
+ https://github.com/microsoft/TypeScript/issues/4002
+ https://github.com/microsoft/TypeScript/pull/11414
+ https://github.com/microsoft/TypeScript/issues/12302
+ https://github.com/microsoft/TypeScript/issues/13227
+ https://github.com/microsoft/TypeScript/issues/15173
+ https://github.com/microsoft/TypeScript/issues/16427
+ https://github.com/microsoft/TypeScript/issues/19153
+ https://github.com/microsoft/TypeScript/issues/21065
+ https://github.com/microsoft/TypeScript/issues/23464
+ https://github.com/microsoft/TypeScript/pull/29607

Please do respect the "**Search Terms**: isNaN" you wrote.

**Comment by AnyhowStep** [comment]
```ts
declare function isNaN(x: string | number): boolean;

let someUnknownType: string | number = "42";
if(isNaN(someUnknownType)){ //OK
  // ..do something here
}else{
  // ..do something else
}
```
[Playground](http://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=8&pc=2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXywGcA5KYgCgA8AueQjGLVAc3gB95VkBbAIxBgBKWrxw4IIKKgDcAKFkSMdHNxABVVAGtUOAO6oAKgE8ADiFr1GLdpx78Y8ALzwARABYATC7lZE5IqQUhCrqWjr6xmaCggDesvDwAPSJ8AB0qcA4yqoYABZMrLkCILIAviAQhCBxCclpGVnBOfnWFVVlQA)

**Comment by bpazo** [comment]
@trotyl 
My apologies. I did try to search for isNaN before posting, but after viewing your comment I tried again and now realize that there is a default filter set in the search input. Not a good excuse, but this is my first issue report that I've made for anything on github. Lesson learned.

I've read through all the various thoughts on the matter now. It seems that this issue is one that is debatable by many at best and will most likely never appease everyone. So, I'll make a work around to suit my needs. Thanks for the feedback.

**Comment by jcalz** [comment]
Yeah, it took me a while before I figured out (probably was told by @RyanCavanaugh now that I think about it) that there is a good and a bad way to search for issues.  The general search bar at the top returns many more relevant results than the issue-specific search in the page itself, for whatever reason.  

![searches](https://user-images.githubusercontent.com/150626/67231006-7454a500-f40c-11e9-864e-c5c9990cddb1.PNG)

**Comment by RyanCavanaugh** [comment]
What's worse is that you want the 'bad' box if you're searching for Closed issues, since the ordering from the 'good' box strongly deprioritizes closed issues.
