### ISSUE TITLE
Unification of functions on union types

### ISSUE THREAD

**Issue by pauldraper** [microsoft/TypeScript#34605]
**TypeScript Version:**  3.6.3

**Search Terms:**

Union type functions

**Code**

```ts
type A = number[] | string[];
const a = <A>[1];
a.forEach(element => console.log(element)); // error
```

**Expected behavior:**

No compile error. (`element` is inferred to be `number | string`)

**Actual behavior:**

Compile error. (`Parameter 'element' implicity has 'any' type.`)

**Playground Link:**

http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=4&pc=1#code/C4TwDgpgBAglC8UB2BXAtgIwgJwNoF0oAfKAZ2GwEskBzAgbgCgBjAeyXKgEMEoAeGAD5cARnxMuAOgBmrbAFEuzABYAKCABsIaCEmAJBUNh1ZbJG1jXVadegJR36UAPTOoObHMZA

**Related Issues:**

---

I'm unsure whether or not it is realistic to improve this. Recently I have been working with a number of `A[] | B[]` types and noticed that most array operations cannot be done on these.

**Comment by jack-williams** [comment]
I believe there is a PR that would address this here #17819, but it's closed from inactivity. The PR links to related issues.

I think the root issue is contextual typing for overloaded / intersected function signatures, rather than union types. Simplified repos:
```ts
const x: ((x: number) => void) & ((x: string) => void) =
    x => console.log(x); // error on x;


interface Foo {
    (x: string): void;
    (x: number): void;
}    

const y: Foo = x => console.log(x); // error on x;
```

**Comment by RyanCavanaugh** [comment]
See #7294 and its related issues
