### ISSUE TITLE
Type inference fails with tuples that may be undefined

### ISSUE THREAD

**Issue by ianstormtaylor** [microsoft/TypeScript#34618]
**TypeScript Version:**  3.7-Beta

**Search Terms:** Tuple, inference, undefined, never, maybe, elements

**Code**

```ts
const getAlways = (): [number, string[]] => {
    return [1, ['a']]
}

const getMaybe = (): [number, string[]] | undefined => {
    if (Math.round(Math.random())) {
        return [1, ['a']]
    } else {
        return undefined
    }
}

const always = getAlways()
const [a1, a2] = always

const maybe = getMaybe()
const [m1, m2] = maybe
```

**Expected behavior:** 

Currently, the `[m1, m2]` line correctly is marked as an error, because `maybe` could be `undefined` and not iterable, and the help text explains that. That's good.

However, if you hover over either `m1` or `m2` they both show their type as `number | string[]` which doesn't seem right. This makes solving the error confusing if you read that inferred type value first—at least I wasted a bunch of time thinking that the return type from my function was somehow wrong before reading the help text again.

**Actual behavior:** 

It seems like they should resolve to `m1: never | number`? and `m2: never | string[]`? Although I'm not an expert on `never`, so maybe something else, but not `number | string[]`?

**Playground Link:** [Link](http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=18&pc=1#code/MYewdgzgLgBA5gUygQQDYHcCGBPCMC8MAFAJQBcMA2mAK4C2ARggE4A0M0zAlmHJQLr8CAPhgBvAFAxpMZkhrMwVAIztKAckzrBEgL4SJoSLERQAsjiYFi5KrUYt2nHn0EwAPjBpgAJggBmPAg+IuJSMlz+xBZQABYAdMwg3j5EMQnMmL4gdKQkJGEyRbLyiipqmtr84dK6MAioEAiFxdJyUApKKQFBPjUw+vqG4NAwmBg4eISmaFi4pMPGVJiqYwBMQoTjcxAGRqN0ls3TSBbYTAv7sJR0q3Qb1ofnCBJAA)

**Comment by RyanCavanaugh** [comment]
`never` is the identity operand of the union operation, so `never | number` is a different spelling of `number` the same way `42 + 0` is the same value as `42`.

In general if you have an error the resulting type display is only going to be a best-guess effort; in this case TS fell back to the indexer of the type, which is not wrong (simply more broad than desired).

**Comment by ianstormtaylor** [comment]
@RyanCavanaugh sounds good, thank you! Makes sense about best-guess and `never` use.
