### ISSUE TITLE
Reflect.ownKeys has overly wide type definition

### ISSUE THREAD

**Issue by jdalton** [microsoft/TypeScript#34626]
Reflect.ownKeys has a return type definition of `PropertyKey[]` which is defined as
`declare type PropertyKey = string | number | symbol;` but the method of `ownKeys` only returns `(string | symbol)[]`.

**Comment by fatcerberus** [comment]
To be fair, the type is not *invalid*, it’s just overly wide. The set is all strings is contained within the set of all strings and numbers, after all.

Of course this is splitting hairs, but since you put “invalid” in the issue title I had to point it out :wink:

**Comment by 00ff0000red** [comment]
A moderate part of the built-in types defines indexable types as `string | number | symbol`, when this doesn't exist in reality at all.

In actual runtime ECMAScript, numbers aren't properties of anything.

Examples:

    JavaScript:
    Arrays are often indexed by number, with the knowledge that the number is being implicitly cast to a string.

    TypeScript:
     Arrays **must** be indexed via number. This is great for safety and all; the chances that the string "fsfh654ewvbhy5" is a property of your array are less than that of the number 35 when cast to a string, but the properties aren't actually stored as numbers.

Note, this effects more than just `Reflect.ownKeys`. For example, all `ProxyHandler` functions that take an index value get `string | number | symbol`, when they should be `string | symbol`.

**Comment by ExE-Boss** [comment]
I’m fixing this in <https://github.com/microsoft/TypeScript/pull/41987>.
