### ISSUE TITLE
module name mismatch in declaration

### ISSUE THREAD

**Issue by andyfleming** [microsoft/TypeScript#34624]
**TypeScript Version:**  3.7.0-dev.20191021

**Search Terms:**
- declaration
- modules

**Code**

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro

**Expected behavior:**

A valid `index.d.ts` file should be emitted.

**Actual behavior:**

The module is declared as `"versions.static"` on line 1, but is imported below as `"versions.static.js"` on line 10 (and not found).

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/blob/master/js/index.d.ts#L1

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/blob/master/js/index.d.ts#L10

**Steps to reproduce**

1. Clone https://github.com/andyfleming/typescript-module-declaration-mismatch-repro
2. Run `npm install`
3. Run `npm run generate-types`
4. Observe declared `"versions.static"` module and import attempt as `"versions.static.js"`.

## Code from Repo

**package.json**

```json
{
  "name": "@example-org/example-package",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "generate-types": "rm js/index.d.ts && tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/andyfleming/typescript-module-declaration-mismatch-repro.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/issues"
  },
  "homepage": "https://github.com/andyfleming/typescript-module-declaration-mismatch-repro#readme",
  "devDependencies": {
    "typescript": "3.7.0-dev.20191021"
  }
}
```

**tsconfig.json**

```js
/* Generated with tsc --init via TypeScript 3.7.0-beta */
{
  "compilerOptions": {
    "module": "commonjs",
    "allowJs": true,
    "declaration": true,
    "outFile": "./js/index.js",
    "emitDeclarationOnly": true,
    "strict": true,
    "esModuleInterop": true
  },
  "include": [
    "js/**/*"
  ]
}
```

**js/index.js**

```javascript
import versions from './versions.static.js';

export {
    versions
};
```

**js/versions.static.js**

```javascript
export default {
    "@a/b": "1.0.0",
    "@a/c": "1.2.3"
};
```

**js/index.d.ts** (sample output)

```typescript
declare module "versions.static" {    // <-- declared one way here
    var _default: {
        "@a/b": string;
        "@a/c": string;
    };
    export default _default;
}
declare module "index" {
    export { versions };
    import versions from "versions.static.js";   // <-- and different way here
}
```

**Comment by RyanCavanaugh** [comment]
Can you put a summary of what's in the repo in the bug body? "Just go clone this repo" is going to make anyone else unable to find this issue through a search

**Comment by andyfleming** [comment]
No problem. I went ahead and copied code into the original comment/issue. 👍

**Comment by RyanCavanaugh** [comment]
Very much appreciated, thanks!

**Comment by elibarzilay** [comment]
Setting `outFile` means that TS is trying to produce a dts file that
there is no legal way to represent, so perhaps it's better to make it an
error if you set an `outFile` that causes emitting relative path names.

**Comment by weswigham** [comment]
Naaaaah, we just need to sync up the specifiers we generate when `outFile` is set. When `moduleResolution: node` is set we have a bunch of extra specifier rules that _probably_ need to be disabled when generating the specifiers in the declaration file. (Since, eg, we support eliding extensions on disk, but not eliding "extensions" in ambient modules)
