### ISSUE TITLE
Declared module name does not match name in package.json

### ISSUE THREAD

**Issue by andyfleming** [microsoft/TypeScript#34623]
**TypeScript Version:**  3.7.0-dev.20191021

**Search Terms:**
- package.json
- export
- modules
- index
- package name
- definition

**Code**

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro

**Expected behavior:**

A module `@example-org/example-package` should be declared matching the name in `package.json`.

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/blob/master/package.json#L2

**Actual behavior:**

The module is declared as `index`.

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/blob/master/js/index.d.ts#L8

**Steps to reproduce**

1. Clone https://github.com/andyfleming/typescript-module-declaration-mismatch-repro
2. Run `npm install`
3. Run `npm run generate-types`
4. Observe declared `"index"` module

**Comment by orta** [comment]
This relates to `allowJs` `outfile`  and `declaration` in the tsconfig. In this setup the `d.ts` for the package declares a module of "index" rather than looking back into the `package.json` for find the right name. Auto import for `versions` gives this:

```ts
import { versions } from "index";

versions
```

Turning off `outfile` generates a d.ts setup which works as expected.

**Comment by andyfleming** [comment]
Ah, yeah, removing `outFile` exports them properly.

You're right that bundling is part of what I'm looking for. I'm going to add a comment related to the `package.json` name matching feature in that thread.

I'll go ahead and close this one since it's basically covered over there.
