### ISSUE TITLE
Auto imports incorrectly add file extension when a json file is also imported

### ISSUE THREAD

**Issue by donovanhiland** [microsoft/TypeScript#34620]
*TS Issue template added by @mjbvz*

**TypeScript Version**: 3.7.0-dev.20191021    

**Search terms**:
- Auto import
- json 

*Original issue below*

---

Auto import paths are wrong after having a json file imported

- VSCode Version: 1.40.0-insider
- OS Version: 10.14.5

Steps to Reproduce:

1. Import a json file
2. Try to import anything else

Here's a repro repo: https://github.com/donovanhiland/json-module-auto-import-issue.git

Trying to auto import the variable in `test.ts` demonstrates the issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@donovanhiland The bug is that it add `.js` to the import, correct?

![Screen Shot 2019-10-21 at 1 52 14 PM](https://user-images.githubusercontent.com/12821956/67242264-07401000-f40a-11e9-9309-0a6dd8e38eb9.png)

**Comment by donovanhiland** [comment]
Yes that's correct
