### ISSUE TITLE
ReturnType support for assertions

### ISSUE THREAD

**Issue by sirian** [microsoft/TypeScript#34636]
## Suggestion

Not found a way to provide return type for assert function. Look at use case 

## Use Cases

```typescript
function assert1(e: any, m?: string): asserts e {
    if (!e) throw new Error();
    return e;
}
function assert2<T>(e: T, m?: string): asserts e {
    if (!e) throw new Error();
    return e; // error:  T is not assignable to void
}

declare const p: Promise<string | undefined>;
p.then(assert1).then((x) => x.length); // error: x is string | undefined
p.then(assert2).then((x) => x.length
); // error: x is string | undefined

```

This doesn't work also
```typescript
const assertAndReturn = <T>(x: T) => { 
    assert(x);
    return x;
}
p.then((x) => { assert(x); return x; }).then((x) => x.length) // ok
p.then(assertAndReturn).then((x) => x.length); // error. x is string | undefined
```

[Playground](https://www.typescriptlang.org/play/index.html?ts=3.7-Beta&ssl=12&ssc=1&pln=12&pc=73#code/GYVwdgxgLglg9mABAQwM6oKYCcoEYAUGAXCmAJ4A0iAtgPwmpRYxgDmAlCWpjqohogDeAKERjEMYInwBCDO0RQAFljgB3RGAwaAollVZ87ANyjxWDFBBYkGUwF9hoSLAQp02KACYAPABUAPkISPyo6BiYWDi4PXn4hMzFJaTkFZVUNLV19OEMTRMQLKxt+Y0QAenL+HKwSRD8JPjA4KHdUGFYwZAAjABsBKDhEADc4GAATYUdhcYwIXuQLRAgERkQABxIABVVqGEwfRmY2RAAfRHBZ4BYMcYDTdYA6ZQwwfG5PXHZnpVf8fAAHgoALwBRAAx79NjKEwVKrYAwkAGNRBHKJnC5gK43SZPF5vD44LzffH-IGIUHgyGvVgwsqVaqI8EotEnc6XDDXLTjIA)

## Related issues
https://github.com/microsoft/TypeScript/issues/34596

**Comment by dragomirtitian** [comment]
This is by design, according to the [PR](https://github.com/microsoft/TypeScript/pull/32695) introducing this features:

> A function call is analyzed as an assertion call or never-returning call when
>1. **the call occurs as a top-level expression** statement, and
>2. the call specifies a single identifier or a dotted sequence of identifiers for the function name, and
>3. each identifier in the function name references an entity with an explicit type, and
>4. the function name resolves to a function type with an asserts return type or an explicit never return type annotation.

The first item states that the call must occur as a top-level statement, this means that  the call can't be nested in an expression (such as a parameter to another function  or in an assignment). This means that effectively, even if you could return from an assertion function, using it in a position where the return value could be use, the function would not be analyzed as an assertion but rather as a regular function call. So it is best to implicitly just say that an assertion function returns `void`. This is also outlined in the PR:

> An asserts return type predicate implies that the returned value is of type void, and there is no provision for returning values of other types.

Your first example (`assert1`) allows a return because of a quirk in assignability rules, since `e` is `any` it is also assignable to `void`. Change to `unknown` and you will get an error.

**Suggestion**: @ahejlsberg  Maybe disallow any return statement that has an expression in assertion functions?

**Comment by nmain** [comment]
The real world use case outlined here is handled fine by typescript if, instead of `then` chains, you make an async function:

```ts
async function f() {
    const val = await p;
    assert1(val);
    val.length; // number
}
```

**Comment by sirian** [comment]
@nmain There are many other use cases. Especially in arrow functions

```typescript
const bar = () => assert(someTask());
// instead of
const bar = () => {
     const result = someTask();
     assert(result);
     return result;
}
```

**Comment by nmain** [comment]
You can do that easily without getting involved with the assert feature at all:

```ts
function assert<T>(v: T): NonNullable<T> {
    if (v == null) {
        throw null;
    }
    return v as any;
}

declare function someTask(): string | undefined;

const bar = () => assert(someTask()); // () => string, instead of () => string | undefined
```

I certainly see the draw of being able to use the same `assert` function in both ways, though, with some sort of type annotation that encompasses both the asserting and the returning a subset of the values idea.

**Comment by sirian** [comment]
@nmain I know. But this increase entropy - i should have two assert functions with same code;

```typescript
function assert(value: any): asserts value {
    if (!value) {
        throw new Error("Assertion failed.")
    }

function assertAndReturn<T>(value: T): value is Exclude<T, null | undefined | void | 0 | false | ''> {
    if (!value) {
        throw new Error("Assertion failed.")
    }
    return value;
}
```

It's silly IMO. And as i said before - why not to add narrowing at least?

```
const assertAndReturn = <T>(x: T) => { 
    assert(x);
    return x;
}
p.then((x) => { assert(x); return x; }).then((x) => x.length) // Works fine 
p.then(assertAndReturn).then((x) => x.length); // Doesn't narrow
```

**Comment by mprobst** [comment]
As a data point, both returning a value and narrowing the type of the input is also how Closure's `goog.asserts.assert()` & Co work.

**Comment by eyedean** [comment]
I also tried to get around this by having two assert functions, one to `assert` and one to return, and have the latter call the former.  e.g. 

```ts
function _assert<T = any>(x: T): asserts x { // say, private one
    if (!x) { throw new Error(); }
}

function myAssert<T = any>(x: T): T { // say, public one that returns
    _assert(x);
    return x;
}

type Employee = { name: string; }

function getEmployee(id: number): Employee | null {
    if (id !== 2) {
        return null;
    }
    return { name: "James" };
}

const emp = getEmployee(3);

console.log(myAssert(emp).name); // Object is possibly null :(

// Pure check:
// _assert(emp); // without this line, I get "Object possibly null" in the console.log
// console.log(emp.name);
```

But unfortunately, while `myAssert` is calling `_assert(x)` on its own, typescript doesn't **infer** that an `assert x` is performed. :(

**Comment by LinusU** [comment]
I ran into to trying to do this today, my use case is this:

```typescript
interface Provider {
  initiatePayment (items: Items): Promise<string>
}

function getProvider (id: string): asserts id is ('foo' | 'bar') & Provider {
  switch (id) {
    case 'foo': return fooProvider
    case 'bar': return barProvider
    default: throw new Error(`Unknown payment provider: ${id}`)
  }
}

function makePurchase (provider: string, items: Items) {
  const providerImpl = getProvider(provider)

  const paymentId = await providerImpl.initiatePayment(items)

  savePurchase({
    provider,      // <---- Provider needs to be typed as 'foo' | 'bar' here!
    paymentId,
    items
  })
}
```

**Comment by RReverser** [comment]
Another datapoint: combining `asserts` with an actual return type would allow to improve typings for in-place `Object.assign`. See https://twitter.com/RReverser/status/1350524568075710464.

**Comment by 00ff0000red** [comment]
I would really love to see this happen, and for the restriction
> 1. the call occurs as a top-level expression statement

to be made obsolete.
I have a function in plain, simple JavaScript that does both, asserts something, and returns a boolean.
The natural use is to use it in an if statement or ternary condition, but TS can't give it a correct signature.

**Comment by RReverser** [comment]
@RyanCavanaugh Just checking - was this closed because it's implemented now or because it's not considered or?

**Comment by ttencate** [comment]
@RReverser Presumably because #40562 is a duplicate of this one.

**Comment by RReverser** [comment]
Hmm 1) it wasn't linked during closing and 2) it's a newer issue, so I'd expect the newer one would be closed as a duplicate...

**Comment by nightlyherb** [comment]
FWIW the specific `assertAndReturn` use-case seems to work as of TypeScript 4.8.2.
https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAeAFQD4AKADwC55KBKZoksw+e+LHpXgAyeIQwwsqAOYBuALAAoMHnEFipDAEFUwAEogMyGPgC88KgBo6TFq3inq8AN5L46rhgasFi93CMTXl8AXyUlUEhYBBVUNQAHZgAFGBwAWwEQcnFJGXgAH3g0UEQpEGBqX3iAOgwACxBUWk5NHX1DY1RWWoam7wcnemqIRul6nyUgA

This doesn't cover all use-cases though.

**Comment by benwainwright** [comment]
@nightlyherb no it doesn't; that function you've written isn't returning an assertion, it's just returning a value. It's not a type guard.

Here is my use case for this

```
type AssertionType = { toBeUndefined: () => void }

const expect: <T>(bar: T | undefined) => asserts bar is T & AssertionType = (bar) => {
  return {
    toBeUndefined: () => {},
  };
};

expect(foo).toBeUndefined()
```

If this feature were implemented in TS, I'd probably submit a contribution to the jest codebase to make certain matchers type guards.

**Comment by ExE-Boss** [comment]
@benwainwright
> Here is my use case for this
> 
> ```
> type AssertionType = { toBeUndefined: () => void }
> 
> const expect: <T>(bar: T | undefined) => asserts bar is T & AssertionType = (bar) => {
>   return {
>     toBeUndefined: () => {},
>   };
> };
> 
> // Currently there is an error here
> expect(foo).toBeUndefined()
> ```
> 
> If this feature were implemented in TS, I'd probably submit a contribution to the jest codebase to make certain matchers type guards.

That’s because your code is equivalent to:
```ts
type AssertionType = { toBeUndefined: () => void }

const expect: <T>(bar: T | undefined) => asserts bar is (T & AssertionType) = (bar) => {
	return {
		toBeUndefined: () => {},
	};
};

// Currently there is an error here
expect(foo).toBeUndefined();
```

What you want, and is currently impossible:
```ts
type AssertionType = { toBeUndefined: () => void }

// The error is now here:
const expect: <T>(bar: T | undefined) => (asserts bar is T) & AssertionType = (bar) => {
	return {
		toBeUndefined: () => {},
	};
};

expect(foo).toBeUndefined();
```
