### ISSUE TITLE
Overloaded method may not call overloaded method with the same signature (TS2769)

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#34632]
**TypeScript Version:**  3.7.0-Beta

**Search Terms:** overload, signature, identical

I have two methods with identical signatures. In real-world code, the `foo` does some checks, then calls `fooInternal` with the same argument it received. Library-internal code may call `fooInternal` directly. Both methods have the same signature and overloads, but TS complains about the call to `fooInternal` if the latter has overload signatures.

**Code**
```ts
function foo(arg: number): any;
function foo(arg: string): any;
function foo(arg: number | string): any {
    return fooInternal(arg); // ERROR: No overload call matches ... (ts2769)
}

function fooInternal(arg: number): any;
function fooInternal(arg: string): any;
function fooInternal(arg: number | string): any {
    return undefined as any;
}


function bar(arg: number): any;
function bar(arg: string): any;
function bar(arg: number | string): any {
    return barInternal(arg); // WORKS
}

// function barInternal(arg: number): any;
// function barInternal(arg: string): any;
function barInternal(arg: number | string): any {
    return undefined as any;
}
```

**Expected behavior:**
No errors

**Actual behavior:**
Errors on the call of the overloaded method

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=24&pc=2#code/GYVwdgxgLglg9mABMOcAUBDATgcwFyJggC2ARgKZYCUBGYAngNwCwAUKJLAsqprgQGcoWGGBw1EdJmw7R4SFOmz5CJClkQAfREJFiJUxAG82iM4izkoILAtQBJMFEpgMAGz7iWrAL5sZ4HLcio7Otu6eBERklAYM3rJcdnChLhHKgsKi4rTxAZzyPClOaR4ZqjEa2rrZcfTGpuaW1raI4AAm5MCi5O2SApJ5vv6s+UFIpNiRFep1CYFJiJNY0zX6udLsC4XL09HqWjpZ64P1JqzmFlY2E9ip4WW4VN5+o6wA9O-I29zL966PFT7WIbbyfb4FX53EoPVbHHKneaQ25Yf7pfgzSiHNYIwznS7NG5tMCdbpgXr9RFsHxAA

**Related Issues:**

**Comment by fatcerberus** [comment]
This happens because, in a set of overloads, the implementation signature is not considered at all when resolving overloads.  It's far from ideal, but this makes it work:
```ts
function foo(arg: number): any;
function foo(arg: string): any;
function foo(arg: number | string): any {
    return typeof arg === 'number'
        ? fooInternal(arg)   // matches numeric overload
        : fooInternal(arg);  // matches string overload
}
```

TS doesn't decompose the union to realize each possibility matches a separate overload individually, it just sees there's no *single* overload that accepts a `number | string` and gives up.  It would definitely be nice if this worked!

**Comment by AlCalzone** [comment]
> TS doesn't decompose the union to realize each possibility matches a separate overload individually

I wonder if that would be necessary (it would be on the safer side for sure) or if it was enough to just compare the implementation signatures. After all, TS already makes sure that that signature matches the single overload signatures.

**Comment by RyanCavanaugh** [comment]
See #1805, #14107, etc.

**Comment by AlCalzone** [comment]
Thanks, this was the key information:
https://github.com/microsoft/TypeScript/issues/1805#issuecomment-179661863
> you should never write a series of overloads which have an equivalent representation in union types.

Apparently the methods work just fine without the overloads. Not sure why I felt that I need them - maybe for JSDoc documentation purposes
