### ISSUE TITLE
Automatic breakpoint and logpoint for 'On Enter Function' in debug

### ISSUE THREAD

**Issue by rubengmurray** [microsoft/TypeScript#34637]
## Search Terms

debug every function breakpoint dynamic logpoint log

## Suggestion

I'd really like to be able to get `debug` to dynamically break and / or log on every function that is called by a particular function, nested through the whole chain until the parent function returns. 

At the moment it seems this behaviour is limited to breaking on a function only when the function name is known, and even then only for breakpoints, not logpoints.

The other alternative is to go through the various places that function may call, and manually add break points at each stage.

## Use Cases

I want to trace and log out the state at every function call along with the function name & location, rather than going through multiple files and manually marking each function.

This would also allow me to map a particular functions path across the code-base for generally faster debugging.

## Notes

I believe this functionality already exists in other version of Visual Studio such as VS for Mac as referenced in this comment: https://github.com/microsoft/vscode-node-debug2/issues/163#issuecomment-365570247?

**Comment by RyanCavanaugh** [comment]
Was this issue logged in the wrong repo? How does this relate to TypeScript?

**Comment by rubengmurray** [comment]
Damn. Yes it was. Explains why I couldn't find anything on the subject. Meant for VS Code... I'll see myself out.
