### ISSUE TITLE
Wrong variant rule on JSX property when the property is a function.

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#34633]
**TypeScript Version:**  3.7-beta

**Search Terms:** JSX function covariant invariant

**Code**

`strictFunctionTypes` is on

```ts
class A { a = 1 }
class B { b = 2 }
function Test(props: { onChange(data: A | B): void }) {
    setTimeout(() => {
        props.onChange(new B())
    }, 1000)
    return null
}
// There is no error!
const data = <Test onChange={(data: A) => {
    data.a.toFixed // Runtime Error!
}} />

let x: (data: A | B) => void
x = (data: A) => {}
// Types of parameters 'data' and 'data' are incompatible.
// This is correct
```

**Expected behavior:**

Throw `Types of parameters 'data' and 'data' are incompatible.` on the JSX's `onChange` property.

**Actual behavior:**

No error.

**Playground Link:** https://www.typescriptlang.org/play/?jsx=1&ts=3.7-Beta&ssl=9&ssc=2&pln=6&pc=2#code/MYGwhgzhAECC0G8CwAoa7pmgXmgRlQF9VRIYAhRVDaAIx2gCYjUAzAVwDtgAXASwD2naABUAphB4AKAA4AnATIgAuRNCEBhABZhOAczFSAJmB5hV8AD7RyASlUA3AXyPRCtqmgwQxPEXwBbMQF2aSkPbAA+TxoaeUUIADpNHX1DTjEAdxtw22oMQgAafAAGMryvdDlfdjlhTnYQEBYUEiFJaBMzBgAecQ6U3QNsBGNTczgI6ORKzvHErAB6RegAJS5+IOgAUTkFOQBCIkJoRcjUVBBfaAAPVTGzC2hrOxxopxdUG4YHidgpxDEFBAA

**Related Issues:**

**Comment by Jack-Works** [comment]
I found that using `props: { onChange: (data: A | B) => void }` can get the right behavior.

A friend tell me that in TypeScript `{ method(): void }` is using covariant and `{ method: () => void }` is using contravirant to make `method` and `function` different.

I think there is no reason to use convariant rule on JSX property.

**Comment by dragomirtitian** [comment]
Under `strictFunctionTypes` ([PR](https://github.com/microsoft/TypeScript/pull/18654)) There is a general rule that method signatures are bi-variant. This is why the assignment is allowed, it has nothing to do with JSX. This assignment would be allowed as well:

```ts
let x: { onChange(data: A | B): void }
x = { onChange: (data: A) => { } }
```
[Play](https://www.typescriptlang.org/play/?jsx=1&ts=3.7-Beta&ssl=9&ssc=35&pln=8&pc=1#code/MYGwhgzhAECC0G8CwAoa7pmgXmgRlQF9VRIYAhRVDaAIx2gCYjVUQBTAF2gA8AuRNAD2AOwDCACzAiA5uwAUAEzCcwA+AB9o5AJQCAbkICWi6MRQ8GCYeKmz2ApSrVwdOAHyDCZ1EA)

The workaround, as you found is not to use a method signature, but to you a property that is a function type which behaves contravariantly: 

```ts
let x: { onChange: (data: A | B) => void }
x = { onChange: (data: A) => { } } // err
```
[Play](https://www.typescriptlang.org/play/?jsx=1&ts=3.7-Beta&ssl=9&ssc=42&pln=8&pc=1#code/MYGwhgzhAECC0G8CwAoa7pmgXmgRlQF9VRIYAhRVDaAIx2gCYjVUQBTAF2gA8AuRNAD2AOwDCACzAiA5uwEAKACZhOYAfAA+0cgEocAPmgA3IQEsl0Yih4MEw8VNnzoy1erj7sR+4SvQAegDodgAnUNQgA)

**Comment by Jack-Works** [comment]
Yes I get it. But is there any use case that when we use JSX, we want to check the JSX property bivariant or covariant?

**Comment by dragomirtitian** [comment]
@Jack-Works Different syntax for different things seems acceptable to me. You don't want bivariance there is an option to write it so it behaves contravaraintly,

React actually uses a hack to force bivariance even for function fields:

```ts
type EventHandler<E extends SyntheticEvent<any>> = { bivarianceHack(event: E): void }["bivarianceHack"];
```
This is done in order to allow function handlers to behave bivariantly, so someone thinks this behavior is useful enough for JSX to actually force it in some cases 😊

**Comment by Jack-Works** [comment]
🤔But in the case I listed above actually happened in our product so I think it might be a common mistake when writing types for React Component

**Comment by dragomirtitian** [comment]
@Jack-Works I think an eslint rule that forbids use of method syntax in object types (maybe just anonymous object type or in type aliases) might be a simple enough to write and would be something each team could opt in if they so chose.

**Comment by Jack-Works** [comment]
maybe we need a suggestion from the language service
