### ISSUE TITLE
Some methods are missing from Blob interface

### ISSUE THREAD

**Issue by waxlamp** [microsoft/TypeScript#34652]
The `arrayBuffer()`, `stream()`, and `text()` of `Blob` are missing from the type definition. (See https://w3c.github.io/FileAPI/#stream-method-algo and following for details.)

**TypeScript Version:**  3.7.0-dev.20191021

**Search Terms:** blob text method typescript

**Code**

```ts
declare var x: Blob;

x = new Blob();
x.slice();
x.text();
```

**Expected behavior:** Program typechecks.

**Actual behavior:** `error TS2339: Property 'text' does not exist on type 'Blob'.`

**Playground Link:**  https://www.typescriptlang.org/play/?ts=3.7.0-dev.20191021#code/CYUwxgNghgTiAEA3W8AeAueAhCB7ARgNwCwAUGavALzwB2IA7tnvgBQCUJpqAdAM4QAlmBAcuvAC4hUEsUA

**Related Issues:**  none

**Comment by MartinJohns** [comment]
According to the MDN these methods are still only part of a Working Draft and not well supported.

https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream
https://developer.mozilla.org/en-US/docs/Web/API/Blob/text
https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer

**Comment by waxlamp** [comment]
You're right.

What's the best way for me to "monkeypatch" these into my code if I really want to make use of them? I imagine I can't just redeclare `interface Blob` and expect everything to just work?

**Comment by MartinJohns** [comment]
You should be able to use declaration merging for this and provide your own declarations:

https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by waxlamp** [comment]
Thank you for the pointer!

**Comment by aizatto** [comment]
Ran into this same problem in my `create-react-app`

Added this to `src/react-app-env.d.ts`

```ts
interface Blob {
  text: () => Promise<string>
}
```

**Comment by valio2** [comment]
You could also call it like `x['text']()`, if you don't want to redeclare the interface.

**Comment by hari-narendran** [comment]
> You could also call it like `x['text']()`, if you don't want to redeclare the interface.

Thank you this helped me while upgrading old project from Angular 2 to 5

**Comment by dogukanakkaya** [comment]
As of today `Blob` functions are widely supported. I guess it'd be nice to reopen this issue since this is still valid.
