### ISSUE TITLE
transpile error message format is different between different node versions

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#34662]
**TypeScript Version:**  3.6.4

**Search Terms:**
Error Message Formats

**Code**

```ts
import * as fs from 'fs'
import * as path from 'path'
import * as vm from 'vm'

import ts from 'typescript'

export const resolve = (...args: string[]): string =>
  path.resolve(__dirname, ...args)

export const read = (file: string): string =>
  fs.readFileSync(resolve(file) + '.ts').toString()

export const execute = (file: string, ...args: number[] | string[]) =>
  vm.runInNewContext(ts.transpile(read(file)), { exports: {} })(...args)
```

**Expected behavior:**

Error snapshots match for all node versions

**Actual behavior:**

Matched on node 8.x and 10.x, breaks on 12.x

![image](https://user-images.githubusercontent.com/8336744/67363618-6041ac80-f5a0-11e9-8cd4-64ea8e179899.png)

**Playground Link:** 

[GitHub Actions](https://github.com/rx-ts/babel-preset-proposal-typescript/commit/9179dfb5680bdd22950b3a0813e3995cb0af309e/checks?check_suite_id=277187061)

Plain logs:

[Node 8.x](https://pipelines.actions.githubusercontent.com/Y5RmP5yn0997VPPSfftNI3pDCLIH7yT6V7hMzUf6y5aTTGSlOA/_apis/pipelines/1/runs/49/signedlogcontent/44?urlExpires=2019-10-23T06%3A22%3A59.2920110Z&urlSigningMethod=HMACV1&urlSignature=jdHFAq90lRlzkVggYFj%2BthxP9KKQ9GLryxNwYPnZL3M%3D)
[Node 10.x](https://pipelines.actions.githubusercontent.com/Y5RmP5yn0997VPPSfftNI3pDCLIH7yT6V7hMzUf6y5aTTGSlOA/_apis/pipelines/1/runs/49/signedlogcontent/32?urlExpires=2019-10-23T06%3A23%3A30.6693230Z&urlSigningMethod=HMACV1&urlSignature=d9vmJvmLkV5NyjC6a9SHJ61szzm5rRUgkP%2BFhIR7%2FWg%3D)
[Node 12.x](https://pipelines.actions.githubusercontent.com/Y5RmP5yn0997VPPSfftNI3pDCLIH7yT6V7hMzUf6y5aTTGSlOA/_apis/pipelines/1/runs/49/signedlogcontent/29?urlExpires=2019-10-23T06%3A21%3A48.5247772Z&urlSigningMethod=HMACV1&urlSignature=ir%2FoLNuPdPLVL21gDWSV97Dr3VFpHXrhOoLIM5B9Tz8%3D)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
The "Node 12.x" link is broken. Can you paste the text *as text* in the issue? Thanks!

**Comment by JounQin** [comment]
https://github.com/rx-ts/babel-preset-proposal-typescript/commit/9179dfb5680bdd22950b3a0813e3995cb0af309e/checks/271086718/logs

You can view it from the actions.

**Comment by IllusionMH** [comment]
Are you sure it's not an exception from Node?

![image](https://user-images.githubusercontent.com/1312662/67513009-a54e0780-f6a2-11e9-82d0-9b5c3f32228d.png)

Can't find anything similar in TS sources.

**Comment by JounQin** [comment]
Wow, it should be related to Node itself then. Thanks for your work.
