### ISSUE TITLE
Exhaustive switch return type is incorrect without intermediate variable

### ISSUE THREAD

**Issue by niedzielski** [microsoft/TypeScript#34661]
**TypeScript Version:**  3.7.0-beta

**Search Terms:** enum switch

**Code**

```ts
enum Animal {
    DOG,

    // Add second member to avoid https://github.com/microsoft/TypeScript/issues/23572.
    CAT
}

const zoo: { animal: Animal } | undefined = { animal: Animal.DOG }

// OK.
function intermediateVariable(): Animal {
    const animal = zoo?.animal ?? Animal.DOG
    switch (animal) {
        case Animal.DOG: return Animal.DOG
        case Animal.CAT: return Animal.CAT
    }
}

// Error: Function lacks ending return statement and return type does not include 'undefined'.(2366)
function expression(): Animal {
    switch (zoo?.animal ?? Animal.DOG) {
        case Animal.DOG: return Animal.DOG
        case Animal.CAT: return Animal.CAT
    }
}
```

**Expected behavior:** Inferred type doesn't depend on intermediate state.

**Actual behavior:** Inferred type differs when an expression is switched on directly versus when the value is assigned to an untyped intermediate variable and then switched on.

**[Playground Link](https://www.typescriptlang.org/play/?ts=3.7-Beta#code/KYOwrgtgBAgiCWECGAbKBvAUFHUAiA8gOIA0m2uA9JbACa1QDOwAxgPYgMTAQBGwAJygAXNlCQA3NvAYALYcIAOjAFzUA5vGGywvAHTsIlCPBYC2jNgDNhlACoBPRcADKZ+ItvxGjMMEaUAEwAzACsAOyBehQ4AMIwdpgAvuTsIIzCUABebGwqGOIIyCj5cIioUElQAD5QYJzAVvAgwAwAvAVIRail3Sh6hESV5NRQBADS0Vb1LMLwHFDNwoLctPBIywBqSALrvCjAABQAlL3laFi4UGkZhedQHTlsAPx6XffPz7B9A8QxTAB3LQsWRQQ7vYrHDD-K4sJDMb7nX5EfICYDCMACECI4rImG4OEIsq4+J2VHozHY4moPSk-4pFKYUYAUQE5gE+QAYjM5gsUEgWABrRhQUBrEDqKBojFYpjCDY8UCZLoMaWUkROYBQWhsfxQEBsTLNFgoMC0LUAcnq5qaLVoFr0hxCADZncdMNMQLN5tjgAAPRRonw+k5nYrQq6MIHCEFgp6vCEVT44mmDKGXK4E+Fa6n9QbkmVUn6DfE4Qk5n6kgvq3O0hL05KYIA)** 

**Related Issues:**  #6155 #32905

**Comment by ahejlsberg** [comment]
This issue is an effect of switching to the control flow analyzer for exhaustiveness checking. We need to unconditionally include CFA nodes representing a missing default clauses in order for our analysis to be correct. Currently we only include such CFA nodes when the `switch` expression is a narrowing expression.
