### ISSUE TITLE
Type Inference: Key Added as Type for Optional Fields

### ISSUE THREAD

**Issue by chriszwickerocteris** [microsoft/TypeScript#34668]
**TypeScript Version:**

* 3.6.3
* Also tried on the [playground](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191022&ssl=1&ssc=1&pln=36&pc=3#code/JYOwLgpgTgZghgYwgAgEoRtCIkB4AqAfMgN4BQyywAJgFzIDOYUoA5gNxkC+ZZoksRCgBiAe1GkKVOo2ZtOlAEZwo9dJijY8AIRWEFyVuJgB+NRiw4IuXVH3de-aPCTJbkynHpMWIDg7IwAE8ABxR0BlEAGwA3awBRABpkfGQIAA9IEGoGZABBKCg4INwAawgg0RhkeMJiAF4PZABtYSoQZHLK6viAXVopSjaMrJyU5pAAVwBbRWheweQTGtbetMzsMdANGuFFymX44Y3s3PVLPG3oNEJ9yiW0O8p6eNW7+hAIOKhFl7euTiBUIicQRaJxajIRpg2LWMSiZLNABEyigSOSSKMVSRvXsZAQohATHaBMKEAQYCiQQA6qIoKUGPR4TCIVCmjR6Ei4AxqDB0VJUfQSMgvMgkel0kjkFxElIsTBOfL+QD8YTiaTNBSqQARUQQBjgWn0pmg-XgiCQxrkSgcsXc3n8pQqTmo5XsIA)

**Search Terms:**

inference optional added string

**Code**

```ts
interface Reference<T> {
  id: string;
}

interface Foo {
  id: string;
  bar: Reference<Bar>;
  goof?: Reference<Bar>;
}

interface Bar {
  a: string;
}

type Resolve<E, T extends Array<keyof E>> = {
  [F in keyof E]:
    F extends T[number]
    ? E[F] extends infer EF
      ? EF extends Reference<infer R>
        ? R
        : E[F]
      : never
    : E[F]
};

type FooResolved = Resolve<Foo, ["bar", "goof"]>;

const incorrectlyWorks: FooResolved = {
  id: "asdf",
  bar: { a: "xx" },
  goof: "goof",
};
const correctlyDoesntWork: FooResolved = {
  id: "asdf",
  bar: "bar",
};
```

**Expected behavior:**

The resolved type should match

```ts
type FooResolved = {
    id: string;
    bar: Bar;
    goof?: Bar;
}
```

**Actual behavior:**

The resolved type matches

```ts
type Y = {
    id: string;
    bar: Bar;
    goof?: "goof" | Bar | undefined;
}
```

**Playground Link:**

[Playground Reproduction](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191022&ssl=1&ssc=1&pln=36&pc=3#code/JYOwLgpgTgZghgYwgAgEoRtCIkB4AqAfMgN4BQyywAJgFzIDOYUoA5gNxkC+ZZoksRCgBiAe1GkKVOo2ZtOlAEZwo9dJijY8AIRWEFyVuJgB+NRiw4IuXVH3de-aPCTJbkynHpMWIDg7IwAE8ABxR0BlEAGwA3awBRABpkfGQIAA9IEGoGZABBKCg4INwAawgg0RhkeMJiAF4PZABtYSoQZHLK6viAXVopSjaMrJyU5pAAVwBbRWheweQTGtbetMzsMdANGuFFymX44Y3s3PVLPG3oNEJ9yiW0O8p6eNW7+hAIOKhFl7euTiBUIicQRaJxajIRpg2LWMSiZLNABEyigSOSSKMVSRvXsZAQohATHaBMKEAQYCiQQA6qIoKUGPR4TCIVCmjR6Ei4AxqDB0VJUfQSMgvMgkel0kjkFxElIsTBOfL+QD8YTiaTNBSqQARUQQBjgWn0pmg-XgiCQxrkSgcsXc3n8pQqTmo5XsIA)

**Related Issues:**

n/a

**Additional Observations**

What is really interesting is that if I open a standalone editor in VSCode and set the "Language Mode" to TypeScript, the type is resolved as expected. Due to this, I assumed one of the options in my `tsconfig.json` was causing the problem. I removed all of the options set, but the problem persisted.

I'm using VSCode 1.39.1, commit `88f15d17dca836346e787762685a40bb5cce75a8` on macOs Catalina. TS versions match between node_modules and VSCode (3.6.3).

**Comment by RyanCavanaugh** [comment]
The Playground shows the expected error. Can you clarify how to reproduce the problem?

**Comment by chriszwickerocteris** [comment]
Wow, this is really strange! I checked on 3.6.3, 3.7-Beta and 3.8.0-dev when I opened, but neither shows the problem now... What's more, I can't reproduce in my local VSCode!

Ok, thanks for looking into it and sorry for wasting your time - I'm very confused here!!
