### ISSUE TITLE
“locale” in tsconfig.json with compilerOptions is invalid,can support?

### ISSUE THREAD

**Issue by lsd908321** [microsoft/TypeScript#34664]
//tsconfig.json
{
  "compilerOptions": {
    "locale": "zh-cn"
  }
}

tsc -p tsconfig.json output  is english
can use the settings's locale?

**Comment by RyanCavanaugh** [comment]
The locale has to be a commandline argument. You want to do this anyway since otherwise TS wouldn't know what language to display parse errors in the tsconfig file in.
