### ISSUE TITLE
Enum default starts @1

### ISSUE THREAD

**Issue by Glorifundel** [microsoft/TypeScript#34678]
## Search Terms

enum
compiler options
enum default

## Suggestion

I would like enum default behavior to start assignment at numeric 1, or to enumerate by default with strings.

Default behavior currently has an enum start at numeric 0, this causes a danger for lazy existence checking.

## Use Cases

Although perhaps a personal preference, I think enum's should function as purely logical constructs, their actual value being effectively irrelevant, they are ideally used to make an assignment From an enum to some variable or property, and later using it to do a conditionalized check against the enum definition (not directly checking based on the internal value it is compiled to)  This works fine as-is with direct identity checks.  This has a vulnerability for existence checks.

Specifically performing a fuzzy existence check on a variable containing an optional enum will result in a failed check if the enum happens to internally be assigned as 0.

## Examples

enum Dangerous {
  Hi,
  There 
}
// internally Hi has been assigned 0, and There has been assigned 1

let test: Dangerous | undefined = Dangerous.Hi
.
.  // do some stuff
.
if(test) {
  console.log('Success, there is an enum present!  test: ', test);
} else {
  console.log('Failure, there is not an enum present!  test: ', test);
}

// Console Output:
//       Failure, there is not an enum present!  test: 0

// Running the same example with test = Dangerous.There
//  Console Output: 
//       Success, there is an enum present!  test: 1

//  Running the same example with test = undefined
// Console Output:
//       Failure, there is not an enum present!  test: undefined

I would like both cases where an enum is in-fact  present, to succeed the fuzzy existence check.

## Checklist

[X] This wouldn't be a breaking change in existing TypeScript/JavaScript code

Adding a compiler option would allow users to set project wide a default behavior for assigning enums, stopping this potentially dangerous javascript quirk.

--EnumStartsAtOne
   have all enums (unless directly defined by the proggrammer) start assignment at 1.

or

--EnumString
  set enum values as the string version of the numeric's typically assigned.   enum Ex { First: '0', Second: '1' }
or the compiler could assign the key as the value in those cases:  enum Ex { First: 'First', Second: 'Second' }

Some flavor of those changes, so an enum never is assigned 0 ( unless directly assigned by the programmer )

[X] This wouldn't change the runtime behavior of existing JavaScript code

Going the compiler option route would avoid possible conflicts.

[X] This could be implemented without emitting different JS based on the types of the expressions

Yes

* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)

Yes

* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I believe this is inline with those goals in that it will reduce the likely hood of failures due to existence checks.

If this could be made the initialization behavior by default I think that would be even better, but then it would cause a breaking change, so it seems like a compiler option is the best route.

Thank you for your consideration.

**Comment by Glorifundel** [comment]
As an aside, I know this can be achieved by assigning a value to the first enum, ie.

enum SlightlyAnnoying = {
   Stuff = 1,
   Things, 
   Blorp,
   Blip 
}

however this seems not ideal to have to manually define a value to all your enums to avoid the potential pitfall.

**Comment by nmain** [comment]
> I think enum's should function as purely logical constructs, their actual value being effectively irrelevant

That's nice, but a bit divorced from the actual reality of things; code can and will do whatever it wants to in the js runtime, and the default numbering order of enums is something that's been guaranteed by Typescript since the bronze age.

So `--enumStartsAtOne` would be difficult or impossible to use if you're bringing anyone else's library code into your compilation; you could break a library's assumption about enum values.

On the other hand, this sounds like an ideal case for a linter rule:  You could have any enum without a value specified for the first member cause a lint warning or error, and then you could apply that to your code as your preference, and others could choose not to use that linter warning if they wanted to.

**Comment by orta** [comment]
Thanks for the idea, however this is not possible to do without breaking a lot of code, as @nmain mentioned. 

It also would break the expectations for people coming from other languages because all the languages I can think of have enums which start at 0.

**Comment by Glorifundel** [comment]
> So --enumStartsAtOne would be difficult or impossible to use if you're bringing anyone else's library code into your compilation; you could break a library's assumption about enum values. 

I was unaware typescript applied a local projects TS compile settings onto npm dependencies found in node_modules.  Changing that behavior even as a compile option would indeed be very dangerous.
