### ISSUE TITLE
Clarify canvas ctx.globalCompositeOperation type

### ISSUE THREAD

**Issue by Joncom** [microsoft/TypeScript#34673]
**TypeScript Version:**  3.6.4

**Search Terms:**

globalCompositeOperation, TypeScript, union

**Code:**

The valid strings for `ctx.globalCompositeOperation` can be viewed here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

For example, this is valid:

```ts
ctx.globalCompositeOperation = 'source-in';
```

However, this is invalid:

```ts
ctx.globalCompositeOperation = 'foo';
```

And yet TypeScript thinks both are valid, because TypeScript simply defines `globalCompositeOperation` as `string`:

https://github.com/microsoft/TypeScript/blob/29becf05012bfa7ba20d50b0d16813971e46b8a6/lib/lib.dom.d.ts#L3376-L3379

The following union would provide a better development experience:

```ts
 'source-over' | 'source-in' | 'source-out' | 'source-atop' | 'destination-over' | 'destination-in' | 'destination-out' | 'destination-atop' | 'lighter' | 'copy' | 'xor' | 'multiply' | 'screen' | 'overlay' | 'darken' | 'lighten' | 'color-dodge' | 'color-burn' | 'hard-light' | 'soft-light' | 'difference' | 'exclusion' | 'hue' | 'saturation' | 'color' | 'luminosity'
```

**Comment by dhaig** [comment]
I opened a PR with these typings over in the DOM-lib-generator repo: https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1206

**Comment by jakebailey** [comment]
The above was pull into main in #47445.
