### ISSUE TITLE
Type is not assignable to type 'void' warning inconsistent

### ISSUE THREAD

**Issue by jimmyfortinx** [microsoft/TypeScript#34675]
**TypeScript Version:**  3.6.3

**Search Terms:**

**Code**

```ts
let returnVoid: () => void;
let returnUndefined: () => undefined;
const returnNumber: () => number = () => 3;

returnVoid = () => {
    return 2; // doesn't fail, but it should since number is not assignable to void
};

returnVoid = (): number => {
    return 2; // doesn't fail, but it should since number is not assignable to void
};

returnVoid = (): void => {
    return 2; // does fail because number is not assignable to void
};

returnVoid = () => {
    console.log('test')
}

returnUndefined = () => {
    return 2; // does fail, because number is not assignable to undefined
};

returnUndefined = () => {
    console.log('test') // does fail, because void is not assignable to undefined
}

returnVoid = returnNumber; // doesn't fail
returnUndefined = returnNumber; // does fail
```

**Expected behavior:**
`() => number` shouldn't be assignable to `() => void`

**Actual behavior:**
`() => number` is assignable to `() => void`

**Goal:**
We want to enforce people to return nothing from that function (also `return;` should be possible). Maybe I'm not using the right keyword, but I didn't found anything around that. Also, we don't want people to have to specify `: void` when they declare the function since nowhere else it's required because typing are correctly behaving.

[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=30&pc=45#code/DYUwLgBATuCuUDsBqB7AlgEwFwQBQEoIBeAPggDd0MBuAKFEhjHgQFUEMQAzNBEbPIVIRYHbr350AxigQBnRnEQA5WAFsARiCg4CxMgnVaoxQfogBmOrSYtUmU3uEBvWhHfQlCCACZqEAHoAiAwUEDkEAHJILgBDNGAAGggNWEg0SDkACxRYYAwIOV4pEAhDTW0INDkylEhYuSKAcwRYjVAIMBQKKloAX2tbRHsCokEccuNzVw9PZkRffyCQsIjoiDiE5NT0zJy8gqKEErKjSura+sa0FraOrp7MfsGvEcd8HEoHFzcPIe8-IFgqFwht4sAUiApLFYHJSpNzjUEHUIA1mq12qUHl8MM9aDZXlR3tNfu4ZPIUKAAHTAFBNXDRcJgSL4fr4-7sTg8PijMw-Wb-RZAlagzZJSHQ2Hws4mC7Iq7ou5Y7qiLkSXEDdleTniHnE-keclySkgGl0hlgJks4Ugmpi7ZQmFwx4FOUotE3DH3FVibn8NkE+bIIljf6qCpQJbA1ZRGLgwMsHV+3lhmVRkV28FAA)

**Related Issues:** It might be related to #33420, but the end goal is not the same

**Comment by j-oliveras** [comment]
[Why are functions returning non-void assignable to function returning void?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

**Comment by jimmyfortinx** [comment]
@j-oliveras I understand that use case, but would it be possible to have a new type like `nothing` (or whatever) that would make it possible to specify that we really want nothing?

**Comment by nmain** [comment]
But you already have that.  If you explicitly annotate a `void` return on the function itself, Typescript does a stricter kind of check to handle exactly this use case, and any `return <value>` is errored.

**Comment by jimmyfortinx** [comment]
But that requires the developer to put `:void` everywhere he is creating a new function for that specific function type. I'll probably have to live with it then.
