### ISSUE TITLE
VS plug in: Unchecked automatic formatting still formats the code

### ISSUE THREAD

**Issue by WaldemarH** [Microsoft/TypeScript#3467]
Using VS 2015 RC and even if all the items in Options/Text Editor/Type Script/Formatting are unchecked when I write a line and press enter the line is formatted.

Ex.:
	var		brb: string = "test";     <-- contains spaces or tabs between var and brb
on enter is converted to
	var brb: string = "test";               <-- only one space is left between var and brb

I would assume if all formatting is unchecked then the editor should not edit anything.

Edit:
This works perfectly in VS2013 SP4.

**Comment by WaldemarH** [comment]
A the first line contained tabs, but the same symptom is when multiple spaces  are used between var and brb.

**Comment by vladima** [comment]
should be fixed by @paulvanbrenk in our internal bits. pinging him to confirm

**Comment by paulvanbrenk** [comment]
Yes, this is fixed for RTM

**Comment by WaldemarH** [comment]
Thanks guys, it's really appreciated what you do.
