### ISSUE TITLE
infer in docs in 2.8 release notes

### ISSUE THREAD

**Issue by guyellis** [microsoft/TypeScript#34684]
**TypeScript Version:**  3.6.4

**Docs**

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html

About half way through the above release-notes:

```javascript
type Bar<T> = T extends { a: (x: infer U) => void, b: (x: infer U) => void } ? U : never;
type T20 = Bar<{ a: (x: string) => void, b: (x: string) => void }>;  // string
type T21 = Bar<{ a: (x: string) => void, b: (x: number) => void }>;  // string & number
```

T21 is `never` with tsc 3.6.4 but with 2.8 it is `string & number`. Would be great if that doc had a link to the updated functionality or noted that it's changed.

**Comment by RyanCavanaugh** [comment]
I think it would be weird to backport changes to release notes - these are effectively historical documents and should be kept as-is absent concrete errors.

**Comment by guyellis** [comment]
@RyanCavanaugh - I understand and agree with the sentiment. Perhaps there's a better way to solve this. Is that information accurately available elsewhere in the official docs for the latest release of TypeScript? If so, how do we get readers from there to the latest docs or at least let them know that there could be changes since that was written and where these docs are?

For example, for this change, I can't find where this change is documented?
