### ISSUE TITLE
Overloads should have `async` modifier when implementation has `async` modifier

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#34698]
**TypeScript Version:**  3.6.3, 3.5.1, 3.7.x-dev.201xxxxx

**Search Terms:**

overload, async

**Code**

```ts
interface ImpossiblePromise extends Promise<number> { 
    impossibleMethod(): void;
}

/**
 * Overloads should have `async` when implementation has `async`
 */
function foo(): ImpossiblePromise;
async function foo(): Promise<number> {
    const p = Promise.resolve(42);
    (p as any).impossibleMethod = () => {
        console.log(42);
    };
    return p;
}

foo()
    .impossibleMethod();
```

**Expected behavior:**

A compile error on the overload. An `async` on the implementation of `foo` should force an `async` on overloads. Or should at least force all overloads to return `Promise<>`

**Actual behavior:**

Compiles fine. Throws a run-time error when run.

**Playground Link:** 

[Playground](http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=18&pc=25#code/JYOwLgpgTgZghgYwgAgJIFsAOB7Azr4AIwBsIAFKbdYXFCAD0hABNdkKqaIAeEAV3SFoAPmQBvZAChkM5MCx4CJCAFkIYABbZmACgCUALmQA3bMGYBuSQF9JkgPQAqR9MfIA8sejFscVslwtPmJmZA04L2QAAzhcAE8QBCjkAHcNCBA5LFJ0DLA4MGBsTPC2GPjEqNd7SRg+RMLi5BhsbH0jDBx8IlIOalorWISEZvqERsyWtsN2Sn6efkERcWlZBGLcMGRMZABeWc5aADooCFxsYi8dABYAJj0rWWQdHdjkOBA4vSP5LqVSNSabR7Z56PaiMSrJ4ydYgc6kI4+ADmN3uj1k1nRMlOYD4UEymCstlqrX0UOQPwU3WUgK0ugeQA)

**Related Issues:** 

Somewhat related, but not quite,

https://github.com/microsoft/TypeScript/issues/28516

https://github.com/microsoft/TypeScript/issues/28516#issuecomment-455002687

-----

I found another thing about overloads that bugs me =x

**Comment by AnyhowStep** [comment]
Another related thing that bugs me,
```ts
/**
 * Implementation should have `async` when overload has `async`?
 */
async function foo(): Promise<number>;
function foo() : Promise<number> {
    throw new Error("Can't catch me")
}

foo()
    .catch((err) => {
        console.log("I should catch all errors from async functions... Right?");
    });
```
[Playground](http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=12&pc=8#code/PQKhCgAIUhJBbADgGwKb1QOwC4ENsCWA9ppAM4AWRArsgCaQW4BuqkABrmQJ6YDG7SAHcKWSEVYAnZEVwMmZDl14CA-FBDBwy-pABm1foRL6iRABQBKAFyQACpKLwCZVAB5M1eACNUkgHwA3OAGRsSkemZWkLYOTi7unj5+-pAA3lCQWdgUjkKQmKj5AKKSjpLmAEQAwriYAOTYkHz4fBSQGJWW4AC+4CFR3VlZAHQt2G3m5n6SlpAAvKkZwyvNJGREaCMyAOZVsORUtAzjbZC4yMiQM0SSinqO8Oc8uqF8xphkI9+QAEoEOwo2FUXWCKx6lkCQA)

**Expected behaviour:**

A compile error on the implementation.

An `async` on the overload should force an `async` on the implementation.

**Actual behaviour:**

Compiles fine.

Doesn't catch "Can't catch me" error during run-time.

![image](https://user-images.githubusercontent.com/5655961/67454881-ce668d80-f5f9-11e9-82fd-0c721c185fab.png)

-----

In my head, the `async` modifier is kind of like a **guarantee** that the function won't throw an error **synchronously**.

**Comment by nmain** [comment]
`async` is generally not considered part of a function's type right now, so you have things like this:

```ts
async function f(a: number) {
    return a;
}
function g(a: number) {
    return Promise.resolve(a);
}
// ff and gg have the same type
let ff = f;
let gg = g;
```

It's true that an `async function` cannot throw an exception.  If you want that information to make it to typing, does that mean you really want https://github.com/microsoft/TypeScript/issues/13219?

**Comment by AnyhowStep** [comment]
We shouldn't need #13219 to enforce the constraints proposed here

**Comment by nmain** [comment]
I think your first issue is just a special case of known soundness issues in overloads.  Typescript knows that "The return type of an async function or method must be the global Promise<T> type.", and the only failure is in comparing `ImpossiblePromise` on the overload to `Promise<number>` on the implementation.  There are plenty of non-async examples of this:

```ts
function f(a: string): { a: string, b: number };
function f(a: number): { a: string, b: number };
function f(a: any): { a: string } {
    return { a };
}
```

**Comment by AnyhowStep** [comment]
If `async` is applied to all overloads, then we don't have that problem anymore.

I see the first issue and the one in your example as different problems. It looks similar and is related, but they're different.

```ts

```

**Comment by AnyhowStep** [comment]
I just realized this shouldn't be *too* complicated because regular functions already force **all** overloads+impl to either have `export` or not have `export`.

So, it's kind of like copy-pasting code. I could be wrong, though...

**Comment by RyanCavanaugh** [comment]
`async` is ultimately an implementation modifier; I agree that in hindsight it shouldn't have been allowed on overload declarations, though it's useful for presenting a nice symmetrical lineup of the syntax. We don't agree with creating errors in legal and unsketchy code for the sake of finding the kinds of problems constructed here.
