### ISSUE TITLE
Typescript compiler allows class instance to access its private properties.

### ISSUE THREAD

**Issue by shanmugapriyaEK** [microsoft/TypeScript#34700]
**Playground link:**
https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAECCB2BLAtmE0DeBYAUNf0ADgE6IBuYALgKbTxjLUBc0Elp8A5gNy4HTAA9vDbEArsEqDiACkoALagDkGzVu0RcAlJmgLEEAHT1G0ALx7FKxt2gBfXA5y541AO5wkqEDIBEAYSpfLWNVbiA

**Problem:** 
Name property should not be accessed using class instance.
**Typescript code**
```
class Animal {
    private name: string;
    constructor(theName: string) { this.name = theName; }
}
new Animal("Cat").name;
```
**Actual compiled js :**
```
"use strict";
class Animal {
    constructor(theName) { this.name = theName; }
}
new Animal("Cat").name;
```

**Comment by MartinJohns** [comment]
I'm not sure what you expect, as the TypeScript compiler is giving you an error. If you enable the `noEmitOnError` compiler flag, then no JavaScript is emitted on erroneous code, otherwise the invalid code is emitted as is.

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs

**Comment by shanmugapriyaEK** [comment]
Could you please add this in the typescript documentation if possible that it would be converted to es6 class?

**Comment by shanmugapriyaEK** [comment]
Though typescript throws the error in compile time. It does not serve the actual purpose during runtime. Hence please add a note in documentation. Thanks for explaining

**Comment by MartinJohns** [comment]
It is documented in the FAQ: https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-type-erasure

Anything TypeScript related is only compile-time. After compilation you only end up with JavaScript, and everything TypeScript related is gone. In JavaScript you have no such thing as "private fields", except...

...except for the upcoming new ECMAScript feature "private fields" (part of the class fields proposal). Support for this feature is tracked in #30829 and will most likely require adoption of a new syntax (to align with ECMAScript and to prevent breaking changes).

**Comment by shanmugapriyaEK** [comment]
Thank you.
