### ISSUE TITLE
[3.7.1.-rc] Regression: exhaustive switch statements are not exhaustive anymore

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/TypeScript#34716]
**TypeScript Version:**  3.7.1.-rc

**Search Terms:** noFallthroughCasesInSwitch, exhaustive, exhaustiveness, switch

**Code**

```ts
interface ProcessEnv {
  NODE_ENV: 'development' | 'production';
}

declare const env: ProcessEnv;

declare function getEnvironmentVariable<K extends keyof ProcessEnv>(key: K): ProcessEnv[K];

const getNodeEnvironment = () => { // 💣 Not all code paths return a value.ts(7030)
  switch (getEnvironmentVariable('NODE_ENV')) {
    case 'development':
      return 'development';
    case 'production':
      return 'production';
  }
};
```

**Expected behavior:**

No error. The expression provided to `switch` evaluates to either `'development'` or `'production'`, so the switch statement is exhaustive.

Interestingly enough, if we assign the expression to a local variable, the function becomes exhaustive.

```ts
const getNodeEnvironment = () => { // ✅ No error
  const environment = getEnvironmentVariable('NODE_ENV');

  switch (environment) {
    case 'development':
      return 'development';
    case 'production':
      return 'production';
  }
};
```

**Actual behavior:**

A compile-time error for `getNodeEnvironment`.

```
Not all code paths return a value.ts(7030)
```

[**Playground Link**](https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=27&ssc=3&pln=18&pc=1#code/JYOwLgpgTgZghgYwgAgApQPZIM7YKIgBuyA3gFDLIByA8gCJ4D6eVAagFzIDkAJhIRAA2GAA4BbCOC7IAPtxGYeAVwRhgGEFwDcZAL5kyfBILhQUCDdjDJJhTuiwRcBQjsMRjplDCUhV6kGQAcwgwF2BMEAlwVlNgOAAjQQgAHgBpGwAPSBAebGQAawgATwwYNEwcfCIAPgAKIuLONIBKe0qnasIAbTSAXTcLECtg0KoMPnDI6OsAXmQ6luRZmtJkAHp16gxrOEFBZAs+ZBE4MAALfLMwJShAuGRCPaUIADowbDqAdgAGAGYfi0KMhsAB3YBgBDnBYhMJECIaGaxKDxJIQOpcWgMZhsLgtJbkSiUBBwbAoXj8ISiGZcdjAonIa63QIUgTCcSSMDaemHUnkhQTFRqDS0nmUJl3eSKIUBbmUfS6QaWayw8aTeHTTkAJmWCyWK1IwKGI1sCKinN1sKmiM5yNRyQxWKYLFYeLclDBEKhC1NmvABJ5JLJ3D4bOpnNFDPFoWZIcp7JpOgZQf50v8IrpUcZMclXAFynTmiTyAVOiAA)

**Comment by fatcerberus** [comment]
Duplicate of #34661, it looks like.

**Comment by karol-majewski** [comment]
You're right, thank you.
