### ISSUE TITLE
When monorepo like packages are linked through symlink and are not built editor cant resolve modules

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/TypeScript#34723]
@sheetalkamat - I am trying this out and noticed that it doesn't work in the case of things that are imported from the outDir rather than the src (in the case of a monorepo):

![image](https://user-images.githubusercontent.com/34725/67434188-764e6d80-f59e-11e9-94ac-fbf90aae0a79.png)

For a quick way to verify this, I prepared a monorepo for you to check it out:

https://github.com/kenotron/TypeScriptMonoRepo/tree/ts3.7

Things work okay if you do "yarn && yarn build", but if I understand this feature, it is meant to address the case where you can start editing in VS Code with Intellisense even before having to build something because we're traversing source rather than output.

_Originally posted by @kenotron in https://github.com/microsoft/TypeScript/pull/32028#issuecomment-545637314_

**Comment by sheetalkamat** [comment]
Have investigated this and currently we are not handling symlinks.. If the resolution happens to be looking at the output path for the referenced project, we make sure that the answer to fileExists and directory Exits is true so that the resolution uses the output file even when its not present. 
In case of symlinks those paths are different eg. its looking for `outDir` in  `"c:/temp/TypeScriptMonoRepo/node_modules/b/lib"` instead of `"c:/temp/TypeScriptMonoRepo/packages/b/lib"`. If resolution had asked for the later we would answer yes and resolution will succeed and we will use source file instead.

**Comment by kenotron** [comment]
How hard is it to provide a flag here to traverse symlinks? I think this would enable a lot of monorepos to use this feature directly without resorting to the hack of the main field being `src/index.ts`

**Comment by sarpik** [comment]
This applies to [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) (since symlinks are used under the cover) and it would be extremely useful to have them supported. Currently we still have to build manually..

**Comment by kenotron** [comment]
@sarpik - the only workaround I see currently is to use the main field to point to a single entry point index. I currently have to create a script to change this at pre-publish time
