### ISSUE TITLE
undefined URL constructor base argument for Safari

### ISSUE THREAD

**Issue by BarryThePenguin** [microsoft/TypeScript#34725]
**TypeScript Version:**  3.6.4

Though the types are still the same

https://github.com/microsoft/TypeScript/blob/a03227d60e2da470a8a964903016e2b3d0106950/lib/lib.dom.d.ts#L16068-L16073

**Search Terms:**

undefined URL constructor base argument Safari

**Code**

```ts
class FooURL {
  private _url: URL
  
  constructor(url: string, base?: string | URL) {
    this._url = new URL(url, base)
  }
}

// Throws `TypeError: Type error` in Safari
new FooURL('https://example.com')
```

**Expected behavior:**

The constructor for URL should not allow `undefined` constructor argument for `base`

Something more appropriate could look like

```ts
new(url: string): URL; 
new(url: string, base: string | URL): URL; 
```

**Actual behavior:**

Both Safari Version 13.0.2 (14608.2.40.1.3), and Safari Technology Preview Release 94 (Safari 13.1, WebKit 14609.1.6.1) throw an error when the `base` constructor argument is undefined.

Essentially typescript treats `new URL('example.com', undefined)` as valid

Other browsers are able to handle this case just fine.

I did look at the [whatwg spec](https://url.spec.whatwg.org/#url-class)

Maybe it's a problem with how `TSJS-lib-generator` generates optional arguments?

I'm not sure if this is something that _should_ be handled by TypeScript. Interested to hear what others think!

[**Playground Link**](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=10&pc=34#code/MYGwhgzhAEBiD28CqAlAMtA3gKGtADgE4CWAbmAC4Cm0A+gK6EgBc0qau0nw8AdhBUL1gFeIQAUjFtAEleAcwA00AEaQqAflaziC6AB826AJRZOeCgAtiEAHQMm0ALzReVAO5G0kpsrUQqY04AX2xQ7AB6COgAFUtCeHcYAAMYgE98KgBRQgTCVnTM6CpcsWToXWgAZTAAMzASbDdPBGR0cQBySwoKfAhmKKoADzAAW3wQKlseUY7jIA)

**Related Issues:**

#15246

**Comment by trotyl** [comment]
I have report this to core-js that Safari doesn't have valid `URL` implementation: https://github.com/zloirock/core-js/issues/656, the types are indeed correct.

**Comment by BarryThePenguin** [comment]
Ahk, I was unsure if that was the case. That clarifies things for me. Thanks for the response!
