### ISSUE TITLE
a way to generate PropTypes from TypeScript

### ISSUE THREAD

**Issue by naorye** [microsoft/TypeScript#34737]
I am using React with TypeScript. I am also using PropTypes.
TypeScript is intended for compile time type checking while PropTypes validate passed props on run time (development mode).
So I found myself writing types twice. Both TypeScript and PropTypes. For example, component ListingsList:
```
interface ListingsListProps {
    listings: Listing[];
    height: number;
    width: number;
    rowHeight: number;
    forwardedRef?: Ref<List>;
    className?: string;
}

const ListingsList: FunctionComponent<ListingsListProps> = props => {
...
...
};

ListingsList.propTypes = {
    listings: PropTypes.arrayOf(listingPropType.isRequired).isRequired,
    height: PropTypes.number.isRequired,
    width: PropTypes.number.isRequired,
    rowHeight: PropTypes.number.isRequired,
    forwardedRef: PropTypes.shape({ current: PropTypes.instanceOf(List).isRequired }),
    className: PropTypes.string,
};
```

Each time I made a mistake (defining a property differently in PropTypes and in TypeScript), I get typescript error. Sometimes I don't really know how to define the PropType. For example, when passing History property from 'history'. I don't want to define History PropType myself because it has a complicated shape.
I saw there are projects that generates TypeScript from PropTypes but I really don't like it because TypeScript is much stronger, I can define more detailed types.
I am looking for a way to generate PropTypes from TypeScript, and I think this is a must feature for React developers.

**Comment by orta** [comment]
If this is for the runtime features of PropTypes, you can use something like [babel-plugin-typescript-to-proptypes](https://github.com/milesj/babel-plugin-typescript-to-proptypes) to generate the `ListingsList.propTypes` from your interface.
