### ISSUE TITLE
 Crash when `IntrinsicElements extends Record<string, any>`

### ISSUE THREAD

**Issue by kgtkr** [microsoft/TypeScript#34730]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
* jsx
* tsx
* Record
*  extends
* IntrinsicElements

**Code**
```ts
/* @jsx D.createElement */

import * as D from "./d";

<a />;
```

```ts
// d.ts
export declare namespace JSX {
  interface IntrinsicElements extends Record<string, any> {}
}
```

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Actual behavior:**
```
Cannot read property 'type' of undefined.
```

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
I can't repro this. Does it still crash with `typescript@next` ? What does your tsconfig look like?

**Comment by kgtkr** [comment]
https://github.com/kgtkr/tsx-bug

**Comment by sandersn** [comment]
Thanks, that's perfect.

This has crashed since 2.8, and before that failed to compile with "Can't find name 'React'.".

**Comment by kgtkr** [comment]
jsx pragma can only be used after TS2.8
