### ISSUE TITLE
a bug with "export * from ..."

### ISSUE THREAD

**Issue by ooyyloo** [microsoft/TypeScript#34731]
**TypeScript Version:**  3.6.4

**Search Terms:**
typescript export compiler

**Code**

```ts
// a.ts
import {B} from './b';

export interface A {
  a: B;
}
```

```ts
// b.ts
export interface B {
  b1: string;
}

export interface B {
  b3: string;
}

export * from './b2';
```

```ts
// b2.ts
export interface B {
  b2: string;
}
```

**Expected behavior:**
When I press F12 in vscode on 'B' which is in 'a.ts', there should be 3 declarations.

**Actual behavior:**
When I press F12 in vscode on 'B' which is in 'a.ts', there are only 2 declarations. The declaration of B in b2.ts is not tracked.

**Comment by RyanCavanaugh** [comment]
@sandersn is this a merge, or does the local declaration take priority?

**Comment by sandersn** [comment]
Nope, no merge here. And the local declaration takes priority, no error as you would have with `export { B } from './b2'`.
