### ISSUE TITLE
Infer type of implicit any from usage

### ISSUE THREAD

**Issue by qwelias** [microsoft/TypeScript#34738]
## Search Terms
infer type
type inference
from usage
argument
implicit any

## Suggestion
Function arguments types should be inferred from their useg inside the function.

## Use Cases
1. Function accepts an argument of implicit any type, argument gets passed to another function where it's type is specified, therefore, it's type could be inferred from usage.
2. Function accepts an argument of implicit any type, certain properties are accessed on the argument, therefore it's type could be inferred from usage.

Currently, if function accepts an implicit any argument it does not infer it's type from usage.

## Examples
In the example below it is obvious that `passString` should accept the `arg` type that extends `arg` type of `acceptString` yet type is not inferred and is shown as `any`;
```ts
const acceptString = (arg: string) => arg;
const passString = (arg) => acceptString(arg);
```

In the example below it is also obvious that type of `arg` should extend `{ do: typeof arg.do }`, but is shown as `any`.
```ts
const callDo = (arg) => arg.do();
```

There could be much more examples, complicated and simple, but as of right now TS does not seem to be handling even simplest ones.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
```ts
function foo (a,b,c) {
  return a+b+c;
}
```

Is `a` of type `bigint|number|string`?

**Comment by RyanCavanaugh** [comment]
This has been an intentional design constraint since inception; *not* doing this is a key reason TS performance is remotely acceptable. The "infer from usage" refactor will produce a type for you on an as-requested basis.

**Comment by qwelias** [comment]
@AnyhowStep Good point, and this is not explicit, `a` and `b` and `c` indeed could be whatever type thats works with `+` operator, but I'm not saying TS should guess that hard, IMO it'd be totally fine if TS would not infer anything in your example.

But TS could handle more explicit cases, like the ones I provided, especially where an argument gets passed into another function with explicit signature types.

**Comment by qwelias** [comment]
@RyanCavanaugh Sorry I wasn't able to get the refactor working for me in simillar cases, and I wasn't able to find much info on what should trigger it.
And thanks for the point regarding performance.

**Comment by merlinaudio** [comment]
With the new Go compiler, could this be re-considered? This is the only real thing I miss from TS.

It would be incredible to be able to do things like this:

```ts
class Foo {
  bar: {baz: string}

  constructor(b) { // type of `b` gets inferred
    this.bar = b;
  }
}

new Foo(123);
//      ^^^ Argument of type 'number' is not assignable 
//      to parameter of type '{baz: string}' (ts(2345))
