### ISSUE TITLE
Destructure parameters and type at the same time.

### ISSUE THREAD

**Issue by danm** [microsoft/TypeScript#34748]
name: Destructure function parameters review
about: Allow types to be added to destructured function parameters for better readability
---

Despite what https://github.com/Microsoft/TypeScript/wiki/FAQ#functions says, can we not type cast parameters using <brackets> instead?

I destructure my parameters a lot, and having to create another curly brace afterwards makes the code messy. I abstract the parameter type to an interface most of the time, but in some cases, it would just be nicer to add types right there whilst destructuring.

so how about...
```
function f({x : <number>}) {
  console.log(x);
}
```

with alias'
```
function f({ x: aliasX<number>}) {
  console.log(x);
}
```

with optional
```
function ({ x?: <number>}) {
  console.log(x);
}
```

with defaults
```
function f({ x = 10<number>}) {
  console.log(x);
}
```

with defaults and alias
```
function ({ x: aliasX<number> = 10 }) {
  console.log(x);
}
```

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
You might want to check out the relevant [issue template](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md).

**Comment by danm** [comment]
thanks @MartinJohns,
I have updated the question.

It still stands though, I haven't seen other comments about why brackets couldn't be used.

**Comment by RyanCavanaugh** [comment]
See #29526 for discussion of this topic
