### ISSUE TITLE
TS3.6/3.7 regression: template arguments used in unions no longer resolve/narrow

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#34754]
**TypeScript Version:**  3.7.1-rc

**Search Terms:** template argument union

**Code**

```ts
declare class Data {
  string<T>(defaultValue?: string|T): string|T;
}

declare const str: string|undefined;
const x = new Data().string(str);
```

**Expected behavior:**

I'd argue `string`, at least that's what the user intended here.

**Actual behavior:**

In TypeScript version:
* 3.5, `typeof x === string`
* 3.6, `typeof x === unknown`
* 3.7, `typeof x === string|undefined`

**Playground Link:** n/a

**Comment by mprobst** [comment]
I presume this is an intentional change (?) but I could find an existing issue.

**Comment by AlCalzone** [comment]
IMO the inferred type is the only logical one here. You pass a variable of type `string|undefined` to an argument expecting `string|T`, so `T` is inferred as `undefined`. The method returns `string|T`, so I expect the return type to be `string|undefined`.

**Comment by mprobst** [comment]
@AlCalzone note the `?` in `defaultValue?`. The parameter is optional, so its real type is `string|T|undefined`. We're passing `string|undefined` into `string|undefined|T`, so `T` should/could be `never`, I guess?

**Comment by RyanCavanaugh** [comment]
I think this is a bug; `undefined` should indeed be part of the union for the purposes of inference. So `T` = `never` and `x` should be `string`. Maybe this is the smallest code snippet that can produce different behavior in 4 consecutive versions of TypeScript 😶

**Comment by fatcerberus** [comment]
If there's no way to infer `T` then shouldn't it default to its constraint of `unknown` (the TS 3.6 behavior), rather than becoming `never`?

**Comment by fatcerberus** [comment]
I see what you're saying, but from a type-theoretical standpoint I view it as the same kind of question as "Given an empty array `[]`, what is the `T` in `Array<T>`"--and in such case we can say `T` is anything we want because an empty array is always a valid input regardless of what `T` is.

**Comment by nreid260** [comment]
In the Closure compiler we would arrive at the same inference at TS3.7 (`string|undefined') which I believe to be the correct one.

Effectively the question being asked is "what should `T` be inferred as?". When the inference is against a union containing `T` the only consistent thing to do is to distribute over all the union elements. That is `T` is inferred to be the entire type of the passed argument.

As a human, in this case, you probably imagine some kind of "type subtraction" where first we remove the common elements of the argument and parameter unions, before inferring `T`. However, for cases that don't involve finite types, "subtraction" is not well defined. In this example even, what's the correct result if `str` was `'foo'|undefined`?

**Comment by ahejlsberg** [comment]
When someone writes `string | T` it is a strong indication that `T` is intended to be disjoint with `string`. For this reason `unknown` is a bad inference as it encompasses `string`. And `never` is a bad inference for the reason previously outlined. That leaves `string`, which is what we currently infer.
