### ISSUE TITLE
Mark TSServer reponses affected by `updateGraph` calls

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#34774]
TSServer logs currently get very noisy with `updateGraph` calls, but it's not clear what is actually the cause of the work being done there. From discussion with @amcasey, it sounds like a reasonable solution is to have TSServer responses should indicate that they're forcing `updateGraph` calls.

**Comment by amcasey** [comment]
The goal here is not to determine what triggers graph updates, but which operations are affected by `updateGraph` computations (i.e. delays), how often, and to what extent.
