### ISSUE TITLE
Determine Perf Impact of 0-Span Refactoring Requests

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#34784]
In some editors, every cursor movement is followed by a request for possible refactorings. It's possible that these requests are causing delays in other editor operations. We should see whether this is the case, and if it is, understand whether this would impact long-term discoverability of our refactorings.

**Comment by amcasey** [comment]
The change has been implemented in a VS-side (internal) PR, but has not been merged because additional telemetry is required before we can A/B test it appropriately.

**Comment by amcasey** [comment]
The telemetry changes are in-flight, so I think 3.9 is a plausible timeframe for this change (though nothing will actually change in this codebase).

**Comment by jessetrinity** [comment]
#38378 allows us to explicitly request refactors for empty spans.

**Comment by amcasey** [comment]
We ended up just speculatively making the change - precise measurement was impractically expensive.
