### ISSUE TITLE
Types with same name but different type parameters

### ISSUE THREAD

**Issue by mariusschulz** [Microsoft/TypeScript#3478]
I was wondering: Are there any plans to support multiple types with the same name, but with a different number of type parameters, like this (similar to the `Func<T>` type in C#)?

```typescript
interface Func<TResult> {
    (): TResult;
}

interface Func<T1, TResult> {
    (value: T1): TResult;
}

// ...
```

The current error message says that *"all declarations of an interface must have identical type parameters"*.

Or, with https://github.com/Microsoft/TypeScript/issues/1616:

```typescript
type Func<TResult> = () => TResult;
type Func<T1, TResult> = (value: T1) => TResult;
```

**Comment by ahejlsberg** [comment]
No plans to support that. It wouldn't work with classes unless we also introduced name mangling or some scheme for generating multiple constructor functions for the same class name.

If we were going to do anything here I think it would be more along the lines of supporting "type parameter tuples", for example such that you could "spread" a generic tuple type into a function call in a type parametric manner.
```typescript
type Func<...T, R> = (...T) => R;

function invoke<...T, R>(func: Func<...T, R>, args: [...T]): R {
    return func(...args);
}

function foo(s: string, n: number) {
}
invoke(foo, ["hello", 42]);
```
But that's just speculation at this point...

**Comment by mariusschulz** [comment]
Interesting. Thank you for the explanation.

Well, to solve the interface naming collision, one could use different names like `Func1` (for one argument), `Func2` (for two arguments), and so on, although that's not as pretty as in C#. ;-)

**Comment by RyanCavanaugh** [comment]
If we did do something like this, it would probably be generic type argument defaults rather than overloading based on generic arity.
