### ISSUE TITLE
Destructuring array into an object is assignable to an array type

### ISSUE THREAD

**Issue by chrunchyjesus** [microsoft/TypeScript#34780]
**TypeScript Version:**  3.8.0-dev.20191026

**Search Terms:**
- array destructuring object
- array destructure assign

**Code**

```ts
let bar = [1, 2, 3]

let foo: any[] = { ...bar }

console.log(Array.isArray(foo)) // false
```

**Expected behavior:** Typescript errors about type mismatch.

**Actual behavior:** Typescript does neither warn nor error about this and `foo` is no longer an array.

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191026&ssl=1&ssc=18&pln=1&pc=8#code/DYUwLgBARghgThAvBA2gRgDQQExYMwC6AUEaJAGYD2lAXBDAHYCeKBSEA3hAHS+wIBfEgGNKDAM6VQ3YJQDmACgCCcODCbcAluJVqmCqpQCURiAHozEcjGDiQQA

**Related Issues:** #14768

**Comment by RyanCavanaugh** [comment]
See #9726 - TS would need a way to know that the array methods don't end up on `foo`.

**Comment by sebapawlak** [comment]
@RyanCavanaugh is that really about enumerable properties? I believe in a very similar case for objects not arrays the type is correctly inferred: 
````
class Customer {
  constructor(public name: string) {}
  greet() {
    return 'Hello ' + this.name;
  }
}
var customer = new Customer('David');
var clone = {...customer};
// console.log(clone.greet()); //Does not compile
````
[Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDCCuEAuB7AtgUwE7QN4ChppgUA7ZLeYVLACgAd4AjEAS2GlLEwC5oLWpAOYBKPPkLQAvhKJCsGDElpiCRIgqTwspaAHIAEhhAgU+6AGpoSABasIAOi6YA3JJkz8ANzA5giVEwcAF5ODAB3OAD0bFo9ABEwL1YAEz0RN29fYlNSDGhQ3Adi-2QYrCk3AHoq4jIIFBAMB1MhWlAyZvlFZREM6Br4lAwYUhQkOrR6ViaJfCA)

Could we have similar feature for arrays?

**Comment by cscleison** [comment]
yeah i found that too doing a `reduce` and accidentally returning `{...acc}` instead of `[...acc]`. i was puzzled by why TS would be happy about it 😄

**Comment by RyanCavanaugh** [comment]
@sebapawlak TS knows which members of a class are enumerable and which aren't, but we don't have any declaration form for annotated the value-declared type of `Array`. That's literally what I'm talking about re #9726
