### ISSUE TITLE
Provide quick fixes for `useDefineForClassFields` breaks

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#34788]
> Since this targets 3.7.1, I'm going to close this bug. When class fields reaches stage 4, I'll do the final two steps.

_Originally posted by @sandersn in https://github.com/microsoft/TypeScript/issues/27644#issuecomment-542299230_
___

Provide a quick fix to fix these breaks.

**Comment by sandersn** [comment]
Moving to 3.9 until class fields reach stage 4.
