### ISSUE TITLE
Type guard function prevents further type guarding

### ISSUE THREAD

**Issue by ArmorDarks** [microsoft/TypeScript#34798]
**TypeScript Version:**  3.6.3

**Search Terms:**  user type guard function nested guarding

**Code**

```ts
type Test = TestOne | TestTwo;

interface TestOne  {
    type: 'one'
}

interface TestTwo {
    type: 'two'
}

const isTest = (data: unknown): data is Test => true

declare var payload: any

if (isTest(payload)) {
    if (payload.type === 'two') {
        // expected to be `TestTwo`, doesn't work
        payload
    }
}

const castedPayload = payload as Test

if (castedPayload.type === 'two') {
    // expected to be `TestTwo`, suddenly works
    castedPayload
}
```

**Expected behavior:**

`Test` should be type guarded and become `TestTwo` inside the `if` statement.

**Actual behavior:**

`Test` is not type guarded after the check. It remains `Test`.

Strangely enough, if `payload` is manually cast with `as` to be `Test`, type guarding suddenly works.

So, it seems to be tighed some how to the user type guard function `isTest`.

**Playground Link:** [link](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=27&pc=2#code/C4TwDgpgBAKhDOwoF5YOAeQHbQD5sRgHcB7AbgCgKBLLYCAJwDMBDAY2jkW2igG8KUIVFCQAXFADkJHJIoBfKrXrN2ndMRL9Bw0RAmTgpOYopsZiKNXhckqABQATFsBYSArlgDWWEkSwAlBLOrlbwBHYAfCIM7hBUjhBsADYsDNAAbmlQYCwgySQsjhIsWCBKTFD21rb2ufmFjgEB2sJWlXV5BUUAdHooyKiGxi0CbW0A9BNQEAAekGz0jiJaAEbQAAa2mhsANFCOJAhYhlCkDF464zldjVdQiqbmWJZsLIgQjgAKt0UoNw0-u8IhUqm8Pt9fo4+uBoIMhkYSJJRvcpjN5kklisoOsoFsNKQ9lB4O5HIksMkQGcSBd4PdwUsfoDHAogA)

**Related Issues:** 

Similar to the https://github.com/microsoft/TypeScript/issues/26729, but not the same

**Comment by jack-williams** [comment]
Duplicate of #30557

**Comment by ArmorDarks** [comment]
@jack-williams Thanks! Closing this, as it's the same issue.
