### ISSUE TITLE
Regression on inference of "old style" recursive interfaces in 3.7.x

### ISSUE THREAD

**Issue by Jessidhia** [microsoft/TypeScript#34796]
**TypeScript Version:**  3.7.1-rc

**Search Terms:** recursive

**Code**

```jsx
// I'm going to try to reduce this, the report is a WIP
// uses @types/styled-components
import styled from 'styled-components'

// "no overload matches this call"
const Component = styled.div`${({ foo }: { foo: string }) => foo}`
```

**Expected behavior:**

To build the same as in 3.6. While recursive `type`s are a new feature, they shouldn't affect how recursive `interface` `extend`s work.

**Actual behavior:**

"No overload matches this call" _unless_ the `export interface FlattenInterpolation<P> extends ReadonlyArray<Interpolation<P>> {}` in the `@types/styled-components` definition is edited to be `export type FlattenInterpolation<P> = ReadonlyArray<Interpolation<P>>` instead; this edit is sufficient to fix all type errors, but would make the types incompatible with typescript <3.7.0.

<details>

```
No overload matches this call.
  Overload 1 of 3, '(first: TemplateStringsArray | CSSObject | InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | ... 253 more ... | "onTransitionEndCapture"> & { ...; }, Theme>>, ...rest: Interpolation<...>[]): StyledComponent<...>', gave the following error.
    Argument of type '({ foo }: { foo: boolean; }) => boolean' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | "id" | "children" | ... 251 more ... | "onTransitionEndCapture"> & { ...; }, Theme>>'.
      Type '({ foo }: { foo: boolean; }) => boolean' is not assignable to type 'InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | "id" | "children" | ... 251 more ... | "onTransitionEndCapture"> & { ...; }, Theme>>'.
        Types of parameters '__0' and 'props' are incompatible.
          Property 'foo' is missing in type 'Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | "id" | "children" | ... 251 more ... | "onTransitionEndCapture"> & { ...; } & ThemeProps<...>' but required in type '{ foo: boolean; }'.
  Overload 2 of 3, '(first: TemplateStringsArray | CSSObject | InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | ... 253 more ... | "onTransitionEndCapture"> & { ...; } & { ...; }, Theme>>, ...rest: Interpolation<...>[]): StyledComponent<...>', gave the following error.
    Argument of type '({ foo }: { foo: boolean; }) => boolean' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | "id" | "children" | ... 251 more ... | "onTransitionEndCapture"> & { ...; } & { ...; }, Theme>>'.
      Type '({ foo }: { foo: boolean; }) => boolean' is not assignable to type 'InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | "id" | "children" | ... 251 more ... | "onTransitionEndCapture"> & { ...; } & { ...; }, Theme>>'.
        Type 'boolean' is not assignable to type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "css" | "id" | "children" | ... 251 more ... | "onTransitionEndCapture"> & { ...; } & { ...; }, Theme>>'.
```

</details>

**Playground Link:** TODO

**Related Issues:** maybe https://github.com/microsoft/TypeScript/issues/33872 but probably not

EDIT: I've spent about 2h on this but I still am failing to reduce it to a failing case... will probably have to revisit tomorrow. There definitely is something here, though, but I don't know yet what I am missing [in the attempt so far](https://www.typescriptlang.org/play/index.html?jsx=2&ts=3.7-Beta#code/KYDwDg9gTgLgBDAnmYcBiBDANgZ2IgNWwFdUBeOYgOwBNgAzASyuBrgB84rissO562PAChQkWAmSoAklRjAokLBhiMIVADwAFAHxwywuP1nzFEZavVEspQ-zQX5VEwqUq1m3Xc4uzFj2jUAMaWnjrCAPQRcAC2xDjwAEaoGFRwzKaCQagwEHDJcHhY9AC0UAwKwHKM2KLg0PAZClmoDipOvm6h2nqgTjQ4cABKwBg06liIAIJQUBiIGp3m7uo9egDecAC+kdFIKOiOVUv+q7r6w6PjVJMzcwsnK2HhYg2SB4+h1qT63oUwUGYAHM-twYskoH9MLh8N9gHVxPB9qgAMqMGJgLDAT4eC44qwkVCcNowJxojFY-FUXaxeJJFJpJpQFoIPIFIqlcr0SrVWqvCRMlkksnozHYuSuZahOB9KoDS5jCbTWbzDTksVUjY7BFvZFwKmBKghDw9C4ACjAUAgYBwAC44FoAJT6PRUnrCYSCjDZOAopBYmgAYQgGPUVRgACEMHgNHZAzKQP1BharTb7RBEgArYAhZ1kPQZ7MhfjcXgAGjsABUE0m4IWczAK0YAPI1uWDevFijrLZNuBTNu0QYAa3wEHocFSiAuLAAbgphBs7Ga7EZLda7XAzfHZUOt+u0+kqNyoA683op3AAPwOuD2ucKZ0AMjgzbsjvTWYbwm1Xp9lYAC2AGJWD9RAA0NY11CjGM40HeUUw3T8ixgc86y-YtOFLLA+2rXd5U7Rs7FbfCOww+Bu17OwB1IuBR0QcdJyoacKAfSElyMM0mCgBJ7UrYDMRUYA-UBKggRwO55g-X1-VYYNQxYOQYOADRAzLOBK3U5t1KmcJONXARGB4mBbQMoxOH4ikhJE4EJJVRAzOMCU-CeSDum3eDkwPTdmBPM8XSY6cby0O8uGAecoGfV8dD7IwADoEvKXj+3sxZnK6E0PNoxDD18hR-PzQLr1ve9wsfOAX2bHQ9LgaSwIDeTIEUyNoxUtSNK0nSao0ABVTz0JQnQVyMIxuN4xyLIEixhIBWzJIckaRp8dKpQCYJ3J3RN233VMfOPfKnQCy9gtCtiotbF8epigyEripKTJS+40tMDLViyra9xyva-MOwrjpKsKIvOiq4Cumq6tkoMQya8NlNU9TNNfEGeq6n8PToIJlHKOAgnUBJ-nA1g0AgCA+KAkCaHqon1o8OGvvtTZ6BJq97USEmsVSbY0MI9Se3CYRcaofGmYzDBTwoBJCZoYmIAAAwAEnWM1NkSMXtgZ-IxdZ9nRjSLY0NV08nxfAByE2tllj0gA); it's possible trying to simplify React to just being a function call / ignoring object styles to simplify things is also avoiding the bug.

**Comment by jonathaningram** [comment]
@Jessidhia and @RyanCavanaugh I've made a repro for this https://github.com/jonathaningram/ts-34796

I've no idea what's going on though. You can see in the commit (https://github.com/jonathaningram/ts-34796/commit/fbd9755329c35e45584b73be84420cbaa3e29bd8) that caused this to fail it was me adding in `react-router-dom` and converting my `Link` styled component from a wrapper around an anchor to a wrapper around react router's `Link`.

I hope this repro helps—we extracted it from our app into minimal a codebase as possible.

**Comment by RyanCavanaugh** [comment]
The linked repo now compiles without (that) error in TS 5.0.
