### ISSUE TITLE
JSDoc on custom types

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#3480]
While working on updating the node.js definitions on DefinitelyTyped this past weekend, I thought I came up with a very clever idea that turned out not to be very valuable (yet).

In the Node.js `fs` module, many functions take an `encoding` property which is a `string`.  Valid values for `encoding` are standardized across the functions in the `fs` module and look something like this: 'utf8', 'utf16, 'ascii', etc.

I thought - wouldn't it be nice to be able to set up a custom type with JSDoc attached to it, to document how the encoding parameter is supposed to be used.  I assumed this would supplement the tooltips provided by the language service and I wouldn't have to repeat myself by re-describing the valid values to be passed to an `encoding` parameter on *every* function in the declaration file.

I created an encoding type like this (this is a simplified version and not the actual Node API):

```typescript
/** 
 * valid values are 'utf8' | 'utf16' | 'ascii'
 */
export type encoding = string;
```

And changed a function in my definition file to look like this:

```typescript
export function writeToFile(fileName: string, encoding: encoding, content: string): void;
```

I was very pleased to see that when I hovered my mouse over the type in this definition file signature, the JSDoc for the type appeared!

![hoveroncustomtype](https://cloud.githubusercontent.com/assets/3755379/8115582/5b0030a6-104a-11e5-85f2-9b432750cf3c.png)

However, hovering over the parameter name *does not* expose the JSDoc:

![hoveronparametername](https://cloud.githubusercontent.com/assets/3755379/8115619/9e3333c8-104a-11e5-9380-0298e7ee5d1f.png)

Nor does trying to use the parameter when consuming the definition:

![encodingshowsasstring](https://cloud.githubusercontent.com/assets/3755379/8115631/b5b88eee-104a-11e5-8e65-fcc765f3281b.png)

In fact, in both cases, the language service shows the encoding parameter as a `string` and entirely ignores that it's an `encoding` (which of course *is* a string).

PS: I am (now) aware of https://github.com/Microsoft/TypeScript/issues/1003 .  I think that proposal is also awesome, and I think it would be a great solution in my particular case, but I still think the JSDoc on custom types (and the custom types themselves) should be exposed better.

Thanks.

**Comment by mhegazy** [comment]
@JsonFreeman is looking into #1003 now. so this should solve the underlying problem. the issue with type aliases is a design limitation. type aliases are computed aggressively and resolved to what they alais.

**Comment by nycdotnet** [comment]
OK, Thanks Mohamed.
