### ISSUE TITLE
TypeScript "as" keyword is not recognized in Intellisense

### ISSUE THREAD

**Issue by rachelgshaffer** [microsoft/TypeScript#34814]
**Search Terms:**
as, intellisense

**Code**

```ts
var x = this as
```
![image](https://user-images.githubusercontent.com/10291901/67814865-806ee100-fa62-11e9-8a46-bd28fd1773a3.png)

**Expected behavior:**
If you type `as` like above, Intellisense should recognize it as an acceptable keyword
```ts
var x = this as HTMLInputElement;
```

**Actual behavior:**
Intellisense suggests `async` so you end up with
```ts
var x = this async HTMLInputElement;
```

**Related Issues:** 
[Visual Studio feedback ticket](https://developercommunity.visualstudio.com/content/problem/794138/typescript-as-keyword-is-always-replaced-by-intell.html)

**Comment by minestarks** [comment]
This seems to repro with `if` as well. It's a poor experience when VS autocompletes partial matching identifiers. 

User feedback:  https://developercommunity.visualstudio.com/content/problem/828762/javascript-intellisense-replaces-exactly-typed-key.html
