### ISSUE TITLE
Default export is not re-exported in type information

### ISSUE THREAD

**Issue by bryanforbes** [Microsoft/TypeScript#3481]
Given a module `one` which exports a default function, a module `two` that re-exports everything in `one` (`export * from './one'`), and a module `three` which attempts to import the default function from `two`, the compiler outputs an error that `two` has no default exports. I have put this into a gist: https://gist.github.com/bryanforbes/12c9e9705b27aa2b7a6a.

From my reading of the spec, the `__exports` function emitted in `two.js`, and also the output of Babel for similar situations, the default export from one module should be re-exported when `export * from './one'` is done. The emitted JavaScript from the compiler runs and correctly outputs `"one"`, however the compiler doesn't see `two` as having a default export.

**Comment by mhegazy** [comment]
This is correct according to the [ES6 spec - section 15.2.1.16.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-resolveexport): 
> 6. If SameValue(exportName, "default") is true, then

>     Assert: A default export was not explicitly defined by this module.
>     Throw a SyntaxError exception.
>     **NOTE A default export cannot be provided by an export *.**

The emitted code does not try to filter default out when exporting *, but the design time error should be sufficient to catch the issue.

**Comment by bryanforbes** [comment]
Thank you! I missed that in the spec.

**Comment by bryanforbes** [comment]
This can be closed if you'd like. I'm not sure if I'm supposed to close it or not.

**Comment by mhegazy** [comment]
thanks!
