### ISSUE TITLE
Using enum values as property values in interfaces causes issue with union types

### ISSUE THREAD

**Issue by deser** [microsoft/TypeScript#34829]
Possibly this is a duplicate of https://github.com/microsoft/TypeScript/issues/33243 but I'm not sure.
Sorry, if this is a duplicate.

**TypeScript Version:**  3.7-Beta

**Search Terms:**  union enum value

**Code**

```ts
enum klad {
    ad = 'ad',
    bd = 'bd' 
}

interface one {
    a: klad.ad,
    b?: number,
    c?: boolean,
}

interface two {
    a: klad.bd,
    b?: boolean,
    d?: number
}

type combined = one | two;

const fn = (b: combined): void => { }

const val = { a: klad.ad, b: 3 };

fn(val);  // errors
```

**Expected behavior:**
It's possible to use enum values as keys in interfaces which then are combined in unions. 

**Actual behavior:**
Error shows:
```
Argument of type '{ a: klad; b: number; }' is not assignable to parameter of type 'combined'.
  Type '{ a: klad; b: number; }' is not assignable to type 'two'.
    Types of property 'a' are incompatible.
      Type 'klad' is not assignable to type 'klad.bd'.(2345)
```

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.7-Beta#code/KYOwrgtgBA1gNgQwCZQN4CgpasqBeKAcmUIBpNsAjFAw6wqdAX3XQEsQAXYAJwDMEAY2BQA9iBEZsOAFyxESAHTJy0ygH454CJV6rsgzVEqjRcYAhDkW7LrwHConAO6i0FLAjnxki6vqwNORMzCysPKCQjbV0eZlZOAE8ABxFBUR0OYBoxCSgAHydXAG5WdJAAZ04oPhB8KAAKSjl0zIkkAEo5ADdRNhoAPjQoG3KqqG6EOHrUWXlfFWM5AGYR0vRahsm4DuKgA

**Related Issues:**  Maybe https://github.com/microsoft/TypeScript/issues/33243

**Comment by fatcerberus** [comment]
Changing the assignment to `val` to:
```ts
const val = { a: klad.ad, b: 3 } as const;
```
fixes it.  The problem is that values inside of an object literal are automatically widened, so `.a` ends up being of type `klad` rather than the literal type `klad.ad`.  TS is then unable to discriminate between the union members.  Adding `as const` prevents the widening.
