### ISSUE TITLE
autocompletion failing in 3.7.1-rc

### ISSUE THREAD

**Issue by chandu0101** [microsoft/TypeScript#34825]
**TypeScript Version:**  3.7.1-rc

**Search Terms:**

**Code**

```ts

export type GeMethodsForType<T, G extends string> = { [K in keyof T]:
    T[K] extends () => any ? { name: K, group: G, } : T[K] extends (s: infer U) => any ? { name: K, group: G, payload: U } : never }[keyof T];


class Sample {
    count = 0;
    books: { name: string, year: number }[] = []
    increment() {
        this.count++
        this.count++
    }

    addBook(book: Sample["books"][0]) {
        this.books.push(book)
    }
}
export declare function testIt<T, G extends string>(): (input: any, method: GeMethodsForType<T, G>) => any


const t = testIt<Sample, "Sample">()

const i = t(null, { name: "addBook", group: "Sample", payload: { } }) // auto completion for payload

```

**Expected behavior:**
Propeties of payload should come in autocompletion
**Actual behavior:**
No autocompletion
**Playground Link:** [play ground nightly](https://www.typescriptlang.org/play/index.html?ts=Nightly#code/LAKApgHgDg9gTgFwAQIJ5TEg4mAsmBACxgBMBnAMXgBV0wAeagGmyUgTADtykyE4AlpwDmAPiQBeJAG8kAbQDSSIUgDWYVDABmSagF0AXKCQndivWwgduZJAAoAlJPEBDTqiQB+GUk4uAtmAGSAoswnAwAK5QwVgsAL5IwdTmltY8dmTBQlpgcEgAqk4Sru5ePn6BwaFI4VEx2CxQLqgANjAuJMEFSInBnGAAbnm9cuqaOvoA3KCzIADGrS5ktgDKAVCtmNLGpvNRnMhSAAwzIKZIAEYwMKpZFQFBvPxCwiyoYC5w-ZH+lyPxOQWKRA3YmITzOBgQKHRwyMEXFCEARkAB0+0ihwA1FiERciCj0QcEDiEfE5hdOiQAEI3VR2a63YLrfybMByABEjLuHL0cmOeicO3OiJMBLR3LRUEiZEIDLpDjJoHJ4Gg8GQJDAiy+mC0mPmCAEME4KDAfAAkghGCwsGkuDw+IIRKJHME7EJpQhgm5UCxAkRSLE8ARiOQqHBaBhrdhRMVSqg5qB9pw+ChJKaLVaWWyWBzs1sOS7FSAk8bUwJ0wg7JxIq1WixZJUnhyqbTbhywhFosE8xsC00Wu1OsFZIl4sWgA)

Working fine in 3.7 beta and 3.6.x

[play ground 3.7 beta](https://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/LAKApgHgDg9gTgFwAQIJ5TEg4mAsmBACxgBMBnAMXgBV0wAeagGmyUgTADtykyE4AlpwDmAPiQBeJAG8kAbQDSSIUgDWYVDABmSagF0AXKCQndivWwgduZJAAoAlJPEBDTqiQB+GUk4uAtmAGSAoswnAwAK5QwVgsAL5IwdTmltY8dmTBQlpgcEgAqk4Sru5ePn6BwaFI4VEx2CxQLqgANjAuJMEFSInBnGAAbnm9cuqaOvoA3KCzIADGrS5ktgDKAVCtmNLGpvNRnMhSAAwzIKZIAEYwMKpZFQFBvPxCwiyoYC5w-ZH+lyPxOQWKRA3YmITzOBgQKHRwyMEXFCEARkAB0+0ihwA1FiERciCj0QcEDiEfE5hdOiQAEI3VR2a63YLrfybMByABEjLuHL0cmOeicO3OiJMBLR3LRUEiZEIDLpDjJoHJ4Gg8GQJDAiy+mC0mPmCAEME4KDAfAAkghGCwsGkuDw+IIRKJHME7EJpQhgm5UCxAkRSLE8ARiOQqHBaBhrdhRMVSqg5qB9pw+ChJKaLVaWWyWBzs1sOS7FSAk8bUwJ0wg7JxIq1WixZJUnhyqbTbhywhFosE8xsC00Wu1OsFZIl4sWgA)

Looks like its getting confused when some properties doesn't contain `payload` property in this case `increment` method , if i change GeMethodsForType to 

```ts
export type GeMethodsForType<T, G extends string> = { [K in keyof T]:
    T[K] extends () => any ? { name: K, group: G, payload?:undefined} : T[K] extends (s: infer U) => any ? { name: K, group: G, payload: U } : never }[keyof T]; // payload added  empty arg methods
```
now autocompletion working fine in 3.7.1-rc  :s

**Comment by andrewbranch** [comment]
Update: fixed my simplified test case, but the original repro is still failing.
