### ISSUE TITLE
TypeScript JSDoc auto complete snippet doesn't work when autoClosingBrackets is set to "never"

### ISSUE THREAD

**Issue by SetTrend** [microsoft/TypeScript#34828]
JSDoc snippets won't appear in Visual Studio Code when the TypeScript option `autoClosingBrackets` is set to `never`. This option, however, is not supposed to correlate with snippet insertion.

### TypeScript Version:
3.6.4

### Search Terms:

I was invited by Matt Bierner from the VS Code team to open this issue here.

### Steps to Reproduce:

1. Open a TypeScript project in Visual Studio Code
1. Set `"javascript.suggest.completeJSDocs": true`
   and `"typescript.suggest.completeJSDocs": true`
1. Set `"editor.autoClosingBrackets": "never"`
1. Open a TypeScript file and create a function.
1. Position cursor above function definition and hit `/**`

### Expected result:
A JSDoc auto complete snippet should appear and fill in the appropriate fields.

### Actual result:
Nothing happens.

![TypeScript JSDoc Auto completion](https://user-images.githubusercontent.com/9283914/67019822-8927f480-f0fd-11e9-8a82-738304b8497b.gif)

### Related Issues:
- /microsoft/vscode/issues/82776
- /microsoft/vscode/issues/82814
- #24468

**Comment by RyanCavanaugh** [comment]
The `autoClosingBrackets` setting is a red herring. When the caret is asking for completions, the function below it is part of a comment and not something we'd provide completion for. You can manually close the comment and then request completion to get the template.
