### ISSUE TITLE
tsc outputs .js and .js.map files to incorrect location

### ISSUE THREAD

**Issue by theaussiepom** [microsoft/TypeScript#34821]
**TypeScript Version:**  3.7.4
**Node Version:** 10.16.3 (64 bit)

**Search Terms:**
outdir (with bug tag)
**Code**

When the outdir is set to "." and all typescript files are located in one subfolder, the tsc outputs the files to the root folder.
e.g. tsconfig.json file is located in the "spec/features" folder, and typescript files are located in "spec/features/step-definitions" folder.
We have many other repos configured identically from a boiler plate. This is the only repo where this problem has been identified and the only repo where we have only one subfolder containing the ts files.

All references from the step definitions are made to dist, not to src. No other directory structure references are made in the code.

The "spec/features/tsconfig.json" file:
```json
{
  "extends": "../../src/tsconfig.json",
  "compilerOptions": {
    "declaration": false,
    "esModuleInterop": true,
    "outDir": ".",
    "typeRoots": [
      "../../node_modules/@types",
      "../../vendor/definitions"
    ]
  },
  "exclude": [],
  "include": [
    "**/*.ts"
  ]
}
```

The "src/tsconfig.json" file:
```json
{
  "compilerOptions": {
    "declaration": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "jsx": "preserve",
    "module": "commonjs",
    "outDir": "../dist",
    "sourceMap": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "strict": true,
    "stripInternal": true,
    "target": "es2017",
    "lib": [
      "es2017"
    ],
    "typeRoots": [
      "../node_modules/@types",
      "../vendor/definitions"
    ]
  },
  "exclude": [],
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ]
}
```

**Expected behavior:**
When outdir is set to ".", the output files are generated in root location of tsconfig.json
**Actual behavior:**
When outdir is set to ".", the output files should be generated next to the respective .ts files
**Playground Link:** 
-
**Related Issues:** 
No

**Comment by fatcerberus** [comment]
By default TS treats the root of the project as the longest common subpath of all files being compiled, not the location of the `tsconfig.json` as you probably expect.  The option you're looking for to control this is `rootDir` (note: **NOT** `rootDirs`!).

What `rootDir` does is best explained in the PR that implemented it:
https://github.com/microsoft/TypeScript/pull/2772

**Comment by theaussiepom** [comment]
This has resolved the issue. Thank you for the speedy response.
