### ISSUE TITLE
Implement interface quick fix should insert new interface implementation after constructor  

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#34841]
From https://github.com/microsoft/vscode/issues/83662

**TypeScript Version:**  3.8.0-dev.20191026

**Search Terms:**
- Quick fix
- implement interface

**Repo**
For the code:

```ts
interface IFoo {
    bar(): void;
}

class Foo implements IFoo {
    private x: number = 1;
    constructor() {}
}
```

1. Run the implement interface quick fix on `Foo`

**Expected behavior:**
Added method `bar` is inserted after the constructor and properties:

```ts
interface IFoo {
    bar(): void;
}

class Foo implements IFoo {
    private x: number = 1;
    constructor() { }
    bar(): void {
        throw new Error("Method not implemented.");
    }
}
```

**Actual behavior:**
Added method is inserted before the constructor and properties:

```ts
interface IFoo {
    bar(): void;
}

class Foo implements IFoo {
    bar(): void {
        throw new Error("Method not implemented.");
    }
    private x: number = 1;
    constructor() {}
}
```

**Comment by mjbvz** [comment]
Removing priority label for now so that it shows up in the TS inbox tracking queries. This is important to some VS Code team members however

**Comment by RyanCavanaugh** [comment]
Thanks @mjbvz
