### ISSUE TITLE
Generic inference different between equivalent function expression and shorthand method in object literal (vol 2)

### ISSUE THREAD

**Issue by iKBAHT** [microsoft/TypeScript#34849]
**TypeScript Version:**  3.6.3 - 3.8.0-dev.20191031

**Search Terms:** parameter, inference, order, generic, function expression, function declaration

**Code**

```ts
interface IData {
  bar: boolean
}

declare function test<TDependencies>(
  getter: (deps: TDependencies, data: IData) => any,
  deps: TDependencies,
): any 

const DEPS = {
  foo: 1
}

// negative test
test(
  (deps, data) => ({
    fn1: function() { return deps.foo },
    fn2: data.bar
  }),
  DEPS
);

// positive tests
test(
  (deps: typeof DEPS, data) => ({
    fn1: function() { return deps.foo },
    fn2: data.bar
  }),
  DEPS
);

test(
  (deps, data) => ({
    fn1: () => deps.foo,
    fn2: data.bar
  }),
  DEPS
);

test(
  (deps, data) => {
    return {
      fn1() { return deps.foo },
      fn2: data.bar
    }
  },
  DEPS
);

test(
  (deps) => ({
    fn1() { return deps.foo },
    fn2: 1
  }),
  DEPS
);
```

**Expected behavior:** `deps` should be inferred as `typeof DEPS` in negative test

**Actual behavior:** `deps` inferred as unknown

**Playground Link:** [link](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=56&pc=3#code/JYOwLgpgTgZghgYwgAgJIBE5jsg3gWAChlkAjOKALjIHsaAbCOEIgXyKIBMIF6KUYAVxAIwwGiGSQAzmAA8AFXQQADhBDcRwCNIB8ACiIkA5hDCQqyfdxXTqS1es0Jt0gDTJOWONQzeAlMgAvLrIzACebkaeqnbIDmoa6i46UYT+1BHIHIQIErLI6ACiAAoAysF40TB01ACMbDkA9E3IIBDGWMAAbigyYET9hsRWNu6eAcGh+gQjJDAgddRCImIS+oG4yFBmglCSYwB0NTTIrGkk8yAATNRe2IfkUNGs-heFpWVE-gDcza0qGjSYBiXpSHRgaSDCHDEjWWLUMDhNQ0GAfcoee5wQIhKyzS7IBZLQnCUTiEAbPDbXb7GK2Y50M7vK63CYPJ4vN7RYrlb5-QjQ2Sw0axTGTXEzaJXYmU3FHE7Mwk3O7eR4UTnvHlfdL8wVgYXw2xi7A40L4y47MB7STmglEylbS3WunSBmnc5Sy4LVlYtXPOZnF6az58nJDaKG6SmvGe+2balW2nyxkegPe+oa7khnVAA)
**Related Issues:**  I guess, the fix of #32230 bug led to the appearance of this bug

**Comment by AnyhowStep** [comment]
Maybe somewhat related?
https://github.com/microsoft/TypeScript/issues/14829

If non-inferential usage is implemented, this might be a perfect use case

**Comment by ahejlsberg** [comment]
This worked in 3.5 and was broken by #25937. I'm thinking it is possible to recognize cases where the new logic in #25937 can be circumvented because it will have no effect anyway.
