### ISSUE TITLE
Logically Defined Operator

### ISSUE THREAD

**Issue by mrttrifork** [microsoft/TypeScript#34847]
## Search Terms

optional chaining, null coalescing,  logically defined, if

## Intro
Inspired by optional chaining and null coalescing operator, i realized that if statements really needed a logically defined operator.
 
## Suggestion

Currently if's falsy check a value to determine if the inner block should be executed

The solution to check for logically defined value are

1. `if(value != null)`
2. `if(value !== undefined && value !== null)`
 
Solution 1 is a very elegant solution, `!=` but it does not tell the entire story. I like to be explicit for other developers, because they might not know that `undefined` is checked as well.

Therefore it would be good to have a logically defined operator. My initial thought was that optional chaining or the null coalescing operator only had a left-hand side expression.

`if(value?)` or `if(value??)`

becomes

`if(value !== void 0 && value !== null)`

### Operator problem
The problem with using Optional chaining and Null coalescing operator is that they are already clearly defined, so the it should probably be another operator.

## Examples

In our examples we will be using the Optional chaining

```typescript

interface data {
  aNumber?: number;
}
const data1: data = {aNumber: 0};
const data2: data = {};

if(data1?.aNumber?) {
   // code will be executed
}

if(data2?.aNumber?) {
   // code will not be executed
}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
  * [ ] Provide a structuring mechanism for larger pieces of code.
    * [ ] Optional Chaining
    * [ ] Null Coalescing Operator

**Comment by Barbiero** [comment]
Won't this be easily solved by the idiom `if(value ?? false)`? Of course, it's a bit hard to read but I feel like this would be more appropriate as a TC39 proposal after null coalescing is stage 4 than as a typescript feature.

**Comment by mrttrifork** [comment]
No

```typescript
const zero = 0;

if(zero !== void 0 && zero !== null ? zero : false){
  // Code is not executed, sinnce 0 is a falsy value
}
```

**Comment by Barbiero** [comment]
> No
> 
> ```ts
> const zero = 0;
> 
> if(zero ?? false) {
>   // Code is not executed, since 0 is a falsy value
> }
> ```
> 
> becomes
> 
> ```ts
> const zero = 0;
> 
> if(zero !== void 0 && zero !== null ? zero : false) {
>   // Code is not executed, since 0 is a falsy value
> }
> ```

I see, but in that case you could as easily do `if(value ?? null !== null)` instead. I agree that it's bothersome(though it's better than comparing to undefined and null) but I still feel that a new operator would be a ECMAScript proposal instead of of a typescript feature.

**Comment by RyanCavanaugh** [comment]
This is something that should be proposed to the ECMAScript committee; as the template indicates, we are deferring runtime things to them
