### ISSUE TITLE
Error types (effect typing for error handling)

### ISSUE THREAD

**Issue by TheCactusBlue** [microsoft/TypeScript#34848]
## Search Terms

Effect Types, Errors, Error Types

## Suggestion

Allows functions to specify the types of errors, as well as the typesystem to check for them.

- The errors are infectious, which means that other functions calling the function with error effects will also have the same effects.
- `throws` (not to be confused with `throw` keyword) allows you to explicitly specify the error type, which may be useful for type definitions.
- This rule has exceptions - firstly, if the function with the error type is wrapped around a try-catch block and handled appropriately.
- There could also be an error silencing operator, which is meant to mark errors that isn't supposed to happen, and is meant to bubble up the error to the top of the function, similar to `panic` in languages such as Go and Rust. operator can possibly be `!`, to keep in line with null assertion operator.

## Use Cases
- try-catch block has stronger typing, instead of just `Error`, which allows for better autocompletion.
- Cases where the errors thrown by function is known (e.g. APIs, database drivers) - as the compiler will be capable of checking for error types.

## Examples

```ts

// implicitly has a error type of MyError
function myFunction(a: bool) {
  if (a) {
    throw new ErrorA();
  }
}

// Now anotherFunction has same error types as myFunction, plus its own error types
function anotherFunction(b: bool) {
  myFunction(b);
  if (b) {
    throw new ErrorB();
  }
}

// Errors can be explicitly specified
function explicitErrors() throws ErrorA|ErrorB {
  ...
}

// If a function is called in a try block, its error types will not be passed.
// However, error caught by the catch will have a type equal to union type of all errors emitted by the try block.
function errorCatching() {
  try {
    explicitErrors()
  } catch (err) {
    ...
  }
}

// this function will not have an error type, as the error is silenced
function errorSilencingExample() {
  throw new SilencedError()!;
}
```

**Comment by RyanCavanaugh** [comment]
Duplicate #13219
