### ISSUE TITLE
keyof conditional type w/ infer is not assignable to itself 

### ISSUE THREAD

**Issue by mprast** [microsoft/TypeScript#34856]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
infer keyof conditional mapped type
**Code**

```ts
type BugDemo<T, K extends keyof T> = {
  [P in K]: BugDemo<
    T[P] extends Array<infer R> ? R : { bad: string },
    keyof (T[P] extends Array<infer R> ? R : { bad: string })
  >
}
```

**Expected behavior:**
Compiles with no issue. In my real-world use case, I was passing `K` in vs. doing `[P in keyof T]` because I wanted to have a non-distributive mapped type, a la `Pick`.

**Actual behavior:**
Throws the error shown below - the gist of it appears to be that typescript is evaluating `keyof (T[P] extends Array<infer R> ? R : { bad: string })` two different ways when trying to validate the recursive call to `BugDemo`, the result being Typescript's claim that the `keyof` type is not assignable to _itself_. This seems wrong to me, especially given that the conditional doesn't contain any references to `never` or the like. 

``` 
Type 'keyof (T[P] extends (infer R)[] ? R : { bad: string; })' does not satisfy the constraint 'keyof (T[P] extends (infer R)[] ? R : { bad: string; })'.
  Type 'string | number | symbol' is not assignable to type 'keyof (T[P] extends (infer R)[] ? R : { bad: string; })'.
    Type 'string' is not assignable to type 'keyof (T[P] extends (infer R)[] ? R : { bad: string; })'.
      Type 'string' is not assignable to type 'never'.
        Type 'keyof (T[P] extends (infer R)[] ? R : { bad: string; })' is not assignable to type 'never'.
          Type 'string | number | symbol' is not assignable to type 'never'.
            Type 'string' is not assignable to type 'never'.
```

Moving `keyof` to a completely different type fixes the error:

```typescript
type BugDemo<T, K extends keyof T> = {
  [P in K]: BugFix<T[P] extends Array<infer R> ? R : {bad: string}>
}

type BugFix<T> = BugDemo<T, keyof T>;    
```

**Playground Link:**
[the bug](http://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAQgrgcwCIQLYHsA8AVANFAaSggA9gIA7AEwGcoBrCEdAMymwD4oBeKAbwBQUKAG0AClACWFQgF0AXLEQoMmIcPbjZxMpVpQAggCcjAQxCZpLCEagAlLgH57URXygAjU1UU1gR6QQoAF9cdWFGZjYACmwtHXJqOmMzCysbeycXN09vX39AkIBKdQ4BYKA)
[the workaround](http://www.typescriptlang.org/play/?ssl=5&ssc=42&pln=4&pc=1#code/C4TwDgpgBAQgrgcwCIQLYHsA8AVANFAaSggA9gIA7AEwGcoBrCEdAMymwD4oBeKAbwBQUKAG0AClACWFQgF0AXLEQAxSSRzjZxMpVpQAggCdDAQxCZpLCIagAlLgH47URXwBGJqoprBD0hAC+HAIBAgKgkEoIquqcPFEoGDj4jMxsnADcwsJAA)

**Related Issues:**

**Comment by jack-williams** [comment]
Looks to be fixed in the beta version on the playground:

[link](http://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/C4TwDgpgBAQgrgcwCIQLYHsA8AVANFAaSggA9gIA7AEwGcoBrCEdAMymwD4oBeKAbwBQUKAG0AClACWFQgF0AXLEQoMmIcPbjZxMpVpQAggCcjAQxCZpLCEagAlLgH57URXygAjU1UU1gR6QQoAF9cdWFGZjYACmwtHXJqOmMzCysbeycXN09vX39AkIBKdQ4BYKA)

**Comment by mprast** [comment]
ah, my mistake. Thanks for the response!
