### ISSUE TITLE
typescriptServices.js is not "strict mode" friendly

### ISSUE THREAD

**Issue by Yellowmat** [Microsoft/TypeScript#3486]
I am using typescript for a project where strict mode is enabled and I have some problem using typescriptServices.js because it is not "strict mode" friendly. As an example, "arguments" must not be used as an identifier ...

This is not a big deal, hope this issue will soon be fixed ;)

**Comment by mhegazy** [comment]
Pleas feel free to send PRs to fix these issue.

**Comment by DanielRosenwasser** [comment]
Hey @Yellowmat, @ShyykoSerhiy sent us a fix which should be in our `master` branch. Give it a try and let us know how it works out.

**Comment by Yellowmat** [comment]
Hi @DanielRosenwasser !

Thanks for the fix !

I'll test this ASAP, no doubt it will work ;)
