### ISSUE TITLE
Non-null type assertions shouldn't affect optional chaining

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#34875]
cc @ahejlsberg 

**TypeScript Version:**  3.7.x-dev.20191101

**Search Terms:**

**Code**

```ts
const a = document.querySelector('_')?.textContent!;
```

**Expected behavior:**

Type of a is string | undefined.

**Actual behavior:**

Type of a is string.

This means `document.querySelector('_').textContent!` is valid and these are the equivalent to `document.querySelector('_')!.textContent!`.

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191101&ssl=1&ssc=53&pln=2&pc=23#code/MYewdgzgLgBAhjAvDAJiYBXAtgUzFAOgEcMcAnATwGUcAbHYKEMgCgHIB9NgSgH4CoOAB5QAwuEH4AhAG4gA

**Related Issues:**

**Comment by falsandtru** [comment]
Another case.

```ts
// b must be `ChildNode | 0` but actualy `ChildNode`
const b = document.querySelector('_')?.firstChild! ?? 0;
```

**Comment by AnyhowStep** [comment]
![image](https://user-images.githubusercontent.com/5655961/68072645-55380a80-fd5e-11e9-9d77-cc378718c0df.png)

**Comment by fatcerberus** [comment]
Memes aside, if the goal here is simply to remove the null possibility *for `textContent` only*, that's probably going to be difficult in general because `!` applies to the entire expression and the compiler can't distinguish between `T | undefined | undefined` and `T | undefined`.  By the time the compiler sees the `!`, the two levels of null possibility have already collapsed down to one.

**Comment by RyanCavanaugh** [comment]
This is the same as if you had written
```ts
const _a = document.querySelector('_')?.textContent;
const a = _a!;
```

IOW `!` applies to the entire operand expression, not just the property access

**Comment by falsandtru** [comment]
Can't you notice the problem that there is no way to infer the actual type `string | null` from `document.querySelector('_')?.textContent` even when using `!`? `!` became useless with many cases using optional chaining.

**Comment by nmain** [comment]
Optional chaining covers common use cases with terse expressions.  If you really need to go deep detail about each part of your expression; if it's important for your use case to distinguish when `querySelector` returns `undefined` vs when `textContent` returns `null`; then just break it out into separate statements and test each one.

**Comment by RyanCavanaugh** [comment]
@falsandtru you'll have to get a time machine and take it up with TC39 in 2017, I guess. `?.` won't propagate a `null` value and TS represents that

**Comment by falsandtru** [comment]
@RyanCavanaugh Then I just replace `null` with `undefined`. Anyway the essential problem is the same. When developers introduce optional chaining, currently TypeScript forces developers to explicitly write the expected type in some cases like `document.querySelector('_')?.textContent as string | undefined`.

*The question is TypeScript won't resolve the new problem that optional chaining sometimes makes type inference to be impossible to infer the actual type?*
