### ISSUE TITLE
Question: Optional chaining, nullish coalescing downlevel and code coverage

### ISSUE THREAD

**Issue by HitalloExiled** [microsoft/TypeScript#34872]
## Search Terms
Optional chaining, nullish coalescing

## Question
Today I decided to try version 3.7 on some files of my code base.

I immediately started replacing all **null/undefined** checks with the new **optional chaining** and **nullish coalescing** operators and ran some tests to see how this would impact my coverage.

I can't say that I was surprised to note that access to some methods that would knowingly never return **undefined** would generate some uncovered branches.

Analyzing the emitted code I found that this is due to the conditional **OR** operator used on code emmited by **optional chaining**, which frankly I already expected for optimization reasons. And I was kind of ready to start spreading dozens of **// istanbul ignore else** comments across all code that would never result in **undefined**.

```js
// original
this.dependencies.get(key)?notify(value);

// emitted 
(_a = this.dependencies.get(key)) === null || _a === void 0 ? void 0 : _a.notify(value);
```

What surprised me was that in the case of the nullish coalescing operator, the **AND** conditional operator was used in the emitted code. Which helps achieve 100% coverage even when the valuation never returns *undefined*.

```js
const reactor = value[REACTOR] ?? new Reactor();

const reactor = (_a = value[symbols_1.REACTOR], (_a !== null && _a !== void 0 ? _a : new Reactor ()));
```

### My question is: ###
What is the reason for this divergence between null/undefined checks?
Could using the **OR** operator really result in any significant optimization?
Would it be possible to use operator **AND** in both scenarios and save us from redundant assertions just to satisfy code coverage?

## Use Cases
Test coverage

## Examples
```ts
const map = new Map<string, Function>();

map.get("foo")?.("Do Something");

// emmited
const map = new Map();

(_a = map.get("foo")) === null || _a === void 0 ? void 0 : _a("Do Something");
//                                ^^^^^^^^^^^^^   never return undefined, else branch not covered
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
What about the case where it always returns `undefined`?

**Comment by HitalloExiled** [comment]
Analyzing better here I realized that even in expressions that always result in null or always result in undefined all branches should be reached.

```ts
null === null || null  === void 0 ? void 0 : 0;
// True on first branch, Break and returns alternate

undefined === null || undefined === void 0 ? void 0 : 0;
// False on first branch, True on second branch. Break and returns alternate

0 === null || 0 === void 0 ? void 0 : 0;
// False on first branch, try second branch, False on second branch. Break and returns consequent. All branches reached.
```

I also just noticed now that the checks are equivalent:

```ts
0 === null || 0 === void 0 ? void 0 : 0;
0 !== null && 0 !== void 0 ? void 0 : 0;
```

**Comment by AnyhowStep** [comment]
Are you sure those two checks are equivalent?
```
0 === null || 0 === void 0 ? void 0 : 0; // 0
0 !== null && 0 !== void 0 ? void 0 : 0; // undefined
```

**Comment by HitalloExiled** [comment]
@AnyhowStep 

Sorry, was a mistype.

The correct would be:
```ts
0 === null || 0 === void 0 ? void 0 : 0;
0 !== null && 0 !== void 0 ? 0 : void 0;
```
