### ISSUE TITLE
TypeScript infer wrongly copying 'this'

### ISSUE THREAD

**Issue by maciejsikora** [microsoft/TypeScript#34878]
**TypeScript Version:**  3.7-Beta

**Search Terms:** copy this, spread this

**Code**

```ts
class A {
  method1() {
     return 'method1'
  }
  copy() {
    return { ...this };
  }
}
const a = new A();
a.copy().method1(); // runtime error
```

**Expected behavior:**
Return of `a.copy()` should not consider having prototype methods.

**Actual behavior:**
Return of `a.copy()` has a type `this`

**Comment by DanielRosenwasser** [comment]
Initially thought the bug was the runtime behavior and not the type. I thought that generally speaking, method-declared values weren't included on spreads @sandersn.

**Comment by fatcerberus** [comment]
> I thought that generally speaking, method-declared values weren't included on spreads

No, they definitely are.  See e.g.
* https://github.com/microsoft/TypeScript/issues/34780#issuecomment-548068666
* https://github.com/microsoft/TypeScript/issues/28801
* https://github.com/microsoft/TypeScript/issues/31809

And probably some others.
