### ISSUE TITLE
Cannot integrate TypeScript_15beta_Dev12 with VS 2013

### ISSUE THREAD

**Issue by Mustafa-Sadikot** [Microsoft/TypeScript#3487]
The installer runs completely but it does not integrate with VS 2013. I tried all the previous versions but in vain. I looked in https://github.com/Microsoft/TypeScript/issues/1162 thread and it still does not seem to be fixed in 1.5 Beta version. Can you please help me out with this?

**Comment by DustinEwan** [comment]
I'm currently having the same issue w/ VS 2015 and a coworker is experiencing this with VS 2013.

**Comment by mhegazy** [comment]
@Mustafa-Sadikot and @DustinEwan do you have other versions of TypeScript installed on these machines? if so what are they? also can you try uninstalling TypeScript and reinstalling it again, and share the installer logs. these should be in `%TEMP%\dd_Typescript*.log`

**Comment by paulvanbrenk** [comment]
what do you mean, does not integrate? What is working and what is not?

What files are in the following folder:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript

Do you have any other extensions installed, like resharper?

Do you see the TypeScript extension in the Add/Remove Programs dialog in Windows?

**Comment by mhegazy** [comment]
@Mustafa-Sadikot and @DustinEwan are you still running into this issue?

**Comment by paulvanbrenk** [comment]
Closing this until we have more info.
