### ISSUE TITLE
Invalid `await` is generated in constructor when initializing field

### ISSUE THREAD

**Issue by brianush1** [microsoft/TypeScript#34887]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** invalid await in constructor

**Code**

```ts
async function bar() {
	return 2;
}

async function foo() {
	return new class {
		baz = await bar();
	};
}
```

**Expected behavior:**
Error, as `await` cannot be used in a constructor

**Actual behavior:**
Invalid JS code is generated, as a constructor using `await bar();` is generated, and this is not allowed in JS

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191101&ssl=1&ssc=1&pln=2&pc=11#code/IYZwngdgxgBAZgV2gFwJYHsIwEbAE4AUAlDAN4BQAkHgKbIJ5YBMA3OQL7nmiSyIoYscdOmJkqteoxgQaAdxhQANqBDjKlXAC8YAXhjA5wVMhz5ibSuzbsgA 

**Related Issues:** None

**Comment by fatcerberus** [comment]
In fact this is an outright syntax error in JavaScript; removing the `await` fixes the error below:

```
D:\temp>node -v
v13.0.1

D:\temp>node foo.js
D:\temp\foo.js:7
                baz = await bar();
                            ^^^

SyntaxError: Unexpected identifier
[90m    at wrapSafe (internal/modules/cjs/loader.js:891:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:941:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:822:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:730:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12)[39m
[90m    at internal/main/run_main_module.js:16:11[39m
```

(note: node.js v13 supports class fields)
