### ISSUE TITLE
Feature Proposal: Optional Curly Braces

### ISSUE THREAD

**Issue by EdSaleh** [microsoft/TypeScript#34881]
Hello Everyone,

I would like to propose allowing curly braces to be optional in JavaScript/TypeScript. 

Example:

```
function foo(){
bar()
}
```

can be written as:

```
function foo():
bar()
```
Or #2:
```
function foo():
{bar()}
{bar2()}
```
Or #3:
```
function foo():
_ bar()
_ bar2()
```
Or #4:
```
function foo():
- bar()
- bar2()
```

Or #5:
```
function foo():
; bar()
; bar2()
```

That would make JavaScript/TypeScript an easy to write on board language, where a language like python dominates because of it's simplicity in writing. This would make JavaScript/TypeScript spread into more areas in science, education and engineering.

Thank you,

**Comment by MartinJohns** [comment]
Please respect the [issue template](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md).

**Comment by DanielRosenwasser** [comment]
@MartinJohns has linked to the appropriate document regarding why this is out of scope.
