### ISSUE TITLE
.js files created in rootDir, in addition to files created in outDir

### ISSUE THREAD

**Issue by JakeGinnivan** [microsoft/TypeScript#34889]
I am playing around with project references and setting up a npm library mono repo for the first time and using `tsc -b` is resulting in duplicate files being created inside rootDir, even though outDir is specified. I tested on stable and `@next` to make sure but can't spot what I am doing wrong.

**TypeScript Version:**  3.8.0-dev.20191102

**Search Terms:** rootDir, project references, output

**Code**
The project is available at:
Run `yarn` then `yarn tsc -b`

https://github.com/sevenwestmedia-labs/etrigan

tsconfig.json (in project)

```
{
    "extends": "../../tsconfig.settings.json",
    "compilerOptions": {
        "outDir": "./dist",
        "rootDir": "./src"
    },
    "exclude": ["dist"]
}
```

And tsconfig.settings.json

```
{
    "compilerOptions": {
        /* Basic Options */
        "incremental": true,
        "target": "es5",
        "module": "commonjs",
        "declaration": true,
        "sourceMap": true,
        "composite": true,
        "importHelpers": true,

        /* Strict Type-Checking Options */
        "strict": true,
        "noImplicitAny": true,
        "noImplicitThis": true,

        "moduleResolution": "node",
        "esModuleInterop": true
    }
}
```

**Expected behavior:**
Output files to be created only in the `dist` folder

**Actual behavior:**
Before compilation finishes, compiled .js files appear next to the source files, but no declarations or .map files. Just the .js
<img width="196" alt="image" src="https://user-images.githubusercontent.com/453152/68085913-15b60f00-fe81-11e9-92c7-4c9b578856e1.png">

☝️ why is src/index.js being created. 🤷‍♂ 

**Playground Link:** https://github.com/sevenwestmedia-labs/etrigan

**Related Issues:** I couldn't see anything which had the same issue, there are other issues related to project references but not the same.

**Comment by sheetalkamat** [comment]
This is error in https://github.com/sevenwestmedia-labs/etrigan/blob/master/tsconfig.json where if this was suppose to be solution tsconfig, it is missing `files: []` entry which would make it solution config. Currently it includes all files in the folder and emits them (can be found by doing `--listFiles --listEmittedFiles`)

**Comment by JakeGinnivan** [comment]
Thanks @sheetalkamat! I have submitted a PR to the docs to try make this clearer :)
