### ISSUE TITLE
tsserver is acting strangely on VS Code Remote-WSL (WSL2)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/TypeScript#34905]
**TypeScript Version:**  3.6.3 (3.7.1-rc seems to have the same issues)

Version: 1.40.0-insider (user setup)
Commit: a14de79ac74f2e0e6566d3cc9410eeb7dc769cde
Date: 2019-11-02T00:39:42.595Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19013

In my https://github.com/Tyriar/xterm.js workspace tsserver is having a bunch of issues this morning on a WSL2 Debian remote connection:

![image](https://user-images.githubusercontent.com/2193314/68150415-8c402480-fef4-11e9-86e9-27317dc25596.png)

Console:

![image](https://user-images.githubusercontent.com/2193314/68150432-95c98c80-fef4-11e9-9394-9bceca005534.png)

[tsserver.log](https://github.com/microsoft/TypeScript/files/3805679/tsserver.log)

**Comment by Tyriar** [comment]
Also `tsc -w` seems to work fine in the terminal of the same window

**Comment by Tyriar** [comment]
cc @mjbvz

**Comment by sheetalkamat** [comment]
Does this still repro? If yes, does https://github.com/microsoft/TypeScript/pull/35615#issuecomment-564263744 help?

**Comment by Tyriar** [comment]
Haven't seem this since
