### ISSUE TITLE
TypeScript emits helpers above import statements in ES6 output mode.

### ISSUE THREAD

**Issue by Themayu** [microsoft/TypeScript#34900]
**TypeScript Version:**  v3.8.0-dev.20191102

**Search Terms:**

TypeScript ES6 Output Helpers Before Imports
TypeScript outputs helpers before ES6 imports

**Code**

```ts
import { LitElement, css, html, property } from "https://unpkg.com/lit-element@2.2.1/lit-element.js?module";

class LayoutPage extends LitElement {
  @property({ type: String })
  path = location.pathname;

  @property({ type: String })
  search = location.search;

  constructor() {
    super();
  }

  createRenderRoot() {
    return document.body;
  }

  render() {
    return html`
      <p>Some output for the test.</p>
    `;
  }
}

customElements.define("layout-page", LayoutPage);
```

**Expected behavior:**
TypeScript leaves import statements at the top of the script and emits the `__decorate` helper below them.

**Actual behavior:**
TypeScript emits the `__decorate` helper at the top of the script, which results in JavaScript not running the imports.

**Playground Link:**
[Playground Link](http://www.typescriptlang.org/play/?experimentalDecorators=true&ts=3.8.0-dev.20191102#code/JYWwDg9gTgLgBAbzgGWDAogGwKYmwOxgBo4BjAZ3JIAsYRMSwoIxtYBPOAXzgDNmQcAES0YYcgC4A9FICu+MAGsA5gDpSEEFMxoAtNhx5CAAQBMq8wEZteg7gIxVAK3IB+EBAAmsnEIDcAFABpJgAhpQooewQsjAACqHK2HDYAB4wBJ7kKGhY9oSIAXBwxkwsbDDsABRIlawScADKMFDA+MrcAJRFcGChMNRwALxwmBCk-cAQ+Kp9A-iheIE9pcysHDVwddgNza3tXT3k2KFQpIMjYxMwUzPHp+fLxRr45C2ypDDQVZ2FxcXkWTrH6BYpcILPKAnDIAJUybBhEAgMB+f3+UJgsig+DgnnGsiMjgARl52KDuBC4FD8J42KiED1ihisTjaPQAAaM-4AHjAAD5GppkjExLE+NAttRkhk3qpuVJ+Vz2eTweDgrI3po8oTyKpabw2tgqkIwtFYro+kkhCRkFERQkkp1AkA)

**Related Issues:**
- [Helpers are emitted after imports](https://github.com/microsoft/TypeScript/issues/2811) - This one looks similar, but is marked as "resolved" when the latest Nightly build does not resolve this issue.

**Comment by Themayu** [comment]
Edited to remove a bunch of unneeded stuff and to bring the playground link in line with the given code.

**Comment by fatcerberus** [comment]
> TypeScript emits the __decorate helper at the top of the script, which results in JavaScript not running the imports.

If that's really true, your runtime is not compliant.  Imports can be anywhere in the top-level code of the module and are resolved statically, before anything runs.  This is why you can't put them in functions.

**Comment by Themayu** [comment]
> If that's really true, your runtime is not compliant. 

I'm using Google Chrome, and the issue I was having went away when I removed the `@decorate` calls from my code. But coming back to this 7 hours later, I can't seem to replicate the original problem even using the code I had at the time.

...This behaviour leads me to believe that I am mistaken, and that this is not an issue - the only reason I believed it was, was because of an error message I was receiving from Firefox some time ago, that further research shows I was misinterpreting. As such, I will be closing this issue, as this behaviour is not problematic.
