### ISSUE TITLE
Build/Environment Variables

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/TypeScript#34918]
When building for a web browser, it can be hard to build for different environments (prod, dev, staging, etc.), because sometimes you need to uses different variables based on where the script(s) are running. For example when using a production environment, you may need a url to go to a production url such as http://example.com but when in development you may need it to go to http://dev.example.com. Modifying the hosts file is not necessarily ideal. This solution might also work with nodejs where the dotenv module would possibly no longer be necessary.

I would like to suggest for the ability of adding a builds variables file, where you can define your variables then build to that environment, it would be possible that it would look something like this:

**/.env.json**
```
{
  "prod": {
    "endpoint": "ws://example.com"
  },
  "stage": {
    "endpoint": "ws://stage.example.com"
  },
  "dev": {
    "endpoint": "ws://127.0.0.1",
    "port": 1234
  }
}
```

Then when you are ready to build you would run one of the following:

```
tsc -p . --env=prod
tsc -p . --env=dev
```

Lets say your TypeScript file looks like this:

```
let master = new WebSocket(env.endpoint);
```

When built, the variables from the build file would be injected into the final build. Let's assume we ran `tsc -p . --env=prod`, the variable `port` exists in `dev` but not `prod`, it probably should still be added to the output variables no matter what environment you select.

```
window.env = {
  endpoint: "ws://example.com",
  port: undefined
};
let master = new WebSocket(window.env.endpoint);
```
Or maybe you want to build for `dev` with `tsc -p . --env=dev` the output would then look something like this:
```
window.env = {
  endpoint: "ws://127.0.0.1",
  port: undefined
};
let master = new WebSocket(window.env.endpoint);
```

**Comment by nmain** [comment]
My guess is that this runs afoul of the stated [non-goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals)

> 4. Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

**Comment by RyanCavanaugh** [comment]
Bundlers are very capable of doing a good job of this and we'd prefer to keep letting them handle these cases

**Comment by TheColorRed** [comment]
Is there a bundler out there that does this?

**Comment by tbell511** [comment]
Looking for this as well!! This would be an absolute game changer.
