### ISSUE TITLE
Object mapping string to boolean or Object gets typed instead to any with new JS->declaration support

### ISSUE THREAD

**Issue by DavidAnson** [microsoft/TypeScript#34914]
```
C:\T\tsrc>npm ls
C:\T\tsrc
`-- typescript@3.7.1-rc


C:\T\tsrc>type example2.js
"use strict";

/**
 * Map of string to boolean or Object.
 *
 * @typedef {Object.<string, boolean | Object>} MyMap
 */

C:\T\tsrc>node_modules\.bin\tsc --allowjs --declaration --outdir out example2.js

C:\T\tsrc>type out\example2.d.ts
/**
 * Map of string to boolean or Object.
 */
type MyMap = {
    [x: string]: any;
};

C:\T\tsrc>
```

**Comment by RyanCavanaugh** [comment]
`Object` is an alias for `any` unless `noImplicitAny` is on. I believe @sandersn offered up some other workarounds offline?

We should try making `object` be `object` in JS Doc now that we have a real object primitive type

**Comment by sandersn** [comment]
This is something we ask periodically. When [I recently removed the `object=any` rewrite when noImplicitAny is on](https://github.com/microsoft/TypeScript/pull/35661), I found that webpack, in particular, still relies on it, despite checking their code with typescript. I expect the results would be similar for `Object=any`.
