### ISSUE TITLE
@property should only add a property to a @typedef with initial type of Object

### ISSUE THREAD

**Issue by DavidAnson** [microsoft/TypeScript#34911]
In the example below, I don’t expect the string map to disappear from MyBadMap when adding a function-typed property to the object. Asking internally, @sandersn suggested I open an issue here.
 
```
C:\T\tsrc>npm ls
C:\T\tsrc
`-- typescript@3.7.1-rc
 
 
C:\T\tsrc>type example.js
"use strict";
 
/**
* Good example.
*
* @typedef {Object.<string, string>} MyGoodMap
*/
 
/**
  * Simple function
  *
  * @callback MyCallback
  * @returns {void}
  */
 
/**
* Bad (?) example.
*
* @typedef {Object.<string, string>} MyBadMap
* @property {MyCallback} callback
*/
 
C:\T\tsrc>node_modules\.bin\tsc --allowjs --declaration --outdir out example.js
 
C:\T\tsrc>type out\example.d.ts
/**
* Good example.
*/
type MyGoodMap = {
    [x: string]: string;
};
/**
* Simple function
*/
type MyCallback = () => void;
/**
* Bad (?) example.
*/
type MyBadMap = {
    callback: MyCallback;
};
 
C:\T\tsrc>
```

**Comment by sandersn** [comment]
Smaller example:

```js
/** @typedef {Object.<string,string>} Mmap
 * @property {string} ignoreMe - should be ignored
 */
```

should produce `{ [s: string]: string}` not `{ ignoreMe: string }`.

**Comment by DavidAnson** [comment]
@sandersn knows this area far better than I, but his example seems slightly different than mine. In his, the added property is a “subset“ of the existing map behavior, whereas in mine, the added property is a function which *should* end up in the resulting declaration file.

**Comment by sandersn** [comment]
So the typescript type you expected to see was `{ [s: string]: string, ignoreMe: string }` ?

**Comment by DavidAnson** [comment]
@sandersn Yes, that!

**Comment by sandersn** [comment]
Unfortunately, that doesn't work for a couple of reasons:

Your specific example is not a valid Typescript type -- a string index signature requires that all properties in the type be assignable to its type. But `MyCallback` isn't assignable to `string`.

My `ignoreMe` example is a valid Typescript type, but neither Typescript nor the [jsdoc site](https://jsdoc.app) nor Closure expects the jsdoc combination of `@typedef {Object<string,string>}` with `@property`. Both Typescript and Closure idiomatically use object literal types, like the ones from my previous comment, not `@property`. So I don't think there's much demand for that combination.

**Comment by DavidAnson** [comment]
Is it possible to represent a flexible dictionary object like the following in TS? That’s basically my goal.

```
var obj = {
  something: 1,
  another: 2,
  more: 3,
  validate: () => {}
};
```

**Comment by sandersn** [comment]
Unless you know all the keys at compile time, the index signature needs be a supertype of all the value types. In the example you gave, `unknown` is the only obvious supertype of `number` and `() => {}`. (`any` is a lot more convenient because `unknown` forces you to cast to use the dictionary).

A mapped type might work although you need to know all the keys at compile time.

**Comment by DavidAnson** [comment]
Thanks for the clarification! I don’t know the types at compile time, so it seems like I’m unable to express this in TypeScript.
