### ISSUE TITLE
3.7.2 released on npm

### ISSUE THREAD

**Issue by Julusian** [microsoft/TypeScript#34921]
npm reports a v3.7.2 was just pushed. This looks untintentional and possibly suspicious.
Can a team member confirm its legitimacy or pull it?

https://www.npmjs.com/package/typescript

**Comment by Julusian** [comment]
Thanks, that issue matches what I have seen here exactly. so it looks valid then.

Still, it would be nice to have a git tag first..

**Comment by RyanCavanaugh** [comment]
This is documented in our release planning: https://github.com/microsoft/TypeScript/issues/33352
