### ISSUE TITLE
Extending multiple interfaces where the interfaces expand on deeper inherited interfaces

### ISSUE THREAD

**Issue by remag9330** [microsoft/TypeScript#34939]
**TypeScript Version:**
3.6.3-Nightly (this was working in 3.5.2 and prior)

**Search Terms:**
extends multiple compatible interfaces not identical

**Code**
```ts
interface Events<T> {
    emit<K extends keyof T>(name: K, obj: T[K]): void;
    on<K extends keyof T>(name: K, func: (obj: T[K]) => void): void;
}


interface WidgetEvents {
    onclick: MouseEvent;
}

interface Widget extends Events<WidgetEvents> {
    // ...
}


interface TextboxEvents extends WidgetEvents {
    textchanged: KeyboardEvent;
}

interface Textbox extends Events<TextboxEvents>, Widget {
    // ...
}


declare const w: Widget;
declare const t: Textbox;

w.on("onclick", e => { })
t.on("onclick", e => { })
t.on("textchanged", e => { });

```

**Expected behavior:**
Works, no errors

**Actual behavior:**
Error on the `interface Textbox` declaration
```
Interface 'Textbox' cannot simultaneously extend types 'Events<TextboxEvents>' and 'Widget'.
  Named property 'emit' of types 'Events<TextboxEvents>' and 'Widget' are not identical.
```
and similar for `on`.

**Playground Link:**
https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191105&ssl=1&ssc=1&pln=31&pc=1#code/JYOwLgpgTgZghgYwgAgKIDcLgM4B4AqAfMgN4CwAUMtchALbBi4DStAHpCACbbIDWEAJ4B7GMiIAKEHDoQAXMmYAaZMIBGAKwX4A2swC6ASgXphwLgG5KNVSBbtOPfkNHjCUmfMUqYAVxAIChLqWuJ6RsgAvMSm5sbIsZaUAL6UaRSgkLCIKADq5gDmEGAYWGC85FQ0wgEANsAIfAoAssK+2BCl4FYUqRSUmdDwSMj5XEVgDlhOXeW4YxOz2MSVNgD0a8gAdDsp6QPgQzniEBxqwmxLU9y8C8VXqzSQHAgAFnAgRVwKzELncFAuLMen0Dllhih8KcwOc2NcZpgcARobCloQVHdJo9qBttrtevsKFwIAhagCUAgathJgB3BSYnrE0nk5CUkDU5BgbQoi49Sg0rY1CQAIhqpIafGFKhQ0VIyGShkoYEFIBFYvqjSltCiK3liooyqFwueYDeHy+WpluoVFiAA

**Related Issues:** #8606, #16936

Came across this while upgrading our project from 3.5.2 to 3.7.2, we rely pretty heavily in our typings for a JS library on the above pattern. I looked through the list of breaking changes for TS 3.6
but didn't see anything related to the issue. I note that it is quite similar to #16936 but opted to open a new issue since this was accepted by the compiler in prior versions where that ticket was never considered fixed.

Also, sorry about the title, hopefully the code makes it more obvious what I'm talking about!

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; prior versions of TS had a bug where certain conflicts were not correctly detected. The types of these properties don't agree and you need to resolve the conflict.

Example:
Setup
```ts
interface Events<T> {
    emit<K extends keyof T>(name: K, obj: T[K]): void;
}

interface WidgetEvents {
    onclick: MouseEvent;
}

interface Widget extends Events<WidgetEvents> { }

interface TextboxEvents extends WidgetEvents {
    textchanged: KeyboardEvent;
}

interface Textbox extends Events<TextboxEvents>, Widget { }
```

The problem:
```ts
declare const w: Widget;
// OK
w.emit("onclick", null as any);
// Error
w.emit("textchanged", null as any)

declare const et: Events<TextboxEvents>;
// OK
et.emit("onclick", null as any);
// OK
et.emit("textchanged", null as any);

declare const t: Textbox;
// OK
t.emit("onclick", null as any);
// Is this supposed to be an error or not?
// The two base interfaces disagree
t.emit("textchanged", null as any)
```

**Comment by remag9330** [comment]
Ahh, okay. So we were relying on a bug in older TS versions - that makes sense. We will deal with this internally then. Thanks for your time!
