### ISSUE TITLE
Number.is* should accept `unknown`

### ISSUE THREAD

**Issue by shicks** [microsoft/TypeScript#34931]
**TypeScript Version:**  3.8.0-dev.20191102

**Search Terms:** Number isInteger isSafeInteger isFinite isNaN

**Code**

```ts
declare function use(number: number): void;
declare const maybeNumber: string | number;
if (Number.isInteger(maybeNumber)) {
  use(maybeNumber as number);
}
```

**Expected behavior:**
Type checks

**Actual behavior:**
Fails to type check because `Number.isInteger` is typed to take only `number`.

**Playground Link:** 
http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20191102&ssl=3&ssc=2&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX2QGcQAKVZAWwCMQYAuec62gSgYDcctgBuAKFCRYCMHkIZ4FKAE8aAOUo168cTCyoA5vAA+jRbX5ZE8EguYwAdFkIBJVBhAbaJKbJBmlLFvADefeATELjLy+jDwUIR65iz8AL5AA

**Related Issues:** 
* #24436 - PR that already addressed this 18 months ago, but seems to have been accidentally reverted by 2f73986b44a4ec10c7ebe7188e23863c3879d54e.
* #15527 - closed for housekeeping.
* #4002 - _not_ the same issue - that issue is about the global functions that coerce their argument, while this is about the functions on `Number` that don't, making it safe to widen the accepted types.
* #21199 - a broader issue, since it's currently infeasible to make these type guards.

**Comment by shicks** [comment]
Reading further, it looks like #24436 updated the generated lib, not the version in src.

**Comment by RyanCavanaugh** [comment]
Thank you for the good research effort on this!

**Comment by DanielRosenwasser** [comment]
So do we want this change? I'm kind of glad it didn't happen (even for bad reasons) because I think the current behavior saves users more than it frustrates, and the workaround is relatively simple (unary `+`).

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser I think it's good. `Number.isInteger("0")` is `false`, IOW no fishy coercion occurs
