### ISSUE TITLE
Typescript 3.7 emits .js && .map files for each ts file

### ISSUE THREAD

**Issue by yadue** [microsoft/TypeScript#34945]
**TypeScript Version:**  3.7.2

**Search Terms:**
js map files

**Code**

```ts
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "node",
    "allowJs": true,
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitOnError": false,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "lib": [
      "es2015",
      "dom"
    ],
    "baseUrl": "./src/js/",
    "paths": {
      "@projectTypes/*": ["types/*"],
      "@interfaces/*": ["interfaces/*"]
    },
    "skipLibCheck": true,
    "rootDir": "."
  },
  "exclude": ["node_modules", "node-exec", "public", "target", "*.js"]
}

```

**Expected behavior:**
When using typescript 3.7, webpack and ts-loader complier shouldn't create js and js.map file for each ts file. Reverting to 3.5.3 fixes issue.

**Actual behavior:**
Typescript 3.7 create all js and map files for each ts file causing constant reloads using Intellij, where 3.5.x didn't create them at all and live reload worked correctly. I have completely no idea how to force ts to stop emitting those files.

**Comment by yadue** [comment]
Intellij Issue, no longer valid.

**Comment by ondraondra81** [comment]
@yadue How I can fix it in Intellij ?

**Comment by yadue** [comment]
Just uncheck compile ts files in IntelliJ typescript config
