### ISSUE TITLE
<TypeScriptSourceMap>False</TypeScriptSourceMap> is not applied in targets files

### ISSUE THREAD

**Issue by nefcanto** [microsoft/TypeScript#34947]
I'm trying to work with TypeScript in Visual Studio. I'm not working with Angular, nor any other JavaScript libraries. We have our own libraries in our company. And we're porting them to TypeScript, so that we can manage them easier.

We don't use Visual Studio Code. We use Visual Studio 2019.

And when you add a TypeScript file to VS, it says that you have to include a NuGet package called `Microsoft.TypeScript.MSBuild`.

And we don't want to map files either. So we have to turn it off. The overall footprint of adding TypeScript to each of our projects is this code:

```
<ItemGroup>
	<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="3.7.2">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
</ItemGroup>

<PropertyGroup>
	<TypeScriptTarget>ES5</TypeScriptTarget>
	<TypeScriptJSXEmit>React</TypeScriptJSXEmit>
	<TypeScriptModuleKind />
	<TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
	<TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
	<TypeScriptRemoveComments>False</TypeScriptRemoveComments>
	<TypeScriptOutFile />
	<TypeScriptOutDir />
	<TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
	<TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
	<TypeScriptSourceMap>False</TypeScriptSourceMap>
	<TypeScriptMapRoot />
	<TypeScriptSourceRoot />
</PropertyGroup>
```

So far so good. But we have a lot of project files. And I mean more than 500 `.csproj` files that need to be configured like this. So it's stupid to repeat this code across them all. 

Microsoft's way of DRYing MSBuild configuration files is to use `.targets` or `.props`. So we've created a targets file called `TypeScript.targets` and we're importing it in every project as `<Import Project='$(ProjectsRoot)\Framework\TypeScript.targets' />`.

The problem is, we still get those map files and Visual Studio completely ignores the configuration of TypeScript in that targets file. 

What should we do?

**Comment by andrewbranch** [comment]
This really is a Visual Studio question, not a TypeScript question. I don’t know the answer and I didn’t get a response that anyone else on the team did either. You’ll have better luck going through VS support channels or asking on StackOverflow.
