### ISSUE TITLE
Major bug in tsc: creating invalid code

### ISSUE THREAD

**Issue by Ziv-Barber** [microsoft/TypeScript#34948]
**TypeScript Version:**  3.7.2

**Code**

I'm trying to write a node.js module in ts:

```ts
export function test () {
  console.log('test')
}
```

And to import it in a node.js code:

```js
var myLib = require('mylib')
```

**Expected behavior:**

myLib should be declared

**Actual behavior:**

myLib is not been declared

I tried to examine the code that tsc creating and I found that it's invalid:

(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports"], factory);
    }
})(function (require, exports) {
  // My code but no return of anything so v is always undefined!
});

**Comment by MartinJohns** [comment]
You left out important details. How exactly are you compiling your TypeScript code? What's the content of your `tsconfig.json` file? (specifically the module option)

**Comment by Ziv-Barber** [comment]
While googling I found out that I should do:

export = {
 ...
}

Thanks!
