### ISSUE TITLE
Object definition requires optional values

### ISSUE THREAD

**Issue by tomconroy** [microsoft/TypeScript#34950]
**TypeScript 3.7.2**
[Playground link](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8AoZZAbQGsIBPALmQGcwpQBzAXVY5cQ3CgF8A3BQoJ0IDshjp0rDNnxESyALzkFS1gHI8cKAeSipMuaWMAvbXvQ0jcWwd5S7AOjDoAqgAOAdAAwnBsEAAUAJQUQA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
interface SomeObject {
  [key: string]: string
};

const foo: SomeObject = { foo: 'bar' }

const baz = foo['baz']

baz.toUpperCase()

```

**Output:**
```javascript
"use strict";
;
const foo = { foo: 'bar' };
const baz = foo['baz'];
baz.toUpperCase();

```

**Expected behavior:**

I ran into a bug in production here where I've defined my own object type. It's a bit unexpected that this doesn't cause an error (but does cause a run-time error). The solution is to mark the value type as optional `string?` – but it seems like this should be the default behavior, you can never guarantee that this object will return a non-optional value, right?

**Comment by AnyhowStep** [comment]
This is why I almost always use `{ [k:string] : T|undefined }`, if I need a string-indexed type (or `Record<string, T|undefined>`) instead of just `{ [k:string] : T }` (or `Record<string, T>`).

It's one of those times where usability is preferred over soundness, I think.

-----

While people creating `SomeObject` cannot say `someObj.prop = undefined`, consumers of `SomeObject` have to be on guard.

If you need to guarantee `baz` exists,
```ts
interface SomeObject {
  [key: string]: string | undefined
  baz : string
};

//Error
//Property 'baz' is missing in type '{ foo: string; }' but required in type 'SomeObject'.(2741)
const foo: SomeObject = { foo: 'bar' }

const baz = foo['baz']

baz.toUpperCase()
```
[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=18#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8BYAKGWQG0BrCATwC5kBnMKUAcwF12XHiF7IAPsgCuIACYQYoCLOq08cAF7Ih3PtQC+AbmrUA9KYCiUKOihnTABRsAHaGGbIA5Oo2fkwDmRMAI4+fxBkd1cvMmQYdHQdEV5DZH0-PClSKAgARylgHNlwyOZozwxsfCISTwA6AAoAJgB2ABYARgBKagR0EC44hPZK3EJiUgBeciHEr3UoP30TKj6B0h9kafj0Om9NT34VnzqwdABVZ1coAGE4DggGrqA)

**Comment by tomconroy** [comment]
```ts
> const foo = { bar: undefined }
> foo.hasOwnProperty('bar')
< true
```

Something to note, a key can exist and still be undefined. It seems to me like the type `{ [key: string]: string | undefined }` implies my example above.

My use-case specifically the object keys are record IDs, so they can't be encoded into the type.

IMO, If you specify a type the contains `{ [key: string]: T }` then arbitrary lookup should always be `T | undefined`. 

It would be cool indeed if this was the case, then typescript could know the key exists and infer `T`, in cases like these

```ts
Object.keys(foo).map(key => foo[key].toUpperCase())

if (key in foo) return foo[key].toUpperCase()
```

I have no idea how that would work, but it seems like a thing! 😀

**Comment by AnyhowStep** [comment]
Except, if you make `foo` of type `SomeObject` (`Record<string, string>`), then `{ bar : undefined }` would not be assignable to it.

**Comment by tomconroy** [comment]
Sure, in my use case the key doesn't exist yet. I was just pointing out the difference between a nonexistent key and a key with `undefined` value shouldn't be represented the same in the type system (I could be wrong about this, but my example shows at least one issue with that). My point was the type `Record<string, T | undefined>` (or `{ [key: string]: T | undefined }` says to me: keys that exist have values of type `T | undefined`. 

I shouldn't specify the `| undefined` because arbitrary lookup of `[key: string]: T` is really `T | undefined`

**Comment by RyanCavanaugh** [comment]
See #13778

**Comment by tomconroy** [comment]
Thanks, I thought it must be well known!
