### ISSUE TITLE
Optional Chaining downlevel emit is wrong for super.method?()

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#34952]
**TypeScript Version:**  3.7.2

**Search Terms:**

**Code**

```ts
// @target: ES6
class Base {
    method?() { }
}

class Derived extends Base {
    method() {
        return super.method?.()
    }
}
```

**Expected behavior:**

Correct code is emitted

**Actual behavior:**

Tries to use `super` as a variable and capture it in a temp variable. That is syntactically invalid.

**Playground Link:** http://www.typescriptlang.org/play/?target=2#code/MYGwhgzhAEBCkFNoG8BQ0PQLYIC4AsB7AEwH4AKAShWgF9V7VRIYARBAJwEsA3BY6AgAeuBADtiMeBCRpM2PEWJUU6eZg54ArhzHQIWgA6cAdDgIlSJqmoz1aQA

**Comment by RyanCavanaugh** [comment]
Tentatively putting this in the patch release

**Comment by rbuckton** [comment]
Also, we apparently aren't stripping the `?` correctly in the `method?() {}` declaration above either.

**Comment by justinfagnani** [comment]
I'm still seeing this problem in 3.7.5: https://www.typescriptlang.org/play/#code/MYGwhgzhAECC0G8BQ1oDMD2GAUBKRKq0EArgA4CmATgHSYYD8NeA3IQL5KdA

**Comment by rbuckton** [comment]
This doesn't repro in 3.8-beta. It seems this didn't make it into the 3.7.5 release.
