### ISSUE TITLE
Add support for environment variables, and files added as link, both in configuration, and in the .ts files

### ISSUE THREAD

**Issue by nefcanto** [microsoft/TypeScript#34968]
I'm asking for a feature.

In industry, cost plays an important role, and a lot of measures are taken to reduce costs and boost productivity.

For that reason, we only use Visual Studio IDE. And we've built a lot of our company's architecture on the features it provides for us.

Two amazing features VS offers are:

1) environment variables
2) add as link

Based on these valuable features, we thought of using TypeScript in our organization-wide architecture.

We include a bunch of TypeScript files in different hierarchies and file-system architecture throughout the entire organization, and we need to be able to reuse them across the entire organization.

For example, we want to have one central tsconfig.json file, and reuse it across all of our projects, because we have a SPL, and all of our projects are like each other in technology stack.

But we tried to include that central tsconfig.json in other projects using "add as link" feature, and TypeScript doesn't recognize it.

Also we would love to use environment variables in our import clauses like:

import DateTools from '%ProjectsRoot%/Framework/Scripts/DateTools'

Please add support for environment variables, and add as link features to make working with TypeScript smoother in Visual Studio for multi-project environments with heavy code reuse.

Thank you so much.

**Comment by nefcanto** [comment]
I also saw #18755 and #31648. And I realized that you have design limitations. At least support environment variables. Environment variables are first-class entities throughout the entire software world. They exist in any operating system, any programming language, and almost any IDE.

**Comment by nefcanto** [comment]
Also it's correct that you have `--preserveSymlinks` compiler option, but symlinks can't be managed in TFS (Azure DevOps) client for Visual Studio, which is called Team Explorer. When you get the latest version on another machine, it gets the real file without creating the symbolic link for it. Thus it's not useful in real-world scenarios.

**Comment by fatcerberus** [comment]
> For example, we want to have one central tsconfig.json file, and reuse it across all of our projects, because we have a SPL, and all of our projects are like each other in technology stack.

I'm pretty sure you can do this today, using `extends`:

```json
{
    "extends": "/path/to/main-tsconfig.json"
}
```

You can then add any project-specific overrides, if necessary.

**Comment by nefcanto** [comment]
@fatcerberus the point is we can't use environment variables in that. We can't also use abslute paths, since it breaks local builds on developers' machines. For example we can't have a tsconfig.json file in C:\Projects\SomeProject that is as follow:

`
extends: '%FrameworkPath%/TypeScript/CentralTsConfig.json'
`

And if we have this, then our colleaguea won't be able to work, unless they all follow file-system architectur strictly:

`
extends: 'C:\\Framework\\TypeScript\\CentralTsConfig.json'
`
Because for example one of develoers map projects to his D folder, in a different file-system architecture.

**Comment by RyanCavanaugh** [comment]
Surely you can use relative paths, though.

TS is not here to provide new ways of naming modules - this is a runtime concern

**Comment by fatcerberus** [comment]
I think he wants the environment variables to be resolved at compile time.

**Comment by nefcanto** [comment]
@RyanCavanaugh relative paths break when developers map repositories differently. Relative paths only work when we force a file-system archietcure, which in turn spawns other problems.

**Comment by nefcanto** [comment]
@fatcerberus thanks for mentioning goals and non-goals. I fail to see how this is related to an end-to-end build issue. The other feature we mentioned

**Comment by milesj** [comment]
Use Babel + plugin to achieve this?

**Comment by nefcanto** [comment]
@milesj isn't it ridiculous to use two JavaScript compilers/transpilers? Do you write Java in C#? Do you use SQL Server Management Studio for MySQL?

**Comment by milesj** [comment]
@nefcanto  I type check with TS but compile with Babel because it provides the entire plugin ecosystem. It's the primary reason TS support was added to Babel.

For example, with Babel I can compile `__DEV__` constants in my code to `process.env.NODE_ENV !== 'production'`. The same can be done with your environment variables within import paths.

**Comment by nefcanto** [comment]
@milesj what you is a very good and vivid reason TypeScript needs more features. Parallel technologies should not be used in real-world exapmles for a lot of reasons. Higher costs, steeper learning-curves, more painfull upgrades, less hiring chances, more compatibility to look for, less flexibility for innovation, and much more.

Angular is enough, so that you don't need React or Vue with it. IMHO what you said is a big red flag for TypeScript team to consider.

**Comment by nefcanto** [comment]
TypeScript is a transpiler that transpiles superset of JavaScript into different flavors of JavaScript. Babel is a transpiler of JavaScript. So, I have to use the handle of this spoon, and the cup of the other spoon because they both lack to be a real spoon?

And your solution won't work for us. Because we need to be able to do so:

`import CountryParser = require('%FrameworkProjectsRoot%\TypeScript\Geo\CountryParser');`

Using Babel won't help us getting the type-checking and intellisense and more features here. Because it's a design-time feature, not compile-time.

**Comment by nefcanto** [comment]
No, it's not a question. It's a feature request.
