### ISSUE TITLE
export default not updating

### ISSUE THREAD

**Issue by basickarl** [microsoft/TypeScript#34976]
Typescript 6.9.0
node v10.16.0

mod.js
```
export let a = { x: 1 };
export function update() {
    a = { y: 2 };
}
    
export default a;
```
start.js
```
import * as allMod from './mod';
import mod from './mod';
import { a } from './mod';
    
console.log(allMod);
console.log(mod);
console.log(a);
    
console.log('');
allMod.update();
    
console.log(allMod);
console.log(mod);
console.log(a);
```
terminal:
```   
{ a: { x: 1 }, update: [Function: update], default: { x: 1 } }
{ x: 1 }
{ x: 1 }
    
{ a: { y: 2 }, update: [Function: update], default: { x: 1 } }
{ x: 1 }
{ y: 2 }
```
As you can see the `a` variable is updated within the module, but the default value stays the same? Does anyone know why this happens? It seems that export default is a type const?

I'm reading this: https://www.ecma-international.org/ecma-262/6.0/#sec-exports-static-semantics-isconstantdeclaration

It states to return false, meaning that export default is should not be a constant? I'm wondering if this is how it should act or if something is off here with the transpiling?

**Comment by fatcerberus** [comment]
`export default` is an interesting case because it exports *by value*, rather than exporting a live binding like named exports do.  When the runtime sees `export default a;`, it evaluates the expression `a` and whatever value it evaluates to is what's exported.  It's as if you wrote `export default { x: 1 };` directly.

**Comment by AnyhowStep** [comment]
@fatcerberus ' comment about `export default`.

Thanks, I hate it.

**Comment by basickarl** [comment]
@fatcerberus I was afraid it was like this. But this does adhere to the official specification stated? I'm sorry but I'm not used to reading ECMA documents!

**Comment by fatcerberus** [comment]
@basickarl Yes, this is how default exports work in all ES module implementations that I’m aware of.  You can in fact default-export plain values: `export default 777;` is entirely legal.  You can’t do this with named exports—they must always export a binding of some sort (variable, hoisted function, class declaration, etc.)

This little wrinkle is also why `export default let foo = 1206;` is a syntax error.  I don’t know *why* this distinction exists, but the behavior you’re seeing is expected at any rate.

**Comment by RyanCavanaugh** [comment]
TIL. Gross.
