### ISSUE TITLE
Get off your ass and "embrace extend extinguish" assemblyscript!!! ( --static )

### ISSUE THREAD

**Issue by chobot2014** [microsoft/TypeScript#34990]
Would be nice if you guys embraced the future
wasm has entered the game, will the developers forget the days of typescript along with java script or will you take, the most amazing amalgam ever made to the level it deserves.

> Some fragile someone will say "well, due to the dynamic nature of what's involved in javascript it's like totally impossible without a runtime and go on about how elon musk is a class traitor or some bullshit.

Current state of the matter:
The only feasible way to say "hello from typescript" on bare hardware is to use assemblyscript with wasm2c

- compiles to web assembly, meaning that you could still call it from the browser,from normal javascript without having to compile to javascript.
make some state based statically compiled "runtime" that lives in the compiled file

Blazor has proven that you can compile the dotnet to wasm..
Imagine a world where developers write their server software using TypeScript on dotnet

thanks ❤

**Comment by trusktr** [comment]
Wanna make a PR?

**Comment by RyanCavanaugh** [comment]
This has been brought up dozens of times; please search before logging new "issues". Thanks!

**Comment by chobot2014** [comment]
> Wanna make a PR? :)

yes

**Comment by chobot2014** [comment]
> Wanna make a PR? :)

gonna take me some time

**Comment by chobot2014** [comment]
> This has been brought up dozens of times; please search before logging new "issues". Thanks!

So are there plans to do this?
