### ISSUE TITLE
Use enums in literal definition of objects using interface with index of type number

### ISSUE THREAD

**Issue by JirkaDellOro** [Microsoft/TypeScript#3499]
There are some issues concerning the declaration of an interface index of an enum-type. However, at least the following should be possible in my opinion:
```javascript
enum Num { num1 = 1, num2, num3 };

interface numToString {
    [num: number]: string;
}

var obj: numToString;
obj = { Num.num1: "Hello" };    // not accepted
obj[Num.num1] = "Hello";        // accepted and working
```
It appears inconsistent, that the first definition is not accepted, the TypeScript-Service misses commas and colons here.

**Comment by danquirk** [comment]
```ts
obj = { Num.num1: "Hello" };    // not accepted
```
This is explicitly declaring a property name. There are specific rules that JavaScript has for what kinds of names can be used for properties (like not allowing dotted names). If you want to do this you can use a string property name: 
```ts
obj = { "Num.num1": "Hello" };    // not accepted
```
Whereas
```ts
obj[Num.num1] = "Hello";        // accepted and working
```
is a property access which happens to have the semantics of setting the property when that property doesn't exist. JavaScript defines different rules for what kinds of expressions can be used in a property access like this. TypeScript needs to enforce and allow the same sets of rules for each of these two different cases.

**Comment by JirkaDellOro** [comment]
I don't think that this is the correct point, since Javascript actually never gets to see this kind of declaration. In the example, Num is an enumeration-type and its value num1 should translate from TypeScript simply to the value of 1. So

obj = { Num.num1: "Hello" }; 
in TypeScript is expected to translate to 
obj = { 1: "Hello" };

in Javascript, which is valid code. Just as the accepted example

obj[Num.num1] = "Hello"; 
actually really does translate to 
obj[1 /* num1 */] = "Hello";

The same simple rule of translating (Num.num1) to (1 /* num1 */) should apply in the declaration.

**Comment by RyanCavanaugh** [comment]
> ```ts
obj = { Num.num1: "Hello" }; 
in TypeScript is expected to translate to 
obj = { 1: "Hello" };
```

That would be *very* surprising behavior. By analogy, you would never expect this
```ts
const x = 'hello';
var y = { x: 3 };
```
to compile to
```ts
var y = { 'hello': 3 };
```

**Comment by JirkaDellOro** [comment]
I agree, but I guess it's a matter of how you expect ENUMS to be handled. If you expect them to be replaced by their actual values at "transpile"-time, as TypeScript does here
obj[1 /* num1 */] = "Hello";

you'd expect it there as well
obj = { 1 /* num1 */: "Hello" };

I'd consider const to be different, since you can use them with arbitrary data types and the values are still mutable, whereas enums are bound to unmutable integers.

**Comment by bryanforbes** [comment]
Since TypeScript allows ES6 computed properties, modifying the original "not accepted" code to a valid ES6 computed property works:

```ts
enum Num { num1 = 1, num2, num3 };

interface numToString {
    [num: number]: string;
}

var obj: numToString;
obj = { [Num.num1]: "Hello" }; // works
```

**Comment by JirkaDellOro** [comment]
We're using 1.4, so this is currently not supported. Also I'd like to stay with ES5 for a while. Will ES6 support enums natively?

However, while Bryans suggestion may become a good workaround, it feels more like having Javascript fix what TypeScript should have done by transpiling the enums consistently.

**Comment by bryanforbes** [comment]
Once/if you move to 1.5, that syntax will compile to ES5, so you don't need to give up using ES5. ES6 does not support enums natively.

**Comment by DanielRosenwasser** [comment]
Yes, as @bryanforbes mentions, you can still use most of the new ES6 constructs in TypeScript 1.5, as well as all the TypeScript constructs we've implemented so far, all while targeting ES5.

(If you mean that you're unwilling to use any ES6 features for the time being, arrow functions and classes are also part of ES6, and are pretty nice to use)

**Comment by JirkaDellOro** [comment]
Indeed! I just got Bryan wrong thinking ES6 needs to be targeted.
