### ISSUE TITLE
Go to Definition on identifier should jump to `require()`'d path

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#34996]
Follow-up to https://github.com/microsoft/TypeScript/issues/9251, and this has been driving me crazy for a long time now.

```js
// ./a.js

class Blah {
  abc = 123;
}

module.exports.Blah = Blah;
```

```js
// ./b.js

const BlahModule = require("./a.js");

new /**/BlahModule.Blah()
```

1. Go to definition on `/**/`
1. You will be taken to the declaration of `BlahModule` itself. Go to definition once more

## Current Behavior

Nothing happens

## Expected Behavior

Take me to the first line of `./a.js`.

**Comment by DanielRosenwasser** [comment]
Thank you so much @sheetalkamat!!! 🙏

**Comment by orta** [comment]
oh yeah, this is big!
