### ISSUE TITLE
Typeof Broken when function invoked in chain

### ISSUE THREAD

**Issue by lonewarrior556** [microsoft/TypeScript#35005]
**TypeScript Version:**  3.7.2

**Search Terms:**

function call breaks getting type when using `typeof `

**Code**
```
var a = {
  b: {
    c: () => ({
      d: {
        e: (param1: string) => param1
      }
    })
  }
}

const fooFunction = a.b.c().d.e

type FooFunction = typeof fooFunction // works
type FooFunctionBroken = typeof a.b.c().d.e // broken
```
```ts
```

**Expected behavior:**
I would expect `typeof` to work on the returned result of the expression (same as it does when using the variable)

**Actual behavior:**
`typeof` breaks when something is invoked when chaining 

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=14&ssc=44&pln=1&pc=1#code/G4QwTgBCELwQ3gKAhARgLgclEDGmAKASlgD4ICkccATTK6nAU0IAdwQBbARkwGcALmACWAOwDmJGOXZgu3bNQC+iiEqLYVKxLgD2owRABmu3QDEArqNwDh+2FAB0qR7mKOajpogEBPVkwQZqaW1rb2cH4BukbGIVY2dqIQiD7+gcHmCeGiAEJgugDWTMmR6TFOLm5EHl5AA
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Use `ReturnType<typeof a.b.c>["d"]["e"]` to refer to this member
