### ISSUE TITLE
CanvasRenderingContext2D#drawImage overloading problem

### ISSUE THREAD

**Issue by NekR** [Microsoft/TypeScript#3501]
This code:

```typescript
var canvas = document.createElement('canvas');
var context = canvas.getContext('2d');
var drawThing:HTMLImageElement|HTMLCanvasElement;

context.drawImage(drawThing, 0, 0);
```
fails with error:
```
2345 Argument of type 'HTMLCanvasElement | HTMLImageElement' is not assignable to parameter of type 'HTMLVideoElement'.
  Type 'HTMLCanvasElement' is not assignable to type 'HTMLVideoElement'.
```
But I thought ```drawImage``` accepts one of ```HTMLCanvasElement | HTMLImageElement | HTMLVideoElement```, isn't it?

**Comment by danquirk** [comment]
Unfortunately while ```drawImage``` does have 3 overloads which cover the three types you mention, that is not the same as actually accepting a union of those 3 types. See https://github.com/Microsoft/TypeScript/issues/1805 for some more discussion, these DOM APIs are certainly motivating examples for why we should consider the solution in that issue where we would special case single argument functions.
