### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by charescape** [microsoft/TypeScript#35021]
**TypeScript Version:**  3.7.2

**How to reproduce**

- (Step 1) Create file `test.js`
```js
(function () {
  var obj = {};
  /**
   * test test
   * @constructor
   * @remind remind
   * @param { Object } options param
   * @example
   * ```javascript
   * var editor = new UE.Editor();
   * editor.execCommand('blod');
   * ```
   * @see TEST.Config
   */
  var a = obj.a = function (options) {
    console.log(this)
  };
})();
```

- (Step 2) Create file `tsconfig.json`
```json
{
  "compilerOptions": {
    "outDir": "./built",
    "allowJs": true,
    "newLine": "lf",
    "target": "es5"
  },
  "files": [
    "test.js"
  ]
}
```

- (Step 3) Open git bash, run command `tsc`

**Expected behavior:**
no errors

**Actual behavior:**

```
$ tsc
C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:78566
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at getFlowTypeOfReference (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:42017:80)
    at tryGetThisTypeAt (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:43171:28)
    at checkThisExpression (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:43135:24)
    at checkExpressionWorker (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48624:28)
    at checkExpression (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48578:38)
    at checkExpressionWithContextualType (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48319:24)
    at getSignatureApplicabilityError (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:45667:35)
    at chooseOverload (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:46035:25)
    at resolveCall (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:45938:26)
    at resolveCallExpression (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:46256:20)
```

**Playground Link:** 

**Related Issues:**

**Comment by bugtype** [comment]
I think it's work well. what version of `tsc` are you using?
I have a question. why did you test the extension with `.js`?

**Comment by nmain** [comment]
> I think it's work well. what version of `tsc` are you using?

I was able to reproduce the same issue trivially by following the exact steps given using `typescript@3.7.2`

> I have a question. why did you test the extension with `.js`?

Presumably the issue depends on Typescript's js support.

**Comment by a-tarasyuk** [comment]
Shorter version to reproduce the issue

```ts
let b;
/**
 * a
 * @constructor
 */
const a = b = function () {
  console.log(this);
};
```

---

<details>
<summary>Details</summary>

The issue occurs because `getDeclaredTypeOfSymbol` cannot determinate `thisType`.

```ts
function checkThisExpression(node: Node): Type {
  ...
  let container = getThisContainer(node, /* includeArrowFunctions */ true);
  ...
  const type = tryGetThisTypeAt(node, /*includeGlobalThis*/ true, container);
  ...
}
```

```TS
function tryGetThisTypeAt(
  node: Node,
  includeGlobalThis = true,
  container = getThisContainer(node, /*includeArrowFunctions*/ false)
): Type | undefined {
    ...
      const classType = (
        getDeclaredTypeOfSymbol(getMergedSymbol(container.symbol)) as InterfaceType
      ).thisType!;
      return getFlowTypeOfReference(node, classType);
    ...
}
```


```TS
function getDeclaredTypeOfSymbol(symbol: Symbol): Type {
  return tryGetDeclaredTypeOfSymbol(symbol) || errorType;
}

function tryGetDeclaredTypeOfSymbol(symbol: Symbol): Type | undefined {
  if (symbol.flags & (SymbolFlags.Class | SymbolFlags.Interface)) {
    return getDeclaredTypeOfClassOrInterface(symbol);
  }
  if (symbol.flags & SymbolFlags.TypeAlias) {
    return getDeclaredTypeOfTypeAlias(symbol);
  }
  if (symbol.flags & SymbolFlags.TypeParameter) {
    return getDeclaredTypeOfTypeParameter(symbol);
  }
  if (symbol.flags & SymbolFlags.Enum) {
    return getDeclaredTypeOfEnum(symbol);
  }
  if (symbol.flags & SymbolFlags.EnumMember) {
    return getDeclaredTypeOfEnumMember(symbol);
  }
  if (symbol.flags & SymbolFlags.Alias) {
    return getDeclaredTypeOfAlias(symbol);
  }
  return undefined;
}
```

I noticed that for the following definitions, the `container` _(`this` parent)_ has different symbol `flags` which used to get a `type`.

```TS
/**
 * a
 * @constructor
 */
const a = function () {
  console.log(this); 
};

/**
  * container.symbol.flags =>  "Function|Class" 
  */

```

```ts
let b;
/**
 * a
 * @constructor
 */
const a = b = function () {
  console.log(this);
};

/**
  * container.symbol.flags =>  "Function" 
  */
```

Due to `container.symbol.flags` equals to `"Function"`, not to `"Function|Class"`, `tryGetDeclaredTypeOfSymbol` cannot determine type, and TS _crashes_. 

@RyanCavanaugh @sandersn Is it acceptable fix by adding an additional condition to check `thisType` on `errorType`? Or the issue related to `parser`?

</details>

**Comment by sandersn** [comment]
No, it's more likely that the binder doesn't recognise this construction as a class and doesn't mark it with the `Class` flag. When that flag is missing, the code in the checker that adds `thisType` doesn't run, and subsequent code (like this) will crash.

It's probably related to syntactically locating `@constructor` on `b` or `a` in the binder in order to mark the anonymous function as a class.
I fixed a number of similar bugs for 3.7: 

- https://github.com/microsoft/TypeScript/issues/34346
- https://github.com/microsoft/TypeScript/issues/33993

**Comment by ZumelzuR** [comment]
I'm using angular 5 and ionic v3. For me work these changes:
`"@angular/cli": "^1.5.5",
"@types/node": "^9.6.55",
"typescript": "3.7.4",
"@ionic/app-scripts": "3.2.3",`

Be sure to remove your node_modules and do `npm cache clean -f`, then `npm i` (maybe will be good also remove your package-lock.json)

**Comment by ErVishalM** [comment]
Hi,
I'm getting the error
`**ERROR in TypeError: Cannot read property 'flags' of undefined**`
When i updated to latest angular-cli packages 
previous version
```
"@angular/animations": "^9.1.4",
"@angular/common": "^9.1.4",
"@angular/compiler": "^9.1.4",
"@angular/core": "^9.1.4",
"@angular/forms": "^9.1.4",
"@angular/platform-browser": "^9.1.4",
"@angular/platform-browser-dynamic": "^9.1.4",
"@angular/router": "^9.1.4",

```
current updated to latest which is
```
"@angular/animations": "^9.1.5",
"@angular/common": "^9.1.5",
"@angular/compiler": "^9.1.5",
"@angular/core": "^9.1.5",
"@angular/forms": "^9.1.5",
"@angular/platform-browser": "^9.1.5",
"@angular/platform-browser-dynamic": "^9.1.5",
"@angular/router": "^9.1.5",
```
Can somebody help me please.

**Comment by isipro** [comment]
Same here. 
Just added a new 9.1.4 Angular project and serve gives the error
**ERROR in TypeError: Cannot read property 'flags' of undefined**

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0


Thanks for your advise!

**Comment by JoshuvaGeorge03** [comment]
Same here, I am having this error too.  after updating from angular 9.1.4  to 9.1.5

`
"@angular/animations": "^9.1.5",
"@angular/common": "^9.1.5",
"@angular/compiler": "^9.1.5",
"@angular/core": "^9.1.5",
"@angular/forms": "^9.1.5",
"@angular/platform-browser": "^9.1.5",
"@angular/platform-browser-dynamic": "^9.1.5",
"@angular/router": "^9.1.5",
`

how to fix this issue?

**Comment by SourabhJha** [comment]
Same here ,just tried 

![image](https://user-images.githubusercontent.com/8576915/81402656-d1414f80-90ff-11ea-9c08-f68cbe116bf5.png)

**Comment by isipro** [comment]
> 9.1.4
@JoshuvaGeorge03 DId it work on 9.1.4 ? 

Can you compare the package.json? 
Something else must have updated which broke it

**Comment by neon096** [comment]
I'm having same issues on 9.1.4

**Comment by reidsci** [comment]
Same here. Created a new app just a few hours ago and got the same error set as others before in this thread.

> Angular CLI: 9.1.4
Node: 12.4.0
OS: win32 x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by shikhasreekumar99** [comment]
Please help...! Any solution for the latest update?????????
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:65165:24)
    at C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (C:\Users\user-pc\Angularwithspringboot\node_modules\typescript\lib\typescript.js:98688:20)   
2m

**Comment by JadedEric** [comment]
Trying to downgrade to lower than 9.1.4 also does not work. Tried deleted the node_modules and the package-lock.json file and re-installing the packages once downgrade completed, persists the error.

Initially thought it was a local installation issue, but found that each new command afterwards pulls this broken typescript.js file down, so uninstalled node/npm completely and reinstalled it. then tried to re-install angular 9.1.0 globally and 9.1.0 for a new app.

Nada. Still broken. I believe this is a bigger issue than just a broken TS file?

**Comment by isipro** [comment]
BTW, this is a closed issue.
I have just reported it with Angular here  (its just a brand new installation for me )

https://github.com/angular/angular/issues/37002

**Comment by neon096** [comment]
Downgrade worked for me 

https://stackoverflow.com/questions/61670882/error-in-typeerror-cannot-read-property-flags-of-undefined/61671596#61671596

**Comment by Saxon-Liu** [comment]
I have the same problem, It worked yesterday。
I use` ng new` created a new project and `ng serve --open`

> @angular-devkit/architect    0.901.4
@angular-devkit/core         9.1.4
@angular-devkit/schematics   9.1.4
@schematics/angular          9.1.4
@schematics/update           0.901.4
rxjs                         6.5.4
typescript 3.8.3

> ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:65165:24)
    at e:\mission\js\task6\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (e:\mission\js\task6\node_modules\typescript\lib\typescript.js:98688:20)

somebody can help me?

**Comment by shikhasreekumar99** [comment]
solution : 
1) npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

2) npm install

3) ng serve

**Comment by boukhemis11** [comment]
Something is broken in Angular 9.1.5 - if you run the following it should work:

npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

ng build
Just spent about 4-5 hours trying to fix it myself...

The issue seems to stem from using Angular CLI 9.1.4 with Angular 9.1.5 (most likely the compiler

You'll see the issue when you do

ng --version
if you get:

Angular CLI: 9.1.4
Node: 12.16.3
OS: win32 x64

Angular: 9.1.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes
Then you will need to follow the npm installs i listed above

**Comment by JoshuvaGeorge03** [comment]
Do delete node_modules and delete package-lock.json

and run 

`
npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
ng build
`

and do ng serve.

it worked for me.

**Comment by imabdullah** [comment]
> solution :
> 
> 1. npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> 2. npm install
> 3. ng serve

this worked for me. Thanks

**Comment by Saxon-Liu** [comment]
> solution :
> 
> 1. npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> 2. npm install
> 3. ng serve

it's worked.   thanks

**Comment by nikitanewmsk** [comment]
in addition, I had to execute a separate `npm install` to install the remaining modules, and only then a ng serve.

**Comment by tigerjherold** [comment]
> Something is broken in Angular 9.1.5 - if you run the following it should work:
> 
> npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> 
> ng build
> Just spent about 4-5 hours trying to fix it myself...
> 
> The issue seems to stem from using Angular CLI 9.1.4 with Angular 9.1.5 (most likely the compiler
> 
> You'll see the issue when you do
> 
> ng --version
> if you get:
> 
> Angular CLI: 9.1.4
> Node: 12.16.3
> OS: win32 x64
> 
> Angular: 9.1.5
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
> Ivy Workspace: Yes
> Then you will need to follow the npm installs i listed above

This works for me. Thanks.

**Comment by FerreirasDenise** [comment]
> solution :
> 
> 1. npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> 2. npm install
> 3. ng serve

This worked for me.
Thanks

**Comment by nikitanewmsk** [comment]
> > solution :
> > 
> > 1. npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> > 2. npm install
> > 3. ng serve
> 
> This worked for me.
> Thanks

this is only downgrade, not fix

**Comment by ErVishalM** [comment]
Hi @nikitanewmsk Thank you so much for immediate reply. But it is I'd done waiting for fix now. :)

**Comment by UmarGit** [comment]
Hello everyone , My **problem** is solved by downgrade which is probably not a fix at all but it works ! @shikhasreekumar99 : thank you 👍 

### Step 1 : 👍 
`Permanently delete your node modules. `

### Step 2 : 👍 
**RUN THIS COMMAND ON YOUR CONSOLE**
`
npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4`

### Step 3 : 💯 
**CONGRATULATIONS YOU SUCCESSFULLY DOWNGRADED THE DEPENDENCIES AND THE TYPEERROR IS RESOLVED SUCCESSFULLY**
Now you may try these !
`
ng serve --open
ng build
.............etc`
### SCREEN SHOT OF SUCCESFULL NG SERVE
![Capture](https://user-images.githubusercontent.com/39865635/81423390-cd4c1680-916d-11ea-9f58-c7a8ba816bda.PNG)

**Comment by Proposito** [comment]
> solution :
> 
> 1. npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> 2. npm install
> 3. ng serve

its worked for me!
Thanks

**Comment by nojvek** [comment]
I'm getting same error while tsc tries to compile highcharts.js which has code like this

```js
  /**
 * @constructor
 */
  var VMLRenderer, VMLElement;
  if (!hasSVG && !useCanVG) {
```

using tsc 3.8.3 with node 10. 

Interestingly babel doesn't fail, but tsc does.

**Comment by exomc** [comment]
Same error angular 10. Tried downgrading to 9.1.4, no difference, nothing works

 "dependencies": {
    "@angular/animations": "^10.0.3",
    "@angular/common": "^10.0.3",
    "@angular/compiler": "^10.0.3",
    "@angular/core": "^10.0.3",
    "@angular/forms": "^10.0.3",
    "@angular/language-service": "^10.0.3",
    "@angular/platform-browser": "^10.0.3",
    "@angular/platform-browser-dynamic": "^10.0.3",
    "@angular/router": "^10.0.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^9.2.0",
    "@angular-devkit/build-angular": "^0.1000.2",
    "@angular/cli": "^10.0.2",
    "@angular/compiler-cli": "^10.0.3",
    "@types/jasmine": "~3.5.11",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.0.23",
    "buffer": "^5.6.0",
    "child_process": "^1.0.2",
    "codelyzer": "^6.0.0",
    "eslint": "^7.4.0",
    "fs": "0.0.1-security",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.2",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~3.3.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "net": "^1.0.2",
    "process": "^0.11.10",
    "protractor": "~7.0.0",
    "tls": "0.0.1",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.2",
    "typescript": "^3.9.6"
  }

**Comment by knaos** [comment]
Are you using Yarn? I am getting this error when using yarn

**Comment by sijakret** [comment]
still an issue.
facing the same with angular 10

"@angular/animations": "^10.1.0",
    "@angular/common": "^10.1.0",
    "@angular/compiler": "^10.1.0",
    "@angular/core": "^10.1.0",
    "@angular/forms": "^10.1.0",
    "@angular/platform-browser": "^10.1.0",
    "@angular/platform-browser-dynamic": "^10.1.0",
    "@angular/router": "^10.1.0",
    "@angular-devkit/build-angular": "~0.1001.3",
    "@angular/cli": "~10.1.3",
    "@angular/compiler-cli": "^10.1.0",
    "@angular/language-service": "^10.1.0",
