### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by jin-yuting** [microsoft/TypeScript#35022]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**
泛型里面，下面这句话多了一个“的”
 因为此时 T的的类型为number。

**Comment by MartinJohns** [comment]
You seem to have forgotten to fill out the entire issue template.

**Comment by Albert-Gao** [comment]
Needs to be more specific, not even able to understand the context of the Chinese wording...

**Comment by xiaoxiangmoe** [comment]
@jin-yuting  

This is not a problem with this repo. 

see https://github.com/mishengqiang/tslang.cn/blob/e3e6df07ec2c53830681cb289963d88b1f82c9a8/src/docs/handbook/generics.html#L119

Please fill this https://github.com/mishengqiang/tslang.cn/issues/new

这不是这个git仓库的问题。

你的问题是这行代码的问题：https://github.com/mishengqiang/tslang.cn/blob/e3e6df07ec2c53830681cb289963d88b1f82c9a8/src/docs/handbook/generics.html#L119

请填写这个表单来提 issue https://github.com/mishengqiang/tslang.cn/issues/new

（友情提示： TypeScript中文网和微软没有直接关系，是社区维护的网站，资料已经落后很多个版本来）
