### ISSUE TITLE
Type Assertion to Object value when key is const variable

### ISSUE THREAD

**Issue by tbvjaos510** [microsoft/TypeScript#35020]
## Search Terms
type assertion object value
type assertion array value
type assertion object value when key is variable
type assertion array value when index is variable

## Suggestion

Type assertion Object value when object key is const variable.
Object value type is fixed because index not changed in runtime, but type assertion not working..
## Use Cases
It works well in now when a key is explicitly entered  
I hope type assertion when key is variable.
Implementing is likely to be complex, but I think it is one of the necessary functions.

### With Object
```typescript
const obj: {
  [key: string]: number | string;
} = {
  a: 3,
  b: ""
};

const key = "a";
if (typeof obj[key] === "string") {
  obj[key].split(); // current: Property 'split' does not exist on type 'string | number'
}

```

### With Array
```typescript
const arr: Array<string | number> = [];
const index = 1;
if (typeof arr[index] === "string") {
  console.log(arr[index].split()); // current: Property 'split' does not exist on type 'string | number'
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplicate of #10530 (and plenty of more). Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

You can easily solve this by just storing the value in a variable.

**Comment by tbvjaos510** [comment]
Thanks you!
