### ISSUE TITLE
Unsupported --target ES6

### ISSUE THREAD

**Issue by si-robertson** [Microsoft/TypeScript#3502]
Hi,

I have just installed TSC 1.0.3 via NPM. According to a [MSDN blog article](http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx) regarding TS 1.4, posted in Janurary, we should be able to `--target` ES6 now. Unfortunately, setting `--target` to ES6 results in a 5002 error `ECMAScript target version ES6 not supported`.

**Comment by DanielRosenwasser** [comment]
> I have just installed TSC 1.0.3 via NPM. According to a MSDN blog article regarding TS 1.4

This is your problem. TS 1.0.3 is older than 1.4, so you should probably install TypeScript 1.4. You can even install 1.5 beta at this point if you're really interested in ES6 compatibility.

**Comment by si-robertson** [comment]
Ah, fair enough. Thanks Daniel. I will grab the source files from here and use the tools directly.

**Comment by DanielRosenwasser** [comment]
You can clone the basically ready `release-1.5` branch, or if you'd like to play around with `master` that works too.

You can still do `npm install -g typescript` to get 1.4 right now or `npm install -g typescript@1.5.0-beta` to get the beta.
