### ISSUE TITLE
type - language service filtering not working when object type with similar value is present

### ISSUE THREAD

**Issue by prakulgupta** [microsoft/TypeScript#35033]
Refer below code snippet - When using sharedComponent type, the language doesn't filter available values correctly. Like in case shown below in componentName options App2Component1 should not be there as it is part of Application2.

![image](https://user-images.githubusercontent.com/6064632/68582384-9340d700-04a0-11ea-9fb6-9fac7572b2ae.png)

When repeating appName with different componentName then this breaks and starts showing all options.

**Code**
```ts
type sharedComponent = { appName: "Application1", componentName: "App1Component1" } |
{ appName: "Application2", componentName: "App2Component1" } |
{ appName: "Application1", componentName: "App1Component2" }

let abc: sharedComponent;
abc = {appName:"Application1", componentName:""}

```

**Expected behavior:**
When giving appName "Application1", componentName options it should show only App1Component1 and App1Component2. 

**Actual behavior:**
It's giving all the options in componentName. i.e App1Component1, App1Component2 , App2Component1

Tested in Version - 3.7.2

**Comment by RyanCavanaugh** [comment]
This is the intended behavior - if we filtered these down more aggressively based on other properties, it'd be impossible to "switch" from one of the constituents to the other via the completion list.
