### ISSUE TITLE
tsc.ps1 presence in %appdata%\npm

### ISSUE THREAD

**Issue by Cerlancism** [microsoft/TypeScript#35031]
I am not sure why there are ps1 files for tsc and tsserver and now I longer able to use tsc on PowerShell as I got the error 
> tsc.ps1 cannot be loaded because running scripts is disabled on this system

I tried to install tsc on my other Windows 10 machine, it does not come with ps1 files.

**TypeScript Version:**  Version 3.7.2

**Search Terms:**
tsc.ps1
tsc.ps1 cannot be loaded because running scripts is disabled on this system

**Comment by Cerlancism** [comment]
Loo

**Comment by Cerlancism** [comment]
Looks like the current npm version will include a ps1 script for global packages.

**Comment by AviVahl** [comment]
Npm fixed it in 6.13.0 https://github.com/npm/cli/pull/281

**Comment by Cerlancism** [comment]
> 
> 
> npm fixed it in 6.13.0 [npm/cli#281](https://github.com/npm/cli/pull/281)

It is not about uninstalling though. 

It looks like everyone who is using Powershell(basically all Windows VSC terminal users)from now on needs to set the flag (RemoteSigned?) to use global npm packages

**Comment by AviVahl** [comment]
Ouch. Might want to report this behavior change in the npm/cli repository: https://github.com/npm/cli/issues

**Comment by fatcerberus** [comment]
Indeed - just for the heck of it I opened PowerShell just now:

```ts
PS C:\Users\fatce> tsc
tsc : File C:\Users\fatce\AppData\Roaming\npm\tsc.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ tsc
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

Not very nice, and I use `cmd` so I never noticed!  This isn't a TypeScript issue, though.

**Comment by v-katmas** [comment]
I had the same issue. Need to run PowerShell as Admin and set the execution policies. In Win10 updates PowerShell has some restrictions for outer scripts. I've set the rights to the policies, but it didn't worked.
I decided to use Git Bash because it's easier for me and there is no issues.

**Comment by haiderlasne** [comment]
To fix it you have to run the command below to run Set-ExecutionPolicy and change the Execution Policy setting.
open PowerShell 
cd C:\Windows\System32>
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypassts

**Comment by MikeInSwitzerland** [comment]
Haiderlasne had the correct solution (but there was a subtle error)

```
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

```

**Comment by Skumbl** [comment]
The works for the current session, I just set mine for my local machine

`Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy Bypass`
