### ISSUE TITLE
Adding JVM like enum classes

### ISSUE THREAD

**Issue by RobbinBaauw** [microsoft/TypeScript#35039]
## Search Terms
- Enum class
- JVM

## Suggestion
The JVM has the concept of enum classes, which provide a couple of advantages over enums currently implemented in TypeScript or over using `public static final` fields (taken from [this SO question](https://stackoverflow.com/questions/9969690/whats-the-advantage-of-a-java-enum-versus-a-class-with-public-static-final-fiel), these are just a few of many advantages listed there):
- Useful methods (`.values()`, giving the ability to loop over all values, `.name()`)
- Type safety and value safety.
- Guaranteed singleton.

My suggestion would be to add a similar concept to TypeScript, with a syntax similar to Java / Kotlin. I would see this as an addition and not a replacement of the current enums, for backwards compatibility.

Some other advantages this would have:
- The ability to implement an interface on an enum
- Improving type constraints, solving https://github.com/Microsoft/TypeScript/issues/30611 for example. This would even allow you to add a following type constraint: `E extends Enum<E> & SomeInterface<E>`. This could also be useful in defining mapped types.
- Having the ability to get an enum value based on the string value of the name (`Enum.valueOf()`)

## Considerations
- The compiler should enforce that `Enum<E extends Enum<E>>` is not extended by any class
- The constructor of the enum arguments should enforce all values to be `readonly`
- In order to support the aforementioned methods in the `Enum` class, it should keep track of the values in some way

## Examples
I think this would (almost) be possible with the current TypeScript and a preprocessor:

### Input:
```typescript
interface SomeInterface { 
    getANumber(): number;
}

enum class FancyEnum implements SomeInterface {
    VALUE(1),
    VALUE2(2);

    // Readonly = implied / forced
    constructor(private readonly a: number) { }

    getANumber() {
        return this.a;
    }
} 
```

### Could map to:
```typescript
class Enum<E extends Enum<E>>{
  // Many useful methods
}

class FancyEnum extends Enum<FancyEnum> implements SomeInterface {

    public static readonly VALUE = new FancyEnum(1);
    public static readonly VALUE2 = new FancyEnum(2);

    constructor(private readonly a: number) { 
        super();
    }

    getANumber() {
        return this.a;
    }
}
```

## Checklist
My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code (my suggestion would be adding the `enum` keyword before `class` instead of removing the current enum)
* [X] This wouldn't change the runtime behavior of existing JavaScript code (it will add functionality, it shouldn't do anything to the current enums)
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
Since this has runtime impact, it falls under

> non-ECMAScript syntax with JavaScript output

and is therefore not likely to be considered.  The existing `enum` was introduced before this policy was put into place and therefore falls under the grandfather clause, but nowadays if you want something like this you need to propose it to TC39 and get it to Stage 3 before TS will consider implementing it.

**Comment by jcalz** [comment]
Isn't this a runtime feature?  Specifically `enum class` is "non-ECMAScript syntax with JavaScript output".  (I suppose the fact that `enum` exists at all is just an indiscretion of a youthful language and not indicative that further runtime dabblings will be allowed.  Ah, to be young and free again!)

**Comment by RobbinBaauw** [comment]
Yes it would be a runtime feature, I'm sorry! I was not aware of the fact that these kinds of requests would (likely) only be considered if it was a stage 3 TC39 proposal. I removed the check mark accordingly.

**Comment by fatcerberus** [comment]
No problem, just wanted to let you know so you don't get your hopes up about it being implemented any time soon :wink:

For what it's worth I believe there's an official `enum` proposal that IIRC might work a bit like this.  Not *quite* as fancy, but still fancier than what TS offers.

**Comment by nmain** [comment]
Here's a potential TC39 proposal: https://github.com/rbuckton/proposal-enum

Not sure what the status of it is

**Comment by fatcerberus** [comment]
Stage 0. 😮  It um, it has a ways to go.  Also it seems that the proposal is by a TS developer, @rbuckton.

**Comment by hinell** [comment]
Such class may be easily implemented outside of the language by standard means.

**Comment by RobbinBaauw** [comment]
Yes I think so too, some pre-processor should be able to do this. Then you'd get the problem of no IDE support though :( 

As this issue probably won't be considered I will look at some other options of solving this
