### ISSUE TITLE
Version 3.7.2 has 3.7.0 in package.json

### ISSUE THREAD

**Issue by dantonel** [microsoft/TypeScript#35044]
**TypeScript Version:**  3.7.2 and 3.8.0-dev.20191105

**Search Terms:**
3.7.2
package.json
version

**Code**
```
yarn add typescript
```
or
```
yarn add typescript@next
```

**Expected behavior:**
installed version's package.json version number should match the version npm/yarn thought it installed

**Actual behavior:**
For both 3.7.2 and @next, the package.json file line 5 says:
`"version": "3.7.0",`

This causes my IDE (PHPStorm) to report that an incorrect version of typescript has been installed.

**Playground Link:** 
nope

**Related Issues:** 
nope

**Comment by weswigham** [comment]
I just did an `npm i typescript` in a project with a `typescript` version set to `^3.7.0` and definitely downloaded a package with version string `3.7.2` - are you sure there's not a version constraint in the project you're installing in that's preventing you from installing the latest version? `3.7.0` was the _beta_ (and was tagged/named as a prerelease), so if you have an explicit beta version string in your package, you'll need to edit it away, as an exact prerelease version match will prevent installing a later non-prerelease version.
