### ISSUE TITLE
Typed arrays should be classes.

### ISSUE THREAD

**Issue by si-robertson** [Microsoft/TypeScript#3506]
Hi guys,

The following code is valid in JavaScript.

````javascript
class Matrix extends Float32Array {
    constructor() {
        super(9);
    }
}
````

Unfortunately that isn't possible to do in TypeScript at the moment because all of the typed arrays appear to be interfaces, and there are also some weird interfaces such as `Float32ArrayConstructor` floating around which confuse matters.

**Comment by kitsonk** [comment]
Dup of #1168

**Comment by si-robertson** [comment]
In that case, consider this issue a friendly reminder that the seven month old bug still exists :)

**Comment by DanielRosenwasser** [comment]
It's on [the roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap) for TypeScript 1.6.
