### ISSUE TITLE
 When tsc targeting esnext, typeScript 3.7 optional chaining feature does not working

### ISSUE THREAD

**Issue by cheblin** [microsoft/TypeScript#35072]
So it is impossible to use **optional chaining** and **BigInts** simultaneously

**Comment by MartinJohns** [comment]
Please use the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md).

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
