### ISSUE TITLE
TS ignores IF statement. Causes error: "Property X does not exist on type of import(“…”)" 

### ISSUE THREAD

**Issue by akopchinskiy** [microsoft/TypeScript#35089]
One module exports function "A". Second module exports functions "A" and "B".

At first I need to create a map array, like this:

```ts
const map = [
  {
    name: 'A',
    data: moduleA
  },
  {
    name: 'B',
    data: moduleB
  }
];
```

I'm trying to run functions "A" and "B" in a cycle like this:

`item.data.A('some data');`

```ts
if(item.data && item.data.B)    // here's error
    item.data.B('other data');
```

But getting this weird error:

`Property 'B' does not exist on type 'typeof import(".../moduleA")'`

Codesandbox live example: https://codesandbox.io/s/youthful-joliot-qyihx

**Comment by nmain** [comment]
Simplified repro (in .ts mode, but the same exact thing applies in .js mode): [Playground](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAhjAvDA3gWAFA2zAJiAFQAsBLCACgEpUZRIQAbAUwDoGQBzcgIgSlIjdqAXwA0mHHkJE4UKjToRGrdl14x+soTGGZdGTItgAjJKgk58xMvJS1wS5m049T-Mtv37DD2MDPoWJbSNtR2isrOav7ugiLiQdhWMnJh9vROqjwxKZ56mD6QsAC2MAD0AFSBksmhAFwwAG4gJLgJNdKyAPxUDc2tANwFGMIA2gC6FWVmo3CiMMbzwOPDAGYgAE4w5EYwJFBMpSCrMMVhFtj7hyy1FJQXeyfkV8U3nVDniZJ7B6-JslQHl5MEA)

**Comment by RyanCavanaugh** [comment]
The short version of this is
```ts
let m = { x: 1 }, n = { x: 1, y: 2 };
let a = [m, n];
if (a[1].y) { 
  a[1].y
}
```
Absent other hints, arrays will infer the element type based on the most general type amongst its elements.

**Comment by akopchinskiy** [comment]
@RyanCavanaugh 
`Working as Intended`
No it's not. It should consider `if` statement and not show this error. As in C# for example, which TS inspired by.

**Comment by akopchinskiy** [comment]
@nmain I found a workaround for this:

Replaced this part of code:
```ts
for(const item of map){
  item.data.doThis();
  
  if(item.data && item.data.doThat)
    item.data.doThat();
}
```

With this:
```ts
for(const item of map){
  item.data.doThis();

  const {
    data = {}
  } = item;
  
  if(data && data.doThat)
    data.doThat();
}
```

**Comment by nmain** [comment]
Seems kind of silly to jump through hoops just to try to fool the compiler, no?  Why not just annotate the type you want?

```js
/** @type Array<{ name: string, data: { doThis(): void, doThat?(): void } }> */
export const map = [ /* ... */
```

**Comment by akopchinskiy** [comment]
@nmain No. It's not a fooling of the compiler, It's telling to compiler the details he wants and it's more short than providing this looooong typing annotation.
Strange that the compiler is not smart enough to understand such easy type by itself.

**Comment by RyanCavanaugh** [comment]
@akopchinskiy language design involves trade-offs and this is an intentional trade-off. The behavior is intentional.
