### ISSUE TITLE
Empty class is treated as `any` in conditional types.

### ISSUE THREAD

**Issue by acrazing** [microsoft/TypeScript#35083]
**TypeScript Version:**  3.7.2

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

export class Foo {}
export type Bar<T> = T extends Foo ? { foo: number } : {};
export const foo: Bar<number> = {};
```

**Expected behavior:**

No errors

**Actual behavior:**

Got error:

```bash
Error:(139, 14) TS2741: Property 'foo' is missing in type '{}' but required in type '{ foo: number; }'.
```

**Playground Link:** 

<http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwF8AoUSWOGATzGDgCEUoAeAFQD44BeOVuUGMAB2AE0w48AfgJwAZrgBccIQFcAtgCNgUOIThKiAblLho8BBCFp48iEsYtVm7Zx5HiQA>

**Related Issues:**

**Comment by AnyhowStep** [comment]
You really should have no need for an empty class.
To TS, that is a type with no properties.

`number` is a type that has all the properties of the empty object/class.

In fact, every type has all the properties of the empty object/class... Except `null` and `undefined`.
