### ISSUE TITLE
Cant iterate over Array.prototype.entries inside for of loop

### ISSUE THREAD

**Issue by n-filatov** [microsoft/TypeScript#35080]
I have a problem to iterate inside ```for of``` loop over ```array.entries()```. Compiled version of code trys to get ```length``` property of ```array.entries``` but this property is undefined, coz ```array.entries``` returns ```Iterator``` which has not ```length``` property.
**Code**

```ts
const a: any = [1, 2, 3];

for (const x of a.entries()) {
    console.log(x)
}
```

**Expected behavior:**
Code will iterate over a.entries and call console.log()

How it works in babel: [Babel Playground](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDA2gXQNwCgsDMQBOAFKJLAB4wi7wB0ApmFAQJb0RECUnMA3ljFIQQAG3q0RIAOZFynLAF8gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.7.3&externalPlugins=)

**Actual behavior:**
Nothing happens, coz no iteration.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/index.html?target=1#code/MYewdgzgLgBAhgLnmAnjAvDA2gRgDQwBMBAzALoDcAsAFC0BmIATjABSiSwAeMI98AOgCmYKEwCWQiKwCUMmAG9aMFTA4QQAGyEDNIAOasuM2gF8gA)

**Comment by nmain** [comment]
This is working as intended.  If you want full iterable semantics in downlevel emit, turn on the downlevel iteration compiler flag:  https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by n-filatov** [comment]
It is ok that my code wont works properly by default and i should use flags for it. I thought that when i set target as ES5 it will compile working code by default.

**Comment by nmain** [comment]
I believe this has been discussed before, but I couldn't find much in search.  In #https://github.com/microsoft/TypeScript/issues/34572 @DanielRosenwasser states "We have opinionated defaults for downlevel iteration." as a side comment but doesn't elaborate further.
