### ISSUE TITLE
React TSX: Default Props Ignored with Index Signature

### ISSUE THREAD

**Issue by chriszwickerocteris** [microsoft/TypeScript#35092]
**TypeScript Version:**
* 3.7.2
* Nightly

**Search Terms:**
defaultprops index signature

**Code**

```ts
import * as React from "react";

export interface FooOptions {
  x: string;
  y?: string;
  [key: string]: any; // remove this and everything is ok
}

interface FooProps extends FooOptions {
  a: boolean;
}

class Foo extends React.Component<FooProps> {
  public static defaultProps = {
    a: true,
  };

  public render() {
    return <div>Remove index signature from FooOptions to make this work</div>
  }
}

class App extends React.Component {
  public render() {
    return (
      <Foo x={""} />
    );
  }
}
```

**Expected behavior:**
Default property recognized as present

**Actual behavior:**
Error that parameter `a` is missing: `Property 'a' is missing in type '{ x: string; }' but required in type 'Readonly<FooProps>'`

**Playground Link:**
* [vNightly](http://www.typescriptlang.org/play/?jsx=2&ts=3.8.0-dev.20191112#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdWAHpLHMAHYxZQF5ZwAYhAgB5MDGAQO6AN504cJgC44qGFE4BzeooCeAflXrNHHQrgBtANZY9xjdoC6q5Bz004Aei9xKICAA3ARgAC2B0NwATOCxgqD0w7XZ0CGs6AF8GTm5efiERAAViMHRmbg4o9GExCSkZOHlFZFUAIxEAGxwOeiy6XA60apFYpgqqzCoYADoAYRJIDiwuAB4a4ohSgD5GizAAV1aO4Fw1GGRJU6isPn2OmA3SuABeXcVm1Q19rAAaCwz6HtDsdTpRKjwABQASje70oMH2UA4cBWUWAgS22ACwXY4KYamAWg4F0RAiIJAKtUk0nQMAgcBAyFscCS6AA7tBrCsvGiMf9MgwBkM4ABBMBgUbjdDYPAzebgaTLeBNOAHI4nPzLa5QaGwxTwxHIiEWd4ompKZ6yMhkDLeLYmuBQ3RwLJZIA)
* [3.7.2](http://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdWAHpLHMAHYxZQF5ZwAYhAgB5MDGAQO6AN504cJgC44qGFE4BzeooCeAflXrNHHQrgBtANZY9xjdoC6q5Bz004Aei9xKICAA3ARgAC2B0NwATOCxgqD0w7XZ0CGs6AF8GTm5efiERAAViMHRmbg4o9GExCSkZOHlFZFUAIxEAGxwOeiy6XA60apFYpgqqzCoYADoAYRJIDiwuAB4a4ohSgD5GizAAV1aO4Fw1GGRJU6isPn2OmA3SuABeXcVm1Q19rAAaCwz6HtDsdTpRKjwABQASje70oMH2UA4cBWUWAgS22ACwXY4KYamAWg4F0RAiIJAKtUk0nQMAgcBAyFscCS6AA7tBrCsvGiMf9MgwBkM4ABBMBgUbjdDYPAzebgaTLeBNOAHI4nPzLa5QaGwxTwxHIiEWd4ompKZ6yMhkDLeLYmuBQ3RwLJZIA)

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/23812

**Comment by weswigham** [comment]
Interestingly, as I recently mentioned [elsewhere](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34809#issuecomment-553057644), we don't actually implement any of the logic for checking `defaultProps` in the compiler - that's entirely in the domain of [the `react.d.ts` over on `DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2847). I'd re-file this over there, where one of the `.d.ts` file maintainers can take a look at it.

**Comment by weswigham** [comment]
Specifically, this is _probably_ a [known behavior for `defaultProps` types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2821), but don't consider me the authority here, I'm just reading the source~

**Comment by chriszwickerocteris** [comment]
Thanks for looking into it! I've opened https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40367
