### ISSUE TITLE
noImplicitAny ignores implicit any on yield expression assignment

### ISSUE THREAD

**Issue by TeoTN** [microsoft/TypeScript#35105]
**TypeScript Version:**  3.7.2 (playground)

**Search Terms:** generator implicitAny

**Code**

```ts
function* generator() {
    const value = yield;
    console.log(value);
}

const iterator = generator();
iterator.next();
iterator.next(5);
```

**Expected behavior:**
TypeScript Compiler with enabled `noImplicitAny` flag warns about implicit any with yield expression assignment.

```ts
function* generator() {
    const value: ExpectedType = yield call(fn); // Example from redux-saga
}
```

**Actual behavior:**
Yield expression is assigned implicitly as `any` because we're not able to infer the type. While I acknowledge that proper type check here is a difficult issue with quite a few other issues open, we should be forced to declare the expected type.

[Playground Link](http://www.typescriptlang.org/play/?ssl=2&ssc=8&pln=2&pc=9#code/GYVwdgxgLglg9mAVAAgOYFMzoE4EMpzYAUAlMgN4CwAUMnchAgM5TIBuuANiOsgLzIAnjHScAJgG4a9Bszid0AOk5xURDt3Qkp1AL40ajMC2QwoOfIX5pMFgsW00zdwoqwAPKKR3O89t+ieRACsjtRAA)

**Related Issues:**
* [#32523](https://github.com/microsoft/TypeScript/issues/32523)

**Comment by nmain** [comment]
Related https://github.com/microsoft/TypeScript/issues/32523
