### ISSUE TITLE
Inlined helpers generate undeclarated references

### ISSUE THREAD

**Issue by manucorporat** [microsoft/TypeScript#35108]
Seems like this issue was introduced at some point in 3.6.x, since it was working fine in 3.5.3.

**TypeScript Version:**  3.6.3 and Nightly

**Search Terms:** helpers name conflict 

**Code**

```ts
// Helpers come from a bundled dependency
function __awaiter() { }

// The generated code, references a non-existing __awaiter_1
async function func() {
}
```

**Expected behavior:**

The generated helpers declarations include an "id" to prevent the name conflict, and the references to the helpers point to the new name.

```ts
var __awaiter_1 = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    // ...
};
function __awaiter() { }
function func() {
    return __awaiter_1(this, void 0, void 0, function* () {
    });
}
```

**Actual behavior:**

Typescript emits the helper with the same name (`__awaiter`) causing a name conflict with existing declarations, but the emitted references point to `__awaiter_1`, generating in fact, JS that errors at runtime, with "__awaiter_1 is undeclarated".

```ts
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    // ...
};
function __awaiter() { }
function func() {
    return __awaiter_1(this, void 0, void 0, function* () {
    });
}
```

**Playground Link:** https://www.typescriptlang.org/play/index.html?target=3&ts=3.6.3#code/PTAEBUAsEsGdQMYHsC2BTeAzATq0BDUAIwFcA7AEwBs0LQK0AHNSlhATwChNyEAXaEjKgA+iPwB3fND5psACgCUoAN6gAvp04gIkNKADmLOfll1kDADShsaTHLYYCoMkIC0aAB5wBZA6PEpGTkRAEZOfFh2MgRQHhiBITjeJVVOTSA

**Comment by manucorporat** [comment]
I want to point out that the conflict with inlined ts helpers comes after bundling dependencies that already have the helpers inlined, so it's not really up to the user to prevent the conflict the conflicts by choosing a different function name.

**Comment by RyanCavanaugh** [comment]
Duplicate #33547
