### ISSUE TITLE
Wrong function return type inference (union type parameter)

### ISSUE THREAD

**Issue by SherloxFR** [microsoft/TypeScript#35106]
**TypeScript Version:**  3.8.0-dev.20191114

**Search Terms:** Wrong union type parameter function result type inference

**Code**

```ts
interface ITestRequired {
    key: string
    ignoredKey: string
}

interface ITestOptional {
    key?: string
    ignoredKey?: string
}

export const unwrapTestObject = ({ key }: ITestRequired | ITestOptional) => ({ key })

// testObj is of ITestRequired type
const testObj: ITestRequired = {
    key: 'test',
    ignoredKey: 'test'
}

const testFilter = unwrapTestObject(testObj)

// testFilter.key should always be a string here, but instead we get
// testFilter.key is possibly 'undefined'.
console.log(testFilter.key.substring(0, 2))
```

**Expected behavior:**
Output type should be inferred from input type even when using Union types (because it is specified in the parameter type).

**Actual behavior:**
Parameter type is totally ignored.

[**Playground Link**](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191113&ssl=1&ssc=1&pln=21&pc=44#code/JYOwLgpgTgZghgYwgAgJIBUIGcwCUICOArsFBACbIDeAUMvcgNYQCeAXMjlKAOZ0PAeIAPZlyAaVYcuvGgF8aNUJFiIUGbGADyABzDBhIOABtq-esxYB+aWG4g+DZIJFjJ12-b4KaEAB46omDICIY4yEQgAO5QcDqYOFoARgBWEAjBALzIABRUTKzIchwaOPjEpBTIAD5oCdp6BkbGAJTImQB8ufmWRS2KAPQDyJCJqc5YyMIwdZrlJGIjLDoQNKEg4aPaqSX185WU2bROlhwA5FtnADTmzkKiFO7nl-KDw1sAYsDGKgB0vVgABbCIjGShJFBwTh2XjIQHQCBXZBJIjBYDBBBwEDIExYYTIlCRcgQGCgCi-NZhYKfb4qdoRaKxeKaZJpDI5Las-rrPHGCC-YzCHgczRfH7Qf6sX5YIhJGQOHIABiRACYWi0gA)

**Related Issues:**
Did not find anything similar.

**Comment by AnyhowStep** [comment]
Are you looking for generic functions?

**Comment by SherloxFR** [comment]
@AnyhowStep like so ?

```
export const unwrapTestObject = <T>({ key }: T) => ({ key })
```

indeed it seems to do the job, but I'm getting `Property 'key' does not exist on type 'unknown'.` as I'm trying to destructure the parameter (seems like TS generics and destructuring are not friends from what I could find in the issues).

[Playground Link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191113&ssl=11&ssc=61&pln=11&pc=1#code/JYOwLgpgTgZghgYwgAgJIBUIGcwCUICOArsFBACbIDeAUMvcgNYQCeAXMjlKAOZ0PAeIAPZlyAaVYcuvGgF8aNUJFiIUGbGADyABzDBhIOABtq-esxYB+aWG4g+DZIJFjJ12-b4KaEAB46omDICIY4yEQgAO5QcDqYOFoARgBWEAjBALzIADzoAHwAFFRMrMhyHOgAlMiZ+cjFpSzlVYoA9G3IkImpzljIwjBoCXiEJGJdLDoQNKEg4d3aqRwaOPjEpBS1Zk6WHADki-sANObOQqIU7gdH8u2diwBiwMYqAHSWnAAWwkTGlEkUHBOHZeMgvtAIMdkEkiMFgMEEHAQMgTFhhDCUJFyBAYKAKG9ZmFgk8XiptpEYnERsk0hlCotaa05ujjBA3sZhDwGZpnq9oB9WG8sEQkjIHIUAAzQgBMVSqQA)

**Comment by jcalz** [comment]
More like 
```ts
const unwrapTestObject = <T extends ITestOptional>({ key }: T): Pick<T, "key"> => ({ key })
```

The compiler is working as intended (the compiler doesn't [distribute control flow analysis over union types](https://github.com/microsoft/TypeScript/issues/25051)); you might consider closing this issue.  Good luck!

**Comment by SherloxFR** [comment]
That's a bit complicated but thanks it's working !
I was simply hoping for something more "generic" ^^

Sorry I opened a bug report for this.
