### ISSUE TITLE
TS 1.5 release

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/TypeScript#3510]
When 1.5 will be released?
Does it wait for VS 2015 release time?
If so, please split VS plugin from language itself and do not block language/tools from usage.

**Comment by lazutkin** [comment]
:+1:

**Comment by mhegazy** [comment]
We usually like to stabilize releases a few weeks before we ship them. release-1.5.2 is now in the final stabilization stages. no more features going in just critical bug fixes. so stay tuned.

you can always grab the latest from [release-1.5](https://github.com/Microsoft/TypeScript/tree/release-1.5/bin) and give it a try, and use [dev mode](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio) to update your language service.

**Comment by wgebczyk** [comment]
... and by accident you sufficiently stabilize that in the moment of VS 2015 rtm?
... and other outstanding things will be silently moved to milestone 1.6 or later...?

Do you really want to stabilize that and solve ALL bugs as of current time?

**Comment by mhegazy** [comment]
release-1.5 is the branch where the release is coming from. we have been submitting fixes, as late as yesterday. so i do not think it is ready yet. we try to keep the issues in sync. new issues will go to 1.6 as we want to minimize new changes to the 1.5 release. hopefully this will be ready within a few weeks. 
We align with the VS release scheduled, but this is not the main diving force here. release-1.5 has been packed with feature work, and we just need to fix some critical issues before putting it out.
Orthogonal the next release will have the TS pieces completely detached from VS.
