### ISSUE TITLE
Consider some strategy for handling "preview" files in TSServer that don't need full project information

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35114]
Today, navigating to a file in another project for a preview will load an entire project. Bad! Much of the time, a user might only care about certain operations (e.g. outlining, brace matching, whatever).

There's basically two high-level ideas here:

* A new file open request, or meta information, that tells the semantic server that it shouldn't try to fully load the full program until a semantic operation occurs
* Editors will "know better" and only dispatch to a separate syntactic server. This requires no work from our end, but we should acknowledge that that's the path forward. (@mjbvz)

**Comment by DanielRosenwasser** [comment]
Let's talk about this at tomorrow's editor sync.

**Comment by DanielRosenwasser** [comment]
One question that came out was whether we could have a "naive mode" for preview tabs. The idea is that go-to-definition works on many constructs like exports and can jump across files and the like, but it might not work all the time, and things like quick info might not work at all. We might be able to get away with doing a lot of this from the syntax server.

Ultimately, this just needs some sort of user story spec'd out.

**Comment by RyanCavanaugh** [comment]
Closing in lieu of #39035
