### ISSUE TITLE
Compile target does not work when lerna is installed

### ISSUE THREAD

**Issue by screendriver** [microsoft/TypeScript#35122]
I created a very small and simple TypeScript project and set the compile `target` to `es5`. With that it is not possible to use functions that were introduced in `ES2015` and later. For example it is not possible to use `['a'].findIndex(e => e === '1');` because the compiler would complain that `findIndex()` does not exist. It works until I add [lerna](https://github.com/lerna/lerna/) as a dev dependency to the project. When I do that `tsc` does not complain anymore. It is enough to just add the dependency itself. No configuration required.

**TypeScript Version:**  3.7.2

**Search Terms:**

- lerna
- lerna target

**Code**	

### tsconfig.json

```json
{
  "compilerOptions": {
    "outDir": "dist",
    "target": "es5",
    "module": "esnext",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "importHelpers": true,
    "sourceMap": true,
    "declaration": true,
    "declarationMap": true,
    "composite": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*"]
}
```

### package.json

```json
{
  "devDependencies": {
    "typescript": "3.7.2"
  }
}
```

### index.ts

```ts
export function test() {
  return ['a'].findIndex(e => e === '1');
}	
```

**Expected behavior:**	

**Actual behavior:**

Run tsc and watch it fail:

```
src/index.ts:2:16 - error TS2339: Property 'findIndex' does not exist on type 'string[]'.	
```

After that just add `lerna` as a dev dependency `yarn add -D lerna` and run `tsc` again. The error magically disappears. You don't need to create a `lerna.json` or anything else. Just adding that dependency is enough.	

It seems that tsc is ignoring `target` completely after adding lerna to my repository.

**Playground Link:** 

**Related Issues:** 

Because I'm not 100% sure if this is a TypeScript bug I created the same issue in the lerna repository: https://github.com/lerna/lerna/issues/2344

I don't know what's going on internally in that dependency but no dependency should affect my project compiler settings.

**Comment by ajafff** [comment]
It doesn't ignore `target`. It extends `lib` and therefore loads declaration files for newer ECMAScript versions.

It probably pulls in a dependency `@types/<whatever>` that contains `/// <reference lib="esXXX" />`. This tells the compiler that the code will be executed in an environment that can handle a newer ECMAScript version than what you specified as `target`

**Comment by RyanCavanaugh** [comment]
The problem is here (via `npm ls`):
``
| +-- @lerna/create@3.18.0
| | +-- globby@9.2.0
| | | +-- @types/glob@7.1.1
| | | | +-- @types/events@3.0.0
| | | | +-- @types/minimatch@3.0.3
| | | | `-- @types/node@12.12.7
```
and here:
```
| | +-- @lerna/github-client@3.16.5
| | | +-- @octokit/rest@16.35.0
| | | | +-- @octokit/request@5.3.1
| | | | | +-- @octokit/types@2.0.1
| | | | | | `-- @types/node@12.12.7 deduped
```
These pull in `@types/node` into your local `node_modules`, which specifies `<reference lib="es2015" />` (or something similar). TS helpfully automatically adds things from `@types/` to your compilation absent other hints.

The quick fix is just to add `"types": []` to your `tsconfig.json` to prevent `@types` from being automatically scanned.

Ideally `globby` and `octokit` wouldn't list `@types` packages as non-dev dependencies, or be more judicious in taking a dependency on the massive `@types/node` package.

**Comment by screendriver** [comment]
Ok, thanks for clarification. But that also would mean I can't use `@types/node` for example, right? So excluding that with `"types": []` would also mean I can't use any types from definitely typed anymore 🤔

**Comment by RyanCavanaugh** [comment]
Not really; if a `.d.ts` files calls in a `lib`, there's no way to override that (except for `noResolve` which you *really* don't want to mess with).

**Comment by screendriver** [comment]
Hmm damn. Maybe something for your "wishlist" / roadmap? :sweat_smile:

**Comment by RyanCavanaugh** [comment]
Absolutely; this is the primary driver of the "placeholder types" effort - so that packages don't need to take an `@types/node` dependency unless you need it
