### ISSUE TITLE
Performance improvement in __rest() helper for Object rest operator

### ISSUE THREAD

**Issue by victor-homyakov** [microsoft/TypeScript#35130]
## Search Terms

rest operator performance

## Suggestion

Now Object rest operator is emulated through a call to `__rest()` helper, which uses `Array#indexOf()` to search for properties in an unsorted array.

1. When compiling the rest operator, tsc could sort the array of excluded property names
2. Then at the run time `_rest()` helper may use binary search in the sorted array instead of `Array#indexOf()` to improve run-time performance

## Use Cases

[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=16&pc=2#code/MYewdgzgLgBAMgSzAaxgXhgCgN4CgYExQJQA2ApgDT6EAWATuQGbWFECG9A5uVK4QBMEEdgCMKA-gUakpHUQEkwA8gA85SMOXoAlZnNBgo9EKT0saBYLQSkBjMHIAOEcgFcBIOWHAA3YW7sspYwAHThTiYuuAC+AJToAHwweLG4QA)

TypeScript code

```ts
const Link = ({
    title,
    href,
    target,
    disabled,
    rel,
    tabIndex,
    innerRef,
    controlRef,
    children,
    pseudo,
    nonvisual,
    ...props
}) => {
    // ...
}
```

now is compiled to

```js
var
    { title, href, target, disabled, rel, tabIndex, innerRef, controlRef, children, pseudo, nonvisual } = _a,
    props = __rest(_a, ["title", "href", "target", "disabled", "rel", "tabIndex", "innerRef", "controlRef", "children", "pseudo", "nonvisual"]);
```

In such cases, when both object and array have many elements, `__rest()` may consume significant time.

## Examples

The array of properties could be sorted at compile-time, and then `__rest()` could use binary search, which will be faster than linear search with `Array#indexOf()`.

```js
var
    { title, href, target, disabled, rel, tabIndex, innerRef, controlRef, children, pseudo, nonvisual } = _a,
    props = __rest(_a, ["children", "controlRef", "disabled", "href", "innerRef", "nonvisual", "pseudo", "rel", "tabIndex", "target", "title"]);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

(I'm not sure about design goals - does it fall under "Aggressively optimize the runtime performance of programs" or not)

**Comment by RyanCavanaugh** [comment]
I'm *extremely* skeptical you could write a binary search in JS that was faster than the natively-implemented `indexOf` for lists less than 20 elements long. Evidence?

**Comment by victor-homyakov** [comment]
OK, you're right. I'm unable to write anything that is faster than `indexOf` on small arrays.
