### ISSUE TITLE
TypeScript API: CompilerHost#readDirectory is called too early

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#35142]
**TypeScript Version:**  3.7.2

**Search Terms:** `readDirectory` `outDir`

**Code:** None, as this is a Compiler API issue.

**Expected behavior:**

`CompilerHost#readDirectory` is not called before I've had a chance to retrieve the path to `outDir` and exclude it from consideration.

**Actual behavior:**

`readDirectory` is called during processing of `parseJsonConfigFileContent`, before I've had a chance to examine the configuration and therefore can't exclude files in `outDir` from the directory listing.  This leads to these files being passed into `createProgram`, where TS will happily recompile its previous output if `allowJs` is enabled.

I can filter out the files in `outDir` after the fact, but my first instinct is that this is a hack and there must be a cleaner way to accomplish this that I'm not seeing.

**Playground Link:** N/A

**Related Issues:** #26785 (only tangentially related)

**Comment by sheetalkamat** [comment]
This is working as intended.. If config has specified `exclude` clause that clause is used. Otherwise `outdir`, `declaraitonDir` are filtered out.

**Comment by fatcerberus** [comment]
@sheetalkamat It's been my experience that tsc will exclude the contents of `outDir` regardless of whether `exclude` is present or not.  How is it able to do this if the API won't allow examining it before the directory listing is requested?  I wasn't able to figure that out from reading the source.

**Comment by sheetalkamat** [comment]
https://github.com/microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L2295 does that only if exclude is not specified in the tsconfig file.
