### ISSUE TITLE
Infer subtype of T based on a predicate function (t: T) => boolean that matches that condition

### ISSUE THREAD

**Issue by kasperpeulen** [microsoft/TypeScript#35146]
I would like that it is possible that based on a predicate function `(t: T) => boolean` typescript can to infer the subtype of `T` that matches that condition.

I have here a standalone example of what I want to achieve. In practice I would like to use this to improve the type safety of redux-saga, as you may notice from the example.

```typescript
type Actions =
  | {
      type: 'A';
      subType: 'A';
      payload: string;
    }
  | {
      type: 'A';
      subType: 'B';
      payload: number;
    }
  | {
      type: 'B';
      payload: number[];
    };

declare function takeEvery<T extends Actions>(
  predicate: (action: Actions) => action is T,
  worker: (action: T) => void,
): void;

takeEvery(
  action => action.type === 'A' && action.subType === 'B',
  action => {
    const payload = action.payload;
    // payload should be inferred as number here
    console.log(payload * 2);
  },
);
```

**Comment by fatcerberus** [comment]
How can this work?  The implementation of the type predicate is opaque at compile time, so the compiler can’t possibly answer the question of “Which `T` will it return true for?”.  You have to *run* the code to know that—and that’s assuming it’s even deterministic.

**Comment by jcalz** [comment]
Please fill out the [template](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) when you open a new issue.  

As mentioned in the answer to [this question](https://stackoverflow.com/questions/58896417/infer-subtype-of-t-based-on-a-condition-function-t-t-boolean-that-matches/58896581#58896581), such inference is an existing open issue, #16069.
