### ISSUE TITLE
I have turned on ‘es’, but I still can’t use `default import/export`

### ISSUE THREAD

**Issue by d1y** [microsoft/TypeScript#35152]
**TypeScript Version:**  3.3.3333

**Code**

my `tsconfig.json` file

```jsonc
{
  "compilerOptions": {
     "esModuleInterop": true
  }
}
```

less code

```ts
// code.ts
enum userCode {
  success = 1,
  faild,
  already
}
export = { userCode }

// imp.ts
import { userCode } from './code'
```

**Expected behavior:**

There should be no problem at the grammatical level, I also set it up to `esModuleInterop` 😐

**Actual behavior:**

```console
src/controller/api/User.ts:3:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referen
cing its default export.

3 import { userCode } from '../../const/code'
```

I am very puzzled how to solve this problem😪?

**Comment by fatcerberus** [comment]
```ts
import code from './code';
```

And then destructure `code` to get `userCode`.

The error message pretty much says as much.  `export =` is analogous to a CommonJS export (`module.exports`), which has no canonical name—so you can’t import it by name either.  `import {}` is not a destructuring, it only looks like one.

**Comment by d1y** [comment]
> ```ts
> import code from './code';
> ```
> 
> And then destructure `code` to get `userCode`.
> 
> The error message pretty much says as much. `export =` is analogous to a CommonJS export (`module.exports`), which has no canonical name—so you can’t import it by name either. `import {}` is not a destructuring, it only looks like one.

Strange, I used the `ts-node-dev` to debug. When I restarted, this error is gone, and in `vscode` these writes will not be reported, I feel it is `ts- Node-dev` problem 😬
