### ISSUE TITLE
Compiler API - Make disableIncrementalParsing not a global variable

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#35158]
## Search Terms

disableIncrementalParsing

## Suggestion

Right now disabling incremental parsing is done via the public api like so:

```ts
ts.disableIncrementalParsing = true;
```

https://github.com/microsoft/TypeScript/blob/196c0aa0783ddd7520f9accd54d53c3223f5a47c/lib/typescript.d.ts#L5882

This means that if someone sets this to true it will mess with anyone else that depends on it.

It would be nice if this was made non-global.

## Workaround

```ts
function doWithIncrementalParsing(action: () => void) {
    const oldValue = ts.disableIncrementalParsing;
    ts.disableIncrementalParsing = false;
    try {
        action();
    } finally {
        ts.disableIncrementalParsing = oldValue;
    }
}
```

**Comment by sandersn** [comment]
This is fixed by #35530.
