### ISSUE TITLE
createIncrementalProgram: trigger recompilation with new files

### ISSUE THREAD

**Issue by ivogabe** [microsoft/TypeScript#35159]
## Search Terms

createIncrementalProgram API changes

## Suggestion

I'm currently trying to use `createIncrementalProgram` in gulp-typescript to make use of the new incremental compilation functionalities. I have not yet found how to signal the compiler that some files have changed. The `version` field of all the files is still at the old version, whereas the `Host` does have files with the new version. So how can I signal the `BuilderProgram` that some file has changed?

## Use Cases

I'm implementing this in gulp-typescript, the gulp plugin for TypeScript. See ivogabe/gulp-typescript#635

**Comment by andrewbranch** [comment]
@sheetalkamat do you know of any examples that @ivogabe can look at?

**Comment by sheetalkamat** [comment]
`createIncrementalProgram ` is similar to `createProgram` but reads the old program from the `.tsbuildinfo`. For your scenario you wanto use `createWatchProgram` which handles changes in files.

**Comment by ivogabe** [comment]
Thanks for the info! I'll take a look, it'll probably require some more changes than I hoped. I'll let you know if I can get it working. Do you mind keeping this open in case we have further questions?

**Comment by andrewbranch** [comment]
I think the bot will close it only after some period of inactivity, but if it gets closed and you come back with more questions, feel free to comment and I’ll reopen.

**Comment by AaroncoolPx** [comment]
createIncrementalProgram still emits and update output files, even though source remain unchanged. 

`import ts = require("typescript");

var options = {
    incremental: true,
    allowJs: true,
    sourceMap: true,
    tsBuildInfoFile: "buildInfoTestOutput",
};
let program = ts.createIncrementalProgram ({
    rootNames: ["./test1.ts"],
    options: options
});
let emitResult = program.emit();`

typescript@4.5.4
