### ISSUE TITLE
Bug: RegExpMatchArray is missing properties `index` and `input`

### ISSUE THREAD

**Issue by balupton** [microsoft/TypeScript#35157]
**TypeScript Version:**  3.7.2

**Search Terms:** RegExpMatchArray, input, index, length, regexp, regex, result objects

**Code**

```ts
const match = 'a'.match(/a/)
if ( match ) console.log(match.input.includes('a'), match.index.toFixed(2))
```

**Expected behavior:** It to work.

**Actual behavior:** Type checks fails because `RegExpMatchArray` does not define `index` and `input`

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=2&ssc=75&pln=2&pc=100#code/MYewdgzgLgBAtgQysAFjAvDA5ArA6RZFACgHoFSBKAKAEsAzGY+JVGSmUSEAGwFM8PEAHNihVHlpgADgFcoksMB6yAJnwjEcWSgBoWRReoAeeKCABitY31XEATJUpA)

**Related Issues:** none

For reference of the `index` and `input` properties, see:

> RegExp result objects have some non-numerical properties already, which named capture groups may overlap with, namely length, index and input. 

https://github.com/tc39/proposal-regexp-named-groups

**Comment by gvelchuru** [comment]
When I run this in the playground, I get "true 0.00" in the console, which is expected behavior.

**Comment by balupton** [comment]
Correct, the code will run, but the typescript type checking warns `Object is possibly 'undefined'.(2532)`

**Comment by nmain** [comment]
The error is correct.  Typescript does define `RegExpMatchArray.input` and `RegExpMatchArray.index`, but warns that they might be undefined, because they might be undefined:

```ts
const m = 'a'.match(/a/g)
if (m) {
    console.log(m.input === undefined) // prints true
    console.log(m.index === undefined) // prints true
}
```

**Comment by balupton** [comment]
Interesting. Is there any further documentation on their behaviour anywhere?

**Comment by nmain** [comment]
[spec](https://tc39.es/ecma262/#sec-regexp.prototype-@@match)

In short, if the regexp has the global flag set, then `String.prototype.match` won't have `input` or `index`.

**Comment by balupton** [comment]
Could we update the type definition then to have `input` and `index` set if the `global` flag is unset? The introspection could be done using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global

**Comment by RyanCavanaugh** [comment]
Regex flags aren't propagated into the resulting type. I believe this is the only one that has any effect, so it'd be a tough sell to add a new feature to make these properties get detected
