### ISSUE TITLE
Type instantiation is excessively deep with PartialRecursive & recursive list type

### ISSUE THREAD

**Issue by idoros** [microsoft/TypeScript#35156]
**TypeScript Version:**  3.7.2 (and nightly/next)

**Search Terms:**
- `Type instantiation is excessively deep and possibly infinite`

**Code**

```ts
type Json =
    | string
    | number
    | boolean
    | null
    | { [property: string]: Json } // recursive  object doesn't cause any issues
    | Json[] // removing the list option resolves the issue

type PartialRecursive<T> = T extends object
    ? { [K in keyof T]?: PartialRecursive<T[K]> }
    : T

interface Data {
    value: Json
}

function acceptData(param: PartialRecursive<Data>) {}

const data = {} as Data
acceptData(data) // error TS2589: Type instantiation is excessively deep and possibly infinite.
```

**Expected behavior:**
Value field should be valid as both the type itself is already inferred as the `Data` type and the entire type is optional 

**Actual behavior:**
The recursive list type causes an infinite (or excessive) calculation that fails.

**Playground Link:** 
- [3.7.2](http://www.typescriptlang.org/play/#code/C4TwDgpgBAUgzgewHZQLwCgpagHynYAJwEskBzTbPJAVwFsAjCQyrPBhBAGwgEMlWuKLS5dBeAN5QA2mEIJIhUAC58RUmQC6q+MigBfcbERJpm9OlCQoABV5LivLgCUIAYxqE4xAG4QAPAAqAHxoUIFQEAAewBBIACZwUAgMAFbuwIIA-FBS0gDSUKRQANYQIAgAZuGaWap2Dk6uHl6+AYEFmqGG2FCqgegA9ABUo2PjE5NT0xODFqSxhJW8btAAIrzAvLmCPk40EDom6IbolTRIbsDEeiurYMAbWwAUYPa8dPX2103unt5+fxPXjBACUuVObmQBCg8U221QEKgvCSwPQdwgD2BzzhW3Bg0GkUI8kI4QAygAmACsAA4AJz9cDQUgEfg-a56YhJaKrOAAiBcECwiCY5EJKBgBB84gMQVFJCVUjEWIAOiAA)
- [nightly](http://www.typescriptlang.org/play/?ts=Nightly#code/C4TwDgpgBAUgzgewHZQLwCgpagHynYAJwEskBzTbPJAVwFsAjCQyrPBhBAGwgEMlWuKLS5dBeAN5QA2mEIJIhUAC58RUmQC6q+MigBfcbERJpm9OlCQoABV5LivLgCUIAYxqE4xAG4QAPAAqAHxoUIFQEAAewBBIACZwUAgMAFbuwIIA-FBS0gDSUKRQANYQIAgAZuGaWap2Dk6uHl6+AYEFmqGG2FCqgegA9ABUo2PjE5NT0xODFqSxhJW8btAAIrzAvLmCPk40EDom6IbolTRIbsDEeiurYMAbWwAUYPa8dPX2103unt5+fxPXjBACUuVObmQBCg8U221QEKgvCSwPQdwgD2BzzhW3Bg0GkUI8kI4QAygAmACsAA4AJz9cDQUgEfg-a56YhJaKrOAAiBcECwiCY5EJKBgBB84gMQVFJCVUjEWIAOiAA)
- [recursive list vs object](http://www.typescriptlang.org/play/?ssl=14&ssc=52&pln=2&pc=1#code/C4TwDgpgBACghgJ2ASzgGwEoQMYFcEDOyAbhADwAqAfFALxQVQQAewEAdgCYFQD2ARgCscwAFBQJUAPxQA3lADaAaSjJ2UANYQQvAGYMAulIBcsRCnRY8hEuQrKDNAL7jJpiqNGhIUAPJC6VwkAHzlFMAReSCQQUwJgBDUAcwNTf0EoFy9waHgkVDR0ujN8yxx8IlIydKpPb2h03wQAGWR4wMkoUPkFCKiIGLiE5NS-ISbW9pdO0MaWtuAFAygAehWoXThkNCh+HDhcAmg9KDQF3dxgKHZeK4FhbDFsnzyLQvH59vpXgqsK22qH0mwCoQA)

**Related Issues:** 
- https://github.com/microsoft/TypeScript/issues/34933
- https://github.com/microsoft/TypeScript/issues/33132

**Comment by jcalz** [comment]
Related: #33050, which introduced the ability to write `type Json = ... | Json[]` instead of requiring an  intervening interface like `type Json = ... | JsonArray; interface JsonArray extends Array<Json> {}`.

**Comment by idoros** [comment]
Looking at this some more I noticed that the problem is in my own (probably copied from somewhere) `PartialRecursive` type that doesn't handle `Array` types.

This fixes my case: 
```ts
type PartialRecursive<T> = T extends object
    ? T extends Array<infer U> ? PartialRecursive<U>[]
    : { [K in keyof T]?: PartialRecursive<T[K]> }
    : T
```

**Comment by jcalz** [comment]
I wouldn't be so quick to dismiss this; since TypeScript 3.1, [mapped array/tuple types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#mapped-types-on-tuples-and-arrays) have been supported so you shouldn't have to special-case arrays like that.  Indeed, the pre-TS-3.7 way of typing `Json` does not have this problem with your original `PartialRecursive`:

```ts
type Json =
    | string
    | number
    | boolean
    | null
    | { [property: string]: Json }
    | JsonArray

interface JsonArray extends Array<Json> {}

type PartialRecursive<T> = T extends object
    ? { [K in keyof T]?: PartialRecursive<T[K]> }
    : T

interface Data {
    value: Json
}

function acceptData(param: PartialRecursive<Data>) {}

const data = {} as Data
acceptData(data) // no error
```
[Playground link](http://www.typescriptlang.org/play/#code/C4TwDgpgBAUgzgewHZQLwCgpagHynYAJwEskBzTbPJAVwFsAjCQyrPBhBAGwgEMlWuKLS5dBeAN5QA2mEIJIhUAC58RUmQC6q+MigBfcbERIAgoUK8Q6dKWDMAZrwDG0XWYtWoEAB72kACZwUOaWIAA87gB8UBKG6KCQUAAKvErEvFwAShDONIRwxABuEOEAKjGoUGXefhCBwQgMAFa5wIIA-LEyANJQpFAA1hAgCA7Vmh2qqemZOXkFxaVl0j2aMYbYUKpl6AD0AFRHxyenZ+cXp3s2do4u0AAivMC8sYJFmTQQOibo8Q40JDOYDEPQuVxgYBPF4ACjAaV4dGmaRBc1y+UKJXC0N4UQAlLF4s5kAQoAFnq8qnEoLxgjj0OCIJCcTDyS8CXs9sIEN4LAgWEA)

So whatever's going on here isn't what I'd call a problem with recursive mapped types.  I don't know if this is a compiler bug / design limitation / working as intended, but I'm still interested in seeing what an official word here would be.

**Comment by idoros** [comment]
Re-opening, feel free to close if this works as expected

**Comment by ahejlsberg** [comment]
This is effectively a design limitation.

When a homomorphic mapped type is applied to an array type, we obtain the element type of the array and apply the mapped type's template type to that. This is done eagerly, which effectively causes a circularity when the type being mapped is itself circular.

As mentioned above, the original example works when an array case is added to the conditional type:

```ts
type PartialRecursive<T> = 
    T extends (infer U)[] ? PartialRecursive<U>[] :
    T extends object ? { [K in keyof T]?: PartialRecursive<T[K]> } :
    T;
```

Here, `PartialRecursive<U>[]` is represented internally as a deferred type reference, and this saves us from the eager circularity problem. We could consider doing something similar for the case of applying a mapped type to an array type, but I don't think it is super important given that we have a very reasonable workaround.
