### ISSUE TITLE
TS doesn't allow optional param destructing in spite of having a default value assigned

### ISSUE THREAD

**Issue by jalooc** [microsoft/TypeScript#35160]
**TypeScript Version:**  3.7.2

**Search Terms:**
default optional parameters destructing

**Code**

```ts
type F = {
  (foo?: { bar?: {}}): void
}

const f: F = ({ bar } = {}) => {

}

const g: F = (foo = {}) => {
  const { bar } = foo
}
```

**Expected behavior:**
Both functions: `f` and `g` should be compiled without errors. `foo` is optional, but it's also provided a default value; same with `bar`. Therefore both `foo` and `bar` are in fact never `undefined`. Btw this also works in vanilla js, tested with all sorts of parameter types.

**Actual behavior:**
TS error is thrown for the `f` function's destructuring of the optional param:
```
Property 'bar' does not exist on type '{ bar?: {} | undefined; } | undefined'.(2339)
```
This error does sound right, but shouldn't occur taking into consideration those three facts:
1. If `foo` is `undefined` (= not passed as an argument to the function), the _default_ value kicks in, so `foo` becomes `{}`. It's safe to access `bar` then.
2. Function `g` does exactly the same logic as `f`, yet it doesn't fail compilation.
3. It's safe to access `bar` in vanilla js.

**Playground Link:**
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=11&pc=2#code/C4TwDgpgBAYlC8UDeAoKUAUAzA9jg-AFzJQBGAhgE5HIC+tAlMQG44CWAJirSigMY4AdgGdgULMTiIMSMlSi0EdBggB8yXj35DRUAOaSl2PEqSM1G9AJFjZFSgqW4c3IA

**Comment by RyanCavanaugh** [comment]
TypeScript is doing what you told it to do: you wrote `bar` without any annotation, so it was assumed to be a required destructuring.

You can write this instead if you meant it to be optional:
```ts
const f: F = ({ bar }: { bar?: {} | undefined } = {}) => {

}
```

**Comment by jalooc** [comment]
@RyanCavanaugh `bar` is typed withing the `F` type. Isn't that enough?

Besides `?` implies it can be `undefined`. Isn't adding `undefined` type to the union for an optional param a no-op?

**Comment by RyanCavanaugh** [comment]
Contextual typing can change the type of a parameter, but can't change its optionality. `| undefined` is implied by optionality, but not vice versa.

**Comment by jalooc** [comment]
@RyanCavanaugh Exactly, so adding `| undefined` to `bar` in my example doesn't change anything since `bar` is optional. I don't see how this is relevant to my issue anyway. What do you mean by:
> you wrote `bar` without any annotation

? It's type is derived from `F`.

**Comment by jalooc** [comment]
@typescript-bot It's still not clear to me whether this really is a _question_ or a bug, as my last comment hasn't been asnnwered.
