### ISSUE TITLE
JSX element type 'Link' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by JaybeeClassical** [microsoft/TypeScript#35166]
`const pageNotFound = () => (
    <div>
        <h1>Sorry!</h1>
        <p>This page does not exis</p>
        <img src={NotFound} style={{ width: 400, height: 400, 
display: "block", 
margin: "auto", position: "relative" }} />
        <Link to="/">Go back</Link>
    </div>
);
`

## Expected
Expecting the <Link> to work normally but it's not

**Comment by MartinJohns** [comment]
Please respect the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md).

**Comment by JaybeeClassical** [comment]
> Please respect the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md).

This was not an intentional action

**Comment by JaybeeClassical** [comment]
If you can help please do
