### ISSUE TITLE
3.7 Optional Chaining Strange

### ISSUE THREAD

**Issue by dolphinlin** [microsoft/TypeScript#35178]
**TypeScript Version:**  3.7.x-dev.201xxxxx
3.7.2

**Search Terms:**

**Code**

```ts
type Test = {
  name?: string;
  arr?: string[];
};

const Person: Test = {
  name: 'TestMan',
};

if (Person.arr?.length !== 0) {
  console.log(Person.arr.map(a => a));
}
```

**Expected behavior:**
```ts
if (Person.arr?.length !== 0) {
  console.log(Person.arr.map(a => a)); // Person.arr must be an Array
}
```
**Actual behavior:**
```ts
if (Person.arr?.length !== 0) {
  console.log(Person.arr.map(a => a)); // Object is possibly 'undefined'.ts(2532)
}
```
**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=4&pc=3#code/C4TwDgpgBAKhDOwoF4oG8BQUoDsCGAthAPwBcUiATgJY4DmA3FlHpZWRcDfQNoC6TAL5MMAYwD2ORFAAKESvEnk401Jmz4i5AOQrgAWTw5tAGgzCMGagDMoACjkLJAOlbtnAGwj1gACygAhMioAAwAlOjMElLiXp7idA7yijiubM4EeGB2eCgAfCxhYUIYQA
**Related Issues:**

**Comment by fatcerberus** [comment]
`Person.arr?.length` might be `undefined` because `arr` is itself undefined or missing (you’ve declared it optional).  `undefined !== 0` is `true`.  The error message is correct.
