### ISSUE TITLE
Change implicit exclude globs to be recursive

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35175]
Follow up from design meeting discussion on https://github.com/microsoft/TypeScript/issues/35121

At the very least, we want to change the implicit `node_modules` glob to be recursive.

```diff
-./node_modules/**/*
+./**/node_modules/**/*

**Comment by fatcerberus** [comment]
> `./**/node_modules/**/*`

Won't this end up skipping `./node_modules`, since the glob calls for at least two slashes between the `.` and `node_modules`?

**Comment by amcasey** [comment]
Some more details would have been helpful here.  It looks like this is actually about updating the _include_ pattern to exclude more things: https://github.com/microsoft/TypeScript/blob/27616dd523279a5d699d2154edb4de6abc8234ad/src/compiler/utilities.ts#L5298
I'll have to do some regex testing, but it looks like the generated pattern should already cover nested `node_modules` folders.

**Comment by amcasey** [comment]
As far as I can tell, the regex already excludes paths containing `node_modules` or a directory starting with `.` at any level.

**Comment by amcasey** [comment]
Please re-open if you find a case that's not covered.
