### ISSUE TITLE
Format deletes spaces before preincrement

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#35179]
Copied from https://github.com/microsoft/vscode/issues/85068

**TypeScript Version:** ^3.8.0-dev.20191116

**Search Terms:**
- format
- increment
- preincrement

**repo**

1. With following TS:

```ts
let a = 0;
if (a>0) ++a;
```

2. format

**Expected**
```ts
let a = 0;
if (a > 0) ++a;
```

**Actual**
Missing space:

```ts
let a = 0;
if (a > 0)++a;
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
