### ISSUE TITLE
Duplicated documentation from common properties in union types

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/TypeScript#35170]
*TS template added by @mjbvz*

**TypeScript Version**: 3.8.0-dev.20191116

**Search Terms**:
- suggest / suggestions
- jsdoc

---

![duplicate-description](https://user-images.githubusercontent.com/23744935/69036467-3c7a5680-09e6-11ea-9db4-7a991ef1aa17.png)

- VSCode Version: 1.41.0-insider
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Create a typescript union type with descriptions for each type, e.g. 
```typescript
export type DocumentFilter = {
    /** A language id, like `typescript`. */
    language: string;
    /** A Uri [scheme](#Uri.scheme), like `file` or `untitled`. */
    scheme?: string;
    /** A glob pattern, like `*.{ts,js}`. */
    pattern?: string;
} | {
    /** A language id, like `typescript`. */
    language?: string;
    /** A Uri [scheme](#Uri.scheme), like `file` or `untitled`. */
    scheme: string;
    /** A glob pattern, like `*.{ts,js}`. */
    pattern?: string;
} | {
    /** A language id, like `typescript`. */
    language?: string;
    /** A Uri [scheme](#Uri.scheme), like `file` or `untitled`. */
    scheme?: string;
    /** A glob pattern, like `*.{ts,js}`. */
    pattern: string;
};
```

2. When using intellisense, it shows duplicate descriptions

Does this issue occur when all extensions are disabled?: Yes

**Comment by nmain** [comment]
This reproduces in the [playground](https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcAiEDGBXAtsAOxgDEBLAGxmCjgF44BvAWACg524B6AKm7gEE45AIYEA5tmFjUpACYAaIaQDWqAAZIUAZ0xRSYGGoB0cbp1YchoiVOAAuOFph7xAbgscefQQFU9cAG0dAAtgfABdAAoAYj9SIxCw4ABKRXIVdQAzCmA1OGg4NWwiUhhyYFljU3M2DkT8AH4HJxcxd1r2LwE4MXIIACM4MGEYKigCNIzC7iMGGC15ACstAF8qsw92YdHqAibHZ1I3VhW4AB9GTa5ebpFxSWk4OUnVQs1gHT0DdZrLO5tpPsWkc2lcur5-EFMKEIjE4gloUlUkpXmpsuU8gUiiUyhUfld6vYDq12pZwT0+oNtmMJij1DM5gtlmsTBsOkMRjSgYdjixThdmOzyf8HjIFHS3sgPrp9IZWb8OCLbNySWCbhDSIFCVFYnoETCUi8sjlMTRsTBSuVKvKCYjGs0eaCheqKQMOTtxkbprN5ktVvj2dTdg7VXz2qxZMBMCIoKgAG7CGiyBwYHD4IhkSjUdqcTgIKVwABEsiMhbgolkCFCBB6EDgmQKRyo5HSWkIbdYQA) as well

**Comment by AnyhowStep** [comment]
Related?

https://github.com/microsoft/TypeScript/issues/32708

**Comment by minestarks** [comment]
In theory the doc comment above for each declaration of `language` could be different. What would we want to show in that case?

In this case since they're _exactly_ the same we could probably collapse them into one.
