### ISSUE TITLE
[Compiler API] resolveNameHelper:  Cannot read 'members'

### ISSUE THREAD

**Issue by schmidt-sebastian** [microsoft/TypeScript#35182]
I am seeing a crash in `getSymbolAtLocation()` that is reproducible via a very small repo. It does not reproduce on https://ts-ast-viewer.com/. The repro is so small that I suspect that I am doing something wrong.

**TypeScript Version:**  3.8.0-dev.20191116

**Search Terms:**
"resolveNameHelper"
"members of undefined"

**Code**

```ts
import * as ts from 'typescript';

const source = `
class ClassA {
  prop: ClassB;
}
`;

console.log('Version: ' + ts.version);

const options: ts.CompilerOptions = { strict: true, target: ts.ScriptTarget.ES2019};
const fileName = '/dev/null';
const program = ts.createProgram([fileName], options);
const typeChecker = program.getTypeChecker();

const sourceFile = ts.createSourceFile(
    fileName,
    source,
    ts.ScriptTarget.ES2019,
   true
);

function visit(node: ts.Node) {
  console.log('\nVisiting:\n' + node.getText());
  typeChecker.getSymbolAtLocation(node);
  ts.forEachChild(node, (n) => {
    visit(n);
  });
}

visit(sourceFile);
```
**Actual behavior:**

getSymbolAtLocation() crashes when it visits `ClassB` in ` prop: ClassB`.

```
TypeError: Cannot read property 'members' of undefined
    at resolveNameHelper (node_modules/typescript/lib/typescript.js:34438:70)
    at resolveName (node_modules/typescript/lib/typescript.js:34297:20)
    at resolveEntityName (node_modules/typescript/lib/typescript.js:35271:26)
    at getSymbolOfEntityNameOrPropertyAccessExpression (node_modules/typescript/lib/typescript.js:63616:24)
    at getSymbolAtLocation (node_modules/typescript/lib/typescript.js:63662:28)
    at Object.getSymbolAtLocation (node_modules/typescript/lib/typescript.js:33338:31)
    at visit (tests/scratchpad.ts:38:19)
```

**Comment by ajafff** [comment]
The type checker only works with SourceFiles (and its Nodes) that come from `program.getSourceFile()`.
That means `sourceFile` in your example is not part of `program` and therefore `typeChecker` (which only works for this specific Program) doesn't know how to handle the Nodes from that SourceFile.

To fix your example code, you need to pass a custom `CompilerHost` as argument to `ts.createProgram`. That CompilerHost's `getSourceFile` method needs to return your `sourceFile` if the path matches.

**Comment by schmidt-sebastian** [comment]
@ajafff You are correct. It works if I update the code to use a CompilerHost. It would be nice to get a slightly better error, but I will close this for now. Thanks for helping me get unstuck!
