### ISSUE TITLE
[Compiler API] Detecting "emittable" nodes/symbols

### ISSUE THREAD

**Issue by kitsonk** [microsoft/TypeScript#35183]
**Search Terms:**

symbol ast compiler api emit node

**Question**

As per guidance, compiler API usage is the one exception to asking questions in the issue tracker.  Because of that, I've got a question.

I've got a use case where I am trying to detect if an export of a source file represent a runtime emit, or something that would be erased on emit.  I can't seem to find a clean way to do this.  Currently I am doing something like this:

```ts
declare const sourceFile: ts.SourceFile;
declare const program: ts.Program;

const checker = program.getTypeChecker();

const sourceSymbol = checker.getSymbolAtLocation(sourceFile);
assert(sourceSymbol);
const sourceExports = checker
  .getExportsOfModule(sourceSymbol)
  .filter(
    sym =>
      !(
        sym.flags & ts.SymbolFlags.Interface ||
        sym.flags & ts.SymbolFlags.TypeLiteral ||
        sym.flags & ts.SymbolFlags.Signature ||
        sym.flags & ts.SymbolFlags.TypeParameter ||
        sym.flags & ts.SymbolFlags.TypeAlias ||
        sym.flags & ts.SymbolFlags.Type ||
        sym.flags & ts.SymbolFlags.Namespace ||
        sym.flags & ts.SymbolFlags.InterfaceExcludes ||
        sym.flags & ts.SymbolFlags.TypeParameterExcludes ||
        sym.flags & ts.SymbolFlags.TypeAliasExcludes
      )
  )
  .map(sym => sym.getName());
```

I just don't know if there is a cleaner way to determine if a symbol will result in non-erased emit.

**Comment by ajafff** [comment]
You probably also need to consider value symbols that are only used in type position (unless used in a decorated class with `--emitDecoratorMetadata`).
Always excluding namespaces seems wrong to me as they can also be used as value.

**Comment by RyanCavanaugh** [comment]
I think what you have there is the correct approach, though there is probably a simplification of that bitwise/boolean logic to be had. Testing for `SymbolFlags.Value` alone may be sufficient, but I'd have to try to check.

@rbuckton what's the exact check we use in the emitter?
