### ISSUE TITLE
`asserts` and `declare` in classes are not included in suggestions

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#35187]
**TypeScript Version:**  3.7.2 in VSCode / Nightly in the playground

**Search Terms:** asserts color

**Code**
![grafik](https://user-images.githubusercontent.com/17641229/69138520-24c2d100-0abf-11ea-9a15-254d12527413.png)
![grafik](https://user-images.githubusercontent.com/17641229/69162265-a8df7d80-0aec-11ea-9cec-e8e9e3aa7fd7.png)

**Expected behavior:**
`asserts` is colored like the other keywords and included in auto completion after typing `:`.
`declare` is colored like the other keywords and included in auto completion when typing `d...` at the start of a line in a class context.

**Actual behavior:**
They are not. (Except declare, which is colored in the playground, but not VSCode).

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191116#code/GYVwdgxgLglg9mABMOcAUAPAXIghmATwEodcBnMgUwCcozENEZ6AiXFxAbwChE-EA9AMQBaMeImSAeojBw8IKHAhwAtgAcANpSiVkcaojYUadFtwC+3bhE3l6AMVRde-ACaVbuanoBGuAC9SQgBuVz4hUTFZeVxFZTUtHT0UQxYPLx9zfkFhXwJEKAALPQB3XAIAGkRSkp8memLcKEQVVVVKMBaEQpLEahgAcyKWshgPAH5LIA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
This is technically two issues. Can you file colorization as a bug in the TypeScript-TmLanguage repo?

**Comment by AlCalzone** [comment]
Done!
