### ISSUE TITLE
error TS5056: Cannot write file '/home/node/api/dist/src/datasources/admin.datasource.d.ts' because it would be overwritten by multiple input files

### ISSUE THREAD

**Issue by HamzaMansouri7** [microsoft/TypeScript#35189]
hi DEVS   i get this  problem after i try to run my server  API  , im using #angular 7 and #loopback 
it seems like the is 2 fils pointing in the same datasources of base (client) and the same thing 
 happen to the (Admin database)
i found the 5054 erreur  but is not the same my error is TS5056 ... 
i thing is Typescript version ..im not sure  any help plz   
 

------this  is my Api Tscofig 

**`{
  "extends": "./node_modules/@loopback/build/config/tsconfig.common.json",
  "include": [
    "src",
    "test"
  ],
  "exclude": [
    "node_modules/**",
    "packages/*/node_modules/**",
    "examples/*/node_modules/**",
    "**/*.d.ts"
  ]
}`

**

------- the error is in the DIST->src ->datasources  .... file auto generated by  ** npm start **

![github](https://user-images.githubusercontent.com/51540362/69143396-28f3ec00-0ac9-11ea-9c2f-b5e70f5c4179.PNG)

**Comment by HamzaMansouri7** [comment]
![tsconfig](https://user-images.githubusercontent.com/51540362/69143548-87b96580-0ac9-11ea-9584-61b167a7a0a0.PNG)

**Comment by AlCalzone** [comment]
I've noticed that some of my projects now include *.d.ts outputs for json files. Since you have .ts and .json files with the same name, I guess that's the reason you're seeing the error.

**Comment by RyanCavanaugh** [comment]
See #34962 - JSON from .d.ts will be disabled in 3.7.3

**Comment by diegoazh** [comment]
Like @AlCalzone said the reason if files `.ts` and `.json` with the same name; I added at the and of the name `.config.json` in order to avoid this error.
Thank you very much @AlCalzone
