### ISSUE TITLE
ts(1064) The return type of an async function or method must be the global Promise<T> type.

### ISSUE THREAD

**Issue by ackvf** [microsoft/TypeScript#35191]
**TypeScript Version:**  3.7.2
**TypeScript Nightly** [Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191116&ssl=1&ssc=1&pln=19&pc=5#code/LAKALgngDgpgBAQQHYQQZwkgxgMQK7ZgCWA9knALxwAUAdPQIYBOA5mgFxwMoDaAugEpKAPjgAFJiQC2RNDAA83CMNCRYcAEoAGAIyVNMMHiZIAKtAXJUGbPkKkkouAHpn4yTLmKUKkFjJoYFw2uEgAogAeMFh4YCRM+vI4cDARYDBIACZoiCjomLgEWMRkwtQAZkicOEIUogwhNPS0zGycSvwCnBqGxmYWSaJ1cJXUrWhCrnAAcgDyANKgU3Arq2vrG5tb2zu7exsAfkfHJ8eg-kiBwQU44VExcUwATInJqelZOVb5tkUljhUqnAaiJrtgmoxWBwuLxBN1dKDRuNJm4FucAkEGjc7tFYvEAMyvFJpDLZXLWG5-BxlSrVWr1Rp0SFtGEQTqcCTSWQKJRDURIqECADcLlRiz8GLBoUiuMeABYie9SV88iE7MVqYC6aCseCmS0oe1YV13FyvD0jCZzLBBnyRkgxoLRXAFgAaOAAI1icDwLAANhBQEGQEKxoz6XAAN6gNYXK5MGBoPB+oJUBgAdwYRExapxD3iYYKNAjcqeAmoKJd4rWUwTSZTnCQeCkHpgTGDsclsCyRCQLB69bACrTuZl+aYcsLepLZYrzrdnu9voDMdWU27mV7-cTyaHHI83PknM8CibLbbwl8ncuQTru+HXEz2bgG63A-v8+ra7cd5Tcsbzatu2IAAL7lgIQA)

**Search Terms:**
async function return type global promise
**Code**

```ts
type AnyAsyncFunction = (...args: any[]) => Promise<any>
type R01 = ReturnType<AnyAsyncFunction>  // Promise<any>
const asyncFnExecutor = <F extends AnyAsyncFunction>(fn: F) => async (...args: any[]): ReturnType<F> => fn(args) // NOK
//                                                                                     ~~~~~~~~~~~~~
const asyncFnExecutor2 = <F extends AnyAsyncFunction>(fn: F) => async (...args: any[]): R01 => fn(args) // OK
const asyncFnExecutor3 = <F extends AnyAsyncFunction>(fn: F) => async (...args: any[]): Promise<any> => fn(args); // OK
const asyncFnExecutor4 = <F extends AnyAsyncFunction>(fn: F) => async (...args: any[]): Promise<ReturnType<F>> => fn(args) // OK, but ugly


;(async () => {
    const result = await asyncFnExecutor(async () => 42)() // OK - correct type inference despite error in type definition
    // result: number

    const pendingResult4 = asyncFnExecutor4(async () => 42)() // OK, but ugly
    // pendingResult4: Promise<Promise<number>>
    const result4 = await pendingResult4 // OK
    // result4: number
})()
```

**Expected behavior:**

Does not report any error since
`ReturnType<F> === Promise<any>`

Using `Promise<ReturnType<F>>` in return type gets rid of the error

**Actual behavior:**

The return type of an async function or method must be the global Promise<T> type.ts(1064)

PS: There isn't any custom ambient Promise type definition if that's relevant.

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/12973
https://github.com/microsoft/TypeScript/issues/12737
https://github.com/microsoft/TypeScript/issues/12292

**Comment by AnyhowStep** [comment]
This is working as intended.

It is possible for a type to extend `Promise<any>` but not be equal to `Promise<any>`.

Async functions can only return `Promise`

```ts
interface MyAwesomeP extends Promise<void> {
  boom () : void
}
//Pretend this is okay
async function foo () : MyAwesomeP {
  const p = Promise.resolve() as MyAwesomeP;
  p.boom = () => console.log("hi");
  return p;
}
foo().boom(); //boom
```

I'm on mobile but the above should give you an error saying that it cannot invoke a value of type undefined if you run it

**Comment by nmain** [comment]
If you want to enforce that your function actually returns a `Promise` and not `MyAwesomeP`, you probably want something somewhat like this:

```ts
const asyncFnExecutor5 = <A extends any[], R>(fn: (...args: A) => Promise<R>) => async (...args: A): Promise<R> => fn(...args)
```

**Comment by ackvf** [comment]
I don't think I understand what you propose or how it relates to my problem.
I am not using any custom Promise definitions.

I am using a type that returns just a plain old `Promise<any>`, I am then trying to infer what is the actual Promise being passed as argument and then I just want to set the return type to that of the Promise.

```
const asyncFnExecutor = <F extends AnyAsyncFunction>(fn: F) => async (...args: any[]): ReturnType<F> => fn(args) // NOK
//                                                                                     ~~~~~~~~~~~~~

const asyncFnExecutor4 = <F extends AnyAsyncFunction>(fn: F) => async (...args: any[]): Promise<ReturnType<F>> => fn(args) // OK, but ugly
```

Even though `ReturnType<F>` gives `Promise<T>`, I can't use it in the signature.
Using `Promise<ReturnType<F>>` works, even though it gives `Promise<Promise<T>>`.

**Comment by AnyhowStep** [comment]
> I am not using any custom Promise definitions.

**You** know you aren't. TS does not. It sees the possibility of it happening. And it is preventing it.

**Comment by RyanCavanaugh** [comment]
This is a correct error. `F` could be instantiated with something like `() => MySpecialPromise`, so `ReturnType<F>` would be `MySpecialPromise`, and an async function *won't* return a `MySpecialPromise` - only a regular `Promise`
