### ISSUE TITLE
Variable still reported as possibly null after nullish coalescing operator

### ISSUE THREAD

**Issue by marnusw** [microsoft/TypeScript#35193]
**TypeScript Version:**  3.8.0-dev.20191119

**Search Terms:**

nullish

**Code**

```ts
const takesAString = (s: string) => s
let maybeString: string | null
const result = maybeString ?? takesAString(maybeString)
```

**Expected behavior:**

Since `takesAString` will never be executed when `maybeString === null` due to the nullish coalescing operator this code should be valid.

**Actual behavior:**

Passing `maybeString` to the function results in the error:
```
error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
```

This only happens when `strictNullChecks: true`, but it should be fine either way.

**Playground Link:** 

[Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191116#code/MYewdgzgLgBFCGBrAphAggZSgJwJZgHMYBeGACggC4Zo9CBKEgPhoCgAbZWAW3gE8ARsix0C1WviIAfGGACu7dq1CRY2VAtileg4TkkwA-IbhJUmfYTI6hIyfVZA)

**Related Issues:**

None

**Comment by fatcerberus** [comment]
The RHS of `??` is evaluated when the LHS *is* nullish, not when it *isn't*.  Nullish coalescing means "Use the value on left if it's not nullish, otherwise substitute this other thing on the right."

This slightly modified version of your example prints `null` if you actually run it:
```ts
const takesAString = (s: string) => console.log(s);
let maybeString: string | null = null;

const result = maybeString ?? takesAString(maybeString)
```

[Playground](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191116&ssl=1&ssc=1&pln=5&pc=1#code/MYewdgzgLgBFCGBrAphAggZSgJwJZgHMYBeGACggC4Zo9CBKEgPhlEhABtkA6DkAivQDcAKC6wAtvACeAI2RY6BarXxEAPjDABXDhxJbdHUSLbQY2VLtikpchTjUwA-M7hJUmR4TJ35itXoRIA)

**Comment by marnusw** [comment]
@fatcerberus the code runs fine, but Typescript reports a type error where it shouldn't. That is the problem. Even in your Playground example the `maybeString` in `takesAString(maybeString)` is underlined in red.

**Comment by fatcerberus** [comment]
Did you actually run my example?  Open the console and press Ctrl+Enter - it prints null, which means `null` was passed to `takesAString()`.  It seems like you're misunderstanding what the `??` operator actually does.

**Comment by marnusw** [comment]
@fatcerberus I deleted my comment. I somehow confused this with `?.`. This is not an issue.

**Comment by RyanCavanaugh** [comment]
We do test this stuff a *little* before releasing it 😉

**Comment by marnusw** [comment]
But so many edge cases, maybe you missed one... :-p
Thanks for your hard work on TypeScript and these additions in 3.7!
