### ISSUE TITLE
Assigning a default value to a deconstructed property is not validated agains the property's type 

### ISSUE THREAD

**Issue by lukaskl** [microsoft/TypeScript#35190]
**TypeScript Version:** 

- [3.7.2](http://www.typescriptlang.org/play/?removeComments=true&target=1&ts=3.7.2#code/C4TwDgpgBAwg9gVwHbAgJwCrggZygXigHIBLJAYzQgEMcIioAfYgEwkprqIFgAoPsqjQAzauWjxkQgApo4kNMBK4oAbz5RNUHMGqKA-AC4oSBAFsARug1bQkI7EQp0WSDj4BfPnwD0PqICg5FAAtFDAABZyAO546HJo7rzCyORKcEjauoqSzmgAFOq8Wpl6wATEUeHUqABu6EQANFB+cXBoxq7QRABEldUQdWjdDCR4SHBltDgkAOZI1BYANtDAcGHYxKaW9VAAdHkATADMBwcAlDaadtCEpBRUtBAsDM0+re1QncTdZByPLMMoKMTBMoFNZvMlis1tdiDkhJ0cERdlBDidzp5jPD0LJ5OglLg+Gc1N5eF5+Lw-FBALwbgBZdkJQFhwXBIIhlCLRMFIEBQd6JZIUNIZHSlbFoA55MByMA4LFOGTS-HKHDEwrFcjpHQkorFLQixTlIh9Wr1JpUsjCdBPdaQBn64DGLZWNBMKC9KomoaXXWw26-B50Z6ac1IS1UFg26ChSPGH73TgQbqu7psP50JPMONpp7db0ecpS+SJcl8IA) - latest version tried
- [3.0.1](http://www.typescriptlang.org/play/?removeComments=true&target=1&ts=3.0.1#code/C4TwDgpgBAwg9gVwHbAgJwCrggZygXigHIBLJAYzQgEMcIioAfYgEwkprqIFgAoPsqjQAzauWjxkQgApo4kNMBK4oAbz5RNUHMGqKA-AC4oSBAFsARug1bQkI7EQp0WSDj4BfPnwD0PqICg5FAAtFDAABZyAO546HJo7rzCyORKcEjauoqSzmgAFOq8Wpl6wATEUeHUqABu6EQANFB+cXBoxq7QRABEldUQdWjdDCR4SHBltDgkAOZI1BYANtDAcGHYxKaW9VAAdHkATADMBwcAlDaadtCEpBRUtBAsDM0+re1QncTdZByPLMMoKMTBMoFNZvMlis1tdiDkhJ0cERdlBDidzp5jPD0LJ5OglLg+Gc1N5eF5+Lw-FBALwbgBZdkJQFhwXBIIhlCLRMFIEBQd6JZIUNIZHSlbFoA55MByMA4LFOGTS-HKHDEwrFcjpHQkorFLQixTlIh9Wr1JpUsjCdBPdaQBn64DGLZWNBMKC9KomoaXXWw26-B50Z6ac1IS1UFg26ChSPGH73TgQbqu7psP50JPMONpp7db0ecpS+SJcl8IA) - TypeScript starts to show errors when deconstructing function arguments
- [2.8.1](http://www.typescriptlang.org/play/?removeComments=true&target=1&ts=2.8.1#code/C4TwDgpgBAwg9gVwHbAgJwCrggZygXigHIBLJAYzQgEMcIioAfYgEwkprqIFgAoPsqjQAzauWjxkQgApo4kNMBK4oAbz5RNUHMGqKA-AC4oSBAFsARug1bQkI7EQp0WSDj4BfPnwD0PqICg5FAAtFDAABZyAO546HJo7rzCyORKcEjauoqSzmgAFOq8Wpl6wATEUeHUqABu6EQANFB+cXBoxq7QRABEldUQdWjdDCR4SHBltDgkAOZI1BYANtDAcGHYxKaW9VAAdHkATADMBwcAlDaadtCEpBRUtBAsDM0+re1QncTdZByPLMMoKMTBMoFNZvMlis1tdiDkhJ0cERdlBDidzp5jPD0LJ5OglLg+Gc1N5eF5+Lw-FBALwbgBZdkJQFhwXBIIhlCLRMFIEBQd6JZIUNIZHSlbFoA55MByMA4LFOGTS-HKHDEwrFcjpHQkorFLQixTlIh9Wr1JpUsjCdBPdaQBn64DGLZWNBMKC9KomoaXXWw26-B50Z6ac1IS1UFg26ChSPGH73TgQbqu7psP50JPMONpp7db0ecpS+SJcl8IA) - up until this version, TypeScript doesn't show any errors in both usages.

**Search Terms**

- deconstruct
- deconstruction
- default property widening

<details>
<summary>all used Search Terms</summary>

- deconstruct
- deconstruction
- deconstruct default
- deconstruct defaults
- deconstructed property
- default assignment
- default property widening
- default property broader type

However, I couldn't find really meaningful tickets with these searches 😕 
 

</details>

**Code**

<details>
<summary>Error Highlighted version</summary>

![image](https://user-images.githubusercontent.com/4083977/69141290-1e3b5600-0acd-11ea-853e-5562fd8f3fd0.png)

</details>

```ts
type CounterTypes = 'increase' | 'decrease'

interface CounterProperties {
    start?: number
    type?: CounterTypes
}

// ✅ - throws errors
function startCounter({
    start = 'whatever', //error: Type '"whatever"' is not assignable to type 'number' .(2322)
    type = 'increased'  //error: Type '"increased"' is not assignable to type 'CounterTypes'. (2322)
}: CounterProperties
) {
}

// 🔴 - doesn't throw any errors
function startCounter2(props: CounterProperties) {
    const {
        start = 'whatever', // inferred type - start: number | "whatever"
        type = 'increased'  // inferred type - type: "increase" | "decrease" | "increased"
    } = props
}
```

**Expected behavior:**

Assigning a default value to a deconstructed property should be validated based on the property's type.

```ts
type CounterTypes = 'increase' | 'decrease'

interface CounterProperties {
    start?: number
    type?: CounterTypes
}

// ✅ - throws errors
function startCounter({
    start = 'whatever', //error: Type '"whatever"' is not assignable to type 'number' .(2322)
    type = 'increased'  //error: Type '"increased"' is not assignable to type 'CounterTypes'. (2322)
}: CounterProperties
) {
}

// ✅ - throws errors
function startCounter2(props: CounterProperties) {
    const {
        start = 'whatever', //error: Type '"whatever"' is not assignable to type 'number' .(2322)
        type = 'increased'  //error: Type '"increased"' is not assignable to type 'CounterTypes'. (2322)
    } = props
}
```

**Actual behavior:**

Assigning a default value to a deconstructed property broadens the type by making an union between property's type and type of default value. 

**Playground Link:** 

[TypeScript Playground](http://www.typescriptlang.org/play/?removeComments=true&target=1&ssl=23&ssc=2&pln=1&pc=1#code/C4TwDgpgBAwg9gVwHbAgJwCrggZygXigHIBLJAYzQgEMcIioAfYgEwkprqIFgAoPsqjQAzauWjxkQgApo4kNMBK4oAbz5RNUHMGqKA-AC4oSBAFsARug1bQkI7EQp0WSDj4BfPnwD0PqICg5FAAtFDAABZyAO546HJo7rzCyORKcEjauoqSzmgAFOq8Wpl6wATEUeHUqABu6EQANFB+cXBoxq7QRABEldUQdWjdDCR4SHBltDgkAOZI1BYANtDAcGHYxKaW9VAAdHkATADMBwcAlDaadtCEpBRUtBAsDM0+re1QncTdZByPLMMoKMTBMoFNZvMlis1tdiDkhJ0cERdlBDidzp5jPD0LJ5OglLg+Gc1N5eF5+Lw-FBALwbgBZdkJQFhwXBIIhlCLRMFIEBQd6JZIUNIZHSlbFoA55MByMA4LFOGTS-HKHDEwrFcjpHQkorFLQixTlIh9Wr1JpUsjCdBPdaQBn64DGLZWNBMKC9KomoaXXWw26-B50Z6ac1IS1UFg26ChSPGH73TgQbqu7psP50JPMONpp7db0ecpS+SJcl8IA)

**Related Issues:** 

I believe that there should be tickets related to this one, but I just couldn't find them 😕

**Comment by RyanCavanaugh** [comment]
See #19127, #14193, #10577

It's really debatable which behavior is preferable. The inconsistency is unfortunate but it's not worth introducing a breaking change just for the sake of making two different constructs be the same - the current behavior allows a decent amount of developer choice depending on intent.

**Comment by lukaskl** [comment]
Thank you for your quick response. I see that you have a valid reason to do so. 

Also in the mean time we found a workaround, adding type before deconstruction throws errors as expected e.g.:
```ts
const { type = 'increased' }: typeof props = props //error: Type '"increased"' is not assignable to type 'CounterTypes'. (2322)
```

maybe it will be helpful for others who will encounter this problem in the future.
