### ISSUE TITLE
Type information from promise executor bodies is not carried into the parent scope

### ISSUE THREAD

**Issue by Adjective-Object** [microsoft/TypeScript#35195]
**TypeScript Version:**  3.7.2
**Code**

```ts
type MockPromise = {
    promise: Promise<void>;
    triggerPromiseResolution: () => void;
};

function foo(): MockPromise {
    let triggerPromiseResolution: (() => void) | undefined = undefined;

    const promise = new Promise((res, _rej) => {
        triggerPromiseResolution = res;
    });

    return {
        promise,
        triggerPromiseResolution,
    };
}
```

**Expected behavior:**

This should typecheck.

In step 9. of https://www.ecma-international.org/ecma-262/6.0/#sec-promise-executor, promise executors are specifically run _before_ the promise constructor returns.

**Actual behavior:**

This throws the following error
```
Type 'undefined' is not assignable to type '() => void'.(2322)
input.ts(3, 5): The expected type comes from property 'triggerPromiseResolution' which is declared here on type 'MockPromise'
```

**Playground Link:** http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=2#code/C4TwDgpgBAsg9gYwNYAUBOcC2BLAztAXigG8AoKCqMDHfALinSzwgB4A3ObAEwD4BucpWBpsAczEQ0TWhABKEXHAA2AV2DY4AOwYAKAJRQCvKJx6CAvoNIAzVVoQbtUG3DgGG8ZDJYkhFZQhgKBFxSWkaFgUlNScdKF0DIxMzbkMAHyh7bggbbC0IbiMsrRy8gu5rSigEbVxg6mZ8YoKAd0ZI-A4uPkS0RQAaKAB9foArQ2M-aurQiSkffGiVdU0tYv7cQWqLfSrKfuBVNHWyGcpG2QH-GbnwxflFFbjrncsgA

**Related Issues:** I couldn't find any, but I think this would depend on
- function `asserts` making assertions about values in their parent scopes
- Propagating `asserts` through other functions, e.g. something like:
```ts
declare class Promise<TReturn> {
  constructor<T_Assertion = empty_assertion>(executor: (res, rej): asserts T_Assertion): asserts T_Assertion
}
```
- Inferring `asserts` from function bodies

I realize this is a pretty big ask that has a lot of requirements, but I didn't see any discussion around it so I figured this might be a good place to start. I'm working around this right now by casting through unknown.

Type assertions are great to work with, thanks for 3.7.2! 🙂

**Comment by fatcerberus** [comment]
#9998

**Comment by RyanCavanaugh** [comment]
Also #11498
