### ISSUE TITLE
trivial unsoundness due to delete

### ISSUE THREAD

**Issue by mlogan** [microsoft/TypeScript#35208]
I know unsoundness reports are not always welcome, but this is a seemingly trivial case. Feel free to close without discussion if you've been over this. (Although in that case a link to any previous discussion of this issue would be appreciated).

**TypeScript 3.7.2**
[Playground link](http://www.typescriptlang.org/play/#code/C4TwDgpgBAKhDOwoF4oG8BQUoEMBcUiATgJYB2A5llAEYHHlUC+GGAZgK5kDGwJA9mShkIEACbwAggGVgpSgAp49OYwCU6atm6D4-ADYQAdPv4UlajC3ZdeAocATAF+WE42Zs2EeKmz55jhGOJbWOmSIUMAEcJGoaLgEAORs-PxJADS0yTQ4RElQ1gD0RVAAmvwcSWJQRBA4+vogUAAW-JBR-FAUEEg4QhBERPxEUIJjImNsUS3QqY38AO6MUYtd+uQIGGIQho5RwRiOiArAakA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
type Test = {
  a: string
  b: string
}

function needsAString(s: string) {
    console.log(s)
}

function test(a: Test) {
    needsAString(a.a)
}

const t: Test = { a: 'foo', b: 'bar' }

// You'd really hope to get an error on one of the following two lines
delete t.a
test(t)
```

**Output:**
```javascript
"use strict";
function needsAString(s) {
    console.log(s);
}
function test(a) {
    needsAString(a.a);
}
const t = { a: 'foo', b: 'bar' };
// You'd really hope to get an error on one of the following two lines
delete t.a;
test(t);

```

**Expected behavior:**

**Comment by DanielRosenwasser** [comment]
> I know unsoundness reports are not always welcome, but this is a seemingly trivial case.

We're very welcoming to unsoundness reports but we generally balance the complexity of adding a new check with the benefits of that check itself. Is there a real-world scenario where you ran into this?

**Comment by mlogan** [comment]
Sort of. I was deleting a property from an object in some actual code I was writing, and it occurred to me to ask whether that could change the type of the variable bound to that object.

So, in this case, I didn't have an actual bug that I would have expected TS to prevent, but it did seem trivial enough that I wouldn't be surprised if I did get bitten by this some day. 

Further, as a TS novice, this changes my mental model of soundness in TS from "If i don't do wacky stuff with generics or deliberately hide behavior from the compiler, I should be okay" to "There are certain perfectly ordinary things I have to remember not to do if I want to be told of basic errors in my code"

**Comment by RyanCavanaugh** [comment]
Duplicate #13783
