### ISSUE TITLE
Incomplete intl.d.ts interfaces

### ISSUE THREAD

**Issue by piloopin** [Microsoft/TypeScript#3521]
DateTimeFormat.format takes a number or _a date object_.
NumberFormatOptions has some additional fields: minimumIntegerDigits, minimumFractionDigits, ...

**Comment by mhegazy** [comment]
The [spec](http://www.ecma-international.org/ecma-402/1.0/#sec-11.3.2) is really hard to read. but feel free to submit a PR to update the definitions to reflect the spec.

**Comment by piloopin** [comment]
The spec is actually [this one](http://www.ecma-international.org/ecma-402/1.0/#sec-12.3.2). I was looking at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) though as a reference, matching it with the original spec.

I'll send a PR for these two specific issues, but I guess there might be other mismatches too.

**Comment by mhegazy** [comment]
thanks @piloopin
