### ISSUE TITLE
Interface type arguments not honored/are ignored

### ISSUE THREAD

**Issue by IRCraziestTaxi** [microsoft/TypeScript#35217]
**Search Terms:**
I googled variations along the lines of "typescript interface arguments not honored" and found a few issues/SO posts but nothing that addressed this issue.

**Code**
For context, I am trying to augment NestJS's definitions of `IQuery` and `IQueryHandler` so that the return type of the query is known by the controller without having to explicitly specify the types in the controller.

```ts
// NestJS's definitions on which these type definitions are built

// NestJS's IQuery definition
export interface IQuery {
}

// NestJS's IQueryHandler definition
import { IQuery } from './query.interface';
export interface IQueryHandler<T extends IQuery = any, TRes = any> {
    execute(query: T): Promise<TRes>;
}

// Custom interfaces and classes

// IReturnTypeQuery
import { IQuery } from "@nestjs/cqrs";

export interface IReturnTypeQuery<TResult> extends IQuery { }

// IReturnTypeQueryHandler
import { IQueryHandler } from "@nestjs/cqrs";
import { IReturnTypeQuery } from "./return-type-query.interface";

export interface IReturnTypeQueryHandler<TQuery extends IReturnTypeQuery<TResult>, TResult>
    extends IQueryHandler<TQuery, TResult> { }

// ReturnTypeService
import { QueryBus } from "@nestjs/cqrs";
import { IReturnTypeQuery } from "./interfaces/return-type-query.interface";

export abstract class ReturnTypeService {
    private readonly _queryBus: QueryBus;

    public constructor(
        queryBus: QueryBus
    ) {
        this._queryBus = queryBus;
    }

    public async query<TResult>(query: IReturnTypeQuery<TResult>): Promise<TResult> {
        return this._queryBus.execute(query);
    }
}

// GetUsersQuery
import { IReturnTypeQuery } from "src/_common/interfaces/return-type-query.interface";
import { User } from "../../../user/user.entity";

// This produces no error although according to IReturnTypeQueryHandler,
// the type argument for this query should match TResult of GetUsersHandler,
// which is User[] rather than User.
// Omitting the implementation of this interface altogether (no "implements")
// also produces the same result (no error in the handler and "unknown" in the controller).
export class GetUsersQuery implements IReturnTypeQuery<User> { }

// GetUsersQueryHandler
import { QueryHandler } from "@nestjs/cqrs";
import { IReturnTypeQueryHandler } from "../../../_common/interfaces/return-type-query-handler.interface";
import { User } from "../../user.entity";
import { GetUsersQuery } from "./get-users.query";

@QueryHandler(GetUsersQuery)
export class GetUsersHandler implements IReturnTypeQueryHandler<GetUsersQuery, User[]> {
    public async execute(query: GetUsersQuery): Promise<User[]> {
        return [];
    }
}

// UserController
import { Controller, Get, Res } from "@nestjs/common";
import { Response } from "express";
import { GetUsersQuery } from "./queries/get-users/get-users.query";
import { UserService } from "./user.service";

@Controller("users")
export class UserController {
    private readonly _userService: UserService;

    public constructor(
        userService: UserService
    ) {
        this._userService = userService;
    }

    @Get()
    public async getUsers(
        @Res()
        response: Response
    ): Promise<Response> {
        const users = await this._userService.query(new GetUsersQuery());

        return response.status(200).json({
            data: users
        });
    }
}
```

**Expected behavior:**
I would expect:

1. An error in the `implements` portion of GetUsersQueryHandler since the specified `TResult` of GetUsersQuery (`User`) does not match the specified `TResult` of the handler (`User[]`). As stated before, omitting the implementation of `IReturnTypeQuery` on `GetUsersQuery` altogether also produces no error.
2. TypeScript to know that the return type of `users` in the `getUsers` method of `UserController` to be be the type argument of `IReturnTypeQuery` as implemented by `GetUsersQuery` passed to the `query` method.

**Actual behavior:**
There is no error in the handler's `implement` statement although the `TResult` specifications do not match and TypeScript claims the return type of `query` with `GetUsersQuery` as the argument is `unkown`.

**Playground Link:**
[Playground link](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=59&pc=2#code/JYOwLgpgTgZghgYwgAgJIEUCu0CeyDeyAvgFAmiSyIobZQ4AScIAJgDbQA8AKshAB6RWAZzRZcyALzJmOADTJuAJQijpsgHwESyXX34QEmSAAoAjnRwAuRQEobABSgB7ALbBhEHiuEaA3CSk5ODQ8EhoKmCYUCDcOAAOEOL03qqYbGBaAkIsorQShEEUodQREFExcYnJjMzsXDp63DX6OXmR0bEJSZapwumZco26ymkZJFmCECJilkysHFA8NQqj-RlahWQA9NvICGxwwqI1AEKYovgku3q68ZgARmzACDLCOCCvAobGEOaWNny9Fs1z2QQOR1EHUq3QAytAAG4vFBXW73J4vN4fV4WXB9AYaEzDW7IXH0QHQrrVXprAnE+zIJxuDxeWkbbQkvQ3bgACw8yH5zgeMAuCDgkBYyAeeAAcqowAApWEAchOlnOwgAdMTbjd4SgwDyUFAIPEXMgYM4oMhXFaUAhnCFBNrOboTRUQMh8Rt8EQArdSODDsdkABVTzWrag5AygDy3AAojYqig4FAAOaYVzTMDIeKQiCSsDOMoelMtYQ85zpSUPCDR8PQADaAF1kMWZM9056AO7AQ3to0C1zxDjZ8Di4CO5DOGDR1CU8tzOqLAWegDi5UbUGE83qUCGNwexgFucNLh7ohAJegLmtoGQm7A293K+g2ohIafL5awBHY5zdpyk6Jc8W3TZiDIT9RG-CNXwWaBh1HCBxzAICy26Go90WThiVg6BhBWYlt1bYlNmJdFnleI5sX0H5TDJaxHy3OCagZJl3E8TgSJbcjXWQd1OmQVt-T0QMoODUQAGFHTAFw2FXVE9DNYAEXFY0IDgFhHTYPAAH0IyRJAAEIbEXOFEWRAIKMeKisU+ZB0xYgiTHYlxOK8Hi+NdB0QGEXMLgIqQZB7OB+0HDxNQMyykE1RiiX424QAgHtmOfODsOgVydT0WxrP4m440TZNYQikAAGtRENA1uhnGBkAAIkCncGpy3Qbn5JqKuvHsQAagTxSNa1DWYRqeNagq9hMK0+ARaYxojfqjkHFBb0dCBqyq2q00zVC2uQDqN2cncK0SBBgBgYBVFsF1XUEmJkGa4RRN0QMgA)

In addition to the playground, here is the full repro I have provided:
https://github.com/IRCraziestTaxi/ts-interface-test

**Related Issues:**
No other issues I found addressed this issue.

**Comment by dragomirtitian** [comment]
**Note**: Try asking on SO first, the bug tracker is not a good place for such issues. If nobody has a solution on SO only then you should post here. Some of the people here also answer on SO (me included), but it reduces the issue tracker clutter.

You issue is cause by unused type parameters. If a type parameter is not used it does not really participate in inference (ts types are structural, type parameters are not part of the structure, only members are). See [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--)

```ts
interface IQuery { }

interface IQueryHandler<T extends IQuery = any, TRes = any> {
    execute(query: T): Promise<TRes>;
}

interface IReturnTypeQuery<TResult> extends IQuery { 
    __inferenceHelper: TResult
}

interface IReturnTypeQueryHandler<
    TQuery extends IReturnTypeQuery<TResult>,
    TResult
> extends IQueryHandler<TQuery, TResult> { }

class ReturnTypeService {
    public async query<TResult>(
        query: IReturnTypeQuery<TResult>
    ): Promise<TResult> {
        // This is obfuscated by NestJS's QueryBus.
        // See the repro for more context.
        return <TResult>{};
    }
}

class User { }

// NOTE: Type argument passed to IReturnTypeQuery should be
// User[] to align with the implementation of
// IReturnTypeQueryHandler in GetUsersHandler,
// but it throws no error in GetUsersHandler.
class GetUsersQuery implements IReturnTypeQuery<User[]> {
    __inferenceHelper!: User[]
}

class GetUsersHandler implements IReturnTypeQueryHandler<
    GetUsersQuery,
    User[]
    > {
    public async execute(query: GetUsersQuery): Promise<User[]> {
        return [];
    }
}

class Controller {
    private readonly _service!: ReturnTypeService;

    public async getUsers(): Promise<User[]> {
        const users = await this._service.query(
            new GetUsersQuery()
        );
        // Users[]
        return users;
    }
}
```
[Playground Link](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=55&pc=2#code/JYOwLgpgTgZghgYwgAgJIEUCu0CeyDeyAvgFAmiSyIobZQ4AScIAJgDbQA8AKshAB6RWAZzRZcyALzJmOADTJuAJQijpsgHwESyXX34QEmSAAoAjnRwAuRQEobABSgB7ALbBhEHiuEaA3CSk5ODQ8EhoKmCYUCDcOAAOEOL03qqYbGBaAkIsorQShDp6APrFoDDQECBIDBBsiVA2ymkZgWQUodQREFExcYnJjMzsXEW63IP6OXmR0bEJSZapwumZcmOKPqskWYJVuWKWTKwcUDyDCs0rGVqEQQhscMKis30LAMrQAG7A4fgb8UwACM2L8ZMIcNVkBZcMtVhoTBs9NDLDZUK95gMlld4Rt7MgnG4PF4cTdtMjkQB6SmKAAWHmQDOcQJgmGECDgkBYyCBeAAcqowAApd4AclEgwAQmyAHRIvTU5CfFBgWkoKAQeIuZAwZxQZCuPUoBDOEKCOUUvQa3ogZBwm74IgBZGke6PZ7IACqnn1dzIir5AHluABRJoLGRQADmmFcVTAyHiT083LAzm6Nv6iwkwlpznS3KBEBIiu90AA2gBdZBpmSgqO2gDuwFVNbVjNc8Q4cfAnOApuQzhgJZp6J6cyzg2OI31oGQAHEemWoMJp6d1oqgcZGQnVS5G6IQOnoC5Z7bF2Bl6vhqc5Q9kwulz7hJNgJ3u-GZuO3ljYcuq7cGylOUlTVBAtT1NAACENj-pWbQkPeHoXlea7QB2XYQD2YBfpmCxTjeozIihz4XBscEbIByKAiCYJPJCCD6IYxgQOYqKPpepGWPihLuJ4nBwVRlrINaczIFWzp6K6ZBIaIADCppgC4bCnOSehasAXycuqEBwCwppsHgxQ+j8SAwcgGJZp8UCmRAAQAsCoKMfRUJRk+0DCCYPEuHxXiCWplomiAwgJmyHlSDIjZwC2bYeDKxnfL8EAyjC9CIsJFIgBAjYcVegxefKui2JJlqls+VaFSJ362mFK4lcQgRAA)

Also you use `Query` and `QueryHandler` inconsistently in the playground code. Since the types contained no properties, the errors did not show up until I added the property `__inferenceHelper`

**Comment by IRCraziestTaxi** [comment]
@dragomirtitian Apologies if the issue seems like clutter. I was unable to find anything pertaining to this case specifically and I was convinced at the time (prior to your explanation) that it was an issue with typescript.

Thanks for the clarification. After creating this issue I feared it would probably have something to do with the type parameter not actually being used. Indeed, adding an arbitrary property of type `TResult` to the query class does result in the expected behavior, but it seems clunky to have to define that unused property on classes implementing the interface. I may just deal with `unknown` being the return type since all the controller is doing is getting the result of the query and sending it in the response (doesn't really do anything with the result), but it was a neat thought to have the service be able to infer the return type based on the type argument of the query class.

It would be great if type parameters did participate in inference, but after your explanation of how typescript is structural, I understand that is outside of the workings of typescript as it stands.

Before closing the issue, however, I would ask: is it possible/feasible for such a feature to be put on the map for a future release? Feel free to close the issue if the answer is no.

**Comment by dragomirtitian** [comment]
@IRCraziestTaxi I am not the right person to ask about future features, but I don't think anything like this is being actively considered. Since this is part of the FAQ, this limitation is well known and accepted as just 'the way TS works'. 

(I also don't have any rights to close issues, I'm just a helpful TS fan 😊)

**Comment by IRCraziestTaxi** [comment]
@dragomirtitian Oh, I see! Well thanks so much for your help! I guess I will go ahead and close it. It's already on people's minds so if it is made possible in the future it won't be because of this issue.
