### ISSUE TITLE
Issue with nested .flatMap()

### ISSUE THREAD

**Issue by khaledosman** [microsoft/TypeScript#35227]
**TypeScript Version:**  3.7.2

**Search Terms:** Typescript flatMap not working

**Code**

```ts
function transformNBAStandingsToTeams (nbaStandingsResponse: NBASeasonStandingsResponse): NBATeam[] {
  return nbaStandingsResponse.conferences.flatMap(conference => conference.divisions
      .flatMap(division => division.teams
        .map(team => ({
          ...team,
          league: 'nba',
          division: ({ ...division, alias_name: division.alias })
        }))
        .reduce((a, b) => a.concat(b), [])
      )
    )
}

function transformNBAStandingsToTeamsWithFlatMap (nbaStandingsResponse: NBASeasonStandingsResponse): NBATeam[] {
  return nbaStandingsResponse.conferences.flatMap(conference => conference.divisions
      .flatMap(division => division.teams
        .flatMap(team => ({
          ...team,
          league: 'nba',
          division: ({ ...division, alias_name: division.alias })
        }))
      )
    )
}
```

the first version of the function works fine, the second one does not.
As you can tell I refactored the top level function calls to use .flatMap successfully however it doesn't work at the 3rd level.

**Expected behavior:**
replacing the last .map().reduce() with .flatMap() should work fine.

**Actual behavior:**
Throws an error about the inferred types not being compatible/properties missing from interface.
if I replace it with .map().flat() instead it works fine aswell

**Playground Link:** https://stackblitz.com/edit/typescript-playground-kqdhvq

**Comment by jablko** [comment]
In the playground, when you transform `Team` to `NBATeam`, where do you add `alias_name`?

**Comment by ilogico** [comment]
The error is correct. You have to return arrays from your mapper function.
`flat` works because it has a strange overload `flat<U>(depth?: number): any[];`, where it's not even using type `U`.
`concat` works because it allows `E | readonly E[]`

**Comment by khaledosman** [comment]
Thanks @jablko & @ilogico 
You're right I had extra properties typed in `NBATeam` that were not included in the `NBASeasonStandingsResponse` 

And I didn't need a `flatMap()` in the third level since I was returning an un-nested 1 dimensional array so I replaced it with `map()` instead.

It was confusing how `.flat()` and the `.reduce()` / `.concat()` version worked but not that `flatMap()` one though.

**Comment by jablko** [comment]
I agree that is confusing.
