### ISSUE TITLE
NonNullable<unknown> should return `{}`

### ISSUE THREAD

**Issue by Validark** [microsoft/TypeScript#35221]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** NonNullable `NonNullable<unknown>` `NonNullable<any>`

**Rationale**
The definition of `NonNullable` is "Exclude null and undefined from T". It does this, literally, but I think it should also exclude null and undefined from `any` and `unknown`, which in this case would be `{}`, since all types but null and undefined are assignable to `{}`.

**Proposal type**
```ts
type NonNullable<T> = unknown extends T ? {} : T extends null | undefined ? never : T;
```

Demo:
```ts
type Test = NonNullable<unknown>; // {}
type Test2 = NonNullable<any>; // {}
type Test3 = NonNullable<string | undefined>; // string
```

**Problem Code**

```ts
type Test = NonNullable<unknown>;
```

**Expected behavior:** should evaluate to `{}`

**Actual behavior:** evaluates to `unknown`

[**Playground Link**](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAKhDOwoF4oDkD2A7NBXANvgIYBG+EAPLlgNZYYDuWAfANwCwAUF6JOtnkKlyAJgoxmKKNTqMsUCAA9gELABN4sKAH4oAbwC+UAFxalK9ZqwF8UAD7T1EAGYBLLBDU6oHgG4QAJxNYDk5eaDhEESlMHBthCDEZeiY2HnAIhGAAZhiBeLJEiiIsEDSwjNgsgBY8uKFCsUQA9wBze0c1F3dPDutCNiA) 

**Related Issues:**  n/a

**Comment by RyanCavanaugh** [comment]
This would be a fairly disruptive breaking change and there isn't any practical upside demonstrated here.
