### ISSUE TITLE
Inference of “this” with higher order functions

### ISSUE THREAD

**Issue by bspot** [microsoft/TypeScript#35222]
**TypeScript Version:**  Version 3.8.0-dev.20191120

**Search Terms:** 

* higher order function "this" type inference
* object literal "this" type inference

**SO Link:** https://stackoverflow.com/questions/58817677/typescript-inference-of-this-with-higher-order-functions

**Code**

When I define a method in an object literal, Typescript will correctly identify the type of `this`, e.g.:

```ts
const test = {
  foo: function() {
    return { type: 'foo' }
  },
  bar: function() {
    // Usage of "this" is fine for Typescript.
    return { type: 'bar', foo: this.foo() }
  }
}
```

This breaks when I use a higher order function to wrap the method:

```ts
function hof<THIS, RESULT>(wrapped: (this: THIS) => RESULT): (this: THIS) => RESULT {
  return function() {
    return wrapped.call(this)
  }  
}

const test = {
  foo: function() {
    return { type: 'foo' }
  },
  bar: hof(function() {
    // TS2339: Property 'foo' does not exist on type 'unknown'.
    return { type: 'bar', foo: this.foo() }
  })  
}
```

**Expected behavior:**
No compilation error.

**Actual behavior:**
```
failing.ts:12:37 - error TS2339: Property 'foo' does not exist on type 'unknown'.

12     return { type: 'bar', foo: this.foo() }
```

**Comment by RyanCavanaugh** [comment]
The "right" way to do this would be to specify that the function expression needs to be invoke with the context of `test`:
```ts
   bar: hof(function(this: typeof test)
```
But in this case that generates a circularity
