### ISSUE TITLE
Inline classes not supported

### ISSUE THREAD

**Issue by mhevery** [Microsoft/TypeScript#3522]
```
function ident(x) { return x; }

var Foo = ident(class Foo {})
```

Throws:
```
error TS9003: 'class' expressions are not currently supported.
```

I believe that is a valid ES6 syntax, and it should work.

**Comment by mhegazy** [comment]
We are adding the support for class expressions currently. class expressions should be fully supported in 1.6.

**Comment by danquirk** [comment]
#497 is the main source of discussion
