### ISSUE TITLE
Suggest class name from file

### ISSUE THREAD

**Issue by birgersp** [microsoft/TypeScript#35220]
## Search Terms

vscode typescript autocomplete class name

## Suggestion

When I am about create a new class in a file, I'd like the appropriate class name to be suggested in autocomplete.

## Use Cases

When creating new Typescript classes with VSCode.

## Examples

Example: The user wants to create a class named "Person". The user creates a new file: "Person.ts".
The user opens that file and starts writing: "export class Pe".
At this point, the user should be able to Ctrl+Space, and VSCode should provide the option to autocomplete "Person". It is the name of the file, so it is likely that the user wants this name for the class.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by birgersp** [comment]
This issue was initially created here: microsoft/vscode#85092

**Comment by RyanCavanaugh** [comment]
This just doesn't meet the bar for value provided vs possible downsides

**Comment by birgersp** [comment]
Hi Ryan,

What possible downsides?

**Comment by RyanCavanaugh** [comment]
Today, this is a "new identifier" location where we don't suggest anything. What are the implications of changing that?
What happens if the filename isn't a legal identifier?
What happens if the filename is a keyword?
What muscle memory might get broken as a result of this?
Does this only happen for the first class in a file, or for all classes? Will that be annoying?
Should this happen in a nested class context? Why or why not?

etc.

https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/

**Comment by birgersp** [comment]
> Today, this is a "new identifier" location where we don't suggest anything. What are the implications of changing that?
I can't answer that. But why should you not make suggestions at a "new identifier" location?

> What happens if the filename isn't a legal identifier?
Nothing should happen.

What happens if the filename is a keyword?
> Nothing, don't make a suggestion. This is the behaviour in other IDEs. As demonstrated here:

![image](https://user-images.githubusercontent.com/5260237/79366574-b63e4e00-7f4c-11ea-8487-5231c49e105e.png)

> What muscle memory might get broken as a result of this?
Is "breaking muscle memory" really an argument to not implement improvement suggestions? What improvement can you ever make without "breaking muscle memory"? Do you never run because you may forget how to walk?

> Does this only happen for the first class in a file, or for all classes? Will that be annoying?
All classes. It won't be annoying because the suggestion is only made at the request of the user (i.e. when the user pressed Ctrl+Space).

> Should this happen in a nested class context? Why or why not?
It should not. It is fair to assume that if any class should take the name of the source file, it should be the top-level class.

Try using other IDEs where this is implemented. CLion, IntelliJ, Netbeans, Eclipse. They got this figured out already.
