### ISSUE TITLE
TsConfig: flatten type errors.  "Advanced Type" errors currently often unreadable.

### ISSUE THREAD

**Issue by SephReed** [microsoft/TypeScript#35246]
## Search Terms

"Type error read"
"type errors unreadable"

## Suggestion

Type checking, and type definitions errors could me made significantly easier to debug by flattening/boiling down the type definitions to something more resembling what developers think of them as.

1. This first example shows the kind of errors I run into in actual development. It's totally unreadable.
<img width="836" alt="Screen Shot 2019-11-20 at 3 58 27 PM" src="https://user-images.githubusercontent.com/14002040/69282740-93cc2280-0bb0-11ea-9c6a-ead7598bec37.png">

2. This second example shows the same effect
<img width="734" alt="Screen Shot 2019-11-20 at 4 02 52 PM" src="https://user-images.githubusercontent.com/14002040/69283569-4650b500-0bb2-11ea-85c1-4e442cf1062a.png">

<img width="477" alt="Screen Shot 2019-11-20 at 4 01 34 PM" src="https://user-images.githubusercontent.com/14002040/69282763-a21a3e80-0bb0-11ea-9112-344fe8403a71.png">

For this second example, it would be a lot more useful if instead it just showed what the type realistically is, and what it was missing. Ie:

```
Property "badProp" does not exist on type '{
  requestId: string;
  type: string;
  id?: string;
  createdAt?: Date;
  data?: string;
}'
```

**This would be a really nice thing to add to tsconfig.**

## Use Cases

Almost 100% of the time one works with advanced types.  Anything involving unions or (worst of all) utility types creates a wall of text.

## Examples

```
// ts.config
{
  flattenTypesInMessaging: true
}
```
(I'll make a habit of posting all my most unreadable messages here)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
I really meant it in #35247 when I said we wanted a way to reproduce that error 😢

**Comment by SephReed** [comment]
I had made these at the same time, unsure of whether or not it was a vscode or typescript issue.  The other one you linked was posted in vscode and moved here.
