### ISSUE TITLE
Typescript: Realistic type definition errors

### ISSUE THREAD

**Issue by SephReed** [microsoft/TypeScript#35247]
Type checking, and type definitions errors could me made significantly easier to debug by boiling down the type definitions to something realistic.  

1. This first example shows the kind of errors I run into in actual development.  It's totally unreadable.

<img width="836" alt="Screen Shot 2019-11-20 at 3 58 27 PM" src="https://user-images.githubusercontent.com/14002040/69281957-da208200-0bae-11ea-99b5-265b49253aee.png">

2. This second example shows the same effect

<img width="477" alt="Screen Shot 2019-11-20 at 4 01 34 PM" src="https://user-images.githubusercontent.com/14002040/69282075-0f2cd480-0baf-11ea-9f15-3ca2b78dd501.png">
<img width="734" alt="Screen Shot 2019-11-20 at 4 02 52 PM" src="https://user-images.githubusercontent.com/14002040/69282153-3a172880-0baf-11ea-94ed-c8e008e5346c.png">

For this second example, it would be a lot more useful if instead it just showed what the type realistically is, and what it was missing.  Ie:

```
Property "badProp" does not exist on type `{
  requestId: string;
  type: string;
  id?: string;
  createdAt?: Date;
  data?: string;
}`
```

This could be a configuration thing, but I can't imagine any reason why a person would want cryptic error messages by default.

**Comment by AnyhowStep** [comment]
Kind of a difficult one.

It's not always true that the fully expanded type is more readable than the type alias.

-----

I personally manually control the emit of my types to try and get the best error message I can.

**Comment by SephReed** [comment]
> I personally manually control the emit of my types (via type hackery)

How do I get started on that? 

And I'm sure this is one of those threads that once you start pulling... but, never-the-less, it couldn't be any worse than it is for some of these errors.

**Comment by AnyhowStep** [comment]
To force TS to expand types,
https://github.com/microsoft/TypeScript/issues/3455

To force TS to not expand types (situational, doesn't work for all cases),
https://github.com/microsoft/TypeScript/issues/34777#issuecomment-551993933

**Comment by SephReed** [comment]
This is the most helpful response I think I've ever gotten to a GH issue.  Thank you very much.... I'm going down the rabbit hole.

**Comment by RyanCavanaugh** [comment]
A way to reproduce the error you saw would be very useful. We can sometimes improve error messages based on the use case.

Anyway it's not at all clear what the right rule is here; if one way were just always better than the other, that's the one we'd be doing by now (one would hope).

Let's say you had something like
```ts
interface Options {
  height: number;
  length: number;
  depth: number;
  width: number;
  color: string; 
  name: string;
  orientation: string;
  location: string; 
  age: number;
  // 30 other properties
}
```
and you use `Options` a lot throughout your code.

Somewhere, a function says
```ts
function fn(opts: Partial<Omit<Options, "orientation">>) {

}
```
and you call it incorrectly.

What would you want to see? `Partial<Omit<Options, "orientation">>` which says "Options, but it's all optional, and no `orientation`" or

```
{
  height?: number;
  length?: number;
  depth?: number;
  width?: number;
  color?: string; 
  name?: string;
  location?: string; 
  age?: number;
  // 30 other properties
}
```
where you will have to *manually diff* the property list to figure out which one got removed? That would be clearly worse in a lot of cases.

You can't just rely on "Well if the alias appears in the code, then use that" rule either because these types can appear in higher-order forms, e.g.
```ts
function fn<T, U extends keyof T>(obj: T, key: U, others: Partial<Omit<T, U>>) {
```
where you'd *still* want the unexpanded alias form.

**Comment by SephReed** [comment]
I suppose the ideal would be some form of switching between the two.  I don't expect that to have any easy way, but (if it was possible) it might be like:

- Get error: `Partial<Omit<Options, "orientation">>`
- click "show flattened"  
- have it turn to the long bare version
- then click "show symbolic" to go back.

> Anyway it's not at all clear what the right rule is here;

Perhaps there is a way to pass this logic off to user land?  There are some things I'd like to try.

Speculatively, I think it might be effective to show flat versions of anything with a symbolic tree of over 3-4 nodes.  Other times, it could perhaps fit both the symbolic and flat version one after another.

I've been getting really into advanced, conditional, and utility types for my projects.

**Comment by weswigham** [comment]
> I suppose the ideal would be some form of switching between the two.

A feature for [this](https://github.com/microsoft/TypeScript/pull/31384), mayhaps?

**Comment by SephReed** [comment]
@weswigham That would definitely be a good way to go about it.  Really, anything works for me, as long as I can see what the final list of properties and types for them is.

**Comment by SephReed** [comment]
I'm going to post examples here as they come up.

<img width="838" alt="Screen Shot 2020-01-03 at 11 18 19 AM" src="https://user-images.githubusercontent.com/14002040/71737976-d5d8bd00-2e1a-11ea-9013-cd66b9be5ab6.png">

**Comment by SephReed** [comment]
<img width="863" alt="Screen Shot 2020-02-08 at 2 56 12 PM" src="https://user-images.githubusercontent.com/14002040/74091931-3e066880-4a83-11ea-8561-01821947e611.png">

**Comment by AnyhowStep** [comment]
The thing is, I feel like most people don't know how to get the current type system to produce "good" type emit. Especially for complex generic types.

There are tricks for these things. But sometimes, the types are just too large and some amount of difficult-to-read output is unavoidable.

**Comment by SephReed** [comment]
I've found a solution for my scenario, and it is to create facade types that are simple and assert their equivalency to my more complex (and realistic) types elsewhere.  

I'm not sure what the limitation of facade types is, but so far it's doing the trick.

**Comment by vadimshvetsov** [comment]
Just started to find a way to fold a type in error message. I'm new in typescript and sometimes I fight with it so hard to be safe typed. But when I see message like this I start to consider renaming this file to `.js` extension.

![image](https://user-images.githubusercontent.com/16336572/80774759-8c993f80-8b66-11ea-8bcb-9d92c036c6f4.png)
