### ISSUE TITLE
Lambda losing track of scope of "this"

### ISSUE THREAD

**Issue by joelmdev** [Microsoft/TypeScript#3525]
I have a function like this in my TypeScript+Angular application (using Definitely Typed typings):

    public login() {
        this.dataModel.login({
            grant_type: "password",
            userName: this.userName,
            password: this.password,
            isPersistent: this.rememberMe
        }).then<void>(
            successResult => {
                this.$rootScope.user = new User(successResult.userName);
                this.$location.path("manage");
            },
            errorResult => {
                this.$rootScope.errors.push(errorResult);
            });
    }

which compiles down to the following Javascript:

    LoginController.prototype.login = function () {
        var _this = this;
        this.dataModel.login({
            grant_type: "password",
            userName: this.userName,
            password: this.password,
            isPersistent: this.rememberMe
        }).then(function (successResult) {
            _this.$rootScope.user = new App.User(successResult.userName);
            _this.$location.path("manage");
        }, function (errorResult) {
            _this.$rootScope.errors.push(errorResult);
        });
    };

When debugging the TypeScript code and stepping through in VS2013, "this" becomes undefined within the promise handlers, but the given the way the TS compiles the actual Javascript works as expected. They can't both be right, and I believe the Javascript has the desired behavior- "this" should reference the LoginController instance in the TypeScript as well... right?

Present in TS 1.4 and 1.5, not sure about earlier versions.

**Comment by mhegazy** [comment]
This is already tracked by #2617; this is an issue with the debugger extension not knowing that `this` was renamed to `_this` when you hover over it.

**Comment by joelmdev** [comment]
Great thanks! Sorry for the dupe!
