### ISSUE TITLE
Limit number of add missing import quick fixes returned

### ISSUE THREAD

**Issue by capaj** [microsoft/TypeScript#35269]
Currently if someone is writing react for example and they have lodash and react-intl,
when they write `find` and they want to use the quick-fix to add the missing import from lodash, they get this:
![image](https://user-images.githubusercontent.com/1305378/69358063-87b29480-0c86-11ea-97f9-4a1bffda74d9.png)

Is it really necessary to render and display such a long list?
Wouldn't it be nicer to just show the number of items that can fit on height of the screen and as the last item render a collapse button that would show all the items when clicked?

**Comment by mjbvz** [comment]
Can you share the project that caused this?

**Comment by capaj** [comment]
I can create you a reproduction project. Give me  a few hours.

**Comment by RyanCavanaugh** [comment]
😲

**Comment by capaj** [comment]
here's the repro repo with the problematic statement: https://github.com/capaj/vscode-quickfix-issue-repro/blob/master/test.tsx#L1

just clone, `npm i` and navigate to that file

**Comment by andrewbranch** [comment]
There are several things worth noting here beyond the size of the list:

1. react-intl v3 stopped shipping a module structure like this, which seems good
2. seems like import fixes should be sorted by number of path segments—even if all these nonsense things show up, they should prioritized less than `'lodash'`
3. the reason all these show up as a match for `find` is that these modules export an _array_—so `find` is actually a destructuring import for `Array.prototype.find`, which is, uh, incredibly wrong.

I’m tempted to fix 2 and 3, but not artificially limit the number of items we return unless it becomes a problem in a world where we’re actually returning _correct_ items. I’m not at all concerned about the UI side of things, as that should be either an OS or VS Code concern. I think the only reason TypeScript should limit its response is if there’s a high performance cost to continuing. But, we can talk about that if it happens again without the lists being padded by garbage results.
