### ISSUE TITLE
TS2339: Property 'message' does not exist on type 'AtMessage'.

### ISSUE THREAD

**Issue by huangjihua** [microsoft/TypeScript#35262]
**TypeScript Version:**  3.7.2

**Search Terms:**

**Code**

```ts
import {
  LitElement,
  html,
  property,
} from "lit-element";

export class AtMessage extends LitElement {
  static get properties() {
    return { message: { type: String } };
  }
  constructor() {
    super();
    this.message = "default";
  }

  render() {
    return html`
      <div>${this.message}</div>
    `;
  }
}
if (!customElements.get("at-message")) {
  customElements.define("at-message", AtMessage);
}
```

**Expected behavior:**

**Actual behavior:**
TS2339: Property 'message' does not exist on type 'AtMessage'.
**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment]
... and? What is the expected behavior? You didn't fill out the issue template properly.

Your class has no `message` property, and I doubt that your base class `LitElement` has one either.

**Comment by RyanCavanaugh** [comment]
Please provide a self-contained repro
