### ISSUE TITLE
Filter object function name

### ISSUE THREAD

**Issue by hubluesky** [microsoft/TypeScript#35261]
I am having a problem when I filter function names for an object. Please ask.
1. I have an object:

```typescript

class Model {
    public health: number = 0;
    public showname: string = "war";
    private _familyName: string = "ff";
    public get familyName(): string {
        return this._familyName;
    }
    public set familyName(value: string) {
        this._familyName = value;
    }

    public Acttack(): void {
        console.log("model attack");
    }
}
```

2. Then extract the object property name

```typescript
type im = keyof InstanceType<typeof Model>;
// type im = "health" | "showname" | "familyName" | "Acttack"
```

3. Exclude object's function name

```typescript
type Exclude2<T, U extends keyof T, K> = T[U] extends K ? never : U;
type pt = Exclude2<Model, im, Function>
// type pt = "health" | "showname" | "familyName" | "Acttack"
```

4. Then I did a test
```typescript
type pt2 = Exclude<Model[im], Function>;
// type pt2 = string | number
```

5. The function type here will be filtered, I am a bit strange, why can't my __*Exclude2*__ function filter out function types?
Why is the result not type pt = "health" | "showname" | "familyName" ? Is this a bug?
``` typescript
type Exclude2<T, U extends keyof T, K> = T[U] extends K ? never : U;
type pt = Exclude2<Model, im, Function>
// type pt = "health" | "showname" | "familyName"
// Filtered Acttack here
```

**Comment by AnyhowStep** [comment]
It's not a bug.

```ts
type Exclude2<T, U extends keyof T, K> = {
  [u in U] : T[u] extends K ? never : u;
}[U];
```

I'm on mobile, so I can't test, but the above should work

**Comment by AnyhowStep** [comment]
Also, you should follow the issue template.

**Comment by AnyhowStep** [comment]
Another thing that should work is to **distribute** the `U`.

```ts
type Exclude2<T, U extends keyof T, K> = 
  U extends keyof T ?
  (T[U] extends K ? never : U) : 
  never
;
```

**Comment by hubluesky** [comment]
> Another thing that should work is to **distribute** the `U`.
> 
> ```ts
> type Exclude2<T, U extends keyof T, K> = 
>   U extends keyof T ?
>   (T[U] extends K ? never : U) : 
>   never
> ;
> ```
> 
> This looks more like your original attempt. I've just wrapped it in an extra conditional type.
> 
> The rules for distributing union types can be pretty unintuitive.
> 
> You should read this,
> https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types

Thank you very much for your answer and help me solve this problem.
My original understanding is wrong, I will take a good look at Advanced types.
