### ISSUE TITLE
Top level await breaks with parentheses

### ISSUE THREAD

**Issue by kevinkassimo** [microsoft/TypeScript#35276]
**TypeScript Version:**  3.7.2

**Search Terms:** Top 

**Code**

```ts
const v = await (1);
```

**Expected behavior:**
No error thrown. (If renaming this file to `.js` extension, it would be accepted by runtimes that enables top-level await e.g. Deno, indicating this is accepted by engines like V8)

**Actual behavior:**
```
error TS2304: Cannot find name 'await'.

► file:///Users/kun/Projects/Deno/test/tla.ts:5:11

5 const v = await (1);
            ~~~~~
```

**Playground Link:** Not available

**Related Issues:** Not found

**Comment by kevinkassimo** [comment]
Sorry, I thought 3.7 turns on top-level await support. Turns out Deno turns off top-level await warnings ourselves and TLA support for TS is not fully completed yet

**Comment by j-oliveras** [comment]
As a reference, #25988 tracks adding top level await. Currently planed for 3.8.
