### ISSUE TITLE
Kinda wrong definition of the DocumentReadyState type in lib.dom.d.ts

### ISSUE THREAD

**Issue by lukejagodzinski** [microsoft/TypeScript#35285]
In the file `lib.dom.d.ts`, the `DocumentReadyState` type is defined as:

```ts
type DocumentReadyState = "loading" | "interactive" | "complete";
```

which is correct according to spec https://html.spec.whatwg.org/multipage/dom.html#documentreadystate, but the problem is that it's not really true if you take into account browsers like Firefox where you have additional states. And this type should look like this:

```ts
type DocumentReadyState = "uninitialized" | "loading" | "loaded" | "interactive" | "complete";
```

Here you have some details https://www.w3schools.com/jsref/prop_doc_readystate.asp

It's pretty annoying that browsers do not respect specification. And actually this incorrect behavior in FF caused our code not to work, so I had to patch it. I feel like, even though that this change is not correct with the spec it would make it easier to use. Currently, I had to create my custom type which is not big deal but maybe you will consider changing type definition.

**Comment by RyanCavanaugh** [comment]
In general we don't make lib adjustments for nonstandard browsers unless something is really critically amiss; this doesn't seem to meet the bar.

**Comment by lukejagodzinski** [comment]
I understand that but then your current type definition is wrong as it adds extra `interactive` value where w3c specification only mentions `loading` and `complete` https://dev.w3.org/html5/pf-summary/dom.html#dom-document-readystate but I guess you're not following this spec or you just made an exception already? :)
