### ISSUE TITLE
Typescript language service plugin CLI output

### ISSUE THREAD

**Issue by ashubham** [microsoft/TypeScript#35287]
## Search Terms

language service plugin output ide integration

## Suggestion

Currently the Language service plugins are IDE only. Which makes them useful only on IDEs that support them. For eg. `ts-lit-plugin` is only supported on VSCode and not on Webstorm. 

It will be great if one could have command line output for `tsc` users from the plugins. In most cases these plugins are additional style checks/validators which would be useful to get on the CLI.

## Use Cases

- Validation plugins not supported by IDEs yet.

## Examples

- (ts-lit-plugin)[https://github.com/runem/lit-analyzer/tree/master/packages/ts-lit-plugin] not supported on Webstorm
- (ts-graphql-plugin)[https://github.com/Quramy/ts-graphql-plugin] Not supported on Webstorm.

When using `tsc` and one of the other plugins the service could output `warnings` or `errors` if any.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #16607 and others
