### ISSUE TITLE
Generic type extended in method not inferred without cast

### ISSUE THREAD

**Issue by connor4312** [microsoft/TypeScript#35288]
**TypeScript Version:** 3.8.0-dev.20191121

**Search Terms:** `unknown' is not assignable to type`, `interface cast`, `unknown generic`

**Code**

```ts
interface IFoo<T> {
    run<R extends T>(value: R): R;
}

class Foo<T> implements IFoo<T> {
    run<R extends T>(value: R): R { return value; }
}

declare function bar<T>(foo: IFoo<T>): void;

const works: IFoo<string> = new Foo<string>();
const doesNotWork = new Foo<string>();

bar(works);
bar(doesNotWork);
```

**Expected behavior:** I should expect `bar` to correctly infer the generic type in `IFoo` when given a `Foo<string>`

**Actual behavior:** 

```
Argument of type 'Foo<string>' is not assignable to parameter of type 'IFoo<unknown>'.
  Types of property 'run' are incompatible.
    Type '<R extends string>(value: R) => R' is not assignable to type '<R extends unknown>(value: R) => R'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'R' is not assignable to type 'string'.
          Type 'unknown' is not assignable to type 'string'.
```

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=Nightly#code/JYOwLgpgTgZghgYwgAgJIDED2mA8AVAPmQG8AoZC5KAVxBwCVkIAPSEAEwGdlCAKANzgAbahABcyegEoJ9ANykAvqVIIhcTtyy5CyYAFsADkIj6I4bhmz4iZSlVoMmrc1x4EBw0bJmSSVCDBqKBBkQREIOWRlZVJ2CDU4KBQYWgQwYExQgCMkm14YbAkrHQJffkxgdgVVLM4wZAB3TCgAa05i7Rx6qFAAcyIAXmQQCEbkLp7+jykFBDqG9kwITgA5TDAAdRbW5GHR8cmwXpAB3lmVXKheZrbOC6veJZX1rZ3ZoA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Generic constraints aren't inference sites (and really shouldn't be), so this is effectively https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--
