### ISSUE TITLE
Union of arrays doesn't get converted to array of unions

### ISSUE THREAD

**Issue by polkovnikov-ph** [microsoft/TypeScript#35294]
**TypeScript Version:**  3.8.0-dev.20191121

**Search Terms:** array union

**Code**

```ts
declare const x: 'a'[] | 'b'[];
x.forEach(v => { }); // FAIL

// it doesn't work as is, so we have to resort
// to enforcing the shape of the type
const shape = <T>(t: T[]): T[] => t;
const x1 = shape(x); // converts to ('a' | 'b')[]
x1.forEach(v => { }); // OK

declare const y: 'a'[] | 'b'[] | never[]
y.forEach(v => { }); // FAIL
const y1 = shape(y); // cannot convert anymore
y1.forEach(v => { }); // FAIL

declare const z: 'a'[] | never[]
z.forEach(v => { }); // OK. apparently 3 cases was too much
```

**Expected behavior:**
No error messages in either case.

**Actual behavior:**
Conversion of union of arrays to array of unions happens only if it's enforced manually, and only if there is no `never[]` cases.

**Playground Link:** 
[Link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191121&ssl=1&ssc=1&pln=17&pc=1#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwHIoCBtAXXgB9CAjUsgbgChsA6AMyRgFEowALABQA3eAF4AfPADe8AL4BKBvAD0K+ADEAggEkAMkyZr4ASyzAkINCgJYA7lwDW8KGlNoANPDRJ4dhPxQwggYvnA+MBhG6qHwICicMGAmKADm8Bj8CGiBAA4ISOwZWRkAnvlMyOhYOVD54vAAPAAqEoIY+M3kCp3k4lIYzFWYOACMDbX5gthKqupVwZFusYJEBFS0BArkLKMcXLwCIv0y8krGAPIA0oagkLAIw1il+Gt91AR07-AoIIs7pX2PD4QlEklOimUxm0+kqqBGpXGYm8eRAglKs2MYCgKBQSCwCxAkRcKFKAFsuCAmIigYdQSdZJC5ppdAYmHdoHBEPCsAAvV7Eb6-f5kJi82kg47gxmY9TXVguXK5B4oDAQUrwADMiFcVj8rgySF8ZIArgImEA)

**Comment by RyanCavanaugh** [comment]
Many duplicates of this - start at #34605 and explore from there

**Comment by polkovnikov-ph** [comment]
I thought the issue with call signatures was only related.

Closing as duplicate of #7294.

**Comment by polkovnikov-ph** [comment]
For other suffering people: it works in both cases if you use another shaping function. So at least there is some way to make code work without `any`.

```ts
const thiccShape = <T extends any[]>(t: T): T[number][] => t;
```
