### ISSUE TITLE
Avoid elaborating missing properties on common container types

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35300]
> As a separate change, it might be nice to special case the message `Foo is not assignable to Promise<Foo>` to say something about adding `await`, rather than listing missing properties.

_Originally posted by @amcasey in https://github.com/microsoft/TypeScript/pull/35278_

**Comment by DanielRosenwasser** [comment]
* Array
* ReadonlyArray
* Promise
* Set
* Map
* WeakSet
* WeakMap
* Typed Arrays

**Comment by fatcerberus** [comment]
> special case the message `Foo is not assignable to Promise<Foo>`

Isn't that backwards?  It should be the other way around because:

```ts
declare let foo: Foo;
declare let fooPromise: Promise<Foo>;
fooPromise = foo;
```

adding an `await` wouldn't actually help you in the case above.  It would if the assignment were the other way around.

**Comment by Kingwl** [comment]
Any common error message?

**Comment by weswigham** [comment]
`Do you need an 'X' of 'Y'?` ex, `Do you need an 'Array' of 'number'?` or `Do you need an 'IteratorResult' of '{x: number, y: number}'?` maybe? Eh, that's maybe not great when `X` has multiple generics, as it's ambiguous to which you're referring.

**Comment by weswigham** [comment]
I do think promise is a bit more special than the rest of these, however - passing a `Promise.resolve(x)` rather than just `x` is common given promise-based API shapes. Wrapping a single value into a collection, however, I'd find much more suspect.

**Comment by RyanCavanaugh** [comment]
This works as expected now
