### ISSUE TITLE
Add alias -c | --config for tsc command line tool

### ISSUE THREAD

**Issue by srslafazan** [microsoft/TypeScript#35315]
## Search Terms

config configuration implicit typescript tsc tsconfig tsconfig.json tsconfig.*.json commandline cli command-line specify project-specific build

## Suggestion

Took a while to figure out that `-p | --project` accepts a config file. We should include `-c | --config` alias, to be explicit.

## Use Cases

Prevent human suffering and additional open issues.

## Examples

// Imagine that "server" and "client" have incompatible dependencies.
```bash
tsc --config .tsconfig.server.json --outDir ./dist/server/
tsc -c .tsconfig.client.json --outDir ./dist/client/
```

Related issues:
- https://github.com/Microsoft/TypeScript/issues/5858
- https://github.com/microsoft/TypeScript/issues/2869
- https://github.com/microsoft/TypeScript/issues/5705

... and many more

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment]
It already exists as `--project` or `-p`. [Compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by srslafazan** [comment]
@j-oliveras -- so is the tsc workaround just to always assume config based on the directory? If so, it might work for most use cases, but it's not the same thing and it's unusual behavior for a compiler.

**Comment by srslafazan** [comment]
Looking through the config, I realized that the `-p|--project` flag also accepts a config file! The parameter name is just so confusing. This is probably why so many issues have been opened on this subject. Honestly, the flag `-c | --config` should be added to prevent further human suffering, I can't think of a reason not to add this. Thanks for the help @j-oliveras.

**Comment by srslafazan** [comment]
Re-opened with the updated feature request topic.

**Comment by fatcerberus** [comment]
From `tsc --help`:
> Compile the project **given the path to its configuration file**, or to a folder with a 'tsconfig.json'.

From https://www.typescriptlang.org/docs/handbook/compiler-options.html:
> The argument can be **a file path to a valid JSON configuration file**, or a directory path to a directory containing a tsconfig.json file.

This is made very clear in the documentation.  What made you think "project" was necessarily synonymous with "directory"?

**Comment by MartinJohns** [comment]
Please don't crowd the CLI with useless options.

**Comment by srslafazan** [comment]
@fatcerberus — every other CLI on earth

**Comment by RyanCavanaugh** [comment]
To be clear, the issues you referenced are for people asking for *the ability to do the thing that you didn't realize you could do*.

It doesn't seem like creating two flags with different names that do the same thing is going to help the problem of "People who don't read the documentation are confused".
