### ISSUE TITLE
Deep interface errors are not helpful

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#3531]
If an interface has some deep property and an object from that type has a inner property that is not conforming to the type interface, TypeScript compiler will throw an error which is not very helpful because it's not pointing to exact property that is not matching.

Consider following example:

```typescript
interface Person {
	location: {
		city: {
			name: string
		}
  	}
}

var obj: Person = { location: { city: { name: 1  }}};
```
**Error thrown:**
```
Type '{ location: { city: { name: number; }; }; }' is not assignable to type 'Person'. Types of property 'location' are incompatible. Type '{ city: { name: number; }; }' is not assignable to type '{ city: { name: string; }; }'. Types of property 'city' are incompatible. Type '{ name: number; }' is not assignable to type '{ name: string; }'. Types of property 'name' are incompatible. Type 'number' is not assignable to type 'string'.
```

The error that is thrown is not telling me that `name` needs to be a string, it's complaining about `obj` as a whole. 

This is a bigger issue for interfaces that are driven from a JSON Schema like [Swagger type interface](https://github.com/mohsen1/swagger.d.ts/blob/master/swagger.d.ts)

**Comment by RyanCavanaugh** [comment]
> The error that is thrown is not telling me that name needs to be a string, it's complaining about obj as a whole.

?. Keep reading to the end of the error:
```
Types of property 'name' are incompatible. Type 'number' is not assignable to type 'string
```

Imagine the opposite world, where for an arbitrarily-deep object, we *didn't* tell you the path to the member that was causing the incompatibility. That would be a nightmare -- you might have ten different properties, each with a different type that had a `name` member. It'd be impossible to figure out which type had the incompatible one.

**Comment by mohsen1** [comment]
I understand that the error has the information about the mismatched property. The error pointer is pointing to `obj` not `name`. Doesn't it make sense to point to `name`?

**Comment by RyanCavanaugh** [comment]
As strange as this sounds, we don't actually know which property is "to blame" in these kinds of situations.

The compiler works by determining the type of the right-hand side of the expression, then seeing if that type is assignable to the left-hand side. There's no mechanism that keeps track of where that type came from in terms of mapping the properties of that type to the initializations that produced it.

If you imagine a slightly different example:
```ts
var x = { location: { city: { name: 1  }}};
var obj: Person = x;
```
It's somewhat more obvious here that we 1) determine the type of x, 2) determine if that type is assignable to Person.

It's probably possible in theory to implement a better error message in the direct initialization case, but it's not feasible (in terms of performance/memory vs error message quality trade-off) in the indirect case to walk backwards to figure out which property is at fault.
