### ISSUE TITLE
error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.

### ISSUE THREAD

**Issue by virtyaluk** [microsoft/TypeScript#35316]
**TypeScript Version:**  3.7.2

**Search Terms:** Bitwise Shift Operators

**Code**

```ts
let res = 1 << '2';
```

**Expected behavior:**
I would have expected that Typescript compiles this source without any complaints, as Javascript follows the [next rule](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators) as of [ECMA-262 Specification](https://www.ecma-international.org/ecma-262/5.1/#sec-11.7.1):
> Shift operators convert their operands to thirty-two-bit integers and return a result of the same type as the left operand.

**Actual behavior:**
Typescript complains with the following error messages:

```
error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type. 
let res = 1 << '2';
               ~~~
```

**Comment by fatcerberus** [comment]
The JS spec allows a lot of coercions like this that TypeScript nonetheless prevents you from doing for safety's sake.  What if instead you did `1 << 'foo'`?  The JS runtime will coerce this and you would get garbage back--but *you wouldn't get a runtime error*.  This is why we have types--to catch this kind of mistake in advance.

See https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals, in particular:
> 1. Statically identify constructs that are likely to be errors.

```ts
declare let foo: number;
declare let bar: string;
let x = foo << bar;  // very likely to be a mistake!
```

If the code you posted compiled, then so would the above.

**Comment by nmain** [comment]
I think something like this question would be appropriate for the [FAQ](https://github.com/microsoft/TypeScript/wiki/FAQ)

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean
