### ISSUE TITLE
Accessing property on super should be a type error

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#35314]
**TypeScript Version:**  3.7.2

**Search Terms:**

typescript property access super undefined

**Code**

```ts
    class Base {
        n = 3
    }

    class Foo extends Base {
        test() {
            console.log(super.n) // type system says it should be a number, but it is undefined
        }
    }

    new Foo().test() // logs "undefined"
```

**Expected behavior:**

Should be some sort of type error, because clearly it is undefined

**Actual behavior:**

no error until runtime

**[Playground Link](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=1#code/AQ4YwGwQwZx4BCsCmwDeBYAUKXwB2wAvMAMza4C+2Foks8AYgPbPDIAeALsvgCbwkMVJhx4QPGFwAUASnS1xuMM3wxmEZADoIzAObSYAVwAOyAE5b88gPQ3gXAJ5ngMR1OQBbV1HfAAllyuABbMRhB8wABGqFAERp4x5gA00UZBgQHwRvzIAGb++Mh8injUYiDlpUUA7sAszHJakjK29rp68ABEOXz5hcVdQA)**

**Comment by fatcerberus** [comment]
This might be a design limitation - TypeScript can’t currently distinguish between prototype properties and own properties of a class type.  The type of `super` is `Base`, and `Base`-the-type has a property `n`, so the typechecker is satisfied.

**Comment by Jack-Works** [comment]
https://github.com/microsoft/TypeScript/pull/54056
