### ISSUE TITLE
[BUG] Detect decorators as a JSDoc tag inside @example block.

### ISSUE THREAD

**Issue by HamedFathi** [microsoft/TypeScript#35310]
**TypeScript Version:**  3.7.2

**Code**

```ts
/**
 * Component that creates log event objects based on raw inputs sent to 'ILogger'.
 *
 * To customize what data is sent to the sinks, replace the implementation for this interface with your own.
 *
 * @example
 *
 * @singleton
 * export class MyLogEventFactory {
 *   public createLogEvent(logger: ILogger, logLevel: LogLevel, message: string, optionalParams: unknown[]): ILogEvent {
 *     return {
 *       logLevel,
 *       optionalParams,
 *       toString() {
 *         return "aaa";
 *       }
 *     };
 *   }
 * }
 *
 * container.register(Registration.singleton(ILogEventFactory, MyLogEventFactory));
 */
export interface ILogEventFactory {
}
```

I want to get **JSDoc tags**, TS compiler detects `@singleton` as a tag but it is not. It is a decorator in the `@example` block.

**Expected behavior:**

Ignore decorators inside the `@example` block of JSDoc.

**Actual behavior:**

returns decorator as a tag!

**Comment by nmain** [comment]
There doesn't seem to be a formal specification for JSDoc syntax, so syntactically speaking, how would the compiler disambiguate this?

**Comment by HamedFathi** [comment]
We can use an escape character to ignore/avoid tag recognition by TS compiler.

For example: `\@singleton`

```ts
/**
 * Component that creates log event objects based on raw inputs sent to 'ILogger'.
 *
 * To customize what data is sent to the sinks, replace the implementation for this interface with your own.
 *
 * @example
 *
 * \@singleton
 * export class MyLogEventFactory {
 *   public createLogEvent(logger: ILogger, logLevel: LogLevel, message: string, optionalParams: unknown[]): ILogEvent {
 *     return {
 *       logLevel,
 *       optionalParams,
 *       toString() {
 *         return "aaa";
 *       }
 *     };
 *   }
 * }
 *
 * container.register(Registration.singleton(ILogEventFactory, MyLogEventFactory));
 */
export interface ILogEventFactory {
}
```

**Comment by dsherret** [comment]
@HamedFathi just looked into this and I believe this needs to be `&#64;singleton`? https://stackoverflow.com/a/53556016/188246

I found that works for me and displays properly in VS code.

**Comment by HamedFathi** [comment]
@dsherret 

Although, I prefer an escape character to a unicode value! just like my sample because It is more beautiful and readable but your suggestion is so good. Thanks.

**Comment by Frikki** [comment]
@HamedFathi and @RyanCavanaugh, I don’t see this working as intended.

<img width="872" alt="Screen Shot 2020-02-06 at 7 05 17 PM" src="https://user-images.githubusercontent.com/180569/73965075-c36b0b00-4913-11ea-9f50-d2b44be18a09.png">

**Comment by dsherret** [comment]
@Frikki it's not working for me anymore either in VS code 1.41.1, but I'm pretty sure it did before. I found it only works if I put that code in code blocks now.

Might be worth it to open an issue in the vscode repo, but I'm not 100% sure what the expected behaviour is.

**Comment by Frikki** [comment]
@dsherret Thanks for following up on this. I would expect that it should be possible to type `@` symbols in a code block even when it follows an `@example` block, without breaking the VSCode display.

**Comment by brokenmass** [comment]
@dsherret @Frikki : I'm having the same problem but i'm not able to get the `@` symbol to work properly in vscode (1.41.1).

```
/**
 * description
 *
 * ```ts
 * @singleton
 * export class MyClass {}
 * ```
 *
 * ```ts
 * &#64;singleton
 * export class MyClass {}
 * ```
 */
```

renders as:

```
*@singleton*  
export class MyClass {}
&#64;singleton
export class MyClass {}
```

**Comment by nicobrinkkemper** [comment]
Sorry for the +1, but this still seems to be an issue. I'm running in to it trying to add common custom html5 element code with Typescript.

Take the following example
```
/**
 * Decorator pattern to define custom elements
 *
 * @example
@defineCustomElement('app-rating')
class AppRating extends HTMLElement {

 * @param {string} name The name of the custom element
 */
```

As I see it right now, this forces developers to choose between two options:
1. Add a space before the @
         -> hovering over the function will not show proper color/code highlighting but will show the
2. Remove the @
         -> code shows proper highlighting, but doesn't show the @ obviously so it's technically a incorrect example

What I've tried: result
- Wrapping with ``` : shows the @ but does not show proper code highlighting
- Escape char with  \ , unintended space added and * signs added
- Adding `&#64;` will just print `&#64;` instead of `@`

**Comment by trusktr** [comment]
> &#64;

This is highly unreadable

**Comment by trusktr** [comment]
In case anyone missed it, https://github.com/microsoft/TypeScript/issues/47679 is open and hopefully will finally provide a solution.

**Comment by kasir-barati** [comment]
Ah, god when will this be fixed?
