### ISSUE TITLE
Importing from referenced project outDir does not work for subfolders.

### ISSUE THREAD

**Issue by VincentBailly** [microsoft/TypeScript#35328]
**TypeScript Version:**  3.8.0-dev.20191125

**Search Terms:**
- Intellisense
- project references
- import

**Code**
A minimal repro can be found here.
[https://github.com/VincentBailly/Ts37Bug](https://github.com/VincentBailly/Ts37Bug)
```ts
// works
export { a } from "aaaa/lib/foo"
// doesn't work
export { a as b } from "aaaa/lib/bar/foo"
```

**Expected behavior:**
Both imports should be resolved.

**Actual behavior:**
The tsserver does not manage to resolve the second import.

**Comment by VincentBailly** [comment]
@sheetalkamat FYI

**Comment by kenotron** [comment]
@VincentBailly is this related to:

```
{ a as b }
```

or 

```
"aaaa/lib/bar/foo"
```

?

**Comment by sheetalkamat** [comment]
Will take a look soon

**Comment by VincentBailly** [comment]
Tested the fix, it now works on our repo.
This feature enables a big optimization of our developer-experience.
Thanks a lot @sheetalkamat for implementing this great feature and for this fix.
