### ISSUE TITLE
Ambient public fields initialized in parent class are blocked at compile-time

### ISSUE THREAD

**Issue by robpalme** [microsoft/TypeScript#35327]
**TypeScript Version:**  3.8.0-dev.20191123

**Search Terms:** ambient declare public class fields parent initializer useDefineForClassFields 

**Code:**

```ts
// @useDefineForClassFields: true
class Parent {
    a: any;
    constructor(arg: any) {
        this.a = arg;
    }
}
class Child extends Parent {
    declare a: number;
    constructor(arg: number) {
        super(arg);
        console.log(this.a);  // Property 'a' is used before being assigned. (2565)
    }
}
```

**Expected behavior:**

There should be no compile-time error, because this is legitimate ES(next) code.  The intent of `declare <field>` is merely to specialize the type, not to impose additional initialization constraints. 

**Actual behavior:**

The usage of `this.a` causes the compiler error `Property 'a' is used before being assigned. (2565)`.

The emitted code is good.  The only problem is the compile-time error.

**Playground Link:**

- [Minimal repro](http://www.typescriptlang.org/play/?useDefineForClassFields=true&ts=3.8.0-dev.20191123&ssl=14&ssc=2&pln=2&pc=1#code/FAYwNghgzlAEAKEBOBTAdgF1gb2LfsEAXIWgJ4DceBIA9mlBkgK4ga1IAUyA5iROQCUOagQIYAFgEsoAOgiwAvISQ8qYgL7At4aHADC0sABNYKAB4Z0xuIlSYRY4yl2pCJNMwC2AIxRJ1GnpGFjYOblUPbz8kYVwxMShmAAd-CJ5BQITYOgZaMBRZMFoeTkkZeUzRWC0tIA)
- [Example from the 3.7 release announcement](http://www.typescriptlang.org/play/?useDefineForClassFields=true&ts=3.8.0-dev.20191123#code/JYOwLgpgTgZghgYwgAgIImAWzgG2Qb2Tg2xwGUwBXGGALiJAE9kBfAKFElkRQBEB7AObIIAD0ggAJgGc0JXAWSShFanQbN2bBDjjTZ6LLgAS-StJT42yG8igRpwSRHD1DpANzXbCfiGlgUJQIYPxQABTERjhu8jgAlATetrZgABbA0gB09o7O4MgAvAzRXinsWjp6sgKCpuYoYhIyctH1FkkpzlX2dg5OLmD0tV4A9KM2AHrTM5Ns48gA5LkD4IvIIPwA7shpekRL3br265j8ksAwwNAANPMTxJLIW36LYMgADlDnwSjEzGYwB9KO9fM4smxkshfP5AsFQhFlIJhkJElYUilpJQPtBwkj4mUMTZ0pkcv18mAskjVDQisgAEQBNT0jw2BYAGVAf0kzieoSUEDOsKgcEg9DSYCB0lo40EwHSlAARllfJhRphgAhvtJ+DAwKMACqMHFkLXAD76zJYhyjADMAFZbQAmADsUIqQA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/34972

The main use-case for ambient public fields is to specialize parent class fields.  It is common for parent class fields to only be initialized in the parent constructor, invoked via `super()`.  Due to this bug, this pattern does not work today, forcing the use of a workaround such as using `@ts-ignore` or redundant re-initialization of the property in the child constructor to appease the compiler.

cc: @sandersn

**Comment by fatcerberus** [comment]
Interestingly, the error is *correct*, but only because the emit is apparently *wrong*.  With `useDefineForClassFields: true` and `target: "esnext"`, the emitted code is:

```js
"use strict";
// @useDefineForClassFields: true
// @target: esnext
class Parent {
    a;
    constructor(arg) {
        this.a = arg;
    }
}
class Child extends Parent {
    a;
    constructor(arg) {
        super(arg);
        console.log(this.a); // Property 'a' is used before being assigned. (2565)
    }
}
new Child(3); // prints undefined
```

`Child#a` is not actually ambient.  With that emit, constructing a `Child` prints `undefined`, regardless of the value passed to the constructor.  It really *is* used before being assigned! 😄

**Comment by fatcerberus** [comment]
It seems the emit was fixed post-3.7, as the ambient field isn't emitted after switching the Playground to `Nightly` and the code then works correctly.  This does perhaps shed some light on how the error in question came to be, though.

**Comment by robpalme** [comment]
You're right @fatcerberus that the original issue https://github.com/microsoft/TypeScript/issues/34972 has now been fixed on master. Upon testing that fix I then discovered this compile-time error, so raised it here.

**Comment by fatcerberus** [comment]
It's just very interesting that the error message is correct for the original (incorrect) behavior.

**Comment by robpalme** [comment]
Good point.  I guess it's obvious in retrospect, because [the fix](https://github.com/microsoft/TypeScript/pull/35058) only changed [the transformer](https://github.com/microsoft/TypeScript/pull/35058/files#diff-c0d0e8b1528663b6cff3bb893150cec3).  There was no change to the checker.

**Comment by robpalme** [comment]
Thanks for scheduling this @RyanCavanaugh.

This feature (`declare` with class fields) was introduced in 3.7 and the showcase example code from [the 3.7 release announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#the-usedefineforclassfields-flag-and-the-declare-property-modifier) still [doesn't work](http://www.typescriptlang.org/play/?useDefineForClassFields=true&ts=3.8.0-dev.20191123#code/JYOwLgpgTgZghgYwgAgIImAWzgG2Qb2Tg2xwGUwBXGGALiJAE9kBfAKFElkRQBEB7AObIIAD0ggAJgGc0JXAWSShFanQbN2bBDjjTZ6LLgAS-StJT42yG8igRpwSRHD1DpANzXbCfiGlgUJQIYPxQABTERjhu8jgAlATetrZgABbA0gB09o7O4MgAvAzRXinsWjp6sgKCpuYoYhIyctH1FkkpzlX2dg5OLmD0tV4A9KM2AHrTM5Ns48gA5LkD4IvIIPwA7shpekRL3br265j8ksAwwNAANPMTxJLIW36LYMgADlDnwSjEzGYwB9KO9fM4smxkshfP5AsFQhFlIJhkJElYUilpJQPtBwkj4mUMTZ0pkcv18mAskjVDQisgAEQBNT0jw2BYAGVAf0kzieoSUEDOsKgcEg9DSYCB0lo40EwHSlAARllfJhRphgAhvtJ+DAwKMACqMHFkLXAD76zJYhyjADMAFZbQAmADsUIqQA) due to this issue.  It is currently scheduled for 3.8 - I wonder if this qualifies for patching 3.7?
