### ISSUE TITLE
Feature Request: Allow aliasing unions 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#3533]
If I need to repeat a union type in multiple places, it would be very nice to have an alias from that union type

For example, if I can assign 
```ts
interface AnyElementList = NodeList|[Node]|[Element]|Text
```

The above syntax is not something I recommend. I don't know what the best syntax would be but it would be nice if I can alias all those union types in one type and re-use it elsewhere

**Comment by JsonFreeman** [comment]
This is supported in 1.4 and above. The syntax is:
```ts
type AnyElementList = NodeList | Node[] | Element[] | Text;
```

**Comment by mohsen1** [comment]
Sweet! 
Thank Jason, I asked this question in Gitter a [couple of hours ago](https://gitter.im/Microsoft/TypeScript?at=5580ab70f207aa853a8bb4ac). You guys should hangout there more! :)

**Comment by danylaporte** [comment]
Is it possible to have a generic signature for the aliasing unions?

```js
type AnyElementList<T> = NodeList<T> | Node[] | Element[] | Text;
```

**Comment by DanielRosenwasser** [comment]
@danylaporte yup, that's slated for 1.6. See [our roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap).

**Comment by JsonFreeman** [comment]
Generic type aliases are actually checked in already. Feel free to try it out early if you like.

**Comment by danylaporte** [comment]
Nice! Thanks.
