### ISSUE TITLE
tsc -b  --watch emits unchanged js on each compilation round

### ISSUE THREAD

**Issue by IIIristraM** [microsoft/TypeScript#35340]
**TypeScript Version:**  3.7.2

**Search Terms:** project references

**Code**

```ts
tsc -b tsconfig.json --watch
```

**Expected behavior:** each recompilation write only changed js files to output

**Actual behavior:** each recompilation write all js files to output in all projects

As far as I understand, files should be written by `writeFileIfUpdated`, but it never invoked. Instead this function called

```js
function writeFile(fileName, data, writeByteOrderMark) {
    ts.perfLogger.logEvent("WriteFile: " + fileName);
    if (writeByteOrderMark) {
        data = byteOrderMarkIndicator + data;
    }
    var fd;
    try {
        fd = _fs.openSync(fileName, "w");
        _fs.writeSync(fd, data, undefined, "utf8");
    }
    finally {
        if (fd !== undefined) {
            _fs.closeSync(fd);
        }
    }
}
```

**Related Issues:** probably regression of https://github.com/microsoft/TypeScript/issues/29927

**Steps to reproduce:** 

- clone https://github.com/IIIristraM/lerna-ts.git
- run `npm run init`
- in first terminal run `npm run tsc:watch` and wait till build will be completed
- in second terminal run `npm start`
- change here https://github.com/IIIristraM/lerna-ts/blob/master/packages/common/src/utils.ts#L1 `number` to `any`, which should not lead to changes in corresponding js file 
- on each recompilation webpack build will print to stdout files that were changed, or you could just attach debugger to tsc process to see that all js files was emitted from scratch

**Comment by sheetalkamat** [comment]
This is working as intended.. We do not track if change in file will not result in its output js file or not. We emit it irrespectively.

**Comment by IIIristraM** [comment]
It's may be OK for this particular file, but all other js files among all projects are also emitted despite whether they depends on changed file or not. How it suppose to be integrated in any development pipeline which is usually watch changed files ?

**Comment by IIIristraM** [comment]
Just for history, webpack was triggers by setting timestamps on all output files during project invalidation step, so there is nothing wrong with emit.
