### ISSUE TITLE
Declaration file references global augmenting package

### ISSUE THREAD

**Issue by AviVahl** [microsoft/TypeScript#35343]
This issue came up as part of a real component library breaking for its consumers, demanding `@emotion/core`.

I was able to get a much smaller reproduction ready to show the behaviour.

**TypeScript Version:**  3.7.2 & 3.8.0-dev.20191125

**Search Terms:**
triple slash reference declaration

**Steps to reproduce**
clone https://github.com/AviVahl/ts-declaration-reference
`yarn`
`yarn build`

**Expected behavior:**
`dist/inferred-comp-export.d.ts` should not contain a reference to `@emotion/core`..

**Actual behavior:**
`dist/inferred-comp-export.d.ts` contains: `/// <reference types="@emotion/core" />`

**Playground Link:** 
Cannot reproduce in playground. It has to do with declaration emit and third party augmenting package.

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/34749
https://github.com/microsoft/TypeScript/issues/11849

**Observations:**
- `@emotion/core/types/index.d.ts` contains:
```ts
declare module 'react' {
  interface DOMAttributes<T> {
    css?: InterpolationWithTheme<any>
  }
}
```
commenting it out removes the triple slash from emit.
- commenting out `export * from '@emotion/core';` from `src/some-other-file.ts` gets rid of the triple slash reference.
- In our more-complex real case, we import `@storybook/react`, which imports `@storybook/theming`, which re-exports `@emotion/core`.

**Comment by weswigham** [comment]
Yeah, I'm going to file this as a bug - given
```ts
// @declaration: true
// @filename: node_modules/foo/index.d.ts
export = React;
declare namespace React {
    export interface Component<P={}> { }
}
// @filename: node_modules/bar/index.d.ts
import { Component } from 'foo';
declare module "foo" {
    export interface Component<P> {
        css?: P;
    }
}
// @filename: reexport.ts
export * from "bar";
// @filename: get.ts
import { Component } from 'foo';
export function getComp(): Component {
    return {} as any as Component;
}
// @filename: use.ts
import { getComp } from "./get";

export const obj = {
    comp: getComp()
};
```
we produce
```ts
/// <reference types="bar" />
export declare const obj: {
    comp: import("foo").Component<{}>;
};
```
for `use.ts`, while if `foo/index.d.ts` is just
```ts
export interface Component<P={}> { }
```
we produce
```ts
export declare const obj: {
    comp: import("foo").Component<{}>;
};
```

Clearly we don't always think the triple slash reference is needed, and at somepoint we're confusing an export-assigned-namespace with a referenced-augmentation or something.
