### ISSUE TITLE
Generic Record fails to infer dynamic property

### ISSUE THREAD

**Issue by Marsup** [microsoft/TypeScript#35354]
**TypeScript 3.7.2**
[Playground link](https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEBiD28A8ARewCuBbApgOwBcAaaAaWhwA8D8ATGCAgJwEs8BzAPmgG8AoaNGDw8jJhmAF4TABQAHVgDcwNaADMWOELQBcZAJS8AvnwHq8MsDoBKOYU1pJSRPNgBGOJp0M8Tgs2pgLCAy8HIEeqQ+ZoIEABYsEAB0ahY80ADaYQQAunoATNBG+gDcZiZmAO7SANYQoeGR0YKxCcmpMulZ4XnQhUbQkNC29o7O0K5YHl6l5XwmQA)

<details>
<summary>Compiler Options</summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```
</details>

**Input:**
```typescript
class Foo<Document, K extends string> {
  constructor(private field: K) {}

  fn(a:Record<K,number>) {}
  
  fail(opt: K) {
    this.fn({ [opt]: 2 });
  }

  works(opt: K) {
    this.fn({ [opt]: 2 } as Record<K, number>);
  }
}

```

**Output:**
```javascript
"use strict";
class Foo {
    constructor(field) {
        this.field = field;
    }
    fn(a) { }
    fail(opt) {
        this.fn({ [opt]: 2 });
    }
    works(opt) {
        this.fn({ [opt]: 2 });
    }
}

```

**Expected behavior:**
I would expect the `fail` function to compile, but it appears I have to force the parameter's type (like in `works` function). I can't determine if it's a compiler's bug or my mistake, all types seem correct and pretty straightforward to me, so if anyone has a clue about what's happening here, I'd be glad to have an explanation.

**Comment by fatcerberus** [comment]
It seems that TS infers a string index signature rather than `{ [x in K]: number }` like one would expect.  It knows that `opt :: K` yet goes ahead and uses its `string` constraint for the key type... hmm.

**Comment by RyanCavanaugh** [comment]
This is a correct error. You only have one key here, but `K` could be a union and you would be failing to produce a complete object. Here's an example that shows how to produce an unsoundness if this code were allowed:
```ts
class Foo<Document, K extends string> {
  constructor(private field: K) {}

  key!: K;
  fn(a: Record<K, number>) {
    return a[this.key];
  }

  setKey(value: K) {
    this.field = value;
  }

 
  fail(opt: K) {
    return this.fn({ [opt]: 2 });
  }

  works(opt: K) {
    this.fn({ [opt]: 2 } as Record<K, number>);
  }
}

const c = new Foo<any, "foo" | "bar">("foo");
c.setKey("bar");
const m = c.fail("foo");
// m: number, but is undefined
```

**Comment by Marsup** [comment]
Oh, thanks for the clarification, I understand now. This seems to be the case only if you enforce generic arguments to be different from what would naturally be inferred from the constructor without generic arguments then. I'll be fine with the forced cast, but out of curiosity, do you see a way to write such a pattern with soundness?
