### ISSUE TITLE
TypeChecker cannot work well with Printer in Compiler API

### ISSUE THREAD

**Issue by mohanson** [microsoft/TypeScript#35355]
**TypeScript Version:**  "typescript": "^3.5.3"

**Code**

/src/sandbox/main.ts

```ts
let a = "DDD";
```

/src/sandbox/test.ts

```ts
import ts from 'typescript'

const program = ts.createProgram(['/src/sandbox/main.ts'], {});
const checker = program.getTypeChecker();
const sources = program.getSourceFile('/src/sandbox/main.ts')!;
const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed
});
const r: string[] = [];
const tmpPath = '/tmp/main.ts'
const tmpFile = ts.createSourceFile(tmpPath, '', ts.ScriptTarget.Latest, false, ts.ScriptKind.TS);
sources.forEachChild(node => {
    r.push(printer.printNode(ts.EmitHint.Unspecified, node, tmpFile));
    r.push('\n');
});
console.log(checker)
console.log(r) // [ 'let a = ;', '\n', '', '\n' ]
```

**Expected behavior:**

prints `[ 'let a = "DDD";', '\n', '', '\n' ]`

**Actual behavior:**

prints `[ 'let a = ;', '\n', '', '\n' ]`

But if I delete `const checker = program.getTypeChecker();`, I can get the right results

**Comment by dsherret** [comment]
@mohanson that code is printing a node in one file (`sources`) with a different file (`tmpFile`). Doesn't really have to do with the type checker and also occurs if you create `sources` with the parent nodes set:

```ts
const sources = ts.createSourceFile('/src/sandbox/main.ts', `let a = "DDD";`, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
````

Basically, use `sources` instead of `tmpFile` to print the node:

```ts
r.push(printer.printNode(ts.EmitHint.Unspecified, node, sources));
```
