### ISSUE TITLE
Node.insertBefore has wrong typing

### ISSUE THREAD

**Issue by 71104** [microsoft/TypeScript#35358]
**Code**

```ts
document.body.insertBefore(null, document.createComment(''));
```

**Expected behavior:**

`tsc` should produce the following JavaScript even with `--strictNullChecks`:

```js
document.body.insertBefore(null, document.createComment(''));
```

That's because `null` is an acceptable value for the first argument of `Node.insertBefore`, as documented [here](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore). The type of the first argument should be something like `Node | null`.

Please note that this is an important use case because it's required to emulate `Node.insertAfter`, which doesn't exist.

**Actual behavior:**

```bash
$ tsc --strictNullChecks < index.ts 
index.ts:1:28 - error TS2345: Argument of type 'null' is not assignable to parameter of type 'Node'.

1 document.body.insertBefore(null, document.createComment(''));
                             ~~~~


Found 1 error.

```

**Comment by nmain** [comment]
`null` is not an acceptable value for the first argument of `Node.insertBefore`.  `document.body.insertBefore(null, document.createComment(''))` fails at runtime with a `TypeError`.  Are you sure you don't have your parameters backwards?

**Comment by 71104** [comment]
Gosh, the two parameters are indeed backwards: the nullable reference node is supposed to be the _second_ one.

Thanks nmain, I'll close the issue. sorry for the confusion.
