### ISSUE TITLE
Trailing comma in tuple after rest

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#35375]
**Search Terms:** Trailing comma tuple

**Code**

```ts
var [...x]: [...string[]] = [];
var [...x,]: [...string[]] = [];
var [...x]: [...string[],] = [];
```

**Actual/Expected behavior:**

Currently, the first line is valid, the second line is invalid because a rest element can't be followed by a trailing comma, and the third line is considered as valid by TypeScript.

I think that for symmetry with array and object rest elements, also rest elements in tuples shouldn't be allowed to have a trailing comma.
This behavior was likely introduced in https://github.com/microsoft/TypeScript/pull/28919, but since that PR doesn't mention rest types, probably it was an oversight.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=28#code/G4QwTgBA2gdHAeBdAXNOMDOAXMBLAdgOZSKIQC80iA3AFCiSwIA0Kac2eRJZlJdDdjCSommHAWKJWFKtSA)

**Related Issues:**

https://github.com/babel/babel/issues/10769 - If this is the expected behavior, we'll fix it in Babel. If instead, you think that this should be fixed in TypeScript, let me know because this should first be fixed in prettier to avoid a broken development workflow.

**Comment by RyanCavanaugh** [comment]
I think had we known at the time, this would have been disallowed, but I'm not thrilled about taking what is observably a breaking change with no apparent upside. It'd be better if Babel could just support it.

**Comment by nicolo-ribaudo** [comment]
Ok :+1:
