### ISSUE TITLE
Attribute Annotation

### ISSUE THREAD

**Issue by TiagoBraga39** [Microsoft/TypeScript#3537]
Why doens't typescript support Attribute Annotation?

For example, in C#, we could do something like:

Method 1:
---
Work around that may work. Not the best solution.

```cs
class Address {
...
     < Required ( Message = "Required street" ) > /* if no Message: defaults to "Required field." */
     private String street;
...
}
```
So, with that said: Why not try this in typescript?
My thoughts:

```javascript
import { Validator } from '<Typescript Validator Path>';

class Address extends Validator {
...
     < Required ( Message = "Required street" ) > /* if no Message: defaults to "Required field." */
     private String street;
...
}


abstract class Validator {

	/* annotatedProperties pseudoCode */

	isValid(): boolean {
		var errors : Map<Property, List<Errors>> = new HashMap<>();
		foreach(property in annotatedProperties) {
			var propertyErrors = new List<>();
			foreach(validation in property) {
				if(!isValid(property, validation)) {
					propertyErrors.add(validation.Message);
				}

			}
			errors.put(property, propertyErrors);
		}

		return errors;
	}

	isValid(property: string) {
		var propertyErrors = new List<>();
		foreach(validation in property) {
			if(!isValid(property, validation)) {
				propertyErrors.add(validation.Message);
			}

		}
		return propertyErrors;
	}

}

```

Method 2:
---
Every class has a list of properties, and every property has a list of validators:

![capturar](https://cloud.githubusercontent.com/assets/8090726/8208012/fd368f9e-14fc-11e5-8968-d8a840b81836.PNG)

**Comment by DanielRosenwasser** [comment]
I think you might be interested in [TypeScript 1.5's upcoming decorators](https://github.com/Microsoft/TypeScript/issues/2249) - see [our roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap).

**Comment by danquirk** [comment]
As mentioned, this is essentially decorators.

**Comment by TiagoBraga39** [comment]
Oh I couldn't find anything...
Thank you both :)
