### ISSUE TITLE
Anonymous function that may or may not be called should affect possible values of a variable

### ISSUE THREAD

**Issue by mmorearty** [microsoft/TypeScript#35381]
**TypeScript Version:**  3.8.0-dev.20191126

**Search Terms:**
lambda type
anonymous type
lambda union
anonymous union

**Code**

```ts
// compile with --strictNullChecks

function foo(entries: string[]) {
    let s: string | null = null;

    entries.forEach(() => s = "hello");

    const s2: null = s;  // should fail to compile
}
```

**Expected behavior:**
Should fail to compile. If `entries` has at least one string in it, then `s` will end up being assigned a string, so you cannot assign it to s2, which is of type `null`.

**Actual behavior:**
Compiles without error.

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=Nightly#code/GYVwdgxgLglg9mABMOcAUBTMUBOMMDOAXIgbjGAOYDaAugJSIDeAUIu4gDYZSkll4qiAD6IwITp0QBeMRM4BuFmw5ZyhAHQocAUQCGEABZo0jaQD5SMxACJDGSXBv0lK9hARlSAJhLjJ1gQK7AD0IaSGcBIAJsh6MFJQcIgeALYADgkYLAC+LEA

**Comment by AnyhowStep** [comment]
Related #9998

**Comment by mmorearty** [comment]
Thanks for the link, @AnyhowStep — that's helpful.

Obviously my example above is very contrived — perhaps too contrived to be useful. Here is another example which is a little bit closer to my original code — and unlike the above behavior, the following one has differs between TypeScript 3.7 and 3.6. I didn't file it as an issue because I am hard-pressed to find a "bug" in the change in behavior; but certainly some sort of backwards-incompatible change was made:

```ts
namespace Maybe {
    export type Maybe<T> = void | null | undefined | T;

    export type NoneT = void | null;
    export const NONE: NoneT = null;

    export const isSome = <T>(m: Maybe<T>): m is T => {
        return typeof m !== "undefined" && m !== null;
    };

    export const valueOrElse = <T, U extends T>(m: Maybe<T>, orElse: () => U): T => {
        return isSome(m) ? m : orElse();
    };

    export const valueOrThrow = <T>(m: Maybe<T>): T => {
        return valueOrElse(m, () => {
            throw new Error();
        });
    };
}

function foo(entries: string[]): string {
    let s: Maybe.Maybe<string> = Maybe.NONE;
    entries.forEach(() => s = "hello");
    return Maybe.valueOrThrow(s);
}
```

Here is the [playground link](https://www.typescriptlang.org/play/?ssl=13&ssc=1&pln=14&pc=1#code/HYQwtgpgzgDiDGEAEBZEBPARsg3gKCUKQgA8YB7AJwBclr0Zk0sIAeAFQD4kBeJAN3IBLACZIAPkmABXADayJSacBEQAZkOAQxk9gG48BIqQo06DZADlyW9rwHCdUubINFiZKrXg2otSwDylgCiAFxI1rb2MvIGRoQmXkg+wH5IQlAAyuSQ9hycABRg4czY+QCU4WDpUEh2PNz47u6UENTSlMDmjORqSNUAhDx8AETKqhpaIiNIAGSz-UhDfDGu8UgAvnHuiWYpafwgstIQAZTBslDIfBwANEgAqh7UECq1XEUlGGVc91QXV3CBXKvG4D0qdVBSCazUIrXanRq2UgRRBAH5FuF-pcIMC3EQtoYdp49r5aIdjqdKOwABaUcgAdzyH2KqG+bC4EPqjXWLTaHS6FJOZwBuLA92BUJhsPc1DpjKkECZwUo9MoeN5BPK+MIhI2hjUyng1CENiQanI5AKr2olCE0HCfjtwAA5gBtAC6EKdmhd0PWsjaSCgXxYADpSmwfa7uHxI2HAiEdcRgLb7VAwxbzggaQVJQ1g-YRjSIPJyCNtet4QK2eGhVTafSGQUoJWNkA) for that code.

In 3.6, it compiles without error. In 3.7, you get an error.

The difference seems to be related to the type of variable `s` when we reach the end of the function. In 3.6 in the playground, if you hover over `valueOrThrow` in the last line, you can see that the call is to `Maybe.valueOrThrow<string>()`; in 3.7, it is to `Maybe.valueOrThrow<Maybe.NoneT>()`.

**Comment by MartinJohns** [comment]
The issue still is #9998. The compiler does not recognize your mutation of `s` inside the callback, so the type of `s` is still `Maybe.NoneT` when it comes to your `valueOrThrow()` call.

Not sure about the difference between 3.6 and 3.7. `s` is still inferred to be `Maybe.NoneT` in 3.6.3, so I would guess that your (unsupported) code got affected by an unrelated change.

There's #11498 to change this behavior for immediately-invoked functions (such as `forEach`).
