### ISSUE TITLE
Type inference of nested if/switch statement no accurate enough.

### ISSUE THREAD

**Issue by vczh** [microsoft/TypeScript#35380]
**TypeScript Version:**  3.7.2

**Search Terms:** "Type inference of nested if/switch statement no accurate enough."

**Code**

```ts
function one(x: 1): number { return x; }
function two(x: 2): number { return x; }
function fake<T extends number>() { return <T>0; }

const a = fake<1 | 2>();
const b = fake<1 | 2>();

if (a === b) {
    if (a === 1) {
        one(b);
    } else {
        two(b);
    }
}
```

**Expected behavior:** Should compile

**Actual behavior:**

on two function calls, both have similar errors
```
Argument of type '1 | 2' is not assignable to parameter of type '1'.
  Type '2' is not assignable to type '1'.(2345)
```

**Playground Link:** N/A

**Related Issues:** Not found

**Comment by fatcerberus** [comment]
The type guard of `a` can't affect the type of `b`.  TypeScript doesn't track what narrowing one variable means for others.  See for example https://github.com/microsoft/TypeScript/issues/12184 (among many, many others)
