### ISSUE TITLE
PartialBy type

### ISSUE THREAD

**Issue by Luifr** [microsoft/TypeScript#35386]
type PartialBy<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>

```
interface Todo {
    id: string;
    text: string;
    creationDate: string;
}

let todo: PartialBy<Todo, 'text'>
// {
//     id
//     text?
//     creationDate
// }
```

**Comment by samal84** [comment]
Seems to be from here:
https://stackoverflow.com/a/54178819/628418

This would be nice to have built in.
