### ISSUE TITLE
Run terminal command after emit with tsc CLI 

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#35398]
In order to apply a post-processing step to typescript files, such as path resolution or migrating files from source directories, it would be useful to have access to a post-emit hook.

```
tsc -w --post-emit="ls dist"
```

This would run `ls dist` every time the compiler emits on watch mode.

**Comment by RyanCavanaugh** [comment]
This is outside the scope of things we want TS to be responsible for
