### ISSUE TITLE
Regression 3.7.2 : Build with Project References ignore prepend: false when compileonsave is true and outfile

### ISSUE THREAD

**Issue by Outlivier** [microsoft/TypeScript#35393]
**Search Terms:** Project references prepend composite

**Description**

In Visual Studio 2019, with nuget package `Microsoft.TypeScript.MSBuild.3.7.2`, and `<TypeScriptBuildMode>true</TypeScriptBuildMode>` in .csproj file, with the following structure :

```
FolderA
    A.ts
    tsconfig.json
FolderB
    B.ts
    tsconfig.json
```
* A.ts

```ts
let a: number = 15;
```

* FolderA\tsconfig.json

```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"noImplicitAny": false,
		"noEmitOnError": true,
		"removeComments": false,
		"sourceMap": true,
		"target": "es5",
		"composite": true,
		"declarationMap": true,
		"declaration": true,
		"outFile": "../file-a.js"
	},
	"exclude": [
		"node_modules",
		"wwwroot"
	]
}
```

* B.ts

```ts
let b: number = a + 15;
```

* FolderB\tsconfig.json

```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"noImplicitAny": false,
		"noEmitOnError": true,
		"removeComments": false,
		"sourceMap": true,
		"target": "es5",
		"composite": true,
		"declarationMap": true,
		"declaration": true,
		"outFile": "../file-b.js"
	},
	"exclude": [
		"node_modules",
		"wwwroot"
	],
	"references": [
		{ "path": "../FolderA/tsconfig.json", "prepend":  false }
	]
}
```

**Expected behavior:**

When Modifing File B.ts, after saving, the output of file-b.js should be 

```js
var b = a + 15;
```

**Actual behavior:**

The output of FolderA is prepend in file-b.js :

```js
var a = 15;
var b = a + 15;
```

This behavior doesn't happen if 
* TypeScript version is 3.6.4 instead of 3.7.2.
* CompileOnSave is false, and we build the project after modifing files.

**Comment by sheetalkamat** [comment]
This is fixed by #35335
