### ISSUE TITLE
Bad line endings in src/compiler/program.ts

### ISSUE THREAD

**Issue by colbyrussell** [Microsoft/TypeScript#3540]
The repo uses DOS-style line endings, but there are two lines in program.ts that don't follow the convention.  It's causing VIM to choke on the file.

![line-endings](https://cloud.githubusercontent.com/assets/10376674/8214966/9348ef64-14f2-11e5-8387-5d9efeb7bc19.png)

**Comment by mhegazy** [comment]
Thanks @colbyrussell !

**Comment by DanielRosenwasser** [comment]
Hey @colbyrussell what Vim extension do you use for TypeScript?

**Comment by colbyrussell** [comment]
I'm "using" [typescript-tools.vim](https://github.com/clausreinke/typescript-tools.vim) as of Friday afternoon, but then, not really.  I tried [typescript.vim](https://github.com/leafgarland/typescript-vim) a couple of weeks ago, but disabled it because it's kind of a mess like almost everything surrounding the current Vim plugin ecosystem.  Right now I'm just working blind/raw with no language support.  (The screenshot above is just showing the default JS syntax highlighting enabled, `set filetype=javascript`.)

I'm going to work a bit on tooling, starting with typescript-tools.vim and its documentation.  It looks like a fairly clean base to start with, and (most importantly) its maintainer seems to have the things to look for in a serious collaborator.  It's still in want of some help and kind of rough around the edges right now, though.

PS: Microsoft (and for that matter, everyone else, I guess) should put some support behind [Neovim](http://neovim.io/).  Want to have a go at convincing somebody of this?

**Comment by DanielRosenwasser** [comment]
Consider looking at @Quramy's [Tsuquyomi](https://github.com/Quramy/tsuquyomi) plugin as well. It looks pretty solid, the code looks clean, and uses the same server backend that our Sublime plugin does (TSServer). Also, thanks to @icholy, [YouCompleteMe](https://github.com/Valloric/YouCompleteMe)'s server [ycmd](https://github.com/Valloric/ycmd) just added support for TSServer and my understanding is that they're planning to document it as soon as 1.5 comes out.

> PS: Microsoft (and for that matter, everyone else, I guess) should put some support behind Neovim. Want to have a go at convincing somebody of this?

In my opinion, NeoVim is doing some exciting and well-deserved work for the Vim community. I can't make any guarantees about anyone primarily working on Neovim, but we on the TypeScript team are more than happy to help integrate our language service with their plugin model if users could be better served by that experience.
