### ISSUE TITLE
SubtleCrypto wrapKey() and unwrapKey() algorithm type is too abstract

### ISSUE THREAD

**Issue by jiripudil** [microsoft/TypeScript#35408]
**TypeScript Version:**  3.7.2

**Code**

```ts
const privateKey = await window.crypto.subtle.unwrapKey(
	'pkcs8',
	wrappedPrivateKey,
	wrappingKey,
	{name: 'AES-KW'},
	{name: 'RSA-OAEP', hash: 'SHA-512'}, // <-- error there
	false,
	['decrypt', 'sign']
);
```

**Expected behavior:**

The code compiles.

**Actual behavior:**

```
Error:(35, 22) TS2345: Argument of type '{ name: string; hash: string; }' is not assignable to parameter of type 'AlgorithmIdentifier'.
  Object literal may only specify known properties, and 'hash' does not exist in type 'Algorithm'.
```

The types in `wrapKey()` and `unwrapKey()` should be updated to match the respective types in the underlying operations (`decrypt` + `importKey` / `encrypt` + `exportKey`). I'm just opening the issue for reference, fix is on the way 😉

**Comment by mizvyt** [comment]
Temporary workaround for my project:
```
interface WrapKeyParams extends Algorithm {
    iv: Uint8Array;
}

<...>

const wrapParams: WrapKeyParams = {name: 'AES-GCM', iv: iv};
const wrapPromise = this.subtleCrypto.wrapKey(
    'jwk',
    keyToWrap,
    key,
    wrapParams
);
```

**Comment by mizvyt** [comment]
+1. Just had an issue with `wrapKey` not letting me specify an `iv` for AES-GCM encryption. In the MDN docs, you can find an example that shows an example of the correct usage (https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/wrapKey), but I guess the TypeScript definitions were not updated.

Temporary workaround for my project:
```
interface WrapKeyParams extends Algorithm {
    iv: Uint8Array;
}

<...>

const wrapParams: WrapKeyParams = {name: 'AES-GCM', iv: iv};
const wrapPromise = this.subtleCrypto.wrapKey(
    'jwk',
    keyToWrap,
    key,
    wrapParams
);
```
