### ISSUE TITLE
Add type support for KaiOS

### ISSUE THREAD

**Issue by zlk89** [microsoft/TypeScript#35402]
## Search Terms
kaios, firefox os

## Suggestion

Add type support for KaiOS, which is an emerging OS. KaiOS has been the second largest OS in India and continue growing.

## Use Cases

Add type support for KaiOS, such that we can get type check on some extension methods.
We can add this as a separate package like `@types/kaios`.

## Examples

All methods listed in https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/Navigator are specific to Firefox OS/KaiOS.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
> We can add this as a separate package like @types/kaios.

You wanna go over here: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by farooqkz** [comment]
What is status of this?
