### ISSUE TITLE
Multiple generic functions in interface TypeScript

### ISSUE THREAD

**Issue by lopatnov** [microsoft/TypeScript#35400]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** multiple generic functions in interface TypeScript

**Code**

```ts
export interface Func<TResult> {
    (): TResult;
    <T>(arg0: T):TResult;
    <T1,T2>(arg0: T1,arg1: T2):TResult;
    <T1,T2,T3>(arg0: T1,arg1: T2,arg2: T3):TResult;
    <T1,T2,T3,T4>(arg0: T1,arg1: T2,arg2: T3,arg3: T4):TResult;
    <T1,T2,T3,T4,T5>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5):TResult;
    <T1,T2,T3,T4,T5,T6>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6):TResult;
    <T1,T2,T3,T4,T5,T6,T7>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9,arg9: T10):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9,arg9: T10,arg10: T11):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9,arg9: T10,arg10: T11,arg11: T12):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9,arg9: T10,arg10: T11,arg11: T12,arg12: T13):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9,arg9: T10,arg10: T11,arg11: T12,arg12: T13,arg13: T14):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9,arg9: T10,arg10: T11,arg11: T12,arg12: T13,arg13: T14,arg14: T15):TResult;
    <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16>(arg0: T1,arg1: T2,arg2: T3,arg3: T4,arg4: T5,arg5: T6,arg6: T7,arg7: T8,arg8: T9,arg9: T10,arg10: T11,arg11: T12,arg12: T13,arg13: T14,arg14: T15,arg15: T16):TResult;
}

function showMessage<T>(f: Func<T>): T {
    console.log('Executing...');
    console.log(f());
    console.log(f('Hello'));
    console.log(f('Hello', 'World'));
    return f('Hello', 'World');
}

showMessage(() => {
    console.log('No params');
    return 0;
});

showMessage((arg0: any) => {//Error there: Argument of type '(arg0: any) => any' is not assignable to parameter of type 'Func<any>'.(2345)
    return arg0;
});
```

**Expected behavior:** No error, this code is valid.
The interface `Func<TResult>` contains a line:
```ts
<T>(arg0: T):TResult;
```
so this method is correct for the interface:
```ts
(arg0: any) => {
    return arg0;
}
```

**Actual behavior:** The error: "Argument of type '(arg0: any) => any' is not assignable to parameter of type 'Func<any>'.(2345)"

**Playground Link:** http://www.typescriptlang.org/play/?ts=Nightly#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQFclsAeAFQCVgBnQgGxgD44BvAKDi7gAoBKAFxwqtBjADcnbhSY9MUAOYAGIeUEi6jSdzgUAjABpyAJlnzlqw+b2rj66polSu+o8aMBmM4pXCrim2F3c2NVD3tRLWddckMTTyMAFm8LPwNrW3TFUOEPLIUPVUSIx21pWLcE8kSjAFYU3wqMoPyc8jzzQuEa80TVWpKxMpcK+PakuqMANgbLfMD4kLD8rur8vuFa-NrVKcGonVcxvLXyLfIpowB2WbTmxezlzqL1-u3d-KnVK-2nQ9H3ONTudLuQrkYABy3JoBTJLXIrF69N7mHbCS7mL7CcHmK6qCG-YYxOKAk41M7Ta6QowATmh-gUC2CjwRz26r0273Rn2++Txwgh+QhqhphOiR1JEwpFyp5EF5BpRj0Snp8zhLPGbLWyM5qI+mN5uPxQpF+RpliUYv+JKq5JBsvlitiSiVelV92ZCjaHUUqx6ig2FL13IN2L5xvMwuEivM5r8LusjT0eit5RtQLtlLB1IVSpdsTielMch8cw9rSevqRAZRijRMtD2aNApN0bNFvmSYZycsdgEGiG4oBtsmMuzctpeddSsBei8JdSMMZ6q9lYK1YUga2wYbiixTcU-InkdNsY7ics3YWRfmbTnqZG6bJo9B4Inued09is5OemSC6TNUWnhTUq3ZHUgzrfU90NQ8I0UKNczPeNO0veZr09ItLB9RlVj-B9iUqDMXwdSdPwLGclV-ck9HqACy1hYCNRwv0OUghR6wxGCw2bY8ENPRQ40-C8-CvXtb2w+Y8P9RlA1ogiJRHaVXxzJ1lS-G9YmopVzj0GZ6LuRiHlXVkwO1GtdSgkNuIPBQj0FE822Q4SAi7dDxOsO8cLnSwZL-SxtwCes9LFABfdh2HQYhsBgBAICQOAaAACwgAB3ABZWgaEwBRgBkHh0CEIgSBkQRhDYaJsHimgIHoYAADp6AgBQeAAcgAURAYBsEIWKkAUerBtavgiSqpAarqxrmoK-gRsq6raoapqWvQNqAAlgHoJrhrmnQxompbptW1qNq2iBWoMOBWoAdWgegABMdqJKBgBgQgoAS47Tu2y6brux65vC9hkrSzKaGy3KeH4OAAF4WA4PaFsm5a2oAOQgOAwHkTAAFsaGG57XvehKlEkUK5uBlKMqynLgCh8xfEwJAAE8+Fh+GAHoOfaqAoGgOAYCStBgCEABBRRCBx4AUDgCB0AF5mwDwVqDKZ1n2bgNXWsQGg4CQCB4EwcGEAUJBMAAIzqgWMaxqBcdetBZflmBFeV4qyDVphWvqnhjA8RIBmiF63o+zWfDJkagA

**Related Issues:** no

**Comment by weswigham** [comment]
You want a union type, not overloads. Overloads require that something that implements them handle all possible overloads (simultaneously).

**Comment by lopatnov** [comment]
Maybe this sample will be more clear:
```ts

export interface Func {
    <TResult>(): TResult;
    <T, TResult>(arg0: T):TResult;    
}

function showMessage1(f: Func) {    
    return f();
}

function showMessage2(f: Func) {    
    return f('Hello');
}

function showMessage3(f: Func, arg: string) {    
    return f(arg);
}

var x = showMessage1(() => 5);
var y = showMessage2(() => 'It is ok');
var z = showMessage3((arg: string) => arg, 'It should pass'); // but error there

/* In the interface Func
the line <T, TResult>(arg0: T):TResult; 
fits to (arg: string) => arg
where T = string; TResult = string
*/
```

Link: http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20191126&ssl=2&ssc=1&pln=27&pc=3#code/FAUwHgDg9gTgLgAgJYDs4hgMwIYGMQIBiArirggN7AI0IA8AKgEogDOxANnAHwAUAlAC4EzNpzgBuarUYAaES3Zc+2GAHMADMIZDRSybQTAAvsGCZSuOEigoErABZQA7gFk2rbGpABGXpmESMn5KQ2kaGBA4Yhg7TAEpU3NLa1t7JzcPLxAAJn9AyxCKMMNI6NiEeIByAAkQDg4oKv5EswsyVLtHF3dWT28AZnyiS3lVNWFWOBhUNSKS2jKYuN5xlpMzADdVBDAEAF50nqzvPwED7gQAVnXtmAQATwOjzL7svPP9y6qASUQkVgIKAAa2aUjuCAAXs9uq9+iAhqt1JNprMQl8EON5L9EN1OAATBAQbB9MEIAD05IQACNiIgMDBYAg4A4MCAzOSAFQIH52FkEVDoLB4AhBXDAfkIDioAhyBRiZRIzTaXSKcQSIyYJBwQFwKAIJUomYoOYXTHqYDOVmREQw1EmjV6cR241qYCc8lAA

**Comment by lopatnov** [comment]
Without generics I can reproduce the same error:
```ts
//Without 3 or 4 line one of errors disappears
interface Rge {
  (pattern: RegExp): number;
  (pattern: string, flags: string): number;
}

function tst(r: Rge) {
  //there a logic that uses Rge function. It 100% recognizes when 1 parameter and when 2.
 }

// Argument of type '(a: string, b: string) => number' is not assignable to parameter of type 'Rge'.
tst((a: string,b:string) => { 
  return 0;
});

/*
Argument of type '(pattern: RegExp) => number' is not assignable to parameter of type 'Rge'.
  Types of parameters 'pattern' and 'pattern' are incompatible.
    Type 'string' is not assignable to type 'RegExp'.(2345)
 */
tst((pattern: RegExp) => {
  return 1;
});
```
Link: http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20191126&ssl=1&ssc=1&pln=23&pc=4#code/PTDqEsBcAsHsFdIAIDMTYCckBYkBtwA7AU3RPQDMliMNMBnJAE3HoEMAHD4tjegKCKQaFNgGNSAJQDmpAN78kSABQc2kYRkIAuJJOLSAogA8OASl2F4AWwBGNANyKVajTR1J6kDEWkAaJAo8Nml6XS8fQmkLJCs7R34AX35+CnhCMUhwWEIkSC9lDF0ZYjMkBSUQGBpSNnxYaXAxPOh1JHh6YkYSwPTM7MIAOiQASWQARgAGSYBSJAxiMQbCcAAvLqQAd2hiXPGkNQw2a2JNJDZCJi2d3IAmQcVk-hAkAEEMaRtd5FgqSABPbhIADkyjY4W8vgCtghkWiSAAvAA+WI2ewYYFIVixWDINj0ejgaSENi2PCkSCwA68Y6nGiUPKA0jAkrAh75SDKMGwqEwiK+MrI8pIZwLSDwLRISZORJmJzPABU-HenxOhB+fyZINU6k0Hn0RlMgpRcXRmOxhFx5wJRJJZIpVMOtLOv0ZQJZsjZzgAKkzGK6nSdNIxga49ZiLldQ7r3BGFliMrBrK5wPaHkolL73fyoubGJa8TbiaTyXkqQD3QaTBw2cpbihsABWMyKBXAfgcrlh9zFAzV43lUWnCV7GVyoA

It's simplified construction of: https://mariusschulz.com/blog/typing-functions-in-typescript#object-type-literals-with-call-or-construct-signatures

**Comment by lopatnov** [comment]
I understand when there are multiple function choices in interface and it's a problem, what function to choose, but it these example there is a single answer for each interface. And these errors shows incorrect comparsion.

**Comment by weswigham** [comment]
You want to write, eg `type Rge = ((pattern: RegExp) => number) | ((pattern: string, flags: string) => number);` then, as I said. You want to provide a function that satisfies only one if the two signatures - that's the correct way to construct a type that accomplishes that.

**Comment by lopatnov** [comment]
Ok, if I can write:
```ts
var args: any[] = [];

function test1<T, TResult>(f: ((() => TResult) | ((arg0: T) => TResult))): TResult {
  /* Argument of type '10' is not assignable to parameter of type 'T'.
  '10' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.(2345) */
  //return f(10);

  /*Argument of type 'never[]' is not assignable to parameter of type 'T'.
  'never[]' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.(2345) */
  //return f([]);

  /*Argument of type '{}' is not assignable to parameter of type 'T'.
  '{}' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'. */
  //return f({});

  /* Expected 1 arguments, but got 0. */
  //return f();

  /* The 'this' context of type '(() => TResult) | ((arg0: T) => TResult)' is not assignable to method's 'this' of type '(this: {}) => TResult'.
  Type '(arg0: T) => TResult' is not assignable to type '(this: {}) => TResult'. */
  //return f.apply({}, args);

  /* The 'this' context of type '(() => TResult) | ((arg0: T) => TResult)' is not assignable to method's 'this' of type '(this: {}) => TResult'.
  Type '(arg0: T) => TResult' is not assignable to type '(this: {}) => TResult'. */
  //return f.call({});

  /* Expected 1 arguments, but got 2. */
  //return f.call({}, 5);

  return (f as () => TResult)();
}

test1(() => {
  return 5;
});

 test1((param: number) => {
  return param;
 });
```

Why I can't write so:
```ts
interface Incorrect<T, TResult> {
  (((): TResult) | ((arg0: T): TResult));
}
```

or so:

```ts
interface Incorrect<T, TResult> {
  ((() => TResult) | ((arg0: T) => TResult));
}
```
?

**Comment by lopatnov** [comment]
If I can write:

```ts
interface CorrectSingleFunc1<TResult> {
  (): TResult;
}

function test2<TR>(i: CorrectSingleFunc1<TR>): TR {
  return i();
}

test2(function () { 
  return 5;
});
```

and

```ts
interface CorrectSingleFunc3<T, TResult> {
  (arg0: T): TResult;
}

function test6<T,TR>(i: CorrectSingleFunc3<T, TR>): TR {
  return i(getT(10));
}

test6<number, number>(function (arg: number) {
  return arg;
});

test6(function (arg: number) {
  return arg;
});
```

why I can't write

```ts
interface CorrectSingleFunc2<TResult> {
  <T>(arg0: T): TResult;
}

function getT<T>(some: any): T {
  return some;
}

function test3<T,TR>(i: CorrectSingleFunc2<TR>): TR {
  return i<T>(getT(10));
}

test3<number, number>(function (arg: number) { // error there
  return arg;
});
```
?
The type T is exactly number.

**Comment by lopatnov** [comment]
if test2 and test6 are correct and

```ts
interface ExtendedOfOthers<T, TResult> extends CorrectSingleFunc1<TResult>, CorrectSingleFunc3<T, TResult> {

}

function test4<TR>(i: ExtendedOfOthers<number, TR>): TR {
  return i();
}

test4(function () { 
  return 5;
});

```
correct, but why test5 is incorrect?
```ts
function test5<T,TR>(i: ExtendedOfOthers<T, TR>): TR {
  return i(getT(10));
}

test5<number, number>(function (arg: number) { //error here
  return arg;
});

test5(function (arg: number) { //error here
  return arg;
});

```
It's (test5) the same as test6. The ExtendedOfOthers interface extends CorrectSingleFunc1 and CorrectSingleFunc3. So for single tests they are correct, but for interface that extends both - incorrect. All generic parameters are in the interface unlike previous example, where CorrectSingleFunc2 has T type as a generic function.

Link: http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20191126&ssl=106&ssc=1&pln=117&pc=1#code/G4QwTgBODmDOBcUB2BPA2gXQgXgpg3AFCEBmArkgMYAuAlgPZITUCms1AjADwAqANBB4AlNmQA21AHwAKEomkKAlDkmCRscdWUAfCApgAGRD2XZVw0RMXXj6zRADehCBAD0AKggBBMNDIBbFiRqCHoSZhQABxYIAHIOA1iIWlgIJHoQkFhYWmgkEAAjMRjqeghI8BBA1kgwiOi4nliAOmc4hKSUqGzc-KKSsuoACxjKRnYwEFpg0PDqKJjYpoECshClpLHxABMIApjp9hBg2hBWXYB3WmGoCG3aEhIWMCCQjQL5hrqxpAmpmdiDgAvi1pAAmADMABYAKzKdyuNquVwvahkMBMEjSBKKIhI9w+PyBGZ1T6LJAsYDPTCdVLpTI9PKFYrMMoVSbVZ6zeqLJqtFyxClUsA05KpLI5Jn9VnMEYQH5-aYhUkLRqxFZrNXy+g7PYHX7UY50M4sS7XIa3e6PZ6vCDvMnchXUSZKuLA0GQ2HwxEuZGo9GY6SYXHEX0E3wBW0qhqAkFitIZbqSvos0rlSqc2pzVUbfluuNdCW9ZkDWWjcbO-7K7Mx5Z7TUbbW6-bJA1G07nCBXG4gO4PJ4vGb21XfCsugHu5oQBFIlEsNEYiBY4Eh-EQACiAA9ojRTRAOFAI8TqLANSFoImDFOZ765wvA6uw4I5bFhilNoxWJvqzy4koVGolhaBAuj6L4RiCKY5h2FYtIJgyyYljK1RDPQ2yxKkr5DO+3IOrE0hvggjhAlBgEaBILRtDwObSIYxikRY5HUHB9JJsW0ppnhBHYURK4AYxmgtNOPpuHeAZLs0ICRJEYgoNIwICDAsCPm4ng8C+hEfsELDfrhNHSAxMHAaBtHgfR-FGYoLGJkWUqpmUKFoRhcSaXpMbcSkiB8WYZGCXm1HuXRkEWUB1kIex9m-vhhFeSRIVMUJN6if6i4kM0lAgGIYjySReJPluO6dgeMCRsEp71ueiZgteIl+vO4lpRlWU5QIcJ5RAKVMLI3R6IZQGKAZRBAsQrDsBw-4+U4LidRAMJDY+o2cAo7JVIgSABPsYCkVNHX1YuK3+EQEC5cQhAeBAADCmViHaxYLiwAgXNhlAWmIICUAA1qknUALQOsc9JnAwSACLQ-gybQlDXLJEBDFkyBxMcKBJDNZI1WdnheDQZDXSgEAAJJ2iwJRwyELxMV2tBZXqvkSCBtPUFOtDNCwU64AJdPw9MzBsJwS4UDQwPCRjhBKs8JDvTE+NUPQYAvDQvACBzUiOG0CgGbY-X02B0AQSYmtMdYQ2EDOovaWAEuUDEF2y-L1AAMrTNAxQAGIC9wyuqDtGsM8bpAC3QjA8+wYK8EIMi0IgNtyywNCO0gzssG7VAe+Hii2Kr017UwtCDYQw2EItYKyAHQsGY4EBtDNc356uYsW5Ll227HDtO67Auh57mcQLwMhBfrvv58Q5BUIHTDQPOPC99IsD0IEiBI+ngjdzNs+BH7I+C0Hi0QorwgR1Hzdx23Scd2HkhL8IK-Z8k08T9QPDYgYRtD4XvO7+t-ibQIn+bTIm9jz0DANaG1njKAcKJCAzwwCyzLC8KuN8YDzTxPXS21sj6twTu3Kgu9+AMy9mrful8jIb1LtvXmAA2Pe4dpCRybjHY+WDT44MVmoC+GcdozVzvfR+OIQwF0WlQ3+zwf6gLAP-MhXVgFpDEeAhB95DzQGQSNShJdR5l2kcIra18FFINrig82aCNzfiCNsU0AB5Eg5jhjPFgKwruOlWBIG2KkaOdt46J2TpQVOQFJACDcS3Dx2DKC4KVkZAhr8AFC0WlCc+tDEBbicWY7YljrEjDAHYrRYT2FqB0eJXO-CVHsChGoreXVwGVyzgomuJ1-bqPIewGE1CD7GKSRYqxNiMn2LThw+R+TpA8Kfi-ARvMmlZJkV-Z4Ej6lSN8CAyZ2iIHImgbA9JLA+mLj0bUxaMJSmANMtAeZm0KnLLlqsm0GymBbJDEAA

**Comment by lopatnov** [comment]
I think it might be a feature or a bug, I don't see in the handbook information about extending [Hybrid Types](http://www.typescriptlang.org/docs/handbook/interfaces.html#hybrid-types). I think the result of extending of 2 hybrid interfaces should be interface that allow 1st or 2nd interface function, but I can't describe it in interface. 

This is incorrect in interface:

```ts
interface Incorrect<T, TResult> {
  (((): TResult) | ((arg0: T): TResult));
}
```
but it's correct as a type in function parameter:

```ts
function sampleTest<T, TResult>(f: ((() => TResult) | ((arg0: T) => TResult))): TResult {
    return (f as () => TResult)();
}
```

Why not? 

Also, I don't see info about generic methods in [Hybrid Types](http://www.typescriptlang.org/docs/handbook/interfaces.html#hybrid-types). There is no any restriction to write something like:

```ts
interface CorrectSingleFunc2<TResult> {
  <T>(arg0: T): TResult;
}
```

It might be a bug that I can't use this interface as a type of function parameter when types of interface and generic functions are [known](https://github.com/microsoft/TypeScript/issues/35400#issuecomment-559557410).

**Comment by lopatnov** [comment]
Thanks @typescript-bot, thanks @weswigham for responses.
