### ISSUE TITLE
Representing non-ts assets for compilation

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#35415]
## Search Terms

watch, non-ts, files, not, typescript, .ts,

## Suggestion

I'm trying to create a solution builder that lets me preprocess markdown imports, (parse the markdown and serialize them into TypeScript files, which are used in the final compilation). Without this ability, I have to create an additional watch process to trigger the creation of new source files, and then clean and rebuild. This isn't ideal; if possible, I'd like to reuse the watch process spawned by `createSolutionBuilderWithWatch`. I guess the difficult question here then becomes: how does a non-ts source file look? This is probably a pretty big change... and begins to blur the line between compiler and packager. For the time being, how do community and team members feel about the following?:

## Example Usage:

1. add a new `compilerOptions` field:

```
{
  ...
  "includeForeignAssets": "true",
  ...
}
```

2. specify `includes` as we currently do.
3. the compiler would produce a new kind of `SourceFile` (dumbed down); this `SourceFile` could contain many of the same fields `pos`, `end`, `flags`, `kind`, `text`, `fileName`, ...
4. non-ts assets would be copied over, without necessarily being transformed.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by harrysolovay** [comment]
Oh, and—incase you celebrate—**happy Thanksgiving!**

**Comment by orta** [comment]
I think this is probably the domain of compiler plugins https://github.com/microsoft/TypeScript/issues/16607 rather than the TypeScript compiler increasing its scope

**Comment by harrysolovay** [comment]
@orta watch mode will not detect changes in non-ts files. Therefore, users––who want to manipulate non-ts files via a plugin––would need to create a parallel watch process that modifies the builder program. This is not only slow, but also breaks incremental builds. Putting all of that aside, I don't believe there's a way to enable this functionality via transforms alone. IMHO, the best path forward would enable users to process their non-ts assets via transforms; this would allow users to integrate their build tasks into the TypeScript compiler's process.

**Comment by fatcerberus** [comment]
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

> [Do not] provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

What you want to do is very much the domain of "external tools".

**Comment by harrysolovay** [comment]
@fatcerberus it's a tough line to draw, but I agree with you. Enabling seamless integration with packaging tools vs. turning into a packaging tool... well, one way or the other, hopefully the two root problems can be addressed (without breaking away from the design goals):

1. Users cannot modify the behavior of the watch process (without a custom fork or monkeypatch).
2. Incremental building only accommodates files which map directly to a corresponding output file; if a transform creates a new `SourceFile` instance based on another (or a non-ts file), there's no way to specify the branching (input(s) > output(s)) for incremental building to work as desired.

Could a given transform communicate with the incremental build system incase it has side-effects which update the dependency graph? And do you & others feel that these problems are worth addressing?

**Comment by fatcerberus** [comment]
The line gets blurrier than with most compilers because tsc works at the *directory level*, rather than directly taking a list of source files as input—and produces multiple files as output, reconstructing the original directory structure as it goes.  It’s been a bit of a challenge for me too, integrating TS with my Cell build system, because of that.

**Comment by harrysolovay** [comment]
Just to clarify, you're saying that users should have more control over output destination?

Would this be a fixed mapping, where the compiler takes care of rewriting imports relative to oneanother?:

`tsconfig.json`

```json
  ...
  "destBySrc": {
    "./src/index.ts": "./dest/a/b/c/d/e/f/g/h"
  }
  ...
```

Or would it be more dynamic? For instance, a function which receives the `SourceFile` instance and returns a new path or paths (incase you want to write the given file to more than one place)... or undefined (incase you want to prevent a file from being written).

`get-destination.ts`

```ts
import ts from "typescript";

export default function(sourceFile: ts.SourceFile) {
  let destination;
  // determine `destination`
  return destination
  // return [destinationA, destinationB]
  // return undefined
  // return null
  // return false
}
```

`tsconfig.json`

```json
  ...
  "getDestination": "./get-destination.ts"
  ...
```

This problem is tangential to the branching problem I described above. Part of me thinks that adding plug-ability for these inessential steps would be a mistake. Probably best to revisit this if / when the programatic API is in a more solid form (and documented ;).

I think the point of friction here is that incremental builds & watch mode could also be considered as in the domain of "external tools". Their focus is much more on workflow than on the language itself. As time goes on, I get the sense that it'll be hard to maintain this separation.

**Comment by fatcerberus** [comment]
No, I didn’t mean to suggest any particular solution - was just pointing out that tsc working at the level of entire directory structures (as opposed to—here’s your list of input files, here’s the list of output files, and here’s the options—like other CLI compilers) often creates friction when attempting to integrate it into larger build systems.  It was a general statement to highlight the seeming contradiction between the goal of “we want to be composable” vs. how tsc actually seems to behave “we want to be the entire build system for this directory”

**Comment by harrysolovay** [comment]
Looking back at this issue now. @fatcerberus your concerns are absolutely correct: any attempt to enable processing of non-ts assets would likely conflict with design goals. Thank you for the feedback!
