### ISSUE TITLE
showConfig printing help if no config is found

### ISSUE THREAD

**Issue by royAmmerschuber** [microsoft/TypeScript#35410]
**TypeScript Version:**  3.8.0-dev.20191128

**Search Terms:**
`showConfig`

**Example**
when running the command `tsc --showConfig` in a folder without a tsconfig.json file it shows the help page

**Expected behavior:**
throw an error (for example: `no config found`) or return empty config (for example: `{}`)

**Actual behavior:**
shows the standard help page from `tsc -h`, wich doesn't even contain any help for `--showConfig`.
**Playground Link:** None
**Related Issues:** None

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
