### ISSUE TITLE
More check for async await: return Promise in try block (without await)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#35429]
## Search Terms
check, async

## Suggestion
Add some suggestions for return statement which returns a Promise inside try block in async context. (That case takes me so many online bugs)

## Use Cases

```ts

async function foo(): Promise<string> {
    if (Math.random() < 0.5) {
        throw new Error("foo throw")
    }
    return "foo"
}

async function bar() {
    try {
        return foo() // Hey! here! await!
        // return await foo() // Expected
    } catch (e) {
        console.log(e.message) // never been call
        return "bar"
    }
}

```

## Examples

```ts
return foo() 
// ^^^^^^^ is that missing await?

return (foo()) // ok, I believe that you know what are you doing

```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ajafff** [comment]
I don't agree:

* maybe `foo` throws exceptions synchronously and you want to handle only that case without catching rejected promises
* wrapping the call expression in parentheses shouldn't suppress any error as some formatters automatically add them for multiline return

This can be checked by a lint rule instead, e.g. https://github.com/fimbullinter/wotan/blob/master/packages/mimir/docs/try-catch-return-await.md

**Comment by RyanCavanaugh** [comment]
I agree with @ajafff's reasoning. This code isn't "obviously wrong" and has a good chance of being with the author intended to do.

**Comment by payload** [comment]
@ajafff an async function can't throw synchronously, doesn't it?

**Comment by alitaheri** [comment]
@payload it surely can. a function can throw an exception **before** returning a promise you can `await` on.

I do like the idea, but I think it's better suited for a linter as a default rule than the compiler itself. Because with linter you can mark it as intentional, while with a compiler you'll need a non-readable syntax marker.

I'm sure this is usually a mistake, but for the few cases where it's intentional it's great to add a comment disabling the linter, the comment itself indicates why it's there and why it's not a mistake.

**Comment by payload** [comment]
@alitaheri consider that this
`function foo() { if (x) throw new Error(); return Promise.resolve(5); }`
is very different from this
`async function bar() { if (x) throw new Error(); return 5; }`

foo is a function which either throws synchronously or returns immediately a promise eventually resolving 5.
bar is an asynchronous function returning always immediately a promise which eventually resolves 5 or rejects with the error. 

An **async** function can't throw synchronously, it will always return a promise.

**Comment by alitaheri** [comment]
@payload I didn't know that. thanks 👍 

Then I guess this is valid for a function marked `async` 👍
