### ISSUE TITLE
Const assertion objects should have implicit index signature

### ISSUE THREAD

**Issue by bschlenk** [microsoft/TypeScript#35424]
## Search Terms

const object
const assertion
index signature

## Suggestion

Objects declared `as const` should have an implicit index signature which is a union of all of the object's values and `undefined`.

https://github.com/microsoft/TypeScript/issues/27127 looks similar, but it was closed without an explanation. It also looks like it was closed before `as const` was a thing, which I think makes this feature request more useful.

## Use Cases

Taking headers and converting them to the fields of an S3 request object. See the example below.

With `const` objects, the possible values are known - it would make sense to be able to index into a const object and get a type that is the union of all the values + undefined.

If I wanted to do this currently, then I'd type my object as `Record<string, string>`, but that causes error `ts(7053)`.

## Examples

```ts
const HEADERS_TO_ATTACH = {
  'content-type': 'ContentType',
  'cache-control': 'CacheControl',
  'content-disposition': 'ContentDisposition',
  'content-encoding': 'ContentEncoding',
  expires: 'Expires'
} as const;

function attachParam(request: AWS.S3.CopyObjectRequest, header: string, value: string) {
  // this should be inferred as `undefined | 'ContentType' | 'CacheControl' | 'ContentDisposition' | 'ContentEncoding' | 'Expires'`
  const prop = HEADERS_TO_ATTACH[header];

  if (prop) {
    // no error because `prop` here is guaranteed to be one of the keys of the `CopyObjectRequest`
    request[prop] = value;
  } else {
    request.Metadata[header] = value;
  }
}
```

If I type `HEADERS_TO_ATTACH` as `Record<string, string>` (the only workaround without this feature?), then the assignment to `request[prop]` fails with ts(7053).

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by poseidonCore** [comment]
Remember that there is some support for some aspects of this by using `keyof typeof HEADERS_TO_ATTACH` as the type for the parameter `header`:

[TS Playground](https://www.typescriptlang.org/play/?ssl=19&ssc=2&pln=1&pc=1#code/MYewdgzgLgBAEgUQIIBEECUDKB9AKgeWyV1yQGE4YBeGAbwCgYYByUMKAU3YFooBPAA4dmALhZlwndrkHCANIxbAAhsAAWHbmygAnEABtR41Rons9hhU1aSuUbgBMAlhAEgITqE-BHmZqVAoLm4eXj5WSrY8XKDOYADmvv52CGCxTgnMERwAHgJOOhwQYswIeQVFzPQAvjDKEDBs0ADc9PQAZgCuaWFgdVBQJgAKyjrKALYAFIUAjp1FUGLKYHxyMBrKDhw6YgDWHHwg7TD8QkfwyGhYeITEpBRrAG7K+vNi0DoZ8QCUdIoA9P8TmoXDAIGoQJ19A4YAAjDgwDLtbaFGH1GAAA26W3aGQ4MIAPuIolAZEJmDAiX4TBx-BYKVTkuwgq53J5vGAGcT2Ck0iA4olKSwyvlChBmBjFE1YAI9AJqBdUBgcAQiCRyHAANobLY6AC6rUUTmOk1lIAEvwYTCYgJgYBAMBRIB0cI4Kk6EARGLNAgx622CNB8U6o2WnHxJwd8Jg4AR5ygGhg+z4DXjiYxEgEfHwsIAVm6oOgOHMFpLrTBZvNoJqfXqFc9XhxWkxahx9J6-uXKwsAHQAWQ4gwcykG2o4m22dZoDfmzZg1RqQA)
```ts
const HEADERS_TO_ATTACH = {
  'content-type': 'ContentType',
  'cache-control': 'CacheControl',
  'content-disposition': 'ContentDisposition',
  'content-encoding': 'ContentEncoding',
  expires: 'Expires'
} as const;

function attachParam(request: any, header: keyof typeof HEADERS_TO_ATTACH, value: string) {
  // this should be inferred as `undefined | 'ContentType' | 'CacheControl' | 'ContentDisposition' | 'ContentEncoding' | 'Expires'`
  const prop = HEADERS_TO_ATTACH[header];

  if (prop) {
    // no error because `prop` here is guaranteed to be one of the keys of the `CopyObjectRequest`
    request[prop] = value;
  } else {
    request.Metadata[header] = value;
  }
}
```

**Comment by RyanCavanaugh** [comment]
This is the intended behavior and `keyof typeof X` is the intended way to express what you're doing.

Adding an implicit index signature would make `as const` things assignable to a *much* larger universe of target types, especially when you consider that `readonly` isn't part of assignability checking. This would cause a lot of false negatives where incorrect uses of `const`ed objects weren't identified as errors.

The example posted isn't self-contained so I can't speculate on what you mean with `Record<string, string>`
