### ISSUE TITLE
Code compiles for ES5 target, yields a compilation error for ES2015, ES2016

### ISSUE THREAD

**Issue by DoctorGester** [microsoft/TypeScript#35421]
**TypeScript Version:**  3.7.2

**Search Terms:** array intersection es5 target error

**Code**

```ts
type Grid<T> = {
    cells: T[]
}

type Cell = {
    position: number;
}

type UI_Cell = Cell & {
    thingy: number;
}

type Battle = {
    grid: Grid<Cell>
}

type UI_Battle = Battle & {
    grid: Grid<UI_Cell>
}

let battle: UI_Battle;

function mami() {
    for (const cell of battle.grid.cells) {
        console.log(cell.thingy);
    }
}
```

**Expected behavior:**
Code compiles for ES5, ES2015, ES2016 targets

**Actual behavior:**
Code compiles for ES5 target, yields "Property 'thingy' does not exist on type 'Cell'.(2339)" for ES2015, ES2016 targets

**Playground Link:** http://www.typescriptlang.org/play/?ssl=27&ssc=2&pln=1&pc=1#code/C4TwDgpgBA4gTgSwCYB4AqA+KBeKBvAKCmKgGMIAbCgZwC4o0BtAXQIF8CDRIoBhSijnxESYAPbUEwBGIB29WQFcAtgCMIcANztO3aAFUAkgH1+VIWcEAyYSSjAAFglkBzEApXqtOruGgAhAENgYApoXEI7F0QkenhkFEsMHz0oI2MgkLChTNDoG0iSaOQ4mJR0pJ8w4ChVYLz6dNyw7QIAM0VZUmk5KGVA5QQACgBKWxI2sTgoIdI5ahryczE22vqwgDpipA2lmjHCu2I52WoxTYoxF1mBDcdnNxHtOw42IA

**Related Issues:** Haven't found any :(

**Comment by fatcerberus** [comment]
Bizarrely, `--downlevelIteration` doesn’t affect this.  Only changing the target does.
