### ISSUE TITLE
spec: arbitrary choice of BindingIdentifier in index signature not clearly documented

### ISSUE THREAD

**Issue by jgehrcke** [microsoft/TypeScript#35422]
This is a point about the specification itself (and I do hope that it's OK to report it here).

In an Index Signature -- currently documented [in these paragraphs](https://github.com/microsoft/TypeScript/blob/7c14aff09383f3814d7aae1406b5b2707b72b479/doc/spec.md#3.9.4
) -- there is the `BindingIdentifier`.

Based on my own testing, based on an answer to [this question](https://stackoverflow.com/q/59103993/145400) on StackOverflow, and based on some blog posts the precise choice of the `BindingIdentifier` in an index signature does not matter to TypeScript.

It seems like one can choose an arbitrary value, and people seem to like `key` or `index` to make the intent explicit, readable. Let me quote [this resource](https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html):

> the name of the index signature e.g. index in { [index:string] : {message: string} } has no significance for TypeScript and is only for readability.

Now, I am new to TypeScript, and I really wanted to see a comment on that aspect in the source of truth, in the language specification. But I couldn't find that part commented on in section 3.9.4, and also not elsewhere in the spec. I have probably missed it elsewhere.

Action items depend on answers to these questions:

- is that behavior specified somewhere in the spec?
- if it is: should we link to that from section 3.9.4?
- if it is not commented on in the spec: should this be added somewhere?

**Comment by MartinJohns** [comment]
Forget about the spec. It's not maintained **at all** and heavily outdated. The last real update was done in January 2016, almost 3 years ago. So realistically TypeScript has no specification anymore.

See #15711.

**Comment by fatcerberus** [comment]
The specific identifier used in an index signature is like the the names of parameters in a function type: it doesn’t affect anything at compile time, it’s just there for documentation.
