### ISSUE TITLE
Wrong recognized `This expression is not callable`

### ISSUE THREAD

**Issue by MichalKalita** [microsoft/TypeScript#35423]
**TypeScript Version:**  All stable versions in playground (2.4.1 ... 3.7.2)

**Search Terms:**
This expression is not callable.

**Code**

```ts
const useLocalStorage = () => {
  const setValue = (value: string | ((oldValue: string) => string)) => { };

  // return [setValue];  // this work
  return ["", setValue]; // this doesn't work
}

// const [setValue] = useLocalStorage(); // this work
const [,setValue] = useLocalStorage(); // this doesn't work

setValue((state) => "");
/*^^^^^^
  This expression is not callable.
    Not all constituents of type 'string | ((value: string | ((oldValue: string) => string)) => void)' are callable.
      Type 'string' has no call signatures.(2349)
*/

```

**Expected behavior:**
It should works in any way of return internal function out.

**Actual behavior:**
This error doesn't makes sense, because if I return just setValue function will work.

**Playground Link:** 
[playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=1#code/MYewdgzgLgBArhApgGRMAhgGwMpRAJ3QHNEYBeGACgEpyA+GAbwFgAoGGUSWJKANSxxSFSgDdBiAFwxo+AJZgiMAD5VKITABMBmIdNkKitMgwOLqxhoxgBfANxs2HAPTOY+RFDj4wMANq8OkIAunYublAAFnIQMADuBADWTu6e3r5+AESZADQynkGIoTCuMFExMJogiBBgAOSwCfjJrDaOrKVc0P6BEsHk8EioGDh4hCQ0YaXlsU0tXbB+Ob26RQMIKGhYuATEiJMlEdGxVTX1jUntK0KUlNDoUIiWMNnUDh0AVAB6P78pACrHGCIAAeAAcPBAIHJwDAKmAQLARph0AAjTCIAB0KQ4ADlETAsJhOOBoHIvIgwFBYiAAGZlACeYNIdTMSlUt3Eq30UHkihUag02gkPL5RnoMl5hgsEtEIDkmmodUJHk4RLRGOx7A4Ov+TJZbOVkXQsQRaswxOhRDAD28NUxlAATABmAAsAE5qGwPs42EA)

**Related Issues:**

**Comment by AnyhowStep** [comment]
return [blah, blah] as const;

**Comment by MichalKalita** [comment]
Thanks @AnyhowStep 
I badly read the error message.

[Const assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) or make types for function result is a solution. 👍

**Comment by shiponcs** [comment]
I'm getting some errors like: 

> This expression is not callable.
  Not all constituents of type 'SetStateAction<string>' are callable.
    Type 'string' has no call signatures.ts(2349)

What I'm returning from a .tsx file : 
`  return [state, Dropdown, setState] as [
    string,
    FunctionComponent,
    SetStateAction<string>
  ];` 
above component was exported as and using in another file .tsx as below

I'm getting the error on other file where I'm using this:

` const [breed, BreedDropDown, setBreed] = useDropdown("Breed", "", breeds); // here importing the exported component
setBreed(""); // getting the error here.
`

**Comment by rawjson** [comment]
Thanks, this helped. I was using a custom hook for enabling dark mode and got this error.  Fixed it by returning the hook state as const.

`import { useEffect, useState } from 'react';

export default function useDarkMode() {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    const checkTheme = localStorage.getItem('theme');
    if (checkTheme) {
      checkTheme === 'dark' ? setDarkMode(true) : null;
    }
  }, []);

  useEffect(() => {
    const root = window.document.documentElement;
    if (darkMode) {
      root.classList.add('dark');
      localStorage.setItem('theme', 'dark');
    }
    if (!darkMode) {
      root.classList.remove('dark');
      localStorage.setItem('theme', 'light');
    }
  }, [darkMode]);

  return [darkMode, setDarkMode] as const;
}`
