### ISSUE TITLE
When extends abstract class show Error on impelimented method

### ISSUE THREAD

**Issue by Hamed228** [microsoft/TypeScript#35439]
Hi Dear team
I wanna use abstrac class 
I use React 

**TypeScript Version:**  3.7.2

**Search Terms:**

**Code**
```ts
export abstract class Moving {

    abstract selectThisCell(row: number, column: number): void;
}


export class VoucherArticlesModel<T extends IVoucherArticlesModel<R>, R> extends Moving {

    selectThisCell = (row: number, column: number): void => {
        this.getAll().currentRowIndex = row;
        this.getAll().currentColumnIndex = column;
        this.trigger('change');
    }
}
```
**Expected behavior:**
compile without any error

**Actual behavior:**
```
Class 'Moving' defines instance member function 'selectThisCell', but extended class 'VoucherArticlesModel<T, R>' defines it as instance member property.  TS2424

    58 |     }
    59 | 
  > 60 |     selectThisCell = (row: number, column: number): void => {
       |     ^
    61 |         this.getAll().currentRowIndex = row;
    62 |         this.getAll().currentColumnIndex = column;
    63 |         this.trigger('change');
```

**Comment by Hamed228** [comment]
when I change it to 
    selectThisCell(row: number, column: number): void {
        this.getAll().currentRowIndex = row;
        this.getAll().currentColumnIndex = column;
        this.trigger('change');
    }
compiler dosen'n have any problem with it!!

**Comment by IllusionMH** [comment]
See https://github.com/microsoft/TypeScript/issues/33113#issuecomment-525719206 and https://github.com/microsoft/TypeScript/pull/18654

**Comment by RyanCavanaugh** [comment]
When an error message correctly describes what's happening, it isn't a bug.

**Comment by Hamed228** [comment]
Hi
thank you a lot for your response
it dosen't work by arrow function the same as normal function!
as a result I didn't use abstract class
there are a lot of issues with abstact classes and I moved all methods and properties into main class
and removed abstract class 
javasctipt works correctly but when I use typescript, react and tsc compiler didn't work correctly
with regards
