### ISSUE TITLE
`!` type assertion on `never` changes the type

### ISSUE THREAD

**Issue by Skalman** [microsoft/TypeScript#35431]
**TypeScript Version:**  3.8.0-dev.20191128

**Search Terms:** ! type assertion, never, wrong type 

**Code**

```ts
type A = { kind: "abc" } | { kind: "def" };

function f(a: A) {
  switch (a.kind) {
    case "abc":
      return 1;
    case "def":
      return 2;
    default:
      throw new Error("Bad kind: " + a!?.kind);
      // Hover over `a`:             ^
  }
}
```

**Expected behavior:**

Hovering gives the type `never`.

**Actual behavior:**

Hovering gives the type `A`.

**Playground Link:** The TS playground doesn't work for me

**Related Issues:**  https://github.com/typescript-eslint/typescript-eslint/issues/1282

-----

**More context:** This is a problem for TypeScript ESLint's "no-unnecessary-type-assertion" rule, which relies on the `!` operator not changing the type of the underlying expression.
(@bradzacher, please correct me if I'm misrepresenting anything.)

In the following example, hovering the `a`s always gives the same type:

```ts
declare const a: { kind: string } | undefined;

console.log(a!?.kind);
console.log(a?.kind);
```

**Comment by bradzacher** [comment]
Note - it appears that this only seems to happen with the `never`s

```ts
type A = { kind: "abc" } | { kind: "def" };

function f(a: A) {
  switch (a.kind) {
    case "abc":
      return 1;
    case "def":
      return 2;
    default:
      throw new Error("Bad kind: " + a.kind);
      throw new Error("Bad kind: " + a!.kind);
  }
}
```

Best shown in the [ts-ast-viewer](https://ts-ast-viewer.com/#code/C4TwDgpgBAglC8UDeUDWBLAdgEwFxQCIBDAIwGMCoBfKAH2TSz0OwgDNKqBuAKB7YCumMsHQB7TFDYAKIvhgBKZDyhQAzgHd0wMgAsosgHQYcSpCtVQyRNdGLkCuC5agAnCMAGvJARl4vrWxZ2R2dLd09vKAAmf0tWNiIBABtgJxdVYF1XMQ0oTAg8gFFXHNdpAgAhImxGHHxKAGooImMmBTiXLJy8guLSsXKqmrrmJpaAQjbTOKoeKiA):

Inspecting the two `a` identifiers:
- In the first case (line 10, the one without the `!`), the API reports the type of the identifier `a` as `never`
![image](https://user-images.githubusercontent.com/7462525/69906021-c96fc900-1371-11ea-9d0b-ce67bf3aa7ac.png)

- In the second case (line 11, the one with the `!`), the API reports the type of the identifier `a` as `A`
![image](https://user-images.githubusercontent.com/7462525/69906026-e3111080-1371-11ea-8600-c4df62fc8639.png)

**Comment by RyanCavanaugh** [comment]
There's some sketchy logic in `getFlowTypeOfReference` that's happening when it shouldn't.
