### ISSUE TITLE
Suggestions for variable like name from type name

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#35430]
## Search Terms
completion, annotation

## Suggestion

Try provide name completions from type name for variable like declaration

## Use Cases
```ts
const us/*here*/ : UserService
// us -> userService
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
There are some conflicting priorities here with "new identifier locations" where we don't want to make any offerings
