### ISSUE TITLE
ReturnType<> broken with never in parameter (please revisit)

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#35432]
**TypeScript Version:**  3.7.2

**Search Terms:**

parameter, never, ReturnType

**Code**

The `AnyFunction` type is found here:
https://github.com/microsoft/TypeScript/blob/c447ebc59c49a1b071c099ce6055e94517973eab/src/compiler/core.ts#L1464

```ts
export type AnyFunction = (...args: never[]) => void;
//Expected: void
//Actual: any
type x = ReturnType<AnyFunction>;
```

**Expected behavior:**

`x` should be `void`

**Actual behavior:**

`x` is `any`

**Playground Link:** 

[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=4&pc=34#code/KYDwDg9gTgLgBDAnmYcCCA7RAxArhgYxgEsIM4BeOACgDp6BDKAcwGcAuODYAN2CgDaAXQCUlAHxweEYgBMA3ACgA9MoCi4YEWCzO0uSuVoiuBgBtODLIqQo4ISnABKwGLigYAKsmAAeTDj4RKQY4vJAA)

**Related Issues:**

Original Issue:
https://github.com/microsoft/TypeScript/issues/33457

PR to fix `ReturnType<>`:
https://github.com/microsoft/TypeScript/pull/33496

@jack-williams tracking the `never` and rest params issue:
https://github.com/microsoft/TypeScript/issues/33495

**Comment by RyanCavanaugh** [comment]
> I don't think it should be intended that "never" in a parameter breaks ReturnType

I disagree and don't see any case being made here. A function that expects a `never` parameter *can't be invoked*.

What problem is this causing for you?

**Comment by AnyhowStep** [comment]
The use case is precisely that I don't want the function to be invoked externally, but I want to preserve the return type information only.

**Comment by AnyhowStep** [comment]
The TS code base uses `never` in arguments for functions that it does not want to invoke directly, but knows that **some other** thing knows how to invoke it properly.

I don't think it's unreasonable to expect `ReturnType` to work properly, for these functions

**Comment by jack-williams** [comment]
A function of type `(...args: never[]) => void` _is_ callable: the type `never[]` is the type of empty lists so the function should be no different to `(...args: []) => void`.

I think the problem is already covered in existing issues and boils down to
1. Whether or not the proposal in #33495 should be accepted
2. And assuming (1), changing the definition of `ReturnType` to use `(...args: never) => infer R` instead.

**Comment by AnyhowStep** [comment]
In my PR, I'm using,
https://github.com/AnyhowStep/TypeScript/blob/15737c267e536bb373b8378628428fc831868a02/src/lib/es5.d.ts#L1469

```ts
type ReturnType<T extends (...args: any) => any> = T extends (...args: never) => infer R ? R : any;
```

+ `any` for the type parameter
+ `never` for the inference

Because `never` in the type parameter broke some tests.

[Playground](http://www.typescriptlang.org/play/#code/PQKhCgAIUg5B7ALgSwMYFNKIBaYAboAei6AdgCYDOkAFAHQMCGATgOaUBckjpAnnpAAOLRJGSksuSKnilKiZo3GI6UGAEEKk-ERIVq9Jm06RS6AG7pmA4c1Hjt02eWQpZjADZZeg9KuiQapAAKtjI1OFipHpupJ7+IMDgiD6YAELoiCTMAEqZAK7MpMGpADzBkLpkVLQMdCzsXDy8AJSQALwAfNx83e1QkIMVVfq1Ro2mFlZtXVEAZlaQOZAA-EuQTXwA3ODgwMAA8gDSAITJqSEAjACc5ZXE1dTNANoAun2QGVlWeYiFxWUaIQuPJmOJWAAaSB1BomYIzbrBN6dHbnXyfZjwADWZF+-xKvjuIxqhnqxi4ZkszARPV4fQGQ3uehJMPJkypNPEC2Y6zWy02vFR+wAooRfKgSOQuMczvt1BL8p5BlwCZgAORAkEKcFQ1kTeEdRFvNWQcjwdDUUhISCURgoShzXiOGRyBRKaKQDV6kyU6aG2lq1QpdFpTE44o3IkPUYvd4dDHY3EFIqq0qam3a0iQ6HjOE0pHvHZAA)
