### ISSUE TITLE
Require a feature for adding polyfills according to browserslist config

### ISSUE THREAD

**Issue by budarin** [microsoft/TypeScript#35441]
Today we have 2 options
- manually review the code and guessing to add this code polyfill or not
- add all 150KB of core-js.js code at once

I think it's a question of TS add the necessary polifill as does Babel.

While with TS we are now in production bugs arise due to the lack of polyfills or code weighs 150кб more than it needs

And society has no answer for this common problem 
https://stackoverflow.com/questions/59061154/how-to-polyfill-typescript-code-and-not-to-over-polyfilll-it

Using TS+Babel - it is not effective to use 2 tools at once

**Comment by RyanCavanaugh** [comment]
The "correct" answer here would be to set your target to the minimum environment's, import from a polyfilling library, and use a treeshaking tool afterwards. We're intentionally trying to keep TS's build behavior as straightforward as possible, so something like this would be out of scope

**Comment by budarin** [comment]
спасибо за ваше терпение и корректный ответ

у меня есть возражение - polyfills привязываются к глобальному объекту window поэтому tree shaking никогда их не удалит потому что он не знает нужны они реально или нет - поэтому проблема с polyfills и стоит так остро

**Comment by seivan** [comment]
Related https://github.com/Microsoft/TypeScript/issues/20095
There is merit in the idea. The only reason we use Babel is because of the it lets you set a `browserlist` to generate necessary polyfills for targets. 
It would be useful if this was part of TSC.
