### ISSUE TITLE
Bug xor Feature? TypeScript does not pick up types from tsconfig.json "types"

### ISSUE THREAD

**Issue by baslr** [microsoft/TypeScript#35440]
**TypeScript Version:**  Version 3.8.0-dev.20191128

**Search Terms:** `compiler type information module`, `additional type information module`, `typeRoots`

**Code**
https://github.com/baslr/ts-demo-bug-types-typeroots

**Expected behavior:**
`tsc` is pointed to a `types` path and picks the types up and makes them available as all the other types that are available without `import`.

**Actual behavior:**
* create a module in ts
   * export typings via `package.json "types`; `types` are autogenerated via `declaration: true`
   * export typings via `tsconfig.json "typeRoots"`; interface definitions, additions for other types eg. `Error`.

* `testmodule $ npm pack` and `tech-demo $ npm install` use this module and have the interface types available the same as I have all the other types available without `import` magic.

I set up an example at https://github.com/baslr/ts-demo-bug-types-typeroots which illustrates the behavior.

Pointed `tsc` directly to `./node_modules/testmodule/types` but `tsc` wont pick up the `MyInterface` type.

from https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types
`A types package is a folder with a file called index.d.ts or a folder with a package.json that has a types field.`
I meet both requirements in the `testmodule`. But `tsc` wont recognize the type in `testmodule/types/index.d.ts`.

From https://github.com/microsoft/TypeScript/issues/18761#issuecomment-332219990 I learned that this problem could be manually fixed with including a `/// <reference path >`.  
I included `/// <reference path="./types/index.d.ts" />` in the `testmodule/index.ts` file. `tsc` converts this in the `testmodule/index.d.ts` to `/// <reference types="types" />`. Which in the end `tech-demo` can not use it.

Also `/// <reference ...>` works only when `import * as foo from 'testmodule'` is done. If you have the file `tech-demo/index.ts`
```typescript
let mytest : MyInterface;
```
compiling it will fail.
```bash
./tsc
src/index.ts:4:8 - error TS2304: Cannot find name 'MyInterface'.

4 let b: MyInterface;
         ~~~~~~~~~~~


Found 1 error.
```
**Output**
```bash
git clone https://
cd /testmodule
npm install
./tsc
npm pack
cd ../tech-demo
npm install
./tsc
node_modules/testmodule/index.d.ts:1:36 - error TS2304: Cannot find name 'MyInterface'.

1 declare function mytestfunction(): MyInterface;
                                     ~~~~~~~~~~~

src/index.ts:15:8 - error TS2304: Cannot find name 'MyInterface'.

15 let b: MyInterface;
          ~~~~~~~~~~~


Found 2 errors.


# with /// <reference path="./types/index.d.ts" /> in testmodule/index.ts
./tsc
node_modules/testmodule/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'types'.

1 /// <reference types="types" />
                        ~~~~~

node_modules/testmodule/index.d.ts:2:36 - error TS2304: Cannot find name 'MyInterface'.

2 declare function mytestfunction(): MyInterface;
                                     ~~~~~~~~~~~

src/index.ts:15:8 - error TS2304: Cannot find name 'MyInterface'.

15 let b: MyInterface;
          ~~~~~~~~~~~


Found 3 errors.


# with manually fixed /// <reference path="./types/index.d.ts" /> in tech-demo/node_modules/testmodule/index.d.ts
./tsc

# no error
```

**Related Issues:** #26900 #18761 #14465

**Comment by RyanCavanaugh** [comment]
A types folder is one that contains `index.d.ts` or `package.json`.

A types root is a folder containing zero or more types folders.

What you have here is `index.d.ts` inside a types root, which is not either of those things!

If you move `testmodule/types/index.d.ts` to `testmodules/types/qqqqq/index.d.ts`, you'll see that the program builds without error as expected.
