### ISSUE TITLE
Different behavior when destructuring from using dot notation.

### ISSUE THREAD

**Issue by larsbs** [microsoft/TypeScript#35443]
**TypeScript Version:**  3.7.2

**Search Terms:**  different behavior when destructuring typescript strictNullChecks

**Code**

```ts
interface Data {
  readonly name: string;
  readonly id: number;
}

interface MainInputLoading {
  readonly isLoading: true;
  readonly data: null;
}

interface MainInputLoaded {
  readonly isLoading: false;
  readonly data: Data;
}

type MainInput = MainInputLoading | MainInputLoaded;

function main({ isLoading, data }: MainInput) {
  if (isLoading) {
    return;
  }

  console.log(data.id);  // Fails
}

function altMain(input: MainInput) {
  if (input.isLoading) {
    return;
  }

  console.log(input.data.id);  // Doesn't fail
}

```

**Expected behavior:** They should behave exactly the same as TS should be able to know that the destructured props still refer to the original object.

**Actual behavior:** In one case we have an error and in the other we don't.

**Playground Link:** https://codesandbox.io/s/sweet-williamson-7bs9d

**Related Issues:** No

**Comment by IllusionMH** [comment]
Looks like duplicate of #33097, #28599, and many other which in the end are related to #12184

**Comment by larsbs** [comment]
Duplicated then.
