### ISSUE TITLE
Unexpected/surprising behavior with type casting and private instance properties. 

### ISSUE THREAD

**Issue by cozmo** [microsoft/TypeScript#35457]
I'm seeing some surprising behavior in how type assertions are failing in inconsistent/surprising ways. It's possible they _should_ be failing, but from what I've seen there's still inconsistent/unexpected behavior that would appear to be a bug. 

**TypeScript Version:**  `3.8.0-dev.20191128`, but also present on previous versions I tried in the playground. 

**Search Terms:**
- `type cast property private TS2352`

**Code**
This code works. Open question on if it _should_ work, since the arguments for bar differ between `Foo` and `mockFoo`, but I believe that should be okay since the arguments for `mockFoo.bar` are a subset of `Foo.bar`? 
```typescript
class Foo {
  bar(baz: number) {
    return baz;
  }
}

const mockFoo = {
  bar: () => 7,
} as Foo;
```

If we add a private property to `Foo` then the same code does not compile: 
```ts
class Foo {
  private nonya: 10;
  bar(baz: number) {
    return baz;
  }
}

const mockFoo = {
  bar: () => 7,
} as Foo;

// error TS2352: Conversion of type '{ bar: () => number; }' to type 'Foo' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
//  Property 'nonya' is missing in type '{ bar: () => number; }' but required in type 'Foo'.
```

**Expected behavior:**
I'm not sure if the first example should fail or not, my understanding is it _should not_ fail, BUT either way I would not expect adding/changing private properties to change if this code fails or not, since nothing about the external interface of `Foo` is changing.

**Comment by MartinJohns** [comment]
Without private members the class is structurally typed, and your object literal is compatible. Once you have private members your class is nominally typed and the object literal is not compatible anymore.

https://github.com/microsoft/TypeScript/wiki/FAQ#when-and-why-are-classes-nominal
