### ISSUE TITLE
Type system maybe broken

### ISSUE THREAD

**Issue by leunam217** [microsoft/TypeScript#35463]
Dear, typescript developers. I'm new to typescript so maybe this is normal but it seems weird to me.
**TypeScript Version: all

**Search Terms:** type system broken

**Code**

```ts
function sum(a: any, b: any): string {
    return a + b;
}

let s: string = sum(4, 4);
s.split('');
```

**Expected behavior:**
  Compile error, sum can return something else than string, ex : number
**Actual behavior:**
 Run-time error a.split is not a function

**Comment by MartinJohns** [comment]
You are using `any`. Using the `any` type is basically an escape hatch from the type-system, removing all type-safety from the code involving those variables.

Everything works as intended.
