### ISSUE TITLE
Nightly throws error on load in browsers where globalThis.TypeScript is undefined

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#35469]
**TypeScript Version:**  3.8.0-dev.20191203

**Search Terms:** globalThis.TypeScript

**Code**

```html
<html>
<script src="node_modules/typescript/lib/typescript.js"></script>
</html>
```

**Expected behavior:** Does not error.

**Actual behavior:**

Throws: `TypeError: Cannot read property 'Services' of undefined`

Bug is on this line: https://github.com/microsoft/TypeScript/blob/c447ebc59c49a1b071c099ce6055e94517973eab/src/services/globalThisShim.ts#L43

Should be noted there is a `// @ts-ignore` comment above this line.

**Comment by dsherret** [comment]
Is there a test that attempts to load typescript.js in a browser? Might be useful as this kind of bug has happened a few times and IIRC a similar bug even made it into the released 3.7.2.

**Comment by orta** [comment]
I don't think there's a browser test for that - nope. 

I think it might be doable to run a [puppeteer script](https://pptr.dev) which does the above script and verifies it does not raise an exception.

**Comment by weswigham** [comment]
Ahhh, my fault - I rewrote it from a `namespace` declaration that was implicitly making all the missing bits - apparently we have _literally nothing else_ that makes a `TypeScript` global member. Talk about legacy.
