### ISSUE TITLE
Visual Studio 2017 (2019) can't find parent project modules without disableSourceOfProjectReferenceRedirect

### ISSUE THREAD

**Issue by busyscout** [microsoft/TypeScript#35465]
I migrated my project to v3.7.2 from v3.5. 
I have parent project and several child projects.
Now both VS2017 and VS2019 show errors (red squiggles) 'Cannot find module <module_name> ' in all child projects for all parent modules.
At the same time typescript code compiles OK to js and d.ts files from Visual Studio and tsc.
I restarted VS, I cleaned all generated js and d.ts files. Nothing helps.
The problem **disappeares** if I set `disableSourceOfProjectReferenceRedirect` option to `true` in tsconfig.json for my child project.

I reference project like that in tsconfig.json
```
"references": [
    { "path": "../ParentProjectFolder" }
  ]
```
I reference module like that in child project ts files
```
import * as module_name from 'module_name';
```
module_name.ts is in the root folder of my parent project.

**Comment by RyanCavanaugh** [comment]
Can you provide a zip file or other concrete way to reproduce the problem? Thanks!
