### ISSUE TITLE
this function argument type can not be narrowed to its subclass

### ISSUE THREAD

**Issue by bogdan** [microsoft/TypeScript#35466]
**TypeScript Version:**  3.5.3

**Search Terms:**

**Code**

```ts
type Attributes<T> = {[P in keyof T]? : T[P]};
class A {
  setAttributes(attributes: Attributes<this>) {
  }
}

class B extends A{
  async run(attributes: Attributes<B>) {
    this.setAttributes(attributes)
  }
}
```

**Expected behavior:**

No Error

**Actual behavior:**

```
tmp/test.ts:9:24 2345: Argument of type 'Attributes<B>' is not assignable to parameter of type 'Attributes<this>'.
```

I didn't find any way for this check to be relevant. If someone can point me out the use case where such check is required, please let me know.

**Playground Link:** 

http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=24&pc=1#code/C4TwDgpgBAgswCcCWAjArsCBnAPAFQD4oBeKAbwG0AFKJAOygGsIQB7AMyjwF0B+KAFxdq3AL4BuAFABjADYBDLFljlJUKFgjA4iVBmwAKefGTpMWITtP7cwABZIsBAJSr1oyR5kKlUAEJQEAAemHQAJsowZGpQiiB00lAIaHRGJnrmlulm2Dh+Lm7qUPaOAHSa2tk2abo5WM4xHqJAA

**Comment by RyanCavanaugh** [comment]
This is a correct error; in a derived class of `B`, there may be additional properties that would not be present in `Attributes<B>`

**Comment by bogdan** [comment]
Why would B have properties that would be present in `Attributes<B>`? If that would be true, does it mean that the following should compile (which doesn't):

```
const z: Attributes<{a: number}> = {a: 1, b: 2}
// 2322: Type '{ a: number; b: number; }' is not assignable to type 'Attributes<{ a: number; }>'. Object literal may only specify known properties, and 'b' does not exist in type 'Attributes<{ a: number; }>'
```

**Comment by RyanCavanaugh** [comment]
Again, this is a correct error. Extra properties is just one form of subtyping that could occur here.
```ts
type Attributes<T> = {[P in keyof T]? : T[P]};
class A {
  a: string = '';
  setAttributes(attributes: Attributes<this>) {
  }
}

class B extends A{
  b: string = '';
  async run(attributes: Attributes<B>) {
    this.setAttributes(attributes)
  }
}

class C extends B {
  b: "foo" = "foo";

  setAttributes(attributes: Attributes<this>) {
    if (attributes.b !== undefined) {
      // Must be true, but is false
      console.log(attributes.b === "foo");
    }
  }
}

const b: B = new C();
b.run({ a: 'a', b: 'not foo' });
```

**Comment by bogdan** [comment]
Wow! I see what you mean now, thanks for explanation.
