### ISSUE TITLE
Different behavior when using keyof 

### ISSUE THREAD

**Issue by v3470** [microsoft/TypeScript#35464]
**TypeScript Version:**  3.7.2

**Search Terms:** keyof, generic, array, index

**Code**

```ts
type t1 = [string];
type B1 = {    // type B1 = {[x: number]: boolean; 0: boolean;  length:...
    [K in keyof t1]:boolean;
} 
type B2<T> = {
    [K in keyof T]:boolean;
}
type B3 = B2<t1>;    // type B3 = [boolean]
```

**Expected behavior:** B1 is equivalent to B3

**Actual behavior:** B1 gets properties from Array type but B3 gets member in array.

**Playground Link:** http://www.typescriptlang.org/play/index.html#code/LAKABKAuCeAOCmZIEYwF4wG0DOkBOAlgHYDmAugNxRyIBCqGA3qGK1gNJjFgDW80AewBmSZGQBcAIwECANvACGRKiAC+EEDARhaAJgA8AFQB86MM3BtMnbn0EjDE6XMXLQq6ttoBmM3v0oxioA9ME6qATYYEQCkGDwAI4ArgQAbgryRHGQAjreoEA

**Related Issues:**  not find yet

**Comment by jack-williams** [comment]
See #26063.

`B1` is an ordinary mapped type; `B2` is a homomorphic mapped type. They have different behavior on arrays and tuples.
