### ISSUE TITLE
Format incorrectly adds space after increment

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#35474]
From https://github.com/microsoft/vscode/issues/85823

**TypeScript Version:** 3.8.0-dev.20191203

**Search Terms:**

**Repo**
For the code:
```ts
let i = 0;
(i++, i++)
```

Run format

**Expected behavior:**
No change.

**Actual behavior:**
Space inserted after the first `i++`:

```ts
let i = 0;
(i++ , i++)
```

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh There is [open](https://github.com/microsoft/TypeScript/pull/35550) PR for this issue.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
