### ISSUE TITLE
Expected Interface Augmentation, Overrode Interface Instead

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#35483]
Our behavior when augmenting a module that reexports other things is surprising. You end up accidentally overriding entire exports, rather than merging with them.

**Code**

```ts
// @filename: file.ts
export interface Foo {
    x: number;
}
// @filename: reexport.ts
export * from "./file";
// @filename: augment.ts
import * as ns from "./reexport";

declare module "./reexport" {
    export interface Foo {
        self: Foo;
    }
}

declare const f: ns.Foo;

f.x;
f.self;
f.self.x;
f.self.self;
```

**Expected behavior:**
No errors.

**Actual behavior:**
`Property 'x' does not exist on type 'Foo'.`

Workaround: Augment the original file containing the declaration in question, rather than the file that reexports it.

**Comment by andyrichardson** [comment]
I'm also having this issue - it looks like this only applies to interfaces which are not namespaced.

**[Reproduction (see index.tsx)](https://codesandbox.io/s/magical-wilbur-gem5z)**

Would be awesome if we can get this labeled as a bug.
