### ISSUE TITLE
Optional argument in callback object not possible

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#35481]
**Expected behavior:**

        aa(resolve: ({result ?: boolean}) => void)
        {
        resolve({result:true});
        }

should work

**Actual behavior:**
<img width="466" alt="Bildschirmfoto 2019-12-04 um 00 13 44" src="https://user-images.githubusercontent.com/364896/70097973-f69ad080-162a-11ea-90ee-993cee2281c1.png">

If I remove the "?" it works... But Property should be optional

**Comment by weswigham** [comment]
You're missing the argument name - write
```
    aa(resolve: (arg: {result?: boolean}) => void)
    {
        resolve({result:true});
    }
```
instead.

**Comment by jogibear9988** [comment]
you‘re right... 
shame on me...

but why does it work without the questionmark?
