### ISSUE TITLE
Generator<T, TReturn>['next'] doesn't narrow properly when using assignment expressions or the comma operator

### ISSUE THREAD

**Issue by JakeTunaley** [microsoft/TypeScript#35484]
**TypeScript Version:**  3.8.0-dev.20191203

**Search Terms:**

* generator
* generators
* iterator
* iterators
* narrow
* narrowing
* assignment
* expression
* next
* comma
* operator

**Code**

```ts
function* generator () {
	yield 4;
	return 'hello world';
}

function consumer1 () {
	const gen = generator();
	let result = gen.next();
	while (!result.done) {
		((x: number) => {})(result.value);
		result = gen.next();
	}
	((x: string) => {})(result.value);
}

function consumer2 () {
	const gen = generator();
	let result;
	while (!(result = gen.next()).done) {
		((x: number) => {})(result.value);
	}
	((x: string) => {})(result.value);
}

function consumer3 () {
	const gen = generator();
	let result;
	while (result = gen.next(), !result.done) {
		((x: number) => {})(result.value);
	}
	((x: string) => {})(result.value);
}
```

**Expected behavior:**

Type narrowing for `result.value` should be the same in `consumer1`, `consumer2`, and `consumer3`.

**Actual behavior:**

`consumer1` narrows `result.value`.

`consumer2` and `consumer3` don't narrow `result.value`, thus giving the following errors:

> Argument of type 'string | number' is not assignable to parameter of type 'number'.
> > Type 'string' is not assignable to type 'number' .ts(2345)

> Argument of type 'string | number' is not assignable to parameter of type 'string'.
> > Type 'number' is not assignable to type 'string'. ts(2345)

Explicitly declaring the type of `result` to be `IteratorResult<number, string>` (the type inferred in `consumer1`) does not fix the issue.

**Playground Link:**

[Playground Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191128#code/GYVwdgxgLglg9mAVAAgOYFMzoE4EMpzbIAUAlMgN4BQAkAJ4zoA2AJsgCwDct26UI2MMgDkAC2ZM4yAO6FWw7gF8qVUJFgJkEBAGcQAWxwBGEuWo1tYHVDSZkAXltY8BbGW40mfZLz1MbjhhgAHRYAB5Q7rTSojBeJACEviD+wSwI6Ga0NMTEYQBcyGAGAEY45PYAfJSKpMTJqQBuuEwgmR40DQFOoegRUTTKOXmF1tgwYKgV1RS19eh+UMHNre1Uyqrg0PBClnqG2ABMppS0ezZBDk44+IQDXjZdHjFx6Inzi1dBvf2kpGkZLI0YYFIqlcoOGZzLrLFptUgeIa5UFjCZTSE1OowlbwpQqNTbTR7Aw4ADMJ3M5ycX0wN1c928T2isXiHxS3W+4UipAANMgkgt2QCsECQYVivoythppi2U04WtBrRkaMoONJjLZljBfLVgj1kA)

**Related Issues:**

None

**Comment by rbuckton** [comment]
In the time since this bug was filed, we seem to have addressed the issue regarding narrowing for `consumer3`, however `consumer2` still does not perform narrowing of `result`. 

In `consumer3`, the reference for `result` in `result.value` has a control flow graph that looks something like this:

```
True (result = gen.next(), !result.done) ─ Assignment (result) ─ Loop ─ Assignment (gen = generator()) ─ Start  
```

Meaning that we're on the `True` branch of the loop.

In `consumer2`, the graph differs for `result.value`:

```
Assignment (result) ─ Loop ─ Assignment (gen = generator()) ─ Start  
```

All we see is the assignment to `result`, the `.done` is disconnected from the reference.

This failing case can be simplified in the following manner:

```ts
type D = { done: true, value: 1 } | { done: false, value: 2 };
declare const obj: D;
{
  let o: D;
  if (o = obj, o.done) {
    const x = o.value; // x has type '1'
  }
}
{
  let o: D;
  if ((o = obj).done) {
      const x = o.value; // x has type '1 | 2' but should be '1'
  }
}
```
