### ISSUE TITLE
Wrongly "is not assignable to type" for Object

### ISSUE THREAD

**Issue by yw662** [microsoft/TypeScript#35487]
**TypeScript Version:**  3.7.2

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
type a = 'a'
type ab = a | 'b'
interface b {b: ab};

type a = 'a'
type ab = a | 'b'
interface b {b: ab};

function ca(d: a) {}
function c(d: ab) {
    if(d === 'b') {}
    else ca(d);
}

function da(d: {b: a}) {}
function d(d: b) {
    if(d.b === 'b') {}
    else da(d);
}
```

**Expected behavior:**
It should compile.
**Actual behavior:**
TS2345: Argument of type 'b' is not assignable to parameter of type '{ b: "a"; }'.
  Types of property 'b' are incompatible.
    Type 'ab' is not assignable to type '"a"'.
      Type '"b"' is not assignable to type '"a"'.

**Playground Link:** 
Not yet.

**Related Issues:** 
Not yet.

**Comment by RyanCavanaugh** [comment]
Duplicate #10065
