### ISSUE TITLE
Difference between 1.4 and 1.5 in generating JavaScript for enums in declared modules

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/TypeScript#3548]
For the code like this:
``` TypeScript
declare module M {
    export enum E {
        V = 1
    }
}

var a = M.E.V;
```

1.4 generates
``` JavaScript
var a = 1 /* V */;
```

1.5 generates
``` JavaScript
var a = M.E.V;
```

Is it expected?

**Comment by danquirk** [comment]
Yes, that's intended. See http://stackoverflow.com/questions/28818849/how-do-the-different-enum-variants-work-in-typescript, in particular the end:

_Changes in TypeScript

Between TypeScript 1.4 and 1.5, there was a change in the behavior (see https://github.com/Microsoft/TypeScript/issues/2183) to make all members of non-declare non-const enums be treated as computed, even if they're explicitly initialized with a literal. This "unsplit the baby", so to speak, making the inlining behavior more predictable and more cleanly separating the concept of const enum from regular enum. Prior to this change, non-computed members of non-const enums were inlined more aggressively._

**Comment by splintor** [comment]
But https://github.com/Microsoft/TypeScript/issues/2183 explicitly says: 
> Ambient non-const enums preserve existing behavior (computed iff there is no initializer)

And this problem is about ambient (declared) non-const enums. In 1.5, they are treated as computed and are not inlined.
