### ISSUE TITLE
No source for the diagnosticInformationMap generation?

### ISSUE THREAD

**Issue by colbyrussell** [Microsoft/TypeScript#3549]
We have diagnosticInformationMap.generated.ts and its diagnosticMessages.json source, but there doesn't seem to be any build step that produces the former from the latter, nor does there seem to be any file in the repo for the generator source.

The generator should be checked in, the build process fixed to invoke it, and diagnosticInformationMap.generated.ts should be added to .gitignore and removed from the index.

It's possible that I'm overlooking something here.

**Comment by colbyrussell** [comment]
> It's possible that I'm overlooking something here.

In fact, I was.  (Was grepping only through ./src instead of project-wide.)

The generator is processDiagnosticMessages.ts, invoked by Jakefile.js.

**Comment by DanielRosenwasser** [comment]
To clarify for others, the command you're interested in is

```Shell
jake generate-diagnostics
```
