### ISSUE TITLE
support export as const enum from enum

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#35492]
## Search Terms

enum,  const enum

## Suggestion

support export as const enum from enum

## Examples

```ts
enum Foo {
  a="a",
  b="b",
}

export const FooList = Object.values(Foo) as Array<Foo>;

export const enum MyFoo = Foo;
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Please fill this in more completely next time if you'd like this to be considered. Just jotting down some syntax doesn't give us much idea of the problem you're trying to solve or what's lacking in the current options.
