### ISSUE TITLE
Incorrect return type of function with conditional return

### ISSUE THREAD

**Issue by JesperLekland** [microsoft/TypeScript#35499]
**TypeScript Version:**  3.7.2

Hi guys! I'm sorry if I have misunderstood something but I really don't think this is the correct behaviour. If it is I would love the reasoning behind it. Cheers!

**Search Terms:**
Inferred return type 
Function with conditional using wrong union - empty object
**Code**

```ts
// Return type inferred wrongly to empty object "{}"
const foo = (bar?: any) => {
  if (bar) {
    // if you inline property 'baz' in return then problem goes away ... (?)
    const baz = {
      baz: 'baz',
    };

    return {
      ...baz,
      foo: 'foo',
    };
  }

  return { };
};

// Return type inferred correctly to  { baz: string, foo: string, bar?: undefined } | { bar: string }
const foo2 = (bar?: any) => {
  if (bar) {

    const baz = {
      baz: 'baz',
    };

    return {
      ...baz,
      foo: 'foo',
    };
  }

  // just adding a random key here solves the problem
  return {
    bar: 'bar',
  };
};
```

**Expected behavior:**
Typescript correctly infers return type 
```ts
type FooReturn = { baz: string, foo: string } | {}
```
**Actual behavior:**
```ts
type FooReturn = {}
```
**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/index.html#)
**Related Issues:**

**Comment by AnyhowStep** [comment]
Something to do with union reduction and how it works.

https://github.com/microsoft/TypeScript/issues/32237

**Comment by JesperLekland** [comment]
It is indeed frustrating. I still find it weird that if I for example don't do the spread, i.e 
```ts
const foo = (bar?: any) => {
  if (bar) {
    return {
      baz: 'baz',
      foo: 'foo',
    };
  }

  return { };
};

```
then it works as expected. It's just that explicit typing in this case is super cumbersome for us, we use a bunch of nested functions (hence the spreads) and they all have pretty complex overloads as it is.

**Comment by RyanCavanaugh** [comment]
Subtype reduction is in general the correct behavior because you have to account for the possibility of aliasing.

Consider this code, which is not meaningfully different from your example:
```ts
function getSomeObj(): {} {
  const obj = { baz: 10, foo: false };
  return obj;
}

function fn() {
  if (Math.random() > 0.5) {
    return { baz: "", foo: "" };
  } else {
    return getSomeObj();
  }
}

const k = fn();
// k.baz?
```
You cannot meaningfully say anything about `k`'s `baz` or `foo` properties because the `{}` type includes values for which those properties have types other than `string`.

**Comment by JesperLekland** [comment]
> Subtype reduction is in general the correct behavior because you have to account for the possibility of aliasing.
> 
> Consider this code, which is not meaningfully different from your example:
> 
> ```ts
> function getSomeObj(): {} {
>   const obj = { baz: 10, foo: false };
>   return obj;
> }
> 
> function fn() {
>   if (Math.random() > 0.5) {
>     return { baz: "", foo: "" };
>   } else {
>     return getSomeObj();
>   }
> }
> 
> const k = fn();
> // k.baz?
> ```
> 
> You cannot meaningfully say anything about `k`'s `baz` or `foo` properties because the `{}` type includes values for which those properties have types other than `string`.

I'm not sure I'm following. Wouldn't it perfect sense for your example `fn` to have return type of `{ baz: string, foo: string } | {}`
