### ISSUE TITLE
callbacks should select the right overload

### ISSUE THREAD

**Issue by millsp** [microsoft/TypeScript#35501]
**TypeScript Version:**  3.8.0-dev.20191121

**Search Terms:**

callback overload mismatch

**Code**

```ts
declare function fn(x: string): string;
declare function fn(x: string[]): string;

declare function map<A, R>(fn: (item: A) => R, list: A[]): R[];

const mapped = map(fn, ['1']) // error
```

**Expected behavior:**

TypeScript does infer `A` as `string` and could choose the right overload `fn(x: string)`, decline the ones that don't fit.

**Actual behavior:**

Checks the last overload only, so it shows an error.

**Playground Link:** http://www.typescriptlang.org/play/?ssl=7&ssc=1&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQAoAPALngGcMYtUBzASnKpvoG4AoUSWBFdbHgIlm1WnQDaAXSaUx7Dl3DQ4SNJlz4AtlAAOAHgCCAGngAlAHyFEqcoSwYQW8oYbwAvBfOmIWKi+lZM2lODjA8KngdXV0QYA8ovWtUUwkAcgBGNJkOIA

**Related Issues:**

**Comment by pirix-gh** [comment]
Another example, where both overloads would match

```ts
declare function fn(x: string): string;
declare function fn(x: string): number;

declare function map<A, R>(fn: (item: A) => R, list: A[]): R[];

const mapped = map(fn, ['1'])
```

`mapped` should be of type `number[] | string[]`

**Comment by pirix-gh** [comment]
And I think that it is important to share my current workaround

```ts
declare function fn(x: string): string;
declare function fn(x: string[]): string;

declare function map<A, R>(fn: (item: A) => R, list: A[]): R[];

const mapped = map((x) => fn(x), ['1'])
```

**Wrapping `fn` does get TS to choose the right overload**

**Comment by RyanCavanaugh** [comment]
Generic inference is not able to do overload resolution, though your examples all don't need overloads in the first place.

**Comment by pirix-gh** [comment]
The examples are silly yes, but they do show how overloads could be improved. I get these scenarios quite often (on ramda especially). So for now, I wrap with `() => ` which does the trick, so I thought this could have been solved easily.

**Comment by jamiebuilds** [comment]
Here is the simplest possible replication of this I could come up with: [[Playground](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=13&pc=1#code/JYOwLgpgTgZghgYwgAgMJwDYYEaINbIDeAUMmcgBQBumArhAFzIi0C220AlE3CAJ6ly1Oo2QBnMFFABzbsl4CAvsWIxaIBGGAB7EMhggKCTDnxN0WXAjycixAJAB6R8gB074stWGaGesgBeAD47Jxd3V09OYiA)]

```ts
interface Callback {
  (value: number): any
  (value: string): any
}

function fn(callback: Callback) {
  // ...
}

fn(value => {
  // ^ Parameter 'value' implicitly has an 'any' type.
})
```

<details>
<summary>Here is a real world example: [<a href="https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgMJwDYYEaINYA8AKgHzIDeAUMjcgBTRQD2UAXMiAK5YA0yUEAM7cw7IgEp2nEHhBMA7iGq0GUZm2QBRNSz4DhGUR24ZJyabIVKAvpUqhIsRCiJxBhUhWU06CTDnx2dCxcBA8SMws5RUpbSggADwAHFjBkGGkEMGAmEGRBaGAhYhI6MDc8QTEKkoBtAF0+PxDAtH9QjwaI9gA3JmAAEy8ASAwINNABxOQAXmQABkpR8f4hESrkIgbZ5Aa7YYyQLJy8kESwOnER5bTy9x27ytrJxPrkAB934yxvWhpgGD0ACEjyuVGGEOaATCdC4vFWBjAgnES2G1mQEAwBWuw0edFU6j0a0MVxmZHBEOGAPojBYYNRlKhHQJum+pgZaIxWJQFMp+nWADokpxBAALOj8kkc4ZnBIXFGUtEM6wKpVKpay+WxOwFKBFQR0Ja1VEIbCzMgFMBEYAAWwgTE4F0u5uQpthJj4AEZxHwAMzzeY+k1msn5cbWu0Op2kshuuEYPgAJh9yETAaDkJDFvDtvtjvxMdd2Hd8N9Kc96Z4S0aSxZUCJiORLop1Lr9MZuUETDGAtpUDbqPRmOxvIQne7EAFGCYAHMJcSkarbGiq+IgA">Playground</a>] </summary>

```ts
interface Callback<T> {
  (error: null, result: T): unknown
  (error: Error, result: null): unknown
}

interface Task<T> {
  (callback: Callback<T>): unknown
}

export function series<T>(tasks: Task<T>[], callback: Callback<T[]>): void {
  let index = 0
  let results: T[] = []

  function next() {
    let task = tasks[index]
    if (!task) {
      callback(null, results)
    } else {
      task((error, result) => {
        //  ^ Parameter 'error' implicitly has an 'any' type.
        //         ^ Parameter 'results' implicitly has an 'any' type.
        if (error) {
          callback(error, null)
        } else {
          results.push(result)
          next()
        }
      })
    }
  }
  next()
}

series([
  cb => setTimeout(() => cb(null, 1), 300),
  cb => setTimeout(() => cb(null, 2), 200),
  cb => setTimeout(() => cb(null, 3), 100),
], (error, results) => {
  // ^ Parameter 'error' implicitly has an 'any' type.
  //       ^ Parameter 'results' implicitly has an 'any' type.
  if (error) {
    console.error(error)
  } else {
    console.log(results)
  }
})
```

</details>

**Comment by jcalz** [comment]
Just to be clear: Note that even though #42620 is listed above as closing this issue, @weswigham says it only fixed the comment before this one, not the whole issue.  So this issue is still a design limitation and is not fixed.
