### ISSUE TITLE
Slow compilation of tagged templates in a single file

### ISSUE THREAD

**Issue by mpk** [microsoft/TypeScript#35503]
**TypeScript Version:**  3.7.3, 3.8.0-dev.20191204

**Search Terms:** slow compilation tagged templates angular

**Code**

```ts
function gql(...args: any[]) {
  return '';
}

export const gqlQuery0 = gql`
  text
`;

export const gqlQuery1 = gql`
  text
`;

// ... etc ...
```

**Expected behavior:** I have a file, which contains about 500 exported tagged templates. First, I use `tsc` to compile the file to ES5 JavaScript, and then I use `tsc` again to compile the generated JS file to other JS file. I expect both steps to take a few seconds.

_Note:_ This process probably looks a bit strange, but it is actually a reduced testcase for problems with Angular CLI build times I encountered. As far as I know, Angular CLI first compiles TypeScript to JS files using `webpack` and `tsc`, and then uses their "build optimizer" webpack plugin to further process generated JS files (parsing and modifying AST using `typescript` package).

**Actual behavior:** For some reason, the second step takes several minutes to complete. It seems the compilation time increases quickly with number of tagged templates:

| Number of tagged templates  | Compilation time (JS -> JS) |
| ------------- | ------------- |
| 100  | 4 s |
| 200  | 10 s |
| 300  | 30 s |
| 400  | 63 s |
| 500  | 132 s |
| 600  | 252 s |

**Playground Link:**

- TypeScript -> JavaScript compiled output: [Playground Link](http://www.typescriptlang.org/play/?target=1&module=1#code/FAMwrgdgxgLglgewgAgOYEcA2AKAdPgQwCdUBnALmQIgE8BtAXQEpkBvYZZIgUxjCJQByQQG5gAX2DBuADwAOCIjGRQkpZRkwAxIgVQBbbhBgAGZAF40WAAYdkIXQaPKdew8bZ3OION0wATO0lrMU5peUVlVQh1K21HdxgARgs4228E52RXJw92Tm9fAKDgELtwhSUVNQ0sHMSAJlTNdPtMj3qs-IKfP0DOYNDkCsjqmNr4t2cAZmabOwcpjvblbsK+krKw2UqomrjO4wAWOcxWxdyXFc8C+yL+5EHyndHo2M1DmABWU-Prz5uPXumyGIyqbwmnwAbL8Fv9rms7hsBqVQS9wfsPisAOywjJLK4EwHrYoorbDdF7cYHFYADjxbSJAMRvVJj1RzwiGOpWIJAE4GRdEtkEV4kWyntsuVT3nUVkkzJYWnCmaLbqyHpKKdKxrLJpckiklfN8ZcRUSWcCyWidRCaQSkk1jWcVWbmWKNSDObtdZD5bNnX9VRaPVb2eSwTK-Q6ToHXcL3eqw1rI777QafnHTQm1UDkeGbT67byDTCs4y3bmSZqOVKi5i5Q7ceWhVlE3mJbXtfWeY2DfSW-CQ0n8ynKWmS4kkgLB8GzZbR13U8W+41FWl422q+KaxHxyv9Y0jRvs1vhx3d4XXg3D84Gk6TxWc+fq1669fe7fjA0A4-W8sXx3N9uw-PVPgaWM-yHedQ0XPdbRvcDMygudhQXTt4J7MCVgaMsUMrQDPWtb1QOjS4GmbfDnxgkcMKvblsIJBoByos8aIvYDl0QnCZ1YgD2NfYj3wYsjEmmddlVPfi0NguiSJE9MxOPSSnzYmTaMveSo0UmYHxU-9CQEoChJAhTJxmX99Og9SOJMrjP0+aZIKs1CulkzThO08zjGmZCXIIoyiILLSJ1XGY8P86ibME4LPNCr8YGmSjIrUtyNM4-duIJaYWJS6S0ts2LTK8sKfN4vLDOi4yivsxjLiOCSTVU-K8ncjKEIclYjmUpqDPNQLkyXTLOoJI49N66yCpiscOrqxIjksibXNa9K7OGubnCOZyloCqqgpmrDRM2vydqiqbqoO0idOOCLTtSlbCsuszSpgI5krulrVjatbZqO45co+yrzv2obfuu17ysB-q9sGzCru875GpdKSgYe6bQcO8Gvh65HmtRr7Vpq9a-u+cbcb69t0bh56Eq+RbycmtGLox+GXq+baGeWgnHpZmnPi+E7Od24HYfokraduoWzqZkHqfF-n3ql+7uapsX4v5gGlc+4lmbl9WVi+SGtfxnXZbVg9oSRoNhZl0WQotlYoRx63pZV3Xzayy4oTJl3ldNu24odgkoXp33tfQjziv14OObDk2I-azGEahQW4+hkW4I9kavcltPKfd+3PcSKFFbz7czcL7Pi81svCIDqOg69o3a4GzPK424xsStzdw++omwYR7FnZ7+O+6e+WcR9kf09ttvA6L5xsVD6f84r+eq8X2OV-L+vapJ7FU+3uu54bhfO9zo-W7k9eO5gbFS8vmGT738HsRrx+M+v0+N875uP9nr+L8Ea0m7ijGebs17f1vrSYeYDV672JuDWkU84E72fog4By9UHH0ARgl6tIt7YKvpHIB+DD5EKfrgge+CL4UM-iQvBCVaQPzoQAhh1CmHv1YRAhBHDPi0j-tw-26C+ErD5KAvG4DhFUKTi9PksDJHwJEbIhKfIUGKLQTI1mqisEaJwewlRnw+SEL0cQxO2ijHkNMZQgxFixG0OsfQ8xfMxEsMcWw5xE9+RcPcTw5Rdj+SCN8dI2xLiHQmAkRTTRoSvEGhMAoqJ+jPHRzieoxJZifqGPlCYXR6SbHJMblOEwJi8lOMyQEuJVjSkePKWEuJDjql+K0XUopbjGkhIKWfZIJgfHtITrU2JRSgl9LHrzQZzhDSRMZk0mJKSpyGkFNMjpAy5kTMdIsrmyz+5ZIdEkXJSz+nbIqfMkpBzRl60KWsqpZzCbj1WcYQ0DSbk8wuV0w0bTnmq3biTQ0vTPkFxvj86cGybYzM6T-ZIDQpmbMOXcy5DyGgJP+ZA0hCVHRpORbwnZBofwgtdlsuFbyIJ4r9rCsZ9zIXXJhecrOt9HRPOpbc8l8LIUfMZS82lPzmIkt7ky15ELHTDMxf4lpEzxI8tHnyzl4M9lIvZV8wFMrpgYvlQCqBPzpj7NVSixhnw9mnO1Vi45YqqWgoJcyt50wGVmrJfyulSUJVSNtdKhGey-mGpFeMh50whUeuaV65IDVHVKP9RSpI3Vg3RPBXSsakakkrJZeGrVNqaXfJlVtONGSjmioeUcU1+LnVptdUca1BbU2KuLWylNUqi0vXDe66tHLa1oqOL6xtCr1Uyq+NC9tarUV6uxpm-JCa3lfBVb2nVoiHR0yHWU7NAakjs1nTU+dYaBbLrBSOgVXxS2kvLZ211Xwq1lprRWutXwG0nqbWetFhsN3mrtT8qEPar0dv7fKJ297C03r1d7L9+730OhDv+09B661QgNROo1ObkgpxA9esDaKoS7t5QhwDpZj17tA+hqcUJL1YbQ7qj9bbX19qI02F9BG33kYNEPeD1Gp20fHaRyd2KpxL3o2Rxj7HIMsegwug+nHWPGoediFDkrCPcYmffIT-Gw1v1k56+TJGqNcbYxMkBinQ2JpgVp2ZOnmOqeEzBpItJk18aUzp3jRm5M6fzTZyzbzaTiadQBmjU5mF6ejT82k+HUMMfUw8gRXmt10vESF1dib5ERcJQKtRMWLVxfMw57TbzjEJcfTKvk9n-NqZE8kPkLmQ36bS5h3LxmF18j8xJgL+XpwqfK7ZrpULKONccxCqFcqoPtdvlCwzbXUsdZyRll1L0oXWYGyVobOWat5Zg1CorUbQskyhWV2bFWKVQuq657D7m7wmAa+tprHWFQjebeBBZs5uuDd6+sq7Fmbsrb2Wdn9OFw0vcQxdmbO3JOBZgIixb8bIvNaSGtn7tX5umY+zhu8wL7spam71qF0O9vfkRSjqTaP+tHZ6yt3F8PJvefBveCbOPHvE4aN94rROEb3kB1m2LSOwfU+WxT7bLPgcdYaId8Hc2A0-la2TxHK3phdYe8L4nyqMd-Z-MlwnrPadOWl-ln8VOluc961a5X82HUE6FzTsbOVtf859cbzbQa9e842yyiCYuEcG4ShBbHVvju9YWmbm3GbLcc8ZytvNHvmsloDx1t6we3fs-V774nraw8re7bH4ng7veR8S71sdCfaczuT0DqPmfScu9x4ntXOfU9x-p8OjXcfmcp8y5niPJfa9jbvdnhnpfifPoz2Nz9LeK+56787n3bfafAZ73OvvjuIOd4n8X1vjeJ-l7H0Prv1eG+jYn-X2fa-wJQh54Puf4Eu5T4P3b+XlfifYgHzXrfOEOOj5XePg-+e9-X6YoJu-m6z+07E0fm-K-N-nZvw317yX0d2xF3yvwAKYk03fwfRf3Il0xgO-U+xwmQR-ygLl31wVzGwITQPgJn2AP3xQIX3vxAPAk80QLc0x3+181wMaGCwoN2yoO50FwL3J1p2iwYN+xV3i04Ih35z5AwNYIl3YKfwgNeyYmy1oLvEKykO-D5D-wILgMaCq1kP+z5HANXzsCAA)
- JavaScript compiled output -> JavaScript: [Playground Link](http://www.typescriptlang.org/play/?allowJs=true&target=1&module=1#code/EQVwzgpgBGAuBOBLAxrYBuAUANwIbygH1CBbXAawgBUISAHAG11ggHkAjAKwlSgF4oAClgALRGCgAySVFHiAdMTKUa9Jiw7dUASigAfPVABmIAHapEAe1NDkly5QAmAGijxcAd10BvTFH9QiEZCmjyw8o4QRoimEAAK8JZ0EPCwAJ4+UKGoEVEx8YnJqWmCdg4QLlDA7h7Art5QeAwgEABcbp5QAL7a6N1QEAyQUA1lTvI1-B0efV1+AfAQsCDwNmMVWF1YEAAedJapYIqEEGAAspaOIAzQAggtWCbmsFY2AOYAjgyCPvP+eAR8G8JAIANoAXSwAWMByEAKIiCmAAY+oREQAeKBAkAkCCmWBHG6mN6iVGIADU5N+0OhQLAoLR4Km2Nx+PpjKhATm0MWy1WUAA5ALNphdvtDvJPgwAGLuN6s2BIqZS4S0RjMNhcMKEACM+kMqrUGuysF1UyUFGoavUmq0sEEoOAAB0bMY5QqoLLcPK8bARi7odFBo4A90XcBwa5HaGjO7fZ64-j-a7-EGGCHXV1w+DtLntnsDgTJV8vT78XqBCqWEaNFrUIQAEz6oTV9W1u2N82kS2qNu2sIO52u2Pej2lj3eUOpxDB0NZ0wRqND1OJv3j+OTlPGGfpufZ3O9UUFiVS9f4puVr6GvsmwgAZmb15tt4fAgtKmtxrr9ujw9XCdHDcp23WdM2zJcY3-M8-U3QMdwzfx5wjA983FItT1XV8oCrT9221AAWR9W2fb9CEIt9uw-Gt+1QQdIMApNoOTODQMQ8CoF-FcGLXf9YICNMELDBcczzI80KODDuPI7Cr2Ir8OwAViI3CaNNJSKOUK1qJNOi-24gCyxg4CBL3YSIL0wyDInYz4NM5DRLFQsJJLVd1Jk745Lw+sADZlO00jfI0nsVJ0zi3X0pi+OnVihMXDjl3CyzIpsmKkJEw9HJPFzuMC9yn3k7UAHY-JvUjiqCqjSrtXSuKS3iUt3MCzPi+i6v0qKQMatjhJQsSnOLGVV3KvLPNUwgAA4SpIjtJoqrSqoHMKRzayyOpMpq4qWqD6q3dbuvsjLj3Q7LDNmkaQtIgBOKaCvra65t7abFoS5axx2liutiyMWost72oawS0t6zLjsG7j7vO-yOx1JUDBbC7oaVB6Eee1q-tWgG7O+raIve-jbI29LUP6yTDJh5VZJR+sdT1OH8q800aa7TTHtun8Xu2-7doJ-bsY53GuY+wH9wco7nLBsmK0hhbqabOnRtvHULyISj5qe2icZW6zudS9jNfR7Whax4GxYG6ClYpjyqcZh95et3UsPfNW2ZqxKDaAnXPrS8zavdpM1p5r6TfEs3Vx1LCcKh7UdUIu2o+p6SndZhnXde+Nks94Xmv19O8eir2RcOkPSYVGPLfpsadSUuOZcZtyk+t1POYxzOsZ9t3c8F-HdZ60Xi5O0u3Mj2vdV8mv1cZ3KG-j9m0c7lujcJ9u08YvPOqzg7iayiXS9y4eJ91Yrx7Zw-meCmem4Fhfu4L7P+a1j3F954OSYH30dWG-eT51Sbj4Z3UzrT1rpfB+-tMZLx+r7eehsb4byJn1be5szpf3-jqa6f9K4QyARPEBfsjKtwgTnVeXd85wJfogsOEMUFjQbLDA0CtSK0LPpVHBRCeIkPXm3SBHdiHX1IcbPur8d6+iYZeK2M9Gy03ofbBsUtsEuzYVZR+sCuGKIzk-IOgiKHcVkeXBhHYGxy2kRIwxzDnYpzUWvPaX1l7Nxgfwwm5DQbQVMWIiut4Gy22MSPTxZjk6qVwdA5RDjea2KvvYzhjitHONXL4tx+jtQNljt4g+SS-GN0sRw6x3tuEr3YXwyJz9onixcdJahHjq4pJPg2euqt-GhXvng5iKjCGNKCWAghRSi5CJcUPSmJix5VP-g2KedSMltN4RE7JesJn5KmYHIGxTQ46L3v0nxR8hk0OGvIixsylEdI0TkzJBTpm926dowyDZP5rNSb-TZHjAFjIvsc+ZPdNp7PUS0rpW8Yk6OQTc6p6D7mMKwU84BLzgmFJsbkuxkLTmbwQb8y5VCAX-zvHQ+GEj0XpOeR8qxCyZlz0mXCglZyfklMwkjaWB87xSMxSPWlOLwV4qyaS95RK5kkrefAkGFLuKMvifbO8Rj6U0uVjsgJEKDlfOhVK-BhzC7kuWYZYVeihVeNFSfO8jswWsJZSctlfMOX7PlTKxZ5ykUKm1WqrFyTNVosTrqhR+rXm33Zb9dppqQmaItXylVZTUVjTvJU+1Qbaks3Gcaz53qjkuq5W6nlpsS6+mDTahlgzQ0vlGRG3FUb8XcrCaAr1ULzVKuTfiO8qzxEMo2Zm0id5tlOt2Xm1lBaYXhPjWQpZ5bYANrTTSu5daOx3keTm5lLaDVtrlc0mNirEV+qtf86tNKgVDu1HeUFY69UTtdXAwtTSA7cqcQulNKLl0n3whi9xpFL1Mu3R64l0rZ13x3Z2gRvrlUKlvYKiR+E6XXo7H+u9zrX1PpLYSh9nKwPwsTf3YR+IgM-pHvhEVAGCLiqbZKuN0HDX7s9TO8DZL52ft9Ch-tF6NVofrPhHVW6QOQZNQRmDeHH3Fpg8ekjCGI6BtvPhO1VHTR8eA82hj0bCPuqgaxpjhqOM9qE0hg++EQ0CbIuG8+47RP5oTSxqDbGZPdrfghvp57-74QzSpszwmsOgb01O7DtmE2ycM7ASzCmL21os42ujInJO6ek3Zmz-nHMGfgy565Jmxr4UHRZ0d6n72+cY4e7T7ai1Ba7R+uTS6LOruy1ZhpgWkt7pSwe8B3ziNybPSphSV6En1mq3l78gSpOFdUfZtL76y3Ofq25-+Cl-21bUnIzD+XNOtuS9OlrUSMtdaluU0iClUMDcIAthr1UJuldlW1ybZXeWcdgCtnrY0FKUaW8d1bqNRuTvG1tjbpbytde4xF28Cl+Oncdd56zl3d2tYK7dudu2e0vfI715Tp21MsPowlsTzHiv4e2z6zroWFLGaq+Z072a4uQ54X5+HsbfudIR-dpHVaqsedO15zHPnseJb+y+r7b6puI+ggpcLVXoundixDqneSacE7x-TnDR6QvM6y6dnLYvzsaxu3ziDUOtPpaZ65SrS3vI1ftqryXs8BcOaK+tmXRGAfOY14d283l+vq6Gx9kbcuxu6+lwqg3SajezZ4wFRb6uMNW8a3rh3EnqfQ-09N0L3llZzY7N5E76vaOU8+zbq7dv8e+9gz01cEfgdjW8q99X72Y-W-9-Ln72v2uM6J9BTP6fTeg-V+D8xsf8+28L3H77JfDfB5RyrtH6uMdc7rzzgPAWi+4-+074PJOVdk-VxTnvee+8F9aYns1w+4Nl9Zyr9n6vOe15n7CwX12F-PoRa3svov1fi9P5rprOPad+9nw3lvI+y-K-toVNXEiX8X594vunTeGc7Yf0NKlMPIqc3N-S3XPb3e3L-G-HfHXDrUvIaF3J7Mqd3N-T3cAtbSAg-I1Qfa-ZPC5BUQqUPV3DsQqSPN-aPafCA-fcTbAn-XfBXeA7iUgivMqLPN-HPSgjA6gmHT-LApzULQqANJAkgqvN-GvepKgnA-XaAjteguAo-IadvZ-TvN-bvLfSQug2A+fKQpPfg6CQqMfZ-CfN-KfdQrgnQqA2g+vePeQ--Jg1fZ-dfN-TfCQ8wzQ4vUJWHZrXAvQoaE-N-M-AIj-TAmgnTXnXQ4XIaJ-CRcaV-EeWI4I7g3DLwq-aQvAy1X0BIk3UicaEA+IsAzgi7dwofb-aw5vP-ZfVcXIlgmaFA+ItAwoqXJIgfYonwyI7icaIg4Q7UcaMg+Iigswooso3-TbZo4LIPaCXomonotg+IjgwYpoiwrAsI-vcYxXDooQlTcaUQ+I8QyNJY0IlI8Iyw3wjopQmIlQ+ItQ1woY2-Gw7Q1otI0406QwmI4w+I0wm4xYx4pPFYufColPDohwmIpw+Ilw-Yn4ywv4u-AE-AzI-w+IwIxExIg4ngkI9jdo06aIkeS6OIg+XElEyE5Yo41YhghQ8GQA4g7US6PI-EgohYrXIkw43gmg54hUGk6Yu6Oo-Ehohky-Y44klkjEiY1cS6LolTS6Po-EgYr4xk4YuQh4+UrQ2EjI-ESUzk00S6WY-E+Y2U-k0kxvJUjwwnckwyLUjUwgS6HY-EvY3NVE5IoUwPdYs084nEy4-E64iEo0komQ1LH09Ik9NU14nE94-Ez4r0u48o0Y+0oXEU8GYEnE0E-E8Eu0pktEsYskuws0hE-EpE3Mwk703A6E+4lUwM2AS6bEg+GGPE7+JEKlCVbfWQ5U6MtMp0xgsmOsi0mGWk2s+kvUx0lowsp4zE0uJERAlTGGbk2s3k-s9Eh0uc2M500c8UpbGGKU2smUiMmA40-nVsxc9s0cx7CcpEbU2s3Urcpsnc2XIciIuMjszY1cpEa02s20jTPcvfGMtYg89+J8rspEd02sz01Mm8qEkk-4k0rM0c4MqspEUM2s8M4CyMkY3ckCvgkcn8hMmCpM2slMt81C5khcr8000cnM2svMsigspChUzwgcoiyCn8ys7+cmDBRWcmZGRC7c-04sqMu7Yi9+Ni6lJins1BJmdivCqi5slCiSq8x3So7iGmcc1ci2Fi0iGmGci8v0ossCmEiCuSyWFc+2GmdckSzcjiy8ri7Sks3SwEyWI8pS08kS88syzStI7i5CpfGy0uMubI6GKuG6ES18+LfC9Mz8zMvSry10qsnUACkSoC8SzirS2isKzy-i6CpiuCkShC+K8yxKwi5KuE8sD+Lsn+fyyuEqsSoK6SiypK2w8K-i0ikS8ixqyihK1yyynijygq2AGmRi1BJhFS6GURFWL3Nw4K+cjM2qlK8sIaoA2WYSyuXRCqrHKq3Kia+-Oq6axSwy0xAa6OVxYa9A241q349q9y2Sqa7q-a2axmXxXa2WUy7Klyk6mq9ai6pWOy7ahyhapyx6krNql60svbJWB87a58vqwK5a460CgG6yrqpWSK7+EZUqxWJGpa7nKGwUvKyauG1GwSvqjKharKyqjGgitawGntJWTCxG7Cvq3C4mnK-6rG16nGhqhapqtmlqhm56pm8m5zJWXqyubFO6m2es4bDQsawcla4cu80ubFHy6ORlYWh2PsjSv67msm2G1U7qgVPGwWqc1BVVNG3vEmkK98-KrW8OAyiRcOYywWh6+mp66GnmzWssm2rsu8L6xWD2zmx2zGjW3i+i8sb2+W6mVNJW8OCG9Grmp2-2zqi21NEOm2GKwWuKh2tWmO0K7G+OtKg2gmr2omyG6Ov2zO5m+Oqmg2mmwWumwu320mku3m0LcOVmr29mlun29O4us2rO12jdLs29cO79A6xouUqW9W+ul2oGwe663UIDAelW5yjuuuru0u12xDXWxWMjAe9SheuHVa8egOja7qsjROme22je+2muxe02iWuiw+mOD662oTAen6tO3exm2O86uG+Tde1SpTZG3+yO42oupem+821ehG1BSzAe1Oy+t+se5ehu82VzH+6GfCPO3+guqO2u6+0ek49C8sNBvuyuje6urBq+8a-euO1e5u3+1u2h9uuBjOhBieim-CAWxWercO7rIevkmGqSk2tsvi8sbh6equeajh+e36xhzu0B7uoGvrLslbLh7eqR7w9+yhz+i2g7FB6OM7Lhi+sh6RkB3BtCmW9+M7E+quT21SoHI2xs7Bih5hg+t62xnR6mZHf+6GDxux8Wkx4xgR-coR7q7xtxuuZOjhmBwxtR+B2Rle+RnOyuFnTx3RzBoBhxyWgJ2+lx8uxJ4hmx0htJ8hjJ4B4Upc8xmhrxuhyphh6Jph2JxBsOBSdh1SjXcO43Hh2cj+30oprJuG9p0Rs3ZJ6mQZnx0avxnBzJsBoGkZ0J0efWyuEPGp1ImJ8ZwRwO7qxZyxtPNpgxwpoxiZkptZu+tPLZ6x6GcvUZo6w54p9J3pi2i52Z6KsGhZwB+xnphPDRw-dZp5rs7ycJlpyJvZ2pmR1ZwJ75v5359B851Jt5-Zxx+plhvm7yHJxWbyPJ85gp2F4F-x65u512tF35qp6ObyTdQ674hF-h3FqZimklrs9-cO9-S58l0Fj8pxqhoGxlx5wqcR1S7lpZgUnF256lvmvlyxwgoZxmcVplkeyZw0ll4VxuqVrls+3l3ZrF5Zup+VuRim5gsVs56OQQ-lg0xUrVuJnVkG62wqZ5xWK1o18CyloV7VkViByuAwiVw+QF9VgVg5x1s1kVhJm1qFg1mF3x2Vk1sNhp+SwqFF3l9Fg1zF0NqluViNxFxVipg1ol6mQqUl4e-U+16801yNsmbNrshI8OrIjp1WuFm595p1xuit0R6o8tyR1+7Fn12tv1+tra62zo91n+FR1tjVkFlN5xuG3tyxqY8ttVxN31mi520di2qYid-V6mcaF+2Btt+Fwt1NpBC1keH+a11S7Yu1nSh1jtot0uY9id-56GcaT1md89lsil9limu90toN1dkNsZkdgtn9zR128aGN29uN1dhN79pN8NiDi99+cadN1dzNxmcaHN3h+d39qDndsOJDrsgk8Ogk6VvN09tD2djD+SvDx5jk3DltjdodwVx9hd12jkyxsUvt5j-Dvhojujl9vm1j8jlV6GdUtj1D0o7d+joGgT8jldxmc0wTrpqwkTrjxu6T8jw9-j15h96t1l59-9sTl1xWS6G96OfTk9qys9jThV82Izpjj9qTr9q54j0zzdsFu+y6IDwzkDqTsDuzzj4Tv9r55zuDqThD3UCs4zjqnz9D0TimkLk+2hGs4ZTsmTz5uT3zgMvbWLi02hHlgxMc0Ls67pszutlxHLmLpEeZjxUr3L6ip9+T7TntWhK2nxJEPjxJJryrySjjgrztorh+xryTxsE8trmS-LxzvFtLgbkrlTlrtT8D+zjrkb8z2JX8krgz+sWhe9mb7z4bmj0p7888f8jL2C912hWz5llLtyqryL5zY7g79z-rzz07iLub7bo5i62hAL-roL2hZDzppL879r2rq7pEZpgxZi4FEH0Wkarzzrud2TtkkRAS6e2RLLxJUSytne+b5Nx7gH0LJHjL5SsHlHgd6j71rdlLuH88C2GL8OI76nxLtl8L2b7HlxWn2Z2RPrtnwb6qoTvz177y1nvypW2RabqHjHyDxnnnrqoXvHlb00WRdbkX57mt6Hkjy5aKvH6zyRE7mVrHrbknpz3n1z1bkqwX8qtH1RxXzTmriXrW2Rd72RT7tBTnve+n63ss+3jL-qgn1boahs9T0XmHpL8n2AQxSk7o735H8Pp39Rl31Lurxa1nnar32X-a33jb5Xhzi3hbnRK6qk735rvPqPlZsn-B4PuJBP9ntJOnrT3X416D88SvhPyb734Xh78X5LnX2Pq7mpD3mXxsXG1PhXvXy34vsx+vgNxhK5I7yfqvq39vtvoPwxQ35P27wxe77Xtvv7obzvnHhsO3hsT7-fwvzVkfsp+v4HxJIWpPxsOWs3wdofj5mPhfm-xHxWq-zxKjqJzPzH+fkv9-jL1VQXobVv7E9a+1XE-rt2D5ACX++fWXtahn5ndTqF3BTi4jgGs9vagA9dp-3v7f9Nu2-FAXu1SRh03+CdYAVgNAEZ9sBXXWJCQJf699PE8vVvrgM37+kn+4-AxH2kAFa8COJnJ7pQLr6QCl+1-FfiOiP7DsO+T-O3r3UAHfcq2-vMAeIN-690Yu-dN-oPQH6MD0+vA8gcgNiRT1c+svWeqoI-5Asv+YvXAQvzXqI9N6qgonmQPzYM9zBv-Y+qzxoxHdXB8AjvswLaKj9g+7glwez2-rqD1+TAxAf91d5pdv6VgpvgYJb7BDNBDg+IeELq5-1lBdA5BkEO4Fhca+9gpIVd2QZWCNeSSLgexwSFyDLuOPQhsoJX5RZRBtHRIXgN0F282GbgmQej1MEB9H+Tg8-qt04Zv9uGGQkodkMI5M9YkIjfQY2AUaC8FGHgjfqEK34L9phrPJRn0NsEmC+B8gn-j4JqQNdUkejPodOzT5lCtBOQhoTogsZLD2erjAYdzzn6OCthrjRHh4ymGxDMheXW4fUIWG6dGECkOgT8NqHtsPhv-P4TFySZTDihNwrwdLVP7B8kmIIlfgpDX6vCkBpQ9oSrwVA1I7eTTI7liJmEhDBhpwy5DiNZ6tM3+7Ta4bJ0hG3loRIyUPiphGQR9ZeMzckb9zmEsDf+MzRHos0F6bNSBaw7QSiPWHlCXEPIzkTAMbAnNeRXrfkUMJ4EjCVkPXVJOXm5GYC+RJwykXgy2EPNOR0Q8US8PxHqjTG1I7yF8IMQQtuRDAuIUcIFHSiCR6IiFjF2RZHdHRuI+oQaNZLsjBBIyFfgSxdFWiZRWQ20SIh9HEjPutLX0aiIoE2iF+YY1nvSzf6ctmRMfN0TtyCZXJaRS2K5AyMbCitJRfvCMccOGG5CceOYxHuK0F5KtEx1fd4X6MDHnglWpYsUVcgOGD8bRyYl7pL11axj2ehrcMYKILGyiixLiHsbGJ1FXI9REI1kd4OpG2sYubrcsRaKRFhDqx+YuUZcjdazjCh0bf4aTwUFbCtxs4lfoVERH6jJxUIiAVcjt4ltyxrQ83n2OtEnCF+JbGLmWzf4VtKxs-Nsfr0l4Ntxhu-LMX+O3FK8axC-aos+LK6MJx2uYw4SuP9FvCQJOw6pJO1fHNiNBNYz8aNzq5LtWea7I7jhN7GtjTxVI88XhOwmjir2UElsWqMIkajqR5ExHm+0F5vt8JVE-ESBLYGJJAOuE8ERSOomGjiJno2DrhOPETjWJv-QSc+M+5YdmJhY5cXeMHGxIpJrPHDm-zI7viEBokrYWR0R4UcVJxgqUSxJuEL9GOSk8CQYh45qTPBvE90ZpIQnDJ1SgvcThZNmEaTqR4nbSezyU5OS8Rhk3-kp20mjirSgE4fruNckmjEkRnByQuJPEuTzxlnJSYUJc5BSH+VYoyZ6Mugr90pSUnAYCM0l28QuDkm8XfwIkxTUx0XWZuiji5BoEuFE1CTBNklRjRI8IVcq4AzEtShUbU39B1JHgKQupB8byL1JPiFQBp-8caMNLGiXQxpisJEJNNUo6gZpg1eaQrUWkJxlpdcVaaPHWkfxNpo02QIZQmm7STE00g6T4jmnHTUkDYdaZ4kun4RLpPUs6dUn6n3ThkQ0p6TQh2kZj9pS2dFOtNpQ-SLpr0l8HeB+k3SAZ9aO6V9MelfSXpX096UKk+n2xL060v9EjP+lLYaMSMkGWjPBkIzIZCM6GQjNhm-p4ZEiarOtL6xkzUZ9sY7GTMxlUzsZJM3GSTPxkkzCZ3U4mSPFVzrSzcXMymRIgjxczaZfM+mRzMZkczmZHM1mX1PZkHwX8607lnLN5kjxSCcswWUrOFkyzRZMs8WTLMlmDTpZJ8WIutNyJGzFZB8XokbNVlmz1ZBszWQbO1kGzdZI0-Wf-FxLrSaSbs02SfElJuzLZXs62S7Ntkuz7ZLsx2eNOdmVw6ym0sclHM9moImuUc32XHP9kRzA5Ec4ORHNDlTTw5rFI6UpVOlKVY5ZVIGaDN8qJyyqyc1iqnNYrpzWKmc2adnNUq0JNpsiZuYXJRrFzVySSZuRXMblVzG5NcxuXXMGoNzoY30kuQrXzmGVhUm07VDPLLle0e5o8vuaPIHmjyh5CtEedHERnjyE4k8x+m3N-odzDKfGTaUplPnLyt5q8reevITibz3GucwyuTJ3l1wD5XjI+dbReybTkcX8i+e4yvnuMb5dcO+ZPAfnW1uZz8uZptP5kQLoq88lpovOJa-zJ4-8yeIAtHjALD4oC-dvLJgWEFNpys3BXAuhhWt8FSCw+CgsPhoKP4GCn+FgqrLGyYFnRbae-P3ZrttpCC1dmQp-gUKf4VCpDptNdkwL3ZQi1+YZxYVVktSAijhVJy4UucBFVCispdMjkQLMuSi0Rat3jkqKTySi6Rf1zIXHclFaCr7pdJhgmK95J09RbL3DgmKiFKPXRXLxMUULbeJijBSH0uktyVFhidxeIuqRdzPF9ikZO4qcW793FriseRmN+kqLp5USnxcMg9qXTg0CS-RQ2gSVGKN010uhdUmRkqKUM102JTQhPk5L7FZma6U4qizXTXFpMlRU-IzELZbp+SipLYp6H2Kfht0pxQiNumuLOZKi8BRmJDyXToFfSppYyPsV-MBlTitFgMtcWyyVFOCjMXgtmUNLGEghS6SQtmX6Lo2qyoxdm0umGyVFDCjMUwv2VLKDEbC-ZfYrva7KnFsHXZa4sEUfTzFqSMUpdO9kqLJFby+xfpxeVOL0pLyjBRVKwBAA) (demonstrates long compile time)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
I can't repro this using `tsc`. What commandline are you using to measure these compile times?

```
D:\Throwaway\allowjstest>dir a.js
 Volume in drive D is Development
 Volume Serial Number is 6008-0100

 Directory of D:\Throwaway\allowjstest

12/17/2019  11:36 AM           616,823 a.js
               1 File(s)        616,823 bytes
               0 Dir(s)  211,612,876,800 bytes free

D:\Throwaway\allowjstest>tsc --diagnostics --allowJs --noEmit a.js
Files:            77
Lines:         46712
Nodes:        237948
Identifiers:   79868
Symbols:       61559
Types:         15356
Memory used: 127117K
I/O read:      0.04s
I/O write:     0.00s
Parse time:    0.50s
Bind time:     0.29s
Check time:    1.06s
Emit time:     0.00s
Total time:    1.85s
```

**Comment by mpk** [comment]
It seems that `tsc` has to emit result into a file to reproduce the issue (with `--noEmit` flag I get same results as you), i.e.:

https://gist.github.com/mpk/f0b501d5aa2ef6e3177703cc2e789971

```
 tsc .\a.js --diagnostics --allowJs --outFile result.js

Files:            6
Lines:        25218
Nodes:       119187
Identifiers:  43226
Symbols:      28604
Types:         8314
Memory used: 82456K
I/O read:     0.01s
I/O write:    0.00s
Parse time:   0.54s
Bind time:    0.46s
Check time:  24.70s
Emit time:    0.14s
Total time:  25.84s
```

Btw, in Angular CLI, most of the time is spent on this line:
https://github.com/angular/angular-cli/blob/8.1.x/packages/angular_devkit/build_optimizer/src/helpers/transform-javascript.ts#L176

**Comment by RyanCavanaugh** [comment]
```
D:\Throwaway\allowjstest>tsc --diagnostics --allowJs --outFile out.js a.js
Files:            77
Lines:         46712
Nodes:        237948
Identifiers:   79868
Symbols:       61592
Types:         15538
Memory used: 143047K
I/O read:      0.04s
I/O write:     0.00s
Parse time:    0.51s
Bind time:     0.41s
Check time:    2.46s
Emit time:     0.21s
Total time:    3.58s
```
What does `tsc -v` report for you?

**Comment by mpk** [comment]
`tsc -v` reports `Version 3.7.3`. I've also tested `3.8.0-dev.20191221` and various Node.js versions (10.18.0, 12.14.0, 13.5.0), but the results are the same.

Here is the run with `--prof` flag:
https://gist.github.com/mpk/1f4c105e40e59054065f2123253aa53c

**Comment by mpk** [comment]
Closing, this is no longer an issue with TypeScript 4.1
