### ISSUE TITLE
Move ts.optionDeclarations data into JSON

### ISSUE THREAD

**Issue by colbyrussell** [Microsoft/TypeScript#3551]
If you open commandLineParser.ts, what you'll find is that the first 48% of the file is taken up by a definition that really wants to be JSON.

See also #3549

**Comment by DanielRosenwasser** [comment]
> what you'll find is that the first 48% of the file is taken up by a definition that really wants to be JSON

It wants to be JSON but 

```TypeScript
```

**Comment by colbyrussell** [comment]
> It wants to be JSON but [...] isn't JSON.

Right, and neither is the `Diagnostics` stuff itself in diagnosticInformationMap.generated.ts.  And yet diagnosticMessages.json exists.

> we'd have to build a translation layer

No.  The translation layer already exists in processDiagnosticMessages.ts, which operates on the two aforementioned files.

"I don't want to spend any time on this" is something I can appreciate, but is it also the intent of the TypeScript project to also say, "we're not going to accept any patches even from anyone else who would"?  The only reason there's not a pull request already sitting here waiting for review is my inability to locate the generator in processDiagnosticMessages.ts this morning.  I just started off to work on this as of my last comment on #3549 a few minutes ago...  

This is data, not code.  It doesn't belong embedded in this file.

**Comment by mhegazy** [comment]
@colbyrussell this is a JSON object but it has a contextual type attached to it. 
```ts
 export var optionDeclarations: CommandLineOption[] = [
```
this allows us to use our tools to do things like rename, find all refes, etc.. which is helpful.

The size of the object is not big enough to warrant moving it out. I also do not see any user/functional benefits for taking this change.

**Comment by colbyrussell** [comment]
> @colbyrussell this is a JSON object but it has a contextual type attached to it.
> 
>  export var optionDeclarations: CommandLineOption[] = [
> 
> this allows us to use our tools to do things like rename, find all refes, etc.. which is helpful.

... how does this differ from diagnosticMessages.json?

**Comment by mhegazy** [comment]
These are two different issues. the reason diagnostic messages is in a .json file is we are creating the id automatically. putting it in a .json file makes it easier for the script to access it.
We had a list of requirements, that generating the file seemed like the best choice, we wanted:
- the id of the message to tell you what the message text is
- we wanted the compiler to check the usage of the messages and flag any wrong flag names
- we did not want to have two files, i.e. an interface, and implementation, cause we did that and it was hard to manage

**Comment by colbyrussell** [comment]
I'm reminded of why I avoid GitHub when I do open source.

*shrugs*

[So long, TypeScript](http://soledadpenades.com/2015/02/18/how-to-keep-contributors-when-they-are-not-even-contributors-yet/).

**Comment by mhegazy** [comment]
I am sorry you feel this way. It is our intention to shutdown contributions, we would be happy to have you as a TypeScript contributor, in any capacity you choose.. also we always welcome feedback for our process, or interactions. Give us another try with bug report or PR..

**Comment by DanielRosenwasser** [comment]
In addition to the reasons @mhegazy mentions, tsc.exe needs to support other languages, and so we need to be able to normalize into an XML format for processing and swap out different `diagnosticMessages.d.ts` files.

"I don't want to spend any time on this" is not at all my intention. It is simply a matter of using the right tool for the job. Sorry if my initial response came off as a little terse. We still feel the same regarding the decision on this issue, but as I first mentioned, we appreciate you taking the time. We always try to be open to issues and pull requests.

**Comment by colbyrussell** [comment]
Thanks for the disproportionately warm response, and apologies about the curtness of my last message.  Resuming audit.  Will comment on this topic in coming days and follow up with PRs, docs, tests, other changes corresponding to my notes soon after.
