### ISSUE TITLE
Compiler option "types" cannot be empty

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#35526]
The [documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) states

> Specify "types": [] to disable automatic inclusion of @types packages.

However that does not seem to work.

**TypeScript Version:**  3.7.3

**Search Terms:** typescript compiler option types empty

**Code**

```json
{
    "compilerOptions": {
        "types": []
    }
}
```

**Expected behavior:**
Does not import types from node_modules.

**Actual behavior:**
> Using tsc v3.7.3
> error TS6044: Compiler option 'types' expects an argument.

**Comment by RyanCavanaugh** [comment]
I can't reproduce the issue:
```
D:\Throwaway>type tsconfig.json
{
    "compilerOptions": {
        "types": []
    },
    "files": ["a.ts"]
}
D:\Throwaway>tsc

D:\Throwaway>
```

**Comment by danielrentz** [comment]
Confirmed. Happens only when using grunt-ts, which seems to call tsc via command line, which then seems to hit #18581

**Comment by danielrentz** [comment]
I have reported the problem to the grunt-ts project. https://github.com/TypeStrong/grunt-ts/issues/442

**Comment by nycdotnet** [comment]
This can be closed @RyanCavanaugh - it is grunt-ts specific.  Thanks.

**Comment by RyanCavanaugh** [comment]
Thanks!
