### ISSUE TITLE
Object is possibly 'undefined' while strictNullChecks is false?

### ISSUE THREAD

**Issue by akafaneh** [microsoft/TypeScript#35523]
**TypeScript Version:**  3.7.3

**Search Terms:**
Object is possibly 'undefined'.
create react app, CRA, create-react-app

**Code**

```ts
  public loadUserProfile = flow(function*(this: UserInfoStore) {
    this._isLoading = true;
    const getUserQuery = new GetUserProfileQuery();
    const profileInfo = yield this.dispatcher.send<Result<ProfileInfo>>(getUserQuery); 
    if (profileInfo && profileInfo.isError) {
      this._profileError = 'loadError';
      this._isLoading = false;
      return;
    }
    this._userInfo = profileInfo.data;
    this._isLoading = false;
  });
```

**Expected behavior:**
Compile without errors
**Actual behavior:**
Object is possibly 'undefined'. (this line  **if (profileInfo && _profileInfo_.isError) {**
**Playground Link:** (not a playground but to state what tools i'm using) React, CRA, Mobx-React

**Related Issues:**  #29642 ?

<details>
  <summary>compilerOptions</summary>
  
    "baseUrl": "./src",
    "rootDir": "src/",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": false,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "removeComments": true,
    "strictNullChecks": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": false,
    "strict": true,
    "forceConsistentCasingInFileNames": false,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noEmit": true,
    "jsx": "preserve",
    "types": ["reflect-metadata", "node"],
    "isolatedModules": true
</details>

**More Details**: I updated typescript to 3.7.3 after CRA released the scripts needed to support it ```"react-scripts": "3.3.0"``` and all worked fine and now I can use optional chaining and nullish coalescing but now I'm getting a compiling error that is stated above, though I'm checking for the object before accessing the key on it. and for some reason the ``` "strictNullChecks": false``` in my tsconfig.json file is being ignored? the related issue states that there is something similar that is not fixed yet but my case is that with the strict checking turned off i still get such error.

Thanks.

**Comment by RyanCavanaugh** [comment]
We need a self-contained repro to be able to look at these sorts of issues

**Comment by AbboudAfaneh** [comment]
@RyanCavanaugh understandable, i'm working on it to try to reproduce it in a stand alone repo.
