### ISSUE TITLE
typescript tag template literal compile error

### ISSUE THREAD

**Issue by MonsterStorm** [microsoft/TypeScript#35527]
Hi, I got an error **Error: Unterminated template literal** when compiling tagged template literal: 

**ERROR**
```
{ 
  code: 1160,
  category: 1,
  key: 'Unterminated_template_literal_1160',
  message: 'Unterminated template literal.',
  reportsUnnecessary: undefined,
  elidedInCompatabilityPyramid: undefined 
}
```

**SOURCE CODE** 

```
import * as ts from 'typescript';
const scanner = ts.createScanner(ts.ScriptTarget.ES2015, true);

scanner.setOnError((err) => {
  console.error(err);
});

scanner.setText('const a = 1; console.error(`${a}`);');  // <--- tagged template literal

do {
  scanner.scan();
} while (scanner.getTokenPos() < scanner.getTextPos());
```

is this a bug and how to solve this problem?

Thanks.

**Comment by RyanCavanaugh** [comment]
You can't unconditionally invoke `scan` and get a correct result; this is not how the API is designed. See the code in `parseTemplateSpan` in `parser.ts` for an example of how the parser and scanner interoperate for the specific case of template literals.

**Comment by DanielRosenwasser** [comment]
This is actually inherent to how ECMAScript as a language is specified. There is no way to run a scanner without having some current syntactic context driving it.

> The source text of an ECMAScript Script or Module is first converted into a sequence of input elements, which are tokens, line terminators, comments, or white space. The source text is scanned from left to right, repeatedly taking the longest possible sequence of code points as the next input element.
>
> There are several situations where the identification of lexical input elements is sensitive to the syntactic grammar context that is consuming the input elements. This requires multiple goal symbols for the lexical grammar.

See https://tc39.es/ecma262/#sec-ecmascript-language-lexical-grammar
