### ISSUE TITLE
use declare module, Execute the file error.

### ISSUE THREAD

**Issue by qq645381995** [microsoft/TypeScript#35525]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
no error 
**Actual behavior:**
![image](https://user-images.githubusercontent.com/7971419/70230678-cd498400-1793-11ea-8d53-ddf4abf409eb.png)

**Playground Link:** 
download this [typescript-demo.zip](https://github.com/microsoft/TypeScript/files/3926526/typescript-demo.zip)

```
yarn demo
```

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Please provide a self-contained repro; we do not run arbitrary commands from zip files.

**Comment by qq645381995** [comment]
> Please provide a self-contained repro; we do not run arbitrary commands from zip files.

https://github.com/qq645381995/typescript-demo
