### ISSUE TITLE
When using aliased intersection types, intellisense shows the constituent types and not the alias name

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#35537]
**TypeScript Version:**  3.7 && playground
**Search Terms:**
intersection type alias

**Code**
When using a intersection type with an alias, you expect the intellisense label to show the name of the alias, not the constituent types.

In the following example, I would expect to see the label as "C", however TypeScript reports the type label as "A & B"

![image](https://user-images.githubusercontent.com/12656294/70305055-7b6a3200-1857-11ea-8d7a-cc2f14ea81b1.png)

However, when using interfaces which extend multiple interfaces, you see the interface name:
![image](https://user-images.githubusercontent.com/12656294/70305144-c3895480-1857-11ea-8e7c-4b11279b2da2.png)

**Expected behavior:**
Type alias intellisense should function the same as interface intellisense 

**Playground Link:** 

[Intersection types with type alias](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=1&pc=5#code/C4TwDgpgBAglC8UDeBYAUFTUBmB7XAXFAM7ABOAlgHYDm6AvuuqJFAEILLpZQBGAhmSKlKtBkzQtoAYU5wAZOwnYArlQDGwCrio58ACgFCo0gJRcMWBkA)

[Interfaces](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-IwD2RAXMgM5hSgDmuAvrrqJLIigEKa4HIBGcKOSo0Q9HExwtw0eEmQBhZBAAekEABMKaADTJuGZFObScMAK4gEYYERCESACkHClASh5mGQA)

**Comment by MartinJohns** [comment]
Relevant / duplicate (?): #34556

**Comment by jcalz** [comment]
Please note that you're talking about [*intersection types* (`&`)](https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types) and not [*union types* (`|`)](https://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types).

**Comment by alshdavid** [comment]
Thanks for the heads up, I have updated the ticket accordingly

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. When you over over `C` you see `C`'s definition; saying "`C` is `C`" is not a useful hover. Interfaces don't have a useful right-hand-side thing to show here, so `interface C` is sort of the best we can do.

When you invoke `foo`, you see the alias as expected, which is the place where it is useful:
![image](https://user-images.githubusercontent.com/6685088/70463968-ca3fe380-1a72-11ea-883c-a6658dd4559d.png)
