### ISSUE TITLE
TypeError: Class constructor BaseAPI cannot be invoked without 'new'

### ISSUE THREAD

**Issue by andreafalco1991** [microsoft/TypeScript#35539]
Typescript: 3.6.3

After i have generate the api.ts with openApi Generator 4.2.2 i found the error "TypeError: Class constructor BaseAPI cannot be invoked without 'new'".
After some hours of debug i found the probable problem.
There is a function called like "xxxPublicxxx".
If i remove "Public" from the function name it seems to work correctly.

One more info:
the function belong to a class defined like "export class Aaa extends BaseAPI {"
and doesn't have the constructor because the constructor is inside BaseAPI.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by benmccann** [comment]
I hit this as well. I had `"target": "esnext"` in my `tsconfig.json`. If I removed that then it worked
