### ISSUE TITLE
Should process parenthesized argument as well with type-predicate-guards

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#3553]
```typescript
if (isV(m)) { // this works
    m.m;   
}

if (isV((m))) { // this doesn't work
    m.m;   
}
```

**Comment by DanielRosenwasser** [comment]
Given the contextual typing issues we had with parenthesized expressions, I'm inclined to call this a bug, though I don't necessarily see why you'd have an identifier wrapped in parentheses other than those of a call.

**Comment by zhuravlikjb** [comment]
I was just testing around how type-predicates work in their current implementation, to understand this mechanism better. Surely this is a border case, and it's not very likely that someone will write such code intentionally.

**Comment by mhegazy** [comment]
This is the same in cases of `typeof` type gurards as well.
```ts
if (typeof x === "number") {
    x // is a number
}

if (typeof (x) === "number") {
    x // not a number
}
```

type guards have a limited support, and that is by design, similar to `==` support.
