### ISSUE TITLE
Control over the return value for optional chaining operator in negative case

### ISSUE THREAD

**Issue by reforms** [microsoft/TypeScript#35547]
## TypeScript Version: 3.7.2
The idea is to give control over the return value for optional chaining operator  in negative case. Now is always **undefined**.

## Search Terms
chaining optional operator, Vue integration, 

## Code
```typescript
type SomeType = {
    id: string;
    payload?: {
        name: string
    };
}

function getName(data: SomeType): string | null {
    return data.payload?.name; // string or undefined, wanted string or null
    // yes, i can write so
    // return data.payload?.name ?? null;
}

// Expected after compile void 0 -> null
// function getName(data) {
//    var _a;
//    return (_a = data.payload) === null || _a === void 0 ? null /** now void 0*/ : _a.name;
// } 
```

## Why it's important / Usage cases

Web development framework such Vue requires for reactive properties to be set to **null**, but not **undefined**. When we started to use optional chaining operator we got a problem - all properties wich initialized with absent value become non reactive :(

```typescrypt
@Component({
    template: 'some template here'
})
class Page extends Vue {

    lastUsufullInfo = "";

    created() {
        this.lastUsufullInfo = this.getCache()?.lastUsufullInfo;
        // here this.lastUsufullInfo become undefined, but wanted null;
    }

    getCache(): {[key: string] : string} {
        // some code here
        return {};
    }
}
```
## Control over in tsconfig.json
Our idea is set compiler property inside tsconfig.json file. For example:
```json
{
  "compilerOptions": {
       "optionalChainingOperatorReturnValue": "null", // default is undefined
   }
}
```

**Comment by MartinJohns** [comment]
This would violate the following point of the checklist you omitted from your issue:

> [ ] This feature would agree with the rest of TypeScript's Design Goals.

Specifically this goal:

> Align with current and future ECMAScript proposals.

With your suggestion `a?.b` will compile to something other than `a?.b` when targeting ES2020 (#35510).

**Comment by saschanaz** [comment]
You alternatively can do this:

```js
return data.payload?.name ?? null; // will return null instead of undefined
```

**Comment by reforms** [comment]
> Align with current and future ECMAScript proposals.

Yes, it's true. Yes, you are right and i am understand.
However, the problem exists. It's triple value problem. Look at example below

```typescript

const tripleState = someData?.value;
// now tripleState variable maybe undefined, null or somthing meaningful

```

Its creating the terrible and hidden problems for frameworks like Vue, JSON, ServerSide JSON deserialization and so on. Yes, i'm undestanding that it's not easy to fix, may be imposible. But i'm thinking, it suggestion make TypeScript better and more reliable. Thank you for time to me.
