### ISSUE TITLE
Typescript 3.7.3 decorator won't auto complete

### ISSUE THREAD

**Issue by jonopus** [microsoft/TypeScript#35555]
**TypeScript Version:**  3.7.3

Typescript 3.7.3 decorator won't auto complete
**Search Terms:**

**Code**

```ts
// selecting autocomplete should add `import { computed } from "@ember/object";` from @types/ember

class Index {
    @computed/* ctrl + space here offers suggestions in typescript@3.6.3 but not in  typescript@3.7.3 */
    get foo() {
        return '';
    }
}

```

**Expected behavior:**
Should suggest decorator

**Actual behavior:**
No suggestions are offered.

**Playground Link:**
https://github.com/jonopus/ts-test/blob/master/index.ts

**Related Issues:**

**Comment by charlzyx** [comment]
maybe same issues https://github.com/microsoft/TypeScript/issues/35521

**Comment by charlzyx** [comment]
looks like fixed.   #35521

**Comment by DanielRosenwasser** [comment]
Have you tried `typescript@next`?

**Comment by DanielRosenwasser** [comment]
Feel free to open another issue if you're able to reproduce the problem!
