### ISSUE TITLE
Add name safety to default exports

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#35569]
## Suggestion

When using TypeScript, I tend to avoid default imports/exports because they can be named anything by default.

It would be nice if TypeScript enabled a method to annotate a default export to ensure it's imported with the expected name

```typescript
// @ts:defaultExportName="myDefault"
export default 'foo'
```

Where consumers would be required to use the annotated default
```typescript
import myDefault from './my-default'
```

Where this would result in an error or warning

```typescript
import myDefaultt from './my-default'
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> Where consumers would be required to use the annotated default
> 
>     import myDefault from './my-default'
> 
> Where this would result in an error or warning
> 
>     import myDefaultt from './my-default'

Why force the user to use a specific name? What would you as the library author actually gain from it? And what if the user already has a `myDefault` name in the scope?

It sounds more like you want a linter for your own source code that enforces a specific pattern.

**Comment by RyanCavanaugh** [comment]
Enforcing naming conventions is the job of a linter
