### ISSUE TITLE
useDefineForClassFields flag for different output

### ISSUE THREAD

**Issue by agrozyme** [microsoft/TypeScript#35563]
**TypeScript Version:**  3.7.3

**Search Terms:** useDefineForClassFields 

**Code**
See this small repo 
[Base Class](https://gitlab.com/agrozyme-package/JavaScript/base-class)

after clone the repo and `npm i `, run `npm test`
then change `"useDefineForClassFields": true` in tsconfig.json and run `npm test` again

**Expected behavior:**
useDefineForClassFields = false
```
Y { xf: 'FALSE', xfr: 'FALSE', xa: 'TRUE', ef: 'ey', efr: 'ey' }
```
**Actual behavior:**
useDefineForClassFields = true
```
Y {
  xf: undefined,
  xfr: undefined,
  xa: undefined,
  ef: 'ey',
  efr: 'ey' }
```
**Playground Link:** 

**Related Issues:** https://github.com/microsoft/TypeScript/pull/33509

**Comment by RyanCavanaugh** [comment]
Please post a self-contained repro here; we cannot run commands off arbitrary repos to demonstrate these sorts of bugs.

**Comment by agrozyme** [comment]
Here are the screen captures.

![00](https://user-images.githubusercontent.com/13079345/71324282-0ade3900-2518-11ea-8df6-c16d7043880d.PNG)
![01](https://user-images.githubusercontent.com/13079345/71324283-0b76cf80-2518-11ea-89f3-3624bad459e3.PNG)
![02](https://user-images.githubusercontent.com/13079345/71324284-0b76cf80-2518-11ea-83bd-63c66d30cf2e.PNG)

**Comment by agrozyme** [comment]
I find the solution, use `declare` keyword.

```
  abstract class X extends Base implements YI {
    declare xa: string;
    declare xf: string;
    declare xfr: string;

    protected ef: string = 'ex';
    protected readonly efr: string = 'ex';

    protected get ea() {
      return 'ex';
    }

    static z() {
      return 'X';
    }

    type() {
      return X;
    }
  }

```
