### ISSUE TITLE
Add support value by default for generic type

### ISSUE THREAD

**Issue by FrontendMetis** [microsoft/TypeScript#35565]
Hi, why do I need use the hack for get required type
```
// It's bad looking for reading code...
const Component = <T = never, requiredT extends T = T>(props: requiredT) => { };

Component({ name: 'value' }); // Error
Component<object>({ name: 'value' }); // Success
```

I want just write simple code to can other people understand for example

 ``` const Component = <T = never>(props: T) => { }; ``` 
or 
 ``` const Component = <T!>(props: T) => { };  ```

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
