### ISSUE TITLE
Duplicate identifier error caused by lib.dom.d.ts 

### ISSUE THREAD

**Issue by SkeLLLa** [microsoft/TypeScript#35578]
**TypeScript Version:**  3.7.3 & 3.8.0-dev.20191207

**Search Terms:**
Duplicate identifier, lib.dom.d.ts
**Code**

```ts
/// <reference types="node" />
declare global {
    class URL {
        hash: string;
        host: string;
        hostname: string;
        href: string;
        password: string;
        pathname: string;
    }
}
```

```json
{
  "compilerOptions": {
    "target": "ESNEXT",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true
  },
  "files": ["./index.d.ts"]
}
```

Actually I've tried various tsconfig options, including target es6, with 
```
  "exclude": [
    "node_modules",
    "node_modules/typescript/lib/lib.dom.d.ts"
  ]
```
but nothing helped.

**Expected behavior:**

No error during compilation should be thrown. Or at list it should respect `tsconfig` `exclude` section and not use that `lib.dom.d.ts` if it's excluded.

**Actual behavior:**

```
node_modules/typescript/lib/lib.dom.d.ts:16073:11 - error TS2300: Duplicate identifier 'URL'.
```

**Related Issues:** https://github.com/microsoft/TypeScript/issues/20595 https://github.com/Microsoft/TypeScript/issues/5585 https://github.com/microsoft/TypeScript/issues/4168 https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960

**Comment by RyanCavanaugh** [comment]
You need to set the `lib` setting in your tsconfig to exclude DOM typings. `exclude` only acts as a filter on `include`; this is the intended behavior.

**Comment by SkeLLLa** [comment]
@RyanCavanaugh what shoud I put to `lib`? I've tried `es6`, `esnext` and other values. Seems it's a possibility only to add libraries, but not exclude.

**Comment by fatcerberus** [comment]
If your tsconfig has a `lib` field, then TypeScript should *only* use those--the automatic defaults don't apply.  It's possible you have a `<reference>` somewhere in your project that directly or indirectly pulls in `dom`?

**Comment by SkeLLLa** [comment]
@fatcerberus No, there are no references to dom. The only reference is to `node`, but I've added it in order to check if it helps or not.

**Comment by SkeLLLa** [comment]
It's not a question. It's a bug. @RyanCavanaugh

**Comment by viggyfresh** [comment]
I'm coming across this same issue and am totally stumped - I've literally grep-ed the relevant `node_modules` folders for references to `lib.dom.d.ts` but _cannot_ get it to stop interfering with  typechecks. @SkeLLLa were you able to figure this out?

**Comment by SkeLLLa** [comment]
@viggyfresh It's a typescript bug, so there's only one option - to define something `MyURL` class or interface and use it unless someone will fix this one. 
cc @RyanCavanaugh

**Comment by viggyfresh** [comment]
Right after I posted this, had a breakthrough - the /// <reference syntax uses “dom” as the lib text, not lib.dom.d.ts. For posterity, if you are mysteriously including lib.dom.d.ts, search your node modules for a package that contains that reference...you might be surprised.

**Comment by SkeLLLa** [comment]
@viggyfresh, yes, that's true. But according to typescript docs it shouldn't use 'dom' library unless there are something except it is set in `lib` section of tsconfig file. However we have what we have.

Probably you should post another issue describing what you've found. Maybe then it will get more attention.

**Comment by hansgfixed** [comment]
Anything new on this? Facing the exact same issue.

**Comment by SkeLLLa** [comment]
@hansgfixed there's just a workaround, and you need to create your own class for URL with name like `myTSURLWorkaround` and use it.

**Comment by nvegater** [comment]
Any news on how to fix this?

**Comment by bluenote10** [comment]
@viggyfresh Thanks for pointing that out -- has helped to narrow down the problem.

> Any news on how to fix this?

I've posted a follow up issue [here](https://github.com/microsoft/TypeScript/issues/43990)

**Comment by TomJerry56** [comment]
> You need to set the `lib` setting in your tsconfig to exclude DOM typings. `exclude` only acts as a filter on `include`; this is the intended behavior.
With react-native@0.71.7, Without adding "lib":["dom'] it is throwing error to include dom in lib but on adding lib option in tsconfig is actually causing d.ts errors in my case.  Any comments?
