### ISSUE TITLE
incorrect function matching inside interface

### ISSUE THREAD

**Issue by smmoosavi** [microsoft/TypeScript#35572]
**TypeScript Version:**  3.7.2 & 3.8.0-dev.20191207

**Search Terms:**
interface function
**Code**

arrow function and simple functions inside interface has different behavior and simple functions optional parameter matching is incorrect

```ts
interface X {
  xxx: (x: number) => void;
}

interface XX {
  xxx: (x: number, y?: number) => void;
}

interface XXX {
  xxx: (x: number, y: number) => void;
}

interface Z {
  zzz(x: number): void;
}

interface ZZ {
  zzz(x: number, y?: number): void;
}

interface ZZZ {
  zzz(x: number, y: number): void;
}

let x: X = {} as any;
let xx: XX = {} as any;
let xxx: XXX = {} as any;

let z: Z = {} as any;
let zz: ZZ = {} as any;
let zzz: ZZZ = {} as any;


x = xxx; // correct error
xx = xxx; // correct error

z = zzz; // correct error
zz = zzz; // no error. why? it should be like xx = xxx and have error

```

**Expected behavior:**

`zz = zzz` have an error, same as `xx = xxx`

**Actual behavior:**

`zz = zzz` have no error.

**Playground Link:** 

[playground]

**Related Issues:** 

I couldn't find it.

[playground]: http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191207&ssl=37&ssc=10&pln=37&pc=1#code/JYOwLgpgTgZghgYwgAgBrIN4ChnIB4EBcyAFHsSAK4C2ARtAJTIC8AfMgG4D2wAJgNxYAvliyhIsRClTpsuAuVKKqdaABpkATwD8FGvShM2nHgOGjx0eEjQzMOfESV7VUDZpcGj7bn0EixcCspZAAte1wAL2iyT0ZiXzMAy0kbUPC5ZGjI2OQVA3ddPP14kz9zQIlrFHSMh2zc-PUtOMME039RABsIMHxidGZMIWQ4AGdRkE1BHr6nOyGMEfHJ6axZx0UZQeHRibgpwXXerOJwxeX9w+O+6LPz3ZWDtY3s+4elvdWjvBZNwQIfwUR0if2ygmiYOi-GQAHpYcgAO4ACx0yGAfTGyK4lC6vGQ9GQXWAAGsUIDmApJvjkStoFAuFAsEA

**Comment by alirezamirian** [comment]
I believe this is because of [strict-function-types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types) flag.
Especially note this:
> The stricter checking applies to all function types, except those originating in method or constructor declarations. Methods are excluded specifically to ensure generic classes and interfaces (such as Array<T>) continue to mostly relate covariantly.

If you disable `strictFunctionTypes`, neither `xx = xxx`  nor `zz = zzz` raise an error.  but if it's enabled, it only raises an error for `xx = xxx`, because functions in `ZZ` and `ZZZ` are defined as methods.
