### ISSUE TITLE
Please provide a Visual Studio installer for TypeScript 3.7.3

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#35575]
https://github.com/microsoft/TypeScript/releases

There are a bunch of fixes by @sheetalkamat that we'd like to check to see whether it fixes some persistent intellisense failure in Visual Studio.

Thanks!

**Comment by orta** [comment]
I believe it has got shipped today: https://github.com/microsoft/TypeScript/issues/32729#issuecomment-563323490

Thanks for the issue

**Comment by HolgerJeromin** [comment]
Still not linked from http://www.typescriptlang.org/#download-links :-(
