### ISSUE TITLE
Nullable return types for functions (and getters)

### ISSUE THREAD

**Issue by rosenbjerg** [microsoft/TypeScript#35577]
## Search Terms

nullable return type, optional return type

## Suggestion

I would like to be able to indicate that a function or getter returns a nullable type using `?` instead of having to apply `| undefined` to the return type in the function signature.

I believe it increases orthogonality of the language, as `?` is used to indicate that fields and input arguments to functions are nullable. It would therefore seem logical to be able to use this operator form function return types as well.

## Use Cases
It seems odd that I have to use `| undefined` for the return type of functions when I can use the `?` operator for fields  (and input arguments). To me, the semantic meaning of `?` would be the same in both cases, signifying that the value might be `undefined`, so I think that it could make the language a bit better.

## Examples
I would like to be able to write
```javascript
public doStuff(myParam?:number) : number? {
    if (myParam !== undefined) return 42 + myParam;
}
```
instead of
```javascript
public doStuff(myParam?:number) : number | undefined {
    if (myParam !== undefined) return 42 + myParam;
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
See #7426 where this was discussed at length and decided against

**Comment by rosenbjerg** [comment]
That discussion seems to be about 
`public doStuff(myParam?:number) : void`
vs
`public doStuff(myParam:number?) : void`
but this one only concerns the return type of functions and getters.
I have updated my examples to make that clearer

**Comment by RyanCavanaugh** [comment]
We don't have special syntax for type annotations that only works in certain positions and would not add such a thing.

**Comment by rosenbjerg** [comment]
That is very understandable.
I just find it odd that I can use `?` at the end of the type declaration of a field, but not at the end of the return type of a functions signature, to indicate that the value might be null/undefined.

Thank you for your answers.
