### ISSUE TITLE
Add option to specify tsconfig.json file to use for each project reference

### ISSUE THREAD

**Issue by rfgamaral** [microsoft/TypeScript#35585]
## Search Terms

`project` `references` `tsconfig`

## Suggestion

Allow to specify `tsconfig` file within the top-level property, `references`.

```json
{
  "references": [
    {
      "config:": "./tsconfig.build.json",
      "path": "../foo"
    },
    {
      "config:": "./tsconfig.build.json",
      "path": "../bar"
    }
  ]
}
```

## Use Cases

Because VS Code (and maybe other IDE's) use root `tsconfig.json` file to configure the built-in TypeScript engine and Project References also use the same root `tsconfig.json` file for each project reference, this creates an incompatibility for `include` and `exclude` properties.

For instance, I don't want my IDE (VS Code) to exclude any `.js` or `.ts` file from type checking files inside my `src` folder, **however**, I also don't want `*.test.ts` files from being transpiled when I build my project. Since both Project References and VS Code use the root `tsconfig.json` file by default without allowing to specify configuration file to use, I can't have my cake and eat it too.

## Examples

With the following configuration I can build my project only the source files will be transpiled, the test files will be ignored. However, VS Code will also ignore test files from type checking and what not.

```json
{
  "extends": "./tsconfig.base.json",
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "./src/**/*.test.ts"
  ]
}
```

With the following configuration VS Code will type check all files (source and tests) just fine. However, building the project will build both the source and test files, which is not what I want.

```json
{
  "extends": "./tsconfig.base.json",
  "include": [
    "./src/**/*"
  ]
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
I'm not sure I understand the suggestion. Reference paths can already point at tsconfig filenames:
```ts
{
  "references": [
    {
      "path": "../foo/tsconfig.build.json"
    },
    {
      "path": "../bar/tsconfig.build.json"
    }
  ]
}
```
What behavior would you want to be different when specifying `path` and `config` separately?

**Comment by rfgamaral** [comment]
@RyanCavanaugh I was not aware you could specify a `tsconfig.json` file directly with the `path` key, I guess I missed the:

> The path property of each reference can point to a directory containing a tsconfig.json file, **or to the config file itself** (which may have any name).

Which I just looked up in the documentation after you mentioning the possibility.

I'll test my real use case tomorrow and I'll report back. I'll leave more info, if needed, otherwise I'll close this myself.

Thank you.

**Comment by rfgamaral** [comment]
It worked great @RyanCavanaugh, thank you 🙇
