### ISSUE TITLE
Error underlining fails in composite project setup

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#35587]
**TypeScript Version:**  3.7.2
**Visual Studio Version:**  VS 2019 Community (16.4)

**Search Terms:**
error underlining

**Repro Steps**
- Project A contains 'library' code in file `aaa.ts` (Project has 'composite' set to true).
- Project B references A and consumes a interface Foo declared in `aaa.ts`
- Ensure all files in B are closed.
- Open file `aaa.ts`.
- Add a new method to interface Foo (which would cause breakage in B).
- Rebuild B and check the output window for the expected error.
- In the output window double click on the error line to see the error.
- This will open the offending file in B.

**Expected behavior:**
The file in B should have the error underlined

**Actual behavior:**
There is no error underlining. 

**Other points to note:**
* Restarting Visual Studio causes the error underlining to show up correctly.
* If the offending file in Project B is already open then the error underlining works correctly.

There is no way to reproduce this as the error occurs only in a very large project set up. However, we have captured language service logs [according to the instructions](https://github.com/Microsoft/JSTSdocs/blob/master/articles/troubleshooting/index.md#enable-detailed-language-service-logging). Please provide a contact email to send through the logs. I cannot post them here as there is potentially sensitive information.

**Usual spiel on why this should be fixed urgently**
We are basically operating in the dark without error underlining.

**Comment by sheetalkamat** [comment]
Please email me the logs, Email id is `shkamat at microsoft dot com`

**Comment by NoelAbrahams** [comment]
@sheetalkamat thanks. I've emailed the logs. FYI I've just upgraded to TS 3.7.3 and the bug is still there.

**Comment by NoelAbrahams** [comment]
@sheetalkamat thanks for the email. I need to look into this and will try to get back tomorrow.

**Comment by sheetalkamat** [comment]
Adding @PranavSenthilnathan and @uniqueiniquity  to investigate the VS side for this. I have forwarded your logs to them to take a look at it.

**Comment by uniqueiniquity** [comment]
Changes to resolve this in TS server have been merged in #36383 and changes to take advantage of the TS-Server-side changes will be included in a future version of Visual Studio 2019. Thank you so much for reporting this!
