### ISSUE TITLE
Move to file does not include namespace imports

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#35591]
From https://github.com/microsoft/vscode/issues/86479

**TypeScript Version:**  3.8.0-dev.20191207

**Search Terms:**
- refactor
- namespace import
- move to new file

**Repo**

1. `git clone https://github.com/johnpapa/vscode-import-bug.git`
1. run `npm install`
1. open `index.ts`
1. use a quick action to move the `createComment` function to a new file

**Bug:**
New file is missing an import for `Octokit`

```ts
import { IssuesCreateCommentParams } from '@octokit/rest';
export async function createComment(comment: IssuesCreateCommentParams) {
  const octokit = new Octokit({ auth: 'somevalue' });
  const response = await octokit.issues.createComment(comment);
  return response;
}
```

In `index.ts`, `octokit` was imported as a namespace:

```ts
import * as Octokit from '@octokit/rest';
```

**Playground Link:** 

**Related Issues:**

**Comment by elibarzilay** [comment]
@mjbvz, do you have a repro of this somewhere else?  The above repository is deleted.

**Comment by DanielRosenwasser** [comment]
Aiming for the end of June.

@johnpapa, still got the repo?

**Comment by DanielRosenwasser** [comment]
Looks like it's back

**Comment by johnpapa** [comment]
Yep - I recreated it.

**Comment by elibarzilay** [comment]
For reference, here's a fourslash test that currently fails to move the `import` line (and works fine with a named import):

```
/// <reference path='fourslash.ts' />

// @Filename: /a.ts
////import * as o from './other';
////[|export const x = o.foo();|]
////export const a = 0;

verify.moveToNewFile({
    newFileContents: {
"/a.ts":
`export const a = 0;`,

"/x.ts":
`import * as o from './other';
export const x = o.foo();
`
    },
});
```
