### ISSUE TITLE
3.7.3 regression: useDefineForClassFields + private = broken emit

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#35590]
**TypeScript Version:**  3.8.0-dev.20191207

**Search Terms:** `usedefineforclassfields` `private`

**Code**

```ts
// enable --useDefineForClassFields

class C {
    private foo: number;
    constructor() { this.foo = 0; }
}

new C();
```

**Expected behavior:**
Code works properly at runtime.

**Actual behavior:**
Code throws at runtime because the emit for an uninitialized private field is:
```ts
        Object.defineProperty(this, "foo", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: foo
        });
```

`foo` is being initialized to `foo`, which of course doesn't exist!

This is a regression in TypeScript 3.7.3, discovered after updating.  I spent about 10 minutes stepping through the debugger looking for the source of the runtime exception before I finally thought to check the emitted JS and discovered it was invalid.

**Playground Link:** 
https://www.typescriptlang.org/play/?useDefineForClassFields=true&ts=3.8.0-dev.20191207&ssl=1&ssc=1&pln=5&pc=1#code/PTAEFMDsEMCMBtygKoGdwBFwDMCWlwAxAewCcBheaVVQ3ceAE1QFgAoAYyptHNAG92oYaAAOpXADdoAFyTZixAFyhIAVwC2scKQDcQkR2KRUM0mo4yyACgCUA0DIAWuVADoFxUAF5QABl1QAF92ELZ2AgB3Xjt9NiA

**Related Issues:** 
Couldn't find anything that seemed relevant.

**Comment by Gerrit0** [comment]
Relevant source... I have no idea why the branch for a modifier is there. Introduced by 369900bb078049a839c09d1b1d53742ab0ddba27:

https://github.com/microsoft/TypeScript/blob/369900bb078049a839c09d1b1d53742ab0ddba27/src/compiler/transformers/classFields.ts#L421-L423

**Comment by aap82** [comment]
I want to add that this also happens for uninitialized public properties as well, if the `public` modifier is used when declaring the property.  

`version: 3.7.3`

**Code:**

```
class SomeClass {
  someProp: number;
}

class SomeClassWithPublicProp {
  public someProp: number;
}
```
**Output:**
```
class SomeClass {
    constructor() {
        Object.defineProperty(this, "someProp", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
    }
}

class SomeClassWithPublicProp {
    constructor() {
        Object.defineProperty(this, "someProp", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: someProp
        });
    }
}
```

**Comment by Gerrit0** [comment]
It will happen with any uninitialized property if that property has a modifier (`readonly`, `public`, `private`, `protected`)

**Comment by ajafff** [comment]
The branch with the initializer is there to handle parameter properties. Seems like the condition needs to be more strict.
@sandersn

**Comment by Gerrit0** [comment]
@ajafff that doesn't make sense to me given that the function accepts a `PropertyDeclaration` and parameter properties don't have a `PropertyDeclaration` node. See [ast-viewer](https://ts-ast-viewer.com/#code/MYGwhgzhAEBa0G8CwAoa0AOAnAlgNzABcBTaAMwHsKBCALmgDsBXAWwCNitVV1gKGIhLE2CEKWABTZ8RUmzBZ6bKiGJgGASkTQAvqh1A)

Though then again, the function is named `transformInitializedProperty` and handles uninitialized properties... so maybe my intuition here is wrong

**Comment by fatcerberus** [comment]
> `hasModifier(getOriginalNode(property), ModifierFlags.ParameterPropertyModifier)`

If my reading of this is correct, it’s checking for only the “parameter property” modifier, but for some reason is picking up *all* modifiers.  The only lead I have is an observation that parameter properties *always* have a modifier, and deduce that, perhaps, the implementation of that was hacked together in such a way that it can’t actually distinguish between the two...

...but that doesn’t really make sense for other reasons so I’m probably totally off-base.  We’ll see what an actual compiler dev has to say before jumping to conclusions. :wink:

**Comment by ajafff** [comment]
The offending code is inside a transform. When it gets executed, parameter properties have already been transformed to property declarations.

`ParameterPropertyModifier` is just a shorthand for public, protected, private and readonly. These are valid for parameter properties and regular properties, so it needs to check whether the property originated from a parameter.

**Comment by fatcerberus** [comment]
Ah hah, so I was (mostly) right!

**Comment by hikarinotomadoi** [comment]
I've submitted PR which will fix this issue, so could you check for it please?
https://github.com/microsoft/TypeScript/pull/35898
