### ISSUE TITLE
Auto import suggestions don't work (JS/CommonJS/Node.js project)

### ISSUE THREAD

**Issue by fabis94** [microsoft/TypeScript#35592]
Auto Imports don't work in even a very basic JS Node.js project. I'm starting to wonder if auto imports even work in JS projects, because I feel like I've tried everything and nothing works.

- VSCode Version: 1.40.2
- OS Version: OSX Mojave 10.14.6

**Steps to Reproduce:**

Reproduction repo - https://github.com/fabis94/vscode-auto-import-broke-repro
b.js should offer to auto import `aTestFunc()` from a.js, and yet it doesn't.

Also check branch 'with-aliases' to see a more advanced scenario that also doesn't work - it uses module-alias to resolve modules using aliases.

**Does this issue occur when all extensions are disabled?:** Yes

**Comment by fabis94** [comment]
Any updates regarding this?

**Comment by andrewbranch** [comment]
This was fixed in #37027; I guess I forgot to link this issue.
