### ISSUE TITLE
typeof x undefined after `let x: T | undefined = undefined;`

### ISSUE THREAD

**Issue by CzBuCHi** [microsoft/TypeScript#35607]
**TypeScript Version:**  ^3.8.0-dev.20191210

**Search Terms:**
wrong type
incorrect type 
incorrectly inferred type
inferred type overrides explicitly set type

**Code**

1) prepare 'project': `yarn init -y && yarn add typescript@next && tsc --init`
2) create test.ts with this content:
```ts
1:  interface Dummy {
2:      prop: string;
3:  }
4: 
5:  let dummy: Dummy | undefined = undefined;
6: 
7:  if (isNotUndefined(dummy)){
8:      const val = dummy.prop;
9:  }
10:
11: function isNotUndefined<T>(value: T | undefined): value is T {
12:     return value !== undefined;
13: }
```

**Expected behavior:**
`dummy` variable should be of type `Dummy` inside if block because of `isNotUndefined` typeguard. (in this code if block is never called, but thats not the issue)

**Actual behavior:**
```
test.ts:8:17 - error TS2532: Object is possibly 'undefined'.

8     const val = dummy.prop;
                  ~~~~~


Found 1 error.
```
i think it is because `dummy` type is inferred as `undefined` on line 5 even when explicit type is written and therefore `isNotUndefined` is called as `isNotUndefined<undefined>(dummy)`

**Playground Link:** 
[minimal code](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCIFcC2mCeyDeAUMicgA5QD2ZAXMgM5hSgDmA3IQL6GEA2EYZABMsuOhmx4APsnQghEGKAhDkAXlnzFyoR0IB6fZoSVsEcMjAALYPUuVkUCJkoA3FNCpQD+kZPUE5FS0yABEocicesAwyAAUtgBylGAAqlpKICpxfrgAlHlEpMgmIIzIrnC8Abk4AHQU1BzchDByCGDAlCDISSnpCpkqADwAKgB8cZW86BB0o8gycoM6eXTTs712C0WkTmDoUD0bKACEahrL2lm6XIRAA)

['real' usage (enzyme + jest test)](http://www.typescriptlang.org/play/?jsx=2#code/PTAEDsHsBdQZwK4CcCmoAWkDupqVAJYC2ADpErNOinCgHQN0BQAJigMYA2AhqqAG69QbOOyQEARigBcobuACeAblYcefQUkLRZ85aq680m0CgAeJDjrmKVbQxqEArGtb0qmxMhVABvUESQCOCwAL6gAGZIkESgAEQo4ABeCkQocSpe5LAAVHJwoABKKNzssFEx8ail0BlMniEoSBGlaADK0NzQaP5MoP2gJNEksuAIRFJISgOgTKH1BI3NraAdXSgAatycCD2zM3Cd3bJr3SoHKNCnMqAAFKgsCOxNsreH6ydHKACUoAC8AD5Vl9foCBJACCwVPMmOxIOBDsD1gBheHdMywP5FEplOhiErdVGNDEAHmuWx2KABt3872OfkGw1kAAZQKEADTwS7XWT4MH4ULfDxwhGwAAqrhQLFRpHhiWsxRqdAAYsj-ndQUDejMRYjaV9ObQrl82erFbiELQiejoLdrtbzNAhfUdfDEeh5CxOChkZwCOwANbq26ahl9GYDI3XW5vL6fdahmmgRh0lCcoaQEbwL50DMkUAAalAAEY2d9nTNQh4ZqhoMhwKASRIENA8A34b7-QG-r4PeAvT6-YHQgDfKnc8NQiTgM3W-CAXMPKpROIpLc4lQCHA4pyQ-8teH+gRbXEsOQA9vd6HfIeI7rYKn4911f48yy2ecI-1vbBwI6eUiz4AD6gMEbARIsUrqmBKAQX+UIul+oAgLgCiWJAEQQP+Jp-LhoAAAYwXBUr4YQoolCwoAYQR1ygCBRGQSw+GIV+95csa6zqi4hx0BE4AhnQgSBgAkqQ3ppCEXQEPCMYPE8Lx3I+gE-PuynXreSFYRitFYnJzxILGCafl+grVkhbFYEg3AkJYWhYoEwS2hpSFkl8DoYnQAAK0T8JCTQCNsuw9vq6yGtyJqhCOzmaf0JISocUoymQf4hMAC4xQM072mijpeT5flIOlSHOtFoCWdZtm8YsLC3AA5LOba1d8dBdLczLNXAxAIDw3TrlwXZxBWSHmJYZRvOFCZ0HgABCPrbN6NUlZpKFdLg6BboMEIhIQoABlAOBUKtUYmlg3AFOw81QbcZ20BQUHiAA5ugsBSBE5BoJu50xBJTo2CwpUoVQTSwe9Wkcc+G1QLADHwaAs64HAZjCGiu37WtXSGvgxCgZ14APahlgPQgvCUXgGAoJw+brbEjClQQmG3FuAByMAAKr9rBjG3H+2kgr8N4Zf0I1WNz2HrBOmbNTNKC3MWQ0mbeplzCVETBGU0kNszbMc8RLBxdSgiUrIYp0aBOuMd8siG7shAFCbAsDMLY3Wz8dBQ1NkCzez4Fc-LoC1vWAWUqAACEeEw1K0JAA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/31187 looks simmilar

**note**
to fix this issue line 5 needs to be rewritten like this:
```ts
5: let dummy = undefined as IDummy | undefined;
```

**Comment by j-oliveras** [comment]
This works as intended.

The tooltip on `isNotUndefined` is `function isNotUndefined<undefined>(value: undefined): value is undefined` because `typescript` knows that is assigned `undefined`. On the _real_ example, typescript don't use any assignment from callbacks because can't be sure if it will be called or when (see #9998 for other examples of this).

Another workaround is:
```ts
let dummy: Dummy | undefined = undefined as any;
```

**Comment by CzBuCHi** [comment]
```ts
let dummy: Dummy | undefined = undefined as any;
```
will not "work" together with "@typescript-eslint/no-explicit-any" rule

also after some other variants i tried i found this construction, which feels wrong: 
```ts
function isType<T>(value: T | undefined): value is T {
    return value !== undefined;
}

interface Dummy {
    prop: string;
}

let dummy = undefined;

if (isType<Dummy>(dummy)) {
    // why is dummy typed as never, when typeguard told tsc typeof dummy is Dummy?
    // isn`t main purpose of typeguards to help tsc determine variable type?
    const first = dummy.prop; // Property 'prop' dows not exist on type 'never'.

    // 3x no error? why is casting from never to anytihng else than never alllowed?
    const second = (dummy as Dummy).prop; 
    const third: Dummy = dummy;
    const { prop }: Dummy = dummy;
}
```

---

anyway for now i will use this construct (despite it feels wrong because of casting):
```ts
let dummy = undefined as Dummy | undefined;
```

**Comment by fatcerberus** [comment]
It's `never` because the TypeScript compiler *knows for a fact* that `dummy` can't possibly be a `Dummy`.  It's `undefined`.  Type guards *narrow* the type, they don't *set* it.
