### ISSUE TITLE
Build not emitting files, but listing them

### ISSUE THREAD

**Issue by TimVosch** [microsoft/TypeScript#35605]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
build out
no files build
emitted files
list emitted files incorrect

**Expected behavior:**
1. Expect `tsc --build` to compile files after outDir is deleted.
2. And expect `tsc --build --listEmittedFiles` to list files emitted

**Actual behavior:**
**Steps to replicate:**
1. Compile a composite project with `yarn tsc -b`
2. Remove outDir (dist or lib for example)
3. Recompile with `yarn tsc -b` (optionally with `--listEmittedFiles`)
4.a. Observe no new compiled files
4.b. Observe `--listEmittedFiles` listing files that aren't actually emitted.

See demo repo:
https://github.com/TimVosch/TS-Build-Bug

**Related Issues:** 
Unfortunately no.

**Comment by TimVosch** [comment]
Also removing `tsconfig.tsbuildinfo` solves the issue. However compiling with `-v` verbose, does acknowledge that the outDir is outdated and should be rebuild.

**Comment by RyanCavanaugh** [comment]
Seems to be a regression

**Comment by sheetalkamat** [comment]
So not generating new build is intended behavior, refer to #30602
To make matters clear, if we change the modified time for the files, it should not mark them as emitted files.
