### ISSUE TITLE
Add inserting/replacing range to suggestion items

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#35602]
From https://github.com/microsoft/vscode/issues/10266

## Search Terms
- suggest / suggestion / complete / completions
- TSServer

## Background
Currently VS Code leaves it up to each extension/language to determine how completions work. Some languages implement completions so that selecting a completion replaces the current word:

```js
c|onsole.log
// accept suggestion for `const` for cursor at pipe character
const.log
```

While other languages instead opt to insert the selected completion at the current position without replacement:

```js
c|onsole.log
// accept suggestion for `const` for cursor at pipe character
constonsole.log
```

With https://github.com/microsoft/vscode/issues/10266, VS Code is considering adding a setting that lets users pick between using the replace vs insert behavior for suggestion

## Proposal
To support this new setting, VS Code needs two ranges for each suggestion item:

- The range when in replacement mode
- The range when in insert mode

As we let the user dynamically select with type of insertion to use with a keybinding, both of these ranges need to be provided up front. 

On the VS Code side, we can do a fairly reasonable job guessing at what the insert/replace range should be, but in order to be more reliable we'd need this information from the TS Server

## Discussion
- Would this API proposal work for JS/TS?
- How does VS handle completions today (insert vs replace)? Is there any way to control this behavior?
- What are the cases where the insert/replace ranges would be different from what VS Code could compute itself? (bracket accessors or string literals for example) Maybe we only need to return additional range info in those cases?

/cc @minestarks @amcasey for VS
/cc @jrieken From VS Code

**Comment by amcasey** [comment]
I'm probably forgetting a case, but isn't the insertion mode range always the same as the current selection (i.e. usually empty, at the cursor)?

**Comment by amcasey** [comment]
Does the user choose between the modes per-completion invocation?  If not, why not just have a flag that indicates which range is desired?

**Comment by mjbvz** [comment]
@amcasey Yes, I think that's usually the case. There are few cases however (such VS Code' jsdoc completions) where we always want to use the same range for both insert and replace. We'd have to see if there are similar cases in TS, such as around string literals or bracket completions

For VS Code, we plan on having a user setting for using insert vs replace. However we also are investigating letting users hold down a key (such as shift) when accepting a completion to instead user the other mode. That's why we need both ranges up front

**Comment by amcasey** [comment]
@mjbvz, sorry, I didn't understand your jsdoc example or what it meant for the insert and replace ranges to be the same.  I was actually guessing that the insert range would always be based on editor state, rather than anything computed by the language service.

**Comment by mjbvz** [comment]
VS Code have a custom jsdoc completion provider: https://github.com/microsoft/vscode/blob/2a46387970f51b13cb22ddfb2bd4a402129f4345/extensions/typescript-language-features/src/features/jsDocCompletions.ts#L36

The completions for jsdocs always need to replace a specific range, no matter what mode the user is actually on

**Comment by Kingwl** [comment]
Related: https://github.com/microsoft/TypeScript/issues/29270

**Comment by andrewbranch** [comment]
The way TypeScript currently works, as @Kingwl pointed out, is that there are a few cases where _only_ a replacement makes sense, and in those cases, we set the `CompletionEntry['replacementSpan']` property. When VS Code commits an entry with `replacementSpan`, it _must_ respect that span. If I understand the proposal correctly, it seems like we want to enable some additional cases where a replacement _or_ an insertion could occur, but these cases are rare.

To @amcasey’s point, I don’t see why this would require us always sending an “insertion range”—it seems like that case can always be determined by the editor state. It seems like all that’s needed is an indication of whether a replacement is _necessary_ vs. simply _available_. I think I’d probably encode this with an extra boolean on the `replacementSpan` object itself, although it could be moved up to the `CompletionEntry` interface. Either way, though, we wouldn’t ever send an insert range.

@mjbvz does that make sense, or am I misunderstanding?

**Comment by mjbvz** [comment]
Yes I think that makes sense. VS Code's API always requires both ranges but a flag that says, 'always use the `replacementSpan`' should let us do the correct thing

**Comment by jrieken** [comment]
> a flag that says, 'always use the replacementSpan'

You do that by returning a single range or by returning the same range two times.

**Comment by andrewbranch** [comment]
The two problems with that are that 1) I don’t think TS Server knows enough of the editor state to supply the insert range (we know what position completions were requested for, but not if the selection width is non-zero, I think), and 2) that just seems like a waste of bytes in our response.

**Comment by jrieken** [comment]
>  I don’t think TS Server knows enough of the editor state to supply the insert range 

The insert range should be the replacement range up to the current cursor position. So, knowing the replacement range is knowing more. Sample: `console.c|lear` has insert range `c` and replace range `clear`. But yeah, if you have the replacement range and a flag that says if cropping it is allowed (meaning won't introduce a syntax but maybe a semantic error) than that's all what's needed.

**Comment by andrewbranch** [comment]
> It seems like all that’s needed is an indication of whether a replacement is _necessary_ vs. simply _available_. I think I’d probably encode this with an extra boolean on the `replacementSpan` object itself, although it could be moved up to the `CompletionEntry` interface.

> Yes I think that makes sense. VS Code's API always requires both ranges but a flag that says, 'always use the `replacementSpan`' should let us do the correct thing

One problem I see is that the _current_ behavior is to assume the presence of `replacementSpan` means “always use the `replacementSpan`,” and if that changed, people using an older version of VS (or VS Code, but I assume people update their copy of VS Code quickly enough that it doesn’t matter very much) with a newer version of TypeScript would always get the replacing behavior. I’m not sure how big of a problem this is, since the replacing behavior seems pretty good. But it is a behavior change that couldn’t be avoided without updating. To avoid creating this situation for VS users, I think we’d have to add another property, like `optionalReplacementSpan: TextSpan`, to be used for times when both insertion and replacement modes are possible. I think this is a messier API, but more backward compatible. What do you think? /cc also @uniqueiniquity for VS awareness.

**Comment by uniqueiniquity** [comment]
Thanks for the tag, @andrewbranch - I can confirm that VS does currently have the behavior of "always use the `replacementSpan`."
