### ISSUE TITLE
Incorrect  error TS2322;

### ISSUE THREAD

**Issue by Ayzrian** [microsoft/TypeScript#35609]
**TypeScript Version:**  3.7.3

**Search Terms:**
 error TS2322: Type 'GetUserDto[]' is not assignable to type 'User[]'.

**Code**

![image](https://user-images.githubusercontent.com/44115170/70540796-88946300-1b6e-11ea-820d-7f18aab409e5.png)

![image](https://user-images.githubusercontent.com/44115170/70540812-90540780-1b6e-11ea-8dd3-7db7c25bea07.png)

**Expected behavior:**

Error is not supposed to occur. All types are correct. Even Webstorm IDE does not highlight anything.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/44115170/70540901-b679a780-1b6e-11ea-92fe-a9a660364ff0.png)

**Playground Link:** 

Here is the tsconfig.

![image](https://user-images.githubusercontent.com/44115170/70541252-60593400-1b6f-11ea-89c5-bf77fbe1a190.png)

**Related Issues:**

**Comment by j-oliveras** [comment]
Please, paste the code as text and add a playground link. Otherwise, is most likely the team will ignore this issue.
