### ISSUE TITLE
Distributive conditional types

### ISSUE THREAD

**Issue by atamelo** [microsoft/TypeScript#35619]
**Code**

```ts
type UnionOfNames<TUnion> = TUnion extends { type: any } ? TUnion["type"] : never


type UnionToMap<TUnion> = {
  [NAME in UnionOfNames<TUnion>]: TUnion extends { type: NAME } ? TUnion : never
}

type Pattern<TResult, TMap> = {
  [NAME in keyof TMap]: (value: TMap[NAME]) => TResult
}

type Matcher<TUnion, TResult> = Pattern<TResult, UnionToMap<TUnion>>;


interface Either<TResult, TError> {

  flatMap<R, E>(f: (value: TResult) => Either<R, E>): Either<R, E | TError>;

  match<R>(success: (result: TResult) => R, error: Matcher<TError, R>): R;
}

class Left<TResult, TError extends { type: any }> implements Either<TResult, TError> {

  public constructor(private readonly error: TError) {}

  public flatMap<R, E>(
    f: (value: TResult) => Either<R, E>
  ): Either<R, E | TError> {
    return new Left(this.error);
  }

  public match<R>(success: (result: TResult) => R, error: Matcher<TError, R>): R {
    return (error as any)[this.error.type](this.error);
  }
}

class Right<TResult, TError> implements Either<TResult, TError> {

  public constructor(private readonly value: TResult) { }

  public flatMap<R, E>(
    f1: (value: TResult) => Either<R, E>,
  ): Either<R, E | TError> {

    return f1(this.value);
  }

  public match<R>(success: (result: TResult) => R, error: Matcher<TError, R>): R {
    return success(this.value);
  }
}

class ResourceError {
  type = "ResourceError" as const

  public constructor(public readonly resourceId: number) {}
}

class ObjectNotFound { 
  type = "ObjectNotFound" as const

  public constructor(public readonly msg: string, public readonly timestamp: string) {
  }
}

class DivisionByZero {
  type = "DivisionByZero" as const
}

class NetworkError {
  type = "NetworkError" as const

  public constructor(public readonly address: string) {}
}

class GenericError {
  type = "GenericError" as const

  public constructor(public readonly exception: Error) {}
}

class BullshitError {
  type = "BullshitError" as const
}

function f1(s: string): Either<number, DivisionByZero> {
  return new Right(+s);
}

function f2(n: number): Either<number, ResourceError> {
  return new Right(n + 1);
}

function f3(n: number): Either<string, ObjectNotFound> {
  return new Right(n.toString());
}

function f4(s: string): Either<number, NetworkError> {
  return new Right(+s);
}

const c = f1('345')
  .flatMap(n => f2(n))
  .flatMap(n => f3(n))
  .flatMap(s => f4(s))

const r = c.match(
  (result: number) => result.toString(),
  {
    //returning of an empty object {} is allowed
    //plus it messes all the other signatures from(value) => string to(value) => { }
    ObjectNotFound: (value: ObjectNotFound) => ({}),
    ResourceError: (value: ResourceError) => 'resourceError',
    DivisionByZero: (value: DivisionByZero) => 'divisionByZero',
    NetworkError: (value: NetworkError) => value.address,
  }
);

console.log(r);
```

**Expected behavior:**
1. returning an empty object {} in the ObjectNotFound case should not be allowed as the expected return type is 'number' in the case above.
2. changing return type of a single function shouldn't affect the others.

**Actual behavior:**
1. returning an empty object {} in the ObjectNotFound case (or any other) is allowed
2. when any 'case' is returning an empty object {}, signatures of all the rest are changing to
return the empty object too (as well as the signature of 'success' function parameter in .match method).

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=120&pc=1#code/C4TwDgpgBAqgdgSwPZwPIDMByBDAthAZwB4AVeZOAPigF4ozEUoIAPYCOAEwKgG8pQkAFxRscEFAC+UAPz1yKANoAiQRGUBdKCLgQAbhABOAWABQZs2tiM4JJAFlsYUgqq0+ZqFEWYAgvYBRKAQ4awoMHHxiBgpKDREYplZ2Lh5+NRE-QKlZeRttKF0DE1NJC1MrAAVsYHZDOFIAJUIAVwAbYAAaekcwajpeT28soJCoAGsIECR0Hqd4qAAKPWw2logE3p9-AI0ASlpqEmaCduAzMvMK8GhHYABjAAsjFxtu49aO-qhq2qMGj6nDrdVx2XqvWKUADc5TMITq6Gw92gAQQwGehiany69AChkMSEM1EGVy86DaNXBjW6AUoi3QImWq3WCROZwONGoqPRL2pUFpexE3IxRD5QQAPrj8YToeUvLgak9RXTTvdkQQCIzDNjWdiOdQ+UYCYYRHcni8SHjjd1GpRBVBGjDSuV7hSNVAADIQdDALFAnGW6WGZhsDjcPgCG4iMQSSTUBC4MBtCD4ODAHjCi1s4FS43EuVQMAtABGbQQ9yg9xQBGAhha92AhMWYEMCBW7Cg2uwnBQbQkRsJCSthIOvEuQyLpfLUHJlKcoppdKGZMZKzWG3o2eA+v5aJFYsoQ3tmcxYqgksDeY8pi8Xm1wBa9UKEAA7p7vcBFuiEAQAHQDww9idLxxxvQsSzLCsFQeR5lUWVV1U1JZtX9XV-R3Q0g1NRURUvQkbTtERGmvW9OwgB8n0WADRB4GM9kUb8-wA381A0L9Hh-f8gyAoZLlA11sHdRoEAAc0eX1ATOd5hyJYJE2TVN013HlMUknM8NkkkJwg6cqzgGs6wbJsWzbGpoC7Hs4D7KA1xZTc9QjUCvEnSCZwpYAqUXRZlxnABGVdmQ3NTt0OZT90XTojyFPdeRpc9cxla8fPvR9QnQXz2M42yIB4sCnPAqcoJwuCEMIJDFhQs40PZULMONbCYItGSCPtYiSVIlKn1KjVMr-bLcpAi4XTdHgTiQR9kRkkjI0gdxlDGiaIBk5QaMratzlJArXL0gz60bQxmx0isLN7CQUPGwxkQASU4HQWlwYsjFHPjhsEnhUGLAArCAG0wJBgAAMXGrgIyGKw6GUD7vt+-6gZaLgVsEtb9I27TCuR3ajIOlzpxOqyJFwAgRJEAyQhE7oceOiBu1OgQE0IYA8DAEnazJ0deKGq4BPdAARNsfwoAAhEAAC0jCQabwagZQ+b0AWUGFsWCURngdo2-iRqgTByJfQlxim9qZugCHteAXXDH1oMVYx1GwMpm3DP2w70bx6zu04FCkNJuAROezmzG5ngAHEOCMcsDbBm45pD3RW3uZbVrVgt7bVx3jKOsiafxkNkTAYAKCFbi+BernNcF9o2gIDjgAjsCpeUcu2kr6uE6RpPnSudB4YbCg-PglnWx948YsxOB7sewxull+W4EV8X8zAzrQl0N9hLEz8AGoCFy0Cu7gHumHQAAmRY4Duh6nuilSiDHi-J4dQgLsmoMF7vcjUufVfRPE0+oA3qBfI73KHvA+aUADMp9z4T2Htfb25MoBQx+sAP6gNgacFfmRCiy9XwOm-p+OALEkAAGVWY+0WHsIBndu750PgAFn7lAOBMCRS3wnt0U25tLZXkNkvT+uD16LC3pQgO61KzuHSosAA5GA2hABWSRewhi-lnB5Jwv9OQzhPnAChSiVG9HUdQdAEDtGKLAso9y+ieAaPQPQ7epiREo07O4e4v5oJPG8mBCqOpCjjyeqFSqHRCEkMHiJchkUwKGy8AAeiiUvMmUAZiiFCCmPOEgkBfSQcXYItEm5IBfBATgPkYlJhaDwNEUAogEEIKIJuAhngJJUow0ScAaiPmqegAkuAmTrh3HAgQSBunrB3PwS4pFEEw1QfDW6SxsoiHGcg2GaCdyLDHHscJpEFqXSWlhGZgUiKP0WjJHckjzqHKDJI9Zt5p4ECFqLcWAV1wiGubcpWSBjmcH5jchWdyCQXJ8hwvWMkHl2QBRbI5oVsq-ndp7S5lxcoOIIEgZMv42hIFCYBJ0QA

**Related Issues:**

**Comment by AnyhowStep** [comment]
string extends {}

So {} is a perfectly valid inferred type. You might be looking for non-inferential usage of type parameters

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/14829

**Comment by atamelo** [comment]
> So {} is a perfectly valid inferred type. You might be looking for non-inferential usage of type parameters

Thanks for the suggestion!
