### ISSUE TITLE
TS2345 error with derivated types from a map of types

### ISSUE THREAD

**Issue by lgraziani2712** [microsoft/TypeScript#35613]
**TypeScript Version:**  3.7.2

**Search Terms:** ts2345 derivated type error

I really don't know how to describe this bug in short terms.

**Code**

```ts
enum A {
    a = 'a',
    b = 'b'
}

interface ObjA {
    prop1: string;
}
interface ObjB {
    prop2: number;
}

type PayloadMap = {
    [A.a]: ObjA;
    [A.b]: ObjB;
}

type Content<T extends A> = {
    type: T;
    payload: PayloadMap[T];
}

function processContent<T extends A>(content: Content<T>) {
    parserPayload[content.type](content.payload);
//                              ^=========== here is the error
}

const parserPayload: { [key in A]: (payload: PayloadMap[key]) => any } = {
//                                           ^============ because this is treated
//                                                         as an intersection
    a: payload => payload.prop1,
    b: payload => payload.prop2,
}
```

**Expected behavior:** To correctly know that `PayloadMap[key]` is in fact the same as `PayloadMap[T]` since `key` matches `T`.

**Actual behavior:** 

```
Argument of type 'PayloadMap[T]' is not assignable to parameter of type 'ObjA & ObjB'.
```

**Playground Link:**  https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=30&pc=2#code/KYOwrgtgBAglDeAoKKoEMoF4oHI04BplUAjLXEnRAX0UQEsQAXYAJwDM0BjYKAeRIArOElRQADqwD24gIwAuKAGcmrRgHMA3DQbM2nHvyEAhBMRSSZAJkXgIJNttqImAT3G8ACmlcAbKWgAJgCyaOLkoqgA2jAAdGgAuooCwtpiMbEkSUaCxk50bh5QAMJSeswAPAAqUMAAHiwggUqwAHwR5lCFwIpVaajiPv5Bit5+ASFhUVUJ+YjsYCBcTPRlEtI8Skql5UzVtQ2gzW0AFFxljUyKO5fVrQCUZmKDrEpsY8OBUee7sd0JZwuoCYsUG4yC9zmPxUEjQr3eQwmingUCiAGtgK4oIxYNkTmDPqNEUFQuJ0ZiEo9MO00CAsdQOmI0IoCRMsO1WUFQdI5EQxCQWcTAuzYeDAtzrERqEA

**Related Issues:**

**Comment by fatcerberus** [comment]
Indexed access produces intersection type => most likely caused by #30769.

**Comment by RyanCavanaugh** [comment]
TS doesn't know that this is OK to do. You could have written this, which would be seen equivalently:

```ts
function processContent<T extends A>(content1: Content<T>, content2: Content<T>) {
    parserPayload[content1.type](content2.payload);
}
declare const a: Content<A.a>, b: Content<A.b>;
// Causes a runtime error, but is an OK call
processContent(a, b);
```

**Comment by RyanCavanaugh** [comment]
Duplicate #31445

**Comment by lgraziani2712** [comment]
> TS doesn't know that this is OK to do. You could have written this, which would be seen equivalently:

BTW, isn't that a kind of bug that TS doesn't check? There are a lot of business logic bugs with correct typings that TS isn't able to catch and that's OK. Isn't the bug you're exemplifying one of that kind?

Thank you for your rapid response!

**Comment by RyanCavanaugh** [comment]
That's a type error, not a business logic error. You can construct examples that observe a `string` where a `number` is expected, for example.
