### ISSUE TITLE
Checking Function.prototype.bind requires --strictFunctionTypes

### ISSUE THREAD

**Issue by justinbayctxs** [microsoft/TypeScript#35610]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:**
strictbindcallapply
function.prototype.bind

**Code**
```ts
declare function foo(x: string, y: boolean): void;
const bound = foo.bind({}, false);
bound('string', 'string', 'string');
```
Run with --strict, except --strictFunctionTypes disabled.

**Expected behavior:**
Errors on line 2, since --strictBindCallApply is enabled. (Line 3 is just to show extra brokenness)

**Actual behavior:**
No errors. It's choosing the last overload for .bind, which just accepts a union of all parameter types for each argument

**Playground Link:**  http://www.typescriptlang.org/play/?strictFunctionTypes=false&ssl=1&ssc=1&pln=3&pc=37#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoAPALngGcMYtUBzAGngE8KAjQiEKVASgoA3HFmABuAFBg81eJzTB4AXgI4AdOzrAiAbwC+zRFAiUQfSfNTaA5NVoNrzWzTr1H8Z-bfmgA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Function types aren't strict when strictFunctionTypes isn't enabled?

**Comment by justinbayctxs** [comment]
If this is working as intended that's fair enough. I was just surprised that `--strictBindCallApply` isn't enough to make bind strict.

**Comment by RyanCavanaugh** [comment]
Yeah it's really not ideal, but there's not much we can do about it without special-casing `bind` even more or causing a breaking change somewhere (or both). Too late to change it now, but `strictBindCallApply` should really have required `strictFunctionTypes` as a prerequisite setting - `SBCA` without `SFT` behaves rather poorly.
