### ISSUE TITLE
lookup type incorrectly becomes intersection type

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#35624]
**TypeScript Version:**  3.5.1, 3.6.3, 3.7.2

> works as expected in TypeScript 3.3.3

**Search Terms:**
lookup type, intersection

**Code**

```ts
const codeToErrorMessage = {
    CODE_1: ({ internalError }: { internalError: Error }) =>
        `internal error: ${internalError} ${internalError.stack}`,
    CODE_2: ({ rc }: { rc: number }) =>
        `bad return code ${rc}.`,
};

export function errMessage<
    K extends keyof typeof codeToErrorMessage,
    F extends typeof codeToErrorMessage[K],
>(k: K, arg: ParamType<F>): string {
    const func = codeToErrorMessage[k];
    const str = func(arg);
    return str;
}

type ParamType<T> = T extends (arg: infer Arg) => any ? Arg : any;

```

**Expected behavior:**

no type errors

**Actual behavior:**

error on this line in TS versions 3.5.1, 3.6.3, 3.7.2.

> Version 3.3.3 is the latest version I could find that has no type errors with this code

```ts
const str = func(arg);  // Error here is unexpected
```

```
Argument of type 'ParamType<F>' is not assignable to parameter of type '{ internalError: Error; } & { rc: number; }'.
  Type 'unknown' is not assignable to type '{ internalError: Error; } & { rc: number; }'.
    Type 'unknown' is not assignable to type '{ internalError: Error; }'.
      Type 'ParamType<{ CODE_1: ({ internalError }: { internalError: Error; }) => string; CODE_2: ({ rc }: { rc: number; }) => string; }[K]>' is not assignable to type '{ internalError: Error; } & { rc: number; }'.
        Type 'unknown' is not assignable to type '{ internalError: Error; } & { rc: number; }'.
          Type 'unknown' is not assignable to type '{ internalError: Error; }'.
            Type '{ internalError: Error; } | { rc: number; }' is not assignable to type '{ internalError: Error; } & { rc: number; }'.
              Type '{ internalError: Error; }' is not assignable to type '{ internalError: Error; } & { rc: number; }'.
                Property 'rc' is missing in type '{ internalError: Error; }' but required in type '{ rc: number; }'.
                  Type 'ParamType<{ CODE_1: ({ internalError }: { internalError: Error; }) => string; CODE_2: ({ rc }: { rc: number; }) => string; }[K]>' is not assignable to type '{ internalError: Error; }'.
                    Type 'ParamType<F>' is not assignable to type '{ internalError: Error; }'.
                      Type 'unknown' is not assignable to type '{ internalError: Error; }'.
                        Type 'ParamType<{ CODE_1: ({ internalError }: { internalError: Error; }) => string; CODE_2: ({ rc }: { rc: number; }) => string; }[K]>' is not assignable to type '{ internalError: Error; }'.
                          Type 'unknown' is not assignable to type '{ internalError: Error; }'.
                            Type '{ internalError: Error; } | { rc: number; }' is not assignable to type '{ internalError: Error; }'.
                              Property 'internalError' is missing in type '{ rc: number; }' but required in type '{ internalError: Error; }'.
```

The problem seems to be related to TS forming an intersection type of the parameter types for the functions in `codeToErrorMessage` rather than keeping them lookup-able.

**Playground Links:**

[Error in v3.7.2](http://www.typescriptlang.org/play/#code/MYewdgzgLgBKAmBTAKiAogJwyDBZREEAhgOaIwC8MA3gFAwMwDCA8gCJoD6AjAFwwAKajACWYKIgxgiAG0zYMMAL79hYiVNnyc-bYqUBKSgD56jcwAN1k6TJiSF-ACTVrmuVhxKYLt7b0AdNBEwADWShYANGYMrBycAEz8QjAYwMqqqcD8YACuALYARpLKRhSm5paFRPCpiFC5UnAgSD7UaUoBUbRKANy0tIgAHgAOOLAAZrlgwFAi4PZY+ISkiAA8MTAA0vZDEmDwEDChiACeIBMwUKcjiBfNSKh6y8Rk0eYAYrv7h1c3d5cECh0J48ARXogANpbAC670YxgEoX4W0iMCIGBI-AAChiiPlkP81h9jAZ+NAMGISDRNqBIJNpukqECnqCXqtIaEYf1zHToDAKZQYFMZgIMSQDDzGBh6o0wAKoBh+koBtdbjBcRh8YTbmtkMYhchvogDkcxZj+GIJiUAIKYsoGohgU4wAD8MDt1P4TtO-SAA)

[Expected behavior in v.3.3.3](http://www.typescriptlang.org/play/?ts=3.3.3#code/MYewdgzgLgBKAmBTAKiAogJwyDBZREEAhgOaIwC8MA3gFAwMwDCA8gCJoD6AjAFwwAKajACWYKIgxgiAG0zYMMAL79hYiVNnyc-bYqUBKSgD56jcwAN1k6TJiSF-ACTVrmuVhxKYLt7b0AdNBEwADWShYANGYMrBycAEz8QjAYwMqqqcD8YACuALYARpLKRhSm5paFRPCpiFC5UnAgSD7UaUoBUbRKANy0tIgAHgAOOLAAZrlgwFAi4PZY+ISkiAA8MTAA0vZDEmDwEDChiACeIBMwUKcjiBfNSKh6y8Rk0eYAYrv7h1c3d5cECh0J48ARXogANpbAC670YxgEoX4W0iMCIGBI-AAChiiPlkP81h9jAZ+NAMGISDRNqBIJNpukqECnqCXqtIaEYf1zHToDAKZQYFMZgIMSQDDzGBh6o0wAKoBh+koBtdbjBcRh8YTbmtkMYhchvogDkcxZj+GIJiUAIKYsoGohgU4wAD8MDt1P4TtO-SAA)

**Related Issues:**

I could not find a related issue

**Comment by fatcerberus** [comment]
Most likely a result of #30769.

**Comment by jack-williams** [comment]
`ParamType<F>` was never working, but in older versions the default type for an inference was `any` which allowed this to type-check. Now the default parameter is `unknown` which causes this to break. You can see the behavior here:
```ts
export function errMessage<
    K extends keyof typeof codeToErrorMessage,
    F extends typeof codeToErrorMessage[K],
    >(k: K, arg: ParamType<F>) {

    // `any` is not assignable to `never` in 3.3
    // `unknown` is not assignable to `never` in 3.5+
    const x: never = arg;

    // ok in 3.3
    // error in 3.5+
    const bad: "nonsense" = arg;
}
```

**Comment by mheiber** [comment]
@jack-williams thanks for taking a look, and for the explanation! I see what you mean about the sneaky `any`.

However, isn't the code in the original post correct? In the example, Args is dependent on K.

I see two possible answers here:
1. the code is "correct" but the type system isn't smart enough to see it yet. In which case this issue could become a bug report or feature request.
2. OR the code is unsound in a way I'm not seeing, in which case I should close the issue

**Comment by jack-williams** [comment]
A little from both.

The code _is_ unsound as shown below:
```ts
// no error but will call a function expecting { internalError: Error }
errMessage("CODE_1" as keyof typeof codeToErrorMessage, { rc: 3 });
```

This unsoundness can be remedied by changing the definition of `ParamType` to not distribute over the union of functions, meaning you correctly get an intersection type at the call-site.

```ts
type ParamType<T> = [T] extends [(arg: infer Arg) => any] ? Arg : any;
```

But there is a fundamental issue in implementing this function, which is that generic constraints are ignored by conditional types, so `ParamType<F>` is always going to remain unresolved in the body of the function. TypeScript just isn't smart enough here, but there are good reasons for the current limitation.

**Comment by mheiber** [comment]
Thanks! Sounds like my issue was related to known limitations in TypeScript's already-super-smart checker. Closing
