### ISSUE TITLE
ObjectConstructor.assign

### ISSUE THREAD

**Issue by TrejGun** [microsoft/TypeScript#35621]
**TypeScript Version:**  3.7.2

**Search Terms:**
ObjectConstructor, Object, assign, target, null

**Code**
```
Object.assign(null, {a:1})
```

this works because 
```
    assign<T, U>(target: T, source: U): T & U;
```
but T can't be null

**Expected behavior:**
type error is risen ts and reported by typescript-eslint

**Actual behavior:**
type error in js
```
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
```

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=1&ssc=26&pln=1&pc=21#code/PIIwVgpgxgLgdAQwM5IJYHMB2AKTBXAGwIBoACAbwQC4BGAXwEog

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/3429

**Comment by fatcerberus** [comment]
The typing used to be correct as the default constraint for a generic type parameter was at one time `{}`.  It is now `unknown` so that should probably be changed to `T extends {}` to exclude null/undefined.

**Comment by TrejGun** [comment]
Guys, as I understand the fix is available for almost half a year already. What prevents it from being merged?

**Comment by sandersn** [comment]
We need to make sure it doesn't cause a lot of breaking changes. I ran the user tests and Definitely Typed tests to see what code there might break.
