### ISSUE TITLE
'asserts' predicate causes unresolvable implicit-any diagnostic in for..of loop

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#35638]
I found this while looking at adding `asserts` predicates to some of our `Debug` assertions in the compiler. Adding an `asserts` condition to `assertNode` resulted in a compiler diagnostic on the variable declaration in a `for..of` loop which can't be resolved because we do not allow type annotations on those declarations.

**TypeScript Version:**  3.8.0-dev.20191210

**Search Terms:** asserts implicit-any for of

**Code**

```ts
function visitNodes<T extends Node>(
    nodes: NodeArray<T> | undefined,
    visitor: Visitor | undefined,
    test?: (node: Node) => boolean
): NodeArray<T> | undefined {
    if (nodes === undefined || visitor === undefined) return nodes;
    let updated: T[] | undefined;
    for (let i = 0; i < nodes.length; i++) {
        const node: T /* (2) */ = nodes[i]; 
        const visited: VisitResult<Node> /* (3) */ = node !== undefined ?
            visitor(node) :
            undefined;
        if (updated !== undefined || visited === undefined || visited !== node) {
            if (updated === undefined) {
                updated = nodes.slice(0, i);
            }
            if (visited) {
                if (isArray(visited)) {
                    for (const visitedNode /* (1) */ of visited) {
                        // Comment out either next line or line below to remove error
                        Debug.assertNode(visitedNode, test); 
                        updated.push(<T>visitedNode);
                    }
                }
                else {
                    Debug.assertNode(visited, test);
                    updated.push(<T>visited);
                }
            }
        }
    }
    if (updated) {
        return createNodeArray(updated);
    }
    return nodes;
}

// minimal declarations from compiler needed for repro
interface Node { kind: number; }
interface NodeArray<T extends Node> extends ReadonlyArray<T> {}

type Visitor = (node: Node) => VisitResult<Node>;
type VisitResult<T extends Node> = T | T[] | undefined;

declare function isArray(value: any): value is readonly {}[];
declare function createNodeArray<T extends Node>(elements?: readonly T[]): NodeArray<T>;

declare namespace Debug {
    // Comment out either next line or line above to remove error
    function assertNode<T extends Node>(value: Node, test: (value: Node) => value is T): asserts value is T;
    function assertNode(value: Node, test: ((value: Node) => boolean) | undefined): void;
}
```

**Expected behavior:**

No error is reported.

**Actual behavior:**

A few things go wrong here:

1. The following error is reported at the location marked by the `/* (1) */` comment above:
    > `'visitedNode' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

    This cannot easily be resolved as we do not allow type annotations in the lexical binding of a `for..of`.

2. The overload of `Debug.assertNode` that has the `asserts` predicate isn't the one chosen by overload resolution, so there's no reason the `asserts` should come into play here.
3. New implicit-any errors are also reported at the comments marked `/* (2) */` and `/* (3) */` if the type annotations are removed. These type annotations were unnecessary prior to adding the overload with the `asserts` predicate.

**Playground Link:** [🔗](http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20191210&ssl=1&ssc=1&pln=52&pc=2#code/GYVwdgxgLglg9mABANxgZxlAcnAJgUzQB4AVRfADynzFzURwID4AKAKEU8TD0IC4GvAIIAnEQEMAnqSaIAPonAFgMMPlwAaDl1QYocEQIBq6TAfmLa+FWs3bO1NFAD8AljwIDG+AJSIAvLIARnBwADb44mBsPl7CYlIyFkrWquqIAN72iDDAiO689P7FlsppuPIKumYiASUpNup+IvhQICJIHoQA3NkRUIoADrji1LgCJADaALrJVo24vVyIwOYs-TkBiAAM3ZtE3IUAdBFgAOZQABZ7MADUt35Zy8sQCE6HnohkAPQAVPkAJj8v2+Wy6aEmMGme2yLzeA2qY2MpigACVCCAwlAiN5ZH98gBmYGg-wffCIACE9Xm5UQzlhz04iIMBQIfj4DMZDXKS0ZOTyLBAw1G6SppO5tkqKBR6WK4ppkrkVRlFTFZMenOeuXyQpGYzq8rKtg1fNNQz1srJaCOaDCMAg+BY2w0OR8vLNiAAvprltqWIimpkfXy-ehRBJJP6VT4TR6zataixXmB3gHcN5EPiWABGYmIOB5NOxuNx76ggDCcAAtlWaAM4CABvhMJd8LU1FREHa1Pnat3yUF8GE4AB3RD6RAtKtwZDktsiAzBkucAAi+CCIDOR3EaDQbewvCjenU3hdjigbsQS+XupFuCOgxAaEuLBkae8buvpu9y64P9-5BhHuQYAc8a4bluO57iIB4EEemDqGehAXu6oHmneD5Pi+b7RqhJb-h6BHPERRF+reYzFs8LRtB0iAQC0IreOGUiCsKFGoUR1HtJ0hS9N6bBlogVaqDAVbiGEiAEBAYTiBIsBvCsC5VnR1aDDAETtvg6jpAmk74IMC5sKo1AiMA4gOoIBCZIgADWqjjNwIBVoOIh7N6xltmZFlMQk0hkJQ1C0PQuLkFQNB0Ig6LiLgCBhJIzF+bIGT8VAkiDOSJh6OYpKsvgcRsgEsiZZg6JoJi2K4r0qXpYgxVohiWKkKFgURSFpJkAoUyzAoErqL0bBSTJLQrOA0DwEgYa+f64kgHliBRJIsQoDN5LoHp0WxZImSejMvSDbJ5KgJA8lIPRkTUD5EZNQF4XBbwrBDvgtZgFAaCuOtMVgHFXwzEtl2JCQTD9ftw1gOItZoIM5nkuBm4gVwgmVjWdb5o25Atm23ABV2aS9jjPbiCEs7jnAenTsT86LssR1jQg827vu3jXWFQWWfgrDICt+X4EhThuJzYSzdzfiBMtgurfQJBLVB+70ALs05JLqE0yd9PQbBjry3Np7jshbjTeLwuFYgIThJEYB+D1CpNAIyBwDAixsJ6QA)

CC: @RyanCavanaugh, @weswigham, @ahejlsberg

**Comment by falsandtru** [comment]
Another problem caused by asserts predicate: #35567

**Comment by ahejlsberg** [comment]
The issue here is that we need to perform full overload resolution to understand the effects of the calls to `Debug.assertNode` (only for a non-overloaded, non-generic method can we understand the return type without having to resolve the parameter types). And because overload resolution needs to know the types of `visited` and `visitedNode`, we end up with circularities. Not clear there's much more we can do, except perhaps consider permitting type annotations on declarations in `for...of`.

**Comment by RyanCavanaugh** [comment]
Side comment but it'd be nice to allow (downcasting) type annotations on `for/of`, especially to fix `keyof` situations
