### ISSUE TITLE
TypeScript in 5 Minutes - Errors on the First Example?

### ISSUE THREAD

**Issue by 1nchHigh** [microsoft/TypeScript#35649]
I'm following the guide here: https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

I have done this a couple of times now (showing colleagues about TS) however, now I simply cannot get even the fist example to work.

Reproduce:
1 - Create a new folder for the project
2 - Create a 'greeter.ts' file
3 - Paste the following example

```
function greeter(person) {
    return "Hello, " + person;
}

let user = "Jane User";

document.body.textContent = greeter(user);
```

4 - Run tsc greeter.ts

5 - The .js file is produce **however** now my greeter.ts file has 2 errors.

**Error 1 -** Duplicate function implementation (under greeter) in the function declaration

**Error 2 -** Cannot redeclare block-scoped variable user

I had a look through the Issues and did find similar issues, but I can see in their examples why TS may be complaining (i.e. an actual redeclaration etc), but I can't figure out why I'm getting these issues with the greeter.ts example (the VERY first example provided by TS).

Thanks

**Comment by RyanCavanaugh** [comment]
It sounds like you opened the `.ts` and the `.js` file at the same time in the editor, so TS now thinks that you have both of them in the same "project" and that these variables are conflicting?

**Comment by 1nchHigh** [comment]
> It sounds like you opened the `.ts` and the `.js` file at the same time in the editor, so TS now thinks that you have both of them in the same "project" and that these variables are conflicting?

@RyanCavanaugh - Actually can't believe it. Feel so stupid now! Many thanks for helping.
