### ISSUE TITLE
Inference to generic overloaded construct signatures fails

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#35641]
**TypeScript Version:**  3.8.0-dev.20191210 (nightly)

**Search Terms:** inference generic overload construct signature

**Code**

```ts
declare class MySet<T> {
    constructor(iterable?: Iterable<T> | null)
    // constructor(iterable?: readonly T[] | null);
    readonly size: number;
    add(value: T): this;
    clear(): void;
    delete(value: T): boolean;
    forEach(callbackfn: (value: T, value2: T, set: Set<T>) => void, thisArg?: any): void;
    has(value: T): boolean;
}

declare function collect<T, U>(it: Iterable<T>, collector: new (iterable: Iterable<T>) => U): U;

collect([1, 2, 3], Set); // expected: Set<number>, actual: Set<unknown>
collect([1, 2, 3], MySet); // expected: MySet<number>, actual: MySet<number>
```

**Expected behavior:**

The return type of the 1st call to `collect` should be `Set<number>`, similar to how the return type of the 2nd call to `collect` is `MySet<number>`

**Actual behavior:**

The return type of the 1st call to `collect` is `Set<unknown>`. This seems to be due to the combination of the following definitions:

```ts
// lib.es2015.collection.d.ts
interface SetConstructor {
    new <T = any>(values?: readonly T[] | null): Set<T>;
    readonly prototype: Set<any>;
}
declare var Set: SetConstructor;

// lib.es2015.iterable.d.ts
interface SetConstructor {
    new <T>(iterable?: Iterable<T> | null): Set<T>;
}
```

Commenting out the first construct signature for `SetConstructor` (in lib.es2015.collection.d.ts) produces the correct return type for `collect`. Likewise, uncommenting the similar `constructor` definition in `MySet` above results in `collect` producing the incorrect return type as well.

**Playground Link:** [🔗](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191210#code/CYUwxgNghgTiAEkoGdnwLIE8DKIAuAPACoB88A3gFDw2ID2AdsnjAK5h50wAUAlniBhQARhBAB+AFzwAkgKGiQxMgB94DVhAgBKANzVaAekP0mLdpx79BIsVPhwowRhEzwiAbQC68NRq16BjSOzgyu8Mi8AF4g0hoAtsKC+rTwTsDcAG5QEKyx7trSeAAWvMgptJAgsNyF8Jl0vMAVNKBiAlk5edJEdcJ0dGJQDC3wAGZcAKJQYMXcYDkQwjMA1mMM0p25+UQANPVdIABMPfvI+NK4hKTa8AC8ZA1N+yVlAIIwAOb2w5h1T80gvBiigtt0CtJ+oNqiNKABfSiUUBIODjVgMDi8Rj0LTga77ACqJD48ls+TkNkUyn2YEGYg4XDiIAA7vASZSxNIKQoxMpbg94AS6gT9JRabiONwPABGfZHfYAZi8+yuengxngIAAHgAHPEgYCXfAEBJJGAkfYzPCsHJGwjolYMOjMhgkMV0vFS2XweXwJX7LCq3TqkzavUcA3SQPG02CC1pDg2iBRnAx1iJONAA)

**Related Issues:** #25917, #35636 (possibly related?)

**Comment by MartinJohns** [comment]
[Type inference in conditional types](http://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types) does not work with overloaded signatures:

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by ChuckJonas** [comment]
I ran into something similar while messing around with variadic tuples, but I assume it's the same problem:

[Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/C4TwDgpgBAwghgGwQIzgYwNYFEBOOoC8UuOA9vgD5QDOwOAlgHYDmUVjArkgNwBQokWIhToMAHgBKAPkJQAFBDwAuIUlSYSAGig4I1LsBUSAlIRlxGIXv3DQAYh0Zpg9UowDq9YAAt4a0WIAKlAQAB7AEIwAJtRQFiAA2gC62tKycgB0WXA4zNQqCVkZgdp+IpiSUkmmBOaWfLxobrRQYGQAtvTU9ABmIGXqGLJiAJIh4ZExcZbJqVJyPY5oKg5OLm6ePgMBI3M1MpnZuflQI8YqAAodXRCVZlAA3rxQOhDAHDiMUIwQAO5QV1InWoEDkcl01FICAAbhBtLoAFYQZz7R7PF5QRZOQ4ZHJ5bQKZSqcrYPDwvQGIyop4YjG6d6fEJ4KAAfleSOchJwphUEKhsPBFIQwGMfFpAF9jOjJXxxdYsc5XF9dHAonZ6AhQeiehqICpaAwWJp0WhkCouSoSOQ2N8uAhyfphfq6ExmKjoaR6FFeOcoB6vXwFetlRBVerNXJtbrnYbmMaXgI9bb2shFPGoKbzYocJa8Nb2HaHZSaC6WO7Pd7ff6ooGlsHXmHdZGXkU8Sd4j60S96R9GLLrE1GC1QrI2kCur1+sJBoLG5rRUA)

Although, I don't think this implementation contains conditional types...
