### ISSUE TITLE
TS doesn't enforce extension of parameters for method type property of an Interface

### ISSUE THREAD

**Issue by HaimWix** [microsoft/TypeScript#35646]
**TypeScript Version:**  3.7.2

**Search Terms:**
method signature
interface
property vs method signature
enforcement 

**Expected behavior:**
(in example) bad should not allow using extended parameter interface

**Actual behavior:**
(in example) bad is allowing usage of extended interface

**Related Issues:**
Nope
**Code**
```ts
interface OptionalInterface {
    something?: string;
}

interface NotOptionalInterface {
    something: string;
}

interface MethodSignature {
    f(y: OptionalInterface): Promise<void>
}

interface ProperySignature {
    f: (y: OptionalInterface) => Promise<void>
}

const bad: MethodSignature['f'] = async (y: NotOptionalInterface) => { }

const good: ProperySignature['f'] = async (y: NotOptionalInterface) => { }


```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const bad = async (y) => { };
const good = async (y) => { };

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=21&pc=1#code/JYOwLgpgTgZghgYwgAgPIAczAPYjgGwElxp4lkBvAKGVuQGdsBbCMAC1AHMB+ALgbBQuAbioBfKlVCRYiFADlsYDFlwFiMsimp0GzVhxCd+9QSPGTppOcgCyB7ABMAysE54wAVyjaadGAAUAJ78Kjh4RCSySACU-AAKUMzA9BAAPABu2MCOAHwWUlFayInY6NBBru5wXj6UfrQw-MGhmOHqRXIxyAC8uSVJTCnpWTn5ElQIuKbIAEZwjvz27E5VHt4QANoA5DDbALq9yHD0QSAIyC3IisptapGaXb39FMgTUyAznNhOCUnlUEqbnWPh2e0OPWOp3OlxC1yUYXuGmssWelDekiAA)

**Comment by RyanCavanaugh** [comment]
Function types declared with method syntax are bivariant in their parameter types; see comments in #18654

**Comment by HaimWix** [comment]
@RyanCavanaugh Thank, I'm reading it right now, but anyhow, why is it checks good in PropertySignature interface and doesn't care in MethodSignature interface?

**Comment by fatcerberus** [comment]
@HaimWix Functions defined using property syntax are checked like function values, which are contravariant in their parameter types under strictFunctionTypes.  Functions defined using method syntax are checked like methods, which  are *bivariant* (for reasons ™), as mentioned above.
