### ISSUE TITLE
Move flat, flatmap to es2019 lib

### ISSUE THREAD

**Issue by mantissa7** [microsoft/TypeScript#35645]
**TypeScript Version:**  
3.7.3

**Search Terms:** 
flapmap es2019, flatmap esnext

**Code**

```ts
[].flat();
[].flatMap(() => {});
```

**Expected behavior:**
With es2019 lib set, it should not error.

**Actual behavior:**
Requires esnext.array lib to compile

**Related Issues:** 
[https://github.com/microsoft/TypeScript/issues/20410](url)

I'm not sure whether this is a bug or feature request, but [https://github.com/tc39/proposal-flatMap](url) is now at stage 4 and included in es2019 [https://node.green/#ES2019-features-Array-prototype--flat--flatMap-](url). I was confused as to why I was getting errors when trying to use the es2019 lib but found it worked when using esnext.array. 

Should/will this be moved to es2019 instead of esnext?

**Comment by IllusionMH** [comment]
Have you tried with `typescript@next`?
It's already in [`lib.es2019.array.d.ts`](https://github.com/microsoft/TypeScript/blob/b98cb0645d2e44947b369a4f7d8921f7d5ca8c56/lib/lib.es2019.array.d.ts) and should be OK if you have `es2019` in `lib`

**Comment by mantissa7** [comment]
Yes, you're right. It is working now. I guess it was a problem with VSCode. It wasn't working even after restarting vscode but now i've restarted my pc it's working. Sorry for the trouble!

**Comment by IllusionMH** [comment]
It's not a problem with VS Code per se, but the fact that VS Code by default uses bundled TS version to power JS/TS completion. VSCode 1.40 has TS 3.6 bundled (IIRC) and yesterday VS Code 1.41 with TS 3.7 was released.
It can be easily changed to use TS from `node_modules` with picking `>TypeScript: Select TypeScript Version...` from command palette or by clicking on TS version in status bar. See [Using newer TypeScript versions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) in docs
