### ISSUE TITLE
TSServer / Code - Insiders Helper (Renderer) taking 100% CPU

### ISSUE THREAD

**Issue by wolfie** [microsoft/TypeScript#35651]
Issue Type: <b>Performance Issue</b>

Steps to reproduce:
Edit some Typescript code in a large codebase with TypeScript >=3.7 enabled.

Can not reproduce with TS 3.6.

_Edit:_ The "Extensions" does mention Prettier, but the issue was reproducible even without it, on a completely blank installation of Insider
_Edit2:_ Seems like the bug reporter mentions "only" 300MB of memory being used, but whenever looking in OSX Activity Monitor, the stuck thread seems to consistently take 920-950MB of memory.

Also, unfortunately I am unable to provide the source code, as I am not allowed to share the code :(. As a random stab, I tried to reproduce the issue in https://github.com/elastic/kibana (arbitrarily chosen as a large opensource TypeScript repository), but was unable to trigger it. So this seems to be some kind of interesting edge case.

VS Code version: Code - Insiders 1.41.0-insider (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-10T21:42:59.146Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	   115	  2222	code-insiders main
    1	    66	  2223	   gpu-process
    0	   295	  2226	   window (cart-usp-callout.tsx — glass)
    0	    66	  2624	     extensionHost
    0	    16	  2655	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=2624
    0	    49	 18156	       electron_node tsserver.js 
   99	   328	 18157	       electron_node tsserver.js 
    0	    49	 18159	         electron_node typingsInstaller.js typesMap.js 
    0	    16	  2626	     watcherService
    0	    16	 15976	     searchService
    0	     0	 15997	     /bin/zsh -l
    0	    33	 17663	     /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-fork ms-vscode.node2 {"common.vscodemachineid":"c495add007039a1a27eac76839551c9af6ac280175ecffc5d6b5b2438666bb13","common.vscodesessionid":"a4862d7d-ee27-4a81-8d53-69eb1f17f35d1576063842384"} AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	     0	 17666	     /bin/zsh
    4	    66	  2634	   shared-process
    0	     0	 18209	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    16	  4806	   utility
    2	    82	 18206	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (cart-usp-callout.tsx — glass)
|    Folder (glass): more than 22135 files
|      File types: js(6508) json(4668) properties(1863) ts(1067) jsx(720)
|                  scss(474) html(332) tsx(297) svg(219) snap(203)
|      Conf files: package.json(61) tsconfig.json(12) webpack.config.js(3)
|                  launch.json(1) settings.json(1)
|      Launch Configs: node(2);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.11.0

</details>

**Comment by mjbvz** [comment]
As a quick check, can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and let us know if that fixes the problem?

**Comment by wolfie** [comment]
I already installed TS@next with just `yarn` and changed the workspace to use that version from the lower right corner. But I'll recheck with the extension as well and let you know.

**Comment by wolfie** [comment]
Yes, it is still easily reproducible with the extension on and using `3.8.0-dev.20191212`.

Trying to find out a minimal reproducible case (within our existing project), I got it boiled down to the following: I create a new blank `.ts` file (also verified with `.tsx`) in our project structure, or open an existing `.tsx` file. I then write this code and press enter to get to the following line:
```typescript
type Foo=1
```

At this time, everything behaves normally. But immediately as I enter a character on the following line (in my case I tried with `t` and `c`), the thread spins up to 100%. 

**Negative case:** I could _not_ reproduce this by using the exactly same test case, but instead of creating a _file_, I just created a new buffer with `cmd-n`. I then changed the file format from "Plain Text" to "TypeScript" from the bottom right corner. When I ultimately entered an `a` on the next line, I got instead an IntelliSense dialog containing the usual suspects: addEventListener, afterAll, afterEach...

**Possible red herring:** Now, once I run `>TypeScript: Restart TS Server` from the command palette, the code gets reformatted to `type Foo = 1` (I only have `Format on save` enabled). The weird thing to me here is that the file doesn't get saved, and I don't trigger the format manually.

I hope this helps

**Comment by wolfie** [comment]
I just noticed that I can reproduce by doing the same scenario, but with the following code for the first line:
```typescript
const foo=()=>{}
```

I also noticed that the bug **does not get triggered** if I _paste in_ the code, instead of _typing it_ manually.

As an additional side note: It doesn't seem to make a difference whether I type the code the way the formatted would format it to.

**Comment by viktorku** [comment]
I also have the same issue on the non-insiders version. TSServer is practically almost always running at 100% CPU load whenever I make some error.

Using TypeScript 3.7.2

```
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by wolfie** [comment]
Things get weirder. I tried to figure out what would be the discriminator here, so I started running a `git bisect` on our project.

That only lead to confusing results - known bad commits suddenly started behaving well. Then going back to the same commit some other time, the bug got triggered again.

This makes me think that whenever the project structure changes, something in some memory gets flushed, and things work well until something gets mucked about in the internal structures. Maybe some memory gets congested, or I try to trigger the bug before some offending data type gets loaded into memory from the project...

Debugging this got even weirder.

**Comment by wolfie** [comment]
Seems like things have started behaving well with the latest Insiders and TS dev builds:
```
VSCode: 1.42.0-insider, Commit: 26f5dfcd76c9a02f116a706844611aeb09ae8c0b
TypeScript: 3.8.0-dev.20191217
```

I'll keep an eye on whether things start acting up again -- I'm okay with closing this _soon_.

**Comment by wolfie** [comment]
Seems like I can't reproduce this anymore, so I guess this can be considered as fixed.
