### ISSUE TITLE
Conditional types, overloads, and declaration files.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/TypeScript#35657]
**TypeScript Version:**  3.6.3

**Search Terms:**
conditional type overload declaration file

**Code**
Typescript file:
```ts
export class Apple {
	constructor(a: string)
	constructor(a: number)
	constructor(private readonly a: string|number) {}
}
```
Generated declaration file:
```ts
export class Apple {
	constructor(a: string);
	constructor(a: number);
}
```
Usage:
```ts
type AppleArgs = ConstructorParameters<typeof Apple>
```

**Expected behavior:**
Whether the usage is inside the same package (.ts file referenced) or another package (.d.ts file referenced) `AppleArgs` should be `[string|number]`.

**Actual behavior:**
If the usage is in the same package, `AppleArgs` is `[string|number]`.
If the usage is in a different package, `AppleArgs` is `[number]`.

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=6&pc=1#code/CYUwxgNghgTiAEkoGdnwIIAdMQQbwCh5jEB7AO2QBcYBXMK0mACigC55qYBLcgcwCUREmApd6jFu3jlaAWwBGIGEIC+BKgE9MCLDhDoYfNAF54AYTE0JTAAqwockFWXIAPFp2kAZhmy4APgIgA
Not a great playground link since this is an issue with declaration emission.

**Related Issues:** I understand that conditional types (like `ConstructorParameters`) use the last overload.  What I believe is a "bug" here is that the emitted declaration file results in different behavior when the class is referenced from another package vs when it is referenced from the same package.  My expectation is that the behavior will be the same in either case.

**Comment by fatcerberus** [comment]
Like you, I'm most surprised that the behavior differs - the implementation signature is (by design) not considered one of the overloads, so if what you've put under "generated declaration file" is accurate, `ConstructorParameters<typeof Apple>` should be the same type regardless of whether it occurs inside or outside of the implementing package.

**Comment by MicahZoltu** [comment]
For the sake of conditional types, I believe that the implementation signature _is_ considered when it comes to "picking the last overload".  This is different from other parts of tsc where the implementation signature isn't considered.

**Comment by MicahZoltu** [comment]
Hmm, I just realized that I cannot reproduce the desired/expected behavior in Playground, so my issue may be something else.  I'm going to close this for now since I don't have a clear repro case that exhibits different behavior between `.d.ts` and `.ts`, though the current behavior _is_ frustrating and confusing, I think it is "by design".
