### ISSUE TITLE
Add Writable<T> and DeepWriteable<T> to lib.d.ts

### ISSUE THREAD

**Issue by bmamouri** [microsoft/TypeScript#35660]
## Search Terms
Writable / Writeable
DeepWritable / DeepWriteable
Removing readonly modifier
Recursively removing readonly

## Suggestion
I would like to add types that remove the `readonly` attribute from another type directly or recursively.

## Use Cases
When using [Immer](https://github.com/immerjs/immer), I find myself removing making the types writeable frequently. This does not really makes the types immutable because Immer changes are reflected in a Proxy object, not the real object.

Immer itself removes the readonly property from the proxy object recursively using its `Recipe` type, which is pretty similar to what is listed in Examples section. But for doing complex operations, some time you still need to mark an object as writeable.

## Examples
```
export type Writable<T> = { -readonly [P in keyof T]: T[P] };

export type DeepWritable<T> = { -readonly [P in keyof T]: DeepWritable<T[P]> };
```

## Checklist

My suggestion meets these guidelines:

* [ X ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ X ] This wouldn't change the runtime behavior of existing JavaScript code
* [ X ] This could be implemented without emitting different JS based on the types of the expressions
* [ X ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ X ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by lucifer1004** [comment]
A simple `DeepWritable` like this will fail in many edge cases. For example, `Map`, `Set`.

**Comment by RyanCavanaugh** [comment]
We've decided to defer built-in definitions like these to the community unless they're strictly necessary for the purposes of the compiler speaking the name of an inferred type.
