### ISSUE TITLE
Is possible to use sourceRoot to point a folder inside outDir and generate the paths relatively to that folder

### ISSUE THREAD

**Issue by lgraziani2712** [microsoft/TypeScript#35670]
**TypeScript Version:**  3.7.2

I'm working with a private package that instead of publishing the root folder and everything related, I'm publishing the content of the `outDir` folder. So, instead of importing things like:

```ts
import bla from 'private-package/lib/folder1/bla';
```

I'm doing this:

```ts
import bla from 'private-package/folder1/bla';
```

Everything works fine until I'm debugging. My `sourceRoot` points to `./_src` which is inside the `outDir` folder (lib). Files in the root of the lib folder will work as expected, but files inside folders from within the lib folder won't because the map file will be treating the `sourceRoot` like an URL. So I get the following:

```js
// lib/folder1/bla.js.map
{
  "version": 3,
  "file": "bla.js",
  "sourceRoot": "./_src/",
  "sources":["folder1/globalActionsBuilders.ts"],
  // ...
}
```

But what I want is this:

```js
// lib/folder1/bla.js.map
{
  "version": 3,
  "file": "bla.js",
  // The source root is one folder above in the hierarchy for files inside folder1
  "sourceRoot": "../_src/",
  "sources":["folder1/globalActionsBuilders.ts"],
  // ...
}
```

Is this possible?

Thank you in advance!

**Comment by RyanCavanaugh** [comment]
It sounds like you want to set the `mapRoot` option

**Comment by lgraziani2712** [comment]
Isn't the `mapRoot` for moving the `.map` files to different location?

I'm not moving the `.map` files, but the source files.
