### ISSUE TITLE
Add a strict-mode configuration to error on unnecessary awaits

### ISSUE THREAD

**Issue by MLoughry** [microsoft/TypeScript#35674]
## Search Terms
TS80007, unnecessary await

## Suggestion
Currently, the tsserver gives a warning/quick fix about unnecessary awaits ([TS80007](https://github.com/microsoft/TypeScript/blob/236012e47b26fee210caa9cbd2e072ef9e99f9ae/src/compiler/diagnosticMessages.json#L4835)). However, there is no configuration to cause the build to error on such cases.

## Use Cases
This would allow PR/CI builds to catch cases where an `await` is used unnecessarily, which can cause significant added code weight when targeting ES versions that do not support native `async`/`await`.

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
    * Depending on how you define added restrictions to strict mode, this could be considered breaking
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplicate of #35419?

**Comment by MLoughry** [comment]
> Duplicate of #35419?

Seems like it, yes.
