### ISSUE TITLE
Uninitialized identifer causes compiler crash

### ISSUE THREAD

**Issue by ahejlsberg** [microsoft/TypeScript#35683]
**TypeScript Version:**  3.8.0-dev

**Code**

```ts
// Compile with --strict
let a: {};
a;
```

**Expected behavior:**

No crash.

**Actual behavior:**

Crash!

**Related Issues:**

Crash is caused by code added in #33171. Beyond this crash, I see several issues with that code. For example, it assumes that if the return type is a union type, then the type annotation AST node is a `UnionTypeNode`, which by no means is a given. For example, the return type node could be a reference to a type alias.

**Comment by ahejlsberg** [comment]
@orta @RyanCavanaugh For now, I'd prefer we revert #33171. Then we can work on getting it right.

**Comment by falsandtru** [comment]
@ahejlsberg Can you fix #35567? Otherwise I (and other developers) can't introduce asserts predicate because it breaks correct tests.

**Comment by ahejlsberg** [comment]
@falsandtru Please restrict yourself to comments that are relevant to this issue. Thanks!

**Comment by falsandtru** [comment]
@ahejlsberg You are the person responsible for asserts predicate you made. Developers can't understand how to introduce it to existing tests without your explanation. At least you should make your design clear whether this incompatibility is intended or not.
