### ISSUE TITLE
Destructuring optional function with default becomes right-most type of union? 😳

### ISSUE THREAD

**Issue by ianstormtaylor** [microsoft/TypeScript#35689]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** Destructuring, destructure, function, default, options, union

**Code**

```ts
const test = (options: {
  fn?: ((value: any) => boolean) | ((value: string) => boolean)
} = {}) => {
  const { fn = () => true } = options
  fn
  // const fn: (value: string) => boolean
}
```

**Expected behavior:** It should have the type as defined in the function's signature.

**Actual behavior:** It acquires the type of the right-most part of the union?

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191214#code/MYewdgzgLgBFCm0YF4YAoQAcoEtwQC4YBvAKBhgDMwB+ItNANwEMAbAV3iObAE8BKFAD4YAIxAhW8HoIA+6Jm05FoAJxxgA5oOQjxk6WH6kAvihImdIshVCRYxKmHOKOXGDwHC4qzjDOoWLj45E6mQA)

**Related Issues:** I'm not totally sure, but https://github.com/microsoft/TypeScript/issues/35414 may be related?

**Comment by ianstormtaylor** [comment]
I actually discovered this while trying to implement a filtering function that had the same semantics as `Array.filter` where you can pass either a narrowing predicate _or_ a simple `boolean`-returning function.

That case also fails:

**Code** ([Playground](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191214&ssl=1&ssc=1&pln=6&pc=2#code/MYewdgzgLgBAhmEUAWBTATjAvDAFCABygEtwIAuGAbwCgYYAzMAfkt1wDc4AbAV1UoIAngEpsAPhgAjECG6oEYgD55OPfpWjpiYAOZiskmXIVgRNAL7ZqFg5Nr1QkWFUZhruOzCjp+MKziEJGR0bpZAA))

```ts
const filter = <T extends string>(
  options: {
    predicate?: ((value: any) => value is T) | ((value: any) => boolean)
  } = {}
) => {
  const { predicate = () => true } = options
  predicate
  // const predicate: (value: any) => boolean
}
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191214&ssl=1&ssc=1&pln=6&pc=2#code/MYewdgzgLgBAhmEUAWBTATjAvDAFCABygEtwIAuGAbwCgYYAzMAfkt1wDc4AbAV1UoIAngEpsAPhgAjECG6oEYgD55OPfpWjpiYAOZiskmXIVgRNAL7ZqFg5Nr1QkWFUZhruOzCjp+MKziEJGR0bpZAA)

**Comment by ianstormtaylor** [comment]
And actually, here's a test case using a 3-part union, and it seems to take the last 2 parts. So instead of the "right-most" hypothesis, instead it seems to just skip the first entry in a union?

**Code**

```ts
const test = (options: {
  fn?: ((v: any) => boolean) | ((v: string) => boolean) | ((v: number) => boolean)
} = {}) => {
  const { fn = (v: any) => true } = options
  fn
  // const fn: ((v: string) => boolean) | ((v: number) => boolean)
}
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191214&ssl=1&ssc=1&pln=6&pc=2#code/MYewdgzgLgBFCm0YF4YAoQAcoEtwQC4YBvAKBhgDMwB+ItNANyIEMwBPAShQD4YAjECAA28NtwA+6JkWgAnHGADm3ZH0EixYSdOYwwAVwC2-eHNXqho8aQC+KErYslyMUJFjEqYBzJhsuXjg5A3gYe1QsXHxXajsgA)

**Comment by ilogico** [comment]
`((v: string) => boolean) | ((v: any) => boolean)` (the order is irrelevant) is a function that can only be safely called with a `string`, hence it's equivalent to `(v: string) => boolean`.
`((v: string) => boolean) | ((v: number) => boolean)` is a function that can only be safelly called with `string & number`, so it's an uncallable function: `(v: never) => boolean`.

**Comment by ianstormtaylor** [comment]
Thanks @ilogico I think that explains part of it. But it still is exhibiting weird behavior that doesn't seem to add up. But this is my bad, I confused the whole issue by attempting the reduced test cases. I've opened https://github.com/microsoft/TypeScript/issues/35690 instead with just my core issue. Thanks!
