### ISSUE TITLE
Optional chaining and assigning to array items

### ISSUE THREAD

**Issue by mehlian** [microsoft/TypeScript#35699]
**TypeScript Version:**  3.7.2

**Search Terms:**  optional chaining array items

**Code**
Is there any reason why I cannot do this:
```ts
interface MyInterface {
    temp: number;
}

const a: Array<MyInterface | null> = [];

a[0]?.temp = 0;
```
and instead I'm forced to use something like this?:
```ts
interface MyInterface {
    temp: number;
}

const a: Array<MyInterface | null> = [];

if (a[0])
    a[0].temp = 0;
```

**Expected behavior:**
a[0] doesn't exists, so assigning number 0 will be skipped.

**Actual behavior:**
Error: The left-hand side of an assignment expression may not be an optional property access.(2779)

**Playground Link:**  https://www.typescriptlang.org/play/?target=2&ssl=5&ssc=35&pln=5&pc=40#code/JYOwLgpgTgZghgYwgAgLIE8CS5ryQbwChkTlIBbABwC5kQBXcgI2gG5CBfQwhAexADOYZHFoBBKFDjoAPBmyRYiFAB869ADYaAfMgC8yANoBddoTiGADMYD8AOgqV9yS2eAxkACgvWAlMVIfYwcIKmdXIA

**Related Issues:**

**Comment by j-oliveras** [comment]
This is not supported by the specification. See https://github.com/tc39/proposal-optional-chaining#not-supported

**Comment by DanielRosenwasser** [comment]
This is technically not the appropriate venue to discuss it (since it's just part of the ECMAScript feature, not TypeScript) - but just curious, what would you want to happen?

**Comment by mehlian** [comment]
I expected that assignment will be skipped and no property will be created (no side effects).
