### ISSUE TITLE
Destructuring optional function changes type based on presence of default?

### ISSUE THREAD

**Issue by ianstormtaylor** [microsoft/TypeScript#35690]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** destructuring, destructure, function, optional, default

**Code**

```ts
const withDefault = <T>(
  options: {
    predicate?: ((value: any) => value is T) | ((value: any) => boolean)
  } = {}
) => {
  const { predicate = () => true } = options
  predicate
  // const predicate: (value: any) => boolean

  const value = 'string'

  if (predicate(value)) {
    value
    // const value: "string"
  }
}
```

```ts
const withoutDefault = <T>(
  options: {
    predicate?: ((value: any) => value is T) | ((value: any) => boolean)
  } = {}
) => {
  let { predicate } = options

  if (predicate === undefined) {
    predicate = () => true
  }

  predicate
  // let predicate: ((value: any) => value is T) | ((value: any) => boolean)

  const value = 'string'

  if (predicate(value)) {
    value
    // const value: "string" & T
  }
}
```

**Expected behavior:** Whether the default is implemented as part of the destructure, or afterwards using an `undefined` check, it should result in the same type.

**Actual behavior:** For some reason the default with destructuring is narrowing the type of the function?

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191214&ssl=26&ssc=41&pln=26&pc=26#code/PQKhCgAIUh1BLALgC0gQ0gEwKYDM0CuANopAG5pEHYB0UIw44AxgPYB2AzqQO5LIARPIRKQAvJAA8AFQB8ACiiRWAB0TwOnAFyQA3ksiQVAJ2yZ4zNImwB+HfPkUq2HWnYBPAJTjZ5StUh4TkhpbwAfSAcnalcPbzFfACNWViJsN08lAF9xPSzweN99QzYuUl0jU3NLa1z5QshEYwCciVV1TSUTMwsrbCVgYEhS7kqempdI6Mm3Lx9IZNT09iYSzVJp3IBybmN4dgBzLdXA3Eju6r7Hf2xPb2LDP2cDSEHh9aeYyAAiXf2D77ZcD5cCgCDQOD8VgEUgYHD4YgbG50aCMFgfPgoaGIIQI0QSGQKJTtDRcHQPQwXXrWOyRa7OWJzBKfbCBYKhSARKI3RkNRZpDLZXK6fINB5pcpjS61VrKNSkzgneBneRUibiMQSAjseH7Mz3F5qvp1BpNahArpVan9QxvCVS632elfWYNTZBELhOnTXnzfnLTJKEZI5zbP6HY5KZXnK0TZ23A2PFkvN7Blk6X5Nf7fSAAMhCQKyQA)

---

This is something I noticed while trying to implement a filtering function that had the same semantics as `Array.filter` where you can pass either a narrowing predicate _or_ a simple `boolean`-returning function. But when using the destructuring default, the type is no longer recognized as a predicate.

**Comment by ahejlsberg** [comment]
This is working as intended. The type `(value: any) => value is T` is a subtype of `(value: any) => boolean`, so the union type `((value: any) => value is T) | ((value: any) => boolean)` is reduced to just `(value: any) => boolean` the minute we perform subtype reduction. We specifically *don't* perform subtype reduction on explicitly written types, but in a destructuring declaration that includes a default value, we form a subtype reduced union between the destructuring type and the default value type. So, for those reasons the union type is reduced in the first example, but not in the second example.

I'd suggest simplifying the predicate type to just `(value: any) => boolean` and getting rid of the type parameter. There's no point in having it.

**Comment by ianstormtaylor** [comment]
@ahejlsberg how can you implement a filtering argument to a function that will narrow the return value without using a predicate type?

For example if you wanted to allow walking `Node` values in a tree, but for people to be able to pass in a filtering function so that the return is `SpecificNode` (a subtype of `Node`) instead. (This seems like what `Array.filter` does?)

```ts
function walk<T extends Node>(tree: Node, filter?: ...) {}
```

Maybe I'm thinking about it incorrectly!

**Comment by travigd** [comment]
I was playing around with trying to do this with function overloading but it doesn't quite work.

This seems to work.
```ts
interface MyNode {
  type: string;
  lhs: MyNode | null;
  rhs: MyNode | null;
}

interface Foo extends MyNode {
  type: "Foo";
}

interface Bar extends MyNode {
  type: "Bar";
}

// Here's the real meat and potatoes!

// More specific overload goes first
function walk<T extends MyNode>(
  tree: MyNode,
  predicate: (arg: MyNode) => arg is T,
): Iterable<T>;

// Less specific overload goes second
function walk(
  tree: MyNode,
  predicate?: (arg: MyNode) => boolean,
): Iterable<MyNode>;

function* walk(tree: MyNode, predicate: (arg: MyNode) => boolean = () => true) {
  if (predicate(tree)) {
    yield tree;
  }
  if (tree.lhs) yield* walk(tree.lhs, predicate);
  if (tree.rhs) yield* walk(tree.rhs, predicate);
}
```

Here are some examples.
```
for (const node of walk(tree)) {
  // Has type MyNode
  console.log(node);
}

for (const node of walk(tree, (node) => node.type === "Foo")) {
  // Has type MyNode
  console.log(node);
}

// Note that we have to explicitly annotate that the predicate is a type assertion
// for it to work as desired.
for (const node of walk(tree, (node): node is Foo => node.type === "Foo")) {
  // Has type Foo
  console.log(node);
}
```

One important thing to note is that this actually does depend on the order in which overloads are defined, since TS attempts to use overloads in the order in which they're defined (I just learned this myself!).
> In order for the compiler to pick the correct type check, it follows a similar process to the underlying JavaScript. It looks at the overload list and, proceeding with the first overload, attempts to call the function with the provided parameters. If it finds a match, it picks this overload as the correct overload. For this reason, it’s customary to order overloads from most specific to least specific.

**Comment by ianstormtaylor** [comment]
@ahejlsberg can you check out my follow up? I think this might have been closed prematurely. (But maybe I’m not understanding correctly!)
