### ISSUE TITLE
Question : Can typescript compute the outline and goto definition of javascript code ?

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#3569]
If there is a positive answer to my question, I would be happy to know how to do such thing :)

Thanks in advance guys !

**Comment by DanielRosenwasser** [comment]
Hi @Yellowmat - usually we propose you simply rename your `.js` files to `.ts` files, and your TypeScript-aware editor will be able to work with your code.

It sometimes depends on the JS codebase that you started with, but in my experience, even in the face of semantic errors, our language service is able to piece things together reasonably well and give you the information you're interested in.

**Comment by Yellowmat** [comment]
Thanks for your reply @DanielRosenwasser !

I already did change the extension of my JS files, and I'm able to get code completion which is really cool. I also load some predefined ts files describing API such as JQUERY to have code completion on those API.

The LanguageService API export a getDefinitionAtPosition methods, which may does what it says (I will check this soon and I'll add a comment here to share my experience).

How to get outline seems not straightforward to me, but I'm surely wrong about that ... if anybody already experienced this feature, please, share ;)

**Comment by DanielRosenwasser** [comment]
The language service method you're interested is `getOutliningSpans`:

```TypeScript
getOutliningSpans(fileName: string): OutliningSpan[];
```

@Yellowmat just curious, is there a particular goal you're trying to achieve outside of text editing? Are you building an editor client?

**Comment by Yellowmat** [comment]
Yep, I have a specific goal in mind.

I mainly come from C++, which is a compiled language. The compilation steps is really important and avoid to get some nasty bugs, the code being in production or not.

I don't have the same knowledge in JavaScript and I'm missing such code analyzing tools to help me understand what is going on.

Being able to code safer and faster is also something I'm interested in and the main reason I'm evaluating TypeScript as a solution to all my problems :)

**Comment by DanielRosenwasser** [comment]
> I'm evaluating TypeScript as a solution to all my problems :)

It is a panacea, and silver bullet, for every problem you can conceive :smile:

There are quite a few editors with language support for TypeScript, such as [Visual Studio](https://www.visualstudio.com/), [VS Code](https://code.visualstudio.com/), [Sublime](https://github.com/Microsoft/TypeScript-Sublime-Plugin), [Atom](https://github.com/TypeStrong/atom-typescript), [Eclipse](https://github.com/palantir/eclipse-typescript), Brackets, and several for Vim such as [Tsuquyomi](https://github.com/Quramy/tsuquyomi) and [TypeScript Tools](https://github.com/clausreinke/typescript-tools.vim).

Those might help you get to where you want to be; but keep us updated on things you might be working on in our Gitter chatroom.

**Comment by Yellowmat** [comment]
May TypeScript solve, at least, my coding problems, I'll be ok to use any other solution for my personal ones ;)

You have a place where to chat about TypeScript ? Is there a better place where to post them instead of creating "fake" issues ?

**Comment by DanielRosenwasser** [comment]
Yup, we have a [Gitter chat room](https://gitter.im/Microsoft/TypeScript), and while the team isn't actively on IRC, there's often a friendly bunch on [#typescript in freenode](https://webchat.freenode.net/).

**Comment by mhegazy** [comment]
Looks like the original issue has been answered. please reactivate if you are running into other issues.
