### ISSUE TITLE
Declaration merging for interfaces defined in other module

### ISSUE THREAD

**Issue by deser** [microsoft/TypeScript#35698]
I have types generated by the graphql-code-generator. When I try to specify some properties of the interfaces I fail.

**TypeScript Version:**  3.7.3

**Search Terms:**
declaration merging
augmentation

**Code**
The code below would be augmented by the pictures explaining the issue.

```ts
declare module 'shared/types/GraphQLSchema' {
    interface GQLFvItem {
        type?: fcft | string;
    }

    interface GQLFvPage {
        items?: Maybe<Array<Maybe<GQLFvItem>>>;
    }
}

const d = {} as GQLFvItem;
const ddd = d.type;
```

As you can see module `shared/types/GraphQLSchema` has merged declaration so `type` property could be taken from both places.
![image](https://user-images.githubusercontent.com/3010698/70903640-58d2d880-2010-11ea-868f-e9f417534824.png)

But actual type of `type` property is `string | undefined`:
![image](https://user-images.githubusercontent.com/3010698/70903735-93d50c00-2010-11ea-8ced-ec371c3b8151.png)

**Expected behavior:**
Actual type of `type` property is `fcft | string | undefined` where `fcft` is enum.

**Actual behavior:**
Actual type of `type` property is `string | undefined`

**Comment by RyanCavanaugh** [comment]
The snippet there wouldn't be a module augmentation because it doesn't import the same module. We'd need a complete repro to be able to advise further

**Comment by probablyup** [comment]
I'm running into a similar issue... honestly it seems like the functionality was broken at some point because even the simple examples provided have not yielded a functional result.

```ts
// thing.ts

import {Something} from './thing.d'

type Thing = Something['foo'] // resolves as string, should be number

// thing.d.ts

export interface Something {
  foo: string
}

// otherthing.d.ts
import './thing.d'

declare module './thing.d' {
  interface Something {
    foo: number
  }
}
```
