### ISSUE TITLE
Narrowing type with boolean algebra

### ISSUE THREAD

**Issue by macabeus** [microsoft/TypeScript#35704]
## Search Terms

- narrow type
- boolean algebra

## Suggestion

I know that TypeScript doesn't do any boolean algebra, but would be very nice to add support for this, even for simple operators, such as `!`.
With that we could write more readable and safer code.

Related:
- https://github.com/microsoft/TypeScript/issues/26852#issuecomment-417969294
- https://github.com/microsoft/TypeScript/issues/11450

## Use Cases

Let's say that we are typing a response from an API:

```typescript
type TApiResponse = {
    valid: false,
    errorMessage: string
  } |
  {
    valid: true,
    value: number
  }
}
```

So, if we receives a valid response, we have a `value` property, otherwise we'll have an `errorMessage`. We can check if it was successful or not checking the boolean value from `valid`.

So we could do it:

```typescript
const result = await fetchMyApi() // I don't know if result has errorMessage or value...

if (result.valid === false) { // Let's check it...
  alert(result.errorMessage) // Nice! Narrowing for 'valid: false'
                        // now I have sure that we have result.message
  return
}

// And narrowing for 'valid: true'...
console.log(result.value) // It's woking!
```

But if we use some lint rule such as [`no-boolean-literal-compare`](https://palantir.github.io/tslint/rules/no-boolean-literal-compare/) we aren't allow to use `result.valid === false`, but just `!result.valid`, and it won't narrow, because TypeScript doesn't do any boolean algebra:

```typescript
const result = await fetchMyApi()

if (!result.valid) {
  alert(result.errorMessage) // Error!! I don't know if we really have 'message' here!
  return
}

console.log(result.value) // But for some reason, we don't have any error here (I don't know why)
```

## Checklist

My suggestion meets these guidelines:

* [ ] Allow very simple boolean algebra, such as unary operators
* [ ] Allow binary operation

**Comment by dragomirtitian** [comment]
Nitpick: You need to check the items in the guidelines checklist not come up with your own check list (I would say this feature request probably checks the items in there but you should go trough them to make sure)

**Comment by jcalz** [comment]
I can't reproduce the issue, either.  The following works as I expect:

```ts
function hmm(result: TApiResponse) {
    if (!result.valid) {
        alert(result.errorMessage); // works
        return;
    }
    console.log(result.value) // works
}
```

[Playground link](http://www.typescriptlang.org/play/#code/C4TwDgpgBAKggmAlgJQgZzAewHZugXigG8BYAKCkqgDcBDAG0QBMAuKAMwbwBpyqoIAJ0GZBAWXRpaAcwhs0wQYmzTyAXygAfcqQpU6jVlEUBXCLz2UDZtthMBbAEZD1fKOXYnsAY2CIcUAAW9vYAFILoJvTAbPBIqBg4eACUxG6UiOxQoQCEEWhRwAB0Bsypuvz8DELA4ZHRRUIi4pIyEMkA3FAA9N1QAO6iANZo6ZURwCaC2B1jamPeSZj0EEX0mNJ1BQ3W7T19g4IjrmTkQA)

I mean, `message` is not the same as `errorMessage`... so what specifically is the issue here?  Can you provide a Playground link that demonstrates it?

**Comment by macabeus** [comment]
@jcalz I have this on Visual Studio Code:

![image](https://user-images.githubusercontent.com/9501115/70938973-34422500-203f-11ea-95d5-9ccd2014ae3c.png)

And it fails:

```
ERROR in /Users/macabeus/ApenasMeu/front/web/src/containers/new-order-steps/Payment/GetDiscount.tsx
./src/containers/new-order-steps/Payment/GetDiscount.tsx
[tsl] ERROR in /Users/macabeus/ApenasMeu/front/web/src/containers/new-order-steps/Payment/GetDiscount.tsx(56,38)
      TS2339: Property 'errorMessage' does not exist on type '{ valid: false; errorMessage: string; } | { valid: true; type: "percentual" | "absolut"; value: number; code: string; }'.
  Property 'errorMessage' does not exist on type '{ valid: true; type: "percentual" | "absolut"; value: number; code: string; }'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
       4 modules
ℹ ｢wdm｣: Failed to compile.
```

And very weird... I'm trying to reproduce this same error on playground, but I can't.
This is a code more similar with the code that I'm developing and have this error (unfortunately, I can't disclose the repository): [playground](http://www.typescriptlang.org/play/?esModuleInterop=false&declaration=false&jsx=2#code/MYewdgzgLgBA5gUygEQJYVAVzLAvDAQwgE8xgYAKAShlwD4YBvAWACgYYpiAHBGAFQCC3VACUEEbuAh98FNhw4t2ijtAJRMEAFwwwmALYAjBACcANAtUwDEiAUS7op1GDhWOAXxgAfD038OADcCABtUABNdADMwmUsVVTNTEFMAWTsHBCcoFzd-bz9EgOLgsMjdXMwEBOsYENDq3X1jMwKrKjYrUEhYUwlaQgB3AlRYaKRgAAsKAHIIEFsYTFNQ2c6VHugYfohMUKhdIRFxSWlZYdG+iQA6ACsFsGoulX7NUzAdiX2oNk8XrawRAodBYHAAMRAIEGRFI5AooAi2RgzlccBo9BKHEBXz2BxhIzG8CQaAwIGwUGeKlQ0UoAEI5g1IrMYK5cT8qDRlKo3itPowUVANFpdLNkqkWf8VFKrLyPuyDn8AdJYEyIhoEKSwXhCCQyJQMQxuTAcbsfgSrsSQWSKZCQHNEQh1i8ODT6YzyhEWWyzQdOVjFGEzJTZsgJMB9rxzDYiDApuSgnxDDBxYRoVAEDgCKZ6p7szBoUiyTgQHSBJmMzH0Jxs0jncU5WArDLqbSKHTfVAbmquf4g6ZKZ2buL0plEBseUg+c2XSbpCBQggbqEQHAKEOGtUNlKgA)


(also, the typo `message` instead of `errorMessage` was specifically when I was writing this issue)

**Comment by adekau** [comment]
What is your workspace typescript version? (Displays bottom right of VSCode)

**Comment by macabeus** [comment]
@adekau My TypeScript version is 3.7.2

**Comment by ark120202** [comment]
@macabeus it's reproducible on playground when `strictNullChecks` flag is disabled. That's a valid error though, because without that flag it's possible to specify `valid: undefined` for both states.

**Comment by macabeus** [comment]
@ark120202 Oh, thank you! I didn't know about this config. Very thank you.
I'm closing this issue.
