### ISSUE TITLE
Add second type parameter to Partial<T>, Required<T>, and Readonly<T> to selectively modify properties

### ISSUE THREAD

**Issue by 1000hz** [microsoft/TypeScript#35703]
## Search Terms

`Partial Required Readonly` `mapped types`

## Suggestion

Currently `Partial<T>` `Required<T>` and `Readonly<T>` apply their modifications wholesale to all properties of `T`, but oftentimes this is more than what you intend. We should consider adding a second type parameter to limit the properties affected by the modifier.

```typescript
type Partial<T, K extends keyof T = keyof T> = Omit<T, K> & {
    [P in K]?: T[P];
};

type Required<T, K extends keyof T = keyof T> = Omit<T, K> & {
    [P in K]-?: T[P];
};

type Readonly<T, K extends keyof T = keyof T> = Omit<T, K> & {
    readonly [P in K]: T[P];
};
```

## Use Cases

Oftentimes it's necessary to make only a few or single property optional or required. This currently requires a lot of manual type intersection, as one needs to split the type apart, apply the mapped type on this subset, and reconstruct the full type. It would be much simpler if we moved this into these predefined mapped types to make them more powerful.

## [Examples](https://www.typescriptlang.org/play/#code/C4TwDgpgBA+gCgQwE7AJYIDYB4AqAaKAaSggA9gIA7AEwGcoBrCEAewDMocoBeR59zgD4eUAPIBbVMFwFCwgGRQA3gCgo6qAG04UVJSIBdAPwAuTtoMBuFQF9rK0JFgAlCAEcArqiQRqMoiTkVHR8rBxcvExhQiISUv5yUIqqGlo6eoYAtKbmcFa29o7QMK4I1CyUGCAJgRQ09FECEaFNwrxx0vhECspqGj5lFVVpuvqEBmY4FtZ2KioA9PNQAKq0CADmEHNFnCIpGmwsLGa0wEh669apAEbIJ2cXVxq3AF45p+eUl7Zz8wBUfzUfyghxYAGp3g8vlAAD5QDw0CBsPS+K7A25ICH3T7rWHwxHIyiooFQV6QnF4hHUJEo6ho+YqADGFVOUDAwDM8GQaEwuDayhsUEWUAAQghGQwAO7IELM8RgBBoa4YLa-AEk0FYqAfC6Ugm0tGku7aqHfKDohBvbG6uFUmlEulAhnMyis9mgzmIFDobBdABEoL9-P26gxZj9GL9PzVgPNIKOWp10Nt+odhoxidNeuphOJcde2WtX3pTJZwDZZ1enNcnm8viwXO9vJwggIEctQb2fVDlvDryjNiAA)

```typescript
type T = {
    foo: string;
    bar: string;
    baz?: string;
}

/**
 * foo+?: string | undefined;
 * bar+?: string | undefined;
 * baz?: string | undefined;
 */
const pt: Partial<T> = {} // Backwards compatible


/**
 * foo+?: string | undefined;
 * bar: string;
 * baz?: string | undefined;
 */
const ptfoo: Partial<T, "foo"> = {
    bar: "bar"
}


/**
 * foo+?: string | undefined;
 * bar+?: string | undefined;
 * baz-?: string;
 */
const ptrbaz: Required<Partial<T>, "baz"> = {
    baz: "baz"
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
> 
>    * [x]  This wouldn't be a breaking change in existing TypeScript/JavaScript code

But what about this?  Currently:
```ts
function foo<T>() {
    const z: Partial<T> = {} // okay
}
```

With proposed change:
```ts
function foo<T>() {
    const z: Partial<T> = {} // error!
    // ┌> ~ 
    // Type '{}' is not assignable to type 'Pick<T, Exclude<keyof T, keyof T>>
}
```

[Playground link](http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcA8AVAfACgJSIDeAsAFCIWIQIDOUiAXgFyIAKAhgE6zsA2mWRAF4iAX0QB6CYjgBrdgE8yosmTDsAtgFMaAB3YQtiALJwAJjGAwtZgCJarYGLFpEylRFAW6jHbjD5MABpEAGlELQAPKC0wMxpEWS0FOGBEDGFE5NT0wREAeQ1nYLDBADI3cg9KAG1WRBgkUIBdAH4WDDrmgG53SlFe0j6KLx9EACUtAEcQGE4bEvComLiEpJS0jJF1nOxMwuKMENDyyura+saw5oBadvSuwY8B1SqR7yNJ9jMEXgVFiLRWLxLIbdKZHabPKIA5QRanEhvarzb6-BSIOoNJrNDqPYaIF5DJGgSAuJAodDYfBnc5UWj0ZhsLg8fh7ESEcRSCKcThwTgAQnxHi5gBhSQQAP0QQsoXIwH0QAHIOQqGgkwHB6OwaDQYABzdQAI14RigcE88oVrBgEFkJQAopEILwQGYtGhIekQh7sFh8Soif7XkA)

I wouldn't advise altering predefined utility types unless there is a bug in them, since doing so changes other people's existing code and the *best case scenario* is that they won't notice.

**Comment by dragomirtitian** [comment]
I also worry about adding more complexity to the built-in types, it might make them harder to understand for beginners.

**Comment by RyanCavanaugh** [comment]
Changing these types is a guaranteed breaking change.

You can write these forms yourself if that's what you'd like to have; after the feedback from #30455 that we added the "wrong" `Omit` type we're completely uninterested in adding new built-in types where we have to make *any* semantic stylistic decisions unless it's absolutely necessary.
