### ISSUE TITLE
Make the type of caught errors unknown instead of any

### ISSUE THREAD

**Issue by devlato** [microsoft/TypeScript#35719]
## Search Terms

catch
unknown
any
catch statement
catch type

## Suggestion

Hey, I've noticed that the type of a caught error is `any`. Should it be `unknown` instead?

## Use Cases

I think the `any` type makes no real sense in terms of helping process the errors. The `unknown` has been designed in order to help devs ensure that they narrow down the types properly when the real type is unclear. I believe this type would fit perfectly to the catch statement.

## Examples

```typescript
try {
  somethingThatFailsAndProbablyThrowsAnError();
} catch (e) {
  // e is of unknown type instead of any type, to make devs narrow down the type
  // when they want to do something with the error
  // We have to narrow down the type, before using the value
  if (e instanceof Error) {
    // ... okay
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> This wouldn't be a breaking change in existing TypeScript/JavaScript code

It would be a heavy breaking change, and that's why it wasn't changed.

**Comment by devlato** [comment]
@MartinJohns Could this be introduced behind a configuration flag then? Ie. `--noCatchAny` 🙂

**Comment by RyanCavanaugh** [comment]
Duplicate #26174
