### ISSUE TITLE
Question : Is it possible to get specific code completions such as a list of constructors in JS after typing the keyword new ?

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#3571]
I don't know if it is possible to get such specific completions after the keyword new in JS using TypeScript, any advice ?

Thanks for your help guys !

**Comment by DanielRosenwasser** [comment]
Right now we don't do type-directed completion - we simply provide all entities in scope as well as keywords.

You could potentially use the returned completion data after a `new` to see if each entry has a construct signature or is a `void`-returning function, and filter that down.

**Comment by Yellowmat** [comment]
Thank you for your answers, you really help me !

Guessing if I'm currently typing a new statement shouldn't be to difficult, and if I just have to filter some results could easily make the job and be of good help.

I'll share my experience as soon as possible.

**Comment by mhegazy** [comment]
@DanielRosenwasser  can you log an issue to track contextual-type-driven completion?
