### ISSUE TITLE
Build watch takes 30x as long as cold build, high transformTime

### ISSUE THREAD

**Issue by lingz** [microsoft/TypeScript#35729]
**TypeScript Version:**  3.7.3 and 3.4.5

**Search Terms:** transformTime, Watch, Slow compilation

**Code**

When building our source code, we can do a cold build in about 25 seconds, but a watch build takes 15 minutes to start on Typescript 3.4.5. On Typescript 3.7.3, the watch time doubles to 30 minutes (60x as slow).

Running extended diagnostics shows that the vast majority of the time (96%) is spent on "transformTime". Is there any way to speed this up, as I do not consider our project too large on the grander scale (600k LOC). 

One thing that was causing slow builds that I already fixed and ruled out was the inlined type definitions bug mentioned in #34119, which cut my build time by a third. But even after this, I still get a very slow `transformTime`.

```
Files:                  3043
Lines:                637432
Nodes:               2372135
Identifiers:          850259
Symbols:             1167934
Types:                462989
Memory used:        2036527K
I/O Read time:         1.03s
Parse time:            2.81s
Program time:          6.12s
Bind time:             3.05s
Check time:           11.54s
transformTime time:  473.05s
commentTime time:      0.14s
I/O Write time:        0.43s
printTime time:      474.27s
Emit time:           474.27s
Total time:          494.99s
```

**Expected behavior:**

Watch build is slightly slower than cold build

**Actual behavior:**

Watch build is significantly slower

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
Can you please provide more details on repro. This seems like its taking long time to do declaration emit but I cant be certain.. Did you try running `tsc --d --extendedDiagnostics`. What do you see then.

**Comment by lingz** [comment]
@sheetalkamat the above pasted diagnostics is in fact from extendedDiagnostics and diagnostics emit only as you suggested. Let me know if any other information could help give clues.

**Comment by sheetalkamat** [comment]
We would need sample code for repro..

**Comment by weswigham** [comment]
Yeah, definitely going to need to see some sample code - when declaration emit takes a long time, it's usually because some type somewhere was easy to compute, but complicated to serialize. Did you check the sizes (and contents) of your output `.d.ts` files by compiling with `declarations` on?

**Comment by lingz** [comment]
I can't provide the source code unfortunately, but I did a CPU profile, and it seems like almost all the time is spent in GC, and `trySymbolTable`. I ran a size profile on the generated `.d.ts`, and they are all small files, almost all the files are only a few lines long (see size profile treemap below)

<img width="902" alt="Screenshot 2019-12-18 at 11 38 54" src="https://user-images.githubusercontent.com/3147213/71083705-8b551080-218b-11ea-956a-a1357c36575e.png">
<img width="257" alt="71001691-b54bfb80-20d5-11ea-9f69-faa5186a614e" src="https://user-images.githubusercontent.com/3147213/71083720-927c1e80-218b-11ea-99c5-fce1c409bae7.png">

**Comment by lingz** [comment]
Seems like the 1 mil symbols might be what is causing the slowdown. But I'm not sure what is causing such a high number of symbols, perhaps generated types?

Do you have any advice on identifying which files might be causing this high number of symbols?

**Comment by lingz** [comment]
I've managed to find out the culprit, and reduced the transform time from 473 seconds to 6 seconds.

It turns out it was a recursive type that was used only a few places in our code:

```ts
/**
 * The JSON version, without functions, methods, class
 */
export type LitNative = string | number | boolean | undefined | null | void;
export type WithoutFunctions<T> = T extends any
  ? Omit<T, FunctionKeys<Required<T>>>
  : T

export type Serialized<T> = T extends any[]
  ? InnerSerialized<T[number]>[]
  : (T extends LitNative ? T : InnerSerialized<WithoutFunctions<T>>);

type InnerSerialized<T> = {
  [k in keyof T]: T[k] extends any[]
    ? Serialized<T[k][number]>[]
    : Serialized<T[k]>
};
```

This type `Serialized` is recursive, and takes an object and gives a version of it without any functions (as if it went through JSON.serialize). It was only used a few places in the code but it was exploding the `transformTime`.

The way I found it, was after seeing that `trySymbolTable` was taking up most of the time, I ran the tsc compiler with the chrome inspector, and set a breakpoint on the function. I saw all the function calls were looking up Serialized over and over again. I would speculate that this could be mitigated by some caching in the tsc architecture?

The command I ran (in case it is helpful to others) is:

`node --inspect-brk $(which tsc) -p ./tsconfig.json --declaration --emitDeclarationOnly --extendedDiagnostics --declarationDir ~/Temp/declarations/out > ~/Temp/declarations/diagnostics.txt`

**Comment by AnyhowStep** [comment]
Is there a function that is supposed to return `Serialized<>`?
Is the return type of those functions implicit or explicit?

I ask because the return type of a generic function should **almost always** be explicit. This goes double for complex recursive types.

I have opened a bunch of issues in the past where emit goes **crazy** because I did not use an explicit return type annotation on a generic function.

TS is pretty bad at figuring out good emit for generic return types.

**Comment by ahrnee** [comment]
> I ran the tsc compiler with the chrome inspector

Hi @lingz - I am running into a similar issue, and trying to follow your debug process. Thanks for providing the command. Could you share a little more info about you managed to find the trySymbolTable function, and then set a breakpoint on it?

**Comment by lingz** [comment]
Hi @ahrnee , The whole typescript compiler is one flat JS file (on production builds), So just step inside the definition from the chrome terminal and search for the `trySymbolTable` function.

**Comment by lingz** [comment]
@AnyhowStep It was always explicit, but nonetheless, still causing this bug to emit.

**Comment by ConneXNL** [comment]
Ran into similar issues with a project that uses mobx-state-tree. I was using exported interfaces instead of types for most of it's typings but not all. This resulted I many of the types when referenced being recalculated because there is apparently not much caching going on with typescript types (other than interfaces).

After optimizing some typings from types and inline types to interfaces I went from 3min initial watch time to just 14 seconds whereas using tsc without watch was always fast and didn't improve much of anything.

I used the same methods as listed above, using tsc --declarations to find the biggest files with windirstat. In these files there were tons of duplicated nested types, one file was as large as 17MB. Because I run typescript with --noEmit via webpack I never knew this was the actual reason for it being so slow.

Just like OP for me "transformTime time" was also taken the longest time. After my changes that value dropped from minutes to just seconds.

**Comment by ShuiRuTian** [comment]
@lingz Sorry for asking, how does FunctionKeys<T> implement? It is amazing for me!

**Comment by grumd** [comment]
Just wanted to contribute that I get the same situation in my 600k LOC codebase:
![image](https://user-images.githubusercontent.com/5869818/99794366-b8940680-2b32-11eb-867f-bbcc8b1cd5a1.png)

**Comment by kumar303** [comment]
Just FYI, the new `--enableTrace` flag (I think that's it?) is documented in https://github.com/microsoft/vscode/pull/110534
