### ISSUE TITLE
Feature: visualize tool

### ISSUE THREAD

**Issue by Akimotorakiyu** [microsoft/TypeScript#35727]
## Search Terms

visualize 
## Suggestion

visualize tool
## Use Cases

teaching、debug or some activities need simple, clear and dynamic display

## Examples
Please have a look at the gif below

![loop-over-python-list-animation](https://user-images.githubusercontent.com/31165554/70997869-e7c71a00-2110-11ea-8801-76739ab549d9.gif)
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
That seems like something that goes way beyond the scope of TypeScript. 

Nothing prevents you from creating such a tool, and I think the resources of the TypeScript team are better used to improve the language and the compiler.
