### ISSUE TITLE
Declaration files generated by tsc output `any` for all fields for nested yup schemas

### ISSUE THREAD

**Issue by king-sam-perez** [microsoft/TypeScript#35720]
Posted in Yup's repo as well [here](https://github.com/jquense/yup/issues/726) since I'm unsure of the root cause.

Hi Typescript,

I am attempting to use yup to define schemas and associated typescript types. When I try to generate typescript declaration files for the schemas that I've written, I've noticed that the type information for any nested schemas is being lost and converted to any.

I've included a small example to illustrate the problem:

`example.ts:`

```
import * as yup from 'yup';

const NestedSchema = yup.object().shape({
  nested: yup.string()
});

export const TestSchema = yup.object().shape({
  working: yup.string(),
  broken: NestedSchema
});

export type Test = yup.InferType<typeof TestSchema>;
```

Run: `tsc -d example.ts`:

Actual generated example.d.ts:

```
import * as yup from 'yup';
export declare const TestSchema: yup.ObjectSchema<yup.Shape<object, {
    working: string;
    broken: yup.Shape<object, {
        nested: any;  // <---- TYPE INFORMATION LOST!
    }>;
}>>;
export declare type Test = yup.InferType<typeof TestSchema>;
```

Expected output:

```
import * as yup from 'yup';
export declare const TestSchema: yup.ObjectSchema<yup.Shape<object, {
    working: string;
    broken: yup.Shape<object, {
        nested: string;
    }>;
}>>;
export declare type Test = yup.InferType<typeof TestSchema>;
```

Another interesting bit of information is that my VSCode IDE is showing the correct types. My coworker and I did some digging around and figured out that the IDE is calling out to tsserver, which implies that tsserver is behaving differently than tsc and that tsserver is showing the intended result.

![image](https://user-images.githubusercontent.com/58450190/70955070-5f6b4b00-2024-11ea-8d77-75aa0cf91145.png)

Is this a known issue? Is there any workaround? Any help would be much appreciated!

Platform:

macOS Mojave 10.14.6
node: v10.17.0
yup: 0.27.0
@types/yup: 0.26.26
tsc: 3.7.3

To repro the issue locally, check out: https://github.com/kingsmendv/issue-yup-infer-type-any/blob/master/package.json

**Comment by hrajchert** [comment]
I think it's a bug in the emit declaration part of the compiler. In a project that I help with, the same problem occurs. While inside the project (both vscode and type checking), the types are correctly preserverd, when emitting the types that information is lost.

In the other project I managed to do a workaround by changing the mapped type, but the types are more ugly now :(

https://github.com/dggluz/parmenides/pull/10

**Comment by RyanCavanaugh** [comment]
We'd need a repro that doesn't depend on an external library in order to be able to investigate

**Comment by hrajchert** [comment]
Hi @RyanCavanaugh , the Parmenides project that I shared on the 24th doesn't have any dependencies (only devDependencies). https://github.com/dggluz/parmenides/blob/master/package.json

And the Pull Request that I submitted shows how to fix the problem by inverting the inference.

If you like I could try to isolate the problem in a new repo, but it will take me some time.

Let me know :)
