### ISSUE TITLE
Avoid listing missing properties on types with only call/construct signatures

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35735]
Found with @RyanCavanaugh 

```ts
interface Dog {
    barkable: true
}

declare function getRover(): Dog;

export let x: Dog = getRover;
```

# Expected

```
Type '() => Dog' is not assignable to 'Dog'.(2741)
  input.ts(7, 21): Did you mean to call this expression?
```

# Actual

```
Property 'barkable' is missing in type '() => Dog' but required in type 'Dog'.(2741)
  input.ts(2, 5): 'barkable' is declared here.
  input.ts(7, 21): Did you mean to call this expression?
```

**Comment by weswigham** [comment]
Hm, OK, but suppose
```
interface Dog {
    caller: {
        caller: {
            collar: boolean;
        };
    }
}

declare function getRover(): Dog;

export let x: Dog = getRover;
```
for which we issue
```
Type '() => Dog' is not assignable to type 'Dog'.
  The types of 'caller.caller' are incompatible between these types.
    Property 'collar' is missing in type 'Function' but required in type '{ collar: boolean; }'.(2322)
input.ts(4, 13): 'collar' is declared here.
input.ts(11, 21): Did you mean to call this expression?
```

what's the rule here? In the above example, I can't make a clear judgement call on which suggestion is more relevant.

**Comment by DanielRosenwasser** [comment]
If you are in the off case where you have a `name` that isn't a `string`, a `length` that isn't a `number`, or any property named `caller`, I'm sure you'll figure it out on your own.

**Comment by RyanCavanaugh** [comment]
When the return type of a function is an identity match for the target type, it seems extremely unlikely that "You forgot to call it?" is not the best possible error message. It requires a lot of construction to make something where a function *and its return type* are both plausible matches for the target.

I would be curious to find out how often a function is ever an intentional *source* for a *target* with zero signatures that isn't a top-ish type. Even assigning a function to something nominally uncontroversial like `{ name: string; age?; number }` *smells* like a bug, and people have complained to that effect.

**Comment by weswigham** [comment]
>I would be curious to find out how often a function is ever an intentional source for a target with zero signatures that isn't a top-ish type

I've seen assignments to `{length: number}` in the wild.

**Comment by openorclose** [comment]
Does this still need help? I would like to work on this.

**Comment by DanielRosenwasser** [comment]
Yes, we're still looking for help here!

**Comment by openorclose** [comment]
Ok, I'll work on this!

**Comment by DanielRosenwasser** [comment]
I think the fix should be relatively self-contained within `structuredTypeRelatedTo`, preceding the

```ts
                        result = propertiesRelatedTo(source, target, reportStructuralErrors, /*excludedProperties*/ undefined, intersectionState);
                        if (result) {
                            result &= signaturesRelatedTo(source, target, SignatureKind.Call, reportStructuralErrors);
                            if (result) {
                                result &= signaturesRelatedTo(source, target, SignatureKind.Construct, reportStructuralErrors);
                                if (result) {
                                    result &= indexTypesRelatedTo(source, target, IndexKind.String, sourceIsPrimitive, reportStructuralErrors, intersectionState);
                                    if (result) {
                                        result &= indexTypesRelatedTo(source, target, IndexKind.Number, sourceIsPrimitive, reportStructuralErrors, intersectionState);
                                    }
                                }
                            }
```

**Comment by liewrichmond** [comment]
Hi, I'm new here and would like to give this a try. Would anyone mind if I started working on this?

**Comment by RyanCavanaugh** [comment]
@liewrichmond go for it! 👍

**Comment by liewrichmond** [comment]
I've been working on a fix, and I think I might have one but it breaks a couple of tests that I'm not too sure if it's intended behavior or not.

For example, 
```typescript
interface Dog {
    barkable: true
}

declare function getRover(): Dog

let x: any[] = []
    
x = getRover;
```

### Before Change 
```
Type '() => Dog' is missing the following properties from type 'any[]': pop, push, concat, join, and 25 more.ts(2740)
```
### After Change
```
Type '() => Dog' is not assignable to type 'any[]'.ts(2322)
```
Is this within spec? and should I submit a PR to get feedback/suggestions on the other failing tests due to the change?

**Comment by DanielRosenwasser** [comment]
Yeah, that looks good. You can send a PR and we should be able to iterate on it.

**Comment by DanielRosenwasser** [comment]
Thank you @liewrichmond!
