### ISSUE TITLE
Autocomplete (auto import) of existing import broken 

### ISSUE THREAD

**Issue by frenic** [microsoft/TypeScript#35737]
*TypeScript Template added by @mjbvz*

**TypeScript Version**: 3.8.0-dev.20191216 & 3.7.3

**Search Terms**:
- auto import 
- automatic imports

---

In VSCode 1.40.2 it autocompleted `useEffect` -> `React.useEffect` when there already was an `import * as React from 'react'`. This stopped working as soon as I upgraded VSCode to 1.41.0.

![vscode issue](https://user-images.githubusercontent.com/237182/70801160-730d7c00-1dae-11ea-9ca5-7292f4d88bcd.gif)

- VSCode Version: 1.41.0
- OS Version: Windows 10

Steps to Reproduce:

1. Start typing `useEffect`
2. Wait for the "Auto import from 'react'" dialog to appear
3. Hit enter

Does this issue occur when all extensions are disabled?: Yes

**Comment by andrewbranch** [comment]
You know, I thought I repro’d this when it was first opened, but I can’t anymore, with any version of TS. Both the completion action and the code fixes work as expected.

![Kapture 2020-01-09 at 14 20 59](https://user-images.githubusercontent.com/3277153/72109803-821f1580-32eb-11ea-8936-89625943d847.gif)

Tried 3.7.3, 3.8.0-dev.20191216, master, Code Insiders, Code 1.41.1, TSX and JSX files, a few different tsconfig settings, messing with package.json, but no effect. @frenic @IllusionMH does this still repro for you? Any clues as to what I’m missing?

**Comment by frenic** [comment]
My VSCode is now upgraded to 1.41.1 and I can't reproduce this anymore. Had this problem with VSCode 1.41.0.

**Comment by IllusionMH** [comment]
Works as expected (same as on GIF) - `useEf` is replaced with `React.useEffect` when I accept auto-import suggestion. So looks like works now.

VSCode Insiders (1.42) and TS@next 3.8.0-dev.20200111

**Comment by andrewbranch** [comment]
Cool! I guess it was a VS Code bug after all. Thanks for confirming!
