### ISSUE TITLE
super[symbol] does not compile in TypeScript

### ISSUE THREAD

**Issue by blesh** [Microsoft/TypeScript#3573]
TSC complains about using `super[anything]` really, this is problematic for Symbols.

```
var symbol = Symbol.for('myThing');

class Foo {
  [symbol]() { console.log('myThing called'); }
}

class Bar extends Foo {
  [symbol]() {
    super[symbol]();
    console.log('in Bar');
  }
}
```

Output:

> 'super' must be followed by an argument list or member access..

**Comment by JsonFreeman** [comment]
I guess this is true for decorators as well.
