### ISSUE TITLE
wrogn type inference when interface is extended

### ISSUE THREAD

**Issue by steabert** [microsoft/TypeScript#35747]
**TypeScript Version:**  3.7.2

**Search Terms:** type inference, type inference failed, type inference interface, type inference extended interface

**Expected behavior:**

Type resulting from `a ?? b` is `A | B | undefined`.
Types on left and right of `d = b1` do not match up.

**Actual behavior:**

Type resulting from `a ?? b is A | undefined`.
Types on left and right of `d = b1` match up.

**Related Issues:**

**Code**
```ts
interface A {
    readonly a: number
}

interface B extends A {
    readonly b: string
}

let a: A | undefined
let b: B | undefined

let c = a ?? b // A | undefined instead of A | B | undefined ?
let d = a !== undefined ? a : b // A | undefined instead of A | B | undefined ?

const a1: A = { a: 1 }
const b1: B = { a: 2, b: "1" }
d = b1
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
let a;
let b;
let c = (a !== null && a !== void 0 ? a : b); // A | undefined instead of A | B | undefined ?
let d = a !== undefined ? a : b; // A | undefined instead of A | B | undefined ?
const a1 = { a: 1 };
const b1 = { a: 2, b: "1" };
d = b1;
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=17&ssc=1&pln=17&pc=7#code/JYOwLgpgTgZghgYwgAgILIN4Chm+VCOAEwHsQAbAT2TgC5kQBXAWwCNosBfLLUSWRCgBCyCAA9IIIgGc0mHHgLEyVZK3rSwUUAHMuPchDA166AD7JGUiDFAQiWQ8fXIRFq0Rt2Hjo8gTIALw0yAD8oWrIAPRRcu7WtiD2yKCahETIJDBxrsjxnonJob7GGcFwyACEgcEeXkkZERX0rNGx5pYJ3ikgacSZ2R1unQXdxVgIZJo0AIymQZgmyDPI3JO9znO5wRhLAEwANGr0AEQzJ6tYZWozQA)

**Comment by RyanCavanaugh** [comment]
Subtype reduction is the expected behavior here.
