### ISSUE TITLE
Generics compile error

### ISSUE THREAD

**Issue by chnliquan** [microsoft/TypeScript#35750]
**TypeScript Version:**  3.5.3

**Search Terms:**

**Code**

```ts
export function useLoading<T, U>(
  effect: (params?: T) => Promise<U>,
  initial = false
): [(params: T) => Promise<U | undefined>, boolean] {
  const [loading, setLoading] = useState(initial);
  const newEffect = async (params: T) => {
    setLoading(true);
    try {
      const result = await effect(params);
      return result;
    } catch (e) {
      message.error(e.message || '服务异常，请稍后再试');
    } finally {
      setLoading(false);
    }
  };

  return [newEffect, loading];
}

async function func(c: string) {
  return {
    a: 1,
    b: 2
  };
}

const [s, l] = useLoading(func);
```

**Expected behavior:**
run normally
**Actual behavior:**
Error: the param of the type “(c: string) => Promise<{ a: number; b: number; }>”can not assign to “(params?: string | undefined) => Promise<{ a: number; b: number; }>”

**Playground Link:** 

**Related Issues:**

**Comment by dragomirtitian** [comment]
The error is correct. You pass in a function that **requires** a parameter of type string, but `useLoading` accepts a function that *may or may not* receive a parameter of type string. Based on the signature, `useLoading` is free to call `effect(param)` or `effect()`. If `useLoading` were to call `effect()`, `func` would not receive it's required parameter.

Change the signature of `useLoading` to accept `effect: (params: T) => Promise<U>`, this means `useLoading` will always call `effect` with a single parameter of type `T`. The passed in argument is free to have a signature that uses this parameter or not:

```ts
export function useLoading<T, U>(
    effect: (params: T) => Promise<U>,
    initial = false
): [(params: T) => Promise<U | undefined>, boolean] {
    return null!;
}

async function func(c: string) {
    return ;
}

useLoading(async (c: string) => ({ a: 1, b: 2 })); // ok, required parameter  
useLoading(async (c?: string) => ({ a: 1, b: 2})); // ok, param is optional, but useLoading will always pass in the param 
useLoading(async () => ({ a: 1, b: 2})); // ok, inline function will ignore the param passed in by useLoading
```
[Playground Link](https://www.typescriptlang.org/play/?ssl=15&ssc=110&pln=2&pc=1#code/JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC+cAZlBCHAORTo4DGMVAsAFDoAekspyAdo2AQ+KDABkIOACbA+AcwA8AFQA0cAKoA+ABRs4+uOhIl0jAFxxtYHFBwhUFpQEo4AXk1wACuRDAMCrRU9A1lgGGAcABs3UiiMNicLAG0rGzsHOGc3D28KP3QAuAAfFD4pI1l0KU01ACMICEi6PgBdRGD9WhhkKBE+ZEjIgEIAbjZCNjYcVABPAV4BcOEF+m16C1QYKFk5FwQOuC6ekTHWCdY2NHQJaR3tabn6S3W4Te35F3dLJBwLAEY6hYAExEJxOEZwAD0kLgEAA1mpaABHZDAWhSODWWwgdD4KD6S7iSQyeT3WbzNYAfg2Wx2nw82h+-0BcCBhDBEOhsIRmLSlD8sLASz4UTqyHgVxuJLkcAA7sBBnAorKcDNULzUOrZHAYAALAhYuxwQnXYl3B4U+nfJXMuC1YHs8FQmHwtSySKVFbCuUK6LAOR8aAEPUGvkajAY7W1GaiU23eRAA)
