### ISSUE TITLE
Suggestion: #error directive

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#3575]
C# and C++ have a handy `#error` directive that results to a compiler error. It would not hurt to have something similar in TypeScript:
- https://msdn.microsoft.com/en-us/library/c8tk0xsk.aspx
- https://msdn.microsoft.com/en-us/library/x5hedts0.aspx

**Comment by mhegazy** [comment]
Can you share a scenario where this is useful in the absence of conditional compilation using preprocessor directives (i.e. `#ifdef`)

**Comment by aleksey-bykov** [comment]
Any block of code that is left unfinished during refactoring and requiring
my attention. An alternative would be to leave it unfinished without a
trace attracting attention and thus prone to being forgotten.

**Comment by aleksey-bykov** [comment]
A error raised should not be an early one like those of syntax, should be raised while doing senatic checking.

**Comment by danquirk** [comment]
Is // TODO (and an editor supporting task lists) and "throw new Error('not yet implemented')" that much worse? You lose a little compile time checking but little else. You could also use a linter to catch this kind of thing at compile time with some custom tag (// #error).

**Comment by aleksey-bykov** [comment]
True. Anything can be done with extra syntax served in comments and a
little patience. With a bit more patience a pen and a piece of paper one
can get a hard copy of their todo list. Low tech shoots and scores.

**Comment by aleksey-bykov** [comment]
Btw are there any plans to marry TypeScript with the Task list in Visual
Studio, so that // TODO's are seen there?

**Comment by danquirk** [comment]
Yep, VS2015 already has the Task List wired up like that.

**Comment by mhegazy** [comment]
> Any block of code that is left unfinished during refactoring and requiring
my attention.

you can just use `unknownFunction("not done")`, or `var n: number = "still needs some work";` to achieve the same result.

**Comment by mhegazy** [comment]
possibly reconsider if an applicable form of conditional compilation (#3538) is supported.
