### ISSUE TITLE
inconsistancy in type

### ISSUE THREAD

**Issue by calidion** [microsoft/TypeScript#35770]
**TypeScript Version:**  3.7.3

**Search Terms:**  error

**Code**

correct:
```ts
export function error(name: string) {
  return class extends Error {
    constructor(message?: string) {
      super(message);
      this.name = name;
    }
  };
}
```

wrong: 
```ts
export function error(name: string) : Error {
  return class extends Error {
    constructor(message?: string) {
      super(message);
      this.name = name;
    }
  };
}
```

error message:
```
(local class) (Anonymous class)
Property 'message' is missing in type 'typeof (Anonymous class)' but required in type 'Error'.ts(2741)
lib.es5.d.ts(974, 5): 'message' is declared here.
```

**Expected behavior:**

No compiling error.

**Comment by MartinJohns** [comment]
This works correctly. You're not returning an `Error` (the instance), but instead a constructor of an anonymous class extending `Error`. As an anonymous class it has no name and you can't provide an explicit type annotation.

**Comment by calidion** [comment]
Yes. 
This function returns a new class inherited from Error not a instance.
as `super(message)` showes that it is a derived class.
It's intuitive to have a type of Error for the new class.
