### ISSUE TITLE
function overloads not match

### ISSUE THREAD

**Issue by samao** [microsoft/TypeScript#35773]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
type PARAM<T extends (...args: any) => any> = T extends (...args: infer P) => any ? P : never;
declare function call<Fn extends (...args: any[]) => any>(fn: Fn, ...arg: PARAM<Fn>): void;

declare function log(name: string): boolean;
declare function log(age: number): void;
declare function log(user: { age: number, name: string }): string;

call(log, 'as');
```

**Expected behavior:**
match the signature `declare function log(name: string): boolean;`
**Actual behavior:**
Argument of type '"as"' is not assignable to parameter of type '{ age: number; name: string; }'.(2345)
**Playground Link:** 
http://www.typescriptlang.org/play/index.html?ssl=12&ssc=17&pln=1&pc=1#code/C4TwDgpgBACgggJTgWQDwBUoQB7AgOwBMBnKACgDoqBDAJwHNiAuKa-EASigF4A+V9v25RMOPEVKUaDZlACW+AGYRasLnwEgoAflhQW+CADcVAbgCwAKEIQAxgBs60RQFd8t4HID2+KLer29qgAYr5iBCTkVBR0jCxsIADaALrq-Am8ZIr4LKEANFDRsSzwSGihvBwsRl5yhBaWVlY2Dk5Qru6ePlD2XvRk+NQAthAsxMC0CvRVUABGXl72EGwNLY60zm4e3r69-dT0o1D4LkOzKjM1dat265udOz19ZC7EKiwA3qyHBqfntAVBiMxhMplAAL4zcaTfD0BpNRqI-yBMh7AoAcmoxHRHFMQA
**Related Issues:**

**Comment by MartinJohns** [comment]
[Type inference in conditional types](http://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types)

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.
