### ISSUE TITLE
`{['__proto__]: 1}` does not seem to be transpiled correctly

### ISSUE THREAD

**Issue by dubzzz** [microsoft/TypeScript#35786]
**TypeScript Version:**  3.7.2

**Context:**

While playing around with `__proto__` and `Object.create(null)` on TypeScript 3.7.2, I detected something that seems to be a bug. The es5-transpiled JavaScript code does not have the same behavior as the original es6-code.

TypeScript seems to fail to transpile (for es5 or before) objects defined with a key `__proto__` , with syntax `{ ['__proto__']: 1 }`.

_I am not sure it is a real bug so please feel free to close the issue_

**Search Terms:** \_\_proto\_\_

**Code**

```ts
const o = { ['__proto__']: 1 };
```

**Expected behavior:**

```js
"use strict";
var _a;
var o = (_a = {}, Object.defineProperty(_a, '__proto__', { value: 1 }), _a);
// Not sure this is the best syntax but it seems to work as the initial code snippet (es6)
```

**Actual behavior:**

But instead, it gets transpiled into:
```js
"use strict";
var _a;
var o = (_a = {}, _a['__proto__'] = 1, _a);
```

When targeting ES5 or before.

The resulting instance of `o` does not satisfy `o.__proto__ === 1` while it should be the case given it is the observed behavior with the original code.

**Playground Link:**

- https://www.typescriptlang.org/play/index.html?target=1#code/MYewdgzgLgBCMF4YG8YG0DkB9LAHATiFCDhgLoBcMAjDAL5A
- JavaScript behavior: https://runkit.com/dubzzz/proto-and-typescript

**Comment by RyanCavanaugh** [comment]
To truly fix this, we'd also have to deal with cases like
```js
{ ['1__PROTO__'.toLowerCase().substr(1)]: 1}
```
and there's not really even a fix at all for ES3.

This is also Babel's behavior FWIW. The recommended workaround is to either target ES6 or not aim the gun directly at your own foot 😉

**Comment by dubzzz** [comment]
Thanks for the update. Closing the issue.

A possible solution to handle this issue would be to always transpile towards `Object.defineProperty` for properties defined between brackets
