### ISSUE TITLE
Support for trailing closure syntax.

### ISSUE THREAD

**Issue by Xapphire13** [microsoft/TypeScript#35780]
## Search Terms
trailing closure

## Suggestion
Both Kotlin and Swift support trailing closures (see [Swift Documentation](https://docs.swift.org/swift-book/LanguageGuide/Closures.html#ID102)), which when a method's final argument is a function type, allows you to specify the lamda/closure/callback simply as a block of code, example:

```typescript
function foo(callback: () => void) {
  callback();
};

foo() {
  console.log("I'm a callback, look at me!");
}
```

## Use Cases
If TypeScript had support for trailing closures, JSX/TSX could be replaced entirely with core language features (rather than the current state of JSX/TSX being external and not part of the language) (See SwiftUI and TornadoFX). It would allow for react-like code to be written without external knowledge, and workaround the parsing ambiguity that causes things like type-casting to be disabled in a `.tsx` file.

It would also keep TypeScript aligned with other modern languages in terms of syntax, reducing the friction of people from Kotlin/Swift worlds learning TypeScript.

## Examples
(See the example from above)

Example of how JSX/TSX can be replaced:

**With TSX**
```typescriptreact
function MyComponent() {
  return <div>
    <SomeOtherComponent/>;
  </div>;
}
```

**With Trailing Closures**
```typescript
function MyComponent() {
  return div() {
    SomeOtherComponent();
  };
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> [x] This feature would agree with the rest of TypeScript's Design Goals.

I would say it goes against these goals:

> - Align with current and future ECMAScript proposals.
> - Avoid adding expression-level syntax.

And this non-goal:

> - Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.

This is definitely out of scope of TypeScripts goal (be JavaScript with types).

**Comment by Xapphire13** [comment]
@MartinJohns, that's fair. I guess this is more of a suggestion for TC39?

**Comment by DanielRosenwasser** [comment]
Yes, check out https://github.com/samuelgoto/proposal-block-params
