### ISSUE TITLE
Please show full version number on the web site

### ISSUE THREAD

**Issue by dannypike** [microsoft/TypeScript#35796]
When I look at your website, the "latest" version number that I can find is 3.7. However, when i install typescript@latest, I get version 3.7.3.

Please do not "simplify" the version number or, if you really want to, please put a big warning on your web site that the number shown is for people who are not programmers, i.e. those who might possibly be frightened by something as complicated as a full semver. I don't know why you would expect people to be reading your web site if they are not programmers but, then again. I think that rain is wet, so what do I know? :)

When you have added that warning, please also put a link to the real version number so that I can be certain that 3.7.3 (or whatever) really *is* the latest version!

Many thanks

**Comment by RyanCavanaugh** [comment]
> please put a big warning on your web site that the number shown is for people who are not programmers

Please don't be ridiculous.

3.7 is the latest scheduled release number and the version number we use to refer to in planning and roadmap documents. 3.7.3 is specific to the *npm* version, and there are other distribution formats that have slightly different version numbers (e.g. VS SDKs have *4* version digits).

If you're ever unsure about whether or not a release is "official", you can check the release lists on our repo.

**Comment by dannypike** [comment]
@RyanCavanaugh

Which file in the repo has the release lists for npm?
