### ISSUE TITLE
TSServer: navtree does not include entries for inline types

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#35793]
**TypeScript Version:**  3.8.0-dev.20191216

**Search Terms:**
- navtree
- outline
- tsserver

**Code**
For the TypeScript code:

```ts
export interface IFace {
    prop: {
        abc: string;
        xyz: string;
    };
}  
```

Run the `navtree` request on the file

**Bug:**
No entries for `abc` or `xyz` are returned.

VS Code uses `navtree` to implement: go to symbol, document outline, and breadcrumbs.

**Comment by RyanCavanaugh** [comment]
We implemented `navtree` with the expectation that it'd be used to populate the navigation tree bar, so it intentionally elides things that are usually small such as inline types, both for perf and UX considerations. It seems like you have an API request for something that does something else?
