### ISSUE TITLE
auto import not working properly

### ISSUE THREAD

**Issue by Tahir500** [microsoft/TypeScript#35792]
Issue Type: <b>Bug</b>

auto import is not working in the new udpate, it was working in the previous build 

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:59:52.065Z)
OS version: Windows_NT ia32 10.0.18363

here is a short video on that
https://drive.google.com/file/d/1inQ1yZGLSfxeXmGLcDl81nEsATyTrjik/view

![image](https://user-images.githubusercontent.com/30975443/71098897-3c7f9900-21d4-11ea-803b-ec35254bdb7b.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.12.2
gitlens|eam|10.2.0
prettier-vscode|esb|3.16.1
python|ms-|2019.11.50794
vscode-import-cost|wix|2.12.0

</details>

**Comment by mjbvz** [comment]
@Tahir500 Please share repo steps and code as text in addition to the videos

**Comment by SantoJambit** [comment]
@IllusionMH I am talking about direct dependencies. But I just tried using an older TS version with the same result, so maybe this is a vscode issue and not a typescript issue.
