### ISSUE TITLE
Nullish coalescing for default function params

### ISSUE THREAD

**Issue by moniuch** [microsoft/TypeScript#35798]
## Search Terms

- param nullish coalescing
- default function param value coalescing

## Suggestion

Just as we can leverage nullish coalescing for variables, I would like to be able to have it for default function param values. This function:

`function swatch(color = '#aaa'){}` 

will provide the default value for when it comes `undefined` but not when `null`. I would like it to handle null too through the following syntax:

 `function swatch(color ?? '#aaa'){}`

## Use Cases

Current state of things

#### Generic example

```ts
function swatch(color: string | null | undefined = '#ddd') {
    console.log('rendering color:', color)
}

swatch(undefined); // rendering color: #ddd
swatch(null); // rendering color: null
swatch(''); // rendering color: 
swatch('#bbb'); // rendering color: #bbb
```

####  Angular example

I use Angular's Forms API a lot - it uses `null` as the default value for AbstractControl, including when it is reset. If I need to somehow process the values by some another function/method, I need to add extra code to handle the `null` case. 

Assume a form which consists of a `color` control:

```ts
export class MyComp implements OnInit {
  form: FormGroup;
  
  ngOnInit(){
    this.form = new FormGroup({
      color: new FormControl(),
    });

    this.form.valueChanges.subscribe(
      ({ color }) => this.renderSwatch(color),
    )

    this.form.reset() // sets color value to null
  }

  renderSwatch(color = '#aaa'){
    // extra guard needed to handle `null`
  }
}

```

## Examples

Taking the generic example - please note the new syntax in the function signature.

```
function swatch(color ?? '#ddd') { // <- nullish coalescing of default param value
    console.log('rendering color:', color)
}

swatch(undefined); // rendering color: #ddd
swatch(null); // rendering color: #ddd
swatch(''); // rendering color: 
swatch('#bbb'); // rendering color: #bbb
```

## Checklist

I leave the checklist blank - not sure of the answers.

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment]
This doesn't agree with one of TS goals
> Align with current and future ECMAScript proposals.

This is not valid ES syntax at the moment and this case is not included in Nullish Coalescing proposal.

At this moment there is open issue https://github.com/tc39/proposal-nullish-coalescing/issues/31 but nothing new since Jul 2018

**Comment by moniuch** [comment]
> This doesn't agree with one of TS goals

Fair enough :) I just wanted to signal the improvement I would need, but I do understand that TS should be in with ECMAScript. Hope it will make to TC39 one day.

Can be closed then.

**Comment by chrisjallen** [comment]
can we reopen this question given the traction for this feature?? It would be super valuable to define 

`function(value ??= 100){`

I realise this might be more a js feature, is there any place I can look into declaring this as a possible enhancement?

**Comment by chrisjallen** [comment]
can we reopen this question given the traction for this feature?? It would be super valuable to define 

`function(value ??= 100){`

I realise this might be more a js feature, is there any place I can look into declaring this as a possible enhancement?

**Comment by moniuch** [comment]
@chrisjallen Please vote for the TC39 proposal (link in one of the comments). This FR cannot be implemented before the TC39 introduces the syntax as part of ES.

**Comment by IllusionMH** [comment]
[nullish coalescing operator](https://github.com/tc39/proposal-nullish-coalescing) already finished and is part of ES2020. So 👍 on that issue won't do anything.

New proposal should be created and it would need a delegate who can present it to committee
https://tc39.es/process-document/ describes flow for proposals.
