### ISSUE TITLE
Docs: Extend a documentation on how casting works

### ISSUE THREAD

**Issue by Hell4Ge** [microsoft/TypeScript#35817]
## Search Terms

<ul><li>cast</li></ul>

## Suggestion

A docs should clear how casting works since it's not like in any other language which I will explain later

## Use Cases

<ul><li>The docs</li></ul>

## Examples

According to https://www.typescriptlang.org/play/

This code:
```
const someStringNumber: string = '100';
const someNumber: number = someStringNumber as unknown as number;

console.log(typeof someNumber); // string
```
converts into
```
"use strict";
const someStringNumber = '100';
const someNumber = someStringNumber;
console.log(typeof someNumber); // string
```

Which does not make any sense, it does nothing and makes weird bugs during runtime.

It's the same here:
```
let foo: string = "100";
let xyz: number = <number><unknown>foo;
```

This compiles into
```
var foo = "100";
var xyz = foo;
```

**Comment by MartinJohns** [comment]
They're called type assertions, but they're often wrongly called casts. Perhaps you should clarify what about the documentation should be extended, as it seems quite clear to me.

[Type Assertions](http://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions)

> Type assertions are a way to tell the compiler “trust me, I know what I’m doing.” A type assertion is like a type cast in other languages, but performs no special checking or restructuring of data. It has no runtime impact, and is used purely by the compiler. TypeScript assumes that you, the programmer, have performed any special checks that you need.

**Comment by RyanCavanaugh** [comment]
It seems like you're confused by the very thing the documentation specifically describes, so I'm not sure what else to do.
