### ISSUE TITLE
Create type Math on Window, in lib.d.ts

### ISSUE THREAD

**Issue by aicioara** [Microsoft/TypeScript#3581]
`tested with tsc 1.5.0-alpha`

```
var n = window.Math.min(1, 2);
```
`error TS2339: Property 'Math' does not exist on type 'Window'.`
Workaround:
```
var n = (<any>window).Math.min(1, 2);
```

This does not seem alright. It seems normal to have `Map`, `Set`(ES6), `Map`(ES6) available on `Window`. Please let me know if this is not the correct way to access `Math`

**Comment by kitsonk** [comment]
Is there a reason you aren't doing?

```ts
var n = Math.min(1, 2);
```

**Comment by mhegazy** [comment]
if you want to augment window, just add the definition as such:
```ts
interface Window {
    Math: typeof Math;
}
```

**Comment by mariusschulz** [comment]
@mhegazy This solves the problem, but I'm still wondering: Is there any reason *not* to add this typing (directly or augmented) to *lib.d.ts*?

**Comment by mhegazy** [comment]
Window is considered the global polluter. any thing you put on the global scope in a js file in a web context, is accessible of window, and this in the global scope. Use of window/this/global scope to declare variables is considered an anti-pattern, and accessing global of window hinders your code from working with other js environments, e.g. node. TypeScript opted in a more conservative world view where you do not pollute the global namespace by default, and you need to declare any of these pollutants. Math and DOM APIs are not any different in this sense from any other user defined variables.
