### ISSUE TITLE
First class type constructor 

### ISSUE THREAD

**Issue by 2A5F** [microsoft/TypeScript#35816]
## Search Terms
first class type alias constructor hkt variadic generics transitivity independent independence first-class first-class-type first-class-type-alias first-class-type-constructor variadic-generics higher-kinded-types hrt higher kinded rank types rank-n

## Suggestion
Add first class type constructor support  

### This proposal contains the following features
- HKT (Higher Kinded Types)
- Variadic Generics
- Independent type constructor
- Transitivity of type constructor

### HKT 

```ts
interface Functor<F extends type<T>> {
    map<A, B>(f: (a: A) => B, s: F<A>): F<B>
}
```
  
The following uses this `'type' ('<' <args>,+ '>')? <return>?` syntax  
although this syntax has compatibility issues

This is already very useful, but there are many other problems

### Transitivity & Independence
 ```ts
declare function foo<T>(v: T): T
type params = Parameters<typeof foo>    // type params = [v: unknown]
type rets = ReturnType<typeof foo>      // type rets = unknown
  ```

[Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVAPgAoA3ALnhIEo6SBYAKAwE8AHBb2KAFsAzvAC88AAoDBIDCBjCiXXjkQEcZdioRwMoiQCU5yGKhI8Qyy2o1kgA)
  
Because it is not transitive, generics are discarded during inference,  
so we need the type constructor to be transitive,  
and this requires that the type constructor must be independent

with transitivity and independence, this will be 

```ts
declare function foo<T>(v: T): T
type params = Parameters<typeof foo>    // type params = type<T> [v: T]
type rets = ReturnType<typeof foo>      // type rets = type<T> T
```

Independent type constructor should not exist at runtime,  
so when an independent type constructor is used as a type without being applied,  
the generic type should be discarded again

```ts
let a: ReturnType<typeof foo><1>    // let a: 1
let b: Parameters<typeof foo><1>    // let b: [v: 1]

let c: ReturnType<typeof foo>       // let c: unknown
let d: Parameters<typeof foo>       // let d: [v: unknown]
```

The transitivity of type constructors should also exist on type aliases

```ts
type params = type<T> [v: T]    // type params<T> = [v: T]
type rets = type<T> T           // type rets<T> = T
```

\*  
This `type` syntax is very loose,  
You can represent not only type constructors with parameters,  
but also type constructors without parameters,  
or you can optionally fill in the return type in the type parameter  

```ts
type num = type number          // type num = number
```
```ts
type Foo<T extends type<A, B> A | B> = T
// This means T extends type<A, B> => R where R extends A | B
// or like associated-types in rust | swift
// type<A, B> {
//  type R: A | B
// }

type Bar<T extends type<A>> = T
// For external T extends type<A> => unknown
// For internal T extends type<A> => anonymous nominal unique type
```

### Variadic Generics

The current improvised solution is  

```ts
type Foo<T extends any[]> = T
```

Normally this is enough, but it is not free enough when the type constructor is transitive  
if has variadic generics, then the type constructor can be inferred  

- Variadic syntax
  ```ts
  type Foo<...T extends any[]> = T

  type Bar = Foo<1, 2, 3>   // type Bar = [1, 2, 3]
  ```

- Infer TypeReturnType
  ```ts
  type TypeReturnType<T extends type<...A extends any[]> any> =
      T extends type<...A extends any[]> infer R ? R : never

  interface Foo<T> { a: T }
  type Bar<A, B> = A | B

  type use = TypeReturnType<Foo>    // return type<T> { a: T }  or return Foo
  type use = TypeReturnType<Bar>    // return type<A, B> A | B
    ```
- Infer TypeParameters
  ```ts
  type TypeParameters<T extends type<...A extends any[]> any> =
      T extends type<...A extends infer P> any ? P : never

  type Foo<A, B> = any

  type use = TypeParameters<Foo>    // return type<A, B> [A, B]
  ```

### Compatibility

It is a pity that although this `type` syntax is very readable, it has compatibility issues  

```ts
type type = 1
type foo = type
```

Other possible syntax

```ts
type A = type: any
type A = type<B>: any

type A = type: any
type A = type:<B> any

type A = (type = any)
type A = (type<B> = any)

type A = ~any
type A = ~<B>any

type A = any
type A = <B>any

type A = for any
type A = for<B> any
```

### What is First class Type constructor

`* -> *` is type constructor  
`(* -> *) -> *` is HKT  
`* -> * -> *` is binary type constructor with currying
`(* -> *) -> (* -> *)` is first class type constructor without currying but with transitivity, independent

## Examples

```typescript
interface Monad<T extends type<X>> {
  map<A, B>(f: (a: A) => B): T<A> => T<B>
  lift<A>(a: A): T<A>
  join<A>(tta: T<T<A>>): T<A>
}
```

```typescript
function mixin<B extends type<...P extends any[]> new (...a: any[]) => any>(Base: B) {
  return class<...P extends TypeParameters<B>> extends Base<...P> { }
}
class A<T> { }
class B<T> extends mixin(A)<T> { }
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Reference

#1213  
https://github.com/microsoft/TypeScript/issues/1213#issuecomment-370763683  
#5959  
#29904  
#30215  
#31116  
#41040  
#44875  
#48036  
#48820  

[first-class-protocols](https://github.com/michaelficarra/proposal-first-class-protocols)

**Comment by RyanCavanaugh** [comment]
What's the differentiation between this and #1213 or other HKT issues?

**Comment by 2A5F** [comment]
@RyanCavanaugh 
this can return a HKT

**Comment by 2A5F** [comment]
I revisited #1213, this may be the same as https://github.com/microsoft/TypeScript/issues/1213#issuecomment-370763683

**Comment by 2A5F** [comment]
@RyanCavanaugh Can you update the labels?
should this issues keep open?

**Comment by 2A5F** [comment]
#### Follow-up proposal 
## Type Extension 

```ts
type <T>.Foo = [T]
type foo = 1.Foo      // foo is [1]

type <A>.Bar<B> = [A, B]
type bar = 1.Bar<2>   // bar is [1, 2]
```

```ts
type <O>.Omit<K> = Omit<O, K>
type <O>.Map<F extends for<[keyof O, O[keyof O]]>> = { [K in keyof O]: F<K, O[K]> }
type <O>.Vals = O[keyof O]

type OmitValue<O, T> = O.Omit<O.Map<for<K, V> V extends T ? K : never>.Vals>
// same to
type OmitValue<O, T> = Omit<O, { [K in keyof O]: O[K] extends T ? K : never }[keyof O]>
```
