### ISSUE TITLE
Parameters type for union of function types returns union of their parameter types

### ISSUE THREAD

**Issue by kimamula** [microsoft/TypeScript#35819]
**TypeScript Version:**  v3.8.0-dev.20191219

**Search Terms:** Parameters utility type, Conditional Types

**Code**

```ts
type UnionOfFunctions = ((arg: number) => any) | ((arg: string) => any)

// Parameters declaration in lib.es5.d.ts
// type Parameters<T extends (...args: any) => any> = T extends (...args: infer P) => any ? P : never;

type TypedWithParameters = Parameters<UnionOfFunctions> // [number] | [string]
type TypedDirectly = UnionOfFunctions extends (...args: infer P) => any ? P : never // [number] & [string]

const a: TypedWithParameters = [1] // no error
const b: TypedDirectly = [1] // Type 'number' is not assignable to type 'never'.(2322)
```

**Expected behavior:**

Both of `TypedWithParameters` and `TypedDirectly` should be evaluated as `[number] & [string]`

**Actual behavior:**

`TypedWithParameters` is evaluated as `[number] | [string]` which is not consistent with the invariant feature of function parameter types.

[**Playground Link**](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191219&ssl=7&ssc=22&pln=7&pc=39#code/C4TwDgpgBAqgdgSwPZwPIDMBiBXOBjYZOAZygF4oAKSgQwCcBzALijmwFsAjCOgSnIB8UGnBD8APlVqMWxYHQRwG-MkJFiAUBoD02qAAV6NdhGA9SAEwh4ANkcIooiqDYScAdBGIBWdxffAxDp6oJAGRiZmdMQAPAAqUBAAHmZwFqSU7ln0DMQs6ipqokIUCcmp6VRZ7jl5TnDoPAaFwqJQAPwGUCxwEABuPADcWqHQceAQFgDqCMAAFoZ0xqbm5OFLkeYx8EQYOPgOJEK6UADabFw8ALpQkqdyCkpXGqNQ45AWACIIdNbANiA1jsUHtcAQiKRyhA0hlqrUWIpGnRmoJWoDOvpuqx+k0TucONw6DcAGRnB6KBjPDR4FByYQsd6TGbzRbLKKkCinACMNxOcCQiTodCQdGptOAUE4DImXx+fwBa25vL0jKgAHILoS1U5SPyJTRiMQEAw4DRODZoMABa8NTi6Gr3JQAEwAZidTt4QA)

**Related Issues:**

**Comment by dragomirtitian** [comment]
This is working as intended.  

`Parameters` is a [distributive conditional](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types) type so it will extract the parameters from each union member and union the result, resulting in `[number] | [string]`

In the other case the conditional type is not distributive, so Ts will try to figure out what type can satisfy **BOTH** signatures at the same time. The only type that could do this would be an intesection of parameter types resulting in `[number] & [string]`

**Comment by kimamula** [comment]
@dragomirtitian Thanks for the response.

> In the other case the conditional type is not distributive

Well, the distributive conditional document says:

> an instantiation of `T extends U ? X : Y` with the type argument `A | B | C for T` is resolved as `(A extends U ? X : Y) | (B extends U ? X : Y) | (C extends U ? X : Y)`

Then, why ` (((arg: number) => any) | ((arg: string) => any)) extends (...args: infer P) => any ? P : never` is not resolved as `(((arg: number) => any) extends (...args: infer P) => any ? P : never) | (((arg: string) => any) extends (...args: infer P) => any ? P : never)`?

It looks to me that TypeScript introduces an exceptional behavior here to make sure that function types are invariant to their parameter types, which should be also introduced into the `Parameters` utility type.

**Comment by dragomirtitian** [comment]
@kimamula The docs also say : 
> Conditional types in which **the checked type is a naked type parameter** are called distributive conditional types.

When you write `UnionOfFunctions extends ...` you do not fulfill the requirements for your conditional type to be distributed. The requirement is for the checked type to be a **naked type parameter**. While `UnionOfFunctions` is a type it is not a type parameter.

When the similar type is written in `Parameters`, then the checked type is a naked type parameter (`T extends ...`) so distribution kicks in.

The fact that conditional types distribute only over naked type parameters is a bit surprising at first, but it usually works out the way you would expect when using them.

**Comment by kimamula** [comment]
@dragomirtitian Thanks for the response again!
I am sorry that I did not read the doc carefully. Now I understand what you mean.

Though this behavior is really confusing, I understand this is how TypeScript works.

```ts
type UnionOfFunctions = ((arg: number) => any) | ((arg: string) => any)

// [number] | [string], which likely means UnionOfFunctions can be executed with number | string
type TypedWithParameters = Parameters<UnionOfFunctions>

declare const f: UnionOfFunctions
f(1) // error
f('a') // error
```

Thanks so much again for your kind explanations.
