### ISSUE TITLE
do you guys heard of anyscript? a new type of typescript

### ISSUE THREAD

**Issue by zzz6519003** [microsoft/TypeScript#35829]

**Comment by Kingwl** [comment]
yes。

**Comment by zzz6519003** [comment]
> yes。

gonna be a big problem

**Comment by xiaoxiangmoe** [comment]
As an Angular user, we have no choice but to use AnyScript, which is new version of Google AtScript.

**Comment by AnyhowStep** [comment]
Never heard of it. Googling it just brings me to this issue lol.

Since we're bringing up random TypeScript variants, here's one.

https://arxiv.org/pdf/1604.02480.pdf

Refinement types for TypeScript

**Comment by DanielRosenwasser** [comment]
Nope, I have not.

**Comment by zzz6519003** [comment]
> As an Angular user, we have no choice but to use AnyScript, which is new version of Google AtScript and it missing many strict type checks. (no strict type check in template and input and so on)

I would suggest flow or reason~.~
