### ISSUE TITLE
Incorrect JSON generated using simple Class 

### ISSUE THREAD

**Issue by ttony** [Microsoft/TypeScript#3582]
Hi there,

please visit the link as the sample code which shows the problem

http://www.typescriptlang.org/Playground#src=%09class%20Simple%20%7B%0D%0A%09%2F%2F%09constructor(private%20_name%3A%20string)%20%7B%7D%0D%0A%09%0D%0A%09%09private%20_name%3A%20string%3B%0D%0A%09%09%0D%0A%09%09get%20name()%20%7B%0D%0A%09%09%09return%20this._name%3B%0D%0A%09%09%7D%0D%0A%09%09%0D%0A%09%09set%20name(name%3A%20string)%20%7B%0D%0A%09%09%09this._name%20%3D%20name%3B%0D%0A%09%09%7D%0D%0A%09%7D%0D%0A%09%0D%0A%09var%20a%20%3D%20new%20Simple()%3B%0D%0A%09a.name%20%3D%20%22tony%22%3B%0D%0A%09%0D%0A%09alert(JSON.stringify(a))%3B%0D%0A

The JSON generated should be {"name": "tony"} rather than {"_name: "tony"} since _name is private field and there is a property get/set for _name.

Cheers,

-Y

**Comment by DanielRosenwasser** [comment]
This is simply the semantics of `JSON.stringify`, and is what you'd get in the analogous ES6 code.

**Comment by DanielRosenwasser** [comment]
Hi @ttony, this is simply the semantics of `JSON.stringify`, and is what you'd get in the analogous ES6 code.

Property accessibility is purely a compile-time construct, and so these fields are still accessible at runtime.

**Comment by kitsonk** [comment]
If you really need to serialize your classes/objects differently, you can provide a `toJSON()` function to provide the right behaviour.  It is exampled at MDN's [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior).

**Comment by DanielRosenwasser** [comment]
@kitsonk's suggestion seems pretty great - thanks for pointing that out!

**Comment by PLEEROCK** [comment]
I think some solution should be found for this problem. providing function to toJSON method each time you dont want your private methods to be exposed is overkill. 
>  is what you'd get in the analogous ES6 code.
right, but in ES6 there is no `private` properties. Since typescript introduces new feature "private properties" that is not in es6, it should handle it proper way. And right now Im not sitisfied the way it works - it should not expose my class's private data

**Comment by kitsonk** [comment]
It would be complicated and surprising.  What if someone wants toJSON to serialise the state of their objects, which includes `private` properties?  What solution would you offer them @PLEEROCK?
