### ISSUE TITLE
Assertion function error messages are unactionable and unclear

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35838]
```ts
class Foo {
    bar?: Foo

    public setBar(): asserts this is Foo & {bar: Foo}  {
        this.bar = this;
    }

    public sayHi(): string {
        return 'Hi!';
    }
}

function test() {
    let foo = new Foo();

    foo.bar = undefined;

    foo.setBar();

    if (foo.bar) {
        console.log('This should be OK: ' + foo.bar.sayHi());
    }
}
```

Current error

```
Assertions require every name in the call target to be declared with an explicit type annotation.

'foo' is declared here.
```

`foo` is declared here but... but okay so what am I supposed to do now??

**Comment by threehams** [comment]
Is it possible this would make arrow function assertion errors even more confusing, given their use it marked as a design limitation in https://github.com/microsoft/TypeScript/issues/34523? This example would (I think?) result in the error `constAssert requires an explicit type annotation`, which is still unclear.

```typescript
function funcAssert (condition: boolean): asserts condition {
    if (!condition) {
        throw new Error();
    }
}

const constAssert = (condition: boolean): asserts condition => {
    if (!condition) {
        throw new Error();
    }
}

(thing: number | null) => {
    funcAssert(!!thing); // this is fine
    thing;
}
(thing: number | null) => {
    constAssert(!!thing); // why doesn't this work, and what am I supposed to do?
    thing;
}
```

https://www.typescriptlang.org/play/?ssl=21&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABKSBBAzugpgJyogCggQBMZYEAuRAIzjgBssBDMASmuc1ynUWLBkKSAN4AoRJMQxghAIQCh8donFT1iKAAsccAO6IwWAwFEcunATYBuCVIC+Yx2IHp8rqBmx5EAXkKK5MrUdIws7JzceHyBwn4AfKp2kjLyscpsSRpS2roGRqbmcJY2yYiOzgTaMGAA5tRgIAC2NLiIAD6GIAwMmb6JalIoEF48BHJy1XU2iAD0s5paMHzLyDVYZVO1to5VS3UNza04HV09fQNlHqN445P7tTPziHpaAJ6IJHBY6GAA5Phqnw9MUANYAGkQrBILy0zHwzCaiAAkoh0CAAA4YuDYGFQOCfOAAfk2Dx2YiAA
