### ISSUE TITLE
lib.d.ts HTMLTableElement, HTMLTableSectionElement, and HTMLTableRowElement

### ISSUE THREAD

**Issue by sockfish** [Microsoft/TypeScript#3583]
A couple of html table related methods in lib.d.ts return HTMLElement, but they could return a more precise type:

- HTMLTableElement.insertRow should return HTMLTableRowElement instead of HTMLElement
- HTMLTableElement.createTHead should return HTMLTableSectionElement instead of HTMLElement
- HTMLTableElement.createTBody should return HTMLTableSectionElement instead of HTMLElement
- HTMLTableElement.createTFoot should return HTMLTableSectionElement instead of HTMLElement
- HTMLTableElement.createCaption should return HTMLTableCaptionElement instead of HTMLElement
- HTMLTableSectionElement.insertRow should return HTMLTableRowElement instead of HTMLElement
- HTMLTableRowElement.insertCell should return HTMLTableCellElement instead of HTMLElement

**Comment by djarekg** [comment]
How about also HTMLTableElement cells and rows property return a new generic type HTMLCollectionOf<T extends HTMLElement> where cells is HTMLCollectionOf<HTMLTableCellElement> and rows is HTMLCollectionOf<HTMLTableRowElement>

**Comment by matthewrwilton** [comment]
Seems like this didn't make v1.6. Is it possible to get a milestone update?

**Comment by mhegazy** [comment]
@zhengbli is working on releasing the script that generates the typings file. it should come out shortly, and with that we should be able to take PRs for features like this one. putting it on @zhengbli for now.

**Comment by zhengbli** [comment]
The `HTMLTableElement.rows` is not only `HTMLTableRowElement`, it also contains headers and other types [spec](http://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-6156016), the same goes for `HTMLTableRowElement.cells`.

**Comment by zhengbli** [comment]
I have a PR fixing this at https://github.com/Microsoft/TSJS-lib-generator/pull/24
If you want to take a look @mhegazy @sockfish
