### ISSUE TITLE
Consider disallowing tagged templates with tags returning type predicate types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3584]
Basically the following is kind of absurd:

```TypeScript
function tag(strs: any, x: any): x is number {
    return typeof x === "number";
}

let x = Math.random() < 0.5 ? 100 : "100"; // x: string | number
if (tag `Hello ${ x } world`) {
    // x: number
    // But why didn't you just use a function call?
    x.toExponential();
}
```

This is the dual suggestion of #3554: see https://github.com/Microsoft/TypeScript/issues/3554#issuecomment-113865503.

**Comment by mhegazy** [comment]
I do agree that this is absurd, and hence do not see the value of fixing it. inclined to resolve this as won't fix.

**Comment by DanielRosenwasser** [comment]
@mhegazy this issue is for disallowing it instead of silently failing.

**Comment by mhegazy** [comment]
It is not failing. the guard will not work. similarly to `typeof x == "string"` does not work, and there is no warning for it either. if we hear enough complains about it we can restrict it. i do not see much probability of the two features being used in conjunction in real world scenarios.
