### ISSUE TITLE
Lack of type check in "for in" expression

### ISSUE THREAD

**Issue by asurance** [microsoft/TypeScript#35847]
**TypeScript Version:**  3.7.2

**Code**

```ts
type Key = 'a' | 'b'

type NMap = { [key in Key]: number }

const MapA: NMap = {
    a: 1,
    b: 2,
}

let sum = 0;
for (const key in MapA) {
    sum += MapA[key];
}
console.log(sum)
```

**Expected behavior:**
`key` in `for in` expression will be identified as `Key`.
**Actual behavior:**
`key` is identified as `string`,and error `No index signature with a parameter of type 'string' was found on type 'NMap'`
**Playground Link:**
http://www.typescriptlang.org/play/index.html?ssl=13&ssc=2&pln=1&pc=1#code/C4TwDgpgBA0hJQLxQOQEMVQD6oEYoFgAoY0SKAOQFk0wkoBvKAbQGt4oBLAO1ngF0AXFG4BXALa4IAJygBfYsQDGAe24BnYFBpgAgsOq16DYlDNQ0wgIwAaU+dzCATHaIKSRADYQt6ifQAGAG5iADMVWQAKVQ0tdgQebVpdAEpGezM-cSgAamQdXTYBELcgA

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208

> Note that the changes we made to for-in specifically apply only when objects have a type parameter type. In for (let x in obj) ... where obj is of type T, if T is a type parameter we infer keyof T for x, but otherwise we infer type string. To do the same for Object.keys would require some way to constrain a type argument to only be type parameter, which currently isn't possible.

**Comment by zq0904** [comment]
I want to know what causes for in to use the key directly in typescript as a type of string
The current finding is that when a function is generic it is resolved correctly
so:

const obj = {
  a: 1,
  b: '2'
};

function forIn<T>(cb: (key: Extract<keyof T, string>) => any, obj: T) { 
  for (const key in obj) cb(key)
}

forIn((key) => {
  console.log(key, obj[key])
}, obj)

**Comment by asurance** [comment]
> I want to know what causes for in to use the key directly in typescript as a type of string
> The current finding is that when a function is generic it is resolved correctly
> so:
> 
> const obj = {
> a: 1,
> b: '2'
> };
> 
> function forIn(cb: (key: Extract<keyof T, string>) => any, obj: T) {
> for (const key in obj) cb(key)
> }
> 
> forIn((key) => {
> console.log(key, obj[key])
> }, obj)

I find another bug in `for in` expression.`key` should be type of `keyof T` instead of `Extract<keyof T, string>`.For example, key of `obj = { a: 1, b: '2', 0: 3 }`should be `0 | "a" | "b"`

**Comment by zq0904** [comment]
First, the object's key must be a string, not a Map
But how do I get to "0" | "a" | "b" I don't know
If you have a good idea, please exchange thanks

**Comment by asurance** [comment]
> First, the object's key must be a string, not a Map
> But how do I get to "0" | "a" | "b" I don't know
> If you have a good idea, please exchange thanks

```ts
const obj = {
    0: 1,
    a: 2,
    b: 3
}

type keyType = keyof typeof obj

function test(key: keyType) {
    return obj[key];
}

test(0);
test('a');
test('b');
```
Use `keyof` will get ` 0 | "a" | "b" ` and I don't know how to tranform  from type `0` to type `"0"`

**Comment by RyanCavanaugh** [comment]
This is a correct error, because we don't know that `MapA` is *exactly* a `NMap`. For example, this code is legal and corrupts `sum`:

```ts
const obj = {
    _: "haha",
    a: 1,
    b: 2,
}
const MapA: NMap = obj;

let sum = 0;
for (const key in MapA) {
    sum += MapA[key];
}
```

**Comment by asurance** [comment]
> This is a correct error, because we don't know that `MapA` is _exactly_ a `NMap`. For example, this code is legal and corrupts `sum`:
> 
> ```ts
> const obj = {
>     _: "haha",
>     a: 1,
>     b: 2,
> }
> const MapA: NMap = obj;
> 
> let sum = 0;
> for (const key in MapA) {
>     sum += MapA[key];
> }
> ```

So the key point is that `NMap` works as an interface?
