### ISSUE TITLE
Strict null checks on function arguments not working properly

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#35843]
**TypeScript Version:**  3.7.4

**Search Terms:**

**Code**

```ts
interface A {
	get(key: string | undefined): number
}

interface B {
	get(key: string): number
}

declare const a: A
declare const b: B

function f(arg: A) { }

f(b) // get does not accept undefined! null-check error!
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** [playground](https://www.typescriptlang.org/play/?ssl=8&ssc=1&pln=9&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4CgCQBzCMACgGsIBPALmQGcwpQ9kAfZAVxABMIZQJOAlNRBsAtgCNoWAL5YsoSLEQoAQplwFiZKrXqMhyERKmys3BABs4UFAgD2IOsjjVUZiJeu2HT8dRVyMBwIYMAOyDBE1niuApjIppHiAkA)

**Related Issues:**

**Comment by AnyhowStep** [comment]
A `strictMethodTypes` flag would be nice but it won't be around for a long time, if ever =/

https://github.com/microsoft/TypeScript/issues/20263

https://github.com/microsoft/TypeScript/issues/35669

https://github.com/Microsoft/TypeScript/pull/18654

https://github.com/microsoft/TypeScript/issues/20530#issuecomment-350016722
> Things written in method syntax are still checked bivariantly due to people being broadly bad at writing class hierarchies that actually achieve substitutability (e.g. the DOM).

**Comment by AnyhowStep** [comment]
In the mean time, you can do this,
```ts
interface A {
	get : (key: string | undefined) => number
}

interface B {
	get : (key: string) => number
}
```

**Comment by ccorcos** [comment]
Wow, I had no idea there was a difference between functions and methods as far as TypeScript is concerned. Very confusing.

As for your reasoning about ES APIs being terrible, it seems a like a good strategy is to have a strict typechecker and cast where necessary.

**Comment by AnyhowStep** [comment]
Not my reasoning. I quoted @RyanCavanaugh 

I would love for it to be implemented =P

**Comment by ccorcos** [comment]
Ok. Well feel free to close this issue if that makes sense.
