### ISSUE TITLE
Invalid "could be instantiated with a different subtype of constraint" error

### ISSUE THREAD

**Issue by vmajsuk** [microsoft/TypeScript#35858]
**TypeScript Version:**  3.7.2, also tested in nightly (3.8.0-dev.20191224)

**Search Terms:**
"is assignable to the constraint of type", "could be instantiated with a different subtype of constraint"

**Code**

```ts
function test<T extends {accepted: boolean}>(cb: (value: T) => void) {
  return (data: Omit<T, 'accepted'>) => cb({...data, accepted: true});
}
```

**Expected behavior:**
No error

**Actual behavior:**

```
Argument of type 'Pick<T, Exclude<keyof T, "accepted">> & { accepted: true; }' is not assignable to parameter of type 'T'.
  'Pick<T, Exclude<keyof T, "accepted">> & { accepted: true; }' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{ accepted: boolean; }'.
```

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191224&ssl=1&ssc=1&pln=4&pc=1#code/GYVwdgxgLglg9mABFApgZygHgCqJQD1TABM1EBvAQwghQAdViAuRAIzjgBsVKwBfAHwAKCKxZCAbpU4gULbAEpEAXgGIJcGMSXkAUIkQAnFFBCGkQ4pSiUWAeQC2MLNgA0iAOTVaDFMQ8CSqqIokLkAHSRVjbu3vSMLFCGsnwKANy6fLpAA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
`T` could be instantiated with `{ accepted: false; }`, couldn't it?

**Comment by vmajsuk** [comment]
> `T` could be instantiated with `{ accepted: false; }`, couldn't it?

1. I believe that's not the reason, changing `accepted: boolean` to `accepted: true` still gives the same error: http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191224&ssl=4&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABFApgZygHgCqJQD1TABM1EBvAQwghQAdViAuZAJxBQF8A+ACggBGLXgDdKAGw4tsASkQBebohFwYxOeQBQiRKxRQQrJL2KUolFgHkAtjCzYANIgDk1WgxTFn3OYsSDecgA6ENNzJzd6RhYodi4ZAG5NTk0gA

2. Even if it was the reason, this would be incorrect from types point of view:
`cb: (v: T) => void`, `T extends { accepted: boolean }` -> we should be able to call `cb` with argument of type `T & {accepted: true}`

**Comment by RyanCavanaugh** [comment]
TS isn't capable of the higher-order reasoning needed to understand that `Exclude<T, k> & { [k]: T[k] }` is equivalent to `T`. You can only make that determination through understanding what `Exclude` and `&` actually do at a higher level.

**Comment by mrcoles** [comment]
I find this usage of `Omit` to be really useful for HOCs, and found it unintuitive that Typescript runs into this design limitation.

In this example, is there any better approach than just doing a type assertion, e.g.,

```typescript
function test<T extends {accepted: boolean}>(cb: (value: T) => void) {
  return (data: Omit<T, 'accepted'>) => {
    const newData = {...data, accepted: true} as T;
    return cb(newData);
  }
}
```

**Comment by dwjohnston** [comment]
Is this here the same problem? 

```
type MyType = {
  somethingFromHoc: string; 
}

type DerivedType<T extends {}, U extends T> = Omit<U, keyof T>; 

const anotherThing = <P extends MyType>(input: DerivedType<MyType, P>): P =>{
  return {
    ...input,
    somethingFromHoc: "hello"
  };j 
}
```

https://www.typescriptlang.org/play/?ssl=15&ssc=1&pln=1&pc=1#code/C4TwDgpgBAsiAq5oF4oG8BQUoGcD2AthMABYCWAdgOYBiAToQBJ4DGAXLsHZVQNxQYAvhgyhIUACIRuANwgATRJAA88KBAAewCBXk50ggDRQAquq069UeAD4oqAPIEywZSeMBrCCDwAzazb8Iix4FDjAUACGFHik0vDk1PZQygAK5tq6+nBKEDYAFJRgAK7AHFKyCrnKOUjGqTYAlBzpyDaY2HTExXQU6FjYUAB0I0WlhgPY+ESkPPRMrBwARCQQADZreEsDgrwAVgLCIkA


Is easily solved with an `as P` assertion.

**Comment by inad9300** [comment]
I would like to expose a simpler example for which an unexpected error is emitted too, that perhaps helps in tracking down the issue here:

```ts
/*
Type '"foo"' is not assignable to type 'T'. '"foo"' is assignable to the constraint
of type 'T', but 'T' could be instantiated with a different subtype of constraint
'"foo" | "bar"'.
*/
function f<T extends 'foo' | 'bar'>(t: T = 'foo') {}
```

**Comment by jakajancar** [comment]
@inad9300
I'm pretty sure you want just:

    function f(t: 'foo' | 'bar' = 'foo') {}

Otherwise what happens if `T` is instantiated with `'bar'`?

    function f<'bar'>(t: 'bar' = 'foo')

The error message is super accurate here.

**Comment by inad9300** [comment]
Inlining the type as in your first snippet would not allow type reuse, unfortunately.

Perhaps what should happen is, an error should be issued when the conflicting situation occurs, and not before. With the overall goal of avoiding having to provide generics explicitly as much as possible, I'd be typically doing things like `f()` or `f('bar')`. In this case, TypeScript reporting this error before it actually happens hinders type inference, which is one of the best features of the language.

**Comment by ro7584** [comment]
There's another solution  if you don't want to use `as` to casting
Thanks for my workmate😍

[Playground Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191224&ssl=1&ssc=1&pln=4&pc=1#code/GYVwdgxgLglg9mABFApgZygHgCoD4AUEARgFyL4BuAhgDYgpnaIBkiA3olRBCgA6oATMkThwaKKkgC+ASkQBeXIgpwYAuWwBQiRACcUUELqT4BVKFUZzFiYvjYA6J2YsAaTtz6CyUXfVkA3JpSmkA)

``` typescript
function test<T>(cb: (value: T & { accepted: boolean }) => void) {
  return (data: T) => cb({...data, accepted: true});
}
```

**Comment by dminkovsky** [comment]
This confused me for a long time. 

I expected [this](https://www.typescriptlang.org/play/?jsx=1&ssl=32&ssc=1&pln=33&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgAUcwBnOJADzCQyQBM4AjAJ5wA7lBRhOfNLkgA7JHJjlgSpFEzok9RiwDe5OEbgoA5kgBccOQFcQ-dRQC+lGjojNWHLjF5wmnGjAmMBoKAA24cJCcERMNuEwqqZwMuAQCkoqahpacAASdHAGxqkQ4dBWTDBQyc6utPkA8gDCJlCmTNm+uWjaTWAwTAA8Rey+cjwsDB5MAHzFhsYtshmKMFbI6DAAdCvpmTAAKoKco3NLRmBEmOqKfVU1deQu5DJy1QWtcAC8cKNeCZTdzMOYACj0cH28nWABo4NckLciHI+nAnFYBkNzgBKTbEXbQtZKE5nQpwABk9AWPwupQhMgqUHhO1Z11mGIKRSpdBxvzppWMYMugtKwx4wAAbv4YIJwkgfnpIYzoOinALRZriojkfckC4tVrhkTDiLDZq9KyduzmAbzYKqBrDcMqBLJU7SjjKG8Mp8AIKScLAPx-ZotYaQsyWax2BxQUhwHgoXyPWpyFLqiEinV3VHR-AwGxQADWSEE+FhIpN6ysEJM5nhSd86L5tP+brmeijTmKTf1Lo7Ly9Po+8GQkzufD+YNbC2GAbAQb8KqgPwARGAi4ukGv6wq9AAmACMPb764DtXCcGP8KPAE47wBWXeOoA) should work, but it did not.

But [this](https://www.typescriptlang.org/play/?jsx=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgAUcwBnOJADzCQyQBM4AjAJ5wA7lBRhOfNLkgA7JHJjlgSpFEzok9RiwDe5OEbgoA5kgBccOQFcQ-dRQC+lGjojNWHLjF5wmnGjAmMBoKAA24cJCcERMNuEwqqZwMuAQCkoqahpacAASdHAGxqkQ4dBWTDBQyc6utPkA8gDCJlCmTNm+uWjaTWAwTAA8Rey+cjwsDB5MAHzFhsYtshmKMFbI6DAAdCvpmTAAKoKco3NLRmBEmOqKfVU1deQu5DJy1QWtcAC8cKNeCZTdzMOYACj0cH28nWABo4NckLciHI+nAnFYBkNzgBKTbEXbQtZKE5nQpwABk9AWPwupTB11mVnJVLoON+dNKxjBly5pWGPGAADd-DBBOEkD89JCZBUoFZGcwdrLoOinJy+ZriojkfckC4tVrhkTDrzDZq9DsrYqmAbzVyqBrDcMqIKhU7SjjKG8Mp8AIKScLAPx-ZotYaQsyWax2BxQUhwHgoXyPWpyFLqiG8nV3VHR-AwGxQADWSEE+FhvJN6ysEJM5nhSd86PZtP+brmeijTmKTf1Lo7Ly9Po+8GQkzufD+YNbC2GAbAQb8KqgPwARGAi4ukGv65K9AAmACMPb764DtXCcGP8KPAE47wBWXeOoA) did. 

See how the only difference is the extracted props. After messing around for a long time I suspected it was the extracted props, then saw @dwjohnston's [post on SO](https://stackoverflow.com/questions/61265219/is-assignable-to-the-constraint-of-type-p-but-p-could-be-instantiated-with) that pointed me here. Rough!

**Comment by artola** [comment]
> Is this here the same problem?
> 
> ```
> type MyType = {
>   somethingFromHoc: string; 
> }
> 
> type DerivedType<T extends {}, U extends T> = Omit<U, keyof T>; 
> 
> const anotherThing = <P extends MyType>(input: DerivedType<MyType, P>): P =>{
>   return {
>     ...input,
>     somethingFromHoc: "hello"
>   };j 
> }
> ```
> 
> https://www.typescriptlang.org/play/?ssl=15&ssc=1&pln=1&pc=1#code/C4TwDgpgBAsiAq5oF4oG8BQUoGcD2AthMABYCWAdgOYBiAToQBJ4DGAXLsHZVQNxQYAvhgyhIUACIRuANwgATRJAA88KBAAewCBXk50ggDRQAquq069UeAD4oqAPIEywZSeMBrCCDwAzazb8Iix4FDjAUACGFHik0vDk1PZQygAK5tq6+nBKEDYAFJRgAK7AHFKyCrnKOUjGqTYAlBzpyDaY2HTExXQU6FjYUAB0I0WlhgPY+ESkPPRMrBwARCQQADZreEsDgrwAVgLCIkA
> 
> Is easily solved with an `as P` assertion.

@dwjohnston What about this approach?
@RyanCavanaugh Could you please if this is an acceptable way?

```ts
function withOwner(owner: string) {
  return function <T extends { owner: string }>(
    Component: React.ComponentType<T>
  ): React.ComponentType<Omit<T, "owner"> & {owner?: never}> {
    return function (props) {
      const newProps = { ...props, owner };
      return <Component {...newProps} />;
    };
  };
}
```

https://www.typescriptlang.org/play?strictFunctionTypes=false&jsx=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoczAVwDsNgJa4B3YGACwHkXakoAFBF78AXHADOMKMFoBzAJRwA3uThwiMalGY16MRswA8AFThIAHjCS0AJhJVxhfKOKkz5cAL4A+AWvU4AGFcSD5aGHFkdBgAOhDwJhsYEwBPMCRTHwCFKOI4hLDktIyjLhB2UwAaAmd+fB84ADIVOqgAfnE+ADd+XxUA9U1tXToGJjgBMBwwCSVVQMC0Jik4PhYABRmHAF5HWIPpiFmatu8KRaGkLR04I0KkiJUD2PWt44kvOAB6HwvArz-QHkLyUGDpJDBFAwd6zOB7BZwAA2wF6Ei61BAACN+P82m5pLI5BRgXpxswgtCBMpkaikBJTiIoN5xJSYdt5gFhrd-IsjLZUdlLip8ARQcKALJIYTiZQotFeGo8FyytriwJGb4C7pCuAKEmUZa0VbKpC2Nnw1jsbhMgT4CQsVIWfAKARs-WUe7Q2lonbKACcXzaO3tjudPz+P2+cE4wAcEg4EGoSNscBxcEwsiQ5DKInN3vl9L9gacTJDDqdot+pCjMY4cckieTqY4KF6cBQMYhAFEoDgoDnTfn4IWJMWvtXa7H402U2nIZm+JRyOCMnAACIQOSwhyI2goEBIAkeOQBfGSQnyEFUMYGCabuTU-eHxkuLziB87zlXG7GbWNAB1CAIEwWVnyQRU4FNVxWiZLxNX-a8jRNPMH0tNhOGgu0K2dV0Hw9T00PAkNM1sCBRWDUNKwjGtvmjadGyTOd00XbNcz4WwiIPJASOAMiKLLKjw0nOi6wbBMmJbNtIU7VckF7ftB1Qrc1m43j+Joqd6xnST5wzLMgA

**Comment by anlauren** [comment]
I was digging into that Omit problem because it is quite a limitation to use generic types. I am not sure if it is related, but even without using `omit` i am discovering something that not consistent.
This, does not seem to generate any error:

```typescript
type A = {
    "id": string
}

function test<T extends A>(a: T): T {
    a.id = "other"
    return a
}

```

even if i use `test` with a more specific subtype of `A`
```typescript
type B = {
    "id": "test"
}

const b : B = {"id": "test"}

const c = test<B>(b) // here c is of type B, but... does not have the key "id": "test"!
```

Which is even going to generate the an error if i then compare the "id" key:
```typescript
c.id === "other"; // generates : "This condition will always return 'false' since the types '"test"' and '"other"' have no overlap."
```

Not sure if I should raise another issue with this, but it is the same problem with than with `Omit`. Typescript should not let you call a function with generics if they contain a constant. Or maybe i am missing something basic here?

**Comment by ZitroWasTaken** [comment]
Hi! I am stuck with (supposedly) same error. Code:
```ts
enum WellKnownTag {
    TEST,
    TEST2
}

class Tag<T extends WellKnownTag, K extends typeof TagTypes[WellKnownTag]> {
    tag: WellKnownTag;
    value: K;

    constructor(tag: T, value: K extends typeof TagTypes[T]? typeof TagTypes[T]: never) {
        this.tag = tag;
        this.value = value; // => Should be no error, but this throws
    }
}

const TagTypes = {
    [WellKnownTag.TEST]: "",
    [WellKnownTag.TEST2]: 0
};

new Tag(WellKnownTag.TEST, "0"); // => No error
new Tag(WellKnownTag.TEST, 0); // => Error

new Tag(WellKnownTag.TEST2, "0"); // => Error
new Tag(WellKnownTag.TEST2, 0); // => No error
```

The class Tag should construct without errors only if:

- first arg is member of `enum WellKnownTag`
- second arg is the corresponding type in `const TagTypes`.

Link to playground: https://www.typescriptlang.org/play?ssl=16&ssc=1&pln=16&pc=15#code/KYOwrgtgBA6sA28DSID2B3EAVAhgcygG8BYAKCgqiwFEBlLAGjMqrqwCYyBfMsgY3g4AzkKr4APFijAAHgBdQAE1FxEKDNnwMoSafKWi5ATwAOwVADMxeLKeBCA2quRpMuPAF0AfEWaU5+ABcsAguGu4A3H4UAG448GDAwUhRpNFQfKggQnIATmB8cqi5ABQBeMGMUHEJSTp6CiDKUMZmlta2Zo5YHgD8LXbt7p32Dj3BIMAxwLkAlL7kLP4AFgCWQgB05VAAvC34qUsr6xs1ibvV8YkRUAD0t7s+tMuoYPCKUABGwFBo0rm5YraT5gOQtNaGZaA9BCdI8Ujw-hZHIdOyiPYkRYUJyhdRufAbGj0DzBABEpKYWKgOLUrk0eEJbHYJKgAAZuKkyJN0NYSs48fTGfRtKTWaTZjd7o8oAA5VD-QG5LnAHnuPm4unuIVVVkSu4PHY+agA4q8Ujc3n8zUEokcEVivVSw1QY2K5Wq-Dq2nhG1M7S6yUGnxyhXFIA

**Comment by RyanCavanaugh** [comment]
Locking since this is garnering a lot of off-topic discussion not really related to the original post
