### ISSUE TITLE
Allow async functions to return any type that implements Promise.

### ISSUE THREAD

**Issue by DaanVandenBosch** [microsoft/TypeScript#35856]
## Suggestion

Async functions should be able to return anything that implements the Promise contract (then, catch and finally, I assume). I don't know whether this conforms with the ES standard, but it works in browsers.

I know this has been talked about before and decision was to limit the return value to Promise and only Promise for the time being. But I don't believe this makes much sense. TypeScript uses structural typing everywhere since this is basically what ES does at runtime, why make an exception here?

Is there a workaround at the moment, aside from annotating every async function with `// @ts-ignore TS1064`?

## Use Cases

Custom promise implementations with special behavior or extra functionality. In my specific use case I have a DisposablePromise type that has a dispose method that cancels the promise when called. It would be very convenient if I could use the async await syntax with it.

## Examples

```typescript
type DisposablePromise<T> = Promise<T> & { dispose() };

declare function f(): DisposablePromise<string>;

async function g(): DisposablePromise<number> {
    return (await f()).length;
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
Have you actually tried it?

That is not how `async` functions work.

```ts
type DisposablePromise<T> = Promise<T> & { dispose() : void };

async function g(): DisposablePromise<number> {
    const promise = Promise.resolve(0);
    (promise as DisposablePromise<number>).dispose = () => { 
        console.log("Called");
    };
    return promise as DisposablePromise<number>;
}

const promise: DisposablePromise<number> = g();
promise.dispose();
```

[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=19#code/C4TwDgpgBAIglgZzAewQQwEYBsIAUBOyAtohADwAqAfFALxQHGmU0BkUA3lACaIoIQAFAEooALigA3ZHG5QAvgG4AUMrQIQAOwDGUAGYBXHcDjJNUAOYiJ8JKkw5GJAWU0GiGCPhodlUf1DaZgjAUGCEztD0TqQAdPgQCMhYkkIADMIqAVCC4UwCUOqwfPbYeBHMbh5eVMKxvHYF9CJ0PlB+2QFBmkk4sVjIVgBEAMJoWDjcQ5kd-kqzUAnABvjmeZGFCMWNDuX55FWe3iryqt0hYRUCNiXoZTEuhzV0liIq63EN-EKZQA)

![image](https://user-images.githubusercontent.com/5655961/71452325-ecfc1880-2751-11ea-9338-e593ca35ca3b.png)

**Comment by AnyhowStep** [comment]
```ts
async function g() {
    const promise = Promise.resolve(0);
    promise.dispose = () => { 
        console.log("Called");
    };
    return promise;
}

const promise = g();
promise.dispose();
```

![image](https://user-images.githubusercontent.com/5655961/71452334-0c934100-2752-11ea-9127-dafb650f413f.png)

**Comment by DaanVandenBosch** [comment]
It's not clear to me why that wouldn't work. I'm reading the ECMAScript spec at the moment to get some clarity on how async and await really work.

Here's a [gist](https://gist.github.com/DaanVandenBosch/8833707b723b018dd1cda5aa41fae7c6) with a JS version of my DisposablePromise implementation. At the end you can see an example of typical usage. It shows that it is at least possible to await a custom promise implementation. Returning a custom promise from an async function does indeed seem to wrap it in a regular promise.

So it seems that the way TS handles async return types is actually in conformance with the ES spec. I'm going to leave this ticket open until I can explain exactly what's going on. I think it would good to have a place with a clear explanation to send people to when this comes up again.

**Comment by jcready** [comment]
An async function always returns a native Promise instance to the caller. Inside an async function you can `await`/`return` anything. If the value you `await`/`return` is `then`-able (e.g. has a `then` property which is a function that takes one or more callback functions as input) then the resultant value will be whatever is supplied to the first callback function, unless that value is another `then`-able then the process repeats. But no matter how you slice it, the result of calling an async function will **always** be a native Promise instance.
