### ISSUE TITLE
`(0, object.property)()` produces TS2695

### ISSUE THREAD

**Issue by dead-claudia** [microsoft/TypeScript#35866]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** Left side of comma operator is unused and has no side effects

(This only brought 7 results in total at the time of writing.)

**Code**

```ts
let list = [() => { }];
(0, list[0])();
let object = {fn: () => { }};
(0, object.fn)();
```

**Expected behavior:** It to type-check without errors - this is a common idiom to invoke functions without setting `this` to the property it's on, and it's fairly broadly used.

**Actual behavior:** TS2695: Left side of comma operator is unused and has no side effects on both calls

**Playground Link:**  https://www.typescriptlang.org/play/index.html?ssl=3&ssc=11&pln=3&pc=5#code/DYUwLgBMCWDOkF4IG0AUBKCCB8EDeEAvgLoDcAUKgAwA0UcYyVx6GFokA9gEYBWIAY0T4AZgDsAXBAxZcBQoQrU6PfkIB041ulJA

**Related Issues:** #12978 #33646

**Comment by ilogico** [comment]
`void 0` :)

**Comment by ajafff** [comment]
Fix is up at #35878

**Comment by MattShaile** [comment]
Any chance we can get this PR merged?

**Comment by shicks** [comment]
The PR was dropped because the author seemed to have abandoned it.  I'd be willing to push it through if there's interest.
