### ISSUE TITLE
Missing specific types in DateTimeFormatOptions

### ISSUE THREAD

**Issue by ksoldau** [microsoft/TypeScript#35865]
**TypeScript Version:**  3.7.3

**Search Terms:** Intl.DateTimeFormat, DateTimeFormatOptions, date format types

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp,
(See below)
```
DateTimeFormatOptions interface missing specific types.
https://github.com/microsoft/TypeScript/blob/408b17649a1197a52f68fcb49b8c2f1eeac13668/src/lib/es5.d.ts#L4253-L4267

**Expected behavior:**
I would expect the types to match what's listed here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

```ts
  interface DateTimeFormatOptions {
        localeMatcher?: 'lookup' | 'best fit';
        weekday?: 'long' | 'short' | 'narrow';
        era?:  'long' | 'short' | 'narrow';
        year?: 'numeric' | '2-digit';
        month?: 'numeric' | '2-digit' | 'long' | 'short' | 'narrow';
        day?: 'numeric' | '2-digit';
        hour?: 'numeric' | '2-digit';
        minute?: 'numeric' | '2-digit';
        second?: 'numeric' | '2-digit';
        timeZoneName?: 'long' | 'short';
        formatMatcher?: 'basic' | 'best fit';
        hour12?: boolean;
        timeZone?: string; // this is more complicated than the others, not sure what I expect here
    }
```
**Actual behavior:**
```ts
 interface DateTimeFormatOptions {
        localeMatcher?: string;
        weekday?: string;
        era?: string;
        year?: string;
        month?: string;
        day?: string;
        hour?: string;
        minute?: string;
        second?: string;
        timeZoneName?: string;
        formatMatcher?: string;
        hour12?: boolean;
        timeZone?: string;
    }
```
**Playground Link:** 

**Related Issues:** 
Couldn't find any

**Comment by RyanCavanaugh** [comment]
Would be a breaking change; we'll have to discuss.

**Comment by andreipfeiffer** [comment]
I would expect these to break only if you misspelled an option, which won't work anyway.
I'm just curious what other Breaking Changes are you thinking about @RyanCavanaugh .

**Comment by johan** [comment]
> Would be a breaking change; we'll have to discuss.

I'd love to see this discussed, or move forward. To me, moving runtime exceptions out of js into hard compile-time errors in typescript is one of the strongest points of typescript to begin with.

**Comment by sandersn** [comment]
Here's a breaking change:

```ts
function makeOptions(matcher: string): DateTimeFormatOptions {
  return {
    year: 'numeric',
    formatMatcher: matcher
  }
}
```

The author of `makeOptions` will have to propagate the stricter type of `formatMatcher` out, possibly breaking its consumers.

**Comment by johan** [comment]
So… …is there some process where you tag all PR:s with fixes for under-specified types like this by something like "improvement for next major version bump", so you can land a busload of such fixes in batch whenever you decide that enough of those have piled up since last time, or that you are just about to release a major version bump anyhow, because of some non-type-related fix to typescript itself?

If not, I think it would be a good process to introduce, so we don't get stuck forever with a lot of DOM / TC39 types that are a notch or two better than the `any` type.

**Comment by ShuiRuTian** [comment]
An advice:
write like 
"x"|"y"|string
And there would be no break.
What we need to do is to wait #33471.

**Comment by johan** [comment]
> Maybe you could write like `"x"|"y"|string`
> And there would be no break changes.

Much or most of the value a strict type here brings _is_ in flagging illegal string values as illegal. The documentation aspect of calling out a few explicitly legal values is nice, but we'd miss the catching bugs at compile time aspect for everything else that the browser definitely explodes on.

**Comment by mhuggins** [comment]
Running into this issue for `dateStyle` and `timeStyle` options as well.

**Comment by lgrahl** [comment]
> Running into this issue for `dateStyle` and `timeStyle` options as well.

I wonder if these are even related. Should we create a separate issue for that? Because those two properties are just missing entirely.

**Comment by BradStell** [comment]
Until this gets fixed you can extend the TypeScript definition for `DateTimeFormatOptions` by writing the following code in your project's root `index.d.ts` file

```
declare namespace Intl {
  interface DateTimeFormatOptions {
    dateStyle?: 'full' | 'long' | 'medium' | 'short';
    timeStyle?: 'full' | 'long' | 'medium' | 'short';
  }
}
```

**Comment by allan-chen** [comment]
Would like to add that the full exhaustive list of properties is here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

Includes more keys such as `calendar`, `numberingSystem`, `dayPeriod` etc that are also missing.

**Comment by plauclair** [comment]
We don't like to replace basic TS declares unless necessary, so we extend the base. For that reason I just created a complete type from the MDN docs.
```ts
/**
 * Better DateTimeFormatOptions types
 * 
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat for representation details
 */
export interface DateTimeFormatOptions extends Intl.DateTimeFormatOptions {
  localeMatcher?: 'best fit' | 'lookup';
  weekday?: 'long' | 'short' | 'narrow';
  era?:  'long' | 'short' | 'narrow';
  year?: 'numeric' | '2-digit';
  month?: 'numeric' | '2-digit' | 'long' | 'short' | 'narrow';
  day?: 'numeric' | '2-digit';
  hour?: 'numeric' | '2-digit';
  minute?: 'numeric' | '2-digit';
  second?: 'numeric' | '2-digit';
  timeZoneName?: 'long' | 'short';
  formatMatcher?: 'best fit' | 'basic';
  hour12?: boolean;
  /**
   * Timezone string must be one of IANA. UTC is a universally required recognizable value
   */
  timeZone?: 'UTC' | string;
  dateStyle?: 'full' | 'long' | 'medium' | 'short',
  timeStyle?: 'full' | 'long' | 'medium' | 'short',
  calendar?: 'buddhist' | 'chinese' | ' coptic' | 'ethiopia' | 'ethiopic' | 'gregory' | ' hebrew' | 'indian' | 'islamic' | 'iso8601' | ' japanese' | 'persian' | 'roc',
  dayPeriod?: 'narrow' | 'short' | 'long',
  numberingSystem?: 'arab' | 'arabext' | 'bali' | 'beng' | 'deva' | 'fullwide' | ' gujr' | 'guru' | 'hanidec' | 'khmr' | ' knda' | 'laoo' | 'latn' | 'limb' | 'mlym' | ' mong' | 'mymr' | 'orya' | 'tamldec' | ' telu' | 'thai' | 'tibt',
  hourCycle?: 'h11' | 'h12' | 'h23' | 'h24',
  /**
   * Warning! Partial support 
   */
  fractionalSecondDigits?: 0 | 1 | 2 | 3
}
```

**Comment by johan** [comment]
Maybe close this issue, now that it's been addressed in a released typescript? (Albeit without the useful docs of https://github.com/microsoft/TypeScript/pull/38522 or the above suggestion.)

**Comment by buzinas** [comment]
> Maybe close this issue, now that it's been addressed in a released typescript? 

Which one? Still facing the problem with v4.2.3.

**Comment by imakarenko** [comment]
@buzinas, hi also had an issue when updated typescript to 4.2.3, but the problem was with other dependencies which also use/define DateTimeFormatOptions, so I updated `react-intl` and `@formatjs/intl-datetimeformat` to the latest versions and the error had gone. You should check other components in your project.

**Comment by buzinas** [comment]
I don't have any other dependencies in my project. I'm only using VS Code and setting it to use typescript `v4.2.3`.

**Comment by GintV** [comment]
typescript playground doesn't recognize opts like dateStyle or timeStyle, so I don't think this was address in ts at all

https://www.typescriptlang.org/play?ts=4.2.3#code/FAOwpg7gBAIghgFzACgJQDoEHsAyWDGcANmAMoIBOAliAObICuIAJmAGY1jMA0UA3lGaIyCAJ4kAXFABEbBkSLSoAX1TBQkWMLSZcBYiOp1GLdpx78oCKgFsR4sFNnzFK1EA

**Comment by arusahni** [comment]
[It appears to be available if you're targeting ES2020](https://github.com/microsoft/TypeScript/blob/f7ef1540d3c10fb282d1d433d9f2850b28391169/src/lib/es2020.intl.d.ts#L280-L288).  The TS Playground demo passes type checking if I change the target to ES2020.

**Comment by BPScott** [comment]
This issue can be closed. As of TS 4.2 these types are use unions of strings where possible per;

https://github.com/microsoft/TypeScript/blob/v4.3.5/src/lib/es5.d.ts#L4332-L4346 and https://github.com/microsoft/TypeScript/blob/v4.3.5/src/lib/es2020.intl.d.ts#L280-L288

Note that you will need to target es2020 or otherwise add it to your `lib` for the properties defined in `es2020.intl.d.ts` to be present

**Comment by mhuggins** [comment]
I'm not seeing `dateStyle` or `timeStyle` in there.
