### ISSUE TITLE
Enum members aren't subtype reduced in unions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35867]
```ts repro
enum E {
    A,
    B,
    C,
}

function f(x: E | undefined) {
    return x ?? E.C;
}
```

Expected `f` to have type `E`, but instead it has type `E | E.C`

[Playground](http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20191224&ssl=1&ssc=1&pln=9&pc=2#code/KYOwrgtgBAolDeAoKKoEEA0zUCEuqgGEsBfRRAMzBAGMAXASwHsQoKAKADwC5YoAfKNQAmwCgxDBhASgTYUAJ2B0wC1pygB+TbAB0hANyISQA)

Doesn't have anything to do with `??` - can reproduce it with `||`.

```ts
enum E {
    A = 1,
    B,
    C,
}

function f(x: E | undefined) {
    return x || E.C;
}
```

**Comment by jack-williams** [comment]
Related: #32621?

**Comment by DanielRosenwasser** [comment]
```ts repro
enum E {
    A,
    B,
    C,
}

function f(x: E | undefined) {
//       ^?
    return x ?? E.C;
}
```

[Workbench Repro](https://www.staging-typescript.org/dev/bug-workbench/?#code/KYOwrgtgBAolDeAoKKoEEA0zUCEuqgGEsBfRRAMzBAGMAXASwHsQoKAKADwC5YoAfKNQAmwCgxDBhASgSIA9PIKoAegH5sKAE7A6YLa05Q1a2ADpCAbkQkgA)

**Comment by DanielRosenwasser** [comment]
I think this is fixed now. Would we have any volunteers willing to add a test case?
