### ISSUE TITLE
processDiagnosticMessages.ts collision handling doesn't actually work

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#3587]
Background:

The build does a preprocessing step to build the `Diagnostics` map, which contains items naming tsc error codes and their corresponding human-readable messages.  The generate-diagnostics target runs before the actual compilation step for tsc.  It takes the diagnostic message from a JSON source and mangles it to create a suitable property name for the `Diagnostics` object.

For example, given the 1100 diagnostic ("Invalid use of '{0}' in strict mode."), we create `Diagnostic.Invalid_use_of_0_in_strict_mode`.

Because we're mangling these, processDiagnosticMessages.ts tries to go through some effort to avoid collisions in the generated property names.  See `ts.buildUniqueNameMap`, `ts.NameGenerator.handleCollisions`, and others.

For example, when dealing with two hypothetical diagnostic messages "Found '{0}'" and "Found 0", we wouldn't want the name-mangling to produce colliding `Found_0` keys for both messages.

Problem:

processDiagnosticMessages.ts does not succeed in its goal to properly deal with collisions.

Analysis and Cause:

During a visual audit of the code, before actually performing any tests against different inputs, I originally fingered the following line as problematic while eyeballing processDiagnosticMessages.ts:

```
    nameMap[names[i]] = uniqueNames[i];
```

This is in the context of having just produced the `uniqueNames` from the orginal elements of `names` (where `names` actually contains elements whose values are the diagnostic messages).  The use of the two arrays are inverted.

```
    nameMap[uniqueNames[i]] = names[i];
```

(Again, `names[i]` is a bit of a misnomer.  It actually contains the human-readable text of the diagnostic.)

However, this does not resolve the problem.  We can process Example Input 1 (adapted from the example above) and it will produce identical `Found_0` keys both before and after making the change above.  There are actually several other problems in processDiagnosticMessages.ts wrt collision handling.

The use of `buildUniqueNameMap` actually happens before the name-mangling (`convertPropertyName`) occurs, so the only time we would ever encounter a collision is if the _diagnostic messages_ are exactly the same (rather than their _would-be mangled names_ being the same as in Example Input).  But in fact, it's not even possible for the messages to be the same, because they come from a JSON source keyed off that message, so they're already guaranteed to be unique.  (Side note: add build preconditions to make sure there are no duplicate messages in the source JSON?)

There's also a problem with the `isFixed` parameter in `handleCollisions`, but I will file a separate issue about that, for various reasons.

Example Input:

```
{
    "Found '{0}'.": {
        "category": "Error",
        "code": 9999
    },
    "Found 0.": {
        "category": "Error",
        "code": 9998
    }
}
```

**Comment by colbyrussell** [comment]
There's a fix for this on my diagnosticspp branch.  See [rev cf1d9c2](https://gitlab.com/crussell/typescript-public/commit/cf1d9c24d865232b6ca8fd2be940b93cc5ba3508).

This message will have to do for a pull request, because GitHub doesn't allow filing a PR for non-GitHub branches.

**Comment by colbyrussell** [comment]
No automated tests created, because I can't make sense of the TypeScript test infrastructure (especially directory layout).  Want to help me out here?

**Comment by RyanCavanaugh** [comment]
We don't have any tests for the build-time tools like generate-diagnostics nor do we intend to add any, since they basically never break (assuming non-malformed inputs). A PR that fixes up the tool without any negative side effects is fine go in without any tests.

**Comment by colbyrussell** [comment]
@RyanCavanaugh, how is the project handling git pull requests from non-GitHub sources?  I have a fix in [rev cf1d9c2](https://gitlab.com/crussell/typescript-public/commit/cf1d9c24d865232b6ca8fd2be940b93cc5ba3508) as mentioned above.  I'd like to submit it for review.

**Comment by DanielRosenwasser** [comment]
Hey @colbyrussell, is there any reason you don't want to add GitHub as a remote? While I'd personally be fine with doing a manual merge, it makes review fairly difficult because feedback is no longer in a consolidated location.

We also need a contributor license agreement (which @msftclas would ordinarily send to you when sending out a GitHub PR). @mhegazy and @jonathandturner might know what to do a little better here.

_______________________

> I can't make sense of the TypeScript test infrastructure (especially directory layout). Want to help me out here?

As @RyanCavanaugh mentioned, we don't have testing for build-time tools, but our testing infrastructure primarily uses Mocha. `src/harness`

**Comment by colbyrussell** [comment]
> Hey @colbyrussell, is there any reason you don't want to add GitHub as a remote?

I don't have a problem with that.  In fact, I already have it as a remote.  Unfortunately, it's not as easy as that.

![screenshot from 2015-06-22 09 36 24](https://cloud.githubusercontent.com/assets/10376674/8284445/86ff82ee-18c2-11e5-9db6-ccfccb0ef7c5.png)

Without contributor branches for the repo, it means in order for anyone to submit their changes they have to spin up an on-GitHub fork, wait for it to finish, add *that* as a remote, and then push to it before submitting a PR.  Then there's the cleanup, unless you're wont to leave these these things lying around.

**Comment by DanielRosenwasser** [comment]
> they have to spin up an on-GitHub fork, wait for it to finish, add that as a remote, and then push to it before submitting a PR.

This is the intended workflow for GitHub. Make your own personal GitHub fork, clone it, modify it (on a separate branch, not `master`), and send a pull request.

The forking takes very little time. In general, the friction associated with this is common to all projects on GitHub. Adding a remote takes one command, and fixing a remote in your case is just one more:

1. `git remote rename origin upstream`
  * (you should be pulling changes from `upstream`)
2. `git remote add origin https://github.com/colbyrussell/TypeScript.git`
  * (you should be pushing to and sending PRs from `origin`)

**Comment by colbyrussell** [comment]
> In general, the friction associated with this is common to all projects on GitHub.

Yes.  This isn't your fault.

> Adding a remote takes one command, and fixing a remote in your case is just one more:
> 
>     git remote rename origin upstream

Even this one isn't necessary, really.  It can be left as "origin".  But it doesn't change the fact that there's lots of friction elsewhere.

**Comment by Eyas** [comment]
Is something going to be done about this and #3588, or were these handles elsewhere?

**Comment by colbyrussell** [comment]
As I mentioned in that issue and in my comment above, the fixes exist.  They're each linked in the comments here and there.

Problem is, GitHub sort of breaks git through the way that it's siloed to allow pull requests only from people who are also hosting their repos on GitHub.  Since my stuff isn't hosted here, no GitHub PR can exist for this issue, and unfortunately, the TypeScript team doesn't accept patches.

If you like, though, feel free spin up a PR of your own that incorporates the changes from [rev cf1d9c2](https://gitlab.com/crussell/typescript-public/commit/cf1d9c24d865232b6ca8fd2be940b93cc5ba3508) and [rev 3b33398](https://gitlab.com/crussell/typescript-public/commit/3b33398ae2eef16217798a6c73f55f8d2c3a9a41).  As I mentioned in issue #3589, [I won't be upset](https://github.com/Microsoft/TypeScript/issues/3589#issuecomment-114602557).

**Comment by NaridaL** [comment]
Here's the current state of things: processDiagnosticMessages.ts doesn't attempt to check for collisions on escaped identifiers. The error message you get further down the line seems descriptive enough, however:

```



934         Found_0: diag(99997, DiagnosticCategory.Error, "Found_0_99997", "Found 0."),
            ~~~~~~~

src/compiler/diagnosticInformationMap.generated.ts(934,9): error TS1117: An object literal cannot have multiple properties with the same name in strict mode.


934         Found_0: diag(99997, DiagnosticCategory.Error, "Found_0_99997", "Found 0."),
            ~~~~~~~

src/compiler/diagnosticInformationMap.generated.ts(934,9): error TS2300: Duplicate identifier 'Found_0'.
```

For checking duplicate input properties: e.g. in the following case:
```
{
    "Found 0.": {
        "category": "Error",
        "code": 9999
    },
    "Found 0.": {
        "category": "Error",
        "code": 9998
    }
}
```
there is
```
    const seenNames = ts.createMap<true>();
    for (const name of Object.keys(diagnosticMessagesJson)) {
        if (seenNames.has(name))
            throw new Error(`Name ${name} appears twice`);
        seenNames.set(name, true);
    }
```
which will *never* fail under any circumstances.

The above `error TS1117: An object literal cannot...` is generated by the binder, so having that same error here would require copying some of it's logic which seems like a lot of additional complexity for something VS Code is warning me about anyways.

**Comment by mhegazy** [comment]
thanks @NaridaL for the detailed investigation.
