### ISSUE TITLE
TS 2535 when using const enum values derived from other const enum values

### ISSUE THREAD

**Issue by dead-claudia** [microsoft/TypeScript#35875]
**TypeScript Version:** 3.7.2

**Search Terms:** 2535 const enum

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
const enum Foo { Value = 0x01 }
const enum Bar { Value = 0x02 }
const enum Baz { Value = Foo.Value | Bar.Value }
type Test = Baz.Value

const foo: Foo.Value = Foo.Value
const bar: Bar.Value = Bar.Value
const baz: Baz.Value = Baz.Value
```

**Expected behavior:** It to type-check without errors

**Actual behavior:** "Enum type 'Baz' has members with initializers that are not literals. (2535)" on both the type alias and the `baz` type, referencing `Baz.Value` in the type position.

**Playground Link:**  https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=33#code/MYewdgzgLgBApmArgWxgMRCGBvGA1AQwBtE4YBeGABgA8qBGGAXwChRJYEUYAhAgJxz5ipCtToAmZm3DR4SVHwBeQwiTKUMIAHRrRAH14DdIsqygBPAA5kAKnDmVlJ9SxkcYAM0wAudJhdRTQC9OHc5ACMBPz5+QI0jONDw2CilGIIleLFnUKA

**Related Issues:**

**Comment by isiahmeadows** [comment]
Accidentally filed this - please ignore.

**Comment by isiahmeadows** [comment]
My immediate use case is that of using a discriminated union based on part of a bit mask. Something roughly like this, but on a bit larger of a scale:

```js
export const enum Mask {
    Type = 0x00FF,
    IsStatic = 1 << 4,
}

export const enum Type {
    One = 0x00,
    Two = 0x01,
    Three = 0x02,
}

export const enum MaybeStatic {
    One = Type.One,
    Two = Type.Two,
    Three = Type.Three,
    StaticOne = Type.One | Mask.IsStatic,
    StaticTwo = Type.Two | Mask.IsStatic,
    StaticThree = Type.Three | Mask.IsStatic,
}

export type Node = NodeOne | NodeTwo | NodeThree;

export interface NodeOne {
    type: MaybeStatic.One | MaybeStatic.StaticOne;
    value: string;
}

export interface NodeTwo {
    type: MaybeStatic.Two | MaybeStatic.StaticTwo;
    value: number;
}

export interface NodeThree {
    type: MaybeStatic.Three | MaybeStatic.StaticThree;
    value: symbol;
}
```

My workaround is specifying these directly, but this is very much so not ideal. (I'm trying to take advantage of TS's constant evaluation to avoid duplicating work with the compile-time constants.)

**Comment by zimtsui** [comment]
same problem

```ts
const enum A { a = 1 }
const enum B { b = A.a }

type Ta = A.a; // ok
type Tb = B.b; // error
```

since A and B are both const enums, B.b's type should be analyzable in compile time.

**Comment by peter50216** [comment]
In the [TypeScript handbook about enums](https://www.typescriptlang.org/docs/handbook/enums.html#computed-and-constant-members), it says that `a reference to previously defined constant enum member (which can originate from a different enum)` is also consider a constant enum expression, which seems to contradict to this issue.

Maybe the `(which can originate from a different enum)` part from the handbook is not implemented?

**Comment by Walkalone13** [comment]
got this in such case:
```ts
const enum Foo {
  a = 0,
  b = 1 << 1,
  c = 1 << 2,
  all = a | b | c
}
```

resolved with using literals without any calculations

```ts
const enum Foo {
  a = 0,
  b = 1,
  c = 2,
  all = 3
}

```

**Comment by dead-claudia** [comment]
@Walkalone13 Please file a new issue. This one's been closed for over a year.
