### ISSUE TITLE
processDiagnosticMessages.ts collision detection is O(n^2)

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#3588]
Problem:

When trying to find collisions among the mangled names, processDiagnosticMessages.ts uses an algorithm that is O(n^2) wrt the number of names.

This is not a big deal right now (no perceptible difference operating on the ~550 diagnostics we have now), although when I test with a couple different datasets with 5000 entries, the new version using the O(n) algorithm consistently performed about 4 times better than the current O(n^2) one.  It's only a small difference, though.  We're talking about ~125ms vs ~600ms here.  To clarify: this is our own preprocessing step, so this is only going to make a (negligible) difference on our _own_ build times; this isn't something that's going to vary with the size of user programs.

There was also a mention of `getCollisionIndices` in a comment, but that function doesn't exist (earlier name for `collectMatchingIndices`, probably).  That has been changed as a side effect of updating the comment anyway.

I fixed this in [rev 3b33398 on diagnostics pp](https://gitlab.com/crussell/typescript-public/commit/3b33398ae2eef16217798a6c73f55f8d2c3a9a41)

**Comment by NaridaL** [comment]
No longer applicable, see also https://github.com/Microsoft/TypeScript/issues/3587#issuecomment-331075009.
