### ISSUE TITLE
ES private fields shouldn't affect type compatibility

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#35888]
TS compiler has to check compatibility of TS private fields since they can conflict with a field of a subclass but ES private fields never conflict. So compatibility checking of ES private fields is not required. Rather, ES private fields should be a way to make classes having different implementations and compatible interfaces.

cc @DanielRosenwasser 

**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
class A {
    #foo = 10;
}
class B {
    #foo = 10;
}
class C {
    #bar = 10;
}

const a: A = new B(); // error
const b: B = new C(); // error
```

**Expected behavior:**
no error
**Actual behavior:**
```
Type 'B' is not assignable to type 'A'.
  Property '#foo' in type 'B' refers to a different member that cannot be accessed from within type 'A'.(2322)
```
**Playground Link:** https://www.typescriptlang.org/play/index.html?ts=3.8.0-pr-30829-97&ssl=1&ssc=1&pln=12&pc=22#code/MYGwhgzhAECC0G8BQ1XQMQDMD23oF5oBGABgG4kBfJUSGAIURTS1wOPKpvCmgGEmaDACMwAJ3akK1GtgB2EAC7QwALjjs5AUwDu0egAoAlBWDyl0YesaFtevsbJA

**Related Issues:**

**Comment by mheiber** [comment]
My understanding is that this behavior is intentional: a class with a private field becomes nominal rather than structural. A reason for this is that ES private fields can be used to maintain invariants or for branding. 

Something similar happens with modifier `private`. Note that the field names do not clash, but the following still errors:


```ts

class A {
    private foo;
}

class B {
    private bar;
}

const a: A = new B();
```

> Typing this on mobile, may have typos

**Comment by falsandtru** [comment]
> ES private fields can be used to maintain invariants or for branding.

Can you show me an example?

**Comment by ilogico** [comment]
```ts
class A {
  #foo = 42
  foo(a: A) {
    console.log(a.#foo);
  }
}

class B {
  foo(b: B) {}
}

new A().foo(new B());
```

**Comment by falsandtru** [comment]
I thought it is inaccessible. Then the compiler should check ES private fields.
