### ISSUE TITLE
Find all references doesn't work with private fields

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35883]
https://www.typescriptlang.org/play/index.html?ts=3.8.0-pr-30829-97&ssl=1&ssc=1&pln=6&pc=2#code/MYGwhgzhAEDC0G8BQ1XQMQDMD23oF5oBGABgG4U1hsA7CAFwCcBXYe7RgCgEpFK009ABYBLCADosuCgIC+SWUA

```ts
class C {
    [|#foo|] = 10;
    constructor() {
        this.[|#foo|] = 20;
    }
}
```

Expected: Find all references on each range contains all ranges.
Actual: Find all references returns no results.

**Comment by dragomirtitian** [comment]
@DanielRosenwasser Since private fields are on master now, can I take a stab at this?

**Comment by DanielRosenwasser** [comment]
Yes :)

**Comment by DanielRosenwasser** [comment]
Thanks @dragomirtitian!
