### ISSUE TITLE
All semantic operations break after go to definition

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35907]
![goToDefinitionBreaksAfterFirstInvocation](https://user-images.githubusercontent.com/972891/71563161-e2869b00-2a3f-11ea-8589-7e9d99d57188.gif)

1. `git clone https://github.com/React95/React95/`
1. `git checkout 57dc66d8a087792fd8fa0f1cfb7c7560767e8520`
2. `yarn`
3. Open up VS Code in the base
4. Open up the file `packages/core/components/Checkbox.jsx`
5. Go to line 82
6. Add the property `draggable` to the destructuring pattern
7. Go to definition on `draggable`
8. Go back to line 82 of `packages/core/components/Checkbox.jsx`
9. Go to definition on `draggable`

**Comment by sheetalkamat** [comment]
I dont seem to repro this with nightly or latest build from master. @DanielRosenwasser Can you please check if it repros for you and if it yes please collect tsserver log to share?
![gotoDef](https://user-images.githubusercontent.com/8052792/79807978-4a2f6180-8321-11ea-8e74-6d8ccd6bfe03.gif)
