### ISSUE TITLE
export binding destructuring downleveling changes runtime semantics

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#35905]
**TypeScript Version:**  3.7.2

**Search Terms:** export destructuring

**Code**

```ts
// @target: esnext
// @module: commonjs
let foo = 1;
export { foo };

console.log({ foo } = {foo : 1});
```

**Expected behavior:**

Logs: `{foo: 1}`

**Actual behavior:**
Logs: `1

**Playground Link:** https://www.typescriptlang.org/play/?module=1&ssl=4&ssc=33&pln=1&pc=1#code/DYUwLgBAZg9jEF4IEYDcAoEAPADjATpAN7RwQC+G6AxjAHYDOMoAdMDAOYAUJs85iCET4QAXCnIBKIA

**Related Issues:**

**Comment by rbuckton** [comment]
This looks to have been addressed in 4.4: https://www.typescriptlang.org/play?target=99&module=1&ts=4.4.4#code/DYUwLgBAZg9jEF4IEYDcAoEAPADjATpAN7RwQC+G6AxjAHYDOMoAdMDAOYAUJs85iCET4QAXCnIBKIA
