### ISSUE TITLE
generate-diagnostics collision handling chokes if two or more collisions are markde "fixed"

### ISSUE THREAD

**Issue by colbyrussell** [Microsoft/TypeScript#3590]
The problem:

If `handleCollisions` finds two collisions that are both marked "fixed" (in the `isFixed` array), it silently allows both names to escape unaltered and leaving the collisions intact:

```
        for (var i = 0; i < collisionIndices.length; i++) {
            var collisionIndex = collisionIndices[i];

            if (isFixed[collisionIndex]) {
                // can't do anything about this name.
                continue;
            }
```

The code for handling `isFixed` and `isCaseSensitive` is dead code, so there's no way to trigger this problem, even with alternative input.  All names are treated as if they're not fixed, so it's completely unused.  Even so, we go through some effort to generate an n-sized array for the `isFixed` part:

```
        if (!isFixed) {
            isFixed = names.map(() => false)
        }
```

It seems like these snippets may have been copied and pasted (or cross-language ported) from another project.

Proposed solution:

Remove the `isFixed`-handling from processDiagnosticsMessages.ts altogether.  This would obviate the problem.  We could do the same with `isCaseSensitive` while we're at it.

**Comment by RyanCavanaugh** [comment]
Any improvements to this tool are welcome :smiley:

**Comment by DanielRosenwasser** [comment]
@CyrusNajmabadi might have some input regarding this; I remember there was some unused code which we determined that we might be using down the line.

**Comment by CyrusNajmabadi** [comment]
These functions are useful, and i intend for them to be used when we start implementing things like "generateFunction/Method".  

They were copied from the Roslyn codebase, and provide the same semantics.

> If handleCollisions finds two collisions that are both marked "fixed" (in the isFixed array), it silently allows both names to escape unaltered and leaving the collisions intact:

Yes.  This is a feature.  The purpose of 'isFixed' is for the client to state explicitly that these names are correct and that they should not be affected.  However, the names should still be in the list of input as any collisions with non-fixed versions should cause the non-fixed name to be changed.

**Comment by colbyrussell** [comment]
In light of the previous comment, this should be marked WONTFIX and closed, instead of "Accepting PRs", no?

**Comment by mhegazy** [comment]
yup. thanks.
