### ISSUE TITLE
Cannot read property 'useCaseSensitiveFileNames' of undefined

### ISSUE THREAD

**Issue by emilmuller** [microsoft/TypeScript#35903]
Using the latest version of the typescript npm package to transpile ts in the browser. It throws

`Cannot read property 'useCaseSensitiveFileNames' of undefined`

in createCompilerHostWorker(...).

While stepping through typescript.js, I see this:

```
    function createCompilerHost(options, setParentNodes) {
        return createCompilerHostWorker(options, setParentNodes);
    }
    ts.createCompilerHost = createCompilerHost;
    /*@internal*/
    // TODO(shkamat): update this after reworking ts build API
    function createCompilerHostWorker(options, setParentNodes, system) {
        if (system === void 0) { system = ts.sys; }
        var existingDirectories = ts.createMap();
        var getCanonicalFileName = ts.createGetCanonicalFileName(system.useCaseSensitiveFileNames);
```

Seems like createCompilerHost calls createCompilerHostWorker with only two arguments, while createCompilerHostWorker tries to access a property on the third argument, which is undefined.

**Comment by tamj0rd2** [comment]
How did you fix this?

**Comment by N2D4** [comment]
Passing a custom implementation of `CompilerHost` to `createProgram` fixed it for me (without one, TS tries to use `ts.sys` defaults, which is unavailable in browsers).

```ts
const compilerHost = {
            getSourceFile: ...,
            getDefaultLibFileName: ...,
            writeFile: ...,
            getCurrentDirectory: ...,
            getDirectories: ...,
            getCanonicalFileName: ...,
            getNewLine: ...,
            useCaseSensitiveFileNames: ...,
            fileExists: ...,
            readFile: ...,
};
```
