### ISSUE TITLE
No check for access modifier for non-trivial class properties

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#35919]
**TypeScript Version:**  3.7.2

**Search Terms:** private computed property

**Expected behavior:**

TypeScript should check the access modifier of class properties with "weird" names that look like computed properties but are given literally (e.g. property names with dashes).

I understand that there is an intended bypass for "real" computed properties where the index is a non-constant expression (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#413-property-access). But properties explicitly  defined in the class should be checked when accessed literally (see playground example).

Actually, TypeScript even acts a little inconsistent: It fails if trying to access a class property that does not exist, but passes accessing private properties from outside.

**Actual behavior:**

TypeScript fails for undefined properties, but not for existing private properties.

**Related Issues:** #26328 

**Code**
```ts
class C {
    public p1 = 1;
    private p2 = 1;
    public ["p-1"] = 1;
    private ["p-2"] = 1;
}

const c = new C;
console.log(c.p0); // error (ok)
console.log(c.p1);
console.log(c.p2); // error (ok)
console.log(c["p-0"]); // error (ok)
console.log(c["p-1"]);
console.log(c["p-2"]); // no error!
```
</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```
</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEDC0G8BQ1XQA4FcBGICWwGAjNALzREDcKa6ATngG5gAuAphgExkXVoY58hANoAidAFoiogLo8qNVPSasOYyZ1nzqAXyRJgAewB2EFtELljbAO5xqR04ZBsAdCEMBzABTBX6AAYASgcTCGc3Dx8-dCIQgzCI9y9ff054x3CXZOj1CQDZDMTsqN886RkipxKU4DzNSuogA)

**Comment by ajafff** [comment]
How is this different from #26328?

**Comment by danielrentz** [comment]
From #26328: `const n = a[nameN];` with nameN being a variable (well in real-life). Ths issue is specifically about `object["literal"]`. And ... about undefined vs. private properties behaving different.

**Comment by RyanCavanaugh** [comment]
This is longstanding behavior to allow (ugh) the access of these properties. It'd be a very substantial breaking change at this point and we don't intend to invoke that pain.
