### ISSUE TITLE
Git tag for TypeScript 3.7.4 is missing.

### ISSUE THREAD

**Issue by nirvdrum** [microsoft/TypeScript#35915]
TypeScript 3.7.4 has been available on NPM since 12-Dec-2019. However, as of 29-Dec-2019 there is no corresponding tag or release available in this repository. It was likely just a hiccup in the release process, but it gets concerning when something appears on NPM but there's no official mention of it anywhere.

**Comment by swftvsn** [comment]
could someone from the team elaborate if it is safe to upgrade to this version or not?

**Comment by DanielRosenwasser** [comment]
Yeah, it was an oversight and it's safe to use.
