### ISSUE TITLE
Unable to resolve signature of parameter decorator when called as an expression

### ISSUE THREAD

**Issue by bruceauyeung** [microsoft/TypeScript#35912]
i followed https://www.typescriptlang.org/docs/handbook/decorators.html to try to decorate class properties declared in constructor, but vscode gave me the error described as the title,  it's ok if i declare these properties in normal way( not declared in constructor parameter ) and decorate them

reflect-metadata: 0.1.13
typescript used in my project : 3.5.3
vscode: 1.41.0
windows 7 64bit

```ts

const rtsTypeMetadataKey = Symbol('rtsType');
function rtsType(rtsType: string) {
  return Reflect.metadata(rtsTypeMetadataKey, rtsType);
}
function getRTSType(target: any, propertyKey: string) {
  return Reflect.getMetadata(rtsTypeMetadataKey, target, propertyKey);
}

class InitData {
  // no error here
  @rtsType('type1')
  softdaInitPath: string | number[];
  constructor(
    softdaInitPath: string | number[] = '',

    // error pops out here
    @rtsType('type2') 
    public appUniqueID: string | number[] = ''
  ) {
    this.softdaInitPath = softdaInitPath;
  }
```
vscode error snapshot:
![image](https://user-images.githubusercontent.com/1210201/70883013-a0effc00-200c-11ea-9d39-a087c69ae0f4.png)

**Expected behavior:**
decorator `rtsType` works well on properties declared in constructor
**Actual behavior:**
vscode gives error  as title described.
**Playground Link:** 
none
**Related Issues:**

**Comment by mjbvz** [comment]
Does this work with TypeScript 3.7.3?

**Comment by bruceauyeung** [comment]
@mjbvz  do i have to upgrade typescript in my project ( described in `package.json` in my project root) 
 ?

**Comment by mjbvz** [comment]
In VS Code, did you choose to  use the [workspace version of TypeScript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript)?

If so, switch to using VS Code's version (which should be 3.7.3)

**Comment by bruceauyeung** [comment]
@mjbvz i didn't switch typescript version, actually i even didn't know how to switch until you told me.
this doesn't work with TS 3.7.3

**Comment by mjbvz** [comment]
This is not a VS Code issue as far as I can tell, the same thing also happens on the command line when using tsc. 

Please file this against TypeScript

**Comment by mjbvz** [comment]
Complete example using the `reflect-metadata` package:

```ts
import 'reflect-metadata';

const rtsTypeMetadataKey = Symbol('rtsType');
function rtsType(rtsType: string) {
    return Reflect.metadata(rtsTypeMetadataKey, rtsType);
}
  
class InitData {
    // no error here
    @rtsType('type1')
    softdaInitPath: string | number[];

    constructor(
        // error pops out here
        @rtsType('type2')
        public appUniqueID: string | number[] = ''
    ) { }
}
```

**Comment by bruceauyeung** [comment]
@mjbvz did you mean that example can compile on your environment ?
i gave another try and failed .
![无标题](https://user-images.githubusercontent.com/1210201/72030348-b383eb00-32c3-11ea-8388-c5007d16ae1c.jpg)

**Comment by RyanCavanaugh** [comment]
Was logged separately already

**Comment by lucideuclid** [comment]
I was dealing with something quite similar. I was getting this error wherever I used a decorator in the project 
`Unable to resolve signature of class decorator when called as an expression _ts(1238)`_

This got resolved by enabling Experimental Decorators in the JS/TS Language Features Extensions setting which comes bundled with VSCode. It can also alternatively be disabled.
