### ISSUE TITLE
Generic function params infer error

### ISSUE THREAD

**Issue by Ztail** [microsoft/TypeScript#35918]
Examples
``` typescript
function func<F extends (...args: any[]) => void>(a: F, b: F, c: F) {

}

var a: (a: any) => void;
var b: (a: number) => void;
var c: (a: string) => void;


func(a, b, c);
```

throw error
> Argument of type '(a: string) => void' is not assignable to parameter of type '(a: number) => void'.
  Types of parameters 'a' and 'a' are incompatible.
    Type 'number' is not assignable to type 'string'.ts(2345)

Generic F infer last params type "(a: string) => void", but i want it infer first params type "(a: any) => void"

**Comment by robottron45** [comment]
All your arguments have the same type in your definition in line 1. But they are different declared in the variables (line 5-7). The type `(a: number) => void` is not equal to `(a: string) => void`. You could use different type generics for different types:
`function func<F extends (...args: any[]) => void, G extends (...args: any[]) => void, H extends (...args: any[]) => void>(a: F, b: G, c: H) {}`
