### ISSUE TITLE
Class fields compiling in Node 12

### ISSUE THREAD

**Issue by Apacheli** [microsoft/TypeScript#35924]
# Search Terms
class, field

## Suggestion
Although only stage 3 (experimental) in ECMAScript, class fields have been implemented in Node 12 and some browsers. I suggest that if you have compiler option `target` set to `ESNext`, it would compile them to the JavaScript equivalent, rather than `this.x = y` as TypeScript currently does. This would also solve the behavior that `useDefineForClassFields` was intended for as it defines class fields in a similar fashion (`[[Define]]` as they say), thus it could(?) be deprecated in the future.

If you want to read more about the proposal: https://github.com/tc39/proposal-class-fields#readme

## Use Cases
In the near future, class fields will be fully supported in, hopefully, all platforms. This could be useful for easier readability of compiled code.

## Examples
With this TypeScript code, the compiled code is a bit larger than what most would anticipate for.
```ts
class Truck {
  wheels: number = 2;
}
```
Compiled code:
```js
class Truck {
    constructor() {
        this.wheels = 2;
    }
}
```
```js
class Truck {
    constructor() {
        Object.defineProperty(this, "wheels", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: 2
        });
    }
}
```
The compiled code could be sugared down to
```js
class Truck {
    wheels = 2;
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sandersn** [comment]
3.7 and above already emit stage 3 class fields with target: "esnext" and useDefineForClassFields: true. Without useDefineForClassFields, we want to provide the old semantics and therefore emit constructor assignments as before.

It sounds to me like Typescript already does what you propose. Am I missing something else it should do?
