### ISSUE TITLE
tsserver: newly added files aren't consider being part of tsconfig.json until restart of the server

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#3593]
Steps to reproduce:

- VSCode, empty workspace
- add file provide.ts with the following content:

export function provide(): void {	
}

Observe: you get a message about a missing module system configuration

- add a tsconfig.json file and restart VSCode (see #3244 why)
- add a second file provide2.ts with the following content:

export function provide2() {
}

Observe: you get AGAIN the message about a missing module system and you need to refresh VSCode. Looks like that the new file is added into a virtual project instead of being covered by the project configured by the tsconfig.json file.

**Comment by mhegazy** [comment]
@hoanhtien is looking into this.

**Comment by zhengbli** [comment]
Should be fixed in #4023. could you give it a try?

**Comment by dbaeumer** [comment]
Tested it with master and it works for me.

**Comment by mhegazy** [comment]
Thanks @dbaeumer for verifying.
