### ISSUE TITLE
Assertion signatures don't work with vars declared by for...of

### ISSUE THREAD

**Issue by ef4** [microsoft/TypeScript#35940]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms**

type assertions, left-hand side of for...of, assertions require every name

**Code**

There is no way to satisfy the 

> Assertions require every name in the call target to be declared with an explicit type annotation.

compiler error when one of the names is declared via a `for...of` statement.

```ts
interface Thing {
    good: boolean;
    isGood(): asserts this is GoodThing;
}

interface GoodThing {
    good: true;
}

function example1(things: Thing[]) {
    for (let thing of things) {
        // Error: Assertions require every name in the call 
        // target to be declared with an explicit type annotation
        thing.isGood();  
    }
}

function example2(things: Thing[]) {
    // Error: The left-hand side of a 'for...of' statement 
    // cannot use a type annotation
    for (let thing: Thing of things) {
        thing.isGood();
    }
}
```

**Expected behavior:**

Either example1 or example2 or some syntactic variant of them should be acceptable to the compiler.

**Actual behavior:**

It's impossible to use assertions against names defined by `for...of`.

**Playground Link:** 

https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191228#code/JYOwLgpgTgZghgYwgAgCoAtQHNkG8BQyRyWA9qQCYBcyARuQDYRwgDchxwAzgOLkUAKAJQ04XLtDBdkYTNO7I+lDNnYBffPlCRYiFEooqQOAsRL8aYKAFcI6zTGsgEYYKRDIIADzgBbAA5MAIwCsthcNEZYANoAukJ4HEQwpFDIAkxgMpjGyKQw2eEJpmbEYcYAdNwGwuxmGhr4js6u7p4+AUwATKE5WBFofXHFScgpaRkQWeVYkX15BTNcI6VlfVW8-LWjDUA

**Comment by RyanCavanaugh** [comment]
@ahejlsberg I think we need to either allow `for/in` iterator type annotations or add some additional special cases to try to find assertion signatures

**Comment by ahejlsberg** [comment]
I'd prefer avoiding type annotations in `for/of` as there is no need beyond this issue. One possibility is to just perform normal type resolution for variables declared in `for/of`. This would mean that calls of the form `thing.isGood()`, where thing is declared as `for (let thing in things)`, will require resolution of the type of `things`. This has the potential to cause new circularity errors (i.e. "variable is referenced in its own type annotation"), but we'd have to try it out to see.
