### ISSUE TITLE
Unable to edit code file after navigating to definition (F12) in Visual Studio

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#35946]
**TypeScript Version:**  3.7.4
**Visual Studio Version:** Community 16.4.1

**Search Terms:**
F12 edit fail

**To Reproduce**
* Right-click on a tab in the document well and select 'Set Tab Layout' -> 'Left'
* Open up the attached Visual Studio Project.
* Open `app2.ts`
* Position the cursor on `getFoo` by clicking on it.
* Hit F12 to navigate to the `getFoo` implementation.
* Hit the down arrow key and start typing.

**Expected behavior:**
The document should be editable.

**Actual behavior:**
It ain't.

Editing is only enabled after clicking with the mouse (which finally causes the edit cursor to appear). This is a regression at some point because editing used to work normally in the past (if I remember correctly).

It affects productivity to have to find the mouse and click in the document and then go back to typing.

[Sample2.zip](https://github.com/microsoft/TypeScript/files/4014290/Sample2.zip)

**Comment by NoelAbrahams** [comment]
Just noticed something else. This only happens when the Tabs in the document well are set to 'Left', ie not along the top. Edited to add the extra step.

**Comment by RyanCavanaugh** [comment]
@NoelAbrahams this seems to be specific to the VS TS component; can you please use the "Report Problem" command in VS to file a report there? This will give the VS team the extra data they need to be able to investigate. Thanks!
