### ISSUE TITLE
Change spelling for private field incorrectly fixes to a string property

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#35954]
**TypeScript Version:**  3.8.0-dev.20191231

**Search Terms:**

private field change spelling, private field autocorrect

**Code**

```ts
class Foo {
    #foobar: number;

    constructor() {
        this.foobar = 12;
    }
}
```

**Actual behavior:**

This code contains a mistake, the suggested option of `Change spelling to '#foobar'` converts the statement into `this["#foobar"]` which is not correct.

**Expected behavior:**

The code should be fixed to `this.#foobar`.

**Playground Link:** 

https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191231&ssl=6&ssc=14&pln=6&pc=20#code/FAYwNghgzlAEBiB7RsDexadgYgGbICMIAnALlgDsBXAWwIFNiBuYDLERCqAF2KpG6JiACgCUaNlizcAFgEsoAOnyIixWAF5YARgBMLKQF9ghoA

**Comment by omkar-joshi** [comment]
I'd like to help with this
