### ISSUE TITLE
Is Node 8 still supported?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#35958]
## Search Terms

node 8 10 eol end of life deprecation 

## Suggestion

Node 8 has reached end-of-life as of December 31, 2019 ([link](https://nodejs.org/en/about/releases)). Is there a formal timeline for when TypeScript will drop support for the platform? 

## Use Cases

https://github.com/microsoft/TypeScript/pull/35957 has build errors in Node 8 for capture groups not being supported _(though, admittedly, I am dubious about relying on the platform's `RegExp` constructor in the compiler...)_.

## Checklist

My suggestion meets these guidelines:

* [❌?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
While we'll likely stop having CI for node 8 soon (and instead have 13, 12, 10), I don't think we'll intentionally land features that rely on es6+ runtime behaviors (without also providing a polyfill) if we can help it.

**Comment by JoshuaKGoldberg** [comment]
Thanks!
