### ISSUE TITLE
Strange "Object is possibly 'null'" assumption

### ISSUE THREAD

**Issue by Simonwep** [microsoft/TypeScript#35964]
**Code**

I've got the following code:
```ts
interface MyGenerator {
    nextItem(): null | string;
    throwError(): never;
}

type GeneratorMapperFn = (gen: MyGenerator) => string | null;
const mapTokenFunction = (fn: GeneratorMapperFn) => {
    return (gen: MyGenerator): string | null => {
        return fn(gen);
    };
};

// The error occurs at this "function", TS seems to know that "gen" implements "MyGenerator"
// but tells me instead that "next" could be null at the very end.
const mappedFunction = mapTokenFunction(gen => {
    const next = gen.nextItem();

    if (!next) {
        gen.throwError();
    }

    // TS2531: Object is possibly 'null'
    return next.toUpperCase();
});
```
> [TS Playground](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200101&ssl=1&ssc=1&pln=22&pc=4#code/JYOwLgpgTgZghgYwgAgLIE8DiETTmAeymQG8AoZS5XADzAElIBbACgEoAuagVwBtfkAH2QBnMFFABzANwUqYABZQCAdwCiUZVHZdcAN2iyAvmTJh0ABxTZcUfEVRwLVqADEQyALzIWknFwwbPEIoNi8APlFxKSEeflkEAhAxZCYnABUCAGscV24QBDBgJK8fGBAuILsQx2dodzDPSPIqZCgIMG4oD19-NCwcYKJOKIkQSViQPgEm0jlWynbO7uRy3pA2WVajY1kyROSwVKcrABM8gqKS7zSLTJyQC8LikHWIudaDlNoj7z8QAB0P0YEFYm1MrWAMB8AEIfmEWgtKP8AYplOpNER2FsqCZ5sgAPQE5DpADKACYAKwAZgAjFwAPIAIwAVhBCshgCJkBYCCIRMAmbx0MgAORTfii-FLLoeH6oggAVTqUAAwnARBBsWQjJsgA)

It gets even more strange, if I replace the `gen.throwError()` with a `throw "Foo"` it works:
> [TS Playground](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200101#code/JYOwLgpgTgZghgYwgAgLIE8DiETTmAeymQG8AoZS5XADzAElIBbACgEoAuagVwBtfkAH2QBnMFFABzANwUqYABZQCAdwCiUZVHZdcAN2iyAvmTJh0ABxTZcUfEVRwLVqADEQyALzIWknFwwbPEIoNi8APlFxKSEeflkEAhAxZCYnABUCAGscV24QBDBgJK8fGBAuILsQx2dodzDPSPIqZCgIMG4oD19-NCwcYKJOKIkQSViQPgEm0jlWynbO7uRy3pA2WVajY1kyROSwVKcrABM8gqKS7zSLTJyQC8LikHWIudaDlNoj7z8QAB0P0YEFYm1MrWAMB8AEIfmEWgtKIplCpkAAiGAEAjorZUEzzZAAeiJyHSAGUAEwAVgAzABGLgAeQARgArCCFZDAETICwEEQiYAs3joZAAcim-HFhKWXQ8PwBhAAqnUoABhOAiCDsYybIA)

... or if `gen` got an explicit type-assignment (`(gen: )`):
> [TS Playground](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200101&ssl=13&ssc=46&pln=13&pc=58#code/JYOwLgpgTgZghgYwgAgLIE8DiETTmAeymQG8AoZS5XADzAElIBbACgEoAuagVwBtfkAH2QBnMFFABzANwUqYABZQCAdwCiUZVHZdcAN2iyAvmTJh0ABxTZcUfEVRwLVqADEQyALzIWknFwwbPEIoNi8APlFxKSEeflkEAhAxZCYnABUCAGscV24QBDBgJK8fGBAuILsQx2dodzDPSPIqZCgIMG4oD19-NCwcYKJOKIkQSViQPgEm0jlWynbO7uRy3pA2WVajY1kyROSwVKcrABM8gqKS7zSLTJyQC8LikBZ1gIHbe1CIudaDlK0I7ePwgAB0QMYEFYm1MrWAMB8AEIgWEWgtKKCwYplOpNER2FsqCZ5sgAPRk5DpADKACYAKwAZgAjFwAPIAIwAVhBCshgCJkBYCCIRMAObx0MgAORTfjS0lLLoeIHYggAVTqUAAwnARBBCWQjJsgA)

Although TS tells me that gen is of type `MyGenerator`:
![F1AqNpfMgn](https://user-images.githubusercontent.com/30767528/71689015-4b07ac00-2da1-11ea-8ce7-1ab15f820ef2.gif)

**Expected behavior:**
TS should correctly assume that `next` cannot be `null` after the conditional statement.

**Actual behavior:**
It throws `TS2531: Object is possibly 'null'`. 

**Related Issues:** 
#34795, #9998

**Comment by ilogico** [comment]
I think this is a current limitation.
I don't know where the documentation for this is, but TS needs explicit type annotations for the assert and never returning functions to contribute to control flow analysis.
For now, you can fix this error by annotating `(gen: MyGenerator) => ...`
