### ISSUE TITLE
module cats with exported var cats 

### ISSUE THREAD

**Issue by henrjk** [Microsoft/TypeScript#3597]
I ran into this while converting some pre existing code. 
The code uses a classic JavaScript module pattern for the browser. 
```JavaScript
// file cats.model.js
cats.model = (function () {
  'use strict';
  var initModule, getCat;
  initModule = function () {
    // some init code here.
  };
  getCat = function() {
    return "tabby";
  }
  return {
    initModule : initModule,
    getCat     : getCat
  };
}());
```  

I converted this to the following TypeScript code:
```typescript
// cats.model.ts
module cats {
  var initModule = function(): void {
    // some init code here.
  }
  var getCat = function() : string {
    return "tabby";
  }
  export var model = {
    initModule : initModule,
    getCat     : getCat
  };
}
```

This works as expected by me and introduces a kind of submodule that can be used under name `cats.model`. Now the existing code has also a root module `cats`. The original code looks like this:
```JavaScript
//  file cats.js
cats = (function () {
  'use strict';
  var initModule = function () {
    cats.model.initModule();
  };
  return {
    initModule : initModule
  };
}());
```
which gives access to a `cats.initModule` function. I could not find a perfect mapping to TypeScript so I converted this 'root' module into a submodule in the same way as before. Instead of calling it `cats.root` I felt `cats.cats` would be more appropriate:

```typescript
module cats {
  'use strict'
  var initModule = function () {
    cats.model.initModule();
  }
  export var cats = {
    initModule : initModule
  };
}
```  

However now I got error:
```console
ts-js-module-pattern dev$ tsc -p app
app/cats.ts(4,10): error TS2339: Property 'model' does not exist on type '{ initModule: () => void; }'.
ts-js-module-pattern dev$ tsc -v
message TS6029: Version 1.5.0-beta
```

Apparently the reference to `cats.model` in the source code refers to `cats.cats.model` which of course is not defined. However in
the original JavaScript pattern these references work as (naively) expected. The introduction of the `cats.cats` name also throws off references between other submodules (not shown here). For example a function in  `cats.model` might reference `cats.util.coolFunction` which no longer is found after the root module cats with a cats variable is introduced.   

While there are good workaround for my scenario it makes me also curious whether this behavior is actually intended. 

Section [4.3 Identifiers](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#43-identifiers) in
the TypeScript specification says *When an expression is an Identifier, the expression refers to the most nested module, class, enum, function, variable, or parameter with that name whose scope (section 2.4) includes the location of the reference.*

This appears to indicate that the first component of the `cats.model` reference inside the module `cats` resolves
to cats.cats because this was defined. However one could also take the position that the 
qualified reference `cats.model` is not defined within the module scope and then take the first reference that is defined in an outer scope, which would be the global level.

My question is whether this is as designed, a bug or a potential enhancement?

I am also curious whether there is a better mapping for the root module that avoids introducing a name so that one could simply use `cats.initModule()` instead of `cats.cats.initModule()`.

**Comment by DanielRosenwasser** [comment]
I think what you want is:

```TypeScript
namespace cats {
    export function initModule() {
        // code goes here
    }
}
```

Now you can do

```TypeScript
cats.initModule();
```

**Comment by henrjk** [comment]
Thank you for the suggested mapping. This would certainly work. 

However I remain curious whether the effect of introducing cats.cats to qualified reference such as  cats.<something>  in other cats namespace is intended?

**Comment by DanielRosenwasser** [comment]
You can use an alias if you so desire:

```TypeScript
import myCats = cats.cats;
```

or if you're not concerned with exported types and namespaces, you can just do

```TypeScript
let myCats = cats.cats;
```

Unfortunately, you can't just alias it to `cats` because we don't have a way of referring to the global `cats` right now.

**Comment by henrjk** [comment]
Thank you for the instant turnaround.
 
I am mostly concerned in not requiring widespread changes to the original sources when converting them to TypeScript. It appears that one just has to look out and avoid to name a module member with the module name.  That said it would perhaps be better if one would not have to depend on these kind of name clashes not occurring. 

Strangely perhaps I just came across this Tip in a presentation also: http://basarat.github.io/TypeScriptDeepDive/#/11/6

![screen shot 2015-06-22 at 22 56 51](https://cloud.githubusercontent.com/assets/7439282/8292893/45411af0-1932-11e5-8f8d-2966e3c4e0a0.png)

**Comment by DanielRosenwasser** [comment]
Yes, it can be a problem because you've implicitly shadowed the module name within the module, but the emit in that slide is slightly outdated (that used to be a bug). This is the new emit:

```JavaScript
var Test;
(function (Test_1) {
    var Test = (function () {
        function Test() {
        }
        return Test;
    })();
    Test_1.Test = Test;
})(Test || (Test = {}));
```
