### ISSUE TITLE
Extract to constant should add a type annotation

### ISSUE THREAD

**Issue by clembou590** [microsoft/TypeScript#35978]
Hello.
here the version of VS code I am using.

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

when I code in typescript and use the "extract to constant in enclosing scope"
then the constant is created without its type.. (as it should be according to this picture that I got from offical vs code site : https://user-images.githubusercontent.com/12821956/32022473-5f5cb84e-b98b-11e7-9508-626de188b197.gif)

Here is what I get 
![01](https://user-images.githubusercontent.com/10899818/71719244-066e2600-2e1e-11ea-957d-d74b48af8250.png)
![02](https://user-images.githubusercontent.com/10899818/71719248-08d08000-2e1e-11ea-90f5-47fd2534aed3.png)
![03](https://user-images.githubusercontent.com/10899818/71719251-0a9a4380-2e1e-11ea-9344-83c627544665.png)

I should have 
   const newLocal_1 : Observable<string> = from("hello");
instead of 
   const newLocal_1  = from("hello");

is there anything that I should be configuring in vs code to make it work?

another question:
is there any feature/shortcut in vs code to add the type in a variable?
if I have 
 const newLocal_1  = from("hello");
I would like to transform it to 
const newLocal_1 : Observable<string> = from("hello");

**Comment by DanielRosenwasser** [comment]
The refactoring shouldn't add a type annotation unless a different type would otherwise be inferred. In this case, you'll always get an `Observable<string>`. It's not clear exactly why the GIF provides an annotation, but I would assume it's to ensure appropriate types are inferred.

**Comment by clembou590** [comment]
@DanielRosenwasser 
thanks for your reactivity. I would like to do exactly as in the provided GIF:  how do I do that?

**Comment by DanielRosenwasser** [comment]
@clembou590 at this time, I don't think that's a scenario we're looking to suppport since it's not clear that there's a ton of demand there. Sorry about that.
