### ISSUE TITLE
Use of generic parameter defaults makes other generic parameters fall back to their defaults, too

### ISSUE THREAD

**Issue by GregOnNet** [microsoft/TypeScript#35977]
**TypeScript Version:** 3.7.2 & vNightly

**Search Terms:** inference, infer, string literal, generic

**Problem**

The behaviour can be observed in a generic method using defaults for its type parameters.
If one generic type parameter uses its default (see `TType = void`), other parameters stop inferring known types (see `TGreeting extends string = string`) and use the defaults, too.

**Code**

The method below takes a string-Parameter and treats it as string-literal-type.

```ts
function greet<TType = void, TGreeting extends string = string>(
  type: TGreeting
): { greeting: TGreeting; type: TType } {
  return "" as any; // fake implementation
}

// string literal is inferred.
const literalInferred = greet("Hallo");

// string literal is lost.
const literalNotInferred = greet<number>("Hello");
```

**Expected behaviour:**

I expected TypeScript to infer as many types as possible.

```ts
const literalNotInferred = greet<number>("Hello");
//    ^ property greeting is of type 'Hello' ✅
```

**Actual behaviour:**

Currently, Typescript uses the default for each generic parameter unless it would be possible to be more precise.

```ts
const literalNotInferred = greet<number>("Hello");
//    ^ property greeting is of type string ❓
```

**Playground Link:**
https://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20200101#code/GYVwdgxgLglg9mABAcwE4FN1QDwBVcCeADuogLyIBucMAJgDSK4DiGWMYyi6AHlOmFoBnREKioOXCmImcAfAAooxdAC4mrTLE4BKdQG8UbbcnUtjkxspJnCJRAF9E+gLAAoRJ8QYoIVEgByAMQAQxEQsAIAbncHd3cAegTRcUlEABsYflQQ9MQYEQ5gdFQMWgA6dwgEMQysktyASTBi0vRaciMtBQCACVz0uACdGLdE5Jk0zOzc-JFBsUq3arBa6Yb0gDk4KGbWss60LWwwEABbACMSxT70dMHhqKA

**Comment by RyanCavanaugh** [comment]
This is the behavior we shipped with and it can't really be changed now without incurring massive breaks.

Alternatives are at #26242 and #10571

**Comment by GregOnNet** [comment]
Thank you very much for the answer.
The alternatives look very promising.

I was able to get around this by providing multiple function overloads.


Closing this issue, since this topic is covered by #26242 and #10571.
