### ISSUE TITLE
It might be better with private property setter

### ISSUE THREAD

**Issue by NanaseRuri** [microsoft/TypeScript#35974]
In C#, I could use private setter while using public getter. Why not make it a feature instead of using private member with public getter?

**Comment by Barbiero** [comment]
#2845
people have been asking for it for a while, but it was closed.

**Comment by MartinJohns** [comment]
You should also follow the [issue template for feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md).
