### ISSUE TITLE
Possibility of `undefined` from optional properties is not honoured in spread

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#35983]
**TypeScript Version:**  3.6.3

**Search Terms:** spread optional undefined object properties property

**Code**

Here's an example of spreading an object with optional properties:

```ts
const myQueryDefaults: { a: number; } = { a: 1 };
const myQuery: { a?: number; } = {};

const result = { ...myQueryDefaults, ...myQuery };

// type is `number`
// runtime value is `number`
result.a;
```

The above example makes sense. However, an optional property does not only mean "this property may not exist" (`{}`)—it also means "this property may exist with a value of `undefined`" (`{ a: undefined }`). (Related: https://github.com/Microsoft/TypeScript/issues/13195.)

As a result of this, the type information may mismatch the actual types at runtime:

```ts
const myQueryDefaults: { a: number; } = { a: 1 };
const myQuery: { a?: number;  } = { a: undefined };

const result = { ...myQueryDefaults, ...myQuery };

// type is `number`, but runtime value is `undefined`!!
// expected type: `number | undefined`
result.a;
```

… which could result in runtime exceptions:

```ts
result.a.toString(); // runtime exception, because `result.a` is `undefined`
```

Ideally optional properties would only mean "this property may not exist" (https://github.com/Microsoft/TypeScript/issues/13195), in which case the existing behaviour with spreading makes sense. However, in the interim, perhaps the behaviour of spreading should be changed?

Extracted from https://github.com/Microsoft/TypeScript/issues/13195#issuecomment-373178677

Also potentially related: https://github.com/microsoft/TypeScript/issues/31025

**Comment by MartinJohns** [comment]
> However, in the interim, perhaps the behaviour of spreading should be changed?

That would most likely break every codebase out there.

**Comment by RyanCavanaugh** [comment]
#13195 is the actionable version of this. This would be an unbelievably large and unergonomic breaking change.
