### ISSUE TITLE
LiteralPropertyName should allow BigInt

### ISSUE THREAD

**Issue by JLHwung** [microsoft/TypeScript#35982]
**TypeScript Version:**  3.8.0-dev.20200101

**Search Terms:** bigint, property name

**Code**

```ts
({1n: 123});
```

**Expected behavior:**
No error

**Actual behavior:**
Property Assignment Expected

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200101&ssl=1&ssc=1&pln=1&pc=15#code/BQbwBAjAdgXJBMBmMBfAlAbiA
**Related Issues:**

https://github.com/tc39/test262/pull/2457
https://bugs.chromium.org/p/v8/issues/detail?id=10083

https://github.com/microsoft/TypeScript/commit/ecd12453f42cd95503bfd0a56a67b732a0ea83d4 should be partially reverted.

**Comment by calebsander** [comment]
This was discussed quite a bit when support for `bigint` was added to TypeScript. We decided that there weren't many good use cases for `bigint` keys and it made more sense to require an explicit conversion to `string` instead. For example, see https://github.com/microsoft/TypeScript/issues/15096#issuecomment-438751487.
Can you explain why you think this behavior should be changed?

**Comment by lucacasonato** [comment]
This currently forbids valid JS syntax in TS files (with a very confusing error message). https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBDAnmYcCCcC8cDeAoOQuARgDsAuOAMwEMAbAZ2DwF8BuIA - even if not allowed in the checker, it should at least be allowed in the parser.
