### ISSUE TITLE
Bad error message when trying to access protected property of super class type

### ISSUE THREAD

**Issue by stringham** [microsoft/TypeScript#35989]
**TypeScript Version:**  3.7.2

**Search Terms:** protected

**Expected behavior:**
I wanted to be able to access protected members of my super class type, so went searching for an issue about this topic. I found #10637 and the explanation about the Bank Account example.

I would still like to be able to access protected members in this way, and see that there is #30756 filed.

Given that it is currently an error to do this, it is expected that the error message tells me that I cannot access the property within my current class.

**Actual behavior:**
The error message in this example is: Property 'doTransfer' is protected and only accessible through an instance of class 'HostileBankAccount'.(2446)

However, this is happening in a line inside of the 'HostileBankAccount'

**Related Issues:**
#10637
#30756

**Code**
```ts
export abstract class BankAccount {
    constructor(protected id: string) { }
    protected abstract doTransfer(destinationAccount: BankAccount, amount: number): void;
}

export abstract class SecureBankAccount extends BankAccount {
    private authorized = false;
    public transfer(destinationAccount: BankAccount, amount: number) {
        if (!this.authorized) {
            throw new Error();
        }
        this.doTransfer(destinationAccount, amount);
    }
}

export class SwissBankAccount extends SecureBankAccount {
    protected doTransfer(destinationAccount: BankAccount, amount: number) {

    }
}

export class HostileBankAccount extends SecureBankAccount {
    protected doTransfer(destinationAccount: BankAccount, amount: number) {

    }

    public main() {
        const mine: BankAccount = new SwissBankAccount('6666666');
        const yours: BankAccount = new SwissBankAccount('1234567');

        // ERROR: Property 'doTransfer' is protected and only accessible through 
        // an instance of class 'HostileBankAccount'.(2446)
        yours.doTransfer(mine, 1e6);
    }
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play/?ssl=33&ssc=1&pln=34&pc=1#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAIQQDsBrAQU0wgFcz4BvAWACg4u46y0p62aAAowUCDGDZgAEzgBLGQC44-eWQDmASjjM4AXw7c4YiVMlzk-LPBkQAKhj4AzYFGEzgadQhjyIZDR0jDAqpJRBDEwANIgAtlGhcGT0cUhuWioAbhCKANwchuwcoJCwiKjoNjz4hHAAylL0UMDh1LSJcKCSZDJEbZEhukbcYvJZvsCI9DAAFtDyAF6ycAC8cM4IuCjABZyj9Ei48phwVS5uHl5+ZL7+gR0hYeTtwTHxiSopaRnD+8ZceTOODCACEc3kKAAdAgZvMoEtZDo2P8AcY5uIAO7JYDYgCiUHE7i0ezRXCKZLOs0hULsjnIKFc7k83lufgCg3eCASIRJI3JhQ4JXA0BwtSI9UxkJQA0eTC6IB6fQaTRasreLH5JnEkmkcjpTkZlxZNzuHLlSXViVi3M+yVS6SgyKFqKKRWFZTFBCIAAkIN5cK0Xpz4N1gL0JaqgxELX9jKZdRY4AaGUyrqyzQ8Nc8YxqbTymF8Hb8UVr3aiwIdjqc4gh1MJnajjLw0HA4upgDnXp11mRcQ0pYQrSFhAByABsk6n49HfKb3Bb8AAngwoCguyG1jjsZLpcOmGOAIwAJgAzAAWACs44A7LO9lrjAB6J9wAAK4jAbhgS7go5TFxQKOChEAm5grOQcgBLgv5YJgXgoPIRxTBiDAaLMiBkAofAwOQ8FwBAwJ4N6f5+gG0bdiEo5QsIx7nue45aI+3Ars00IAUa7jtn2sSHsAjGktwbpAA)

**Comment by DanielRosenwasser** [comment]
I guess we could do something like

```
Property 'doTransfer' is protected and only accessible within the body of 'HostileBankAccount' or on 'this' within its subclasses.
```

Is that right @searyanc @sandersn?

**Comment by stringham** [comment]
I think 'HostileBankAccount' shouldn't show up in this error message. That message makes sense if you replace HostileBankAccount with BankAccount.

**Comment by omkar-joshi** [comment]
I'd like to help with this

**Comment by sandersn** [comment]
I think the right answer is an elaboration that says "This is an instance of '{0}'." So the full error would be

```
Property 'doTransfer' is protected and only accessible through an instance of class 'HostileBankAccount'.
    This is an instance of 'BankAccount'.
```

**Comment by stringham** [comment]
@sandersn in this case, `doTransfer` is being called from within an instance of `HostileBankAccount`, but it is being called on a `BankAccount`, so the message from @DanielRosenwasser, but modified slightly, makes a lot of sense to me:

```
Property 'doTransfer' is protected and only accessible within the body of 'BankAccount' or on 'this' within its subclasses.
```

"This is an instance of BankAccount" isn't true at the location of this error message.

**Comment by sandersn** [comment]
When I pasted the code above into my editor, the error span is on `yours.doTransfer` and `yours: BankAccount`. Is your error span somewhere else? I use emacs, which is not always reliable at showing errors. 

The playground link isn't working for me, it just shows some jsdoc on some javascript.

**Comment by stringham** [comment]
I updated the playground link.

I also see the error span on `yours.doTransfer`, but I think the important context for this error message is that I am inside the `main` method of `HostileBankAccount` attempting to access a protected property of an instance of my super class.

Some additional examples:

```typescript
export class HostileBankAccount extends SecureBankAccount {
    protected doTransfer(destinationAccount: BankAccount, amount: number) {

    }

    public main() {
        const mine: BankAccount = new SwissBankAccount('6666666');
        const yours: BankAccount = new SwissBankAccount('1234567');

        // Property 'doTransfer' is protected and only accessible through an instance of class 'HostileBankAccount'.(2446)
        yours.doTransfer(mine, 1e6);

        const other = new HostileBankAccount('4343434');
        // allowed because 'other' is an instance of HostileBankAccount and this code is inside HostileBankAccount
        other.doTransfer(mine, 323);

        const swiss = new SwissBankAccount('39293923');
        // Error message makes sense:
        // Property 'doTransfer' is protected and only accessible within class 'SwissBankAccount' and its subclasses.(2445)
        swiss.doTransfer(mine, 3443);
    }
}
```

[Playground link](http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAIQQDsBrAQU0wgFcz4BvAWACg4u46y0p62aAAowUCDGDZgAEzgBLGQC44-eWQDmASjjM4AXw7c4YiVMlzk-LPBkQAKhj4AzYFGEzgadQhjyIZDR0jDAqpJRBDEwANIgAtlGhcGT0cUhuWioAbhCKANwchuwcoJCwiKjoNjz4hHAAylL0UMDh1LSJcKCSZDJEbZEhukbcYvJZvsCI9DAAFtDyAF6ycAC8cM4IuCjABZyj9Ei48phwVS5uHl5+ZL7+gR0hYeTtwTHxiSopaRnD+8ZceTOODCACEc3kKAAdAgZvMoEtZDo2P8AcY5uIAO7JYDYgCiUHE7i0ezRXCKZLOs0hULsjnIKFc7k83lufgCg3eCASIRJI3JhQ4JXA0BwtSI9UxkJQA0eTC6IB6fQaTRasreLH5JnEkmkcjpTkZlxZNzuHLlSXViVi3M+yVS6SgyKFqKKRWFZTFBCIAAkIN5cK0Xpz4N1gL0JaqgxELX9jKZdRY4AaGUyrqyzQ8Nc8YxqbTymF8Hb8UVr3aiwIdjqc4gh1MJnajjLw0HA4upgDnXp11mRcQ0pYQrSFhAByABsk6n49HfKb3Bb8AAngwoCguyG1jjsZLpcOmGOAIwAJgAzAAWACs44A7LO9lrjAB6J9wAAK4jAbhgS7go5TFxQKOChEAm5grOQcgBLgv5YJgXgoPIRxTBiDAaLMiBkAofAwOQ8FwBAwJ4N6f5+gG0bdiEo5QsIx7nue45aI+3Ars00IAUa7jtn2sSHsAjEPvOXCLgRcxuFufbYmRfiBvuMBjueF5Kee97MVwL6ILguAQJiKzpJgsI7H+EizG4wGQph2FoHhUyEXA0nyLJwaxpBVIWXQnggVZihTA5Tm5okamiaZUC0g4hpptxwCxKeZ5zkFIkoIORC9v2u5Ds5GpjqeACcx45blZ6qUJcAaQSRJtghCAaFMtYUF4qjhjsShBRpH4QF+sC-v+4WpmZXlgXqmFQWQMGILQCFIYGcBShCWHEXUo7pTKmWJMBrnyDARAoIcC07NCtH0ZeTElUl0phfSgHCFFMX0aec7GG6QA)

**Comment by sandersn** [comment]
There are two conditions for `yours.doTransfer` to be legal inside HostileBankAccount:

1. The reference needs to be inside the body of HostileBankAccount, or the body of a HostileBankAccount subclass.
2. The reference needs to be *to* an instance of HostileBankAccount (or subclass).

The original program already meets condition (1); condition (2) is the one that's violated. In that respect the current error is correct. Furthermore, the error can be fixed in one of two ways: 

1. change the instance reference to HostileBankAccount.
2. move the reference to BankAccount.

The current error leads to fix (1), which is the smaller, more local fix, and one that is more likely to expose incorrect assumptions. Moving `main` to `BankAccount` will still not work because `other.doTransfer` violates condition (1).
However, there really isn't a simple way to fix this program; it makes too many wrong assumptions about accessibility. A single error can't lead programmers to success in this case, so I prefer the current error because it's at least technically correct and minimally describes the problem.

**Comment by chharvey** [comment]
Here is a simpler example (taken from [the docs](https://www.typescriptlang.org/docs/handbook/classes.html#understanding-protected)) that relates to this, but I'm not sure if it covers the same problem.
```ts
class Person {
    protected name: string;
    constructor(name: string) { this.name = name; }
}

class Employee extends Person {
    private department: string;

    constructor(name: string, department: string) {
        super(name);
        this.department = department;
    }

    public getElevatorPitch() {
        return `Hello, my name is ${this.name} and I work in ${this.department}.`;
  }

  static main(): void {
    const p = new Employee('Picard', 'Starfleet');
    console.log(p.name) // no error

    const s = new Person('Skywalker');
    console.log(s.name) // Error: Property 'name' is protected and only accessible through an instance of class 'Employee'. (2446)
    }
}
```
Should this even be an error? I would expect methods inside `class Employee extends Person` to be able to have access to protected properties of `class Person`.

**Comment by dezsiszabi** [comment]
> Should this even be an error? I would expect methods inside `class Employee extends Person` to be able to have access to protected properties of `class Person`.

Yes, it should be. From the [specification](https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#8.2.2) (**emphasis** mine):

> Protected property members can be accessed only within their declaring class and classes derived from their declaring class, and **a protected instance property member must be accessed through an instance of the enclosing class or a subclass thereof**. Specifically, a protected member M declared in a class C can be accessed only within the class body of C or the class body of a class derived from C. Furthermore, when a protected instance member M is accessed in a property access E.M within the body of a class D, the type of E is required to be D or a type that directly or indirectly has D as a base type, regardless of type arguments.

This is the same in C#:
https://stackoverflow.com/questions/1904782/whats-the-real-reason-for-preventing-protected-member-access-through-a-base-sib

https://docs.microsoft.com/en-us/archive/blogs/ericlippert/why-cant-i-access-a-protected-member-from-a-derived-class-part-six

**Comment by chharvey** [comment]
@dezsiszabi  Ah, the StackOverflow link clears it up. The reason `s.name` can’t be called inside `Employee` is that `s` (even though it’s of type `Person`) might be an instance of some unrelated subclass of `Person`, e.g. `Volunteer`, where the protected `name` could be overridden.

**Comment by Griffork** [comment]
We're still getting a bad error message on this:
![image](https://user-images.githubusercontent.com/3665998/101897766-2649c480-3bff-11eb-9b73-62fc6f093d2e.png)

[Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAu0DeAoAkABwE4Hsl5giATaAQQEIAuaAOwFcBbAI3lwG50Bfdf0JBgJkAJmjwAHkXqlhiJBkyEAFh1pwF3TKXywVAS3oBzABQBKNFky54SRrnrQkhiADpVHNxW18+6IA)
