### ISSUE TITLE
Auto import adds value import to type-only import statement

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#36002]
**TypeScript Version:**  3.8.0-dev.20200104

**Search Terms:**

**Code**

```ts
import type {SourceFile} from 'typescript';
const file: SourceFile = createSourceFile(
```

While typing `createSourceFile` use auto import.

**Expected behavior:**

Adds a named import for `createSourceFile` and removes the `type` keyword from the import.

**Actual behavior:**

Adds a named import for `createSourceFile` while keeping it a type-only import. This causes an error as `createSourceFile` does not exist in the type space. 

**Related Issues:** Introduced by #35200 @andrewbranch

**Comment by andrewbranch** [comment]
Already working on this one (it’s one of the two unchecked to-do boxes on the original PR)
