### ISSUE TITLE
Potential type mismatch on 'impossible' code blocks relying on functions returning void, which can also be assigned as returning anything

### ISSUE THREAD

**Issue by silicakes** [microsoft/TypeScript#36008]
Disclaimer:

This is not a discussion about:
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

This is not a branch of any of the issues noted here: 
https://github.com/microsoft/TypeScript/issues/21674#issuecomment-363537054

Let's look at the following code:

```ts
type MutateArray = (arr: any[], val: any) => void;
const mutateArray: MutateArray = (arr, val) => arr.push(val);

// the type of t is than casted into void, as expected.
const t = mutateArray([1, 2], 3);

if (t !== void(t)) { 
// This block should not be reached as `t` is casted into `void`
// hence t should be typed as never. Instead, it's still typed as void.
    console.log(t)
}
```

[Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=9&pc=2#code/C4TwDgpgBAsgrsAhsCBBATuxIoF4oAUimAXFIgHYgDaAugDRQBuiANmZSAJR4B8zAewCWAEwDcAKADGAigGdgUALYJkaTNjLwkKDFhz4imRi1Y9c-YugB0YOHIAWBU10kTpshVEX4VO9foE1ACMjABMDFAAzK7uQgBmhIoAhLj4TMIiBMBcPADeUBJQxVAy8gKsENasAgDm2VwSAL5AA)

From what I gather, it shouldn't behave differently than:

```ts
const t = null;

if (t !== null) {
    // t is typed as never
    console.log(t);
}
```

[Playground](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200104&ssl=5&ssc=2&pln=1&pc=1#code/MYewdgzgLgBLC8MwFcA2qDcAoLBLAZjABSwCE8iK6AlDAN5YxMyiQioCmAdKiAOYlq2AL5A)

Note that the plain example, also works as expected:

```ts
const t = void(0);

if (t !== undefined) { // or (t !== void(0))
    console.log(t); // t is typed as 'never'
}
```

[Playground](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200104#code/MYewdgzgLgBLC8MBuICWATAFABgJQG4AoQ1AMxk1gEJ5EBXMdAU1NTCfVxgG9CZ+YoSCAA2TAHQiQAc0oFCAXyA)

**Expected behavior:**
a void `t` within an impossible block is typed as `never`

**Actual behavior:**
`t` is still typed as `void`

**Typescript version:**
3.7.2 / Nightly (currently 3.8.0-dev)

**Comment by RyanCavanaugh** [comment]
It seems like your confusion here is assuming the `void e` operator is an expression of type `void`. It isn't because a `void` expression always produces `undefined`, but a `void` type isn't solely inhabited by `undefined`. `void` is not a synonym for `undefined`, and your example perfectly illustrates it because the the code in the `if` block *does run!*

**Comment by RyanCavanaugh** [comment]
See also https://stackoverflow.com/questions/58885485/why-does-typescript-have-both-void-and-undefined

**Comment by silicakes** [comment]
Thanks for the answer! 

To follow it up - How come it's different between arrow functions and 'normal' functions? i.e:

`function foo(): () => void {
    return 2;
}`  will error, while `const arrow_foo: () => void = () => 2;` will not.

[Playground](http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcAUBKAXIziC8AfIgG5wwAmiA3gFCIOIBOAplCE0gEwDctAvrVoQEAZyiIAhkyZwA7gH0UcHHiKlyVfLgwFivIA)

**Comment by RyanCavanaugh** [comment]
It'd be odd (thought not *wrong*) to let you return a value on purpose from a function that said it returned `void`; likely this was a mistake.

It'd be wrong to prevent you from assigning a value-returning function to a target that returned `void`, because this is one of the reasons `void` exists.

**Comment by silicakes** [comment]
I get the second argument, but IMO, we should consider normalizing non-arrow function expressions into the same behavior, WDYT?
