### ISSUE TITLE
GoToDefinition doesn't seem to work on parameter of a type predicate

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3600]
Might be an issue with how I did it, but I built TypeScript and patched up the tsserver.js in my Sublime directory. Then tried this out:

```TypeScript
function f(parameter: any): /**/parameter is string {
    return typeof parameter === "string";
}
```

Go-to-definition doesn't work on the LHS of the type predicate type.

**Comment by mhegazy** [comment]
@tinganho interested in looking into this one?

**Comment by tinganho** [comment]
Yes I can look into it.

ons 24 juni 2015 kl 00:39 skrev Mohamed Hegazy <notifications@github.com>:

**Comment by DanielRosenwasser** [comment]
Thanks @tinganho!
