### ISSUE TITLE
setting importsNotUsedAsValue: error does not invalidate .tsbuildinfo

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#36000]
**TypeScript Version:**  3.8.0-20200104

**Search Terms:**

**Code**

```ts
// @filename: tsconfig.json
{ "compilerOptions": { "incremental": true } }

// @filename: a.ts
export class C {}

// @filename: b.ts
import {C} from './a';
export let v: C;
```

* compile
* set `"importsNotUsedAsValue": "error"` in tsconfig.json
* recompile

**Expected behavior:**

Expected error in `b.ts`

**Actual behavior:**

No error in `b.ts` unless the file or one of its dependencies are touched.

**Related Issues:** #35200 @andrewbranch  

PR incoming.

**Comment by amcasey** [comment]
Maybe @andrewbranch was the intended taggee?  I'm not mentioned in #35200.

**Comment by ajafff** [comment]
You're right, I mixed up the names. Sorry for the noise.
