### ISSUE TITLE
Go to definition: not working with type-only imports

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#36004]
**TypeScript Version:**  3.8.0-dev.20200104

**Search Terms:**

**Code**

```ts
// @filename: a.ts
export class C {}

// @filename: b.ts
import type { C } from "./a";

export function f(p: C/*1*/) {}
```

**Expected behavior:**

Go to definition at `/*1*/` works.

**Actual behavior:**

Go to definition only works if I use a regular import.

**Related Issues:** Introduced by @andrewbranch in #35200

**Comment by andrewbranch** [comment]
A test already exists for this 🤔
