### ISSUE TITLE
Option baseUrl changes directory 'Http' to 'http' when using sqlite3

### ISSUE THREAD

**Issue by IonelLupu** [microsoft/TypeScript#36006]
**TypeScript Version:**  3.7.4
**OS:**  Windows 10 (it might be a problem here)

**Search Terms:**
baseUrl changes directory 'Http' to 'http' when using sqlite3
**Code** (or [repo here](https://github.com/IonelLupu/typescript-compiler-directory-issue))
┌─ Http
│   └── index.ts
├─ index.ts
├─ tsconfig.json
└─ package.json
```json
// package.json
{
  "dependencies": {
    "sqlite3": "^4.1.1"
  },
  "devDependencies": {
    "@types/sqlite3": "^3.1.6"
  }
}
```

```ts
// index.ts - just 1 import that does nothig
import { Database } from 'sqlite3';
```
```ts
// Http/index.ts can be empty

```
```json
// tsconfig.json
{
	"compilerOptions": {
		"outDir": "./dist",
		"baseUrl": "./"
	}
}
```

Notice the `dist` folder after running `tsc`.

**Expected behavior:**
All the directories inside `dist` should have the same name with the same case: `Http` instead of `http`.
**Actual behavior:**
Running `tsc` on a simple project like this will cause the compiled result to have a `dist/http` directory instead of `dist/Http`.
Particularities:
 - removing the import will yield to the expected result
 - or, removing the `baseUrl` inside `tsconfig` will also yield to the expected result

This happens only with `sqlite3` but it might happen with other packages too (didn't test).

**Playground Link:** 
Cannot link a Playground link since this is a multifile issue.
**Related Issues:** 
None.

**Comment by RyanCavanaugh** [comment]
Can you set up a repo that reproduces this? It seems like there's probably at least something else in play here

**Comment by IonelLupu** [comment]
@RyanCavanaugh I've updated the `Code` section of the issue with a link to a repo

**Comment by RyanCavanaugh** [comment]
I'm not seeing this repro - it's still `Http`. `npm install` failed when I ran it. Please open a new issue if you have a working way to reproduce the problem. Thanks!
