### ISSUE TITLE
 [loc][Query][TypeScript] Localizability of 0; "MultilineCommentReturnKeyHandlerName"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/TypeScript#36022]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Multiline Comment Return Key Handler

File Name:
LanguageService\TypeScriptLanguageService\Windows\bin\Release\localize\ENU\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll

Resource ID:
0; "MultilineCommentReturnKeyHandlerName"

Query:
Does "Return Key" mean "Enter key" on the keyboard?
understood as "Return Key Handler for multiline comments" for now

**Comment by minestarks** [comment]
@PDostalek  Yes, "return key" does mean the Enter key on the keyboard in this context.

**Comment by PDostalek** [comment]
Thank you!
