### ISSUE TITLE
Missing SharedWorkerGlobalScope

### ISSUE THREAD

**Issue by jiripudil** [microsoft/TypeScript#36027]
Similar to #24323, the [`SharedWorkerGlobalScope`](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope) type is missing in the webworker lib

**Comment by DCtheTall** [comment]
I'd be interested in adding this to the webworker lib :smile:

**Comment by DCtheTall** [comment]
@jiripudil does there need to be anything added besides [what is in this PR](https://github.com/microsoft/TSJS-lib-generator/pull/809)?

**Comment by jiripudil** [comment]
@DCtheTall yes, the PR adds the `SharedWorker` class for registering and communicating with the worker. The global scope I'm talking about is the type of `self` in the worker script itself.

**Comment by DCtheTall** [comment]
@jiripudil thanks for the reply. I will open a PR once the one I linked to is merged to avoid conflicting with their work.

**Comment by DCtheTall** [comment]
@jiripudil is there any estimate on when that PR is going to be merged? It's been open for some time, and now that it's blocking this issue I am wondering what the plan was (if there is one)?

**Comment by jiripudil** [comment]
@DCtheTall honestly no idea, I don't work for Microsoft 😅

**Comment by DCtheTall** [comment]
@RyanCavanaugh should I wait for [the existing PR](https://github.com/microsoft/TSJS-lib-generator/pull/809) or just create a new one

**Comment by orta** [comment]
This got merged on the JSTS side, and should be coming up in 3.9
