### ISSUE TITLE
Quick fix is wrong for type used as value

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#36033]
```ts
// ./fileA.ts
export class Foo {
}

// ./fileB.ts
import type { Foo } from "./fileA.js";

class Derived extends /**/Foo {
}
```

Try to apply the quick fix for the error at `/**/`

![addImportToWrongStatementWhatEven](https://user-images.githubusercontent.com/972891/71844027-1e41e600-307a-11ea-9357-99ba7f0aa6bf.gif)

**Comment by andrewbranch** [comment]
Duplicate of #36002 (auto import and quick fix share this logic)
