### ISSUE TITLE
Parameters with default value should be allowed anywhere

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#3604]
Have code like this

```
function foo(one = 1, two, three) {

}
````

which is valid ES6 syntax (http://www.ecma-international.org/ecma-262/6.0/index.html#sec-functions-and-classes). TypeScript flags such a signature as error because it treats default values like optional parameters.

**Comment by JsonFreeman** [comment]
@jrieken Correct me if I'm wrong, but I think you can only elide arguments at the end of the argument list, right? You can't do this for example:
```ts
foo(, 2, 3);
```

**Comment by jrieken** [comment]
unsure about that, but you can all ```foo(undefined, 2, 3)```

**Comment by mhegazy** [comment]
The initialization is considered a marker for optionality, and `?` is prohibited. no non-optional members are allowed after an optional one. doing this would be a large breaking change, unless we only treat them as optional if they fall at the end, which would be a convoluted rule. 

Unless we have a proposal for how to make this work, i would be inclined to mark it as won't fix.

**Comment by JsonFreeman** [comment]
@jrieken Yes, I just wanted to make sure that was the only way to pass undefined.

@mhegazy I discussed this with @ahejlsberg and we think it is reasonable to only treat them as optional at the end (the one that you are saying is a convoluted rule).

**Comment by RyanCavanaugh** [comment]
> doing this would be a large breaking change

How is making a prior error a non-error a breaking change?

**Comment by JsonFreeman** [comment]
@RyanCavanaugh That is a good question.

**Comment by JsonFreeman** [comment]
I do not think it is a breaking change.
