### ISSUE TITLE
Generators "not supported" even with --target ES6

### ISSUE THREAD

**Issue by lmcarreiro** [Microsoft/TypeScript#3605]
Visual Studio display a syntax error in function* and the message "Generators are not currently supported." even when I'm targeting to compile to ES6, that already has support for generators.

This message wouldn't apper only in ES3 or ES5 mode?

**Comment by DanielRosenwasser** [comment]
Hi @lmcarreiro, support for generators are slated for TypeScript 1.6. See [our roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap) for more details.

**Comment by lmcarreiro** [comment]
Hi @DanielRosenwasser, thanks for response...
But it's not a TypeScript support, I'm talking only about syntax recognition when compiling TypeScript to ES6.
For generators support I'm using traceur in TypeScript *.js output files...

Will it work only in 1.6 too?

**Comment by DanielRosenwasser** [comment]
Ah, I misunderstood - in fact, I think I ran into this issue myself with #3328. @paulvanbrenk can you confirm that this is a duplicate and has since been fixed?

**Comment by paulvanbrenk** [comment]
@lmcarreiro if it compiles as expected on the command line it's indeed the same issue as #3328 which has been fixed.

**Comment by DanielRosenwasser** [comment]
@lmcarreiro can you confirm that on the command line, this compiles correctly right now?

**Comment by lmcarreiro** [comment]
Which version should it work? I tried in 1.5.0-beta and it doesn't work.

```javascript
//a.ts
function* a() {
	yield 1;
}
```

```
>"C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc" --target ES6 a.ts
a.ts(1,9): error TS9001: Generators are not currently supported.
a.ts(2,2): error TS9000: 'yield' expressions are not currently supported.

>"C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc" --version
message TS6029: Version 1.5.0-beta
```

**Comment by DanielRosenwasser** [comment]
@mhegazy should that be showing 1.5.2 or something along those lines?

**Comment by mhegazy** [comment]
Generators support is added in 1.6, 1.5-beta or 1.5.2 would give you the same error message (see [roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap#16)). @lmcarreiro if you want to use that, grab the latest from master it should do the trick.

**Comment by lmcarreiro** [comment]
Thank you all for your answers...
I took the last version on master branch and it worked. Compiles ok with ES6 and displays an error with ES5.
```
>"C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc" --version
message TS6029: Version 1.5.3

>"C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc" --target ES6 a.ts

>"C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc" --target ES5 a.ts
a.ts(1,9): error TS1220: Generators are only available when targeting ECMAScript 6 or higher.

>
```

**Comment by mhegazy** [comment]
@lmcarreiro we are should be adding ES5 support in the next release (post 1.6). plans has not solidified yet at this point, but stay tuned.

**Comment by thgaskell** [comment]
Is there a way to squelch the "Generators are not currently supported." warnings? Currently outputting to ES6 and transpiling with Babel, but would like to still have type error warnings.
