### ISSUE TITLE
support compilation options to ignore warning when tsc

### ISSUE THREAD

**Issue by ysyzqq** [microsoft/TypeScript#36054]
## Suggestion

Can support compilation options to ignore warning when tsc?
## Use Cases

like: 
```javascript
{
  "compilerOptions": {
 "noWarningEmit": true
}
```
there is so many warnings when tsc ,but actually we care for error only,
## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #29651
