### ISSUE TITLE
Formatting issue (might be VS specific, not sure where else to mention it)

### ISSUE THREAD

**Issue by upta** [Microsoft/TypeScript#3606]
I know that at some point in the past I didn't have this problem TS, but over the last several months it's been doing some funky stuff when auto-formatting.

http://imgur.com/yVORrUA

It used to move my {}'s over to line up with their ".then", but no longer :(

Any ideas?

**Comment by vladima** [comment]
this looks like a dupe of #1888 that was already fixed.
