### ISSUE TITLE
Type assertion on unspecified generic return type changes the type

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#36062]
**TypeScript Version:**  nightly (on playground).

**Search Terms:**
generic, return, assertion, inference, checker api.

**Code**

```ts
declare function genericGet<TValue>(object: any, path: string): TValue

const object = { foo: { bar: 123 } };
const result1 = genericGet(object, 'foo.bar');
const result2 = genericGet(object, 'foo.bar') as number;
```

**Expected behavior:**
In both cases, the return type of `genericGet(object, 'foo.bar')` reported by the type checker API (`checker.getTypeAtLocation`) should be `unknown`.

**Actual behavior:**
In the first case, the return type of `genericGet(object, 'foo.bar')` reported by the type checker API is `unknown`.
![image](https://user-images.githubusercontent.com/7462525/71931708-39345900-3153-11ea-9528-78ade91b7533.png)

In the second case, the return type is `number`.
![image](https://user-images.githubusercontent.com/7462525/71931719-45b8b180-3153-11ea-9b05-b54cacac38b6.png)

(best shown via ts-ast-viewer, link below).

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=7&pc=56#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMRUQYswBxEDAHgBUA1KCZEAPgAocAjAK3AwAueFFQBPADTwADlAwALYQGcMZVAQCUwxs1YAoPWDwr4PfpngBeeAG8kOHMLvdYwgIwAmAMzwAvn4BuQ2MMeDglZAgMNytCYlJyKgwuPgEpAHJEBwA6Fxh0jSCjVBNwyIwPWKISMkpqFPMMDKycXNgCkSV4VGQAW25SAKA

https://ts-ast-viewer.com/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMRUQYswBxEDAHgBUA1KCZEAPgAocAjAK3AwAueFFQBPADTwADlAwALYQGcMZVAQCUwxs1YAoPWDwr4PfpngBeeAG8kOHMLvdYwgIwAmAMzwAvn4BuQ2MMeDglZAgMNytCYlJyKgwuPgEpAHJEBwA6Fxh0jSCjVBNwyIwPWKISMkpqFPMMDKycXNgCkSV4VGQAW25SAKA

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/31435
Loosely related to: https://github.com/microsoft/TypeScript/issues/35431

Related issue in typescript-eslint:
https://github.com/typescript-eslint/typescript-eslint/issues/1410

Related rule logic:
https://github.com/typescript-eslint/typescript-eslint/blob/aee723813ec47ccac0a165cf1bc9674f6257b609/packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts#L244-L292

---

I found https://github.com/microsoft/TypeScript/issues/31435, which seems to suggest that this is entirely intentional.

However I would like to question this from the context of the type checker API.
This makes the type API pretty hard to use for certain use cases. Inspecting the type of the assertion expression (via `checker.getTypeAtLocation`) says it's of type number, and similarly inspecting the type of the call expression via the same API says it's of type number.

Is there any way to get the type that hasn't been inferred from a return type assertion?

In the context of our `no-unnecessary-type-assertion` rule, the rule warns about assertions that don't do anything, so that there is less useless code in a codebase..
(i.e. `genericGet(object, 'foo.bar') as number` is necessary, because it asserts `unknown` to `number`, but `genericGet<number>(object, 'foo.bar') as number` is unnecessary, because the return type is already `number`).

**Comment by RyanCavanaugh** [comment]
There isn't a way to do this; the type of the expression really truly actually for real is `number`, and an `unknown` is never produced during the inference process for `TValue`. We don't have any concept of "what would the type have been were it not for the surrounding context of the expression", which seems to be what you'd really need to assess the underlying intent of the rule.

Hopefully this has the end effect of dissuading people from writing functions like `genericGet` in the first place?

**Comment by nevir** [comment]
A real world example of this is `lodash.get`, unfortunately:


```ts
interface lodashGet<TObject, TResult> {
  (object: TObject, path: string | string[], defaultValue?: TResult): TResult;
}
```

```ts
const result = lodashGet(object, 'foo.bar') as number;
```

**Comment by nevir** [comment]
Overrides are one way to work around that specific one:

```ts
function lodashGet<TObject, TResult>(object: TObject, path: string | string[]): unknown;
function lodashGet<TObject, TResult>(object: TObject, path: string | string[], defaultValue: TResult): TResult;
function lodashGet<TObject, TResult>(object: TObject, path: string | string[], defaultValue?: TResult): TResult {
  /* pretend this works. */
  return (undefined as any) as TResult;
}
```
…but I'm wary of having to patch common libraries when they have generic return types that are optional like that

**Comment by bradzacher** [comment]
I was trying to find that definition, but it looks like the types for lodash's `get` method have been somewhat refined so that it doesn't use the "generic that is used in the return position" pattern.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/56c1ea26b59ed0e4634b1ba27096ab3b90371875/types/lodash/common/object.d.ts#L1659-L1792

**Comment by nevir** [comment]
Oh, nice find! I can upgrade my type declarations to mitigate that instance then 👍  

Seems likely to come up in other contexts though?
