### ISSUE TITLE
Inconsistent results of non-null assertion operator

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#36069]
**TypeScript Version:**  3.7.x-dev.20200104

**Search Terms:**

**Code**

```ts
function f<T>(a?: T): void {
    const b = a!;
    b; // NonNullable<T>
}
function g<T>(a?: T): void {
    a = a!;
    a; // T
}
```

**Expected behavior:**
Both type `b` and type `a` are T, or NonNullable\<T>.
**Actual behavior:**
Type `b` is NonNullable\<T>.
Type `a` is T.
**Playground Link:** http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20200104&ssl=1&ssc=1&pln=8&pc=2#code/GYVwdgxgLglg9mABMAPAFQHwAoCGB+ALkTQEoiA3OGAE0QG8AoRZxCBAZykQCNEBeRDgCEAbiYtuIxAHppiAHIJ5IADYqc3FQFN0GBgF8GoSLASIA5rtyFiZRJRr1xzHP0GjngqbOIGgA

**Related Issues:**

**Comment by falsandtru** [comment]
Probably we don't have to know that a value having a generic type will be undefined or null using type assertion operator. Developers just want to remove `undefined` from `T | undefined`. `NonNullable<T>` is not expected.

**Comment by RyanCavanaugh** [comment]
Non-unions can't be narrowed, but expression evaluation is expression evaluation.
