### ISSUE TITLE
NonNullable behaves differently when passing a property type from `this`

### ISSUE THREAD

**Issue by shilangyu** [microsoft/TypeScript#36061]
**TypeScript Version:**  3.7.2

**Search Terms:**
NonNullable this this[] this property nonnullable
**Code**

```ts
type SomeType = string | undefined

class Test {
    prop: SomeType

    func1 = (): this['prop'] => {
        return this.prop
    }

    func2 = (): SomeType => {
        return this.prop
    }

    func3 = (): NonNullable<this['prop']> => {
        return this.prop!
    }

    func4 = (): NonNullable<SomeType> => {
        return this.prop!
    }
}
```

**Expected behavior:**

This code compiles correctly, `this['prop']` and `SomeType` point to the same type.

**Actual behavior:**

`func3` is not happy with the return statement: `Type 'string' is not assignable to type 'NonNullable<this["prop"]>'`.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=21&pc=2#code/C4TwDgpgBAyg9gWwgFXNAvFAzsATgSwDsBzKAHygFdCATCAMyIhoCgWBjAGwEMsspkEHFADeLKBKhhccMAC5YiFGjaSo9auwCMUTAAoAlAuAALfFgDaAcmmyrAXV0A+UeLWTcEYJVyEop8wA6WzA3CQBfVUkNQnYAJl0oQwV4JFRIZ1d3Dy8fPwCsYJlQtUiw9U0AZkTkqAA5OEI6yk4eACNOCAAeAusQhxd0FzFsiU9vX38zQpCAQnKytRj2ABYao3rG5tbuDu7U5UhB4fK1cbypoLmFlnCgA)

**Related Issues:** none

**Comment by AnyhowStep** [comment]
Workaround,
```ts
type SomeType = string | undefined

class Test {
    prop: SomeType

    func3 = (): NonNullable<this['prop']> => {
        const tmp: this["prop"] = this.prop;
        return tmp!
    }

}
```

**Comment by RyanCavanaugh** [comment]
@weswigham can you link to the proper duplicate please

**Comment by shilangyu** [comment]
Tried v3.8, still seems to not work. I also tried to find the duplicate issue but I couldn't (probably a broader topic)

**Comment by weswigham** [comment]
There's another similar issue to this one to do with `this` and `NonNullable<this>` not being compatible, but in this case the issue is that when we do a property access on `this`, we actually get the constraint of the access (so we report the "current" type rather than `this["prop"]`), which, when `NonNullable`'d, then produces a (less precise) result.

#26942 is a dupe with a slightly inaccurate answer (even adding a cast is not sufficient, because of what I described above).

**Comment by JoniJnm** [comment]
Works since 4.8

https://github.com/microsoft/TypeScript/pull/49119
