### ISSUE TITLE
define a 'no exception' indicator

### ISSUE THREAD

**Issue by Nkmol** [microsoft/TypeScript#36075]
## Search Terms

- noexcept
- no exception
- exception hinting

## Suggestion

Currently, there is no way of defining a clear contract of the caller and the implementation in respect to the exception flow. I would like to see a function definition, which allows me to hint and guard an expected exception in a function body.

## Use Cases

Imagine the following basic structure
```
function myNoExceptionFlow(toBeStringified: object): string {
   if(toBeStringified.stringifiedIndicator) {
      return stringifyFunction()
   }
   return '';
}
```
This function can, of course, be longer, more complex and be split into multiple flow-functions.

If one of the developers sees this code, in an encapsulated way, it might want to refactor the return statement to a `throw Error` functionality:

```
function myNoExceptionFlow(toBeStringified: object): string {
   if(toBeStringified.stringifiedIndicator) {
      return stringifyFunction()
   }
   throw new Error('Could not get stringified version');
}
```

This results in the parent flow most likely not correctly handle this scenario, where the parent functionality most likely early-fails.

## Examples

It would be great to have a function definition for this. Something like [`noexcept` in c++](https://en.cppreference.com/w/cpp/language/noexcept), but more focused on hinting.

```
function myNoExceptionFlow(toBeStringified: object): NoExcept<string> {
   if(toBeStringified.stringifiedIndicator) {
      return stringifyFunction()
   }
   throw new Error('Could not get stringified version');
}
```

I have no idea how this would be realised, or if this would be even possible to realise.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment]
Likely a duplicate of https://github.com/microsoft/TypeScript/issues/13219 (except that issue wants the opposite)

**Comment by Nkmol** [comment]
Having an `explicitThrowCheck` option would also imply the other way around. Agree, this is a duplicate.
