### ISSUE TITLE
Type checking not work in circular  reference

### ISSUE THREAD

**Issue by wuchangming** [microsoft/TypeScript#36070]
**TypeScript Version:**  3.7.4

**Search Terms:**

**Code**

```ts
interface SubFunc {
    (number: string): any
}
function func(subFunc: SubFunc) {
    return 'x'
}
const x = {
    steps: {
        a: func(() => {
            // When `subFunc` has a type define but not `any`,
            // then the type checking is not working:  🤔️🤔️🤔️
            return x.steps.a.wrong
        })
    }
} 
function func2(subFunc: any) {
    return 'x2'
}
const x2 = {
    steps: {
        a: func2(() => {
            // If `subFunc` is defined as `any`, everything looks great.
            //
            // TIPS：Property 'wrong' does not exist on type 'string'.
            return x2.steps.a.wrong
        })
    }
}
```
![image](https://user-images.githubusercontent.com/5039340/71946291-570dc680-3204-11ea-98a8-f8fa50dbf6be.png)
![image](https://user-images.githubusercontent.com/5039340/71947081-9fc67f00-3206-11ea-835a-e93b24cf1042.png)

**Expected behavior:**
Type checking work in circular  reference
**Actual behavior:**
Type checking not work in circular  reference

[Playground Link](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgMoFcBGAxdIHIDeAUMmcgBQjoC2m0AXMgM5hSgDmAlE3CAJ7EAvsRh4EYYAHsQyMfgrMsufEww5xXIqXJQIYdFFkByAB7HhxBDNbJTyALzbyLSAAdmTEi5dwm8hAoKLQcAPmcfSIB6KOQAdQALCFkAAyUNfBTkBLhmZDhkMH43FAATCBhQFEx0MGQQKTqUvn4UgBodSJcYwqTZMCTC4pQEJIQAa05kYDyGuoB3KShJkA4mZEA+DcAUXcB4P+293c6usj0DIzsAOlYIDwu4C-moGQ4jlyEuI5EhZFFxSRk5OIAEyKZTiXgCLTeXT6QwmUxAiwiawgWwIxwRMjXDxeV7kPyA-Ag4KOcLQ45kHoASRgyDSYMy0zy5UqIAgpXyeWaAnayAgADdoPwBlMADZSKTjPIcPRwMAXPHRKKKnw9AAqVIACqhAFj-mqeJSgRWQxkez2MyFKUggs0afNMMzqAKKJRNrHYq2MCopMLOsgRV3czDuDyeqxV70+lhRaIAzBjya4bp5MT4CQFiSEySrurEaXT0ioEFkZpaKlUObk6S1eQKhSLVshxZLpbL5TnfXC7EDA8m7hGPm9hEA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
There's still an error in the first block. TS currently is not capable of analyzing circular expressions with enough smarts to avoid seeing a circularity in this case.
