### ISSUE TITLE
Error getSyntactifClassifications

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#3607]
I was testing the latest TypeScript in VS (644ea82ee39f16102b776f98a9) and I had some error popups when typing. 
It only happened on invalid code (because I was typing) so I'm not sure if this really is an issue but see the attached image
![tserror](https://cloud.githubusercontent.com/assets/765657/8313227/c2bac17a-19e1-11e5-9412-bd2415eb26cb.png)

Feel free to close if this is just expected because I'm running in DevMode.

**edit** oops, I forgot to add the code... 

    class foo {
        public bar() {
            this
        }
    }

It happens when typing a `.` (dot) right after `this` but also when trying to type a comment there.

**Comment by vladima** [comment]
This is bug, repro:
```typescript
class A {
    a:
}
```
pinging @CyrusNajmabadi

**Comment by DickvdBrink** [comment]
That was fast! Thanks!
