### ISSUE TITLE
"source.organizeImports" shouldn't remove my unused imports

### ISSUE THREAD

**Issue by yardz** [microsoft/TypeScript#36085]
## Search Terms

source.organizeImports, remove unused imports, don't remove unused imports

## Suggestion

When i put "source.organize Imports" in "editor.codeActionsOnSave" it removes my unused imports. It would be interesting to have a parameter for it to just organize but not remove.

## Use Cases

Many developers save their files all the time, often without even realizing it. This feature is very interesting but ends up "disturbing" who has this habit.

If you can pass a few more configuration parameters (like not removing unused imports or not removing space between imports) this feature would be better taken advantage of.

**Comment by limahatzl** [comment]
I would love this feature. 

It really helps if we have a parameter to decide if we want vscode to remove or not the unused imports. 

I have many problems when I am coding and then suddenly the import disappear. 

The solution is: all the time I have to add the import again or I have to add another third party plugin to control my imports instead of using the vscode functionality.

🚀

**Comment by sunknudsen** [comment]
We definitively need an option to grey out unused imports vs removing them. Here’s my use case. When I temporarily disable code blocks, the related imports are removed if not used elsewhere in the code. When I re-enable them, the imports are gone and the code is broken.

**Comment by sunknudsen** [comment]
@RyanCavanaugh, is there a fix for this aside from disabling `source.organizeImports`?

**Comment by yardz** [comment]
> We definitively need an option to grey out unused imports vs removing them. Here’s my use case. When I temporarily disable code blocks, the related imports are removed if not used elsewhere in the code. When I re-enable them, the imports are gone and the code is broken.

It happens to me all the time... And worse, I have a habit of saving every line of writing, so I often import, save, write the code I'm going to use that import... This is terrible for me ... I have to "fight the IDE" to program the way I'm used to...

**Comment by karlhorky** [comment]
Just found this via https://github.com/microsoft/vscode/issues/89263 - also was just bitten by this: 

- I was doing some research and left my code in an invalid state: a template string was open, causing the rest of the file (including usages of imports) to be an invalid template string with no end
- The imports were automatically removed by the Organize Imports in `editor.codeActionsOnSave`
- I came back and fixed my code, but now other things were broken.

Two suggestions here:

1. Maybe don't run Organize Imports if the code is not valid?
2. Maybe this could be a setting, for those who do want the auto-removal behavior? I would count myself in this group too, as long as my code was valid.

**Comment by yardz** [comment]
@karlhorky I am no longer using organize because of this. In fact I am using it manually sometimes, when I have finished all changes to the file.

It would be nice if there were two separate features, one to organize and one to remove.
I believe that it would answer many other cases, without implementing any "new behavior".

People who just want to remove unused imports and / or people who want to organize imports.

**Comment by yardz** [comment]
I will close this issue because the problem is with vscode and not with typescript.

**Comment by karlhorky** [comment]
@RyanCavanaugh would it be possible to get an option / separate function for this?

Or if not, what would you like to see with "more feedback"? I guess this would be a pretty important issue for a lot of developers...

**Comment by karlhorky** [comment]
For an example of a user story why a setting would be critical to some users, here's what we've been running into:

Bootcamp students at @upleveled are beginners - they are learning how to code for the first time. It is very helpful for them to have tools that help them with best practices, such as auto saving, code formatting, auto sorting and import combining tools. If they use `source.organizeImports`, it gets them some of these features! 🎉 But it has a critical weakness: after they have achieved the task of adding an import, if they switch to another file, the combination of auto save and `source.organizeImports` will cause their hard-earned imports to be erased. 😫

cc @RyanCavanaugh @amcasey @andrewbranch

**Comment by karlhorky** [comment]
I think the following may be a suitable plan, which will still keep those happy who appreciate this removal behavior:

1. Change the default behavior of `source.organizeImports` to not remove unused lines
2. Add a new code action for the current behavior, eg. `source.organizeAndRemoveImports`

It would also make the behavior of the option more explicit.

**Comment by 1337cookie** [comment]
> 1. Change the default behavior of `source.organizeImports` to not remove unused lines
> 2. Add a new code action for the current behavior, eg. `source.organizeAndRemoveImports`

I think something even more explicit than this would be `source.sortImports` and `source.removeUnusedImports`. This would give more granularity in the behaviour. 
I can imagine a scenario where someone may want to remove unused imports but maintain a particular order and a scenario where someone only wants to sort the imports but keep the unused one. 
The current behaivour with `source.organizeImports` could be left as-is to avoid disturbing anyone already happy with how it works.

**Comment by OliverJAsh** [comment]
FWIW I discovered this already exists under a slightly different name: `source.removeImports`. For example here is how you would setup a keyboard shortcut to remove unused imports:

```jsonc
  {
    "key": "shift+ctrl+r",
    "command": "editor.action.sourceAction",
    "args": {
      "kind": "source.removeUnused",
      "apply": "first"
    }
  },
```

**Comment by andrewbranch** [comment]
Note that `removeUnused` removes _all_ unused declarations, not just imports.

**Comment by karlhorky** [comment]
Ohh was this just released in VS Code 1.57? 👀 🎉

```json
"editor.codeActionsOnSave": {
    "source.sortImports": true
}
```

https://code.visualstudio.com/updates/v1_57#_sort-imports-source-action

**Comment by karlhorky** [comment]
@yardz if you test this out and it addresses your wish, maybe you can close this issue?

**Comment by joeytwiddle** [comment]
Thanks for the suggestion to use `source.sortImports`.

I will just tag the VSCode issue, to make this solution easier to find from there. https://github.com/microsoft/vscode/issues/112021

**Comment by jankkosinski** [comment]
`"editor.codeActionsOnSave": {
    "source.sortImports": true
}` - it works properly. That's perfect!

**Comment by yardz** [comment]
@karlhorky Sorry for the delay, I wasn't following and missed the notification. I just tested it and it really works.
It is perfect!

**Comment by sjc5** [comment]
I have noticed that switching to `sortImports` over `organizeImports` now breaks unused imports highlighting in vs-code, seemingly as though `sortImports` causes TS to stop checking whether imports are used/unused at all (as opposed to solely not deleting them on save when unused, which IMO would be desired behavior).

Anyone else seeing this?

**Comment by NickDiVona** [comment]
@sjc5 I'm not seeing that on my end. Unused imports are still showing as unused and vice versa.
