### ISSUE TITLE
geterr only returning syntaxDiag

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36081]
From https://github.com/microsoft/vscode/issues/88209

**TypeScript Version:**  3.7.4

**Symptoms**
@dbaeumer Has reported seeing stale typescript errors in VS code. When looking over [a trace](https://github.com/microsoft/vscode/files/4034523/88209-trace.txt) of what  VS Code gets back from TypeScript, it seems that at some point we only start getting back `syntaxDiag` errors from `geterr` and not `semanticDiag` (look at request 1433 for example)

This starts around request 1380, which is a `geterr` request that is canceled before being fully completed. I wonder if this would be leaving the server in an inconsistent state.

@dbaeumer Can you also please try collecting the TS Server log for this case

**Comment by epranka** [comment]
I attach trace log of my scenario: https://github.com/microsoft/vscode/issues/88209#issuecomment-572219893

This is the same issue.

[ts-trace.log](https://github.com/microsoft/TypeScript/files/4036916/ts-trace.log)

**Comment by mjbvz** [comment]
@epranka Is that the complete log? I don't see any calls to format.

**Comment by epranka** [comment]
> @epranka Is that the complete log? I don't see any calls to format.

It's only TS server log

**Comment by sheetalkamat** [comment]
we need tsserver log using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) to take a look at this. 

You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file.

**Comment by epranka** [comment]
[tsserver.log](https://github.com/microsoft/TypeScript/files/4039230/tsserver.log)

**Comment by dbaeumer** [comment]
![capture](https://user-images.githubusercontent.com/1931590/72053137-bc29f080-32c6-11ea-9462-c03f89af77ea.png)

[tsserver.log.txt](https://github.com/microsoft/TypeScript/files/4039514/tsserver.log.txt)

**Comment by dbaeumer** [comment]
Looking at the log and the TS server code the problem seems to be a thrown Error when computing the diagnostics caused here: https://github.com/Microsoft/TypeScript/blob/release-3.7/src/compiler/checker.ts#L30455

Shouldn't the code check if `iterationTypes !== noIterationTypes` as well and not only for undefined.

At least my case looks like a dup of https://github.com/microsoft/TypeScript/issues/32953

**Comment by dbaeumer** [comment]
@sheetalkamat @RyanCavanaugh any news on this. I see this quite frequent (ever ~10 minutes).
