### ISSUE TITLE
returning from a for loop breaks narrowing

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#36088]
**TypeScript Version:**  3.8.0-dev.20200107 (nightly on Playground

**Search Terms:** for return loop

**Code**

```ts
function test() {
  for (var x: string | number = 'a'; typeof x === 'string'; x = x.toUpperCase()) {
    return;
  }
}
```

**Expected behavior:**
No error, just as if `return;` were not present

**Actual behavior:**

The terminating condition fails to narrow the type for the increment clause:

> Property 'toUpperCase' does not exist on type 'string | number'.

I suspect this happens because exiting the loop early (especially with `break;` means that the narrowing doesn't apply after the loop body.
However, that's never true for the increment clause.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200107&ssl=1&ssc=1&pln=5&pc=2#code/GYVwdgxgLglg9mABFApgZygCgJSIN4BQiiwcATopgG4CGFAHgFyIZkxgDmiAPomCAFsARigoBeRAHIakgNzIAngAcUcYInqIx2qa3Yc5GrRoB0UOAFUlKsgGEaaFDlyFixMiiggyYWUUQAvgQBQA)

**Related Issues:** None

**Comment by RyanCavanaugh** [comment]
See #26914
