### ISSUE TITLE
Type of function return value is not narrowed based on function parameters

### ISSUE THREAD

**Issue by joyzhong** [microsoft/TypeScript#36083]
**TypeScript Version:**
3.7.2, Nightly

**Search Terms:**
type narrow function parameter

**Code**

```ts
function stringOrUndefined(returnStr: boolean) {
    return returnStr ? 'foo' : undefined;
}

const str = stringOrUndefined(true);
str.concat('bar');
```

**Expected behavior:**
This should be acceptable, as `str` should be narrowed to string type.

**Actual behavior:**
Error, as `str` is typed as string|undefined.
Object is possibly 'undefined'.

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=7&pc=1#code/GYVwdgxgLglg9mABAZygJxmA5geTQVTABMBTYTEogCjRKhDTAGV0AuRAIzjgBsSBDMAEpEAbwBQiKYlr1GMug2bpEAfkQByYNw2J24UuTCUA3OIC+48RASoUKgLz2M2PIUMVq6ECSFnUaAB0NpD8UFQaHPxoGn7iQA

**Related Issues:**
No

**Comment by j-oliveras** [comment]
You can do it:
```ts
function stringOrUndefined(returnStr: true): string;
function stringOrUndefined(returnStr: false): undefined;
function stringOrUndefined(returnStr: boolean): string | undefined; // You can remove it
function stringOrUndefined(returnStr: boolean): string | undefined {
    return returnStr ? 'foo' : undefined;
}

const str = stringOrUndefined(true);
str.concat('bar');
```

[Playground](https://www.typescriptlang.org/play/?ssl=10&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABAZygJxmA5geTQVTABMBTYTEogCjRKhDTAGV0AuRdEEgSndQ2wBuAFChIsBCnSZcBYmQrVa9RizTtgAQwA2yHu3ClyYSiLHR4SfjLyEjimnQbM2iAEZw42kprC8pAliIAD6IhgomRIKIAPQxiACacCCIEL6ItAC2cABuJIgwUKLgFpLW2LbyxpSOKi7q7p7evv7lQaHh1USIAN7CiAMZToxDdWqIAPyIAOTAntOIBlWKIgC+wsIQCKgBiAC8ATZy9pFUnDwi-AB0W5CaUFTTbppo09wiQA).

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; function implementations are assumed to be at least somewhat opaque in the absence of hints to the contrary

**Comment by joyzhong** [comment]
I see, thanks for clarifying!
