### ISSUE TITLE
AST does not include an `Any` token for restructured bindings

### ISSUE THREAD

**Issue by leeavital** [Microsoft/TypeScript#3609]
The AST will not include an Any token when parsing restructured bindings. I wrote the following program to demonstrate.

test.ts
````typescript
let {a: any, b: number} = {a: 2, b: 4};
````

print_tokens.js
````javascript
var ts = require('typescript');
var fs = require('fs');

var txt = fs.readFileSync("test.ts").toString('utf-8');
var sf = ts.createSourceFile("test.ts", txt, 1 /* es5*/ , false);

function printKinds(node) {
  console.log(node.kind);
  ts.forEachChild(node, printKinds);
}

ts.forEachChild(sf, printKinds);
````

We expect two Any tokens (code=112).  The output is:
````
180
199
198
150
152
65
65
152
65
65
154
224
65
7
224
65
7
1
````

When I change test.ts to
````typescript
let a: any = 2;
````

I get

````
180
199
198
65
112
7
1
````
which includes 112.

Is this expected behavior?

**Comment by RyanCavanaugh** [comment]
Yes. The names `any` and `number` in your example are *identifiers* in the value space, not keywords that are types. This destructuring means "Take the `a` member of the RHS and assign it to the variable `any` and take the `b` member of the RHS and assign it to the variable `number`".

```ts
let {a: any, b: number} = { a: 2, b: 4 };

any = 43;
any = 'foo'; // error
number = 100;
number = 'bar'; // error
```

**Comment by danquirk** [comment]
For completeness, if you want a type annotation on a destructuring binding you need to apply it to the whole binding, not individual elements, since ES6 uses that syntax for renaming:
```ts
let {a, b}: { a: any; b: number } = { a: 2, b: 4 };
b = 'no'; // error
```
