### ISSUE TITLE
StringEnum in conditional expression

### ISSUE THREAD

**Issue by omqmo** [microsoft/TypeScript#36096]
```
enum AnswerVariant{
    Yes = "yes",
    No = "no",
    Difficulty="difficulty"
}

interface IQuestion{
    answer: AnswerVariant;
}

const hasEmptyAnswer = (question: IQuestion) =>
    question.answer !== AnswerVariant.Yes || question.answer !== AnswerVariant.No; // second condition error! This condition will always return 'true' since the types 'AnswerVariant.Yes' and 'AnswerVariant.No' have no overlap.(2367)

/**
 * This is bug?
 * First condition question.answer is AnswerVariant
 * Second condition question.answer is AnswerVariant.Yes!!???
 * But first condition proved that answer is not an AnswerVariant.Yes
 */
```

[Playground](https://www.typescriptlang.org/play/?ssl=19&ssc=4&pln=1&pc=1#code/KYOwrgtgBAgiDOB3YAnAagQxQSwyALgN4BQUZUAmsPFALxQBEAntQwDSnkByA9nYyB7tOZACLYAZhOwBjMABt8TWgwAmk6XMVMGxAL7Fi2AqgkYZwKAEkAimGr5sPECXJQ8SVAC5YCZOixcAgBufUMZZ3h8KAALDHgAUQgAByU4TxR+AAoAR3sopxAfW3zHZwBKOgA+ESg8h0KAOg9-KABCWnp0-0wcPHxGqhoAH2G60qaW1HbO3wzeoIHeUOIAegAqddJ1qAAVGOwaQ6gAIzAAcwB+bagAMWwUKKgIkHUykHGG52a-aePu1ALfo3ADKwBeqmezjehU+BW+U0y-1+AT6BEG1DabUuOJuACEwNFpI9ohDsO8oMkUDwAG7ASH4OLRRFQY6CZkfAGoxYY+DbVZAA)

**Comment by IllusionMH** [comment]
Guessing from function name it looks more like TS notices potential bug in the logic and functions as designed

You can see yourself that your implementations always return true and updated variant.
[Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=31&pc=111#code/KYOwrgtgBAgiDOB3YAnAagQxQSwyALlAN4BQU5UAmsPFALxQBEAnjYwDRkUByA9vUxC8OXcgBFsAM0nYAxmAA2+ZgMYATKTPlLmjEgF8SJbAVSSMs4FACSARTA182XiGKioeJKgBcsBMnQsXAIAbgMjWRd4QgALDHgAUQgAB2U4LxQBAAoARwdo5xBfO3ynFwBKegA+dzzHQoA6TwCoAEI6BnSAzBw8fAbqWgAfIag6gpcm-1Q2jr8MnuD+vjCSAHoAKg2yDagAFRjsWiOoACMwAHMAfh2oADFsFGioSJANMtdxj6mMqBOu1CLPq3ADKwFeaheLnehTGpUazRm-2mgV6BAGNFarSuONuACEwIQZE9CBDsB8oMkULwAG7ASH4OKERGZE5CZmuAGopYY+A7NYRKK8BTABoKXgXLIAcl4OAuJgwCil7Hm3SCfV5KriiRSaRRWSIHhRvi5QPRgyg+nK5TCr3gwtF4slMrlCqVKtN6vRfC18SSqWYXINRoyJpRZuW-CtNpIdodYol0tl2HlIEVytVgK9-Qk0jkimUvp1AaDhpZYYW2Yaua0BZU0dWsaisT9usDKIAqsk1Bh8PTsl9CsV7PUKtVavDJizZp1w1WLQAyBdw0cgH4tdqzytoyOrOMihPOsDd3v0jOeneaqDa-16jJdnt9tTB8uZ7kai0NpsIeNO6XHx8zw9OdLx9a9WxLTsTyfF9jTfCMGj4S1rVtIUDz-KUANPNRzxAnka3zHQi1vdt72g+lYNDeCqwI7RlGQm0gA)

**Comment by RyanCavanaugh** [comment]
TypeScript found a bug in your code. You meant to use `&&`, not `||`.
