### ISSUE TITLE
TypeScript Organize Imports inserts extra newline

### ISSUE THREAD

**Issue by xROAL** [microsoft/TypeScript#36102]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.0-dev.20200108

**Search Terms**
- Organize imports

---

In TypeScript / JavaScript, the command `Organize Imports` inserts up to two newlines if `export { ... };` is at the end of a file. This does not happen with other forms of `export`.

- VSCode Version: 1.41.1
- OS Version: Windows 10 (1803)

Steps to Reproduce:
1. Have a list / renamed export as the last line of your file, e.g.:
```
import { Router } from 'express';
const router = Router();
// ... other code
export { router as namedRouter }; // also happens with `export { router };`
```
2. Run the `Organize Imports` command. It will insert a newline after the `export { ... };`
3. Run the `Organize Imports` command again. It will insert another newline, resulting in two empty lines at the end of the file.

**Expected behavior**
Only one newline is inserted / kept after the `export { ... };`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Kinrany** [comment]
Should this be in 3.8?

**Comment by captain-yossarian** [comment]
Can I pick it up?

**Comment by DanielRosenwasser** [comment]
Yes

**Comment by DanielRosenwasser** [comment]
(Unless @elibarzilay has already started, but I assume you can go ahead)

**Comment by captain-yossarian** [comment]
@DanielRosenwasser if @elibarzilay has already started then I will only follow this. Anyway I don't know where to start

**Comment by Kinrany** [comment]
I believe you'll need to fix [`coalesceExports`] in `src/services/organizeImports.ts`

[`coalesceExports`]: https://github.com/microsoft/TypeScript/blob/master/src/services/organizeImports.ts#L292

**Comment by captain-yossarian** [comment]
@Kinrany Thank you

**Comment by captain-yossarian** [comment]
@Kinrany do you know how to debug this file? I've tried to put `console.log`, but it is throws an error

**Comment by captain-yossarian** [comment]
@DanielRosenwasser @elibarzilay @Kinrany 
I'm able to reproduce the bug, but I'm unable to see any of my logs.
I've tried:
 - link `typescript` local build to my project (`npm link`)
- change  "typescript.tsdk":"D:/js/typescript/TypeScript-master/lib"
-  add logs directly into node_modules  source code (without any links)
- to use console.log and logger.log
it did not help :/

How should I do it right?

**Comment by elibarzilay** [comment]
@captain-yossarian I'm new so little experience with trying to run things live, instead I start with a test case for the problem and then use the debugger.

**Comment by ahtee** [comment]
Do you have any auto formatters installed currently? Something like prettier may be adding the new line.

**Comment by RudeySH** [comment]
If someone out there is still having this issue, try disabling the "EditorConfig for VS Code" extension or removing `insert_final_newline = true` rule from `.editorconfig`.

**Comment by MM1132** [comment]
I did set `"source.insertFinalNewline": false`. Nothing changed. 
`"source.organizeImports": true` still inserts a newline at the end of imports.

**Comment by RudeySH** [comment]
@MM1132 This issue is about a problem where VS Code inserts **two** newlines at the end of imports, which can be solved by disabling insertFinalNewline. This solution will not make VS Code stop inserting a single newline at the end of imports, it just fixes the duplicate newline problem.

**Comment by MM1132** [comment]
`insertFinalNewline` changes absolutely nothing. For now, disabling `source.organizeImports` is the only thing that makes VsCode not insert double newline after imports.

**Comment by bene-we** [comment]
I didn't test it extensively, but for me adding the following to `settings.json` worked so far:

```json
"files.insertFinalNewline": true,
"files.trimFinalNewlines": true,
```

With that, multiple newlines at the end of a file are being trimmed to only have a single newline, and it seems that this setting runs last.

**Comment by rnveach** [comment]
I just ran into this, and while the previous post does ends up saving the file correctly, you can see it is adding the new line and then subsequently removing the line quickly before the save, depending on how slow your system is.
