### ISSUE TITLE
If node_modules folder or a subfolder (like with pnpm) is a symlink (under Windows), TypeScript auto imports do not work anymore 

### ISSUE THREAD

**Issue by stefanocke** [microsoft/TypeScript#36104]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Copy some TypeScript project into a new folder
2. There, replace node_modules directory by a symlink to the node_modules in the original TypeScript project
3. Try to import something from node_modules in the copied project (for example, somethinf from @angular/core in an Angular project). The import will work (no compiler error), but there is no light bulb and no intellisense support for the import

More explanation:

- We use symlinked node_modules to share them between multiple projects. It is our own solution, but tools like https://pnpm.js.org/ do similar things. So, other users might have the same issue.
- I have not tested it under Linux yet. Only Win 10.
- I have searched for similar issues with keyword "symlink", but I am not sure any of them matches.
- I think it stopped working some months ago but unfortunately I cannot tell exactly. I am sure it worked in the past.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that fix the issue?

**Comment by stefanocke** [comment]
@mjbvz , with typescript@next  (3.8.0-dev.20200109), there is no difference.

**Comment by stefanocke** [comment]
I verified with [pnmp](https://pnpm.js.org/). 
There, not node_module itself is a symlink, but the subfolders are.
Same effect: Auto-import is not working.

**Comment by thynson** [comment]
Auto import does not work in macOS with pnpm, too.

**Comment by sheetalkamat** [comment]
This seems to work correctly with typescript@next .. Please let us know if this is still the issue and if it is create a sample repro and provide detail steps. Thanks

**Comment by stefanocke** [comment]
Verified that it works with pnpm and typescript 3.9.0-dev.20200323

@thynson , is it working for you as well with typescript@next?

**Comment by thynson** [comment]
💯 It works now. 
Hope it could be backported into v3.8.
