### ISSUE TITLE
Support for NodeList methods

### ISSUE THREAD

**Issue by mkay581** [microsoft/TypeScript#36113]
**TypeScript Version:**  3.7.4

**Search Terms:**

NodeListOf, NodeList

**Expected behavior:**

`NodeListOf` to contain the methods available at https://developer.mozilla.org/en-US/docs/Web/API/NodeList. 

**Actual behavior:**

`NodeListOf` does not contain the methods available at https://developer.mozilla.org/en-US/docs/Web/API/NodeList. `forEach` and `item` seem to be there though.

**Playground Link:** 

**Related Issues:** 

https://github.com/microsoft/TypeScript/pull/14641

**Comment by IllusionMH** [comment]
Definitions for `NodeListOf` are split into two files: 
1. `length`, `item`, and `forEach` in [`dom.generated.d.ts`](https://github.com/microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L11249-L11259)

1. `entries`, `keys`, and `values` in [`dom.iterable.generated.d.ts`](https://github.com/microsoft/TypeScript/blob/5fc917be2e4dd64c8e9504d36615cd7fbfdd4cd3/src/lib/dom.iterable.generated.d.ts#L164-L178)

Looks like all are in place already.

Are you sure you have both `dom` and `dom.iterable` or something like `es2015.full` in `compilerOptions` > `lib`?

**Comment by usmcgwg** [comment]
I dont haven't had time  to further testing in order to get a positive run.
Could be so kind as to move forward with the right course of action. Please
and thank. Your time and consideration is highly appreciated

**Comment by mkay581** [comment]
> Are you sure you have both `dom` and `dom.iterable` or something like `es2015.full` in `compilerOptions` > `lib`?

Ah yes, that was it. I had `dom` lib but didn't realize I needed `dom.iterable` also. Closing. Thanks!
