### ISSUE TITLE
Generic forwarding from `keyof typeof Record<T, any>`

### ISSUE THREAD

**Issue by maraisr** [microsoft/TypeScript#36117]
**TypeScript Version:**  3.7.2

**Search Terms:**
- generic types
- generic forwarding
- abstract methods

**Code**

```ts
type StyleMap<ClassName extends string> = Record<ClassName, string>;
type Style = Record<string, string>;

type Red = 'red1' | 'red2';
type Blue = 'blue1' | 'blue2';

type Colours = Red | Blue;
interface Theme {
    colours: Record<Colours | 'white', string>;
}

const theme: Theme = {
    colours: {
        blue1: 'blue-colour-1',
        blue2: 'blue-colour-2',
        red1: 'blue-colour-1',
        red2: 'blue-colour-2',
        white: 'white'
    }
}

declare function toClassList<T extends Record<string, string | number>>(list: T): Record<keyof T, Style>;

const classListTest = toClassList(theme.colours);

declare const colourMap: keyof typeof classListTest;
```

**Expected behavior:**
In my playground example, I expect the `colourMap` to "auto-complete" an item in the `Colours` type alist + `'white'`. However, doesn't seem to resolve.

**Playground Link:** : https://www.typescriptlang.org/play/?target=99#code/C4TwDgpgBAyqA2ECyBDMAeAwvFBnXAcigLbQQAewEAdgCa5S7ABOAltQOYB8UAvFACUIAYwD2zWlhz4ipADSMW7bgG4AUKEiwE0fkLET0TNpwXHlXdRvDQhtPlADkzCLQCMjqAB8nL2gCZHdU1oACF4AFddJwAjSIgPb1j4wKsQqExReFEI5gY9VyTwqPV2KmYAMxRhaAAVAAsIUigAbzUoDqgxbNzcAC5BEXFJTJ68pMcAd3rWKkczJU5LNQBfNTUxaiYoYEbSAYam6LbOrqycvIGT0864qLcBxzuIAFpui5ePOXabjuf-R7PN7nXIvQLfX4dPwPZJRYFjT7zH6-PwA2Gvd6g8HIm7TWYQR54uY4tZrNS0EQ4FxQCoRajCYCsUTUHaibB4XAAGVYTHQtSgFCodAY+mGRkWHAWJg4SWoEWIMQgzC4XAAFPAecADgBKAaiwwAawgIFEFSgtQUcBAiGWG2Z22E0i5mtqEG2-GAbKd3KYqt2RwAdJi8tqrBTHShqZsHSDmKgwAMjSazSFTV1vS63cArMH4w5HI51kA

**Comment by dragomirtitian** [comment]
`colourMap` is declared as `const` so you will not get autocomplete when you try to reassign it, but if i hit ctrl+space I get autocomplete when initializing the const or when reassigning a `let` declaration. 
![image](https://user-images.githubusercontent.com/8193316/72142803-2c577580-339e-11ea-84b3-6205bb5e6eff.png)

Or did I miss where or what autocomplete you were expecting ..😕

**Comment by maraisr** [comment]
Wow that is gold... Kinda light bulb actually... Didn't know that about `const` being treated as a reassignment, and thus not "autocompleting". So thanks for that. I was trying to have a playground reproduction case; which looks like has failed.

But here is an example where it hasn't worked:

https://github.com/autoguru-au/overdrive/blob/6476582b38689ffb984bc2abb177ff99e3e66619/lib/components/Box/useBoxStyles.ts#L52

which is defined here: https://github.com/autoguru-au/overdrive/blob/6476582b38689ffb984bc2abb177ff99e3e66619/lib/components/Box/useBoxStyles.treat.ts#L69-L71

that gets its map from here: https://github.com/autoguru-au/overdrive/blob/6476582b38689ffb984bc2abb177ff99e3e66619/lib/utils/mapTokenToProperty.ts#L4-L7

> reference treat types: https://github.com/seek-oss/treat/blob/master/packages/treat/src/types.ts

eg:


```ts
import * as styleRefs from './tokens.treat.ts';

interface BoxStyleProps {
	backgroundColour?: keyof typeof styleRefs.backgroundColours;
}

// tokens.treat.ts
import { Properties } from 'csstype';

const mapTokenToProperty = <T extends unknown>(
	record: T,
	property: keyof Properties,
): Record<keyof T, Style> =>
	Object.entries(record).reduce(
		(result, [key, value]) => ({
			...result,
			[key]: { [property]: value },
		}),
		{} as Record<keyof T, Style>,
	);

export const backgroundColours = styleMap(theme =>
	mapTokenToProperty(theme.colours.gamut, 'backgroundColor'),
);
```

but for some reason; the `BoxStyleProps['backgroundColour']` resolves to a `Record<never, string>` or something???


HUGE caveat; yes I was just that guy that posted their entire code base, and said "fix it".... But in saying that, the general gist is. There is record, that gets its types from a `keyof typeof`, that gets mapped about 3 times. But should basically retain its keyof's all the way down the line. Esentially: `keyof Record<keyof Record<'a' | 'b', string>, string>`

**Comment by RyanCavanaugh** [comment]
We'd need an isolated repro to be able to investigate.
