### ISSUE TITLE
Return `this.#value` suggestions when typing out a private field in a class

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36118]
**TypeScript Version:**  3.8.0-dev.20200108

**Search Terms:**
- suggestion / suggestions
- completion / compltions
- No content available
- completionInfo

**Code**
For the TS:

```ts
class K {
    #value: number;

    private keyword: number = 1;

    foo() {
        
    }
}
```

1. In `foo`, type `#va` (without a `this.`!) and trigger suggestions

**Expected behavior:**
A suggestion for `#value` should be returned. Accepting this suggestion should automatically insert `this.` to create:

```ts
class K {
    #value: number;

    private keyword: number = 1;

    foo() {
        this.#value
    }
}
```

This is what private properties such as `keyword` do

**Actual behavior:**
No suggestions returned

**Related Issues:** 
- #35954
- #36116

**Comment by andrewbranch** [comment]
It seems this was fixed automagically by #36188 🎉
