### ISSUE TITLE
Wrong type assertion on array when using type isntruction

### ISSUE THREAD

**Issue by AlexDmr** [microsoft/TypeScript#36127]
There is a problem with type assertion on array :
Exemple (tested on http://www.typescriptlang.org/play v3.7 and v3.8)
1. type T = 'X' | 'Y' | 'Z';
2. const s = ['X', 'Y', 'Z', 'A'] as T[];
3. const s2: T[] = ['X', 'Y', 'Z', 'A'];

** Actual behavior 
No error detected on line 2
Type error detected for line 3

**Expected behavior:**
Type error detected for line 2 and line 3

**Comment by dragomirtitian** [comment]
Line 2 and 3 are not equivalent. 2 is a type assertion. Type assertion checks are not as strict as assignment checks, by definition. When you use a type assertion, you are telling the compiler to ignore what it knows and pretend the type of something is what you tell it to be. Type assertions can lead to inconsistent types for values if what is asserted is not actually true. This is why they should be used sparingly.

**Comment by AlexDmr** [comment]
Yes I agree that these lines are not equivalent.
However I would assume that the compiler is checked that the assertion is credible.
For instance:
const a: Animal = ...
const b = a as Cat
// is credible because Cat is an Animal

This is not the case with my previous example. I guess this is due of the usage of type disjunction which probably is projected into string type in the assertion ?

**Comment by RyanCavanaugh** [comment]
This is no less a downcast than your Cat/Animal example.
