### ISSUE TITLE
esModuleInterop is ignored when using project references

### ISSUE THREAD

**Issue by cyberalien** [microsoft/TypeScript#36144]
**TypeScript Version:**  3.8.0-dev.20200111

**Search Terms:** "esModuleInterop", "esModuleInterop composite", "esModuleInterop project"

**Code**
Repository with short test case: https://github.com/cyberalien/typescript_esmoduleinterop_bug

Root tsconfig.json includes 2 projects: src/tsconfig.json and tests/tsconfig.json
Flag `esModuleInterop` is enabled in src/tsconfig.json and tests/tsconfig.json

However when running `tsc -b`, it throws error that esModuleInterop is not enabled.

**Expected behavior:**
Test case should compile without issues.

**Actual behavior:**
tsc throws following error:
```
src/get_uri.ts:1:8 - error TS1259: Module '"node_modules/@types/request/index"' can only be default-imported using the 'esModuleInterop' flag

1 import request, { Response } from 'request';
         ~~~~~~~

  node_modules/@types/request/index.d.ts:405:1
    405 export = request;
        ~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.
```

**Workaround:** 
Workaround to demonstrate that this is compiler issue, not code issue: to root tsconfig.json add this:
```
	"compilerOptions": {
		"composite": true,
		"esModuleInterop": true,
		"noEmit": true
	},
```
(see tsconfig-workaround.json in repository)

Then esModuleInterop becomes enabled in referenced projects.

**Comment by ajafff** [comment]
Try setting `"files": [], "include": []` in your root tsconfig.json. Otherwise it will be treated as a regular project which just happens to contain project references. By explicitly excluding all files, TypeScript will not attempt to use this tsconfig.json to compile files and instead only processes the project references.

**Comment by cyberalien** [comment]
That works.

However other options do work in referenced files, except for esModuleInterop. Does that mean esModuleInterop is treated differently than other options or is it a bug?

**Comment by RyanCavanaugh** [comment]
@ajafff has the right answer. TS is doing exactly what you told it to do: You have a project here (`/tsconfig.json`) that *doesn't* have `esModuleInterop` set but does include files (through the implicit `include`) that can only import each other if that flag is set.

**Comment by cyberalien** [comment]
Yes, project doesn't have `esModuleInterop`, but included files do. When changing other options in included files, they do work. When changing `esModuleInterop` in included files, it does not work.

**Comment by khachaturs** [comment]
> Try setting `"files": [], "include": []` in your root tsconfig.json. Otherwise it will be treated as a regular project which just happens to contain project references. By explicitly excluding all files, TypeScript will not attempt to use this tsconfig.json to compile files and instead only processes the project references.

this does not work for me
in fact only putting compiler options directly into root tsconfig.json file works, which seems wrong to me

**Comment by Griffork** [comment]
@khachaturs try putting "files" and "include" inside "compilerOptions".
