### ISSUE TITLE
esModuleInterop + named export evaluated differently depends on usage

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#36149]
**TypeScript Version:**  3.7.3

**Search Terms:**
esModuleInterop named export enquirer

**Code**

![image](https://user-images.githubusercontent.com/3254987/72215474-de3e9100-34c7-11ea-8d1f-06ef18765a04.png)

![image](https://user-images.githubusercontent.com/3254987/72215481-e5fe3580-34c7-11ea-8dbf-cd5fed98cf70.png)

**Expected behavior:**
`AutoComplete` gets the function (class) regardless if the default export is being accessed.

This is very interesting and completely caught me by surprise.

`enquirer` is commonjs and exports using `module.exports = Enquirer`.

The curious thing this that it uses properties (static properties so to speak) to expose other classes in the `Enquirer` object:

```ts
import E from 'enquirer'

Object.keys(E)

// receives
[ 'autocomplete', 
  'basicauth', 
  'confirm', 
  'editable', 
  'form', 
  'input', 
  'invisible', 
  'list', 
  'multiselect', 
  'numeral', 
  'password', 
  'scale', 
  'select', 
  'snippet', 
  'sort', 
  'survey', 
  'text', 
  'toggle', 
  'quiz', 
  'ArrayPrompt', 
  'AuthPrompt', 
  'BooleanPrompt', 
  'NumberPrompt', 
  'StringPrompt' ] 
```

```ts
import E from 'enquirer'

Object.getOwnPropertyNames(E) //?

[ 'length', 
  'prototype', 
  'Prompt', 
  'prompts', 
  'types', 
  'prompt', 
  'name', 
  '_events', 
  '_eventsCount', 
  '_maxListeners', 
  'setMaxListeners', 
  'getMaxListeners', 
  'emit', 
  'addListener', 
  'on', 
  'prependListener', 
  'once', 
  'prependOnceListener', 
  'removeListener', 
  'off', 
  'removeAllListeners', 
  'listeners', 
  'rawListeners', 
  'listenerCount', 
  'eventNames', 
  'autocomplete', 
  'AutoComplete', 
  'basicauth', 
  'BasicAuth', 
  'confirm', 
  'Confirm', 
  'editable', 
  'Editable', 
  'form', 
  'Form', 
  'input', 
  'Input', 
  'invisible', 
  'Invisible', 
  'list', 
  'List', 
  'multiselect', 
  'MultiSelect', 
  'numeral', 
  'Numeral', 
  'password', 
  'Password', 
  'scale', 
  'Scale', 
  'select', 
  'Select', 
  'snippet', 
  'Snippet', 
  'sort', 
  'Sort', 
  'survey', 
  'Survey', 
  'text', 
  'Text', 
  'toggle', 
  'Toggle', 
  'quiz', 
  'Quiz', 
  'ArrayPrompt', 
  'AuthPrompt', 
  'BooleanPrompt', 
  'NumberPrompt', 
  'StringPrompt' ] 

```

The corresponding code:
```js
const prompts = Enquirer.prompts;

for (let name of Object.keys(prompts)) {
  let key = name.toLowerCase();

  let run = options => new prompts[name](options).run();
  Enquirer.prompt[key] = run;
  Enquirer[key] = run;

  if (!Enquirer[name]) {
    Reflect.defineProperty(Enquirer, name, { get: () => prompts[name] });
  }
}
```
where `Enquirer.prompts` has the `AutoComplete` class and its alias `autocomplete`

```js
// lib/prompts/index.js
const define = (key, fn) => {
  utils.defineExport(exports, key, fn);
  utils.defineExport(exports, key.toLowerCase(), fn);
};

define('AutoComplete', () => require('./autocomplete'));
```

**Comment by RyanCavanaugh** [comment]
I can't tell if you're describing a runtime bug, a typechecking bug, or an editor scenario bug. How is `enquirer` defined?

**Comment by unional** [comment]
Sorry, it is a runtime bug. `enquirer` typings is not complete. So please ignore the IDE error. The `//? [...]` in blue is the runtime result printed by Quokka, I use that in the screenshot because it is easy to demonstrate.

**Comment by unional** [comment]
Consider `<statement> //?` the same as `console.log(<statement>)`

**Comment by RyanCavanaugh** [comment]
For a runtime bug, please open a new issue describing which line of emit you think is wrong and why. Thanks!
