### ISSUE TITLE
Type error in callback function body when using union type.

### ISSUE THREAD

**Issue by realyze** [microsoft/TypeScript#36156]
In the snippet below, callback argument passed to `callAsynchonously` causes a compilation error `This condition will always return 'false' since the types 'ResourceState.LOADING | ResourceState.FAILED' and 'ResourceState.LOADED' have no overlap.`.

```
export const enum ResourceState {
    LOADING = 1,
    LOADED = 2,
}

export type Resource<T> = |
{
    status: ResourceState.LOADING,
    data?: never,
} | {
    status: ResourceState.LOADED,
    data: T,
};

function callAsynchonously(fn: Function) {
    setTimeout(fn, 1000);
}

export function doSomething() {
    const resource = { status: ResourceState.LOADING } as Resource<any>;

    if (resource.status !== ResourceState.LOADED) {
        callAsynchonously(() => resource.status === ResourceState.LOADED);
    }
}
```

Since the callback runs asynchronously, `resource.status` may have changed to `ResourceState.LOADED` when it is invoked. So typescript should not treat this as an error.

Note: If I change the `Resource` type to:
```
export type Resource<T> = {
  status: ResourceState.LOADING | ResourceState.LOADED | ResourceState.FAILED,
  data?: any,
};
```
it compiles OK.

Playground link here: https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=26&pc=1#code/KYDwDg9gTgLgBAYwgOwM72MgrgWzgJWFQiygWAGUYBDGYOAbwCg5W4AZAeQEEARASQByAcTgBeOAEYANCzZc+AUV7i4AJlkBfJk1CRYcGAE8w9QsVLkAPABUAfKoA+TZmzjpaWVAC4CREmSUNHQAdAoCIrJuACa01AD8vsjAAG7AUFpwjoxyrB4wXr7mAeRUtMBhPLzKUWyxNL42WgDcOgBmWMgIMACWKIjUADaD3KhGXQAWKCSog0YAFG3IvgBind19yACUOW6owDA2PTjAJDCLyNJSAAy3W63auuDQ8B1dvf3REBQQJzATPWQAHN5jtXGwkGh4FB-JZ6BIGO5goU-BZAmVQuEhKJNHBqKhUSVgFZqMgjHZWrk4D02nB5jC0eQQvkvHAAIRiCTFOEYirhZRgqluBBDEZjSbTLxzeag8QOBlE5nIgmcrmw9HBPlVAWtNzabRAA

**TypeScript Version:**: `3.7+` (possibly earlier versions too).

**Comment by RyanCavanaugh** [comment]
See #9998
