### ISSUE TITLE
Have `--strict`: true imply `--importsNotUsedAsValue`: "error"

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#36159]
## Search Terms

import type, 3.8, ESM, flag

## Suggestion

Change to existing "strict" flag:
- "strict" implies "--importsNotUsedAsValue: error"

## Use Cases

My understanding of `--strict` is that it implies giving the checker as much information as possible in order to "do the right thing."

Given that not using the [`new --importsNotUsedAsValue: error option`](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports) leads to off-spec behavior with regard to ES Modules (module side effects are not always run), it may be helpful to have "strict" imply opting in to more speccy ESM behavior.

> Churn to users can be reduced if there is a codemod like the one mentioned in the [PR that introduced `import type`](https://github.com/microsoft/TypeScript/pull/35200).

## Examples

- example of desired behavior: `--strict`: true implies `--importsNotUsedAsValue`: "error"

Here is an [example from the 3.8 beta announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports):

```ts
// This statement will get erased because of import elision.
import { SomeTypeFoo, SomeOtherTypeBar } from "./module-with-side-effects";
```

With the change described in this issue using `--strict` would lead to an error in the example above, ensuring that the user runs the codemode to convert to:

```ts
import type { SomeTypeFoo, SomeOtherTypeBar } from "./module-with-side-effects";
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code

This requirement is a breaking change for users of `--strict`, but adding new stuff to `strict` is always a breaking change.

* [x] This wouldn't change the runtime behavior of existing JavaScript code

* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
This came up at a design meeting, and we couldn't reach consensus on this behavior. I was and still am pretty strongly against doing this because it would be akin to turning on `isolatedModules` under `strict`. You'll find out quickly if import elision is a problem, and it's not like you can't opt into it yourself.

**Comment by DanielRosenwasser** [comment]
Though I suppose the *emit* behavior is what we proposed changing at the design meeting. Still, I'm a little skeptical.

**Comment by mheiber** [comment]
Thanks @DanielRosenwasser , I'll close the issue since this was discussed already and I see the analogy with isolated modules

**Comment by DanielRosenwasser** [comment]
@mheiber I hope my comment didn't come off as "sorry, no, end of story", but more to convey my personal position. You're not the only one who's suggested it though.

**Comment by mheiber** [comment]
Ah, no worries. I closed because the explanation made sense to me. It sounds like it would be hard to justify strictness implying `--importsNotUsedAsValue: "error"` but not `isolatedModules`.
