### ISSUE TITLE
no error when constructor of subclass not assignable to base class 

### ISSUE THREAD

**Issue by chharvey** [microsoft/TypeScript#36151]
**TypeScript Version:**  3.7.2

**Search Terms:** constructor, subclass, error, assignable

# Summary
#7955 asks why a subclass with a different constructor is not assignable to the type of its parent class. The answer is, that’s by design. But the problem is there’s no error indicating that the subclass is not assignable to its superclass, until you actually try to assign it.

# Code
```ts
class WithConstructor {
  constructor(s: string) { s }
}
class SubWithConstructor extends WithConstructor {
  constructor(n: number) { super(`${n}`) } // no error here (not expected)
}
function testExample3(x: typeof WithConstructor): void {
  new x('hello') // send in string argument
}
testExample3(SubWithConstructor) // error (expected): argument is not assignable to parameter
```

# Expected behavior
There should be an error when `class SubWithConstructor extends WithConstructor` is declared, telling you that the constructors are not compatible.
> Expected error on subclass constructor: Type `new (n: number) => SubWithConstructor` is not assignable to type `new (s: string) => WithConstructor`.
> Types of parameters `n` and `s` are incompatible.
> Type `string` is not assignable to type `number`.

This expected behavior is consistent with regular methods. When a subclass has a method that is not assignable to the same in the parent class, we get an error.
```ts
class WithInstanceMethod {
  method(s: string): number { return +s }
}
class SubWithInstanceMethod extends WithInstanceMethod {
  method(n: number): string { return `${n}` } /* Error on the member (expected):
  > Property … is not assignable to same property in base type … */
}
function testExample1(x: typeof WithInstanceMethod): void {
  new x().method('hello'); // send in string argument
}
testExample1(SubWithInstanceMethod) // error (expected): argument is not assignable to parameter


class WithStaticMethod {
  static method(s: string): number { return +s }
}
class SubWithStaticMethod extends WithStaticMethod { /* Error on the class (expected, but not in the right place):
  > Class static side … incorrectly extends base class static side … */

  static method(n: number): string { return `${n}` } // the error should be on the method instead of on the entire class
}
function testExample2(x: typeof WithStaticMethod): void {
  x.method('hello') // send in string argument
}
testExample2(SubWithStaticMethod) // error (expected): argument is not assignable to parameter
```

# Actual behavior
There is no error until you actually try to assign `SubWithConstructor` to type `typeof WithConstructor`.

**[Playground](http://www.typescriptlang.org/play/?ssl=42&ssc=30&pln=42&pc=29#code/PQKgBAjAdGCiAeAHApgYwC7ICZgEbIAsBDANwEsB7AJwC4BYAKAHUDkA7MIjstgZ3S6pkYALbIR+KmAoAzTmF4BXXKgA2RXrzBktbCuk6ayAczZFcq4egqN0rBUTHa+AtkNHjJzsHeGIiVOwGahq8ADS29shUVNQKBBSKqjj40hx2RAZiEtEwIMCMIZpgTGR2AJIugsgAssh2FDgA3oxgHg1YABS8NAroVDzGAJS9bIo5Uk1ggeiKVBwA1FoAvoyrDEVaAMrKpRVVbrX1CTjI8JhsWFp7BJX81XUdYC0MbWIdnWyj45IjfQNsYzPab1OYcAAGABImmxluCwMswKA4DE4hR0vZsl5OmcUBhsCNWmAAAqxFBUdAATzAgDICbS6fSGXgmMwWKwUBxORBk6JU7y4DRWSkoWlgfJrRgyRRudCUdLIfgIRyISwQTrwXpUlCyEplW4HISPE5-EgUMjNIlsZAAdzA8E6Qyg7xOnQA5KxVKoKK6hgBuJHABTsHA8f6DThUYzjIIShiYRXwZWqzo7XA3O6uQ3HRpDANgaKxKQ4pBoTBYP4BKNiNgGHRgPQGUIs8yWHwc-xURz1aKMXsMRjIgBMMAQeLLeEIpEotEYLHY8ix0WkciICmUm0AmARae6y1AKc3COsNpnNtltyLCXhdjwTZc+ewdoJgTfbgS7-dYZARONRVFSXgJEkOBEKovAcqk6L3pkN6SHkBQbOoxQ3Fsb5kKgRqNM8RI7mh7Quj0YaAn8Yy3lMMxgmASwIrGmxgKmyGoeh2anOcwbXHqKGZGhGHNEi4CwH+aT3sItGfIyuKlgS9CvGAADCiGvlxe7Mp+oo8Kg1CBBgqjUmcFxXHggrPgpfRKR+wg0kSAAqv6FvS9aMpBvjLjIwbhouVBhHgigGE5UQ1mQgRrioClwdhjF4Y0nzfBMfz8ACQJkaC8xgFCMJwtRDDrFKMpyj4CroEqIgqsgg7qpqwrIDqDFKTxJpmhaMnwE6zFuh6Xo+nmvDBt48XhpW0Y1rG8aFYmxWWGV9EcYxdV5gWcTFmOUkRlWT5HoyTamC27JgB2XaYFQfZ9siADMI4lviKSTuQ1DSTZInovFigYGiK7BbRAGJMkE4nltZ7WBez6Pf0z3WFIOplFoj41sZoRhQhoS6nYsnA1QoNxC8bQaS4aMvVQ3S9H1RHAisNEmVNyOo+jUh6WxSMECjOPU1hMnY09ePRfWPzRLmUxKOSnRpbC4K5oiyJ6PmgmsEFYkGBJl25uKWUDuAAAiFAKg5WTIPU+YXeO+DEDdVBQIwo6SacgmQUoIWI2zIN470VmValVq2pzJG-GAAC8AB8dG7HqjPs2D4KMOtjZGH9rbWD4Lvgm7YAE4Rww+-7NzBw7oemwwSs5RgeUjUVJUneVcfanIGdU3j9XmizbSJ-a7rIJ63q5sAgbdZcvX9P1kaDegw0FcXlilxTDPV2D7eBvNRby2WFb99WtYMpHzLRzte3vD2DBAA)**

**Related Issues:** #7955

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Subclasses with different constructor signatures are extremely common and we'd be incorrectly rejecting a lot of valid code to error on this.

**Comment by chharvey** [comment]
@RyanCavanaugh Couldn’t the same be said for static methods though? One might want a subclass that has a static method with the same name as its parent, but with a different signature.
```ts
class Color {
  constructor(r: number, g: number, b: number) {
    /* construct a new Color from RGB components */
  }
  static fromComponents(h: number, s: number, l: number): Color {
    /* return a new Color from HSL components */
  }
}

class ColorAlpha { // ERROR
  constructor(r: number, g: number, b: number, a: number) { // apparently fine, but…
    /* construct a new ColorAlpha from RGBA components */
  }
  static fromComponents(h: number, s: number, l: number, a: number): ColorAlpha { // … invalid?
    /* return a new ColorAlpha from HSLA components */
  }
}
```
> Error: Class static side 'typeof ColorAlpha' incorrectly extends base class static side 'typeof Color'.

---

Side note, as mentioned in my OP, shouldn’t the error appear on the offending method, rather than on the entire class? When an instance method incorrectly overrides its parent, the error is on the method:

> Property … is not assignable to same property in base type …

But when a static method incorrectly overrides, the error appears on the class itself instead of on the overriding member.

**Comment by RyanCavanaugh** [comment]
We can really only guess when something will be used through indirection and needs to maintain a subtype relationship; for `static` methods this seems more plausible, but indirection of constructor functions is in practice rather rare (and is detected correctly).

**Comment by chharvey** [comment]
I see. So in other words we’re a lot less likely to find
```ts
function test(x: { new (): Object }) {
  new x()
}
```
in the wild than
```ts
function test(x: { staticMethod(): void }) {
  x.staticMethod()
}
```
which is why the latter is detected more strictly.
