### ISSUE TITLE
"Implement interface" codefix missing newline after first member

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#36171]
**TypeScript Version:**  3.7.3

**Search Terms:** implement interface codefix

**Code**

The "Implement interface" codefix fails to add a newline character after the first newly-added member when the class body is split across multiple lines:

![image](https://user-images.githubusercontent.com/3902892/72302077-be20e600-361d-11ea-9c6a-72331ceb4cdc.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/3902892/72302098-ce38c580-361d-11ea-94db-a0f4a12864d5.png)

**Comment by RyanCavanaugh** [comment]
#26550
