### ISSUE TITLE
User-defined type guard assignment check is backwards

### ISSUE THREAD

**Issue by lucaswoj** [microsoft/TypeScript#36189]
**TypeScript Version:**  Nightly as of 2020-01-14

**Search Terms:** user-defined type guards, type guards

**Code**

```ts
interface A {
    one: 1;
    two: 2;
}

interface B {
    one: 1;
}

function good(a: A): a is B {
    return true;
}

function bad(b: B): b is A {
    return false;
}
```

**Expected behavior:**

I expect `good` to compile without error because all instances of `A` are structurally compatible with `B`.

I expect `bad` to produce a compiler error because instances of `B` are not structurally compatible with `A`. 

**Actual behavior:**

`good` produces a compiler error and `bad` does not

```
A type predicate's type must be assignable to its parameter's type.
  Property 'two' is missing in type 'B' but required in type 'A'.(2677)
input.ts(3, 5): 'two' is declared here.
```

[Playground Link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200111&ssl=1&ssc=1&pln=13&pc=1#)

**Related Issues:** None found

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Guarding a type to a supertype of itself doesn't make any sense; it wouldn't *do* anything.

**Comment by lucaswoj** [comment]
> Guarding a type to a supertype of itself

Granted. What seems like a bug is that I cannot guard a type to a _subtype_ of itself. 

```tsx
interface FooOptions {
    type: 'foo';
    one: 1;
}

interface BarOptions {
    type: 'bar';
    two: 2;
}

type Options = FooOptions & BarOptions;

function isFooOptions(a: Options): a is FooOptions {
    return a.type === 'foo';
}
```

```
A type predicate's type must be assignable to its parameter's type.
  Type 'FooOptions' is not assignable to type 'Options'.
    Property 'two' is missing in type 'FooOptions' but required in type 'BarOptions'.(2677)
input.ts(8, 5): 'two' is declared here.
```

**Comment by RyanCavanaugh** [comment]
`FooOptions` is a supertype of `Options`, not a subtype. It seems extremely likely that you meant `type Options = FooOptions | BarOptions`, not `&`
