### ISSUE TITLE
Is it possible to configure baseUrl and still use relative path when doing autocomplete?

### ISSUE THREAD

**Issue by lgraziani2712** [microsoft/TypeScript#36181]
**TypeScript Version:**  3.7.4

**Search Terms:** baseUrl, autocomplete, relative path, lib, aliases, monorepo, sibling libs

**Code**

**tsconfig.json**

```json
{
  "compilerOptions": {
    // ...

    "baseUrl": ".",
    "paths": {
      "sibling-a/lib/*": ["../sibling-a/src/*"],
      "sibling-b/lib/*": ["../sibling-b/src/*"]
    },
  },
  "references": [{ "path": "../sibling-a" }, { "path": "../sibling-b" }]
}

```

**Expected behavior:** I have a monorepo with some libs and some of them uses code from sibling libs. I achieved three things I wanted: (1) to not need to build them just for TS to correctly check the imports (thanks to `baseUrl/paths` config), (2) to jump into the actual definition instead of the built file (also thanks to `baseUrl/paths`), (3) to TS understand the relationship between these libs (although I don't know if I configured everything correctly).

The thing is, since I'm using the `baseUrl` config, any module I try to import from within the same library, but at least two folders up above the actual module will use the alias. E.g.:

```ts
// ./packages/sibling-c/src/some/path/to/file.ts
// I try to import
// ./packages/siblin-c/src/some/anotherFile.ts
// And instead of VSCode offering me
import anotherFile from '../../anotherFile';
// It will suggest something like this:
import anotherFile from 'src/anotherFile';
```

The problem with the alias for files withing the same lib is exactly that: they are libraries, so what I build with TS is what I publish to my private repository manager. When some service import the file with the alises it will crash because it won't understand it.

Is correct what I'm configuring/want to have?

Thank you in advance!

**Comment by mezzab** [comment]
+1

**Comment by Ore4444** [comment]
i seond that. having the same issue

**Comment by andrewbranch** [comment]
You can suppress auto imports from using the relative path with a VS Code setting:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/3277153/89570226-bfdd1180-d7da-11ea-8771-a23b318ffc2e.png">

But TypeScript will still believe that `src/anotherFile` is valid. The proposal to “fix” this (it’s not actually a bug per se; my understanding is it used to be a feature designed for AMD modules and now that it’s being used differently by many people, certain aspects of the feature don’t make sense in the current context) is here: https://github.com/microsoft/TypeScript/issues/31869.

**Comment by lgraziani2712** [comment]
Uhmmm, you really cannot use the relative value in a monorepo project. If that relativity only worked up to the nearest tsconfig file, maybe, but it isn't feasible to use it if it adds an import of a sibling lib's module as a relative import.

**Comment by andrewbranch** [comment]
FWIW, monorepos with project references work really well with lerna and/or yarn workspaces, and don’t require path mappings / baseUrl that way. Out of curiosity, how do you test/run the projects in your monorepo? That is, during development, what mechanism makes `"sibling-a"` resolve to `../sibling-a`?
