### ISSUE TITLE
Attempted import error: `Enum` is not exported 

### ISSUE THREAD

**Issue by Rawnly** [microsoft/TypeScript#36184]
**TypeScript Version:**  `v3.7.3`

**Environment**:
```json
{
    "next": "^9.1.7",
    "typescript": "^3.7.4",
    "react": "^16.12.0"
}
```

**Search Terms:**
- exporting namespace broke
- exporing enum inside namespace
- import makes my module unavailable
- Attempted import error namespace

**Code**
```tsx
import { A } from '../types'

export default () => {
	console.log(A);

	return <h1>Ok</h1>;
};
```

My namespace declaration:
```ts
export namespace A {
	export const B = 'C';
	export enum C {
		D = 'E',
	}
}
```

**Expected behavior:**
I'd like to use my enum `C` inside my react component.

**Actual behavior:**
It crashes with the following message: 
`Attempted import error: 'A' is not exported from '../types'.`

**Related Issues:** #8004 ?

My **TSConfig**:
```json
	{
		"compilerOptions": {
			"target": "es5",
			"lib": ["dom", "dom.iterable", "esnext"],
			"allowJs": true,
			"skipLibCheck": true,
			"strict": false,
			"forceConsistentCasingInFileNames": true,
			"noEmit": true,
			"esModuleInterop": true,
			"module": "ESNext",
			"moduleResolution": "node",
			"resolveJsonModule": true,
			"isolatedModules": true,
			"jsx": "preserve",
			"baseUrl": ".",
			"typeRoots": ["./interfaces"],
			"paths": {
				...
			}
		},
		"exclude": ["node_modules"],
		"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
	}
```

**Comment by DanielRosenwasser** [comment]
Where are you getting that error from?

**Comment by DanielRosenwasser** [comment]
Additionally, what other tools are you using in your pipeline? I don't see any issues with TypeScript on my end. It sounds like you're reporting an error from an external build tool or a runtime, and maybe you need another build tool (like a bundler or loader) or you need to change your compiler settings (e.g. why is JSX preserve?)

**Comment by Rawnly** [comment]
> Could you provide some more information? e.g. where are you getting that error from?
<img width="1072" alt="immagine" src="https://user-images.githubusercontent.com/16429579/72478177-a5692980-37f1-11ea-8b06-03709543e4f2.png">

That's what I get.. the `tsconfig` file is auto-generated by NextJS. Any idea or solution?

**Comment by RyanCavanaugh** [comment]
We'd need a way to repro this without external build tools to be able to investigate. Most likely this is a bug in another component.
