### ISSUE TITLE
Conditional type guard throws error in map function

### ISSUE THREAD

**Issue by sundowndev** [microsoft/TypeScript#36186]
**TypeScript Version:**  3.7.4

**Search Terms:**
conditional type union check error

**Code**

```ts
type TOrigin = string | number;

const originId: TOrigin = '123';

if (typeof originId !== 'string') {
      throw Error(`Origin id must be string.`);
    }

const id: string = originId;

// Error:
// Argument of type 'string | number' is not assignable to parameter of type 'string'.
// Type 'number' is not assignable to type 'string'. ts(2345)
```

**Expected behavior:**
Typescript understands it can't be a number since I checked it.

**Actual behavior:**
TS throws an error

**Playground Link:** 

**Related Issues:** 
It might be duplicate but can't find anything relatable

**Comment by sundowndev** [comment]
To elaborate on the context, the error is coming in a map function.

```ts
type TOrigin = string | number;

const originId: TOrigin = '123';

if (typeof originId !== 'string') {
    throw Error(`Origin id must be string.`);
}

const id: string = originId; // pass

interface IObject {
    k: string;
}

const arr: IObject[] = [];
arr.map((i: IObject) => {
    i.k = originId // throws error
    return i;
})
```

**Comment by RyanCavanaugh** [comment]
Type guards from the surrounding context are not applied to function bodies because TS can't know when the function body will execute -- by the time the body does run, the type guard might not be true any more (this is the conservative assumption; while in some special cases it may be showable that the variable couldn't have changed, in general this is a correctly conservative take)

**Comment by sundowndev** [comment]
Alright, thank you for the explanation.

I managed to make it work simply by using another variable.

```ts
type TUnion = string | number;

const originId: TUnion = '123';

if (typeof originId !== 'string') {
    throw Error(`Origin id must be string.`);
}

const id: string = originId;

interface IObject {
    k: string;
}

const arr: IObject[] = [];
arr.map((i: IObject) => {
    i.k = id // pass
    return i;
})
```
