### ISSUE TITLE
Rename doc to docs or Documentation

### ISSUE THREAD

**Issue by jasonwilliams200OK** [Microsoft/TypeScript#3618]
The folder in source tree called `doc` is not consistent with other repos on GitHub.

IMO, it should either be `docs` (many repositories use this) or use `Documentation` (ASCII sort order) so it appear at the top in source tree (like https://github.com/torvalds/linux, https://github.com/dotnet/corefx/ and https://github.com/dotnet/coreclr/).

Also, please convert existing pdfs/docx to markdown and move wiki to documentation for keeping docs under unified source control (the same reason why core[clr/fx] folks moved).

**Comment by danquirk** [comment]
Changing to docs seems pretty innocuous if that's the convention.

The only pdfs/docx in \doc is the language spec which is also in there in Markdown (spec.md). We still find the other formats useful sometimes (ex Word's authoring tools/change tracking, PDFs for attaching to email).

The wiki content is currently in a separate repo per prior suggestions: https://github.com/Microsoft/TypeScript-wiki. Moving it under \docs puts it in a singular place but doesn't actually make the editing/PR workflow much better does it?

**Comment by mhegazy** [comment]
feel free to send a PR for this. you will need to make sure that `jake generate-spec` is still working correctly.

**Comment by jasonwilliams200OK** [comment]
@danquirk, thanks for your input.

> Moving it under \docs puts it in a singular place but doesn't actually make the editing/PR workflow much better does it?

One of the ideas of having docs in the source-control is to encourage contributors to keep the docs in sync with code changes. This way the commit history keeps track of code changes + docs + PRs. Having a separate repository is a good idea (I wasn't aware of Typescript-wiki repository), but the most popular workflow is to keep the docs within the source-control.

@mhegazy, thanks, will do. :)

**Comment by danquirk** [comment]
Makes sense. @DanielRosenwasser has been the main one managing the syncing of the two repos so he might feel opinionated one way or the other. Mostly we were just holding out hope for GitHub to actually support editing repo wikis in a good way.

**Comment by DanielRosenwasser** [comment]
I don't think there's a standard - for instance, Rust uses "doc" as well. I'm not seeing a strong benefit of a rename, but I'm not that strongly opinionated on it.

I understand the desire to have wiki pages in the `doc`/`docs` directory; however, I personally don't want to conflate wiki history with TypeScript history. Others on the team may feel differently, and if so, I encourage them to voice their input.

The editing/PR workflow would be more difficult. I'm not sure how I could make this work unless we added a git repo into our repo. Not the worst idea, but probably confusing for most people.

I think it would be a good idea if we had `doc/wiki/README.md` which pointed to both our actual wiki (https:///github.com/Microsoft/TypeScript/wiki) and the PR-able wiki (https:///github.com/Microsoft/TypeScript-wiki).

**Comment by mhegazy** [comment]
Does not seem to be a consensuses here. closing.
