### ISSUE TITLE
Duplicate types are allowed (and ignored) if the first type is exported

### ISSUE THREAD

**Issue by fefrei** [microsoft/TypeScript#36196]
**TypeScript Version:**  3.7.2

**Search Terms:** duplicate type identifier export ignored allowed

**Code**

```ts
export type A = 1;
type A = 2;
const x1: A = 1;
```

**Expected behavior:** I think this should not be allowed: I'm defining a duplicate type, the first of which is exported. Still, it's a duplicate.

**Actual behavior:** This is actually allowed, and the second definition is completely ignored. (Note that any other arrangement of `export` keywords cannot make the program correct, only this works.)

**Playground Link:** http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcCCcC8cCMBuAKCRXSzgCZCBjCAOwGd4QcAuU7fAoA

**Related Issues:** I did not find any.

(Sorry if this is a duplicate. It feels too simple to not be one, but I didn't find it.)

**Comment by andrewbranch** [comment]
Notable that if you reverse the order of the exported one and the local one, you get an error 😳
