### ISSUE TITLE
React & Webpack docs incorrect

### ISSUE THREAD

**Issue by stusherwin** [microsoft/TypeScript#36197]
Documentation about [React & Webpack](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html) is incorrect, it specifies `resolve.extensions`:

```
    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: [".ts", ".tsx"]
    },
```

This works for webpack, but it fails when using webpack-dev-server as this uses more extensions such as `wasm`, `json`, `js`, and it's not obvious what the problem is when it suddenly stops working. Have a look at [this issue on webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues/2393) for more information.

**Comment by RyanCavanaugh** [comment]
Documenting third-party tools was a mistake 😞

**Comment by orta** [comment]
This is fixed in the new website with https://github.com/microsoft/TypeScript-Website/pull/700
