### ISSUE TITLE
Unexpected type for Generator

### ISSUE THREAD

**Issue by flibustier7seas** [microsoft/TypeScript#36192]
**TypeScript Version:**  3.7.2

**Search Terms:**

**Expected behavior:**
```ts
let barGenerator: Generator<any, string, { name: string; } | { age: number; }>;
```

**Actual behavior:**

```ts
let barGenerator: Generator<any, string, { name: string; } & { age: number; }>;
```

**Related Issues:**

**Code**
```ts
function* Bar() {
  let x: { name: string } = yield;
  let y: { age: number } = yield;

  return x.name + y.age;
}

let barGenerator = Bar();
// let barGenerator: Generator<any, string, { name: string; } & { age: number; }>;

let barResult = barGenerator.next();

barResult = barGenerator.next({ name: "Bar" }); // Error: Argument of type '[{ name: string; }]' is not assignable to parameter of type '[] | [{ name: string; } & { age: number; }]'.
barResult = barGenerator.next({ age: 40 });

console.log(barResult);

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function* Bar() {
    let x = yield;
    let y = yield;
    return x.name + y.age;
}
let barGenerator = Bar();
//let barGenerator: Generator<any, string, { name: string; } & { age: number; }>
let barResult = barGenerator.next();
// Error: Argument of type '[{ name: string; }]' is not assignable to parameter of type '[] | [{ name: string; } & { age: number; }]'.
barResult = barGenerator.next({ name: "Bar" });
barResult = barGenerator.next({ age: 40 });
console.log(barResult);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mAVAAgEIEMBOAKAlMgbwFgAoZZAGwFMpkAPALkOTHQFsqmBnKTGMAObIAvsgC8yAJ4wqFACYBuUuWq1JTAsnQDOLEGwBGVTCPFSZ8pSWXJMNEJjD0AdKw7IA1FOfaqV4aSkqsgGWADiVGDG6FBwJhIYOLhWAPQpwaGYEVGYMXFM2dGxmAA86GCSADTIPHyC1ZpuurX8AgqmAGTMvkxg+kaY7cIAfIEkGVgASlRcIBS0EpmFucWuVHRQeKkpyACimJj5yACCmAL6kbRwwMhQkgAOVMgA5ADajezNvK1DALrPyBgXBYcFo6C4XBgAlYBmotzgyHuWE+UGMyGutweTzev2QAB9kO8WJ9uN9BENkF1ND09IZjH9ns4xplprN5mYlpEinE1htsB8OEwAESJIUiZKkFkzOYLELhLkrHlRPnUnRMAAsAAZxVZSBAEFw4NRnBQ4AJsFK2VAJSQgA)

**Comment by IllusionMH** [comment]
Only type that has both `name` and `age` can be assigned to both `x` and `y`.
See [example](https://www.typescriptlang.org/play/index.html?ssl=7&ssc=52&pln=7&pc=53#code/CYUwxgNghgTiAEYD2A7AzgF3gVxQS1QDUoJsQAueAb3hSgFsL5MY8UBzAbngF94AfavCjsmKbPQBGIGNx6cAUAoggsAD2yUadRpRZt2veAF4c+IiTKKVWAJ6ahIsROkwjp3ARTFSIRUtBIWARkdCw2DBk0cAwvHzItWgYmfQ45eAAyR1FKcSkZOX8beDU8RJ0UjFYOd3gIqJi4yz9lVXhbMuznfLc+U3qYaLBYi19OIA)
Only intersection satisfy both constraints, where union would allow

```ts
let barResult = barGenerator.next();

barResult = barGenerator.next({ name: "Bar" });
barResult = barGenerator.next({ name: "Bar" }); // allowed by union, but not assignable to { age: number }
```

**Comment by flibustier7seas** [comment]
> Only type that has both `name` and `age` can be assigned to both `x` and `y`.
> See [example](https://www.typescriptlang.org/play/index.html?ssl=7&ssc=52&pln=7&pc=53#code/CYUwxgNghgTiAEYD2A7AzgF3gVxQS1QDUoJsQAueAb3hSgFsL5MY8UBzAbngF94AfavCjsmKbPQBGIGNx6cAUAoggsAD2yUadRpRZt2veAF4c+IiTKKVWAJ6ahIsROkwjp3ARTFSIRUtBIWARkdCw2DBk0cAwvHzItWgYmfQ45eAAyR1FKcSkZOX8beDU8RJ0UjFYOd3gIqJi4yz9lVXhbMuznfLc+U3qYaLBYi19OIA)
> Only intersection satisfy both constraints but union would lead to a problem
> 
> ```ts
> let barResult = barGenerator.next();
> 
> barResult = barGenerator.next({ name: "Bar" });
> barResult = barGenerator.next({ name: "Bar" }); // allowed by union, but not assignable to { age: number }
> ```

If `x` has type `string` and `y` has type `number`, then intersection will be `never`.  And so, I can't use the generator at all.

```ts
function* Foo() {
  let x: string = yield;
  let y: number = yield;

  return x + y;
}

let fooGenerator = Foo();
// let fooGenerator: Generator<undefined, string, never>

let fooResult = fooGenerator.next();

fooResult = fooGenerator.next("Foo"); // Error: Argument of type '["Foo"]' is not assignable to parameter of type '[] | [never]'
fooResult = fooGenerator.next(age);

console.log(fooResult);
```

**Comment by IllusionMH** [comment]
IMHO statically typing `yield` is impossible as soon as you start using different input types because TS can't enforce types order in general case.

In this case you can't rely on inferred type and need to add explicit annotation. It can be `Generator<undefined, string, any>` or more involved [`Generator<undefined, string, string | number>` and type assertions](https://www.typescriptlang.org/play/?ssl=1&ssc=18&pln=1&pc=63#code/GYVwdgxgLglg9mAVAAgEIEMBOAKAlALmQHEBTMEzdKOTAHnABMTgZyGAaZAZyk1YHNOPPmH7IAPsjAgAtgCMKAPmQBvALAAoZMgA2JKMgAehYQO0BeZNgCeMEjoa5k6Lt14CA3Ju16D1wtLyFMiWNnYOTi5SsgqYXhreyJj6IJhgRsgA1MjW8QC+mpq+yHJYpOSU1JghaFh48QD0DcWlmOUUVDSE7ZU0tOhg1kLuopwqUugyJCYj-B7IecgAZKrO-NPRQXELioUaLVgASiRcIDoGlq09nZgAdOSGUPWaTcgAopiYXcgAgpj8sjIBjgwGQUGsAAcSMgAOQAbXGYEmG1MonmeQAujDkDBXGA4AYXFwYPwkXI9GC4MgIVhkVBgiCwZDofCMRJkAiJlMZiI5gtlqt0OsAjEKOisbc9q1jqdzjUrmQOlV7iRHtgAEQYTDq3DxaUnM4XEplRW9O4PJ4AFgADLq9hAEFw4Hpbjo4PxsPrZVA7RogA)

But this will be your responsibility to math expected and passed types at runtime.
