### ISSUE TITLE
HTMLVideoElement is missing 'playsinline' attribute

### ISSUE THREAD

**Issue by timmydoza** [microsoft/TypeScript#36204]
**TypeScript Version:**  3.8.0

**Search Terms:**
HTMLVideo, HTMLVideoElement, playsinline 
**Code**

```ts
const el = document.createElement('video');
el.playsinline = true; // Property 'playsinline' does not exist on type 'HTMLVideoElement'.
```

**Expected behavior:**

There should not be a TS error.  `playsinline` is a boolean attribute that exists on the `<video>` element per https://html.spec.whatwg.org/multipage/media.html#htmlvideoelement

**Actual behavior:**

There is a TS error: `Property 'playsinline' does not exist on type 'HTMLVideoElement'.`

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=2&ssc=92&pln=1&pc=1#code/MYewdgzgLgBApgGxgXhgExMArgWzmKAOmACc4BDKOAUQTjwIAoByANwEs04RmBKAbgCwAKESEADgnIBPCOzAJ5cFDCgkscfjAD02mAAUSIcXBJRpMZpJlyFS5uhBwIMMCFhwAHu2gxwq6RNLAAkAFQBZABkANU5uWnp8KGZCIA

**Related Issues:** 
None.

**Comment by pmer** [comment]
While the attribute is called playsinline, it is exposed as playsInline (capitalized "i") in the DOM.

https://html.spec.whatwg.org/multipage/media.html#the-video-element

**Comment by lsqy** [comment]
I had the same problem too～

**Comment by atnpcg** [comment]
yeah, remember that typescript uses cammelcase
like: autoplay should be autoPlay
and playsinline should be playsInline

**Comment by yukitaka13-1110** [comment]
Any progress?

**Comment by pushkar8723** [comment]
I faced the same issue even the attribute used was `playsInline`. I updated the typescript version. That fixed it.

**Comment by pmer** [comment]
Can this issue be closed?

**Comment by krishnamhn009** [comment]
> I faced the same issue even the attribute used was `playsInline`. I updated the typescript version. That fixed it.

which version are you using?

**Comment by pushkar8723** [comment]
@krishnamhn009 4.2.2

https://github.com/ente-io/bada-frame/blob/76ee1517d3cd39b37cab0578a5027f0b2b2e5627/yarn.lock#L7479
