### ISSUE TITLE
Add FormDataEvent

### ISSUE THREAD

**Issue by naokikimura** [microsoft/TypeScript#36217]
**TypeScript Version:**  Nightly

**Search Terms:**

- FormDataEvent 
- HTMLFormElement: formdata event
- GlobalEventHandlers.onformdata

**Expected behavior:**

No errors. Behave as specified by WHATWG.
- https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#the-formdataevent-interface

**Actual behavior:**

Error `Cannot find name 'FormDataEvent'.(2304)`

**Related Issues:**

**Code**
```ts
let e: FormDataEvent;
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
let e;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200115&ssl=3&ssc=1&pln=1&pc=1#)

**Comment by adriengibrat** [comment]
```ts
interface FormDataEvent extends Event {
    readonly formData: FormData;
}
interface FormDataEventInit extends EventInit {
    formData: FormData;
};
declare var FormDataEvent: {
    prototype: FormDataEvent;
    new(type: string, eventInitDict?: FormDataEventInit): FormDataEvent;
};
```

**Comment by meidlinga** [comment]
Hello,

is there any ETA for this issue?

**Comment by jakebailey** [comment]
This was pulled into main in #44684, so is present in TS 4.4 and above. [Playground Link](https://www.typescriptlang.org/play?ts=4.4.4#code/DYUwLgBCBcEGIHsBOBbAIgQzBgogNxADswBuIA)
