### ISSUE TITLE
Offer completions in export lists

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#36213]
## Search Terms

completion, export, exports

## Suggestion

Offer in-scope symbol names when completion is invoked within an export list `export { /*here*/ }`.  Presently, the server returns `"success":false,"message":"No content available."` for both `completionInfo` (VS Code) and `completions-full` (VS).

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by amcasey** [comment]
Repro:

```ts
function MyFunction() { }
export { MyF/*ctrl-space*/ }
```

**Comment by DanielRosenwasser** [comment]
Probably important to make sure that this doesn't affect the

```ts
export { /**/ } from "module";
```

case

**Comment by DanielRosenwasser** [comment]
Yeah, just make sure the current file's locals don't suddenly appear.
