### ISSUE TITLE
Type inference with reduce functions

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#36225]
Type of array elements shouldn't affect type inference in this case.

**TypeScript Version:**  3.7.x-dev.20200115

**Search Terms:**

**Code**

```ts
([] as any[]).reduce(() => 0, 0); // any
([] as unknown[]).reduce(() => 0, 0); // unknown
([] as never[]).reduce(() => 0, 0); // number
```

**Expected behavior:**

```ts
([] as any[]).reduce(() => 0, 0); // number
([] as unknown[]).reduce(() => 0, 0); // number
([] as never[]).reduce(() => 0, 0); // never or number
```

**Actual behavior:**

```ts
([] as any[]).reduce(() => 0, 0); // any
([] as unknown[]).reduce(() => 0, 0); // unknown
([] as never[]).reduce(() => 0, 0); // number
```

**Playground Link:** https://www.typescriptlang.org/play/?target=99&ts=3.8.0-dev.20200115&ssl=1&ssc=1&pln=3&pc=46#code/BQbQugBAhgztB2BPcBKAdAJwKYBMCuAxlsMChALwB8EADADS0oDcEA9KwogFCiSwR54Aa3gB7AO7xUmXIWKkK1eoxbsBwsZJ7hoceFgBuWDNOz4iJMlVoMazNh3h4AtgCNjQA

**Related Issues:** #25454

**Comment by RyanCavanaugh** [comment]
Please add to our suite at #36554
