### ISSUE TITLE
Element access with non-literal constant key should be narrowable

### ISSUE THREAD

**Issue by thany** [microsoft/TypeScript#36230]
**TypeScript Version:**  3.7.4 (also tried vNightly on the playground)

**Search Terms:** exhaustive type check array

**Code**

Error ts2532:
```ts
type Progress = Array<number | undefined> | undefined;

const progress: Progress = [1, 2, 3];
const index = 1;

if (progress !== undefined && progress[index] !== undefined && progress[index] >= 0) {
  // Do something
}
```

Workaround, but undesirable:
```ts
type Progress = Array<number | undefined> | undefined;

const progress: Progress = [1, 2, 3];
const index = 1;

if (progress !== undefined)
  const p = progress[index];
  if (p !== undefined && p >= 0) {
    // Do something
  }
}
```

**Expected behavior:**
The exhaustive type checking mechanism in Typescript should know that neither `progress` nor `progress[index]` are undefined inside the if statement, because I'm doing an explicit check for that.

**Actual behavior:**
On `progress[index] >= 0` you'll get ts2532: _Object is possibly 'undefined'_

**[Playground Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200115&ssl=1&ssc=1&pln=8&pc=2#code/C4TwDgpgBACgTgewOZwgZzVAvFAgnOAQxAB4A7AVwFsAjCOKAHygrIBMIAzASzIjYB8TFuy69+AbgBQUgMYIyaYFDCIU6NAC5Ya1BmxQA2gEYANFABM5gMwBdafMXLeHAB4Hj0qd05QAFKrIepgAhFg4rBw8fGxQAGRxKroahi4QrrZQYRGi0fzxiYHqGKmiGVACOAAMAJRQAN5SUFAA9C1QACIIUGgIVBDAABa8SFIAvkA)** 

**Related Issues:** 
In #34661 the workaround seemed to be to use an intermediate variable, which will fix my code as well, while also making it more hairy.

**Comment by andrewbranch** [comment]
If I recall correctly, @sandersn implemented control flow like this for literal element access, so at first glance it seems like it could be expanded to _constant_ element access, but I’m not an expert in this area.

**Comment by thany** [comment]
Me neither 😀
Literal element access is probably the right keyword. Because if `index` were a function and I'd be doing `progress[index()]` (hence it wouldn't be *literal* element access anymore) the error would be completely correct and understandable. TS wouldn't be able to know (with confidence) if the function returns the same result every time. But as for a constant value, that's fully predictable, if I understand `const` correctly.

**Comment by sandersn** [comment]
I recall the cost of control flow analysis being much higher since there are many more index accesses with variables than with constants. But I could be wrong. It's worth making an experimental PR to see what the performance cost is.

**Comment by DanielRosenwasser** [comment]
Didn't we talk about this at https://github.com/microsoft/TypeScript/issues/32357 and https://github.com/microsoft/TypeScript/pull/31478 ?

**Comment by sandersn** [comment]
Yes: 

> Inserting flow nodes only for element accesses with literal access expressions was a performance decision from quite some time ago. As far as I know, we have no reason to revisit that decision.

I made that decision two years ago, so maybe something has changed since then. It's more likely that I was simply wrong and the performance hit is small, or worth it to get this feature.

**Comment by tadhgmister** [comment]
A particularly compelling case of this is when using `const enum` properties for discriminated union.  Using the same property from the declaration doesn't narrow the type but the number literal does, even though both emit identical javascript code ([Playground Link](https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBApmArgWxgDQN4wNZwJ4wC+AsAFBkCWYUcATgGYCGwcMAgjFgNpoB0ueALoAuGACI2YgNwwAJoyiMA+o1FJkAIzpFK1OkxYwAQpxg9++EeKPS5C5RrUottHaSo0GzVgGFT5gSsxH1t5RSVgJ01tEnJSekQwYCgKcBgAczgoABF7JQB1AEkAFQAJJR8AeQA5AGVipQAxACVKgFklbIBRHwAZNma2YsKagAooAAsqdNEOAB9jGAWfAEpOMhhNmAgAdwooYAmYcamwdIDLNawAemu5EDgIMAByWB2QWmwNrZ-gRghWBIxKJaFlELQwDBJtNeGFlIwpN8fps-gDrMCYKCoODIdCzrC8hpEaRkVtUYCQiCwRCoad0gTwsBiT9YrEEkkUmlMjk8kUykpeiUuoNeidprMlotllckds9gcjmKzlwAAyCK4wW4wd6fCAwegfGDgAA2BGgtGmRtc6hcMGN+zojGNEFlv3+gMkVOxNLx9LhKmZpJg5PRXpxtJh-qJrrJ7vElMx1NxdIZyiZstZQA))

```ts
const enum X{ key }

interface A { [X.key]: "A"; data_a: number }
interface B { [X.key]: "B"; data_b: number }
interface C { [X.key]: "C"; data_c: number }

 // doesn't work
function getData_WITH_CONST_FROM_DECLARATION(thing: A | B | C) {
    switch (thing[X.key]) {
        case "A": return thing.data_a;
        case "B": return thing.data_b;
        case "C": return thing.data_c;
    }
}

 // works for only string or number literals
function getData_WITH_LITERAL(thing: A | B | C) {
    switch (thing[0]) {
        case "A": return thing.data_a;
        case "B": return thing.data_b;
        case "C": return thing.data_c;
    }
}
```

**Comment by joshkel** [comment]
If I'm understanding correctly, the inability to narrow using constant keys is also a significant limitation of symbol properties. [These](https://github.com/microsoft/TypeScript/issues/1863#issuecomment-574852520) [comments](https://github.com/microsoft/TypeScript/issues/1863#issuecomment-574538121) from #1863 suggest that using symbols as properties is fully supported, but code such as the following doesn't work:

```typescript
const Parent: unique symbol = Symbol('Parent');
const Name: unique symbol = Symbol('Name');

interface GenericGroup {
    [Name]?: string;
}
interface Company extends GenericGroup {
}
interface Division extends GenericGroup {
    [Parent]?: Company;
}
interface Team extends GenericGroup {
    [Parent]?: Division;
}
type Group = Company | Division | Team;

function getName(group: GenericGroup): string {
    if (group[Name] == null) {
        return '';
    }
    // Error - "Type 'string | undefined' is not assignable to type 'string'"
    return group[Name];
}

function getParentName(group: Group): string | undefined {
    if (!(Parent in group)) {
        return undefined;
    }
    // Error - "Element implicitly has an 'any' type because expression of type 
    // 'unique symbol' can't be used to index type 'Group'."
    return group[Parent]?.[Name];
}
```

**Comment by lazytype** [comment]
Should the following behavior fall under the current issue or should it be its own?:

```typescript
const record: Record<string, number | string> = {};

const key = 4;
const constKey = 4 as const;

let stringValue: string;

record[4] = 'hello';
stringValue = record[4];

// @ts-expect-error - should be error because checker doesn't know what `key` is specifically
record[key] = 'hello';
stringValue = record[key];

record[constKey] = 'hello';
// Proposal: allow `record[constKey]` to be narrowed since `constKey` is a `const` key
stringValue = record[constKey];

// Bonus: hopefully implementing above would make the following work for free
if (key === 4) {
    record[key] = 'hello';
    stringValue = record[key];
}
```

[Playground](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200328#code/MYewdgzgLgBATgU1HAJgLhgJSSVAeaOASzAHMAaGMAVwFsAjBOGAHxkJNID4YBeGAN4BfANwAoMaEiwA1ggCefGABZxU6DHVQA0gqXKYAQwibw0cWIA2CWBzIA1Q5eoIMd0hcTIUAbWUBdJQByAAsES0sQIPF3R2cEJS9cXwCLAHo0mAABKAgAWgQADwAHJCgCuDhcGDz2EJBqSxQYRhgmKuZGYENqCATgMOA5ZhQQBAgwINkwEAB3GFmQw1gAAzl5FZgiEwhS4CIAMyJuiPkxJNQfdcD+UPDI6LFYpxdEnEvrz3ffLV15G5gdwiUXEGRgAAUqsUQBAnBgnJF5isLj8zDoFP5NlAQC0EmBDJU5ghmhASMAEitfgpNtsjDBKWjNusnlBiA4Xgl+CifFT-ulMgAhcC9DD1UoHRqWRREWjFay0BBgKCcIz0EAANwSswaTRgtEMchgUDCMAOIGBsxV2rgMlN1QOiAQYkOMAAFOs+Lx+MoAJSCMQwQPwb5XDHBMLAx5B9iszhxV5ckOfMRCIA)

**Comment by sandersn** [comment]
@lazytype it's the same; `const index = 1` from the OP behaves the same as your `const constKey = 4 as const` in this case.

**Comment by mbroadst** [comment]
Hi, I think I'm running into this bug please let me know if I should post elsewhere:
```
const kSymbol = Symbol('foo');
class WithSymbol {
  [kSymbol]?: number[];
}

function takesWithSymbol(foo: WithSymbol) {
  if (foo[kSymbol] && foo[kSymbol].length) {  // Object is possibly `undefined` ts(2532)
  }  
}
```

Curiously if the member variable is a primitive type this works just fine:
```
const kSymbol = Symbol('foo');
class WithSymbol {
  [kSymbol]?: number;
}

function takesWithSymbol(foo: WithSymbol) {
  if (foo[kSymbol] && foo[kSymbol] === 4) {  // works fine
  }  
}
```

**Comment by andrewbranch** [comment]
Yep, that’s this. The second example works because you’re always allowed to compare `foo[kSymbol]` for equality even if it might be undefined.

**Comment by tadhgmister** [comment]
@mbroadst yes that is the same issue, and `foo[kSymbol] === 4` is still a valid statement if `foo[kSymbol]` is undefined so there is no type error, trying to do `foo[kSymbol] === []` for array or `foo[kSymbol].toFixed()` for a number shows it.
