### ISSUE TITLE
Improve message for "Remove declaration for: ..."

### ISSUE THREAD

**Issue by zoechi** [microsoft/TypeScript#36231]
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

"Remove **unused** declaration for: " would it make much clearer why one gets the suggestion to remove this code. 
I don't know if this message is shown for other cases except "unknown".

**Comment by DanielRosenwasser** [comment]
Feel free to send a PR!

1. Update `diagnosticMessages.json`
2. Fix generated uses of `Remove_declaration_for_0`
3. Update test baselines `npx gulp runtests-parallel; npx gulp baseline-accept`.
4. Update any failing tests in `tests/fourslash`

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
