### ISSUE TITLE
Unclosed object binding patterns do not give correct completions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3623]
Now that #3615 is in, here's an annoying one for editors without brace completion:

```TypeScript
interface Thing {
    abcdef: any;
}

interface I {
    property1: Thing;
    property2: string;
}
var foo: I;
var { property1: { /**/ } = foo;
```

Expected: `abcdef` is in the completion list.
Actual: `property1` and `property2` are in the completion list.

**Comment by mhegazy** [comment]
This is a hard one to get right just because of the grammar.

**Comment by DanielRosenwasser** [comment]
Right - this shouldn't be a bug. I forgot that an initializer is valid on a nested binding pattern.
