### ISSUE TITLE
No  incremental autocomplete options for private fields

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript#36234]
**TypeScript Version:**  Nightly - 3.8.0-dev.20200115

**Search Terms:**autocomplete private fields

**Expected behavior:** The following would autocomplete with all available private fields on the class

```ts
console.log(`Welcome, ${this.#| }`);
```

**Actual behavior:** It's an empty completion list

**Related Issues:** N/a

**Code**
```ts
class Person {
    #firstName: string

    constructor(firstName: string) {
        this.#firstName = firstName;
    }

    greet() {
        // Expected: when you write # after the dot below you get #firstName ✓
        // console.log(`Welcome, ${this.}`);

        // Bug: when you write f after the # below you don't get #firstName as an option ❌
        // console.log(`Welcome, ${this.#}`);
    }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, privateMap, value) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to set private field on non-instance");
    }
    privateMap.set(receiver, value);
    return value;
};
var _firstName;
class Person {
    constructor(firstName) {
        _firstName.set(this, void 0);
        __classPrivateFieldSet(this, _firstName, firstName);
    }
    greet() {
        // Expected: when you write # after the dot below you get #firstName ✓
        // console.log(`Welcome, ${this.}`);
        // Bug: when you write f after the # below you don't get #firstName as an option ❌
        // console.log(`Welcome, ${this.#}`);
    }
}
_firstName = new WeakMap();

```
</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200115&ssl=1&ssc=1&pln=15&pc=2#code/MYGwhgzhAEAKCmAnCB7AdtA3gKGn6AxAGYCWyALgHJgC28AXNBOYiWgOba77DrOIBXYORSIAFKQrU6jfm3YBKLN3z5yACxIQAdMTLNp8aAF5okg7XgBuFdAC+XVe0Tx45MUpyrVAeh-QAUQAPAAd4YXgAE0YAd3V4DABPFAFoGNZyIwJoMCJMxGgNI0iUcmgAI3gQFBjoZNT2N0JzKktoQGRyW19-XjRUEHhtavYxAAMAdSreOgAaaAASTA0tbTtRhRsu-D9oACEBdlj4pJS0jKMiHLykQvjCCqqautOStAByMsayvSk2yByMCgQuQSOhoIAZci2eB2vX6g2GY0mIGm8Dmi2WOgIaw2tgcdiAA)

**Comment by andrewbranch** [comment]
> Expected: when you write # after the dot below you get #firstName ✓

This part actually doesn’t work for me. Not 100% sure but it might require a change on the VS Code side... that was the case on triggering string literal completions starting with a backtick.

> Bug: when you write f after the # below you don't get #firstName as an option ❌

This was fixed yesterday in https://github.com/microsoft/TypeScript/pull/36191

**Comment by DanielRosenwasser** [comment]
This is a change that has to happen in the client side to trigger completions when `#` is typed in (cc @mjbvz and @minestarks). But at the same time, if I recall correctly, @mjbvz was interested in having TSServer provide a list of completion trigger characters so that we'd be in control of this.

**Comment by DanielRosenwasser** [comment]
I can't speak to that as well yet (unfamiliar with how completions work there), so yes please.

**Comment by minestarks** [comment]
@mjbvz @DanielRosenwasser in VS, this is less about `#` being a trigger character per se, more about `#` being a valid first character in an identifier. I love the idea of tsserver returning a list of trigger characters, but at least in VS, triggering is very context-dependent so I'm not sure how we'd be able to convey that information in the protocol.

Context: https://devdiv.visualstudio.com/DevDiv/_git/TypeScript-VS?path=%2FVS%2FLanguageService%2FTypeScriptLanguageService%2FShared%2FFeatures%2FCompletion%2FCompletionUtilities.cs&version=GBmaster&line=41&lineEnd=42&lineStartColumn=1&lineEndColumn=1&lineStyle=plain

**Comment by DanielRosenwasser** [comment]
From what I gather from Matt's side, I think the protocol already has `CompletionsTriggerCharacter` or something like that. We could see if the containing context is a `class` and provide no completions if the trigger character is `#`.

**Comment by minestarks** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_queries/query/5344e075-72f0-4bd3-af49-c7dddb3c62e9/ to track this for VS and assigned to @uniqueiniquity  - it's not clear to me at this point what changes need to happen to get this to work
