### ISSUE TITLE
Triple-slash references duplicated in .d.ts with printer.printFile

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#36242]
Compare https://github.com/sandersn/downlevel-dts/blob/0eb977fcbdbd16f5e738a046c8c3d9c59537b5dd/test/test.d.ts#L1 to
 https://github.com/sandersn/downlevel-dts/blob/0eb977fcbdbd16f5e738a046c8c3d9c59537b5dd/baselines/ts3.4/test.d.ts#L1

The code that produces this erroneous output is pretty simple:

https://github.com/sandersn/downlevel-dts/blob/0eb977fcbdbd16f5e738a046c8c3d9c59537b5dd/index.js#L132

Here's a simplified version:

```js
  const program = ts.createProgram(['./test.d.ts'], {});
  const files = program.getRootFileNames().map(program.getSourceFile);
  const printer = ts.createPrinter({
    newLine: ts.NewLineKind.CarriageReturnLineFeed
  });
  for (const f of files) {
    console.log(printer.printFile(f));
  }
```

Create `test.d.ts` with the following text:

```
/// <reference types="node" />
/// <reference path="./src/test.d.ts" />
```

I also tested with multiple triple-slash references; in that case, all references are duplicated.

**Comment by sandersn** [comment]
Interestingly, this:

```ts
/// <reference types="node" />
/// <reference path="./src/test.d.ts" />
```

is duplicated as this:

```ts
/// <reference path="./src/test.d.ts" />
/// <reference types="node" />
/// <reference types="node" />
/// <reference path="./src/test.d.ts" />
```

So I think the first two lines are the triple-slash references after sorting etc, and the second two lines are the original comments.

**Comment by SkeLLLa** [comment]
I think this has the same root cause https://github.com/microsoft/TypeScript/issues/33950

**Comment by sandersn** [comment]
1. Store leading comments.
2. write reference path directives (`./src/test.d.ts`)
3. write reference type directories (`node`)
4. Write trailing comments, using emitLeadingComments. This seems wrong.

Doesn't repro with just ts.createSourceFile.

**Comment by sandersn** [comment]
From investigating with @rbuckton: declaration files emit all the references, then all the comments as written. That's because we assume that all triple-slash references in declaration files are generated -- in other words, that there weren't any there in the source. @rbuckton is going to make a PR so we can make sure it doesn't break anything else.
