### ISSUE TITLE
TypeScript server won't start on WSL

### ISSUE THREAD

**Issue by alexpaluzzi** [microsoft/TypeScript#36243]
Issue Type: <b>Bug</b>

Open a large repo and then open any .js or .ts file. No intellisense.

All extensions (except WSL remote) disabled. Tried with latest TS. It DOES work if the project files are not in WSL2. Possibly related to Remote - WSL extension?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|25.01GB (2.04GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.41.7
prettier-vscode|esb|3.18.0
vscode-typescript-next|ms-|3.8.20200115

</details>

**Comment by mjbvz** [comment]
Seems like https://github.com/microsoft/TypeScript/issues/33335

**Comment by alexpaluzzi** [comment]
Possibly-- but it just started recently. And I DO have the files in the native WSL2 system (where they are recommended to go and things are generally blazing fast from there).

I really would like to exclude all `node_modules` folders from any kind of consideration here. There are probably 500+ `node_modules` folders in this project that I have open.

**Comment by alexpaluzzi** [comment]
@mjbvz even trying to completely disable the filewatcher.

![image](https://user-images.githubusercontent.com/1376892/72569248-f297da80-3887-11ea-870a-908e3d77e2c8.png)

This `Vmmem` process is taking almost all of my memory (!!28GB+) and about ~40-50% CPU until I start getting errors. Even after the errors come, the CPU usage drops to about 10% but it doesn't let go of the memory (even after closing Code). The CPU drops to ~0% after I close it, though.

It doesn't let go of the whopping 28GB of memory until I literally shutdown the WSL2 VM with `wsl --shutdown`. If I open Code again with this project, I get the "Initializing JS/TS language features" and watch this `Vmmem` process climb and climb until I run out of RAM and it fails.

**Comment by alexpaluzzi** [comment]
There is something seriously wrong with how my project opens here in WSL2 and Code. I was able to reproduce this on an entirely different machine.

To give an idea of what my project looks like:

`node_modules`
`folderA`
  `node_modules`
`src`
  `folderB`
    `folderB1`
      `node_modules`
    `folderB2`
      `node_modules`

There are about 500+ folderB(n). All with their own `node_modules` folder. The joyous world of "serverless".

**Comment by alexpaluzzi** [comment]
Digging in more, it definitely looks related to the file watchers. No matter what kind of globbing I can come up, I can't get Code to ignore all `node_modules` folders recursively.

**Comment by mjbvz** [comment]
@sheetalkamat Should @alexpaluzzi try changing to use a different file watching strategy to see if that helps?

**Comment by sheetalkamat** [comment]
I dont know think it would help since editor watches `node_modules` directory instead of actual script infos. I think the issue is similar to #33335. We would need more options to ignore directories for watch to handle this.

**Comment by alexpaluzzi** [comment]
@sheetalkamat that certainly seems like it. It doesn't look like it's possible today to have this directory open with WSL2 in Code unfortunately.
