### ISSUE TITLE
Rename refactor for parameter does not rename parameter in TypePredicate

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#3624]
A rename refactoring for a parameter in a function whose type annotation is a type predicate does not rename the parameter in the type predicate.

**Comment by DanielRosenwasser** [comment]
This might be working thanks to #3611. I'm seeing correct behavior in Sublime with an updated tsserver. Can you try a recent services version and confirm?

**Comment by mhegazy** [comment]
confirmed this is already fixed in latest.
