### ISSUE TITLE
Type refinement doesn't work on destructured properties

### ISSUE THREAD

**Issue by StevenLangbroek** [microsoft/TypeScript#36256]
**TypeScript Version:**  3.7 (tried nightly too)

**Search Terms:**
- refinement destructuring
- refinement destructure
- refinement destructured property
- refinement union destructured

**Code**

```ts
type Result = {
    __typename: 'AuthError'
} | {
    __typename: 'OtherError'
} | {
    __typename: 'User';
    firstName: string;
    lastName: string;
}

const getResult = (): Promise<Result> => fetch('some/url').then(res => res.json());

getResult().then(result => {
    const { __typename } = result;

    if (__typename === 'AuthError') {
        return;
    }

    if (__typename === 'OtherError') {
        return;
    }

    // result isn't refined into `__typename: User` here:
    console.log(result.firstName);
})
```

**Expected behavior:**

I'd expected this to be refined regardless of whether testing the destructured discriminator or accessing it through the argument.

**Actual behavior:**

When destructuring the type is not refined.

**Playground Link:** 

[Playground](https://www.typescriptlang.org/play/index.html?ssl=34&ssc=9&pln=34&pc=16#code/C4TwDgpgBAShDOBXANsKBeKBvAUFfUA+oaJAHYCGAthAFxQDkAgosABYCiATlwPZcMcAXygAfbHgLFSESjXoMA8uwhdufAcLESCREuFnU6jAKrxVDANyT8AMwCWXeMAByR+s672yAc2u7kCmc3eShPbz9hHBwAY14yZygfCGA4JFQMKAAKAEp6AAU+KntzAB40lGAAPgwa2xSYtiyGeF4aAHpELmQGHIA6FTIsrgRaqBH4PoArVqGcnOscdoAqZbxl2AgHMggaMjQAd34Aa3h19pxk1IRK3IG2WWGbjPQa3F17W2yJyr7pAzk0HQwMYLHY6n4vR0ugII2AXTI-gIQmiHy+T3SwD++nIRgwIKUKjUPEhOWhMPGKQRSPwKJsUDiCV4yAgfWQvB8GN+DicriMC2EOWiKzWUA2cG2u1kaAAJrwEGQGIcTudLikKqg7oMuS83vTGYksHoZICoCJMD9UIs0dl-riaPjMMxWJwSQIye8KZT4VxEfS6TasnbDA7gU7lA9iRooZ6KXDqf7UQQDczWezOZasTzgvzrEIckA)

**Related Issues:**

**Comment by ajafff** [comment]
searching for "refinement destructuring" brought up issue #35283 which is basically the same.
TypeScript cannot narrow a variable based on another variable's refinement.
