### ISSUE TITLE
Incorrect classification for parameter name and type of type predicate 

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#3625]
The parameter name and type in a type predicate are classified such that they are colored the same as a keyword.

**Comment by mhegazy** [comment]
Pinging @tinganho for this one.

**Comment by DanielRosenwasser** [comment]
As mentioned in https://github.com/Microsoft/TypeScript/issues/3624#issuecomment-115107309, are we sure this wasn't fixed by #3611?

I can't confirm on my end.

**Comment by mhegazy** [comment]
looks like this one is fixed too. thanks @tinganho !

**Comment by tinganho** [comment]
:+1:
