### ISSUE TITLE
Cannot export const name: keyof T = 'x' ... does not export value 'x'

### ISSUE THREAD

**Issue by dphochman** [microsoft/TypeScript#36260]
**TypeScript Version:**  3.7.3
* Also found in 3.6.3, 3.5.1, 3.3.3, 3.1.6, 3.0.1.

**Search Terms:** export const keyof

**Expected behavior:**
TypeScript should export the value that is validated with 'keyof'

**Actual behavior:**
TypeScript exports the declaration of a variable that is validate with 'keyof', but not its value.
* The JS output is correct.
* The TypeScript output does not export the value "x".
* A workaround is to assign a local variable that is validated by `keyof`, and then export a variable that is assigned to that local variable.
* Unfortunately, TypeScript Playground will not Run this code ... the DTS tab shows the problem.
* FWIW: this seems like a tsc compilation problem.

**Related Issues:**

**Code**
```ts
/**
 * Demonstrate export + keyof issue.
 * TypeScript Playground Run fails to eval 'export' in JS.
 * Please review DTS tab results.
 */

// JS: Should export 'x'. PASS.
/** DTS: Should export "x". PASS. */
export const propertyName0 = 'x';

// JS: should not render interface. PASS.
/** DTS: should export interface as-is. PASS. */
export interface Interface1 {
    x: string;
}

// JS: Should export 'x'. PASS.
/** DTS: Should export "x". FAIL. */
export const propertyName1: keyof Interface1 = 'x';

// JS: Should assign 'x'. PASS.
/** DTS: Should not render local variable. PASS. */
const propertyName2: keyof Interface1 = 'x';

// JS: Should export value of local variable. PASS.
/** DTS: Should export "x". PASS. */
export const propertyName3 = propertyName2;

console.log(new Date());

```

<details><summary><b>Output</b></summary>

```ts
/**
 * Demonstrate export + keyof issue.
 * TypeScript Playground Run fails to eval 'export' in JS.
 * Please review DTS tab results.
 */
/** DTS: Should export "x". PASS. */
export declare const propertyName0 = "x";
/** DTS: should export interface as-is. PASS. */
export interface Interface1 {
    x: string;
}
/** DTS: Should export "x". FAIL. */
export declare const propertyName1: keyof Interface1;
/** DTS: Should export "x". PASS. */
export declare const propertyName3: "x";

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?ts=3.5.1#code/PQKhCgAIUgRBTAtgewHYGcAuAnAhp+SeADwAdltNIBqSAa3gE9kAzSAS3XQFd4A6KDAAqjUvADKAY2ztSVAAoAbXIwDm2ZN1QATSACUtkFrnaL0kTMiIA3XIsgByEuUoOOqSAClxA6JCXwuOiE2PDW7PAA7nBC4ha4AEaQoTyKmOi+IMDg4MDAXuIAXJDiABaairrOFFQOxA58-gCC4j65YDFFJeXclURkNZAARMRDjfItPtDZ1ZSQkmhYkKQaYpSMAHK4iPAADJAAvI71ANw5eQXF6D19qMhUoTrw2O4E2MaS-M2tAqAwsLErjcqgM5uxUG8PoQggBaTjjSaNLLgWZUcGQ3CfSAASQhzyhAEZIABvKCQcnEK44cGqM4AX3O+W8xTKFRBLlq9QRP3a-0B3TZ-Q5w1GjQAYk1sQAZJEzUFUBYYKgrZBrTCbbbwAnFBjMNi4jGfIlHOoOM65JldVm9XRBdDsVQeU3ctp-Tos4GQO4PeBPF6KZCSOyQWwyRKKL4TH7TcCKpYqtUanYAJh1TFYOLx70xWsOxzNjMuAptQsGtkUvEgGYDQfsofY4cjiN57uLfVRIrG3ymyI7ceVq2e6q2OwAzHmE0Ok-Bk+a48gI3wA6oABSoKJwfDwFcASh3ZyAA)

**Comment by dphochman** [comment]
Basically, TypeScript can export a constant, and it can assign a constant to a value validated with `keyof`, but it can't do both at the same time.

We are applying TypeScript to a codebase that has many TypeScript workarounds ... including exporting property names in constants and using those constants elsewhere to extract a property value (e.g. `const value = record[propertyName]`), or to define another interface (e.g. `interface Interface2 { [propertyName]: string; }`.  This bug makes it harder, and the workaround is less obvious.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior - type annotations have always taken precedence over initializers when emitting declarations.
