### ISSUE TITLE
Referencing `this` from a static class field

### ISSUE THREAD

**Issue by rauschma** [microsoft/TypeScript#36267]
**TypeScript Version:**  Nightly Playground

The following code ([Playground link](http://www.typescriptlang.org/play/?ts=Nightly#code/MYGwhgzhAEDC0G8BQ1oQC5nQS2NM0AvNAORgkDcKamOeARkdOgBbYQB0YVAvksAHsAdhAEgAphxACA5gApYHegEoK0APTrS5IA)) is legal in JavaScript, but produces a static error in TypeScript:

```ts
class C {
  static a = 'a';
  static b = this.a;
    // 'this' cannot be referenced in a static property initializer.
}
console.log(C.b); // 'a'
```

Practical use case – [my library Enumify for enums](https://github.com/rauschma/enumify):

```js
class Color extends Enumify {
  static red = new Color();
  static orange = new Color();
  static yellow = new Color();
  static green = new Color();
  static blue = new Color();
  static purple = new Color();
  static _ = this.closeEnum(); // TypeScript: Color.closeEnum()
}
```

**Comment by DanielRosenwasser** [comment]
Sounds like you want #5863, but if I recall correctly, the problem is that we don't assume the static side of one class is substitutable for another because then every subclass construct signature would have to be assignable to the constructor in the superclass.

**Comment by rauschma** [comment]
AFAICT, this is simpler. In first example above, `this` is just a synonym for `C`.

Another example:

```ts
class A {
  // Legal in JS, not allowed in TS:
  static thisIsA = (this === A);
}
class B extends A {}

console.log(B.thisIsA); // true
```

**Comment by DanielRosenwasser** [comment]
So you want "Monomorphic `this` for static members" :smile:

**Comment by rauschma** [comment]
Probably? 🤔

**Comment by robpalme** [comment]
Thank you for finding this @rauschma!

It's not just the type checking that's wrong.  The emit is corrupting legit ESnext code.  [Playground](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200118&ssl=4&ssc=25&pln=3&pc=2#code/MYGwhgzhAEDC0G8BQ1oQC5nQS2GgpiAGbQC806AFthANxIC+QA)

```js
class C {
  static self = this;
}
```

...becomes...

```js
class C {}
C.self = this;
```

**Comment by rauschma** [comment]
Right! Should be done via definition, not assignment.

**Comment by robpalme** [comment]
>Should be done via definition, not assignment.

Actually that bit is handled fine via the option `useDefineForClassFields`. The badness comes from using `this` at top-level scope. The downlevel is just semantically wrong.

Interestingly this bug goes away if `target == ESnext && useDefineForClassFields == true`.

**Comment by RyanCavanaugh** [comment]
@sandersn can you look at the emit thing (described lower in comments) ?

**Comment by sandersn** [comment]
Note that the classic, non-spec-compliant emit has been wrong since at least 2.4: https://www.typescriptlang.org/play/?ts=2.4.1#code/MYGwhgzhAEDCD2J4CdoFMAeAXNA7AJjAKK4CuAtgJYBmAntAN4CwAUNNBFmFpcNMmnzQAvNFxoA7nEQoAFAEoA3K3aduvaCjC4A5mhFjJ0pMgXK2HLjz600IJFNHipCE2ZWX1fHQLwHnxnJKHmrW0ABGIKT6TkauQeaqVhoADqTIKSAxhi4ypsEWoRoA+gZYABaUEAB0oPAQaCQUZtAA9K3QACq0KWgAysDIlClYAFyByLVIDU3kCqwAvkA

**Comment by sandersn** [comment]
1. We should remove the error for useDefineForClassFields+ESNext. The emit is correct and the type is correct. So the error is wrong there.
2. For class field emit, we could just replace `this` with `C` outside function and class expressions in static property initialisers. In that case we could remove the error entirely.
3. I thought that this emit would be incorrect with the semantics proposed in #5863, but that issue requests a `this` *type* for the static side of the class. Right now, in a static property of `C`, `this: typeof C`, but the emit wouldn't need to change if we changed it to be `this: this`.

I did (1) in #36781.

@rbuckton can you think of any problems with changing `this` references to `C` when emitting static properties?

**Comment by sandersn** [comment]
(2) is getting complicated fast -- and I still haven't thought about decorated classes. I'm going to move this to 4.0 since it's unlikely a finished PR would be safe to ship in the RC anyway.

**Comment by Kingwl** [comment]
Any progress? 

It's affect https://github.com/microsoft/TypeScript/pull/42986 and https://github.com/microsoft/TypeScript/pull/43092 at least.
