### ISSUE TITLE
async function needs Promise<T> return type quick fix

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/TypeScript#36266]
## Search Terms

- return type quick fix
- async function quick fix
- global promise type

## Suggestion

It would be nice if TypeScript contributed a quick fix to resolve `The return type of an async or global function must be the global Promise<T> type` errors. The fix would simply wrap the existing return type into a Promise.

## Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
Could you provide an example of a before and after of the code fix? It's not clear what fix you're expecting.

**Comment by JacksonKearl** [comment]
Before:
```ts
async doThing(): boolean { // Err: The return type of an async function must be the global Promise<T> type

}
```

After:
```ts
async doThing(): Promise<boolean> {

}
```

**Comment by Kingwl** [comment]
Related: https://github.com/microsoft/TypeScript/issues/35300

**Comment by DanielRosenwasser** [comment]
We should specialize the diagnostic for when the given type isn't assignable to `PromiseLike<any>` to add `Did you mean to write 'Promise<{0}>'?`

Then provide a quick fix to write `Promise<{0}>`.

**Comment by DanielRosenwasser** [comment]
Looks like this didn't make it into 3.9. Will have to review with @mjbvz and @RyanCavanaugh whether it goes into 3.9.3 or 4.0

**Comment by JacksonKearl** [comment]
!!!

hell yes
