### ISSUE TITLE
Self defined String Literals

### ISSUE THREAD

**Issue by fireflysemantics** [microsoft/TypeScript#36296]
```
export const ON_FIXED_PARAMETERS_SELECTED = 'ON_FIXED_PARAMETERS_SELECTED'
```

Turns into:

```
export reflect ON_FIXED_PARAMETERS_SELECTED
```

The reflect keyword could be something else ...

**Comment by dragomirtitian** [comment]
Please follow the template when you file a feature request. 

Your request specifically goes against:

* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
