### ISSUE TITLE
Type of variable changes by assigning a new value

### ISSUE THREAD

**Issue by HesamMarshal** [microsoft/TypeScript#36303]
**TypeScript Version:**  3.7.5

**Search Terms:** type change, type conversion

**Code**
```ts
function isString<T>(arg:T):boolean {
     return (typeof(arg)==='string')?true:false;
}

let myEcho;
myEcho = isString;
let myInt :number = 5;
console.log(myInt  + ", Type is "+ typeof(myInt)) // 5, Type is number
myInt = myEcho("hi");
console.log(myInt  + ", Type is "+ typeof(myInt)) //  true, Type is boolean

// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
**Expected behavior:**
It should make an error or  in console >> Type is number
**Actual behavior:**
 5, Type is number
true, Type is boolean
**Playground Link:** 

**Related Issues:**

**Comment by IllusionMH** [comment]
If you tried this in playground as (suggested by issue template) you would see an error.
`Type 'boolean' is not assignable to type 'number'. (2322)` [Playground](https://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABDAzgZSgJxmA5gHgBUA+ACgENNcAuRQgSloCM44AbAU3KQG8AoRIMSYOUEJiSkoATwAOHOMEQUq9RAF5NiAOQosOXNrUB+RFhAdEtYOTYoOAbj4BfPn05REAW2kBRCAAWcE4+-kEayOj6eE4e3tIAkmBQtGAgXkwcmBEArE4QCCjsHAB0bHC4pD5JngDUiABEADR0cpaojYj1MvKKytXJ9GoA9MOIOS2EbZGIaRlZfAOe6vFhcKQNATAN9PmFxWUVVYnJXY2T0x0NZz0KSsc1Q4ijguYcF-IzLMXcQA)

Are there any other configurations in your case?

**Comment by RyanCavanaugh** [comment]
There is indeed an error. Please follow the template completely. Closing due to lack of follow-up.
