### ISSUE TITLE
TS isn't able to find correct definition when deriving from previously returned generic

### ISSUE THREAD

**Issue by Siegrift** [microsoft/TypeScript#36312]
_(Sorry, if the title is not that descriptive, I tried my best)_

Hi, I am trying to create a functional `set = (object, path, value) => state` helper which sets the `value` on the given `path` in the `object` immutably...

I have a working definition in my library [here](https://github.com/Siegrift/tsfunct/blob/master/src/set/set.ts) (here is [code sandbox](https://codesandbox.io/s/tsfunct-zysfi) if you want to play with it)

The problem is I want to create a functional version of this helper with this signature:
`set = (path, value) => (object) => object` so that I can compose these setters...

I know typescript is not able to partially infer generics (#26242 and #26349) but I don't understand why my current version doesn't work.

**TypeScript Version:**  3.7.2 (but the problem persists on all TS versions in the playground)

**Search Terms:** Generics, Partial type inference, nested key inference, definition overloading

**Code**
Code is a bit large, so I added it only to the attached playground.

**Expected behavior:** Calling the `fpSet` function should infer correct definition.

**Actual behavior:** TS is not able to correctly infer the correct definition

**Playground Link:**  [playground link](https://www.typescriptlang.org/play/#code/C4TwDgpgBAYmDKFgEYA8AVANFA0sqEAHsBAHYAmAzlANYQgD2AZlOgHxQC8rBxZVUAIakQAbQC6AWABQUKAH5WMuQC4oABQCWAYxoZsAUULaANgFdyEVHUYssuZGw4AyZXPcBvKKJx4om0gdxAFp5NQAlCABHM00AJwhyVC1dfVw8Jx88cSgAXxkZUEhYBCQAJjS-IhIKahtmVmwcMt4agXq7H2RxDm50Vv5qYTEpWQUlMbUUvXsjUwsrDsaHJyhXMfcoLyz8AKDQiOjYhKTtm39A7LU4RBQMLvEmso5cth2c-OkZAJI4pkFtNAbkgYIEPG4APQQqDAAAWmmoCKEUFhAJo2AARhBtIIzJRoOh4FByAwIJRSAByYBQShmMBgBhxalgQRMzSCExQADmZAgcR0UBZcUEAFsLkw+WRAZDoQkRQwAG7QOFI4TkGGw6DaBiWQWCSj46jauIJbTAEwgNwYNgACgAlGpUFU+LVaPQGuwbW45Cy4WoHphvVAFRyzBA1OgA247VwODbKAwzHFARGY5wOMC7vYMgUxlCNUjVSi0Zjsbj8awiSSyZTqbT6YzmazgOzOTzSHyBULReLJaRpWNrfbHc62nV3XYngNXUtI9lbUHfbD-Xgno8gyHzOHWA8fGV12M03GE0mU6wjyVbhVs8gnmwZJ8ZJZTKytQxSJRqUxSsBrj-QbmRTQAAqvicRcFsbiaOQaikGYIpYnED6AeA0DwMAggkBB4JjHifKUGooF8hIyFfNIz4mK+UAmEgNIYSQajoZhEAyPmKrUCYATQJQsKJiY6qkAw1LtnyzHIoSBAmoyQjUHC3HYu+6qWEwASaC274XJeIKBEi2oimAnHCMArHQhyCb+CwjBmFAcqKsqmpQCpcSfsSEAqaQamaBpeyZqC2ByVA2q6qi1CCZJcSMpQMjfrcqBMSQtp2jaogUnhzkUtgAAMjxbP4MFQAA7EVeRJZ+zF2kAA)

**Related Issues:**  #26242, #26349

**Comment by Retsam** [comment]
I believe the core issue here is that the overloaded function definition is essentially trying to do return-type polymorphism, which isn't supported.

It's defined like:

```ts
interface FpSetFn {
  // this is a hack, because TS doesn't support partial generic param inference
  // remove this and the code passes correctly
  <T>(): /* function with two type parameters */
  <T>(): /* function with a single type parameter */
}
```

Since those signatures only differ in return type, any call to `FpSetFn` is always going to match the first overload (Typescript takes the first overload that matches, when multiple can match), with a single type param, so it's not going to accept the args associated with the two parameter version of the inner function.

**Comment by Siegrift** [comment]
@Retsam Thank you, do you know any tips how to make the function signature compliant with TS? The idea is to use it like:
`fnSet<FromObject>(['state', 'path'], newValue)(destinationObject)` so the `fnSet` functions can be partially applied and composed... I don't see any nice way how to do this with TS (as it doesn't support partial generics)

**Comment by Siegrift** [comment]
I managed to solve the problem using this updated snippet: https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=39&pc=49#code/C4TwDgpgBAYmDKFgEYA8AVANFA0sqEAHsBAHYAmAzlANYQgD2AZlOgHxQC8rBxZVUAIakQAbQC6AWABQUKAH5WMuQC4oABQCWAYxoZsAUULaANgFdyEVHUYssuZGw4AyZXPcBvKKJx4om0gdxAFp5NQAlCABHM00AJwhyVC1dfVw8Jx88cSgAXxkZUEhYBCQAJjS-IhIKahtmVmwcMt4agXq7H2RxDm50Vv5qYTEpWQUlMbUUvXsjUwsrDsaHJyhXMfcoLyz8AKDQiOjYhKTtm39A7LU4RBQMLvEmso5cth2c-OkZAJI4pkFtNAbkgYKQMBwPG4APRQqDAAAWmmoSKEUHhAJo2AARhBtIIzJRoOh4FByAwIJRSAByYBQShmMBgBhxWlgQQszSCExQADmZAgcR0UDZcUEAFsLkwBWRAdDYQkxQwAG7QBEo4TkOHw6DaBiWYWCSiE6i6uIJbTAEwgNyoKp8Wq0egNdgACjccjZCLUD0w7qgSq5ZgganQPrcAEo1C7KAwzHFASHw1wOMC7vYMgUxjCtSj1WiMdjcfjCawSWSKdTafTGczWezgJzuXzSAKhSLxZLpaRZWNbfhqoNHbZls0Bg6lqHsmw3RsDV7vHgno8-QHzMHWA8fGVl2NI1Bo7H4+v0EnOCnSsAKunkE82DJPjJLKZ2TqGKRKLSmBe1OCXafz7coLgpmRTQAAqoScRcFsbiaOQaikGYYo4nE94geA0DwMAggkNBkJjASAqUGoEEChIaFfNIT4mC+UAmEgdLYSQahYThEAyNmarUCYATQJQ8KxiYmqkAwtLNgKbGosSBBmsyQjUAifG4m+mqWEwASaA2b4XCUgGBCiupimAPHCMAHGwlyMb+CwjBmFACrKqq2pQOpcQfqSEDqaQmmaNpeypqC2CKVAur6ui1AiTJcTMpQMhfrcqCsSQ07hi6ohUoRblUtgAAMjxbP48FQAA7KVeSpR+bHhkAA
