### ISSUE TITLE
string enums: Infer default value from key

### ISSUE THREAD

**Issue by KennethKo** [microsoft/TypeScript#36319]
## Search Terms

string enum 
default value
initializer
infer

## Suggestion

Add syntactic sugar to string enum declarations to infer their values from their key names. The overwhelming majority of string enum values are identical or near-identical to their key names, and it's kludgy to list every reserved value twice in its declaration.

```
enum<string> Foo {
  A,
  B,
  ...,
  Y = 'LegacyOverrideYValue',
  Z,
  LongAndSimilarEnumName,
  LongUnsimilarEnumName,
}

// instead of 

enum Foo {
  A = 'A',
  B = 'B',
  ...,
  Y = 'LegacyOverrideYValue',
  Z = 'Z',
  LongAndSimilarEnumName = 'LongAndSimilarEnumName',
  LongUnsimilarEnumName = 'LongUnSimilarEnumName',
}
// which contains a sneaky bug
```

**Comment by AnyhowStep** [comment]
https://github.com/microsoft/TypeScript/issues/16464
