### ISSUE TITLE
Array of different subclasses can't be pushed onto array of common base

### ISSUE THREAD

**Issue by realh** [microsoft/TypeScript#36331]
**TypeScript Version:**  3.8.0-dev.20200119

**Search Terms:**
array of unions
array different subclasses
array type inference

**Code**

```ts
class Widget {
    constructor (public name: string) {}
}

class Label extends Widget {
    constructor(name: string, public text: string) {
        super(name)
    }
}

class Button extends Widget {
    constructor(name: string, public caption: string) {
        super(name)
    }
}

let widgets: Widget[] = [
    new Label("label1", "Hello world"),
    new Button("button1", "Click me"),
]

widgets.push([
    new Label("label2", "Hello again"),
    new Button("button2", "Click me too"),
])
```

**Expected behavior:**
The code should compile without errors. The initial assignment to `widgets` is valid, so pushing a similar array literal should be valid too. 

**Actual behavior:**
The `push` statement causes this error:

> Argument of type '(Label | Button)[]' is not assignable to parameter of type 'Widget'.
>   Property 'name' is missing in type '(Label | Button)[]' but required in type 'Widget'. ts(2345)

If I `push` each of the widgets separately the code compiles OK.

This issue also affects typescript 3.7.5.

**Comment by IllusionMH** [comment]
It looks like TS found issue in your code. Most likely you mean `concat` array of two widgets to existing two instead of `push`?

**Comment by realh** [comment]
I thought `Array.push` could take an array and push each of those items, but I had it confused with the version that takes multiple arguments. I guess I just need to remove the square brackets.
