### ISSUE TITLE
Syntactic sugar for Algebraic Data Types

### ISSUE THREAD

**Issue by agentcooper** [microsoft/TypeScript#36336]
Many modern languages have a feature to elegantly represent a group of related values with the data attached to each variant. Some languages use enums with associated values ([Swift](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html#ID148), [Rust](https://doc.rust-lang.org/book/ch06-01-defining-an-enum.html)), others use sealed classes ([Kotlin](https://kotlinlang.org/docs/reference/sealed-classes.html)). Sometimes this feature is called [algebraic data types](https://en.wikipedia.org/wiki/Algebraic_data_type).

In TypeScript we need to write some amount of boilerplate for this, as it can be seen in the [language comparison](https://agentcooper.github.io/swift-kotlin-typescript-rust/#algebraic-data-types).

The proposal is to extend `enum` syntax:

```typescript
// new syntax
enum Shape {
  Square(side: number),
  Circle(radius: number)
}
```

The above will be desugared (expanded by the compiler) into:

```typescript
const enum ShapeKind {
  Square,
  Circle
}

interface Square {
  kind: ShapeKind.Square;
  side: number;
}

interface Circle {
  kind: ShapeKind.Circle;
  radius: number;
}

type Shape = Square | Circle;

const Shape = {
  Square(side: number): Square {
    return {
      kind: ShapeKind.Square,
      side
    };
  },

  Circle(radius: number): Circle {
    return {
      kind: ShapeKind.Circle,
      radius
    };
  }
}
```

To be later used as usual:

```typescript
const shapes: Shape[] = [Shape.Square(2), Shape.Circle(4)];

function getArea(shape: Shape) {
  switch (shape.kind) {
    case ShapeKind.Square:
      return shape.side * shape.side;
    case ShapeKind.Circle:
      return Math.PI * shape.radius ** 2;
  }
}

const totalArea = shapes.reduce(
  (sum, shape) => sum + getArea(shape),
  0
);
```

[Full code on TypeScript playground](https://www.typescriptlang.org/play/index.html?ssl=58&ssc=1&pln=43&pc=1#code/PQKhFgCgGMHsDsDOAXABAU3gVwLaoMoAWAhgA7qoDeUqBAjlsQE7oAUiAlgCboBcq2HACN0TAJQAaGqgDCHJtAA2bJsS4csifoJHioAXyghgUKMGCoAQgFEA4gEkAcvx6IsAc2bouqODyhwSGiYuAQk5ADSHPA+1JC0+AxeUvGy8kroBqaQ0ciiAGbE0BSJjCxU0gDW0Vz8RGToUTEAdKVeANzSnDzauLqdkIaQULkFRRRyCsoVqdUxdeGNNc2TGQO0quqavcKiA0NQyACe5GENqAC89GUUAD5pU+gDAQgoZ6dXcQlJLOzcfAI+qIxHUfhQvrRUCxkFgmPAZpDIXNau8li02iwUojaN1MqlaPp1qh9ClpKtlKxNhotIDduJ+OTwdINugYXCEdjkQsGk0uCt0sosdiqZpmcSiUMhuZUNZHAARFzoNyeFg+Px4l5BVCIRY0+rkADaAF1LqgDfr0K0wawAEySVH8x6sAAsYiNz0g+Sw8GgyA4CFQ7lZAEEWMR2ItueQxBzEAB3DjIaCEVARhrNZExiG0aDERAlRa8q03Xhills+E69O41AgbWLZq4ok5vMFnnLRml-GQ6Gw+EAWWIyEIzQACvZa-X0yLELW6zaJVlhjBXmhkLBkMRFKH0MRTVXyIhmqqsMVWNJ2LgJFPo5cAHza0IAakDIbDaejQoADFAxB7AogsDKM0iiwO4rDrpu25hn+QA).

I don't think this is too far from the current `enum` since it already acts as both type and runtime value.

**Comment by jcalz** [comment]
I think we're supposed to use the template, right?  

> My suggestion meets these guidelines:
> 
>* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
>* [ ] This wouldn't change the runtime behavior of existing JavaScript code
>* [ ] This could be implemented without emitting different JS based on the types of the expressions
>* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
>* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

This definitely counts as "non-ECMAScript syntax with JavaScript output", so I doubt this will get traction.  Yes, [`enum` is already like this](https://github.com/microsoft/TypeScript/issues/35039#issuecomment-552560576), but that's a legacy decision from a simpler time.

**Comment by RyanCavanaugh** [comment]
As much as I love ADTs too, we're getting out of the runtime-affecting constructs as much as possible.

We've been chatting *very* lightly internally about some kind of more friendly way to write a discriminated union, but it'd definitely be runtime-free. Maybe this would be cute? Might delete later
```ts
type MyUnion on 'kind' {
  'circle': { radius: number },
  'square': { length: number }
}
```

**Comment by jcalz** [comment]
```ts
type MyUnion = DiscriminatedUnion<"kind", {
  circle: { radius: number },
  square: { length: number }
}>
```
<details><summary>🛠</summary>

```ts
type DiscriminatedUnion<K extends PropertyKey, T extends object> = {
  [P in keyof T]: ({ [Q in K]: P } & T[P]) extends infer U ? { [Q in keyof U]: U[Q] } : never
}[keyof T]
```
</details>

[Playground](http://www.typescriptlang.org/play/#code/C4TwDgpgBAIglgZwMYCc4Fs4DsCGwIAmAqlnAPZYA8A0lBAB75YEJQAKKZkKo1EIAGigAVOowjNWZAEYArCEmAA+KAF4oAbwBQUKAG02UbFADW-MgDMRAXQBcUABQb9ARSNYo1O+ygBfKABkIgbWAJRiTCzuFhAoUERQAPyaru6m5lZE3kR6LtZ+UPZYEABusVq+emYgljZaWqCQUACyICTkHurwyGiYuPjEpBSUAEQm2AQjQtq6SHAoSAA2EPbOKDgEcACuCEVb6NKxfgI6UAgAjls4KCspy1gA5sAAFnsHR74VSjpaAPQAVFBGtBWu0KGpNKddONmPYRnMFssRgBuKFQdabHZvQ4oVH+AA+kN00ImcIuVxuKLR9yerygWH2OLxUH+vyAA)

**Comment by ozyman42** [comment]
The nice thing about TypeScript enums and Rust enums that this `DescriminatedUnion` type doesn't offer is nominal typing.
Ideally I could declare an ADT enum and each member is a nominal type.
