### ISSUE TITLE
Invalid left-hand side of assignment expression error when LHS is ES6 style imported object

### ISSUE THREAD

**Issue by gautamsi** [Microsoft/TypeScript#3634]
I get this error when I try to perform following. Idea is that value is populated during bootstrapping module when consuming code import my module. consumer can then change this value to something they want (an IApi interface type)
file 1:
````TypeScript
export var Variable = null;
````
````TypeScript
import {Variable} from "./file1";
Variable = somevalue;
````

if I use old style import statement like following, there are no error thrown
````TypeScript
import file1Module = require("./file1");
file1Module.Variable = somevalue;
````

is it by design? or bug?
Should not compiler take care of this, it anyways generates proxy Variable_1.Variable during compilation.

**Comment by DanielRosenwasser** [comment]
I believe this is by design; exported variables, if I recall correctly, can't be written to.

**Comment by vladima** [comment]
this is by design: per ES6 spec import bindings (created via [CreteImportBinding](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-createimportbinding)) are immutable.
