### ISSUE TITLE
clarify error messages relation to settings/rules

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/TypeScript#36376]
Hello, the VSCode team suggested I file this here, as it is an upstream issue: 

Currently, when Typescript reports an error in the "problems" pane, it's not clear which option/rule to turn on/off if you want to ignore that warning.  

**Example error**: `initializer provides no value for this binding element ... TS(2525)`

There seems to be **no documentation mapping the error to the associated compiler option** in `tsconfig.json` (I have an open [Stackoverflow](https://stackoverflow.com/questions/59848559/connecting-typescript-errors-to-their-associated-compiler-options-tsconfig-json) question about that, if anyone knows.)

**A fix** would be for the warning text to contain the setting related to this problem, like ` "strictPropertyInitialization": true`, or whatever.  

Thanks for considering!

**Comment by RyanCavanaugh** [comment]
Please follow the provided template.

The specific error you have here cannot be silenced by a compiler option.

In general we feel that your compiler settings should drive your coding experience, not vice versa. For someone who really does want e.g. `strictNullChecks` on in their codebase, it would be noisy and annoying to say "This object could be null. Did you want to turn strict null checks off?".

There currently isn't documentation on each of our error messages (this would be a *colossal* undertaking, but would be nice), but we feel the existing commandline option documentation is fairly clear.
