### ISSUE TITLE
custom jsxFactory unchecked type of children

### ISSUE THREAD

**Issue by xania** [microsoft/TypeScript#36370]
## Search Terms

jsx, jsxFactory, typesafe children

## Suggestion

typechecking the children in a JSX declaration to match the inferred type of the 3e argument from the custom jsxFactory. Consequently, type inference of the children element should be possible too.
Also, this should be included as a opt-in feature to prevent existing code from breaking without a gratuate migration plan, i.e when option --jsxStrictChildren is set.

## Use Cases

Improved typechecking and type inference for react and react-like libraries.

## Examples

say we have this minimal component

```typescript
function MyContainer(props: unknown, children: number[]){
    return null;
}
``` 

The custom jsxFactory `h` requires it's `children` argument to be of type `number[]`.
```typescript
Type PureComponent = (props: unknown, children: number[]) => any;
function h(comp: PureComponent, props: unknown, ...children: number[]) {
  return comp(props, children);
}
```

Pass `string` where `number` is expected does not compile, just as expected. 
```typescript
h(MyContainer, null, 'invalid value'); // compilation error
```

Same as above, but with JSX syntax.
This line passes compilation, but shouldn't!
```typescript
const notok = <MyContainer>{'invalid value'}</MyContainer>; // missing compilation error
```

## Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is the same as #14729 / #21699 / related issues; setting a custom factory currently only modifies emit and does not cause typechecking behavior to change.

**Comment by xania** [comment]
@RyanCavanaugh "and does not cause typechecking behavior to change" suggests that React itself has typechecking of the children, but to my knowledge it's not the case, which makes it more evident that we need an opt-in setting so this wouldn't be a breaking change for existing react code.
