### ISSUE TITLE
tsc should return a failed exit code (ie: 1) when it can't build due to no config file

### ISSUE THREAD

**Issue by drtimwright** [microsoft/TypeScript#36385]
**tsc version**
Version 3.7.5

**Impact**
This caused our docker builds to pass and go into a test environment when they should have failed. For various reasons, the tsconfig.json file wasn't copied into the docker container - having tsc fail in this case would have blocked us deploying and made the root cause of the failing containers more obvious.

**Search Terms:** 
exit value
exit config missing

**Code**

when no tsconfig.json file:
tsc
echo $?

**Expected behavior:**
returns a non-0 exit code

**Actual behavior:**
returns a 0 exit code

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/33849

**Comment by RyanCavanaugh** [comment]
Checked some other commands that also print help with there is no obvious input; they all return `1`
