### ISSUE TITLE
property accessor of subclass instance should return base's class property value, but uses a subclass' getter

### ISSUE THREAD

**Issue by abobr** [microsoft/TypeScript#36399]
**TypeScript Version:**  3.7.2

**Search Terms:** 
getter
property accessor

**Expected behavior:**
should return value from base class A, which for the example provided is 10

**Actual behavior:**
returns value from class B, which for the example provided is 200

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/36346
https://github.com/microsoft/TypeScript/issues/29305

**Code**
```ts
class A {
    a = 10;
}

class B extends A {
    _a = 200;
    get a() {
        return this._a;
    }
    set a(v) { this._a = v; }
}


console.log(new B().a);
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class A {
    constructor() {
        this.a = 10;
    }
}
class B extends A {
    constructor() {
        super(...arguments);
        this._a = 200;
    }
    get a() {
        return this._a;
    }
    set a(v) { this._a = v; }
}
console.log(new B().a);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAECC0G8BQ1XTNAvNAjABgG4kBfJJUSGAIWgFMAPAF1oDsATGeZNaAfQ2wAmPIRRoA5rUboAFAEpEYnqgBOUgK4qW0RgAsAlhAB0-Ij1I8IU2QDcFCHQeP8s0GwWilSZYAHsWEL4gtEYgvuIyLLQA7tBU8kZgcgRAA)

**Comment by abobr** [comment]
in console the result is 10
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by jcalz** [comment]
I'm pretty sure `200` is the correct output (why wouldn't a subclass use its own accessors when overriding a property in the base class?) and I can't reproduce your result of `10` using the same version of Chrome and the same emitted JS code:

![cannot reproduce](https://user-images.githubusercontent.com/150626/73081888-69d7fa80-3e96-11ea-87f6-12defdbd2cbd.PNG)

Can you double check what you're doing and/or explain why you think the subclass should use the superclass's property value instead of its own?

**Comment by nmain100** [comment]
The emitted JS code is an incorrect downlevel.  If you take the typescript code (which is valid javascript, in this case) and paste it into the same console, you get `10`.

If you want fully compliant behaviour you have to set `useDefineForClassFields`: [Release Notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier)

**Comment by jcalz** [comment]
Got it, thanks!

**Comment by RyanCavanaugh** [comment]
This is one of the subtle differences between the "old" version of TypeScript class fields and what the committee ended up shipping. `useDefineForClassFields` will get you the "new" behavior to match e.g. Chrome's
