### ISSUE TITLE
tsserver.js/typingsInstaller.js is watching ignored directories (causing CPU load)

### ISSUE THREAD

**Issue by a1291762** [microsoft/TypeScript#36394]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.7.3

**Search Terms**
- watcher
- watch

---

I have Visual Studio Code 1.41.1 on Ubuntu 18.04.
I have an Ember project, that builds into a tmp/ directory.
I have added this to the watch exclude list because it's large and changes regularly (eg. while running tests).

    "files.watcherExclude": {
        "**/web-ui/tmp/**": true,
    },

I turned on verbose logging for tsserver (after reading many bugs and trying to identify the source of my CPU load). The logs show that changes inside the tmp directory are triggering something, which is probably why the CPU load is so high. Also, once this starts it seems to just loop forever? (or maybe it's just queued up the notifications).

Here's a sample of the part of the log that repeats.

    Info 19646[14:51:17.385] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-output_path-84OVG1Ct.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19647[14:51:17.385] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-output_path-84OVG1Ct.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19648[14:51:17.665] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-input_base_path-wnOSxgXB.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19649[14:51:17.665] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-input_base_path-wnOSxgXB.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19650[14:51:17.959] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-input_base_path-wnOSxgXB.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19651[14:51:17.959] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-input_base_path-wnOSxgXB.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19652[14:51:18.305] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-input_base_path-wnOSxgXB.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19653[14:51:18.305] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/funnel-input_base_path-wnOSxgXB.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19654[14:51:18.606] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_concurrency-input_base_path-KfhqeYgr.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19655[14:51:18.606] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_concurrency-input_base_path-KfhqeYgr.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19656[14:51:18.894] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_concurrency-input_base_path-KfhqeYgr.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19657[14:51:18.894] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_concurrency-input_base_path-KfhqeYgr.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19658[14:51:19.177] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_text_measurer-output_path-jaXKXveR.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19659[14:51:19.177] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_text_measurer-output_path-jaXKXveR.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19660[14:51:19.489] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_text_measurer-cache_path-4KZn31rh.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19661[14:51:19.489] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_text_measurer-cache_path-4KZn31rh.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19662[14:51:19.798] DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_text_measurer-input_base_path-I4mIM5US.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
    Info 19663[14:51:19.798] Elapsed:: 0ms DirectoryWatcher:: Triggered with /home/lincolnr/work/git/web-ui/tmp/broccoli_persistent_filterbabel__babel_ember_text_measurer-input_base_path-I4mIM5US.tmp :: WatchInfo: /home/lincolnr/work/git/web-ui 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations

Is there something else I need to do to stop tsserver from watching this excluded directory?

I can upload the whole log if it helps.

**Comment by mjbvz** [comment]
Moving upstream for TypeScript team's awareness

**Comment by sheetalkamat** [comment]
We don't have support to ignore watch directories yet, but #35615 enables us for that. we haven't gotten around to it yet. Note that typescript tries to optimize watches where in instead of watching all failed lookup locations we watch directory corresponding to it or something similar. Since your OS is ubuntu, we are creating recursive watches..

**Comment by RyanCavanaugh** [comment]
@sheetalkamat what's the follow-up recommendation for this now?

**Comment by sheetalkamat** [comment]
For now if the folder for `web-ui` was one level below i think we would skip watching it but i am not 100% sure if we do it in  all places or not (esp when creating recursive directory watching).
Moving this to 4.0 to look into watch ignore pattern specification.
