### ISSUE TITLE
Provide a way to supress specific compiler message like TS2415, incorrectly extends base on override method with different return type

### ISSUE THREAD

**Issue by gautamsi** [Microsoft/TypeScript#3639]
I am working on a code port from c# to TypeScript. Having some instance of overridden methods with new keyword in derived class. like following. Is there a way that I can suppress this instance of error TS2415. 
I can live with error message as it does compile the file. It will have issues when I start putting build system around, they will show as failed all the time. 

````csharp
class parent{
public string testmethod(){return ""}
}
class child: parent{
public new int testmethod(){return 1;}
}
````

**Comment by danquirk** [comment]
See https://github.com/Microsoft/TypeScript/issues/2900
