### ISSUE TITLE
Prefer .js file when attempting to access files with both .ts and .js

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#36437]
Consumers of typescript libraries will prefer the `.ts` source rather than the compiled `.js` files sitting next to them.

[[Example repo]](https://github.com/alshdavid-sandbox/tsc-workspace )
Imagine the following folder structure:

```
/lib
  /a
    index.ts
  tsconfig.json
  package.json
/project
  index.ts
  tsconfig.json
  package.json
```

When compiled `lib` will look like 
```
/lib
  /a
    index.js
    index.d.ts
    index.ts
  tsconfig.json
  package.json
```

and if `project/index.ts` attempts to import the compiled files from `lib` then after module resolution, `tsc` will prefer the `.ts` files over the `.js` files

```typescript
/*
 This will import '../lib/a/index.ts'
 however we were expecting '../lib/a/index.js'.
*/

import a from 'lib/a'
```

This causes problems when the compilers have different configurations, say the consumer is set to `strict: true` where the library has it set to `strict:false`

This is a huge problem with monorepos that use yarn workspaces or in projects that make use of npm/yarn link.

How do I get around this?

**Comment by RyanCavanaugh** [comment]
You can use project references to cause the `.d.ts` files to be picked up instead. I'm not sure why you'd expect the js to be preferred - this would be much worse.

**Comment by alshdavid** [comment]
I mean it makes sense for included files, but directories outside the compile's included source shouldn't be compiled
