### ISSUE TITLE
Inconsistent type inference on equivalent code, when passing generic same as default

### ISSUE THREAD

**Issue by fguitton** [microsoft/TypeScript#36434]
**TypeScript Version:**  3.8.0-dev.20200124

**Search Terms:**
generic inconsistent default 

**Description:**
While trying to write typings for a function that connects `react-redux` based React component I have come across a situation where inference happens correctly only when the generic type is not provided and left to default. When the same type as the default is passed, the inference breaks. Please accept my apologies if I have failed to find a past similar issue.

**Code**
```ts
interface StateConnector<R> {
    <O = {}, S = { [key: string]: unknown }>(propsMapper: MapStateToProps<S, O, ReturnType<R>>, component: FC<S & O & DispatchProp>): FC<S & O & DispatchProp>;
}

const rootReducer = () => ({
    demo: true,
    purposes: 'Testing'
})

const withState: StateConnector<typeof rootReducer> = (propsMapper, component) => {
    return component;
};

/* Example of behaviour #A
   This works as expected
*/
const HelloCmp = withState(s => ({
    example: s.demo,
    greeting: 'Hello'
}), ({example, greeting, dispatch, extra}) => { // Property 'extra' does not exist on type....
        extra++;
        if (example.valueOf())
            dispatch()
        return greeting.toLocaleUpperCase();
})

/* Example of behaviour #B
   This should behave exactly like #A
*/
const HelloCmpWithEmpty = withState<{}>(s => ({
    example: s.demo,
    greeting: 'Hello'
}), ({example, greeting, dispatch, extra}) => {
        extra++; // Object is of type 'unknown'.
        if (example.valueOf()) // Object is of type 'unknown'.
            dispatch()
        return greeting.toLocaleUpperCase(); // Object is of type 'unknown'.
})

/* Example of behaviour #C
   This is simalr to #B and only serves
   as illustration of the end-goal
*/
type HelloCmpProps = {
    extra: number
}
const HelloCmpWithProps = withState<HelloCmpProps>(s => ({
    example: s.demo,
    greeting: 'Hello'
}), ({example, greeting, dispatch, extra}) => {
        extra++;
        if (example.valueOf()) // Object is of type 'unknown'.
            dispatch()
        return greeting.toLocaleUpperCase(); // Object is of type 'unknown'.
})

```

**Expected behavior:**
Case #A and #B yield de same inference.
Case #C inference appropriately

**Actual behavior:**
#A functions as expected
The inference for #A and #B diverge.
Case #C does not produce expected outcome

**Playground Link:**
[Playground Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200124&ssl=1&ssc=1&pln=6&pc=65#code/PTAEFEA8BcFMCcB2BDANqaBPADrUATWVAY2XmWgEsB7RAZwCgtdQAlWZY6AOWsNAC8oRAFdUqANxMcedp2jhUsALaxE0QaGSJMU5ngAK8atjoB1StAAWAYSuVU+eGoA8BgHyaDoAGSgA3qDE9o7OiAD8AFxsHFy8-AC+ejKgALLI2ADK0BSwACrURiZ0LnnZuUWmADSgeQDyAO6IlXQ15XCeQgAUdDlw0e2wNdRNLdH1o8amAJSCnmV9sC3JLAAilHTYFMGVmoH4G1vQwdFdswKeAG7UlPgSoAnSLABiNm57CZ2gzyKIXDSIGzUZTYWhqaBudxSSjqBAAM04eB+fyotCBILB6neQn8nwCoC62CmdGiLQs1jsDicrg8NWItDgMCiWh002ici4ihU4NAAB9hGJJA8GAwQKAAJKwpBoUC9XJBWiIWBcajwAhEUjkVGIBgwuDwBHEPCDIGIJUq+AuViefwMUD20AuOofNp7UAAbQA1rBMNFevAYQBzAC60V+nsQI0QD3chOJ6WwuHg0QTgwKLRcmRqdRq7GgIiQeRkVvc7jpwNBSvU0Vemd8oGdfnWm22Vkq7jZ3zemXrjdAzaOOymUIYj1FYEGsqsGTw2nwssWCrNyqoiEDoDhv3+tAY9PoGmM1Gg7HwIiNau6508XVtDvVymo0Wg8BEQztDuwBdBdFgJNAAHI8l-VdA3-UdphFPdelABpLCsQYBkWU1zWgVUXH0ag4VAQ9j1gU9zy+ONigTJNywxKtoCvAJ33tZx8yQBVyPBKQkhFMUoGQEElFATDQAAI1gadLhoAtQAAYgARl3WhoIACSIVBqBsEFNFg6xBh6OYCVvB1YEgTjsCUP0ADpCAfKoaNAQNnFgEDon-eTxGoMCEmmGobz0gylBqazYFsoMagOFtjisGo9OfZBXK0nS73tcLyAAagSqRYodSgsK6TyuNgYzLjQV86jhM4INS1KgsHKwzksu86ILaNfP8tdjNQgAZahSCUABVRMEBsZAfzOFiIPHCB9OynisIEoSRLVMSACZpP3UBHMU5TsHJKxwBBLBVLgwYXFxWM6C0m9LKywzYBMszqAsu8GrsgCVuc8D3P8c7vKsmyQMCw5WzCmByCii5qNK0B4uQJKUtK9KCXenK8tQAqiumErQYdcrWyq0HaoY+6g2a6g2o62BuqTPqBumIa2LADjxt4qbkGE6hRLEgBmJ48CetaWj2M6AeQaJRGUAT4FHRa5IUpSQQ2nmhDU+DFhcLmQRaI6TpisGxouq6VBuyy8bXeynpctztLhnyvoCghfpC-6IqBm1qt0-nIad+0YcyrWlFy-LYEK4q3dijGQqx0qcfqy2mta9q0BJnr4HJ2BBvAhggA)

**Related Issues:** 
Possibly #24369, #30134

**Comment by AnyhowStep** [comment]
What you want seems to be partial inference for generic type parameters. I remember an issue for it being somewhere...

**Comment by AnyhowStep** [comment]
You can, instead, have,

```ts
const withState : <O={}>() => <S=Record<string, unknown>>(/*snip args*/) => /*snip return type*/;

withState<{}>()(/*snip args*/);
```

**Comment by fguitton** [comment]
Thank you very much for the insight. I have been able to achieve the desired result via currying.
Closing this issue, since this topic is covered by #26242 and #10571.
