### ISSUE TITLE
Merge custom "this" context with original "this" context

### ISSUE THREAD

**Issue by pleerock** [microsoft/TypeScript#36447]
## Search Terms

original this context, self this context

## Suggestion

When using a custom this context, I would like to use original this context as well. 

## Examples

Better to show example:

```ts
interface Repository {
    find(): void
    findOne(): void
}

interface CustomRepository {
    [key: string]: (this: Repository & this) => any // note: I tried to add & this but it doesn't work.
}

const repository: CustomRepository = {
    findNew() {
        this.findOne()
    },
    findOld() {
        // here I would like to access find(), findOne(), findNew() using this.
        // this.
    }
}
```

http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgEoQA4HsDOwxZQCeyA3gLABQyNyMoAJgBQCUAXMgG5bANW11GAeRARWHbryoBfKlVCRYiFAGEArjgIBbdNjwFiZfrQDaAawhEOmqKADmAXQ6tkAXgB8yOCBIB6X8ggWJAcAJLIYLYQDBFYXgwxAGQRABbAOMgARmpgyPjIDFgQOCAA5LkA7oRmAHQycpQIWCCayFCYuPiEVsjqmlg6HfrdbkbUtPQgDAByEBVMYGk4HLqdBkQsYwIC-qnpNZPMLMY00gA0J4JTQgA2R1vbNLsp0CjhVWp3yDfAFrFeCCQOAyh1YZyuDBEYhY4MOs3mmw09j2ODq40eu0W+0uskouKAA

What's interesting `& this` works if things are declared on interface itself. And what's interesting else, same interface changed to type doesn't understand `& this` syntax.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment]
FYI you can workaround it using `ThisType` and factory function (anyway you need to add 2 methods from your `Repository`).
[Example](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgEoQA4HsDOwxZQCeyA3gFDJXIygAmAFAJQBcyAblsHZdbSHQDyICMzadu5AL7lyoSLEQoAwgFccBALbpseAsTK8qAbQDWEImw1RQAcwC6bBmAAWwHGx258hEgDJkV3cmZABeAD5kOBASAHpY5BAsSDYASUCbCDpArCi6bICgnGQAI1UwZHxkOiwIHBAAcgqAd0JTADppWQQsEA1kKExvfUtkNQ0sbSG9XzDDahp6ADkIZuZ5heoi9v4hEWYjZCkAGkPdwQAbRhCKTa23HHbkeORei5IXOGKAJmQcVVstjqYGAvRwhwWLxc0BQ6VaqiuyAuwHMOSiCCQOGKu2Yx0WAmEoiYeN2KzWIXUdkCD06dyoL22hxkMnIdAgCAucEGNFUIAQIN6yAQgzgkC8M2IAB4ACrhBjATQYC5saXIALSh7SogYCCS8U+Azq8KsZDSgDczwSACFysh0rZVHVioMwKooCBAtqUDgXFgEdkSih9SM1abumCKoNdAaiL9QkKRWLpjGGLc+MtVus03dtud9kwmacFucrlmIfd3E8Xs1gBcLn9fc0onXkAAWP4AoEaUF9cv0hLQ7lwv2I5GogjozHY+i4-F7IkkjPk5CUkC2amVvuWjePJnSJhAA)

**Comment by pleerock** [comment]
@IllusionMH thanks a lot, didn't know about `ThisType`. This perfectly fits my requirements, since in a real case I have a factory function.

**Comment by RyanCavanaugh** [comment]
Tagging as Question since there's already a way to do it. If you want to refile as suggestion, some additional examples for context would be useful. Thanks!
