### ISSUE TITLE
Can't use aliases of the global `Symbol` value to refer to its properties in the same manner or create unique symbols

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#36468]
Although Nodejs also uses this technique, we can't do the same thing.

https://github.com/nodejs/node/search?q=primordials+symbol&unscoped_q=primordials+symbol

**TypeScript Version:**  3.7.x-dev.20200125

**Search Terms:**

**Code**

```ts
export { }
const Symbol = globalThis.Symbol;
const sym = Symbol();
[][Symbol.iterator];
```

**Expected behavior:**

```ts
const sym = Symbol(); // typeof sym
[][Symbol.iterator]; // Refer iterator method
```

**Actual behavior:**

```ts
const sym = Symbol(); // symbol
[][Symbol.iterator]; // error
```

**Playground Link:** http://www.typescriptlang.org/play/index.html?target=5&ts=3.8.0-dev.20200125&ssl=1&ssc=1&pln=2&pc=21#code/KYDwDg9gTgLgBAbzgXwFAGMIDsDO8DKAngLYBGEANnALxwDmFEpAhhQCoAWAljgHRFlKAbgzY8cHCRpwB5CgAoAlCIDaAXRWzKvLjGBRmMaGqA

**Related Issues:** #21603 #35478

**Comment by falsandtru** [comment]
Global variable reference greatly decreases the performance.

https://falsandtru.github.io/benchmark/suites/10/

But we can't avoid this performance problem caused by global reference for Symbol because of this issue.

**Comment by RyanCavanaugh** [comment]
I don't quite understand what you're doing or why, or why what you're doing doesn't justify a type assertion

**Comment by falsandtru** [comment]
> what you're doing or why

To improve runtime performance as I explained above.

> why what you're doing doesn't justify a type assertion

I'm not sure what you mean. What is meant by "justify a type assertion"?

**Comment by falsandtru** [comment]
FYI, you can also improve the performance of TypeScript using this technique but you can't do it about Symbol because of this problem.

**Comment by falsandtru** [comment]
@RyanCavanaugh Can you triage the other issues too?

**Comment by RyanCavanaugh** [comment]
@falsandtru if you can come cook dinner and tend to my kid I can work evenings

**Comment by falsandtru** [comment]
@RyanCavanaugh I'm not saying do it right now and the oldest issue in these days (#35896) was opened a month ago. Do you require me to wait more? 2 months?

**Comment by RyanCavanaugh** [comment]
@falsandtru your issues are very confusing and require a lot of time to try to piece together what you mean and what you want to happen. You'll have to forgive me that I take up more actionable issues first; other people have put in the work to make  understandable reports and are treated as such.

**Comment by falsandtru** [comment]
> Can't use aliases of the global `Symbol` value to refer to its properties in the same manner

And can't make unique symbols using an alias of the `Symbol` function. Don't miss it.

**Comment by falsandtru** [comment]
> your issues are very confusing

Can you point out where I don't know? It is difficult to know it myself.

**Comment by ExE-Boss** [comment]
The global `Symbol` properties will be fixed by <https://github.com/microsoft/TypeScript/pull/24738>, which converts them all to `unique symbol` types.

**Comment by bordoley** [comment]
One unfortunate side-effect of the inability to alias the Symbol constructor when defining unique symbol property keys for classes and objects is that it results in increased bundle size, even when compiled with terser (see: https://github.com/terser/terser/issues/1337). Your compiled code becomes littered with Symbol() invocations.

Typically in libraries one will alias globals like Math to a local variable to work around terser failing to mangle built-ins,  but given this TS limitation there is no way for one to do so.

**Comment by RyanCavanaugh** [comment]
The issue in the OP now behaves as desired, so I'm inclined to close this. @bordoley can you confirm or provide a failing repro?

**Comment by bordoley** [comment]
@RyanCavanaugh: I'll create a test repo, and file a new issue with an example that illustrates the issue.

**Comment by RyanCavanaugh** [comment]
Thanks!

**Comment by bordoley** [comment]
see: https://github.com/microsoft/TypeScript/issues/53282
