### ISSUE TITLE
Compiler incorrectly narrows variable to never type in finally block

### ISSUE THREAD

**Issue by mpvosseller** [microsoft/TypeScript#36473]
The below code gives a compiler error in the finally block at messageSource.close(). It appears to incorrectly believes that `messageSource` has type `never` at the `messageSource.close()` line. This seems to be because both the try block and catch block return/exit the function. However the finally block will still run so the code should compile. At the time of this writing it is broken in the latest release `3.7.5` but appears to be working in `3.8-Beta` so it may have been fixed.

**TypeScript Version:**  3.7.5

**Search Terms:**

**Expected behavior:**
This below code should compile without error

**Actual behavior:**
There is a compiler error in the finally block at `messageSource.close()`

**Related Issues:**

**Code**
```ts
/* eslint-disable no-console */
class MessageSource {
  getMessage(): string {
    return 'myMessage'
  }

  close(): void {
    console.log('Cleaning up')
  }
}

function getMessageSource(): MessageSource {
  return new MessageSource()
  //throw new Error('Something failed')
}

function run(): string {
  let messageSource: MessageSource | null = null
  try {
    messageSource = getMessageSource()
    return messageSource.getMessage()
  } catch (e) {
    console.log('Caught an exception')
    console.log(e)
    console.log('Rethrowing exception')
    throw e 
    // return 'test'
  } finally {
    console.log('In finally block')
    if (messageSource) {
      console.log('Closing source')
      messageSource.close()
    }
    console.log('Completed finally block')
  }
}

run()

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
/* eslint-disable no-console */
class MessageSource {
    getMessage() {
        return 'myMessage';
    }
    close() {
        console.log('Cleaning up');
    }
}
function getMessageSource() {
    return new MessageSource();
    //throw new Error('Something failed')
}
function run() {
    let messageSource = null;
    try {
        messageSource = getMessageSource();
        return messageSource.getMessage();
    }
    catch (e) {
        console.log('Caught an exception');
        console.log(e);
        console.log('Rethrowing exception');
        throw e;
        // return 'test'
    }
    finally {
        console.log('In finally block');
        if (messageSource) {
            console.log('Closing source');
            messageSource.close();
        }
        console.log('Completed finally block');
    }
}
run();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#)

**Comment by MartinJohns** [comment]
Duplicate of #35644.

Your playground link does not work, it just links to the playground itself. [Here is a fixed link.](https://www.typescriptlang.org/play/#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJgID2KAxkQlEfmCMAFCkxZRRgCy02A5hAMpEArgCdSBAN70wYXkk6ssvABQBKAFxgoSYYm5hJ06cIhIRCMAHIAtgE95PCBalgAvvWdMiUCKo0A3Ijg0fWdpckpqCAA6GCJuJQsAYXwsBF0wQQAHCxVnNzd6ADNBBFIkOAoZE3tFfiFRH3UOLlqBETEQoxMzQggAd2aFXjaG1WdgYCQAC2EiAYR+sABRYVnhBIErEyn0wqw4fDQc+gLi0vLK4RLfTW10gzB8JDAtobr2iA0a4fqOgB9CIIYDAwABeQHA5zaGydQyvBwjDrg2Tfd6jXKGMDGUzCczw1q-aIolrKDGuMCkLBIUhTMBKCAqWFhChUfAxOIJRJYQTcKbPVKQAAeYkyFwQx0x4VZ0Vi8QZoQpLMi7PiFgASttZn10hBhRBRRVxWTpNMtZAwAqJljurjLEhoEgnNIXGBCogsMCYQ9mRE2bKEgBJcxuhAemAwvBEUgAawlhjghTp+J+H0Z3sMUuV-qSsSg6SoHzjmOTaLEUU83jGmLckqVfo5SSIVkyTwgwRDYYjsRjcfy7iuCFUQA)

[Here is your code in the 3.8-beta version.](https://www.typescriptlang.org/play/?ts=3.8-Beta#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJgID2KAxkQlEfmCMAFCkxZRRgCy02A5hAMpEArgCdSBAN70wYXkk6ssvABQBKAFxgoSYYm5hJ06cIhIRCMAHIAtgE95PCBalgAvvWdMiUCKo0A3Ijg0fWdpckpqCAA6GCJuJQsAYXwsBF0wQQAHCxVnNzd6ADNBBFIkOAoZE3tFfiFRH3UOLlqBETEQoxMzQggAd2aFXjaG1WdgYCQAC2EiAYR+sABRYVnhBIErEyn0wqw4fDQc+gLi0vLK4RLfTW10gzB8JDAtobr2iA0a4fqOgB9CIIYDAwABeQHA5zaGydQyvBwjDrg2Tfd6jXKGMDGUzCczw1q-aIolrKDGuMCkLBIUhTMBKCAqWFhChUfAxOIJRJYQTcKbPVKQAAeYkyFwQx0x4VZ0Vi8QZoQpLMi7PiFgASttZn10hBhRBRRVxWTpNMtZAwAqJljurjLEhoEgnNIXGBCogsMCYQ9mRE2bKEgBJcxuhAemAwvBEUgAawlhjghTp+J+H0Z3sMUuV-qSsSg6SoHzjmOTaLEUU83jGmLckqVfo5SSIVkyTwgwRDYYjsRjcfy7iuCFUQA) It works correctly in 3.8, as indicated by #35644.

**Comment by mpvosseller** [comment]
Thanks!
