### ISSUE TITLE
Compiler error from method with return type + body with if and throw: A function whose declared type is neither 'void' nor 'any' must return a value or consist of a single 'throw' statement.

### ISSUE THREAD

**Issue by atsu85** [Microsoft/TypeScript#3647]
Hi,
Here is an example that incorrectly (as I understand) generates a compile-time error with TypeScript 1.5 beta: 

> A function whose declared type is neither 'void' nor 'any' must return a value or consist of a single 'throw' statement.

```TypeScript
class Demo {
  xxx() : number { // 1. note: this method has return type (not any)
    if(true) { // 2. note: this method contains if statement (body is not important)
    }
    throw new Error("test"); // 3. note: this method throws error instead of returning instance of expected type
  }
}
```

But if i remove the if or add return after throw statement (that never gets executed), then compiler is fine with it:
```TypeScript
class Demo {
  xxx() : number {
    if(true) {
    }
    throw new Error("test");
    return null; // this line doesn't make sense, but makes TS compiler happy
  }
}
```
**Expected behavior:**
First example should compile fine without errors, workaround shown in second example should not be needed to make compiler happy, as adding return statement after throw statement doesn't make sense (return will never be executed at runtime).

**Comment by mhegazy** [comment]
This is because the compiler does not do control flow analysis at this point. it would be a restriction that can be relaxed once this support is added. 

As for now this is by design, as per the [section 6.3: function implementations](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#63-function-implementations) from the language spec:

> An explicitly typed function whose return type isn't the Void or the Any type must have at least one return statement somewhere in its body. An exception to this rule is if the function implementation **consists of a single 'throw' statement**.

**Comment by mhegazy** [comment]
see #1042

**Comment by qq1209974887** [comment]
> 错误:(19, 43) TS2355:A function whose declared type is neither 'void' nor 'any' must return a value.

```
        let identity = function <T>(x: T): T {
            console.log(1);
        };

        let reverse = function <U>(y: U): U {
            console.log(0);
        };
        identity = reverse;
```
