### ISSUE TITLE
`this` can not be inferred when the function definition is wrapped in parentheses.

### ISSUE THREAD

**Issue by stevekrenzel** [microsoft/TypeScript#36492]
**TypeScript Version:**  3.7.5 & 3.8-Beta

**Code**

```ts
type Foo = any;

const foo: Foo = {};

foo.bar = function () {
    const self: Foo = this;
}

foo.zab = (function () {
    const self: Foo = this; // This results in an error
});
```

**Expected behavior:** Both the `foo.bar` and `foo.zab` definitions should type check fine.

**Actual behavior:** The `foo.zab` assignment fails. It appears that TS can't determine the `this` when the assigned function is wrapped in parentheses.

**Playground Link:** https://www.typescriptlang.org/play/index.html?ssl=11&ssc=4&pln=1&pc=1#code/C4TwDgpgBAYg9nKBeKBDAdiA3AKBwYznQGdgoAzBALlgWSgG8BfXHSuAOgCNUAne8gFd0+YAEsiUABQBKRjiiKohEmWIQANuRrxEKYAAsxxXEzzsOAL1Rd6UoSPGTZ8pcqKko6rTrr6jJjhMMlhAA

**Comment by DanielRosenwasser** [comment]
Thanks @brandonbloom!
