### ISSUE TITLE
Conflict with Object.prototype.watch in FireFox/Gecko

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#3649]
In Gecko engine `commandLine.options.watch` evaluates to a truthy value — [Object.prototype.watch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch). That means running the compiler in Gecko (as opposed to V8/node) it effectively defaults --watch to true

Here's a pull request to work around the conflict:

https://github.com/Microsoft/TypeScript/pull/3648

**Comment by danquirk** [comment]
Looks like the fix was already merged.

**Comment by mhegazy** [comment]
Thanks @mihailik !
