### ISSUE TITLE
Invalid type declaration for Class Instance Method inside a .js file with a default value of an inner parameter

### ISSUE THREAD

**Issue by nbaura** [microsoft/TypeScript#36507]
**TypeScript Version:**  3.7.5 and 3.8.0-dev.20200128

**Search Terms:** "default value" parameter "type definition" 

**Code**

```sh
tsc --allowJs --declaration --outDir out x.js
```

x.js:
```js
export class Z {
  f(x = 1, y) {
    return [x, y];
  }
}
```

**Expected behavior:**

x.d.ts should be:
```ts
export class Z {
    f(x: number | undefined, y: any): any[];
}
```

**Actual behavior:**

x.d.ts contains invalid typescript:
```ts
export class Z {
    f(x?: number, y: any): any[];
}
```

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=22&useJavaScript=true#)

**Related Issues:** None

**Notes:** Both top-level functions (in either .js or .ts) and class instance methods in .ts files have correct type defs generated in both 3.7.5 and 3.8.0-dev.20200128

**Comment by a-tarasyuk** [comment]
Should TS emit `x: number | undefined` for optional parameters (`x?`) in `strict` mode? Or here `strict` option doesn't matter?

сс @RyanCavanaugh @weswigham @DanielRosenwasser

**Comment by a-tarasyuk** [comment]
Should TS emit `x: number | undefined` _(`x?`)_ in strict mode? Or here `strict` option doesn't matter?

сс @RyanCavanaugh @weswigham @DanielRosenwasser

**Comment by weswigham** [comment]
Emitting the `undefined` even outside strict mode is, IMO fine; but I'm not 100% sure if that's desirable (since the code in question may not actually handle `undefined`)
