### ISSUE TITLE
Possibly add a new compiler option to list output files.

### ISSUE THREAD

**Issue by jakepetroules** [Microsoft/TypeScript#3650]
I'm adding support for TypeScript in the [Qbs](http://doc.qt.io/qbs) build system. Due to the way we track dependencies, we require knowing the list of output files a particular tool will produce when invoked with a particular set of arguments.

Currently, this can be difficult to determine since it requires actually parsing the TypeScript source code (i.e. external modules) rather than simply looking at filenames (as in the case of a C compiler, for example).

I'd like to request the addition of an additional option, `--exportDependencyInfo`, which will output in JSON format a list of all files that will be written by the compiler for a particular command line invocation. This would be used in combination with --noEmit, for example:

    tsc --noEmit -exportDependencyInfo --declaration --sourceMap --module amd --outDir /var/foo/bar \
        /var/public/a.ts \
        /var/public/b.ts

Expected output (assume b.ts imports an external module c):

    [
        {"filePath": "/var/foo/bar/a.js"},
        {"filePath": "/var/foo/bar/a.js.map"},
        {"filePath": "/var/foo/bar/a.d.ts"},
        {"filePath": "/var/foo/bar/b.js"},
        {"filePath": "/var/foo/bar/b.js.map"},
        {"filePath": "/var/foo/bar/b.d.ts"},
        {"filePath": "/var/foo/bar/c.js"},
        {"filePath": "/var/foo/bar/c.js.map"},
        {"filePath": "/var/foo/bar/c.d.ts"},
    ]

I notice there's a --listFiles option documented here: https://github.com/Microsoft/TypeScript/wiki/Compiler%20Options Will this become a documented option in a future version? If so, this could be a possible solution to our problem, as we could find the common base path of the input files printed by --listFiles, and calculate the corresponding output filenames.

However, it would be ideal if the compiler itself did this, to avoid any potential discrepancy.

**Comment by mihailik** [comment]
It would be inconsistent this JSON way.

Inputs are dumped as line-separated list, so the output should go line-separated as well. Would that work for you, @jakepetroules ?

I'd name the new option --listOutputFiles, and required an extra line between input and output files if both options are specified at the same time.

**Comment by jakepetroules** [comment]
JSON would be ideal since it can losslessly represent any file path... but I suppose filenames containing newline characters are uncommon enough. Just being pedantic. :)

**Comment by mhegazy** [comment]
We talked about a `verbose` mode that would make the compiler write out some additional info to stdout, this can be one of the things we could emit along with resolution order, search locations, tsconfig location, etc..

**Comment by jakepetroules** [comment]
@mhegazy I don't think that this would be well suited for a verbose mode -- it must be output in a well-defined format that is machine parseable and will not change.

**Comment by mhegazy** [comment]
We have tried to limit the number of flags that the compiler supports to limit support costs and complexity. --listFiles is merely a debugging aid, and so was my --verbose suggestion. 

One option for finding out the output files, we do something similar for MSBuild task in VS, by inspecting the inputs to the compiler, and the compiler options you can enumerate the expected output files, e.g.: if you have `--out` you have a single .js file, if you have `--sourceMap` you have a .map file matching to each .js file and so on.. i can share the logic with you if that is something of interest.

The other option is to use the compiler API directly. see [this wiki page](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) for more details. this way you have full control on reading and writing files. This is the approach other build system extensions like [grunt-ts](https://github.com/TypeStrong/grunt-ts) and [gulp-typescript](https://github.com/ivogabe/gulp-typescript) are doing for instance.

**Comment by jakepetroules** [comment]
I think using the compiler API is probably the best solution for my use case. Here's what I've come up with for that:

```typescript
import ts = require("typescript");

declare var process: any;

export namespace io.qt.qbs {
    export class Artifact {
        filePath: string;
        fileTags: string[];
    }

    export namespace tools {
        export namespace utils {
            function stringEndsWith(s: string, e: string) {
                return s.slice(-e.length) === e;
            }

            export function artifactFromFilePath(filePath: string): Artifact {
                var fileTags: string[] = [];
                if (stringEndsWith(filePath, ".js.map")) {
                    fileTags.push("source_map");
                } else if (stringEndsWith(filePath, ".js")) {
                    fileTags.push("js", "compiled_typescript");
                } else if (stringEndsWith(filePath, ".d.ts")) {
                    fileTags.push("typescript_declaration");
                }

                return { filePath: filePath, fileTags: fileTags };
            }
        }

        function compileInternal(fileNames: string[], options: ts.CompilerOptions): qbs.Artifact[] {
            var outputArtifacts: qbs.Artifact[] = [];
            var program = ts.createProgram(fileNames, options);
            var emitResult = program.emit(undefined, filePath => {
                outputArtifacts.push(utils.artifactFromFilePath(filePath));
            });

            var allDiagnostics = ts.getPreEmitDiagnostics(program).concat(emitResult.diagnostics);
            allDiagnostics.forEach(diagnostic => {
                var message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
                if (diagnostic.file) {
                    var { line, character } = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
                    console.error(`${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`);
                } else {
                    console.error(message);
                }
            });

            return emitResult.emitSkipped ? undefined : outputArtifacts;
        }

        export function compile(commandLineArguments: string[]): qbs.Artifact[] {
            var parsedCommandLine = ts.parseCommandLine(commandLineArguments);
            return compileInternal(parsedCommandLine.fileNames, parsedCommandLine.options);
        }

        export function TypeScriptCompilerScannerToolMain(): void {
            var outputArtifacts = compile(process.argv.slice(2));
            if (outputArtifacts !== undefined) {
                console.log(JSON.stringify(outputArtifacts));
            } else {
                process.exit(1);
            }
        }
    }
}

io.qt.qbs.tools.TypeScriptCompilerScannerToolMain();
```

Thanks for your help!

**Comment by mihailik** [comment]
@mhegazy just curious, this analysis of compiler inputs seems to have a flaw: you miss `/// <references/>` and `imports` for example.

Does your msbuild logic include a mini-parser to fish files for such sub-strings?

**Comment by mhegazy** [comment]
Nope :) it is an approximation. Turns out most msbuild users list files in their project file, as they use VS for other features. So the input list is usually exhaustive; but again it is not 100% correct.

**Comment by paulvanbrenk** [comment]
Working on an implementation which would emit the files in a plain list to the console.
