### ISSUE TITLE
call hierarchy shows full file paths

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#36511]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.0-dev.20200128

**Search Terms**
- call hierarchy
- provideCallHierarchyIncomingCalls

/cc @rbuckton 

---

re https://github.com/microsoft/vscode/issues/89386

* use ts3.8-beta
* show callers of [mergeSort](https://github.com/microsoft/vscode/blob/a47886c5daa748b413fefbf45acb82c0700b2c7d/src/vs/base/common/arrays.ts#L94)
* :bug: some entries show as full file paths, instead they should be folder/project relative

<img width="1270" alt="Screenshot 2020-01-29 at 15 14 00" src="https://user-images.githubusercontent.com/1794099/73364180-608dca00-42aa-11ea-901a-e1cfcac8969b.png">

**Comment by mjbvz** [comment]
Here's the response that causes this:

```
Trace  - 19:46:11.735] <semantic> Response received: provideCallHierarchyIncomingCalls (138). Request took 120 ms. Success: true 
Result: [
    {
        "from": {
            "name": "/Users/matb/projects/vscode/src/vs/base/test/common/arrays.test.ts",
            "kind": "module",
            "file": "/Users/matb/projects/vscode/src/vs/base/test/common/arrays.test.ts",
            "span": {
                "start": {
                    "line": 1,
                    "offset": 1
                },
                "end": {
                    "line": 347,
                    "offset": 1
                }
            },
            "selectionSpan": {
                "start": {
                    "line": 1,
                    "offset": 1
                },
                "end": {
                    "line": 1,
                    "offset": 1
                }
            }
        },
        "fromSpans": [
            {
                "start": {
                    "line": 49,
                    "offset": 53
                },
                "end": {
                    "line": 49,
                    "offset": 62
                }
            },
            {
                "start": {
                    "line": 55,
                    "offset": 36
                },
                "end": {
                    "line": 56,
                    "offset": 1
                }
            },
            {
                "start": {
                    "line": 68,
                    "offset": 31
                },
                "end": {
                    "line": 68,
                    "offset": 40
                }
            },
            {
                "start": {
                    "line": 70,
                    "offset": 30
                },
                "end": {
                    "line": 70,
                    "offset": 39
                }
            },
            {
                "start": {
                    "line": 99,
                    "offset": 64
                },
                "end": {
                    "line": 99,
                    "offset": 73
                }
            }
        ]
    },
    ...
```

**Comment by rbuckton** [comment]
@jrieken, @mjbvz: Isn't this supposed to be handled by `asRelativePath` here: https://github.com/microsoft/vscode/blob/d91ca067cab6a9a52ba07feb50c9c800d0891552/extensions/typescript-language-features/src/features/callHierarchy.ts#L79-L81?

**Comment by rbuckton** [comment]
Related discussion: https://github.com/microsoft/TypeScript/issues/31863#issuecomment-554261674

**Comment by jrieken** [comment]
Yeah, should be... Unsure if the file doesn't match the workspace path because of "path formatting" issues?

**Comment by mjbvz** [comment]
Fixed for me in the current VS code code base using TS 3.9-nightly

<img width="452" alt="Screen Shot 2020-04-09 at 7 34 05 PM" src="https://user-images.githubusercontent.com/12821956/78957082-235b6a80-7a99-11ea-8579-1f8e9b199b2f.png">

@jrieken Do you still see this issue?

**Comment by rbuckton** [comment]
@jrieken, @mjbvz has there been any further investigation on the VSCode side? I haven't been able to repro this on Windows. Was the original case discovered on an *nix operating system?

**Comment by andrewbranch** [comment]
Doesn’t repro for me on macOS either. The original screenshot was taken on macOS. Seems like this is fixed.
