### ISSUE TITLE
Bad call hierarchy highlights

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#36512]
*TS Template added by @mjbvz*

**Tested typeScript Version**: 3.8.0-dev.20200128

**Search Terms**
- Call hierarchy 
- provideCallHierarchyIncomingCalls
- fromSpans

/cc @rbuckton 

---

re https://github.com/microsoft/vscode/issues/89386

* invoke call hierarchy on [isFalsyOrWhitespace](https://github.com/microsoft/vscode/blob/3f1a2f690ae5b0dc192ef1a233a7c1c9cb8360ff/src/vs/base/common/strings.ts#L9)
* the resolve-child and likely others have broken highlights

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1794099/73363507-2a037f80-42a9-11ea-8ffa-5fa6aa53568a.png">

**Comment by mjbvz** [comment]
Here's the result of one of the incoming calls to `mergeSort` in the VS Code code base:

```
  {
        "from": {
            "name": "applyEdits",
            "kind": "function",
            "file": "/Users/matb/projects/vscode/src/vs/base/common/jsonEdit.ts",
            "span": {
                "start": {
                    "line": 158,
                    "offset": 1
                },
                "end": {
                    "line": 177,
                    "offset": 2
                }
            },
            "selectionSpan": {
                "start": {
                    "line": 158,
                    "offset": 17
                },
                "end": {
                    "line": 158,
                    "offset": 27
                }
            }
        },
        "fromSpans": [
            {
                "start": {
                    "line": 238,
                    "offset": 98
                },
                "end": {
                    "line": 239,
                    "offset": 8
                }
            }
        ]
    },
```

The `jsonEdit.ts` file only has 182 lines so I'm not sure where the `fromSpans` are coming from.

**Comment by mjbvz** [comment]
@rbuckton @RyanCavanaugh Can we please investigate this for TS 3.8 (either for the final 3.8 release or for a 3.8.x recovery build that VS code would be able to pick up)

**Comment by rbuckton** [comment]
My bad, I should have included this as fixed by https://github.com/microsoft/TypeScript/pull/36559. It will be in the 3.8 RC.
