### ISSUE TITLE
Cyan color of ts.formatDiagnosticsWithColorAndContext is hard to read on white background

### ISSUE THREAD

**Issue by gempain** [microsoft/TypeScript#36519]
## Search Terms

- colors

## Suggestion

Darken cyan color used by `ts.formatDiagnosticsWithColorAndContext` as it is currently hard to read on a white background.

## Use Cases

I am having this problem when debugging Angular CLI errors. File names are hardly readable. I was redirected here after I filed [an issue](https://github.com/angular/angular/issues/34990) to their repository. I haven't verified this scientifically using contrast checkers, but I'm pretty sure it wouldn't pass:
![Screenshot 2020-01-27 at 13 39 39](https://user-images.githubusercontent.com/13135149/73175570-ce02f480-410a-11ea-97d2-c03d03001462.png)

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Keep up the great work !

**Comment by RyanCavanaugh** [comment]
These are ANSI color references; we have no ability to tweak them (it's just "cyan", which terminals decide how they want to render in terms of an actual color). Your console program may have some option for changing how "cyan" is displayed. Pass `--pretty false` if you'd like no colorization at all.

**Comment by gempain** [comment]
Colorization is a very useful feature, turning it off would be worse than leaving it on as is. Couldn't you use [another ansi color](https://github.com/chalk/chalk#colors) ?
