### ISSUE TITLE
Web MIDI API

### ISSUE THREAD

**Issue by waterplea** [microsoft/TypeScript#36527]
## Search Terms

midi, web midi api

## Suggestion

Web MIDI API interfaces are missing in TypeScript:
https://www.w3.org/TR/webmidi

## Use Cases

Creating a web app working with MIDI requires these typings

## Examples

```
navigator.requestMIDIAccess()
  .then(access => {
    console.log(access.input) // <-- access: MIDIAccess
  });
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AviVahl** [comment]
https://www.npmjs.com/package/@types/webmidi

**Comment by waterplea** [comment]
Go it, thanks. So far only Chrome supports it. However it's been around for 5 years already, spec draft, as well as Chrome 43 are from 2015.

**Comment by MartinJohns** [comment]
If there's only one existing implementation, then it really shouldn't be added to the standard library definitions.

**Comment by ezequielramos** [comment]
> If there's only one existing implementation, then it really shouldn't be added to the standard library definitions.

Well, its supported by the most of the browsers now... Should we implement it?

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/requestMIDIAccess
