### ISSUE TITLE
tsserver exited unexpectedly

### ISSUE THREAD

**Issue by akosyakov** [microsoft/TypeScript#36528]
We are running tsserver in Gitpod Theia. And while working with very big monorepo, tsserver crashes. It does not happen always, but only when multiple files are opened from different packages and I trigger find references in one of them. I cannot share the full logs because source code is not open, but the last message in logs always:
```
Info 764  [9:26:46.489] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 765  [9:26:46.878] DirectoryWatcher:: Added:: WatchInfo: /home/gitpod/.cache/typescript/3.8/node_modules 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 766  [9:26:47.31] Elapsed:: 153ms DirectoryWatcher:: Added:: WatchInfo: /home/gitpod/.cache/typescript/3.8/node_modules 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
```

Also before the failure tsserver consumes a lot of CPU, but not much memory. htop shows 421% for CPU and 2.5% for memory. Logs don't have any other errors. I wonder what could be the cause of the crash? Could we change something in tsconfig to work it around? I've already tried to use latest and next versions but get the same issue.

**Comment by sheetalkamat** [comment]
Can you please share tsserver log using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code).

You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

If you need to you can share it privately as well at `shkamat at Microsoft dot com`

**Comment by sheetalkamat** [comment]
Also I think it could be that you are running into limitation of  #33287 but you mentioned that memory consumption isn't the issue so I am not sure.
