### ISSUE TITLE
Error assigning object with optional field to variable with required type after checking for undefined

### ISSUE THREAD

**Issue by jtvd78** [microsoft/TypeScript#36536]
**TypeScript Version:**  3.7.5

**Search Terms:** assign optional undefined required

**Code**

```ts
type Type = {
    a?: string,
    b?: string,
}

type ARequired = Type & {
    a: string
};

const test: Type = {
    a: "a",
}

if (test.a !== undefined) {
    const req: ARequired = test;        // Error: Type 'undefined' not assignable to type 'string'
    const req2 = {... test, a: test.a}  // Compiles
}
```

**Expected behavior:**

No error when assigning `test` to `req`

**Actual behavior:**

Error when assigning `test` to `req`

**Playground Link:** http://www.typescriptlang.org/play/#code/C4TwDgpgBAKu0F4oG8BQUNQIYH4BcUAzsAE4CWAdgOYA06mARvkaZbagL6qqiRQCCAJQgBHAK5kSEACZQkcPgDIU9DFgLFy1TgG5uAYwD2FYlGARiBBYhWZsBAERYHdLqjIAzKAApzxAHRYUACECEhiFNIQHpQyAJSoaHZGJsBQUiIEQqISUrJIfsA6dnYA9KVQAKIkJIYkVvBQAOQRUTEUMk1QFIZpWISEZFQUWAwANtDAhmaNTZpsTapQKaYZAExyKP7bZhbANPa7AVgcGOVQAMKGALZgZBOEnEA

**Comment by AnyhowStep** [comment]
```ts
const req: ARequired = test;
test.a = undefined;
console.log(req.a); //undefined
```

**Comment by jtvd78** [comment]
Ahh yes, mutability. Is there a way to force immutability on `a` so that this assignment works?

**Comment by AnyhowStep** [comment]
You could just add a cast, if all else fails
