### ISSUE TITLE
NumberFormatOptions is missing several options including notation

### ISSUE THREAD

**Issue by benmccann** [microsoft/TypeScript#36533]
`notation` is missing from `NumberFormatOptions`

https://github.com/microsoft/TypeScript/blob/91ffa1c752ac26882b1426fb4c9012701c1d908e/lib/lib.es5.d.ts#L4236 

**TypeScript Version:**  3.7.5

**Search Terms:** NumberFormatOptions notation

**Code**

```ts
const str = new Intl.NumberFormat(undefined, {notation: 'scientific'}).format(100000);
```

https://github.com/chartjs/Chart.js/blob/5f24b97bbfff52975c801b0a0b8880b2aa3b0a6a/src/core/core.ticks.js#L57

**Expected behavior:**

I should be able to use NumberFormat's notation option. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Actual behavior:**

src/core/core.ticks.js(57,43): error TS2345: Argument of type '{ notation: string; minimumFractionDigits: number; maximumFractionDigits: number; }' is not assignable to parameter of type 'NumberFormatOptions'.

**Playground Link:** None

**Related Issues:** None

**Comment by MartinJohns** [comment]
Commonly the TypeScript team does not add experimental APIs to the standard library definitions.

You can use [Declaration Merging](http://www.typescriptlang.org/docs/handbook/declaration-merging.html) to extend the types yourself. There's probably also a npm package out there that does this for you.

**Comment by benmccann** [comment]
Thanks!

**Comment by maneetgoyal** [comment]
@MartinJohns `notation` is not experimental anymore. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/NumberFormat

Can this issue be reopened or I can create a new one if preffered?

**Comment by Plortinus** [comment]
> @MartinJohns `notation` is not experimental anymore. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/NumberFormat
> 
> Can this issue be reopened or I can create a new one if preffered?

same need +1

**Comment by NarasimhaReddyY** [comment]
@benmccann Any workaround for this for now?

**Comment by germain-receeve** [comment]
> @benmccann Any workaround for this for now?

                const shortAmount = new Intl.NumberFormat(undefined, {
                  //@ts-ignore
                  notation: "compact",
                  compactDisplay: "short"
                }).format(parseInt(value));

I think the only solution for now is to add a `ts-ignore` until the types definitions are updated.

**Comment by vinayakkulkarni** [comment]
I get the same error in `toLocaleString()` as well:

```ts
function getFormattedDistance(distance: number): string {
  return distance.toLocaleString('en-US', {
    style: 'unit',
    unit: 'kilometer',
    unitDisplay: 'narrow',
  });
}
```

```sh
Argument of type '{ style: string; unit: string; unitDisplay: string; }' is not assignable to parameter of type 'NumberFormatOptions'.ts(2345)
```

**Comment by christianjtr** [comment]
I think is related to the TS version/config, I've tested in TypeScript TS Playground and then in my current project with this config:

- Typescript version: v4+. 
- Target: ES2020, 
- Module: ESNext.

And everything went ok.

Hope this helps.

**Comment by eugene-g13** [comment]
'trailingZeroDisplay' does not exist in type 'NumberFormatOptions'.ts(2769)

**Comment by EIQfrans** [comment]
> 'trailingZeroDisplay' does not exist in type 'NumberFormatOptions'.ts(2769)

https://stackoverflow.com/questions/31816061/why-am-i-getting-an-error-object-literal-may-only-specify-known-properties

```
const formatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    trailingZeroDisplay: 'stripIfInteger'
} as Intl.NumberFormatOptions);

const price = formatter.format('500000.25'); // output: $500,000.25
```

**Comment by BlueManCZ** [comment]
I resolved this error by changing lib and target to `ES2023` in tsconfig.
