### ISSUE TITLE
Compiler Options wiki: separateCompilation has weird description

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#3653]
[Compiler Options](https://github.com/Microsoft/TypeScript/wiki/Compiler%20Options)
> --separateCompilation
> Unconditionally emit imports for unresolved files.

Is it really the meaning of this option? You'd never guess!

**Comment by DanielRosenwasser** [comment]
We had a very hard time trying to name this option. See #2499. Actually, in #3208, this was renamed to `--isolatedModules`. 

I just fixed it, but in the future, you can send a PR/file an issue on [TypeScript-wiki](https://github.com/Microsoft/TypeScript-wiki). Does that more or less address what you had in mind?

**Comment by mhegazy** [comment]
Thanks @mihailik

**Comment by mihailik** [comment]
Thanks a lot, the links create a perfect context. Pieces fall into their places.
