### ISSUE TITLE
Type narrowing loses explicit type, forces me to re-cast to explicit type

### ISSUE THREAD

**Issue by fefrei** [microsoft/TypeScript#36530]
**TypeScript Version:**  3.8-Beta

**Search Terms:** Type narrowing explicit type lost concat

Sorry if this is a duplicate – I failed to find any related issues.

**Code**

```ts
type A = 1 | 2;

const one: A = 1;

[one].concat([2]); // type error
[one as A].concat([2]); // types alright
```

**Expected behavior:** TypeScript's type narrowing is super useful, but here, I stumbled about a case where it introduces a type error, forcing me to manually re-assert my original type. I'd expect that the program above is typed correctly…

**Actual behavior:** …but TypeScript infers (correctly) that `one` has type `1`, which is more specific than `A`. Unfortunately, this means I no longer can `concat` something of type `A[]` (or `[2]`) to it, I have to explicitly re-cast `one` to its original type.

I'm not sure whether this qualifies as a bug or a suggestion – either way, it's sad, and I'd like for this to change.

**Playground Link:** https://www.typescriptlang.org/play/index.html?ts=3.8-Beta#code/C4TwDgpgBAglC8UCMUA+UBMBuAUDgxgPYB2AzsFCRAFywLK44DaVAugHRHH4CGwAFEwysAlFigB6CVFCQoEAE4LCC5lSg9SsDl14Cho8VJngIWngBsFASwDmAC2A4gA

**Related Issues:** Couldn't find any 🤔

**Comment by jcalz** [comment]
Duplicate of #8513, related to #8010.  

If you want an assignment of a value to a union-typed variable not to be control-flow-analysis narrowed by the value's type, you should type-assert the value to the union type before the assignment.  In your case you could write `const one: A = 1 as A` or the simpler `const one = 1 as A`:

```ts
type A = 1 | 2;
const one = 1 as A;
[one].concat([2]); // okay
```
[Playground](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAglC8UCMUA+UBMBuAUAYwHsA7AZ2CmOkRQEMTZcBtSgXQDpCi8bgAKRjCwCUWKAHoxFANY0QOKEA)

**Comment by fefrei** [comment]
Thanks! This indeed is a duplicate.

Using `as` in the declaration helps, but unfortunately this means I lose type checking of the initial assignment (which of course becomes more relevant for more complex types). It looks like there is no way to prevent the narrowing that is type safe and does not repeat the type (risking an inconsistent change by a careless future me).

I think in this case, a better solution is to move the cast to the empty array (which makes more sense if `[2]` is a more complex thing, as in my actual code):

```
type A = 1 | 2;
const one = 1;
([] as A[]).concat([one], [2]); // OK
```

…but this solution is specific to this example.

Either way, thanks!; and I hope TypeScript will get a more useful solution for this in the future.

**Comment by jcalz** [comment]
You can get type checking back with a helper function like this:
```ts
const annotatedAs = <T>(t: T) => t;
```
Then you manually specify `T` when you call `annotatedAs()`:

```ts
let one = annotatedAs<A>(1); // okay
[one].concat([2]); // okay

let three = annotatedAs<A>(3); // error!
//  ---------------------> ~
// Argument of type '3' is not assignable to parameter of type 'A'
```
[Playground link](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAglC8UCMUA+UBMBuAUDgxgPYB2AzsFAIbHGHCXAQAmMpCUAPACoB8AFMABcULgEoEPKMFw4ANhAoloiarXqMWpDjH5JRWKAHpDUQgGtKIHAG0lAXQB0RYvgZ9rGO-qMnzlvPIUwAAWAE4QylQ0dAzMrNr8AMzexlAQoaGEoQCEOKlQALRFxSWlZZIAfnkmMKEA5gCuALYQxIoAZlLg0ADkiT1QAJZsalSkpIN1xJQARvJShFBglKGULYyhpp2gkFA9MANAA)

That is both type-safe and doesn't repeat the type.  If you want to see something built into the language here, you might want to go to #7481 and give it a 👍.  Maybe this is even a duplicate of #7481.

**Comment by fefrei** [comment]
**Thank you!** This is nice and feels like a proper solution.
I'll add my voice at #7481.
