### ISSUE TITLE
Clarify whether glob patterns like *.* can be used for tsc.js and tsconfig.json

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#3654]
Several PRs/issues address globbing, but the [tsconfig.json docs](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) and [schema](http://json.schemastore.org/tsconfig) are not up to date.

#3232 Adds glob-style pattern matching for file specifications using new "include" property in tsconfig.json **(unmerged)**

#3188 Support "exclude" property in tsconfig.json **(merged 16th of May)**

[#916](https://github.com/Microsoft/TypeScript/pull/916)

(and others)

**Comment by DanielRosenwasser** [comment]
2 of those haven't been merged yet, one won't be out until 1.6, and 1.5 isn't even out yet.
