### ISSUE TITLE
[loc][Query][TypeScript] Localizability of 0; "TypesInstallerInitializationErrorMessage"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/TypeScript#36545]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Thanks in advance for the reply

Source:
Failed to initialize Automatic Type Acquisition. This might cause poor IntelliSense in your JavaScript/TypeScript files. See {0} for more information. Error: {1}

File Name:
LanguageService\TypeScriptLanguageService\Windows\bin\Release\localize\ENU\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll

Resource ID:
0; "TypesInstallerInitializationErrorMessage"

Query:
Please clarify the meaning of "poor IntelliSense". Does "poor" mean "incorrect"?

0; "TypesInstallerInitializationErrorMessage"
0; "TypingsInstallErrorMessage"

**Comment by RyanCavanaugh** [comment]
"poor" here means "of low quality" or "worse than is usual or expected"
