### ISSUE TITLE
__extends (and friends) should be emitted withing the `System.register` call when targeting System

### ISSUE THREAD

**Issue by ttowncompiled** [Microsoft/TypeScript#3655]
Using this contrived example again,

Export file with super class:
```typescript
/// foo.ts
export class Foo {
  a: string;
}
```
Import file with sub class:
```typescript
/// bar.ts
import {Foo} from './foo';

export class Bar extends Foo {
  b: string;
}
```
System.register format output:
```javascript
/// bar.js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};System.register(['./foo'], function(exports_1) {
    var foo_1;
    var Bar;
    return {
        setters:[
            function (_foo_1) {
                foo_1 = _foo_1;
            }],
        execute: function() {
            Bar = (function (_super) {
                __extends(Bar, _super);
                function Bar() {
                    _super.apply(this, arguments);
                }
                return Bar;
            })(foo_1.Foo);
            exports_1("Bar", Bar);
        }
    }
});
```
The output of System.register contains no namespace. This is not valid System.register bundle format output. When we bundle our files, our bundle will be broken with this output. To adhere to proper bundle format, the output would need to be:
```javascript
/// bar.js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};System.register('bar', ['./foo'], function(exports_1) {
    var foo_1;
    var Bar;
    return {
        setters:[
            function (_foo_1) {
                foo_1 = _foo_1;
            }],
        execute: function() {
            Bar = (function (_super) {
                __extends(Bar, _super);
                function Bar() {
                    _super.apply(this, arguments);
                }
                return Bar;
            })(foo_1.Foo);
            exports_1("Bar", Bar);
        }
    }
});
```
Notice that the System.register call now has a namespace which matches the name of the file.
This would help Angular out a lot.

Thanks for all the hard work guys!

**Comment by dalcib** [comment]
1+

**Comment by mhegazy** [comment]
The problem is choosing the name. should this file be called "Bar" or "mymodules\bar" or something else.. the correct path is to use https://github.com/systemjs/builder to build your bundles. we are working on adding TypeScript support in the next release.

**Comment by basarat** [comment]
One could potentially leverage something like what we have for amd `/// <amd-module name="Foo"/>`. Although I've always advised against it :) and like that its an undocumented feature.

**Comment by mhegazy** [comment]
Just to clarify, the issue we are tracking here is making sure that `__extends` is emitted inside the body of the register call.

**Comment by RichiCoder1** [comment]
Is it? I'm reading this as a namespace issue. `__extends` just seems related.

**Comment by mhegazy** [comment]
The module name issue should be handled by the builder(see https://github.com/Microsoft/TypeScript/issues/3655#issuecomment-117796197), We have a workitem to get this done for 1.6,

**Comment by guybedford** [comment]
Note anonymous `System.register` output as it is doing should always be the default, with names optional only for creating bundles.

There is another issue here actually, and that is that code outside of the `System.register` closure statement is not strictly supported by the format. It runs in a global scope, so will leak variables declared here onto the global object which isn't ideal. It also messes with SystemJS's format detection which assumes a `System.register` module will have that as the first code in the file, not the helper definitions.

**Comment by guybedford** [comment]
(note the above explains the multiple anonymous System.register statements issue - it's not detecting the file as a System.register format due to this extra code)

**Comment by guybedford** [comment]
The suggested fix would be to output:

```javascript
System.register(['./foo'], function(exports_1) {
/// bar.js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
    var foo_1;
    var Bar;
    return {
        setters:[
            function (_foo_1) {
                foo_1 = _foo_1;
            }],
        execute: function() {
            Bar = (function (_super) {
                __extends(Bar, _super);
                function Bar() {
                    _super.apply(this, arguments);
                }
                return Bar;
            })(foo_1.Foo);
            exports_1("Bar", Bar);
        }
    }
});
```

**Comment by dalcib** [comment]
@guybedford  In some cases this can be useful even out of creating bundles.
For example in [Meteor](www.meteor.org), with anonymous modules, all files are reload again by *xhr* in Systemjs.
Only in production mode the files are bundled.

Today it is solved by [meteor-angular2-typescript](https://github.com/netanelgilad/meteor-angular2-typescript/blob/master/plugin/handler.js) package with this code:
 ```
var tsFile = compileStep.read().toString('utf8');
var output = typescript.transpile( tsFile, { module : typescript.ModuleKind.System });
var moduleName = compileStep.inputPath.replace('.ts','');
output = output.replace("System.register([",'System.register("'+moduleName+'",[');
```

**Comment by vladima** [comment]
in TypeScript 1.5 [`transpile` function](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L1773) has parameter `moduleName` for this exact purpose.

**Comment by guybedford** [comment]
Any update on having the helper functions included within the `System.register` wrapper here? From a SystemJS perspective this is one of the last remaining major issues I believe.

**Comment by mhegazy** [comment]
Should have it in a release before the end of the week.

**Comment by mhegazy** [comment]
The change should be in the `typescript@next` release later tonight.

**Comment by guybedford** [comment]
Awesome, I'm going to be doing some testing very soon, hoping to add a little more polish to these workflows to hopefully make things slightly easier all around.

**Comment by dashaus** [comment]
It works! Thanks you!

**Comment by pkozlowski-opensource** [comment]
@vladima sorry for commenting on a closed issue but the way I understand [your comment](https://github.com/Microsoft/TypeScript/issues/3655#issuecomment-124263773) it should be possible to use the `moduleName`  option to have a non-anonymous System.register module. That is, based on this config:

```javascript
 var compileResult = ts.transpile(content, {
            module: ts.ModuleKind.System,
            moduleName: 'foo'
});
``` 

I would expect to get `System.register('foo', ['angular2/angular2'], function(exports_1)` but I'm getting (with typescript@next): `System.register(['angular2/angular2'], function(exports_1)`

Is there any additional compiler switch that needs / should be used?

**Comment by vladima** [comment]
@pkozlowski-opensource I've posted the answer in #4801
