### ISSUE TITLE
assertion signature with primitive union: resulting type too narrow

### ISSUE THREAD

**Issue by NaridaL** [microsoft/TypeScript#36574]
**TypeScript Version:**  3.7.5, 3.8.0-dev.20200201

**Search Terms:**
assertion signature

**Code**

```ts
interface Foo {
    action(): void
    bar?: string
}

declare function assertFooBar(foo: any): asserts foo is ((Foo & { bar: string })|true)

declare const x: Foo | true
assertFooBar(x)

const y = x
```

**Expected behavior:**
`y` has type `(Foo & { bar: string }) | true`

**Actual behavior:**
`y` has type `true`.

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200201&ssl=11&ssc=12&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHKJjDogAUAlAFzIBu6wAJvoQEZxQD8tAzmFFABzXAF9cuJhAQAbTihgBXEAhJkivXtDAZ0AIU7kYmWnBABPGhq1QwvZMazB75cruQAyHMg5Q+A4WRRSgAfAUUISgkpWXlkBDJ+ZAAPWncQ5HCIXDhNbV0DKHJkqNwEkCTzZABeFIkwcwAHFAAVGuRXN0xPb19-QRAhIMpkDKzKEa8urDGoCNKG5uQADXbdAHVgMAALQoAedMy5iAA+ZHqmlA2t3c49lrPatohkyBAme3cuNG6vbB9OP1AqJkLQWrhFldMJsdoUAIIWNbQm77MzmE64IA
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate of #35953

**Comment by NaridaL** [comment]
@RyanCavanaugh Yeah, I was half expecting this to be by design due to some type system subtlety. Thanks in any case.
