### ISSUE TITLE
How to declare method that exists in a base class ?

### ISSUE THREAD

**Issue by rogergl** [Microsoft/TypeScript#3657]
I'm using ember with typescript and I'm trying to provide the necessary type hints. The problem is that I can't figure out how to declare the get method in my interface. If I add a get declaration to RouteObj I get:  Property 'get' is missing in type, which makes sense since I haven't declared it, but get is a member of a base class, which TypeScrip doesn't know.

The source is:
```javascript
/// <reference path="./../../../typings/my_typings.d.ts" />

import Ember from 'ember';

export default Ember.Route.extend({

    barcode: Ember.inject.service(),

    actions: {

        scan: function() {

            this.get('barcode').scan().then(() => {
                this.transitionTo('scale');
            }, error => {
                alert("Scanning failed: " + error);
            });

        }

    }

});
```

The type declaration is:
```javascript
declare module 'ember' {

    interface RouteObj {
        model?: () => any;
        actions?: {
            [index: string]: () => any;
        }
        [index: string]: any;
    }

    class Route {
        extend(obj: RouteObj): any;
    }

    class Service {
        service(): any;
    }

    class Ember {

        static Route: Route;
        static inject: Service;
        static set(object: any, field: string, value: any): any;

    }

    export default Ember;

}
```

**Comment by mhegazy** [comment]
The problem is the 'extend` method is defined to return `any`. that means that the compiler does not know anything about the shape of the output. Disclaimer, I do not know much about Ember to be able to help much; looking at other ember extend declarations, e.g.:  https://github.com/borisyankov/DefinitelyTyped/blob/master/ember/ember.d.ts#L1001 you would want to define extend function as a generic function and pass an explicit type parameter:

```ts
   class Route {
        extend<T>(obj: RouteObj): T;
    }
```
```ts
declare class MyObject extends Ember.Route {
    // assuming this is how you would want to access the get method later on
    get(s:"barcode"): Ember.Service;
    get(s:string"): any;
}

export default Ember.Route.extend<MyObject>({
 ....
});
```
