### ISSUE TITLE
TSC: --composite documented as CLI option but generates TS6064 error

### ISSUE THREAD

**Issue by JasonGore** [microsoft/TypeScript#36588]
**TypeScript Version:**  3.7.5, 3.8.0-dev.20200201

**Search Terms:**
TS6064 composite cli option

**Code**

* `npm install -g typescript`
* `tsc --composite`

**Expected behavior:**

No error since option is [documented as a CLI option](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Actual behavior:**

```
λ tsc --composite
error TS6064: Option 'composite' can only be specified in 'tsconfig.json' file.
```

**Comment by orta** [comment]
You can now use it from the CLI: https://github.com/microsoft/TypeScript/issues/36917#issuecomment-592136968
