### ISSUE TITLE
performanceData.updateGraphDurationMs missing from protocol.d.ts

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36589]
**TypeScript Version:**  3.8.0-dev.20200201

**Search Terms:**
- tsserver
- `protocol.d.ts`

**Bug**
Looks like `performanceData.updateGraphDurationMs` is currently missing from the server protocol definitions (`protocol.d.ts`)

**Related issues**
#35675

/cc @amcasey

**Comment by amcasey** [comment]
Not fixed by https://github.com/microsoft/TypeScript/pull/36210?

**Comment by amcasey** [comment]
Looks like it's internal.  I think I/we did that because it didn't seem to be of general interest, but I don't know our usual convention for such things.  I guess I'll make a PR promoting it to public and see what people think.

**Comment by mjbvz** [comment]
Sounds good. Right now VS Code has to define this property. Better if it can come from the TS server definitions even if VS Code and VS are the only consumers of it
