### ISSUE TITLE
Extra await inserted when accepting suggestion

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36596]
From https://github.com/microsoft/vscode/issues/89879

**TypeScript Version:**  3.8.0-dev.20200201

**Search Terms:**

**Repo**
For the code:

```ts
import * as util from 'util';
import * as fs from 'fs';

const readFile = util.promisify(fs.readFile);

async function foo() {
    const includedContents = await readFile('x').
}
```

Trigger suggestions after the `.` in `foo`. Accept a suggestion

**Bug:**
An extra `await` is inserted:

```ts
async function foo() {
    const includedContents = await (await readFile('x')).BYTES_PER_ELEMENT
}
```

**Comment by RyanCavanaugh** [comment]
This isn't extra, because the `await` you inserted has nothing to do with the prior `await`. It's the same as if you had written
```
import * as util from 'util';
import * as fs from 'fs';

const readFile = util.promisify(fs.readFile);

async function foo() {
    const includedContents = 1 + readFile('x').
}
```
We wouldn't erase the `1 +` here; the `await` has the same syntactic positioning in this case.
