### ISSUE TITLE
Document a way to determine class at runtime (reflection)

### ISSUE THREAD

**Issue by drudru** [Microsoft/TypeScript#3660]
Typescript generates standard JavaScript and erases the types in the generated code. I think this is fine, but for many dynamic programs, there is a need to process a heterogeneous collection. In that situation, the ability to easily determine the class of an instance at run-time is a requirement.

A solution or best practice for his does not appear to be specified or described in the Handbook or Specification. When I search on the net with the phrase "typescript reflection class name", the top answers refer to a technique that uses a regexp on the string form of the function definition. That is not a good solution.

When I search on "ES6 class name", there is the method of using the instance.constructor.name == 'ClassName' technique. A quick test in the console showed that this worked for me, but I didn't consider testing all of the cases. I find that a little verbose, but it may be part of the standard. Also, completion in the editor may make this a non issue.

I think the official documentation should cover this topic and the current approved way of determining class at run-time. I would contribute patches to the docs, but I'm not 100% sure what the right answer is.

**Comment by DanielRosenwasser** [comment]
Thanks @drudru, I've filed https://github.com/Microsoft/TypeScript-Handbook/issues/52, not sure if that's exactly what you had in mind.

**Comment by mhegazy** [comment]
Classes are compiled to functions. if you are in a engine that supports [function.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) iinstance.constructor.name should work. if you are on an older browser, you can use a pollyfill for function.name, e.g. corejs, (implementation here: https://github.com/zloirock/core-js/blob/master/modules/es6.function.name.js)

**Comment by drudru** [comment]
Ok - thx 

@DanielRosenwasser - thanks for filing that to the Handbook
