### ISSUE TITLE
noImplicitAny allows type changing for non-typed variable declaration

### ISSUE THREAD

**Issue by artaommahe** [microsoft/TypeScript#36600]
**TypeScript Version:**  3.7.5

**Code**

```ts
let smth; // any
smth = 1; // any
console.log(smth); // number
smth = 'afas'; // any
console.log(smth); // string
```

**Expected behavior:**
error at second assignment due to determined `number` type

**Actual behavior:**
no error

**Playground Link:** https://www.typescriptlang.org/play/#code/DYUwLgBAzgtmAWBuAULBEC8ECMKDGA9gHZQGgB0wBA5gBRrwCUKDmEA5AIYBmnU7+YqQpU6DZkA

**Comment by dragomirtitian** [comment]
This is the intended behavior. Typescript is pretty good at tracking types through control flow analysis. If you were to access the variable without and assignment or in an inconsistent way, you would get an error:

```ts
let smth;
smth.test() // error 
smth = 1;
smth.toExponential()
smth = 'afas';
smth.toExponential() // error 
```
[Playground Link](https://www.typescriptlang.org/play/?ssl=9&ssc=1&pln=1&pc=1#code/DYUwLgBAzgtmAWBuAULBA6MIpgBQEoIB6IiEAJ3IHtyJU54IBeCARhTXkyoFEAPAA5UAdiGFgAlgENgBegmYQA5FIBmUqEo4Nu-IaPHTZhEmUo06yZEA)
