### ISSUE TITLE
coerce string union to const enum if subset 

### ISSUE THREAD

**Issue by mattkrick** [microsoft/TypeScript#36605]
## Search Terms
coerce const enum string union TS2345 assignable to parameter

## Suggestion

when a const enum is a superset of a string union, i'd like the string union to satisfy the enum constraint

## Use Cases

External libraries can't use const enums, so they often export string unions.
In my project files, I prefer const enums because Color.PURPLE is so much nicer than a hex value. 
When a library provides a string union, I'd like to use it as a const enum.
The current way to do this is `(pet as unknown) as AnimalEnum`, which is a little verbose.

## Examples

```ts
// 3rd party lib
type Animal = 'dog' | 'cat'
const pet: Animal = 'dog'

// my project
const enum AnimalEnum {
  DOG = 'dog',
  CAT = 'cat'
}

const useTheEnum = (animal: AnimalEnum) => {}
useTheEnum(pet) // ES2345 please go away, the union satisfies the const enum, just coerce it
 ```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Some level of opacity as to the actual values of the enum is the intended behavior of string enums. If you just want a set of string values from which a regular matching string is assignable, you can use a string union instead.
