### ISSUE TITLE
Auto Complete does not work when project very large.

### ISSUE THREAD

**Issue by Dellybro** [microsoft/TypeScript#36616]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Use VSCode on a React Native project which has over 75000 files (including npm packages)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). 

If you still see the problem after installing that extension and restarting VS Code, can you please provide more information about your project? Number of JS/TS files for example? With the project open in VS Code, run `code-insiders --status` from the command line to get this info

**Comment by sheetalkamat** [comment]
Could this be fixed by #35733
