### ISSUE TITLE
error TS1206: Decorators are not valid here?

### ISSUE THREAD

**Issue by matthewjh** [Microsoft/TypeScript#3661]
Hi,

What's the problem here? I can't see it.

```javascript
@Provide(Log)
function getKarmaLoggerInstance() {
	return logger.create('preprocessor-x');
}
```
This produces the following compiler error:
```
error TS1206: Decorators are not valid here.
```

My only guess is that it's on a function, but aren't decorators supposed to be applicable to functions?

**Comment by robertbaker** [comment]
+1 Having a similar issue with master and using ng-decorate. Was working fine before.

TS1240: Unable to resolve signature of property decorator when called as an expression.
Supplied parameters do not match any signature of call target.

**Comment by DanielRosenwasser** [comment]
Decorators are not supported on function declarations. To quote #2249:

> * Decorating a function declaration is not allowed as it will block hoisting the function to the top of the scope, which is a significant change in semantics.
* Decorating function expressions and arrow functions are not supported. The same effect can be achived by applying the decorator function as `var x = dec(function () { });`
* Decorating function formal parameters is currently not part of the ES7 proposal.

**Comment by thariesl** [comment]
If somebody still gets this error after the solutions above:

This was my code: 
`@Effect()
constructor(private httpClient: HttpClient, 
                private actions$: Actions,
                private store: Store<fromRecipe.FeatureState>){
    }
    recipeFetch = this.actions$
        .ofType(fromRecipe.FETCH_RECIPES)
        .switchMap((action: fromRecipe.FetchRecipes) => {
            return this.httpClient.get<Recipe[]>('https://https://course-recipe-book.firebaseio.com/recipes.json', {
                observe: 'body',
                responseType: 'json'
            })
        })`
and i got the Error: "Decorators are not valid here.

afterwards i simply wrote @Effect() after the constructor above recipeFetch :)
Worked for me.
