### ISSUE TITLE
TS importModuleSpecifier could work better for lerna monorepos with libs only

### ISSUE THREAD

**Issue by lgraziani2712** [microsoft/TypeScript#36624]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.0

**Search Terms**
- importModuleSpecifier
- auto import
- mono repo / monorepo

---

Related issue: https://github.com/microsoft/TypeScript/issues/36181 (I thought was something related to TS itself, but maybe is not).

Right now, the `typescript.preferences.importModuleSpecifier` **auto** option only uses relative paths for files nearer to the actual file than the `basePath` configuration file. But this isn't the best approach for a monorepo full with libs.

I only want to have aliases on imports from other lib folders, but I want to keep every import within a lib as relative imports. The problem is, VSCode suggestions sometimes adds the alias to imports within files of the same lib. When I build and publish everything as is, the service using that lib will crash because doesn't understand the alias.

Thank you in advance!

**Comment by mjbvz** [comment]
Moving upstream for feedback from TS team

**Comment by Ore4444** [comment]
I'm having the same issue.
`compilerOptions.baseUrl` in my project tsconfig is set to root of monorepo modules.
In every module tsconfig, I have: `compilerOptions.outDir = "lib"` and `compilerOptions.rootDir = "src"`
I don't have a `baseUrl` in module tsconfigs which is what causes the mismatch of relative imports (i have exactly the same symptoms as #36181).
If I add `compilerOptions.baseUrl = "src"` to a module tsconfig, it does solve the issue of doing move refactoring, but for some reason tsc fails with lots of TS2307. Now none of my `compilerOptions.paths` are resolved for that module.
The difference between baseUrl and no baseUrl can easily be verified by moving a folder or renaming a file with vscode.
Seems like when `compilerOptions.baseUrl` is set in a composite project, `compilerOptions.paths` of parent tsconfig stops having a effect.

**Comment by andrewbranch** [comment]
@Ore4444 what you’re describing sounds like a separate issue than the original post here. Are you able to provide an example repo demonstrating your problem?
