### ISSUE TITLE
"Error TS2576: Property is a static member of type" when calling static method on class from Set

### ISSUE THREAD

**Issue by dandv** [microsoft/TypeScript#36620]
**TypeScript Version:**  3.8.0-dev.20191105

**Search Terms:**
Error TS2576: Property ... is a static member of type ...

**Expected behavior:**
No errors.

**Actual behavior:**
Error:(30, 11) TS2339: Property 'represent' does not exist on type 'Animal'.

**Related Issues:**
#35024

**Code**
```ts
abstract class Animal { }

class Dog extends Animal {
  static represent() {
    console.log('Woof');
  }
}

class Cat extends Animal {
  static represent() {
    console.log('Meow');
  }
}

class Zoo {
  public static species: Set<Animal> = new Set();
  static add(animal: Animal) {
    Zoo.species.add(animal.constructor);
  }
}

const d1 = new Dog();
const d2 = new Dog();
const c1 = new Cat();
Zoo.add(d1);
Zoo.add(d2);
Zoo.add(c1);
for (const species of Zoo.species)
  species.represent();
```

I tried `(species as Animal).represent()` on the last line, after defining `static represent() { console.log('Some animal'); }` in `Animal` but I get the same error.

<details><summary><b>Output</b></summary>

```ts
class Animal {
}
class Dog extends Animal {
    static represent() {
        console.log('Woof');
    }
}
class Cat extends Animal {
    static represent() {
        console.log('Meow');
    }
}
class Zoo {
    static add(animal) {
        Zoo.species.add(animal.constructor);
    }
}
Zoo.species = new Set();
const d1 = new Dog();
const d2 = new Dog();
const c1 = new Cat();
Zoo.add(d1);
Zoo.add(d2);
Zoo.add(c1);
for (const species of Zoo.species)
    species.represent();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "strictNullChecks": false,
    "strictFunctionTypes": false,
    "strictPropertyInitialization": false,
    "strictBindCallApply": false,
    "noImplicitThis": false,
    "noImplicitReturns": false,
    "useDefineForClassFields": false,
    "alwaysStrict": false,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": false,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ESNext",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play/?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&target=99&ts=3.8.0-dev.20191105#)

**Comment by y-nk** [comment]
I'm not 100% confident, but I believe that `Zoo.species.add(animal.constructor);` is a problem. You defined `species` to be a `Set<Animal>` so you need to pass on an `Animal` _instance_ ; the constructor type is a function (?)

A way to solve your problem is to change `represent` **not to be** static and store animal instances inside `species`.

If you really want to keep `static`, i'd suggest to make species to be a `Set<function>` and store directly the `represent` function with something along `Zoo.species.add(animal.constructor.represent)` (i'm not sure about the proper way to access a static method from an instance) 

Also `(species as Animal).represent()` would target a non static method, so that's why it fails.

**Comment by dandv** [comment]
In case this is a YX problem, what I'm trying to do is record in
Zoo.species all unique classes derived from Animal that have been add-ed to
the Zoo, given that the `add` method can only receive instances of Animal
subclasses.

**Comment by y-nk** [comment]
> Zoo.species all unique classes derived from Animal that have been add-ed to
the Zoo, given that the `add` method can only receive instances of Animal
subclasses.

Then your species set cannot be of type Animal, since it refers to an instance of an Animal, and not its class.

**Comment by dandv** [comment]
> Then your species set cannot be of type Animal, since it refers to an instance of an Animal, and not its class.

I need the `species` set to be of type Animal, because I want to record the unique species (e.g. `Dog` and `Cat`, not unique animals. The transpiled JavaScript code works as intended - the set contains the constructor functions, and calling `represent()` in the `for` loop does call the correct static methods.

> I'm not 100% confident, but I believe that `Zoo.species.add(animal.constructor);` is a problem. You defined species to be a `Set<Animal>` so you need to pass on an `Animal` instance ; the constructor type is a function (?)

Good point. Since the way to obtain the class of an Animal instance is with [`animal.constructor`](https://stackoverflow.com/questions/48437284/get-intances-class-in-typescript/48437531#48437531), I've made `species` a `Set` of `any`. However, the [Error 2576](http://www.typescriptlang.org/play/?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&target=99&ts=3.8.0-dev.20191105&ssl=1&ssc=1&pln=30&pc=1#) persists.

**Comment by dandv** [comment]
@RyanCavanaugh: is it intended for the cast `(species as Animal).represent();` to still generate E2576, when `Animal.represent()` does not? If so, why is that the case?

**Comment by reforms** [comment]
It's work for me
```typescript
abstract class Animal { 
  ["constructor"]: Animal &  {represent(): void};
}

class Dog extends Animal  {
  static represent() {
    console.log('Woof');
  }
}

class Cat extends Animal {
  static represent() {
    console.log('Meow');
  }
}

class Zoo {
  public static species: Set<Animal["constructor"]> = new Set();
  static add(animal: Animal) {
    Zoo.species.add(animal.constructor);
  }
}

const d1 = new Dog();
const d2 = new Dog();
const c1 = new Cat();
Zoo.add(d1);
Zoo.add(d2);
Zoo.add(c1);
for (const species of Zoo.species)
  species.represent();
```
