### ISSUE TITLE
Use of private fields with noImplicitAny triggers TS7008 

### ISSUE THREAD

**Issue by RomainMuller** [microsoft/TypeScript#36630]
**TypeScript Version:**  3.8.0-dev.20200205

**Search Terms:**
- "#private" noImplicitAny
- "#private" TS7008

**Code**

```js
// tsconfig.json (in "foo" and "bar" modules)
{
  "compilerOptions": {
    "target": "ES2018",
    "noImplicitAny": true,
    "declaration": true
  }
}

```

```ts
// In module "foo", "index.ts"
export class Foo {
  readonly #bar: string = 'baz';

  public get bar() {
    return this.#bar;
  }
}
```

```ts
// in module "bar", "index.ts"
import { Foo } from 'foo';

new Foo();
```

**Expected behavior:**
I can declare private fields in classes exported by one package/module, and consume that from another package/module without issues.

**Actual behavior:**
The module that contains the private fields yields a `#private` declaration that triggers the `noImplicitAny` error when it's imported from the other module:
```ts
// "index.d.ts" in module "foo"
export declare class Foo {
    #private;
//  ~~~~~~~~ error TSC7008: Member '#private' implicitly has an 'any' type
    get bar(): string;
}
```

**Related Issues:** Similar to #6415, except with private-named fields.

**Comment by ajafff** [comment]
Simplified code which reproduces in the playground: http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200204&ssl=1&ssc=1&pln=3&pc=2#code/CYUwxgNghgTiAEkoGdnwMLwN4Ch7-gGIAHGAe2IG4cBfIA

```ts
declare class C {
    #prop;
}
```

PR incoming.

**Comment by DanielRosenwasser** [comment]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes.
