### ISSUE TITLE
Suggestion: add some mechanism to access properties with non-identifier characters in a fully type-safe way

### ISSUE THREAD

**Issue by fr0** [microsoft/TypeScript#36645]
## Search Terms

type safe bracket notation

## Suggestion

Consider the following interface:

```
interface Foo {
  prop_1: {value: number}|false;
  ['prop-1']: {value: number}|false;
}
```

`prop_1` can be accessed either by `foo.prop_1` (type safe) or `foo['prop_1']` (not type safe). The user has the opportunity to choose which one he/she wants.

However, there is no type-safe option where `prop-1` can be accessed; TypeScript (and JavaScript) only supports `foo['prop-1']`.

I don't know what the syntax should be, but it would be nice to express to the type checker that "I'm using bracket notation because the property isn't a standard identifier, not because I want you to ignore type checking".

## Use Cases

The back-end I am working with likes to use `dashed-names` for some fields, and they're serialized over JSON and deserialized as-is. I don't want the complexity of having to write a deserialization + serialization layer that converts them into `camelCase` or `underscore_case`. However, I'd still like type-safety.

## Checklist

Unknown. Depends on the solution.

**Comment by JacksonKearl** [comment]
What do you mean by not type-safe? The return value of the access will be typed appropriately and TS will error is there's a misspelling in the name of the property being accessed. 

https://www.typescriptlang.org/play/?ts=3.8-Beta#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyyADlOsQPoCMAXDgG5wA2ArhHSCwLYBG0AvgB94TAM4QA3ASIBtAOSlyAWipyAunWyNW7ZJ14DhzcVPz8CBACYQETOFBQJ0IUWGRw6GdKYJx5i4hV1ZABeZDkACwgmJnQ5C3wCJxc3EGcUML8FMkCAJnUCIA

**Comment by fr0** [comment]
You are correct - this was user-error. Closing this.
