### ISSUE TITLE
"tsc --project tsconfig.json --incremental" doesn't clean files from output folder.

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#36648]
**TypeScript Version:**  3.7.5

**Search Terms:**

tsc incremental doesn't clean old files

**Code**

N/A

**Expected behavior:**

When, for example, refactoring by renaming a file (and VS Code updates all import statements, etc), then the outputDir should not contain the old file.

**Actual behavior:**

The output directory contains old unused files.

Prior to trying incremental builds (today for the first time) I was simply doing `rm -rf dist/` to "clean" it first. This doesn't work with incremental builds (https://github.com/microsoft/TypeScript/issues/30602).

I tried running `tsc --build --clean` and `tsc --build ./tsconfig.json --clean` but those don't do anything, old files still remain in the output folder.

Note, I have a single tsconfig.json at the root of my project, and compile all my source code into a single output directory all at once with a single `tsc` command. I'm not "composing projects".

**Playground Link:** 

N/A

**Related Issues:** 

- https://github.com/microsoft/TypeScript/issues/30602
- https://github.com/Microsoft/TypeScript/issues/13722 - @mhegazy mentions there that we should add our clean step, but like I mentioned that doesn't play well with incremental builds. I believe TS should handle this somehow.

**Comment by sheetalkamat** [comment]
`tsc --build --clean` will only clean the files that are the outputs from current program so if you changed the name of the file or there exists some old file that's not part of the project' its output wont be deleted. For now this is by design and we do not track files that aren't part of compilation

**Comment by leotm** [comment]
It's because of VS Code's integrated Git support.

A right-click `Rename` does a `git mv` (`git rm --cached` + `mv` + `git add`).

Our TypeScript compiler only sees the `mv`.

Both being by Microsoft, it would be nice to see some support for this.

**Comment by trusktr** [comment]
>  For now this is by design and we do not track files that aren't part of compilation

Makes sense, and this makes it possible to output JS and declaration files as siblings to the input TS files, which is a valid use case.

Maybe there can be an option for it though? f.e. `cleanNonOutputFilesFromProjectOutput: true` or some descriptive name like that.

**Comment by croraf** [comment]
This does not only happen in --incremental mode.

**Comment by trusktr** [comment]
I suppose someone somewhere if going to accidentally publish files they didn't mean to publish.

**Comment by aweebit** [comment]
@sheetalkamat @RyanCavanaugh can't the `.tsbuildinfo` file be utilized to only delete output files corresponding to the source files from the previous build that are no longer present? Seems like a pretty reasonable and straightforward use of `.tsbuildinfo`.

Not having this automatic cleanup has at least two pretty bad implications:
- As @trusktr mentioned, leftover output files could be published accidentally
- Project references are broken in monorepos (see the extensive discussion starting [here](https://github.com/microsoft/TypeScript/issues/40431#issuecomment-2677375151) in #40431)

It looks like using a third-party tool like Google's [Wireit](https://github.com/google/wireit) is right now the only viable way to avoid these problems.
