### ISSUE TITLE
Narrow the `valueOf` return type for TypedArrays

### ISSUE THREAD

**Issue by wemeetagain** [microsoft/TypeScript#36656]
## Search Terms

valueOf

## Suggestion

Narrow `valueOf` return type for TypedArrays. (Rather than inheriting typing from `Object`)
eg:
```typescript
interface Uint8Array {
   valueOf(): Uint8Array;
}
```

## Use Cases

When building interfaces that mimic TypedArrays, ie interfaces with a subset of TypedArray methods that allow for both TypedArray and opaque implementations, there is often a need for explicit coersion into the actual typed array.
In these cases, it is convenient to have some API to unify the representation that would work in both mimiced and real TypedArrays.

`valueOf` provides this API. Unfortunately, the return type for TypedArrays is `Object` as inherited from `Object`, _even though `valueOf` will return a TypedArray in this circumstance_.
This means that any mimiced TypedArray interface that hopes to use a TypedArray implementation must also have an `Object` return type for `valueOf` to be compatible with the TypedArray type declaration.

This leads to unnecessary typecasts in situations where the return type should be known beforehand, but must be explicitly cast.

## Examples

Currently
```typescript
interface OpaqueUint8Array {
  valueOf(): Uint8Array;
}

// 2322: Type 'Uint8Array' is not assignable to type 'OpaqueUint8Array'. The types returned by 'valueOf()' are incompatible between these types. The 'Object' type is assignable to very few other types.
const x: OpaqueUint8Array = new Uint8Array(1);

// instead we must do:

interface OpaqueUint8Array {
  valueOf(): object;
}
const x: OpaqueUint8Array = new Uint8Array(1);
const y: Uint8Array = x.valueOf() as Uint8Array;
```
Ideally
```typescript
interface OpaqueUint8Array {
  valueOf(): Uint8Array;
}

const x: OpaqueUint8Array = new Uint8Array(1);
const y: Uint8Array = x.valueOf();
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ilogico** [comment]
Could `valueOf` be defined like `valueOf(): this`?
