### ISSUE TITLE
RTCStatsType in dom.generated.d.ts is incorrect.

### ISSUE THREAD

**Issue by doutori** [microsoft/TypeScript#36650]
**TypeScript Version:**  3.7.5

**Search Terms:**

- RTCStatsType

**Code**

**Expected behavior:**

**Actual behavior:**

RTCStatsType is defined as

https://github.com/microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L20177

Actually returns a hyphenated value.

- candidate-pair
- data-channel
- inbound-rtp
- local-candidate
- outbound-rtp
- remote-candidate

MDN Web Docs -> https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsType

**Playground Link:** 

**Related Issues:**

**Comment by hikarinotomadoi** [comment]
Since these three WebRTC features finally published as W3C Candidate Recommendation
https://www.w3.org/TR/webrtc/
https://www.w3.org/TR/webrtc-stats/
https://www.w3.org/TR/webrtc-identity/

I think we should add these types as well.

**Comment by trptcolin** [comment]
I think this is fixed as of https://github.com/microsoft/TypeScript/pull/42067

**Comment by jakebailey** [comment]
Yes, this was fixed in the above linked issue.
