### ISSUE TITLE
() => void 0 causes TS7011 with noImplicitAny

### ISSUE THREAD

**Issue by avin-kavish** [microsoft/TypeScript#36651]
```
() => void 0
```

This function is guaranteed to return `undefined` under any and all conditions. Why is it saying that "Function expression, which lacks return-type annotation, implicitly has an 'any' return type"? When I look at this code, I see function expression, which lacks return-type annotation will always return undefined so why do I need to annotate this with types?

**Comment by JacksonKearl** [comment]
I can't reproduce this in playground https://www.typescriptlang.org/play/?ts=3.8-Beta#code/BQSgBAvAfGBuD2BLAJmADEA or VSCode, how are you seeing the error?

**Comment by avin-kavish** [comment]
Web Storm. It's probably a web storm bug, web storm is also bugged on other typescript fronts. (It keeps auto-completing imports from `@types/...` and then telling me not to import from `@types/...` xD)

**Comment by ajafff** [comment]
You need to enable `strictNullChecks` for this to work as expected.
Without `strictNullChecks` every type can contain `undefined` (and `undefined` itself is not considered a real type). Therefore TypeScript cannot infer which type you actually meant and infers `any`.

**Comment by avin-kavish** [comment]
I see.

**Comment by lucattelli** [comment]
If you want to return undefined, you can simply write an empty arrow function. As functions that don't return nothing actually returns undefined.

```
const myFunction = () => { void 0 }
myFunction(); // undefined, but caught by TS7011

const MyNewFunction = () => { }
myNewFunction() // undefined, not caught by TS7011
```
