### ISSUE TITLE
Inference of generic function return type

### ISSUE THREAD

**Issue by maciejsikora** [microsoft/TypeScript#36657]
**TypeScript Version:**  3.7.5

**return generic type inference, generic return type**

**Code**

```ts
type F<A> = <R>(a: A) => R;
const f: F<string> = (a => 1); // error
const g: F<string> = <number>((a: string) => 1) // error cannot apply generic

// in object
type O<T> = {
   [K in keyof T]: <R>(a: T[K]) => R // function which has argument type T[K] and unknown return
}

const o: O<{ a: string }> = {
   a: x => x + "" // error + not possible to set generic type
}
```

**Expected behavior:**
Possibility of creating function type with properly inferred return type of the function.

**Actual behavior:**
No possibility of having proper inference. Possible only fallback to unsound type.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=12&ssc=2&pln=1&pc=1#code/C4TwDgpgBAYgPAQQHxQLxTgJSQCgIYBcUCAlGipgNwCwAUAMYD2AdgM7BQBmR87ATgEtmAcxTp85KAEYSlKAHp5UCHz6M+dJmw7CecfkNFoMzAK4BbAEYrc+IgZFlUKGQqUq1fKPTzNmjDjwwMAAbEChhCGYVAXo6OkUoIShGSwArCHpgOlBIKAB5OAAVMSgAbzooKoBtAGkk5igAawgQRk4oIoBdIixcQk66rqcKNy5TZiyBFigAdwALWPmoebxWKDw+YQsojlzoIqG6AF94hhZ2FKJCso37YEERKGPSitoqu6gAD0kfgGooAAiQFjDzqby+fyBYJhCJRGJxWjHIA

**Comment by RyanCavanaugh** [comment]
```ts
type F<A> = <R>(a: A) => R;
const f: F<string> = (a => 1); // error
```
This is a correct error. `f<boolean>("")` produces `1` instead of `true`.
