### ISSUE TITLE
[typescript server] type discoverability is unstable

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#36652]
**TypeScript Version:**  3.7.5

**Search Terms:** type infer problem stable ts-server

**Code**

`business-logic.ts`
```ts
export type Dummy = {
  flags: Record<string, boolean>
}
```

`abstract-tool.ts`
```ts
export class PropOf<C, V = any> {
  get value(): V { return null! }
  set value(val: V) {}

  constructor(public context: C) {}
}
```

`applied-middleware.ts`
```ts
import { PropOf } from 'block-above'
import { Dummy } from 'business-logic'

class Middleware extends PropOf<Dummy, Record<string, boolean>> {
  get value() { return this.context.flags }
  set value(val) { this.context.flags = val }
}

export default (context: Dummy) => new Middleware(context)
```

`main.js`
```ts
import { getDummy } from 'some-api-connector'
import flagsOf from 'the-middleware-block'

const dummy = await getDummy('fake-id')
const flags = flagsOf(dummy)

flags.value = {
  ...flags.value,
  'feature1': true
}
```

**Expected behavior:**
setter of `flags.value` doesn't appear as badly inferred.

**Actual behavior:**
setter of `flags.value` is infered as `{ [x: number]: any }` instead of `Record<string, boolean>`

**Playground Link:** 
```
cd /tmp
git clone https://github.com/y-nk/typescript-is-broken
cd typescript-is-broken
yarn
code .
```

**Extended demo:** 
<img src="https://cl.ly/256ca890309e/Screen%252520Recording%2525202020-02-06%252520at%25252001.02%252520PM.gif" width="600" />

https://cl.ly/385ea35d83f3

In a project environment, TS Server casts wrongly as `{ [x: number]: any }` instead of `Record<string, boolean>` but when running tests (using ts-jest), no type error is thrown and test is successful.

**Related Issues:** Related to fallen in limbos: #36603

**Comment by paulsouche** [comment]
Not a typescript but a vscode issue. See https://github.com/y-nk/typescript-is-broken/pull/1 Can be closed now

**Comment by y-nk** [comment]
@paulsouche thanks
