### ISSUE TITLE
Multiline strings in VS 2015 RC

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#3665]
Bugs in entering multiline strings

I typed:
![image](https://cloud.githubusercontent.com/assets/5490484/8399553/c6606b76-1dde-11e5-9090-b4ec1398b6ac.png)

and when I entered the trailing ; I got

![image](https://cloud.githubusercontent.com/assets/5490484/8399554/d48d6aa0-1dde-11e5-96e1-3262294e0707.png)

There are other errors -- such as pressing ; and losing the last line

![image](https://cloud.githubusercontent.com/assets/5490484/8399573/09fb14d0-1ddf-11e5-8098-e3a0c0633f60.png)

**Comment by danquirk** [comment]
The issue here is with the auto formatting kicking in incorrectly? I don't fully understand the last example. You typed ; and a line was deleted?

**Comment by mhegazy** [comment]
@BobFrGit i can not get a repro for this locally following the visible part of your snippet. can you share larger code snippet.

**Comment by BobFrGit** [comment]
Here is the entire contents of the file (is there a way to upload it) in a separate TS

export class wMsgLog {
    constructor(msg: string) {
        this.msg = msg;
        this.dn = utils.DeviceName;
        var bx = `appName: ${navigator.appName}
platform: ${navigator.platform}
useAgent: ${navigator.userAgent}`;



        var bi = `appName: ${navigator.appName}
            navigator.appVersion}
platform: ${navigator.platform}
            navigator.userAgent}`;
        this.browser = bi;
        this.room = HSupport.Named.CurrentRoom;
        this.usingSSL = Flagger.useSSL.checked;
    }
    msg: string;
    dn: string;
    browser: string;
    room: string;
    usingSSL: boolean;
}

(BTW, in creating the new file the "General" files show JavaScript but not TypeScript -- I have to to the Script choice for TypeScript -- it should be listed under General because it is not just for scripting)

***

![image](https://cloud.githubusercontent.com/assets/5490484/8418357/a12221ea-1e80-11e5-9042-6c76f1491ef4.png)

I then typed `; and upon typing the ; it became

![image](https://cloud.githubusercontent.com/assets/5490484/8418359/abf3ec0c-1e80-11e5-8aa0-7eb7b4f50551.png)

I then fixed it to

![image](https://cloud.githubusercontent.com/assets/5490484/8418368/b7dbc7ba-1e80-11e5-8cd3-88c0055fe068.png)

Then backspaced and typed `; and it didn't fail
I then removed and typed ; in the second example and get

![image](https://cloud.githubusercontent.com/assets/5490484/8418377/c0cb4c1a-1e80-11e5-93e2-e5c8b81fc73a.png)

When I deleted and retyped the ; in the “bi” (as opposed to the “bx”) assignment the last line disappeared.

**Comment by BobFrGit** [comment]
DId I close this -- didn't mean to -- was

**Comment by danquirk** [comment]
You're good now, it's open/active. https://gist.github.com/ is usually an easy way to share larger chunks of code if you don't want to actually put the file itself on DropBox, OneDrive, etc.

**Comment by BobFrGit** [comment]
Thanks. I can do the others but I presume gist is more forever (Yeah, I know more forever is like more unique -- doesn't make sense but it does make sense).

**Comment by danquirk** [comment]
You can delete a gist when you want to:
![image](https://cloud.githubusercontent.com/assets/7121557/8419230/24ec8b00-1e6d-11e5-913b-497125e3798a.png)
but I get what you're saying. Any of the usual file sharing services is a fine option too.

**Comment by mhegazy** [comment]
thanks @BobFrGit, This looks like it should be fixed in the next release.
