### ISSUE TITLE
Error in a case without type annotation.

### ISSUE THREAD

**Issue by laco0416** [Microsoft/TypeScript#3666]
[Playground](http://www.typescriptlang.org/Playground#src=interface%20PolymerElement%20%7B%0D%0A%20%20properties%3F%3A%20%7B%20%5BpropName%3A%20string%5D%3A%20StringConstructor%7CPolymerElementProperty%20%7D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20PolymerElementProperty%20%7B%0D%0A%20%20type%3A%20StringConstructor%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Why%20is%20this%20incorrectly%20implements%3F%0D%0Aclass%20WithoutTypeAnnotation%20implements%20PolymerElement%20%7B%0D%0A%09properties%20%3D%20%7B%0D%0A%09%09prop1%3A%20String%2C%0D%0A%09%09prop2%3A%20%7B%0D%0A%09%09%09type%3A%20String%0D%0A%09%09%7D%0D%0A%09%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20WithTypeAnnotation%20implements%20PolymerElement%20%7B%0D%0A%09properties%3A%7B%20%5BpropName%3A%20string%5D%3A%20StringConstructor%7CPolymerElementProperty%20%7D%20%3D%20%7B%0D%0A%09%09prop1%3A%20String%2C%0D%0A%09%09prop2%3A%20%7B%0D%0A%09%09%09type%3A%20String%0D%0A%09%09%7D%0D%0A%09%7D%3B%0D%0A%7D%0D%0A%0D%0A)

```typescript
interface PolymerElement {
  properties?: { [propName: string]: StringConstructor|PolymerElementProperty };
}

interface PolymerElementProperty {
  type: StringConstructor;
}

// Why is this incorrectly implements?
class WithoutTypeAnnotation implements PolymerElement {
	properties = {
		prop1: String,
		prop2: {
			type: String
		}
	};
}

class WithTypeAnnotation implements PolymerElement {
	properties:{ [propName: string]: StringConstructor|PolymerElementProperty } = {
		prop1: String,
		prop2: {
			type: String
		}
	};
}
```

Both `properties` are same object, but tsc occurs error in  a case without type annotation. Why?

Thanks.

**Comment by RyanCavanaugh** [comment]
Necessary background: http://stackoverflow.com/questions/22077023/why-cant-i-indirectly-return-an-object-literal-to-satisfy-an-index-signature-re

The root problem here is that we don't contextually type class property initializers with the type the property "should" have from an `implements` or `extends` clause. Without a contextual type on the object literal, the property is inferred to not have an index signature.

Logged #3667 as this has been a long-standing pain point.

**Comment by laco0416** [comment]
Thanks, Ryan. I understood the problem's background.
I hope it'll be resolved someday.
