### ISSUE TITLE
Casting a non-empty namespace to an interface sometimes type checks incorrectly

### ISSUE THREAD

**Issue by mgoszcz2** [microsoft/TypeScript#36660]
**TypeScript Version:**  3.7.5 + Nightly

**Search Terms:** typescript casting namespace to interface bug, typescript namespace implement interface

The following code compiles without errors, even though the namespace Foo does not implement the interface Bar fully.

**Code**

```ts
interface Bar {
    ham(): void
    spam(): void
}

namespace Foo {
    function ham(): void {}
}

const bar = Foo as Bar;
```

This also works if `ham` is exported by the namespace. Interestingly this fails correctly:

```ts
interface Bar {
    ham(): void
    spam(): void
}

namespace Foo {
    export function ham(): void { }
    export function dummy(): void { } // Incorrectly type-checks if removed.
}

const bar = Foo as Bar;
```

**Expected behavior:**
An error that might look something like
```
TS2352: Conversion of type 'typeof Foo' to type 'Bar' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'spam' is missing in type 'typeof Foo' but required in type 'Bar'.
```

**Actual behavior:**
The example compiles successfully. If the namespace is empty it fails with `Cannot use namespace 'Foo' as a value.`.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgEJysg3gKGf5ACzgFsAKASgC5kA3Ae2ABM8CBnAB1MpoeZwC+OHCFIROiFADF69bK3wwAriARhg9EEW7U6jJtiFCcCTWzDIARhmQBeZDLlw2aDAG4gA)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; see #20849 or others for discussion around why type assertions exist and what rules they enforce
