### ISSUE TITLE
'new Function' has bug specifying its function body

### ISSUE THREAD

**Issue by mukulga** [microsoft/TypeScript#36670]
I'm developing with TypeScript compiler v 3.7.5, on Windows 10. Below is a complete TypeScript code, that I've question with (which looks to me a bug, and an area of improvement),

var myFunction = new Function("a", "b", "c", "var res1:number = a + b + c; return res1;"); 
var x:number = myFunction(4, 3, 2); 
console.log(x);

The above code compiles fine, using the TypeScript compiler. When the generated javascript code is run, I get following runtime error,

var res1:number = a + b + c; return res1;
            ^
SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at Object.<anonymous> (D:\typescript_examples\tst1.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

The generated javascript code with my above specified TypeScript example, was following,
var myFunction = new Function("a", "b", "c", "var res1:number = a + b + c; return res1;");
var x = myFunction(4, 3, 2);
console.log(x);

I think that, the generated javascript code should have had following in it,
"var res1 = a + b + c; return res1;"
instead of,
"var res1:number = a + b + c; return res1;"

**Comment by AnyhowStep** [comment]
You want TypeScript to look at the string argument, parse that, and replace it with a JS string?

This definitely seems out of scope.

**Comment by mukulga** [comment]
> You want TypeScript to look at the string argument, parse that, and replace it with a JS string?

The last argument of the call 'new Function(...)' has to be a function body. When writing for example, new Function("a", "b", "c", "var res1:number = a + b + c; return res1;");
as a TypeScript code, the string that is written in this example for the last argument is a valid TypeScript function body (represented as a string value). I think therefore that, the TypeScript compiler should have a way to generate a valid JavaScript code for such an input function body, and if that's not possible the TypeScript compiler should show some error.

**Comment by nmain** [comment]
```ts
var myFunction = new Function("a", "b", "c", "var res1:number = a + b + c; return res1;");
```

This is valid Javascript code.  When run in a Javascript engine, the result of this code is to throw a `SyntaxError: unexpected token: ':'`.  You'd like it to do something different in Typescript, which is against some of the core requirements of Typescript features:

>* [ ] This wouldn't change the runtime behavior of existing JavaScript code
>* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)


Also consider that most uses of `Function(...)` pass it a dynamic string; if the string is known at compile time, you could have just made a regular function.  So to make this be at all useful, you'd need to have the entire Typescript compiler available at runtime!

**Comment by mukulga** [comment]
> var myFunction = new Function("a", "b", "c", "var res1:number = a + b + c; return res1;");
> 
> This is valid Javascript code.

I don't think that, above mentioned code is a valid JavaScript code. res1:number is not valid with JavaScript, but is valid with TypeScript.
 
> Also consider that most uses of `Function(...)` pass it a dynamic string; if the string is known at 
> compile time, you could have just made a regular function. So to make this be at all useful, you'd 
> need to have the entire Typescript compiler available at runtime!

Thanks for above point. That looks useful to introspect.

Interestingly, the following TypeScript code (having a junk function body) compiles fine using the TypeScript compiler (and generates the same as JavaScript),

var myFunction = new Function("a", "b", "c", "gfhdgfdhfg");

But of course, the generated JavaScript for above, gives a JavaScript runtime error (since the function body is not compliant as per the JavaScript language).

I can conclude following so far, as per the doubt I expressed initially for this thread,
The errors in a programming application, as per my original question in this thread, can be known to the user/programmer only at run time (which looks reasonable to me, since the application framework provided by the TypeScript compiler & JavaScript runtime has decided to implement in a particular way).

**Comment by RyanCavanaugh** [comment]
This sort of construction is extremely rare in modern JS coding, and the places where one would plausibly still want to do it involve string manipulation anyway (so we'd be unable to make meaningful guarantees).
