### ISSUE TITLE
[Bug] Decorators for arrow functions. Unable to resolve signature of property decorator when called as an expression. ts(1240)

### ISSUE THREAD

**Issue by Eramik** [microsoft/TypeScript#36679]
**TypeScript Version:**  3.7.5

**Search Terms:** decorators for arrow functions

**Code**:

Error: Unable to resolve signature of property decorator when called as an expression. ts(1240)
```ts
function decorator(target: any, propertyKey: string, descriptor: PropertyDescriptor) {
}

class TextClass {

    @decorator
    arrowFunction = () => {
        
    }
}
```

**Expected behavior:**  For decorator to be recognized as method decorator.

**Actual behavior:** Decorator recognized as property decorator, resulting in error.

Purpose of using arrow functions is to preserve `this` context as class when passing class methods to child nodes in react instead of binding `this` for each method in class constructor.

**Playground Links:** 
[Doesn't work with an arrow function](http://www.typescriptlang.org/play/?experimentalDecorators=true#code/GYVwdgxgLglg9mABAEwKYTgJwIZSwCim0wHNUoAuRbMATwBpEAHTOJ1TKWgaVVqoDOUTDDAlGaARBFM8mKgAVW7TrQAiqKTLkBKRAG8AUAF9DhiABtsAgYgAqqAB5QAwlZsGzib4gACaDBw5Qx9qTFYAdwAxcGh4JABeRHw9BIA+T1DQkJ9TYyA)
and
[Works with a usual function](http://www.typescriptlang.org/play/?experimentalDecorators=true&ssl=7&ssc=20&pln=7&pc=23#code/GYVwdgxgLglg9mABAEwKYTgJwIZSwCim0wHNUoAuRbMATwBpEAHTOJ1TKWgaVVqoDOUTDDAlGaARBFM8mKgAVW7TrQAiqKTLkBKRAG8AUAF9DhiABtsAgYgAqqAB5QAwlZsGzib4gACaDBw5Qx9qTFYAdwAxcGh4MHw9I1DQkJ9TYyA)

**Comment by RyanCavanaugh** [comment]
See #19528

This is a property, not a method.
