### ISSUE TITLE
Feature Request: implementation of an interface should ignore modifiers.

### ISSUE THREAD

**Issue by KostyaTretyak** [microsoft/TypeScript#36676]
## Search Terms

- is:issue interface ignore modifiers

## Suggestion

Since the interfaces cannot have modifiers, the implementation of these interfaces should ignore these modifiers.

## Use Cases

```ts
interface Options {
  prop1: string;
  prop2: string;
}

class Application implements Options {
  protected prop1: string;
  protected prop2: string;

  constructor(options: Options) {
    this.prop1 = options.prop1;
    this.prop2 = options.prop2;
  }
}
```

Should be without this error:
> Class 'Application' incorrectly implements interface 'Options'.
>  Property 'prop1' is protected in type 'Application' but public in type 'Options'.ts(2420)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
Wait, should we be allowed to assign a value of type `Application` to a variable of type `Options`?

```ts
const options: Options = new Application({ prop1: "", prop2: "" }); // error or not?
```

If that results in a compiler warning, then you have `Application implements Options` but you can't use an `Application` as an `Options`, which seems to invalidate the meaning of `implements`.  

And if there's *no* compiler warning, then `protected` members of `Application` are suddenly usable from the outside, which seems to invalidate the meaning of `protected`.   We currently have a similar situation with `readonly` (see #13347) and I don't think anyone's happy with it.  

I guess I don't understand the use case.  Why do you want to say that `Application implements Options` in the first place?  What do you lose by just leaving out the `implements` clause?

**Comment by KostyaTretyak** [comment]
@jcalz, results - in a compiler warning.

> seems to invalidate the meaning of `implements`

Probably, but it seems nothing bad should happen if the interfaces are responsible for the presence of the property and does not take into account the modifier.

> I guess I don't understand the use case. Why do you want to say that `Application implements Options` in the first place? What do you lose by just leaving out the `implements` clause?

I want to set options outside the `Application` class, and without implementation, there is no guarantee that any of the developers later will make prop1 and prop2 incompatible with `Options`.

**Comment by RyanCavanaugh** [comment]
This would introduce frankly bizarre inconsistency between `implements` and assignability, which today are fully symmetric. I don't think this is what we want `implements` to mean.
