### ISSUE TITLE
async, await, loop, implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#36687]
**TypeScript Version:**  3.5.1, 3.7.5, 3.8-Beta

**Search Terms:** async, await, loop, promise, variable assignment, implicitly has type any, referenced directly or indirectly in its own initializer.

**Code**

```ts
interface Foo {
    id : string,
}

declare function paginate(after: string|undefined): Promise<Foo[]>;

async function main() {
    let after: string | undefined = undefined;
    while (true) {
        const page = await paginate(after);
        for (const foo of page) {
            after = foo.id;
        }
    }   
}
```

**Expected behavior:**

Type checks successfully

**Actual behavior:**
![image](https://user-images.githubusercontent.com/5655961/74070095-05f11e00-49ce-11ea-9340-d2cec4e3a276.png)

**Playground Link:** [Playground](http://www.typescriptlang.org/play/?ts=3.8-Beta&ssl=1&ssc=1&pln=15&pc=2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHLAAmyAXMgM5hSgDmANLgL667EQIA2cUKMAVxAIwwdCGQAHOHVBxIACjgxIUCtVog6AHyEcYoCMQCUFAApR0AW2CUIAHgzoA2gF0AfAG42cSgE9hZEFhUXFkKzhQBWMcfEIuCDBkZVV1GnpkbWQ9CAMQI2QAXmyQfUNib0JkAHcAC2AE5AUaAQgYvCqqhHFqKRkUYrhqyKTpWRB5CCUVaGNKzoIYdCgm7pBepax0GD66NtiFhZToIqDMADoSeYXWKuZCFiA)

**Related Issues:** 

Similar to https://github.com/microsoft/TypeScript/issues/14428 , an already fixed issue.

Similar to https://github.com/microsoft/TypeScript/issues/36666 , but without destructuring; and my initial variable also has explicit type annotations (`after : string|undefined`)

-----

### Workaround

Just use an explicit type annotation,
```ts
const page : Foo[] = await paginate(after);
```

However, it is strange. It shouldn't need the explicit type annotation because it can only possibly be `Foo[]`.

**Comment by AnyhowStep** [comment]
Shorter [repro](http://www.typescriptlang.org/play/?ts=3.8-Beta&ssl=1&ssc=1&pln=13&pc=2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHLAAmyAXMgM5hSgDmANLgL667EQIA2cUKMAVxAIwwdCGR0IYDOgAUcGJCgVqtEHQA+QjjFARiASgoAFKOgC2wShAA8sgHwBuNnEoBPYckHDR45BZwoHKGOPiEXNLIisqqNPTImsg6EHogBsgAvMkguvrELoTIAO4AFsCRyHI0AhCheEVFCOLU3phZ0cVBYJLSsgpK0IaFjQQx0B0wmAB0JCMEzIQsQA)

```ts
interface Foo {
    id : string,
}

declare function getFoo(after: string|undefined): Promise<Foo>;

async function main() {
    let after: string | undefined = undefined;
    while (true) {
        const foo = await getFoo(after);
        after = foo.id;
    }   
}
```

**Comment by Zemnmez** [comment]
interesting... the `while(true)` seems to be involved in this:

```
interface Foo {
    id : string,
}

declare function paginate(after: string|undefined): Promise<Foo[]>;

async function main() {
    const page = await paginate("ok");
    for (const foo of pa...
```

[Playground Link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRywAJsgFzIDOYUoA5gDQEC+BBpECANnFChgBXEAjDB0IZAAc4DUHEgAKODEhQqteiAYAfEVxigIpAJRUAClHQBbYNQgAeDOgDaAXQB8Abg7441ACeosjCouKSyDZwoEqmOATEyAiStDJyKAC8yHAA7jFg6fIgihBKAEToANblpr6ExDDoUMhKKSBpTVjoMEUQ8XgNSUSJxOyEbEA)

**Comment by Zemnmez** [comment]
OK. I think this is an issue of type narrowing. It looks to me like the first time the loop runs, `after` is explicitly typed to `string | undefined`, but after this, it's type is `await paginate(after)[...].foo.id`, whose type is determined indirectly by the result of `paginate(after)`.

**Comment by Zemnmez** [comment]
> ```ts
> async function main() {
>     let after: string | undefined = undefined;
>     while (true) {
>         const foo = await getFoo(after);
>         after = foo.id;
>     }   
> }
> ```

the example here would be broken even if we didn't have this issue because `id` does not exist on `Foo[]` (the return type of `getFoo()`)

**Comment by Zemnmez** [comment]
Here's a version of this code that *does* work (I am not sure why...):

```typescript
interface Foo {
    id : string,
}

declare function paginate(after: string|undefined): Promise<Foo[]>;

async function main() {
    let after: string | undefined;
    while (true) {
        const page = await paginate(after);
        for (const foo of page) {
            after = foo.id;
        }
    }
}
```

[Playground Link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRywAJsgFzIDOYUoA5gDQEC+BBpECANnFChgBXEAjDB0IZAAc4DUHEgAKODEhQqteiAYAfEVxigIpAJRUAClHQBbYNQgAeDOgDaAXQB8Abg7441ACeosjCouKSyDZwoEqmOATEyDwQYMiq6pp0jMi6yAYQRiAmvoTEAO4AFsApyEp0QhDxeGVJRAiStDJyKAC86eUxabLyIIoQKmrQpqVtxDDoUHUdIF0LWOgw3QxNCa1zxBnQyP3rAHRkswfs+zc3QA)

**Comment by AnyhowStep** [comment]
> because id does not exist on Foo[] (the return type of getFoo())

What are you talking about?
In the second example, `getFoo()` returns `Promise<Foo>`. Not `Promise<Foo[]>`.

**Comment by Zemnmez** [comment]
> > because id does not exist on Foo[] (the return type of getFoo())
> 
> What are you talking about?
> In the second example, `getFoo()` returns `Promise<Foo>`. Not `Promise<Foo[]>`.

sorry i misread 😅

**Comment by RyanCavanaugh** [comment]
This is a legit circularity and none of our existing circularity-shortcutting mechanisms work in this case

**Comment by AnyhowStep** [comment]
How is it circular, despite the explicit type annotation, and explicit initialization?

Why would removing explicit initialization (`= undefined`) make it work?

If it was circular before removing it, it should be circular after removing it

**Comment by AnyhowStep** [comment]
Still confused here =(

**Comment by AnyhowStep** [comment]
Bump to prevent auto closing

**Comment by evenfrost** [comment]
Any update on this? Just faced this very error in the `while` loop.

**Comment by evenfrost** [comment]
Faced this again, found this thread again, realized that I had already commented on this a year ago.

Well, as I'm back here, any update on this? Removing the `async/await` stuff from this throws no error, so I believe it's more like a bug than a design limitation.

**Comment by RyanVExtend** [comment]
I just ran into this issue with a very similar scenario.  Was very surprised to find this as an open issue still... and originating in 2020...

I can't share the complete code here, but the short of it is essentially:
```ts
async processStream(): Promise<void> {
  let ShardIterator: string | undefined = await this.getShardIterator() // () => Promise<string>

  while (ShardIterator) {
    const res = await this.ddbStreamsClient.getRecords({ ShardIterator, Limit: 10 }).promise()
    //     ^ res has implicit any
    
    //  ... other code ...
    
    ShardIterator = res.NextShardIterator // string | undefined
  }
}
```

outside of the loop block this isn't an issue.  This is just my first stop in my search for an answer, but have not seen anything in the responses here that makes me feel like error is by design.

**Comment by rdsedmundo** [comment]
Just got this on a do..while loop using pagination with a cursor, feels odd that this triggers a problem on TS.

**Comment by isnifer** [comment]
Any update on this? It's very annoying to use workarounds, cmon

**Comment by zachweinberg** [comment]
Update?

**Comment by martinlarka** [comment]
I think this issue might be fixed since I don't get any errors in the playground when I choose ts 5.

However, I have also run into this or a similar issue and just wanted to share what helped me. And that is to explicitly type the awaited result which would be `const page` in @AnyhowStep example.

**Comment by RealAlphabet** [comment]
> I think this issue might be fixed since I don't get any errors in the playground when I choose ts 5.
> 
> However, I have also run into this or a similar issue and just wanted to share what helped me. And that is to explicitly type the awaited result which would be `const page` in @AnyhowStep example.

Still not working for me with TypeScript 5.3.3.

**Comment by Judekeyser** [comment]
Still ran into this issue in one of my code. Everything was working fine if I typed the result of `await task$` , and failed without it.

Why closing the issue on Feb 24, while a comment on Feb 7 was issued? Very puzzling management
