### ISSUE TITLE
Conditional type inference gives conflicting results for functions returning booleans

### ISSUE THREAD

**Issue by vitoke** [microsoft/TypeScript#36683]
**TypeScript Version:**  3.8.0-dev.20200206

**Search Terms:**
conditional boolean

**Code**

```ts
type Example1<T> = () => T;
type Example2<T> = T extends any ? () => T : never;
type Example3<T> = T extends never ? never : () => T;

function test1<T>(e: Example1<T>): void {}
function test2<T>(e: Example2<T>): void {}
function test3<T>(e: Example3<T>): void {}

test1(() => 1); // ok
test2(() => 1); // ok
test3(() => 1); // ok

test1(() => ''); // ok
test2(() => ''); // ok
test3(() => ''); // ok

test1(() => true); // ok
test2(() => true); // fail
test3(() => true); // fail

test3(() => false);         // fail
test3(() => true as true);  // ok

// root cause: with boolean, conditional type is inferred to be:
type FalseOrTrueReturn = (() => false) | (() => true)
const falseOrTrueReturn: FalseOrTrueReturn = () => (false as boolean)  // fail

// it only fails for function return type, so this works:
type FalseOrTrueArg = ((value: false) => void) | ((value: true) => void)
const falseOrTrueArg: FalseOrTrueArg = (value: boolean) => {} // ok
```

**Expected behavior:**
All failing lines should compile just fine. This is a simplified example, but it prevents correct type inference for more complex real-world use-cases.

**Actual behavior:**
Compiler fails to compile the lines with a function returning a boolean. This is due to the boolean return value being destructured into `() => true | () => false`, and `() => boolean` is not assignable to that.

**Playground Link:** 
[TS Playground](https://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20200206&ssl=1&ssc=1&pln=31&pc=1#code/C4TwDgpgBAogHgQwLZgDYQIwB4AqA+KAXigAoBKIgnAbgFgAoUSWRFdAJlwOJygjmAQAdgBMAzlARCQUAPykKhKlABcUIRABuEAE51G4aPGRoIAZi5EovfoNESN2nXPVbdqhZWv6GAMwCuQgDGwACWAPZCUIJiwNj4JBBqxmyYXGRqmuGhIlAA3gC+foEhEVExwJwJSSwmHOmZ2bmFxcFhkdEQsRbVyaymPXgZUFk5+UX0DBUYJOReGGTUUAD0y1DhANZTXZWzigQLS6vrW4w7ZnvziytrmwzbsTNzSlAA5K-Xx3dnseyXL+9PrdThULs8CICjsD7j84v8CMAdP4IECTg9duDokiUVCoL4EKFUOiwfsscjUfjCTDQfC8QhUGIcVBmSyWcdKUTYSSvIjkZIJLymTc0ZN6McdOFwsAoEEEP5GWoAO6hYAACygACNJegpAAaGWREQqsr06KGKChCShIS+XQ6CC5YDhTVJKbmgBi9MZAHkdDhsQAlCDAfw6KLEWn4hkoqAAH1ImMFZAYQUisTp0d9-uRQZDYbUnszfsDwdD4c8LxIUcZ-M12ogUgowo5MOOKvWQlQMg5El84WcATaZSg9rz5UM+rEzrVlqgiv7GzEKjdzELPuLyIAgjoAOZWWaaenItTVmMvUYiCjxg9HmpJrwX5P0VNCdOnrPY7c7gteiAfre7vuh6oMedbhDqQikoUwrfEAA)

**Related Issues:** 
Possibly:
https://github.com/microsoft/TypeScript/issues/33369 
https://github.com/microsoft/TypeScript/issues/35861

**Comment by weswigham** [comment]
@vitoke you _probably_ want to write
```
type Example2<T> = [T] extends any ? () => [T] : never;
```
- conditions by default distribute their computation over unions, and `boolean` is a union of `true | false`.
