### ISSUE TITLE
Goto definition shouldn't go to named import

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3669]
It would help me a lot if the current behaviour of goto definition goes to the definition and not the named import:
```typescript
// module.ts
/*shouldGoHere*/export function something() { ...}
```
```typescript
// index.ts
import {/*nowGoesHere*/something} from './module';

something/*goto*/
```

**Comment by NoelAbrahams** [comment]
I've also found this to be annoying.

**Comment by DanielRosenwasser** [comment]
I think it should be the case that if you go to definition on the import once more, you'll land in the exported function in `module.ts`. Is it not?

**Comment by tinganho** [comment]
yes, in the import clause it will go to the exported function. But could this be a direct jump to the export function? It doesn't help me that much that it jumps to the import clause. I guess people want to figure out what a function does, when they goto definitions and jumping to the import clause doesn't give me so much info except the name, which I already know.

FWIW, namespaced import jumps directly to the definition.

**Comment by mhegazy** [comment]
The rational that gotoDef takes you to where the construct you are using is defined. and in this case it is the import declaration. It is a declaration, it has its own scope, and it can introduce new named binding, in that sense it is the same like an object literal property for instance. i also find it a bit disorienting when imports introduce renames e.g.:

```ts
// file1.ts
export class C {}
```
```ts
// file2.ts

import {C as D} from "file1";

new /*goToDef here takes you to a class "C" */D();
```
changing it should not be hard, it is more about consistency..

**Comment by tinganho** [comment]
@mhegazy any news on this one? It is still quite annoying that it jumps to the import declaration. I think a special casing here wouldn't do any harm. I think in all situation one want to jump to the "real" declaration.

**Comment by techird** [comment]
@tinganho The same anoying for me. BTW. C# always jumps to the real definition point, not the using clause.

**Comment by mhegazy** [comment]
@tinganho if you want to take a crack at it, would be happy to look at the PR.

**Comment by tinganho** [comment]
OK I will try to look into it.

**Comment by olmobrutall** [comment]
+1, maybe in the aliased case its justifiable, but in the normal case is quite annoying.

**Comment by mhegazy** [comment]
thanks @tinganho!
