### ISSUE TITLE
Daily build's patch version isn't updated

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#36691]
Because the daily build's version is still 3.8.0, I can't get the latest build based on the order of the versions.

```
Version History
3.8.0-dev.20200208
9 hours ago
3.8.0-dev.20200207
a day ago
3.8.1-rc
2 days ago
3.8.0-dev.20200206
2 days ago```

**Comment by IllusionMH** [comment]
Where do you get that list? Looks like Versions tab from npm.
`
If you are really looking for latest nightly version you can just use version that has `next` tag after it, or rely on `rc`, `beta`, `latest` tags and pick higher from them.

**Comment by orta** [comment]
Yeah, the patch never changes - you need to use the tags ( I do this for the playground nightlies too, so it's reliable.)  This conforms to [semver prerelease tags](https://semver.org/#spec-item-9)

**Comment by falsandtru** [comment]
I'm updating dependencies using npm-check-updates to install updates at once but it doesn't support tags. If you update all dependencies using tags, you will have to run `npm install` twice or more.

```
  shell('ncu -ux del');
  shell('ncu -ut typescript');
  shell('npm i --no-shrinkwrap');
```

Anyway the minor version is updated instead.

```
3.9.0-dev.20200220
14 hours ago
3.9.0-dev.20200219
2 days ago
3.9.0-dev.20200215
6 days ago
3.9.0-dev.20200214
7 days ago
3.9.0-dev.20200213
8 days ago
3.9.0-dev.20200212
9 days ago
3.8.0-dev.20200211
10 days ago
```

**Comment by falsandtru** [comment]
So, @orta's answer has a problem as the official solution.

**Comment by IllusionMH** [comment]
If you have npm you can get versions for tags as `npm dust-tag ls typescript` and grep for tag that you need
