### ISSUE TITLE
Empty JSDocTemplateTag has single type parameter with zero width

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#36692]
**TypeScript Version:**  3.8.0-dev.20200208

**Search Terms:** JSDocTemplateTag typeParameters

**Code**

```ts
ts.version; // 3.8.0-dev.20200208
const sourceFile = ts.createSourceFile("test.ts", "/**\n * @template\n */\nlet x;");

console.log(sourceFile.statements[0].jsDoc[0].tags[0].typeParameters);
```

**Expected behavior:** Empty array.

**Actual behavior:** Array with single element: `[{pos: 16, end: 16, …}]`

![image](https://user-images.githubusercontent.com/1609021/74088967-06d78d80-4a6a-11ea-8a69-fcff9408a323.png)

https://ts-ast-viewer.com/#code/PQKhCgAIUgBAXApgWwA4BsCGSomOdReSADwG4g (select `typescript@next` and check `show internals`)

**Comment by RyanCavanaugh** [comment]
This is a pretty normal parse when we encounter syntax where an identifier is mandatory. You'd see the same for e.g.
```
export { x as }
```
the second `Identifier` has an empty span

**Comment by dsherret** [comment]
@RyanCavanaugh that's not an equivalent example because this is an array.

**Comment by sandersn** [comment]
A better example is 

```ts
class C<> {

}
```

Which does produce an empty array for typeParameters.

**Comment by Rustin-Liu** [comment]
I want to working on it, Can I take this?

**Comment by orta** [comment]
Give it a shot!

**Comment by Ivan-Z** [comment]
@Rustin-Liu are you still working on this? If not, I'd like to take a shot a this.

**Comment by Rustin-Liu** [comment]
> @Rustin-Liu are you still working on this? If not, I'd like to take a shot a this.

Please feel free take it.

**Comment by michaelhankin** [comment]
@Ivan-Z are you still working on this? If not, I'm gonna give it a shot.
