### ISSUE TITLE
JsDoc @type {modue:X} + null default value = syntactically invalid .d.ts emit

### ISSUE THREAD

**Issue by AjiTae** [microsoft/TypeScript#36690]
**TypeScript Version:**  3.8.0-dev.20200207

**Search Terms:**
JsDoc module null alias empty type declaration

**Code**
Minimal js file:
```javascript
/**
 * @module A
 */
class A {}


/**
 * Target element
 * @type {module:A}
 */
export let el = null;

export default A;
```
Minimal tsconfig:
```json
{
  "compilerOptions": {
    "emitDeclarationOnly": true,
    "allowJs": true,
    "declaration": true,
    "outFile": "./x.d.ts"
  }
}
```

**Expected behavior:**
```ts
declare module "b" {
    /**
     * Target element
     * @type {module:A}
     */
    export let el: A; // or any
    export default A;
    /**
     * @module A
     */
    class A {
    }
}
```
**Actual behavior:**
```ts
declare module "b" {
    /**
     * Target element
     * @type {module:A}
     */
    export let el: ;
    export default A;
    /**
     * @module A
     */
    class A {
    }
}
```
**Playground Link:** [Provided](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=13&pc=18&useJavaScript=true#code/PQKhCgAIUgBBbA9gEwK4BsCmkCCUTDgDG6AhgM7m6QDeAvuI6BNJACqkBOA5pgC6RMWeJgB2ffHD4BPAA7YaSNFgBcOBtEKYAHrMScBWAUMgBeSKIzoA3Ix16DkZJgBmpDAJzWgA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Clarifying title for priority. Thanks for the good repro!

**Comment by weswigham** [comment]
Nice - this is just because we don't parse `module:` references in jsdoc, so we see `@type {module:A}` as an "empty" type declaration. I'll make the handling more graceful, so we output `any` instead, but @AjiTae, you shouldn't expect those `module:` references to work (I don't even know how they're supposed to).
