### ISSUE TITLE
`webworker` lib: `Clients#get` returns `Promise<any>`, should return `Promise<Client | undefined>`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#36705]
**TypeScript Version:**  3.7.5

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

https://w3c.github.io/ServiceWorker/#dom-clients-get

```ts
get(id: string): Promise<Client | undefined>;
```

**Actual behavior:**

https://github.com/microsoft/TypeScript/blob/fa3173f8f6443307739fc7c41f2bdd680f56a844/lib/lib.webworker.d.ts#L907

**Playground Link:** 

**Related Issues:**

**Comment by Rustin-Liu** [comment]
Hi @RyanCavanaugh , I raised a PR to fix this issue, could you please take a look?
