### ISSUE TITLE
NonNullable should consider the void type

### ISSUE THREAD

**Issue by amitport** [microsoft/TypeScript#36703]
**TypeScript Version:**  3.7.5

**Search Terms:** NonNullable  void

**Code**

```ts
    function isNonNull<T>(value: T): value is NonNullable<T> {
      return value != null;
    }
    function test(): void | true {
      if (Math.random() < 5) {return true;}
    }
    const t1 = test();
    let t2: true;
    if (isNonNull(t1)) {
      t2 = t1;
    }
```

**Expected behavior:**
should work fine, because `!= null` is also `not void`

**Actual behavior:**
getting `Type 'void' is not assignable to type 'true'.`

**workaround**
I'm using
```ts
type NonNullable2<T> = T extends null | undefined | void ? never : T;
```
which works fine

**Comment by MartinJohns** [comment]
`void` does not mean "no value", it means "this value should not be used for anything". It may very well `null` or `undefined`, it may also be an object. It can be truthy or falsy.

**Comment by amitport** [comment]
@MartinJohns 
according to typescript doc `void` is just `undefined | void` see https://www.typescriptlang.org/docs/handbook/basic-types.html#void

If there is some other definition then this would be a bug in the documentation
and how would you check if something is not void? and what is the typescript "way" of doing what I did in the example code?

**Comment by MartinJohns** [comment]
> according to typescript doc void is just undefined | null see

I'm not sure where you get this from. The documentation you linked states:

> void is a little like the opposite of any: the absence of having any type at all.

Absence of having a type means it can be any value, not just `undefined` and `null`.

This FAQ section is relevant: https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

#35236 and #35850 have a lot of discussions regarding this behavior as well and mentions why something like `void | true` doesn't make sense.

---

With a small adjustment of your code the issue should become more clear:

    function test(fallback: () => void): void | true {
      if (Math.random() < 5) { return true; }
      return fallback();
    }
    
    const t1 = test(() => "abc");

The type of the else-branch is `void`, but it will return the value `"abc"`. This is completely legal TypeScript code.

**Comment by amitport** [comment]
the problem is that using `undefined` generates `TS7030: Not all code paths return a value.`

**Comment by amitport** [comment]
I guess this is controlled by `noImplicitReturns`
dup https://github.com/microsoft/TypeScript/issues/18319
closing this. thanks, @MartinJohns !
