### ISSUE TITLE
combined output causes error when there is an inheritance (order in file is wrong)

### ISSUE THREAD

**Issue by mdzieg** [Microsoft/TypeScript#3671]
In solution (Visual Studio 2013) with a couple of separate ts files, when one class extends another one and files are combined together, it may happen that resulting file causes exception in __extends method. Second parameter has undefined value (derived class goes first, parent class is not yet defined).

I think that parent classes should be placed before derived ones.

**Comment by mhegazy** [comment]
The compiler does not reorder emitted code. the files are emitted in order supplied on the commandline and through resolving /// references. you can either move the derived class definition to be after the base, or add a `/// <reference>` tag to the file with the derived class pointing to the file with the base class to ensure correct emit order.

See #21 for more details about this issue.

**Comment by mdzieg** [comment]
Thank you @mhegazy. This seems to be exactly what I need.

**Comment by mhegazy** [comment]
glad it helped.
