### ISSUE TITLE
Typescript 3.4 breaks some type inference with method overloads. (unknown)

### ISSUE THREAD

**Issue by garronej** [microsoft/TypeScript#36735]
**TypeScript Version:**  3.4 and up

**Search Terms:** 
unknown, 3.4, type inference fails, method overload

**Code**

```ts
type Circle = {
    type: "CIRCLE";
    radius: number;
};

type Square = {
    type: "SQUARE";
    sideLength: number;
};

type Shape = Circle | Square;


class Evt<T> {

    public attach<U>(
        matcher: (data: T)=> [U] | undefined,
        callback: (transformedData: U)=> void
    ): Promise<U>;
    public attach(
        matcher: (data: T) => boolean,
        callback: (data: T) => void
    ): Promise<T>;
    public attach(...args: any[]){
        return null as any;
    }

}

const evtShape = new Evt<Shape>();

//OK
const prRadius = evtShape.attach(
    shape => shape.type === "CIRCLE" ? [shape.radius] : undefined,
    radius => { }
);


const prShape = evtShape.attach(
    shape => true,
    shape => { } //<====== In typescript 3.4 and up shape is unknown 
);
```

**Expected behavior:**

In the last line, shape should be of type Shape. In typescript 3.4 and up it is of type unknown.

**Actual behavior:**

[Playground Link](http://www.typescriptlang.org/play/?ts=3.3.3&ssl=1&ssc=1&pln=43&pc=1#code/C4TwDgpgBAwglgJwMYBtoF4oG8BQV9SiQBcUARDAJIBKMAMgKJkDceBCAhgCZwCuAzqQB2vALYAjCAlYBfVjiLQAygEdeHBBmxt8i0mSUBFAKoBBak1YEo-OFwh0IQgObAAFsLGTpOOTgXgym4ckFCY8MhoUAA+UKrqmvI4qBz8-FAMAG7AADwAKgB82jpQYLziKHBIUBzAwBxIbjnGBQAUJdaitY1SpK1ctRykeQCU6EUA2sYAujEABbxC9gBmcEIQXAA0HQRIHCgo4g0A1n3AnEL8ywD2CKIbACKDpMZjRZnXdiUjpAAKCNdRHB+BBmgUrAQyhUqjU6g03O1rJ1um5elB+s8oKMwkVxNdrmgOEJtkjdvtDic+gN6sMRjioB8vtYflB-oDgaDChD8FDKtVavVGq0AHSijTOQQ1IQgCbTEa4Un4TTAXgIIRQEQHGrpIkgblQGT+Q3Ja6XYBQCDZJTBUKYdYAdwy2Ry1pCEDaI3kAHovQB5ADSJrNpQQ1G4fHSmEtwFdkGFAvhiII-BtGCKKbdwsUYXQmAoNHoTCgAH4oBMM3HODwBLNSIsVmsNiT2OGBPSsAacJ7-EH+OawAhY1po0P43ChSUK2nCAheBBm-gp+2DVAfTlcxvMJR1Yp+EgEHAwOaAMzCgAsUq4UF4YBsqagwOvQmOQmu9vVXaSOCAA)

**Comment by DanielRosenwasser** [comment]
Slightly shorter

```ts
declare class Stream<T> {
    compactAndThen<U>(matcher: (data: T) => [U] | undefined, callback: (transformedData: U) => void): Promise<U>;
    compactAndThen(matcher: (data: T) => boolean, callback: (data: T) => void): Promise<T>;
}

const thing = new Stream<string>();

//OK
const prRadius = thing.compactAndThen(
    str => str.length > 0 ? [str.toLowerCase()] : undefined,
    str => { }
);


const prShape = thing.compactAndThen(
    foo => true,
    bar => { } //<====== In typescript 3.4+, 'bar' is unknown 
);
```

Looks like `bar` gets fixed with no inferences from the first overload. Not sure if there's a way to fix this. @ahejlsberg?

**Comment by garronej** [comment]
After further investigation, I noticed that event in typescript prior to 3.4 altho the type ``Shape`` is inferred it can only be used as a ``{}``. 

![Screenshot 2020-02-13 at 08 54 42](https://user-images.githubusercontent.com/6702424/74412816-87b5d100-4e3e-11ea-8f81-4444ab755897.png)

![Screenshot 2020-02-13 at 08 50 43](https://user-images.githubusercontent.com/6702424/74412548-f9414f80-4e3d-11ea-9351-40b6ec8694da.png)

Thanks to the typescript's team, you guys do amazing work <3

**Comment by garronej** [comment]
Hello, 
Just a quick update to say that this limitation is a big deal for the library I am working on: [EVT](https://evt.land). 
The overload of the "attach" method had to be split into two groups "attach" and "$attach" and peoples get confused about why and when they need to add the "$".  
I know this is really pushing the already amazing type inference system but it would be great for EVT to be able to merge all the overload together.

Regards

**Comment by ahejlsberg** [comment]
The two overloads are just too close for us to distinguish between them. Best alternative I can come up with is a single signature that uses a conditional type:

```ts
declare class Stream<T> {
    compactAndThen<U extends [any] | boolean>(matcher: (data: T) => U | undefined, callback: (data: U extends [infer V] ? V : T) => void): Promise<U extends [infer V] ? V : T>;
}
```

This seems to deliver the desired results.

**Comment by garronej** [comment]
@ahejlsberg  Thank you very much for taking the time to come out with a workaround, it is very clever.
