### ISSUE TITLE
[format] wrong indent in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#3673]
- VSCode 0.3.0
- create a TS file
- put below contents
- Right click -> Format

=> the closing is on the wrong indent

```
var merged = objects.mixin(
	true
);
```

=>

```
var merged = objects.mixin(
	true
        );
```

**Comment by kuon** [comment]
Also see https://github.com/Microsoft/TypeScript/issues/3781#issuecomment-119662750

**Comment by SaschaNaz** [comment]
Fixed by #3738?

**Comment by mhegazy** [comment]
Indeed fixed. thanks @SaschaNaz!

**Comment by kuon** [comment]
Yep, looks good, thanks!
