### ISSUE TITLE
Generics visibility control. Shadow generics.

### ISSUE THREAD

**Issue by reforms** [microsoft/TypeScript#36734]
## Main Idea
Function, Class or something else don't allow use generics explicit. Add ability to declare non visible generics from outside.

## Search Terms
shadow generics, non visible generics, generics visibility control

## Suggestion

Add ability to declare non visible generics from outside

## Use Cases
Keep control above generics visibility

## Examples
Example from <a href="https://www.typescriptlang.org/docs/handbook/generics.html#using-type-parameters-in-generic-constraints">TypeScript handbook</a>

```typescript
function getProperty<T, K extends keyof T>(obj: T, key: K) {
//                   ^  ^ Is there any way to make it non-accessible from outside?
//                   ^ Is there any way to make it non-accessible from outside?
    return obj[key];
}

let x = { a: 1, b: 2, c: 3, d: 4 };

getProperty(x, "a"); // okay

getProperty<any, any>(x, "M"); // okay, but it's not ok
//          ^ Is there any way to make it non-accessible from outside?

// How it might look? For example
function getProperty<shadow T, shadow K extends keyof T>(obj: T, key: K) {
    // some code here
}

getProperty<any, any>(x, "M"); 
//          ^ Now error, because getProperty function dont allow use generics explicit

```

More complex exapmle 
```typescript
type OneField = {
    id: string;
}
type TwoField = {
    id: string;
    data?: string;
}

type DiffType<Free, Strong> = Omit<Free, keyof Strong>
type Constraint<Free, Strong> = Record<keyof DiffType<Free, Strong>, never>
type DirectType<Free, Strong> = Free & Constraint<Free, Strong>

function validate<Free>(data: DirectType<Free, OneField>) {
    // do some work
}

const okData: OneField = null;
const badData: TwoField = null;

validate(okData);
validate(badData); // Error -> It should be so

validate<OneField>(badData); // No error
//       ^ Is there any way to make it non-accessible from outside?
```

## Checklist

My suggestion meets these guidelines:

* [ x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
This seems more like a job for a linter.

Even if you can prevent explicit generic types, you could still type your variables as `any`, e.g. `let x: any = ...`.

**Comment by RyanCavanaugh** [comment]
I don't think there's any way for someone to *correctly* reason that it shouldn't be possible for an external caller to specify explicit type arguments. It really solve anything, because you could just as easily have written:
```ts
validate(badData as OneField); // Still OK
```
or
```ts
const o: OneField = badData;
validate(o); // No error
```
It seems like you're wanting to write functions that aren't stable the in the presence of upcasted data, which implies you actually want contravariance annotations?

**Comment by reforms** [comment]
> It really solve anything

I think about it in a different plane. Hidden generics - the ability to organize encapsulation as a phenomenon, as a dogma. Encapsulation as a process is the right thing for class fields, method fields, and generics too. TypeScript does not allow this now. 
Now you can access private and protected class fields, for example like this
```typescript
class Unprivate {
    constructor(private readonly field: string) {}
}
(<any> (new Unprivate("access to private?"))).field;
```
But this does not mean that we do not need private fields, right?
