### ISSUE TITLE
Enum number return type is not type safe

### ISSUE THREAD

**Issue by ismail-codinglab** [microsoft/TypeScript#36756]
**TypeScript Version:**  3.8.0-dev.20200211

**Search Terms:**
Enum return type, enum strictly typing, enum type safety
**Code**

```ts
enum Hello{
  world
}

const sayHello = ():Hello => {
  return 2;
};
console.log(sayHello()); // 2
```

**Expected behavior:**
An exception/error that `2` is not one of the enum option
and that i should use the enum and not just a number value. Which in the programming world 
 is commonly known as [Magic number](https://en.wikipedia.org/wiki/Magic_number_(programming))

**Actual behavior:**
returns 2
**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=30#code/KYOwrgtgBAEsA28D2BvAsAKClA7kgTvACZQC8UAjJgL6aYDGSIAzgC5TMCGAnnIkmSgAKAJQAuPsjIA+KOixR8wVmHwgoAJgDcNHRkYsk8YADpkAcyFdeCZKJFaoAeieagA

**Hackish workaround:**
```ts
enum Hello{
  world = "1",
}

const sayHello = ():Hello => {
  return "2"; // <-- will give an error
};
console.log(sayHello()); // 2
```

But typescript should make our code more typesafe and give enums the power it should have in first place.

**Comment by AnyhowStep** [comment]
Number enums are not really enums at all. It's "by design", even if many people don't agree.

**Comment by ismail-codinglab** [comment]
Enum numbers are by design meant to be not actually enums and string enums are by design actual enums?

I would just expect number enums to act the same as string enums

Hope you can help me out, it's giving different type restrictions depending on if the Enum is a number or string. 

If many people feel the same then it's good to discuss about it

I think you would agree with me that the restrictions for string enums should also be reflected with number / default enums and will help the developer gain a more strictly typed environment

**Comment by AnyhowStep** [comment]
I don't like it, either. It is what it is, though.

But, yes, number and string enums have different behavior. Also, if you look at the JS emit for number and string enums, you'll see that they're different.

It's worth noting that JS has no actual `enum` type. It's a TS concept. Just like `namespace`.
