### ISSUE TITLE
Incompatibility of `Object.isFrozen(nonObject)` and lib.es5.d.ts

### ISSUE THREAD

**Issue by ypresto** [microsoft/TypeScript#36750]
**TypeScript Version:** 3.8.1-rc

**Search Terms:**

Object.isFrozen
ES5 ES2015

argument is not an Object
Internet Explorer 11
IE11

**Code**

```ts
Object.isFrozen(1)
```

```json
{
  "compilerOptions": {
    ...
    "lib": ["es5"],
  },
  ...
}
```

**Expected behavior:**

```
Argument of type '1' is not assignable to parameter of type 'object'. ts(2345)
```

**Actual behavior:**

No type error, and will get a runtime error.

**Playground Link:**
https://github.com/microsoft/TypeScript/blob/6f079a4ebcb78489eabb523faaf1b69f88e80bd7/src/lib/es5.d.ts#L229
It is just because lib.es5.d.ts accepts any for isFrozen().
For ES5 it should be `object`, then overloaded by lib.es2015.core.d.ts to accept any.

**Related Issues:**

MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen

```js
Object.isFrozen(1);
// TypeError: 1 is not an object (ES5 code)

Object.isFrozen(1);
// true                          (ES2015 code)
```

This issue is found when using ts-polyfill, which is hand-picked core-js polyfills referring to TypeScript builtin type definition.
https://github.com/ryanelian/ts-polyfill/pull/10

**Comment by RyanCavanaugh** [comment]
This would be a breaking change for a lot of working scenarios; we'd need more than one person encountering the problem to justify the risk of changing it now.
