### ISSUE TITLE
[Feature proposal] Counter constraints on dynamic keys

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#36766]
## Search Terms

dynamic key, counters

## Suggestion

Add modifiers on dynamic keys to add constraints on the type definition.

1. would be a `(exactly: number) | (min: number, max: number)` definition (similar to regexp occurences counter).
2. would be to extend the `?` notation to express "0 or more" more explicitly (probably more "graphic" than "required")

This would require to define multiple blocks of the same key type definition and have an additive strategy towards matching key definitions.

## Use Cases

Mostly for arrays but not only ; I can see the potential towards regular objects too.

There's already a way to write "an array of type U with one tuple of type T inside" but it's failing to have dynamic position. The only way to write this is with the spread operator such as `[T, ...U[]]` but an array of shape `[U, T, U]` wouldn't be valid.

This limitation shows that either the way to handle it is not the good one (as for "half a feature/broken/possible but not fully"), or that it should not exist at all.

I propose to handle it differently by extending the "dynamic keys" feature with a totally optional syntax which adds more constraints.

## Examples

```ts
type Foo = 'foo'
type Bar = 'bar'

type EitherRequired = { [k: number](1): Foo | Bar }

const arr1: EitherRequired = ['foo']
const arr2: EitherRequired = ['bar']

type BothRequiredOnce = { [k: number](1): Foo } & { [k: number](1): Bar }

const arr3: BothRequiredOnce = ['foo', 'bar']
const arr4: BothRequiredOnce = ['bar', 'foo']

type OneOrTheOtherOfBoth = EitherRequired | BothRequiredOnce
```

Of course, you may see this example as easily replaceable with `['foo']` instead of `{ [k: number](1): Foo }`, but keep in mind that only 2 types are used. If a 3rd type would be to come, the number of permutations necessary would be of 2^(types)...

Some generic types would also benefit from it:

```ts
type Foo = 'foo'
type Bar = 'bar'

type FooBar = Foo | Bar

type HasOne<T, U = any> = {
  [k: number](1): T
  [k: number]?: U // ? explicitly
}

const arr1: HasOne<Foo> = ['foo', 'bar'] // ok
const arr2: HasOne<Foo> = ['bar', 'foo'] // ok
const arr3: HasOne<Foo> = ['bar', 'foo', 'bar'] // ok

const err1: HasOne<Foo> = ['bar'] // ko: does not contain one Foo
const err2: HasOne<Foo> = ['foo', 'foo'] // ko: contains more than one Foo
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Griffork** [comment]
I personally don't think ? is the best choice for 2. because I feel like it will cause user confusion when used with extends, for example:
```ts
type newType<T extends number?> = T;
type newType<T> = T extends number? never: number;
type newType<T> = T extends number?? never: number;
```

I do like the idea of being able to somehow limit usable numbers without having to do `1|2|3|4|5`, however I personally think this is better captured by the various previous proposals to support different number types (int, uint, float, etc.) mostly because the most common use cases are whether or not a number can include negative values, and whether or not a number can include decimals.

**Comment by y-nk** [comment]
@Griffork Probably the `?` isn't necessary. As much as i understand, dynamic keys have a "0 or more" policy already. It just felt cleaner to have this explicit `?` next to a `(1)`. Please note that i didn't mean to add the `?` right after the type of the key, rather after the bracket, to show that the key itself can be undefined. I remember seeing a similar syntax with `+?` and `-?` but I fail to recall where :/

**Comment by andrewbranch** [comment]
I think this suggestion is more or less subsumed by #15480

**Comment by andrewbranch** [comment]
Also it’s probably worth pointing out you can already do the “exact” case today: https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgIJSnAngdWGACwBEIZR8IAbLAeRAgFFKIBbCcAHgBUA+ZCAB6QQAEwDOaDNm7IAPsgCuo0qAgi+AbwBQyZAAYAXMi4BuHcgDaoEYKMgFLAEbQAuka5zFysvRFmAvlpaNgiUcFAozGDIAkbomLj4xCogFNR0jMxsnPZO0DxBCAD2IGLRcMgAvDEWei4myAD0jci5zlBaxaXRjlU1AIz1TS1t0J5KNj5qWkA

**Comment by y-nk** [comment]
@andrewbranch I'm not sure #15480 qualifies as similar. The Range type is to create "expandable" type definition for suites of things right? It doesn't act on keys, or anything related to an object stucture?

As for your playground link, there's a `[0]: T` which is exactly what i try to avoid. As said in my example, with such a definition, an array of `[U, ..., T, ..., U]` would not fit the type.

**Comment by andrewbranch** [comment]
Huh, I misread your original proposal, thinking the numbers corresponded to indices, not occurrences. Now that we’re on the same page, personally, I’m having a hard time imagining a convincing real-world use for this. I also think there are some semantic issues with some of the relationships you showed, but probably the right place to start is explaining (in a concrete, less generalized way) what problem you want to solve. In other words, we need to see more of the problem before we can think about any given solution. A great explanation would include an example of a real-world scenario that's prone to bugs or coding errors because today’s types are insufficiently describing something.

**Comment by y-nk** [comment]
@andrewbranch thanks for bringing more attention to this proposal.

The typical scenario i'm trying to solve is trying to express an explicit constraint in a (way) broader data architecture which can be summarized as **an array type can have a restrained number of occurences of a specific tuple in it, without constraint of order**

My current project (as much as i can reveal) is composed of one data structure which has an array of string describing which "plugin" it carries. Depending on strings inside this array, the object can fit larger description and method signature.

Let me try to give a more approachable structure without digging too much into "example specific" :

```ts
const MP3_DECODER = 'mp3Decoder'
type Mp3Decoder = typeof MP3_DECODER

const WAV_DECODER = 'wavDecoder'
type WavDecoder = typeof WAV_DECODER

type PluginType = (Mp3Decoder | WavDecoder)

interface MusicPlayer {
  plugins: PluginType[]
  generalConfig: {}

  [rest: string]: any
}

interface Mp3Player extends MusicPlayer {
  plugins: [Mp3Decoder ...PluginType[]] // constraint should tell "plugins[] should contain one occurence of Mp3Decoder, but order doesn't matter
  mp3DecoderConfig: {}
}

interface WavPlayer extends MusicPlayer {
  plugins: [WavDecoder, ...PluginType[]] // constraint should tell "plugins[] should contain one occurence of WavDecoder, but order doesn't matter
  wavDecoderConfig: {}
}

// should be implicitly fitting Mp3Player or WavPlayer type
const somePlayer1 = {
  plugins: [MP3_DECODER, WAV_DECODER],
  generalConfig: {},
  mp3DecoderConfig: {},
  wavDecoderConfig: {},
}

// should not be raising errors
const somePlayer2: Mp3Player = {
  plugins: [WAV_DECODER, MP3_DECODER],
  generalConfig: {},
  mp3DecoderConfig: {},
  wavDecoderConfig: {},
}

// should not be raising errors
const somePlayer3: WavPlayer = {
  plugins: [MP3_DECODER, WAV_DECODER],
  generalConfig: {},
  mp3DecoderConfig: {},
  wavDecoderConfig: {},
}

// should not be raising errors
const somePlayer4: WavPlayer = somePlayer1

function DoSomethingOnlyMp3PlayerCanDo(player: Mp3Player) {}
function DoSomethingOnlyWavPlayerCanDo(player: WavPlayer) {}
```

Here, ideally, `somePlayer` would fit the interface of `Mp3MusicPlayer` **and** `WavMusicPlayer` _implicitly_ so each of the 3 instances would fit into the 2 test functions.

Maybe there's something bigger at stake, like "array scanning" or "array type assertion" since in this particular example, `somePlayer1.plugins` ins casted as `string[]` but should be (by link to constants and types) be of type `PluginType[]` or more strictly `[Mp3Decoder, WavDecoder]` ?

**Comment by y-nk** [comment]
?

**Comment by y-nk** [comment]
🤷‍♂️
