### ISSUE TITLE
NamespaceExport node has inconsistent width

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#36762]
**TypeScript Version:**  3.9.0-dev.20200212

**Search Terms:** NamespaceExport width

**Code**

As seen on ts-ast-viewer.com with typescript@next

![image](https://user-images.githubusercontent.com/1609021/74384410-2e5a8d00-4dbf-11ea-9607-e56f78975f59.png)

```ts
export * as ns from "test";
```

**Expected behavior:** `* as ns` width

This would make it consistent with `NamespaceImport`:

![image](https://user-images.githubusercontent.com/1609021/74384536-724d9200-4dbf-11ea-9ec3-62e0cc908c94.png)

**Actual behavior:** `ns` width (identifier only)

**Comment by andrewbranch** [comment]
Yeah, this does look wrong when judging by the grammar text

<img width="248" alt="image" src="https://user-images.githubusercontent.com/3277153/74488040-e9ddf880-4e75-11ea-8a5c-959f12654f3e.png">
