### ISSUE TITLE
Exporting One Value on Both Default and Named Exports (Circular)

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript#36774]
This is similar to "Re-export class from namespace" (https://github.com/Microsoft/TypeScript/issues/4529)

---

I was recently working with a TypeScript project with `passport-aut0`. I installed the types for it with [the DefinitelyTyped `@types/passport-auth0` declaration file](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/passport-auth0).

Importing the `Strategy` as a named import from `passport-auth0` worked well:

```typescript
import {Strategy} from 'passport-auth0';
```

But the `Strategy` is also exported as a default `export`. So, as in [the Readme](https://github.com/auth0/passport-auth0/blob/master/README.md), you should be able to import it like this:

```typescript
import Strategy from 'passport-auth0';
```

This did not work with `@types/passport-auth0` (before my pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42315). The error message was like:

```
Type 'typeof import("/home/vsts/work/1/s/types/passport-auth0/index")' has no construct signatures.
```

**Comment by karlhorky** [comment]
I wanted to fix this problem for others, and went down the rabbit hole of trying to export / import a value as both a default export and also a named export (with hints from @sandersn).

My solution (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42315) ended up being the following.

The original type definitions looked something like this:

```typescript
//
// The class that will be exported / imported as both:
//
// - name export (works already because `export class`)
// - default export (doesn't work)
//
export class Strategy extends passport.Strategy { /* ... */ }

export interface Profile extends passport.Profile { /* ... */ }
export interface AuthenticateOptions extends passport.AuthenticateOptions { /* ... */ }
export interface StrategyOption { /* ... */ }
export interface StrategyOptionWithRequest extends StrategyOption { /* ... */ }
export interface ExtraVerificationParams { /* ... */ }
export type VerifyFunction = ( /* ... */ ) => void;
export type VerifyFunctionWithRequest = ( /* ... */ ) => void;
```

I had to:

1. **rename the class** from `Strategy` to `StrategyInternal` (so that I can export a circular reference without `Circular definition of import alias` when using `export import ...`)
2. **change the `export` before the class to `declare`**
3. **declare a namespace** with the new name `StrategyInternal` at the bottom of the file
4. **move all of the other interfaces and types to the namespace** and remove the `export`s
5. **update the references inside the class** from eg. `VerifyFunction` to `StrategyInternal.VerifyFunction`
6. **use `export import` inside the namespace** to export the value as a named export
7. **set the default export** with `export = StrategyInternal` at the bottom of the file

Here is the gist of my final solution:

```typescript
declare class StrategyInternal extends passport.Strategy {
	// Updated references to types and interfaces
    // Eg. changing `VerifyFunction` to `StrategyInternal.VerifyFunction`
}

declare namespace StrategyInternal {
	interface Profile extends passport.Profile { /* ... */ }
	interface AuthenticateOptions extends passport.AuthenticateOptions { /* ... */ }
	interface StrategyOption { /* ... */ }
	interface StrategyOptionWithRequest extends StrategyOption { /* ... */ }
	interface ExtraVerificationParams { /* ... */ }
	type VerifyFunction = ( /* ... */ ) => void;
	type VerifyFunctionWithRequest = ( /* ... */ ) => void;

    // NOTE: not true for `export import` statements
    // tslint:disable-next-line:strict-export-declare-modifiers
    export import Strategy = StrategyInternal;
}

export = StrategyInternal;
```

I just wanted to post this as the solution, since it seems to pass the tests and allows either of the styles of imports:

```typescript
import {Strategy} from 'passport-auth0';
```

...or...

```typescript
import Strategy from 'passport-auth0';
```

**Comment by karlhorky** [comment]
Just wanted to post this here so that it will get indexed eventually in search engines.

Closing this out now.

**Comment by sandersn** [comment]
@karlhorky you should mention a couple more things:

1. you can *also* write `import Strategy = require('passport-auth0')` (and `const Strategy = require('passport-auth0')` in JS).
2. `import Strategy from 'passport-auth0'` only works when `"esModuleInterop": true` in tsconfig.

**Comment by karlhorky** [comment]
@sandersn Thanks for the suggestions, done!
