### ISSUE TITLE
Cannot compile jsx if we provide `noImplicitAny` option

### ISSUE THREAD

**Issue by saneyuki** [Microsoft/TypeScript#3679]
we cannot compile jsx if we provide `noImplicitAny` option.

## Reproducible revision

https://github.com/Microsoft/TypeScript/commit/fe4612273ccc2017cfec598521eec5ce30bbd4dc

### command

```sh
tsc test.tsx --jsx react --noImplicitAny
```

### test case: test.tsx

```html
<div>test</div>
```

## Actual Result

```sh
test.tsx(1,1): error TS2602: JSX element implicitly has type 'any' because the global type 'JSX.Element' does not exist.
test.tsx(1,1): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists
```

## Expected Result

Success the compilation  if we provide `noImplicitAny` option.

## Remarks

Of course, this will be success if we don't provide `noImplicitAny` option.

**Comment by RyanCavanaugh** [comment]
As the errors say:

> because the global type 'JSX.Element' does not exist.

and

>  because no interface 'JSX.IntrinsicElements' exists

If you want to compile JSX files, you can define those types:
```ts
declare namespace JSX {
  interface Element { }
  interface IntrinsicElements { div: any; }
}
```

I recommend getting the `react-jsx.d.ts` file from DefinitelyTyped

**Comment by saneyuki** [comment]
aha. Thank you!

**Comment by nahuel** [comment]
Got bitten by this, but now `react-jsx.d.ts` doesn't exists on DefinitelyTyped. Currently the options seems to be:

**typings install react** 
  - for React Version: 15.0.1
  - reads https://github.com/typings/registry/blob/master/npm/react.json referencing https://github.com/cantide5ga/typed-react/commit/42692d400db3c333394ec75bce9f6d09b5a0a769 which seems like a typings refactoring made by @cantide5ga
  - `JSX` definition was REMOVED

**typings install dt~react --global**
  - for React version: 0.14.0
  - installs https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts
  - has `JSX` definition

**npm install @types/react**
  - for React version: 0.14.33
  - installs from https://www.npmjs.com/package/@types/react , which is copied from DefinitelyTyped
  - has `JSX` definition

**Comment by cantide5ga** [comment]
@nahuel not REMOVED, just not yet 'ported'.  Glad to iterate on it if you wouldn't mind opening an issue for it.  Or feel free to make a PR.

I'll get right to it when I get back this weekend from traveling.
