### ISSUE TITLE
High CPU / Disk due to looking for node_modules/@types continuously

### ISSUE THREAD

**Issue by KrishnaPG** [microsoft/TypeScript#36791]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.7.5

**Search Terms**
- windows
- disk 

---

- VSCode Version: 1.42.0
- OS Version: Windows 10 .0.18362

Steps to Reproduce:

1. Launch VS code 
2. Open a normal node.js project without typescript

Does this issue occur when all extensions are disabled?: Yes

VS Code is consuming high CPU (one full core) continuously, looking for a `node_modules/@types` file or folder. Refer the below screenshot (from ProcMon)

![image](https://user-images.githubusercontent.com/4610831/74449080-0728bc00-4ea2-11ea-9a8d-48bf5f12329d.png)

**Comment by mjbvz** [comment]
@KrishnaPG Is `E:` a network drive?

Also, can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After installing that extension and restarting VS Code, do you still see this issue?

**Comment by KrishnaPG** [comment]
> Is E: a network drive?

No, it is on local hard disk (one of the partitions).

> After installing that extension and restarting VS Code, do you still see this issue?

Installed the extension and restarted VS Code. Still the same behavior. Not sure why code.exe is in a relentless pursuit of non-existent `node_modules/@types` in the workspace folder. Usually one would expect it to 

- look once or twice and stop looking any further, or
- use something like an exponential delay before retrying.

Would like to highlight one point, if it makes any difference: the workspace I have (namely, `E:\WinApp\Xperiments`) does not contain `node_modules` folder. It rather contains set of folders, each of which is a different nodeJS project. The workspace folder itself (`E:\WinApp\Xperiments`) is not a nodeJS project. (And even inside those individual project folders where the `node_modules` is present, I could not see `@types` folder.)

**Comment by sheetalkamat** [comment]
@KrishnaPG We need tsserver and ti log for you issue 
using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) to be able to investigate this.
You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Comment by KrishnaPG** [comment]
Here are the files: https://we.tl/t-SwHVq88GGv 

There is nothing problematic in those files, and I do not think this is specific to my machine or setup.  You should be able to reproduce it even with a simple setup as:

- Create a new folder somewhere on your machine
- inside the folder create a new empty js file named `index.js`
- open VS Code and use `open folder` option to open the newly created folder
- Start [Process Monitor ](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and you will start to see VS Code continuously searching for files that do not exist
![image](https://user-images.githubusercontent.com/4610831/80049156-cd260700-852f-11ea-8adc-be69ab1017a3.png)

For your convenience, I have attached the ProcMon Logs: https://we.tl/t-UMQn3wAsY5 but you should be able to observe this behavior on any machine

There seems to be some issue with adding non-existent files/folders to the watch-list and probably that is going on in an error loop.

**Comment by sheetalkamat** [comment]
Yes looking for those directories is by design since we want to detect if you do install dependencies and such ..  looking for them from home directory or being invoked for some unexpected location would be something we would investigate hence we need specific repro to determine the action to take or changes to make to heuristics if at all

**Comment by KrishnaPG** [comment]
"Looking" is not the term I would use to describe this behavior.  Please run the Process Monitor tool to understand the bug.
