### ISSUE TITLE
Use `import` in class or module

### ISSUE THREAD

**Issue by wang-prtimes** [Microsoft/TypeScript#3680]
I want to know why `import` statement isn't allowed when in a class or module.
Is there a way to import module as local variable in class or module !?

```js
class Foo{
    method(){
        import Bar from './FollowerList'; // not allowed       
    }
}

module Foo{
    import Bar from './FollowerList'; // not allowed
}
```

**Comment by mhegazy** [comment]
This is the ES6/ES2015 specification for what a module import/export can be. There is no support for conditional/deferred module loading. TC39 (the JS committee)'s rational was to make modules statically analyzable.

Now if you are not using/planning on using ES6 modules, i.e. you are sticking with commonJS/AMD for a while, you can do this as a normal function call to `require`. e.g.:

```ts
module Foo {
     var Bar = require('./FollowerList');
}
```
see require definition in [node.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts#L30)

**Comment by wang-prtimes** [comment]
Thanks mhegazy!

Seems like I have use the good old 'require()' now :(
