### ISSUE TITLE
Defining a generic type alias with unused type parameters causes a strange behavior.

### ISSUE THREAD

**Issue by swen128** [microsoft/TypeScript#36818]
**TypeScript Version:**  3.7.5

**Search Terms:**
type alias, generic

**Code**
```ts
type Type<T> = {/* type definition without the parameter T */};

function f<T>(x: Type<T>, y: T) { }

const x: Type<boolean> = { };

f(x, 'string');
```

**Expected behavior:**
The above code should compile without any problems,
as it is equivalent to the following code after substitution of the type aliases:

```ts
function f<T>(x: { }, y: T) { }

const x: { } = { };

f(x, 'string');
```

**Actual behavior:**
Argument of type '"string"' is not assignable to parameter of type 'boolean'.

**Related Issues:**
none

<details><summary><b>Output</b></summary>

```ts
"use strict";
function f(x, y) { }
const x = {};
f(x, 'string');

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=1#code/C4TwDgpgBAKuEB4YD4oF4oG8D0AqKokUAJhAGYCWAdhcBQPZVQDutAFvQK7AFvRgBDAE4CAthGAQhsKLmwBfANwAoZWU5UAxnUZQySZAAoAHgC5Y8AwBooIczACUWKPNWbGAZx5mLkBACN6egAbCAEqVAxMFxU1ExsAci8hagBzBIdFIA)

**Comment by RyanCavanaugh** [comment]
From a performance perspective, we need to be able to short-circuit evaluation of generic types when we see two instatiations of the same type. Since there's no legitimate reason to write `Type<T>`, some "weirdness" is an acceptable trade-off.
