### ISSUE TITLE
Include the version number in the downloadable TypeScript_SDK.exe filename

### ISSUE THREAD

**Issue by Jehoel** [microsoft/TypeScript#36829]
## Search Terms

* "typescript_sdk.exe"
* "installer filename"
* "setup filename"

## Suggestion

* The built `TypeScript_SDK.exe` setup file should include the version in the filename.
    * Presently, all setup files of any version of TypeScript from the download page share the same name `TypeScript_SDK.exe`.
* If it's a build for Visual Studio (rather than Visual Studio Code) or another product/host/platform then that information should also be included in the filename.
* So TypeScript 3.7.2's download file would be named `TypeScript_SDK_3.7.2.exe`.
* And as it's for VS2017 and VS2019 for Windows 10 x86/x64 (as opposed to Windows 10 for ARM) then it could be named `TypeScript_SDK_3.7.2_Dev15_Dev16_x86.exe` for example.

I assume this is something that can be set-up in the DI / CI / CD workflow.

## Use Cases and Examples

* For keeping track of which downloaded files correspond to which versions of TypeScript.
* For allowing easy project dependency archival by allowing us to copy+paste/move the setup files to on-prem dependency archives without having to manually rename them first.
* I've downloaded different versions of TypeScript and forgot to rename them so my downloads folder was full of `TypeScript_SDK.exe`, `TypeScript_SDK (2).exe`, `TypeScript_SDK (3).exe` and so on. 
    * It was actually faster for me to redownload them all and save them with the right name from the browser save-file dialog instead of inspecting each file.
* While the version number *is* present in the `VERSIONINFO` resource, Windows 10's File Explorer does not show `VERSIONINFO` details in the file list details sidebar pane nor the Status Bar - you instead have to open the File Properties dialog and open the Details tab for each file individually.
    * You can enable the "File version" column in File Explorer too - but that's a hassle as that's a per-folder setting and File Explorer doesn't reliably remember folder view settings - it also only shows the version number without any platform details - and obviously doesn't help you if you're in Tile or Icon view mode.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). (*Edit*: Well, it's orthogonal, but it doesn't _disagree_ with TypeScript's design goals).

**Comment by minestarks** [comment]
This is pretty solid suggestion - I agree it would be an improvement. @uniqueiniquity can you think of anything that would break if we did this?

**Comment by uniqueiniquity** [comment]
Not off the top of my head - sounds reasonable to me as well.

**Comment by minestarks** [comment]
The filename should be updated in our next release. Thanks for the suggestion!
