### ISSUE TITLE
Please support SharedWorker.

### ISSUE THREAD

**Issue by Lalavava** [microsoft/TypeScript#36824]
## Search Terms

SharedWorker

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
This does not seem to be a valid feature request as it does not contain all the required information from the template.  

Likely duplicate of #24323

**Comment by RyanCavanaugh** [comment]
SharedWorker
