### ISSUE TITLE
callable interface as parameter allows unknown properties

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#36826]
**TypeScript Version:**  3.9.0-dev.20200215

**Search Terms:** callable interface

**Code**

```ts
// callable interface
interface Accepted {
  (): void;
  foo: string;
}

function rejected() { }
rejected.foo = "";
rejected.bar = "";

function check(a: Accepted) { }

// desired: should reject unknown properties
// fail: accepts unknown properties
check(rejected);
```

concrete example
```ts
interface ForwardRefRenderFunction<T, P = {}> {
  (props: P, ref: Ref<T>): ReactElement | null;
  displayName?: string;
}

function forwardRef<T, P = {}>(render: ForwardRefRenderFunction<T, P>): ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<T>>;

function Component() {
  return null;
}

Component.propTypes = {}

// should be rejected since `propTypes` aren't supported and add a runtime warning
forwardRef(Component);
```

**Expected behavior:**
- unknown properties on functions are rejected

**Actual behavior:**
- unknown properties are accepted

**Playground Link:** 

- [using nightly](https://www.typescriptlang.org/play/?ts=Nightly#code/PTAEGMEMBtsgjaBTUBLAdgFyQJwGaThIBQG2+hKAguEQA7YAmoA3saKABQCUAXKADcA9qkYBudqDxCh-AM6YcGAOYSAvsWJ4ArunCZUQ9KEL0mPVqA2mkDJIwB00oaAC8oAOQeJW3fsPGOEgAVkj69hYsVsRBoeGOzm6gAETJErFhTA7wkDhJqT46egZGEAAWYQDWnJD8NGb23JYaxOAV4NU2dozcEiCgjEhyqEGM8mVC2tDMGfqgupXoQgDuxnQ4QnS4BkPE-QSo0PxdmHLz6IsraxtbODtyre3Vs0y9mvt+JcZkuHKZ9qBlqhMGVQEJ4HFMMRMABPLageq2JgANQATElOBZXAA+QQiHqgABklmc8kUKishU+AVAL3saMi0TpjDRThk+TSMRC-xZqOyuQ5VOKNLaVQZtQRtCR9NRTSiLX6g2Go3Gk2mtO5cwWS1WoHWm22qF2+0gh2OUoYZ21Vz1N0Nu1FHQZzLRbz2YGGAFs6MgwRDMqQsLgCERQABRAAehEwrEkpNACiU6FUxBaRX8pUdlUj0c4SH4Of0cui7oTEymM01Metuv1t3upbokDkD36ABJI1t9GGcBscI8qoXMJwovGvAAaUA5HD8DwARg8Vm4QA)
- [using 3.9.0-dev.20200215](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200215#code/PTAEGMEMBtsgjaBTUBLAdgFyQJwGaThIBQG2+hKAguEQA7YAmoA3saKABQCUAXKADcA9qkYBudqDxCh-AM6YcGAOYSAvsWJ4ArunCZUQ9KEL0mPVqA2mkDJIwB00oaAC8oAOQeJW3fsPGOEgAVkj69hYsVsRBoeGOzm6gAETJErFhTA7wkDhJqT46egZGEAAWYQDWnJD8NGb23JYaxOAV4NU2dozcEiCgjEhyqEGM8mVC2tDMGfqgupXoQgDuxnQ4QnS4BkPE-QSo0PxdmHLz6IsraxtbODtyre3Vs0y9mvt+JcZkuHKZ9qBlqhMGVQEJ4HFMMRMABPLageq2JgANQATElOBZXAA+QQiHqgABklmc8kUKishU+AVAL3saMi0TpjDRThk+TSMRC-xZqOyuQ5VOKNLaVQZtQRtCR9NRTSiLX6g2Go3Gk2mtO5cwWS1WoHWm22qF2+0gh2OUoYZ21Vz1N0Nu1FHQZzLRbz2YGGAFs6MgwRDMqQsLgCERQABRAAehEwrEkpNACiU6FUxBaRX8pUdlUj0c4SH4Of0cui7oTEymM01Metuv1t3upbokDkD36ABJI1t9GGcBscI8qoXMJwovGvAAaUA5HD8DwARg8Vm4QA)

**Related Issues:**

**Comment by MartinJohns** [comment]
This is intended behavior and due to TypeScripts structural type system. Your `rejected` function fulfills everything that `Accepted` demands to be present.

https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by eps1lon** [comment]
> Your rejected function fulfills everything that Accepted demands to be present.

Sure. As does the the object. But for objects typescript rejects unknown properties. 

So if we're talking with structural typing in mind the behavior between passed objects and functions shouldn't change.

**Comment by MartinJohns** [comment]
The behavior is the same for objects. If it matches the interface then it's compatible, even if it has additional proprtierties.

You probably confuse this with the excess property checks that happens for objects literals. But you're not creating an object literal here.

**Comment by eps1lon** [comment]
> You probably confuse this with the excess property checks that happens for objects literals. But you're not creating an object literal here.

I was which is why I got confused: `checkExact({ foo: '', bar: '1' })` threw while `const object = { foo: '', bar: '1' }; checkExact(object)` does not.

#12936 is exactly what I'm looking for.
