### ISSUE TITLE
There is code action to delete declaration for private method without noUnusedLocals#true

### ISSUE THREAD

**Issue by vagusX** [microsoft/TypeScript#36820]
**TypeScript Version:**  3.7.5

**Code**

```ts
export class Klass {
  private handleTest() {
    console.log('123')
  }
}
```

**Expected behavior:**

Fill the code into [tslang playground](http://www.typescriptlang.org/play/?experimentalDecorators=true&ssl=1&ssc=1&pln=6&pc=1#code/KYDwDg9gTgLgBAYwDYEMDOa4GlUbgbwFgAoOOMKASwDcUZg4ALFAOwBMlgAVYNGACgCUBEmTIIILNBE4A6JBADm-AOQBGAEwBmFYNFwAviSPEgA)

![image](https://user-images.githubusercontent.com/6828924/74588829-b7312d00-503a-11ea-9277-b68b18385f49.png)

I got a lightblub and tooltip for method `handleTest`, telling `'handleTest' is declared but its value is never read.(6133)`, and there is a code action `Remove declaration for: handleTest`, it's clearly that `noUnusedLocals` option is false,

![image](https://user-images.githubusercontent.com/6828924/74588827-b0a2b580-503a-11ea-8661-f690aa049c17.png)

And I meet the same situation in vscode.

**Actual behavior:**

According to the docs [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals), I'm confused why these is tip for private method without noUnusedLocals#true ?

**Playground Link:** 

http://www.typescriptlang.org/play/?experimentalDecorators=true&ssl=1&ssc=1&pln=6&pc=1#code/KYDwDg9gTgLgBAYwDYEMDOa4GlUbgbwFgAoOOMKASwDcUZg4ALFAOwBMlgAVYNGACgCUBEmTIIILNBE4A6JBADm-AOQBGAEwBmFYNFwAviSPEgA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is working as intended, though the intent is somewhat strange.

If `noUnusedLocals` is *explicitly set to `false`*, then you won't see these suggestions.

If `noUnusedLocals` is *explicitly set to `true`*, then you will see errors + a suggestion.

If `noUnusedLocals` is *not set at all*, then you will see suggestions without errors.

The Playground doesn't offer a tri-state checkbox for UI simplicity reasons.

**Comment by vagusX** [comment]
@RyanCavanaugh Thanks for your reply, but the first rule is not working, you can try this codesandbox demo, https://codesandbox.io/s/romantic-sunset-ruhh8?fontsize=14&hidenavigation=1&theme=dark,
I've already set `noUnusedLocals` to `false` in `tsconfig.json`, and there is still a suggestion.
