### ISSUE TITLE
Dynamic Object Key is strange when using with keyof

### ISSUE THREAD

**Issue by macabeus** [microsoft/TypeScript#36848]
## Search Terms

keyof, dynamic object key

## Suggestion

In my option, there is a strange behaviour when using `keyof` with a dynamic object.
For example, let's see this simple code:

```ts
type TDynamicKey = { [key: string]: string }
type Magic = keyof TDynamicKey
```
[_Playground_](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=32#code/C4TwDgpgBAKgIiAdgQwLYEsDGBpCIoC8UA3lANoDWeAXFAM7ABO6iA5gLq0PNtQC+AWABQoSFACyyVlkJQqIAPYAzWAhQYceYUA)

Which will be the type of `Magic`?
- `string`
- `string | number`

The correct choice is the second.
But since the keys will be just `string`, why we are receiving `number` too? I think that `Magic` should be just `string`.

```ts
type TDynamicKey = { [key: number]: string }
type Magic = keyof TDynamicKey // type Magic = number
```

In this situation works as expected. Just `number`.

**Comment by jcalz** [comment]
This is working as intended, see [TS2.9 release notes, support for `number` in `keyof`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-number-and-symbol-named-properties-with-keyof-and-mapped-types).

**Comment by macabeus** [comment]
@jcalz 

> Given an object type `X`, `keyof X` is resolved as follows:
> - If `X` contains a string index signature, `keyof X` is a union of `string`, `number`, and the literal types representing symbol-like properties, otherwise

Okay. It is working as intended. But what is the reason for this behaviour? Just `string` wouldn't be better?

**Comment by dragomirtitian** [comment]
TS tries to model the behavior of JS. In JS, you can't have a key of type `string` and one of type `number` with the same value . Also if you index using a number and the equivalent string value is present, you will get the key. So while a bit surprising, it is consistent with the way JS actually works: 

```ts
console.log({ "0": "A" }[0]) // "A"
console.log({ 0: "A" }["0"]) // "A"
console.log({ 0: "A", "0": "B" }["0"]) // "B" (also duplicate key error in TS which is ok)
console.log({ 0: "A", "0": "B" }[0]) // "B" (also duplicate key error in TS which is ok)

```

[Playground Link](https://www.typescriptlang.org/play/#code/MYewdgziA2CmB00QHMAUBvABAIgAzYC4cBBbTAXwG1cBdASkwHpGTsAoUSGBJNLXItlIVKebPSYsh7TlDiIUGTANYAaHPkEAhMlTETmOHZlQBDaFEwATAK4AHaAEtgpgC6xMAa1gBPTLAAnAJAAzEcwTAAVAGVMAHcAC2cEsIhMEE86DnA5HkV+QVJ1MW1dagMpYzMLEGt7Jxd3L19-IJCwiJj4pOAUxzSMhiA)

**Comment by macabeus** [comment]
@dragomirtitian 
![pickachu-surprised](https://66.media.tumblr.com/60aeee62dc1aee0c3c0fbad1702eb860/tumblr_inline_pfp352ORsk1r4hkfd_250.png)

So, okay. I understand better now.
For me, this issue could be closed and tagged and `working as intended`.

**Comment by zanza00** [comment]
I have the same problem. One solution that I found is to use `Record<string, string>`.


[link to playground](https://www.typescriptlang.org/play/#code/C4TwDgpgBAKgIiAdgQwLYEsDGBpCIoC8UAShJgPYBOAJgDwDOwl6iA5gDRSPNsB8AsAChQkKAFlkrLISgBrPOQBmsBCgw48QoA)

```ts
type TDynamicKey = Record<string, string>
type Magic = keyof TDynamicKey
```

Hope this helps.
