### ISSUE TITLE
Project build ignores changes in node_modules imports

### ISSUE THREAD

**Issue by aslatter** [microsoft/TypeScript#36842]
**TypeScript Version:**  3.8.1-rc

**Search Terms:** tsc project build --build -b node_modules declarations

**Code**

Demo project is here: https://github.com/aslatter/ts-demo-project-ref

This demo project contains:

* src/node_modules/some_import.d.ts - an example dependency defining a const enum
* src/index.ts - an example project file using the above enum

The following script will checkout the demo project, build "v1", switch to "v2" and build "v2", both builds using "npx tsc --build".

```sh
git clone https://github.com/aslatter/ts-demo-project-ref
cd ts-demo-project-ref
git checkout v1
npm install
npx tsc --build --verbose
git checkout v2
npx tsc --build --verbose
```

**Expected behavior:**

"v2" and "v1" contain different definitions for the const enum. I expected the second build to update the generated "index.js" to reflect the changes in *some_import.d.ts*.

**Actual behavior:**

The const-enum in *node_modules* changes, but that change is not picked-up by *tsc --build*, leading to incorrect behavior at runtime.

After running through the above:

# some_import.d.ts
```ts
export const enum MyEnum {
    Foo = 15,
    Bar = 20,
}
```

# index.js
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function main() {
    console.log(10 /* Foo */);
}
exports.main = main;
```

I expected the console.log invocation to be *console.log(15 /* Foo */);*, to match the declaration.

**Comment by RyanCavanaugh** [comment]
`--build` mode assumes that a project is up to date if its specified inputs are up-to-date relative to their outputs. Additionally, all outputs *must* have prespecified inputs (this is subtle). For files which don't produce outputs (e.g. `.d.ts`), the assumption is that those files don't affect the up-to-dateness of the build, so it's acceptable if those files aren't specified at all.

This means that a change in a file that isn't prespecified (e.g. is in `node_modules` and gets picked up via an `import`) can't be detected by the "is the build up to date check" - the up-to-date check has to be fast to be useful, and so we don't spend the CPU cycles to parse the entire set of input files to determine what other files should be included, so we don't even know that a .d.ts file changed.

Options available:
 * I believe you could add this `.d.ts` file to your `files` list and we'd correctly detect it as out-of-date
 * Enable `--isolatedModules`, which adds additional checks that prevent you from getting into this situation
 * Just run `--build --force` after running `npm ci` (probably good policy regardless)

**Comment by aslatter** [comment]
For our part, we ended up tweaking the particular testing-utility which was prone to this sort of thing (the utility intentionally compares different commits in our git repo, and we weren't nuking the work-tree completely in-between).

Thanks for taking a look at this.
