### ISSUE TITLE
Incorrect comment placement on transpiling `super` call

### ISSUE THREAD

**Issue by YoDaMa** [microsoft/TypeScript#36859]
**TypeScript Version:**  3.7.5

**Search Terms:** typescript comment

**Expected behavior:** Transpiles comment before declaration of variable.

**Actual behavior:** Transpiles comment into the middle of declaration of variable.

**Related Issues:**
This is related to the following bug in NYC, a code coverage checker for Babel/Typescript/Javascript
https://github.com/istanbuljs/nyc/issues/1274

The problem with having the comment end up in the middle of the declaration is then `nyc` cannot use the comment to know to skip the variable definition.

**Code**
```ts
export class ArgumentError extends Error {
  constructor(message?: string) {
    /* istanbul ignore next */
    super(message);
    this.name = 'ArgumentError';
    this.message = message as string;
    (<any>Object).setPrototypeOf(this, Error.prototype)
  }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var ArgumentError = /** @class */ (function (_super) {
    __extends(ArgumentError, _super);
    function ArgumentError(message) {
        var _this = 
        /* istanbul ignore next */
        _super.call(this, message) || this;
        _this.name = 'ArgumentError';
        _this.message = message;
        Object.setPrototypeOf(_this, Error.prototype);
        return _this;
    }
    return ArgumentError;
}(Error));
exports.ArgumentError = ArgumentError;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?target=1&module=1&ssl=9&ssc=2&pln=1&pc=1#)

**Comment by RyanCavanaugh** [comment]
I don't think this is actionable. The comment is just before the super call expression in the pre-emit, and TS placed the comment just before the super call expression in the post-emit. Moving it elsewhere will just break someone else instead.

**Comment by YoDaMa** [comment]
@RyanCavanaugh I see what you're saying, but the post-emit has just added a line break between the variable assignment and the super call expression. Why move it between the two, if you are generating the whole lien out of the pre-emit super call?

**Comment by vitaly-t** [comment]
This shouldn't be closed, because what we have now here, test guys are pointing finger at TypeScript developers, while TypeScript developers are pointing at test (Istanbul) developers. All the while, leaving developers out to dry.

```ts
export class MyError extends Error {

    constructor(msg: string) {
        /* istanbul ignore next */
        super(msg);

        Object.setPrototypeOf(this, MyError.prototype);
    }
}
```

This translates into the following:

```js
     var _this = 
        /* istanbul ignore next */
        _super.call(this) || this;
```

As a result, `|| this` part is never test-covered, and it cannot be excluded from tests either.

**Comment by vitaly-t** [comment]
After a bit more analysis, I can see that `istanbul` frameworks can do absolutely nothing here. It is TypeScript issue, splitting the code and the comment like that, it is a dangerous premise, which now shows its ugly side.
