### ISSUE TITLE
'Auto import feature' works incorrectly

### ISSUE THREAD

**Issue by nighttiger1990** [microsoft/TypeScript#36850]
`Auto import` feature work incorrectly. 
Follow my picture. When i type `<Main`: `Auto import` feature show `Auto import from 'src/MainApp'`. But correct is `./src/MainApp`. 

**TypeScript Version:**  3.7.5
This is 'Auto import' show:
![image](https://user-images.githubusercontent.com/21042933/74723269-e29b5e00-526c-11ea-9bf5-4c957dfa6d08.png)

This is my folder structure:
![image](https://user-images.githubusercontent.com/21042933/74722647-dbc01b80-526b-11ea-94f6-2c7c557a2cfb.png)

**Expected behavior:**
Show correct path, example `'./src/MainApp'` instead of `'src/MainApp'`
**Actual behavior:**
Show incorrect path, example `'src/MainApp'`
**Step for this bug**

1. Create Project React-Native: `npx react-native init TSProject --template=react-native-template-typescript`
2. Create `src` folder inside 'TSProject' folder
3. Create file `MainApp.tsx` then create `MainApp` component
4. Inside `App.tsx` type `<Main` then press `Ctrl + Space`

**Comment by RyanCavanaugh** [comment]
Fixed in 3.8.0
