### ISSUE TITLE
New Website Logo: Ignite (Infragistics)

### ISSUE THREAD

**Issue by MariaTimova** [Microsoft/TypeScript#3685]
Please fill the following out:

- Name: Ignite UI
- Homepage url: http://www.igniteui.com/
- Brand Guidelines/Licensing: I am Josh Anderson the Director of Marketing at Infragistics.  You have permission to use our logo
- Logo: 
![vector_logo_final_ignite_ui](https://cloud.githubusercontent.com/assets/11754033/8425870/102246aa-1f13-11e5-8adf-4702d2e1dc26.png)
(svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by jonathandturner** [comment]
I was just trying this out on the website and I noticed that you have "UI" in white.  You'll notice above that the white blends into the white of the site (and the GitHub page also).

Do you have a logo that's safe to put on a white background?

**Comment by MariaTimova** [comment]
Hi Jonathan,

Thank you for letting me know about this. 

Here is another logo that can be used on a white background: 
![ignite-logo](https://cloud.githubusercontent.com/assets/11754033/8674862/40f9c97e-2a49-11e5-9ed2-9d94a1a703af.png)

**Comment by MariaTimova** [comment]
Hi Jonathan,

Thanks for helping with the process.
