### ISSUE TITLE
Automate release branch creation

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#36863]
We need to perform the following tasks every time we create a `release-*.*` branch:

1. TypeScript creates a branch from `master` on GitHub.
1. TypeScript updates the version on that branch to `beta`.
    1. Update `package.json`
    1. Update `src/compiler/corePublic.ts`
1. TypeScript LKGs the branch.
1. SDK script is updated to sync from that branch.

We should find a way to do all of this "at once".

**Comment by orta** [comment]
Could the creation of the tag on the repo be the trigger for this? I've done this kind of stuff with Danger  ( https://github.com/danger/peril-settings/blob/master/org/new_tag.ts )

**Comment by uniqueiniquity** [comment]
I think the tag happens after all of this - there still may be changes in the release branch before the beta tag is created

**Comment by weswigham** [comment]
I've setup an action to [create release branches](https://github.com/microsoft/TypeScript/actions?query=workflow%3A%22New+Release+Branch%22). To do the VS half, it should just need another step at the end for sending a request to trigger a pipeline on the VS devops instance that sets up the new sync target.

The more open question is the preferred way to start this whole `new-release-branch` workflow. In devops, that's an easy question to defer, as I can always say "well, just trigger it by hand in devops", but not so for GH actions - these need to be wired into _something_ to fire off the build request. I could add an `@typescript-bot` github comment trigger; but our release process doesn't have, like, a "release tracking issue" (like VSCode does), so there's no natural issue to make a comment on. I could add the functionality to our teams bot, but, per daniel, "Oh right, teams doesn't work on mobile [without intune enrollment which nobody is going to do]".

Should we change our release process to have a release tracking issue? Should we still wire it up with teams as a chatbot despite its shortcomings? Should we be extra-special and make a web frontend for release management (seems like overkill, IMO)?

**Comment by weswigham** [comment]
There is now a `@typescript-bot create release-X.Y` task that can be used in issues. Ideally, it should be used in a release tracking issue (where anything to do pertaining to the upcoming release process can be collected).

I can prepare tasks for the other common release branch activities, like syncing with `master` (for pre-RC), doing an LKG (if a cherry-pick-and-LKG command on a PR is insufficient), changing the release tag+version (from `0-beta` to `0-rc` to `.1`, to `.2` and beyond), and, hopefully, triggering the final publish task.

With all that in place, all we should need is appropriate triggers for the VS SDK builds, right?

**Comment by JCMais** [comment]
@weswigham this is unrelated, but is the typescript-bot source code available somewhere? How are you guys triggering actions from PR comments?

**Comment by weswigham** [comment]
Yeah, it's linked in the [wiki article](https://github.com/microsoft/TypeScript/wiki/Triggering-TypeScript-Bot) explaining its commands, iirc.

**Comment by RyanCavanaugh** [comment]
This is "done enough" I think
