### ISSUE TITLE
Requesting support for variadics with varargs in arbitrary but contiguous positions in .d.ts files

### ISSUE THREAD

**Issue by aholmes** [Microsoft/TypeScript#3686]
Some libraries with variadic methods that use varargs don't always place the parameters at the end of the parameter list. One such example is lodash's `assign` method whose signature and API documentation is as follows.

`_.assign(object, [sources], [customizer], [thisArg])`

  1. object (Object): The destination object.
  2. [sources] (…Object): The source objects.
  3. [customizer] (Function): The function to customize assigned values.
  4. [thisArg] (*): The this binding of customizer.

TypeScript does not currently support this use case, and will report the error "A rest parameter must be last in a parameter list."

A way around this is to write an arbitrary number of method declarations (which is what lodash's .d.ts file does); one for each possible length of varargs. As I'm sure is clear, the arity being infinite, there is a concrete limit to how many of these declarations can exist. It also unfortunately "dirtys" the type hinting, making the method look more complex than it is. Lastly, maintaining these kinds of declarations is prone to error.

Edit:

Having thought about this a bit more, I realize the issue may actually lie with the .d.ts file. The documentation for writing declaration files recommends that optional parameters are not supplied as part of a function declaration. A possible fix, then, is to write another declaration with the varargs, and one without.

**Comment by danquirk** [comment]
We have had previous requests for this (not requiring optional/rest params to be last) but I cannot find them via search at the moment...

**Comment by DanielRosenwasser** [comment]
#1024 seems vaguely related. Maybe that's what you're looking for @danquirk

**Comment by danquirk** [comment]
No I think it was a specific request for optional parameters in the middle of the param list due to some particular JavaScript APIs doing this.

**Comment by aholmes** [comment]
Is it #1360?

**Comment by danquirk** [comment]
That looks like it, thanks. Will close this as a dupe unless there's something unique to your request that isn't captured there.
