### ISSUE TITLE
Unable to write a type to represent an array of length 0

### ISSUE THREAD

**Issue by Lalavava** [microsoft/TypeScript#36868]
**TypeScript Version:**  3.7.5

**Code**

```ts
const a: {length: 0,[index: number]: number} = []
```

**Expected behavior:**
Compile successfully

**Actual behavior:**
error TS2322: Type 'undefined[]' is not assignable to type '{ length: 0; }'.
  Types of property 'length' are incompatible.
    Type 'number' is not assignable to type '0'

**Comment by thebanjomatic** [comment]
Can you just use an empty tuple type?

```ts
const a: [] = [];
a.length; // 0
```

**Comment by Lalavava** [comment]
> Can you just use an empty tuple type?
> 
> ```ts
> const a: [] = [];
> a.length; // 0
> ```

I need to represent an array of fixed size.
If the above code does not compiled and you need to distinguish between the two case:
one for length is not 0,for example const a: {length: 1,0: number}
one for length is 0.

I've actually written a fixed-size array type using type metaprogramming
```ts
type Bool = "true" | "false"

type UInt = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | "undefined"

type PrevUInt<I extends UInt> = {
    [P in UInt]: {
        undefined: "undefined",
        0: "undefined",
        1: 0,
        2: 1,
        3: 2,
        4: 3,
        5: 4,
        6: 5,
        7: 6
    }[P]
}[I]

type NextUInt<I extends UInt> = {
    [P in UInt]: {
        undefined: "undefined",
        0: 1,
        1: 2,
        2: 3,
        3: 4,
        4: 5,
        5: 6,
        6: 7,
        7: "undefined"
    }[P]
}[I]

type UIntEq<A extends UInt,B extends UInt> = {
    undefined: "undefined",
    0: {
        undefined: "undefined",
        0: "true",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "false",
        6: "false",
        7: "false"
    }[B],
    1: {
        undefined: "undefined",
        0: "false",
        1: "true",
        2: "false",
        3: "false",
        4: "false",
        5: "false",
        6: "false",
        7: "false"
    }[B],
    2: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "true",
        3: "false",
        4: "false",
        5: "false",
        6: "false",
        7: "false"
    }[B],
    3: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "true",
        4: "false",
        5: "false",
        6: "false",
        7: "false"
    }[B],
    4: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "true",
        5: "false",
        6: "false",
        7: "false"
    }[B],
    5: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "true",
        6: "false",
        7: "false"
    }[B],
    6: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "false",
        6: "true",
        7: "false"
    }[B],
    7: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "false",
        6: "false",
        7: "true"
    }[B]
}[A]

type UIntLessThan<A extends UInt,B extends UInt> = {
    undefined: "undefined",
    0: {
        undefined: "undefined",
        0: "false",
        1: "true",
        2: "true",
        3: "true",
        4: "true",
        5: "true",
        6: "true",
        7: "true"
    }[B],
    1: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "true",
        3: "true",
        4: "true",
        5: "true",
        6: "true",
        7: "true"
    }[B],
    2: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "true",
        4: "true",
        5: "true",
        6: "true",
        7: "true"
    }[B],
    3: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "true",
        5: "true",
        6: "true",
        7: "true"
    }[B],
    4: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "true",
        6: "true",
        7: "true"
    }[B],
    5: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "false",
        6: "true",
        7: "true"
    }[B],
    6: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "false",
        6: "false",
        7: "true"
    }[B],
    7: {
        undefined: "undefined",
        0: "false",
        1: "false",
        2: "false",
        3: "false",
        4: "false",
        5: "false",
        6: "false",
        7: "false"
    }[B]
}[A]

type IntRange<Min extends UInt,Max extends UInt> = {
    true: IntRange<NextUInt<Min>,Max> | Min,
    false: Min,
    undefined: "undefined"
}[UIntLessThan<Min,Max>]

type Array<T,Size extends UInt> = {
    [P in IntRange<0,PrevUInt<Size>>]: T
} & {length: Size}
```
Typescript are many limitations when to metaprogramming
1.Recursion is not supported
2.SFINAE is not supported

**Comment by AnyhowStep** [comment]
There are easier ways to do what you want. It looks like you want to be able to say `Tuple<T, Size>` and have a tuple of the given size, without repeating the same element multiple times.

**Comment by AnyhowStep** [comment]
Also, this works,
```ts
const a: {length: 0,[index: number]: number} = [] as const
```

**Comment by Lalavava** [comment]
> Also, this works,
> 
> ```ts
> const a: {length: 0,[index: number]: number} = [] as const
> ```
> 
> Introducing SFINAE and template overloads would make life wayyyyy moreeee complicated



> There are easier ways to do what you want. It looks like you want to be able to say `Tuple<T, Size>` and have a tuple of the given size, without repeating the same element multiple times.
> 
> ```ts
> type PushFront<TailT extends any[], HeadT> = (
>   ((head : HeadT, ...tail : TailT) => void) extends ((...arr : infer ArrT) => void) ?
>   ArrT :
>   never
> );
> 
> type MyTuple<T, LengthT extends number, ResultT extends T[] = []> =
>     {
>         0: T[],
>         1: ResultT,
>         2: MyTuple<T, LengthT, PushFront<ResultT, T>>
>     }[
>         number extends LengthT ?
>         0 : 
>         ResultT["length"] extends LengthT?
>         1 :
>         2
>     ]
> ;
> 
> //const len0: []
> declare const len0: MyTuple<string, 0>;
> //const len1: [string]
> declare const len1: MyTuple<string, 1>;
> declare const len2: MyTuple<string, 2>;
> declare const len3: MyTuple<string, 3>;
> declare const len4: MyTuple<string, 4>;
> declare const len5: MyTuple<string, 5>;
> declare const len6: MyTuple<string, 6>;
> declare const len7: MyTuple<string, 7>;
> declare const len8: MyTuple<string, 8>;
> declare const len9: MyTuple<string, 9>;
> //const len10: [string, string, string, string, string, string, string, string, string, string]
> declare const len10: MyTuple<string, 10>;
> //const len42: [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, ... 20 more ..., string]
> declare const len42: MyTuple<string, 42>;
> 
> //const lenNum: string[]
> declare const lenNum: MyTuple<string, number>;
> ```
> 
> [Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=40&pc=1#code/C4TwDgpgBACgrgZwBYDEBOB7AdsAPAFQEMBLAG3yggA9gIsATBKQrEAbQF0AaKACQkL18APigBeKAAoAUFCmSkA+lABcfJfh4A6HcBKlVUImXwBKcaIBuGYvXPVaDJpMk6thNGkPEsAMwheAIKeZhZQ1rbmAPyyUMFoFCqxWBCWAdKmANzS0qCQUACyIPhwYKQQBDwAMnQA5sBIFA50jFBYcAC2AEYBPABKEAhwpMBNNC1M+JziUJyiYrFyAN6LcmsADGpT3KtrUACMagNDI5q7awBMakUlZRWaUDVY9Y088Mjo2HjHw6M8IsJVgBfNjnOTtboBSjjJyPOoNCgxPZ7daGMFQH6nNgAInKzwa2I40McrSeL3wSORcn2qnRF1WHGk2WkAHoWQBjbAIYBQPGbWaM+gQdmkDzQTlYbm8uj8m6lcq4bloHy1HjrYTZNkSqV4w6zJUqwXC0VocVcnm667FeUVA3PHj7DXSIUisVQbUWuhXQrWu6K4DK+1QC5Ol0ms2Sz1YADMVtuCrtqqg0dDxrdHulWAALHGbf7A0ms6nXab3ebMwBWXN+xM8CvF8NlyOZgBs1YTAZVPBbDfT5bxAHZ27bO0GB73Sxm8QAOYf5rtQacTiM6ugATjntaga6dWv7dH2-LYW5Po6Tp4LPAvC+vQcTRpLK6jh83Z4d6s1HP32e9x7fUFvc9-0Aq9gLAy8APAm8oLvGCgIgkDIIQuDtB0YNUQ6DBSzcUCCwfRspzoLNvTlGt-2Ip1WS-Zs8QAOU6NRE04Z000nb96I6V8IIhHo0CdIA)
> 
> If you want tuples longer than length 42, you're going to have to implement type-level trampolines.

Nice code.
But I still don't quite understand why need "as const" to compile successfully.

**Comment by AnyhowStep** [comment]
I'm not on my computer now, so I might be wrong, but,

The **value expression** `[]` alone gets inferred as the **array type** `never[]` (`length : number, [index : number] : never`),
rather than the **empty-tuple type** `[]` (`length : 0, [index : number] : never`)

The **value expression** `[] as const` makes TS infer the **readonly empty-tuple type** `readonly []` (`length : 0, readonly [index : number] : never`)

And readonly properties are assignable to mutable properties (it's weird, I know).

So, `length : 0, readonly [index : number] : never` is assignable to `length : 0, [index : number] : number`.

`never` is assignable to every other type (including `number`)
