### ISSUE TITLE
Type resolution in linked packages - Updated Repro

### ISSUE THREAD

**Issue by simonfox** [microsoft/TypeScript#36866]
I am still suffering from the issue described in microsoft/TypeScript#32970 

I that issue I provided a repro and that repro was resolved by microsoft/TypeScript#33567

However in my actual application I still face the original issue described (the repro was intentionally simplified). Get `error TS2742: The inferred type of 'actions' cannot be named without a reference to 'drive-common/node_modules/typescript-fsa'. This is likely not portable. A type annotation is necessary.` when using `yarn link` to link packages for dev.

I have updated my original repro to re-expose the problem. Follow steps below...
clone https://github.com/simonfox/repro-plugin-one 
clone https://github.com/simonfox/repro-plugin-two 
run `yarn` for both
run `yarn link` in plugin two root
run `yarn link plugin-two` in plugin one root
you will see the issue in src/features/feature-one/actions.ts (you may need to reload the VS Code window after linking).

cc @sheetalkamat

**Comment by imt-jaime** [comment]
I will refer my closed issue as related here. It seems to be the same problem: #33137 

Lastly I've discovered this may happens even inside node modules (when there are more than one package (B) that depends on another module (C) in different major versions).

TypeScript compiler cache is not handling NodeJS module resolution described in:
- [npm](https://docs.npmjs.com/cli/install#algorithm), [npm resolution explained] (http://npm.github.io/npm-like-im-5/npm3/dependency-resolution.html)
- [NodeJS](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)

I also think that the pull request #33567 is a close approach to the solution.

**Comment by ericmdantas** [comment]
@imt-jaime 
> Lastly I've discovered this may happens even inside node modules (when there are more than one package that depends on another module (C) in different major versions).

That's pretty much what happens to me. It's an issue even when the packages are not linked, just being a dependency already triggers this. Also, it doesn't have to be a major version difference, any version difference causes the issue.

**Comment by imt-jaime** [comment]
Have you tried to set 'preserveSymlinks' to true in package json?

**Comment by simonfox** [comment]
@imt-jaime `preserveSymlinks` does not resolve the issue

**Comment by tpluscode** [comment]
If anyone find this issue, it seems fixed on the `next` package today :)

**Comment by ericmdantas** [comment]
I'm still having this issue even when using typescript 3.9.x. I'll set up a repository to make it easier to simulate the problem.

**Comment by btakita** [comment]
Still having this issue with pnpm as of Typescript 4.0.3

**Comment by codeness93** [comment]
> I'm still having this issue even when using typescript 3.9.x. I'll set up a repository to make it easier to simulate the problem.

Hi, commenting after exactly (almost) 1 year. Were you able to resolve this issue? Because I'm still running into the same problem even after upgrading typescript version to 3.9.x.
