### ISSUE TITLE
TypeChecker shoud be passed when Declare `this` through `ReturnType`

### ISSUE THREAD

**Issue by Himself65** [microsoft/TypeScript#36875]
**TypeScript Version:**  3.8-Beta

**Search Terms:**

ThisType, this, ReturnType, Circularly References 

**Code**

function `replaceStore` is similiar as `restore`, but `restore` display an error.

```ts
function replaceStore(this: Store) {
  
}

export function createStore () {
  return {
    tokens: [],
    replaceStore,
    // de-comment next comment and you will see the bug
    restore (this: Store) {

    }
  }
}

export type Store = ReturnType<typeof createStore>
```

**Expected behavior:** Type check pass.

**Actual behavior:**  `Error:(16, 13) TS2456: Type alias 'Store' circularly references itself.`

**Playground Link:** 

https://www.typescriptlang.org/play/index.html?ts=3.8-Beta&ssl=17&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABAJwKYAcA2BDCqDKUcaAFFABYwDOAXIocagJSIDeAUIouwL7vuoAHumJREoSLASIIabFAJE0iEiw5c0UEMiTquiIgGtUYWogDaAXQA0nfWiy5FjW-sQB6d4gAmqALQQcAC2QSZiYEJigSFhiNhg3ogAnnAgiADuMJiYiFSoqAbkBQBGIADmdhqoVEoFZJRmDGhq-G58XHx8AsKiBknoBU0FALyIAEqoWjoAKv2oADxQc3DAMnIKQwB87EA

**Related Issues:** Haven't yet.

**Comment by orta** [comment]
I'm not sure they are the same I'm afraid, the argument in `replaceStore` isn't a part of `Store` because it uses` ReturnType` where are the returned type in `createStore` is circular because it contains itself through the `restore` function.

**Comment by RyanCavanaugh** [comment]
This is a true circularity and thus something we will error on. When an identifier refers to a declaration we can defer its type resolution and thus not encounter a circularity, but that isn't a possibility for a function declared inline in an object literal.
