### ISSUE TITLE
Type guarding not working on class union types

### ISSUE THREAD

**Issue by Nkmol** [microsoft/TypeScript#36873]
**TypeScript Version:**  3.7.5

**Search Terms:**
- Union types not working with type guards
- Class union types not working with type guards

**Code**

```ts
enum Kind {
  Foo,
  Bar,
}

enum OtherKind {
  Oof,
  Rab
}

interface Base {
  kind: Kind | OtherKind;
}

class Foo implements Base {
  public kind = Kind.Foo;
  public propertyString: string = '';
}

class Bar implements Base {
  public kind = Kind.Bar;
  public propertyNumber: number = 0;
}

class Oof implements Base {
  public kind = OtherKind.Oof;
  public propertyStaticString: 'static' = 'static';
}

class Rab implements Base {
  public kind = OtherKind.Rab;
  public propertyObject = {
    test: 'test'
  };
}

type BothOtherKind = Oof | Rab;
type BothKind = Foo | Bar;
type Both = BothKind | BothOtherKind;
function isBoth(x: Base): x is Both {
    return true;
}

const input: Both = { kind: null } as unknown as Both;

if (isBoth(input)) {
  switch (input.kind) {
    case Kind.Foo:
      // tslint:disable-next-line: no-console
      console.log(input.propertyString);
      break;
    case Kind.Bar:
      // tslint:disable-next-line: no-console
      console.log(input.propertyNumber);
      break;
  }
}
```

I have added an extra layer of union types, which may not be needed to define the underlying problem, but resembles the scenario I am currently in.

**Expected behavior:**
`case Kind.Foo` correctly recognizing the input through the discriminator type.

**Actual behavior:**
`case Kind.Foo` not correctly recognizing the input through the discriminator type.

**Playground Link:**
[The illustrated problem](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200215&ssl=48&ssc=18&pln=48&pc=5#code/KYOwrgtgBA0gliAJlA3gKClAYgexwGgygCEBDAJ0IF801RIoB5AFwAthz4lUjGcAzQpgBKpAEZoaaBMw79SAY2AlSAZ2XpMAawSIAXLF1QAPkzYcuiANyTaCgDZrV2PFDgQADveARQzZ2TqPJgeYGL2cApQOtwAvIZIAHS4ODYhYRFRHuQ4HhzMAJ4AyszkCADmBqqlFVDxAOT1NlIOTirkbp7eviD+KkGaUKHhkdFG8ZaJZORpQxmj2bn5BQBykGIcBuAQGx3xAAzNdo6qznz8nV4+fgFqGkTDmWNxZuycuonns48LOXnkhRKpGYkRKZRAlSg9WqwMi9TqUJhIIUTVsaFapygojEl26N3693SIyiMWQ8RYb0m2O+8yyf2WjDEACtgApmAjBphZNUDPVucx6kQqEc0IU8iQcGwKRZxkwBCYseIbGLlMRJaxLAiUgrpsqCuK1WwEYaNUZTCbpe8kDZ+GAQGy4DgQG5VCaABQADwMgWAAEoDB6XRKjZyoORgMwwORnaUwMARQondU3CBQsxveqOc99FBwPZ7FAqFA1FA7VoQDgAO7OksmmzSC5uuCu9VN1NgZi+33BKCqStwZgKVhQNtpxKk7uhhR3BKIZJ4PRETCYAD0K6g-givT0iGb4m8AFoQMAPcwD1vgFscAfEyBVDhvEvl7f795EvYcOVRx3Eot-oCaghX1ZmXKAxHDUgtBAqBpyCSZpkXUDV3XTcZB3PdwmAI8TzPC8rxvJMH2AJ9MBfIj30-b9mF-ekAVWdYOGAkiwIgqChVsIA)

**Related Issues:**
- https://github.com/microsoft/TypeScript/issues/16778

Note that the above issue is about interfaces, which indeed, does seem to work correctly if I am using the same setup ([See](https://www.typescriptlang.org/play/#code/KYOwrgtgBA0gliAJlA3gKClAYgexwGgygCEBDAJ0IF801RIoB5AFwAthz4lUjGcAzQpgBKpAEZoaaBMw79SAY2AlSAZ2XpMAawSIAXLF1QAPkzYcuiANyTaMuYuW4cUYAA9ZSVSvU9tug0sAOmcbTAAHchxwjmYATwBlZnIEAHMDVWS0myl7cnklFXJXD1BEbzJfTSgdJEDdILJyMKhI6Ni4gDlIMQ4DcAhe5ttpEFl8xyYBEs9ynw0iWv0zdk4Gvn4WtpjyeIARUlkDA9kcuzGHQtExGbKKtQX-OpWLBuutqJ34xjEAK2AFMwDCgoABtLTAOIZLIgVIAXWhKVhUCoZzQ8RiJBwbCgAF5sHgTEUiRsie80PwwCBAXAcCAoHBVMRsawABRuAyVYAASgMbgZFRZfkwUHIwGYYHI9OSYGAaIUdMyDJA4TAQKxOPxIKW-TAABs9SioGooFStCAcAB3ekm5lsGzSfhQVmMu1shCq5jc7nC1SWuDMBSsZ0etVBJY+6qYBQPQxIEJ4PREEVQAD0qagzFUepkekQjPEeuAAFoQO5mMWc2X+jhiwqQKocEXkyL642i0E9ThUi6VWHth0kkjUtyWimxGLSFox1AY75gk0kynMOnM9nc-nVIWS2WPJWEMAa3XFU3gC3oyeO12e6HmEEB7suj0OKPz1AJ8Apy0aFQgA))

**Comment by DanielRosenwasser** [comment]
This is because TypeScript has no way to know whether those properties are meant to be reassigned, so each enum value is widened to the appropriate enum type. You can instead provide an explicit enum type on each property, or more desirably, mark the properties as `readonly`.

```ts
enum Kind {
  Foo,
  Bar,
}

enum OtherKind {
  Oof,
  Rab
}

interface Base {
  kind: Kind | OtherKind;
}

class Foo implements Base {
  public readonly kind = Kind.Foo;
  public propertyString: string = '';
}

class Bar implements Base {
  public readonly kind = Kind.Bar;
  public propertyNumber: number = 0;
}

class Oof implements Base {
  public readonly kind = OtherKind.Oof;
  public propertyStaticString: 'static' = 'static';
}

class Rab implements Base {
  public readonly kind = OtherKind.Rab;
  public propertyObject = {
    test: 'test'
  };
}

type BothOtherKind = Oof | Rab;
type BothKind = Foo | Bar;
type Both = BothKind | BothOtherKind;
function isBoth(x: Base): x is Both {
    return true;
}

const input: Both = { kind: null } as unknown as Both;

if (isBoth(input)) {
  switch (input.kind) {
    case Kind.Foo:
      // tslint:disable-next-line: no-console
      console.log(input.propertyString);
      break;
    case Kind.Bar:
      // tslint:disable-next-line: no-console
      console.log(input.propertyNumber);
      break;
  }
}
```
