### ISSUE TITLE
Return type not inferred correctly when used with conditional type guard

### ISSUE THREAD

**Issue by gotenxds** [microsoft/TypeScript#36888]
**TypeScript Version:**  3.7 and 3.9

**Search Terms:**
 Typeguards
**Code**

```ts
function isBoolean(value?: unknown): value is boolean  { 
    return value === false || value === true
}

function shouldError(value: string): { value: boolean } { 
    if (isBoolean(value)) { 
        return value
    }

    return { value: true }
}


function doesError(value: string | boolean): { value: boolean } { 
    if (isBoolean(value)) { 
        return value
    }

    return { value: true }
}
```

**Expected behaviour:**
in the method, `shouldError` I incorrectly give a parameter of just string type where it should be `string | boolean` 

I should get an error saying I'm trying to return a bool(or a string) where an object of type `{ value: boolean }` but it does not

**Actual behaviour:**
Only if I fix the parameter type to `string | bool` do I get the desired error

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200219&ssl=1&ssc=1&pln=20&pc=2#code/GYVwdgxgLglg9mABDAzgITnANgUwIZgAUAbnliDgPwBci4A1mHAO5gCUtp5OyKiARplwFEiAN6IAsAChRogE44oIeUi4VEAXm2JgZFDwA+hxOp7bNiKPIoyAvjJmhIsBIhQALOCCwATAKLy8nDyJGQUtCjWMGAA5hzipuE4tILY+Eh2iTJyyMCIhKgY6QRh3Gxs2bK5corKqkncOXIO0s0KSipIEma01hqtrY7SztDwSL5wOCiBwaG97tFxiCZpwuy0PcmpQhmIWRLteQVFu6VmFVU1tZ0NZkdD1R313Y0RVjY8g0A
**Related Issues:** 
No

**Comment by IllusionMH** [comment]
> I should get an error saying I'm trying to return a bool(or a string) where an object of type { value: boolean } but it does not

You are not returning `boolean` there -  if you hover over value inside `if` block in `shouldError` you'll see that narrowed type is `never` - basically any of possible string types won't satisfy `isBoolean` check therefore it's empty set of types (in practice that `return` shouldn't be called at all if types are correct at runtime). Therefore returned type is `{value: true} | never` and `never` is omitted in unions so no type errors.

On the other hand it would be nice to see that `return` statement is unreachable.

**Comment by RyanCavanaugh** [comment]
It's weirdish, but there aren't any good fixes here that don't make something else much worse.

**Comment by gotenxds** [comment]
@IllusionMH Ya I figured that was the logic behind that, but the thing is, it did happen and fell only in unit tests, I just forgot to add the ` | boolean' but the fact is I tried to return a boolean.

@RyanCavanaugh Cant this be marked as unreachable code and if so why wouldn't this cause an error?

**Comment by RyanCavanaugh** [comment]
This would be undesirable:
```ts
function fn(x: string) {
  if (typeof x !== "string") throw new Error("wrong arg type")
                              ~~~~~ Error, unreachable code detected
}
```
