### ISSUE TITLE
Typeguard method not working for class members 

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#36887]
**TypeScript Version:**  3.8-Beta (on Playground)

**Search Terms:** typeguard class member

**Code**

```ts
class Foo {
  constructor(prop: number | number[]) {
    this.prop = prop;
  }
  prop: number | number[];

  isNumberFoo(): this is NumberFoo {
    return typeof this.prop === "number";
  }

  isArrayFoo(): this is ArrayFoo {
    return Array.isArray(this.prop);
  }

  method() {
    // using typeguard methods
    if (this.isNumberFoo()) {
      this.prop; // (✓) correctly narrowed to number, but the type display is unnecessarily complicated
    } else {
      this.prop; //  ✗  not narrowed at all, but TS should know that prop is not a number
    }

    // using direct typeguards
    if (typeof this.prop === "number") {
      this.prop; // ✓ number
    } else {
      this.prop; // ✓ number[]
    }
  }
}

type NumberFoo = {
  prop: number;
}

type ArrayFoo = {
  prop: number[];
}
```

**Expected behavior:**
In the `if` branch, `prop` is narrowed to `number`. In the `else` branch, `prop` is narrowed to `number[]`.

**Actual behavior:**
In the `if` branch, `prop` is narrowed to `number & (number | number[])`, which works but looks confusing. 
In the `else` branch, `prop` is not narrowed at all.

**Playground Link:** [here](https://www.typescriptlang.org/play/?ts=3.8-Beta#code/MYGwhgzhAEBiD29oG8CwAoa1jwHYQBcAnAV2APiIAoAHI+GgLmlxIFsAjAUyOgB8W7bkQDaAXQCUKDFiwEAFgEsIAOjoNoAXmjqaAbhnQAvod3NWnHv0GXRYg+kPKAckJ4J4VCcwXLof11sPaUxZIi4CEiJcaAIATxoueAAzWKVVXS1NbQAiC2EchywTR1DlAEEiIjA4jy8fdP8YSuraxBDZaHDI6OgWmpUKqpqqXwz6Ggki4wxDNgj5eAATLw7ZRVTR9MGIQOE6iSk0UM6xtQm9aAB6K+gqQGRyKRwqrnIQOJYwKvgAdy4l2JIfI8AA00A4JAIaS4sQSMKWyho4A+fhIuFwry4UC+ine2HgbCRimAYAI-0MxWgXBAEBhx06cm2ukuNywgHRyLC4eBQ3Bfeh-AGk6BgEAgMEQqEAFQAytAIIsSCAAQBrLk-NJCzJ+LlQsA2YQUmalTobO7xRIpNLKc4abK5YFEHJHQ2M63M663e76niGoxUml0l1W8YMFme712X2GEolDDmmF7dztbT0nQTcxuIgOWPoeN9YZtJAp0zpiPibNAA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/26212 describes the exact same issue, but was closed without a proper solution.

**Comment by RyanCavanaugh** [comment]
`this` isn't a union, so we don't have any available type to narrow to it in the `else` branch. This isn't something CFA is capable of producing without some notion of negated types

**Comment by AlCalzone** [comment]
Could it work if there was a way to narrow the property directly instead of the `this` type? Something along the lines of
```ts
  isNumberFoo(): this["prop"] is number {
    return typeof this.prop === "number";
  }
```

**Comment by mcintyret** [comment]
Could there be some syntax like

```  
isNumberFoo(): this is NumberFoo else this is ArrayFoo {
    return typeof this.prop === "number";
}
```

That lets the programmer explicitly set the "else" type?

I guess if that existed, the compiler could just do it automatically:

`isTypeX(): this is TypeX else this is Exclude<typeof this, TypeX>;`

**Comment by mcintyret** [comment]
I'm hitting this issue in a related situation where the generic type _is_ a union:

```
class Box<T> {
    constructor(private val: T) {}

    public containsArray(): this is Box<Extract<T, any[]>> {
        return Array.isArray(this.val);
    }

    get value(): T {
        return this.val;
    }
}

const box: Box<string | string[]> = new Box("foo");

// Type 'string | (string | string[])[]' is not assignable to type 'string[]'.
//  Type 'string' is not assignable to type 'string[]'
const stringArray: string[] = box.containsArray() ? box.value : [box.value];
```

**Comment by oliver-giersch** [comment]
I have come across this issue while trying to implement a Rust-like `Result` type, i.e., a discriminated union with two variants (`Ok` and `Err`) and a number of methods, directly callable on the `Result` instance via the dot operator.

```typescript
const Ok<T> = { tag: 'ok', val: T }
const Err<E> = { tag: 'err', err: E }

export class Result<T, E> {
    private constructor(readonly repr: Ok<T> | Err<E>) { }
    static Ok<T, E>(val: T): Result<T, E> { ... }
    static Err<T, E>(val: E): Result<T, E> { ... }
    isOk(): this is { readonly repr: Ok<T> } { ... }
    isErr(): this is { readonly repr: Err<E> } { ... }
    getVal(this: { readonly repr: Ok<T> }: T { ... }
    getErr(this: { readonly repr: Err<E> }: E { ... }
    // various adapters like map, mapErr, and, or, etc...
}
```
This should allow writing code like so:

```typescript
type AppError = { reason: IoError | ... }
declare function read_file(path: string): Result<Buffer, IoError>

function do_something(): Result<void, AppError> {
    const res = read_file(...)
    if (res.isErr()) {
        // narrowed to { repr: Err<E> }
        return Result.Err({ reason: res.getErr() })
    }
    // else branch, narrowed to { repr: Ok<T> }
    const file = res.getVal()
}
```
I've tried a different approach defining `Result` like this:

```typescript
export type Result<T, E> = (Ok<T> | Err<E>) & ResultMethods<T, E>
export interface ResultMethods<T, E> {
    isOk(): this is Ok<T>,
    isErr(): this is Err<E>,
    // ...etc
}
```
This feels unnecessarily convoluted though, because each result instance needs to have a bunch of arrow functions created along-side it each time it is constructed.
To me it seems that such thin wrapper classes/types (i.e., no base class, only a single non-function member) should be treated exhaustively by type guard checks.

**Comment by mlhaufe** [comment]
A simple example of this problem:

```ts
abstract class Color {
    isRed(): this is Red { return false }
    isBlue(): this is Blue { return false }
    isGreen(): this is Green { return false}
}

class Red extends Color {
    isRed(): this is Red { return true }
}

class Green extends Color {
    isGreen(): this is Green { return true }
}

class Blue extends Color {
    isBlue(): this is Blue { return true }
}

let c: Color = new Blue()

if(c.isRed()) {
    c // c: Red
} else if(c.isGreen()) { // Property 'isGreen' does not exist on type 'never'
    // c: never (Green expected)
} else if(c.isBlue()) { // Property 'isBlue' does not exist on type 'never'
    // c: never (Blue expected)
}

c // c: Red (Blue expected. if all conditions false, then Color expected)
```

**Comment by roborich** [comment]
Another simple example.  This type-guard doesn't work, am I missing something?
```ts
class Example {
  asset: Asset | null = null;

  get isAssetAvailable(): this['asset'] is Asset {
    return this.asset != null;
  }
}

**Comment by AlCalzone** [comment]
@roborich how about this?
```ts
declare class Asset {};

class Example {
  asset: Asset | null = null;

  isAssetAvailable(): this is this & {asset: Asset} {
    return this.asset != null;
  }
}

const foo = new Example();
foo.asset.toString(); // error here
if (foo.isAssetAvailable()) {
    foo.asset.toString(); // ok
}
```
You'd have to turn the property getter into a method though

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwIKpAF3gbwF8BuAKBKVXgFEAPKAWwAcIE8T54VkcAuDLXAB94AOwCuECPAC8oiRFLt4AS2SZu2dADcoy6ACMWACgCUfbAAtVKtJesAyfF178NBfEo5xsYmCPh2yAB0zrgAhLLikqQcBCRx5AD2Isi4AGaJiTKiIADu1HRMxiakGYkhAkHYiQDK2DDKIgDmpqTKafBGZUGq6jjaugbFJh4cHN2hVbX1jS0l8UA
