### ISSUE TITLE
Boolean properties don't properly differentiate types without explicit comparison or strict null checks

### ISSUE THREAD

**Issue by Drundia** [microsoft/TypeScript#36893]
**TypeScript Version:**  3.7.5

**Search Terms:**

**Expected behavior:**
Boolean properties differentiating types without explicit comparison with `true`/`false` regardless of `strictNullChecks` option.

**Actual behavior:**
Boolean properties require explicit comparison with `true`/`false` (double equals surprisingly works) or `strictNullChecks` compiler option to differentiate types.
If/Else branching works same as conditional operator.

**Related Issues:**

**Code**
```ts
interface IBase {
    flag: boolean;
}

interface ITrue extends IBase {
    flag: true;
    t: any;
}

interface IFalse extends IBase {
    flag: false;
    f: any;
}

type IAny = ITrue | IFalse;

declare let x: IAny;

// Errors at identifying IFalse type. Considers it to be IAny
console.log(x.flag ? x.t : x.f);
console.log(!x.flag ? x.f : x.t);

// Working
console.log(x.flag == true ? x.t : x.f);
console.log(x.flag === true ? x.t : x.f);
console.log(x.flag != true ? x.f : x.t);
console.log(x.flag !== true ? x.f : x.t);
console.log(x.flag != false ? x.t : x.f);
console.log(x.flag !== false ? x.t : x.f);
console.log(x.flag == false ? x.f : x.t);
console.log(x.flag === false ? x.f : x.t);

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?strictNullChecks=false#code/JYOwLgpgTgZghgYwgAgJICE4GcUG8CwAUMicjADZwDmAXMgEYD2j5EcIA3EQL5FGiRYiFKgAqUAK4oIAD0ggAJljSYcyAsVIVqdMJIhdNJMHXYBPQ70L9w0eEjQAxOOTWz5SldjxFSZSrRkLjiGfjCmIBY8fIRgZgAOIgCCkcgAvGjiUsgAPk7BBjEKEAiUUCisYMgydKgpUdaEAPRNyACiUFCMUMpwVcDF4MAwZqBU+a4ocYkAdMgAwowgWAPQysBVYIwMyZFECEtYLBAz5IxUABQyM9rjAPzVM1V01zAAlIYHy8en5xcAhK8AsgHq9kC8nh8Yi1kAB1boAazG+0OPzOlyB1HSGT02VBT3Bj3en1RrF+GJuwLS1OQuJQ+OeRKhhC+RzJ6KulKx-wy8EmIMejNezNZaL+mPGPN5BQF1yFN2ZKO+7PFXMlOP0spuhLlItJJw5EuQUtpmvxMB1kJJyoNqtu2KC-PNlrAept5M59up0qdRJdHyAA)

**Comment by MartinJohns** [comment]
This is as expected, because of `strictNullChecks`. The true-branch does not need an additional check, but in the else branch you have three possible values: `false`, `undefined` and `null` - all evaluating falsy.

**Comment by Drundia** [comment]
One of the branches has `undefined` and `null` in all working cases too. By this logic it should never differentiate any types without strictNullChecks at all.

**Comment by Drundia** [comment]
@MartinJohns @RyanCavanaugh If we enable `strictNullChecks` and explicitly include `null` and `undefined` in the types, the branch receiving these values is not narrowed.

So the behavior is inconsistent and encourages bad code with explicit comparison between boolean and `true`.
