### ISSUE TITLE
Implements self is not show problems

### ISSUE THREAD

**Issue by belozer** [microsoft/TypeScript#36898]
**TypeScript Version:**  3.7.5

**Search Terms:** Implements self

**Code**

Case 1
```ts
interface Test {
    foo(): void;
}
class Test { }

new Test().foo(); // Expected Error
```

Case 2
```ts
class Test2 implements Test2 {} // Expected Error
```

Case 3
```ts
// Case 3
interface Test3 {
    foo(): string
}

class Test3 implements Test3 {  // Expected Error
    bar() { return '' }
}

new Test3().foo();  // Expected Error
```

**Actual behavior:**
No errors...

**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/index.html?ssl=21&ssc=19&pln=12&pc=1#code/PTAEGEEMGcFNQIwCgCWA7ALrATgM0gMbwAqs0GoA3kqLaLgPYMAUAlAFygBuDKAJgG4kAXyQEANjGihS5KqFFI0sAO4yyGNgDpGLVkKQgIMeACYxk6NNkZToFAFsADuNgPYmaxruVFRqHCgAMyomDj4ROrkQVQ0dLpsnOTY6ADmIkgWUlEYMY4ubh4YXtGxdKAARpDYbPLYsBgArthooADkbQoZSqo5QdoJ+kA)

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/9699#issuecomment-232477522

**Comment by RyanCavanaugh** [comment]
These are all the intended behavior, as per the comment you linked.

**Comment by artalar** [comment]
TS is grate, but runtime error for type-safe code - is a wrong =(
