### ISSUE TITLE
Property 'sheet' does not exist on type 'SVGStyleElement'

### ISSUE THREAD

**Issue by waterplea** [microsoft/TypeScript#36896]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** sheet, SVGStyleElement

**Code**

```ts
var c: SVGStyleElement;

console.log(c.sheet);
```

**Expected behavior:**
No error on `c.sheet`

**Actual behavior:**
Error `Property 'sheet' does not exist on type 'SVGStyleElement'`
**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=3&ssc=22&pln=1&pc=1#code/G4QwTgBAxgXBDKA1A4vALgTwDYFMCiuAtjgHZoDcAsAFA1QD2JAzvbgHRb0DmAFFG0wAWOHGgCU5IA

**Additional info**
Both Chrome and Firefox have `sheet` on `SVGStyleElement`.

**Comment by waterplea** [comment]
It also should bee `CSSStyleSheet` not `StyleSheet` on `HTMLStyleElement` and `SVGStyleElement` according to MDN:
https://developer.mozilla.org/en-US/docs/Web/API/LinkStyle

**Comment by conniefan** [comment]
hi, I'm taking this as my first bug!

**Comment by jakebailey** [comment]
This was fixed in #42067.
