### ISSUE TITLE
Mapped types relations inside function body

### ISSUE THREAD

**Issue by tinganho** [microsoft/TypeScript#36890]
I have been struggling to write a simple map function that return different types, and couldn't find any good examples in Google for that, but shouldn't this simple example work?

```ts
interface A {
    a: string;
}

interface B {
    b: string;
}

interface TypeMap {
    a: A;
    b: B;
}

function map<K extends keyof TypeMap>(key: K): TypeMap[K] {
    if (key === 'a') {
        return {
            a: 'a',
        } as TypeMap['a'];
    }
    return { b: 'b' } as TypeMap['b'];
}
```

It complains that the Type `A` is not assignable to `A & B`. Imo `A & B` is the wrong type to compare with inside the function. I should at least be able to assert the type inside the `map` function? Why not just let it be `A | B` instead?

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=1&ssc=14&pln=21&pc=2#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmQGcwpQBzAbiwF8stRJZEUAhTHPAIyNPJDU6DJtHhJkAFQCeABwgBZOLM558RVDTW9kbGvSwwAriARhgAexDIAtsoA8AaWQQAHpBAATYsgDWEaQsYKTlFZQA+AAp-aSJHAEoiGXklWQBtRwBdVTxgYOiA5ABeEuQAcjgy+Jy1XCgIMCMoa2xatvVyyoAaLjbafB9ksPSKssytPHo1esbmzGQdMu4y5H64QdDUtKWx-SA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #33014
