### ISSUE TITLE
Support basic string operations on string literals

### ISSUE THREAD

**Issue by taxilian** [microsoft/TypeScript#36904]
## Search Terms

string literal, concatenate string literal, string operation, string types

## Suggestion

I would like to be able to perform basic string operations on string literal types; e.g.

```
type a = 'foo';
type b = 'bar';
type c = a+b; // evaluate to 'foobar'

type a2 = 'foo' | 'oof';
type b2 = 'bar' | 'rab';
type c2 = a2+b2; // evaluate to 'foobar' + 'foorab' + 'oofbar' + 'oofrab'
```
(alternatively it could be limited to only work with non-union string literals; for my use cases and most I can think of that would work just fine)

Similarly it should be possible for typescript to evaluate types from basic string operations, in particular concatenation. 

```
const a = <const>"foo";
const b = <const>"bar";
const c = <const>(a+b); // c is type 'foobar' because both a and b are known non-union string literals
```
Perhaps even more usefully than that would be to support those inside a computed property name in an object, e.g.

```
const pName = <const>'myProp';
const suffix = <const>'_thingy';
const obj = {
    a: 5,
    b: 4,
    [pName]: 17,
};
// currently evaluates to {a: number, b: number, [pName]: number}
// Should evaluate to {a: number, b: number, myProp: number}
const obj2 = {
    a: 5,
    b: 4,
    [pName+suffix]: 17,
    [pName + "s"]: 23,
};
// currently evaluates to {[x: string]: number; a: number; b: number; }
// should evaluate to {a: number; b: number; myProp_thingy: number; myProps: number; }
```

## Use Cases

This would make the creation of complex templated function types significantly more powerful. For example, a factory function which can work on a number of different types could return an object with type-relevant key names, e.g:

```
const modelTypes = {
    user: UserModel,
    book: BookModel,
    movie: MovieModel,
};

const userOperations = getOperations('user', ['book', 'movie']);
/*
    userOperations could now be type: 
    {
        model: typeof UserModel,
        get_user_books: (user: <lookup id>) => BookModel[],
        get_user_movies: (user: <lookup id>) => MovieModel[],
    }
*/
```

This is just one possible example off the top of my head, but there are a lot of possible uses, particularly if you could make it able to understand the result of a number of string operations. Off the top of my head the ones that seem most useful would be (in order of usefulness in my opinion):

* toLowerCase, toUpperCase
* substr/substring, charAt, split

Having operations for startsWith, endsWith might be cool as well, but that could also be getting too far into the weeds =] 

## Checklist

My suggestion meets these guidelines:

* [?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

It is possible that this could be a minor breaking change in existing typescript/javascript code if someone is relying on a type to be the "widened" type when concatenating and it was then more specific -- that said, in most cases I think the "break" would lead to more clarity in code and would certainly be an easy fix.

I believe that this feature agrees with TypeScript's design goals; it most likley does not add any syntax and if it did it would be very specifically type-specific. It could be used to make significantly more powerful generic types for advanced libraries.

**Comment by MartinJohns** [comment]
Related (duplicate?): #12754

**Comment by RyanCavanaugh** [comment]
Going to track at #12754 since that's where we're currently experimenting with this. It's almost certain that whatever we come up with for property key transforms will be applicable in the broader type space.
