### ISSUE TITLE
readonly property emit with useDefineForClassFields includes non-existent initialiser

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#36910]
```ts
// @useDefineForClassFields: true
class TitleService {
  readonly title?: string;
}
```

**Expected emit:**

```js
"use strict";
class TitleService {
    constructor() {
        Object.defineProperty(this, "title", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
    }
}
```

**Actual behavior:**

```js
"use strict";
class TitleService {
    constructor() {
        Object.defineProperty(this, "title", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: title
        });
    }
}
```

**Playground Link:** 
https://www.typescriptlang.org/v2/en/play?useDefineForClassFields=true#code/MYGwhgzhAEAqCWAXEBTAyigTgN3sF0A3gFDTSYpgAmA9gHYgCe0iSqA-AFzQSKbx0A5gG5iAXyA

**Comment by a-tarasyuk** [comment]
@sandersn It seems the nightly build emits the correct code - [Playground](https://www.typescriptlang.org/play/index.html?useDefineForClassFields=true&ts=3.9.0-dev.20200220#code/MYGwhgzhAEAqCWAXEBTAyigTgN3sF0A3gFDRnSYpgAmA9gHYgCe0iSqA-AFzQSKbx6AcwDcxAL5A)

**Comment by michaeljota** [comment]
Shouldn't this be backported to at least 3.8? Now that releases are one every 3 months, seems too much wait for this to the next release.

**Comment by milesj** [comment]
@michaeljota Agreed. I've ran into this issue a handful of times, and had to change my modifiers to move forward.

**Comment by sandersn** [comment]
@a-tarasyuk looks like you are right.

@michaeljota @milesj I'm not sure why people would turn on useDefineForClassFields without esnext emit. From reading feedback on this repo, I believe [[Define]] semantics are strictly more confusing (and less useful) than [[Set]] in the few cases where they differ, though both have pros and cons. Can you explain your uses?

**Comment by michaeljota** [comment]
I mostly use this with forms that required a model to have all the properties, even if they are not defined. Angular Forms for instance (I caught this bug using it)

**Comment by sandersn** [comment]
How does useDefineForClassFields help? Does it make sure that every field is initialised to at least undefined?

**Comment by michaeljota** [comment]
Yes. Maybe it doesn't have all the values, but it does have the shape with the properties.

**Comment by InExtremaRes** [comment]
> I'm not sure why people would turn on useDefineForClassFields without esnext emit. From reading feedback on this repo, I believe [[Define]] semantics are strictly more confusing (and less useful) than [[Set]] in the few cases where they differ, though both have pros and cons.

@sandersn I thought one valid reason to enable `useDefineForClassFields` was to be prepared and probably start adapting the code (if it's worth doing) for the future. At least I understood something like that from the release announcement. Am I wrong then? Is there a reason to turn it on when emiting ES2019 or ES2020?

**Comment by sandersn** [comment]
@InExtremaRes JS runtimes are likely to be strictly better at understanding:

```js
function C() {
  this.x = 1
}
```

compared to 

```js
class C {
  constructor() {
    Object.defineProperty(this, 'x', { value: 1 })
  }
}
```

since the former has been a common idiom since day 1.


The only reason I can see to have `useDefineForClassFields: true` is to get the new errors to avoid the [[Define]] corner cases. However, all the code bases we inspected only turned up less than 10 errors, and that includes tons of open source, lots of Microsoft's projects and all of Google's (as far as I know).
