### ISSUE TITLE
npm EINTEGRITY 3.7.5

### ISSUE THREAD

**Issue by sheldonkwok** [microsoft/TypeScript#36916]
**TypeScript Version:**  3.7.5

**Search Terms:** integrity checksum failed

**Code**

```bash
npm install
```

**Expected behavior:**
Typescript is installed

**Actual behavior:**

```
npm ERR! code EINTEGRITY

npm ERR! Verification failed while extracting typescript@3.7.5:

npm ERR! Verification failed while extracting typescript@3.7.5:

npm ERR! sha512-/P5lkRXkWHNAbcJIiHPfRoKqyd7bsyCma1hZNUGfn20qm64T6ZBlrzprymeu918H+mB/0rIg2gGK/BXkhhYgBw== integrity checksum failed when using sha512: wanted sha512-/P5lkRXkWHNAbcJIiHPfRoKqyd7bsyCma1hZNUGfn20qm64T6ZBlrzprymeu918H+mB/0rIg2gGK/BXkhhYgBw== but got sha512-9Ywwy5yYAF78j3Q3U3HFmxRDJ0GO/40NjE51SEWwl8i6l7XfwnxRpvW4trJThUWfEfP9YuPxu2X+M3HuG6rKAA==. (4086425 bytes)
```

On https://www.npmjs.com/package/typescript/v/3.7.5, it looks like the original publish is one month ago. I could update the sha in the package-lock.json but I just wanted to make sure it wasn't maliciously published since the tags are generally immutable.

**Comment by mjrgeorge** [comment]
same problem

**Comment by RyanCavanaugh** [comment]
Seems like a problem on npm's side; we haven't touched this at all

**Comment by sheldonkwok** [comment]
My original issue resolved itself after waiting FWIW. Seems like it's npm
