### ISSUE TITLE
Access undefined guard checking

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3692]
Given this code:
```typescript
interface A {
	a?: B;
}

interface B {
	a: string;
	b: string;
}

let a: A;
console.log(a.a.b);
```
I want it to error on the line:
```typescript
console.log(a.a.b);
```
because I didn't add a check:
```typescript
if(a.a) {
    console.log(a.a.b);
}
```

I think access undefined errors are one of the most common bugs.

**Comment by DanielRosenwasser** [comment]
I believe this would need control/data flow analysis which @vladima has worked on a bit.

**Comment by mhegazy** [comment]
is not that the same as #185?

**Comment by tinganho** [comment]
@mhegazy that is suggesting a modifier, though very related to this suggestion. Since null is assignable to every type. If that got landed maybe add checking for null too then.

**Comment by mhegazy** [comment]
this is subsumed by #185
