### ISSUE TITLE
Mixed sync/async overloads result in incorrect type returned by sync function.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/TypeScript#36927]
**TypeScript Version:**  3.7.5

**Search Terms:**
async overload return

**Code**

```ts
async function apple(sync: false): Promise<boolean>
function apple(sync: true): boolean
function apple(sync: boolean): Promise<boolean> | boolean {
    if (sync) return Promise.resolve().then(() => true)
    return true
}
console.log(apple(true) as unknown instanceof Promise) // true
async function main() {
    await apple(true) // 'await' has no effect on the type of this expression. (80007)
}
```

It is worth noting that not only does TypeScript say the type of `apple` is a boolean when really it is a Promise, it also gives me a gentle warning if I try to await it!

It is also worth noting that if you don't do any async work in the function, the TypeScript won't generate an awaitable function and the runtime type will correctly match the compile-time type.

**Expected behavior:**
TypeScript either tells me the function returns a promise, or the function returns a boolean.

**Actual behavior:**
TypeScript tells me the function returns a boolean, when in reality it returns a promise.

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=10&pc=2#code/IYZwngdgxgBAZgV2gFwJYHsI2ABxwGwFMAKcaALnmHxEIEpKAFAJ3QFtVaAeAI3XSLAIAPgBQiFBiy4CJMlErJmCepT4DCQ8UihpM2PEVKQFMdYIgMYLdp0K9+F4TAA+Zx5qwBvUTD8xUOBhjaDoYZkJkBGYsGw5aADoIkAEANxI6BOQAC0IIYmIwgF5nJRU6X38IqJiYMsJRAF9RKEwUogT8dABzYhkjerDQGCQAawh0AHcsVAgQZCEoQnQguLswgHoNuuUG0BN4HT0sNmBZwpgff2xJs+QDWWJBmC2YAHJgW9RkN5hs4YmMEIcDghF0MH0OUIdTAOGhKzq2U4QIAHjhkiApAlggAOAAMBIA7BVGkA

**Related Issues:**
#34698 though it doesn't seem to directly discuss the the fact that TypeScript lies about the function's type at the callsite.

**Comment by RyanCavanaugh** [comment]
You're "on your own" for having your function body match the behavior of the overloads you wrote. See #13235

**Comment by MicahZoltu** [comment]
In that other issue it was mentioned that there isn't a low-complexity way of addressing the reported problem.  In this case, it feels like the problem is much more tractable in that the compiler will know when a function gets flagged as async at compile time, and at that point it can error if any of the overloads returns a non-promise.

# Opinion

I find it very disappointing that the TypeScript compiler allowing me to incorrectly type a function is considered working as intended.

IIUC, you are saying that function overloads are effectively unchecked typecasts (or should be treated as such by the developer at least)?  Is there a way I can tell the compiler to not allow overloads?  When running in strict mode, I generally expect TypeScript to not let me do bad things.

With typecasts, I at least reasonably expect to be taking control of the type system away from TypeScript.  In this case, I did not expect at all that writing overloads would be overriding the type system so I was terribly surprised when I found out (after hours of debugging) that the problem was that TypeScript was simply not doing type checking on function overloads.
