### ISSUE TITLE
TypeScript cannot correctly infer non undefined object property

### ISSUE THREAD

**Issue by micheleangioni** [microsoft/TypeScript#36929]
**TypeScript Version:**  
3.7.5 and previous ones

**Search Terms:** 
infer undefined object property

**Code**

```typescript
type Test = {
  [s: string]: {
    optionalFunction?: (aString: string) => void
  }
}

const test: Test = {
  myString: { optionalFunction: (aString: string) => { console.log(aString); } }
}

const testTheFunction = (inputString: string) => {

  if (test[inputString] && test[inputString].optionalFunction) {
    test[inputString].optionalFunction(inputString);
 }
}

```

**Expected behavior:**
No error

**Actual behavior:**
`Cannot invoke an object which is possibly undefined`

**Playground Link:** 
[Playground example](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=1#code/C4TwDgpgBAKhDOwoF4oG8BQUoG14C4pEAnASwDsBzAXUM22wHsxhTHyBDAGwDEBXcgGNW7APyEAFBwDKwMlUIkKlAJQoAfFABujUgBMsUAL4YTGQe0RRgCYIThXU9KAFsQs+ZTpRmIzrwFhNnJJGTllRXCqNWRNNCgLcnhGLggAOi5GSikPZRUAbmNjUwxzSyQbRBgACwh+IT8UKAkKMD5gXIUiKNUNdFLsUgAzZsrgHFb2zpooADJZ61sJ8jaOnuo032DueqD2NWdsMeXV6Y2t9h3AvxaVqZ6CrBMTIA)

**Comment by RyanCavanaugh** [comment]
Duplicate #36230
