### ISSUE TITLE
TypeScript can't parse the nullish coalescing operator in .js files after hot reload

### ISSUE THREAD

**Issue by ms-dosx86** [microsoft/TypeScript#36924]
We are migrating from AngularJS to Angular 9 with hybrid mode, so we have to use both .js and .ts files. Everything is fine when I use `??` operator in .js file at the first time, I mean when I run `ng serve`. But when I change something in that .js file, hot reload happens and I get this error `Module parse failed: Unexpected token (131:57)`. However if I change something in different file, hot reload happens and everything is fine.

TypeScript: 3.7.5
Angular: 9.0.0

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
