### ISSUE TITLE
Allow function types to omit param names

### ISSUE THREAD

**Issue by jameslong** [Microsoft/TypeScript#3693]
It would be nice to be able to omit function type parameter names. e.g.

```javascript
var identity: <T>(T) => T;
var add5: (number) => number;
```
This could make code more concise and readable in some cases where the param name is not important.

**Comment by RyanCavanaugh** [comment]
See #3081 for discussion of parameters lacking type annotations.

It is waaaaaaaaaaaaaay too late to change this now.
