### ISSUE TITLE
Namespace qualification on export members

### ISSUE THREAD

**Issue by AaronNGray** [microsoft/TypeScript#36938]
## Search Terms

export namespace

## Suggestion

The ability to qualify exports with namespace specifiers rather than having to use the workaround below.
## Use Cases

https://github.com/AaronNGray/QueryJS/blob/master/src/QueryJS.ts#L1831

## Examples

```
namespace QueryJS {
    class Element {
        ...
    }
    class Elements {
        ...
    }
    function $(...) { ... }
    function $$(...) { ... }
}

const QueryJS_Element = QueryJS.Element;
const QueryJS_Elements = QueryJS.Elements;
const QueryJS_$ = QueryJS.$;
const QueryJS_$$ = QueryJS.$$;

export {QueryJS as default, QueryJS, QueryJS_Element as Element, QueryJS_Elements as Elements, QueryJS_$ as $, QueryJS_$$ as $$};
```
Should be able to be specified as follows :-
```
...

export {QueryJS as default, QueryJS, QueryJS.Element as Element, QueryJS.Elements as Elements, QueryJS.$ as $, QueryJS.$$ as $$};
```
Note I am using Element which clashes with DOM's Element, hence needing the QueryJS namespace. I would have liked to have been able bring DOM in in a namespace.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Namespaces are just objects so this isn't meaningfully different from
```ts
const obj = { a: 10 };
export { obj.a as A };
```
which isn't legal JS syntax either. This should be taken as a TC39 proposal to allow more expression forms on the left side of `as`
