### ISSUE TITLE
Union type tolerates types merge/combination 

### ISSUE THREAD

**Issue by quasiunafantasia** [microsoft/TypeScript#36945]
**TypeScript Version:**  3.7.5

**Search Terms:**
union combined, union merged
**Expected behavior:**
none of the statements should be valid, because the provided type does not match any signature of the union.
**Actual behavior:**
all the statements are valid

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/20863

**Code**
```ts
type WithTotalNumber = { total: number, perPage: number }

type WithTotalPages = { totalPages: number }

type WithTotal = WithTotalNumber | WithTotalPages

function plain(total: WithTotal) { }

function generic<T extends WithTotal>(total: T) { }


plain({ totalPages: 1, total: 2 })
generic({ totalPages: 1, total: 2 });

const shouldFail: WithTotal = { totalPages: 1, total: 2 };

const actuallyFails: WithTotalNumber = { totalPages: 1, total: 2 }
const actuallyFails2: WithTotalPages = { totalPages: 1, total: 2 }




```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function plain(total) { }
function generic(total) { }
plain({ totalPages: 1, total: 2 });
generic({ totalPages: 1, total: 2 });
const shouldFail = { totalPages: 1, total: 2 };
const actuallyFails = { totalPages: 1, total: 2 };
const actuallyFails2 = { totalPages: 1, total: 2 };

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=22&pc=1#code/C4TwDgpgBA6glsAFgFQPbAIYBsByBXAWwCMIAnKAXigG8ph1sAuKAO0JNIBopJSAFDAHMIzNsTJQAvgChpoSLAQoGWAcIDOlGnRVqI60ewky54aPCRpMWLReXX848gB9Fl3UP2yAZnhYBjYDhUFh4sDDgWAAp6a2Y7K2wASm0TXwCgkKhhFjI4fwAeZCgIAA9gCBYAE00ElQA+GJVmZBTaE2kwcMio2ljsPQMoAEZufqxmACYpJOkcvP9enWtB5lHlpihpySSAbll-EPVgKHVEVDwsKoAxCIm3e2wtPo8NNbHmral96UOWY6gGECeGwWBAtzgWCGdQcRnIVBeK08Q3W4ymUl+RxOQOAIKwYIhUMm8SUiVUyOeG3JbxGHziXw60iAA)

**Comment by RyanCavanaugh** [comment]
I don't understand. This is definitely valid code; in all cases you have a valid `WithTotalNumber`. Why do you think it should be invalid? What problem is resulting?

**Comment by quasiunafantasia** [comment]
sorry for a typo in the demo and thanks for not closing this right away :), updated the demo (the types dont have any common properties)
I get the error for the last 2 statements, so my value is neither type  `WithTotalNumber` nor `WithTotalPages`. It is tolerated as a valid input when I use a union type though

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Object types are not sealed, so you have an object that matches both union types, which is fine - it doesn't need to match exactly one of them.

**Comment by quasiunafantasia** [comment]
i cant really get this
my input `{ totalPages: 1, total: 2 }` is not a valid `WithTotalNumber` - its missing `perPage` property
and its not `WithTotalPages` - there is an extra property `total`
typescript indicates errors for these types but stops showing an error when using a union type

**Comment by RyanCavanaugh** [comment]
> I would expect A | B type to strictly check if the object type is A or B, not something in between

Some type `T` is assignable to `A | B` if it's assignable to `A` or is assignable to `B` or both.

Excess property checking is "outside" the type system; it operates more like a lint rule. A property is excess when assigning to `A | B` if there's no corresponding property in `A` *and* if no corresponding property in `B`

**Comment by quasiunafantasia** [comment]
thank you for clarifications
