### ISSUE TITLE
non-null assertions break CFA

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#36958]
**TypeScript Version:**  3.7.x-dev.20200221

**Search Terms:**

**Code**

```ts
const m = ''.match('');
m?.[0] && m[0];
m?.[0]! && m[0];
m?.[0].length! > 0 && m[0];
m?.[0].split('').slice() && m[0];
m?.[0].split('')!.slice() && m[0];
```

**Expected behavior:**

```ts
const m = ''.match('');
m?.[0] && m[0]; // ok
m?.[0]! && m[0]; // ok
m?.[0].length! > 0 && m[0]; // ok
m?.[0].split('').slice() && m[0]; // ok
m?.[0].split('')!.slice() && m[0]; // ok
```

**Actual behavior:**

```ts
const m = ''.match('');
m?.[0] && m[0]; // ok
m?.[0]! && m[0]; // error
m?.[0].length! > 0 && m[0]; // error
m?.[0].split('').slice() && m[0]; // ok
m?.[0].split('')!.slice() && m[0]; // error
```

**Playground Link:** http://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200221&ssl=5&ssc=34&pln=4&pc=28#code/MYewdgzgLgBAtjAvDA5CgdHAhlYALACjQEoBuAKDgH50BtABgF0YAyF+Bxi6upgQlbs4nbjU7oANgFMwAcyh4BAPhj1BHJqN6N0EAA4SAllCIpiuo8CkFi64Zspimug8dPE+Fw1Zt2RQA

**Related Issues:**

**Comment by falsandtru** [comment]
cc @DanielRosenwasser

**Comment by macabeus** [comment]
What is CFA?

**Comment by DanielRosenwasser** [comment]
control flow analysis
