### ISSUE TITLE
regression from 3.7.5 - Custom elements doesn't allow constructor parameters

### ISSUE THREAD

**Issue by mityok** [microsoft/TypeScript#36965]
Having extra parameters in constructor of custom elements causes error in 3.8.2:

Argument of type 'typeof Foo' is not assignable to parameter of type 'CustomElementConstructor'.(2345)

works just fine in 3.7.5

**TypeScript Version:**  3.8-Beta

**Search Terms:**

**Expected behavior:**

**Actual behavior:**

**Related Issues:**

**Code**
```ts
class Foo extends HTMLElement {
  constructor(a:string) {
    super()
  }
}

window.customElements.define('custom-tag', Foo)

class Bar extends HTMLElement {
  constructor() {
    super()
  }
}

window.customElements.define('another-custom-tag', Bar)
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class Foo extends HTMLElement {
    constructor(a) {
        super();
    }
}
window.customElements.define('custom-tag', Foo);
class Bar extends HTMLElement {
    constructor() {
        super();
    }
}
window.customElements.define('another-custom-tag', Bar);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ts=3.8-Beta&ssl=1&ssc=1&pln=15&pc=56#code/MYGwhgzhAEBiD29oFMAeAXZA7AJjAEgCoCyAMgKIjIC2260A3gFDTTDxYToBOArsOnjcAFGABcXbgEssAcwCUjFq2gReAB2Qj5ygL5N9TAO4yc8IwDpgvLvGqUadCBZzIAZjOTCA5NdvUAWnQwWW8AGjhEHSZQSBgAITBuFAxsPGgiMgdaLHpmVnZOHn5BbSUVVQ0tYR1WfUMTXHMrG0F7Khz0Z1cPLC9vMCx4dAALLQC-NqCQ8OhE7nkgA)

**Comment by leon** [comment]
same for me with Angular Elements and TypeScript 3.8.2

**Comment by lukechu10** [comment]
What I did is mark the argument as optional with `?`

**Comment by mityok** [comment]
> What I did is mark the argument as optional with `?`

that's the first thing i did :)
but that just felt like a workaround, that makes the code to lose some of it robustness and validations.

**Comment by TimvdLippe** [comment]
This change seems related: https://github.com/microsoft/TSJS-lib-generator/pull/815
