### ISSUE TITLE
Wrong conditional type using "extends" never

### ISSUE THREAD

**Issue by atothek1** [microsoft/TypeScript#36974]
Dear Typescript team,

Using conditional types that check against never, are always fall through to the last else branch.

**TypeScript Version:**  3.7.x; 3.8.x

**Search Terms:**
conditional type, never, extends 

**Code**

```ts
interface ActionWithType<TType> {
    readonly type: TType
}

interface ActionWithPayload<TType, TPayload> extends ActionWithType<TType> {
    readonly payload: TPayload
}

interface ActionWithPayloadAndMeta<TType, TPayload, TMeta> extends ActionWithPayload<TType, TPayload> {
    readonly meta: TMeta
}

type Action<TType, TPayload = unknown, TMeta = unknown> = TPayload extends never
    ? ActionWithType<TType>
    : TMeta extends never
        ? ActionWithPayload<TType, TPayload>
        : ActionWithPayloadAndMeta<TType, TPayload, TMeta>;

enum ActionType { 
    ActionTypeA = "ActionTypeA",
    ActionTypeB = "ActionTypeB"
}

interface PayloadType {
    readonly id: string;
}

type MySimpleAction = Action<ActionType.ActionTypeA>;
type MyPayloadAction = Action<ActionType.ActionTypeB, PayloadType>;
```

**Expected behavior:**
```ts
// expected MySimpleAction  === ActionWithType<ActionType.ActionTypeA>;
// expected MyPayloadAction === ActionWithPayload<ActionType.ActionTypeA, PayloadType>;
```
**Actual behavior:**

```ts
// actual   MySimpleAction  === ActionWithPayloadAndMeta<ActionType.ActionTypeA, unknown, unknown>;
// actual   MyPayloadAction === ActionWithPayloadAndMeta<ActionType.ActionTypeA, PayloadType, unknown>;
```
**Playground Link:** 
hovering over the MySimpleAction and MyPayloadAction shows the  actual signature

[Playground example](https://www.typescriptlang.org/play/?ssl=14&ssc=1&pln=12&pc=1#code/JYOwLgpgTgZghgYwgAgIILMA9iA6sMACwBUBPABwgB5izKA+ZAbwChl3koI4ATHAG1LIwFCAC5ktUSwC+LFqEixEKdJhz4iABTil+WXjToQANJJ16DPRhAAekEDwDOaDNjwESoo6MasOnNx8IILI5Lr6vBLEFpE8svKK0PBIruoe2hFWqI4AshBgcD6UZjFZvKX5hTb2EI4uau6ahLFWxabm5dbMbBxcvAJCALYFcNFVcAksIpRp7u2lrbzIALzIAK4gANYgWADuIJWjqxvbuweMa2WWy3YOzsggEABu0L3sAPxzGp7G7fTvZDjY53OoPJ6vKCAgJfRo-TI3HgLTqIgEBAISOEZFpdHI8CbI65xI7VADc8jq6yG3xAxmYyEBWOMqBOACImaJUKyTIy3DhjAAhNkcygC1lTJLKVJLHh0-x9IKDZDAHgSJxgKCgADm5Lk01EyFypAAysAhuR+BAsScsVQRRAAHT21D0ckzFBGmXWta2+1Ovm00QCswy4yutgsAD0keQdkoGAgPENJrNFqtAfYKyzNOafz9zvD0eQiDA6zg-A4RtN5st1tW2axzS9eVGdoDxn96WZZk2O32h1OfYu5KLcYgCaTntxGazPoDTa6ba7ok77m7yFDvhHMZLZYr7CniO9Dfnnmb+Nb+fbnJDXWMPbO-fDQA)

Info:

if I change the conditional type to the following it is working as I expected.
Maybe I totally not got the gist of the never and unknown types.

```ts
// proper working conditional type
type Action<TType, TPayload = undefined, TMeta = undefined> = TPayload extends undefined
    ? ActionWithType<TType>
    : TMeta extends undefined
        ? ActionWithPayload<TType, TPayload>
        : ActionWithPayloadAndMeta<TType, TPayload, TMeta>;
```

And thank you for this perfect Language.

**Comment by RyanCavanaugh** [comment]
`unknown extends never` is `false`, so TS chooses the false branch.

**Comment by atothek1** [comment]
> `unknown extends never` is `false`, so TS chooses the false branch.

Thank you @RyanCavanaugh for such a simple explanation, I think i got it.

everything is extending unknown, and unknown extends nothing else, as unknown is the top type of everything.

never is the bottom type, so nothing extends never.

Never the less i stumbled over something else that goes allongside which i do nit understand it is a bit more complex as its using infer.
Code:

```ts
interface ActionWithType<TType> {
    readonly type: TType
}

interface ActionWithPayload<TType, TPayload> extends ActionWithType<TType> {
    readonly payload: TPayload
}

interface ActionWithPayloadAndMeta<TType, TPayload, TMeta> extends ActionWithPayload<TType, TPayload> {
    readonly meta: TMeta
}

type Action<TType, TPayload = undefined, TMeta = undefined> = TPayload extends undefined
    ? ActionWithType<TType>
    : TMeta extends undefined
        ? ActionWithPayload<TType, TPayload>
        : ActionWithPayloadAndMeta<TType, TPayload, TMeta>;

enum ActionType { 
    ActionTypeA = "ActionTypeA",
    ActionTypeB = "ActionTypeB"
}

interface PayloadType {
    readonly id: string;
}

interface MetaType {
    readonly status: string;
}

type FnWithType<TType> = () => Action<TType>;
type FnWithTypeAndPayload<TType, TPayload> = ( payload: TPayload ) => Action<TType, TPayload>;
type FnWithTypeAndPayloadAndMeta<TType, TPayload, TMeta> = ( payload: TPayload, meta: TMeta ) => Action<TType, TPayload, TMeta>;

// conditional type for the creator function type definition
type CreateFn<TType, TPayload = undefined, TMeta = undefined> = TPayload extends undefined
    ? FnWithType<TType>
    : TMeta extends undefined
        ? FnWithTypeAndPayload<TType, TPayload>
        : FnWithTypeAndPayloadAndMeta<TType, TPayload, TMeta>;

// infered types
export type ExtractType<T> = T extends Action<infer TType> ? TType : undefined;
export type ExtractPayload<T> = T extends Action<unknown, infer TPayload> ? TPayload : undefined;
export type ExtractMeta<T> = T extends Action<unknown, unknown, infer TMeta> ? TMeta : undefined;

// factory method
function create<TAction extends Action<ExtractType<TAction>>>(type: ExtractType<TAction>):
    CreateFn<ExtractType<TAction>, ExtractPayload<TAction>, ExtractMeta<TAction>> {

    return ( ( ...args: unknown[] ) => { 
        const [
            type,
            payload,
            meta
        ] = args;
        return { type, payload, meta } as unknown as TAction;
    } ) as unknown as CreateFn<ExtractType<TAction>, ExtractPayload<TAction>, ExtractMeta<TAction>>;
}

type MyAction = Action<"MyAction", boolean, MetaType>;
// factory methods returns a union type, as it looks like infer boolean is handled as true | false
const myActionFn = create<MyAction>("MyAction");

// call with boolean value true or false throws type error,
// true | false not assignable to type never
myActionFn(true, { status: "error" });

// expected myActionFn  === FnWithTypeAndPayloadAndMeta<"MyAction", boolean, MetaType>;
// actual   myActionFn  === FnWithTypeAndPayloadAndMeta<"MyAction", true, MetaType> | FnWithTypeAndPayloadAndMeta<"MyAction", false, MetaType>;;
```
[Playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgIILMA9iA6sMACwBUBPABwgB5izKA+ZAbwChl3koI4ATHAG1LIwFCAC5ktUSwC+LFqEixEKdJhz4iABTil+WXjToQANJJ16DPRhAAekEDwDOaDNjwESoo6MasOnNx8IILI5Lr6vBLEFpE8svKK0PBIruoe2hFWqI4AshBgcD6UZjFZvKX5hTb2EI4uau6ahLFWxabm5dbMbBxcvAJCALYFcNFVcAksIpRp7u2lrbzIALzIAK6OEDCgEDyVo6sbWzsge4xrZZbLdg7Oxzzbu-EBAPxzGp7G7fS97OOHW51e6bR6nPZ-ALId6NT6Za48BadBG-KEcCSwjItLo5HgTJFXOIHaoAbnkdXWQw+IGMzGQkMxxlQRwARIzRKgWSYGW4cMYAEKs9mUfksqZJZSpJY8Wn+PpBQbIYA8CROMBQUAAczJcgU4GSKmQE1lkP6wVCargYHWTlV6q1OvkMxQADEsd8pAwjgAKACUq0YmJ+ZOdyDdzSZjmlBOlF2Q3rCXWi0uQ-pWgd5IBjXXoIdEYfdHKjOLyo2zCOJcDjCfCCOTXTMI0KAMKqYD1PLRMkE1z8gA9H3kAgcDwCO44PxhPmYFgoMJCCgEP0wLPkDBNpmp7MwaAxzhpvmAMLLiBuztWI6gp5nfbdw5rK-g7qXFNA+oPa8Qt4FiPeT0QVF0TvVs3xBE5nkhb9wy+IseGjf9FhzSCgOgohIzgks8TLBDkS7YgezJFgByVEAYGgPYtwgJwWDschZzASjkAAUXsKBEDAD042IZBQIaTMqFAMi53-Rh3n-ZAJEfZ4yVo+jGJY9V2PgrieNqd8g02ABrEAsAAdxAMxBOgXCrFEkzlkk8Cbxk2w6KgBjQwUtiMHxYgVN4jstJ0-SzC8vSDJIoTgKraFgokj8n0I4iUhXKBhgKQgsHidcQE3JduEgGhMVUu4+PSKgnPYj1MXoUrvWdCRCowYrM3oX0xEhY8MtPLMqo4v8SrMNr4M65jWPY1ySr8eQAi4a0oBAeMpoAOlmuAoE1W1jm0-yAG0AF023TOlkPYYcQDVZBVt2qFnW5NE0VrIkToCJtJgu5BNrWebFrJB6xvWCa6TOxMK2QO7kBkZA4BcPz9OBlxiExN6OCB-0QeW7zJoRpqrRagr+uqjraq6zGwB6nG+sUlzsKGx0D1mXJSGytYgxZKnMS5ZAACMsCwfhuAC41fDJfbDqGanMzdI50rRqgGdq716cF9IWV9KLBwQCdJ10zwWbZjm4EmgA3Cd1hQdV9eQVd4H4JwDcIKA9JcUNoCtqBuWInSGJBpxgE1EA4GZjnhCwRizm16AWAFzE3XKqB9bMJhkEta0lpZO3ZxZQH5f7QdaIgDAKJDoXJtWFY1lQrxKFxaVcXxaXGbMVn2c5sxuYYMliPY9YJw4HP0mF-PC8LEviwRcuy0rzMmcNjoG4A5AAB8fxgvuMIH0tCioYfZbMU3zfr0ZjFzMkgA)
