### ISSUE TITLE
.d.ts files with invalid imports are emitted with no errors or warnings

### ISSUE THREAD

**Issue by fgallardograzio** [microsoft/TypeScript#36971]
**TypeScript Version:**  3.9.0-dev.20200223

**Search Terms:** .d.ts import cannot find module, export type imported from .d.ts

**Code**

```ts
// tsconfig.json
{
  "compilerOptions": {
    "declaration": true,
    "outDir": "lib"
  }
}
```
```ts
// types.d.ts
export interface MyType {}
```
```ts
// index.ts
import { MyType } from './types';
export let myVar: MyType;
```

**Expected behavior:**
Since `types.d.ts` will not be included in the build results, it being a 'local' or 'development only' type declaration file, then an _emitted_ declaration file should not be allowed no contain references to it.
So I would expect a build error explaining that the exported constant `myVar` uses a type that cannot be emitted.
Or, perhaps (although I'm not very convinced about this myself because of the possible complexities it may involve, and the concepts that may be affected), copy or resolve those types and properly include them as needed in the emitted `index.d.ts` file, inline, instead of importing them.

Importing from a .d.ts file and using those types internally should of course still be fine, since that would not result in them being included in an emitted declaration file.

IMO, this may be analogous to errors such as:
- `Return type of exported function has or is using name 'xxx' from external module 'yyy' but cannot be named.`
- `Export of module has or is using private name 'xxx'.`

that are a result of a module exporting a type, or a variable using a type, that cannot be used or referenced.

**Actual behavior:**
Build process completes successfully, and `lib/index.d.ts` get emitted with the following content:
```ts
// lib/index.d.ts
import { MyType } from './types'; // error: Cannot find module './types'.
export declare let myVar: MyType;
```

**Consequences**
Now, projects that depend on this package will not be able to compile, since **they** are the ones that will get that `Cannot find module './types'.` error.
Or, if they have the `skipLibCheck` compiler option, then the type will fall back to an `any` on their side, resulting in more difficult to track errors.
An extremely trivial and nonsensical example could be:
```ts
// my-package:
// types.d.ts
export type MyType = {
  str?: string;
  num?: number;
}; 

// index.ts
export { MyType } from './types';
```
```ts
// Some package that depends on my-package:
// somefile.ts
import { MyType } from 'my-package';
// Example of a type that uses MyPackage's 'MyType'
type MyPickedType = Pick<MyType, 'str'>;
```
In such a case, `MyPickedType` would silently resolve to `{ str: any }`. So we lost `str`'s type, as well as its 'optional property' flag. So type checking is lost, and a confusing error saying a mandatory `str` property is now required would appear when in fact it could be safely omitted.

**Playground Link:** Not relevant.

**Related Issues:** Couldn't find any that specifically relates to such a scenario.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior (as evidenced by the fact that it's worked this way since day 1 of TypeScript); the idea is that downstream projects will consume the sameish set of `.d.ts` files that you do. Your project itself should not be hand-authoring `.d.ts` files you intend to be seen by consumers of your project; this is why it's legal to write "only types" in a .ts file

**Comment by fgallardograzio** [comment]
Thanks @RyanCavanaugh 

I should've been clearer, sorry. I completely agree with your point and the way .d.ts files work. In fact what you said is more or less the same argument I wanted to present.
Projects are not supposed to be doing what you're describing, and it will 100% result in consumers either missing those 'hand-authored' types wrongfully placed in and imported from a `.d.ts` files (either accidentally, naively, via third party tools, whatever), or getting the `cannot find module` error themselves.

So shouldn't it be considered a compile-time error?

**Comment by RyanCavanaugh** [comment]
The problem here is that you're assuming a meaningful distinction between "`.d.ts` files I wrote myself by hand" and "`.d.ts` that other people will also be importing", but this distinction is only one of convention.

For example, by your rule, it should be illegal for someone to refer to some type in `node`'s `.d.ts` files because that file isn't going to be copied to the output folder.

**Comment by fgallardograzio** [comment]
Well, I only meant _local_, _unresolvable_ imports in emitted `.d.ts` files, but I see what you mean now.
And, AFAIK it'd be out of scope for `tsc` to figure out which imports can or can't be resolved in emitted files.

**Comment by RyanCavanaugh** [comment]
I suppose if you had a *relative* import to a `.d.ts` file that'd be pretty unlikely to work, but we just really don't know for sure how these will be consumed
