### ISSUE TITLE
BigInt.toLocaleString does not have any arguments, and Intl.NumberFormat does not support formatting BigInt

### ISSUE THREAD

**Issue by TNThacker2015** [microsoft/TypeScript#36970]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
bigint
bigint format
bigint numberformat
**Code**

```ts
console.log((2000n).toLocaleString("fr"));
console.log(new Intl.NumberFormat("fr").format(3000n));
```

**Expected behavior:**
The code runs without errors, and "2 000" and "3 000" is logged to the console.
**Actual behavior:**
The code fails to compile, with the errors
```
Expected 0 arguments, but got 1. ts(2554)
Argument of type '3000n' is not assignable to parameter of type 'number'. ts(2345)
```
It shouldn't fail. [Reference](https://v8.dev/features/intl-numberformat)
ECMA Specification
![image](https://user-images.githubusercontent.com/37024464/75125627-d8ad9c80-566a-11ea-8f99-900995ddd97e.png)

**Playground Link:** [Link](https://www.typescriptlang.org/play/?target=7&ts=3.9.0-dev.20200222&ssl=2&ssc=13&pln=2&pc=1#code/BQJgDBB2CUB0AuB7AMogxgQwDYFMDK8ATgJaQDmwARAGaGXQDcAsAFCQ4DuABAJKTxZYAOQCuAWwBGOQgDFEhMRnhVa9WNXmLlAZghgYDIA)

**Related Issues:**

**Comment by ShuiRuTian** [comment]
About the second part 
`console.log(new Intl.NumberFormat("fr").format(3000n));`
we could do it like
`const bigdddint = BigInt(1);
console.log(new Intl.NumberFormat("fr").format(bigdddint));`
This time we get error: "Argument of type 'bigint' is not assignable to parameter of type 'number'."
It seems that BigInt type could not be converted to number type. 
But should this convention happen?
