### ISSUE TITLE
Feature Request: Compiler Option to allow accessing private method/variables

### ISSUE THREAD

**Issue by tomardern** [microsoft/TypeScript#36985]
## Search Terms

access private property typescript compiler option

## Suggestion

A compiler option that allows direct access to a private property/method.

## Use Cases

Would be nice to have a compiler option to allow unit testing (for example, we use angular and jest) to quickly override a private dependancy, function or method.

## Examples

```
class Foo {
 private bar;
 
 private someFunction(): string {
	return 'hello';
 }

}
```

If the compiler flag is enabled, allow the following:
```
// Example 1
const fooInstance = new Foo();
fooInstance.bar = 'hello world';

// Example 2
fooInstance.someFunction(); // Returns 'hello'

// Example 3
fooInstance.someFunction = () => 'world';

fooInstance.someFunction(); // Returns 'world'
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
FYI you can use `fooInstance["bar"] = ` to do this today if you like

**Comment by tomardern** [comment]
@RyanCavanaugh - Yep that's what we've been doing, however, it'll be nice to not have errors similar to the following on compile time

`Property 'someFunction' is private and only accessible within class 'Foo'`

**Comment by RyanCavanaugh** [comment]
Just really haven't seen any other demand for this despite `private` being in since day 1, so declining.
