### ISSUE TITLE
Empty array's type changes from never to any when turning on noImplicitAny

### ISSUE THREAD

**Issue by dinofx** [microsoft/TypeScript#36987]
The following code:

```
const foo = [];
foo.push('bar');
```

Is clean with both `noImplicitAny` and `strictNullChecks` turned off.  `foo` is typed as `Array<any>`, as expected.

When you turn on 'strictNullChecks', foo is typed as `Array<never>`.  This is unexpected.
http://www.typescriptlang.org/play/index.html?noImplicitAny=false#code/MYewdgzgLgBAZiEMC8MDaBdA3AKBwkAOgAcBXCACwAoByAIwEMAnGgSiyA

Then, when you *also* turn on 'noImplicitAny', foo is once again typed as `Array<any>`.

It seems the middle configuration (null checks true, but implicit any false) has the incorrect behavior.  Adding a more restrictive setting shouldn't relax the array type.

I've seen issue #8944, however that issue seems stale, since it suggest that the code above would report an error when `noImplicitAny` is used, which is not happening.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior for backward compatibility reasons
