### ISSUE TITLE
'yes' | 'no' converted to string when in react state

### ISSUE THREAD

**Issue by matthewoates** [microsoft/TypeScript#37005]
**Search Terms:**
enums react, unions broken, react union broken, react state union

**Code**
```ts
import React, { Component } from 'react';

type PropsType = {};
type StateType = {
    ans: 'yes' | 'no'
}

// this works
const data: StateType = { ans: 'yes' };

export default class ExampleComponent extends Component<PropsType, StateType> {
    // error
    state = { ans: 'yes' };

    constructor(props: PropsType) {
        super(props);

        // this works
        this.state = { ans: 'yes' };
    }
}
```
[Playground Link](https://www.typescriptlang.org/play/?ssl=19&ssc=2&pln=1&pc=1#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQnMAnmEjgAFemADOAFX6CAvLkpc+AuAGUYKGEinK5OTnANwUJMQC4mvJGMZwAPkxIRGnStwD0buDAAWwMXAB3aABrMU40UjF4ABMNFHM1DS1pOF0jE3NGS2s4BW4kAA9IWDhopBoUAFcAG3g0apQxfwBRApRwaqRCYjIKOELNEmj-bshemAAeEQhxbSRsRM05gD5cfUMopNTcdLMLKxs89YMIkxgoSoxoAAowUT3p2ekASjXDd7gxSoEoW-vnrjHD4+PwAOk2mm2eGMeyyB1yXHerkoQA)

**Expected behavior:**
no errors

**Actual behavior:**
error on `state = { ans: 'yes' };`

```
(property) ExampleComponent.state: {
    ans: string;
}
Property 'state' in type 'ExampleComponent' is not assignable to the same property in base type 'Component<PropsType, StateType, any>'.
  Type '{ ans: string; }' is not assignable to type 'Readonly<StateType>'.
    Types of property 'ans' are incompatible.
      Type 'string' is not assignable to type '"yes" | "no"'.(2416)
```

**Comment by RyanCavanaugh** [comment]
Duplicate #10570. You can use `{ ans: 'yes' } as const`" in the meantime.
