### ISSUE TITLE
Code completion suggests cyrillic words from the next comment as completion variants

### ISSUE THREAD

**Issue by zhuravlikjb** [microsoft/TypeScript#37009]
**TypeScript Version:**  typescript@3.9.0-dev.20200225

**Search Terms:** completion comment

**Code**
Invoke code completion after '.' and before 'value' in 'param.value':
```ts
type BoxedValue<T> = { value: T };
type BoxedArray<T> = { array: T[] };
type Boxed<T> = T extends any[] ? BoxedArray<T[number]> : BoxedValue<T>;
function foo<T>(param: Boxed<T>) {
    console.log(param.value); // ошибка, но комплишн предлагает value
}
```

**Expected behavior:**
No words from the comment in completion

**Actual behavior:**
Words from the comment appear in completion
![image](https://user-images.githubusercontent.com/4499495/75232791-1bc95600-57b8-11ea-9464-9dccc7e0f2d0.png)

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=22#code/C4TwDgpgBAQg9gDwgEwGoEMA2BXCAeAFQD4oBeKAbygDctcAuKAqAXwG4AoUSWRFAQQBOg9CEIlyVdMNGMCAbQC6rTt2jwkycWSZQICYBAB2yAM5R0RkEqgB+XpqEixCo9gC2AIwiDFJRhooGDj4xJwAZthGAMbAAJZwRlDhcHDiABRg0ujuAXxaxACUlBxQZVDRiaZwmBAAdJhwAOaZ2e51tCGFbFAA9L1QgHwggBIggBwggIwggFwggAwgADRQgLwgg1CTg4A8IID8IIDcIKPDC1AbgAIggKwggCwgW9OAzCDTx4BCIDR0EBwsQA

**Comment by IllusionMH** [comment]
It's VS Code suggestions which are controlled by `"editor.suggest.showWords": true` and `"editor.wordBasedSuggestions": true`

**Comment by zhuravlikjb** [comment]
True. What misled me is that TS playground shows the same. But if it is powered by the same engine as VS Code, that's understandable.

Feel free to either move the issue to VS Code (as such items are not very valid there), or close it.
Thanks for the explanation.

**Comment by RyanCavanaugh** [comment]
Yep, the Playground and VS Code share a common editor component. Thanks!
