### ISSUE TITLE
Completion of object literal/binding patterns suggests identifiers at beginning of existing identifier

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3700]
```TypeScript
interface I {
    property1: number;
    property2: string;
}

var x: I = {
    /**/property1
}
```

Both `property1` and `property2` are suggested at that position even though it currently exists in the object literal. To make this worse, if you commit with `property1, you end up with the following:

```TypeScript
interface I {
    property1: number;
    property2: string;
}

var x: I = {
    property1property1
}
```

**Comment by mhegazy** [comment]
we still want  property1 to show if you are in the middle, so that ctrl+Enter would get you the right thing again.

```ts
var x: I = {
    pro/**/perty1
}

I would check with @CyrusNajmabadi on the best way to handle this.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser can you hold off on new labels? Let's talk on Monday.

**Comment by mhegazy** [comment]
This is caused by Roslyn commit logic. see:
```ts
var x = "";

x./**/toString  // Select "toString" again.
```

@DanielRosenwasser can you port to roslyn?
