### ISSUE TITLE
outputFile umd support？

### ISSUE THREAD

**Issue by yisar** [microsoft/TypeScript#37006]
## Suggestion

Use `--outputFile` for bundling `umd` or `cjs` modules

## Use Cases

- to build a single file, which I can publish to npm
- just use tsc, without rollup or any others

## Examples

```json
  "compilerOptions": {
    "module": "umd",
    "outFile": "./dist/doux.js",
    "rootDir": "./src"
  }
```

**Comment by RyanCavanaugh** [comment]
There are a lot of great bundlers these days and we don't really think it's worth it for TS to invest a bunch of time for something that's ultimately duplicative of existing tools.
