### ISSUE TITLE
Imperfect type inference and type guards

### ISSUE THREAD

**Issue by Akimotorakiyu** [microsoft/TypeScript#37007]
**TypeScript Version:**  3.8.2

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

function instantiateReactComponent(element: object|string|number|boolean):any {

    const elementType = typeof element;

    if (elementType !=="object") {
        return element;
    }

    if (typeof element !=="object") {
        return element;
    }
}
```

**Expected behavior:**
```ts

function justAttemp(element: object|string|number|boolean):any {
    const elementType = typeof element; // type should be "object|string|number|boolean"

    if (elementType !=="object") {
        return element; // type should be "string|number|boolean"
    }

    if (typeof element !=="object") {
        return element;// type in here is right
    }
}
```
**Actual behavior:**
![图片](https://user-images.githubusercontent.com/31165554/75213975-dfe9bd00-57c6-11ea-9629-9d08c7073fcf.png)
![图片](https://user-images.githubusercontent.com/31165554/75213981-eaa45200-57c6-11ea-93f5-ef6610673c0a.png)
![图片](https://user-images.githubusercontent.com/31165554/75213998-fc85f500-57c6-11ea-9205-2927d4a0e791.png)

**Playground Link:** [http://www.typescriptlang.org/play/index.html?ssl=12&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABDMBnKBDMsNQKYBKeG0AwnALYAOCe2AFHgDZ4V1QBcicARgFZ5oAH3QAnFAHMhYEBR55RQnnDgssASg5YAnogDeAWABQxxGcQQE6RM1bsAKtqp5EAXkRQneOMBss22ADcxqbmML6M-g5eiACErq4ARLwC0Inq+qHm5qJ4UCCiSLYBUMFG2QC+IeVhEZ7OPn522HEJyfyCUOmZNdlmufmFTSVllcYVQA](http://www.typescriptlang.org/play/index.html?ssl=12&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABDMBnKBDMsNQKYBKeG0AwnALYAOCe2AFHgDZ4V1QBcicARgFZ5oAH3QAnFAHMhYEBR55RQnnDgssASg5YAnogDeAWABQxxGcQQE6RM1bsAKtqp5EAXkRQneOMBss22ADcxqbmML6M-g5eiACErq4ARLwC0Inq+qHm5qJ4UCCiSLYBUMFG2QC+IeVhEZ7OPn522HEJyfyCUOmZNdlmufmFTSVllcYVQA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate e.g. #22341

**Comment by Akimotorakiyu** [comment]
@RyanCavanaugh Not exactly.

this part is not the same.

Expected behavior:
```ts
function justAttemp(element: object|string|number|boolean):any {
    const elementType = typeof element; // type should be "object|string|number|boolean"
}
```
Actual behavior:
![图片](https://user-images.githubusercontent.com/31165554/75306868-3d444380-5885-11ea-8ce9-ff7a22a34c98.png)
