### ISSUE TITLE
Expand Selection in function and arrow function skips body block

### ISSUE THREAD

**Issue by alexilyaev** [microsoft/TypeScript#37030]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.2

**Search Terms**
- expand selection
- selectionRange

---

Issue Type: <b>Feature Request</b> (maybe **Bug**)

### Reproduce

Given these code examples (`javascript` or `javascriptreact`), run **Expand Selection** a few times:

```js
const func = () => {
  |<-- put caret here
};
// or...
const func = () => {|<-- put caret here

};
// or...
function func(params) {
  |<-- put caret here
}
```

### Actual

Expand Selection skips the body of the function and goes straight to selecting the whole function.

![exapnd-selection-arrow-func](https://user-images.githubusercontent.com/480469/74763971-7c710400-5289-11ea-8b0c-d7de831c1af8.gif)

### Expected

Should be able to select the function body when using Expand Selection, regardless of where I started inside the function.

In WebStorm it works as expected:

![webstorm-expand-func](https://user-images.githubusercontent.com/480469/74765415-34071580-528c-11ea-8910-b3ec63217034.gif)

I find myself updating the body of an arrow function dozens of times a day, usually to inline the return expression as an implicit return.
Of course there are extensions and ESLint rules that can help with that, but Expand Selection should respect the function body block regardless. 

### Update: More examples

```js
const func = () => {
  // some comment
  const one = 1;
};
```

1. Placing caret to the left of `// some`:
   - Expand Selection just once will select the whole arrow function (from `()` to the closing `}`).
1. Placing caret to the left of `const`:
   - Expand Selection actually **works as expected**, after 4 times, only the body of the arrow function is selected (although it doesn't select it including the `{}`, but that's not so bad).

Here's the example where I first encountered this issue:

```js
const func = () => {
  return someFunc();
};
```

1. Select and Cut `someFunc();` (caret will be to the right of `return ` at this point)
1. Expand Selection > results in selecting the whole function (from `()` to the closing `}`)
1. If I first move the caret to the left of `return`, then Expand Selection **works as expected**.

### System Details

VS Code version: **Code - Insiders** 1.40.0-insider (c58aaab8a1cc22a7139b761166a0d4f37d41e998, 2019-10-22T05:25:41.549Z)
VS Code version: **Code** 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
TS server response:

```
[Trace  - 23:38:30.491] <syntax> Sending request: selectionRange (15). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/index.js",
    "locations": [
        {
            "line": 2,
            "offset": 3
        }
    ]
}
[Trace  - 23:38:30.492] <syntax> Response received: selectionRange (15). Request took 1 ms. Success: true 
Result: [
    {
        "textSpan": {
            "start": {
                "line": 1,
                "offset": 14
            },
            "end": {
                "line": 3,
                "offset": 2
            }
        },
        "parent": {
            "textSpan": {
                "start": {
                    "line": 1,
                    "offset": 1
                },
                "end": {
                    "line": 3,
                    "offset": 3
                }
            }
        }
    }
]
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
