### ISSUE TITLE
No type-checking for @property with misspelled type across files

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#37040]
**TypeScript Version:**  3.9.0-dev.20200225

**Code**

**a.js**

```js
/**
 * @typedef MyType
 * @property {sting} [x]
 */

/** @param {MyType} p  */
export function f(p) {}
```

**b.js**

```js
import {f} from "./a.js"
f({ x: 42 })
```

**Expected behavior:**

Error at `sting`.

**Actual behavior:**

No error.
There is an error if we call `f({ x: 42 })` in `a.js`.

**Comment by DanielRosenwasser** [comment]
I'm not seeing this locally - do you have a repro? Is `a.js` actually being type-checked?

**Comment by andy-ms** [comment]
I'm testing this in a directory with only 3 files -- `a.js` and `b.js` as above and this `tsconfig.json`:
```json
{
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"noEmit": true,
	}
}
```

I can verify that `a.js` is being type-checked by adding this at the bottom:

```js
/** @type {numbr} */
const x = 3
```

which correctly produces an error.
