### ISSUE TITLE
Uninitialized instance fields are not added to instances

### ISSUE THREAD

**Issue by parzhitsky** [microsoft/TypeScript#37043]
**TypeScript Version:**  3.9.0-dev.20200225

**Search Terms:** uninitialized not initialized class property in operator

**Code**

Looks like the same code that in JavaScript actually adds a non-static property to an instance, in TypeScript, however, does not.

```ts
class Thing {
	property;
}

const thing = new Thing();

console.log("property" in thing);
```

**Expected behavior:**
<details>
<summary>logs <code>true</code></summary>

![image](https://user-images.githubusercontent.com/59528510/75334386-6a4a2380-5890-11ea-8b1c-ef3769de0137.png)
</details>

**Actual behavior:**
<details>
<summary>logs <code>false</code></summary>

![image](https://user-images.githubusercontent.com/59528510/75334655-e7759880-5890-11ea-88b2-d1faa0b9a4a7.png)
</details>

**Playground Link:** https://www.typescriptlang.org/play/?noImplicitAny=false&ts=3.9.0-dev.20200225#code/MYGwhgzhAEAqAWBLAdgc2gbwFAEgAOATgPZ4CmBALgJ4DcWAvllsEchBdBUmtALzTJSAdzjdUACgCUdZqwhEQpAHQgiEgESES5auugpOY6ViA

**Related Issues:** _(none)_

**Comment by parzhitsky** [comment]
Closed by accident :/

**Comment by IllusionMH** [comment]
>same code that in JavaScript actually adds a non-static property to an instance

Class properties in TS and JS (with class fields proposal) differs (at least at this moment #34787)

If you want to have JS behavior you should set `useDefineForClassFields` to `true`.

**Comment by parzhitsky** [comment]
Seems like duplicate of #34787. Thanks @IllusionMH!
