### ISSUE TITLE
CLI --extend-tsconfig argument

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#37044]
# Search Terms

CLI tsconfig

## Suggestion

Add a mechanism to extend the current ts-config configuration via the CLI utility through an argument.

## Use Cases

I am writing a thin wrapper around the tsc (ttsc) CLI tool to inject plugins for path resolution. I don't want consumers to manually include the plugins so I am attempting to transparently extend an existing target config with the plugin declarations.

This isn't possible so instead I am creating a `tsconfig.temp.json` next to the `tsconfig.json` and cleaning it up after the operation completes

## Examples

```
tsc --extend-tsconfig /absolute/path/to/tsconfig.master.json
```

Inline configuration extension would be fantastic also 
```
tsc --extend-tsconfig--inline "{ \"compilerOptions\": { ... } }"
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by vugryumov-mdsol** [comment]
I really wish this was available. Would be super useful with `lint-staged` where we can't ignore `tsconfig.json` but would like it to only apply to staged files, not the entire project.

**Comment by gburt** [comment]
@alshdavid AFAICT this isn't fixed?  The [CLI docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html) do not show any option that lets one achieve this, and specifying both `-p` and source files still gives

```
error TS5042: Option 'project' cannot be mixed with source files on a command line.
```

So: I think this should be reopened?

**Comment by gburt** [comment]
Ah perhaps this is a dupe of #27379
