### ISSUE TITLE
Extra check before calling method causes problem

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#37041]
I am sure this is reported somewhere but just making sure. I am tsc version:  Version 3.7.2

this works:

![Screenshot from 2020-02-26 00-44-29](https://user-images.githubusercontent.com/11139560/75327500-5cb18100-5831-11ea-85be-cd15d9dcb3cf.png)

but then I add an extra super safety check and it fails unnecssarily:

![Screenshot from 2020-02-26 00-44-11](https://user-images.githubusercontent.com/11139560/75327525-663ae900-5831-11ea-957e-24961a5f706f.png)

maybe it's operator/user error, idk

**Comment by IllusionMH** [comment]
1) Do not ignore template and provide link to playground. It's hard to read code from screenshots.
2) Questions should be asked on StackOverflow first

in your case `isFunc` doesn't have any annotation that will narrow type to function

[Playground](https://www.typescriptlang.org/play/index.html?ts=3.8-Beta&ssl=16&ssc=1&pln=16&pc=14#code/MYewdgzgLgBAlhAYgVzMGBeGAKAHgLhgEMwBPASkwD4YpSAHAUxADMZdMMsByF1YKHHDcA3AFgAUJNCRYCFGgBCjKFEYAnTDgLEy5QhwQ4AdKaLqA5hEIlSAbQC6lDDVvVaDZmw5cefNILC4lIhACaMwAA25owwMtAwIABGAFaEAN6SMDAAtioAFiChAPyE2ESE0OpwYBYANDBJhGDIOUkazq5kkgC+kpLJKcZ5UIWh2NwAjNwNAEzkwQOpwwVFMABk64nLI2MT03ML-RLy-NiDK6NFlJvbQ7tF+zMw84snSPzKqhrnO6uhNy2Fwe4ymz1eQA)

**Comment by RyanCavanaugh** [comment]
@ORESoftware You've contributed a very high quantity of noise to this repo with very little signal at this point. I'm asking you to use other forums to get TypeScript support. You are *uniquely* in the position of having filed nearly 100 issues without identifying a single actual bug, and this is a system for tracking bugs.
![image](https://user-images.githubusercontent.com/6685088/75369737-d9b41900-5878-11ea-8a47-5e7eb9f1f4b4.png)
Further use of the issue tracker for support purposes will be considered abuse.
