### ISSUE TITLE
Redundant lines of code generated from constructors?

### ISSUE THREAD

**Issue by MaikelChan** [Microsoft/TypeScript#3704]
Hello everyone.

I'm learning TypeScript and I noticed some weird behaviour. I don't know if it's intentional or not and I didn't find answers because I don't know exactly how to describe the issue since English is not my main language. But let me show you an example:

I have this class:

```typescript
class Vector2D {

	X: number;
	Y: number;

	constructor();
    constructor(X: number, Y: number);
    constructor(X?: number, Y?: number) {
        this.X = X || 0;
        this.Y = Y || 0;
    }
}
```
And it generates this javascript code, which is fine:

```typescript
var Vector2D = (function () {
    function Vector2D(X, Y) {
        this.X = X || 0;
        this.Y = Y || 0;
    }
    return Vector2D;
})();
```

However, from what I understand, there is a shorter way to write that code that should do exactly the same:

```typescript
class Vector2D {

    constructor();
    constructor(X: number, Y: number);
    constructor(public X?: number, public Y?: number) {
        this.X = X || 0;
        this.Y = Y || 0;
    }
}
```

And it generates this Javascript code:

```typescript
var Vector2D = (function () {
    function Vector2D(X, Y) {
        this.X = X;
        this.Y = Y;
        this.X = X || 0;
        this.Y = Y || 0;
    }
    return Vector2D;
})();
```

It does the same, but notice those two extra lines that have no purpose. So I don't know if I'm doing something wrong, or if this is a normal behaviour or some kind bug.

Thanks for your attention. Greetings! :)

**Comment by mhegazy** [comment]
When annotating a constructor paramter with `public`, `private` or `protected`, the compiler emits code to intialize the properties for you. this helps with common pattern with instance properties initialized to constructor arguments.

So
```ts
class C {
    constructor(private x, public y) {}
}
```
is equivalent to:
```ts
class C {
    private x;
    public y;
    constructor(x, y) {
         this.x = x;
         this.y = y;
    }
}
```
in your example you are intializing the values to `0` if they are empty, so to do that you can:

```ts
class Vector2D {

    constructor();
    constructor(X: number, Y: number);
    constructor(public X = 0, public Y = 0) {
    }
}
```
or as:
```ts
class Vector2D {
    public X: number;
    public Y: number;
    
    constructor();
    constructor(X: number, Y: number);
    constructor(X?: number, Y?: number) {
        this.X = X || 0;
        this.Y = Y || 0;
    }
}
```

**Comment by doskallemaskin** [comment]
I'm not sure if it's a wierd behaviour or if you're just not using default parameters as intended. For instance why don't you just do this:


    class Vector2D {
        X: number;
        Y: number;
        constructor(X:number = 0, Y:number = 0) {
            this.X = X;
            this.Y = Y;
        }
    }

this should cover all the constructors you asked for without overloading it.

or 

    class Vector2D {
        constructor(public X:number = 0, public y:number = 0) {
        }
    }
