### ISSUE TITLE
Generic Type: return type from callback as T incorrect

### ISSUE THREAD

**Issue by RazgrizHsu** [microsoft/TypeScript#37051]
**TypeScript Version**: 3.8.2

**Code**

```typescript
function Test1<T>( msg, fn:(arg:T)=>void, fnTake:(any)=>T )
function Test1( msg, fn, fnTake ) {}

Test1( 'test', (arg) =>{ arg.ZZ }, m => { ZZ:123 } );
//                 Property 'ZZ' does not exist on type 'unknown'
```

![image](https://user-images.githubusercontent.com/3889141/75376211-a0c48480-590a-11ea-8f70-a7189465554f.png)

**Expected behavior:**
expected it to use the return value from the second callback,
but it seems to point to an unknown type

**Comment by RyanCavanaugh** [comment]
Inference can only resolve these in left-to-right order.

**Comment by RazgrizHsu** [comment]
@RyanCavanaugh okay... got it, thank you for explian 👍
