### ISSUE TITLE
Export type alias?

### ISSUE THREAD

**Issue by daniel-shin1104** [Microsoft/TypeScript#3705]
Foremost, thanks for all the work you guys have put into this amazing language. 

Is there a support for `export`ing `type` alias?

For example,

types.ts
```typescript
import express = require("express");

export type ExpressResponse = express.Response;
```

api.ts
```typescript
import types = require("./types.ts")

const res:types.ExpressResponse = .....;
```

I have failed to compile so far and wonder if this isn't implemented.

Thanks in advance.

**Comment by mhegazy** [comment]
This builds fine for me on 1.5-beta. see the example in http://www.typescriptlang.org/Playground#src=interface%20Foo%20%7B%20%7D%0D%0A%0D%0Aexport%20type%20ExpressResponse%20%3D%20Foo%3B

**Comment by daniel-shin1104** [comment]
Hi,

The part that fails to compile isn't the `export` part. It fails when I access type from api.ts.

```typescript
import types = require("./types.ts");

// This part fails. types variable simply doesn't have ExpressResponse as its property.
const res:types.ExpressResponse = ...;
```

I'm guessing it's syntactically valid to `export type` but internally, it doesn't actually export? 

Thanks for your help.

**Comment by tinganho** [comment]
@daniel-shin1104 I think what you are trying to do is?

```typescript
/// <reference path="typings/express/express.d.ts"/>
export {Response} from "express";
```
Though this doesn't stop you from adding the reference in the affected file in the first place or just add it in the root file(and no need to add references in all subsequent files).

**Comment by daniel-shin1104** [comment]
@tinganho Hello,

I'm pretty new to this language. Could you elaborate more on what 
```typescript
export {Response} from "express";
```
achieves?

I'm guessing it destructures and then export `Response`?

What I'm trying to achieve here is to have one consolidated `Types.ts` where I can reference often used external module types in more concise manner since some of types defined by external module definition files are somewhat convoluted.
 
Thanks for your help!

**Comment by tinganho** [comment]
>I'm guessing it destructures and then export Response?

@daniel-shin1104 yes, it re-exports the import.

Also the syntax you are using for import `import something = require('somehting')` is deprecated or not recommended in favor of ES6 modules.

**Comment by daniel-shin1104** [comment]
Thanks for your help.

So does that mean when we target es6, `import something = require("something");` will not compile? Is this what compiler args `--module commonjs` was for?

And now that we have this new module system (`import .. from`) implemented natively, we don't need to include that compiler arg anymore?

**Comment by daniel-shin1104** [comment]
I'm asking because I just switched to target es6 and compiler erred as following

`Error:TS1204: Cannot compile external modules into amd or commonjs when targeting es6 or higher.`

**Comment by tinganho** [comment]
>So does that mean when we target es6, import something = require("something"); will not compile? Is this what compiler args --module commonjs was for?

`--module commonjs` is for `< es6` since the ECMAscript spec doesn't cover module definitions. I guess the TS team decided not to implement other module compilation target other than `ES6` when you are targeting `ES6`. And I guess `import something = require("something");` was a temporary module solution for TS, because they couldn't wait for ES6 modules spec to be finished.

**Comment by daniel-shin1104** [comment]
Aha! Thanks for the clarification.

Also apparently, after some experimentations,
```typescript
import types = require("./types.ts");
// This still doesn't work.
const res:types.ExpressResponse = ....;

import {ExpressResponse} from "./types.ts";
// This works!!
const res:ExpressResponse = ....;
```

New module system seemed to fix this 'issue'. Thanks for the help!

**Comment by tinganho** [comment]
@daniel-shin1104 there is also namespace import in ES6:
```typescript
import * as types from "./types.ts";
const res:types.ExpressResponse = ....;
```

**Comment by JanEggers** [comment]
i dont know when it was introduced but this is possible now with ts 2.6.2:

export {
    List as ImmutableList,
    Map as ImmutableMap,
    fromJS
} from 'immutable';
