### ISSUE TITLE
Inconsistent behavior: should not be possible to type assert non-overlapping literal types

### ISSUE THREAD

**Issue by lazytype** [microsoft/TypeScript#37056]
**TypeScript Version:**  3.4+

**Search Terms:** "literal", "non-overlapping", "type assert"

**Code**

```ts
2 as const as 4;
```

**Expected behavior:**
Conversion of type '2' to type '"4"' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

**Actual behavior:**
No type error

**Playground Link:** https://www.typescriptlang.org/play/?ts=Nightly#code/MYewdgzgLgBFDuIBcMBMMC8MAsMCGEO+hqA3AFCiSzQCWANvQCqIrpa4ExXTFqlA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/11151
https://github.com/microsoft/TypeScript/issues/28955

**Comment by RyanCavanaugh** [comment]
See #37032

**Comment by RyanCavanaugh** [comment]
Everyone in the team room is curious what you were doing when this happened

**Comment by lazytype** [comment]
I think what differentiates this from #37032 is the explicit `as const` which one might expect to prevent the type from being widened.

**Comment by lazytype** [comment]
>Everyone in the team room is curious what you were doing when this happened

I chose a more illustrative example for the github issue, but I was originally looking to add "type-level" tests (not unlike dtslint), by having a line in our code such as:
```ts
true as DoesComponentHavePropsTypedAsAny<typeof MyComponent>;
```

but to my surprise, this "test" didn't actually work, even with `true as const` or `true as true`
