### ISSUE TITLE
Queue files that trigger failed compiling on save, and emit files related to them together with the last successful compiling. (Visual Studio)

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#3706]
This may help the compiled results be better synced with desired output.

BTW, can we expect compile on save feature in Visual Studio Code?

**Comment by mhegazy** [comment]
I am not sure i understand the proposal. can you elaborate..

**Comment by vilic** [comment]
For example, if we have two files `a.ts` and `b.ts`:

```typescript
// a.ts
test();
```

```typescript
// b.ts
function test(): void { }
```

Assuming they are been correctly compiled at the first place.

Then update `a.ts` and save:

```typescript
test('some arguments...');
```

We won't get any output if `noEmitOnError` is true.

Then update `b.ts` and save:

```typescript
function test(text: string): void { }
```

We'll get an updated `b.js` but leave `a.js` unsynced.

I hope we may queue files that failed compiling on save until a successful compiling and then update them all together.

**Comment by mhegazy** [comment]
This should be the behavior in VS2015. Compile-on-save will queue the generation of all files to ensure the program recovers of error states as you mentioned. which version of VS are you using?

**Comment by vilic** [comment]
Strange then, I am using VS 2015 RC.

**Comment by mhegazy** [comment]
My bad, should have been more specific. this should be fixed in the next public release of VS2015.

**Comment by vilic** [comment]
+1
