### ISSUE TITLE
Add container information to `CallHierarchyItem`

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37061]
From https://github.com/microsoft/vscode/issues/89616

## Search Terms
- call hierarchy
- tsserver

## Problem
Currently using the call hierarchy api, it can be difficult to browse through long list of callers and understand where those callers are:

![Screen Shot 2020-02-26 at 3 12 17 PM](https://user-images.githubusercontent.com/12821956/75396991-a5f1e700-58aa-11ea-9ffe-317fbbeb579a.png)

## Suggestion
Add optional information about the container on the `CallHierarchyItem` type. For example, the `NavTooItem` has:

```ts
containerName?: string;
containerKind?: ScriptElementKind;
```

We should consider something similar for `CallHierarchyItem`

/cc @jrieken

**Comment by DanielRosenwasser** [comment]
Given that you're in call hierarchy, won't you end up with the same icons anyway? What sorts of distinctions would be helpful here, and would they only apply to methods on classes?

**Comment by mjbvz** [comment]
Yes I don't think we would use the `containerKind` to display an icon. It may be helpful to understand the type of the callee for example

**Comment by mjbvz** [comment]
@jrieken Do you think we show the file name for every entry? 

![Screen Shot 2020-02-26 at 5 20 23 PM](https://user-images.githubusercontent.com/12821956/75403409-8499f680-58bc-11ea-9acb-5ab6ec52e9bb.png)

This is similar to workspace symbol search results

**Comment by jrieken** [comment]
In a very first version we showed the file name and that was disliked - often different (contained) types are in the same file. Also file paths are very long. 

That's why container name is wanted, which sometimes might be a file name but often is a class or namespace name. Having this will provide much more context and will make it easier to work with the call hierarchy (which by its nature can be confusing already)

**Comment by mjbvz** [comment]
Here's my proposal for the TS Server api:

```ts
interface CallHierarchyItem {
    /**
      * Name of symbol's container symbol (if any), such as the class name.
     */
    containerName?: string;
}
```

Not sure we have a use for `containerKind` so I'm leaving that out for now

**Comment by jrieken** [comment]
@mjbvz did we adopt this? I don't see a difference when selfhosting

**Comment by mjbvz** [comment]
@andrewbranch Looks like TS does not return a value for `containerName`. It's `undefined` in all the cases I've tested

**Comment by andrewbranch** [comment]
It turns out there’s a data conversion function on the server layer, which our normal test suite doesn’t touch, that returns an object with a specific set of keys, so the new property was left out of the serialization. PR incoming.
