### ISSUE TITLE
Infered type in generic that is boolean used in conditional type ends up in compiler error

### ISSUE THREAD

**Issue by atothek1** [microsoft/TypeScript#37069]
Dear TS Team,

using infer to extract the type of a generic which is passed to a conditional type ends up reporting error 
_Argument of type 'true' is not assignable to parameter of type 'never'.(2345)_ but only for boolean.

The returned type is a union `FactoryReturnAFn<false> | FactoryReturnAFn<true>` instead of
 `FactoryReturnAFn<boolean>;` 

passing then true or false as parameter leads to compile error.

**TypeScript Version:**  3.7.x, 3.8.x, nighly

**Search Terms:** infer, conditional, generic, boolean

**Code**

```ts
interface BaseType<T = undefined> {
    readonly data: T;
}

// infered types
type ExtractType<T> = T extends BaseType<infer A> ? A : undefined;

// define type definitions for function signatures that the factory can return
type FactoryReturnAFn<T> = (p: T) => BaseType<T>;
type FactoryReturnBFn<T> = (p: T) => BaseType<number>;

// define a conditional type
type ConditionalFactoryReturnFn<T> = T extends undefined
    ? FactoryReturnBFn<T>
    : FactoryReturnAFn<T>;

function factory<T extends BaseType<ExtractType<T>>>(): ConditionalFactoryReturnFn<ExtractType<T>> { 
    return ((p: ExtractType<T>): BaseType<ExtractType<T>> => {
        return { data: p };
    }) as unknown as ConditionalFactoryReturnFn<ExtractType<T>>;
}
// specify a concrete type derived from BaseType, with different generic types except boolean
// number, string, string[], { readonly id: string } etc.
type SpecificType = BaseType<{ readonly id: string }>;
const callbackWithTypes = factory<SpecificType>();
callbackWithTypes({  id: "string" });


// specify a concrete type derived from BaseType, with boolean
type SpecificTypeBoolean = BaseType<boolean>;
// the callback signature returned from the factory becomes a union type 
// and passing true | false tsc error
// Argument of type 'true' is not assignable to parameter of type 'never'.(2345)
const callbackWithBoolean = factory<SpecificTypeBoolean>();
callbackWithBoolean(true); // passing true or false is no possible

// expected signature
// callbackWithBoolean === FactoryReturnAFn<boolean>
// actual signature
// callbackWithBoolean ===  FactoryReturnAFn<false> | FactoryReturnAFn<true>
```

**Expected behavior:**
type defintion to be properly using boolean type `FactoryReturnAFn<boolean>`

**Actual behavior:**
type definition is union type `FactoryReturnAFn<false> | FactoryReturnAFn<true>` and blocks to call fun ction with true or false as parameter.

**Playground Link:** [Example](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=40&pc=77#code/JYOwLgpgTgZghgYwgAgEJwM4QCoE8AOEAPNsgLzICuIAJhDKBDQHzIDeAUMt8lBHDQD2IADa5kNOGDgAuZNgDcHAL4cOAenXJQMaE2RgCEDB0OFkAUQAeYKIjB5CJVhVIQbEWhjSYcRojrQyACCrAD8Ichy1HQMIExKGlqxjAZGEvSgwGDAwt4wglDIMNQIOcLIGMAA5iBSlHzeYAAWUgbNKPBlheIIcCC8EGANIKbpAGL2PQBKQyPB4yDO5MgAFPhy2ACU5KzoWI7E2MxKZiiT3VC4s8NQIKiLyxTrmztke76HRCCUALYARtATmpNBk4ig4MgEMIaNlcnURGlCGNzABhGFw4RwEQXMAzOZ3R7HFZuDxeKi0TLxGhcHgRXH4273InMWncOQMq43eYsxIlEBleHFKZXEjIdyQcn7PxOay2exfY7MZirLZydG0TEIznXAkgR5yuxlRXK9jINmDJlrF6WGxGhz+Y5qnwHfyGhWO03vdgWniWkZmyTSOT4ZDKJR+5Q7TAUgDWIEEAHcBjGNbDytqRbqmQa7R6nEqlKpQRhCAhgDBxJDoQK+JAkSg6FBgAA3fQwKCCX4umUQAA0yET2WaEgruj44GQ1U80GACAb3ncSHwYGQ-0EghE-FGoJ+AOgA4wtlA1UPx5A1QA2gBdAdsQYCYRibQ0ORH5sXsPisAIAB0KJQABlMsKznQ4VmlL57z4R9RHEYBX0qc9qjDYEayPKFsREf5EFjAB1YdDm8CgujxUVgIgcsGAQQ4VS2JQ+hEbDcIIloiNWe8XzkAAid8T24sN6LUJJKhAytkGrYQEDrFAzgyZs2xoYpO27SCjAHIcWjXDct36ADkAoqiwKMVAdO3CDPn8ddN23YFQRaFBGOYhBY0qGo6luFA6xGdsVPaToszXSiu2MCSKSFOSRP6JT8EwKpP1sSgUAAH2FEQsAMDB52gTsoBE4IoGqP5PFXQQYAbZAAHJEogSrtG8BNVzi9y4H+LcDEEZBYrsX4hiCMqKsq+I2ygSrf1WAAmABmAAWABWLYOHQ1cnJwlzWOaUybP6FZSJ6IhDNAmiTLM-o6IYrC1vw4ctt0kBVhqoSRPcMtICUqpanqPgRNWlibtOgYyCB5AdW5O4FiWay7tZUF7EobE3M+zyfsuv6Wlu8ygYoEGszBkAIaIeB0ogVhUtBvUCZq5ggA)

**Related Issues:** 
#33369

**Comment by RyanCavanaugh** [comment]
See e.g. #36683

**Comment by atothek1** [comment]
@RyanCavanaugh thanks for the answer after playing a bit around I have got it what to do, was for me not that obvious. I post the solution here.

```ts
interface BaseType<T = undefined> {
    readonly data: T;
}

// infered types
type ExtractType<T> = T extends BaseType<infer A> ? A : undefined;

// define type definitions for function signatures that the factory can return
type FactoryReturnAFn<T> = (p: T) => BaseType<T>;
type FactoryReturnBFn<T> = (p: T) => BaseType<number>;

// define a conditional type, FIX: [T]
type ConditionalFactoryReturnFn<T> = [T] extends undefined
    ? FactoryReturnBFn<T>
    : FactoryReturnAFn<T>;

function factory<T extends BaseType<ExtractType<T>>>(): ConditionalFactoryReturnFn<ExtractType<T>> { 
    return ((p: ExtractType<T>): BaseType<ExtractType<T>> => {
        return { data: p };
    }) as unknown as ConditionalFactoryReturnFn<ExtractType<T>>;
}

type SpecificType = BaseType<{ readonly id: string }>;
const callbackWithTypes = factory<SpecificType>();
callbackWithTypes({  id: "string" });

type SpecificTypeBoolean = BaseType<boolean>;
const callbackWithBoolean = factory<SpecificTypeBoolean>();
callbackWithBoolean(true); 

type MyUnion = "a" | true | 100 | string[];
type SpecificTypeUnion = BaseType<MyUnion>;
const callbackWithUnion = factory<SpecificTypeUnion>();
callbackWithUnion(true); 
callbackWithUnion("a"); 
callbackWithUnion(100); 
callbackWithUnion(["works"]); 
callbackWithUnion(false);  // works not as expected
```
