### ISSUE TITLE
Can you add this feature

### ISSUE THREAD

**Issue by mengxinssfd** [microsoft/TypeScript#37070]
can you add this feature:
```
function test(param: { key: string, value: any } |  { obj: object }) {
    console.log((<typeof param | 0>param).key);
    console.log((<typeof param | 1>param).obj);
}
````

|0 pointer to { key: string, value: any }  
|1 pointer to { obj: object }

not 

```
type a = { key: string, value: any };
type b = { obj: object };
function test(param: a | b) {
    console.log((<a>param).key);
    console.log((<b>param).obj);
}
```

**Comment by RyanCavanaugh** [comment]
This would be very confusing. If you wrote
```ts
type Thing = string | number;
function fn(x: boolean | Thing) {

}
```
It's not really apparent if `x | 1` is `string` or `string | number`, especially since the hover on `x` will say something like `number | string | boolean` as union ordering is not a defined concept.
