### ISSUE TITLE
ConstructorParameters<T> cannot get correct types of overloaded constructor

### ISSUE THREAD

**Issue by meteorlxy** [microsoft/TypeScript#37079]
**TypeScript Version:**  3.8.2

**Search Terms:** ConstructorParameters, overload

**Code**

```ts
interface Options {
	a: string;
	b: string;
}

class Foo {
	constructor(a: string, b: string);
	constructor(options: Options);
	constructor(options: Options | string, b?: string) {
		// implement
	}
}

// Expected: type Params = [Options] | [string, string]
// Actual: type Params = [Options]
type Params = ConstructorParameters<typeof Foo>;

const paramArray: Params = ['foo', 'bar']; // error
const paramObj: Params = [{ a: 'foo', b: 'bar' }]; // ok
```

**Expected behavior:**

```ts
type Params = [Options] | [string, string]
```

**Actual behavior:**

```ts
type Params = [Options]
```

**Playground Link:** [playground link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAsAFACQcAXMnmFKAOYDcZ5ARjXQyC2QL5kyCADZw8BAGLZsRNglzcArgjDYoACmq16TADTJOOnowCUrCgvz0Vazdkw58NDFkXn5im6vUaHb5zRHRWQAH2N9QwB+Ll1eUzkKcgB6ZORgAFt0EQgMiHA2QVIislTkAFEAD3QIVQgAExowAE8a5AAFOCg4DIIAXmQAbVcnPABdMKHuSOneMdK0gEFVJTgRJtaUTu7e5AHh4Px50ha27Z7+5ABhLyhbdXO8yCg8AB5TiGwYZGlsAD4LMIvMh0F0eosoN1mjRHpdBgByGAyeEGeHsLrwsbMZBlaBQdRA6wgsEZVDsABWMJJcMIyG0iORBiMaIxyH4WJxaWwAGsyEA)

**Related Issues:**

- #35657 - similar but closed by the author

**Comment by jcalz** [comment]
This is going to be a design limitation like #26591 and #24275.  

You can build something yourself that sort of works, as shown in [this SO answer](https://stackoverflow.com/a/59538756/2887218), at least up to some fixed number of overloads.  You'd get
```ts
type OrderedParams = OverloadedConstructorParameters<typeof Foo>; // [[string, string], [Options]]
type Params = OrderedParams[number]; // [string, string] | [Options]

const paramArray: Params = ['foo', 'bar']; // okay
const paramObj: Params = [{ a: 'foo', b: 'bar' }]; // okay
```

<details>
<summary>implementation details</summary>

```ts
type ConstructorOverloads<T> =
    T extends {
        new(...args: infer A1): infer R1; new(...args: infer A2): infer R2;
        new(...args: infer A3): infer R3; new(...args: infer A4): infer R4
    } ? [
        new (...args: A1) => R1, new (...args: A2) => R2,
        new (...args: A3) => R3, new (...args: A4) => R4
    ] : T extends {
        new(...args: infer A1): infer R1; new(...args: infer A2): infer R2;
        new(...args: infer A3): infer R3
    } ? [
        new (...args: A1) => R1, new (...args: A2) => R2,
        new (...args: A3) => R3
    ] : T extends {
        new(...args: infer A1): infer R1; new(...args: infer A2): infer R2
    } ? [
        new (...args: A1) => R1, new (...args: A2) => R2
    ] : T extends {
        new(...args: infer A1): infer R1
    } ? [
        new (...args: A1) => R1
    ] : any

type OverloadedConstructorParameters<T> =
    ConstructorOverloads<T> extends infer O ?
    { [K in keyof O]: ConstructorParameters<Extract<O[K], new (...args: any) => any>> } : never

type OverloadedInstanceType<T> =
    ConstructorOverloads<T> extends infer O ?
    { [K in keyof O]: InstanceType<Extract<O[K], new (...args: any) => any>> } : never
```
</details>


[Playground link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAsAFDIXJwBcyeYUoA5gNxmXIBGt9jIrZAL5kyCADZw8BAGLZsRdpQS5eAVwRhsUABQ06DZgBouPA-wCUbckpUN1mndkw58tDFhWXFFZfjsatbScPVzRnFWQAH30+JmNOAH5TWPMFaw4KAHpM5GAAW3QxCDyIcG9kYVJKkVIwAE90FFQoABNoCBaABTgoODyCAF40ADdoMWw4NpaAYVsoey1u3pLIKDwAHnrG7BhkWWwAPhZkbOQAbTPeIxjmAF1jM-cXPFvbsi2UJb7BtFb2rp63zOIFUeU40Fux1OlzMcRu-FuUXOTxUb1IolsyHQgLyAEEoL06rQvv1kEMzgByGByCnGCmcHoUyEnHLYADWcDqGL8WJxqE4ACtiTifmdCFRaFSafFJQyoBSKszTuzOewatkNZqtdqdbq9Zkah9kLM-PMAlBUKMoONJhsACoHMnlO3ICAAD0gIBaBBI6QyIAgAHdtAA6MM9Jh4WigGDQZC4gCM5mjIFjUGQACUE8cA8GwyGI1Hcqm47iAEzJ4tpzNlqwZSi50PhqCRlPV3EAZkrMbjGY7OaDTYLLaLPfTuIALN2S+mMxPyoJkAlzuUOLnkEPC7RE6kBo6s8Z15uR9uK2T92XDKuG0GN-mt-Gu+fMx3D7fj6341Pn3PyojaC67qet6aT1hQjb3ieValkmba9tmyAQc2n5jvGFZwbOtbXuBg6QShM6PtO1Z9guS4rn6a7vnhRY7j+CZvoGd7ITRZ57jWV4UTejEfjRT5sSRfr-sggEeqUIG+mBiG4cxGHxrB0GzghSHDvh7boQpNakcuZzYVJ3HUduSZ0QxTEqSxu4Xn+yAAa6olej6unKQ+qE7rJWZaeRklHgZckWZmCZWbQcAgFy6K1A0TRWjaUwmmo5okhAqz2o6AzlLF-gOJaYwTN66wOrZwEEKhqBLuU4pnAA0sWyBshAdQ7Ggty0OlZoOAlSXrAAoh6vQaOsqCVfcemmQ+wV1H5Y0HI6i60AGVqGhFIzZZMHQAJJ+MFSB2hFeUpWlcwLBaUU5clBViUVBElQkZXnFVoA1XVDWoE1yDrfQm0QNtjRdT1iBgP1g0mTxQUhRNIVTRU1lSVaQA)

**Comment by JasonHK** [comment]
> This is going to be a design limitation like #26591 and #24275.
> 
> You can build something yourself that sort of works, as shown in [this SO answer](https://stackoverflow.com/a/59538756/2887218), at least up to some fixed number of overloads. You'd get
> 
> ```ts
> type OrderedParams = OverloadedConstructorParameters<typeof Foo>; 
> // [[string, string], [Options]]
> type Params = OrderedParams[number]; 
> // [string, string] | [Options]
> 
> const paramArray: Params = ['foo', 'bar']; // okay
> const paramObj: Params = [{ a: 'foo', b: 'bar' }]; // okay
> ```
> 
> implementation details
> 
> [Playground link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAsAFDIXJwBcyeYUoA5gNxmXIBGt9jIrZAL5kyCADZw8BAGLZsRdpQS5eAVwRhsUABQ06DZgBouPA-wCUbckpUN1mndkw58tDFhWXFFZfjsatbScPVzRnFWQAH30+JmNOAH5TWPMFaw4KAHpM5GAAW3QxCDyIcG9kYVJKkVIwAE90FFQoABNoCBaABTgoODyCAF40ADdoMWw4NpaAYVsoey1u3pLIKDwAHnrG7BhkWWwAPhZkbOQAbTPeIxjmAF1jM-cXPFvbsi2UJb7BtFb2rp63zOIFUeU40Fux1OlzMcRu-FuUXOTxUb1IolsyHQgLyAEEoL06rQvv1kEMzgByGByCnGCmcHoUyEnHLYADWcDqGL8WJxqE4ACtiTifmdCFRaFSafFJQyoBSKszTuzOewatkNZqtdqdbq9Zkah9kLM-PMAlBUKMoONJhsACoHMnlO3ICAAD0gIBaBBI6QyIAgAHdtAA6MM9Jh4WigGDQZC4gCM5mjIFjUGQACUE8cA8GwyGI1Hcqm47iAEzJ4tpzNlqwZSi50PhqCRlPV3EAZkrMbjGY7OaDTYLLaLPfTuIALN2S+mMxPyoJkAlzuUOLnkEPC7RE6kBo6s8Z15uR9uK2T92XDKuG0GN-mt-Gu+fMx3D7fj6341Pn3PyojaC67qet6aT1hQjb3ieValkmba9tmyAQc2n5jvGFZwbOtbXuBg6QShM6PtO1Z9guS4rn6a7vnhRY7j+CZvoGd7ITRZ57jWV4UTejEfjRT5sSRfr-sggEeqUIG+mBiG4cxGHxrB0GzghSHDvh7boQpNakcuZzYVJ3HUduSZ0QxTEqSxu4Xn+yAAa6olej6unKQ+qE7rJWZaeRklHgZckWZmCZWbQcAgFy6K1A0TRWjaUwmmo5okhAqz2o6AzlLF-gOJaYwTN66wOrZwEEKhqBLuU4pnAA0sWyBshAdQ7Ggty0OlZoOAlSXrAAoh6vQaOsqCVfcemmQ+wV1H5Y0HI6i60AGVqGhFIzZZMHQAJJ+MFSB2hFeUpWlcwLBaUU5clBViUVBElQkZXnFVoA1XVDWoE1yDrfQm0QNtjRdT1iBgP1g0mTxQUhRNIVTRU1lSVaQA)

@jcalz That hack has a big flaw. If the overload function or constructor had one or more overload with no arguments, the infer will totally be screwed.

```typescript
declare function basicFunction(): void;
declare function basicFunction(value: number): void;

type FunctionOverloads<T> =
    T extends {
        (...args: infer A1): infer R1;
        (...args: infer A2): infer R2;
        (...args: infer A3): infer R3;
    } ? [
        (...args: A1) => R1,
        (...args: A2) => R2,
        (...args: A3) => R3,
    ] : T extends {
        (...args: infer A1): infer R1;
        (...args: infer A2): infer R2;
    } ? [
        (...args: A1) => R1,
        (...args: A2) => R2,
    ] : T extends {
        (...args: infer A1): infer R1;
    } ? [
        (...args: A1) => R1,
    ] : never;

type T = FunctionOverloads<typeof basicFunction>;
```

For some reason `T` is `[(...args: unknown[]) => unknown, () => void, (value: number) => void]` but not `[() => void, (value: number) => void]`.

**Comment by CMCDragonkai** [comment]
Is there a proper solution for this?
