### ISSUE TITLE
type K extends keyof T is not assignable to parameter of type keyof T when used as Map key for a function

### ISSUE THREAD

**Issue by IllusionElements** [microsoft/TypeScript#37081]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
class KeyMap<T> {
   keys = new  Map<(data: T[keyof T]) => any, any>()
   getKey<K extends keyof T>(key: (data: T[K]) => void)  {
      this.keys.has(key);
      this.keys.get(key);
      //...etc
  }

}
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
 no errors,   Types of parameters 'data' and 'data' should be compatible

**Actual behavior:**
Argument of type '(data: T[K]) => void' is not assignable to parameter of type '(data: T[keyof T]) => void'.
  Types of parameters 'data' and 'data' are incompatible.
    Type 'T[keyof T]' is not assignable to type 'T[K]'.
      Type 'keyof T' is not assignable to type 'K'.
        Type 'string | number | symbol' is not assignable to type 'K'.
          Type 'string' is not assignable to type 'K'.
            'string' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string'
**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=2&pc=25#code/MYGwhgzhAEDSCmBPAsmADgHgCoD5oG8BYAKGjLQCcBLANzABd5oBrJGAXmgDt4B3M1JgAUAEwZgAXNCwBtVogD2AM2kBdAJTR2eMF0QAaaLsQ4h6kmWgBzePQSIMsaPAAejLiJjzl06ADJoCHpqLitTeSlRcSlZWA0tPBoFKhFNAgtLMnoACyoIADp5AuzIIXl1AG4MzJy8wrZ8m3oypErqywB6Dvye22AMgF8SEgGgA
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is a correct error. `getKey` allows for a specialization of `K`, so you could legally write e.g.
```ts
type Data = {
  s: string;
  n: number;
}
const m = new KeyMap<Data>();
m.getKey<"s">(s => s.substr(0));
```
but `keys.has` is legally allowed to invoke its argument with `10` as a parameter because `10` is a valid `T[keyof T]`
