### ISSUE TITLE
Constrain object literal without losing the keys and values

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/TypeScript#3708]
Simple example:

```typescript
var out: {[name: string] : number} = { a: 5, b: 10 };
out.a // Is not valid
```

It would be nice if we could retain the keys and values, but still constrain the object literal. For backwards compatibility it probably can't be introduced in above syntax, but perhaps new syntax is required like `var out: Object<string, number>` or something.

Here is a longer use case, where it is important to retain the keys and values:

```typescript
interface Field<T> {
    clean(input: T): T
}

class CharField implements Field<string> {
    clean(input: string) {
        return "Yup";
    }
}

class NumberField implements Field<number> {
    clean(input: number) {
        return 123;
    }
}

class ObjectField<A, T extends { [name: string]: Field<any> }> implements Field<A> {
    fields : T
    constructor(fields : T) {
        this.fields = fields;
    }
    
    clean(input: A) {
        return <A>{}
    }
}

var person = new ObjectField({
    id: new NumberField(),
    name: new CharField()
});

person.fields.id // Is not valid at the moment
```

It does work if I remove the constrain, and modify it to this: 

```typescript

class ObjectField<A, T> implements Field<A> {
    fields : T
    constructor(fields : T) {
        this.fields = fields;
    }
    
    clean(input: A) {
        return <A>{}
    }
}


person.fields.id // Is valid and checks as NumberField!
```

But now I loose the constraint on the T, which in this case should say that right hand side of T is Field.

**As a bonus**, If one looks at the ObjectField really hard, it is difficult to use it without this: https://github.com/Microsoft/TypeScript/issues/3448 implemented also.

**Comment by DanielRosenwasser** [comment]
Why not add properties to the type of interest?

```TypeScript
var out: {[name: string] : number; a: number, b: number} = { a: 5, b: 10 };
out.a // is now valid
```

**Comment by Ciantic** [comment]
@DanielRosenwasser check out the full use case at the bottom:

```typescript
var person = new ObjectField({
    id: new NumberField(),
    name: new CharField()
});

person.fields.id // Is not valid at the moment
```

Where should I shovel those, write them all again in generic?

**Comment by JsonFreeman** [comment]
The issue is that we do not take the apparent type of the contextually type when we do inferential typing. Believe it or not, the following bug stems from the same issue:
```ts
function foo<T extends (p: string) => number>(x: T): T {
    return undefined;
}

foo(x => x.len); // No error
```

**Comment by Ciantic** [comment]
Was this reverted? I'm finding problems with this again in 1.8:

```
var out: {[name: string] : number} = { a: 5, b: 10 };
out.a // Is not valid
```

I find myself needing to constrain the right side of object literal without loosing the object literal itself.

**Comment by mhegazy** [comment]
@Ciantic, this example was never allowed by a TS version. I do not think it is related to this issue. please file a new ticket and provide more information.

**Comment by Ciantic** [comment]
@mhegazy this is my issue, the title and opening comment by me is still exactly the same problem I just described. Maybe someone fixed something else?

Anyhow, the title is clear, I want to constrain object literal without loosing the key accessor and it's precious values.

**Comment by mhegazy** [comment]
The issue that is being fixed is explained in https://github.com/Microsoft/TypeScript/issues/3708#issuecomment-118127368.

and the example in your comment in https://github.com/Microsoft/TypeScript/issues/3708#issuecomment-118113803 works as expected.

**Comment by Ciantic** [comment]
well, this is embarassing, I must be doing something wrong then... Doing same kind of API but for Immutable records (which uses `.set(fieldname, value)` when in fact it should also use `fieldname.set(value)`)
