### ISSUE TITLE
Optional binding

### ISSUE THREAD

**Issue by FilipeBeck** [microsoft/TypeScript#37097]
## Suggestion

Add the possibility to create variables within conditional expressions in `if` statement, like in [Swift language](https://medium.com/whoknows-swift/swift-what-is-the-optional-binding-7624c7f9098e). These variables, if not `undefined | null`, will be available in the scope of the `if` statement block.

## Examples

```typescript
if (const user = getUser(id) && user.age >= 18) {
  console.log(user.name)
}
const user = getUser(anotherID)
```
It is translated to something like the following in JS:
```typescript
const user_1 = getUser(id)
if (user_1 !== undefined && user_1 !== null && user.age >= 18) {
  console.log(user.name)
}
const user = getUser(anotherID)
```

**Comment by RyanCavanaugh** [comment]
This is a TC39 matter. See https://github.com/tc39/proposal-Declarations-in-Conditionals
