### ISSUE TITLE
Improve error when default-importing from a module that `export *`s from a module with a default export

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#37092]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

https://github.com/bluelovers/ws-react/blob/master/packages/react-use-localstorage/index.ts
```ts
export * from './core/v4';
//import createStorageHook from './core/v4';
//export default createStorageHook

//console.log(exports.default)
```

```ts
import createStorageHook from './src/core';
```

**Expected behavior:**

know "src/core" has default import

**Actual behavior:**

> Error:(2, 8) TS1192: Module '"src/core"' has no default export.

**Playground Link:** 

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/37090

**Comment by DanielRosenwasser** [comment]
`export \*` doesn't include default exports

**Comment by DanielRosenwasser** [comment]
That should be what this issue is - that the error message is bad.

**Comment by rpgeeganage** [comment]
Can I take this?

**Comment by DanielRosenwasser** [comment]
Sorry I missed that @rpgeeganage - but thanks for fixing this @a-tarasyuk!
