### ISSUE TITLE
Do not give me default inteli-sense suggestions when there are better matches

### ISSUE THREAD

**Issue by isidorn** [microsoft/TypeScript#3709]
Trigger inteli-sense inside an object creation literal.
I would expect to get the fields of the expected argument as only suggestions, not the global suggestions.

Picture attached
![screen shot 2015-06-30 at 09 43 35](https://cloud.githubusercontent.com/assets/1926584/8473766/3b1e9bfc-20ac-11e5-8f34-6d06837512c0.png)

**Comment by RyanCavanaugh** [comment]
Which editor is this? The TypeScript language service isn't reporting all those other things -- those look like snippets being provided by the editor's plugin.

**Comment by jrieken** [comment]
This looks like VS Code which adds template suggestions now and then. Maybe we should re-label this work item to either: (1) suggestions should include templates or (2) suggestion should hint what template scope is appropriate.

**Comment by mhegazy** [comment]
> (1) suggestions should include templates or

what locations are ok to include templates and what are not? looks like you are in a function body in the example above, `class`, `if` are still valid, `get` is not though..

> (2) suggestion should hint what template scope is appropriate.

I think this is a better approach. can you elaborate of some possible values? may be:
- global
- class body
- object literal
- function body
- switch body
- expression

**Comment by DanielRosenwasser** [comment]
Sublime would also greatly benefit from this. @zhengbli @billti

**Comment by DanielRosenwasser** [comment]
Should this be closed and marked as external?

**Comment by mhegazy** [comment]
@DanielRosenwasser we will have the same issue in VS with #312, all editors need some syntactic context if they want to filter templates.

**Comment by RyanCavanaugh** [comment]
AFAIK all editors do (or at least can) handle this in the preferred way now
