### ISSUE TITLE
Suggestion: optional interface

### ISSUE THREAD

**Issue by vvakame** [microsoft/TypeScript#371]
I think this is useful syntax :)

sample.

```
interface IFoo {
  foo: string; // not optional
}

class Bar implements IFoo? {
  // Bar does not have a foo property.
}

new Bar().foo;
```

How useful.

```
class Foo implements Lib.IListener? {
  constructor() { Lib.injectInto(this); }
}

module Lib {
  export interface IListener {
    on(data: any): void;
  }

  export function injectInto(target: any) {
    target.on = () => { /* do something... */ }; 
  }

  export function listen(receiver: IListener) {
    receiver.on("foobar");
  }
}

var obj = new Foo();
Lib.listen(obj);

Lib.listen({
  on: ()=> {} // on method required
});
```

In real world.

case 1.
https://github.com/borisyankov/DefinitelyTyped/blob/705102df2b652bdbadad23561675116a26e48760/space-pen/space-pen.d.ts#L52

case 2.
// Emissary#emitter
https://github.com/atom/emissary#emitter
// .d.ts
https://github.com/borisyankov/DefinitelyTyped/blob/b4aba562ef4192bc3f2e770ab2018f89e047836b/emissary/emissary.d.ts#L13
// usage in TypeScript (dirty hack!)
https://github.com/vvakame/language-review/blob/d23f8797bbb6e99d636399a14c7035c4809ab365/lib/util/emissary-helper.ts#L11

**Comment by basarat** [comment]
There is also : https://typescript.codeplex.com/workitem/1885 and https://typescript.codeplex.com/workitem/2475

**Comment by duanyao** [comment]
I love this suggestion because it is also useful for creating `UniversalElement` (#3304).

**Comment by benliddicott** [comment]
Is this need met by Intersection Types #3622 (committed)? See also Feature: type alternatives (to facilitate traits/mixins/type decorators) #727, aiming at the same target. 

Syntax: ` A & B ` is a type which implements both `A` and `B`. (In other words roughly equivalent to `interface A_n_B implements A, B{}`) It can be used wherever union types can be used. 

Synopsis:

    interface Emitter{ 
      on(event, fn);
      once(event, fn);
      off(event, fn);
      emit(event);
    }

    function MakeEmitter<T>(o T: ( T & Emitter) {
       require('my-emitter-library').mixin(o);
       return <T & Emitter>o;
    }

Or you could provide a .d.ts which typed the function `mixin` as returning the appropriate intersection type.

**Comment by unional** [comment]
How about this use case?
I can't find a way to do this:

```ts
interface Foo {
  foo: string;
}

interface Boo extends Foo? {
  boo: string;
}

let x: Boo = getBoo();
if (x.foo) {
  let y: Foo = x;
  ...
}
```

Essence: I want to put make `foo` and optional property in `Boo`, but still able to type `y` properly.

Here is an example that show current error when this is missing:
```ts
interface Config<S> {
  initialize<S>(...);
  reduce<S>(state: S, action: any): S;
  ...
}

class Foo<S> {
  configs: Config<S>[] = [];
  reducers: Config<S>[] = []; // <-- Could have been Reducer<S>[];
  addConfig(config: Config<S>) {
    this.configs.push(config);
    if (config.reduce) {
      this.reducers.push(config);
    }
  }

  do(state: S, action: any) {
    return this.reducers.reduce((s, reducer) => {
      return reducer.reduce(s, action); // <-- Object is possibly 'undefined'
    }, state);
  }
}
````

Currently a workaround is to duplicate the signature of `reduce()` in `interface Reducer<S> { }` and make it not optional.

**Comment by guillaume86** [comment]
It's also useful for `options` parameters or stricts `merge` typechecks.

A very common pattern is to define default options object with values for all required properties
and when the user provide his options, do something like `Object.assign({}, defaults, userOpts)`.

It would be nice to internally use `IOptions` with some required properties, and expose the API to the user with `IOptions?` (all properties optional).

This would also be useful in redux when Object.assign is used as an immutable `merge`.

**Comment by aluanhaddad** [comment]
This kind of type operator would be extremely useful in many cases as discussed above. One that occurs to me and I don't think it's been mentioned, is simply sending and receiving isomorphic data from a JSON service.

Generally when you do this you want interface with optional properties to compose requests an exact same interface except with required properties to type responses.

```ts
function getUser(id: number): Promise <User>;

function updateUser(user: User?): Promise <void>;
```
It would be especially powerful when mixed with subset types and intersection types.

I don't think it should be limited to interfaces I think it should apply to type aliases.

**Comment by RyanCavanaugh** [comment]
This is now
```ts
class Bar {
  // Bar does not have a foo property.
}
interface Bar extends Partial<IFoo> { }

new Bar().foo;
```
