### ISSUE TITLE
Proposal: 'sync' function keyword (Type guards preserved for inline callbacks)

### ISSUE THREAD

**Issue by benwiley4000** [microsoft/TypeScript#37107]
## Search Terms

`type guard`, `callback`

## Suggestion

Apologies if this has been discussed somewhere. I found a [closed issue](https://github.com/microsoft/TypeScript/issues/7719) about type guards not working inside callbacks, but the issue was closed because this is considered the correct behavior.

I agree, mostly. For example the type guard in the below example would clearly become invalid inside the async callback:

```ts
function run(stringOrNull: string | null) {
  if (stringOrNull === null) {
    stringOrNull = '/my/fetch/path';
  }
  fetch(stringOrNull).then(res => res.text()).then(() => {
    // not currently safe in TypeScript because it doesn't know if stringOrNull
    // has the string prototype (and in fact it doesn't, in our code)
    console.log('FETCHED', stringOrNull.trim());
  });
  stringOrNull = null;
}
```

In this modified case (removing the last line) we could actually statically guarantee that the `stringOrNull` variable would never become `null` after the callback is created, since there's no later code or other callback that modifies the value.

```ts
function run(stringOrNull: string | null) {
  if (stringOrNull === null) {
    stringOrNull = '/my/fetch/path';
  }
  fetch(stringOrNull).then(res => res.text()).then(() => {
    // not currently safe in TypeScript because it doesn't know if stringOrNull
    // has the string prototype (but we can prove it does)
    console.log('FETCHED', stringOrNull.trim());
  });
}
```

Ok, but let's say it's too complicated to implement this kind of check (maybe it is, I don't know). We can still safely make this type of guarantee if we're able to assert that the callback function will be fired *synchronously* by the destination function. For example:

```ts
function run(stringOrNull: string | null) {
  if (stringOrNull === null) {
    stringOrNull = 'my_var';
  }
  stringOrNull
    // already safe in TypeScript because we're on the same function scope
    // level and we know stringOrNull is now a string with the split() method
    .split('_')
    .forEach(part => {
      // not currently safe in TypeScript because it doesn't know if stringOrNull
      // has the string prototype (but we can prove it does since we know the
      // callback is fired synchronously)
      console.log(stringOrNull.replace(part, part.toUpperCase()));
    });
  // Ok so yes the variable gets set null later, but it shouldn't matter,
  // because we should be able to tell TypeScript that the prior callback was going
  // to be fired synchronously
  stringOrNull = null;
}
```

To address the last case, if unaided static analysis isn't feasible, I'd propose a `sync` keyword for callback functions to tell TypeScript that a function isn't allowed to be passed somewhere that will fire it asynchronously. The keyword will be required both for the function definition and as an argument modifier for any function that receives the callback, so it can be used as a safe guarantee that the callback isn't being stashed anywhere outside the inner scope of the receiving function (which will guarantee it can't be fired asynchronously.

Clearly, I think, a `sync` function cannot also be `async`. They're not opposites... really they're not quite talking about the same thing, since my definition of `sync` is not about the synchronicity of the function execution itself but about when the function to which it is passed decides to call it. But since we would lose that guarantee of type guard safety if the callback itself were `async`, since it necessarily *would not* execute synchronously, it's implied that the `sync` keyword also means that the callback itself executes synchronously.

## Use Cases

I think I explained that well enough above.

## Examples

This would be a valid version of the earlier example...

```ts
function run(stringOrNull: string | null) {
  if (stringOrNull === null) {
    stringOrNull = 'my_var';
  }
  stringOrNull
    .split('_')
    .forEach(sync (part) => {
      console.log(stringOrNull.replace(part, part.toUpperCase()));
    });
  stringOrNull = null;
}
```

...***Assuming*** that the forEach signature looks like this:
```ts
Array<T>.forEach(callbackFn: sync (value: T, index: number, array: T[]) => void, thisArg?: any): void
```

Here's another valid code example:

```ts
// VALID
function acceptCallback(callback: sync () => void): void {
  callback();
}
let x: number | string = 0;
x = 'yes';
acceptCallback(sync function() {
  console.log(x.toUpperCase());
});
```

But this slightly modified example is invalid, since the callback gets passed again into a function which does not accept a `sync function` argument:

```ts
// INVALID
function acceptCallback(callback: sync () => void): void {
  whoKnowsWhatThisDoes(callback);
}
function whoKnowsWhatThisDoes(callback: () => void): void {
  // anyone's guess, since we didn't use the `sync` keyword in our declaration
}
let x: number | string = 0;
x = 'yes';
acceptCallback(sync function() {
  console.log(x.toUpperCase());
});
```

The code below is also invalid, because it saves the callback outside the scope where we can guarantee synchronous usage:

```ts
// INVALID
let whoKnowsWhenYouWillUseThis;
function acceptCallback(callback: sync () => void): void {
  // now that you've saved the variable in an outside scope we can't
  // easily make static guarantees
  whoKnowsWhenYouWillUseThis = callback;
}
let x: number | string = 0;
x = 'yes';
acceptCallback(sync function() {
  console.log(x.toUpperCase());
});
```

Note that `sync` doesn't necessarily mean the function *will* be called, just that *if* it is called, it will be synchronously, so this is valid:

```ts
// VALID
function acceptCallback(callback: sync () => void): void {
  // don't do anything, it's fine
}
let x: number | string = 0;
x = 'yes';
acceptCallback(sync function() {
  console.log(x.toUpperCase());
});
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by benwiley4000** [comment]
I had a mistake in my example use case that didn't really make sense. Updated.

**Comment by AnyhowStep** [comment]
#9998

**Comment by AnyhowStep** [comment]
#9998 

Part of the reason TS has trouble with callbacks is because it doesn't know if a callback will be called once or many times, before the function returns or after the function returns, is sync or async, etc

**Comment by benwiley4000** [comment]
Makes sense, although I believe the type would still be knowable even with repeated calls if they're guaranteed to be made synchronously and the possible end type after the callback is called once is taken into account at the top of the callback (assuming it's the second or later call).

**Comment by RyanCavanaugh** [comment]
See #11498

**Comment by benwiley4000** [comment]
Ah indeed it's a duplicate. Not sure I'll make it through that whole thread this year though.. would be nice to have a summary if it's non-actionable. :)

**Comment by benwiley4000** [comment]
Also the statement given at some point in the thread that all functions would need to be annotated if sync is the rule... Either doesn't understand that sync means something different than "the opposite of async", or is using a different definition than I am. There can indeed be functions fired asynchronously but executed synchronously (as has been normal for years before async functions ever existed).

**Comment by AnyhowStep** [comment]
The issue I have with the word `immediate` and `sync` is that they don't describe this case well,

```ts
async function bar (callback : /*beforeReturnedPromiseResolves*/ () => void) {
  await new Promise(resolve => setTimeout(resolve, 1000));
  //Not immediate, not synchronous, but definitely before promise resolves
  callback();
}
async function foo (arg : string|undefined) {
  if (typeof arg == "string") {
    await bar(() => {
        //Should be OK, even though bar() is async
        //And callback is called asynchronously,
        //it is still invoked before bar()'s promise resolves
        const str : string = arg;
    });
    arg = undefined;
  }
}
```

**Comment by benwiley4000** [comment]
Yeah that's an interesting point. I hadn't considered this for the async/await context. Not really the terminology we're looking for but in C++ we could "statically" rather than "dynamically" allocate this variable since it only needs to live for this duration of the call stack and can be safely collected immediately afterward and you expect the callee not to store the reference anywhere. Maybe you could use "temporal" or "nonpersistent" or something to communicate that the function value won't be kept anywhere?
