### ISSUE TITLE
TS2339 Fails to trace Interface inheritance

### ISSUE THREAD

**Issue by theqwertman** [Microsoft/TypeScript#3710]
In some TypeScript code I'm trying to compile, `return { value: this.props.value || '' };`, however this results in the error `Property 'value' does not exist on type 'TodoTextInputProps'` even though

```ts
/// <reference path="react/react.d.ts" />
interface TodoTextInputProps extends React.HTMLAttributes {
  onSave: Function;
}
```

and in the React Module,

```ts
interface HTMLAttributes extends DOMAttributes {
//...
  value?: string;
//...
}
```

Because `React.HTMLAttributes` contains `value?: string`, and `TodoTextInputProps` extends that class, it seems that `TodoTextInputProps` should be able to contain the property, meaning that the error is a bug.

adding `value?;` to the Interface `TodoTextInputProps` eliminates the error, but this is unnecessarily redundant.

**Comment by RyanCavanaugh** [comment]
I can't reproduce this - maybe there's something else in your project that's causing an issue in the compiler. Can you post a zip file or something else self-contained?

**Comment by thewiseman** [comment]
I'm seeing this, too.

I have an Event 'e' being returned, but trying to access e.target.result fails with the error message described above. 'e.target' is an EventTarget, and the EventTarget interface is extended by several interfaces that have the property 'result' defined (such as IDBRequest), so it seems like it should be allowed by the compiler. I would expect interface fields be required by the compiler, but other properties (especially those defined on interfaces that extend the base) also be allowed.

**Comment by mhegazy** [comment]
@theqwertman  and @thewiseman is this still an issue?

**Comment by thewiseman** [comment]
I think my issue was from Visual Studio's TypeScript being older than I thought (and using its own version of some files). After I pulled down the latest and replaced VS's stored files everything was working as expected for me!
