### ISSUE TITLE
Invalid emit for class+namespace using module=commonJs in TS 3.9

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37118]
**TypeScript Version:** 3.9.0-dev.20200228

**Search Terms:**
- export
- namespace

**Code**
With `target = ES2017`, `module = commonJS`

```ts
export class Color {
    static readonly x = new Color();
}

export namespace Color {
    export const a = 1
}
```

**Expected behavior:**
In TS 3.8, this emits:

```js
Object.defineProperty(exports, "__esModule", { value: true });
class Color {
}
exports.Color = Color;
Color.x = new Color();
(function (Color) {
    Color.a = 1;
})(Color = exports.Color || (exports.Color = {}));
```

**Actual behavior:**
In TS 3.9, this emits:

```js
Object.defineProperty(exports, "__esModule", { value: true });
const Color = /** @class */ (() => {
    class Color {
    }
    Color.x = new Color();
    return Color;
})();
exports.Color = Color;
(function (Color) {
    Color.a = 1;
})(Color = exports.Color || (exports.Color = {}));
exports.Color = Color;
```

Which is not valid since it tries to reassign a constant value: `Color = exports.Color`

- [TS 3.8.2](https://www.typescriptlang.org/play/?module=1&ts=3.9.0-dev.20200227&ssl=7&ssc=21&pln=7&pc=26#code/PQKgtBldO38MU5EBQACE70GED2ADgJ4BOAlgOYAWALugBQDGAlOgLJmMl4DOeAZnXwkCeEgEMaZPADsAdOgCCAG2Xpy1Gj3UBTHjpIA3HQBM5GLOgAynHTP0n0AVxkmD6GlR3sAkgBVrW3sdBQBlHW8bRjt9ORoADzoyGQ8vdAJuACsdRjpuPDp+MXRlIP10ZKKSAFtJaXkLFCbmltakEGBUVB140RI6RmVxHm18ZWKAbwxsdB4aOsZdcRNZZSJ0ePQAXnQZHQB3XDxxknpmAG4ugF8unr66GXFqvQJxaKOT9CmZ9DuxAdkc3Q4m26AAjKgbkA)
- [TS 3.9](https://www.typescriptlang.org/play/?module=1&ssl=13&ssc=1&pln=5&pc=1#code/PQKgtBldO38MU5EBQACE70GED2ADgJ4BOAlgOYAWALugBQDGAlOgLJmMl4DOeAZnXwkCeEgEMaZPADsAdOgCCAG2Xpy1Gj3UBTHjpIA3HQBM5GLOgAynHTP0n0AVxkmD6GlR3sAkgBVrW3sdBQBlHW8bRjt9ORoADzoyGQ8vdAJuACsdRjpuPDp+MXRlIP10ZKKSAFtJaXkLFCbmltakEGBUVB140RI6RmVxHm18ZWKAbwxsdB4aOsZdcRNZZSJ0ePQAXnQZHQB3XDxxknpmAG5UAF8unr66GXFqvQJxaKOT9CmZ9DuxAdkc3Q4m26AAjNdUEA)

**Comment by mjbvz** [comment]
@rbuckton Possibly introduced by #36795

**Comment by weswigham** [comment]
Ack, this is probably my fault - as a follow up to the community PR, I updated it to use `const`, thinking it was more desirable - I didn't realize we relied on the ability to reassign the class declaration later on (even if we're reassigning it to itself in most cases). Regressed by #36907.
