### ISSUE TITLE
Partial object return has inconsistent intellisense

### ISSUE THREAD

**Issue by Validark** [microsoft/TypeScript#37117]
**TypeScript Version:**  3.8.2

**Search Terms:** 

**Code**

```ts
declare function partial<A extends object>(a: A): Partial<A>;
declare function object(): { x: number };

// try adding `.` before each semicolon
partial({ x: 2 });
partial(object());
```

![](https://user-images.githubusercontent.com/15217173/75591211-c5247c00-5a44-11ea-85ac-f2b9ed2d7aad.gif)

**Expected behavior:** Both should display `x?`

**Actual behavior:** Only one has `x?`, the other has `x`. 

**Note:** They both have the question mark on the right hand side.
**Also Note:** It never shows `x?` on the playground:

**Playground Link:**  https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200227#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxwCMArACgEoAueAb3gA9rVkBbQkGeAXwG4AoUJFgIU6bHngAHWNigQAPAEF4IehhCpgAZwIlwGAHyko1RVXgAFGVjlKD-PtJiyIpOo3gAmbuUfW5pERk5ORAA

**Related Issues:**  Couldn't find any

**Comment by Git-Lior** [comment]
This is a bug in a feature of vscode, not typescript (that's why it didn't reproduce in the playground).

I opened a pull-request at microsoft/vscode#94165 that fixes this problem
