### ISSUE TITLE
Throw compile error when using an enum imported from a declaration file

### ISSUE THREAD

**Issue by MatthiasKunnen** [microsoft/TypeScript#37120]
## Search Terms
Declaration files Definition files .d.ts enums

## Suggestion
Currently exporting an enum from a .d.ts file and importing/using this enum in a common TS file is allowed. Compilation succeeds but the compiled code will not run since the .d.ts file is not compiled thus the enum values are lost. I would like this to error on compilation. 

## Use Cases
I just ran into this problem and unfortunately the cause was masked by some other tools resulting in a lot of wasted time.

## Examples

```ts
// bar.d.ts
export enum Status {
   Open = 'Open',
}
```

```ts
// server.ts
import {Status} from './bar';
const open = Status.Open;
```

I would like to get something along these lines:
```
server.ts:3:13 - error TS????: Values from enum 'Status' imported from declaration file cannot be used.

3       const open = Status.Open;
                     ~~~~~~
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions **it would not break working code**
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This fails squarely under the "We believe what you told us" rule. If there isn't a module named `./bar` at runtime present with a `Status` value export, then it is incorrect to write a `.d.ts` file claiming there is.

**Comment by MatthiasKunnen** [comment]
Gotcha
