### ISSUE TITLE
"TS6133: xxx is declared but its value is never read." behaviour

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/TypeScript#37137]
**TypeScript Version:**  3.8.3

**Search Terms:**
"is declared but its value is never read."
**Code**

```ts
interface A {
  one: string;
  two: string;
}

class B {
  private _aa: A;
  constructor() {
    this._aa = { one: "one", two: "two" };
    on(Callback);

    function on(cb: ()=>void) {
      cb();
    }
    function Callback() {
      console.log(this._aa.one);
    }
  }
}

new B();
```

**Expected behavior:**
I would expect to not get the error below since the `_aa` variable is used implicitly by reading `_aa.one`
**Actual behavior:**
When compiling, I get the following error: `TS6133: '_aa' is declared but its value is never read.`

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/19700 which leads to https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#write-only-references-are-unused but this is not the same issue. The variable in question should be read via reading one of its subfields.

**Comment by jcalz** [comment]
Could you include a Playground link that reproduces this, as requested by the bug report template?  If I drop that code into the Playground like [this](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzkD2IEAXMgM5hSgDmA3LvmAO4FmXUj24C+uuCADZxy5ZACFMjZAAdqANziRkAfThwyqBnmQIiHAK4IwBKAAoCYABbQAwsNEBKKTqZXg5AHRq4yALyYhMRkAEREECEANMgsbMghsSHIPNr4+JY2UPYiXkRmIQDKBAC2ENa0Uci2cIKCAEaIANaO2tL4MAYgxsBEVTX1TWbO2K5peiDkBIIQnoIENGblXj6e4S1tydJ8ODxAA) I get errors but not the one you're referring to.

**Comment by WesleyYue** [comment]
I'm new to typescript/javascript so I actually need a bit of help putting this example together that is stripped from the actual code I'm working with. I stripped the example code furthermore and I get a [different error](https://www.typescriptlang.org/play/?target=1&ssl=16&ssc=24&pln=16&pc=27#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzkD2IEAXMgM5hSgDmA3LvmAO4FmXUj24C+uuCADZxy5ZACFMjZAAdqANziRkAfThwyqBnmQIiHAK4IwBKAAoAlFJ1MAFsHIA6NXGQBeTIWJkAREQg+ADTILGzIPqE+yDza+PhEZgDCcIKCAEaIANYW2tL4MAYgxsBEXmYIaWSWbgB88gTAACZW2DZxFZaxcXxtBUVgJSDIyakZCJmW1nHt+gSCEI6CBDRmYPZOLo7+OXnR0j09uMTMEp1AA) from my actual code. Could my issue be that the `this` keyword is not captured in the context of `Callback()`. If so, is there a way to make it so that it is captured? I realize that one solution could be to change `Callback()` to a member function of the class `B`, but just for educational purposes is it possible for `Callback()` to capture `this` from the constructor scope as is?

**Comment by WesleyYue** [comment]
Figured it out: the callbacks were indeed capturing an incorrect `this` context which I solved by using [arrow functions](https://basarat.gitbook.io/typescript/future-javascript/arrow-functions) type callbacks instead of what I had.
