### ISSUE TITLE
Decorating a declared class property should be an error

### ISSUE THREAD

**Issue by jamescdavis** [microsoft/TypeScript#37132]
**TypeScript Version:**  ^3.7

**Search Terms:**

declare decorator decorated class property

**Code**

```ts
function baz(_target: Object, _key: string) {};

class Foo {
  @baz declare bar: string;
}
```

**Expected behavior:**

Error due to decorating ambient context.

**Actual behavior:**

No error, decorated property is emitted (exact same output as [without declare](https://www.typescriptlang.org/play/?experimentalDecorators=true#code/FAMwrgdgxgLglgewgAgEYEMBeAKA+jdAJwHMBTGALmQHlUArU2AGmVwGtSBPKgZxkLgRiASmQBvAL4BuYMCgAbdDx7IAYggTjgyZAAEMmNEQCEvfoOIyJQA)).

**Playground Link:** 

https://www.typescriptlang.org/play/?experimentalDecorators=true&ssl=6&ssc=2&pln=2&pc=1#code/FAMwrgdgxgLglgewgAgEYEMBeAKA+jdAJwHMBTGALmQHlUArU2AGmVwGtSBPKgZxkLgRiASmQBvAL4BuYMCgAbdDx7IAYggTjgyZAAEMmZABNGiwqTRFe-QcRkSgA

**Related Issues:**

**Comment by whzx5byb** [comment]
Is this an error or a feature? I think it's useful since I'm using this pattern for dependency injection.

````
class A {
  @Inject('AnyNamespace.AnyInterface')
  declare private Foo: AnyNamespace.AnyInterface;

  method() {
    this.Foo.blabla... // <-- this.Foo is type-safe.
  }
}
````
DI module will inject to the property `Foo` from decorator, so the assignment could be omitted. However, since I enabled `strictPropertyInitialization: true`, property declaration without initialization will result in an error. So the `declare` keyword is needed.

If it turns to be an error, the injection to property have to be written as
````
  @Inject('AnyNamespace.AnyInterface')
  private Foo: AnyNamespace.AnyInterface = undefined as any;
````

**Comment by jamescdavis** [comment]
What about using definite?

```ts
  @Inject('AnyNamespace.AnyInterface')
  private Foo!: AnyNamespace.AnyInterface;
```

**Comment by whzx5byb** [comment]
> What about using definite?
> 
> ```ts
>   @Inject('AnyNamespace.AnyInterface')
>   private Foo!: AnyNamespace.AnyInterface;
> ```

Sorry for the late reply, but `declare foo: any` and `foo!: any` may have different behavior: The later will override its value when `useDefineForClassFields: true` is set.

```typescript
declare function SomeDecorator(...args: any): any;

class A {
    foo: string = 'foo';
}

class B extends A {
    @SomeDecorator
    declare foo: string;
}

class C extends A {
    @SomeDecorator
    foo!: string; // <- warning here.
    // Property 'foo' will overwrite the base property in 'A'. If this is intentional, add an initializer. 
    // Otherwise, add a 'declare' modifier or remove the redundant declaration.(2612)
}

```
[playground link](https://www.typescriptlang.org/play?useDefineForClassFields=true#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwGUcBbEAEXBxigyoAoA6J2AcwGcAueKVATwEouPXgG4AUGMhQ2beAEF4AbzHxVSHDi5sMMLKhbwAvPADkiDSfEBfCVJnwAQvBAAPDCFTBZC5WvgABIlIKMCoaKhU1UCk4dU14bV19a1toewBhZzcPL3klSNVAknJKaloYAriAQi0dPRYUoA)

Sometimes I don't need to overwrite the value, only want to add some behavior by using a decorator. 
There will be no way to do it if decorating a declared property becomes an error.

**Comment by rbuckton** [comment]
This is actually an intended behavior, and one of the reasons `declare` exists. If you are compiling targeting native fields, or with `--useDefineForClassFields`, redeclaring a `field` in a subclass just to decorate it would _actually overwrite the field_, as @whzx5byb mentions above. We allow you to decorate a `declare` field as that is the only way to decorate the field on a subclass without overwriting it.

**Comment by jamescdavis** [comment]
Thanks, @rbuckton! TBH I should have closed this months ago. Decorated declare properties is a pattern I now use regularly. I even wrote a blog post about it! 😆
