### ISSUE TITLE
isPropertyName should return true for PrivateIdentifiers

### ISSUE THREAD

**Issue by wessberg** [microsoft/TypeScript#37135]
**TypeScript Version:**  3.8.3

**Search Terms:** isPropertyName, PrivateIdentifier

**Code**

According to the internal type definitions, a  `PropertyName` is:
```ts
type PropertyName = Identifier | StringLiteral | NumericLiteral | ComputedPropertyName | PrivateIdentifier;
```

However, the TypeScript Compiler API helper `isPropertyName` returns false for `PrivateIdentifiers`, as can be reproduced with the following minimal repro:

```ts
import * as TS from "typescript";
const privateIdentifier = TS.createPrivateIdentifier("#foo");
TS.isPropertyName(privateIdentifier); // returns false
```

**Expected behavior:**
The Compiler API helper `isPropertyName` should return true for `PrivateIdentifiers`.

**Actual behavior:**
The Compiler API helper `isPropertyName` returns false for `PrivateIdentifiers`.

**Playground Link:**  (None)

**Related Issues:**  (None)

**Comment by tchetwin** [comment]
Is this a candidate for cherry-picking into the 3.8 release?
