### ISSUE TITLE
FileData interface missing iterable methods [entries, keys, values]

### ISSUE THREAD

**Issue by BayanBennett** [microsoft/TypeScript#37153]
**TypeScript Version:**  3.8.3

**Search Terms:** FileData entries keys values method

**Code**

`lib.dom.d.ts`

```diff
-interface FormData  {
+ interface FormData extends Iterable<readonly [string, FormDataEntryValue]> {
    append(name: string, value: string | Blob, fileName?: string): void;
+   entries(): Iterable<readonly [string, FormDataEntryValue]>;
    delete(name: string): void;
    get(name: string): FormDataEntryValue | null;
    getAll(name: string): FormDataEntryValue[];
    has(name: string): boolean;
+    keys(): Iterable<readonly [string]>;
    set(name: string, value: string | Blob, fileName?: string): void;
+    values(): Iterable<readonly [FormDataEntryValue]>;
    forEach(callbackfn: (value: FormDataEntryValue, key: string, parent: FormData) => void, thisArg?: any): void;
}
```

**Expected behavior:**
FormData interface should follow the spec https://xhr.spec.whatwg.org/#interface-formdata

> The value pairs to iterate over are the context object’s entry list’s entries with the key being the name and the value being the value.

**Actual behavior:**
I get the following warning: `TS2339: Property 'entries' does not exist on type 'FormData'.`

**Playground Link:** http://www.typescriptlang.org/play/#code/MYewdgzgLgBAZiATgWwCIEMrpgXhmAUwHcYAxJNTdACgEoBuAWACgXRJYCwpEBLAiLngUMWAHRce-CHSbMgA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/14537

In the above issue, browser support is cited as the reason for not including the `getAll` method. However, the `getAll` method is now in the interface and the browser support for `entries`, `keys`, and `values` is the same or better than other methods currently in the interface. (https://developer.mozilla.org/en-US/docs/Web/API/FormData)

If approved, I'm happy to make a PR [‌](https://bayanbennett.com)

**Comment by IllusionMH** [comment]
Duplicate of #36113 (or at least related to it)

These methods already in [`dom.iterable.generated.d.ts`](https://github.com/microsoft/TypeScript/blob/c7f27c331682b23f90a455b0d9aaa52306cad985/src/lib/dom.iterable.generated.d.ts#L64-L78) just make sure that you have `"dom.iterable"` in `lib` compiler option.

**Comment by BayanBennett** [comment]
That worked. Closing issue.

`tsconfig.json`
```json
{
  "compilerOptions": {
    //...
    "lib": ["dom.iterable"]
  }
}

```
