### ISSUE TITLE
Down-level lexical 'arguments' binding for arrow functions

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#3716]
* *Related compatibility test: [arrow functions - lexical "arguments" binding](http://kangax.github.io/compat-table/es6/#arrow_functions_lexical_arguments_binding)*

Currently we make this an error when compiling to ES5, however we recently added lexical argument capturing for ES6 async functions in #3078, so we may want to revisit this.

**Comment by RyanCavanaugh** [comment]
We decided to not bother with this unless someone shows up and asks for it.
