### ISSUE TITLE
No error with `=== undefined` (or null) against a type that doesn't contain undefined (2367)

### ISSUE THREAD

**Issue by Retsam** [microsoft/TypeScript#37160]
**TypeScript Version:**  Version 3.9.0-dev.20200229

**Search Terms:**  2367, no overlap, 

**Code**

```ts
if("str" === undefined) { /* ... */ }
```

**Expected behavior:**
Expected error (with `strictNullChecks` on): `This condition will always return 'false' since the types 'string' and 'undefined' have no overlap`

**Actual behavior:**
No error

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=1&pc=40#code/JYMwBAFARALgpgZxlMBedYCuA7AJnEYbOXASjAG8wB6AKjADomxbqwBfIA

**Related Issues:** 
#32627
[typescript-eslint#1591](https://github.com/typescript-eslint/typescript-eslint/issues/1591)

**Comment by Retsam** [comment]
@RyanCavanaugh Marked as duplicate, can you link the issue that this duplicates?  I couldn't find anything more similar than #32627.  Thanks!

**Comment by RyanCavanaugh** [comment]
#30519, #11920

**Comment by Retsam** [comment]
Thanks, sorry I missed those.
