### ISSUE TITLE
outDir not created when single file project only exports a method from a dependent project.

### ISSUE THREAD

**Issue by BrianMar** [microsoft/TypeScript#37167]
**TypeScript Version:**  3.7.2

**Search Terms:**
typescript not emitting output
outDir not created
**Code**

I have a project which is simply exporting a method from a dependent project:

SpecialExport.TS file:
```ts
import { SomeClass } from 'SomeClassInExternalLibrary';
export const specialExport = SomeClass.getFactory();
```

tsconfig:
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "./lib",
    "incremental": true,
    "target": "es2015",
    "module": "commonjs",
    "allowSyntheticDefaultImports": true,
    "composite": true,
    "rootDir": "src"
  },
  "exclude": [
    "node_modules",
    "dist",
    "lib"
  ]
}
```
where the file were are extending is:
```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "esnext",
    "jsx": "react",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "noEmitOnError": true,
    "moduleResolution": "node",
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true
  }
}
```

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
I expected there to be an output "lib" folder with SpecialExport.js written, along with d.ts files.

**Actual behavior:**
No lib folder is created, and the file is not written.
If I add the following line:
export const foo=3;
Then I get the output I expect and "lib" is created.

If I then remove the "foo" line, the file will be written in the existing lib folder, with all reference to foo gone. This is the output I expect.

If I then "rm -rf lib" and run tsc.js again, no lib is created and the file is note written.

It appears that just the export of the dependent function somehow doesn't trigger the need to create the output folder, but it works fine if the output folder already exsits.

**Playground Link:** 

Does not repro in the playground since it isn't writing any files.

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Please make a sample repo or zip file. We'd need to see the definition of the other library as well as the `../../tsconfig.json` to be able to investigate.

**Comment by BrianMar** [comment]
This was entirely user error on my part. There was no issue. I did learn during this (Thanks Ryan & Sheetal) that "composite" implies "incremental". The actual issue was an error in my package.json file.
