### ISSUE TITLE
Rename does not update aliased imports

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37188]
From https://github.com/microsoft/vscode/issues/91940

**TypeScript Version:**  3.9.0-dev.20200303

**Search Terms:**

**Code**

`foo.ts`
```ts
export interface IFoo { 
    bla(): void;
}
```

`bar.ts`
```ts
import { IFoo as SomeAlias } from './index'

export class K implements SomeAlias {
    bla(): void { }
}
```

1. In `foo.ts`, rename `IFoo` to IFoo

**Expected behavior:**
Reference to `IFoo` in `bar.ts` is updated

**Actual behavior:**
The reference is not updated

**Comment by martinjaime** [comment]
hello typescript team! i'd love to help with this. could you point me in the right direction? this would be my first open source contribution.

**Comment by RyanCavanaugh** [comment]
@martinjaime this is probably a bit of a tricky one that might not be a good first issue. I'd recommend choosing something [from this list](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) if you'd like to make a contribution. Thanks!
