### ISSUE TITLE
Readonly<T> miss all internal symbol keys

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#37182]
**TypeScript Version:**  3.8.3

**Search Terms:** readonly internal symbol

**Code**

```ts
const sym = Symbol();
const x :{
	readonly str :any
	readonly [sym] :any
	readonly [Symbol.iterator] :any
	readonly [Symbol.toStringTag] :any
} = {} as Readonly<{
	str :any
	[sym] :any
	[Symbol.iterator] :any
	[Symbol.toStringTag] :any
}>;
```

**Expected behavior:**

no error

**Actual behavior:**

`TS2739` (missing properties `Symbol.iterator` and `Symbol.toStringTag`)

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@ahejlsberg wasn't this the intent of https://github.com/microsoft/TypeScript/pull/23592 ?

**Comment by ahejlsberg** [comment]
> wasn't this scenario the use case for #23592 ?

Yes, except we have always excluded "well known symbols" from `keyof`. The fix really is to get rid of the well known symbol concept and just treat them all as unique symbols.

**Comment by ahejlsberg** [comment]
See #24738.

**Comment by PSeitz** [comment]
This blocks converting Readonly Sets to Arrays

```
const mySet: Readonly<Set<string>> = new Set();
const myArr = [...mySet]; // Type 'Readonly<Set<string>>' must have a '[Symbol.iterator]()' method that returns an iterator.
```
