### ISSUE TITLE
lib.es2015.core.d.ts: Some parameters of functions of Number is not completely right

### ISSUE THREAD

**Issue by Ezio1212** [microsoft/TypeScript#37190]
For example, We can use the following in es2015:

`Number.isInteger(undefined); // false`

but in lib.es2015.core.d.ts:
`interface NumberConstructor {`
`// some defination codes....`
` isInteger(number: number): boolean;`
`// some other def codes...`
`}`

thx

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/34931

**Comment by Ezio1212** [comment]
thanks, i will colse it.
