### ISSUE TITLE
(arr: any[]) => arr.join() should be a type error

### ISSUE THREAD

**Issue by davidgilbertson** [microsoft/TypeScript#37199]
## Search Terms

symbol, array, join, tostring, TypeError
## Suggestion

Since `any` includes the `symbol` type, and [symbols can't be implicitly converted to strings](https://www.ecma-international.org/ecma-262/#sec-tostring), and we know that [`arr.join()` will try to convert each item to a string](https://www.ecma-international.org/ecma-262/#sec-array.prototype.join), then we know that calling `arr.join()` on `arr: any[]` is not type safe.

Specifically, I suggest that this should result in a type error:
```ts
const sym = Symbol('My symbol');
const arr: any[] = [1, sym, 'cats'];
arr.join(','); // runtime TypeError, but not a TypeScript error
```

[Playground Link](https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBBCeBbGBeGBlJAjEAbAFAOQCy8c2ehAlANwCwAUKJLAIYBO7AXDK2PAG0AuqhgCAjABpyiaYWCsoEQkPoMO7AHQArEAEswRSdRowA9GZjsArmCh7EAUxgAVeAAdHAUU4h20rGtYMBA2Vw9HdGB2PXdYR192RkZmCDxHTVwQAHN8AANSGRxcGD0IGAASAG8ERABfPNpzSxcACzLS8tZwzyiYuJgE9j9pAHd24FbOmFBOR2AoIA)

Notably,
```js
console.log(`My symbol is ${sym}`);
```
_is_ an error, and TypeScript helpfully tells me about implicit conversion of symbols to strings.

## Use Cases

I have a library ([react-recollect](https://github.com/davidgilbertson/react-recollect)) that allows users to put any sort of data in a store. Internally, I treat this data as `any`, and at one point I join values in an array.

The current shortcoming is that this allowed a type-related bug through because I didn't know about symbols throwing errors when implicitly converted to strings.

## Examples

As above.
## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) _(maybe?)_

## Reasons not to
99% of arrays probably don't contain symbols, so maybe this is a pain for a _lot_ of developers. Maybe it fits [non-goal 3](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals): 

>Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

If so, feel free to close.

**Comment by RyanCavanaugh** [comment]
We'd need negated types to properly flag this as an error, since `join` is sensible on anything that *isn't* `symbol`
