### ISSUE TITLE
Function called with string literal mismatch not recognized with object shorthand syntax

### ISSUE THREAD

**Issue by nopelluhh** [microsoft/TypeScript#37201]
**TypeScript Version:**  3.8.3 - 3.9.0-dev.20200229

**Search Terms:**
function expression, object shorthand, literal

**Code**

```ts
import React from 'react';

type Callable = (x: 'foo' | 'bar') => void;

const shorthandFn = (
    { setSomething }: { setSomething(x: 'foo' | 'bar'): void; }
) => undefined;

const aliasFn = (
    { setSomething }: { setSomething: Callable }
) => undefined;

// should error
shorthandFn({ setSomething: (x: 'foo') => null })
// does error
aliasFn({ setSomething: (x: 'foo') => null})

const ShorthandComponent: React.FC<{
    setSomething(name: 'foo' | 'bar'): void;
}> = ({ setSomething }) => <button onClick={() => setSomething('bar')} />

const AliasComponent: React.FC<{
    setSomething: Callable;
}> = ({ setSomething }) => <button onClick={() => setSomething('bar')} />

// should error
const shorthandElement = <ShorthandComponent setSomething={(x: 'foo') => null} />
// does error
const aliasElement = <AliasComponent setSomething={(x: 'foo') => null} />
```

**Expected behavior:**
Using a function shorthand should behave the same way as a type alias, recognizing that the type of `x` is incorrect

**Actual behavior:**
An error recognizing the mismatch is only produced when using a type alias:
```
Type '(x: "foo") => null' is not assignable to type 'Callable'.
  Types of parameters 'x' and 'name' are incompatible.
    Type '"foo" | "bar"' is not assignable to type '"foo"'.
      Type '"bar"' is not assignable to type '"foo"'.(2322)
```

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?jsx=2&ts=3.9.0-dev.20200229&ssl=29&ssc=74&pln=1&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4BhFAG1ZQCNXGBeOABQAPAFwFMECPjgAfApxRR8ASji8AfHABuEYABMK1SmggA7AM7xzAC2gxrKU3oBiptYKpwvcAN5xzSDAAyriB1sCmAOZwAL5ifgHBofYRkcJi+BJSsvKKKmI6+qSxVKoacACuTkiYEUgGVFQmFvBswCjmru4Cnt4JgSEgYamx8f4DyeFRYizsXDwllGWaVXo1dQ1GAPRb-rYVrHpwSFA4UFQ2dg5OrgL9SUMp04Ki4pIqapqmB6yxylQ7OB6CBIczHU7QKhtDq3e6DYbPdJvKTLODfdgxf5GZqWOBBWywa56Ji4SCmJCmGBiZDoGAAOmcTAAPD5el5EvCnmlTCghhkstI5PgFEplAVdJsYpp+Hdxg8EdFMZ84EzOBUYDAzHAzExWMA0ABrXg+ASojmTVICYV5ZQxOBbdSNYxmXEAQT1HRJ4DMFKpiGI9MZLLZcs5U0iMzYHG4SEMUu6cItUT+ytV6s1bh1esNxtNyvNj3DVpFKjtDqdgMuByOJzOTRdVgJ9kcegAojwhpT3Ez8VcW16yb7Q0nIrnXpl3qj0awy47KIDgaDwXXnS04NDzO2kJ34Pwme72uYBz6uwWFWP+ZPldPZ06qEA

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/34849 (only issue I found referencing a difference between shorthand and function expression syntax)

**Comment by dragomirtitian** [comment]
Duplicate of #36752, probably others. Method syntax behaves differently.

> This is a side effect of the way `strictFunctionTypes` work differently for signatures originating in methods vs other signatures. Methods behave bi-variantly in spite of `strictFunctionTypes`. From PR #18654 :
> 
> > Methods are excluded specifically to ensure generic classes and interfaces (such as Array) continue to mostly relate covariantly. The impact of strictly checking methods would be a much bigger breaking change as a large number of generic types would become invariant (even so, we may continue to explore this stricter mode).

**Comment by nopelluhh** [comment]
Ah, thanks for the info. Definitely...weird.
