### ISSUE TITLE
Provide a way to map an arbitrary amount of overloads to a different type

### ISSUE THREAD

**Issue by ashmind** [microsoft/TypeScript#37204]
## Search Terms

overload mapping parameters

## Suggestion

Without suggesting any specific syntax, my goal is to be able to map a set of function overloads to other types (e.g. object). Currently it is a bit hard as `Parameters<>`/`ReturnType<>` helpers only picks the last overload (by design).

## Use Cases

Consider this interface
```typescript
interface Dispatcher {
     dispatch(type: 'a', data: A): void;
     dispatch(type: 'b', data: B): void;
     dispatch(type: 'c', data: C): void;
}
```

There are often cases where I want to provide multiple dispatches or handlers using a type like this:
```typescript
{
    a: (data: A) => void;
    b: (data: B) => void;
    c: (data: C) => void;
}
```
However building this validation based on original overloads is cumbersome.
The best approach I found looks somewhat like this:
```typescript
type OverloadParametersToUnion<F> =
    F extends { (...a: infer A): void; (...b: infer B): void; (...c: infer C): void } ? A|B|C :
    F extends { (...a: infer A): void; (...b: infer B): void } ? A|B :
    F extends { (...a: infer A): void } ? A :
    never;

type BuildMap<T extends [string, any]> = { [key in T[0]]: (data: Extract<T, [key, any]>[1]) => void };

type DispatcherMap = BuildMap<OverloadParametersToUnion<Dispatcher['dispatch']>>;
```

This only handles 3 overloads. I created one for 26 overloads, but it started slowing down VS Code.

I only started using TypeScript recently, but I have encountered similar examples two times: creating an object map helper for CodeMirror's `on` event subscription method, creating an handler map for an event dispatcher implementation. So it does seem like a common case at the moment.

## Examples

I am not set on any specific syntax as I don't feel I know TypeScript well enough.
Any syntax or helper type would be fine as long as it can handle an arbitrary number of overloads.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
The usual way to do this is:

```ts
type A = { a: string };
type B = { b: number };
type C = { c: number };

interface DispatcherParamMap {
  'a': A;
  'b': B;
  'c': C;
}

interface Dispatcher {
  dispatch<T extends keyof DispatcherParamMap>(type: T, data: DispatcherParamMap[T]): void;
}
```

This is very performant from a type checker perspective and handles higher-order invocations quite well. You can also augment `DispatcherParamMap` from multiple locations (this is typical in redux-like scenarios).

**Comment by ashmind** [comment]
@RyanCavanaugh What should I change so that it can be seen as a proposal and not question -- do I need to include a proposed syntax? To me it's not a question as I already know it's not supported and I would like it to be supported, but I can try to think about some syntax approaches.
