### ISSUE TITLE
function with properties type interface is not type safe

### ISSUE THREAD

**Issue by regevbr** [microsoft/TypeScript#37207]
**TypeScript Version:**  3.9.0-dev.20200303

**Search Terms:**

type order, composite

**Code**

```typescript
interface ICompositeFn {
  (a: string): string;
  obj: {
    num: number;
  };
}

const run = (fn: ICompositeFn) => {
  console.log(fn.obj.num);
}

const compositeFn = (a: string): string => {
  return a;
};

run(compositeFn);

compositeFn.obj = {
  num: 5
};
```

**Expected behavior:**

It is awesome that typescript can automatically infer that the type of `compositeFn` has the `obj` property, but that inference should be applied in order, so using the `compositeFn` before the actual `obj` property was set will not be possible.

Compile time type error, stating that the passed parameter to the `run` methods is not matching the expected type.

**Actual behavior:**

There is no type error, thus can lead to runtime error that otherwise could have been prevented.

```
VM34:3 Uncaught TypeError: Cannot read property 'num' of undefined
    at run (eval at <anonymous> (main-3.js:1239), <anonymous>:3:24)
    at eval (eval at <anonymous> (main-3.js:1239), <anonymous>:8:1)
    at main-3.js:1239
```

[Playground Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200303&ssl=1&ssc=1&pln=22&pc=1#)

**Comment by regevbr** [comment]
@RyanCavanaugh this will not be fixed?

**Comment by RyanCavanaugh** [comment]
@regevbr oops, I see I forgot to comment. No, this isn't likely to be addressed with new functionality -- ordering effects of all sorts are very difficult to model correctly given how JS works.
