### ISSUE TITLE
Compile classes fields marked as "private" to ECMAScript private fields (`#xxx`)

### ISSUE THREAD

**Issue by TokugawaTakesi** [microsoft/TypeScript#37206]
## Search Terms

TypeScript pivate fields, ECMAScript private fields

## Suggestion

Compile classes fields marked as "private" to ECMAScript private fields (`#xxx`).

In TypeScript 3.8, ECMAScript private fields has been added, but TypeScript class fields marked as "private" are sill being compiled to default public ECMAScript-fields.

## Problem 1: The developers forced to rewrite their code to new syntax

Because ECMAScript private fields are more safe, developer forced to rewrite "private"-marked class fields to ECMAScript class fields.

## Problem 2: Syntax unity loss

```typescript
class Application {
  
  public examplePublicField1: string;
  public examplePublicField2: string;

  #examplePrivateField: string; // standing out and annoying
}
```

Well, even if I stop to use `public` keyword, still `protected` keyword exists:

```typescript
class Application {

  examplePublicField: string;
  
  protected exampleProtectedClassField: string; // standing out and annoying

  #examplePrivateField: string;
}
```

### Solution alternative 1

Compile `private examplePrivateClassField` to `#examplePrivateClassField` when TypeScript compiler's `target` option is `ES2020`. Otherwise compile `private examplePrivateClassField` to default public `examplePrivateClassField`.

### Solution Alternative 2

Add compiler option like `unifiedPrivate` which provides above behavior when turned on.

## Examples

```
class Application {
    private privateClassField: stirng;
}
```

should be compiled to:

```
class Application {
   constructor(example) {
        this.#example = example;
    }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment]
Open discussion in https://github.com/microsoft/TypeScript/issues/31670, including rationale for why this would not be done

**Comment by RyanCavanaugh** [comment]
Per above 👆 we won't be doing this

**Comment by TokugawaTakesi** [comment]
You have raised the holy war between `private` keyword followers and and ECMAScript private field followers :simple_smile:. The mental energy consumption for the team work will increase. :weary:
