### ISSUE TITLE
TS2339: Property 'all' does not exist on type 'CSSStyleDeclaration'.

### ISSUE THREAD

**Issue by BrandonMA** [microsoft/TypeScript#37215]
**Typescript version**: 3.8.3

**Code**
```
const element = document.createElement("div");
element.style.all = "initial"; // error here, property doesn't exist
```

**Expected behavior:**
Since the property all actually exist on style, should be an option.

**Actual behavior:**
TS compile error: TS2339: Property 'all' does not exist on type 'CSSStyleDeclaration'.
It works as expected by using `// @ts-ignore` before the line.

**References:**
https://developer.mozilla.org/es/docs/Web/CSS/all

**Comment by swapna06** [comment]
Im seeing the same behaviour, In my case I use location.state to save if i have to autoScroll
TS2339: Property 'autoScroll' does not exist on type '{}'.
Error when trying to access location.state properties like, this.props.location.state.autoScroll
Im trying to upgrade from 3.5.2 to 3.8.3

**Comment by hikarinotomadoi** [comment]
I've created a PR at TSJS-lib-generator that will fix this issue.
https://github.com/microsoft/TSJS-lib-generator/pull/835
