### ISSUE TITLE
Typescript need a standalone VM or native compiler. (like JDK or Clang)

### ISSUE THREAD

**Issue by netroby** [microsoft/TypeScript#37226]
I am learn and use type script for years.  thanks for your great works.
I hope typescript have it's own VM or native compiler. 

From Typescript => VM running directly.
From Typescript => .exe or elf binaray executable 

Gave us the power of TypeScript.  no other depends on. 

Do not need nodejs. do not need gcc, clang, or what ever.

It can standalone, like CSharp. Donet .

The similar project  `deno` can make TypeScript serve a web app server. looks very impressive.

Hope TypeScript has the same ability.

Not just a paper language. (Depends on other tools, language,  vms)

**Comment by orta** [comment]
Thanks for the issue, but this is pretty explicitly [not a goal of TypeScript](https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals).

If it's something you're interested in, check out [Static TypeScript](https://www.microsoft.com/en-us/research/publication/static-typescript/) which does this.
