### ISSUE TITLE
Add {root} helper for tsconfig.json (for avoiding multiple ../../)

### ISSUE THREAD

**Issue by Yegorich555** [microsoft/TypeScript#37227]
## Search Terms

helper {root} {workspace} in tsconfig.json

## Suggestion

I have the following project structure
```
tsconfig.json
>folder
   >folder
     >folder
       tsconfig.json => 
         {
             "extends": "../../../tsconfig.json"
              ... 
         }
```

I didn't find any path-helper that can replace "../../../" to **{root}** where the root is the current workspace folder

## Use Cases

Avoiding using "../../../" because of this is a headache for refactoring

## Examples

```js
// folder/folder/folder/tsconfig.json
{
  "extends": "{rootOrWorkspaceFolder}/tsconfig.json"
   "paths": {
      "root/*": ["{rootOrWorkspaceFolder}/*"]
    }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
What is the "current workspace folder"? How is that determined?

**Comment by Yegorich555** [comment]
- ```process.cwd()``` in NodeJs... 
- package.json can point on the workspace folder. It always in the root

A lot of packages use similar logic for defining {root} (jest for example)

**Comment by karlhorky** [comment]
I guess this is pretty similar to my new issue https://github.com/microsoft/TypeScript/issues/51213, wonder if I should close 51213...
