### ISSUE TITLE
Type inference with map & (otherMap | otherMap2) fails

### ISSUE THREAD

**Issue by DragonRaider5** [microsoft/TypeScript#37231]
**TypeScript Version:**  Nightly

**Search Terms:** None (I couldn't come up with any, please excuse me)

**Code**

```ts
type Entity = {
  someDate: Date | null;
} & ({ id: string; } | { id: number; })

type RowRendererMeta<TInput extends {}> = {
  [key in keyof TInput]: { key: key; caption: string; formatter?: (value: TInput[key]) => string; };
}
type RowRenderer<TInput extends {}> = RowRendererMeta<TInput>[keyof RowRendererMeta<TInput>];

const test: RowRenderer<Entity> = {
  key: 'someDate',
  caption: 'My Date',
  formatter: (value) => value ? value.toString() : '-' // value: any
}

const thisIsNotTheIssue: Partial<RowRendererMeta<Entity>> = {
  someDate: {
    key: 'someDate',
    caption: 'My Date',
    formatter: (value) => value ? value.toString() : '-' // value: Date | null
  }
}
```

**Expected behavior:**
TypeScript inferes the argument of `formatter` to be `Date | null`.

**Actual behavior:**
When removing the ` & ({ id: string; } | { id: number; })` part of the `Entity` type definition, everything works as expected. However including it breaks type inference, resulting in an implicit any error/warning (depending on configuration), though it does not break the `RowRendererMeta<...>` type, as shown in the second `const` declaration.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200304&ssl=22&ssc=2&pln=1&pc=1#code/C4TwDgpgBAogdsAlqKBeKBvAsAKClAZwHsBbCAEQENgIAuKKmqAHyjgFcAbTgblwF8oAMigAKDFEQATegWAAnRHADmPKINYTp9DiQBGEeWv4BKXLlCQoAJSIB3axDhTDhgLIRglADwAVAJJwYOzAUBAAHjTOBJj8AHxomLj4ANoA1hAgknBQGSBEAGZQAUEhALr0Enn0eWoAxpRgSERwsgpKqlAFRPIk1DTyAPz0ogBulJzsdMWBwcDpmWUmaAlyiirGfDj8FuDQtg5OLvKGfrMhYZFHMRjxiQeOzq7yHl5npcBxC-lFD0fPrx8JTmcTKW1wdRacigNDk9D+TxO8m88CQoAS6GweFymXoAHJiGRGBA8QAaZJQBpNRAtfFuLLEskU7q9fqGEbjSYQZaoBKcqZQQZQfkQAB0wCIAGV2ipRMt8QBaPFQAD0KuFEym9EocBAAnMOEhcGhwAAFogCP4CAA5IjAXymiBWghaqAABUo8iQE28COO7k8PlRyBAcQxSWxhIo1GmWPw+GqUAJpGjNCZ2PwVOarST9IYMfT8a6PT6wAGHM13JWGq5gprU3FUplyjlUEVyrV9emxJYbC4nApO22QA)

**Related Issues:** None found.

**Edit:** Inference for `id` sadly does not seem to work at all.

**Edit 2:** Even though TS seems not to infer the type of the function argument, it complains when you try to use an invalid type (in this example `string` to name one).

**Comment by orta** [comment]
Just in case someone is blocked on this, you can switch from `({ id: string; } | { id: number; })` to `{ id: string | : number; }` [as a work around](https://www.typescriptlang.org/play/#code/PTAEHkCcEsHNoHYEMA2AoEoAuBPADgKagCiCW0uoAvKAN6gDOA9gLYEAiSWBAXKJ91AAfUAgCuKFKAC+oAGSgAFPWgATPgywwEsANwzhdUGr7iWAIwKR90gJRoMYAIpjoAYwDWAM2gAPNLiEJGQUONRGzGwCvPxcRCLikgYKKuqMWoiwhmaW1gYOgUQASkwA7kUECKpWVgA8ACoAkgh4YligBL7cVQx00gB84SXlldWQVgCyBFhIDc2tWP0A2h4EOExeoMMVVTWQUzNzLW39ALq6Dm5MCJrYBJp826N7taTkuIM0tGigoKs4fAA5JEOHFAQAaH6gNxIPDka5AiZhaIQqFeJiQFhcbiQPiKABuqDEBFs1EGhJQxNAAH5QBTiQA6LBMADKGR0ilJQIAtIDQJh6TEkAgcGhpAV8MUyjsxpNprMmsd2p1uqperQBuFvr8VmtjAg-msNqBFQtTnxtb9DQDrRcrdDYfCEBp2Xoob90ZjsVZqXjBXxTW1dThTqSqINNNo3b9pBdxWgrjd2lgABbQBiNBgAOSYWHqKYImYYxL4AAUkJByKhak9duN9vLXiEPp86FCQdELe7rUCO2DIfaYXDoAjQICkbFuKj7Z6sVgcX6iSSyXSlzTV5SCEzWa7OaAeXyBUu+NFshJ0DGxUA)
