### ISSUE TITLE
React

### ISSUE THREAD

**Issue by jssaluja1** [microsoft/TypeScript#37245]
hi can anyone hep me with this  question
1. Write a react function that takes the following input:
rooms = [
    { room_type: "Queen", vacant_rooms: 5, price: 100 },
    { room_type: "Double", vacant_rooms: 3, price: 75 },
    { room_type: "Twin", vacant_rooms: 8, price: 60 }
  ];
And produces the following output:
<ol><li>Queen, 5, $100</li><li>Double, 3, $75</li><li>Twin, 8, $60</li></ol>

**Comment by soul-codes** [comment]
[StackOverflow](https://stackoverflow.com/) would be a more appropriate place to ask questions such as these.

**Comment by orta** [comment]
Hey there, as @soul-codes mentioned this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [TypeScript](http://stackoverflow.com/tags/typescript) where people can help out with questions like this. We try to keep the TypeScript issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
