### ISSUE TITLE
Assertion functions cannot be used to narrow discriminated union types

### ISSUE THREAD

**Issue by vaskevich** [microsoft/TypeScript#37241]
Recently I tried to get creative with an assert function, but ran into a shortcoming. I think I understand *why* this is the behavior, but it would be nice if it wasn't the case.

**TypeScript Version:**  3.9.0-dev.20200304

**Search Terms:** assertion assert function discriminated union narrowing

**Code**

```ts
interface Cat {
  type: 'cat';
  canMeow: true;
}

interface Dog {
  type: 'dog';
  canBark: true;
}

type Animal = Cat | Dog;

function assertEqual<T>(value: any, type: T): asserts value is T {
  if (value !== type) {
    throw new Error('Not equal!');
  }
}

const animal = { type: 'cat', canMeow: true } as Animal;
assertEqual(animal.type, 'cat' as const);

// Error
animal.type; // "cat"
animal.canMeow; // Property 'canMeow' does not exist on type 'Dog'

// Works
if (animal.type !== 'cat') {
  throw new Error();
}
animal.canMeow; // true

```

**Expected behavior:**
Calling `assertEqual(animal.type, 'cat')` would infer `animal` as a `Cat`.

**Actual behavior:**
Only `animal.type` by itself is inferred; the type narrow does not "propagate" up to the union type.

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=32&pc=1#code/JYOwLgpgTgZghgYwgAgMJzMg3gWAFDLJgCeADhAFzIDkCG1A3PoXSALIQD2A7lWFAFcITPAF98+UJFiIUAEU4BzbMyJlKNACZLGq1gCE4UANZ9Bw-OLz4S5ZAEEQwALZwANsgC8aDMgA+yAqKIvgwAiAIYMCcIMhwAM7x0GAAogCOAu4APAAqAHwAFABu7kJUcCDEADRq5FQ5AJTlicnxyCVuQsjAbTkqBN0wyMWlKACEnt62EA39hIRgABZQPMggENzIKVArUAXUAHKcmBAZ7mPUDSKEVlb4CDHxmBUu7l7YtRq09DWsHDxmLqiOJtRyvNwiBJJKCpM5uAovVxuAB00xq3zA1BByAeICeVwkeAA9EStjtOFB8Ij3Kj1AxkCTkAAiOhgJlUpxI5F-LjcemMgAKK3IMOINB5PCx2ggbRAx2QEAAHj1MDFPjQgtRCYyAOoU4zxSRDBGcmnTZATbwYy5zIjLVbrTbbXYFAliDng7kVf58hmk-hCQlAA)

**Related Issues:** #11787 (most closely related, but that's for type guards, not the new assertion functions), #34596

**Comment by jamietre** [comment]
I'm having a similar problem. It's not totally clear to me if your example exposes the same behavior, but it seems very similar: the type is not narrowed by the assertion.

```
interface Ok extends String {
  _nominal: null;
}

function assertIsOk(foo: string | Foo): asserts foo is Foo {
  if (foo !== "ok") {
    throw new Error("not ok");
  }
}

function mustBeOk(foo: Ok) {
  ...
}

let baz: string;
..
assertIsFoo(baz);
mustBeOk(baz);  // compiles  - `bas` is type "string & Foo"; expected it to be type "Foo"
```

Works the same way when coded as a type guard.

**Comment by BobElDevil** [comment]
Note for a workaround in the first example, a more generic `asserts value` works for the original example situation, since that asserts the entirety of the statement as true, like an 'if' would

```
interface Cat {
  type: 'cat';
  canMeow: true;
}

interface Dog {
  type: 'dog';
  canBark: true;
}

type Animal = Cat | Dog;

function assert(value: any): asserts value {
  if (value) {
    throw new Error();
  }
}

const animal = { type: 'cat', canMeow: true } as Animal;
assert(animal.type === 'cat');

animal.type; // "cat"
animal.canMeow; // Works
```

**Comment by wmaca** [comment]
It seems to be affecting other union types:

```
type MyUnion = { [key: string]: any } | string[];

function assertObject(value: any): asserts value is Record<string, any> {
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
        throw new Error("Assertion failed");
    }
}

function getValue(): any {
    return { foo: "bar" };
}

const value = getValue();

assertObject(value);

console.log(value["propName"]); // Error as it does not know if it is a string[] or { [key: string]: any }
```
