### ISSUE TITLE
T[K][number] cannot be pushed to T[K] being an Array type

### ISSUE THREAD

**Issue by maciejsikora** [microsoft/TypeScript#37248]
**TypeScript Version:**  3.8.3

**T[K] push T[K][number]**

**Code**

```ts
type T = {
   a: number[],
   b: string[]
}
function add<K extends keyof T>(a: T, k: K, v: T[K][number]) {
   const tmp = a[k]; // tmp has type T[K]
   tmp.push(v); // error ? how T[K][number] cannot be pushed to T[K] ?
}

add({ a: [], b: [] }, 'a', 12) // level of api fully correct typying
```

**Expected behavior:**
Array T[K] can be pushed by T[K][number] as this is exactly the type this array contains.

**Actual behavior:**
Error:
```tsArgument of type 'T[K][number]' is not assignable to parameter of type 'never'.
  Type 'string | number' is not assignable to type 'never'.
    Type 'string' is not assignable to type 'never'.(2345)
```
**[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=11&ssc=69&pln=1&pc=1#code/C4TwDgpgBAKlC8UDeAoK6CGAuKA7ArgLYBGEATgNoC6ANGusTgM7BkCWuA5tSgL4ooAZvlwBjYGwD2uKBgAmcgDwBpKBAAewCLjlMoAawghJg2AD4AFNlg0DOZbYBuOGBWVUKBEuSoBKZPRQotIsUMCEYAiyFPpUANxQAPSJYRFQABYYeqCQsG5UgeFgAHRg+EzpFo6+CclqZGSSZFAA-BmSAO5QTJKE0K7unkSkZFRBGLi4ksBQpFBlFRByYZJ57q18AvJyFkiyONS2jFDUULy2AOQYF7YAjABM-nUANhCOEM9QJrJgbFDCz2eICCTTIEHEYXAIA4nCAA)**

**Comment by nmain** [comment]
Unsound:
```ts
add<"a" | "b">({ a: [], b: [] }, "a", "v");
```
