### ISSUE TITLE
Arrow function member marked as SyntaxKind.PropertyDeclaration

### ISSUE THREAD

**Issue by testpossessed** [microsoft/TypeScript#37247]
**TypeScript Version:**  3.7.x-dev.201xxxxx
3.8.3

**Search Terms:**
isArrowFunction
SyntaxKind.ArrowFunction

**Code**
Given I have a class defined thus

```ts
export class OrgMe {
  field = true;

  constructor() {}

  arrfn = () => {};

  mthd() {}
}
```
When I run the excellent TypeScript Class Organizer extension it gets organised like this

```ts
export class OrgMe {
  arrfn = () => {};

  field = true;

  constructor() {}

  private mthd() {}
}

``` 
This is a problem because we use tslint and the default rules require methods be organised after the constructor.  Of course we could disable the rule, but don't want to.

I attempted to fix the problem with the intention of submitting a PR to the author such that arrow functions are recognised and organised as methods of the class.  The extension has a parser that implements a visitor pattern on nodes in a ts.SourceFile.   The section of interest originally looked like this

```ts
else if (ts.isClassDeclaration(node))
{
  elements.push(new ClassNode(sourceFile, node));
  for (let member of node.members)
  {
    if (ts.isConstructorDeclaration(member))
    {
      (<ClassNode>elements[elements.length - 1]).constructors.push(new ConstructorNode(sourceFile, member));
    }
    else if (ts.isPropertyDeclaration(member)))
    {
	(<ClassNode>elements[elements.length - 1]).properties.push(new PropertyNode(sourceFile, member));
    }
    else if (ts.isGetAccessorDeclaration(member))
    {
	(<ClassNode>elements[elements.length - 1]).getters.push(new GetterNode(sourceFile, member));
    }
    else if (ts.isSetAccessorDeclaration(member))
    {
	(<ClassNode>elements[elements.length - 1]).setters.push(new SetterNode(sourceFile, member));
    }
    else if (ts.isMethodDeclaration(member))
    {
	(<ClassNode>elements[elements.length - 1]).methods.push(new MethodNode(sourceFile, member));
    }
    else if (ts.isIndexedAccessTypeNode(member))
    {
       (<ClassNode>elements[elements.length - 1]).indexes.push(new IndexNode(sourceFile, member));
    }
  }
}
```
I modified it to add ts.isArrowFunction(node) alongsid the check for method declaration

```ts
else if (ts.isMethodDeclaration(member) || ts.isArrowFunction(member))
{
  (<ClassNode>elements[elements.length - 1]).methods.push(new MethodNode(sourceFile, member));
}
```
However this did not work.  Debugging the extension I found the problem is that the ts parser has marked the arrow function as SyntaxKind.PropertyDeclaration

**Expected behavior:**
TypeScript parser recognises a class member declared like this
```ts
 arrfn = () => {...}
```
as an arrow function and the corresponding node is set to SyntaxKind.ArrowFunction
**Actual behavior:**
The arrow function node kind is set to SyntaxKind.PropertyDeclaration

**Playground Link:** 

**Related Issues:**

**Comment by IllusionMH** [comment]
How do you perform this check?

Class member should be `PropertyDeclaration` because `arrfn = ...` is property declaration independently from what it's assigned to.
In your case you need to go a bit deeper and for each `PropertyDeclaration` check if its `initializer` is `ArrowFunction`.

**Comment by testpossessed** [comment]
Thanks for the fast and throughough response.

The check is at the point we iterate through the members.  The code provided is one of the conditional blocks that is run when we detect that we are processing a class definition.  It iterates through the members and populates collections of different member types, that are later used to organise the class based on some configuration settings.

I will try that now, and hopefully close this issue very quickly.

**Comment by testpossessed** [comment]
All good, thanks again for your help.
