### ISSUE TITLE
Narrowing a function/component type to take a more specific parameter

### ISSUE THREAD

**Issue by alloy** [microsoft/TypeScript#37250]
I’m trying to find a way to support typings for cross-platform React Native components in a single file using already supported TS features.

In this example I use a functional React component, but the same applies to a class-based component.

**TypeScript Version:**

Nightly

**Search Terms:**

type-guard function parameter narrowing

**Code**

```ts
import React from "react"

interface CommonProps {
    commonProp: 42;
}

interface IOSProps extends CommonProps {
    iOSProp: 42;
    __platform_ios?: never
}

interface AndroidProps extends CommonProps {
    androidProp: 42;
    __platform_android?: never
}

function SomeComponent(props: IOSProps | AndroidProps) {
    return <div/>
}

type ExtractIOS<C> = C extends React.ComponentType<infer R>
  ? R extends { __platform_ios?: never }
    ? React.ComponentType<Extract<R, { __platform_ios?: never }>>
    : never
  : never

function onIOS<C extends React.ComponentType<any>>(
    component: C
): component is ExtractIOS<C> {
    return true // In reality, this would check if the current React Native platform is iOS.
}

if (onIOS(SomeComponent)) {
    (<SomeComponent commonProp={42} iOSProp={42} />);
    // We want this to fail
    (<SomeComponent commonProp={42} androidProp={42} />);
}
```

**Expected behavior:**

For it to work similarly when using re-assignment instead of a type-guard:

```ts
function makeIOS<C extends React.ComponentType<any>>(
    component: C
): ExtractIOS<C> {
    return component as any
}

const IOSComponent = makeIOS(SomeComponent);
(<IOSComponent commonProp={42} iOSProp={42} />);
// This fails as expected
(<IOSComponent commonProp={42} androidProp={42} />);
```

**Actual behavior:**

Type of `SomeComponent` remains `function SomeComponent(props: IOSProps | AndroidProps): JSX.Element` after applying the type-guard.

**Playground Link:**

[Link](https://www.typescriptlang.org/play/index.html?jsx=1&ts=3.9.0-dev.20200305#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wChTgA7GJKTdJOAYVxAkoAUcwBnOAb1JxhcNK3ZcIYAFxwALACYA3KQC+5KjToM4ASQDyAZUm84SAB41KAEz4sQbTtz6CRcYEZOzFKtwH0-MAAbFBhMaBA-YAgeAH5ZSiQAN1o1DWpaejRGAEEbHGBrEz4LK1tmcScpFyERFHyIQq95ZVrhAODQ8KhI+usC63i4RJSoNNJMAFdKDGjKOENcJHtIROoACjBnWQNjZzgAHzg8-sai5wBKATa4IhhJqHmAHmtgJIB6AD5xmABPMEYAFFLFB0DBdk8mJ84ABeZhmSxIGx8ZBggB0K3YSJgABV-kgnlRMLREN9hLFEAiyi44B0QmEIlEYkMRiT1G4KaiMBjcKtsXiAU9gTBQRgnggADQCWmBendSLROIJZJsz5kkTK0a1TWpUjvd5wAASEAA7qJ6nATYxrBA4Cg4H8AQBaADmkxQUGsDoAFqE4L6+Pa2ERhh6cGaAFSJHg0awR25Ie6PB342ITaazdhwdgQphUpHlLkwHngLHUAUE+q-NXrG5iUtrGCyJikC6yet86juPjC0XgoyQ6GuER3B7zEWTRj6vTzIgoILAP5SmDe4B8E0QSZBL1ob1INAAa3cmB9jDQDyIXaLcAAcqE3oxOgyet33EY0WlgCf1jmjOtFiAyy8mWMAXFcw7COsTwAUBDbYqIlQmDC-CKKob57FIyGoXAXwXL4IjToY3qbtucD0MAQQ3FBMGYo2CEOBI3BYQoaF9AMSEoSxOGfHh4zTtOOKruu0AHjwUoAEaTPAa6UIAmATwPajpIK67qeumMwwHMcAgCgB5ILm+bIogxDFrR-L4k8VY1nWwGNs2rayL2YK5kONyjsmHYgXagaUL8aRiJQMZ6EYZldnCOl6bs-5LKFoEqFBuyxfRjgcdhHgYWAzFobhKiEcRW5euRlEJSFtnwfWKVMZxrENE0VXYTlpBAA)

**Comment by DanielRosenwasser** [comment]
This one's a little tricky. The problem is that because parameters are compared contravariantly, you're trying to narrow down a subtype (which is "narrow") to a supertype (which is "wide"). Narrowing is supposed to make types more capable, so but narrowing `SomeComponent` from `(x: IOSProps | AndroidProps) => Element` to `(x: IOSProps) => Element` is strictly making it take fewer types.

**Comment by andrewbranch** [comment]
I think you want `SomeComponent` itself to be a union, not just the props: [playground](https://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wChTgA7GJKTdJOAYVxAkoAUcwBnOAb1JxhcNK3ZcIYAFxwALACYA3KQC+5KjToM4ASQDyAZUm84SAB41KAEz4sQbTtz6CRcYEZOzFKtwH0-MAAbFBhMaBA-YAgeAH5ZSiQAN1o1DWpaejRGAEEbHGBrEz4LK1tmcScpFyERFHyIQq95ZVrhAODQ8KhI+usC63i4RJSoNNIxSh54Q1wke0hE6llkdBgAOgAxJgAeA2NnAD44AB9EYg3tnbz+xqKjuABeOEwAV0oMaMo4WZB53EWSGoAAowM5ZPtiqc4DcBsUAJQCNpwIgwV5Qb47azAJIAekO4xgAE8wIwAKKWKBrfY7JjHZ5MMyWIHlVYYdYLdhAmAAFRJSB2VEwtEQBOEsUQTLKLjgHRCYQiURiQxGIvUbglbI2nKWvP5OwpMCpGB2CAANAJZYF5d1ItE4glkmrDmKRI7RrV3alSG8PjAvnB2DTGaUWXwtRyAVzqHzSTt6kSXcDkWJwNGYLImKR4bJU4DqO4+IbjTBg8dXCJUejvkbXoxcbi9N8iCggsBiRaYAALYB8ADuEFeQWsoi7SDQAGt3Jg4N3GGh0UQC1q4AA5UI4xidBU9QvuIzrcbAGfAoNGYG-f5p3XwxEV4TAnaXnXc0SVEyPfiKVT7g5ST-fnA+Lwr4IgNnAADqjB9vU8Ddr2s4QC8KDAEEyKPs+Ua6m+DgSNwAEKD+fRwvhX6EUBhwgeM4G6DOc5wDwwAAOaUKE6KML2lCAJgE8CsVAOB9kg1gWoJcBdigKSIXAYIQEkhRbs4LzQHAABGEDdtJNoRDwh7gTyPZ8AhYj8eOMAWip44oK8PBICJSBBEEdlvkOI4WYG3xIO2Y5QJpXQRBafTSUQPCvCAKAqUERKkOB9HbrawxIEJfDdjECnVIeGFzC+Bapo4H5kT+Hh-mABFEQ0TSkYBwEqJlfzZfAuV4f+BW-vlVWUTVT5ZVhr6NVUJUtcRdxteR1WkEAA)

**Comment by alloy** [comment]
Ah yes, nice one 👌 Thanks, this solves the actual problem I had, so this can be closed as far as I am concerned.
