### ISSUE TITLE
Argument of type 'IGridModel' is not assignable to parameter of type 'T'.

### ISSUE THREAD

**Issue by NikitaEgorov** [microsoft/TypeScript#37252]
**TypeScript Version:**  3.8.3

**Search Terms:**
Generics, Cast

**Expected behavior:**
No errors

**Actual behavior:**
Argument of type 'IGridModel' is not assignable to parameter of type 'T'.
  'IGridModel' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'IBaseModel'.(2345)

**Related Issues:**

**Code**
```ts
interface IBaseModel {
  a: string
}

interface IGridModel extends IBaseModel {
  b: string;
}

function test<T extends IBaseModel>(): T[] {
  const merged: T[] = [];

  let sizeObj: IGridModel = {
    a: 'sds',
    b: 'st',
  }

  let sizeObj2: IBaseModel = {
    a: 'sds',
  }

  merged.push(sizeObj)
  merged.push(sizeObj2)

  return merged;
}



```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function test() {
    const merged = [];
    let sizeObj = {
        a: 'sds',
        b: 'st',
    };
    let sizeObj2 = {
        a: 'sds',
    };
    merged.push(sizeObj);
    merged.push(sizeObj2);
    return merged;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=28&pc=1#code/JYOwLgpgTgZghgYwgAgJICE4GcIFkD2AJhADbIDeAsAFDLJwBcyWYUoA5jQL402iSxEKVAHE2hAsTIQAHpBCEsaTDkmkKNOgCMmLNiHYBubr2owAriARhg+EMkgsAPABVks+YuXY8RUgD4ACgBKJhcAbQBdDVpkBDsWZABbaHYIQjCo5ABeZCjjak1kEggwZmAALwgAeS0AKyZRcTUyXKpYukZkAHIsRW6AGiLtJl6wQaKeQtiSsqxKmvqAJkaVXykcmLpO0b6sCdipopSoNMIAOgAHcywAC0D5qtq64OPU9Kub+8fFuqXX6Z0KClcxQewnM4FLhAA)

**Comment by AviVahl** [comment]
the error is correct.

see: https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJICE4GcIFkD2AJhADbIDeAsAFDLJwBcyWYUoA5jQL402iSxEKVAHE2hAsTIQAHpBCEsaTDkmkKNOgCMmLNiHYBubr2owAriARhg+EMkgsAPABVks+YuXY8RUgD4ACgBKJhcAbQBdDVpkBDsWZABbaHYIQjCo5ABeZCjjak1kEggwZmAALwgAeS0AKyZRcTUyXKpYukZkAHIsRW6AGiLtJl6wQaKeQtiSsqxKmvqAJkaVXykcmLpO0b6sCdipopSoNMIAOgAHcywAC0D5qtq64OPU9Kub+8fFuqXX6Z0KClcxQewnM4FI7UfjQeBINAATVKAEEQPgwLdoC13HIIAolBgfDj2iNkCBzEktNATNN4iBEnAoFBNo4wE5UMiwGiMVioC0gsFkAB6YUOW7AJSS5D4ADWA3ohK5PMx2L80jxBO8qnVNCZUHCAAZIuctCKxRSqTTpqLxSh4sRkKB5o62SFkjcytAoPgoArsE6yqxgBAlNd5gYZfUINYlJi4GVCHZumVgXASCQAJ40W3AJKXEopcDINyBUDi6UIHwKzmo9Gq-nq4LnHNimDAKCJOwoW4BvQcRU9LSDZgxuyEGUgHsByzEdtTi50GhAA

**Comment by NikitaEgorov** [comment]
Thanks!
