### ISSUE TITLE
Rest parameter with modifier is allowed

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3725]
Even though the TS spec's grammar doesn't seem to permit it, the following is now allowed:

```TypeScript
class C {
    constructor(...public rest) {
    }
}
```

Seems to have been introduced by 80edb2de4a058ccd8594d8faad5f8e1f4cbe8962.

**Comment by danquirk** [comment]
Did we really not have a compiler baseline for this?

**Comment by JsonFreeman** [comment]
We really did not
