### ISSUE TITLE
Infer generic class type with super

### ISSUE THREAD

**Issue by krmax44** [microsoft/TypeScript#37259]
TypeScript Version:  3.9.0-dev.20200305

**Search Terms:**

Super type inference

**Code**

```ts
class MyClass<T extends number | string> {
    constructor(_x: T) {}
}

const a = new MyClass(5); // works perfectly! No need for this:
const b = new MyClass<number>(5);

// but when extending, super can't pick up the type
// this throws an error:
class AnotherClass extends MyClass {
    constructor() {
        super(2);
    }
}

// only this works:
class AnotherClass extends MyClass<number> {
    constructor() {
        super(2);
    }
}
```

**Expected behavior:**

Just like `new`, `super` picks up the type.

**Actual behavior:**

Unlike `new`, `super` can't pick up the type and it has to be specified at class-level manually.

**Playground Link:** 

[Playground](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200305#code/MYGwhgzhAECyCeBhcUA8AVaBTAHgFywDsATGQgVwFsAjLAJ2gB9oI86BLQgcwD5oBvAFDQR0YAHtCrOuWB5xdABQB9HAC5o6AJQCAvoP2CJUvNDDQAvNEJYA7nCQoIigKxaA3NAD0X6LYUA1jAADvQAZlhyIPAAhNAAcuLWWFjE0GEKakaSrNDUlsn2CMiQEKgUNPQ8rh6Cgj555Ka2ABZE2PhExJxcADQs5KEMwGCEAOSmwezAAdCD0HhtC-ChAHRGTtAAgoTii-QlUB0EJDDFm0KiYjlssvJKOpdXohCD9IoATLVX+rpAA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #36456
