### ISSUE TITLE
Syntax error 'this condition will alway return false since the types A and B have no overlap' whereas the condition may in fact return true or false

### ISSUE THREAD

**Issue by JessyParis** [microsoft/TypeScript#37254]
I know there are other issues of this type opened, but here it seems to be different.

**TypeScript Version:**  3.7.5

**Search Terms:**
this condition will alway return false no overlap

**Code**
```
if (
          (key !== "nbBalleChargementAwayFrombBalleDechargement"
          && key !== "poidsChargementAwayFromPoidsDechargement"
          && key !== "prixTonneHTEquals0"
          && key !== "refusCamionDDechargementRelatedData")
          || (key === "dDechargementPrevueOutOfDMoisDechargementPrevu" && 
                  this.applicationUserContext.connectedUtilisateur.HabilitationLogistique === HabilitationLogistique.Transporteur)
)
```
**Expected behavior:**
The error message is not adequate because the condition may return true or false depending on the value of key.
If key equals 'Anotherkey', then the condition returns true
If key equals 'nbBalleChargementAwayFrombBalleDechargement', then the condition returns false

Maybe we could have a warning or another error message because the code is not well written in case key equals to 'dDechargementPrevueOutOfDMoisDechargementPrevu' (indeed, in this case the condition always returns true whatever the value of this.applicationUserContext.connectedUtilisateur.HabilitationLogistique is.)

**Actual behavior:**
The compiler show a syntax error 'error TS2367: This condition will always return 'false' since the types '"nbBalleChargementAwayFrombBalleDechargement" | "poidsChargementAwayFromPoidsDechargement" | "prixTonneHTEquals0" | "refusCamionDDechargementRelatedData"' and '"dDechargementPrevueOutOfDMoisDechargementPrevu"' have no overlap.'
the error is on 'key === "dDechargementPrevueOutOfDMoisDechargementPrevu"'.

**Comment by nmain** [comment]
Simplified and playgroundized:
```ts
declare var key: string;
declare var otherCondition: boolean;

if (key !== "a" && key !== "b" || key === "e" && otherCondition) {
}
```
[Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=6&pc=1#code/CYUwxgNghgTiAEA3W8DWICeAueBnALjAJYB2A5gNwBQoksCyM8A9vgBYgwDCzJwR+IrxwAjZswggoJalSIAzeAAp0GeAEIAvJvgAiKLvgAyI2kwbtekYYA+Ns2u07dIQyZbtOPPgKEkAlPAA3lQAvlRAA)


> the code is not well written in case key equals to 'dDechargementPrevueOutOfDMoisDechargementPrevu' (indeed, in this case the condition always returns true whatever the value of this.applicationUserContext.connectedUtilisateur.HabilitationLogistique is.)

Yes, that's exactly correct.  And TypeScript is giving you an error message notifying you of that, which is exactly what you asked for.  So what's the problem?

**Comment by JessyParis** [comment]
thank you for your answer but I am affraid yous simplification is not correct
A: (key !== "a" && key !== "b" || key === "e" && otherCondition)
is different from 
B: ((key !== "a" && key !== "b") || (key === "e" && otherCondition))

If I am not wrong, with key="c" and otherCondition=false
A: gives false
B: gives true

I agree that there were some kind of mistake in my code and it is great to have a warning in such case. But the error message "...This condition will always return 'false'..." is not correct because, with the code I have written,
- if key equals 'Anotherkey', then the condition returns true
- if key equals 'nbBalleChargementAwayFrombBalleDechargement', then the condition returns false
So the condition does not always return false.
That is what confuses me.

**Comment by nmain** [comment]
> thank you for your answer but I am affraid yous simplification is not correct

Just dumping those parens to make it easier to read.  The two are equivalent:
[Operator Precedence (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence)

The error message is correct because of the short circuiting behavior of javascript's `||` operator.  The only time you'll hit the second branch of the `||` is when the first one was false, which means `key` must have been one of the ones you tested against in the first branch.  Typescript understands this and warns you that you will never ever be in a situation where that second test is true.
