### ISSUE TITLE
import missing with tsc 383

### ISSUE THREAD

**Issue by francesc79** [microsoft/TypeScript#37262]
**TypeScript Version:**  3.8.3

**Search Terms:** import missing

**Code**
please see [test-ts](https://github.com/francesc79/test-ts)

**Expected behavior:** in the compile file i expected correct imports

**Actual behavior:** a constant import is missing

**Playground Link:** 
[test-ts](https://github.com/francesc79/test-ts)

**Related Issues:** no

**Comment by DanielRosenwasser** [comment]
Is there no way you can give us a single `.ts` file with an expected input/output?

**Comment by francesc79** [comment]
@DanielRosenwasser is not possible to give you a single .ts file because the problem is the import. This is a very strange behaviour because the problem depends on jsdoc, @types/lodash dependency and the type of source file, which is .js. The project I supplied is the minimum for reproduce the problem. The class Test have a import of INDEX_FIELD contanst,
`
import _ from 'lodash';
import { INDEX_FIELD } from './Consts';

export class Test {
  /**
   * @param {object} obj
   * @param {object} vm
   */
  test(obj, vm) {
    let index = 0;
    vm.objects = _.mapValues(
      obj,
      object => ({ ...object, [INDEX_FIELD]: index++ }),
    );
  }
}
`
I expected that in the output file the import to the INDEX_FIELD constant is kept, but it is missing

`
import _ from 'lodash';
export class Test {
    /**
     * @param {object} obj
     * @param {object} vm
     */
    test(obj, vm) {
        let index = 0;
        vm.objects = _.mapValues(obj, object => ({ ...object, [INDEX_FIELD]: index++ }));
    }
}
//# sourceMappingURL=Test.js.map
`
