### ISSUE TITLE
Invalid isExternalLibraryImport detection w/ workspaces

### ISSUE THREAD

**Issue by arcanis** [microsoft/TypeScript#37270]
**Code**

Explanation: when a project uses workspaces, since `isExternalLibraryImport` is [hardcoded to `true`](https://github.com/microsoft/TypeScript/blob/master/src/compiler/moduleNameResolver.ts#L956) unless the import path is relative, TypeScript will store the imported path into the `sourceFilesFoundSearchingNodeModules` array (even if it's actually not an external library). This will lead to the `emit` function to disable emissions (why? not sure).

As a result, it causes issues with ts-node, which doesn't know the transpilation result for the workspace files (when fixing the bug where they forgot to implement `realpath` into the host methods), or when using Yarn 2 (which doesn't use symlinks for workspaces anymore). For some reason `tsc` isn't affected; I'm not sure why, but I guess it fetches the emit files another way that doesn't rely on following the import trail.

To be honest my explanation is likely off on a few details as it's fairly intricated, but the gist is that TypeScript doesn't emit the files from the workspaces because it thinks they are node_modules entries, and that doesn't play well with ts-node.

```bash
set -e

cd $(mktemp -d)
cat > package.json <<EOF
{
  "private": true,
  "workspaces": [
    "packages/*"
  ]
}
EOF

mkdir -p packages/foo
cat > packages/foo/package.json <<'EOF'
{
  "name": "foo",
  "version": "1.0.0",
  "dependencies": {
    "foo": "1.0.0"
  }
}
EOF

mkdir -p packages/bar
cat > packages/bar/package.json <<'EOF'
{
  "name": "bar",
  "version": "1.0.0"
}
EOF

cat > tsconfig.json <<'EOF'
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node"
  },
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ]
}
EOF

cat > packages/foo/script.ts <<'EOF'
import 'bar';
EOF

cat > packages/bar/index.ts <<'EOF'
export const bar = 42;
EOF

yarn add -W ts-node typescript

## Required to fix a bug in ts-node which doesn't properly declare the `realpath` primitive
sed -i.bak 's#\(const serviceHost = {\)#\1 realpath: ts.sys.realpath,#' node_modules/ts-node/dist/index.js

yarn ts-node packages/foo/script.ts
```

**Expected behavior:**

The script should exit without failure.

**Actual behavior:**

```
TypeError: Unable to require file: packages/bar/index.ts
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or other executable extension with loader attached before `ts-node` available.
at getOutput (/tmp/tmp.oa9rKs0ArQ/node_modules/ts-node/src/index.ts:538:17)
at Object.compile (/tmp/tmp.oa9rKs0ArQ/node_modules/ts-node/src/index.ts:735:32)
at Module.m._compile (/tmp/tmp.oa9rKs0ArQ/node_modules/ts-node/src/index.ts:814:43)
at Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
at Object.require.extensions.<computed> [as .ts] (/tmp/tmp.oa9rKs0ArQ/node_modules/ts-node/src/index.ts:817:12)
at Module.load (internal/modules/cjs/loader.js:914:32)
at Function.Module._load (internal/modules/cjs/loader.js:822:14)
at Module.require (internal/modules/cjs/loader.js:956:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/tmp/tmp.oa9rKs0ArQ/packages/foo/script.ts:1:1)
```

**Comment by sheetalkamat** [comment]
This seems issue with ts-node and not typescript,

Running this with tsc results in correct result.
```
c:\temp\test>node c:\TypeScript\built\local\tsc.js --listFiles --listEmittedFiles
TSFILE: c:/temp/test/packages/bar/index.js
TSFILE: c:/temp/test/packages/foo/script.js
c:/TypeScript/built/local/lib.d.ts
c:/TypeScript/built/local/lib.es5.d.ts
c:/TypeScript/built/local/lib.dom.d.ts
c:/TypeScript/built/local/lib.webworker.importscripts.d.ts
c:/TypeScript/built/local/lib.scripthost.d.ts
c:/temp/test/packages/bar/index.ts
c:/temp/test/packages/foo/script.ts
```

**Comment by arcanis** [comment]
I mean, the problem is at least in part in TS. The heuristic that detects external libraries is simply incorrect with regard to workspaces.
