### ISSUE TITLE
this["prop"] does not resolve properly when used in conditional type

### ISSUE THREAD

**Issue by xaviergonz** [microsoft/TypeScript#37275]
**TypeScript Version:**  3.8.3

**Code**

```ts
  class C {
    arr: number[] = [2]

    x() {
      // I expect this to be "number"
      type A = this["arr"] extends Array<infer T> ? T : never

      // but apparently it is not
      const a: A = 5 // type 5 is not assignable to type A
    }
  }
```

**Expected behavior:**
Type A should be number

**Actual behavior:**
It seems like the type never gets resolved to anything

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=7&ssc=1&pln=1&pc=1#code/ATDGBsEMGduBhYBvAUCEkBOmBcwB2ArgLYBGAppgNoC6wAvMFQEw0proAeAFAJTId0wAC4BPAA7lgAQQYiAFgEtoVAERZMquuU7Dy+ACZxp2SKIA8i-ADNKwACoA+YAH4HwPPnIA3SoPSgAPb40MLAkHiyjACswAD0cSISUrHKBIFhMNCKAOb4kKTgUsKBSZIy-gC+HNVAA)

**Related Issues:** N/A

**Comment by ilogico** [comment]
I think this is the expect behavior, since TypeScript allows an extending class to refine properties:
```ts
class D extends C {
  // This is unsound, but allowed in TS
  arr: (1 | 2)[] = [2];
}
```
This happens because you use `this['arr']` instead of `C['arr']`.
