### ISSUE TITLE
Conditional types split function return type `boolean` to two separate functions

### ISSUE THREAD

**Issue by moshest** [microsoft/TypeScript#37279]
**TypeScript Version:**  3.8.3

**Search Terms:** return type true false instead of boolean

**Expected behavior:** Template should resolved to a `() => boolean` function

**Actual behavior:** Template resolved to `(() => true) | (() => false)`

**Related Issues:**

**Code**
```ts
type Func<T> = T extends never ? never : (() => T);

const foo: Func<boolean> = Boolean;

// Type 'BooleanConstructor' is not assignable to type '(() => false) | (() => true)'.
//   Type 'BooleanConstructor' is not assignable to type '() => false'.
//     Type 'boolean' is not assignable to type 'false'.(2322)
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const foo = Boolean;
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.8.3#code/C4TwDgpgBAYgrgOwMYB4AqA+KBeKaoQAewECAJgM5QIQBuEATlAPzV2NQBcUAFDwJQ4safgG4AUOKQB7BBWBQAZtOnd4yFACMVAGwgBDBFlwAhXQYSigA)

**Comment by moshest** [comment]
The same problem happens to any union type:

```ts
type Union = 1 | 2;

const misc: Func<Union> = (): Union => 1;

// Type '() => Union' is not assignable to type '(() => 1) | (() => 2)'.
//   Type '() => Union' is not assignable to type '() => 1'.
//     Type 'Union' is not assignable to type '1'.
//       Type '2' is not assignable to type '1'.(2322)
```

**Comment by jcalz** [comment]
This is working as intended; see the documentation for [distributive conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types).  The easiest way to turn this off is to “clothe” the bare type parameter `T` in a one-tuple: change `T extends never ? A : B` to `[T] extends [never] ? A : B`.

**Comment by moshest** [comment]
Thanks @jcalz!

So current fix is:
```js
type Func<T> = [T] extends [never] ? never : () => T;

const bool: Func<boolean> = Boolean;
```

**Comment by jyasskin** [comment]
Thanks @jcalz for pointing me here in https://stackoverflow.com/a/61927169. I wonder if it might be possible to improve the error message when … something that doesn't look like a union winds up in a distributive conditional type that … resolves to hard-to-satisfy types? You'd know better whether this is actually confusing a lot of people, but it seems like the compiler could help more here.
