### ISSUE TITLE
Make const array declaration truly constant

### ISSUE THREAD

**Issue by AnupKTarafder** [microsoft/TypeScript#37288]
## Search Terms
const array

## Suggestion

Values shouldn't be pushed to arrays declared via const 

## Use Cases

For now, we can declare arrays as constant and later push some value inside the array without the compiler throwing any error.

`const arr = [1, 2, 3, 5, 7, 11];`
`arr.push(13, 17);`

But if we try to assign a direct value, the compiler throws an error. 
`arr = [1, 2, 3, 5, 7, 11, 13, 17];`

>Can not assign to arr because it is a constant.

## Examples

`const arr = [1, 2, 3, 5, 7, 11]`
`arr.push(13, 17);`
>Can not push values to arr because it is a constant.

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> [x] This feature would agree with the rest of TypeScript's Design Goals.

This definitely would disagree with several design goals, e.g.

> Align with current and future ECMAScript proposals.  
> Do not cause substantial breaking changes from TypeScript 1.0.

You're misunderstanding `const` variables as "this object can not change anymore", when it's actually just "the assignment can't be changed".

Also, are you aware of [const assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions)?

**Comment by RyanCavanaugh** [comment]
`const` refers to the constancy of the value that the identifier binds to, not the immutability of the bound value.
