### ISSUE TITLE
Allow throwing where expressions are expected

### ISSUE THREAD

**Issue by avin-kavish** [microsoft/TypeScript#37296]
## Suggestion

Why can't we throw exceptions where expressions are expected in C# style?

```ts
this._es = es ?? throw new Error('Argument Null Exception')
```
## Use Cases

Throw in one line.

**Comment by nmain** [comment]
This is already being championed in TC39 https://github.com/tc39/proposal-throw-expressions, and Typescript will add it if it passes there.

**Comment by avin-kavish** [comment]
Thanks, I was gonna prefix this with maybe I should take this to TC39, is it expected to progress smoothly? I really don't see why there could be any hiccups considering how effective and practical it is in C#.
