### ISSUE TITLE
Assert functions do not constraint type when they are guarded by a truthy expression.

### ISSUE THREAD

**Issue by mhevery** [microsoft/TypeScript#37295]
**TypeScript Version:**  3.8.3

**Search Terms:**: [Assert Function](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+assert+functions)

**Code**

```ts
function assertString(actual: any): asserts actual is string {}
function expectString(value: string) { }
let devMode: {} = {};

// This works as expected
const x: string|number = '' as any;
assertString(x);
expectString(x); // x is string!

// This fails
const y: string | number = '' as any;
// Expecting TS to correctly infer that `devMode` is always truthy and 
// hence the`assertString` sholud always execute therefore its 
// type assertion should hold.
devMode && assertString(y);
expectString(y); // y is string|number hence it fails
```
**Expected behavior:**

Assert functions should be assumed to always execute when they are guarded by an expression which is truthy.

**Actual behavior:**

Any sort of guard expression (even if know to be truthy) prevents the assert function from applying its constraint.

**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=16&pc=54#code/GYVwdgxgLglg9mABAQwM6oKYCcoGUpYxgDmAFMtCMgDYBcKYAngJT1qY6oqU2IxeoCRYogDeAXwBQoSLASIMADwAOGaPkIlSANxogM9QZuLMxiKdQxREAEwzaAsnDv0JiALxjxAbkmSA9P6IACoAFvyIAO5wWADWXGgKKmpQGDaSEAiCiIqGQiQAPmAgALYARtgeiADk1SgJTL7s2Hj5ZIrMvkqq6m2kHd6IgTl8Am0AhH7DYRHAyDDUqBlZ1ox5xogFiMXllZ619QyMvsMAosnQwiG4iFBwiJlYWCnUjHxgwJVQocjWAAZ2RzODB-UYoaiRZCMLgEEDfN7IMA2RABIKhDCQDC3dF-Zo4DTCUGoUJwaggZE0SHQpJqOFY77YDDAGJYmBQLio26MVT1DhyJDEuAgajIkkigB0kkBTjsiAAZHLeS0CVoWF0Lq1jKQ1UMgm8IkZhEVShUsIh0Zi+NY5gtUEA)

**Related Issues:** 
- [Assertion functions cannot be used to narrow discriminated union types · Issue #37241 · microsoft/TypeScript](https://github.com/microsoft/TypeScript/issues/37241)
- [Assertion functions don't work when defined as methods · Issue #36931 · microsoft/TypeScript](https://github.com/microsoft/TypeScript/issues/36931)

**Comment by RyanCavanaugh** [comment]
We don't trust the results of our own truthiness analysis for these situations because there are legitimate situations where a falsy value might inhabit a truthy position. We also believe that code like `x && y` is written *because* `x` is possibly falsy (otherwise why would you do it...?). It seems like you intend to strip this out later, so I'd recommend just using some other approach.
