### ISSUE TITLE
Undefinining a non optional interface property doesn't yield an error

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3730]
I think this code:
```typescript
interface A {
	a?: string;
	b: string;
}

let a: A = { a: "hej", b: "då" };
a.a = undefined;
a.b = undefined;
```

should yield an error at line:

```typescript
a.b = undefined;
```

because we are undefining a non-optional property.

**Comment by tinganho** [comment]
Also passing an initialized undefined value to an function argument like this:
```typescript
interface A {
	a?: string;
	b: string;
}

function test(a: A) {
}
test({ a: "hej" }); // error as expected
test({ a: "hej", b: undefined }); // no error
```
shouldn't it yield an error?

**Comment by RyanCavanaugh** [comment]
`undefined` is a valid value for all types (see #185 for discussion of non-nullable properties). Only `delete` actually "undefines" a property in JS, and it's very rarely used.

**Comment by tinganho** [comment]
> undefined is a valid value for all types

I expect most people treat `undefined` as not a value? Even though I use an assignment operator for undefining something, the meaning is still undefining a property like `delete` does? Or does it mean assigning it an undefined value?

**Comment by tinganho** [comment]
Ok I think I got it clarified in here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined.

So the interface:
```typescript
interface A {
    a?: string; 
}
```
`a?` means optionally initialized and NOT optionally `undefined`.
