### ISSUE TITLE
Type inference within decorator factory args

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#37300]
**TypeScript Version:**  3.8.2

**Search Terms:** decorator, member, target, type, signature, inference, propagation, arguments, return

**Disclaimer:** I'm unsure if this is a bug or by design, although I hope for the former.

**Description:**

It seems that a lot of crucial type information is lost to decorators and decorator factories.

I'm trying to create a `Field` decorator, which acts on the following class members:

```ts
export class User {
  @Field()
  name: string;
  @Field((user) => `Hello ${user.name}`)
  greeting: string;
}
```

`Field` has an optional argument: a function. If passed a function, that function's signature should be––in the case of the `User` class––`(user: User) => string`. The function's argument type `User` can come from the decorator's target, and the function's return type `string` can come from the member, the `Target[PropKey]`). Let's temporarily ignore the desired return type inference and focus on placing the target type as the argument's type. It seems––at first glance––that we should be able to do the following:

[View in TS Playground](https://www.typescriptlang.org/play/index.html?strictPropertyInitialization=false&experimentalDecorators=true&emitDecoratorMetadata=true#code/MYewdgzgLgBAYgSwKYBsAmMC8MA8AoGGAFQEMAnAcySgBoCYAlGJADyiTDQhgApyKAXMX7UAlFgB8MAK5gA1mBAB3MHgl9KAfiENxmKQG96ZatLJheUEVCGlK1GjAD6ABzIgXSMlACeAaSQfIQAFd09vf0DRIQA3EAQMfRgjQkJQSBAUJAA6FBAKDQpHK3soUQBuegBfSpq8PFYXEG8YYBQSCG4AVQgvZPowEgBbJCFoMgQwCkr6AAFEVDQeHmlesj1DekITKDMLAAMACVQ8mAASA1WvbMGRqv3KwirRegoTaknBGHHP2qA)

```ts
const Field = <
  Target,
  // desired return type is `string`, but we'll leave as `unknown` for this example
  R extends (arg: Target) => unknown
>(arg?: R) => {
  return (target: Target, _propertyKey: PropertyKey): void => {
    console.log(arg, target);
  };
};
```

I expected that, within the `User` class, the anonymous function passed to `Field` would infer its argument as being of type `User`. Instead, the `unknown` type is imposed on the arg.

We also run into problems when trying to gather the member type as the function's return type. My hope was that one could do something along the following lines:

[View in TS Playground](https://www.typescriptlang.org/play/index.html?strictPropertyInitialization=false&experimentalDecorators=true&emitDecoratorMetadata=true&ssl=1&ssc=1&pln=18&pc=2#code/MYewdgzgLgBAYgSwKYBsAmMC8MA8AoGGAFQEMAnAcySgBoCYAFMkABwGkkBPGJADyiRg0ERsxZIyUTh051CcMD36DhMABTkKALmKbqASiwA+XZWoBtJqxkBdPEY2UA-DoWHMJgN70y1AK5kimpQelA6pGa0MCxiMjpW7Fz6OgBuIAgYHjDehISgkCAoSAB0KCAUjhQ0MCGR1THWSQDc9AC+Le14eHwsIJIwwCgkECIAqhAS2fRgJAC2SDrQZAhgFC30AAKIqGhqan4TZO5e9IS+UAGKAAYAEqhlMAAkngcSxTPzrVcthK369BRfNQVtoYEsQR0gA)

```ts
const Field = <
  Target,
  PropKey extends PropertyKey,
  Fn extends (arg: Target) => Target[PropKey]
>(arg?: Fn) => {
  return (target: Target, propKey: PropKey): void => {
    console.log(arg, target, propKey);
  };
};
```

The thinking is that this would effectively safeguard the user against returning a member-incompatible type from that anonymous function (the return type would be set to `string`). Instead, we get the error `Type 'PropKey' cannot be used to index type 'Target'`. I'm unsure if there's a way to still gather the return type, or if this has to do with the larger problem of type info propagation in decorator functions/factories.

Thank you so much for reading through this issue. I greatly appreciate any help!

Kind regards,

Harry

**Comment by sam-goodwin** [comment]
You can build type-safe decorators by returning a generic function:

```ts
function field<InstanceOf>(): <T extends object, K extends keyof T>(
  target: T,
  propertyKey: T[K] extends InstanceOf ? K : never
) => void {
  return null as any;
}

class A {
  @field<number>()
  @field<string>()
  key: string;
}
```

Breaking it down:

This creates us a decorator that can only be applied to fields of type `InstanceOf`:
```ts
function field<InstanceOf>()
```

The type of the decorator is generic. It then capture the instance value, `T`, and the property key, `K` and uses them to validate that `T[K] extends InstanceOf`:
```ts
<T extends object, K extends keyof T>(
  target: T,
  propertyKey: T[K] extends InstanceOf ? K : never
)
```

You can encode any constraint you want in here:
```ts
propertyKey: T[K] extends InstanceOf ? K : never
```

**Comment by harrysolovay** [comment]
Similar, but that's a slightly different problem from the one described. The issue is that it's not possible to pipe type information about the class and the specific class field, into whats passed to the decorator factory, a function, in which the first parameter should be of the class type, and the return type should be of the field type.

**Comment by harrysolovay** [comment]
TS team members: please let me know if you'd like me to close this issue.

Seems it may no longer be applicable, depending on the outcome of the latest decorator proposal.

**Comment by rbuckton** [comment]
I'm not certain inference can work the way you want here. Consider that (A) and (B) below are essentially the same:

```ts
class C {
  // A
  @field(t => "foo")
  f: string;
}

// B
field(t => "foo")(C.prototype, "f");
```

Inference generally flows left to right, we currently can't infer `t` in (B) either ([Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMwJYgmAC54AeAFXhAA8MQVg14kAjAK3AwBp4BpK2vUbwA1iACeSbPHI8AYgLoMmAClgBzEuQCU8ALwA+GQG1eAXQMrsJObsPwVGDSAxaeY8SV52jANyS4wADcALAAUOGQUGhMAMLwAN7h8CnwAAJ4BMCO+kYARNhISHnayanYAIQkmDC4KOqhYQC+4eGZhDn2BUUlKrEAdAAOMEgYo+KDIDwFJUFAA)).

You can _almost_ get there with a somewhat backwards definition of `field` and a helper type:

```ts
type MatchingKeys<T, TMatch> = { [P in keyof T]: T[P] extends TMatch ? P : never }[keyof T];

declare const field: <F extends (arg: any) => unknown>(f: F) => 
    <T extends Parameters<F>[0], K extends MatchingKeys<T, ReturnType<F>>>(target: T, key: K) => void;

class C {
    @field(t => "foo")
    f!: string;
}

field(t => "foo")(C.prototype, "f");
```

Except `t` above is still essentially untyped ([Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCyBDGBjAFgSwDsBzAaWEQGcAeAFQBo5bMdcA+OAXjgG84BtAApwicANYUIAMyYBdAFxMhsuKBjBCAE0pMWeOAH44wxYWAA3YFDgBffhMTS5AbgCwAKA+bg2ADYYoVGwIQkp4KXxgX01FagAxVRB1LR0ACgDiRQxCRABKLg4AV0IxQggAd0I2VKlFOPzODjpE5O1jAIwAW2B1KBo4tn4ABllGUhaNNr0CEnIqOkYAJR7CqEJaZGB4th3UmAyexQZxCkVSBo5zCHxNN093PwxKHQBhXg84T7gAAQiozT2BTgACIpBAIMD8l9oZ8APSwhBZHIfL6-SLRVJ7RQvC4gsEQqFfeGIuAvFGfKQAQkUYSgRGIdxsHg8fwx8EaePBkNSLwAdGAoBAYELNoxQZDnDCiQiYEjECz0QCsaTcaCubkefzBcKkCgxVIJdKSS8gA)).

While there may be room for improving inference for decorators, I don't think this kind of inference is currently feasible.

**Comment by harrysolovay** [comment]
Re-reading this issue, and I agree: this inference would be counter-intuitive. Thank you for the consideration!

**Comment by DmitryEfimenko** [comment]
I keep coming back to the need of this exact functionality for couple years now. Finally I see this issue and the outcome of the discussions is really discouraging! :(

**Comment by Airblader** [comment]
I agree, the reasoning is understandable, but this puts severe limitations on what decorators can be used for. What I find interesting, however, is that given

```
function Decorated<T>(fn: (self: T) => unknown) {
  return (target: T, pKey: string) => {
    return null as any;
  };
} 
```

we get the following expected results:

```
class Test {
  // works (as expected), self is of type Test
  @Decorated<Test>(self => self.a)
  public readonly a = 1;

  // doesn't work (as expected), self is of type unknown
  @Decorated(self => self.b)
  public readonly b = 1;

  // doesn't work, which is a shame as it would at least avoid duplication, but still as expected
  @Decorated<this>(self => self.c)
  public readonly c = 1;
}
```

but, interestingly, passing an incorrect type argument does error and that error mentions the type that it cannot infer:

```
class Test {
  // Argument of type 'Test' is not assignable to parameter of type 'number'.
  @Decorated<number>(self => self.d)
  public readonly d = 1;
}
```

It's interesting that TypeScript is able to reference the type in the error message, but not able to infer said type.

**Comment by thegedus-moonfare** [comment]
It seems TypeScript 5 added this feature, when using the `"experimentalDecorators"`. I have no idea if it also works for standard ES decorators or not

![image](https://user-images.githubusercontent.com/87527102/232474627-b3958406-84a6-43ae-adb2-c199f353945f.png)
