### ISSUE TITLE
Awaited "promise" changes type to void.

### ISSUE THREAD

**Issue by Griffork** [microsoft/TypeScript#37315]
**TypeScript Version:**  3.8.3 (playground) or 3.7 (visual studio)

**Search Terms:**
await promise becomes void not assignable promiselike

**Expected behavior:**
Code compiles successfully.

**Actual behavior:**
Error produced at line 27: `Type 'void' is not assignable to type 'Test'.(2322)`

The language service does infer the correct type for tester even though the compile fails.

**Related Issues:**
None yet found.

**Code**
```ts

class Test implements Promise<void> {
	
	get [Symbol.toStringTag]() {
		return "true";
	}

	protected resolve!: () => void;
	protected reject!: (e: Error) => void;

	private promise = new Promise<void>((resolve, reject) => {
		this.resolve = resolve;
		this.reject = reject;
	});

	then = this.promise.then.bind(this.promise);
	catch = this.promise.catch.bind(this.promise);

	doThing() {
		return this;
	}
}

async function runTest(): Promise<Test> {
	var tester = (new Test).doThing();
	await tester;
	return tester;
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class Test {
    constructor() {
        this.promise = new Promise((resolve, reject) => {
            this.resolve = resolve;
            this.reject = reject;
        });
        this.then = this.promise.then.bind(this.promise);
        this.catch = this.promise.catch.bind(this.promise);
    }
    get [Symbol.toStringTag]() {
        return "true";
    }
    doThing() {
        return this;
    }
}
async function runTest() {
    var tester = (new Test).doThing();
    await tester;
    return tester;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html#code/FAYwNghgzlAEAqBTKAXWBLAtgBzIziAdinAAoBOA9pulIgDwBul6AJgHywDewAkHwHNEaANoBlAJ6YARpTAA6FJTEpy6QgPgQBAXQAUASm59e5YQFdyhWACJV5xDYDcfAL7A+2KikQgfrWDMoOUZEAEIALlhDWABeTmY2F14vSh8-RACzACtfFEjoxCiAUXIqciN42ETWF081RggfWFSaOjjYQkQAd1gKaloGGvY9PSCQxAAaQMRcv0rOHl5eFAALWnlxsFCOrdDklfWoTdm83dO-ZNcDOsOiDrWN1sHFVaJ5aXVWPUfj57obnwQE0QKsHkd5P9EPJgShQR8vj8IVDAXxWJR4OsNDElqYLFZYL8rsB3MBoBJCCBYAAzcyUlDoSjWch0pCoQxRfptBhslCLPiNciE5A+IWxaJdXq8gzydGY9QCQzJCDdCDoNA+VCIcjJMwoSzWTWilyuIA)

**Comment by Griffork** [comment]
This error is infectious in that trying to cast the tester to another type doesn't work, it still gets reported as "void" by the compiler.

**Comment by nmain** [comment]
The error is correct.  Try running the code!  (Well, you'd need to change it so that something resolves the promise first).  An `async function` always calls `Promise.resolve` on its return, which recursively unwraps promise-likes.  `Test` is regarded as promise-like at runtime, so `runTest` will in fact return `Promise<void>`.

**Comment by Griffork** [comment]
Ooooh, I didn't know that an async function always called promise.resolve on it's return values. I'd always been awaiting them because I didn't think that'd be the case :/.

Thanks, is that behaviour written anywhere? I don't remember seeing it mentioned in the announcement blogs.

**Comment by nmain** [comment]
It's not a typescript specific thing, so best to check docs like [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).

Here's a minimal playground example of what you're running into: [Playground](https://www.typescriptlang.org/play/#code/IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AoASACcBTZBCrUssgI2AoC4YAiAdi4BpyZZAAsqETrjiSAbpwgIAtsyoVCAXgB8MGelQATDdri4AzAAZ85AL4BuEtZIlcoSLAIwtxclEwhkMNQgCAA2AeowwADuwKgBcDgE9mS+ECDoIVQAdCHoAOa4QaHI+LYwAPTlMAAOFKgQyCAwFvwwEOgBRDCsHNx8raLinABiSFBomDCO1vhJJEA); typescript's involvement is limited to simply telling you what the actual type of the async function return will be.
