### ISSUE TITLE
Array of a string union type not working when used with type conditionals

### ISSUE THREAD

**Issue by NeekSandhu** [microsoft/TypeScript#37313]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
string, union, conditional ,array
**Code**

[Playground](http://www.typescriptlang.org/play/?ts=3.6.3#code/C4TwDgpgBAclC8UDkBDMYA2ElQD7IFsUA7AcwHsd8lyAnE07AKCdEigA0AeAFQD4EUAN5QARgC4oPANoBdKAF8WbaAHU6AawDOvAYm78A3MvDQAYigCWGHf0EAKHlAgAPYBGIATLVC3BalmRQAPyculCSQgoAlCxMAMbkxH5QAO6S6rTaXDB6wkxQhWKS0qjoWEgANIQMlNU09GTYskxKCUkpAGaSFtY6uYJCBUUA9CO+AI4ArpakpBggUBiBED5TXhC0YsHBw4USUKVomNj1RGR1yHQMza1MQA)

**Expected behavior:**
No squiggly lines under `f.b`
**Actual behavior:**
Squiggly lines under `f.b`

All the types are exact same except the one not working is wrapped in a conditional.

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types

**Comment by jgbpercy** [comment]
> https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types
> 
> > Conditional types in which the checked type is a naked type parameter are called distributive conditional types. Distributive conditional types are automatically distributed over union types during instantiation. For example, an instantiation of `T extends U ? X : Y` with the type argument `A | B | C` for `T` is resolved as `(A extends U ? X : Y) | (B extends U ? X : Y) | (C extends U ? X : Y)`.
> 
> You can disable the distribution by wrapping your type in an array when checking:
> 
> ```
> type Fails<T> = ([T] extends string ? X<T> : {})
> ```

I think that should be `extends string[]` not `extends string`:
```
type Fails<T> = ([T] extends string[] ? X<T> : {})
```
Otherwise the type conditional is just failing... (the `{}` should probably be 'never` to catch this)

**Comment by NeekSandhu** [comment]
@MartinJohns @jgbpercy thanks you guys! @jgbpercy yea `never` is a good idea to keep it strict.
