### ISSUE TITLE
add databases interface to IDBFactory

### ISSUE THREAD

**Issue by fritzschoff** [microsoft/TypeScript#37317]
## Search Terms

indexDB
types

## Suggestion

I would like to add to the IDBFactory interface the `databases` function

## Use Cases

I was encountering an issue when I wanted to delete all the existing indexedDBs on my client application. For instance, if the user signs out, I want delete all the data and I don't want to hard code the name of the databases in the code. So I did something like this:
```
    const dbKeys = await (window.indexedDB as any).databases();
    for (let key of dbKeys) {
      indexedDB.deleteDatabase(key.name);
    }
```

## Examples

in `lib.dom.d.ts`:
```
interface IDBFactory {
...
databases(name: string): IDBDatabase[];
}

interface IDBDatabase {
name: string;
version: number;
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by hikarinotomadoi** [comment]
At this time, this feature seems to be an Editors Draft in w3c.
https://w3c.github.io/IndexedDB/#factory-interface
I'm not sure whether we should introduce it yet.

@RyanCavanaugh 
What is the consensus on this?

**Comment by hikarinotomadoi** [comment]
According to this [guidline](https://github.com/microsoft/TSJS-lib-generator#additions)
> If it's at Working draft the additions available in all three of Firefox, Safari and Chromium

[this feature](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases) isn't supported in FireFox yet, so it doesn't seems to be ready for adding it.

**Comment by Maxstgt** [comment]
what about a `@warning` flag? Firefox might add it in the future?

**Comment by hikarinotomadoi** [comment]
Do you mean using JSDoc comment like this?

```
/** @warning: hello */
interface A{

}
```

I haven't seen declaring type in such way at `lib.dom.d.ts`.

Well, adding types from https://w3c.github.io/IndexedDB and creating a PR won't be such an  effort (10min will do), though I'm not sure they will accept it.
> Changes to this repo can have pretty drastic ecosystem effects, because these types are included by default in TypeScript. Due to this, we tend to be quite conservative with our approach to introducing changes.
https://github.com/microsoft/TSJS-lib-generator#what-are-the-typescript-teams-heuristics-for-prs-to-the-dom-apis

**Comment by Maxstgt** [comment]
yes like JSDoc. Of course if you not doing it like that, then we shouldn't use it like that. 
I will create an issue and PR for that in the w3c repo.

**Comment by hikarinotomadoi** [comment]
Why do you have to create an issue in the w3c repo?
Editor’s Draft for Indexed Database API 3.0 (which includes implementation of IDBFactory#databases) already exists.
https://w3c.github.io/IndexedDB/#factory-interface

The only thing we have to do is to just wait for the Draft to be published as Candidate recommendation or the browsers implementation(FireFox and safari).
Or, if the TS team think this feature can be added to the `lib.dom.d.ts` even it is in Draft stage.

**Comment by Maxstgt** [comment]
ah okay sorry, I misinterpreted your comment!

**Comment by t3chguy** [comment]
This got added

![image](https://user-images.githubusercontent.com/2403652/234679095-77c5b7c6-c9b5-4c50-98c3-3d74512aedc0.png)

**Comment by jakebailey** [comment]
Yep, thanks; this is done.
