### ISSUE TITLE
Regression: Partial properties became undefined instead of optional

### ISSUE THREAD

**Issue by sveyret** [microsoft/TypeScript#37324]
**TypeScript Version:**  3.9.0-dev.20200310

**Search Terms:**
Partial

**Code**

```ts
export interface Messages {
  [key: string]: string
  $: string
}
export type PartialMessages<T extends Messages> = Partial<T> & {
  $: string
}
export function createMessages<T extends Messages>(messages: T): T {
  return messages
}
export const en = createMessages({
  $: 'English',
  welcome: 'Welcome!',
}
export const fr_ca = createMessages<PartialMessages<typeof en>>({
  $: 'Français (Canada)',
})
```

**Expected behavior:**

Should compile. Messages in `PartialMessages` are either complying or absent.

- last tested working version: Typescript 3.7.5
- first tested failing version: Typescript 3.8.2

**Actual behavior:**

Fail in:

```ts
export const fr_ca = createMessages<PartialMessages<typeof en>>(
```

Consider that all messages are present, but may be `undefined`.

    Type 'PartialMessages<{ $: string; welcome: string; }>' does not satisfy the constraint 'Messages'.
      Property 'welcome' is incompatible with index signature.
        Type 'string | undefined' is not assignable to type 'Message'.
          Type 'undefined' is not assignable to type 'Message'.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts on this?

**Comment by MKRhere** [comment]
`Partial<T>` makes property values optional rather than the keys. Even though it seems like a semantic difference, a non-existent property cannot be accessed by `messages.<prop_name>`, while a property with a non-existent value may be accessed to give `type | undefined`. Quick fix would be:

```ts
export type Messages = Partial<{
    [key: string]: string,
}> & {
    $: string
}
```

**Comment by ahejlsberg** [comment]
This is working as intended and is an effect of #35143 (which was in the 3.8 release). Consider:

```ts
// Compile with --strictNullChecks
declare let t: { [key: string]: string, $: string };
declare let s1: { welcome?: string } & { $: string };
declare let s2: { welcome?: string, $: string };

t = s1;  // Error, but wasn't before 3.8
t = s2;  // Error
```

Clearly the two assignments should be checked the same and they are now. Note that neither assignment is an error when `--strictNullChecks` is off.

**Comment by sveyret** [comment]
Thank you @ahejlsberg. So, if I understand, the best way to write what I expect is how suggested by @MKRhere?
I suggest to add this behavior (and the solution) in the « breaking change » list of 3.8…

**Comment by ahejlsberg** [comment]
@sveyret I would probably change the declaration of `Messages` to

```ts
export interface Messages {
  [key: string]: string | undefined;
  $: string;
}
```

**Comment by sveyret** [comment]
Yes, that's what I finally did. Thank you.
Shall I close the issue?
