### ISSUE TITLE
.ts file does not support "?." writing.

### ISSUE THREAD

**Issue by wudi98** [microsoft/TypeScript#37322]
The ts version of my project is 3.8.3。 When I compile, I wile report an error,not support "?."。Error reporting and real code are as follows:
![4B24806D475611FAB9CDE0243F9168FF](https://user-images.githubusercontent.com/47620997/76326648-eed28280-6323-11ea-8f11-f1ac90933b5e.jpg)

![CCE3212170B49C21B7D520101B1D52AF](https://user-images.githubusercontent.com/47620997/76326629-e5491a80-6323-11ea-8981-d93158a8d164.jpg)

Additional information: only ts files are not supported, other suffix files are ok。
I tried to downgrade to version 3.7.5,but it still didn't work.

Please help me, thank you.

**Comment by nmain** [comment]
That screenshot looks suspiciously like a `react-dev-utils` error overlay.  Were you looking for https://github.com/facebook/create-react-app/issues/7431?

**Comment by DanielRosenwasser** [comment]
Sounds like you need to upgrade your version of create-react-app. Is that right @nmain?

**Comment by nmain** [comment]
Yes, assuming that is in fact `create-react-app`, a newer version will suffice.  I'm using `?.` in a `create-react-app` right now.  Here's the relevant documentation:  https://create-react-app.dev/docs/updating-to-new-releases/

**Comment by DanielRosenwasser** [comment]
Keywords: unexpected token optional chaining create react app typescript babel elvis

**Comment by wudi98** [comment]
@nmain @DanielRosenwasser That's great.We got rid of it.It's because of the low version of react-scripts.I updated to version 3.3.1 and it was resolved!Thank you very much!
