### ISSUE TITLE
DefinitelyTyped d.ts files and --target es6

### ISSUE THREAD

**Issue by daniel-shin1104** [Microsoft/TypeScript#3732]
I tried to compile using `--target es6` compiler option and majority of d.ts files from DefinitelyTyped spit out error primarily concerning new module system.

Is there any workaround to this? Am I stuck with `--target es5 --module commonjs` until all other definition files are correctly updated to target es6?

**Comment by mhegazy** [comment]
just out of curiosity, what engine you are using that supports all of the es6 features including modules?
