### ISSUE TITLE
multi index signatures 

### ISSUE THREAD

**Issue by zenHeart** [microsoft/TypeScript#37333]
**TypeScript Version:**  3.8.3

**Search Terms:** index signature 

**Code**

```ts
type ExtendObj<T, Q> = {
  [key in keyof T]: T[key];
 // error
  [key1 in keyof Q]: Q[key1];
};

let foo = {
  foo:1
}
let bar = {
  bar:1
}

let foobar:ExtendObj<typeof foo,typeof bar> = {
  foo:1,
  bar:1
}
```

**Expected behavior:**

foobar can combine two object properties.

**Actual behavior:**

can't find "key1”。ts(2304)
can't find "keyof”。ts(2304)

In [spec 3.9.4 Index Signatures ](https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#394-index-signatures) I find  **An object type can contain at most one string index signature and one numeric index signature.**

So Why we can't use multi-index signature ?

My suggestion we can offer better error for this situation 
like `Can't declare duplicate index signature ts(xxxx)!` or add  multi-index signature feature.

**Playground Link:** 
<https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=16&pc=2#code/C4TwDgpgBAogHsCA7AJgeQEYCsA8AVAGigEUA+KAXigG8AoKBqAbQGsIQoBLJKNkAewBmUPAF0AXCNbtRAbnoNpIAIxcefISQkklyubQC+82gBsIwKIP79KNBQyv9Jyw6fNQMAQwBOtuow8fZ1c3C0cvb0l4RFRMXFBITUciBIhNCPIqf0ZHZwJ7QMioFwMgA>

**Comment by MartinJohns** [comment]
You're not defining an index signature, you're creating a mapped type. An index signature would look like: `[key: string]: Type`, while a mapped type contains the `in` keyword.

You can easily create the desired result by using an intersection type or a conditional type:

    type ExtendObj<T, Q> = {
        [key in keyof T]: T[key];
    } & { [key in keyof Q]: Q[key] };
    
    type ExtendObj2<T, Q> = {
        [key in (keyof T | keyof Q)]: key extends keyof T ? T[key] : key extends keyof Q ? Q[key] : never
    }

> In spec 3.9.4 Index Signatures I find An object type can contain at most one string index signature and one numeric index signature.

Forget the spec. TypeScript has no specification. The document you refer to is heavily outdated, it hasn't been updated in over 3 years.
