### ISSUE TITLE
Error:(2, 28) TS2339: Property 'querySelector' does not exist on type 'Node'.

### ISSUE THREAD

**Issue by tcstory** [Microsoft/TypeScript#3734]
I have the following code:
**test.html**
```
<!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title></title>
</head>
<body>
    <div id="container">
        <div id="box"></div>
    </div>
    <script src="test.js"></script>
</body>
</html>
```

and the ts file **test.ts**
```
var box = document.querySelector('#box');
console.log(box.parentNode.querySelector('#box'));
```

and i got the error.
`Error:(2, 28) TS2339: Property 'querySelector' does not exist on type 'Node'.`
could someone tell me what's wrong with that?

the version of typescript is 1.4

**Comment by rielz** [comment]
`querySelector` is only defined on `Document`, `DocumentFragment` and `Element` but not on `Node` which you are getting with `parentNode`.

You can use `parentElement` instead, that should fix the problem.

**Comment by tcstory** [comment]
@rielz thanks

**Comment by tcstory** [comment]
@rielz but, if `querySelector` is not defined in Node,why i can access  `querySelector`  in Node ? the type returned by  `parentNode` is Node ,isn't it?
 sorry,i am a novice

**Comment by tcstory** [comment]
I found the following sentence in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentNode)
**parentNode is the parent of the current node. The parent of an element is an Element node, a Document node, or a DocumentFragment node.**

here is my test 
```
var ul = document.querySelector('ul')
undefined
ul.parentNode.toString()
[object HTMLDivElement]"
```

**Comment by RyanCavanaugh** [comment]
I think in practice any `parentNode` is going to have a `querySelector` method, but the W3 spec does not define the API in such a way that this is guaranteed to be true (N.B. for people who say this is all we need to do! :wink:). Since we generate lib.d.ts from a specification, that kind of information is unfortunately lost. You'll need to add a type assertion depending on what you know the type of the parent is.
