### ISSUE TITLE
Implicit 'it' parameter name

### ISSUE THREAD

**Issue by irissoftworks** [microsoft/TypeScript#37341]
Kotlin, for example, supports the implicit 'it' function parameter name for functions with a single parameter: 

`ints.filter { it > 0 }`

I find that this removes a lot of verbosity from these commonly used expressions and makes code a little bit cleaner. 

Not knowing if this is feasible [or even desirable] for Typescript, considering it's not [afaik] on the JS roadmap, I would still love to see it or at least check if someone has any ideas for equivalent syntax that could be applicable to Typescript. 

Not knowing much about the tsc's internals, I would assume a similar syntax applicable to Typescript would be sugar coating something like:

`ints.filter(n => n > 0)` 

where the type of 'it' would be the same as inferred for n. This would of course simply ignore further parameters if they exist in the function signature.

Couldn't find duplicates [maybe I missed any?], so decided to raise it for awareness. Anyone has any thoughts on this ?

**Comment by RyanCavanaugh** [comment]
This would be something for TC39 to add to JS. Please use the Suggestion template.

**Comment by irissoftworks** [comment]
updated the issue to use the template.
