### ISSUE TITLE
Object.observe() Generating a warning

### ISSUE THREAD

**Issue by piraveen** [Microsoft/TypeScript#3735]
The method Object.observe(object, callback) generates a warning during the build.

**Comment by mhegazy** [comment]
`Object.observe` is a proposed ES7 feature and not a standard JS feature that sported by all engines. this is why it is not defined in lib.d.ts. Interfaces are open ended, thus you should be able to augment the `Object` constructor definition by adding it to `ObjectConstructor`; to define the function, in one of you files add:

```ts
interface ObjectConstructor {
     observe(o: any, callback: Function): any;
}
```

**Comment by piraveen** [comment]
@mhegazy My bad, sorry for the wrong feed. And thanks for the definition example :+1:

**Comment by mhegazy** [comment]
glad it helped.
