### ISSUE TITLE
Add support for inferring tuple types generated from using the spread operator on const assertions

### ISSUE THREAD

**Issue by btoo** [microsoft/TypeScript#37357]
## Search Terms

spread tuple const assertion

## Suggestion

I've noticed that when using the spread operator with `as const` variables, TypeScript loses tuples' index-to-type information, contrary to object literals, which get their structure (key-to-type) copied over:
```typescript
const a = { b: 1, c: 2 } as const
/**
 * correctly inferred as
 * const e: {
 *  readonly f: 3;
 *  readonly b: 1;
 *  readonly c: 2;
 * }
 */
const e = { ...a, f: 3 } as const

const g = [1, 2] as const
/**
 * inferred as
 * const h: readonly (1 | 2 | 3)[]
 * but would prefer
 * const h: readonly [1, 2, 3]
 */
const h = [...g, 3] as const
```
[(reproduction link)](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAhjAvDA3jARgLhgRgDQzDYBMMAvvBIeNALABQA9AFTMMzPUBOXApsFAA2ATxgBLMADNePXgBNK7TqEixe2FEpgw+cOeBExJ2AMwBuLTt56DorLgv0O23frCGiMYo+dkljBhVoGF4kVBgAOii4AmMYE3JKalUGQJpYAHMwgG18LwBdJKCoBhY2J04JaVkFOAgtYpgAC2xXWxgAChwYAB8vXviASmz8rXQAV1gAdxBxwQUABz5qhvTm1us3Q1yCYgITUYqA+kamnKiIjP3CuuS6eiA)

Is this due to the same underlying issue present in https://github.com/microsoft/TypeScript/issues/34589?

## Use Cases

This would allow us to "extend" tuple types

## Examples

```typescript
const workweekDays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'] as const
const weekendDays = ['Saturday', 'Sunday'] as const

/**
 * inferred as
 * const days: readonly ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[]
 * but would prefer
 * const days: readonly ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
 */
const days = [...workweekDays, ...weekendDays] as const
```
[(reproduction link)](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=11&pc=1#code/MYewdgzgLgBA7iATgazgUzcgIgQwJ4QwC8MA2gOQCy4AJvuQDQzkAqArmhHXo8wOpoaYTt16sAFm0Rd6TcgDFEAS1EBdGDkKhIUALAAobdHgZkaMDVwFiZcgGUcUKaLl22F+us0wje-QYB6ACoggxggmCUwADM0RERBDQgwiN8YbggALhgEnBpwABs8GAAKACJqDzwymAAfGDL2EXwa+rKBIWbquoaWSWluVobFFRaesocnREHxtyqygEpSVRSYACM2WAQ2ApoYAAcE2MRVtIzs3PywIrIK2hamRo4ZaseO4Reyx76pT8eRwaPSbOB4NOaDFb6cIBAxnfCEEikAB0KIQKHQmCsECYKKRGLMFixXi04GgBiAA)

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
@ahejlsberg this feels more like a bug to me; the intended behavior here seems unambiguous. Thoughts?

**Comment by ahejlsberg** [comment]
Looks like a duplicate of #33783. This is a design limitation that we could consider lifting.

**Comment by somebody1234** [comment]
if this is a duplicate, should this be closed?

**Comment by btoo** [comment]
this is fixed with https://github.com/microsoft/TypeScript/pull/36861! closing now
