### ISSUE TITLE
No completions in string literal index on mapped type

### ISSUE THREAD

**Issue by LorenzHenk** [microsoft/TypeScript#37364]
**TypeScript Version:**  3.8.0-dev.20200131

(Works fine with `3.8.0-dev.20200130`)

**Search Terms:** type suggestion intellisense autocomplete generic

**Code**

```ts
type Foo = {
  bar: string;
};

type SpecialFoo = Readonly<Foo>;

type Test = Foo["bar"]; // suggestions work
type Test2 = SpecialFoo[""]; // suggestions do not work
```

**Expected behavior:**
Using generic types, that use a syntax similar to
```ts
type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};
```
should still have suggestions.

**Actual behavior:**

When using generic types that utilize the syntax above, the suggestions do not work anymore.

**Playground Link:** https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200311#code/C4TwDgpgBAYg9nKBeKBvAUFKAjAhgJwC4oBnYfASwDsBzAbnQF8H1RIoBlSAYwtwBt4iFACUIuACZwq-EAB4hAPhZtoAFQhlksBAG0ARHnz6Aug1VQNZAEzauEXgKEHTDIA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/28662

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh It seems the bug caused by the following crash

>  Cannot read property 'kind' of undefined
> TypeError: Cannot read property 'kind' of undefined
> ....

Maybe makes sense to add the label `"Crash"`?

**Comment by RyanCavanaugh** [comment]
We usually only use `Crash` for commandline compile crashes or total LS failure, since caught LS exceptions are comparatively much lower impact.

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Got it, thanks for the clarification.
