### ISSUE TITLE
Assertions considered identical even when object is modified

### ISSUE THREAD

**Issue by stephanedr** [microsoft/TypeScript#37366]
**TypeScript Version:**  3.8.3, Playground/Nightly

**Search Terms:** asserts condition always false

**Code**

```ts
declare function assert(value: boolean): asserts value;

let a = [];
assert(a.length == 0);
a.push(0);
assert(a.length == 1); // This condition will always return 'false' since the types '0' and '1' have no overlap.(2367)
```

**Expected behavior:**
No error.

**Actual behavior:**
Error in comment.

**Playground Link:** [Playground Link](http://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200311#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAKANygmRAC54AjHHCEKVASkaJLMLxqtEAG4AsACgp7DAXgBeeAG0AuhMl9SFKADp2qAOYYAFoqUAGLhr0AHZIRPkrN4tvJ6DxswqUBGaykgA)

**Related Issues:** 
No.

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/36975

My search terms were array push narrowing

**Comment by stephanedr** [comment]
OK I thought it was linked to assertions.

**Comment by nmain** [comment]
Assertions use the same underlying flow control understanding as the rest of narrowing, and the core problem is the same:  Typescript has no knowledge of the fact that calling `arr.push()` mutates and should reset narrowings on `arr.length`, nor even a way to track these sorts of cross property dependencies.

**Comment by stephanedr** [comment]
Then to me, TS should consider that all method calls can mutate the object.

**Comment by stephanedr** [comment]
Whatever the object, not only arrays.
