### ISSUE TITLE
type flow should detect access before initialization from another switch branch

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#37363]
## Search Terms
variable hoisted hoisting type flow switch case

## Suggestion
Prevent access to local variables from a different switch case branch.

## Use Cases
We had the following code:(minimal example).
````ts
switch (5 as number) {
    case 4:
        let localVar = "foo";
        break;
    case 5:
        localVar = "bar";
        break;
}
````
Compiled to es5 we got `var localVar = "foo"` and the variable was hoisted. No problems in runtime.
After switch to es6 we go native `let` (hooray) and a runtime exception:
`ReferenceError: Cannot access 'localVar' before initialization`

IMO TypeScript should have saved us from this error.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sbdchd** [comment]
I think this might be related to https://github.com/Microsoft/TypeScript/issues/19503

**Comment by HolgerJeromin** [comment]
Thanks for finding this dupe.

**Comment by IlanFrumer** [comment]
I found a case that is probably related to this bug, but it depends on the **strictNullChecks** mode.

code on [playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygCigTwA4oBciARAIwmIA+pATCQJSIDeAsAFCKJoDuMUEABaJs+FEzacuiCAEM0KUhUIdp0gDYooiALbo0sgOaKAvKTRw9UQTDCGAdI-skA3KrWIATlpCekEBAtNe3U4Q0xmXX0jRQBfBjcpLjkFOhIVJOlvKF9-QLhg0PDIvTQDY0R4xK5Yjlr2DlQMTHJGRKasEnoEjiA)

*detected* when  `"strictNullChecks": true,`

![image](https://user-images.githubusercontent.com/3116399/108757460-88ee0380-7552-11eb-9d00-0f3d609c6a9f.png)

*not detected* when `"strictNullChecks": false,`
![image](https://user-images.githubusercontent.com/3116399/108757684-d4081680-7552-11eb-869c-95f7de89b5d1.png)
