### ISSUE TITLE
error TS5042: Option 'project' cannot be mixed with source files on a command line.

### ISSUE THREAD

**Issue by indraraj26** [microsoft/TypeScript#37379]
**TypeScript Version:**  Version 3.6.3

**Search Terms:** Property 'entries' does not exist on type 'ObjectConstructor'.
**Docs:** That i followed for compile :- https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Code**

```ts
class TestObject {
    constructor() { }

    getData(obj: any): any {
        // Property 'entries' does not exist on type 'ObjectConstructor'.ts(2339)
        return Object.entries(obj).map(([key, value]) => {
            console.log(key, value)
        })
    }
}

const test = new TestObject();
console.log(test.getData({ id: 1, name: 'Alexa' }))
```

**Expected behavior:**
It should compile

**Actual behavior:**
Getting this error TS5042: Option 'project' cannot be mixed with source files on a command line.
```
tsc --project tsconfig.json app.ts
error TS5042: Option 'project' cannot be mixed with source files on a command line.
```
**Playground Link:** 
Repo : https://github.com/indraraj26/object-entries-typscript

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #27379

**Comment by FernandoRogelin** [comment]
It worked for me https://github.com/okonet/lint-staged/issues/468#issuecomment-605102567
