### ISSUE TITLE
Cannot compile when derived class has at least one #private field and constructor has statements before super()

### ISSUE THREAD

**Issue by kchow1985** [microsoft/TypeScript#37371]
**TypeScript Version:**  3.8.3

**Search Terms:**
super(), #private field, derived class, overload constructor

**Code**
```ts
export class A {
    constructor() {

    }
}

export class B extends A {
    #field: any;

    constructor() {
        1;
        super()
        this.#field = "any";
    }
}
```

**Expected behavior:**
should compile

**Actual behavior:**
compiler complains with 
"A 'super' call must be the first statement in the constructor when a class contains initialized properties, parameter properties, or private identifiers.(2376)"

whereas if I use the "private" keyword instead of "#" it works perfectly fine

```ts
export class B extends A {
    private field: any;

    constructor() {
        1;
        super()
        this.field = "any"; // no complaints
    }
}
```

**Playground Link:** 
http://www.typescriptlang.org/play/?ts=3.9.0-dev.20200311#

**Related Issues:**

**Comment by a-tarasyuk** [comment]
```ts
class A { }
class B extends A {
    private a = 1;

    constructor() { // Error TS2376
        1;
        super();
        this.a = 0;
    }
}
```
[Playground](https://www.typescriptlang.org/play/index.html?ts=Nightly#code/MYGwhgzhAECC0G9oF8BQrSRgIWgUwA8AXPAOwBMZ4FVo7oAHAJwEsA3ME6MaAXmgCMAbnT1owAPakIRJgFdgRCUwAUASkS0x9YVu3QIchnlVqR+ukQAWLCADoe-AAzn6aZEA)

```ts
class A { }
class B extends A {
    private a: any;

    constructor() { // There is no error, it is a bug
        1;
        super();
        this.a = 0;
    }
}
```
[Playground](https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200312#code/MYGwhgzhAECC0G9oF8BQrSRgIWgUwA8AXPAOwBMZ4FVo7oAHAJwEsA3ME6MALm9ICeAbnT1owAPakIRJgFdgRCUwAUASkS0x9AIwjt9CHIZ5Va-QehEAFiwgA6MNAC80AAwW6aZEA)

cc @RyanCavanaugh

**Comment by a-tarasyuk** [comment]
```ts
class A { }
class B extends A {
    #a: any;
    constructor() { // error TS2376
        1;
        super();
        this.a = 0;
    }
}
```

```ts
class A { }
class B extends A {
    private a: any;
    constructor() { // there is no error
        1;
        super();
        this.a = 0;
    }
}
```

```ts
class A { }
class B extends A {
    private a = 1;
    constructor() { // error TS2376
        1;
        super();
        this.a = 0;
    }
}
```

@RyanCavanaugh Which example has the correct behavior?

**Comment by a-tarasyuk** [comment]
```ts
// The first statement in the body of a constructor (excluding prologue directives) must be a super call
// if both of the following are true:
// - The containing class is a derived class.
// - The constructor declares parameter properties
//   or the containing class declares instance member variables with initializers.
const superCallShouldBeFirst =
    some((<ClassDeclaration>node.parent).members, isInstancePropertyWithInitializerOrPrivateIdentifierProperty) ||
    some(node.parameters, p => hasModifier(p, ModifierFlags.ParameterPropertyModifier));
```

It seems expected to avoid checking super in a constructor if a class member does not have initializer 

```ts
class A { }
class B extends A {
    private a: any; // The class member without an initializer, so `superCallShouldBeFirst` is negative.
    constructor() {
        1;
        super();
        this.a = 0;
    }
}
```


```ts
class A { }
class B extends A {
    #a: any; // The class member is the PrivateIdentifier, so `superCallShouldBeFirst` is positive.
    constructor() {
        1;
        super();
        this.a = 0;
    }
}
```

cc @sandersn @RyanCavanaugh

**Comment by Jamesernator** [comment]
This also applies to non-private class fields with `useDefineForClassFields`. As such this should work as well (as it already does in Chrome/Node):

```ts
class Bar {}

class Foo {
  #x = 12;
  y = 30;

  constructor() {
    console.log("Hello!");
    super();
  }
}
```

**Comment by sandersn** [comment]
Given how limited `superCallShouldBeFirst` is, this error is still "correct", even for target: "esnext", useDefineForClassFields: true. Consider:

```ts
class Bar {}

class Foo {
  #x = 12;
  y = 30;
  constructor() {
    console.log(this.#x, this.y);
    super();
  }
}
```

Which is treated identically by the error, and does indeed error at runtime.

However, it may be the case that `checkThisBeforeSuper` is adequate and the `superCallShouldBeFirst` error is completely unneeded. I'm going to disable it and see how the baselines change.

**Comment by sandersn** [comment]
I opened a PR to remove the superCallShouldBeFirst error entirely, but mainly so I could get the experts on class semantics to review it. I think we would have done this years ago if it were possible.
