### ISSUE TITLE
TSC creates an invalid triple slash reference in declarations

### ISSUE THREAD

**Issue by elevatebart** [microsoft/TypeScript#37375]
**TypeScript Version:**  3.6.2 - 3.8.3

declarations, reference, invalid, optimisations

**Code**

[Repro Repo](https://github.com/elevatebart/ts-ref-issue)

Clone the repo, install using yarn (or npm) and run the `compile:types` script

**Expected behavior:**

`lib/client/rsg-components/slots/index.d.ts` should be 

```ts
/// <reference types="react" />
export declare const DOCS_TAB_USAGE = "rsg-usage";
declare const _default: (config?: any) => {
    docsTabs: {
        id: string;
        render: import("react").FunctionComponent<{
            props: {
                methods: import("react-docgen").MethodDescriptor[];
            };
        }>;
    }[];
};
export default _default;
```

**Actual behavior:**

Instead there is a line added here line #2 that complains as invalid.

```ts
/// <reference types="react" />
/// <reference types="lib/typings/dependencies/react-docgen" />
export declare const DOCS_TAB_USAGE = "rsg-usage";
declare const _default: (config?: any) => {
    docsTabs: {
        id: string;
        render: import("react").FunctionComponent<{
            props: {
                methods: import("react-docgen").MethodDescriptor[];
            };
        }>;
    }[];
};
export default _default;
```

I traced the issue back to 3.6.2. In 3.5 it uses the relative path of the file which does not break.

**Playground Link:**

**Comment by AviVahl** [comment]
Maybe related to https://github.com/microsoft/TypeScript/issues/35343

**Comment by sheetalkamat** [comment]
The root cause of this is #39695
