### ISSUE TITLE
Arrow function allows return of different type with explicit void declaration as the return, normal function declarations though throws an error

### ISSUE THREAD

**Issue by rdsedmundo** [microsoft/TypeScript#37386]
**TypeScript Version:**  3.8.3

**Search Terms:**
arrow function allows a return of different type with explicit void declaration

**Code**

```ts
const a = () => 3;

const f1: () => void = () => {
  // all good
  return a();
};

function f2(): void {
  // Type 'number' is not assignable to type 'void'. ts(2322)
  return a();
}
```

**Expected behavior:** both return statements should have the ts(2322) error.

**Actual behavior:** only the function declaration has the ts(2322) error, even though both functions have the same type.

**Playground Link:** http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=9&pc=2#code/MYewdgzgLgBAhjAvDAFASiQPhgZgNwBQBoksAZgIwBcqGi2AbiAJYAmStWMA3gTDACcAplACuAsPHSEAvoQJlRYYFGbgYZAEzoaTNjz6CR4yXGkEZQA

**Related Issues:** #20006

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.

**Comment by rdsedmundo** [comment]
Would you mind clarifying the reasoning? I found it strange considering that the final type of both functions is exactly the same: `() => void`. I tried to search about it in the documentation but didn't find anything. Thanks.

**Comment by AnyhowStep** [comment]
`void` means "there may or may not be a value here. Don't use it"

**Comment by rdsedmundo** [comment]
That's all true @AnyhowStep, but it doesn't explain why in the function declaration it throws and in the arrow function it doesn't.

**Comment by AnyhowStep** [comment]
The same reason why we have excess property checks in some places, and don't in others.

A tradeoff between correctness, usability, and intent.

**Comment by rdsedmundo** [comment]
In my opinion, this:
```
const f: () => void = a();
```
Should be disallowed yes, if `a` is a function that has a different return type. If you want this assignment to work, then you either use inference, or you use `() => any` and accept any function type. What I'm understanding here, in other words, is that declaring `() => void` is pointless.

But opinions aside in what's correct or not here, it's super strange that the function declaration behavior is different. It should've been at least consistent. For the user (developer) point of view, both are functions and behave exactly the same.

This definitely looks like related to #20006, as this behavior seems very opaque.
