### ISSUE TITLE
customElements.define needs parameterless constructor

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#37396]
**TypeScript Version:**  3.9.0-dev.20200313

**Search Terms:**
customElements.define custom Element

**Expected behavior:**
No error

**Actual behavior:**
error: Argument of type 'typeof AB' is not assignable to parameter of type 'CustomElementConstructor'.

**Code**
```ts
export class AB extends HTMLElement {
  constructor(aa: string) {
    super();
  }
}

customElements.define("a-b", AB);
```

<details><summary><b>Output</b></summary>

```ts
export class AB extends HTMLElement {
    constructor(aa) {
        super();
    }
}
customElements.define("a-b", AB);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play?ts=next&ssl=1&ssc=1&pln=7&pc=34#code/KYDwDg9gTgLgBAYwDYEMDOa4EEBCdQzAB2AJpgBIAqAsgDICiSwAtsfAN4BQciERaMKAFcEMaAAoUKAFxwBUAJZEA5gEo4XHjzRCwwKONUBubnAC+nC5wRCBEZoxZs0AOhLAAZkuDiARCgBaACNfABpsHGMgA)

**Comment by jogibear9988** [comment]
It is a valid scenario that I create the instance only in code, so no parameterless constructor is needed.

But I still need to register the component, so the browser could dis.play it

**Comment by MartinJohns** [comment]
Duplicate of #36965. Search term: `customElements`

**Comment by jogibear9988** [comment]
duplicate
