### ISSUE TITLE
JSDoc namespace type definitions. Named import/export not working.

### ISSUE THREAD

**Issue by ernestostifano** [microsoft/TypeScript#37398]
**SEE EDITS BELOW!**

**TypeScript Version:**  3.9.0-dev.20200314

**Search Terms:** JSDoc not exported. JSDoc type not available. "X" has no exported member "Y".

**Code**

./file-a.js (Exporting)
```
/**
 * @typedef {number} MyClass.arg
 */

/**
 * @classdesc Description.
 */
export class MyClass {
    /**
     * @constructs MyClass
     * @param {MyClass.arg} arg - Arg.
     */
    constructor(arg) {
        this.arg = arg;
    }
}
```

./file-b.js (Importing)
```
import {MyClass} from './file-a';

/**
 * @function myFunction
 * @description Description.
 * @param {MyClass.arg} arg - Arg.
 * @returns {number} Returns.
 */
function myFunction(arg) {
    return arg * arg;
}

myFunction({});
```

**Expected behavior:**
`MyClass.arg` type should be available to be used in JSDoc in `file-b.js`. Generated declaration files should export all namespace's JSDoc types.

**Actual behavior:**
`error TS2694: Namespace '"/some-path/file-a".MyClass' has no exported member 'arg'.`

**Playground Link:**  Not possible because multiple files involved.

**Related Issues:** 
There are similar issues about type export/import problems, but none specifically addresses the above JSDocs problem.

As seen in the following screenshots, JSDoc type is correctly exported, imported and analysed by WebStorm, but not by TypeScript.

Please note that the above code generates correct documentation using `jsdoc` command. And it respects JSDoc specifications.

**Screenshots:**
<img width="1128" alt="Screenshot 2020-03-14 at 19 19 55" src="https://user-images.githubusercontent.com/34403992/76688242-660d5c80-662b-11ea-8403-ef79796f8e03.png">
<img width="1128" alt="Screenshot 2020-03-14 at 19 20 49" src="https://user-images.githubusercontent.com/34403992/76688246-6a397a00-662b-11ea-824a-1512825abfb0.png">

**IMPORTANT EDIT:**
Adding a default export to `file-a.js` like `default export MyClass;` adds the following statement to the output declaration file:
```
export declare namespace MyClass {
    export type arg = number;
}
```
So it seems that the problem is with named exports. However, it is still not being imported and correctly interpreted in `file-b.js`.

BUT, if I use default import in `file-b.js` like `import MyClass from './file-a';` everything works as expected!

So, definitely, bug is with named import/export! :)

I think that a fix should be considered to be fully compliant with the spec. If not, the current behaviour remains a little confusing.

**FINAL EDIT**
Using `export {MyClass};` at the end of the file instead of placing it in the class declaration works too! Now the thing becomes trivial. Considering namespaces as objects/members, exporting the class reference should export all its members (?).

**Comment by sandersn** [comment]
Looking at `MyClass` in file-a vs file-b shows that it gets the correct namespace-class merge in file-a, but the imported alias in file-b only gets the class. I'm not sure whether this is a failure of alias resolution or of the implicit-export code for `@typedef`. It's probably the latter because this non-class example also fails:

```ts
// @filename: file-a.ts
/** @typedef {number} Dotted.Name */
export var dummy = 1

// @filename: file-b.ts
import { dummy } from './file-a'
/** @type {Dotted.Name} - should work because implicit-exports go into the globals */
var dot1
/** @type {import('./file-a').Dotted.Name} - maybe should also work */
var dot2
````

**Comment by sandersn** [comment]
Note: I tested this back to 3.7 and it's not a regression -- a recent one at least.

**Comment by sandersn** [comment]
There actually isn't *any* implicit-export code for ES modules, although you can use import types:

```js
// @filename: file-a.ts
/** @typedef {number} Monad */
export var dummy = 1

// @filename: file-b.ts
import { dummy } from './file-a'
/** @type {Monad} - doesn't work */
var dot1
/** @type {import('./file-a').Monad} - works */
var dot2
```

So I think the real bug here is that `/** @type {import('./file-a').Dotted.Name} */` doesn't work.

**Comment by sandersn** [comment]
Yep, `Dotted` ends up binding through `declareSourceFileMember`, used for locals, not `declareModuleMember`, which exports jsdoc type aliases. `declareModuleMember` might need a bit of code added to support ModuleDeclarations, which is what `Dotted` is.

**Comment by sandersn** [comment]
#40980 fixes the import type reference; the un-imported type is not intended to work in an ES module.
