### ISSUE TITLE
default value for function argument (for js)

### ISSUE THREAD

**Issue by heavyk** [microsoft/TypeScript#37397]
**TypeScript Version:**  3.9.0-dev.20200313

**Search Terms:**

**Expected behavior:**
the default value should be type any.
additionally, it can also infer from the code that the return value is also an array and that the first param is a number.

**Actual behavior:**
naïvely assumes the init_value is a number:
`declare function empty_array(n: any, init_value?: number): any`
when it should be:
`declare function empty_array(n: any, init_value?: any): any`
or even:
`declare function empty_array(n: number, init_value?: any): Array`

**Related Issues:**

**Code**
```ts
function empty_array (n, init_value = 0) {
  var array = Array(n)
  while (n-- > 0) array[n] = typeof init_value === 'function' ? init_value(n) : init_value
  return array
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function empty_array(n, init_value = 0) {
    var array = Array(n);
    while (n-- > 0)
        array[n] = typeof init_value === 'function' ? init_value(n) : init_value;
    return array;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play?ts=next#code/GYVwdgxgLglg9mABAUwLYAcoE8D6BDAJwLy0QAowAaRGMGKHANzwBsRlEBeRABgEpEAbwBQiRMwKJCxUtwCCREhT6jEAdwAWMFhwoBaPYgB8vAdJIBtMAF0uibOmRxgNOg2ZsOnb4gDkoSFgEX0QAfld6JlZ2ZUQALgj3aORVAmQoEAIkcyxhAF8gA)

**Comment by heavyk** [comment]
a similar behaviour can be found with this code:
```ts
export function on (emitter, event, listener, opts = false) {
  // ...
  if (typeof opts === 'boolean' || opts.passive) {
    console.log('broken')
  }
}
```

**Comment by RyanCavanaugh** [comment]
This is the intended inference. You can add JS Doc as needed to clarify.

**Comment by heavyk** [comment]
adding the jsdoc comment now produces two errors:
```ts
/**
 * @param {int} n - number of items to put in the array
 * @param {any | function} init_value - initialisation value for each of the values
 */
function empty_array (n, init_value = 0) {
  var array = Array(n)
  while (n-- > 0) array[n] = typeof init_value === 'function' ? init_value(n) : init_value
  return array
}
```

now, it gives another error saying `Parameter 'n' implicitly has an 'any' type.`

however, the goal is to get typescript compiling the js without errors before beginning the transition.. I don't want to have to change all their filenames and add a bunch of types to the project just to get it compiling.
