### ISSUE TITLE
Control flow in function affects widening of return type

### ISSUE THREAD

**Issue by NiGhTTraX** [microsoft/TypeScript#37393]
**TypeScript Version:**  3.8.3

**Search Terms:** control flow return type widen literal

**Code**

```ts
function infersLiterals() { // return type is "foo" | "bar"
    if (Math.random() > 0.5) return 'foo';
    else return 'bar';
}

function infersString() { // return type is "string"
    return 'foo';
}
```

**Expected behavior:** Either the return types are inferred as `"foo" | "bar"` and `"foo"` respectively, or both as `string`.

**Actual behavior:** The function that has some simple control flow infers string literals, the one that doesn't infers widened strings.

[**Playground Link**](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=2#code/GYVwdgxgLglg9mABDMwCmAnAzgGRlTAQwBssAKASkQG8AoRB5YRMgWUKgAsA6DQsACZwAtpUQA+RAAZuAVioY0UEBiQByYHDhqA3PUZpSaRIuWrEagEaEMu2gF9atUJFgJkqTFgDKUDCgBzMTpGEyUVdU1tPXsgA)

**Comment by RyanCavanaugh** [comment]
The relevant distinction here is whether you return two different values or not. A function returning only one string value is assumed to not be a roundabout way to hardcode a constant and is more likely a placeholder value.

In general, TS producing two different results for two different programs is not a per se defect.
