### ISSUE TITLE
Invalidate unnecessary 'as any' and '@ts-ignore'

### ISSUE THREAD

**Issue by steida** [microsoft/TypeScript#37391]
TypeScript type system is not easy. Errors are often undecipherable. There is no shame to use `as any` or `@ts-ignore` because YOLO is the real thing. Especially after days spent hunting compiler bugs.

But TypeScript and its ecosystem is smarter day by day. Some old `as any` or `@ts-ignore` maybe are not required anymore. 

TypeScript should detect it.

**Comment by IllusionMH** [comment]
Not sure if first one is doable or reasonable, however second point us already implemented.
Use `//@ts-expect-error` https://github.com/microsoft/TypeScript/pull/36014

**Comment by AlCalzone** [comment]
For the first one you might want to try the wotan linter.

**Comment by steida** [comment]
@IllusionMH Thank you!
