### ISSUE TITLE
The export type of namespace presents the wrong typing alert 

### ISSUE THREAD

**Issue by LenChang** [microsoft/TypeScript#37408]
**TypeScript Version:**  3.7.2

**Search Terms:**
namespace, typing

**Code**
```ts
type Nullable<T> = T | null

export namespace ProfileFields {
   type name = string;
   type WHYYY = string | null;
   type id = string | null;
  // export type WHYYY = Nullable<string>;
  // export type id = Nullable<string>;
}

export interface Profile {
  name: ProfileFields.name;
  WHYYY: ProfileFields.WHYYY;
  id: ProfileFields.id;
}

export type General = Pick<Profile, 'WHYYY' | 'name' | 'id'>
```

**Expected behavior:**
```ts
type General = {
WHYYY: ProfileFields.WHHYY
name: ProfileFields.name
id: ProfileFields.id
}
```

**Actual behavior:**
```ts
type General = {
WHYYY: ProfileFields.WHHYY
name: ProfileFields.name
id: ProfileFields.WHHYY
}
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.7.5#code/C4TwDgpgBAcgrgGwQQwEYIgHgCoD4oC8U2UAPlAHaIIBQNEAHmAPYBOwlyAthAM5jIAxtAAKrZgDMAlhgBiUiAgAmvKAG8aULYxbsooSJx6EovYKykUA5gG5N2pmw4HoAdQASATW8mzF62SU1HZaUDpO+uDQUkq+5pZWgVRIIVAA9GlhjnouUB7enibwSGgYmH4JuKkZWbrOUVAxRdSlWBXWVTQAvnThepbAEKwSQqLi0hjq9hTcEABcUGKSMhDyiioAdDM8qfneC0sTqwrKvBt7nqkxB+Mra6cbMXY9NDXYABbQAOIQFEPICEihgBQw4UlUAHdxAEAIT0bL1Qw-P6sAEmERSQQAa0whxWABooAByC5EwJE7YQMnkIkxIm4IA)

**Comment by RyanCavanaugh** [comment]
Two type aliases for the same type are considered interchangeable (because they are), and declaration emit can choose arbitrarily between two equivalent types when finding a name to emit.

**Comment by LenChang** [comment]
But it make me confused.  I adjust the type of WHYYY & id to **Nullable<string>**, and it make code more readable.

Has any better recommended method to use it ?

**Comment by RyanCavanaugh** [comment]
#37444  should improve this
