### ISSUE TITLE
Type transformations do not use concrete types

### ISSUE THREAD

**Issue by aloifolia** [microsoft/TypeScript#37401]
So, I am not quite sure if there is already a way around this behaviour or if this is a feature request.

My code makes heavy use of type computations via recursive conditional types and mapped types. These types generate stuff like

```ts
// VSCode shows that Generated resolves to { a: { b1: { c: 42 }, b2: { d: { e:  42}}}}
type Generated = ComplicatedTransformation<SomeType> 
```

This works until I make use of these generated types by transforming them even further. E.g., there is

```ts
type OmitNever<T> = Omit<T, SelectKeys<T, never>>;
```

As soon as I feed the generated type `Generated` to `OmitNever` the compiler shows the infamous error message _Type instantiation is excessively deep and possibly infinite_ (https://github.com/microsoft/TypeScript/issues/31619). 

Now I was wondering why the compiler does not use the concrete type that VSCode shows when the cursor hovers over `Generated`. Instead it seems to recalculate the whole (or part) of `ComplicatedTransformation`.

Is there a way to tell the compiler "use the generated type as is and just forget how this type was generated"? If not, would that be a useful addition (in my eyes it looks like that, but maybe I am missing something crucial)?

**Comment by AnyhowStep** [comment]
There are many ways to get around that error. And all of them are situational, and some of them unintuitive.

**Comment by RyanCavanaugh** [comment]
Type aliases are generally "just" aliases and behave as if they are inlined at their use sites; this is important to make other scenarios work.

If you have a case where it looks like the instantiation process *should* be finite and shallow, we can investigate as a one-off, but in general the error means what it says. At some point it's best to switch to a `.d.ts` generation process if your types are extraordinarily complex.
