### ISSUE TITLE
Should create unique symbols when creating properties on `module.exports`

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/TypeScript#37404]
## TypeScript Version:
`3.9.0-dev.20200315`

## Search Terms:
- module.exports unique symbol property
- module.exports unique symbol
- exports unique symbol property
- exports unique symbol

## Code
```ts repro
// @target: ES2015
// @module: CommonJS
// @allowJs
// @checkJs
// @noEmit
// @filename: index.js

exports.customSymbol = Symbol("custom");
//                ^?
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?checkJs=true&allowJs=true&target=2&module=1&noEmit=true#code/PTAEAEBcEMCcHMCmkBcoCiBlATABgIwCsAUCBALYD2AJgK4A2iaAwpeVQHYBSmpY40evUoB3LgGc+EAMYALRNIDWEqeA6V05AJaRVAMy2MO0ck1BaO1RAA8AdACtJxGwAdKsSONvTa4yG0wAT3IAI0p6UABeUCDQ8IAKACIfPzZEgEoAbilQXLz8goA9AH5iIA)

## Expected behavior:
```ts
// some-module.d.ts
export const customSymbol: unique symbol;
```

## Actual behavior:
```ts
// some-module.d.ts
export var customSymbol: symbol;
```

## Playground Link:
https://www.typescriptlang.org/play?module=1&useJavaScript=true#code/KYDwDg9gTgLgzgOgMYFc4wgWwMoE9MBGEANgAQC8pehJAFAESrpb0CUA3AFBA

## Related Issues:
- <https://github.com/microsoft/TypeScript/issues/37403>

**Comment by RyanCavanaugh** [comment]
@rbuckton @weswigham what do we think should happen here?

**Comment by weswigham** [comment]
We don't make unique symbols because we see the position as mutable, ie,
```ts
exports.customSymbol = Symbol("custom1")
// later
exports.customSymbol = Symbol("custom2")
```
is perfectly acceptable.

In theory, we could recognize
```js
Object.defineProperty(module.exports, "prop", {
  writable: false,
  value: Symbol("prop")
});
```
as immutable and be appropriately `unique`, but we currently do not.

**Comment by ExE-Boss** [comment]
But **TypeScript** complains when you re‑assign a property on `module.exports` with:
> TS2323: Cannot redeclare exported variable 'customSymbol'.

**Comment by weswigham** [comment]
Hm. I didn't realize we issued the  `Cannot redeclare exported variable 'customSymbol'.` error - I'm surprised we do, actually, considering there's no such limitation for cjs modules. Afaik we shouldn't be.
