### ISSUE TITLE
Warn about Partial in union where is another object

### ISSUE THREAD

**Issue by steida** [microsoft/TypeScript#37407]
Because TypeScript does not have exact types, suddenly the result of such a union can accept any object, which is pretty tricky.

**Comment by MartinJohns** [comment]
Please respect the issue template for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and for [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md).
