### ISSUE TITLE
Top Level "for await" not supported, but should be

### ISSUE THREAD

**Issue by kitsonk** [microsoft/TypeScript#37402]
**TypeScript Version:**  3.8.3

**Search Terms:**

top level for await

**Code**

```ts
const arr = [ Promise.resolve() ];

for await (const item of arr) {
  item;
}

export {};
```

**Expected behavior:**

To compile without issue.

**Actual behavior:**

```
A 'for-await-of' statement is only allowed within an async function or async generator. (1103)
```

In the Stage 3 proposal, https://github.com/tc39/proposal-top-level-await/pull/133 was specifically added to address that `for await` is valid.  Therefore the TypeScript implementation is incomplete.  While it was implemented in V8 separately, V8 now supports it (as well as potentially other engines).

**Playground Link:** [link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwTAvDA2jACgkBbASwgFMA6BYiEAGwDdiAKAShgF0BuAKE4DMRk4AdzgFYDUJFijieGCB7wkLAN6cYMaXi4BfbsQAeAB36xl2rkA)

**Related Issues:** #25988

**Comment by hikarinotomadoi** [comment]
I've created a PR that should fix this issue.
Could someone check for it please?
#37424

**Comment by kitsonk** [comment]
@DanielRosenwasser @RyanCavanaugh any chance of some action on this.  PR has been open since 4+ months with no review.

For us, the side effect of this is that when we "bundle" modules in Deno, and use SystemJS as the target, the emitter doesn't realise the module requires TLA and so it breaks the bundle.

**Comment by dandv** [comment]
Adding another search term, the error code: `TS1103`.

**Comment by hikarinotomadoi** [comment]
I thought [this](https://github.com/microsoft/TypeScript/pull/37424) was already merged an years ago.🥱
