### ISSUE TITLE
Should preserve unique symbols when re‑assigning `module.exports`

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/TypeScript#37403]
## TypeScript Version:
`3.9.0-dev.20200315`

## Search Terms:
- object property preserve unique symbol
- module.exports preserve unique symbol

## Code
```ts repro
// @target: ES2015
// @module: CommonJS
// @allowJs
// @checkJs
// @noEmit
// @filename: index.js
const customSymbol = Symbol("custom");
//              ^?

// This is a common pattern in Node’s built-in modules:
module.exports = {
	customSymbol,
	//        ^?
};
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?checkJs=true&allowJs=true&target=2&module=1&noEmit=true&allowSyntheticDefaultImports=true#code/PTAEAEBcEMCcHMCmkBcoCiBlATABgIwCsAUCBALYD2AJgK4A2iaAwpeVQHYBSmpY40evUoB3LgGc+EAMYALRNIDWEqeA6V05AJaRVAMy2MO0ck1BaO1RAA8AdACtJ0yh3GRQ02m7aYAnuQAjSnpQAF5QP0DggAoAIk9vcliASgBuKVBMrOysgD0AfmIpABVZLXFzCugPNk5QAAdoSEhEWA5zdoA5GkRATAIKgNpDSABaC1AqOkZxFGJJhkRbG3rKWEgK8IBvYgBIBMgffyD6ABpdshzMguIAX3SgA)

Also, the following requires a `// @ts‑ignore` comment, but otherwise works:

```ts
// some-module.js
const customSymbol = Symbol("custom");

// This is a common pattern in Node’s built-in modules:
module.exports = {
	/** @type {typeof customSymbol} */
	// @ts-ignore
	customSymbol,
// 	~~~~~~~~~~~~ TS2322: Type 'symbol' is not assignable to type 'unique symbol'.
};
```

## Expected behavior:
```ts
// some-module.d.ts
declare const customSymbol: unique symbol;
declare const _default: {
	customSymbol: typeof customSymbol;
};
export = _default;
```

## Actual behavior:
```ts
// some-module.d.ts
declare const _default: {
	customSymbol: symbol;
};
export = _default;
```

## Playground Link:
https://www.typescriptlang.org/play?module=1#code/MYewdgzgLgBMCu0QFsDKBPZAjEAbGAvDBtngBQBECSyFAlANwCwAUAKYAeADiAE6xEA3qxii4iKChI5cAGlYBfZiyA

## Related Issues:
- <https://github.com/microsoft/TypeScript/issues/23263>
- <https://github.com/microsoft/TypeScript/issues/37404>

**Comment by ExE-Boss** [comment]
Also, the following requires a `// @ts‑ignore` comment, but otherwise works:

```ts
// some-module.js
const customSymbol = Symbol("custom");

// This is a common pattern in Node’s built-in modules:
module.exports = {
	/** @type {typeof customSymbol} */
	// @ts-ignore
	customSymbol,
// 	~~~~~~~~~~~~ TS2322: Type 'symbol' is not assignable to type 'unique symbol'.
};
```

**Comment by ExE-Boss** [comment]
Looks like this got fixed at some point in **TypeScript 4.1** with the changes to `module.exports` handling.

**Comment by weswigham** [comment]
Yeah, https://github.com/microsoft/TypeScript/pull/42655 probably got this as a drive by?

**Comment by ExE-Boss** [comment]
Note that this breaks if you do:

```ts repro
// @target: ES2015
// @module: CommonJS
// @allowJs
// @checkJs
// @noEmit
// @filename: index.js

// This is also a common pattern in Node’s built-in modules:
module.exports = {
	customSymbol: Symbol("custom"),
	//        ^?
};
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?checkJs=true&allowJs=true&target=2&module=1&noEmit=true#code/PTAEAEBcEMCcHMCmkBcoCiBlATABgIwCsAUCBALYD2AJgK4A2iaAwpeVQHYBSmpY40evUoB3LgGc+EAMYALRNIDWEqeA6V05AJaRVAMy2MO0ck1BaO1RAA8AdACtJUgCqyt48x+ihpbTqAAHaEhIRFgOcwiAORpEQEwCDwAjWkNIAFoLUCo6RnEUYmyGRFsbAMpYSA8AXlAAb2IASGlacUg2TABPckTKejRO7t6ACgAiZta2EYBKABpGslBFpdAAPQB+YgBfAG5iIA)
