### ISSUE TITLE
Fixing `>` character in JSX text should have a "fix all in file"

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#37409]
We introduced a breaking change in #36636 so that `>` in JSX text would become an error as per the JSX spec:

```
Unexpected token. Did you mean `{'>'}` or `&gt;`?
```

I hit this several times on the new website's `src/templates/pages/download.tsx` even though the code was just working. Users shouldn't have to fix them one-by-one, so it'd probably be a good idea to auto-fix them all.

**Comment by nmain** [comment]
Could this fix choose `{'>'}` or `{">"}` intelligently based on other quote usage in the file?

**Comment by orta** [comment]
I think we already have checks for that sort of thing

**Comment by a-tarasyuk** [comment]
@orta I tried to add a test/fix for the `Fix all` QF and got the following error message
> No available code fix has the expected id. Fix All is not available if there is only one potentially fixable diagnostic present

The code which I tried to test
```ts
let a = <div>>{"foo"}</div>;
let b = <div>>{"foo"}</div>;
let c = <div>>{"foo"}</div>;
```

Are there any special cases that need to be considered when processing scanner errors in QF services?

> I think we already have checks for that sort of thing - so it's likely, yes

You are right, however, it seems that the current service doesn't use quote preferences 
 https://github.com/microsoft/TypeScript/blob/b8baf4804370a4405f7f123db5bbb4530297982b/src/services/codefixes/fixInvalidJsxCharacters.ts#L39

**Comment by andrewbranch** [comment]
@a-tarasyuk I worked on the fix-all changes that generate that message somewhat recently; seems like there might be a bug there in `codeFixProvider`. I’m happy to help take a look if you need a hand.

**Comment by a-tarasyuk** [comment]
@andrewbranch Thanks. I've created PR, with the one change in the `codeFixProvider`.
