### ISSUE TITLE
await should be treated like .then

### ISSUE THREAD

**Issue by maximilianMairinger** [microsoft/TypeScript#37415]
Await statements are not considered asynchronous

**TypeScript Version:**  3.9.0-dev.20200315

**Search Terms:**
overlap await then
**Code**

```ts
(async () => {
    let x = 0

    if (x === 0) {
      await Promise.resolve()
      
      if (x === 1) { // Error

      }
    }
})()
```

`x` could have changed during the await statement. (No error)

**Expected behavior:**

This should be trated like a (`then`) callback.

**Actual behavior:**

It is treated like synchronous code

**Playground Link:** http://www.typescriptlang.org/play?ts=next#code/BQQwzgngdgxgBMAlHAvAPjgbwFBz3AGwFMAXOAD1TgAZtd8BLAMwUpXZuR33xAHcQDMgAUATgHsAtgzBEAdKKJhxBAG5Ek9HlsYtgbDgEYudHngC+Oy+cRIgA

**Related Issues:** N/A

**Comment by nmain** [comment]
Duplicate.  See #27900, #9998 for background.
