### ISSUE TITLE
for await and nullish coalescing causes name collision

### ISSUE THREAD

**Issue by rynti** [microsoft/TypeScript#37418]
It seems I stumbled on a bug in TypeScript when I used a for await loop containing two nullish coalescing operations inside an if condition. When targeting ES2017 or less, TypeScript uses _b as a temporary variable holding the iterator, calling _b.next() for every iteration. However, in the if condition _b is overwritten as another temporary variable. See the playground link to see the generated JS code, the bug happens inside the outerIterator function.

**TypeScript Version:** v3.9.0-dev.20200315

**Search Terms:** for await async iterable iterator name collision next nullish coalescing

**Code**

```ts
async function* getIterator(): any {
    yield { member: 1 };
    yield { member: 2 };
    yield { member: 3 };
}

async function* outerIterator(): any {
  for await (const row of getIterator()) {
    // This line causes a name collision with by setting a variable `_b`,
    // which is also used to hold the iterator above:
    if ((row.member ?? null) === (row.member ?? null)) {
      yield row;
    }
  }
}

async function main() {
  console.log("main()");
  for await (const row of outerIterator()) {
    console.log(row);
  }
}
main().catch(e => console.error(e));
```

**Expected behavior:**
In the console:
```
main()
{ member: 1 }
{ member: 2 }
{ member: 3 }
```

**Actual behavior:**
```
main()
{ member: 1 }
TypeError: _b.next is not a function
    at outerIterator_1 ...
```

**Playground Link:**
[Playground Link](https://www.typescriptlang.org/play/?downlevelIteration=true&ts=next#code/IYZwngdgxgBAZgV2gFwJYHsICoYHMCmyAksvgE7DLpkAUAlAFwzARgwDeAUDDzGKvgA2AEw4wAtvnEAjckwCMMAL4Bubr35DR7CVNlkmAJmVrefASLGSZcmAGYTnJZ06hIsRCgzYY6BKTISckpqeiYWNi4eOGpmAHdgVGQYGihMEGSydDjfODxCIIoqWjo6DnUeAHpKmAAVAAtUEBhBVAh8GChgBBB8ZuAYCGBJTvRBVpBvGDik+phpNl7kNAhcZhgAN2AyVGBpQQ6AAwB9aUOAGgqYaunGqDmm5kEQdBge-FEqGHqxz-qOpLBYrMaToDb4BhXVB5Gg0LJxAB01n0MAA-KjBghxmUALx4lLwpF6chojEQLGCUrlMw8TSWeGmXjOHjOZyucDQeBIKBoTASRIQejU0YQF4HBGCdC4GgAInEAvoMrojJiZHiiWSqXSmWyuV8-nIhRCJTKUV4aVFY3wEqlcOyyvUrM48ra9ARXWQ9xoHRxAD4RWLreQsrR8KU1EA)

**Related Issues:**
Not sure, but maybe #28849 is related.

**Comment by Kingwl** [comment]
Seems template variables has conflict...
