### ISSUE TITLE
IntelliSense - auto-detection regression when using Javascript Language Service

### ISSUE THREAD

**Issue by thernstig** [microsoft/TypeScript#37413]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.3

**Search Terms**
- auto import
- auto imports
- jest
- javascript

---

- VSCode Version: 1.4.30 (User)
- OS Version: Ubuntu 16.04.5

This might be a regression, but I am not sure. According to https://github.com/microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#-automatic-acquisition-of-type-definitions anything in package.json should download a the proper type from @types into a local cache, which it does perfectly fine into `.cache/typescript/3.8/node_modules/@types/jest/`

In a file I then have this:

```javascript
beforeAll(async () => {
  await page.goto(`https://www.whatismybrowser.com/`);
});
```

Previously the `beforeAll()` did properly give IntellieSense, but recently it does not. I do not have a `jsconfig/tsconfig.json` in the directory where the above code resides.

If I manually install `"@types/jest": "25.1.4"` in `package.json` the IntelliSense starts working fine.

So from what I can gather, even though JavaScript Language Service properly downloads @types/jest to the cache, VS Code does not pick it up for some reason for the globals such as `describe()` and `it()`. I _believe_ this worked before (potentially in 1.42.X but not in 1.43.0 ? Just guessing.)

**Comment by mjbvz** [comment]
Do you have an imports for jest in your code?

**Comment by thernstig** [comment]
No, not before the update nor after.

**Comment by RyanCavanaugh** [comment]
The intended behavior for both performance and UX reasons is that you only see auto-imports for things listed in your `package.json`. If you want to use something from a package, it should be in your `package.json` -- whatever indirect dependency you rely on is not guaranteed as part of your direct dependencies' API contracts.

**Comment by thernstig** [comment]
@RyanCavanaugh `jest` is listed in package.json as `"jest": "25.1.0",` should I then get IntelliSense for e.g.`describe()` in files? I investigated exactly why this happens. This is the story:

Add this in package.json and install:

```json
  "devDependencies": {
    "babel-eslint": "8.2.6",
    "eslint": "5.9.0",
    "eslint-config-airbnb-base": "13.1.0",
    "eslint-config-prettier": "3.3.0",
    "eslint-plugin-import": "2.14.0",
    "eslint-plugin-jest": "23.0.3",
    "eslint-plugin-jsdoc": "15.12.1",
    "eslint-plugin-prettier": "3.0.0",
    "jest": "24.9.0",
    "prettier": "1.17.1",
    "expect-puppeteer": "4.3.0"
  },
```

Add a file with this:

```javascript
it('has a title', async () => {
  const title = await page.title();
  expect(title).toBe('Foo');
});
```

`it` will have IntelliSense. Now remove `"expect-puppeteer": "4.3.0"` from `package.json` (and reinstall with `npm reinstall` if wanted). Suddenly the globals related to Jest such as `it` does not get IntelliSense anymore. I find this strange because I do have the `jest` package still listed in the dependencies. I don't understand this at all. The package `expect-puppeteer` has nothing to do with Jest https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/expect-puppeteer/index.d.ts

**Comment by thernstig** [comment]
@RyanCavanaugh Do you have any idea why the above scenario would work?
