### ISSUE TITLE
`T[Extract<keyof T, string>]` should be assignable to `T[keyof T]`

### ISSUE THREAD

**Issue by ngolin** [microsoft/TypeScript#37412]
**TypeScript Version:**  3.8.3

**Search Terms:** No.

**Code**

```ts
function keyOf<T, K extends keyof T>(
    map: T,
    val: T[K]
): K {
    for (const key in map) {
        if (map[key] === val) return key;
    }
    throw Error();
}
```

**Expected behavior:**
Compiles fine.

**Actual behavior:**
Compiles error.

**Playground Link:** 
https://www.typescriptlang.org/en/play?ssl=6&ssc=30&pln=6&pc=9#code/GYVwdgxgLglg9mABAawKYE8DywA8AVAGkQGlFUAPKVMAEwGcUM5hE8A+ACgChFfEBbAIYAHAFysCPPgDdBAG3F4A2sQC6XAJTjSAbym9gcAE6IOEBHSiN0iGEiHCNiPX1e2WHB0rTpViALyBiLJyTkaoUCBGSD4A3PqIAL4JUAAWRnAA7ogAokYZRhwa8clAA

**Related Issues:** 
Not Found.

**Comment by RyanCavanaugh** [comment]
Per the definition of the comparability relation, these values aren't related "directly enough" for TS to consider them comparable. The `return` statement is also suspect; this function as written could easily produce an unsoundness.

**Comment by ngolin** [comment]
This resolves the problem.
```ts
function keyOf<T>(
    map: T,
    val: T[keyof T]
): keyof T {
    for (const key in map) {
        if (map[key] === val) return key;
    }
    throw Error();
}
```
