### ISSUE TITLE
3.7.5 => 3.8.3 introduces breaking change(and shouldn't)

### ISSUE THREAD

**Issue by rmainseas** [microsoft/TypeScript#37416]
**TypeScript Version:**  3.8.3

**Search Terms:**
1. `Option 'noEmit' cannot be specified with option 'incremental'.`
1. `typescript incremental noEmit`
1. `tsc noEmit incremental`

**Code**
```json
{
  "incremental": true
}
```

```bash
tsc --noEmit
```

**Expected behavior:**

The typescript project should compile successfully (it does under 3.7.5) since 3.7.5 to 3.8.3 is not a semver breaking change the two should be backwards compatible, but aren't. https://semver.org/spec/v2.0.0.html#summary

**Actual behavior:**

```
tsconfig.json:15:5 - error TS5053: Option 'noEmit' cannot be specified with option 'incremental'.

15     "incremental": true,
       ~~~~~~~~~~~~~


Found 1 error.
```

**Playground Link:** 

n/a (typescript playground doesn't have the option to configure the `tsc` command or set the `incremental` option in `tsconfig.json`

**Related Issues:** 
n/a

**Comment by MartinJohns** [comment]
> since 3.7.5 to 3.8.3 is not a semver breaking change

TypeScript does not follow SemVer: https://github.com/microsoft/TypeScript/issues/14116#issuecomment-280410804

**Comment by rmainseas** [comment]
...oh. 

...Well that's "fun".

**Comment by MartinJohns** [comment]
There are **good** reasons to not follow SemVer. :-) You can read about them in #14116.

Also you can check out #36917, which mentions why `noEmit` and `incremental` is not allowed/supported together.

**Comment by rmainseas** [comment]
Yeah, thanks. I'm reading the thread just now...the only problem is that I'm pinned to 3.5.2 and getting 3.8.x.


If typescript doesn't follow semver...is there an explanation somewhere of what the version numbers actually mean? Do they mean anything at all?
