### ISSUE TITLE
Type predicate does not work as expected on Object

### ISSUE THREAD

**Issue by yuval-gilboa** [microsoft/TypeScript#37425]
**TypeScript Version:**  3.8.3

**Search Terms:**
type predicate object
type narrowing object
type guard object

**Expected behavior:**
Function with type predicate `value is Object` should work the same as type guard `typeof value == 'object'`. In the example below, the type of parameter `p` should be inferred to be `Object` in all four cases.

**Actual behavior:**
The type predicate `value is Object` does not narrow down the type as expected.
In the example below, the type of parameter `p` is wrongly inferred to be `number | Object` in the third case.

Note: this issue seems to be specific only to `Object` or `{}`. For all other types i checked, the type predicate works correctly. I don't know if this is due to type compatibility rules, but in any case it seems inconsistent.

**Related Issues:**

**Code**
```ts
function isObject(value: any): value is Object {
   return typeof value == 'object';
}

function isNumber(value: any): value is number {
   return typeof value == 'number';
}

function test(p: number | Object) {
    if (typeof p == 'object') {
        p  // OK: p is Object
    }

    if (typeof p != 'number') {
        p  // OK: p is Object
    }

    if (isObject(p)) {
        p  // ERROR: p is number | Object
    }

    if (!isNumber(p)) {
        p  // OK: p is Object
    }
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function isObject(value) {
    return typeof value == 'object';
}
function isNumber(value) {
    return typeof value == 'number';
}
function test(p) {
    if (typeof p == 'object') {
        p; // OK: p is Object
    }
    if (typeof p != 'number') {
        p; // OK: p is Object
    }
    if (isObject(p)) {
        p; // ERROR: p is number | Object
    }
    if (!isNumber(p)) {
        p; // OK: p is Object
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAzgeQEYCsCm0AUAbgIYA2IOAXIsWAJ4CU1J5OyKimu0iA3gFCIhAJxxQQwpFDoAHHHGCIWFRAF5ViAORxseKJoDc-AL79+oSLATsAciAC2GHMKJkK1Wo2Zu2qRGAcnYT5BETEJKVl5RWU2dS0Ax2dDEzMLaHgpHBQofBlqRKDEAB9OXWgGEKEhGEV8aTkFRBk1DW1y-UqBap7moQB6fs4AaWoWvy49UKFTaeQ6hui+gEI2wuSuuZ6WxEGRsfYy7ig52Z7axHxUSYIZBk3e6p29gFEAJTe0N4O-deDSm4nHpnaoXfDLVB2JIuO4PR59XZDNCjPoTDqnVJAA)

**Comment by MartinJohns** [comment]
This works as expect. The `Object` type describes functionality that is common to all JavaScript objects, so including `number`. This code is perfectly valid:

    const value: Object = 123;

You should instead use the `object` type.

https://mariusschulz.com/blog/the-object-type-in-typescript#the-object-type

**Comment by yuval-gilboa** [comment]
Thank you for the clarification.
Closing as this is clearly not a bug.
