### ISSUE TITLE
Add mechanism for specifying the type of a function declaration

### ISSUE THREAD

**Issue by BPScott** [microsoft/TypeScript#37433]
## Search terms

function definition type, function expression

## Suggestion

I think it would be useful to add a mechanism for specifying the type of a function definition, i.e a type that defines arguments and a return type like `type Stringifyer = (arg: number) => string;`. This is currently possible by using function expressions but is not possible with function declarations, this feels like a gap that leads to a slightly sub optimal developer experience, as using a function expression results in having to store two types and causes the developer to have to repeat their function names.

### Use Cases

Consider a case where I want export a function that should adhere to a predefined interface. In these examples I'll use a trival `Stringifyer` type as an example but a more concrete use-case would be writing a React component function and wanting to type your function as a [`React.FunctionComponent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80fef0454291a5c8cd70a4fcaae767b4da60314f/types/react/index.d.ts#L518-L524).

This is possible using a function expression as follows:

```ts
type Stringifyer = (arg: number) => string;

// Define the type of the variable
// Pro: Puts the type close to the function name
// Con: Creates two types (one for the const, one for the anon function)
// Con: repetition of function name
export const stringify1: Stringifyer = function stringify1(arg) {
  return arg.toString();
};

// Type assert the function
// Pro: Creates a single type
// Con: The type is far away from the function name
// Con: repetition of function name
export const stringify2 = function stringify2() {
  return arg.toString();
} as Stringifyer;
```

Both of these examples have their faults.

- In both exampels the user is required to repeat the function name as both the variable name and the function name. You could omit the function name but anonymous functions makes debugging harder (and in the case of my React use-case will throw [a linting warning as React expects its components to have a name](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md)).
- The first example creates two types - one for the variable and one for the function, when ideally one would do.
- The second example puts the type far away from the function uuh header(?) - where the function name and arguments are defined.

### Examples

A few ideas for what this could look like:

I'm thinking keeping the type close to the name of the function is useful

```ts
// Pro: Similar to existing convention of `const x: SomeType = /*...*/;`
// Con: I'd expect a function name to be immediatly before the opening ( of the argument list
export function namedDouble: Stringifyer(arg) {
  return (arg * 2).toString();
}

// Pro: keeps the function name next to the argument list
// Con: I think TS convention tends towards having the type after the name when using colons
export function: Stringifyer namedDouble(arg) {
  return (arg * 2).toString();
}

// Pro: keeps the function name next to the argument list
// Consider: Ambiguity with anonymous function declaration with a generic type argument
// e.g. `const x = function<T>() { /*...*/ }
// Consider: Similarity with angle bracket style type asserts for function expressions
// e.g. `const x = <SomeType> function() { /*...*/ } 
export function<Stringifyer> namedDouble(arg) {
  return (arg * 2).toString();
}

// Pro: uses the same style syntax as existing `as` type asserts
// Con: The type is far away from the function name
export function namedDouble(arg) {
  return (arg * 2).toString();
} as Stringifyer
```

Out of these three I'm leaning towards option 3 if there are no parser issues. I don't thiiink there will be as the `function` keyword continues to come first so I guess the parser would know it' is in a function declaration

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ilogico** [comment]
This reminds me of this suggestion: https://github.com/microsoft/TypeScript/issues/34319

**Comment by RyanCavanaugh** [comment]
Duplicate #22063

**Comment by BPScott** [comment]
Thanks for the links @ilogico and @RyanCavanaugh, it seems my searchbar-fu was not strong enough today. 

`function namedDouble(arg) implements Stringifyer {}` is an implementation example mentioned in #34319 that wasn't covered in my statement.

**Comment by offg777** [comment]
Did this functionality ever get added to typescript? I couldn't tell if there was conclusion that was reached on this topic.

I like the following syntax:
```
interface IMyFuntion {
   (arg: number): string
   prop1: string
}
function myFunction(args) implements IMyFuntion {}

**Comment by ilogico** [comment]
@offg777 It wasn't. I suppose you can vote on the linked issues.

**Comment by offg777** [comment]
How do I do that?
