### ISSUE TITLE
type loss within template string

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#37435]
**TypeScript Version:**  3.8.3

**Search Terms:**

**Expected behavior:**
Type should be preserved

**Actual behavior:**
Type is casted as string, which is true because of the backquotes, but false if you consider that the value can only be `foo` due to `const` constraint imbrication.

**Related Issues:**

**Code**
```ts
const FOO = 'foo'
const BAR = 'bar'

type Foo = typeof FOO
type Bar = typeof BAR

type FooBar = Foo | Bar

const I_AM_FOO: Foo = `${FOO}`
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const FOO = 'foo';
const BAR = 'bar';
const I_AM_FOO = `${FOO}`;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAYgeQTAvDA5AMxCdAoUSWAIQEEAlVDAIwEMAnfPKATwAcBTeHK1zkTPCTN2XYg16iBMMuTwjO3EOPpU4PAD4yG8wtBgBJAPqkAskcQIAXEqoADACQBvSwF87QA)

**Comment by RyanCavanaugh** [comment]
Duplicate #33757
