### ISSUE TITLE
Formater no longer normalizes spaces in method signature

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37431]
From https://github.com/microsoft/vscode/issues/92582

**TypeScript Version:**  3.9.0-dev.20200316

**Search Terms:**

**Code**
Run format on:

```ts
class Foo {
    private async         bar() { }
}
```

**Expected behavior:**
The spaces between `async` and `bar` are normalized

**Actual behavior:**
Spaces are left intact

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
