### ISSUE TITLE
Make `Validation Method`s of arguments in function definition

### ISSUE THREAD

**Issue by qtisan** [microsoft/TypeScript#37437]
## Search Terms

advice, function, arguments, validation

## Suggestion

Should Typescript add a feature intended to *Function Arguments Validation*?
In the function definition, argument is able to have a `Validation Method` there. While making a call of it, arguments passed in would be validated in `Validation Method`.

## Use Cases

Frequently, we would define a function by validating arguments at first of body, such as:
```ts
type Person = {
  name: string;
  age: number;
}
function findYoungestPerson(persons: Person[]): Person {
  // ------------ Start to validate arguments -----------------
  if (persons.length === 0) {
    // Or `return null;`, means that we should make the return type `Person | null`.
    // It would be more complex.
    throw new Error('persons should not be empty.');
  }
  // ------------ End validating -----------------
  // In some complex examples, this will make a better performance.
  if (persons.length === 1) {
    return persons[0];
  }
  return persons.reduce(
    (youngerOne, currentOne) => 
      youngerOne.age > currentOne.age ? currentOne : youngerOne
  )
}

findYoungestPerson([{name:'1', age:33}])
findYoungestPerson([]) // In the bussiness logic, it is not allowed.
```

- The case may be not a typical case.
- There is lots of cases in our everyday coding.

## Examples

Should the CASE be this below?

```ts
function findYoungestPerson(
  // Argument `persons` has a `Validation Method` after `~`.
  persons: Person[] ~ ps => ps.length != 0
): Person {
  if (persons.length === 1) {
    return persons[0];
  }
  return persons.reduce(
    (youngerOne, currentOne) => 
      youngerOne.age > currentOne.age ? currentOne : youngerOne
  )
}

// The code below will course (may be runtime):
// Argument Validation Error, see the arguments of function `findYoungestPerson()`.
findYoungestPerson([]); 

```

It may be making a Grammar break, sorry for my crazy idea.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is a runtime feature, not a type system feature

**Comment by qtisan** [comment]
@RyanCavanaugh 
It it a variant of decorator, or dedicated decorator for function arguments.
Sorry, I did not read TypeScript's Design Goals carefully that make the issue out of scope.
Maybe I should submit it to the ES community.
