### ISSUE TITLE
Array.indexOf - searchElement is too Restrictive?

### ISSUE THREAD

**Issue by halfnibble** [microsoft/TypeScript#37434]
**TypeScript Version:**  3.8.3

**Search Terms:**
indexOf, too restrictive, searchElement

**Expected behavior:**
I expect `Array.indexOf()` to allow a `searchElement` with a type that includes and extends beyond the array. E.g. If the haystack is `[2, 3]`, then I expect to the needle could be of type `1 | 2 | 3` and that a value of `-1` would be returned if the needle is `1`.  But I do not expect a compiler error. 

**Actual behavior:**
Compiler error.
Argument of type 'CoolNumbers' is not assignable to parameter of type '2 | 3'.
  Type '1' is not assignable to type '2 | 3'. (2345)

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/29290
https://github.com/microsoft/TypeScript/issues/35257

**Code**
```ts
type CoolNumbers = 1 | 2 | 3;

const B: CoolNumbers = 2;
const C: CoolNumbers = 3;

const A: CoolNumbers = Math.floor(Math.random() * 3 + 1) as CoolNumbers;

if ([B, C].indexOf(A) === -1) {  // <--- Error here.
    console.log('My favorite 2 numbers.');
} else {
    console.log("it's 1");
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const B = 2;
const C = 3;
const A = Math.floor(Math.random() * 3 + 1);
if ([B, C].indexOf(A) === -1) {
    console.log('My favorite 2 numbers.');
}
else {
    console.log("it's 1");
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9nANgOQK4FsBGEBOBnKAXigEYoAfKAJgqgGYBuAKCYGM4A7PYKAIQC5YCFBmz4i1Zuy48Yg+EjRZcBYoxbTuUAILzhSsaqgBZAIbAAFgDoAZogQ4AFGctWcpjgBM46RwEooACp6KABqUgDTAgURZXxmJgBLGyhHAG1eABpYAF0rRK8IAA8AeRtHbQDCaqgAWhIAgG8mKFaoTSQIK3sAc0cAcmMQKBtTADc4HETgaBoOURUrfr9mAF8oCEQ8aGa29s48Tu64PoAiaf6CElOVplWgA)

**Comment by RyanCavanaugh** [comment]
Root cause is #14520

**Comment by halfnibble** [comment]
Thanks for the root cause! I honestly don't understand all the terminology in that issue, but I feel like this is a fairly common use case for indexOf. Please let me know if I'm doing something wrong.

My current workaround is to typecast `A` as `any` to get past compilation errors.
