### ISSUE TITLE
inline type-guard

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3744]
I want to be able to define type guards inline like below:
```typescript
const enum SyntaxKind {
  VariableDeclaration,
  FunctionDeclaration,
}

interface Node {
  kind: SyntaxKind
}

interface VariableDeclaration extends Node {
  varProp: string | number;
}

interface FunctionDeclaration extends Node {
  functionProp: string;
}

function(node: Node) {
  if(node.kind === SyntaxKind.VariableDeclaration): node is VariableDeclaration {
    // node is now a VariableDeclaration
  }
  else {
    
  }
}
```

Multiple inline type narrowing with `&&` operator:

```typescript
function(node: Node) {
  if(node.kind === SyntaxKind.VariableDeclaration && node.varProp.length): node is VariableDeclaration && node.varProp is number {
    // node is now a VariableDeclaration and node.varProp is now a number.
  }
}
```

**Comment by SaschaNaz** [comment]
I would love this.

**Comment by danquirk** [comment]
Seems nice, but it's a bit unfortunate to require each conditional essentially be written twice, with the second one the form the compiler 'understands'.

**Comment by danquirk** [comment]
I see Flow recently added tagged unions that really handle this kind of pattern better

**Comment by tinganho** [comment]
> I see Flow recently added tagged unions that really handle this kind of pattern better:

You're right. But, I guess people need to bookkeep and make the tags unique in Flow, which might not be so scalable? (I don't totally understand their blog post).

**Comment by tinganho** [comment]
Closing this in favor of Flow's type guards.

**Comment by tinganho** [comment]
@danquirk I was thinking about this issue a bit more. I just want to know your thoughts about using an identity operator/modifier as below, so we can declaratively mark one property for type identification:

```typescript
interface VariableDeclaration extends Node {
  id kind: SyntaxKind = SyntaxKind.VariableDeclaration;
}
```

and then just check a property:

```typescript
function(node: Node) {
  if(node.kind === SyntaxKind.VariableDeclaration) {
    // node is now a VariableDeclaration
  }
}
```
I don't think checking a property against a value is so expressive. Because, it is a property of the instance and because it checks against a value and not a symbol of the type. So how about using the `is` operator like below to make it more expressive:

```typescript
function(node: Node) {
  if(node is VariableDeclaration) {
    // node is now a VariableDeclaration
  }
}
```

gets compiled to:

```typescript
function(node: Node) {
  if(node.kind === SyntaxKind.VariableDeclaration) {
    // node is now a VariableDeclaration
  }
}
```
Both `===` and `is` checking is needed. One for anonymous types and one for named types.

And when we want to initialize a new variable with an interface of that type:
```typescript
let: variable: VariableDeclaration = {
  name: "helllo"
}
```
it will automatically set the identity property. And if the variable has no initializer it will not set the identity property.

```typescript
let: variable: VariableDeclaration;
```
And you would need to set it yourself later:
```typescript
variable.kind = SyntaxKind.VariableDeclaration;
```

**Comment by danquirk** [comment]
@tinganho The problem I see is that marking it in the type itself isn't very scaleable. While it may be nice for types that use single values like this (particularly enums) what do you do with types that have more overlap? Ex:

```ts
interface Point2D {
    x: number;
    y: number;
}

interface Point3D {
    x: number;
    y: number;
    z: number;
}

interface Line {
    x: number;
    y: number;
    length: number;
}

function drawGeometry(shape) {
    if(shape is Point2D) { ... }
    if(shape is Point3D) { ... }
    if(shape is Line) { ... }
}
```
What do I tag in each type as the discriminator? A Point2D and a Point3D share x and y but not z, while a Point2D and Line share x and y but not length. If you were doing the type discrimination in the normal JavaScript fashion (via property access) or a TypeScript user defined type guard you would have to encode all these facts (ie ```if(shape.x && shape.y && !shape.length && !shape.z)```). 

The second part of the proposal (the ```is```) operator runs into the usual problems we have with adding expression level syntax. While JavaScript isn't likely to add that operator in the near future if they do then we're in trouble. So we'd need an extremely good reason to add such a feature.

**Comment by tinganho** [comment]
@danquirk How do you deal with if two interface have the same shape?

```typescript
interface PointInAmerica {
  x: number;
  y: number;
}

interface PointInAfrica {
  x: number;
  y: number;
}
```

**Comment by danquirk** [comment]
In that case you are kinda screwed regardless of type guards :)
