### ISSUE TITLE
Provide a quick-fix for non-exported types

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#37440]
In https://github.com/microsoft/TypeScript/pull/36187, @a-tarasyuk wrote up a handy error message for non-exported types. We should provide a quick fix to add the `export` modifier for declarations like this that aren't in `node_modules` and the like.

**Comment by AGMETEOR** [comment]
@DanielRosenwasser / @RyanCavanaugh I can get time and work on this. Quick question, which files generally have the code for Domain "Quick Fixes"?

**Comment by DanielRosenwasser** [comment]
It's all in `src/services/codefixes/`. Make sure you update `src/services/tsconfig.json` to include the new file for the quick fix. One similar code action would be in `fixImplicitThis.ts` which adds a `this.` to `foo` in

```ts
class C {
  foo = 10;
  bar() {
    foo; // oops! needs to be prefixed with `this.`
  }
}
```

**Comment by DanielRosenwasser** [comment]
Sorry, I meant `fixForgottenThisPropertyAccess.ts`!

**Comment by AGMETEOR** [comment]
Thanks a lot :)

**Comment by jjpiv** [comment]
@AGMETEOR Are you still working on this issue? If not, I'm looking for an opportunity to begin contributing. :)

**Comment by AGMETEOR** [comment]
@jjpiv yes, I am working on it

**Comment by AGMETEOR** [comment]
Hello @DanielRosenwasser ,
I seem to be stuck. 

For a file like this,
```
declare function foo(): any;
declare function bar(): any;
export { bar };
```

my approach was to look for the export `declaration` and then try and add `foo` to it. I am thinking there should be a way to get the export statement at the end of the file but I haven't been successful.

I tried using `getDeclarationOfKind(sourceFile.symbol, SyntaxKind.ExportDeclaration);` but that returns undefined. Any ideas on how to I can write my "makeChange" function to actually add the export?

**Comment by AGMETEOR** [comment]
@jjpiv please take this on.

**Comment by davidstellini** [comment]
@jjpiv Did you take this? If not I'd like to take a shot :)

**Comment by Qiyu8** [comment]
I'm working on this issue, currently stuck at getting SourceFile object for `a.ts`, can anybody help me?
```
// @filename a.ts

declare function foo(): any

declare function bar(): any;

export { bar };

// @filename b.ts

import { foo, bar } from "./a";
```

**Comment by AGMETEOR** [comment]
@Qiyu8 I think that information is in the context that's passed to `getCodeActions(context: CodeFixContext)` in the arg object for `registerCodeFix`

**Comment by Qiyu8** [comment]
@AGMETEOR Thanks for your advise, would you mind reviewing the code?

**Comment by AGMETEOR** [comment]
@Qiyu8 I think @DanielRosenwasser is the one that reviews.

**Comment by BenjaVR** [comment]
I assume nobody is working on this at the moment? If so, I would like to take a shot @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
