### ISSUE TITLE
Unable to implement class with protected members

### ISSUE THREAD

**Issue by sviat9440** [microsoft/TypeScript#37447]
**TypeScript Version:**  3.8.3

**Search Terms:**
implement class protected members

**Code**

```ts
class A {
  protected a: string = '';
}

class B implements A {
  protected a: string = '';
}
```

**Expected behavior:**
No errors

**Actual behavior:**
Error: Class 'B' incorrectly implements class 'A'. Did you mean to extend 'A' and inherit its members as a subclass?
  Property 'a' is protected but type 'B' is not a class derived from 'A'.

**Playground Link:**
https://www.typescriptlang.org/v2/en/play?#code/MYGwhgzhAECC0G8BQ1oAcBOB7ALgU2HwBNowAuaCHDASwDsBzaAXmgHI2BuJAXySVCQYAIWg0AtmhB5xeOjhjxkqTLgLFSFKrUYt2XXkiA

**Comment by RyanCavanaugh** [comment]
This is the intended behavior, as noted by the fact that there's a special error message just for it 😉
