### ISSUE TITLE
Inference after if is not applied to function calls.

### ISSUE THREAD

**Issue by Tiagojdferreira** [microsoft/TypeScript#37450]
**TypeScript Version:**  3.7.5

**Search Terms:** if, function, attribute, undefined, optional

**Code**

```ts
function test(aux: {
    foo?: string
}) { 
    if (aux.foo) return aux.foo; // works and foo is string
    if (aux.foo) return strict(aux); // doesn't work
}

function strict(aux: {
    foo: string
}) { 
    return aux.foo
}
```

**Expected behavior:**
Since I checked for the attribute `foo` before passing the variable to the function, the compiler should understand that `foo` is a `string` and not `undefined` when calling the function.

**Actual behavior:**
Error `Undefined is not assignable to string` for using aux variable in the strict function.

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=2#code/GYVwdgxgLglg9mABFApgZygCgIYgB4BciA3gFCIWLBxwD8RGATjGAOakC+AlCYuZTGCIc+AHTU4PRiighGSXHnE0A3PwqDhi5ZMTTZ8xExjQReLmo6lSoSLARGozU4qJlKVGgyct23Xup6MnIKYhKcQA

**Comment by RyanCavanaugh** [comment]
Duplicate #10065

**Comment by Tiagojdferreira** [comment]
Thanks for the quick reply. From what I understood from that issue, this will not be implemented. In your opinion what is the best course of action?  Create a custom guard type to narrow the type of the object?
