### ISSUE TITLE
Ternary operator with precondition does not compile: Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by rijx** [microsoft/TypeScript#37452]
**TypeScript Version:**  3.8.3

**Search Terms:**

possibly undefined

**Expected behavior:**

The code compiles.

**Actual behavior:**

Throws compiler error:

```
error TS2532: Object is possibly 'undefined'.

return a ? a.message : b.message;
```

**Related Issues:**

N/A

**Code**
```ts
type TestType = {
    message: string;
};

function bug(a: TestType | undefined, b: TestType | undefined): string | undefined {
    if (a || b) {
        return a ? a.message : b.message;
    }

    return;
}

console.log(bug({ message: "a is truthy" }, undefined)); // outputs: a is truthy
console.log(bug(undefined, { message: "b is truthy" })); // outputs: b is truthy
console.log(bug(undefined, undefined)); // outputs: a and b are falsy

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function bug(a, b) {
    if (a || b) {
        return a ? a.message : b.message;
    }
    return;
}
console.log(bug({ message: "a is truthy" }, undefined)); // outputs: a is truthy
console.log(bug(undefined, { message: "b is truthy" })); // outputs: b is truthy
console.log(bug(undefined, undefined)); // outputs: a and b are falsy

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ssl=10&ssc=38&pln=5&pc=85#code/C4TwDgpgBAKhDOwbmgXigbwFBV1AtgvAIYDmEAXFIgE4CWAdqQNxYC+rWAZgK4MDGwOgHsGUAEY9SACmJU4iZJCgAfKHwAmELowgaANBPkIkKVeoZadDPQEoqtRqXObtujZhx46XKLNVq4raeeKFQNBDAPDRixFAA-FDEAHSE8CTkUFTiqURkEKyhbFheuBFRMazFWPyi8MIANhDJDcIykjIYBHnkVABEcXTwUMA0PMAAFiB9UGyGrtZ2tsxQAPSrUMLjYOPwVIPDo+NTNXWNza3tUtIL7oZdaRmUUH3iUEMjY5PTs7bLaxstsAdsA9hJ3ocvidagx6k0Wm1pB0bpY3DYDBYrO4-it1pttrt9klLODiBEoFxiA14CAsEA)

**Comment by j-oliveras** [comment]
You can write it as ([playground](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=19&pc=1#code/C4TwDgpgBAKhDOwbmgXigbwFBV1AtgvAIYDmEAXFIgE4CWAdqQNxYC+rWAZgK4MDGwOgHsGUAEY9SACmJU4iZJCgAfKHwAmELowgaANBPkIkKVeoZadDPQEoqtRqXObtujZhx46XKLNueeEFQNBDAPDRixAB0hPAk5KxBbF64Pn7iAdjBeKHhkRKxRGQQSXgpqSFhEQysFfyi8MIANhDRzcIykjIYBMXkVABExFB08FDANDzAABYgg1Bshq7WdrbMUAD0m1DC02DT8FQjYxNTsyBYDQxNre2d0t3SK+6GvXEJlFCD4qPjk9M5gs2LZ1lsdntgAdgEcJH8zoDLtdbm0Ol0pM9LG4bAYLFZ3KCNttdvtDscoMRLHDiKEoFxiM14JcgA)):
```ts
type TestType = {
    message: string;
};

function bug(a: TestType | undefined, b: TestType | undefined): string | undefined {
    if (a) {
        return a.message;
    }
    if (b) {
        return b.message;
    }

    return;
}

console.log(bug({ message: "a is truthy" }, undefined)); // outputs: a is truthy
console.log(bug(undefined, { message: "b is truthy" })); // outputs: b is truthy
console.log(bug(undefined, undefined)); // outputs: a and b are falsy
```

**Comment by RyanCavanaugh** [comment]
Flow control analysis isn't really set up to do multi-level reasoning about things like this
