### ISSUE TITLE
(Set | Array).forEach loses type inference for callback

### ISSUE THREAD

**Issue by iansan5653** [microsoft/TypeScript#37453]
**Code**

```ts
type ListOfNumbers = Set<number> | number[];

function iterates(list: ListOfNumbers) {
  list.forEach(element => {
    element; // has type any
  });
}
```

**Expected behavior:**

The type of `element` should be `number`, because the type of `forEach` should be:
```ts
type ForEachSetOrArray<T> = (current: T, index: T | number, list: Set<T> | Array<T>) => void;
```

*Note*: The type of `index` is not a mistake - `Set` gives the current value twice, while `Array` gives the current index. It's weird.

**Actual behavior:**

The type of `element` is inferred to be `any` and has to be explicitly stated as `number`.

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=9&pln=1&pc=1#code/C4TwDgpgBAMglgZ2AeQGYDkCuBbARhAJwSgF4oBlCYAHgDsd8CA+KAHynr0IG0BdAbgCwAKBGpMtAMbA4Ae1pQ4wQgENlCABQAbRMABcsXWixciASigBvEVCg6kAOlSyCAURWSAFhohaI2CFpgUhZrYVtbX39A4H4oAHp4qE8VYlBIKBVaEBsoAF8zIWE8oA

**Comment by RyanCavanaugh** [comment]
We're only capable of combining contextual types when the source signatures come from the same declaration; making the parameters line up in the first position wouldn't be sufficient here.
