### ISSUE TITLE
tsx files are not compiled by default

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3746]
It seems like when running only `tsc` on the root folder of a project. It doesn't compile all the `.tsx` files. The current behavior is that it compiles all `.ts` files(if not using `exclude` option).

**Comment by mhegazy** [comment]
@RyanCavanaugh this will also happen on the managed VS side. i believe we are filtering on *.ts now.

**Comment by RyanCavanaugh** [comment]
I can't reproduce this. Are you on the latest sources from master?

```
C:\Throwaway\3746>dir

07/06/2015  04:09 PM                17 foo.tsx
07/06/2015  04:09 PM                 3 tsconfig.json

C:\Throwaway\3746>type foo.tsx
var x = 8 * '';

C:\Throwaway\3746>type tsconfig.json
{ }

C:\Throwaway\3746>node \github\TypeScript\built\local\tsc.js
foo.tsx(1,13): error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
```

**Comment by tinganho** [comment]
I was probably not using the latest master. But it works for me now.
