### ISSUE TITLE
Inconsistent reachability with different type annotations

### ISSUE THREAD

**Issue by nprindle** [microsoft/TypeScript#37472]
**TypeScript Version:** Nightly

**Search Terms:** control flow analysis, reachability analysis, never, type annotation

**Code**

```ts
function impossible1(): never {
    throw new Error();
}

const impossible2: () => never = () => {
    throw new Error();
};

const impossible3 = (): never => {
    throw new Error();
}

function foo(): never {
    // impossible1 and impossible2 work here, but not impossible3
    impossible3();
}

// but all seem to have the same type
const x: typeof impossible2 = impossible1;
const y: typeof impossible3 = impossible2;
const z: typeof impossible1 = impossible3;
```

**Expected behavior:**

The three functions with the same type should all behave the same under control flow/reachability analysis.

**Actual behavior:**

Using `impossible3`, which removes the type annotation from the LHS, does not compile, while using `impossible1` or `impossible2` does.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200318#code/GYVwdgxgLglg9mABDAtgBzgZ0zARgGwFMBGACgEoAuRMQgN0ICdEBvAKEU8SgAtG4A7jUJCAoo36MKAbjYBfNmwgJMUZOiw4ChAEzUKiALwA+YQ2aHEBk6w5de-IbTES4U8rLmylKtagzYeEQAzEZWVGZMRqbsXNx8gsIukjLyiqCQsAiIwHBwFNS05rZxAPSl6gFaRMSIAIZgACaVmkG6iAJuANaIPEyEADSIuCBqYHB+GoHawXac-q0zqQps5cOj9fj4iJiEhCjccL11DPGEO3Uo51AAnmiEPmCqiAAe1Lf3cMAt00Q6YQtfiRZMonmobu87oQvj9qoRQpZAXCdCDfIgAF6Qz7fJFtWqIqZw4KyIA)

**Related Issues:** N/A

Other issues exist related to reachability not working as expected, but removing the type annotation like this is a strange way to run into it.

**Comment by RyanCavanaugh** [comment]
See implementation notes in #32695 - the **declaration** of a `never`-returning function needs to have an explicit type annotation to participate in CFA, and `impossible3`'s **declaration** does not have a type annotation (its *initializer* does, which is different).
