### ISSUE TITLE
TypeScript should allow declarations to be compatible with older versions.

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#37478]
## Search Terms

semver

## Suggestion

We would like to use TypeScript 3.8 and emit declaration files compatible with TypeScript 3.4

## Use Cases

Many of our users can't upgrade their TypeScript version because they are using a version mandated by another tool, especially Angular. We want to be able to use the newest TypeScript on out source to gain additional features, but that should be isolated from the outputs of our project that other projects consume.

The particular motivation for this request is that my project upgraded to TypeScript 3.8, which emits property accessors in declaration files. We have multiple reports from users that this broke their builds with TypeScript 3.4 with the message "An accessor cannot be declared in an ambient context.".

## Examples

```json
{
  "compilerOptions": {
    "declaration": true,
    "declarationVersion": "3.4",
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment]
I haven't personally tried it but, https://github.com/sandersn/downlevel-dts

**Comment by RyanCavanaugh** [comment]
See #35016

**Comment by justinfagnani** [comment]
The downlevel-dts tool appears to be written by a TypeScript team member... so it's at least somewhat a recognized problem. Why is it out of scope then?

Combined with TypeScript not following semver and breaking .d.ts changes in minor versions, the current situation leads to some very nasty surprises when we publish what _should_ be a non-breaking change of our project, but it is for TypeScript consumers.

Without this semi-external tool, the only way for a project to be safe is to only upgrade TypeScript minor versions when our project has a new major version. That's not at all a constraint I planned for.

**Comment by RyanCavanaugh** [comment]
We can't solve every problem in the entire TS ecosystem with code written inside this repository. That's what we mean by "out of scope" - we had hoped *someone* would write `downlevel-dts` (since it's fairly straightforward), but we stepped in when that didn't happen.
