### ISSUE TITLE
Missing folder when compiling using outDir flag

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3747]
I have one folder `src` in root path that contains the folders `folder1` and `folder2`. I specify a `outDir` flag to `built`. The compiled output is now skipping the `src` folder under `built`. So it only contains `built/folder1` and `built/folder2` and not `built/src/folder1` and `built/src/folder2`. 

Please clone this repo to check it out:
https://github.com/tinganho/ts-test

This is appearing in the master branch. And I have in other circumstances been able to compile the `src` folder.

**Comment by mhegazy** [comment]
use `--rootdir` to point to the parent directory of `src`

**Comment by tinganho** [comment]
Miss the help section, thanks!
