### ISSUE TITLE
An Interface or Abstract Class Do Not Enforce Proper Implementation in Case of Union Type

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/TypeScript#37474]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** typescript interface union parameter, typescript interface not enforce union parameter

**Code**
```ts
interface I {
    method(param: string | number): void;
}

class C implements I {
    method(param: string): void {
    }
}
```

**Expected behavior:**
An error message like "'C.method': 'param': interface is not implemented properly; cannot convert from 'string | number' to 'string'".

**Actual behavior:**
Successful compilation.

This is _not_ the desired behavior. If we call `method()` with a `C` variable typed `I`, and pass it 
a number, the code will fail.

**Playground Link:** https://www.typescriptlang.org/play/?ts=Nightly#code/JYOwLgpgTgZghgYwgAgJLIN4Chm+QWwjAAsB7AEwAoAHOKOfALmQGcwpQBzZAH2RACu+AEbQAlMwBupYOQDcWAL5YsCADZwWLZAGFkwfNTURC4bemx4CRMlVr0mrdlwnJpszDjzLlQA

This issue is also applied to abstract methods in abstract class.

**Comment by RyanCavanaugh** [comment]
See design notes in #18654 - method-syntax declarations have their parameter types checked bivariantly.
