### ISSUE TITLE
type of Dynamic Property Keys Incorrect

### ISSUE THREAD

**Issue by replac5** [microsoft/TypeScript#37485]
`
interface State {
    user: string;
    pwd: string;
    auto: boolean;
}

function onChangeFactory(field: keyof State, isBool?: boolean) {
    return (evt: ChangeEvent<HTMLInputElement>): void => {
        const value: string|boolean = isBool ? !!evt.target.checked: evt.target.value
        this.setState({
             [field]: value
        })
    }
}
`

field type resolved string, not keyof State

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
