### ISSUE TITLE
Can't access static members in function scope.

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3748]
Am I doing something wrong in below code? or is it a bug?
```typescript
class A {
	public static a: string = "jhuihiuhu";
	public static method() {
	};
}
function f(a: new () => A) {
	a.method(); // error
	a.a = "hej"; // error
}
f(A);
```

Works in babel.

**Comment by RyanCavanaugh** [comment]
The type you wrote, `new () => A`, means "any constructor function for `A`". It does not refer to the *specific* constructor function `A` that also has members on it.

You can write `typeof A` to refer to the actual constructor function `A` that the class defines:
```ts
class A {
    public static a: string = "jhuihiuhu";
    public static method() {
    };
}
function f(a: typeof A) {
    a.method(); // no error
    a.a = "hej"; // no error
}
f(A);
```
