### ISSUE TITLE
empty marker interface narrows down incorrectly to never

### ISSUE THREAD

**Issue by sokra** [microsoft/TypeScript#37489]
**TypeScript Version:**  3.8.3 and below, nightly (2020-03-20) too

**Search Terms:** empty interface

**Code**

```ts
interface A {
    a: number;
    isB(): this is B;
}

interface B extends A { }

let x = {} as A;

if (x.isB()) {
    
} else {
    // x is incorrectly never here
    x.a
}
```

**Expected behavior:**

`x` should be `A`

**Actual behavior:**

`x` is `never`

In a way it kind of make sense as typescript uses structual typing in which B and A are equal, so nothing is left over when B is already covered. But in this case B is used as marker interface without additional properties (see also the real world case linked below).

**Playground Link:** 

[playground link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmRAFcBbAI2gG4c9gBnAIQAoBKIsAC0eV6doBfLFlCRYiFE2QQAHpBAATBmkzJhWADYQwyWcgC8mQfhWpaomMhayAdI1Zs2mOriwmImhimx5kAen89PhVQBAB7KCgIBDBNAE9iCAA3aGQuaAhXPVs4dyA)

All typescript versions available in the playground have this problem.

The code snippet is a reduced version of this real world case: [playground link](https://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAKjgQwM5xugZlCI4BEMAnmAKaoDGUwYMBA3AFBMA2Z8AHnALxwDeAXxTpMAOgAqpMsybAscABScxwVFPIAFZFGQgOZKIoCUxgUziW4TYWVaoy5q3AD0LuNzVxgAO0rQoMkoYVmI4HzIAN0M4AAtDMgsrFTUAVR9gCB8TZkEgA)

**Related Issues:**

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

The types `A` and `B` are absolutely the same. If something is `B`, then it's also `A`, and vice-versa. This works as intended.

**Comment by sokra** [comment]
> The types `A` and `B` are absolutely the same. If something is `B`, then it's also `A`, and vice-versa. This works as intended.

hmm, that's also what I thought. Also see my real world case with the typescript typings:

``` ts
    interface Type {
        isTypeParameter(): this is TypeParameter;
        // ...
    }
    export interface InstantiableType extends Type {
    }
    export interface TypeParameter extends InstantiableType {
    }
```

What would be the correct fix here?

I often see this pattern in the typings:

``` ts
    export interface Declaration extends Node {
        _declarationBrand: any;
    }
```

Does the same makes sense for TypeParameters?

``` ts
    export interface TypeParameter extends InstantiableType {
        _typeParameterBrand: any;
    }
```

**Comment by MartinJohns** [comment]
In general you should not have "empty" types. That's an anti-pattern in languages with structural typing.

The pattern with the branding makes sense if you need to distinguish the types, yes.

https://github.com/microsoft/TypeScript/wiki/FAQ#how-do-i-prevent-two-types-from-being-structurally-compatible
