### ISSUE TITLE
Overlooked "Spread types may only be created from object types" error

### ISSUE THREAD

**Issue by josemigallas** [microsoft/TypeScript#37491]
**TypeScript Version:**  3.8.3

**Search Terms:**
Typescript conditional conditionally spread combine objects
Spread types may only be created from object types

**Expected behavior:**
Regardless of the output or validity of the expression, sometimes I get an error and sometimes I don't. It should always rise an error _Spread types may only be created from object types.ts(2698)_ when trying to merge a non-object.

**Actual behavior:**
The error is not risen when using an optional or boolean type as part of the predicate

**Related Issues:**
I haven't found anything really related to this.

**Code**
```ts
const dictionary = {
    foo: {},
    bar: {}
}

function overlookWithBoolean(flag: boolean) {
    const ok = {
        ...dictionary.foo,
        ...flag && dictionary.bar // No error
    }

    const error = {
        ...dictionary.foo,
        ...false && dictionary.bar // Spread types may only be created from object types.ts(2698)
    }
}

function overlookWithOptional (optional?: 'foo' | 'bar') {
    const ok = {
        ...optional && dictionary[optional] // No error
    }

    const error = {
        ...undefined && dictionary[optional] // Spread types may only be created from object types.ts(2698)
    }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const dictionary = {
    foo: {},
    bar: {}
};
function overlookWithBoolean(flag) {
    const ok = Object.assign(Object.assign({}, dictionary.foo), flag && dictionary.bar);
    const error = Object.assign(Object.assign({}, dictionary.foo), false && dictionary.bar);
}
function overlookWithOptional(optional) {
    const ok = Object.assign({}, optional && dictionary[optional]);
    const error = Object.assign({}, undefined && dictionary[optional]);
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAJgS2FB4CGAnAnjAvDAbwCgZSYAzEEALkIF8AaEsgI01oLqK6PIFcwyVGBggAbgFMMAGyoBrAOoIoACwBCVaRLRgAFOWloA5rRabtYAJSFmpUJFgg5eG2TcwAdF8RD02D5QgTO5kXgGGRjAAZFHwSCh+WB5sGLYwPG720DBSGCAYLsQhpGE+CWCYSYHBxWHkaNIQEtGxZcKVyZhpXDz8guWikjLySqoA8gAO5Q0wuiBT7dIA-LQA5IGrMAA+MKspq9ZFZFmOzvhHIWHz09Itcb4V2ADa14sAut1EaSc5GHkF5zSbjCAjgEnICDAEjgdzaiReC3Q0g+bh6QA)

**Comment by RyanCavanaugh** [comment]
This is intentional. There's a concrete difference between doing something that *always* does nothing and doing something that *sometimes* does nothing.

**Comment by josemigallas** [comment]
I don't understand. Precisely because the expression may be `falsy` the error should be thrown. Cases:
- Expression always returns object -> No error
- Expression may return object OR falsy -> Error, because it can be false (check its value first)
- Expression returns falsy -> Error

**Comment by RyanCavanaugh** [comment]
Spreading in a value that is sometimes a non-object is idiomatic and not a problem.

Spreading in a value that is *always* a non-object indicates a logic error in your code.

This kind of thing is super common; we don't allow `string === boolean` because it indicates a logic error in your code (because it *always* returns `false`), but `string | boolean === boolean` is fine because it *sometimes* returns `true`, *even though* this operation does a superset of comparisions of `string === boolean`.

**Comment by josemigallas** [comment]
OK that makes sense, thanks for the clarification!

**Comment by xgqfrms** [comment]
# `...(obj as object)`

```js
    const columnsShaper = (headers = []) => {
        const columns = [];
        for (const obj of headers) {
            const {
                key,
            } = obj;
            columns.push({
                // ...obj,
                ...(obj as object),
                dataIndex: key,
            });
        }
        return columns;
    };

```

https://stackoverflow.com/questions/51189388/typescript-spread-types-may-only-be-created-from-object-types

**Comment by ackvf** [comment]
https://github.com/microsoft/TypeScript/issues/45066
I am very sad that this is not supported any more. I remember using it in older projects in React very very often.

```ts
function MyComponent({isLoading}: {isLoading: boolean}) {
  const extraProps = { background: 'pink', displayArea: true }

  return <SomeComponent {...(isLoading || extraProps)} />
}
``` 

Now I need to use this instead `{...(isLoading ? {} : extraProps)}`

---

For reference

```ts
interface Data {
    a: number,
    b: number
}

const data: Data = { a:1, b:2 }

const flag1 = true
const flag2 = false
const flag3: boolean = false as boolean

console.log({...(flag1 || data)}) // error
console.log({...(flag2 || data)})
console.log({...(flag3 || data)}) // error

// prints:
// {}
// {a:1, b:2}
// {a:1, b:2}
```


So I was wondering, is there a flag or a workaround for this?
