### ISSUE TITLE
Change signature of Object.keys to return (keyof T)[]

### ISSUE THREAD

**Issue by iansan5653** [microsoft/TypeScript#37495]
This seems like a simple thing, although I know there's probably a reason it's not already like this.

Currently the signature of `Object.keys` is:
```ts
{
  keys(o: object): string[];
}
```

But why not make it more specific?:
```ts
{
  keys<T extends object>(o: T): (keyof T)[];
}
```

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md).

Both issue templates ask you to search for existing issues before opening a new one.

---

This is a duplicate and has been rejected multiple times: https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208, #30314, #13254. #30228, #28899, #28284, #26901, #30749, #31087, #32321, #34498, #35145.

[more info](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript)

**Comment by RyanCavanaugh** [comment]
@MartinJohns I'm becoming worried that listing all the duplicates is resulting in an `O(n^2)` usage of GitHub's storage 😅

**Comment by MartinJohns** [comment]
Considering how often this and similar questions are asked I have absolutely no doubt that Microsoft / GitHub will run of space in no time!
