### ISSUE TITLE
Proposal: Expose collection element's type

### ISSUE THREAD

**Issue by lazutkin** [Microsoft/TypeScript#3749]
I often needed (and I think others do) to get type of element of collection, especially when dealing with collections of complex type. As a workaround I introduce new dummy variable which is assigned with a value of collection element in order to get its type further through the `typeof`. Here is a sample with simple collection of type `number[]`

``` javascript
function test(a: number[]) {
    var dummy = a[0]

    return a.map(mapper)

    function mapper(v: typeof dummy) {
        // some code
    }
}
```

A bad things about this approach is need to introduce new dummy variable, and some unclarified declarations `function mapper(v: typeof dummy)`

So my proposal is to provide some kind of metadata (which is common for C++ STL, boost) in form of exported type properties like `<...container type...>.ElementType`.

Here is not a final syntax, but at least it looks more clear

``` javascript
function test(a: number[]) {
    return a.map(mapper)

    function mapper(v: (typeof a).ElementType) {
        // some code
    }
}
```

**Comment by RyanCavanaugh** [comment]
It'd be good to understand what kind of things are showing up in your code other than `number` that make introducing new syntax preferable to just writing `function mapper(v: number)`.

One alternative approach would be to allow indexing expressions with numeric literals in `typeof` positions. This would allow you to write:
```ts
function fn(x: number[]) {
  type elem = typeof x[0];
  function foo(y: elem) { }
}
```

**Comment by lazutkin** [comment]
Problem I'm talking about arises when we deal with complex types (especially tuples), or when data interface defined inline, like
```
interface Some {
	a: {
		b: {
			c: number
		}[]
	}
}
```

instead of

```
interface Some {
	a: AType
}

interface AType {
	b: BType[]
}

interface BType {
	c: number
}
```

So here an another version of code from previous post:

```
type Collection =[
	{
		a: string
		b: number
	},
	{
		c: {
			inner: number			
		}
	}[]
][]

function extractInner(c: Collection) {
	var a = func1(c.find(...)[1])
	var b = c.map(func2).reduce(func3)
	
	// a lot of code here
	// ...
	// ...
	
	
	function func1(v: Collection.ElementType[1].ElementType) {
		//......	
	}

	function func2(v: Collection.ElementType): Collection.ElementType[0] {
		//......	
	}

	function func3(o: number, v: Collection.ElementType[0]) {
		//......	
	}

}
```

**Comment by lazutkin** [comment]
@RyanCavanaugh I think that allowing indexing expression with numeric literals in would be concise and good solution.

**Comment by ander-nz** [comment]
While the array type is known to be `number` in the example given, the type would be unknown in the following example:
```js
var data = [1, 2, 3].map(v => {
  return { raw: v, square: v * v };
});
type DataItem = typeof data[0];
```

**Comment by lazutkin** [comment]
@ander-nz why? Since TS can derive type for `data` as  `{raw: number, square: number}[]` then it will be able to derive a type for expression `typeof data[0]` as `{raw: number, square: number}`

**Comment by ander-nz** [comment]
@lazutkin Sorry, my post was unclear, so I've updated it. (I meant that the type was unknown to the _developer_, so `typeof` would be useful)

**Comment by RyanCavanaugh** [comment]
Approved + accepting PRs: allow `typeof expr['str']` and `typeof expr[42]` in type positions.

**Comment by yortus** [comment]
I submitted a proposal + implementation that covers this: #6606

However the proposal goes beyond what's suggested here so is more aligned with #4233, with this issue covered as a special case.

**Comment by simonbuchan** [comment]
@RyanCavanaugh looks like this can be closed now?

```ts
function test(a: number[]) {
    return a.map(mapper)

    function mapper(v: typeof a[53]) { // or typeof a[number]
        return v.toExponential();
    }
}
```

**Comment by mhegazy** [comment]
with indexed types, `typeof a[number]` should work. see it on the [playground](http://www.typescriptlang.org/play/index.html#src=function%20test(a%3A%20number%5B%5D)%20%7B%0D%0A%20%20%20%20var%20dummy%20%3D%20a%5B0%5D%0D%0A%0D%0A%20%20%20%20return%20a.map(mapper)%0D%0A%0D%0A%20%20%20%20function%20mapper(v%3A%20typeof%20a%5Bnumber%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20v%20%3D%20%22%22%3B%20%2F%2F%20string%20is%20not%20assignable%20to%20number%0D%0A%20%20%20%20%7D%0D%0A%7D)
