### ISSUE TITLE
Suggest values

### ISSUE THREAD

**Issue by VimHax** [microsoft/TypeScript#37492]
## Search Terms

Suggest, Suggestion, Suggest Values

## Suggestion

```typescript
type Suggest = string | 'hello' | 'world';
var x: Suggest = 'hello';
```

When typing out the value of `x` i.e. `'hello'`, it should suggest, not force, the values given in the type, so `'hello'` & `'world'`. 

## Use Cases

For example, if you are define the `on` method of the `Node.js` `EventEmitter`, `on: (event: Event, listener: EventListener) => this;` , & you want the user to be able to emit custom events, you can't suggest them existing events without forcing them to only use them.

**Comment by RyanCavanaugh** [comment]
Duplicate #33471
