### ISSUE TITLE
"typeof" unexpectedly narrows the type of a "let" binding

### ISSUE THREAD

**Issue by aleclarson** [microsoft/TypeScript#37516]
**TypeScript Version:**  3.9.0-dev.20200322

**Search Terms:**
- typeof let narrow

**Code**

```ts
// inferred as "boolean"
let foo = false

// "false" when it should be "boolean"
type Foo = typeof foo

interface Test {
    // "false" when it should be "boolean"
    foo: typeof foo
}
```

**Expected behavior:** 
`typeof foo` should resolve to `boolean`

**Actual behavior:** `typeof foo` resolves to `false`

**Playground Link:** [Click here](https://typescript-play.js.org/#code/PTAEEsDsDMFMCd6wCagIYGdQCIBGB7fAG1jUmwCgSAXUaQ0AXjrSI1gopB2lfe1AB3ABaxIEWhmH4ArkVS5YOAsVLkK1AJ4AHJQDEGzLbvzQ6hTlGoJeAYyUAVWBloBvCqE+hu2Xm1gCImISoFKy8qCKyoQkZJRe5vgAXKDGsKaJFAC+QA)

**Related Issues:** N/A

**Comment by RyanCavanaugh** [comment]
`typeof x` uses the narrowed type of `x`, rather than the declared type, and the narrowed type here is taken from the initializer. The decision to use narrowed vs declared in this case is ultimately arbitrary; either one makes certain use cases awkward.
