### ISSUE TITLE
Add `testEnvironment` option to export/publish all module/class members

### ISSUE THREAD

**Issue by FilipeBeck** [microsoft/TypeScript#37513]
## Suggestion

Add a `testEnvironment` option in `tsconfig.json` that allows importing all members of a module, regardless of whether or not it contains the `export` modifier, and accessing all class members, regardless of access level. I did an initial implementation of this feature [here](https://github.com/FilipeBeck/TypeScript/commit/7dc88aae2164614c69983178eb6314e2c2214537).
I tried to use the same [approach](https://medium.com/@ani.sam2015/what-is-testable-c26ee882ada4) used by the [swift language](https://swift.org/) (adding a `testable` modifier in the import statements), but the complexity is much bigger and my experience in the language design is very limited.

## Use Cases

Very useful when performing unit tests. Currently, if we want to test members of non-exported modules and members of protected and private classes, we have to resort to alternatives like [rewire](https://github.com/jhnns/rewire), for example. The biggest disadvantage of this approach is the loss of typing and the need to compile the code to JS before using.

## Examples

This feature works great when used in conjunction with the [extends](https://www.typescriptlang.org/tsconfig#extends) option, with the `testEnvironment` option being used only in the test files.

__{$workspace}/tsconfig-base.json__
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true
  },
  "files": ["mod-1.ts", "mod-2.ts"]
}
```

__{$workspace}/tests/tsconfig-tests.json__
```json
{
  "extends": "../tsconfig-base",
  "compilerOptions": {
    "testEnvironment": true
  },
  "files": ["mod-1.test.ts", "mod-2.test.ts"]
}
```

**Comment by RyanCavanaugh** [comment]
In general we do not add flags for "Make JS behave completely differently from its defined semantics", and this would qualify as one of those.

**Comment by FilipeBeck** [comment]
@RyanCavanaugh  I understand, but I think this feature would greatly enrich the language. In addition, it is a relatively simple feature to implement. This would make testing much easier.
