### ISSUE TITLE
FindAllReference and Rename for unicode escape sequence

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#3752]
```typescript
var y = {
  "\u0042": 1
}
y.B
```
 Highlight ```B``` or findAllReference at ```B``` should display both ```B``` and ```"\u0042"```. Currently it only show ```"\u0042"

Also doing rename at ```B``` show the rename info as ```"\u0042"````

**Comment by mhegazy** [comment]
That is currently by design. we do not handle any Unicode escapes in the language service features though the language permits them. I am inclined to maintain that course as the value added does not justify the cost or complexity.
