### ISSUE TITLE
After Upgrading Angular 9 Getting Karma Error in node_modules , karma - Config.tpl.ts  , ERROR in node_modules/karma/config.tpl.ts:13:18 - error TS1109: Expression expected.

### ISSUE THREAD

**Issue by Abhilashtiwari0301** [microsoft/TypeScript#37525]
Hi Everyone,
I am getting below Karma Config file  error after upgrading Angular 9 , Angular-9 requires typescript version, >=3.6.4 and <3.8.0, if i degrade the typescript than below issue is resolved.

ERROR in node_modules/karma/config.tpl.ts:13:18 - error TS1109: Expression expected.
frameworks: [%FRAMEWORKS%],
node_modules/karma/config.tpl.ts:13:30 - error TS1109: Expression expected.
frameworks: [%FRAMEWORKS%],
node_modules/karma/config.tpl.ts:17:13 - error TS1109: Expression expected.
files: [%FILES%
node_modules/karma/config.tpl.ts:18:5 - error TS1109: Expression expected.
node_modules/karma/config.tpl.ts:22:15 - error TS1109: Expression expected.

 Package.json

"devDependencies": {
    "@angular-devkit/build-angular": "~0.900.7",
    "@angular/cli": "~9.0.7",
    "@angular/compiler-cli": "~9.0.7",
    "@angular/language-service": "~9.0.7",
    "@types/jasmine": "^3.0.0",
    "@types/jasminewd2": "^2.0.0",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.1.2",
    "jasmine-core": "^3.0.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.0.0",
    "karma-chrome-launcher": "^3.0.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-html-reporter": "^0.2.7",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "node-sass": "^4.13.1",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "^3.6.4"
  }

**Comment by DanielRosenwasser** [comment]
Karma ships some bogus `.ts` file that isn't meant to be read by TypeScript. Ultimately I think the issue is external and should be filed on Karma (i.e. don't ship that bogus file). I'm guessing that the reason you probably are seeing this error is that Angular adds `node_modules` to the list of `typeRoots`.

**Comment by Abhilashtiwari0301** [comment]
@DanielRosenwasser :- But this karma file is installed when we run npm install command from the command line. if I suppose remove this file than still when next time another developer run the command npm install , it will again come in his/her node_modules.
can you please tell me some other solution or how to remove the file.

**Comment by DanielRosenwasser** [comment]
If changing the `typeRoots` option in your `tsconfig.json` doesn't help, then I would suggest filing an issue with Karma. Maybe @mgechev has thoughts here too.

If you're really stuck, you can use `patch-package` to temporarily work around things and add `// @ts-ignore` comments or remove the troublesome file altogether.

**Comment by mgechev** [comment]
As @DanielRosenwasser mentioned, this doesn't seem like an issue in TypeScript. Angular CLI or Karma's issue trackers would be the right place to discuss the problem. I haven't seen this occur in other CLI projects, might be related to custom `tsconfig.json` configuration you've introduced.

**Comment by Abhilashtiwari0301** [comment]
Thanks @DanielRosenwasser and @mgechev , i raised the issue in Angular and Karma Platform.
