### ISSUE TITLE
URL is missing from Window interface

### ISSUE THREAD

**Issue by xtuc** [Microsoft/TypeScript#3753]
From PR https://github.com/Microsoft/TypeScript/pull/3741

**Comment by mhegazy** [comment]
@zhengbli can you take a look

**Comment by xtuc** [comment]
I'm trying to help but that's the only thing I can do. The Window Interface is in the dom.generated.d.ts source file: https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L11848. I can't find the way to create the URL object.

**Comment by zhengbli** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Window/URL:
> It is good practice to call the URL constructor instead of using this property.

we should add a constructor for interface ``URL`` too. It may look like this:
```typescript
interface URL {
    createObjectURL(object: any, options?: ObjectURLOptions): string;
    revokeObjectURL(url: string): void;
}

declare var URL: {
    prototype: URL;
    new(): URL;
}
```

Then for ``window``, add:
```ts
interface window ... {
    ...
    URL: URL 
    ...
}
```

**Comment by xtuc** [comment]
The URL interface is already created: https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L10773-L10776 but it isn't instantiated.

**Comment by zhengbli** [comment]
Actually after trying it out on several browsers, I found that the constructor of ``URL`` doesn't exist in both IE and Spartan. And the two methods ``createObjectURL`` and ``revokeObjectURL`` turn out to be static methods. So it might be more proper this way:

```typescript
interface URL {
}

declare var URL: {
    prototype: URL;
    createObjectURL(object: any, options?: ObjectURLOptions): string;
    revokeObjectURL(url: string): void;
}
```

**Comment by zhengbli** [comment]
Actually after trying out on various browsers, we found that the constructor of interface ``URL`` is not supported in both IE and Spartan. Therefore I think it is safer now to just add the property to ``window`` without changing the ``URL`` interface.
