### ISSUE TITLE
Transpiling "import './b';" to "import './b.js'", while reading b.ts

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript#37547]
I use nodejs 13.11.0 with {"type": "module"} in package.json: all .js files are handles as ES6 modules.

I create a file module b.ts:
```javascript
var m = [1,2,3];
export default m;
```
and also a.ts:
```javascript
import x from "./b";
console.log(x);
```

Now, the file TypeScript has actually to import is b.ts.  If I write in a.ts `import ./b.ts`,then the resulting javascript will contain `import ./b.ts` which does not work and in fact tsc does not allow `import ./b.ts`.

If I keep `import "./b"`, then the resulting code in JavaScript is `import "./b";`. This does not work (in Node and in the browser), since the filename to be imported is b.js and the extension has to be specified.  See also https://github.com/nodejs/node/issues/32442.

Then the last resort is to write in TypeScript `import "./b.js";`.  This is not logical, as at the time this is read, the b.js file probably does not exist yet and TypeScript has to read b.ts.  In fact, TypeScript does exactly this, when I run the process behing `strace`: On `import './b.js';`  tsc 3.8.3 reads b.ts.

But this does match the documentation:

At https://www.typescriptlang.org/docs/handbook/modules.html all sample imports do not use file extensions. except in the discouraged examle at https://www.typescriptlang.org/docs/handbook/modules.html#import-a-module-for-side-effects-only .

The final code must contain `import "./b.js";` otherwise Node does not find the file.

At https://www.typescriptlang.org/docs/handbook/module-resolution.html it is not described what shall the TS-input contain so that both:
• the result is `import "/.b.js";` and
• TypeScript handles the imported file as TypeScript file-module

**Comment by j-oliveras** [comment]
You can already write the imports with js extension (typescript will found the ts file). Tested with version 3.7.5 but I think this behaviour is present in previous versions.

**Comment by dilyanpalauzov** [comment]
It is not documented, that by importing a .js file-module tsc will try reading a .ts file.
