### ISSUE TITLE
Update class expression icon in visual studio completion list & nav bar

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#3754]
Currently in nav-bar and completion, the class expression name has incorrect icon. We need to update the icon to be similar to the one used by class declaration.

**Comment by mhegazy** [comment]
Do we still need this?

**Comment by danquirk** [comment]
Seems not unless I'm misunderstanding the issue:

![image](https://cloud.githubusercontent.com/assets/7121557/8940945/9fbe18a6-3521-11e5-8393-7218d9bd6496.png)

Completion list uses the same icons of course.
