### ISSUE TITLE
New error: This spread always overwrites this property

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#37559]
I believe the error is both correct and valuable, but filing it for completeness, since it wasn't produced by 3.8.

https://github.com/apollographql/apollo-server/blob/c177acd7959aaf516f8ac814f1a6bb2e6d3ed2e6/packages/apollo-server-core/src/ApolloServer.ts#L775

```
packages/apollo-server-core/src/ApolloServer.ts:775:7 - error TS2783: 'context' is specified more than once, so this usage will be overwritten.

775       context,
          ~~~~~~~

  packages/apollo-server-core/src/ApolloServer.ts:787:7
    787       ...this.requestOptions,
              ~~~~~~~~~~~~~~~~~~~~~~
    This spread always overwrites this property.
```

To repro:
1) `npm ci`
2) `tsc -b -f tsconfig.build.json`

**Comment by sethlowie** [comment]
I'm not sure this error is correct. I have the use case of wanting to overwrite the properties. I have to use `Object.assign` which compiles fine, even though it's the same behavior. This change is forcing users to choose a specific syntax for the same behavior.

**Comment by amcasey** [comment]
@sethlowie I'm not sure I follow - do you have an example?  In this case, it looks like the user thought specifying `context` was going to have some effect, but it actually won't because it will always be clobbered by the property spread from `requestOptions`.  I think the intended fix is just to move the overriding `context` after the spread.

**Comment by sethlowie** [comment]
In this example, I can place a script tag in the head of my HTML document and use that to enable/disable specific combinations of feature flags for testing locally and in CI. Changing this to use `MockFlags: Partial<Flags>;` fixes the type error. So maybe the issue here is that using `Object.assign` instead of spreading doesn't throw an error.

```typescript
type Flags = {
  featureA: boolean;
  featureB: boolean;
}

interface Window {
  MockFlags: Flags;
}

window.MockFlags = {
  featureA: false,
  featureB: false,
  ...(window.MockFlags || {}),
}
```

**Comment by amcasey** [comment]
> So maybe the issue here is that using Object.assign instead of spreading doesn't throw an error.

It does seem like they should be consistent.

In your example, it looks like `MockFlags` should be optional?  Otherwise, the `|| {}` will never do anything, will it?  As written, it seems to guarantee that both `featureA` and `featureB` will be present on `window.MockFlags` and will override your explicit values.

**Comment by sethlowie** [comment]
👍 Partial and optional both work. I was thrown by Object.assign not throwing the error.

Here's an [example](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=19&pc=22#code/C4TwDgpgBAYgNgQwOYGcoF4oG8BQUoBmECwArgE4QCCAXFAEYD2jcxAdgNx6HFmUBCdJi3ZcAvjhwBLNsAjkCCAMbQA6jIAmjAO7ZuAWUZKA1vGQo6Z1OMnbNOgHSGTVtJlz4iJCtTqK4KBAANNxefBCChAgBwdwO8XZsWtpORqaIqCESOInJqS4ZblAA8vQAVhBKwA4IKChSSGwAFB483pS0UTEhnrw+kf6BWUFQuY7O6eYAlBxAA) that better demonstrates the inconsistency between spread and Object.assign

```typescript
type Flags = {
  featureA: boolean;
  featureB: boolean;
}

interface Window {
  MockFlags: Flags;
}

window.MockFlags = {
  featureA: false,
  featureB: false,
  ...window.MockFlags,
}

window.MockFlags = Object.assign({
  featureA: false,
  featureB: false,
}, window.MockFlags);
```

**Comment by amcasey** [comment]
It's unfortunate that they don't agree, but I'm not sure there's a good way around that.  Since `Object.assign` is just a function (vs a syntactic construct, like spread), there's no way to know for sure which functions are actually performing assignment.  For example, I could make an alias `const oa = Object.assign;` or I could redefine `Object.assign` to do something else and there'd be no practical way for the compiler to detect those cases.

**Comment by master117** [comment]
I'm actually having problems with this new error and I'm not sure if it is correct.

```
// Get Entries
axios.get(apiUrl + '/rlm/lists/' + self.state.id + '/entries', {
  params: {
    limit: this.state.rows,
    offset: this.state.offset,
    sort: this.getSortString(),
    ...this.getFilters()
    },
  withCredentials: true
})
```

> 'sort' is specified more than once, so this usage will be overwritten.ts(2783)
Editor.tsx(420, 9): This spread always overwrites this property.

getFilters returns an Object {}

I know that the spread may overwrite values, if getFilters returns {sort: "abc"} for example. But while my code logic guarantees that it won't do so I can't state/type this anywhere. I see no way to get rid of this error.

**Comment by hutber** [comment]
I agree, I am having issues with the following:

`config/images.ts:39:5 - error TS2783: 'position' is specified more than once, so this usage will be overwritten.`

```
{
    width: "100%",
    height: "100%",
    marginBottom: `${margin} !important`,
    position: "initial !important" as const, // used to solve chakra bug
    ...(avatar && {
      overflow: "hidden",
      borderRadius: width,
      position: "relative" as const,
    }),
  }
```

position will not be overwritten in this case.

**Comment by amcasey** [comment]
@hutber it looks like `position` will be overwritten if `avatar` is known to always be truthy at that location (which it may or may not be, depending on the surrounding code).

**Comment by hutber** [comment]
Ahhhh interesting indeed. You are correct off the top of my head. I will make sure the definition types are set correctly

**Comment by nithintel** [comment]
@amcasey 'value' is specified more than once, so this usage will be overwritten.  TS2783 i am getting this error and the code is:
<TextField
          id="outlined-select-currency" select value={states} onChange={handleCountry}   variant="outlined" 
          error={touched.country && errors.country ? true : false} {...getFieldProps('country')} helperText={touched.country && errors.country ? errors.country : ''} >
         
          {country.map((option) => (
            <MenuItem key={option.value} value={option.value}>
              {option.label}
            </MenuItem>
          ))}
        </TextField>
        
        Can you please help me on it i am using tsx file in reactjs

**Comment by amcasey** [comment]
@nithintel That's not a lot to go on, but I would guess the return type of `getFieldProps` has a property called "value" that's overwriting the value you specified, `value={states}`.  If you want yours to win, you should put it after the spread (`...`).

**Comment by nithintel** [comment]
> @nithintel That's not a lot to go on, but I would guess the return type of `getFieldProps` has a property called "value" that's overwriting the value you specified, `value={states}`. If you want yours to win, you should put it after the spread (`...`).

@amcasey Thanks for the feedback...

**Comment by NullPainter2** [comment]
"Fixed" by 
```
<JSX
    {...stuffWhichBeSpreadAtTheEnd}
    valueWhereIsError={stuffWhichBeSpreadAtTheEnd.valueWhereIsError || "default value"}
/>
```
