### ISSUE TITLE
Why don't arrays have string index signatures?

### ISSUE THREAD

**Issue by zjopy** [microsoft/TypeScript#37550]
## Search Terms

treat arrays subtype objects 

## Suggestion

In JS there is just one non-primitive value: objects. Arrays (and functions) are just "special" objects. One can start adding properties or methods to them at any time. TS however seems to treat arrays (and functions) as separate types from objects.

Consider the following example of reusing an array as object by adding a property and a method.

```javascript
const arr = ["Hi", "my", "name", "is"];
arr.name = "Peter";
arr.sayHi = function() { console.log(this.join(" ") + " " + this.name) };
```

Typing this in TS can be done using Index Signatures like this.

```typescript
interface StringArray {
    [key: string]: string | (() => void);
    [index: number]: string;
}
```

You might think that's it, but hold on. How would you use this now? You can't just start with an array, since they are treated as different entities from objects.

```javascript
const arr: StringArray = ["Hi", "my", "name", "is"];
// Type 'string[]' is not assignable to type 'StringArray'.
// Index signature is missing in type 'string[]'.(2322)
arr.name = "Peter";
arr.sayHi = function() { console.log(this.join(" ") + " " + this.name) };
```

You can get around it using an `as any` type assertion on the array, but I believe this solves only the effect and not the cause. It seems the cause is that TS doesn't understand that arrays (and functions) are in the end just objects.

What I need is that arrays and functions are treated as "subtypes" of objects. Basically arrays have the special length property and `Array.prototype` as prototype. Functions are callable, possess a `prototype` property and have `Function.prototype` as prototype.

## Use Cases

JS doesn't distinguish between arrays (and functions) and objects and TS should neither. This would allow to use objects in their entirety as possible in JS. Shortcomings of the current apporaches are discussed above.

## Examples

See example above.

## Checklist

My suggestion meets these guidelines:

* [ x ] This wouldn't be a breaking change in existing JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
TypeScript does think that arrays are subtypes of objects:
```ts
// OK
const obj: object = [];
// OK
const m: { length: number } = [];

function fn(x: number | string[]) {
  if (typeof x === "object") {
    // x: string[] in here
  }
}
```
TypeScript doesn't think that arrays have string index signatures, because they really don't. It is absolutely not the case that indexing an array by a string will always produce a `[key: string]: string | (() => void);` - `"length"`, for example, will produce a `number`.

**Comment by zjopy** [comment]
Thanks @RyanCavanaugh, I guess I didn't fully understand index signatures yet. I'm still confused about one part of your answer though.

> Why don't arrays have index signatures?

Since in JS a numeric index is converted to a string index, i.e. `arr[12]` is converted to `arr["12"]`, they sure do. Also you mentioned `"length"` is a valid string index.  

What I did forget was to cover the type of the `"length"` property. But even if I cover any type that is accessible by a string index, TS still gives the error.

```typescript
interface StringArray {
    [index: string]: string | number;
}

const arr: StringArray = ["Hello", "World"];
// Type 'string[]' is not assignable to type 'StringArray'.
// Index signature is missing in type 'string[]'.(2322)

arr["length"]; // number
arr["0"]; // string
```

**Comment by RyanCavanaugh** [comment]
Index signatures also imply validity of writing. So if you had `[index: string]: string | number`, you'd allow this crashing code:
```
["hello"]["length"] = "five";

> VM97:1 Uncaught RangeError: Invalid array length
```

**Comment by zjopy** [comment]
True, but that doesn't seem to answer the question, because if I use an array of numbers with the string index `[index: string]: number`, your error would not happen but TS still shows an error.

```typescript
interface NumbersArray {
    [index: string]: number;
}

const arr: NumbersArray = [10, 20, 30];
// Type 'number[]' is not assignable to type 'StringArray'.
// Index signature is missing in type 'number[]'.(2322)

arr["length"]; // number
arr["0"]; // string
```

**Comment by zjopy** [comment]
Question moved to [SO](https://stackoverflow.com/questions/60912874/why-dont-arrays-have-string-index-signatures)
