### ISSUE TITLE
New error: Argument of type 'B' is not assignable to parameter of type 'Record<string, any>'

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#37562]
https://github.com/Yoctol/bottender/blob/c18c7be57dc9c372dc51fc5d191065f1e0b82a6a/packages/bottender/src/bot/Bot.ts#L184

```
packages/bottender/src/bot/Bot.ts:184:38 - error TS2345: Argument of type 'B' is not assignable to parameter of type 'Record<string, any>'.
  Type 'unknown' is not assignable to type 'Record<string, any>'.

184       const body = camelcaseKeysDeep(inputBody) as B;
```

To repro:
1) `yarn`
2) `tsc -b -f tsconfig.build.json`

**Comment by RyanCavanaugh** [comment]
This is an expected break though somewhat unfortunate. We changed the source assignability of type parameters constrained to `any`, which `B` is - despite its constraint to `Body` which appears to be a very nice union, the last union constituent is actually `any`, so the observed form is `B extends any` which we now treat as `unknown` for the purposes of assignability when in a source position. The containing class could in fact be instantiated with e.g. `B = number` which would violate the input type of `camelcaseKeysDeep`

cc file authors @chentsulin @jigsawye for FYI
