### ISSUE TITLE
New error: Type 'Record<string, any>' is missing the following properties from type 'Mock<T, Y>'

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#37575]
https://github.com/facebook/jest/blob/4a59daa8715bde6a1b085ff7f4140f3a337045aa/packages/jest-mock/src/index.ts#L826

```
packages/jest-mock/src/index.ts:826:5 - error TS2740: Type 'Record<string, any>' is missing the following properties from type 'Mock<T, Y>': apply, call, bind, prototype, and 23 more.

826     return mock;
        ~~~~~~~~~~~~
```

To repro:
1) `npm install`
2) `tsc -b -f packages\jest-mock`

**Comment by RyanCavanaugh** [comment]
It looks like we forgot to document this, but no one noticed? Closing as "got away with it"

**Comment by zuzusik** [comment]
I bumped into similar issue today - @RyanCavanaugh it would be great if you could reveal what was that thing you got away with documenting 😄 

Thanks!

**Comment by RyanCavanaugh** [comment]
I'd need more context here. A type assertion seems appropriate, though.

**Comment by abdelmagied94** [comment]
@RyanCavanaugh Please take a look at this [playground](https://www.typescriptlang.org/play?target=5&ts=4.2.3#code/JYOwLgpgTgZghgYwgAgJIBUIGczIN4CwAUMqciHALYQBcyOUoA5sQL7HFgCeADiqgDEAriATIAvMgAUcKEzoAlCAgD2UACYAeBswA0yOCC4A+AJQTj9MIxAsixVSBzJIOYaLqCRYyTLmfMHFM6HVsLfGIyZCgIMCEoEAM5ADoKajYOeyJuPjR3BAAmTXRkCAAPSBB1LGQlVQ1taz0DI2NLX1l5ZHRzcUtQuwcVJ1xXMHyCzwnNDGwwdulO4KsbJnDCEjIYuISkplSqCAyiIA). It shows the problem and the solution I used.
