### ISSUE TITLE
Globally Augment Function Type

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#37577]
**TypeScript Version:**  3.8.2

**Search Terms:** augment, function, type, signature, globally, add, method

I do apologize if this is intended behavior, which I'm mistaking for a bug.

**Code**

Let's try to augment the global `Function` type to have `someMethod` attached to it.

`augmentation.ts`

```ts
declare module "typescript/lib/lib.es5" {
  interface Function {
    someMethod(): string;
  }
}
```

Then try to utilize that augmented method.

`index.ts`

```ts
import "./augmentation"

function shouldBeAugmented(): void {
  console.log("hi");
}

const result = shouldBeAugmented.someMethod();
```

**Expected behavior:**

For the code to compile without error, as the declaration merging will have occurred (`shouldBeAugmented` will be type-checked as having `someMethod` attached to it).

**Actual behavior:**

Compile error: `Property 'someMethod' does not exist on type '() => void'.`

Any feedback would be greatly appreciated. Thank you!

**Comment by nmain** [comment]
Things like `Function` are in `global` and need to be augmented as such:
[Playground](https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEBzCB7ARlC8DeAoeB8AlgHYAuIMAZlGAgGICuJYZRKJO+hPAzigFsQAWRBkAFimAAKAJQAueLzIxSiANzcCAX1y7cVZq3adekxhGAAhEAEFGiIeRAyF8AG4oiwLgTAd+CBAAOlREaQAicSII2U19fxJleDheCzJ4AF4lc0sbe0cQZ2Bg-iFRCSk5TVwQAA8ABxQYDOx4XSA)

**Comment by harrysolovay** [comment]
Thank you! Works like a charm.
