### ISSUE TITLE
Typo in AllowQualifedNameInPlaceOfIdentifier

### ISSUE THREAD

**Issue by Maxim-Mazurok** [microsoft/TypeScript#37578]
**TypeScript Version:**  master branch

**Search Terms:**
`AllowQualifedNameInPlaceOfIdentifier`
`AllowQualifiedNameInPlaceOfIdentifier`

**Code**
https://github.com/microsoft/TypeScript/blob/a1c8608f681488fda3f0b6ffd89195a81f80f0b0/src/compiler/types.ts#L3688

**Expected behavior:**
`AllowQualifedNameInPlaceOfIdentifier` should be deprecated in favor of `AllowQualifiedNameInPlaceOfIdentifier`

**Actual behavior:**
`AllowQualifedNameInPlaceOfIdentifier` is not deprecated

**Introduced in PR:** #14709

**Comment by cljazouli** [comment]
Good catch @Maxim-Mazurok ! I updated the variable name in https://github.com/microsoft/TypeScript/pull/38726
