### ISSUE TITLE
`ts.SyntaxKind` fails to RoundTrip

### ISSUE THREAD

**Issue by kingces95** [microsoft/TypeScript#37574]
https://github.com/microsoft/TypeScript/blob/e3ec7b18b82d28f796ec635267907ff9014c4c5b/src/compiler/types.ts#L532

This line regressed me. 

Previously `ts.SyntaxKind[225]` would equal `"VariableStatement"` but now it equals `"FirstStatement"`.

How can I enumerate the names of the productions and tokens given that `SyntaxKind` is now polluted with "markers"?

Or how am I supposed to get the nominal name of a production given a `node.kind` given `SyntaxKind` is polluted with "markers". For example, suppose I want to debug and dump the name of a node using: 

`var kind = ts.SyntaxKind[node.kind]`

Now instead of seeing `"VariableStatement"` I get `"FirstStatement"` instead. 

I expect there to be no index of `ts.SyntaxKind` that returns a marker (`"FirstXXX"` or `"LastXXX"`).

**Comment by RyanCavanaugh** [comment]
This has been the case forever; enumeration like this is not a design goal of the enum.

**Comment by kingces95** [comment]
Hm, TypeScript enums may have behaved like that forever, but have those markers been there forever? 

Why isn't it a design goal of enum to be able to enumerate its values? Everything else in Javascript can be enumerated. 

Does it seem unreasonable to want to convert from an id representing a `SyntaxKind` to a string representation of its name? 

I always thought that was the entire point of an enum: associating a name with a number...

**Comment by kingces95** [comment]
Well, this is easy enough to work around. So FWIW to whomever finds this, enums are not designed to be enumerated!
