### ISSUE TITLE
Control flow analysis work unexpectly at strict mode for type maybe undefined

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#37579]
**TypeScript Version:**  3.8.3

**Search Terms:**
control flow analysis strict mode undefined

**Code**

```ts
export class Test {
    test(): any[] | undefined {
        // clear
        this._results = undefined;
        this.addResult('xxx');
        return this._results && this._results.length ? this._results : undefined;
    }

    private _results: any[] | undefined;
    addResult(result: any) {
        if (this._results === undefined) {
            this._results = [];
        }
        this._results.push(result);
    }
}
```

```
tsc test.ts --strict
```
**Expected behavior:**
compile succ

**Actual behavior:**
compile error:
> test.ts:6:47 - error TS2339: Property 'length' does not exist on type 'never'.
6         return this._results && this._results.length ? this._results : undefined;

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #9998
