### ISSUE TITLE
Conditional type in property marks valid assignment as invalid

### ISSUE THREAD

**Issue by domoritz** [microsoft/TypeScript#37586]
I am trying to make a type depend on a generic type but an assignment becomes invalid when the generic type is of a property. When I compare this to a conditional that is not in a property, it works. 

**TypeScript Version:**  3.8.3 and nightly

**Search Terms:**

object, generic, conditional, property

**Code**

```ts
type Rep = {rep: string};
type Fie = string | Rep;

export type Dat<F> = {
  dat: Rep extends F ? string | Rep : string;
};

declare const a: Dat<string>;
export const b: Dat<Fie> = a;  // this should be correct

declare const a2: Dat<string>;
export const b2: Dat<string> = a2;

declare const a3: Dat<Fie>;
export const b3: Dat<string> = a3;
```

This works correctly (the last example should not be assignable). 

```ts
export type Dat<F> = Rep extends F ? string | Rep : string;

declare const a: Dat<string>;
export const b: Dat<Fie> = a;

declare const a2: Dat<string>;
export const b2: Dat<string> = a2;

declare const a3: Dat<Fie>;
export const b3: Dat<string> = a3;
```

**Expected behavior:**

I would expect the first example to pass. 

**Actual behavior:**

The first example is marked as invalid. 

<img width="553" alt="Screen Shot 2020-03-25 at 09 35 01" src="https://user-images.githubusercontent.com/589034/77561427-e9288100-6e7b-11ea-839d-6c1aaeeccfd0.png">

**Playground Link:** 

[Not working](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200324#code/C4TwDgpgBAShZQLxQN4Cd4C4oGdhoEsA7AcwF8BuAKFEigDEDpk9DSoAfWeaqiADzAB7NMCi1oAEQCGwADz0oA4BCIATHAyYA+JKipQoa2djgJlqjQygB+XPmIlO3BNlaPqlKlTUQAxgA20hhQfkJEeFDS2DLy7qTa1ALCoqHhkQBGMbIKOnrSvL6BwdBhEWLSAEzZcQ4JSYIiYmWZ1VCxcvEkushVhf5BIS0VAMw1uRCJfI2pw1AZY+05XT1RI9RAA)

Interestingly, if I don't put the condition as a property type, it works. 

[Working](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200324&ssl=15&ssc=35&pln=4&pc=1#code/C4TwDgpgBAShZQLxQN4Cd4C4oGdhoEsA7AcwF8BuAKFEigDEDpk9DSoAfWeaqiADzAB7NMCi1oAEQCGwADz0oA4BCIATHAyYA+JNwTLVGhlAD8ufMRKd9UbKyu81EAMYAbaRiguhRPFGlsGXkHUm1qAWFRb19-ACMg2QUdPWknVw8vHz8xaQAmRJDLMIjBETFs+IKoYLlQkl1kfPT3T2hK3IBmQuSIcL4y6I6oOO6apPrGgM7qIA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #30639
