### ISSUE TITLE
building other non-ts files with ts files by running  "tsc" command-line

### ISSUE THREAD

**Issue by lgyytm** [microsoft/TypeScript#37584]
**Code**

```
{
  "compilerOptions": {
    "allowJs": true,
    "module": "ES6",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": false,
    "declaration": true,
    "outDir": "./lib",
    "target": "es5",
    "jsx": "react",
    "moduleResolution": "node",
    "types": ["react", "react-dom"],
    "allowSyntheticDefaultImports": true,
    "lib": ["ES6", "DOM"]
  },
  "include": ["static/*/*", "component", "index.tsx"],
  "exclude": ["node_modules", "lib"]
}

```

**Expected behavior:**
when running "tsc" build the ts files in component, the non-ts files will pack up within importing these files into same directory.
I have set scss.d.ts to recognize scss module.
```
declare module "*.scss" {
  const content: any;
  export default content;
}
```

**Actual behavior:**
these non-ts files just stay there

**Playground Link:**

**Related Issues:** 
[2709](https://github.com/microsoft/TypeScript/issues/2709)

**Comment by nmain** [comment]
Typescript supports constructs like `declare module "*.scss"` so you can inform it what your bundler and/or runtime module system will support, but it has no facilities for actually importing stylesheets or any of the other various formats that this is commonly done with.  Adding this would fall in line with one of the [non-goals of the project](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

Tools that support this, like Webpack and Parcel, are large and complex projects in their own right, and you wouldn't want the Typescript team wasting their time so you could get a worse Typescript and a worse Parcel all in one.

**Comment by lgyytm** [comment]
> Typescript supports constructs like `declare module "*.scss"` so you can inform it what your bundler and/or runtime module system will support, but it has no facilities for actually importing stylesheets or any of the other various formats that this is commonly done with. Adding this would fall in line with one of the [non-goals of the project](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):
> 
> > Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.
> 
> Tools that support this, like Webpack and Parcel, are large and complex projects in their own right, and you wouldn't want the Typescript team wasting their time so you could get a worse Typescript and a worse Parcel all in one.

Is that means I have to make a automatic script to satisfy my request?Because this is my final plan.
