### ISSUE TITLE
Function truthy check doesn't apply if the function is in a boolean expression

### ISSUE THREAD

**Issue by afrieder** [microsoft/TypeScript#37598]
**TypeScript Version:**  3.8.2, nightly

**Search Terms:**
Function truthiness, function truthy check

**Code**
```ts
const someBool = true;

function f() {}

if (f) {}

if (someBool && f) {}

if (!someBool || f) {}
```

**Expected behavior:**
All three `if` statements should throw a `This condition will always return true since the function is always defined. Did you mean to call it instead?` error.

**Actual behavior:**
Only the first statement throws the error.

**Playground Link:** https://www.typescriptlang.org/play/index.html?ts=Nightly#code/MYewdgzgLgBBIFsCmAhEIA2MC8MoCcBXJAbgFgAoSgM0LGCgEtwZqAKAShgG8BfSyo2ow21LnwEUhI+MjSYYAMkWtx-KlOFsAhLNTosAH0OqevIA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/37149

**Comment by amunger** [comment]
Is the fact that simply negating the check causes the warning to disappear covered by this issue?

https://www.typescriptlang.org/play?#code/MYewdgzgLgBFAWBLMBzGBeGBvAsAKBhkQgCEBTAQwFcpEAzKgGwAoBKbfQwgJzKiu5g43KmQDcnGAF98UiXnz0YzBMhQA6YuWq0GjdrgIxQkEIzLrGIFMwBEACUS3W8mQrwB6DzADK8EEwAJjBk3Nwg3DCMiADWZDAUAEYgAG5kinTKAISqqJqklDT0TAaSJhBmFlY2Dk4uskA

```
const thing = {
  isBeautiful() {
    return true;
  }
};

if (thing.isBeautiful) {
  console.log("Hi");
}

// Should error like above
if (!thing.isBeautiful) {
  console.log("Hi");
}
```

**Comment by RyanCavanaugh** [comment]
The uncalled function check is intentionally very limited, since there are a lot of cases where you might be checking a function truthiness on purpose. For the case of `if (!x)` it's reasonable to not see an `x` in the body of the function, and we didn't want you to have to write `!!!x` to get around the checking error, so not including that case was intentional.
