### ISSUE TITLE
inferring optional type argument in generice functions

### ISSUE THREAD

**Issue by garronej** [microsoft/TypeScript#37593]
## Search Terms

generic, optional, type guard, asserts

## Suggestion

With generic functions, we can either let the compiler assert the type arguments
or explicitly provide them. It is not possible to provide some and let the compiler
infer the others.

```typescript
declare const myFun: <T, U>(a: T, b: U) => T | U;

declare const a: any;
declare const b: number;

//It would be nice to be able to write this and out being inferred as string | number
const out = myFun<string>(a,b); 
```

## Use Cases

Not having to arbitrate between type safety ( using generic default ) and usability/concision ( forcing users to explicitly provide type annotation that could be inferred )

## Examples

Currently, it is possible to do this:

```typescript
declare function assert(condition: any): asserts condition

const typeGuard= <U extends T, T>(o: T): o is U => true;

const o: number = 33;

assert(typeGuard<33, typeof o>(o));

o; //<= Is of type 33
```

It would be great to be able to write:

```typescript
assert(typeGuard<33>(o));
```
and let ``T`` be inferred as ``number``.  

## Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
See #26242

**Comment by garronej** [comment]
sorry for not finding it :/
