### ISSUE TITLE
Emit a 'noImplicitAny' warning for callbacks to generic functions

### ISSUE THREAD

**Issue by acutmore** [microsoft/TypeScript#37595]
Search Terms

noImplicitAny, generic, callback, function

## Suggestion

Parameters of an inline callback to a generic function become subject to noImplicitAny checks.

[Playground Link](https://www.typescriptlang.org/play/?ssl=4&ssc=4&pln=4&pc=55#)

## Use Cases

This came up when using the React.useCallback hook.

```tsx
function Component(props: any) {
  // 'e' has implicit type 'any' but no warning
  const cb = React.useCallback(e => e.methodThatDoesNotExist(), []);
  return <button onClick={cb}>Click Me</button>
}
```

A workaround would be to move the function out so it's not inline:

```tsx
function Component(props: any) {
  // error(ts7006) 'e' implicitly has an 'any' type.
  const _cb = e => e.methodThatDoesNotExist();
  const cb = React.useCallback(_cb, []);
  return <button onClick={cb}>Click Me</button>
}
```

❌Not compatible with React 'exhaustive-deps' lint rule
❌Not idiomatic React

## Examples

Callbacks to non generic functions would follow existing functionality.

```ts
declare function takesCallback(cb: (...args: any[]) => any): void;
// no warning
takesCallback(e => e.hasTypeAny()); 
```

Callbacks to generic functions would follow noImplicitAny checks

```ts
declare function takesCallback<T extends (...args: any[]) => any>(cb: T): void;
// ts7006 'e' implicitly has an 'any' type. ✅
takesCallback(e => e.hasTypeAny()); 
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is entirely up to whoever writes the definition of `useCallback`. They chose to add a constraint that ultimately makes the `any` explicit:
```
    // TODO (TypeScript 3.0): <T extends (...args: never[]) => unknown>
    function useCallback<T extends (...args: any[]) => any>(callback: T, deps: DependencyList): T;
```

**Comment by acutmore** [comment]
Thanks @RyanCavanaugh,

Raised the issue because I didn't think there was a 'better' way to type a function like this.
Generic args extending a `never[]` fixes the the issue, 'forcing' the author to give the argument a type.

I'll have to wait for the React types to support TS 3.x

Apologies and thanks again 😀

**Comment by akozhemiakin** [comment]
@acutmore 
Actually you do not have to wait, just declare it in your custom types file (something.d.ts)
```
declare module 'react' {
  function useCallback<T extends (...args: never[]) => unknown>(
    callback: T,
    deps: DependencyList,
  ): T;
}
```

**Comment by acutmore** [comment]
Thanks @akozhemiakin. Had to alter it slightly as `@types/react` uses namespaces rather than modules but got it working 😀

```ts
// react-extension.d.ts

declare namespace React {
    function useCallback<T extends (...args: never[]) => unknown>(
        callback: T,
        deps: React.DependencyList
    ): T;
}
```
