### ISSUE TITLE
get InterfaceKeyword instead of letKeyword during tree walk

### ISSUE THREAD

**Issue by ecp3** [Microsoft/TypeScript#3760]
1.5-beta.

I am using the Node interface to walk the syntax tree.  However, when I hit a node that should be 'let', I appear to be getting a 'kind' of InterfaceKeyword instead of LetKeyword.  The text of the node is 'let'.  These two items are adjacent in the enum, so I suspect that's not coincidence.

**Comment by RyanCavanaugh** [comment]
I think we're going to need more information than what's been given to help you here.

**Comment by ecp3** [comment]
I'll try to throw some sample code together tomorrow.

**Comment by ecp3** [comment]
Okay, looks like the problem was I had a 'bad' services header file.  I'm not sure where I got mine from, but it was called tsServices.d.ts.  In that file an excerpt of SyntaxKind looks like this:

       WithKeyword = 101,
        AsKeyword = 102,
        ImplementsKeyword = 103,
        InterfaceKeyword = 104,
        LetKeyword = 105,
        PackageKeyword = 106,
        PrivateKeyword = 107,
        ProtectedKeyword = 108,
        PublicKeyword = 109,
        StaticKeyword = 110,
        YieldKeyword = 111,
        AnyKeyword = 112,

Right now, in your repo I see 'typescriptServices.d.ts', with the following excerpt:

        WithKeyword = 101,
        ImplementsKeyword = 102,
        InterfaceKeyword = 103,
        LetKeyword = 104,
        PackageKeyword = 105,
        PrivateKeyword = 106,
        ProtectedKeyword = 107,
        PublicKeyword = 108,
        StaticKeyword = 109,
        YieldKeyword = 110,
        AsKeyword = 111,

So it looks like in the copy I had the AsKeyword was at a different position, leading to different numbers for a small subset of the syntax elements.

Very confusing.  I hope I just picked up some sort of intermediate copy, as it would be bad to have those numbers shift.

Sorry about the confusion.

**Comment by RyanCavanaugh** [comment]
> as it would be bad to have those numbers shift.

Bad news :smiley:  These numbers *are* going to shift and you should make sure you're compiling against a matching version of the definition file when using this enum. They have to be able to move because we frequently add keywords and tokens that need to go in specific places (we use sentinel values in this enum to define ranges, e.g. "all reserved words" are a contiguous block).

Sorry that this affected you, I know it's not ideal.

**Comment by ecp3** [comment]
Ugh.  That seems unfortunate because it means that an update to the typescript version will require every tool that uses the services to be rebuilt.    And it will be impossible to have one version of the tool that runs against multiple versions.  I'm in an environment where this is not much of a problem (just some dev tools), but it seems like backward compatibility should be a higher priority.

**Comment by danquirk** [comment]
@ecp3 re: backwards compatibility, it absolutely is important, but the compiler API isn't fully baked yet, see: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API :
_Keep in mind that this is not yet a stable API - we’re releasing this as version 0.5, and things will be changing over time._

That said, maybe we need to make sure we publicize changes like this a little more clearer for tool authors.

**Comment by ecp3** [comment]
Fair enough.  I was assuming it was a little more cooked than it actually is.
