### ISSUE TITLE
flat over tuple error

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#37617]
**TypeScript Version:**  3.8.3

**Search Terms:**
* flat
* tuple
**Code**

```ts
const a = [[1, 2, 3]].flat(); // number[]
const b = ([[1, 2, 3]] as const).flat(); // unknown[]
```

**Expected behavior:**
b is `number[]`
**Actual behavior:**
b is `unknown[]`
**Playground Link:** 
No
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Please add to #36554
