### ISSUE TITLE
Abstract function parameter typing doesn't pass to implementing functions 

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#37629]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.9.0-dev.20200324

**Search Terms**
- abstract
- interfere / inference

---

- VSCode Version: 1.43.1

Steps to Reproduce:

1. Install a node module, with typescript definitions.
2. Require the module and try to extend a class in the module with an abstract function. The parameters in the function have type of any although the type of parameter has been defined in the typings.

Does this issue occur when all extensions are disabled?: No

**Comment by meeh0w** [comment]
Could someone share some details on how this could be fixed? I may be able to give it a shot, but it would be nice to get a hint as to where to start :)

**Comment by RyanCavanaugh** [comment]
I mistriaged this; this is not a bug. Derived classes don't inherit their base class methods' parameter types
