### ISSUE TITLE
Type checking on only 1 key gives inconsistent behavior

### ISSUE THREAD

**Issue by binoche9** [microsoft/TypeScript#37636]
**TypeScript Version:**  3.8.3 (also reproduceable on Nightly)

**Search Terms:** inconsistent, assertions

**Code**

```ts
interface KeyCheck<K extends string> {
    _key: K;
}

interface Key1 extends KeyCheck<'key1'> {
    extra: () => void;
}

interface Keys {
    key1: KeyCheck<'key1'>;
    key2: KeyCheck<'key2'>;
    key3: KeyCheck<'key3'>;
}

interface Subset {
    key1: Key1;
}

function narrow(keys: Keys): Subset {
    // This fails with the following error:
    // Property 'extra' is missing in type 'KeyCheck<"key1">' but required in type 'Key1'.
    return keys as Subset;
}

function cast(key1: KeyCheck<'key1'>): Key1 {
    // but this is okay?
    return key1 as Key1;
}
```

**Expected behavior:**

Either both type assertions in `narrow` and `cast` are allowed, or both fail.

**Actual behavior:**

The type assertion in `narrow()` fails with the message `Property 'extra' is missing in type 'KeyCheck<"key1">' but required in type 'Key1'.` which indicates casting `KeyCheck<'key1'>` to `Key1` should fail, but the type assertion in `cast()` is deemed okay by the compiler.

The `narrow()` function is what I want to implement: From the `Keys` provided to me, I want to be able to pick out a subset of those and type assert it to a wider type as long as it has the correct `_key`.

I don't necessarily expect this to be possible (though if it is I'd like to learn how!), but I found it very bizarre that I'm allowed to cast `KeyCheck<'key1'>` to `Key1` but the error message in `narrow()` implies that shouldn't be possible.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgNIQJ4GEAWEEDWAPKshAB6QgAmAzsrWFKAOYB8yA3gFDJ-IB9ApgBcaANzcAvt26hIsRCnQYAjGUoQa9FbnzEA5MLUGOPfhqZwxACgCUyALwcAbgHtg1STLnho8JDRMenN+Y1UxXTxCIiNMVVNJC2MAJkjMPRi4jBTE3jDMAGZ07GjDY0K8n3l-JWQAZQBXACNaCDAufL5wktVvWRhGkAQwYDcQZBA4KCg3AHcbY1oS2jsxJtb2zosAeh3kABUcYHp4YAAbejngMBxkW5QYN3Pz+dYyGbcoES7kPeQAAqzAAO0DAGGQBgoVgMyBOyAAtidaO9QPcMKDIVF9EQAEThXFsWHNRodKAQACOjWA5OocIm4MxBhUCQAdL9yWBGlAJktkHB6Bs2mB+txBsNRuNkAgBWBFvESplyvFTGsgmptvx-iSOrd4fC3AQ4BgAPwc9rc3nxfk6eLeIA)

**Related Issues:** I was not able to find a similar issue.

**Comment by RyanCavanaugh** [comment]
There is a consistent rule being enforced: A type assertion is allowed if one type is assignable to the other, in either direction. `KeyCheck<'key1'>` is assignable to `Key1`, so that assertion is allowed. `Subset` isn't assignable to `Keys` or vice versa, so the assertion isn't allowed.

**Comment by binoche9** [comment]
Hmmm I didn't realize that the type assertion was allowed in both directions. I think that explains my confusion. Thanks for the fast answer!
