### ISSUE TITLE
Type guard fails to narrow type in specific situations with (indirectly) recursive types

### ISSUE THREAD

**Issue by marijnh** [microsoft/TypeScript#37631]
**TypeScript Version:**  3.8.3

**Search Terms:** guard recursive

**Code**

(This is very weird code, result of reducing a real-world situation to the minimum complexity necessary to reduce this.)

```ts
class A<Value> {
  prop!: (x: Value) => void
}
class B<Value> {
  prop!: A<Value>
  is<T>(): this is B<T> { return true }
}

let b: B<any> = null as any
if (b.is<string>()) {
  // b will still be of type B<any> here
}
```

**Expected behavior:**

The conditional would, due to the type guard on the `is` method, narrow the type of `b` to `B<string>`.

**Actual behavior:**

`b` remains of type `B<any>`. _But_, when the line that defines `A.prop` is commented out, it does correctly get narrowed to `B<string>`. If its type is changed to just `Value`, or some function type that doesn't involve `Value`, the problem also goes away.

**Playground Link:** [here](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=14&pc=1#code/MYGwhgzhAECCA8A1MICuBTAfNA3gWAChpoAHAJwHsSBCALmgAoA3Fe5NdASmgF5smKASwAmhAL6FQkGACEkKDNnxFSlGvQTtFhYoIjwAKpgad6AFwAWe6NblHc0MujOoyAO2hmyGaBIJ-CEGdoACN6OTA3AE9sHmg3VBAQaEgU6MJBADNGEIA6PXgIL0E3AHNjTm5lYiCzaCZeUOgAemboAyiSdGgKbIbUN3QADy7gM3RhECibWXhImJ1oYAo3CAog3JAKUuZOcUIgA)

**Related Issues:** none that I found

**Comment by RyanCavanaugh** [comment]
This works as expected for me at your Playground link. Is there more configuration needed to reproduce the problem?
![image](https://user-images.githubusercontent.com/6685088/77715689-81685800-6f99-11ea-861f-426549482236.png)

**Comment by marijnh** [comment]
Apologies, I pasted a slightly incorrect playground link. [Updated to this one](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=14&pc=1#code/MYGwhgzhAECCA8A1MICuBTAfNA3gWAChpoAHAJwHsSBCALmgAoA3Fe5NdASmgF5smKASwAmhAL6FQkGACEkKDNnxFSlGvQTtFhYoIjwAKpgad6AFwAWe6NblHc0MujOoyAO2hmyGaBIJ-CEGdoACN6OTA3AE9sHmg3VBAQaEgU6MJBADNGEIA6PXgIL0E3AHNjTm5lYiCzaCZeUOgAemboAyiSdGgKbIbUN3QADy7gM3RhECibWXhImJ1oYAo3CAog3JAKUuZOcUIgA]

**Comment by RyanCavanaugh** [comment]
`B` is contravariant on `Value`, so it's deliberately not narrowed in this situation (narrowing is supposed to make you have fewer type errors, not more)
