### ISSUE TITLE
For loop wrong indexer type recognition

### ISSUE THREAD

**Issue by k4hvd1** [microsoft/TypeScript#37639]
Seems that indexer type could be better recognized in for loop. Please check the code.
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
mapped type, keyof 
**Code**

```ts
type SimpleType = { a: string, b: number }
let x: SimpleType = { a: "", b: 9 }
let fields: (keyof SimpleType)[] = ["a"]
for (const f of fields) {
    x[f] = x[f] // This throws TS 2322, although the type is obviously the same
}
```

**Expected behavior:**
The type of x[f] is the same as the x[f] and should be assignable. 
**Actual behavior:**
x[f] is not assignable to x[f]
**Playground Link:** 
[example](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=7&pc=1#code/C4TwDgpgBAyglgWzAGwgFXNAvFA3lAQwC4oBnYAJzgDsBzAGigCMTqBXBJiCqAXwChUwKAA8S8JKgyQoOfMSgAiRYxZQAnH0ERhAMzgRkAE1IkAFAGsIIAPa7YiFOkwBKANoBdWVDeKCij35dGx4zAGMbanIoezsYg2NSFzx+KDTRN10vHBFMwIEgA)

**Related Issues:** 
Actually the initial issue was with mapped type, but while looking for the cause and workaround I created this simple showcase. Suppose fixing this would resolve mapped type issue.

**Comment by RyanCavanaugh** [comment]
In general this is a correct error. You couldn't validly, for example, write this (it would sometimes corrupt the object), even though the types are the exactly the same:
```ts
type SimpleType = { a: string, b: number }
let x: SimpleType = { a: "", b: 9 }
let fields: (keyof SimpleType)[] = ["a", "b"]
for (const g of fields) {
  for (const f of fields) {
    if (Math.random() > 0.5) x[f] = x[g]
  }
}
```
See #32693

**Comment by k4hvd1** [comment]
Your code makes sense, but it is a different case from the one I submitted. 


You proposed general case and x[g] is not assignable to x[f]. However its a bit tricky and special case should be considered. So, if the indexer is the same type than operation should be allowed.
The type of indexer is not just its declared type, perhaps it also depends on exact instance. This is not currently checked with compiler, and this raise error for correct code , please check the code.

```javascript
type SimpleType = { a: string, b: number }
let x,y: SimpleType = { a: "", b: 9 }
let fields: (keyof SimpleType)[] = ["a", "b"]
for (const g of fields) {
    for (const f of fields) {
        x[f] = x[g] //OK (Error -> and should not be allowed; type are not same: each one is string|number )
        y[f] = x[f] //Error -> but is OK (types are the same: each one is string or each one is number)
        x[f] = x[f] //Error -> but is OK (types are the same)

        let h = (Math.random() > 0.5) ? fields[0] : fields[1]
        y[h] = x[x] //Should be an error
        let j = f
        y[j]=x[f] //Would be nice if the complier let this compile to
  }
}
```
[code link](https://www.typescriptlang.org/play/?ssl=15&ssc=2&pln=1&pc=1#code/C4TwDgpgBAyglgWzAGwgFXNAvFA3lAQwC4oBnYAJzgDsBzAGigCMTqBXBJiCqAXwChUwKAA96IEvCSoMkKDnzEoAImWMWUAJx9BEYQDM4EZABNSJABQBrCCAD2+2IhTpMASgDaAXXlQPygjUVJmUvfn07HgsAYztqcihaKAcoQ2MzNzx+KBzUyKgYuITHFLTTUkzcbNyakQ99Hxw62h8AelaAeQBpAoBRCgp8gFoAPkJqEzIACzs2UyhqO2EuQmRkOwB3CBM3apqckHrG0SOodv7BnlHmNmE4UihugtBIB4IKaGAp6FICBAhdvtcnUGr4QW1WhdhmMmLcoPdHj0LC8IG8PlAvj8-gD+Ht9kIoFNfBYALIEL4AOgoBAmdgQFkyYwADBSAKyZAD8qSM5Q8TJ8JDKZg8AEYwkCDh4psc6iIITAZnNJisaVBuJc8TUCQArXz6TW5Q7arxYcFnVoAdVm8xW1Dg0WgcEcmKgsWkRh4BK+CLdYDgqAxdmqAl4QA)

Proposal:

1)  add additional check while compiling that checks both type and variable in indexer

2)  add special keyword (to simplify and limit compiling effort)
```javascript
  for (const f of /*keyword_of_mapped_field*/ fields)
``` 
and implement additional indexer instance check

3) add special keyword (to simplify and limit compiling effort)
```javascript
	y[/*keyword_of_mapped_indexer(*/f/*)*/]=  y[/*keyword_of_mapped_indexer(*/g/*)*/]
```
and implement additional indexer instance check

**Comment by TiagoCavalcante** [comment]
Any updates on this?
This feature would be really useful and doesn't seems to be as complicated as other new TypeScript features
