### ISSUE TITLE
React import is being omitted

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3764]
I'm getting an issue with React/JSX on VSCode with the master from today and I use the latest `react-jsx.d.ts` and `react.d.ts` from `DT`. I extend `React.Component` in an another file and then use it on my current file. So I don't expose React namespace in my current file. And when I import React it is being shaked off.

`module1.tsx` 
```typescript
/// <reference path='typings/react/react.d.ts'/>
/// <reference path='typings/react/react-jsx.d.ts'/>

import * as React from 'react'; // it didn't gave me any error when this line is omitted.

export class Document<P, S> extends React.Component<P, S> {
    public name: string;
}
```
`module2.tsx` (notice omit comment)
```typescript
/// <reference path='typings/react/react.d.ts'/>
/// <reference path='typings/react/react-jsx.d.ts'/>

import {Document} from './module1';
import * as React from 'react'; // this line is being omitted

interface Props {}
interface States {}

class Something extends Document<Props, States> {
    public name = 'helloworld';

    render() {
        return <div/>
    }
}
```
`module1.js`
```javascript
/// <reference path='typings/react/react.d.ts'/>
/// <reference path='typings/react/react-jsx.d.ts'/>
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var React = require('react');
var Document = (function (_super) {
    __extends(Document, _super);
    function Document() {
        _super.apply(this, arguments);
    }
    return Document;
})(React.Component);
exports.Document = Document;
//# sourceMappingURL=module1.js.map
```
`module2.js`
```javascript
/// <reference path='typings/react/react.d.ts'/>
/// <reference path='typings/react/react-jsx.d.ts'/>
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var module1_1 = require('./module1');
var Something = (function (_super) {
    __extends(Something, _super);
    function Something() {
        _super.apply(this, arguments);
        this.name = 'helloworld';
    }
    Something.prototype.render = function () {
        return React.createElement("div", null);
    };
    return Something;
})(module1_1.Document);
//# sourceMappingURL=module2.js.map
```
Also because the export class makes below file an external module. Don't you think it should error on below comment:
```typescript
/// <reference path='typings/react/react.d.ts'/>
/// <reference path='typings/react/react-jsx.d.ts'/>

import * as React from 'react'; // it didn't gave me any error when this line is omitted.

export class Document<P, S> extends React.Component<P, S> {
    public name: string;
}
```

**Comment by billccn** [comment]
For module2: see https://stackoverflow.com/questions/15267705/typescript-compiling-removes-unreferenced-imports

For module1:
This is due to the particular way `react.d.ts` is coded. It declared `React` as an exported module, which tells the compiler the `React` symbol is a reachable object regardless of whether the library is imported. I guess this is to accommodate front-end setups where the React library is loaded externally to the module system.

Arguably, the definition file write should have left the choice to the user and let you decide whether to declare `React` as an ambient variable or as an imported module.

**Comment by tinganho** [comment]
That SO thread is not relevant for me, since it is an amd reference. I still think module2 is a bug, because I declared with a flag that I'm using `React.createElement` factoring and in my code I have wrote `<div/>`

I agree with you on `module1`. Maybe send a PR and have `d.ts` file not exposing globals.

**Comment by RyanCavanaugh** [comment]
There's already a pending PR to go back to the previous style of .d.ts for React, which was to have a separate .d.ts file for the global 'React' vs the importable module.

Under `--jsx react` we should treat any element as a usage of the 'React' symbol.
