### ISSUE TITLE
Mapping of nested tuples shows error

### ISSUE THREAD

**Issue by maximilianMairinger** [microsoft/TypeScript#37643]
Mapping nested tuples via `in keyof` into a Wrapper requiring a tuple throws an error. However the output is as intended.

**TypeScript Version:**  3.9.0-dev.20200326

**Search Terms:**
nested tuple wrap map
**Code**

```ts
type Wrap<T extends any[]> = {wrapped: T}

type WrapTupel<T extends any[][]> = {
  [P in keyof T]: Wrap<T[P]>   // Err: Type 'T[P]' does not satisfy the constraint 'any[]'.
}

type test = WrapTupel<[[number], [string, boolean]]>   // Works anyway
```

**Expected behavior:**
No error thrown
**Actual behavior:**
Error thrown
**Playground Link:** 
[link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200326&ssl=7&ssc=71&pln=1&pc=1#code/C4TwDgpgBA6gTgQzAHgCpQgD2BAdgEwGcoFcQBtAXQD4oBeKAbwHdExJ8AuKVAXwFgAUENCRYbVAFdIAGzQZseIiTJUqtBoyFQo5AApQAlrigBrCCAD2AMx6Vu8JGn00dUAPTuoAUThxuqODQAOSoLsFQ+JYQxLiWwFCECMCGhNYgUMAAFtAAxpa4hMCIxgnBpBSUwQB0QgLCgqLQOEX04khSssjk5LiSALYARhBwlAA0ukVwxgDmE4OWljIQpJSuOp6wlnCmxBXMCCBCQkA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is a correct error. `type K = any[][] & { m: string }` is a valid `any[][]`, but `K[keyof K]` for `keyof K === "m"` is not `any[]`.
