### ISSUE TITLE
Type in .ts is not same as type in .d.ts

### ISSUE THREAD

**Issue by lcswillems** [microsoft/TypeScript#37647]
**TypeScript Version:**  3.8.3

**Expected behavior**
```ts
export const s = true ? 'a' : 'b';
```

should give this declaration:

```ts
export declare const s: 'a' | 'b';
```

**Current behavior**

The current declaration is:

```ts
export declare const s: string;
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```
</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?#code/KYDwDg9gTgLgBAYwgOwM71XAvHGUCuwcA-HAOQCGZcAXOQEZkDcQA)

**Comment by DanielRosenwasser** [comment]
Bizarre that it's not just `"a"` in both cases...

**Comment by lcswillems** [comment]
Is it a bug or is it me?

**Comment by RyanCavanaugh** [comment]
In a TS file `s` has the type `widening "a" | widening "b"`, which you can see by writing this:
```ts
export const s = true ? 'a' : 'b';
// j: string
let j = s;
```
This is different from regular `"a" | "b"`:
```ts
export const s: "a" | "b" = true ? 'a' : 'b';
// j: "a" | "b"
let j = s;
```
There's no type system syntax to let you refer to `widening "a" | widening "b"`, so declaration emit has to pick one or the other. There are pros and cons to each and it'd just be a massive breaking change to change our minds about it now.

**Comment by lcswillems** [comment]
I don't get why it has been marked as question. It is not a question. It is an issue for me

**Comment by kitsonk** [comment]
Why is it an issue for you?  You haven't explained that.

A type annotation would be the workaround.  As Ryan said, it is sort of the Schrödinger's cat of types, in that `widening "a" | widening "b"` is not emitable and so something has to be chosen.

**Comment by lcswillems** [comment]
Because it is very unexpected (for me) that the type inside a typescript file doesn't match the type that is exported.

I don't understand why it makes sense to implement it the way it is currently implemented.

**Comment by orta** [comment]
I think the underlaying ask here is that because we can evaluate the code flow, we should be able to make more narrow assumptions about the type:

 - we know it's a `const`, so it _can_ use a literal
 - we know there's only two code paths, both of which end in a literal

So, could TypeScript use the CFA to make the `const` a union of the potential types instead of 'giving up' on the literals and widening to `string`

**Comment by RyanCavanaugh** [comment]
@orta everything you said already happens, it's just that it's a union of the widening forms of the literal types.

> Because it is very unexpected (for me) that the type inside a typescript file doesn't match the type that is exported.

Of the two things we could emit, *neither* would exactly match the observed type in the .ts file.

**Comment by kitsonk** [comment]
I guess one problem, though fixing it for non-sensical code doesn't make sense, is that the intellisense type does not match the export type.  When you hover, you get `"a" | "b"`.  The OP doesn't mention this.

**Comment by lcswillems** [comment]
I agree with @kitsonk . I didn't mention it but this is what makes it very confusing. The editor tells me the type of the variable is `"a" | "b"` but the exported type is `string`. It took me some time to understand the issue in my code because of this.
