### ISSUE TITLE
Error: Type alias circularly references itself - when using array

### ISSUE THREAD

**Issue by infi-pc** [microsoft/TypeScript#37649]
**TypeScript Version:**  3.9.0-beta

**Search Terms:**
circular reference, type alias

**Code**

```ts
type TypeStructure =
  | ["or", TypeStructure[]] // problem is only here, when using array
  | ["string"]
  | ["number"] 
  | ["list", TypeStructure] // with just this it is ok
```

**Expected behavior:**
No error, as in 3.8.3 and lower

**Actual behavior:**
Showing error `Type alias 'TypeStructure' circularly references itself.`

**Playground Link:**
https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200326#code/C4TwDgpgBAKuEGVgCcCuBjYrnQLwCgooAfKAbQCIB7ZCgGlniTU2wjIF0PCTyKBnFAEsAdgHMK3IqUojUAWwBGEWlN6UANkMH1GkZhiw4OQA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/37597

**Comment by RyanCavanaugh** [comment]
@weswigham regression from 3.8.3
