### ISSUE TITLE
Issue on JSON.stringify (lib.es5.d.ts)

### ISSUE THREAD

**Issue by bwlt** [microsoft/TypeScript#37641]
https://github.com/microsoft/TypeScript/blob/7f1df6e53e99e6bd1512581e3da1e3d8298ca401/lib/lib.es5.d.ts#L1066
https://github.com/microsoft/TypeScript/blob/7f1df6e53e99e6bd1512581e3da1e3d8298ca401/lib/lib.es5.d.ts#L1073

The signature of this functions are not correct. If passing undefined as an argument this function can return undefined.
On the above definitions the return type is always type `string`.

see [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description):
> undefined, Functions, and Symbols are not valid JSON values. If any such values are encountered during conversion they are either omitted (when found in an object) or changed to null (when found in an array). JSON.stringify() can return undefined when passing in "pure" values like JSON.stringify(function(){}) or JSON.stringify(undefined).

**Comment by AviVahl** [comment]
https://github.com/microsoft/TypeScript/issues/18879
