### ISSUE TITLE
Discriminated union does not work with string literal types

### ISSUE THREAD

**Issue by proteriax** [microsoft/TypeScript#37650]
**TypeScript Version:**  3.8.3

**Search Terms:**

**Code**

```ts
const $type: "@type" = "@type"
type A = { ["@type"]: "A", a: boolean }
type B = { ["@type"]: "B", b: boolean }
type C = A | B

declare const c: C;
switch (c[$type]) {
    case "A":
        c.a; // <-- Property 'a' does not exist on type 'B'.(2339)
}

switch (c["@type"]) {
    case "A":
        c.a;
}
```

**Expected behavior:**
No error.

**Actual behavior:**
Property 'a' does not exist on type 'B'.(2339)

**Playground Link:** 
[Playground](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=15&pc=2#code/MYewdgzgLgBAJFAngBwKYC4YCIACS1YwC82eKqWAUPqjAILEwDeMA2rjVgLqZZ1YAaGAENMAIxAgANqmFgYAX2rkYAIUYt2ZAj2yrBMMeMky5i5WhgBhRgwA+aypQAmqYFOEAnWqEixgmFYA3JQQAO4AllDAABYwABTArAjkXACUzJQw2TDAwhC0fFjoWTllwAB0wiFKoZHRcYlanOmZ5fmF-CVl5VU1QA)

**Related Issues:** 
Can’t find any so far.

**Comment by RyanCavanaugh** [comment]
@sandersn design limitation?

**Comment by sandersn** [comment]
Performance limitation; it's too expensive to put a control flow node on every element access -- creating it uses too much space and walking over it uses too much time. The decision to create a flow node is made syntactically, just after parsing, so there's no type information to guide it.

We have made similarly expensive expansions to control flow analysis before, like the nodes we add to support `assert` narrowing. But this feature isn't as useful, I think.

**Comment by sandersn** [comment]
Discussion is here, including a link back to the original bug: https://github.com/microsoft/TypeScript/pull/31478
