### ISSUE TITLE
Invalid assignment from union when more accurate type is inferred

### ISSUE THREAD

**Issue by hayes** [microsoft/TypeScript#37654]
**TypeScript Version:**  3.9.0-dev.20200326

**Search Terms:**
union assignment guard
**Code**

```ts
let numberOrString: number | string = 123

function assign() {
  numberOrString = '123'
}

assign()

const n: number = numberOrString
```

**Expected behavior:**

assigning numberOrString to n should not be allowed
**Actual behavior:**

No error, numberOrString is inferred to be number rather than numberOrString. If numberOrString were a `const` I could see justification for this behavior, since we now from the assignment that it is a number, but as a let, with a function call between the 2 assignments, it is not safe.

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200326&ssl=1&ssc=1&pln=11&pc=1#code/DYUwLgBAdgrgtgIxAJwPLIMpmQSygcwC5p4lkIAfCAZ2z3wgF4IBGAJgGYAoLgMxigBjMDgD2UCAENq1HPigAKAJQQA3lwglEKdFlwEmEAOTsORrgF8e02fOU9B42tGKxt5Zm7K66BHkA

**Related Issues:**

**Comment by hayes** [comment]
This only seems to affect the block where the variables are declared, assigning from within the assign function for example, correctly produces an error.

**Comment by RyanCavanaugh** [comment]
See #9998

**Comment by hayes** [comment]
thanks!  Sorry about the duplicate.  I got tripped up by not realizing that a type could be narrowed immediately by its assignment, even when there is an explicit type, but it makes sense.
