### ISSUE TITLE
[3.9.0-beta] Type gets incorrectly un-narrowed after ifs

### ISSUE THREAD

**Issue by eamodio** [microsoft/TypeScript#37660]
**TypeScript Version:**  3.9.0-dev.20200327

**Search Terms:**

**Expected behavior:**
No error

**Actual behavior:**
Error:
```
Property 'name' does not exist on type 'object | Function'.
  Property 'name' does not exist on type 'object'.(2339)
```

**Related Issues:**

**Code**
```ts
function foo(instance: Function | object) {
	if (typeof instance === 'function') {
		if (instance.prototype == null || instance.prototype.constructor == null) {
			return instance.name;
		}
	}
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function foo(instance) {
    if (typeof instance === 'function') {
        if (instance.prototype == null || instance.prototype.constructor == null) {
            return instance.name;
        }
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?ts=3.9.0-dev.20200327#code/GYVwdgxgLglg9mABMOcAUMwGcoENICmAXIgGLjTxIA+icARgFYHQCUiA3gFACQMwiNFACeABwJwBmHPggFEAXiWIA5KEiwEK9tx58BGbHkIA6UQCc4UK2PnKwIADaPE1WtONyzl6yPEmIBBxzEGg4c0UFRAdnHV49cwIoEHMkD1kCEzBcAFsCAG54gF9eEpKgA)

**Comment by ahejlsberg** [comment]
The logic in #32774 has logic to reset to the declared type in certain cases. In #37134 we removed all such logic from other narrowings. We should remove it here as well.
