### ISSUE TITLE
Const enums with mixed types not correctly having their type deduced

### ISSUE THREAD

**Issue by Newbytee** [microsoft/TypeScript#37667]
**TypeScript Version:**  3.9.0-dev.20200327

**Search Terms:** const enum enums mixed types

**Code**

```ts
interface IDBTarget {
  result: IDBDatabase;
}

const enum ObjectStoreNames {
  OBJECT_STORE_KEY_PATH = "object-store-key-path",
  VERSION = 1
}

const request = indexedDB.open("list-of-items", ObjectStoreNames.VERSION);

request.onupgradeneeded = evnt => {
  if (evnt.target === null) {
    return;
  }

  const db = (evnt.target as unknown as IDBTarget).result;

  db.createObjectStore("storage-of-objects", {
    keyPath: ObjectStoreNames.OBJECT_STORE_KEY_PATH
  });
}
```

**Expected behavior:** The TypeScript compiler deduces that OBJECT_STORE_KEY_PATH is a string at runtime and thus lets it be used as value for this property. 

**Actual behavior:** The TypeScript compiler complains that ObjectStoreNames cannot be assigned to string.

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200327#code/JYOwLgpgTgZghgYwgAgJIBEBCAVOUDmEYyA3gLABQyyUEAzgK4A2YAXGlunGHAEZx0IAbkoBfSpQQB7EHWIQQDALbIA8rwBWEBGADKYKbQBycJfVKVqqzACkAogGFsAfV3ZVAJTvOA0nYCazgAKAILYABLIALzIAERSmtpgALRyhhDJANYQAJ7JAA7cABaxADSWyABqdh66qKpG0cgAjGISFNKyxLQAjgz0xDGgACYQAB4Qw1gAdFL5CgAUsUzAcslSMMnAkEp0ZWqJOvrpJmZ009W19UYAlCIUlL39crOK+fhQcKMgEJOTTRAAG7gaIAPgsVGQwBgyAWQPA0x4BCI0SiMUUTCYNwh1GotDADCgIHu1HED0hnTkyGGvCacOBYEReEIxAEyAYIEyICkAHcQMg2RgcMyiDdprRGCx7hUadMELRuBB1FojgZaEs0p9COtNgkVWA9qUcbjsjkgsV2MqksdjKZ6NNrPYnK53F5fAFgmFwhVRHcxEA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior - TS assumes that you want to maintain flexibility on the underlying values here (otherwise you could just have used a regular object). Use `as const` on the value if this is not your intent.
