### ISSUE TITLE
Abstract property cannot be accessed in the constructor check cant trace through function

### ISSUE THREAD

**Issue by moonrailgun** [microsoft/TypeScript#37671]
**TypeScript Version:**  3.9.0-dev.20200328

**Search Terms:**
abstract, property, constructor error, check

**Code**
```typescript
abstract class P1 {
    abstract property: string;
    constructor() {
        console.log(this.property)
    }
}

abstract class P2 {
    abstract property: string;
    constructor() {
        this.init()
    }

    init() {
        console.log(this.property)
    }
}
```

**Expected behavior:**

TS error tip should show in class P2

**Actual behavior:**

If I wrapper it with function, its not work correct. Its easily to take mistake.

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200328&ssl=15&ssc=39&pln=15&pc=42#code/IYIwzgLgTsDGEAJYBthjAgCgRgQbwCgFiFRIZ4EAHKAeyoFMoIBPALgXIEsA7AcwDcRErFo9yAV3i0oACgCU+YSRFiwtZAwB0yWn1kQAFlzBaa9Jq3nKEAXwL2CZaHEQo0GTACYlK5xURzRmZ2TmheQRtRcWgpCBkFXxUSIxMtXi4IBRtHFQysxUJk1XENbV19VNMgyxZFAHp6hB5aRCM6AHcEJjooJEMGWABrBGQuIYYsbByHAiA

**Related Issues:** 
#19197 #26642

**Comment by RyanCavanaugh** [comment]
Methods aren't inlined for purposes of CFA, and shouldn't be since they're virtual - the design contract of this class may well be "Initialize `property` then call super.init()`"

**Comment by moonrailgun** [comment]
I have no idea about CFA mean. 

In my mind, i just want to call `init` by parent class constructor. so its unnecessary to call it by other way. 

If i try to access `property` in . TS will tell me its error, i cant do it, its very good, i will modify it.  
But, if i wrap it with function at first, no error tip throw, and its hard to find this error. Maybe it can be improve?

Just raise this problem as typescript user, FYI.
