### ISSUE TITLE
JSX IntrinsicElements detection

### ISSUE THREAD

**Issue by NekR** [microsoft/TypeScript#3767]
Let's say I have a tool completely not related to React which transforms JSX to JS. And let's say I want it to use with NativeScript elements/controls.

One of main things of JSX is that it has built-in elements and custom elements (components) are based on built-in elements, because in the end of a day they return some built-in element (or primitive).
This all works fine with DOM and html tags because your are treating lower-case elements as built-ins. But it won't work for NativeScript since its built-ins are in CamelCase, so TypeScript will try to find such elements in the scope, instead of treating them as `IntrinsicElements`.

Of course, this could be solved with some built-in like `<view type="StackLayout"></view>` and then make NativeScript built-ins as a classes and return `<view type="..."></view>` inside them.

Does not it seems wrong to you?

**Comment by RyanCavanaugh** [comment]
Let's keep going on this hypothetical. Say this tool exists, and that it supports a notion of user-defined classes (the same way React does).

Then I define a user class `MyClass`

What mechanism would this tool use to determine that it should transform `<MyClass>...` to `NativeScript.Create(MyClass, ...)` and `<StackLayout>...` to `NativeScript.Create("StackLayout", ...)` ?

If it's a hardcoded list, then you can (in TypeScript) just write:
```ts
declare var StackLayout: ...;
declare var Label: ...;
```

If it's some other mechanism that couldn't be modeled that way, we'd need to understand what that mechanism could be in order to support it in TypeScript.

**Comment by NekR** [comment]
> Say this tool exists, and that it supports a notion of user-defined classes (the same way React does).

You misunderstood me. As I said, it's completely separate and is not any compatible to React.
That hypothetical tool is able to look into scope and determine if such variable exists or not. And yes, it has configurable list of built-ins (plus ability to disable scope look-up, but this is not important). So for DOM config might look like this:

```javascript
tool({
  captureScrope: true,
  builtins: ['div', 'span', 'p', ... /* all html tags */]
})
```

Then transpilation of this code:
```js
import custom from './custom';

export default () =>
<custom>
  <div>test</span>
<custom>
```

will produce function call for ```custom``` and just descriptor for built-in tag -- ```div```.

For NativeScript these all might look like this:

```javascript
tool({
  captureScrope: true,
  builtins: ['StackLayout', 'GridLayout', 'Page', ... /* all NativeScript tags */]
})
```

```js
import CustomWidget from './custom';

export default () =>
<CustomWidget>
  <StackLayout>...</StackLayout>
<CustomWidget>
```

Here ```CustomWidger``` should be function call and ```StackLayout``` built-in descriptor.

This is the case I am talking about.

**Comment by NekR** [comment]
See here: https://medium.com/@nekrtemplar/jsx-everywhere-a6ee99290e0d _TypeScript_ section for more details.

**Comment by buzinas** [comment]
Any news on this?

**Comment by NekR** [comment]
React components now can be just functions too, not sure if TS reflected
this change.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be affecting anyone else, and JSX: Preserve is available for downstream transpilers to put their own rules on
