### ISSUE TITLE
missing getter is undetected TS error, runtime error

### ISSUE THREAD

**Issue by bunnybones1** [microsoft/TypeScript#37689]
**TypeScript Version:**  3.8.3

**Search Terms:**
missing getter setter

**Code**

```
class A {
  label:string = 'test'
}

class B {
  private _a:A
  set a(val:A) { this._a = val }
  constructor() { this._a = new A() }
}
const b = new B()
b.a.label = 'hello' //b.a will always be undefined due to missing getter, but still somehow gets b.a's type from the setter, and will cause no TS errors

```

**Expected behavior:**

Error: no 'a' property on class 'B'

OR

Error: class 'B' is missing a getter for property 'a'

(P.S. maybe `b.a` should not resolve to type 'A' just because that is the setter type)

**Actual behavior:**

Compiles fine. Variable has value undefined at runtime.

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=12&pc=1#code/MYGwhgzhAECC0G8CwAoa1wCMCmIBcEALgE4CWAdgObQC80A5IdkfagL6qqiQwBCiqdAAcyANzBNoAfTB5Yg6BGyFoYABTj8sAJSJohABakIAOhm1om6BzTRgAe3JFiAV2CF7xNboT6jp8zpybAB3OG9rdi5HImhMC2Cw3m9UTBMwEyxcC3oDXBB7emgAemK0sGgQ0hAQVRAQsABPGBxoF3IAE2wAMwpsDugOl2x9e2gAW2MICmpKZSZiABo4lxUiatqIe3HsA3swucIW9PoYQkahEe7ibb8RpUIF5bBOyo27MBclaHIxgBUAMrQbDEG7ECCoIA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/30852

**Comment by arilotter** [comment]
+1 A getter without a setter is well-defined in TS (readonly) but a setter without a getter should either use some `writeonly` modifier ( https://github.com/microsoft/TypeScript/issues/21759 ) or fail to compile entirely, since TS's type system *won't complain* and you'll get runtime errors.

**Comment by bunnybones1** [comment]
Hey @RyanCavanaugh 
I'm aware of https://github.com/microsoft/TypeScript/issues/30852 but it's closed and unresolved, so I wasn't sure how to proceed.
