### ISSUE TITLE
Overloaded union type does not resolve overloads

### ISSUE THREAD

**Issue by maximilianMairinger** [microsoft/TypeScript#37704]
Two interfaces with (at the same signatures) overloaded functions as members, combined into an union type, loose the overload information.

**TypeScript Version:**  3.9.0-dev.20200328

**Search Terms:**

Union Overload resolve interface

**Code**

```ts
type Wrap<T> = {wrap: T}

type A<Values extends any[]> = {
  get(): Values
  get(overload: string): Wrap<Values>
}

type B<Value> = {
  get(): Value
  get(overload: string): Wrap<Value>
}

type AB<Values extends any[]> = A<Values> | B<Values[number]> 

let ab: AB<(string | number)[]>
let res = ab.get("overload") // typeof (string | number | Wrap<(string | number)[]>)
```
`res` should be only `typeof (Wrap<string | number> | Wrap<(string | number)[]>)` since both subtypes (`A` and `B`) of the union type (`AB`) have the same overload signatures

**Expected behavior:**

`res` in the above code should be the same as `A` and `B` seperatly executed.

```ts
type AB1<Values extends any[]> = A<Values>
let ab1: AB1<(string | number)[]>
let res1 = ab1.get("overload")

type AB2<Values extends any[]> = B<Values[number]>
let ab2: AB2<(string | number)[]>
let res2 = ab2.get("overload")


let whatResShouldBe: (typeof res1) | (typeof res2)
```

**Actual behavior:**

`res` in the first example is `typeof (string | number | Wrap<(string | number)[]>)` and not as the union suggests `(typeof res1) | (typeof res2)` or `(Wrap<string | number> | Wrap<(string | number)[]>)`

**Playground [Link](https://www.typescriptlang.org/play/index.html?strictNullChecks=false&ts=3.9.0-dev.20200328&ssl=36&ssc=51&pln=27&pc=1#code/LAKALgngDgpgBAdQE4EMoB4AqA+OBeOAbwHdUoAuOTAX1FEljgEF0A1FAGwFcYBnOGAA8wMAHYATfilEQA2gF1cBQqDhwA5jDAAKAJSV23Pqo1btAewBuMJB3MpxlXmCQBLUev2IybTj17YoLQg9NDwAEK+RkpEJpo6XoY8cWZWNnYOTi7unpTIaFE8gSDBoYxMkUl8AsJiknDScor4zIV8uAA+cJV+fLKiXAC2AEY2zXQgHFoNw5QV6NrObh5wXQMjNroKxVNgcEjVBCjDAHTx2gBEabb24he6cAD0j3AMMOYAZnCL2StrQ6MkKtvAUfst1MD1oCtopdBNnvtqrwABbmLgccRwUZwcyiDgQV5hT7ffIYJY5SEAmydEEYMEU-4bJAw7APXjuADG8GG5jAyLgvC4wze-G0TAaEm6D0+oARfPgXFErlxhMYYvCD2RKGsr2R8F4KEG8GuGUx7PUohQYC4B14E3tIARmD1MzScA55nE+tR6MxxHMSAA1liYByUFxeDByBM3sxwgBGNr8IQiCRSGTbFosKoBUC7GbxuYJhbkv5wKGbbZ56a2+MtY7xs5mK7WG4Oe4xsJxgBMSZqqfqjUzBB6Rl4-SpSEU1b2x27Rd79LLFeZVcmNb43frw27TZ0LfStw7IRP+eIWrAACU+ABlH0Y8JR75vYm1h5dbQvr627sPOVEr5tFJdBSwhRlARpYClzA8tJxZXQgA)**

**Comment by RyanCavanaugh** [comment]
You really, really, really want to list overloads in the other order
```ts
type A<Values extends any[]> = {
  get(overload: string): Wrap<Values>
  get(): Values
}

type B<Value> = {
  get(overload: string): Wrap<Value>
  get(): Value
}
```
TS proceeds with overload resolution in declared order and if you list less-specific signature first, they'll be considered as potential matches. Always have longer overloads first.
