### ISSUE TITLE
Bad JSDoc comments leads to generate invalid declaration file

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#37703]
**TypeScript Version:**  3.9.0-dev.20200328

**Search Terms:** `JSDoc` `A required parameter cannot follow an optional parameter.`

**Code**

```ts
/**
 * @param {string} password Passphrase
 * @param {string} [targetRoomId] Room ID to target a specific room.
 * Restores all rooms if omitted.
 * @param {object} opts Optional params such as callbacks
 */
function x(password, targetRoomId, opts) {}
x()
```

**Expected behavior:**
Generate declaration file:
```ts
function x(password: string, targetRoomId?: string, opts?: object): void
```

**Actual behavior:**
Generate declaration file:
```ts
function x(password: string, targetRoomId?: string, opts: object): void
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ Notice the question mark `?` has gone
// error TS1016: A required parameter cannot follow an optional parameter.
```

**Playground Link:** https://www.typescriptlang.org/v2/en/play?ts=3.9.0-dev.20200328&useJavaScript=true#code/PQKhFgCgAIWgBADgQwE7ILbQN4GcAuqAlgHYDmAvtCrrgO4D2qAJtAArK2IAW6uAplFgIU6LHkKlK0ANr40ZfvgBKDBhgCSzALrRV66BoAi0fA1MKl0ZNFyJ+AYyIAzIg+io1GAHRC4y-gImQOsAG1CPL1xoF2h1Inx8fmZfGDgkNEwcBgAjACtHfCoGRHxogHlSogYSZAjRTGjcAFcHbmtohzrQnOQHAGtcP2AoZ2aSB3xqkmgADwAKGnomZgAaC1RFFS8tdZKygEocCigoBYOoIA

Hover the mouse on the function `x`, you can see it's signature is inferred as `function x(password: string, targetRoomId?: string, opts: object): void` which is wrong.

**Comment by Jack-Works** [comment]
Possible fix:

Add it in `checker.ts`, `function isOptionalParameter(...)`

```ts

            const parameterIndex = node.parent.parameters.indexOf(node);
            if (isInJSFile(node) && parameterIndex >= 1) {
                // Check from (n-1)th parameter to 0th parameter
                let descentIndex = parameterIndex - 1;
                while (descentIndex >= 0) {
                    // if the parameter before this parameter is optional, this parameter must be optional too (only for JSDoc in JS files).
                    if (isOptionalParameter(node.parent.parameters[descentIndex])) {
                        return true;
                    }
                    descentIndex -= 1;
                }
            }
```

**Comment by Qiyu8** [comment]
@Jack-Works Are you working on this? your solution looks fine. Is there any way to fix this Bug without recursion？

**Comment by Jack-Works** [comment]
I'm not working on this because I didn't find a way to do this without recursion or big changes.
