### ISSUE TITLE
Can't merge namespace declaration with imported class declaration

### ISSUE THREAD

**Issue by wojpawlik** [microsoft/TypeScript#37712]
**TypeScript Version:**  3.8.3 and 3.9.0-dev.20200330

**Search Terms:**

declaration merging import 

**Code**

```ts
// telegraf.d.ts
export declare class Telegraf<TContext> {}
```

```ts
// index.d.ts
import { Telegraf } from "./telegraf";

declare namespace Telegraf {
	export const foo: number;
}

export = Telegraf;
```

**Expected behavior:**

Declaration merging of `declare class Telegraf` and `declate namespace Telegraf`.

**Actual behavior:**

```
typings/test/index.d.ts:1:10 - error TS2440: Import declaration conflicts with local declaration of 'Telegraf'.       

1 import { Telegraf } from "./telegraf";
           ~~~~~~~~
```

**Playground Link:** 

(how to create a playground with 2 files?)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This isn't how to do a declaration merge.

**Comment by wojpawlik** [comment]
Thank you for responding. Do you mean, only declarations in the same file can be implicitly merged?
I wish to keep `class Telegraf` out of `index.d.ts` to keep the file short.
Is there any other way to achieve that? I found a hack, but it violates DRY:

```ts
// index.d.ts
import { Telegraf as _Telegraf } from "./telegraf";
declare class Telegraf<TContext> extends _Telegraf<TContext> {}
```
