### ISSUE TITLE
Generic type lost in function output

### ISSUE THREAD

**Issue by GolubevAndreyUA** [microsoft/TypeScript#37710]
**TypeScript Version:**  3.8.3

**Search Terms:**
- Generic type lost
- Generic mapping

**Expected behavior:**
Should determine output generic type when function receives argument with same generic.

In "unknown_1" and "unknown_2" I expect that returned value from "getTest" will be of type "Test\<number\>".

**Actual behavior:**
Function output generic type is lost when argument have same generic type and used in provided function.
If no argument provided then type checking works as expected.

**Code**
```ts
type TMapper<I, O> = (input: I) => O;

interface State<T> {
  count: number;
  prev: T;
}

interface Test<T> {
  getValue: TMapper<State<T>, T>
}

function getTest<T>(test: Test<T>) {
  return test;
}

const unknown_1 = getTest({
  getValue: ({ count }) => count
});

const unknown_2 = getTest({
  getValue: ({ }) => 1
});

const number = getTest({
  getValue: () => 1
});


```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function getTest(test) {
    return test;
}
const unknown_1 = getTest({
    getValue: ({ count }) => count
});
const unknown_2 = getTest({
    getValue: ({}) => 1
});
const number = getTest({
    getValue: () => 1
});

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAKgsgQzJATgHgJIBooHkB8UAvFABQCWAdmAK7ABcUGAlMYbgNwCwAUL1cAgoAZggDG0AMrAEgtDEIBvXlChiA9jUoMolGgFsARkO49VYFBABujGKYC+vftqGiJsCAGdg8pSqgA5hDAAGoIADY0ELaIyEJo0rIQvjgKvI58PMJaYsDk6pSBwTBePgqkgt62pb6symZQlsA0KIWVwA5OPBqU3lBaANaU6gDulAD6AIzERcAl3qT1qkGhEVGMi2qa2lD2rESEGlrA6cymvD19g8Nj4wBMMyvzwIv+K2GR0WSKu-uEk6dzt0Cn09EYhI9iqVXg13msvqQ-lAATw9kCgA)

**Comment by RyanCavanaugh** [comment]
I can't understand from the text what you expect to be different in the code examples. Please be more specific.

**Comment by GolubevAndreyUA** [comment]
In "unknown_1" and "unknown_2" I expect that returned value from "getTest" will be of type Test<number>.

**Comment by GolubevAndreyUA** [comment]
@RyanCavanaugh , can you please check out updated description. Does it make sense now?
