### ISSUE TITLE
Automatic Type Acquisition does not work

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#37723]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.3

**Search Terms**
- automatic type acquisition / ATA
- jest

---

- VSCode Version: 1.43.2
- OS Version: macOS Catalina 10.15.4 (19E266)

Steps to Reproduce:

```
$ mkdir test-jest-types
$ cd test-jest-types
$ npm init -y
$ npm i --save-dev jest
$ echo "describe('xxx')" > index.test.js
$ code --disable-extensions .
```
Now open the index.test.js file in VSCode, see there is TS error because jest type acquisition did not work and describe is missing type annotation.

Does this issue occur when all extensions are disabled?: **Yes**

I would like if the ATA work without the need for workarounds such as:
1) Creating a jsconfig.json or tsconfig.json with explicitly saying i want jest type definitions
2) Installing `npm i --save-dev @types/jest` as a dependency of the project
3) Installing the types globally `npm i -g @types/jest`

**Comment by alesmenzel** [comment]
I used the empty jscongif.json with type acquisition:
```json
// jsconfig.json
{
  "typeAcquisition": {
      "include": ["jest"]
  }
}
```

**Comment by RyanCavanaugh** [comment]
This is working fine for me with the provided repro steps + jsconfig file

**Comment by IllusionMH** [comment]
It's kinda reproducible - requires 10-12s before Jest types will be added to program and I see `any` before that and no indication in status bar.

Steps: 
1. Add `index.test.js` and `jsconfig.json` from steps above. Save `jsconfig.json`
2. See that there is `Fetching data for better TypeScript IntelliSense` in status bar and Jest types available when message is hidden.
3. Reload window while `index.test.js` is focus or open it after reload.
4. `Initializing JS/TS language features` shows for 1-2s.
5. Hover over `describe` - `any`
6. Wait for 10-15s and hover over `describe` again - `var describe: jest.Describe`

So I would say than in my case it's `Fetching data for better TypeScript IntelliSense` which is missing to notify me that not everything has been processed at this moment.

**Comment by geekley** [comment]
In case it helps anyone, setting the `typeAcquisition`.`enable` property to true worked for me for a similar problem.
```jsonc
{
  // ...
  "typeAcquisition": {
    "enable": true,
    "include": [
      "node",
      "vscode",
      // ...
    ],
  },
}
```
Oddly enough, it needed this only in `tsconfig.json`, not `jsconfig.json`. Maybe the default is different in those files?

**Comment by Elyx0** [comment]
Thank god you found this @geekley 🙏
