### ISSUE TITLE
Value not read properly with generic types and keyof object

### ISSUE THREAD

**Issue by joacimastrom** [microsoft/TypeScript#37735]
**TypeScript Version:**  3.8.3

**Search Terms:**
generic type keyof
generic string not assignable

**Expected behavior:**
Should identify that value of id corresponds to keyof DataStructure

**Actual behavior:**
Only infers type string and ignores the value, yields error:

> Type '{ id: string; }[]' is not assignable to type 'IColumns<DataStructure>[]'.
  Type '{ id: string; }' is not assignable to type 'IColumns<DataStructure>'.
    Types of property 'id' are incompatible.
      Type 'string' is not assignable to type '"name"'.

**Related Issues:**

**Code**
```ts

const columns = [{
    id: "name",
}]

const data = [{
    name: "John Doe"
}]

interface IColumns<F> {
    id: keyof F;
};

interface DataStructure {
    name: string;
}

function test<T>({ columns, data }: { columns: IColumns<T>[]; data: T[] }) {
}

test<DataStructure>({ columns, data })
 
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const columns = [{
        id: "name",
    }];
const data = [{
        name: "John Doe"
    }];
;
function test({ columns, data }) {
}
test({ columns, data });

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=22&pc=2#code/FAYw9gdgzgLgBOANgVwLbTgXjgbQN7BxFwCWAJgFxwBEEAhqgKbUA0wAvgLrCiSxxk6MOllwFicekyrUAUmAAWEOABEwzDt2AkIMRgCcAZnRCM4ASQDCYFOigAeAGIA+OOOLkqAa0YBPMIZwjgDcHKHaugbGpqpCdADKMPrIIDDI+mbuRFKMVLD6OgDmoew8hsgQqSSQcHqw9gAqzgAUeAg2aNAsAnFw7FRtSJ1QVFYddo3OOJzBPcJUKnGJyanpjNN9AJRuHDx1MPaLwsspaRktg+NdcyLsm4RAA)

**Comment by ilogico** [comment]
https://stackoverflow.com/questions/54975170/in-typescript-how-to-use-a-string-literal-type-in-an-interface
