### ISSUE TITLE
"K in keyof this['property']" does not properly evaluate to keys of this['property']

### ISSUE THREAD

**Issue by compeek** [microsoft/TypeScript#37737]
**TypeScript Version:**  3.8.3
(also tried nightly and all other versions in the playground)

**Search Terms:**

in keyof this
in keyof this[
keyof this property

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

interface State { test: boolean }

class Test {
    state: State = { test: false };

    constructor() {
        // this works
        const a: State = { test: false }; 

        // the type is structurally identical to State
        // this works
        const b: { [K in keyof State]: State[K] } = { test: false }; 

        // this['state'] is structurally identical to State
        // this works
        const c: this['state'] = { test: false }; 

        // the type is structurally identical to this['state'] (and therefore State)
        // however, this has a compiler error saying it is not assignable
        const d: { [K in keyof this['state']]: this['state'][K] } = { test: false };

        // similar type but using "any" for the values to narrow down the problem
        // it seems the problem lies with what "K in keyof this['state']" evaluates to
        // this has the same compiler error saying it is not assignable
        const e: { [K in keyof this['state']]: any } = { test: false };

        // similar type but making all keys optional
        // this works
        const f: { [K in keyof this['state']]?: any } = { test: false };
    }
}
```

**Expected behavior:**

No compiler error

**Actual behavior:**

Compiler error:
```
Type '{ test: false; }' is not assignable to type '{ [K in keyof this["state"]]: this["state"][K]; }'.(2322)
```

I cannot tell exactly what the problem is, but it sure looks to me like `K in keyof this['state']` does not evaluate to the keys of `this['state']`. Perhaps it is evaluating to a superset of what it should? If I make the keys optional in the mapped type, the error goes away, so that tells me it's expecting more keys than there actually are.

**Playground Link:** 

https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=31&pc=2#code/JYOwLgpgTgZghgYwgAgMpjpZBvZkDOYAXMgEYD25ANhHCMgL4BQTCVc++yAKhITk2RDkhTBBLoxyALw48fYsnhV8KBgG4Ww5AnIhCUAK4Iw5KAAoAlAO3aA9HbwALYFwDuZgNb5Btobv0wZDgJDCxZXAJFZVVGdWQtP2QHZxQwAE8ABxRXETAjE0MoOCoqdORgABMIcGAEErxyNDCIXz8UsBd3Lx8knT1+UhJcAG0AaQr6Twh08hhmsQBdULFxxcYZOSiSGLV4xPbHTtcRgHJRSFP13INjMCKSsorq2vqqRoXINtsOruQPKDeb7aAL8BAkY74M4XCBXTaRBQ7EqxDQJYHCX5pLI5Li3QrFUrlKo1MB1BqmZwnc4tOHmOiVVJQCAwMwoSSQSzooQpJzkNwQABu0AANJSuE4OMF+gBbTLAGhQZDQKBmERwdKgADmFSCuRA5CCHHwwE1IDgpBoXP6gWQlWGyHGk2Q01m80h0Jpi2WYo9Yiuaw2EXkhCRKj2Bx+jmN0vlcEVGWyZEMQUMxpA2oARHR0hmlKrOigBSVDHwPmaoCq3La+fQC8hMiqLRBpVaUsAgqpm1w6w3yE3pcgqMBS25205-hKghmJqBnTM5j7qX7FrnBcWxN3yK2jn8Jd2nCh8HBpShdLL5dAlRXVUeNemdRUuPrDZwTWam1bQUFxHJHbOXQu7pLpcXokNmgZbIiSjIuG24iMAMbsPG2JJkE0pwJ4WrBKUc7pFw5CZKSeglHBkL-D0n4DEEMD2n+Uzzm6XS+iBiwAPxgSA5QMPCwbRDBcTfMwDBAA

**Related Issues:** 

I cannot find anything at all similar to this. I really did search. I looked in the FAQ too.

**Comment by RyanCavanaugh** [comment]
Different syntax has different meanings, of course. At the point you have a mapped type over `this`, TS really believes you meant to do a deferred type operation, and it's correctly erroring because a subtype of `Test` could have a bigger type for `state`. Contrast with:
```ts
        // OK
        const g: { [K in keyof Test['state']]: Test['state'][K] } = { test: false };

        // OK
        const h: { [K in keyof Test['state']]: any } = { test: false };
```

**Comment by compeek** [comment]
Thank you for the immediate response!

Ah, I see. I hadn't considered what happens if `Test` is extended. That makes sense, I think.

I'm not sure how to accomplish what I want then, if it's possible. Here's what I'm really trying to do:

```
import { Observable, of } from 'rxjs';

interface State { test: boolean }

class A {
    setStatePropertyWhenAnyObservableEmits<TProperty extends keyof this>(
        property: TProperty,
        state: { [K in keyof this[TProperty]]: Observable<this[TProperty][K]> }
    ): void {
        // subscribe to the observables and update the specified property when they emit
    }
}

class B extends A {
    state: State = { test: false };

    constructor() {
        super();
      
        this.setStatePropertyWhenAnyObservableEmits('state', { test: of(false) });
    }
}
```

Playground link: https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=22&pc=2#code/JYWwDg9gTgLgBAbzgeQEYGcCmUBuBDVAG0wBo4IAzOAXzgqghDgHIoAPAK3WYG4AoPsAB2MbBTwBjTHADKMPKMRxR6GAC44qCBGJ4hNARMJ506OAEFEfODbhYYchZgAKDMNhgBPAOoALTELmQp5oWLgExACiIMAw6AA8ACquEO6wnnCYbKJCACZmANaYnpTKvsDoAHwAFNa29WBuHp4ayU3pJHX1NqpOGkgA2gDScMJwRSVUMOXoA22pzQC6ixqh2PhEmPHTFXMpaV6Lw4uVBvUAlBo4EMC5Vt22APSPdgCuGBJQwKjSMBBl0ggGHWEUwZj0d1eYFyTgBdncEmAFGAmDujQW6TgAHd-PppsVMjEYF0DNRDMZTHAAEKZbIBfIWe62XqiDSORQAXiUKnUdDwhCwNH4JIkECEqigrwkfyg1XOTIe6Ch2Dl-AeJPqO3QADp7OyXO0vH4AkEQsDwptorF0NVmCzMMwyEgeRpKNVxALMPLqOc1bYydQgA

In the child class, I want to be able to pass a property name of `this` to the method and have the second parameter be a mapped type according to that property. Is this possible?

**Comment by compeek** [comment]
I'm thinking about this some more and came up with the following example to try to prove some of this out to myself, but it seems like a subclass expanding the type from the parent class leads to some problems and I'm confused why it's allowed.

Notice that in the method on class A, it will be setting `state` to a value that is incompatible with the type defined for the same property in class B. Why is this allowed?

```
interface State { test: boolean }

class A {
    state: State = { test: false };

    setStatePropertyWhenAnyObservableEmits(state: { [K in keyof State]: State[K] }): void {
        this.state = state;
    }
}

class B extends A {
    state: State & { test2: boolean } = { test: false, test2: false };

    constructor() {
        super();
      
        this.setStatePropertyWhenAnyObservableEmits({ test: false });
    }
}
```

https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=19&pc=2#code/JYOwLgpgTgZghgYwgAgMpjpZBvZkDOYAXMgEYD25ANhHCMgL4BQTCVc++yAgjk8gOSFMEEuhHIAvDjwRCJeFXwoGAbhaChEMOMgAFKOQAO0MAE8A6gAsIIbiDMB5UsqgA3OKRoBRALbAwfAAKYUgSXABtAGlkUGQAawgzchg0DEgAXTF0iGiMxgBKEjdyYAATPk1NMCtgfAA6UJRpJvVNZmZWdk5kACFkCAAPSBAyrl5sfkEm7IkAMhkCMAAmEgpqWnoGKUW5YmRFZQAaWUJVg7glFXUpgQRyEEIoAFcEMHIoIILKqoF8Z5MnwKbSqtyqNTqjW0uggBmMpksNjsDmcrg8XggfgCwVwSwUl2UhRBAg6QA

**Comment by compeek** [comment]
@RyanCavanaugh If you have any insight on my additional questions, I'd be most appreciative. I do think the last thing I brought up is an interesting downside to TypeScript allowing the child class to expand the type of the property in the parent class. It seems like the child class should only be allowed to expand it to a type that contains additional optional properties so you don't have the scenario where the parent class is assigning data to the property that is does satisfy the type in the child class.

Maybe this is common across languages, but it seems to me like this is somewhat of a significant problem.

And to be clear, I believe this only applies with `strictNullChecks` on.
