### ISSUE TITLE
TSX @ts-ignore comments no longer suppressing errors in TypeScript 3.9

### ISSUE THREAD

**Issue by brieb** [microsoft/TypeScript#37738]
**TypeScript Version:**  3.9.0-beta and 3.9.0-dev.20200330

**Search Terms:**

ts-ignore 3.9 tsx @ts-ignore

**Code**

```ts
      {/*
      // @ts-ignore */}
      <MyOtherComponent prop={123} />
```

**Expected behavior:**

Error suppressed when running tsc (TS 3.8 behavior)

**Actual behavior:**

Error emitted when running tsc

**Repro Repo Link:** 

https://github.com/brieb/ts-39-issue-ts-ignore-tsx

**Comment by brieb** [comment]
I was trying to beta test TypeScript 3.9 and we have some `@ts-ignore`s in our TSX code that are no longer being respected, so we aren't able to get a passing build to assess performance improvements.
cc @DanielRosenwasser

**Comment by mohsen1** [comment]
cc @JoshuaKGoldberg

**Comment by brieb** [comment]
> line comments still work

Definitely true, though is it always possible to express `@ts-ignore` as a line comment in TSX?
I'm trying to think of a counter example.

I suppose this is also an option if the error is on the component
```
    <
    // @ts-ignore
    Comp />
```
Though that does break syntax highlighting in vscode.

My guess is that this was an unintentional breakage though

**Comment by JoshuaKGoldberg** [comment]
Indeed, this was an unintentional breakage. Specifically the breakage was here: https://github.com/microsoft/TypeScript/pull/36014/files#diff-08a3cc4f1f9a51dbb468c2810f5229d3L1782 
Sorry for bungling up your TS 3.9 usage @brieb! 😅 

TypeScript _used_ to check if a line looked like `// @ts-ignore` on its own, regardless of whether the line was part of a multiline comment. I suspect that itself was an unintentional side effect of how it was checking for comments, and just happened to work well in the .jsx/.tsx use case?

TypeScript _now_ understands where single-line `// @ts-(expect-error|ignore)` directives are, and only ignores comments after any of them. I suppose a good fix would be to also understand the last line of multiline comments when that line includes a comment directive. E.g. `/* \n // @ts-ignore */`.

..but I'll defer to the Typescript team. Happy to send a PR if that or another strategy is approved!

**Comment by brieb** [comment]
No worries, at all! Glad we could help catch this. We're so thankful for all the great work going into the TS 3.9 release!! 😃 

Ya, the format is not ideal. But, that's the best that we came up with here
https://github.com/microsoft/TypeScript/issues/27552

Looks like there has been some follow-up requests about a cleaner syntax for this
https://github.com/microsoft/TypeScript/issues/31147

`{/* @ts-ignore */}` was my preference in the original issue as well. 

Though I'm not sure how much scope it would add to accept that format vs fixing up the good 'ol
```
{/* 
// @ts-ignore */}
```

**Comment by DanielRosenwasser** [comment]
My intuition tells me that if `@ts-ignore` appears in the last line of any comment, the following line's errors should be suppressed.

**Comment by JoshuaKGoldberg** [comment]
Swell. Just to be clear @DanielRosenwasser, is your intuition strong enough for TypeScript to accept a PR making that behavior change?

**Comment by JoshuaKGoldberg** [comment]
Ping, sorry to re-tag you @DanielRosenwasser - since TS 3.9 is close to release, is there a way this could get triaged? I would very much like to fix this regression before the major release. 🤗

**Comment by DanielRosenwasser** [comment]
I'm so sorry this didn't get triaged and fell off my radar. If you can get a PR out, we can work on it. Ideally this would go in before the RC, but I don't think we'll have time for that.

**Comment by JoshuaKGoldberg** [comment]
Swell, thanks! 🚀 #38228 minimally adds directive parsing for multiline comments.

**Comment by DanielRosenwasser** [comment]
Thanks to everyone involved on this thread for your patience, and thanks @JoshuaKGoldberg for the quick fix!
