### ISSUE TITLE
Degenerate compiler performance when processing large unions

### ISSUE THREAD

**Issue by nomcopter** [microsoft/TypeScript#37744]
**TypeScript Version:**  3.9.0-dev.20200328

**Search Terms:** large union, performance, indexed access

**Code**

```ts
type BigUnion = {
  name: '1';
  children: BigUnion[];
} | {
  name: '2';
  children: BigUnion[];
  // 1000 more .......
} | {
  name: '1003';
  children: BigUnion[];
};

type DiscriminateUnion<T, K extends keyof T, V extends T[K]> = T extends Record<K, V> ? T : never;

type WithName<T extends BigUnion['name']> = DiscriminateUnion<BigUnion, 'name', T>;

type ChildrenOf<T extends BigUnion> = T['children'][number];

export function makeThing<T extends BigUnion['name']>(
  name: T,
  children: ChildrenOf<WithName<T>>[] = [],
) { }
```

**Expected behavior:**
It compiles reasonably quickly.

*Note:* This happens even when `children` is not a recursive reference. In my project `children` is an array of specific subtypes of `BigUnion` but it is closed source.

**Actual behavior:**
It takes over 90s to compile on a 2019 Macbook Pro using node or the playground link.

```
  % tsc --noEmit --diagnostics --extendedDiagnostics --generateCpuProfile out.prof simple.ts
Files:                           6
Lines:                       27987
Nodes:                      122358
Identifiers:                 44171
Symbols:                     32200
Types:                       19618
Memory used:               234674K
Assignability cache size:  2055962
Identity cache size:             0
Subtype cache size:              0
Strict subtype cache size:       0
I/O Read time:               0.01s
Parse time:                  0.30s
Program time:                0.32s
Bind time:                   0.15s
Check time:                 97.49s
Total time:                 97.95s
✨  Done in 98.49s.
```
[cpuprofile.prof.zip](https://github.com/microsoft/TypeScript/files/4418098/cpuprofile.prof.zip)

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=Nightly#code/C4TwDgpgBAQglgcwKoDs4HsVQLxQN4BQUUKAhgLYQBcUA5AIy0DcRUAxgBZwA2AJgE4QUNeMjSYA2gF0WAXygAffKzKUatAEzNWnHgKEjEqDCmlzFy4qup0AzNuK6+g4bCPjTMgvKWErFG1oAFgd2LmcDNzETM28LPxIA9QBWUKd9V1FjSS8fS0S1OgA2NPCMw2ic818VJLoAdlK9Fwrsz2r863UADiaIzPcY3PjawtoATj7yqLbYvISuunoABimWmY85kf8x+kYWRzL1rM3hmp3A+i0DsObIk6GOhbqGexv048GquPOCy5D3kd7l92j9Oi96KlAXcBpVQfNRpcStD+q1Tk9Eep6I0UdMHt8ERcsb1cZ84VtfosGJNScDyWdwWMNKtabDZgznkz9jogWz0WDOYENNceTC0Y8BZi6Bo3qLURsJYS-uoNAC5XiQRTGUKoeqyeyMUTpci9XSDZKjZocaa+YrtsrpSSbeKCfaqRoac6Fa7KS9bCyvfj4W6-dzDmLvcHfWNbCLw-Kg1rBepbLL4xr6YaHbRbGr0-r+UqqbZdfmzYWQzGTWXbT7tSnrTWXVH63YnU3I0mpTnPR3Exzu0EA33NQPLUEw7cE6Os1SgnGpxnzUWXkE04uC3bo4EgnmN+Wt63gqX97WW8m6EFq6fm13x42b52x9mgu3H-3Z6ve++Zxbs8lhx-TM-ypZJJw+A86wvWhkgXCCzzvf913g29n1AvcUKfT8xmSE9MI-ECXmSa98N-FccIfUjgPIwJkjfKjl0rWjvwYitt3UIpANYw9oKKcDeVQ7DAiKOCBKwwixiKZCxIImiOIwmSyKYji8MU6jlOKEi1MY9jiko7S2KPIp6IMnjuyKFjTKg7t6i4qzzxs-iI1kjTaHqUTnKU3S3Okzz1O8+oFL8nSj3qVTgsM6D6i0iKzMtep9Ni6z4pMpKHPiyy0sQqlujsrK0JebonOnfyj26DySpC6Dul8yrIu7bogrquLs26cLmuS1qYo69LWsSnrssK1KBoKsZukykahPUcY8smiTAnGYql3qy1xgq5aWqpcZao2zqtqa3beq29rDsGsZxm607RoW-qrqmuhxmGu75umibnrkpZllm97XJWJbNz2iFlnWgGjqBnbQbOy5lgOyHrqxZYTrh+6GGWS7kZez7boxj7UaenHfuWN6Ce8vZvpJo89n+yCwd2K41hpqGsXoCHGfhpZ6FhtmUb2JHucxhh6HR-ncb2bGRd++h8Yl0n6GJmXKeZBmEPZhgNGplWeeFZXBIFq5Wc1vXVR18TRY0PnDbN4XLd+jRxZt0mNGlh3Ffll3oJZ8mFY92wNd10XYxNlzSdTIOvMp3Mw9Kn2Lf937bGtuOQ-tpOI+d1OfbdjPu05r33Zzico6qguQe9guDezy1Oa5-Oq6CWPTd+q8i5W7NOZTxvSdfFvNohIIs87ymAJ7wHdjAkfacuWCJ6ZpZkgrwePeSGvK7b3CZ9VyFE8XnPkg74Oh-Tneq+SAeD49ziN55vir71kTb9FqSH9+ooV+Ptuigb8+c6Kbfv6roo+9w4XyPv-D+Z9gE51ss-Um9Q-bvypNiUutc271AXmAxBgUYGUzCtgj20U8FQKAdHKBoDIFV3qBAkhVdcqEJofAjBEJyp0LbjVFhiDGrsKYV-chrC-68I4cQ4uNCyHUNYVQ4RbcZpcN2ItGRlw1ryKxNtJRSxxhv0YbInhYjEEXVUdSIRrddGiMkboiRRiXjMjzqvd0ywGECMscDfRzJ0EOKZDDZxiNPH8J0Y4wxvd3EmIse48xAShQrGcXsSJyCbGWJZpEjRbjwnaNMXEnxqSuT+NHuEoJYSVRy2cUrVksSmTq0KTEhBliZSFMSb40pKTglCg0OkxpKo7aFNydktpoSunSn9M432AyKmaKFKHYplSmSR3GSMlUJYBktLyX0rJk9ZmdJWX0np6zNBDmcYXaZSSVTzl2a4upQpdy7IaYs7ZCzenbOWbPbZayHmqk2c84e+zTkqnHh8jJOphkHOlPPZxy9gWXNuebG5Wzzb3NVubJ5sLT7OMvj81pxp7GfONP8jFmgn4oquc02pvyVSfyRZC55gCkXwpRs015sLoF4vBXA5x7lmUnKJdKLBDKoW4K5c8ghvK6UwupfUKlAs7a0upbQgVkr0Xss0Mw6VYq2GKtxk7QlqL5Vgqhd0MlsLuhCqVaK1V41nHSJVa5D0sqNUeixXKj0bLrXqNNVq55ejzXeQ9Aa1Vj1TUSoFv6axEzAj+itVc-0tqNX+gdWGjx7qjz+hdarf0uqUb+i9a5f0RqM1E30b7QNMy7BRLjdBX2Eaw3xOLd2X26ry2JtTULXN2JG1Zu8r7P1uNYz5oBTmMplbLSxjLbc2M0ah3Gz7dmWMdb-XNNze08dxYnazvbRm-p86-SDLXTGQOm7g1jMDN21MNah1zJ3SmBOubbDptbbYFt8bbDLtbTs09dg9n7uxbmQdWzcwjq-ec59OZ665ubv+3MV743dxA-3XN7y31ypLKGod08QNAuQ0er969kMpv9XvaDt6S2IpA8i2Dkab6Ec-Q8hOP6KOv1zSSwjWGO0UsI3hqtFlc30uI2GplIGWU8ao0mzlnGh08qE1+-lomKMJXYyx-tlDc1Sok0moq8nyNKf46mzhIG2ryYYxm-V8mZMTpNSBs1inU1yJM6p8z6n-VOpM1OjtbqzO2bAyWn1JmH1HiHF27FQ4ENbKHFZgWQ4bO4yHGhh5Q4HOuSHLp7yQ5XODmWIZucOb-0Th83Kic-nIv03SxW5zYXOb6InNF+LDb8uJfHFLErBT0tFMKzF3tjX4va3q6FprEXVbzjK15md9WqsvkXfVzz0E1yZY1WuHL3Xt0ta83ukcvmplzbGyelbg5z3pcvSVm9O3RuDifet8cr7FtZaOeltcJW-1HZfIBi7cWvNBEG3OCDN2Xv7fHDB07k3vlvdXEhv7Yx64dfiyC9LGHAc7mIiVnD4OUv-Y+y+Ij32rlXmmyjK8QWwu4sh+oK8XWMd0dx5eX+JWmPE+CMZMniO5wcZR7cp76Pgu8Yp09kHXnBP04CyJrnkXxO8+61J9LIqStyfSwpgXGPlPi6xzF5VrPNMK962NnVJX9Pi-h0D4zrPTOS+CxZnXsv4sqPS3ZnXyvBxOb12F8Yz2vya53OMGnREvr6IAkz3GAEjdHgAuz6CAECcCwAhby0AEHv++WHbnCyW3dpYp2BCbVywIe9cmBb3-uCvW9T8V-9YEQ--gq-Hptueasl+dzhBrWfvKwRT9Xtr8fqm57HQ3-PoF+sN6j7RYbDfy+0VXfHjdA-0-dnnn7kfy2q8+7W5P-3m2B+d5SLt3P963eHZnyPk7QE5XL2H6Hy7ufrvr7363oiwH49PdXw7lIUHc9fa3xq3CtefcA6P-+FD8ewcf5PzhaHt+F90FwivwAII3j2R3vyT1I1AN33-Bx1f1Aho1zyJzgKIlJ0QP-xgip0QN7xSDp3ANuT3if39xZ2QIojH1D05zwK2T3m-1on50oIeT3nQL3iAJgjF3jwl3oNVjokIJHwVXYLIP-EVxINom01z1VzEKYO6BYLomwIAN104JRlPh4ND0UVzxN3jzN2EJSHGBoO0PDxH1tzd3cw0NkNoE4kT1uU4mUOzE4mgKpE4gEPsNjQp04l0OKDRn0U4nQM4hYM4lML4gsK2T4msPsLyxcMzwUIFj4kD1xj4jcLMMLy0OKGL3CN8LqxcMr0iNiOaySLMPr1yJEkcJeBEhiNchEniJEn0MtBEm8O7wKI9E8P7wKMH2aLsOKIWyyLKIn06O8ikgqLn2aO8KXxcJX3-VfkCIeVfhCOKPOxcP3zmNKN6LuzmKqJsIvzGNewKJvxcLv24ksN+wKJfx6KMnf0OMWJOIqN-x2O8Lok8JAIKLAL2KCMgIeLaMklgOON4gQJcKQM+PMlQJ+O8MwJ+P8NwKeMmO4xcOIL+OqLQU8IoPBNVkAQqLoMRJRkAW8JFzGLYIKI4LRKiOlxcL4NxKKMkiEJhJsNEKJNWPsPVyJN8O1wKPkPxNiINyZLeOEnUKZPON4h0M8KtwpPsMMLGOMKZNMNsgmNVlsmmLGFsg5PUFslJMCFsh5Jsi8X-VshpJeFsnQNshYNsnFIiQ1KLQpzgXlIaAiJZNcjgVVPikhH0TgS1NlJSNyLgX1PSNdMyKtIChyMFO1PyL9NlMb1NOb09PiPcidOVLnRDP1IaI1KaMDOVJaMTIVNm1dI6O9NCm6MzKimnxTIaAGPzJ8l1OGPTPFLXyLMChlOVNmNdPmLrNtOzECnDLPzrN1M2MrO2NdN2PsgeTCmrIVKOJzJslOMrM-27PDKuO7N1NuI1PuMrMeN7KlJeIXPNLcg+OHPim+NdN+M3KbIBJ3N1OBJ3PFLBKXJRgSgHIaGhL3KpASiVIVIRPPIFgSnDNROfNxgSl1KxNNJxMrLxI-OtMJNdOJP-IfIaHJNvO1KpJAsjIVLpJAv1MZMrOZMAoCjZJQrXMoXArck0JQvDIFKgtlOFNNNFJQtMNyklJRlyivNoFyjXNyhwtykbJynVIp1yjgroFynQNyhYNygoqNPYpNNyKKgYstLQrKhzyEviKKk4ropdKLKKj4o9MUq9Ikuql9KIsCHKgYuDJEtDNUpkvb30p4rqNUoooTK0p6GTKsq4rTMUozPUoamzKcstBqhksLNsrou23-Rqj4tGPYorK8salosagYvrMUsP0ipktbMip4o7OCq7MUp7PymooOOSoYtHOCvHOSpkqnOSp4tnPYvnOCsXNSoFh1VCvvl8o3Ncq6hYsKl3LqpygPMUvJxEuPLaoorPPKtxn1VCpvOasKjhN8qfN6tcn1RkvfPGu8n1R4p-JEr-OCoApmrKmAsUtAuWqYsgqGrGhgo2rkqkJ4qkP0SkIotQtWuqgwuCtUPYq5MUrwpupksIt2u0pIpErIputMJmiooFhmlopmjXJmhwpmgavOjYtyJmjkpmnQJmhYJmm+sEshuEqLMWiBvEsuu7EWjBoWntP-UWmhoUq8sWnhpUuJrUsxtWk0teumgDPJpBoMvJviLWmhujMhrMvJu+ssppoehsp5omHsuJscspuzG2hxumjzKFuhp8op22nhoCshqCv5vUQBtrNRoiuJqis1uZtis1thoSuVqSuJpSrmlxh0IBqHOVqyqtvFoegh0hvyuNthqKodu+rKtNtcgugBuqtltqpFq2m3NRqav9peAumhvaqDvhrY3xp6o9u8ltwBsGpDvOhGtlrGrjqPFt2Zumozuglt1hoWtRqWuVpWtzqxvWuJs2pLpBp2uToWn2sruhoQtRpOvxuQuJourLtWmuuVtushvuo7ttomD5Pxperrtelhs+t7tMJWFd3-VntotnrXNntCxYAIFAEgCgAABE4AABnNgfgOAcgOAMgYACANoAAHgABUAAaKAAAaSgAgAAA8z6UBeBd6oAABrCAEAdAAAMygFvqgAADUn7X6hAP6gGJB76pAAA+HAIB8Bt+qBgAJQgDYHQH4F4AvvvrvpAYQYAH4kGaAUAIAAA3CAfgNeje6AAAdTgGAA4AADkAhr7kHIHP7ExaBrBaB4HEGd797D7j7T7z6PAL6gw76eGAhaA76r64GaHwBoAABhXkAAeX-vYZfpQa4ZBAQdwCvokFoHgj4YkBQAAFdyAAAjKhrwAgF+sALB4AKAf+8xlANgYAEwFx9AdALRiB9+3R8kaRygPhuBgACilFvq9FUZhA0YvoYaYdYcoGvrgbgekEQekBvoIAAEp8AoBZACAgA)

**Related Issues:** #29350

**Comment by weswigham** [comment]
Ohhh, 86.44% of total time spent in `getRegularTypeOfLiteralType`? Yeah, that sounds degenerate. Looks like we don't cache that calculation, so we're re-iterating over the massive union every time.

**Comment by nomcopter** [comment]
Thanks for a quick fix - clever optimizations!
