### ISSUE TITLE
tsserver not providing semantic diagnostics for files included in other subproject's `tsconfig.json`

### ISSUE THREAD

**Issue by JaydenNavarro-at** [microsoft/TypeScript#37741]
**TypeScript Version:**  3.7.2

**Search Terms:** tsserver, tsconfig, semanticDiagnosticsSync

In `tide-mode` in emacs, I noticed that typechecking errors were not appearing in some files, despite syntactic errors being shown. Inspecting the `tsserver` log I noticed that `semanticDiagnosticsSync` responses were sending empty bodies despite there being semantic errors in the file, ones that `tsc -b` catches, so it seems to be a `tsserver` issue. I also reproed directly on `tsserver` using the following two requests:

```
{"command":"open","seq":"1","arguments":{"file":"/path/to/file/my_file.tsx","scriptKindName":"TSX"}}

{"command":"semanticDiagnosticsSync","seq":"2","arguments":{"file":"/path/to/file/my_file.tsx"}}
```

The project I've seen this in contains several subprojects, each in their own directory with their own `tsconfig.json` that `"references"` other subprojects. This problem only happens in files that are explicitly `"include"`d in referenced subproject `tsconfig.json` files. If I comment out the line inside the other subproject's `"include"` that lists the file, and then restart the `tsserver`, `semanticDiagnosticsSync` properly shows the errors in the original file.

**Comment by RyanCavanaugh** [comment]
Can you provide a more concrete repro? Trying to reconstruct this ourselves from prose is likely to miss some important details of your setup.

**Comment by JaydenNavarro-at** [comment]
Here's a minimal repro I just verified exhibits the issue:

File structure:
```
tsserver_repro
 |- tsconfig.starter.json
 |- proj_a
    |- tsconfig.json
    |- my_file.ts
 |- proj_b
    |- tsconfig.json
```

`tsconfig.starter.json`
```json
{
    "compilerOptions": {
        "composite": true
    }
}
```

`proj_a/tsconfig.json`
```json
{
    "extends": "../tsconfig.starter.json",
    "references": [
        { "path": "../proj_b" }
    ],
    "include": [
        "."
    ]
}
```

`proj_a/my_file.ts`
```typescript
function test() {
    let num: number = "string";
}
```

`proj_b/tsconfig.json`
```json
{
    "extends": "../tsconfig.starter.json",
    "include": [
        "."
        "../proj_a/my_file.ts"
    ]
}
```

Run in `tsserver`:
```
{"command":"open","seq":"1","arguments":{"file":"/path/to/tsserver_repro/proj_a/my_file.ts","scriptKindName":"TS"}}

{"command":"semanticDiagnosticsSync","seq":"2","arguments":{"file":"/path/to/tsserver_repro/proj_a/my_file.ts"}}
```

With above config `tsserver` outputs:
```
{"command":"open","seq":"1","arguments":{"file":"/path/to/tsserver_repro/proj_a/my_file.ts","scriptKindName":"TS"}}

{"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/path/to/tsserver_repro/proj_a/tsconfig.json","reason":"Creating possible configured project for /path/to/tsserver_repro/proj_a/my_file.ts to open"}}
Content-Length: 142

{"seq":0,"type":"event","event":"projectLoadingFinish","body":{"projectName":"/path/to/tsserver_repro/proj_a/tsconfig.json"}}
Content-Length: 621

{"seq":0,"type":"event","event":"telemetry","body":{"telemetryEventName":"projectInfo","payload":{"projectId":"064b3ac811ddf556a63333eba2e5c6e48b49b26f2ae9ba2006b1f2bd12a0e5b8","fileStats":{"js":0,"jsSize":0,"jsx":0,"jsxSize":0,"ts":1,"tsSize":52,"tsx":0,"tsxSize":0,"dts":5,"dtsSize":1058342,"deferred":0,"deferredSize":0},"compilerOptions":{"composite":true},"typeAcquisition":{"enable":false,"include":false,"exclude":false},"extends":true,"files":false,"include":true,"exclude":false,"compileOnSave":false,"configFileName":"tsconfig.json","projectType":"configured","languageServiceEnabled":true,"version":"3.7.2"}}}
Content-Length: 226

{"seq":0,"type":"event","event":"configFileDiag","body":{"triggerFile":"/path/to/tsserver_repro/proj_a/my_file.ts","configFile":"/path/to/tsserver_repro/proj_a/tsconfig.json","diagnostics":[]}}

{"command":"semanticDiagnosticsSync","seq":"2","arguments":{"file":"/path/to/tsserver_repro/proj_a/my_file.ts"}}

{"seq":0,"type":"response","command":"semanticDiagnosticsSync","request_seq":"2","success":true,"body":[]}
```

Note the empty body in the `semanticDiagnosticsSync` response, despite the obvious type error in `my_file.ts`.

If I comment out the `"../proj_a/my_file.ts"` line in `proj_b/tsconfig.json` here's the output instead:
```
{"command":"open","seq":"1","arguments":{"file":"/path/to/tsserver_repro/proj_a/my_file.ts","scriptKindName":"TS"}}

{"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/path/to/tsserver_repro/proj_a/tsconfig.json","reason":"Creating possible configured project for /path/to/tsserver_repro/proj_a/my_file.ts to open"}}
Content-Length: 142

{"seq":0,"type":"event","event":"projectLoadingFinish","body":{"projectName":"/path/to/tsserver_repro/proj_a/tsconfig.json"}}
Content-Length: 621

{"seq":0,"type":"event","event":"telemetry","body":{"telemetryEventName":"projectInfo","payload":{"projectId":"064b3ac811ddf556a63333eba2e5c6e48b49b26f2ae9ba2006b1f2bd12a0e5b8","fileStats":{"js":0,"jsSize":0,"jsx":0,"jsxSize":0,"ts":1,"tsSize":52,"tsx":0,"tsxSize":0,"dts":5,"dtsSize":1058342,"deferred":0,"deferredSize":0},"compilerOptions":{"composite":true},"typeAcquisition":{"enable":false,"include":false,"exclude":false},"extends":true,"files":false,"include":true,"exclude":false,"compileOnSave":false,"configFileName":"tsconfig.json","projectType":"configured","languageServiceEnabled":true,"version":"3.7.2"}}}
Content-Length: 226

{"seq":0,"type":"event","event":"configFileDiag","body":{"triggerFile":"/path/to/tsserver_repro/proj_a/my_file.ts","configFile":"/path/to/tsserver_repro/proj_a/tsconfig.json","diagnostics":[]}}

{"command":"semanticDiagnosticsSync","seq":"2","arguments":{"file":"/path/to/tsserver_repro/proj_a/my_file.ts"}}

{"seq":0,"type":"response","command":"semanticDiagnosticsSync","request_seq":"2","success":true,"body":[{"start":{"line":2,"offset":9},"end":{"line":2,"offset":12},"text":"Type '\"string\"' is not assignable to type 'number'.","code":2322,"category":"error"}]}
```

Note the correct error body in the `semanticDiagnosticsSync` response.

**Comment by JaydenNavarro-at** [comment]
The original repro I gave was incomplete as `tsc -b` could not run. I've edited it to more closely reflect my real project structure and added the `tsc -b` output.

**Comment by JaydenNavarro-at** [comment]
One thought I just had was that it could be an issue that `tsserver` has `configFile` set to `proj_a/tsconfig.json` instead of the root-level `tsconfig.json`. However, I tried changing `proj_a/tsconfig.json` to `proj_a/tsconfig.proj_a.json` (same for `proj_b`), and updated all references to match. `tsserver` then properly used the root-level `tsconfig.json` as `configFile`, but the `semanticDiagnosticsSync` issue was still present, so the file naming does not appear to be the cause of the issue.

**Comment by JaydenNavarro-at** [comment]
Changing `proj_a/tsconfig.json` to include `"prepend": true` fixed the issue for me! Now it looks like:

```json
{
    "extends": "../tsconfig.starter.json",
    "compilerOptions": {
        "baseUrl": "..",
        "outDir": "../out/proj_a",
        "rootDir": ".."
    },
    "references": [
        { "path": "../proj_b", "prepend": true }
    ],
    "include": [
        "."
    ]
}
```

Out of curiosity, why is `"prepend": true` necessary to get this to work? As I'm unsure whether the original repro still exposes a bug (despite the known workaround), I'm not closing the issue for now. If it turns out this is intended behavior and `"prepend": true` is explicitly required for this to work, feel free to close.

**Comment by JaydenNavarro-at** [comment]
After investigating more, it seems that `"prepend": true` doesn't fully solve the issue, even in my minimal repro project. So this issue is still outstanding.

Also, to clarify the project structure more: `proj_a` references many files in `proj_b`, but `proj_b` only uses a couple of files in `proj_a`. They can't reference each other, as that would introduce a circular dependency, so `proj_b` just explicitly includes the few files it needs from `proj_a`.

**Comment by JaydenNavarro-at** [comment]
Added the file to `"exclude"` in `proj_a/tsconfig.json` fixed the problem in the minimal repro. However, in my real project these are all `.tsx` files (not `.ts`) and `"jsx": "preserve"` is set in the starter compiler options, and for some reason when I convert the minimal repro files to `.tsx` and add `"jsx": "preserve"`, including the file in `"exclude"` no longer works!

**Comment by JaydenNavarro-at** [comment]
I've figured out the error, due to this line in the `tsconfig.json` section of the handbook:

> Any files that are referenced by files included via the "files" or "include" properties are also included. Similarly, if a file B.ts is referenced by another file A.ts, then B.ts cannot be excluded unless the referencing file A.ts is also specified in the "exclude" list.

The issue I was hitting was that there was a long chain of references down to the affected file, which all had to be excluded in order to properly exclude the file.

**Comment by JaydenNavarro-at** [comment]
Given the above, what this boils down to is that `tsserver` can't handle circular dependencies (double typechecking) that `tsc -b` seems to handle just fine. It would be great if `tsserver` could be made consistent with `tsc -b` and typecheck these files even if they are included in two different projects.
