### ISSUE TITLE
I hope the type checker to report an error when I call a function which return never.

### ISSUE THREAD

**Issue by zhuobinggang** [microsoft/TypeScript#37747]
For example:

```typescript
class OpenBox implements Box{
  open(): never{
    throw "No I should not call this method"
  }
  close(): CloseBox{
    return new CloseBox();
  }
}

new OpenBox().open() // I want the type checker to report an error.
```

**Comment by DanielRosenwasser** [comment]
It's no more of an error to call a `never`-returning function than it is to write a `throw` statement. 

Maybe what you're requesting is that we report an error on unreachable code following that statement, but that's a design limitation (see https://github.com/microsoft/TypeScript/pull/33622).
