### ISSUE TITLE
Inconsistent behaviour with generic type parameter defaults

### ISSUE THREAD

**Issue by jerguslejko** [microsoft/TypeScript#37755]
**TypeScript Version:**  3.9

**Search Terms:** generic parameter defaults

**Code**

```ts
type Foo = { type: 'foo' };
type Bar = { type: 'bar' };

export type OnlyFoo<T> = T extends (infer E)[]
    ? E extends Foo
        ? E
        : never
    : never;

export type NotContainsFoo<T, X = OnlyFoo<T>> = [
    X,
    OnlyFoo<T>,
    [X] extends [never] ? true : false,
    [OnlyFoo<T>] extends [never] ? true : false,
];

type Bug = NotContainsFoo<(Foo | Bar)[]>;
```

**Expected behavior:**

`[X] extends [never] ? true : false` and `[OnlyFoo<T>] extends [never] ? true : false` should resolve to the same type as `X = OnlyFoo<T>`.

The `Bug` type would therefore be `[Foo, Foo, false, false]`.

**Actual behavior:**

The `Bug` type is `[Foo, Foo, false, true]`.

**Playground Link:** [Playground link](https://www.typescriptlang.org/play/?ts=Nightly#code/C4TwDgpgBAYg9nKBeKBvKpIC4oHIBmCuUAvgNwCwAUJtAEICGATsmhuBDrgEbPHnVqEAB5g4TYO0hQA8gDsANiHhwAPABUAfK3VQRwCHIAmAZygAKAJZz8EFgFEAlAG0AutSieoAfij29wgbGZioeXuG+9mHhnjhyEABudtFQcYl2lFRCouKStFAAcnDAAMJwcsAM1iYqGgA0UAAarPJKtVraKM4pjXUprcoIGpp9VOHOja4BQaZQzvFJTFO+wEwArtA4+AwKJhCj4wPtmlP6hrPz6Us+GOubUNu7+9SumdT5APpfH6xFpeWVaq1cwqKAAHygjCYLlcmjIQA)

---

The code above can be _fixed_ by refactoring `OnlyFoo` to only take the type union representing the element type (in this case `Foo | Bar`).

See below:

```ts
type Foo = { type: 'foo' };
type Bar = { type: 'bar' };

export type OnlyFoo<T> = T extends Foo
    ? T
    : never;

export type NotContainsFoo<T, X = OnlyFoo<T>> = [
    X,
    OnlyFoo<T>,
    [X] extends [never] ? true : false,
    [OnlyFoo<T>] extends [never] ? true : false,
];

type Bug = NotContainsFoo<Foo | Bar>;

// Bug = [Foo, Foo, false, false]
```

Playground: [Playground link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200328&ssl=15&ssc=39&pln=1&pc=1#code/C4TwDgpgBAYg9nKBeKBvKpIC4oHIBmCuUAvgNwCwAUJtAEICGATsmhuBDrgEbPHnVqEAB5g4TYO0hQA8gDsANiHhwAPABUAfK3VQRwCHIAmAZ1gJqUK1AD8UdZes45EAG4QmlKkNHjJtKAA5OGAAYTg5YAYASzkTFQ0AGigADVZ5JQStbRQAbUcrFMSC2UVlBA1NYqprKFyUgF09YQNjM1yXdyYmu2AmAFdoHHwGBRMIatrcjPK1LSb9Q1M6zo8ejAGhqBGxieoGr2oAgH1T49ZgsIio2PiKlSgAHyhGJk0yIA)

**Comment by RyanCavanaugh** [comment]
This works as expected now
