### ISSUE TITLE
Expression not callable after `typeof valueOrFunction === 'function'` check

### ISSUE THREAD

**Issue by sambostock** [microsoft/TypeScript#37750]
**TypeScript Version:**  3.9.0-dev.20200328 

**Search Terms:**

- typeof function or value
- check if variable is function
- typeof function or value

**Code**

```ts
function example<T>(valueOrFn: T | (() => T)) {
  const value: T = typeof valueOrFn === 'function' ? valueOrFn() : valueOrFn;
  //                                                 ~~~~~~~~~~~
}

```

**Expected behavior:**

TypeScript should be able to that if the possible types for `valueOrFn` are
- `T`
- `() => T`
and `typeof valueOrFn === 'function'`is true (meaning `valueOrFn` is some sort of`Function`), then the type of `valueOrFn` is `() => T`.

**Actual behavior:**

TypeScript complains about `valueOrFn()`:

```text
This expression is not callable.
  Not all constituents of type '(() => T) | (T & Function)' are callable.
    Type 'T & Function' has no call signatures.(2349)
```

**Playground Link:** 

- [Playground](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200328#code/GYVwdgxgLglg9mABAUwB4EMC2AHANsgHgBUA+ACgDd1cRkB5AJwDEwAuRIxAH0TLIEpEAXhId+ggN4AoRIggIAzlERUaydpyGIoAT2zI4wFdVqMWwoVoDkoSLARXEAfmNqzYAYnarTzMAG4pAF8gA)

**Related Issues:**

**Comment by sambostock** [comment]
Duplicates #37663.

Found by searching for error message.

> expression is not callable

**Comment by isumix** [comment]
Same for me, Typescript 5.1.6
```ts
const mergingReducer = <V extends {}>(
  accumulator: V,
  value?: V | ((v: V) => V),
) => ({
  ...accumulator,
  ...(typeof value === 'function' ? value(accumulator) : value),
});
```
error in `value(accumulator)`
```
This expression is not callable.
  Not all constituents of type '((v: V) => V) | (V & Function)' are callable.
    Type 'V & Function' has no call signatures.ts(2349)
```

**Comment by iDavid2619** [comment]
Same problem still persisting in 2023 😂
