### ISSUE TITLE
Add navigation path for going to JS node_modules definitions instead of .d.ts declarations

### ISSUE THREAD

**Issue by davidmurdoch** [microsoft/TypeScript#37777]
Issue Type: <b>Bug</b>

When I "go to definition" of module in a JavaScript project it jumps to the TypeScript types file, if available, not the *actual* definition. If the TypeScript types are _not_ available it will work as expected.

In the past, VSCode maintainers have commented:

> It's not that TypeScript types are blocking you from jumping to the implementation
https://github.com/microsoft/vscode/issues/68782#issuecomment-464177500

and

> In general, you cannot jump to the js implementation of a npm module
https://github.com/microsoft/vscode/issues/68782#issuecomment-464158572

and

> it's that there in general is not logic to examine the code of an arbitrary node module and figure out which external invocations map to which implementations in the module.

https://github.com/microsoft/vscode/issues/68782#issuecomment-464177500

but that's is so clearly just flat-out wrong. There is a separate command for navigating to TypeScript types in the Right-Click context menu: "Go to Type Definition", it appears directly beneath "Go to Definition".

To reiterate: **if the TypeScript file is removed everything works as expected.**

People don't want to browse TypeScript definition files when stepping through source definitions. Abstractions are leaky. We need to find out why.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.0.0-16-generic

**Comment by sheerun** [comment]
The providers for "Go to Definition", "Go To Type Definition", and "Go To Implementation" currently do the same thing. It's visible on this screencast where I call them in turn: https://asciinema.org/a/619AvvIQjd3zG7IV5MoLafVec

I'd expect that only "Go to Type Definition" goes to d.ts files. Maybe "Go To Definition" and for sure "Go to  Implementation" should go to JS files if they are the only ones with implementation. This is very serious issue because it makes it really hard to debug code of dependencies.

**Comment by davidmurdoch** [comment]
Any way to get this bumped to a higher priority? I go a little bit more insane every day over this :zany_face: 

Also, the issues label is wrong. This has got to be considered a bug?

Also, not sure how this is a TypeScript issue, seems more like a VSCode issue to me.

**Comment by sheerun** [comment]
It is typescript issue and it even has failing test: https://github.com/microsoft/TypeScript/pull/39426

**Comment by powext** [comment]
Definitely waiting for this!

**Comment by IllusionMH** [comment]
Is this issue still relevant?

Go to Source Definition available in VS Code from early June
https://code.visualstudio.com/updates/v1_68#_go-to-source-definition

**Comment by fabriziobertoglio1987** [comment]
Yes. It is still relevant. Go to source definition is not available on coc-tsserver see https://github.com/neoclide/coc-tsserver. More info here https://github.com/neoclide/coc-tsserver/pull/272. Thanks

**Comment by davidmurdoch** [comment]
Now that "Go To Source Definition" can be set as the preferred mode for "Go To Definition" (see https://github.com/microsoft/TypeScript/issues/49003#issuecomment-1499297090) I think this can be closed.

**Comment by fabOnReact** [comment]
using the vim plugin coc-tsserver when I navigate to useRef, the file is still minified and unreadable. 

https://github.com/user-attachments/assets/6b8f0747-9bd1-406d-b5db-d40436ddfdd1
