### ISSUE TITLE
'declare method' quick fix adds inline import

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37781]
From https://github.com/microsoft/vscode/issues/94118

**TypeScript Version:**  3.9.0-dev.20200330

**Search terms**
- quick fix
- declare method
- import

**Repro**
For a project:

`foo.ts`
```ts
export interface Foo {
    abc: number;
}

export function doFoo(callback: (x: Foo) => void) { }
```

`index.ts`
```ts
import { doFoo } from "./foo";

class Bar {
    bar() {
        doFoo(x => this.baz(x))
    }
}
```

1. Trigger the `declare method` quick fix on `baz`

**Expected behavior:**
An import for `Foo` is added to the top of the file:

```ts
import { doFoo, Foo } from "./foo";

class Bar {
    bar() {
        doFoo(x => this.baz(x))
    }
    baz(x: Foo): void {
        throw new Error("Method not implemented.");
    }
}
```

**Actual behavior:**
An inline import is added:

```ts
import { doFoo } from "./foo";

class Bar {
    bar() {
        doFoo(x => this.baz(x))
    }
    baz(x: import("./foo").Foo): void {
        throw new Error("Method not implemented.");
    }
}
```

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
