### ISSUE TITLE
"Object is possibly null" After Non-Null Assertion

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/TypeScript#37798]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

typescript object is possibly null after non null assertion
typescript object is possibly null after exclamation mark check

**Code**

```ts
const obj: { a: number } | null = null;

if (obj!.a) {
    console.log(obj.a);
}
```

**Expected behavior:**

Successful compilation, since we notify the compiler with non-null assertion at line 3 that `obj` is not `null`, then it's not `null` at line 4 too.

**Actual behavior:**

Error "Object is possibly null" at line 4 (`console.log(obj.a)`).

**Playground Link:** https://www.typescriptlang.org/play?ts=3.9.0-dev.20200328#code/MYewdgzgLgBCBGArAXDA3jAhqsBXAtvAKYBOMAvjAD4x4A2dMAvLbgwNwBQnAlgGYwAFAkQBCAHSYAlOk4x5MUJBB0i4uiADmwpJKldycmEA

**Related Issues:**

**Comment by nicojs** [comment]
I guess you meant to use the optional chaining here? https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

```ts
const obj: { a: number } | null = Math.random() > .5? null : { a: 42 };

if (obj?.a) {
    console.log(obj.a);
}  
```

https://www.typescriptlang.org/play?ts=3.9.0-dev.20200328#code/MYewdgzgLgBCBGArAXDA3jAhqsBXAtvAKYBOMAvjAD4x4A2dMAvDALKZQAWAdCZmABMQ+ABQBKGAD4Y3AKwB+WrgYxUGbDAAsAJgoBuAFAGAlgDMYIhInndMEtAZhOYoSCDpFudEAHNLSWzFDckcYIA

**Comment by ChayimFriedman2** [comment]
@nicojs No. I mean non-null assertion.

I know that works with optional chaining operator, but that's not the case. It should produce no errors even with non-null assertion, since we let the compiler know (at line 3) that `obj`, not matter what you (= the compiler) knows about it, is NOT null. And since we don't assign `null` to `obj` between line 3 and 4, if in line 3 it can't be null - it can't be at line 4 too.

**Comment by nicojs** [comment]
I'm pretty sure the non-null assertion operator works as intended here. With non-null assertion you're effectively saying to TypeScript "I know it might be nullish, but I know better, please let me use it this one time". It doesn't interfere with control flow analysis.

Although this is not explicitly found in the handbook: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator. Maybe adding this small example could help with that?

**Comment by ChayimFriedman2** [comment]
@nicojs What's the point? If `obj` is null, it'll crash. If not, why we emit an error in the next statement?

**Comment by RyanCavanaugh** [comment]
See #9640

In general we don't do "if it didn't *crash*" reasoning since it's very difficult to fit into an efficient control flow analysis, which is really what you're asking for since the same reasoning would apply to this example:
```ts
const obj: { a: number } | null = null;

if (obj!.a) {
}
console.log(obj.a);
```
