### ISSUE TITLE
Using object destructuring with ECMAScript's private field as computed property name leads to runtime error

### ISSUE THREAD

**Issue by louistio** [microsoft/TypeScript#37791]
**TypeScript Version:**  3.8.3

**Search Terms:** computed object property name destructuring private ECMAScript

**Code**
```ts
class PropertyAccessor {
    readonly #propertyName: string;

    constructor(propertyName: string) {
        this.#propertyName = propertyName;
    }

    getPropertyValue(obj: Record<string, string | undefined>): string | undefined {
        const { [this.#propertyName]: value } = obj;
        return value;
    }
}

const accessor = new PropertyAccessor('name');
console.log(
    accessor.getPropertyValue({ name: 'Adam' })
);
```

**Expected behavior:**
'Adam' is logged at runtime.

**Actual behavior:**
Runtime error occurs:
```
Private field '#propertyName' must be declared in an enclosing class 
```

**Additional information:**
I just started using TypeScript and I ran into this problem while converting one of my javascript projects, the behavior was confusing to me. It seems like the code is transpiled incorrectly, as it works when not using destructuring syntax:

```ts
const { [this.#propertyName]: value } = obj;
// compiles to
const { [(_propertyName = new WeakMap(), this.#propertyName)]: value } = obj;

const value = obj[this.#propertyName];
// compiles to
const value = obj[__classPrivateFieldGet(this, _propertyName)];
```

The error does not occur when using TypeScript's `private` field instead of ECMAScript's.
The error does not occur when targeting ESNext.

**Related Issues:** Maybe #26572 #26355? Doesn't seem like the same problem but similar keywords.

<details><summary><b>Output</b></summary>

```ts
"use strict";
var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, privateMap, value) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to set private field on non-instance");
    }
    privateMap.set(receiver, value);
    return value;
};
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, privateMap) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to get private field on non-instance");
    }
    return privateMap.get(receiver);
};
var _propertyName;
class PropertyAccessor {
    constructor(propertyName) {
        _propertyName.set(this, void 0);
        __classPrivateFieldSet(this, _propertyName, propertyName);
    }
    getPropertyValue(obj) {
        const { [(_propertyName = new WeakMap(), this.#propertyName)]: value } = obj;
        return value;
    }
}
const accessor = new PropertyAccessor('name');
console.log(accessor.getPropertyValue({ name: 'Adam' }));

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.8.3#code/MYGwhgzhAEAKBOB7ADgU3gFwJ4EFjFSkXmgG8AoaK6eVMAE0QDsQtoBiZJNTLAOTABbVAC5oEDPACWTAOYBucpWrBmE+AFdgGYgAouKdNgHCx6mbICUZZdWoYAFlIgA6TtyP8hqaAF5oBjzG3op2AL5KdrKoGAiGvABqYCAaqLqIAEYAVmIASqiq8PQAPOZyADTikhbQAD7QGkz0qABmMqj0AHyWZtVydQ1Nre30NnZ2qkwSZNAA2o7OboGeJqgAumIAbsmp0GF+0JlZoeNUtBga8EzQ2ymoJ1QREeST02D4hBDEB0yoAO5wDy8PAEIjwXQAciY3ghlkUr0QIFQLhAiFkuls0HeoK+8Bc0ViQOwSTuulI0GhpmgEJw9CEEL2lnIcKAA)

**Comment by a-tarasyuk** [comment]
The following example works for the `ESNext` target, because of TS emits JavaScript code without _`polyfills`_ for private fields

```js
"use strict";
class Foo {
    constructor(value) {
        this.#value = value;
    }
    #value; // <- declarated private value. if remove it JavaScript engines will throw 
            // Private field '#propertyName' must be declared in an enclosing class 

    getValue(data) {
        const { [this.#value]: value } = data;
        return value;
    }
}
```

You can try to use `workaround` - [Playground](https://www.typescriptlang.org/play/?target=7&ssl=8&ssc=9&pln=9&pc=39#code/MYGwhgzhAEBiD29oG8BQ0PQE4FMwBN4A7EAT2gGIA3MEAVxwC5oIAXLASyIHMBudTMGJssdYK3hYAFDXpMW7LtwCUKAZkysAFhwgA6arQbQAvNFkN+GgL6p10bjlYA1Izin4wrMMwBKOISx8AB4RJQAaBU4eAD5lZjCeaAAfaDoifBwAMy4cfDUNDSEiNmgAaxxyM21dAwscK0KMYtLkaABtCtIAXWZ66GtTaE9vRqbcVjosInM3MYHUW1QW1mgsxCGiHAB3OEQpAHIiMABbHAPlfhb4EBw9EHhuKXX4PUcXNyk247PmA4AVACiAGV-gcBspLkA), like so 
```ts
const key = this.#value;
const { [key]: value } = data;
```

However, I think, it is a bug, because, the following code
```ts
const { [this.#value]: value } = data;
```
should be converted something like so
```ts  
const { [__classPrivateFieldGet(this, _value)]: value } = data;
```

**Comment by a-tarasyuk** [comment]
Is it possible to include this issue in `4.2.0` milestone?

**Comment by nicolo-ribaudo** [comment]
I was going to open a new issue, but I _think_ it's the same as this one. However, I'm using computed class methods and not destructuring:
```ts
let getX: (a: A) => number;

class A {
  #x = 2;

  [(getX = (obj: A) => obj.#x, "_")]() {}
}

console.log(getX!(new A));

```

[playground](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201211#code/DYUwLgBA5uAaBcEAUBDRBBAlBAvAPggDsBXAWwCMQAnAbgCg6BjYFAZ1YnQgG86IIAxAA9cEAEz0+EANpIYYWKKQB7cgCsM2fBFVqAdMIA0EAEQB9E5gC6SbNwC+dR02WFWy0HuDKocuAEIkQhAAd05MTHogA)

**Comment by rbuckton** [comment]
@nicolo-ribaudo The fix @a-tarasyuk has proposed doesn't address this, but I think I found the cause of the issue you're seeing. I've brought up [the problem](https://github.com/microsoft/TypeScript/pull/38135#issuecomment-747831266) in the PR so hopefully we can resolve both at the same time.

**Comment by rbuckton** [comment]
@nicolo-ribaudo I've turned your code sample into a repro the bot can track:

```ts repro
// @showEmit
// @target: ES2015
let getX: (a: A) => number;

class A {
  #x = 2;

  [(getX = (obj: A) => obj.#x, "_")]() {}
}

getX!(new A);

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=1&ts=4.2.0-dev.20201211#code/PTAEAEGcAsHsHcCiBbAlgFwLACgQXQIYBOA5gKboBcoiAygEwAMAjAKw4A2Fo56AGtQAUBagEEAlKAC8APlAA7AK7IARmSIBuHDgDGHApEihRoAN45QoAMQAPaaHpbsF0AG1BvPvcGwVAKzFJWVBfPwA6WwAaUAAiAH0Y8QBdQUlTAF8cTOdsTwBCQXkyeGNxJyA)

**Comment by rbuckton** [comment]
Same for the repro mentioned by @a-tarasyuk:

```ts repro
// @showEmit
// @target: ES2015
class Foo {
    #value: any;
    constructor(value: any) {
        this.#value = value;
    }
    getValue(data: any) {
        const { [this.#value]: value } = data;
        return value;
    }
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=1&ts=4.2.0-dev.20201211&ssl=2&ssc=15&pln=2&pc=13#code/PTAEAEGcAsHsHcCiBbAlgFwLACgQXQIYBOA5gKboBcoiAygEwAMAjAKw4DGANgZJKADFYsUAG8coSaADEANwJcArmWoEAdgE8A3BKkdYayOiKKO6WEQAU8pStDqNASjG6pU9NFSQAdHIXLQAF5QG2UdbDcAX1dQcnQANX8ySwATAkJVTWdxCLc9AyMxUABtDy9fULIAXWpK0Eig0DTCcLypIgpFIjUQpNapaOxIoA)

**Comment by orta** [comment]
@typescript-bot run repros
