### ISSUE TITLE
Generic meta types

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#3779]
As far as I know, in Flow there are so called "generic meta types" that can operate on other types:

```ts
type C = $Merge<{a: number}, {b: string}>; // C = { a: number, b: string }
type A = $Args<(a: number, b: string) => void>; // A = [number, string]
```

Such "type algebra" would be useful to construct function signatures and interfaces that are hard/impossible to construct  with other techniques:

```ts
interface TaggedFunction<Callable extends (...args) => any> {
  type Args = $Args<Callable>;
  type RetV = $RetV<Callable>;

  (...args: ...Args): RetV;
  tag: number;
  bind<...T>(...args: ...T): TaggedFunction<(...args: $Concat<Args, ...T>) => RetV>;
}
```

Do you think this would be a useful addition to the type system?

**Comment by Lenne231** [comment]
I like the idea, but maybe this can also be solved with type providers #3136

**Comment by danquirk** [comment]
It seems like $Merge would be better described through intersection types:
```ts
// & not checked in yet but you can use | here to see how it works with unions
type c = typeof a & typeof b; 
```
$Args and $RetV look like they're essentially compile time reflection APIs.

**Comment by d180cf** [comment]
Some of these meta types can have corresponding meta operators: `&` can denote `$Merge`, `+` can denote `$Concat` and so on; while other meta types, like `$Args`, won't have a corresponding operator. Such operators will essentially allow to write expressions that operate on types and construct other types.

@Lenne231, I'm not familiar with type providers, but a brief look at #3136 made me think that it's an imperative/procedural way of constructing types at compile time, while what I'm suggesting is a declarative way. If this is the case, then type providers is indeed a much more powerful feature.

**Comment by d180cf** [comment]
Btw, does TS have plans to support nested types: `interface Foo { type Bar = number; }`? If yes, then it seems natural to have built-in nested types:

```ts
interface DecoratedFunction<F extends (...args) => any> {
  (...args): F.ReturnValueType;
  tag: number;
}
```

**Comment by danquirk** [comment]
@d180cf local/nested types are already in, planned for 1.6: https://github.com/Microsoft/TypeScript/pull/3266

**Comment by Lenne231** [comment]
A "generic meta type" that creates a subset would also be nice,  especially for functions that update data.

```
type A = $Sub<{ a: number; b: string }>; // A = { a?: number; b?: string }

function setState<T>(update : $Sub<T>) { ... }

setState<{ a: number; b: string }>({ a : 20 });
```

**Comment by d180cf** [comment]
It seems, that the appropriate place for such "generic meta types" (that would better be called "type expressions" or "computed types") is the .d.ts files. Currently they can contain only static type definitions, but could also contain "dynamic definitions":

```ts
/// [mytypes.d.ts]
declare module mytypes {
  export type BasicType = (a, b) => number;

  export type Intersection(a: ObjectLiteral, b: ObjectLiteral) {
    const r = new ObjectLiteral;
    for (const name of a.members) {
      if (name in b.members) {
        if (!Type.same(a.members[name], b.members[name]))
          throw CompileError(...);
        r.members[name] = a.members[name];
      }
    }
    return r;
  };
}

/// [sample.ts]
type X = { a: number; b: string };
type Y = { b: string; c: symbol };
type Z = mytypes.Intersection(X, Y);
```

Such computed types could be compiled in some special "compilation context" in which all these `Type` and `ObjectLiteral` are defined. Then we could go even further and allow "type operators":

```ts
/// [mytypes.d.ts]
declare module mytypes {
  export type "&" (a: ObjectLiteral, b: ObjectLiteral) {
    return Intersection(a, b);
  }
}
```

Of course, some of these computed types will be pretty common and will naturally become a part of the standard types library:

```ts
/// [lib.d.ts]
type "&" (a: ObjectLiteral, b: ObjectLiteral) { ... }
```

This should make it possible to express all fancy constructs that can exist in JS.

**Comment by benliddicott** [comment]
It seems that part of the motivating case could be met by extending `typeof` to arbitrary expressions, as per #4233.

    type C = $Merge<{a: number}, {b: string}>; // C = { a: number, b: string }

Would then become

    // $Merge woiuld provide 20 or so overloads with 1 to 20 parameters.
    // Here's the two parameter overload.
    function $Merge<T1>(a1: T1): (T1&T2);
    function $Merge<T1, T2>(a1: T1, a2: T2): (T1&T2);
    function $Merge<T1, T2, T3>(a1: T1, a2: T2, a3: T3): (T1&T2&T3);
    function $Merge(...args){return null;}
    type C = typeof $Merge({a: number}, {b: string});

Args is harder to see.

**Comment by mhegazy** [comment]
this is already covered by #2710
