### ISSUE TITLE
Type guard can't reference this within ThisType

### ISSUE THREAD

**Issue by ashmind** [microsoft/TypeScript#37796]
**TypeScript Version:**  3.8.3

**Search Terms:**
thistype 2526 guard this typeguard

**Code**

```ts
({
    guard(): this is { x: 1 } {
        return !!this.x;
    },
    
    test() {
        if (this.guard())
            defined(this.x);
    }
} as ThisType<{ 
    x?: 1;
    guard(): this is { x: 1 };
}>);

function defined(x: 1) {}
```

**Expected behavior:**
Code compiles without errors.

**Actual behavior:**
The guard works as expected -- `defined(this.x)` compiles properly.
However, there is an error in guard definition:
```
guard(): this is { x: 1 }
         ↑ A 'this' type is available only in a non-static member of a class or interface.(2526)
```

This is surprising as there is no error on using `this` _inside_ the guard.

**Playground Link:**
https://www.typescriptlang.org/play?target=99#code/BQbwsAUABDUOYFcCGAnAJsAlALigFwAsBLAZylKhCgA9cBGKAX0sljahQFM8EUA7KAEJBhUgDpqAblaxGAGhkxF+TiTxYW0djCIAzKMFEkxiVBkyZl2mGk66ifThiMTM0rTEaRmSMgBViEj8ATwAHTgAeKmVqAH56dzZTdCxcI3IyKlooBkZ3RgA+N0hIXQQ+AGM8IgB7AVt7RwxsukxKRiA

**Comment by RyanCavanaugh** [comment]
Inside the object literal, `this` has type `any`, thus no error. TypeScript doesn't know what `this` in `this is { x: 1 }` is referring to - depending on how the object is being used, this could be literally anything.

**Comment by ashmind** [comment]
Not with `ThisType`, right? _Within_ the method, it is correct:
![image](https://user-images.githubusercontent.com/166396/79622154-37bef780-816a-11ea-9c60-4da8b2b8eb70.png)

Just want to note that both `this` and guard work perfectly fine as expected -- it actually does guard.
![image](https://user-images.githubusercontent.com/166396/79622192-64730f00-816a-11ea-85b9-e591303df497.png)
^ no undefined

Just the guard definition itself is flagged.

Obviously in this specific case I can do a simpler approach:
```
interface X {
    x?: 1;
    guard(): this is { x: 1 };
}

({
    guard() {
        return !!this.x;
    },
    
    test() {
        if (this.guard())
            defined(this.x);
    }
} as ThisType<X>);

function defined(x: 1) {}
```

However I doing some Vue work and `ThisType` is inferred there, so I don't want to explicitly cast -- I would like `this` in guard definition to follow the same rules as `this` in guard body. If `this` in body is not `any`, `this` in definition should not be `any` as well?

**Comment by ashmind** [comment]
Another simpler example:
```typescript
({
    guard(this: { x?: 1 }): this is { x: 1 } {
        return !!this.x;
    }
})
```
