### ISSUE TITLE
Better type inference for Frozen const arrays 

### ISSUE THREAD

**Issue by joseDaKing** [microsoft/TypeScript#37795]
Search Terms: Object.freeze, Readonly

I think typescript should have better type inference when object freeze is used on arrays and The type used is readonly array of the given type, instead the type should be readonly tuple that has the types used in the array.

Example:
``` javaScript
// The type of the array is: 
// readonly Array<string | number>

// What the type should be:
// readonly ["Abra", "Isma", 0]
const b = Object.freeze(["Abra", "Isma", 0]);
```

**Comment by RyanCavanaugh** [comment]
You can use `as const` if this is your intent

**Comment by joseDaKing** [comment]
what do you mean exactly?

**Comment by RyanLamansky** [comment]
He means this:
```TS
const b = Object.freeze(["Abra", "Isma", 0] as const);
```

**Comment by joseDaKing** [comment]
Aha did not that existed thanks
