### ISSUE TITLE
type confusion on values of enums

### ISSUE THREAD

**Issue by kutoman** [microsoft/TypeScript#37803]
**TypeScript Version:**  3.8.3

**Search Terms:**
enum types values
type confusion

**Code**
```
import { store } from "@risingstack/react-easy-state";

export enum SizeLevel {
  xs = 0,
  sm = 576,
  md = 768,
  lg = 992,
  xl = 1200
}

const storage = {
  state: store({
    screen: {
      widthLevel: SizeLevel.xs,
      widthLevelIsMin: function(level: SizeLevel): Boolean {
        let s = SizeLevel[this.widthLevel].valueOf();
        let s2 = this.widthLevel.valueOf();

        console.debug("l_val:", level, "type:", typeof level);

        console.debug("cur_val:", s, "type:", typeof s);
        console.debug("check:", s <= level);
        console.debug("check:", s >= level);

        console.debug("cur2_val:", s2, "type:", typeof s2);
        console.debug("check:", s2 <= level);
        console.debug("check:", s2 >= level);

        return s2 >= level;
      }
    }
  })
};
```

**Expected behavior:**

when logging `s` I would expect it to be a value (e.g. 'xs', 'sm' ..) of type **string** 
therefore the `s` checks (<= >= comparisons) should return `false`
when logging `s2` I would expect it to be a (enum) value (e.g. 0, 576 ..) of type **number** 
therefore one of the `s2` checks (<= >= comparisons) should return `true`

most important: the inferred types should be accordingly (e.g. when hovering over `s` and `s2`)

**Actual behavior:**
when logging `s` a literal of type **number** is outputted
one of `s2` comparison checks return `true`
when logging `s2` a literal of type **string** is outputted
all `s2` comparison checks return `false`

inferred types are not matching with the logged ones and the comparison checks of `s` are marked as erroneous  whereas the comparison checks of `s2` are not.

**Playground Link:** 
it kinda didn't run there. I managed to reproduce this on [codesandbox](https://codesandbox.io/s/objective-moore-piwfw). Please check bar.ts from that project.

**Related Issues:** 
I'm not sure.. maybe slightly with #17043

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be anything indicating a TypeScript bug in this report
