### ISSUE TITLE
Inconsistent typing when intersecting an index signature with an incompatible object type

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#37809]
Found this oddity during discussion with someone on Gitter about using an index signature as a "rest signature", which generally isn't allowed (and certainly isn't typesafe!)

**TypeScript Version:**  3.9.0-dev.2020032

**Search Terms:** index signature incompatible

**Code**

```ts
type T = Record<string, string> & { bar: number };
declare let x: T, y: T;
x = { foo: "fooey", bar: 777 };  // error, bar is incompatible with index signature
y.bar;  // no error, bar is number despite being incompatible
```

**Expected behavior:**
One or all of the following:
* Error on access of `y.bar` due to incompatibility of `bar` with index signature
* Error on the declaration of `T`
* `y.bar` to be typed as `string` (or `never`, i.e. `string & number`) because the index signature is meant to apply to all properties

**Actual behavior:**
Error upon assignment to `x`, but *no error* upon access of `y.bar`, *and* `y.bar` is typed as `number`.

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200328&ssl=1&ssc=1&pln=5&pc=1#code/C4TwDgpgBAKlC8UBKEDGB7ATgEwDwGdhMBLAOwHMAaKQkigPigDIoBvKAIwENMAuKUgFcAthwiYoAXwDcAKGxoANj2iKIwKAA9+MaiB1zNCNlABm6dPwBE59BBBXq3PlADs7qdKhQA9D6jimFhOPFDE+GGkGMJgXMDEHGpQAO7EwAAWkQpG+MTkpHGCmBCyIAB0zl6+-qToAZhBmCES4QIiYhIK+GBp0GJk5JHRsfGJJUA

**Related Issues:** 
None that I could find

**Comment by jack-williams** [comment]
I think you can trace this back via #24300 -> #17867.

**Comment by fatcerberus** [comment]
The linked issues are about *allowing* this to work.  I’m already aware this construction is unsound—I was surprised by the loophole presented by intersection types, and wondered if it was a bug.

**Comment by fatcerberus** [comment]
Wait, this is working as intended?  How?
