### ISSUE TITLE
`unknown` is not assignable to the union of all other primitives

### ISSUE THREAD

**Issue by isiahmeadows** [microsoft/TypeScript#37805]
**TypeScript Version:**  3.9.0-dev.20200328

**Search Terms:** unknown union not assignable, exclude unknown

**Expected behavior:** At least one of the two below to not error out

**Actual behavior:** Both error out

**Related Issues:** #35221, although solving that isn't a hard requirement

**Code**
```ts
type FakeUnknown1 = undefined | null | void | boolean | number | bigint | string | symbol | object;
const test1: FakeUnknown1 = 0 as unknown;

type FakeUnknown2 = undefined | null | boolean | number | bigint | string | symbol | object;
const test2: FakeUnknown2 = 0 as unknown;
```

<details><summary><b>Output</b></summary>

```ts
const test1 = 0;
const test2 = 0;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strictNullChecks": true,
    "target": "ES2020",
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/en/play?noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&noLib=true&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=7&jsx=0&ts=3.9.0-dev.20200328#code/C4TwDgpgBAYghgawgVQHYNQewO6oIxQC8UArqgCYQBmAlqhOVAD5SokA27zUAbpjYxYAjTJnYQ4qbmwC2QiACduQmgHM6wbgGdgCuqu0g5Y7piEArCAGNgAbgBQVzKh1RgEHXgBcsRCnRYuATEAAxQcFqkATioDvagkL5IaBgxAExEUZS09IKsHFzCouKS0iRyispqGtq6+obGhVBmljYOTi6a7jppPvDJ0bgZoeGRZKm4tkA)

**Comment by jack-williams** [comment]
What's the use-case for this?

**Comment by isiahmeadows** [comment]
In my case, it's so I can use `Exclude<unknown, X>` without issue. One case where I need it is in a proof of a few type-level invariants (so I don't have to fuzz test it as heavily):

```ts
type AnyNonSpecialObject =
    | Exclude<Maybe<Any>, object>
    | Array<AnyNonSpecialObject> & {"%"?: Exclude<Maybe<Any>, number>}
    | object & {"%"?: Exclude<Maybe<Any>, number>}
export type __TestVnodeAny = Assert<AnyNonSpecialObject, Vnode>
export type __TestAttributeUnionNonPrimitiveTypeIdentifierIsAny =
    Assert<Maybe<Any>, VnodeAttributes["%"] | VnodeNonPrimitive["%"]>
export type __TestFunctionsAreNotValidVnodes =
    Assert<Is<(...args: Maybe<Any>[]) => Maybe<Any>, Vnode>, false>
export type __TestConstructorsAreNotValidVnodes =
    Assert<Is<new (...args: Maybe<Any>[]) => Maybe<Any>, Vnode>, false>
```

For context:

```ts
type Maybe<T> = T | null | undefined
// `FakeUnknown2` is as per the above
type Any = Exclude<FakeUnknown2, null | undefined>
```

It'd be nice to not have to roll my own `Any` type here, and BTW, if I replace the `Maybe<Any>` with `unknown` here (and within `Vnode` as appropriate - I've omitted it for brevity as it's over 200 lines of pure type-level code excluding comments), the proof fails.

**Comment by RyanCavanaugh** [comment]
This is kind of confusing since the world of known types depends on `target` and will probably expand in the future. In a true interpretation of `unknown` we also have to include kinds of values that haven't been invented yet, I think -- technically hosts are already allowed to invent their own.

**Comment by isiahmeadows** [comment]
So in other words, I'm stuck until negation types come into existence?

**Comment by isiahmeadows** [comment]
Welp, I guess I'm stuck with my current solution.
