### ISSUE TITLE
Can not access default export type when there is a default export value

### ISSUE THREAD

**Issue by acutmore** [microsoft/TypeScript#37829]
**TypeScript Version:** 
3.9.0-dev.20200328

**Search Terms:**
multiple default exports

**Code**

```ts
export default interface Result {
    prop1: string;
}

export default function(): Result { // Error: Cannot find name 'Result'.(2304)
    return { prop1: 'a string' }
}
```

**Expected behavior:**
Able to access type `Result` or an error explaining the issue accessing `Result`

**Actual behavior:**
Error: Cannot find name 'Result'.(2304)

**Playground Link:**
https://www.typescriptlang.org/play/#code/FAUwHgDg9gTgLgAgCYgGYEMCuAbRBLAOzhBgwGMQEAlEAZx0QG9gFWEIYoIBGALgVpwYhAOYBuYAF9goSLEQoMDBKkwEycPFAIAKAJT8a9XAmZsEMEHEwwCp9px78A5OgFDRzhNOlA

**Related Issues:**

**Comment by acutmore** [comment]
Ran into this today. I didn't actually want to export the interface as default. Spent 10 minutes struggling to work out why I couldn't refer to the interface, restarting vscode etc.

If this is expected behaviour it would have been useful if the error message said something along the lines of _"can not 'Result' because it is a default export"_

**Comment by acutmore** [comment]
Additional note: I _can_ access the type if the module imports the default export from itself.

```ts
// file.ts
import type DefaultType from './file';

export default interface Result {
    prop1: string;
}

export default function(): DefaultType {
    return { prop1: 'a string' } // No errors
}
```

**Comment by RyanCavanaugh** [comment]
@ahejlsberg what's the intended visibility of `Result` here?

**Comment by ahejlsberg** [comment]
The following works as expected (the two meanings of `hello` are merged and both are exported as the default):

```ts
export default interface hello { a: string }

export default function hello(x: hello) {}

hello({ a: 'abc' });
```

If the function has a different name, or no name, we should report an error (because there can only be one `export default` entity). The fact that we don't is a bug in my opinion.

**Comment by acutmore** [comment]
Thanks @RyanCavanaugh and @ahejlsberg. Really appreciate you looking into this.

I'm more than happy to work on providing fix to emit an error for this. Especially as I might be the only person in the world who got confused by the lack of error.

**Comment by RyanCavanaugh** [comment]
> If the function has a different name, or no name, we should report an error

@ahejlsberg I don't agree with this. The declarations (can) create internal names and those names need not match, and create an external name `default` that resolves to multiple entities depending on meaning. Forcing the local names to match doesn't seem to accomplish anything. Thoughts?
