### ISSUE TITLE
Proposal: Incremental build mode

### ISSUE THREAD

**Issue by kuon** [Microsoft/TypeScript#3782]
I am using tsify and browserify to build my typescript application.

It works, but it is sadly very slow ( https://github.com/smrq/tsify/issues/54 ).

It seems the typescript compiler would need an incremental build mode to make "tsify like uses" faster. The same issue arises when using typescript in something like ruby on rails asset pipeline.

The incremental build mode would work exactly like `tsc -w` but it would use an on disk cache that could be used for fast compilation if the same command is issued again.

**Comment by mhegazy** [comment]
The compiler provide a [services API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services) that can do most of this work. [gulp-typescript](https://github.com/ivogabe/gulp-typescript) uses the same API for incremental compilation. the other alternative is to use the new ts.transpile interface similar to the support in [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader).

**Comment by kuon** [comment]
I'll have a deeper look at the API and see if I can improve the compilation speed. I'll come back here if more support is required on the typescript compiler side.
