### ISSUE TITLE
New Website Logo: HexEd.it

### ISSUE THREAD

**Issue by jens-duttke** [Microsoft/TypeScript#3783]
- Name: HexEd.it
- Homepage url: https://hexed.it
- Brand Guidelines/Licensing: N/A
- Logo: https://hexed.it/img/logo.svg

HexEd.it is an online hex editor running in the web browser, which is built using TypeScript.

**Comment by RyanCavanaugh** [comment]
Neat!

**Comment by jakepetroules** [comment]
Wow, this is an incredible app. Performance is excellent and the UI is really well designed and well thought out. Great job!
