### ISSUE TITLE
ASI incorrectly kicks in for let declarations

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3784]
From looking through the specification, I don't think we are doing the right thing when a `let` declaration spans multiple lines.

The following:

```TypeScript
let
x
```

seems to incorrectly compile to

```JavaScript
let;
x;
```` 

instead of

```JavaScript
var x;
```

I'm not seeing a "[No *LineTerminator* here]" for `let` declarations in the spec. The most relevant restriction on `let` that I see is the following:

> <span id="sec-13.4" class="secnum">[13.4](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-expression-statement "link to this section")</span> Expression Statement
============================================================================================================================================================================

> Syntax
------

> *ExpressionStatement*<sub>\[Yield\]</sub> <span class="geq">:</span>

> &nbsp; &nbsp; &nbsp; <span class="grhsannot">\[lookahead ∉ {`{`, `function`, `class`, `let [`}\]</span> *Expression*<sub>\[In,\\ ?Yield\]</sub> `;`

> <span class="nh">NOTE</span> *[...]* **An *ExpressionStatement* cannot start with the two token sequence `let [` because that would make it ambiguous with a `let` *LexicalDeclaration* whose first *LexicalBinding* was an *ArrayBindingPattern*.**

**Comment by CyrusNajmabadi** [comment]
This is because it would otherwise be a breaking change moving from ES5 to ES6.  In ES5:

```js
let
x
```

Is parsed as

```js
let;
x;
```

So we need to preserve that.  In ES5 though

```let x```

won't legally parse, so it's ok to now parse that as a let-declaration.

**Comment by CyrusNajmabadi** [comment]
Interesting point about ```let [```.  It would seem like they're allowing a breaking change there.  someone could have had "let[0] = 1" in their existing ES5 code, and that would break moving to ES6.

**Comment by DanielRosenwasser** [comment]
Discussed offline with @CyrusNajmabadi; while the above was our reason for implementing things the way they are now, we're leaning towards just aligning with the ES6.
