### ISSUE TITLE
Assert while trying to report error about a bad tsconfig file

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#37850]
https://github.com/microsoft/vscode/blob/0ba0ca52957102ca3527cf479571617f0de6ed50/extensions/typescript-basics/test/colorize-results/tsconfig_off_json.json is not actually a tsconfig.json file (I think it gives colorization settings for one).  If you run `tsc -p` on it, it asserts:

```
Error: Debug Failure.
    at Object.assertDefined (tsc.js:1724:24)
    at tsc.js:13692:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (tsc.js:13692:21)
    at createFileDiagnostic (tsc.js:13712:20)
    at Object.createDiagnosticForNodeInSourceFile (tsc.js:10181:16)
    at reportInvalidOptionValue (tsc.js:22339:36)
    at convertPropertyValueToJson (tsc.js:22327:21)
    at convertToObjectWorker (tsc.js:22219:16)
    at parseOwnConfigOfJsonSourceFile (tsc.js:22851:20)
```

(Line numbers are from 3.8.3)

**Comment by a-tarasyuk** [comment]
The error occurs in the following line 
https://github.com/microsoft/TypeScript/blob/3d3854c93de833a6e2c56e3de2498b83634eec3e/src/compiler/commandLineParser.ts#L1849

```sh
tsc -p tsconfig_off_json.json 
```
The file is valid JSON which contains an array as the root element., CLI parses JSON file and tries to use it as `list` option, however, it is not valid `tsconfig`.

@RyanCavanaugh @amcasey  What is the acceptable solution to this problem?

**Comment by amcasey** [comment]
Generally speaking, a parser shouldn't crash on any input.  At a minimum, it should report that there was a syntax error.  At best, it would report what it did parse and how that differed from what it expected (e.g. "a tsconfig file may not have an array as the root element").

**Comment by KSahithyan** [comment]
I am having the same problem.
My **tsconfig.json** file

```json
{
    "compilerOptions": {
      "target": "es5",
      "module": "commonjs",
      "outDir": "./build",
      "strict": true,
      "strictFunctionTypes": false,
      "forceConsistentCasingInFileNames": true
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules"]
  }
  ```

when I run `tsc` from terminal, it doesn't output anything.
But when running `tsc -b`, it outputs,

```bash
/usr/share/nodejs/typescript/lib/tsc.js:81040
                throw e;
                ^

Error: Debug Failure.
    at Object.assertDefined (/usr/share/nodejs/typescript/lib/tsc.js:1724:24)
    at /usr/share/nodejs/typescript/lib/tsc.js:13692:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/usr/share/nodejs/typescript/lib/tsc.js:13692:21)
    at createFileDiagnostic (/usr/share/nodejs/typescript/lib/tsc.js:13712:20)
    at createDiagnosticForNodeInSourceFile (/usr/share/nodejs/typescript/lib/tsc.js:10181:16)
    at Object.createDiagnosticForNode (/usr/share/nodejs/typescript/lib/tsc.js:10171:16)
    at handleSymbolAccessibilityError (/usr/share/nodejs/typescript/lib/tsc.js:73879:50)
    at checkEntityNameVisibility (/usr/share/nodejs/typescript/lib/tsc.js:74252:13)
    at visitDeclarationSubtree (/usr/share/nodejs/typescript/lib/tsc.js:74389:29)
```

**Comment by amcasey** [comment]
@KSahithyan Thanks for the update!  I'm not seeing that error when I build with the latest compiler (though, obviously, it fails later when there are no files).  Which version of tsc are you using?

**Comment by KSahithyan** [comment]
It's version is 3.8.2

**Comment by amcasey** [comment]
@KSahithyan Looking more carefully at the stack, it doesn't match the one in this bug, which explains why I'm unable to repro with just a tsconfig file.  Can you please file a new issue for yours?  It would be extra helpful if you could include the file in which the error is occurring.  Thanks!

**Comment by KSahithyan** [comment]
@amcasey I am using 3.8.3. And let me try to reproduce the bug and get back to you. (if I can repro, I will create a new issue)

**Comment by KSahithyan** [comment]
Actually while trying to reproduce the error, I found why this error is showing up.

I was using this line to import Client, Collection from the package `discord.js`;
```typescript
const { Client, Collection } = require('discord.js');
```

When I added the above line, the error came again. So I changed it with,
```typescript
import { Client, Collection } from 'discord.js'
``` 
now it is fixed.

**Comment by amcasey** [comment]
@KSahithyan I'm glad you found a way to work around the issue, but it still seems like a bug that you were seeing a crash when running tsc.  Can you please file an issue and include as much detail as possible about the file where you had to change the import?  Thanks!

**Comment by KSahithyan** [comment]
Ok

**Comment by KSahithyan** [comment]
@amcasey I created the issue. https://github.com/microsoft/TypeScript/issues/39373
