### ISSUE TITLE
ResizeObserver API declarations missing

### ISSUE THREAD

**Issue by manucorporat** [microsoft/TypeScript#37861]
## Search Terms

- Reopening this close issue: https://github.com/microsoft/TypeScript/issues/28502

## Suggestion

- lib.dom.ts does not include ResizeObserver API declarations.
- ResizeObserver is already supported by all modern browser, typescript should provide the typs

## Examples

https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by orta** [comment]
Yeah, [now that it's in all the main browsers](https://caniuse.com/#search=ResizeObserver), we'd accept a PR to https://github.com/microsoft/TSJS-lib-generator/ on it 👍

**Comment by manucorporat** [comment]
@orta hey! i just tried to prepare the PR:
```
  bareMessage: 'Attributes cannot accept sequence types',
  context: 'Syntax error at line 23, since `interface ResizeObserverEntry`:\n' +
    ' attribute sequence<ResizeObserverSize> borderBoxSize;\n' +
```
and got this error...

**Comment by orta** [comment]
I'd make a work in progress PR on that repo, and ask for help if the IDL -> DTS translation requires changes

**Comment by m93a** [comment]
GitHub user @strothj implemented the type definitions [in a gist](https://gist.github.com/strothj/708afcf4f01dd04de8f49c92e88093c3). It should be possible to make a PR based on this.

**Comment by yooouuri** [comment]
Any progress on this?

**Comment by PratikMMohite** [comment]
Any updates here ?

**Comment by sapkra** [comment]
@m93a What about this PR? https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/847

**Comment by MatthiasKunnen** [comment]
>  There is no open PR currently, but if you want this implemented in TS, you can start one
> -m93a

As @sapkra said, https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/847 will fix this issue. Unfortunately the PR is inactive.

@m93a, In case you didn't know, just beneath the title of the issue and in the section on the right you can see if there are any pull requests that address the issue.

![image](https://user-images.githubusercontent.com/16807587/95927901-553ee800-0dc0-11eb-8c91-2b7995da79e7.png)

**Comment by timocov** [comment]
> Unfortunately the PR is inactive.

Since that PR is inactive, I've done required changes in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/948 (that's PR on top of changes from https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/847).
