### ISSUE TITLE
Declaration file is missing undefined in promise's generic type union

### ISSUE THREAD

**Issue by jbsulli** [microsoft/TypeScript#37862]
**TypeScript Version:**  3.8.3

**Search Terms:** declaration missing undefined promise generic type union

**Code**

```ts
const test = async (): Promise<string | undefined> => {
  return Math.random() > 0.5 ? "boo!" : undefined;
}

export default test;
```

**Expected behavior:**

I expected `tsc ./test.ts --lib esnext --emitDeclarationOnly --declaration true` to produce:

```ts
declare const test: () => Promise<string | undefined>;
export default test;
```

**Actual behavior:**
```ts
declare const test: () => Promise<string>;
export default test;
```

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=2&ssc=22&pln=1&pc=1#)

**Related Issues:**

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/37351.  To get the behavior you want without a tsconfig.json, use `--strict`.

**Comment by jbsulli** [comment]
Totally makes sense now! Thank you so much @nmain!
