### ISSUE TITLE
Incorrect type inference with nullish coalescing operator

### ISSUE THREAD

**Issue by starsolaris** [microsoft/TypeScript#37872]
**TypeScript Version:**  3.8.3, Nightly

**Search Terms:** nullish coalescing operator, type inference

**Code**

```ts
(a: { a: {} | undefined}) => {
    const b = a?.a ?? "";    
}
```

**Expected behavior:**
type of b should inferred as: {} | ""
**Actual behavior:**
type of b is inferred as: {}

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ssl=4&ssc=1&pln=1&pc=1#code/BQQwXABA3h7QvhAPhArgOwCYFMBmBLdbTeASggF4A+aAWACgImIBjAe3QGcAXCAI0qwA-ADoQEIUIgAiaQG5mEBvAZA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/36393

**Comment by DanielRosenwasser** [comment]
This is because `{}` is a supertype of `string`. The `object` type has the same structure implied by `{}`, but explicitly rejects direct compatibility with primitives like `string`.
