### ISSUE TITLE
Never errors on property accesses

### ISSUE THREAD

**Issue by clar-cmp** [microsoft/TypeScript#37875]
**TypeScript Version:**  Nightly

**Search Terms:** "Property does not exist on type" never coercion

**Expected behavior:** Because `breaks` is just a subcase of `works`, this should typecheck.

**Actual behavior:** TypeScript complains that type `never` does not have the property "length." This is incorrect; because `never` is a subtype of all types, it has all possible properties.

**Related Issues:** The list was full of so many things, it was hard to sift through. Nothing that I saw was related, but this could be a duplicate.

**Code**
```ts
function works<T extends any[]>(value: T): boolean {
  return value.length > 0;
}

function breaks(value: never): boolean {
  return value.length > 0;
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function works(value) {
    return value.length > 0;
}
function breaks(value) {
    return value.length > 0;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200408&ssl=1&ssc=1&pln=7&pc=2#code/GYVwdgxgLglg9mABAdzgJwNYGcA8AVRAUwA8pCwATLRAQzAE8BtAXQD4AKANxoBsRCAXIjwBKIQCM4cHoTqIA3gFgAUIkRpCUEGiTc+hAHQywAcygALRK0QAGANwqAvipWhIsBInEaa2Lr34hMEJOQjQxLykZOSVVdU1tXQDDYzNLa3snIA)
      
# Slightly more realistic case

I found this with something along the lines of:

```ts
interface Example {
    thing: any[];
    otherThing: any[];
}

function operateOnObject(obj: Example): void {
    for (const key in obj) {
        const k = key as keyof Example;
        if (obj[k].length === 0) {
             // ...
        }
    }
}
```

If I add additional properties to `Example` of type `any[]`, this continues to work properly. Additionally, removing one property will continue to type check. However, commenting out all the properties for debugging causes a type error, because of this restriction on never.

I understand the desire to lint out problems with accessing stuff on `never` (which is the purpose of dead code lints!) but forbidding property accesses on `never` seems like a bad idea; it makes  much more sense to simply mark the `.length === 0` as dead code rather than failing to type-check.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. It's much, much more ergonomic (both from an implementor's perspective and a developer experience perspective) an to make it *legal* to enter a block where some value in the universe has type `never` and then subsequently error on property access than to try to figure out, at any bare statement, if some value has type `never` or not.

**Comment by clar-cmp** [comment]
Right, I get your logic there, but what I'm proposing is changing this from a typecheck error to an unreachable code error. What I'm interpreting from you're saying is that this is easier to implement on the compiler side, which doesn't make sense to me, because AFAIK dead code detection already requires knowing whether a value is `never`  or not.

**Comment by clar-cmp** [comment]
It was marked but I asked a question and it didn't get it answered, so, I don't really think this should be closed.

**Comment by RyanCavanaugh** [comment]
The checker only resolves property types for properties that are accessed. So it's entirely possible that some series of type guards, for example, produces an expression for which `a.b.c.d.e.f.g.h.i.j.k.l.m` is `never`, but you'd have to resolve the types of `26^12` different properties before finding it.

**Comment by clar-cmp** [comment]
If your type checker is taking exponential time to complete that's definitely not programmed correctly. But either way, it seems like this isn't going to be done, so, noted.

**Comment by wchargin** [comment]
Might this be reconsidered? There is one common and powerful use case
that this prohibits: namely, sound matching on disjoint unions.

In both TypeScript and Flow, we may write:

```javascript
type T = {type: "A", a: number} | {type: "B", b: string};

function f(t: T) {
  switch (t.type) {
    case "A": return t.a;
    case "B": return t.b;
  }
}
```

And this is good, but when `f` may be called with unsound types—either
through use of `any`, or in an untyped file, or because it’s exported as
a public API and may be used by non-TypeScript consumers—it can fail
unexpectedly. So, in Flow, we may harden it thus:

```javascript
type T = {type: "A", a: number} | {type: "B", b: string};

function f(t: T) {
  switch (t.type) {
    case "A": return t.a;
    case "B": return t.b;
    default: throw new Error(`unexpected type: ${(t.type: empty)}`);
  }
}
```

This is a powerful tool, because the `t.type: empty` type assertion
guarantees statically that we haven’t forgotten any cases, and the code
still fails at runtime if it’s given a bad input.

But the TypeScript equivalent does not compile:

```typescript
type T = {type: "A", a: number} | {type: "B", b: string};

function f(t: T) {
  switch (t.type) {
    case "A": return t.a;
    case "B": return t.b;
    default: {
      const _: never = t; // type-checks: good!
      throw new Error(`unexpected type: ${t.type}`); // fails: bad!
      // ^ Property 'type' does not exist on type 'never'.
    }
  }
}
```

Type-theoretically, this doesn’t make much sense, either. The point of
`never` is that it’s the bottom type, a subtype of anything, and so any
operation on it should be type-valid. This is the position that Flow
takes, and it is both theoretically and practically useful.

Can we reopen this issue, or should I make a new one?

**Comment by clar-cmp** [comment]
Maybe I'm just bitter but based upon the closure of this issue and others I doubt that soundness is a design goal of TypeScript. Or at least, that case in particular.

**Comment by RyanCavanaugh** [comment]
I really fail to see how erroring *more conservatively than is needed to be sound* counts against us on the soundness column. Nothing about soundness says you have to allow property access on `never`-typed values.

**Comment by clar-cmp** [comment]
I was clearing out my notifications and even though this has been long closed, I think that hating on flow for a problem which TS itself has is honestly short-sighted. Both Flow and TS are designed to allow undefined behaviour in dead code, and TS forbids just this one case.

Just because that example fails in flow doesn't mean there are dozens other which fail in TS. You can even slightly modify that code to work fine in TS but crash all the same:

```
type T = {type: { value: "A"}} | {type: { value: "B"}};

function f(t: T) {
  switch (t.type.value) {
    case "A": return t;
    case "B": return t;
  }
}
```

I understand the argument that you're making and respectfully disagree, but you just can't say that TS is designed to prevent all undefined behaviour, because that certainly isn't true.
