### ISSUE TITLE
Hover over property accessed using ?. shows T | undefined

### ISSUE THREAD

**Issue by larsnystrom** [microsoft/TypeScript#37879]
Issue Type: <b>Bug</b>

When I hover an object property, there is a tooltip with the type:

<img width="700" alt="bild" src="https://user-images.githubusercontent.com/1000370/78334304-d1dc4880-758b-11ea-996e-a7019f98ef96.png">

The problem is that the type is not for the *property* but for the *expression*. This can get confusing when using optional chaining. In the screenshot above, the type of the `filteredFile.reports` property is actually just `FilteredReport[]`, which is why there is no red squiggly line warning about it being potentially undefined when accessing the `.length` property. But the expression `filteredFile?.reports` has the type `FilteredReport[] | undefined` because of the optional chaining, which I guess is why that's the type being presented in the tooltip?

So the tooltip says `(property) FilteredFile.reports: FilteredReport[] | undefined`, even though the type is not for the property but for the expression. I think a better tooltip would be:

```
(expression) filteredFile?.reports: FilteredReport[] | undefined
(property) FilteredFile.reports: FilteredReport[]
```

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.15.0-91-generic
TypeScript version: 3.8.3

**Comment by mjbvz** [comment]
Playground link: https://www.typescriptlang.org/play/#code/PTAEAkHsDcFMCdQwaANrAdgcwC4AsAoAgY0gwGcdQBDALlAG8kAHHASzOtQH57qMAngG0AuqAC+oALyNxBagDpIrDhi4L02fKBCgAynkgB3cqAwBXALYAjBPKUrOPDZlx5QOsOUMmzV24gAPqDmGAAmsABmbBiwYUA

**Comment by RyanCavanaugh** [comment]
We show the symbol and the type as it exists in the current expression - this can be influenced by narrowing, for example:
```ts
![image](https://user-images.githubusercontent.com/6685088/79157093-d0c7ca00-7d88-11ea-96a5-72b68e444e67.png)
```
so in this case `a?.p.length` can produce `undefined` as part of the expression context its in, so `undefined` is intentionally included

**Comment by larsnystrom** [comment]
Sorry, if I knew the message came from TypeScript and not VSCode I would have provided a TypeScript playground link myself. The code submitted by mjbvz does not describe the problem here.

@RyanCavanaugh Please look at this playground link instead. The problem here is that when you hover `arr` in `a?.arr.length` , the message says `(property) A.arr: string[] | undefined` but the type is not for `(property) A.arr` but for `(expression) a?.arr`. The distinction is important in this case because if the property has the type `string[] | undefined` then TypeScript should not allow me to write `a?.arr.length` but I should instead have to write `a?.arr?.length`.

https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=1#code/PTAEAkHsDcFMCdQAMCG95NASwHbJQPwB0a8RANrDgOYAuAFpijgCba2gDuW55oAzigCeAKBCgJACgAO8SNIS0hASlABBEugBcA2vFzUA2gF1QAH1ABXVrABmuWCzFgAQpY4bSoAMbMckDgAjWCsbexxHIhERXFoEWxRvELVQAG8RCQlSHX49AxMAbhEAX2jba29aLEg8ONzJQh01ZRy8mjSMzPhYWkt4PEJNMkoaBlACUAAiNUnQHUmXSaLSoA

**Comment by RyanCavanaugh** [comment]
I suppose that's technically correct
