### ISSUE TITLE
Syntactic sugar for mapping over a union type

### ISSUE THREAD

**Issue by nth-commit** [microsoft/TypeScript#37880]
## Search Terms

distributed conditional types, discriminated unions, mapped types

## Suggestion

It's quite arduous to map over a union type, when you need inference to each case of the union. ~~It requires you to do symmetrical `extends` with an `infer`.~~ A special syntax for this would be great, e.g.

```typescript
type Species = 'dog' | 'cat' | 'pig';

type Animal = U in Species | { species: U; givenName: string, age: number }

/* Resolves as:
 *
 * type Animal =
 *  | { species: 'dog', givenName: string, age: number }
 *  | { species: 'cat', givenName: string, age: number }
 *  | { species: 'pig', givenName: string, age: number }
 */
```

I haven't put much thought into the syntax at all, but you get the idea. The reasoning behind the above suggestion was to mirror the mapped-type syntax somewhat i.e.

```typescript
type Animal = {
  [P in Species]: ...
}
```

Whilst mirroring the union type syntax (`|`).

## Use Cases

There is a way of yielding the type in the example above using the current lang, but it's hard to discover, the syntax is heavy and it's scary for newbies. The "Advanced Types" docs are great, but you need to read an ingest them all the way to distributed conditional types in order to do something that's feels quite intuitive if you have a little bit of experience with mapped types.

Here's how you would achieve the above, as of TS 3.8 (and a new syntax could just be sugar over this pattern):

```typescript
type Species = 'dog' | 'cat' | 'pig';

type Animal = Species extends infer U ?
    (U extends Species
       ? { species: U; givenName: string, age: number }
       : never)
: never;
```

As @yortus pointed out, a more direct approach of achieving the same result is:

```typescript
type Animal = { [U in Species]: { species: U; givenName: string, age: number } }[Species];
```

## Examples

If you understand what the value of mapped-types are then mapping union types isn't that outrageous an idea.

Here's something from recent memory:

```typescript
type PropertiesAsUnion<T> = U in keyof T | { key: U; value: T[U] }

type Model = {
  foo: string;
  bar: number;
}

type ModelProperty = PropertiesAsUnion<Model>;

/* Resolves as:
 *
 * type ModelProperty =
 *  | { key: 'foo', value: string }
 *  | { key: 'bar', value: number }
 */

const updateModelProperty = (model: Model, property: ModelProperty): Model => { ... };
updateModelProperty(model, { key: 'foo', value: 'must be a string as per discriminated union' });
```

As with distributed conditional types, candidates for the same type are combined:

```typescript
type Vehicle = 'car' | 'truck' | 'bus'

type UnnecessaryUseOfMappedUnion = U in Vehicle | { foo: string } // Warning: 'U' is declared but its value is never read.

/* Resolves as:
 *
 * type Vehicle = { foo: string }; 
 */
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by yortus** [comment]
There is a simpler formulation for mapping over a union type that doesn't require `extends` or `infer`. E.g. your `Animal` example could be written:

```ts
type Species = 'dog' | 'cat' | 'pig';
type Animal = { [U in Species]: { species: U; givenName: string, age: number } }[Species];
```

That's only a little longer than your special syntax, but perhaps still a bit obscure.

**Comment by nth-commit** [comment]
@yortus, oh nice one! That's much more simple at least, will add that to my toolbox 😁 I can see how that also spreads to a union.

My vague feeling that it should mirror the existing mapped-typed syntax seems more justified now. There's less reason for a syntactic sugar over it now in my eyes, but still, ya a little bit obscure (too obscure for me to realise that solution, anyhow).

**Comment by RyanCavanaugh** [comment]
You could also write
```ts
type UnitOf<T> = T extends infer U ? { species: U; givenName: string, age: number } : never;
type Animal = UnitOf<Species>;
```
Declining since there are multiple ways to do this

**Comment by nth-commit** [comment]
Hey @RyanCavanaugh,

Thanks for the reply.

I guess that Animal example is quite trivial - I just wanted to demonstrate the syntax. I could have fleshed out the model property example a bit more in my original post, which I still believe is nasty enough to warrant some extended syntax, or at least some docs about mapping to a union or mapping over a union.

Suspend disbelief for a second, this example is pretty fabricated, but it actually pretty analogous to something I'm working on at the moment - reduced heavily for simplicity.

```typescript
type Model = {
    foo: string;
    bar: number;
};

// Suppose I want to allow updating individual properties of a model, so that I can control how those things are updated.
type ModelProperty = PropertiesAsUnion<Model>;
/* Outputs:
 *  | { key: 'foo'; value: string }
 *  | { key: 'bar'; value: number }
 */

// Suppose there is some additional data, which drive the "how" of the updates.
type UpdateModelPropertyAction = UpdatePropertyAction<Model>
/* Outputs:
 *  | { key: 'foo'; newValue: string; isDraft: boolean }
 *  | { key: 'bar'; newValue: number; isDraft: boolean }
 */
```

These would be the supporting types as of 3.8:

```typescript
type PropertiesAsUnion<T> = { [U in keyof T]: { key: U; value: T[U] } }[keyof T]

// I don't believe this can be collapsed to indexing out of a mapped type in this case
type UpdatePropertyAction<T> = PropertiesAsUnion<T> extends infer U
    ? (U extends PropertiesAsUnion<T> 
        ? {
             key: U['key'];
             newValue: U['value'];
             isDraft: boolean
           }
        : never)
    : never
```

If there was a syntax for mapping over a union:

```typescript
type PropertiesAsUnion<T> = U in keyof T | { key: U; value: T[U] }

type UpdatePropertyAction<T> = U in PropertiesAsUnion<T> | {
  key: U['key'];
  newValue: U['value'];
  isDraft: boolean
}
```

In my real-life scenario, the `PropertiesAsUnion<T>` is definitely a handy abstraction to have, as it's used to drive a bunch of different types in the system. Mapping over each case in that union (and not collapsing the cases) is a thing that I do in a heap of places.

I hope this sheds a little more light on the use-cases.

Cheers.

**Comment by nth-commit** [comment]
This still gets in the way for me, but mostly, I still believe the existing syntax is very unfriendly for newbies.
