### ISSUE TITLE
Call private/protected methods for sister classes

### ISSUE THREAD

**Issue by ianmakecode** [microsoft/TypeScript#37889]
## Suggestion
Allow the a class to access the `private` and `protected` members of other instances of the same type, as many object oriented programming languages do? The only design goal I can think that this would fly agains is "Don't emulate the features of other programming languages" however if we're making that the basis argument for not implementing a feature like this, but then it almost seems like basic features of OOP are being picked/chosen arbitrarily... Oh, and Javascript supports this, obviously lol.

```typescript
class Parent {
  protected discussChildren(newParent: NewParent) {
    // this is allowable in Java, C++, and other object oriented languages
    // crashes without a ts-ignore or ts-expect-error in typescript though?
    newParent.insultChild();
    this.insultChild();
  }

  protected insultChild() {
    console.log('My child is an idiot. Uh oh, I said that out loud.');
  }

  public discussWith(newParent: NewParent) {
    this.discussChildren(newParent);
  }
}

class NewParent extends Parent {
  protected insultChild() {
    console.log('Babies are great and all, but they don't stop defecating. I didn't even feed him that much!');
  }
}

const parentA = new Parent();
const parentB = new NewParent();

parentA.discussWith(parentB);
```

**Comment by DanielRosenwasser** [comment]
I think this is a duplicate of #10637.

**Comment by ianmakecode** [comment]
Ah, shoot. I see why this could be a problem now. nevermind.
