### ISSUE TITLE
Typeguard failing for undefined variable

### ISSUE THREAD

**Issue by fqlx** [microsoft/TypeScript#37882]
**TypeScript Version:**  3.8.3

**Search Terms:**
error TS2532: Object is possibly 'undefined'.
Typeguard bug undefined filter
Typescript typeguard not working

**Code**

```ts
const arr = [{ time: 1 }];
const startDate = undefined;

if (startDate) {
    const filtered = arr.filter(item => item.time >= startDate);
}
```

**Expected behavior:**
No error.  
Typescript compiler works and passes the above code because we have a Typeguard around accessing `startDate`

**Actual behavior:**
The Typescript compiler reports the following error.

```yarn tsc```
```
TS2532: Object is possibly 'undefined'.
const filtered = arr.filter(item => item.time >= startDate);
                                                 ~~~~~~~~~
```

**Workaround**
Use the non-null assertion operator `!`.
```
const filtered = arr.filter(item => item.time >= startDate!);
```

Disable the line if using eslint.
```
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
```
**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=6&pc=2#code/MYewdgzgLgBAhgJwTAvDA2gbxlAlgWwFMAuGARhgF8BdAbgChRJZpEoAROKQ1GAVzAATQgDNcYQoIb1cImAApWCDl0IBKGJnowdMJtBhiANtwSTeiBADpjp+bm75UAPhgPC+K3iIxnaJSrcagyUQA)

**Comment by RyanCavanaugh** [comment]
The absolutely correct thing to do here would be to narrow `startDate` to `never` and then error on that instead, but the error is effectively correct in its intent and for a problem like this, any error is good enough.

**Comment by fqlx** [comment]
If `startDate` was a union type like`Date | undefined`, type `never` would be applicable here. The typeguard would still error.

**Comment by RyanCavanaugh** [comment]
This code works fine:
```ts
const arr = [{ time: 1 }];
const startDate = Math.random() > 0.5 ? 100 : undefined;

if (startDate) {
    const filtered = arr.filter(item => item.time >= startDate);
}
```

**Comment by fqlx** [comment]
Consider the following code:
```
const arr = [{ time: 100 }];
const obj = { startDate: Math.random() > 0.5 ? 100 : undefined };

if (obj.startDate) {
    const filtered = arr.filter(item => item.time >= obj.startDate);
    console.log(filtered);
}
```

```
(property) startDate: number | undefined
Object is possibly 'undefined'.(2532)
```

[Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=7&pc=2#code/MYewdgzgLgBAhgJwTAvDA2gbxlAlgWwFMAuGARgAYKYBfAXQG4AoUSWEAIwCtUZtpEUACJwoJGAFlRACwB0COGAAmIfAAoAlDAB8MCrICsMAPzkqMUgFdlhAGa4whJbWZNctmGs5dZAhMNFCLUwmGDCYVmgYewAbMQQnXkQEWVj4tVwxfFRdTMJ8WTwiHTRvXyhBETENZnCI8AgQGMJZGJAAczU0wgSlGqYaIA)

**Comment by fqlx** [comment]
@RyanCavanaugh Thoughts?
