### ISSUE TITLE
miss-match in handling implicit vs explicit types in function argument of a class type with a member function that never returns

### ISSUE THREAD

**Issue by defunctzombie** [microsoft/TypeScript#37885]
**TypeScript Version:**  3.8.3

**Search Terms:**
never type narrowing

**Code**
```typescript
class SomeClass {
    throw(): never {
        throw 'never';
    }
}

function foo(fn: (arg: SomeClass) => void) {
    fn(new SomeClass());
}

// Fails with "Type 'undefined' is not assignable to type 'number'."
foo((ctx) => {
    let a: number | undefined = undefined;
    if (!a) {
        ctx.throw();
    }

    const b: number = a;
    b;
});

// Compiles
foo((ctx: SomeClass) => {
    let a: number | undefined = undefined;
    if (!a) {
        ctx.throw();
    }

    const b: number = a;
    b;
});
```

**Expected behavior:**
The code understands that `ctx.throw()` has `never` return type and properly detects unreachable code and performs type narrowing.

**Actual behavior:**
Unless the ctx argument is explicitly type annotated with `SomeClass`, the build fails to take into account that `ctx.throw()` never returns. In the above example I have shown this with a failure to type narrow but the same is true if you put any code under `ctx.throw()`. The compiler does not realize it is unreachable code.

The following compiles with no errors about unreachable code even tho `ctx.throw()` has a `never` return type.

```typescript
foo((ctx) => {
    ctx.throw();
    const a = 4;
    a;
});
```

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=21&ssc=1&pln=31&pc=4#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNf0ALgBYBO8A7gBQCUAXNAHbIBuyp2eB3J5F0AcmZtSAgNxd8AXxwycAMwCujYIQCW8RtHnx4VeYwZUwpAOYMEKdJAg1oAXgB80FvDUATO7m4GqzfpZoGBC0NBJyAPQR0ABiYGogMBRqJNAARAAqAJ4ADsiCyu7I8mrM7gLQajCM8ITQNmqmjGAARiD5hPBEuflCiogt7AIAdGkKulRUqgAedk6c3O11YAyM-YMcAD7QhcWlyO4OO4xFJWUS3Gry0FQAhGBektzQM8O8lLQXBHLcwJoQdRaq3W7COYC++Ba4TCOBwUWgqCQOQSyAg4z0U0I0wsSCCNjmzm8BCW9WBA1B212ZwORyp+3cEMq1zuDwWz3wr3e1Bh3B+BD+jAB0CBTBBHHs9UZUNkMKAA

**Related Issues:** 
* https://github.com/microsoft/TypeScript/issues/36753

**Comment by RyanCavanaugh** [comment]
The control flow graph is built during a phase which comes before inferring types, and `ctx`'s type is inferred from context. For that reason, the `const b: number = a` assignment is seen to be unconditionally reached from a control flow graph perspective. The inference algorithm then consults the control flow graph and doesn't know to perform any narrowing based on the `throw` call.

Fixing this is *extremely* nontrivial; you can construct code that shows that you'd need an unbounded number of iterations going back and forth between tweaking the graph and inferring the types, *or* you'd have to slow down checking by probably at least an order of magnitude by an exhaustive search for control flow divergence while hoping to reach a fixed point.

**Comment by RyanCavanaugh** [comment]
P.S. you can also write `return ctx.throw()` for an equivalent program that CFAs correctly

**Comment by defunctzombie** [comment]
Will `return ctx.throw()` cause issues with return type miss-match if the function containing this statement is otherwise set to return a value?

Does the compiler design allow for doing a basic level of inference before control flow graph for the situation above where the types are obvious from the function call?. This is maybe wishful thinking on my part around how "obvious" the types are in practice.

Thank you for the comments around design. I will close this issue given this is a known design limitation. Maybe in the future as inference changes this will change and produce different diagnostics.
