### ISSUE TITLE
Assignment expression fails to narrow

### ISSUE THREAD

**Issue by alfredr** [microsoft/TypeScript#37883]
**TypeScript Version:**  3.8.3

**Search Terms:** method type guard, return value, assignment expression

**Code**

```ts
type AorB = A | B;

class A {
    isA(): this is A { return true; }
    doA() { }
}
  
class B {
    isA(): this is A { return false; }
}

function f(): AorB { return new B(); }

// compiles
let aorb: AorB = f();
if (aorb.isA()) {
    aorb.doA();
}

/* does not compile:
  Property 'doA' does not exist on type 'AorB'.
    Property 'doA' does not exist on type 'B'.(2339)
*/

if ((aorb = f()).isA()) {
    aorb.doA();
}
```

**Expected behavior:**

```ts
let aorb: AorB = f();
if ((aorb).isA()) {
    aorb.doA();
}
```

to be equivalent to 

```ts
let aorb: AorB;
if ((aorb = f()).isA()) {
    aorb.doA();
}
```

**Actual behavior:**

the later fails to compile with 

> Property 'doA' does not exist on type 'AorB'.
>   Property 'doA' does not exist on type 'B'.(2339)

**Playground Link:** 

https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=100&pc=1#code/C4TwDgpgBAgg9gJwEJQLyygHykg3AKHwGMAbAQwGcKMBvfKBqASwpgAoBKALimAAsWzajCg0oCCMACuCAHa8EUiLigBfeowAmcdh1Fr86hsXJUcojQxa6e-QYJFiJ0uVABmZEhWUH1+N1KyRMBMcPJunDzwyPrOMvKyEADuOJwqfgD0GVBEcAC2YEwkEBT4xcBQZIgARlGIKOgRHARMblBsVQjVAHTWnHp0jJU13dq6BJkAVFDaJVCycBW5BUUQXBoACghwkAigUADkYwczcHMLFRAAHiwVYbzg0AfRSAfdllBbOxB7IIfHp3Oiyg11uUHuoEgh1e3TYACYAMwIgCcHHwkwyhFa7Q6NTQ7n6vVY-QsQ06PTGaUMQA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Sorry, misread this and changed the title before realizing what was going on.

**Comment by sandersn** [comment]
Fails since at least 3.3 per the playground.

**Comment by vostrnad** [comment]
@alfredr I tested this with 4.0.2 and it works fine now.

**Comment by sandersn** [comment]
Thanks for checking @vostrnad !
