### ISSUE TITLE
TypeScript should infer `newLocal` name from property name when performing "Extract to constant in enclosing scope" on a PropertyAccessExpression

### ISSUE THREAD

**Issue by dtinth** [microsoft/TypeScript#37898]
## Search Terms

newLocal, Extract to constant in enclosing scope

## Suggestion

When performing “Extract to constant in enclosing scope”, if the expression being extracted is a `PropertyAccessExpression`, I think it would be great if TypeScript used the expression’s `name` instead of `"newLocal"`, if the name would not clash with other symbols in the scope or keywords.

My suggestion summarized as a patch:

```diff
diff --git a/src/services/refactors/extractSymbol.ts b/src/services/refactors/extractSymbol.ts
index 30dcaeaebf..c3b57c61b0 100644
--- a/src/services/refactors/extractSymbol.ts
+++ b/src/services/refactors/extractSymbol.ts
@@ -1009,7 +1009,9 @@ namespace ts.refactor.extractSymbol {
 
         // Make a unique name for the extracted variable
         const file = scope.getSourceFile();
-        const localNameText = getUniqueName(isClassLike(scope) ? "newProperty" : "newLocal", file);
+        const localNameText = isPropertyAccessExpression(node) && !isClassLike(scope) && !checker.resolveName(node.name.text, node, SymbolFlags.Value, false) && !isPrivateIdentifier(node.name) && !isKeyword(node.name.originalKeywordKind!)
+            ? node.name.text
+            : getUniqueName(isClassLike(scope) ? "newProperty" : "newLocal", file);
         const isJS = isInJSFile(scope);
 
         let variableType = isJS || !checker.isContextSensitive(node)
```

If this sounds good, I’m happy to come up with a proper PR and submit it. Would love to try contributing :).

## Use Cases

This would save me a lot of time when I extract stuff to constant (I do this a lot). Without this feature I would have to:

- Copy the name before performing the refactoring, so that I could paste it into the rename box.

  ![Kapture 2020-04-11 at 2 54 21](https://user-images.githubusercontent.com/193136/79019128-ce564c00-7b9f-11ea-810e-860aac949036.gif)

- Sometimes I forgot to copy before extracting. I had to type the name manually.

- That name may be long and the rename box doesn’t provide auto-completions… I had to dismiss the rename box, copy the name, and come back to the rename box.

  ![Kapture 2020-04-11 at 2 57 23](https://user-images.githubusercontent.com/193136/79021620-390a8600-7ba6-11ea-8157-27611b7e7436.gif)

## Examples

![Kapture 2020-04-11 at 3 38 16](https://user-images.githubusercontent.com/193136/79021543-ffd21600-7ba5-11ea-80be-a220bd78c809.gif)

<details><summary>Text version</summary>

```ts
function get(options: { url: string }) {
  return fetch(options.url).then(r => r.json())
  //           ^^^^^^^^^^^
  //           Extract to constant in enclosing scope 
}
```

**Current behavior:** The variable name is always `newLocal`.

```ts
function get(options: { url: string }) {
  const newLocal = options.url;
  return fetch(newLocal).then(r => r.json())
}
```

**Suggested behavior:** The variable name is `url`.

```ts
function get(options: { url: string }) {
  const url = options.url;
  return fetch(url).then(r => r.json())
}
```

</details>

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dtinth** [comment]
I created a branch with the changes in place, as well as test for each added conditional logic. If this looks satisfactory I can open a PR.

https://github.com/microsoft/TypeScript/compare/master...dtinth:extract-constant-property-name

**Comment by dtinth** [comment]
I’ve opened the PR, since the conditions for a PR has been met. (Issue went in the `Backlog` milestone; “help wanted” label added)

**Comment by ilogico** [comment]
Since this is already a particular case, I would prefer it would refactor to `const { url } = options;` instead.

**Comment by dtinth** [comment]
@RyanCavanaugh Thanks for merging the PR #37902 — it’s working on my VS Code with JavaScript and TypeScript Nightly extension now.

Should this issue be put on the [TypeScript 4.7.0 milestone](https://github.com/microsoft/TypeScript/milestone/156)?
