### ISSUE TITLE
this-property assignments should use autoType to get control flow narrowing

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#37900]
Based [on discussion](https://github.com/microsoft/TypeScript/pull/37827#discussion_r405787859) in https://github.com/microsoft/TypeScript/pull/37827, we could further improve typing of this-property assignments if we used `autoType` whenever we can't tell what type they should have.

This has three open questions:

1. Performance.
2. Is there benefit in real code? This only helps if (1) we aren't getting the right type some of time where (2) the auto type would get the right type. This is likely to be when a property is used repeatedly in a long method.
3. What changes are actually needed. Just returning autoType doesn't work, because control flow narrowing doesn't seem to track this-property assignments as references.

**Comment by sandersn** [comment]
implementation hiccup number 1 is that a union with `auto` turns into `any`, not `auto`.

**Comment by ahejlsberg** [comment]
I _think_ you could do this by utilizing logic similar to that in `checkPropertyInitialization` where we check that properties are definitely assigned in the constructor. In particular, the control flow walk we do in `isPropertyInitializedInConstructor` where we start from a virtual flow node representing all constructor return points. If you were to pass in `autoType` for the declared type and `undefinedType` for the initial type, the result should be a CFA'd aggregate of the possible assigned values upon return from the constructor. You'd furthermore have to special case `this.xxx` property access expressions _inside_ the constructor to similarly use `autoType` and `undefinedType` for declared and initial types (which would allow `this.x = this.x + ...` without circularity errors). But for references _outside_ the constructor you would rely on the CFA computed type.

**Comment by ahejlsberg** [comment]
@sandersn I've put up an experimental prototype of this in #37920.
