### ISSUE TITLE
`getTypeAtLocation` fails on a `PropertyAccessExpression` in a type position

### ISSUE THREAD

**Issue by uniqueiniquity** [microsoft/TypeScript#37901]
**TypeScript Version:**  3.8.3

**Search Terms:**
`getTypeAtLocation`

**Code**

```ts
declare class SomeClass implements NodeJS.CallSite {
  //
}
```

**Expected behavior:**
`getTypeAtLocation` on the `PropertyAccessExpression` node for `NodeJS.CallSite` should return `CallSite`.

**Actual behavior:**
Instead, it returns `any` with intrinsic name `error`.

**Notes**
Note that `getTypeAtLocation` on the parent `ExpressionWithTypeArguments` does actually succeed.

**Playground Link:** N/A

**Related Issues:** #35233

Thanks to @bradzacher for finding this!

**Comment by bradzacher** [comment]
Related issue: https://github.com/typescript-eslint/typescript-eslint/issues/1868

**Comment by cruhl** [comment]
I just ran into this while using TypeScript+ESLint:

`Unsafe member access .toSortedLine on an any value.`

Where the "any value" is a perfectly normal namespace.
