### ISSUE TITLE
export keyword has different color(blue in VSCode) on classes and interfaces 

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3790]
I'm not sure if this is an editor bug or LS bug. I just noticed this difference in color:

<img width="213" alt="screen shot 2015-07-09 at 2 03 56 pm" src="https://cloud.githubusercontent.com/assets/1324476/8588978/60c22634-2643-11e5-8c12-3dca98ad5cfa.png">

Also all identifiers are not colored the same. Some has light blue/gren and some black.

**Comment by DanielRosenwasser** [comment]
@dbaeumer might have filed something similar under https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/274.

**Comment by mhegazy** [comment]
Can you file this on https://code.visualstudio.com/Issues/List instead?
