### ISSUE TITLE
tsconfig.json target lead to an error

### ISSUE THREAD

**Issue by rabbitooops** [microsoft/TypeScript#37915]
**TypeScript Version:**  3.8.3

**Search Terms:**

**Code**
https://github.com/rabbitooops/lerna-test

**More**
I am not sure if it's a bug, please help me, thank you!
When target is ES5, it works properly.
![image](https://user-images.githubusercontent.com/20941062/79069878-4a69a480-7d04-11ea-9dce-dc5fe2ca3144.png)
But if I set target to ES6 or higher version, it will throw an error.\
![image](https://user-images.githubusercontent.com/20941062/79069900-71c07180-7d04-11ea-8a14-12d4917a11b1.png)

**Comment by AviVahl** [comment]
Uncomment "moduleResolution": "node" so it won't automatically change when you move between targets.

**Comment by rabbitooops** [comment]
@AviVahl This answer is very helpful! Thanks!
