### ISSUE TITLE
checkJs: "Cannot find module" in .html file inline module

### ISSUE THREAD

**Issue by henrahmagix** [microsoft/TypeScript#37919]
**TypeScript Version:**  3.9.0-dev.20200411, the latest as of writing in the [Nightly VS Code extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Search Terms:**
- Cannot find module
- html file
- ts-check
- checkJs

**Code**

[Example repo](https://github.com/henrahmagix/ts-check-html-inline-module-bug/tree/ea8ee7d45d861165ec2852b7aea3e5f81eb67eb4): visit the links in the README to see that the code works, and open the repo in VS Code to see the error.

```js
// src/module.js
export const anything = true;
```
```js
// src/component.js
import { anything } from './module.js';
// Correct: anything is available, and Go To Definition goes to src/module.js
alert('anything in .js: ' + anything); // true
```
```html
<!-- src/component.html -->
<script type="module">
  // @ts-check
  import { anything } from './module.js';
  // Error: Cannot find module './module.js'
  alert('anything in .html: ' + anything); // true
</script>
```

**Expected behavior:**

ts-check in the html file doesn't raise an error, and Go To Definition works on `anything`.

**Actual behavior:**

ts-check errors and Go To Definition only shows references in the html file.

**Comment by AviVahl** [comment]
typescript itself doesn't really process or handle `.html` files on its own.

`vscode` starts a separate language service with the javascript *separated* from the html document: https://github.com/microsoft/vscode/blob/release/1.44/extensions/html-language-features/server/src/modes/javascriptMode.ts#L41

Just an educated guess, but the issue might reside on that side. FYI @aeschli

**Comment by henrahmagix** [comment]
Just discovered a bug in the HTML Language Server, so maybe this is related? https://github.com/microsoft/vscode/issues/95090

**Comment by henrahmagix** [comment]
I'm having lots of problems trying to type check my inline script modules. They run fine in the browser. So I've filed https://github.com/microsoft/vscode/issues/95344, I really hope it gets fixed soon, it's quite sad to add `@ts-check` and see a problem that's impossible to fix :<

Thanks for the code link @AviVahl – totally makes sense that the JavaScript(/TypeScript) LSP is used on the contents separately from the HTML LSP.

Maybe this is the problematic line?
https://github.com/microsoft/vscode/blob/release/1.44/extensions/html-language-features/server/src/modes/javascriptMode.ts#L66
```ts
getCurrentDirectory: () => '',
```

**Comment by RyanCavanaugh** [comment]
I think the linked issue is the root cause here; we don't directly handle HTML files so this would be an editor-side issue
