### ISSUE TITLE
[Feature Request] Shorthand for embedded generic constructs

### ISSUE THREAD

**Issue by INVITR0** [microsoft/TypeScript#37914]
**My Proposal**

The Ability to give generic constructs embedded in a generic function or class a name for easier reference. With this I mean assigning long(ish) constructs like `Pair<A, B>` a shorthand like `P` for more efficient reference throughout the code.

**Syntax Idea**

My Idea right now of a possible syntax is the following:
```typescript
genericConstruct<GENERIC_TYPES> with (anotherGeneric<GENERIC_TYPES> as SHORTHAND, ...)
// (Parenthesis only for multiple shorthands)
```

**Example**

A very basic Example would be something like this:
```typescript
type Index = string | date | number;
type ListEntry<I extends Index, T>;
```
With the class `List`
```typescript
class List<I extends Index, T> {
    private entries = ListEntry<I, T>[];

    public constructor(...items: ListEntry<I, T>) {
        entries.push(...items);
    }

    public pushEntry(item: ListEntry<I, T>) { ... }
}
```
becoming something like this:
```typescript
class List<I extends Index, T> with ListEntry<I, T> as E {
    private entries = E[];

    public constructor(...items: E) {
        entries.push(...items);
    }

    public pushEntry(item: E) { ... }
}
```

**Why I think this is useful**

I have searched quite a while, but I have not found a feature that exactly matches what I described. Sure, you can define helper Types that can shorten the amount of code, but a real shorthand would save quite a lot of writing in large classes.

**Additional comments**

I don't think this should impact how the generic Type/Class/Function/etc is seen from outside. When I start typing `myList.pushEntry(...` I still want to see `pushEntry(item: ListEntry<I, T>) `.

**Comment by RyanCavanaugh** [comment]
It seems like you're really asking for #7061? The use case seems to be to have a local type alias, which has many scenarios that aren't adjacent to a type parameter list, so it seems weird to tie the two together.

Sidenote: Having invalid other syntax in your proposal makes it extremely difficult to understand (e.g. `ListIndex` not having a definition?)
