### ISSUE TITLE
Typings for npm packages Wiki 404

### ISSUE THREAD

**Issue by fishcharlie** [microsoft/TypeScript#37922]
**TypeScript Version:** NA

**Search Terms:**

- typings for npm packages wiki 404
- npm package.json typings wiki 404

**Code**

NA

**Expected behavior:**

The link at https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages to not throw a 404 error.

**Actual behavior:**

The link at https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages says the page has been moved to https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html which throws a 404 error.

The link on the wiki should be updated to direct the user to the correct link.

**Playground Link:** NA

**Related Issues:** NA

**Comment by orta** [comment]
These aren't 404ing for me on prod or staging, so I'm going to close
