### ISSUE TITLE
Property X dows not exist on window for usage in other scripts

### ISSUE THREAD

**Issue by serkonda7** [microsoft/TypeScript#37929]
**TypeScript Version:**  3.8.3

**The relevant parts of my Code**
preload.ts
```ts
declare global {
    interface Window {
        myFunc(param: string): void;
    }
}

const myFunc = (param: string): void => { ... };

window.myFunc = myFunc;
```

script.ts
```ts
window.myFunc('parameter');
```

**Expected behavior:**
Compile without errors and execute the function at runtime.

**Actual behavior:**
The compiler throws the following error: 
`script.ts error TS2339: Property 'myFunc' does not exist on type 'Window & typeof globalThis'.`

preload.ts compiles without any problems. This error only appears at using custom properties of window.

**Comment by RyanCavanaugh** [comment]
How are you running `tsc` ?

**Comment by Serkonda** [comment]
I have a yarn build script:
`"build": "tsc -p ./tsconfig.main.json && tsc -p ./tsconfig.renderer.json"`

Maybe this error happens because preload.ts is compiled by the first part and script.ts by the second.

**Comment by Serkonda** [comment]
@RyanCavanaugh I found a bad workaround. 
First I compile all my files with `"module": "es2015"` and in a second step recompile these files that need to be commonjs modules.

**Comment by RyanCavanaugh** [comment]
We fixed multiple bugs around this since the last time I looked at it; I expect it's fixed now. Please open a new issue with a consolidated repro if that's not the case. Thanks!
