### ISSUE TITLE
Declaration file has wrong reference path for composite projects

### ISSUE THREAD

**Issue by timocov** [microsoft/TypeScript#37928]
**TypeScript Version:** 3.9.0-dev.20200413, 3.8.3

**Search Terms:** composite projects, declaration files, paths, reference, baseUrl

**Code**

1. Download zip with the project [ts-bug.zip](https://github.com/microsoft/TypeScript/files/4469787/ts-bug.zip)
1. `npm install`
1. `npm run build-non-composite` - it should be fine

Then, if you run `npm run build` - there are 2 errors:
```
lib/src/common/nominal.d.ts:2:55 - error TS2304: Cannot find name 'MyNominal'.

2 export declare type Nominal<T, Name extends string> = MyNominal<T, Name>;
                                                        ~~~~~~~~~

lib/src/common/nominal.d.ts:1:22 - error TS6053: File 'C:/projects/src/common/types.d.ts' not found.

1 /// <reference path="../../../src/common/types.d.ts" />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

And if you run `npm run build-baseUrl` - there are another 2 errors:
```
lib/src/common/nominal.d.ts:2:55 - error TS2304: Cannot find name 'MyNominal'.

2 export declare type Nominal<T, Name extends string> = MyNominal<T, Name>;
                                                        ~~~~~~~~~

lib/src/common/nominal.d.ts:1:23 - error TS2688: Cannot find type definition file for 'types'.

1 /// <reference types="types" />
                        ~~~~~
````

This is pretty similar to #31696. In this case we have 2 bugs:

1. For `npm run build` incorrect generated path for `reference path` (it exits for 1 more folder).
1. For `npm run build-baseUrl` (which is differ from `build` case in the only `baseUrl` compiler option in `common` sub-project) incorrectly replaced `refernce path` with `reference types`, so no project could use it because they might (and will) not have the same `baseUrl` option.

**Related Issues:** #31696, #25600

**Comment by timocov** [comment]
I think that in both cases there should be `reference path` directive with correct path (without exceeded `..`).

**Comment by sheetalkamat** [comment]
`npm run build` is definitely bug and #39645 fixes that.

` npm run build-baseUrl ` well that raises questions. #32878 started preferring `types` over `reference paths` to make it more portable. But our resolve type reference name doesnt use baseUrl so this is kind of questionable.
Other way to look at it would be when file is referenced throught only referece path from root file tree (or relative imports) prefer relative path instead of portable path.
