### ISSUE TITLE
Type 'ConstructorParameters<C>' must have a '[Symbol.iterator]()' method that returns an iterator.

### ISSUE THREAD

**Issue by jfet97** [microsoft/TypeScript#37923]
**TypeScript Version:**  found in 3.8.3 but still present in Nightly

**Search Terms:** ConstructorParameters, Symbol.iterator

**Code**

```ts
function instantiate<C extends (new (...args: any) => any)>(
    constructor: C,
    ...args: ConstructorParameters<C>
) : InstanceType<C> {
   return new constructor(...args); // <-- error
}

class Circle {
    constructor(public radius: number) {}
}

class Rectangle {
    constructor(public width: number, public height: number) {}
}

const circle = instantiate(Circle, 5);
const rectangle = instantiate(Rectangle, 3, 7);
```

**Expected behavior:**
`args` is a rest parameter, it has the `[Symbol.iterator]()` method. The fact that its type is `ConstructorParameters<C>`, a **tuple type**, shouldn't be a problem.

**Actual behavior:**
Error: Type 'ConstructorParameters<C>' must have a '\[Symbol.iterator\]'() method that returns an iterator.

**Playground Link:** https://www.typescriptlang.org/play?target=7&ts=3.9.0-dev.20200412#code/GYVwdgxgLglg9mABDMBnKBDMsNQKYA8AwongB75gAmqiAFGHgO70B07GATgOaoBciLAE8AlIgC8APkFhRkugChEyxBATpOIaHE4CiAGiUr2rLrz3qom7ZwAKXDAFs8+TqmKSFYgQEk0mSDwAFSEAB0IiaQBvI0ROFxBOJEYWNX9rKB06EzNUEQBuBQBfBQUIABsMVFoiGE4KvEQYlVVLDKzQkAAjcpgIOIwqGBB+RDAQRy68TjEokpKyyurEACU8aCxucsbmlTSNLUzOOk6evsQmGCooAAsBccnp-URT3v6bvBhuG6h7iamZk15qV9lBVHUGhJkP4sDh8HRavVts8AKwFMqWOLrAJbRriaHoWEwXB4OhrDZgXHPADMzwA7AUgA

**Comment by rjcnd105** [comment]
@jfet97 I got the same problem! How could you solve it? please let me know...

**Comment by vic1707** [comment]
did one of you found a solution ? @rjcnd105 @jfet97
