### ISSUE TITLE
Default export rename not propagated beyond re-export

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#37957]
**TypeScript Version:**  3.8.3

**Search Terms:** default import export rename alias

**Code**

`src/foo/foo.ts`:
```typescript
const foo = 1;
export default foo;
```

`src/foo/index.ts`:
```typescript
export { default } from './foo';
```

`src/main.ts`:
```typescript
// Workaround: import from module directly
// import foo from './foo/foo';

import foo from './foo';
foo;
```

1. Go to `src/foo/foo.ts`
1. Rename `const foo` to something else

**Expected behavior:**

Default import in `src/main.ts` is renamed

**Actual behavior:**

Default import in `src/main.ts` is not renamed

If you import from the module directly, i.e. `src/foo/foo.ts` instead of `src/foo`/`src/foo/index.ts`, then it works as expected.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
I don't think it should. `foo` in `src/main.ts` is that file's choice of name and there's nothing necessitating a change there.

**Comment by OliverJAsh** [comment]
This works if we remove the re-export from the equation, so why wouldn't the same logic apply when using re-exports?

`src/foo/index.ts`:
```typescript
const foo = 1;
export default foo;
```

`src/main.ts`:
```typescript
import foo from './foo';
foo;
```
