### ISSUE TITLE
Not inferring correct interface after property validation.

### ISSUE THREAD

**Issue by vajahath** [microsoft/TypeScript#37952]
**TypeScript Version:**  3.8.3

Search terms: Type-inference

**Code**

:heavy_check_mark:  Working code: (please note how the type inference worked here properly) ([playground](https://www.typescriptlang.org/play/index.html?ssl=19&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJIGUxWAsBBEYAWzgBtkBvAKGWTAE8AHCALmQGctQBzAbmQD0A5ACNgUACYAaZHEIlSNZAgD2pFVDadsIPlQC+VKg2bIAKgAU4UOEWQBeNJmy4CxMsgA+yAK4gJEDCgEBK8RjB+uMAqIMgwKioAFHLupGyW1rYAlJRKwDDIiQCEKQo51LS0YAAWUCoA7sggEI0AolB1UIkARCAqsvJk3VlhtIZKqiCcyABuZMASbgpsGFyug+SOpWT8QrIwkFCz8xJwYNEgMqsu+BvIADwAtOZWNnYsAPIA0hMx7GoQAB06m4iTmpAWSzIIwMQA))
```ts
interface IStrictAnimal {
  type: string; // bird, animal
  color: string;
}

type TParam = IStrictAnimal | undefined;

function foo(animal: TParam) {
  if (!animal) {
    throw new Error("no animal");
  }

  const validAnimal: IStrictAnimal = animal; // after validation, IStrictAnimal <- TParam :OK
  console.log(validAnimal);
}
```

:crab: Failing code (please note how the type is not inferred properly) ([playground](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=15&pc=2#code/JYOwLgpgTgZghgYwgAgJIHkAOZgHsRwA2AgiMALZHIDeAUMsmAJ6YQD8AXMgM5hSgBzANz1kCXIVxROPPoJEBfWrVCRYiFKgDKchGFIUqdBs1Zde-EMNHjJUc3KuLlMAK4g9eEMgBGcKAAUcGSUhFwY2F5EBqEAlDSiwDDIAQCEwYaEyAA+2cjpIUQAdLZSOXkFmUWmEPHGDIwAFlC4AO7IIBDtAKJQLYEARKAAbkTAACbIGaEDsSIMSgw2+LzIo4QTMUThOvx6W1kAvFOFhELIAPQXUzBqa2PjcDj4ADRou8D7p8gAPAC0AA80FhngQSN8OAA5dAAFWQ6AA0ssQNwJBAipIBAF1ptTnNaAogA)):
```ts
interface IOptionalAnimal {
  type?: string;
  color?: string;
}

interface IStrictAnimal {
  type: string;
  color: string;
}

function bar(animal: IOptionalAnimal) {
  if (!animal || !animal.color || !animal.type) {
    throw new Error("invalid animal");
  }
  
  const validAnimal: IStrictAnimal = animal; // after validation, IStrictAnimal <-x IOptionalAnimal :NOT OK
//      ^^^^^^^^^^^  ====> Error!
  console.log(validAnimal);
}
```
Error:
```
Type 'IOptionalAnimal' is not assignable to type 'IStrictAnimal'.
  Types of property 'type' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.ts(2322)
```

Here in the first case, ts is able to deduce the type after the if clause but in the second case, fails.

**Comment by RyanCavanaugh** [comment]
See #10065

**Comment by vajahath** [comment]
Alright so that's a design limitation. Got it.
I went through the thread (#10065). Despite these tiny limitations, I just wanted to let the ts team know that this whole ts thing you guys are working on, is very cool and damn smart :star2: 

closing this.
