### ISSUE TITLE
Overloaded splice definition incorrectly ignored when using Function.prototype.apply

### ISSUE THREAD

**Issue by DavidANeil** [microsoft/TypeScript#37951]
**TypeScript Version:**  3.9.0-beta and 3.9.0-dev.20200412

**Search Terms:**
Overload strictBindCallApply splice

**Code**

```ts
var arr = [1, 2, 3];

var other = [4, 5, 6];

arr.splice.apply(arr, [0, 1, ...other]);
```

**Expected behavior:**
While arguably bad code, it should pass typechecking.

**Actual behavior:**
```
error TS2345: Argument of type '[number, number, ...number[]]' is not assignable to parameter of type '
[number, (number | undefined)?]'.
  Types of property 'length' are incompatible.
    Type 'number' is not assignable to type '1 | 2'.
```
**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200412#code/G4QwTgBOkLwQ2gRgDQQEyoMwF0DcAofUSAewBcALAU1gQBZUBWVANj0OgDoBnABwBsAlgGMqnELwEBPABTRU8AAyoUETuvLUw2AJS4gA

**Comment by RyanCavanaugh** [comment]
This is a design limitation of `strictBindCallApply`; overload resolution is not supported. See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#caveats
