### ISSUE TITLE
wrong type inference for boolean

### ISSUE THREAD

**Issue by Akimotorakiyu** [microsoft/TypeScript#37953]
**TypeScript Version:**  3.8.3

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const x = true

```

**Expected behavior:**
the type of x should be boolean
**Actual behavior:**
the type of x is true
**Playground Link:** 
https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBAHjAvDKAnArgUwFBA

![图片](https://user-images.githubusercontent.com/31165554/79193885-1904ec00-7e5e-11ea-940c-2771edb8fb95.png)

https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgIUwGcFsAVATzGABFgjs4BvAKDjgG0woIwiAuOERhRkAcwC6gpAFcAtgCM0cAD5CR41XAUQIAG2CYkAbhYBfFqEiw42PcSJxK1OgwA8ZOKFRIAJo8IScipaemwAPmY2OBgQgEkkdAhBMlN2CHR0UjRBAHlM7KgPSIBeOCRgAHc4fKzcKAAKGAALBCIASjTbCCRhKBlsGGgm+MTkp3ao9nYWtoA6WOoEpLgyxeBliC6LC0twaHg7BxqC+o8vEB9-AmJSZ1CGSNZ2bFa9XwBZeiJMMWAAfjypzQbiMFHCXXWrmwKRC0OKpmi2B6fQGQ0aULCsJcYWKk2e01mRAWcLCqxipIY2xY0UqolQDTkRDEgImzB2NORvXgAAVgLwDOSKtV7tCGgS2gAlBBiZowQRYPREYDmTo0vkC4BzDJ1NBzOkIBkSojS2XymL9FVmNVAA
![图片](https://user-images.githubusercontent.com/31165554/79288551-a0536d80-7ef9-11ea-95ce-75ef48cda4e9.png)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.

**Comment by orta** [comment]
The feature is type narrowing: http://www.staging-typescript.org/play/?q=311#example/union-and-intersection-types

**Comment by Akimotorakiyu** [comment]
But in this case, The feature cause an error.
https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgIUwGcFsAVATzGABFgjs4BvAKDjgG0woIwiAuOERhRkAcwC6gpAFcAtgCM0cAD5CR41XAUQIAG2CYkAbhYBfFqEiw42PcSJxK1OgwA8ZOKFRIAJo8IScipaemwAPmY2OBgQgEkkdAhBMlN2CHR0UjRBAHlM7KgPSIBeOCRgAHc4fKzcKAAKGAALBCIASjTbCCRhKBlsGGgm+MTkp3ao9nYWtoA6WOoEpLgyxeBliC6LC0twaHg7BxqC+o8vEB9-AmJSZ1CGSNZ2bFa9XwBZeiJMMWAAfjypzQbiMFHCXXWrmwKRC0OKpmi2B6fQGQ0aULCsJcYWKk2e01mRAWcLCqxipIY2xY0UqolQDTkRDEgImzB2NORvXgAAVgLwDOSKtV7tCGgS2gAlBBiZowQRYPREYDmTo0vkC4BzDJ1NBzOkIBkSojS2XymL9FVmNVAA
![图片](https://user-images.githubusercontent.com/31165554/79288551-a0536d80-7ef9-11ea-95ce-75ef48cda4e9.png)

**Comment by JasonHK** [comment]
> But in this case, The feature cause an error.
> https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgIUwGcFsAVATzGABFgjs4BvAKDjgG0woIwiAuOERhRkAcwC6gpAFcAtgCM0cAD5CR41XAUQIAG2CYkAbhYBfFqEiw42PcSJxK1OgwA8ZOKFRIAJo8IScipaemwAPmY2OBgQgEkkdAhBMlN2CHR0UjRBAHlM7KgPSIBeOCRgAHc4fKzcKAAKGAALBCIASjTbCCRhKBlsGGgm+MTkp3ao9nYWtoA6WOoEpLgyxeBliC6LC0twaHg7BxqC+o8vEB9-AmJSZ1CGSNZ2bFa9XwBZeiJMMWAAfjypzQbiMFHCXXWrmwKRC0OKpmi2B6fQGQ0aULCsJcYWKk2e01mRAWcLCqxipIY2xY0UqolQDTkRDEgImzB2NORvXgAAVgLwDOSKtV7tCGgS2gAlBBiZowQRYPREYDmTo0vkC4BzDJ1NBzOkIBkSojS2XymL9FVmNVAA
> ![图片](https://user-images.githubusercontent.com/31165554/79288551-a0536d80-7ef9-11ea-95ce-75ef48cda4e9.png)

@Akimotorakiyu You can use a interface fix the issue:

```typescript
interface IPeople extends BasicTypeDesc
{
    isRight: boolean;
}

const People = new TypeDesc<IPeople>({ isRight: false });
```

**Comment by Akimotorakiyu** [comment]
> @Akimotorakiyu You can use a interface fix the issue:
> 
> ```ts
> interface IPeople extends BasicTypeDesc
> {
>     isRight: boolean;
> }
> 
> const People = new TypeDesc<IPeople>({ isRight: false });
> ```

I have too many difference kind `TypeDesc` instance adn every kind instance is unique kind, enn... that's to say I need many extra interface to fix that?

**Comment by RyanCavanaugh** [comment]
You can write
```
    isRight: false as boolean
```

**Comment by Akimotorakiyu** [comment]
@RyanCavanaugh Yes, I did.
