### ISSUE TITLE
React prop type types lost when using spread 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37950]
From https://github.com/microsoft/vscode/issues/93361

**TypeScript Version:**  3.9.0-dev.20200413

**Search Terms:**
- react
- prop types
- suggest, suggestions

**Code**
For the JS:

```jsx
import React from 'react'
import PropTypes from 'prop-types'

const Component = ({ prop, ...otherProps }) => <div />

Component.propTypes = {
	/** Test prop */
	prop: PropTypes.bool
}

const test = <Component />

export default Component
```

1. In `Component`, trigger suggestions

**Expected behavior:**
`prop` is suggested and has a boolean type. It should also include the documentation `test prop`

**Actual behavior:**
`prop` is suggested but it has an `any` type

Removing `...otherProps` fixes the issue

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't attempt to interpret `propTypes` assignments and we've scoped this out of our JSX support
