### ISSUE TITLE
Initializing js/ts features Causes Application to hang

### ISSUE THREAD

**Issue by klleroy** [microsoft/TypeScript#37967]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.3

**Search Terms**
- TS Server (tsserver)

---

Issue Type: <b>Performance Issue</b>

Upon opening VS Code, JS/TS Features are initialized. This causes the Application to grind to a halt. I am not even using Typescript and I'm still forced to wait for this.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:17:38.324Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3306)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 1, 0|
|Memory (System)|15.58GB (8.92GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   112	 18228	code main
    0	    32	 18232	   zygote
    0	   112	 18272	   gpu-process
    0	    48	 18284	   utility
    0	   112	 18496	   shared-process
    0	     0	 18893	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 18894	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   255	 18612	   window (server.js - tasteslikehome - Visual Studio Code)
    0	   223	 18634	     extensionHost
    0	    80	 18707	       electron_node tsserver.js 
   35	   144	 18708	       electron_node tsserver.js 
    0	    80	 18776	         electron_node typingsInstaller.js typesMap.js 
    0	    96	 18744	       electron_node eslintServer.js 
    0	     0	 18642	     /bin/bash
   26	   303	 18847	       npm
    0	    48	 18689	     watcherService
    0	    48	 18706	     searchService
    0	    96	 18873	   window (Issue Reporter)
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
jsrefactor|cms|2.20.5
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.7.0
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.1
python|ms-|2020.3.69010
vsliveshare|ms-|1.0.1783
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0

</details>

**Comment by mjbvz** [comment]
@jobu206 Was this log was collected during the hang? 

Potentially sounds similar to https://github.com/microsoft/TypeScript/issues/37653 but the logs don't show an install

**Comment by jobu206** [comment]
@mjbvz yep, sure was.

**Comment by sheetalkamat** [comment]
@klleroy please check if this is still the issue, if it is, provide the log using latest vscode and typescript nightly. 
I would want you to follow the repro steps completely ( do let us know those steps) and wait for log to complete for those requests before you submit the log. Your previous log just shows project initializing but doesnt show npm install or anything else which is where you are seeing the issue.

You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Comment by klleroy** [comment]
I've been attempting to test this out but I can't get a repro. Closing as no repro. Will open a new issue if I have more problems.
