### ISSUE TITLE
Incorrect Array.concat typings

### ISSUE THREAD

**Issue by artalar** [microsoft/TypeScript#37978]
**TypeScript Version:**  3.9.0-beta

**Search Terms:** array.prototype.concat, concat, concat is not a function.

**Code**

```ts
const arr1 = [[1]];

// TS: number[][]
const arr2 = arr1.concat([2]);

// TS: ok
// runtime: arr2[1].concat is not a function 
arr2[1].concat()
```

**Expected behavior:**

Type error `Property 'concat' does not exist on type 'number'.ts`

**Actual behavior:**

Types is ok, runtime error.

**Playground Link:** https://www.typescriptlang.org/v2/en/play?ts=3.9.0-beta#code/MYewdgzgLgBAhgJwQRhgXhgbU8gurgbgCgjRJZEEAmdeJZAOjODigApMrcBKYoyqjlxNwLdtyJA

**Fix:**

```ts
interface Array<T> {
  concat<T1>(...items: T1[]): (T | (T1 extends (infer T1)[] ? T1 : T1))[];
}
```

**Comment by plzgix123** [comment]
у меня всё работает

**Comment by artalar** [comment]
@plzgix123 click to "run" in REPL
![image](https://user-images.githubusercontent.com/27290320/79319519-1adbb780-7f11-11ea-8c51-44ea6a042b8d.png)

**Comment by RyanCavanaugh** [comment]
Please add to #36554

**Comment by artalar** [comment]
https://github.com/microsoft/TypeScript/issues/36554#issuecomment-580921643
