### ISSUE TITLE
Inaccurate schemastore description for isolatedModules

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#37977]
The current description on schemastore for `isolatedModules` in `tsconfig.json` and `jsconfig.json` is something to the effect of

```
Unconditionally emit imports for unresolved files
```

https://github.com/SchemaStore/schemastore/blob/d1d79204ebbd48d24e7130bdfb156e8f7b1b9279/src/schemas/json/tsconfig.json#L229

https://github.com/SchemaStore/schemastore/blob/d1d79204ebbd48d24e7130bdfb156e8f7b1b9279/src/schemas/json/jsconfig.json#L220

Is this an artifact of time?

On our [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) page, we describe it as

```
Perform additional checks to ensure that separate compilation (such as with transpileModule or @babel/plugin-transform-typescript) would be safe.
```

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh I'm just trying to get clarity before I update this - would you and @sheetalkamat say the original descriptipn is inaccurate?

**Comment by sheetalkamat** [comment]
Our description in commandLineParser is `Transpile_each_file_as_a_separate_module_similar_to_ts_transpileModule` which seems accurate.

**Comment by jakebailey** [comment]
Just looking at old issues; this was fixed a couple of years ago back in https://github.com/SchemaStore/schemastore/pull/1534.
