### ISSUE TITLE
Undetected runtime error when a tuple containing an array is used inside a generic

### ISSUE THREAD

**Issue by JosephJNK** [microsoft/TypeScript#37972]
**TypeScript Version:**  3.8.3, Nightly, and all other 3.x versions available in TypeScript playground

**Search Terms:**
generic tuple
tuple runtime error
generic runtime error
tuple subtype

**Code**
Apologies that this is long, I've spent an hour and a half trying to simplify this but the behavior changes if I don't use all three of (union types, generic tuples, arrays). For context, this is a simplified version of some code I wrote while writing a parser combinator library.
```TypeScript
// Set up some types. The union type inside Parser seems to be necessary to reproduce the issue.
class ParseError { }
class ParseResult<T, U> {
  parsed: T;
  remnants: U;
  constructor(parsed: T, remnants: U) {
    this.parsed = parsed;
    this.remnants = remnants;
  }
}
type Parser<T, U> = (input: U) => ParseError | ParseResult<T, U>;

// This function is incorrect, but TS doesn't realize it.
function runParser<T>(
  parse: Parser<T, string>
): Parser<[T, Array<string>], Array<string>> {

  // Parse returns ParseError | ParseResult<T, string>
  // This nested function should return ParseError | ParseResult<[T, Array<string>], string]
  // Somehow the first one is being allowed in place of the second one
  return (arr: Array<string>) => {
    const found = arr[0];

    return parse(found);
  };
}

// Demonstrating the issue
const foo = runParser(x => new ParseResult(1, x));
const bar = foo(["x", "y"]);

if (bar instanceof ParseError) throw new Error();
const { parsed, remnants } = bar;

// This line will throw a runtime error; remnants is a string, not an array
console.log(remnants.map(x => x));
```

**Expected behavior:**
I believe that a type error should occur inside `runParser`. Specifically, a value of type `ParseError | ParseResult<T, string>` should not be allowed where a value of type `ParseError | ParseResult<[T, Array<string>], string]` is expected.

**Actual behavior:**
No type error occurs, a runtime error occurs instead.

**Playground Link:**
[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=36&pc=35#code/PTAEGUFMBdQVwA6gM4HsC2lTQJ4MsgHSgAqAFlnAHYCWqV2eWNVyNAJlgAoCGATskh8UkSOmTZUoAEZYqkAMYFk-HJNB9ICPqnZwl2CqBrJkcSIQCwAKAUAbHqdC8BkAKJ8dwgN6gAvjb2jhIuggBKBHB20AA8JAA0oACqAHyg3jagoAj8guwAXKQA3JkaYlQ8VNDIhUkl1lkK9MjQfPrQqHwAFDmuBaSJmugVVTXJAJTppVnQZCaEvXmgALzZuZDs9Vkzc0RDI9UrZcOV1Vv+NgHWuPjO63xxialHXSwIcNC1k8tpoe6enVAAB87q4ImZoo9kil6jYQKRdqAAGbUBTQOgMEzGKhNTyKaCJaQfUjgUDsVAEKgAclgmh4dhoAC9mNArNYUTj0fQNNQ-g8SCkuqVFpBCnyoS0+CwAOYpGzjMX3GIAbQSoAAgp4eDgYpKZSkALqJTV8bW61r6tIZayleF-MrQOB8VigwQeLzA12QcFRWJqvVUWW2sDkLHyFobZGorkMZBkVBRdgOp0MP7uwEgv4+yGq41anUB2VGlAWwMG4MQDCQeMAd0MWCRNAEsHozAkshloHpdlQNcjLGyDgMqCR9ZETSoSdbpU0judoC6-D4hRNZsLKW+VumoAnLWRCcnRyXyoADAbYQ1trOU2tXF0kQf2ONzn56lc4WAACJiZqtHjowMxxMMxIECX99ykVY2ioPkugADxWNJ5DrLNImiLoAEZEjg8ZnzA1hYGkfgjgfVAumVAAiOCKMSCicAog08JtawaFHLoiOEFgWkqJQRy9dM+EmWYdDrZDQAEromN3WBfBFdhBnKU4JD8I4OIveFQwkBl5FAGsaDsOxDBErseSqGhMFAIQvCKY4DgkLEeBLKVA0SKhUFgSou3zfC0DsCwe2lLp9iUwh0B4BB4MQ0AcOfIA)

**Related Issues:**
I could not find any similar issues.

**Comment by RyanCavanaugh** [comment]
The problem here is that `ParseError` is empty, so your `runParser` function returns something that is structurally a valid `ParseError` (because anything is), then later TS believes that you don't have any structural-only-matching things when you check for `instanceof ParseError`. In general, making empty classes is a very bad idea and will lead to subtle issues like this; using a signalling primitive instead is much preferable.

**Comment by JosephJNK** [comment]
I see. I'm coming from Flow and did not know that this empty class behavior is different. Thank you!
