### ISSUE TITLE
Backtick literals in utility types

### ISSUE THREAD

**Issue by fxedel** [microsoft/TypeScript#37983]
##  Search Terms

Template string, Util, Omit, quotes

## Suggestion

Allow the usage of template literals in utility types, like here:

```ts
type UserWithoutPassword = Omit<User, `password`>;
```

Currently, this causes the errors `Generic type 'Omit' requires 2 type argument(s).` and `'>' expected.`.

Quoted from #30962, which proposed a similar change:

> This is especially important because the backticks mode of the quotes rule from ESLint breaks programs. While it could be seen as an ESLint bug, I think it should be possible for TS to use raw template string interchangeably with regular strings as long as they don't contain variables.

I'm not really sure if this only belongs to utility types, though, but that's where I faced this problem.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
See #29331
