### ISSUE TITLE
Provide a way to determine whether a SourceFile is an untitled, inexistent file

### ISSUE THREAD

**Issue by manuth** [microsoft/TypeScript#37987]
## Search Terms
tsserverlibrary, untitled, isdynamic

## Suggestion
Currently I'm trying to write a language service for typescript and I find myself unable to determine whether a file is untitled.

What I've noticed so far is that untitled files send `untitled:^Untitled-1` as its filename to the `getSymanticDiagnostics` function. This naming convention could change anytime and also it's not consistently containing an URI or a filepath.

Is there some way to check whether a `SourceFile` is untitled?

## Use Cases
I'm passing the files to a linter. If the file is untitled I'll get an incorrect results if I pass the filename which, at runtime, equals `untitled:^Untitled-1`.

## Examples
```ts
result = engine.executeOnText(file.getFullText(), ...(file.isUntitled ? [] : [file.fileName]));
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
@sheetalkamat is this a guaranteed format?

**Comment by sheetalkamat** [comment]
We do not have any concept of untitiled files in program as it doesnt need to know but tsserver has [isDynamicFileName](https://github.com/microsoft/TypeScript/blob/master/src/server/scriptInfo.ts#L274) that handles this to check if file needs to be checked on disk. In general any open file in editor may not exist on the disk since editor provides contents for the same.

**Comment by manuth** [comment]
Thanks for the rapid answer
I do not know whether this might be related to the `@internal`-tag but when I tried to look fot this method I found myself unable to find it

**Comment by sheetalkamat** [comment]
It is marked as internal. I dont see issue with making it public. PR is welcome to remove internal.
