### ISSUE TITLE
'npm install knex' causes BigInt to be valid in all JS files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37986]
https://github.com/microsoft/vscode/issues/95187

**TypeScript Version:**  3.9.0-dev.20200413

**Search Terms:**
- bigint
- npm install
- javascript

**Code**
For the JS:

```ts
// @ts-check

export const a = 1;

BigInt(1)
```

1. See error reported about `BigInt` since we are targeting es6 by default
1. Now run `npm install knex`

**Bug:**
The error goes away after the install

Go to definition on `BigInt` goes to `lib.es2020.bigint.d.ts`

**Comment by RyanCavanaugh** [comment]
See #37775
