### ISSUE TITLE
TypeScript error “TS2354: This syntax requires an imported helper but module 'tslib' cannot be found”

### ISSUE THREAD

**Issue by doberkofler** [microsoft/TypeScript#37991]
**TypeScript Version:**  3.8.3

**Search Terms:** TS2354

**Code**

**package.json**
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "test": "tsc --noEmit --project ./tsconfig.json"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/argparse": "1.0.38",
    "argparse": "1.0.10",
    "tslib": "1.11.1",
    "typescript": "3.8.3"
  }
}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "checkJs": true,
    "allowJs": true,
    "moduleResolution": "node",
    "target": "es2018",
    "module": "commonjs",
    "importHelpers": true,
    "lib": [
      "es2018"
    ]
  },
  "include": [
    "*.js"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**index.js**
```ts
'use strict';

const {ArgumentParser} = require('argparse');
```

**Expected behavior:**

**Actual behavior:**

I have reduced a problem with TypeScript to a simple example. When trying to run tsc, I get the following error message but tslib should be available.

```bash
$ tsc --noEmit --project ./tsconfig.json

index.js:3:8 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.

3 const {ArgumentParser} = require('argparse');
         ~~~~~~~~~~~~~~
Found 1 error.
```

**Playground Link:** https://codesandbox.io/s/quizzical-mclean-n9vvi?fontsize=14&hidenavigation=1&theme=dark

**Related Issues:**

**Comment by jordanjordanb1** [comment]
I was having this exact same issue and I figured it out! 

Add to paths in tsconfig.json
```
"paths": {
    "tslib" : ["path/to/node_modules/tslib/tslib.d.ts"]
}
```

**Comment by chiuan** [comment]
thanks gus！！！

**Comment by dzintars** [comment]
Seeing this error when opening Yarn PnP project in VIM. `yarn add -D tslib@latest` does not solves this. `npm i tslib@latest` does solves this, but it brings in `node_modules` directory to the project which is not what i want.
In VS Code everything works fine because it handles PnP.

**Comment by maneetgoyal** [comment]
Facing similar issue while migrating from Yarn 1.x to Yarn 2.x (which uses `pnp`).

**Comment by emmenko** [comment]
Has anyone found a solution for this issue (with Yarn v2)?

**Comment by rbuckton** [comment]
Seems like our checker is incorrectly checking for lib helpers in cases where they're not needed. We shouldn't need to check for them when using `--noEmit` or when checking CommonJS import syntax that just uses `require`.

**Comment by mihe** [comment]
I'm also seeing this error in JavaScript files when running with `--checkJs` and using object destructuring, even when targeting ES2020.

**Comment by DanCouper** [comment]
Ditto on object destructuring triggering the error. I can't use the `paths` option to fix this as I'm using PnP (I don't have a node_modules to point to). Is there a solution to get it working for the minute apart from either:

1. removing object destructuring from the code that is triggering the error (this is what I'm currently doing).
2. unplugging `tslib` then using a path to that (which seems unfeasibly fragile as it unplugs to a folder with a fully-qualified name like `tslib-npm-2.0.1-tslib-npm-2.0.1-26f70961f9`).

(nb installing `tslib` via NPM isn't really an option for me here)

**Comment by janpauldahlke** [comment]
just came accross this. can anyone provide cleaner solution, than adding ts-with npm? much appriciated.

**Comment by elpddev** [comment]
Using yarn pnp this can be overcome by executing tsc with yarn pnpify.

```
yarn pnpify tsc --someoptions
```

**Comment by slst19** [comment]
No matter what I do in the internet I still get the error. 

- I have upgraded tslib to ^1.10.0 and did npm i
- I already have tsconfig.json "moduleResolution": "node", "module": "esnext" so tried es2015 instead of esnext.
- Tried restarting vscode after everychange.
- Deleted and installed node modules from scratch.
Funny thing I have spreadarray being used in many places of my application but only in one place where I copied mat-tree functionality I get below error.

This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.ts(2343)

**Comment by evollhhan** [comment]
> No matter what I do in the internet I still get the error.
> 
> * I have upgraded tslib to ^1.10.0 and did npm i
> * I already have tsconfig.json "moduleResolution": "node", "module": "esnext" so tried es2015 instead of esnext.
> * Tried restarting vscode after everychange.
> * Deleted and installed node modules from scratch.
>   Funny thing I have spreadarray being used in many places of my application but only in one place where I copied mat-tree functionality I get below error.
> 
> This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.ts(2343)

I got the same __spreadArray error in my project. I npm i tslib to ^2.2.0 and the error is gone.

**Comment by RodrigoAB93** [comment]
> 
> 
> I was having this exact same issue and I figured it out!
> 
> Add to paths in tsconfig.json. And in your case, you will need to add "baseUrl" too.
> 
> ```
> {
>   // ...rest of config
>   "compilerOptions": {
>     // ...rest of compiler options
>     "baseUrl: ".",
>     "paths": {
>       "tslib" : ["path/to/node_modules/tslib/tslib.d.ts"]
>     }
>   }
> }
> ```

Thank you.

**Comment by validityone** [comment]
For those using pnp, you need to resolve the pnp path within tsconfig in your "compilerOptions":
```
const path = require("path");
const { resolveRequest } = require("pnpapi"); // built-in yarn pnp api

{
     "compilerOptions": {
         "baseUrl": ".",
         "paths": {
             "tslib": [resolveRequest("tslib", path.resolve("."))] // will resolve to ./.yarn/cache/...long-filename
         }
     }
}
```

**Comment by zrysmt** [comment]
https://stackoverflow.com/questions/58329178/the-syntax-requires-an-imported-helper-named-spreadarrays

This error might happen if you have in your tsconfig.json file :
```
{ 
  "importHelpers": true,
  "target": "es5"
}
```
If for any reason you can't upgrade to es6, setting importHelpers to false will make the error go away ...
