### ISSUE TITLE
Arrow function with never return type does not cause unreachable code when called

### ISSUE THREAD

**Issue by cherryblossom000** [microsoft/TypeScript#37998]
**TypeScript Version:**  3.8.3

**Search Terms:** arrow function never unreachable narrowing

**Code**

```ts
const f = (): never => {
    throw new Error()
}
f()
// should be unreachable but isn't
console.log()
```

**Expected behavior:**
`Unreachable code detected. (7027)` warning on line 6 (last line).

**Actual behavior:**
No warning.

**Playground Link:** [link](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAZjAvDAFASgFwzAUwG44BOSAfDAN4CwAUDHTFABaEgDu2O7AooS4ejQC+NOAOoB6cTAiMQAVwA2AExgAjHDDlhCOAIbBGu1Qo2q5sAJYQwAcig1QkECYB0CkAHN0QA)

**Related Issues:** #36753, #12825

**Comment by IllusionMH** [comment]
As mentioned in linked #36753 (and many other) - it's design limitation.
Your `const f` need to have explicit type annotation to participate in CFA.
[`const f: () => never = ...`](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAZgLhgCgJQwLwD4ZgKYBueATpiutjAN4CwAUDIzFABbEgDuueXAose2Jp6AX3pxhdAPRSYEFiACuAGwAmMAEZ4YisMTwBDYCwMbl2jYtgBLCGADkUeqEghzAOmUgA5miA)
