### ISSUE TITLE
Project references with --build ignoring include/exclude paths.

### ISSUE THREAD

**Issue by codycuellar** [microsoft/TypeScript#37997]
**TypeScript Version:**  3.8.3

**Search Terms:**
build exclude include composite project references

**Code**

project tree:
```
root/
  tsconfig.json
  lib/
    foo/
      docs/
      src/
      tsconfig.build.json
```
tsconfig.json:
```json
{
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true,
        "target": "es2018",
        "module": "commonjs",
        "moduleResolution": "node",
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "strict": true,
        "noUnusedLocals": true,
        "declaration": true,
        "declarationMap": true,
        "sourceMap": true
    },
    "references": [
        { "path": "lib/foo/tsconfig.build.json" }
    ]
}
```

lib/foo/tsconfig.build.json
```json
{
    "extends": "../../tsconfig",
    "compilerOptions": {
        "composite": true,
        "outDir": "./dist/",
        "rootDir": "./src/",
        "checkJs": false,
    },
    "include": [
        "./src/**/*",
        "./types/**/*"
    ],
    "exclude": [
        "./docs/**/*"
    ]
}

```

```bash
tsc -b tsconfig.json
```

**Expected behavior:**
builds only files from src/ and types/ in lib/foo package.

**Actual behavior:**
builds everything that ends with .js or .ts in the entire lib/foo directory including files in docs/.

** NOTE: **
If I run tsconfig.build.json directly from inside the foo/ directory with:
```
tsc -p tsconfig.build.json
```
then everything works perfectly.

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/27069

**Comment by codycuellar** [comment]
I think I actually figured this out - it appears my base tsconfig not having a `files: []` entry was overriding the project config. I still feel that this is proper bug - if I provide ANY includes/files/excludes entries in a sub-project it should completely override the parent config it's inheriting from, otherwise you end up with some really weird overlaps. I suppose this is in the project references docs, but somewhat unclear since it's just in the 'guidance' section, therefor not a clear gotcha.

**Comment by RyanCavanaugh** [comment]
Not sure what to tell you; a tsconfig has an implicit `include` and it'd break tens of thousands of projects to change this.

**Comment by codycuellar** [comment]
Understandable, but just for clarity - what's happening with this particular config example is that the main tsconfig is implicitly including everything in the entire tree, clobbering any excludes of nested projects? My only suggestion is that the docs should make this a bit more clear on the project references page as a 'caveat' maybe? Being loosely described in the suggestions made it difficult to track down what was happening as my first instinct was that explicit excludes would be respected.
