### ISSUE TITLE
Generics: Type is not assignable

### ISSUE THREAD

**Issue by biqas** [Microsoft/TypeScript#3799]
Hi,

why is the online TypeScript compiler (http://www.typescriptlang.org/Playground) marking the line 225 as error. (Type is not assignable)

[Link to TypeScript editor with code]
(http://www.typescriptlang.org/Playground#src=interface%20IController%0D%0A%7B%0D%0A%20%20%20%20Parent%3A%20IController%3B%0D%0A%0D%0A%20%20%20%20HostView%3A%20IView%3B%0D%0A%0D%0A%20%20%20%20HostViewModel%3A%20IViewModel%3B%0D%0A%0D%0A%20%20%20%20Initialize(%24parent%3A%20IController)%3A%20void%3B%0D%0A%0D%0A%20%20%20%20Start()%20%3A%20void%3B%0D%0A%0D%0A%20%20%20%20Stop()%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IController%242%3CTHostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%0D%0A%7B%0D%0A%20%20%20%20HostView%3A%20THostView%3B%0D%0A%0D%0A%20%20%20%20HostViewModel%3A%20THostViewModel%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IController%243%3CTSelf%20extends%20IController%243%3Cany%2C%20any%2C%20any%3E%2C%20THostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%242%3CTHostView%2C%20THostViewModel%3E%0D%0A%7B%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20IContentController%20extends%20IController%0D%0A%7B%0D%0A%7D%0D%0A%0D%0Ainterface%20IContentController%242%3CTHostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%242%3CTHostView%2C%20THostViewModel%3E%2C%20IContentController%0D%0A%7B%0D%0A%20%20%20%20HostView%3A%20THostView%3B%0D%0A%0D%0A%20%20%20%20HostViewModel%3A%20THostViewModel%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IContentController%243%3CTSelf%20extends%20IContentController%243%3Cany%2C%20any%2C%20any%3E%2C%20THostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%243%3CTSelf%2C%20THostView%2C%20THostViewModel%3E%2C%20IContentController%242%3CTHostView%2C%20THostViewModel%3E%0D%0A%7B%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20IWindowController%20extends%20IController%0D%0A%7B%0D%0A%7D%0D%0A%0D%0Ainterface%20IWindowController%242%3CTHostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%242%3CTHostView%2C%20THostViewModel%3E%2C%20IWindowController%0D%0A%7B%0D%0A%20%20%20%20HostView%3A%20THostView%3B%0D%0A%0D%0A%20%20%20%20HostViewModel%3A%20THostViewModel%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IWindowController%243%3CTSelf%20extends%20IWindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20THostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%243%3CTSelf%2C%20THostView%2C%20THostViewModel%3E%2C%20IWindowController%242%3CTHostView%2C%20THostViewModel%3E%0D%0A%7B%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20IApplicationController%20extends%20IController%0D%0A%7B%0D%0A%7D%0D%0A%0D%0Ainterface%20IApplicationController%244%3CTSelf%20extends%20IApplicationController%244%3Cany%2C%20any%2C%20any%2C%20any%3E%2C%20TWindowController%20extends%20IWindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20TWindow%20extends%20IWindow%2C%20TWindowModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%2C%20IApplicationController%0D%0A%7B%0D%0A%20%20%20%20HostView%3A%20TWindow%3B%0D%0A%0D%0A%20%20%20%20HostViewModel%3A%20TWindowModel%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20IView%20%7B%20%7D%0D%0A%0D%0Ainterface%20IWindow%20extends%20Window%2C%20IView%20%7B%7D%0D%0A%0D%0Ainterface%20IViewModel%20%7B%20%7D%0D%0A%0D%0Ainterface%20IWindowModel%20extends%20IViewModel%20%7B%20%7D%0D%0A%0D%0Aclass%20Controller%20implements%20IController%0D%0A%7B%0D%0A%20%20%20%20protected%20IsInitialized%3A%20Boolean%3B%0D%0A%0D%0A%20%20%20%20private%20_Parent%3A%20IController%3B%0D%0A%0D%0A%20%20%20%20public%20get%20Parent()%3A%20IController%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this._Parent%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20protected%20_HostView%3A%20IView%3B%0D%0A%0D%0A%20%20%20%20public%20get%20HostView()%3A%20IView%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this._HostView%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20set%20HostView(%24value%3A%20IView)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this._HostView%20%3D%20%24value%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20protected%20_HostViewModel%3A%20IViewModel%3B%0D%0A%0D%0A%20%20%20%20public%20get%20HostViewModel()%3A%20IViewModel%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this._HostViewModel%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20set%20HostViewModel(%24value%3A%20IViewModel)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this._HostViewModel%20%3D%20%24value%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Initialize(%24parent%3A%20IController)%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.IsInitialized)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%20%20%20%20this.IsInitialized%20%3D%20true%3B%0D%0A%20%20%20%20%20%20%20%20this.Parent%20%3D%20%24parent%3B%0D%0A%20%20%20%20%20%20%20%20this.Init()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20protected%20Init()%3A%20void%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20protected%20Connect()%3A%20void%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20protected%20Disconnect()%3A%20void%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20public%20Start()%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this.Connect()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Stop()%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this.Disconnect()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Controller%242%3CTView%20extends%20IView%2C%20TViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20Controller%0D%0A%20%20%20%20implements%20IController%242%3CTView%2C%20TViewModel%3E%0D%0A%7B%0D%0A%20%20%20%20public%20get%20HostView()%3A%20TView%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%3CTView%3Ethis._HostView%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20set%20HostView(%24value%3A%20TView)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this._HostView%20%3D%20%24value%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20get%20HostViewModel()%3A%20TViewModel%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%3CTViewModel%3Ethis._HostViewModel%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20set%20HostViewModel(%24value%3A%20TViewModel)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this._HostViewModel%20%3D%20%24value%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20SetHostView(%24view%3A%20TView)%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this.HostView%20%3D%20%24view%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20SetHostViewModel(%24viewModel%3A%20TViewModel)%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this.HostViewModel%20%3D%20%24viewModel%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Controller%243%3CTSelf%20extends%20Controller%243%3Cany%2C%20any%2C%20any%3E%2C%20TView%20extends%20IView%2C%20TViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20Controller%242%3CTView%2C%20TViewModel%3E%0D%0A%20%20%20%20implements%20IController%243%3CTSelf%2C%20TView%2C%20TViewModel%3E%0D%0A%7B%0D%0A%20%20%20%20private%20_Self%3A%20TSelf%3B%0D%0A%0D%0A%20%20%20%20public%20constructor(protected%20%24self%3A%20TSelf)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20this._Self%20%3D%20%24self%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aclass%20ContentController%243%3CTSelf%20extends%20ContentController%243%3Cany%2C%20any%2C%20any%3E%2C%20TView%20extends%20IView%2C%20TViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20Controller%243%3CTSelf%2C%20TView%2C%20TViewModel%3E%0D%0A%7B%0D%0A%7D%0D%0A%0D%0A%0D%0Aclass%20WindowController%243%3CTSelf%20extends%20WindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20TWindow%20extends%20IWindow%2C%20TWindowModel%20extends%20IWindowModel%3E%0D%0A%20%20%20%20extends%20ContentController%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%0D%0A%20%20%20%20implements%20IWindowController%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%0D%0A%7B%0D%0A%7D%0D%0A%0D%0A%0D%0Aclass%20ApplicationController%3CTSelf%20extends%20ApplicationController%3Cany%2C%20any%2C%20any%2C%20any%3E%2C%20TWindowController%20extends%20IWindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20TWindow%20extends%20IWindow%2C%20TWindowModel%20extends%20IWindowModel%3E%0D%0A%20%20%20%20extends%20Controller%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%0D%0A%20%20%20%20implements%20IApplicationController%244%3CTSelf%2C%20TWindowController%2C%20TWindow%2C%20TWindowModel%3E%0D%0A%7B%0D%0A%20%20%20%20private%20_WindowController%3A%20TWindowController%3B%0D%0A%0D%0A%20%20%20%20public%20get%20WindowController()%3A%20TWindowController%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this._WindowController%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20constructor(%24windowController%3A%20TWindowController%2C%0D%0A%20%20%20%20%20%20%20%20%24window%3A%20TWindow%2C%20%24windowModel%3A%20TWindowModel)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20super(this)%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20this.WindowController%20%3D%20%24windowController%3B%0D%0A%20%20%20%20%20%20%20%20this.HostView%20%20%20%20%20%20%20%20%20%3D%20%24window%3B%0D%0A%20%20%20%20%20%20%20%20this.HostViewModel%20%20%20%20%3D%20%24windowModel%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Initialize()%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20super.Initialize(null)%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20if%20(this.IsInitialized)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20this.WindowController.Initialize(this)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Start()%20%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this.Initialize()%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20super.Start()%3B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20this.WindowController.Start()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0D%0Aclass%20AppController%20extends%20ApplicationController%3CAppController%2C%20CalculatorController%2C%20ICalculatorWindow%2C%20ICalculatorWindowModel%3E%0D%0A%7B%0D%0A%20%20%20%20public%20constructor()%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20super(new%20CalculatorController()%2C%20%3CIWindow%3Enull%2C%20%3CIWindowModel%3Enull)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20ICalculatorWindow%20extends%20IWindow%20%7B%20%7D%0D%0A%0D%0Ainterface%20ICalculatorWindowModel%20extends%20IWindowModel%20%7B%20%7D%0D%0A%0D%0Aclass%20CalculatorController%0D%0A%20%20%20%20extends%20WindowController%243%3CCalculatorController%2C%20ICalculatorWindow%2C%20ICalculatorWindowModel%3E%0D%0A%7B%20%7D)

And in line: 260 the error message is not really good.

**Comment by RyanCavanaugh** [comment]
Please simplify (i.e. remove unneeded lines of code) this repro to a reasonable size.

**Comment by biqas** [comment]
Simplified Version [Code](http://www.typescriptlang.org/Playground#src=interface%20IController%7B%7D%0D%0A%0D%0Ainterface%20IController%242%3CTHostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%7B%7D%0D%0A%0D%0Ainterface%20IController%243%3CTSelf%20extends%20IController%243%3Cany%2C%20any%2C%20any%3E%2C%20THostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%242%3CTHostView%2C%20THostViewModel%3E%7B%7D%0D%0A%0D%0Ainterface%20IContentController%20extends%20IController%7B%7D%0D%0A%0D%0Ainterface%20IContentController%242%3CTHostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%242%3CTHostView%2C%20THostViewModel%3E%2C%20IContentController%7B%7D%0D%0A%0D%0Ainterface%20IContentController%243%3CTSelf%20extends%20IContentController%243%3Cany%2C%20any%2C%20any%3E%2C%20THostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%243%3CTSelf%2C%20THostView%2C%20THostViewModel%3E%2C%20IContentController%242%3CTHostView%2C%20THostViewModel%3E%7B%7D%0D%0A%0D%0Ainterface%20IWindowController%20extends%20IController%7B%7D%0D%0A%0D%0Ainterface%20IWindowController%242%3CTHostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%242%3CTHostView%2C%20THostViewModel%3E%2C%20IWindowController%7B%7D%0D%0A%0D%0Ainterface%20IWindowController%243%3CTSelf%20extends%20IWindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20THostView%20extends%20IView%2C%20THostViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%243%3CTSelf%2C%20THostView%2C%20THostViewModel%3E%2C%20IWindowController%242%3CTHostView%2C%20THostViewModel%3E%7B%7D%0D%0A%0D%0Ainterface%20IApplicationController%20extends%20IController%7B%7D%0D%0A%0D%0Ainterface%20IApplicationController%244%3CTSelf%20extends%20IApplicationController%244%3Cany%2C%20any%2C%20any%2C%20any%3E%2C%20TWindowController%20extends%20IWindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20TWindow%20extends%20IWindow%2C%20TWindowModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20IController%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%2C%20IApplicationController%7B%20%7D%0D%0A%09%0D%0Ainterface%20IView%7B%7D%0D%0A%0D%0Ainterface%20IWindow%20extends%20Window%2C%20IView%7B%7D%0D%0A%0D%0Ainterface%20IViewModel%7B%7D%0D%0A%0D%0Ainterface%20IWindowModel%20extends%20IViewModel%7B%7D%0D%0A%0D%0Aclass%20Controller%20implements%20IController%7B%7D%0D%0A%0D%0Aclass%20Controller%242%3CTView%20extends%20IView%2C%20TViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20Controller%0D%0A%20%20%20%20implements%20IController%242%3CTView%2C%20TViewModel%3E%7B%7D%0D%0A%0D%0Aclass%20Controller%243%3CTSelf%20extends%20Controller%243%3Cany%2C%20any%2C%20any%3E%2C%20TView%20extends%20IView%2C%20TViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20Controller%242%3CTView%2C%20TViewModel%3E%0D%0A%20%20%20%20implements%20IController%243%3CTSelf%2C%20TView%2C%20TViewModel%3E%0D%0A%7B%0D%0A%20%20%20%20public%20constructor(protected%20%24self%3A%20TSelf)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aclass%20ContentController%243%3CTSelf%20extends%20ContentController%243%3Cany%2C%20any%2C%20any%3E%2C%20TView%20extends%20IView%2C%20TViewModel%20extends%20IViewModel%3E%0D%0A%20%20%20%20extends%20Controller%243%3CTSelf%2C%20TView%2C%20TViewModel%3E%7B%7D%0D%0A%0D%0A%0D%0Aclass%20WindowController%243%3CTSelf%20extends%20WindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20TWindow%20extends%20IWindow%2C%20TWindowModel%20extends%20IWindowModel%3E%0D%0A%20%20%20%20extends%20ContentController%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%0D%0A%20%20%20%20implements%20IWindowController%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%7B%7D%0D%0A%0D%0A%0D%0Aclass%20ApplicationController%3CTSelf%20extends%20ApplicationController%3Cany%2C%20any%2C%20any%2C%20any%3E%2C%20TWindowController%20extends%20IWindowController%243%3Cany%2C%20any%2C%20any%3E%2C%20TWindow%20extends%20IWindow%2C%20TWindowModel%20extends%20IWindowModel%3E%0D%0A%20%20%20%20extends%20Controller%243%3CTSelf%2C%20TWindow%2C%20TWindowModel%3E%0D%0A%20%20%20%20implements%20IApplicationController%244%3CTSelf%2C%20TWindowController%2C%20TWindow%2C%20TWindowModel%3E%0D%0A%7B%0D%0A%09public%20constructor(%24windowController%3A%20TWindowController%2C%0D%0A%20%20%20%20%20%20%20%20%24window%3A%20TWindow%2C%20%24windowModel%3A%20TWindowModel)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20super(this)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20AppController%20extends%20ApplicationController%3CAppController%2C%20CalculatorController%2C%20ICalculatorWindow%2C%20ICalculatorWindowModel%3E%0D%0A%7B%0D%0A%20%20%20%20public%20constructor()%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20super(new%20CalculatorController()%2C%20%3CIWindow%3Enull%2C%20%3CIWindowModel%3Enull)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20ICalculatorWindow%20extends%20IWindow%7B%7D%0D%0A%0D%0Ainterface%20ICalculatorWindowModel%20extends%20IWindowModel%7B%7D%0D%0A%0D%0Aclass%20CalculatorController%0D%0A%20%20%20%20extends%20WindowController%243%3CCalculatorController%2C%20ICalculatorWindow%2C%20ICalculatorWindowModel%3E%7B%7D)

Line: 71 & Line: 79.


It is also wired that generic types with different generic arguments can not have the same class or interface name.

**Comment by DanielRosenwasser** [comment]
While it's still hard to grok, I think your code can be simplified to the following:

```TypeScript
class A<T extends A<any>>{
    constructor(x: T) {
    	
    }
}

class B<T extends B<any>> extends A<T> {
    constructor() {
        super(this);
    }
}
```

If this is the case, your issue is that you can't assign a B<T> to parameter of *a specific type `T` that extends `B<any>`*. If `T` is a subtype of `B<any>`, it isn't sound to supply a `B<T>`.

However, you can instead extend an `A<B<T>>` because now the constructor of `A` expects a `B<T>`.

TL;DR: Fix the declaration of `AppliationController` to be the following:

```TypeScript
class ApplicationController<TSelf extends ApplicationController<any, any, any, any>, TWindowController extends IWindowController$3<any, any, any>, TWindow extends IWindow, TWindowModel extends IWindowModel>
    extends Controller$3<ApplicationController<TSelf, TWindowController, TWindow, TWindowModel>, TWindow, TWindowModel>
    implements IApplicationController$4<TSelf, TWindowController, TWindow, TWindowModel>
```

**Comment by biqas** [comment]
Hi,

thanks, undestood, I was only confused by the online TypeScript compiler and VS2015RC TypeScript compiler. The later did not showed any errors but the online one did.

And I found that I made there one mistake, the corrected simplified version below.
In this case B is an abstract construct so it should not be possible to create it without extending it.

```javascript
class A<T extends A<any>>{
    constructor($self: T) {
    }
}

class B<T extends B<any>> extends A<T> {
    constructor($self: T) {
        super($self);
    }
}
```

Is there something planed for "generic types with different generic arguments can not have the same class or interface name"?

**Comment by RyanCavanaugh** [comment]
> Is there something planed for "generic types with different generic arguments can not have the same class or interface name"?

Can you clarify what this would mean? It's already an error to declare two classes with the same name, and an error to declare two parts to an interface with different type parameters or type parameter names.

**Comment by DanielRosenwasser** [comment]
> In this case B is an abstract construct so it should not be possible to create it without extending it.

@aozgaa implemented abstract classes, and I believe they should be going out for 1.6.

**Comment by markknol** [comment]
Not sure if relevant, but I get this TS2322 error. 
My testcase looks like this ([Runnable code here](http://www.typescriptlang.org/Playground#src=class%20Component%20%7B%20%7D%0D%0A%0D%0Aclass%20Entity%0D%0A%7B%0D%0A%20%20%20%20private%20_components%3A%7B%5Bid%3Anumber%5D%3A%20Component%7D%20%3D%20%7B%7D%3B%0D%0A%09%0D%0A%20%20%20%20public%20getComponent%3CA%20extends%20Component%3E(id%3Anumber)%3AA%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%2F%2F%20error%3A%20TS2322%3A%20Type%20'Component'%20is%20not%20assignable%20to%20type%20'A'.%0D%0A%20%20%20%20%20%20%20return%20this._components%5Bid%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20e%20%3D%20new%20Entity()%3B%0D%0Aconsole.log(e.getComponent(2))%3B)):
```ts
class Component { }

class Entity
{
    private _components:{[id:number]: Component} = {};
	
    public getComponent<A extends Component>(id:number):A
    {
      // error: TS2322: Type 'Component' is not assignable to type 'A'.
       return this._components[id];
    }
}
```
Is this also intended behavior?

**Comment by DanielRosenwasser** [comment]
@markknol That's by design - `A` refers to a *specific subtype* of `Component`, so you can't just give a `Component`. Either make your class generic on `A` and have the indexer of `_components` return `A`s, or make `getComponent` non-generic and return a `Component`. You probably want to do the latter.
