### ISSUE TITLE
Unique symbol can't be used to index class

### ISSUE THREAD

**Issue by ilogico** [microsoft/TypeScript#38009]
**TypeScript Version:**  3.8.3 and next (3.7.x works as expected)

**Search Terms:** unique symbol class expression

**Code**

```ts
// tsc --target esnext --strict
const s = Symbol();

class A {
    [s]: number;
    constructor() {
        this[s] = 42;
    }
}

const B = class {
    [s]: number;
    constructor() {
        this[s] = 42;
    }
}

const C = true && class {
    [s]: number;
    constructor() {
        this[s] = 42;
    }
}
```

**Expected behavior:**
No errors
**Actual behavior:**
error TS7053: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'B'.
  Property '[s]' does not exist on type 'B'.

13         this[s] = 42;
**[Playground Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200415&ssl=22&ssc=2&pln=1&pc=1#code/MYewdgzgLgBBMF4YGUCeBbARiANgCgEoBuAWAChzgcBDCeAQRgG9yY2YBtCAXQC4YwAVywBTAE6ky7GKEhQxg4FBBjCzVtPZQAFgEsIXbohgAWAEyTpAX3I2KZWdBgAhY1VrwWU9of5DREhpsjvKKyqoE6t6aMDr6hsbmlux2dpTgTgDCxqEiMABk+TI0dFHSvgLCmOLJwRmhSipqXjFscQY8iRZBMKlAA)**

**Related Issues:** Did not find any

Only the `B` example doesn't work. It doesn't matter if the class is named or not. Returning the class from a IIFE also works without errors.

**Comment by kiroushi** [comment]
Managed to reproduce this issue while implementing a singleton pattern.

**Comment by a-tarasyuk** [comment]
It seems the issue, not in `unique symbol`

```ts
const key = 'key';
const Foo = class {
    [key]: number;
    constructor() {
        this[key] = 1;
    }
}
```
[Playground](https://www.typescriptlang.org/play/?ssl=8&ssc=2&pln=1&pc=1#code/MYewdgzgLgBA1gUwJ4wLwwOSKRg3AKH1ElgDEQQ0ZgAbAQwghgG98Z2YBtbAXQC4YYAK4BbAEYIATgQ7Vw0SUOBQQkgBQBKFm1kcoACwCWEbsh5UALACYZHAL747QA)

```ts
const key = 1';
const Foo = class {
    [key]: number;
    constructor() {
        this[key] =1;
    }
}
```
[Playground](https://www.typescriptlang.org/play/#code/MYewdgzgLgBA1gUwJ4wLwwIwG4BQPSSwBiIIaMwANgIYQQwDeOMLMA2okgLoBcMYAVwC2AIwQAnXKwrho4gcCghxACgCUjZtNZQAFgEsIHZF3IYADOamsAvjhtA)

**Comment by RyanCavanaugh** [comment]
This is fixed now
