### ISSUE TITLE
enum exported from external module ("declare module" + "export enum") doesn't generate any javascript

### ISSUE THREAD

**Issue by atsu85** [Microsoft/TypeScript#3800]
Hi,
I'm having problems with enums defined inside external module (i'm compiling to amd module format).
When using internal module format
``` TypeScript
module someModule {
    export enum Color {Red, Green, Blue};
}
```
then resulting JS contains enum and constants as expected (see http://www.typescriptlang.org/Playground#src=module%20someModule%20{%0A%20%20%20%20export%20enum%20Color%20{Red%2C%20Green%2C%20Blue}%3B%0A}%0A ).

But when using following syntax:
``` TypeScript
declare module 'someModule' {
    export enum Color {Red, Green, Blue}
}
```
then resulting JS file is empty (see http://www.typescriptlang.org/Playground#src=declare%20module%20someModule%20{%0A%20%20%20%20export%20enum%20Color%20{Red%2C%20Green%2C%20Blue}%0A}%0A )

Is this a bug or am i doing smth wrong? I don't see any compiler errors so I'd guess that this could be a bug.

I'm using TypeScript 1.5 beta with amd module format.

**Comment by RyanCavanaugh** [comment]
`declare` creates an "ambient" module -- it's for describing an existing object that isn't part of your compilation. For example, in `node.d.ts` we have `declare module "fs" {` to define the shape of the module `fs`.

If you want to have an external module with that content, make a file `someModule.ts` with the top-level declaration `export enum Color { /*...*/ }`

**Comment by atsu85** [comment]
Hi,
Thanks for the response. I came out with the same solution later yesterday, but i wanted it to be confirmed that i understood it right. 

Thanks again for the explaination.
