### ISSUE TITLE
Example on the correct way to use typescript in NON SPA application

### ISSUE THREAD

**Issue by valeriob** [microsoft/TypeScript#38003]
Hi,
we develop a lot of web application, we start with server side rendering (aspnet core) and on each page that need some enhancement we add some Typescript with  various npm libraries (vuejs and so on). 
Until now i've always being using typescript with namespaces, so each page like Index.cshtml, has his companion Index.ts, and references as script the compiled index.js.

I would like to use modules instead of namespaces, what would it be the correct way to configure typescript compiler and keep my lightweight workflow ?
I've instructed tsconfig.json to use ES6 module system, and i had to specify "moduleResolution" :"node".
So now when it loads the module, the browser fails with this error : 

> Uncaught TypeError: Failed to resolve module specifier "rxjs". Relative references must start with either "/", "./", or "../".

Here is the example, it should print in the console the numbers from 1 to 100 : 
[WebApplication17.zip](https://github.com/microsoft/TypeScript/files/4486312/WebApplication17.zip)

Thanks
Valerio

**Comment by WhileTrueEndWhile** [comment]
Maybe related: #16577
It seems to be necessary to provide a file path instead of a module name in import statements.
RXJS provides bundles and also loose files also missing extensions in import statements.
So you could add JS extensions for your own code and also for RXJS which means that you will need a script for RXJS as mentioned in the linked issue. It should be possible to include the RXJS bundle in index.html an then declare RXJS as given in typescript which means that you don't need a script if you add the JS extensions of your own code manually.
I hope the text was understandable :)

**Comment by valeriob** [comment]
Hi @WhileTrueEndWhile  thanks for the tip but i'm not expert enough in the js ecosistem to understand your solution. I'm not sure if you are saying that there is a problem with the rxjs package or typescript.
I would like not to use the bundle, because i'm already using it without the module system (using namespaces), so i would have no benefit using an hybrid system.
Here is another example using babylonjs or moment, having the same problem.
[WebApplication17.zip](https://github.com/microsoft/TypeScript/files/4486949/WebApplication17.zip)

Thanks
Valerio

**Comment by WhileTrueEndWhile** [comment]
Ok, I try to explain it by example:

__Bundle Solution__

- Import dependency in `index.html` file:
```html
<html>
    <head>
        <script src="my_dep.js"></script>
    </head>
</html>
```
Note: we expect an UMD bundle or just "raw" JS

- Declare existence in a `.d.ts` file:
```typescript
declare MyDep: any;
```
Note: `any` should be replaced with an actual type

Now we should be able to access `MyDep` in any TS file.

__Loose File Solution__

- Import TS modules via file path:

```typescript
import {MyDep} from './my_dep.js'
```
Note: It is not officially recommenced to do this directly in source code, but it could be automated by https://github.com/microsoft/TypeScript/issues/16577#issuecomment-310426634

Just my 2ct^^

**Comment by WhileTrueEndWhile** [comment]
I hope nobody here is complaining because that's a question ;-) Since I haven't run the code yet: Can you briefly describe how to start the project (e.g some commands) so that I can better understand the error?

**Comment by valeriob** [comment]
> I hope nobody here is complaining because that's a question ;-) 

I appriciate the effort ! What surprises me is that looks like everybody is talking about SPA and single compiled boundle, I can't find any documentation on simple use cases of build a simple server side rendered application plus some scripts per page :D

>Since I haven't run the code yet: Can you briefly describe how to start the project (e.g some commands) so that I can better understand the error?
Sure !
- Install dotnet core runtime (3.1) https://dotnet.microsoft.com/download 
- go to the webapp folder and run dotnet run
- open http://localhost:5000

![image](https://user-images.githubusercontent.com/1522516/79571392-67fb8d00-80bb-11ea-983d-26b468a92ce2.png)

**Comment by WhileTrueEndWhile** [comment]
Ok, I run the code. It was pretty easy. Just download `dotnet` and `export "PATH=$PWD:$PATH"`... 

The first question is: **How to hook into the build process?**

To implement one of the mentioned "Solutions" it is required to extend the build process. I don't know when `tsc` is called. We need another script, that is executed after `tsc` (for the "Bundle Solution") or that is executed before `tsc` (for the "Loose File Solution").

I am not experienced with modern ASP/DOTNET apps, even if I had some experience with VB.NET/C# in earlier days. So, I can not provide any instructions to fix that properly. But if there is "no way", some "top level scripts" invoking dotnet (and replacing direct dotnet calls) should be sufficent.

I think It would be a success, if we a are able to add the `rxjs` bundle to `index.html` and automate copying the bundle to a distribution folder (to follow the "Bundle Solution"). Then we need a [`d.ts`](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) file which tells typescirpt, that `rxjs` is already included by something like this: `declare const rxjs: RXJSTYPE;`. As you already mentioned, there seems to be no type for the hole RXJS...
But I was able to load the bundle, which gives us the following object at runtime:
![rxjs](https://user-images.githubusercontent.com/33146321/79745371-6ffc3c80-8308-11ea-9093-88a7b3f27775.png)

So, If there is a type for the hole `rxjs`, we have to prefix each `rxjs` export with `rxjs` which breaks portability maybe. This is the deal. But I works great for e.g. jquery :D

To implement the "Loose File Solution" we need to run [a script](https://github.com/microsoft/TypeScript/issues/16577#issuecomment-310426634) before `tsc` (yes, we known that already).

Another option is to use `requirejs`. The [`monaco`](https://microsoft.github.io/monaco-editor/) project is written in typescript ans also uses `requirejs` to load modules at runtime or, if we want to do so, to bundle modules at buildtime.

**Comment by valeriob** [comment]
First of all, thank you for your time and effort !

For the bundles solution i'm on that page too. From what i understand  the problem is that rxjs do not expose types as namespaces for the umd build :( 

For the Loose File solution i would like to work with ES6 modules, and i do not really understand why i do need that script, and what problem does it solve.
I mean, i can write ".js" by myself if it would work, but typescript compiler complanins if i type : 

`import { range } from "rxjs.js";`

I created a repository here with the example so you can publish something if you want https://github.com/valeriob/Typescript_Non_SPA 
I also automated the tsc invocation in the build command.

Thanks
Valerio

**Comment by WhileTrueEndWhile** [comment]
My personal agenda is to build Angular in such a way that Angular is bundled and the individual components are pretty-printed JS. Of course RXJS has to be included as well.
I was involved in version 2 from the beginning and still have code lying around where `ngc` is called directly, so no high level CLI is used. But Rollup is still used as a bundler. I still have to change that.
I don't know when I have time for that, so please be patient.
I wish you a blessed time.

**Comment by valeriob** [comment]
Thanks ! do not worry ! I really hope someone else is using typescript to build non SPA application :D
