### ISSUE TITLE
tsconfig - validate and warn about unknown/unexpected properties 

### ISSUE THREAD

**Issue by levenleven** [microsoft/TypeScript#38006]
## Search Terms

tsconfig validate 

## Suggestion

Currently tsc validates and warns about invalid properties in `compilerOptions` section which is great!. It would be really helpful if it would do the same for the root of the config file.

## Use Cases

Easily identify mistakes/typos in configuration.

## Examples

Sometimes people put complier option in the root by mistake, then scratching the head for hours trying to understand what is wrong.  

In example below path mapping obviously won't work:

```json
{
  "compilerOptions": {
    ...
  },
  "paths": {
    "@module": [
      "./src/utils/module"
    ]
  },
  "include": [
    ...
  ]
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
The top level is intentionally kept "open" so that other tools wanting to interop with TS projects can store configuration data there.

**Comment by levenleven** [comment]
Maybe there could be "check for unknown config props" mode or something like that.. Anyway thanks for explanation @RyanCavanaugh

**Comment by botic** [comment]
@RyanCavanaugh Maybe a warning if e.g. `outDir` is specified in the root of tsconfig instead of `compilerOptions`? Just took me 20 minutes to find my typo:

```
{
    "extends": "@tsconfig/node16/tsconfig.json",
    "include": [
        "src/*" ,"src/**/*"
    ],
    "outDir": "dist"
}
```

For beginners it might not be obvious that `include` and `outDir` are not on the same level.

**Comment by RyanCavanaugh** [comment]
@botic see https://github.com/microsoft/TypeScript/pull/44964
