### ISSUE TITLE
Invalid left handed error

### ISSUE THREAD

**Issue by sebdoucet** [microsoft/TypeScript#38010]
**TypeScript Version:**  first seen on 3..8.3 to typescript@next

**Search Terms:**

**Code**
```typescript
methodRoot(mode: number): void{
    delete this._lastError; // Works when this line is commented

    mode === 1 ? this.runStuff1() : this.runStuff2();

    if (this._lastError instanceof MyClassError) {
        throw this._lastError;
    }
}
```

**Expected behavior:**
Valid sentence

**Actual behavior:**
Error on `this._lastError` inside the if instruction: The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/FAYwNghgzlAECyBPAwpGBRATpg9p2ApgB4AuBAdgCZxa74DewwAvk+NHEqh7I7P7AAOmAJYA3CGVgB9NCVp4A-AC5YCzAG4mA2AFsCJABY5KAJRw4SACl0mCq8gFddAIwKYAlKrE4RlPjoClARgBgSwRiJQAHSy0PLYeBqwAPQpsADqeADWcADuhhQRhlGwYCLk4aUgOLr65GSU2oH8tsGwALxdsACMsIrFUdGYjuQAyiSOAGZTPVYesKqRMSPjkzMATPNawC38IlOwVsuxcuqwFVAkEOQgBDiHXGhQ6gsBewJGuHmDMXFX6i0H1YOlYuwEqwm01m828vn84JaJEwiF4iI+qXSUJmsAggkEFCawPROhAkhAhiO7k8aIxnxKfzOiXwHUI2CBexBAjBOkh6ymWy8sB8fnegWRqLFHzSsGxhzxBKoJO5yv4ZJIFKp2DeqvFDNO8XOrOpHJaXP4rGYQA

**Comment by RyanCavanaugh** [comment]
See #9998

**Comment by sebdoucet** [comment]
How its dupplicate?!

Why even that does not work:
`if (this._lastError && this._lastError instanceof MyClassError) `

this._lastError can't be undefined... I valid it. And the instanceof does the same.

The link doesn't help and have no meaning on the matter.

**Comment by RyanCavanaugh** [comment]
> How its dupplicate?!

The linked bug concerns the question: Should TypeScript assume that functions have side effects over any possibly-affected property? Both answers result in unpleasant outcomes in certain situations.

> And whatever the result, valid and safe JS have to work with typescript or this is not a superset.

See https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean . I'd encourage you to use JavaScript instead of TypeScript if you don't want type errors.

**Comment by sebdoucet** [comment]
The question is ask in favor of Typescript...

Should Typescript for infering and override any proper validation... Why Typescript infer "never" when this is a "Variable" and by definition vary.

Even in languages like C# this does not exists !! Why changing the type of my class member... This make no cense!!

I can understand changing the type of a scoped variable.... but when typescript can't ensure its changes, why does it assume the life of a member as stop and the state will never change.

Dont try to make cense of this case.

**Comment by sebdoucet** [comment]
And whatever your answer, why this work when I do that in an other method... Maybe you can be consistant and fix that.

**Comment by sebdoucet** [comment]
> I'd encourage you to use JavaScript instead of TypeScript if you don't want type errors.
This is the kind inappropriate comment that make people avoid reporting issues... This is my case from now.

I'm a Typescript veteran that have multiple repositories of thousand LOC in a big tech compagny and I follow every new feature of the language.

Your linked article is off topic in case of class member and you didn't even consider a second my request.
