### ISSUE TITLE
.json inputs not allowed outside of rootDir

### ISSUE THREAD

**Issue by duarten** [microsoft/TypeScript#38015]
**TypeScript Version:**  Version 3.8.3

**Search Terms:** json rootDir 

**Code**

Folder structure:
```
src/test.ts
src/tsconfig.json
data/dummy.json
```

tsconfig:
```json
{
    "compilerOptions": {
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "rootDirs": [
            ".",
            "../data"
        ]
    }
}
```

test.ts:
```ts
import dummy from "./dummy.json"

console.log(dummy)
```

**Expected behavior:**

JSON printed to stdout.

**Actual behavior:**

The error: `src/test.ts:1:19 - error TS6059: File 'repro/data/dummy.json' is not under 'rootDir' 'repro/src'. 'rootDir' is expected to contain all source files.`

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
This does not repro and does not repro error with latest from master
```
c:\temp\test>node c:\TypeScript\built\local\tsc.js --listFiles --p src
c:/TypeScript/built/local/lib.d.ts
c:/TypeScript/built/local/lib.es5.d.ts
c:/TypeScript/built/local/lib.dom.d.ts
c:/TypeScript/built/local/lib.webworker.importscripts.d.ts
c:/TypeScript/built/local/lib.scripthost.d.ts
c:/temp/test/data/dummy.json
c:/temp/test/src/test.ts
```

**Comment by duarten** [comment]
Specifying `rootDir` is an integral part of this issue. The command to run is `tsc --project src/tsconfig.json --outDir lib/ --rootDir src`. That will reproduce it:

```
tsc --project src/tsconfig.json --outDir lib/ --rootDir src
src/test.ts:1:19 - error TS6059: File '/Users/duarten/code/ts-issue/data/dummy.json' is not under 'rootDir' '/Users/duarten/code/ts-issue/src'. 'rootDir' is expected to contain all source files.

1 import dummy from "./dummy.json"
                    ~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by sheetalkamat** [comment]
The issue is not `rootDir` but `outDir` when you specify `outDir` you are saying all the files in the program need to go into the `outDir` folder and the common source directory for all the files is `rootDir`. Clearly `dummy.json` is not in it hence the error. This is intended behavior

```
c:\temp\test>node c:\TypeScript\built\local\tsc.js  -p src  --rootDir src

c:\temp\test>node c:\TypeScript\built\local\tsc.js  -p src  --rootDir src --outDir lib
src/test.ts:1:19 - error TS6059: File 'c:/temp/test/data/dummy.json' is not under 'rootDir' 'c:/temp/test/src'. 'rootDir' is expected to contain all source files.

1 import dummy from "./dummy.json"
                    ~~~~~~~~~~~~~~

```

**Comment by duarten** [comment]
Why does TypeScript need to put the JSON files in the `outDir`? Couldn't it treat them like `d.ts` files, which _can_ be outside of the `rootDir`?

**Comment by sheetalkamat** [comment]
.json files are like .js files and will be emitted .. only special casing is they are emitted if the emit would overwrite them

**Comment by duarten** [comment]
I see, thanks! Although I find it weird that json files are treated differently than, say, css files.
