### ISSUE TITLE
Error when accessing to optional argument of overloaded function inside correct type guard

### ISSUE THREAD

**Issue by jareguo** [microsoft/TypeScript#38022]
**TypeScript Version:**  3.8.3

**Search Terms:** type guard function optional overload

**Code**

```ts
class MyClass {
    foo () {}
}

function add (test: number): void;
function add (test: object, paramIfObject: MyClass): void;  // should overload this declaration
function add (test: number | object, paramIfObject?: MyClass): void {
    if (typeof test === 'object') {  // Indicated the argument to overload is not optional
        paramIfObject.foo();   // Error: Object is possibly 'undefined'.(2532)
    }
}
```

**Expected behavior:** Compile successfully

**Actual behavior:** Error: Object is possibly 'undefined'.(2532)

**Description:** The variable `paramIfObject` was used inside the if statement, which should be a type guard refering to the correct function overload. So the variable should not compiled as an optional argument. Just equals to this: (no error)

![image](https://user-images.githubusercontent.com/1503156/79572516-aa3ec180-80ef-11ea-8605-c3f0fc9c1939.png)

**Playground Link:**  [Playground Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=12&pc=1#code/MYGwhgzhAECyCeBhcVoG8BQ1vQGYHt9oAKASnQF8MqNcBXAO2ABcBLfB6MAE25OYCmEZgC5oDOgFsARgIBOpMQDd8rbgG5ajFu048+xQcLH5pAKwEsANNAAOYOWEkBJXAHlzl0XCQoIi6BU1TXomNg4uXn4hbwkZeWgAH2hTC2s7BydXDzTmAH4xBGRIf2VVPkwcaFZcfnhbAXxao2ZoAF4O6AByVK8u8kqqnHtHF3dPFgA6AnwyTSqqKiA)

**Related Issues:** 

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```
</details>

**Comment by RyanCavanaugh** [comment]
See #14515

**Comment by jareguo** [comment]
Thanks
