### ISSUE TITLE
Index Signature could be improved (for ... in, if ... in operators)

### ISSUE THREAD

**Issue by alessiocancian** [microsoft/TypeScript#38021]
I've read the FAQs but I didn't find anything similar to what I'm requesting...

When trying to access an object property using a string as index we get the error
> Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'MyType'

But...
- Checking if the key is a property of the object with `if(key in obj)` should be enough to use it as index but eslint and tsc give me an error about missing index signature.

- Iterating the keys with a `for(let key in obj)` loop should make sure that key is a key of obj but even in this case I can't use it as an index without an index signature. The problem here is that the type of `key` is inferred as `string` and not as `keyof MyType` that would be better.

So my opinion is that the following code should be allowed (even with noImplicitAny=true):
```
type MyType = {
  name: string
  id: number
}

const foo = (key: string, item: MyType) => {
  if(key in item) {
    console.log(item[key])
  }
  for(let k in item) {
    console.log(item[k])
  }
}
```

**Comment by MartinJohns** [comment]
Duplicate of #35847.

**Comment by alessiocancian** [comment]
> Duplicate of #35847.
Ok so the `for in` "works as intended" but what about `if(key in obj)` ?

**Comment by RyanCavanaugh** [comment]
#21732

**Comment by RyanCavanaugh** [comment]
I'm not sure that anything correct would be useful to you. For some `s`, even if `s in obj`, `obj[s]` is necessarily of type `unknown`. Inferring `keyof MyType` would be wrong; see https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript

**Comment by alessiocancian** [comment]
Ok, I get the point, I thought the error was that I can't use the property as index for that object but the real problem is that the type cannot be inferred, so it is considered an "implicit any" (in fact it isn't an error with noImplicitAny option set to false).

Thanks for the answer, I'm closing the issue cause everything works fine! 👍
