### ISSUE TITLE
Quick fix to 'declare function' from call site

### ISSUE THREAD

**Issue by markusjohnsson** [microsoft/TypeScript#38025]
## Search Terms

declare function quick fix

## Suggestion

Provide a quick fix for calls to unknown functions to declare a function of that name in current or module scope. Similar to the "declare method" quick fix for methods in classes.

## Use Cases

Write code that consumes a function before writing it to let you figure out the order of arguments etc. Function parameter types and names should be inferred from arguments given at call site, just like "declare method". 

## Examples

```ts
declare x: boolean;
declare y: string;
foo(x, y, 123); // Cannot find name 'foo'
```
Cursor at squiggly -> Quick fix "Declare function in module scope" ->

```ts
declare x: boolean;
declare y: string;
foo(x, y, 123);

function foo(x: boolean, y: string, arg3: number) {
}
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Should this feature be created as a new QF service or added to some of the existing ones?

**Comment by RyanCavanaugh** [comment]
@a-tarasyuk please don't implement features in the Awaiting More Feedback state - we can only take PRs for things assigned to the Backlog or a named release milestone

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh I think this issue related to https://github.com/microsoft/TypeScript/issues/26217 which is located in the `Backlog` milestone. However, don't worry I won't work on it. :hand::point_up:

**Comment by markusjohnsson** [comment]
@a-tarasyuk yes, I think that issue covers this.

**Comment by markusjohnsson** [comment]
Closing in favor of #26217
