### ISSUE TITLE
Inference for contravariant positions in second argument of conditional type results in arbitrary union supertype

### ISSUE THREAD

**Issue by polkovnikov-ph** [microsoft/TypeScript#38039]
**TypeScript Version:**  3.8.3 (Nightly is broken at the moment)

**Search Terms:**
distributive conditional types over intersection

**Code**

```ts
type X = (
    ((x: { a: 1 }) => 0) & ((x: { b: 2 }) => 0)
) extends (a: infer T) => any ? T : never;
type Y = (
    ((x: { b: 2 }) => 0) & ((x: { a: 1 }) => 0)
) extends (a: infer T) => any ? T : never;
type XY = X extends Y ? Y extends X ? true : false : false;

type A = (
    ((x: { a: 1 }) => 0) | ((x: { b: 2 }) => 0)
) extends (a: infer T) => any ? T : never; 
type B = (
    ((x: { b: 2 }) => 0) | ((x: { a: 1 }) => 0)
) extends (a: infer T) => any ? T : never;
type AB = A extends B ? B extends A ? true : false : false;
```

**Expected behavior:**
`XY` and `AB` both `true`, i.e. condition types distribute over intersections the same way as over unions.

**Actual behavior:**
`XY` is `false`. Type checker picks the last term of intersection.

**Playground Link:**
[Playground Link.](https://www.typescriptlang.org/play/#code/C4TwDgpgBAGlC8UAUBYAUFTykA8BcUA3lAIYECMUAvgJQIB8UADHQGTb5FQBGBATNTrxGLdHQg5gEAHYATAM7IyUAJbSAZhABOUACpDGJaSCgB+PVALSIAN20BudKEhQAmgmTosHAsV5QBWgZmNh8uZUog4RCxKAkpOUUkZTVNHX1goxNzXUsoazstRzRnaBh3RDh4mQU3MzrqxNh64C0AV2gCdRIAG3lOqG6+iGKncGgAQQ9UDCwkXF9SCkFgligAHzC-fhXo0TRxSRqklI1tPQNSY3rcq1sHKDGXACFprzmFrn9Ay7XN+c4xAiuxENFijVqyQIqXOGWiWRueQKDiek1eiCmEMUr3MryxUCm5laHTyQ36pN6-XsQA)

**Related Issues:** 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types

**Comment by jack-williams** [comment]
Intersections of functions behave like overloaded functions, and the behaviour for a conditional type inferring from an overloaded function is to use the last signature as described in #21496

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types (this would require us to support typeof for arbitrary expressions, as suggested in #6606, or something similar).

**Comment by polkovnikov-ph** [comment]
Yes, I remember that back from the time conditional types were added, but it never made sense to me.

Intersection of functions has to conform to types of all functions at the same time, i.e. call site has to pass arguments in a way that types of formal arguments check against _every_ signature, while for an overloaded function it's enough to check against _any_ signature.

Overloaded functions need to be treated either as separate kind of entity or as unions, and surely not as intersections.

**Comment by polkovnikov-ph** [comment]
I would expect that if I used conditional on an intersection
```
type F = ((a: 1) => 0) & ((a: 2, b: 3) => 0) & ((a: 4, b?: 5, c?: 6) => 0)
```
types of arguments would be inferred either as
```
1 | 2 | 4
3 | 5 | undefined
6 | undefined
unknown
```
or
```
1 | 2 | 4
3 | 5
6
unknown
```
or
```
1 | 2 | 4
unknown
unknown
unknown
```
but surely not
```
4 | undefined
5 | undefined
6 | undefined
unknown
```
that we're getting right now.

**Comment by RyanCavanaugh** [comment]
Re: the title, it would be plainly wrong to do this
```ts
type Pt = { x: number } & { y: number }
type IsPoint<T> = T extends { x: number, y: number } ? true : false;
// Expected true, not false & false
type X = IsPoint<Pt>;
```

**Comment by polkovnikov-ph** [comment]
I'm not sure how to properly call it otherwise. The "distributive conditional types" term doesn't really cover that distributivity through contravariant positions converts unions to intersections (and in case of this issue, vice versa).

The example you've shown doesn't show distribution through contravariant positions.
