### ISSUE TITLE
No contextual typing for interfaces that extends interface with index signature

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3804]
I was hoping this could work:
```typescript
class A {
	public a: string;
}

interface B {
	[index: string]: A;
}

interface C extends B {
	a;
	b;
	c;
}

let c: C;
c.a.a // c.a of type A
```
but members of interface C has type `any` instead I was hoping I could get type `A`?

Notice I don't want to define directly:
```typescript
let c: B;
```
because I need to pass C as a type with defined props.

**Comment by RyanCavanaugh** [comment]
Contextual typing applies to expressions, not declarations, so that part isn't exactly relevant.

It's legal to declare members of type `any` (which is what you've done) even when you have an index signature. I don't think we would take a breaking change here.

**Comment by tinganho** [comment]
This is my problem right now:

```typescript
interface StyleRules extends Radium.StyleRules {
    feed: Radium.CSSStyleDeclaration;
    feedTitle: Radium.CSSStyleDeclaration;
    feedLoadMoreButton: Radium.CSSStyleDeclaration;
.   ...
}
```
Having to repeat a type that I think could be inferred from a base interface. If not inferred maybe be able to reference the base signature value type?

**Comment by RyanCavanaugh** [comment]
#1373 ?

**Comment by tinganho** [comment]
Yes sort of related. Though this suggestion is an interface derived from an
interface/class. His suggestion where a class derived from a
interface/class.

tis 14 juli 2015 kl 00:45 skrev Ryan Cavanaugh <notifications@github.com>:
