### ISSUE TITLE
Union of subtypes should be usable as the supertype

### ISSUE THREAD

**Issue by wojpawlik** [microsoft/TypeScript#38048]
**TypeScript Version:** 3.8.3 and v3.9.0-dev.20200418 

**Search Terms:**
common type subtype union 

**Code**

```ts
interface Cata<OkIn, OkOut, ErrIn, ErrOut> {
    Ok(value: OkIn): OkOut
    Err(err: ErrIn): ErrOut
}

type CataOk<OkIn, OkOut> = Cata<OkIn, OkOut, never, unknown>
type CataErr<ErrIn, ErrOut> = Cata<never, unknown, ErrIn, ErrOut>

interface BaseResult<T, E> {
    readonly ok: boolean
    cata<OkOut, ErrOut>(cata: Cata<T, OkOut, E, ErrOut>): OkOut | ErrOut
}
export class Ok<T> implements BaseResult<T, never> {
    readonly ok = true as const
    constructor(readonly value: T) {}
    cata<OkOut>(cata: CataOk<T, OkOut>) {
        return cata.Ok(this.value)
    }
}
export class Err<E> implements BaseResult<never, E> {
    readonly ok = false as const
    constructor(readonly error: E) {}
    cata<ErrOut>(cata: CataErr<E, ErrOut>) {
        return cata.Err(this.error)
    }
}

export type Result<T, E> = Ok<T> | Err<E>

// tests

declare const u: Result<number, Error>

u.cata({
    Ok(v) { return '2' },
    Err() { return 3 },
})
```

**Expected behavior:**

No error ([Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle)).

**Actual behavior:**

> This expression is not callable.
  Each member of the union type `(<OkOut>(cata: CataOk<number, OkOut>) => OkOut) | (<ErrOut>(cata: CataErr<Error, ErrOut>) => ErrOut)` has signatures, but none of those signatures are compatible with each other. ts(2349)

**Workaround:**

```ts
export type Result<T, E> = BaseResult<T, E> & (Ok<T> | Err<E>)
```

[**Playground Link**](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJzHAPAeQNYCSIANMvjgK5ikCiUURt9lYAfMgN4BQyvZeACgBucADYUIALn5EAlNPJUefOlAHQo01XK3MlAXy5cwATwAOKdJny5CJfi3YBeNBmz5GDqqRAQh0UgoQPBAAewB3EFZjc0s3VSxte1VHZBcrbF9-KEDgsMimBmS9NiNQSFhEFAAhOABnCAAlCDqKUTAsABVadm4+ZCgIOAATUJBRE2RQvGkAI1DQ0SGQZV4EN1sWQscBdcxpDK7SRWpkGm2qVnkvMGQAHzOSrkMIAA8zUKhbhFF6uv4uuxgABbMxLYEQcD-WoNZqtdpHZBZaC9VYDIajcaTaZpZBgKASZD1ZAIMZ1MBo0kgckEhBgT4CQYjMYTZAicRSZCdWScQz9PbuPA7AUHNw2bo3K6cNH9QZgChQEAktwAOnwAjAAAtgHUVeyJLI0YYXu9Pt9fnV-gkaEDQeDIWBofUmi02h1kTkzqjZRiWdi8Lj4KIGkT-lTyZSyfiKHSGUzMayNJ8tDyOHy+ALEiVWLs3KLMNaLmxUzK+HKFUqBSrVBrtbqk1BDf1jUY3h8vnjYsg4W7ETbceL2A9rdEuAB6Md4lqOozDCA-OCDElR5AUaQ9hEgCjA2YBR5QT6jigqgUCPp8dVCVPo+WK5AAcgATPfkPpiGia9fy3eAMyv9-6IaXDhrcszSDCLrwu6267p6qiHriFBGLMJ5uGeaKXl+EC3kqT4vm+H70AIWE4cgf4EYBQA)

**Related Issues:** #37704.

**Comment by trgwii** [comment]
```ts
type AnyFn = (...args: any[]) => any;

interface Cata<Ok extends AnyFn, Err extends AnyFn> {
	Ok: Ok,
	Err: Err
}

class Ok<Value> {
	constructor(private value: Value) {}
	cata<
		Ok extends (value: Value) => any,
		Err extends AnyFn
	>(x: Cata<Ok, Err>): ReturnType<Ok> {
		return x.Ok(this.value);
	}
}

class Err<Error> {
	constructor(private error: Error) {}
	cata<
		Ok extends AnyFn,
		Err extends (error: Error) => any
	>(x: Cata<Ok, Err>): ReturnType<Err> {
		return x.Err(this.error);
	}
}

export class Result<Value, Error> {
	static Ok<Value, Error = never>(value: Value) {
		return new Result<Value, Error>(new Ok(value));
	}
	static Err<Error, Value = never>(error: Error) {
		return new Result<Value, Error>(new Err(error));
	}
	constructor(private result: Ok<Value> | Err<Error>) {}
	cata<
		Ok extends (value: Value) => any,
		Err extends (error: Error) => any
	>(x: Cata<Ok, Err>): ReturnType<Ok> | ReturnType<Err> {
		return (this.result.cata as AnyFn)(x);
	}
	map<
		NextValue
	>(mapper: (value: Value) => NextValue): Result<NextValue, Error> {
		return this.bimap<NextValue, Error>(mapper, <T>(x: T) => x);
	}
	mapErr<
		NextError
	>(mapper: (error: Error) => NextError): Result<Value, NextError> {
		return this.bimap<Value, NextError>(<T>(x: T) => x, mapper);
	}
	bimap<
		NextValue,
		NextError
	>(
		mapValue: (value: Value) => NextValue,
		mapError: (error: Error) => NextError
	): Result<NextValue, NextError> {
		return new Result((this.result.cata as AnyFn)({
			Ok: (value: Value) => new Ok(mapValue(value)),
			Err: (error: Error) => new Err(mapError(error))
		}));
	}
}
```

Here's an alternative implementation of Result

**Comment by weswigham** [comment]
Our rules for calls on unions are quite strict, as we do not have the capability to "resolve the call on each union member". When attempting to call a union, the call is only allowed of the signatures are sufficiently similar such that we can unify them into a single signature.

In this case we cannot, because each of the input signatures has a different type parameter (declared in a different location), which is going to prevent us from merging them. (While we could combine the parameter list, making inference then behave the same way on the input arguments as the component signatures isn't something we can do - the combined parameter type is inferred to by a potentially different set of inference heuristics).

The intersection with the base type workaround succeeds, as then in the resulting union, each type shares a common overload (the one intersected from the base), which we can trivially resolve against. It's worth noting that class inheritance works differently than intersection here - intersection merges signature lists, while when subtyping a class, you override them.

**Comment by wojpawlik** [comment]
Thank you for your thorough answer. 

> each of the input signatures has a different type parameter (declared in a _different location_)

Are you referring to generic type or its instantiation? If the former, I disagree that it depends on location of the declaration:

```ts
type AnyFn = (x: never) => unknown

interface Cata<OkFn extends AnyFn, ErrFn extends AnyFn> {
    Ok: OkFn
    Err: ErrFn
}

interface BaseResult<T, E> {
    readonly ok: boolean
    cata<ValueOut, ErrorOut>(
        cata: Cata<(x: T) => ValueOut, (x: E) => ErrorOut>
    ): ValueOut | ErrorOut
}

export class Ok<T> implements BaseResult<T, never> {
    readonly ok = true as const
    constructor(readonly value: T) {}
    cata<Out>(cata: Cata<(value: T) => Out, AnyFn>) {
        return cata.Ok(this.value)
    }
}
export class Err<E> implements BaseResult<never, E> {
    readonly ok = false as const
    constructor(readonly error: E) {}
    cata<Out>(cata: Cata<AnyFn, (error: E) => Out>) {
        return cata.Err(this.error)
    }
}

export type Result<T, E> = Ok<T> | Err<E>

// tests

declare const v: Result<number, Error>

const o = v.cata({
    Ok(v) {
        return "2"
    },
    Err() {
        return 3
    },
})
```
[Playground](https://www.typescriptlang.org/play/#code/C4TwDgpgBAggdiAYnKBeKAKAHgLinCANwgCcBKNAPigFc4BrOAewHc4AodgSzmFIDMAhgGNoAYUHBBAHgDy9ZFAhY+cACYBnWAmQAaKAFESJRctWbtSONQDe7KA6jy885PcdGSeT24C+nHj4SIVEoACFBDQgAJQgNGgAbYGkAFX0DW3cHEghBNSY4BJAoJno8ACMmJgTcjkcoYUkZADVBBJoIWRpgdOMmEi7gSgws+oamvAkpaWw8FIpUalb2zu79WcMF6k9+wcpRsjxljsGoAB9DPoHu9n92ZTB+4AaEyK15VOouAFswGu+ILwtBEorF4klUvoCMQSJl6jk8gUiiV6GgoMASB0oJEGgUNMBRsI8RiaMJgP0MAj8oVioQ2h05hQbP56o1pnsMGzBJMmjM6StGVQnGtLMhKEzRvCIMAaCQUFyAHTyDDAAAWXA0Cv5HTIo38-geTxeb0uJGkGSgPz+EABQPCkRicUSyWhpHScMcVKRxVKaKECSi2K0RLg+MJxMxZIpXppSiu3iZLMcXLk3WGXJ503gVnWpBI-QTQr2ErGnulsvlTQVnhV6s1ef6uvq+s4hpIz1AkCgYOdkMM1HQHxS1AunnN+3YAHpJ+i4sANJw1BBhK8crjQ89CHgexC4DRvuU3ab+hOQ-iSmjCAquRg7PVlYQS6WoDkZXKoAAiABMH71ulGNZPqWr4VlAADMf63GQQA)

This code (evolved in the meantime) doesn't alias `Cata`, yet it hits analogous error.

**Comment by weswigham** [comment]
> Are you referring to generic type

The generic type parameter on the method itself is to what I am referring. Each method declaration has a distinct list of them.

**Comment by zlepper** [comment]
I find that example really difficult to read, but i assume it's basically the same as what is happening here:

````ts
interface Base {
    foo: string;
}

interface SpecificA extends Base {
    bar: number;
}

interface SpecificB extends Base {
    baz: boolean;
}

enum TheType {
    A,
    B
}

interface A {
    type: TheType.A;
    foo: SpecificA[];
}

interface B {
    type: TheType.B;
    foo: SpecificB[];
}

type options = A | B;


// tests

function getValue(): options {
    return {
        type: TheType.A,
        foo: [
            {
                bar: 42,
                foo: 'my value'
            }
        ]
    };
}

const value = getValue();

value.foo.map(v => console.log(v.foo));
```
where the `.map` call is impossible, even though accessing `v.foo` should certainly be allowed. 

I'll try to work around it by doing a bunch of type casting.

**Comment by wojpawlik** [comment]
I encountered a scenario in which the requested behavior is undesirable:
```ts
interface Base {
	type: string
}

interface Foo extends Base {
	type: 'foo'
}
interface Bar extends Base {
	type: 'bar'
}

type Foobar = Foo | Bar
type FoobarTypeProp = Foobar['type'] // should be `'foo' | 'bar'`, not `string`
