### ISSUE TITLE
Merge "export * as" exports 

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#38041]
## Search Terms

Namespacing exports as

## Suggestion

Currently to export things under a conceptual "package" namespace in TypeScript developers must add a proxy barrel file

a.ts
```typescript
export const a = 'foo'
```

b.ts
```typescript
export const b = 'bar'
```

index.barrel.ts
```typescript
export * from './a'
export * from './b'
```

index.ts
```typescript
export * as mypackage from './index.barrel'
```

It would be great if the `export * as mypackage' statement could merge exports with the same name

## Examples

a.ts
```typescript
export const a = 'foo'
```

b.ts
```typescript
export const b = 'bar'
```

index.ts
```typescript
export * as mypackage from './a'
export * as mypackage from './b'
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by rbuckton** [comment]
This seems like something that should be proposed to TC39 first, as this directly affects the ECMAScript syntax.

I have been interested on extending more of the ECMAScript module syntax to namespaces, but that's been fairly low on the list of priorities. If we did that however, you might be able to do something like this:

```ts
import * as a from './a';
import * as b from './b';
export namespace mypackage {
  export * from a;
  export * from b;
}
```

**Comment by DanielRosenwasser** [comment]
If all you're interested in is exporting values, you could also write

```js
import * as a from './a';
import * as b from './b';

export const mypackage = { ...a, ...b };
```

**Comment by frangio** [comment]
`export * as name` seems to be a part of ECMAScript already.

See [Exports](https://tc39.es/ecma262/#sec-exports):

```
ExportDeclaration :
    export ExportFromClause FromClause;
    [...]

ExportFromClause :
    *
    * as IdentifierName
    [...]

FromClause :
    from ModuleSpecifier

```

**Comment by cruhl** [comment]
> This seems like something that should be proposed to TC39 first, as this directly affects the ECMAScript syntax.
> 
> I have been interested in extending more of the ECMAScript module syntax to namespaces, but that's been fairly low on the list of priorities. If we did that however, you might be able to do something like this:
> 
> ```ts
> import * as a from './a';
> import * as b from './b';
> export namespace mypackage {
>   export * from a;
>   export * from b;
> }
> ```

I have needed and wanted this syntax dozens of times. Specifically, namespace/function/type merging are useful for representing things like a type `User`, component `User`, and namespace `User` (i.e. `User.someFunction`). It's extremely hard currently to re-export something like `User.Profile` if `Profile` exists outside of the namespace definition itself.

**Comment by JalilArfaoui** [comment]
This has been closed, but I can see that @rbuckton solution is not working … has something been done to allow merging of exports ?

I’m trying to use [facade import](https://samhh.github.io/fp-ts-std/facades.html) strategy but with a named export or namespace …
