### ISSUE TITLE
Unable to determine type of key in object from conditionally typed function parameter

### ISSUE THREAD

**Issue by louisreingold** [microsoft/TypeScript#38046]
**Playground Link:** https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIDkCGBbCBnKBeKAidAFgPYCuANgCYBCEAysAE4CWAdgOa5QA+ehplNBCRQAjCA1wBuAFDTQkKADUkZJhWVkSEAGJEGcEAB4AKgD5sUY1AgAPYBBYVM+YuWp1GrDlAD8UdJ7sUABcUCzCYgwycuDQALIgAPIiAFYQAMbAFgDe0lD+rgIezOyhASVsMvl8boIR4qHhouIyAL7RAGYkLJlMRCxQKEgA1hAIEADuyWmZJtZ2Dk6w8Mho6KYAFHlQRKkZwKEJ0-sANNtgDERgxkQAwgRI7BChxmf5LJMaWqEaal86egMJlM0gAlFBcvl0v0AmFJsdMjkoAA6VG7GZZdrbD5TPaZADaFyuN3ujzYEAAuhYcf8qlAGBBgCQGAMcQjgG1pEA

```typescript
type KeyNames = "shouldBeString" | "shouldBeNumber";

type ValidValueForKey<T> = T extends "shouldBeString" ? string : number;

type MyObject = {
  shouldBeString: string;
  shouldBeNumber: number;
};

function makeNewObject<T extends KeyNames>(
  object: MyObject,
  propToChange: T,
  newValue: ValidValueForKey<T>
) {
  const newObject = { ...object };
  newObject[propToChange] = newValue;
  return newObject;
}
```
**Expected behavior:**

1. There should not be a type error when assigning _newValue_ to _newObject[propToChange]_, because when _propToChange_ is "shouldBeString", both _newValue_ and _newObject[propToChange]_ will be of type string, and when _propToChange_ is "shouldBeNumber", both _newValue_ and _newObject[propToChange]_ will be of type number.

**Actual behavior:**

1. There is a type error when assigning _newValue_ to _newObject[propToChange]_.
2. In the error message, TypeScript claims _newObject[propToChange]_ of type _'{ shouldBeString: string; shouldBeNumber: number; }[T]'._ _newObject[propToChange]_ should really have a type of string or number.

**TypeScript Version:**  Nightly

**Search Terms:** conditional type function parameter object keys

**Comment by louisreingold** [comment]
I think this is a bug. I'll happily work around it though. I'll give $250 to the first person who emails me in the next week and tells me how to work around this and still get what I want - which is TypeScript understanding that newObject[propToChange] and newValue are both strings when propToChange is "shouldBeString", and are both numbers when propToChange is "shouldBeNumber".

**Comment by MartinJohns** [comment]
This is a known design limitation. You assume that `T extends "shouldBeString" | "shouldBeNumber"` means that `T` is either one of those two, but that's wrong. `T` can also be the type `"shouldBeString" | "shouldBeNumber"`, making it impossible to type-safely evaluate this.

**Comment by RyanCavanaugh** [comment]
Subtle distinction: this isn't a design limitation; it's TypeScript identifying wrong code. This function is legal to call in a way that creates a corrupted value:
```ts
const k = makeNewObject<KeyNames>({ shouldBeNumber: 10, shouldBeString: "" }, "shouldBeNumber", "ha");
// Crashes
k.shouldBeNumber.toFixed(0);
```

**Comment by louisreingold** [comment]
Thank you for the explanation. If I understand correctly, if I could tell TypeScript that T can be string, T can be number, but T can't possibly be anything else - i.e. it can't be string | number, then it would work?

If so, any hints on telling TypeScript that would be appreciated.

**Comment by louisreingold** [comment]
In my example, is TypeScript able to conclude that when T is "shouldBeString", the type of newObject[propToChange] and newValue are both string, and that when T is "shouldBeNumber", the type of newObject[propToChange] and newValue are both number, and the only reason for the TypeError is that T could also be "shouldBeString" | "shouldBeNumber"?

**Comment by louisreingold** [comment]
I believe the error message where TypeScript claims newObject[propToChange] of type '{ shouldBeString: string; shouldBeNumber: number; }[T]' is wrong. How could newObject[propToChange] could not ever be of type { shouldBeString: string; shouldBeNumber: number; }. That's the type of newObject itself, not the keys of newObject.
