### ISSUE TITLE
inconsistent string template exports in type interface files

### ISSUE THREAD

**Issue by aappddeevv** [microsoft/TypeScript#38055]
**TypeScript Version:**  3.8.3

**Code**
```ts
export const strange = `no interpolated values`
export const interpolated = `has interpolated ${some_value} values`
```
**Expected behavior:**
```ts
export declare const strange: string
export declare const interpolated: string
```

**Actual behavior:**
```ts
export declare const strange = "no interpolated values"
export declare const interpolated: string
```
I could not determine if this was expected but it seemed inconsistent.

**Comment by MartinJohns** [comment]
This is by design. See: #16592

The first version is a constant because it contains no interpolated values. That means a more strict type (the string literal type) can be inferred.

**Comment by j-oliveras** [comment]
As a workaround you can set the type explicitly:
```ts
export const strange: string = `no interpolated values`
```
