### ISSUE TITLE
key constraints not helping return type inference

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#38054]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

mapped index types inference return values keyof

**Code**

```
interface Foo {
  x: number;
  y: string;
  z: boolean;
}

// Should be able to infer the return type  based on switching
// on keys. And error out on an unrecognized key.
function Bar<K extends "x"|"z">(fieldName: K): Foo[K] {
  switch (fieldName) {
    case "x":
      return 0; // Ideally it realizes here typeof Foo["x"] is number.
    case "z":
      return false; // Ideally it realizes here typeof Foo["z"] is a boolean..
  }
}

// Tooltip correctly infers the type of test based on the argument
const test = Bar("z");
```

**Expected behavior:**
 The switch statement is considered exhaustive.  And the return in each branch are considered the correct type.

**Actual behavior:**

Each of the returns complain about not being assignable to never.  And you get an error about the function lacking a return statement because it doesn't consider the switch exhaustive.

**Playground Link:** 

https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=1&pc=10#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIAeAXMiAK4C2ARtANz7ICepAzmFKAOYMEBepapgA2EOCAYBfXLgD0s5AGUAFunLCAJslrI41UcjBZQMaIeUooEMOSghDTAA4ptcVhC3p7rAO5hgCMrccgpeyADWEEysAHS4MOQgCP5hAEJwUAA8ANLIEISQIBqsyABEhKUAPqV8pQB8ABQwwBCaAHJwlBCk2QCUpBjoANrZALo4jL7AYIHITS3tnRC9EwQECG4o5aXEjGvIVjZ2yAAMvGsb7mW1u-sEh7b28MLu59LSIcgAwuhQVsnCJjIEzQEpgCwEMBOFDoGDIBBediudyeezglAZLhUCDgXAIkBIyBIgC8yHSUAaNVKvToQA

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/30784
https://github.com/microsoft/TypeScript/issues/22735

**Comment by kwasimensah** [comment]
So  looking at the generated Javascript, it actually makes sense that you can do switch exhaustion with keys because they really are just strings and anyone can pass what they want once it's javascript. 

The return type however still seems like it could be inferred.

**Comment by RyanCavanaugh** [comment]
This would be covered by #33014
