### ISSUE TITLE
private class field declaration generates #private in dts

### ISSUE THREAD

**Issue by dnalborczyk** [microsoft/TypeScript#38050]
TypeScript Version: **3.8.3** and **v3.9.0** nightly

repro:

```ts
// ts
class FooBar {
    #foo = 'foo'

    bar() {
        return this.#foo
    }
}
```

**Expected behavior:**
```ts
// dts
declare class FooBar {
    bar(): string;
}
```

**Actual behavior:**
```ts
// dts
declare class FooBar {
    #private;
    bar(): string;
}
```

**playground:**
https://www.typescriptlang.org/play?ts=3.9.0-dev.20200418#code/MYGwhgzhAEBiD28BCYBO0DeAoavoGIAzRaAXmgHJj4Ksc8AjNACgEpN689UBTAFwCuqAHbQ+ACwCWEAHRFEnaAF8sSoA

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/36963
https://github.com/microsoft/TypeScript/pull/36640
https://github.com/microsoft/TypeScript/issues/36630

**Comment by RyanCavanaugh** [comment]
This is the intended behavior so that classes with `#p` private fields retain their nominal typing behavior when emitted to a .d.ts file

**Comment by pikadun** [comment]
@RyanCavanaugh 

I used a [npm package](https://github.com/pikadun/dom) with d.ts containing `#private`, the compiler issues some errors, such as : `'#private' is declared here.`, `Property '#private' is missing in type xxx`.

The `#private` in `lib/api/Element.d.ts`
