### ISSUE TITLE
Possibly undefined in filter

### ISSUE THREAD

**Issue by LonguCodes** [microsoft/TypeScript#38053]
**TypeScript Version:**  3.9.0-beta

**Search Terms:** undefined, possibly undefined

**Expected behavior:** Code should pass compilation 

**Actual behavior:** The compiler complains that `a` is possibly undefined in the filter

**Related Issues:**

**Code**
```ts
function foo(a?:{b:{[x:string]:any}}) {
  if (!a)
    a = {
      b: {
        c:{x:1},
        d:{e:1}
      }
    };
  const filteredKeys = Object.keys(a.b).filter(x => 'x' in a.b[x]);
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function foo(a) {
    if (!a)
        a = {
            b: {
                c: { x: 1 },
                d: { e: 1 }
            }
        };
    const filteredKeys = Object.keys(a.b).filter(x => 'x' in a.b[x]);
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "Latest",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?allowJs=true&target=99&ts=3.9.0-beta#code/GYVwdgxgLglg9mABMOcAUBDA-ALgN4BG+A2gB44DOUATjGAOYC6OGYAngL4cCUieAUIkQxgiNAEIM3QUMQZEAXj4zZiIstWqI+cgEYOAGhWaAJvgCmOfcaEdjHANwyICKshgAbKOermTAaXM2CkVEAHkCACtzaAA6AGsgikxYgm5Y4E9vajRSRQA+RAByUiLhJAxUskZuJw4gA)

**Comment by RyanCavanaugh** [comment]
It's legal to assign `undefined` back to `a`, and TS doesn't know that `filter` invokes its callback immediately, so it errs on the side of being conservative. See also #11498

**Comment by LonguCodes** [comment]
@RyanCavanaugh thank you for your quick answer, now I understand. Is there a way to mark `a` so it's considered a non-undefinable variable after the assignment?
