### ISSUE TITLE
Cannot assigned values from the constructor to a property that has been initialised at a class that extends another class

### ISSUE THREAD

**Issue by zisiszikos** [microsoft/TypeScript#38075]
**TypeScript Version:**  3.8.3

**Search Terms:** initialise, property, class, constructor, super

**Code**

```ts
interface IA {
    names: string[];
}

class A implements IA {
    names: string[] = [];
    constructor(names: string[]) {
        this.names = names;
    }
}

interface IB extends IA {
    ages: number[];
}

class B extends A implements IB {
    names: string[] = [];
    // names: string[];  <---- Error: TS2564
    // names?: string[];  <---- Error: TS2416
    // names!: string[];  <---- Works but not best solution
    ages: number[] = [];
    constructor(names: string[], ages: number[]) {
        super(names);
        this.ages = ages;
    }
}

const b = new B(['john', 'bill'], [23, 34]);
console.log(b.names); // <---- this is empty array!
```

**Expected behavior:**
The property `names` at class `B` should finally have the values `['john', 'bill']`.

**Actual behavior:**
The property `names` at class `B` is an empty array because when adding an initialiser at a class property, typescript is moving this initialisation inside the constructor but **after** the `super` function.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?removeComments=true&ssl=30&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJIEFkG8BQz-IhwC2EAzgFzJlhSgDmA2gLoDcOAvjjggDZxkyyTMGIAHXhFLghGbHgJFSlarQYtkAXmQt2BZAgD2IGlACuCMIagAKJeSqn1zAJTz9+sAAtgZAHT2QtqBegRcXDigkLCIKKgAQsgQAB6QIAAmspi4+nD0DoRmxABG0Lqc3HwCQokpaZnCyKISUhAyaIk5iiQFTiBMzFo6bAr4APRjhD0qfQOs+AA8ALQrS8gAolBQ1lQAKgDKAEwArABsACyjyBNTygD8jmr9uoura5vbUHtH5wCMp1cboEAISPOjPNivVbIADq1gA1kJimYwIRDKjSjRqIZeCjgMYrnkCiAiqUoBptOV9EYTLQLFZbIEwc4ADTIIkqEklMqudwefBkMxiaB2aYuUL87y+PwcoYciXIcKVYxY4pDEAQADuyHiNkYAHIAFaGLwgfVs-XFYC8Xj65hsxiHADMbKd51c7BpZBxED8vEM9BsxQCYvmN2W0KlQl8SXEYAAnuytnB48CcEA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See https://stackoverflow.com/questions/43595943/why-are-derived-class-property-values-not-seen-in-the-base-class-constructor . This is the JavaScript initialization order; nothing to do with TypeScript here.

The best solution is to just not redeclare `names` in `B`
