### ISSUE TITLE
"Add all missing imports" adds them all in one line

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#38082]
**TypeScript Version:**  3.9.0-dev.20200420

**Search Terms:**
- fix all
- code action
- quick fix

**Code**
With `@types/node` installed, open a file:

```ts
join();
homedir()
```

1. Now trigger quick fixes and select `add all missing imports`

**Bug:**
The two imports are added on the same line:

```js
import { join } from "path";import { homedir } from "os";

join();
homedir()
```

Here's the edit that TS Server returns in this case

```
[Trace  - 23:52:04.985] <semantic> Response received: getCombinedCodeFix (72). Request took 13 ms. Success: true 
Result: {
    "changes": [
        {
            "fileName": "/Users/matb/projects/san/test.ts",
            "textChanges": [
                {
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 1,
                        "offset": 1
                    },
                    "newText": "import { join } from \"path\";"
                },
                {
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 1,
                        "offset": 1
                    },
                    "newText": "import { homedir } from \"os\";\n"
                }
            ]
        }
    ]
}
```

**Comment by DanielRosenwasser** [comment]
Likely a culprit of generated nodes not having trivia, so the new "preserved trivia" strategy is not printing out new lines between statements. See some instances of this in https://github.com/microsoft/TypeScript/pull/37814

**Comment by andrewbranch** [comment]
It would be helpful if I could get a review on #37846

**Comment by DanielRosenwasser** [comment]
I gave a reivew, but if I understand correctly I think that only solves problems for gathering newlines between nodes more appropriately - it doesn't fix the problem for nodes that have no newlines because they're generated.

**Comment by andrewbranch** [comment]
I think you’re probably right, but it will be useful nonetheless to avoid making simultaneous PRs to the same area. Thanks!

**Comment by andrewbranch** [comment]
@mjbvz, it doesn’t seem to repro for me—also using that nightly and Insiders. Now that I think about it, we definitely already have test coverage for fix-all imports that should catch this. My screen cap shows semicolons on both calls, but I tried it with mixed and semicolon-less styles too. Any tricks you can think of to reproduce this?

![Kapture 2020-04-21 at 15 42 28](https://user-images.githubusercontent.com/3277153/79921271-bb851800-83e6-11ea-8ddc-9ec8ca2918a4.gif)

**Comment by mjbvz** [comment]
To repo for me, start with:

```ts
import fs = require('fs')

join();
homedir()
```

Delete the import. Then trigger the `add all missing imports` quick fix

**Comment by andrewbranch** [comment]
Thanks! The trick was having a newline at the start of the file. This turned out not to be related to the newline preservation changes after all.
