### ISSUE TITLE
Add outlining spans for 'type' declarations

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#38080]
From https://github.com/microsoft/vscode/issues/95577

**TypeScript Version:**  3.9.0-dev.20200420

**Search Terms:**
- fold / folding
- outlining spans / `getOutliningSpans`
- type

**Code**
For the TS:

```ts
interface A {
    x: number
}

type B = {
    y: number
}
```

**Expected behavior:**

Both `A` and `B` are foldable

**Actual behavior:**

Only the interface (`A`) is foldable

**Comment by a-tarasyuk** [comment]
I noticed that Tuple type doesn't have outlining spans too,

```ts
type Foo = [
    number,
    number
]
```

@mjbvz Do you think it makes sense to add outlining spans for the Tuple type?

cc @DanielRosenwasser

**Comment by orta** [comment]
Yeah, I think we should 👍

**Comment by 16oh4** [comment]
@orta @a-tarasyuk @mjbvz Cool, thanks a lot!
