### ISSUE TITLE
Path mapping doesn't work for relative modules

### ISSUE THREAD

**Issue by slavafomin** [microsoft/TypeScript#38095]
Hello!

I'm trying to use [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) feature (i.e. a "paths" config option) to redirect compiler from one local modules to another one. However, the compiler completely ignores `paths` when trying to import file starting with `./`.

This limits my control over the paths resolution algorithm in TypeScript. Is this intentional? I doesn't see any mentions about this in the documentation.

# Example

```typescript
import readme from './README.md';
```

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*.md": ["./empty-string.ts"]
    }
  }
}
```

In this example I'm trying to replace all imported markdown files with an empty string, because `tsc` doesn't know how to import such files. This is handled by Webpack instead.

# Actual behavior

Having `./` in the import statement makes `tsc` to ignore `paths` option completely.

# Expected behavior

Path mapping should work for any module names, be it relative ones or module ids from `node_modules`.

---

**TypeScript Version:** Version 3.9.0-dev.20200421

**Comment by RyanCavanaugh** [comment]
Path mapping is only applied to nonrelative module names like `foo` or `bar/baz`. There is currently no mechanism that allows relative names to be resolved in any way except for in a normal relative manner.
