### ISSUE TITLE
Expect an error when try to set two props from two union interfaces 

### ISSUE THREAD

**Issue by Ester-I** [microsoft/TypeScript#38097]
**TypeScript Version:**  3.8.3

**Search Terms:**
 prevent from prop to be set if other prop is set / union interfaces ...

I want to be sure that only one prop from some would  be set. 
I expect that if I declare two interfaces and do union with **|** , mixing two different interfaces in a single object will be avoided.

**Code**

```ts
interface General {
  prop1: boolean
}

interface Option1 extends General {
  prop2: boolean
}

interface Option2 extends General {
  prop3: boolean
}

type Option1orOtion2 = Option1 | Option2

let data: Option1orOtion2 = {prop1: true, prop2: true, prop3: true}
```

**Expected behavior:**
Receive an error that only one param can be set (`prop2` **or** `prop3`).
Setting them both will be disabled.

Success to do this:
```ts
let data: Option1orOtion2 = {prop1: true, prop2: true}
```
or this:
```ts
let data: Option1orOtion2 = {prop1: true, prop3: true}
```
but **not** this:
```ts
let data: Option1orOtion2 = {prop1: true, prop2: true, prop3: true}
```

**Actual behavior:**
Both can be sent although the interfaces are configured as **or**.
```ts
let data: Option1orOtion2 = {prop1: true, prop2: true, prop3: true}
```

**Playground Link:** [playground link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgOIRNOAbZBvAKGWQAcoB7EgRgH4AuZAI3POwjhCNIpICZ6mLNhwIBfAgVCRYiFAHkSYYORBVkEAB6QQAEwDOaDFlyFiZSgGYGzVu07jJ4aPCTIFSlb3VaM+w5igcfC5zEgAWayE7MQkwAE8SeUVlVXIoOQ8QLwBeN2SVNQAfPMzeCTYwZB04MDgGdxSqNIyUnPxuSwYwKABXCAAaDvCu3pRxIA)

**Comment by RyanCavanaugh** [comment]
Object types aren't sealed and unions aren't mutually exclusive. You've provided a value that is valid for both cases. Discussion at #14094
