### ISSUE TITLE
`querySelectorAll` returns a NodeList with wrong child types

### ISSUE THREAD

**Issue by TheDutchCoder** [microsoft/TypeScript#38090]
**TypeScript Version:** 3.8.3

**Search Terms:**
querySelectorAll
NodeList
Element

**Code**

```ts
// Given the following document innerHTML
document.body.innerHTML = '<div><p><span>a</span></p><p><span>b</span></p></div>'

const children = document.querySelectorAll('p')
children.forEach(child => {
  const sub = child.querySelector('span') // Results in: "Property 'querySelector' does not exist on type 'Node'.ts(2339)"
})
```

**Expected behavior:**
TS to know that elements in a NodeList are of type `Element` and not `Node`
See: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

**Actual behavior:**
TS thinks children are of type `Node`

**Additional info**
Logging the child even shows that it is of type `HTMLDivElement`

**Comment by orta** [comment]
You can learn about this on the new site's docs: http://www.staging-typescript.org/docs/handbook/dom-manipulation.html
