### ISSUE TITLE
Destructing nested arrays/tuples does not infer type

### ISSUE THREAD

**Issue by ryall** [microsoft/TypeScript#38092]
**TypeScript Version:**  Nightly

**Search Terms:**
"typescript array destructing types not working"

**Expected behavior:**
`fieldName` to be of type `string`
`emptyValue` to be of type `any`
`expectedError` to be of type `string`

**Actual behavior:**
`fieldName` is of type `string | boolean`
`emptyValue` is of type `string | boolean`
`expectedError` is of type `string | boolean`

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/32465

**Code**
```ts
// Fails
for (const [fieldName, emptyValue, expectedError] of [
    ['email', '', 'must enter an email address'],
    ['password', '', 'must enter a password'],
    ['tos', false, 'must accept the ToS'],
]) {
  fieldName.charAt(0);
}

// Works
const [fieldName, emptyValue, expectedError] = ['email', '', 'must enter an email address'];

fieldName.charAt(0);
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// Fails
for (const [fieldName, emptyValue, expectedError] of [
    ['email', '', 'must enter an email address'],
    ['password', '', 'must enter a password'],
    ['tos', false, 'must accept the ToS'],
]) {
    fieldName.charAt(0);
}
// Works
const [fieldName, emptyValue, expectedError] = ['email', '', 'must enter an email address'];
fieldName.charAt(0);
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200420#code/PTAEDEEMEsBsGcBQAzA9gJ1ACgMaoHbwAuoA2stAKawAmAcpALaUA0oljADkQJ4BqkWAFdW7AB6dKOIpRoBRdOgwBdUKmRlEobWQDkHGLF1tdx0LsZDi7fDMyR87RodCQaNdJXjxdyllp1SXU5IbwB3DBozUxNLa0pbSntQEPDI338dPSJUHzZkQXhRCysSSBwcSm5QIgALSlAAFVQAZQzEZQBKUABvAIpqeiZKADocWsh0AEEiLAAGToBuRABfREQQUAB1DABrJDxCEnIqWgZmNg5ufkERS4kpGXlFFVAAXj0DOGjouJIEuyuRxfWCudyeby+ZYoU5DZhjCbTWYLRZAA)

**Comment by nmain** [comment]
In the playground link you provided, typescript is already giving you exactly the right error message at exactly the right place that tells you exactly why this won't work.

> The left-hand side of a 'for...of' statement cannot use a type annotation.(2483)

Relevant discussion: https://github.com/Microsoft/TypeScript/issues/3500#issuecomment-494491530

**Comment by ryall** [comment]
Yeah apologies, I have updated the code to demonstrate the problem more clearly.

**Comment by ryall** [comment]
I can fix the issue by explicitly defining the type of the tuple, with:
```ts
for (const [fieldName, emptyValue, expectedError] of [
    ['email', '', 'must enter an email address'],
    ['password', '', 'must enter a password'],
    ['tos', false, 'must accept the ToS'],
] as [string, any, string][]) {
  fieldName.charAt(0);
}
```

**Comment by MartinJohns** [comment]
> I can fix the issue (for now) by explicitly defining the type of the tuple, with:

Without the type assertion you don't have a tuple, you just have an array. You can also use `as const`, it's intended for this.

Changing this behavior (infer tuple instead of array by default) would be a major breaking change.

**Comment by ryall** [comment]
OK thanks for the clarification! :)

**Comment by ryall** [comment]
OK thanks for the clarification! :)
