### ISSUE TITLE
Object is possibly 'undefined' when accessing Partial object via bracket notation

### ISSUE THREAD

**Issue by NIV54** [microsoft/TypeScript#38091]
I can't understand why i can gain access to a `Partial` object this way `a.b && a.b.c`
but not this way `a[keyof A] && a[keyof A].b` (when typeof `a` is `A`).

I have a use-case in which I can't use optional chaining. I want to conditionally render a `React` element like so `{myObj[key] && <p>myObj[key].message</p>}` when the type variable `key` is of type `keyof myObj`. See example below to better understand.

**TypeScript Version:**  3.8.3

**Search Terms:**
- cant access partial type with Bracket notation
- Bracket notation on Partial
- access to partial type with Bracket notation failes to evaluate

**Code**

```ts
export interface MyType {
  a: number;
  b: string;
  c: Date;
}

interface MyOtherType {
  message: string;
}

const myObj: Partial<Record<keyof MyType, MyOtherType>> = {
  a: { message: "my message" },
  b: { message: "my message" },
  c: { message: "my message" }
};

myObj.a.message // not allowed - `Object is possibly 'undefined'`
myObj.a?.message // allowed
myObj.a && myObj.a.message // allowed

const myKey: keyof MyType = "a";
myObj[myKey].message // not allowed - `Object is possibly 'undefined'`
myObj[myKey]?.message // allowed
myObj[myKey] && myObj[myKey].message // not allowed - `Object is possibly 'undefined'` - why?
```

**Expected behavior:**
last line should work
**Actual behavior:**
Object is possibly 'undefined' error thrown when running tsc

**Playground Link:** https://codesandbox.io/s/mystifying-framework-5110c

**Related Issues:** #29642 is very similar but was closed for a being a duplicate of an issue from 2016 (?!). I don't think they are even related.

**Comment by MartinJohns** [comment]
Duplicate #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.
