### ISSUE TITLE
How to use types embedded in npm module

### ISSUE THREAD

**Issue by valeriob** [microsoft/TypeScript#38114]
I'm asking the question here because in SO there are no answers at all (not even bad ones :( ) as far as i could find. 

Here is the repro, just added knockout npm package and run tsc -b.
I expected it to work since knockout include types in the package 
node_modules\knockout\package.json :   "types": "build/types/knockout.d.ts"

[types.zip](https://github.com/microsoft/TypeScript/files/4517240/types.zip)

To reproduce the problem :
- npm install
- tsc -b
- You should get the error
 `index.ts:1:12 - error TS2304: Cannot find name 'ko'.`

Thanks
Valerio

**Comment by RyanCavanaugh** [comment]
The issue templates are quite clear about what kind of activity is expected here.

**Comment by valeriob** [comment]
I'm sorry, but this question has been made many times in SO and does not have an answer : 
https://stackoverflow.com/search?q=%5Btypescript%5D+package.json+type+definitions
Can you point me to the right one pls ?
Thanks
Valerio

**Comment by valeriob** [comment]
I was able to use type definitions embedded in npm packages by using the configuration below
{
   "compilerOptions": {
       "types" : ["babylonjs", "knockout"]
   }
}
The documentation barely touch this scenario 
`A types package is a folder with a file called index.d.ts or a folder with a package.json that has a types field.` 
i guess this qualifies this issue as a feature request to update the documentation to make it more clear.

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

Thanks
