### ISSUE TITLE
VS Code: intersection types, type not assignable

### ISSUE THREAD

**Issue by sKopheK** [microsoft/TypeScript#38113]
Hello, using VS Code to have typed JS (checkJs: true), but it seems to be having troubles with intersection types that work in both TS and JS in TS Playground without any error. Interestingly enough, properties from a second intersected type are correctly detected by VS Code despite the error on assignment of the typed value (see intellisence tooltip on the screenshot in Actual behavior).

**TypeScript Version:**  3.9.0-dev.20200420

**Search Terms:**
not assignable, Intersection types

**Code**
```
const ExtraProps = {
    one: 1,
    two: 2
}

class Test { }

/** @type {Test & ExtraProps} */
const inst = new Test();
inst.one;    // no complains
```
[Playground Link](https://www.typescriptlang.org/play/?useJavaScript=true#code/MYewdgzgLgBAogDygJwIYAVkgA4RgXhgG8AoGcmcAUwC4YBGAGjIqgHcQ6AmEgXxJLAANqgh4AKlWjEY-EgHoAVIpgABKAE9sVYpOkAyeEjSYcEXjEXzB4aQEtIsQmCpsYeqAAoAlAG4SDtAAdNS+FDDy8jBgIDCgALbYIoFAA)

Assigning a properly defined type also does not work:
```
/**
 * @typedef {{[x in "one"|"two"]: number}} ExtraPropsType
 */

/** @type {Test & ExtraPropsType} */
const inst = new Test();
```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/5802917/80001620-33813a00-84dc-11ea-8e8e-ff78997a4726.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/5802917/80000908-624ae080-84db-11ea-9787-e16ae3067c2e.png)

**Comment by RyanCavanaugh** [comment]
The behavior in VS Code is the desired one. Something's wrong with the Playground

**Comment by sKopheK** [comment]
> 
> 
> The behavior in VS Code is the desired one. Something's wrong with the Playground

is both error for value assignment and later proper property detection desired tho?

regarding the playground: does the same problem occur in the following TypeScript code?

![image](https://user-images.githubusercontent.com/5802917/80013357-5c113000-84ec-11ea-9e75-53949738850a.png)
[Playground Link](https://www.typescriptlang.org/play/#code/C4TwDgpgBAogHsATgQwArJQWwM5QLxQDeAUFGVAPYB2EAXFFQK6YBGEiA3KecAO4X0mrdlwC+xYgGMANsmy4AKhGzAiUbmQq8qqRBTD4oAcgAWEadIpHi4qdRVQAllQcEavKEpUAKAJRQ5T2VVADJYBBR0LGwuZxUAOiA)

**Comment by IllusionMH** [comment]
Just in case - there are no errors reported for JavaScript in current playground (see https://github.com/microsoft/TypeScript-Website/issues/203) so unfortunately you can't rely on it.

But you can see same error in Errors tab of [new playground](https://www.typescriptlang.org/v2/en/play?useJavaScript=true#code/MYewdgzgLgBAogDygJwIYAVkgA4RgXhgG8AoGcmcAUwC4YBGAGjIqgHcQ6AmEgXxJLAANqgh4AKlWjEY-EgHoAVIpgABKAE9sVYpOkAyeEjSYcEXjEXzB4aQEtIsQmCpsYeqAAoAlAG4SDtAAdNS+FDDy8jBgIDCgALbYIoFAA)

**Comment by sKopheK** [comment]
wasn't aware of the new playground, thanks.
seems like a bug then, but, I'm wondering, how should this TS code behave then. no errors even in the Errors tab, *correct* recognition of properties from the second intersected type:

![image](https://user-images.githubusercontent.com/5802917/80059761-6530ea00-854a-11ea-9b6c-001920ca8303.png)

[Playground Link](https://www.typescriptlang.org/v2/en/play?#code/C4TwDgpgBAogHsATgQwAqIPZgM5QLxQDeAUFGVBgHYQBcUlArgLYBGEiANKecAO4Z1GrdsQC+xYgGMANsmy4AKhGzAiUcVKoqoAS0raC1XlCUqAFAEoock8tUAyWAhTos2ANzE9KgHRA)

**Comment by IllusionMH** [comment]
This one is [type assertion](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) which is completely different and might be not safe.
> Type assertions are a way to tell the compiler “trust me, I know what I’m doing.”

This is definitely not the same as JS which correctly reports type that has missing properties.

Anyway you can use
```js
/** @type {Test & ExtraPropsType} */
const inst = (new Test());
```

Which won't allow to check types in JS and won't complain. But it's still unsafe (as with most JS checks) so use it with care.

**Comment by sKopheK** [comment]
Thanks. Everyday, I'm learning some many new things about TS :). 
I might have wrong thinking with all this overly complex structures and a bit too generic approaches, but I like to follow DRY principle and as TS does not support https://github.com/microsoft/TypeScript/issues/38115, I have to use some workarounds to have my code realm by my desires.

**Comment by orta** [comment]
Linking this to https://github.com/microsoft/TypeScript-Website/issues/203 - I'm aiming to get this in before the 3.9 release build of the playground

**Comment by sKopheK** [comment]
How much ugly is this workaround :)?
```typescript
type extraProps = {
    DecoratedProp: number;
    ExtendedProp: string;
}

function decorator(target: Function) {
    target.prototype.DecoratedProp = 2;
}

@decorator
class Test {
    Prop: number;
    constructor() {
        this.Prop = 1;
    }    
}

Object.defineProperty(Test.prototype, 'ExtendedProp', { writable: true });

const DecoratedTest = Test as ((new () => Test & extraProps) & typeof Test);

const inst = new DecoratedTest();
console.log(inst.DecoratedProp);    // outputs "2"
inst.ExtendedProp = 'test';
console.log(inst.ExtendedProp);    // outputs "test"
```

[Playground Link](https://www.typescriptlang.org/v2/en/play?#code/C4TwDgpgBBAewCcCGAFBB7MBnKBeKA3gFBSlQAiEAxussBACZqYBcUAdgK4C2ARhAgDcJMgFF4Edg0bMwbLIgCW7AObCAvkSIAzTuyrBF6dlGk06tABTAkCFRGBsAYnoNH2ASkIjSNuw4A6MAxgdFBIAMpzJHomDDA8KAAmDS0AATNaGNoiKgAbJCwcABUIBW8yKFk2Lj4BYUqadgUETgMrL2JKyuAAC0UsANlEgEYGsnVKok0iAHleACtqYADpbWUIWQFQS1KFIJCw8AgAGigAcnF6KRl487OCKAB3BEUbXjyINkROaHUPYS5YzlKJZWJ7YCJCFQQpQSyWdgQJ5wry4AB8UGhADIYPBkLIsF4ceEIOhtJiysAAVomuVlOV8IjkaC6IwIZZqbT0J8Anl0CpLPSViyYrdMADKgB6SVQdCcYBgeU4ABESWVRCFASukmkcUwiXO9AU52EXJ5fIFmu1Nz1YAlZGlsvliuAKqNwHVQA)

**Comment by orta** [comment]
The JS support for errors should be fixed on the staging site as of tomorrow: https://www.staging-typescript.org/play

**Comment by orta** [comment]
The Playground and VS Code provide the same errors the same here when in JS mode on nightlies:

![Screen Shot 2020-07-21 at 12 34 40 PM](https://user-images.githubusercontent.com/49038/88081592-95d6ee80-cb4e-11ea-9afd-77e438e1e5fc.png)

@IllusionMH  is right, the underlaying misconception here is what the `@type` is being applied to:

```js
/** @type {Test & ExtraPropsType} */
const inst = new Test();
```

is like `const inst: Test & ExtraPropsType = new Test();` vs 

```js
/** @type {Test & ExtraPropsType} */
const inst = (new Test());
```

is like `const inst = new Test() as Test & ExtraPropsType`

Which is why we get the error without the braces. This leaves the question to me as: Should we consider this a bug and always assume the `as` condition in this space?

**Comment by orta** [comment]
Yeah, so I double checked this the behavior is as expected
