### ISSUE TITLE
Type narrowing is ignored unless the object is constructed by destructuring with explicit narrowed property assigned to it

### ISSUE THREAD

**Issue by taxnuke** [microsoft/TypeScript#38126]
**TypeScript Version:**  3.8.3

**Search Terms:**
type not narrowed sometimes declaration ignored deep asserts object destructuring

**Code**

```ts
declare function getPerson(name: string): Person;

interface Person {
    marriedAt?: Date;
}

type MarriedPerson = Person & {
    marriedAt: Date;
}

const marriedPeople: MarriedPerson[] = [];
const joe = getPerson('Joe Johnson');

if (joe.marriedAt) {
    // narrowed
    marriedPeople.push({
        ...joe,
        marriedAt: joe.marriedAt
    });

    // not narrowed
    marriedPeople.push(joe);
}
```

**Expected behavior:**
Type narrowed in both cases

**Actual behavior:**
Type narrowed only in one of the cases

**Playground Link:** https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMAFEGAZzwApUoBbEALngoxi1QIEoWzK8AbgBQwzhnKIoYBPyr4A3sPgr49WBxDAAghgD8LACJQJIgL6iMATwAOCALIasWuXngBeeK-wAyeEtU1Jy1dIxMQc1EwPDYgmE1gMhwbCGZ4R3jnRPJ5AG0AXQ94ApFo1FiAKxwETyJSHJoAcgApavhWgAtyvEbuETFEeGoqkAA6dUyQjG5-ZVUAenn4OnicAHctOZUJhKSUsZtkCg7qAMDVUcuRgBot852s0PgR8eCdDDuzPtFAxeWcDDLDTrTaBB4uEDJVKjQ7HYbVb5mIA

**Related Issues:** Couldn't find any

**Comment by rvinzent** [comment]
Here's another example that seems related and is also frustrating to work around 
```
interface FormData {
    description: string | null
}

function saveForm(formData: { description: string }) {
    console.log(formData)
}

function submitForm(formData: FormData) {
    if (!formData.description) {
        // type of formData.description is not narrowed even inside this block
        throw new Error()
    }
    saveForm(formData) // TypeError: "string | null" is not assignable to string
}
```

[Playground Link](https://www.typescriptlang.org/play/?ssl=16&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgGIHsoFsAicxzIDeAUMucgCYQDOCUwADmMOiAFzI1gMgDmyAD7IQAVwA24kgF8SJGKJAIWbLnABuEDNgAUMTLnxxORKrXpMVHLj1ADpASmJkKCNjXTiIAOnHo+egZ4BA4ycgpKVlyiAEZYwGDaWIHYwcZoQUZOpBTIwDDIOgCE+qlG3tR0DMysINkuueQA9E3IYACejCjoBaWGBBXm1VHANCLoYCJwUFDoAO4QlA2NYAAWs3MiEJsAojOYOqG5srk0GloGKf1wTi3IACqdEHuzUJwARNy8AsJiku95MYgCbIOA0GjAPggOAxLxtdA2b5hIA)

**Comment by RyanCavanaugh** [comment]
See #10065

**Comment by rvinzent** [comment]
@RyanCavanaugh is it reasonable to have `if (!formData.description)` perform the same type narrowing as `if (formData.description !== null)` in the above example? It appears that the `!` operator doesn't remove `null` from the type, while `!== null` is able to do so.

**Comment by RyanCavanaugh** [comment]
@rvinzent inside `if (!formData.description) {`, its value could be either `""` (a string) or `null`, so the type `string | null` is still correct

**Comment by rvinzent** [comment]
🤦 I'm dumb pls ignore
