### ISSUE TITLE
Support mutually exclusive members in interface

### ISSUE THREAD

**Issue by akshgpt7** [microsoft/TypeScript#38120]
## Search Terms
- mutually exclusive
- interface
- optional

## Suggestion
TypeScript currently supports optional properties in interfaces.
It'd be a good idea to also allow creating mutually exclusive groups for options that cannot coexist, when declaring variables in an interface. 

Say, we have 2 properties declared in a mutually exclusive group in an interface. Now, *exactly one* of those properties can exist, with no two properties coexisting simultaneously in an object having type of that interface. (See **Examples**)
```typescript
interface args {
  (arg1: string | arg2: string);
}
```

Additionally, we can also think of making the entire group optional, maybe with something like this:
```typescript
interface args {
  ?(arg1: string | arg2: string);
}
```

## Use Cases
Many APIs have filters of which exactly one can be used at a time. So to define their schemas, such a feature can prove to be really helpful.
Also, there are many options/flags which cannot be used simultaneously in one command line.

Optional properties do not solve this problem, since they make a property independently optional, without checking against other properties. 

## Examples
```typescript
interface args {
  (arg1: string | arg2: string);
}
```
Now, if this interface is used as a function parameter:
```typescript
function command(params:args) {
  //do something
}

let obj: args = {arg1: "foo", arg2: "bar"};
command(obj);
```
The following code snippet should throw an error, since the two properties `arg1` and `arg2` cannot coexist in the same object.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #14094

**Comment by weswigham** [comment]
OP: This is already possible. You just want to use a pattern along the lines of

```ts
type Arg1 = { arg1: string, arg2?: undefined };
type Arg2 = { arg1?: undefined, arg2: string };
type args = Arg1 | Arg2;
```
Then your example,
```ts
function command(params:args) {
  //do something
}

let obj: args = {arg1: "foo", arg2: "bar"}; // should error right here, as this literal isn't exactly one of the args object types
```

**Comment by akshgpt7** [comment]
@weswigham  I agree this is a possible workaround for lesser number of arguments, but as the number of arguments increases, the following solution becomes much longer, complex and difficult to debug. 

In the use cases that I have mentioned, there is a need of much more properties than just two. Creating a separate type alias for each property will just make the code messier.
A separate feature would rather be more sensible for a larger number of properties.
As also mentioned in the discussion in #14094.
