### ISSUE TITLE
issue with React.SyntheticEvent<HTMLVideoElement>

### ISSUE THREAD

**Issue by jt3k** [microsoft/TypeScript#38125]
Friends! How do I fix these wonderful wavy underlines?
https://www.typescriptlang.org/play/?jsx=2&ssl=2&ssc=39&pln=2&pc=78#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAULhAHarwAWyLAJgDZYAasB5YIAYT7BcAazgBeOAAoA3nBjIoAcyzwAvgC5MVGADoAygE8WMDrukBRAG5YbAHgASAFQCyAGWFRCAcBEFcYAD4ASgUIuBVGOCS4YAJlAEINbV0YyhgAVygWegZk9U0dMzBkfNQsHjgAfnLsqr5kSyUYoyzK02rarC6SvRKgA

**Comment by AviVahl** [comment]
Use event.currentTarget: https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

**Comment by jt3k** [comment]
thnx
