### ISSUE TITLE
Array with string-based index allows numbers anyway

### ISSUE THREAD

**Issue by beltaurus** [microsoft/TypeScript#38127]
**TypeScript Version:**  3.8.3

**Search Terms:** array index string number allowed

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
interface my_array_t {
	[index: string]: number
}

let my_arr1: my_array_t = {}
// work with array notation (but still working on object!)
my_arr1["string"] = 7
my_arr1["test"] = 42
my_arr1[7] = 10					// This does not error out?!
my_arr1.new = 0

console.log(my_arr1)

let my_arr2: my_array_t = {
	"string": 7,
	"test": 42,
	7: 10,					// Also does not error out?!
	"new": 0
}

console.log(my_arr2)
```

**Expected behavior:**
The interface is meant to enforce a `string` index.
Therefor, I expect the transcompiler to error out when I'm trying to use a `number` anyway.

Offending lines:
```ts
....
my_arr1[7] = 10					// This does not error out?!
...
	7: 10,					// Also does not error out?!
```
**Actual behavior:**
The number is accepted without any warning or complaint.
The debugger shows that the number is just accepted and stored in the Object:
![image](https://user-images.githubusercontent.com/54114043/80042716-8646fb80-84b4-11ea-9b21-c340ec7e5b83.png)

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/v2/en/play?#code/JYOwLgpgTgZghgYwgAgLYE8D6cpTlsZAbwCgBIAbVABMIAPALmQGcwpQBzAXSZAFdUAI2gkAviRIAbCIQzZcARiZyceAsgC8xcQHodyAO4B7KAGtDwMAAtkq-MhBGwcMMCMhkACkF9CrYJKShiamnMju4YIAVhAIYACEAJQkKooUAESs7CAc6VyayADsKViqChmQrHkFACwATCXyUOWF+VoKAAxk3d16yAAqVsDMyNRGECOOhNBQJuG+APzxjWUAdCAQBgUdEgjuzEbSq5JGHJ6pzclSMmiluHXKd2qYhFqkZJlsnOlMhQA05HSlTAP2Q9QBZEKTE6fx6PT6AEFJAdRuNJk5kDM5kZFssPhsDKCduISHsQAcjiczhc6okgA)
**Related Issues:** 
None

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Numbers coerce safely and predictably to strings in property key positions in JS, so this is an allowed coercion.
