### ISSUE TITLE
Class field initialisation does not show completion list

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#38138]
**TypeScript Version:**  3.8

**Search Terms:**
field intellisense 

![Resolving Edits3](https://user-images.githubusercontent.com/1106823/80134528-ca123180-8596-11ea-86f1-f32edfe3678b.gif)

**Expected behavior:**
When I type `private x = un...` I expect a completion list so that I can select `undefined`

**Actual behavior:**
There is no completion list.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200422#code/LAKAxgNghgzjAEAxA9s+BvUp4-mZAdjAC4BOArmMcqQBQCUGWIur8AblKfAB7wC88cgQAmAUwBmASwJiRAbngB6JfGQBrKAE9mrAL67cAB1JTOxMfAmoGTFmxydufQcPHTZC5ao3bsuAxB-HBMzKAt4ACMuASFg+FA9IA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/35180

**Backstory**
This has been a problem as long as I can remember. I've been too lazy to report it hoping it will get fixed by someone else.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
