### ISSUE TITLE
URLSearchParams needs keys and values

### ISSUE THREAD

**Issue by mjackson** [microsoft/TypeScript#38139]
**TypeScript Version:**  3.8.3

**Search Terms:** URLSearchParams

**Code**

```ts
console.log(new URLSearchParams().keys())
// or
console.log(new URLSearchParams().values())
```

**Expected behavior:**

No error

**Actual behavior:**

Error: Property 'keys' does not exist on type 'URLSearchParams'

**Playground Link:** https://www.typescriptlang.org/play/#code/MYewdgziA2CmB00QHMAUZYHcAEBVASgDIDKsAhgE7AAWACpWQLYSoCU8A1rAJ4uusBYAFAB6EdhAVhoSDARI0GHARLkqdBszbwAbmWgBXWH1ZA

**Related Issues:** None

**Comment by mjackson** [comment]
I'd be happy to dig in and fix this but I'm not sure exactly how. It looks like lib/dom.d.ts is automatically generated using TSJS-lib-generator, and in fact [the comments are already there for the `keys` and `values` properties of `URLSearchParams`' iterator interface](https://github.com/microsoft/TSJS-lib-generator/blob/1ba0ad73a975def78445ed4fd49eabfb7788eff6/inputfiles/comments.json#L1818-L1819), but for some reason the declarations don't show up in lib/dom.d.ts.

Where is the right place to fix this?

**Comment by MartinJohns** [comment]
> but for some reason the declarations don't show up in lib/dom.d.ts.

They're part of `dom.iterable.d.ts`: https://github.com/microsoft/TypeScript/blob/9c71eaf59040ae75343da8cdff01344020f5bba2/src/lib/dom.iterable.d.ts#L98

Your code should work if you add that to your libs.

**Comment by eps1lon** [comment]
> Your code should work if you add that to your libs.

Correct. Adding `dom.iterable` to [`compilerOptions.lib`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) in your `tsconfig` should solve this.

**Comment by mjackson** [comment]
Confirmed. Adding `{ "lib": ["dom.iterable"], "downlevelIteration": true }` to my `compilerOptions` did the trick. Thanks!

**Comment by DanielRosenwasser** [comment]
We really need to get better at suggesting adding certain `lib` options.
