### ISSUE TITLE
Generic rest parameters can't be combined with additional arguments

### ISSUE THREAD

**Issue by matthewvalentine** [microsoft/TypeScript#38134]
**TypeScript Version:**  3.9.0-dev.20200422

**Search Terms:**
Rest, variadic, tuple, function, generic

**Code**

```ts
// Let's say I want to make a decorator. It takes in a function fn and returns one that
//  1. Takes an array of fn's first argument, rather than just one
//  2. Then takes an extra argument before the rest of fn's parameters
//  3. Then takes the rest of fn's parameters as-is.
// And let's say we already have a decorator that does 1 & 3, so we just want to insert
// that extra argument. Coding it is easy! Typing it is not.
//
// Though it presents slightly differently, the error seems to stem from tuples getting 'blurred'.
// They turn from R into R[number][] or from Parameters<F> into Parameters<F>[number][],
// which is similar but makes every parameter type into a union of all of them. 

// ATTEMPTS THAT DO NOT WORK
// Using generic rest argument
function change1R<T, R extends any[]>(
    fn: (t: T, ...rest: R) => void
) {
    return (ts: T[], ...rest: R) => fn(ts[0], ...rest);
}

function change1Add2R<T, R extends any[]>(
    fn: (t: T, ...rest: R) => void
) {
    // ERROR: R[number][] is not assignable to type R
    return change1R((t: T, x: number, ...rest: R) => {
        console.log(x);
        fn(t, ...rest);
    });
}

// Using generic function type for Parameters
function change1F<T, F extends (...args: any[]) => any>(
    fn: (t: T, ...rest: Parameters<F>) => void
) {
    return (ts: T[], ...rest: Parameters<F>) => fn(ts[0], ...rest);
}

function change1Add2F<T, F extends (...args: any[]) => any>(
    fn: (t: T, ...rest: Parameters<F>) => void
) {
    // ERROR: Property 0 is missing in type any[] but required in type
    // [number, ...Parameters<F>[number][]]
    return change1F((t: T, x: number, ...rest: Parameters<F>) => {
        console.log(x);
        fn(t, ...rest);
    });
}

// Using both together
function change1B<T, R extends any[], F extends (t: T, ...rest: R) => any>(
    fn: F,
) {
    return (ts: T[], ...rest: R) => fn(ts[0], ...rest);
}

function change1Add2B<T, R extends any[], F extends (t: T, ...rest: R) => any>(
    fn: F,
) {
    // ERROR: Property 0 is missing in type any[] but required in type [number, ...R[number][]]
    return change1F((t: T, x: number, ...rest: R) => {
        console.log(x);
        fn(t, ...rest);
    });
}

// ONE THAT WORKS
// Using complicated type inspection
type Head<F> = F extends (head: infer Head, ...tail: any) => any ? Head : never;
type Tail<F> = F extends (head: any, ...args: infer Tail) => any ? Tail : never;

function change1C<F extends (...args: any) => any>(
    fn: F,
) {
    // If you don't explicitly specify the return type here, then it will be inferred as 'any'
    return (ts: Head<F>[], ...rest: Tail<F>): ReturnType<F> => fn(ts[0], ...rest);
}

function change1Add2C<F extends (...args: any) => any>(
    fn: F,
) {
    // If you don't explicitly specify the return type here, then it will be inferred as 'any'
    return change1C((t: Head<F>, x: number, ...rest: Tail<F>): ReturnType<F> => {
        console.log(x);
        return fn(t, ...rest);
    })
}
```

**Expected behavior:**

The first attempt above (or others) should work. At least, even if there are different errors, the type `R[number][]` should not appear in any circumstance.

**Actual behavior:**

The errors encountered are written above. In general, the error seems to stem from tuples getting 'blurred'. They turn from `R` into `R[number][]` or from `Parameters<F>` into `Parameters<F>[number][]`, which are similar but make every parameter type into a union of all of them. Then this type mismatches with the actual parameters type, producing the error.

**Playground Link:** 

[Link to Playground](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200422&ssl=1&ssc=1&pln=85&pc=2#code/PTAEBkFMBcHIGdTwIYE9QElQHdkDtpRoB7UAW2QGtJRlQATSAY2ICdkTWA6TQ6KyIgCWeWqABmAVzxNoQ4qPGj89UKxiTWeRAprQAFhwCwAKBChQARh4AVAYny1W7dMXES8CCUNbxCyVgBzSTJIAgAaNQ59SFYiQ1EAK0k-UF1Tc1AAJlsY0X5qB1FIAA9odidg0IJQACNIcTY9GLVBQjcPLwAHAORQ6Fj4DLBQAGZcsKJ7eJp1VI6lbt7+wdp4AFoheC5h0ABBPFUAGxgvFHRsGmQj9WR6dEMANyuGZjYONniOBmJBK1AAGRjSLwUiXUDJVK4GokUAieCxaC7AzfUrlOgBKphaA8ADCxHoIkCcMIW1AkGQ8FQAEJQDZUF0iSS4Yg8MQccNdjZ9MRJIF9MyunNsYh4EchPzoEd0ITxOJYtjpZEDDRYqxPgjIGRELC-FqJOqyERJF0TohAjA5HhibBakdNOp6LAdmYwNzIOhoJpFIbQAAlOEEUh+gDaeBC9VYAF0Q1G0nFxL6AArLGCDAA8ADEAHyB2Ep9grXxZ7NhiOxGNR8K7bD6IRMAVk+BCMhCI4BOqSQgUQrk56sdA9QtpuLQBk0ESwujSeSiDrXI5pdwqsg8Uy7PY2GwAUQAskmbABlOkACU3oAAIgB5UAAOSvNlAAHUr36ANK7ACqzetoAteFietWlSTEQmxUwpBkOQFFABt8AtSw-XTGxIgDNEwnoIpUFjbMAApTAsCwlAALlAXDoFIlDQC4Gi5go-0AEpQAAXlzR5iCEehTCYgBvAjCPUL0tDI6B4Eo2NIhorg6NIv0mNYjxyPgEMAAYq2o2i2gYgBuUwAF91xMSDZFnWCEgQvZ6HoLIkKotCygwrCcPwkxCI8UjyMoyTNL8WT5LYjiuJMXj+Iscxtz9P1X1kssyEjSsWVANl-HgZtAjwZA7T0Ugxy6Gg-VC1ohNEODrUgRDcM8ulIhKUjwzi2JvOkto-JY3M+NctzCJYbRiBOLgjmIQJcJKHTCrcpRyKauixs6iw9NmgyTC-H9iX-QCmAkaQTJg3KaEaOICz6EchiM7boJK8zyszZDIkzckHMORBcKkzExNoPBsKjfyPtQPDCpIkSvI05rfNAI6i3gEsfvYzjuNADq3ME70RPemwJJBmTwdTAZixzH7JtE1T1KkmbdJMJaIPO0zSosqyshuqj7vQp6yNeoJ3vwL6fq5-65vcoHqsxlrseHXGofxtrQFhoKQv58LIui8H1Ty1gx1AFTEtbVKmREIhx1+2NO0IdQAEdJB8SBVD1vbCvMWLIyaiGTpLB2K1jKNCuR4Taeuyr6Ko2qkvLVhppF53xehqXEa6iwetBfrBuG0bydjoi8Cm4W-FmtyFvJynXVAb8mVqdkBRIC0VVYKmoJpq7LAAIVu-0HoGVmuYx5nHswwWqNJkW5Kl3mXImvBSMzatgoRr2NGEpTxJJnz6MHhTCeUtSw+z-PDOMi6zPg8rLOspu7NbxzDfUru257qq+6X1qFOHgGx9ACf4ZjsKwAiqK-VIpMVcROgTWZJtarUDPrPKF9jatHNpba2+QDZu1DiDUM9V4oexnsVfeZVLCZn9sDIOaDGpZ2Xj9D+XV459UgANIaI0c5p0JpvaA9D5qLUMuYGwJ5tygCvLebhnDzwvnfIeFaTIWBkFNPWDgVsIETm0HlHaeBTB7VACeCk9ASwsVfmfVmuEYh3FIiIeUcQ1F3CavwNspEuY80+qAAA-Ko9RoA6qQH7OTFRdg2yaOYtolmN99H0CsZ9Jqb1DF4GMXSZAbYbHoAcZ4xcLi3E72pjBX2lhcRZh0TfdmgROafRiXzUe49J5yzcuYDA7hUC8h+J4QgpRJFMCEFKdA8AFFCHEJ6Fo3sEGQJiOoZUeRmTYDbIueogZjGOjWKAWAXNYCYJRvPRxdxXaL1BgHKJRxoayVnngekeVvG5jXsTJhbDlpnVrqk+uR8sgZKvufF6NFQm-QKSPQigM35T3IeUyp1T6AKFgHUkoDSmnSiQG0jpMwiooxUX0yAAzJhNJwCMuociJkyMpNM2Z8yfb11xPgpZGicw1TqiHJhlENlbP9DsvZkADnT35m5ShidaEp3GgJHZiloAnNToRBa+lTBAA)

**Related Issues:** 

Hard to say - possibly https://github.com/microsoft/TypeScript/issues/35154 ?

**Comment by ahejlsberg** [comment]
This is a known design limitation. We'd need the ability represent and reason about tuple types such as `[number, ...R]` where `R` is a type parameter `R extends any[]`. We currently require the rest part of a tuple to be an array type and that's why you're seeing the "blurring" to `[number, ...R[number][]]`. It would be nice to lift this restriction, but it's not trivial.
