### ISSUE TITLE
Result of { ...Array<T> } is assignable to Array<T>

### ISSUE THREAD

**Issue by abliarsar** [microsoft/TypeScript#38137]
**TypeScript Version:**  3.8.3

**Search Terms:** array, object spread.

**Code**

```ts
const fn = (wut: Array<number>): Array<number> => ({ ...wut})

fn([]).map(() => 1) // No type error, but runtime will crash
```

**Expected behavior:** Error
**Actual behavior:** No error

[Playground Link](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAZmGBeGAKA7gVygLhgQQCdCBDATwB4xMBbAIwFNCA+ASjyNMuvqeeX6oA3jAB04rFAC+rALAAoBQlQBtALqtRNEgAdUqVgJgBGQwHozMAKLEQhIA)

**Comment by MartinJohns** [comment]
Duplicate of #34780.
