### ISSUE TITLE
keyof incomatible with function interfaces

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#38131]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

keyof function interfaces

**Code**

```ts
interface DoSomething{
    (x: number): boolean;
}

// Can happen if you're applying mapped types recursively.
type ReadOnlyDoSomething = Readonly<DoSomething>;

function doesSomething(_x: number) {
    return false;
}

const assignGood: DoSomething = doesSomething;
const assignBad: ReadOnlyDoSomething = doesSomething;

assignGood(5);
assignBad(5); // TS2349. Type has no call signatures.
```

**Expected behavior:**

assignBad(5) invokes doesSomething.

**Actual behavior:**

TS2349. Type has no call signatures.

**Playground Link:** 

https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=16&pc=54#code/JYOwLgpgTgZghgYwgAgCIHsDK6C2EwAWoA5gN4BQyVyAFAB4BcyIArjgEbQCUT766AGwhwQAbnIBfcuQD0M5AGERyAnAAOaiCGTAYyAJ7oWAcigp1agfpLIcFiABNkYfZoDOyMwhZQ3wAG4QVgB05C6ayABKwg4A8iBWGNh4hDYAvFEx6An6ADxJuPhEIMQAfOLkMCwgCGDA2cgO6BBuyUUkNAD6jMxsnFBcyBTUnvg+2vACbhDiUuQI2W5gyHBufsQgAOL8DkwFKcXEyBlNLW2pJeILIEsra8AbAEJwu5kv8YlYhRdHJ82t30OFVW6y2OxoAFYuOIQQ8QM8HJDocg5MgACqYABMAGYACwATmC6NcKFUHhA6GQCDgAgEyFBcDAPhawSAA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `Readonly` is a mapped type and mapped types intentionally don't retain call signatures.

**Comment by kwasimensah** [comment]
Note, this is a blocker for trying to have an immutable type.

```ts
interface SettingDependingOnState {
    (state: State) => Setting;
}

interface Options {
    param: string;
    settingDependingOnState: SettingDependingOnState;
}

type Immutable<T> = {[P of keyof T]: Immutable<T>}

type NoLongerHasCallback = Immutable<Options>
```

**Comment by nmain** [comment]
> Note, this is a blocker for trying to have an immutable type.

There are some ways around this.  Check out `DeepReadonly` in https://github.com/piotrwitek/utility-types for one example.
