### ISSUE TITLE
`value: T` is not assignable to `Exclude<T, null>` after passing `value !== null` check

### ISSUE THREAD

**Issue by likan999** [microsoft/TypeScript#38140]
**TypeScript Version:**  Nightly

**Search Terms:**
typescript nullness inference

**Expected behavior:**
1. After nullity check, it should infer value is not null, thus assignable to `Exclude<T, null>`;
2. When `T` is not nullable, should be inferred not to take the nullable branch, therefore the return value should be assignable to `U`.

**Actual behavior:**
```
Type 'T' is not assignable to type 'Exclude<T, null>'.(2322)
```
and
```
Type 'U | null' is not assignable to type 'T extends null ? U | null : U'.
  Type 'null' is not assignable to type 'T extends null ? U | null : U'.(2322)
```

**Related Issues:**
No, but I might miss something because there are 3000+ bugs related to null.

**Code**
```ts
function f<T>(x: T) {
    if (x !== null) {
        const y: Exclude<T, null> = x;
    }
}

function g<T, U>(x: T, y: U) {
    const z: T extends null ? null | U : U = x === null ? null : y;
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function f(x) {
    if (x !== null) {
        const y = x;
    }
}
function g(x, y) {
    const z = x === null ? null : y;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200422&ssl=8&ssc=67&pln=8&pc=66#code/GYVwdgxgLglg9mABMAPAFQHwAoAeAuRNASkQG8AoRKxGYRXRAQgF5nEwQAbTki6-xBAQBnKIgCeBAKI4InEABMApugA07LpwyI2OANyVqAX3InyoSLASIA5msQBVbPkLrJj3oapCwoxAC8CNEQlHCglMAVhDW5EAH4YzkQAH0dEAgcdRBwdVkT4-IJxAxMgA)

**Comment by likan999** [comment]
Original bug report mixed two issues together, now make them two test cases.

**Comment by RyanCavanaugh** [comment]
We'd need negated types to handle this kind of narrowing
