### ISSUE TITLE
In assignment Type Union is resolved as Intersection  

### ISSUE THREAD

**Issue by askirmas** [microsoft/TypeScript#38159]
**TypeScript Version:**  Nightly

**Search Terms:**
Type Union, Type check during assignment
**Expected behavior:**
Some error i.e.
```
19:7 - error TS2339: Property 'c' does not exist on type 'tAB'.

19 c: false,
``` 
**Actual behavior:**
exits with status 0

**Related Issues:**

**Code**
```ts
type tAB = {
  a: string
  b: number
}
type tAC = {
  a: string
  c: boolean
}

type tUnion = tAB | tAC

//@ts-ignore Type '{}' is not assignable to type 'tUnion'
const empty: tUnion = {}

//No ts-error but should be
const union: tUnion = {
  a: '',
  b: 0,
  c: false,
}
//@ts-ignore  Property 'b' does not exist on type 'tAC'
union.b


```

<details><summary><b>Output</b></summary>

```ts
"use strict";
//@ts-ignore Type '{}' is not assignable to type 'tUnion'
const empty = {};
//No ts-error but should be
const union = {
    a: '',
    b: 0,
    c: false,
};
//@ts-ignore  Property 'b' does not exist on type 'tAC'
union.b;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200423&ssl=15&ssc=28&pln=15&pc=1#code/C4TwDgpgBMCCBCUC8UDeAoKUCGAuKAzsAE4CWAdgOaZQBG+5ArgLa0THoC+6okMsAYWRoaeQiQrUsAY3y0A9vIA2EbOS7oe4aMACq5UvPLC4iAD78BmgPTWAAsAIBaUpXLzi0ACraoAclROPyhSAih3YBwCAldybFoVGHkYXz89AyM-dGkjIigIZjBQfHTDYxRAm2sAOWTHJ3ZiDzpGSIIAC3lGJQATOghs3MjGDPIS-TLhDCwxPz8AGhp6KAAGRZl8ADNsJQIIRe5bB2dYj2goAAUmyGJQf1pgnvkIMIj8gA9QyKMUvjTBLIjMoAOlomiAA)

**Comment by RyanCavanaugh** [comment]
Unions are not mutually exclusive. You have a valid `tAB` and a valid `tAC`; no type violation has occurred.

**Comment by askirmas** [comment]
I see that they are exclusive - working like operator `XOR` or JsonSchema's `oneOf`
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=24&pc=1#code/C4TwDgpgBMCCUF4oG8BQUoEMBcUDOwATgJYB2A5qgL6qiQwBCiK6UARrqQK4C2bEhaqlrhowAKqliAe1LM4UAD6NhAY1kEoXKbNwSdcpGgw4oAcjMAaVhygAGazVTEAZlAAUZtmahktBgEpWAHpgmFEoAAsyYCw8KHVSTW0ZUj0GVlcPMwATHz8U2SCMDFCoAAVCaUhCUHM8qBzpCHjSaViIAA9iTVlw+jNSCAA3ATMAOlYMQtJxnNQgA

```typescript
type tA = {
  a: string
}
type tB = {
  b: number
}

type tUnion = tA | tB

const union: tUnion = {
  a: '',
  b: 0,
}

if ('b' in union)
  // type hint as const union: tB
  if ('d' in union)
    //TSError: Property 'd' does not exist on type 'never'.ts(2339)
    union.d
```

**Comment by askirmas** [comment]
[https://en.wikipedia.org/wiki/Union_type](https://en.wikipedia.org/wiki/Union_type) also thinks that  better to have `XOR`  rather than mathematical union

**Comment by askirmas** [comment]
@RyanCavanaugh so it is not working as intended

**Comment by askirmas** [comment]
How to reopen it?

**Comment by RyanCavanaugh** [comment]
@askirmas This is the intended behavior; truly it is.

**Comment by askirmas** [comment]
So please explain why here type resolved to `never`
https://github.com/microsoft/TypeScript/issues/38159#issuecomment-619108680

**Comment by rictic** [comment]
I don't think you meant to at me, but consider: https://www.typescriptlang.org/play/#code/C4TwDgpgBMCCUF4oG8CwAoKUCGAuKAzsAE4CWAdgOYYC+GokMAQoihlgEb7kCuAthwjFaGeuGjAAquVIB7cqzhQAPsxVQAFEoBkzAJSj0AY3lEoPGfPxTLCpGkw58AcmcAadlC5QADB-R06BikAGaazhzOUBTmtgaOAPQJMOJQABYUwDgEUCbkZhZy5NZMnqHh2FExhfLxWFhJACoAygCixMSyxPgACp2QxKBQzpVQACayEDnkslkQAB6kZvIpjM7kEABuQs4AdMAEGgBMAMwnAJx19TXku9hAA

**Comment by askirmas** [comment]
Oh, miss in mention, sorry.
I know that `OR` pattern - just a bit up https://github.com/microsoft/TypeScript/issues/38159#issuecomment-619112350. My question in `XOR` that doesn't working in assignment statement
