### ISSUE TITLE
Generic default is useless

### ISSUE THREAD

**Issue by StNekroman** [microsoft/TypeScript#38158]
I have method:
```
class SomeClass {
//...
    public static giveSomething<T = MyInterface>() : T {
    }
//...
}
```
When I invoke it without explicit declaring type
```
function returnData() : string {
    return SomeClass.giveSomething();
}
```

I expect to have error about types mismatch.
But TypeScript compiler accepts that as it is, without complaining.
I want to use generic defaults in order to create some sort of "default type" validation,
when generic method is called without providing types.

In other words, I expect next:

```
function returnData() : string {
    return SomeClass.giveSomething(); <-- error, by default
}

function returnData2() : string {
    return SomeClass.giveSomething<string>(); <-- ok, type is declared as "string" explicitly
}
```
I hit this issue with return types. May be with input parameters this works.

**Comment by StNekroman** [comment]
Currently, TypeScript compiler works out the return type from caller side.
But I expect that default type will be "strict" until other type is not provided explicitly.

**Comment by RyanCavanaugh** [comment]
If this is the behavior you want, a generic default is the wrong concept.

**Comment by StNekroman** [comment]
Working as intended?
Then what is the point of using generic defaults?
Currently, on return statement compiler picks any type, but not default.
It just ignores default. Then who needs that default value, if nobody looks on it?

**Comment by RyanCavanaugh** [comment]
A default only applies when there are zero inference candidates; any potential candidate (including from a contextual source) will be used in place of the default.
