### ISSUE TITLE
Allow direct property check `if (x.a)` to work and narrow type if at least one type in `typeof x` has `a`

### ISSUE THREAD

**Issue by ashmind** [microsoft/TypeScript#38156]
## Search Terms

condition property if in guard 

## Suggestion

I would like the following to work:
```typescript
function f(x: { a: string }|{ b: string }) {
    if (x.a) {
        // x should be { a: string } here
    }
}
```

## Use Cases

This is very common pattern in JavaScript, so when rewriting some of my JS code to TypeScript I often have to change this.

E.g.
```typescript
function logError(e: Error|TaskError) {
    if (e.fromTask) {
        // TaskError, log fromTask
    }
    else {
        // other error, simple log
    }
    ...
}
```

I can rewrite this in two ways.

**First**
```typescript
if ('fromTask' in e)
```
This has two issues:

1. It does not check that at least one of union types has `fromTask`, so if I made a typo (`fromTsk`) it would not be found.
2. It looks unnatural -- there is probably some JS pattern that recommends this over a shorter check, but I haven't seen it used much

**Second**
```typescript
function logError(e: (Error & { fromTask?: undefined })|TaskError)
```
This works, but feels really artificial -- it does not give any information that previous signature didn't have, and the only purpose is to work around the `if` error.

### Union
```
interface I1 { a: string }
interface I2 { b: string }
interface I3 { a?: string; b: string }

function f(x: I1|I2|I3) {
    if (x.a) {
        // type of x should be I1|(I3 & { a: string })
    }
}
```

### No such property
```
interface I1 { a: string }
interface I2 { b: string }

function f(x: I1|I2) {
    if (x.c) { // should fail to compile as `c` is not present on either I1 or I2
    }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; the proposed code isn't typesafe and we intentionally want you to opt-in to the "obvious what is going on" `in` operator if you really intend to do this.

See also https://github.com/microsoft/TypeScript/issues/34590#issuecomment-546150761

See also #14094
