### ISSUE TITLE
Plan for making syntactic classification consume less memory

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#3816]
Syntactic classification is slow in VS because the JSON string representing the classifications is too big. It classifies pretty much every token in the file. I was talking with @CyrusNajmabadi and we have an idea for how to reduce this string. Here's the idea:

* Provide only the classified spans that differ from what the lexical classifier produced.
* This means we need the lexical and syntactic classifiers to both be running.
* This leads to color flashing.

So to fix this, we have to fundamentally solve the flashing problem. The flashing is because sometimes the lexical classifier's results override the syntactic classifier's results. We have to ensure that doesn't happen. This leads us to steps 1 and 2 of the plan.

(1) Make three sets of tags on the VS side, where the kind of tag reflects which classifier returned the tag. Encode constraints that make sure semantic tags override syntactic, and that syntactic tags override lexical tags. Many of these tags would not be user visible, and would derive their colors from their corresponding visible tags.

(2) Make all the classifiers return the correct tags (the ones that are associated with said classifier).

This eliminates the flashing while both classifiers are running.

(3) The last step is for the syntactic classifier to run the lexical classifier to compare the output to its own results. Then it would *only* return the spans that are classified differently from lexical. This can be done in a way that is allocation free for the spans that are the same between the two classifiers.

**Comment by billti** [comment]
How much value does all this work get us over a simple TextMate like solution (i.e. lexical classification over lines with a scope stack)? We have to maintain a tmLanguage file anyway for our Sublime plug-in, and editors such as Sublime or Atom manage fine with TextMate based solutions.

Yes there are a few cases where you can get a token that isn't colorized perfectly, but this is rarely a cause of notable user confusion or complaint. I think we should be very practical and deliberate in assessing just how much complexity we want to add (with all the opportunity cost, bugs, and perf hit that implies), compared to the real value we get out it.

**Comment by JsonFreeman** [comment]
@CyrusNajmabadi and @vladima can weigh in on this, but my understanding is that even if we have one classifier for the entire file, it will still marshall a very large string over to VS, and the performance will be just as bad. And it will cause lags while typing, since it will be on the UI thread.

**Comment by billti** [comment]
I don't follow. Wouldn't this all be VS side where it already has the text buffer available? Same as Sublime and Atom, they don't give the buffer to the language service to colorize, they do the work themselves based on the editor buffer and the syntax specified by the tmLanguage file.

**Comment by CyrusNajmabadi** [comment]
"Yes there are a few cases where you can get a token that isn't colorized perfectly, but this is rarely a cause of notable user confusion or complaint."

Our own code doesn't work properly for this case.  Template literals screw this up for us.

it depends on our bar.  I would like our bar to be: we work well on real code.  

I don't want to give a solution that fails in real world code just because we didn't want to spend the effort to do it right.

**Comment by DanielRosenwasser** [comment]
> Yes there are a few cases where you can get a token that isn't colorized perfectly

@billti [half of the highlighting in my file is busted in `checker.ts` and `services.ts` in Sublime right now](https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/284). I don't think a paying user of VS would find something like that acceptable, and I would think that down the line, the other editors should also use our classifiers, provided that the experience provided can feel fluid.

**Comment by billti** [comment]
@DanielRosenwasser That issue was fixed already with a simple tmLanguage update (as you can see in the issue you linked to). A bug with a basic fix shortly after being noticed does not warrant a strong argument. Are there any actual specific limitations or problems with the TextMate approach you can provide?

**Comment by CyrusNajmabadi** [comment]
@JsonFreeman   

>  Make three sets of tags on the VS side

While i think this would definitely work, i also don't this it is really necessary.  I think we would have new tags for the lexical and syntactic systems.  And we would mark all of them as [Before] the existing semantic tags (i.e. all the type name tags).

**Comment by CyrusNajmabadi** [comment]
> "How much value does all this work get us over a simple TextMate like solution"

I'm curious why we're calling the "TextMate" solution 'simple'.  To me it is much more complicated than an actual syntactic classifier.  in order to get it 'right' you need to find a way to effectively support contect free grammars in a regexp-oriented framework.

Even if that was something supported well by TM solutions, you'd still effectively be building a parser/grammar in that world TS so that you can properly classify things.

This seems *orders of magnitude* more complex to me than just reusing the existing parser/syntax model *we already have*.

**Comment by JsonFreeman** [comment]
@CyrusNajmabadi 
> And we would mark all of them as [Before] the existing semantic tags (i.e. all the type name tags).

You're right, we only need two new groups.

I wholeheartedly agree with @CyrusNajmabadi that having two or more implementations of the grammar is not simple. Especially because the grammar changes frequently, this means a high marginal cost for grammar changes.

**Comment by billti** [comment]
@CyrusNajmabadi Because we already have to maintain a TextMate grammar for TypeScript for Sublime, Atom, etc...

Re your other comment about template strings - that's because currently in VS our lexical colorizer doesn't use a TextMate type solution. If you look at our colorization in Sublime, where we depend on the TypeScript language service to do NONE of the colorization, the colorizing is correct (see side-by-side below - this is VS *without* the syntactic colorizer).

![templatestring](https://cloud.githubusercontent.com/assets/993909/8631053/2fc2168a-2723-11e5-8e1b-8c8f55ab1f00.PNG)

**Comment by JsonFreeman** [comment]
Isn't it bad though that we have to maintain what essentially amounts to a second parser for these other editors?

**Comment by CyrusNajmabadi** [comment]
> Because we already have to maintain a TextMate grammar for TypeScript for Sublime, Atom, etc..."

But we already maintain a better grammar/tree already for tsc, typescriptServices, and all other features as well...

The tm solution seems necessary because we're plugging into systems that only support that more complicated system.  For systems that aren't so limited, i'd far prefer we just use the actual correct single tree that we use for literally every other feature in the LS :)

**Comment by billti** [comment]
> i'd far prefer we just use the actual correct single tree...

Which is the point of my concern. I'd far rather we just use a single source of truth also. But that doesn't align with the original proposal of:

> "This means we need the lexical and syntactic classifiers to both be running"...

> "Make three sets of tags on the VS side, where the kind of tag reflects which classifier returned the tag"...

> "Encode constraints that make sure semantic tags override syntactic, and that syntactic tags override lexical tags"...

> "The last step is for the syntactic classifier to run the lexical classifier to compare the output to its own results"...

What I'm suggesting is we look at just how much value the complexity and perf/engineering cost of doing all this really buys us. I've not seen any argument yet (beyond anecdotal) that using **one** classifier, (as used by several other well known and very fast editors), is far too inferior a solution to consider.

**Comment by JsonFreeman** [comment]
All the ideas in the proposal related to multiple taggers and certain tags overriding others are based on how our semantic classifier works. And the semantic classifier works very well, and does the right thing, and is low cost. We have had good experiences with it. It adds teal coloring to all the types, and yet we do not think of that as over the top. Why not do the same with the syntactic classifier?

**Comment by JsonFreeman** [comment]
Also, the correct single tree argument does not undermine any of my points because only one of the classifiers I am talking about uses a tree.

**Comment by CyrusNajmabadi** [comment]
> that using one classifier, (as used by several other well known and very fast editors), is far too inferior a solution to consider.

Note: at the end of the day, we will definitely be using at least two classifiers.  Unless we want to get rid of semantic classification.  Something i would be *loath* to contemplate.  Type classification is already great, letting me know what are types, and providing an experience far more in line with C#/VB.  Indeed, in the future, i would like this to expand further.  That way users can say "i would like my functions to be colored X, my variables to be colored Y, etc.".


> What I'm suggesting is we look at just how much value the complexity and perf/engineering cost of doing all this really buys us.

Jason's approach is actually *very* simple.  He's just saying: allow each phase of classification to override the previous phase.  He was just diving into the particulars so we wouldn't lose the good conversation we had about this if/when we get around to actually going about the implementation.

His approach allows us to:

1. produce fast results. 
2. avoid any sort of 'flashy' experience.
3. produce accurate results.
4. produce advanced results.  

> I've not seen any argument yet (beyond anecdotal) that using one classifier, (as used by several other well known and very fast editors), is far too inferior a solution to consider.

IMO, losing semantic classification is far too inferior a solution to consider.  I do not want to lose my type classification.  I don't want to return back to C# 2003 levels of classification.  

> just how much value the complexity and perf/engineering cost of doing all this really buys us. 

The benefit of the approach specified is that there is *not* a lot of complexity.  Indeed, it works by leveraging the system that we have today.  But tweaking it to address the two problems we've seen with the current approach so far.  Specifically:

1. What he does with tags avoids the 'flashyness' problem that had previously with classification.
2. What he does with diffing prevents the issue with marshaling a large amount of data from the script side to the managed side.

**Comment by JsonFreeman** [comment]
Is there a way to do infinite lookahead in tmLanguage? I imagine there is not. If not, we would get all the infinite lookahead cases (like lambdas, generic calls, etc) wrong in our classifier.

If the tmLanguage approach is so good, then should we make the compiler use it - i.e. update the parser to use a parser generator, and plug in the tmLanguage file? That would seem to follow if we prefer the tmLanguage parser over the classification based on our own parser.

**Comment by mhegazy** [comment]
This is completed now.
