### ISSUE TITLE
TypeScript Bot's `sync release-X.X` fails

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#38174]
This is the first time we tried running it, so not super unexpected, but looks like we probably wanted to merge from `origin/master` instead of `master`.

https://github.com/microsoft/TypeScript/issues/37198#issuecomment-619274427

https://github.com/microsoft/TypeScript/runs/616943054?check_suite_focus=true

![image](https://user-images.githubusercontent.com/972891/80263798-ae666400-8646-11ea-9c17-7a4609057187.png)

**Comment by DanielRosenwasser** [comment]
This might've just been due to a merge conflict, in which case maybe we just want to always take in `master`?

**Comment by weswigham** [comment]
as in deleting the releases branch and force pushing master as the new release?

**Comment by DanielRosenwasser** [comment]
Ehh, maybe let's discuss later this week

**Comment by DanielRosenwasser** [comment]
It happened again for different reasons 

https://github.com/microsoft/TypeScript/issues/40124#issuecomment-692385792

```
Run git config user.email "typescriptbot@microsoft.com"
From https://github.com/microsoft/TypeScript
 * branch              master     -> FETCH_HEAD
 * [new branch]        master     -> origin/master
fatal: refusing to merge unrelated histories
##[error]Process completed with exit code 128.
```

**Comment by weswigham** [comment]
Fixed - the task was broken when it was changed to `checkout@v2`, since that, by default, does not include history.
