### ISSUE TITLE
Extract to function can use inline imports 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#38177]
**TypeScript Version:**  3.9.0-dev.20200423

**Search Terms:**
- refactor / refactoring
- extract to function / method

**Code**
For the TypeScript code:

`foo.ts`
```ts
export class Foo { }
export const foo = new Foo();
```

`index.ts`
```ts
import { foo } from './foo';

{
    const x = foo;
    console.log(x);
}
```

1. Select `console.log(x);` and run the extract to function refactoring

**Bug:**
This adds an inline import type for `Foo`:

```ts
import { foo } from './foo';

{
    const x = foo;
    newFunction(x);
}

function newFunction(x: import("/Users/matb/projects/san/foo").Foo) {
    console.log(x);
}
```

Instead, it should add the import of `Foo` to the existing import at the top of the file

**Related Issues:** 
- #37781
- #35078

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk
