### ISSUE TITLE
Parameter inference breaks type intersection

### ISSUE THREAD

**Issue by Ghirigoro** [microsoft/TypeScript#38183]
**TypeScript Version:**  3.8.3 (also tested with 3.9.0-dev.20200425)

**Search Terms:**
inference

**Code**
```ts
type Effect<T, M> = {
  // NOTE: The problem seems to be here somewhere. Getting rid of the
  // intersection `& M` below gets rid of the error.
  do?: (o: T & M) => void;
};

type Obj = {};

function create<T, M>(params: {
  methods: M;
  effect: Effect<T, M>;
}): Obj & M {
  return params.methods
}

const obj = create({
  // If the parameter below is inferred then the Obj type
  // breaks and the methods are no longer merged in.
  // If a type is given (e.g. `obj:any`) the methods work
  // as expected
  effect:{do: (obj) => {}},
  methods: {
    something() {}
  }
});

// This will be an error if the effect infers the parameter type
obj.something();
```

**Expected behavior:**
Functions in `methods` should be merged into the type that is output by `create` or an error should be generated if there is a problem with the types.

**Actual behavior:**
Function in `methods` are only merged if `do` in `effects` is defined with explicitly typed parameters and no error is generated.

**Playground Link:** [playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=28&pc=17#code/C4TwDgpgBAogZnCBjYAeAKgGigWQHxQC8UA3gFBRQD0VUAcgPLowBcU6AFtGAE4D2AIwA2EALZQAzhDESowPlAHQuPaBL6iIAdxUQAdFADiEYMACWAOwDmUHmYAmUPnDlcK1WpeAQeUlGb4LKAADADJcYMUIIT4tKCsTWTtHZ1doH34ePXd7PgB+NgAKPjZ0KHCcAEoiAgA3PgcAbjIAX2ayUEgoBgEAKyJSNrIyOABXC39AqCRVAENvDGx8QrBZnlnRCTZySk1gDj57LdxmyggEZGA2eEQURdw8ZpbKth7+itJ3VWBRniDV9abPR7A5HVrDJCBCTAJx9AYzCDzCCFHYeKAASRc+24aw2Jh8URicTMsksiB4qkc2KC2O6cM6EHcNEUcwA1rJZhYqVwoCDDhzVFALAoYtYCZoeAlHJZspRmZioLM5OBoCT4mZahAgoV9FYDMFBL0WJyQMFqrS+UcoFo+DxWUzaLNZBAAB6QFAQezuc63K4kXJFQ3VQgEEgtFqYdyW46oyjqEGWKyFaph9wtVqVdrMzhqrRmIRCKKKoIZW1QMxYnk+y7lizk2S0gF47w8ZWQMiGvTxkwcRPJxpAA)

**Comment by RyanCavanaugh** [comment]
The problem here is that you have no inference site for `T`, so `T` gets fixed to `unknown`, then this ends up with `M` getting `unknown` because of inference on the `obj` parameter. The straightforward fix is to just remove `T` from these declarations entirely. A more fleshed-out example might be something we could provide a better way to write a declaration for
