### ISSUE TITLE
TypeScript not recognizing the rootDir in another subproject package

### ISSUE THREAD

**Issue by YannickFricke** [microsoft/TypeScript#38197]
First of all, thank you for developing TypeScript! It's such a nice experience to work with!

**TypeScript Version:**  3.8.3 & typescript@next (tried with both but the problem exists in both)
**Search Terms:** tsconfig, paths, rootDir

**Background:**

I want to get rid of the circular dependencies so I can compile the libraries and publish them afterwards.

**Expected behavior:**
The rootDir should be recognized by TSC.

**Actual behavior:**
Before I start describing the actual behavior don't wonder about the repository paths:

- `/src/github.com/Botvy/BotvyNX`
- `/src/github.com/Botvy/botvy-nx`

I am using this repository and branch: https://github.com/Botvy/BotvyNX/tree/feature/pluginsystem

Since this is an open source chatbot I need to publish the developed and used libraries (in the `libs` directory) to NPM or another registry. Currently I am testing it with the `plugins` library (located under `libs/framework/plugins`).

Other packages within the repository which were generated with the same parameters (by NX (a handy tool for managing mono-repos)) are working fine (everything else in the `libs` directory).

But somehow I'm getting the following error

![grafik](https://user-images.githubusercontent.com/591450/80308562-02e91b00-87d0-11ea-8268-0694220726f3.png)

When you invoke TSC with the `listFiles` flag, it shows, that the required files are actually found (last 4 lines):

Command: `yarn tsc -p libs/framework/plugins/tsconfig.lib.json --listFiles`
Output:
![grafik](https://user-images.githubusercontent.com/591450/80309070-c66aee80-87d2-11ea-8b4e-52150a94e192.png)

As you can verify [here](https://github.com/Botvy/BotvyNX/blob/feature/pluginsystem/libs/framework/constants/tsconfig.lib.json#L7) the rootDir is set to the correct path.

**Comment by sheetalkamat** [comment]
This is configuration error.. Your program includes `.ts` files from other package and hence they need to be emitted and all files that need to be emitted need to be under the `rootDir` which is not the case for the files for which the error is given
```
c:/temp/BotvyNX/libs/framework/constants/src/lib/Services.ts
c:/temp/BotvyNX/libs/framework/constants/src/index.ts
```

**Comment by sheetalkamat** [comment]
You probably want to use project References to ensure that you are including built ".d.ts" file instead of source file
