### ISSUE TITLE
No error using keywords in dotted module names

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#382]
Reported originally on <https://typescript.codeplex.com/workitem/2540>

```TypeScript
module module.var.var {
    export var a;
}
```
Generated JS is invalid, but it's not a compiler error now.

**Comment by DickvdBrink** [comment]
It is an error on the TypeScript Playground now ("Identifier expected"), so is this something that should stil be open or do you want a better error message?

**Comment by danquirk** [comment]
The error message/recovery is pretty bad right now:

![image](https://cloud.githubusercontent.com/assets/7121557/6419863/d477c970-be75-11e4-9953-b5ec9049afa2.png)

Would be great if we can give the straightforward error description.

**Comment by mhegazy** [comment]
Closing for housekeeping purposes. The behavior outlined in the OP has been in place for over 18 month now and have not got any updates on this issue. Please file a new issue if an action is required.
