### ISSUE TITLE
Type not assignable for string literal in signature

### ISSUE THREAD

**Issue by WangHansen** [microsoft/TypeScript#38201]
**TypeScript Version:**  3.8.3

**Search Terms:**
string literal
string alias
is not assignable to parameter of type

**Expected behavior:**
No type check errors

**Actual behavior:**
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'tAlgorithm' is not assignable to parameter of type '"oct"'.
      Type '"EC"' is not assignable to type '"oct"'.
```

**Related Issues:**

**Code**
```ts
interface KeyStore {
    generate(kty: 'EC', crv?: string, parameters?: object, isprivate?: boolean): void;
    generate(kty: 'OKP', crv?: string, parameters?: object, isprivate?: boolean): void;
    generate(kty: 'RSA', bitlength?: number, parameters?: object, isprivate?: boolean): void;
    generate(kty: 'oct', bitlength?: number, parameters?: object): void;
}

type tAlgorithm = "RSA" | "EC" | "OKP" | "oct";

function generateKey(alg: tAlgorithm, crvOrSize: string | number) {
    return ({} as KeyStore).generate(alg, crvOrSize);
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function generateKey(alg) {
    return {}.generate(alg, "P-256");
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=11&ssc=41&pln=11&pc=48#code/JYOwLgpgTgZghgYwgAgNIQJ4GUwHsooDeAUMmcgOYQjRyQAUA1mBgFzIDkAogMIcA0yBFABuAfnYBnMFFAVBABzhQ4AWwiQokiclwAjAFYQEYQcEkLZIuhB17cuADYQ4IAJTsRuYABMA3KTkVDQqDMxsnADyqAAKAkKiOtKyIPLISirqmtrs+kYmZhZWNnYOzq4eyF6+AeSU1LRhLOwcAEpYAILxesBgzqlgABY6IACuqnrQispqGtA5uobGpsjmlsDWkKVOLu6e3v6BZMGNEEzNnLgm3b39FEMj45NQ05lzWjp5y5XVhwC+xGILAUKDAHUcFHwvUGqmQAF5kAAidodRHIAA+SN4aMxiOiMRxSKuYERAWIMFGIBMwFwIHqIRs6Aw9DgEPYYIhUKGqkEwhEkSgWGAAC8IFIZHIMcgxhNoG5kCQyAQwKMoHT6IQ-sg4JI0JgcPgIG4AHQnUJnVlpPkCoWitwBP5AA)

**Comment by WangHansen** [comment]
Another reproduction link: https://codesandbox.io/s/laughing-shockley-hlpr1?file=/src/index.ts

**Comment by MartinJohns** [comment]
`alg` can be one of four different string literals. Only two overloads accept a string as a second argument, but you pass the string `"P256"`.

This is not a bug, it's TypeScript protecting you.

**Comment by DanielRosenwasser** [comment]
This clearly shouldn't work given that `generateKey("EC", 128)` can be substituted with

```ts
({} as KeyStore).generate("EC", 128)
```

and shouldn't match any overload.

**Comment by WangHansen** [comment]
How about this?
```javascript
interface KeyStore {
    generate(kty: 'EC', crv?: string, parameters?: object, isprivate?: boolean): void;
    generate(kty: 'OKP', crv?: string, parameters?: object, isprivate?: boolean): void;
    generate(kty: 'RSA', bitlength?: number, parameters?: object, isprivate?: boolean): void;
    generate(kty: 'oct', bitlength?: number, parameters?: object): void;
}

type tAlgorithm = "RSA" | "EC" | "OKP" | "oct";

function generateKey(alg: tAlgorithm) {
  return ({} as KeyStore).generate(alg);
}
```

This still gives the error.
[Playground](https://www.typescriptlang.org/play/?ssl=12&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgNIQJ4GUwHsooDeAUMmcgOYQjRyQAUA1mBgFzIDkAogMIcA0yBFABuAfnYBnMFFAVBABzhQ4AWwiQokiclwAjAFYQEYQcEkLZIuhB17cuADYQ4IAJTsRuYABMA3KTkVDQqDMxsnADyqAAKAkKiOtKyIPLISirqmtrs+kYmZhZWNnYOzq4eyF6+AeSU1LRhLOwcAEpYAILxesBgzqlgABY6IACuqnrQispqGtA5uobGpsjmlsDWkKVOLu6e3v6BZMGNEEzNnLgm3b39FEMj45NQ05lzWjp5y5XVhwC+xGILAUKDAHUcFHwvUGqmQAF5kAAidodRHIAA+SN4aMxiOiMRxSKuYERAWIMFGIBMwFwIHqIRs6Aw9DgEPYYIhUKGqjcyBIZAIYFGUDp9EIf2QcEkaEwOHwEDcADoTqEzqyKG4An8gA)

**Comment by DanielRosenwasser** [comment]
Sorry to not also link to the more general problem earlier on (it would've spared you some time): #1805 has some explanation on why the pattern is currently not supported.

Though, since then, I can sort of imagine us doing better given some of the work that went into https://github.com/Microsoft/TypeScript/pull/30779.

**Comment by DanielRosenwasser** [comment]
However, I think that even with the ideas of #30799 incorporated, it wouldn't help you write the original code easily without a type assertion or duplicate overloads.
