### ISSUE TITLE
As operator in module and namespace issue

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3821]
I've debugged the other day and I tried out in TS source code to do:
```typescript
console.log((ts as any).SyntaxKind[node.kind])
```
instead of:
```typescript
console.log((<any>ts).SyntaxKind[node.kind])
```
And I got:
```
src/compiler/checker.ts(7085,33): error TS1005: ')' expected.
src/compiler/checker.ts(7085,36): error TS1005: ',' expected.
src/compiler/checker.ts(7085,62): error TS1005: ';' expected.
```

**Comment by danquirk** [comment]
I'm not seeing an issue on master?
```
> type a.ts
var bar = 'a';
console.log((bar as any).SyntaxKind[bar.length]);
> node .\built\local\tsc.js a.ts
> type a.js
var bar = 'a';
console.log(bar.SyntaxKind[bar.length]);
```

**Comment by tinganho** [comment]
@danquirk I think the bug is only for `namespace` and `module`.

**Comment by mhegazy** [comment]
this is a parse error, if it works in one case it should work for all others. i can not get a repro for it either on the latest build. i would say there is something else going on @tinganho that is not in your snippet; can you share more context.

**Comment by tinganho** [comment]
@mhegazy I just pulled down master and tried again. This issue seems to have been fixed.
