### ISSUE TITLE
Signature help not working on optional methods

### ISSUE THREAD

**Issue by madcapnmckay** [microsoft/TypeScript#38219]
I noticed that if I made a type a property that is a function and I made that property optional I lost autocomplete functionality on it when creating an instance of that type.

**TypeScript Version:**  3.8.3

**Search Terms:** autocomplete, optional properties

**Code**

```ts
export type Route = {
    // make this method optional
    routeWillEnter: (current: any) => any;
};

const SomeRoute: Route = {
  // autocomplete params on this method only appear if it's not optional
  routeWillEnter() {
    return {};
  }
};
```

**Expected behavior:**

<img width="404" alt="Screenshot 2020-04-27 15 34 43" src="https://user-images.githubusercontent.com/777858/80427479-b0296500-889c-11ea-924a-a18fb35d0f19.png">

**Actual behavior:**

Nothing happens.

**Playground Link:** 

https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcBKECuNUF44DeAUHKXAPTlwC2AhgNaowAWAlgM43AsQAmcEMDFYQAdrQA2JMlCw4A6qwkSAoqJxQAXHAAUAY0xQowddtqjEASji4AfHHOIA3EQC+LonrHt4AZQjUwBjYwNrBODaE0pQO2BBe1GAS3KhgtFC01JxiCGycgTz8YhKIDmAo6XCsAGZVMADknKIQ8ILCYpLSsiGKymoaOtbEZHDGMIaihO7Srm5OQA

**Comment by DanielRosenwasser** [comment]
I'm actually a little bit surprised that signature help even works in this context.

**Comment by DanielRosenwasser** [comment]
I think there is a larger work-item discussion to understand when we should be providing signature help.
