### ISSUE TITLE
Optional arguments due to multiple constructors are not considered when resolving rest parameters in generics

### ISSUE THREAD

**Issue by stephanemagnenat** [microsoft/TypeScript#38211]
**TypeScript Version:**  3.8.3 and nightly from the playground as of today.

**Search Terms:** `label:bug constructor rest parameter `

**Code**

```ts
class A {
	constructor(value: number);
	constructor(sKey: string, sValue: string);
	constructor(sKeyOrValue: string | number, sValue?: string) {}
}

function test<T, S, A extends any[]>(ctor: new (...args: A) => T, ...params: A): T {
	return new ctor(...params);
}

test(A, 3);
```

**Expected behavior:**
I would expect this to compile without error, because class `A` has a valid constructor with one argument of type `number`.

**Actual behavior:**
Error: `Expected 3 arguments, but got 2.(2554)`. It seems the compiler is not able to realise that class `A` has a matching constructor.

**Playground Link:** [Playground link](https://www.typescriptlang.org/play/?ssl=11&ssc=12&pln=1&pc=1#code/MYGwhgzhAECC0G8BQBIYB7AdhALgJwFdgd08AKANzBAIFMAuaTAgWwCNa8BKAblQ2z4iJchADStAJ6NceAJaYA5gBpoEAGrU6M-AsW9+WWcNJlxUgPJ5NNBmt1LoAHyasOeVRq20A-DvlKXIgAvkihSABmBJjEcljQOLS4ADwAKqoAyqrwtAAeiZgAJjBgmJIA2gC6AHxkxKSMmLQA7tBkAHSdYHiKEIywQQC81dDp0J3tAA7dYCx9cFyMqYioeLQ4BHiYTC3Q9eQT03izEAbhibhksKoAzAZAA)

**Related Issues:**  #37142, #29707

**Comment by jcalz** [comment]
This is a design limitation: type inference from a type with multiple call or construct signatures only happens against the last such signature. See #32418, #35641, probably others...

**Comment by ahejlsberg** [comment]
Meanwhile, it works if you write it like this, though you loose the descriptive parameter names:

```ts
class A {
	constructor(...args: [number] | [string, string]);
	constructor(sKeyOrValue: string | number, sValue?: string) {}
}

function test<T, S, A extends any[]>(ctor: new (...args: A) => T, ...params: A): T {
	return new ctor(...params);
}

test(A, 3);
test(A, 'foo', 'bar');
```
