### ISSUE TITLE
Fix diagnostic with "body block braces"

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#38225]
We have a diagnostic

```
Remove all incorrect body block braces.
```

Typically we say "block body" not "body block". Perhaps we could make it less confusing by writing "function body braces"

**Comment by a-tarasyuk** [comment]
I think this QF applied only for arrow functions, also there is QF all message

```ts
Diagnostics.Remove_block_body_braces
Diagnostics.Remove_all_incorrect_body_block_braces
```

Maybe make sense to point out in QF about arrow functions? Something like so

```ts
Remove braces surrounding arrow body
Remove braces surrounding arrow body from all functions
```

**Comment by DanielRosenwasser** [comment]
I like

```
Remove braces from arrow function body.
Remove braces from all arrow function bodies with relevant issues.
```

**Comment by DanielRosenwasser** [comment]
Eh, I mean, I don't _totally_ like them, but they'll do...

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Thanks

**Comment by rajatdiptabiswas** [comment]
Is this issue still available to be worked on?
If yes, would you kindly let me know what needs to be done so that I can try working on it?
