### ISSUE TITLE
conditional class types are incomplete

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#38221]
```js
class A{}
class B{}
class C{foo}

function test(bool){
    const x = new ( bool ? A : B )()  // x: A
    const y = new ( true ? C : B )()  // y: B
    const z = new ( false ? A : C )()  // z: A
}
```
only happens when classes have alike types
1.44.2

**Comment by mjbvz** [comment]
I believe the issue may be that `A` and `B` are structurally equivalent. Change them to:

```ts
class A { x; }
class B { y; }
```

And now `x` is `A | B`

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely
