### ISSUE TITLE
TS 3.9+ extends any and keyof generics regression

### ISSUE THREAD

**Issue by kitsonk** [microsoft/TypeScript#38238]
**TypeScript Version:**  3.9.1-rc

**Search Terms:** keyof generic extends any

**Code**

```ts
function invokeOrNoop<
  O extends any,
  P extends keyof O
>(o: O, p: P, ...args: Parameters<O[P]>): ReturnType<O[P]> | undefined {
  assert(o);
  const method = o[p];
  if (!method) {
    return undefined;
  }
  return method.call(o, ...args);
}
```

**Expected behavior:**

In TypeScript 3.8, this worked fine and the called type inference worked correct as well.

**Actual behavior:**

In TypeScript 3.9, the more conservative view of `extends any` disallows assignability of `O[P]` but cannot find any type to extend that would actually work.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200428#code/CYUwxgNghgTiAEYD2A7AzgF3lNaQwwC54AKZFYYgVxQGsUkB3FASngF4A+bXfDNRKmABuAFCiAZjTAYAlqniyUANyS0QAeRgA5JEgAOAHlHx4G+CAAeGEBQFQUATwA0J+AAUL128AHrHSBJmopwkSMQazvD6xO5RAHSJsADmaLGwUAC2IDYwaIYaANruALqcLMQASjlUMCgAKo76IAXFZfAAPvA0oBJKIMDwAN5uOHgEYSxipuSY8NkYABZIg+zwSIX6JdOKQSQAhAvLwGwjpqZwGLUo3RQgfSgDOwC+bpfX8znH8WBQEBBhBJJGCpKaiV6iWZYCR6DjDNwAI1gJAq8EwMCUyXh53g7zq8AAREiYASXuCxJDUHM4GgqBAsGslKp1FpdAYSDCkFEibACWCgA)

**Comment by DanielRosenwasser** [comment]
I guess the solution is

```diff
  function invokeOrNoop<
-   O extends any,
-   P extends keyof O
+   O extends Record<P, any>,
+   P extends PropertyKey
  >(o: O, p: P, ...args: Parameters<O[P]>): ReturnType<O[P]> | undefined {
    assert(o);
    const method = o[p];
    if (!method) {
      return undefined;
    }
    return method.call(o, ...args);
  }
```

Just want to confirm whether this is `Working as Intended` or if this feels like a regression. @weswigham @ahejlsberg @RyanCavanaugh

**Comment by kitsonk** [comment]
🤦 I should have thought of that, I tried a few other things and had some assignability issues at the call site, but that is a better type than `any` anyways.  Doesn't feel like a regression now, just a breaking change.
