### ISSUE TITLE
Dependency resolution issue when one module depends on pre-ts lib and parent project depends on ts lib?

### ISSUE THREAD

**Issue by jwheeler-gs** [microsoft/TypeScript#38233]
**Search Terms:**
Got, definitely-typed got version 9

**Code**
Typescript projects which have a dependency on the "got" library at major version 10 or newer and also a dependency on "openid-client"@3.15.0 fail to compile.

Openid-client depends on Got version 9. Everything compiles successfully if the parent project is also on Got version 9, but fails on version 10 or newer.

I suspect this is a problem due to the fact that got@10 and newer is a typescript module whereas version 9 and older depended on the definitely-typed definitions for got. This seems like a dependency resolution issue with Typescript. When compiling, it is using the type definitions for got@10 (via the parent project's dependency) even though the openid-client module clearly has dependencies on both `got@9` and `@types/got@9`.

Is this a problem that exists with all projects which have an overlapping dependency with a library that depends on a definitely-typed version while the top-level project depends on a native ts version?

**Expected behavior:**
Typescript should compile

**Actual behavior:**
Compilation fails:
```
node_modules/openid-client/types/index.d.ts:12:10 - error TS2614: Module '"../../../../../../../my-project/node_modules/got/dist/source"' has no exported member 'GotOptions'. Did you mean to use 'import GotOptions from "../../../../../../../my-project/node_modules/got/dist/source"' instead?

12 import { GotOptions, GotPromise } from 'got';

node_modules/openid-client/types/index.d.ts:12:22 - error TS2614: Module '"../../../../../../../my-project/node_modules/got/dist/source"' has no exported member 'GotPromise'. Did you mean to use 'import GotPromise from "../../../../../../../my-project/node_modules/got/dist/source"' instead?

12 import { GotOptions, GotPromise } from 'got';
```

**Comment by jwheeler-gs** [comment]
As a possible work around for now, adding the following to my tsconfig.json gets around this issue:
```
"skipLibCheck": true,
```
https://www.typescriptlang.org/v2/tsconfig#skipLibCheck

Apparently this is a known issue? Sounds similar to what is described on that page:
"A common case where you might think to use skipLibCheck is when there are two copies of a library’s types in your node_modules. In these cases, you should consider using a feature like yarn’s resolutions to ensure there is only one copy of that dependency in your tree or investigate how to ensure there is only one copy by understanding the dependency resolution to fix the issue without additional tooling."

Although their suggested fix is not applicable here since the library definitely needs to use one version of type definitions while the parent project uses a different version of type definitions.

**Comment by RyanCavanaugh** [comment]
This doesn't sound like a bug; TS is doing what you've told it to. It seems like one or more of the definition files need to be updated
