### ISSUE TITLE
Block scoped typing

### ISSUE THREAD

**Issue by hejkerooo** [microsoft/TypeScript#38244]
## Search Terms
block, scoped typing

## Suggestion

I would love to tell to TS `from this bracket to this bracket the type of this variable is Foo`

This feature works when used with `instanceof` operator but when using some libraries (e.g. [axios](https://github.com/axios/axios/blob/c120f44d3d29c8e822a92e1d6879b8b77be6b9dc/index.d.ts))
`instanceof` won't work there as `AxiosError` is not a value (it is an interface which doesn't exist during runtime).

Currently, we need to define a helper variable to cast this type.
## Use Cases

```javascript
if(err instanceof Foo) {
  // err is now treated as a Foo
} else if((err as any).isAxiosError) {
  // err is not treated as a AxiosError so TS will treat it as Error so I can't access other properties without casting
}
```

## Examples

```javascript
if(err instanceof Foo) {
  // err is now treated as a Foo
} else if(((err as any).isAxiosError) as AxiosError) {
  // err is now treated as a AxiosError
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment]
Isn't a custom type guard sufficient for this?
```ts
function isAxiosError(e: any): e is AxiosError {
    return !!e.isAxiosError;
}
```
