### ISSUE TITLE
TypeScript 4.0 should actually be 3.10

### ISSUE THREAD

**Issue by RyanLamanskyInsite** [microsoft/TypeScript#38248]
## Search Terms

TypeScript major

## Suggestion

Adopt "semver" practices and stay on 3.x until there's a breaking change to the external API.
This request is invalid if there are important breaking changes in 4.0.

## Use Cases

Some 3rd party tooling assumes TypeScript follows "semver" and has checks like ">=3.4.0  && 4.0.0" or "^3" to determine compatibility. Some of this tooling is rarely updated, so using TypeScript 4.x will add warnings or errors to uses of these tools that would otherwise have worked perfectly.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/14116
My search term was semver

**Comment by RyanLamanskyInsite** [comment]
Didn't think of that search term 🙄 

I think it's safe to assume that things haven't changed so I'll just close this.
