### ISSUE TITLE
Intl DateTimeFormatOptions Missing Properties

### ISSUE THREAD

**Issue by nikarc** [microsoft/TypeScript#38266]
Hi guys,

I'm using [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) to format some database dates into human readable format. TS is throwing an error:

```shell
Argument of type '{ year: string; month: string; day: string; weekday: string; hour: string; minute: string; dayPeriod: string; }' is not assignable to parameter of type 'DateTimeFormatOptions'.
  Object literal may only specify known properties, and 'dayPeriod' does not exist in type 'DateTimeFormatOptions'.  TS2345

    13 |         hour: 'numeric',
    14 |         minute: 'numeric',
  > 15 |         dayPeriod: 'short'
       |         ^
    16 |     });
    17 |     const date = new Date(eventDate);
    18 |     const [
```
I noticed that the TS documentation [here](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es5_d_.intl.datetimeformatoptions.html#day) does not reflect all the options present [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#Parameters)

I tried searching the issues but i did not see anything about this specifically. Is this known/intentional? Could I make a quick pr to add the options to the `DateTimeFormatOptions` interface, if not?

Thanks

**TypeScript Version:**  3.8.3

**Search Terms:**
DateTimeFormatOptions, DateTimeFormat

**Code**

```ts
    const dtFormatter = new Intl.DateTimeFormat('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        weekday: 'short',
        hour: 'numeric',
        minute: 'numeric',
        dayPeriod: 'short'
    });
```

**Expected behavior:**
`dayPeriod` is exposed in the `DateTimeFormatOptions` interface

**Actual behavior:**
Error is thrown because `dayPeriod` is not present in `DateTimeFormatOptions`

**Playground Link:**
[playground](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200429&ssl=2&ssc=2&pln=10&pc=4#code/LAKAxg9gdgzgLgAgCZwGIQE4FsCGc4CmGCAvAlAQO4ICSUcANgHQAieBAKgJZYHrZ4AFAHICUALQBVAMrCANAgDeoBKoQBPAjgwAuBMKgBXXhi5h5KtVmhwAFnuExbmOBZBrkOdQ6Mmzbj0oCAgBrJC8HJxcAtWdDXX1fIn85S1UsLiNCH2Nk81T3NXD1AAVkiCRI5wxXUABfAEoAblAgA)

**Comment by MartinJohns** [comment]
35865

**Comment by casey6** [comment]
@RyanCavanaugh I don't believe this is a duplicate as it's talking about adding missing parameters. The referenced ticket proposes using string literal types to match the exact values allowed, which would be a potential breaking change. I think that would be avoided here when adding these missing parameters.

**Comment by raymonschouwenaar** [comment]
I'm also experiencing a issue with the fact, `dateStyle` property is also giving an error.

In the MDN docs we can see the should exist in the `DateTimeFormat` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#Examples

**Comment by JorisWillig** [comment]
I am also encountering this issue, with the 'timeStyle' and 'dateStyle' options

**Comment by costasovo** [comment]
Same here with the 'timeStyle' !

**Comment by amychang0401** [comment]
same here with timeStyle + dateStyle ! Also one odd thing I found was
```
// SUCCESS with timeStyle and dateStyle 
new Intl.DateTimeFormat('en-US', {
  timeStyle:'short', dateStyle:'short'
}).format(date)
"11/2/20, 12:13 PM" 

// FAILED with additional `hour` option added
new Intl.DateTimeFormat('en-US', {
  hour:'numeric', timeStyle:'short', dateStyle:'short'
}).format(date)
VM788:1 Uncaught TypeError: Invalid option : dateStyle
    at new DateTimeFormat (<anonymous>)
    at <anonymous>:1:1
```

**Comment by dev99problems** [comment]
@amychang0401 seems like `one odd thing` happens because according to the [MDN Doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#Examples)

> dateStyle can be used with timeStyle, but **not with other options** (e.g. weekday, hour, month, etc.)

So while using **Intl.DateTimeFormat** there are 2 options — to use `dateStyle, timeStyle` **OR** any other options, like `hour, month, etc.`

**Comment by 64J0** [comment]
Bump, still facing this problem...

**Comment by 64J0** [comment]
After reading the [MDN docs](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) I think that this lack of properties is intencional because Safari doesn't support those configurations, like illustrated in the figure above:

![image](https://user-images.githubusercontent.com/50725287/108065387-ae53ac80-703c-11eb-8911-99325976af8f.png)

But idk, maybe it has other explanation.

**Comment by Whobeu** [comment]
Just noticed an issue with "fractionalSecondDigits". I am using Node v14.16.0 so there is support for it:

Object literal may only specify known properties, and 'fractionalSecondDigits' does not exist in type 'DateTimeFormatOptions'.

Typescript is 4.1.5

I'll work around it but just something else to be added to the library.

**Comment by lukepuplett** [comment]
Looks like `dateStyle` and `timeStyle` are supported in Safari 14.1 is browser support is the reason for the interface being mishapen.

**Comment by nstringham** [comment]
@RyanCavanaugh can you explain why this was marked as a duplicate

this issue is requesting that new fields be added to DateTimeFormatOptions

#35865 is requesting that existing fields be made more strict

**Comment by omonk** [comment]
Certainly a TS version issue: 
- [3.8.3](https://www.typescriptlang.org/play?target=7&ts=3.8.3#code/MYewdgzgLgBAJjAvDMBTA7jAkmKAbAOgBEBDKVAFQEsBbVAMRACcayAKAIlTAFoBzAEYcANDADeMKLVQBlKAE88qAFwwOEABbMoHGAF8AlEA)
- [4.4.2](https://www.typescriptlang.org/play?target=7&ts=4.4.2#code/MYewdgzgLgBAJjAvDMBTA7jAkmKAbAOgBEBDKVAFQEsBbVAMRACcayAKAIlTAFoBzAEYcANDADeMKLVQBlKAE88qAFwwOEABbMoHGAF8AlEA)
