### ISSUE TITLE
Ternary operator type inference with optional parameter

### ISSUE THREAD

**Issue by sajal50** [microsoft/TypeScript#38275]
**TypeScript Version:**  3.8.3

**Search Terms:** ternary type-inference

**Code**

```ts
function foo(bar ?: string) {
    const options = (bar) ? { bar } : {};
    // why is options inferred as { bar : string } | { bar ?: undefined }
    // and not { bar : string } | {} 
}
```

**Expected behavior:**
`options` to be inferred as `{ bar : string } | {} `

**Actual behavior:**
`options`  inferred as `{ bar : string } | { bar ?: undefined } `

**Playground Link:**  
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=5&pc=2#code/GYVwdgxgLglg9mABMOcAUAjAhgJ0QfgC5EBnKHGMAcwEpEBvAKERcQgTMTgAdYPEAvIky46+Bomx4AvomL1pAbmasA9KsQB3ABYBPRDBJde8MEcrAApjhyWAJoixH6k3HNLlKVRLIA+EqQJicDtLYEp7HxUWdUcwBzA4KAC3YjIKah9EfwVERmkgA

**Comment by ahejlsberg** [comment]
See #19513.

**Comment by sajal50** [comment]
Thank you for the explanation, @ahejlsberg.
Closing this.
