### ISSUE TITLE
Type-only imports don't work

### ISSUE THREAD

**Issue by inad9300** [microsoft/TypeScript#38271]
**TypeScript Version:** 4.0.0-dev.20200430

**Search Terms:** type-only imports, import type

**Code**

```ts
// From /client/src/Y.ts
import type { X } from '../../server/src/X'

// ...
```

**Expected behavior:** The whole server code should not be part of the compiled output.

**Actual behavior:** It is.

**Comment by nmain** [comment]
You need to provide a reproducible example where `tsc` takes an `import type` expression and does not elide it from the compiled output.  This is more likely a problem with some larger build chain.

**Comment by RyanCavanaugh** [comment]
`import type` vs `import` does not affect which sources are / aren't part of your project.

**Comment by inad9300** [comment]
From the [release notes of 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-exports) (emphasis _not_ mine):

> It _always_ gets fully erased, so there’s no remnant of it at runtime.

If that were any true, the client wouldn't have to carry with it the entire server just because it wants to import a type from it.

A reproducible example, as requested: https://github.com/inad9300/ts-import-type.

**Comment by RyanCavanaugh** [comment]
Again, this is a misunderstanding of what `import type` does

**Comment by inad9300** [comment]
This should not even happen with regular `import`s... Whatever.
