### ISSUE TITLE
Compatibility error when callback has void return type

### ISSUE THREAD

**Issue by canal874** [microsoft/TypeScript#38284]
**TypeScript Version:**  3.8.3

**Search Terms:** 
callback return type void 

**Code**
```ts
const a: () => number = (): void => {};  // Type error. It is expected.
const b: () => void = (): number => { return 7 };  // Ok. It is expected.
```
a and b are expected behaviors which have been discussed many times, 
see https://github.com/microsoft/TypeScript/issues/21674#issuecomment-363537054 

But the following examples are different. 
```ts
const f: (x: () => number) => number = (y: () => void) => 7;  // Ok. It is expected.
const g: (x: () => void) => number = (y: () => 7) => 7; // Type error. It is not expected. It should be Ok.
```
According to the [Assignment Compatibility]( https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#3114-assignment-compatibility),
f is also expected behavior, that is to say,
type '(() => void) => number' is assignable to '(() => number) => number'
because both types are object (function) type 
and the parameter type in '(() => void) => number' is assignable **to or from** the corresponding parameter type in '(() => number) => number'.

Here, parameter type '() => void' is assignable **from** type '() => number'.

g is expected to be ok because parameter type '() => number' is assignable **to** type '() => void',
according to [Assignment Compatibility]( https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#3114-assignment-compatibility) which says that 'each parameter type in N is assignable **to or from** the corresponding parameter type in M'.

**Expected behavior:**
[Assignment Compatibility]( https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#3114-assignment-compatibility) document may be wrong or its implementation may be wrong.

I assume that both may be wrong, f should be type error and g should be Ok in the same way as a and b.

**Comment by MartinJohns** [comment]
This is working as intended.

[Why are functions returning non-`void` assignable to function returning `void`?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

> Assignment Compatibility document may be wrong or its implementation may be wrong.

The specification is not maintained and **heavily outdated**. You should not use it to verify any behavior of TypeScript. It was last updated in **early 2016**. See #15711.

**Comment by canal874** [comment]
I have already read the [FAQ](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void) many times, but the FAQ explains only a and b.

The FAQ shows f is type error and g is OK, however the actual behavior is that f is ok and g is type error.
```ts
const f: (x: () => number) => number = (y: () => void) => 7;  // Ok in the actual behavior
const g: (x: () => void) => number = (y: () => 7) => 7; // Type error in the actual behavior
```

**Comment by nmain** [comment]
The variance flips when a parameter appears as an input to a function.  Easiest to understand this by trying an example that would fail if the types are wrong:

```ts
const gimpl = (y: () => 7) => {
    const ret = y();
    if (ret !== 7) {
        throw new Error("Type was not expected")
    }
    return ret;
}

const g: (x: () => void) => number = gimpl;

g(() => { console.log("this function doesn't return anything") });
```

[Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=1#code/MYewdgzgLgBA5gSwLYAcA2MC8MAUBPALlwEosA+GAdlMwoG8AoGZmUSWAJwFNZs8diAbiYsEAM1zdYAQkzZqMRi2UwoACw4gA7jDBcdAUQ6aOOAEQAVPCi4wtAQwi6QsLgA8bwKFwAmZ4iLMAL6BMFIArhxgYTzCIQxs0PBEOG4pNBQAbiAIPhm64UgARlwcWPDI6MIMcDgC5Iqs4BAgaFwAdGggtWbqCE5i4WBeCOAwPiBcEGAA5Jw8kdH2YHh9YHD+MEFCDEA)

**Comment by canal874** [comment]
> The variance flips when a parameter appears as an input to a function. Easiest to understand this by trying an example that would fail if the types are wrong:

I got it. Thanks for the easy to understand example.
