### ISSUE TITLE
Function, Parameters, ReturnType

### ISSUE THREAD

**Issue by cyrilchapon** [microsoft/TypeScript#38285]
**TypeScript Version:**  3.8.3
(Not tested against Nightly; as the playground doesn't work with Nightly for some reason for now...)

**Search Terms:**
Function, ReturnType, Parameters

(Extremely hard to find something reliable because of the word "Function"...)

**Code**

```ts
const a: Function = () => ({})
type B = ReturnType<typeof a>
type C = Parameters<typeof a>
```

**Expected behavior:**
`ReturnType` and `Parameters` accepting `Function` global type.

**Actual behavior:**

Compiler complaining `Function` not being compatible with `ReturnType` constraint `(...args: any) => any`

```
Type 'Function' does not satisfy the constraint '(...args: any) => any'.
  Type 'Function' provides no match for the signature '(...args: any): any'.
```

**Playground Link:** 

https://www.typescriptlang.org/play/?target=99#code/MYewdgzgLgBAhgLhgMQK5mFAluGBeGACgEp8A+IgbwF9iAoKATwAcBTGAIXxgCVWpUAJzAAVFqwA8TNiABm8Mg3EwAwtwAKcQXAC2-VoIhTxchUA

**Related Issues:** 

Not really, see "Search Terms" for explaination

**Comment by nmain** [comment]
I was also unable to cook up any good searches.

What type would you want `B` and `C` to be here?  `any`?

**Comment by RyanCavanaugh** [comment]
This is the intended behavior since, as noted, there is not any obvious *answer* to the question "What parameters does `a` accept".

**Comment by cyrilchapon** [comment]
@nmain hum; nah I guess

```
const a: Function = () => ({})
type B = ReturnType<typeof a>
// {}
type C = Parameters<typeof a>
// []
```

**Comment by cyrilchapon** [comment]
@RyanCavanaugh an empty array I guess ?

**Comment by cyrilchapon** [comment]
@RyanCavanaugh ; check this out :

```
const a : () => void = () => {}
type A = Parameters<typeof a>
type B = ReturnType<typeof a>
```

https://www.typescriptlang.org/play/?target=99&ssl=1&ssc=1&pln=3&pc=30#code/MYewdgzgLgBAhjAXDAFAShgXgHwwG4gCWAJlqhjjAN4C+AUFAJ4AOApjAIJkAKcATnAC2rKKz4QAPEzYgAZvGwMW7AEJkASiICufMABVlU5XIVA

This works without any compilation error; and I doubt my first use-case is an intended behavior; because in that last example; Parameters = []; ReturnType = void which seems logical

**Comment by cyrilchapon** [comment]
Ok just found why;

Inside _lib.es2015.core.d.ts_; the `Function` interface does not embed a "callable" form.

See this : https://www.typescriptlang.org/play/?target=99#code/JYOwLgpgTgZghgYwgAgGIFcQLMA9iVKXAWwBlgAjZAbwChlkB6AKmfoeeQGE4AbXgM7IwACxQxM2PCAA0yAegoCcYdDhABzYWPkAHCAmAxgEACbJcFAFYGwyGLijaUo4EIBufdClwxn9yRx8OTgQc1EUAX1DYzNkOCgoOABPe0d-BI10YghwIV9-CSwgkAA6dmROAAFdBLhibTcAQSgtABUdSxtsYVxkChR0ATi4IQjG-OtbcoZK5Bq6hsyWpNSm+Qg7Aszs3LAxvoHkWoFh8L7xoql8GY5GdjhdXV5kgApXAQAuNEDpOQ+WhpvqFkiFWisUgB+YEgZIAShhyQA3LR2Cw2LNODx+EI4MgcqJcOZtiALFNsHIFEoVGpQFpQrgIk4urY0k5xgh0Ik9mTumBbnMFkkGgDWsgOj5yXYwIdBmd4mMdJzueBedMKtVasL4uDEilkOteG4tn4djk8r1+igTvKZf4CSIiQLmPcGAg+Lx3iI3N8MMU-hNAYi5KVQ8s9clEQBtAC6CPisJRaNYGrQ6TxGmA7lyAX9wWQCCgEDgkFx-VwmHMVxK2hLyBEo38AnqKAoRNSjfGjmAmZAfFz1zKqYlEzVPQK4zblYHNbcCoEuEMJbiAHdgKIm9EjCZiVKQmF652dFEDNu4qB18B+1qW5AoAJnfMbyLvQJAQbSSyenaV96ECJ-A+ZAAGsIGSFdHHMd1SSLGBoGQUABGAUwXB0EAIBXGdpEfIV6h1DQITWZAjWUCxTVaXYLTtI4bTiO1xnQzDq2wjVXX6UBTC9H0fjzWRA1aYNkFDUpw1WaM40RJMGHRZAACVNi5EAy2UKA6WQItdCLYZwBLaQyPiLCbkqNiZQAZTAVTNFeeMVLpKTjiIGUwGSfRJPYIs4FMfAXmI3INFEb4QGyAYoHsxhGGQAA5fAAFplFCUwEnMCAAA9ICU6QBAeCjzX2Ny3Q9aBfV+fAUQAX1RUA73gJA0GAFKzD9QdCBIcgqFS9LTCEJqShashKBoNEIraAAJABRNAAEkAA1kHG2SxvYV5hMyL4E2SWN4xBcrUWc-Q5ISkger0gBeZBrOQE6AD5kHcXBkNoPaUHWM6AAVFk2aABAAHlkw7iGO-ArselyUAAIUuuSFKgEA2lB37-sBkBgae7hIfe4VPvvb6kZR0HkAAEUh+TVBhuH9BxkrkZB-aJrej67x+pG+ravH9tQYnodh+HmaIfqKDZlAAHF0YZr6cfqxqqZZyhBbmznSe5inUEl0xeda2WgA

**Comment by nmain** [comment]
`Function` is meant to represent any value for which `v instanceof Function` is true, with no further restrictions.  So it has no known call signatures.  If you know you have something that has a particular signature, type it as that.

`Function` values are granted a signature of `(...args: any[]) => any` when you attempt to call one for back compat reasons, but that signature doesn't participate in other things.  If you want that signature, you can explicitly type your function as that too.

**Comment by cyrilchapon** [comment]
@nmain OK thanks :) I understand.

I'll make a `Callable<T extends Function = Function>` helper; but in my opinion;

> Function values are granted a signature of (...args: any[]) => any when you attempt to call one for back compat reasons

I'm curious, where is that code actually ?

> Function is meant to represent any value for which v instanceof Function is true, with no further restrictions. So it has no known call signatures. [...] that signature doesn't participate in other things

That's curious IMHO. Especially the fact every duck-typing insights are coded inside _lib.es2015.core.d.ts_ EXCEPT the main - basic - feature of a function : being callable. Am I missing something ? oO
