### ISSUE TITLE
Incorrect parse on static property followed by method

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#38283]
```ts
// @target: esnext
// @noImplicitAny: false

class C {
    static static
    foo() {}
}
```

Here, ASI needs to take effect and the parse should be a class with two members: a static property named "static", and an instance method named "foo".

**Expected**

No errors. The file is parsed as

```js
class C {
    static static;
    foo() {}
}
```

**Actual**

```
'static' modifier already seen.
```

**Comment by yungvldai** [comment]
`
class C {
    static static;
    foo() {}
}
`
?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser There is a similar test for the index signature

https://github.com/microsoft/TypeScript/blob/f68a8393ef51d1c8b797cec440ba82201d0c83e9/tests/cases/compiler/staticAsIdentifier.ts#L1-L4

Should it be parsed similarly to your example?

```ts
class C {
    static static;
    [x: string]: string;
}
```
