### ISSUE TITLE
Function with argument of specific type can be assigned to interface containing function with union type arguments

### ISSUE THREAD

**Issue by lynxtaa** [microsoft/TypeScript#38293]
**TypeScript Version:**  3.8.3

**Search Terms:**
function with union arguments in interface
**Code**

```ts
function Component(props: {
    onClick(val: number|string): void
}) {
    props.onClick(123)
    return null
}

const format = (val: string) => val.toLowerCase()

Component({
    onClick: format  // this will throw at runtime!
})
```

**Expected behavior:**
Compilation error
**Actual behavior:**
Runtime error
**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/v2/en/play?#code/GYVwdgxgLglg9mABAYTgWwA4IKZigCgwCc4MBnALkQG8AoRBxBZAGxggGt8A3AQxapgQaAEbYiAHzJQiMMAHMAlFW5wYAE1oBfRTXqNipMgDpmbTvgCMAJgDMi-QyLYoIIkiEsW22rQgJpRGA4IjReKEQAXkQefippWQVdSIA+RD4WYyg4ABk4AHdxZF4ybHwHWlRMHDx8OkYmMFZ2Dipg0PCGAHouxCgACxgyRHyYLz7+knzETqJwWDRsAEJtRSA)
**Related Issues:** 

Am I doing something wrong? How can I prevent this behavior?

**Comment by MartinJohns** [comment]
See #18654.

Method arguments are checked bivariantly. You can easily solve this issue by using a function property instead, which are checked contravariantly (when `strictFunctionTypes` is enabled): `onClick: (val: number|string) => void`

**Comment by lynxtaa** [comment]
> 
> 
> See #18654.
> 
> Method arguments are checked bivariantly. You can easily solve this issue by using a function property instead, which are checked contravariantly (when `strictFunctionTypes` is enabled): `onClick: (val: number|string) => void`

Oh wow! Thanks
