### ISSUE TITLE
RangeError when trying to infer type for Array.prototype.flat()

### ISSUE THREAD

**Issue by 0kku** [microsoft/TypeScript#38298]
**TypeScript Version:**  3.9.1-rc, 4.0.0-dev.20200430

**Search Terms:** Array flat RangeError Maximum call stack size exceeded

**Code**
```ts
class Foo <T> {
  arr: T[] = [];
    
  bar (
    depth = 1,
  ) {
    return this.arr.flat(depth);
  }
}
```

**Expected behavior:**
Code compiles without errors.

**Actual behavior:**
TSC crashes with `RangeError: Maximum call stack size exceeded`. Edit: Only happens when either `--watch` or `--declaration` flag is set.

**Playground Link:** Couldn't figure out how to add newer libs for Array, and not super useful anyway, as the compiler crashes

**Related Issues:** 
https://github.com/microsoft/TypeScript/pull/32131 seems to be the breaking PR
https://github.com/microsoft/TypeScript/issues/36554 seems related maybe

edit: simplified code example

**Comment by b-fuze** [comment]
I can also produce it here
```typescript
function foo<t>(arr: t[], depth: number) {
  return arr.flat(depth);
}
```

**Comment by pirix-gh** [comment]
Not able to reproduce the error on 3.9.1-rc or 4.0.0-dev.20200430.

**Comment by b-fuze** [comment]
@pirix-gh It doesn't happen in normal mode, it happens in watch mode.

**Comment by 0kku** [comment]
Looks like it doesn't happen if I comment out `"declaration": true` from my tsconfig. Also with `-w` flag it happens regardless of that config option. Here's my tsconfig: 
```js
{
  "compilerOptions": {
    "lib": ["es2019"],
    "declaration": true,
    "outDir": "./dist",
    "rootDir": "./src",
  }
}
```
