### ISSUE TITLE
Iterate over object key whose values are of different type

### ISSUE THREAD

**Issue by krvikash35** [microsoft/TypeScript#38301]
**TypeScript Version:**  3.8.3

**Search Terms:**
I searhed a lot related to iterating over object key having different value type but could not get satisfactory result.

**Code**

```ts 
type TTheme = {
  color: {
    primary: string;
    secondary: string
  };
  font: {
    baseSize: string;
  };
};

const currentTheme: TTheme = {
    color: {
      primary: 'green',
      secondary: 'red'
    },
    font: {
      baseSize: '1rem',
    }
}

// Transform above currentTheme by changing attribute value i.e `green` with `var(--green)`
  Object.keys(currentTheme).forEach(key => {
    currentThemeVars[key] = {};
    Object.keys(currentTheme[key]).forEach(themekey => {
      currentThemeVars[key][themekey] = `var(--${themekey})`;
    });
  });
```

**Expected behavior:**
Above code should work

**Actual behavior:**
It is throwing error, complaning alot about usage of `key` and `themekey`
`No index signature with a parameter of type 'string' was found on type 'TTheme'`

**Comment by RyanCavanaugh** [comment]
There's no definition of `currentThemeVars`. You are probably getting tripped up on `Object.keys` not returning a `keyof` type; see https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript
