### ISSUE TITLE
`mustUse` / `noignore` return values

### ISSUE THREAD

**Issue by wojpawlik** [microsoft/TypeScript#38303]
## Search Terms
no ignore noignore must use mustUse

## Suggestion

```ts
declare function returnsPromise(): noignore Promise<void>
```

Not using the returned value would be an error. Value can be used by:

1. Passing it to a function or method,
2. Calling its method,
3. Using one of its properties,
4. `await`ing it, if it's a Promise,
5. `yield`ing it,
6. Returning it.
   Inferred return type should be `mustUse` / `noignore`.

## Use Cases

1. Detecting unhandled Promise rejections (related: #13219),
2. Detecting unnecessary calls to pure functions (related: #17181).

## Examples

```ts
declare function returnsPromise(): noignore Promise<void>

foo(returnsPromise()) // ok (1)
returnsPromise().catch(...) // ok (2)
await returnsPromise() // ok (4)
return returnsPromise() // ok (6)
returnsPromise() // error

array.splice(0, 1) // ok
bar(array.slice(1)) // ok (1)
array.slice(1).forEach(...) // ok (2)
array.slice(1).length // error, `.length` unused
baz(array.slice(1).length) // weird but ok (3, 1)
return array.slice(1).length // weird but ok (3, 6)
yield array.slice(1) // ok (5)
yield* array.slice(1) // ok (5)
return array.slice(1) // ok (6)
array.slice(1) // error
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ikokostya** [comment]
In most cases unused return value should be considered as error or warning. For this reason make sense in opposite approach when we can specify that return value should be ignored:

```ts
returnsPromise(); // must be error or warning
_ = returnsPromise(); // OK
```

See for example https://docs.microsoft.com/en-us/dotnet/csharp/discards

**Comment by ikokostya** [comment]
Also related to https://github.com/microsoft/TypeScript/issues/13376

**Comment by RyanCavanaugh** [comment]
I don't think this covers any ground not already covered by existing issues.
