### ISSUE TITLE
Option for Strict Type Checking in Output JavaScript

### ISSUE THREAD

**Issue by zemse** [microsoft/TypeScript#38302]
## Search Terms

type assert, type guard for output js, forced types for output js

## Suggestion

An option to force type inputs to the functions in the output js files. This can be disabled by default since every one is familiar with typescript as it is (it doesn't add type checking in the js).

I tried to find solutions on google but couldn't find what I wanted. There definitely are some packages out there that help do the type checking. But if there would be this feature in typescript which I can turn on in critical projects where finance is at stake, runtime bugs would be nightmare.

## Use Cases

I understand that typescript is a development time tool but many times it happen that inputs that depend on external sources which can change interface / data types later can go un noticed until a bug is discovered which might cause a huge loss.

## Examples
So here is an example of a small system that checks the price of a cryptocurrency in two exchanges and computes the average and places a buy order at the average price.

Typescript code:
```typescript
function avgOfTwoNumbers(a: number, b: number): number {
  return (a + b) / 2;
}

interface ApiOutput {
  price: number
}

// by default getRequest is of type Promise<any>
const apiResponse1: ApiOutput = JSON.parse(await getRequest('https://exchange1/btc-price'));
const apiResponse2: ApiOutput = JSON.parse(await getRequest('https://exchange2/btc-price'));

const avg = avgOfTwoNumbers(apiResponse1.price, apiResponse2.price);

await postRequest('https://host3/buy-btc', { price: avg });
```

Expected runtime:
```javascript
// expected api outputs
apiResponse1 = {
  price: 8460
}
apiResponse1 = {
  price: 8450
}

// expected computation of avg
avg = avgOfTwoNumbers(8460, 8450)
avg = ( 8460 + 8450 ) / 2
avg = 16910 / 2
avg = 8455
```
Possible runtime:
```javascript
// correct api output by one provider
apiResponse1 = {
  price: 8460
}
// incorrect api output by other provider
apiResponse1 = {
  price: '8450'
}

// expected computation of avg
avg = avgOfTwoNumbers(8460, '8450')
avg = ( 8460 + '8450' ) / 2
avg = 84608450 / 2
avg = 42304225
```
In this example, the runtime didn't even give an error or warning. User will know about this when they find time to look at their account balance.

Suggesting Runtime:
```javascript
avg = avgOfTwoNumbers(8460, '8450')
Error: Type '"8450"' is not assignable to type 'number'.
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplicate of #1573. And this disagrees with the Design Goals.

**Comment by zemse** [comment]
Thanks for providing link to the first issue.
