### ISSUE TITLE
Wrong type inference in constructor body with multiple overloads

### ISSUE THREAD

**Issue by stephanemagnenat** [microsoft/TypeScript#38315]
**TypeScript Version:**  3.8.3 and nightly (tested on Playground as of May 4, 2020)

**Search Terms:** boolean constructor overload, constructor overload resolution

**Code**

```ts
class A { }

class B {
	_x: boolean;
	_y: boolean;

	constructor(x: boolean, y: boolean);
	constructor(a: A);
	constructor(xOrA: A | boolean, y?: boolean) {
		if (xOrA instanceof A) {
			this._x = true;
			this._y = true;
		} else {
			this._x = xOrA;
			this._y = y;
		}
	}
}
```

**Expected behavior:** I expect this code to compile.

**Actual behavior:** Compilation failure on line `this._y = y;` with error:
```
Type 'boolean | undefined' is not assignable to type 'boolean'.
Type 'undefined' is not assignable to type 'boolean'.(2322)
```

My understanding is that in the else branch of the if, the compiler knows that we are using the first overload, and therefore should be able to infer that `y` must be defined. Maybe I missed something trivial, but after searching in the documentation and online I did not find any useful hint, so I am reporting the issue.

**Related Issues:** none found

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ts=Nightly#code/MYGwhgzhAECC0G9oF8BQrSRgIUagkAPoAeAXNAEYD2VIApmAHYDcBhAnudbQy+vsCqMIAFwBOAV2AiqYgBRlKNekwA00Tkp5MAlKwFDRk6bLlhysPQUHDxUmfOIB5MbAvQAPlpWN17APxcyrw6ePj4AJYAZtAKLvARtkzAdFQxlmHhIgAWERAAdCTQALzQdnT6WbkFHCVlkhUE+MjQdCAQdJn4OXmFxHXOrpXd1YXsdeyVaM2oyEA)

**Comment by MartinJohns** [comment]
Same issue as in #38211.

**Comment by stephanemagnenat** [comment]
Ah ok, I definitely encounter a lot that design limitation these days, sorry for the noise then. Yet I suggest to keep this issue as well because the "surface feature of the error" is quite different than in #38211, in that issue the error was at the call site, while in this issue the error is within the constructor.

**Comment by RyanCavanaugh** [comment]
Duplicate #14515
