### ISSUE TITLE
Inconsistent behavior when extending a class with an overloaded method with a generic parameter

### ISSUE THREAD

**Issue by seishun** [microsoft/TypeScript#38313]
**TypeScript Version:**  4.0.0-dev.20200504

**Search Terms:** generic method extends incompatible inconsistent

**Code**

(1)
```ts
class Foo {
  static from(a: string): void
  static from(a: number): void
  static from(a: any) {}
}

class Bar extends Foo {
  static from(a: string): void {}
}
```

(2)
```ts
class Foo {
  static from<T>(a: T) {}
}

class Bar extends Foo {
  static from(a: string): void {}
}
```

(3)
```ts
class Foo {
  static from(a: string): void
  static from<T>(a: T): void
  static from(a: any) {}
}

class Bar extends Foo {
  static from(a: string): void {}
}
```

**Expected behavior:**

Either (3) doesn't compile, or one of (1) and (2) compiles.

**Actual behavior:**

(1)
```
error TS2417: Class static side 'typeof Bar' incorrectly extends base class static side 'typeof Foo'.
  Types of property 'from' are incompatible.
    Type '(a: string) => void' is not assignable to type '{ (a: string): void; (a: number): void; }'.
      Types of parameters 'a' and 'a' are incompatible.
        Type 'number' is not assignable to type 'string'.
```
(2)
```
error TS2417: Class static side 'typeof Bar' incorrectly extends base class static side 'typeof Foo'.
  Types of property 'from' are incompatible.
    Type '(a: string) => void' is not assignable to type '<T>(a: T) => void'.
      Types of parameters 'a' and 'a' are incompatible.
        Type 'T' is not assignable to type 'string'.
```
(3)
(no error)

**Playground Link:** 
[(1)](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200503&ssl=1&ssc=1&pln=9&pc=2#code/MYGwhgzhAEBiD29oG8CwAoa0IBcw4EthoAzAJ3gFsAKMALmxzIIDsBzASgYDd4CATDFlz4ipCjXrQWAV0oAjAKZku0XgKGNRxclVoMwLAJ4cUAXwwX0GUJBgAhMGWiKAHjkUt+MBEjSYtQh0JfUZmdlV1fnNLIA)
[(2)](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200503&ssl=1&ssc=1&pln=9&pc=2#code/MYGwhgzhAEBiD29oG8CwAoa0IBcw4EthoAzAJ3gFsAeAFQD4AKMALmloEoUBfDX9DKEgwAQmDLQApgA8ckgHYATGAiRpM2PIWLkqzNrjIF5Acw5sAbvAKKefIA)
[(3)](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200503&ssl=1&ssc=1&pln=7&pc=2#code/MYGwhgzhAEBiD29oG8CwAoa0IBcw4EthoAzAJ3gFsAKMALmxzIIDsBzASgYDd4CATDFlz4ipCpQA8AFQB8tBtK7ReAoY1HFyVBdDAsAnhxQBfDGfQZQkGACEwZaAFMAHjict+MBEjSYNhFoSurjM7Mqq-KbmQA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
(3) is considered a match due to bivariance, but the others are not. This is the intended behavior.

**Comment by seishun** [comment]
> (3) is considered a match due to bivariance

Are you referring to `T` being narrowed to `string`? If so, (2) should work too, no?

(If I replace `T` with `any` or `unknown`, then both (2) and (3) work, which is expected.)

**Comment by seishun** [comment]
Also consider this example:

```ts
class A
{
    foo(a : string) : void
    foo(a : number) : void
    foo(a : string) { }
}

class B
{
    foo<T>(a : T) : void
    foo(a : string) { }
}

class C
{
    foo(a : string) : void
    foo<T>(a : T) : void
    foo(a : string) { }
}
```

Here, only `A` fails to work. `B` compiles even though it's analogous to (2). Should I create a separate issue about this?

**Comment by yw662** [comment]
The later one is for sure WAI.
However, why subclasses must have the same static signature with super classes ?
The static methods are never inherited, threfore, the static methods `Foo.from` and `Bar.from` are never the same. It doesn't make any sense to require them having the same signature.
