### ISSUE TITLE
Property 'description' does not exist on type 'unique symbol'

### ISSUE THREAD

**Issue by shaman-apprentice** [microsoft/TypeScript#38310]
**TypeScript Version:** 4.0.0-dev.20200503 and 3.8.3

**Search Terms:** *Symbol description*

**Code**

```ts
const s = Symbol("some description");
console.log(s.description);
```

**Expected behavior:**
As `Symbol.prototype.description` works in the Browser as well as in node, I expect it to transpile without errors (also see [https://developer.mozilla.org/](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/description))

**Actual behavior:**
```
src/index.ts:2:15 - error TS2339: Property 'description' does not exist on type 'unique symbol'.

2 console.log(s.description);
                ~~~~~~~~~~~
```

**Comment by rbuckton** [comment]
`Symbol.prototype.description` was added in ES2019, and ships in our default libs if you use `--lib es2019`:

```json
{
  "compilerOptions": {
    "lib": ["es2019", "dom"],
    ...
  }
}
```

[Playground example using --target ES2019](https://www.typescriptlang.org/play?target=6&ts=4.1.0-dev.20200823#code/DYUwLgBMD2DGCGwDKBPAtgI2sCBeCqm2AFAEQAmIAzrAE4CWADmPdAHakCUA3AFCiQA5jAyJCWHPnHYAdADNotMsHgYQwLn1jsq2EDJiDiMBMnQSZlGg2as2PXtra7QB6EeHRRZosEvU6JhZ2HiA)

[Playground example using lib](https://www.typescriptlang.org/play?lib=&ts=4.1.0-dev.20200823#code/PQgEB4CcFMDNpgOwMbVAGwJYCMC8AiAEwHsBbfUYAPgCgRgIZ4lUMcDoBnAJgAYBGAJwVqdBgDkA8gBUAogC5QASUScALtACGhUMVig1ACzSbsxAG5oArpzRG0sYunTEA7pkQBzUB9ABPYitIA05kYkRYTE8AOgArTnD5MVAAb2TQUHww0gAHTHQESRy1THDOfEU0sAyM-CxsCtAAbXwuPiF8ABpMknIAXU70muiRoYBfZImaGgK1DGJkTXQAZT9SM3RQXFBV9acACiIuZEhMYtLEfABKAG4Z6DnPF2wl3Y2tnbWN6MdIQ-RTNB0Nc7mFVE5oNEXJ59i5Fisvk5ooRjqdzuFbjQwQkClDiDCnsQXgi9uhkaiziUMTcgA)
