### ISSUE TITLE
Value explicitly has type `any` but tsc error says it is implicit

### ISSUE THREAD

**Issue by spectraldani** [microsoft/TypeScript#38324]
**TypeScript Version:**  3.8.3

**Search Terms:**

`TS7053`,  `implicitly has an 'any' type because expression of type 'any'`

**Expected behavior:**

The code should compile without errors.

**Actual behavior:**

Compiler throws: `error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ -1: string; 0: string; 1: string; 2: string; 3: string; }'`.

**Related Issues:**

I couldn't find any related issues.

**Code**
```ts
const PATTERN_NAMES = {
    '0': 'zero',
    '-1': 'minus one'
};

declare const index: number;
PATTERN_NAMES[index.toString() as any]
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const PATTERN_NAMES = {
    '0': 'zero',
    '-1': 'minus one'
};
PATTERN_NAMES[index.toString()];

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/MYewdgzgLgBACgQQCpIKICUByB9TCCyqAyjALwwDeAUDLTAOQAM9AXAwF4CmATiPQDQ069ALQBGVgwC2ASzABXCDHCd6VAL4BuKlQAmnYABsAht04xQkWHP0APNgqkAjHtsQoMOPISIBtG5y2AHRQIERQ3HIA5gAUAJQwxkrGYACeALpAA)

**Comment by RyanCavanaugh** [comment]
You're type-asserting the wrong part of the expression to fix this error. The correct fix is:
```
(PATTERN_NAMES as any)[index.toString()]
```
or
```
(PATTERN_NAMES as any)[index]
```

**Comment by spectraldani** [comment]
Ah, I see. You are totally right.

I think I was led to believe the problem was with the expression that was indexing the object because the whole expression was red-underlined instead of just `PATTERN_NAMES`. I tried type-asserting the whole expression and that didn't work but I didn't occur to me to try type asserting the indexed object.

Thank you for your time!
