### ISSUE TITLE
strictNullChecks with optional properties on class change type

### ISSUE THREAD

**Issue by hasezoey** [microsoft/TypeScript#38323]
**TypeScript Version:**  4.0.0-dev.20200504

**Search Terms:** optional class strictNullChecks generics type

**Code**

```ts
type RefType = number | string | Buffer;
type test<T, S extends RefType = number> = T | S;

class SomeClass {
  public prop?: test<string>;
  // type of "prop" when "strictNullChecks" is disabled "test<string>" (how it should be)
  // type of "prop" when "strictNullChecks" is enabled "string | number | undefined"
}
```

**Expected behavior:**
that `prop` is of type `test<string>` (or in strict mode `test<string> | undefined`)

**Actual behavior:**
`prop` is of type `string | number | undefined`

**Playground Link:** 
not working as expected: [Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=2#code/C4TwDgpgBAShBmAVc0C8UB2BXAtgIwgCcoAfKAZ2EIEsMBzUqAIS3niIG4BYAKFEijAIlADyIANFADKUCAA8hGACblYCZAPTZ8RAHxR0iRlO49eAYwA2AQ3KqpAexwQAwjbtQA3ryhQwWPEtqcz9CBzAAfgAuQWFgEUoael1TXwB6NMEUKAd4KAAiMDCwfKgAdwALCAwCxODgADksS0sXKvMAa3JS6lUlXutAiCUCoVE65NKACgqHMqhqYApZ5pGCAEofKAysgVyCovDSyuraqnqmlraITu6F1WrBy2GzpIYybQJiMixlBFphvleABfIA)

working as expected: [Playground Link](https://www.typescriptlang.org/play/?strictNullChecks=false#code/C4TwDgpgBAShBmAVc0C8UB2BXAtgIwgCcoAfKAZ2EIEsMBzUqAIS3niIG4BYAKFEijAIlADyIANFADKUCAA8hGACblYCZAPTZ8RAHxR0iRlO49eAYwA2AQ3KqpAexwQAwjbtQA3ryhQwWPEtqcz9CBzAAfgAuQWFgEUoael1TXwB6NMEUKAd4KAAiMDCwfKgAdwALCAwCxODgADksS0sXKvMAa3JS6lUlXutAiCUCoVE65NKACgqHMqhqYApZ5pGCAEofKAysgVyCovDSyuraqnqmlraITu6F1WrBy2GzpIYybQJiMixlBFphvleABfIA)

**Related Issues:** 
- #37163 might be related 

---

the current behavior breaks functions that depend on destructuring types
```ts
function getRefProperty<T, S extends RefType>(ref: test<T, S>): S {
  // some code
}
```

**Comment by nmain** [comment]
`test<string>` is exactly equivalent to `string | number`, and `test<string> | undefined` is exactly equivalent to `string | number | undefined`, so there's nothing wrong there.

The way you've written `getRefProperty` you'll never get useful inferences for `S`.  Inference proceeds left to right starting at `T`, and the sole argument to the function is a `T | ...`, so `T` will be inferred to simply be the type of the argument in all cases.  But then `S` is entirely unconstrained by the parameter values, so there's nothing to do but set it to some sensible default and hope things work out.

Keep in mind that types are structural and type unioning is commutative and associative, so whenever you have `T | S` it doesn't matter to typescript what "part" of the type is in `T` and what "part" is in `S`.

`getRefProperty` is a type assertion in disguise.

```ts
// returns "chicken noodles", of course
declare var c: SomeClass;
getRefProperty<string | number | undefined, "chicken noodles">(c.prop);
```

**Comment by andreialecu** [comment]
@nmain take a look at this example:

```ts
class ObjectId {
  anObjectId!: boolean;
}

export declare type RefType = number | string | ObjectId | Buffer;

type Ref<
  R,
  T extends RefType = R extends { _id: RefType } ? R["_id"] : ObjectId
> = R | T;

declare function isRefType<T, S extends RefType>(
  doc: Ref<T, S>,
): doc is S;


class Model {
  _id?: string; // change to ?
  name!: string;
}

class Parent {
  child!: Ref<Model>;
} 

const x = new Parent();

isRefType(x.child) ? x.child.anObjectId : x.child._id;
```

Here's a [Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=28&pc=55#code/MYGwhgzhAEDyBGArApsALgSQCbQN4FgAoaaMAOwRXWwEIAuaeAeyZGXIG4iBfIo5AB4AHJgCc00LKnCjk0NAE8hcgErIAZgBUlcgLzQyAVwC28ZKOgAfaBDSiAlmQDmVuElSYc1gEKH168y5CIkVlaDV1AB4iEhUAGhjoTWhBNGQyLBgI7TD9FRSBNIyYXGgAfXssBmydaG5oAH5wgG0AIgqsVoBdaAZKD2wiAD5oPNdNIKIpUDBZaHVDMnR7JjJoewga5UjNOOgAZQKizPCNHOQhgApErCZgao0dvf2hhMIASgZb4HWYfcngoQZlBoABZJhSEB4RIdBoMWwOZwcaAAehR0GAAAtyE45GgmI1EmQwMZkPQbHZHE4grxAcCYAAFWbpCQEYgYzH2EBYckRSLgyFDGnQPhA1a2aACUYGZAAd2gTNkZDQl3eAI2W2QlwEADosVysO9GpK9ZzuTryP1qDgGLr9eaOhwgA)

Depending on whether `_id` is defined as nullable or required, the type of `Child` changes from `Ref<Model, ObjectId>` to `Ref<Model, string>`, and a compilation error appears below.

Something similar, but separate, happens depending on whether `child` has an `?` or a `!` after it.

**Comment by andreialecu** [comment]
Thinking about it, it seems that if a property is defined as `string | undefined`, then the `extends` check is false. Is there any way to work around this?

**Comment by hasezoey** [comment]
@nmain then why does it work (as expected by me) when `strictNullCheckes` is `false`?
(so that the type is `test<string, number>`(`test<string, number> | undefined`) and not `string | number | undefined`)

> The way you've written getRefProperty you'll never get useful inferences for S

when `strictNullCheckes` is `false` it is fully working as it is written, and it is very useful, that is why i made an issue on why it changes with this option

-> the whole intention about `getRefProperty` is to automatically infer the types needed

**Comment by nmain** [comment]
> then why does it work (as expected by me) when `strictNullCheckes` is `false`?

If the argument's type is `test<A, B>` for some `A` and `B` and that hasn't been expanded or simplified or modified at all yet, then tsc sees that it's trying to fit `test<T, S>` and does the obvious thing and infers `T` as `A` and `S` as `B`.

**Comment by hasezoey** [comment]
@nmain yes, but shouldnt when `strictNullCheckes` (that adds `| undefined`) is active result in `test<A, B> | undefined` where it still could resolve the function?

**Comment by RyanCavanaugh** [comment]
I don't see anything indicative of a bug here. Please file a new issue with a more explicit explanation of what's wrong if you'd like us to come back to it - "This isn't what I *expected*" is not really indicative of a defect without more context.

**Comment by andreialecu** [comment]
@RyanCavanaugh here's an example where behavior is different with `strictNullChecks` on or off:

[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDyAjAVsAxjASQBM4BeOAbzgH0BLIgLjgGcYpaA7AczgF8BuAFCDQkWAmSoASsABmAFUlk4HAK4BbDMChwAPizace+1RyJzOwEvsw58xIYKQo4M2QB55cUDGBnmcBDYeDAANHAAyt4gvv6ucoou5LYhxAB8yl76EY7muAA2AIZQqLKm+LQQHHC0zAAiELgafjCe0bFEAUF2YZHtfp3xCpJpABREjUxunuERaQCUTBO4NQHywgWFzAEREOrAaDAAFtoAshDm+ZQIPgCETKzs3HzCeUUlcLhVrHAlslNydy7faHE5Qc6XDImMwWDhWRy0WRwUa1BpNfYcGCjP7zeaUQRwT7feDOYAARmUfyEhIA9DTAgBrOAAd1oxwgqngj1o+Dg6guwAYBIkKDJADpfDFBLxvPlmKgKMKvhwfqSAEyUuRCXhAA)

Just toggle `strictNullChecks` on or off.

The curious part is that simply changing the type on the first line to add `undefined` to it:

`export type ObjectId = { _id: string } | undefined;`

Resolves the issue, but it's unclear why. So I don't think there's a typescript bug here, just non-intuitive behavior.

**Comment by andreialecu** [comment]
Nevermind, I understand the problem. More context here if someone runs into this in the future and needs help: https://github.com/typegoose/typegoose/pull/254#discussion_r422502220 :)

Issue can probably be closed.

**Comment by hasezoey** [comment]
thanks @andreialecu for explaining why this is happening, but i would have expected an error from typescript of "incompatible types" or something like that
