### ISSUE TITLE
declaring an object user have to initialize get properties!

### ISSUE THREAD

**Issue by keysersoze24** [microsoft/TypeScript#38338]
if a declare a class

```
class MyClass {
   a: number;
   get b(): number { return a * 2 };
}
```
when I initialize an object of type "MyClass" the prop "b" is required even if it's just readonly (get) property

example code:

`var myObject: MyClass = { a: 10 };`
so this will throw a typescript error:

**Property 'b' is missing in type '{ a: number; }' but required in type 'MyClass'.**

**Comment by IllusionMH** [comment]
There are other errors in playground that you didn't included as was required by template: [Playground](https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAECyCeBhcVoG8BQ1tgFzQDsBXAWwCMBTAJwG4tsBzCgF2jIAoBKfY869aFRZEqBaGGgAqaACZoAXzryMGAG5gq0EvADyZAFYVgzfAmSQYAXgF5oARgAMCmkA)

`myObject` will contain only what you specified `a: 10` and `b` is not accessible on provided object (`var myObject: MyClass = { a: 10 };` *won't create instance of the class*, you need to properly construct class instance).
On the other hand any place that accepts `MyClass` will expect to have access to both `a` and `b` propeties, but your object specifies only one therefore TS marks this an error.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
