### ISSUE TITLE
Question: What is SyntaxKind.PropertySignature (131)? How is it different from SyntaxKind.PropertyDeclaration (132)?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#3833]

**Comment by DanielRosenwasser** [comment]
My understanding is that a `PropertySignature` is part of a type declaration (as in an interface or type literal), whereas a `PropertyDeclaration` is a class element. There is also a `PropertyAssignment` and `PropertyShorthandAssignment` which appear in object literals. As if this was not subtly confusing enough, we have the following code in the parser:

```TypeScript
let property = <PropertyDeclaration>createNode(SyntaxKind.PropertySignature, fullStart);
```

**Comment by aleksey-bykov** [comment]
- for something called "PropertySignature" there is no interface that defines an AST node in the code of the TS compiler
- there is only a syntax-kind value `SyntaxKind.PropertySignature = 131` that is the only representation of "PropertySignature"
- in ALL switch cases around the code PropertySignature falls through to PropertyDeclaration
- at the same time PropertyDeclaration does have an interface `PropertyDeclaration` for an AST node and a syntax-kind value: `SyntaxKind.PropertyDeclaration = 132`
- on top of that
> let property = <PropertyDeclaration>createNode(SyntaxKind.PropertySignature, fullStart);

**Comment by DanielRosenwasser** [comment]
It sounds like you and I are thinking something similar; though considering it more, it may useful to be able to say "I want all the `PropertyDeclaration`s in a file but not `PropertySignature`s, and aggregate them specifically with a `forEachChild`. I could also see the differentiation being useful in language service scenarios.

I think that the real problem is that it's not that obvious which is which.

**Comment by mhegazy** [comment]
@aleksey-bykov and @DanielRosenwasser what is the action item here? do we have a proposal?

**Comment by aleksey-bykov** [comment]
Can be closed.

**Comment by mhegazy** [comment]
thanks. closing.
