### ISSUE TITLE
String.split() method's separator argument should be optional

### ISSUE THREAD

**Issue by deluksic** [microsoft/TypeScript#38331]
```ts
console.log("some string".split());
```

**Expected behavior:**
`tsc` succeeds in transpiling this code.

**Actual behavior:**
```
test.ts:1:13 - error TS2554: Expected 1-2 arguments, but got 0.

1 console.log("test split".split());
              ~~~~~~~~~~~~~~~~~~~~

  ../../../../usr/local/lib/node_modules/typescript/lib/lib.es5.d.ts:475:11
    475     split(separator: string | RegExp, limit?: number): string[];
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'separator' was not provided.


Found 1 error.
```
Running the resulting `.js` file in node results with `[ 'test split' ]` being written to console.

**Playground Link:** 
https://www.typescriptlang.org/play/#code/MYewdgziA2CmB00QHMAUAiALrCmAEuATgJZjLrwQAO0xmqAlAwNxA

**Comment by DanielRosenwasser** [comment]
That code seems highly suspicious. `Array.prototype.split()` just creates an array with the original string when you omit a split argument. Why would you want that/

**Comment by deluksic** [comment]
Even though I agree with you, the spec seems to be different.

**Comment by DanielRosenwasser** [comment]
The spec will always have well-defined behavior for different cases, but TypeScript's declarations aim to give a sensible version that can avoid issues. Consider the fact that `split()` can also work fine on `null`, `number`s, and `bigint`s. The behavior of `split()` really indicates to me that it should not make the parameter optional because there's nothing to be gained there.

```
> "hello".split("")
["h","e","l","l","o"]

> var x = "hello null undefined world";
> x.split()
["hello null undefined world"]

> x.split(undefined)
["hello null undefined world"]

> x.split(null)
["hello", "undefined world"]
```

**Comment by deluksic** [comment]
Ah, that makes sense. I was just trying to port over some code from js to ts and this was giving me an error when in fact it was working. But I see your point, typescript doesnt have to adhere to spec if it introduces more safety.
