### ISSUE TITLE
Use infer to constrain type without "narrowing" it 

### ISSUE THREAD

**Issue by mmkal** [microsoft/TypeScript#38349]
## Search Terms

infer, constrain, generic

The above search terms yielded an issue with a similar request: https://github.com/microsoft/TypeScript/issues/36450, but that was seemingly coupled to the eslint `typedef` rule - usage of which was explicitly called out by @RyanCavanaugh  as [a bad idea](https://github.com/microsoft/TypeScript/issues/36450#issuecomment-578846421). There's a [comment at the end](https://github.com/microsoft/TypeScript/issues/36450#issuecomment-609719880) that's closer to this proposal, but I thought it deserved its own issue for voting/conversation/triaging.

## Suggestion

Use the `infer` keyword in an explicit type definition to constrain a type, but ask the compiler to still infer things about it.

## Use Cases

Several - for example when using a library publishing types, it allows conforming to an interface and extending it, without the compiler losing track of the "extended" part.

## Examples

```typescript
// some-library.ts
interface Logger {
  info: (message: string) => void;
}

const startServer = (logger: Logger) => ...
```

```typescript
// my-app.ts
const myLogger: Logger = console;

startServer(myLogger); // ok

myLogger.warn('abc'); // error!
```

Right now, the above fails because `warn`  does not exist on type `Logger`. That's reasonable, but it'd be great if we could instead define `myLogger` with:

```typescript
const myLogger: infer Logger = console;

startServer(myLogger); // ok

myLogger.warn('abc'); // ok - myLogger has type `Console`
```

And then when using it, we'd have all of the other methods/properties available on `console`. Adding `infer` to the type definition basically means that the type of `const myLogger` is inferred as if there were no type definition, but the compiler makes sure that the assignment (` = console`) conforms to the `Logger` interface.

The solution right now is to leave `myLogger` with no explicit typedef. This has the downside of putting errors in "the wrong place", which could be far from the where the error happened:

```typescript
// can't add `: Logger` type annotation because it'll stop me implementing `warn`:
const myLogger = {
  log: (message: string) => console.log(message), // no error, even though I implemented `log` instead of `info`
  warn: (message: string) => console.warn(message),
}

createServer(myLogger); // error here, but this isn't where the mistake is
```

If we could use the `infer` keyword in this way, the compiler would catch the mistake without erroring on the extra `warn` property:

```typescript
const myLogger: infer Logger = {  // error - type { log: ..., warn: ... } is not assignable to Logger
  log: (message: string) => console.log(message),
  warn: (message: string) => console.warn(message),
}
```

We could also gain the normal benefit of type inference benefits within the type (autocompletion, parameter inference, etc.):

```typescript
const myLogger: infer Logger = {
  info: message => console.info(message), // `message` has type `string`
}
```

## Alternatives

The `extends` keyword might work here too:

```typescript
const myLogger: extends Logger = console;
```

The existing workaround I've used a couple of times is to make a (run-time!) function just to constrain the type:

```typescript
const specifically = <T>() => <U extends T>(value: U) => value;

const myLogger = specifically<Logger>()(console); // myLogger has type `Console`

const badLogger = specifically<Logger>()({ log: msg => console.log(msg) }); // error - property info is missing
```

But that's very awkward/hacky, and as a library author not something most people would want to tell their users to do. 

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code - _`infer` usage is currently a syntax error without `extends`
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Use cases here align with #7481

**Comment by jcalz** [comment]
I suppose #32794 is the currently open version of this?  `satisfies` is implemented but this feature is not.
