### ISSUE TITLE
Private method in derived class breaks the class decorator

### ISSUE THREAD

**Issue by volo-maslow** [microsoft/TypeScript#38341]
**TypeScript Version:** 
vNightly or 3.8.3

**Search Terms:**
decorator, constructor, derived class private method

**Code**
A full example can be shown at [this snippet](https://www.typescriptlang.org/play/?experimentalDecorators=true&ts=4.0.0-dev.20200504#code/MYGwhgzhAEAyD2BzRBTATtA3gWAFDQOgAcBXAIxAEthoQkAKASgC5oA3eSgEyz0P+jB4AOwjwQKAHR1E9AESUALgHIYYWkgCEcxgG4+hAL55juPJWGL0AMzDAU0AJIAJMMK4SMOfISJp49lBM0Kwc3Pq4pnhgZBCKaHaKguBQ0K7untCUALZEEtkoljAubh7ovGY+BH7wVsBWPDKoaKwIyOgRBgRCovEk9fBo9E3orUjNjBUChIoAFpQQ0uPlALwa7WgR-FFVxORUNDFxCfXE-oEQTKGcXCZ4eIoAnkQOAMIix-2KgwA8ACoAPmga280wIwhQAHd6GgUERBlYWnBlmgWNA-lswbCwFwRCBHmdarVnihWBi7pVrCRhPVKCJoLDEAtEf9oCgAB5Wdwwd69NBfX7pMpoAEA+gAawsXFYxwsiEmoMIsMUJDQwmg9AGSL+kxWQMV0x6Ygkkgs1ng9AABgAlFBMuLoFA8dSzUqZc0YAAkmEl7kMlr0XQEAHpg9BXRl0BBbfb4o9JDiuBKpQAaQTfVGY6bK1XqrVZ6CmHYAAUZzPQ8khs3EYB0eFAkBgfxJAEEuFwnULMhyuVwYF3yt4g6QKNRCRcruwblMwXMFksNgumAWdvxQ2dKGwwFYspZ0MIwCAAArnFBBBXQIPr-hG8RSGTyWbZZ-ZAD8OgL66LQA)

```ts
type Constructor<T> = {
        new(reporter: Logger): T;
        readonly prototype: T;
}

function register<T extends Constructor<Handler>>(kind: string) {
    return (ctor: T) => {
        console.info(`Registered a handler for ${kind}`);
        // handlersRegistry.add(kind, ctor);
        return ctor;
    }
}

abstract class Handler implements IHandler {
    protected logger: Logger;

    constructor(logger: Logger) {
        this.logger = logger;
    }
    public abstract process(): void
}

@register("whola")
export class TypeAddedHandler extends Handler {

    public process(): void {
        this.logger.log();
    }

    // private internalProcess() { 
    //     console.log("hmmmm?");
    // }
}
```

**Expected behavior:**
The private methods are ignored and no compilation errors occur, the decorator is applied to child classes.

**Actual behavior:**
After uncommenting a private method in child, the decorator stops work with TS1238:
>  Unable to resolve signature of class decorator when called as an expression.
>   Type 'Constructor<Handler>' is not assignable to type 'typeof TypeAddedHandler'.
>     Type 'Handler' is missing the following properties from type 'TypeAddedHandler': internalProcess

**Playground Link:**
[Playground](https://www.typescriptlang.org/play/?experimentalDecorators=true&ts=4.0.0-dev.20200504#code/MYGwhgzhAEAyD2BzRBTATtA3gWAFDQOgAcBXAIxAEthoQkAKASgC5oA3eSgEyz0P+jB4AOwjwQKAHR1E9AESUALgHIYYWkgCEcxgG4+hAL55juPJWGL0AMzDAU0AJIAJMMK4SMOfISJp49lBM0Kwc3Pq4pnhgZBCKaHaKguBQ0K7untCUALZEEtkoljAubh7ovGY+BH7wVsBWPDKoaKwIyOgRBgRCovEk9fBo9E3orUjNjBUChIoAFpQQ0uPlALwa7WgR-FFVxORUNDFxCfXE-oEQTKGcXCZ4eIoAnkQOAMIix-2KgwA8ACoAPmga280wIwhQAHd6GgUERBlYWnBlmgWNA-lswbCwFwRCBHmdarVnihWBi7pVrCRhPVKCJoLDEAtEf9oCgAB5Wdwwd69NBfX7pMpoAEA+gAawsXFYxwsiEmoMIsMUJDQwmg9AGSL+kxWQMV0x6Ygkkgs1ng9AABgAlFBMuLoFA8dSzUqZc0YAAkmEl7kMlr0XQEAHpg9BXRl0BBbfb4o9JDiuBKpQAaQTfVGY6bK1XqrVZ6CmHYAAUZzPQ8khs3EYB0eFAkBgfxJAEEuFwnULMhyuVwYF3yt4g6QKNRCRcruwblMwXMFksNgumAWdvxQ2dKGwwFYspZ0MIwCAAArnFBBBXQIPr-hG8RSGTyWbZZ-ZAD8OgL66LQA)

**Related Issues:**
No related issues found yet.

**Comment by rbuckton** [comment]
The issue is that the `T` in `register<T...>` doesn't have enough context when applied as a decorator factory. If you move the `T` to the decorator function inside of `register`, then there is no error:

```ts
function register(kind: string) {
    return <T extends Constructor<Handler>>(ctor: T) => {
        console.info(`Registered a handler for ${kind}`);
        // handlersRegistry.add(kind, ctor);
        return ctor;
    }
}
```

I will look into whether we can improve contextual type inference for this case.

**Comment by rbuckton** [comment]
I'm not certain there's an error here. I've verified our contextual type behavior is the same for decorators here as for a regular call:

```ts
const _TypeAddedHandler: typeof TypeAddedHandler = register("whola")(TypeAddedHandler);
//    ~~~~~~~~~~~~~~~~~ - same error as when used with a decorator.
```

This behavior seems consistent with our current call behavior. I would recommend my suggestion above and move the type parameter to the arrow function inside of `register`.
