### ISSUE TITLE
Regression: DTS emit

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#38356]
Works in TS `3.9.0 beta` but not in `nightly (4.0.0-dev.20200505)`

Code:
```js
class X {
    /**
      * Cancels the request, sending a cancellation to the other party
      * @param {Object} error __auto_generated__
      * @param {string?} error.reason the error reason to send the cancellation with
      * @param {string?} error.code the error code to send the cancellation with
      * @returns {Promise.<*>} resolves when the event has been sent.
      */ 
    async cancel({reason = "User declined", code = "m.user"} = {}) {}
}
```

Playground:

https://www.typescriptlang.org/v2/en/play?ts=4.0.0-dev.20200505&useJavaScript=true#code/MYGwhgzhAEAa0G8CwAoa7oHoBU3UY22gGEwA7YAUxBgBcALS6AJ0oEcBXSiWgGmgiUyAEwCWZAObQw0YOSohwtUQHsy0Wio2NoKhpWbQADmGa0AnvgLQiAARPMwAW0QB5AEYArSsFoBfaANmFUMAfVCwDk1QiSEDMFpKYXCrAjsHZ0QeZnEJAH4AoJCAOlZINW0mIsMyiArNASFhStl5aiVVdQB3UQZUwmh7U0yEbNyCwOZg5mLgFWEmfUnp2XnFrUERFrkKdoTO6B6+tGs7VloOZjIYBAAFYKdRQWKAHmwAPgDWOpAAN25Dox1EtKP8yLRoPRINB3JQhI1wcV+uhsJhoP1IOYKK1diAABQIWoVAC80AARABVQSGBagcRJMn8OYLaCkslOYocalkgKkhB+ACUiD8qFQfiAA

Old output:
```ts
declare class X {
    /**
      * Cancels the request, sending a cancellation to the other party
      * @param {Object} error __auto_generated__
      * @param {string?} error.reason the error reason to send the cancellation with
      * @param {string?} error.code the error code to send the cancellation with
      * @returns {Promise.<*>} resolves when the event has been sent.
      */
    cancel({ reason, code }?: {
        reason: string;
        code: string;
    }): Promise<any>;
}
```

New output (invalid): 
```ts
declare class X {
    /**
      * Cancels the request, sending a cancellation to the other party
      * @param {Object} error __auto_generated__
      * @param {string?} error.reason the error reason to send the cancellation with
      * @param {string?} error.code the error code to send the cancellation with
      * @returns {Promise.<*>} resolves when the event has been sent.
      */
    cancel({ reason, code }?: 
     * @param {?string} error.reason the error reason to send the cancellation with
     * @param {?string} error.code the error code to send the cancellation with
    ): Promise<any>;
}
```

**Comment by Jack-Works** [comment]
Another problem:

```js
/**
 * @param {Array} x
 */
function x(x) {}
/**
 * @param {Promise} x
 */
function y(x) {}
```

In 3.9.0 beta:
```ts
/**
 * @param {Array} x
 */
declare function x(x: any[]): void;
/**
 * @param {Promise} x
 */
declare function y(x: Promise<any>): void;
```

In nightly:
```ts
/**
 * @param {Array} x
 */
declare function x(x: Array): void;
/**
 * @param {Promise} x
 */
declare function y(x: Promise): void;
```

Notice the missing generics make it invalid

**Comment by DanielRosenwasser** [comment]
@weswigham this is a 3.9 regression - I think it'd be best to just never reuse type nodes if they come from a JS file.

**Comment by weswigham** [comment]
@DanielRosenwasser too late - https://github.com/microsoft/TypeScript/pull/38368 has the fix. We have code explicitly mapping jsdoc constructs to ts type constructs, it was just missing the jsdoc object literal form, and didn't account for how we allow missing type parameters (even without defaults) in JS.

**Comment by DanielRosenwasser** [comment]
My fear is just that there's another case we haven't covered. The assumption is that TS types are always "well formed" for declaration emit, but JS nodes aren't. As long as we're confident that there aren't other cases that we've missed, #38368 should be sufficient.

**Comment by weswigham** [comment]
As we add support for more jsdoc forms, we should check that we actually support declaration emit for those forms, same as we do for TS type nodes. If we could exhaustively check for node kinds so it's typesystem enforced, I would, but, ah, something something, compiler performance compiling itself is still kinda bad when `Node` is a union of all possible kinds?
