### ISSUE TITLE
Assigning never in generic types to broader types doesn't work when used in a function

### ISSUE THREAD

**Issue by fxedel** [microsoft/TypeScript#38363]
**TypeScript Version:**  3.8.2

**Search Terms:** never, unknown, any, generics, parameter

**Code**
```ts
// This works

interface SomeGeneric<T> {
  name: string;
}

const neverGeneric: SomeGeneric<never> = {
  name: `With never in generics`
};

const unknownGeneric: SomeGeneric<unknown> = neverGeneric;


// This doesn't work

interface SomeGenericWithFunction<T> {
  name: string;
  foo: (a: T) => string;
}

const neverGenericWithFunc: SomeGenericWithFunction<never> = {
  name: `With never in generics`,
  foo: () => `bar`
};

const unknownGenericWithFunc: SomeGenericWithFunction<unknown> = neverGenericWithFunc;
```

**Expected behavior:**

The code compiles, as `unknown` is a superset of `never`.

**Actual behavior:**

The last line `const unknownGenericWithFunc: SomeGenericWithFunction<unknown> = neverGeneric;` fails with following error:

```
Type 'SomeGeneric<never>' is not assignable to type 'SomeGeneric<unknown>'.
  Type 'unknown' is not assignable to type 'never'.ts(2322)
```

Assigning never in a generic type to a broader type like `unknown`, `any` or even `string` works in general, except in the case that this generic is used as a parameter type of a function of the interface. I don't think that's the intended behavior.

<details><summary><b>Output</b></summary>

```ts
"use strict";
// This works
const neverGeneric = {
    name: `With never in generics`
};
const unknownGeneric = neverGeneric;
const neverGenericWithFunc = {
    name: `With never in generics`,
    foo: () => `bar`
};
const unknownGenericWithFunc = neverGeneric;
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=28&ssc=1&pln=1&pc=1#)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Please see the FAQ regarding interfaces that don't use their type parameter.

This error is correct; `unknown` is a superset of `never` but `T` is used in a contravariant position, so it would need to be a *subset* for this to be legal. A function with a `never` parameter should never legally observe itself being invoked, but `unknownGenericWithFunc.foo("")` would cause `neverGenericWithFunc` to be invoked.

**Comment by fxedel** [comment]
Okay, it took me a time understanding why a function's parameter types are handled just the other way round than its return types, but it definitely makes sense. Thanks!
