### ISSUE TITLE
Suggestion: better type printing for JSX IntrinsicElements

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#38362]
Now:

`Type '{ class: string; }' is not assignable to type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.`

Suggest:

`Type '{ class: string; }' is not assignable to type '<a />'.`

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
