### ISSUE TITLE
Broken method inheritance, superclass calls subclass method

### ISSUE THREAD

**Issue by giacomoferlaino** [microsoft/TypeScript#38361]
**TypeScript Version:**  3.8.3

**Search Terms:** inheritance, method, superclass, subclass

**Code**

```ts
class SuperClass {
    get(key: string): void { 
        console.log('SuperClass GET:', key);
    }

    set(key: string, value: string): void { 
        console.log('SuperClass SET:', key, value);
    }

    update(key: string, value: string): void {
        this.get(key);
        console.log('SuperClass UPDATE:', key, value);
        this.set(key, value)
    }
}

class SubClass extends SuperClass { 
    private fixedKey: string = 'key';

    get(): void { 
        console.log('SubClass GET:', this.fixedKey);
        super.get(this.fixedKey);
    }

    set(value: string): void { 
        console.log('SubClass SET:', value);
        super.set(this.fixedKey, value)
    }

    update(value: string): void {
        console.log('SubClass UPDATE:', value);
        super.update(this.fixedKey, value);
    }
}

const superClass: SuperClass = new SuperClass();

const subClass: SubClass = new SubClass();

subClass.update('testValue')
```

**Expected behavior:**

The context of the superclass should be separated from the context of the subclass.
The superclass shouldn't be able to call/access methods from the subclass.
Once a method call is forwarded to the superclass using super.method() the superclass should use its own methods and not the one provided by the subclass that forwarded the method call.

Expected console output:
```
SubClass UPDATE: value
SuperClass GET: fixedKey
SuperClass UPDATE: fixedKey value
SuperClass SET: fixedKey value
```
_Executed using Java class inheritance, same code structure: [**online code sample**](https://repl.it/repls/FumblingMeaslyBash)_

**Actual behavior:**

When the method call is forwarded to the superclass using super.method() and the method of the superclass has a this.method2() call inside, it ends up calling subclass(method2) instead.

Actual console output:
```
SubClass UPDATE: value
SubClass GET: fixedKey
SuperClass GET: fixedKey
SuperClass UPDATE: fixedKey value
SubClass SET: fixedKey
SuperClass SET: fixedKey fixedKey
```

**Playground Link:** [**Code sample link**](https://www.typescriptlang.org/play/#code/MYGwhgzhAEDKCuAHApgJwMLitA3gKGkOgHNkAXACgGtkBPALmgjNQEsA7YgSkYDcB7VgBNc0AkQnB+7CPxDIAdCH7EKAcgQoMWGAHEAogBV6agDTQatLgG5xhAL547TctTqNmbTud5gQ8ZA8WDm4+QREcMQlJaVl5JRV1TTRMSBhYIxNzSx8-AJtnR2ckITAyZDcGJmDvaF9-QOqvULrw3GcJMgALVggFUkpLAuiiKRk5RWVVDSQUnWgAVQAFABEAQUN9LIs6XIbhkehu3oUIVxy6vOQuQrwi0DS4eAAjVOxkAA9y9iF02e1HpFnIg2L5ytAAGasD7IIQAaXcTRC0AAvNA1FCYfC6GpbM4BhQeK1hKIOqNYhMEtMEK95gZjGYjj0+pjYQirLZDkx-v1XMcWdC2XQDg4nBIzpR6gEgs0iQISUCuWM4pNEjNaY8Mgy9vlOYcIDyJRR+QpWdjaDrrrdiohSuUKFLGp4QnK2vglRT4lMki83jBlutNttHSLogatAoSmUKiazezLaHHPdYmRuVo-YxkgDsGj2MgAO5PdM6Ql45Wpg0aqCZ33zXMFp5ViClpyVv2R23R9SOtRcIA)

**Related Issues:**

**Comment by nmain** [comment]
> Executed using Java class inheritance, same code structure:

Java is not javascript.  The behavior is correct, and you can see that by running just the pure javascript code (without the type annotations) in any javascript environment that natively supports classes.

**Comment by giacomoferlaino** [comment]
That Javascript is not Java is quite clear.
The two languages are fundamentally different in a lot of aspects.

This kind of behaviour is related to Javascript too, and that's why I also created a Typescript Playground sample, to see how it would be translated.

My point is, wouldn't it be better/useful to create an abstraction inside TypeScript to have a better inheritance implementation?

**Comment by nmain** [comment]
Making typescript have different runtime behavior is one of the non goals of typescript https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals 

>better inheritance

/shrug.  As someone who uses C# daily (which supports this feature as well), I try to avoid member hiding.

Either way, you'd have to take it up with TC-39 and they're not likely to rework javascript classes entirely.

**Comment by giacomoferlaino** [comment]
@nmain I see your point now. I should have not opened this as a bug but as a question/discussion at most, even though as you pointed out:

> behavior is one of the non goals of typescript

I don't think they would rework classes entirely either.
I just find really confusing the fact that they gave the possibility of using class inheritance and then the implementation is everything but predictable, at least for me, given that the superclass can call a subclass method.

I also understand that JavaScript works around prototype and object composition, but I found this implementation of class and the related inheritance confusing.

I guess I will just have to get used to it for the time being.
Thanks for the discussion anyway.
