### ISSUE TITLE
Switch statements should discriminate by class prototype

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/TypeScript#38373]
**TypeScript Version:**  Nightly (4.0.0-dev.20200505)

**Search Terms:**

- switch
- control flow
- discriminated union
- untagged union
- disjoin
- prototype
- constructor
- 2339

**Code**
```ts
class Failure {}

class Success {
    constructor(readonly value: string) { }
}

function main(result: Failure | Success): void {
    switch (result.constructor) {
        case Success:
            console.log(`Success! Your value is ${result.value}`); // Property 'value' does not exist on type 'Failure | Success'.
            break;
        case Failure:
            console.log('Oh noes');
    }
}

main(new Success("🍆"));

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class Failure {
}
class Success {
    constructor(value) {
        this.value = value;
    }
}
function main(result) {
    switch (result.constructor) {
        case Success:
            console.log(`Success! Your value is ${result.value}`); // Property 'value' does not exist on type 'Failure | Success'.
            break;
        case Failure:
            console.log('Oh noes');
    }
}
main(new Success("🍆"));

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200505&ssl=19&ssc=1&pln=29&pc=2#code/MYGwhgzhAEBiYEsQFcBOBTaBvAvgKD1EhgGVlhh0ps9o7pgB7AOwgBdVy3HUAKDMABMWIAJ7QAbmBToAXNHaoEzAOYBKbNHz48AM2TNgbBC2gBbRM35VkINvPhI0mAD7QyFKhDXyJjBII09AoA7ghswAAW0NYQtmwAdEysHFw8Gli0wfTAkJgelFCyWdnZyRCMIOgJIIwqvAAGBV4AhNAAmoxoktLImAgwACRYGHF2CVIyOA1qANzQAPQL0AAKqIwADuiobOIA5JN9e9DCVNDMjGzQ6AAeA1emu1vQe44oGNBuzVB7CQSlpQARgIANYlMp5OCId5ycEAhgsCpVGp1Xh7ADy0QuVD2c3B2gIFmUvGY6BC7nIhQgvAARIAeDcAYvs0tR4oA)
      

**Expected behavior:**

No compile-time error. `result.value` should be of type `string`. That's what is happening in runtime.

**Actual behavior:**

We get a type error.

```
Property 'value' does not exist on type 'Failure | Success'. (2339)
```

Note that it works if you use `if` statements.

```ts
class Failure {}

class Success {
    constructor(readonly value: string) { }
}

function main(result: Failure | Success): void {
    if (result instanceof Success) {
        console.log(`Success! Your value is ${result.value}`);
    }

    if (result instanceof Failure) {
        console.log('Oh noes');
    }
}
```

**Comment by RyanCavanaugh** [comment]
This code doesn't work in the presence of e.g. `class GreatSuccess extends Success { ... }` - is this an intentional gap?

**Comment by karol-majewski** [comment]
It's not — I haven't considered subclass relationships.

A bit of context. I'm using classes to construct value objects. They are never inherited from. My program yields well-defined results such a `Success<T>`, `Failure`, or a `Timeout`. These types form a union. I was looking for a neat way to disjoint that union. A `switch` statement seemed appropriate.

**Comment by RyanCavanaugh** [comment]
Duplicate #16035
