### ISSUE TITLE
JavaScript runtime error : Unable to get property 'flags' of undefined or null reference

### ISSUE THREAD

**Issue by gooddaytoday** [Microsoft/TypeScript#3837]
Installed Typesscript 1.5 and have found bug of compiler:

tsc.js(16127, 17) JavaScript runtime error : Unable to get property 'flags' of undefined or null reference

**Comment by gooddaytoday** [comment]
I don't know how to catch the point in my project, that causes this error. Can somebody show me docs/tutorial?

**Comment by gooddaytoday** [comment]
Ok, I have found guilty code. I am using branch of 1.5 with async/await. So, Visual Studio doesn't highlight mistake of incompatible types of abstract functions and its implementation.

Abstract function:
```javascript
@abstract
protected AsyncFunction(): SomeObjType<T>
{
}
```

And implementation:
```javascript
@override
protected async AsyncFunction(): SomeObjType<T>
{
    let =  await  SomeVar;
}
```

And there are no highlighted errors in Visual Studio, but compiler saying: "Unable to get property 'flags' of undefined or null reference".

**Comment by DanielRosenwasser** [comment]
Are you using the async/await branch or are you using TypeScript 1.5 beta? The async/await branch is slightly out of date and not necessarily meant for consumption; still, this might be a useful test case/

**Comment by mhegazy** [comment]
As @DanielRosenwasser mentioned. we are working on cleaning up that branch and getting it in master for the next release.
