### ISSUE TITLE
Generating Type Definitions from Javascript is blocked by requiring private name

### ISSUE THREAD

**Issue by stephenash** [microsoft/TypeScript#38382]
**TypeScript Version:**  3.8.3, 4.0.0-dev.20200506

**Search Terms:**
- Declaration emit for this file requires using private name
- An explicit type annotation may unblock declaration emit
- Static class members

**Code**

```js
// that-hard-math-static.js
/**
 * @class
 */
var ThatHardMathStatic = {};

/**
 * @memberof ThatHardMathStatic
 * 
 * @param {number} a
 * @param {number} b
 */
ThatHardMathStatic.add = function(a, b) {
  return a + b;
}

module.exports = ThatHardMathStatic;

// index.js
var ThatHardMathStatic = require('./that-hard-math-static.js');

module.exports = { ThatHardMathStatic: ThatHardMathStatic };
```

**Expected behavior:**
Creating declarations works

**Actual behavior:**
```
index.js:1:1 - error TS9006: Declaration emit for this file requires using private name 'ThatHardMathStatic' from module '"/home/runner/BitterApprehensivePdf/that-hard-math-static"'. An explicit type annotation may unblock declaration emit.

1 var ThatHardMathStatic = require('./that-hard-math-static.js');
  ~~~
```

```typescript
// that-hard-math-static.d.ts
export declare function add(a: number, b: number): number;
```

Looks like the `add` function was exported as a top level export instead of inside of a class/object.

**Playground Link:** https://repl.it/@stephenash/BitterApprehensivePdf
Open shell and run `npm run build` to trigger error

**Related Issues:** 
- https://github.com/microsoft/TypeScript/issues/37832

**Comment by weswigham** [comment]
This no longer repros in our latest builds (I'm pretty sure another, more recent report was essentially the same thing and got fixed). ❤️
