### ISSUE TITLE
Cannot export self module as default

### ISSUE THREAD

**Issue by Fenzland** [microsoft/TypeScript#38387]
**TypeScript Version:**  3.8.3

**Search Terms:**
module import export circular

**Background**
I use to write module like this:
```javascript
// module.js
export { foo, bar, baz, };
export * as default from './module.js'; // path of current file itself.
```
Then we can import the module with both to ways:
```javascript
import { foo, } from './module.js';
import Module from './module.js';

Module.foo === foo; // true
```
That's work fine with JavaScript but not TypeScript.

**Code**

```ts
// module.ts
export * as default './module.ts';
```

**Expected behavior:** works like JavaScript.

**Actual behavior:**
```bash
error TS1359: Identifier expected. 'default' is a reserved word that cannot be used here.
export * as default from './module.ts';
            ~~~~~~~
```

So I modify my code to:
```ts
// module.ts
import * as Module './module.ts';
export default Module;
```
This works fine with JavaScript too, but not TypeScript again.

**Expected behavior:** works like JavaScript.

**Actual behavior:**
```bash
error TS2303: Circular definition of import alias 'Module'.
import * as Module from './test.ts';
       ~~~~~~~~~~~
```

I modify my code again to:
```ts
// module.ts
import * as Module './module.ts';
export default (Module);
```

It finally works, both JavaScript and TypeScript.

**Comment by rbuckton** [comment]
This was fixed by #39803 and shipped in TS 4.1.
