### ISSUE TITLE
Support TSX/JSX formatting

### ISSUE THREAD

**Issue by manishtpatel** [Microsoft/TypeScript#3838]
Right now formatting is supported or not right.

As you see below it just removes all indentation from JSX, i would prefer that we leave jsx code out of formatting if can't be supported right now, this makes formatting completely useless in TSX files.

If i understand this correctly then typescript has formatting capability and which is being used by atom-typescript in the sample below.

Original Code
![image](https://cloud.githubusercontent.com/assets/249478/8654236/22de6136-2957-11e5-9fb9-5b7c6f7c4f4c.png)

Formatted Code 
![image](https://cloud.githubusercontent.com/assets/249478/8654255/3a4026c0-2957-11e5-8129-ee7b64856fc3.png)

**Comment by mhegazy** [comment]
@vladima or @SaschaNaz if either is interested in this issue, please feel free to send a PR and will pull it in.

**Comment by mhegazy** [comment]
thanks @SaschaNaz !

**Comment by manishtpatel** [comment]
Need some tweaking

                    <h5 className="level-text">
                      <span className="custom-radio">
                        <span className={checkIfSelected}></span>
                      </span>
                      <span className={checkedClass}>{levelText}</span>
                    </h5>


Getting formatted to

                    <h5 className="level-text">
                      <span className="custom-radio">
                        <span className={checkIfSelected}></span>
                          </span>
                      <span className={checkedClass}>{levelText}</span>
                        </h5>

Looks like it doesn't track closing elements properly yet

**Comment by mhegazy** [comment]
@SaschaNaz wanna take another look?

**Comment by SaschaNaz** [comment]
@mhegazy Sure. It looks like I hurried up too much :/

@manishtpatel How did you employ the latest master branch on Atom? I couldn't really make it work on it, so I just added the test and thought it's okay now. Sorry for that.

**Comment by manishtpatel** [comment]
@SaschaNaz atom-typescript does not support  "Edit -> Lines -> Auto Indent", Ctr+Alt+L should do it.

I verify using two methods, atom-typescript Ctr+Alt+L and directly using typescript@next nightly build.

**Comment by alexgorbatchev** [comment]
Also experiencing this.

```js
export default class Application extends React.Component<any, any> {
  render() {
    return (
      <div>
        <Component name="World" kind={ComponentKind.warning} />
      </div>
    );
  }
}
```

results in

```js
export default class Application extends React.Component<any, any> {
  render() {
    return (
      <div>
        <Component name="World" kind={ComponentKind.warning} />
        </div>
    );
  }
}
```

**Comment by DanielRosenwasser** [comment]
@alexgorbatchev that's just a matter of time constraints. 1.7 should be going out soon, so there really isn't a way to get this in for it.

**Comment by olmobrutall** [comment]
Hi, first of all thank you for your great work. I've been using Typescript since the beginning and, since then, I feel at home building Web apps. 

I was initially surprise that you find time to include JSX support, given that XML literals was never added to C#, but I quickly realize that in this case was much more justified: The relationship of Javascript with HTML is much stronger, and the feature is only enabled in .tsx files. 

Since them I've started to rebuild our framework using react (https://github.com/signumsoftware/framework/wiki/Signum-React). 

In theory it's going to be awesome, with a templating technology that has all the expressivity of modern ES6, strongly typed bindings, and interface definitions auto generated from C#. 

In practice however some problems make the experience very frustrating:
 
* Errors in TSX elements formatting.
* Lack of colorization https://github.com/Microsoft/TypeScript/issues/4835, 
* No auto-close when writing html tags (in the Visual Studio 2015). 

I know the comment is not very concrete, just a heads-up that there's at least one developer that will be veeery hapy if this gets solved.

**Comment by DanielRosenwasser** [comment]
This should be fixed. Try it out with our nightly in a few hours.

**Comment by rent-a-developer** [comment]
> This should be fixed. Try it out with our nightly in a few hours.

Where can I get the nightly build?
I only found nightly builds for the compiler and the msbuild tasks, but don't you also need a new version of the TS Visual Studio Integration for the formatting to work?

**Comment by olmobrutall** [comment]
+1 to how to make it work in VS

**Comment by olmobrutall** [comment]
Works great in 1.8! Thanks!

**Comment by rent-a-developer** [comment]
> Works great in 1.8! Thanks!

How did you get it working in VS with TS 1.8?

**Comment by matijagrcic** [comment]
> How did you get it working in VS with TS 1.8?

Download and install [TypeScript_Dev14Full.exe download](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS1.8.1-Beta-TS-master.20160126.1/TypeScript_Dev14Full.exe)

**Comment by rent-a-developer** [comment]
@matijagrcic Thank you very much!

Where did you found this link?
Does a build of the TS tools exist for VS 2013?

**Comment by matijagrcic** [comment]
> Where did you find this link?
> Does a build of the TS tools exist for VS 2013?

Just go to [Announcing TypeScript 1.8 Beta](http://blogs.msdn.com/b/typescript/archive/2016/01/28/announcing-typescript-1-8-beta.aspx) and in the first paragraph you'll see the following.

>TypeScript 1.8 beta is available for [Visual Studio 2015](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS1.8.1-Beta-TS-master.20160126.1/TypeScript_Dev14Full.exe)

**Comment by rent-a-developer** [comment]
Perfect. Thank you very much!
I am looking forward for the TS 1.8 Tools for VS 2013!
(VS 2015 does not work well for my project, I guess the ReSharper implementation for VS 2015 is screwing up things.)

**Comment by wbhob** [comment]
Any news on TSX formatting? Noticed this hasn't really been touched in a while.

**Comment by rooch84** [comment]
I'm having the same issue with JSX attributes not indenting properly in .tsx files.  Is there any plan to fix this?
