### ISSUE TITLE
Transform a string literal type into a value at compile time. 

### ISSUE THREAD

**Issue by kuberlog** [microsoft/TypeScript#38384]
## Search Terms
"string literal type"
"string literal type value"

## Suggestion

Given a named string literal type, when I attempt to use that type as a value, the compiler will inline the value of the string literal.

## Use Cases

This would be very helpful for switching on discriminated unions. Right now there is no way to do a switch on a string literal without duplicating that literal in both the type and the value used in the cases.

## Examples

```
// action.ts
export interface Initialize {type: "INITIALIZE", payload: InitializePayload};
export interface Update {type: "UPDATE", payload: UpdatePayload};

export type Action = Initialize | Update;

// reducer.ts
// .. imports ..
function(state: State, action: Action) {
  switch(action.type) {
    case Initialize.type: return stateFromInitialize(state, (action as Initialize).payload)
    case Update.type: return stateFromInitialize(state, (action as Update).payload)
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
Technically can't check this off, but explicitly using a type as a value isn't really an "expression" at the moment. 

* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)

* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
Eh, it kindof violates: "Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.", although I don't think this would require runtime metadata. The string literal type could be inlined as a JS string literal.

**Comment by nmain** [comment]
How are `const enum`s not a sufficient solution to this?

**Comment by kuberlog** [comment]
Sorry, `const enum`s are a sufficient solution to this.
