### ISSUE TITLE
readonly attribute only being checked on a first level, instead of deep check all the way down

### ISSUE THREAD

**Issue by helios1138** [microsoft/TypeScript#38392]
**TypeScript Version:**  3.8.3

**Code**

```ts
interface Some {
  field: string
}

function test(arr: readonly Some[]) {
  arr[0].field = '3' // trying to prevent this
}

const s: readonly Readonly<Some>[] = [{ field: 'some' }]

test(s) // this should not be allowed
```
```ts
interface Some {
  field: string
}

function test(arr: Readonly<{ field: Some }>) {
  arr.field.field = '3' // trying to prevent this
}

const s: Readonly<{ field: Readonly<Some> }> = { field: { field: 'some' } }

test(s) // this should not be allowed
```

**Expected behavior:**
It should NOT be possible to pass a readonly array of readonly objects as an argument to a function which takes readonly array of NON-readonly objects. Same for readonly objects containing fields that are themselves readonly objects

**Actual behavior:**
Typescript correctly prevents only assignments which do not match the first level of readonly markers, but it does not check if the structure matches deeply

**Playground Link:** https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=13&pc=8#code/JYOwLgpgTgZghgYwgAgMoHsC2KDeAoZQ5GYCAGwBMAuAZzClAHM8BfPPGAVxATGHRDJIdABRwoUKsgBKEOBQFkAngB4cxUpSkZsyFgD4AlMnxFk4qADoS5Ctc0VkAXmQByAMyvW7PAgF1kGilZeUVVdRstGTkFEGUVHQh9PWSXCIcpdNspVxosCFc9PR9hMBEaQyA

**Comment by RyanCavanaugh** [comment]
`Readonly` is not recursive. You can read its definition:
```ts
type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};
```

**Comment by helios1138** [comment]
@RyanCavanaugh that's not what I was saying. Did you look at the code I provided?

**Comment by RyanCavanaugh** [comment]
`readonly`ness isn't checked as part of assignability

**Comment by helios1138** [comment]
@RyanCavanaugh 
> `readonly`ness isn't checked as part of assignability

It is being checked for arrays. And this makes the object behavior feel a bit inconsistent (since both use the same `readonly` keyword in definition):

this throws an error:
```ts
interface ObjectWithArray {
  a: number[]
}

interface ObjectWithReadonlyArray {
  a: readonly number[]
}

const readonlyObject: ObjectWithReadonlyArray = { a: [3] }
const object: ObjectWithArray = readonlyObject
// TS2322: Type 'ObjectWithReadonlyArray' is not assignable to type 'ObjectWithArray'.
//  Types of property 'a' are incompatible.
//    The type 'readonly number[]' is 'readonly' and cannot be assigned to the mutable type 'number[]'.
```
while this doesn't:
```ts
interface ObjectWithField {
  a: number
}

interface ObjectWithReadonlyField {
  readonly a: number
}

const readonlyObject: ObjectWithReadonlyField = { a: 3 }
const object: ObjectWithField = readonlyObject
// no error
```

**Comment by helios1138** [comment]
@RyanCavanaugh ^

**Comment by helios1138** [comment]
@RyanCavanaugh is it possible to get an answer to my last example?

**Comment by RyanCavanaugh** [comment]
@helios1138 `readonly number[]` is a readonly version of a type; `readonly x: number[]` is a readonly property. They are two different things; I was only referring to the latter.
