### ISSUE TITLE
Greek Yot (U+037F) - Invalid character. ts(1127)

### ISSUE THREAD

**Issue by charlesLoder** [microsoft/TypeScript#38396]
The character [GREEK CAPITAL LETTER YOT (U+037F)](https://www.fileformat.info/info/unicode/char/037f/index.htm) causes the error `Invalid character. ts(1127)`. No other Greek characters cause this. See this [repo](https://github.com/charlesLoder/greek-transliteration) if you need to see more.

No other characters from the Greek/Coptic block cause this issue. I cannot find any invalid characters in my code that would be causing this issue. 

**TypeScript Version:**  3.8.3 and tested with 4.0.0-dev.20200507

**Search Terms:** Invalid character, ts(1127)

**Code**

```ts
// src/grcCharsTrans.ts
type Dict = { [key: string]: string };
export const transliterateMap: Dict = {
  Α: "a", // GREEK CAPITAL LETTER ALPHA (U+0391)
  Β: "b", // GREEK CAPITAL LETTER BETA (U+0392)
  ...
  Ϳ: "", // GREEK CAPITAL LETTER YOT (U+037F)
}
```

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/8882

**VSCode**: 1.34.0 (yes, this is old; this is the highest version my os can support) Perhaps a VSCode issue?

fyi, this is my first time submitting an issue. Apologies if any pertinent information is missing!

**Comment by DanielRosenwasser** [comment]
This doesn't seem to repro in the playground or locally with the repo you provided. I do think there must have been some sort of problem elsewhere, maybe with how VS Code was sending bytes across the wire previously (UTF-8 vs. UTF-16 maybe?). Maybe @mjbvz knows more.

(Which OS are you on?)

**Comment by charlesLoder** [comment]
OSX 10.9.5

**Comment by mjbvz** [comment]
@charlesLoder I also can't repro this using up to date versions of VS Code. Please let us know if you see this on VS Code 1.45+
