### ISSUE TITLE
Occurrences highlighting should support the 'abstract' keyword

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3840]
```TypeScript
abstract class C {
    abstract foo();
    abstract bar();
}

abstract class D {
    abstract baz();
}
```

Occurrences for `abstract` on methods/properties in the same class should all get highlighted. They should potentially highlight their owning class's `abstract`. Not sure about `abstract` on `C` triggering `abstract` on `D`

**Comment by mhegazy** [comment]
looks like a bug-level change. @aozgaa can pick it up if he has time.

**Comment by DickvdBrink** [comment]
Might be a dumb question but asking it anyway xD

When I trigger the highlight on `abstract class C` should it highlight the members too?

**Comment by mhegazy** [comment]
i would say highlighting an `abstract` modifier for the class, should highlight all the abstract modifiers on members, and vice versa.

**Comment by mhegazy** [comment]
thanks @DickvdBrink
