### ISSUE TITLE
Rename previousValue to accumulator in reduce typings

### ISSUE THREAD

**Issue by BenLorantfy** [microsoft/TypeScript#38418]
## Search Terms

previousValue, accumulator

## Suggestion

I'm not sure where previousValue comes from, but everywhere I've seen reduce calls the first function the "accumulator".  For example, in the MDN docs it's calls this. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by BenLorantfy** [comment]
I made a small PR for this if it's something that's wanted: https://github.com/microsoft/TypeScript/pull/38417

**Comment by MartinJohns** [comment]
It's called `previousValue` in the ECMAScript spec: https://tc39.es/ecma262/#sec-array.prototype.reduce

> callbackfn is called with four arguments: the previousValue (value from the previous call to callbackfn), the currentValue (value of the current element), the currentIndex, and the object being traversed. The first time that callback is called, the previousValue and currentValue can be one of two values. If an initialValue was supplied in the call to reduce, then previousValue will be equal to initialValue and currentValue will be equal to the first value in the array. If no initialValue was supplied, then previousValue will be equal to the first value in the array and currentValue will be equal to the second. It is a TypeError if the array contains no elements and initialValue is not provided.

**Comment by BenLorantfy** [comment]
hmm I see. In practice I think people call this accumulator. Is it more important to be consistent with the spec or what people call it in practice? I'm not actually sure.

**Comment by MartinJohns** [comment]
I think in practice it's called `previousValue` as well. An accumulator is just one use-case, but `reduce` can be (and is) used without accumulating a value.

The decision is up to the TypeScript team of course.

**Comment by RyanCavanaugh** [comment]
I really don't want to get into the unending rabbit hole of "Is the name from the spec good enough". If the name is genuinely confusing we can reconsider, but this isn't.

**Comment by appdevopts** [comment]
I’m often confused about the meaning of the first argument, previousValue, and the second argument, currentValue, when coding with reduce(). They have a similar naming style (time-related adjectives + Value), which initially leads me to think they refer to the same kind of thing and share the same data type. However, this is not always the case.

In the current invocation of the callback function, previousValue refers to the return value of the previous callback call. This return value has the same type and kind as the initialValue provided to reduce().

Sometimes, I mistakenly think that previousValue is the previous item of currentValue, where currentValue represents the current item in the array being iterated over.

It maybe better if name the first argument in different style with the second one.
