### ISSUE TITLE
The requested module '@shopify/koa-shopify-auth' does not provide an export named 'verifyRequest'

### ISSUE THREAD

**Issue by petetnt** [microsoft/TypeScript#38420]
I am trying to import the library to node with experimental modules enabled (`node --expermental-modules server.js`, but the ESM loader claims that the export doesn't exist.

I have tried various other ways of importing like `{* as shopifyAuth}` but those don't seem to work either. I am not sure if this is an issue with TypeScript, Node's experimental modules or this library, but this is the only library giving me issues.

**TypeScript Version:**  3.8.3
**Node version:** 14.0.0

**Search Terms:**

export, named, @shopify/koa-shopify-auth, verifyAuth

**Code**

```ts
import createShopifyAuth, { verifyRequest } from '@shopify/koa-shopify-auth';
```

tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": false,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "outDir": "build"
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "server.ts"
  ]
}
```

command:

```
"start":  "tsc && node --experimental-modules ./build/server.js"
```

**Expected behavior:**

Everything works

**Actual behavior:**

The requested module '@shopify/koa-shopify-auth' does not provide an export named 'verifyRequest'

**Comment by petetnt** [comment]
Nevermind, apparently node doesn't support named exports

**Comment by Khivvi** [comment]
I am facing the same issue. Can you tell me how did you resolve it?
I am too getting 
 import createShopifyAuth, { verifyRequest } from "@shopify/koa-shopify-auth";
                                            ^^^^^^^^^^^
 SyntaxError: Named export 'verifyRequest' not found. The requested module '@shopify/koa-shopify-auth' is a CommonJS module, which may not support all module.exports as named exports.

**Comment by petetnt** [comment]
Hey @Khivvi, there's another issue in the correct repo: https://github.com/Shopify/koa-shopify-auth/issues/1

Cannot remember how I solved it myself, I think I just used the `esm` module loader
