### ISSUE TITLE
Union types get narrowed unexpectedly

### ISSUE THREAD

**Issue by mmktomato** [microsoft/TypeScript#38423]
**TypeScript Version:**
3.8.3 and Nightly

**Search Terms:**
* type inference
* union type
* narrowing
* callback
* function

**Code**

```ts
const fn1 = (cb: (n: number) => void) => {
    cb(0);
};

const fn2 = () => {
    let a: number | string = "";
    fn1(n => a = n);
    return a;
};

type T = ReturnType<typeof fn2>;  // T is string
```

**Expected behavior:**
I define `a` as `number | string` explicitly. So I expect `T` is `number | string`.

**Actual behavior:**
`T` is `string`.

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=nightly#code/MYewdgzgLgBAZmAjDAvDAFMARgLg2PMAVwFssBTAJwEpUA+GANxAEsATWlBgbwCgYBMbOgAM1ANy8AvpN6hIsBACZUGTj36CANuVgBDQqQqUYAHxjRKLMAHNVAInuTB8JOjD0Ye1WAmaBlLpElB56kjK8vFAAngAO5DAAKqoASkEhiXHkADwx8SBwrkp04gIA9GVJMCwQFlBWtkA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/9998

**Comment by nmain** [comment]
Two things going on here.

`a` is initially typed to `string`:
Duplicate of https://github.com/microsoft/TypeScript/issues/8513
My search terms were union narrowing assignment
Also see discussion in https://github.com/microsoft/TypeScript/issues/31734

`fn1(...)` does not reset the narrowing on `a`, or renarrow `a` to `number`:
Duplicate of #9998

**Comment by mmktomato** [comment]
Thank you. I understand the situation and the background.
Fortunately my case is enough to do like:
```ts
const fn2 = (): number | string => {
    // ...
};

type T = ReturnType<typeof fn2>;  // T is number | string
```
