### ISSUE TITLE
Check time regression between 3.8.3 and 3.9.1: ant-design

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#38432]
**TypeScript Version:**  3.9.1-rc

**Search Terms:**

Performance, Check Time

**Steps**

1. `git clone --depth=1 https://github.com/ant-design/ant-design`
2. `cd ant-design`
3. `npm install --ignore-scripts`
4. `tsc  --extendedDiagnostics --skipLibCheck --incremental false --pretty false -p tsconfig.json`

5-run averages:
3.8.3: Check Time = 8.41s
3.9.1: Check Time = 9.65s (15% slower)

**Comment by amcasey** [comment]
I'm currently plotting times for past commits to see if I can localize the regression(s).

**Comment by amcasey** [comment]
It looks like there might be a tiny regression post-36696, but no individual commit stands out, so I don't plan to file any additional sub-issues.

**Comment by amcasey** [comment]
Note that this issue refers specifically to check time, but the sub-issues track total time (since that was the easiest way to survey a lot of commits).

**Comment by lukasz-bendykowski-fluke** [comment]
Hi there! I was just investigating a significant decrease in building time for version 3.9 compared to 3.8 in our project. I've noticed it's mostly due to the Check time. For us, it's around 350 seconds slower. Diagnostics on `3.8.3` shows:

```
Files:                         3070
Lines:                       405935
Nodes:                      1625900
Identifiers:                 539792
Symbols:                     871886
Types:                       330409
Memory used:               1343413K
Assignability cache size:    195092
Identity cache size:           4617
Subtype cache size:           15051
Strict subtype cache size:    13683
I/O Read time:                3.79s
Parse time:                   2.79s
Program time:                10.71s
Bind time:                    2.14s
Check time:                  89.26s
transformTime time:           2.66s
Source Map time:              0.88s
commentTime time:             1.06s
I/O Write time:              16.30s
printTime time:              27.42s
Emit time:                   27.42s
Total time:                 129.53s
```

And on `3.9.3` shows:
```
Files:                         3070
Lines:                       405809
Nodes:                      1624933
Identifiers:                 539527
Symbols:                     934830
Types:                       385500
Instantiations:             1711202
Memory used:               1082037K
Assignability cache size:    219219
Identity cache size:           4609
Subtype cache size:           15220
Strict subtype cache size:    13107
I/O Read time:                8.93s
Parse time:                   2.80s
ResolveTypeReference time:    0.15s
ResolveModule time:           3.48s
Program time:                16.35s
Bind time:                    2.02s
Check time:                 403.45s
transformTime time:           2.51s
Source Map time:              0.99s
commentTime time:             1.08s
I/O Write time:              16.23s
printTime time:              27.54s
Emit time:                   27.54s
Total time:                 449.37s
```

**Comment by amcasey** [comment]
@lukasz-bendykowski-fluke Thanks for the feedback!  Given the magnitude of the regression, I'm assuming you're seeing something other than the ant-design slowdown.  Can you please file a new issue with more details and tag me?  Thanks!

**Comment by lukasz-bendykowski-fluke** [comment]
Yeah, sure, sorry, I thought ant-design is just an example here.

**Comment by ahejlsberg** [comment]
@amcasey Looks like this was already broken down to separate issues, so can we close this one?
