### ISSUE TITLE
Downlevel emit for template strings should use 'void 0' not 'undefined'

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#38430]
**TypeScript Version:**  3.9.x, 4.0.x-dev

**Search Terms:** template string emit

**Code**

From `~/tests/cases/conformance/es2018/invalidTaggedTemplateEscapeSequences.ts`:
```ts
const x = tag`\u{hello} ${ 100 } \xtraordinary ${ 200 } wonderful ${ 300 } \uworld`;
```

**Expected behavior:**

ES5/ES3 emit:
```js
const x = tag(__makeTemplateObject([void 0, void 0, " wonderful ", void 0], ["\\u{hello} ", " \\xtraordinary ", " wonderful ", " \\uworld"]), 100, 200, 300);
```

**Actual behavior:**

ES5/ES3 emit:
```js
const x = tag(__makeTemplateObject([undefined, undefined, " wonderful ", undefined], ["\\u{hello} ", " \\xtraordinary ", " wonderful ", " \\uworld"]), 100, 200, 300);
```

In ES5, `undefined` is an identifier and not a keyword and can be redeclared. In ES3, `undefined` isn't declared. In general we emit `void 0` in these cases.

This can be easily addressed by changing `createTemplateCooked` in `~/src/compiler/transformers/taggedTemplate.ts` to return `createVoidZero()` instead of `createIdentifier("undefined")` when a template contains an invalid escape sequence..

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html?target=0&ts=4.0.0-dev.20200507#code/MYewdgzgLgBAHjAvDKBDA5gAwDoFcDeAFgKYA2pIAvjACT4wCMADEzNdnFAE6ohcAmASzCouAT1r0ATCzYwA7uH7EuAM1ylJMAMyz2uRV1L9MAbgCwAKCA)

**Related Issues:** https://github.com/microsoft/TypeScript/pull/23801, https://github.com/microsoft/TypeScript/issues/12700

**Comment by lissein** [comment]
Hi, I'll work on this if it's ok.

**Comment by DanielRosenwasser** [comment]
Thanks @lissein!
