### ISSUE TITLE
Two functions of exactly same type returning type 'never' have different impact on control flow analysis and narrowing types

### ISSUE THREAD

**Issue by turtleflyer** [microsoft/TypeScript#38441]
**TypeScript Version:**  3.8.3

**Search Terms:**
Control flow analysis, type narrowing

**Expected behavior:**
There are two functions of type `() => never`. The first one is declared at the top level. The second function is returned by a high order function. Both are using in identical clauses where they serve narrowing types of variables. As both functions are of the exact same type and located in the exact same code structures so the result of their existence must be identical. They both have to narrow the types of the variables in the same manner.

**Actual behavior:**
The function of type `() => never` declared at the top-level truly influences the control flow analysis narrowing the type of the variable. But the second function does not affect on determining what type the variable has.

**Code**
```ts
type Throw = () => never;

declare const throwA: Throw // const throwA: Throw

declare function compThrow(): Throw

const throwB = compThrow(); // const throwB: Throw

declare const a: { foo?: () => void };
declare const b: { foo?: () => void };

const { foo: fooA } = a; // const fooA: (() => void) | undefined
const { foo: fooB } = b; // const fooB: (() => void) | undefined

if (!fooA) {
  throwA(); // const throwA: () => never
}

if (!fooB) {
  throwB(); // const throwB: () => never
}

fooA(); // const fooA: () => void

fooB(); // const fooB: (() => void) | undefined
        // Cannot invoke an object which is possibly 'undefined'.(2722)

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const throwB = compThrow(); // const throwB: Throw
const { foo: fooA } = a; // const fooA: (() => void) | undefined
const { foo: fooB } = b; // const fooB: (() => void) | undefined
if (!fooA) {
    throwA(); // const throwA: () => never
}
if (!fooB) {
    throwB(); // const throwB: () => never
}
fooA(); // const fooA: () => void
fooB(); // const fooB: (() => void) | undefined
// Cannot invoke an object which is possibly 'undefined'.(2722)

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAKgFgJwPYHcoF4oAoCUGB8UAdhAG4QIDcAsAFB0AmEAxgDYCGC0zSRAzsCjBEqAIIAuWCLQB6GVB79Bw5CglTVdRiw5coAMwCuRZsACWvBUgC2YeKtyT7qLbUUCh0gEIYrt5yi4lFByVkqeql5O0q5MbJzcvB7skgDeBkhIAPySuARQpEhmDFAAvjS0cbqJ4QBGaRnZuXjohIXFZRV07oLp+pmS-UiiZb7swaE9jepYea0FRQx4AD5Qxkz6ZiQM3Um9jYOZPqW+tRPyU0NR2HNtiytrRBtbEDv0tGb62ACEQ6J4qToUAiYiCIQuexBama+RI5AQdFKrk+PyuAKBUK8YMmkJUqGut2IZAoiNcf2xEPCfxh83abzoVwpYQ8V1yhLpD3WEE22wxwP54KgAGF2EQiEhBFtCgBraCiqBIWoAKxYghQcDMzDgUDMfCgYCQfD4ZlqrBAUAA5Fyea8LQA6LAAJgA7I7HTg6EA)

**Comment by jack-williams** [comment]
See #37472 and the linked PR.
