### ISSUE TITLE
Comments for call expression arguments are not preserved in output

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3844]
Reported by @NickHeiner in #3283

And I know that TS offers multiline strings via template strings, but here's another use case:

index.ts
```ts
declare var angular: any;

angular.module('app').factory('myService', /* @ngInject */ function foo($scope, filter) {

});

```

tsconfig.json
```
{
    "compilerOptions": {
        "removeComments": false
    }
}

```

```
λ tsc -v
message TS6029: Version 1.5.3
λ tsc -p .
```

Generated index.js
```js
angular.module('app').factory('myService', function foo($scope, filter) {
});

```

The `/* @ngInject */` comment needs to be there so `ng-annotate` can annotate the Angular dependency injection function.

**Comment by CyrusNajmabadi** [comment]
@nickheiner Nick, if you use this form ```/*! @ngInject */``` would angular still understand and respect the comment?

if so, then this would be the recommended way to solve this problem.  It's already the design of the .ts compiler (modulo bugs) that ```/*!``` comments are preserved.  So that would ideally solve this problem.

If angular only accepts ```/* @``` and not ```/*! @```, then it sounds like a new comment type we'll have to add special handling for.  @yuit could do this as part of her efforts in this space.

**Comment by Gillespie59** [comment]
According to the code of the ngAnnotate, it should work I think 

```javascript
function inspectComments(ctx) {
    const comments = ctx.comments;
    for (let i = 0; i < comments.length; i++) {
        const comment = comments[i];
        const yesPos = comment.value.indexOf("@ngInject");
        const noPos = (yesPos === -1 ? comment.value.indexOf("@ngNoInject") : -1);
        if (yesPos === -1 && noPos === -1) {
            continue;
        }

        const target = ctx.lut.findNodeFromPos(comment.range[1]);
        if (!target) {
            continue;
        }

        addSuspect(target, ctx, noPos >= 0);
    }
}
```


@mhegazy : If it failed, you can maybe use the other syntax, by using the '@ngInject" string

**Comment by CyrusNajmabadi** [comment]
@Gillespie59 Thanks!  If that's the case, i think the appropriate solution is for people to annotate their ```@ngInject``` and ```@ngNoInject``` annotations with ```/*!``` so that they are preserved.

If anyone sees a case where we are not preserving ```/*!``` then please file a bug on that.  That is a bug and needs to be fixed.

**Comment by yuit** [comment]
@Gillespie59 let us know whether it is the case the angular respect ```/*!```. As @CyrusNajmabadi says if it not the case, we may have to extend our logic to preserve this special angular comment

**Comment by yuit** [comment]
This is a result of we don't preserve comment in the call expression. In following scenario, we didn't emit comment as well
```typescript
function foo(x: any){}
foo(/*lol*/ 10);
```

**Comment by mthamil** [comment]
I have a similar situation where comments are not preserved when defining a function on an object literal.
```typescript
resolve: {
    id: /*! @ngInject */ (details: FooDetail) => details.id
}
```

**Comment by CyrusNajmabadi** [comment]
Any time that we don't preserve a ```/*!``` comment should be considered a bug.  @yuit , can you take a look at these.  We're likely just missing an obvious ```emitLeadingComments``` call somewhere.

**Comment by yuit** [comment]
@CyrusNajmabadi  @mthamil I believe the root of this issue is that we do not preserve comment at all when the comment is not lead by new line regardless of the ```/*!```

For example:
```typescript
var x = 10;
/*comment*/ () => { }, /*comment1*/ () => { } 
```
/*comment1*/ will not be emitted as well

I am talking a look on how to solve the issue now

**Comment by NickHeiner** [comment]
> @nickheiner Nick, if you use this form `/*! @ngInject */` would angular still understand and respect the comment?

Yes, I do believe that will work for me. I didn't know about `/*!` comments. Thanks@!

**Comment by arthursw** [comment]
Comments are also always removed when placed after a function definition:
```

class ExampleClass {
    
    constructor() {}

    exampleFunction() /*! removed precious comment */ {
        console.log("exampleFunction");
    }
}

```

Those comments are really important for me since they are used by [Unreal.js](https://github.com/ncsoft/Unreal.js).

**Comment by RyanCavanaugh** [comment]
@arthursw please log a new issue for a bug with a different repro

**Comment by elfrevaldes** [comment]
I have the same problem that @arthursw has. I need to keep the comment but even though the file tsconfig.json says "removeComments": false or I use the /*! it does not preserve the comment. I I need them to turn on or off hints in my application

**Comment by mchambaud** [comment]
+1

**Comment by RyanCavanaugh** [comment]
Again, please log a new issue with explicit repro steps

**Comment by nishantkagrawal** [comment]
I have added details to bug #16727 where the `/*!` is not honoured if it is not on a new line.
