### ISSUE TITLE
Allow --noEmit to override incremental: true from tsconfig.json

### ISSUE THREAD

**Issue by dandv** [microsoft/TypeScript#38440]
## Search Terms

noEmit incremental override type-check

## Suggestion

If `--noEmit` is specified on the command line, ignore the `incremental: true` setting from `tsconfig.json`.

## Use Cases

I want to have a `type-check` npm script that runs `tsc --noEmit`, only for type checking. Whether `incremental` was set to `true` in `tsconfig.json`, shouldn't prevent that, because this isn't a build.

## Examples

Currently, this leads to

> Option 'noEmit' cannot be specified with option 'incremental'

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
@sheetalkamat thoughts?

**Comment by sheetalkamat** [comment]
While working on #38853 i did consider this and i think it would be ok to write tsbuildInfo file when --noEmit is specified. But we should handle difference between running 
`tsc --noEmit` and `tsc` where tsbuild info file remains same, and hence had decided to file separate PR for this.
