### ISSUE TITLE
stripInternal not working when generating declaration files from JS

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#38444]
**TypeScript Version:**  4.0.0-dev.20200509

**Search Terms:** stripInternal JSDoc

When generating declaration files from JS files annotated with JSDoc, declarations marked with `@internal` are not stripped from the declaration files, although `--stripInternal` is true.
**Code**

TypeScript input file:
```ts
export class tsTest {
  tsFoo(): string {
    return "";
  }

  /**
   * @internal
   */
  tsBar(): null {
    return null;
  }
}
```

equivalent JavaScript input file:
```js
class jsTest {
  /**
   * @returns {string}
   */
  foo() {
    return "";
  }

  /**
   * @internal
   * @returns {null}
   */
  bar() {
    return null;
  }
}
module.exports = {
  jsTest,
};
```

TSConfig:
```jsonc
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",

    "allowJs": true,
    "checkJs": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    "stripInternal": true,

    "strict": true,
    "esModuleInterop": true,

    "forceConsistentCasingInFileNames": true
  }
}
```

**Expected behavior:**
```ts
// TypeScript and JavaScript output
export declare class tsTest {
    tsFoo(): string;
}
```

**Actual behavior:**
```ts
// TypeScript output
export declare class tsTest {
    tsFoo(): string;
}
```
```js
// JavaScript output
export class jsTest {
    /**
     * @returns {string}
     */
    foo(): string;
    /**
     * @internal
     * @returns {null}
     */
    bar(): null;
}
```

Notice how `bar()` isn't stripped out and there is no `declare` modifier.

**Playground Link:** No JS in the Playground, so I made a repro repo: https://github.com/AlCalzone/ts-stripinternal-repro

**Related Issues:** Only https://github.com/microsoft/TypeScript/issues/27125 and an unrelated proposal came up.

**Comment by kyryloonufriiev** [comment]
I have the same issue with the current stable version of `tsc`. Please fix it

**Comment by AlCalzone** [comment]
Oh, I did not know that `stripInternal` is not documented. Is there any other intended way to have members of a class only visible in the current project, but not from outside? Something like VB.net's `Friend` modifier?

**Comment by telamonian** [comment]
I'm hitting this issue too. It makes the current autogeneration of declaration files from javascript sources somewhat useless, since they require significant manual rewriting.

I'm perfectly happy to submit a PR for this issue. The typescript codebase is massive, and I could use a few pointers. Is one of these files where the relevant code is?

https://github.com/microsoft/TypeScript/blob/master/scripts/buildProtocol.ts
https://github.com/microsoft/TypeScript/blob/master/src/compiler/factory/nodeFactory.ts
https://github.com/microsoft/TypeScript/blob/master/src/compiler/transformers/declarations.ts

**Comment by swingingtom** [comment]
@telamonian did you succeed to find where to start a PR ?

**Comment by JakobJingleheimer** [comment]
Perhaps the "undocumented" has since changed, but `stripInternal` is indeed documented now (and still doesn't work): https://www.typescriptlang.org/tsconfig#stripInternal
