### ISSUE TITLE
Support publishing npm module with "ts" files

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#38452]
I hope the TypeScript to support publishing npm module with `*.ts` files. 

I don't mean that publishing npm module only with `*.ts` files, but also with pre-compiled `*.js` files. If a developer, using the npm module, is not using the TypeScript but pure JS, only pre-compiled `*.js` files would be utilized. If the developer is using the TypeScript compiler, `*.ts` files would be used instead of pre-compiled `*.js` and `*.d.ts` files.

Anyway, if the npm module is published with `*.ts` files and let users to compile those `*.ts` files by themselves, there would be two benefits. The first benefit is the exact-debugging and the second is the performance enhancement.

## 1. Exact Debugging
In nowadays, many TypeScript users are using [`ts-node`](https://www.npmjs.com/package/ts-node) or [`source-map-support`](https://www.npmjs.com/package/source-map-support) to debug their TypeScript codes exactly. When error occurs, those libraries point the exact line number of `*.ts` file. Those library also adding breakpoint on `*.ts` files possible.

However, if an error comes from the external npm module, it's hard to debug because the error message would point the line number of `*.js` file. In such reason, adding breakpoint on external npm module is also very hard for users.

> If the external npm module is using `async/await` feature and compiled with polyfill, debugging the external npm module without `*.ts` files are almost impossible.
> 
> ```js
> var __generator = (this && this.__generator) || function (thisArg, body) {
>     var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
>     return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
>     function verb(n) { return function (v) { return step([n, v]); }; }
>     function step(op) {
>         if (f) throw new TypeError("Generator is already executing.");
>         while (_) try {
>             if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
>             if (y = 0, t) op = [op[0] & 2, t.value];
>             switch (op[0]) {
>                 case 0: case 1: t = op; break;
>                 case 4: _.label++; return { value: op[1], done: false };
>                 case 5: _.label++; y = op[1]; op = [0]; continue;
>                 case 7: op = _.ops.pop(); _.trys.pop(); continue;
>                 default:
>                     if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
>                     if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
>                     if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
>                     if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
>                     if (t[2]) _.ops.pop();
>                     _.trys.pop(); continue;
>             }
>             op = body.call(thisArg, _);
>         } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
>         if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
>     }
> };
> ```

## 2. Performance Enhancement
When developing and publishing an npm module with TypeScript, compability should be consired. In my case, because of the compability, I always compile TypeScript files as `es5` target and `commonjs` mode with `--downlevelIteration` option. 

However, if the TypeScript supports publishing npm module with `*.ts` files, such compile options can be determined by users. As you know, NodeJS is optimizing the `async/await` features whenever beeing updated. Therefore, when using `async/await` feature in NodeJS environment, `es2020` target compiled `*.js` file is faster than `es5`, who does not use the `async/await` statements and utilizes polyfill method instead.

Like the above example case, higher version's target and mode can take the performance enhancement. Therefore, if users can determine compile options by themselves freely, the performance can be enhanced.

**Comment by mscottnelson** [comment]
TypeScript does not control what you choose to publish to npm. You can publish .ts files if you wish, and require that they be built by the top-level TypeScript project. You could either have them required directly, or rely on a module setup using the tsc -b flag.

**Comment by aelesia** [comment]
Turn on `"sourceMap": true`, so that when you are viewing source code or debugging, it will point you to the exact line of code in your .ts file.

You can try adding then debugging my package here: 

https://www.npmjs.com/package/httyp

It's written in .ts, but compiled down to .js. However when you use debugging tools you will be redirected to the .ts file.

You can also use my npm template for typescript to test it out:

https://github.com/aelesia/npm-template
