### ISSUE TITLE
TS2362 - Error when doing bitwise operations on number[]

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#38458]
```ts
[1] & 1
```
> x side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type

Expected : bitwise operations on arrays evaluate against index 0

[Playground link](https://www.typescriptlang.org/play?#code/NoRgugBAZBJA)

**Comment by RyanCavanaugh** [comment]
> Expected : bitwise operations on arrays evaluate against index 0

🤔
```
> [1, 1] & 1
< 0
```

See also https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean

**Comment by pushkine** [comment]
Yeah it only works with arrays of length 1
It is weird and I can't find documentation about it anywhere, yet it is used extensively in sveltejs
Is there a way to define it locally anyway ?
