### ISSUE TITLE
The `is` predicate return type is not being utilized properly

### ISSUE THREAD

**Issue by ekilah** [microsoft/TypeScript#38454]
**TypeScript Version:**  `3.8.3`, also Nightly (`v4.0.0-dev.20200509`) and the `3.9.0-beta`

**Search Terms:**
is predicate
infer
filter
array
instanceof
type guard

**Code**

```ts
abstract class Foo {
  public abstract isFooBar(): this is FooBar
  public isFooQux(): this is FooQux {
    return !this.isFooBar()
  }
}

class FooBar extends Foo {
  isFooBar() {
    return true
  }
}

class FooQux extends Foo {
  isFooBar() {
    return false
  }
}

const fooList: Foo[] = [new FooBar(), new FooQux()]

// this seems to typecheck, so you might assume all is well.
const fooBarList1: FooBar[] = fooList.filter(f => f.isFooBar()) 

// adding the generic to specify the overload of `filter` I want doesn't typecheck though.
// TS doesn't "remember" that `isFooBar` has `this is FooBar` as a return type.
// 
// from lib.es5.d.ts:
//   filter<S extends T>(callbackfn: (value: T, index: number, array: T[]) => value is S, thisArg?: any): S[];
//   filter(callbackfn: (value: T, index: number, array: T[]) => unknown, thisArg?: any): T[];
const fooBarList2: FooBar[] = fooList.filter<FooBar>(f => f.isFooBar()) // error, should work

// now this shows me that `fooBarList1` typechecking above was not as type safe as you may have hoped.
// this and `fooBarList1` typecheck solely because TS thinks this function returns `boolean`
const fooBarList3: FooBar[] = fooList.filter(f => f.isFooQux()) // no error, shouldn't work

// -------------------

// Let's try something else to get the `is` return type working, to see if the class method was the problem?
const globalIsFooBar = (foo: Foo): foo is FooBar => {
  return foo.isFooBar()
}
const globalIsFooQux = (foo: Foo): foo is FooQux => {
  return foo.isFooQux()
}

// using a function outside of a class definition, things seem to work nicer (on the surface):
const fooBarList4: FooBar[] = fooList.filter(globalIsFooBar) // no error
const fooBarList5: FooBar[] = fooList.filter<FooBar>(globalIsFooBar) // no error
const fooBarList6: FooBar[] = fooList.filter(f => globalIsFooBar(f)) // no error

// except when I add the generic back w/ a lambda?
const fooBarList7: FooBar[] = fooList.filter<FooBar>(f => globalIsFooBar(f))

// trying to cause a bug again, all of these should fail... but they don't. not good!
const fooBarList8: FooBar[] = fooList.filter(globalIsFooQux) // no error, shouldn't work
const fooBarList9: FooBar[] = fooList.filter<FooBar>(globalIsFooQux) // no error, shouldn't work
const fooBarList10: FooBar[] = fooList.filter(f => globalIsFooQux(f)) // no error, shouldn't work

// this is still only complaining that the lambda returns `boolean` instead of `is`, so no points for TS here.
const fooBarList11: FooBar[] = fooList.filter<FooBar>(f => globalIsFooQux(f))


// Helper function from https://github.com/microsoft/TypeScript/issues/5101#issuecomment-145693151
function isInstance<T>(ctor: new(...args: any[]) => T): (x: any) => x is T {
  return (x: any): x is T => x instanceof ctor
} 

const fooBarList12: FooBar[] = fooList.filter(isInstance(FooBar)) // ok...
const fooBarList13: FooBar[] = fooList.filter<FooBar>(isInstance(FooBar)) // ok...
const fooBarList14: FooBar[] = fooList.filter(f => isInstance(FooBar)(f)) // ok...
const fooBarList15: FooBar[] = fooList.filter<FooBar>(f => isInstance(FooBar)(f)) // should work, doesn't

const fooBarList16: FooBar[] = fooList.filter(isInstance(FooQux)) // no error, shouldn't work
const fooBarList17: FooBar[] = fooList.filter<FooBar>(isInstance(FooQux)) // no error, shouldn't work
const fooBarList18: FooBar[] = fooList.filter(f => isInstance(FooQux)(f)) // no error, shouldn't work
// errors, but again no points because TS sees a `boolean` return type and is complaining about that
const fooBarList19: FooBar[] = fooList.filter<FooBar>(f => isInstance(FooQux)(f))
```

**Expected behavior:**
See notes above / in the playground, the `is` predicate's narrowing should work in the above test cases.

**Actual behavior:**
See notes above / in the playground, there are several ways in which this does not seem to work as expected.

**Playground Link:** [Here (same code as above)](https://www.typescriptlang.org/play?ts=3.8.3#code/IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIIAOAriMgJawKiQzwLVg7YBCwUAFAJQAuBBAAWrFhnZcoxMpRp1W7AIrkAHvyGjx4leoKySUAKYRyUAHYIAhNrAA6Jbmn9ZAX0IfCKNJOfcEYzUIYwsAEz88IhInTm5+AxIjU3MraHJjd09Cb1R0LFxVNUDg0IiCqNlYlz5EpJMzSwQAM2BkMEySDy9YbAtIFtwAGVYIIXYAbQBdBABeBAmLYwB3CpqAGgQl1b0NPimcgHpD4TEMDuMAWwwIPAgAT1JjWBFngGtNsDx77HIES+oAHMRIhfORLsZ6MhkBIEMtjND7N4+gNmv4oCNIABGcbo6ZzQbYTEQezNajIEK8ZpzAB8LUcbHR-FqRxOwDCYWoFkBp0hgNCxigtGEeDAT1g1Ga915CGwADdBchsOzZdSAAZkimCtUIACScOAFkQYWwxjAFgA5IgHuLXrA3qdfsCkccEAAVADKCBNZstiAARCYIZcQIL-adgIg1dVuDqRGgEGq7LCpLH6BhgAgGqlhI9jC6ToRXc0oNhLggaCB7GaAKz2ML2CBgARFk4kTWUgA8XqCIXCGDdNJ4sDayBAcDezQsQh4craGSEbs2XLCQSEFnBoagm24MHui+mtVmdLnyAysI9mzsAEEoICAPxCQ33QQID3TADcraSHcFw9H472lOM6ngu7rLuEa5bJugo7lAe4HlMR50uQFhvBY2DLBYV5nLeD5PhYL6IV+vT9IgaJxBiowAEy4pR+LzBRxKkuSXaplAQ7Use9IxrwfC1K6gqltuCBgCIvzIGEcLYFAbyslsmGnOIYmYRgEIRlGFHSMSWI6jazx2m8XI8qA8qQssCYYaCNx5qJwDNJCCY-H8lzANK8YKgg4lPA237JoaUkauiOl6XmLzvKJ2DIAi0qhiO5AdO6XraGhNxnC0qHwNQfRZiklgYGqIC4NFhpqsiZGEtpowAMx0dIDGEsxv5UrSPGMtgRTMggroYYE8EyZ84nkJJfrSbJ8kALRTdNM2zTN8lDKYFo3FA0pfBCKU8giiW3Ag-LWq8iasDq2ZNPpY1GdyV6isYkKSjKPj5Bt4lSRZaWQqQpZUFc97lQMgJKuOyC6u10gEjwFF0a+FEpuirXRLljRWBRDLsa4Hikf9gNtCDuzg5DFTQ7gsMdfo3EI6dyO4KjhTqOj8kJcZ9AZRYWU5b8TbUKuqrM49GCrmSFjUBA2XYUp3LnLd5a7csMkOkLsCCggPA5aIkJgOYrSK4If3kcFowACx1dwDVMaMLFarwAPYEDuPogJJy9UJMm65V3DEjWxtQKbwzm81nbsUO1u26D3AOwpfXCa7Wnu6MABsXs+0SfusX+XF0sHOOh1S-HdY7eDOzI35BIrpCIMsrxWPq7JSWre0CkKdCAQ6yxshWwAhmEwC-ZjeuUcSADsiczIxvuQBbbHopxrWZ8D2cQ-x8nQPcTO7fFiWZiA5AmYCwBcju0I82riUqcNUmtOS9hXwgW8HcY0omn69gKYggK4GE1jR-rkAABzDwSZtx7NR4LPO2pM1Dhydv1ESp8RpWgul-fuowACc-9R7JyAanKAAcp4gOxnPXYkCC7QMGhJMIo1ZbjV7m7Ki2IAAMaDGop0thDGe+CwGdWaLnHqxDhKkLPhQuWS90rKRFofPoyBpS9EuKQVAXJV7xjvu3TumZKYFSKlFYwpUWBkS0VJbA6pjqfDwL1Ug2AuRNkGFAJKXlBT5kQVVbEOI1gmxHkwzBlscGUWntxUB7VOGL3kgACQRE8axzRMoixyiWMsXkIAQFIM2Y4gJhYiEoPYaRhwASwFLF8ZoEBDhujzB6HJ1Ay6HFYBrM0hwaxYjoViAAxJUjI0iIRGgmliA2NY47IOqliWphAImsyiVYVguoyKGkVp2Qcw5bhQHXCsHgV97DcEBM2eghFDytTdK+HgagCIvlasUcQbo6iU2VvsjZREEDHIHEcnRkBJnGAMUgOZngEA5GoTHWhEAsS0Rcd7NxgCSTALGRM1mxgeDsW4ScbAbxlkONjtiWqAKk5NSwV46QQ4wWPIhVC+24c4UIq+d-X5RtUVArHiCrBrDuI4ogE8-FlE+AL0JfCq+iKfn9MYcCiegpMXcB8XSeljLoWsrzqJIakkLqbB9OaK0nyUR90cb8hOFKAFUr5bwEVeLCFEMjgNSVZDBFUKVTQnSQ91XoPRZ4wOPAdWKyZUUGFEdC78LgeXIRJKkHYj-la9x1KWHpwkOM3FjrCHip4QamBUryHwMoXJQS0CwCbFvvQXeXII5mIsRgOKwAEqQk9KJW6GZEwaJKhYE6eU0i2QCrCaRsi95C25PQIq5ADqRk5TpVB-reX+ztcGh1kKI1cL4EAA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/5101
https://github.com/microsoft/TypeScript/issues/16069

**Comment by MartinJohns** [comment]
Two notes that cause issues in your examples:

- `FooBar` and `FooQux` are structurally compatible, that means something like `const fooBar: FooBar = new FooQux();` is valid. To solve this you should make your classes nominally typed by adding a private member.
- You have `filter(f => ...)` several times. In this case the arrow function is returning `boolean`, it is not a type guard anymore. You can solve this by explicitly typing the return type, e.g. `filter((f): f is MyType => ...)`.

Both behaviors are intended.

**Comment by ekilah** [comment]
The structural compatibility comment is good, thanks for that. That points out a flaw in my example code, definitely. I didn't know that structural compatibility ("duck typing") worked for `class`es in TS, I knew it did for regular objects.

Re: your second point, that means there is no way to use an `is` type guard function defined on a `class` without a bunch of extra `(f): f is MyType` stuff in each `filter`. Is that part intended, or just an unfortunate side effect?

**Comment by ekilah** [comment]
I guess the only way to get an `is` function reference without a global function is something like this, which is a decent workaround, but still unfortunate IMO:

```ts
abstract class Foo {
  public abstract isFooBar(): this is FooBar
  public isFooQux(): this is FooQux {
    return !this.isFooBar()
  }

  public static isFooBarStatic(foo: Foo): foo is FooBar {
    return foo.isFooBar()
  }
}

const testStatic1: FooBar[] = fooList.filter(Foo.isFooBarStatic) // works as expected
const testStatic2: FooQux[] = fooList.filter(Foo.isFooBarStatic) // error as expected
```
