### ISSUE TITLE
Infer (unspecify) generic type for members in recursively defined classes & interfaces

### ISSUE THREAD

**Issue by MaxGraey** [microsoft/TypeScript#38457]
I didn't find anything similar among the available feature requests, but it's possible that I was just looking badly) So I'm totally ok with closing this suggestion if it duplicate.

## Search Terms

"Infer", "omit", "recursive", "parametric types", "generics"

## Suggestion

In most cases recursive generic structures specify the same parametric types so I suggest ability for skipping fully specify parametric types for cases when it is possible (See examples).

## Use Cases

This suggestion remove verbosity and simplify refactoring. On the other hand, it violates the principle of “Explicit is better than implicit”. That's why I suggest use `GenericClass` without explicit parametric types instead implicit `Self` like in Rust. Also this approach allows you infer parametric types for base class as well like in **Example 2**. So apparently it's good balance.

### Example 1
```ts
interface TreeNode<T> {
  left:  TreeNode | T,
  right: TreeNode | T
}
```
which infer as
```ts
interface TreeNode<T> {
  left:  TreeNode<T> | T,
  right: TreeNode<T> | T
}
```

### Example 2

```ts
class BTree<K, V, Comp> extends BNode<K, V, Comp> {
  children: BNode[]
  constructor(children: BNode[], keys?: K[]) {
    //...
  }
  clone(): BNode {
    //...
  }
}
```

infers as:
```ts
class BTree<K, V, Comp> extends BNode<K, V, Comp> {
  children: BNode<K, V, Comp>[]
  constructor(children: BNode<K, V, Comp>[], keys?: K[]) {
     //...
  }
  clone(): BNode<K, V, Comp> {
    //...
  }
}
```

### Example 3

```ts
type ValueOrArray<T> = T | Array<ValueOrArray>;
```
infers as:
```ts
type ValueOrArray<T> = T | Array<ValueOrArray<T>>;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
I think this would be confusing especially since typescript already allows omitting type arguments if defaults are specified. This means inside the type it would be clear if the type has defaults, or if this new scheme is being used. Also how would you deal with the case where the type does have default ? 

```ts
interface TreeNode<T = number> {
  left:  TreeNode | T, // TreeNode is TreeNode<T> or TreeNode<number> ?
  right: TreeNode | T
}
```

**Comment by MaxGraey** [comment]
that's good point. I guess parametric types have some omitting precedences (like operator precedences)? Where omitting as default has lowest priority. In this case it should infer as

```ts
interface TreeNode<T = number> {
  left:  TreeNode<T> | T,
  right: TreeNode<T> | T
}
```

**Comment by RyanCavanaugh** [comment]
I agree with @dragomirtitian -- this would simply be too confusing given that a missing type argument already means "use the default", and there's a desire for it to also mean "perform inference" in other cases.

**Comment by MaxGraey** [comment]
Regarding this ambiguous case (with default parameters) semantic analyser could just some report and ask to explicitly specify is it `TreeNode<T>` or `TreeNode<number>`
