### ISSUE TITLE
Unable to assign class to type T extends { new(...args: any[]): T }

### ISSUE THREAD

**Issue by ppn2** [microsoft/TypeScript#38455]
**TypeScript Version:**  3.8.3

**Search Terms:**
"Property 'prototype' is missing", "Property 'prototype' is missing in type"

**Expected behavior:**
Should be able to assign the class (Trx in this case) to type T extends { new(...args: any[]): T }

**Actual behavior:**
Compilation error. 
Argument of type 'typeof Trx' is not assignable to parameter of type 'new (...args: any[]) => typeof Trx'. Property 'prototype' is missing in type 'Trx' but required in type 'typeof Trx'.

**Related Issues:**
Possibly related #38341 

**Code**
```ts
function func<T extends { new(...args: any[]): T }>(clazz: T): T {
    throw new Error("Not Implemented");
}
class Trx {
    transactionId: number = 0;
    trxType: number = 0;
}
function test() {
    func(Trx);
}

```
<details><summary><b>Output</b></summary>

```ts
"use strict";
function func(clazz) {
    throw new Error("Not Implemented");
}
var Trx = /** @class */ (function () {
    function Trx() {
        this.transactionId = 0;
        this.trxType = 0;
    }
    return Trx;
}());
function test() {
    func(Trx);
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=0#code/GYVwdgxgLglg9mABKSAeAKogpgDylsAEwGdEBvRMLAdwAoA6RgQwCcBzYgLkSbAE8A2gF0AlN0wBfAHy0IAGyYAvReLGJMZAFCIdiKAAsWcapRqIAoiyMtaAIgBycKIgCSAWwAOcrG4L5CtiIA3JoSmvJMxKToLDjk2rpQLLzETNDwYC6E3GAgbgBGWCyIALyIAAwhunqx6HweWDl5hcVllaGaKOkIeljEULQi8dVdtDE4wR1AA)

**Comment by dragomirtitian** [comment]
`T extends { new(...args: any[]): T }` is a constructor that returns itself, so `new Trx()` should return the class `Trx` itself (not an instance of it)

You are looking for 
```ts
function func<T extends { new(...args: any[]): any }>(clazz: T): InstanceType<T> {
    throw new Error("Not Implemented");
}
```
 or 

```
function func<T >(clazz:  { new(...args: any[]): T }): T {
    throw new Error("Not Implemented");
}
```
Depending on what you want to do with the class inside the function.
