### ISSUE TITLE
<T extends unknown> does not narrow

### ISSUE THREAD

**Issue by asmundg** [microsoft/TypeScript#38456]
I'm not entirely sure _why_ you would want to extend `unknown`. But if you end up doing it, it seems a bit surprising that the narrowing behavior is not the same as for `unknown` itself.

**TypeScript Version:**  4.0.0-dev.20200509

**Search Terms:** narrow unknown

**Code**

```ts
function works(arg: unknown): void {
  typeof arg === "object" && !!arg && Object.keys(arg);
}

function fails<T extends unknown>(arg: T): void {
  // No overload matches this call.
  // Overload 1 of 2, '(o: {}): string[]', gave the following error.
  //   Argument of type 'T' is not assignable to parameter of type '{}'.
  //     Type 'unknown' is not assignable to type '{}'.
  // Overload 2 of 2, '(o: object): string[]', gave the following error.
  //   Argument of type 'T' is not assignable to parameter of type 'object'.
  //     Type 'unknown' is not assignable to type 'object'.
  typeof arg === "object" && !!arg && Object.keys(arg);
}
```

**Expected behavior:**

Both examples compile.

**Actual behavior:**

Only `works` compiles.

**Playground Link:**  https://www.typescriptlang.org/play?ts=4.0.0-dev.20200509#code/GYVwdgxgLglg9mABAdzgJwNYGcAUBDNAcwC5FwMw5kwBKUgNzhgBNEBvAKEUSgE8AHAKZxgiAoUQBeaYgBEcAEYArQdFmIAZBsQBCHeM3aA8stVQAdBkG9c4mgG4OAXw4dQkWAkTA8MADZYADwAKoiCAB5QgmDMWGRgFFRgAHz4RKTBdIiMLOxciAD0BYgAcnCIcPSCaH5weKwAtnhQEAAWgnFQrTBxEHh+fub5RYhGVTV1rACMFaIATAA0iADkOHCkbE5ZWFBoMGCEANoAustLhHhVPO3ecANU+xLVaOhD3CPcAIJEIA3RULMeAJBCtgstED1EJQAXgsFgYIQwHgFH4QVByvwCHg-lE0IC+EIVptlm9CsVuNxgsCVuRKNRwZDoWI4QikSi0eUCSDlsTSSMxtVavVEHNAYsVmtSIoVNBtrtHiczogLlcuiDgHdashHmE0C80HzyYhvoRfv98dTlmCIXEmbD4YjkaieBisTjqhbCctpWYScMjZTLbSkgzbXAYSzHeyXUCvT7oH7uFyRGIiFIZPJTGpDLp9GmtKMsxYrDY0oQHM4gA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
In general a `T extends U` won't behave exactly like `U` in any number of cases. Different things having different behavior is why we have different things.

**Comment by benwiley4000** [comment]
@RyanCavanaugh I had a very similar issue to @asmundg . I was surprised to learn that `T extends unknown` can't narrow.. what do you see as the intended use case of `<T extends unknown>` ? Why not just use `<T>`? I found that this does compile when you remove the `extends unknown` (even in strict mode), but that said I can't figure out what the point of `extends unknown` is.

**Comment by sebasthuis** [comment]
@benwiley4000 Did you manage to find out what the point is of `extends unknown`?

**Comment by jsejcksn** [comment]
@sebasthuis My current understanding is that it's used to trigger distribution and create a distributive type as explained in the v`3.0` [release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#example-3).
