### ISSUE TITLE
[Infrastructure] [DefinitelyTyped Tooling] - Automatically merge PR from only Author

### ISSUE THREAD

**Issue by Jojoshua** [microsoft/TypeScript#38468]
I have noticed new features relating to DefinitelyTyped merging features for the typescript-bot to allow automatically merging a PR if the Author approves changes that came from a different contributor. This works great. 

I've noticed that for my type definitions which I am the only Author (even if I have added tests) this still seems to require approval from a DT maintainer to merge. The same logic should apply and allow the only Author to automatically merge their PR. 

Example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44644

Today, I could essentially trick the system and simply create the PR using a different account and then allow the Author account to Review and approve the changes resulting in automatic merge.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior - we want "minimum two humans" before merge, whether it's author + maintainer or author + reviewer.

If you create a second account to game this, we will ban both of them, of course. For obvious reasons I won't describe the sorts of systems we have in place for detecting fishy behavior.

**Comment by Jojoshua** [comment]
I understand the 2 person logic but the system can still be thwarted with 2 actual people whether friends or coworkers.

**Comment by RyanCavanaugh** [comment]
Understood; it's all trade-offs. I still lock my front door even though there are large glass windows right next to it. If you are trustworthy enough to enlist a second person to submit code in their name on your behalf on a regular basis, then it's probably OK that you're effectively self-merging.

**Comment by Jojoshua** [comment]
> If you are trustworthy enough to enlist a second person to submit code in their name on your behalf on a regular basis, then it's probably OK that you're effectively self-merging.

If this is true @RyanCavanaugh  then could an enhancement be made to allow the Author to request a code review from someone else? This would satisfy the preconditions as well.

**Comment by RyanCavanaugh** [comment]
You can ping whoever yourself already - other people can't be assigned in the native GitHub UI unless they're DT Collaborators (which very few people are)

**Comment by Jojoshua** [comment]
So that is what I am getting at... the ability to for example ping my co-worker or heavy user of my definitions to perform the review.

**Comment by RyanCavanaugh** [comment]
I don't understand what you're asking for. You need a way for the bot to say `🔔 @coworker` instead of you saying `🔔 @coworker` ?

**Comment by Jojoshua** [comment]
I think that's what I am asking for but maybe it's my inexperience with Github is the issue. Is there already a way I can request my coworker to review my DefinitelyTyped PR? I don't see the section to add reviewers.

**Comment by Jojoshua** [comment]
It's also possible that an error occurred with the DefinitelyTyped PR build I noted above and I am not seeing something or the system isn't working properly. I noticed the bot added Where is Travis? label.

**Comment by RyanCavanaugh** [comment]
You can ask by saying `Hey @coworker please look at this`, but no one (us included) can add a person to the Requested Reviewers section unless that person is already a "Collaborator" on the repo the PR exists in.

This iteration of the bot is a bit new and we're still working through some kinks. The Where Is Travis? label should disappear on its own in a bit; if it doesn't, the on-call maintainer will take a look.

**Comment by orta** [comment]
Docs for adding other people as reviewers is over in the DT repo: https://github.com/definitelytyped/definitelytyped/#definition-owners

And nope, no plans to allow letting single-owner modules to PRs get auto-merged - the second opinion is an important part of the feedback loop
