### ISSUE TITLE
Reopen 12750

### ISSUE THREAD

**Issue by mikegwhit** [microsoft/TypeScript#38473]
Microsoft closed comments on this issue, but it's still relevant.  It's a painfully basic behavior to want to ignore files from TypeScript compilation.  In my case for my team, I am trying to author a tool to check file modification times so we don't have to needlessly run TypeScript.  The resolution specified by 12750 of `"exclude": ["**/node_modules/*"]` simply does not work.  Run `tsc --listFiles` and you'll receive a listing of files from `node_modules`.  For obvious reasons, this file tree walk takes more than 5 seconds.  

I get that everyone wants to think their tool is critical and important, but I can't recommend TypeScript as it adds to the complexity of testing small changes.  Obviously, you could just fix the way you pick up changes and compile only the diff.  Then I read some issue ticket where Anders Hejlsberg decided to comment that it's an "intractable" problem to traverse an entire set of imports upon compilation soas to only transpile the diff.  How some people wind up with a "distinguished engineer" title is beyond the scope of this report.  Maybe they once did great things and age has captured back some of their brain cells or they simply don't keep up with the "little people" any more.  Maybe there are no consequences for authoring bad tools and pushing tools out prematurely to hit a corporate quota.  Such speculation is also outside the scope of this report.

Please fix the issue, it's painful and adds obvious time to something as simple as transpiling a few files.  It can be assumed that anything in `node_modules` is transpiled.  Please assign one of your distinguished developer advocates to the problem.  Clearly, developers need to be advocated for in this woefully technical domain.  Hard problems call for large salaries.  /s

**Comment by RyanCavanaugh** [comment]
Unfortunately we're not able to investigate reports that just have a prose description of a misconfigured project -- there are many different ways to set up your build with different trade-offs and it's impossible for us to figure out which conditions you're hitting. I'd be happy to look at an actionable issue report describing the problem you're facing.

The personal sniping here is entirely unwarranted and inappropriate. I would refer you to the code of conduct and ask you to refrain from such personal attacks in the future.
