### ISSUE TITLE
Perf Regression in ant-design from #36696

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#38478]
Sub-issue of #38432
Regression introduced in #36696

**Steps**

1. `git clone --depth=1 https://github.com/ant-design/ant-design`
2. `cd ant-design`
3. `npm install --ignore-scripts`
4. `tsc  --extendedDiagnostics --skipLibCheck --incremental false --pretty false -p tsconfig.json`

**Results**

f31ff2dac0163cc4a161c2f9d0fea518dcd87ca1: 16978 ms
be4b814a4c7eb09515cade5bfc56d03b2a885170: 17571 ms (3% slower)

**Comment by amcasey** [comment]
I think we may have discussed this perf regression in another context and concluded it was a necessary evil, but I couldn't find a write-up.

**Comment by ahejlsberg** [comment]
Yeah, there is going to be _some_ cost associated with the intersection reduction, and it doesn't seem unreasonable here.
