### ISSUE TITLE
tsconfig exclude field not working

### ISSUE THREAD

**Issue by mikegwhit** [microsoft/TypeScript#38475]
Using TSC 3.8.3, run `tsc --init`.  In the `tsconfig.json` file, add the line:
`exclude: ["**/node_modules/*"]`

Add a `package.json` dependency that includes TypeScript files.  Run `npm install` or install dependencies such that there is a TypeScript file inside of `node_modules`, i.e. `node_modules/**/*.ts`.

Now run `tsc --listFiles`.  You should see the TypeScript files within `node_modules` appear in the file listing that results.  **This is not expected**.

**Expected behavior:**
When using an exclude entry, expecting those entries to be applied such that they do not appear in any glob / grep / file tree walk that results from running `tsc`.

**Actual behavior:**

Seemingly, the `exclude` field is ignored.

**Related Issues:** 

#12750

**Comment by RyanCavanaugh** [comment]
This is what I tried based on the description:

```
D:\Throwaway\nodetest>tsc --listFiles
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.es5.d.ts
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.dom.d.ts
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.scripthost.d.ts
D:/Throwaway/nodetest/a.ts

D:\Throwaway\nodetest>type tsconfig.json
{
  "compilerOptions": {
    "target": "es5"
  },
  "exclude": ["**/node_modules/*"]
}

D:\Throwaway\nodetest>dir /s node_modules
 Volume in drive D is Development
 Volume Serial Number is DC1F-3B69

 Directory of D:\Throwaway\nodetest\node_modules

05/11/2020  10:24 AM    <DIR>          .
05/11/2020  10:24 AM    <DIR>          ..
05/11/2020  10:24 AM    <DIR>          testpkg
               0 File(s)              0 bytes

 Directory of D:\Throwaway\nodetest\node_modules\testpkg

05/11/2020  10:24 AM    <DIR>          .
05/11/2020  10:24 AM    <DIR>          ..
05/11/2020  10:24 AM                16 test.ts
               1 File(s)             16 bytes

     Total Files Listed:
               1 File(s)             16 bytes
               5 Dir(s)  111,997,284,352 bytes free
```
As expected, `node_modules/testpkg/test.ts` was *not* in the file list.

What's different between my setup and yours?

**Comment by mikegwhit** [comment]
Adding notes:
* Running Windows

It looks like what's required is to import a TypeScript file from an excluded directory for it to be picked up.  Furthermore `--listFiles` actually seems to compile all TypeScript files.  Developer (me) was seeking a dry-run behavior that had less CPU footprint.  Goal is to develop a manifest of file modification times.  If local, non-excluded TypeScript file has mtime > associated transpiled JS file, then run `tsc`.  Any solution to this will do.

Whereas behavior may be "expected" for exclusion, sibling issue becomes: "expecting `--listFiles` to not compile or traverse import chains".  My generally, my need (and likely common developer need) is to require some flag to understand `tsc` entry points utilizing the `exclude` option in `tsconfig.json`.  Goal is most generally to reduce CPU footprint when integrating `tsc`.

**Comment by RyanCavanaugh** [comment]
`--listFiles` additionally prints the list of files; `--listFilesOnly` will *only* list the files. You can run whichever you intend to.

`exclude` does not prevent a file from being imported into the compilation via an` import`. It is **ONLY** a filter on files selected by `include`; this is its intended behavior.

**Comment by mikegwhit** [comment]
`--listFilesOnly` seems like it (maybe) does not traverse `.ts` files but it still picks up hundreds of `*.d.ts` files.  This still is undesirable and takes seconds.  This closes this issue in a technical way, but creates sibling impacts and still leaves the greater usability issue (large CPU footprint for trivial tasks).

**Comment by RyanCavanaugh** [comment]
You can run `--traceResolution` to see what's causing which file walks to happen during module resolution. Your `include` pattern may be misconfigured if TS is needlessly going into `node_modules` for a full walk. So far there's no actionable defect described here, though.

**Comment by mikegwhit** [comment]
I'm going digress (without the prose).  In general, there is an existing broken contract that when a user runs `tsc` they expect TypeScript files to be transpiled.  When they add an `exclude` flag, they expect files to be excluded from a build.  It has previously been regarded as intractable to solve the file walk / dependency resolution issues.  Still, the contract of what `exclude` means is broken to most developers (reference the dozen or so issue tickets and StackOverflow posts).

In general, this sounds more like a community management issue.  A broken developer contract is an abuse of terms.  Claiming "no warranty" as a mechanism to push testing of an underregulated tech behemoth onto outside developers and companies they represent who collect a lesser salary / bonus is not a viable economic and nothing to claim pride to.  Likewise, any lack of professional response due to generated frustrated can be no less professional than delivering software that qualitatively fails to deliver on what it promises.

`--traceResolution` seems to indicate a cache hit but it seems quite slow for a cache hit.  It's simply not my job to dig into these technicals.  Whereas it seems sound to assume people will pick up broken software due to a larger budget, it at least doesn't work with me and it contributes to the overall impression I'd guess others might remark as, "TypeScript only seems friendly to big enterprises, we tried it and got burned."

**Comment by RyanCavanaugh** [comment]
`exclude`'s design is to do exactly one thing, which is pretty standard for configuration design. If we made it do two things, it would be more confusing, because then you would have desirable file inclusion patterns that would be unrepresentable.

Feel free to post any new issues if you encounter any traceable defects. Seems like this is as resolved as we're going to get.

**Comment by mikegwhit** [comment]
I think I'm fine to turn this into a feature request.  I don't know the exact verbiage to search for to discover if this feature exists or if it is in-flight.

All I am trying to implement for our current project is this: we have 10 files sitting outside of `node_modules`.  I just want to check the mtime of the `.ts` files and if they are newer than their `.js` counterpart, I want to automate running `tsc` so our developers don't need to remember to do so.  Currently, I run `tsc` by default without this check, but we're incurring a 8-12 second delay because of this.  I realize that in the world of minutes-long deploy times this sounds trivial, but the sooner I can get developers toward meaningful terminal output, the happier I suspect they will be.

Ultimately, there are impacts for onboarding users onto a project that generally are impacted by full-scope `.tsc` compilation.  

I can write this tool in-house, but I'm just lost if this feature already exists in TypeScript?  My data is coming from searching for issues relating to this: most searches result in the `exclude` field.  After reading about a half dozen to a dozen StackOverflow posts and GH issue tickets corresponding to the "brokenness" of the `exclude` field, this is where I am drawing my conclusion (or confusion!) from.

**Comment by RyanCavanaugh** [comment]
It sounds like what you want to do is set `composite: true` in your config. After this point, the file list formed by globbing `include` and exclude `exclude` is guaranteed to be the same set of files that would be compiled, so you can trivially perform that file time computation on your tool's side and decide whether or not to perform any further action.

**Comment by mikegwhit** [comment]
Aye, so you're tracing roughly the path I took.  However, even running `--listFilesOnly` and `composite: true` still takes about 5-8 seconds.  If there is a resolution to this latency would be much appreciated!

Without solving latency within TSC tooling, what I can do is generate a file walk locally ignoring `node_modules` (I have some tooling that does this).  However, you might imagine that my colleagues would likewise be baffled of, "hey you're rolling your own tool here, why not use TypeScript to do this?"  This creates the tension of, "wow, the TS folks haven't implemented this???" after overcoming whatever resistance -> disbelief -> time sink.  Plus there is the additional cost of implementing the tooling.

Please don't be too alarmed at my feedbacks, in general this is not an isolated dynamic to TSC or Microsoft.  This dynamic has existed now in industry for half a decade or longer.  Sometimes development teams adopt tools without scrutiny as a form of architecture, and while one might claim job security to patch fixes for another company, some people prefer solving problems and adopting tools with more scrutiny.

**Comment by RyanCavanaugh** [comment]
Are you aware of TS's incremental mode, which does this all automatically?

Anyway, without a way to reproduce the problem you're alluding to, we have no next steps on our side and I can't follow up on this any further.

**Comment by mikegwhit** [comment]
Aye, have `incremental` set to true and still incur these lengthy runtimes.  Are you referring to setting `incremental: true` ???

I read through some remarks about `incremental` and IIRC that's somewhat where I had already drawn the conclusion that TS claims to have solved this issue as much as it can without ground-up rearchitecture (that might not bear fruit even).

It's really confusing though.  All I want to do is shrink the CPU burden from 5-8s to about 500ms to 1s.  I'd imagine only compiling the changes would help.  If `incremental` does this then I'm just at a loss.  If incremental were working, why is it compiling when there are no changes???

I apologize if I'm far off the mark or missing some simple syntax, but again even if I am drawing conclusions on bad data, then the problem seems to bubble up to Google is indexing bad information about these topics.  🤔

**Comment by VladRose** [comment]
I thought that I should repeat the structure to exclude something with subDir - **/.
I had `__stories__/**/**/*.test.tsx` and it didn't work, then I changed it to `__stories__/**/*.test.tsx` and it works.
Also stuff like this - `__stories__/**/*.test.[jt]s?(x)` doesn't work
