### ISSUE TITLE
3.9.1-rc regression: Unable to specify `rawText` when programmatically creating tagged template literals

### ISSUE THREAD

**Issue by petebacondarwin** [microsoft/TypeScript#38485]
**TypeScript Version:**  3.9.1-rc
**Search Terms:** tagged template literal rawText raw ES5

**Code**

The problem occurs when synthesising tagged template literals programmatically, and then trying to render them in ES5.

The API provides a method for specifying the "raw" parts of the template:

```ts
const template = ts.createNoSubstitutionTemplateLiteral('text', 'text');
```

But due to this regression this raw value is no longer being used.
An empty string is there, instead.

Here is a link to a reproduction: https://github.com/petebacondarwin/ts-3.9-rawtext-bug

**Expected behavior:**

```ts
$localize(__makeTemplateObject(["text"], ["text"]));
```

**Actual behavior:**

```ts
$localize(__makeTemplateObject(["text"], [""]));
```

**Playground Link:**
It is not possible to provide a Playground link because it only occurs when programmatically creating a tagged template literal AST node.

See the reproduction at https://github.com/petebacondarwin/ts-3.9-rawtext-bug

**Related Issues:**

This is a regression due to this commit: https://github.com/microsoft/TypeScript/commit/70399e146e2a426a2419adc3e3393fa0dc4cd59b#r39098346

**Comment by IgorMinar** [comment]
Hi ya'all!

This issue is currently blocking Angular from upgrading our ecosystem to TS3.9. We are exploring a workaround in case you can't fix this quickly, but we'd prefer a proper fix upstream. 

Thank you!

**Comment by DanielRosenwasser** [comment]
Gotcha. We're planning a patch release later this month. If we could get something in the nightly and have something official released in ~2 weeks' time, would that be acceptable?

**Comment by IgorMinar** [comment]
That would work if that's the best you can do. We are working towards cutting Angular v10-rc.0 next Wednesday, so we'll keep on pursuing our workaround for rc.0. Thanks!

**Comment by DanielRosenwasser** [comment]
3.9.3 should be published with a fix soon
