### ISSUE TITLE
Incorrect lexing of TLA await in try...catch

### ISSUE THREAD

**Issue by kitsonk** [microsoft/TypeScript#38483]
**TypeScript Version:**  3.8.3

**Search Terms:** top level await, try catch

**Code**

```ts
try {
  await (async () => {})(); // TS2304 cannot find name 'await'
} catch {
  //
}
```

**Expected behavior:**

The file is considered valid.

**Actual behavior:**

The file has an error at `await` of "TS2304 cannot find name 'await'".

**Playground Link:** https://www.typescriptlang.org/play?#code/C4JwngBA3gUAkAQwO4IJbAgCgQZzAOwGMsBKCAXgD5oBfEzEgbhhokIWEIAtp4B6PixhA

**Comment by lissein** [comment]
Hi,

This seems to be a problem with all the top level statements of the form `await (async () => { ... })()` and not only in try...catch.

I'm gonna work on it.

**Comment by Shayan-To** [comment]
Today I was adding some code to a function, and needed to make a function `async`. I accidentally put the `async` keyword on the wrong function and my code became something like this:

```
```

**Comment by Shayan-To** [comment]
Today I was adding some code to a function and needed to make the function `async`. But I accidentally put the `async` keyword on the wrong function and my code became something like this:

```
function f() {
    await(async () => 0)();
}
```

And typescript gives me this strange error:

```
a.ts:2:5 - error TS2304: Cannot find name 'await'.

2     await(async () => 0)();
      ~~~~~


Found 1 error.
```

And I'm like WHAT THE??? WHAAAT?? WHY?? And I search for the error message and I find this issue, and I'm very very confused for a long time, thinking that typescript does not support syntax like `await (async () => 0)()` and I say to myself very loudly "WHY in the world would such a compiler not support such syntax..."

I now realize that I have put the `async` keyword on the wrong function, and I've now learned (the strange way,) that you actually CAN define a variable named `await`, but I think that the error message in such a case as above should not be something like `Cannot find name 'await'.`...

**Comment by rbuckton** [comment]
> [...] but I think that the error message in such a case as above should not be something like Cannot find name 'await'....

Outside of an async function or the top level of a module, `await` is considered an identifier, so the error isn't *wrong*, per se. We can consider introducing a better error message for this specific case, considering you might have meant to declare the function as `async`. We already do that if your operand is not parenthesized: `function f() { await 1; }` gives you an error and a quick fix to "Add async modifier to containing function". We just don't currently offer that quick fix when we initially parsed it as a call expression.

**Comment by rbuckton** [comment]
I created #46986 to track the possibility of a distinct error message for an ambiguous `await`, along with providing the relevant quick fix.
