### ISSUE TITLE
Tuple element type fails to be inferred

### ISSUE THREAD

**Issue by markusjohnsson** [microsoft/TypeScript#38499]
**TypeScript Version:**  4.0.0-dev.20200511

**Search Terms:** tuple keyof generic

**Code**

```ts

type Vertex = [number, string, boolean];

declare function myLookerUpper1<K extends keyof Vertex = keyof Vertex>(t: K): Vertex[K];
declare function myLookerUpper2<T, K extends keyof T = keyof T>(t: K): T[K];
declare function myLookerUpper3<T>(): <K extends keyof T = keyof T>(t: K) => T[K];

const r1 = myLookerUpper1(1); // string
const r2 = myLookerUpper2<Vertex>(1); // huge union
const r3 = myLookerUpper3<Vertex>()(1); // string

```

**Expected behavior:**

`r2` should have type `string`, like the less generic case `r1` and the work-around `r3`.

**Actual behavior:**

`r2` has a huge union type:

```
const r2: string | number | boolean | (() => string) | (() => string) | (() => string | number | boolean | undefined) | ((...items: (string | number | boolean)[]) => number) | {
    (...items: ConcatArray<string | number | boolean>[]): (string | ... 1 more ... | boolean)[];
    (...items: (string | ... 2 more ... | ConcatArray<...>)[]): (string | ... 1 more ... | boolean)[];
} | ... 22 more ... | {
    ...;
}
```

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200511#code/FAFwngDgpgBAalATiKAPGBeGBtAdgVwFsAjJAGhgGcREBLXAcwuIHsWAbKAQ1wF0BuYMAAmUAMbsuiWADN8uMSFotcMQmAAybANZIAqhGiIAjAB4A0jDQpcwyjF1gWM+EhTosj56+RoAfAAUIABcMOYAlKEIvqjY5gIi4pLSMHIKSipqmjr6hkgATKYAKhSW1lC29l4uRZgOUE41gSFhkTBFcQmiElKy8orKqupaLLqIBkYAzMWBbRZWqDZ29Y3tddXtzaERmH7tnYLAYirUMCZ1wznjeSYBxuH8MAD0T1Q09AxHJyBn+RfZo1yRkK0XcgXujxeMAAFvgGLB5IMvrhTohJv8RmMJkhpqD-AFwncHs9XtQ6IxgEA

**Related Issues:**

**Comment by awerlogus** [comment]
If you pass the first type parameter to `myLookerUpper2` function, the second type parameter will be automatically inferred as default type assigned to it — `keyof T`. To improve type inference we can use default types only in cases when type parameter can't be inferred another way. So, it means that in case of this function 
```typescript
declare function myLookerUpper2<T, K extends keyof T = keyof T>(t: K): T[K]
```
function parameter `t` should have higher priority to infer type parameter `K` than default type parameter value `keyof T`

**Comment by markusjohnsson** [comment]
@awerlogus yes, I guess that is what is happening. 

A way of declaring that `K` should be inferred from usage (even if `T` is provided) would solve the problem; then I would not need to assign a default type for `K`, but still only provide a type for `T` at the call site.

**Comment by awerlogus** [comment]
I think, allowing you pass only first type argument without default value assigned to the second type parameter is a bad idea. In this case we will be needed to add also another way to mark required type parameters. Currently they are required by default if no default value is assigned to them.

**Comment by RyanCavanaugh** [comment]
When any type arguments are present, the remaining type arguments are set to their defaults rather than going through inference (the desirability of this is debatable, but that's the behavior). #26242 would allow you to specify the other behavior
