### ISSUE TITLE
[bug] existing module shows as not found in VS Code

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#38495]
I marked this as [project-references?] because I started noticing these issues when I tried to switch a project to using `--build`. Not sure if it is actually related.

**TypeScript Version:**  3.8.3

**Search Terms:**

typescript no definition found for

**Code**

```ts
import './fake-process'
```

**Expected behavior:**

It should find the module, and I should be able to navigate to it in VS Code

**Actual behavior:**

![existing-module-not-found](https://user-images.githubusercontent.com/297678/81643500-8f075f00-93da-11ea-96ec-4a5cd05239b7.png)

**Playground Link:** 

Unfortunately I don't have a public reproduction yet; it is in a private repo.

**Related Issues:** 

Possibly related: https://github.com/microsoft/TypeScript/issues/38494

**Comment by sheetalkamat** [comment]
We would need more information to be able to investigate if this is really bug or configuration issue..  We would need repro steps, tsserver log. You can also enable `traceResolution` in tsconfig to see why and where the module resolves to or doesnt resolve.

**Comment by trusktr** [comment]
Ah, that's good info. Thanks! I will see if I can get more info.

**Comment by trusktr** [comment]
@sheetalkamat I found this:

```
❯ npm run typecheck | grep fake
======== Resolving module './fake-process' from '/home/trusktr/src/my-project/apps/mapper-annotator/src/entry/index.ts'. ========
Loading module as file / folder, candidate module location '/home/trusktr/src/my-project/apps/mapper-annotator/src/entry/fake-process', target file type 'TypeScript'.
File '/home/trusktr/src/my-project/apps/mapper-annotator/src/entry/fake-process.ts' exist - use it as a name resolution result.
======== Module name './fake-process' was successfully resolved to '/home/trusktr/src/my-project/apps/mapper-annotator/src/entry/fake-process.ts'. ========
```

which seems to indicate that `tsc` is able to find the module, but it is only in VS Code that when I try to go to the definition it says `No definition found`.

**Comment by trusktr** [comment]
As for the TS Server log, I see an empty `definitions` response:

```
Info 504  [14:18:41.901] request:
    {"seq":74,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"/home/trusktr/src/my-project/apps/annotator/src/entry/index.ts","line":10,"offset":12}}
Perf 505  [14:18:41.902] 74::definitionAndBoundSpan: elapsed time (in milliseconds) 0.7504
Info 506  [14:18:41.902] response:
    {"seq":0,"type":"response","command":"definitionAndBoundSpan","request_seq":74,"success":true,"body":{"definitions":[]}}
```
