### ISSUE TITLE
Overriding "incremental" gives error on tsBuildInfoFile

### ISSUE THREAD

**Issue by crystalfp** [microsoft/TypeScript#38493]
**TypeScript Version:**  3.8.3

**Search Terms:**
incremental, tsBuildInfoFile

**Code**
Create subdirectory `client` containing the following `tsconfig.json` file:
```ts
{
    "compilerOptions": {
        "target": "esnext",
        "module": "es2015",
        "noLib": false,
	"outDir": "../server/http/widgets",
        "sourceMap": true,
        "incremental": true,
        "tsBuildInfoFile": "./tsconfig.tsbuildinfo"
    },
    "include": [
        "*"
    ],
    "exclude": [
        "./node_modules",
        "./tests"
    ]
}
```

**Expected behavior:**
Overriding "incremental" on the command line this way `tsc -p client --incremental false` should ignore tsBuildInfoFile setting. I am doing this to force full recompilation of the project.

**Actual behavior:**
The above command line gives the following error:
```
client/tsconfig.json:8:9 - error TS5069: Option 'tsBuildInfoFile' cannot be specified without specifying option 'incremental' or option 'composite'.

8         "incremental": true,
          ~~~~~~~~~~~~~

client/tsconfig.json:9:9 - error TS5069: Option 'tsBuildInfoFile' cannot be specified without specifying option 'incremental' or option 'composite'.

9         "tsBuildInfoFile": "./tsconfig.tsbuildinfo",
          ~~~~~~~~~~~~~~~~~
```
Reproduce by running: `tsc -p client --incremental false`

**Playground Link:** 

**Related Issues:** 
None

**Comment by sheetalkamat** [comment]
This is desired behavior as we want to warn people if they specify incorrect configuration. You can run `tsc -p client --incremental false --tsBuildInfoFile null` to fix the error

**Comment by sheetalkamat** [comment]
Related #36997
