### ISSUE TITLE
Emitted__exportStar helper has missing ; which causes runtime error

### ISSUE THREAD

**Issue by alan-agius4** [microsoft/TypeScript#38501]
**TypeScript Version:**  3.9.1-rc

**Search Terms:**
__exportStar
export star

**Code**
Input
```ts
export *  from './test';
```

Output
```js
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
} /* There is a missing semi-colon here */
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "./test"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    __exportStar(require("./test"), exports);
});


```
When module target is configured UMD and helpers are emitted. The `__exportStar` unnamed function declaration has a missing `;`, which causes an error during runtime `Uncaught TypeError: (intermediate value)(…) is not a function`

**Expected behavior:**
A semi-colon is added after the unnamed  `__exportStar` function declaration.
**Actual behavior:**
A semi-colon is missing from the output which cause a runtime error.

**Playground Link:** https://www.typescriptlang.org/play/?module=3&ts=4.0.0-dev.20200511&ssl=2&ssc=18&pln=2&pc=1#code/KYDwDg9gTgLgBAKjgMyhAtnA5AOgPQzADOMWA3AFBA

**Comment by DanielRosenwasser** [comment]
Please port the change to tslib

**Comment by alan-agius4** [comment]
On it @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Sorry, no, I didn't mean to ask you! Though I just made the change as well! 😅

**Comment by alan-agius4** [comment]
@DanielRosenwasser, I did the change to tslib https://github.com/microsoft/tslib/pull/101 though that shouldn't have any effect.

**Comment by DanielRosenwasser** [comment]
Thanks @alan-agius4!

**Comment by DanielRosenwasser** [comment]
Should be fixed now
