### ISSUE TITLE
Fail to short circuit an undefined private class field with optional chaining

### ISSUE THREAD

**Issue by motss** [microsoft/TypeScript#38503]
**TypeScript Version:**  3.8.3

**Search Terms:**
* private method
* private class field
* short circuit
* optional chaining
* typeerror
* cannot get property of

**Code**

```ts
     /** Truncated for brevity */
33   // this.#callback?.(this.#list, this); /** Fails to short-circuit with ?. */
34   if (this.#callback) this.#callback(this.#list, this); /** This works fine */
     /** Truncated for brevity */
```

**Expected behavior:**

Expected `this.#callback?.(this.#list, this)` to not execute when `this.#callback` is nullish.

**Actual behavior:**

```ts
/**
 * Fail to short-circuit with ?. and produces TypeError.
 * Expected it to behave just like:
 * 
 *   if (this.#callback) this.#callback(this.#list, this);
 *
 */
this.#callback?.(this.#list, this);
```

```sh
Uncaught TypeError: Cannot read property 'call' of undefined
    at A.add (eval at <anonymous> (main-3.js:1239), <anonymous>:42:62)
    at eval (eval at <anonymous> (main-3.js:1239), <anonymous>:54:3)
    at main-3.js:1239
```

**Playground Link:** 

Run the [reduced test case in TypeScript playground] and see the result in DevTools.
Comment and uncomment L33 and L34 to see the different results when they should behave the same.

**Related Issues:** 
Tried to look up but could not find one.

[reduced test case in TypeScript playground]: https://www.typescriptlang.org/play/?ssl=19&ssc=2&pln=20&pc=1#code/MYGwhgzhAECCAyBLCAXaBvAUNH0DEIyKAXNAHYCuAtgEYCmATgNoC60AvNKwNyba4AHCjULBoYACYSAFAA9SlWowCUpAG4B7RBIz9cuFAAtkAOgJETQiIbnLe+gL599QkYjGg6YBtNXRN2rr6+kam5qgcXCz2uE560K6i0HRkKAyIdBC+CtT0zGxYwbgMdCgUDGTQoRBmhKgxOE5xiKmMAGZgwHRwAAoMGgKMKBkwhbjAYCAgNJ0A1tJ1JHBIqAA00Bo0AFZ0wEuwfgESvHGgkDCwQbjh+ytonGR0AO7LRL4N+BNTM8CzAPykWB9AZDEZMADkX2mc3B0WcgmESWAGjIqAYFD2Gh8UJ+-0BwMGDGGmQhOJhLGUVyKiDa0GkKAAnoMNLTpGTfpT2FzoOC2hQyHtECjwZTqmZ2bNIhKPnEXIj3OIpHIckoGIctDoxkUxTcTJIZLI7PCigB6ABUZugACEAKoAcVIABVjDAJhQIJlkgx+gxoGaTfF9CaTVUXeLJtDfn8TPSwzd1tUjUUcDS6TqJaK4xLY2FFgmXUnYsaEvKPCAvD51YEtcEdYsTJ5vO94k0+MjUWgwJFHi9YM32xEaN3nnBpAsiOtNhBOQA+KnQAcacsmEAaADm0kDuAAsmAjCY2qusdJCW0sVQwAK6CYyBonr4-dAAIwABmgAFJny-lKstzgp7+ybQPWKRpCMvjxEaDhGpgYB6kqT5GnB+rSAATDBNDwTIADMRqYShAAsdhAA

**Comment by nmain** [comment]
Simplified repro:
```ts
class C {
    #a;
    b() {
        this.#a?.();
    }
}
new C().b();
```

[Playground Link](https://www.typescriptlang.org/play/?ssl=8&ssc=1&pln=1&pc=1#code/MYGwhgzhAEDC0G8BQ1XQMRgNwrQIwAoBKRXNNAFwAsBLCAOkwH57idyBfJLgOwFMA7nGL1CRHEA)
