### ISSUE TITLE
Specific type incompatible with and interface `[key: string]: any` in generic

### ISSUE THREAD

**Issue by Kerumen** [microsoft/TypeScript#38513]
**TypeScript Version:**  3.8.3

**Search Terms:** `property is missing in type` / `{ [key: string]: any }`

**Expected behavior:**

There should be no error.

**Actual behavior:**

TS is emitting an error: `Property 'blabla' is missing in type 'Params' but required in type 'MyParams'.`
Apparently, `type MyParams = { blabla: string }` is incompatible with `interface Params { [key: string]: any }` when used in generic.

**Related Issues:**

**Code**
```ts
// Basic declarations

interface Params {
  [key: string]: any
}

interface RequestFunction<T extends Params = Params> {
  params: T
}

// My function

type MyParams = {
  blabla: string
}

const myFunction = async (request: RequestFunction<MyParams>) => { }

// Export everything

const cloudFunctions: [string, (request: RequestFunction) => any][] = [
  ['my-function', myFunction],
]
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?#code/PTAECEEMGcEsGNQBMCm8A2kBOkAusB7AO2gChTYjcUsAzSeFUABW0gFtpQBvU0UANoBrFAE8AXKGi4slAOYBdSZCKjSAX3KVqdBkwBKKAI4BXFNIBiJovHzEAPABVQKAB7UiSLqxydQAXhY2TgA+Hj5QAAdg6ElHDXIQUABZUVBaa1tCInJcUUimVJ8OLkDefgAjTCrISWlZIjkE0nhiaVB2USsbOyIA0BhRG1AACixjM2lJQ1NzXG6shyKYkIBKALDuUE1SJIBRV0iCLFwXADcaUVwAC3lyVpJTjAITJAXe2MF6+QAaUfHZlNQDNJvNMr11v4wipRAoBAp+gIIgIAOSdAC0GR62RRf0672yCh+pAUQA)

**Comment by RyanCavanaugh** [comment]
This is the correct behavior. Your type declaration says that
```ts
cloudFunctions[0][1]({ params: {} });
```
is a legal line to write, but your function declaration says that this line could appear in the implementation:
```ts
const myFunction = async (request: RequestFunction<MyParams>) => {
  request.params.blabla.toLocaleLowerCase();
}
```
which would cause a crash

**Comment by Kerumen** [comment]
Thanks for your reply.

So how can I write my interface `Params` to make it "generic" but also accept the type `RequestFunction<MyParams>`?
