### ISSUE TITLE
React JSX optimizations

### ISSUE THREAD

**Issue by prabirshrestha** [Microsoft/TypeScript#3851]
Babel supports two JSX optimizations when using React 0.14. https://babeljs.io/blog/2015/03/31/5.0.0/#react-optimisations

1. Constant Elements 
2. Inlining `React.createElements`

Any plans to support these sort of optimizations in TypeScript?

**Comment by tinganho** [comment]
Note that it support is through a plugin and not natively:
```javascript
require("babel").transform("code", {
  optional: ["optimisation.react.constantElements"]
});
```

**Comment by RyanCavanaugh** [comment]
I don't think we're going to port over all of the advanced JSX emit options. People who really need them (which should realistically be very few) can use `--jsx preserve` and configure their JSX transformer appropriately.

Hopefully we can get a pluggable emitter figured out in the near future so we can re-use some of these techniques.
