### ISSUE TITLE
 When two parameters have the same generic type, when using typeof to constrain one, the other type is wrong

### ISSUE THREAD

**Issue by Hucy** [microsoft/TypeScript#38524]
**TypeScript Version:**  3.8.3

**Search Terms:**

**Expected behavior:**

**Actual behavior:** y: T  Argument of type 'T' is not assignable to parameter of type 'string'.(2345)

**Related Issues:**

**Code**
```ts
// Welcome to the TypeScript Playground, this is a website
// which gives you a chance to write, share and learn TypeScript.

// You could think of it in three ways:
//
//  - A place to learn TypeScript in a place where nothing can break
//  - A place to experiment with TypeScript syntax, and share the URLs with others
//  - A sandbox to experiment with different compiler features of TypeScript

function fn<T>(x:T, y:T):boolean{
    if (typeof x === 'string') {
        return x.includes(y)
    }
    return x === y
}

// To learn more about the language, click above in "Examples" or "What's New".
// Otherwise, get started by removing these comments and the world is your playground.
  
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// Welcome to the TypeScript Playground, this is a website
// which gives you a chance to write, share and learn TypeScript.
// You could think of it in three ways:
//
//  - A place to learn TypeScript in a place where nothing can break
//  - A place to experiment with TypeScript syntax, and share the URLs with others
//  - A sandbox to experiment with different compiler features of TypeScript
function fn(x, y) {
    if (typeof x === 'string') {
        return x.includes(y);
    }
    return x === y;
}
// To learn more about the language, click above in "Examples" or "What's New".
// Otherwise, get started by removing these comments and the world is your playground.

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.staging-typescript.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBZJcWCoCjwLzJTgAHhwAD4ABSrfI4fh4bkASnyIPgjU4AG9FCUSojQOzUC0SWCALwq0AAckEqEonGYav5oAlUqNoCcBLIXlWAQysGg7G4+nZeH5kqlAF8XSVTYSLaAVUrQHhFO7ijgGh5zaBEPABgwQewaN83GZmOwGMxIPwbepErH4HoRF4AEQAUVWDEQNX0haSOML4AcqA1oAAcpAJIWgioAPLfMi7QQZrSQY6oRwKVzSPAmyBRnSjLD6FAIRAw4RXRMSaPREQGDg47osNhcbhBEpAA)

**Comment by RyanCavanaugh** [comment]
This is the correct behavior. A legal call to `fn` would be `fn<string | number>("a", 10)`, and `number` is not a valid argument to `includes`.

**Comment by Hucy** [comment]
@RyanCavanaugh Oh  my fault THX
