### ISSUE TITLE
Improve accessibility on terminal output

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3852]
The output on `tsc` is not so accessible. I find it hard to read because everything is white and no newlines between lines.

Also when running `tsc -w` it is very hard to distinguish latest build from the second latest. 

These problem can be solved if the output where a little bit more colorized.

**Comment by danquirk** [comment]
I think @DanielRosenwasser might actually already be working on exactly some things to help out with this.

**Comment by tinganho** [comment]
ok nice!

**Comment by Gaelan** [comment]
:+1:

**Comment by myitcv** [comment]
Can I ask that if colourisation of terminal output is considered that it be off by default? Covers the case where tools consume the output of `tsc`.

**Comment by DanielRosenwasser** [comment]
I've put out #5140 if you guys'd like to try it out and give some feedback. :smiley:

**Comment by DanielRosenwasser** [comment]
Give it a try, it should be out in tonight's nightly, and uses the `--pretty` flag.
