### ISSUE TITLE
RFC: Remove the first period from version numbers to reduce version numbering confusion

### ISSUE THREAD

**Issue by zakhenry** [microsoft/TypeScript#38527]
## Search Terms
Semver major minor patch version

## Suggestion

The case to [move typescript to semver](https://github.com/microsoft/TypeScript/issues/14116) has already been discussed at length, and this issue is not that. I agree that strict semver isn't a great fit for Typescript, however it remains that case that nearly every major npm package does follow the semver pattern, admittedly to varying degrees of quality.

Rather than suggesting that Typescript just move to semver, I'm suggesting that the versioning pattern is changed to remove the first period, such that **rather than the next version being `4.0.0` (current being `3.9.2`), it should be `40.0`**.

Subsequent versions would be `40.1`, `40.2`, `41.0` ...etc 

* This will reduce the repeated confusion every time a developer expects that Typescript is using semver and is surprised to see breaking changes in the changelog (or worse in their code after assuming it was minor)
* Typescript can still broadly keep the same pattern of releases
* None of the confusion about `4.0` following `3.9` but actually being the same magnitude of change as the `3.8` to `3.9` change. If you expect semver to be the pattern (a fair assumption), the natural next version would be `3.10`

## Difficulties
Making a jump from `3.9.x` to `40.0.x` is a difficult one to make exclusively in terms of communicating the change to developers. I imagine the vast majority of developers would be indifferent to, or embrace the change, but there could be a vocal few that would rail against the change. I think Typescript is a more than big enough project to safely weather any fallout from it as the developer community is generally a sensible bunch.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment]
From #14116 (first response):
> TypeScript never claimed to follow semantic versioning, in the sense that breaking changes imply major versions.

**Comment by RyanCavanaugh** [comment]
We don't intend to change this - we've stuck with this versioning scheme for nearly 8 years now, and changing it is going to create more confusion than would be outweighed by any problems it might fix.
