### ISSUE TITLE
Cannot read property 'flags' of undefined with a d.ts file

### ISSUE THREAD

**Issue by Bene-Graham** [microsoft/TypeScript#38545]
**TypeScript Version:**  3.9.2
Also does not work in 4.0.0-dev.20200512

**Search Terms:**
Cannot read property 'flags' of undefined

**Code**
tsconfig
```json
{
	"compilerOptions": {
		"target": "es2017",
		"module": "None",
		"sourceMap": false,
		"strict": true
	}
}
```

a typing file in /typings/sweetalert.d.ts
```ts
export interface SweetAlert {
    (...params: any): Promise<boolean>;
}

// This seems to be the issue
declare global {
    const swal: SweetAlert;
}

declare const swal: SweetAlert;
export default swal;
```

**Expected behavior:**
tsc not to crash

**Actual behavior:**

tsc crashes

Some key takeaways:

1) It only crashed when using `tsc --watch -p tsconfig.json`, a build works fine `tsc -p tsconfig.json`
2) The problem seems to be an issue with `declare global { ... }` If I remove it it works fine
3) This only seems to be an issue when module is set to **None** in the tsconfig, ESNEXT and CommonJS seems to be fine
4) Changing the target does not seem to matter

I have included a link to a sample repo that should be able to reproduce this: https://github.com/Bene-Graham/TypeScriptError

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicating to #38556
