### ISSUE TITLE
[3.9.2] Browser specific types are deleted

### ISSUE THREAD

**Issue by screendriver** [microsoft/TypeScript#38543]
**TypeScript Version:**  3.9.2

**Search Terms:**

webkitDisplayingFullscreen
webkitSupportsFullscreen
webkitExitFullScreen
webkitExitFullscreen

**Code**

```ts
videoElement.webkitExitFullscreen()
```

**Expected behavior:**

Should compile like in the previous versions of TypeScript

**Actual behavior:**

Types are gone because the were deleted with commit 065a996345fcfafd3c744d2a724a1ae9f31f9ab0

Personally it makes totally sense to me to have only types that are standard spec compatible. But what bothers me is that the types were there before 3.9 and nothing was mentioned in the [changelog](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html). So was this deletion intended? Or is this some kind of "bug" (unintended)?

**Playground Link:** 

**Related Issues:**

**Comment by AviVahl** [comment]
Reference PR (which removed these types): https://github.com/microsoft/TSJS-lib-generator/pull/802
It was apparently intended, but wasn't documented in the announcement.

**Comment by screendriver** [comment]
Do you know if there is an alternative type definition at definitely typed that I can use? I didn't found something unfortunately.

**Comment by IllusionMH** [comment]
You can pick types that you need from 3.8 and use same approach recommended for 3.1 lib.dom.d.ts changes.
https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#some-vendor-specific-types-are-removed-from-libdts

**Comment by screendriver** [comment]
Yes but shouldn't this be mentioned somewhere as a breaking change in the release notes?

**Comment by orta** [comment]
Yeah, agreed - I'll add it to the ones on the site

**Comment by screendriver** [comment]
👍

**Comment by orta** [comment]
Shipped in https://github.com/microsoft/TypeScript-Website/commit/5bfa51c4e30ac967f4feb513486f0238c565aeec and in the handbook for the prod site

**Comment by screendriver** [comment]
Awesome. Thanks a lot!
