### ISSUE TITLE
Declaration emit breaks with varargs and this type specified in function type parameter

### ISSUE THREAD

**Issue by TimvdLippe** [microsoft/TypeScript#38550]
**TypeScript Version:**  4.0.0-dev.20200512

**Search Terms:** jsdoc, declaration, varargs

**Code**

`clazz.js`:
```js
export class Clazz {
  /**
   * @param {function(this:Object, ...*):*} functionDeclaration
   */
  method(functionDeclaration) {}
}
```

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "outDir": "lib",
    "declaration": true,
    "allowJs": true,
    "checkJs": true
  },
  "files": [
    "clazz.js"
  ]
}
```

**Expected behavior:**
The emitted declaration file is:
```ts
export class Clazz {
    /**
     * @param {function(this:Object, ...*):*} functionDeclaration
     */
    method(functionDeclaration: (...args: any[]) => any): void;
}
```
**Actual behavior:**
```ts
export class Clazz {
    /**
     * @param {function(this:Object, ...*):*} functionDeclaration
     */
    method(functionDeclaration: (args: any, ...args: any[]) => any): void;
}
```

Subsequent usages of a composite project break, as `args` is duplicated in the method argument types.

Note that removal of `this:Object` fixes the issue. Also, the following properly emits:

```js
export class Clazz {
  /**
   * @param {function(this:Object, ...*):T} functionDeclaration
   * @template T
   */
  method(functionDeclaration) {}
}
```

Note here that the `T` is unused in the function, but it fixes the emitted declaration file.

**Playground Link:** 

**Related Issues:** #38242 (we are successfully able to compile DevTools with the above workaround and the fix for #38242)

**Comment by sandersn** [comment]
The code that emits named, non-`new` parameters in closure function types is just wrong as far as I can tell.
