### ISSUE TITLE
Sinon stubbing failed after upgrade to 3.9.2

### ISSUE THREAD

**Issue by zorji** [microsoft/TypeScript#38568]
**TypeScript Version:**  3.9.2, 3.9.3

**Search Terms:** sinon, stub

**Code**

```ts
// file: ./src/stubber/index.ts
export { toStub } from './to-stub'

// file: ./src/stubber/to-stub.ts
export const toStub = () => {
  console.log('real stub')
}

// file: ./src/start.ts
import * as sinon from 'sinon'
import * as stubber from './stubber'
(async () => {
  sinon.stub(stubber, 'toStub').callsFake(() => {
    console.log('fake stub')
  })
  stubber.toStub()
})()
```

Run the start.ts script by compiling it with `tsc` or simply use `ts-node`.
I'd expect it print fake stub but now it prints real stub. It's working as expected for typescript@3.8 or lower, start breaking from 3.9.2.

**Expected behavior:**

Print "fake stub"

**Actual behavior:**

Print "real stub"

**Playground Link:**  Can't provide Playground link because it contains multiple files

**Related Issues:**  Nope

**Comment by nico1510** [comment]
The same problem exists for jasmine's `spy`s. I tracked the problem down to this change https://github.com/microsoft/TypeScript/pull/32264. After this change `get` and `set` properties of modules imported with star syntax are no longer enumerable which then causes a crash in jasmine's check [here](https://github.com/jasmine/jasmine/blob/b4cbe9850fbe192eaffeae450669f96e79a574ed/src/core/SpyRegistry.js#L53).
Most likely the same can be said for Sinon and I also saw a comment from someone having this problem with jest [here](https://github.com/facebook/jest/issues/6914#issuecomment-628153427).

Should we tell those libraries to adapt their code or can we have a flag to keep those properties enumerable?

**Comment by msholty-fd** [comment]
I found this code to break when upgrading from 3.8.2 to 3.9.2. We use `ts-jest` to transform our TypeScript Jest tests.

```ts
import * as foo from 'some/path'
jest.spyOn(foo, 'bar');
```

I would get an error like:
```
<spyOn> : bar is not declared writable or has no setter
```

I resolved this by doing this workaround:

```ts
jest.mock('some/path', () => ({
  ...jest.requireActual('some/path'),
}));
const foo = require('some/path');
```

It's not pretty, but it at least unblocked me from upgrading.

**Comment by RyanCavanaugh** [comment]
ES module exports are specified to not be enumerable, so this is the expected behavior. Prior behavior was out of compliance with the spec.

**Comment by drtyh2o** [comment]
Does you comment still apply if we are using `"commonjs"` modules, @RyanCavanaugh? I noticed the following difference between the emitted modules:

**Before**
```
seconds: [Function: seconds],
minutes: [Function: minutes],
hours: [Function: hours],
days: [Function: days]
```
**After**
```
days: [Getter],
hours: [Getter],
minutes: [Getter],
seconds: [Getter]
```

Both modules work fine, but the latter (3.9) breaks our ability to mock the imported functions with `Sinon`. We've had to roll back to 3.8 until we can resolve.

**Comment by RyanCavanaugh** [comment]
If you're targeting `commonjs` but writing ES module imports/exports, TS is still going to try to give you ES module behavior.

This code is effectively not legal ES, since it's attempting to modify (indirectly via `sinon.stub`) a readonly property (the properties of something imported with `import * as name` are not mutable). It should never have worked.

**Comment by squidfunk** [comment]
See https://github.com/jasmine/jasmine/issues/1817#issuecomment-630110087 for a temporary workaround.

**Comment by adjerbetian** [comment]
@RyanCavanaugh Sorry, I didn't understand your answer when you said

> If you're targeting commonjs but writing ES module imports/exports

I created a demo project here [typescript-3.9-commonjs](https://github.com/adjerbetian/typescript-3.9-commonjs) with a very simple node script. 
Do you mean that I should write `index.ts` differently?

**Comment by JordanPawlett** [comment]
> I found this code to break when upgrading from 3.8.2 to 3.9.2. We use `ts-jest` to transform our TypeScript Jest tests.
> 
> ```ts
> import * as foo from 'some/path'
> jest.spyOn(foo, 'bar');
> ```
> 
> I would get an error like:
> 
> ```
> <spyOn> : bar is not declared writable or has no setter
> ```
> 
> I resolved this by doing this workaround:
> 
> ```ts
> jest.mock('some/path', () => ({
>   ...jest.requireActual('some/path'),
> }));
> const foo = require('some/path');
> ```
> 
> It's not pretty, but it at least unblocked me from upgrading.

Just the workaround i was looking for!

**Comment by denieler** [comment]
Yeah, having the same issue, very annoying 👍

**Comment by ahnpnl** [comment]
Hi @SimenB not sure if you are aware of this ? I assume once jest supports fully esm this won’t be an issue ?

**Comment by SimenB** [comment]
Jest module mocks should work regardless, but you probably need to use `import()` so it's not evaluated statically

**Comment by AndyOGo** [comment]
@RyanCavanaugh 
You are right, ES module export shall not be enumerable.

Though may I ask you to consider testability.
And please do not publish breaking changes as a patch.

**Comment by squidfunk** [comment]
@AndyOGo see https://github.com/jasmine/jasmine/issues/1817#issuecomment-823329763 for an easy workaround monkey-patching `tslib`.

**Comment by AndyOGo** [comment]
Related:
https://github.com/microsoft/tslib/issues/103

**Comment by FauxFaux** [comment]
I did a similar thing with babel, https://github.com/snyk/babel-plugin-mutable-imports , but ended up just forking sinon to make it warn, and fixing all the code. https://github.com/sinonjs/sinon/pull/2319

**Comment by shawnjones253** [comment]
I noticed this only breaks if there is an `export x from y` in between your test code and the module you want to stub. If the module/function you want to stub is directly exported already, you can directly import it in your test code and this still works. Ended up saving me some refactoring and going down the proxyquire rabbit hole.

```
// file: ./src/stubber/index.ts
export { toStub } from './to-stub'

// file: ./src/stubber/to-stub.ts
export function toStub() {
  console.log('real stub')
}

import * as sinon from 'sinon'
import * as stubber from './stubber'
import * as toStub from './stubber/to-stub'

// file: ./src/start.ts
(async () => {
  // breaks: logs 'real stub' because toStub is an intermediate reference here
  // (imported via the 'export from' in 'stubber/index')
  sinon.stub(stubber, 'toStub').callsFake(() => {
    console.log('fake stub')
  })
  stubber.toStub()

  // works: because toStub is a direct reference
  // (imported via 'export function' in 'stubber/to-stub')
  sinon.stub(toStub, 'toStub').callsFake(() => {
    console.log('fake stub')
  })
  toStub.toStub()
})()
```

**Comment by cqcmdwym** [comment]
> If you're targeting `commonjs` but writing ES module imports/exports, TS is still going to try to give you ES module behavior.
> 
> This code is effectively not legal ES, since it's attempting to modify (indirectly via `sinon.stub`) a readonly property (the properties of something imported with `import * as name` are not mutable). It should never have worked.

Hi @RyanCavanaugh so if we are targeting 'commonjs', how can be writing without ES module imports/exports in ts 3.9? I mean how can we make it mutable? Thanks.
