### ISSUE TITLE
Import in Definition File Hides Interfaces

### ISSUE THREAD

**Issue by pixelshaded** [Microsoft/TypeScript#3857]
I'm trying to merge some missing methods from https://github.com/borisyankov/DefinitelyTyped/blob/master/i18next/i18next.d.ts for my node server.
```
interface IWebTranslateOptions {
  i18nextWTOptions: {
    languages: Array<string>;
    namespaces: Array<string>;
    resGetPath: string;
    resChangePath: string;
    resRemovePath: string;
    fallbackLng: string;
    dynamicLoad: boolean;
  }
}

interface I18nextStatic {
  serveClientScript(app: any): I18nextStatic;
  serveDynamicResources(app: any): I18nextStatic;
  serveMissingKeyRoute(app: any): I18nextStatic;
  serveChangeKeyRoute(app: any): I18nextStatic;
  serveRemoveKeyRoute(app: any): I18nextStatic;
  serveWebTranslate(app: any, options: IWebTranslateOptions): I18nextStatic;
}
```

This compiles and works, however I'd like to change all those app any types to express types. If I add

```
import express = require('express');
```

to the file, the compiler says it can't find the other interfaces anymore.

**Comment by RyanCavanaugh** [comment]
When you add `import` or `export` to a top-level declaration, the file becomes a module, and declarations of interfaces create new types in your module scope rather than augment existing interfaces declared at the global scope.

To fix this, move the interfaces you want to augment to a separate .d.ts file.

**Comment by pixelshaded** [comment]
Alright. That explains why it can't find the interfaces anymore, but not how I can achieve what I want. The interfaces I created are in their own .d.ts file. I18nextStatic is top-level declaration in the i18next.d.ts, i.e. it's not part of any module. How do I augment this interface with express types without importing express? If i18next.d.ts declared I18nextStatic in a module, then Id just redeclare that module and importing express wouldn't be an issue.

**Comment by mhegazy** [comment]
this is now tracked in  #4166
