### ISSUE TITLE
10x compiler performance

### ISSUE THREAD

**Issue by newtack** [microsoft/TypeScript#38573]
Typescript is awesome. While I am sure there are more features that may still be added, the main pain point I have right now in terms of usability is that compilation speed makes me wait on a medium sized project (~ 45K lines of Typescript). 

Typescript compilation speed also is a bottleneck in Deno, which was just released, see https://deno.land/v1#tsc-bottleneck

If we could have one feature that would make Typescript much better, it would be 10x compiler speed. 

While incremental improvements should be considered, I think it is time for the team to really look at what would be needed to 10x compiler speed.

Going with Rust/wasm and a massively parallel (web worker?) approach may be able to get us there.

**Comment by nmain** [comment]
The team is constantly monitoring performance of the compiler and impact of new changes on performance.  An entire order of magnitude of speed difference though?  That's not something you can pull out of a hat.

**Comment by RyanCavanaugh** [comment]
Are people under the impression that we haven't thought about this already? 😕

**Comment by newtack** [comment]
@RyanCavanaugh I wasn't aware of it. :-)

But, with Deno 1.0 being released and them wanting a Rust based compiler, rather than having many different teams (Typescript/Deno/swc/etc.) working separately on it, it would be great if this could be a joined effort.

**Comment by RyanCavanaugh** [comment]
Engineering teams at Microsoft are aware of the concepts of rewrite and native languages, I assure you.

**Comment by sod** [comment]
The swc developer seems to literally try to add tsc capabilites to it's compiler right now, see 
https://github.com/swc-project/swc/pull/889 (d.ts generation) & https://github.com/swc-project/swc/issues/571 (type checking)

**Comment by JohanHeyvaert** [comment]
swc seems very promising. Especially for unit testing a monorepo the typescript compilation is too slow. The WallabyJS advises to try swc too. Cf. https://wallabyjs.com/blog/optimizing-typescript.html
Hopefully the official compiler can learn from this?

**Comment by Bessonov** [comment]
From my point of view, bet on alternative compiler is very dangerous. TypeScript is too complex and too powerful language. BTW, I'm not sure that swc will stay free. I can throw [sucrase](https://github.com/alangpierce/sucrase) in. Interesting point about sucrase is, well, it's ts/js based and (possibly) faster than rust-based swc.

I think there are different use cases of slowness. For example, in most cases slow compilation CI is not good, but OK. While slow compilation during development is very annoying. Currently, I use [webpack 5 with caching(!) + ts-loader + fork-ts-checker + devServer/nodemon](https://github.com/Bessonov/monorepo-starter). And it works fast enough. Additionally, vscode do own checks. I will love to have more reliance on vsc and get rid fork-ts-checker during development.

**Comment by Bessonov** [comment]
Finally, it happened - the TypeScript team is porting `tsc` to Go! See [this blog post](https://devblogs.microsoft.com/typescript/typescript-native-port/).  

I understand their choice, however, personally, in the era of LLMs, I would prefer a rewrite in Rust rather than a port to Go - especially to minimize bugs. And maybe even achieve more parallelization.
