### ISSUE TITLE
Debugging TypeScript problems Wiki 404

### ISSUE THREAD

**Issue by fireairforce** [microsoft/TypeScript#38575]
**TypeScript Version:** NA

**Search Terms**:
- Debugging TypeScript problems wiki 404

**Code**

NA

**Expected behavior:**

The Link at https://raw.githubusercontent.com/wiki/Microsoft/TypeScript/debugging can visit

**Actual behavior:**

The Link get a 404 error

**Comment by RyanCavanaugh** [comment]
What is the *incoming* link to that page?

**Comment by fireairforce** [comment]
@RyanCavanaugh 
![image](https://user-images.githubusercontent.com/32598811/82006188-d0796200-9699-11ea-8c90-8a2d2be9d77b.png)

**Comment by fireairforce** [comment]
> What is the _incoming_ link to that page?

at the picture below
