### ISSUE TITLE
Extended enum can't be used as type in extended interface

### ISSUE THREAD

**Issue by nazar-pc** [microsoft/TypeScript#38585]
**TypeScript Version:**  3.9.2 and 4.0.0-dev.20200514

**Search Terms:** TS2430 TS2535

**Code**

```ts
enum BaseEnum {
    A = 0,
}

enum ExtendedEnum {
    A = BaseEnum.A,
}

interface IBaseType {
    field: BaseEnum.A;
}

interface IExtendedType extends IBaseType {
    field: ExtendedEnum.A;
}
```

**Expected behavior:**
`A` field in both enums is obviously the same, hence interfaces should be fully compatible too.

**Actual behavior:**
2 errors, which may in fact be 2 separate issues, but I'm not 100% sure:
```
Interface 'IExtendedType' incorrectly extends interface 'IBaseType'.
  Types of property 'field' are incompatible.
    Type 'ExtendedEnum' is not assignable to type 'BaseEnum'.(2430)
Enum type 'ExtendedEnum' has members with initializers that are not literals.(2535)
```

**Playground Link:** https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200512&ssl=1&ssc=1&pln=2&pc=11#code/KYOwrgtgBAQghgZ2AUXNA3gKCjqBBKAXigAYAaTAX001EimQA8AXUAE2DdXq13yNiIUaAHR4K1TAEsQrAE4AzOAGNgUAJLwkAFQCeABzW9cCqcAA2bAFyCk3CGIDcVGjPlLVGpqxAc2ewyhgFnYEDS1gAKNsEzNLG292TnsnFyA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/20920

**Comment by RyanCavanaugh** [comment]
Enums are intentionally not assignable to each other like that; this is one of their reasons for existing.

**Comment by nazar-pc** [comment]
I'm not extending enums per say, I'm using its variants as values. And it works just fine except when in extended interface.
