### ISSUE TITLE
Feature Request: Enumerable get/set

### ISSUE THREAD

**Issue by ackava** [microsoft/TypeScript#38587]
From 3.9 TypeScript is breaking all of our existing code base, and I understand ES conformance is an issue. So here is a simple request
## Use Cases

```typescript
class Foo {

     // following directive makes accessor enumerable...
     // @ts-enumerable 
     public get bar() {
     }
}
```

This is important as we can easily create the type of members we want to generate. 

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by erichiller** [comment]
I would like to second that the new behavior of TypeScript 3.9 is breaking code. A way to define enumerability would be great

**Comment by RyanCavanaugh** [comment]
We have a policy of never removing flags, so this would effectively be an infinite support burden on our side for the sake of a spec incompliance that should never have existed. I'm sorry you have code that depended on it, but we don't intend to continue to ship that bug in any form.

**Comment by doriansmiley** [comment]
I have a question. How is one expected to iterate over the properties of an object where the underlying instance variable is supposed to be private? For example:
```
f = function(){
  const _s = 'test'; // actually private
  Object.defineProperty(
                this,
               's',
                {
                    get: () => _s,
                    enumerable: false
                }
   )
}
let r = new f();
Object.keys(r); //[]
```
Is the assumption in TypeScript that the transpiler isn't going to attempt to scope private vars to the closure scope of the function so this isn't an issue? I noticed all my private vars are visible with `Object.keys`, so I could work around this. However it feels like an anti pattern if you ever want to take advantage of scoped members in ES classes. There is a stage 3 proposal for [private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields). It seems like TypeScript is going to need to support this eventually. For example:
```
class g {
   #_s = 't';
   get s() {return this.#_s};
}
b = new g();
b.s; // 't'
b.#_s; // Uncaught SyntaxError: Private field '#_s' must be declared in an enclosing class
```
This also seems supportable if you transpile to something like:
```
class g {
   constructor(sayWhat){
      let _s=sayWhat; // this was marked private _s: string;
      Object.defineProperty(
                this,
               's',
                {
                    get: function() {return _s},
                    enumerable: true //pretty much required if I want introspect
                }
      )
   }
}
let r = new g();
Object.keys(r); //['s']
```
This sort of sucks right now. Everyone can see and access my privates, but my own code can't iterate over them with `Object.keys`. I'm forced to rely on the privates being public for the world to see, and that's sort of embarrassing. Are there any other options here?
