### ISSUE TITLE
Type Narrowing in Object Literal Lookup for React

### ISSUE THREAD

**Issue by fabb** [microsoft/TypeScript#38588]
**TypeScript Version:**  3.9.2

**Search Terms:** type narrowing, react

**Expected behavior:**

A lookup in an object literal could narrow the type that is used as key to that object. That would help in React which does not allow `switch` in curly braces.

**Actual behavior:**

Typescript does not narrow the type which makes it impossible to use discriminated unions in object literals in React curly braces.

**Related Issues:**

No related issues found.

**Code**
```ts
import React from 'react'

type MessageType =
      | {
            type: 'EMAIL'
            subject: string
            message: string
      }
      | {
            type: 'MESSAGING'
            message: string
      }


const ContactComponent = ({ messageType }: { messageType: MessageType }) => (
      <div>
            {{
                  EMAIL: <div>
                        <div>
                              subject: {messageType.subject} // type narrowing does not kick in
                        </div>,
                  <div>
                              message: {messageType.message}
                        </div>,
                  </div>,
                  MESSAGING: <div>
                        message: {messageType.message}
                  </div>
            }[messageType.type]}
      </div>
)
```

<details><summary><b>Output</b></summary>

```ts
import React from 'react';
const ContactComponent = ({ messageType }) => (React.createElement("div", null, {
    EMAIL: React.createElement("div", null,
        React.createElement("div", null,
            "subject: ",
            messageType.subject,
            " // type narrowing does not kick in"),
        ",",
        React.createElement("div", null,
            "message: ",
            messageType.message),
        ","),
    MESSAGING: React.createElement("div", null,
        "message: ",
        messageType.message)
}[messageType.type]));

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAWSQGdGUBzJAFWtoF5S4BggD5wA3v0GTJVGgC4CAUToBBAJIAZMlO1xGAVwBGAKyQZ5jGFGAA7VhJ2CQTFu3OWbd7QF97wsb4cZJHl8OgUAZXDlAHFVADlorQdHZzZg3XdbALgfcjQIaws4AGECmHQYUvACpGt4HjgAClE4J2Y0rhoc+Ra2l05ueQZ29k7aLwBKOB4APibsgB4AE2AANxns7VFxZOSlNXV5ZbWN3bPBY-XN87P9Y1MYHr6O7gA6O5MMLzgAeh+4IJwawoKA4ADuHjgSwgTCBEHgAGtgGgEXAbNcbhcfit1gAaDHJS6nTEk56uMRkgY0V6UnwkwnYk74+kCBaMvEEhxhSIxeLRI444ksqSUp6pUZvWmcnRswXSrwAbUpY1eQQAunSpLKTqQJkA)

**Comment by nmain** [comment]
All keys on the object literal are computed before it is indexed, so there are many ways to get runtime observable breakage by allowing this kind of type narrowing.

**Comment by fabb** [comment]
Ok then I guess this cannot be improved, too bad.
