### ISSUE TITLE
False error when using directive prologues inside constructor with initialized properties.

### ISSUE THREAD

**Issue by ShyykoSerhiy** [Microsoft/TypeScript#3859]
class A {
    }

    class B extends A {
        public s: number = 9;

        constructor () {
            "use strict";   // no error?
            super();
        }
    }
results in "A 'super' call must be the first statement in the constructor when a class contains initialized properties or has parameter properties."

connected issue #3454

**Comment by DanielRosenwasser** [comment]
Yeah, this seems like a bug, though, keep in mind that a class is implicitly going to be parsed in strict mode in 1.5 - though, we don't have strict mode semantics if a method handle loses its `this` context.

**Comment by mhegazy** [comment]
@ShyykoSerhiy feel free to send a PR.

**Comment by mhegazy** [comment]
thanks @ShyykoSerhiy !
