### ISSUE TITLE
Declaration file non-exported types are importable

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#38592]
**TypeScript Version:**  3.9.2, 3.8.3, 3.1.6 3.0.3 (and likely more)

**Search Terms:**

declaration file export, non-exported types,  implicit export, dts, .d.ts, es-modules declaration

**Code**

**module.d.ts**

```ts
export declare const explicitlyExported: {};
declare const implicitlyExported: {};
```

**importer.d.ts**
```ts
import { implicitlyExported } from "./module"; // no error, is usable import
```

**Expected behavior:**

Error: Module '"./module"' has no exported member 'implicitlyExported'.

**Actual behavior:**

No error.

Even thought it wasn't exported, `implicitlyExported` is available for import.

**Playground Link:** 

n/a (declaration file issue)

**Related Issues:**

**Comment by mheiber** [comment]
As far as we can tell, this is how TS currently decides which mode to use for declaration files. Is this intended? What is the use case for implicit exports / mixed mode?


|                                     | has export declaration | no export declaration         |
| ----------------------------------- | ---------------------- | ----------------------------- |
| has >= 1 import or export statement | ESM-style              | implicit exports (mixed mode) |
| no import or export statements      | ESM-style              | ambient                       |
|                                     |                        |                               |

**Comment by weswigham** [comment]
Yeah, this is unfortunately... by design... if you add `export {}`, you'll get correct private-ness. We could opt to change this, but it'd definitely be a breaking change that walks back something that we've been calling "working as intended" for a long time.

**Comment by mheiber** [comment]
Thanks @weswigham

**Comment by renet** [comment]
Are there any plans on changing this behavior, maybe in a major release some time?

**Comment by RyanCavanaugh** [comment]
No
