### ISSUE TITLE
Support fold regions for lambda without block

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#38597]
## Search Terms

VSCode, Language Service

## Suggestion

Support fold regions for lambda without block

```ts
const fooBar$ = pageList$.pipe(
  map(pageList =>
    pageList.map(
      page =>
        page.pageConfig.find(
          config =>
            config.key.orgId === KeyOrgId.MyOrg &&
            config.key.Id === KeytId.MyKey,
        ).data ?? {},
    ),
  ),
  shareReplay(1),
)
```

This TypeScript code can't fold unless we change all `x=>y` to `x=>{ return y; }`

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Related issue

https://github.com/microsoft/vscode/issues/97415

**Comment by ahejlsberg** [comment]
Please post a complete example. Several functions/methods have no declaration so it's impossible to know what they do.

**Comment by xiaoxiangmoe** [comment]
@ahejlsberg

If we write arrow function without braces block, no fold regions:
![image](https://user-images.githubusercontent.com/8111351/82121468-d2d5dc00-97bf-11ea-954f-de2b8fcff794.png)

If we refactor it with braces block, it will support fold regions:
![image](https://user-images.githubusercontent.com/8111351/82121441-acb03c00-97bf-11ea-9a31-aef9f34eef61.png)
![image](https://user-images.githubusercontent.com/8111351/82121459-c18ccf80-97bf-11ea-8251-94e95e0b3eae.png)

**Comment by xiaoxiangmoe** [comment]
![image](https://user-images.githubusercontent.com/8111351/84364526-c6983f80-ac02-11ea-957b-7b62e9597164.png)

When we use rxjs with arrow functions, we cannot collapse most of the code.

**Comment by DanielRosenwasser** [comment]
@jessetrinity do we have any sort of heuristics where things that aren't blocks but are multi-line still get an outlining span?

**Comment by DanielRosenwasser** [comment]
Also, in this case the declarations aren't really necessary, outlining spans don't currently need semantic information.

**Comment by jessetrinity** [comment]
In most cases we collapse to the bounds defined by the open/close tokens. One example is JSX elements for which we collapse about `<` and `>`. 

In this case, we could probably just collapse the arrow function body?

![foldArrowFunction](https://user-images.githubusercontent.com/42591254/84552974-70410480-acc7-11ea-81f9-18bd034497ba.gif)

**Comment by xiaoxiangmoe** [comment]
@jessetrinity Great Job!

Also, can we fold long parameters list? 

For example: 
```ts
const bar$ = $foo.pipe(
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  map(x => x),
  shareReplay(1)
);
```

It would be great if we can fold in `.pipe()`

**Comment by DanielRosenwasser** [comment]
I would say arrow function body provided it spans 3 lines at least.

**Comment by Kingwl** [comment]
Happy to work on this if @jessetrinity not started the work.

**Comment by jessetrinity** [comment]
Go for it, I just added a case for arrow functions to the switch statement here:
https://github.com/microsoft/TypeScript/blob/e97003f26387402a17dfd9cf76874076f6b93053/src/services/outliningElementsCollector.ts#L165

It looked like there was more tweaking to do to to correctly fold the body when the function call is on the same line as the arrow e.g.
```ts
a => map(
    ...
)
```

**Comment by DanielRosenwasser** [comment]
Thanks @kingwl!
