### ISSUE TITLE
TS fails to see that var is always defined

### ISSUE THREAD

**Issue by garyo** [microsoft/TypeScript#38590]
In this typescript function (playground [here](https://www.typescriptlang.org/play/?ssl=19&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABAEwKbAIYgDZQApzYYBOAFAJSIDeixqUIxSA2gIwA0iADALqIC+AKFCRYCRAGd6BCaQAeALkRgQAWwBGqYpwBeSlRq2UaEBBMKoAdNjgBzebspDh4aPCQgADsgxRUAYQxVLQwAJRh7TxIgiSUqQUREdQwpUIB+fTVNbQSklNQAFQALegwM5SytdkF+Y1yYYERSKOIYy2TUxABCAF5EcDRgGDBUZEQAH3HEFraOwpKoDG6+gfRh0brExIammdUJdvzQxB7T-rBB9bHJ6ej9w6li0pOz1aGR5E2txNMwCSg8lICERiCcUOgsLhgSQKLlvjtmncDnNjqcVhc1h9yHDvrdWvcUWC5tDiMxeDjEqhsFJEAi9sj8k9Fi90ZcsRStvSHvNnn1iYQSGweDihN9fv9AagABpgrmEgBUiAAsr4ipZTLI5YyFhhsWKzAC5gAtWVI7nHRUqqBqiTDRH4hmPHV6rZSfBwWRzKWcY3Y-hAA)), the initial logic ensures that `params.baseTheta` and `params.baseR` are always defined. But Typescript (3.9.2) doesn't figure that out.

```typescript
function defaultPolar() { return [1, 0] }
function setPos(x: number, z: number) { console.log(x, z) }

function updateCameraRig(params: {
  baseR?: number,
  baseTheta?: number,
}) {
  if (params.baseR != undefined || params.baseTheta != undefined) { // at least one is defined
    if (params.baseR === undefined || params.baseTheta === undefined) { // at least one is undefined
      const basePolar = defaultPolar()
      if (params.baseR === undefined)
        params.baseR = basePolar[0]
      else if (params.baseTheta === undefined)
        params.baseTheta = basePolar[1]
    }
   // params.baseTheta is never undefined here but tsc still gives error saying possibly undefined:
    const baseX = params.baseR * Math.cos(params.baseTheta)
    const baseZ = params.baseR * Math.sin(params.baseTheta)
    setPos(baseX, baseZ)
}
```

Removing the "else" fixes the "undefined" error although it shouldn't be necessary, since only one of the two items can be undefined (never both) because the first `if` guarantees that at least one of them is defined.

**Comment by RyanCavanaugh** [comment]
The design of variable narrowing isn't capable of doing Sudoku-style analysis that would be required to treat this correctly

**Comment by garyo** [comment]
ok

**Comment by DanielRosenwasser** [comment]
Just to clarify a little bit, we don't really have the logic in place of determining that given a set of checks combine to imply mutual exclusion.
