### ISSUE TITLE
Ignore ts(2315): permit empty generic brackets in reference to non-generic

### ISSUE THREAD

**Issue by JonathanWilbur** [microsoft/TypeScript#38606]
## Search Terms

- "ts(2315)"
- "empty generic"

## Suggestion

Currently, TypeScript emits an error if a symbol followed by empty arrow brackets refers to a non-generic assignment. The exact text of this message reads "Type '?' is not generic," where "?" is the symbol. In my particular case, I have `AlgorithmIdentifier<>` referring to:

```typescript
class AlgorithmIdentifier<> {
    // ...
}
```

... which is not generic.

The problem in my case is that this code was generated automatically--not by a human. Though I can modify my program to avoid emitting those empty brackets in the first place, I think they should be tolerated by TypeScript.

That pretext being out of the way, here is my suggestion: **if a symbol is followed by empty arrow brackets, it should not be tolerated as a generic or non-generic, wherever needed.** Those empty arrow brackets never hurt anybody!

## Use Cases

This would be useful for code generation. Code generators could carelessly emit empty angle brackets, and only worry about how to populate the generic type parameters--not _how many_ there are.

## Examples

Here is a currently failing example:

```typescript
class AlgorithmIdentifier<> {
    // ...
}

AlgorithmIdentifier<> // Fails here: "Type 'AlgorithmIdentifier' is not generic. ts(2315)"
```

I would like this error to be ignored, because the inclusion of those empty brackets has no significance.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
I think we'd rather leave this syntax alone in case we want to do something else with it later, rather than just declare it to be meaningless. There are a ton of grammar positions where 0 arguments need the surrounding production removed entirely.
