### ISSUE TITLE
symbol type not match

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#38617]
**TypeScript Version:**  4.0.0-dev.20200514

**Search Terms:**

**Code**

```ts
const symbolName = '@ipld/js-cid/CID';
export const SymbolCID = Symbol.for(symbolName);

export function getSymbolCID()
{
	const symbolName = '@ipld/js-cid/CID';
	return Symbol.for(symbolName)
}
```

**Expected behavior:**

`SymbolCID` and return type of `getSymbolCID` is same type

all `unique symbol` or all `symbol`

**Actual behavior:**

```ts
export declare const SymbolCID: unique symbol;
export declare function getSymbolCID(): symbol;
```

**Playground Link:** 

https://www.typescriptlang.org/play?#code/MYewdgzgLgBBCeBbARiANgOQIaIKYwF4YByAAQEsAHNAEwHoArCAWmHPoGEBJAEWIG4AULgAelEACdYoSLADKSVGm49CMBSnQA6AGaSAFAk2YcuAJRDhYybB0BXMMCjlwMAOa4oGpSv1nBAN6CAJAy0HCK6Nh4amRUtIwsbJy8AiESnnYSYOqRaLoGRkrR5oIAvoJAA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
We don't track symbols this way
