### ISSUE TITLE
Why is a for-loop used here?

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#3861]
At <https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L272-279>?

Could it be replaced by
```ts
            if (children.length === 0) { return undefined; }

            let child = children[children.length - 1];

            if (child.kind < SyntaxKind.FirstNode) {
                return child;
            }

            return child.getLastToken(sourceFile);
```
with a similar modification for `getFirstToken()` above?

**Comment by DanielRosenwasser** [comment]
I say make the change, but use `lastOrUndefined` for `child`.

**Comment by DanielRosenwasser** [comment]
Also fix `getFirstToken`

**Comment by DanielRosenwasser** [comment]
Also curlies on the next line :smiley:

**Comment by mhegazy** [comment]
+1

**Comment by mariusschulz** [comment]
For future reference, here's the mentioned `for` loop:

https://github.com/Microsoft/TypeScript/blob/32bec3b3e7ba55600da7b3f065251b02388089dd/src/services/services.ts#L275-L282

@aozgaa If you want to link to a specific line (or a range of lines), you can get a permalink to the blob by pressing <kbd>y</kbd> while you're looking at the file on GitHub. That way, changes to the file don't mix up your referenced lines — as is already the case now ;).

**Comment by DanielRosenwasser** [comment]
@mariusschulz thanks for the tip! That's going to save me quite a bit of frustration in the future.

**Comment by mariusschulz** [comment]
@DanielRosenwasser You're welcome. Did you also know that you can (manually) append `?w=1` to any URL pointing to a commit diff to ignore whitespace-only line changes? Another one of those handy GitHub secrets. ;)
