### ISSUE TITLE
Functions with overloads don't automatically get types for their parameters

### ISSUE THREAD

**Issue by fregante** [microsoft/TypeScript#38625]
**TypeScript Version:**  3.9.2

**Search Terms:**

noImplicitAny true
overloaded
inferred types

**Code**

I don't know the exact terms for what's happening in the first example. Are these parameters' "types being inferred"?

```ts
// `text` has type `string`
window.alert = (text) => {
	return window.alert(text);
}

// Both parameters are `any`, because `addEventListener` has overloads
window.addEventListener = (type, fn) => {
	return window.addEventListener(type, fn);
}
```

**Expected behavior:**
They should follow these types from `lib.dom.d.ts`:

```ts
addEventListener<K extends keyof WindowEventMap>(type: K, listener: (this: Window, ev: WindowEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
```

**Actual behavior:**
```
Parameter 'type' implicitly has an 'any' type. ts(7006)
Parameter 'fn' implicitly has an 'any' type. ts(7006)
```

**Playground Link:** https://www.typescriptlang.org/play/#src=window.alert%20%3D%20(text)%20%3D%3E%20%7B%0D%0A%09return%20window.alert(text)%3B%0D%0A%7D%0D%0A%0D%0Awindow.addEventListener%20%3D%20(type%2C%20fn)%20%3D%3E%20%7B%0D%0A%09return%20window.addEventListener(type%2C%20fn)%3B%0D%0A%7D

**Comment by RyanCavanaugh** [comment]
For overload sets with "terminal" signatures that encompass all of the preceding ones, this is sufficient, but for other overload sets where there are "disjoint" signatures (e.g. `number => string` + `string => number`) this process doesn't produce correct results.
