### ISSUE TITLE
Possible to implement overloaded call signature with an arrow function?

### ISSUE THREAD

**Issue by bcherny** [microsoft/TypeScript#38622]
**TypeScript Version:**  4.0.0-dev

**Search Terms:** Function overload, signature, declaration

**Code**

```ts
type CreateElement = {
  (tag: 'a'): HTMLAnchorElement
  (tag: string): HTMLElement
}

/*
  Error TS2322:
    Type '(tag: string) => HTMLAnchorElement | HTMLDivElement' is not assignable to type 'CreateElement'.
      Type 'HTMLAnchorElement | HTMLDivElement' is not assignable to type 'HTMLAnchorElement'.
*/
const createElement: CreateElement = (tag: string) => {
  if (tag === 'a') {
    return document.createElement('a')
  }
  return document.createElement('div')
}
```

TS infers `createElement`'s signature as `(tag: string) => HTMLAnchorElement | HTMLDivElement`, which is not assignable to `CreateElement`. Could there be a way to treat this case similarly to how TS treats `function`-based overloads, so instead of checking that the right-hand-side of the assignment is compatible with the left-hand type (`CreateElement`), TS instead checks that each case of the overload (in `CreateElement`) is assignable to the right-hand-side? Or if this is too radical of a departure from TS's assignability checking, could there be another way to make this work?

**Expected behavior:** TS should treat `function` and function expression overloads the same. This code should work, the same way that the following code works:

```ts
function createElement(tag: 'a'): HTMLAnchorElement
function createElement(tag: string): HTMLElement {
   return document.createElement(tag)
}
```

**Actual behavior:** TypeError

[Playground Link](https://www.typescriptlang.org/play?preserveConstEnums=true&ts=4.0.0-dev.20200516#code/C4TwDgpgBAwgThAhsCBRANhAthAdsKAXigG8AoKKACmEQHMAuKAckWYEomAJAFQFkAMgEFcAYwAWAezgZseYBWq1GUAM7A4AS1x1OUXoNk58ZAL5kyAegBUi1HDjSoPAMoAmAMxu3DRZR7g0Mw09EzqWjrsRAB8+vzCYlIymMYEAD5xggAimgBuRvLMUJqqULiSBIiqqpp0uIgARphQwJItgSzwSCgF+MwAdH6Uzh3MBgkS0r3pmQI5+SmFxaXlldW19U3Qre2QLOMik8lyfYPWlmSikrjqUKIIyGiL+Exdj9NESqFqGtq6MaRFJoAGZfOhEQjEVgcQHDKAIYAAVzguCgABNJKJEal+vduk8TsAqND2IpzJQEcjURisTi8e9nkTmGi8hwzGQgA)

**Related Issues:**

- https://github.com/microsoft/TypeScript/issues/37704
- https://github.com/microsoft/TypeScript/issues/37394
- https://github.com/microsoft/TypeScript/issues/34319

**Comment by RyanCavanaugh** [comment]
The posted "equivalent" has only one overload; it is not at all equivalent 😐

The only way to detect that this is a valid assignment is to read the function body and understand that it behaves correctly in each overload case; it is far beyond TS's capabilities to do this.

**Comment by PetrosPetoyan1997** [comment]
Sorry, but this code does not work too

`
function createElement(tag: 'a'): HTMLAnchorElement
function createElement(tag: string): HTMLElement {
   return document.createElement(tag)
}
`
