### ISSUE TITLE
Inconsistent object declaration for comma and semi-colon? 

### ISSUE THREAD

**Issue by thian4** [microsoft/TypeScript#38621]
I found a strange thing with object type declaration. I expect the p2 is the correct one, but it worked with a , or even I omit the semi-colon, it's still fine. Why is it so inconsistent?
```
let p: {
    x: number,
    y: string
} = {
    x: 1,
    y: "abc",
}

let p2: {
    x: number;
    y: string
} = {
    x: 1,
    y: "abc",
}

let p3: {
    x: number
    y: string
} = {
    x: 1,
    y: "abc",
}
```
https://www.typescriptlang.org/play?#code/DYUwLgBADgXBDeAoCKIA84DsCuBbARiAE4A0yqAnnAM5hECWmA5ogL4QC8C5KGEAjGVQQqEAEQBDfAGMxZVokWhIUAExwkwvjgLEA3DxE06jFuy6bUfQYdGSZctosTLoAZg2HteQkVvGGZjZObi04G2E7KVl5RSA

**Expected behavior:**
Throw error when use ```,```
**Actual behavior:**
Everything is fine

**Comment by RyanCavanaugh** [comment]
Type members can be separated by comma or semicolon, and like in other JavaScript, the separator is optional if a newline is sufficient to disambiguate.
