### ISSUE TITLE
Conditional variable type signature does not retain inside functions when filtering using if condition

### ISSUE THREAD

**Issue by zemse** [microsoft/TypeScript#38636]
**TypeScript Version:**  3.9.2

**Search Terms:** conditional type filtering

**Code**

```ts
interface Person {
  id: number | null;
}

function validate(request: Person): void {
  const pid1 = request.id; // const pid1: number | null
  if (request.id) {
    const pid2 = request.id; // const pid2: number
    [1, 2].forEach((n) => {
      const pid3 = request.id; // const pid3: number | null
    });
  }
}
```

**Expected behavior:**
`pid3` should have signature `number`.

**Actual behavior:**
For `pid2`, the signature gets filtered out intelligently to `number`. But in case of `pid3`, inside the same if condition but inside a function too, the signature doesn't get filtered and reflects the base signature as it is.

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/36436, search terms narrowing reset function

**Comment by zemse** [comment]
Thanks for the pointer, I have subscribed to that issue. Closing this one.
