### ISSUE TITLE
TS build output not invalidated when node_modules changed

### ISSUE THREAD

**Issue by brieb** [microsoft/TypeScript#38648]
Changes to types within node_modules do not invalidate the TypeScript build output.

Suppose we have a project with project references enabled and that there are no TypeScript errors in the project. If we update our node_modules to a new version of a package that contains types, that could introduce errors into our project. However, if we leave the build output directory in place, we do not see these errors in the `tsc -b` output.

1. `tsc -b` -- no errors.
2. Update types within node_modules that should trigger error.
3. `tsc -b` -- no errors, which is unexpected.

Upon inspection of the tsbuildinfo files, the shas for the node_modules d.ts files do not get updated.

We cache our TS output directory between CI builds so that we can incrementally build from it on subsequent builds. We currently invalidate our cache whenever node_modules changes. Ideally, we could keep the cache and TypeScript could figure out what needs to be recompiled.

Separately, it would be great if the validity rules for the TypeScript output were documented as part of the [project references docs](https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript). That would help us better understand when it is safe to rebuild from an existing output vs requiring a clean build (between TS versions, when node_modules change, etc).

Thank you! 😃  

**TypeScript Version:**  4.0.0-dev.20200518

**Search Terms:**
project references, build, incremental, node_modules, invalidate, tsb, `tsc -b`, rebuild, `@types`

**Code**

https://github.com/brieb/ts-issue--tsb-nodemodules

**Expected behavior:**

TS errors reported when types within node_modules change.

**Actual behavior:**

No TS errors reported.

Errors only reported after editing code within project triggers invalidation.

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/25600

**Comment by RyanCavanaugh** [comment]
During an incremental rebuild, declaration files that aren't immediately included in the compilation process (i.e. those in `node_modules`, unless you specifically included them) aren't checked for up-to-dateness because figuring out which of those files are in the program in the first place is a major performance burden.

A few options:
 * Run `-tsc -b -f` to force a rebuild when you know these files have changed
 * Modify your `include` or `files` list to include `node_modules/**/*.d.ts` (warning: This *will* slow down all your incremental builds)

**Comment by brieb** [comment]
Got it. So sounds like ignoring the previous output directory (either by not restoring it or `tsc -b -f`) is the best we can do in this case. Wouldn't want to slow down all incremental builds.

What are the other output/cache invalidation conditions when we should use `-f`? 

So far it sounds like:
- When node_modules change

Anything else?

Would have maybe thought "When TypeScript version changes" but looks like the output tsbuildinfo files contain the version number.

**Comment by RyanCavanaugh** [comment]
I think that's it, unless you have other places where `.d.ts` files might get read in from outside of `node_modules` (this is unlikely in my estimation, but it's possible).
