### ISSUE TITLE
 Type 'string[]' is missing the following properties from type '[string, string]': 0, 1

### ISSUE THREAD

**Issue by eng-dibo** [microsoft/TypeScript#38652]
```
type A = [string, string]
type B = string[]

const a = ["a", "b"]

function test(a: A) { }  
function test2(a: B) { } 


//works
test([a[0],a[1]])

//error ; even if 'a' is [string, string]
test(a)

//works
test2(a)
```

error:
 `Type 'string[]' is missing the following properties from type '[string, string]': 0, 1`

view on [Typescript playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=19&pc=1#code/C4TwDgpgBAglC8UDaBnYAnAlgOwOYBoo0s8BdAKFEigCEEiMdckLyBjAe2zSgEN6kAIl6DCggEaDWAMwCu2NsExcowCGgAUvAFywAlFADeUAL5Qo5OQqUq1aAExbdNA8bPkPAek8B3DugBrFEp1YA0kXiQABlJ8SIBGUlI9L08IdHR-Czsw3hTybz9A4JzHPI8gA)

**Comment by jcalz** [comment]
The type of `a` is `string[]`, not `[string, string]`.  #3369

If you want `a` to be `[string, string]` you need to annotate it as such: `const a: [string, string] = ["a", "b"]`.  Or use something like [`const` assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) (which makes the tuple readonly as well, which you might not want here), etc.
