### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by mvolkmann** [Microsoft/TypeScript#3867]
I don't see ES6 Promises on the Roadmap page. Shouldn't it be there somewhere? I realize I can use the es6-promise library for now, but I think support for Promises should be built into TypeScript at some point. Maybe it belongs in 1.6.

**Comment by RichiCoder1** [comment]
Promises as an implementation are presumed to either be pollyfilled or provided natively by TypeScript. See https://github.com/Microsoft/TypeScript/issues/1664

**Comment by danquirk** [comment]
As mentioned, the expectation is that wherever you run your TypeScript has Promises implemented (natively or in a polyfill). We don't ship a standard library with this kind of thing since it's not really adding any value over the implementations that everyone already has access to.

**Comment by mvolkmann** [comment]
Ah, thanks for explaining that! Is there a list somewhere of the ES6 features that require polyfills? Another example is the new methods in the String class like startsWith. It would be great to have a list of recommended polyfills. I see that #1664 provides that for promises.

**Comment by danquirk** [comment]
https://www.npmjs.com/package/core-js is a big one, it's used as a measure of ES6 compatibility here https://kangax.github.io/compat-table/es6/

**Comment by mvolkmann** [comment]
Thanks Dan! It seems that I needed to add a reference to lib.es6.d.ts, but I didn't need to add a script tag for core-js. I'm curious how it is able to work without that.

**Comment by RichiCoder1** [comment]
It'll compile, and some browsers already have native promise support.
