### ISSUE TITLE
Circularity error in intersection of object with index signature

### ISSUE THREAD

**Issue by ahejlsberg** [microsoft/TypeScript#38672]
**TypeScript Version:**  4.0.0-dev

**Code**

```ts
type Foo1 = { x: string } & { [x: number]: Foo1 };    // Circularity error
type Foo2 = { x: string } & { [K in number]: Foo2 };  // No error
```

**Expected behavior:**

No errors.

**Actual behavior:**

Error: Type alias 'Foo1' circularly references itself.

**Playground Link:**

https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=3&pc=1#code/C4TwDgpgBAYg9nAjFAvFA3lAHgLigZ2ACcBLAOwHMoBfKAMgygG1coyBXAWwCMIiBdPPCQ0A3FAlQA9FKgBhEkQDG7ADYBDUqCh8icIgChQkWAgBMqRq0KlKNeoyYBpKOTZdeAoebESZUADk4HSI9QyA

**Comment by ahejlsberg** [comment]
Noticed this as I was writing some code. Issue is we check for empty object types in intersections, which currently causes resolution of object type members, which in turn causes unexpected circularities when the types index signatures. We need to revise the empty object type check to not require member resolution (which really isn't necessary).

**Comment by DanielRosenwasser** [comment]
@bterlson I think you ran into some weird code like this. Check out the packed playground when it's ready over at https://github.com/microsoft/TypeScript/pull/38673#issuecomment-631258931

**Comment by DanielRosenwasser** [comment]
Glad this was a bug, others on the team were telling me this behavior was expected which made no sense because...well, it was a big feature in 3.7!
