### ISSUE TITLE
[Infrastructure]: The latest build 4.0.0-dev.20200520 breaks @typescript-eslint/parser

### ISSUE THREAD

**Issue by a-tarasyuk** [microsoft/TypeScript#38682]
```ts
Linting: node_modules/eslint/bin/eslint --cache --cache-location scripts/.eslintcache --format autolinkable-stylish --rulesdir scripts/eslint/built/rules --ext .ts scripts
> /.nvm/versions/node/v12.16.1/bin/node node_modules/eslint/bin/eslint --cache --cache-location scripts/.eslintcache --format autolinkable-stylish --rulesdir scripts/eslint/built/rules --ext .ts scripts
/TypeScript/scripts/eslint/rules/only-arrow-functions.ts
Error: /TypeScript/scripts/eslint/rules/only-arrow-functions.ts  Parsing error: Cannot read property 'map' of undefined
```

[Example 1](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=74432&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=d4dc47fd-fd59-5101-b9ac-5d3dea126cfb&l=195)

[Example 2](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=74429&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=d4dc47fd-fd59-5101-b9ac-5d3dea126cfb&l=195)

It seems this issue related to some of the changes in public API. In this repo, `@typescript-eslint` uses the latest version of typescript. However, the `next` version has changes that have not supported by `@typescript-eslint` yet.
https://github.com/microsoft/TypeScript/blob/5f597e69b2e3b48d788cb548df40bcb703c8adb1/package.json#L99

Can we use the stable version of the TypeScipt in dependencies?

cc @DanielRosenwasser @RyanCavanaugh @weswigham @sandersn @orta

**Comment by weswigham** [comment]
We should probably fix the version, at least till we update eslint to handle labeled tuple elements.
