### ISSUE TITLE
TypeScript validation result doesn't match `tsc` result when compilerOptions / target is ES6

### ISSUE THREAD

**Issue by tomdai** [microsoft/TypeScript#38697]
- VSCode Version: 1.44.2
- OS Version: Darwin x64 19.4.0
- More info:
  ```
  Version: 1.44.2
  Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
  Date: 2020-04-16T17:07:18.473Z (1 wk ago)
  Electron: 7.1.11
  Chrome: 78.0.3904.130
  Node.js: 12.8.1
  V8: 7.8.279.23-electron.0
  OS: Darwin x64 19.4.0
  ```

Steps to Reproduce:

1. Make sure `typescript` is installed globally by running `npm list -g` and seeing `typescript` listed in the result
2. Create a new Node project by running `npm init` with all default configs as the following
  ```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
  ```
3. Link `typescript` from within the Node project by running `npm link typescript` in the `test` project directory
4. Install the node definition file by running `npm install @types/node` in the `test` project directory
4. Create a file named `test.ts` and write `import * as ts from "typescript";` to it.
  Now the structure of the project is as the following:
  ```
node_modules
node_modules/typescript
package.json
test.ts
  ```
5. VS Code's PROBLEMS tab shows no problem
6. Create a file named `tsconfig.json` and write the following to it:
  ```
{
	"compilerOptions": {
		"target": "ES6"
	}
}
  ```
  and now the structure of the project is as the following:
  ```
node_modules
node_modules/typescript
package.json
test.ts
tsconfig.json
  ```
7. VS Code's PROBLEMS tab shows `Cannot find module 'typescript'. ts(2307)` for the file `test.ts`, but compiling the file to JavaScript with `tsc test.ts` has no problem

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I believe the fix is to specify `"moduleResolution": "node"`. 

```json
{
    "compilerOptions": {
        "moduleResolution": "node",
        "target": "ES6"
    }
  }
```

With `"target": "ES6"`, Typescript will using classic module resolution instead: https://www.typescriptlang.org/docs/handbook/module-resolution.html
