### ISSUE TITLE
why get this bug

### ISSUE THREAD

**Issue by DemonCloud** [microsoft/TypeScript#38702]
<img width="474" alt="CleanShot 2020-05-21 at 10 41 47@2x" src="https://user-images.githubusercontent.com/7436361/82517530-e4b4d780-9b4f-11ea-96a4-8e8213e15d28.png">

**Comment by Ryuurock** [comment]
Because your `searchParams` has no initial value

**Comment by DanielRosenwasser** [comment]
We need a minimal repro with the requested issue template filled out.
