### ISSUE TITLE
How to transform types with TypeScript transformers?

### ISSUE THREAD

**Issue by pirix-gh** [microsoft/TypeScript#38707]
Hey @sandersn @andrewbranch I would be very grateful if you could take a bit of your time to tell me if the compiler API could allow to alter `d.ts` generation?

If it's possible, could you point where I should start looking in the `typescript.d.ts`?

https://stackoverflow.com/questions/61924488/how-to-transform-types-with-typescript-transformers

Thanks :hand:

**Comment by DanielRosenwasser** [comment]
I think you're interested in `afterDeclarations` transformers

https://github.com/microsoft/TypeScript/blob/5f597e69b2e3b48d788cb548df40bcb703c8adb1/src/compiler/types.ts#L3334
