### ISSUE TITLE
window.removeEventListener needs specialized signatures like addEventListener

### ISSUE THREAD

**Issue by lilred** [Microsoft/TypeScript#3871]
The definition for `addEventListener` is on point. The definition for `removeEventListener` should essentially copy it.

**Comment by danquirk** [comment]
Which version of lib.d.ts are you looking at? They appear the same in the latest bits?
```ts
interface EventTarget {
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;
    dispatchEvent(evt: Event): boolean;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;
}

declare function addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;
declare function dispatchEvent(evt: Event): boolean;
declare function removeEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;

```

**Comment by lilred** [comment]
Version isn't clear, but there's this bit:

    addEventListener(type: "MSGestureChange", listener: (ev: MSGestureEvent) => any, useCapture?: boolean): void;
    addEventListener(type: "MSGestureDoubleTap", listener: (ev: MSGestureEvent) => any, useCapture?: boolean): void;
    addEventListener(type: "MSGestureEnd", listener: (ev: MSGestureEvent) => any, useCapture?: boolean): void;
    ...
    addEventListener(type: "waiting", listener: (ev: Event) => any, useCapture?: boolean): void;
    addEventListener(type: "wheel", listener: (ev: WheelEvent) => any, useCapture?: boolean): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;

**Comment by danquirk** [comment]
Ah, I see, you mean you want all those specialized signatures for removeEventListener.

**Comment by mhegazy** [comment]
The reason addEventListener has these overloads is to allow for flowing contextual type to the event handler. but in the remove case, why would pass a lambda? @lilred can you share a sample where this is useful in removeEventListener

**Comment by lilred** [comment]
[You call removeEventListener with a reference to the lambda you called
addEventListener with.](
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener
)

    function foo(bar: StorageEvent) { console.log("foo!") };
    window.addEventListener("storage", foo); //event handler is registered
    window.removeEventListener("storage", foo); //back to normal

**Comment by lilred** [comment]
[You call removeEventListener with a reference to the lambda you called
addEventListener with.](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener)

    function foo(bar: StorageEvent) { console.log("foo!") };
    window.addEventListener("storage", foo); //event handler is registered
    window.removeEventListener("storage", foo); //back to normal

**Comment by mhegazy** [comment]
:) i understand. i was talking about the contextual type. contextual types are what allows you to get type of a lambda paramter e.g.:

```ts
window.addEventListener("storage", (e) => {
    e; // <- e is StorageEvent becuase contextual type flowed from the definition of window.addEventListener("storage", ...);
})
```

so it seems the scenario you are talking about is:
```ts
function foo(bar: StorageEvent) { console.log("foo!") };

window.removeEventListener("click", foo); // Error MouseEventListener is not assignable to StorageEventListener
```
is this correct? if so there is a different problem that would make this not work, once #1003 is fixed we can revisit this.

**Comment by mhegazy** [comment]
as mentioned earlier in my reply, this does not seem to be of much value as the event is usually defined in the `addEventListener` method. please reopen if this is not the case.

**Comment by MaxDaten** [comment]
Hi,

I'm using typescript with ionic 1.0 & cordova and bumping against this error:

```
TypeScript error: typings/globals/InAppBrowser/index.d.ts(46,11): Error TS2430: Interface 'InAppBrowser' incorrectly extends interface 'Window'.
  Types of property 'addEventListener' are incompatible.
    Type '{ (type: "loadstart", callback: (event: InAppBrowserEvent) => void): void; (type: "loadstop", cal...' is not assignable to type '{ (type: "MSGestureChange", listener: (this: this, ev: MSGestureEvent) => any, useCapture?: boole...'.
      Types of parameters 'type' and 'type' are incompatible.
        Type '"MSGestureChange"' is not assignable to type '"loadstart"'.
```

with:

```
$ tsc --version
Version 2.0.6
```

What is the problem here and how to solve it? Thanks for any advice.

**Comment by mhegazy** [comment]
looks like `InAppBrowser` does not include all overloads for `addEventListener` which makes the class/interface not implement the `Window` interface correctly. the fix would be done on the declaration file i would say.

//cc @mbraude
