### ISSUE TITLE
"Move to new file" edits `files` in `tsconfig.json`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#38714]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

`tsconfig.json`:
```jsonc
{
    "files": ["src/main.ts"]
}
```

`src/main.ts`:
```typescript
import { foo } from './foo';

const bar = 1;

console.log(foo, bar);
```

`src/foo.ts`:
```typescript
export const foo = 1;
```

1. In `src/main.ts`, select the line `const bar = 1;`
1. Run the "move to new file" command

**Expected behavior:**

1. The code is moved to a new file and imported in `src/main.ts`
1. `tsconfig.json` _should not_ be edited

**Actual behavior:**

1. The code is moved to a new file and imported in `src/main.ts`:
   ```typescript
   import { foo } from './foo';
   import { bar } from './bar';
   
   console.log(foo, bar);
   ```
1. The new file is added to `files` in `tsconfig.json`:
   ```jsonc
   {
       "files": ["src/main.ts", "./src/bar.ts"]
   }
   ```

**Playground Link:** 

**Related Issues:** https://github.com/microsoft/TypeScript/issues/24857#issuecomment-453816287

**Comment by RyanCavanaugh** [comment]
This is considered desirable behavior because if you have `composite` on, listing all the files is mandatory if you're using a `files` array
