### ISSUE TITLE
Method implicitly has return type of any despite explicit cast of returned value

### ISSUE THREAD

**Issue by devuxer** [microsoft/TypeScript#38724]
**TypeScript Version:**  3.9.2 (also checked with nightly)

**Search Terms:**

- `is:issue is:open in:title implicitly`
- `is:issue is:open in:title cast any`

**Code**

```ts
class Nation {
    public readonly id = "";
    public readonly name = "";

    public static fromPayload(payload: any) {
        const nation = new Nation();
        return Object.assign(nation, payload) as Nation;
    }

    public clone() {
        const nation = new Nation();
        return Object.assign(nation, this) as Nation; // <-- cast to Nation
    }
}
```

**Expected behavior:**

No error

**Actual behavior:**

> (method) Nation.clone(): Nation
> 'clone' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.(7023)

**Playground Link:** 

[Click me](https://www.typescriptlang.org/play/?ts=Nightly#code/MYGwhgzhAEByYBcCWB7AdtA3gKGn6ADgK4BGISw0ATgKZgAm6IAntEvdALzQBEPA3LnzEyFanUZoW0NGAC2NLrwHYheEeUoQEiMQDMqKOQAUwzECgYAKAmYsMAXNDBpmASixr8eYOm0zddCU0GgB3OEC0KzdBb29aBCIqDAB5EgArGmAEADpICCQAcyjZZHQAGkI7S3oPSAiytFj8AF9Vbw0xUHQaaM84-F80f1LUDG4Q8PhG6OaBhKTUjKzc-KKSyMqEAAskCDqYabG56DaWoA)

**Discussion:**

It's particularly perplexing that the error literally starts out with `Nation.clone(): Nation`. Doesn't the word `Nation` after the `:` mean the compiler thinks it has an explicit type?

Also, this was not an error as of the version currently installed in VSCode (TypeScript 3.7.2).

Finally, this code does *not* generate the same error:

```ts
public clone() {
    const nation = new Nation();
    const result = (Object.assign(nation, this) as Nation);
    return result;
}
```

**Related Issues:** 

#35546 seems similar but it has so much indirection, I can't tell if it's the same problem. The example here is a more clear case of a direct cast of the return value not being accounted for in determining the type of the method.

**Comment by RyanCavanaugh** [comment]
This is still a circularity; to determine if the type assertion from `Object.assign(nation, this)` to `Nation` is valid, TS has to determine the type of `this`, which depends on the return type of `clone`.

**Comment by devuxer** [comment]
@RyanCavanaugh ,

Ohh! So, if I do this...

```ts
    public clone() {
        const nation = new Nation();
        return Object.assign(nation, this as Nation);
    }
```

...the error goes away.

Nevertheless, the specific reason for the circularity is not at all clear from the error message. Is there any way it could be improved to be more concrete/specific about what exactly cannot be resolved? 

Also, is this scenario mentioned in the "breaking changes" section of the release announcement? I just did a quick review and didn't see it, but it could just be that it was mentioned, and I just don't know the terminology well enough.
