### ISSUE TITLE
lib.es6.d.ts error in ArrayConstructor interface

### ISSUE THREAD

**Issue by mvolkmann** [Microsoft/TypeScript#3873]
This interface contains:
isArray(arg: any): arg is Array<any>;
but I think it should be:
isArray(arg: any): boolean;

It doesn't compile as it is.

**Comment by RyanCavanaugh** [comment]
It sounds like you're pulling down lib.es6.d.ts from source while trying to compile with a released compiler version.

The checked-in copy of that file can only be built by a sufficiently up-to-date compiler from `master`. The new feature (functions that return `arg is type`) is called "type predicates".

**Comment by mvolkmann** [comment]
You are correct that I pulled down TypeScript from source. I built that and am using bin/tsc to compile. I see lib.es6.d.ts in both the bin and build/local directories. They are identical and use type predicates as you pointed out. I'm not sure why I can't compile it with this version of tsc.

**Comment by danquirk** [comment]
```tsc -v``` should verify whether you're actually running the version you think you're running and not getting bitten by unexpected PATH things or something.

**Comment by mvolkmann** [comment]
tsc -v gives me "Version 1.5.0-beta"

**Comment by mvolkmann** [comment]
The errors I get are:
lib.es6.d.ts(1168,28): error TS1005: ';' expected.
lib.es6.d.ts(1168,31): error TS1005: ';' expected.
lib.es6.d.ts(1168,41): error TS1005: '(' expected.
lib.es6.d.ts(1170,26): error TS1005: '(' expected.
lib.es6.d.ts(1171,1): error TS1128: Declaration or statement expected.

**Comment by RyanCavanaugh** [comment]
That is not the correct version for tsc built from `master`. You should be seeing "Version 1.5.3".

As of right now on commit 32a040b48765d3:

 > C:\github\TypeScript-master>git hash-object built\local\tsc.js

 > 3901b042ed4b4684de3e21f8b1f1f5ab6271aa54

**Comment by mvolkmann** [comment]
So sorry for the noise. Ryan, you were correct. I had previously installed TypeScript with npm and was using that version of tsc instead of the one from my git clone. I uninstalled the npm version and all is good now. Thanks!
