### ISSUE TITLE
Cannot be used to index type in 3.9 (worked in 3.8)

### ISSUE THREAD

**Issue by jasonkuhrt** [microsoft/TypeScript#38740]
**TypeScript Version:**  3.9.3

**Search Terms:**

cannot be used to index type

**Code**

2536

```ts
// A *self-contained* demonstration of the problem follows...
```
```ts
// works in 3.8, fails in 3.9
// Is this a bug in 3.9?
// Nexus (nexusjs.org) depended on this functionality

type Get1<
  A extends any,
  B extends any,
  C extends 'filtering' | 'ordering'
> = A extends keyof Stuff
  ? B extends keyof Stuff[A]
    ? Stuff[A][B][C] // error here
    : never
  : never;

interface Stuff {
  // [k:string]: any               // <-- Putting this here fixes Get1 in TS 3.9
  Blog: {
    // [k:string]: any               // <-- Putting this here fixes Get1 in TS 3.9      
    posts: {      
      filtering: 'a',
      ordering: 'b'
    }
  }
}
```

**Expected behavior:**

TS 3.9 supports the same type logic as in 3.8 (see playground repro)

**Actual behavior:**

Breaks in 3.9 (our context: https://github.com/graphql-nexus/nexus/pull/859)

**Playground Link:** 

[link](https://www.typescriptlang.org/play/index.html#code/PTAEHcHsCcGsGdQEsB2oDMA6AHAGlAGYCGSANoqhpgJwBQIoAkogC4AWSiRoARgK4BzZGizUA-PTAA5AKYAPPogAUKeYoBW8TDAEBKUABMZABxkojB0JDTtOhPigDGLJNaKkkLAJ61a306AA4jIsAIwAPLSgoACCoPIsZgZcKF64UaAAQvFyieYpaRkAwjl5yaAA5ARkidCoAhWgAD6VMEZ1KA20AHygALyxpUmIsDJekASgAMosfAQEGWJZQ-mgo+OTM3MEANoxALoZ0Utb83v7O5kXRYfR0QBcoKoAbjLQGY8vbwDcvv4yoGgoX6QRCEQqmVIkAauAqxkg8BY8AqsOqpFq9Qq3V8DBiKEg7DeoFsnUkTxkr2gEBgCGAUDgMgMZPAbC8Ej8XgCwRYACZItE4glhpVIdCURlskLVusJtNZmcDuloiUpeUqjU3pjmq1oO1MRlegNTrsDpdrocOQFoDyQdy+RCoTC4QikSj1ejNZ0sTiwHiCWwiSSBPhbIh6Qh8I4ofAZIiIADHJA+KRLAIQsTILwZAQYDIyQARSCxlAVFigIjOPjuUjlxwcCkApNUgSQdzEthJgRsP6cgHc9D8waqxAOsVK5bDtZjWXGnajhr7ccq3LC90Yr3aiptT1daKGuXbc5mnY3HtW9C2kID+du+GI5GojUdBrYyRvhiJOMGIgsIi+VC1MQjgAsaoAAN4ZAwOywPciLPvsjxEKkdwoahdwMOEAC0mGgAACnwLAuJ07Z2AG0AAtUcixqCYTCKAAAqUxUHQ0SigIjwQShUEwXB9QIeWyFoUJoAYdheEEURQihqAZEUUgVGINywKUIxzFoUcoB3kiHHqWhaLruxlREOKaHbs+jwVDwFQaQAvhkdk2UAA)

**Comment by ahejlsberg** [comment]
The immediate cause of this is #29571. Previously, a type parameter declared with `extends any` was treated as just `any`, which effectively turned off type checking. For example, you could change `Stuff[A][B][C]` to `Stuff[A][42]['elephant']` in your example with no error!

We now treat `extends any` the same as having no constraint, meaning that things actually get checked. And, in your example `A` might not include `'Blog'` and `B` might not include `'posts'`, so there is no guarantee that `'filtering' | 'ordering'` is a valid key for `Stuff[A][B]`. You need to include another check to make it work:

```ts
type Get1<
  A extends any,
  B extends any,
  C extends 'filtering' | 'ordering'
> = A extends keyof Stuff
  ? B extends keyof Stuff[A]
    ? C extends keyof Stuff[A][B]
      ? Stuff[A][B][C] // Ok
      : never
    : never
  : never;
```

**Comment by jasonkuhrt** [comment]
Ahh thanks @ahejlsberg I thought I tried that 🤦.

I also mistakenly thought that TS would statically analyze that `Stuff` only had `filtering` and `ordering`. I guess though the only way for that to happen would be having Stuff` come through as a constrained generic.

There's probably an obvious reason TS must/does behave this way, but I don't see it.

Anyways, getting off-topic here.

Thanks again @ahejlsberg!
