### ISSUE TITLE
ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.9.0 but 3.9.3 was found instead

### ISSUE THREAD

**Issue by ErVishalM** [microsoft/TypeScript#38745]
### **Description**
I **just upgraded to Angular/cli 9.1.7 and some other packages also using `ng update`**

Old packags.json
 ```
"dependencies": {
	"@angular/animations": "^9.1.7",
        "@angular/common": "^9.1.7",
        "@angular/compiler": "^9.1.7",
        "@angular/core": "^9.1.7",
        "@angular/forms": "^9.1.7",
        "@angular/platform-browser": "^9.1.7",
        "@angular/platform-browser-dynamic": "^9.1.7",
        "@angular/router": "^9.1.7",
	"moment": "^2.25.3",
    },
    "devDependencies": {
        "@angular/cli": "^9.1.6",
        "@angular/compiler-cli": "^9.1.7",
        "@angular/language-service": "^9.1.7",
        "@types/node": "^12.12.39",
        "karma": "^5.0.8",
        "typescript": "^3.7.5"
    }
```
 
new package.json
```
"dependencies": {
	"@angular/animations": "^9.1.9",
        "@angular/common": "^9.1.9",
        "@angular/compiler": "^9.1.9",
        "@angular/core": "^9.1.9",
        "@angular/forms": "^9.1.9",
        "@angular/platform-browser": "^9.1.9",
        "@angular/platform-browser-dynamic": "^9.1.9",
        "@angular/router": "^9.1.9",
        "moment": "^2.26.0",
    },
    "devDependencies": {
        "@angular/cli": "^9.1.7",
        "@angular/compiler-cli": "^9.1.9",
        "@angular/language-service": "^9.1.9",
        "@types/node": "^12.12.42",
        "karma": "^5.0.9",
        "typescript": "^3.9.3"
    }
```

Now when I run `ng s`, I get an error, 
**ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.9.0 but 3.9.3 was found instead**

Why did Angular update me to Typescript 3.9.3 if it's not supported?
Error SS 
<img width="647" alt="TypescriptError" src="https://user-images.githubusercontent.com/43669644/82731678-3616bf80-9d26-11ea-95dd-bccab299eeee.png">

**Comment by eun-choi** [comment]
umm...
just, angular@9.1 is supported until typescript@3.8.3
and, angular@10 will be supported typescript@3.9

**Comment by ErVishalM** [comment]
@eun-choi Thanks for the info. I have installed the lower version and it solved the problem, well that i wanted to know why it was showing me outdated if it is not supposed to install in angular@9.1.

**Comment by MartinJohns** [comment]
This issue is completely unrelated to TypeScript. Perhaps you should file an issue in the Angular repository. It's the Angular tool that updated your dependencies, and it's the Angular tool that reports the error on the TypeScript version.

**Comment by ErVishalM** [comment]
Hi @MartinJohns  yeah i can do that thanks.

**Comment by wentjun** [comment]
For those who are facing a similar issue, please refer to my answer on [stackoverflow](https://stackoverflow.com/a/57216166/10959940) :)
