### ISSUE TITLE
Function's signature with return type void not throw an error when return any values

### ISSUE THREAD

**Issue by VovaSv** [microsoft/TypeScript#38758]
**TypeScript Version:**  3.8.3

**Search Terms:**
- Function signature with return type void

**Code**
```
let greet: (a: string, b: string) => void;

greet = (name: string, greeting: string) => {
console.log(greeting)
return 1;
}
```

**Expected behavior:**
Error:
Type '(name: string, greeting: string) => number' is not assignable to type
'(a: string, b: string) => void'

**Actual behavior:**
No Errors

**Comment by MartinJohns** [comment]
A return type of `void` does not mean the function returns nothing. It means the functions return type should not be used for anything meaningful.

[Why are functions returning non-`void` assignable to function returning `void`?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

**Comment by VovaSv** [comment]
So why in case below we have an error?
```
let greet: (a: string, b: string) => void;

greet = (name: string, greeting: string): **void** => {
console.log(greeting)
return 1;
}
```

**Comment by ahejlsberg** [comment]
> So why in case below we have an error?

Because you're attempting to return something from a function whose result you've declared is always ignored.

**Comment by VovaSv** [comment]
Maybe an use case which I described above just called TS "substitutability"?
The TS ability to substitute one thing for another, wherever it make sense.
@ahejlsberg @MartinJohns

**Comment by powelski** [comment]
@MartinJohns are you sure about that? Perhaps it's up to debate, but it's not how it works in Swift, for example:

<img width="433" alt="swift" src="https://user-images.githubusercontent.com/2076782/200148545-ec7af014-a904-48ad-9ddc-050dfc0a31f8.png">

I'd expect TypeScript to interpret it as an error too.

**Comment by MartinJohns** [comment]
@powelski Yes, I'm sure. Doesn't matter how it works in other languages, this is how it works in TypeScript. Not every language behaves the same.
