### ISSUE TITLE
Existence of a function changes type of unrelated varaible (in .d.ts)

### ISSUE THREAD

**Issue by kdy1** [microsoft/TypeScript#38757]
**TypeScript Version:**  typescript@3.9.2

**Search Terms:**
 - Existence of function
 - Changes unrelated variable
 - Changes unrelated types

**Code**

Full gist: https://gist.github.com/kdy1/2dbb1efc34e3ae2128dcecd6fb5822da

<details>
    <summary>
        test1.ts
    </summary>

```ts
type PrimitiveName = 'string' | 'number' | 'boolean';

const string: "string" = "string";
const number: "number" = "number";
const boolean: "boolean" = "boolean";

const stringOrBoolean = string || boolean;
const stringOrBooleanOrNumber = stringOrBoolean || number;
```
</details>

<details>
    <summary>
       test1.d.ts
    </summary>

```ts
declare type PrimitiveName = 'string' | 'number' | 'boolean';
declare const string: "string";
declare const number: "number";
declare const boolean: "boolean";
declare const stringOrBoolean: "string" | "boolean";
declare const stringOrBooleanOrNumber: "string" | "number" | "boolean";
```

</details>

<details>
    <summary>
        test2.ts
    </summary>

```ts
type PrimitiveName = 'string' | 'number' | 'boolean';

function getFalsyPrimitive(x: "string"): string;
function getFalsyPrimitive(x: "number"): number;
function getFalsyPrimitive(x: "boolean"): boolean;
function getFalsyPrimitive(x: "boolean" | "string"): boolean | string;
function getFalsyPrimitive(x: "boolean" | "number"): boolean | number;
function getFalsyPrimitive(x: "number" | "string"): number | string;
function getFalsyPrimitive(x: "number" | "string" | "boolean"): number | string | boolean;
function getFalsyPrimitive(x: PrimitiveName): number | string | boolean {
    if (x === "string") {
        return "";
    }
    if (x === "number") {
        return 0;
    }
    if (x === "boolean") {
        return false;
    }

    // Should be unreachable.
    throw "Invalid value";
}

const string: "string" = "string";
const number: "number" = "number";
const boolean: "boolean" = "boolean";

const stringOrNumber = string || number;
const stringOrBoolean = string || boolean;
const booleanOrNumber = number || boolean;
const stringOrBooleanOrNumber = stringOrBoolean || number;
```

</details>
<details>
    <summary>
        test2.d.ts
    </summary>

```ts
declare type PrimitiveName = 'string' | 'number' | 'boolean';
declare function getFalsyPrimitive(x: "string"): string;
declare function getFalsyPrimitive(x: "number"): number;
declare function getFalsyPrimitive(x: "boolean"): boolean;
declare function getFalsyPrimitive(x: "boolean" | "string"): boolean | string;
declare function getFalsyPrimitive(x: "boolean" | "number"): boolean | number;
declare function getFalsyPrimitive(x: "number" | "string"): number | string;
declare function getFalsyPrimitive(x: "number" | "string" | "boolean"): number | string | boolean;
declare const string: "string";
declare const number: "number";
declare const boolean: "boolean";
declare const stringOrNumber: "string" | "number";
declare const stringOrBoolean: "string" | "boolean";
declare const booleanOrNumber: "number" | "boolean";
declare const stringOrBooleanOrNumber: PrimitiveName;
```

</details>

This code is taken from the official test suite. (I'm poring tsc into rust)

**Expected behavior:**

stringOrBooleanOrNumber have the same type, regardless of the existence of a function.

**Actual behavior:**

Existence of function changes the type of variable.

**Playground Link:** 

Note: The playground seems like doing something wrong. Maybe an another issue?

test1: [Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgSwLYOAgbhAcgQydAXigHIBnYRAOwHNioAfEygVyQCMI47Hi2B7PgBsIOSsQDcAKEkBjPpXJRyVagC4oAImUIaGqES0Ud1DVLkLgUFu07qN1jnD0GHnU7PmL+QkZTvfhUWdNAN93DwslIxoAeTgAIQFAyn0olQZGUNEzT0ttWISk3zisVkdU-Oo4xJ9RDKsyznEgA)

test2: [Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgSwLYOAgbhAcgQydAXigHIBnYRAOwHNioAfEygVyQCMI47Hi2B7PgBsIOSsQDcAKEkAzZpQDGaPpSjUIwAGI5BpEPGSoMEABQAPAFxQAROSrVrASit2ENKXMXLV6rTr0GKGiY5lbWLOycTlYRHHAe8koIKmoa2rr6iEHGoTb8QiKU0VD5wqIJXsk+af6ZhsGmlnkCZUUMNq40xaWF7Z3UFUkpvukBWUYhTdY9otbt4axx3S29jLGcg96pfhmBE41h63BzjLYUbg7OUEd95+6yiVsjtXsNuQuRx-P9J80Fs1cbox+u0ZpRNlVtqM6tlJlZXsZcPhAYtOLd7KCVqIoABvSRQAlQBAyKDmKAECkdO6XXH4wn0uAaZhwVTWaxSekAXzpBOJpLM5MpHyWjlp9IZTJZUAADBzCdz6XyyRSiNMsUVRXjxYTGcBmaoZP4IHKCdyeVAAPQWqAAZQAFnxmIIACYlaDyRk4BR2nBsYQAOnNwDtcD4AHcbABJSjoHQIV2xwTMCDsyRmhQqchQfphH7kqn2VMZyhZo6HVFfVVHIuZ4AldVhMFzVVNqSSYtZ-oAeTgWAr+ZB9DWFakHbr3bgACF1QPqQxGGDR7X6-9KD2+5980CF+qlyXx9Se9PV+v+0QJ8fWvPriOgA)

**Related Issues:** N/A

**Comment by RyanCavanaugh** [comment]
The only invariant of .d.ts generation is that it is semantically equivalent, not syntactically equivalent, to its input types. TS is allowed to use internal optimizations to improve speed or output size at its discretion as part of this. When the first time TS encounters* a union type is during the initialization of a type alias, that union type is "tagged" with the alias, and during .d.ts printback, the alias will be used if available.

* "encounters" is implementation-defined and is not guaranteed to be the same order between versions
