### ISSUE TITLE
this should be able to use in static property initializer

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#38756]
**TypeScript Version:**  3.9.3

**Search Terms:**

**Code**

```ts
class C { static default = /*#__PURE__*/Object.freeze(this); }
```

**Expected behavior:**

No error, because `this` in `static` property refer to the class self according to spec.

**Actual behavior:**

```
TS2334: 'this' cannot be referenced in a static property initializer.
```

**Playground Link:**

**Related Issues:**

**Comment by MartinJohns** [comment]
Duplicate of #36267. Search terms: `this static class`

**Comment by LongTengDao** [comment]
Sorry, I only found #6331 by `TS2334`. Thank you.
