### ISSUE TITLE
Narrowed to never when type-guards used with types union

### ISSUE THREAD

**Issue by Hookyns** [microsoft/TypeScript#38753]
**TypeScript Version:**  4.0.0-dev.20200523, same as 3.9.x, 3.8.x

**Search Terms:**
type guard, never, property does not exist on type 'never'

**Expected behavior:**
`expr` is narrowed to C when type guarding function `isC(x): x is C` used.

**Actual behavior:**
`expr` is narrowed to never.

**Related Issues:**

**Code**
```ts
// -- declaration
enum Kind
{
	A = 1,
	B = 2,
	C = 3,
}

interface Node
{
	kind: Kind;
}

interface A extends Node {
	expression: Node
}

interface B extends Node {
	escapedText: string;
}

interface C extends Node {
	expression: C | B | A;
	name: B;
}

function isA(node: Node): node is A
{
	return node.kind == Kind.A;
}

function isB(node: Node): node is B
{
	return node.kind == Kind.B;
}

function isC(node: Node): node is C
{
	return node.kind == Kind.C;
}
// -- end of declaration


function doSomething(expr: A | B | C) // It works OK when 'expr: Node'
{
	if (isA(expr))
	{
	}
	else if (isB(expr))
	{
	}
	else if (isC(expr)) // or when isC(expr) branch is before isB(expr) branch
	{
		return expr.name; // TS2339: Property 'name' does not exist on type 'never'
	}
}
```

<details><summary><b>Output</b></summary>

```ts
var Kind;
(function (Kind) {
    Kind[Kind["A"] = 1] = "A";
    Kind[Kind["B"] = 2] = "B";
    Kind[Kind["C"] = 3] = "C";
})(Kind || (Kind = {}));
function isA(node) {
    return node.kind == Kind.A;
}
function isB(node) {
    return node.kind == Kind.B;
}
function isC(node) {
    return node.kind == Kind.C;
}

function doSomething(expr) {
    if (isA(expr)) {
    }
    else if (isB(expr)) {
    }
    else if (isC(expr)) {
        return expr.name;
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "esnext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=99&jsx=0&module=1&ts=4.0.0-dev.20200523#code/PTAEFp1ATBTBjANgQwE7IC4EsD2A7AKFjwFcBbUAaSz2gIG8CBIAQVAF5QBGAGmYCEOoAEx8mAYSEBmPgF8CBGhlioAZsnixQAORxwGzANY1oALiomA3AXmK8ytRq1tYAD2W0Azjr1bGTNwAHVFhPT1w8c119WyUVdU1QQTcPaG9ov2ZQ+GRA2GgAFRTzTwxUGgBza1j7eKdQSRTiNJ84UH8gkLCI80kAHyTQAZZrJjxkMlhzfmqFVRI8eGx8UCxPFgAKPF8o3wBKc222tdAWAyYQjBJUPFAj2AA6Y1oOTmpaB5GbOYWliNXPPwtjtWrADndfACkudLtdbvcniZXhYPjNvgR5otlrc1uJgXBdnBwfcoeIYbArjcIXBES92G8TA9xLMQBAoM1QDhVDAECh0NiFBjftiYDgAMo4SYYAAWlQ2nXMbAGggG4j25yw3I2a02nT26qY-nkAUQni0mtA2sB8tcwX1zCNWVN5q1uJtdoN-guFLhoE6D3Gk0soFZBTFwikUgAnOYAAqoHB5VAYACeoAA5IHYOnRaEIRg-a41gWVqm8hm8LAAG4qdPMeSyIA)

**Comment by MartinJohns** [comment]
The issue here is that `A` and `C` are structurally compatible. Both types have an `expression` property with the type being `Node` (in the case of `C`it's `C | B | A`, but all these types extend `Node`). This means that when the `expr` is of type `C` it **must** also be the type `A`. Switch this around it means that if the `expr` is **not** type `A` it means that it **can't** be type `C`.

You can see that in the `isB(expr)` statement the `expr` is already narrowed to `B`, instead of `B | C`. In `isC(expr)` it's already narrowed to `never`.

To my understanding **this works as intended**. You can work around this by checking for `C` first, before checking for `A`.

---

An improved design (IMO) would be to create a discriminated union by removing the `Node` interface and move the `kind` property to each specific type and give a literal type.

	interface A { kind: Kind.A; expression: MyNode }
	interface B { kind: Kind.B; escapedText: string }
	interface C { kind: Kind.C; expression: C | B | A; name: B }

	type MyNode = A | B | C

(Note that I had to rename `Node` to `MyNode` to not conflict with the existing `Node` type. In your example it makes use of interface declaration merging.)

**Comment by Hookyns** [comment]
Well, structure is not same, `A` is subset of `C` but okay, I got it, no matter what interface it is, if they match structure, they are equal (semantic). 

But why it works when I call `isA()` as first and `isC()` as second (it is not necessary to call it first as you told), then it is buggy in different way. 

It also works if I change function parameter type from `A | B | C` just to `Node`; `isC()`can be 3rd.

**Comment by RyanCavanaugh** [comment]
@MartinJohns 's explanation is correct. Structurally, anything that's a `C` is also an `A`

**Comment by Hookyns** [comment]
I got @MartinJohns's explanation, I understand what was the intent and I know that my original comment is wrong.

Now, please look at this:
```typescript
function doSomething(expr: A | B | C)
{
	if (isA(expr))
	{
		return expr.expression;
	}
	else if (isC(expr))
	{
		return expr.name;
	}
	else if (isB(expr))
	{
		return expr.escapedText;
	}
}
```
@MartinJohns told that it cannot be `C` when it is `A`, because `A` is structurally compatible (it's subset of `C`).
After `if(isA())` it is narrowed to `B` and `B` became `C` thanks to isC() guard. Is it okay? Intended behavior is different (you both described it). If it works as intended, it can **never** be narrowed to C, but it is.
