### ISSUE TITLE
Make const assertions smarter 🧠

### ISSUE THREAD

**Issue by mamiu** [microsoft/TypeScript#38751]
## Search Terms

- const assertions
- as const
- object.keys
- exact types

## Suggestion

Const assertions are really useful in many different scenarios! However, the types are not always recognized properly when using some standard Javascript operations. Which should be possible for const assertions.

## Use Cases

Everywhere where final Javascript objects are used. For example in config objects or mapping objects.

## Examples

```ts
const counterHoiPolloi = {
  jeffB: {
    vision: "Squeeze the shit out of people!",
    trustScore: 97,
  },
  markZ: {
    vision: "How could I even track their winks?",
    trustScore: 43,
  },
  billG: {
    vision:
      "Viruses are my expertise! First digitally, now biologically and next mentally.",
    trustScore: -32,
  },
  donaldT: {
    vision:
      "I am the best! I didn't tamper my trust score! I invented trust scores!",
    trustScore: 9999,
  },
} as const;

const test1 = Object.values(counterHoiPolloi);
// ✅ smart => const test1: ({ readonly vision: "..."; readonly trustScore: 97; } | { ...; })[]
const test2 = test1[0];
// ✅ smart => const test2: ({ readonly vision: "..."; readonly trustScore: 97; } | { ...; })
const test3 = test2.trustScore;
// ✅ smart => const test2: 97 | 43 | -32 | 9999
type test4 = typeof test2.trustScore;
// ✅ smart => type test3 = 97 | 43 | -32 | 9999
const test5 = Object.keys(counterHoiPolloi);
// ⛔️ not smart => const test5: string[]
// expected result => const test5: "jeffB" | "markZ" | "billG" | "donaldT"
const test6 = test1[5];
// ⛔️ not smart => const test2: ({ readonly vision: "..."; readonly trustScore: 97; } | { ...; })
// expected result => const test6: undefined
const test7 = [97, 43, -32, 9999].includes(test2.trustScore);
// ⛔️ not smart => const test7: boolean
// expected result => const test7: true
const test8 = test1.find(chp => chp.vision === "How could I even track their winks?").trustScore;
// ⛔️ not smart => Error: Object is possibly 'undefined'
// expected result => const test8: 43
const test9 = test1.find(chp => chp.vision === "How could I even track their winks?")?.trustScore;
// ⛔️ not smart => const test9: 97 | 43 | -32 | 9999 | undefined
// expected result => const test9: 43
const test10 = counterHoiPolloi.hasOwnProperty("steveJ");
// ⛔️ not smart => const test10: boolean
// expected result => Uncaught OutOfThisWorldError: "steveJ" no longer dwells among the "counterHoiPolloi".
// real expected result => const test10: false

// and so on...
```

_There are no implications. All example data are purely random._

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is like ten different language change proposals in one, many of which are questionable (do we *really* need to special-case `include` to return compile-time true/false values? Why?), wrong (`Object.keys` should not return `(keyof T)[]`; see StackOverflow or dozens of duplicates), or flatly undesirable (why should `hasOwnProperty` be only legal on things you already know to exist?). Please take these up individually after researching what's already been posted about them.
