### ISSUE TITLE
Type-only imports should not render a file a module

### ISSUE THREAD

**Issue by mihailik** [microsoft/TypeScript#38763]
**TypeScript Version:**  3.9.3,  playground,  playground/nightly

**Search Terms:**

**type-only imports**

```ts
// ts-import-type-only.ts
import type * as ts from 'typescript';

function some(s: ts.SyntaxKind) {
}
```

```ts
// ts-import-brackets.ts
function some(s: import('typescript').SyntaxKind) {
}
```

**Expected behavior:**

Both compile to simple:
```js
function some(s) {
}
```

**Actual behavior:**

While `ts-import-brackets.ts` does compile to simple, the `ts-import-type-only.ts` transforms into a module.

Depending on `--module` parameter it could inject an empty `export {}`, wrap in AMD `define` etc.

<a href="https://www.typescriptlang.org/play?ts=4.0.0-dev.20200524#code/JYWwDg9gTgLgBDAnmApnAVHAhgZwXgMyghDgHIlUcBjKYMGMgbgFgAodggVwDtqZgEHnBwkUAChwAufADoAyoh4wsADwDSwHgBMAlHADe7AL5A">
<b>Playground Link:</b>
 

![image](https://user-images.githubusercontent.com/4041967/82790536-1dacbf00-9e64-11ea-8737-63d629d0b330.png)
</a>

For packages with huge typings universe, it may become tedious to ALWAYS prepend type names with `import('typescript').***` when the code is not meant to be in a module.

It'd make it much simpler to have `import type * as ts from 'typescript'` and just use the short `ts.` prefix.

As type-only "ad-hoc importing" does not turn a source file into a module, the current behaviour is inconsistent. Merely importing a type is not meant to indicate a module shape.

**Comment by RyanCavanaugh** [comment]
We can't possibly change this behavior now.
