### ISSUE TITLE
type mismatch when importing json, no error with inline placement

### ISSUE THREAD

**Issue by novellizator** [microsoft/TypeScript#38773]
**TypeScript Version:**  3.8.3

**Search Terms:** inline import bug

**Code**
https://stackoverflow.com/questions/62010225/typescript-only-raises-error-only-if-file-is-imported/62010521

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:** Should not have errors

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
When you give a program different inputs, different behavior may result; this is how you're able to write different programs.

Imports produce an inferred type based on certain widenings; these widenings work differently when a contextual type is present as shown in the question.
