### ISSUE TITLE
Pick<T, never> doesn't work as expected

### ISSUE THREAD

**Issue by Eddie-CooRo** [microsoft/TypeScript#38771]
**TypeScript Version:**  4.0.0-dev.20200524

**Search Terms:** Pick utility, never

**Code**

```ts
interface Person {
  name: string;
}

type T = Pick<Person, never>;
const a: T = {}; // this should work
const b: T = "Hello"; // this shouldn't work
const c: T = { name: "Eddie" }; // this shouldn't work
```
[link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200524#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyyIcAthAFzIZhSgDmA3AQL4EFgCeADigCrIAvGmAIA1gB50UbCAA0JCADdoAPhYIctZHGqCReVk2QB6U8jAALYBhpWsAVwA2AE2QB3LFHEEtIHQAjfWFkACIACQhnZywwk3NLGzsMBxdXEAByME9vX38dBBDDEnIqcIBRV1dgCDDkYzMLa1t7JzcsnK8fIA)

**Expected behavior:**
I feel like `Pick<T, never>` should be equal to `{}`. So `Omit<T, keyof T>` should become an empty object.

**Actual behavior:**
`Pick<T, never>` becomes `any` as if there is some sort of bug that prevents the type check to execute normally

**Playground Link:** An additional example which uses the `Pick<T, never>` through the usage of the `Omit` utility in a real use case and demonstrates why it is important for Pick to work as I mentioned: [link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200524#code/C4TwDgpgBAChBOBnA9gOygXigbwFBQKgDMBLJYVAQwFsIAuKRYeE1AcwG59CAbSpqrQZMW7LoSiU29KKgCu1AEYIuAX1y5QkKAFEAHpQDGwADwAVADQBVAHyYoZqBD3AIqACaIoVqAH5vTi5ung5+oQyoEABuCFAR0Soa7hCGfPDQRHKoxiRoxMjIJgBC9jCU8MAklDwmcEhoNjYAFOVsiAy6BsbFFrDlldW1CCiojVAAPn0VVTV1I3a96UwAgvBtDADy1CSmc2i9ANYQIMhEUEU2AJQMUcgk7hxQGkQFTdjEZAI0MgBEOu7uEgQH5QVS9d5SGQAJl6fC+QigPwAwgV4MgQapLo8APTYqAAd2Q8AOXkMRPSxh4IFwL2Qbw+5EEv3+gOBoPBkmkDChoKxUFxTngaKQUDJQpSwCpNNe71IjO+DD+AKBP16kO5sP4FAViJRRPRoKgvR+AAkIDweOjLvy8WYABbQRApNDuKBgcrfVzwKDKMm0LyUVAgAB0BOghkDbv4AaDwDtrDYUGAyCgO1wQA)

**Comment by ilogico** [comment]
It doesn't become `any`, it becomes `{}`. You cannot assign `null` or `undefined` to it, but everything else is assignable to the empty interface.
I believe the empty interface is special in the sense that excess properties aren't checked. But everything else is just a consequence of all values (except for `null` and `undefined`) implementing the empty interface.

**Comment by Eddie-CooRo** [comment]
Yeah. It makes sense that the type becomes {}.
BTW, I still don't understand why string should be assignable to the {}.
Had you checked the second playground link I shared? the most reasonable behavior for the Omit expression in that example is to remove all of the properties and only accept an empty object as the parameter.

**Comment by ilogico** [comment]
Strings are assignable to `{}` because they implement all the necessary properties and methods (none in this case).
In any case, there's no way to force a type not to have properties.
```ts
interface Person {
  id: string;
}

const joe = { id: '42', name: 'Joe' };
const person: Person = joe; // compiles
const otherPerson: Person = { id: '42', name: 'Joe' }; // errors because there's excess properties
```

[Excess properties checks](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks) only apply to fresh objects, but they don't seem to apply to the empty interface. I believe this is by design.

**Comment by Eddie-CooRo** [comment]
Than you @ilogico.
Yeah it's probably by design though it doesn't make sense to me, but I'm sure the guys at the core are seeing the bigger picture and this is probably the best solution.
However, I was able to achieve my desired behaviour by doing this:
```ts
Exclude<keyof Person, keyof B> extends never ? Record<string, never> : Omit<Person, keyof B>;
```

A type that only matches the empty object would be very useful. Do you know of any feature request issue for it that I can track?

**Comment by ilogico** [comment]
Just another example
```ts
interface Person {
  name: string;
}
const f: Person = () => {}; // works because functions have a name property, which is a string
const w: Person = window; // the window has name as well
```
