### ISSUE TITLE
Can not assign Object to a string type variable 

### ISSUE THREAD

**Issue by anjneeksharma** [microsoft/TypeScript#38778]
not able to assign  **res['createdBy'] = createdby;**  here res['createdBy']  is a string and createdby is a object, please see bellow code for more detail. 

.then((output: any) => {
              const usersdata = output.data;
              newresponse = response.map(function (res) {
                const createdby = usersdata['rhatUUID_' + res['createdBy']];
                const updatedby = usersdata['rhatUUID_' + res['updatedBy']];
                res['createdBy'] = createdby;
                res['updatedBy'] = JSON.stringify(updatedby);
                return res;
              });

**Comment by DanielRosenwasser** [comment]
No minimal repro.
