### ISSUE TITLE
Unnecessary (Empty) File residing in the repo (Causing issues to Deno Website)

### ISSUE THREAD

**Issue by Swap76** [microsoft/TypeScript#38782]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:** the file  .gitmodules is empty and causing issues to deno.land website

**Actual behavior:** No file with 0B data should be there is taken into mind while programming the deno.land website
The file is completely empty
<img width="1048" alt="Screenshot 2020-05-26 at 10 51 25 PM" src="https://user-images.githubusercontent.com/37082605/82931271-4936c300-9fa4-11ea-9cc9-6c86704259fc.png">

Because of this the deno.land is waiting to fetch the data but not able to and gets into stoped stage 
<img width="1112" alt="Screenshot 2020-05-26 at 10 57 44 PM" src="https://user-images.githubusercontent.com/37082605/82931298-56ec4880-9fa4-11ea-943e-78b2801de00e.png">
 

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
We might be able to delete the file, but, uh, is there a corresponding issue on Deno to deal with empty files appropriately? That sounds like the actual bug.

**Comment by Swap76** [comment]
@DanielRosenwasser Actually this was kind of the first encounter with the empty files I am creating one issue for the empty file so no worry about that :-)

**Comment by lucacasonato** [comment]
@DanielRosenwasser Yeah this is definitely our bug, not yours.
