### ISSUE TITLE
Fine tuning compiler options for removing comments

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#3878]
Talk with @CyrusNajmabadi . Currently we have following different types of comments:
* Pinned comment
* Triple-slash
* Detached comment (i.e. copy right)
* Normal comment (`//`, `/* */`, `/** **/`)

Currently, ```compilerOptions.removeComments``` will remove everything but pinned comment and detached comment. However, in some case, users may want to preserve triple-slash or may want to get ride of detached comment. Thus, it will be useful to have a compiler flag that allows users to specify what kind of comments to be remove and by default ```compilerOptions.removeComments``` should remove all but pinned comments

**Comment by yuit** [comment]
To clarify the comment, pinned comments in every circumstance should be preserved (even if it is used with ```interface``` which will not be emitted in js)

**Comment by yuit** [comment]
As a result of PR #3883, our `--removeComments` will remove all comments except pinned comment at the top of the file (i.e Copyright header comments). This change eliminate the original functionality of the pinned comment. It is possible that we will go even further to totally remove the differentiation between `/!*` and `///` and `/*` (see issue #4734)

**Comment by mhegazy** [comment]
We have not got much feedback about this issue, and thus, do not see the value of adding additional complexity here.
