### ISSUE TITLE
Intellisense ignoring the typeRoots settings in tsconfig.json

### ISSUE THREAD

**Issue by JB-Scott** [microsoft/TypeScript#38793]
Issue Type: <b>Bug</b>

We need to place some custom typescript module definition files (___.d.ts) in a local project folder (./typings) for some node modules that do not have typings, and do not have @types typings either. We are using the following tsconfig.json:

```json
{
  "compilerOptions": {
    ...
    "module": "ESNext",
    "moduleResolution": "node",
    "typeRoots": ["node_modules/@types", "./typings"]
  }
}
```

This works for CLI compiling. But does not provide intellisense if the files are in the /typings folder.

Intellisense is working perfectly for modules that have typings in the node_modules/@types folder, but any files we put in ./typings are ignored by the intellisense system.

Hovering over the import statement shows error ts(7016) - could not find a declaration file for module '...' and suggests looking for a npm @types file.

Visual Studio Code intellisense is not looking in the 'typeRoots' specified folders and is only looking in the node_modules/@types (even if there is no 'typeRoots' option specified). It should look in all the folders specified in 'typeRoots'.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
@JB-Scott Can you share a project the reproduces this issue?

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? The insiders build has a new TS version

**Comment by zenininja** [comment]
Facing the same problem, the intellisense is not picking up the types..

**Comment by wkh237** [comment]
I had encounter similar issue, I suggest you can check the following things:

1. use `.d.ts` instead of `.ts` for type definition files, sometimes VSCode doesn't load `.ts` files I'm not quite sure why ..
2. try to explicitly `include` the typings folder

Hope that's going to help 😅

**Comment by mjbvz** [comment]
Closing this as are information is needed from the original poster.

If you are seeing a similar issue with the latest TS, then open an issue so we can follow up
