### ISSUE TITLE
Cannot safely, generically add a property to a record

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#38796]
**TypeScript Version:**  v4.0.0-dev.20200525, 3.9.2

**Search Terms:** object intersection record 

**Code**

```ts
function add<TShape, TName extends string, TValue>(
    obj: TShape, name: TName, value: TValue): TShape & Record<TName, TValue> {
  return {...obj, [name]: value};
}
```

**Expected behavior:**

No compiler errors

**Actual behavior:**

```
Type 'TShape & { [x: string]: TValue; }' is not assignable to type 'TShape & Record<TName, TValue>'. Type 'TShape & { [x: string]: TValue; }' is not assignable to type 'Record<TName, TValue>'.
```

**[Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200525#code/GYVwdgxgLglg9mABAQwCaoDwBUDKALZABwFMAaRLAOWQFtjFiAPKYsVAZ0XagCcYwA5uSwA1ZABsQxAHwAKAFCIliOACMAVgC4K+ImURhaxbVSPkAbhKkmxk4gEoTukogBkiAErEIcHplN0wrZS0ogA3oqIPMRQIDxIYQB0yWrq5ADahnQAutqWdgC+ANzyBUA)** 

**Additional attempts:**

I couldn't find any way to make this work without a cast; no matter what I tried, the property `[name]: value` is inferred as `[x: string]: TValue`, ignoring `TName`.  Other attempt:

```
  const addition: {[name in TName]: TValue} = {[name]: value};
  return {...obj, ...addition};
```
```
Type '{ [x: string]: TValue; }' is not assignable to type '{ [name in TName]: TValue; }'.
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200525#code/GYVwdgxgLglg9mABAQwCaoDwBUDKALZABwFMAaRLAOWQFtjFiAPKYsVAZ0XagCcYwA5uSwA1ZABsQxAHwAKAFCIliOACMAVgC4K+ImURhaxbVSPkAbhKkmxk4gEoTukogBkiAN4BtQ3UT8KajoAXRsrYgBfT0VECARuFHQYWARtb196ANMQsLsogF5PHyNQxEs8gG4YnmIoEB4kDwA6FrV1chamtFRk+DAIqoigA)

**Related Issues:** Possibly #18538

**Comment by SLaks** [comment]
On further thought, this wouldn't actually be safe, because `TName` could also be a union:

```
const bad = add<{x: 1}, 'a'|'b', 'Oops'>({x: 1}, 'a', 'Oops');
bad.b;
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200525&ssl=8&ssc=7&pln=7&pc=1#code/GYVwdgxgLglg9mABAQwCaoDwBUDKALZABwFMAaRLAOWQFtjFiAPKYsVAZ0XagCcYwA5uSwA1ZABsQxAHwAKAFCIliOACMAVgC4K+ImURhaxbVSPkAbhKkmxk4gEoTukogBkiAN4BtQ3UT8KajoAXRsrYgBfT0VECARuFHQYWARtb196ANMQsLsogF5PHyNQxEs8gG4YnmIoEB4kDwA6FrV1chamtFRk+DAIqoj5eTiwBNU0RELujA9GbQBGCPIAcmQVgB8V1RXVgHk4QnYVuTnF5cQ13cuDo5X7KonUJtUKoA)

I guess this is a feature request then, to have some way of accepting a _single_ property name as a parameter so this can be safe.  I don't have a specific design offhand.

**Comment by SLaks** [comment]
## Motivation

I want to create a hierachical builder that accepts property names as strings and builds an object with those properties.

For (a simplified) example:

[Playground Link](https://www.typescriptlang.org/play?ts=3.9.2#code/GYVwdgxgLglg9mABAQwCaoDwBUDKALZABwFMAaRLAOWQFtjFiAPKYsVAZ0XagCcYwA5uSwA1ZABsQxAHwAKAFCIliOACMAVgC4K+ImURhaxbVSPkAbhKkmxk4gEpEAb0WIexKCB5InAOn9q6uQA2oZ0ALralnYAviicuAQkiABkzqFGiPwU1BE2VsQxANzyMfLyEOLI7JwAInBwPM6uqiAw4qgA0mBqslAAniTaAOQQeMREwwA+w0wkYOww5sTDjk5uHl5IYMQA7oj1jd29UHgw7OQDJPZFiGVlFVU1Bw08x6rNShAI3Dwg0I1ZO40AhxP1EKhXtpDjxyMDIWAwYgrsZEKNxpMZnNWItlqtnPdHtVOAAJOAgdjEABCbQ6xB42AACsgeFB2NJPohvgteP8oID4aDwYQWWyTMzWex7E4ykpXGhUDDsLl6EwWGxOL9+AI5GFUaY6ORIY1oa9pa4lO5PN4DHsXo0ae1UPTZAq+md2L4RZLyHqjWb-Y0bq57iUic8YY66QysBK2Ry1awOIgyRTqbTnTG4+zOdzfnzAd6xRRs6RCHxLCwNiDEeDjTxTUHnFwQCQeLIi1Lbg95egYQBrHqqZWZRMari8bW6owmFWXQao9ETQjTWaMea4lbm5Qba3bO2pylRzOu9Du85e0UXAxmZEe3z13ytJ3vPoL+wfkpKQnlPNQRA0P0h70AAvLa+zAceLoyvYFqIL4CowrIwzADwCBQDCwy+naSEfnBO4IX2ryDr0KFoWAGGvO8WFotiCxLFucGEYqrzIaoyAQP2mHYfsuGwTuBGIcRQ5sRxXFUUONFLpMwYCcoFQ-HA4jEL44hwAIsiAcBl6Sr4qHoTC7wPq8iAgWZAFAeSlI6WyenkZRQYlHmSkqWpGlaVZKmdk+YmGUOxmNKZ5keWmNmeuxnEwsGQA)

**Comment by RyanCavanaugh** [comment]
I can't tell what you're trying to do here - please boil this down to something more actionable if you'd like us to follow up more. Thanks!

**Comment by SLaks** [comment]
## General feature request

Have a type-safe way to accept a string parameter and use it as a property name. In other words, a way to write the following code without the cast:

```ts
function add<TObject, TName extends string, TValue>(
    obj: TObject, name: TName, value: TValue) {
  return {...obj, [name]: value} as TObject & {[name in TName]: TValue};
}
```

This may require some way of accepting a _single_ property name as a parameter (as opposed to `'a' | 'b'`) so this can be safe.

**Comment by RyanCavanaugh** [comment]
Got it - this would be a duplicate (or at least *dependent on*) of [#27808](https://github.com/microsoft/TypeScript/issues/27808) then
