### ISSUE TITLE
`React.ElementRef<string>` failing tests in @types/react, ts@3.1

### ISSUE THREAD

**Issue by hellatan** [microsoft/TypeScript#38794]
There might be a regression in TypeScript@3.1. according to the failing tests in DefinitelyTyped.

**TypeScript Version:**  3.1

**Code**

```ts
// @types/react:
type HTMLIntrinsicAsRef = React.ElementRef<'div'>; // $ExpectType HTMLDivElement
type SVGIntrinsicAsRef = React.ElementRef<'svg'>; // $ExpectType SVGSVGElement
```

**Expected behavior:**
```
expect  TypeScript@3.1 expected type to be: HTMLDivElement
expect  TypeScript@3.1 expected type to be: SVGSVGElement
```

**Actual behavior:**
generated error:
```
Error in react
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/react/test/index.ts:464:1
ERROR: 464:1  expect  TypeScript@3.1 expected type to be:
  HTMLDivElement
got:
  {}
ERROR: 465:1  expect  TypeScript@3.1 expected type to be:
  SVGSVGElement
got:
  {}
```

**Playground Link:** 

**Related Issues:** 
I made the following PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44671 but these failing specs were completely unrelated to what I changed in the type definition file.

**Comment by sandersn** [comment]
I can't repro this bug on 4.0, and it passes tests, so I think it was related to DT infrastructure on that particular PR.
