### ISSUE TITLE
Cannot assign to 'clipboard' because it is a read-only property

### ISSUE THREAD

**Issue by TheDutchCoder** [microsoft/TypeScript#38804]
**TypeScript Version:**  3.9.3

**Search Terms:**
"Cannot assign to 'clipboard' because it is a read-only property"
 "clipboard"

**Code**

```ts
describe('clipboard', () => {
  it('it is undefined', () => {
   expect(global.navigator.clipboard).toBe('undefined')
  })

  it('can be mocked', () => {
    global.navigator.clipboard = {} // error
  })
}
```

**Expected behavior:**
Either clipboard to exist, or to be able to be mocked

**Actual behavior:**
Even though it's undefined, mocking it result sin "Cannot assign to 'clipboard' because it is a read-only property." which indicates it actually does exist.

**Comment by RyanCavanaugh** [comment]
This really is a read-only property according to the spec. If your mock environment is different, you'll need to provide a different DOM .d.ts

![image](https://user-images.githubusercontent.com/6685088/83435398-02f0c200-a3f1-11ea-962f-c50be4b4cf1b.png)

**Comment by abeMedia** [comment]
> Maybe I miss understand, but if it's `undefined` (not `null`), then how would it know it's read-only? It doesn't exist at all.
> 
> It would make sense it it **was** defined in some way, but it isn't.

As a quick hack you could just write `global.(navigator as any).clipboard = {}`
