### ISSUE TITLE
Ability to cleanly declare class interfaces separate from implementation (C++ style)

### ISSUE THREAD

**Issue by bogdanionitabp** [microsoft/TypeScript#38802]
## Search Terms

class declaration
class interface

## Suggestion

It would be nice if Typescript allowed "declaring" classes, like in C++. I will explain what this means.
Currently, in Typescript when writing a class, one has to write the entire implementation, like so:

```
class Foo {
    constructor(...) {
        // constructor implementation
    }

    public method1(...) {
        // method implementation
        // which may span
        // many lines
    }

    private method2(....) {
        // another method
        // with many
        // lines
    }
}
```

This is a simple example, but you can imagine how in the real world, it will become quite hard to glance the interface of the class (what the class offers - the public fields and methods) quickly, and one has to use either the "outline" feature of some IDEs - which I'm not a fan of - or simply scroll through hundreds of lines of code or use search to see all the methods. This is not optimal in my opinion.

The alternative, as C++ offers the possibility (and quite frankly enforces it in most non-trivial use cases) is to "declare" the class - write down the entire interface of the class without any method implementation and then implement the methods either in the same file or in a different one. The declaration of the class above would be:

```
class Foo {
    constructor(....);
    public method1(....);

    private method2(....);
}
```

This makes it easy to see the entire class at a glance, and understands what it offers. Then one can navigate to the desired method implementation if necessary.

## Use Cases

I would pretty much use this for all classes I write in Typescript, it's a very elegant approach in my opinion.

You can kind of simulate this currently by writing an "interface" (using the interface keyword) and then have your class extend that interface, but it's not really the same thing, since you can't instantiate an interface, and working with interfaces makes you unaware to the real type behind them.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) - especially points #2 and #5.

**Comment by WhileTrueEndWhile** [comment]
Why not an interface?
You can declare a constructor via `new(...): ...`.
I don't know if this i sufficient :)

**Comment by NN---** [comment]
What is the use ?
You have code folding and class structure view.

If you want separation you can do smth like:

```
var Foo : { 
 method(): void;
 ...
} = {} as any;

Foo.method = () => {
...
};

```

**Comment by RyanCavanaugh** [comment]
Please refer to 

>  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
