### ISSUE TITLE
Type guard against 'unknown' fails to narrow down to 'object' when using an if statement with the OR condition

### ISSUE THREAD

**Issue by wil93** [microsoft/TypeScript#38814]
**TypeScript Version:**  3.9.2

**Search Terms:** null object unknown

**Code**

```ts
declare const data: unknown;

if (data === null || typeof data !== 'object') {
    throw Error();
}

data;
```

**Expected behavior:** the 'data' const should be of type `object`.

**Actual behavior:** the 'data' const is recognized as type `object | null`.

Notice that _if I split the above condition_ into two separate `if` statements, then it works as expected.

**Playground Link:**

Version showcasing the bug: https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEYD2A7AzgF3sKGoC54BXFAaxSQHcUBuAKDoEsAzeAChz3gF5f4UiECPAA+I+BgCeABxBJWnKPACEfAORIARgCtwGNQEp4AbzrxzEgBYwq8AKIwbMNgfoBfBoppA

And here's the (working) version with separate `if` statements: https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEYD2A7AzgF3sKGoC54BXFAaxSQHcUBuAKDoEsAzeACgwE8AHEJVnHngBCALyj4AciQAjAFbgMkgJTwA3nXhb4GABYwq8AKIwDMNsvoBfBi3aCo8cRJREIEVRu079hk2YtrBgcaIA 

**Related Issues:** none found

**Comment by jack-williams** [comment]
This is a duplicate of #28131, just with the logic negated.

**Comment by wil93** [comment]
Right, it's the same issue.
