### ISSUE TITLE
Update spec section 4.8.2 to allow super bracket access

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#3881]
The first sentence of spec section 4.8.2 (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.8.2) says that a super property access must include a dot and an identifier. This is no longer true as of #3880. It needs to be updated to account for super bracket access.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
