### ISSUE TITLE
JSDoc comments in `lib.d.ts` shouldn't use bare opening HTML tags

### ISSUE THREAD

**Issue by dabalyan** [microsoft/TypeScript#38812]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** html tags, string typings html tags, doc comments html tags

**Code** See the open HTML tag `<big>`

```ts
/** Returns a <big> HTML element */
big(): string;
```

**Expected behavior:** No open-ended HTML tags in doc-comments

**Actual behavior:** open-ended HTML tags in doc-comments

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Worth reposting the image from your PR here, which gives more context and is also just funny.

![image](https://user-images.githubusercontent.com/972891/83063661-593abb00-a015-11ea-8b34-66681ea17233.png)

**Comment by DanielRosenwasser** [comment]
Thanks for the PR @dabalyan!
