### ISSUE TITLE
Typescript 3.9.* transpile adding interfaces to the output javascript when they are re-exported

### ISSUE THREAD

**Issue by weagle08** [microsoft/TypeScript#38818]
**TypeScript Version:**  3.9.*

When using the tsc transpiler included in all of the 3.9.* versions it puts re-exported interfaces into the output javascript when the module type is *commonjs*. This causes an issue when the module is a shared module between a commonjs NodeJS project and a client side project which uses module loaders such as Webpack or SystemJS. This is causing an "exports is undefined" error when the transpiled javascript is bundled.

**Expected behavior:**

re-exported interfaces should not be included in the transpiled javascript as exports.

**Related Issues:** none

**Comment by RyanCavanaugh** [comment]
It's *very* hard to tell what specifically you mean from a prose description; we really do prefer some code if at all possible. I can't reproduce this problem by taking my best guess at how you've set things up. Do you need to maybe use `import type` ? Are you using `tsc` on the commandline, or through another build pipeline? What is the relevant emit difference between 3.9 and your last working version?
