### ISSUE TITLE
narrow type according to deep property.

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/TypeScript#38819]
**TypeScript Version:**  4.0

**Search Terms:** narrow discriminate type

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

interface Test4 {
    somekey: 'a';
    s1: number;
    secondKey:{
        innerKey: 'x'
    },
};

interface Test5 {
    somekey: 'b';
    secondKey:{
        innerKey: 'y'
    }
    s2: number;
};

interface Test6 {
    somekey: 'c';
    s3: number;
};

type Union3 =Test4|Test5|Test6;

function f3(u: Union3){
    if(u.somekey === "a" || u.somekey === "b"){
        if(u.secondKey.innerKey ==='x'){
            console.log(u);
        }
    }
}
```

**Expected behavior:**
u in "console.log(u);" could be infered as Test4

**Actual behavior:**
u in "console.log(u);" is infered as Test4|Test5

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=1#code/FASwdgLgpgTgZgQwMZQAQBUoGcIBZUDewqJqWA9gLZQDWUAngFyoDkCLA3MaVgIzNgArpQBGsLqTJQk5MABMA0g0ZFJk8GFhKmrAB4tuJAL4AaYEa6hIsRCgzYIAVkKGyVWstYjOrrNNmKyqpqJBpaniz0BpJGvgBMAsJiMFwWwFbQ8MhomDgAbC6SFNR0OixIPkUAzImi4uaWEPQADmgAqmAgslWoALy5eAA+A47DDnmWcIJgSBBdYKhwVQAUgswd81UAlMGhcKsAdMUe9H29vagARAiXqIODqIJH7qVnF5cilzuu6vtPfjJ5NoDmEYNo3ix9N8QiFARQADZQA7w8gAc1WWwkMNiMXMQA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #18758
