### ISSUE TITLE
Hover hint is invalid if there are multiple type aliases with same parameters

### ISSUE THREAD

**Issue by zaki-yama** [microsoft/TypeScript#38829]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.9.3

**Search Terms**
- quick info
- alias / aliases 

---

- VSCode Version: 1.45.1
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Write the following TypeScript code

```ts
type Foo = string | number;
type Bar = string | number;

function someFunc(params: {
  foo: Foo,
  bar: Bar,
}) {
  //
}

// then try to call the function `someFunc`
someFunc(
```
Here I defined two type aliases, `Foo` and `Bar`.
Both have the same parameters, `string | number`.

2. Hover over the `someFunc` and show popup
3. The expected type of parameter `bar` is `Bar`, but actually it was `Foo`

![SS_2020-05-28_at_21_44_48](https://user-images.githubusercontent.com/1001444/83143637-37ccf280-a12d-11ea-9cf9-042ccb66c3d9.png)

It's also happened in Signature help.

![SS_2020-05-28_at_21_44_59](https://user-images.githubusercontent.com/1001444/83143708-5206d080-a12d-11ea-9ed3-d0c05ad48597.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Also related to #34778

The issue is that `Foo` and `Bar` are structurally equivalent from the type system's point of view

**Comment by DanielRosenwasser** [comment]
Yes, when we try to display the type

```ts
{
  foo: Foo,
  bar: Bar,
}
```

we are actually working with the type represented by

```ts
{
  foo: string | number,
  bar: string | number,
}
```

When we see `string | number`, we say "oh, yeah, I saw an alias for that once" and use the first we encountered: `Foo`.

**Comment by zaki-yama** [comment]
For your information, when I tried to open the same file in IntelliJ IDEA, hover hint showed the type alias correctly.

![SS 2020-05-28 at 21 40 25](https://user-images.githubusercontent.com/1001444/83517906-adadd100-a514-11ea-992c-43edc04a7b57.png)
