### ISSUE TITLE
document.baseURI type is string instead of string | null (lib.dom.d.ts)

### ISSUE THREAD

**Issue by vladeck** [microsoft/TypeScript#38823]
**TypeScript Version:**  3.9.3 (lib.dom.d.ts)

**Expected behavior:** `document.baseURI` is of type `string | null`

**Actual behavior:** `document.baseURI` is of type `string`

**Additional info from MDN:**  A DOMString representing the base URL of the specified Node. It may be **null** if unable to obtain an absolute URI. Although this property is read-only, its value may change in certain situations (see below).

**Comment by RyanCavanaugh** [comment]
I don't think this is worth the upgrade pain. The property appears to be defined in the vast majority of situations and would be a pretty annoying breaking change.
