### ISSUE TITLE
Unsoundness with strictNull, spread operators and accessors

### ISSUE THREAD

**Issue by skogsbaer** [microsoft/TypeScript#38824]
**TypeScript Version:**  3.9.3

**Search Terms: strictNull spread**

**Code**

```ts
// bug.ts
function useObj(obj: {foo: string, bar: number}): string {
    return obj.foo;
}

interface Inter {
    foo: string;
    spam: number;
}
class C implements Inter {
    get foo() {
        return "foo string";
    }

    get spam() {
        return 42;
    }
}

function doWork(c: Inter) {
    const res = useObj({...c, bar: c.spam}); // <==
    console.log("res=" + res);
}

doWork(new C()); // should print "res=foo string"
```

**Expected behavior:** should print `res=foo string` or result in a type error saying that property foo is undefined in the line marked with `<==`

**Actual behavior:** prints "res=undefined"

```
$ tsc --target ES5 --strictNullChecks bug.ts
$ node bug.js
res=undefined
```

**Playground Link:** 

**Related Issues:** no

**Comment by jgbpercy** [comment]
Spread tends to introduce a lot of potential unsoundness and should be used with care. There's nothing really in TS currently that addresses the difference in semantics between property access and something like spread or `Object.keys` (at least as far as I know). [Here's another example](https://mobile.twitter.com/_joetdc/status/1206689337640968192) where spread can land you in trouble with properties that are unset vs explicitly `undefined`.

While I'd love to see the team address stuff like that at some point, I don't know how far up the priority list it really is, and what the trade offs would be in terms of complexity, perf and "false positives" (rejecting code that is actually fine) for the compiler.

**Comment by RyanCavanaugh** [comment]
This is effectively the same as #9726 (if we did anything, we would handle ownness/enumerability as part of some combined effort to address exactly this scenario)
