### ISSUE TITLE
Sibling namespace missing name from import in allowJs declaration

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#38834]
**TypeScript Version:**  4.0.0-dev.20200528

**Search Terms:** javascript declaration js dot array notation namespace

**Code**

`index.js`:

```js
export const colors = {
  royalBlue: "#6400e4",
};

export const brandColors = {
  purple: colors.royalBlue,
};
```

**Expected behavior:**

When compiled with `tsc --allowJs --declaration --emitDeclarationOnly index.js`, it should export:

```ts
export namespace colors {
    export const royalBlue: string;
}
export namespace brandColors {
    import purple = colors.royalBlue;
    export { purple };
}
```

**Actual behavior:**

Instead, we get:

```ts
export namespace colors {
    export const royalBlue: string;
}
export namespace brandColors {
    import purple = royalBlue;
    export { purple };
}
```

Note the `import purple = royalBlue;`. It's missing `colors.`. 

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.staging-typescript.org/play?ts=4.0.0-dev.20200527&useJavaScript=true#code/KYDwDg9gTgLgBAYwgOwM7yQG2quBeOAbwCg44oIBPAQ0wCFMBXYALjgCIBiANgBYAGfsF7sANMQC+AbmLFQkWIhTo4AIyjVkAEwDCEbFFwESZMIyhhMrJQdQA6CjXpNg46cSA)
      
**Related Issues:** The closest issues I could find were #36270 and #33626...

**Comment by weswigham** [comment]
Looks like this is fixed in our latest nightlies. Probably by #38982.
