### ISSUE TITLE
Not able to infer type by checking existence of property in object

### ISSUE THREAD

**Issue by egonm12** [microsoft/TypeScript#38842]
**TypeScript Version:**  3.9.2

**Search Terms:**
object type inference 
incorrect type inference

**Expected behavior:**
When I have two interfaces that extend from the same base interface I should be able to check for the existence of a property within a variable that only exists in one of the two interfaces. TypeScript will not give an error saying that the property doesn't exist on the other type when I first check for its existence.

**Actual behavior:**
When I have two interfaces that extend from the same base interface I am not able to check for the existence of a property within a variable that only exists in one of the two interfaces. TypeScript will give an error saying that the property doesn't exist on the other type.

**Related Issues:**

**Code**
```ts
export type ProductDescription =
  | BagDescription
  | BeltDescription
  | ClothingDescription
  | ShoeDescription;

export interface BaseDescription {
  brand: string;
  name: string;
  partner_catalogue_number: number;
  color: string;
}

export type BagDescription = BaseDescription;

export interface BeltDescription extends BaseDescription {
  length: string;
  length_manufacturer: string;
}

export interface ClothingDescription extends BaseDescription {
  clothing_size_eu: string;
  clothing_size_manufacturer: string;
}

export interface ShoeDescription extends BaseDescription {
  shoe_size_eu: string;
  shoe_size_manufacturer: string;
}

// a response from an API request
// unkown what description will be
const description: ProductDescription = {} as ProductDescription;

// ts error while I expect this to work
// Property 'shoe_size_eu' does not exist on type 'ProductDescription'.
//  Property 'shoe_size_eu' does not exist on type 'BagDescription'
if (description.shoe_size_eu) console.log(description.shoe_size_eu)

// not a ts error
if ("shoe_size_eu" in description) console.log(description.shoe_size_eu)
```

<details><summary><b>Output</b></summary>

```ts
// a response from an API request
// unkown what ProductDescription will be
const description = {};
if (description.shoe_size_eu)
    console.log(description.shoe_size_eu);
if ("shoe_size_eu" in description)
    console.log(description.shoe_size_eu);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.staging-typescript.org/play?ssl=1&ssc=1&pln=40&pc=73#code/KYDwDg9gTgLgBDAnmYcAKUIBMCuBjGAEWAGc8oBLMGCiAOzgF4AoOOAHzgCEBDAc2JlK1WnVYduwADZFS5KjXrjOAYSkQYACwp0Bc4YrFtOAZU0Rgg+SPoBuZs1CRYcHTGBQAZjzypeJS30FUTgAb3EAIygeOiwALjgSGEpdezY6HgBbYASklL40uDAeWDoPAH08HhgedT4cYHK6HEyIjwTm1o97AF8HJ2h4Nw9vX25+KwMQ0HdYknGAyeD6MPE8CHUoXOSdAuY+x3BB1zp3Lx8-aVkhZYYZ4DmFwJubBnC2dc3t-MKpB74tN9dr9-lpypkYjhRjAcFB2okdql9v0ji5hucxmoNNpdEtXnB7o9-M9rIZVh8NtAgUiPuotLtyiQKAAvRrAHDUva07EMpms8GQ6Gw+F5YHIw7OIanEYXOBmCx4smErDzYmKkLvOCfKkIn7iEjmRp8tkc3VitgGiyMlmNCHNIVwrZmpEHAD0rrgPDgcJIkDoATgnkwmU9DAAgmgAJLe4AARwaSWY7rgODoAGsIAB3BiZzTVdCYXAEdUrTMUKRSOBtZjrf3wLBBV4JDDYfDXUkhRhhHqe+YtovtqZ2BwUTxwAAUDZehgAdJajTbyuyAJRa+gkDbAGd1SeN2fz638lfMUcTgBEB+NS5wZ5OcCnHfoq9rG7+24gfF309Ec8Nh5Ny5AA)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; see #34590, #37343, or others
