### ISSUE TITLE
window.orientation was changed to string

### ISSUE THREAD

**Issue by chocolatechipui** [Microsoft/TypeScript#3884]
On iOS 7, 8 and 9 window.orientation is a number:
```
typeof window.orientation === 'number' // returns true;
```
But in TypeScript 1.5 you've changed the type of window.orientation to string. This makes it impossible to check for orientation on iOS, such as the following:
```
var landscape = (window.orientation === 90 || window.orientation === -90);
```
TypeScript complains that you can't compare a number to a string. On iOS this is always a number.

**Comment by mhegazy** [comment]
@zhengbli can you take a look

**Comment by chocolatechipui** [comment]
Just checked my Android browsers, native and mobile Chrome on 4.4 and 4.5, they also return numbers for window.orientation. Windows Phone 8 and 10 always return 0 for all orientations. But at least it's a number.

**Comment by chocolatechipui** [comment]
I found a workaround by down casting to any:
```
var landscape = (window.orientation === <any>90 || window.orientation === <any>-90);
```

**Comment by zhengbli** [comment]
The IE spec (where lib.d.ts is generated from) defines ``window.orientation`` as string, but I didn't find W3C or MDN spec on this. Also as you said, it seems that in most cases the property is used as number. Therefore I agree it makes more sense to change it back to number.

**Comment by chocolatechipui** [comment]
Yes, I noticed that in the release note for 1.5 and though maybe I was overlooking something. But at the moment I'm in the middle of converting a mobile JavaScript framework into TypeScript and when I got to the module for feature detection, I ran into this for orientation checks.

**Comment by chocolatechipui** [comment]
The media query value for orientation is of course a string: "portrait" | "landscape".

**Comment by chocolatechipui** [comment]
The w3c spec for screen orientation is different from what this is. That threw me off at first until I read it carefully and realized that spec does not specify a window.orientation property.
