### ISSUE TITLE
await inside a non-async function should be a parsing error, even in JS with "checkJs": false

### ISSUE THREAD

**Issue by tupelo-schneck** [microsoft/TypeScript#38847]
## Search Terms

await, checkJs, mixed JS/TS codebase

## Suggestion

JavaScript input with await inside a non-async function, like

```JS
function foo() {
    await Promise.resolve();
}
```

should fail parsing even when `"checkJs": false`.  This is malformed JavaScript, not JavaScript with type-checking issues.

## Use Cases

Using VS Code for a mixed JS/TS codebase, unless `"checkJs": true`, await inside a non-async function is not highlighted as an error.  ESLint with `"parser": "@typescript-eslint/parser"` doesn't help and [typescript-eslint won't change that](https://github.com/typescript-eslint/typescript-eslint/issues/2126), since they just pass along what the TypeScript parser says.

But await inside a non-async function is just malformed JavaScript -- it's not a type-checking issue.  VS Code should notify me about the issue even with `"checkJs": false`.

Also we find that `"checkJs": true` is too noisy to be helpful in a mixed JS/TS codebase; compare #28448.

Our current workaround to catch this kind of bug in VS Code is to use ESLint with a parser other than `@typescript-eslint/parser`, which is a shame.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by gzzhanghao** [comment]
Another workaround is to write a eslint plugin that forbids using await expression outside async function: [eslint-plugin-await-in-async](https://www.npmjs.com/package/eslint-plugin-await-in-async).

**Comment by tupelo-schneck** [comment]
This issue seems to have been fixed at some point.  Using VS Code today with TypeScript 5.0.4 (and @typescript-eslint/parser 5.59.7) I see a `ts(1308)` error in JS files, even with `"checkJs": false`.

**Comment by RyanCavanaugh** [comment]
Confirmed. Thanks!
