### ISSUE TITLE
Mapped type with function makes generic accessed function not callable

### ISSUE THREAD

**Issue by Harpush** [microsoft/TypeScript#38843]
**TypeScript Version:**  3.9.2

**Search Terms:**

When trying to access a mapped type with functions as value with a generic type - the function is not callable and accepts never.

```ts
enum Type {
  A = 'a',
  B = 'b'
}

interface FnRes<T extends Type> {
  box: string;
  val: T
}

type fn<T extends Type> = (param: T) => FnRes<T>;

const fnsMap: { [key in Type]: fn<key> } = {
  [Type.A]: (param) => ({ box: 't1', val: param }),
  [Type.B]: (param) => ({ box: 't2', val: param })
};

const type = Type.A;
const res = fnsMap[type](type); // WORKS (FnRes<Type.A>)

function get<T extends Type>(type: T): FnRes<T> {
  // NOT WORKING - inferred param as never instead of T (fn<T>)
  const no = fnsMap[type](type);
  // Workaround:
  const yes = (fnsMap[type] as fn<Type>)(type);
  return yes as FnRes<T>;
}
```
In this case the compiler knows the keys are of enum `Type` and the generic too. So why cant it infer the function parameter as T?

**Expected behavior:**
Should infer the generic type instead of never

**Actual behavior:**
Inferred as never and thus not callable

**Playground Link:** https://www.typescriptlang.org/play/#code/KYOwrgtgBAKgngB2FA3gWAFBSgQSgXigHIBDIgGk2wCEDiAjIzAX00wEsQAXYAJwDMSAY2QAxEACVgAZwA8MKMAAePEABNpsRMAB8qKlHoB7JQC4o0rr04BzANwGAbiQA25mCzYYu2qPxDyiiqgGlpIeoQAFAgkvCQQ7gCUBHriUnIwOg4YmEJGIJZ+BQCyJAjmKFAA2gDWwHBQnGHAALrm-rJ1cHrMdOhY1fBIAHQ4bVDRsfHJ+HqRlcZmxFwAjBRQzm5QMXHQzImUA1VDwMPU45O7M3MLJuZEXABM65vmO-FQ+yzZufmFPkg6CdRtk8gUuFBeDI6P5pKUEFUAa1IkjEnYoAB6DFQADqAHkJABpADKEzSMnk2lGOkSXn4YBAQi47HyUBswC4gWUqlCJx0KO0SXM5Iyen62CxUAAcniFPiiQBJKUAcSgAFpGiB+HwoWptlNoCRNMC8AAyZpnTWWYAkPVGfiwCYdTK0gZgwogIwwkplRHaFoCpBogySnFGXg1WJGBlqUwGd0QuDQqKw+F+pAtKBGoqU8KJQPAYMDKFcMC8EBQJOabMi+RZTw5RuYIA

**Comment by RyanCavanaugh** [comment]
This is a correct error from TypeScript's perspective because there's no guarantee that any two expressions of the same generic type are necessarily the same *subtype* of that type's constraint. For example, this code would cause an unsoundness if invoked:
```ts
function get<T extends Type>(type1: T, type2: T) {
  fnsMap[type1](type2);
}
get<Type>('a', 'b');
```
In your example, we can see from inspection that both instances of `T` are sourced from the same expression `type` and that there (probably?) isn't any mutation between when the indexing occurred and when the function was invoked, but this is very one-off analysis that doesn't apply in any other case.

**Comment by Harpush** [comment]
@RyanCavanaugh Isn't it weird though? Lets take your example - i would except both `type1` and `type2` to be constrained to the same type.
Which means:
```ts
get<Type.A>('a', 'a'); // valid (works)
get<Type.A>('a', 'b'); // invalid (works)
get<Type>('a', 'a'); // valid (works)
get<Type>('a', 'b'); // invalid (doesnt work)
```
The last one should be both can be any `Type` but should be the same type. I think allowing to pass different values in this case is wrong.
Either don't use generics in this case or add two type parameters - say T and K.
Might be saying nonsense but that's what it seems to me.

**Comment by Harpush** [comment]
@RyanCavanaugh what i wrote isnt relevant to the question? Or should be another issue/ suggestion?
