### ISSUE TITLE
JS to TS inverter co-file for those who want to TS without the overhead while coding.

### ISSUE THREAD

**Issue by reijam** [microsoft/TypeScript#38851]
## Search Terms

 JavaScript to TypeScript from Typescript to JavaScript

## Suggestion
As a very long time user of JavaScript I find a great deal of Typescript to be less useful during development but as  I get closer to production code it becomes a great means for ensuring the code works properly and can be maintained.

At the same time I look at the JavaScript code generated by the TypeScript compiler and while compatible with JavaScript it is code that is boring to look at (said politely). It feels like to the TS universe JS  is an afterthought. As a consequence many users are turned off by the amount of boiler plate and other overhead in coding with TS.  I think there is a great way to address that problem and further the acceptance of TS.

Here is my request/ idea.  There should be a way to take any typescript generated .js file and reverse it back to typescript.  If not i suggest that a typescript co file be generated along with the JavaScript file that makes this possible. The co-generated file could be in JSON or .js format and should be both complete and useful for others who want to emulate it for their own purposes.

This might seem counterintuitively useful but if there was a reasonable example set of co-generated typescript hinting that is produced during a typescript compile Typescript the  language would be more palatable to those who find  it to be (  as Mr Putin has so eloquently stated about a former NSA worker) . 

   "Like shearing a pig. A lot of squealing and not a lot of fur".

## Use Cases

 Along with the JS output of the TS compiler another co-generated file that can be combined with the js file to revert back to the TS definitions and files

## Examples

Users look at the co-generated file to figure out how to create a ts file set out of their js file without having to to go through the formal **TSificiation** of their own code... If they follow the examples in the other code that is generated they can build TS without coding in TS.

## Checklist

My suggestion meets these guidelines:

* [ x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x? ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
So you have an input file, you create an output file from it, and you want a separate and additional way to... get a second copy of the input file? What?

Source maps already exist for the purpose of correlating lines of code in the output to lines of code in the input.

**Comment by reijam** [comment]
I think I was unclear about the goal.

The goal is to afford someone who codes in JS the ability to migrate existing code to TS without the laborious effort of line by line annotation and type creation... 


In other words the ability to construct all ts files associated with a typical typescript layout 

Specifically i want to start with a well formed **module.js** file

and then i want to construct one _and only one_ additional file that will in turn be able to construct 

- **module**.js.map
- **module**.d.ts
- **module**.tsx 
- **module**.types.ts

and any other ts files that i might be missing in this list.


However i recognize that today that is not possible without the laborious process of creating a tsx or ts file directly out of the initial **module**.js

This becomes a really big barrier to acceptance among the most experienced JavaScript coders.

While the value to an organization of having typescript files might be high.  For someone fluent in JavaScript it is not very much.   To be candid... I just delete all of it because the annotation it delivers relative to the page clutter it creates is a bad tradeoff.

Most of the types of errors that Typescript catches (the ones that have the most ts value)  are analogous to memory leaks in C and C++ 

Coders who have written a great deal of c/c++ know to code everything on the stack if possible and therefore can live with the risk.

And like memory leaks... when there are problems... having tools to lock down ones code becomes really useful as long as the bar is not too high to implement.

Having a co-generation file that can be combined with a js file to create all the TS files in a normal repo for a given module would be a boon for those who are on the fence about TS.

It also would be a great way to demo the two way relationship between js and ts... If you can take a ts file turn it into a js file and from that file (and one other file) revert back to the original ts it would be much more credible as a JS alternative.

Most of the time I would not use TS because I value my time :) but if I started having some strange issues it might be worth the time and effort to TS annotate all of my JavaScript files... but that is usually in the latter stages of an application development effort. 

From a TS perspective this seems like a waste of time. But i promise you two way painless compatibility will really help reduce friction in converting the really experienced JavaScript coders who do not need training wheels.
