### ISSUE TITLE
GoToDef/FindAllRefs for object binding elements do not trace back to their defining property

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3885]
``` TypeScript
interface I {
    /*def*/property: string;
}

let x: I;
let { /*use*/property } = x;
```

Go to definition on `use` doesn't currently take us to `def`; it instead jumps back to `use`.

Likewise, find all references on `use` should give us the identifier at `def` but it currently does not.

**Comment by weswigham** [comment]
IMO, the existing behavior makes sense since `property` is an assignment. A destructing assignment, sure, but still an assignment. If I wanted to see where, in scope, the `property` variable comes from, the current behavior is correct.

**Comment by DanielRosenwasser** [comment]
We made this change with shorthand properties. The idea is that in this example, if you are already on the definition you are clearly disinterested in where the variable definition is coming from, so we allow you to jump to the property definition.

This way, you can always get back to the property from a variable declaration with an extra `F12` or whatever your editor's Go-To-Definition supports.

```TypeScript
interface I {
    /*afterTwoGoToDefs*/property: string;
}

let x: I;
let { /*afterOneGoToDef*/property } = x;

/*goToDefOnHere*/property += " hello";
```

**Comment by DanielRosenwasser** [comment]
I dunno who did it but this is fixed now.
