### ISSUE TITLE
Typescript errors: cannot read property 'length' of undefined for spread operator, incompatibility from 3.5.1 to 3.6.3

### ISSUE THREAD

**Issue by HarkaranGill** [microsoft/TypeScript#38855]
Upgraded TypeScript library to the latest recently. Found an incompatibility issue going from 3.5.1 to 3.6.3 .

https://www.typescriptlang.org/play/index.html?target=1#code/GYVwdgxgLglg9mABAGTgcwBQFMBuWxQAqAngA5YBciAzlAE4xhoA0iu+UAkgCJUCGYYqzB8AtpRr1GLRMDh0IWAGIAbENQAWiAPxUARnDgqsA1gDoLAayzEAanzVYACnxh1qVWgyYBtALoAlIhUOHAwACaIAN4AUIjxiBAI1EZYZiroGABEABJYKhmIAOryKuFZAQDcMQC+MTFJYLSIGWho0tx8UHz8gogAvIjg4VjAjFjh1aiYAOQAwiowEJYzrDM5TquIWdQmChpK8qJZrPQgWGtgcCMAcmJYWzt7EBpydMdrpHx0HDfXWHdxI8AMrPDQGAAeJ0QMwgi2WAH0oGQHms3qIthZ0uh2kxOt0qkA

Make sure Target is ES5.

For 3.6.3 and up we get : 
Uncaught TypeError: Cannot read property 'length' of undefined
    at __spreadArrays (tsWorker.js:21)
    at eval (eval at <anonymous> (main-3.js:1239), <anonymous>:17:19)
    at main-3.js:1239

For 3.5.1 and lower it passes without error. 

SpreadArray function was introduced here, which triggers this exception: https://github.com/Microsoft/TypeScript/pull/31166 

To be fair spread operator on undefined should fail! As undefined is not iterable. 

Just reporting this issue for awareness, as originally did not check for undefined when using the spread operator as older versions of TypeScript did not catch this. 

Not sure if this should be marked as a "bug"

**Comment by j-oliveras** [comment]
To compare, running a simplified version of your code compiled to target esnext on Firefox and Node (both supporting spread operator):
```ts
function Log(...keyValuePairs: string[]) : void {
    console.log("Hello World");
}

const loggingData: any = undefined;
Log(...loggingData);
```
[Playground](https://www.typescriptlang.org/play?target=99#code/GYVwdgxgLglg9mABAGTgcwBQDocGsCmAngGoCGANiPgAqkwBOAzgFyKNT0xhoDaAugEpErAG5wYAE0QBvAFCIFiCAkZxy+LOXQYARAAl85LYgDqceuQk6BAblkBfWbOVh2iLWjRc0AEVJRSVlIwQkQAXkRwCXxgLnwJO1RMHE10L24-ANtZIA)
Firefox 76.0.1: `TypeError: loggingData is undefined`
Node 12.16.3: `Uncaught TypeError: Log is not iterable (cannot read property Symbol(Symbol.iterator))`

So typescript generated have a similar behavior as native support.
