### ISSUE TITLE
Previous generic union does not narrow to an union again with type predicate

### ISSUE THREAD

**Issue by InExtremaRes** [microsoft/TypeScript#38869]
**TypeScript Version:**  4.0.0-dev.20200531

**Search Terms:** type narrow discriminant generic

**Code**

```ts
interface A<T, K extends keyof T> {
    t: true;
    v: T[K];
}
interface B {
    t: false;
    e: Error;
}
type X<T> = A<T, keyof T> | B;

type Some = { y: number; z: string };
declare function assertIsX(x: unknown): asserts x is X<Some>;

// CASE 1: narrowing unknown (works)
declare const some: unknown;
assertIsX(some);
// Ok, `r1` is `string | number | Error` as expected
const r1 = some.t ? some.v : some.e;

// CASE 2: before narrowing (works)
declare const some2: X<{ [k: string]: unknown }>;
// Ok, `r2` is `unknown` as expected
const r2 = some2.t ? some2.v : some2.e;

// CASE 3: narrowing again (does not work)
assertIsX(some2);
// ERROR: `some2` narrowed to `B`, not `X<Some>`,
// so `v` isn't accesible
some2.t ? some2.v : some2.e;

// CASE 4: narrowing `A<any, any> | B` (does not work)
declare function onlyASomeHere(x: A<Some, keyof Some>): void;
declare const a: A<any, any>;
// `A<any, any>` is assignable to `A<Some, keyof Some>`
onlyASomeHere(a);

declare const some3: A<any, any> | B;
assertIsX(some3);
// ERROR: `some3` narrowed to `B`, not `X<Some>`
some3.t ? some3.v : some3.e;
```
I'm using a type assertion, but a type predicate makes no difference. The same happens starting with `X<any>` or `X<unknown>`.

**Expected behavior:** `some2` is narrowed to the union `A<Some> | B` so `.v` can be accessed when `t === true`.

**Actual behavior:** `some2` narrows only to `B`, so when `t === true` `some2` is `never`.

**Playground Link:** [playground](https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200531&ssl=31&ssc=22&pln=31&pc=39#code/JYOwLgpgTgZghgYwgAgIIB4AqAaZBpZCAD0hABMBnZAawgE8B7GZTAPmQG8AoZX5MAFz8oAVwgBuHnwBuQzAG08AXUkBfLqEixEKAEKcpvQcngAbChMOEhAUShQGUNVzB0ADigAaWdgF40WLi0jMxsyAA+yLqSLu4oAMoMALYo-hzIdEIgIkkARtDiyABeQhRgUKAA5siqkmQQCKZwUCgwIiAIYMAMIMhwFBZQYACSFJ4AFERC7dQgDADuIACUQv2DYFREyMBU3okprDEA9EfIAMKo8TbIAIxZzQ7zVcgzc4vI4-OO1BRLXPWNZooBA9MrICjJCDTECzBYgSRraAjMbjCEpJaSE7IADy1FwAAMoDd8dsqPiyhUQNVItk8tAIsg7A4oCT+oQiB5OhAyFwQSAwUTkP40RAAHRgZAAfnBkNF0mQpVlli4WIuV2QACYhPkYI4UCAHgtnp9vr9-g0mi1kHywSKtchvOl5NRSuUqkpobD3qpDirTriCVANSSdsh8a84ayqMROZAeTaJUGhTKUhrxVKUxA0-LFanRcrVZdrgBme72I1UvqVOCgD5kBgQKhzCVfKDUP6IoajCZ2jF+xkAJQH2IHQnJkODyAN5fm3P4DDDunxuGbYb2kNYy-7ELD0hDFBAAHIJYgkBRgLlTBAuHb09LbznM2mC6c1dcACxlx7PfEYOAgOhcH-Oh2EiJc6wbJsGBbb4-gBS1WnaTpul6HpTDoS5IQACWgCBJiEDB9ggIJ6CYZAiNYFZkGkBhgDIOoLSBa1QRPAj0GAoCAN9LFf3YgDOJA-c+gGYBKgNS8UDABdeKIkiQnIjd8S4NCMKInCWnGOA+3NQErQTTNSwCDi+i4hloi4TtkR7SFiz7LEbCHEcxxFYsSWnR45ykxdlynaC13QCilJcu8DLlBVQssIA)

**Related Issues:** Maybe #30557 but that case works on last nightly and this does not.

**Comment by jack-williams** [comment]
This is the same as #31156; the problem is that the left constituent of the union `X<{ [k: string]: unknown }>`, which is  `A<{ [k: string]: unknown }, keyof ({ [k: string]: unknown })>`, is not a subtype of `X<Some>`. As a result, the `A` part of the type in `some2` is removed, leaving `B` which is related to `X<Some>`.

**Comment by InExtremaRes** [comment]
Thank you @jack-williams, I didn't find that issue, reading it now. However the PR that should close that issue is closed with the comment "[...] there’s not currently a solution that’s worth the disruption it will bring". Something similar in #32158.

Also there is something I don't understand completely here. I updated the description just in case. Consider this snippet:

```ts
// CASE 4: narrowing `A<any, any> | B` (does not work)
declare function onlyASomeHere(x: A<Some, keyof Some>): void;
declare const a: A<any, any>;
// `A<any, any>` is assignable to `A<Some, keyof Some>`
onlyASomeHere(a);

declare const some3: A<any, any> | B;
assertIsX(some3);
// ERROR: `some3` narrowed to `B`, not `X<Some>`
some3.t ? some3.v : some3.e;
```
The first lines show that `A<any, any>` is assignable to `A<Some, keyof Some>` (and therefore a subtype, isn't?), however `A<any, any> | B` still narrows to `B` alone.

If this is still related to the issue you have linked, feel free to close this as a duplicate and I'll suscribe to that instead.

**Comment by jack-williams** [comment]
Assignability and subtyping are different relations, so while `any` assignable to everything, it is not a subtype of everything. 

Function calls use assignability, which is why there is no error.
Type predicates filter using subtyping, which is why the any case gets removed.

**Comment by InExtremaRes** [comment]
Oh, I see. Thank you for your explanation. Feel free to close this as a duplicate then :)
