### ISSUE TITLE
Multiple optional chaining accesses fail to correctly inference variable is defined

### ISSUE THREAD

**Issue by fguitton** [microsoft/TypeScript#38860]
Hello everybody,

I hope you are all doing brilliantly. I stumbled upon this today. Unless I'm not reasoning about this properly, the following behaviour seems buggy or inadequate.

**TypeScript Version:**  3.9.2

**Search Terms:**

- nested
- null
- undefined
- check

**Code**

```ts
if (orgid !== undefined && itemsMap[orgid]?.usage?.lastDays !== undefined)
    console.log(itemsMap[orgid].usage.lastDays.reduce((total, current) => total + current, 0))

if (orgid !== undefined && itemsMap[orgid] !== undefined && itemsMap[orgid].usage !== undefined && itemsMap[orgid].usage.lastDays !== undefined) 
    console.log(itemsMap[orgid].usage.lastDays.reduce((total, current) => total + current, 0))
```

**Expected behavior:**

Both statements above are correctly able to determine that `itemsMap[orgid].usage.lastDays` is defined by the we get to `console.log(...)`.

**Actual behavior:**

I both cases Typescript mentions that `itemsMap[orgid].usage.lastDays` is possibly undefined by firing to separate warnings:

```
(property) usage?: Usage | undefined
Object is possibly 'undefined'.(2532)
Object is possibly 'undefined'.(2532)
```

**Playground Link:**
[https://www.typescriptlang.org/play?#code](https://www.typescriptlang.org/play?#code/PTAEBUE8AcFNQM6wC4FdoChk3gVQQIYDm8AvKAN4ag2gA2BCyAIgZAgPwBcoAdqgFsARrABOAbQC6AbgwBfWbVBYcoAJLJYA0OSpLUhEt1D5isWQowq46zQIQBZAtB2VqtcQEsAJj37CxSR4NLQtZDBBQADFPAA80UXgAYwB7XiYCXmQEDFT05FBPO0dnYOKnF113GgAWACYePSVaAzNG+kYWNgQecQBGABpQAGYh0dAAdklQOWqZ+Vy0plAU0SIfP0ERUVAAH1BUXm9YADNPXlhvVwAGcMiAeVFPdd4COlAkgAtYJIBrc6IiGQBDssCyGE8J1AAApVusrgBCUjkQ7HM4XK4AMkxhXKznEcJ8kg4ADpWkYSQwmKx2KAkSijqdzpcAJRzPIIFJ0WCUlJEaFFLQlaAEtZEsmGHlUrrsEmJbyoJKwaHQ5ApYF0IZJVCiRJZFk6AB8oDVGtAAGoPjq9cghtcWWyImAAKKxOCMq5fH7-XiAjKg8GQmGExHIg6M9GXUDY3FCiqi+HTenhtHMrE4wX2eMhyQSsx0sOopkY6MZvEinN5kiUzo0hAFhmpjEG9lLLlSvkC8sJ8XkqW17pyy6K5Wq9VvLXWsHIA2kY2mt4Wq266d2h1AA)

**Related Issues:**
I would expect this to be related to :
https://github.com/microsoft/TypeScript/issues/14350
https://github.com/microsoft/TypeScript/issues/24091

**Comment by MartinJohns** [comment]
Duplicate #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.
