### ISSUE TITLE
Field decorator in Constructor field Parameters

### ISSUE THREAD

**Issue by danfma** [microsoft/TypeScript#38877]
## Search Terms

Field, Decorator, Constructor.

## Suggestion

This should be just syntax sugar. The idea is to allow defining in the constructor a decorator that will be applied to the field defined in the constructor.

So, my suggestion is to create something like a `@field:decorator` that would be applied to field parameter definitions on the constructor.

```typescript

class MyType {
	constructor(
		@field:decorator public field: FieldType) {
	}
}

// what would be the same as 

class MyType {
	@decorator field: FieldType;

	constructor(field: FieldType) {
		this.field = field;
	}
}

```

## Use Cases

For example, suppose you are defining a class using Mobx. Sometimes, you want to receive some values in the constructor. That new syntax would help to build this kind of "data types" easily.

## Examples

```typescript

class Car {
	constructor(
		@field:observable public name: string,
		@field:observable public pilot: Pilot) {
	}
}

```

Instead of having to write this:

```typescript

class Car {
	@observable
	name: string;

	@observable
	pilot: Pilot;

	constructor(name: string, pilot: Pilot) {
		this.name = name;
		this.pilot = pilot;
	}
}

```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I don't know if there is something similar proposed for the decorators in new  EcmaScript versions.

**Comment by RyanCavanaugh** [comment]
The potential for syntactic confusion here with decorators on the parameters themselves is just too high, plus it's possible that `@foo:bar` gains some additional meaning in the future. This would best be left alone.
