### ISSUE TITLE
any in array prevents type checking rest of array

### ISSUE THREAD

**Issue by danielzgtg** [microsoft/TypeScript#38870]
**TypeScript Version:**  3.9.3

**Search Terms:** "any array", "any list", "any prevents"

**Code**

```ts
// Works properly
let x: number = 123;
let y: number[] = [
        123,
        x,
        true,
];
```

```ts
// Doesn't work properly
let x: any = 123;
let y: number[] = [
        123,
        x,
        true,
];
```

**Expected behavior:** For both code snippets to result in the same compile error.

**Actual behavior:** The second snippet compiles without any error. This is unsound.

**Playground Link:** [First](https://www.typescriptlang.org/play/?#code/PTAEHUHsCcGsGdQAdqSQU2gGwJ4Cgt0AXUADwC5QA7AVwFsAjTUAXlAEYAmAZgG4DioHJVqNMAbQC6rUOLygFihV24AaeUsWl1mxUWg106ybyA) [Second](https://www.typescriptlang.org/play/?#code/PTAEBEHsFMGcDsDkAXUB3SAnA1qADppHtJgDYCeAUKdKgB4BcoAhvOaALygCMATAMwBuarVDkm8AK4BbAEYkA2gF1OoBZVCatmvvwA0G7VroGjW5JknQDSwUA)

**Related Issues:** No

**Comment by RyanCavanaugh** [comment]
Duplicate #19541
