### ISSUE TITLE
tsserver drops responses

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#3887]
The tsserver drops responses for requests that doesn't compute a valid value. An example is quickInfo request for a boolean literal (true, false). The actual quickInfo result is undefined which leads to no response send.

This is a regression and worked before.

**Comment by dbaeumer** [comment]
This big shows that it would be worthwhile rethinking the response strategy. The code would be a lot clearer if every request sends a response. I would make the life of clients easier as well. If something doesn't require a response then an event should be used and not a request.

**Comment by mhegazy** [comment]
@dbaeumer I agree, this is what we should have done from the get go. feel free to send a PR for that. @zhengbli there should not be any need for changes on the sublime text plugin side if openFile for instance started sending a response, correct?

**Comment by zhengbli** [comment]
Right the changes won't affect Sublime Text. I also agree it would be less error-prone this way.

**Comment by weswigham** [comment]
I concur - needing to specify the presence of responses and if one should be waited on has been the source of a number of bugs during my development.
