### ISSUE TITLE
TS Server: [Bug] Go To References should not include / prioritise definition

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/TypeScript#38887]
**Description**
_Go To References_ shouldn't include the definition in its results list as its used to find references to the function in question. This is usually not how it works with other language servers. I think this is a bug.

The problem right now is that I want to be taken to a reference but instead I end up in the same place as before because it points back to itself.

I can do this the other way around pretty easily (right clicking a function call and selecting "Go To Definition" works fine) but not this way.

There shouldn't be an issue with removing these. If users want the function itself they can select _Go To Definition_ or _Go to Implementations_

## Example

In the below example there is only one use of `alfa()` so i would expect Go To References to take me directly to that function call, but instead it shows me the definition (where i already am) first.
![gotoreference](https://user-images.githubusercontent.com/936006/83451517-01ee7d80-a44f-11ea-8c2c-1d45926c1e19.gif)

## Steps to reproduce

* Clone https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example/tree/goToReference (goToReference branch)
* You should have the same workspace as the example above
* right click on `alfa` definition and select _Go To Definition_

**TypeScript Version:**  3.9.4
**VSCode Version:** 1.46.0

## Expected behaviour
Take me directly to the reference (if there is only 1), otherwise only show references to the function.

Expected TS Server response

```json
{
    "refs": [
        {
            "file": "c/nextjs9-typescript-server-vscode-example/server/index.ts",
            "start": {
                "line": 10,
                "offset": 1
            },
            "end": {
                "line": 10,
                "offset": 5
            },
            "lineText": "alfa();",
            "isWriteAccess": false,
            "isDefinition": false
        }
    ],
    "symbolName": "alfa",
    "symbolStartOffset": 17,
    "symbolDisplayString": "function alfa(): string"
}
```

*Expected example:*
The Rust language server takes me directly to the use of this function and doesn't include the definition. 
![rustreference](https://user-images.githubusercontent.com/936006/83452535-cce32a80-a450-11ea-9a08-fdbf4678fafd.gif)

## Actual behaviour
Shows the implementation where i already am.

Actual TS Server response
```json
{
    "refs": [
        {
            "file": "/nextjs9-typescript-server-vscode-example/pages/index.tsx",
            "start": {
                "line": 8,
                "offset": 17
            },
            "end": {
                "line": 8,
                "offset": 21
            },
            "contextStart": {
                "line": 8,
                "offset": 1
            },
            "contextEnd": {
                "line": 12,
                "offset": 2
            },
            "lineText": "export function alfa(): string {",
            "isWriteAccess": true,
            "isDefinition": true
        },
        {
            "file": "/nextjs9-typescript-server-vscode-example/server/index.ts",
            "start": {
                "line": 3,
                "offset": 10
            },
            "end": {
                "line": 3,
                "offset": 14
            },
            "contextStart": {
                "line": 3,
                "offset": 1
            },
            "contextEnd": {
                "line": 3,
                "offset": 30
            },
            "lineText": "import { alfa } from \"pages\";",
            "isWriteAccess": true,
            "isDefinition": true
        },
        {
            "file": "/nextjs9-typescript-server-vscode-example/server/index.ts",
            "start": {
                "line": 10,
                "offset": 1
            },
            "end": {
                "line": 10,
                "offset": 5
            },
            "lineText": "alfa();",
            "isWriteAccess": false,
            "isDefinition": false
        }
    ],
    "symbolName": "alfa",
    "symbolStartOffset": 17,
    "symbolDisplayString": "function alfa(): string"
}
```

**Comment by RyanCavanaugh** [comment]
This report seems to intermix "Go to Definition" and "Go to References" (title says one and body says another) so I'm not entirely sure which command you want changed? "Go to definition" on a definition will find references instead since "you're already there".

Anyway we generally think of "references" as "Here are all the places you should rename if you want to rename this identifier", which *definitely* includes the original declaration. It's also intuitive because you might want to start at the definition and jump back and forth between the definition and its references using the references result as a navigation list.

If editors want to exclude the originating request span from the server response, they're free to do so (seems reasonable as a setting), so I would suggest this with e.g. VS Code if it's inhibiting your editing experience.
