### ISSUE TITLE
Issues with extending ObjectConstructor interface

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#3889]
While this currently doesn't error in [Playground](http://www.typescriptlang.org/Playground#src=interface%20ObjectConstructor%20%7B%0D%0A%20%20%20%20assign(target%3A%20any%2C%20...sources%3A%20any%5B%5D)%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Alet%20assign%20%3D%20Object.assign%20%3F%20Object.assign%20%3A%20function(target%3A%20any%2C%20...sources%3A%20any%5B%5D)%3A%20any%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%7D%3B%0D%0A), in **1.5.0-beta** and **release-1.5** branch, I get `error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'` for the following:

```typescript
interface ObjectConstructor {
    assign(target: any, ...sources: any[]): any;
}

let assign = Object.assign ? Object.assign : function(target: any, ...sources: any[]): any {
    return;
};
```

**Comment by billccn** [comment]
This is due to some limitations in definition merging where interfaces declared in `d.ts` files do not merge with "normal" ones declared in `.ts` code.

Your example _would_ have worked if you can say

```
declare interface ObjectConstructor {
    assign(target: any, ...sources: any[]): any;
}
```

but you can't do `declare` on `interface`.

The only solution is to move the `interface` bit into its own `.d.ts` and `///<referece` it from your code.

**Comment by mhegazy** [comment]
@billccn interfaces always merge, even accross files. there is no such limitation. looks like you are talking about interfaces defined within a module, since modules have thier own scope, and interface with the same name as one in the global scope will not merge..

e.g.:
```ts
// global.d.ts
interface I {
    a: string
}


// myModule.ts
import d from "anotherModule";

// This I is local to myModule and does not merge with the global"
interface I {
    b: number;
}
```

**Comment by mhegazy** [comment]
@kitsonk the sample you provided works fine for me on latest. can you provide more details?

**Comment by kitsonk** [comment]
Ok, I tried several different variations because I got it "working" accidentally and I realise the problem.  Now I don't know if it is as designed or not (it is very confusing from a developer though).

The following works:
```typescript
interface ObjectConstructor {
    assign(target: any, ...sources: any[]): any;
}

let assign = Object.assign ? Object.assign : function(target: any, ...sources: any[]): any {};

function test () {};
```

The [following](http://www.typescriptlang.org/Playground#src=interface%20ObjectConstructor%20%7B%0D%0A%20%20%20%20assign(target%3A%20any%2C%20...sources%3A%20any%5B%5D)%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Alet%20assign%20%3D%20Object.assign%20%3F%20Object.assign%20%3A%20function(target%3A%20any%2C%20...sources%3A%20any%5B%5D)%3A%20any%20%7B%7D%3B%0D%0A%0D%0Aexport%20function%20test%20()%20%7B%7D%3B) gives `Property 'assign' does not exist on type 'ObjectConstructor'`:
```typescript
interface ObjectConstructor {
    assign(target: any, ...sources: any[]): any;
}

let assign = Object.assign ? Object.assign : function(target: any, ...sources: any[]): any {};

export function test () {};
```

Obviously it has to do with modules and namespacing, but I will admit I am confused.

**Comment by RyanCavanaugh** [comment]
When you have a top-level `export`, your file is a module, which means all declarations are introduced at the module scope rather than the global scope. This means that `interface ObjectConstructor` declares a *new* type `ObjectConstructor` rather than merging with the global `ObjectConstructor`.

This is intentional because otherwise there wouldn't be any way to make a new interface local to your module that had the same name as a global type.

**Comment by kitsonk** [comment]
Thanks.  I figured it was intentional, but obviously it is rather confusing, especially when not having a "choice" about accessing globally scoped namespaces at the implementation level.  I assume there are no language semantics to denote that I am referring to the global namespace?  Therefore, the only way to extend it is as @billccn suggests (and @mhegazy implies) by declaring in a non-module, like a project `.d.ts`.

**Comment by RyanCavanaugh** [comment]
Correct. Some related discussion in #3857 and #983

**Comment by bryanforbes** [comment]
@kitsonk Given what @RyanCavanaugh explained, could you do something like this?

```ts
interface ObjectCtor extends ObjectConstructor {
	assign(target: any, ...sources: any[]): any;
}
declare var Object: ObjectCtor;
export let assign = Object.assign ? Object.assign : function(target: any, ...sources: any[]): any {
	    return;
};
```

**Comment by kitsonk** [comment]
@bryanforbes thanks for the effective workaround.  #983 being re-opened would also address the "limitation" I am perceiving so I will close in lieu of that.

**Comment by tomitrescak** [comment]
Guys, sorry to comment in this zombie thread but there is weird stuff happening. 
Declaring a following definition file does nothing and typescript does not recognise the polyfill:

```ts
// file polyfills.d.ts
declare interface ObjectContructor {
  assign(target: any, ...sources: any[]): any;
}
```

but declaring it inside global, using module augmentation works

```
// polyfill.ts

declare global {
  export interface ObjectContructor {
    assign(target: any, ...sources: any[]): any;
  }
}

// Object.assign = ...
```

Any idea why this is?

**Comment by mhegazy** [comment]
i would assume that the file ` polyfills.d.ts` has a top level import or export, this turns it into a module. modules have their own scope, an this this `ObjectConstructor` is not really the `ObjectConstructor` but rather a local interface with the same name that shadows the global declaration.

using the `declare global` syntax, you are bypassing the scoping of the module and placing the declaration explicitly in the global scope, and this it merges with the intended `ObjectConstructor` declaration and you get the desired behavior.
