### ISSUE TITLE
Find references for string union member finds all occurences of the string literal, instead of only the union member references

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#38895]
**TypeScript Version:**  3.9.4

**Search Terms:** union find references

**Code**
1. checkout https://github.com/AlCalzone/node-zwave-js/tree/dafcab951f25419a9cf92df68b0ee98d9c43e350
2. open `src/lib/commandclass/CommandClass.ts`
3. go to line 814
4. trigger _find all references_  on the union member `"partial"`

**Expected behavior:**
It finds the following references of the union member `"partial"`:
* `Driver.ts`, line 1291
* `SendDataMessages.ts`, line 232
* `CommandClass.ts`, line 814

**Actual behavior:**
![grafik](https://user-images.githubusercontent.com/17641229/83532735-f81c5700-a4ee-11ea-8e02-afdc4eef804b.png)
where each of the other occurences is just the literal `"partial"`:
```ts
			log.controller.logNode(node.id, {
				endpoint: this.endpointIndex,
				message: `${this.constructor.name}: doing a ${
					complete ? "complete" : "partial"
				} interview...`,
				direction: "none",
			});
```

**Playground Link:** not applicable

**Related Issues:** none found

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `"partial"` in one union and `"partial"` in another union are the same type and the request was to find all references to that type.

**Comment by AlCalzone** [comment]
@RyanCavanaugh 
> "partial" in one union and "partial" in another union are the same type

This part I understand. However the results above are not part of any union, they are just "random" occurences of the string literal.
