### ISSUE TITLE
Suggestions for jsx attributes should include ="" 

### ISSUE THREAD

**Issue by yunti** [microsoft/TypeScript#38891]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.9.4

**Search Terms**
- suggest, suggestion, completions
- snippet
- react, jsx

---

In vscode the autocomplete for className just adds `className` in webstorm it adds `className=""` is there a way in vscode to get it to add the additional =""?

I'm not sure currently where the autocomplete comes from, whether it is inbuilt into vscode or comes from the React plugin I use (although it doesn't appear to be in their snippets). 

https://github.com/dsznajder/vscode-es7-javascript-react-snippets

**Comment by mjbvz** [comment]
Potentially related to #25207 

If there is enough interest in this, we should also consider what happens when a user wants to write: `className={expr ? 'a': 'b'}`

**Comment by yunti** [comment]
@mjbvz webstorm/pycharm etc... has an option for completion on jsx attributes to be braces, quotes, none or `based on type`.  Based on type defaults to className using quotes and the others using `{}`by default. Which works pretty well.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/1826271/83502034-efa92980-a4b8-11ea-92a4-4e60ce5aba9d.png">

**Comment by armanio123** [comment]
Based on type makes sense to me as, it can also be used to avoid adding the suggestion to boolean. For the union types scenario, unless is union with `undefined`, I think everything should be on braces.

- None
- Braces
- Based on type

**Comment by merlindru** [comment]
Just wanted to leave a big thank you for adding this, super helpful 😄

**Comment by rshea0** [comment]
If I have it set to braces, it will auto complete a given attribute with braces once. If I ctrl+z and try completing it again, it just completes the attribute name without braces.

**Comment by andrewbranch** [comment]
I can’t reproduce that behavior:

https://user-images.githubusercontent.com/3277153/184702590-2c8e37e7-7857-4e14-8812-29aebe874737.mp4

Feel free to file a new issue with more repro info. This one should have been closed as completed.

**Comment by Strate** [comment]
It would be nice to auto add braces / quotes when `=` symbol pressed (like in webstorm).

This is VSCode:

https://user-images.githubusercontent.com/392644/203531303-31bac65f-58e4-4cab-a945-f5bf34be4c2d.mov

And this is WebStorm:

https://user-images.githubusercontent.com/392644/203531493-29b7fb6b-d144-4f9b-b5f0-652720db98e2.mov

**Comment by andrewbranch** [comment]
@Strate I think that would require a new VS Code API; there’s nothing that I know of where an editor asks us to auto-insert code upon insertion of a previous character. Feel free to leave your suggestion on the VS Code repo (be sure to search for duplicates first).

**Comment by Strate** [comment]
@andrewbranch isn't auto-closing jsx tag almost same feature?

https://user-images.githubusercontent.com/392644/203761394-bbc74c6f-f190-4419-a7ca-e7b01fe5c023.mov
