### ISSUE TITLE
the 'lib.dom.d.ts' file may need to add the 'onhelp' property

### ISSUE THREAD

**Issue by Kitetop** [microsoft/TypeScript#38909]
## Search Terms
onhelp event

## Suggestion

'lib.dom.d.ts' file may need to add one property for this event

## Use Cases
Disable F1 key on IE browser， but there will be errors on the editor
![image](https://user-images.githubusercontent.com/33886685/83612087-80186480-a5b4-11ea-862d-53624d04c90a.png)
![image](https://user-images.githubusercontent.com/33886685/83612107-87d80900-a5b4-11ea-874a-1f3e621f0e14.png)
## My Typescript version
3.1.6

**Comment by IllusionMH** [comment]
This looks like IE specific thing that makes no sense in definitions for everyone.

You can use same approach described here https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#some-vendor-specific-types-are-removed-from-libdts or just use `// @ts-ignore`/`// @ts-expect-error` for these two lines

**Comment by Kitetop** [comment]
> This looks like IE specific thing that makes no sense in definitions for everyone.
> 
> You can use same approach described here https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#some-vendor-specific-types-are-removed-from-libdts or just use `// @ts-ignore`/`// @ts-expect-error` for these two lines
