### ISSUE TITLE
`Array.prototype.flat` typing is incorrect

### ISSUE THREAD

**Issue by hbergren** [microsoft/TypeScript#38901]
**TypeScript Version:**  3.9.3, 4.0.0-dev.20200602, Nightly

**Search Terms:**
- flat
- Array.prototype.flat

**Expected behavior:**
Given `abc = [[1,2]]`, I expect `abc.flat()` to equal `[1,2]`.

**Actual behavior:**
I get the following error: `error TS2339: Property 'flat' does not exist on type 'number[][]'.`

**Related Issues:**
Potentially related to https://github.com/microsoft/TypeScript/issues/38298

**Code**
```ts
const abc = [[1, 2]]

const xyz = abc.flat()
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const abc = [[1, 2]];
const xyz = abc.flat();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200601&ssl=3&ssc=23&pln=1&pc=1#code/MYewdgzgLgBAhgI2DAvDA2ugjAGhgJgF1CAoE0SWADwE8AvVeJAOgDMAbOKACgEog)

**Comment by RyanCavanaugh** [comment]
Please add to #36554

**Comment by RyanCavanaugh** [comment]
Actually, cancel that, set target or lib to ES2019 to get `flat` typings. Your target (in Playground) is set to ES2017 but `flat` is an ES2019 feature

**Comment by hbergren** [comment]
Ah, my mistake. Thank you for the help!
