### ISSUE TITLE
Cannot extend union type field when interface inherits

### ISSUE THREAD

**Issue by sl1673495** [microsoft/TypeScript#38906]
**TypeScript Version:**  3.8.3

**Code**

```ts
interface Test {
  o: "a" | "b";
}

// Error !!
interface SubTest extends Test {
  o: "a" | "b" | "c";
}
```

**Expected behavior:**

An union type field could be expand when Interface extending

**Actual behavior:**

The type ""a" | "b" | "c"" cannot be assigned to the type ""a" | "b"".

**Comment by RyanCavanaugh** [comment]
This is the correct behavior. You can think of it this way: Someone with a reference of type `Test` that actually points to a `SubTest` should not be surprised - they think `o` can either be `"a" | "b"`, but they could read a `"c"` out of it instead.

**Comment by sl1673495** [comment]
> This is the correct behavior. You can think of it this way: Someone with a reference of type `Test` that actually points to a `SubTest` should not be surprised at a value of `.o` - they think `.o` can either be `"a" | "b"`, but they could read a `"c"` out of it instead.

Thanks a lot.

To give an example in the actual scene, there is a Button Component in `ant-design` component library whose props interface is

```ts
interface ButtonProps {
   type:'primary'
   ... more fields,
}
```

My own project encapsulates a MyButton based on `ant-design` Button, and I want to extend a danger type to its Props

```ts
// Error !!
interface ButtonProps {
   type:'primary' |'danger'
}
```

How can i do that?

**Comment by RyanCavanaugh** [comment]
You can write e.g.
```ts
interface SubTest extends Omit<Test, "o"> {
```

**Comment by sl1673495** [comment]
> You can write e.g.
> 
> ```ts
> interface SubTest extends Omit<Test, "o"> {
> ```

Thanks very much :)

**Comment by sl1673495** [comment]
> This is the correct behavior. You can think of it this way: Someone with a reference of type `Test` that actually points to a `SubTest` should not be surprised at a value of `.o` - they think `.o` can either be `"a" | "b"`, but they could read a `"c"` out of it instead.

>  Someone with a reference of type Test that actually points to a SubTest


I don't quite understand this, how to make this happen?
