### ISSUE TITLE
Remove unused quick fix does not remove inline type of destructed parameter 

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#38900]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.0-dev.20200601

**Search Terms**
- quick fix
- unused

---

Testing microsoft/vscode#98997

```ts
function foo({ x, y }: {x: number, y: number}): void {
	console.log(y);
}

foo({ x: 10, y: 20});
```

results in

```ts
function foo({ y }: {x: number, y: number}): void {
	console.log(y);
}

foo({ x: 10, y: 20});
```

**Comment by mjbvz** [comment]
To repo, just trigger the remove unused quick fix on `x` in `foo({ x, y }:`

**Comment by RyanCavanaugh** [comment]
This feels like guessing at what the user wanted, and violates a "Generate as few compiler errors as possible" metric for deciding what the expected behavior is.
