### ISSUE TITLE
JavaScript: redux.createStore return type inferred to be any

### ISSUE THREAD

**Issue by kaihaan** [microsoft/TypeScript#38903]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.0-dev20200601

**Search Terms**
- redux
- typings
- javascript
- suggest, suggestions

---

Intellisense not recognising/suggesting for redux store object:
<img width="590" alt="Screenshot 2020-06-02 at 17 10 23" src="https://user-images.githubusercontent.com/64160099/83543318-23557500-a4f4-11ea-91b8-32c2c0e90194.png">

...
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (2 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by mjbvz** [comment]
Minimal example:

```js
//@ts-check
const redux = require('redux')

const initialState = { counter: 0 }

const rootReducer = (state, action) => {
    return state
}

const store = redux.createStore(rootReducer, initialState)
```

The bug is that `store` is inferred to be of type `any`. This may be an issue with the redux typings, or with TypeScript's type inference

**Comment by mjbvz** [comment]
You can workaround this by giving store an explicit type:

```js
/**
 * @type {redux.Store<{ counter: number }>}
 */
const store = redux.createStore(rootReducer, initialState)
```

**Comment by kaihaan** [comment]
Awesome - thank you.
