### ISSUE TITLE
Private fields always generate polyfill unless on ESNext

### ISSUE THREAD

**Issue by TheBrokenRail** [microsoft/TypeScript#38902]
**Search Terms:**
private field, esnext, es2019

**Code**
```ts
class A {
    #prop: string;
    constructor(object: string) {
        this.#prop = object;
    }
}
```

**Expected behavior:**
On ES2019 and above it will generate with private fields.
```js
"use strict";
class A {
    constructor(object) {
        this.#prop = object;
    }
    #prop;
}
```

**Actual behavior:**
It only generates private fields on ESNext.
```js
"use strict";
var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, privateMap, value) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to set private field on non-instance");
    }
    privateMap.set(receiver, value);
    return value;
};
var _prop;
class A {
    constructor(object) {
        _prop.set(this, void 0);
        __classPrivateFieldSet(this, _prop, object);
    }
}
_prop = new WeakMap();
```

**Playground Link:** https://www.typescriptlang.org/play/?target=6&ts=4.0.0-dev.20200601#code/MYGwhgzhAECC0G8BQ1XQMQAcBOB7TAXNBAC7YCWAdgOYDcKawulp2ArsCbtgBS4BGAKwCmnIqyrUAlIgZo0JABbkIAOix5M0ALzQBIzvXkBfJMaA

**Additional Information**:
This page from MDN says private fields were introduced in ES219: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields.

**Comment by DanielRosenwasser** [comment]
Sorry, private fields are not part of ES2019 (nor ES2020). I think the page is inaccurate. It hasn't been moved to stage 4 yet, so it's not officially part of [the spec](https://tc39.es/ecma262/).

**Comment by TheBrokenRail** [comment]
Thanks for the clarification!
