### ISSUE TITLE
Typescript build in ErrorProne

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/TypeScript#38918]
https://errorprone.info/bugpatterns

error prone is awesome in java, what would be nice is to have support for error prone basically built into the language, like strict checks but that people can easily write checks for using a common API. It's possible that in a future version the existing strict checks could be replaced with this.

My 2 motivations for this is, I wish typescript was even stricter, beyond the scope of that which I think ya'll would be willing to provide. I'd also like to choose between warning/error/off with a common api.

**Comment by xenoterracide** [comment]
seems like a prerequisite? but maybe it's a duplicate? I suspect EP has a "plugin" API on top of the fact that it works as a compiler plugin.

**Comment by xenoterracide** [comment]
and to be fair, I'm asking for typescript to provide this EP compiler plugin as part of typescript (meaning it isn't a compiler plugin?), where in java it's all external.

**Comment by RyanCavanaugh** [comment]
I don't understand what the difference between a plugin API surface and what you're describing here is, relative to what already exists today. You can use the compiler API to query arbitrary type information today and write type rules that function like this; `typescript-eslint` is an example.

**Comment by AlCalzone** [comment]
There's also Semmle's LGTM.com, which is now being built into Github itself and does some quite clever checks ranging from unused imports to unsanitized user input and path traversal attacks.
