### ISSUE TITLE
: ( https://www.typescriptlang.org/play - spam to history api

### ISSUE THREAD

**Issue by qwabra** [microsoft/TypeScript#38916]
: (

https://www.typescriptlang.org/play

spam to history api
spam to history api
spam to history api
spam to history api
spam to history api

to browser history api

**Comment by qwabra** [comment]
I'm upset he erased my history

**Comment by orta** [comment]
You can turn this off keeping the URL as in the new playground settings page - I'm afraid some browsers don't respect the 'don't set history option;

![Screen Shot 2020-06-03 at 12 53 21 PM](https://user-images.githubusercontent.com/49038/83665295-38d0aa80-a599-11ea-94cb-968cc7c3d1d4.png)
