### ISSUE TITLE
Different compile results on 1.4.1 and 1.5.0-beta

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#3891]
test.ts (double `\\` in template)
```TypeScript
console.log(`a\\tb`);
```
tsc 1.4.1 -> test.js (single `\` in result)
```JavaScript
console.log("a\tb");
```
tsc 1.5.0-beta -> test.js (double `\\` in result)
```JavaScript
console.log("a\\tb");
```

**Comment by Artazor** [comment]
This is breaking change, imo

**Comment by RyanCavanaugh** [comment]
This is the intended behavior, but we should document it for the release. Thanks for reporting it!
