### ISSUE TITLE
@returns does not support arrow function syntax with object params

### ISSUE THREAD

**Issue by tstewart-klaudhaus** [microsoft/TypeScript#38912]
**TypeScript Version:**  3.9.3

**Search Terms:**
jsdoc arrow

**Code**

Works (Arrow syntax for return function, no object parameter):

```js
/**
 * @param options { { a: number, b: number } }
 * @returns { (c: number, d: number) => number }
 */
const test = ({ a, b }) => (c, d) => a * b * c * d
```

Works (Closure style syntax for returned function with object parameter):
```js
/**
 * @param options { { a: number, b: number } }
 * @returns { function({ c: number, d: number }): number }
 */
const test = ({ a, b }) => ({c, d}) => a * b * c * d
```

But fails (should be the equivalent of above in Arrow style syntax):
```js
/**
 * @param options { { a: number, b: number } }
 * @returns { { c: number, d: number } => number }
 */
const test = ({ a, b }) => ({c, d}) => a * b * c * d
```

Also fails (parameter type wrapped in parentheses, as is necessary in JS)
```js
/**
 * @param options { { a: number, b: number } }
 * @returns { ( { c: number, d: number } ) => number }
 */
const test = ({ a, b }) => ({c, d}) => a * b * c * d
```

**Expected behavior:**

Expect the arrow syntax (also referred to as Typescript syntax in the TS handbook) to work the same as the function syntax (also referred to as Closure syntax).

**Actual behavior:**

When the object parameter is not wrapped in parentheses (first failing example):
`TSC1005: '}' expected`
(on the arrow)

When wrapped in parentheses (second failing example):
`TS2300: Duplicate identifier 'number'`
(on both of the number type declarations within the object)

**Comment by sandersn** [comment]
The arrow function type syntax, which is defined by Typescript, requires parameter names and parentheses. Here's a working version:

```
/**
 * @param options { { a: number, b: number } }
 * @returns { (arg: { c: number, d: number } ) => number }
 */
const test = ({ a, b }) => ({c, d}) => a * b * c * d
```

Note that I had to come up with a name for the parameter, in this case `arg`.
