### ISSUE TITLE
Support Higher-kinded types

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#38925]
## Search Terms
Type Parameters, HKT

## Suggestion

Support Higher-kinded types

## Examples

```ts
function length<T extends ArrayLike<unknown>, U>(m: T<U>) {}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
See #1213
