### ISSUE TITLE
(Master Branch) tsserver.js hangs in vs-code

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#3892]
Tested at commit c27b379b1798b79f3ebf46db0aef03222acfc65f and 01244d60dac82eec017e9150e663c5d144f989ff .

To reproduce:

1) Build typescript (`jake local`).
2) In powershell:
`Copy-Item C:\<...>\typescript\public\built\local\tsserver.js C:\Users\<username>\AppData\Local\Code\app-0.5.0\resources\app\plugins\vs.language.typescript\lib\tsserver.js`

3) Open up vs code. Hover over several items to get quickinfo. After a few requests, the language service writes `Loading...` on each hover.

On occasion, the language service was busted immediately (on the first hover), but I'm having trouble reproducing it consistently. 

The source file I've been inspecting is `src\services\services.ts`.

This error doesn't appear to occur in Visual Studio. So it may or may not be a bug on our side.

**Comment by aozgaa** [comment]
This may or may not be related to #3887.

**Comment by RyanCavanaugh** [comment]
Can we close this then?
