### ISSUE TITLE
Specify optional properties without adding `undefined` which fixes an impossible to type JSON issue.

### ISSUE THREAD

**Issue by thesunny** [microsoft/TypeScript#38927]
## Search Terms

JSON
JsonObject
JSONObject
undefined
property
optional

## Suggestion

A way to specify a property as optional like with a ? but without allowing its value to be `undefined`.

## Use Cases

To get an object with optional properties defined using `?` such that it does **not** add undefined to the value type.

This allows a type with optional properties to extend an object type that does not allow `undefined`. The most common use case is the JSON type which does not allow undefined.

This is important when checking if data is valid before it flows through an API that uses JSON such as next.js.

## Examples

I want to type something as a JSON type defined something like:

```ts
export type JSONPrimitive = string | number | boolean | null;
export type JSONValue = JSONPrimitive | JSONObject | JSONArray;
export type JSONObject = { [member: string]: JSONValue };
export type JSONArray = JSONValue[];
```

But it doesn't pass if there are optional types. Here's a real world example of a table of contents hierarchy that I cannot get to pass as JSON even though it is valid JSON if `children` is optional but cannot be set to `undefined`.

```ts
type TOC = {
  id: number
  children?: TOC[]
}

type IsJSON = TOC extends JSONObject ? true : false
// this is false
```

It fails because `children` can be set to `undefined` which is invalid JSON; however, I only want to specify that `children` is `optional` (ie. it can be not set at all). There is currently no way to specify this.

The suggestion is to have an alternate syntax something like:

```ts
type TOC = {
  id: number
  children??: TOC[]
}
```

Or a breaking change which I think is probably more accurate but the above is backward compatible:

```ts
// This is the same as the old behavior but you have to be explicit that the value can
// be `undefined`. The `?` is specifically to specify that the key exists or not.
type TOC = {
  id: number
  children?: TOC[] | undefined
}

// This means that you cannot set `children` to be `undefined` but you can leave
// the value unset.  This is the same as the old behavior but you have to be explicit
// that the value can be `undefined`. The `?` is specifically to specify that the key exists or not.
type TOC = {
  id: number
  children?: TOC[]
}
```

## Checklist

**I'm assuming option 1 above which meets these guidelines**

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplicate of #13195.

**Comment by thesunny** [comment]
Thanks!
