### ISSUE TITLE
 Omit<{ key: any }, 'key'> becomes {} and allows any keys to be passed in

### ISSUE THREAD

**Issue by Alphy11** [microsoft/TypeScript#38932]
**TypeScript Version:**  3.9.2 -- nightly

**Search Terms:**
Omit, {}
**Code**
```ts
type BadOmit = Omit<{ key: any }, 'key'>;
function Example(param: BadOmit) {}
Example({ notAKey: true }); // should error!


```

**Expected behavior:**
The call to Example should error on an extra key being added.

**Actual behavior:**
No error is omitted.  Can decalre anything you want.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=Nightly#)

**Related Issues:** 

This comes up when generating a function that curries some arguments in a function that takes it's parameters as a single object.  If your function provides the remaining arguments, then the return will take any arguments you pass it, since {} ignores EPC.

Workaround: 
```ts
type SafeOmit<T extends Record<any, any>, K extends keyof T> = Omit<
    T,
    K
> extends {}
    ? Record<string, never>
    : Omit<T, K>;
```

**Comment by jack-williams** [comment]
I'm not sure what is the precise alternative being proposed. Is it that `{}` should apply excess property checking, or that `Omit` should return something other than `{}` when all the keys are removed?

**Comment by Alphy11** [comment]
I think changing EPC to include `{}` would be a pretty large breaking change, that has further implications than this.  Not against it, but I do not know what the consequences are.

HAving Omit return a type that is completely constricted to an empty object (such as `Record<any, never>`) is the expected behavior.  Whether that means also changing `{}`'s EPC behavior, I do not know.

**Comment by RyanCavanaugh** [comment]
`Omit` is just a type alias; we have no means by which to give it special behavior to do something different. Changing how it works *at all* would be a huge breaking change.

In a far and distant land, everyone will have switched from `{ }` to `object` or `unknown` and then *maybe* we can EPC `{}`
