### ISSUE TITLE
More Utility Types Regarding Partials

### ISSUE THREAD

**Issue by zieka** [microsoft/TypeScript#38935]
## Search Terms

- label:feature-request Partial
- label:feature-request Pick
- label:feature-request PartialProperties
- label:feature-request PartialPick
- label:feature-request Partial Pick
- label:feature-request Null
- label:feature-request NullableKeyOf
- label:feature-request Null Partial

## Suggestion

Add the following utility types for convenience:

```ts
/**
 * Provide a Type (T) and pick which keys (K) should be made partials (allow undefined)
 */
export type PartialPick<T, K extends keyof T> = Partial<Pick<T, K>> & Omit<T, K>;

/**
 * Provide Type (T) to get a union of string literals representing the nullable keys
 */
export type NullableKeyOf<T> = {
	[K in keyof T]: null extends T[K] ? K : never
}[keyof T];

/**
 * Provide Type (T) to get the same Type but nullable fields will be made partials (allow undefined)
 */
export type NullableAsPartial<T> = Partial<T> & Omit<T, NullableKeyOf<T>>;
```

## Use Cases

Sometimes you want to make specific properties optional and not all of the properties as is the case with `Partial<T>`.  This tends to be the case when building react components that must adhere to some narrow schema contract but the component's props may want to be wider for various reasons such as to make the component more generic and reusable or to simply prevent explicitly passing `null`.

## Examples
Here is a quick playground featuring a few scenarios of each:
https://www.typescriptlang.org/play/#code/C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDsBXAG3ICgrRI8IBnYHKAbyqijgC5YFkKAMrAATgEtiAcwwBuTlER8RE6fK4BjZWMlTCJCuXkBfGnWgAFOKODi45C+I0BrdABooAaSgQAHsAhiABNGKGcIEAB7ADM8LFwrGztyFEcXdy8MLAAyKAB5AFtxYAzPDBoNSOJmKEriMUjyAEY+NCYWXA4uXigAcgDmXrcFJT6B4CGFLTH23qpTKjqauobyACZW9tYu7j5+2eGuUf3B+Yqq5arVgGZNms6RvfHJhaWWcaaexNt7NNc25geXpwXr6XoaXrxdgKHonCaHRRPA5TJGnV4Xd7tNZfaw-BxOf7tIEgsEQqE7WHPBHHZ5nRYYqDja44pK-AnoIl9ElEcGQ7aPGaDYbo6qY5jXAAsfG+yT+HMBXNBPLJ-O6qPhKMFGoW5igADlDHBEOQIJ4InlouhyQoANreSRhCIxPAAXT4ZEoPn8gRCeDtLqgAH4vFB3RAAG4QUTzG3hKKxNAu+T00VQSQNRiQDS2SN8A2UI0ms0gC3y4DknXgaD58iFiAAQUYMvsVtYzZSmCguUKxQyNbrxdLmDk51TH1G-eNDabuOSZetaq1kyO6uXtVXdLejKxE8NU8b7fnqt2S+pG5FNSZu4L+5nrI77QXiNPm4Z4wl19rt8PAPLx8pyKaKuwo0EAA

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Based on user feedback, we're only adding utility types if they're needed for declaration emit.
