### ISSUE TITLE
bug of documentation-handbook-Variable Declarations

### ISSUE THREAD

**Issue by 6dyAllen** [microsoft/TypeScript#38944]
`Now search is { food: "rich", price: "$$", ambiance: "noisy" }. Object spreading is more complex than array spreading. Like array spreading, it proceeds from left-to-right, but the result is still an object. This means that properties that come later in the spread object overwrite properties that come earlier. So if we modify the previous example to spread at the end:

let defaults = { food: "spicy", price: "$$", ambiance: "noisy" };
let search = { food: "rich", ...defaults };
Then the food property in defaults **overwrites food: "rich"**, which is not what we want in this case.`

there should be <overwrites food: "spicy"> but found <overwrites food:"rich">
it is my first time to submit a issues,I don't know if I have made the problem clear，thanks

**Comment by RyanCavanaugh** [comment]
I think you're misreading it. The documentation accurately describes what happens; the property in the spread does overwrite the declared property.
