### ISSUE TITLE
Incorrect parse of type synonyms with with generics

### ISSUE THREAD

**Issue by wereHamster** [Microsoft/TypeScript#3894]
The following code does not parse with 1.5.0-beta:

```typescript
interface Editable<T> { editable: T }
interface Static<T> { static: T; }
type Entity<T> = Editable<T> | Static<T>;
```

The compiler seems to think that Entity is a function and the right hand side of the type synoym declaration is its body.

**Comment by RyanCavanaugh** [comment]
Works in master branch. I believe type aliases with generic type parameters are only in 1.6
