### ISSUE TITLE
Allow non-null assertion in object shorthand property

### ISSUE THREAD

**Issue by softwareCobbler** [microsoft/TypeScript#38941]
**TypeScript Version:**  3.9.2

**Search Terms:**
definite assignment assertion not permitted in this context
typescript non-null shorthand property
**Expected behavior:**
Accept input like `{foo!}`
**Actual behavior:**
`error TS1255: A definite assignment assertion '!' is not permitted in this context. `
`Variable 'resolve' is used before being assigned.(2454)`

**Related Issues:**
N/A
**Code**
```ts
type Resolver = () => void;
type Rejecter = () => void;

function explodedPromise() {
    let resolve: Resolver;
    let reject: Rejecter;
    let promise = new Promise((_resolve, _reject) => {
        resolve = _resolve;
        reject = _reject;
    });

    return {
        resolve!,
        reject!,
        promise
    };
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function explodedPromise() {
    let resolve;
    let reject;
    let promise = new Promise((_resolve, _reject) => {
        resolve = _resolve;
        reject = _reject;
    });
    return {
        resolve,
        reject,
        promise
    };
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/C4TwDgpgBAShDOB7ANgNwgJygXigCgEocA+KVRASwBMBuAKFElggCsIBjYTHfI7U8tXp0AZgFcAdpwqIJUCAA8wyRFQhUAChkQBbCvAiEoAbzpRzUZBGBQMCFOgBczJGkz0Ll67dYdgzuDZOdzMLKxswbT0DHgkIAHcoLV19QzwAfTtXdAAaKEzfTj5SU09PLIdoXALsiA8y8zsgm2qmv3rzAF8CYXLrMQw5UoafWoBCHNCGts4JqbLIlIN5zvpOoA)

**Comment by fatcerberus** [comment]
Using a definite-assignment assertion in a context where you're *explicitly providing a value* doesn't make much sense.

Isn't the correct solution to write the code like this?

```ts
type Resolver = () => void;
type Rejecter = () => void;

function explodedPromise() {
    let resolve!: Resolver;
    let reject!: Rejecter;
    let promise = new Promise((_resolve, _reject) => {
        resolve = _resolve;
        reject = _reject;
    });

    return {
        resolve,
        reject,
        promise
    };
}
```

**Comment by fatcerberus** [comment]
On a related note, I want to point out that definite-assignment and non-null assertion are different things, but in the context of this feature request it's ambiguous which one should be used.  That ambiguity is relevant because:
```ts
let foo: number;
({ foo: foo! });  // non-null assertion, OK
({ foo!: foo });  // definite assignment, error
```

**Comment by softwareCobbler** [comment]
Poor research on my part with the naming. "Non-null assertion" is what I intended to discuss.

With something like `({foo: foo!})`, it seems like possibly an arbitrary restriction that we cannot also do `({foo!})`; but maybe it introduces ambiguities or other problems. Thank you for your time.

**Comment by fatcerberus** [comment]
FWIW I agree with the feature request, I've found myself wanting to do `{ foo! }` myself a few times.  Would be nice if it were allowed.

**Comment by softwareCobbler** [comment]
OK so not world changing (people working on Typescript 4 and all), but I found there is a single check for an errant `!` in an Object shorthand property via `checkGrammarForInvalidExclamationToken`, which can be removed to no apparent ill-effect. The only test it failed was the one directly ensuring that `const foo = { a! }` is invalid, which here we are discussing making valid.
https://github.com/softwareCobbler/TypeScript/commit/e62df63

**Comment by fatcerberus** [comment]
> can be removed to no apparent ill-effect

The real question is, does it do what you want it to then, i.e. to act as a non-null assertion?

**Comment by softwareCobbler** [comment]
ah, good question! All I was thinking about was it passing the tests, heh.

**Comment by softwareCobbler** [comment]
Yes my very non-exhaustive tests show it accepts:
```
function foo() : {bar:number} {
    let bar: number; // yeah I now see "let bar!: number;" is equivalent
    return {bar!};
}
```
But is it necessary? Typing this whole thing out after you showed me the Tao of definite assignment has me seeing my own proposal as "i would like two ways to do the same thing, please"

**Comment by fatcerberus** [comment]
It's not the same thing, though.  Non-null assertion removes `null` and `undefined` from the type.  Definite assignment means "Even if you think I didn't initialize this, pretend I did".  `{ foo! }` would presumably do the former and therefore still have utility beyond just the example in the OP.

**Comment by FFdhorkin** [comment]
> Yes my very non-exhaustive tests show it accepts:
> 
> ```
> function foo() : {bar:number} {
>     let bar: number; // yeah I now see "let bar!: number;" is equivalent
>     return {bar!};
> }
> ```
> 
> But is it necessary? Typing this whole thing out after you showed me the Tao of definite assignment has me seeing my own proposal as "i would like two ways to do the same thing, please"

@softwareCobbler I don't want to open a dupe - would you please reopen? This 100% is not completed. As fatcerberus pointed out, what you said on Jun 11, 2020 is a definite assignment, not a non-null assertion.

Take this example: 

```typescript
function Foo(something: string[], somethingElse: string): { data1: string, data2: string } | null {
    let data1 = null as string | null; // can't use let data1: string | null = null because TS doesn't realize it might be overwritten in the callback below
    const data2 = something.find(thing=> {
        let someConditionMet = ...;
        if (someConditionMet) {
            data1 = somethingElse;
        }
        return someConditionMet;
    });
    return (data1 !== null) ? { data1, data2! } : null; // error!
}
```

I can't simply put a ! after `let data1`, because then I can't assign it a default of null (`Declarations with initializers cannot also have definite assignment assertions.ts(1263)`), and it might not be assigned a value in the loop.

I can't simply put a ! at the end of the find() callback, because undefined is valid. And I can't put a ! at the end of `const data2`, because the assignment is on the same line (same `ts(1263)` as above) and even though it is definitely assigned, it might be assigned a value of undefined.

I am forced to do one of the following to avoid the error, both of which hurt readability:
- `return (data1 !== null) ? { data1, data2: data2! } : null;`
- `return (data1 !== null && data2 !== null) ? { data1, data2 } : null;`
