### ISSUE TITLE
Type guard doesn't exclude null after null-check for object

### ISSUE THREAD

**Issue by Spoki4** [microsoft/TypeScript#38948]
**TypeScript Version:**  Nightly

**Search Terms:** null check fail type alias

**Expected behavior:**
Not need assign data to new variable for exclude null from type after null check

**Actual behavior:**
Can be use original object after null check, without assigning to new variable

**Code**
```ts
const someData = {
    foo: {
        mindfulness: `mindfulness`,
        focus_on_result: `focus_on_result`
    },
    bar: {
        mindfulness: `mindfulness`,
        focus_on_result: `focus_on_result`
    }
}

const skillGroupsDict = () => ({
  mindfulness: `mindfulness`,
  focus_on_result: `focus_on_result`
})

const order: (keyof ReturnType<typeof skillGroupsDict>)[] = [
  'mindfulness',
  'focus_on_result'
]

type StoreType<T> = {
    data: null | T
}

const store: StoreType<typeof someData> = {
    data: null
}

type TransformedItem = {
    id: number,
    text: string
}

const scope: (keyof (typeof someData)) = `foo`

const getData = (): TransformedItem[] => {
    if (!store.data) {
        return []
    }
    const data = store.data // This is workaround after null check for exclude null from type
    return order.map((key, id) => ({
        id,
        text: data[scope][key], // <- no error, works as expected
        text2: store.data[scope][key] // <- store.data possibile null
    }))
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=Nightly#code/MYewdgzgLgBBIFsCmARAhlNMC8MDeAsAFAykwBmIIAXPsWQzAgJZgAm5ArgDZhIQRaAAxbsuvfhCEAaeo1KVgnCAH1wKgE78eUYYuVqwm7dyhC5pAL6ySZAEZoNtQrfmiOPPgOHvxXqTbyCiBKqupaEDp6IQbhJmYWMJbEyUTEoJCwEADWzNzcAOIaIJwADhAozMCwuAAUAJQ4AHwwtS6kvp6SPqweEgIycvphRhFRMELDhsaRpuZElvXE6eDQMCAabEhOrdlIAJ4g5DAASkhQnBpgACr7pUgAPFB3SEdwuflFJeWV1U31AG0ALo4GAAuQAck6-QgEMCMAhUzisygEOIQOWRGe9xgAGUoBskLd7g9ri1cO0yGwMGhaGAeNwYAAfGDXFKYjJraCE2j4wnEx7Y17HeDIdCYcl0VwwamYOkM9lpLEvVkaNCQSgaZBsACSUCQCFBlNIzDY8oQdm28NI+oAHro4FANKwAOaKlaZOCge60Wp7Q7HWpCt6i1A0+qNXCTKjzD1rF3ncVYOr1WjXNUajbavUG4HNKUMZiBgCE3K0ADpZWhGsbGFoLlcwRjpakGJzYFXQWWkJWaYl65cwOtNttywg0KVan6DtIYKbIy02olC2xrYw7Q6qwCIN6kECAf6gWuGBuAEy0bu9zDb3f7w+JRZLBZAA)

**Comment by fatcerberus** [comment]
Control flow-based narrowing doesn't persist across function boundaries due to design limitations.  See #9998.

In this particular case TS doesn't understand that the `.map()` callback will be called immediately and only once.  You and I know that, but the compiler doesn't.  So it widens the type again at the function boundary just in case the value of `store.data` changes between the time you called `.map()` and the time(s) the arrow function gets called.  The same issue doesn't apply to `data` because it's a locally scoped `const` so TS knows it won't change.

**Comment by Spoki4** [comment]
Thank you, I completely forgot about this option.
