### ISSUE TITLE
Typescript/Reactjs has issues with Readonly intersection

### ISSUE THREAD

**Issue by MuratGT** [microsoft/TypeScript#38947]
**TypeScript Version:**  3.9.5

Following structure:

```
interface EditViewState<T> {
    entity?: T;
}

abstract class EditView<T, P, S> extends React.Component<P, EditViewState<T> & S> {

  constructor(props: P, ctx: any) {
      super(props, ctx);
      this.state = {
          entity: null // Type '{ entity: null; }' is not assignable to type 'Readonly<EditViewState<T> & S>'.ts(2322
      }
  }

    componentDidMount(){
        this.setState({ mode: "show" }) // Type '"show"' is not assignable to type '("loading" & S["mode"]) | ("show" & S["mode"]) | ("edit" & S["mode"])'.ts(2345)
    }
}

```

How can I use the `EditViewState `and extend it with `S` which is coming from the concrete class?

**Comment by MuratGT** [comment]
My current workaround looks like this https://stackoverflow.com/a/62218357/4467208

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
