### ISSUE TITLE
Import autocompletion with project references and yarn workspaces doesn't work

### ISSUE THREAD

**Issue by elitvinchuk** [microsoft/TypeScript#38955]
**TypeScript Version:**  3.9.5

**Search Terms:**
"project references" import 
"project references" import autocomplete
"project references" monorepo

**Description**
Hello! First of all, thank you for all amazing work! 

I've been trying to befriend yarn workspaces, project references and import autocompletion for a while. It was a relief to see that [caveat mentioned in docs is resolved](https://github.com/microsoft/TypeScript/pull/32028#issuecomment-583316477), but didn't manage to do it myself. I've even tried [example repo](https://github.com/RyanCavanaugh/project-references-demo) provided by maintainers, but no luck.

When using only yarn workspaces there're no issues at all - all packages listed in workspaces are imported with no issue. After adding ts and project references autocomplete disappears, though Go to Definition works as expected.

I'm is using `@babel/preset-typescript` so don't actually rely on `d.ts`.

Could you please point to whether I'm doing anything wrong or the issue really takes place?

Thanks in advance! 

**Code**
I've created [example repo](https://github.com/elitvinchuk/project-references). Initial commit illustrates how things didn't work initially, and second commit is updates due to [maintainer's example](https://github.com/RyanCavanaugh/project-references-demo).

**Expected behavior:**
Import autocomplete is available without building with `tsc -d`

**Actual behavior:**
![not-working](https://user-images.githubusercontent.com/1371092/83919155-b1df2600-a782-11ea-90ca-a112b9793c8a.gif)

**Related Issues:** 
* #26913
* #30946
* #26913
* #32028 - PR by @sheetalkamat

**Comment by sheetalkamat** [comment]
I think #38923 by @andrewbranch will help with this

**Comment by elitvinchuk** [comment]
Thank you @sheetalkamat for pointing me! Subscribed to the issue.

**Comment by andrewbranch** [comment]
@sheetalkamat, my PR almost solved this, but module resolution through node_modules fails when the referenced project isn’t built because `index.d.ts`/`index.js` doesn’t exist yet—the resolution host needs to use [your version of `fileExists`] that recognizes project reference redirect sources, but it’s not accessible in its current location. I remember you originally had that function in Project, but later moved it to Program, but can’t remember why... do you think moving it out to a common utility would make sense?

**Comment by sheetalkamat** [comment]
I think you could  imprelement getCompilerHost of autoImport provider as configuredProjectInQuestion.getCcompilerHost() and that should fix this. (Note you would want to remove unsetting compiler host of the configured project after updateGraph is complete.)
