### ISSUE TITLE
.d.ts files strip private property types, which can be used to distinguish instance types

### ISSUE THREAD

**Issue by tjjfvi** [microsoft/TypeScript#38953]
**TypeScript Version:**  4.0.0-dev.20200604

**Search Terms:**
private class property type declaration

**Expected behavior:** .d.ts files preserve the types of private properties, as these determine if an instance type is assignable to another

**Actual behavior:** .d.ts files strip private property type, creating an error

**Related Issues:** N/A

**Code**
```ts

namespace Original {
    class Box<T> {
        declare private value: T;
    }

    type Assert<T, U extends T> = U;

    export type False = Assert<false, Box<number> extends Box<string> ? true : false>;
}

// Compiles to:

declare namespace Compiled {
    class Box<T> {
        private value;
    }
    type Assert<T, U extends T> = U;
    // Errors becuase the type of Box.value was stripped
    export type False = Assert<false, Box<number> extends Box<string> ? true : false>;
    export {};
}

```

Obviously, this is a contrived example, but this was an issue I ran into.

<details><summary><b>Output</b></summary>

```ts
"use strict";
var Original;
(function (Original) {
    class Box {
    }
})(Original || (Original = {}));

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.staging-typescript.org/play?ts=4.0.0-dev.20200604#code/FAOwhgtgpgzgDmAxlABAeQE4EsDmXwA2KA3sCuSogWDDCgEID2AHgDwAqAfCWRXwCZQqYDKjjYAbmAAuqKQQCuUAFwp2Abl7kAvsC0ppATzioAgrSgZpHADQoAqiijNZIfnS4oAvA837ncIxWBsaoAGJgBDCoPubRVqwAZpHRdkxsIAoQAEaW3M6u7gwsrDDS2CA43AD8BhhKKKrJUVCcmrrAAPSdKADCjBBwWASwBozKeoLCoijg0PBIqP2Dw1D8PHzCtMVsnqR8fOJYUrIo8kqafLp8RiYocZbW7HaOBVBuHtw+9pcU3SgAUQwGCCdFyiAUNFQAHdUGVsHATOtpAALVC3VCMRI7AB05yg-mYgWCGJQERa3nuFgSzVSO1YmRyeScLneRXSpXK+CqKFq5QaTRSrV+5ACQWkJG07WAQA)

**Comment by tjjfvi** [comment]
A workaround is to use `protected` instead of `private`; it will preserve the type in the .d.ts, while still keeping it nominal.

**Comment by tjjfvi** [comment]
What if the compiler outputted `(variance: any) => any`, `(variance: any) => T`, `(variance: T) => any`, or `(variance: T) => T` (multiple generics can be handled with intersections, i.e. `(variance: T & U) => U`), based on the variance. When #1394 lands, it could be changed to the corresponding types, which wouldn't be a breaking change, as the types of private properties are not relevant for anything.

**Comment by pilcrowOnPaper** [comment]
2 years later and ran exactly into this issue

> However, if the type is imported via a .d.ts file (i.e. at compile time), the type of x is any! This leads to a long path of debugging where you can't figure out why vscode doesn't match tsc.

Would like to clarifications inside docs on `protected` vs `private` and/or remove the ability to get types from private methods entirely.

**Comment by Stono** [comment]
2 years later, exactly the same rabbithole and just stumbled across this 🤣
