### ISSUE TITLE
DataView access functions' littleEndian argument is optional

### ISSUE THREAD

**Issue by jasongrout** [Microsoft/TypeScript#3896]
In the es6 spec, various DataView functions have an *optional* littleEndian argument: http://www.ecma-international.org/ecma-262/6.0/#sec-dataview.prototype.getuint32, however the es6 typings included with typescript have these arguments as mandatory: https://github.com/Microsoft/TypeScript/blob/master/bin/lib.es6.d.ts#L2046

This causes problems when trying to compile code where the littleEndian argument is not specified.

**Comment by mhegazy** [comment]
looks like a duplicate of #4083.

should be handled by #4307

**Comment by jasongrout** [comment]
I'd say #4083 was a duplicate of this, since this was opened way before that :).  But no matter, thanks for fixing it!
