### ISSUE TITLE
Add a way to declare a generic type inside generic arrows?

### ISSUE THREAD

**Issue by Stupidism** [microsoft/TypeScript#38965]
## Search Terms

1. nested generic types
2. declare a generic type as a generic type
3. Type 'Response' is not generic

## Suggestion

The ability to declare a generic type as a generic type

## Use Cases

I have multiple API services, which returns responses with different structures.

For example: 
```
export interface BackendResponse<Result = any> {
  result: Result;
}

export interface AResponse<T = any> extends BackendResponse<T>{
  success: boolean;
  code: number;
  message: string;
  total?: number;
  page?: number;
  pageSize?: number;
}

export interface BResponse<T = any> extends BackendResponse<T>{
  errorCode: number
  errorMsg: string
  success: boolean
  responseTime: number
  elapseTime: number
}
```

I want to create two api hooks to represent these two services, it prompts me `Type 'Response' is not generic` once I change my code:

```diff

export type UseApi<Response extends BackendResponse> = <Result, Params>
    (inProps: UseApiInProps<Result, Params>) => 
-        UseApiOutProps<Result, Response>
+        UseApiOutProps<Result, Response<Result>>

```

## Examples

If we write like this, I will get two errors one is `Generic type 'BackendResponse<Result>' requires 1 type argument(s)` another one is `Type 'Response' is not generic`. So if we support this new feature, there's no breaking change then.

```diff
-export interface BackendResponse<Result = any> {
+export interface BackendResponse<Result> {
  result: Result;
}

- export type UseApi<Response extends BackendRespons> = <Result, Params>
+ export type UseApi<Response<T> extends BackendResponse<T>> = <Result, Params>
    (inProps: UseApiInProps<Result, Params>) => 
-        UseApiOutProps<Result, Response>
+        UseApiOutProps<Result, Response<Result>>
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
It sounds like you're asking for #1213

**Comment by Stupidism** [comment]
@RyanCavanaugh Yes, thank you! Never found the right keyword to search for this!
