### ISSUE TITLE
Parameter decorator lost the default value

### ISSUE THREAD

**Issue by txbo** [microsoft/TypeScript#38972]
hi~
I am using the ts parameter decorator, but when I attach a default value to the decorated parameter, the default value does not take effect, and there is no default value in the decorator parameter options

Typescript version: 3.9.5

```ts
  @Get('/world')
  public async world (
    ctx: Context,
    @Query('name') @Parse('toString') name: string = 'txbo',
    @State('token') @Parse('toString') @Required('string') token: string,
    @Ctx('ip') @Parse('toString') ip: string
  ) {
    console.log(name) // -> When the parameter should use the default value is null
    return this.helloModel.world(ctx, name, token, ip)
  }
```

and

```ts
  @Get('/world')
  public async world (
    ctx: Context,
    // @Query('name') @Parse('toString') name: string = 'tianxiaobo',
    name: string = 'txbo',
    @State('token') @Parse('toString') @Required('string') token: string,
    @Ctx('ip') @Parse('toString') ip: string
  ) {
    console.log(name) // -> work well
    return this.helloModel.world(ctx, name, token, ip)
  }
```

I had to add an unnecessary decorator `@Default` to do things that JS already supports

**Comment by MartinJohns** [comment]
This seems to be an issue with the decorators you use, not with TypeScript. Just using decorators does not prevent default values to take effect.

---

Please also respect the issue templates for [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md) and [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md).
