### ISSUE TITLE
[Feature Request] Provide syntax for exceptions to index operator

### ISSUE THREAD

**Issue by thw0rted** [microsoft/TypeScript#38977]
## Search Terms

index signature class extend record

## Suggestion

Come up with some syntax for classes to implement a `Record` pattern / index signature, while having members/methods that do not conform to its constraints.

````ts
class FooDictionary {
  [key: string, other than "id" or "print" or "serialize"]: Foo;  // Needs magic
  id: string;
  print() { ... }
  serialize() { ... }
}
````

I'm not sure how this would be implemented.  Maybe what's needed is a "complement" type, i.e. a formal internal representation of `Exclude<string, "a" | "b">` that doesn't just collapse down to `string`?

## Use Cases

There seems to be wide consensus that implementing the `Record` pattern directly on classes is A Bad Idea, but that doesn't change the fact that legacy codebases exist that use this pattern.  I came here because I'm trying to describe the shape of [this PropertyBag class](https://cesium.com/docs/cesiumjs-ref-doc/PropertyBag.html) but there are a bunch of StackOverflow questions (and a few issues here) where people are asking for the same thing

* https://stackoverflow.com/questions/55054226
* https://stackoverflow.com/questions/60706834
* https://stackoverflow.com/questions/48032926
* https://stackoverflow.com/questions/57899147
* https://github.com/microsoft/TypeScript/issues/19828

## Details

I've done pretty extensive research and have found a number of partial workarounds, but none that fully describe a type that:

a) is `new`-able,
b) types its unknown properties strongly, and
c) types is known properties correctly

The closest I've gotten is [this union type](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyARnFAFzIgCuAtidANwEC+BAJhAgDbkq84AZyHIAQnA4ARYAjDB0IcgE8cBYsgDaAawjKqQsFFABzALpUM6FoWLAOBo6abIA9K+TRKyQ8ZAnkYFEQdDBkYSFgEyUSHhQwLCs2AgJQSFhEFABJKxk5BSUoVTxbIk17Rz9zS0wbdnwuQSgBPhFkPPlFFQkhFBKNCp8nfxsNXuM4HmAALwgACgBKKgA3dHs6gjBlAAcUAHFMaVlOwtUAXmQczA6ClWQAMnbj26KeiBsCOLCHZAP0I-yXSKNg4yAuIAgAHdfocbkDlIsXO5PFBvH8ASc7ooeKpmjBoKIEuFkFtdpwAHT2ckJAAy6Eh0AAwsJ5gsQeTxsBJjNWUwgA) where you declare a base class and an interface with an index signature, then declare a union type that mashes them together, but as the Playground example shows, that union isn't `new`-able.

(Moving the bag-of-values down to a member property, would be a good idea, but I'm trying to describe the shape of code I don't own.)

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment]
Related/duplicate #4183, #4196 and #29317

**Comment by thw0rted** [comment]
Thanks @j-oliveras , I didn't have the right terminology for "negated" -- "complement" turned up in a lot of set-theory articles that also use TS terms "union" and "intersection".

But! Also!  Before anybody mashes that "Close as Duplicate" button, I'd like to point out that I'm trying to solve a *use case* -- strongly typed indexing on a "normal" class -- not to advocate one specific solution.  While negated types would almost certainly solve this, I'd like to leave this as a separate issue to see if any other promising solutions can be proposed.

**Comment by RyanCavanaugh** [comment]
The real original is #17867
