### ISSUE TITLE
Generated helpers in v3.9.5 decrease code coverage

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/TypeScript#38975]
**TypeScript Version:**  3.9.5

**Search Terms:** typescript coverage barrel

**Code**

```ts
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./file1"), exports);
__exportStar(require("./file2"), exports);
//# sourceMappingURL=index.js.map
```

**Expected behavior:**

Coverage 100%

**Actual behavior:**

![image](https://user-images.githubusercontent.com/11164679/84009849-24fbbe80-a974-11ea-8713-60f87d0a4bee.png)

The autogenerated code is not covered. If full coverage of the generated code is not possible, could you please consider adding a coverage ignore comment?

**Playground Link:** https://github.com/waldekmastykarz/c8-ts395-repro

**Related Issues:** n/a

**Comment by AlCalzone** [comment]
Out of curiosity: Is there a reason you choose to generate coverage for the transpiled code and not for the TypeScript sources?

**Comment by waldekmastykarz** [comment]
Yes, because if you look at coverage of the .ts file, you see the decreased coverage but don't get any information about what's wrong. All lines seem to be hit, yet the coverage is less than 100%

![image](https://user-images.githubusercontent.com/11164679/84027438-428a5180-a98f-11ea-9c84-0126b73ffb47.png)

**Comment by DanielRosenwasser** [comment]
Our helper functions aren't built with code coverage in mind, so I don't think we'll be changing it. One solution might be to switch to tslib to see if that helps. Alternatively, I believe Istanbul seems to be able to deal with this problem by giving itsourcemaps. It sounds like this is a feature request in C8.

**Comment by waldekmastykarz** [comment]
@DanielRosenwasser I understand that the helpers are not built with coverage in mind and it makes perfect sense. With that being said, would it be possible to include comments in them that would exclude them from the coverage reports? That would allow you to retain flexibility with regards to the helper code without negatively affecting developers who use code coverage tools in their projects.

**Comment by RyanCavanaugh** [comment]
We produce sourcemaps, which are the canonical way to represent "where this code came from"

**Comment by waldekmastykarz** [comment]
Correct, but somehow the coverage doesn't cover all paths. Not sure if that's limitation of the coverage tools or the consequence how the helpers are built. Following to what @DanielRosenwasser mentioned, if the helpers are not built with coverage in mind, then it would be fair to exclude the from coverage.
