### ISSUE TITLE
Azure Pipeline 404 Status Code

### ISSUE THREAD

**Issue by Danc2050** [microsoft/TypeScript#38974]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
N/A
**Code**
N/A
**Expected behavior:**
[Azure Pipelines](https://dev.azure.com/typescript/TypeScript/_build/latest?definitionId=4&view=logs) page should return a `200` status code.
**Actual behavior:**
[Azure Pipelines](https://dev.azure.com/typescript/TypeScript/_build/latest?definitionId=4&view=logs) page returns a `404` status code.
**Playground Link:** 
N/A
**Related Issues:**
N/A

**Comment by RyanCavanaugh** [comment]
I don't think we can change how `dev.azure.com` works from this repo, but we could likely update the link if you told us where you found it?

**Comment by Danc2050** [comment]
@RyanCavanaugh It is the second readme badge in this repo's `README`:
![readme](https://user-images.githubusercontent.com/32185616/84545832-d708f280-acb4-11ea-810d-fa8b9f0d0ca7.png)
