### ISSUE TITLE
Rename tsconfig.json to ts.config.json

### ISSUE THREAD

**Issue by timreichen** [microsoft/TypeScript#38983]
## Search Terms

config
tsconfig.json
rename

## Suggestion

I wonder if it would be a good idea of renaming the ```tsconfig.json``` file to ```ts.config.json``` to push a standard naming convension for config files as I explored in this article [here](https://gist.github.com/timreichen/87a894c94a4c2258b15962d1754e34a8/17245a26215174d88192ec1cc59fad35b20bca0e) and what many other tools do already (examples in article).

## Use Cases

This rename has the only purpose to align multiple conventions to a naming standard that is relevant now and also will be in the feature. Since typescript is becoming more and more popular it will undoubtedly influence other tools and could lead the discussion about this for now poorly explored topic.
What are your thoughts on this?

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> to push a standard naming convension for config files as I explored in this article here and what many other tools do already (examples in article).

[Relevant xkcd](https://xkcd.com/927/)

> [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code

This definitely would be a breaking change.

**Comment by RyanCavanaugh** [comment]
If config file names were going to standardize in the 50+-year history of file systems existing, I think they would have done so already.

`tsconfig.json` is only the name of the default config file that TS looks for. You can't "rename" a default like that in any meaningful sense of the word without breaking the planet. You can name your tsconfig files whatever you want by providing a filename to `-p`; we're investigating how to make that scenario more ergonomic with editors
