### ISSUE TITLE
Feature Request: type inference in class constructor

### ISSUE THREAD

**Issue by lc150303** [microsoft/TypeScript#38987]
Issue Type: <b>Feature Request</b>

As the following class
```js
class A{
    constructor(shouldBeString){
        if (shouldBeString) {
            this.id = 'abc';
        } else {
            this.id = 123;
        }
    }
}
```
After I instantiate it as follow, the type of `a.id` can be inferred to be `string` not `string | number`.
```js
let a = A(true);
a.id.substr(...);
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
You are missing a `new` in `let a = A(true);`. It should be `let a = new A(true);`

Once I fix this, I see the correct results in VS Code insiders:

<img width="516" alt="Screen Shot 2020-06-08 at 5 00 15 PM" src="https://user-images.githubusercontent.com/12821956/84091543-9013b800-a9a9-11ea-8018-570d593b5570.png">

**Comment by lc150303** [comment]
Sorry for missing the `new`. But I think the type can be narrow down to `string`, rather than the union `string | number`.
