### ISSUE TITLE
missing property in`declare module` when develop npm package local

### ISSUE THREAD

**Issue by ishowman** [microsoft/TypeScript#38989]
**TypeScript Version:**  3.8.3

**Search Terms:**

**Code**
package: https://www.npmjs.com/package/vue-cookie-plugin
source code: https://github.com/ishowman/vue-cookie-plugin
I declare module to add property to Vue in `src/main.js`

project source code: https://github.com/ishowman/vue-ts-consumer

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**steps**
> the steps to create project you could simply use code of `project source code` instead
- using vue cli to create a project with manual select: babel，typescript, eslint.
- install vue-cookie-plugin
- open `src/main.js` & add
```
import VueCookiePlugin from 'vue-cookie-plugin'
Vue.use(VueCookiePlugin)
```
- open `src/app.vue` & add `create methods` to class App
```
create() {
 console.log(this.$AppName)
}
```
- everything was perfect, I can get correct type tips to `this.$AppName`，and no types error when run ` npm run serve`
--------   attention please   ---------------
- set paths option in tsconfig.json or use `npm link`  to link my local code of `vue-cookie-plugin` to the project create before
- `App.vue` get error red underline for `this.$AppName`, and get types error tip when run ` npm run serve` (sometimes you need to reload your ide, i use vscode)

**Expected behavior:**
set paths in `tsconfig.json`, should get correct property like `$AppName` that add in `decalre module xxx {}`, and compile without no type error
**Actual behavior:**
can't get correct property type that add in `decalre module xxx {}`, and compile with type error

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
These repro steps haven't been reduced to a level that indicates a TypeScript bug; it sounds more like a misconfiguration or bug in an external tool.
