### ISSUE TITLE
Suggestion: Parameter type inference in plain functions

### ISSUE THREAD

**Issue by emilioplatzer** [microsoft/TypeScript#38992]
## Search Terms

   * is:issue  parameters type inference 
   * is:issue  parameters type inference duck 
   * is:issue  parameters type inference plain function

## Suggestion

Have a way to do not need to write parameter types of obvious funcitons in `noImplicitAny` mode. 

May be adding a global directive `// @ts-infer-any`

## Use Cases

I'm working in very strict mode. Then I am forced to write the types in places where it would not be necessary. 

## Examples

```ts
// @ts-infer-any

function f(name) {
    return !!name.match(/data/)
}

function pythagoras(a, b) {
    return Math.sqrt(a * a + b * b);
}

var good = f('hi');
var error = f(42); 
// Error: Argument of type '42' is not assignable to parameter with inferred interface {match:(Regex)=>any}.

var good2 = pythagoras(3, 4);
var error2 = pythagoras('3', ['']);
// Error: Argument of type '3' is not assignable to parameter with inferred number.
```
[see it here](https://www.typescriptlang.org/play/index.html?ssl=18&ssc=1&pln=1&pc=1#code/PTAEAEBcGcFoEsB2AzApgJ1gQ0QTwFD7ICuiAxpPAPaKjIAUiWAtqgJSgDe+ovo6qSMXS0AhKKasAdMyyQyAC3rAAJnKzA2+AL6ES5SjVAAHXJAVYA5lXRZo9LABpQAIw7c+-QcNoBZOQpS0ACO6JAOoABUoFigANSuUa5sANw6hABuWOig1lQqoAC8dPQA5Arwpan4WTkY6DZFJQAsAEypoPggoACi6A3oAFygAILolsSsiJCgVMigkLjGqKClbaWg8NCgiFQzdtDwlkwuADYrkFQm2SyCGKAA7vDmmyj1qAVIkBjIWGQrnFk8gUg3oACVUJZUAAPNiFAB8OFw2ikmWyuSo+VaTVM5isNjs9AAzM5mtVaqB6jZscVcRZrLZ7KUiaVnABtUqlAC61W6fQGwzGEymMzmCyWK2ZGy2Oz2MWgh2OWDOFyuxhurG+OSeLyQaH6Hx2kxcGFRQA)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
   * Because in noImplicitAny theres no parameters without type
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
People have asked us hundreds of times why we don't do this; the answer is that it's architecturally impractical to do this in a way that results in stable, performant checking results in anything other than toy programs. See e.g. https://medium.com/flow-type/what-the-flow-team-has-been-up-to-54239c62004f where the flow team has basically abandoned this feature.

The "infer from usage" refactor is available for this purposes.

**Comment by emilioplatzer** [comment]
Thanks @RyanCavanaugh. I apologize for bothering you with this. 

These also explains the point: 
   * https://github.com/microsoft/TypeScript/issues/34738
   * https://www.typescriptlang.org/play/?noImplicitAny=false&e=28#example/infer-from-usage-changes
