### ISSUE TITLE
Property  'length' does not exist on type 'never'

### ISSUE THREAD

**Issue by cesco69** [microsoft/TypeScript#38991]
**TypeScript Version:**  3.9.2

**Search Terms:**
property type never

**Code**

I have a set of basic function:
```ts
    export function isObject(value: any): value is Object {
      return value !== null && typeof value === 'object' && !isArray(value);
    }
    
    export function isNumber(value: any): value is number {
      return typeof value === 'number' && !isNaN(value);
    }
    
    export function isString(value: any): value is string {
      return typeof value === 'string';
    }
    
    export function isArray(value: any): value is Array<any> {
      return Array.isArray(value);
    }
    
    export function isNull(value: any): value is null {
      return value === null;
    }
    
    export function isUndefined(value: any): value is undefined {
      return value === undefined;
    }
    
    export function isNullOrUndefined(value: any): value is null | undefined {
      if (isNull(value) || isUndefined(value)) {
        return true;
      }
      return false;
    }
```
and a "special function" that check if a value is `null`, `undefined` or `empty` (empty string, 0 for number, empty array or empty object `{}`):
```ts
    export function isNullOrUndefinedOrEmpty(value: any): value is null | undefined | '' | [] | {} | 0 {
      if (isNullOrUndefined(value)) {
        return true;
      }
      if (isString(value)) {
        return value === '';
      }
      if (isNumber(value)) {
        return value === 0;
      }
      if (typeof value === 'number' && isNaN(value)) {
        return true;
      }
      if (isArray(value)) {
        return value.length <= 0;
      }
      if (isObject(value)) {
        return Object.keys(value).length === 0 && value.constructor === Object;
      }
      return false;
    }
```
when i use `isNullOrUndefinedOrEmpty()` typescript show the error:

> Property 'length' does not exist on type 'never', example:

```ts
    export function foo(myArray: Array<any>): Array<any> {
      if (isNullOrUndefinedOrEmpty(myArray)) {
        return myArray;
      }
      // on myArray: Property 'length' does not exist on type 'never'
      for (let i = 0, e = myArray.length; i < e; i++) {
        // ... some logic
      }
      return myArray;
    }
```

what i'm doing wrong?

**Expected behavior:**

No error: Property  'length' does not exist on type 'never'

**Actual behavior:**

Show error:  Property  'length' does not exist on type 'never'

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html?ssl=12&ssc=9&pln=12&pc=42#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWIhACgFsBPAQSigEMSAuOC6kgHipRID4BKexm19hzgBvALAAoOHEwI4BTAGcAckgA2qgPJQAqigAmwBJhTA9WgKJEwMEsXKUaXLiIlSpUYDCRRcpPiQBuVzgAX2CAenC4HDg-Bzo4AAUoCDBgWBI4AHJVYBQAcxgACyy4PQhgBTgUCHhQRXgYmzTskwA3dKzghGg5XPhMOABeOAAGABo4YGHY%20yYAOlyC4oDpOGYp1cwAam3nMUk3SLh507gFCCJp1Qh8zDRgsMOPLx9Z-yDxJ4kDNFUqDyIVAYbC4RQqdRaXQGIwmMxQSzWWxtKiqJDAehsEg8OAotHTRTVNSqOAAHzgqBhxlMZOypXJAG0ALq00a04RPIA)

**Comment by MartinJohns** [comment]
[Why are all types assignable to empty interfaces?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces)

> Types with no members can be substituted by `any` type.

`Array<any>` is compatible with the `{}` type. You use `isNullOrUndefinedOrEmpty(myArray)` to check your argument, and return if it matches. So according to the type system you checked that `myArray` is **not** an `Array<any>` (via the `{}` type), that means the only valid type left is `never`, and `never` has no `length` property.
