### ISSUE TITLE
Object.assign does not conclude correct type from second argumet in ternary operator

### ISSUE THREAD

**Issue by aghArdeshir** [microsoft/TypeScript#39002]
**TypeScript Version:**  4.0.0-dev

**Search Terms:** Object assign, spread

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
const production: boolean = true;

interface Icon {
    x: number;
    y: number;
    name: 'we' | 'you' | 'hello' | undefined;
}

const myBeautifulIcon: Icon = Object.assign(
    { x: 2, y: 2 },
    production ? { name: 'we' } : { name: 'you' }
)

console.log(myBeautifulIcon);
```
(code tested in nightly ts playground)

**Expected behavior:**
The code to be valid and `myBeautifulIcon` object have correct type. The correct type should be concluded from Object assign.

**Actual behavior:**
Error arised, saying that theconcluded type for `name` was string;

**Playground Link:**  
[https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200609&ssl=1&ssc=1&pln=14&pc=30#code/MYewdgzgLgBADgJxAEwK7CgS3ALhgIxBABsBTAQzBgF4YoFVSBuAKBczClIQDNzhSMAJKgqAbxYwpMAB54wqALb5uraTACe8pSoRrpYcotJ4A5AHdSpmAB8YpjSFTW7pgBalixEC5iowyKQ8HKTIrAC+bKLQMIoaAEIUqFg8qMQiuMKiNDAA8vgAVqQYAHTkEBCYAOZgABSS0mKyeABMADSarTDhbQ1SiCjoWOAwAPwwTYbGZpbW4TB4k0Ym9o7O3SwAlFHgECSkJd5VtXGJ5MmYqemim0xAA](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200609&ssl=1&ssc=1&pln=14&pc=30#code/MYewdgzgLgBADgJxAEwK7CgS3ALhgIxBABsBTAQzBgF4YoFVSBuAKBczClIQDNzhSMAJKgqAbxYwpMAB54wqALb5uraTACe8pSoRrpYcotJ4A5AHdSpmAB8YpjSFTW7pgBalixEC5iowyKQ8HKTIrAC+bKLQMIoaAEIUqFg8qMQiuMKiNDAA8vgAVqQYAHTkEBCYAOZgABSS0mKyeABMADSarTDhbQ1SiCjoWOAwAPwwTYbGZpbW4TB4k0Ym9o7O3SwAlFHgECSkJd5VtXGJ5MmYqemim0xAA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/35621
https://github.com/microsoft/TypeScript/issues/26792
https://github.com/microsoft/TypeScript/issues/16163

**More practical use case:**
![image](https://user-images.githubusercontent.com/5755214/84236297-abe39f00-ab0c-11ea-8ce2-d096f3e3ab70.png)

**Comment by Ardeshir81** [comment]
Just to make it slience:
[https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200609#code/MYewdgzgLgBADgJxAEwK7CgS3ALhgIxBABsBTAQzBgF4YoFVSBuAKBczClIQDNzhSMAJKgqAbxYwpMAB54wqALb5uraTACe8pSoRrpYcotJ4A5AHdSpmAB8YpjSFTW7pgBalixEC5iowyKQ8HKTIrAC+bKLQMIoaAEIUqFg8qMQiuMKiNDAA8vgAVqQYAHTkEBCYAOZgABSS0mKyeABMADSarTDhbQ1SiCjoWOAwAPwwTYbGZpbW5faz3TB4k0Ym9o7OMPMOTtaRAJRR4BAkpCXeVbVxieTJmKnpogdMQA](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200609#code/MYewdgzgLgBADgJxAEwK7CgS3ALhgIxBABsBTAQzBgF4YoFVSBuAKBczClIQDNzhSMAJKgqAbxYwpMAB54wqALb5uraTACe8pSoRrpYcotJ4A5AHdSpmAB8YpjSFTW7pgBalixEC5iowyKQ8HKTIrAC+bKLQMIoaAEIUqFg8qMQiuMKiNDAA8vgAVqQYAHTkEBCYAOZgABSS0mKyeABMADSarTDhbQ1SiCjoWOAwAPwwTYbGZpbW5faz3TB4k0Ym9o7OMPMOTtaRAJRR4BAkpCXeVbVxieTJmKnpogdMQA)

**Comment by j-oliveras** [comment]
You can also use `as const` since version 3.4:
```ts
    production ? { name: 'we' } as const : { name: 'you' } as const
    // or
    production ? { name: 'we' as const } : { name: 'you' as const }
```

**Comment by Ardeshir81** [comment]
Oo! That's a bummer.
Cause lots of times, typescript does things that "feels like" smart!
And that feeling in me made that expecttion that I wished typescript to conclude result type.
