### ISSUE TITLE
Feature proposal: TypeScript to follow code properly regarding optional properties

### ISSUE THREAD

**Issue by basickarl** [microsoft/TypeScript#39007]
The following code is deterministic:
```
interface Something {
    maybe?: () => void;
}

function run(isTrue: boolean): Something {
    const object: Something = {};
    if (isTrue) {
        object.maybe = (): void => {
            console.log('maybe');
        };
    }
    return object;
}

run(true).maybe();
```

Yet TypeScript does not follow the internal happenings of the run function knowing that the returned object *has* the maybe method which can be run (current error `Cannot invoke an object which is possibly 'undefined'.`).

Since this is deterministic, this *can* be programmed to be checked and quite frankly I am surprised that it does not in it's current state. This *would* mean that TypeScript would need to follow this object specifically throughout the entire check.

This does not include overloading, so please do not mention overloading.

**Comment by MartinJohns** [comment]
Duplicate of #9998.

**Comment by basickarl** [comment]
> Duplicate of #9998.

Thanks, I'll continue my rant on that one!
