### ISSUE TITLE
`enum` definition is lost when used inside a type, or with a type proxy?

### ISSUE THREAD

**Issue by dotansimha** [microsoft/TypeScript#39019]
**TypeScript Version:**  3.9.2

**Search Terms:** type, enum, typeof, proxy, import, `only refers to a type, but is being used as a value here`

**Code**

```ts
// 1
enum E {
  A,
  B,
  C
}
type Working1 = typeof E;

// 2
import P2 = E;
type Working2 = typeof P2;

// 3
type P1 = E;
type NotWorking1 = typeof P1;

// 4
type T = {
  f: E
}
type NotWorking2 = typeof T['f'];
```

**Expected behavior:**

Enum definition should be preserved somehow? or `typeof` should be able to use types that are pointing to an `enum`? 

**Actual behavior:**

It seems like when `enum` is being used in a type, or as a proxy type, the ability to execute `typeof` is being lost. 

[Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=19&pc=1#code/PTAEEYCgFMDsFcC2oCioDelSgIIBotQAhA7AYUgF9IAXATwAdpQB1AewCcBrAS1gHNwoALyh6TNgDNUAbkiQQoAEyQeiBpxqgACkpGzajZu259+e0eOhSdSuQrABmQ0x1DRKOVdAA5NjRNeAXcxIxttcHtFABYXZgAVfUxsSQAuVCo4339AswtQiWl4gG0AcklSgF0ZIA)

**Related Issues:** 
:(

**Comment by RyanCavanaugh** [comment]
`typeof` gets the type of a value, and `type` only makes a type. You can make a value/type combination with `import`, as shown.
