### ISSUE TITLE
Rename imports does not pick up `.mjs` as a trigger

### ISSUE THREAD

**Issue by bnb** [microsoft/TypeScript#39012]
**TypeScript Version:**  3.9.3 (via [VS Code Insiders](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/package.json#L157))

**Search Terms:** `mjs`

**Code**

> Rename esm.js to esm.mjs

**Expected behavior:**

.mjs to trigger "rename imports" (VS Code's prompt implementation of this is powered by TS under the hood).

**Actual behavior:**

.mjs does not trigger "rename imports" prompt.

**Comment by mjbvz** [comment]
I believe we send over mjs file to TS Server but they are never included in any project so rename imports would have no effect on them

**Comment by RyanCavanaugh** [comment]
Track at #27957
