### ISSUE TITLE
Variable narrows type to assigned value and ignores type declaration

### ISSUE THREAD

**Issue by pgraham** [microsoft/TypeScript#39028]
**Search Terms:** have no overlap

**Code**
I have a script with a number of flags that I use to control the behaviour. Since I run this script rarely and need to open and read it every time, I just define the flags inline rather than passing them on the command line. I recently tried to add type information to these flags so that I can't do something inadvertent with a typo. However, when I do this, the compiler interprets the type of the  variable as the assigned value rather than the declared type, resulting in errors when branching based on the flag.

```ts
type TakeAction = boolean | 'dry-run';

const DO_DELETE: TakeAction = 'dry-run';

if (DO_DELETE) { // Error if DO_DELETE === false
  console.log(
    DO_DELETE === 'dry-run' ? 'Would delete ' : 'Deleting ', // Error if DO_DELETE === true
    'some items'
  );

  if (DO_DELETE === true) { // Error if DO_DELETE === 'dry-run'
    // Do the delete
  }
}
```

 I can fix this by assigning the value as:
```
const DO_DELETE: TakeAction = ((): TakeAction => 'dry-run')();
```

**Expected behavior:**
Code compiles

**Actual behavior:**
Compiler outputs error: This condition will always return 'false' since the types 'string' and 'boolean' have no overlap.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=16&pc=2#code/C4TwDgpgBAKghgawgQQMbAJYHsB2UC8UARllgDYRx4A+UA5ACYBOIAtEwK450DcAUH1S4AzsCgARAPIB9cQFEAMnJhyC9Zm07d+Aeh0UxU2YuVyAXLEQp02PIUYt2XXlD1QAynAC20CEyZYTHx6QjiiEjLySioW8EhomLhqABTJAJSxVgm2BAB8UMCcEGnpPK46sAAWGMJQAO6BCMICGABmUMlGUaZpUADefFBQocLkEAB0ZFgA5smDQxHG0ar4q+qOWnRQAPz0AOpYHGQMUAwQBtBbFnTi5xCYONP0ADTzQ3SjPlAYwBBewnR5ml+PM2h0uiYVAQ1oUOMV+m9yhIsAVKtAzhd5gBfPhYoA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; the code is indistinguishable from having a bug and is treated as such.
