### ISSUE TITLE
api compile typescript code for javascript

### ISSUE THREAD

**Issue by GlauberF** [microsoft/TypeScript#39021]
first, i apologize if i'm writing this request in the wrong place, i'm new here.
I want to create a call to my API node, passing my typescript code and have it compile and return the compiled code to me in javascript.
what function / method can i use from typescript?
or should I use https://www.npmjs.com/package/ts-node

## Example
https://www.typescriptlang.org/play/

**Comment by MartinJohns** [comment]
[Using the Compiler API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API)

**Comment by GlauberF** [comment]
thank you @MartinJohns 
in the example of the compile function, it passes an array of files to be compiled, as I would do, if instead of passing files, pass my code in string format?

would you use ts.transpileModule?

**Comment by DanielRosenwasser** [comment]
Yup, I believe `transpileModule` is what you're looking for

**Comment by DanielRosenwasser** [comment]
btw https://github.com/microsoft/TypeScript-Website/tree/v2/packages/playground has the source for the playground in it

**Comment by GlauberF** [comment]
thanks, it helps me.
