### ISSUE TITLE
a list of escaped character codes is displayed instead of part of the path

### ISSUE THREAD

**Issue by vadimmos** [microsoft/TypeScript#39027]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.9.4

**Search Terms**
- import path
- hover / quick info
---

- VSCode Version: 1.46.0
- OS Version: Linux Mint 19.3 x64 5.3.0-59-generic

Steps to Reproduce:

1. In the import block, specify the path to the module.
2. Hover the cursor over the specified path.
3. If the path contains non-Latin characters (in my case, Cyrillic), a list of escaped character codes is displayed instead of plain text.

The situation is similar in the error text in the terminal.

Does this issue occur when all extensions are disabled?: Yes

![vscode_bug_0](https://user-images.githubusercontent.com/14206443/84324649-abd1b680-ab81-11ea-9898-97f34afaaac3.png)
![vscode_bug_1](https://user-images.githubusercontent.com/14206443/84324477-68774800-ab81-11ea-9113-ca7056004561.png)

**Comment by mjbvz** [comment]
To repo:

1. `git clone https://github.com/mjbvz/ts-39027`
1. In the project, open `index.ts` and hover over the import


TS Trace: 

```
[Trace  - 18:38:51.910] <semantic> Sending request: quickinfo (122). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/😀/index.ts",
    "line": 1,
    "offset": 22
}
[Trace  - 18:38:51.913] <semantic> Response received: quickinfo (122). Request took 4 ms. Success: true 
Result: {
    "kind": "module",
    "kindModifiers": "",
    "start": {
        "line": 1,
        "offset": 19
    },
    "end": {
        "line": 1,
        "offset": 24
    },
    "displayString": "module \"/Users/matb/projects/san/\\uD83D\\uDE00/a\"",
    "documentation": "",
    "tags": []
}
```

**Comment by ShuiRuTian** [comment]
Not pretty sure this issue belongs to TS.

In session.ts, in function `public send(msg: protocol.Message)`, 
formatMessage would use JSON.stringify(msg), finally produce `msgText` like follows to write
"Content-Length: 324

_{"seq":0,"type":"response","command":"quickinfo","request_seq":148,"success":true,"body":{"kind":"module","kindModifiers":"","start":{"line":1,"offset":19},"end":{"line":1,"offset":29},"displayString":"module \"c:/Users/XXX/Desktop/VS Code Dubug/Node/TypeScript/src/\\u4E2D\\u6587/tmp\"","documentation":"","tags":[]}}_
"

It seems VSCode use italic text part as an object directly, but it should be a JSON string.
