### ISSUE TITLE
Stop using an offensive color for error messages

### ISSUE THREAD

**Issue by blacklistisnotracist** [microsoft/TypeScript#39020]
I'm Native American and I'm offended every time I see an error message displayed in red. Can we change that to something else?

https://github.com/microsoft/TypeScript/blob/a72ed0a2f55681f9d8e6a1125e8e9850ce1c4d9c/src/compiler/program.ts#L372

**Comment by RyanCavanaugh** [comment]
Unfortunately we're not able to deal with bad-faith trolling at this time.
