### ISSUE TITLE
If exported variable is renamed, tsc will generate code with a syntax error

### ISSUE THREAD

**Issue by gdh1995** [microsoft/TypeScript#39022]
**TypeScript Version:**  typescript@4.0.0-dev.20200611 (also 3.9.5)

**Search Terms:** exported variable renamed

**Code**

```ts
// a.ts
let foo = 1
export { foo as fooValue }
export const testFoo = (val: number) => {
  if (val <= ++foo) {
    return val
  }
  return foo
}
```

And then run this in a terminal:

``` bash
npx tsc a.ts && cat a.js
```

**Expected behavior:**

The command should output:

``` JavaScript
"use strict";
exports.__esModule = true;
exports.testFoo = exports.fooValue = void 0;
var foo = 1;
exports.fooValue = foo;
exports.testFoo = function (val) {
    if (val <= (exports.fooValue = ++foo)) {
        return val;
    }
    return foo;
};
```

**Actual behavior:**

The actual output is as the below, and `require('./a.js')` in Node.JS throws a `SyntaxError`

``` javascript
"use strict";
exports.__esModule = true;
exports.testFoo = exports.fooValue = void 0;
var foo = 1;
exports.fooValue = foo;
exports.testFoo = function (val) {
    if (val <= exports.fooValue = ++foo) {
        return val;
    }
    return foo;
};
```

If I run `require("./a.js")` in `node`, then it outputs:
```
Thrown:
R:\working\2\a.js:7
    if (val <= exports.fooValue = ++foo) {
        ^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid left-hand side in assignment
```

**Playground Link:** https://www.staging-typescript.org/play?target=1&module=1#

**Related Issues:** None

**Comment by gdh1995** [comment]
Um, I found another related bug: `val <= foo--` will be transformed into `val <= exports.fooValue = foo -= 1` - both a SyntaxError and a logic mistake, because the old value of `foo` is aborted.

**Comment by gdh1995** [comment]
@a-tarasyuk Hello, there's still a related case which seems not fixed:

> Um, I found another related bug: `val <= foo--` will be transformed into `val <= exports.fooValue = foo -= 1` - both a SyntaxError and a logic mistake, because the old value of `foo` is aborted.

In the test files of your PR, it looks like that `y <= x--` will be transformed into `y <= (exports.x = x -= 1)` ...

Should I open a new issue for it?

**Comment by rbuckton** [comment]
Good point, I hadn't checked that. In our System transform we do the correct thing and add/subtract ` from the result, but that seems to be missing in our commonjs/amd emit.

**Comment by rbuckton** [comment]
#42676 addresses @gdh1995's concerns, but is likely too big of a change for 4.2. I may just make another one-off PR for this specific fix.
