### ISSUE TITLE
A syntax for function declarations to "implement" types (like `const C: React.FC<Props> = (props0) => ...`)

### ISSUE THREAD

**Issue by gfx** [microsoft/TypeScript#39039]
## Search Terms

function,implements,type,interface

## Suggestion

I'd like to make a `function` to implement types or interfaces. It is partially possible for variable declaration (e.g. `const f: T = () => ...`) but it is slightly different from what I'm issuing.

## Use Cases & Examples

When making a React component.

It is a good practice to use `React.FC<Props>` when you make a React component like this:

```typescript
import type React from "react";
type Props = { ... };
export const Foo: React.FC<Props> = (props) {
  ...
};
```

It's useful because a function component with a wrong return type doesn't compile. However, I think it's natural if I can declare implementing types for `function` declarations like this:

```typescript
function Foo implements React.FC<Props> (props) {
  ...
}
``` 

(syntax doesn't matter; just for example)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #34319

**Comment by gfx** [comment]
Cool. A use-case for `React.FC<Props>` is also explained at https://github.com/microsoft/TypeScript/issues/34319#issuecomment-623082842
