### ISSUE TITLE
"is assignable to the constraint of type but could be instantiated with a different subtype of constraint" error with assetion function

### ISSUE THREAD

**Issue by mateja176** [microsoft/TypeScript#39036]
**TypeScript Version:**  3.9.4

**Search Terms:**

`is assignable to the constraint of type`

**Code**

```ts
const isNil = <A extends any>(a: A) => a === undefined || a === null;

type DeepRequired<O extends {}> = {
  [key in keyof O]: O[key] extends {}
    ? DeepRequired<O[key]>
    : NonNullable<O[key]>;
};

export function assertNonNullable<O extends {}>(
  object: O,
): asserts object is DeepRequired<O> { // throws
  Object.entries(object).forEach(([key, value]) => {
    if (typeof value === 'object' && value !== null) {
      assertNonNullable(value);
    }
    if (isNil(value)) {
      throw new Error(`Key ${key} is required, but the provided value is nil`);
    }
  });
}

interface MaybeA {
  a?: number;
}

const a: MaybeA = { a: undefined };

assertNonNullable(a);

const b = a.a;

```

**Expected behavior:**

No error is thrown

**Actual behavior:**

The following error is thrown:

```
A type predicate's type must be assignable to its parameter's type.
  Type 'DeepRequired<O>' is not assignable to type 'O'.
    'DeepRequired<O>' is assignable to the constraint of type 'O', but 'O' could be instantiated with a different subtype of constraint '{}'.
      Type 'O[key] extends {} ? DeepRequired<O[key]> : NonNullable<O[key]>' is not assignable to type 'O[key]'.
        Type 'DeepRequired<O[key]> | NonNullable<O[key]>' is not assignable to type 'O[key]'.
          Type 'DeepRequired<O[key]>' is not assignable to type 'O[key]'.
```

**Playground Link:** 

[Link](https://www.typescriptlang.org/play?ts=4.1.0-beta#code/MYewdgzgLgBAlhAcnANjAvDAPAQRgUwA8p8wATCGAQzAE8A+ACioC4YcBKDe6jdTAK7l8AMzhh8ZGAB9pvfpjACUKANwBYAFBaotAA74YifNEkYYAbxgBtANb5a8MDGgAncQHMZMJQFsARviuALpsSireQmSi4mZybp7efoGu3v4gICj4NN7GpmTWwbkmJFIAvlo6+oYAIvj4egBK+ACOAnCuklgA8gTEpBRGJZI8mBZaMDb2juIw0yAiMN2hS3YORUQk5JR5pRMwAPwwdQ3NbR1d3Wu0wfT7bIjgiMooVP5ZPde3GpplP1qgSCwBA4VyuKiOTCMED+ABW+GAUAewykcl2kkKHDYMPhiPgOxRhW47DBEIAdCDSbRoXCEVAOJVNEQ9CBXLAREJEXBwNQIBAglBHmBnio3h9epsBgT8kx9ji6WxugAaLQAelVMAAAlAIABaOAeMCs-BaLG8-lsyjyvEIY71JqtdqdMg9HhWdUwKAAC1cIAA7pQ-V7SFqdfrDcb8TBOr4QAA3ST7bq0xFk0hQdwmGm4+lkkSsgCiVGAXsYjGuSpgcaoKAE+GCXHQbv2kzgi0YugMCyrNbrfEwAHJrVABzAAGRjnu1wwAQn4PheXHGmkmq-g7cp4Op1enHCXLbXU7recLxdLVD5AqFIte73wHB+h5gZQIKH5lgPa4vFsFTxeYvwRgdzrB9P2fA8KhXVc2xgRgEGQFAgN7e99ygtdvV9P0fHwLCCzBVlGAAAwAaQcGAABILGmF9bU6c5nUrfwBFgb1DD0X04zgaIpGAwxbTAVBCNAtDwKgsphMggFwGgag2GaUBXBdBIwA8StwjQOR5NZJSM08NSBACIJ6FGSxZIXCI-kZb8rz-UU72YYSpKBGB-HMKgySof5NA9AAFTpOJAAQIEZD1ARk+DUHMXA+i2QYaAYZg2E4YkqH7GAohiCRUTkVKFHMtQQo1TtantM4nUuGKpUsMoTOXD1JmuJw5gcbtlkVL5Ku2aq1Q1NcjhOB16MuL47m83rVweWzb3FEafg9SztDGvoWTZGAOTALkeWstlr3-O8ek6wYLBqxgetXYdFRVJazW2nUYGHKMBrKi4XW6N0YA9DD-WCpbJmTHM0zAXSs2HDgT1cIsSzLCsj3rRtm1+6D22K7teLSocUxHcdJzRudFEXD9Ea-S8dqmgCkN3ObxsmSD6qR2CIsQ3i90Jun0J9f1sNw-DXCI0jHEo6iozo8qyEY5jPWDGB2PjLizDR-jBOEtnRLp8SqdEs7xBIVwRGLQwAFkIUCPA6vGqgDjCAyUg1ySlrC2BWBgI3aBN8wrCdjKxCy58vI9W7drsrIHL9jUHZctyPNUIA)

**Related Issues:** 

#29049

**Comment by fatcerberus** [comment]
It seems that the root of the issue is that, since `O` is an unbound type variable, TypeScript doesn't actually know `DeepRequired<O>` is related to `O` (it *does* know it's related to `{}` but this isn't enough, as the error message proves).  For that the compiler would need to do some kind of higher-level reasoning (i.e. reasoning about the generic type alias *itself* rather than a specific instantiation of it), which it can't currently do.

My suspicion is therefore that this is probably a design limitation.
