### ISSUE TITLE
Unnamed Function Argument Types

### ISSUE THREAD

**Issue by k-koehler** [microsoft/TypeScript#39045]
##  Search Terms

unlabelled, function, types, arguments

## Suggestion

Consider c/cpp-style header files:

```c
int my_function(int, double, char[]);
```

The ability to omit the argument names would be useful in typescript in scenarios like:

```typescript
function myFunc(callback: (value1: SomeType, value2: SomeOtherType) => void)){
   ...
} 
```

Where we could just do:

```typescript
function myFunc(callback: (:SomeType, :SomeOtherType) => void){
  ...
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #3693, #3081, etc
