### ISSUE TITLE
DOM not imported

### ISSUE THREAD

**Issue by R00tS3c** [microsoft/TypeScript#39040]
**TypeScript Version:**  3.7.x-dev.201xxxxx
TypeScript: 3.9.5
Node.js: v12.18.0
NPM: 6.14.4

**Search Terms:**

**Code**
```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext",
	  "es2017"
    ],
	"sourceMap": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
	"downlevelIteration": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noEmit": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "strictFunctionTypes": false,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "jsx": "preserve",
    "strict": false,
    "isolatedModules": true
  },
  "include": [
    "src"
  ]
}
```

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
To build app with working window, localstorage and document

**Actual behavior:**
`Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.  TS2584

    4 | import App from "./App";
    5 |
  > 6 | ReactDOM.render(<App />, document.getElementById("root"));
      |                          ^`
**Playground Link:** 

**Related Issues:** 

Yes i have looked every similar issue here and on stackoverflow but nothing working

**Comment by RyanCavanaugh** [comment]
I can't reproduce the error given the information provided. How are you invoking `tsc` ? Can you share a repo or something that reproduces the issue?

**Comment by R00tS3c** [comment]
https://github.com/PoorlyDefinedBehaviour/discord-clone-frontend i have tried with importing @type/node and some other but still same

**Comment by R00tS3c** [comment]
And ?

**Comment by RyanCavanaugh** [comment]
@R00tS3c I cloned the repo, ran `npm install`, and ran `tsc` without any errors

It doesn't appear that you're running into any TypeScript bugs; this sort of problem is generally caused by a misconfiguration. Please refer to other support channels for follow-up; we are not able to assist people 1:1 with project setup.
