### ISSUE TITLE
support custom moduleResolution

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#39041]
## Search Terms

esm deno moduleResolution
## Suggestion

Support custom moduleResolution
## Use Cases

deno, nodejs-esm has different moduleResolution. Maybe we should support users to define custom moduleResolution.

for example:

```json
{
  "compilerOptions": {
    "moduleResolution": "./node_modules/node-esm-ts-module-resolution"
  }
}
```

**Comment by RyanCavanaugh** [comment]
Duplicate #18896
