### ISSUE TITLE
Types defining `Symbol.hasInstance` should be eligible to use with the `instanceof` operator

### ISSUE THREAD

**Issue by lazytype** [microsoft/TypeScript#39064]
**TypeScript Version:**  3.9.4

As specified here, https://tc39.es/ecma262/#sec-instanceofoperator, it should be sufficient for an object to define a function for the `Symbol.hasInstance` well-known symbol in order to be used as the right-hand side of the `instanceof` operator.

It seems like this was intended to be implemented based on these comments: https://github.com/microsoft/TypeScript/pull/12728#issuecomment-269801430
but for whatever reason that didn't happen it in the PR

**Search Terms:** Symbol.hasInstance

**Code**

```ts
({}) instanceof {[Symbol.hasInstance]: () => true}
// Running this in the browser evaluates to `true`
```

**Expected behavior:**
No type-errors

**Actual behavior:**
```ts
({}) instanceof {[Symbol.hasInstance]: () => true}
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!! error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.
```

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=1&pc=51#code/BQbwvglABAlgdgZwC4EM4GMCmB7AZlEAbQGUBPAWwCNsAbAOgAsUEBJRVDTAXQC4phoAXgB8UJACcArpjBA)

**Related Issues:**

**Comment by lazytype** [comment]
I have a tested and working branch that implements this proposal here: https://github.com/lazytype/TypeScript/commit/0c226a775f63f4dd97f6a65422707d4231787188

Holding off on creating a PR until this issue gets tagged with the "Backlog" milestone, per the contributor guidelines.

**Comment by ExE-Boss** [comment]
See also: <https://github.com/microsoft/TypeScript/issues/17360>

**Comment by rotu** [comment]
The typescript compiler also spuriously complains when the lhs of `instanceof` is not an object:

```
class MyNumber {
  static [Symbol.hasInstance](x:any) {
    return (typeof x === 'number');
  }
}

console.log(1 instanceof MyNumber);
```

It gives this error:

> The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.

**Comment by shrinktofit** [comment]
Why was this issue marked as "Suggestion"? I think it should be labeled as bug. @RyanCavanaugh

**Comment by MichaelMitchell-at** [comment]
> I have a tested and working branch that implements this proposal here: [lazytype@0c226a7](https://github.com/lazytype/TypeScript/commit/0c226a775f63f4dd97f6a65422707d4231787188)
> 
> Holding off on creating a PR until this issue gets tagged with the "Backlog" milestone, per the contributor guidelines.

❤️ Thanks for finally fixing the bug @rbuckton. I can finally delete this branch.
