### ISSUE TITLE
Negated instanceof operator, !instanceof

### ISSUE THREAD

**Issue by kshetline** [microsoft/TypeScript#39062]
## Search Terms

instanceof, negated, negate

## Suggestion

I've recently started using Kotlin. The Kotlin equivalent of `instanceof` is `is`. Checking if an object belongs to a class looks like this:
```kotlin
obj is MyClass
```
One nice convenience of the `is` operator is that it can be negated like this:
```kotlin
obj !is MyClass
```
While I realize this isn't an earth-shattering convenience, it's certainly more elegant than:
```kotlin
!(obj is MyClass)
```
My suggestion is that TypeScript allow similar negation of `instanceof` like this:
```text
obj !instanceof MyClass
```
...which could easily and safely be transpiled to the `!(obj instanceof MyClass)` form.
## Use Cases

The use case is simply to have a more concise and elegant way to negate `instanceof`.

## Examples

(See above)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x?] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). (I'm not completely sure that this (6) "Align[s] with current and future ECMAScript proposals", having not read every such proposal, and while I don't *think* this proposed infix operator would (8) "[add] expression-level syntax", at least any more than recent additions like `??`, I'm not absolutely certain.

**Comment by RyanCavanaugh** [comment]
This is a runtime feature. 

>  at least any more than recent additions like `??`

That feature was developed through the TC39 committee, not from TypeScript

**Comment by kshetline** [comment]
`??` may not have originated with TypeScript, but TypeScript now supports the null coalescing operator via transpiling for older versions of JavaScript which don't natively support it -- and doing *that* does not require runtime support, nor would my proposal require runtime support.

**Comment by RyanCavanaugh** [comment]
The point is that, like `??`, `!instanceof` should be originated with TC39, not TypeScript.

You can click through to that label and see dozens of suggestions for other downlevelable runtime syntax. We're quite consistent on this.
