### ISSUE TITLE
Could you please rename master branch and remove references to problematic words?

### ISSUE THREAD

**Issue by blacklivesmatterplease** [microsoft/TypeScript#39070]
Words such as master, slave, blacklist and whitelist are not suitable due to the deep history associated with racism.
They can be more accurate and precise than they are currently.

Golang team has already removed the use of those words in their code along with few others - https://www.reddit.com/r/golang/comments/gy9ylr/go_has_removed_all_uses_of_blacklistwhitelist_and/

There are other google projects which have done the same.

Here is a tweet from the github CEO - https://twitter.com/Una/status/1271180494944829441
Rust team is planning to do it as well.

There are many more projects moving to remove racism from the code. Would you please consider doing the same for typescript?

PS - Historical context for main - https://www.nakasendoway.com/the-japanese-family-system/

Please consider alternatives such as canary, develop or edge.

**Comment by RyanCavanaugh** [comment]
I'm 99.9% convinced this is a sock puppet for the user who logged #39020. Someone with an account more than a day old can raise this issue around specifics if they like, and certain things are already in flight, but we won't be engaging further with this user.
