### ISSUE TITLE
How to integrate into current angular workflow

### ISSUE THREAD

**Issue by matthiasg** [microsoft/TypeScript#3907]
Are there any best practices in how to extend an existing Angular/Browserify application with Typescript ?

My main issue is that Angular uses DI but Typescript seems to remove code that is just imported but not used (and depending on future optimization efforts just mentioning the imported variable might be eliminated as dead code). This makes it quite cumbersome to migrate towards TS.

Any tips or workarounds ?

Background:

I am currently trying to change our client side portion of a larger angular webapp to use typescript where it makes sense. its current setup using gulp and browserify.

I initially thought simply adding a browserify module such as tsify would be enough to let get my feet wet with typescript in certain places. we are not planning on converting everything over from js to ts (just renaming is not good enough since i have to add definitions to require etc and all whitespace in the generated files change so line numbers are not compatible and map files have some issues).

**Comment by jods4** [comment]
With the old syntax you had to use `///<amd-dependency>` to import a module for its side-effects and not have it removed.
With the new es6 syntax it just works `import "side-effects"`.

**Comment by matthiasg** [comment]
I tried that syntax too but the resulting file was empty .. Maybe it doesn't work with tsify ... 

-----Original Message-----

**Comment by napalm684** [comment]
Sorry I know this is a little dated but has there been any luck here?  I too am trying to get tsify to import angular via the angular.d.ts file with no luck.  I have been scouring the net today with not much luck in seeing anyone able to get it work with tsify.
