### ISSUE TITLE
ESNext - public instance field definitions get removed or moved to constructor

### ISSUE THREAD

**Issue by jeremychone** [microsoft/TypeScript#39082]
**TypeScript Version:** 3.9.5

**Search Terms:** esnext contructor class fields 

Currently, when target set to `esnext`, public instance fields definition get removed, and public fields assignment get moved to constructor.

This transformation unnecessarily deviates emitted code from source one, as well as introducing some runtime divergence. 

**Code**
```ts
class TestClass {
  static ERR = 'rdr';

  a: any;
  b = 3;
  c: any;
  #d: any;

  setC(c: any) {
    this.c = c;
  }
}
```

**Expected behavior:**

Emitted code should be (+/- empty lines)

```ts
class TestClass {
  static ERR = 'rdr';

  a;
  b = 3;
  c;
  #d;

  setC(c) {
    this.c = c;
  }
}
```

**Actual behavior:**

```ts
class TestClass {
    constructor() {
        this.b = 3;
    }
    #d;
    setC(c) {
        this.c = c;
    }
}
TestClass.ERR = 'rdr';
```

**Issues:**

for `const tc = new TestClass()`

1) From an optics point of view, it looks like a lost opportunity to do less transformation when possible and support targetted specifications as natively as possible. 

2) But more importantly, the runtime behavior is not preserved between native ES field support and typescript emitted code, as the non-assigned fields won't be in the enumerable list of properties for the object (contrary to the native JS support)

    - For example, with the `TestClass` above. 

```ts
const tc = new TestClass();

// EXPECTED: with native node 14 class field support
Object.keys(tc); // ['a', 'b', 'c']

// ACTUAL with typescript esnext emitted code
Object.keys(tc); // ['b']
```

3) Also, from a micro-performance point of view, it seems that the emitted code won't allow JS runtimes for potential [Fast properties / HiddenClass optimization](https://v8.dev/blog/fast-properties). (although that this could be considered negligeable or speculative at this point)

**My 2 cents**

While this seems to be mostly a cosmetic issue, I think that the 'runtime behavior mismatch' might become a bigger issue over time as TypeScript developers might rely on the erroneous behavior in their code. 

Also, cosmetic aside, there is a non-negligible benefit having the emitted code as close as the source code as possible, especially for runtime debugging / quick-edit-and-restart occasional dev-ops workflow.

**Comment by RyanCavanaugh** [comment]
You need to set `useDefineForClassFields` to `true`

**Comment by jeremychone** [comment]
@RyanCavanaugh Sorry, completely misssed this one. 

Yep, once this is set, get clean emitted code. Even respect the field declaration order! Thanks!

```ts
class TestClass {
    static ERR = 'rdr';
    a;
    b = 3;
    c;
    #d;
    setC(c) {
        this.c = c;
    }
}
```

I can close this issue then.
