### ISSUE TITLE
"Number.isFinite" and "Number.isInteger" do not filter out values as a predicate

### ISSUE THREAD

**Issue by goodwin64** [microsoft/TypeScript#39090]
**TypeScript Version:**  3.9.2

**Search Terms:** isFinite, isInteger, filter, callback, predicate, null values

**Code**

```ts
const nums = [1, 2, 3, null, 5];
const filteredFinite = nums.filter(Number.isFinite);
const filteredIntegers = nums.filter(Number.isInteger);
```

**Expected behavior:**
```ts
const filteredFinite: number[]
const filteredIntegers: number[]
```

**Actual behavior:**
```ts
const filteredFinite: (number | null)[]
const filteredIntegers: (number | null)[]
```

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=2&ssc=7&pln=2&pc=21#code/MYewdgzgLgBGCuBbCMC8MDaBGANDATHgMx4IA2ZeArALoDcAsAFCiSwBmAlmVAKYBOvACYAxTmE580cJBAB0XHgIAUAOSQAjAXM4QxEvgEpGLcNBiK+goQEkwfAOYCU6BMgXcrazdt13HAsbMzKwQIGS8cmQgDsqWAsL6krxBppDhkdGx8db+vE78EKlAA

 

**Related Issues:** not found

**Comment by fatcerberus** [comment]
As far as TS is concerned, it's just like any other function, a black box that returns true or false.  There's no special case in the compiler that says using `Number.isFinite` in particular will remove all the nulls.

**Comment by RyanCavanaugh** [comment]
Type guards are only correctly type guards if they return `true` for *every* value of the tested type, not *some* values of the type.

See #15048 for supporting type guards that only identify a subset of their type.

**Comment by fatcerberus** [comment]
Ah right, because otherwise `!Number.isInteger(x)` implies that `x` is *not* a number and would be narrowed as such.  I forgot that that works both ways when I made the above suggestion.
