### ISSUE TITLE
Update downlevel-dts for tuple enhancements in 4.0

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#39099]
* Named tuple members (strip the names)
 * Variadic tuples (TODO: What do we need to cover?)

**Comment by jdmichaud** [comment]
I see you were not sure [Variadic Typle Types](https://github.com/microsoft/TypeScript/pull/39094) were impacting older TS versions. Do you have a definitive answer on this? Did Variadic Tuples be managed by downlevel-dts? I don't see any change related to this in https://github.com/sandersn/downlevel-dts/pull/38.

**Comment by sandersn** [comment]
Variadic tuple types *definitely* do not work in older TS versions. But downlevel-dts is operates only on syntax, and converting a single signature with tuple kinds to a set of overload signature is extremely complex, even with semantic information.

Basically, users of downlevel-dts need to test the generated d.ts files to make sure that the downlevelled code is valid.
