### ISSUE TITLE
Type inference ignoring union type when initial value is specified

### ISSUE THREAD

**Issue by bdwain** [microsoft/TypeScript#39092]
**TypeScript Version:**  3.9.2 and Nightly build

**Search Terms:**
type inference ignoring union
type inference wrong
type inference side effect
type inference narrowing

**Code**

```ts
let foo: number | null = null;

foo; //type is null. a little odd, but that's fine since it can't not be null now

function blah() {
  foo = 123; //foo is correctly inferred as `number | null`
}
blah(); //this should "widen" the type back to the original declared type of `number | null`, as blah could have side effects

foo; //type is inferred to be null, incorrectly. it should be `number | null` (not just `number`)
```

**Expected behavior:**
The type of let variables should not be narrowed to their known values (or at least not after any functions have run, as all functions can potentially have side effects). 

In this example, foo's type should be inferred as `number | null` at the end, not `null`, which is incorrect.

**Actual behavior:**

let variable inferred types are narrowed and end up being incorrect if the run time type changes in a side effect

**Playground Link:** https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200615#code/DYUwLgBAZg9jBcEB2BXAtgIxAJwgH2RWGAgF5DiBuAWACg7YYb7aoUkBjMASxiQgzAAhgAsAFAEpEANxjcAJhADedCNDhkIARgBMAZmYBfOoNGTmDOJSA

**Related Issues:** None

**Comment by RyanCavanaugh** [comment]
Duplicate #9998

**Comment by fatcerberus** [comment]
#9998 goes into detail about this, but suffice to say your proposal would mean *all* function or method calls would have to discard *all* local narrowings, which would be extremely painful in practice.

**Comment by bdwain** [comment]
interesting. I see why it's a tough tradeoff. Thanks for explaining. I'll close this in favor of that one.
