### ISSUE TITLE
Converting unions of types inferred from JSON modules to intersections fails

### ISSUE THREAD

**Issue by third774** [microsoft/TypeScript#39106]
**TypeScript Version:** 3.9.5

**Search Terms:** `json dynamic import`

**Code**

`foo.json`

```json
{
  "foo": "foo"
}
```

`bar.json`

```json
{
  "bar": "bar"
}
```

`index.ts`

```tsx
const foo = import("./foo.json");
const bar = import("./bar.json");

export type UnionToIntersection<U> = (
  U extends any ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never;

export type PromiseType<P> = P extends Promise<infer T> ? T : never;

type Foo = PromiseType<typeof foo>;
type Bar = PromiseType<typeof bar>;

type UnionedJsonModules = Foo | Bar;

// Unions of types inferred from JSON modules being converted to
// intersections worked in 3.8.3 but resolves to never in 3.9.5
export type X = UnionToIntersection<UnionedJsonModules>;
```

**Expected behavior:**

`type X` should be:

```tsx
{
    default: {
        foo: string;
    };
    foo: string;
} & {
    default: {
        bar: string;
    };
    bar: string;
}
```

**Actual behavior:**

`type X` is `never`

**Playground Link:** N/A since playground doesn't support multiple files. I've created a repo with the example code [here](https://github.com/third774/json-modules-typescript-bug)

**Comment by RyanCavanaugh** [comment]
"Union to intersection" is not a well-defined operation ([thread](https://twitter.com/SeaRyanC/status/1184862011043151872)) and `never` is an expected outcome of using it
