### ISSUE TITLE
Opting Out of Implicit Interfaces

### ISSUE THREAD

**Issue by gravidThoughts** [Microsoft/TypeScript#3910]
It would be nice to have a compiler flag/annotation which would prevent the compiler from using implicit interfaces.

This follows the spirit of this [excellent paper](http://janvitek.github.io/pubs/ecoop15a.pdf), which proposes an extension for TypeScript to allow programmers to opt into a stronger typing system.

I understand that support for legacy systems is a major driver for the design of TypseScript.  

I am a lead in a new major enterprise development project that is using TypeScript from the beginning. We don't have any legacy code to support. 

Moving forward, I hope design decisions will take into account new systems development, and give the developers more powerful design options which are feasible because they are not constrained by legacy code.

**Comment by nycdotnet** [comment]
When you say implicit interfaces, do you mean the interfaces declared in lib.d.ts?  If so, you can pass the --noLib switch which will require you to provide your own interfaces for essentially everything (and you can start from the production lib.d.ts to create your own).

**Comment by gravidThoughts** [comment]
I mean that the following is allowed by the compiler.

```typescript
interface IMagazineArticle {
    title: string;
    author: string;
    ...
}

class Book {
    constructor(public title: string, public author: string)
}

function getMagazineArticle(article: IMagazineArticle): IMagazineArticle{
    return new Book('Clean Code', 'Martin Fowler')
}
```

This is allowed because the Book class implicitly implements the IMagazineArticle interface. It is designed this way, I believe, in order to make it easier to use interfaces with existing legacy code.

For those who have no legacy code, implicit interfaces preclude a more strongly typed design. The flag I am proposing would force the compiler to throw an error if the interface is not explicitly implemented.

**Comment by RyanCavanaugh** [comment]
So you would want this code to be an error?
```ts
interface Point { x: number; y: number; }
function printPoint(p: Point) { ... }
printPoint({x: 3, y: 2});
```

**Comment by gravidThoughts** [comment]
Hi Ryan,

Thanks for the quick reply.

Yes.

If implicit interfaces were disabled, the programmer would have to explicitly cast an anonymous object.

```typescript
printPoint(<Point>{x: 3, y: 2});
```

To be clear, this would be an opt in for a new project that wanted the strength of typing to be closer to C#. Anal from the perspective of someone who comes from a dynamic language background. Expected from my perspective, as semantics are more easily enforced by the compiler.

**Comment by RyanCavanaugh** [comment]
Code like that isn't "legacy", it's "every JavaScript library in the world", including ones written yesterday using TypeScript. I think if you turned on a mode like this, you'd quickly find it was unusable in practice.

JavaScript itself behaves like a structural type system and TypeScript matches that. We don't want to start a fork of the language with completely different (non-structural) semantics.

**Comment by gravidThoughts** [comment]
Appreciate your attention.

I guess I confused as to why external libraries matter.

Certainly, those who have started their libraries under existing semantics could continue to do so.

What I care about is my project.

Are you saying this would make d.ts files unusable?

**Comment by gravidThoughts** [comment]
Nvm, I certainly take you at your judgement about complexity at face value.

Coming from a C# background, I have some ideas that are ingrained and TS semantics are quite foreign. Reading this [paper](http://janvitek.github.io/pubs/ecoop15a.pdf), I was really intrigued by the idea of a developer to opt into a design that is more strongly typed.

**Comment by danquirk** [comment]
@gravidThoughts see https://github.com/Microsoft/TypeScript/issues/202 for some existing discussion on the concept (nominal typing vs structural typing)

**Comment by gravidThoughts** [comment]
@danquirk That is a great thread, exactly what I was looking for. Thanks!
