### ISSUE TITLE
Extending Number does not work with operators

### ISSUE THREAD

**Issue by sjohnsonaz** [microsoft/TypeScript#39102]
If I create a new `class` that extends `Number`, operators cannot be applied to the new `class`.

However, it works as expected in JavaScript.

**TypeScript Version:**  3.9.5

**Search Terms:**

* extend Number
* extend base types
* valueOf

**Code**

```ts
class Test extends Number { }

let a = new Test(5);
let b = new Test(10);

let c = a + b;
```

**Expected behavior:**

`c` should equal `5`.

**Actual behavior:**

Compiler returns: `Operator '+' cannot be applied to types 'Test' and 'Test'`

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/MYGwhgzhAEAqCmEAu14A8nwHYBMYDkBXAWwCN4AnaAb2gF8AoBkeFMaAXmi3gHc5ESABQBWAJQBuZq2ilO3PgORCAjAAZJTFimDz2AalkSgA)

This appears related to #2031, #2361

**Comment by RyanCavanaugh** [comment]
This is another manifestation of #2361
