### ISSUE TITLE
[BUG] links not working

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [microsoft/TypeScript#39116]
Typescript All version not resolve modules by links
---

file structure:
```
/link/
/node_modules/link 
```

typescript code:
```typecsript
import link from "link"
```

`/node_modules/link` linking to `/link/` directory, webpack works correctly, but typescript not using link and say "module not found"

solution:
===
typescript should follow the links for module-resolution

**Comment by RyanCavanaugh** [comment]
There are dozens of unspecified factors involved here; please provide a complete repro in a follow-up issue if you'd like us to investigate.
