### ISSUE TITLE
Add `not` keyword

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#39120]
## Suggestion

Add `not` keyword. It can't be implemented by `is`, nor `typeof value extends Type ? false : true`.

## Use Cases

Sometimes users need validator function which is `not`, not `is`.

## Examples

```
declare function notString (value :unknown) :value not string;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
See #29317 and others
