### ISSUE TITLE
Narrow type by `typeof value extends Type ? any : never`

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#39121]
## Suggestion

Narrow type by `typeof value extends Type ? any : never`.

## Use Cases

```ts
declare const x :number | string;
if ( typeof x!=='string' ) { throw TypeError(); }
x;// string
```

Make inline type narrow code can be util function.

## Examples

```ts
declare function throwNonString (value :unknown) :typeof value extends string ? void : never;

declare const x :number | string;
throwNonString(x);
x;// string
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
The syntax for this is
```ts
declare function throwNonString(value: unknown): asserts value is string;
```

**Comment by LongTengDao** [comment]
@RyanCavanaugh Thank you! And I try to find this syntax in docs again, but I can't find it. Is it forgotten to write in docs?

**Comment by fatcerberus** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

**Comment by LongTengDao** [comment]
@fatcerberus Thank you! So it's not in category docs yet... (Only in release notes)
