### ISSUE TITLE
Casting enums with same values gets error

### ISSUE THREAD

**Issue by zlk89** [microsoft/TypeScript#39127]
**TypeScript Version:**  3.9.2

**Search Terms:**

**Expected behavior:**
It would be great to check if all enum values are exclusively overlap, and only throw error when it is not.

**Actual behavior:**
Now it shows error even when they have exactly same values:
```
Conversion of type 'EnumA' to type 'EnumB' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.(2352)
```

**Related Issues:**

**Code**
```ts
export enum EnumA {
  Key = 'VALUE',
}

export enum EnumB {
  Key = 'VALUE',
}

function assign(val: EnumA) {
  const val2: EnumB = val as EnumB;  // <--- getting error here
  return val2;
}

```

<details><summary><b>Output</b></summary>

```ts
export var EnumA;
(function (EnumA) {
    EnumA["Key"] = "VALUE";
})(EnumA || (EnumA = {}));
export var EnumB;
(function (EnumB) {
    EnumB["Key"] = "VALUE";
})(EnumB || (EnumB = {}));
function assign(val) {
    const val2 = val;
    return val2;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=12&ssc=1&pln=1&pc=1#code/KYDwDg9gTgLgBMAdgVwLZwKItQQTgbwFgAoOOAaWAE84BeOAcgDUcAZAVQwYBoSBfEiVCRYCbJmwAhAiTKUa9Zm049+g4gDNkiAMYwAlhERwAhgGcz+gOaIAFADcTAGwBcEtDgCUM0nB1GzeEcnACY3LDRpemDTM3dUSQBuWTgoYBhkKGNgkOTiAWIgA)

**Comment by ron23** [comment]
I had the same problem and would love to see a native support

**Comment by RyanCavanaugh** [comment]
The intent of string enums is specifically to disallow conversions like this in either direction. This is the same category of type assertion as "cat to fish" - despite both being animals, sharing a common ancestor (in this case `{ Key: "Value" }`) is not sufficient proof of validity

**Comment by zlk89** [comment]
I think it makes sense to disallow conversion when two enums have some values not in common, e.g.,
```
enum Cat {
    Key1 = 'VAL_1'
    Key2 = 'VAL_2'
}

enum Fish {
    Key1 = 'VAL_1'
    Key3 = 'VAL_3'
}
```

But what if both of them are having exclusively same values?

**Comment by RyanCavanaugh** [comment]
Why do they both exist? 🤔

**Comment by jbmilgrom** [comment]
Does TS's structural typing philosophy not extend to enums? 

this seems to work
```ts
type A = { name: string };
type B = { name: string };

const f = (x: A) => x.name;

const b: B = { name: 'george' };

f(b); // no type errors
```

Would it be natural for the enum equivalent to work too?

**Comment by RyanCavanaugh** [comment]
The defining behavior people requested when they asked for string enums is that their values *not* be treated structurally (otherwise you would just use a string literal union)

**Comment by zlk89** [comment]
This could happen often, if you are migrating to graphql, and then generate all types including enums separately in graphql schema.

**Comment by RyanCavanaugh** [comment]
@zlk89 indeed; this is why I voiced my support on https://github.com/apollographql/apollo-tooling/pull/1750

**Comment by zlk89** [comment]
@RyanCavanaugh I think this could be a potential improvement item for ts itself as well

**Comment by kdmadej** [comment]
A bit late to the party but maybe someone can help me figure this one out.

I love the fact that enums are treated like nominal types – to be honest I'd like to see more options for nominal types in TS but that's for a whole different discussion.

Basically I'm dealing with the same situation as OP so let us assume, just for the sake of this thought experiment, there is no other way.

Is there a type-safe way for me to cast one enum to the other? I.e. using some combination of conditional and mapped types?
I tried creating a conditional type that would return `never` if keys of the source didn't extend keys of the target (through `keyof typeof Enum`) so that the unsafe cast through `unknown` would still fail if the enums didn't overlap, like so:
```ts
type CastToTypeIfKeysMatch<From, To> = keyof From extends keyof To ? To : never;
const foo: EnumA = bar as unknown as CastToTypeIfKeysMatch<typeof bar, EnumA>
```
but then I realised I can not assign anything to `never`, but I can assign `never` to anything so that idea went down the drain.

Anyone got any other suggestions? 😅

**Comment by vegerot** [comment]
> This could happen often, if you are migrating to graphql, and then generate all types including enums separately in graphql schema.

@zlk89 this is exactly what I'm experiencing right now.  This is our setup

- graphql schema in `.graphql` files generating `schema-types.ts` file
-  BE team gives us OpenAPI schema we generate types from


A user makes a request to our GraphQL service, and we pass it along to our REST service.

Here is a shortened version of the generated `schema-types.ts` (GraphQL input)

```ts
export type RegistryDetailInput = {
  /** Access type of the registry (PRIVATE, PUBLIC) */
  accessType: Access;
};
export enum Access {
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
}
```

And here are the OpenAPI generated types (BE)
```ts
export interface BaseRegistryV3Details {
    accessType: BaseRegistryV3Details.accessType;
}
export declare namespace BaseRegistryV3Details {
    enum accessType {
        PUBLIC = "PUBLIC",
        PRIVATE = "PRIVATE"
    }
}
```

Now trying to run
```ts
updateRegistry({accessType: gqlInput.accessType})
```
gives
```ts
Type '{ accessType: Access;}' is not assignable to type 'BaseRegistryV3Details'. Types of property 'accessType' are incompatible. Type 'Access' is not assignable to type 'accessType'.
```

--- 
Trying 
```ts
updateRegistry({accessType: gqlInput.accessType as BaseRegistryV3Details.accessType}) // 🤢
```
gives
```ts
Conversion of type 'Access' to type 'accessType' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

And of course I could just do 
```ts
updateRegistry({accessType: gqlInput.accessType as unknown as BaseRegistryV3Details.accessType}) // 🤮
```
but that's pretty #cringe haha

**Comment by vegerot** [comment]
To clarify, @RyanCavanaugh this is not isolated to this one parameter `accessType`, but happens *multiple* times in *every* REST API call 😩

**Comment by microHoffman** [comment]
Hey, any updates on this?

**Comment by ob-ivan** [comment]
I don't know about GraphQL, but in general, if I have a library that exports a single function with a single parameter:

```
export const veryUsefulFunction = (veryImportantParameter: QuiteAnIntersetingType) => { ... };
```

if the parameter type is an interface, then renaming it is a patch-level change, it does not break the compatibility, but if the type parameter is an enum, then renaming it is suddenly breaks backward compatibility and requires a major version release.

**Comment by ThomasP1988** [comment]
`import { Notification, NotificationProperty } from "core/repositories/notification/types";
import { Notification as NotificationGQL, NotificationProperty as NotificationPropertyGQL, NotificationPropertyType as NotificationPropertyTypeGQL } from "../../schema-type";

export const NotificationReducer = (input: Notification): NotificationGQL => {
    return {
        ...input,
        id: input.notificationId,
        properties: input.properties.map(NotificationTypeReducer)
    }
}

export const NotificationTypeReducer = (input: NotificationProperty): NotificationPropertyGQL => {
    return {
        ...input,
        type: input.type as unknown as NotificationPropertyTypeGQL
    }
}`


if i want to prevent the ts-ignore i have to increase my complexity just for a enum casting when those two enum are identical, I think this is working as intended, maybe you could re-consider it?
