### ISSUE TITLE
@typedef doesn't with ES6 modules

### ISSUE THREAD

**Issue by Akany** [microsoft/TypeScript#39126]
`@typedef` doesn't work in case file has ES6 import/export or require use.

Example:
Define `@typedef` in a file that has import/export.
```js
// a.js
/**
 * @typedef {Object} Some
 * @property {number} value
 */
import $ from 'jquery';
```

Use type in another file.
```js
// b.js
/**
 * @date 2020-06-12
 * @param {Some} some
 * @returns {any}
 */
function logSome(some) {}
```

By hovering on `Some` in `b.js` file - `Cannot find name 'Some'.ts(2304)`.
But it starts to work, in case i remove any import/export or require from `a.js` (`@typedef` file).

Is it expected behavior ?

Tested with/without `jsconfig.json` file and different setting.
Example provided without us of `jsconfig.json` file.

- VSCode Version: 1.46.0
- OS Version: Windows_NT x64 10
- Does this issue occur when all extensions are disabled?: Yes
- Does this issue occur in code-insider?: Yes

**Comment by RyanCavanaugh** [comment]
I think @IllusionMH answered this sufficiently. Thanks!
