### ISSUE TITLE
'always false' field now narrowed in 'if' true-branch

### ISSUE THREAD

**Issue by SQReder** [microsoft/TypeScript#39139]
**TypeScript Version:**  3.9.2, Nightly

**Search Terms:**
true|false boolean controlled flow
boolean type narrow

**Code**

```ts
function absurd(_: never) { throw new Error("Must not be called"); }

interface Foo {
    bar: false;
}

function fooled(foo: Foo) {
    if (foo.bar) {
        // foo expected to be narrowed to 'never' type
        absurd(foo);
    } else {
        const bar: false = foo.bar; 
    }
}
```

**Expected behavior:**
foo type in the 'true' branch narrowed to never

**Actual behavior:**
foo type is Foo, which is nonsense

**Playground Link:** https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200615#code/GYVwdgxgLglg9mABAQwEYGcQCcAmAKAfQC5EwBTANzKwEpEBvRKACyzgHdSzOBRLNrHgBEAWRDoopOJNRlEEZABtFZHEJoBuRAF8AULphgo1YMghyAYnDgNdie4lTIsJU4vRkNuvbtCRYCIjA1ir4wXAkVnB09HYOMMCIeOEAdE60tg5ZiAD0OUHWiGQAHgAOZNCqTDaypM5s7FVQNgDk5FRYLUwAnuVx2SgY2GHWmv06Re5ysQP2EAgSjs6uSh6IALwFcGnOWuN6ekA

**Related Issues:** 
No

**Comment by ShuiRuTian** [comment]
Not pretty sure, but I think this is similar to #39110 and #39114

**Comment by fatcerberus** [comment]
`Foo` is not a union, it's just a single object type.  Therefore you don't get discriminated union behavior, and TS won't narrow arbitrary objects based on their properties.  It works the way you expect if you use a proper discriminated union:

```ts
function absurd(_: never) { throw new Error("Must not be called"); }

interface Foo {
    bar: false;
}

interface Bar {
    bar: true;
}

function fooled(foo: Foo | Bar) {
    if (foo.bar) {
    } else if (!foo.bar) {
    } else {
        absurd(foo);
    }
}
```

**Comment by fatcerberus** [comment]
See also #29827

**Comment by SQReder** [comment]
The problem described in detail in #38963. I wanted to avoid complete union discriminator, however, there are not possible for now. 
Thanks, guys 😉
