### ISSUE TITLE
Type of object value unexpectedly become never, won't happen when assign to variable first

### ISSUE THREAD

**Issue by lukyth** [microsoft/TypeScript#39134]
**TypeScript Version:**  4.0.0-dev.20200615, 3.9.2

**Search Terms:** never, type never, type never if, type become never, type never variable

**Expected behavior:** `description[key]` shouldn't be `never` at `description[key] = value` 

**Actual behavior:** `description[key]` is `never` at `description[key] = value`. But if I assign `description[key]` to a variable first then do `assignedVariable = value`, it becomes fine.

**Related Issues:** Couldn't find it.

**Code**
```ts
const description = {
  key: "",
  keyCode: 0,
  code: "",
  text: "",
  location: 0,
}

interface KeyDefinition {
  keyCode?: number
  shiftKeyCode?: number
  key?: string
  shiftKey?: string
  code?: string
  text?: string
  shiftText?: string
  location?: number
}

const definition: KeyDefinition = {}

const descriptionKeys = Object.keys(description) as Array<keyof typeof description>
descriptionKeys.forEach((key) => {
  const value = definition[key]
  // This doesn't work
  if (value) {
    description[key] = value
  }
  // But this works
  let a = description[key]
  if (value) {
    a = value
  }
})
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const description = {
    key: "",
    keyCode: 0,
    code: "",
    text: "",
    location: 0,
};
const definition = {};
const descriptionKeys = Object.keys(description);
descriptionKeys.forEach((key) => {
    const value = definition[key];
    // This doesn't work
    if (value) {
        description[key] = value;
    }
    // But this works
    let a = description[key];
    if (value) {
        a = value;
    }
});

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.staging-typescript.org/play?ts=4.0.0-dev.20200615#code/MYewdgzgLgBAJgUwsATgSwA5TeGBeGAbwCgYYBrBATwC4YAiegGlIuoGERE6AGFs0NwbNWUBAA8odRvxgAbEMACG2cLxYBfYsTRgxKAGZLgCGAGlqAEQQHdaVWCKtKVTogD8dMAFcAtgCMEFFYIAAs0AygLVy4ETxgfAKDnanjodDAAcxDwyOi0qAzsgViCotEJKDLdYpgwiKgAFUrqrNYFZQd4xMDgrWJQSFhEWzB7HDA6aOtR8dwCQn7B6HgkVEwHaIh8GAB5fwArBGAoADoXCAAKRGR0LAmAShglbYBBFBQlKgAeFxADGBQKgYBD-Va3DYTAB8xBu63u4C2pwMIBQAFFjKFLpcXE88FCnCUhjAAG5KOTeUwEEZ2BwAbRcAF1WAB6FkwRrhbZwEBIMAAclgAHdUeRWBEYJcyRSEE8SGQyHC7vSmTtpZTWFoyGyYAAhbywKBcmAilDkCDtBCwJQ7JWQ8AM6jMsgSqXkyly1hkG0EdUITXEDQPIA)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. You could corrupt `description` with a write like `description[key] = value`, but `a` will not be corrupted by this operation because its type is the general type `string | number`.

**Comment by MattGson** [comment]
> You could corrupt description with a write like description[key] = value

This is not explained. I run into these kind of typing issues a lot. This is very limiting. It makes it impossible to build an object key by key for instance (without resorting to type workarounds like 'any').
