### ISSUE TITLE
incorrect union type checking

### ISSUE THREAD

**Issue by tli4** [microsoft/TypeScript#39145]
**Expected behavior:**

John is neither Person, Lady or SingleMan, so the variable John should get a ts warning

**Actual behavior:**

John passed type checking

**Playground Link:** https://www.typescriptlang.org/play/?ssl=16&ssc=7&pln=16&pc=10#code/C4TwDgpgBA4hB2ATCAnKBeKByAtgQwBsIsoAfbAMwnyJPKwHtgALVLAbgChPRIoAFVAGcG8DFADeUAOYJkKAFyw5qADRR4eHBCVDgKAJbxpUAL49w0AMpHpRALJ4xmKbKSoluQsXUEGANw8NAFcCAjMLPgAZPEQQcVcVRUpqbxJzSOgACWD8ZwFhUTIoGLjim2MHJy5OAGNRPSgAKQZmeCUcvITOKBkkpQAiKhoIAdUeqD9A5PhQgnGM3mzcpwAmcVL48gq7CEd4Gvr4RoARBh0oTrXu3rd5QeHvMYmpoNmwhaA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
That repro... hmmm 👀

`John` is a valid `Lady` with an allowed excess property that aligns with another property found in the union. You can write `type Lady = { gender: 'female', lover?: never };` if you want to disallow that initialization.

**Comment by tli4** [comment]
That make scenes 👍 thanks a lot!
