### ISSUE TITLE
emit file lost import module in .js with package use export = with build by new typescript@next

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#39149]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

Version 4.0.0-dev.20200615

[bug-web-46035.zip](https://github.com/microsoft/TypeScript/files/4800087/bug-web-46035.zip)

download the zip and run `yarn build` will see

**note: remember run yarn for install deps before test**

```ts

import gitRoot from 'git-root2';

let git_root = gitRoot(process.cwd())

console.dir(git_root)


```

**Expected behavior:**

https://www.typescriptlang.org/v2/en/play?module=1#code/JYWwDg9gTgLgBAc2DAShC8BmUIjgciRgFocMAmfAbgCgaAbAU3iIH0z4BeRZNDACjA4AxowDOYgHTCA7gBN+ASkV1hEAHZiITSXOBR+bDoqA

```js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const git_root2_1 = __importDefault(require("git-root2"));
let git_root = git_root2_1.default(process.cwd());
console.dir(git_root);
```

**Actual behavior:**

```js

Object.defineProperty(exports, "__esModule", { value: true });
let git_root = gitRoot(process.cwd());
console.dir(git_root);
//# sourceMappingURL=index.js.map
```

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the output I get (in index.js, which is what I'm guessing you're referring to)
```
"use strict";
/**
 * Created by user on 2020/6/19.
 */
exports.__esModule = true;
var git_root2_1 = require("git-root2");
var git_root = git_root2_1["default"](process.cwd());
console.dir(git_root);
```

**Comment by bluelovers** [comment]
@RyanCavanaugh are u install deps before run ?

i forgot say 
need to install deps

**Comment by bluelovers** [comment]
looks like this happen with package use `export =`

![image](https://user-images.githubusercontent.com/167966/85163162-09a68280-b295-11ea-94c8-3ef787c2c97c.png)

**Comment by rbuckton** [comment]
Interestingly, when running the following:

```
yarn
yarn build
```

I get the following error:
```
index.ts:7:16 - error TS2552: Cannot find name 'gitRoot'. Did you mean 'git_root'?

7 let git_root = gitRoot(process.cwd())
                 ~~~~~~~

  index.ts:7:5
    7 let git_root = gitRoot(process.cwd())
          ~~~~~~~~
    'git_root' is declared here.


Found 1 error.
```

However, if I change the source file to this:

```ts
import { default as gitRoot } from "git-root2";
...
```

We both check and emit correctly (i.e., including `__importDefault`).

For some reason we aren't treating the default import as a valid identifier reference.

**Comment by rbuckton** [comment]
The underlying issue is that we fail to fully resolve the alias from the `export = gitRoot` due to the fact that `gitRoot` is defined as a `namespace` with a `default` export in `git-root2/core`. The following is a fairly simple repro of the issue:

```ts
// @esModuleInterop: true
// @filename: main.ts
import gitRoot from "git-root2";
gitRoot(""); // error: Cannot find name 'gitRoot'

// @filename: external.d.ts
declare module "git-root2/core" {
    export function gitRoot(cwd?: string): string;
    export namespace gitRoot {
        var _a: typeof gitRoot;
        export { _a as default };
    }
    export default gitRoot;
}

declare module "git-root2" {
    import { gitRoot } from "git-root2/core";
    export = gitRoot;
}
```

When we try to resolve `import gitRoot from "git-root2"`, we resolve it to the `export=` symbol. The `export=` symbol is an alias to `gitRoot` in `import { gitRoot } from "git-root2/core"`, which is an alias to `gitRoot` in _core_. When we resolve the symbol, we resolve an alias symbol once, which results in _another alias symbol_, because we never properly resolve the alias in the call to `resolveExportByName` from `getTargetOfImportClause`.
