### ISSUE TITLE
Unable to use common node modules for all my projects on shared drive

### ISSUE THREAD

**Issue by avinash10993** [microsoft/TypeScript#39158]
Hi Team,

We are currently running into an issue and are not able to address it. We need to have all the node modules installed in a central location rather than each project to keep projects light weight.

Could someone help us if this is expected behaviour. Could anyone please guide us where we are going wrong thanks for the help.

We have tried using types and paths. It is not throwing a compilation issue but while running the code it says Module not found.

We are using the following package.json and tsconfig.json

**tsconfig.json**
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "preserveConstEnums": true,
    "strict": true,
    "target": "es2020",
    "sourceMap": false,
    "declaration": false,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "ConvertedJSFiles",
    "types": [
      "C:/Users/node_modules/@types/jasmine", 
      "C:/Users/node_modules/@types/node",
      "C:/Users/node_modules/@types/cucumber",
      "C:/Users/node_modules/@types/chai"],
      
    "baseUrl": "C:/Users/node_modules/", // This must be specified if "paths" is.
    "paths": {
      "protractor": ["protractor"],
      "cucumber-tsflow":["cucumber-tsflow"] ,// This mapping is relative to "baseUrl"
    }
  },

  // "exclude": [
  //   "node_modules"
  // ]
}
```
package.json
```
{
  "name": "protractorautomation",
  "version": "1.0.0",
  "description": "Protractor Typescript automation framework",
  "main": "config.js",
  "type": "commonjs",
  
  "devDependencies": {},
  "scripts": {
    "pretest": "npm run tsc",
    "test": "protractor ConvertedJSFiles/config.js",
     "tsc": "tsc"
  }
}
```

Error: Error: Cannot find module 'protractor' 
This is not specific to protractor but for all the modules its the same.

Note: If i have my nodemodules within the project structure it is working fine.

Thanks,
Avinash

**Comment by RyanCavanaugh** [comment]
Set `typeRoots` to `C:/Users/node_modules/@types` and this should work as you expect. `types` is an array of type directive names, not paths

**Comment by anjanroushan** [comment]
Hi Ryan,
Thanks for your response
On setting typeRoots to C:/Users/node_modules/@types it is throwing error Cannot find type definition file for 'lib'
