### ISSUE TITLE
Feature Request/Proposal: Clauses

### ISSUE THREAD

**Issue by NightshadeX9X** [microsoft/TypeScript#39151]
# **Clause**
A clause can be used to create extremely customizable types. Don't have a better way to explain it, so look at the example.

### **Example**
```typescript
clause LessThan5 (x) {
  return typeof x === "number" && x < 5;
}

const myNum: LessThan5 = 2;
const myNum2: LessThan5 = 7; // error at compile-time
```
So whatever value you try to assign to a clause, gets passed in as the clause argument. If the clause returns true for that value, it works, otherwise, it throws an error.

And if you wanted to shorten it even further, you could do the following instead:
```typescript
clause LessThan5 (x: number) {
  return x < 5;
}
```
...and it would work the same.
Giving the clause argument a type means that the value it is assigned to must first be of that type, and then meet the clause's restrictions. In that first clause, x's type would be inferred as any.

### **Why?**
Imagine you want a function that can get a certain number of users from a database. If you pass in a positive number, it gets that many users. If you pass in -1, you get all the users.

Now to implement this in typescript (without clauses) you would do:
```typescript
function getUsers(amountToGet: number) {
  if (amountToGet > 0) return db.users.filter(amountToGet);
  else if (amountToGet === -1) return db.users;
}
```
This is fine, but we don't want the caller of the function to pass in just any number, only -1 or a positive number. So that's why we should use clauses.
Look at the following code: 
```typescript
clause GetAmount (x: number) {
  return x > 0 || x === -1;
} 
function getUsers(amountToGet: GetAmount) {
  if (amountToGet > 0) return db.users.filter(amountToGet);

  else return db.users; // instead of `else if` we can use `else`. This is because: since x is not greater than 0, the only remaining possibility is that x is -1, since the type of x is the clause `GetAmount`
}
```
I think that Clauses would be a great addition to the language, and would be able to solve many problems. I hope this is implemented.

**Comment by RyanCavanaugh** [comment]
We're not going to do anything that involves evaluating user-written code during the compilation process.
