### ISSUE TITLE
Generic types assumed to never overlap, even if they might

### ISSUE THREAD

**Issue by clar-cmp** [microsoft/TypeScript#39165]
**TypeScript Version:**  Nightly

**Search Terms:** Generic overlap

**Expected behavior:** Should compile without errors.

**Actual behavior:** States that the condition is always false because `T1` and `T2` do not overlap, even though they can.

**Related Issues:** N/A

**Code**
```ts
function checkEqual<T1 extends number, T2 extends number>(
  first: T1,
  second: T2,
): boolean {
  return first === second;
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function checkEqual(first, second) {
    return first === second;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200615&ssl=1&ssc=1&pln=6&pc=2#code/GYVwdgxgLglg9mABBAFgUwgawKIEcQCGANgDwAqAjImgB5RpgAmAzomCALYBGaATgDSIyAJmp0GLNpx68AfAAoAsAChEiYDF7MoALiEV+KtcwwJGekYeUBKPVzhwiaAkgDeRxLzRQQvJBq0oRABeUMQTCDMAbhUAXyA)

---

This is a pretty contrived example, I'll admit, but I was using it with conditional types to determine what the resulting type is based upon a generic parameter's value:

```
function ifSymbol<T1 extends SomeEnum, T2 extends SomeEnum, U>(
    first: T1,
    second: T2,
    result: U,
): (T1 extends T2 ? U : {}) {
    if (first === second) {
        return result;
    } else {
        return {};
    }
}
```

Meanwhile, this works fine with only one generic:

```
function ifSymbol<T extends SomeEnum>(
    first: T1,
    result: U,
): (T extends typeof SOME_SYMBOL ? U : {}) {
    if (first === second) {
        return result;
    } else {
        return {};
    }
}
```

**Comment by RyanCavanaugh** [comment]
This is the intended behavior, though admittedly the error message isn't 100.00% correct (since it's the same message we'd use for pure non-overlaps like `string === number`). In this case the error helps you "keep straight" `T1` and `T2`, which absent other evidence seem to be separate types you don't want to conflate.

A basic rule of thumb is that a generic function should typecheck if *all* concrete instantiations of it would typecheck. `checkEqual<0 | 1, 2 | 3>` fails that test.

**Comment by clar-cmp** [comment]
That *would* be fine except if you consider the last example given. For example:

```
const second = 2;
function checkEqual<T extends number>(
  first: T,
): boolean {
  return first === second;
}
```

You still have this typecheck even though setting `T = 1` would result in completely disjoint types.

**Comment by clar-cmp** [comment]
I never got a response on this. I don't think this should be closed.

**Comment by RyanCavanaugh** [comment]
@clar-cmp We've defined that this is the expected behavior and explained why; it's not tractable for us to leave every issue open until the OP is convinced.

**Comment by clar-cmp** [comment]
I provided a counterexample to your explanation stating a case where there was typechecking even though not every instantiation would type check. I'm not asking you to convince me on your decision; I'm asking you whether this separate case that works and lead me to file this bug report is also considered unintended and should be fixed.

**Comment by RyanCavanaugh** [comment]
The second example is why I described the prior rule as a "rule of thumb" - a non-generic type `U` is comparable to a type parameter when the type parameter is constrained to  `U`.
