### ISSUE TITLE
Prototype assignment doesn't work on default-assigned constructor functions

### ISSUE THREAD

**Issue by minestarks** [microsoft/TypeScript#39167]
Bug seen in actual VS customer code.

**TypeScript Version:**  3.9.2

**Search Terms:** ES5 class javascript prototype assignment constructor function

**Expected behavior:** In the example below, I expect the `test.class` properties include the one from the prototype. The behavior shouldn't depend on whether or not `test.class` was default-assigned or not.

**Actual behavior:** The prototype assignment doesn't seem to work when default assignment is used. @sandersn thinks this is a bug but isn't surprised.

**Related Issues:** #39166 from same user code

**Code**
```ts
var test = {};

test.class = test.class || function (name) {

    function getName() {
        return name;
    }

    this.name = getName();
}

test.class.prototype = {
    add: function (i) {
    }
}; 

var t = new test.class("test");
t.name
t.add // EXPECTED: Binds to `add` from the prototype, ACTUAL: doesn't


//
// Same pattern works with a straightforward assignment:
//

var test2 = {};

// Removed `test.class ||` 
test2.class = function (name) {

    function getName() {
        return name;
    }

    this.name = getName();
}

test2.class.prototype = {
    add: function (i) {
    }
}; 

var t2 = new test2.class("test");
t2.name
t2.add // ACTUAL: `add` bound correctly

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?useJavaScript=true#code/G4QwTgBALgpgzlCBeCBvAvgbgFDdggOgGMAbEOOZaeKYsiiAH0YgDMBXAOyKgEsB7ThAAUnEAFsYASjS4I8tlx4ChAcxhQAchJjCZqbAqMQwG9mCFjJOI+jkKoAC15wCVmFXVadenHbw0dOSuAA5g-FARAJ4hHigGRiAAJkkAXIrcfIIivPqGCnZYELigkIgonDAA7tSEpMHCAET4UI1SOLTueATJSRAA9P0QAKIAGgAKwwDCACrDACLpAEK8nEmUkRAABr1bbOHi0I4eYRHRsQA0EACCswCq1wAy6Un88JwA5FC42IO-QwBlHQQEIgKCwCwQKr8MAAa0oVV4TggIAgCDAIF4qkcUFYMKq4D6wSxnEknCgqX+JXAtSgACYqBgcP8IAAlGDifjAGB9LYtIIMZh7AIIOkCygoDiZFQidx5fLyKXKbJebSSPSyYwKUxQcyWHQ2Ar2eROFxuYEoVU+drYfwtMX1CgEU6RKAxOKahS9dJKrJCYS5T3yQqYYrYUrQBkVaq0h30OBNFptDpirr0nopAZDW4zB7Pba7CAAI34XD6RBhph4JCi2CAA)

**Comment by sandersn** [comment]
`getAssignedClassSymbol`, which looks up members of `prototype`, is wrong for default-assigned constructor functions, and returns undefined incorrectly.
