### ISSUE TITLE
Side effect bugs with logical assignment

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#39172]
**TypeScript Version:** Nightly

**Search Terms:** logical assignment side effect 

**Code**

This code is from [lgcl-nullish-assignment-operator-lhs-before-rhs.js](https://github.com/tc39/test262/blob/5908ed29ac04a9f5582bb774ca07f8089d3cddfd/test/language/expressions/logical-assignment/lgcl-nullish-assignment-operator-lhs-before-rhs.js), a test262 conformance test.

```ts
var assert = {
  sameValue(a, b, error) {
    if (a !== b) throw new Error(`${error}: ${a} !== ${b}`)
  }
}

var count = 0;
var obj = {};
function incr() {
  return ++count;
}

assert.sameValue(obj[incr()] ??= incr(), 2, "obj[incr()] ??= incr()");
assert.sameValue(obj[1], 2, "obj[1]");
assert.sameValue(count, 2, "count");
```

**Expected behavior:** This code should exit cleanly

**Actual behavior:** This code crashes with `Uncaught Error: obj[incr()] ??= incr(): 3 !== 2`

The problem is that TypeScript evaluates the property key in the property access twice instead of capturing the value and only evaluating it once.

TypeScript generates this (incorrect):

```js
(_a = (_b = obj)[incr()]) !== null && _a !== void 0 ? _a : (_b[incr()] = incr());
```

Babel generates this (correct):

```js
(_a = obj[_b = incr()]) !== null && _a !== void 0 ? _a : obj[_b] = incr();
```

**Playground Link:** [link](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200615&ssl=1&ssc=1&pln=16&pc=1#code/G4QwTgBCDO0KZgC4QLwQN4CgIWiAtnAGogA2ArnABQgA0EARvQmAPZgCUG2OEAlgDMINCAEIUaBl0QALNgHcIAOziKAomDZgqAAwAk6FuwC+ALggGQxsRIvoGxnRx7HMrzKEgBjVuSXI0AAYAbg9wCFYGACtUDGNQgT8vRD5WJX4lL20uLBwwOERyMHSAahKfP0RQ9xh4JAA6PEISCmpIqIBtPkzsgF0IAH4BtG6sqg56ACZ6ACJ2rp7x-qGRxY4ZjlDahERGgmIySip5gEZeqdnT3o2t2B295sPqCv8LiBmXxBvMIA)

**Related Issues:** #37255 #37727

**Comment by Kingwl** [comment]
Good catch. I'll take a look.
