### ISSUE TITLE
Invalid calculate property "length" of function with optional arguments

### ISSUE THREAD

**Issue by 4urbanoff** [microsoft/TypeScript#39176]
**TypeScript Version**: 3.9.2

**Search Terms**: function, arguments, length

**Code**
```ts
function one(a: string, b = null) {}
one.length //> 1

function two(a: string, b?: boolean) {}
two.length //> 2, but need 1
```

**Expected behavior:** correctly calculate property "length"

**Actual behavior:** optional syntax leads to incorrect calculations

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=5&pc=42#code/GYVwdgxgLglg9mABAgpgCgIYC5EGcoBOMYA5gDSIBGiAvImCADaMCUiA3gL4CwAUBAlxxGKAHSM4JNKnEpSUABZsA9MoB8iAIx8+oSLASIoAdziYc+IqQqUA-DkpxhKDGDZc+AsEJHjJaEzhZeSVEVQ0AJhsQKHoUFAATLSA)

**Comment by dragomirtitian** [comment]
Related to: https://github.com/microsoft/TypeScript/issues/23251
