### ISSUE TITLE
Emit a better warning when default-exporting an inappropriate declaration

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#3917]
Courtesy of @LPGhatguy in #3914.

Instead of going off the rails, we should resiliently parse the following:

``` TypeScript
export default interface User {
    hi: string;
}
```

And give an error like

```
An 'interface' declaration cannot be 'export default'. Consider writing 'export default User;' separately.
```

**Comment by danquirk** [comment]
If we don't fix #3914 we should certainly do this. My preference would be to just allow these sorts of declarations.

**Comment by DanielRosenwasser** [comment]
Agreed, I'd prefer just allowing these sorts of declarations for the sake of consistency.

**Comment by clavecoder** [comment]
I'm guessing it's not allowed because interfaces and enums are not **EcmaScript* objects, correct? What's the list of types this fails on? Just `interface` and `enum` or are there more?

**Comment by Kingwl** [comment]
seems already worked?
