### ISSUE TITLE
The expression is not callable

### ISSUE THREAD

**Issue by hanspeter1** [microsoft/TypeScript#39179]
**TypeScript Version:**  3.9.5 and Nightly

**Search Terms:** The expression is not callable

**Code**

```ts
interface A {
    write(chunk: any, cb?: (error: Error | null | undefined) => void): boolean;
    write(chunk: any, encoding: string, cb?: (error: Error | null | undefined) => void): boolean;
}

interface B {
    write(chunk: string | Uint8Array, callback?: (err: Error) => void): boolean;
    write(chunk: string | Uint8Array, encoding: string, callback?: (err: Error) => void): boolean;
}


function a_b(param: A | B){
    param.write("");
}

```

**Expected behavior:**
No error

**Actual behavior:**
Error: The expression is not callable

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200620&ssl=14&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QdymEgAoEALAVxAGsAuZOEATwBpkEAjAfgZOigB7KAwCiUIVGQAfZCEoAbBTOTUAJhBigIagJTIAvAD5kAN0HA9DToMEKITANw48hYhDJVaDJm2QQQBEE1UABzBgBnMCIQUPYuXmR+CWExFKlZeSUVdU1tPUMTc0tda1t7JywAXywsUEhYRBQAIUwXXDdSCmp6ZCiY0JUAVXqADlQJOD8EOCVORBpE5JFkcUl9YzMLK2QbOwcQZzwCIi6vXv6w4bGJqCn2AKCQ2MjosPjZhXmERb4BNPWhS2JTK+0qNVqMGoCDAwEEIEYAH1OCQAA5wO4AWwY6FkzV02GO6KxADpOh4AEQU3TOKpAA)

**Related Issues:**

**Comment by hanspeter1** [comment]
And this works:
```ts

interface A {
    write(chunk: any, cb?: (error: Error | null | undefined) => void): boolean;
    write(chunk: any, encoding: string, cb?: (error: Error | null | undefined) => void): boolean;
}

interface B {
    write(chunk: string | Uint8Array, callback?: (err: Error) => void): boolean;
    //write(chunk: string | Uint8Array, encoding: string, callback?: (err: Error) => void): boolean;
}


function a_b(param: A | B){
    param.write("");
}
```

**Comment by RyanCavanaugh** [comment]
Only certain kinds of call signatures can be merged into a callable property in a union, and this isn't one of them

**Comment by hanspeter1** [comment]
Why not?
Call signature of the first `write `function of A and the first `write `function of B are not equal but for a `write("that's a string")` there are a match. If i remove the second `write `function of B, the error is gone.

**Comment by hanspeter1** [comment]
There should be no error. 
But you're right, its a "Design Limitation"
