### ISSUE TITLE
Invalid code generated when spread `Set` in js source

### ISSUE THREAD

**Issue by timepp** [microsoft/TypeScript#39171]
testspreadarray.js:
```javascript
let s = new Set()
s.add(1)
console.log([...s])
```

```
$ tsc testspreadarray.js -outFile tsa.js --allowJs
$ node tsa.js
(node:91969) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/a1234/src/witpuzzle/tsa.js:3
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
                 ^

RangeError: Invalid array length
    at __spreadArrays (file:///Users/a1234/src/witpuzzle/tsa.js:3:18)
    at file:///Users/a1234/src/witpuzzle/tsa.js:10:13
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:141:24)
```
tsc 3.9.5
---

My analysis: this is because at 2nd line in generated `__spreadArrays`:
```javascript
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
```
`arguments[i]` is `Set` so `arguments[i].length` will be undefined.

---

BTW: is there a way to tell tsc not to translate spread statements? I can ensure my code only runs on lasteast browsers that all has spread syntax support.

**Comment by AviVahl** [comment]
For full iterables support in ES5/ES3, check out `tsconfig.json` -> `compilerOptions` -> `downlevelIteration`.

For targeting new web browsers, you may want to adjust the `target` option (also in `compilerOptions`). Please note that changing the `target` also affects the default value of other options, such as `module` and `lib`. You might have to explicitly set them to the project's requirements as well.

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by timepp** [comment]
Setting "target" worked for me. There was no obvious tips leading me to this option though :(
Thanks!
