### ISSUE TITLE
Input type can not be checked for belonging to a recursive type

### ISSUE THREAD

**Issue by plohoj** [microsoft/TypeScript#39184]
**TypeScript Version:**  4.0.0-dev.20200621

**Search Terms:**
Circular type 
Circular type extends
Recursive type
Recursive type extends

**Code**

```ts
type Json =
    | string
    | number
    | boolean
    | null
    | { [property: string]: Json }
    | Json[];

interface ISimpleInterface {
    id: number;
    name: string;
}

type isJson = ISimpleInterface extends Json ? true : false;
// Return false

type isJsonWithouInterface = {
    id: number;
    name: string;
} extends Json ? true : false;
// Return true
```
Another case:
```ts
function transferFactory<T extends Json>(callBack: (data: T) => void): T {
    // ...
}

function transferCallback(data: ISimpleInterface): void { }

transferFactory(transferCallback); // Error: Type 'Json' is not assignable to type 'ISimpleInterface'
```

**Expected behavior:**
Check for the correct type will be successful

**Actual behavior:**
Verification of conformity of the type fails.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ssl=34&ssc=102&pln=27&pc=1#code/C4TwDgpgBAUgzgewHZQLwCgpagHynYAJwEskBzTbPJAVwFsAjCQyrPBhBAGwgEMlWuKLS5dBeAN5QA2mEIJIhUAC58RUmQC6q+MigBfcbERJpmgNzp0pYMwBmvAMbQAkgGVidMDxdJbhB2coCUFiABNVWkZmS2xhXjoIVQIScktDdFBIKGI4XRRUKHdPbwhff0DoCAAPWyQwuGM9AH4oIhpoVQcuOAhLAHp+qAAlCGAaQhRu3qss6Fz8gHViYAALBBpy+ydoQpC48Mj6JkJY7CQEpLVUsnSoGrqGppRW9s6oab70QZGxiZQ3lYrD9lmsoGQIEhmMRHFY7DQkI5gMQ9ER+HA7MwAGJOYAIQggAA8ABV7rVIU98gA+AAUjl4ogAQk4ANaqGlhXjAXiqYkASjQVKgADcEOE+bzgoIfgA6OWCQh-SbCGiiKC8Rr8EDpOEIpEogGEdGYwgAYQZXAYrI5XJ5RQ8Xh8fm2zglIrFYWCBlmRqQGOxuPxIBpaL9JvNoitjhZfPMUB+AFFCPJCLzwNAAOT5DM5RpIBDAdVwODEMgXBg8NoINrpqAZ4qOsrOgI7DPoIA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/15300

**Comment by dragomirtitian** [comment]
The problem is not necessarily with the recursive type. If you use an type alias instead of an interface (or an anonymous object type as you also tried) the assignment succeeds. This is due to different behaviors between interfaces and type aliases. To quote @RyanCavanaugh from [here](https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024)

> Just to fill people in, this behavior is currently by design. Because interfaces can be augmented by additional declarations but type aliases can't, it's "safer" (heavy quotes on that one) to infer an implicit index signature for type aliases than for interfaces. But we'll consider doing it for interfaces as well if that seems to make sense

So a type alias without an index signature is a subtype of one that has a compatible index signature, while an interface is not:

```ts
type SimpleType = {
    id: number;
    name: string;
}

interface SimpleInterface {
    id: number;
    name: string;
}

type Indexable = {
    [n: string] : string | number
}


type Y = SimpleType extends Indexable ? "Y" : "N"
type N = SimpleInterface extends Indexable ? "Y" : "N"

```
[Playground Link](https://www.typescriptlang.org/play/?ssl=18&ssc=1&pln=1&pc=1#code/C4TwDgpgBAyglgWzAGwgFXNAvFA3gKCiKjgBMAuKAOwFcEAjCAJwG5DiqBDBCSgZ2BM4VAOZsAvvnzDgzAGacAxtHhJUASSqymC5XnZEylWg2Zti1brygChoiVNCQom0hAAeneqig4CFgG0qfkFhEQBdKBC7ESgAH2o6RiZ8SUdMKABNX1hEFHQMj1kqUj4XEo8vHwB+KAAiTLqo+oA5OvwnaBac1XzNbV1oIogSstdK72hahqbKOrapIA)

**Comment by plohoj** [comment]
Thank you, @dragomirtitian, I understood your explanation.
It turns out that at the moment, if you specify for the generic method that it accepts any type similar to JSON, then whoever uses this method cannot use the interface? That is, the creator of the library should warn the user that this method cannot accept interface.

Example library method with constraint:
```ts
function transferFactory<T extends Json>(data: T): T {
    // ...
    return null as any;
}

const data: ISimpleInterface = {
    id: 0,
    name: 'someName'
}

transferFactory(data); // Error: Argument of type 'ISimpleInterface' is not assignable to parameter of type 'Json'
```
[Playground Link](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAUgzgewHZQLwCgpagHynYAJwEskBzTbPJAVwFsAjCQyrPBhBAGwgEMlWuKLS5dBeAN5QA2mEIJIhUAC58RUmQC6q+MigBfcbERJpmgNzp0pYMwBmvAMbQAkgGVidMDxdJbhB2coCUFiABNVWkZmS2xhXjoIVQIScktDdDsaJEdgYj0ifjg7ZgAxJ2AEQhAAHgAVKAgAD1skMLhjZAA+AAow3mBeVTqASmHgwQB6SagAOnnBQghgGkIUES4oXg7+EHSrR2QCKH7B1XdPbwhff0DoVAm48NUABgAaQSQEpKgAckREgA5b6-dAZQpIYplCpVEB9Aa8EbmKDTKAAUUI8kIqgAgoQyPQIH4oAg7FBQJA-hcvD4-PYnBBflBiB0kAhgFs4HBiGQvgweOSEFAwLxCN9-CSyRToL9dEhQUA)
