### ISSUE TITLE
Typo in Specification

### ISSUE THREAD

**Issue by ericfortmeyer** [microsoft/TypeScript#39185]
### **Replace one with on**

[2.3 Declarations](https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#23-declarations)
...
A name that denotes a value has an associated type (section 3) and can be referenced in expressions (section 4.3). A name that denotes a type can be used by itself in a type reference or on the right hand side of a dot in a type reference (3.8.2). A name that denotes a namespace can be used _**`one`**_ the left hand side of a dot in a type reference.

**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment]
The specification is not maintained and extremely outdated. The last update was **early 2016**.

See https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3ASpec and #15711.
