### ISSUE TITLE
Type argument inference for types and interfaces

### ISSUE THREAD

**Issue by kuba-orlik** [microsoft/TypeScript#39182]
## Search Terms

type argument inference for interfaces

## Suggestion

Generic interfaces could use the same type argument inference behavior as functions do, that is — the type arguments could be automatically inferred based on the contents of the object. This way we could for example create a properly type-checked type that is an object where the one property is a function, and another property is a list of *valid* arguments for that function.

This is already possible for functions, and I believe that extending it to interfaces and types would make the language more expressive and concise in certain cases.

Perhaps there is a reason to enable generic type inference *only for functions*, but I didn't stumble upon one yet. 

## Use Cases

This could be especially useful for typechecking complex objects when creating a declarative API. 

When working on an API for creating collection in our internal framework I've encountered the need to have a list of `Fields`, defined by objects that contain a `FieldType` (which is a class) and `FieldParams` (which are specific to each `FieldType`). 

Ideally, I could define the list of fields like so:

```ts
type FieldDescription<FieldType> = [FieldType, Parameters<InstanceType<FieldType>["setParams"]>];

type Fields = FieldDescription[];

// and then use it like so:

const fields: Fields = [
   [Text, {max_length: "abc"}], // an error would be marked here for invalid type of `max_length` attribute
   [Number, {min:0, max: 100}],
]
```

Without type argument inference for interfaces and types I cannot ensure type safety of such list and I need to resort to functions, which makes the syntax needlessly verbose:

```ts
function FieldDescription<FieldType>(type: FieldType, params: Parameters<InstanceType<FieldType>){
   return [type, params];
}

const fields = [
   FieldDescription(Text, {max_length: 2}),
   FieldDescription(Number, {min:0, max: 100}),
]
```

## Examples

This could work like this:

```ts
interface fnPlusArgs<F extends (...args: any[]) => any> {
	function: F;
	arguments: Parameters<F>;
}

const instance: fnPlusArgs = {  
	function: Math.max,
	arguments: ["1", "2", "3"], // show an error here because these arguments can't be passed to Math.max
}; 
```

The current work-around is to use a function:

```
function fnPlusArgs<F extends (...args: any[]) => any>(
	fn: F,
	args: Parameters<F>
) {
	return { function: fn, arguments: args };
}

const element = fnPlusArgs(Math.max, ["1", "2", "3"]); //shows an error right here because the arguments don't match the function. But the object structure is obfuscated here
```

I've tried finding a workaround with mapped types, but to no avail:

```
type fn<Args extends any[] = any[]> = (...args: Args) => any;
interface fnPlusArgs {
	function: fn;
	arguments: this["function"] extends fn<infer R> ? R : never;
}

const instance: fnPlusArgs = {
	function: Math.max,
	arguments: ["1", "2", "3"], // no error :<
};
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code. *
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
I think this is just a modified presentation of #7481. You'd write
```ts
type FieldDescription<FieldType> = [FieldType, Parameters<InstanceType<FieldType>["setParams"]>];

type Fields<T> = FieldDescription<T>[];

// and then use it like so:

const fields = [
   [Text, {max_length: "abc"}], // an error would be marked here for invalid type of `max_length` attribute
   [Number, {min:0, max: 100}],
] __op__ Fields<unknown>
```

Simply leaving off the type argument list isn't a tractable path forward since it would drastically change how adding a generic type parameter default would behave from a forward compat perspective
