### ISSUE TITLE
Enum type checking seems broken

### ISSUE THREAD

**Issue by nbabanov** [microsoft/TypeScript#39187]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
Enum, enum type checking, enum param
**Code**

```ts
enum MyEnum {
	B = 3
}

function foo(param: MyEnum) {    
}

foo(MyEnum.B); // This should be the only working example.

foo('asdfasdf'); // This does not work, which is good.

foo(2); // This should also not work, but it does. :(
```

**Expected behavior:**
`foo(2)` - should result in `TS: 2345 argument of type number is not assignable to a parameter of type MyEnum.`.
**Actual behavior:**
No errors.

**Playground Link:**  [demo](https://www.typescriptlang.org/play/index.html#code/KYOwrgtgBAsgngUXNA3gKAJACEoF4oDMaAvmmgGZggDGALgJYD2IU5jjAFAA4CGATjwgAuWImQBKKCigyoJMm07wkkAHRZxAbigB6HVAAqAC3oBnKKaOMwAGwAmUAEbAotIy+Y24UAO6M+ANb0IADmUMAAHoJcNsAK7BwA5DymduQpaYlauvrGZlB2jMDmIIy0vv4BADS+JtRGUPkh7Haq8ZwATNl6hibmltb2UDw2poxQpeV+gUA)
**Related Issues:** None.

I think the actual behaviour of TS makes using enums almost pointless to me. If I want a stricter type checking I have to manually create an union type or a function which returns union types.

**Comment by MartinJohns** [comment]
Duplicate of #32690 / #30629.

**Comment by nbabanov** [comment]
This is fixed in TypeScript v5!!! 🎊
