### ISSUE TITLE
Syntax error when lowering object rest into Object.assign

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#39181]
**TypeScript Version:** Nightly

**Search Terms:** object rest property binding Object.assign

**Code**

```ts
var y
({ x: { ...y } } = { x: { z: 1 } })
console.log(y.z === 1) // true
```

**Expected behavior:**

The code above should print `true` without crashing.

**Actual behavior:**

The TypeScript compiler generates this code when targeting ES2017 or below, which is invalid JavaScript:

```js
var y;
({ x: Object.assign({}, y) } = { x: { z: 1 } });
console.log(y.z === 1); // true
```

Attempting to run this code gives `Uncaught SyntaxError: Invalid destructuring assignment target` in V8.

Babel roughly generates this code, which works correctly:

```js
var y;
var _x = { x: { z: 1 } };
y = Object.assign({}, _x.x);
console.log(y.z === 1); // true
```

This came up because I'm trying to implement the [rest/spread proposal](https://github.com/tc39/proposal-object-rest-spread) for [esbuild](https://github.com/evanw/esbuild) by following what the TypeScript compiler does. I logged this issue when I discovered the TypeScript compiler isn't a correct implementation.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ts=Nightly#code/G4QwTgBAngUAFAbwgDwFwSQOm1CBffCAXgxXSQC90BGQvAShgGMB7AOwGcWAbAU024sA5nCiYKxIiWr0IAejkQALmACuvGEA)

**Related Issues:**

**Comment by evanw** [comment]
There are also other issues with the object rest lowering transform in TypeScript such as incorrect ordering of side effects:

```ts
var [{ ...a }, b = a] = [{ x: 1 }]
console.log(b.x === 1) // true
```

That should print `true` but the JavaScript code that the TypeScript compiler generates throws `Uncaught TypeError: Cannot read property 'x' of undefined`. This is what the TypeScript compiler generates:

```js
var [_a, b = a] = [{ x: 1 }], a = __rest(_a, []);
console.log(b.x === 1); // true
```

Is that something you're interested in fixing too? I'm happy to file a bug for that too if you'd like. I'm asking because I could understand if you want to leave this correctness bug there, since it seems like an edge case. It seems more benign than the generated code having a syntax error at least.

**Comment by RyanCavanaugh** [comment]
I'd call that a bug as well; there's nothing stopping us from being spec-compliant here

**Comment by evanw** [comment]
> I'd call that a bug as well; there's nothing stopping us from being spec-compliant here

Ok, sounds good. I will file at least one more bug about object rest patterns for the other issues soon. I'm most of the way through implementing lowering for object rest in esbuild and have discovered some more issues (e.g. with object rest patterns in namespace exports). Many of the issues were found by a fuzzer I wrote for destructuring patterns that I can share as well.

Relevant to this bug: The problem here is of course that the binding pattern is incorrectly being treated as an expression, which causes the `Object.assign` expansion. I've discovered that there are at least two other cases in the grammar where this exact same problem happens, so it might make sense to fix them at the same time as this bug:

1. For-in loops

    ```ts
    for ({ 0: a, ...b } in { abc: 1 })
        // Should print: {"a":"a","b":{"1":"b","2":"c"}}
        console.log(JSON.stringify({a, b}))
    ```

    TypeScript incorrectly compiles this into this JavaScript:

    ```js
    for (Object.assign({ 0: a }, b) in { abc: 1 })
        // Should print: {"a":"a","b":{"1":"b","2":"c"}}
        console.log(JSON.stringify({ a, b }));
    ```

    This is at least not a syntax error, but it's not a correct compilation.

2. For-of loops:

    ```ts
    for ([{ ...x }] of [[{ abc: 1 }]])
        // Should print: {"abc":1}
        console.log(JSON.stringify(x))
    ```

    TypeScript incorrectly compiles this into this JavaScript:

    ```js
    for ([Object.assign({}, x)] of [[{ abc: 1 }]])
        // Should print: {"abc":1}
        console.log(JSON.stringify(x));
    ```

    This is a syntax error: `Uncaught SyntaxError: Invalid destructuring assignment target`
