### ISSUE TITLE
[Feature Request] Flag for disabling implicit coerisions

### ISSUE THREAD

**Issue by redradist** [microsoft/TypeScript#39194]
I would like to suggest to introduce a new flag for disabling implicit type coercion at all:
```typescript
let strange_boolean: any = true;
let strange_string: string = "1";
console.log(strange_boolean == strange_string);
```
This code compiles ... but I want that this code produce error and compiles only if:
```typescript
let strange_boolean: any = true;
let strange_string: string = "1";
console.log(String(strange_boolean) == strange_string);
```
or
```typescript
let strange_boolean: any = true;
let strange_string: string = "1";
console.log(Boolean(strange_boolean) == Boolean(strange_string));
```

This make `Typescript` even more safe !! ;)

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by redradist** [comment]
@RyanCavanaugh One additional questoin ...

Why for unknown type not enforced explicit conversion to appropriate type ?

I mean:
```typescript
let strange_boolean: unknown = true;
let strange_string: string = "1";
console.log(strange_boolean == strange_string); // Error, use explicit type conversion for type unknown like this String(strange_boolean)
```

In such way there is available default JavaScript behavior as well as "safe" behavior ...
