### ISSUE TITLE
Cannot set property  on #<Object> which has only a getter

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#39195]
**TypeScript Version:**  4.0.0-dev.20200622

**Search Terms:**

**Repo**
1. In the VS Code code base
1. Revert [this change](https://github.com/microsoft/vscode/commit/a8f1fedaf682f9b03671fc4088dd79f9a283ce68#diff-b9480969594d18cfd1c9f13ff3ace0ad) in `grid.ts`
1. Recompile VS Code (`yarn run watch`
1. Start VS Code

**Bug:**

VS Code doesn't start due to the following exception

```
/Users/matb/projects/vscode/out/bootstrap-window.js:215 TypeError: Cannot set property GridViewSizing of #<Object> which has only a getter
    at Object.<anonymous> (/Users/matb/projects/vscode/out/vs/base/browser/ui/grid/grid.js:136)
    at Function.Module._invokeFactory (/Users/matb/projects/vscode/out/vs/loader.js:1040)
    at Module.complete (/Users/matb/projects/vscode/out/vs/loader.js:1050)
    at ModuleManager._onModuleComplete (/Users/matb/projects/vscode/out/vs/loader.js:1671)
...
```

This is triggered on a line that looks like: 

```js
    exports.GridViewSizing = Sizing;
```

**Comment by mjbvz** [comment]
@RyanCavanaugh This seems like a regression from 4.0.0-dev.20200615. Possibly related to #38809?

**Comment by weswigham** [comment]
Wow, so it looks like there's a bug in our namespace export emit - namely, `export namespace Sizing` is adopting the reexport from
`export { Orientation, Sizing as GridViewSizing, IViewSize, orthogonal, LayoutPriority } from './gridview';` - there shouldn't _be_ a `    exports.GridViewSizing = Sizing;`, _since the local `Sizing` namespace isn't exported as `GridViewSizing`_. Here's a minimal repro:
```ts
// @filename: gridview.ts
export type Sizing = any;
export namespace Sizing {
	export const Distribute = { type: 'distribute' };
}
// @filename: index.ts
export { Sizing as GridViewSizing } from './gridview';
export namespace Sizing {
	export const Distribute = { type: 'distribute' };
}
```
I'm working on it now.
