### ISSUE TITLE
Allow partial (subset) type matching

### ISSUE THREAD

**Issue by jbrantly** [microsoft/TypeScript#392]
Various libraries have a concept of applying partial updates to an object. For example:

http://backbonejs.org/#Model-set
http://facebook.github.io/react/docs/component-api.html#setstate

Take the following example (to roughly mimic Backbone)

```
interface Person {
    firstName: string
    lastName: string
    phoneNumber: string
}

var model = {
    set: function(data: Person) {}
}

model.set({
    phoneNumber: '405-555-1254'
})
```

In this case an error is thrown saying that properties are missing. One solution is to make all of the properties in the interface optional. However, that may not be desirable; I may actually want those properties to be required in other locations and only optional in this specific context. I would like to propose a feature where in a certain context a new type is created on-the-fly based on another type where all properties of the base type are optional. For example:

```
Person? => {
    firstName?: string
    lastName?: string
    phoneNumber?: string
}
```

and therefore the following would work:

```
var model = {
    set: function(data: Person?) {}
}

model.set({
    phoneNumber: '405-555-1254'
})
```

I think this would also work particularly well in conjunction with my other suggestion #391 

```
set: function(data: Person?!) {}
```

Where zero or more properties from Person will match but ONLY properties from Person will match.

**Comment by silhouettes** [comment]
+1

**Comment by realyze** [comment]
+1 This would make mongo projections in TS much safer.

**Comment by BowserKingKoopa** [comment]
This should be reopened.  This is a thing.

**Comment by jbrantly** [comment]
@BowserKingKoopa I think this is essentially reopened in #4889. I would track there.
