### ISSUE TITLE
TS 2322 Type is not assignable to Partial<GENERIC> when GENERIC extends another generic

### ISSUE THREAD

**Issue by n8jadams** [microsoft/TypeScript#39207]
**TypeScript Version:**  4.0.0-dev.20200623

**Search Terms:** Inherited generics TS 2322 Type not assignable to partial generic type that extends another generic

**Code**

```ts
interface VALID_EXP_TYPE {
	id: string
}

interface GatheringExpChildMachineBaseContext<TYPE> {
	id?: string
	originalData: TYPE
	order: number
}

function createChildMachine<
	TYPE extends VALID_EXP_TYPE,
	CHILD_CTX extends GatheringExpChildMachineBaseContext<TYPE>
>(): void {
	const onServerEvent = (serverData: TYPE): Partial<CHILD_CTX> => {
		// Type '{ id: string; originalData: TYPE; }' is not assignable to type 'Partial<CHILD_CTX>'.ts(2322)
		return {
			id: serverData.id,
			originalData: serverData
		}
	}
}
```

**Expected behavior:**
No error

**Actual behavior:**
`TS2322: Type '{ id: string; originalData: TYPE; }' is not assignable to type 'Partial<CHILD_CTX>'.`

**Playground Link:** https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200622#code/JYOwLgpgTgZghgYwgAgOJzAC2qA5gUQA8AHAYU2ABsATAWUQpAgCE4BnCUge3AkLAA8AFQCaABXwA+ZAG8AUAEhg1APwAuZGzBQ8irjtyg4lACIY4G0RL1Rq0DSACuAWwBG0OQF85c0JFiIKABqAIIAMgCSJgD6+AAaYtFW+LKKyhpaOiC4Xj4wjiAIYMA8yAhQEBicFDT0CIwQAorJyHyQINRsyKGRMfGJyQA0iqQAEhFhMaRCca38EB1d6Fg42URkNXQMoCzsnDyQ-MLiUnKSABQAlBoAblzKqQoIPFrIPADK0DfQ+N-gyABeZDnDhQb5QMxgCzIZLXZBiOBQYrGARjCZTGbSAHSeQKBQVMCOKAgR549KaL7QSFwAB0ymGeIU+mAhhAxmpGUpEPMigU3j5uSAA

**Related Issues:**
I found a whole slew of them that were almost the same. All of them are marked as `working as intended`, but the problem clearly still persists.
* https://github.com/Microsoft/TypeScript/issues/19467
* https://github.com/microsoft/TypeScript/issues/19388
* https://github.com/microsoft/TypeScript/issues/17071
* https://github.com/microsoft/TypeScript/issues/17071

**Comment by RyanCavanaugh** [comment]
This is a correct error, which is why you found a bunch of other "working as intended" issues. `Partial<CHILD_CTX>` might be something like `{ originalData: { id: "only this string" } }`, which is not necessarily satisfied by `TYPE`

**Comment by n8jadams** [comment]
Thanks for the quick response.

I'm just having a hard time wrapping my head around this, because I thought that something like `{ originalData: { id: "only this string" } }` _would_ satisfy `TYPE`, because `TYPE extends VALID_EXP_TYPE`, or `TYPE extends { id: string }`...

I guess since `TYPE` is a generic, whatever is passed in could potentially not have an id. I thought that's why I needed to extend `VALID_EXP_TYPE`. Is there a better way to enforce that any `TYPE` generic argument has a field for id?

Something like

```typescript
function createChildMachine<
	TYPE hasToAtLeastConformTo { id: string }, // <--
	CHILD_CTX extends GatheringExpChildMachineBaseContext<TYPE>
>(): void {}
```

**Comment by RyanCavanaugh** [comment]
Your function has two type parameters when it should have none (since there are no inputs to correlate with each other or with the output); I can't really advise on the right way to write it in the way you want. Once you have actual inputs with which to form a generic relationship, it's easier to demonstrate why the assignability works the way it does.

**Comment by n8jadams** [comment]
This is mostly because I was trying to extract out the bare minimum to reproduce this error I was running into, it's very contrived. Here's a bit more complete example, although still contrived

```typescript
interface ChildMachineBaseContext<TYPE> {
	id?: string
	originalData: TYPE
	order: number
}

interface VALID_EXP_TYPE {
	id: string
}

enum INPUT_TYPES {
	TEXT_OPTIONAL,
	TEXT_REQUIRED,
	EMAIL_OPTIONAL,
	EMAIL_REQUIRED,
	DATE_OPTIONAL,
	DATE_REQUIRED
}

type FieldNamesConfig<T, C> = {
	[key in keyof Omit<T, 'id' | '__typename'>]: {
		type: INPUT_TYPES
		customValidation?: (context: C) => string
		// This is only for WorkExperience endDate pretty much
		customDefaultContextValue?: any
	}
}

function createChildMachine<
	TYPE extends VALID_EXP_TYPE,
	CHILD_CTX extends ChildMachineBaseContext<TYPE>
>(fieldNamesConfig: FieldNamesConfig<TYPE, CHILD_CTX>): void {
	const onServerEvent = (serverData: TYPE): Partial<CHILD_CTX> => {
		return {
			id: serverData.id,
			originalData: serverData
		}
	}

	const onChangeEvent = (fieldName: keyof TYPE, value: TYPE): Partial<CHILD_CTX> => {
		if (Object.keys(fieldNamesConfig).includes(fieldName)) {
			return {
				[fieldName]: {
					value,
					error: false,
					errorMessage: ''
				}
			}
		}
		return {}
	}
}

```
