### ISSUE TITLE
[Feature Request] Flag for disabling implicit coerisions

### ISSUE THREAD

**Issue by redradist** [microsoft/TypeScript#39209]
## Search Terms

safe typescript, predictable behavior, no implicit coercion

## Suggestion

I would like to suggest to introduce a new flag for disabling implicit type coercion at all
Something like this:
```console
--predicatableJs
```
Or some other flag

## Use Cases

To make `Typescript` even more safe

I want to enforce my team to use only predictable features and if they want old style behavior, just to write another module or disable warning at the top of the file (in such way all reviewers of this files will see that)

## Examples

Instead of writing either:
```typescript
let strange_boolean: any = true;
let strange_string: string = "1";
console.log(strange_boolean == strange_string);
```
or
```typescript
let strange_number: any = 2;
let strange_string: string = "1";
console.log(strange_number == strange_string);
```

I want to enforce that this code produce error and compiles only if there is explicit cast:
```typescript
let strange_boolean: any = true;
let strange_string: string = "1";
console.log(String(strange_boolean) == strange_string);
```
```typescript
let strange_boolean: any = true;
let strange_string: string = "1";
console.log(Boolean(strange_boolean) == Boolean(strange_string));
```
```typescript
let strange_number: any = 2;
let strange_string: string = "1";
console.log(String(strange_number) == strange_string);
```
```typescript
let strange_number: any = 2;
let strange_string: string = "1";
console.log(strange_number == Number(strange_string));
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We're not going to add a flag that causes errors on `any`, so that's right out. A flag for disabling boolean coercion is discussed at #14114

**Comment by redradist** [comment]
> 
> 
> We're not going to add a flag that causes errors on `any`, so that's right out. A flag for disabling boolean coercion is discussed at #14114

I am not taking about `boolean` coercion, but about `coercion` at all

I want to enforce users to write by default safe code, that's all

**Comment by redradist** [comment]
@RyanCavanaugh Have you seen my comment ? Will you remove tag `Duplicate` ?

**Comment by redradist** [comment]
@ahejlsberg I just want to call to you as Lead of the language ...

Don't you think this Feature Request should be implemented ? This very useful that make `TypeScript` even more safe ...

**Comment by RyanCavanaugh** [comment]
@redradist We're tracking this adequately; thank you for the feedback. See also #38905
