### ISSUE TITLE
Argument of any no longer matches `<T>(x: T) => T` in overload set

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#39208]
Based on code from knockout on DT:

```ts
interface Punch {
    <T>(value: T): T;
    <T = any>(value: null): T | null
}
function x(p: Punch) {
  var wat = p<number>(5 as any)
  var wit = p<number>('hi')
  var wot = p<number>(5)
}
```

**Expected behavior:**

`wat: number, wit: number, wot: number`

**Actual behavior:**

`wat: number | null, wit: number | null, wot: number`

**Comment by sandersn** [comment]
Looks like it only repros when the second overload's parameter type is `null`; I tried `never` and `{ random, object, properties }` and the first overload gets chosen.

**Comment by sandersn** [comment]
Works on nightly from 06/15; fails on nightly from 06/20; we failed to publish 16,17,18,19.

**Comment by sandersn** [comment]
Bisecting shows the cause to be #35282. Doesn't really make sense though.

**Comment by sandersn** [comment]
Turns out 905 lines changed in the checker, so it's probably a minor transliteration error.

**Comment by RyanCavanaugh** [comment]
Doesn't appear to be any user-encountered impact from this
