### ISSUE TITLE
document.createElement always marked deprecated

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#39212]
**TypeScript Version:**  4.0.0-dev-20200622

**Search Terms:**
- deprecated

**Code**
For the JS
```js
document.createElement('a');
```

**Bug:**

`createElement` is always rendered as deprecated

![Screen Shot 2020-06-23 at 1 42 05 PM](https://user-images.githubusercontent.com/12821956/85459722-57521200-b557-11ea-9aea-7d56343a55ad.png)

I believe this is because one of the `createElement` overloads is deprecated

/cc @Kingwl @DanielRosenwasser We will need to fix this before we can ship `@deprecated` support in the stable version of VS Code

**Comment by mjbvz** [comment]
Ideally we should determine when a deprecated overload is being called. If that is not possible right now, I think we should be conservative and only mark a call deprecated if all of its overloads are deprecated

**Comment by Kingwl** [comment]
okay, I'll take a look soon

**Comment by jrieken** [comment]
Using 4.0.0-dev20200708 I see deprecation warnings as below. Not sure if this isn't the latest release (tho using `ms-vscode.vscode-typescript-next`) or if this is the same as the createElement-issue

<img width="1418" alt="Screenshot 2020-07-16 at 14 24 44" src="https://user-images.githubusercontent.com/1794099/87670540-2d63c800-c770-11ea-9539-089b196328c8.png">

**Comment by Kingwl** [comment]
> Using 4.0.0-dev20200708 I see deprecation warnings as below. Not sure if this isn't the latest release (tho using `ms-vscode.vscode-typescript-next`) or if this is the same as the createElement-issue. 
> 
> <img width="1418" alt="Screenshot 2020-07-16 at 14 24 44" src="https://user-images.githubusercontent.com/1794099/87670540-2d63c800-c770-11ea-9539-089b196328c8.png">
> 
> (same with 20200712)

It's already fixed in nightly build yesterday(utc+8, or today)
