### ISSUE TITLE
TypeScript language service completion details command cannot handle multiple results with the same name

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#3921]
Logically - this followed from the `"completionEntryDetails"` command taking an array of string names as its argument. This can be an issue in situations like so:
```ts
function get() {}
class A {
    ge
}
```
`ge` can be validly completed with either the `get` function call or the `get` keyword (the same name), according to the language service (which may be another error), both of which resolve to the details of the `function` typed symbol.

Resolving this would probably involve a breaking change in the service (altering completions to return an ID of some kind and making `entryNames`). This bug surfaces in VS Code at present:
![image](https://cloud.githubusercontent.com/assets/2932786/8760716/70f52cb4-2ce1-11e5-96ee-3c6ea458f4d7.png)
![image](https://cloud.githubusercontent.com/assets/2932786/8760719/823aa97c-2ce1-11e5-8a89-a48678e7472d.png)

**Comment by mhegazy** [comment]
you should not ask for completion entry details on a keyword. CompletionEntry.kind tells you what it is. keywords has no more details associated with them (e.g. documentation or type).

Where i agree that the current API design could have been better, i do not see the need to solve the issue, as it can be easily handled by the host with an simple check.
