### ISSUE TITLE
Readonly + const don't properly guard async calls

### ISSUE THREAD

**Issue by apfelbox** [microsoft/TypeScript#39225]
**TypeScript Version:**  3.9.2 (Playground)

**Search Terms:** readonly const

**Code**

```ts
interface Test {
    test: string | null;
}

declare const a: Readonly<Test>;
function doSth (param: string) : void {}

if (null !== a.test)
{
    doSth(a.test); // ok

    setTimeout(
        () => doSth(a.test), // not ok, should be ok
        1000
    );
}
```

**Expected behavior:**
The code should run fine, as with `const` and `Readonly` the properties of `a` can never be changed.
So the outer check should guard the inner call, even if it is async.

**Actual behavior:**
The async call errors out with "string|null not assignable to string".

**Playground Link:**
https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDKHKRYBcyWUoA5sgD7IgCuANiwNx4C+eeAJhAQs4UFAgD2ILMjjkAShDh9JLAJ4AedFgB8nGExAIwwScmUBlMAAtkACgAOIuAFtylGgEpk5AG7jgfLg8eMAwdsxsyACEALwxMgB0JGAeePhEZuKWVrZwSZgp7MgA9MXI4gDWvBkYEGCowM4Q4kxgtgQZRLZeMdqZ2bn5WB4ANCVlIOLYlWMYVi0sgQBGKJUdncgAjAAMu+vIHpxcQA

**Related Issues:**
I honestly searched, but couldn't find anything. Sorry if I missed it and this is a duplicate!

**Comment by MartinJohns** [comment]
Duplicate of #9998.

> The code should run fine, as with const and Readonly the properties of a can never be changed.

They can't change via this interface, but they can still change. Readonly does not mean immutable.

    const b: Test = a;
    b.test = null;

**Comment by apfelbox** [comment]
> They can't change via this interface, but they can still change. Readonly does not mean immutable.

I understand your point, but with this argument you can practically throw all types out of the window. Because right now you can always get a reference to any variable, or add an `any` cast somewhere to overwrite something.

But ... if we assume this, then we lose nearly all types in TypeScript, as they compile away and some other code can practically always change our values without any guards.. 🤔 

Closing as duplicate of #9998
