### ISSUE TITLE
Add Optional<T, K extends keyof T> to TypeScript standard library

### ISSUE THREAD

**Issue by cnshenj** [microsoft/TypeScript#39223]
## Search Terms
- Optional
- Partial

## Suggestion
`Partial<T>` makes **all** properties optional. It's also a common scenario to make **some** properties optional (e.g. providing default values for some properties).
Add the following type TypeScript standard library, just like `Partial<t>`
```typescript
type Optional<T, K extends keyof T> = Partial<Pick<T, K>> & Pick<T, Exclude<keyof T, K>>;
```

## Use Cases
Provide default values to some properties.

## Examples
```typescript
// doSomething is a function imported from a library
interface Options {
    prop1: string;
    prop2: string;
    prop3: string;
}
function doSomething(options: Options): void { /* ... */ }

// Simplified version
function myDoSomething(options: Optional<Options, "prop3">): void {
    doSomething(Object.assign({ prop3: "default" }, options));
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We've chosen to not add utility type aliases unless they're needed for declaration emit.
