### ISSUE TITLE
Union of unlabled tuple rest args have bad signature help parameter names

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#39227]
![image](https://user-images.githubusercontent.com/972891/85542360-dda93b00-b5cd-11ea-8ebf-7f10ed552c70.png)

```ts
function foo(...args: [string, string] | [number, string, string]
) { 
}

foo(/**/)
```

**Expected**

```
foo(args_0: string, args_1: string): void
foo(args_0: number, args_1: string, args_2: string): void
```

**Actual**

```
foo(args: string, args: string): void
foo(args: number, args: string, args: string): void
```
<!-- snip, filed separately as #39228
![image](https://user-images.githubusercontent.com/972891/85543541-04b43c80-b5cf-11ea-882b-7f8ff2139e93.png)

```ts
function foo(...args: [string, string] | [number, string, string]
) {
    
}

foo(123/**/,)
```

**Expected**: first parameter is considered the current parameter
**Actual**: second parameter is always the current parameter
--!>

https://www.typescriptlang.org/v2/play?ts=4.0.0-dev.20200623#code/PQKhFgCgAIWgBALgTwA4FNoG8AUA6AgQwCcBzAZwC5oBtcxYgSwDtSAaaep1gXWgB9azAK4BbAEbpiHLi3acGcngEpoAXgB80AG4B7RgBMAvlFjAoAM2HMAxoka7m0C7t34iZKrVmsZi3gJCYpLSCtzyPqQ8UKpYptAJUCaQlq44AIwATADMbMpAA

**Comment by ShuiRuTian** [comment]
Sorry for ask, it has been detailed, but I could not understand the second one, what is its issue?
