### ISSUE TITLE
HTMLFrameElement deprecated or not?

### ISSUE THREAD

**Issue by evmar** [microsoft/TypeScript#39234]
**TypeScript Version:**  [current github master](https://github.com/microsoft/TypeScript/blob/785e44704c56ecfe7f795a2f287f51090173f5cb/lib/lib.dom.d.ts#L6801)

**Search Terms:** HTMLFrameElement deprecated

**Code**

HTMLFrameElement looks like:

```ts
interface HTMLFrameElement extends HTMLElement {
    /**
     * Retrieves the document object of the page or frame.
     */
    /** @deprecated */
    readonly contentDocument: Document | null;
```

**Expected behavior:**
If the whole thing is deprecated, the interface should be marked deprecated.

**Actual behavior:**
Each individual field in the interface is marked deprecated, but not the outer interface.

**Playground Link:** n/a, deprecated is only used by linters (I think?)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@Kingwl what's the intended setup here?

**Comment by Lonli-Lokli** [comment]
Looks like whole interface is /** @deprecated */ now
