### ISSUE TITLE
Bug with apply+concat and a function argument?

### ISSUE THREAD

**Issue by vote539** [Microsoft/TypeScript#3924]
The following code compiles.

```typescript
function myFunction(arg1:string, arg2:(msg:string)=>void){
	// do stuff
}
var args = ["hello", function(msg){ /* do stuff */ }];
myFunction.apply(myFunction, args);
```

But the following code does not compile, even though the variable `args` is of the same type as above.

```typescript
function myFunction(arg1:string, arg2:(msg:string)=>void){
	// do stuff
}
var args = ["hello"].concat(function(msg){ /* do stuff */ });
myFunction.apply(myFunction, args);
```

It throws the following error.

```
>> src/workspace.ts(20,29): error TS2345: Argument of type '(msg: any) => void' is not assignable to parameter of type 'string'.
```

Any idea why?  Is this a bug in my code or a bug in the TypeScript compiler?

**Comment by kitsonk** [comment]
When you create the second array the way you do, it implies a type of `string[]`, where as the first, `any[]` is implied.  One way of working around it is:

```typescript
function myFunction(arg1:string, arg2:(msg:string)=>void){
    // do stuff
}
var args = (<any[]> ["hello"]).concat(function(msg){ /* do stuff */ });
myFunction.apply(myFunction, args);
```

**Comment by vote539** [comment]
That makes sense, and so does the workaround.  Thanks for the tip.

**Comment by RyanCavanaugh** [comment]
http://stackoverflow.com/questions/31495573/typescript-applyconcat-with-a-function-argument

Note: Please don't cross-post. You end up consuming two people's time to get the answer a few minutes earlier.

**Comment by vote539** [comment]
Yeah, that was pretty irresponsible, I was too much in a hurry :disappointed:
