### ISSUE TITLE
Poor inference for variadic tuple rest element when other inference targets are not rest parameters

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#39244]
I believe that we mentioned this at some point at a design meeting or in https://github.com/microsoft/TypeScript/pull/39094, but don't know if we have an issue.

So I wrote a `partialApply` function (similar to `curry` in https://github.com/microsoft/TypeScript/pull/39094).

```ts
function partialApply<T extends readonly any[], U extends readonly any[], R>(f: (...args: [...T, ...U]) => R, headArgs: T) {
    return (...tailArgs: U) => f(...headArgs, ...tailArgs)
}
```

The main difference between the two is that `headArgs` isn't a rest parameter.

```diff
- function partialCall<T extends readonly any[], U extends readonly any[], R>(f: (...args: [...T, ...U]) => R, ...headArgs: T) {
+ function partialApply<T extends readonly any[], U extends readonly any[], R>(f: (...args: [...T, ...U]) => R, headArgs: T) {
```

Still, I'd expect TypeScript to give me good types and appropriate errors:

```ts
function partialCall<T extends readonly any[], U extends readonly any[], R>(f: (...args: [...T, ...U]) => R, headArgs: T) {
    return (...b: U) => f(...headArgs, ...b)
}

function foo(x: string, y: number, z: boolean) {
}

// Expected: (y: number, z: boolean) => void
// Actual: (...b: readonly any[]) => void
const f1 = partialCall(foo, ["hello"]);


// Expected: error
// Actual: no error
const f2 = partialCall(foo, [100]);
```

This is weird because switching back to a rest parameter gets the right behavior (because we special cased inference there).

```ts
function partialCall<T extends readonly any[], U extends readonly any[], R>(f: (...args: [...T, ...U]) => R, ...headArgs: T) {
    return (...b: U) => f(...headArgs, ...b)
}

function foo(x: string, y: number, z: boolean) {
}

const f1 = partialCall(foo, "hello");
const f2 = partialCall(foo, 100);
```

additionally, switching the constraint from `readonly any[]` to `readonly unknown[]` causes errors.

```ts
function partialCall<T extends readonly unknown[], U extends readonly unknown[], R>(f: (...args: [...T, ...U]) => R, headArgs: T) {
    return (...b: U) => f(...headArgs, ...b)
}

function foo(x: string, y: number, z: boolean) {
}

const f1 = partialCall(foo, ["hello"]);
//                     ~~~
// Argument of type '(x: string, y: number, z: boolean) => void' is not assignable to parameter of type '(...args: unknown[]) => void'.
//   Types of parameters 'x' and 'args' are incompatible.
//     Type 'unknown' is not assignable to type 'string'.
```

**Comment by ahejlsberg** [comment]
It's a tricky problem. We currently first infer an arity for `T` from the number of rest arguments, then infer from the function argument to `[...T, ...U]` using that arity to determine the cut point, and then use the actual inference for `T` as the contextual type for the rest arguments. It's not clear how we would infer an arity (and only an arity) from a type parameter used in arbitrary positions in a parameter list _without_ doing full inference--which we can't do in that initial phase if `T` is also supposed to be a contextual type. I suppose we could further look for parameters with singleton type parameter types and infer an arity from an array literal used as an argument or from an actual expression (which would then be processed without a contextual type available from `T`, but that rarely would matter).

**Comment by ahejlsberg** [comment]
Regarding the lack of errors with the `readonly any[]` constraint, that's because we make no inferences for `U` and therefore default it to `readonly any[]`, which is super permissive. Also, there is nothing in your declarations to cause a tuple type to be inferred for an array literal passed for `T`, so we infer array types. A better declaration is:

```ts
function partialCall<T extends unknown[], U extends unknown[], R>(f: (...args: [...T, ...U]) => R, headArgs: [...T]) { ... }
```

That then errors in both cases because we don't make an inference for `U`, but the error messages are more meaningful.

**Comment by ahejlsberg** [comment]
BTW, notice that inferences made to variadic elements _always_ infer mutable types, even if the source is readonly. That's because instantiation of variadic elements in turn ignores readonly in the source. The readonly state comes only from the containing tuple and never from variadic elements. A because of all this, you don't need `readonly` in the constraint of type parameters that are only used in variadic element positions.

**Comment by DanielRosenwasser** [comment]
Wanted to make an amendment to that last signature to allow readonly arrays/tuples

```ts
function partialCall<T extends unknown[], U extends unknown[], R>(f: (...args: [...T, ...U]) => R, headArgs: readonly [...T]) { ... }
```

**Comment by moward** [comment]
I don't know if this helps at all, but I have a real use case which I believe hits this same limitation:
```ts
function partialCall<T extends Readonly<any[]>, U extends Readonly<any[]>, R>(
  f: (...args: [...T, ...U]) => R,
  getHeadArgs: () => T
) {
  return (...b: U) => f(...getHeadArgs(), ...b);
}
```
We use this in some classes to take in a pure function, partially apply some instance variables, and get back the partially-applied function to use as callback:
```ts
function pureFunctionCallback(foo: string, bar: boolean) : string { ... }

class MyClass {

  private foo: string;

  private myCallback = partialCall(pureFunctionCallback, () => [foo] as const);
}
```
We had some pretty ugly code using `typescript-tuple` that made this work safely before, but after switching to TS 4.0 went with the above variadic tuple approach, only to later find out the returned function type had parameters `any[]`.
