### ISSUE TITLE
Where is the static abstract ? 

### ISSUE THREAD

**Issue by Hyoukjoo** [microsoft/TypeScript#39250]
## Search Terms

3.9.4 version

## Suggestion

I sincerely hope

## Use Cases

Sometimes

## Examples

`static abstract create() {}`

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment]
Here it is #34516
