### ISSUE TITLE
Function is assignable to interface describing call signature, but not to generic T extending interface

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/TypeScript#3925]
If you have an interface describing a call signature (e.g. `Func<A, R>` above), assignability with generics seems to be a bit weird. It seems you can assign a `(...args: A[]) => R` to a `Func<A, R>`, but not to a `T` extending `Func<A, R>`. 

Please see this [playground link](http://www.typescriptlang.org/Playground#src=%09interface%20Func%3CA%2C%20R%3E%20%7B%0A%09%09(...args%3A%20A%5B%5D)%3A%20R%3B%0A%09%7D%0A%09%0A%09function%20test%3CT%20extends%20Func%3Cstring%2C%20any%3E%3E()%20%7B%0A%09%09let%20fn%20%3D%20(...args%3A%20string%5B%5D)%20%3D%3E%20(%7B%7D)%3B%0A%09%09%09%0A%09%09let%20a%3A%20Func%3Cstring%2C%20any%3E%20%3D%20fn%3B%20%2F%2F%20Works%0A%09%09let%20b%3A%20T%20%3D%20fn%3B%20%2F%2F%20Doesn't%20work%0A%09%7D) for a demonstration. The code is reproduced below:
```ts
	interface Func<A, R> {
		(...args: A[]): R;
	}
	
	function test<T extends Func<string, any>>() {
		let fn = (...args: string[]) => ({});
			
		let a: Func<string, any> = fn; // Works
		let b: T = fn;                 // Doesn't work
	}
```
In case anyone is curious, this is the actual use case where I ran into this problem:
```ts
	interface Func<A, R> {
		(...args: A[]): R;
	}
	
	type Primitive = string|number;
	type PrimitiveFunc = Func<Primitive, any>;
	
	let memoized: MethodDecorator;
	memoized = function memoizedMethod<T extends PrimitiveFunc>(target: Object, propertyKey: string|symbol, descriptor: TypedPropertyDescriptor<T>) {
		descriptor.value = memoizeFn1(descriptor.value); // Doesn't work
		descriptor.value = memoizeFn2(descriptor.value); // Works
		return descriptor;
	}
	
	// Works
	function memoizeFn1(fn: PrimitiveFunc): PrimitiveFunc {
		return function (...args: Primitive[]) {
			// Do something here ...
		}
	}
	
	// Doesn't work
	function memoizeFn2<T extends PrimitiveFunc>(fn: T): T {
		return function(...args: Primitive[]) {
			// Do something here ...
		}
	}
```

**Comment by ahejlsberg** [comment]
This is by design. It doesn't have to do with call signatures, but rather with the assignment compatibility rules for type parameters. Given a type parameter T with a constraint C (that is `<T extends C>`), T is assignable to C, but not the other way around. This is because a type parameter is a proxy for some type that is known to satisfy the constraint but is likely to have more members. It wouldn't be safe to allow assignment from a value of the constraint type because that type is likely to be missing members.
