### ISSUE TITLE
TypeScript language service freezing or dying in a large monorepo

### ISSUE THREAD

**Issue by bajtos** [microsoft/TypeScript#39263]
*TS Template added by @mjbvz*

**TypeScript Version**: 3.9.5

**Search Terms**
- monorepo

---

Issue Type: <b>Bug</b>

TypeScript language service is often freezing or dying when working in https://github.com/strongloop/loopback-next, which is a large monorepo using lerna and TypeScript Project References.

Steps to reproduce:

1. Clone loopback-next
2. Run `npm install`
3. Open VS Code
4. Open any TS file (preferably something else than `**/index.ts`)
5. Make some changes (e.g. whitespace formatting)
6. Save the file to trigger "organize imports"
7. The operation takes ages to complete

After working this way for a while, VS Code shows a warning that TS Language Service is dying too frequently and offers to fill a bug report (which I am doing here).

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 16|
|Memory (System)|16.00GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.7.0
mermaid-markdown-syntax-highlighting|bpr|1.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.0
vscode-pull-request-github|Git|0.17.0
vscode-test-explorer|hbe|2.19.1
vscode-drawio|hed|0.7.1
rest-client|hum|0.24.1
vscode-docker|ms-|1.3.1
vsliveshare|ms-|1.0.2377
vsliveshare-audio|ms-|0.1.85
polacode|pnp|0.3.4
vscode-graphql|Pri|0.2.14
vscode-yaml|red|0.8.0
shopify-liquid|sis|2.3.0
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
vim|vsc|1.14.5
vscode-mermaid-preview|vst|1.5.2
markdown-all-in-one|yzh|3.1.0
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.4.2

(1 theme extensions excluded)

</details>

**Comment by sheetalkamat** [comment]
I dont repro this: 
```
Info 606  [9:58:12.489] request:
    {"seq":107,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"c:/temp/loopback-next/packages/authorization/src/authorize-interceptor.ts"}}}}
Perf 607  [9:58:12.516] 107::organizeImports: elapsed time (in milliseconds) 27.1891
Info 608  [9:58:12.516] response:
    {"seq":0,"type":"response","command":"organizeImports","request_seq":107,"success":true,"body":[{"fileName":"c:/temp/loopback-next/packages/authorization/src/authorize-interceptor.ts","textChanges":[{"start":{"line":6,"offset":1},"end":{"line":19,"offset":1},"newText":"import {\n  asGlobalInterceptor,\n  bind,\n  BindingAddress,\n  // eslint-disable-next-line @typescript-eslint/no-unused-vars\n  config,\n  Context,\n  Interceptor,\n  InvocationContext,\n  Next,\n  NonVoid,\n  Provider\n} from '@loopback/core';\nimport {SecurityBindings, UserProfile} from '@loopback/security';\nimport debugFactory from 'debug';\nimport {getAuthorizationMetadata} from './decorators/authorize';\nimport {AuthorizationBindings, AuthorizationTags} from './keys';\nimport {\n  AuthorizationContext,\n  AuthorizationDecision,\n  AuthorizationError,\n  AuthorizationOptions,\n  Authorizer\n} from './types';\nimport {createPrincipalFromUserProfile} from './util';\n"},{"start":{"line":19,"offset":1},"end":{"line":20,"offset":1},"newText":""},{"start":{"line":20,"offset":1},"end":{"line":21,"offset":1},"newText":""},{"start":{"line":21,"offset":1},"end":{"line":22,"offset":1},"newText":""},{"start":{"line":22,"offset":1},"end":{"line":23,"offset":1},"newText":""},{"start":{"line":23,"offset":1},"end":{"line":30,"offset":1},"newText":""},{"start":{"line":30,"offset":1},"end":{"line":31,"offset":1},"newText":""}]}]}
```

We would need more specific repro steps to investigate this

**Comment by bajtos** [comment]
Thank you @sheetalkamat for taking a look! To be honest, I was not able to reproduce the crash again either. My main pain point is slow start of the language service, which should be hopefully improved by [partial editing mode](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#partial-editing-mode) that's coming in v4.0. Let's close this issue as invalid, I'll open a new one if I manage to get a reproducible problem with the new version.
