### ISSUE TITLE
Generator functions cannot be overloaded

### ISSUE THREAD

**Issue by birtles** [microsoft/TypeScript#39274]
**TypeScript Version:**  3.9.2

**Search Terms:** overload generator

**Expected behavior:** It should be possible to overload generators (including async generators) just as it is possible to overload functions.

**Actual behavior:** `TS1222 An overload signature cannot be declared as a generator` is returned.

**Related Issues:** #25710

**Code**
```ts
// NOT using generators
function yer(type: 'a'): Array<number>;
function yer(type: 'b'): Array<string>;

function yer(type: 'a' | 'b'): Array<any> {
    if (type === 'a') {
        return [0, 1, 2];
    }
    return ['hello', 'there'];
}

// Using generators
function* bleh(type: 'a'): IterableIterator<number>;
function* bleh(type: 'b'): IterableIterator<string>;

function* bleh(type: 'a' | 'b'): IterableIterator<any> {
    if (type === 'a') {
        yield 0;
        yield 1;
        yield 2;
        return;
    }

    yield 'hello';
    yield 'there';
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function yer(type) {
    if (type === 'a') {
        return [0, 1, 2];
    }
    return ['hello', 'there'];
}
function* bleh(type) {
    if (type === 'a') {
        yield 0;
        yield 1;
        yield 2;
        return;
    }
    yield 'hello';
    yield 'there';
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/PTAEDkHkBVQVwM4EsB2BzUaCmKsCcBDAFwHs8EBYAKADM4UBjIpElUAT3wAoj2AHLAC5QAcgIiAlMICCeQuwA8KOAFsARvgB8Abmp1GzVh268BwkWsky5BRQiJ5UaHdT30mLNpzw9+Q0eKgAD6illKgsvIKBCjsmqAA3tSgKaBINKC+AqAAvHkBkonJqSV4WERweGwA2gAMADSgAIyNAEwAurpUJQC+xSllFVWg1SIAFlgANpMkIo0iRBNlIp3UfVTUIKAAqsjomDj4xGSUtO6GKABUoGqTWGNZ-mJWoACSREe3WO9HpHhKqg0eBcZwMnmuXwepieYWEP0IX3hx3+9kc6BBbjBrAhdyhfnMgRCFheSMRH0If2isXiSW6qXSmWhuXyzwkRTpJRS7CQUwAJqBal1OaluXzmkLhRweZN+a0JcLBpUUPLQOt+lKxeMpjMRCrRTLRIt8FhdWsgA)

**Comment by ilogico** [comment]
As far as I can tell, generator functions don't have a representation in the type system.
They are functions that return generators, just like async functions are merely functions that return promises.

That being said, you can overload them normally. Just remove the `*` like [this](https://www.typescriptlang.org/play/#code/PTAEDkHkBVQVwM4EsB2BzUaCmKsCcBDAFwHs8EBYAKADM4UBjIpElUAT3wAoj2AHLAC5QAcgIiAlMICCeQuwA8KOAFsARvgB8Abmp1GzVh268BwkWsky5BRQiJ5UaHdT30mLNpzw9+Q0eKgAD6illKgsvIKBCjsmqAA3tSgKaBINKC+AqAAvHkBkonJqSV4WERweGwA2gAMADSgAIyNAEwAurpUJQC+xSllFVWg1SIAFlgANpMkIo0iRBNlIp3UfVTUIKAAqsjomDj4xGSUtO6GbGqTWGNZ-mJWoACSREdXWC9HpHhKqhp4LjOBk8oHet1M9zCwk+hHeMOOP3sjnQgLcwNYACpQddwX5zIEQhZHvC4a9CN9orF4kluql0pkIbl8g8JEVaSUUuwkFMACagWpdDmpLm85qCoUcbmTPmtcVCwaVFBy0DrfqS0XjKYzETKkXS0SLfBYHVrahAA).

**Comment by birtles** [comment]
> That being said, you can overload them normally. Just remove the `*` like [this](https://www.typescriptlang.org/play/#code/PTAEDkHkBVQVwM4EsB2BzUaCmKsCcBDAFwHs8EBYAKADM4UBjIpElUAT3wAoj2AHLAC5QAcgIiAlMICCeQuwA8KOAFsARvgB8Abmp1GzVh268BwkWsky5BRQiJ5UaHdT30mLNpzw9+Q0eKgAD6illKgsvIKBCjsmqAA3tSgKaBINKC+AqAAvHkBkonJqSV4WERweGwA2gAMADSgAIyNAEwAurpUJQC+xSllFVWg1SIAFlgANpMkIo0iRBNlIp3UfVTUIKAAqsjomDj4xGSUtO6GbGqTWGNZ-mJWoACSREdXWC9HpHhKqhp4LjOBk8oHet1M9zCwk+hHeMOOP3sjnQgLcwNYACpQddwX5zIEQhZHvC4a9CN9orF4kluql0pkIbl8g8JEVaSUUuwkFMACagWpdDmpLm85qCoUcbmTPmtcVCwaVFBy0DrfqS0XjKYzETKkXS0SLfBYHVrahAA).

Oh, interesting!

Is there a way to do the same for async generators?

The specific code I am trying to write is as follows:

```typescript
async function* bleh(type: 'a'): AsyncIterableIterator<number>;
async function* bleh(type: 'b'): AsyncIterableIterator<string>;

async function* bleh(type: 'a' | 'b'): AsyncIterableIterator<any> {
    if (type === 'a') {
        yield 0;
        yield 1;
        yield 2;
        return;
    }

    yield 'hello';
    yield 'there';
}
```

**Comment by birtles** [comment]
> Is there a way to do the same for async generators?

Nevermind, I realized I can overload this by removing _both_ `async` and `*`:

```ts
function bleh(type: 'a'): AsyncIterableIterator<number>;
function bleh(type: 'b'): AsyncIterableIterator<string>;

async function* bleh(type: 'a' | 'b'): AsyncIterableIterator<any> {
    if (type === 'a') {
        yield 0;
        yield 1;
        yield 2;
        return;
    }

    yield 'hello';
    yield 'there';
}
```

**Comment by AgainPsychoX** [comment]
Why can't we allow sugar syntax?
