### ISSUE TITLE
Is it possible for tsserver to return all references from a whole project without having to open the files?

### ISSUE THREAD

**Issue by sdogra** [microsoft/TypeScript#39279]
Hello, I'm not sure if this something that is already possible and my configuration is not correct, but here is my question:

I'm currently trying to integrate theia-ide's typescript-language-server (which uses tsserver in the backend) with my frontend to support definition and references requests for all js/ts files in a large codebase - I'm finding it's working quite nicely except it only returns references for files I've already opened (I'm guessing it's indexing the files and storing the info as they are opened).

So for example, when I send a request to find all references for the "getElementById" function, 9 results from the local file show up, then after opening a few more files with that function, I now get results for 75 references to the function in the files I have opened.

Is this the expected behavior? Perhaps my tsconfig.json is not set up correctly (all I did was place it in the root directory that contains all my js/ts files in subdirectories and set allowJs to true) - does anyone know if there would be a way to configure tsserver to return all references within the project?

What I am asking for is similar to how other language servers generate an index with all information beginning from the root directory (i.e. ccls (c++ language server)'s Stand-alone mode: indexes the entire project at then exit) - is this possible with tsserver? I thought having tsconfig.json at the root of my project would accomplish this but it seems like this is not the case.

**Comment by RyanCavanaugh** [comment]
@sheetalkamat can you describe the exact conditions where we find the parent tsconfig? Thanks!

**Comment by sheetalkamat** [comment]
https://github.com/microsoft/TypeScript/blob/master/src/server/editorServices.ts#L3054 has information on how we go look at the parent chain to find ancestor projects. In short if tsconfig found contains the info, then we go look till `projectRootPath` specified at opening of the file to go ahead and see if there are more tsconfigs referencing the found tsconfig. Note that tsconfig project needs to be composite as those are the only projects that can be referenced through project references. These projects arent opened right away. They are just maked to delay open when needed.

While doing findAllRefs we go ahead and actually load these projects. https://github.com/microsoft/TypeScript/blob/master/src/server/editorServices.ts#L3088
