### ISSUE TITLE
Key can't be number in Proxy

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#39272]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
new Proxy({}, { get(target, key) {
    // key is type number | string | symbol which is impossible.
})
```

**Expected behavior:**

`key` be `string | symbol`

**Actual behavior:**

`key` be `number | string | symbol`

![image](https://user-images.githubusercontent.com/5390719/85839674-d6508000-b7cd-11ea-8108-1b3afd433aaa.png)

**Comment by rbuckton** [comment]
Fixed in #35594
