### ISSUE TITLE
Cannot use namespace as a type

### ISSUE THREAD

**Issue by waterplea** [microsoft/TypeScript#39273]
**TypeScript Version:**  3.9.2

**Search Terms:**
namespace type

**Code**

```ts
export const TOKEN = new InjectionToken<CSS>('An abstraction over window.CSS object', {
    factory: () => window.CSS,
});
```

**Expected behavior:**
It compiles properly

**Actual behavior:**
Seems like type generic picks constant instead of global interface

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=3&pc=4#code/KYDwDg9gTgLgBAYwgOwM7wCoHkDSBRAOTgF45lgB3OASWQCtgEYBLFDCAa2GQB4BhAMoCAfAAoA5AEFkcAIYAjdFFlNWMiADdgUOBWbIAJhAoA6QQLgR5DJuIA0cAN4BYAFBwPcAGYqY0AJ4AXHCiAJQkwrr6Rqbmdm4AvqEA3EA

**Comment**
It worked in TS 3.8.x and prior to that.

**Comment by waterplea** [comment]
Just found out it became `namespace` and was `interface`. To be honest, I'm not that versed in terms of namespaces but it was a breaking change for me :( Probably `typeof CSS` would be a workaround.

**Comment by RyanCavanaugh** [comment]
We removed that interface intentionally since it wasn't being used anywhere

**Comment by waterplea** [comment]
How is it not used anywhere when there is global CSS object where you test for CSS features support?
