### ISSUE TITLE
Promise.all(PromiseArray) is not working ( using from variables )

### ISSUE THREAD

**Issue by SeoHyunDeock** [microsoft/TypeScript#39271]
I used "Promise.all" api.

But It it not working when using different return type promise variables.

```
ex.

const foo = async () => 5;
const foo2 = async () => '1';

const arr = [foo(), foo2()];


(async () => await Promise.all(arr))

```

above example is not wokring. 

### error message:
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(Promise<number> | Promise<string>)[]' is not assignable to parameter of type 'Iterable<number | PromiseLike<number>>'

but, below is working

```
const foo = async () => 5;
const foo2 = async () => '1';

(async () => await Promise.all([foo(), foo2()]))

```

why this error is occrued ?

and any solve this problem ?

Thank you.

**Comment by climba03003** [comment]
If I am not wrong.

The upper one use ```lib.es2015.iterable.d.ts``` to evaluate the typing. Which lead to ```Promise.all``` only accept either full ```Promise<number>``` or ```Promise<string>``` array.
The lower one use ```lib.es2015.promise.d.ts``` to evaluate the typing. Which unwrap the array to ```all<T1, T2>(values: readonly [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>]): Promise<[T1, T2]>;``` which can accept ```Promise<number | string>``` array.

If you want to use the upper one. You may try to explicitly set the type of acceptable array.
```typescript
const foo = async () => 5;
const foo2 = async () => '1';

const arr = [foo(), foo2()];

(async () => await Promise.all<string | number>(arr))
```

**Comment by SeoHyunDeock** [comment]
Thank you.
I solve the problem your answer ( using generic )
