### ISSUE TITLE
/// <reference types="foo" /> does not work well with packages that include their own types

### ISSUE THREAD

**Issue by dgoldstein0** [microsoft/TypeScript#39287]
**TypeScript Version:**  3.8.3

**Search Terms:** /// <reference types= /> triple slash reference

**Code**

create a new npm package with a dependency on eventemitter3@4.0.0 (or any other npm package that contains it's own types)

```foo.d.ts
/// <reference types="eventemitter3" />

declare const foo: EventEmitter.EventEmitter;
```

**Expected behavior:** typechecking something that includes this foo.d.ts should pass

**Actual behavior:** the `/// <reference types="eventemitter3" />` does not resolve.  After playing with --traceResolution, it appears that node_modules/@types/ is searched for the package, but node_modules/ itself is not.  Adjusting typeRoots in the tsconfig to include both leads to more problems, as @types/ is then expected to be an npm package.

It's worth mentioning that I also attempted `/// <reference path="eventemitter3" />` and discovered that the `paths` section of the tsconfig is not applied to that.  So it appears there is no supported way to reference a node module that caries it's own types, without knowing the exact relative path from the current file to that module's types.

A hack that works in some cases is `/// <reference types="../eventemitter3" />` but that depends on the node_modules/@types folder existing, which it might not.

**Playground Link:** multi-file issues like this don't seem to be supported by the playground.

**Related Issues:** didn't spot any

**Comment by dgoldstein0** [comment]
I wonder, why is the resolution of /// <reference /> directives different than typescript's normal module resolution?  `import "eventemitter3"` works just fine. it's only the triple-slash references to it that are problematic.

**Comment by RyanCavanaugh** [comment]
> I wonder, why is the resolution of /// directives different than typescript's normal module resolution? 

Different syntax does different things; we do this so that people are able to write more than just the one program that would be possible if it didn't.

**Comment by dgoldstein0** [comment]
I guess I don't understand how it would be limiting if we had something more standard - if module resolution is sufficiently flexible, it should be good enough for declaration files too.  as is, it's multiple things to understand.

Anyhow, that's tangential to the original bug - unless somehow unifying is involved in the fix.  I would definitely be a fan of a solution like `/// <reference module="foo" />` that follows the exact same rules as regular module resolution.

**Comment by dgoldstein0** [comment]
by the way, I don't consider this a question.  This is a bug that I have not found a satisfactory workaround for.  The temporary workaround I figured out was to generate a node_modules/@types/eventemitter3/index.d.ts but I suspect that is going to cause me more headaches and grief in the future.

**Comment by dgoldstein0** [comment]
... though I also don't really understand how you folks are using "question" as a label.  maybe it doesn't mean what I think.

**Comment by dgoldstein0** [comment]
I disagree that this is a question.  How can I reopen this?

In general I expect to be able to `/// <reference types="foo" />` (or some other reference form) and for typescript to be able to find this in my node_modules - whether or not foo contains it's own types, or has a separate @types/ package.  I consider it a shortcoming that, afaict, there is no such form of reference that currently works this way for .d.ts files (normal typescript files can use `import`s).
