### ISSUE TITLE
Negative tuple indexer should not be valid

### ISSUE THREAD

**Issue by cntkillme** [microsoft/TypeScript#39293]
**TypeScript Version:**  4.0.0-dev.20200625

**Search Terms:**
negative tuple indexer

**Code**

```ts
type t1 = [string, number][0]; // string
type t2 = [string, number][1]; // number
type t3 = [string, number][-1]; // (string | number)  ???

type u<t extends any[], u extends number> = t[u];

type u1 = u<[string, number], 0>; // string
type u2 = u<[string, number], 1>; // number
type u3 = u<[string, number], 2>; // undefined
type u4 = u<[string, number], 1.5>; // undefined
type u5 = u<[string, number], -0.5>; // (string | number)  ???
```

**Expected behavior:**
that `type t3 = [string, number][-1];` emits a compile-time error "Tuple type '[string, number]' of length '2' has no element at index '-1'." and `u5` is `undefined`.

**Actual behavior:**
`t3` and `u5` is a union of the types contained in the tuple.

**Playground Link:** [playground link](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200625#code/C4TwDgpgBMCMUF4oG0DOwBOBLAdgcwBoocBXAWwCMIMBdZABhoG4oB6VqdbfAWAChQkGACZEKLrkLFyVWsljM2HUpWr9B0YAGYxaTJKIrZdALQKW7KAAoJ+KAB9pqjAEooUAPxf+68NBIAPMBQEAAewBA4ACaoUACGOCDINEQkIeGRMU6yAHxiwMgkzD4CflAk8EiBetxSRtQpUPQ5Fhy2eL5CJKJVATUG2Q1EsC1Kgxid-jq9-fiGMkNQwqOWJNEQAGa4EFGT5QAsYtXt886NsAB0AKwrHGtRm9u7pV1XR30n440m9Ne31u0HOM3J5vHwgA)

**Comment by DanielRosenwasser** [comment]
Misread the code, so I prematurely marked this as a bug.

In expression positions, if we statically know the index, we will issue an error; otherwise, we'll let it slide.

```ts
declare let x: [string, number];

x[1.5]; // error
x[1.5 as number]; // no error
```

@ahejlsberg any thoughts here?

**Comment by MicahZoltu** [comment]
Maybe it doesn't matter' but this bug is far type indexes, not variable indexes (as in your example).  `type Apple = Banana[-1]`.  Also, we do statically know the the index in all of the examples provided, and they don't error like you say they should.

**Comment by DanielRosenwasser** [comment]
Yeah, I saw that, I mentioned expression positions. The questions are whether we can actually enforce the same checks in type-land and how often it comes up to be worth it if that causes problems.

**Comment by MicahZoltu** [comment]
Ah, I misread *your* comment.  :)  You were saying, "this is what we do with expressions" as a comparison for what we *might* do with types.

**Comment by DanielRosenwasser** [comment]
It's okay, let's chalk it up to Monday 😄
