### ISSUE TITLE
Type deduction seems to be broken inside Generator Functions

### ISSUE THREAD

**Issue by milizhang** [microsoft/TypeScript#39297]
**TypeScript Version:**  4.0.0-dev.20200627 (Repros on 3.9 and 3.8 too)

**Search Terms:** Generator

**Expected behavior:** Function f compiles properly without errors.

**Actual behavior:** Function f fails to build.

**Related Issues:**

**Code**
```ts
enum A
{
    a,
    b
}

interface B
{
    a: A.a;
    b: number;
}

interface C
{
    a: A.b;
    c: string;
}

type D = (B | C);

declare function isA<T> (x: T | A): x is A;

declare function e(): Generator<A, D, (A | D)>;

function* f(): Generator<A, D, D>
{
    let a: (A | D) = A.b;
    const x = yield a; // x is deducted to D
    do
    {
        // 'y' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
        const y = yield a; // Error: Cannot deduct type of y, while TSC knows that a is always of type A here.
        const z = yield A.a; // z is deducted to D - it works if we use a literal.
        a = e().next(y).value;
    }
    while(isA(a));

    // Type '{ a: A; b: number; }' is not assignable to type 'D'.
    //  Type '{ a: A; b: number; }' is not assignable to type 'B'.
    //    Types of property 'a' are incompatible.
    //      Type 'A' is not assignable to type 'A.a'.(2322)
    return {
        a: A.a,
        b: 1234
    };
}

function* g(): Generator<A, D, D>
{
    let a: (A | D) = A.b;
    const x = yield a;
    do
    {
        const y: D = yield a; // This works, and only works if we type it properly as D.
        const z = yield A.a;
        a = e().next(y).value;
    }
    while(isA(a));

    // And with casting, this works too.
    return {
        a: A.a,
        b: 1234
    } as D;
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var A;
(function (A) {
    A[A["a"] = 0] = "a";
    A[A["b"] = 1] = "b";
})(A || (A = {}));
function* f() {
    let a = A.b;
    const x = yield a; // x is deducted to D
    do {
        // 'y' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
        const y = yield a; // Error: Cannot deduct type of y, while TSC knows that a is always of type A here.
        const z = yield A.a; // z is deducted to D - it works if we use a literal.
        a = e().next(y).value;
    } while (isA(a));
    // Type '{ a: A; b: number; }' is not assignable to type 'D'.
    //  Type '{ a: A; b: number; }' is not assignable to type 'B'.
    //    Types of property 'a' are incompatible.
    //      Type 'A' is not assignable to type 'A.a'.(2322)
    return {
        a: A.a,
        b: 1234
    };
}
function* g() {
    let a = A.b;
    const x = yield a;
    do {
        const y = yield a; // This works, and only works if we type it properly as D.
        const z = yield A.a;
        a = e().next(y).value;
    } while (isA(a));
    // And with casting, this works too.
    return {
        a: A.a,
        b: 1234
    };
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200627&ssl=1&ssc=1&pln=65&pc=2#code/KYOwrgtgBAggUAbzlFUCGAaZqBGcC+ccAliAC7ABOAZmgMbBQBCi2KaAXLAHRoDcbKDi7gIOKgMIlyVWgygBhVqnRcY3HAJV0uAZzKVSAc0lEyATwAOjACJQAvFAAUTKAB9FASgFwAJsDoAGzRKRmowEDoyYgB7EChiXRgAHgAVAD5nAA8uVPdYTy4shN1YH38gkLCIqNj44CdCqABxUCo0MhjKZJgMKBs+pxh8m090n3DI6LiAKihqRq5WkHbO7t7+vpt05VRA4DJVZ2GPUYceTUE6OP0oYsdzYmBA33Q+KAB6D7uSqH9fMBRYCvTr9QS+GKCJAqFRfKAAcnM8ISEEsgWIdGIZEC5igAAs0KULNYEWgQEihAE0GBdIwsX8YsBSiAYocCQA3RhoKDErkgFlkDp1dAgV6JKChahUUAMV6+YihKI4qBdBKihUBbG40gJMilGIAd3ipCxxDQ6IAXlRuE4AOwABgATI7PIJtDdDriHk8Xm9Pt8AKKUShdLgKMkCv7AwGHXkq6hQcx9A144j7KCpADKCigAGsWQaiQTDtzxeaDWhzPqE3Hhnjpdw3ahriBbhbzo9nq91Px-VB2+L-jHgTyYv0oABaXVQA1dXOlYgJg2MGlcqDoiiUc2NmGobmOBqebgrLJkJzmI-s81gYBaVCEFQptMNRIwJxoTzeIiw76pKyMeEECOGB3mEKBRHESh3nwZFxUjQldGIIwQDQHB01BON4RseEd1QOEM3-BEgM4MohBESBIOg2DmVZdBdEQ5DUPQsdMKYHDBHwlA-2sasoEsENrEoCxSWRKo1WuVEhTQ4BcJQTjUG4gCYGo8DaIQpCUOk0ceUI+EexwpxHQAZmdV0VFCMgwEoeJoV3YDeCwOyyKgABGYyABZBHwUw4EmWpZigIxFhaNotzWHoti2HZbJQfYSy4IYRk8c51Eud1W0Oe5Ex9V5+HBSEVBimEW1ucwuDsb0uz9OFUlTUpZ0oec+jJV44mVBr5wSJdGDjel+JiQTlUJfpZOKj1+w7HKeDypz9ygQ9j2AU9z0va9by8wQn32JxX3fT8fB-WBRRnLE8SgOhCWiEAjD6Mg6pnOciRiGJRosqybKbdg1Acz7nLcozPJUfA6P6SQgA)

**Comment by RyanCavanaugh** [comment]
Given how generators get inferred, this looks to be about the best we can do. The circularity is a true circularity IMO, and the return expression can be quickly with an `A.a as const` - attempting to fix that with the contextual type would just introduce another circularity.
