### ISSUE TITLE
Object spreading of primitive values is denied although it's valid JavaScript code

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#39292]
**TypeScript Version:**  3.7.x-dev.20200625

**Search Terms:**

**Code**

```ts
({ ...'' });
```

**Expected behavior:**
pass
**Actual behavior:**
Spread types may only be created from object types.(2698)
**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior since intentionally spreading a string is extremely rare
