### ISSUE TITLE
'infer' in mapped type may lose specificity 

### ISSUE THREAD

**Issue by aloifolia** [microsoft/TypeScript#39295]
**TypeScript Version:**  3.8.3 - 3.9.5 (probably more)

**Code**

```ts
// suppose that IRL this type does something more useful 
type MakeOptional<TObject extends object> = {
  // the "extends infer TValue" is crucial - without it, everything works as expected
  [TKey in keyof TObject]?: TObject[TKey] extends infer TValue
    ? TValue
    : never;
};

type BaseType = { a: number; b: { c: string } };
type ConcreteType = { a: 42; b: { c: 'stuff' }; };

declare const value: ConcreteType;

declare function doNothing<
  // Here, ConcreteType would entail the same result
  TValue extends BaseType, 
  TMappedValue extends MakeOptional<TValue>
>(
  value: TValue,
  mappedValue: TMappedValue,
): {
  value: TValue;
  mappedValue: TMappedValue;
};

const result = doNothing(value, {
  a: 42,
});
```

**Expected behavior:**
The inferred type of result should be 

```ts
{
    value: ConcreteType;
    mappedValue: {
        a: number
    };
}
```

**Actual behavior:**
The inferred type of result is 

```ts
{
    value: ConcreteType;
    mappedValue: MakeOptional<ConcreteType>;
}
```

There is a workaround: If you pass the argument for the parameter `mappedValue` with `as const`, the compiler will instead infer the concrete type. However, if you do this you lose code completion for the fields of `mappedValue`. So basically, you are left with what I would consider another bug/shortcoming of the compiler.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=15&ssc=18&pln=15&pc=26#code/C4TwDgpgBAsghgawgeTMAlgewHZwDYA8AKsgEYBWEAxsFBAB7ATYAmAzlJhdcAHxQBeKAG8AUFCgBtIgGkIIKOmxQkITADMoJbjQC6AfgBcWspRrS5IXXUbN2i7OogAnLQDV8AVwjiJUfe5ePn5QxtgQAG4uANyiAL6xoqCQUADCOFTOEExE4NBCYhJwxgAsAEyxEqTGwlBUxgDkbMCe6uoNUAnxiSzUeHBZdTjNUBFBxunYmdkQuZA9fQPQ6p5TGDhQLJgAcpjAABZKAOYEvkQeeN42TKwck9M5eQA0Z-BgkCwXVww39vBIqHWuEI5yCvFEvAAFL4xpcIMZQXCXhIALZwd4QT7jLRvD5fCAvACUNRh2MR3kqUDRGKxcIRuMx+NiXVEVGGtCybE8eFoQi2uwOx0hsO8TxEvmKUHKLzihOiQA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
I don't understand the argument for why this is a defect. There are two type arguments with a relationship implied by the constraint, and TS satisfied those constraints. In general this sort of cross-parameter inference is the preferred behavior and we've done work to make it work more like people expect.

If you can justify why you would write `T extends infer U ? U : never` (which seems to be a no-op?) and some kind of implementation bug that would justify this, I can look again, but this is a correct inference as far as TS's rules are concerned.

**Comment by aloifolia** [comment]
I probably need to clarify what exactly looks broken to me. So, there are two cases:

1. The code as you see it in the playground. 
If you inspect the inferred type of `result` (by hovering over the variable name), you see this:
<img width="386" alt="Screenshot 2020-07-01 at 14 26 04" src="https://user-images.githubusercontent.com/1295054/86243677-14231f00-bba7-11ea-8de0-2ab8a4363c2d.png">

2. If you change line 3 from `? TValue` to `? TObject[TKey]`, you see this:
<img width="252" alt="Screenshot 2020-07-01 at 14 30 20" src="https://user-images.githubusercontent.com/1295054/86243914-71b76b80-bba7-11ea-9ce9-f5d6eaf4c4c2.png">

So the field `mappedValue` in `result` has a different type, based on whether you used the inferred type or not, although this is basically a no-op (as you affirmed) and should be the same. 

In this basic example this no problem, but I have some code where line 3 is a more complex structure which uses multiple nested `infer` expressions to keep the code legible.

**Comment by aloifolia** [comment]
In [this playground](https://www.typescriptlang.org/play/index.html?ssl=34&ssc=1&pln=34&pc=38#code/C4TwDgpgBAsghgawgeTMAlgewHZwDYA8AKsgEYBWEAxsFBAB7ATYAmAzlJhdcAHxQBeKAG8AUFCgBtIgGkIIKOmxQkITADMoJbjQC6AfgBcWspRrS5IXXUbN2i7OogAnLQDV8AVwjiJUfe5ePn5QxtgQAG4uANyiAL6xoqCQUABCcGwQRODQQmIScGGeALakMb6kxsJQVMYA5GzAnurqdVAJ8YnJ0ADCOFTOEEzZKXm+hVAALABMsRKVIjX1jc2t7bEdoizUeHCDNTiNUBFBxn3YA0NZOYnbVLv76p4XGDhQLJgAcpjAABZKAHMCL4iB48N4bExWBx0pkRhAADQg+BgSAsMEQhhQ+zwJCoV64QigoK8US8AAUvhO4IgxmJNKREmKcFREHRpy0KLRGMRogAlFUqRz6d45lBmaz2TS6Vy2TyNokqIdaIM2J48LQhB9vn9AeTqd4ESJxsYZki4nzEqr1cAAHQS7lBW1wW3ATAAUXoYBwzAw+HJlqAA) you see that the field `result.mappedValue.a` is inferred as being optional although I would expect it to be non-optional.

**Comment by RyanCavanaugh** [comment]
> In this playground you see that the field result.mappedValue.a is inferred as being optional although I would expect it to be non-optional.

I strongly disagree based on this example:
```ts
// Error-free implementation of 'doNothing'
function doNothing<TValue extends BaseType, TMappedValue extends MakeOptional<TValue>>(value: TValue,  mappedValue: TMappedValue): {
  value: TValue;
  mappedValue: TMappedValue;
} {
  return { value, mappedValue };
}

// Legal call to 'doNothing'
const result = doNothing<ConcreteType, Partial<ConcreteType>>(value, {});
// Crashes
result.mappedValue.a.toFixed();
```

**Comment by aloifolia** [comment]
I think that I still have not quite pointed out which aspect is wrong (in my opinion). So, based on your example, I extended the Playground example. 

## 1. [Playground](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAsghgawgeTMAlgewHZwDYA8AKsgEYBWEAxsFBAB7ATYAmAzlJhdcAHxQBeKAG8AUFCgBtIgGkIIKOmxQkITADMoJbjQC6AfgBcWspRrS5IXXUbN2i7OogAnLQDV8AVwjiJUfSY6wBbyur4SxtgQAG4uANyiAL4JoqCQUABCcGwQRODQQmIScJGeALak8b6kxsJQVMYA5GzAnurqjVDJSSlp0ADCOFTOEEx56YW+JVAALABMCRI1IvVNLW0dXQndoizUeHAj9TgtUNFeEMaD2MOjufkpe1QHR+qeNxg4UCyYAHKYwAAFkoAOYEXxEDx4bw2JisDhZHLjCAAGgh8DAkBYUJhDDh9ngSFQn1whEhF14ol4AApfOdoZd3Bc0RIynBMRBsRdjEQMVicajRABKWp07lMhmLKBsjlchk8vmcgXbFJUE60ZwARkE3z+AOB2BB1Pp3hRK2m8y6QtEWoAdDL+RdbXBbcBMABRehgHDMDD4alC1XqqDOOY6n7-IGggjXW5jfJmgAKhz9hFjI3jkF4NJNqJEiUDNrm9vZjoZztdHq9PuwqYDcSAA) with code that works as expected
Here, the type `MakeOptional` just returns `TObject[TKey]`. This leaves us with the following result:
<img width="507" alt="Screenshot 2020-07-01 at 18 27 00" src="https://user-images.githubusercontent.com/1295054/86268433-7a6c6980-bbc8-11ea-81fc-98033e623ad4.png">
✅ This is good, because the compiler infers that `r1.mappedValue.a` is non optional whereas `r2.mappedValue.a` is optional. So both of our example calls work as desired.

## 2. [Playground](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAsghgawgeTMAlgewHZwDYA8AKsgEYBWEAxsFBAB7ATYAmAzlJhdcAHxQBeKAG8AUFCgBtIgGkIIKOmxQkITADMoJbjQC6AfgBcWspRrS5IXXUbN2i7OogAnLQDV8AVwjiJUfe5ePn5QxtgQAG4uANyiAL6xoqCQUABCcGwQRODQQmIScGGeALakMb6kxsJQVMYA5GzAnurqdVAJ8YnJ0ADCOFTOEEzZKXm+hVAALABMsRKVIjX1jc2t7bEdoizUeHCDNTiNUBFBxn3YA0NZOYnbVLv76p4XGDhQLJgAcpjAABZKAHMCL4iB48N4bExWBx0pkRhAADQg+BgSAsMEQhhQ+zwJCoV64QigoK8US8AAUvhO4IgxmJNKREmKcFREHRpy0KLRGMRogAlFUqRz6d45lBmaz2TS6Vy2TyNokqIdaM4AIyCd5fH7-bAA8nU7wIxYTGbtPmiNUAOgl3KClrgluAmAAovQwDhmBh8OS+YrlVBnNMNR9vn9AQRzpdhjkjQAFPZewiRwbRyC8CkGxEiOK+i3Ta0s200+2Ol1uj3YRM+6JAA) with code that works in unexpected ways
Here, the type `MakeOptional` just returns `TObject[TKey]`. This leaves us with the following result:
<img width="507" alt="Screenshot 2020-07-01 at 18 30 22" src="https://user-images.githubusercontent.com/1295054/86268764-f36bc100-bbc8-11ea-8b13-85f3d6bb832d.png">
❌ This is bad because now both `r1.mappedValue.a` and `r2.mappedValue.a` are inferred as optional fields. `r1` is unnecessarily imprecise.

The puzzling thing here is that the difference in the inference of the function argument arises from something seemingly unrelated (by returning an `infer`ed "copy" of a type vs. just returning the same type in `MakeOptional`). Also, if you use one of the other "workarounds" that I mentioned in the first post, the compiler will infer the more precise type.

**Comment by RyanCavanaugh** [comment]
It looks like what's going on there is that the `T extends infer U ? U : never` is creating a lower-priority inference site, which is a normal part of inference.

**Comment by aloifolia** [comment]
So, I investigated a bit more to get a feeling for which cases break and which work. In [this playground](https://www.typescriptlang.org/play/index.html?ssl=76&ssc=7&pln=76&pc=9#code/C4TwDgpgBAsghgawgeTMAlgewHZwDYA8AKsgEYBWEAxsFBAB7ATYAmAzlJhdcAHxQBeKAG8AUFCgBtIgGkIIKOmxQkITADMoJbjQC6AfgBcWspRrS5IXXUbN2i7OogAnLQDV8AVwjiJUfe5ePn5QxtgQAG4uANyiAL6xoqCQUABCcGwQRODQQmIScGGeALakMb6kxsJQVMZswM5KAOZQCfGJydAAwjhUzhBM2Sl5voVQACwATLESlSI1xgDk9Z7q6outsW2iLNR4cP01OPVQu1T7-SweeN7GPdh9A1k5iVTHtEroGPjoAF4QVyCghEo2MUwANBUqgsoMtgKt1q1IdszhdoOpPA8MDhTpgAHKYYAAC2aAHUvkT0pkhhACL4iNdvDYmKwOFTnpBIRIiPAwJBATdoAwWfZ4EhUNjcIQGUFeKJeAAKXwRILGGWCrlQYpwPkAxkQNW8-n6yEASiqytVgUFMy1OuNVp59r1QS2iVRB3RmJoWGULHxhJJ2Ca5OJ90egxydO5+uZdg44f6kc59KNLsFcdZsEQKDQvvwxH1csVlsFapNvm1uoFty0aZrEDNFokKrL1u8tqrDrbTur+rdolEAHoh1BAKDkUDwXxc+CgAHcKZhPLROqc9gc4JKoKI3tgTs4AIzA-0E4lkinsmkK-JQMYQqHzWqwlZrDZxZHg+Z3yatU2iQ8AHRdum3gAXAAHAJgACi9BgDgzDfHgCqmokI5QIAMuSTtOzizguxJQKuVAZCumBQKQGTQJ0O7vFAzg-kIJ6BuexKXjk16ghMkyanM1RPnCCJvsit5shRNKftU36-v+kxAc6DZgRB0GwfB2CIchqGjphU5MDheDzhSBE5DUxEEaRu4RpROTUXutDOAAzMeAZnsGoaUqJbE3t+3HQnxL6Iu+8TCVAiZPGJX5gj+cR-vZsl9kECmQTBcHhKp6D4Opg5oZh6C7Kl6joC4nCaCqjRwKQeDQHhRKGSkHo4ZK1n7uMjmnkGIYXu5kAKnVIGNuFnFSc44yxd2oHgYlykpWpKGZaOE45Qh6D5YVGhQCVaXlZVBmfIhfybr6jW2QArC1TEuR11JsTtaVTv8DbibeEWDUdI29QlSnJYt6UzcOc2KLlGDLa4q3rWVFX6fhq51ftOJgDcHC7icGSZM4W7qJgriZLuLC3s4TQlAhEiHbRABsp3Oe1LGdRA3XrpcJr9VMrRBYjwDRSTr3yeNH0qdNGkYVhOm4Yuy41dA0NbgAtGRotVVAABE5lJpZkDy1AGJYgdrO0QA7OTbWuSFyY055EXeY+Sx+YJ8QPZJUX-jrnP6u9SW8zdGW-QL2kznpcuESZ0twKwEPVYrvTK2Lasaz6ODE84AAc+vMUSRscibHH3rMPmW-Cr5IoFGTBeHoU5LbT32wnTvxdzrtTe7M1AA) you can see the results. And here are my findings (I will reference the playground code):

1. If you provide both arguments as object literals, the compiler might infer the more specific variant:
- if the first parameter is typed as an extension of a certain base type, this works → see `r1` 
- if the first parameter is typed as an extension of a type which is exactly the same type as the provided argument, this does not work → see `r7`
2. If you use a type cast for the first parameter, the compiler might infer the more specific variant:
- if you use a cast to the base type (and the function parameter is typed accordingly), this works `r2`
- if you use a cast to the concrete type, this does not work → see `r3` and `r8`
- note that in the playground, the typecast examples use literal objects for the first parameter - these can be swapped to variable identifiers without a change of the result
3. If you provide the first argument as a variable identifier, the compiler might the more specific variant:
- if the variable was initialized with a value, this works → see `r5` (here, the fields do not have literal types but more general ones, but this is to be expected - this is documented somewhere)
- if the variable was assigned a designated type, this does not work initializedValue → see `r4`
4. If you provide the second argument with a constant assertion, every one of the examples work → see `r6` (this approach can be used for any of the other cases)

After letting all these examples sink in, I come to the following conclusion:
- the current behaviour might follow a certain consistent logic
- for me as a Typescript *user*, however, this logic is entirely inscrutable

So, with the current state of the compiler, if I want to add a function like `doNothing` to an API, I have the following choices:
- let user figure out which kind of arguments could possibly infer specific types - basically by trial and error (because they will certainly not understand what's going on
- tell the user to always use constant assertions if the type inference "breaks" - which means that they may need to struggle with [this bug](https://github.com/microsoft/TypeScript/issues/39384)
- let go of uses of the `infer` keyword in types like `MakeOptional`- thus, missing the convenience of a generally very useful Typescript feature

The first option is a no-go, the second one would be acceptable as soon as the linked bug is solved, the third one might work, but might also severly limit the structure and expressiveness of types that I can use. The best option (in my eyes) would be to somehow improve the inference to have consistently specific resulting types.

**Comment by RyanCavanaugh** [comment]
What you're proposing is basically "TypeScript should *just do the right thing* during generic inference"

The inference rules started out pretty simple. I could write them down on a small index card.

Then people showed up and said "Hey, inference isn't doing a good thing here, when X > Y and Y > Z then Z < X so therefore you should pick X or Z depending", and we agreed, and made the inference rules a little more complex to make inference do the right thing in that situation.

Then more people showed up and said "Hey, inference isn't doing the right thing here, when there are two inference candidates, this one is clearly superior and should be chosen", and we agreed, and made the inference rules a little more complex to make inference do the right thing in that situation.

Then more people showed up and said "Hey, inference isn't doing the intuitive thing here, when there are two inference candidates and one is from a contravariant inference, then you pick the other candidate instead", and we agreed, and made the inference rules a little more complex to make inference do the right thing in that situation.

This happened dozens more times, based on user feedback, each with the goal of TS just doing the right and intuitive thing.

**Comment by aloifolia** [comment]
I get your point - the inference mechanism could probably be made arbitrary complicated and eventually unmaintainable. 

So, for me, one of the core aspects of any language is predictability. For any language this means that you should generally be able to see a certain piece of code and tell what it might do. Of course, the more complex the code is or the more side effects it involves the less likely this assumption will materialize. 

Now, for a statically typed language with type inference, the surface area includes static types: You should be able to reason which types are inferred at a certain position in your code (is this assumption naive?) since these types are basic building blocks of your program. If that is not the case, the coding process becomes somewhat of a lottery.

I think that two main factors of type predictability are:
1. Consistency: Do equal expressions entail the same types? Note that I use the somewhat fuzzy "equal" instead of "identical". So the question whether this statement should hold true for a specific example is probably a bit subjective.
2. Traceability: Will a user be able to understand the reasoning of a certain inference? This will probably depend on two factors:
(a) the experience of the programmer
(b) the documentation of the programming language

Ideally, every decision that a compiler comes to is completely consistent in the eyes of a slightly experienced programmer. However, this ideal is probably unrealistic for a type system like the one that Typescript establishes. Thus, I suggest that to improve the developer experience nevertheless that the inference rules of Typescript should somehow be documented. This would certainly help library authors avoid constructs which ultimately confuse users. Also, the question of which remaining gaps in the inference should be closed eventually would become more obvious.

**Comment by RyanCavanaugh** [comment]
We can agree that two *identical* programs should have identical behavior, and that guarantee is upheld. TypeScript is deterministic even if it's not predictable to a lay user.

However, one programmer's "consistency" is another programmer's "lack of expressiveness" - at the point that two programs diverge in their text, we *can* (though not necessarily *should*) assume that the divergence is grounded in some intent to write a different program.

An example is that `T extends U ? V : W` is different from `[T] extends [U] ? V : W` due to distributivity rules around bare type parameters. One person could look at that and say "It's inconsistent; TypeScript would be better if it were more consistent and treated these different programs identically". Another person could say "This lets me be expressive by allowing me to control whether my conditional type is distributive or not; it would be worse for TS to remove this feature because it would remove my ability to make this decision myself'.

More documentation is always better but there will always be a point where no reasonable programmer is able to keep all the rules in their head at once and accurately predict the outcomes; the example in the OP is well past what I would expect 99.99% of programmers to be able to reason about. An example with more complexity than a human can manage will always be constructable no matter how well-documented and intuitive the rules are.

**Comment by aloifolia** [comment]
Exactly, that is what I meant with "consistency is subjective" - which is why I was wondering whether "documentation of inference rules" could help in my example. You might be right that the OP example is already beyond manual human reasonableness - to validate this statement, I would actually need to know the rules ;-).

Spontaneous idea: a tool which, given some code, incrementally shows which inference rules are used and which intermediate types are produced by them. Since I have no clue, how the inference mechanism in the compiler is implemented, I don't know if that is even feasible.

**Comment by Twonster** [comment]
I don't know, may be it cal help)

`
declare type InferKeyByValue<I extends Record<string, any>, T> = {
  [Key in keyof I]: I[Key] extends T ? Key : never;
}[keyof I];
`

example

`
export type KeyMapForPreview<I extends InitialPassedFileForPreview> = {
  text?: InferKeyByValue<I, string>;
  type: InferKeyByValue<I, InAppFileType>;
  url: InferKeyByValue<I, string>;
};
`

usage

`
  const handleMediaPreview = useCallback<OnMediaPreviewClick>((file) => {
    const { type, name, url } = file;

    if (!type || !name || !url) {
      return;
    }

    const picked = {
      type,
      name,
      url
    };

    showPreview(prepareAttachmentsToPreview([picked], { type: 'type', url: 'url', text: 'name' }));
  }, []);
`
