### ISSUE TITLE
Switch case fallthrough

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#393]
There are numerous places where the code just fallsthrough a different case like here:
https://github.com/Microsoft/TypeScript/blob/02d0b024c695f059fb8209e301b30f80fddc3d08/src/compiler/checker.ts#L646 or here https://github.com/Microsoft/TypeScript/blob/02d0b024c695f059fb8209e301b30f80fddc3d08/src/compiler/emitter.ts#L118
There are also multiple places in the binder or parser where this is the case.
In my opinion it might be nice to write a comment there when it is intentional... or isn't it intentional?

Example for comment how for example jshint knows it is intentional:
```javascript
switch(1) { 
    case 1: console.log("foo");
    /* falls through */
    case 2: console.log("bar");
}
```
In the above code both are written to the console.

**Comment by DanielRosenwasser** [comment]
I think we can close this now.

**Comment by DickvdBrink** [comment]
Yeah, think so :)
