### ISSUE TITLE
Incorrect code hint for mapped (in keyof) property types

### ISSUE THREAD

**Issue by simon-robertson** [microsoft/TypeScript#39300]
**TypeScript Version:**  3.9.2

**Search Terms:** incorrect code hint for mapped keyof property types

**Code**

```ts
type Numbers = {
    [key: string]: number
}

type Strings<T extends Numbers> = {
    [K in keyof T]: string
}

function test<T extends Numbers>(input: T): Strings<T> {
    const output = {} as any

    for (const key of Object.keys(input)) {
        output[key] = input[key].toString()
    }

    return output
}

// hover over `mapped` to see the property type is `number` (incorrect)
const mapped = test({ value: 100 })
// hover over `value` to see the property type is `string` (correct)
mapped.value
```
**Expected behavior:**

Code hint should show property types as `string`

**Actual behavior:**

Code hint shows property types as `number`

However, hovering over a property shows its type as `string`

**Playground Link:** 
[This example code highlights the issue](https://www.typescriptlang.org/play?esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=99&jsx=0#code/C4TwDgpgBAcgrgWwEYQE4GcoF4oG8CwAUFCVANoDWEIAXFOsKgJYB2A5gLp0uIqpEBfIkVCQoAZUas26ADwAVKBAAewCCwAmmeMjToAfNjxFS5ANJRWUKiAD2AMyjyu9Ke0HDC9uCwDGwJlsWKDUGBSVVdS1YXj19AApWMDhgOnkASjpJZnY5eUMCYlJfIIYoWxTk4CNcASgAQ0x6lhBPU3tbVCh4kpYym3LHAHkkACsIfwA6G3RElir09OMi0xIK4CrKag4jJJStkA5J4Fts6Xj0k1IhQiuSVAhgOFRg9aqPW8IAei+oAAtbAA3NDlYFdAAGCHqYEgGnBIVs9Ag0GAf2gYFQtkgqFAIXA0CYmHBPF0qHhcxKqAe-kuhF6ZShMIgGiMoWA8VwUEB9QANnAIHQAIwABmFUAEtJ+-yBIJlEO5fIg8JOSJRaKgGKxaFxogJRIYOTY5Mp1OAtMZsMmCv5QA)

**Comment by vasilii-kovalev** [comment]
It seems that
```ts
{
  value: number;
}
```
in
```ts
const mapped: Strings<{
    value: number;
}>
```
defines the input's `T` type, not the __return type__ of the function.

**Comment by RyanCavanaugh** [comment]
The tooltip says, reading it in its entirety, `Strings<{ value: number }>`, which is exactly what this type is.

**Comment by simon-robertson** [comment]
> The tooltip says, reading it in its entirety, `Strings<{ value: number }>`, which is exactly what this type is.

@RyanCavanaugh, could you please explain how that is the case when the `test` function is returning a `[key: string]: string` type? I assume there is a misunderstanding on my part regarding the way `[K in keyof T]` works when mapping objects this way

**Comment by dragomirtitian** [comment]
@simon-robertson  The type you are seeing `Strings<{ value: number }>` resolves to `{ value: string; }` but TS does not always expand out type aliases in tooltips. So there is no conflict between what you are seeing. 

If you want to always expand out a type alias add `{} &` to the mapped type to force expansion (not the `{} &` is not documented and should not be relied upon, it's just a useful debugging trick)
```
type Numbers = {
    [key: string]: number
}

type Strings<T extends Numbers> = {} & {
    [K in keyof T]: string
}

function test<T extends Numbers>(input: T): Strings<T> {
    const output = {} as any

    for (const key of Object.keys(input)) {
        output[key] = input[key].toString()
    }

    return output
}

// Now you see { value: string; }
const mapped = test({ value: 100 }) 
mapped.value // string
```

[Playground Link](https://www.typescriptlang.org/play/?esModuleInterop=false&declaration=false&target=99&ssl=21&ssc=23&pln=1&pc=1#code/C4TwDgpgBAcgrgWwEYQE4GcoF4oG8CwAUFCVANoDWEIAXFOsKgJYB2A5gLp0uIqpEBfIkVCQoAZUas26ADwAVKBAAewCCwAmmeMjToAfNjwCoAMjxFS5ANJRWUKiAD2AMyjyu9Ke0HDCLuBYAY2AmJxYoNQYFJVV1LVhePX0AClYwOGA6eQBKOklmdjl5QwJiUiDwhignTIzgI1wTAENMZpYQPysXJ1QoFMqWascatwB5JAArCBCAOkd0NJZ6nJyLcqsSWuB6ymoOI3TMvZAOWeAnAukUnMtSIUI7klQIYDhUCO3630fCAHo-rAnAB3KDOOD0CDQXBQABuzQANnAIHQGIU2ABuKAPQbVBDNMCQDRGKLAFIw+FIlFQACMAAY6di1kR8YSIBpZpTkVAAV50UA)

**Comment by simon-robertson** [comment]
Thank you for the explanation @dragomirtitian, using `{} &` does indeed work even though its use in this case is counter-intuitive

**Comment by athyuttamre** [comment]
This is an amazing trick, but would be even better if the "flatten the tooltips" behavior was configurable. Maybe some option in tsconfig? Or perhaps a UI enhancement to Monaco / VS Code where you can click on the type in the tooltip and have it expand automatically?
