### ISSUE TITLE
Enrich TypeScript Utility Types

### ISSUE THREAD

**Issue by SalathielGenese** [microsoft/TypeScript#39305]
## Search Terms

Distributive keyof, ValueOf, PickWhen, OmitWhen

Partial results...

- https://github.com/microsoft/TypeScript/issues/37642
- https://github.com/microsoft/TypeScript/issues/31438

## Suggestion

I'd like to see TypeScript default typeset richer so that some common takes comes handy and universal.

#### `KeyOf<U, C?, K?>`

> Get the keys of each member of the union `U`, mapped to a value whose type extends `C` and which keys intersects with `K`.
> - `C` defaults to `any`
> - `K` defaults to the combined keys of each element of `U`

In #31438, I stressed the need to collect keys or union type. Today, I have it evolve by supporting conditions on the value they map to. I can collect all the keys of an entity that maps to another entity and array of entities.

```typescript
type KeyOf<U, C = any, K extends (U extends any ? keyof U : never) = (U extends any ? keyof U : never)> =
  C extends any ? U extends any ? K extends any ? U[K] extends C ? K : never : never : never : never;
```
e.g:
```typescript
type testKeyOf = KeyOf<{ a: 'Aa' } | { b: 'Bb' } | { ó: 'Aa' }, 'Aa'>; //  "a" | "ó"
```

#### `ValueOf<U, K?>`

> A distributive version of `Pick`.

Also in #31438 also, I suggested this type along the `KeyOf`. Again, I augmented it today with the ability to narrow down which keys to pick, if applicable to the union member.
```typescript
type ValueOf<U, K extends KeyOf<U> = KeyOf<U>> = U extends any ? K extends keyof U ? U[K] : never : never;
```
e.g:
```typescript
type testValueOf = ValueOf<{ a: 'Aa' } | { a: 0, b: 'Bb' }, 'a'>; // "Aa" | 0
```

#### `PickWhen<U, C?, K?>`

> For each member of the union `U`, `Pick` the key-values when the value matches the constraint `C` and eventually restrict the keys that intersect with `K`.
> - `C` defaults to `any`
> - `K` defaults to the combined keys of each element of `U`
> - Union member that would transform into empty objects are commuted into `never`

`Pick` does quite a great job by containing on the keys, `PickWhen` proposes to constrain on the value type, while still allowing to narrow down the keys to picking from, and keeping the union structure.
```typescript
type PickWhen<U, C = any, K extends KeyOf<U> = KeyOf<U>> =
  U extends any ? K & KeyOf<U, C> extends never ? never : { [k in K & KeyOf<U, C>]: U[k] } : never;
```
e.g:
```typescript
type testPickWhen = PickWhen<{ a: 'Aa' } | { a: 0, b: 'Bb' }, 'Aa' | 'Bb'>; // { a: 'Aa' } | { b: 'Bb' }
```

> **NOTES:** Rephrase the description of `Extract` which would be confusing with `PickWhen` behaviour:
>
> **Currently:** Constructs a type by extracting from `T` all properties that are assignable to `U`.
>
> **Proposed Change:** Constructs a type by extracting from `T` all types that are assignable to `U`.

#### `OmitWhen<U, C?, K?>`

> For each member of the union `U`, `Omit` the key-values when the value matches the constraint `C` and eventually restrict the keys that intersect with `K`.
> - `C` defaults to `any`
> - `K` defaults to the combined keys of each element of `U`
> - Union member that would transform into empty objects are commuted into `never`

`OmitWhen` it to `Omit` what `PickWhen` is to `Pick`
```typescript
type OmitWhen<U, C = any, K extends KeyOf<U> = KeyOf<U>> =
  U extends any ? Exclude<K & keyof U, KeyOf<U, C>> extends never ? never : { [k in Exclude<K & keyof U, KeyOf<U, C>>]: U[k] } : never;
```
e.g:
```typescript
type testOmitWhen = OmitWhen<{ a: 'Aa' } | { a: 0, b: 'Bb' }, 0 | 'Bb'>; // => { a: 'Aa' } | { b: 'Bb' }
```

## Use Cases

Provided along with each proposed type.

## Examples

I have put it all together [here, on TypeScript Playground](https://www.typescriptlang.org/play/index.html?ssl=79&ssc=43&pln=38&pc=1#code/C4TwDgpgBA0hIHkBmAeAqgGigYSgXigEMA7ELGKCAD2AmIBMBnKACjUprqaNKgH4oAa3gB7JFHYAuKMQgA3CACcAlPlbtqtBsxIh+Q0eKkz5S5QD58AKCg4OW7rv0bO2nnoEVNXHbwFoAbRgAXXsfO08oaVkFRSiTWPiYpSTTRQBuKytQSCgANUIAGwBXCGR0cjC3OERUNEsCGvL6hokqxz9YduZhEDE2-yDQ6LTU2Mzs8GgABQBLAGNBAHUACzoKuwJdSu9q+GbWprrzBps23Y6PLoAyWH26rGxLC+ZkuIE3+IBvKADBKFmxBud1qGyewWkgUEoQAvmMlBMctAEABbWbAVbrTCbdw7VzcI7oQ73ImnWwuBy+K4AUSo8xK9AgKAot16-WxhOxT2e+Neow+o2kPz+AKBtPpxUZzKgrMMEnIJK5JwhEj+sPhGSyWQA9NqoLr9XqDbqrAakVAALJKADmTI53RBBzUnJOamF-0BsBVBRKZQeQksMImWWoYBEimAotoiiQhHm0AtIkZhRQAEkACJqYjFFEAIxSAB8oIxgIpAdbzFYvmdZvRpBmJrZ5ooIIRaPQAILAPjSdNtiCNqDFMD0fud7u9-uZGEhqhhiNQc2J5MAMUB9BQFody4ghVa00IEdmRRQqPRmOIm6wO8KUCLN4CwROE1D4cjS6Tu+wLf7m+3n73NQzwxNZLwta8ALvS0AMfLBxQZJlCQtcwsAAclrVCoNQ5tW3bLtMKLVDh1HPDgFQ59Z3nd8pmg5M0BHX8txeWjd1aatbBFT14MlJk2XEcCoGwn9SIIwTiLHfDzGCHtLTVf9k30G96JIpkLTVStbGkNToXk3dH0UgDlMYtUAmzPMlCffStLVadg0BaNY3jHBCkIRhmGYm8UDM-NFErdioEKUxCmkEsy2Ia1B0YeYVhEERgqgABlaLYsKSLgB44hgEYaQEvSxlMsfSLkri1M60S4rCgCdD6FQ4JpyyeylEc6AkpiuLdJTbylD8mtGGmYpc0KBZpFzFLW2IQd6VcxgIGy5zpsKrJbGIQgUQgELS3LeqrEamM4xavK6EjDyAK8nMfJ62wkFmRQSwAOVW9bi028LBxc+7Ho2sKIqWqAprc0rpGwd7GCqjC6t+-65uB6btvNGG3LXBg1BvJGNwRxhzEyc1WpStGUYAtGUFxuKscmXJcoy4B8YIVH12Jw7MrJ8noAx79cOgWmAPZ38MbJnGKp52gCeTIWmRJvdsZoyn8uAMWRa-YTxcZ4BmfhkGjOFrm6IY2gUD5qWKYqzXOZYwoTeJir+ellWTYV83deVqmyaAA).
```typescript
export interface Model<ID = number | string>
{
  id: ID;

  createdAt?: Date;

  updatedAt?: Date;
}

export type ModelFind<M extends Model> = Partial<OmitWhen<M, Model | Model[]>>;

export type ModelCreate<M extends Model> = OmitWhen<M, Model | Model[], Exclude<KeyOf<M>, 'id' | 'createdAt' | 'updatedAt'>>;

export type ModelUpdate<M extends Model> = {
  [k in Exclude<keyof M, 'createdAt' | 'updatedAt'>]?: M[k] extends Model ? ModelUpdate<M[k]>
  : M[k] extends Model[] ? ModelUpdate<M[k][number]>[] : M[k];
};
```

```typescript
interface Class extends Model<number>
{
  level: string;

  school: School;

  students: Student[];

  schoolId: School['id'];
}

interface School extends Model<number>
{
  isPublic: boolean;

  classes: Class[];

  name: string;
}

interface Student extends Model<number>
{
  firstName: string;

  lastName: string;

  classId: Class['id'];

  class: Class;
}

// Check out the types below

type ClassFind = ModelFind<Class>;
type SchoolFind = ModelFind<School>;
type StudentFind = ModelFind<Student>;

type ClassCreate = ModelCreate<Class>;
type SchoolCreate = ModelCreate<School>;
type StudentCreate = ModelCreate<Student>;

type ClassUpdate = ModelUpdate<Class>;
type SchoolUpdate = ModelUpdate<School>;
type StudentUpdate = ModelUpdate<Student>;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behaviour of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We have decided to not add any additional utility types unless they are needed for declaration emit. Every time we add a new utility type, there are ~four different forms to choose from, people split roughly equally on which is "best", and then 75% of people get mad that we added the "wrong" one and blocked them from adding the "right" one to their project's global scope - given that situation, we think it's better for people to just add whichever utility types they need to their own project.

**Comment by SalathielGenese** [comment]
Thank you @RyanCavanaugh . It is legit.

**Comment by SalathielGenese** [comment]
Please, any TS utility types out there to recommend suggesting this at ?

**Comment by KilianKilmister** [comment]
@SalathielGenese  [type-fest](https://github.com/sindresorhus/type-fest) has implementations of these
