### ISSUE TITLE
Function generics losing type information (A extends B)

### ISSUE THREAD

**Issue by simon-robertson** [microsoft/TypeScript#39301]
**TypeScript Version:**  3.9.2

**Search Terms:** function generics losing type information

**Code**

```ts
type A = {
    value: string
}

type B = {
    [key: string]: Partial<A>
}

type C<T> = {
    readonly [K in keyof T]: string
}

function test<T extends B>(input: T): C<T> {
    return {} as any
}

const output1 = test({
    hello: {
        value: '', // ok
        world: ''  // this should not be allowed (expected 2322)
    }
})

const output2 = test({
    hello: {
        value: '',  // ok
        world: ''   // this should not be allowed (expected 2322)
    } as Partial<A> // this does nothing to enfoce the value type
})
```

**Expected behavior:**

The `world` property in the above code should not be allowed because it does not exist on type `A`. This only appears to become an issue when using `T extends B` in the function signature

**Actual behavior:**

The `world` property in the above code is allowed

**Note** The use of `T extends B` here is used to map the keys in `input T` to the return type `C<T>`

**Playground Link:** 

[This example highlights the issue](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeBYAUFTUBuBDANgK4QBcUAzsAE4CWAdgOboC+66okUAQgsullADaAawggylWowC6ZAAq4qwGgQA8MAHws2aDtADCqgCobeqDFioRcAEwD2dfCCEBpKPSiiQdgGZQjshTU9ExorGjoPoR0AMbKDlDAEJTGUBAAHkl0NuTcGgAU9GCEwGRGAJRkhiZ8FphWwIRUdMjMULi5uHQg2hFoMQ6UUHYlxcAAjLxJlPnmAgAWEPj4dmRzAlh4RKRQAOS7ADRQAPTHw8L8G5gA7nZU+DZk+5inifM0ueTzIw9QdHbAKAAI2gBBW1wgNig+QykDikKgACYAMyIxHlS6YcLMDF9AZ0IYjYBjRFTZLAWaYqCLZarWpXTBbYhPQ4vM52C51Da3e6PPa7LCvYDvT7fQi-f6AkHtWkQqEw9JwpJQlFo3ECNodKAKJQqfDqUxCkVQezJP4A96MRJ2NJ0Hx2GLQYXQJlO8AQFjlIA)

**Comment by vasilii-kovalev** [comment]
The more tiny example [[playground](https://www.typescriptlang.org/play?ts=3.9.2#code/JYOwLgpgTgZghgYwgAgJIgA4FczIN4CwAUMqcgBYQA2VA9gFz7FkvIBucVWEjAzmFFABzANzMyAXzFEpxYgloh+ySMoC8yADwAVZBAAekEABNeaTDgB8AClDYwjbQEpHyNZeR2c0+YuWqwdHtGIJw3JhIyShoGCNYyDi4eZAByFIAaZAB6LOQAeQBpcXiAd1ooKmNGNMzs3NQzEFpcTjoSiGNkAFp8osjSCXTi5BhgairkABYAJkyctEbm5Fbads6ewuJZIl8lXCgIXiwqMABGcIDrANCwJx8iBT3kA6OT6YvDsGtCfopqOkYP3ipES3GqGTqvWGLDKFQmaVI8wAgjE1t1kE1cJtfoNhqNxowZnNcii2h10ZioTInMQgA)]:
```ts
interface Input {
    hello: {
        value: string;
    };
};

const test = <T extends Input>(input: T): T => input;

const testInput: Input = {
    hello: {
        value: '', // OK
        world: '',  // Is not allowed - OK
    },
    field: 42, // Is not allowed - OK
};

const result1 = test(testInput);

const result2 = test({
    hello: {
        value: '', // OK
        world: ''  // Allowed - not OK
    },
    field: 42, // Allowed - not OK
})
```

As I see, it was discussed here: https://stackoverflow.com/questions/44645560/typescript-strict-class-interface
Link to the issue from one of the answers: https://github.com/Microsoft/TypeScript/issues/12936

**Comment by simon-robertson** [comment]
If you add a required property to the partial type, the expected 2322 error is reported correctly for unknown properties until you add the the required property

```ts
type A = {
    value: string
}

type B = {
    [key: string]: Partial<A> & { id: string }
}

function test<T extends B>(input: T): any {
    return {}
}

const output1 = test({
    hello: {
        id: '',
        value: '',
        world: '' // this should not be allowed (expected 2322 error)
    }
})

const output2 = test({
    hello: {
        value: '',
        world: '' // this correctly reports the expected 2322 error, until the `id` property is added
    }
})
```

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeBYAUFTUBuBDANgK4QBcUAzsAE4CWAdgOboC+66okUAQgsullADaAawggylWowC6ZAAq4qwGgQA8MAHxQAZMig0AJhOr0GUVmgvoAZoToBjZQHs6UYBEqqAKlAgAPdzoDcm4NAAp6MEJgMi8ASjJcOhA+DCwqCGBCKlckCys0exdKKCdoqOAARl53SjDUNMwACwh8fCcyBoEBQzIAcj6AGn5uzDwiUigB4cbugHcnKnwjKb7MAHp1tyaaEPImsuWoOidgKAAjaAJ2uYgDKDD-SEc7qAAmAGY3t98qKkW4iNMPlAWh0EU6CUysAKj9ELVgPUgVAWm0OqlRmMCMR+kNkQIFksVgMsJttrsoEU-hBHPgUhkwItgCFgC1fH5nu57p9vr9-lRBlA7Mp8NtoAADQziqBgf6QJQpCm4AwGO7IkFAA)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; in general inference is always allowed to choose a more specific type for a type parameter given a candidate of that type. You can convince inference to do other things by using intersections and such, but this isn't a bug.

**Comment by simon-robertson** [comment]
> This is the intended behavior; in general inference is always allowed to choose a more specific type for a type parameter given a candidate of that type. You can convince inference to do other things by using intersections and such, but this isn't a bug.

That is understandable @RyanCavanaugh but I have had no luck getting this to work correctly. For example, the following code correctly reports a 2322 error if an unknown `Values` property is added to `input`, unfortunately `output` then obviously loses code hints for the mapped property keys

I have not been able to get this working with intersections either

```typescript
type Values = { a: string, b: string, c: string }
type Input = { [key: string]: Partial<Values> }
type Output<T> = { [K in keyof T]: string }

function test<T extends Input>(input: T): Output<T> {
    return {/* placeholder */} as any
}

const input: Input = {
    hello: { a: "", b: "" }
}

test(input).hello // unknown property
```

It feels like we need a way to tell TSC that `T` does not extend `Input` but is actually an instance of `Input`

```typescript
function test<T is Input>(input: T): Output<T> { ... }
function test<T typeof Input>(input: T): Output<T> { ... }
function test<T instanceof Input>(input: T): Output<T> { ... }
```

Do you have any further thoughts on, or solutions for, this?

**Comment by simon-robertson** [comment]
@RyanCavanaugh, the following code appears to be the solution

```typescript
type Values = {
    a: string
    b: string
}

type Input<P extends keyof any> = {
    [K in P]: Partial<Values>
}

type Output<P extends keyof any> = {
    [K in P]: string
}

function test<P extends keyof any>(input: Input<P>): Output<P> {
    return {} as any
}

const output = test({
    one: {},
    two: {
        a: '',
        z: '' // error
    }
})

output.one
output.two
output.three // error
```

I will close this issue. Thank you for your time
