### ISSUE TITLE
Results are not showing in logs.

### ISSUE THREAD

**Issue by Aman-SS** [microsoft/TypeScript#39304]
**TypeScript Version:**  3.9.2

**Search Terms:**

**Expected behavior:**

**Actual behavior:**

**Related Issues:**

**Code**
```ts
for (var i = 0; i < 10; i++) {
  setTimeout(function() { console.log(i); }, 100 * i);
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
for (var i = 0; i < 10; i++) {
    setTimeout(function () { console.log(i); }, 100 * i);
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/GYewTgBAFAbghpAlhAvBADAbgsgPBARixwGoSBKCAbwCgIIBnAUwBcAVRAWyZAFcWowXgDsAxi0QhhUSlQiipDEABsmAOmUgA5lETlsAXwA0hdOggAqHPpoGgA)

**Comment by ShuiRuTian** [comment]
Emmmm, you can press F12 to see the console, they are actually logged, just not logged on "Logs" page.
Not sure, but I think https://github.com/microsoft/TypeScript-Website/issues is the better place?

**Comment by Aman-SS** [comment]
In playground 'Export' > 'Report Github issue on Typescript' took me to here. Anyways, filing it there and thanks for the clarification.
