### ISSUE TITLE
"declare module" definitions leak out of module

### ISSUE THREAD

**Issue by xatian** [microsoft/TypeScript#39315]
**TypeScript Version:**  3.9.5

**Search Terms:** declare module

**Code**

**foo.ts**
```ts
export class Foo {
}
```
**bar.ts**
```ts
import { Foo } from "foo";

declare module "foo" {
    class Foo {
        do_something (): void;
    }
}
Foo.prototype.do_something = function () {
    console.log ("Hello World");
}

export class Bar {
}
```
**main.ts**
```ts
import { Foo } from "foo";
import { Bar } from "bar";

const foo = new Foo ();
foo.do_something (); //<-- no error here
```
**Expected behavior:**
Error --> Property 'do_something' does not exist on type 'Foo'.
As a sidenote --> if `import { Foo } from "foo";` in main.ts is remove the error does occur.

**Actual behavior:**
No Error

**Playground Link:**
Not possible due to module-imports

**Related Issues:**
I think it is related to this: https://github.com/microsoft/TypeScript/issues/38592

Thank you!

**Comment by DanielRosenwasser** [comment]
This is an unfortunate "by design". In a module, those declarations are "module augmentations" that affect every file in the program.

I know, the syntax is terrible.

**Comment by xatian** [comment]
Fine thank you!
