### ISSUE TITLE
Function types: overload/merging behavior is unclear

### ISSUE THREAD

**Issue by layershifter** [microsoft/TypeScript#39313]
**TypeScript Version:**  3.9.2

**Search Terms:** interface, function types

**Expected behavior:**

1. Compiler error if overloads are not supported
2. `foo` is resolved to `number`, `string`, `null` type

**Actual behavior:** `foo` becomes `any` on `a` & `b`

```
Parameter 'foo' implicitly has an 'any' type.
```

**Related Issues:** N/A

**Code**
```ts
interface A {
    (foo: string): string
    (foo: number): number
}

interface B extends A {
    (foo: null): null
}

const a: A = (foo) => foo
const b: B = (foo) => foo

console.log(a, b)
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const a = (foo) => foo;
const b = (foo) => foo;
console.log(a, b);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-IAUMA9iQFzIDOYUoA5gJSU10j24FGkXIgCuAWwBG0ZnyGiouAL65coSLEQoAQsggAPSCAAmVNJk4FiZSgIA2F8ZYuz5OBCRA1kcSugC83Mo2SeAPmQeXCcXMGRhSnVvUxI-QOCyBzCqEgsIADoLEnpCOAAaSMYgA)

**Comment by RyanCavanaugh** [comment]
I don't see a described defect here

**Comment by layershifter** [comment]
![Screenshot_20200629-230300](https://user-images.githubusercontent.com/14183168/86055845-b97dac00-ba5c-11ea-826b-35b131c2c5b9.jpg)

I updated a playground, can you please check? It fails for `a` & `b`, but passes for `c` if there is a single definition without `extends`, [Playground Link](https://www.staging-typescript.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-IAUMA9iQFzIDOYUoA5gJSU10j24FGkXIgCuAWwBG0ZnyGiouAL65coSLEQoAQsggAPSCAAmVNJk4FiZSgIA2F8ZYuz5ORdHhJkAYSN4TPFrQaNkXzYOHDkcXAQSEBpkOEp0AF5uMgCEgD5kHgiomOFKdSTTElSMrJxI6LBkBEoPQp4SzLIHCqoSCwgAOgsSekI4ABpkYSGERiA)

**Comment by RyanCavanaugh** [comment]
Contextual typing can only apply a type to a parameter if there is a single overload to source the type from.
