### ISSUE TITLE
Intellisense stuck on loading after trying to index absolute import

### ISSUE THREAD

**Issue by Bluefitdev** [microsoft/TypeScript#39326]
- VSCode Version: 
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (5 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```
- OS Version: OSX 10.15.5 (19F101)

Steps to Reproduce:

1. My js config:

```
{
    "compilerOptions": {
        "baseUrl": "./src"
    },
    "include": [
        "src"
    ]
}
```

Bootstrapped with Create react app. Try to `import {} from "app/..."` goes loading. Afterwards intellisense won't work for 1-2 minutes until it starts working again in the code.

 
<img width="679" alt="Screen Shot 2020-06-23 at 9 51 14 am" src="https://user-images.githubusercontent.com/56941349/85346023-8062aa80-b537-11ea-99cb-8593e443c01e.png">

Does this issue occur when all extensions are disabled?: Yes

Same thing goes on, if i try to index some files from the import. intellisense stays on loading on the code for 1-2 mins. Its pretty annoying when I need to code fast so sometimes when it loads i moved back to vim :(

Can anyone help please?

<img width="702" alt="Screen Shot 2020-06-23 at 9 55 34 am" src="https://user-images.githubusercontent.com/56941349/85346115-d46d8f00-b537-11ea-83cb-2f2bba46478a.png">

<img width="574" alt="Screen Shot 2020-06-23 at 9 55 48 am" src="https://user-images.githubusercontent.com/56941349/85346121-d899ac80-b537-11ea-9a99-f01cb4a7ce20.png">

**Comment by mjbvz** [comment]
Moving upstream for more feedback

To help us investigate, can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

This may help us identify why intellisense is so slow

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Bluefitdev** [comment]
Hey I have created the server log.. but yes it contains some sensitive information and I don't want to risk it for anyone from my company to see that I violate the condition.

Can I share to you in any other ways? Probably on private Gdrive or something else. Please let me know, thanks heaps!

**Comment by mjbvz** [comment]
You can share them with: matb at microsoft. Google drive or email works fine

**Comment by Bluefitdev** [comment]
Emailed you mate.. Try to see if you received the invite

Thanks

**Comment by mjbvz** [comment]
Can you try sending the file directly. I don't know what google docs is doing but it doesn't seem to let me download the file:

<img width="871" alt="Screen Shot 2020-07-01 at 6 09 28 PM" src="https://user-images.githubusercontent.com/12821956/86305232-0761f380-bbc6-11ea-9eb7-d5133b6ba0b8.png">

**Comment by Bluefitdev** [comment]
Hmm that's odd,

No worries, just sent you the email. Its 11mb log file from dev at bluefit email

**Comment by sheetalkamat** [comment]
@Bluefitdev can you please try this with typescript@next. Does this still repro. If yes can you please share the latest logs. if you want you can email them to me at shkamat at microsoft dot com. Thanks

**Comment by robertwt7** [comment]
Yes this is still repro... I can email you the logs previously that I emailed to mjbvz

**Comment by sheetalkamat** [comment]
@robertwt7 we will need logs with typescript@next so we are looking at the latest things. i

**Comment by robertwt7** [comment]
So if i try to repro with the latest vscode, it should use the typescript@next lvm automatically right? 

I'll try to produce new log later

**Comment by Bluefitdev** [comment]
@sheetalkamat  I just sent you with the version `typescript: 4.1.2` in the log with latest vscode. Please double check

Thanks

**Comment by sheetalkamat** [comment]
@Bluefitdev can you please try out build at https://github.com/microsoft/TypeScript/pull/42428#issuecomment-764105745 to see how its working out. Please send the tsserver report with that build if things have not improved. Thanks.

**Comment by Bluefitdev** [comment]
I can confirm that this work. I got the intellisense almost instantly. Happy to go back to vscode!

Thanks
