### ISSUE TITLE
Is there any plan to have an option to make return type more "strict" ?

### ISSUE THREAD

**Issue by bodinsamuel** [microsoft/TypeScript#39320]
## Search Terms

- return type, infer, strict, structural typing

## Suggestion

> Please feel free to close this if it has already been discussed, I tried my best to find the answer but did not find exactly what I wanted.

Right now, Typescript is known to have a Structural Typing. I won't debate that point however I feel like it's inconsistant with the `strict` option. Some times Typescript complains that we can not assign a unknown property or that something should exists and some times not depending on the way you code.

So most of the times it gives the developer confidence on the code. But this confidence is broken in some that are only found the hard way, for example by allowing to return more than what should be allowed in a function. 
In the end, TS is a tool and it does not replace developer brain, but once your start relying on a tool it's harder and harder to known when to pay attention and when it's okay.

I also understand that "Structural Typing" is handy when passing parameter around (I'm using this feature everywhere so I'm quite convinced). However a return usually means you computed something, something that can be dramatically different than the params. 

I have no clue how everything works in the backend and my guess is that it's complicated :D 
But I would love, to have your opinion on this and maybe some optional flag to enforce strict return type so that I'm not allowed to return "equal or more" object, that could lead to errors and/or leaks of data.

## Examples

I have 2 scenarios where it makes me do mistakes:
- Structurally compatible object with "indirect return"
  - [Playground](https://www.staging-typescript.org/play?noUnusedLocals=true&noUnusedParameters=true#code/C4TwDgpgBAQghgZ2gXigbwFBW1AlgEwC4oFgAnXAOwHMBuDAXw2YHoWoBaL7n3v3qAFEAHnAC2YADbQAjBgBmAV0oBjYLgD2lKPI0aAFAEpi8JOiw4yEYIrLbMOR3iJQA5GVcAaC9iZMFymqa2roaMLgIRiaI0A6W1rb2Pk4ExO5eyY7AGmDE5IoQnlBsUBTUABbASpKSIFAqGhKScFTJfswBqupaUBrA5RBkUbAxUABk6FDZuVNkBVAM5o5WNnZLTtipbh7eG9jTeXOFbYzMSl3BUABGcEPGI2Zx2A2UpNdQqH0Dd-TLCWtXWjYEr4DQQBBQSh9eqNKQtSinIA)

- Method overload with different return type
  - [Playground](https://www.staging-typescript.org/play?#code/C4TwDgpgBAQghgZ2gXigbwFBW1AlgEwC4oFgAnXAOwHMBuDAXwwwHoWoBaL7n3v3qAFEAHnAC2YADbQATBgBmAV0oBjYLgD2lErgnSAFGDhlxxcoogBKYvCRQAZOijyNG4qQo0oDektXqtHT0IQ2NTKAAjV2k4SmtYRGhMHDx5KFCTMShkHKhzK3QsFJwyCGBFMm1k4pqCYgByMnqAGiKalJc3KHqIFqg2KBUNPTgqKABiBDh8NuKfWaYU2dLyysL2vCJuptaUpiYgA)

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code **(not sure but with the flag can be minor)**
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
The feature you're asking for is called exact types: #12936

**Comment by bodinsamuel** [comment]
Indeed @RyanCavanaugh that would cover the first scenario 👌 
I'm not sure about the overload, it's seems that it would requires extra logic? wdyt?
