### ISSUE TITLE
JavaScript incorrect type display in Visual Studio code editor 

### ISSUE THREAD

**Issue by GovindaramanNaganathan** [microsoft/TypeScript#39334]
- VSCode Version: 1.46.1
- OS Version: Windows 10

Steps to Reproduce:

step 1. Add the following javascript code

```js
var i = 10;
var i = "govind";


console.log(i);
console.log(typeof(i));
```

step 2. Hover over(Mouse over) the variable i (in any of the console log statement given above).......picture attached

step 3. Expected: During mouse/hover over,  variable i on the console statement should display "string" type
            Actual:     During mouse/hover over,  variable i on the console statement is displaying "number" type

Does this issue occur when all extensions are disabled?: Yes

Screenshot of the bug is attached:

![VS Code-type-bug](https://user-images.githubusercontent.com/67518351/85929582-ab505400-b8d3-11ea-9d21-78ddab61bdcf.jpeg)

**Comment by DanielRosenwasser** [comment]
Our of curiosity, is this a common pattern in your code? Could you tell us a bit more about the use-case?

**Comment by awerlogus** [comment]
The more general proposal is handling effects on type level. Something like

```ts
const a: [1, 2] = [1, 2]

// Now type of a is [1, 2]

a.push(3)

// Now type of a is [1, 2, 3]
```

But I'm not sure it's really necessary. The better way is just deny such constructions programmatically. Or just recommend to not use it.

**Comment by touchnewshiva** [comment]
Good Catch Govind

**Comment by GovindaramanNaganathan** [comment]
I have raised this bug to capture the correct type as per screenshot; the type of variable 'i' in line no. 5 has been changed to string. This is evident by looking at the output produces by JS. It would be really nice, If VS Code can recognize the type change and reflect accordingly.

**Comment by GovindaramanNaganathan** [comment]
> Our of curiosity, is this a common pattern in your code? Could you tell us a bit more about the use-case

I have raised this bug to capture the correct type as per screenshot; the type of variable 'i' in line no. 5 has been changed to string. This is evident by looking at the output produces by JS. It would be really nice, If VS Code can recognize the type change and reflect accordingly.
