### ISSUE TITLE
QuoteStyle not respected for string literal types in implement interface

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#39332]
From https://github.com/microsoft/vscode/issues/101219

**TypeScript Version:** 4.0.0-dev.20200629

**Search Terms:**

**Code**
Using `"typescript.preferences.quoteStyle": "single"`

```ts
interface IFoo {
  a(x: 'abc') : void;
}

class Foo implements IFoo {

}
```

Run implement interface on `Foo`

**Bug:**
The parameter value uses double quotes:

```ts
class Foo implements IFoo {
  a(x: "abc"): void {
    throw new Error('Method not implemented.');
  }
}
```

Also, if `typescript.preferences.quoteStyle` is unset, it would be nice if we used the original quote style for implement interface

**Comment by a-tarasyuk** [comment]
I'll look at this issue and open PR.
