### ISSUE TITLE
Intelligent code completion not working in child class with composited base interface

### ISSUE THREAD

**Issue by wayou** [microsoft/TypeScript#39346]
**TypeScript Version:**  3.9.5

**Search Terms:**

- `auto completion`
- `code intelligence`

**Code**

_Base.ts_
```ts
interface ILifeCycle {
  onA(): void;
  onB(): void;
}

// 🚨 all of these breaks the intelligent code completion
// type ComposedType = Partial<ILifeCycle>;
// type ComposedType = Pick<ILifeCycle, "onA" | "onB">;

// ✅ this is okay
type ComposedType = ILifeCycle;

export interface Base extends ComposedType {
  onC(): void;
}

export class Base {}
```

_MyClass.ts_
```ts
import { Base } from "./Base";

class MyClass extends Base {
  on| // here we expect the auto completion shows
}

```

**Expected behavior:**

- the auto completion for parent methods `on*` shows

**Actual behavior:**

- the auto completion for parent methods `on*` does not showing

**Playground Link:** [👉 check it out](https://www.staging-typescript.org/play?#code/PTAECEEMGcFMDoAu0BQKQRg5aCWA7RWAJwDNIBjWUASQBldTYBhATwoBtqBvFUUAPb4AggAoAlAC5QANwG4AJgG4+g-OAnS5ilQF80GQLwbgCr3QkDh0GlQiABaw4oAEbFYkANbQb90ASIXcAHNYQlAKAQVqcIBbAAcuRFwhdDBEVljqZgE4gTgFABV06gBeUAAFSGJE8wAeekYWdi4APhUMNIzQLJy8ws7SstwKdzqGJjZOWAAaUAAiIWFZ0AAfOaFwWdaDMEBQcm9cLwPBd0hWFA7M7Njc2AKi0FL68abYFRRYAA9rqt9CEnIqJhHJ8iPgFF5utdevdePwhMxNLJ5MoUPp3l8BD9ODAvFBHNw0RgALKsZgcHFIVAobHQLwksk40AgkLgoE8VTJfRAA)

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser What do you think about changing milestone for this issue from `Backlog` to `4.0.1`?

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
