### ISSUE TITLE
experimentalDecorators in Visual Studio

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#3934]
Hi. Great to see TS 1.5 finally released! Quick question which doesn't seem to be covered by the announcement / blog posts:

I see decorators have been hidden behind a compiler flag (experimentalDecorators). How can I specify this for a Visual Studio project? Guessing the answer is a tsconfig.json file, but after dropping one into the root of my project it still doesn't appear to pick it up:
```
{
    "compilerOptions": {
        "target": "ES5",
        "module": "system",
        "experimentalDecorators": true
    }
}
```

**Comment by mhegazy** [comment]
If you have a project file, tsconfig will not be honored. the project file takes precedence. We are still flushing the integration story between a VS project and a tsconfig as you can specify compiler options in both.

so to disable the error message, right-click on project file, unload project, then right-click edit the project file, At the end of the file there should be a config section, add:

```XML
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
     ....
    <TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators
  </PropertyGroup>
```
save and reload. 

You may also need `TypeScriptEmitDecoratorMetadata` to map `--emitDecroatorMetadata`

For the full list, see [Setting Compiler Options in MSBuild](https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects) page.

**Comment by Elephant-Vessel** [comment]
Where is the above mentioned integration story tracked?

**Comment by mhegazy** [comment]
supporting tsconfig as the main source of configuration should be in TS1.8 and is tracked by https://github.com/Microsoft/TypeScript/issues/5287
