### ISSUE TITLE
unexpected behaviour when use Omit with Insection Types

### ISSUE THREAD

**Issue by rust404** [microsoft/TypeScript#39359]
**TypeScript Version:**  3.9.2

**Search Terms:**
omit, insection types

**Code**
```ts

interface User {
  type: 'user';
  name: string;
  age: number;
  occupation: string;
}

interface Admin {
  type: 'admin';
  name: string;
  age: number;
  role: string;
}

type PowerUser = Omit<User & Admin, 'type'> & {
  type: 'powerUser'
};
let p: PowerUser = {
  type: 'powerUser',
  name: 'hello',
  age: 123,
  occupation: '123',
  role: '123'
}
console.log(p)
```

**Expected behavior:**
no error

**Actual behavior:**
```
test.ts:21:3 - error TS2322: Type 'string' is not assignable to type 'never'.

21   name: 'hello',
     ~~~~

test.ts:22:3 - error TS2322: Type 'number' is not assignable to type 'never'.

22   age: 123,
     ~~~

test.ts:23:3 - error TS2322: Type 'string' is not assignable to type 'never'.

23   occupation: '123',
     ~~~~~~~~~~

test.ts:24:3 - error TS2322: Type 'string' is not assignable to type 'never'.

24   role: '123'
     ~~~~

```

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=26&pc=15#code/LAKAlgdgLgpgTgMwIYGMYAICqBne6Deo66UAngA4wBc6A5AK65y0DcR6ESAttetlHEgBzNiGJIhvCPS4AjeKOIB7FCnrkkUMEog1+giCNABfUKEixEqDAEEAJl0gF2ZSjVpIHkVu0489AsKK6BJSMvJwwXBKADa8+kEmZiCuGAAKSgDu8Dh4ALzoAPKOUAA8uXDoAGTo9o4QADR0qbQAfNXOYiQUvLTkWTlMtCaicVDo5DQZ2XAV6AWEXanu-TMVtA2+3L0AFjAxMUob7KE0AIwATADMm10qahpaOu6XV8dd0XEv18MgpiAoHTYWIwAB0hyEAApyABKIA
**Related Issues:**

**Comment by dragomirtitian** [comment]
This is related to a recent change in behavior from https://github.com/microsoft/TypeScript/pull/36696, where object types that contain a `never` field are reduced to `never`.  

You can change your types to this:

```ts

type PowerUser = Omit<User,'type'> & Omit<Admin,'type'>  & {
  type: 'powerUser'
};
```
[Playground Link](https://www.typescriptlang.org/play/?ssl=18&ssc=3&pln=15&pc=1#code/LAKAlgdgLgpgTgMwIYGMYAICqBne6Deo66UAngA4wBc6A5AK65y0DcR6ESAttetlHEgBzNiGJIhvCPS4AjeKOIB7FCnrkkUMEog1+giCNABfUKEixEqDAEEAJl0gF2ZSjVpIHkVu0489AsKK6BJSMvJwwXBKADa8+kEmZiCuGAAKSgDu8Dh4ALzoAPKOUAA8uXAANLSptAB86ABkRSWl9o4Q1bUNTc5iJBS8tORZOUy0JqJxUOjkNBnZcBXoBYT9qe4jixW0lb7cQwAWMDExSrvsoTQAjABMAMx7-SpqGlo67nf3F-3RcZ8PCYgUwgFA6bCxGAAOjOQgAFOQAJRAA)

**Comment by RyanCavanaugh** [comment]
@dragomirtitian has it right 👆
