### ISSUE TITLE
Type Aliases doesn't act as handbook said

### ISSUE THREAD

**Issue by shockw4ver** [microsoft/TypeScript#39355]
**TypeScript Version:**  3.9.2

**Search Terms:**
Interfaces vs. Type Aliases

**Expected behavior:**
As handbook says, hovering over `aliased` should show returns a **object literal type**

**Actual behavior:**
It showed `function aliased(arg: Alias): Alias` as well as hovering `interfaced` did.

**Related Issues:**

**Code**
```ts
type Alias = { num: number }
interface Interface {
    num: number;
}
declare function aliased(arg: Alias): Alias;
declare function interfaced(arg: Interface): Interface;

```

<details><summary><b>Output</b></summary>

```ts
"use strict";

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ssl=6&ssc=56&pln=1&pc=1#code/C4TwDgpgBAggNgSwIYGcoF4oG8oDsCuAtgFx5EBGEATlAL4BQCuw1AZkgMbQCSzbn0LPSgiyJMZSoBuegwAmEDnCRVorfLg7AEAe1xQkiVBDkAKFQHNS8ZCgCU1oyhkKlKtRq279TFlXZcZpakvH4BEA5QofxcMkA)

**Comment by RyanCavanaugh** [comment]
Which page did you read this on?

**Comment by orta** [comment]
The hover info will only show the literal when you hover over the type specifically, not everywhere that uses it.

I assume it is because it would be harder to read the function signature.

**Comment by shockw4ver** [comment]
@RyanCavanaugh 
Got this at [Interfaces vs. Type Aliases](https://www.typescriptlang.org/docs/handbook/advanced-types.html#interfaces-vs-type-aliases)
Thx 🙏

**Comment by shockw4ver** [comment]
> The hover info will only show the literal when you hover over the type specifically, not everywhere that uses it.
> 
> I assume it is because it would be harder to read the function signature.

Info from hovering on type itself is as expected, so maybe the handbook got some ”errata“？

**Comment by RyanCavanaugh** [comment]
This page has been rewritten
