### ISSUE TITLE
Wrong conditional type breaks code

### ISSUE THREAD

**Issue by arogg** [microsoft/TypeScript#39358]
**TypeScript Version:**  latest (nightly playground)

**Search Terms:** infer generic const

**Code**

https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200701&ssl=2&ssc=65&pln=2&pc=69#code/FAFwngDgpgBA8gIwM5QE4DcCGCA2UA8AKgHwwC8MACqgPYC2AlikcQNwwD0HMAVgK5IQMAGaYA1gwB2AcxioAHjyQwayNFlyxw0YKEixCqTJKTCaqOgEYW5GIRhR5IKJIAmy6vSYEpwtDABVUgB+eDUMbDx8IJgALjCUCM0WVj1oOyMTMwsAJhsKRESNKJJUtK1LW0NjU3MrfAQaGjxjNnKYEByqzNrchqaWyTZObiQACxo+HFcYMAYoaZgkTDotfRhMZRBLABoYBD4hVxooZUkaEF0OACpgRpAxjJrsqw23J6y6roBlAAk4AIAGQAIjBjg55JgAMYgHBgDpjWDLVYIqSybIddYAIkazSgxixugAmgBRezbN4zTobVCwYEASQAYoySQAlEkAOXJ+iQugA6r8iTAGBs6DAIDRBGjUUhYrptBV9rTxMoFEoYAAKanHU4wc4gACUcuAUJoJiEqmUsW2FEkUxwG2UxjAqUtADoIAxoBq6JgIBqaGRiABmA0G9hcByoWioXQwa4cIA

both Transform1 and Transform2 SHOULD do exactly the same thing for type "boolean"

YET t1 and t2 are DIFFERENT types

WHY i am posting this:

type t1 breaks rxjs (t2 does not):
```
const obs :t1= null as any;
obs.pipe(map(o=>3)); // error
 ```

a far BETTER example:

https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200701#code/FAFwngDgpgBAKgJwIYDsDOAzA9ggtgRgB44A+GAXnhigA8QoUATNGABQS1wEs0pCuUGKAhgBVMgH4YAQQTIwhcTABcMuUgWkA3KEixEqTDlwAmYmUqz55nbugwQ+CvGTpseIgCMsWADZRUEh1wexATZwM3YzNvPwCUIJgAeiSYNAALLABXX0YYMC4oXLSkXFgQ2CQWRwAaGE8skBhGLCgWFCwQYGAANyQRPoR8VUdnFBzfGCqplDAdQZhBkxHwynHfSenUOe7B-AA6XCQIAAosCjIAZgBKLWTU4Q4EXv6TQ+Ozi5gbu5SYDuochwQA

a workaround would be ok with me (how i can transform t1 back to t2?)

**Comment by MartinJohns** [comment]
[Distributive conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types)

Use this instead:

    type Transform1<T> = [T] extends [Promise<infer U>] ? Observable<U> : Observable<T>;

**Comment by arogg** [comment]
Ok thanks, but unfortunately not getting anywhere. Is THIS a bug?

https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200701&ssl=5&ssc=33&pln=5&pc=40#code/C4TwDgpgBAKg9gQQE5IIYgDwwHxQLxQDaMAulBAB7AQB2AJgM5EAKScAtgJYMQac0AzCEigBVbCQBQUKAH4oyNJnHSZUAFwKU6LNgDcqyaEhQAEhAA2kJFnJVajKAAoAlHmyoaIXHniKdAEoQwACuSDQw4Lw4+pKSAPTxdpAAxsBQwHBQAEbQDKjs0MYQDAA0OSHpqEjQAHIA8jBGUVBBDCEW6QTmVsIYrvi42XBwFhCescWtJR3AAEwEftqYQaHhkZD9LoM5I2MTsUA

**Comment by RyanCavanaugh** [comment]
Please don't just paste raw playground links, it makes it very difficult for us to read without inline code samples and makes it impossible for other to use search terms to find similar issues.

**Comment by arogg** [comment]
Sorry, I understand. Still, I'm unsure if any of the code samples are bugs because of missing feedback. I will do my best to double check I have actually found bugs, and will open new issue(s) if that is the case and in a proper manner.
