### ISSUE TITLE
Feature Request: Mapped Computed Property Names

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/TypeScript#39369]
## Search Terms

json
json mapping
mapped computed property names

## Suggestion

Re-purpose computed property names to automatically handle mapping at build, but alias property as another name during development.

Today, let's say I use an API I don't control that yields the following:
`{"d":"acb123","n":"Sample","s":"c"}`

That's not terribly descriptive of what's contained. I could create an interface to represent this with the following:

```
interface Sample {
  d: string;  //ID
  n: string;  //Name
  s: State; //State enum (below)
}

enum State {
  Completed = <any>"c",
  Pending = <any>"p",
  Error = <any>"e"
}
```

Given that I can specify the actual values to expect in the enum, this will map right up when I just cast a response to the Sample interface without issue. But it's a pain to develop against this interface, because I constantly have to keep in mind which property name actually represents what. I'd much rather have an interface like the following:

```
interface BetterSample {
  id: string;
  name: string;
  state: State;
}

```
In order to get here, I have to add a mapping function and manually line up each of the properties on either end, which is error prone and requires maintenance should the shapes ever change. 

I think the use of the computed property names nearly resolves this. Being able to do something like the following would be nearly ideal:

```
const id = "d";
const name = "n";
const state = "s";
interface BetterSample {
  [id]: string;
  [name]: string;
  [state]: State;
}
```

Unfortunately, it just barely misses the mark because in development, I still reference the name property as `BetterSample.n` instead of `BetterSample.name` as it's computed by the IDE. It'd be great to have this go one step further and defer computation of these property names until build instead of the IDE actually computing these. 

Even better, it would be something like, eliminating the need for two lines for each property, and putting the mapped value closer to the property name itself.

```
interface EvenBetterSample {
  [id="d"]: string;
  [name="n"]: string;
  [state="s"]: State;
}
```

## Use Cases
As described above, this would allow for trivial JSON mapping to interfaces of primitive types. Rather than try to do the same with decorators, or a mapping function, the JSON value would be clearly noted in the interface itself while still allowing the developer at dev time to have contextual knowledge of what the response values actually are.

**Downsides to existing approaches**
_Mapping function_
Still necessary for mapping to class instances or any more elaborate mapping, but especially for simple 1:1 maps, this takes a cumbersome and error-prone step out of the picture and leave it to TypeScript to simply emit the constant value in the output (as it does with the computed property names anyway). For anything that does require this more elaborate mapping, just opt out of using this altogether for that property and only have to map those complex objects - everything else is easily cast-able (as is currently done with JSON -> interfaces for like-name properties).

_Decorators_
Like the mapping, it's error prone around class instance mapping or something more elaborate (e.g. nested objects, handling serialization/deserialization, collections) adds complexity to the implementation.

## Examples

As described above, given a JSON object:

```
{
  "d": "abc123",
  "n": "Sample"
  "s": "c"
}
```

It'd be great to be able to trivially develop against this with contextual property names at development time, but know that Typescript will actually use the API values at runtime with something like the following.

**Option 1**
Re-purpose computed property names, but configure to allow the constant name itself show in the IDE instead of the value of the constant.

```
const id = "d";
const name = "n";
const state = "s";

interface Option1 {
  [id]: string;
  [name]: string;
  [state]: State;
}

enum State {
  pending = <any>"p",
  completed = <any>"c",
  error = <any>"e"
}

```
**Option 2**
Put the mapping value in-line in the computed property name, then show the name of the constant in the IDE instead of its value.

```
interface Option2 {
  [id="d"]: string;
  [name="n"]: string;
  [state="s"]: State;
}

enum State {
  pending = <any>"p",
  completed = <any>"c",
  error = <any>"e"
}
```

## Practical Example
At development time, I can trivially use this to map from an RXJS request in Angular:

```
this.myService.getData()
  .subscribe((data: Option2) => {
   //Do something with it, without further ado
 });
```

In practice, at development time, the properties would be trivial to use and self-explanatory, and at runtime, the build would map against the shortened values actually used by the API.

Mapping may be required for all sorts of different reasons. The written language used between the API and the consuming app may vary, the API may use shortened values as in the above, the casing may simply vary from app conventions - whatever the reason for the mapping, it'd be ideal if Typescript made the development experience simpler to use 1:1 mappings. This aligns with the design goals in numerous ways: it eliminates an opportunity for "magic string"-based errors, it imposes no run-time overhead and, with the use of something like Option2, would not cause a breaking change with current Typescript syntax.

Thank you for your consideration.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
> In practice, at development time, the properties would be trivial to use and self-explanatory, and at runtime, the build would map against the shortened values actually used by the API

This is type-directed emit, so it's not something we would do.
