### ISSUE TITLE
Parent class is incompatible with base class if base has function properties with polymorphic "this" as an argument

### ISSUE THREAD

**Issue by mcpower** [microsoft/TypeScript#39375]
**TypeScript Version:**  4.0.0-dev.20200630 (occurs since 2.7.1 after testing in the playground)

**Search Terms:** is not assignable to type, does not satisfy the constraint, extends, polymorphic this, class

**Code**

```ts
interface Ctor<T> {
    new(x: T): any;
}

interface Builder<T> {
    build(x: T): any
}

// Uncomment any "bad" property to cause the bug.
class BaseClass {
    // bad1?: Ctor<this>;
    // bad2?: (x: this) => any;
    // bad3?: new (x: this) => any;
    // good1?: Builder<this>;
    // good2?: () => this;
    // good3?: new () => this;
    // good4(x: this): any {}
}

class ParentClass extends BaseClass {
    foo() { }
}

let x: BaseClass;
x = new ParentClass();
```

**Expected behavior:** `ParentClass` is always assignable to `BaseClass` (as it extends it) after uncommenting any of the properties in the example.

**Actual behavior:**

An error mentioning that `ParentClass` is not assignable to `BaseClass` after uncommenting a "bad" property. For example, when using `bad2` in the example above:

```
Type 'ParentClass' is not assignable to type 'BaseClass'.
  Types of property 'bad2' are incompatible.
    Type '((x: ParentClass) => any) | undefined' is not assignable to type '((x: BaseClass) => any) | undefined'.
      Type '(x: ParentClass) => any' is not assignable to type '(x: BaseClass) => any'.
        Types of parameters 'x' and 'x' are incompatible.
          Property 'foo' is missing in type 'BaseClass' but required in type 'ParentClass'.(2322)
```

This also affects type parameter constraints: if a type parameter is `<T extends BaseClass>`, then `T` can't be set to `ParentClass` (giving a `Type 'ParentClass' does not satisfy the constraint 'BaseClass'` error).

The "good" properties can be uncommented without causing the bug. Interestingly, the definitions for `Ctor` and `Builder` are almost identical, but `Ctor` causes the bug while `Builder` does not.

**Playground Link:**  https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200630&ssl=1&ssc=1&pln=26&pc=1#code/JYOwLgpgTgZghgYwgAgMJgPZQDwBUB8yA3gLABQylyIEA7gBQAeAXMrgJStwgCeA3OQC+5cqEixEKAEIBXYABsAJtDyFSFKgCM5Spqw5deQkWQD0p5AFUQCDAFs7EcMm49kAIk1xF75AAcoDD9oMDdMZAQ4GQBnFDAACxRtAHMAOnIEeTho6OQpbIhULJzicipkc2QvRQBGAH5WdCxsBOBo-AENSkrqgCYG5D1kVuj2ZABeQldO8p7vAGYBmlpBlmH4trHJl14ZqkrkjAxagdkFZRwRjrL9i0Pj-tZ6LcIRve67o8VF1mXBl-WbXeFU+xwALEMRpwdm4iMIyPCMsVcgAFOBQJxgIrZXIQRiQECKXL5WLYkrqcowI7PYjIeGIsjyCBgZBrEmFZGdRgTah0ZBojHgMnRZ6dIA

**Related Issues:**  I believe #21662 is the same issue, but specific to JSX "intrinsic class attributes".

**Comment by RyanCavanaugh** [comment]
This is a correct error. If this were allowed, something like this could happen:
```ts
class BaseClass {
    bad2?: (x: this) => any;
}

class DerivedClass extends BaseClass {
    foo() { }
    constructor() {
        super();
        this.bad2 = self => self.foo();
    }
}


const x: BaseClass = new BaseClass();
// @ts-ignore
const y: BaseClass = new DerivedClass();
// Crashes
y.bad2 && y.bad2(x);
```

**Comment by mcpower** [comment]
Thank you for the clear explanation!

Interestingly, `Builder` in the example above seems to be bivariant instead of contravariant. I assume it's because `build` is a method, so "[Why are function parameters bivariant?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)" seems to be taking place here - so it's working as intended.
