### ISSUE TITLE
Optional properties with object shorthand syntax

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#39376]
## Search Terms
object shorthand optional

## Suggestion
Allow to specify optional properties in object shorthand syntax. If the variable is `undefined`, the property will not be added to the object (instead of being added with value `undefined`). Proposed syntax is to add a question mark to the property name, for example `{ prop1, prop2? }`.

## Use Cases
Goal is to create one object with a short clear (one-line) syntax.

On StackOverflow, this issue is discussed here: https://stackoverflow.com/questions/54909137/how-to-conditionally-set-optional-properties
The proposed solution uses object spread syntax. But this may have performance impact (temporary objects, property iteration) and is way too verbose.

## Examples
```
interface Test {
  required: number;
  optional?: number
}
let required = 42;
let optional: number | undefined;
```
Current solution:
```
const object: Test = { required };
if (optional !== undefined) { object.optional = optional; }
```
**Proposed solution:**
```
const object: Test = { required, optional? };
```
The compiler would convert this to the solution above with if statements as needed.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I have no idea about the last point though... :/ At least I did not find a comparable ES proposal.

**Comment by DanielRosenwasser** [comment]
Hmm, that's an interesting idea for a design proposal given the sorts of hacky object spread syntax.

**Comment by RyanCavanaugh** [comment]
There's always
```
const object: Test = { required, ...{optional && { optional } } };
```

I think this is out of scope for TS; it doesn't have anything to do with type checking

**Comment by danielrentz** [comment]
OK thanks, I'll try my luck with an ES proposal.

**Comment by danielrentz** [comment]
For the records. Just found an existing idea in the TC discuss groups: https://es.discourse.group/t/optional-property-shorthand-in-object-literal/196
Not much action since 2018 though...
