### ISSUE TITLE
Generic type extending primitive should allow default value

### ISSUE THREAD

**Issue by Ignasimg** [microsoft/TypeScript#39377]
Earlier today I was trying something along the lines of:

`function test<T extends boolean>(v: T = false) {}`

I don't know how would one extend boolean, but even then if I try something like:

`function test<T extends false>(v: T = false) {}`

I get an error message saying: 

Type 'false' is not assignable to type 'T'.
  'false' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'false'.

---

I know I can just use **false as any** but then I'd be losing some information I'm using later on, in concrete to get a specific return type out of conditional parameters.

**Comment by DanielRosenwasser** [comment]
Like you mentioned, a union of literal values is always a subtype of a primitive. `boolean` is a slightly more special case since its domain is finite, but even then `never` is a subtype of `false`. I guess understanding why you needed a type parameter would be helpful.

**Comment by Ignasimg** [comment]
Ok I understand never is a subtype of false.

I was trying to do something similar to this: [https://stackoverflow.com/a/54166010](https://stackoverflow.com/a/54166010) but passing in a default value.

Maybe a solution would be to define what a generic type is, like **T is boolean**, althought it wouldn't make much sense to call it a generic type anymore.

I have noticed that I can do something like

`<T extends boolean = false>(param?: T)`

And in such scenario, typescript won't complain and will correctly infer the type, however the code generated is not what I want, since param wouldn't be false by default.

[Playground sample](https://www.typescriptlang.org/play/index.html?ssl=22&ssc=63&pln=22&pc=56#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QNzgBsBXCAfTgC5kByVWrAXyy1ElkRQCFMc9CpCgCMatboxZYwATwAOKVAHso3ADwAVAHzIAvP1wbkEAB6QQAEwDOyMFDLIA-GmRUDyI6fPXk8IlZRnXjc8ZBAIfGgAblYAeljkAHUACzgwZABJZAB3JRIiC2QiYABrFDAlZERk4AiILBgSEAQwYCUQZABzCDBlVU1jMwhLG2ElJSIIOBAtAAps6d6aI11bewgASho+9W0+UOAYZHnF1A3kKB6SKA6MAmIySjEGZCYqmx3NLRjQiH8US5ga63e5CciiOgSV7vNAqXbfZisLDxJKpdK5KAlGygWzyCBWBBQYBydLCEjpCxKfEgWjpbrhKBpFAIFSXFrIABWcEIBKJJIaTRabQ63V6cPI+AATAMvMMfGMJlMOqs7GQ5gtwKhHMtztgDkcTprzoDgZhQY9qHQXm84B84V8fng-gELlcbmbBI8IeJaNDbbD+toYiwgA)


Personally I think that it all comes down on whether typescript wants to allow infering dependencies from parameters, which I understand can be a very complicated subject, but should be simpler if we just talk about primitive types.

Maybe someone with a wider view can shine some light into this issue.
