### ISSUE TITLE
const {} = require import causes Debug Failure

### ISSUE THREAD

**Issue by KSahithyan** [microsoft/TypeScript#39373]
**TypeScript Version:** 3.8.3, 4.0.0-dev.20200701 (tested on both versions)

**Search Terms:** typescrpt importing problem (Error. Debug Failure.)

**Code**

```ts
// H is a exported class in a file called test.ts in the same directory.

// when using this line, the error is shown
const { H } = require('./test');

// when using this line, the error is gone
// import { H } from './test';

```

**Expected behavior:** When running `tsc -b`, tsc builds the project. 

**Actual behavior:** `tsc -b` returns an error.
```sh
$ tsc -b
/usr/share/nodejs/typescript/lib/tsc.js:81040
                throw e;
                ^

Error: Debug Failure.
    at Object.assertDefined (/usr/share/nodejs/typescript/lib/tsc.js:1724:24)
    at /usr/share/nodejs/typescript/lib/tsc.js:13692:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/usr/share/nodejs/typescript/lib/tsc.js:13692:21)
    at createFileDiagnostic (/usr/share/nodejs/typescript/lib/tsc.js:13712:20)
    at createDiagnosticForNodeInSourceFile (/usr/share/nodejs/typescript/lib/tsc.js:10181:16)
    at Object.createDiagnosticForNode (/usr/share/nodejs/typescript/lib/tsc.js:10171:16)
    at handleSymbolAccessibilityError (/usr/share/nodejs/typescript/lib/tsc.js:73879:50)
    at checkEntityNameVisibility (/usr/share/nodejs/typescript/lib/tsc.js:74252:13)
    at visitDeclarationSubtree (/usr/share/nodejs/typescript/lib/tsc.js:74389:29)
```

**Playground Link:** This is a problem related to importing. I don't know where can I do that.

**Related Issues:** I didn't find any related issues

**To Reproduce:** Clone this [repo](https://github.com/KSahithyan/ts-bug) to reproduce

**Comment by DanielRosenwasser** [comment]
Don't necessarily know which combination of flags triggered this, but here's an easy copy/paste test for anyone looking at this.

```ts
// @module: commonjs
// @esModuleInterop: true

// @filename: client.ts
const { H } = require('./test');

// when using this line, the error is gone
// import { H } from './test';

export default class extends H {
    newProperty: any;
}

// @filename: test.ts
export class H {
}
```

**Comment by DanielRosenwasser** [comment]
This should be easy to fix. Some error message is taking too many or few parameters

**Comment by KSahithyan** [comment]
@DanielRosenwasser Exporting with name (as shown below), fixes the problem too.
```typescript
// client.ts
export class Yadda extends H {
}
```

**Comment by a-tarasyuk** [comment]
```ts
const { Foo } = require('./b');
export default class Bar extends Foo {} // TS4020: 'extends' clause of exported class 'C' has or is using private name 'Foo'
```

```ts
const { Foo } = require('./b');
export default class extends Foo {} // This is ClassExpression which doesn't have a name, however, diagnostic message expects a class name.
```

@DanielRosenwasser I'm not sure, do we need to add a new message for this case or need to omit this error for Class Expressions?

**Comment by Soni295** [comment]
Hello mr. I think your problem is Because in typescript use require only for one export with out  "{ }"   and import for one or more module blocks. example
const H = require('./test');// Yes
const J = require('./test');// Yes
const { H, J } = require('./test');// No
import {H, J, K} from "./test";//Yes
https://www.typescriptlang.org/docs/handbook/modules.html
in Optional Module Loading  explain better this.
