### ISSUE TITLE
Component cannot be used as a JSX component. Its return type 'Element[]' is not a valid JSX element

### ISSUE THREAD

**Issue by RaiderII** [microsoft/TypeScript#39391]
I'm currently getting the following error on the `Todos` component inside `TodoApp.tsx`: 'Todos' cannot be used as a JSX component.
  Its return type 'Element[]' is not a valid JSX element.
    Type 'Element[]' is missing the following properties from type 'Element': type, props, key

And this is my folder structure

`TodoApp.tsx`

```
function TodoApp() {
  return (
    <Body>
      <AppDiv>
        <Form />
        <Todos />
        <Footer />
      </AppDiv>
    </Body>
  );
}
```

`Todos.tsx`

```
function Todos(): JSX.Element[] {
  const todos = useSelector((state: RootState) => state.todos);
  const footer = useSelector((state: RootState) => state.footer);

  if (footer.hideAll) {
    if (footer.showCompleted) {
      return todos
        .filter((todo) => !todo.completed)
        .map((todo) => (
          <>
            <ul>
              <Todo todo={todo} />
            </ul>
          </>
        ));
    }
    return todos.map((todo) => (
      <>
        <div>
          <Todo todo={todo} />
        </div>
      </>
    ));
  }

  return todos.map(() => (
    <>
      <div></div>
    </>
  ));
}
```

`Todo.tsx`

```
type Todo = {
  todo: TodoProps;
};

const Todo = ({ todo }: Todo) : JSX.Element => {
  const [isEditing, edit] = useState<boolean>(false);
  const dispatch = useDispatch();

  if (!isEditing) {
    return (
      <TodoDiv>
        <Li
          key={todo.id}
          completed={todo.completed}
          onClick={() => dispatch(completeTodo(todo.id))}
          // style={{
          //   textDecoration: todo.completed ? "line-through" : "none"
          // }}
        >
          {todo.text}
        </Li>
        <TodoBttns>
          <Button edit onClick={() => edit(!isEditing)}>
            <img src={editBttn} alt="Edit Button" />
          </Button>
          <Button delete onClick={() => dispatch(deleteTodo(todo.id))}>
            <img src={deleteBttn} alt="Delete Button" />
          </Button>
        </TodoBttns>
      </TodoDiv>
    );
  } else {
    return (
      <FormEdit>
        <InputForm key={todo.id} {...{ todo, edit }} />
      </FormEdit>
    );
  }
};
```

and the TodoProps interface is the following:

```
interface TodoProps {
  text: string;
  completed: boolean;
  id: string;
}
```

already tried the fix of wraping the map items with fragments, but I still can't make it work. The only thing that as of now is fixing the issue is declaring at the top of `Todos.tsx` as this `function Todos(): any`

As a side note: I'm using Styled Components, but I don't think the issue is related to the library.

**Comment by DanielRosenwasser** [comment]
You posted this on StackOverflow and got an answer https://stackoverflow.com/questions/62702485/component-cannot-be-used-as-a-jsx-component-its-return-type-element-is-not

**Comment by StringEpsilon** [comment]
Seems to be caused by  https://github.com/microsoft/TypeScript/issues/21699.

See also here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20356

**Comment by Prince890840** [comment]
D:/SmartRestaurant-SuperAdmin/src/components/Layout/Layout.tsx
TypeScript error in D:/SmartRestaurant-SuperAdmin/src/components/Layout/Layout.tsx(91,16):
'PrivateRoute' cannot be used as a JSX component.
  Its return type 'void' is not a valid JSX element.  TS2786

    89 |               <Route path="/shop/edit/:id" exact component={Shop} />
    90 | 
  > 91 |               <PrivateRoute exact={true} path="/login" component={Login} />
       |                ^
    92 |             </Switch>
    93 |           </div>
    94 |         </section>

**Comment by Prince890840** [comment]
D:/SmartRestaurant-SuperAdmin/src/components/Layout/Layout.tsx
TypeScript error in D:/SmartRestaurant-SuperAdmin/src/components/Layout/Layout.tsx(91,16):
'PrivateRoute' cannot be used as a JSX component.
  Its return type 'void' is not a valid JSX element.  TS2786

    89 |               <Route path="/shop/edit/:id" exact component={Shop} />
    90 | 
  > 91 |               <PrivateRoute exact={true} path="/login" component={Login} />
       |                ^
    92 |             </Switch>
    93 |           </div>
    94 |         </section>
