### ISSUE TITLE
VS2015 RTM: Compile on save does not work when redirect JavaScript output is specified

### ISSUE THREAD

**Issue by sgreer** [Microsoft/TypeScript#3939]
Hello,

I upgraded to Visual Studio 2015 Community Edition RTM today and have found that if a TypeScript project has the "Redirect JavaScript output to directory" option set to true, then compile on save no longer functions.  Deselecting this option on the project causes compile on save to function as expected.

The repro is quite simple: create a new project of type "HTML Application with TypeScript".  Open app.ts, make a change and save the file.  Now open app.js, make a change to the app.ts and save - app.js is reloaded with the changes.

Now add a folder to the project named "Scripts" and change the project properties such that "Redirect JavaScript output to directory" is checked and the path is "./scripts".  Make a change to app.ts and save the file.  Note that app.js does not show up under the "Scripts" folder.  Build the project and note that app.js now appears under the "Scripts" folder.  Open this file, make a change to app.ts and save the file - /scripts/app.js is not updated.

**Comment by Sharpiro** [comment]
I am also experiencing this issue.  Do you think there will be an interim build that will fix this?

**Comment by NoelAbrahams** [comment]
What the Lord giveth with one hand, he taketh away with the other.

**Comment by sgreer** [comment]
I've been able to workaround the issue using grunt.  I updated my gruntfile to have a watch task that copies the files to the required directory after the JavaScript file is emitted by the TypeScript compiler.  You have to bind the watch task to the Project Open event in the Task Runner Explorer, but then it works flawlessly.

I'd be interested in an interim build as well, however this will work for the time being.

**Comment by paulvanbrenk** [comment]
I also found that a fully qualified path works for both the single file and the directory redirection.

**Comment by sgreer** [comment]
Thanks, Paul!  That's very good to know.

**Comment by paulvanbrenk** [comment]
I checked in a fix for this, which should be part of 1.6

**Comment by NoelAbrahams** [comment]
@mhegazy, 

This has been marked as a high priority issue, but then it only be available in 1.6, which is probably many months away.

Putting in a workaround (of copying the files to the output directory) is going to be quite an undertaking, because we have 40 plus projects to worry about.

Is there any chance of getting this fix early?

**Comment by ilmax** [comment]
I'm asking for an early fix either.

**Comment by ctrlShiftBryan** [comment]
Hoping for a fix before 1.6....

**Comment by Sharpiro** [comment]
Also requesting an interim build

**Comment by Gitgiddy** [comment]
:+1:

**Comment by taicho** [comment]
This has also ruined the ability for my projects containing TypeScript with --out to build normally. Unfortunately my team and I will not be able to use VS 2015 with our current projects as the redirect output option for TypeScript does not appear to use relative paths anymore and appears to not honor the VS macros i.e. $(ProjectDir). Anybody that has embraced TypeScript and makes heavy use of it will undoubtedly run into this issue - has it been marked as critical?

**Comment by taicho** [comment]
To add to the pitch forks - we need an interim build or patch otherwise it's back to VS 2013 for those of us who love TS.

**Comment by taicho** [comment]
Why is this issue closed? The bug may be fixed but it is a critical issue to any real-world user of TypeScript. Please re-open to give this issue much needed attention...

**Comment by mhegazy** [comment]
@taicho we are working on it. hopefully i will have an update in the next day or so..

**Comment by taicho** [comment]
Thanks for the prompt response @mhegazy! Sorry for the trolling I just wanted to make sure this didn't get lost in the sea tasks.

**Comment by ddotlic** [comment]
> What the Lord giveth with one hand, he taketh away with the other.

@NoelAbrahams  If there was a way to "Like" a comment or "+1" it, I would have done so multiple times for this comment of yours :grinning:

**Comment by qbunia** [comment]
I managed to fix the issue in my case: 
Instead of writing in Combine JavaScript output into file: 
AllTypescripts.js
I wrote
C:\\Users\\Qbusoft\\Desktop\\AngularTest\\AngularTest\\AngularTest\\AllTypescripts.js

and now everything works fine :+1:

**Comment by Gitgiddy** [comment]
Any update?

**Comment by kennyatappfive** [comment]
I'm unable to use 2015 because of this issue.

**Comment by kamranayub** [comment]
I see an update in the Product Updates tab of Extensions. However it says it's unable to install.

![image](https://cloud.githubusercontent.com/assets/563819/9143808/1ea7c8ee-3d0e-11e5-9d59-59f7bf85addf.png)

I don't see anything in `C:\Users\Kamran\AppData\Local\Temp` that I could check.

**Comment by paulvanbrenk** [comment]
Adding @yuit who may have some insights on the install issue

**Comment by yuit** [comment]
@kamranayub, I am investigating the issue. Jut want some more information: what VS sku you are running an upgrade? and what older TypeScript version you are on

**Comment by kamranayub** [comment]
@yuit, VS Community 2015, at 1.5.4 right now.

**Comment by yuit** [comment]
@kamranayub  you are able to get the latest update 1.5.4 ? Could you tell me detail of TypeScript entry in the Programs and Features (i.e Name, Version in particular)?

**Comment by mhegazy** [comment]
Can you share the install logs. they should be in %TEMP%, they have a prefix of "dd_TypeScript*", also if you can share the files with "dd_SecondryInstaller*"?

**Comment by yuit** [comment]
Please see this issue  #4229 for any wrong displaying error message

**Comment by yuit** [comment]
@kamranayub We can't repo your issue. If you still have the problem, please send us files @mhegazy specified

**Comment by kamranayub** [comment]
@yuit, no I mistyped, 1.5.3--can't install 1.5.4.

@mhegazy Sorry, there are no files under %TEMP% following that pattern. I doubt the installer even runs, it happens as soon as I click "Update."

![image](https://cloud.githubusercontent.com/assets/563819/9147980/b19eee58-3d35-11e5-8fdf-b8b9439ec897.png)

**Comment by mhegazy** [comment]
@sgreer, @kennyatappfive, @Gitgiddy, @ddotlic  and @taicho can you give the latest update a try. you should see a new update in your tools\Extensions and Updates\Updates.

sorry for the delay.

**Comment by taicho** [comment]
@mhegazy Fantastic work and turnaround guys! Just installed 1.5.4 **successfully** and can confirm that **relative output paths with compile-on-save are now indeed working correctly**. Also did a standard rebuild and the relative path continues to work as expected in that scenario. 

Thanks again! I'll continue down my path of promoting the virtues of TypeScript!

**Comment by Gitgiddy** [comment]
:+1: Yes, it works now.  Thanks so much for getting this fix out.

Are there release notes for it?  I can't find any documentation on it whether it had anything else in there.

Thanks!

**Comment by s093294** [comment]
Sorry for bumping this again. I am on latest version of VS2015 with latest (1.6.3) of typescript for visual studio and used the latest asp net 5 empty project. I added a tsconfig.json file but I cannot get visual studio to compile my typescript files on save. Everything works when doing a build.

**Comment by kamranayub** [comment]
It is working for me with latest version. In project properties make sure Compile on Save is checked--can't vouch for ASP.NET 5, only MVC 5.

**Comment by Sharpiro** [comment]
@s093294 Try this:

In VS 2015 go to : Tools > Options> Text Editor > TypeScript > Project 

Under "Compile on Save"
Check the box: "Automatically compile Typescript files which are not part of a project"

I've found this is necessary for vnext projects using .tsconfig
