### ISSUE TITLE
Compile-time checking of string literal arguments based on type

### ISSUE THREAD

**Issue by jbrantly** [Microsoft/TypeScript#394]
Often a method will take as a string the name of a property of some object that it's working on. A common example would be http://backbonejs.org/#Model-get

It would be ideal if TypeScript could provide compile-time checking on these calls to make sure that the string is actually a valid property of the underlying model. As a possible proposal:

```
interface Person {
	firstName: string
	lastName: string
	phoneNumber: string
}

function get(property: memberof Person) {}

get('firstName') // compiles
get('middleName') // would not compile
```

In the context of the get function, "memberof Person" would be equivalent to "string".

**Comment by ghalle** [comment]
I am currently using [Baobab](https://github.com/Yomguithereal/baobab) for a project, it is an immutable data tree / cursor library. When using it I have to use something like this (non-working simplified example):
```typescript
type Foo = {
   a: number;
};
get<T>(property: string): T;

// elsewhere
get<number>('a');
```

This for one does not check that the property actually exist and also forces me to cast the `get` to the correct type every time, which can lead to error for example if I change `a` in `Foo` to `string` my `get` will still be casting it to `number`.

This suggestion would therefore be really useful to help keep my code as type checked as possible.

###### I like this proposal from @jbrantly:
```
get(property: memberof T is A): A;
set(property: memberof T is A, value: A);
```

###### My proposal would be something like this:
```
get(property: A memberof T): A;
set(property: A memberof T, value: A);
```
The righthand would need to be an object type ({...}, interface, Class) or it would throw an error.
The lefthand side would be optional and only used if you need a reference to the type.

If you try to pass something that doesn't resolve to a constant string to a memberof type it would throw an error.

###### Or a way to reference a subtype using the parameter name:
```
get(property: memberof T): T[property];
set(property: memberof T, value: T[property]);
```

**Comment by mhegazy** [comment]
the proposal in #1295 should cover the scenarios outlined in this issue.

**Comment by Dominator008** [comment]
Looks like this is largely solved by string literal types: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-literal-types ?

**Comment by SaschaNaz** [comment]
Not really, but I think at least it is a prerequisite to solve this issue. #10425 will do.
