### ISSUE TITLE
Typing files exports

### ISSUE THREAD

**Issue by billouboq** [microsoft/TypeScript#39406]
## Search Terms

Typing, files, exports, default

## Suggestion

Create an annotation that can allow file exports typing.
See the exemple for a better explanation of the needs.

## Use Cases

Sometimes we want to create files that need to export specific things and those things MUST always be the same accross multiple files.

## Examples

You want to create name-of-file.widget.ts files. All those widgets files needs to export 2 things, first a function which must return a boolean and the default export must be the widget itself.

To be extra carefull you want to ensure those files always have those exports.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
It sounds like you want #420. If not, I can't tell what you mean from this.

**Comment by billouboq** [comment]
@RyanCavanaugh yeah exactly thanks !
