### ISSUE TITLE
Decorators on enum

### ISSUE THREAD

**Issue by aureole82** [microsoft/TypeScript#39407]
I simply want this:
```ts
enum Country {
    // ...
    Uganda = 800,
    Ukraine = 804,
    @DisplayName("United States (Minor Outlying Islands)") UnitedStatesMinorOutlyingIslands = 581,
    @DisplayName("United States of America") UnitedStatesofAmerica = 840,
    Uruguay = 858
    // ...
}
```

So, I can auto populate a `<select>` list with the display names:
![image](https://user-images.githubusercontent.com/4819891/86483365-3ad28880-bd54-11ea-86c9-92c3ba5235b7.png)

Same issue posted here: https://stackoverflow.com/questions/52197931/how-to-use-decorators-on-enum-in-typescript

**Comment by RyanCavanaugh** [comment]
Duplicate #3279; please search before logging new issues and respect the template
