### ISSUE TITLE
tsconfig not working in Visual studio 2015 RTM njsproj 

### ISSUE THREAD

**Issue by afaayerhan** [Microsoft/TypeScript#3941]
just got VS 2015 RTM now but the tsconfig is not working. and when you change module system it just does not work. it defaults to commonjs. and if you remove TypeScriptModuleKind it cannot compile without --module flag

**Comment by billti** [comment]
I see you logged this on the Node Tools side also ( https://github.com/Microsoft/nodejstools/issues/302 ). We'll address it there and track it with that issue. Thanks!
