### ISSUE TITLE
Constructor assignment and import conflict

### ISSUE THREAD

**Issue by nguyenxndaidev** [microsoft/TypeScript#39413]
**TypeScript Version:**  3.9.2

**Code**
```ts
import {v4 as uuid} from 'uuid';

const abc = '';

class Task {
  // OK
  constructor(public id = uuid(), public abc = 'a') {}

  // Cannot use uuid, which is used when import library, as field name in constructor => BUG?
  //constructor(public uuid = uuid()) {}
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Stackblitz Link:** [Provided](https://stackblitz.com/edit/typescript-h8f8jx)

**Comment by MartinJohns** [comment]
constructor(public uuid = uuid()) {}

When you write it like this, then the identifier `uuid` in your function call (`uuid()`) refers to the argument `uuid`, not to the imported function. This is correctly and matches how JavaScript works.

See the JS and the logs (when you hit run) on the playground: [Playground Link](https://www.staging-typescript.org/play?#code/JYWwDg9gTgLgBAbwG4BY4EMDOcCuPgAmAvnAGZQQhwDkeh1A3AFBMDGANltgCpYDWiJnDgB6EXACiUClDgBeAHxwA6gAsAngH4hcVhAB2mGFBysY0ABRgcAI3bBWufAXlPCFgJQfERJr7YGmBDsAKYAdOwQAOYW+iEA7nC8mHyeHsxAA)

**Comment by nguyenxndaidev** [comment]
Thanks for your explanation!
