### ISSUE TITLE
Refacoring "Convert named export to default" removes function typeings

### ISSUE THREAD

**Issue by essenmitsosse** [microsoft/TypeScript#39410]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.0-dev.20200702

**Search Terms**
- refactor / refactoring

---

- VSCode Version: 1.46.1
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. Have a file with a named export, that is typed like this:

```typescript
export const getFoo: (input: number) => number = (input) => input;
```

2. Click "Convert named export to default" in the refactoring menu

3. The refactored code new lacks the typing

```typescript
export default (input) => input;
```

I would expect the refactoring to maintain the functions typing. For example like this:

```typescript
const getFoo: (input: number) => number = (input) => input;
export default getFoo;
```

After all, the intend of the refactoring is to change the type of the export, not the way the code is written. I mainly use this refactoring, to automatically change the imports in other files. So for me, just removing the `export` before `const` and add a new line with `export default getFoo` would be sufficient for this refactoring.

Does this issue occur when all extensions are disabled?: Yes

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Are there any reasons to use only `initializer` instead of export a variable? 
https://github.com/microsoft/TypeScript/blob/2fe2f88047e6c1465744cf869b53810ee8d0edfc/src/services/refactors/convertExport.ts#L112-L118
