### ISSUE TITLE
Upgrade XML Parser

### ISSUE THREAD

**Issue by amitguptagwl** [microsoft/TypeScript#39424]
## Search Terms
xml parser

## Suggestion

Upgrading XML Parser for better performance

## Use Cases

As we're currently using xml2js, I wanted to request upgrading to [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser) due to performance; We've already moved from xml2js to FXP in other Microsoft projects.

file size | fxp 3.0 validator (rps) | fxp 3.0 parser (rps) | xml2js 0.4.19 (rps)
-- | -- | -- | --
1.5k | 16581.06758 | 14032.09323 | 4615.930805
1.5m | 14918.47793 | 13.23366098 | 5.90682005
13m | 1.834479235 | 1.135582008 | -1
1.3k with CDATA | 30583.35319 | 43160.52342 | 8398.556349
1.3m with CDATA | 27.29266471 | 52.68877009 | 7.966000795
1.6k with cdata,prolog,doctype | 27690.26082 | 41433.98547 | 7872.399268
98m | 0.08473858148 | 0.2600104004 | -1

-1 indicates the error.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We only use xml2js in a build script that is not at all performance-sensitive, so taking the risk that fxp may or may not have the same behavior is not something we're interested in.

Going around to various repos to request them to use a library you work on, without doing any due diligence into how those projects use xml2js, is inappropriate behavior.

![image](https://user-images.githubusercontent.com/6685088/86806638-e833ed80-c02d-11ea-8dae-889244a1bddb.png)
