### ISSUE TITLE
High CPU usage of Intellij TypeScript language service since 3.9.6

### ISSUE THREAD

**Issue by dyatko** [microsoft/TypeScript#39428]
**TypeScript Version:**  3.9.6, 4.0.0-dev.20200705

**Search Terms:** webstorm, intellij, typescript language service

**Expected behavior:**

Seemless TypeScript experience as it was for 3.9.5 and below

**Actual behavior:**

Any TypeScript project starts TypeScript language service which takes 100% CPU.

**Playground Link:**

https://www.jetbrains.com/webstorm/nextversion/

**Related Issues:**
https://youtrack.jetbrains.com/issue/WEB-46345

**Comment by mathiasvbg2019** [comment]
Yo

**Comment by mathiasvbg2019** [comment]
Yes

**Comment by montogeek** [comment]
It would be good to have a GitHub release for it too, and also a tag in the repo, there is not info at all about 3.9.6 changes.

**Comment by dyatko** [comment]
Yeah, I was looking for some details about this release but nothing there
https://github.com/microsoft/TypeScript/releases
https://github.com/microsoft/TypeScript/tags

**Comment by DanielRosenwasser** [comment]
Can you all confirm you're not having the same issues on 3.9.5?

Also, any details about the types of projects that you're running would be helpful.

For anyone working on the bug, check out https://github.com/microsoft/TypeScript/commits/release-3.9

**Comment by dyatko** [comment]
@DanielRosenwasser yes, I do confirm

**Comment by dyatko** [comment]
@DanielRosenwasser the projects are React/Material UI frontend app and NestJS backend app.

**Comment by amcasey** [comment]
https://github.com/mui-org/material-ui/blob/next/docs/tsconfig.json is our usual benchmark for this scenario and it doesn't show a  (tsc) regression between 3.9.5 and 3.9.6, so I guess we need a new test.  Any chance anyone can share their project?

I'll try again with tsserver, in case it's somehow specific to the language service.

p.s. Notes have now been posted: https://github.com/microsoft/TypeScript/releases/tag/v3.9.6

**Comment by amcasey** [comment]
I've packed up a couple of builds that separately revert the two interesting changes in 3.9.6:

Revert of 986e9dd:

[Grab the tgz](https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/79057/artifacts?artifactName=tgz&fileId=8070EBDEC994D6ADDA19D890BCF6E0FE3D67A857CFC7E8A32BCD6B2114FB94FF02&fileName=/typescript-3.9.6-insiders.20200707.tgz) or 
```
{
    "devDependencies": {
        "typescript": "https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/79057/artifacts?artifactName=tgz&fileId=8070EBDEC994D6ADDA19D890BCF6E0FE3D67A857CFC7E8A32BCD6B2114FB94FF02&fileName=/typescript-3.9.6-insiders.20200707.tgz"
    }
}
```

Revert of 9ec5fc5:

[Grab the tgz](https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/79076/artifacts?artifactName=tgz&fileId=40553BACC4F0B423702F0FD2F35A644DB83F72FA4FE18EDEE47FC27DA08762D702&fileName=/typescript-3.9.6-insiders.20200707.tgz) or
```
{
    "devDependencies": {
        "typescript": "https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/79076/artifacts?artifactName=tgz&fileId=40553BACC4F0B423702F0FD2F35A644DB83F72FA4FE18EDEE47FC27DA08762D702&fileName=/typescript-3.9.6-insiders.20200707.tgz"
    }
}
```

**Comment by dyatko** [comment]
@amcasey Thanks for the builds!

I've tried both of them on both projects and they behave normal, no crazy spikes in CPU usage. Moreover, I've installed 3.9.6 again and cannot reproduce the issue anymore. Maybe it's something to do with some caches, very strange, I was struggling with this CPU usage for a week.

Anyway, I'm closing the issue, but thanks for tagging the release!

**Comment by amcasey** [comment]
Glad things worked out.  Thanks, @dyatko!
