### ISSUE TITLE
TypeScript package is transpiled to ES5 on npm

### ISSUE THREAD

**Issue by proteriax** [microsoft/TypeScript#39420]
## Search Terms
npm, compiler

## Suggestion
Is there any reason the TypeScript package itself is transpiled down to ES5 on npm? The last version of Node.js without ES2015 support was released five years ago. Right now the `typescript` package is sitting at around 50MB on npm. I imagine that switching to an ES2015 build or above would also slightly improve the performance.

**Comment by RyanCavanaugh** [comment]
The TS package gets rolled in to other environments like the Visual Studio Online editor that functions in older runtimes. People are also running TS in some strange-ish environments where ES2015 isn't available.

We've tested these things and in general perf/size wins from not downleveling are either very small or even negative; there's not really any downside to targeting older runtimes.

**Comment by proteriax** [comment]
@RyanCavanaugh Thanks for the answer!
