### ISSUE TITLE
VS2015 RTM: "Failed to save file" error

### ISSUE THREAD

**Issue by chinhodado** [Microsoft/TypeScript#3943]
I just downloaded VS2015 RTM and opened a project that I've been working on in VS2013.

When I save a file, all I see is an error:

    Failed to save file 'compiled.js'.

where `compiled.js` is the `--out` argument, as indicated in the project setting ("Combine JavaScript output into file").

There is no error or warning shown in the Error List window.

This seems to be similar to #3939, except that no redirect option is specified.

**Comment by mhegazy** [comment]
indeed duplicate of #3939.
