### ISSUE TITLE
Property 'entries' does not exist on type 'ObjectConstructor'

### ISSUE THREAD

**Issue by praveeno** [microsoft/TypeScript#39437]
**TypeScript Version:**  4.0.0-beta

**Search Terms:**

**Expected behavior:**
Object.entries should work as expected
**Actual behavior:**
not finding entries function

**Related Issues:**

**Code**
```ts
enum A {
    X = 1
}

Object.entries({}) 
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var A;
(function (A) {
    A[A["X"] = 1] = "X";
})(A || (A = {}));
Object.entries({});

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/KYOwrgtgBAglDeAoKKoA0oF4oEZEF9FEB5AIwCtgBjAFwDpQaAnAS2AGcAKUAEwAcA9ixA12ASihA)

**Comment by MartinJohns** [comment]
Works correctly if you add the `es2017.object` library.

```
// or via tsconfig.json -> compilerOptions -> lib
/// <reference lib="es2017.object" />
enum A { X = 1 }
Object.entries(A);
```

[Playground Link](https://www.typescriptlang.org/play/?ts=4.0.0-beta#code/PTAEHsCdQNwSwIagC4GcDG4B2AzOBzAOgCtVtQBaAPlEwFsAHOAGwFNIB5B5ObVSmszgAjAFAgwAHkisc7VlnStQQ4QF4ARK1QAmAAwBGAOyFww4q3TINoYFVEKArnVABBUAG9QADVBrQBqAAvqIc5pbIhArIkHDaABSuAJQA3EA)
