### ISSUE TITLE
auto-complete not work but type check still working

### ISSUE THREAD

**Issue by xuzhanhh** [microsoft/TypeScript#39435]
**TypeScript Version:**  3.9.2

**Search Terms:** auto-complete

**Code**

```ts
const func = <T>(data: T): { return: { data1: T, }, config: { func: string } } => {
    return null as any
}

const func2 = <T>(data: T): { return: { data2: T }, config: { func2: string } } => {
    return null as any
}

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never;


const test = <T extends { data: number }, P extends any[]>(config: UnionToIntersection<P[number]['config']>, plugins: { [K in keyof P]: (data: T) => P[K] }): UnionToIntersection<P[number]['return']> => {
    return null as any
}


// type check is correct, it must send func2 into config
const b2 = test({ func: '1', }, [func, func2])

// but auto complete isn't work. nothing show up when I click f fu fun...
```

**Expected behavior:** auto-complete should show up when I click f, fu, fun, func in "config" params

**Actual behavior:** auto-complete not showing up

**Playground Link:**  https://www.typescriptlang.org/play?jsx=0&ts=3.9.2#code/MYewdgzgLgBAZgVzMGBeGAeAKgPgBQAmAhlEQFwxYCUFA3jAE4CmUCDYdMxpAjBVgBoYAXyGgwcAJYBzTomQVoDSWGkj1qHDFoAoGPsYs2YGGAQAbczCIRrYAJ47hOneOjwkwAExpMuQiTklDTahqzsnNxEXvwiYuBSsqHy3opQyqrqwmhaugZhxqYWVjZ2js46UPYADkwwAKpgkuBYIACSYFBMDBBMwFDNYBj1Wuh49TBMAB5dYAS2RA4wAPwweADWFPVUOTAAbiCSBDAUYEx73TvTs-NrGxQqcN0wbTua+4cEO6ttJ6bn3QA3C5XOB3F13OhsJMZkw5rZ6FFTggALYAI2eohgAAUYTcFg4ANoAXXw4kSWyaLXanW6vX6gww2MJZnR3WJhIA5OSZJzSUJquYENIVBBOISANIwFQwdZMewgOA44kUAKkfhvLTMiXEkQhRqDVodLo9PoDcBMlmojEMDmc5jhMB80a5PQGB2FMyWawE8oggD0-pgVVqMGAAAs+utpbZQAxmP0hJJYCiEO5enMPMgfCooCAwwkZKDILA0T50BCoHh6CkKJyeJyhFjCSkhCkvMSqC5AzA0QhYER+-nQCjBSw6pIIE7YAB3EAMdYAOlMICg4ZUagg4ZAM5gCGqMBnkZMv2A5kkwGjSsQWcXd6AA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
I think this is a limitation in balancing how much inference we do for completions along with how much we peek at the constraints. @andrewbranch knows more.

By the way, there's no need for that `T` type parameter.

https://www.typescriptlang.org/play/?ts=3.9.2&ssl=1&ssc=1&pln=20&pc=74#code/MYewdgzgLgBAZgVzMGBeGAeAKgPgBQAmAhlEQFwxYCUFA3jAE4CmUCDYdMxpAjBVgBoYAXyGgwcAJYBzTomQVoDSWGkj1qHDFoAoGPsYs2YGGAQAbczCIRrYAJ47hOneOjwkwAExpMuQiTklDTahqzsnNxEXvwiYuBSsqHy3opQyqrqwmhaugZhxqYWVjZ2js46UPYADkwwAKpgkuBYIACSYFBMDBBMwFDNYBj1Wuh49TBMAB5dYAS2RA4wAPwweADWFPVUOTAAbiCSBDAUYEx73TvTs-NrGxQqcN0wbTua+4cEO6ttJ6bn3QA3C5XOB3F13OgMAAFSYzJhzBYOADaAF18OJElsmi12p1ur1+oMYcizABbABG3VRyIA5JiZLT0UJquYENIVBBOMiANIwFQwdZMewgOAwaGoigBUiRQKnBCU57CN5aaG81EiEKNQatDpdHp9AbgEnkqkMGm05jhMBM0a5PQGK2FMyWaxI8oggD0npgVVqMGAAAs+ut+bZQAxmP0hJJYGSEO5enMPMgfCooCAAwkZKDILAKT50BCoHh6CkKLSeLShJ6AFQAElrPtEMGRKSEKS8qKoLm9MApCFgREHmdAZNZLDqkggNtgAHcQAx1gA6UwgKCBlRqCCBkBzmAIaowOfBky-YDmSTAUNixAp5cPoA

**Comment by andrewbranch** [comment]
I’m not sure what’s going on here off the top of my head, but it seems a bit suspicious that quick info is showing `P` instantiated to `any[]` when the type error clearly indicates that `P` has been correctly instantiated to the tuple `[typeof func, typeof func2]`.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/3277153/86843295-390e0b00-c05b-11ea-8e65-9f9834bb2fb5.png">

This is definitely reminiscent of some very difficult problems we’ve had in the past with object literal completions at inference-affecting positions (and this could be a side effect of the fix), but I would hope this is fixable.

**Comment by xuzhanhh** [comment]
> I’m not sure what’s going on here off the top of my head, but it seems a bit suspicious that quick info is showing `P` instantiated to `any[]` when the type error clearly indicates that `P` has been correctly instantiated to the tuple `[typeof func, typeof func2]`.
> 
> <img alt="image" width="518" src="https://user-images.githubusercontent.com/3277153/86843295-390e0b00-c05b-11ea-8e65-9f9834bb2fb5.png">
> 
> This is definitely reminiscent of some very difficult problems we’ve had in the past with object literal completions at inference-affecting positions (and this could be a side effect of the fix), but I would hope this is fixable.

But when you complete the `config` params.  The quick info of `P` become showing 
```
({
    return: {
        data1: {
            data: number;
        };
    };
    config: {
        func: string;
    };
} | {
    return: {
        data2: {
            data: number;
        };
    };
    config: {
        func2: string;
    };
})[]
```
🧐🧐

**Comment by Andarist** [comment]
This works as expected since 4.2.x, the issue can be closed.
