### ISSUE TITLE
Missing 3.9.6 version Git tag

### ISSUE THREAD

**Issue by davidlj95** [microsoft/TypeScript#39444]
Version `3.9.6` has been released, but the tag is not in Git:

https://github.com/microsoft/TypeScript/tree/v3.9.6

Detected by @irstavr

**Comment by DanielRosenwasser** [comment]
Sorry about that, I just fixed it!

https://github.com/microsoft/TypeScript/releases/tag/v3.9.6

**Comment by papb** [comment]
The link for [fixed issues in v3.9.6](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A%22TypeScript+3.9.6%22+is%3Aclosed+) in the [3.9.6 release](https://github.com/microsoft/TypeScript/releases/tag/v3.9.6) does not show any issues...

**Comment by DanielRosenwasser** [comment]
The "June Servicing Release" milestone needed to be renamed.
