### ISSUE TITLE
after x[ii] && ..., it should be clear that x[ii] is not falsy

### ISSUE THREAD

**Issue by d1manson** [microsoft/TypeScript#39445]
## Search Terms
* `array short circuit`
* `falsy array`

## Use Cases & Example

If you have an array with falsy holes, it's handy to be able to do short-circuit checks like this...

```
const x = ["hi", null, false]; 
for (let ii = 0; ii < x.length; ii++) {
  console.log(x[ii] && x[ii].toUpperCase()); 
}
```

But currently TS complains that after the check that `x[ii]` could still be falsy, which it can't.
If your array is `(string | null | undefined)[]` you can use `x[ii]?.toUpperCase()`. However if you have other falsy values it would be nice if it could be made to work with the short-circuit operator. I note that if you do `x_ii = x[ii];` and then `x_ii && x_ii.toUppserCase()` it's ok, but that can sometimes be unnecessarily verbose.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplicate #10530 (somewhat). Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by RyanCavanaugh** [comment]
Arguments about whether `ii` is actually the same between two references aside (this is *much* more subtle than you'd think), we haven't found a way to track this that isn't terrible for performance.

**Comment by fogfish** [comment]
You can solve it with functional decomposition

```ts
const list = ["hi", null, false]

const isString = (x: any): x is string => typeof x === "string"

const seq = list.filter(isString).map(x => x.toUpperCase()) 
```
