### ISSUE TITLE
No auto implementation refactorings for abstract class with method with explicit this parameter.

### ISSUE THREAD

**Issue by SirJosh3917** [microsoft/TypeScript#39440]
**TypeScript Version:**  4.0.0-dev.20200706

**Search Terms:** refactoring, abstract class, this, suggestions, intellisense, 

**Code**
```ts
abstract class Thing {
  abstract run(): void;
}

class ThingImpl extends Thing {
}

abstract class ThingWithThis {
  abstract run(this: ThingWithThis): void;
}

class ThingWithThisImpl extends ThingWithThis {
}
```

**Expected behavior:**
Refactorings to auto implement ThingWithThisImpl as such:
```ts
abstract class Thing {
  abstract run(): void;
}

class ThingImpl extends Thing {
  run(): void {
    throw new Error("Method not implemented.");
  }
}

abstract class ThingWithThis {
  abstract run(this: ThingWithThis): void;
}

class ThingWithThisImpl extends ThingWithThis {
  run(this: ThingWithThis): void {
    throw new Error("Method not implemented.");
  }
}
```

**Actual behavior:**
Implementing the abstract class is not suggested for ThingWithThis.

![image](https://user-images.githubusercontent.com/9854865/86595628-008d0500-bf67-11ea-9fbf-6af978b9bbe3.png)
![image](https://user-images.githubusercontent.com/9854865/86595646-0682e600-bf67-11ea-8677-fd3c139c3358.png)

Github doesn't support mp4s, so attached is a zip containing an mp4 of the problem if necessary.
[problem.zip](https://github.com/microsoft/TypeScript/files/4879016/problem.zip)

**Playground Link:** [Playground Link]([Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200703#code/IYIwzgLgTsDGEAJYBthjAgKgCwJYDsBzBAbwCgEFRIZ4EoBXfACgEoAuBANwHtcATANxkAvmTIo0GHAUIBJALYAHZAgCmADwhr8-aXiKlR46tDiJJ6LAcIB1XBGwyM5SqdqJGLR7jCcZRPaOzhzcfELGEqhWAXYOTnhgiirqWjp61rJBCb5GIkA))

**Related Issues:** N/A?

**Comment by DanielRosenwasser** [comment]
Thanks to both @andrewbranch who fixed this without necessarily knowing it, and @a-tarasyuk for the test (and the other fix)!
