### ISSUE TITLE
Implement interface adds an extra `| undefined` to parameter

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#39458]
**TypeScript Version:**  4.0.0-dev20200702

**Search Terms:**
- quick fix
- implement interface

**Code**
With strict mode enabled. For the TypeScript:

```ts
interface IFoo {
    bar(x?: number | string): void;
}

class Foo implements IFoo {
}
```

Run `implement interface` on `Foo`

**Expected behavior:**
`bar` is marked with a `?`:

```ts
class Foo implements IFoo {
    bar(x?: string | number): void {
        throw new Error('Method not implemented.');
    }
}
```

**Actual behavior:**
`bar` is marked with both `?` and its type also now has  `| undefined`

```ts
class Foo implements IFoo {
    bar(x?: string | number | undefined): void {
        throw new Error('Method not implemented.');
    }
}
```

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Pretty sure we have logic in the type printer to automatically display these, but check with @weswigham on the matter.
