### ISSUE TITLE
TS 4.0: jsxFragmentFactory ignored in Preact + TypeScript setup

### ISSUE THREAD

**Issue by ddprrt** [microsoft/TypeScript#39451]
I'm using the new `jsxFragmentFactory` to make `Fragment` work in a Preact setup, but TypeScript won't recognize it.

**TypeScript Versions:**  4.0.0-beta, 4.0.0-dev.20200706

**Search Terms:** JSX Fragment Factory, Preact

**Code**

*Counter.tsx*

```ts
import { Fragment, h } from "preact"

import { useState } from "preact/hooks"

type CounterProps = {
  count?: number
}

export function Counter({count = 0}: CounterProps) {
  const [cnt, setCnt] = useState(count)
  return <>
    <p>{cnt}</p>
    <button onClick={() => setCnt((prev) => prev + 1)} type="button">Update</button>
  </>
}
```

*tsconfig.json*

```ts
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["DOM", "DOM.Iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "noUnusedLocals": true
  },
  "include": ["src"]
}
```

See also:

<img width="1658" alt="Screenshot 2020-07-06 at 12 55 33" src="https://user-images.githubusercontent.com/1374451/86624311-63ac8500-bfc3-11ea-9e99-518ca2edbb7f.png">

**Expected behavior:** TypeScript recognizes that I use `<>...</>` as a shorthand for the imported `Fragment` 

**Actual behavior:**
With `"noUnusedLocals"` set to true, TypeScript throws `error TS6133: 'Fragment' is declared but its value is never read.` 

**Playground Link:** No playground, but a GitHub repo (https://github.com/ddprrt/preact-vite-ts-playground) -- this is a Vite setup that compiles, but I think this can be ignored for this issue. Editor feedback and running `tsc` show the actual behavior.

Hope this helps!

**Comment by DanielRosenwasser** [comment]
Should be quick to fix.
