### ISSUE TITLE
Call hierarchy: missing outgoing calls inside function expression

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#39453]
**TypeScript Version:**  3.9.2

**Search Terms:**

**Code**

```ts
const c = function () {
    return {};
};
const b = function () {
    return c();
};
const a = function () {
    return b();
};
a();
```

Place cursor on `a` (in `const a`) and then run "peek call hierarchy" (configured to show outgoing calls).

**Expected behavior:**

Call to `b` should be shown.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/921609/86629267-0fa1a080-bfc3-11ea-91b8-f893958cf98f.png)

**Playground Link:** 

**Related Issues:** 

If we use function declarations instead of function expressions, this works as expected.

![image](https://user-images.githubusercontent.com/921609/86629506-732bce00-bfc3-11ea-815a-e688222f8d77.png)

**Comment by DanielRosenwasser** [comment]
We need some sort of special-casing, at least for `const`s immediately initialized with `functions`, and potentially also `let`s and `var`s. Work with @rbuckton and @sandersn to see other parts of the compiler/LS where we do similar logic.
