### ISSUE TITLE
Not tell when code never be executed

### ISSUE THREAD

**Issue by kitsoRik** [microsoft/TypeScript#39462]
I have [example code](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=18&pc=2#code/C4TwDgpgBAsiAq5oF4oHIDOwBOBLAdgOZpQA+6+ArgLYBGE2J5atA9qwDYQCG+aA3AChBBYAwBm3AMbQ4AeVoArCFOBQA3oKjaooSAC5YCJEJ1QAbtw6UIh3iCEBfYVNb4sUVkpXBD876pkRoiQUKiaZnq2UABEbJw8+DEANFo6ltbRAIwATADMgo5CghgA7rjAUgAWUAAUUazingFqyG3oXsqqJAD8zV3AAHRRUIYNTZ0+AJQaadpS3BjQaJPdhrTYPADW-FAA9Hu6VbgYUKXcIFD4EOYMUPRQEAAeKpRiACZzUAtL6PFcvDQ+i+P2WVDoDCBIMW0BiWDwRBi6023B2+0OVg4RxOZwu31492gz1eH0KQA). This code have bug. In switch part, 'case' never can be 'object', but typescript not tell me about that, and suggest 'object' in intellisense.

[Code](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=18&pc=2#code/C4TwDgpgBAsiAq5oF4oHIDOwBOBLAdgOZpQA+6+ArgLYBGE2J5atA9qwDYQCG+aA3AChBBYAwBm3AMbQ4AeVoArCFOBQA3oKjaooSAC5YCJEJ1QAbtw6UIh3iCEBfYVNb4sUVkpXBD876pkRoiQUKiaZnq2UABEbJw8+DEANFo6ltbRAIwATADMgo5CghgA7rjAUgAWUAAUUazingFqyG3oXsqqJAD8zV3AAHRRUIYNTZ0+AJQaadpS3BjQaJPdhrTYPADW-FAA9Hu6VbgYUKXcIFD4EOYMUPRQEAAeKpRiACZzUAtL6PFcvDQ+i+P2WVDoDCBIMW0BiWDwRBi6023B2+0OVg4RxOZwu31492gz1eH0KQA) to reproduce.
**TypeScript Version:**  3.7.5

 
**Code**

```ts
type MyType = 'string' | 'number' | 'boolean';

interface MyObject {
    type: MyType;
    value: any;
}

const object: MyObject | MyType = {
    type: "boolean",
    value: 123
};

switch (typeof object === 'object' ? object.type : typeof object) {
    case 'object': break; // this way never be executed
    case 'boolean':
    case 'number':
    case "string": break; // all this way can be executed
}
```

**Expected behavior:**
Gets error in 'object' case.

**Actual behavior:**
Doesn't gets error in 'object' case.

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=18&pc=2#code/C4TwDgpgBAsiAq5oF4oHIDOwBOBLAdgOZpQA+6+ArgLYBGE2J5atA9qwDYQCG+aA3AChBBYAwBm3AMbQ4AeVoArCFOBQA3oKjaooSAC5YCJEJ1QAbtw6UIh3iCEBfYVNb4sUVkpXBD876pkRoiQUKiaZnq2UABEbJw8+DEANFo6ltbRAIwATADMgo5CghgA7rjAUgAWUAAUUazingFqyG3oXsqqJAD8zV3AAHRRUIYNTZ0+AJQaadpS3BjQaJPdhrTYPADW-FAA9Hu6VbgYUKXcIFD4EOYMUPRQEAAeKpRiACZzUAtL6PFcvDQ+i+P2WVDoDCBIMW0BiWDwRBi6023B2+0OVg4RxOZwu31492gz1eH0KQA)

P.S. I think, 'cause  in js object can be any type.

**Comment by RyanCavanaugh** [comment]
The root cause here is that `typeof object` returns the full union of `typeof` results; we had previously discussed changing `typeof e` to return a narrower union based on `e`, but this raises problems because people sometimes want to do defensive runtime checks like `if (typeof mightBeDefined !== "undefined")` and we'd cause that code to error if `mightBeDefined` was (reasonably) defined as not including `undefined`
