### ISSUE TITLE
Strange array + push inference behavior with spread operator

### ISSUE THREAD

**Issue by CapsAdmin** [microsoft/TypeScript#39470]
**TypeScript Version:**  3.7.x-dev.201xxxxx

array with push inference failing

**Code**

```ts
const Foo = (arg: { val: number }[]) => {
	return { val: 1 }
}

let arr = []

arr.push({
	bar: 1, // ERROR: argument of type X is not assignable to parameter of type Y, etc. 
	...Foo([]),
})

Foo(arr) // comment out this and uncomment below

// this circumvents the error
// let lol = arr; Foo(lol)
```

**Expected behavior:**
Typescript should be able to guess the array type when spreading out {val: 1} to be `{bar: number, val: number}[]`.  

**Actual behavior:**
It errors with a confusing error. It's circumventable by doing `let lol = arr; Foo(lol)`

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/index.html?ts=4.0.0-beta#code/MYewdgzgLgBAYiEMC8MAUBDATgcwFwwDeMAbhgDYFgCuAtgEYCmWMAvgNoC6AlCgHxEAsACgAkFkZRqWMEVIUCARjYjWIkeUkxsLVF3XCdAOgAO1CAAs0hEaPrYlAGhgB6FzACiAJS8B5LwTYOHSMYLAgAGYwUACeJowwABowAJYQMGAgsBgQECk4YBj0mtFIJtgYtJLMMJHRcQkAms6SwEYwtkZdCCBoXNyOqtwGPZhYWLxuMKC0VWG11LBQFmnaYAAmMNRgM3OwTOQgAO4GU8urwClYwHQkoVDpywnMWCBYIlOasIfkKNrjAG54Ig0D9uEA)

**Related Issues:** 
Not really sure what to search for.

**Comment by DanielRosenwasser** [comment]
This is pretty bizarre though - not sure if it's of interest to you @ahejlsberg.

**Comment by ahejlsberg** [comment]
Looks like we're not removing freshness from the control flow type we compute for the array.
