### ISSUE TITLE
[feature request] make it possible to /// reference node modules that carry their own types the same as node modules with @types/

### ISSUE THREAD

**Issue by dgoldstein0** [microsoft/TypeScript#39484]
## Search Terms

/// triple slash reference node module node_modules

## Suggestion

Today, there's a nice `/// <reference types="foo" />` directive that works for including the types of `foo` found in any `typeRoots`, which defaults to `@types/` packages.  So this is the defacto way to include types for a node module into a declaration file.  However, if your desired module includes it's own types, instead of having a separate `@types/` package, this form of `/// <reference />` can't be used - adjusting the typeRoots in tsconfig.json to include `"./node_modules/"` causes problems because typescript then expects `@types` to be a module it can load the types for.  An instance in the wild where this matters is the `eventemitter3` library, which has an `EventEmitter` namespace that's usable from declaration files, if you can only figure out how to reference the types for it.  (Aside: the `/// <reference path=... />` form is only usable if you know where your node_modules folder is relative to your code, which feels like an implementation detail that should not be sneaking in to your sources).

Fundamentally what I want to see is that a declaration file author doesn't need to care whether each node module has it's own types or a separate `@types/` package.  For this, we need either (a) to modify the semantics of `/// <reference types=... />` or (b) create a new type of `/// <reference />`.  I am not sure the former would be backwards compatible, so I'm going to focus on the latter.

So in particular, I propose that we have a new type of /// reference that uses the standard module-resolution logic: `// <reference module="foo" />` will look up the types for module `foo`, and like other types of references, load all the resulting namespaces and other declarations into scope as types.

Most of the time I expect this will be paired with `moduleResolution: "node"`, in which case this will be able to find any module named `foo` - whether a module in the current project, node_modules/foo/index.d.ts, node_modules/@types/foo/index.d.ts, or, following package.json types/typings/typeVersions fields (as moduleResolution: node does) and find a declaration file which the package.json references.

## Use Cases

My main use case for this is so that I can teach my teammates to write `/// <reference module="react" />` or `/// <reference module="eventemitter3" />` and not have to worry whether each module carries it's own types or has a separate @types/ module.  Additionally, by reusing the module resolution algorithm, this proposal will keep us from having to learn yet another algorithm that typescript uses to resolve references.

## Examples

using eventemitter3@4.0.0

```// blah.d.ts
/// <reference module="eventemitter3" />
/// <reference module="react" />
// EventEmitter namespace should now be in scope from eventemitter3, as should JSX from the react type declarations

declare const emitter: EventEmitter.EventEmitter;
declare const fn: () => JSX.Element;
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
Tentatively marking this as a suggestion, but if `/// <reference types="foo" />` doesn't request a resolution on both `@types/foo` and `foo` in the worst-case, I want to say that that's a bug. Thoughts @RyanCavanaugh @rbuckton?

**Comment by dgoldstein0** [comment]
I believe /// <reference types=... />
searches the typeRoots only, which defaults to node_modules/@types.
Changing typeRoots to also include node_modules gives errors as typescript
then thinks the @types/ folder should itself be a package with types in it.

**Comment by dgoldstein0** [comment]
bump on this.

>  if /// <reference types="foo" /> doesn't request a resolution on both @types/foo and foo in the worst-case, I want to say that that's a bug

In case I wasn't clear: yes, this is definitely the bug.

**Comment by dgoldstein0** [comment]
@DanielRosenwasser bump on this.  This issue is still causing pain at Dropbox for our usage of eventemitter3.  any eta on a fix?

**Comment by DanielRosenwasser** [comment]
Hey @dgoldstein0 sorry about the...well delay is putting it lightly.

We just tried playing with this and haven't been able to reproduce the issue you're running into. Can you give an example repo?

One thing that has crossed my mind - what is your `moduleResolution` setting? If it's `classic`, I believe we won't try to automatically resolve to `node_modules`, but will auto-include `@types` packages because they reside in the default `typeRoots`. Running with `traceResolution` might help here a bit.

**Comment by dgoldstein0** [comment]
It's definitely moduleResolution: node.

I'll whip up something tonight or tomorrow.

**Comment by dgoldstein0** [comment]
so I've been unable to reproduce it thus far.  Which is rather confusing as I was convinced at the time that I had the problem explained right.  At the time I was likely using Typescript 3.8.3 and now I'm using 4.0.7 (I know, quite stale) so perhaps it was fixed in between there.  Part of me wants to get to the bottom of it... but I don't think it's worth the time.  Anyhow given it works I guess I don't need any fix.

If I do encounter it again, I'll try to get a better repro and reopen then
