### ISSUE TITLE
Current TypeScript Specification documents (.docx & .pdf) still point to 1.4 version

### ISSUE THREAD

**Issue by cyparu** [Microsoft/TypeScript#3948]
The current TypeScript Specification documents [.docx](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.docx) & [.pdf](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf) are obsolete, pointing to **v1.4** from October 2014.

**Comment by danquirk** [comment]
A large spec update is in progress, not sure of the exact ETA.

**Comment by ahejlsberg** [comment]
@danquirk This bug is about the links on http://typescriptlang.org not pointing to the latest released specs (which is 1.5 from February). We should fix that. Yes, we also need to update the spec itself, and that is work in progress (don't have an exact ETA).

**Comment by danquirk** [comment]
Sorry, you're right, Will get @jonathandturner on that.

**Comment by jamesxv7** [comment]
Being **TypeScript** an open source project, why the specification document can not be a living document that the community can contribute in the same way as it contributes to source code. I'm sure there are many excellent technical writers in the community with the desire to genuinely contribute in this project.

**Comment by jonathandturner** [comment]
@jamesxv7 there's also a markdown version of the spec.  Generally, though, specs are too difficult to write in something like markdown.  This is due in part to the need for rich support for change tracking in the editor.  TC39 experiences the same problem with the JavaScript spec, though there are a couple efforts to help with this.

BTW, the markdown version is here: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md

**Comment by jonathandturner** [comment]
I've bumped the version on the TS website

**Comment by jamesxv7** [comment]
Excellent, I really appreciate the feedback and thanks for the reference.

**Comment by cyparu** [comment]
Great to see it fixed so fast:zap:! Here are all the relevant specification docs:
- [TypeScript 1.5 Language Specification **(.pdf)**](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf)
- [TypeScript 1.5 Language Specification **(.docx)**](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.docx)
- [TypeScript 1.5 Language Specification **(.md)**](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md)
