### ISSUE TITLE
Within operator as typeguard for union types

### ISSUE THREAD

**Issue by jeswr** [microsoft/TypeScript#39492]
## Search Terms

Type Guard
Union
Array
includes
within

## Suggestion
To include a `within` operator to check if a variable is `within` a union type. 

### Example 1:

```TypeScript
type Vowels = 'a' | 'b' | 'c' | 'd' | 'e' 
```
```TypeScript
function isVowel(str: string) {
   return str within Vowels
}
```
this could be transpiled to 
```TypeScript
function isVowel(str: string) {
   return [ 'a', 'b', 'c', 'd', 'e' ].includes(str)
}
```

### Example 2:

```TypeScript
enum VehicleType {
   Car,
   Motorbike,
   Train,
   Plane
}

interface Car {
   vehicleType: VehicleType.Car,
   ...
}

interface Motorbike {
   vehicleType: VehicleType.Motorbike,
   ...
}

interface Train {
   vehicleType: VehicleType.Train,
   ...
}

interface Plane {
   vehicleType: VehicleType.Plane,
   ...
}

type Vehicle = Car | Motorbike | Plane | Train

type RoadVehicle = Car | Motorbike
```

```TypeScript
function isRoadVehicle(vehicle : Vehicle) {
   if (vehicle.vehicleType within RoadVehicle['vehicleType']) {
      return true
   } else {
     return false
   }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* (Would depend on elements of the union) This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* (Possibly against non-goal 5) This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We don't do features that don't meet the design guidelines, especially type-directed emit.
