### ISSUE TITLE
Cannot narrow down "[0, null] | [number, T]" with type guard

### ISSUE THREAD

**Issue by yshui** [microsoft/TypeScript#39496]
**TypeScript Version:**  3.9.6

**Search Terms:** sum types

**Code**

```ts
class T {
	asdf: string = ""
}

function works(a: [0, null] | [1, T]) {
	if (a[0] !== 0) {
		let x = a[1]
		console.log(x.asdf)
	}
}

function doesnt_work(a: [0, null] | [number, T]) {
	if (a[0] !== 0) {
		let x = a[1]
		console.log(x.asdf)
	}
}
```

**Expected behavior:**
Should compile. This is no way to pass `[x, null]` to `doesnt_work` if `x !== 0`, so if `a[0] !== 0`, then `a[1] !== null`

**Actual behavior:**
Fails to compile. Although the simpler case works

**Playground Link:** https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200708#code/MYGwhgzhAEAq0G8BQBISATAZgLmhALgE4CWAdgObQC80ARLUgL5JKYCupw+xA9qdAHcehANYQAFGFwBtAAwAaaKTYgQAXWgAfaNICMi2GoCUiVMUzRJcjQEIqNWSeQoUIAKb5oAD2rQwetVQUYD4IHncAOhAecnEvCIxMI1RmZlYOLl5+dB43CFJ8AH0hUUkZBSUVdS0dZQBbACM3QgNjUxRzS39ZW3toR3bXD29ff11AlxDSMMjo2PjE5JRUpCA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
`a: [number, T]` includes values like `[0, new T()]`, so there's no way to narrow it out with `a[0] ===0`.

Note that you *can* check for `null`.

```ts
class T {
	asdf: string = ""
}

function works(a: [0, null] | [1, T]) {
	if (a[0] !== 0) {
		let x = a[1]
		console.log(x.asdf)
	}
}

function doesnt_work(a: [0, null] | [number, T]) {
	if (a[1] !== null) {
		let x = a[1]
		console.log(x.asdf)
	}
}
```

**Comment by yshui** [comment]
> a: [number, T] includes values like [0, new T()]

You are right.

However, this only means you cannot go from `a[1] !== null` to `a[0] !== 0`. OTOH you can do from `a[0] !== 0` to `a[1] !== null`.
