### ISSUE TITLE
tsconfig.json is ignored by Visual Studio 2015 RTM

### ISSUE THREAD

**Issue by UTGuy** [Microsoft/TypeScript#3949]
VS2015 RC was (seemingly) using this configuration file... after updating to RTM this file simply being present actually causes Typescript to not compile on save anymore. We had to remove tsconfig.json to get this to work again. On top of that, there is no way to set configurations, other than editing the .xproj file and adding what is needed by looking at https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects.

**Comment by danquirk** [comment]
tagging @paulvanbrenk

**Comment by paulvanbrenk** [comment]
Yes, you need the tsconfig.json file to set the compiler options. We do expect the tsconfig.json file to be located in a "scripts" folder next to the "wwwroot" folder.

````
/project root
    /wwwroot
    /scripts
    -tsconfig.json
    -*.ts
````
Further you need to enable 'Compile on Save' for files that are not part of a project in tools\options.

![image](https://cloud.githubusercontent.com/assets/5273975/8809263/6effaa52-2f9c-11e5-8a7c-60693c072280.png)

**Comment by UTGuy** [comment]
I checked this morning... here is our project structure...

/project root
    /wwwroot
    /client
        /app
            - *.ts
            - tsconfig.json

I have the compile "Compile on save" option checked and this works.

I also tried putting a "scripts" folder next to the "wwwroot" folder as you suggested with the tsconfig.json file in it and that would not work unless the "Compile on save" option was checked.

**Comment by paulvanbrenk** [comment]
Compile on build expects the tsconfig.json to be located in the root of the scripts folder next to the wwwroot folder.

**Comment by UTGuy** [comment]
Ok I have figured this out finally....

With this config, compile on build will create an app.js in the /project root/wwwroot/lib folder, but this same config will produce a NEW wwwroot folder inside the scripts folder (WHAT?)...

```javascript
{
    "compilerOptions": {
        // other options here
        "target": "es5",
        "out": "wwwroot/lib/app.js"
    }
}
```

THIS config will work properly with compile-on-save, but puts a NEW wwwroot abover the project root (WHAT?)...

```javascript
{
    "compilerOptions": {
        // other options here
        "target": "es5",
        "out": "../wwwroot/lib/app.js"
    }
}
```

There is a discrepancy with the 2 different build types... is there a fix (or work-around) for this yet?

**Comment by paulvanbrenk** [comment]
Did you install TS 1.5.4 or are you still on the 1.5.3 which shipped with RTM?

**Comment by UTGuy** [comment]
1.5.4.0 (per the "TypeScript for Microsoft Visual Studio" extension)

**Comment by danquirk** [comment]
As noted here https://github.com/Microsoft/TypeScript/issues/4820#issuecomment-140873005 we should make sure whatever the default is the user understands what's happening if tsconfig or the project file is superceding the other.

**Comment by MrAndMrsK** [comment]
Just checking, this is the same issue that makes my ASP.NET 5 RC1 project with */tsconfig.json* including `"module": "es6"`and my */src/main.ts* of `export class whatever { }` actually "compile on build" just fine but still show an Error List pane error of "Cannot compile modules unless the '--module' flag is provided."?

As of today, is there a workaround for this?

**Comment by paulvanbrenk** [comment]
@MrAndMrsK  Which version of Visual Studio and TypeScript are you using?

**Comment by MrAndMrsK** [comment]
"Enterprise 2015 14.0.24720.00 Update 1" and "TypeScript 1.7.4.0"

**Comment by paulvanbrenk** [comment]
No, I don't think there is a workaround at the moment.. I'll have to look into that, but we're doing a ton of work on tsconfig support in VS, so I expect it to be much smoother in the next release.

**Comment by MrAndMrsK** [comment]
There's also an .xproj file that seems to have some remnants of the old Project file format that I guess isn't handled by project.json?  Anyway, I tried shoving `<TypeScriptModuleKind>System</TypeScriptModuleKind>` into that - for which VS did ask to reload the project, but it doesn't seem to make a difference.

**Comment by paulvanbrenk** [comment]
Does Compile on Save have the expected result?

**Comment by MrAndMrsK** [comment]
Yes it does

**Comment by paulvanbrenk** [comment]
@MrAndMrsK ok, thanks. I'll make sure to fix this for the next release. It doesn't sound like you're blocked at this time?

**Comment by MrAndMrsK** [comment]
I guess if I only get red squiggles on exported types and just on their name then it won't block us.  thanks.

**Comment by paulvanbrenk** [comment]
Support for multiple tsconfig.json files is part of 1.8, as is support for more project types.
