### ISSUE TITLE
Empty output from tsc and `out` compiler option acting surprisingly

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/TypeScript#3950]
I would not be at all surprised if I was doing something wrong here or if this problem was due to a lack of my understanding, but I think that `tsc` should have an error message or something here instead of producing surprising results and exiting with code `0`.

**tsconfig.json**
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "out": "out.js",
    "noImplicitAny": true,
    "preserveConstEnums": true,
    "noEmitOnError": true
  },
  "files": [
    "index.ts"
  ]
}
```

**index.ts**
```ts
import log = require('./log');

export = log('hello world');
```

**log.ts**
```ts
export = function log(message: string): void {
    console.log('[log]', message);
}
```

```
λ tsc -v
message TS6029: Version 1.5.3
nick.heiner@nheiner.local:/tmp/ts  λ tsc -p .
nick.heiner@nheiner.local:/tmp/ts  λ echo $?
0

```

**Expected**: As noted in the [`tsconfig.json` docs](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options), all my ts files are concatted into a single `out.ts` file, respecting what I set in `tsconfig.json`. 

> Concatenate and emit output to single file. The order of concatenation is determined by the list of files passed to the compiler on the command line along with triple-slash references and imports. See output file order documentation for more details.

**Actual**: I see `index.js` and `log.js` files created, which look correct, but `out.js` is empty.

**Comment by danquirk** [comment]
See https://github.com/Microsoft/TypeScript/issues/1544
