### ISSUE TITLE
Add @deprecated reasons in lib.dom.d.ts

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#39514]
**TypeScript Version:**  4.0.0-beta

**Search Terms**
- `@deprecated`
- `dom`
- `d.ts`

**Problem**

With TypeScript 4.0, we now render use of `@deprecated` apis. The dom apis include many deprecated symbols, but some of these do not include a reason that explains why a given api is deprecated and which API to use instead. This can be frustrating for users who don't want to see a strike through in the code but also don't know how to fix the problem

**Proposal**

Where possible, add `@deprecated` messages to the dom apis. See the MDN documentation on the deprecated `ScriptProcessorNode` for example: https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode

/cc @DanielRosenwasser

**Comment by RyanCavanaugh** [comment]
I'm not sure how many of these there are, but it'd be nice to have a list to check off
