### ISSUE TITLE
Add all imports inserts all commas before imports in files with crlf line endings 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/TypeScript#39515]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.0-dev.20200708

**Search Terms**
- windows
- crlf
- Add all missing imports

---

Issue Type: <b>Bug</b>

Copy some code into an existing TS file, and select "add all missing imports" form the quick fix.

### Before:
![image](https://user-images.githubusercontent.com/3840081/86653127-ce48cb00-bf99-11ea-9036-6c7f750b0401.png)

### After:
![image](https://user-images.githubusercontent.com/3840081/86653239-e4568b80-bf99-11ea-894a-d580ab1c44f6.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (48.88GB free)|
|Process Argv|--file-uri file:///c%3A/GIT/s%20p/vscode-python/pvsc.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vscode-pull-request-github|Git|0.17.0
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.6.1
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-typescript-tslint-plugin|ms-|1.2.3
code-spell-checker|str|1.9.0

</details>

**Comment by mjbvz** [comment]
Minimal repo:

https://github.com/mjbvz/ts-39515

Again, only could repo on windows

**Comment by mjbvz** [comment]
Also confirmed that changing line endings to `\n` fixes the problem.

**Comment by mjbvz** [comment]
TS Server trace


```
[Trace  - 02:24:06.406] <semantic> Response received: getCombinedCodeFix (80). Request took 7 ms. Success: true 
Result: {
    "changes": [
        {
            "fileName": "c:/Users/matb/projects/san/index.ts",
            "textChanges": [
                {
                    "start": {
                        "line": 3,
                        "offset": 7
                    },
                    "end": {
                        "line": 3,
                        "offset": 7
                    },
                    "newText": ","
                },
                {
                    "start": {
                        "line": 3,
                        "offset": 7
                    },
                    "end": {
                        "line": 3,
                        "offset": 7
                    },
                    "newText": ","
                },
                {
                    "start": {
                        "line": 3,
                        "offset": 8
                    },
                    "end": {
                        "line": 3,
                        "offset": 8
                    },
                    "newText": "\n    a3"
                },
                {
                    "start": {
                        "line": 3,
                        "offset": 8
                    },
                    "end": {
                        "line": 3,
                        "offset": 8
                    },
                    "newText": "\n    a4"
                }
            ]
        }
    ]
}
```
