### ISSUE TITLE
crypto.createHash("sha256").update does not accept base64 encoding.

### ISSUE THREAD

**Issue by xs2bharat** [microsoft/TypeScript#39528]
I am trying to generate sha256 fingerprint from pem certificate using following code.
The code as below

```
 const certificate = pemCertificate
      .split("\n")
      .filter(line => !line.includes("-----"))
      .map(line => line.trim())
      .join("");
crypto.createHash("sha256").update(certificate, 'base64').digest('hex');
```
The above code works fine but following warning appears. 

> The warning appears base64 is not assignable to parameter of type Utf8AsciiLatin1Encoding

.update method only accept following encodings type Utf8AsciiLatin1Encoding = "utf8" | "ascii" | "latin1";

The warning can be suppressed by using following code and code still works fine.
`crypto.createHash("sha256").update(certificate, 'base64' as Utf8AsciiLatin1Encoding).digest('hex');`

Shouldn't base64 be accepted encoding in .update method unless i am missing something.

The above code was referenced from here https://github.com/digitalbazaar/forge/issues/596

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by christophgysin** [comment]
FYI: this was fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50055
