### ISSUE TITLE
Template string not coloured when used with URL

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#3952]
Hi,

**Version**: VS 2015 RTM/TS 1.5

In the image below `url1` is coloured correctly, but not `url2`:

![image](https://cloud.githubusercontent.com/assets/1106823/8804809/d3ffbf72-2fc5-11e5-9438-375f3a2ba581.png)

(There is nothing wrong with the output.)

**Comment by mhegazy** [comment]
it is the slash before the `$` that is tricking the colorizer.

**Comment by SaschaNaz** [comment]
I think the last `` ` `` character should not be blue, should it?

**Comment by mhegazy** [comment]
the whole thing should not be blue :D it should be colorized just like the one in `const url1 =`

**Comment by SaschaNaz** [comment]
Ah, you're right.

**Comment by DanielRosenwasser** [comment]
This is not us being "confused" by the slash. This is a VS specific feature that is agnostic to our language service. You can see the same behavior within regex literals as well.

![image](https://cloud.githubusercontent.com/assets/972891/8813960/64c4025c-2fbc-11e5-835e-c1702392e462.png)

As a work-around, you can disable single-click URL navigation in `Tools` > `Options`:

![image](https://cloud.githubusercontent.com/assets/972891/8814003/c86e8eb2-2fbc-11e5-9359-5d2308998244.png)

**Comment by NoelAbrahams** [comment]
Okay, thanks. Turning off the hyperlinking seems to be a reasonable solution. There might still be a tiny bug in here because in `url2` in my original post the first back tick is coloured but not the second.

**Comment by DanielRosenwasser** [comment]
That's still just the issue with VS itself. It's looking for anything in a text buffer that it considers part of a URL and formatting it as such.
