### ISSUE TITLE
Type narrowing should be suppressed by assignments in nested function

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#39538]
**TypeScript Version:**  4.0.0-beta

**Search Terms:**

 - type narrowing inner function 
 - type narrowing nestedfunction 

**Code**

```ts
let foo: 1 | null = null;

const setFoo = () => foo = 1;

setFoo();

expect(foo).toEqual(1);

declare function expect<T>(actual: T): { toEqual(expected: T): void };
```

**Expected behavior:**

No error.
After `setFoo` is defined, `foo`'s type should no longer be narrowed by its original assignment, and should go back to `1 | null`.

**Actual behavior:**

> Argument of type '1' is not assignable to parameter of type 'null'.(2345)

`foo` is still inferred as `null`, even after it could be assigned differently in the inner function.

**Use case**

This comes up in complex Jasmine tests; Jasmine has `expect().toEqual()` like I defined above, and passing variable assigned in a callback breaks.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html?ts=4.0.0-beta#code/DYUwLgBAZg9jBcECMEA+EB2BXYwIF5MdgBuAKDIGMYMBnSW8AMTgIgAoBKAgPmlcJJyZRmBYwuwkAA8ADiEph2sGJwB0YGAFEAjlgCGwdkk7CAJguD6ATiGhYMigJY0IM+YoA8AFR7t9igbAiN6ciADeEJq6QezuCmAgZiFhEABuME5mEAC+JEA)

**Comment by DanielRosenwasser** [comment]
Pretty sure this is a design limitation discussed in #9998, and TypeScript takes an optimistic stance that local assumptions can be trusted over non-local side-effects.
