### ISSUE TITLE
TS 1.5.3 - Property 'attachEvent' does not exist on type 'Window'

### ISSUE THREAD

**Issue by Vadorequest** [Microsoft/TypeScript#3953]
I've just updated from 1.4.1 to 1.5.3 and my compiler doesn't want to compile that kind of code.

```
        if (window.addEventListener) {
            addEventListener("message", callback, false);
        } else {
            // Compatibilité IE.
            attachEvent("onmessage", callback);// THIS FAILS in 1.5.x., tried window.attachEvent, same thing.
        }
```

It is not listed on the breaking changes: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

Any advice/workaround?
Thanks.

*(that seems to be the only breaking change, keep up the good work guys, TS is just awesome!)*

**Comment by nippur72** [comment]
as for the workaround, what about
```TypeScript
(<any>window).attachEvent("onmessage", callback);
```

**Comment by Vadorequest** [comment]
This workaround should make it, thanks. ;)

**Comment by mhegazy** [comment]
Sorry about that. i have added it to the breaking changes list. they are IE-specific and we have cleaned up most of these, to keep the library accurate. to get your code to work all you need is the defintiion for these, so include this in one of your files:

```ts
// Add IE-specific interfaces to Window
interface Window {
    attachEvent(event: string, listener: EventListener): boolean;
    detachEvent(event: string, listener: EventListener): void;
}
```

**Comment by Vadorequest** [comment]
It makes sense! Thanks for the quick review and help, much appreciated!

**Comment by Vadorequest** [comment]
Just another thing, I just saw you made a spelling mistake in the breaking change page at `detatchEvent `:

> IE-specific attachEvent and detatchEvent are removed from Window

**Comment by mhegazy** [comment]
thanks! fixed.

**Comment by z-vr** [comment]
so how come all the global properties such as window.HTML*Any*Element do not exist in the Window interface? am I doing something wrong?

**Comment by mhegazy** [comment]
@z-vr, this is not related to the OP. the standard lib does not model the DOM mapping of global object to window. if you want to add these you can define something like:

```ts
interface Window {
    HTMLDivElement: typeof HTMLDivElement;
}
```

**Comment by mounikapk** [comment]
Hi ,

I have similar issue with my web application. uses web parts and Ajax. Below is the error:-

Object doesn't support property or method 'attachEvent'
Can someone help?

Thanks

**Comment by kmvan** [comment]
Try `window['attachEvent']`

**Comment by white112** [comment]
@kmvan 
Thanks.
It works when I try `window['FileReader']`

**Comment by NN---** [comment]
It is better to have definitions for missing functions.
I started a small library long time ago: https://github.com/NN---/lib.ie.d.ts/
Since I didn't need more IE-specific functions, it doesn't include more.
You are free to use it and submit updates.

Currently it is not pushed to npm cause I don't know how much interest there is in such lib.

**Comment by dimaslanjaka** [comment]
i've written some collections for typescript [globals.d.ts#L105](https://github.com/dimaslanjaka/js-prototypes/blob/7005460fd7c4fd117edf58b64d2520ce11a490e9/src/globals.d.ts#L105)
