### ISSUE TITLE
No aria suggestions for on react element when suggestions are manually triggered

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#39530]
From https://github.com/microsoft/vscode/issues/97220
**TypeScript Version:**  4.0.0-dev.20200708

**Search Terms:**
- jsx
- react
- aria
- suggest / suggestions / completions

**Code**
For the TS

```ts
import * as React from 'react';

export const a = (<div className="fdsa"></div>)
```

After the classname attribute:

1. Manually trigger suggestions.
1. Type `aria`

**Expected behavior:**
Suggestions for aria show up

**Actual behavior:**
No suggestions.

In my testing, the suggestions do show up in a few different cases:

1. When you manually trigger suggestions before className
1. When you start typing to trigger suggestions

**Comment by DanielRosenwasser** [comment]
If the `aria-` tags are defined, it should just be a matter of refining our completion filtering logic.

**Comment by arpithparikh** [comment]
Following this issue... is it resolved?

**Comment by Zzzen** [comment]
😆Apparently no.

**Comment by DanielRosenwasser** [comment]
Thanks @Zzzen!
