### ISSUE TITLE
Generic interface with generic type parameter as another generic interface without declared parameter 

### ISSUE THREAD

**Issue by archfz** [microsoft/TypeScript#39536]
## Search Terms

generic parameter for interface as another generic interface 
generic interface parameter nesting
generic interface with proxied generic parameter 

## Suggestion

I would like to be able to define a generic interface T<X> where X would be another generic interface and to be able to restrict how many generic parameters it would provide. Maybe best I could write it as `interface T<X<any>>` to require 1 generic type with 1 generic parameter, but that parameter would have to be added not in the declaration of the interface but in the declarations inside the body of the interface.

## Use Cases

An example use case would be of having a provider that serves some types A, B, C wrapped in another object that can have a generic type ParameterBag.

```typescript
interface Provider<ParameterBag<any>> {
  getA(): ParameterBag<A>
  getB(): ParameterBag<B>
  getC(): ParameterBag<C>
} 

interface ParmeterBagKind<T> { }
class ProviderKind implements Provider<ParmeterBagKind> { }
```

## Checklist

My suggestion meets these guidelines:

* [ x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
Duplicate of #1213

**Comment by archfz** [comment]
Is there a typescript vocabulary that gives all of these words for the generic typing specifics? Searching for existing issue for this was hard for me because I was not able to construct with proper names what I would like.

**Comment by archfz** [comment]
Also I will close this as of duplicate.

**Comment by jcalz** [comment]
>Is there a typescript vocabulary that gives all of these words for the generic typing specifics? Searching for existing issue for this was hard for me because I was not able to construct with proper names what I would like.

Not that I know of; the only reason I knew this was a duplicate is because I remembered the existing issue.  In other languages this is usually called "higher kinded types" but I don't know if there's a single canonical terminology for this or anything else in TypeScript.
