### ISSUE TITLE
A extends B relation break after wrapping by extra interface

### ISSUE THREAD

**Issue by nzhl** [microsoft/TypeScript#39545]
Reproduce link:  https://www.staging-typescript.org/play?ts=4.0.0-beta

![image](https://user-images.githubusercontent.com/16397293/87136381-0586e700-c2ce-11ea-8d87-d94fa79b284d.png)
The hint indicates that `CCELEextPCEle` in line 29  is false.  However when I uncomment line 20 and comment 17~19, the result back to true as expected.

**Comment by RyanCavanaugh** [comment]
Please don't post screenshots of code without accompanying text. It's absolutely tedious to type in 30 lines of code to validate things.

To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
