### ISSUE TITLE
Strange tuple typing

### ISSUE THREAD

**Issue by osdm** [Microsoft/TypeScript#3954]
```typescript
function f<T extends { "0": (p1: number) => number }>(p: T): T
{
	return p;
}

var v = f([x => x]); // v is typed as [{}]. Expected [number=>number]
```

**Comment by jonathandturner** [comment]
In your example, there isn't really a type to bind to.  You're saying T extends a type, but there's not enough information to know which type you mean.  It's like saying "pick a subtype of T, but I won't tell you which one".  

The x=>x isn't enough to help figure it out either.  

When the compiler hits that point, it chooses a conservative answer, like {}, to help prevent other errors from slipping through.

**Comment by osdm** [comment]
Could you please point to paragraph in the specification which discusses this process of choosing a conservative answer?

**Comment by osdm** [comment]
And one more question. If we have a tuple as a result, then we have a contextual type with a property "0" for our array literal. But at the same time, we don't have a contextual type for array element. I think this is not logical.

**Comment by RyanCavanaugh** [comment]
This isn't specific to tuples. You see the same behavior with object literals:
```ts
function f<T extends { q: (p1: number) => number }>(p: T): T {
    return p;
}

var v = f({q: x => x}); // v is typed as [{}]. Expected [number=>number]
```
We don't meaningfully contextually type `x => x` because the parameter type is just `T`. Arguably we should use base constraint of a type parameter when contextually typing by it, which should make all these examples "just work". @ahejlsberg ?

**Comment by osdm** [comment]
@RyanCavanaugh Well, at least there should be an compilation error, because [{}] is not assignable to { "0": (p1: number) => number }. Because of this IMHO this is a bug.

**Comment by RyanCavanaugh** [comment]
That's a good point

**Comment by JsonFreeman** [comment]
I'm debugging this now. I'll be able to give you an answer soon about what is going on.

**Comment by JsonFreeman** [comment]
@jonathandturner @RyanCavanaugh @osdm We do use the base constraint for contextual typing, as of recently, #3822. So there is something else amiss.

**Comment by JsonFreeman** [comment]
Ok, turns out we are leaking an internal compiler type that looks like `{}`. It happens whenever you try to infer a type for a type parameter, and the type parameter contains the anyFunctionType, but isn't directly the anyFunctionType.

**Comment by JsonFreeman** [comment]
I am adding a rule in the subtype relation to fix this.

**Comment by JsonFreeman** [comment]
Ok, the new rule is that a type with signatures is *not* a subtype of the anyFunctionType. It is assignable, but it's not a subtype.
