### ISSUE TITLE
Wrong union of types

### ISSUE THREAD

**Issue by bitlab-code** [microsoft/TypeScript#39544]
**TypeScript Version:**  Nightly

**Search Terms:**

**Expected behavior:**
`encode` need to accepts an intersection of types

**Actual behavior:**
`encode ` has an union on types as param

**Related Issues:**

**Code**
```ts
// TYPES
type Schema = {
    one: {
        apple: number
    },
    two: {
        banana: number
    }
}
type Collection = keyof Schema;
type Doc<C extends Collection> = Schema[C];

type SchemaObject = {
  [name in keyof Schema]: SchemaObjectItem<name>;
};
type SchemaObjectItem<C extends Collection> = {
    encode: (data: Doc<C>) => string;
  }

// EXAMPLE
const schemaObject: SchemaObject = {
    one: {
        encode: data => `${data.apple}`
    },
    two: {
        encode: data => `${data.banana}`
    }
}

function test<C extends Collection>(schemaItem: C, data: Doc<C>): string {
    // `encode` must accept Doc<'one'> | Doc<'two'> and not Doc<'one'> & Doc<'two'>
    return schemaObject[schemaItem].encode(data)
} 
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// DATA
const schemaObject = {
    one: {
        encode: data => `${data.apple}`
    },
    two: {
        encode: data => `${data.banana}`
    }
};
function test(schemaItem, data) {
    // data is Doc<'one'> | Doc<'two'> and not Doc<'one'> & Doc<'two'>
    return schemaObject[schemaItem].encode(data);
}

```
</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```
</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200710&ssl=31&ssc=60&pln=31&pc=59#code/PTAEBUE0AUFEGUBQAXAngBwKangYwBaYC2AhqALygDeiodoA9gHaYBc1t9XJ66ANm1BMArkQBGmAE6c6AXwA0M0MgDuDdjS5cxJJrpLsR4qUtmIzaLKADCDPgNzIAlswqgA1plQMAZjgLEJADcKBjYACIMuAA81qCYAB7ImEwAJgDONnYOzswAfG54hKQA2tYAuiGhVkWBAPJiAFaYjm6aoCV6RNhOTB5evv7FJOXstaQNzY4AkslE0V2YeSGyIZbY4ySTLcizxLHxSSkZWfY7LkwFlO10KbgMqYIAFKkkyAagkTHWeQCUFAV0shJL0AOYhOSIRAgT4AQXAsMQ9yYQNA6QCEyaOzGGK2WNa1yUzEENy0dwegle7wBoAABgASKhUkgAOh4-EwslppkUXFU6g4Wno5Me7GZNIZTLerJ0ej0XNM5ihPmETEcF2UmCBB0SyTSmVsZ3V+Se6OGeyI7Gs8lAzPYX1if3YQJBTFBgvoMPFTkyDoA5MS-QUAD6fKLRP38oOgXSpIQMZBhmIBljRgBkSYjUbySkkmGQwkkfTN9XxyBKJdIFvKLJFmBe0t+5lAQA)
      

Error: 
```
Argument of type 'Doc<C>' is not assignable to parameter of type '{ apple: number; } & { banana: number; }'.
  Type '{ apple: number; } | { banana: number; }' is not assignable to type '{ apple: number; } & { banana: number; }'.
```

**Comment by RyanCavanaugh** [comment]
This is a correct error; your misapprehension is that `C extends Collection` means that it'd be *exactly either* of `one` or `two`, but `test<"one" | "two">(...` is a legal call that would induce an unsoundness in this code.

**Comment by bitlab-code** [comment]
ok @RyanCavanaugh, thanks.
if it work as intended, i'll close this issue... 

but honestly I did not understand 😅 why `encode` (inside `test` function) expects `{ apple: number } & { banana: number }` and not `{ apple: number } | { banana: number }` 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/19858243/87179450-083e0800-c2df-11ea-8fe7-009539e434a8.png">
