### ISSUE TITLE
Emitting combined output declarations tries to resolve monorepo imports

### ISSUE THREAD

**Issue by mischnic** [microsoft/TypeScript#39547]
**TypeScript Version:**  4.0.0-dev.20200710

**Search Terms:** emit declaration, combined output, monorepo, outFile

**Code**

`tsc index.ts --declaration --emitDeclarationOnly --outFile dist/index.d.ts`

```ts
// packages/a/src/index.ts
import { B } from "b"; // this imports another package in the monorepo

export default function () {
	return new B();
}
```

```json5
// packages/b/package.json
{
	"name": "b",
	"version": "0.0.0",
	"source": "src/index.ts",
	"types": "dist/index.d.ts", // doesn't exist yet
	"main": "dist/index.js"     // doesn't exist yet
}
```

The files listed in the package.json of `b` don't exist yet because when building all packages in this monorepo setup, `a` is built before `b`.

Full repro in https://github.com/mischnic/parcel-issue-3891

Strangely enough, when omitting the `--outFile` flag, the declaration file for `packages/a/src/index.ts` (correctly) contains `import ... from "b";` (this suggests that this is indeed a bug and not per design).

**Expected behavior:**

`a/dist/index.d.ts` output:
```ts
declare module "index" {
    import { B } from "b";
    export default function (): B;
}
```

**Actual behavior:**

`a/dist/index.d.ts` output:
```ts
declare module "index" {
    import { B } from "../../b/index"; // <---
    export default function (): B;
}
```

**Playground Link:** 
https://github.com/mischnic/parcel-issue-3891

**Related Issues:** Not really related: https://github.com/microsoft/TypeScript/issues/34846

**Comment by mischnic** [comment]
(I'd be happy to fix this myself if someone can confirm this and point me to the right source files)

**Comment by RyanCavanaugh** [comment]
Using `outFile` with modules is almost always a mistake; what are you intending to do with that setting?

**Comment by mischnic** [comment]
Thanks for the response!

We're using it in [Parcel](https://github.com/parcel-bundler/parcel) to essentially create a definitions bundle (as opposed to multiple files) for a package, e.g.

```ts
// index.ts
import { B } from "b";
export { thing } from "./other";

export default function () {
	return new B();
}
// other.ts
export function thing(){
	return "abc";
}
```
--tsc-->
```ts
declare module "other" {
    export function thing(): string;
}
declare module "index" {
    import { B } from "b";
    export { thing } from "other";
    export default function (): B;
}
```
--ast transformation-->
```ts
import { B } from "b";
export function thing(): string;
export default function (): B;
```
