### ISSUE TITLE
[Bug Report] Wrong keyof type with string index signature

### ISSUE THREAD

**Issue by meteorlxy** [microsoft/TypeScript#39543]
**TypeScript Version:**  3.9.x

**Search Terms:** keyof, index signature

**Code**

```ts
interface Test1 {
    [key: string]: string;
}

type KeyofTest1 = keyof Test1

interface Test2 {
    [key: number]: string;
}

type KeyofTest2 = keyof Test2
```

**Expected behavior:**

- `KeyofTest1 ` should be `string`
- `KeyofTest2` should be `number`

**Actual behavior:**

- `KeyofTest1 ` is `string | number` (**wrong**)
- `KeyofTest2` is `number` (correct)

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=1#code/JYOwLgpgTgZghgYwgAgCoQM5gIzIN4BQyxyA2gNYQCeAXMllKAOYC6dDzA3AQL4EFgqABxQBpagHsY6LLgC8ySlSlpMOfqEixEKGWABM+IiQrU6IAK4BbAEbQ29MIxBNufAcLGTpawwqUqevoEQA

**Related Issues:**

**Comment by IllusionMH** [comment]
This is by design
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-number-and-symbol-named-properties-with-keyof-and-mapped-types

> Given an object type X, keyof X is resolved as follows:
>
> If X contains a string index signature, keyof X is a union of string, number, and the literal types representing symbol-like properties, otherwise

**Comment by meteorlxy** [comment]
@IllusionMH Thanks for your quick reply. ❤️ 

What's the underlay reason of this "by design" ? 🤔 

It looks odd and causes some strange type checking error in some third party packages

**Comment by IllusionMH** [comment]
I think it's because there's no difference between `obj[123]` and `obj["123"]` in JS, and TS won't error in case of `orders[orderId]` if it's `orderId` is number (which would be annoying).
Any number converted to string will be valid string, however not every string will be valid number therefore same is not applied for `number` index signature.

I guess it should be of to use `Extract<keyof T, string>` if you don't expect to use numbers there.

But I can be wrong here.

**Comment by meteorlxy** [comment]
Yeah a possible solution. I'll trying to submit a PR to that package.

Thanks again~ 😄

**Comment by ExE-Boss** [comment]
Arguably, now that we have <https://github.com/microsoft/TypeScript/pull/40336> and <https://github.com/microsoft/TypeScript/pull/40598>, `keyof` should report <code>\`${number}\`</code> for numeric index signatures.
