### ISSUE TITLE
function type in union type not work?

### ISSUE THREAD

**Issue by keelii** [microsoft/TypeScript#39546]
```ts
type fn = (param: number) => string

// works
type t1 = string | fn

// not works, why？
type t2 = string | (param: number) => string
```

**Comment by keelii** [comment]
But this is OK(with brackets`()`):

```ts
type fn = (param: number) => string

// works
type t1 = string | fn

// It's OK
type t2 = string | ((param: number) => string)
```

This maybe confused, the same code express different meanings.

```ts
type t2_maybe_1 = string
    | (param: number) => string
    | number

type t2_maybe_2 = string
    | (param: number) => string | number
```

**Comment by DanielRosenwasser** [comment]
Concerns over visual ambiguity.

```ts
type Foo = () => string | () => number;
```

could be parsed as

```ts
type Foo = () => (string | () => number);
```

which isn't always what people want.

It doesn't protect against all the cases, but it's what we felt we could cover.

The fact that you don't get a good error message - now that's a terrible experience...

**Comment by DanielRosenwasser** [comment]
Check out https://github.com/microsoft/TypeScript/issues/39548 to track making the error UX better here.

**Comment by DanielRosenwasser** [comment]
You should now get a nicer error message thanks to #39570 by @uhyo.

**Comment by keelii** [comment]
@DanielRosenwasser Nice work, thx~
