### ISSUE TITLE
Filter function in lodash makes the compiler run out of memory and barf

### ISSUE THREAD

**Issue by reduxdj** [microsoft/TypeScript#39553]
Typescript: 3.9.6
Node: 12.13.0

```js
_.filter(results, filters)
```
Workaround:
```js
const lodash = _
        return eval('lodash.filter(results, filters);') 
```

**Comment by RyanCavanaugh** [comment]
This is my best guess at what you were doing
```ts
import * as _ from "lodash";
declare const results: any, filters: any;
_.filter(results, filters);
```
which compiles without problem. Can you be more specific about how to reproduce the problem?

**Comment by reduxdj** [comment]
Interesting, any works. 

I had this:
```js
const results: SomeType = JSON.parse(result.Payload as string)?.hits.hits?.map(({ _source }) => _source);
```

And then I moved to this, and works fine: It would be neat if the compiler could catch this and tell you to use any in this case, instead of a spew of errors in the console

```js
const results:any = JSON.parse(result.Payload as string)?.hits.hits?.map(({ _source }) => _source);
```
