### ISSUE TITLE
[Bug] Setting `module: esnext` behaves like i also set `moduleResolution` to `classic`

### ISSUE THREAD

**Issue by sw-yx** [microsoft/TypeScript#39555]
hi! long time user, first time issue filer. :)

**TypeScript Version:**  3.9.6

**Search Terms:** module, moduleResolution, esnext

**Code**

```json
{
  "compilerOptions": {
   "target": "es2017",            
   "module": "esnext",          
   "strict": true,             
   "esModuleInterop": true,        
   "skipLibCheck": true,          
   "forceConsistentCasingInFileNames": true
  }
 }
```

this breaks module resolution:

![image](https://user-images.githubusercontent.com/6764957/87189341-1150c880-c323-11ea-818d-5acdedb499aa.png)

add back module resolution:

```json
{
  "compilerOptions": {
   "target": "es2017",            
   "module": "esnext",          
   "strict": true,             
   "moduleResolution": "node",      // here
   "esModuleInterop": true,        
   "skipLibCheck": true,          
   "forceConsistentCasingInFileNames": true
  }
 }
```

and it works

![image](https://user-images.githubusercontent.com/6764957/87189404-2c233d00-c323-11ea-9b3e-fcc05a1d1c08.png)

**Expected behavior:**

i think its a bug. according to this https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies `moduleResolution` should be `node` when `module` is `esnext`

**Actual behavior:**

setting `module: esnext` makes `moduleResolution` behave like it is `node`

**Playground Link:** i cant replicate this in playground since it is about node module resolution

**Related Issues:** not here but https://github.com/octokit/rest.js/issues/1790

**Comment by DanielRosenwasser** [comment]
I think this is a duplicate of https://github.com/microsoft/TypeScript/issues/11434

**Comment by sw-yx** [comment]
oh interesting! (also, hi!) i was kinda doubting whether i should file this cos i had seriously doubted something like this wouldve gone undiscovered/unaddressed. now surprised to find it's been like that for 4 years!

i confess my interest in this bug declined immediately after i found that forcing `moduleResolution` fixed my problems. perhaps as a first effect, we could update the docs to reflect how the `module` field *currently* works, instead of how it's intended to work?

**Comment by DanielRosenwasser** [comment]
No worries! I think it's confusing and the docs don't help either. Otherwise 👋 to you too! 🙂

I think we would definitely appreciate a PR to https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Module%20Resolution.md

@orta will know whether new docs have any of the same mismatch in description

**Comment by DanielRosenwasser** [comment]
P.S. we also have https://github.com/microsoft/TypeScript/issues/35876 and https://github.com/microsoft/TypeScript/pull/38105 will help users clue in on the wrong behavior sooner.

**Comment by sw-yx** [comment]
nice. i see, so we rather preserve backward compatibility than "fix" it? imo this is one of those things that might be a nice breaking change for TS 4.0. but my opinion is very very uninformed so pls dont mind me too much. im happy as long as the docs are right

**Comment by DanielRosenwasser** [comment]
Nah, while it's not necessarily clear how breaky/turbulent a change like that would be, that would've been something to consider but...we have tried to avoid breaks after shipping our beta.

**Comment by orta** [comment]
I've not been merging PRs to this repo since I moved all of the docs to the v2 site and did a bunch of work, basically when we archive this repo in 2 weeks I'm planning on moving over every open PR by hand

**Comment by sw-yx** [comment]
ah i wasnt aware. i've found the equivalent doc https://github.com/microsoft/TypeScript-Website/blob/10096c186fe4b470250218fd9c935fbe4119a6a1/packages/handbook-v1/en/Module%20Resolution.md but its not clear if i should move [my PR](https://github.com/microsoft/TypeScript-Handbook/pull/1333) there or just let you figure it out. i'll leave it for now and feel free to point me at whatever i can do to help

**Comment by sw-yx** [comment]
resolved by orta on the new docsite https://github.com/microsoft/TypeScript-Website/pull/781
