### ISSUE TITLE
Ternary operator does not correctly narrow types (while equivalent if statement does)

### ISSUE THREAD

**Issue by avolkovi** [microsoft/TypeScript#39550]
**TypeScript Version:**  3.9.2

**Search Terms:**
typescript, ternary, type narrowing

**Expected behavior:**
Both bar() and baz() should compile and have equivalent behavior.

**Actual behavior:**
baz() compiles, bar() fails to compile with "Property 'a' does not exist on type 'never'."

**Related Issues:**
Possibly related to https://github.com/microsoft/TypeScript/issues/37452

**Code**
```ts
interface FooA {
  a: string;
}

interface FooB {
  b: string;
}

interface FooAB {
  a: string;
  b: string;
}

type Foo = FooA | FooB | FooAB;

function bar(foo: Foo | string): string {
  const parsedFoo = typeof foo === 'string' ? { a: foo } : foo;
  if ('a' in parsedFoo && 'b' in parsedFoo) {
    // typeof(parsedFoo) is never
    return parsedFoo.a + parsedFoo.b;
  }
  return "";
}

function baz(foo: Foo | string): string {
  let parsedFoo: Foo;
  if (typeof foo === 'string') {
    parsedFoo = { a: foo }
  } else {
    parsedFoo = foo;
  };
  if ('a' in parsedFoo && 'b' in parsedFoo) {
    // typeof(parsedFoo) is FooAB
    return parsedFoo.a + parsedFoo.b;
  }
  return "";
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function bar(foo) {
    const parsedFoo = typeof foo === 'string' ? { a: foo } : foo;
    if ('a' in parsedFoo && 'b' in parsedFoo) {
        // typeof(parsedFoo) is never
        return parsedFoo.a + parsedFoo.b;
    }
    return "";
}
function baz(foo) {
    let parsedFoo;
    if (typeof foo === 'string') {
        parsedFoo = { a: foo };
    }
    else {
        parsedFoo = foo;
    }
    ;
    if ('a' in parsedFoo && 'b' in parsedFoo) {
        // typeof(parsedFoo) is FooAB
        return parsedFoo.a + parsedFoo.b;
    }
    return "";
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=11&ssc=6&pln=11&pc=7#code/JYOwLgpgTgZghgYwgAgGIHt0EFkG8BQyycAXMgM5hSgDmA3PgL776iSyIoboBCehyAEZlK1EPSYs20eEjSYsfAkVIUqtBkWFqxE5vjABPAA5dMyALzzsyAD7W+97oob4YAVxAIwwdCCFwUAAUMJhk3HY6tACUIuri-EQIfpTIxoHkEAAmEVZGpugwyKHolhZWAOSitBXIAPx4xGQlyIzIzZiayMBFQRVwtaBpGdkRAGRjyBWCg-7pUJk5mNGJRMgA9OvI+RCFQfOL3CvA5MggEABu0AJEUBBg7lBzI0voAHRwyADUwwujmG9BF1mLd7o9-AAiCEMfQeLw+PwBABeITC1ki1XEsSiCWUyAANvdfoc0dwuj1kEEdoViuZypVMTQKis8UQDv9SlZcE1aaUQa1kBB8ZlVmyXrlecDyb1+rNiRzkBMpjNus8-q8WTcNltqTB9uLlt1Ts4eFq7g8nvLXh9vlbuIDgQJzeDkFCYUA)

**Comment by RyanCavanaugh** [comment]
These functions are different because one explicitly introduces the possibility of `FooAB` into the mix at the declaration site for `parsedFoo`, where the other doesn't because there's a subtype reduction in the false arm of the conditional that produces `FooA`.

**Comment by avolkovi** [comment]
@RyanCavanaugh how is the possibility of FooAB filtered out in the ternary case? The Possibility of FooA is introduced - I agree, but FooAB is still a valid possibility

**Comment by RyanCavanaugh** [comment]
@avolkovi the inferred type of `parsedFoo` in `bar` is produced from the subtype-reduced union between `{ a: string }` and `FooA | FooB | FooAB`, which is `FooA | FooB`. 

A union like `Foo` never quite behaves well because it reduces as soon as you look at it funny; `FooA | FooB` is a better way to write the union that behaves more consistently

**Comment by jcalz** [comment]
related to #37518
