### ISSUE TITLE
Higher-order inference fails depending on how an intersection is built

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/TypeScript#39565]
**TypeScript Version:**  3.9.2

**Search Terms:** Intersection, interface, inference, higher-order, function

**Expected behavior:**

`working` and `broken` behave the same. The code should compile for both.

**Actual behavior:**

A compile-time error is issued for valid code.

```
Property 'name' is missing in type 'Aging' but required in type 'Both'.(2345)
```

**Related Issues:**

**Code**

I'm intersecting two object types by creating an interface that inherits from both.

```ts
interface Named {
  name: string;
}

interface Aging {
  age: number;
}

/**
 * I would expect it to be the same as Named & Aging.
 */
interface Both extends Named, Aging {}
```

The `withName` function accepts a function and partially applies it.

```ts
function withName<P extends object>(fn: (props: P & Named) => void): (props: P) => void {
  return props => fn({ ...props, name: 'Bob' });
}
```

Depending on how I define `fn`, the code either compiles or it doesn't. I expect `working` and `broken` to be equal — as `Named & Aging` is equal to `Both`.

```ts
declare function working(props: Named & Aging): void;
declare function broken(props: Both): void;

const aging: Aging = { age: 42 }

withName(working)(aging);
withName(broken)(aging); // Property 'name' is missing in type 'Aging' but required in type 'Both'.(2345)
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function withName(fn) {
    return props => fn(Object.assign(Object.assign({}, props), { name: 'Bob' }));
}
const aging = { age: 42 };
withName(working)(aging);
withName(broken)(aging); // Property 'name' is missing in type 'Aging' but required in type 'Both'.(2345)

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.staging-typescript.org/play?#code/JYOwLgpgTgZghgYwgAgHJwLYQCbIN4BQyyImEAXMgM5hSgDmA3AQL4EGiSyIoCC9DfEWRx6FEgFcMAI2jM2BAPQAqZUWXIAksgDuAewkAbXBAAeABwgIwyYDbB7ks5GAAWKKmRFU0ZXADJkfgYAOnVFDnBoeCRkACE9N2QzSBBsH3QsbAAaIIEQenwFGAkQa2A9EF07V0yIAB4ABWTTVPTkPWkAKyswAD4AChgQSgHzKD1zKkpmwLrsAEpkAF4+5AA3PWBF0fHJ6eRGpdWNrdxCYigIMAkoKr2plbXhgbxkEI+HqlzSLEoAcgS0n+yBYC3k7GwVkMcCuyBKZTAFSq+igAGsGGMJlNKPNkIFggUFpRNttmFCEDC4QjypUnBM0RAQFj9pQEm5iacyewEJUaCJ8vRKITCst8ALxAAWABMoPYOhqdQGqIxRIGogY4IICrcSukDKZC3VgvByEUikO2OgYAAnsh-r8ICDgD4MC6qIJQC4bZZ7SKQdIJDYrgBHCTAK64L2232AxKuf4hAbSgDMkoArAsgA)

[Reference](https://stackoverflow.com/q/62848561/10325032)

**Comment by RyanCavanaugh** [comment]
In the intersection case, given a `T & U` inferring to a `V & U` position, the desired inference is `T = V`; this was a fairly common complaint before it was implemented.

In the interface case, one of generic inference's design constraints is that it won't synthesize a new type - the inferred type is always one of the identifiable candidates. The type we'd have to produce would be `Exclude<Aging, keyof Named>` which is really what you'd actually want.

In practice both of these cases work they way you'd usually want them to in real code; the fact that they are different does mean that different results can occur.
