### ISSUE TITLE
in generic<T extends bigint|number> T * T is deduced as number instead of T

### ISSUE THREAD

**Issue by emilioplatzer** [microsoft/TypeScript#39569]
**TypeScript Version:**  3.9.4

**Search Terms:** is:issue bigint generics 

**Code**

```ts

function mult(a: bigint, b: bigint) {
    return a*b
}
var c = mult(1n, 2n);

function prod<Num extends bigint | number>(a: Num, b: Num) {
    var d1: Num = a * b;
    return a*b
}
var d2 = prod(1n, 2n);
```

**Expected behavior:**
var d1 dos not show error because is Num and also a and b are it too and number * number is number and bigint * bigint is bigint and both are of the same type. 
var d2 is deduced of type bigint;

**Actual behavior:**
var d1 show error because expect number;
var d2 is deduced of type number;

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?target=7&ssl=12&ssc=23&pln=1&pc=1#code/FAMwrgdgxgLglgewgAgLZgDYwBQEMBcyARnAOZwQwA0xhJ5lAlMgN7DIfIBOApjGFxS4AVEWABfYADdcXZFGQBeNJhwBGCDQBMERgG5gh8NHhJkABy4IAJgB4AcmFTIeADxg8I1gM7EyFGGQAH2QIJyIeLgA+PEJHVBoiOKdmNk5kGTlrNWTnZVxkYWIDdN5+QWQRMUlM5GstJQsra2wNbV0DIA

**Related Issues:**

**Comment by emilioplatzer** [comment]
I found something more puzzling: 

You cannot add two T extens bigint|number

```
function sum(a: bigint, b: bigint) {
    var c1:bigint = a + b; // ok
    return a + b
}
var c2 = sum(1n, 2n);

function add<Num extends bigint | number>(a: Num, b: Num) {
    var d1: Num = a + b; // show error in "a + b"
    return a + b
}
var d2 = add(1n, 2n);
```

https://www.typescriptlang.org/play/index.html?target=7&ssl=13&ssc=1&pln=1&pc=1#code/FAMwrgdgxgLglgewgAgM5gLYAoCGAuZAIzgHM4IYAaIg4sigSmQG9hl3kA3HAJ2SgCMeOuRjIAvMhzIA1EQDcbDjwCmMMDxTS5hYAF9g3PlABMEtJiwCI1ExAaLQkWIi0ATNwB4AcpmQqADxgVCDdUIlJRZAAfZAhMQhUeAD5cAl8MakJ0zCZWDi5eZDchZAzzbQUldlV1TSlZIn1DIrczSRwPKxtkOwdgYCA

**Comment by MartinJohns** [comment]
> var d1 dos not show error because is Num and also a and b are it too and number * number is number and bigint * bigint is bigint and both are of the same type.

But "bigint * number" is an illegal operation, and the type can be `BigInt` or `number`.

    prod<BigInt | number>(123n, 4);

**Comment by emilioplatzer** [comment]
Oh, I see. You are right! 

Is there a way to say in a generic "Num is bigint or Num is number but not bigint|number"?

That was I need!

**Comment by awerlogus** [comment]
You can write something like

```ts
function mult<T extends [number, number] | [bigint, bigint]>(...data: T): T[0] extends bigint ? bigint : number {
  return data[0] * data[1]
}
```

But typescript shows an error here too:
```
Operator '*' cannot be applied to types 'number | bigint' and 'number | bigint'.ts(2365)
```

This is a type system flaw that should be fixed.

**Comment by MartinJohns** [comment]
> Is there a way to say in a generic "Num is bigint or Num is number but not bigint|number"?

No, there is not. The feature request for this is #27808.

Your best option is to either just use two functions, or use function overloading and type-assertions in your implementation.

**Comment by emilioplatzer** [comment]
Can we expect to having something like https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#contextual-narrowing-for-generics to this cases?
