### ISSUE TITLE
Why promise will be unwrapped by dynamic import?

### ISSUE THREAD

**Issue by unadlib** [microsoft/TypeScript#39566]
`import('./sample.json')` as expression returns a Promise because it executes asynchronously.
`import('./sample.json')` as type is not intended to be the same as the expression counterpart. It's meant to reference a type of another module inline. Since it has no runtime behavior, it doesn't need to result in a Promise-type.

_Originally posted by @ajafff in https://github.com/microsoft/TypeScript/issues/27678#issuecomment-428459967_

You mean it's not runtime behavior, so it's just a static type import, right? 

But `import()` as one of the important features of ECMAScript 2020 (ECMA-262). I wonder if TypeScript should be consistent with it. Especially since there is a difference between local dynamic import and remote dynamic import(although it's not currently supported by TypeScript.). 

Should `import('./sample.json')` be considered a Promise-type in order to be consistent?

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be describing a defect or proposal. There are valid arguments either way but it's shipped now and the argument for changing it would need to be a lot stronger than "you could"
