### ISSUE TITLE
a weird problem with promise-type check 

### ISSUE THREAD

**Issue by catee** [microsoft/TypeScript#39576]
**TypeScript Version:**  3.9.2

**Search Terms:** promise

**Code**

```ts
type FuncType = () => boolean | Promise<boolean>

function imok(fn: FuncType) {
    const flag = fn()
    if (typeof flag === 'boolean') {
        flag  // flag is boolean
    } else {
        flag  // flag is Promise<boolean>
    }
}

function imconfused(fn: FuncType) {
    const flag = fn()
    if (Promise.resolve(flag) === flag) {
        flag  // flag is Promise<boolean>
    } else {
        flag  // flag is boolean | Promise<boolean> . so i'm confused.
    }
}

```

**Expected behavior:** 

```ts
function imconfused(fn: FuncType) {
    const flag = fn()
    if (Promise.resolve(flag) === flag) {
        flag  // flag is Promise<boolean>
    } else {
        flag  // flag is boolean
    }
}
```

**Actual behavior:**

```ts
function imconfused(fn: FuncType) {
    const flag = fn()
    if (Promise.resolve(flag) === flag) {
        flag  // flag is Promise<boolean>
    } else {
        flag  // flag is boolean | Promise<boolean> . so i'm confused.
    }
}
```

**Playground Link:** 

[click me](https://www.typescriptlang.org/play/index.html?ssl=23&ssc=1&pln=3&pc=1#code/FDAuE8AcFMAIDECuA7AxgFSnAvLAFAJSzYB8sARgPaUA20AhsrAD6wAKATpQLYCWAztAA8VWg2QkQwAGYpUoXpSa9ulANZ5pyAFwI5mGEQDewWGdiol-ULGk16Ac2K3khU+d7T8EGJS93HYmxcAHJROkYQ43dzcwCHGNgAX1hoGkFYE1jY+MSk4HyZOQUlWBVLZFlBABNNHT00A2ho2IrrW3snXC03WM98Th4BaAA6Dmh+WgA3aE1OomDu+czEnM681PS4LOyzXNj8-KA)

**Related Issues:** 

Haven't found one.

**Comment by DanielRosenwasser** [comment]
While we know that `Promise.resolve` passes through the original value if it's a promise, the type-checker doesn't.

In the positive case, we can narrow the type to `Promise<boolean>`, but in the negative case, it would be bad to narrow the `Promise<boolean>` type out based on object identity. We only do this when we have singleton types.

The relevant code in the compiler is `narrowTypeByEquality`.

**Comment by catee** [comment]
Thanks! Got it. 👍
