### ISSUE TITLE
Adding a TS file to a project breaks renaming files in VS 2015 RTM

### ISSUE THREAD

**Issue by HellBrick** [Microsoft/TypeScript#3957]
Here are the steps to reproduce the issue:

1. Create a new ASP.NET 4 project in VS 2015 RTM by using the default MVC template.
2. You can make sure the renaming works at this point: use Solution explorer to rename any file with a C# class in it (HomeController.cs, for example), agree to rename the class itself and verify that it has been renamed successfully.
3. Add a TypeScript file to the project.
4. Try renaming a file with a C# class again, but this time when VS tries to rename the class, it will crash with the following error:

http://i.imgur.com/3Suoxi9.png
>Unable to cast object of type 'Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptProject' to type 'Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.IProjectCodeModelProvider'.

P.S. I'm not sure if this is the right repo to post this kind of issue, but since it clearly has something to do with TypeScript, this place seemed like a good fit.

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look

**Comment by paulvanbrenk** [comment]
This is a problem in the Visual Studio codebase, not in the TypeScript code. We did submit a fix there, but I can't tell you at this time when that will be available.
