### ISSUE TITLE
When Compiling to ESNext Class Fields Initializers Should Not Move to the Constructor

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/TypeScript#39575]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
private class fields initializer constructor

**Code**
Target ESNext.
```ts
class Hello {
    #field2 = 5;
    field = 5;
    method = () => { }
    #method2 = () => { }
}
```

**Expected behavior:**
Output:
```js
class Hello {
    #field2 = 5;
    field = 5;
    method = () => { }
    #method2 = () => { }
}
```
Since the class fields proposal supports initialization and this would reflect the original code more accurately.

**Actual behavior:**
Fields are initialized in constructor:
```js
class Hello {
    constructor() {
        this.#field2 = 5;
        this.field = 5;
        this.method = () => { };
        this.#method2 = () => { };
    }
    #field2;
    #method2;
}
```

**Playground Link:** https://www.staging-typescript.org/play?target=99&ts=4.0.0-dev.20200712#code/MYGwhgzhAEASCmIQHtoG8BQ1vQMQDMBLRAEwCZoBeaAVgG4scjSraGdoBbeAFwAtkJVgAoAlFQB86aAF9G2XN36CK1MZOly5QA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is for back compat reasons; set `useDefineForClassFields` to `true` to have them remain as ES-style property initializers
