### ISSUE TITLE
TypeScript shouldn't compile configured exclusions 

### ISSUE THREAD

**Issue by ltfschoen** [microsoft/TypeScript#39580]
**TypeScript Version:**  3.9.6

**Search Terms:**

csstypes

**Code**

Reproduce the issue as follows:
* Clone my repo https://github.com/ltfschoen/typescript-test
* Run `yarn build-examples`, and it should compile.
* Then remove these lines https://github.com/ltfschoen/typescript-test/blob/master/tsconfig-examples.json#L7 and https://github.com/ltfschoen/typescript-test/blob/master/tsconfig-examples.json#L10.
* Re-run `yarn build-examples`, and it should generate the above error.

**Expected behavior:**

If I configure a  tsconfig.json file to exclude certain directories that I don't want to be compiled (e.g. `"exclude": [ "node_modules/**/*" ]`), then when I run `tsc` then I don't expect any TypeScript files in that excluded directory to be compiled, and I don't expect other configuration properties of the tsconfig.json file or folders that are included in the compilation by default to take precedence over the exclusions (i.e. exclusions where specified should override inclusions)

**Actual behavior:**

If I configure a tsconfig-examples.json to only compile a specific file (e.g. `"files": [ "./src/examples/greeter.ts", ]`), or if I specify only a specific folder to be compiled (e.g. `"include": [ "src/examples/**/*" ]`), or if I specify that I do not want the node_modules folder to be compiled (e.g. `"exclude": [ "node_modules/**/*" ]`), then regardless of these inclusions and exclusions, when I compile the code with `./node_modules/typescript/bin/tsc --project tsconfig-examples.json`, it will generate the following error:
```
node_modules/@types/react/index.d.ts:38:22 - error TS2307: Cannot find module 'csstype' or its corresponding type declarations.

38 import * as CSS from 'csstype';
```

However, if in tsconfig-examples.json I set `compilerOptions.moduleResolution: "node"`, as recommended [here in Stackoverflow](https://stackoverflow.com/a/49723080/3208553) then it compiles successfully.

Alternatively, if in tsconfig-examples.json I set `compilerOptions.types: []`, then it also compiles successfully. This is because in the TypeScript documentation typescriptlang.org/docs/handbook/tsconfig-json.html, it says __By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible__, and it also says __Specify "types": [] to disable automatic inclusion of @types packages.__.

## Search Terms

csstypes

## Suggestion

I think if a user explicitly excludes any folders/files using `"exclude"` in tsconfig-examples.json, then if the exclusions include the visible “@types” packages, then it shouldn't compile them, or alternatively it should provide a suggestion to the user in the error message recommending them to update their tsconfig.json file by either setting `compilerOptions.moduleResolution: "node"` or `compilerOptions.types: []`, and possibly even a link to the relevant docs

**Related Issues:**

https://stackoverflow.com/questions/49701735/cannot-find-module-csstype

**Comment by RyanCavanaugh** [comment]
This is a common confusion; `exclude` is *only* a filter on `include` and does not have other effects.

**Comment by orta** [comment]
This is pretty explicit in the new docs: https://www.staging-typescript.org/tsconfig#exclude
