### ISSUE TITLE
Different behavior between arrow function declaration and normal function declaration inside interface

### ISSUE THREAD

**Issue by SpringNyan** [microsoft/TypeScript#39587]
**TypeScript Version:**  4.0.0-beta

**Search Terms:** function interface

**Code**

```ts
interface A {
  test(obj: unknown): unknown;
}

interface B {
  test: (obj: unknown) => unknown;
}

const a: A = { test: (obj: string) => obj }; // ok?
const b: B = { test: (obj: string) => obj }; // error

const c: A['test'] = (obj: string) => obj; // ok?
const d: B['test'] = (obj: string) => obj; // error
const e: { (obj: unknown): unknown } = (obj: string) => obj; // error
const f: (obj: unknown) => unknown = (obj: string) => obj; // error

```

**Expected behavior:**
`a` and `c` should be error

**Actual behavior:**
`a` and `c` are allowed

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ts=4.0.0-beta#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzmQDOYAFAPYBGAVgFzICuIA1iGQO4gCUdjL7IAblwBfXLlCRYiFACFMufETB1y1Hs1YdOyALwA+Bhv5CconLgRkQxZHDrodmAhGIrKtZMSigA5tv3I7sjCAsgA9GGBTAD8FlY2FHRyjhjOrsiqHl6+-gZBIeGR0FBkUGI4ltZgyAj2ANoA5EoNALq6Ge502SB+unnUoRFRsRXx1QAmSY3NbY6ZXWDePbmBA4XIxaVxVRt0qfOGfFrqRyDB7QfdvQHug0VQJWWjOzBuaoeaXH0f-Bednosct9butNk8gA

**Related Issues:**

**Comment by MartinJohns** [comment]
Duplicate of #35572.

**Comment by RyanCavanaugh** [comment]
This is in the FAQ

![image](https://user-images.githubusercontent.com/6685088/87338068-61818380-c4f9-11ea-8afb-47ebfb775ea7.png)

**Comment by SpringNyan** [comment]
Got it. Thanks for the reply.
