### ISSUE TITLE
Type narrowing doesn't work when using variables inside brackets property accessors 

### ISSUE THREAD

**Issue by echamudi** [microsoft/TypeScript#39586]
**TypeScript Version:**  3.9.2

**Search Terms:** type narrowing, type guard, control flow analysis 

**Code**

```ts
const students: Record<number, {name: string | null, age: number}> = {
    1: { name: 'John', age: 5},
    2: { name: 'Joseph', age: 6},
    3: { name: null, age: 6},
};

if (typeof students[5]?.name === 'string') {
    students[5].name; // The type of name is string, correct ✅
}

const id = 5; // Type of id is 5

if (typeof students[id]?.name === 'string') {
    students[id].name; // The type of name is (string | null) 🤔
}
```

**Expected behavior:** The type of `students[id].name` inside the body of the second if statement should be `string`, without `null`.

**Actual behavior:** The type of `students[id].name` inside the body of the second if statement is `string | null`.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=16&pc=1#code/MYewdgzgLgBNCuATApmKEBcMBKzQCdEAeMeAWwCNl8AaGAbzAEMzktp8BLMAcxgB8YpADbC6THmyHkq+AL4A+GAF4GAKBiaYARiz0hLKQHIAUiAAWYI+MlYArHJoatAJj0HWWUyAjIADubWMBJSAGyOzpoAzO7MntKiNmERcgDcamqcAGYwABRQAJ5+yCA5CChoEADadgC6APwAdHHIKsqqRhzcPEYAlOpacFBIqOg1tc2GqTAA9DMwACrmrYXFMKUerZwQQ1y8dAT4eLCAoORqchmgkLCciCowdtNzi0WtG7cw2w8Z2XmrJWVhhUxrcGpNWG0Ol1eH0BlpyqNqqDwcgnvMlitXusci1PjtctC+IIRMJ+oA+DcAKLvnNRAA)

**Related Issues:**
Maybe related? https://github.com/microsoft/TypeScript/issues/9998

**Comment by MartinJohns** [comment]
Duplicate #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.
