### ISSUE TITLE
Custom type definition not included in compilation process

### ISSUE THREAD

**Issue by FawzyMokhtar** [microsoft/TypeScript#39581]
**TypeScript Version:**  3.9.6
**Node.js Version:**  12.18.2

**Search Terms:** The typescript compiler can't find the custom type definition.

**Problem:** I'm using **typescript** in **node.js** project and i'm trying to add a custom `user` property in the `Express.Request` interface, my custom type is defined in `./src/typings/express.d.ts` file.

**The tsconfig.json**

```json
{
    "compilerOptions": {             
      "target": "ES2015" ,
      "module": "commonjs" ,
      "outDir": "./build" ,
      "rootDir": "./src" ,
      "strict": true ,
      "moduleResolution": "node" ,
      "typeRoots": ["src/typings/", "node_modules/@types/"] ,
      "esModuleInterop": true ,
      "forceConsistentCasingInFileNames": true,
      "resolveJsonModule": true 
    }
}
```

**The src/typings/express.d.ts**

```ts
declare namespace Express {

  export interface Request {
    /**
     * Gets or sets the user that owns the current http request.
     */
    user: {
      /**
       * Gets or sets the id of the user.
       */
      userId: number;

      /**
       * Gets or sets the id of the user's company.
       */
      companyId?: number;
    };
  }

  export interface Response {
    /**
     * Gets or sets the user that owns the current http request.
     */
    user: {
      /**
       * Gets or sets the id of the user.
       */
      userId: number;

      /**
       * Gets or sets the id of the user's company.
       */
      companyId?: number;
    };
  }
}
```

**Trying to use the added user property**

```ts
export async function Authenticate(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const jwt = await JWT.verifyAndDecode(req.headers.authorization ?? '');

    if (jwt) {
      req.user = {
        userId: jwt.userId,
      };
      next();
    } else {
      UnAuthenticated(res);
    }
  } catch (error) {
    InternalServerError(res, error);
  }
}
```
**Expected behavior:** It should work.

**Actual behavior:**
- The editor is not showing any errors.
- The **tsc** still output this error :
TSError: ⨯ Unable to compile TypeScript:
src/shared/middleware/auth.middleware.ts:15:11 - error TS2339: Property 'user' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs>'.

15       req.user = {
             ~~~~

**Comment by FawzyMokhtar** [comment]
Adding the definition under the following folder structure **solves** the problem for me:
```
├── src
│   ├── app.ts
│   └── typings
│       └── global
│           └── index.d.ts
├── tsconfig.json
```
This makes custom definition available in the `global` module.

**Comment by leonnardovv** [comment]
> Adding the definition under the following folder structure **solves** the problem for me:
> 
> ```
> ├── src
> │   ├── app.ts
> │   └── typings
> │       └── global
> │           └── index.d.ts
> ├── tsconfig.json
> ```
> 
> This makes custom definition available in the `global` module.

@FawzyMokhtar been looking for this for hours, thanks!

**Comment by hatemjaber** [comment]
This seems to work for me as well. I'm a little confused about putting this in the src directory. I was under the impression that this should be outside the src so that it's not compiled with the rest of the code. I'm asking just to grow my TS knowledge, if you can provide a link or an explanation I would greatly appreciate it.
