### ISSUE TITLE
Overzealous deprecation warnings for no apparent reason

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#39590]
**TypeScript Version:**  4.0.0-dev.20200709

**Search Terms:** jsdoc deprecated

**Code**

I saw this while working in the TypeScript codebase in VSCode:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3902892/87335032-7ad40100-c4f4-11ea-8806-a404108b2442.png)

**Expected behavior:**

Nothing crossed out

**Actual behavior:**

Everything crossed out

**Comment by MartinJohns** [comment]
Related: #39542

**Comment by Kingwl** [comment]
Holy shit.
I'd like to take a look
