### ISSUE TITLE
Overloading functions in TypeScript

### ISSUE THREAD

**Issue by ekr3peeK** [microsoft/TypeScript#39609]
**TypeScript Version:**  4.0.0-beta

**Search Terms:** overloading

**Expected behavior:** TypeScript should accept my function invocation with 2 parameters, as I defined a function signature with 2 parameters also.

**Actual behavior:** TypeScript complains about the invocation, that it should not receive a second parameter.

**Code**
```ts
function test(arg1: string): void;
function test(arg1: string, arg2?: string): void {
    console.log(arg1);
}

test('bu', 'bu');
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function test(arg1, arg2) {
    console.log(arg1);
}
test('bu', 'bu');

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=4.0.0-beta&ssl=4&ssc=2&pln=2&pc=1#code/GYVwdgxgLglg9mABFApgZygCgIYCcDmAjAFyIa4xj4CUpAbnDACYDcAUKJLAsulnkVLlK+ADSIBAJgD8QqBSq1EDZogDebRFsQQEaOABsUAOgNx8OAoWrsAvmzaoMmAOQAjEC-HvPNoA)

**Comment by artu-ole** [comment]
You don't need first type at all as second type describes a superset of functions described by first type.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error
