### ISSUE TITLE
Type narrowing failed when accessing property of this

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#39616]
**TypeScript Version:**  4.0.0-dev.20200712

**Search Terms:**
type guard narrow this property access
**Code**

```ts
class Foo {
  bar: string | number;

  a(arg: Foo['bar']) {
    if (typeof arg === 'number') {
    } else {
      arg.substr(0); // OK! arg is string.
    }
  }

  b(arg: this['bar'] /* replace "Foo" with "this" here. */) { 
    if (typeof arg === 'number') {
    } else {
      arg.substr(0); // Error! arg should be narrowed to string but failed.
    }
  }
}
```

**Playground Link:** 
https://www.typescriptlang.org/play/?strictPropertyInitialization=false&ssl=2&ssc=23&pln=2&pc=24#code/MYGwhgzhAEBiD29oG8BQ1oCMwCcBc0EALjgJYB2A5tAD7TkCuAtpgKY4Dcq60YAFLkoEE8ANoBybDnEBdAJQoeGUgDNofIgE8ADq3hrB0ALwno4xi3biFaDBgC+0ViAitFdu4IB0EBpmI4fAAMchzQAPTh0ADyANIAhLw41KQwARSUXkrQ9jy5PJgCyQREABapElKyEQBU0Dis2uDAbgBEIq3QAO6kZdCtZamdpeysXtA14TbQ2arqWrr6SdQmRmYWbNI22Y7Oru4eyz5+AcGhEVEAojg48DiJhhCl8AwgACZYbuS4t12sH0QkOkqFgGERoCowKQQP8sh5cg5UPYgA
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate https://github.com/microsoft/TypeScript/issues/33014
