### ISSUE TITLE
Unable to overload arrow function in module augmentation

### ISSUE THREAD

**Issue by dotansimha** [microsoft/TypeScript#39622]
I'm trying to overload an existing arrow function in a module, exported as `const`. It works perfectly fine with overrides for function, class and interface, but failing for arrow function declared as `const`. 

Also tried with:

```
    export interface myVar {
        (param: number): number
    }
```

It works, but then the arrow function become unusable because it treats it as `interface` and it's not callable.

**TypeScript Version:**  3.9.2

**Search Terms:** const, module augmentation, declaration merging, overload, block-scope variable

**Expected behavior:**

Allow to override block-scoped variables if it's referring to an arrow function. Just like a `function`.

**Actual behavior:**

```
Cannot redeclare block-scoped variable 'myVar'.(2451)
```

**Related Issues:**
- https://github.com/microsoft/TypeScript/issues/18163 (maybe related) 

**Code**
```ts
declare module 'test' {
    // export function works
    export function myFunc(param: string): string;

    // export const doesn't work
    export const myVar: (param: string) => string;
}

declare module 'test' {
    export function myFunc(param: number): number;
    export const myVar: (param: number) => number;
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=2#code/CYUwxgNghgTiAEBbA9sArhBByALiAzjlvAN4CwAUPNfAPS3wgAeADsjDvAGZoB2YOAJbJe8AO7sA1vko1Grdpx78hIpAE8AYnzAAKFrCiIAXPEIxBvAOYBKU+ctWA3JVk168th3hgRheMDIBLy44lJu1MxenL68-ojqAGqwpvqGJmY4FtY28AC8AHyZ2c6UAL6uFKCQsAgo6JjwuAREpBGeitw6qqIJ2vxpMEamvGiIAEYgMHbwoxNTLlQ0UZ2x8Ukp8IPDs2OT0-lFc-uLZUA)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `const`s are assumed to be in conflict but multiple `function` declarations adds new overloads.

**Comment by dotansimha** [comment]
@RyanCavanaugh But `const` that point to an arrow function is basically a function...

**Comment by orta** [comment]
The goal of that message (I assume) is to match runtime behavior where the `function` declaration  acts like var vs the `const` which never allow overriding:

```
❯ node
Welcome to Node.js v13.6.0.
Type ".help" for more information.
> function a() {}
undefined
> function a() {}
undefined

> const b = () => {}
undefined
> const b = () => {}
Uncaught SyntaxError: Identifier 'b' has already been declared
```
