### ISSUE TITLE
Comment vanishes during parse when next line has leading semicolon

### ISSUE THREAD

**Issue by wolfgang42** [microsoft/TypeScript#39620]
**TypeScript Version:**  4.0.0-dev.20200715

**Search Terms:** `comment semicolon`

**Code**

```ts
import * as ts from 'typescript'
// This comment is not lost
import * as fs from 'fs'
// THIS COMMENT IS LOST
// (but not if you remove the semicolon at the start of the next line, or add one on the line above)
;fs.readFile(__filename, 'ascii', (err, text) => {
	// This comment is not lost
	if (err) throw err
	const sourceFile = ts.createSourceFile(__filename, text, ts.ScriptTarget.ES2015, true, ts.ScriptKind.TS)
	console.log(ts.createPrinter().printNode(ts.EmitHint.Unspecified, sourceFile, sourceFile))
})
```
(There’s no good reason for the leading semicolon in this demo; the original had an IIFE there which therefore had a leading semicolon to prevent it from being interpreted as a call to the previous expresssion.)

**Expected behavior:**
Program should be pretty-printed with all comments:
```ts
import * as ts from 'typescript';
// This comment is not lost
import * as fs from 'fs';
// THIS COMMENT IS LOST
// (but not if you remove the semicolon at the start of the next line, or add one on the line above)
fs.readFile(__filename, 'ascii', (err, text) => {
    // This comment is not lost
    if (err)
        throw err;
    const sourceFile = ts.createSourceFile(__filename, text, ts.ScriptTarget.ES2015, true, ts.ScriptKind.TS);
    console.log(ts.createPrinter().printNode(ts.EmitHint.Unspecified, sourceFile, sourceFile));
});
```

**Actual behavior:** Comment below import statements disappears when pretty-printed.

**Related Issues:** #17665 describes a vaguely similar bug where a comment was getting swallowed into a previous statement due to ASI.

**Comment by RyanCavanaugh** [comment]
Comment preservation is "best effort" and you may lose comments during emit if they end up being attached to a token rather than a node. Do not rely on comments do be reprinted in every possible syntactic position; this is not an invariant of TS's emit process.

**Comment by wolfgang42** [comment]
Good to know. Can you point me to where I’d find out what positions in the AST are acceptable for a comment to be emitted?

In particular, will the output of `printNode` always contain comments only in positions where they will be preserved if the result is reparsed and emitted again? (i.e., is a `createSourceFile()` → `printNode()` cycle idempotent?)

**Comment by RyanCavanaugh** [comment]
There are no guarantees per se, but you can be reasonably confident that any comments directly preceding a declaration will be preserved, since this is a big use case for .d.ts generation.

> In particular, will the output of printNode always contain comments only in positions where they will be preserved if the result is reparsed and emitted again? (i.e., is a createSourceFile() → printNode() cycle idempotent?)

Honestly, I don't know. Probably?

**Comment by wolfgang42** [comment]
> I don't know. Probably?

LOL, fair. I guess that's good enough for the experiment I'm doing, though it sounds like I probably shouldn't rely on it for production. Thanks for the info!
