### ISSUE TITLE
Type inference overrides the type of a variable

### ISSUE THREAD

**Issue by cwohlman** [microsoft/TypeScript#39626]
**TypeScript Version:**  3.9.2 (also tested and got the error on Nightly on the Typescript Playground)

**Search Terms:**
 inferred vs declared type
type inference overrides declaration
type doesn't match declaration 

**Code**

```ts
type Thing = { a: string }
let thing: Thing | null = null

foo(() => { 
    thing = { a: 'hi' }
});

if (thing) { // <-- intelisense reports the type of 'thing' to be 'null'
    // Error: Property 'a' does not exist on type 'never'.(2339)
    // Expected: should be fine
    console.log(thing.a);  // <-- intelisense reports the type of 'thing' to be 'never'
}

function foo(cb: Function) { cb() }
```

**Expected behavior:** Should compile fine

**Actual behavior:** Got the error: `Error: Property 'a' does not exist on type 'never'.(2339)`

**Playground Link:** https://www.typescriptlang.org/play/?ssl=12&ssc=35&pln=1&pc=1#code/C4TwDgpgBAKgFgSwHYHMoF4oG8oEMBcUAzsAE7JoC+AUADYTBTCKqHwVQA+USArrbQw9+tatQBmAe0kAKGQEoMAPmxRqUDUxZpMOAlADkiA1BqV5AbjEJxUGcwqKs6zQGNJSIpPoA6WpJR7bR9cS2oaCV4kV2AEDygpWVcAI0IAMSiYuKQnKBSFSiA

**Related Issues:**

These had to do with type inference and came up in my search, though I'm not sure they're related:

https://github.com/microsoft/TypeScript/issues/33738
https://github.com/microsoft/TypeScript/issues/38700

<details><summary><b>Output</b></summary>

```ts
"use strict";
let thing = null;
foo(() => {
    thing = { a: 'hi' };
});
if (thing) {
    console.log(thing.a);
}
function foo(cb) { cb(); }

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Comment by IllusionMH** [comment]
Looks like part of #9998

**Comment by cwohlman** [comment]
Yeah, I agree. I'll close this issue.

**Comment by cwohlman** [comment]
@IllusionMH looks like #9998 is coming up a lot, do you know if there are any plans to address it?

**Comment by IllusionMH** [comment]
I have no answer for this question because I'm not part of the team.

Personally I see this issue as some kind of documentation of current behavior and reasons, trade-off of it and alternatives, and couple of workaround in comments.

Not sure if there are some obvious action items that have worthy trade-offs at this moment.

**Comment by RyanCavanaugh** [comment]
👆
