### ISSUE TITLE
TypeScript is adding trailing "_1" to a variable, but not at it's declaration

### ISSUE THREAD

**Issue by gulamsounov** [microsoft/TypeScript#39625]
**TypeScript Version:**  Version 3.9.6

**Code (before compilation)**

```ts
function loadData(): Promise<string> {
    return new Promise((resolve, reject) => {
        reject('My error')
    })
}

async function testData() {
    try {
        await loadData()
    } catch (err) {
        console.log(err)
    }
}

testData()
```

**Code (after compilation, fragment)**
```ts
function testData() {
    return __awaiter(this, void 0, void 0, function () {
        var err_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    _a.trys.push([0, 2, , 3]);
                    return [4 /*yield*/, loadData()];
                case 1:
                    _a.sent();
                    return [3 /*break*/, 3];
                case 2:
                    err_1 = _a.sent();
                    console.log(err_1);
                    return [3 /*break*/, 3];
                case 3: return [2 /*return*/];
            }
        });
    });
}
```
Why the variable 'err' -> 'err_1'? 

This causes an Error in VS Code:

![error](https://user-images.githubusercontent.com/22195929/87666375-8edc6480-c779-11ea-8c6d-7ceba09d8089.png)

If you remove async/wait then everything is fine

PS: Sorry for my english

**Comment by gulamsounov** [comment]
If you remove async/wait then everything is fine

**Comment by IllusionMH** [comment]
This is current behavior of debuggers with compiled code - they execute your expression `err` as is without consideration that this should match name of variable from original source.
See issue related to names of variables in scope variables view https://bugs.chromium.org/p/chromium/issues/detail?id=327092

You'll have same results with debug of minified/bundled code or with  ES2015+ code compiled to ES5 with Babel.
