### ISSUE TITLE
Allow transformation of imported files

### ISSUE THREAD

**Issue by AndrewLeedham** [microsoft/TypeScript#39634]
## Search Terms

- ts-transformer
- transform imported files
- isExternalModule
- isSourceFile

## Suggestion

The ability for a transformer to modify imported files which are not in the project as a `SourceFile`.

## Use Cases

I am using `@wessberg/rollup-plugin-ts` to bundle declaration files, I want to add a React style import to each of my files, but when treating a import as `"external"` via the rollup API the `SourceFile` is not included in the TS project, meaning I can no longer transform it.

I created a minimal repro to show this exact use case: https://repl.it/@AndrewLeedham56/rollup-plugin-ts-external-repro#transformer.js

## Examples

This would likely need to be opt-in as it would traverse all node_modules when enabled. Using my use case above, perhaps it could look something like this:
```javascript
import * as ts from "typescript";

function sourceVisitor(context, sourceFile) {
  const visitor = (node) => {
    if (ts.isSourceFile(node) || ts.isImportFile(node)) {
      const importStatement = ts.createImportDeclaration(
        undefined,
        undefined,
        ts.createImportClause(ts.createIdentifier("createElement"), undefined),
        ts.createLiteral("vhtml")
      );
      return ts.updateSourceFileNode(node, [
        importStatement,
        ...node.statements,
      ]);
    }
    return ts.visitEachChild(node, visitor, context);
  };
  return ts.visitNode(sourceFile, visitor, undefined, undefined, true);
}

export default function transform() {
  return (context) => {
    return (sourceFile) =>
      sourceVisitor(context, sourceFile);
  };
}
```

Where `ts.visitNode` would have a 5th option which enables the import traversal, perhaps it could even be a filter so the traversal can be scoped, and then some way to check if we are in an imported file as apposed to a SourceFile shown here with `ts.isImportFile(node)`.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Context
- [@wessberg/rollup-plugin-ts](https://github.com/wessberg/rollup-plugin-ts)
- [@wessberg/rollup-plugin-ts Issue](https://github.com/wessberg/rollup-plugin-ts/issues/102)
- [Stackoverflow question](https://stackoverflow.com/questions/62838264/typescript-transformers-transform-imported-file)
- [Minimal repro](https://repl.it/@AndrewLeedham56/rollup-plugin-ts-external-repro#transformer.js)

**Comment by AndrewLeedham** [comment]
I don't think my `visitNode` would work actually, since I don't believe imported files would be child nodes, they would be separate `SoureFile` objects.

Perhaps instead there could be a flag for transformers where the `(sourceFile) => visitor` callback is called for all source files that can be retrieved from `program.getSourceFiles`, then they could be filtered with `program.isSourceFileFromExternalLibrary` and `program.isSourceFileDefaultLibrary`.

**Comment by DanielRosenwasser** [comment]
> I don't think my `visitNode` would work actually, since I don't believe imported files would be child nodes, they would be separate `SoureFile` objects.

Yes - this is the thing. You wouldn't be able to do anything once the file is transformed. Rollup presumably needs to act on the result file, but you're telling it not to process anything. I think you'd be better-served by some sort of build orchestrator that acts on your `external`s exactly once. You'll see a much faster build every time.

**Comment by AndrewLeedham** [comment]
@DanielRosenwasser The reason I am trying to do this via TS transformers and not rollup is so TS is aware of the typings change, so with TSX it knows the export should be `JSX.Element`. I am not sure I see a way of doing that outside of TS?

**Comment by wessberg** [comment]
@AndrewLeedham

> The reason I am trying to do this via TS transformers and not rollup is so TS is aware of the typings change, so with TSX it knows the export should be JSX.Element. I am not sure I see a way of doing that outside of TS?

Just FYI: TypeScript Custom Transformers can be a bit surprising in that they run during the emit phase and as such any transformations applied in a `before` transformer won't actually have an impact on the declarations that will be generated by TypeScript. For example, you may intuitively expect that, say, renaming a `ClassDeclaration` from "Foo" to "Bar" would carry over to the declarations, but since the type checking phase is decoupled from the emit phase in TypeScript, it won't. Instead, if you want to transform the declarations with the Compiler APIs, you can use the `afterDeclarations` transformer hook as part of your Custom Transformer logic. With the beforementioned example, that would mean that you'd have to use the `updateClassDeclaration` method of the `NodeFactory` API and provide a new name to the `ClassDeclaration` while transforming declarations in an `afterDeclarations` hook.

**Comment by AndrewLeedham** [comment]
I found a workaround, which I outlined in https://github.com/wessberg/rollup-plugin-ts/issues/102. It seems this behaviour is not really possible given how TS works.
