### ISSUE TITLE
Could not find declaration when path mapping the root dir

### ISSUE THREAD

**Issue by tobi97h** [microsoft/TypeScript#39639]
root/
1.  test.ts
2.  func.ts

tsconfig.json
`"baseUrl": ".",
    "paths": {
     "/*": ["./*"]
    },`

if i do `import func from "/func"` or `import func from "func.js"` in my test.ts everything works fine. However if i do `import func "/func.js"` i suddenly get `Could not find a declaration file for module ... implicitly has an 'any' type.`

Thanks in advance

**Comment by matsuaki-jp** [comment]
When importing a .js file, if the type definition file (d.ts) does not exist, it is implicitly set to any treatment.

If you set "noImplicitAny" to true in tsconfig.json, you get a compile error.

If you do not change this tsconfig.json, create a definition file with the same file name (test.d.ts) .

You can compile in a terminal to generate a definition file as well, with 

`tsc test.ts -d 
`

I hope your program works well!

**Comment by tobi97h** [comment]
my func.ts file is already a typescript file. It would seem redundant to create an extra definition file for it.

even if i do it though and now i have the following files in my root directory:

test.ts
func.ts
func.d.ts
func.js

doing `import func from "/func.js"` still yields the same error.

setting or unsetting no implicit any doesnt seem to do anything in my case.

Thanks again!

**Comment by matsuaki-jp** [comment]
Sorry. I misunderstood the problem.

The cause of this error is the file position of the require statement after the transpile is not correct.

The require("/func") after the transpile searches for the system root, so my In the local environment, the compile error is solved by placing the func.ts file directly under the D drive. done.

The solution is to change the file notation to a relative path (./func) from func.ts, 

or you need to fix it with webpack or module-alias, where path conversion does not exist in Typescript.

Please see #35351 and #10866.

Thank you!
