### ISSUE TITLE
Broken inference of empty object as Record

### ISSUE THREAD

**Issue by javiertury** [microsoft/TypeScript#39630]
**TypeScript Version:**  3.9.7

**Search Terms:** empty object, broken inference, Record

**Code**

```ts
export class Bar <
  Key extends string,
  Value extends string
> {
  get foo (): Record<Key, Value> {
    return {}; // [tsserver 2322] [E] Type '{}' is not assignable to type 'Record<Key, Value>'.
  }
}
```

**Expected behavior:**

The empty object type should be inferred as `Record<Key, Value>`

**Actual behavior:**

```
[tsserver 2322] [E] Type '{}' is not assignable to type 'Record<Key, Value>'.
```

**Playground Link:** 

https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAYwDYEMDOa4CEVTgHgCg44BpYATzlBmADsATTNGKASzoHMAaYuANRRIArsGohajZqw6dCAPjgBvPp2DwAZhAhwAFAEoAXHABKwBNAb5yFbgKGjFKkiSjrhUOsoC+Abj7ehN5AA

I used the default version in the playground because the nightly version is completely broken and very slow.

```
Cannot find name 'Record'.(2304)
Return type of public getter 'foo' from exported class has or is using private name 'Record'.(4043)
```

**Related Issues:** 

This problem is similar but not equal to #14930

**Comment by RyanCavanaugh** [comment]
This is a correct error.
```ts
export class Bar <
  Key extends string,
  Value extends string
> {
  get foo (): Record<Key, Value> {
    return {}; // [tsserver 2322] [E] Type '{}' is not assignable to type 'Record<Key, Value>'.
  }
}
const k = new Bar<"bla", "baz">();
// No error, crashes
k.foo.bla.toLowerCase();
```

**Comment by javiertury** [comment]
I thought Record didn't require the property to be defined, like this:

```
type Foo = Record<string, string>;
const foo: Foo = {}; // Ok
```

But investigating further I see that you are right and this is the expected behavior when the key is a string literal union. Thank you.
