### ISSUE TITLE
Incorrect type inference with bracket accessor and return object type

### ISSUE THREAD

**Issue by dislido** [microsoft/TypeScript#39659]
**TypeScript Version:**  3.9.7

**Search Terms:** 

**Code**

```ts
const objOrClass = {
  culprit() { return {} }, // returns object, if remove this, type inference will be correct

  async async() {},
  num() { return 1 },
  str() { return '' },
}

async function test(key: 'culprit' | 'async' | 'num' | 'str') {
  // result inferred to `{}`，should be `{} | Promise<void> | number | string`
  const result = objOrClass[key]();
  console.log(result);
}

test('culprit');

```

**Playground Link:**  
[![Edit charming-borg-qg77o](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-borg-qg77o?fontsize=14&hidenavigation=1&theme=dark)
**Related Issues:**

**Comment by MartinJohns** [comment]
> // result inferred to `{}`，should be `{} | Promise<void> | number | string`

Well, it is inferred as that. Then it's simplified to `{}`, because that covers all the possible types. It's the same behavior as `number | 1` being simplified to `number`.

**Comment by dislido** [comment]
> > // result inferred to `{}`，should be `{} | Promise<void> | number | string`
> 
> Well, it is inferred as that. Then it's simplified to `{}`, because that covers all the possible types. It's the same behavior as `number | 1` being simplified to `number`.

if I await the result, the editor will report a message `'await' has no effect on the type of this expression.ts(80007)` ，but it could  be `Promise<void>` type
![image](https://user-images.githubusercontent.com/25094788/87871326-f8f74280-c9e1-11ea-962d-3f01d2ad0efc.png)

**Comment by RyanCavanaugh** [comment]
The suggestion is just a suggestion; you can ignore it or what have you. Fundamentally the code is not 'safe' as there is nothing in the type system preventing this substitution:
```ts
const objOrClass = {
  culprit(): {} {
    const obj = { then: () => console.log('oop') };
    return obj;
  }, // returns object, if remove this, type inference will be correct

  async async() {},
  num() { return 1 },
  str() { return '' },
}

async function test(key: 'culprit' | 'async' | 'num' | 'str') {
  const result = await objOrClass[key]();
  console.log(result);
}
```
