### ISSUE TITLE
deprecated wrongly applies to overloaded function

### ISSUE THREAD

**Issue by proteriax** [microsoft/TypeScript#39651]
**TypeScript Version:**  4.0.0-beta

**Search Terms:** overload, deprecated

**Code**

```ts
location.reload()
```

**lib.dom.d.ts**
```ts
// Line 9768
interface Location {
    /**
     * Reloads the current page.
     */
    reload(): void;
    /** @deprecated */
    reload(forcedReload: boolean): void;
}
```

**Expected behavior:**
No deprecation warning.

**Actual behavior:**
'reload' is deprecated(6385)

**Playground Link:** [Link](https://www.typescriptlang.org/play/index.html?ts=4.0.0-beta&ssl=1&ssc=1&pln=1&pc=18#code/DYewxghgLgliB2A6ATgU1BAJgCgJRA)

**Related Issues:** None.

**Comment by IllusionMH** [comment]
Looks like already fixed in Nightly builds. [Playground](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200703#code/DYewxghgLgliB2A6ATgU1BAJgCgJQG4BYAKBNElgRXRC2ymQFdUCg)
