### ISSUE TITLE
WebGL extensions typings not available

### ISSUE THREAD

**Issue by ShukantPal** [microsoft/TypeScript#39655]
I see that a few WebGL extension typings are missing from the `libdom.d.ts` file:

* WEBGL_compressed_texture_pvrtc
* WEBGL_compressed_texture_etc1
* WEBGL_compressed_texture_atc

I can make a PR if you can point me where these typings are supposed to be put.

**Comment by ShuiRuTian** [comment]
Hi, dude.
thanks for the enthusiasm, but it might not be that easy(as far as I'm concerned).
let me explain:

libdom.d.ts is generated through using the files in this https://github.com/microsoft/TypeScript/tree/c779fc7998e6c01c26fa0db284647118f154137b/src/lib.
And I am not sure where these WEBGL should be put,  but I see similar property `WEBGL_compressed_texture_astc` in dom.generated.d.ts. This `generated` suffix means you need goto https://github.com/Microsoft/TSJS-lib-generator.

This generator project would use webidl to produce types automatically. And it has detailed manual.
(I think search some existing similar property would help, like WEBGL_compressed_texture_astc?)

Are you still interested in it?

**Comment by SukantPal** [comment]
@ShuiRuTian Yes, thanks for pointing me to where I should go.

**Comment by SuperSodaSea** [comment]
- **WEBGL_compressed_texture_etc1**: Added a long time ago.
- **WEBGL_compressed_texture_pvrtc**: I recently added it back in microsoft/TypeScript-DOM-lib-generator#1484.
- **WEBGL_compressed_texture_atc**: It was rejected by Khronos so there is no need to add it.

So in my opinion, the issue has been solved and can be closed now.
