### ISSUE TITLE
The static side of subclasses should not be restricted by the static side signature of superclasses

### ISSUE THREAD

**Issue by yw662** [microsoft/TypeScript#39665]
**TypeScript Version:**  4.0.0-beta

**Search Terms:**
ts2417, "static side incorrectly extends"

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
class base {
    static foo(v: string) { }
}

class sub extends base {
    static foo(v: number) { }
}

```

**Expected behavior:**
It should pass.
**Actual behavior:**
It raised 2417: Class static side 'typeof sub' incorrectly extends base class static side 'typeof base'.

However static functions are never considered "inherited" or "same". `base.foo` and `sub.foo` are totally different. Many other languages also allow this behavior.
**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.0.0-beta

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #4628
