### ISSUE TITLE
"Solution Style" tsconfig causes VS Code Typescript language service to break

### ISSUE THREAD

**Issue by seangwright** [microsoft/TypeScript#39666]
**TypeScript Version:** 

`"typescript": "3.9.7"`

**Search Terms:**

"Solution Style" tsconfig
VS Code Typescript import intellisense failure

**Code**

https://github.com/seangwright/ng10-0-3-typescript-issue

**Expected behavior:**

Using "Solution Style" `tsconfig.json` in VS Code keeps standard code fixes for imports.

**Actual behavior:**

Code fixes for imports are completely broken.

The below repository was created with a new Angular 10.0.3 project without any Typescript customizations or VS Code settings.

**Playground Link:** 

https://github.com/seangwright/ng10-0-3-typescript-issue

Steps:
- `npm i -g @angular/cli@latest`
- `ng new ng103 --skip-git`
- `cd ng103`
- `code .` 
  - Open in VS Code (1.47.2)
- Open `src/app/app.module.ts`
- Remove line 5: `import { AppComponent } from './app.component';`
- Try to use `ctrl + .` code action / fix to add the import statement for `AppComponent`
  - __this fails__ and instead recommends `Add 'const' to unresolved variable`

![Annotation 2020-07-19 210707](https://user-images.githubusercontent.com/1382768/87890335-0f15fa80-ca04-11ea-95bc-5cf3ff122e8d.jpg)

- Navigate to `src/app/app.component`
- Try to use `ctrl + .` code action / fix to add the import statement for `TestService`
  - __this fails__ and instead shows `No code actions available`

![Annotation 2020-07-19 210817](https://user-images.githubusercontent.com/1382768/87890337-13daae80-ca04-11ea-9bff-4bb8c0d81167.jpg)

Now checkout branch `fix/standard-tsconfig` and try the above two steps to reproduce the issue and you will see the issue is __gone__.

All that is different between `master` and `fix/standard-tsconfig` is that `master` uses a "Solution Style" `tsconfig.json` and `fix/standard-tsconfig` uses the normal `tsconfig.json`.

**Related Issues:** 

Both of these were closed but I'm experiencing the exact same issue:
https://github.com/microsoft/TypeScript/issues/39411
https://github.com/microsoft/vscode/issues/101696

This one is open but doesn't include the same visual details/simple reproduction:
https://github.com/microsoft/TypeScript/issues/39632

I've tried reproducing this with VS Code 1.47.2 and Angular 10 and Typescript 10.8.3 (which means I'm not using "Solution Style" `tsconfig.json` and I __cannot_ reproduce the issue.

This problem seems to be specific to "Solution Style" `tsconfig.json`.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/39632

**Comment by seangwright** [comment]
Closing as a duplicate.
