### ISSUE TITLE
declaration files exclude scope from <reference types> output

### ISSUE THREAD

**Issue by Validark** [microsoft/TypeScript#39668]
**TypeScript Version:**  4.0.0-dev.20200719

**Code**

To reproduce in one command, run the following on the command line: (assuming `tsc` and `npx` are installed)
```
npx roblox-ts --init package && echo "export function f(k: keyof Instances) {}" > src/index.ts && tsc
```

Alternatively, create a new folder with the following contents:

tsconfig.json:
```json
{
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"isolatedModules": false,
		"downlevelIteration": true,
		"module": "commonjs",
		"noLib": true,
		"strict": true,
		"target": "es6",
		"typeRoots": [ "node_modules/@rbxts" ],
		"rootDir": "src",
		"outDir": "out",
		"declaration": true,
		"jsx": "react",
		"jsxFactory": "Roact.createElement"
	}
}
```

package.json:
```json
{
  "name": "@rbxts/ts-repro",
  "version": "1.0.0",
  "description": "",
  "main": "out/init.lua",
  "scripts": {
    "prepublishOnly": "rbxtsc"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "publishConfig": {
    "access": "public"
  },
  "types": "out/index.d.ts",
  "devDependencies": {
    "@rbxts/types": "^1.0.383"
  }
}
```

src/index.ts:
```ts
export function f(k: keyof Instances) {}
```

Then, run:
```
npm install
tsc
```

**Expected behavior:**
I want this .d.ts file:
```ts
/// <reference types="@rbxts/types" />
export declare function f(k: keyof Instances): void;
```
![](https://user-images.githubusercontent.com/15217173/87898870-04b02c80-ca15-11ea-9a4e-9c10426b08e8.png)

**Actual behavior:**
It outputs this .d.ts file:
```ts
/// <reference types="types" />
export declare function f(k: keyof Instances): void;
```
![](https://user-images.githubusercontent.com/15217173/87898771-bdc23700-ca14-11ea-8ed2-370a757c3467.png)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior because you specified `node_modules/@rbxts` as a type root -- by the same token, we don't emit `/// <reference types="@types/somename" />` when `typesRoots` is the default `node_modules/@types`.
