### ISSUE TITLE
Default code action for unused function parameter (6133) in non-final position should not delete

### ISSUE THREAD

**Issue by midgleyc** [microsoft/TypeScript#39676]
**TypeScript Version:**  3.9.6

**Search Terms:**
6133, unused parameter, quick fix, code action, tsserver

**Code**

```ts
const express = require('express')
const unusedImport = require('fs')
const anotherUnusedImport = require('util')
const app = express()
const port = 3000

app.get('/', helloWorld)
app.get('/used', (req, res) => res.send('used'))

function helloWorld(unusedReq, res) {
    return res.send('Hello World!');
}

function unusedFunction() {
}

app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))
```

**Expected behavior:**

If I apply the code action "Delete all unused declarations" to "unusedImport", it, "anotherUnusedImport" and "unusedFunction" should be deleted, but nothing else.

**Actual behavior:**

The parameter "unusedReq" in helloWorld is also deleted, but the line `app.get('/', helloWorld)` is not modified.

The unread `req` parameter in `app.get('/used', (req, res) => res.send('used'))` is correctly not removed.

If I were to change the line to `app.get('/', (req, res, next) => helloWorld(req, res, next))` it would be adjusted correctly, but using the function directly with a changed parameter set changes the behaviour.

**Playground Link:** 

**Related Issues:**

**Comment by a-tarasyuk** [comment]
The `fixUnusedIdentifier` doesn't check where or how a function was used
https://github.com/microsoft/TypeScript/blob/87a3b42d7208b81023c91e3a5fda1723b0270843/src/services/codefixes/fixUnusedIdentifier.ts#L251-L252
I'm thinking about the following ways, however, not sure which way will be correct.
1. Forbid changing parameters in function declarations for _`fixAll`_ action
2. Try to find all references by the function name, if some of them used in a call expression then forbid remove unused parameters

cc @RyanCavanaugh @DanielRosenwasser
