### ISSUE TITLE
JSDoc: function with param or null

### ISSUE THREAD

**Issue by liangjiancang** [microsoft/TypeScript#39674]
Example:

```js
/**
 * @param {?((n: number) => void)} add - shows [ add: (n: number) => void ]
 * @param {?(() => void)} remove - shows [ remove: (() => void) | null) ]
 */
function example(add, remove) {
    add && add(1)
    remove && remove()
}
```

The first line should be `add: ((n: number) => void) | null`

**Comment by RyanCavanaugh** [comment]
You'd need to turn on `strictNullChecks` to see `null` represented here

**Comment by liangjiancang** [comment]
> You'd need to turn on `strictNullChecks` to see `null` represented here

But this is not a typescript project. I opened it from VS Code, which explain JSDoc by typescripe.
I tried to add tsconfig.json to the project, but VS Code obviously does not read it to explain the JSDoc.
So how to solve it?

See https://github.com/microsoft/vscode/issues/102925
