### ISSUE TITLE
Auto-import wrong for javascript project since tsserver 3.9.2

### ISSUE THREAD

**Issue by bstaletic** [microsoft/TypeScript#39677]
**TypeScript Version:**  3.9.2 and newer

**Search Terms:** diagnostics auto-import javascript

**Code**

- Project: https://github.com/ycm-core/ycmd/tree/master/ycmd/tests/javascript/testdata
- File: https://github.com/ycm-core/ycmd/blob/master/ycmd/tests/javascript/testdata/test.js

**Expected behavior:**

Completing `Bår` at the last line should insert `import { Bår } from "./unicode";`. This worked fine all throughout 3.8.x versions.

**Actual behavior:**

Version 3.9.2 (first stable 3.9.x) inserts `const { Bår } = require("./unicode");`.

To be honest, I don't know much about typescript. I'm a maintainer of a text editor plugin that uses tsserver. From what I can tell, the `const { Bår } = require("./unicode");` thing is not valid javascript. Please correct me if I am wrong.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
That line is valid JS.

The import syntax depends on your configuration, and you have the default module system `commonjs` as a result of the jsconfig file. You can set that to `module: "ES6"`` if you want ES6-style imports

**Comment by bstaletic** [comment]
Thanks for the quick response. That does answer my question, so I'll close this issue. Apologies for the noise.

**Comment by puremourning** [comment]
Isn't the problem here that the behaviour changed although we didn't change anything our side? i.e. the default behaviour of tsserver has changed through and upgrade? Was that intentional? How do we tell our users to expect this change?

**Comment by RyanCavanaugh** [comment]
It's a component for an interactive editing experience; its behavior changes all the time in ways designed to better match user expectation. No one should be hooking up their build system to a code action designed to fix in-situ errors.

**Comment by puremourning** [comment]
> designed to better match user expectation

OK so yes it was intentional that the default modules system selected is now commonjs rather than es modules? Fine, so long as that's what you guys expected :)

**Comment by RyanCavanaugh** [comment]
The default module system has always been CommonJS, but we were emitting ES module imports despite that fact

**Comment by puremourning** [comment]
Aaaah, I see. Thanks for clarifying :)
