### ISSUE TITLE
Generic inference from return type

### ISSUE THREAD

**Issue by idoros** [microsoft/TypeScript#39688]
**TypeScript Version:**  4.0.0-dev.20200715

**Search Terms:** generic inference

**Code**

```ts
interface Test<C> {
    title: string;
    test(context: C): unknown;
}
declare function suite<C>(setup: () => C, ...items: Test<C>[]): Test<C>;
declare function describe<PC, C extends PC>(setup: (context: PC) => C, ...items: Test<C>[]): Test<PC>;
declare function it<C>(title: string, test: (context: C) => unknown): Test<C>;

suite(
    () => ({
        a: 'param',
        b: 5
    }),
    it(``, ({a, b}) => {a.charAt(b)}), // <- generic works for first level
    it(``, () => {}),
    describe(
        ({a, b}) => ({a, b, c: true}),
        // it(``, ({a, c}) => {}) // <- uncomment to override generic ({a: any, c: any})
    )
);
```

**Expected behavior:**

Inference should work in the same way for `describe` as it works for `suite`.

**Actual behavior:**

Placing the `it` under the 2nd level triggers the inference in a different way. The difference between them is that in the `describe` signature the `PC` generic from the first level is used in the setup function - removing the `context: PC` from the setup function or just not using it in the actual setup will make both levels work the same.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=4.0.0-beta#code/JYOwLgpgTgZghgYwgAgCoQM5gDwGEB8yA3gFDLnJjBgA2EAXMllKAOYDcZFkWAFAgHtwEAB5hGuAJSMAriADWIAQHcQnAL4kAJhAQ04UFDDkIqQpjOoQ8+XhghgZAB0a9JyALyFcAGmQA6QKsAWwxGdCwbAG0AXWk0TBwCTh09AyMTMxBkHQwEFgAjawAFX2RcZFFIEC0MZFLbe0cXZH4hSDFGUvcvcr9A-xCwhMiCWPiInAaU3X1DZGMQU2BzahteKloGJjAWEFY-HnFWwWFO8p7COUUVEAnEm04SDEtIXi5yN09CXlIKf+QcEYAHInAY4MFgT4PgCCowAKww9SSaH-ai8AAGGL8vzgfgKyO+xDg-gQAAsDABBMC8AqSZF+AD0jOQ2AAtMhWBAQNBgAhkMoBFB5HUYEKFsAoFhkHQAG4QGgw9FYnGXYgMmG5fLAIrvAEUXH4wm9Q3IAp+BCMXYyCAa-XkZnIZXY1pEPHIBDGwhEQmO9nIEwCYLBblgSgCZACeVQFg6Tnc3n83GMOAgACeFpT6eRMMkJEkT0dACUIMEo2xKGSUGDDOAPe0qgsoEHKygms4FpkVtllMAaDRkME4PIUGAycA6oLhSRtLN0p2llkcphtUUAOrUMkAOQExXS4FwDbE2FKfgqVW5tXqBDsDmcrjVZQGQ3CDzGcVfkWmM5eVj1BrVX4YX+IFkFBcFIVRe04WQRF-jtChnRxN0jTVN1SQpKBqVpekUSVGkVVaNCEPILVCggDcxx3PdazAQ8zhpYCAKJZMwKhM1GAARkzSgoBtEiASQ113U9Yj3D9DklCdDAXkwXN80LFkACkZGlVSKzHat9zDU4Oh0uBVMwVtpNk1oKiUMMLxqCtuhnVI5gyRdu2XPJyMoskaNDei9JPMob3bFo2gYropCJJ8gkgUJPySfBxmi3z8CeX83hhL4TT+e1QPAqAIShJjyBguCKAEoTTQJNCSXJKkaTpEqCJdNLvQEsidQozdPIPI9GPtIiWKIS1eP4lFkAk5Aa1DesGOQAArVSwwsgN7C0fKnXq5DRKJH1xJZf0pInWSMFzKDSJXNz2u07yqn-fVcS9V0ButW1htGgAiQyXsjGAxu0ya9JW0r+ruraRp2jlUCrSoRAnaokE+5AMTddQMSdbJNKYO8nA9Az7DqVMTJteSCyAA)

**Related Issues:**

- [Inconsistency in generic parameter inference](https://github.com/microsoft/TypeScript/issues/38264)

**Comment by RyanCavanaugh** [comment]
Looks like a job for #30134

**Comment by idoros** [comment]
@RyanCavanaugh , this still doesn't work in the latest/nightly version, is this something that will not get resolved, or just a duplicate?

**Comment by RyanCavanaugh** [comment]
@idoros it's unlikely this will be changed barring a full redesign of generic inference
