### ISSUE TITLE
TypeScript doesn't watch the file imported by import statement without import clause

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#39700]
**TypeScript Version:**  4.0.0-dev.20200722

**Search Terms:**

**Code**

tsconfig.json

```json
{
    "compilerOptions": {},
    "files": ["./main.ts"]
}
```

main.ts
```ts
import './a'
```

a.ts
```ts
console.log('hi??')
```

- Run `tsc -b -w .`
- Change `hi??` to `hi!`

**Expected behavior:** watch the file changes

**Actual behavior:** nothing happened

**Comment by sheetalkamat** [comment]
This is working as intended. When using `tsc -b` it watches files only specified by your config file. It does not watch whole tree. `tsc` without build mode will watch whole program state. Build is simplified building tool that depends on your input (and corresponding outputs) files specified by your config without having to parse whole program.

**Comment by Jack-Works** [comment]
Do I have to use project composition with -b flag? I want to make sure it is included in the compilation.
