### ISSUE TITLE
Add anyFunctionType to the spec

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#3970]
We have a wildcard type in the compiler called anyFunctionType. Since there are some type system rules that relate to this type (for example the change in #3968), it should ideally be added to the spec. Note that this likely fits into the work of #1186 for updating overload resolution in the spec.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
