### ISSUE TITLE
aka.ms/tsconfig.json doesn't resolve in tsconfig.js init

### ISSUE THREAD

**Issue by barik** [microsoft/TypeScript#39705]
**TypeScript Version:**  3.9.7

**Search Terms:**
aka.ms

**Code**

```
npx tsc --init
cat tsconfig.json
```

**Expected behavior:**

```
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

```
I expected the link https://www.typescriptlang.org/v2/tsconfig to resolve in order to read more about this file.

**Actual behavior:**

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by RyanCavanaugh** [comment]
Fixed; now points to https://www.staging-typescript.org/tsconfig. I'll take a bit for the change to propagate everywhere

**Comment by RyanCavanaugh** [comment]
Thanks for the ping!
