### ISSUE TITLE
TypeScript 1.6 Breaking Changes log

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3971]
This issue tracks breaking changes to the 1.6 release. The full list can be found in the wiki: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-16

* [External modules parsed in strict mode](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#module-body-is-parsed-in-strict-mode) see #2598 for more details
* [System module output uses bulk exports](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#system-module-output-uses-bulk-exports) see #3346 for more details
* [Strict object literal assignment checking](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#strict-object-literal-assignment-checking) see #3823 for more details 
* [Function and class default export declarations can no longer merge with entities intersecting in their meaning](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#function-and-class-default-export-declarations-can-no-longer-merge-with-entities-intersecting-in-their-meaning) see #3095 for more details
* [.js content of npm package is moved from 'bin' to 'lib' folder](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#js-content-of-npm-package-is-moved-from-bin-to-lib-folder), see #3408 for more details
* [https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#changes-to-dom-apis-in-the-standard-library](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#changes-to-dom-apis-in-the-standard-library), see #4295, #4220, and #3999  for more details
* [https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#changes-to-dom-apis-in-the-standard-library](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-npm-package-does-not-install-globally-by-default), see #3987 for more details

**Comment by mhegazy** [comment]
Adding [Function and class default export declarations can no longer merge with entities intersecting in their meaning](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#function-and-class-default-export-declarations-can-no-longer-merge-with-entities-intersecting-in-their-meaning) see #3095 for more details

**Comment by vladima** [comment]
Adding [.js content of npm package is moved from 'bin' to 'lib' folder](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#js-content-of-npm-package-is-moved-from-bin-to-lib-folder), see #3408 for more details
