### ISSUE TITLE
4.0 next/dev - adding auto import with trailing comma 

### ISSUE THREAD

**Issue by whitecolor** [microsoft/TypeScript#39717]
**TypeScript Version:**  4.0.0-dev.20200722

I'm using prettier formating with trailing comma rule.
Adding with autoimport from `getWidgetCreatedEvent` results in:

![image](https://user-images.githubusercontent.com/736697/88328330-b6b36580-cd41-11ea-9a44-623f46b525c8.png)

**Expected behavior:**
```ts
  ChatCommand, 
  getWidgetCreatedEvent,
} from './commands'
```
**Actual behavior:**

```ts
  ChatCommand,, getWidgetCreatedEvent
} from './commands'
```

**Comment by andrewbranch** [comment]
@whitecolor this doesn’t reproduce for me. Can you add more details on how to get this to happen?

**Comment by whitecolor** [comment]
Add autoimport 
![image](https://user-images.githubusercontent.com/736697/88610407-fced2980-d09f-11ea-9add-3f713c9fc9fb.png)

Go to the top, and see:
![image](https://user-images.githubusercontent.com/736697/88610414-07a7be80-d0a0-11ea-86a0-bba4f64822f2.png)

I use the latest `@next`

Use prettier:
```
"prettier": {
    "semi": false,
    "singleQuote": true
  },
```
