### ISSUE TITLE
Type guards don't infer generic types

### ISSUE THREAD

**Issue by imachug** [microsoft/TypeScript#39727]
**TypeScript Version:**  4.0.0-dev.20200724

**Search Terms:** generics, type guard, typeof

**Code**

```ts
function func<T>(object: T): T {
	if(typeof object === "number") {
		return 1;
	} else {
		return object;
	}
}
```

**Expected behavior:**

The code compiles. It is obvious that if `typeof object === "number"`, then `T` must be `number`, and `1` is a `number`.

**Actual behavior:**

The code yields:

```
test.ts:3:3 - error TS2322: Type '1' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to '1'.

3  	return 1;
   	~~~~~~~~~


Found 1 error.
```

**Playground Link:** [There we go](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200724&ssl=1&ssc=1&pln=2&pc=22#code/GYVwdgxgLglg9mABKSAeAKgPgBRwEYBWAptAFyLoCU56iA3gFACQMw2UAngA5FzCL5i0RAF4xiAERgQAWzxEAThMr1mTBUSggFSAIwBuZgF9ERADYBnIqqbrN2pIJJRDTIwyNA)

**Related Issues:** none

**Comment by RyanCavanaugh** [comment]
```ts
// Causes the value '1' to inhabit an expression of type '2'
const a = func<2>(2);
```

**Comment by imachug** [comment]
Perhaps that was a wrong example. My actual code is similar to:

```
function func<T>(object: T): T extends Number ? number : T {
	if(object instanceof Number) {
		return object.valueOf();
	} else {
		return object;
	}
}
```

I don't see how `func<2>(2)` or similar would apply here.

I'll reopen the issue and change the code in the first comment if this turns out to be a bug.

**Comment by RyanCavanaugh** [comment]
#33014

**Comment by imachug** [comment]
Sorry for duplicates. I'll try to search better next time.

**Comment by RyanCavanaugh** [comment]
Those ones are hard for *me* to find 😅
