### ISSUE TITLE
JSDoc code fence displays invalid decorator code

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/TypeScript#39728]
**Code**

```ts
/**
 * ```
 * @NgModule({
 *   providers: [ ]
 * })
 * export class AppModule { }
 * ```
 *
 * @export
 * @class OAuthInitService
 */
export class MyClass {}
```

**Expected behavior:**

When you mouse over the element you should see properly formatted code when a decorator is used within a jsdoc code fence.

**Actual behavior:**

When you mouse over the element to see the jsdoc the code fence block displays incorrectly when using decorators:

![image](https://user-images.githubusercontent.com/1571806/88402208-69aab000-cd90-11ea-8e51-58c8535710c5.png)

If you prefix the `@NgModule` with a `\` so it becomes `\@NgModule`. Then the code displays properly, however the `\` is still present:

![image](https://user-images.githubusercontent.com/1571806/88403514-484ac380-cd92-11ea-8c74-460e2d1093dd.png)

**Comment by RyanCavanaugh** [comment]
You have a markdown code fence in a JS Doc comment block; we do not intermix these DSLs for the purpose of comment parsing.

You can see that the JS Doc "examples" do not use code fences: https://jsdoc.app/tags-example.html

**Comment by TheColorRed** [comment]
@RyanCavanaugh Then shouldn't/couldn't the example code be formatted?

**Comment by trusktr** [comment]
@TheColorRed Kinda harsh that your issue got closed without a workaround, or without even acknowledging that a solution exists.

I've always been unable to decorate inside JSDoc examples. Looks like there is finally an issue that they (respectfully) keeping open:

https://github.com/microsoft/TypeScript/issues/47679
