### ISSUE TITLE
Enum supports custom values

### ISSUE THREAD

**Issue by empty916** [microsoft/TypeScript#39725]
## Suggestion
enum supports custom values

## Use Cases

Enumeration values are not numbers

## Examples

````typescript

enum mode {
  pool = '02',
  single = '04',
}

mode.pool; // '02'
mode.single; // '04'
mode['02']; // it should be 'pool'
mode['04']; // it should be 'single'

````

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment]
In contrast to numeric enums it's not safe to make reverse mapping mapping for string enums
```ts
enum mode {
  pool = 'single',
  single = '04',
}
```

**Comment by empty916** [comment]
> In contrast to numeric enums it's not safe to make reverse mapping mapping for string enums
> 
> ```ts
> enum mode {
>   pool = 'single',
>   single = '04',
> }
> ```

I think an exception can be thrown at this time

**Comment by jcalz** [comment]
> I think an exception can be thrown at this time

That would break any existing TS code using string enums where a value is the same as one of the keys.

**Comment by empty916** [comment]
> > I think an exception can be thrown at this time
> 
> That would break any existing TS code using string enums where a value is the same as one of the keys.

you are right，thanks
