### ISSUE TITLE
Wrong sub-typing when using custom type predicate methods

### ISSUE THREAD

**Issue by ClementNerma** [microsoft/TypeScript#39733]
**TypeScript Version:**  2.4.1, 3.9.3, 3.9.7, 4.0.0-dev.20200724, nightly

**Search Terms:** type predicate, sub-typing type predicate

**Code**

```ts
// Here are sample types
type A_or_B = A | B

class A {
    isA(): this is A { return true }
    isB(): this is B { return false }
}

class B {
    isA(): this is A { return false }
    isB(): this is B { return true }
}

// Problem n°1:
const a: A_or_B = new A()
const b: B = a // Shouldn't work as it's in reality an A typed as an A_or_B

// Problem n°2
if (a.isA()) {
    // here, 'a' has type 'A_or_B' ; should be 'A'
} else {
    // here, 'a' has type 'never' ; should be 'B'
}

if (a.isB()) {
    // here, 'a' has type 'A_or_B' ; should be 'B'
} else {
    // here, 'a' has type 'never' ; should be 'A'
}
```

**Expected behavior:**

The first "problem example" should not compile as `A_or_B<string>` should not be assignable to a `B<string>` constant.
The second "problem example" should infer sub-types correctly.

**Actual behavior:**

It does not.

I have absolutely no idea what's causing this issue, but as it does not work in 2.4.3 as well, this does not seem like a regression.

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=30&pc=1#code/PTAEAkFMCdNBDWoDO8C2AHANnALgTw0mQCgCjQBBAfQHtpqAhUAXitAB9RGSSBjLPGTJ2AbxKhJoAJbJKACgCUALlC4AFrJkjKoUaFi4ArtAB2a6EbgBfCVNmMlqjVq3N9hk+YBm8LMhsSW35BYW49O0lZBRU1TREtXQ9IYzNQX39AqW1HWJcEkXcDFK8LK1BbYJBQAAVoWgAjHDRQUwAGgEZlflpTZFwEVRp6JlZWyAB3KiUevoGG1WY2eFBqgGV1WiMsABNTAHIBifoAawQE3H2E81g-aQIEc10d2QBzI1k4IUeqOgYeEjVOqNZqtNoAJhI0m8oHk8AAdNElIoItlquoYJAADSgfbwfagdTfchwfbDf4EgDcKE22x2oAapMo+yCoEgmVRUnRmJxeIJRJEJNxpkgADcYFSaVtdgzSYwWcFobCEQ5kZzJNzYLz8YTiYQmX8mJLkLSZYzcfLWeyAurVmAMVrcTqBWp9cKxRLQNSTdL6eayQqSEA

**Related Issues:** -

**Comment by RyanCavanaugh** [comment]
Two issues here:
 * Your classes are structurally identical; see the FAQ on structural typing
 * TS can see the control flow initialization of `a` so can tell it will never be `B`, this is correct behavior.

A sample that works as you expect when correcting those errors:
```ts
// Here are sample types
type A_or_B = A | B

class A {
  a!: string;
  isA(): this is A { return true }
  isB(): this is B { return false }
}

class B {
  b!: string;
  isA(): this is A { return false }
  isB(): this is B { return true }
}

// Problem n°1:
const a: A_or_B = new A() as A_or_B;
const b: B = a // Correctly errors

// Problem n°2
if (a.isA()) {
  // a is 'A'
} else {
  // a is 'B'
}

if (a.isB()) {
  // a is 'B'
} else {
  // a is 'A'
}
```

**Comment by ClementNerma** [comment]
Ok I didn't about the TypeScript compiler being unsound in specific scenarios, nor it requiring different structures to eliminate types from an union.

Thanks for your explanation :)
