### ISSUE TITLE
Compiler mixes up types

### ISSUE THREAD

**Issue by jesseschalken** [microsoft/TypeScript#39738]
**TypeScript Version:**  3.9.7, Nightly

**Code**

```ts
interface A {
  create<T>(): {
    readonly bar: T;
    readonly foo: T | number | string;
  };
}

interface B extends A {
  create<T>(): {
    readonly bar: T;
    readonly foo: T | number;
  };
}
```

**Expected behavior:**

No Error

**Actual behavior:**

```

src/test.ts:8:11 - error TS2430: Interface 'B' incorrectly extends interface 'A'.
  The types of 'create().bar' are incompatible between these types.
    Type 'string | T' is not assignable to type 'T'.
      'T' could be instantiated with an arbitrary type which could be unrelated to 'string | T'.
        Type 'string' is not assignable to type 'T'.
          'T' could be instantiated with an arbitrary type which could be unrelated to 'string'.

8 interface B extends A {
            ~

```

`tsc` says specifically:

```
  The types of 'create().bar' are incompatible between these types.
    Type 'string | T' is not assignable to type 'T'.
```

but provides no explanation for where the ` string |` part came from. The compiler seems to have just grabbed the `string` part of the unrelated property `foo` in `A` and thrown that into the union for the property `bar` in `B` for no reason.

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4ChnIVCOSAHgBUA+ACgEoAuTHXZAuAEwHsQAbAT2QCM4UeqQDcjXCw7c+MduxHIAPshABXALb9oy5AGcwUUAHNxuAL7jzWLKEixEKAELIIAD0ghWetA1z5CEgoaemwmZkJpXgEhETMmKU5ouQVkUl11LWh4yyxrIA

**Comment by jesseschalken** [comment]
FWIW it works fine in Flow: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gAKBcAthgM54AyGA1ngDwAqAfGAG9UYMDgAWeLJwCqvABRQsALjByAHiu4BKMAF5+1Ooy6ytKw-SYzeqAL7ps+ImQoBBQcLCkCeYvh7yZh4iIgBGxAQKyqoaYNp6-KFwcDC+WEFJKWlgAD5UNJYs7FyZqcRYvADcniJQyXJB3LlgAG5wGAAmzRbGrBw8zW2dVZ621faYuIQk5GAAQmB4avhYHQxg7kIi3r7+fA0qWyHhkYoq6po6+mClaRnJZVjVIWB1cAdxg+0dz2BjdqggA

**Comment by MicahZoltu** [comment]
If you remove `foo` from the result type of A the problem goes away, which makes me think the compiler is somehow getting confused seeing as how the error is on `.bar`.

**Comment by RyanCavanaugh** [comment]
This is a correct error given how TypeScript implements inference between unions. It's hard to observe this, but consider if you wrote
```ts
declare const a: A;
const m: { foo: string | number | boolean } = a.create();
```
This is inferred to be a call to `a.create<boolean>();`

If you had written
```ts
declare const b: B;
const n: { foo: string | number | boolean } = b.create();
```
This is inferred to be a call to `b.create<boolean | string>();`

This means that:
 * `m.bar` had type `boolean`
 * `n.bar` had type `boolean | string`

Note that `boolean | string` is *not a subtype* of `boolean`, which means it would be unsafe to alias `b` in `a`'s position, which means `B` is not a subtype of `A`

**Comment by jesseschalken** [comment]
> This means that:
> 
> * `m.bar` had type `boolean`
> * `n.bar` had type `boolean | string`
> 

That's only because a different `T` was given to `.create<T>()`, inferred or not. Of course if you pass a different type parameter you will get a different type as the result. What does that have to do with compatibility between `A` and `B`?

My understanding was that type inference is done as a first step purely as a convenience to the developer to save them writing out many explicit types but otherwise has no influence on the subtype relation on types themselves.

But you seem to be saying that `B` is not a subtype of `A` not because some code that accepts an `A` may crash if given a `B`, but purely because some code written referring to `A` may infer different types if that code was changed to refer to `B` instead. Is this correct? Why is this relevant to type compatibility?

Certainly the rest of TypeScript doesn't seem to follow this rule:

```ts
function bar() {
  type A = string;
  type B = string | undefined;
  type C = undefined extends A ? string : number; // <= B is a subtype of A, but change this A to B and the code will break
  const x: C = 1;
}

```

**Comment by RyanCavanaugh** [comment]
> But you seem to be saying that B is not a subtype of A not because some code that accepts an A may crash if given a B, but purely because some code written referring to A may infer different types if that code was changed to refer to B instead. Is this correct? Why is this relevant to type compatibility?

This argument elides the fact that *functions must have implementations* - this isn't about what type gets produced from inference, it's about whether or not you believe the function signature is telling the truth about its behavior and then make sound assumptions about compatibility based on that behavior. If `A` claims to have some behavior in the presence of a `string | number | boolean` type and `B` has some other *incompatible* behavior in the presence of that type, it'd be an unsoundness to treat those types as related. This relationship is very difficult to demonstrate for a contravariant-only type parameter like exists in `T` (this kind of function ought not exist, but I digress), but it's very much a rule that exists to prevent unsound relationships from manifesting.

> My understanding was that type inference is done as a first step purely as a convenience to the developer to save them writing out many explicit types but otherwise has no influence on the subtype relation on types themselves.

This is incorrect. Relating two generic signatures involves inference to detect if the signatures are properly related, see comments in `instantiateSignatureInContextOf` in `checker.ts`. This is required to properly assess relationships where one or more of the signatures being compared are generic.

**Comment by jesseschalken** [comment]
> If `A` claims to have some behavior in the presence of a `string | number | boolean` type and `B` has some other _incompatible_ behavior in the presence of that type, it'd be an unsoundness to treat those types as related.

Except this "incompatible behavior" *is* entirely because TS infers a different type for `T` when `a.create()` is replaced with `b.create()`. If the type parameter `T` is specified explicitly to be `string`, then both `a.create<string>()` and `b.create<string>()` produce `{readonly bar: string, readonly foo: string | number}`. No matter what type you push in through `T`, the same type or a subtype will come out. So they're compatible.

The only thing you've shown is some code which uses TS's inference for `T` will infer a different `T` when `a.create()` is replaced with `b.create()`, but then say "this isn't about what type gets produced from inference". Makes no sense.

> This is incorrect. Relating two generic signatures involves inference to detect if the signatures are properly related, see comments in `instantiateSignatureInContextOf` in `checker.ts`. This is required to properly assess relationships where one or more of the signatures being compared are generic.

Yes, this makes sense. Since TS allows generic signatures to be compatible with non-generic signatures, provided some suitable substitution exists, it will need inference to find a suitable substitution.

Still I don't see the relevance. Even if we create a third interface `C` to reflect the non-generic usage:

```ts
interface C {
  create(): { foo: string | number | boolean };
}

interface A extends C {
  create<T>(): {
    readonly bar: T;
    readonly foo: T | number | string;
  };
}

interface B extends A, C {
  create<T>(): {
    readonly bar: T;
    readonly foo: T | number;
  };
}
```

`A` is compatible with `C` through `T = boolean` (or any narrower type), `B` is compatible with `C` through `T = string | boolean` (or any narrower type) and `A` is compatible with `B` because `T | number` is compatible with `T | number | string` for all `T`.

So what is the problem?

**Comment by RyanCavanaugh** [comment]
There isn't a problem. This is the intended behavior for the reasons already described.

If you have some proposal for how to make this work more like you expect that doesn't make inference worse for other cases I'm very open to hearing it, but the algorithm today is very straightforward and consistent - infer the signature in the context of the other signature and use that to relate the types. There might be some completeness gaps in this due to its lack of use of higher-order reasoning (which I think is what you're describing here) but it's sound in both senses of the word.
