### ISSUE TITLE
Type circularly referencing itself when using a generic union type

### ISSUE THREAD

**Issue by ClementNerma** [microsoft/TypeScript#39734]
**TypeScript Version:**  3.9.2, 4.0.0-beta.20200724, nightly

**Search Terms:** generic union type circularly referencing itself

**Code**

```ts
class A<T> {}
class B<T> {}

type A_or_B<T> = A<T> | B<T>

type C = A<C> | B<C> // Works fine
type D = A_or_B<D> // Doesn't work :(
```

**Expected behavior:**

The code should compile.

**Actual behavior:**

It does not.

**Playground Link:** https://www.typescriptlang.org/play/#code/FAYwNghgzlAECCAeAKgPlgbwL6kjWAQiutsMAC4CeADgKYID6A9gE4NFqwC8CxsAPoWJkqdWAGFuvcekFEZsAPSLYAdVYBrOADMAlgDtaFGvQAiU+MzZFT6ZbFNNaUfQHJysAO6bYALgAUwEA

**Related Issues:** -

**Comment by RyanCavanaugh** [comment]
Duplicate https://github.com/microsoft/TypeScript/issues/41164#issuecomment-712418462; others
