### ISSUE TITLE
Error about 'declare' modifier not allowed on class elements is not exactly correct since it can be used on class properties

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#39745]
Sorry, this is kind of pedantic, but I thought worth reporting anyway since it's easy for someone to go fix this.

**TypeScript Version:**  4.0.0-dev.20200725

**Search Terms:** declare modifier class element

**Code**

```ts
class Test {
    declare public type(): string;
    declare other: string;
}
```

Errors on first with:

> 'declare' modifier cannot appear on a class element.

But the `declare` modifier is valid on class properties as of TS 3.7.

**Expected behavior:**

Error message should not say "on a class element" because that's not technically correct.

Perhaps just change the error to `'declare' modifier cannot appear class elements of this kind.`

**Actual behavior:**

Error message says that the declare modifier is not allowed on class elements.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.0-beta&ssl=1&ssc=1&pln=5&pc=1#code/MYGwhgzhAEAqCmEAu0DeBYAUNH0Am8oYATvNAA4CuARiAJbDRICe58AFAJQBc0yxdAHYBzANxZc+QuFLQA9kgAW8Yr35CxWAL5YgA

**Comment by saigeethakandepallicherukuru** [comment]
Hi, I have started working on this. Thanks!

**Comment by DanielRosenwasser** [comment]
Thanks @saigeethakandepallicherukuru!
