### ISSUE TITLE
Namespaces and import statements

### ISSUE THREAD

**Issue by germanysources** [microsoft/TypeScript#39741]
The following code causes TS2304 errors (name `PostResponse` not found):

index.ts
```ts
import * as XLSX from './sheetjs';

namespace Wrapper {

        export interface PostResponse {
                shared: boolean;
                options: XLSX.CommonOptions;
        }

}
```
ns.ts
```ts
/// <reference path="index.ts"/>
namespace Wrapper {

        function setResponse(r: PostResponse) {
          //
        }

}
```

`sheetjs` is the declaration file from https://github.com/SheetJS/js-cfb/blob/master/types/index.d.ts.
Tried with `tsc` version 3.9.5.

**Comment by RyanCavanaugh** [comment]
Declarations in the global scope and declarations in a module scope do not merge together because they are different declarations, not two declarations of the same thing
