### ISSUE TITLE
allowing 'unknown' to be on the right side of 'in' operator

### ISSUE THREAD

**Issue by chxzh** [microsoft/TypeScript#39748]
## Search Terms

- unknown type
- in keyword

## Suggestion

to allow using 'unknown' as the right operand for 'in'.

## Use Cases

Runtime type checking by inspecting certain members. 

## Examples

```TypeScript
interface Duck {
  quack(): void;
}

function isDuck(value: unknown): value is Duck {
  return 'quack' in value;
}
```
Right now there will be an error of "The right-hand side of an 'in' expression must be of type 'any', an object type or a type parameter." To my understanding of TypeScript design, this seems to be omitted when adding `unknown` type and it would be more consistent if we could include this change.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
`in` throws an exception if its right operand isn't an `object`

**Comment by chxzh** [comment]
Make sense. Thanks!
