### ISSUE TITLE
Infer super function call from super

### ISSUE THREAD

**Issue by vectoron** [microsoft/TypeScript#39747]
When calling a super function from a child class, just calling super should infer the parent super function. Having to call the super function by name is rather problematic and can lead to problems if you accidentally call the incorrect super function. It is already inferred by the constructor so the fact that it is not inferred by the child functions is confusing.

```javascript
class MyParent {
   protected myFunction(test:string):void {
   }
}

class MyChild extends MyParent {
   myFunction(test:string):void {
      super("test"); //this should infer super.myFunction()
   }
}
```

**Comment by ExE-Boss** [comment]
This goes against **TypeScript**’s [design goal 8](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals).

**Comment by vectoron** [comment]
> This goes against **TypeScript**’s [design goal 8](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals).

What in particular?

**Comment by RyanCavanaugh** [comment]
This is out of scope as mentioned above; it has nothing to do with typechecking. You can take this runtime proposal to TC39 as a suggestion
