### ISSUE TITLE
TypeScript Barfs on Unescaped \u2028 Characters in JSON

### ISSUE THREAD

**Issue by travigd** [microsoft/TypeScript#39757]
**TypeScript Version:**  3.9.7

**Search Terms:**
JSON unicode escape

**Code**
Any JSON file with an unescaped \u2028 in a string

**Expected behavior:**
TS will be able to parse this file since it's valid JSON.

**Actual behavior:**
TS barfs with
```
Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.
```

**Playground Link:** 

**Related Issues:** 

---

The issue seems to be that unescaped \u2028's are not valid is JavaScript but are valid JSON.
https://stackoverflow.com/questions/2965293/javascript-parse-error-on-u2028-unicode-character

This might very well be a wontfix, but creating this issue for posterity.

**Comment by IllusionMH** [comment]
These characters in strings should be parsed without an error since ES2019
https://github.com/tc39/proposal-json-superset

**Comment by Zuckjet** [comment]
It seems this error won't occur now
