### ISSUE TITLE
Error message for assigning to an imported variable is confusing

### ISSUE THREAD

**Issue by uhyo** [microsoft/TypeScript#39751]
## Search Terms

TS2539 import variable

## Suggestion

```ts
import { v } from "somewhere";
// Error TS2539: Cannot assign to 'v' because it is not a variable.
v = 100;
```

The error message for TS2539 is confusing because `v` is actually a variable (at least regarding the ES spec where imported ones and other normal variables are described as different kinds of "bindings") . The true reason of the error is that it is an imported variable, so it would be better if we changed the message to, for example:

- Cannot assign to `v` because it is an imported variable.
- Cannot assign to `v` because it is immutable.
- Cannot assign to `v` because it is a constant. (same as `const` variable)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
There's a slight subtlety here which is that there's another syntax called "namespace import aliases".

```ts
   namespace foo { export var x = 100; }
   
   import X = foo;
   
   X = { x: 100 };
// ~
// Cannot assign to 'X' because it is not a variable.
```

Maybe it's fine to issue the same message on these too.

**Comment by hailin-zhang** [comment]
Hello, I've created a PR for this issue. There were a couple different cases for this error so I've opted to change it to `Cannot assign to v because it is immutable.` Please let me know if a more descriptive message is preferred 😄

**Comment by DanielRosenwasser** [comment]
I don't think "immutable" is right either, but I'll try to provide something better in the PR - thanks!

**Comment by mohamadhamad300** [comment]
hello  
adjust the compilerOptions so that your module is treated as CommonJS one
treat the imported values as bindings (aliases), not true identifier

**Comment by kylejlin** [comment]
Hi everyone! I'd be happy to create a PR for this issue, but I'm not certain what the error message should be.

How about `Cannot assign to {{x}} because it is an import binding.`? Let me know if you have suggestions for alternatives.

**Comment by kylejlin** [comment]
Oh, wait. I just realized that this is the same error message that gets used when the user tries to reassign other non-variables (such as functions or enums). I guess these were the cases @hailin-zhang was referring to.
