### ISSUE TITLE
template string not parse correctly in es3

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3976]
````
export function translate(load) {
   logger.debug(`systemjs translating ${load.address}`);
````

transpiled to:
````
    function translate(load) {
        logger.debug(`systemjs translating ${ + load.address + );
````
This is in `frankwallis/plugin-typescript@2.0.1/lib/plugin.js` of the jspm (systemjs) package.
Using `mhegazy/typescript@v1.5-beta2` jspm package.
Is this fixed in 1.5.3?

**Comment by unional** [comment]
Likely systemjs issue. Closing this.

**Comment by DanielRosenwasser** [comment]
I'm not able to repro it, but it seems odd that you even get that output. Can you fully confirm this is a systemjs issue?

**Comment by frankwallis** [comment]
The issue is that transpile does not accept the ```target``` option as a string. I don't know if this is intentional or not. To recreate:

```
var ts = require("typescript");
var variable = "world";
var source = "console.log(`hello ${variable}`);";
var es3stringOutput = ts.transpile(source, { target: "es3" });
var es3enumOutput = ts.transpile(source, { target: ts.ScriptTarget.ES3 });

if (es3stringOutput != es3enumOutput) {
	console.log('es3stringOutput:');
	console.log(es3stringOutput);
	console.log('es3enumOutput:');
	console.log(es3enumOutput);
}
```

**Comment by mhegazy** [comment]
aah.. these functions do not do input validation, they assume you are compiling using the typescript compiler :).

looks like since we have different checks like if(target <= ES3) where the string would make it pass, the parser behaves unexpectedly.

**Comment by mhegazy** [comment]
and @frankwallis it is intentional. see the definition: https://github.com/Microsoft/TypeScript/blob/8fcca92e4ee400afaa550e0279c90209c9809751/bin/typescript.d.ts#L2074

**Comment by mhegazy** [comment]
@frankwallis i believe this is a plugin issue then.
