### ISSUE TITLE
`export * as default from "module"` syntax should work as per ECMA-262

### ISSUE THREAD

**Issue by HughCrail** [microsoft/TypeScript#39769]
**TypeScript Version:**  4.0.0-beta

**Search Terms:**
ESModule, export star as default, "export * as default from"

**Expected behavior:**
`export * as default from "module"` should export the namespace of "module" as the `default` export.
This is valid ES Module syntax from [this stage-4 proposal. ](https://github.com/tc39/proposal-export-ns-from) See the [test](https://github.com/tc39/test262/blob/e193b449d417c4fb7fc9b6f6b869fd55bca04372/test/language/module-code/export-star-as-dflt.js) in test-262.
I also tested this syntax in Chrome and it was supported.

**Actual behavior:**
You get the following errors:
- "Cannot find name 'from'."
- "Identifier expected. 'default' is a reserved word that cannot be used here."
- "';' expected."

**Code**
```ts
export * as default from "rollup";
```

<details><summary><b>Output</b></summary>

```ts
export * as  from ;
from;
"rollup";

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "Latest",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.staging-typescript.org/play?target=99&ts=4.0.0-beta#code/KYDwDg9gTgLgBAKjgQwM5wCbAGbIK4A282UEAtnAESkEF5iUDcQA)

**Comment by DanielRosenwasser** [comment]
CC @Kingwl in case you want to take this on as a follow-up to https://github.com/microsoft/TypeScript/pull/34903

**Comment by Kingwl** [comment]
Take a look soon.

**Comment by DanielRosenwasser** [comment]
Thanks @Kingwl!
