### ISSUE TITLE
Unexpected output from typescript about default value & extends

### ISSUE THREAD

**Issue by foolseafish** [microsoft/TypeScript#39761]
**TypeScript Version:**  4.0.0-beta

**Search Terms:** Default Value, Extends

**Expected behavior:**  Child constructor assign > Parent constructor assign > Child property default value > Parent property default value.

**Actual behavior:**  Child constructor assign > Child property default value >  Parent constructor assign > Parent property default value.

**Code**
```ts

class father {
    color:string = 'red';
    constructor(color:string){
        this.color = color
    }
    say(){
        return this.color;
    }
}


class child extends father{
    color:string = 'blue';
}

console.log(new child('yellow').say());

```
<details><summary><b>Output:</b><b>blue</b></summary></details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBWCMQTCZL4-qgADeihKJQQ0HgZHyglQlE4YwAvKAAORObjCgDcLNZCE4PLI7Fg6DIAAp2ZzubzRgBKZms-UCQQBdU4oUm6UlAC+FuuTBVupt+qcBLImTURpNUv11utlOpwg0WNcawUPFp9J+epl8A5XPlo1AQuF0mg7EgksUvtlghjkACHOYKs4kAkJjU0RVwrwMA5EmF2oCQLw9u1UpUOAaHldoEQnOcIPYNG+bjMzHYDGYkH4VPUiQYIL0Ii8ACIAKKrBiIGr6ZdJHHL8AOVDC4QAORLy6CKgA8t8yLtBFOtJBjqhHApXNI8KAnL2dAnvkfdFEBhYQrmHCROWiEQDA4HFuhYNguG4IISiAA)

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/43595943/why-are-derived-class-property-values-not-seen-in-the-base-class-constructor

**Comment by foolseafish** [comment]
Thanks a lot for your answer.
