### ISSUE TITLE
Do not allow destructuring an optional parameter

### ISSUE THREAD

**Issue by LamTVB** [microsoft/TypeScript#39771]
## Search Terms

Search terms: destructure parameters

## Suggestion

Right now, a parameter in a function signature that is optional and destructured in the same function does not return any warning or error.
It would be nice if we can have a compile error saying that the parameter must have a default value or to be mandatory in case the parameter is destructured in the function. 

## Examples

```javascript
interface User {
  firstName: string;
  lastName: string;
}

function duplicateUser(oldUser?: User) {
  // This should return a compile error stating that the `oldUser` is optional so it cannot be destructured
  const { firstName, lastName } = oldUser;
  ...
} 
```

## Checklist

My suggestion meets these guidelines:
 
* [x]  This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x]  This wouldn't change the runtime behavior of existing JavaScript code
* [x]  This could be implemented without emitting different JS based on the types of the expressions
* [x]  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x]  This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
This is already an error if you enable the `strictNullChecks` compiler option. Without it `undefined` is not part of the type.
