### ISSUE TITLE
InterfaceTypeWithBaseTypes.baseTypes is lazily loaded without clear API to do that

### ISSUE THREAD

**Issue by Knagis** [Microsoft/TypeScript#3977]
This issue appeared after upgrading from 1.4 to 1.5 - the baseTypes of a class were always returning `undefined` - by looking in the source I found that calling, for example, `getConstructSignatures()` would lazily load the data.

        if (node.kind === ts.SyntaxKind.ClassDeclaration) {
            var cl = <ts.InterfaceTypeWithBaseTypes>checker.getTypeAtLocation(node);
            console.log(cl.baseTypes); // prints "undefined"
            cl.getConstructSignatures();
            console.log(cl.baseTypes); // prints the actual base types
        }

It seems that instead of exposing the field `baseTypes`, there should be a method `getBaseTypes()` - similar to other such changes in the API.

**Comment by mhegazy** [comment]
pinging @JsonFreeman

**Comment by JsonFreeman** [comment]
In general, there are two recommendations for using the Types API:

1. Do not cast to a type that grants you access to more properties. These properties are generally hidden in a subtype for a reason.
2. Do not directly access properties that start with `resolved`

Instead, you should call a function that gets you these things and that will take care of the lazy computation.

@Knagis In the version of the code that you're looking at, we do indeed have a getBaseTypes that you should call.

If you update to the latest in master, getBaseTypes is still there, but InterfaceTypeWithBaseTypes is gone. Instead there is a property called resolvedBaseTypes which should not be accessed. There is additionally resolvedBaseConstructorType which should not be accessed (for that one you call getBaseConstructorTypeOfClass).

I wish there were a better way to hide members that should not be accessed directly, but the only way I know of is to use privates, which today require that the containing type be a class. And we don't use classes in the compiler.

Although now that ambient classes and interfaces can be merged, maybe we can.

**Comment by JsonFreeman** [comment]
@mhegazy Is there anything that needs to be done here?

**Comment by JsonFreeman** [comment]
@Knagis, are you asking us to expose the getBaseTypes function on the TypeChecker interface? What are you trying to use it for?

Also, I think we should designate these properties as internal.

**Comment by Knagis** [comment]
> @Knagis In the version of the code that you're looking at, we do indeed have a getBaseTypes that you should call.

In the master branch I only see `resolvedBaseTypes` field but no `getBaseTypes()` method.

---

I am writing code that extracts certain classes and properties from the code and creates documentation page from that. I need base types both to check if a class should be included in the documentation (if it is derived from a certain base class) and to display the type hierarchy there. Is there a different approach I should use for this purpose?

**Comment by JsonFreeman** [comment]
I was talking with @mhegazy and he suggested maybe getting the base type nodes from the AST and then getting the types of those base type nodes. So if you have the class declaration node `classNode`, you would `classNode.heritageClauses`, find the extends list in there, call it `heritage`. Then `heritage.types`, and those will be expressions with type arguments. Then call `checker.getTypeAtLocation` on that base type node. And then it should give you the right thing.

**Comment by Knagis** [comment]
That could be done, it just slightly increases the complexity since there can be multiple declarations.

What is the reason why the Type could not expose the baseTypes? If I call `Type.getProperties()`, it returns all properties including inherited properties from base types - so it does have this information internally.

**Comment by JsonFreeman** [comment]
Oh I see, you are not using the TypeChecker interface, you are using the Type interface defined in services. I think you're right - it's reasonable for us to expose getBaseTypes().

**Comment by JsonFreeman** [comment]
@Knagis does #3990 address your need?

**Comment by Knagis** [comment]
Yes, it does.
Thank you!
