### ISSUE TITLE
Readonly exporting of imported modules doesn't support mocking for unit tests

### ISSUE THREAD

**Issue by Farenheith** [microsoft/TypeScript#39775]
**TypeScript Version:**  3.9.7

When, in a index file, it is exported the content of another file, tsc transpiles it with read only accessors, making it not possible to mock on unit tests..

**Search Terms:** exports accessor, export readonly, export accessor readonly, export getter

**Code**
tsconfig file is configured for commonJs module output
```js
{
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src",
    "target": "es2018",
    "module": "commonjs",
    "strict": true
  }
}
```

File my-test.ts
```ts
export function myTest() {
  return 1;
}
```
File index.ts
```ts
export * from './my-test';
```
Supposing it is transpiled to a dist folder, you can have a javascript file with this code:
```js
const test = require('./dist');
test.myTest = function () {
  return 2;
}

console.log(test.myTest());
```
Alternative:
```js
import test = require("./index");
Object.defineProperty(test, "myTest", {
  get() {
    return 2;
  },
});

console.log(test.myTest());
```

This substitution is not production material, but a simulation of mocking/stubbing on unit tests. Libraries like **sinon** do something like this to achieve the mocking.
Notice that, in a real project, I'm using typescript register + mocha, not running directly the compiled code, but with this setup is easier to simulate the problem.

**Expected behavior:**
I expect that the js code prints 2;

**Actual behavior:**
In js alternative 1, It prints 1, in js alternative 2, it throws an error;
The problem happens because of how the index.js is generated. Since 3.9.2, it is generated like this:
```js
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
}
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./my-test"), exports);
```

Notice that, in the line 4 of this code, an accessor is defined.
On version 3.8.3, it generates like this:
```js
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./my-test"));
```
With this generated code, the mocking, ie, the substitution of the exported method, is possible, but with the first one it's not. Is important to notice that the generated module is not complying with the [compilerOptions module rule](https://www.staging-typescript.org/tsconfig#module) in both cases, but with the latest version it also changes the expected behavior.

**Playground Link:** I'm unable to create a playground example as this issue only happens using multiple files, but i created a example project: https://github.com/Farenheith/issue-readonly-exporting-example

**Related Issues:** I couldn't find any.

**Comment by RyanCavanaugh** [comment]
ES6 module exports are immutable; this is the same behavior you'd get if you weren't downleveling

**Comment by Farenheith** [comment]
But this is a diverging behavior.

If the function are exported in the same file, it is mutable.
Example:
index.ts
```ts
export * from './my-test';
export function myTest2() {
  return 3;
}
```

If I do the same operation in myTest2 from the issue example:
```ts
const test = require('./dist');
test.myTest2 = function () {
  return 2;
}

console.log(test.myTest2());
```
It'll print 2

**Comment by Farenheith** [comment]
It can be said that, in this case, the wrong behavior happens with this last example, but even though, changing it is a breaking change, so it should be addressed to a major version, not minor one.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't follow semver, and even if it did, changes to make code comply with the ES6 spec would be defect fixes and thus not part of any semver contract.

**Comment by Farenheith** [comment]
I got your point, but I still see an issue:
In the example project I linked, the tsconfig.json specifies tsc to generate module as commonjs, like this:
```js
{
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src",
    "target": "es2018",
    "module": "commonjs",
    "strict": true,
  }
}
```
So, why tsc is simulating es6 behavior in some cases?
According to the tooltip raised in the property module, it should generate as commonJS modules
```
Specify module code generation: 'None', 'CommonJS', 'AMD', 'System', 'UMD', 'ES6', 'ES2015', 'ES2020' or 'ESNext'. Only 'AMD' and 'System' can be used in conjunction with --outFile.
```
I know the generated code still is commonjs, but it really not a defect fix to simulate ES6 behavior when tsconfig if configured like that.

**Comment by gustavobeavis** [comment]
in this case, this issue makes sense, including the perspective that assumes the target as es5, so you must respect the module generation as shown.

**Comment by Farenheith** [comment]
@gustavobeavis from my point of view. Even if the target is not es5, the modules still should behave as commonJs if it is specified in the module configOption.

**Comment by Farenheith** [comment]
Hello guys, I just want to give an update about this issue. I checked out [official documentation](https://www.staging-typescript.org/tsconfig#module) about the the module property, and both outputs I described in the issue looks like when that **compilerOption** is not informed. So, I think the actual issue is that the compiler is not complying to that specific rule.
![image](https://user-images.githubusercontent.com/5713887/88661492-f74b1000-d0ae-11ea-95b4-ccfa47d22088.png)
![image](https://user-images.githubusercontent.com/5713887/88661511-fdd98780-d0ae-11ea-9499-78c278d24ab6.png)
As so, I'm updating the initial post with this information to make it more clear.

**Comment by gustavobeavis** [comment]
@RyanCavanaugh I consider the classification of this issue to be incorrect since in the compile options as commonJs it should behave as pointed out by @Farenheith 

so if you don’t intend to support CommonJS in the future it’s a breaking change.

**Comment by GuilhermeSpadaccia** [comment]
I was having the same issue. My unit tests were working as expected and, after I updated my packages, it just stops to work, until I found this issue and realized that Typescript started to generate modules with some exported functions as read-only and others not. Only downgrading the typescript to fix that.

**Comment by Farenheith** [comment]
@RyanCavanaugh even though there is a bug and It is clearly showed in the discussion you'll keep this issue wrongly marked as "working as intended" and now as closed?
If you prefer, I'll open another issue more clear, talking specific about de compiler option module bug

**Comment by Farenheith** [comment]
I just wanted to add here that I was mistaken about pointing it out as a TypeScript problem. I figure out after many time that it's actually problem with [sinon limitations](https://github.com/sinonjs/sinon/issues/1711), as it doesn't give the proper tools to mock ES6 read-only modules. **Jest**, in the other hand, delivers it, making it possible to mock anything. like in the example below:
```ts
const myMockedModule = {
   ...jest.requireActual('my-es6-readonly-module'),
   theFunctionIWantToMock: jest.fn(),
}
jest.mock('my-es6-readonly-module', () => myMockedModule);
```
So, I want to apologize about my stuborness in the case with the team! As the best solution for me, in that case, would be to change my testing libraries for a better one.
