### ISSUE TITLE
Conditional type does not work with a generic

### ISSUE THREAD

**Issue by impworks** [microsoft/TypeScript#39787]
**TypeScript Version:**  3.9.2

**Search Terms:** KeysOf, Conditional type, Generic, Extends

**Code**

```ts
type KeysOf<T, TPropType> = { [P in keyof T]: T[P] extends TPropType ? P : never }[keyof T];

function getValues<T>(obj: T, ...keys: KeysOf<T, string>[]) {
    console.log(keys.map(x => obj[x]));
}

interface Foo {
    a: number;
    b: string;
    c: string;
}

class ConcreteReporter {
    report(obj: Foo) {
        getValues(obj, 'b', 'c');
    }
}

class AbstractReporter<T extends Foo> {
    report(obj: T) {
        getValues(obj, 'b', 'c');
    }
}
```

**Expected behavior:**
Code compiles successfully.

**Actual behavior:**
In `AbstractReporter`, the `'b'` key is not accepted in `getValues` with an error:

```
Argument of type '"b"' is not assignable to parameter of type 'T[keyof T] extends string ? keyof T : never'. (2345)
```

**Playground Link:**
https://www.typescriptlang.org/play/#code/C4TwDgpgBA0hIGcDyAzAPAFQDRQwBQCcB7MDcCAPigF4oBvKAbTygEsA7KAa3iJVwC6ALlzMBUCAA9gEdgBMEuQiTKQoAfigsR7CADcIBKAF9GPEH0EBuALAAoeygCu7AMbBWRTgHMIwAGoAhgA2ThAImBQAFEQARgBWIthQAHRp5ggicIiomDgIwAQc3hSMAgCU9PZQNVCuXghEwRApwUTeURkpALaBYFGSNFRx8YySFeW2dsb29hwyBCiBrtAAYkREVXa1UIE6Tt2xhlM7sSIFRezeJ7Wu54XFUzMOdq7BgQiKAMJergR+EAAShAwEQCAstjt-qDwTEEiJ1kRKnRqjtar4AiEwgg4fEcAByWL4gmufGTVE1Z7PexvD6KACCsQuy2AwJhC0wEmksgUUERVBR21q0LBwFxSWRFLRGKCoXCuIJRJJZJulPsxiAA

**Related Issues:** ???

**Comment by yume-chan** [comment]
I have a much simpler example:

```ts
type A<T extends string> = T extends string ? true : false;
```

AFAIK the only way to make it return `false` without throwing compiling errors is `A<any>` (or `// @ts-ignore` or `// @ts-expect-error`, same thing anyway).

---

```ts
type A<T> = T extends string ? true : false;

class C<T extends string> {
    fn(): A<T> {
        return true; // Type 'true' is not assignable to type 'A<T>'.(2322)
    }
}
```

In this example it's pretty clear that the `T extends string` in `class C<T extends string>`, is the same `T extends string` as in `T extends string ? true : false`, so `A<T>` must be `true`.

---

If you want to consider `any`, then the following code should also lead to compiling errors:

```ts
class C<T extends string> {
    fn(value: T): string[] {
        return value.split(' '); // no error?
    }
}

new C<any>().split(42);
```

**Comment by jack-williams** [comment]
The constraints of type variables are ignored when resolving conditional types with generic conditions, so when attempting to check that `"b"` is assignable to `'T[keyof T] extends string ? keyof T : never'`, the checker ignores that `T extends Foo`. 

Does this work for you?
```ts
function getValues<K extends string>(obj: Record<K, string>, ...keys: K[]) {
    console.log(keys.map(x => obj[x]));
}
```

**Comment by impworks** [comment]
@jack-williams Thanks for the workaround. Unfortunately it does not completely solve my problem, since Typescript is unable to suggest values for this notation the way it could for `keyof T`:

![image](https://user-images.githubusercontent.com/604496/90241800-72911d80-de34-11ea-9a95-2d1818f34a07.png)

I hope this limitation will be addressed in future versions of TS.

**Comment by xianshenglu** [comment]
I guess this is the same problem?
```ts
type Te<S extends string[]> = S extends [infer A,...infer B] ? `${A}` : ''
 // Type 'A' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
