### ISSUE TITLE
Order of super() and instance variable assignment in transpiled code

### ISSUE THREAD

**Issue by monopolesystems** [microsoft/TypeScript#39799]
**TypeScript Version:**  3.9.2

**Search Terms:** order super instance variable

**Expected behavior:** logically the programmer expects super() call should come after the this.num=0 assignment in transpiled code

**Actual behavior:** super() call comes before the this.num=0 assignment in transpiled code

**Related Issues:** None

**Code**
```ts
class Animal {
  [key: string]: number
  constructor(num: number) {
    this['num'] = num
  }
}

export class Dog extends Animal {
  public num = 0
  constructor() {
    super(10)
  }
}

console.log(new Dog().num)
```

<details><summary><b>Output</b></summary>

```ts
class Animal {
    constructor(num) {
        this['num'] = num;
    }
}
export class Dog extends Animal {
    constructor() {
        super(10);
        this.num = 0;
    }
}
console.log(new Dog().num);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=2&ssc=22&pln=1&pc=1#code/MYGwhgzhAECCB2BLAtmE0DeAoa0DaA1gKYCeAXNBAC4BOi8A5gLoXwCuyARkTTtMAHt41Gm2BUBNABTtkrDtxoBKTH1xUAFogh4A5LN1NoAXmiy+AXyxWsRAB4AHSVX7go0ACICG0e1SLwACYwCChoqrgObJwgiMBmHCbQAAx8gsK0YhLSKti4uBBsDjxSAIzJSpbWWFjpEAIgRAB0IN4yRADunm1KTbJKQA)

**Comment by MartinJohns** [comment]
Duplicate of #39761.

**Comment by monopolesystems** [comment]
@MartinJohns Thanks for clarifying. I was unable to search this issue out from github. I'm closing this.

**Comment by MartinJohns** [comment]
You're welcome. Finding issues can be tricky (remember to check closed ones!), but this particular one is just a few days old and I remembered it.
