### ISSUE TITLE
Mapped object type ignores readonly 

### ISSUE THREAD

**Issue by lsdsjy** [microsoft/TypeScript#39802]
**TypeScript Version:** 
3.5, 4.0.0-beta

**Search Terms:** 
mapped object type, readonly property, exclude, lookup type

**Code**

```ts
type MyOmit<T, K extends keyof T> = {
  [S in Exclude<keyof T, K>]: T[S]
}
declare const foo: MyOmit<{ readonly a: number, b: number }, 'b'>
foo.a = 1  // expects error but none

declare const foo2: Omit<{ readonly a: number, b: number }, 'b'>
foo2.a = 1  // error as expected
```

**Expected behavior:**
Assignment to `foo.a` is an error.

**Actual behavior:**
No typing error reported.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200729#code/C4TwDgpgBAsiDyBbAlsAPAFQDRQNJQgA9gIA7AEwGcoBrCEAewDMoMA+KAXigG8AoKFADaAZSjJSUAKKEAxgBsAruQho6jFtjxsAugC5WonXwC+fFQoCGAJ2iyGpSsChMGDA3CSo0PKLcvkDvIgUJYGpIqIAEYQ1jhR4ZEx1lAmOADkUelsfK4MAHSWXFAAjIIA9OUEhJCywNSx1gwpUYrOpA4QfOYQVrZQ9o7OeQBMBl7ovv6BpMGhidGx8QvJqRlZOaOFxWVQlQTWTSmWDTW9JORAA

**Related Issues:**

**Comment by jcalz** [comment]
This is working as intended.

`MyOmit` is not a homomorphic mapped type and therefore does not copy modifiers from anything.  The type `Exclude<keyof T, K>` is not  seen by the compiler as being the keys of some type from which modifiers could be copied.

**Comment by Kingwl** [comment]
https://www.typescriptlang.org/play/?target=2&module=4&ts=4.0.0-beta#code/C4TwDgpgBA8gPAFQDRQNJQgD2BAdgEwGcoBrCEAewDMoEA+KAXigFkQYBbAS2ERQFFMAYwA2AV3wQ4ZSjWRo6dALAAoUJFbtuveeiw4CxGdVoNmAb1VQoAbQDKULrjQBdAFy17L1QF9VqyVEAQwAnaCEKXEJgKCoKCg94cygwoPxIkRAoII9cMQ4AIwgQlALc-KKQqB8UAHIC2uUVOIoAOiCmKABGawB6XoxMSCFgYmKQiiqCsRjcSIh-FUCRUPDI6Nj4gCZEuGTU9NxM7PLC4tLTyuq6hqaWrfbOnqh+jBCJqqCxoYgRiHwgA 
Seems work as your expected.

**Comment by lsdsjy** [comment]
@jcalz Thank you for your clear explanation. But I still cant understand @Kingwl 's working example using this `homomorphic mapped type' theory. How can `Pick` establish a connection between `T` and the keys of the output type(i.e. `Exclude <keyof T, K>`)?

**Comment by jcalz** [comment]
As far as I know, there are two ways to get a homomorphic mapped type.  The normal way is to explicitly write `in keyof T` where `T` is a type parameter:

```ts
type Homomorphic<T> = {[P in keyof T]: string};
```

The less common way is to write `in K` where `K` is a type parameter constrained to `keyof T` where `T` is a type parameter, which gives you a "partially" homomorphic type (see #12826), which is what makes `Pick`'s behavior possible:

```ts
type PartiallyHomomorphic<T, K extends keyof T> = {[P in K]: string};
```

**Comment by lsdsjy** [comment]
@jcalz Well, so in the `Pick` case TS sees the constraint of second type parameter and makes a homomorphic mapped type, regardless of what the type argument is? Thanks again for your patient and thorough explanation! Issue closed.
