### ISSUE TITLE
Infer generic function types from arg by way of mapped type

### ISSUE THREAD

**Issue by jared-laethem** [microsoft/TypeScript#39838]
Sorry about the title. Not sure I'm describing this correctly but the code below is pretty straight forward I hope. Thank you in advance for reviewing. 

**TypeScript Version:**  4.0.0-beta, 3.9.2

Mapped type, infer, generics, function

**Code**
```ts
type Unbox<F extends Boxed<any>> = F extends Boxed<infer V> ? V : never
type BoxMap = { [key: string]: Boxed<any> };
type MappedUnbox<F> = F extends BoxMap ? {
    [K in keyof F]?: Unbox<F[K]>
} : never

export type InferingProps<F extends BoxMap> = {
    inferFrom: () => F;
    inferTo?: (values: MappedUnbox<F>) => string;
}

function factory<F extends BoxMap>(
    props: InferingProps<F>
) {}

interface Boxed<GetValueType> {
    aMethod: (arg: string) => GetValueType
}

class BoxedImpl<ValueType extends string = string> implements Boxed<ValueType> {
    aMethod(arg: string): ValueType {
        return arg as ValueType;
    };
}

//Fails
factory({
    inferFrom: () => {
        return { // Object returned direcly.. 
            name: new BoxedImpl() 
        }
    },
    inferTo: (values) => {
        values.name; // <-- typeof values.name is "any", (not desired behavior)
        return "";
    },
}
)

//works
factory({
    inferFrom: () => {
        let x = { // Only change here is to assign this object to a variable before returning...
            name: new BoxedImpl()
        }
        return x;
    },
    inferTo: (values) => {
        values.name; // typeof values.name is string (desired behavior)
        return "";
    },
}
)
```

**Expected behavior:**
Generic can be inferred in example above whether or not map containing BoxedImpl is first assigned to a variable or returned directly from constructor. Autocomplete and typechecking for "inferTo" property on props takes into account the type of "inferFrom" property. 

**Actual behavior:**
If map is returned directly types aren't inferred correctly versus if you just assign to a variable and return that then boxed type is inferred.  

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=53&ssc=2&pln=1&pc=1#code/C4TwDgpgBAqgdgIwPYA8A8AxKEXAnAEwGcoAhVCAtAQzhAD56oBeKLHPQk8lStASzgAzCACcoANSYB+SVABcUOBABuYgFChIZVAFlqYFlADeUANoBrCCEVFgowQHMAuop59aDKAF8A3JvBofTBIAnhkdAwmVnZcfGIdFGCoWWN1KAzzAGkoQSgrECQhNmdpRXDUTDMs53p1bwUlVQ11HDAkUWAoLWgASWExJwAFUSQwIkxsOK5E4OiTdMzBEVEMUYBbRQAKAEoWJgx-TNyB0QAVJDKoLZVqABsAVwgiRWDQisj6PeYmOwc4Rz+bzqdRCB5wADGwH4SDgUCE1ChHRAkw48W4egM9C2iwyYFG40U-RWwwJEyi6j2xmB6kEeFECIh0HcVAA4hBgBJ7k8zoEmGljtRdByABZIAjbaiiRy2exOb5Mdmc7kQXmQeogiF3ahEDG8Ai9dZgO5oLmPVWBKacBJ-JxGW0Apj8I13CDrfDAPV8M08vkLQXC4BighbKUyqAOxw7RQ+i3aAXHTKiDkPURwsNQHWSFVqiBHTJ+DXqAD0xYw1H4dyIoMRwGRWwTGWWYjWSE21wV-sTGWTwFTcNMpagAHkEAArCBQqC9-uUKAEfjJrUgAB0K6guO7mTg1HdimUAHdEpRDcbdhutz5N94ADSb5vnJDbW7moidxuJl9PIgrnfu3xQEOaAALTAd0gRFFAX7PL+u7QPwJAAESeIhN7XHASBdAQzyLnOCAQCK1AqDCog7JuxwzmmUCIYh+YZLeGpkSWxYHh0FjVoydaiCADb3qcrbtuePxdt2rpdCgRiDsWI5wHcIBQBChEAtAIpiPBJB1pmur8I4cJBghUBIOOk5dJp1BQVK-DUAgrpQPhQgdNAlFwE4a4ruRW5-hA+4QEeLKnncuwefRwXTimVEoHRPh3scD4XM+KpvvsImfolsH-oB0k9JB0E-l5uQkJG1zYUQuEEHZBFESRZGXs51G0ded7AmRQA

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/38001

**Comment by RyanCavanaugh** [comment]
This is a design limitation caused by the fact that the return expression of the function is in a position where it could be contextually typed by the type parameter that it's inferring to. Factoring it into a local removes the contextual type, so we don't try to observe it during the inference process and thus avoid incorrectly fixing to `any` early.
