### ISSUE TITLE
The compiler does not allow validating for an error if it is impossible in Typescript to make that error

### ISSUE THREAD

**Issue by lsalazarm99** [microsoft/TypeScript#39847]
**TypeScript Version:**
4.0.0-dev.20200730 | 3.9.2

**Search Terms:**
TS2367, validate

**Code**
This...
```ts
function divideTwoBy(divider: 1 | 2 ): number {
  return (2 / divider);
}
```
...compiles to this:
```js
"use strict";
function divideTwoBy(divider) {
    return (2 / divider);
}
```
The compiler won't let me use this:
```ts
function divideTwoBy(divider: 1 | 2 ): number {
  if (divider === 0) { // Error: This condition will always return 'false' since the types '1 | 2' and '0' have no overlap. (2367)
    // Handle the error
  }

  return (2 / divider);
}
```

**Expected behavior:**
It is specified that the divisor can only be 1 or 2. The code in JS will have that validation since the TS compiler does not allow me to validate that it is not 0.

**Actual behavior:** 
The code in JS does not have that validation.

I know that if I generate the declarations, this error will be noticed when using JS. But the problem is not the fact that someone can skip that warning, but _the compiler does not allow handling the error in JS because for TS that error could never occur_.

**Playground Link:**
https://www.staging-typescript.org/play?ts=4.0.0-dev.20200730#code/GYVwdgxgLglg9mABAExgNxsgpgFQO5wBCAngBSobYBOAXIgIyIA+iATIgJR1ggC2ARliqIA3gFgAUIkQxgicukxDEAXjWIADB1GTp0qAAsqcPIgDkATTghEEAIZIwcKCkXZE-YprMBuXYgBfSX8qLCgQKiRSdgB6V0ohDj8JAKA

**Comment by Haroenv** [comment]
You'll need type guards for now I think:

```
function isOneOrTwo(input: number): input is 1 | 2 {
    return input === 1 || input === 2;
}

function divideTwoBy(divider: number): number {
    if (!isOneOrTwo(divider)) {
        throw new Error('input is not divisible');
    }

    return 2 / divider;
}
```

Don't think this can be done generically without specifying the output of the type guard

**Comment by lsalazarm99** [comment]
@Haroenv Many thanks. I was using the first alternative until I remembered that it is possible to specify available values (I need an integer number greater than or equal to 1 and less than or equal to 32). For now, as you mention, I will return to that first option.

**Comment by AjiTae** [comment]
If you want typing for ts and checks for js - just use overloads: 
````ts
function divideTwoBy2(divider: 1 | 2): number;
function divideTwoBy2(divider: number): number {
  if (divider === 0) { // ok

  } 

  return (2 / divider);
}

const a = divideTwoBy2(4); // Argument of type '4' is not assignable to parameter of type '1 | 2'.(2345)
````

**Comment by lsalazarm99** [comment]
@AjiTae Amazing! I didn't know about it.

One more question. In case you are dealing with interfaces, would this be the correct way to do it? I ask this because I am not getting code completion inside the function.

```ts
function divide(parameters: MyParameters): number;
function divide(parameters: any): number {
    if (parameters.divider === 0) {
        throw 'You can not divide by 0';
    }

    return (parameters.dividend / parameters.divider);
}

interface MyParameters {
    dividend: number;
    divider: 1 | 2;
}
```

[Playground Link](https://www.staging-typescript.org/play?ts=4.0.0-dev.20200730#code/GYVwdgxgLglg9mABAExgNxsgpgCgA4CGATgQLZZRZEDOAXIgLICeACsWRVdQJT1gikARlQDcAWABQoSLAQp0mXIRLlKNegTBNeifkKqIA3pMSIYwRPnaquAOlQZsRRAF43iAAzcjJ04igAFkRwAO6IAOQAmnAgiBCaunBQ8o5YiIJMnuHiEqYAvpK+RBQgREhWKpw09grYYMiIAPSIyhxq1DWpRNw5BRKSMGBqwAQQacxsle0+uSmK9XwCwkQ5pg6KRPQAjIgAPogATL1AA)

**Comment by AjiTae** [comment]
"any" is for anything, you need to specify some narrower type, something like this, I think: 
```
function isObject(value?: unknown): value is object { // use some lib
  const type = typeof value
  return value != null && (type === 'object' || type === 'function')
}

type Unknown<T> = undefined | (T extends object ? {
    [P in keyof T]: Unknown<T[P]>;
} : unknown);

function divide(parameters: MyParameters): number;
function divide(parameters: Unknown<MyParameters>): number {
  if (!isObject(parameters))
    throw new TypeError('not an object')

  if (!isInteger(parameters.divider)) {
    throw 'divider not integer';
  }
  if (!isInteger(parameters.dividend)) {
    throw 'dividend not integer';
  }
  if (parameters.divider === 0) {
    throw 'You can not divide by 0';
  }
  return (parameters.dividend / parameters.divider);
}

interface MyParameters {
  dividend: number;
  divider: 1 | 2;
}
```
[Playground Link](https://www.staging-typescript.org/play?ts=4.0.0-dev.20200730#code/PTAEFcGcFNUh7AtrANgSwEYFgBQATaAYxQEMAnWAM3ADtCAXNeG0NSAeQwCsj6AKAG4kU4aAH4AXBBoBrGvADuNAJRShI2G1DxuvULgLFyVWgyYs2ASRr1oAc2hlBw0ZNAkaAT1Wh1o1pCgNOCIGI64ETj0ngAOsACqsvJKADwAKgB8oAC80gSUaDTQeKAAPqB8aaDQAB62NHiBOjwMoGKgAN64oD2gANoACqwsMtCe8JSgaQC6UolyijTpg9MZANy4AL6gUrQLSsobOLjUdIzMoHhoAmgEfDHkJMi2ZJBSALKeA4-PjpA+wVCjiOpzMFyuNzuDzIT2gLzeoHmySWn2+MN+rwyAJCYTInW6rEmfAAhGxOC1+NDYfDlMoCT16AALMiKILQBRTWLQACiZBZTgA5PJ6O4WM1eAK6cccD00ETSZBrLYHE4qRjIAA6CG3Ry0-Ey3pMlkcgXagh44XDZWOAVHHqbAlyioKpX2Rz3H5wv5a646hp6roGhnM1mm30EBpBeAiwrWsi2gkOg1Oj3or2vH2Qxw5bK5AAMyn1vVARtDAE14OBQIQPFGRWbYBhPKA8wmDUmehR6OAyCxU9TvQ3I2A1enNQ2yIctpFY45KCRCLBUZ74UXLuHoA0pIDcXb11myFIAIxlUAAJiOmyAA)
