### ISSUE TITLE
Bug: Incorrect return type of SubtleCrypto.digest

### ISSUE THREAD

**Issue by btesser** [Microsoft/TypeScript#3984]
Currently window.crypto.subtle.digest() return type is specified as `any`.  Instead, it should be a ```Promise<ArrayBuffer>```

**Comment by mhegazy** [comment]
PRs are welcomed. here is some documentation for adding new types to lib.d.ts: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by zhengbli** [comment]
It should be partially solved by https://github.com/Microsoft/TSJS-lib-generator/pull/60, now it returns `PromiseLike<ArrayBuffer>` .
