### ISSUE TITLE
Variadic tuple behavior

### ISSUE THREAD

**Issue by MuTsunTsai** [microsoft/TypeScript#39845]
I'm not sure if this is a bug, but I just found an example where variadic tuple behaves differently in 4.0 beta version and in nightly version:

```ts
type GrowBy<N extends number, T = any, S extends T[] = [], I extends any[] = []> = {
	0: S,
	1: [...GrowBy<N, T, [...S, T], [any, ...I]>]
}[I['length'] extends N ? 0 : 1];

type LengthTuple<N extends number, T = any> = GrowBy<N, T>;

type StringAndNumberTuple<N extends number, M extends number> =
	[...LengthTuple<N, string>, ...LengthTuple<M, number>];
```

These code works perfectly in beta version, as can be tested in this [Playground Link](https://www.typescriptlang.org/play/?ts=4.0.0-beta#code/C4TwDgpgBA4gTgewO4CEQB4ByUIA9gQB2AJgM5SECuAtgEYRwA0UAKlALxQCGhIzAyjnxEyrANoBdDlEnMAkkIIlyPEJOmSAfNIDeAKACQABgBcUfo0MBGM2IB0D+MjRZmLZvYcXWEj6uYOdnISmhJ6AL5icmIA5AA2RADmwAAWMVJ4SqLYAPxQRlBmVhIA3Hp6oJBQADJJqSyUYAlYiiLkVHQMbtKq2pxOqBiYbpplFeDQ-MBwAJaEiQCCJJg09HANTRAtmW0Uq11QALKtynudcH2Gnna18-WNzcNQpNNziZoBDrfJKRvNh8wOmtQmUgA). The reason for surrounding `GrowBy` by `[...]` in line 3 is to make TypeScript recognize `GrowBy` as an array-type, so that the last line will work. If `[...]` is removed from line 3, the last line will report an error.

However the same code doesn't work in nightly version, as can be seen in this [Playground Link](https://www.typescriptlang.org/play/?ts=Nightly#code/C4TwDgpgBA4gTgewO4CEQB4ByUIA9gQB2AJgM5SECuAtgEYRwA0UAKlALxQCGhIzAyjnxEyrANoBdDlEnMAkkIIlyPEJOmSAfNIDeAKACQABgBcUfo0MBGM2IB0D+MjRZmLZvYcXWEj6uYOdnISmhJ6AL5icmIA5AA2RADmwAAWMVJ4SqLYAPxQRlBmVhIA3Hp6oJBQADJJqSyUYAlYiiLkVHQMbtKq2pxOqBiYbpplFeDQ-MBwAJaEiQCCJJg09HANTRAtmW0Uq11QALKtynudcH2Gnna18-WNzcNQpNNziZoBDrfJKRvNh8wOmtQmUgA). TypeScript complains about line 3, and I found no method to make the last line working.

I hope that the behavior in the beta version is the intended one, since I do need TypeScript to recognize `GrowBy` as an array-type. Any ideas?

**Comment by weswigham** [comment]
I don't see any errors in the latest nightly on the playground? In any case:
```ts repro
type GrowBy<N extends number, T = any, S extends T[] = [], I extends any[] = []> = {
	0: S,
	1: [...GrowBy<N, T, [...S, T], [any, ...I]>]
}[I['length'] extends N ? 0 : 1];

type LengthTuple<N extends number, T = any> = GrowBy<N, T>;

type StringAndNumberTuple<N extends number, M extends number> =
	[...LengthTuple<N, string>, ...LengthTuple<M, number>];
```

**Comment by MuTsunTsai** [comment]
@weswigham Well if you go to the second playground link I provided, you should see errors, no? I still do:
![image](https://user-images.githubusercontent.com/39870664/90831230-dc01b680-e375-11ea-83ac-c8f93078f8a7.png)

**Comment by weswigham** [comment]
Somehow you've got a nightly from two weeks ago in your playground - I don't see any errors using yesterday's.

**Comment by MuTsunTsai** [comment]
@weswigham Then I guess we have another issue that the playground does not really use the latest nightly...

**Comment by weswigham** [comment]
@orta maybe you know why the playground is retaining a nightly for so long for him?

**Comment by weswigham** [comment]
Yeah, I'm going to close this since it seems to be fixed in latest.
