### ISSUE TITLE
Superclass/subclass generic type inference produces different results depending on generic usage

### ISSUE THREAD

**Issue by chanderson0** [microsoft/TypeScript#39851]
**TypeScript Version:**  3.9.2

**Search Terms:** generic subclass infer unused

**Expected behavior:** Inference of generics shouldn't depend on the usage of those generics in the superclass. Separately, the behavior of inferring generics is confusing: sometimes they're left at the base of the superclass, sometimes they're made narrower by subclasses - is this intentional?

**Actual behavior:** Behavior depends on how the types are used, producing inconsistent results.

**Related Issues:**
- #39850 may be related, though this isn't only related to functions or overloads

**Code**
```ts
// ----------------------
// Case 1: unused generic
// ----------------------

class A<T extends number> { }
class B extends A<1> { }

type AGeneric<T> = T extends A<infer U> ? U : never;

type Ag = AGeneric<typeof A>; // number
type Bg = AGeneric<typeof B>; // number (should be: 1)

const a = new A<2>();
const b = new B();

type ag = AGeneric<typeof a>; // 2
type bg = AGeneric<typeof b>; // number (should be: 1)

// --------------------
// Case 2: used generic
// --------------------

class X<T extends number> {
    foo(x: T) { }
}
class Y extends X<1> {}

type XGeneric<T> = T extends X<infer U> ? U : never;

type Xg = XGeneric<typeof X>; // never (should be: number)
type Yg = XGeneric<typeof Y>; // never (should be: 1)

const x = new X<2>();
const y = new Y();

type xg = XGeneric<typeof x>; // 2
type yg = XGeneric<typeof y>; // 1

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// ----------------------
// Case 1: unused generic
// ----------------------
class A {
}
class B extends A {
}
const a = new A();
const b = new B();
// --------------------
// Case 2: used generic
// --------------------
class X {
    foo(x) { }
}
class Y extends X {
}
const x = new X();
const y = new Y();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/PTAEFpK6d8CgSgMIEMDOBTUBGAXKAK4B2hWAJqAOabGYBOAlgMaJhwdzzzMA2G6UAEEAPABVQmAB4AXWuUGkAtgCMGAPlABvUAF8e-dIIBCk2fMGicmnfvgyAngAdsQgOK0GLcZoC8oCWk5YgVhEUZiADMGUABVTQB+ONACOgA3BgBubkcXYSpQf3dPJmYRXMwAe0jhdUzQJGU1entnbGMCoo86UvK26tBjOoawJpiACnQAC0rCXko1AhwASm5mSuJ0GVBUQtA6AHcwgCZ1ceXs9c3tlT3DwfPs1rzUTuFurzKKgdRhpGPntgVG9ij1vN8aio-qNCKoJtNZvNQItcKs2BBOJj0WgsKBjgQyJhKDQwawkJisQYBKAABriMzBUJjeg2eCgdmgSKVSrjKQEMTLbR6eD6PjUgCaDIstJE1m0dgqtI+vTEfgCUpCgjpEWi9DiiWSqUwGXoT0VNLeNOV4P6NRp0P2xvhMzmC0wqVhzVWivFlutX1toHFDvSzsRbqWaKuW1AUjumCOdNOjx4GxjDnjR3FKcBsb9JRtLgGUgdAMVDnzpL6RZqDgdOHgQA)

**Comment by stephanedr** [comment]
@chanderson0, `A`, `B`, `X` and `Y` are already types, so you should not use `typeof`.
Removing `typeof`:
```
type Xg = XGeneric<X<number>>; // number
type Yg = XGeneric<Y>; // 1
```
You can add a default for `T` (`class X<T extends number = number> {...}`) to allow `type Xg = XGeneric<X>; // number`.

However you still get `number` for `B`.
The reason is that you need to declare a member, or a method with an argument (as in `X`) or return value of type `T`, in order to "capture" `T`.
Adding a member (that you don't need to assign):
```
class A<T extends number = number> {
    private _?: T;
}

type Bg = AGeneric<B>; // 1
type bg = AGeneric<typeof b>; // 1
```

**Comment by chanderson0** [comment]
Thanks for the clarification; my mistake for using `typeof` on a type. The "capturing" behavior is still confusing (did I miss documentation somewhere?), because it doesn't seem to be well respected. A few illustrative cases below:

The first case that's confusing to me is that extensions of the generic type don't seem to cause any capturing:

```ts
class A<T extends number = number> {
    foo<U extends T>(u: U): U {
        return u;
    }
}

class B extends A<1> { }

type AGeneric<T> = T extends A<infer U> ? U : never;

type Ag = AGeneric<A>; // number
type Bg = AGeneric<B>; // number (should be: 1)
```

[Playground Link](https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAECCA8AVaBTAHgFxQOwCY2wFcBbAIxQCdoBeaIsygPmgG8AoaT6AMwHtf4AVVSYc+aIkYAKQgC5oggJTzh7LuugUUGQhWzRCAbg5cAvm3NtQkGACERWPDAQBGZi2iWMATwAOKOABxHEoAS2AkZlpkdEdxBFDsbkoFZgB+BWh5bBQAN0pjNh9-OABzGiCQinD4WEZDaAB6RroScgoivwDbctpYYJzqiNt6ppb6dugpCAALXkIQXGhyeRdFNiA)

And then there are several more behaviors that don't seem right. Note how in case 3, there's a whole new type that hasn't shown up anywhere.

```ts
// ----------------------
// Case 1: captured types
// ----------------------

class A<T extends string | { [k: string]: number } = string> {
    _t?: T;
}
class B extends A<{ one: 1 }> { }

type AGeneric<T> = T extends A<infer U> ? U : never;

type Ag = AGeneric<A>; // string
type Bg = AGeneric<B>; // { one: 1 }

// ---------------------
// Case 2: derived types
// ---------------------

type KeysOrString<T> = T extends string ? T : keyof T;

class X<T extends string | { [k: string]: number } = string> {
    _u?: KeysOrString<T>;
}
class Y extends X<{ one: 1 }> { }

type XGeneric<T> = T extends X<infer U> ? U : never;

type Xg = XGeneric<X>; // string
type Yg = XGeneric<Y>; // "one" (should be { one: 1 })

// ------------
// Case 3: both
// ------------

class M<T extends string | { [k: string]: number } = string> {
    _t?: T;
    _u?: KeysOrString<T>;
}
class N extends M<{ one: 1 }> { }

type MGeneric<T> = T extends M<infer U> ? U : never;

type Mg = MGeneric<M>; // string
type Ng = MGeneric<N>; // "one" | { one: 1 } (should be { one: 1 })
```

[Playground Link](https://www.typescriptlang.org/play/index.html#code/PTAEFpK6d8CgSgMIEMDOBTUBGAXKAMaoAOALgK4BOmAJqGQJ4mbqJhydzzyEA2GdKACCAHgAqoTAA8ymAHa0h6MlQCW8gOagAPqADeoANoBrAivVaAugXkUAtgCNMVUAF9QAXlAWNmgHwG8KAhoAD6ZAD8BOIA3PBuvALoQgBCUrIKSiKihgD28pgEOO6BhonwTCwiAOIKLmqEEoHekjJyikJiGgBmLqAAqoGRg6C2mABuLvGVzNjC2t7CdYXqTcL+saBIvlqz1amLtfVroqmb22D5hcXuPEhcj5DsKBjYAEwEtA1T9FWsLyejx4-1AAGlMIx0AB5KgAZVUfmaXlAbUynR8iK0oBGkgIJkheR6qJm-EEoAAGhIMh1srttHpDKZzFjNDZQHYnP0PN56WVgqEwhRouDITD4azmvFEmSUqAAJo0rJCKnXIq4UoGO77bAUlYNJriFqopUYqm9fpDHGjcZTKgzUEUo56k6NUQUi47Vk6hXO-WneWesAAIgKmGDoAAFOgABZ5Ch8ejOLVh25uACU9w4TxeaCwoAAzARHHkyDHATmkuSALLU9rKzGWBla5mNvzsznOVw8ttafmhcJRGLxAdCkUQqGwhFNqUJKtygBypuytbVabK2tB1f9bqNKLRtKEtYtritIwGYw5k2mILmoGrR23rqa1aDvc0PoXj53TQXb9DhQRoyoCphqHjRnGCZJtga5gZmQA)

The original motivation for this was usage of the [eventemitter3 types](https://github.com/primus/eventemitter3/blob/master/index.d.ts). 

```ts
type Events = {
    one: [1],
    two: [2]
};

class MyEmitter extends EventEmitter<Events> { 
    foo() {
        this.emit('one', 1);
    }
}

type EventEmitterGeneric<T> = T extends EventEmitter<infer U> ? U : never;

type MyEmitterEvents = EventEmitterGeneric<MyEmitter>; // "one" | "two" (should be: Events)
```

Including type definitions: [Playground Link](https://www.typescriptlang.org/play/index.html#code/PQKhCgAIUhZBLAdvAtgQwDaQAYFEBuApogC64rwkmEBO2kS1NAZmgMaGQkAWaJDAZ0goA9hgAmhcZDQBzNEgH8enAHIjJAOgBWAqDDxFS5Sk3qNarDpv3BwkthjQ1OjtAKEFiZClVoAeKEgvUgAVAE8AB0IhQgAPakRxTyMfU1pNADVMeHEQkgjooQBeSCUaJFlIAB8y8JQAIzEAGiCAYRFSeP5u4mSZRHDIUrRB8AA+SABvIMgykj54NkhIl2Z4OKkALnmKxCraprFCUYBucCDQCDnoSAAlQhIAVxpEAZkaGjQhjHglSq43E4hFSQmYIhokAA7twltxAcDfExILwhC5ZH8mFJZjBfkpiLQBDYbiA7HMQd5VGgUDEABQASh2AEFPt9-PkTH4aJp8lSaQJ2alCjFxuNzpcwDj7o8Xm8VJA8YlCZB0ZjaFJIODIWhIBijJAKaRiXNSUFFQSaALQgaEn0Ut5OUweak+TFBd5hQJRbTZgbUjtQkFGZAWV9wu7jEiMvkADJqxABfKe5qQUKi8VzK5Sh7PV4IyCIJ6NWiQETMBXx5Xm5D7LgiGS6+D6w0kY3QMkV-EJmgdJ6kWktnYcqPc3nUt1JqIi4OF4s0DOQLMkyBtTAYWLseFl-PV5Wq-EuaRaht64h+7xt03k3z+a29JL2yPpUcu8cCydFb2+wep1o3SCaIBziyAIQ6pI60apCyIERgUU4CCmaZBjsRwYCciALkuJohuI0g6rukLHjqp5vC2l4dp0t42ok-TDs+zqUm+sGel+-4-qEf43MwiBgQ6I4MaQcZdomQrwYh4ycXMbCdNQCQAPw7B0XQJMhgJ-OccxoLhQlKjQVH3rR4H8WO-LMfBrE3OxkmajxwRGfRsaVnpH4xOJ1nScpJAKSuMndKpPDqRcmaSsuTK4Q2nSEAAtCQqCcARmoQieTZnmROIUYgHD6baD52XxDmvqZLleuMPpsf6v6+txvFPlyAkkDpFpmUUbm+h5sleYpvkqXMwYBQImEhdhDyiEQO5OUI27ESlpGpORQQuKNhCNd22U0Y+aR1SZE6iZ+pXfhVHFVYg3l0VtqQrSJHpiamEltd1nU+Z51mdBw3moeh-mwgNQRlswa12nltVOtt767SK+3ld4AbWdxp32ed3iXc54MIbd7kPd5SkdS9mWEO9IjHKMX2BRK1zDYQS0yBgWAEWjSU8CIAicNu8oCNEbDwOsGppSSHaLSIRBMjTyMCAOqTw-liOkK6YPXZ+fXfecAC+FwOE4LgFm+kTsJwZ3IjM5JxJEEL8BYLC65AyMAGKIP40GxDl-SjOEADaAC6wwDG77uTIbNy0oBmjAaBIY0CBwb4CIuQaZAqtBPEJs0GbXQWxwQObUwADKCyxcs-tzAmUKQIE-5zMV1GA9kvx5KjXvlACtQCPUTQYNZczY90Xsu76pXBvrV1hDdncJGKQTx0bSfKFOkDV7kFfFL6TckHsshL3UjRiOvUyQK7ADSDBvA3tZNy3YjuzsLsezUkC0oHQHh6HV-u-SwyTFHuSv8rC6J6bXAz6DAGuU5613liKL2d4nZCGPgcDerdfRyVTL6HYABrQg4RtyhB-sbP+JAZ7QSLN4WAaBIhAP6CIBo2hCBsBIJMUoBdd4HyQJANBGDyyhAvqmfensDJCHvsHR+l9Bge1fsUd+0dxC+jmIggACs4ccTArTcPGFIyAAZuGV1ys-VRiDQjcNUUIn2sdv5BRtFPf+0QM7I1LjcSB61Z45FAUPFqvoD68IzrLW8Ki5h0NTJo-oMCb7N03hgBBt8g4h0MSIt+kAP6SP-DsfhkSw6yEIaQYhpDcBxEcE8SQt4UyBNPiE0U3DRHiJjqY3+ycLF6ygo-Gxcw7FV0ccVaybioEeKYkhHxXs5FfBpIo2C1iOKQD3umSpODqkeSUBnCCNAaqZ1oDnRYbAVYXGAMASAABVAQchCAXDwZY-IJRpi+kijsV2ABGd21kSBQhEBcgATO7cAJjwBuA8HAcIcz-EbTmbBL00xIBVUJgyU5Zcbj9U0JTSgtIADkkU4UpkufSWOcxVbx0ObUqWTAADiFolheIgb82ZI5-BIGYCWLZkxEFbLUQWCk84Dkz1gN8kcxyvYDxoPi7shLWVzLFIuTZAAiSKwqb7CruSIcVtIBDcBEE8CQkAGiEAWQIek4AgA)

**Comment by stephanedr** [comment]
Look at the [FAQ/generics](/Microsoft/TypeScript/wiki/FAQ#generics).

In the FAQ they only mention to add a member of type `T`, whereas, by testing, we also see that a method argument or return value of type `T` is OK too.

I'm not an expert of TS, so my feeling (just my feeling) is that in all the cases you don't specify `T` directly, but a type derived from `T` (`U extends T` or `T extends string ? T : keyof T`).

However, with `T extends string ? T : keyof T`, `Yg` should be `string | {[k: string]: number; }` (no members of type `T`).
It seems TS considers it has captured `T`, whereas it is `keyof T`...

**Comment by RyanCavanaugh** [comment]
You're observing that generics behave differently depending on their *variance*, which is the intended behavior.
