### ISSUE TITLE
Syntax highlighting not working properly for template strings.

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#3985]
![image](https://cloud.githubusercontent.com/assets/937933/8837389/1e6628fc-3094-11e5-82d9-0ac6814f4894.png)

Can be seen at [playground](http://www.typescriptlang.org/playground#src=%60%24%7B%60%0D%0A%60%7D%0D%0A%09interface%0D%0A%60%3B).

**Comment by DanielRosenwasser** [comment]
So there are a few elements in play here:

1. In VS 2015, you will currently get the same results. See "[Why does the lexical classifier sometimes give inaccurate results for nested template strings?](https://github.com/Microsoft/TypeScript/wiki/FAQs-for-API-Consumers#why-does-the-lexical-classifier-sometimes-give-inaccurate-results-for-nested-template-strings)"
2. We are working on using the syntactic classifier in VS 2015 again.
3. The playground is going to be updated. In VS Code, this is fixed, so the playground should eventually be fixed
