### ISSUE TITLE
Quick Fix: Wrap in Array

### ISSUE THREAD

**Issue by MohamedAlFahim** [microsoft/TypeScript#39863]
## Search Terms

- quick fix
- array

## Suggestion

Certain type mismatches can be resolved by wrapping the value in an array (i.e. by adding square brackets around the value).

## Use Cases

For instance, a user might wrongfully pass a number to a function that expects an array of numbers.

## Examples

```typescript
function get_sum(numbers: number[]): number {
  return numbers.reduce((a, b) => a + b, 0);
}

console.log(get_sum(0));
```
causes `Argument of type '0' is not assignable to parameter of type 'number[]'` error.

The solution is to change:

```typescript
console.log(get_sum(0));
```

to

```typescript
console.log(get_sum([0]));
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This doesn't seem like the kind of thing that occurs frequently enough to justify the cost a quickfix.
