### ISSUE TITLE
TypeScript Bot Sync Is Broken

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#39869]
https://github.com/microsoft/TypeScript/issues/38510#issuecomment-667805503

https://github.com/microsoft/TypeScript/runs/939136680?check_suite_focus=true

```
Run git config user.email "ts_bot@rcavanaugh.com"
  git config user.email "ts_bot@rcavanaugh.com"
  git config user.name "TypeScript Bot"
  git fetch origin master
  git merge master --no-ff
  npm install
  npm test
  git push
  shell: /bin/bash -e {0}
From https://github.com/microsoft/TypeScript
 * branch              master     -> FETCH_HEAD
 * [new branch]        master     -> origin/master
merge: master - not something we can merge

Did you mean this?
	origin/master
```

**Comment by orta** [comment]
Could be using the checkout action which doesn't grab history

**Comment by DanielRosenwasser** [comment]
Just switching to merging from origin/master would do it though, right?

**Comment by weswigham** [comment]
It needs a `fetch` command now, to get the ref.

**Comment by weswigham** [comment]
But moreover, I probably wanna change it to actually delete the branch, then rebranch master, reset the version, and re-lkg; so none of this merge conflict malarkey happens when people cherry pick before they were supposed to.

**Comment by weswigham** [comment]
I added a workflow trigger (so you can trigger it from the GH UI, in addition to from the bot), and updated it to fix the issue - it just wanted the branch ref to be named `origin/master` instead of `master`.
