### ISSUE TITLE
Modify AST before type checking?

### ISSUE THREAD

**Issue by m93a** [microsoft/TypeScript#39866]
## Search Terms
Compiler API, transform code before type-checking, change AST after parsing and before emit.

## Question
Hey,
I know questions shouldn't go here, but I've already asked [on StackOverflow](https://stackoverflow.com/questions/63105982/how-to-transform-typescript-code-before-type-checking-using-compiler-api) and in the TS Discord, but I still wasn't able to find an answer, so I thought I'd try it here. I want to use the [Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) to **parse a TypeScript file, modify the AST and *then* emit the program**.

Specifically, I want to find all occurences of `a + b` and turn them into `op_add(a, b)`, but I want to type-check the code *after* the replacement. (My motivations are explained in the [SO question](https://stackoverflow.com/questions/63105982/how-to-transform-typescript-code-before-type-checking-using-compiler-api).) However, if I modify the AST after parsing (`ts.createProgram`) and before emitting (`program.emit()`), it fails with an unspecified error.

### Code
`sample.ts`:
```typescript
let a = { a: 4 }
let b = { b: 3 }
let c = a + b
```

`index.ts`:
```typescript
import * as ts from "typescript"
import { possibleChildProperties } from "./visit";

let program = ts.createProgram(['sample.ts'], { target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS })
let inputFiles = program.getSourceFiles()

let outputCode: string

for (let input of inputFiles) {
  if (input.fileName === 'sample.ts') {
    ts.visitNode(input, visitor) // modifies input's AST
    break
  }
}

let emitResult = program.emit() // fails



function visitor(node: ts.Node): ts.Node {
  if (node.kind === ts.SyntaxKind.BinaryExpression) {
    let expr = node as ts.BinaryExpression

    if (expr.operatorToken.kind === ts.SyntaxKind.PlusToken) {
      return ts.createCall(ts.createIdentifier('op_add'), [], [expr.left, expr.right])
    }
  }

  return visitChildren(node, visitor)
}

function visitChildren(node: ts.Node, visitor: ts.Visitor) {
  for (const prop of possibleChildProperties) {
    if (node[prop] !== undefined) {
      if (Array.isArray(node[prop]))
        node[prop] = node[prop].map(visitor)
      else
        node[prop] = visitor(node[prop])
    }
  }

  return node
}
```

### Error
```
/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:100920
                throw e;
                ^

Error: start < 0
    at createTextSpan (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:10559:19)
    at Object.createTextSpanFromBounds (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:10568:16)
    at getErrorSpanForNode (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:13914:19)
    at createDiagnosticForNodeInSourceFile (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:13808:20)
    at Object.createDiagnosticForNode (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:13799:16)
    at error (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:35703:22)
    at resolveNameHelper (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:36602:29)
    at resolveName (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:36274:20)
    at getResolvedSymbol (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:52602:21)
    at checkIdentifier (/home/m93a/Dokumenty/tsc-experiments/node_modules/typescript/lib/typescript.js:54434:26)
```

---

**So how do I modify the AST before type-checking? Is there a way to do it?**

**Comment by Kingwl** [comment]
After edit the ast, you should write back into the disk/memory, And re-create the program in my memory

**Comment by MartinJohns** [comment]
You might want to check out [ts-morph](https://github.com/dsherret/ts-morph/tree/latest/packages/ts-morph).

> TypeScript Compiler API wrapper. Provides an easier way to programmatically navigate and manipulate TypeScript and JavaScript code.

**Comment by m93a** [comment]
Hey,
thank you for the quick replies!

> After edit the ast, you should write back into the disk/memory, And re-create the program in my memory

I know that when I modify the AST, printing works. But then I would have to parse the intermediate files again. Performance-wise it's probably not a big deal, but I want to integrate the transformer into an IDE and I'm afraid that hooking all the language services to the transformer will be much harder if I can't use the same `program`, but instead have to construct a new one for each request.

> You might want to check out ts-morph.

Thank you for the sugestion, I have already checked ts-morph, but I don't think it supports AST modifications before the Type resolver (let alone before the [Binder](https://github.com/microsoft/TypeScript/wiki/Architectural-Overview), which would be even better for me). But I'm not entirely sure, so I [filled an issue there](https://github.com/dsherret/ts-morph/issues/843). Sadly, it's still without a response.

**Comment by m93a** [comment]
The SO question already got [a working answer](https://stackoverflow.com/a/63259927/1137334), so I'm closing this issue :)
