### ISSUE TITLE
typeof (arg) == 'number' no longer always narrows arg to number

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/TypeScript#39879]
**TypeScript Version:**  3.9.2 (also happens on 4.0.0-beta playground)

**Search Terms:** typeof number

**Expected behavior:** arg after the type guard `typeof(arg) == 'number'` to be of type `number`

**Actual behavior:** In the below code example, the typeof guard does not fully narrow down to `number`. Instead it narrows down the variable to `number | (string & {})`, causing any subsequent numerical arithmetic to result in a TS error. Strangely, if I wrap the `typeof(arg) == 'number'` to its own custom type guard function, the variable properly narrows down to `number`

**Related Issues:**

**Code**
```ts
import * as React from "react";

function isNumeric(arg: any): arg is number {
    return typeof (arg) == 'number';
}

const style: React.CSSProperties = {
    height: 20
};
const h = style.height; //string | number | (string & {}) | undefined
if (typeof (h) == 'number') {
    const h2 = h + 20; //number | (string & {}) ????
}
if (typeof (h) === 'number') {
    const h3 = h + 20; //number | (string & {}) ????
}

if (isNumeric(h)) {
    const h4 = h + 20; //Works!
}
```

<details><summary><b>Output</b></summary>

```ts
function isNumeric(arg) {
    return typeof (arg) == 'number';
}
const style = {
    height: 20
};
const h = style.height; //string | number | (string & {}) | undefined
if (typeof (h) == 'number') {
    const h2 = h + 20; //number | (string & {}) ????
}
if (typeof (h) === 'number') {
    const h3 = h + 20; //number | (string & {}) ????
}
if (isNumeric(h)) {
    const h4 = h + 20; //Works!
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ssl=15&ssc=26&pln=15&pc=33#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdBArgHb7AQtzCoByTILFGC4AFMigBzAFwoWATwCUsiZO7oWAgEZC4AbzpwjcSjCZQuMeWCwQCccVMVwAvC7gByTSB1QP9AF8GXE5UeDD5ABssWWw8GAA6AGEAZRSABWIbWGAsdHcDYzgACyxgSWKYWQAmAAY6APoQljCS1zgI6ITS8sqaOAB6AbDhFjUAHzhvXzhJ0RHgMbgAMn0A50nWABMsAkWsLbpge1ErGzsHYuc3T2mhD2dC42bW4ur24rgAajg6-qG7lBZg4FktVnp1nAAPwwqENI4nM62E5XVw3Lzae6PQzPULwYoAZg+31+tX+A0BwPmMFGanBkNhcKCCIcPH4gmEYiu2KKL3xABZiT8-oMBgB1aAAa1QAEIGkA)

**Comment by MartinJohns** [comment]
> Strangely, if I wrap the typeof(arg) == 'number' to its own custom type guard function, the variable properly narrows down to number

That's not strange. The compiler does not verify that the logic in your custom type-guard function makes sense. All it cares is that you return a `boolean` value, which you do.

---

Also, the behavior of TypeScript regarding this did not change. The behavior you observe happens on every version available in the Playground, at least back until version 3.1.6. Only in version 3.0.1 there's no error.

**Comment by jack-williams** [comment]
Type guard narrowing is different to `typeof` narrowing. 

Type guards uses assignability to remove non-assignable cases (like `string & {}`). Type tests (`typeof`) use a fact system where the facts of `string & {}` are the facts of `string` and facts of `{}`, and because `{}` might be a number it is retained.

It is probably best to avoid types like `string & {}`. If you need them for branding reasons, then you will have to use custom type-guards.

**Comment by jumpinjackie** [comment]
Thanks for the explanation @jack-williams

**Comment by Philipp91** [comment]
[Here](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200807#code/PTAEEkBdQQwGzqAzpGAnSTQHcCWkALUQ3LFNGAOwHMBTUAV0twHtLiBPAB1oBocCuAMZFaSJLUqRc8OB1BCWAWzGgAZmmWgCtNLQBcAKBDbIkLkn0hq+AgwBGAOkVLgGycOBDxkbrWD2cCz2wEowKLrAuJQAJrQAHo4xjpjGYADKPEK4asKyHPwASrQwQtAMElgABgDC6emOAAqaPBi4YgA85NHUoAA+oJQMSva6AHxVsLHEOqBVOrjUBJCTXC26vqBsM7r0BOGwnDzIuEq4cOjELDOkRr7HAKrMbAAqfqAAvIPDo2j9oAAKbo0UAAMlAAG8AL4ASgA3GkIKA6NAYHMUBw4GJJsEAFa0Mo4WyHea0RbLVbrDDyKgxJHYKjQSDXLgMaD4UDRZkkoYjXSTXK0OAxIxY6C8-TfPloBGIgEARhhoAA6jp2IR6Pd6KRQHEhBc9HTtgA3UBhIb5KZ0tGKShCPSQejG+AMbVYcJIRaUWh07n4fi0Y26DgkEHYFhoADWWFy3schltKFAxvlkqerEob2OXwArAicoCtSw1Mn5Z8Pl8AOS836VpW8z6l2UmAEAJiVqskO2TLvoLlUGi0VC29nxZX4HPDUawzJY8cT7KUXDgwnwcizPoA8qOCdAvhDBcL9DmoQiF8nW2nnpn3l9TsvV5B134Ytux5BHIeYvmSwCiyXjVbcsqxrXQ6ylRtAObMAAQAZg7NVu2dOBXQUZQB00JQpjmKgOCqABaLUjR3ccdj0St3XYXRNDQAMg3VAgWAYJYkNg9R2mFbQDg1UA0HJJk-HnNgk1wt9d0lXDGwPDiRRPM9hOgY1YKvDMN0bUSSI-L8f0LPxi2TNiKxAn4wPrYZINguFQBMABRNAaMlNTK3TV4-ErTksEoFhUXEL0YECTVri1UBqxMtBK3jOUABYlQAQWmT0zgNOQiUIbCuV0NRSj4UBAy7AsOVaNRdxSvUDVUHi1hYVpfHjDK0CyoR6HAKRMuyyFDFALr2KFEVQBcm8eARKEEwUo4t00yUWsdBr2v3L9JTk0bKCTY0opU1zs3G19NM-GSdL-PSAKi4CQtA8KzKwr41qs2z7IjRz3mc68N3cnUvJ8z1qEofysSucazrCiLDDlHMlSgCjuyQGAVE5EseOdPjfvoGIWDEShK2gJAshyeQeL4pYBOOGBqBgaJcviB9sifDgjHPY0c0bIixLKPbetusAADlrgGtSdD0Orf3-ZNGaMwHpXAhtrrzaywDshzQCc3m3I8wZvNgXzvuR-7gtCiX4yAA) is another example that shows that it's not the `string&{}` type alone, but also the fact that it's read from an object property as opposed to a regular variable.
