### ISSUE TITLE
Project too large for TS Server to handle

### ISSUE THREAD

**Issue by fab1o** [microsoft/TypeScript#39884]
- VSCode Version: 1.47.3
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Open a large JS project on VSCode
2. Wait a few seconds

Does this issue occur when all extensions are disabled?: Yes

**Getting warning message:**
`
To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.
`

**jsconfig.json**
```json
{
  "compilerOptions": {
    "experimentalDecorators": true
  },
  "exclude": [
    "**/node_modules/*"
  ]
}
```

I noticed that **tsserver.log** was watching a lot of files, because the project is very large. I was able to reduce the size by excluding more folders on `jsconfig.json` above, like the "dist" folder for example. So the file looks more like this:
```
  "exclude": [
    "**/dist/*"
    "**/node_modules/*"
  ]
```

So I'm not having getting this warning/issue anymore, but I can reproduce it again by removing the folder from the config/exclude, which makes me think there's a limit we may reach again, at currrent configuration, if the project keeps getting larger and larger.

So this is just a report to hopefully allow the VSCode team to improve this in the future.

**Comment by mjbvz** [comment]
Moving upstream to TypeScript

@fab1o Excluding `dist` sounds correct. Are there any other folder in your project which contain JavaScript or TypeScript code but are not really part of the project?

Also have you tried following [our guide for working with large projects](https://code.visualstudio.com/docs/typescript/typescript-compiling#_working-with-large-projects)?

**Comment by mjbvz** [comment]
Closing as not actionable without more information

If you see this again with VS Code 1.53+ and TypeScript 4.15+, please try following the large project instructions. If there still seems like a bug, please let us know

**Comment by dpkirchner** [comment]
Is there a way for us to configure the extension to remove the guardrails for large projects? I don't mind if things are a little slower.

In any case, ideally, the error should tell us what the file limit is so we know how much we have to trim (if it's even possible to trim).
