### ISSUE TITLE
Overloaded function calling overloaded function

### ISSUE THREAD

**Issue by jmezzera** [microsoft/TypeScript#39885]
**TypeScript Version:**  3.9.2

**Search Terms:**

**Expected behavior:**
Being able to call an overloaded function with the union of types derived from the overloading of another function. In the provided example, in `C2Wrong`, `param` can be either `A` or `B` (nothing else), and method `method` on `child` accepts both `A` or `B`. Is there any reason why I should check myself? Doing so results in nonsense redundant code `C2Ok`.

**Actual behavior:**
The compiler complains about the types.

**Related Issues:**

**Code**
```ts
class A {
    prop1: string;
    constructor(prop1: string){
        this.prop1 = prop1
    }
}

class B {
    prop2: string;
    constructor(prop2: string){
        this.prop2 = prop2
    }
}

interface i1 {
    method(a: A): number;
    method(b: B): number;
}

class C1 implements i1 {
    method(a: A): number;
    method(b: B): number;
    method(param: A | B): number {
        return 1;
    }
}

interface i2 {
    method(a: A): number;
    method(b: B): number;
}

class C2Wrong implements i2 {
    child: i1 = new C1();
    method(a: A): number;
    method(b: B): number;
    method(param: A | B): number {
        return this.child.method(param);
    }
}
class C2Ok implements i2 {
    child: i1 = new C1();
    method(a: A): number;
    method(b: B): number;
    method(param: A | B): number {
        if (param instanceof A){
            return this.child.method(param);
        }
        return this.child.method(param);
    }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class A {
    constructor(prop1) {
        this.prop1 = prop1;
    }
}
class B {
    constructor(prop2) {
        this.prop2 = prop2;
    }
}
class C1 {
    method(param) {
        return 1;
    }
}
class C2Wrong {
    constructor() {
        this.child = new C1();
    }
    method(param) {
        return this.child.method(param);
    }
}
class C2Ok {
    constructor() {
        this.child = new C1();
    }
    method(param) {
        if (param instanceof A) {
            return this.child.method(param);
        }
        return this.child.method(param);
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.staging-typescript.org/play?#code/MYGwhgzhAECC0G8BQ1XQA4CcD26CMAXNBAC6YCWAdgOYDcKaw2lpmArsCdpgBRa6FiZKtQCUyNJOgkAFuQgA6fvmgBeDDnwNUAXyR6koSDABCibRtwAmIqxH1JTFmQ5deym0Io1xFybPklTSs1S3QrCz0DKhIAU0wAMzBgWOhyPHNJAFtY2WwAEx4wIlhRIko2LIAjeIc0HLzCqqITMugK6tr9JENwKGgAYQzyLPQQWJzKEhh0zPrcmQKikraOmsw61AbFppbVyvXN6G2l9DBMMCyS6AAfaFbyg-i5qWhMXLZMSmg8I6iemLxJIpNIhCTzRrLOD7TobCwnXb3GGHbq9YyDKwAdRwNDSo3Gk2moJe0GAchA+SIs3UlFiAHdBngeKIjgioaVHrDWQsls0kZyUdkeYUzhcrnBbvz2k9MCTJO8SJ9vgFFGTyBSFGzRZcWZFukZ+gMrAB5ADWeLGE1iUxmYIsaopVIyNPpjOZ3MhxWhAq6QshfIe0q58OFfHOl2ud0Da2e4Ne5AS0DDYrSzjAlBS2ETpTjrzQCqV0jkqvJ+U1oe1WV1eegehrBa+RcCDrLWvDVb++iAA)

**Comment by DanielRosenwasser** [comment]
Seems like a duplicate of https://github.com/microsoft/TypeScript/issues/1805

**Comment by jmezzera** [comment]
Seems like. My bad!
