### ISSUE TITLE
Missing property types on the function object

### ISSUE THREAD

**Issue by samuelhulla** [microsoft/TypeScript#39886]
### Information:

- **VSCode Version**: 1.47.3
- **OS Version**: Darwin x64 19.4.0

### Steps to Reproduce:

1. Create a typescript project with enabled live typescript check in vscode.
2. Attempt to access typescript function properties

```ts
const example = (
   callback: (...args: unknown[]) => unknown
): void => {
 try {
    callback()
 } catch (e) {
    const raisedError = {
       name: callback.name // <- issue here
       // ....
    }
  }
}
```

The following line produces the following error:
```ts
name: callback.name // Property 'name' does not exist on type '(...args: unknown[]) => unknown'
```

Despite the fact these properties are accessible in the [`Function`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) object.

### Other information:

 - Typescript in my project (`package.json`) is "`ˆ3.9.7`" *(which is the latest version as of the day of this issue being posted)*
  - In my `defaultSettings.json` the `typescript.tsdk` is set to `null` (so it should use the latest version from package.json if I'm not mistaken)

 - Does this issue occur when all extensions are disabled?: Yes
 - This issue **does not** occur, if you try to reproduce it on 
      - [Codesandbox.io](https://codesandbox.io/s/ramda-typescript-2bv7t?file=/src/index.ts)
      - [typescriptlang.org/player](https://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABAQQBQQIYBssCMMQDWAXIqgHSUYBOA5gM6kZgCeA2gLoCUiAvAHyJmLHgG8AUIimIo1FognSliTDnxFUXANyTpAXxUYoEABZkApmN3KVCenCznyWOLXTY8BQuTAYAtpbWiHriekA)
      - atom (with ts extensions)
 
- Link to [StackOverflow thread](https://stackoverflow.com/questions/63214752/how-to-properly-type-a-function-to-acess-its-properties)

**Comment by mjbvz** [comment]
Works fine for me in VS Code insiders with TS 3.9.7 and with latest TS nightlies:

<img width="1403" alt="Screen Shot 2020-08-03 at 1 01 39 PM" src="https://user-images.githubusercontent.com/12821956/89222249-95e0e080-d589-11ea-8c7e-fd80b6aa78e2.png">

Do you have a tsconfig? If so, can you share it

**Comment by samuelhulla** [comment]
@mjbvz 

```ts
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./lib",
    "baseUrl": "./src",
    "strict": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "**/__tests__/*"]
}
```

**Comment by mjbvz** [comment]
Still doesn't reproduce for me. Do you see this same error if you open a new folder in VS Code and create a single TS file with that content?

**Comment by samuelhulla** [comment]
@mjbvz  Hmm strange, indeed. Seems to work fine in a new file. Here's the [link to the file in question](https://github.com/samuelhulla/react-eformless/blob/026d288aea749e87f4463f5e99816c7a0ab4d108/src/util/errorChecking.ts#L4) 

Also the entire repo is publicly available, so you can check the entire setup.
https://github.com/samuelhulla/react-eformless

**Comment by samuelhulla** [comment]
@mjbvz  Actually I found out the issue which was causing it. In `tsconfig.json` I had to change my `target` from `es5` to `es6` because the interface for function was only introduced in `lib.es6.d.ts`

**Comment by mjbvz** [comment]
`Function.prototype.name` was non-standard before ES6 (although widely supported). This error is likely by-design but I'll wait for a TS team member to confirm

**Comment by RyanCavanaugh** [comment]
Compare
https://www.ecma-international.org/ecma-262/5.1/#sec-15.3.5
to
http://www.ecma-international.org/ecma-262/6.0/#sec-function-instances

`name` is only present in the latter
