### ISSUE TITLE
Unexpected intersection in mapping type

### ISSUE THREAD

**Issue by markboyall** [microsoft/TypeScript#39905]
**TypeScript Version:**  3.9.2, issue still occurs on Nightly

**Search Terms:** intersection, mapped type

**Code**
```ts
interface EditState {
    sharedProperty: number;
}

interface EditStateOne extends EditState {
    property1: number;
}

interface EditStateTwo extends EditState {
    propertyTwo: number;
}

export interface EditStateLookup<T extends EditState> {
    [key: string]: T;
}

export interface EditStateLookups {
    editStateTwo: EditStateLookup<EditStateOne>;
    editStateOne: EditStateLookup<EditStateTwo>;
}

export interface EditStates {
    lookups: EditStateLookups;
    nextEditorId: number;
}

function underscoreKeys<T>(_object: T): (Extract<keyof T, string>)[] {
    return [];
}

function underscoreFilter<T>(_list: T[], _filter: { (item: T): boolean }): T[] {
    return [];
}

function underscoreUnion<T>(_listOne: T[], _listTwo: T[]): T[] {
    return [];
}

function underscoreMap<T, U>(_list: T[], _mapper: { (item: T): U }): U[] {
    return [];
}

type EditStateTransitions = { [K in keyof EditStateLookups]: { (initial: EditStateLookups[K][string], updated: EditStateLookups[K][string]): void } };

export function getChangedEditStates<T extends EditState>(initial: EditStateLookup<T>, updated: EditStateLookup<T>) {
    const keys = underscoreUnion(underscoreKeys(initial), underscoreKeys(updated));
    return underscoreFilter(underscoreMap(keys, key => ({ initial: initial[key], updated: updated[key] })), pair => pair.initial !== pair.updated);
}

export function handleEditorTransition<K extends keyof EditStateLookups>(key: K, transitions: EditStateTransitions, initial: EditStateLookup<EditStateLookups[K][string]>, updated: EditStateLookup<EditStateLookups[K][string]>) {
    for (const changed of getChangedEditStates(initial, updated)) {
        const transition = transitions[key];
        transition(changed.initial, changed.updated);
    }
}
```

**Expected behavior:**
Code compiles

**Actual behavior:**
Code fails to compile; either with a "union expression too complex" when including all cases and properties in the original sample, or simply "'EditStateOne | EditStateTwo' is not assignable to type 'EditStateOne & EditStateTwo'".

**Related Issues:** #33130, #30769, #31445, #32693

Seems like #30769 was not supposed to affect functions where the key type is fixed in a generic argument, which applies here. #32693 is not the same as no fixed generic argument. #31445 also isn't the same for the same reason. Intellisense claims that the compiler already knows that the `transition` function is `EditStateTransitions[K]`, which according to the mapping, makes it `{ (initial: EditStateLookups[K][string], updated: EditStateLookups[K][string]): void }`. Then `changed` is known to be `{ initial: EditStateLookups[K][string]; changed: EditStateLookups[K][string]; }`. Seems like this should be a slam dunk as in all cases, K is specifically referenced as the fixed generic parameter?

I've experimented with changing the code to the following:

```ts

function handleEditorTransition2<K extends keyof EditStateLookups>(transition: { (initial: EditStateLookups[K][string], updated: EditStateLookups[K][string]): void }, initial: EditStateLookup<EditStateLookups[K][string]>, updated: EditStateLookup<EditStateLookups[K][string]>) {
    for (const changed of getChangedEditStates(initial, updated)) {
        transition(changed.initial, changed.updated);
    }
}

function handleTransitions(transitions: EditStateTransitions, initial: EditStates, updated: EditStates) {
    underscoreMap(underscoreKeys(initial.lookups), <K extends keyof EditStateLookups>(k: K) => handleEditorTransition2<K>(transitions[k], initial.lookups[k], updated.lookups[k]));
}
```

This fails (if strictFunctionTypes is enabled) because "Argument of type 'EditStateTransitions[K]' is not assignable to parameter of type '(initial: EditStateLookups[K][string], updated: EditStateLookups[K][string]) => void'." which is *literally* how the mapping is defined.

**Comment by RyanCavanaugh** [comment]
There isn't any guarantee that two references to the same type parameter have the same value. See discussion in similar bug #31445

**Comment by markboyall** [comment]
@RyanCavanaugh I guess the issue is that the key type parameter isn't really how I thought of it. K doesn't have to be *one* of those options, it can be a union too. Perhaps there could be some kind of `K in keyof ...` which requires that K must be exactly one of them, so all uses of any value of type K must be the same? Seems somewhat complicated though. I seem to recall that in another issue, it's planned that multiple references to the same key can be tracked as the same type always? In that case there would be no need for any change.

**Comment by RyanCavanaugh** [comment]
See #27808 for discussion of "no unions allowed" generics
