### ISSUE TITLE
Support typeof this for cloning

### ISSUE THREAD

**Issue by Sharcoux** [microsoft/TypeScript#39902]
Looking for the issue, I found multiple references to this, but all of them lead to [this issue](https://github.com/microsoft/TypeScript/issues/3694) which is closed and marked as "fixed" while the problem remains (or at least the solution is [not documented](https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types). 

## Search Terms

Clone
typeof this
cloning

## Suggestion

It should be possible to write something like:

```typescript
interface A {
  clone (): typeof this
  }
}
```

The expected result would be that `X.clone()` is inferred to `typeof X` when X implements A, and any implementation of A should define a function `clone` that returns an instance of this type.

## Use Cases

This is very useful for cloning objects, but also for any object method that should return an instance of that same object.

### For interface:

```typescript
interface A {
  clone (): typeof this
  }
}
class Impl implements A {
  // Implementing A should force any implementation to define the method and return an implementation of this class
  clone (): typeof this {
     return new Impl()
  }
}

const a = new Impl()
console.log(typeof a.clone()) // Impl
```

### For inheritance

```typescript
class Container {
  content: number[]
  constructor(content: number[]) {
    this.content = content
  }
  extract(start: number, end: number): typeof this {
    return new Container(this.content.slice(start, end)
  }
}

class BetterContainer extends Container {
  superProp: string
  constructor(content: number[], superProp: string) {
    super(content)
    this.superProp = superProp
  }
  // Using `typeof this` as a return type in a class or interface should be considered as using `abstract` and force any inheritant to redefine the method.
  extract(start: number, end: number): typeof this {
    return new BetterContainer(this.contentslice(start, end), this.superProp)
  }
}

const container = new BetterContainer([1, 2, 3], 'test')
const extract = container.extract(0, 1).superProp // Should work
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
You can do this today. Given no discussion of how it doesn't fit your criteria I'm assuming you didn't know about it.
```ts
interface A {
  clone(): this
}

class C implements A {
    clone() {
        return this;
    }
}
```
