### ISSUE TITLE
Setup constructor parameters before call to `super`

### ISSUE THREAD

**Issue by lucas-rudd** [microsoft/TypeScript#39914]
## Search Terms

constructor parameters
class initialization order
using constructor parameters

## Suggestion

I'd be really surprised if this has not been reported/requested before. If it has been, I'd be more than happy to take a look at the issue; but, I could not find any issues related to this problem.

This is somewhat related to this issue #38038. However, that issue is related to user actions, the issue I'm opening is related to the way TypeScript is compiled.

When using constructor parameters, it would be expected that the parameters are set up before anything else. Primarily due to the order (that is, they're defined in the constructor, giving the impression that when the constructor is called, the parameters are set up for use), but also due to the idea that these parameters are likely required in class initialization, and thus need to be setup immediately for use.

The suggestion I have is that when using constructor parameters, the parameters should be setup prior to anything else, in this case, the `super` call.

## Use Cases

**Benefit**
This would be beneficial in class setup, particularly when some of the setup is done by a parent class, and that setup process may rely upon different implementation details in the child class to obtain certain configuration data in order to set the class up properly.

**Current Workaround**
Currently, you can add an initalization method to the parent class, and call it in the child's constructor immediately after the call to `super`. After the `super` call, the constructor parameters have been properly setup, so any logic that depends upon those parameters will now work as intended, like so.
```ts
// ParentClass.ts
export abstract class ParentClass {
   constructor(...) { }
   initalize() {
      this.getValues();
   }

   abstract getValues(): Values;
}

// ChildClass1.ts
export abstract class ChildClass1 extends ParentClass {
   constructor(private readonly config: ChildConfig1) {
      super();
      super.initalize();
   }

   getValues() {
      return this.config.childValues1;
  }
}

// ChildClass2.ts
export abstract class ChildClass2 extends ParentClass {
   constructor(private readonly config: ChildConfig2) {
      super();
      super.initalize();
   }

   getValues() {
      return this.config.childValues2;
  }
}
```

The shortcomings of this approach are as follows

- **Being prone to error:** There is no way to ensure that a consumer extending the class with call this initalization method
- **Difficult to read/understand:** It is not immediately obvious as to why such an initialization method is required, as there is no need for any additional setup logic to exist in the TS file immediately after the call to `super`. The problem exists _only_ in the compiled code. Any developers not familiar with the order of operations related to constructor parameter initialization and a call to super will naturally think that such an initialization method is unnecessary, and that the setup can exist in the parent class' constructor method. 
The difficult to read/understand point runs directly counter to one of the TypeScript Design Non-Goals.

> Introduce behaviour that is likely to surprise users. Instead have due consideration for patterns adopted by other commonly-used languages.

## Examples

Here's an example of an abstract `BaseHandler` class, and some child classes that rely upon some initialization to occur before they can use an implementation of a logger. It also relies upon some abstract methods being implemented, which will obtain the necessary data from the necessary location which changes based on the Handler type. 

**This currently _does not work_.**

```ts
// BaseHandler.ts
export abstract class BaseHandler {
  protected _logger: Logger;
  constructor(partialLoggerConfig: PartialLoggerConfig) {
    const loggerConfig: ILoggerConfig = {
      correlationId: this.getCorrelationId(),
      sourceIp: this.getSourceIp(),
      context: this.getContext(),
      ...partialLoggerConfig,
    };
    this._logger = new Logger(loggerConfig);
  }

  abstract getCorrelationId(): string;
  abstract getSourceIp(): string;
  abstract getContext(): Context;
}
```

```ts
// BaseExpressHandler.ts
export abstract class BaseExpressHandler extends BaseHandler {
  constructor(
    protected readonly functionName: string,
    protected readonly request: Request,
    protected readonly response: Response,
    protected readonly next: NextFunction
  ) {
    super({
      domain: functionName,
      action: request.method || 'REQUEST',
    });
  }

  getCorrelationId(): string {
    return this.request.get(X_CORRELATION_ID) || '';
  }

  getSourceIp(): string {
    return this.request.get(X_SOURCE_ID) || '';
  }
  
  getContext() {
    return {
      userId: this.getUserId()
      ...
    };
  }
}
...
```

```ts
// BaseLambdaHandler
export abstract class BaseLambdaHandler<T extends BaseAwsLambdaEvent> extends BaseHandler {
  constructor(
    protected readonly event: T,
    protected readonly context: Context,
    protected readonly callback?: Callback
  ) {
    super({
      domain: context.functionName,
      action: event.httpMethod || 'REQUEST',
      invoker: event.requestContext?.apiId || '',
    });
  }

  getCorrelationId(): string {
    const { requestContext } = this.event;
    return requestContext.requestId;
  }

  getContext(): Context {
    const { requestContext } = this.event;
    const userId = requestContext?.authorizer?.userId || '';
    ...
    return {
      userId
      ...
    };
  }

  getSourceIp(): string {
    const { requestContext } = this.event;
    return requestContext?.identity?.sourceIp || '';
  }
}
```

The above does not work, although it is not immediately clear as to why it does not work. When running this, errors will occur such as
```
Cannot read _something_ of undefined
```

This is because when the `BaseExpressHandler`, and `BaseLambdaHandler` are compiled, the JS looks like this
```js
class BaseLambdaHandler {
    constructor(event, context, callback) {
        super(...);
        this.event = event;
        this.context = context;
        this.callback = callback;
   }
}
```

```js
class BaseExpressHandler {
    constructor(functionName, request, response, next) {
        super(...);
        this.functionName = functionName;
        this.request = request;
        this.response = response;
        this.next = next;
   }
}
```

Thus resulting in the various implementation methods (e.g. `getCorrelationId`, `getSourceIp`, and `getContext`) failing to access the constructor parameters.

The desired fix would be to alter the order of the two in the compiled code, like so
```js
class BaseLambdaHandler {
    constructor(event, context, callback) {
        this.event = event;
        this.context = context;
        this.callback = callback;
        super(...);
   }
}
```

_However_, I understand this would result in the parent class overriding the child class' member variables if the parent class also accepts these values in it's constructor. So, perhaps the name of the constructor parameters could be dynamically constructed so as to avoid this issue, like so:

```js
class BaseLambdaHandler {
    constructor(event, context, callback) {
        this.baseLambdaHandlerEvent_1 = event;
        this.baseLambdaHandlerContext_1 = context;
        this.baseLambdaHandlerCallback_1 = callback;
        super(...);
        this.event = event;
        this.context = context;
        this.callback = callback;
        this.baseLambdaHandlerEvent_1, this.baseLambdaHandlerContext_1,  this.baseLambdaHandlerCallback_1 = undefined;
   }

   
  getCorrelationId(): string {
    const { requestContext } = this.baseLambdaHandlerEvent_1 || this.event;
    return requestContext.requestId;
  }

}
```

Although additional logic would be necessary to ensure the cleanup of these temporary variables, as well as to only use them if the proper member variable does not yet exist, it could potentially avoid the problem I described above.

I am open to other suggestions as to what a compiled output would look like while supporting this behavior, as the above example of compiled output which supports this functionality could introduce additional space complexity before the variables are removed by the garbage collector, which is not ideal. 

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
It's a runtime error to refer to `this` before calling `super`, so this is a non-starter

**Comment by lucas-rudd** [comment]
Although `this` cannot be used, modifying the object's prototype can occur before `super` is called.


So, something like the following would have the same functional effect as using `this`

```js
class BaseLambdaHandler extends BasHandler {
    constructor(event, context, callback) {
        BaseLambdaHandler.prototype.event = event;
        BaseLambdaHandler.prototype.context = context;
        BaseLambdaHandler.prototype.callback = callback;
        super(...);
        this.event = event;
        this.context = context;
        this.callback = callback;
        BaseLambdaHandler.prototype.event, BaseLambdaHandler.prototype.context,  BaseLambdaHandler.prototype.callback = undefined;
   }

   
  getCorrelationId(): string {
    const { requestContext } = BaseLambdaHandler.prototype.event, || this.event;
    return requestContext.requestId;
  }
}
```

Would such an approach have any adverse affects on the proper initialization of a class when using `super`?
