### ISSUE TITLE
Incorrect inheritance of union of unique symbols in objects

### ISSUE THREAD

**Issue by kaaboaye** [microsoft/TypeScript#39910]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
const someA = Symbol()
const someB = Symbol()

type SomeUnion = typeof someA | typeof someB

const value: SomeUnion = someA

const brokenObject = {value}

// TypeScript wrongfully allows this assign operation because `typeof value is symbol`
brokenObject.value = Symbol()

const validObject = {
    value: value as typeof value
}

// TypeScript errors on this assign operation because `typeof value is SomeUnion`
validObject.value = Symbol()
```

**Expected behavior:**

Writing `value: value as typeof value` shouldn't be required.

**Actual behavior:**

When writing

```ts
const a = {value}
```

the `typeof a['value'] is symbol`

**Playground Link:** 

https://www.typescriptlang.org/play?#code/MYewdgzgLgBBIFsCmBBGBeGBlAnggRiADYAUAlAFCiSzzIBCG2ehplFUOADktokgFUwAS3BNOPEADM4-NAB8YEpNNkMKVcNBgA3AIZEArkgBcfZENFgmdVBurb8AJxABrJGADy+AFZJgsJgA3vpGSAC+Gs5uHt5+AQB0ocZMuATE5PZasKHCACZx-oEwQRQw5boGxmbJvHoQStwqMrUUkRS5Bb5FSVW8mGmsmUA

**Related Issues:** 

Didn't find any

**Comment by RyanCavanaugh** [comment]
These are all the intended behaviors. You're missing `: unique symbol` in `const someA/B` and `as const` in `validObject` if the behavior you describe is what you want.
