### ISSUE TITLE
Cannot assign union typed value to a conditional generic property

### ISSUE THREAD

**Issue by wmaca** [microsoft/TypeScript#39919]
**TypeScript Version:**  4.0.0-dev.20200803

**Search Terms:** generic discriminant assignment conditional

**Expected behavior:** the variable `animal` of type `Animal` should should be assignable to the property `value` of `AsyncValue<Animal>`

**Actual behavior:** the property `value` of `AsyncValue<Animal>` seems to accept only `Bird & Reptile`, issuing an error. 

**Related Issues:** none

**Code**
```ts
type Bird = {
	readonly type: "bird";
	readonly flying: boolean;
};

type Reptile = {
	readonly type: "reptile";
	readonly swimming: boolean;
};

type Animal = Bird | Reptile;

export type AsyncValue<T> =
	| {
			readonly available: false;
	  }
	| (T extends void
			? {
					readonly available: true;
			  }
			: {
					readonly available: true;
					readonly value: T;
			  });

const animal: Animal = null as unknown as Animal;

const foo: AsyncValue<Animal> = {
	available: true,
	value: animal // error: type Animal is not assignable to type Reptile
};

console.log(foo);

```

<details><summary><b>Output</b></summary>

```ts
const animal = null;
const foo = {
    available: true,
    value: animal // error: type Animal is not assignable to type Reptile. Property 'swimming' is missing in type 'Bird' but required in type 'Reptile'.
};
console.log(foo);
export {};

```

</details>

Interestingly, if you remove the conditional type (`T extends void`), it works.

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200803&ssl=34&ssc=1&pln=1&pc=1#code/C4TwDgpgBAQglgJwCZQLxQN4CgCQCICGSA9gHYA2IUokAXFAEQBGiSDA3LvkWZVAGaU4pAOb0mxYuUKlOAX05Ya0AEoQwwONLSYuhEhSrL6DfBq0QOenoagBnAO5wAts+FioEqTPmLlUAEFSFwJyHXhkKAAfKDVzaUUIAA8wYgRganBoALsQUgBjADVQgFcIAB4AFQA+NFwY7Bwm7gM+AgA3Ai0CJml6flC7CE4cKCg5eqgACkqoZOAIUiQ7KHbiOCRcJoB+XSb9lt4qDq7yHr7qBDKRprGJ-fpG-bx9I6gT7t6IemAr4a2Dq9bJ1yGV6JUbqNxgBKRT5Mh2DIEYLOUL0IIhMLoUglchhAgrEqkADWpGIDlI7xWGNR5DhCIy-Ek6NyBWKoIqNNCtXQjQ+Zy+Pz+ABpcCCwe8UaEoAB6GVzBAINI-LKBKVhOArMlIux2OAiUgEETaYDETKQWLqTTSLAKLBYeGkOzeAB05GIIimTOIsKwQA)

**Comment by MartinJohns** [comment]
You got hit by [distributive conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types).

Your type is basically resolved to `{ value: Bird } | { value: Reptile }`, not `{ value: Bird | Reptile }`. Here's a simplified version:

	type Foo1 = { readonly value: Bird } | { readonly value: Reptile }
	type Foo2 = { readonly value: Bird | Reptile }

	const test1: Foo1 = { value: animal } // Compiler error
	const test2: Foo2 = { value: animal } // Works

You can disable the distribution by wrapping the arguments in an array, e.g. `[T] extends [void]`.

**Comment by wmaca** [comment]
Wow! I saw something about it, but did not dig any further, as I thought it wouldn't be the culprit. It seems to solve my problem.

Thank you very much, and I am sorry for any inconvenience caused. It is never fun to report something that is working as intended.
