### ISSUE TITLE
The problem of missing file extension after build.

### ISSUE THREAD

**Issue by quasipaa** [microsoft/TypeScript#39929]
I have a problem when I compile the ts module to the es module, The file cannot be loaded because of the lack of the file extension. Many browsers currently support modular loading, and webpack is not necessary to compile the project, so I think this is a problem ；
Before asking this question, I checked a lot of issues, but I didn’t find any related issues. If it’s a duplicate issue or the way I look it up is wrong, I’ll say sorry.

**TypeScript Version:**  typescript@4.1.0-dev.20200805

**Search Terms:**
.js file extension

**Code**

```ts
import {Option} from "./util/configure"
```

**Expected behavior:**

```js
import {Option} from "./util/configure.js"
```

**Actual behavior:**

```js
import {Option} from "./util/configure"
```

**Playground Link:**
build error.

**Related Issues:** 
none.

**Comment by quasipaa** [comment]
Sorry, I found a duplicate problem

**Comment by BrenoMazieiro** [comment]
@mycrl Would you please link to the original issue?
