### ISSUE TITLE
Incompatible type guards are assignable to each other

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/TypeScript#39920]
**TypeScript Version:**  4.0.0-beta

**Search Terms:** type guard, assignability, covariance, strictFunctionTypes

**Expected behavior:**

`isUnknown` is not assignable to `isString`.

**Actual behavior:**

`isUnknown` is _sometimes_ assignable to `isString`. At other times it's not.

**Related Issues:**

#29501

**Code**

I apologize for using a dependency here, but I wasn't able to reproduce the issue without it.

```ts
import Refinement from 'refinements';

/**
 * Let's suppose I want to create a type guard like this.
 */
let isString: (candidate: unknown) => candidate is string;

/**
 * And let's suppose I have a type guard of type `(candidate: unknown) => candidate is unknown`.
 */
const isUnknown = Refinement.create(
  _ => Refinement.miss
);

/**
 * As expected, this doesn't compile.
 */
isString = isUnknown;

/**
 * Unexpectedly, this does — even though the right-hand side is of exactly the same type as `isUnknown`.
 */
isString = Refinement.create(
  _ => Refinement.miss
);
```

<details><summary><b>Output</b></summary>

```ts
let isString;
import Refinement from 'refinements';
// isUnknown is of type `(candidate: unknown) => candidate is unknown`
const isUnknown = Refinement.create(candidate => Refinement.miss);
isString = isUnknown;
isString = Refinement.create(candidate => Refinement.miss);
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/JYWwDg9gTgLgBAJQKYDNgDskie+KoQhwDkUqGWOMAzsQNwBQDA9AFSsNytwAySMxanGoBXMJGpI4ASTgB3AIa44MCHADGZBTCkKVATzBSA5iIVQAJnAA2wANZSYAC2DUAdJ1bMG1-nFcAyjBQGMYAXHAAFOpKFsAW2kgRIuh26BBy6ACUcAC8AHwasfGJ-kLUwaGMLOyecACC6Fa+AuViElKyTgoAbroGRnCm5lYQKANSAAbRxQk6yanpmTkFRU0lOmVwKWkZ6JMeXN7qEOgVZQCqi3t5iOSY2LhumkiJkZxwAPp5hchoD1Q3CBXNQGFlqmwOFwGkIkAAPIzqHQWAA0KhcQgsECQ1HQxHgJ3AwF8hy8DEClXQxluriuu0yENq0Ku8MRyOs+jRzlccCxOLggBQCOBIProdEQETGJzoqQhKUwAC03SawniUh5Y2FcIUSI5MuECmwEzgCiEk1p10yB083gpISptz+FEeMGeWh07zgXx+d3+lCewOooPBQA)

**Comment by MartinJohns** [comment]
> Unexpectedly, this does — even though the right-hand side is of exactly the same type as `isUnknown`.

But it's not the same type. If you hover over it you can see that the type is `(candidate: unknown) => candidate is string`. With the direct assignment the second generic type parameter is inferred to be `string`, while in your `isUnknown` case there's no information to infer the type from and it's `unknown`.

**Comment by MartinJohns** [comment]
Here's a minimal example without a dependency:

	function identity<T>(): T { return {} as any; }

	let isString: string;
	let isUnknown = identity(); // T inferred to be unknown.
	isString = isUnknown;       // unknown is not assignable to string.
	isString = identity();      // T is inferred to be string, assigning possible.

**Comment by jack-williams** [comment]
The first call that assigns to `isUnknown` lacks a contextual type to instantiate the parameter so you get back unknown. At that point the parameters are fixed and the assignment to `isString` will fail.

The second call is contextually typed by the type annotation on `isString`, so the type parameter is inferred to be `string`.

I think this comes down to the design whereby type-inference is local to the call site. Contextual typing lets you push information down to the call-site in some cases, but it doesn't extend as far as to propagate back through assignments of returned values. For this to work you would need a global analysis.

Here is a mini example to demonstrate contextual type, in this case, for inferring literal types.
```ts
let obj: 5;
let obj2 = 5
obj = obj2 // error
obj = 5
```

**Comment by karol-majewski** [comment]
Good explanation, thank you both.

I suppose there is nothing to do here?

**Comment by MartinJohns** [comment]
> I suppose there is nothing to do here?

Everything is working as intended. :-)
