### ISSUE TITLE
Code syntax hint question

### ISSUE THREAD

**Issue by LittleStoney** [microsoft/TypeScript#39939]
- VSCode Version:1.47.3
- OS Version: Windows_NT x64 10.0.19041

 In a JS file,when I create an object,such as
 `const status = {
  PENDING: Symbol('pending'),
  FUFILLED: Symbol('fulfilled'),
  REJECTED: Symbol('rejected'),
}`
But in my editor, when using `status` later, put the mouse on it,the code hint shows information from the **lib.dom.d.ts** file , it shows `var sattus:string`  from `declare var status: string;`
How to avoid this??

**Comment by mjbvz** [comment]
Same root cause as #39534
