### ISSUE TITLE
Apply more TSLint rules

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3994]
Including

- [ ] One variable declaration per variable statement (see https://github.com/palantir/tslint/issues/525)
- [ ] Spaces, not tabs
- [ ] No space preceding colons
- [ ] Double quotes for strings (though, depending on TSLint's behavior on this, we can be flexible.
- [ ] No explicit types for inferrable entities
- [ ] use `namespace` instead of `module` (see https://github.com/palantir/tslint/pull/517)
- [ ] `else`/`catch`/etc. on a different line (see https://github.com/palantir/tslint/issues/88)
- [ ] Space before `{` in interfaces, classes, enums, any sort of attached statement body, or type annotation.
- [ ] No trailing whitespace
- [ ] Forbid boolean/`undefined` parameters who aren't named.
- [ ] Forbid `null`

Any other suggestions?

**Comment by weswigham** [comment]
We also need a rule to capture having `else` and `catch` statements on the line _after_ the closing curly of the previous statement. [Open issue on tslint requesting a rule for it.](https://github.com/palantir/tslint/issues/88)

**Comment by RyanCavanaugh** [comment]
Do we have one for spaces between `if` and `(` ?

**Comment by weswigham** [comment]
We also need one for the space after a method declaration but before the method body, ie disallowing:
```
{
    func(){

    }
}
```
and
```
{
    func(): void{

    }
}
```

**Comment by weswigham** [comment]
Also a rule for enforcing inferred typing on primitive literal declarations, ie
```ts
const member: string = "item"
```
should be
```ts
const member = "item"
```

**Comment by weswigham** [comment]
The rule added that will be added from [this PR](https://github.com/palantir/tslint/pull/517) should also be enabled to disallow the `module` keyword for internal modules.

**Comment by weswigham** [comment]
@RyanCavanaugh `"whitespace": [true, "check-branch"]` should be covering that.

**Comment by weswigham** [comment]
[From this PR:](https://github.com/Microsoft/TypeScript/pull/4068)
> Use named parameter

A rule to forbid boolean parameters who aren't named.

**Comment by weswigham** [comment]
...also a no trailing whitespace rule.

**Comment by danquirk** [comment]
I tried to apply the no trailing whitespace rule locally but too many people are using editors where newline causes a smart indent that inserts whitespace. So then tslint flags tons of seemingly blank newlines as having trailing whitespace (because they're not simply a \n or \r\n). Would be nice to have on though.
