### ISSUE TITLE
vscode does does not respect tsconfig.json configuration for ts files

### ISSUE THREAD

**Issue by hadson172** [microsoft/TypeScript#39942]
- VSCode Version: 1.47.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open empty folder 
2.  Create .ts file
3. "Go to project configuration" 
4. Configure tsconfig.json file
5. Go to back to the .ts file, repeat step 3 (should navigate to the file, but instead it shows popup :
![image](https://user-images.githubusercontent.com/8881977/88590115-78c48300-d05a-11ea-9fe1-a8a8eb49a37c.png)

Second approach to the same problem:
1. Open empty folder
2.  Create two files: first.js and second.ts
3. Type `const a = 1000` in first.js and `const a = 2134123` in second.ts (the values, modifier does not matter)
4. Configure tsconfig.json with allowedJs: false
![image](https://user-images.githubusercontent.com/8881977/88590425-fa1c1580-d05a-11ea-8b93-86a19c330463.png)

 5. There shoud not be re-declaration error message in ts but it is:
![image](https://user-images.githubusercontent.com/8881977/88590526-29cb1d80-d05b-11ea-914f-60a4b610e752.png)

Third example of the same problem:
1. Create two files - first.ts and second.ts
2. Change property in tsconfig.json to modules: "none"
3. VScode helps with imports when it should not

So why tsconfig.json is not respected?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Here's what I see in VS Code insiders on windows (there is a ~2sec delay after saving the config file before the error goes away):

![Aug-06-2020 14-14-33](https://user-images.githubusercontent.com/12821956/89583480-44d22600-d7ef-11ea-934a-8bdd9e8b9f66.gif)

The second error is expected. If your files does not use any imports or exports, then it is treated as being part of the global scope

**Comment by hadson172** [comment]
Still having the issue. Is there any way to debug this problem or see detailed logs?
About second case. If all files are included agree. But if i include only one of the files in tsconfig.json and the other one is excluded i should not be getting collision errors this is my understanding at least.

**Comment by efpage** [comment]
Problem persists. Opening a folder with VScode, a .ts-file delivers 191 errors, after first edits jumps to 591 errors without any changes to the code. Seems tsconfig is not used anymore after first edits.

TSconfig.json seems to be ok:
```json
{
  "compilerOptions":
  {
     "outDir": "./dist",
     "allowJs": true,
     "checkJs": true,
     "module": "ES2015",
     "target": "ES2015"
  },
  "exclude": ["node_modules", "**/node_modules/*", "dist"]
}
```

**Comment by RyanCavanaugh** [comment]
Please open a new issue with concrete (like, *very* concrete) repro steps. We haven't been able to reproduce this in any form yet.
