### ISSUE TITLE
'this' autocomplete broken

### ISSUE THREAD

**Issue by fsenart** [microsoft/TypeScript#39946]
**TypeScript Version:**  3.9.2

**Search Terms:** this function return decorator wrapper callback autocomplete

**Code**

```ts
interface Ctx {
    foo(): { x: number };
}

declare function wrap(cb: (this: Ctx) => any): void;

wrap(function () {
    const xs = this.foo();
    // xs. // autocomplete works
    // return xs. // autocomplete broken
});

wrap(function () {
    const xs = this.foo();
    // const y = xs. // autocomplete works as long as 'y' or 'xs' is not used in return!!!
    // return y // autocomplete broken
});

wrap(function () {
    const xs = this.foo();
    // return xs.y // typescript effectively catches the non-existing y property
});
```

**Expected behavior:**

Autocomplete must work, always.

**Actual behavior:**

Autocomplete doesn't work as long as `xs` is used in **any possible way** in the return statement.

**Playground Link:** [HERE](https://www.typescriptlang.org/play?ts=3.9.2#code/JYOwLgpgTgZghgYwgAgMJgB7IN4FgBQyRyMA9qQBQCUAXDshnSAK4C2ARtMgL4DcB3AgQAmEBABs4UFDGYgEYYKRDIA7lDgAHCgnZ0KYABbAAznXQYqyALwA+ZHBABPWsgBupYMP74C6rRSy8orKyNQ4BMTICMomYAwmNshGpgB0ZJRUPlEA9DkJqch5DsxgpDGsmuIQkGqkUADWJpHExdJgzFAqGCaFxXCl5aSV1bXsUKQNECACWUL4-tpBCkoq4XiExDEgcQlJKb0Z1Nmt+du7Tkk9ffkDZRVVNSiq9U0OieLKAObvyADkTj+yHq-x6QNMyBApHizBMEGEyFAyHanRAAEIMS0iG0aqjkJd+oMHqMUONJtNZj4-BolnIVqF1ljorF4j19sZDuRjkycR0ugUCfkwE5NBATAgoMBNPEIDAYGJFG4IOJLgg4GAEIYxcktZDlABaCAYUyKEA-S6aCaiqDCylAA)

**Comment by orta** [comment]
Yeah, looks like the inference isn't passing through like expected when the object is used in a return position, maybe a caching issue

```ts repro
interface Ctx {
    foo(): { x: number };
}

declare function wrap(cb: (this: Ctx) => any): void;


wrap(function () {
    const xs = this.foo();
//         ^?
    return ""
});

wrap(function () {
    const xs = this.foo();
//         ^?
    return xs.x // autocomplete broken
//            ^?
});

wrap(function () {
    const xs = this.foo();
    const y = xs.x
//        ^?
    // autocomplete works as long as 'y' or 'xs' is not used in return!!!
    return y // autocomplete broken
//         ^?
});

wrap(function () {
    const xs = this.foo();
    return xs.y // typescript effectively catches the non-existing y property
});

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/JYOwLgpgTgZghgYwgAgMJgB7IN4ChkHIwD2xAFAJQBcOyGNIArgLYBG0yAvgNy6e64AJhAQAbOFBQxGIBGGDEQyAO5Q4ABzIJWNMmAAWwAM410GCsgC8APmRwQAT2rIAbsWCDeA1RrLTZ8orIlDj4hAiKRmB0RlbIBsYAdCTkFLwA9OmE2QQAegD8YQSSYIxQSgBEFXxp3mqa-nIKSiF42REgUTFxCUbJpJQZWTmEBUXIJWVKGH1YmXaMYMQRzOqiEJDIrFDEANYQILjzIzljnLW4Pg0yTUGt4x1dMz2GfSmDD5HRDnEziRhHYYjMbZeZwRbLYirdabZTEKC7WJwWKiRQAczssQA5A4sch4cgsTM8cZkCBiNFGEYIIJkKAJhspgBCFnjSblZA-MEQlZrDYobZ7A6Ak55QrnLxXPw3QItCxtcJfbqWeKvfqpXjZdnTPpcrJgBzqCBGBBQYDqaIQGAwETyFwQUQ-BBwMAIfTG1UockgAC0EAwxnkIAxP3UOyNUANNV4QA)

**Comment by DanielRosenwasser** [comment]
@rbuckton didn't you run into something similar to this a week or two ago?

**Comment by fsenart** [comment]
Kindly, following up on this @orta @DanielRosenwasser. As the problem is real, can we label it as a bug?

**Comment by rbuckton** [comment]
The issue is that we end up encountering a circularity when type checking `xs` because we check the body of the function to find the return type while checking the `this` type while getting the type of `xs`:

![image](https://user-images.githubusercontent.com/3902892/128270477-b7a13826-b2f6-44f2-90c4-2e557d3399bb.png)

If `xs` isn't involved in the calculation of the return type, then we don't encounter the circularity.

**Comment by rbuckton** [comment]
If you change `wrap(function() {` to `wrap(function(): any {` then completions work. I'm looking for a way to avoid the circularity.

**Comment by rbuckton** [comment]
The circularity isn't reported during regular compilation because we have already checked the `this` type before we get to the `return` statement. I've found a quick solution that involves getting the type of the containing function *before* getting the type of the node at the cursor, which will result in the `this` type being checked and cached, avoiding the circularity.
