### ISSUE TITLE
Async / await with Bluebird promises

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [microsoft/TypeScript#39953]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

Bluebird promises typescript import

**Code**

I want to add a simpler solution for "Async / await with Bluebird promises" #8331, but could not add to the discussion.

How to import Bluebird:

```ts
import { Promise as BbPromise } from 'bluebird';
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:** 

Async / await with Bluebird promises #8331

**Comment by MartinJohns** [comment]
You probably should fill out the issue template completely.
