### ISSUE TITLE
Type narrowing broken for variables assigned from an object property

### ISSUE THREAD

**Issue by Philipp91** [microsoft/TypeScript#39956]
**TypeScript Version:**  4.1.0-dev.20200807

**Search Terms:**
narrow, narrowing
property, properties

**Code**
```ts
// It all starts with this strange union type, which essentially comes from here:
// https://github.com/frenic/csstype/blob/master/index.d.ts
// Specifically, React uses `CSS.Properties<string | number>` and the `height` property on there has a type similar to this:
type UnionType = number | (string & {});
// I get a `styles` object with a `height` property and I want to put it into a `number` field:
let num: number;

// (1) When the type is declared on v manually and a concrete value is assigned to it, everything works fine.
const v1: UnionType = 5;
if (typeof v1 === 'number') num = v1;

// (2) When the value comes from an object, it works too.
const implicitlyTypedObject = {field:5};
const v2: UnionType = implicitlyTypedObject.field;
if (typeof v2 === 'number') num = v2;

// (3) When the value comes from an `any`-typed object, there's an error, even though the v3 field has the right type.
const anyObject: any = {field:5};
const v3: UnionType = anyObject.field;
if (typeof v3 === 'number') num = v3; // Error: Type 'UnionType' is not assignable to type 'number'.

// (4) And similarly with an interface, even if it perfectly declares the property.
interface Interface {
    field: UnionType;
}
const typedObject: Interface = {field: 5};
const v4: UnionType = typedObject.field;
if (typeof v4 === 'number') num = v4; // Error: Type 'UnionType' is not assignable to type 'number'.

// (5) It's the same if the variable doesn't specify the right type again explicitly:
const v5 = typedObject.field; // No UnionType here.
if (typeof v5 === 'number') num = v5; // Error: Type 'UnionType' is not assignable to type 'number'.

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// I get a `styles` object with a `height` property and I want to put it into a `number` field:
let num;
// (1) When the type is declared on v manually and a concrete value is assigned to it, everything works fine.
const v1 = 5;
if (typeof v1 === 'number')
    num = v1;
// (2) When the value comes from an object, it works too.
const implicitlyTypedObject = { field: 5 };
const v2 = implicitlyTypedObject.field;
if (typeof v2 === 'number')
    num = v2;
// (3) When the value comes from an `any`-typed object, there's an error, even though the v3 field has the right type.
const anyObject = { field: 5 };
const v3 = anyObject.field;
if (typeof v3 === 'number')
    num = v3; // Error: Type 'UnionType' is not assignable to type 'number'.
const typedObject = { field: 5 };
const v4 = typedObject.field;
if (typeof v4 === 'number')
    num = v4; // Error: Type 'UnionType' is not assignable to type 'number'.
// (5) It's the same if the variable doesn't specify the right type again explicitly:
const v5 = typedObject.field; // No UnionType here.
if (typeof v5 === 'number')
    num = v5; // Error: Type 'UnionType' is not assignable to type 'number'.

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Expected behavior:**
Compiles without errors.

**Actual behavior:**
Complains `Type 'UnionType' is not assignable to type 'number'.` in a context where type narrowing should have made it clear that it's a `number` now.

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200807#code/PTAEEkBdQQwGzqAzpGAnSTQHcCWkALUQ3LFNGAOwHMBTUAV0twHtLiBPAB1oBocCuAMZFaSJLUqRc8OB1BCWAWzGgAZmmWgCtNLQBcAKBDbIkLkn0hq+AgwBGAOkVLgGycOBDxkbrWD2cCz2wEowKLrAuJQAJrQAHo4xjpjGYADKPEK4asKyHPwASrQwQtAMElgABgDC6emOAAqaPBi4YgA85NHUoAA+oJQMSva6AHxVsLHEOqBVOrjUBJCTXC26vqBsM7r0BOGwnDzIuEq4cOjELDOkRr7HAKrMbAAqfqAAvIPDo2j9oAAKbo0UAAMlAAG8AL4ASgA3GkIKA6NAYHMUBw4GJJsEAFa0Mo4WyHea0RbLVbrDDyKgxJHYKjQSDXLgMaD4UDRZkkoYjXSTXK0OAxIxY6C8-TfPloBGIgEARhhoAA6jp2IR6Pd6KRQHEhBc9HTtgA3UBhIb5KZ0tGKShCPSQejG+AMbVYcJIRaUWh07n4fi0Y26DgkEHYFhoADWWFy3schltKFAxvlkqerEob2OXwArAicoCtSw1Mn5Z8Pl8AOS836VpW8z6l2UmAEAJiVqskO2TLvoLlUGi0VC29nxZX4HPDUawzJY8cT7KUXDgwnwcizPoA8qOCdAvhDBcL9DmoQiF8nW2nnpn3l9TsvV5B134Ytux5BHIeYvmSwCiyXjVbcsqxrXQ6ylRtAObMAAQAZg7NVu2dOBXQUZQB00JQpjmKgOCqABaLUjR3ccdj0St3XYXRNDQAMg3VAgWAYJYkNg9R2mFbQDg1UA0HJJk-HnNgk1wt9d0lXDGwPDiRRPM9hOgY1YKvDMN0bUSSI-L8f0LPxi2TNiKxAn4wPrYZINguFQBMABRNAaMlNTK3TV4-ErTksEoFhUXEL0YECTVri1UBqxMtBK3jOUABYlQAQWmT0zgNOQiUIbCuV0NRSj4UBAy7AsOVaNRdxSvUDVUHi1hYVpfHjDK0CyoR6HAKRMuyyFDFALr2KFEVQBcm8eARKEEwUo4t00yUWsdBr2v3L9JTk0bKCTY0opU1zs3G19NM-GSdL-PSAKi4CQtA8KzKwr41qs2z7IjRz3mc68N3cnUvJ8z1qEofysSucazrCiLDDlHMlSgCjuyQGAVE5EseOdPjfvoGIWDEShK2gJAshyeQeL4pYBOOGBqBgaJcviB9sifDgjHPY0c0bIixLKPbetusAADlrgGtSdD0Orf3-ZNGaMwHpXAhtrrzaywDshzQCc3m3I8wZvNgXzvuR-7gtCiX4yAA)

**Comment by IllusionMH** [comment]
Looks similar to #39879 there are comments why `{}` might break this kind on narrowing.

**Comment by Philipp91** [comment]
Yep, it's a duplicate. Thanks for finding it! I'll post my example there.
