### ISSUE TITLE
Question about ts/js deprecated hint

### ISSUE THREAD

**Issue by galenjiang** [microsoft/TypeScript#39954]
- VSCode Version: 1.47.3
- Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
- Date: 2020-07-23T13:08:29.692Z
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 18.6.0 macOS Mojave 10.14.5

![image](https://user-images.githubusercontent.com/12699258/89632492-db2c4780-d8d4-11ea-9832-cbe68ab20fac.png)
![image](https://user-images.githubusercontent.com/12699258/89632568-fdbe6080-d8d4-11ea-8532-76a53b959592.png)

The function type is overload, and deprecated part of signature
I have no idea whether the hint is right or wrong

Does this issue occur when all extensions are disabled?: No
But it came out when installed the plugin of [JavaScript and TypeScript Nightly]

**Comment by mjbvz** [comment]
Thanks @sandersn!

I've moved the issue over for housekeeping but am closing it since it sounds like the issue has been fixed
