### ISSUE TITLE
Make .match() return an empty array instead of null when 0 mathes are found

### ISSUE THREAD

**Issue by Luctia** [microsoft/TypeScript#39968]
## Search Terms
match empty array null no matches

## Suggestion
Currently, .match()'s documentation states:
>Matches a string or an object that supports being matched against, and returns an array containing the results of that search, or null if no matches are found.
My suggestion is to return an empty array instead of `null` when no matches are found. This way, no extra case has to be coded for when you want to know the exact number of matches.

## Use Cases
Let's say I want to make sure that a string contains one and only one space. In the current implementation, I'd have to make two checks: that `.match()` is not null, and that it returns 1 match. I cannot only check the latter since `.length` of null does not exist.

## Examples
Using the example from before:
```
const value = 'this is a string`;
```
Current implementation
```
if (value.match(/\s/g) !== null && value.match(/\s/g).length === 1) {
  return true;
}
```
Proposed implementation:
```
if (value.match(/\s/g).length === 1) {
  return true;
}
```
These two would be functionally equal.

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
TypeScript is not going to change how the browsers run JavaScript.

And you can just use the `?.` operator.

**Comment by abdatta** [comment]
This is a javascript change, not a typescript change. Typescript does not modify any runtime behaviour of javascript. Anyways, you can achieve what you want using the opt-chaining operator `?.` like this:
```ts
if (value.match(/\s/g)?.length === 1) {
  return true;
}
```
or simpler
```ts
return value.match(/\s/g)?.length === 1);
```
