### ISSUE TITLE
TS2691: import .ts file

### ISSUE THREAD

**Issue by SancheZz** [microsoft/TypeScript#39965]
**TypeScript Version:**  3.9.7

**Code**

```ts
import { doSomething } from './utils.ts';
```

**Expected behavior:**
It should work :) I can have different files with the same name, e.g. ```component.ts``` and ```component.vue```.

**Actual behavior:**
```error TS2691: An import path cannot end with a '.ts' extension. Consider importing './utils' instead.```

**Related Issues:** #27481

**Comment by MartinJohns** [comment]
Duplicate of #38546 & #27481.

**Comment by SancheZz** [comment]
@MartinJohns
Could you please add compiler option to allow ```.ts``` extension? Please, consider resolving #37582
