### ISSUE TITLE
typescript 1.5 language specifications

### ISSUE THREAD

**Issue by aminroosta** [Microsoft/TypeScript#3996]
Where can i find the **typescript 1.5 language specifications** ?  
[This Link](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf) is for the **1.4** version.  
Even a draft or a working version of **1.5** language specification is OK,  

Since so much have changed in the new version of typescript.

**Comment by ahejlsberg** [comment]
Latest copy is located here:

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md

I'm working on an update that incorporates the latest features, but can't give you an ETA. Meanwhile, your best source of information is the linked issues on the roadmap page:

https://github.com/Microsoft/TypeScript/wiki/Roadmap
