### ISSUE TITLE
undefined value for HTMLInputElement when used as @ViewChild

### ISSUE THREAD

**Issue by biswaranjan-rath** [microsoft/TypeScript#39964]
**TypeScript Version:**  3.0.0-dev.201xxxxx
We are using: 3.8.3
Playground Link using: 3.1.1

**Search Terms:** 
ViewChild 
HTMLInputElement 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
HTMLInputElement.value should return text value from the element

**Actual behavior:**
HTMLInputElement.value returns undefined.
As checked in console, HTMLInputElement instance doesn't refer to nativeElement. It expects to be used as "HTMLInputElement.nativeElement.value", but nativeElement property isn't avaialble in the type HTMLInputElement.

**Playground Link:**  
https://stackblitz.com/edit/angular-2-template-reference-variable-jnkdmm?file=src%2Fapp%2Fapp.component.ts

**Related Issues:**

**Comment by MartinJohns** [comment]
This is not an issue with TypeScript, but with Angular and your code. You're simply using the wrong type. You need to use `ElementRef<HTMLInputElement>` instead of `HTMLInputElement` for your `@ViewChild`.

    @ViewChild('firstNameInput') nameInputRef: ElementRef<HTMLInputElement>;

In general Angular provides very poor TypeScript support.
