### ISSUE TITLE
Using "extends" conditions on a union type to map to a class / interface with a generic type can results in an unnecessary "split" union type which causes unjustified assign-ability error

### ISSUE THREAD

**Issue by sharshuv-quotient** [microsoft/TypeScript#39967]
**TypeScript Version:**  3.9.2

**Search Terms:**

extends condition, union type, generic type, assignability

**Code**
```ts
class ValueRef<T> {
  onChanges: () => T; // Note that if I would have used this type directly (i.e. `value: T` it works correctly)
}

type Test<T> = T extends any ? ValueRef<T> : ValueRef<T>; // Expected to behave like identity

const a: ValueRef<boolean> = new ValueRef<boolean>(); // No error
const b: Test<boolean> = new ValueRef<boolean>(); // Error
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class ValueRef {
}
const a = new ValueRef();
const b = new ValueRef();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBqYgK4FMBKyBmAeAKgPmgG8AoaaAewDsBhACzEoHNkIAuaACgEpoBeAnAG5iAX2LEALgE8ADsmg4WE3AV4LoyAB4TklACYwARuXIhkDaAH44CFOmz5o7eEjSYVw4sCoQJ0MM62btjGpuaUqtCUyADuNq72WKFmDHjcwt6UvtCG7Iq+SSYpEXxRsfF27snhaVyCQA)
     
**Expected behavior:**

The code should compile without error. `Test<boolean>` should be interpreted the same as `ValueRef<boolean>`

**Actual behavior:**

The last assignment fails with the following error:

```
TS2322: Type 'ValueRef<boolean>' is not assignable to type 'ValueRef<false> | ValueRef<true>'.   
Type 'ValueRef<boolean>' is not assignable to type 'ValueRef<false>'.
Type 'boolean' is not assignable to type 'false'.
```
I.e. `Test<boolean>` is interpreted as `ValueRef<true> | ValueRef<false>`, than each one is checked separately and the conclusion is that `ValueRef<boolean>` is not assignable to it. 

I'm aware that `ValueRef<true> | ValueRef<false>` is NOT the same as `ValueRef<boolean>`. I simply expect the `Test<boolean>` to be equal to the later. 

**Notes**
* It doesn't matter what the "extends" condition is, it matters that the generic type (in that case - boolean) is a union type. (i.e. true | false)
* I wrote the condition as an identity just for the sake of simplicity but of course I expect it to work with a condition that maps to two different types.

**Comment by jack-williams** [comment]
This is caused by distributive conditional types that a union type like `boolean` which is defined as `true | false`, and apply the conditional type to each part of the union.

Here is one of the related issues which will give you more detail: #37279.

Search terms: _boolean conditional type_

**Comment by sharshuv-quotient** [comment]
Thanks. The use of tuples solves my issue.
I do not understand why is this a wanted behavior at the first place, but as long as I can override this I'm happy with it.
