### ISSUE TITLE
Incorrect behavior of `@type {typeof import('module').NamedExport}` as document

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#39974]
document: https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#import-types

**TypeScript Version:**  4.1.0-dev.20200810

**Search Terms:** `@type {typeof}`

**Code**

```js
// @ts-check

/**
 * @type {typeof import("rollup").RollupOptions}
 */
const config = {
  input: "src/index.js",
  output: {
    file: "dist/index.js",
    format: 'esm',
  },
};

export default config;
```

**Expected behavior:**

No error

**Actual behavior:**

```log
rollup.config.js:7:35 - error TS2694: Namespace '"/Users/JounQin/Workspaces/Local/test/node_modules/rollup/dist/rollup"' has no exported member 'RollupOptions'.

3  * @type {typeof import("rollup").RollupOptions}
                                    ~~~~~~~~~~~~~


Found 1 error.
```

**Playground Link:** 
https://www.typescriptlang.org/play?target=99&useJavaScript=true#code/PTAEAEBcGcFoGMAWBTeBrAUMAVNjpsJIBPAB2VAG8TyB7AM1AEsBbU2gJ0gAoAiD2gBtBAV1K8AlADoASkNGkA8qUhNaAO2gBffNmAZ4G6JFCH19JgHNQAXir5m60iMgAuUL2gd4wJuoAmyAAeUgBW0LwANA60Ls5u9qBJoBaCyO68-kzGvgHBYRHRySmcLACGCQDkyNAslUWgWtFaANwYGMHsXKCB9GUigiZmFpYtQA

But the following would work:

```js
// @ts-check

/**
 * @typedef {import("rollup").RollupOptions} RollupOptions
 */

/**
 * @type {RollupOptions}
 */
const config = {
  input: "src/index.js",
  output: {
    file: "dist/index.js",
    format: 'esm',
  },
  plugins: [nodeResolve(), commonjs()],
};

export default config;
```

**Related Issues:** 
Not found

**Comment by orta** [comment]
I think you just had wrong syntax in the first case. You're trying to do typeof on a type, which isn't really a thing (though maybe it could be argued to NOOP) - we use `/** @type { import("rollup").RollupOptions } */` in the [playground plugin](https://www.typescriptlang.org/dev/playground-plugins/) template and it works just fine.

```ts
export default rootFiles.map(name => {
  /** @type { import("rollup").RollupOptions } */
  const options = {

```

**Comment by JounQin** [comment]
@orta Thanks for reply, sounds reasonable, I misunderstood the example in the document. 🤣

![image](https://user-images.githubusercontent.com/8336744/89801351-a0d7da00-db62-11ea-9722-767b5e98d69c.png)
