### ISSUE TITLE
VS2015 Community Should have a TypeScript New Item Type in the Folder base website

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#3998]
When adding a new item (file) to a VS2015 Web Site there is no option to add a Typescript file type. Everything else under the sun, but no Typescript file option ( or Typescript Definition, d.ts ).

**Comment by paulvanbrenk** [comment]
Is that in the `File -> New Web Site...` 'project' or `File -> New Project -> ASP.NET Web Application`?

**Comment by ToddThomson** [comment]
That would be: File -> New -> Web Site from top menu. Select 'ASP.NET Empty Web Site' ( or any web site template ). Then: Add -> Add New Item . There is no Typescript file type option.
For an ASP.NET 'Project', the Add New Item dialog has a Typescript type listed.

**Comment by paulvanbrenk** [comment]
Thanks

**Comment by broomstick73** [comment]
Presumably this is actually all editions - I'm using VS 2015 Enterprise and have the same problem.
I pulled down a website from GitHub that contained some some .html and .js files and attempted to add a typescript (.ts) file to no avail. Eventually I added a JavaScript file but gave it a .ts extension. Intellisense seemed to work but it refuses to compile the typescript to JavaScript.

**Comment by mhegazy** [comment]
I would add, it should show under general in all projects:

![image](https://cloud.githubusercontent.com/assets/8000722/12763525/b8e70096-c9a9-11e5-900f-f8856298bf86.png)

**Comment by khaled4vokalz** [comment]
Same here no option in my VS 2015 Enterprise edition...
I even installed the Typescript too for vs 2015 tool manually but still no option to add a Typescript File in my Projects... When is this Bug gonna get solved?
Does this Bug avail in the Community edition too?

**Comment by ghachey** [comment]
Same problem here with Community Edition.

**Comment by joe912** [comment]
Same problem for me with Professional edition update 2

**Comment by paulvanbrenk** [comment]
The main problem is that there is no build we can hook into. So even if we add a template for TypeScript files, you still won't be able to compile them into `.js` files.

**Comment by ghachey** [comment]
Well in our project we use Grunt to compile the TypeScript into JS. So the ability to be able to simply add a TypeScript file would be nice anyway. Currently I add a Javascript file and rename to .ts which feels annoying.

**Comment by jimior2** [comment]
+1, didn't have add new item for "New Typescript File.." anymore. annoying

![image](https://cloud.githubusercontent.com/assets/654999/15062793/64eb5de0-1376-11e6-95bf-075339101a9d.png)

**Comment by paulvanbrenk** [comment]
@jimior2 Is this a website?

**Comment by jimior2** [comment]
@paulvanbrenk nope, this is Tools for Apache Cordova project.

**Comment by paulvanbrenk** [comment]
@jimior2 That's a different issue then... can you open a new bug so we can track this accordingly? Does IntelliSense work? When did the menu item stop showing up?

**Comment by jimior2** [comment]
@paulvanbrenk ok, thanks, I probably after upgrade TACO to update 9 then the new ts file disappear.

**Comment by RyanCavanaugh** [comment]
@paulvanbrenk what's your opinion of this issue as it stands?

**Comment by broomstick73** [comment]
Still doesn't appear to be fixed.
Typescript intellisense works, adding file works, but there is no "add new
typescript file" and "typescript" doesn't appear in the list of templates
for files to add.
What I do is to add an HTML file named with the .ts extension and delete
out the HTML. Works fine but is weird.

--------------------------------------
James C.
james.conley@gmail.com

**Comment by paulvanbrenk** [comment]
We have tried to fix this a bunch of times.. I'll take another stab.

**Comment by broomstick73** [comment]
could this be caused by one of the 40 extensions I have enabled?

--------------------------------------
James C.
james.conley@gmail.com

**Comment by paulvanbrenk** [comment]
No, it's probably that I haven't figured out the right location to drop the templates, so the new file dialog is able to find them.

**Comment by paulvanbrenk** [comment]
I fixed this for VS "15", should show in the release after Preview 4

**Comment by invegat** [comment]
Is there a forecast date for VS2015 Service Pack 4?

**Comment by paulvanbrenk** [comment]
@invegat currently there is none planned

**Comment by invegat** [comment]
Looking through the Preview 4 updates I didn't see any way to rename a web site though the IDE.  http://www.c-sharpcorner.com/blogs/rename-website-project-in-visual-studio-2013

**Comment by jayendranshan** [comment]
Hi,
Is this fixed? i still cant add a .ts file to asp.net website project.

**Comment by invegat** [comment]
I use this to start a new asp.net Angular 2 project.
https://jonhilton.net/2017/02/21/create-a-vs2017-angular-2-and-net-core-site-using-the-command-line/

**Comment by danwellman** [comment]
Is this still not fixed? I do the same thing as @broomstick73 above - create new HTML file but give it a .ts extension. Problem is that every single time I do this, when I open up the new .ts file and delete all the mark-up inside it, VS crashes. Every. Single. Time.

I'm using Visual Studio Pro 2015, and have Update 3 installed.

**Comment by amitkprajapati** [comment]
Please can anyone have solution for the same , I really need to add .ts file in project.
I am using vs2015 professional update3.
I tried all available solution for the same , but not get the solution.
