### ISSUE TITLE
Seemingly mismatched function types are considered compatible

### ISSUE THREAD

**Issue by ZFLloyd** [microsoft/TypeScript#39997]
**TypeScript Version:**  3.9.2

**Search Terms:** function returning  specific function type compatible parameter

**Expected behavior:**
Typescript should not allow me to pass `() => (a: string) => void` to a function explicitely expecting
 `(a: string) => void`

**Actual behavior:**
Those two types seem to be considered compatible where it should not imho. The case where I encountered this has a side-effect and needs to return void, but it's really easy to forget calling the constructor instead of passing it directly ( passing `funcTypeConstructor` instead of `funcTypeConstructor()`). Having this kind of  constructor with zero arguments is not really common so it's quite a minor issue though I would like to understand why the behaviour is so if it is intended.

If the type constructor has arguments, the problem does not appear.

**Related Issues:**
I have looked into similar issues without success so far.

**Code**
```ts

type someFuncType = (a: string) => void
const funcTypeConstructor = () => {
    return (a: string): void => {
        console.log(a);
    };
}

const test = (f: someFuncType): string => {
    f('ping');
    return 'test'

}

test(funcTypeConstructor);
test(funcTypeConstructor());



```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const funcTypeConstructor = () => {
    return (a) => {
        console.log(a);
    };
};
const test = (f) => {
    f('ping');
    return 'test';
};
test(funcTypeConstructor);
test(funcTypeConstructor());

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAzgewLZQGIFcB2BjAKpWAXhgAoBDALnhACcBLTAcwEoZCA+GANwToBNg2BJjggYAMyx4CAYWGia6bCAQ02pVhxgBvYDH0waUEOhqZSlavSbMqPfm066DLmEJEIANlAB0nhIzkzADcegYAvqHhwILyYiBQouok4lSIKBg4+NC2VgyMjjph+uIkAOQQ+WUhxYbGpuZlCaJlMdGgiSApUtlQciK0Sio0Nc1dklmycYrKqiTMNTFAA)

**Comment by MartinJohns** [comment]
[Why are functions with fewer parameters assignable to functions that take more parameters?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters)

[Why are functions returning non-`void` assignable to function returning `void`?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

**Comment by ZFLloyd** [comment]
Okay so I actually read through those in the FAQ but did not realize what happened was a combination of the two. Thanks for the quick answer it seems to be the problem here 👍 
I'll close it.
