### ISSUE TITLE
Default generic type not applied on function

### ISSUE THREAD

**Issue by nicolaes** [microsoft/TypeScript#40000]
**TypeScript Version:**  3.9.2

**Search Terms:**
Default generic type is not applied on functions. Generic parameter defaults don't imply correct type.

**Expected behavior:**
Default generic type is applied to function call when no type is supplied.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults

**Actual behavior:**
Default generic type is ignored. Applies to functions only.

**Related Issues:**
Did not find any.

**Code**
```ts
interface MyInt<T = string> {
  val: T;
}
const x: MyInt = {val: 42}; // Type error <-- ok


function foo<T = string>(x: T) {x}
const y: number = 42;
foo(y); // No error <-- this is the bug

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const x = { val: 42 }; // Type error <-- ok
function foo(x) { x; }
const y = 42;
foo(y); // No error <-- this is the bug

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CS4A8AVZAXmQGcwpQBzAPmQG8AoZZANzgBsAuZPAbgYC+DBAHsQZZAA9uGbGCL02XZABYATAN7IA9Np7oADimhQRUZDgC0l5CIDWDRzACuIBGGBjkMESPwKyChAaAAppHgBKekkhUXF5dG4QZwBbACNoBXV+HxEQ9AitXWQAORFkEzMLa2QwAAtgEmRG2rqUNOdKBiA)

**Comment by MartinJohns** [comment]
The type is inferred from the argument. The default does not kick in.

**Comment by nicolaes** [comment]
You're right, thanks for the hint. Here is an example with correct behavior:

```ts
function foo<T = string>(): T {return {} as T;}
const x = foo(); // x gets correct string type

function bar(n: number) {n}
bar(x); // Throws "Argument of type 'string' is not assignable to parameter of type 'number'"
```
