### ISSUE TITLE
Document the tsconfig.json file

### ISSUE THREAD

**Issue by phaas** [Microsoft/TypeScript#4000]
Please add documentation for the `tsconfig.json` file.

I did not find any information in the [Handbook](http://www.typescriptlang.org/Handbook) and the [1.5 Release Announcement](http://blogs.msdn.com/b/typescript/archive/2015/07/20/announcing-typescript-1-5.aspx) only links to the [pull request](https://github.com/Microsoft/TypeScript/pull/1692).

Unfortunately the pull request does not make it clear if the example given is still valid -- the subsequent discussion indicates that there were some revisions to the proposed format.

**Comment by vvakame** [comment]
https://github.com/Microsoft/TypeScript/wiki/tsconfig.json ?

**Comment by DanielRosenwasser** [comment]
We're tracking this with https://github.com/Microsoft/TypeScript-Handbook/issues/2
