### ISSUE TITLE
Typescript Compilation Performance Cliff

### ISSUE THREAD

**Issue by RyanKadri** [microsoft/TypeScript#40001]
**TypeScript Version:**  3.9.7 (Also tried with @next)

**Search Terms:**
Slow Compilation, Instantiations, diagnostics

**Code**
Reasonably minimal repro at: https://github.com/RyanKadri/slow-ts-repro

**Expected behavior:**
Adding a property to an interface increases complexity proportionally to the complexity of the type(s) you've added to the compilation process

**Actual behavior:**
In the repro above, when I un-comment the following property in a base class:
`compileSlowlyFlag: Window`
the compilation becomes a lot slower (3-4x) and the diagnostics show WAY more instantiations and a decent increase in the number of types. (In the repro, this file is `src/targets.ts`)

**Without line:** 
```
Files:              33
Lines:           27289
Nodes:          118364
Identifiers:     43743
Symbols:         30614
Types:           11241
Instantiations:   8450
Memory used:    73485K
I/O read:        0.01s
I/O write:       0.00s
Parse time:      0.42s
Bind time:       0.22s
Check time:      1.10s
Emit time:       0.00s
Total time:      1.74s
```

With line:
```
Files:               33
Lines:            27289
Nodes:           118368
Identifiers:      43745
Symbols:          86404
Types:            32060
Instantiations: 1135789
Memory used:    140815K
I/O read:         0.00s
I/O write:        0.00s
Parse time:       0.40s
Bind time:        0.20s
Check time:       5.00s
Emit time:        0.00s
Total time:       5.61s
```

Notice that types increase by a factor of ~3 and instantiations increase by a factor of **134**

It seems like this is related to how `TargetEntity` is used to derive other types. Simply including Window in a reference to other types does not cause this same increase in types or instantiations. 

For some background on this issue, for a project I was working on, I was trying to create a Spring-like way of declaring REST endpoints that parse request information (query params, headers, route params, etc) and include them as parameters to the endpoint handling functions. I noticed after a fairly routine refactor that my VSCode TypeScript features became more or less unusable and I traced it back to converting a property from an `any` type to a more descriptive type. I think I've pared my original project down to a pretty small repro of the core issue but please let me know if you'd like any help understanding what my code is trying to do or how to reproduce the issue

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
The property to save everyone else time: https://github.com/RyanKadri/slow-ts-repro/blob/37f536ff5367bd8bd9249a3669cd8a2a8321f70a/src/targets.ts#L5

**Comment by DanielRosenwasser** [comment]
Maybe @sandersn has an idea of what's going on.

**Comment by amcasey** [comment]
Something is causing an instantiation explosion.  It looks like there's some sort of conditional type related to arrays that's being instantiated too many times.

**Comment by amcasey** [comment]
Checking this expression is ridiculously expensive, but there's also something else going on.

https://github.com/RyanKadri/slow-ts-repro/blob/37f536ff5367bd8bd9249a3669cd8a2a8321f70a/src/target-endpoint-impl.ts#L16

**Comment by RyanKadri** [comment]
Yep. That makes sense. For some extra context there, before being pared down, this project used TypeORM for persistence. The `Repo` class in that file is meant to stand in for the `Repository<Entity>` type from typeorm and makes use of the same DeepPartial type. If I make `Repo` no longer generic and hardcode the type to `TargetEntity`, the instantiations go back to normal

**Comment by amcasey** [comment]
My hunch right now is that [FlatArray](https://github.com/microsoft/TypeScript/blob/1f5caf554c4c468767097db36cea52e1911e2ce2/lib/lib.es2019.array.d.ts#L21) is being instantiated too many times.

**Comment by amcasey** [comment]
FlatArray was a red herring.  Reduced repro:

tsconfig.json
```
{
  "compilerOptions": {
    "noLib": true,
    "strict": true,
    "skipLibCheck": true,
    "noEmit": true,
  },
  "files": [
    "node_modules/typescript/lib/lib.dom.d.ts",
    "node_modules/typescript/lib/lib.es5.d.ts",
    "src/concat.ts",
  ]
}
```

concat.ts
```ts
type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends Array<infer U> ? Array<DeepPartial<U>> : T[P] extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>> : DeepPartial<T[P]>;
};

const _w: DeepPartial<Window> = {} as Window;
```

**Comment by amcasey** [comment]
While it's obvious to humans that a `T` is a `DeepPartial<T>`, you can see why it would be expensive to check that structurally.  I'll dig in a bit on where the time's spent but, frankly, making every property of every type referenced directly or indirectly by `Window` optional and than comparing the resulting type to the original type is never going to be fast.  To achieve something like that, we'd have to give the compiler the same sort of hint that we're using - an assertion that a relationship exists between `DeepPartial<T>` and `T`.

Since that's not in TS's near-term plans, I'd suggest using `as any as DeepPartial<Window>` as a workaround.

**Comment by amcasey** [comment]
We'll take a note that high-level assertions about relationships between types might be useful but, at the moment, there's not much to be done about this - huge comparisons are expensive.  Thanks for reaching out and, in particular, for the reduced repro!
