### ISSUE TITLE
Incorrect indenting for promise 

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#4001]
Hi,

**Version**: VS 2015 RTM/TS 1.5

The formatting for the `then` callback seems wrong. Towards the end, I am required to hit Cntrl+D to get the document to format. I shouldn't have to do this.

![giff1](https://cloud.githubusercontent.com/assets/1106823/8856165/f4a0996c-3160-11e5-82ff-108b0e66741c.gif)

**Comment by RichiCoder1** [comment]
Very much agree with this. Drives me crazy.

**Comment by danquirk** [comment]
This is the kind of bug that one could call minor but is in fact anything but.

**Comment by mhegazy** [comment]
This has been fixed in latest bits. thanks to @SaschaNaz.
