### ISSUE TITLE
Intl.NumberFormat does not include 'notation' in the list of known properties.

### ISSUE THREAD

**Issue by ztolley** [microsoft/TypeScript#40018]
To recreate:

```
    const x = new Intl.NumberFormat('en-GB', {
      notation: 'compact',
      compactDisplay: 'short',
      maximumFractionDigits: 1,
    }).format(987654321)
```

 "Argument of type '{ notation: string; compactDisplay: string; maximumFractionDigits: number; }' is not assignable to parameter of type 'NumberFormatOptions'.\n  Object literal may only specify known properties, and 'notation' does not exist in type 'NumberFormatOptions'."

**Comment by bdrazen** [comment]
Getting this as well. Why closed?
