### ISSUE TITLE
asserting "false is NonNullable<boolean>" triggers unreachable code detection

### ISSUE THREAD

**Issue by max-vogler** [microsoft/TypeScript#40017]
**TypeScript Version:**  3.8.2, 3.9.2

**Search Terms:** unreachable code, asserts, assertion, nonnullable, type guard

**Expected behavior:** The code compiles without warnings.

**Actual behavior:** Any code after `assertNonNull(false)` is marked as unreachable.

**Related Issues:** -

**Code**
```ts
function assertNonNull<T>(value: T): asserts value is NonNullable<T> {
  if (value === null || value === undefined) {
    throw new Error(`Expected value to be non-nullable, but got ${JSON.stringify(value)}`);
  }
}

assertNonNull(0);
assertNonNull('');
assertNonNull(false);
console.log("end"); // Unreachable code detected.
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function assertNonNull(value) {
    if (value === null || value === undefined) {
        throw new Error(`Expected value to be non-nullable, but got ${JSON.stringify(value)}`);
    }
}
assertNonNull(0);
assertNonNull('');
assertNonNull(false);
console.log("end"); // Unreachable code detected.

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.8.2#code/GYVwdgxgLglg9mABAQwM6oKYCcoDkG4gA2RAPACoB8AFAG7JEgYBci5AlK2pjqovYwyIYffGEIlkAIyIYKlRAG8AUImHBEdBk0QBefYjDEiiAD6n+2oft2JwAEwzAYYDPfZLVaxFAAWWOAB3QwxggFEsAKxqAAMwgA8ABwxoN0tBHzhEKSEwBABaI0kZDAAabJAoRABzOCqAEkUAKQBlAHlcADpUKCwXaphgAE8tQXYAXxj2AG4vceV55W5sPAJjagAGGaX0FbEJImoAciPt5Zx99eAGTG2IBFQ4WU6iOGrqACIMMHsPmcQAPQAxAAVTAWAwyAgvmkskQ90ciEcUBSKPsnSAA)

**Comment by mprobst** [comment]
I think this is only reported as unreachable with `allowUnreachableCode: false`, right?

**Comment by max-vogler** [comment]
`tsc` reports a hard error ` TS7027: Unreachable code detected.` for `allowUnreachableCode: false`. If the config option is `undefined` or `true`, `tsc` compiles the code without errors. This is expected per [tsconfig#allowUnreachableCode](https://www.typescriptlang.org/tsconfig#allowUnreachableCode), but still does not explain the unexpected behavior of my issue.

**Comment by jack-williams** [comment]
Did you try master? Looks to be a duplicate of #38699 which is now fixed.

**Comment by max-vogler** [comment]
You're right. Switching to 4.0.0-beta in the playground removes the error.
