### ISSUE TITLE
recursive deep property access works unless the assigned variable has explicit type annotation?

### ISSUE THREAD

**Issue by tadhgmister** [microsoft/TypeScript#40022]
### This isn't really actionable as is, just seemed odd enough I wanted to post it.

**TypeScript Version:**  4.0.0-beta

**Search Terms:**
explicit annotation, (2589), recursion, recursive type, variadic tuples, deep property access
**Expected behavior:**
the definition of `slice` in below code should not conditionally fail based on the presence of an explicit type annotation.
**Actual behavior:**
`const a = slice(simple, "a")` works with inferred type of `number` where `const a: number = slice(simple, "a")` fails claiming `Type instantiation is excessively deep and possibly infinite.` despite the tooltip in the playground showing all the correct types.

**Related Issues:**
couldn't find any similar issues
**Code**
```ts
/**
 * resolves the type of an object from a list of nesting keys.
 */
type ResolveKeys<T, K extends unknown[]> = K extends [] ? T 
    :K extends [infer A, ...infer Rest]
        ? {[kk in A & keyof T]: ResolveKeys<T[kk], Rest>}[A & keyof T]
    : unknown;

/**
 * returns extension on valid keys list
 * this is set to be specifically recursive to mimic the behaviour of something like this:
  | [keyof T, keyof T[K[0]]]
  | [keyof T, keyof T[K[0]], keyof T[K[0]][NonNullable<K[1]>]]
  | [keyof T, keyof T[K[0]], keyof T[K[0]][NonNullable<K[1]>], keyof T[K[0]][NonNullable<K[1]>][NonNullable<K[2]>]]
 * this is obviously not maintainable when hardcoded in that way, so this intends to read the length of arguments given and
 * return a suitable list of valid arguments.
 */
type NestedIndex<T, K extends [keyof T, ...unknown[]]> = 
    // if there are no common keys given the current info then don't have any valid keys.
    keyof T[K[0]] extends never ? []
    // if we end up with a total wild card then stop the list, this can happen if using a union variable and we lose all safety for fields after it if we don't check here.
    : (keyof any) extends keyof T[K[0]] ? [] 
    // otherwise see if we have at least one extra element in our list
    : K extends [K[0], infer A, ...infer R]
        ? [A] extends [keyof T[K[0]]]
            // if A is valid then we can keep going recursively, using a bit of object literal trickery
            //  so typescript doesn't complain we are circularly defined.
            ? {[k in K[0]]: [keyof T[K[0]], ...NestedIndex<T[K[0]], [A, ...R]>]}[K[0]]
            // if an element of the key list isn't a valid key then we use never[] to short circuit a bunch of irrelevent possibilities from being generated in invalid cases.
            : [keyof T[K[0]], ...never[]]
        // if we don't have an extra element then we could choose to extend the list by 1 or not.
        // since this is in the constraint I don't think this is noticable ever, but still in theory it's the right way to put it.
        : [] | [keyof T[K[0]]]


declare function slice<T, K extends [keyof T, ...NestedIndex<T,K>]>(obj: T, ...keys: K): ResolveKeys<T,K>

interface RecursiveData {
    a: {
        b: RecursiveData
    }
    c: string
}
declare const complicated: RecursiveData;
// this type works perfectly well with arbitrary nested types
const no_issue_here = slice(complicated, "a", "b", "a", "b", "c")

declare const simple: Record<"a", number>
// however the moment the variable has any explicit type annotation this gives infinite recursion?
const fail: number = slice(simple, "a")
const working      = slice(simple, "a");
const work2: number= slice<Record<"a", number>, ["a"]>(simple, "a")
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// this type works perfectly well with arbitrary nested types
const no_issue_here = slice(complicated, "a", "b", "a", "b", "c");
// however the moment the variable has any explicit type annotation this gives infinite recursion?
const fail = slice(simple, "a");
const working = slice(simple, "a");

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**[Playground Link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200807#code/FAegVGwARlBOBTAzgewDYDdlQC4AsFcBPAB0JQDMoBDAOyhQCMArBAYxygrhQFsaoaAJZJOlKLWQ4htAOZQA1giJIAdNDAhgOUoQBKydFgDSypAB4AKgBooxqAgAeOBLQAmSKAFdaC2igB3WgBtAF0APigAXjsHZ1cPKDCoAH4oSyhoKGyALnsnF3dPYJkKBDgoAEFbVVrS8qgDUVCs7LbUqABvYIUFKBkqqAAyRWVxS1CcxsNMBFMVKx6FUNsmnHCAX2DK4dGicZb2qZ8-QNoAbmBQCA14BBwvOFpPAtckIRR6T6gMamE3PaeYSiW74ET9TxIe64FBQRiEJBkNhCChCNh-NBEO5sR7vLAwqC8IREti4AhwhB4agYD6PBhUVC8e54GTyYRKMkiHJZAA+SSU+yoNj242CxmCAAZQtLefyxkLbALReKpSsRUKxZLpcEAHKfHVeNBoaiMNAIczigCMERl2T5PXl6UVjssmtVzsF6Td2r1tANRpNZotwWt4TVSo1Kp9+sNxtN5qtNt1MYD8eDACYbYdYGDPOCmDSUF4kJiJChOLxqDIcFXaIHCAECPQqXA3GwUG4EACBvhqJwAtQiLZUJy87RCokcLDENQAfhCGa5Ph6TQ4LIvEzx55ZEIsPQ6G5bogHk8BEgvEIa-HBCIxFRfv9V+vNzg1BotDoyFAdVIuwBJdwnCsWx8niIo5U9YValUE5-CCMIImiTJ2hAEB+ioedEFXQh-CgdteF4b4BW3XdXDJQgcTgRBx36WgKFhed6DcT4AHJOCpfE6CxB8hABYj1HaCMvSjUI4gnTxJCwCo0jCVooFQ9CoACQgEm8EglMvPABCnGs0A0tAAXRVtyPoUQUHU+cb1EWxczwugoCpEgyHoFFvHeOQBB8D56F+OAhHrGh3CUhcUChGgjSgJBqDKHQuBQCpUQQAzPGilwKkvRTlKgZjaDYvCCDYPoCEQAS2imAAKISuIASjEhJPCE10RI6ZI5IU8tioCEQEQQQhXKyjjCD7QQEGoUQGEkMS4GoBwzRfWiGDpYEcDkqZQPEpIo1seoKmqKBoJ2xpDnaNoZMqUTXnAh1IO9W0TvuhTXJ2cEeLnJtgrs+glAQdTZBQVlsVxUjMVsYsAZmxgMvEJhWA4G80r+XA-MK8oiDk+7sgUyKGN0JA2D8khOGY5Bcs4fCSGNAYsuoLDkTgHFjTgUtO1RSQ3FKjHTq6HoFpEqZruVLU1Wgn9RH-QDHEWETbG2Gpaj0G0thE9GMceqh7KShB5vESyBSszgRFJgRXr2EyPuLHCECk5Ip0ivB4rJoR6YvTgIZ8NgtPEJ3EDNPdOBIUL3kh4RpGwbg+ApAHZFcco+y7BaZBN9EoTfTmjggwX3X22pJPKBCVcxtD+sIHK8sGwKppmzX5sYj720NQz7dCwhbcut6F1vOEsUtBgKn8HAOZOhT3LYFuWTzMdyLwz5RGm6soD-bLWM4MFfFHCEy2kdFryt8pbEYLxOFEIQIp7Ah4qxS8WM8Sy-NkPB+0HAkSEP-oB4LqB+dE+1Gtulork7GwRmhAKDu2kN8EsaJzTCnWvVDOCps6qFFi4NwAFOySxsMYMM4RyowymFBWoxE1rVSmE0IwcwzDASwVcas5QKDUFHtMSieIEAABE+wzU6HJagUwuGc0YKQ9gQMsDsJrHJDYck2BTFnqyYAEjAHAOns8MmfAKZojjm4QRzDSKiOoJcBStlPwNnigoTwZA4BlA4KWZSEUurLhppDHA004BYkkGLOcuNgDtmUWWAA+iIc8CBfHFUIDESBo9yrk2EOiFBtgABE1A4nxMYEkqACTUlxJSfEtgcTqoAPYIo7x413i8ApggLR8U3DmHSbYWgG54RwHCKANC9tlJSSnoRGu5JfL+WvFSFKtAsRODUciFeuhAr9z7N5deO4sBjlZpeQgiBtGfBSF4menB6EnymHU3gDSkLhIQOVEpZT4mJLyUU-sJiAYnTCdEo5JyzRnNyZcS5SkTHph2fU8odyoHmAMO2Vs1TEm1O+Y0mW6SIjHOJKctJ5ygA)**

**Comment by RyanCavanaugh** [comment]
Presenting a contextual type does have influence on inference, so seeing different results depending on different code is not per se indicative of a bug.

This repro would take hours to understand and doesn't seem to directly indicate a defect; if anyone can boil this down into something that unambiguously demonstrates a bug we can investigate earlier, but we have many more approachable issues to address first.

**Comment by david-shortman** [comment]
using 4.2.3 this appears to no longer be an issue: [playground](https://www.typescriptlang.org/play?ts=4.2.3#code/FAegVGwARlBOBTAzgewDYDdlQC4AsFcBPAB0JQDMoBDAOyhQCMArBAYxygrhQFsaoaAJZJOlKLWQ4htAOZQA1giJIAdNDAhgOUoQBKydFgDSypAB4AKgBooxqAgAeOBLQAmSKAFdaC2igB3WgBtAF0APigAXjsHZ1cPKDCoAH4oSyhoKGyALnsnF3dPYJkKBDgoAEFbVVrS8qgDUVCs7LbUqABvYIUFKBkqqAAyRWVxS1CcxsNMBFMVKx6FUNsmnHCAX2DK4dGicZb2qZ8-QNoAbmBQCA14BBwvOFpPAtckIRR6T6gMamE3PaeYSiW74ET9TxIe64FBQRiEJBkNhCChCNh-NBEO5sR7vLAwqC8IREti4AhwhB4agYD6PBhUVC8e54GTyYRKMkiHJZAA+SSU+yoNj242CxmCAAZQtLefyxkLbALReKpSsRUKxZLpcEAHKfHVeNBoaiMNAIczigCMERl2T5PXl6UVjssmtVzsF6Td2r1tANRpNZotwWt4TVSo1Kp9+sNxtN5qtNt1MYD8eDACYbYdYGDPOCmDSUF4kJiJChOLxqDIcFXaIHCAECPQqXA3GwUG4EACBvhqJwAtQiLZUJy87RCokcLDENQAfhCGa5Ph6TQ4LIvEzx55ZEIsPQ6G5bogHk8BEgvEIa-HBCIxFRfv9V+vNzg1BotDoyFAdVIuwBJdwnCsWx8niIo5U9YValUE5-CCMIImiTJ2hAEB+ioedEFXQh-CgdteF4b4BW3XdXDJQgcTgRBx36WgKFhed6DcT4AHJOCpfE6CxB8hABYj1HaCMvSjUI4gnTxJCwCo0jCVooFQ9CoACQgEm8EglMvPABCnGs0A0tAAXRVtyPoUQUHU+cb1EWxczwugoCpEgyHoFFvHeOQBB8D56F+OAhHrGh3CUhcUChGgjSgJBqDKHQuBQCpUQQAzPGilwKkvRTlKgZjaDYvCCDYPoCEQAS2imAAKISuIASjEhJPCE10RI6ZI5IU8tioCEQEQQQhXKyjjCD7QQEGoUQGEkMS4GoBwzRfWiGDpYEcDkqZQPEpIo1seoKmqKBoJ2xpDnaNoZMqUTXnAh1IO9W0TvuhTXJ2cEeLnJtgrs+glAQdTZBQVlsVxUjMVsYsAZmxgMvEJhWA4G80r+XA-MK8oiDk+7sgUyKGN0JA2D8khOGY5Bcs4fCSGNAYsuoLDkTgHFjTgUtO1RSQ3FKjHTq6HoFpEqZruVLU1Wgn9RH-QDHEWETbG2Gpaj0G0thE9GMceqh7KShB5vESyBSszgRFJgRXr2EyPuLHCECk5Ip0ivB4rJoR6YvTgIZ8NgtPEJ3EDNPdOBIUL3kh4RpGwbg+ApAHZFcco+y7BaZBN9EoTfTmjggwX3X22pJPKBCVcxtD+sIHK8sGwKppmzX5sYj720NQz7dCwhbcut6F1vOEsUtBgKn8HAOZOhT3LYFuWTzMdyLwz5RGm6soD-bLWM4MFfFHCEy2kdFryt8pbEYLxOFEIQIp7Ah4qxS8WM8Sy-NkPB+0HAkSEP-oB4LqB+dE+1Gtulork7GwRmhAKDu2kN8EsaJzTCnWvVDOCps6qFFi4NwAFOySxsMYMM4RyowymFBWoxE1rVSmE0IwcwzDASwVcas5QKDUFHtMSieIEAABE+wzU6HJagUwuGc0YKQ9gQMsDsJrHJDYck2BTFnqyYAEjAHAOns8MmfAKZojjm4QRzDSKiOoJcBStlPwNnigoTwZA4BlA4KWZSEUurLhppDHA004BYkkGLOcuNgDtmUWWAA+iIc8CBfHFUIDESBo9yrk2EOiFBtgABE1A4nxMYEkqACTUlxJSfEtgcTqoAPYIo7x413i8ApggLR8U3DmHSbYWgG54RwHCKANC9tlJSSnoRGu5JfL+WvFSFKtAsRODUciFeuhAr9z7N5deO4sBjlZpeQgiBtGfBSF4menB6EnymHU3gDSkLhIQOVEpZT4mJOqpcIp-YTEAxOmE6JRyTlmjObky5GylImPTDs+p5R7lQPMAYdsrZqmJNqT8xpMt0kRGOcSU5aTzlAA)

**Comment by tadhgmister** [comment]
that it does, well cool. thanks.
