### ISSUE TITLE
NumberFormatOptions interface is missing compactDisplay and signDisplay properties

### ISSUE THREAD

**Issue by wyze** [microsoft/TypeScript#40038]
**TypeScript Version:**  3.9.2

**Search Terms:** NumberFormatOptions compactDisplay signDisplay

**Code**

```ts
console.log(new Intl.NumberFormat('en', {
    currency: 'USD',
    signDisplay: 'never',
    style: 'currency',
}).format(-1.5));

console.log(new Intl.NumberFormat('en', {
    compactDisplay: 'long',
    notation: 'compact'
}).format(100000));
```

**Expected behavior:**

`compactDisplay` and `signDisplay` should be usable for [NumberFormatOptions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/NumberFormat).

**Actual behavior:**

```
Argument of type '{ currency: string; signDisplay: string; style: string; }' is not assignable to parameter of type 'NumberFormatOptions'. Object literal may only specify known properties, and 'signDisplay' does not exist in type 'NumberFormatOptions'.

Argument of type '{ compactDisplay: string; notation: string; }' is not assignable to parameter of type 'NumberFormatOptions'. Object literal may only specify known properties, and 'compactDisplay' does not exist in type 'NumberFormatOptions'.
```

**Playground Link:** https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUZYHcAEBJMALtPAHICuAtgEawBOAYiLRQIYGoDksYHANNgG8AUNlHZgZWrW7AAngC5sHAKoBlACJ8RYiAEtkYdbogAHaCwVKMANzpax2CAVlxFHCVJmytAXwCU8ABmTKzsALQAjPAArH5+ANxCQqCQMAhIaBg4+ESklDQMIWyc3HyC2qKgFCYswARGpuaWHEhgyPZiYCAEbLrgblU1dRxC-kFF7BEADDMzcfFAA

**Related Issues:** 

- #38012
- #36533

**Comment by DanielRosenwasser** [comment]
Thanks!

**Comment by daniyaniazi** [comment]
Hey , I am facing this issue any solution yet

**Comment by yassin-assim** [comment]
I have the same issue with currencyDisplay:

`Argument type {
  minimumFractionDigits: number,
  currencyDisplay: string,
  style: string,
  currency: string
} is not assignable to parameter type NumberFormatOptions | undefined 
`
