### ISSUE TITLE
Conditional type T extends U ? X : Y is either resolved to X or Y, should not be both (X|Y)

### ISSUE THREAD

**Issue by bingtimren** [microsoft/TypeScript#40049]
**TypeScript Version:**  4.1.0-dev.20200813

**Search Terms:** conditional type any extends

**Code**

```ts
type YesAndNo = any extends object ? 'Y' : 'N'; // type YesAndNo = "Y" | "N"
const yes : YesAndNo = 'Y' // no problem
const no : YesAndNo = 'N'  // no problem
```

**Expected behavior:**

The handbook [https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types](url) defines a conditional type as:

> A conditional type selects **one of two** possible types based on a condition expressed as a type relationship test... A conditional type ```T extends U ? X : Y``` is either resolved to **X or Y**, or deferred because the condition depends on one or more type variables. 

Does ```any extends object```? That is the question. However whatever the answer is, the result should be either X or Y, not X|Y.

Is this an expected behaviour? I cannot see that from the definition in handbook.

**Actual behavior:**

Type YesAndNo is resolved to "Y" | "N", meaning **both** branches are picked. This is the Schrödinger’s cat in Typescript.

**Playground Link:** [https://repl.it/@RenBing/ScrawnyMarriedBoard](url)

**Related Issues:**

**Comment by jack-williams** [comment]
This isn't especially well-documented outside of the source-code, but in the checker you'll find in the relevant place:
```ts
// Return union of trueType and falseType for 'any' since it matches anything
if (checkType.flags & TypeFlags.Any) {
```
So `any` is treated like a wildcard that matches both branches.

**Comment by bingtimren** [comment]
This put the conditional type expression at compile time different than the conditional value expression at run time. Personally I feel it's natural to just take the left branch if the condition evaluates true... even it also evaluates false? Are we also introducing a third Boolean literal 'trueandfalse' here?

**Comment by RyanCavanaugh** [comment]
There's nothing especially unsurprising about this result given how conditional types work in general. A conditional type will *frequently* produce a union of both of its outputs, e.g. `type M<T> = T extends true ? 1 : 0` will produce `1 | 0` for `M<boolean>`

**Comment by bingtimren** [comment]
At least I want to say this is incongruous. One would expect the part before "?" is a kind of boolean expression, which result determines the value to take the left or right branch... and this is indeed written in the handbook. 

Conditional type taking a union of both branches feels incongrous. 

Also this example ```type M<T> = T extends true ? 1 : 0``` also confused me. Can you point me to somewhere in the handbook that explain this behaviour? How does 'extends' produces its result exactly?

However I do understand that Typescript is a dynamic and developing language, and that's one of its charms. It's understandable that documents may lag a few steps behind the actual language. I'm now closing this issue if it's intended. Though still I think this is incongrous.

**Comment by wffurr** [comment]
I just ran into this today and found the union result to be quite surprising.
