### ISSUE TITLE
When assigning to a type, using a literal and using a const of the same literal results differently

### ISSUE THREAD

**Issue by bingtimren** [microsoft/TypeScript#40045]
**TypeScript Version:**  4.1.0-dev.20200813

**Search Terms:** assignable extends 

**Code**

```ts
interface Base {n:string}
interface Sub extends Base {v:number}
const sub : Sub = {n:"name", v:1}

const base : Base = {n:"name", v:1}    //  this is a rightful error
const base2 : Base = sub  // then how can this pass?
```

**Expected behavior:**

The compiler checks if a value is **assignable** to a type before an assignment. It should be expected that whether the value is expressed as a literal or as a constant of the same literal does not affect the outcome of the determination of **assignable**. The above example breaks this expectation.

**Actual behavior:**

Compiler reports an error on this line, which is correct.
```const base : Base = {n:"name", v:1}    //  this is a rightful error```

However compiler ignores this line without an error.
```const base2 : Base = sub  // then how can this pass?```

**Playground Link:** [https://repl.it/repls/WorldlyWryUsername](url)

**Related Issues:** 

I guess this issue is related to the confusion of "extends" and "assignable". In Java, if class SuperHero extends class Human, then a SuperHero instance is assignable to a Human variable. In Typescript, this is actually not guaranteed. I'm guessing that somewhere in the logic determining "assignable", where the value has a type, "extends" is determined to be "assignable". 

In my opinion this should not be the expected behaviour. Correct me if I'm wrong.

**Comment by MartinJohns** [comment]
> const base : Base = {n:"name", v:1}    //  this is a rightful error

When assigning object literals TypeScript performs an "excess properties check", and errors when you provide more properties. This is done based on the assumption that you really just wish to create a `Base`, and any additional properties are unwanted.

> const base2 : Base = sub  // then how can this pass?

This passes, because `sub` contains all properties that `Base` requires, so the types are compatible and an assignment is possible.

---

Everything works as intended and expected.

**Comment by bingtimren** [comment]
Well at least this makes the concept "assignable" complex and inconsistent. I am expecting that if additional properties are allowed, there should be ```[k:string]:any ``` inside Base, otherwise it would not be allowed. If this is the expected behaviour, maybe it should be put in the handbook? But still it feels a bit unnatural to behave this way, to treat const and literature differently.

**Comment by bingtimren** [comment]
One should argue that the definition of Base decides what's acceptable and what's not, as far as the compiler can determine at compile time. This behaviour breached this expectation. What's acceptable become dependent on **how** you assign it, not **what** you assign it.

**Comment by MartinJohns** [comment]
> Well at least this makes the concept "assignable" complex and inconsistent. I am expecting that if additional properties are allowed, there should be `[k:string]:any `inside Base, otherwise it would not be allowed. If this is the expected behaviour, maybe it should be put in the handbook?

[What is structural typing?](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing)

> What's acceptable become dependent on how you assign it, not what you assign it.

These are just two different mechanisms at play. Excess property checks also happen when returning an object literal in a function.

**Comment by bingtimren** [comment]
Ok, thanks for the clarifications. I understand this is how it works, though now how I had expected it to work. Thanks again for pointing me to the wiki. I'm now closing this issue.
