### ISSUE TITLE
Provide a quick fix to add missing enum member

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40056]
```ts
enum TokenKind {
  LeftBrace,
}

function scan(text: string, pos: number) {
  let c = text[pos];
  switch (c) {
    case '{': return TokenKind.LeftBrace;
    case '}': return TokenKind.RightBrace;
  }
}
```

We should have a quick fix for the error message

```
Property 'RightBrace' does not exist on type 'typeof TokenKind'.
```

to add `RightBrace` as a missing enum member. The resulting code should look like

```ts
enum TokenKind {
  LeftBrace,
  RightBrace,
}

function scan(text: string, pos: number) {
  let c = text[pos];
  switch (c) {
    case '{': return TokenKind.LeftBrace;
    case '}': return TokenKind.RightBrace;
  }
}
```

**Comment by DanielRosenwasser** [comment]
One could probably fold in the logic into the existing "add missing member" quick fix, which would be preferable.

**Comment by DanielRosenwasser** [comment]
"What happens if you have something that's both a class and enum?"

I don't really know. If it's being used in a comparison or the contextual type is string-like or numeric, probably add it to the enum. Otherwise add it to the static side of the class. 🤷🏻‍♂️

**Comment by JoshuaKGoldberg** [comment]
Err, @DanielRosenwasser this already exists, I think. Copy & pasting that sample into the playground does give a quick fix.

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/KYOwrgtgBAKg9ga1AaQJYgCZQN4CgAywAZgC4BCATgIYDGwANLgEqoDmAFudXbgL664iYEDRKo4IKAGcaVEAAoSwAB4kAXNJIV0relAAOcKRvAQARsAoBKHLihQANsBJQaUALxQlqgNqGpALoA3HbSAO6oJDTsUPI0Nnj29rJSwFAA5NjpGhTOYBSS8EggaJgAdISklLTAIUmuVKkZvNlQuST5hYgo6BhlLBxcNXVQ-LxAA)

**Comment by a-tarasyuk** [comment]
https://github.com/microsoft/TypeScript/blob/2426eb4980d34c762e745cdb5062ca211e65f25e/src/services/codefixes/fixAddMissingMember.ts#L19-L23
