### ISSUE TITLE
Can't wrap variadic tuples into other generic types

### ISSUE THREAD

**Issue by ClementNerma** [microsoft/TypeScript#40060]
**TypeScript Version:**  4.1.0-dev.20200813

**Code**

```ts
interface Decoder<T> {
    // ...
}

export function decodeTuple<T extends unknown[]>(
    decoders: [...Decoder<T>] // ERROR
): Decoder<[...T]> {
    // ...
}
```

**Expected behavior:** This code should work fine

**Actual behavior:** The `decoders` argument's type causes an error: `A rest element type must be an array type.ts(2574)`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.0-beta#code/JYOwLgpgTgZghgYwgAgCIQQewCbQDwAqAfMgN4BQyVyA9DcgHRPkC+55EAHgA6ZRjIYAVxAIwwTCGS4suAkO4AbCIWRdIIbAGdkIgNYhMAdxABtALpEAFJWoyc0LQC5kppg3Sz8xc7XoBRACVAgHlA8gBKF08HKDw3JgJLMlsqOkZmFiA

**Comment by ahejlsberg** [comment]
This is working as intended. A rest element must have an array type, and `Decoder<T>` isn't. It works if you have `Decoder<T>` extend `Array<T>`:

```ts
interface Decoder<T> extends Array<T> {
    // ...
}
```

**Comment by ClementNerma** [comment]
Indeed, but what I want is to have an array of `Decoder<T>`, without `Decoder<T>` being an array itself.
