### ISSUE TITLE
Conditional type doesn't work inside tuple

### ISSUE THREAD

**Issue by ienzam** [microsoft/TypeScript#40067]
**TypeScript Version:**  4.1.0-dev.20200807

**Search Terms:** conditional type tuple

**Code**

```ts
type Tuple<T> = [T extends null ? T? : T];

```

**Expected behavior:**
Expected the definition to work as expected.

**Actual behavior:**
Got the following error:
> JSDoc types can only be used inside documentation comments.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/C4TwDgpgBAKgrmANhAPDAfFAvFA2jKCAD2AgDsATAZyjLkUSgH5YWAuWAXQG4AofgPQCoASSgALAIYA3aMAD2UCovnBxEAE4B3AJZUIvUJCgB5MMDSYc+Jj0PhoAJQgBHS9jww7R6AFlNAOaoGB4ExKSUNHQMzKbm7hzObhh8QA)

**Related Issues:** Did not find anything close.

**Comment by jack-williams** [comment]
As per #24897, outside of JSDoc the `?` modifier is only valid for tuple elements, not arbitrary types. It does not make sense to say that a type can be omitted, only that an element can be omitted.

**Comment by ienzam** [comment]
The above definition is inside a tuple, and one way to look at that is the element can be omitted or not.
But I guess that messes up in other ways like making sure all the other elements are optional too.
