### ISSUE TITLE
some comments are missing when using the compiler API 

### ISSUE THREAD

**Issue by unbregg** [microsoft/TypeScript#40074]
**TypeScript Version:**  4.1.0-dev.20200816

**Search Terms:** comments are missing

**Code**

```ts
const ts = require('typescript');
const printer = ts.createPrinter();
const sourceFile = ts.createSourceFile('', `
const arr = [//hello
    {
        obj: ''
    }
]
`)

console.log(printer.printFile(sourceFile))
```

**Expected behavior:**
output:
```ts
const arr = [//hello
    {
        obj: ''
    }
]
```
**Actual behavior:**
output(comments are missing):
```ts
const arr = [
    {
        obj: ''
    }
]
```
**Playground Link:** 

**Related Issues:**

**Comment by xqin** [comment]
AND  THIS:

https://www.typescriptlang.org/play?target=99&jsx=3&ts=4.0.0-beta#code/FDDGBsEMGdoAgBpwN7DuuAPOBedqNC5IAuOAckknIBo4B6euAWwEtZWA7AczSPQBGZStTr0AVC3bQu3OOPp9+AE2FVaDcQEIpHHvMX90AUzWjNk3TP0KlRUGWQBfBkwDurcODgBrY8YAHOycQQlAAe05oABcAJwBXUGjw2LgACgBKFDtCADdIVIBPXGyjIlIKdTFJNj05WzLCIThOeK9XOA92v0CcjBDCELtGFmNogAtw5ThCu2LMlA7mMcnpwvX02utuDL70EeWJqZn19eDgJyA

![image](https://user-images.githubusercontent.com/1265888/90361261-5093d700-e090-11ea-8a4f-939ce9beb830.png)


All the missing part, we want keep it in the result.

**Comment by RyanCavanaugh** [comment]
The parser doesn't preserve 100% of comments and isn't intended for this purpose. You should use a different library if preserving 100% of comments is a design constraint for your application.

**Comment by weswigham** [comment]
https://github.com/microsoft/TypeScript/issues/17689

**Comment by marc3lsk** [comment]
I found following unexpected behaviour with tsx (v4.1.2):
```javascript
class Component {
    render() {
        return <div>
            {/* missing */}
            {null/* preserved */}
        </div>;
    }
}
```
