### ISSUE TITLE
Completion: Higher priority for the same name when assign access expression to property 

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#40078]
## Search Terms
completions

## Examples
```ts

interface T {
  a: string
  b: number
}

interface U {
  b: number
}

declare const a: T

const b: U = {
  b: a. /*Currently is dictionary order but usualy assume as a.b */
}

```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This just seems a little too magical; the completion order can't have *too many* heuristics or it becomes very unpredictable

**Comment by Kingwl** [comment]
Are there any plan to improve suggestion by more contextual info？eg: same type, same name,etc. 
In my usages of jetbrains it's fells better.
