### ISSUE TITLE
Error in wiki on What's New page

### ISSUE THREAD

**Issue by zuzusik** [Microsoft/TypeScript#4007]
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#computed-properties has the following code example:
```typescript
function makeNode(name: string, initialNeighbor: Node): Node {
    return {
        name: name,
        neighbors: {
            [initialNeighbor.name] = initialNeighbor
        }
    }
}
```
On line `[initialNeighbor.name] = initialNeighbor` it should  be `:` instead of `=`

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up - in the future, if you see a problem with our wiki you can send a pull request yourself to https://github.com/Microsoft/TypeScript-wiki.
