### ISSUE TITLE
Issue in comparing number like 121 >= 50 , expected result true but getting false

### ISSUE THREAD

**Issue by mupadhyaya** [microsoft/TypeScript#40080]
Hi there,

I found the problem while working on testing >= comparison operator. In while comparing 121 >= 50 it always return false and we can see it should be true.

Is there anything I am missing? I am using Angular 9 and I believe it is the issue related with typescript. If anywhere I am incorrect please advise me for the correction.

`import { Component, TrackByFunction } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
})
export class AppComponent  {
 
  constructor(
    
  ) {}

  

  ngOnInit() {
    let value1 = "121";
    let value2 = "50";
    let flag = value1 >= value2; // 121 >= 50 => true
    console.log(`${value1} >= ${value2} expected: true, output:`, flag);
  }`

**Comment by MartinJohns** [comment]
There's an [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md). Please use it, it makes the work for the TypeScript team much easier. 👍

---

Related / duplicate: #36534 / #26592.

This behavior is intentional.

**Comment by mupadhyaya** [comment]
> There's an [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md). Please use it, it makes the work for the TypeScript team much easier. 👍
> 
> Related / duplicate: #36534 / #26592.
> 
> This behavior is intentional.

It seems like its intentional to move towards strongly typed language.   Apology for not following the bug template, just was in hurry while writing the concern.
