### ISSUE TITLE
False in logical conjunction causes missed null check

### ISSUE THREAD

**Issue by joarwilk** [microsoft/TypeScript#40093]
**TypeScript Version:**  3.9.2

**Search Terms:** false logical conjunction null

**Expected behavior:** Both statements should be valid

**Actual behavior:** One statement causes a typescript error

**Code**
```ts
const str: string | null = Math.random() > 0.5 ? "Hello World" : null;

const isfalse = false;

false && str && console.log(str.length) // Object (str) is possibly 'null'.
isfalse && str && console.log(str.length) // Valid

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const str = Math.random() > 0.5 ? "Hello World" : null;
const isfalse = false;
false && str && console.log(str.length);
isfalse && str && console.log(str.length);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/MYewdgzgLgBNBOAuOV4EswHMYB8ZgFcAbImAXhgFkBDKACwDp5qwATEAWwAoBKGAPhgAGBgFYYAfhgAiABIBTEiBgB1EPCKtpMZIRIBuAFCHQkWGggAzakQjzyMa7flHDTuzABknlPC8-TCBAieQYiEEwuBDD5LHoeQwt3e29ffxhA4NDwyOiQuLoEoA)

Not the worst bug in the world and not very relevant for production scenarios, but interesting nonetheless.

**Comment by RyanCavanaugh** [comment]
Duplicate #26914
