### ISSUE TITLE
error when a variable is both read as a parameter and written as a result of a function call in an async do while loop

### ISSUE THREAD

**Issue by joeflateau** [microsoft/TypeScript#40096]
**TypeScript Version:**  v4.1.0-dev.20200817

**Search Terms:**

**Code**
```ts repro
let token: string | undefined = undefined;


do {
  const response = listObjectsSync({
    token: token
  })
  token = response.token;
} while (token != null)


(async () => {
  do {
    const response = await listObjectsAsync({
      //  ^^^^^^^^ errors - 'response' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
      token: token
    })
    token = response.token;
  } while (token != null)
})()


function listObjectsSync(params: { token: string | undefined }): { token: string | undefined } {
  console.log(params);
  return {
    token: undefined
  }
}

async function listObjectsAsync(params: { token: string | undefined }): Promise<{ token: string | undefined }> {
  console.log(params);
  return {
    token: undefined
  }
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ssl=14&ssc=11&pln=14&pc=19#code/DYUwLgBGD2DWIDsBcEDOYBOBLBBzCAPhAK4IAmIAZjiGRALwnlU1kDcAUF2dBAN4cIEAMbQE6CBhCoADmNQgGEYFnQB5AEYArEMLCoAygE8EwgBQChQmPGRQ4iQRAC+ASic3ESqbPkgAdJ4InM4QAO4AFligEGZBEACEjAjEwMDuXGYAhqgmwrGuDAB8-E48pVYi8pA+cuKKjFlhWViQKurauvoAgrmmFk6VAPRDQgB6E5MTECAYGNAYqBAAtBAA5LV+axBYALYyKsKtwEYQETlQRjKKa1kIRtsaulnECjuQPNIQCNCQ5wBuiiyl2uEDuPzAWTAWDEYPIOyWUkos0QwloEDIWCkehOEAWO3IWK6uJw7yW0DCCAJrSwWRUAC9Zv5BlYgiggiy3Cz4oxNvVAg5gk5QpFooo4oLEslUukOG4zBkOJRSHoYVT2mBNDo9IY8mYZFkMFldqgUHx7LYUOhsHhCEwKNQEOi3GaLYgrZgcPgiKQHawXBUquJoKB-MBoLh9YbjahXJwhFIwMQMFTLKzBShfSwnWRhXKuDk8hBlaZobCNVquqhenqDUaTa62WhPbafcxHc7XCgAArzXaqEAAHnNTetXrtWY7dGcJTTomDofDkbrMbjTkTydT3Iz9uztDzziAA)

**Expected behavior:**
Typescript should be able to infer the type of the response variable

**Actual behavior:**
Typescript cannot infer the type due to a circular reference. It's unclear what the circular reference is.

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is a real circularity because the `while` test can narrow `token` which in turn could cause `listObjectsAsync` to have a different result type
