### ISSUE TITLE
Generics interface conditional type

### ISSUE THREAD

**Issue by mokeyish** [microsoft/TypeScript#40104]
## Search Terms

Generics conditional type

## Suggestion

```ts
interface Array<T> { 
     // allow for all type
     some(callbackfn: (value: T, index: number, array: T[]) => unknown, thisArg?: any): boolean;
}

interface  Array<T when T is number> {
    // only when `T` is number
    sum(): number;
    avg(): number;
    max(): number;
    min(): number;
}
```

## Use Cases

```ts
const a = ['a', 'c', 'd'];
// a.sum()   // not allowed

const b = [1, 2, 5];
const c = b.sum(); // ok
console.log(c); // 8
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
What about `Array<string  | number>`?

**Comment by mokeyish** [comment]
> What about `Array<string | number>`?

I write some  extension methods for `Array`, but it is not work as expectedly.

<img width="750" alt="图片" src="https://user-images.githubusercontent.com/16131917/90484217-77254100-e168-11ea-966f-06ff20a4c263.png">

**Comment by mokeyish** [comment]
Currently ,  interface declarations with the same qualified name, it `Declaration Merging`

https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#7.2

**Comment by MartinJohns** [comment]
Please note that the spec is **completely outdated and abandoned**.

**Comment by RyanCavanaugh** [comment]
You can already do this today; no new syntax is necessary:
```ts
interface  Array<T > {
    sum(this: Array<number>): number;
}

declare const a: string[];
a.sum(); // Error
declare const b: number[];
b.sum(); // OK
```

**Comment by mokeyish** [comment]
@RyanCavanaugh Thanks!😁
<img width="695" alt="图片" src="https://user-images.githubusercontent.com/16131917/90697324-bc548a80-e2b0-11ea-8e9f-b940f33d4b20.png">
