### ISSUE TITLE
Folding destructing object

### ISSUE THREAD

**Issue by Esporia** [microsoft/TypeScript#40103]
My feature request is the possibility to fold destructing object with left arrow located in the gutter.
For example, to reduce that to one single wrapped line.  

````jsx
const { 
parent_selector,
height, 
width,
container_background_color,
font_size,
margin_horizontal_text,
on_click } = props;
````

to 

````jsx
const { ⋯ } = props;
````

**Comment by mjbvz** [comment]
Seems fixed for me in VS Code 1.49 (the insiders build) which uses TypeScript 4.0 (possibly by #31303)

Note that this is how the folding looks: 

<img width="403" alt="Screen Shot 2020-08-17 at 5 37 42 PM" src="https://user-images.githubusercontent.com/12821956/90457448-674a2600-e0b0-11ea-8490-1a119446f56f.png">
