### ISSUE TITLE
VS2015RTM: Property 'write' does not exist on type 'Document | Window'

### ISSUE THREAD

**Issue by AlexMaroz** [Microsoft/TypeScript#4012]
Hi,

I have a web project where I using TypeScript.
When I used VS2015 Preview everything was OK. But when I've upgraded to RTM then I got error message:

> Property 'write' does not exist on type 'Document | Window'

This issue simple to reproduce with code below:
```javascript
var newDoc = document.open("text/html", "replace");
newDoc.write('test');
```
TypeScript [playground](http://www.typescriptlang.org/Playground) also shows the error.

Thanks

**Comment by mhegazy** [comment]
@zhengbli can you take a look

**Comment by zhengbli** [comment]
The spec says ``(Document or Window)`` on the return type of ``Document.open``, but I found on Edge, IE, Chrome and Firefox it is always of type ``Document``, so I guess it is safe to change it back.
