### ISSUE TITLE
After combining multiple types, how to access the properties as optional properties?

### ISSUE THREAD

**Issue by JYC-99** [microsoft/TypeScript#40128]
**TypeScript Version:**  3.9.2

**Search Terms:**

**Expected behavior:**
```ts
obj.doSomethingA?.();

obj.doSomethingA ? obj.doSomethingA() : null;
```
Should work. 

**Actual behavior:**

End up with error:
```
Property 'doSomethingA' does not exist on type 'TMyInterface'.
  Property 'doSomethingA' does not exist on type 'IInterfaceB'.
```
I have to use type casting to work around.

**Related Issues:**

**Code**
```ts
interface IInterfaceA {
    doSomethingA(): void;
}

interface IInterfaceB {
    doSomethingB(): void;
}

type TMyInterface = IInterfaceA | IInterfaceB;

const gen = (): TMyInterface => {
    if (Math.random() > 0.5) {
        return {
            doSomethingA: () => {}
        };
    }

    return {
        doSomethingB: () => {}
    }
}

const obj = gen();

obj.doSomethingA?.();

obj.doSomethingA ? obj.doSomethingA() : null;
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var _a;
const gen = () => {
    if (Math.random() > 0.5) {
        return {
            doSomethingA: () => { }
        };
    }
    return {
        doSomethingB: () => { }
    };
};
const obj = gen();
(_a = obj.doSomethingA) === null || _a === void 0 ? void 0 : _a.call(obj);
obj.doSomethingA ? obj.doSomethingA() : null;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJKvNeSCCyDeAUMicgCYD2AyhQLYRgAWoA5jgBQCUAXMgG4VgZANyEAvoUKhIsRCnSZZSAEIFipSjXpNWyrrwFDREwmACeABxQAVALJmMM7CgC8aR1jl4APu8XPlUUIEChAAZzBkFggQZDd9ZDsHfzk4gD41UmRgGGR2WzgmADooOBBKWi5kDIAGIoBWTkys0igGAFcoWKIW3vJqOgZmEDZeKpcM-Ak+5DFRLJMstrBO7vVezUGdEeUxpomCadIJExDwyIoAIwArOKiYriCr66LN7WG2AH4ix8ln14G71YeE+yH+byGwKqvBA7QANnDhEA)

**Comment by jcalz** [comment]
This is not a forum for asking TS questions; it's for reporting bugs or requesting features.  And when you report bugs or request features, you are expected to search existing GitHub issues to see if it has been raised before.
