### ISSUE TITLE
1.5 does not contain the Intl.DateTimeFormat fix (#3281)

### ISSUE THREAD

**Issue by cveld** [Microsoft/TypeScript#4013]
In 1.5 lib.d.js is still reading:
var DateTimeFormat: {
        new (locales?: string[], options?: DateTimeFormatOptions): Collator;
        new (locale?: string, options?: DateTimeFormatOptions): Collator;
        (locales?: string[], options?: DateTimeFormatOptions): Collator;
        (locale?: string, options?: DateTimeFormatOptions): Collator;
        supportedLocalesOf(locales: string[], options?: DateTimeFormatOptions): string[];
        supportedLocalesOf(locale: string, options?: DateTimeFormatOptions): string[];
    }
}
Apparently fix 3281 (https://github.com/Microsoft/TypeScript/pull/3281) has not been processed towards the latest and gratest 1.5 yet. How can I track this (github basic question)? 

How do I proceed? (TypeScript Visual Studio question)
I can change the lib.d.js on the file system directly, but how can I process this change towards my team members?
Path:
D:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript
But I also see the following path:
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5

So I have a lib.d.ts living on multiple places. Is that something that will be refactored in the near feature?

Good to know: the design-time errors can be fixed by editing the Visual Studio related file, whereas the errors during build can be fixed by editing the SDK related file.

Additionally, the definition for the interface needs to be fixed:
interface DateTimeFormat {
        format(date: number): string;
        resolvedOptions(): ResolvedDateTimeFormatOptions;
    }
Must be:
interface DateTimeFormat {
        format(date: _any_): string;   // or some multi-type syntax that I am currently unaware of
        resolvedOptions(): ResolvedDateTimeFormatOptions;
    }

**Comment by mhegazy** [comment]
The fix will be in next release, you can try the nightly build: `npm install typescript@next`

**Comment by mhegazy** [comment]
> How do I proceed? (TypeScript Visual Studio question)

you can include a custom copy of the library with `--nolib`; you will need to include your custom version of the library in your project, VS and command-line build should honor it.
