### ISSUE TITLE
Use MIT license

### ISSUE THREAD

**Issue by kryptine** [microsoft/TypeScript#40131]
## Search Terms

license, MIT

## Suggestion
Change the license of this repository to the MIT license

## Use Cases

The MIT license is simpler and reduces legal problems relating to [license compatibility](https://github.com/twbs/bootstrap/issues/2054) as well as [patents](https://github.com/dotnet/fsharp/issues/1727)

## Examples

Not applicable.

## Checklist

This is not a technical change so obviously all of these apply.

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
The Apache-2.0 license was chosen as it's already a very liberal license. It's very common throughout the open-source ecosystem. To date, we haven't received any feedback from any other organization that the license is a major problem or a blocker. So at this point in the project's lifetime, we believe migrating to a different license would be too disruptive, and would provide very little benefit.
