### ISSUE TITLE
TS 4.1 should support `require` with nested binding patterns

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#40143]
prettier uses nested binding patterns to import multiple things from "namespaces":

**Code**

```js
const {
  builders: {
    concat,
    join
  },
  utils: {
    nub,
    intercalate
  }
} = require('../document')
```

(Identifier names have been changed to make fun of Haskell.)

**Expected behavior:**

`nub :: Eq a => [a] -> [a]`

**Actual behavior:**

error "Module '../document' has no exported member 'nub'.", and `nub: any`. 

This worked before switching `const x = require` to create real aliases, and needs to work afterwards.

**Comment by sandersn** [comment]
Update from surveying user tests for this pattern:

1. Prettier uses it in 21 places, all from document.js. Maybe they're treating it like an index.js?
2. Eslint and discord use it once each.
3. Webpack has 2 tests that use it.

I'm still running my survey on js files from DefinitelyTyped. It's a lot slower than grep since I'm using naive AST-walking search.

**Comment by sandersn** [comment]
We can re-open this if prettier wants it, or if somebody else starts using this pattern (they shouldn't, it's a bad idea).

**Comment by brodybits** [comment]
Hi @sandersn please see this PR: https://github.com/prettier/prettier/pull/9207

Unfortunately I had to apply some ugly workaround hacks to get Prettier's typecheck to work with typescript `4.1.0-dev.20200915`. I think this is not something we want to apply unless absolutely necessary.

I suspect that this would be a very small corner case, maybe needs a new issue?

**Comment by sandersn** [comment]
Yep, looks like a separate bug from this one -- and hopefully a minor one -- so I filed #40578 to track it. Thanks for checking this out!
