### ISSUE TITLE
[VS2015] text editor "tabs" option always behaves "smart"

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#4014]
In VS2015, I can change the "tab" text editor options for TypeScript (none/block/smart) but the editor always behaves like it's set in `smart` mode. 

I tried restoring the default settings, but didn't worked. It's stuck in smart mode. 

Example
```
   function foo() 
   {
A  B  C
```
hitting `return` right after the curly brace should move caret to:
- A when "none"
- B when "block"
- C when "smart"

In this issue, Visual Studio always moves to C

**Comment by paulvanbrenk** [comment]
We should take the IndentStyle into account in the `TypeScriptIndentationService`.

**Comment by paulvanbrenk** [comment]
This is fixed in the next public release of TypeScript.

**Comment by nippur72** [comment]
is this supposed to show in nightly builds? 

I'm using `1.7.0-dev.20151016` but the bug it's still there.

**Comment by paulvanbrenk** [comment]
No, this required changes in the Visual Studio components.

**Comment by nippur72** [comment]
I've just installed VS2015 update 1, finally getting rid of this annoying bug. Thanks! :smile:
