### ISSUE TITLE
lib.webworker.d.ts refers to types not defined

### ISSUE THREAD

**Issue by nwolverson** [Microsoft/TypeScript#4015]
`lib.webworker.d.ts` seems to refer to some types not defined in either that file or `lib.core.d.ts`: `EventInit`, `UIEvent`, `MSAppAsyncOperation`, `MSExecAtPriorityFunctionCallback`, `XMLHttpRequestUpload`, `Node`, `NodeList`, `Position`, `PositionError`, `MediaQueryList`, `MutationRecord`, `MutationObserver`, `AudioBuffer`.

It would seem that some of those types shouldn't be there, while others (`EventInit`) should be available.

**Comment by Gitgiddy** [comment]
Node.d.ts, which doesn't assume a windowed environment, needs types `Uint8Array`, `Uint16Array`, `Uint32Array`, `ArrayBuffer`, `DataView`, `Float32Array`, `Float64Array`, `Int16Array`, `Int32Array`, `Int8Array`, and `Intl` which are in lib.d.ts but not lib.core.d.ts.  I propose that these types be moved to the core.  

`console`/`Console` is also required by Node, but it should maybe not be moved as it isn't available in all environments or might conflict with some different `console` mechanism with its own signature in some non-standard javascript environment.
