### ISSUE TITLE
"Output Generated Successfully" on file with errors

### ISSUE THREAD

**Issue by Anupheaus** [Microsoft/TypeScript#4016]
Using v1.5 in VS 2013, TypeScript now tells me that it has compiled any .ts file successfully, even if there is an error in it.  However, even though it says it generated the output successfully, it doesn't actually change the compiled .js file if there is an error.  Put simply:
Save file with error -> "Output Generated Successfully" -> no change to .js file
Save file without error -> "Output Generated Successfully" -> changes .js file

Whilst this is an issue, it doesn't actually affect us too much since it also starts underlining and reporting the errors in the Error List, but it should still be fixed.

**Comment by danquirk** [comment]
The message should certainly reflect what's actually happening.

**Comment by mhegazy** [comment]
@Anupheaus i a can not reproduce this locally. i get the correct message when saving. are you seeing this behavior on a vanilla project? or is it a specific project?

**Comment by Anupheaus** [comment]
@mhegazy Both myself and my colleague have this issue, on very different machines, but it is with the same project and both of us are using VS2013.  Neither of us have another project to test it on but if I get chance this afternoon I will create a new project with an error and see if the issue occurs on other projects.

**Comment by mhegazy** [comment]
thanks @Anupheaus, appreciate the help!

**Comment by mhegazy** [comment]
@Anupheaus is this still an issue with 1.6 release?

**Comment by mhegazy** [comment]
Closing. please reopen if it is still an issue.
