### ISSUE TITLE
Will language service getEmitOutput always return map before JS?

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#4018]
We've just added support for using Babel as an alternate transpiler in atom-typescript (mostly to work around https://github.com/Microsoft/TypeScript/issues/3915 , and if any other similar issues crop up).

The feature includes support for doubly-mapped source maps.  This functionality relies on the language service returning the `.js.map` file *before* the corresponding `.js` file when `getEmitOutput(fileName)` is called.  [See here](https://github.com/TypeStrong/atom-typescript/blob/9c7621bcd7c9d38fd2e255845f476bdf3ef63d27/lib/main/lang/modules/building.ts#L46-L59).

**Is this sequencing guaranteed?**

Many thanks!

//cc: @mhegazy

**Comment by mhegazy** [comment]
no. :) this is not not something you can take a dependency on. this can change.

**Comment by nycdotnet** [comment]
OK, thanks.  We'll make sure that our build component is robust enough to handle that.  Thanks!
