### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by skiv71** [microsoft/TypeScript#40187]
## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Make console class colour as per reserved (blue on monokai) - please

**Comment by RyanCavanaugh** [comment]
> Make console class colour as per reserved (blue on monokai) - please

Blue is for keywords, but `console` is not a keyword. For example, it's legal to write
```ts
function f(console) {
```
but not
```ts
function f(let) {
```

We don't make exceptions for this.
