### ISSUE TITLE
Importing html template with 1.5

### ISSUE THREAD

**Issue by mjw56** [Microsoft/TypeScript#4019]
Hi, I would like to be able to import an html file. However when I try this doing something like:

```js
import template from './home.html';
```

I get ```Cannt find module './home.html'```

Is there any way to do this currently in 1.5?

**Comment by mjw56** [comment]
Closing as it's being discussed here https://github.com/Microsoft/TypeScript/issues/2709

**Comment by harryjubb** [comment]
https://github.com/systemjs/plugin-text

    import template from 'app/index/index.template.html!text';

Works for me.
