### ISSUE TITLE
Mapped types only sometimes know when a property key is optional

### ISSUE THREAD

**Issue by gustavderdrache** [microsoft/TypeScript#40190]
**TypeScript Version:**  4.1.0-dev.20200821

**Search Terms:**
- mapped type undefined
- conditional type undefined
- conditional type strictNullChecks
- mapped type strictNullChecks
- keyof optional

**Expected behavior:**

Given the following interface:

```ts
interface Interface {
  foo: number;
  bar?: string;
  baz: boolean | undefined;
}
```

These two mapped types should be identical:

```ts
type M1 = { [K in keyof Interface]: Interface[K] };

type Keys = keyof Interface;
type M2 = { [K in Keys]: Interface[K] };
```

However, we have `bar?: string: undefined` in `M1`, and `bar: string | undefined` in `M2`. This causes issues with more sophisticated mapped types, as when the compiler knows you're mapping over `keyof T`, then it will inject `undefined` only when the key is optional.

The tension (and possibly the bug) is that this makes some seemingly equivalent expressions have different behavior: the type `Pick<T, 'key'>` will preserve the optionality of `'key'`, but the manual expansion of the definition won't. In the below example, `bar` is optional in `P1`, but not in `P2`.

```ts
type P1 = Pick<Interface, 'bar'>;
type P2 = { [K in 'bar']: Interface[K] };
```

Ultimately, I would expect the two to behave similarly, as it gives a much cleaner intuition to mapped types, which is how I originally was searching for this bug (hence the keywords referring more to conditional and mapped types instead of optional properties).

Consider the type below:

```ts
type N1 = { [K in keyof Interface]: never }[keyof Interface];
```

The type `N1` is `undefined` because of the property `bar`: since the property is optional, we can't know if it exists (and thus we have to surface the underlying JS behavior of yielding `undefined`). On the other hand, `baz` is mapped to `never` since the property is required to exist (but its value may be `undefined`).

Thus, the expansion is `/* foo */ never | /* bar? */ (never | undefined) | /* baz */ never = undefined`. 

If we indirect over the `Keys` alias, we get `never` back. The expansion should still be the same, but the since the optionality of `bar` is lost, we instead expand `T['bar']: never` to `never`.

```ts
type N2 = { [K in Keys]: never }[keyof Interface];
```

**Related Issues:**
- #34992

**Code**
```ts
interface Interface {
  foo: number;
  bar?: string;
  baz: boolean | undefined;
}

type M1 = { [K in keyof Interface]: Interface[K] };

type Keys = keyof Interface;
type M2 = { [K in Keys]: Interface[K] };

type N1 = { [K in keyof Interface]: never }[keyof Interface];
type N2 = { [K in Keys]: never }[keyof Interface];
```

<details><summary><b>Output</b></summary>

```ts
"use strict";

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200821#code/JYOwLgpgTgZghgYwgAgJLmvJyDeAoZZGAe2IC5kQBXAWwCNoBuA5OuKAfgoGcwpQA5s0JsAXhTqkANhDghkAH2RUQAEwgxQEVcwC+ePGACeABxQBZAIzIAvLmQBtANLJQyANYQjxGGgyxECABdCnRIAKRnIORdZkNTFCcvblsPLx8-cKwIZmMzZHMAJlScRxc3JKNuEMzMQKiYuLyUADlrO1LnV3lPb18wuqQakAgAN2gYh16MgYjg3ITkFuKOsu7kSuqKEfGoSen+-2ygxiA)

**Comment by DanielRosenwasser** [comment]
When we can tell that a mapped type is "homomorphic" on properties of some other type, we are able to preserve those properties' modifiers in the output. When you remove the direct usage of `Interface`'s from the mapped type in `M1`, we've lost the connection and all we see is `"foo" | "bar" | "baz"`.

**Comment by gustavderdrache** [comment]
I guess I'm not sure where the distinction lies - you can get the compiler to recognize that `"foo" | "bar" | "baz"` is `keyof Interface` when using `K extends keyof T` (indeed, `Pick<Interface, "bar">` comes back with `{ bar?: string }`). It seems strange (to me, at least) that the compiler only recognizes the specific `keyof T` syntax as a sign it should check the optionality of T's properties, but not for seemingly equivalent constructions.

**Comment by DanielRosenwasser** [comment]
I agree that it can be a little surprising at times, but we chose this behavior over several different kinds of mapped types or mapped type modifiers. @ahejlsberg may remember better when we expanded the rule-set to also recognize constraints.
