### ISSUE TITLE
Check 'imports' are relative and end with '.js' (no rewrite)

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#40207]
I know that it was discussed a lot of times, that Typescript should rewrite 'imports' so they are relative.
I also understand that this is not planed to do.

But would it be possible to introduce a compiler switch, wich could turn the compiler to throw a error when a non relative import is used?

So I can decide to create a ES6 Library wich can directly be used in a Frontend Project without using a Bundler?

**Comment by AlCalzone** [comment]
https://www.npmjs.com/package/eslint-plugin-import could help with that:
> Forbid import of modules using absolute paths (no-absolute-path)

**Comment by RyanCavanaugh** [comment]
Already nonrelative paths aren't going to work unless something special has been set up or explicitly predefined, and writing an absolute path seems very unlikely to happen accidently.

This seems like something in the domain of a linter if you want to get more specific than that (e.g. enforcing .js file extension be present)
