### ISSUE TITLE
Mapped type with keys in keyof enum-type differs when using parentheses

### ISSUE THREAD

**Issue by hwanders** [microsoft/TypeScript#40206]
**TypeScript Version:**  4.0.2

**Search Terms:** mapped type "in keyof" keyof enum index parentheses associativity (several combinations)

**Code**

```ts
enum MyEnum { A, B }
type EnumType = typeof MyEnum;

// "A" | "B"
type EnumKeys = keyof EnumType;

// good: { A: boolean; B: boolean; }
type UsingEnumKeys = { [K in EnumKeys]: boolean };

// let's inline the EnumKeys
// good: { A: boolean; B: boolean; }
type InliningEnumKeysWithParens = { [K in (keyof EnumType)]: boolean };

// now let's remove just the parentheses around "keyof EnumType"
// bad, unexpected: { [x: number]: boolean; readonly A: boolean; readonly B: boolean; }
type InliningEnumKeysWithoutParens = { [K in keyof EnumType]: boolean };
```

**Expected behavior:** Hover type of `InliningEnumKeysWithoutParens` should be the same as `InliningEnumKeysWithParens` - just `{ A: boolean; B: boolean; }`

**Actual behavior:** Hover type of `InliningEnumKeysWithoutParens` contains `[x: number]: boolean`, furthermore `A` and `B` are `readonly`

**Related:** Perhaps #40190 (another observation of different behavior when inlining `keyof X` after `in` without parentheses)

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.2#code/KYOwrgtgBAsgngUXNA3lAggGigISgXwCgAXOAB2CiUgBVzKBeKUigewDNZFkBuQwgPQCoAInQioAH1E4RJelWQBpYHADOUJgGtVHRbXp9BwgOatWAEwBcUNOhsAjcwBtgAQxA9cjl+88F5CigAVTUASxATaggVdU1bKABtJSgI-RjVNQBdH1ZXDwIjIShXYgByDQjnCMpiAAtKaNi1YygzSxs7XPz-HG6-LyIWSgBJEGqQCKjlTIB1MPqABTcAJ1ANJjRk1JAoAAodOD1ougoAShyoJzy-Qv5ikFYAdxLgco01iFYAN0oAKzAamIzAaUDIq1A9WAamhUFWrDAIAsokOx2Qp2AcmKDjcFmwiOAAA8KABjYjAawJRKEmzIBzAFaXa49LxrXGscZwDD9Dys9wWDnOLl9K6+XkBYZQMYTKZNOYLOoI4jLNYgDZUlJpVGcE70Jli3b4IrCAC0ZvNZvuwhGwKerBWWg07BqUHY9qgrAcf2AZOY9BaJI5QI9XviaDcNgAjNgHFAbAAmO6SgDyXp9xAx8WGek9f2NojcEmkIgcchTabJzXi2qgqe9ZIx+falPDPP8Djbg0Co3GESmdfTzXmSwharDSU1uwOuk4A4b9AubburWbnThnauG6GCmlfcic+IQ4VSpV63H2y1M9rFYzeqXRsIQA

**Comment by ahejlsberg** [comment]
This is working as intended, but merits a bit of explanation. When the `keyof` type operator is applied to a non-generic type (such as `EnumType` above), it is resolved to a literal type or a union of literal types. This resolved type has no "memory" of the fact that it originated in a `keyof` type operator. Rather, it is indistinguishable from the literal type or union of literal types written out explicitly. So, technically, in the example above there is no difference between `keyof EnumType` and `"A" | "B"`. However, there is a difference in a mapped type. When the `in` keyword is immediately followed by `keyof` and some type, the mapped type is _homomorphic_ with respect to that type (i.e. it copies property modifiers from that type). However, this doesn't occur if there are parentheses around the `keyof` type or an indirection through a type alias. You could argue we should permit parentheses, but what about other typing constructs such as unions or intersections? At some point the "memory" of where the keys came from has to disappear. I think our current behavior is reasonable, and I'm not eager to take a breaking to change to modify it slightly.
