### ISSUE TITLE
Conversion of Partial<T> to T loses "optional"ness of properties

### ISSUE THREAD

**Issue by orgads** [microsoft/TypeScript#40216]
**TypeScript Version:**  4.1.0-dev.20200824

**Search Terms:** Partial optional

**Code**

```ts
function partialToFull<T>(x: Partial<T>): T { return x as T; }

interface Foo {
  bar?: string;
};

const foo: Foo = { bar: 'baz' };
const full = partialToFull(foo);
delete full.bar; // error TS2790: The operand of a 'delete' operator must be optional.
```

**Expected behavior:**
It should work, as the property is optional.

**Actual behavior:**
It fails.

If I explicitly assign the type to full, it works:
```ts
const full: Foo = partialToFull(foo);
```

**Playground Link:** [Link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABABwIYCdaoDYBU4BiI22APLgHwAUAHgFyIAKGWZlAlA7ogN6LoBTKCHRIaiVAGdEuANyIAvgCglMMFAHpgqCAMQE4cXksSIARhgD8DSVHRqA5rKULnSiAluJghhgaMAvLzmGAwA5BYAXmGKzh5gXqAkiEFomDA4+EQkVD5w7M4AJgLYQnpJ2AB0FujOQA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/13783

**Comment by RyanCavanaugh** [comment]
I'm not sure why this is the "expected" behavior -- the entire point of the `partialToFull` type signature is to erase optionality; that's what it's written to do.

**Comment by orgads** [comment]
Why? It returns T, and the type I sent it is Foo.

My use-case is deepmerge, which accepts 2 objects (possibly of the same type), and returns a merged object. I'd expect it to maintain optionality.

**Comment by RyanCavanaugh** [comment]
It *accepts* a `Partial<T>` and returns a `T`.

You gave it a `Partial<{ foo: string }>` and it returned a `{ foo: string }`.

That's what inference is supposed to do.

**Comment by orgads** [comment]
I see. Thanks for the explanation.
