### ISSUE TITLE
URLSearchParams constructor type should accept Record<string, string | number | boolean>

### ISSUE THREAD

**Issue by 3dos** [microsoft/TypeScript#40214]
**TypeScript Version:**  4.0.2

**Search Terms:** URLSearchParams

**Code**

```ts
const a = new URLSearchParams({ number: 42, flip: true }).toString()
```

**Expected behavior:** no compile time error

**Actual behavior:** `Record<string, string>` seems too strict

**Playground Link:** https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0cQAXkGkAkj1exA8ZA0tEcDEQggAFABvQbsRDSH75UAAFgATPxktAqBLUGR2CgAL4ASgC6GIytGfI1wRUOAa7K8iHgAwYIPYNG+bjMzHYDGYkH4sAVsES1vgehEXgARABRVY8mr6ANJHEB8AOVAAcmEADkmQGgioAPLfMi7QRurSQY6oRwKVzSPCgJwWnSjLD6FAIRAw4RXe0SS3REQGDg47osNhcbhBEpAA

**Related Issues:** none

**Comment by RyanCavanaugh** [comment]
The spec is pretty clear that this takes strings and other values are being coerced:
```

[Exposed=(Window,Worker)]
interface URLSearchParams {
  constructor(optional (sequence<sequence<USVString>> or record<USVString, USVString> or USVString) init = "");
```
