### ISSUE TITLE
v4 regression: weird type inference inside of `Array.every` when using `pipe`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#40217]
**TypeScript Version:**  4.0.2

**Search Terms:**

**Code**

```ts
declare function pipeWith<A, B>(a: A, ab: (a: A) => B): B;

interface None {
    readonly _tag: 'None';
}
interface Some<A> {
    readonly _tag: 'Some';
    readonly value: A;
}
type Option<A> = None | Some<A>;

declare const getOrElse: <A>(onNone: () => A) => (ma: Option<A>) => A;

declare const myOption: Option<boolean>;

[].map(() =>
    pipeWith(
        // no error ❌
        myOption,
        getOrElse(() => true),
    ),
);

[].every(() =>
    pipeWith(
        // error! ✅
        myOption,
        getOrElse(() => true),
    ),
);
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by j-oliveras** [comment]
As a reference, some other issues about Array.every with TS 4: #40157, #40184 (first part).

**Comment by jakebailey** [comment]
This works as of 4.7: [Playground Link](https://www.typescriptlang.org/play?ts=4.7.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcsCQB1LDACwB4BBAGngCEA+ACigC54H4oAjbh260AlPAC8LZqO5MA3AChFWVBhAxEUMAgByeBAG9F8U-DhRgeCAE94AfQxQA5twDk+1CDdKAvirUNLR14AGUcAFsQOmljM3MQS2s7Rxd3cKifEzMLK1RbeAA3KAhkEBE-RQwbEngAeQJsPBjJeE8EAB8wyOjaFiVFUEhYBDA8AGcMeGcQDDqYAFEIcfL4GLY8dqFxKR4d6TYIrnrG3FQY-Z4Boeg4eDHUSfgImwam1G43s+p+HBwIRKofrKADaAF0AHRHAhsNj7bKmIgkchUNgI+LwAD0mPgqBw8A0MBwMHggBlydHxF5fPD0ClmGZzRbLECwy4YGBlUS0+JcxSiAbgiEgQoaGysyQsdFIsgUShojFmbEEmBEmAAQnggFByOmmKmnGk66azeZLFbi3bszncsy8-lAA)
