### ISSUE TITLE
Typescript auto-import put comma in wrong position

### ISSUE THREAD

**Issue by chengB12** [microsoft/TypeScript#40219]
**TypeScript Version:**  4.1.0-dev.20200823
**Visual Studio Code Version:** 1.48.1

**Search Terms:** import comma

**Code**

```ts
import { Foo1,
   Foo2, Foo3,
   Foo4, Foo5,
} from 'foo'

export default {
     foo6: {} as Foo6
}
```

**Expected behavior:**
When prompted  Quick Fix  => click "Add 'Foo6' to existing import declaration 'foo', and click auto-import
The import declaration shall be 
```ts
import { Foo1,
   Foo2, Foo3,
   Foo4, Foo5, Foo6,
} from 'foo'

```
**Actual behavior:**
```ts
import { Foo1,
   Foo2, Foo3,
   Foo4, Foo5,, Foo6
} from 'foo'

```
![image](https://user-images.githubusercontent.com/66152032/91065158-0016ff00-e5e5-11ea-84a0-7e55d518f698.png)
![image](https://user-images.githubusercontent.com/66152032/91065213-0e651b00-e5e5-11ea-918e-0af9edbc668a.png)

**Comment by chengB12** [comment]
This is can be reproduced when new imported is last thing in that line, when '} from 'foo' is on newline

**Comment by j-oliveras** [comment]
Duplicated/related to #39717?

**Comment by chengB12** [comment]
> Duplicated/related to #39717?

Yes, it looks duplicate, I think because I searched for open issues, and that issue was closed, so I missed that.

And previous closed because can't reproduce, I find a way to reproduce

**Comment by andrewbranch** [comment]
I don’t know what to tell you 😐 

![Kapture 2020-08-25 at 16 46 32](https://user-images.githubusercontent.com/3277153/91238725-91c06280-e6f2-11ea-953e-0b6b76f6f4a3.gif)

**Comment by chengB12** [comment]
well, I can conform ts 4.1.0-dev.20200824, vs code 1.48.2 still has this issue

**Comment by chengB12** [comment]
I reproduced it with 11 imports:
```ts
import {
    Foo1, Foo2,
    Foo3,
    Foo4,
    Foo5,
    Foo6,
    Foo7,
    Foo8,
    Foo9,
    Foo10,, Foo11
} from './foo'

export default {
    foo1: 1 as Foo1,
    foo2: 2 as Foo2,
    foo11: 11 as Foo11,
}

```

**Comment by chengB12** [comment]
before 
![image](https://user-images.githubusercontent.com/66152032/91239654-07c5c900-e6f5-11ea-9277-2a78b2dfdb5a.png)
after
![image](https://user-images.githubusercontent.com/66152032/91239672-1318f480-e6f5-11ea-80e3-ee89821bf2ed.png)

**Comment by andrewbranch** [comment]
Ok, that one repros for me. Thanks @chengB12
