### ISSUE TITLE
'void' parameters treated as optional only for calls, but not for assignability.

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#40227]
**TypeScript Version:**  4.0.2

**Search Terms:** signature void parameter optional assignability

**Code**

```ts
declare function f(a: number, b?: void): void;
declare function g(a: number, b: void): void;
f(1); // ok
g(1); // ok

let ff: (a: number) => void = f; // ok
let gg: (a: number) => void = g; // error
```

**Expected behavior:**

`g` should be assignable to `gg` since we treat `void` parameters as optional.

**Actual behavior:**

`g` is not assignable to `gg`.

**Playground Link:** [link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIAooAueVZAWwCMQYAaeKgflIDcctgBKNj4AbgBQoSLAQp02PPADmRUuWq0GVXpx7x2nIYgIBGLv3gB6Y-BwBrQXINHT5q4IggMSRKXllKNGF3gBeAD5NPgCkIWdXGRkPEi8lXwDgrWAwmX4gA)

**Related Issues:** #39817, #29131

**Comment by ExE-Boss** [comment]
Also **Related Issues:** <https://github.com/microsoft/TypeScript/issues/29131>
