### ISSUE TITLE
tsc command won't work

### ISSUE THREAD

**Issue by ReactHTMLCSS** [microsoft/TypeScript#40225]
I recently installed typescript globally and I used tsc to check the version of typescript i'm using. Whenever I use tsc, it always shows an error message and I don't know what to do.Please fix this bug as im waiting to make a new app with typescript

**Comment by RyanCavanaugh** [comment]
This sounds more like a misconfiguration problem than a TypeScript bug. If you could post the error message, a community member may be able to help out, but tsc is not broken in general and there's nothing we can do on our side to diagnose the problem without more concrete information. Thanks!
