### ISSUE TITLE
JSDocs @typedef parsing runs into infinite loop

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/TypeScript#40234]
**TypeScript Version:**  v4.1.0-dev.20200824

**Search Terms:**

**Code**

TS:

```ts
export type XMLObject<T> = {
  $A: {
    [K in keyof T]?: XMLObject<T[K]>[]
  },
  $O: {
    [K in keyof T]?: {
      $$?: Record<string, string>
    } & (T[K] extends string ? {$:string} : XMLObject<T[K]>)
  },
  $$?: Record<string, string>,
  } & {
  [K in keyof T]?: (
    T[K] extends string ? string
      : XMLObject<T[K]>
  )
};

const p:XMLObject<{foo:string}> = {};

```

JS:

```js
/**
 * @template T
 * @typedef {{
  $A: {
    [K in keyof T]?: XMLObject<T[K]>[]
  },
  $O: {
    [K in keyof T]?: {
      $$?: Record<string, string>
    } & (T[K] extends string ? {$:string} : XMLObject<T[K]>)
  },
  $$?: Record<string, string>,
  } & {
  [K in keyof T]?: (
    T[K] extends string ? string
      : XMLObject<T[K]>
  )
}} XMLObject<T> */

/** @type {XMLObject<{foo:string}>} */
const p = {};
```

**Expected behavior:**

VSCode Intellisense outputs should match and results should somewhat as fast in JS as in TS.

**Actual behavior:**

Extremely long parsing time, Intellisense mismatch and long, infinitely looping type details. Hovering over `XMLObject` in the playground link takes a very long time on JS.

JS: ![loop example](https://user-images.githubusercontent.com/9271155/91117249-262bb600-e65c-11ea-9e48-9aad253eba7c.png)

TS: 
![loop example2](https://user-images.githubusercontent.com/9271155/91117286-3ba0e000-e65c-11ea-9211-5a7cc585550b.png)

**Playground Link:**

JS: https://www.typescriptlang.org/play?ts=4.1.0-dev.20200824&useJavaScript=true#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUowICeqiAJogGaQDeNUkAJAIIBctDkkA2gNKQBLAHaQA1oiIB7argC6AfnYANALIAZAPIAjAFaIAxvAA8uPrIB83WQwC+AGgaMN7ely59BI8VJkKXnN0ZGRUgAJQNJACcyIwBneEjhAHM7SHjEoSTzAJtIADJIAApTXllIRAAPJCEyWLSE5Mh5WkZWdOTc5XVtPUMTM3MASlsHLiCQ8P0omPbM1Nms0chcgtcefmExCWk8PyKAkrLK6tr6jKSms+SAri7NXQNjQ+yuYZtc1Xvep-NoYHBwKBCPASIhaJ8eo8jDRKJJJG0GpkbOZciB-lMhPFIKhIABeWg2ADc4CAA

TS: https://www.typescriptlang.org/play?ts=4.1.0-dev.20200824#code/KYDwDg9gTgLgBDAnmYcAaBZAMgeQEYBWwAxjADwAqAfHALxwDeAUHHACQCCAXIy63AG0A0nACWAOzgBrYIggAzOBQC6Afh6ZchEuQrDlVAcr4BfADR82OHs36CRE6bIVK1NvnbZt1cAEoloABMyAGcYKAkAczM4MIjxSKoPOBM4ADI4AAo9IWU4UBhgcUCQ2PCouFVGNi44qNSNbHwiUkp9KgBKUwtWLx9-YiDQ8oSYuoSqHpT03lZhMUkZOUUVH0zknLyCopKy+MjKvajk1katFt12vi6TAG4mJkHxMLgwLk1mnTIGeQgIWpGkRMNHoDDuTCAA

**Related Issues:**

**Comment by clshortfuse** [comment]
I see what's going on. The JSDocs parser is including `$A` and `$O` as part of `T` when it runs the last `[K in keyof T]`.

I can work around the issue by breaking apart the first part into it's on type first.

````ts
export type XMLObjectBase<T> = {
  $A: {
    [P in keyof T]?: XMLObject<T[P]>[]
  },
  $O: {
    [P in keyof T]?: {
      $$?: Record<string, string>
    } & (T[P] extends string ? {$:string} : XMLObject<T[P]>)
  },
  $$?: Record<string, string>,
};

export type XMLObject<T> = XMLObjectBase<T> & {
  [K in keyof T]?: (T[K] extends string ? string : XMLObject<T[K]>)
};
````

The parser is probably compiling a type as one big one on the fly and getting stuck in an infinite loop.

**Comment by sandersn** [comment]
I thought this might be the result of changing `?` to parse as a type postfix only when no other interpretation is possible, but the bad behaviour repros on 3.9 and 4.0 too.

**Comment by sandersn** [comment]
The code that makes recursive type aliases work failed on typedefs. #40861 fixes this.
