### ISSUE TITLE
unbounded type is not strict

### ISSUE THREAD

**Issue by royling** [microsoft/TypeScript#40235]
**TypeScript Version:**  4.0.2

**Search Terms:** unbounded

**Code**

```ts
type Strings = [string, string];
type Numbers = number[];

type Unbounded = [...Strings, ...Numbers, boolean];
//   ^?

const data: Unbounded = ['a', 'b', false, false]; // <-- No error?
console.log(data);
```

**Expected behavior:**
The above `Unbounded` type should allow only the last element in the tuple as boolean, other elements in range `[2, -2]` if available should be numbers only.

**Actual behavior:**
`[...number[], boolean]` is now handled as `<number | boolean>[]`

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAdgcwM5QLxQNroRVQBooCk0BdAbgChRIoA5AVwFsAjCeTHZdrvFw1a9cNACqyDgHsWyACYQF2PADoNcChlIa1rTt3SlZMgDYQAhshEB6W1EcA9APyiAxjOQEoCy8EsALigpWXklFRxcAHJLaNJojnioADNLM3QIUjSMiBFPb3MINTMZVAAKPwCASmogA

**Related Issues:** 
No.

**Comment by RyanCavanaugh** [comment]
Tuple types don't support this operation, but we should be issuing the same error at the declaration site as we would if there wasn't a type alias used here

Shorter
```ts
type Numbers = number[];
type Unbounded = [...Numbers, boolean];
const data: Unbounded = [false, false];
```

**Comment by royling** [comment]
> Tuple types don't support this operation

This seems opposite of the update in [4.0 doc](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html):
>The second change is that rest elements can occur anywhere in a tuple - not just at the end!

**Comment by RyanCavanaugh** [comment]
Previously, rest elements could *only* occur at the end. Now, that can occur anywhere, as long as they meet the criteria of either being bounded-length tuples themselves, or being type parameters.

**Comment by royling** [comment]
Thanks for the reply.

> as long as they meet the criteria of either being bounded-length tuples themselves, or being type parameters.

Should this be mentioned in the doc? Or, the Unbounded example used in [Variadic Tuple Type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types) looks inappropriate, IMHO.
