### ISSUE TITLE
Type IsNever

### ISSUE THREAD

**Issue by macabeus** [microsoft/TypeScript#40248]
## Search Terms

never, distributive conditional type

## Suggestion

[As described at this issue](https://github.com/microsoft/TypeScript/issues/31751), this behaviour is the expected:

```ts
type IsNever<T> = (
  T extends never
    ? true
    : false
)

let foo: IsNever<1> // false
let bar: IsNever<never> // never
```

But since it always returning `false` or `never` is complicated to compound more complex types, for example:

```ts
type ArrayHasLessThanThreeElements<T> = (
    IsNever<Extract<'2', keyof T>>
)

let a: ArrayHasLessThanThreeElements<[1, 2, 3]> // false
let b: ArrayHasLessThanThreeElements<[1, 2]> // never, but the expected type is "true"
```

## Use Cases

It is useful when you need to compound types and use something like `T extends never`.
Since if T is `never` the truthy clausure isn't run, it's very complicated to compound types at this case.

## Examples

Let's say that we have the new utility type `IsNever` from TS:

```ts
type ArrayHasLessThanThreeElements<T> = (
    IsNever<Extract<'2', keyof T>>
)

let a: ArrayHasLessThanThreeElements<[1, 2, 3]> // false
let b: ArrayHasLessThanThreeElements<[1, 2]> // true
```

**Comment by yume-chan** [comment]
Just scroll down a little bit to https://github.com/microsoft/TypeScript/issues/31751#issuecomment-498526919 you will find how to do `IsNever` as your Intended.

```ts
type IsNever<T> = [T] extends [never] ? true: false;

type ArrayHasLessThanThreeElements<T> = (
    IsNever<Extract<'2', keyof T>>
)

let a: ArrayHasLessThanThreeElements<[1, 2, 3]> // false
let b: ArrayHasLessThanThreeElements<[1, 2]> // true
```
([playground](https://www.typescriptlang.org/play?noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&emitDecoratorMetadata=false&target=99&ts=4.0.2#code/C4TwDgpgBAkgzgOQgNwgJwDwBUB8UC8UA2lgLpQQAewEAdgCZzG0rrkD8UwaArhAFxQAZgEMANnAgBuAFAzQkKAEE0aESAASIuABkIcOFgAWI2sbQQIAUTEQAtnWBxseQgAoZUL7EStMV6jUAY2AMAHIAJjCAGigAawgQAHshKFwcGQBKOVtgKBFBFTVNbT0DY1NzSxt7R2ciAEZYiNiAZlI8AHpO4XFJGVyoACNC1XUtXX1DEzMjC2tbB1onDEbmjqhurl4IIA))
