### ISSUE TITLE
Object.entries implements code error!

### ISSUE THREAD

**Issue by tangjfn** [microsoft/TypeScript#40243]
**TypeScript Version:**  4.0.2

**Search Terms:**

**Code**

typescript.js at line 1479

**Expected behavior:**

var _entries = Object.entries ? Object.entries : function (obj) {
        var keys = getOwnKeys(obj);
        var result = Array(keys.length);
        for (var _i = 0, keys_1 = keys; _i < keys_1.length; _i++) {
            var key = keys_1[_i];
            result[i] = [key, obj[key]];
        }
        return result;
    };

**Actual behavior:**

var _entries = Object.entries ? Object.entries : function (obj) {
        var keys = getOwnKeys(obj);
        var result = Array(keys.length);
        for (var _i = 0, keys_1 = keys; _i < keys_1.length; _i++) {
            var key = keys_1[_i];
            result.push([key, obj[key]]);
        }
        return result;
    };

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
The proposed diff would fail to run.

Please be more explicit about why you think this is wrong

**Comment by tangjfn** [comment]
var result = Array(keys.length);
...
result.push([key, obj[key]]); // here is wrong

result[0 .. keys.length] is undefined

entries push after result[keys.length]

**Comment by tangjfn** [comment]
it is run normally because most javascript has Object.entries function.

**Comment by RyanCavanaugh** [comment]
I misread "Expected" and "Actual" - yes, this is indeed broken.
