### ISSUE TITLE
VS Code consumes too much RAM

### ISSUE THREAD

**Issue by nad182** [microsoft/TypeScript#40246]
Issue Type: <b>Bug</b>

I've checked many similar issueson GitHub and StackOverflow, before I decided to submit mine. My issue is reproducible in both the stable and insider's version of VS Code. Extensions are disabled.
Within an hour or so VS Code starts consuming over 10GB of RAM. Closing it, frees up the memory immediately. If I miss the point, when the RAM consumption is too high, the OS hangs and I'm left with nothing but to hard reset the computer.

I'm attaching the result of `code --status` at the bottom.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3697)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (4.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.2619

</details>

```
Version:          Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS Version:       Darwin x64 19.3.0
CPUs:             Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3697)
Memory (System):  32.00GB (5.00GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	   131	   777	code main
    0	    98	   778	   gpu-process
    0	    33	   781	   utility
    0	   131	  1225	   shared-process
    0	     0	  5025	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   754	  1268	   window (ValidationButtonRow.stories.tsx — wecancomply)
    0	     0	  1269	     /bin/zsh -l
    0	    33	  4396	       npm
    0	     0	  4397	         sh -c cd ./common && start-storybook -p 9009
    0	   819	  4398	           node /Volumes/Shared/work/wecancomply/node_modules/.bin/start-storybook -p 9009
    0	   754	  1272	     extensionHost
    0	   164	  1716	       electron_node tsserver.js 
    0	  3244	  1717	       electron_node tsserver.js 
    0	    66	  1735	         electron_node typingsInstaller.js typesMap.js 
    0	  3178	  1718	       electron_node tsserver.js 
    0	    33	  1809	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1272
    0	    66	  3006	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=1272
    0	    98	  3018	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=1272
    0	    33	  1525	     watcherService
    0	     0	  2314	     /bin/zsh -l
    0	    33	  2771	       npm
    0	     0	  2772	         sh -c cd ./client_eam && react-app-rewired start
    0	    33	  2773	           node /Volumes/Shared/work/wecancomply/node_modules/.bin/react-app-rewired start
    0	   426	  2774	             node /Volumes/Shared/work/wecancomply/node_modules/react-app-rewired/scripts/start.js
    5	   754	  2775	               /Users/naz/.nvm/versions/node/v12.16.1/bin/node --max-old-space-size=2048 /Volumes/Shared/work/wecancomply/node_modules/fork-ts-checker-webpack-plugin/lib/service.js
    0	    66	  2840	     searchService

Workspace Stats: 
|  Window (ValidationButtonRow.stories.tsx — wecancomply)
|    Folder (wecancomply): 809 files
|      File types: ts(233) tsx(103) scss(88) js(50) svg(46) map(43) json(18)
|                  png(7) id(4) otf(4)
|      Conf files: package.json(3) tsconfig.json(3) tslint.json(3)
```

**Comment by mjbvz** [comment]
Thanks for the logs. There definitely is something wrong if the logs are getting that large

@sheetalkamat In a log from TS 3.9.7, I see a huge block of repeating lines:

```
Info 81443[0:13:6.723] -----------------------------------------------
Info 81444[0:13:6.723] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 81445[0:13:6.723] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 15371 structureChanged: undefined Elapsed: 0ms
Info 81446[0:13:6.723] Project '/dev/null/inferredProject1*' (Inferred)
Info 81447[0:13:6.723] 	Files (0) NoProgram

Info 81448[0:13:6.723] -----------------------------------------------
Info 81449[0:13:6.723] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 81450[0:13:6.723] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 15372 structureChanged: undefined Elapsed: 0ms
Info 81451[0:13:6.723] Project '/dev/null/inferredProject1*' (Inferred)
Info 81452[0:13:6.723] 	Files (0) NoProgram
```

It looks like the project is being loaded over and over again.

@nad182 Is your project on a network drive? If so, how is it mounted/shared?

**Comment by nad182** [comment]
My project is on a local SSD drive. The other people on my team use Webstorm IDE. According to them, they don't have any issues with memory leaks.
Another thing is I'm getting the similar issue when I work on different projects, so I don't believe the problem is project related. I also had the same problem in Ubuntu, which I used before switching to mac OS, hoping that changing the OS could solve the memory issue.
I can send you the IDE settings (json) if you think this could help with the investigation.

**Comment by nad182** [comment]
Also I often lose the ability to "fall-through" function/type definitions (with CMD+right click), or typescript doesn't pick up type/interface definitions, showing errors in IDE. But when I open the files with those definitions, the errors disappear, and reappear of I chose the definitions file. Perhaps, these issues are connected somehow.

Oh, and using the latest insider's Typescript version doesn't eliminate any of the issues.

**Comment by nad182** [comment]
Hi there. Sorry for pushing, but I would like to know if there is any estimate when the issue can be resolved or if I can help with the investigation. For now I have to quit VS Code every time the RAM consumption becomes critical (usually once every 2-4 hours, which means I can't have it open at all times), otherwise the OS freezes and I have to do the hard reset.

**Comment by nad182** [comment]
@mjbvz , @RyanCavanaugh , @sheetalkamat , any updates? I woke up today to see my 512GB SSD run out of space. Upon investigation, I noticed that one of the VS Code log file consumes 320GB. This is definitely not normal!

**Comment by nad182** [comment]
@mjbvz , @RyanCavanaugh, @sheetalkamat , I found 2 other people who have a similar issues (memory is leaking/high RAM consumption). Closing IDE frees up 7+ GB of RAM instantly in their case. They are working on completely different projects and in different OSs - one in Ubuntu, another one in MacOS. If they don't close VS Code in time, the whole OS hangs, and they have to hard reset their machines (same for me)

**Comment by nad182** [comment]
I switched to Web Storm for now, because it's become impossible to work with VS Code.

**Comment by nad182** [comment]
Wow... Still no reply. That must  be such a thorough investigation! Thank you, Microsoft, for taking such a meticulous look into the issue!

**Comment by nad182** [comment]
Hey guys! I hope you're all doing great. No need to rush getting back to me regarding the issue! It's not like it's affecting my work or anything. I know this particular VS Code issue is treated with all seriousness and rigorous steps are being taken in order to solve it in 2020. If nothing else, there's always the next year, and the next year after that, so yeah.

**Comment by kitsonk** [comment]
You are being rude and obnoxious @nad182.

**Comment by nad182** [comment]
Thanks @kitsonk for your valuable input! I will follow the useful steps you provided in order to solve the issue at hand. Great to have such a supportive community! As always, feel free to reach out if you need more information to help with investigation. I look forward to hearing back from you, and I'm ready to try other suggestions if you have any.

**Comment by sheetalkamat** [comment]
@nad182  can you send the tsserver file mentioned in https://github.com/microsoft/TypeScript/issues/40246#issuecomment-680225615 or one using latest typescript built to me at shkamat at microsoft dot com. I can take a look at this issue this week and @mjbvz is going to be out of office this week so that would speed up the process or i would need to wait for him to return to office. Thanks.

**Comment by shepherd1530** [comment]
I am having this same issue! Vscode and typescript maxes out all my ram in less than 10 minutes!! Although Vscode and other languages works fine without freezing my OS.

**Comment by Mckenney17** [comment]
Really???! This is 2022 and I still got here @nad182 
I couldn't bear it any longer, so I decided to google "why?". Fortunately, this is an issue VSCode users have already. 
I'm not even using TypeScript yet.
![Screenshot 2022-07-15 124827](https://user-images.githubusercontent.com/37163297/179218157-2c0a57c1-3d73-4dc6-aa32-b7cc5270ae36.png)

**Comment by nad182** [comment]
@Mckenney17 , I'm not surprised at all. But as @kitsonk so politely and helpfully pointed out, it's considered "rude and obnoxious" to report this issue to Microsoft and expect its resolution.

I have "solved" the original issue by the way. Apparently, all I needed to do was delete VSCode and start using WebStorm instead.

**Comment by nad182** [comment]
The logs were shared 3 times 2 years ago by email to "matb at microsoft". So looks like @mjbvz , the person who confirmed that the logs were received also claims that they were never sent.


> Thanks for the logs. There definitely is something wrong if the logs are getting that large

**Comment by mjbvz** [comment]
@nad182 https://github.com/microsoft/TypeScript/issues/40246#issuecomment-703922903

Sorry if you feel the issue didn’t get the right attention. Sheetal asked you for logs using the then recent TS version back in 2020. We didn’t hear anything for 2 years. That’s why I closed it

If you’re still seeing problems, open an new issue with updated logs

**Comment by nad182** [comment]
> @mjbvz is going to be out of office this week so that would speed up the process or i would need to wait for him to return to office. Thanks.

Wow, that's nowhere near the truth. The message said sending the logs would help speed up the process, or we'd need to wait a week for your return. A week - which I was fine with, not 2 years.

**Comment by mjbvz** [comment]
@nad182 Again, if this is still relevant, open a new issue with updated logs. We didn't hear anything for two years which means this issue was likely either fixed or was not actually that important

I'm locking this issue to redirect the energy of conversation in a more productive direction (such as a new issue with updated logs :)
