### ISSUE TITLE
TypeScript 4.0 AST > string | null produces Union(StringKeyword, LiteralType) instead of Union(StringKeyword, NullKeyword) 

### ISSUE THREAD

**Issue by pleerock** [microsoft/TypeScript#40258]
For the following type:

```ts
type Category = {
    name: string | null
}
```

TypeScript 4.0 produces a following AST:

```ts
name > UnionType
                  > StringKeyword
                  > LiteralType
                       > NullKeyword
```

Before 4.0 it was:

```ts
name > UnionType
                  > StringKeyword
                  > NullKeyword
```

Just want to make sure new AST is correct before applying changes in my code.

**Comment by RyanCavanaugh** [comment]
This is the intended categorization since `null` is a literal value at runtime (where as `string` is only a reserved keyword)
