### ISSUE TITLE
Obsolete any keyword

### ISSUE THREAD

**Issue by Bow2Jesus** [microsoft/TypeScript#40252]
## Search Terms

_**any**_

## Suggestion

I read the faq and confirmed that my suggestion is not a duplicate. Here is my suggestion:

Since typescript is supposed to be a type safe scripting language (hence the name) why don't we get ready of the _**any**_ keyword?  

According to the TypeScript documentation,  _**any**_ was only included to help people migrate from JavaScript to TypeScript.  Using _**any**_ allows people to continue to bypass all type safety.  

Migrating to good writing code in a type safe object oriented language from writing bad code in a procedural language with no type safety is about learning better solutions and creating better habits to produce more maintainable and less error prone code.  Giving the people of option of using _**any**_ instead of making them declare the type that they intend allows them to continue to violate the very solid engineering principle of intentionality.  If we force them to declare the type, then they will have be more intentional when they do everything from declaring variables to defining abstract generic classes.  Not only that, everyone else who has to interact with their code will understand what they intended to do.

I know that this will break a lot of code, so I suggest it be done in parts.  

First, in one release a warning that _**any**_ is deprecated will be obsoleted in the next major release. At the same time make no_any the default compiler option.   Also provide suggestions for what to use in the place of _**any**_ in many cases.  

Then obsolete it completely in the next major release.  People can determine whether or not their project is worth migrating to that major release.  All projects that use that major release and all subsequent releases will only have truly typesafe code. (Of course, also standard TypeScript objects and methods would also need stop using _**any**_ as well.)

## Use Cases

Enforce the application of sound engineering principles to produce more maintainable and less error prone code for the browser.

People can continue to use bad habits to produce code that is error prone and hard to maintain as long as _**any**_ is an option.

## Examples

// Currently this is legal, but it will produce an error at run time.

  doSomething() {
    const newFlag: string = 'test';
    this.setToFalse(newFlag);
 }

 setToFalse(flag: any){
   flag = false;
 }

//Under proposed change this is not legal, so it will be caught at compile time and intended type of flag will have to be declared.

  doSomething() {
    const newFlag: string = 'test';
    this.setToFalse(newFlag);
 }

 setToFalse(flag: any){
   flag = false;
 }

//Under proposed change this is not legal just like the current system, so it will be caught at compile time.

  doSomething() {
    const newFlag: string = 'test';
    this.setToFalse(newFlag);
 }

 setToFalse(flag: boolean){
   flag = false;
 }

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code - NO
* [ ] This wouldn't change the runtime behavior of existing JavaScript code - yes
* [ ] This could be implemented without emitting different JS based on the types of the expressions - yes
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.) - yes
* [ ] This feature would agree with the rest of [TypeScript's Design Goals] -(https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) YES.

**Comment by RyanCavanaugh** [comment]
We consider `any` to be an important escape hatch. There are style settings available to you via eslint or tslint if you want to forbid use of it in your codebase.

Moreover, we don't really *ever* remove features, including built-in types.
