### ISSUE TITLE
AllowJs + ES6 lib result in compiler crash

### ISSUE THREAD

**Issue by JimmyPruitt** [microsoft/TypeScript#40251]
**TypeScript Version:**  4.0.2

**Search Terms:**
`typescript Cannot read property 'name' of undefined`

**Code**
For reasons beyond my control, my team has a few node modules checked into our code that we subsequently run through the Typescript compiler as a part of building our front end through the `ts-loader` Webpack loader. We can probably work around this on our end because this case is special, but I'm reporting this because I have a hunch that there could be other legitimate cases that fall to the same error. Here's a minimal `package.json` and `tsconfig.json` that I can use to recreate the problem:

```json
{
  "name": "broken-typescript",
  "version": "1.0.0",
  "scripts": {
    "build": "tsc -p tsconfig.json"
  },
  "dependencies": {
    "@okta/okta-signin-widget": "4.3.3",
    "typescript": "4.0.2"
  }
}
```

```json
{
  "compilerOptions": {
    "rootDir": "./",
    "outDir": "out",
    "allowJs": true,
    "strict": true,
    "lib": ["es6"]
  },
  "include": [
    "./node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.js"
  ]
}

```

Just `npm i && npm run build` and you'll see the error

**Expected behavior:**
The compiler finishes without failure

**Actual behavior:**
An error gets thrown:
```
TypeError: Cannot read property 'name' of undefined
```

**Comment by frank-dspeed** [comment]
That is because https://unpkg.com/browse/@okta/okta-signin-widget@4.3.3/dist/js/okta-sign-in.js is not a JS Module its a webpack module TS does not support importing webpack modules at present.

**Comment by JimmyPruitt** [comment]
The same module works in version 3.9 of Typescript. Are you saying that was an undocumented breaking change of version 4?

**Comment by ahejlsberg** [comment]
The root issue is that this produces an error:

```ts
declare let s: (...items: never[]) => never[];
let t: () => unknown[] = s;  // Error, but should be ok
```

To make matters worse, when attempting to report the erroneous error, we crash if there's a rest parameter:

```ts
declare let s: (...items: never[]) => never[];
let t: (...args: []) => unknown[] = s;  // Crash
```

The issue only occurs with a rest parameter of type `never[]` and it's caused by `compareSignaturesRelated` assuming that `any` (the type used for an unmatched parameter position) is assignable to anything. It is--except for `never`. We should change the logic to not even attempt to relate unmatched positions. I will put up a PR to that effect.
