### ISSUE TITLE
Why Not add a  grammar like '?()' and '!()' ?

### ISSUE THREAD

**Issue by Zhengy1995** [microsoft/TypeScript#40264]
## Search Terms

- ?()
- !()

## Suggestion
Add a grammar like `?()` and `!()`.

## Use Cases
Now i can only use a grammer like `myfn ? mtfn()` to call a  handler which is not necessarily exist, i think that's inconvenient, my wish is to be able to use`?()`operator  whose semantics likes`?.`operator, and use `!()` like `!.`.

## Examples

```javascript
const a = {}
// call a handler which is not necessarily exist
a?.fn?()
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Not sure what you want, as both options exist already...

    const fn = Math.random() > 0.5 ? (() => {}) : undefined;

    fn?.();
    fn!();

**Comment by Zhengy1995** [comment]
> Not sure what you want, as both options exist already...
> 
> ```
> const fn = Math.random() > 0.5 ? (() => {}) : undefined;
> 
> fn?.();
> fn!();
> ```

what i want is
