### ISSUE TITLE
Cannot create union type tokens with null keyword

### ISSUE THREAD

**Issue by ivank** [microsoft/TypeScript#40263]
**TypeScript Version:**  4.1.0-dev.20200826

**Search Terms:** NullKeyword, NullLiteral

**Code**

```ts
import * as ts from 'typescript';

const nullToken = ts.factory.createToken(ts.SyntaxKind.NullKeyword);
const booleanToken = ts.factory.createToken(ts.SyntaxKind.BooleanKeyword);

ts.factory.createUnionTypeNode([nullToken, booleanToken]);
```

**Expected behavior:** 

Should create a union type node. 
```
null | boolean
```

We used to have a literal "null" and a syntax type "null". The syntax type "null", created with `ts.createKeywordTypeNode(ts.SyntaxKind.NullKeyword)`, could be passed to union type tokens.
`ts.factory.createKeywordTypeNode(ts.SyntaxKind.NullKeyword)` doesn't work in the 4.0.2 version too.

**Actual behavior:**

Shows an error 
```
Property '_typeNodeBrand' is missing in type 'NullLiteral' but required in type 'TypeNode'.(2741)
```

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200826#code/JYWwDg9gTgLgBAKjgQwM5xugZlCI4DkMAnmAKaoDGUwYMBA3AFBOUQB2q87ArgDZ8AKhADWZdnAC8GVADosySjGjFZ1MshhlhY9gApMsgMrF2MZAA8A0sHYATWQDl+fK2WIB3aHYCUzNpzwAEYQEHwa7DriUjLyispQquqa2qLiBnImZpY29rIAQqHhyOxunt5+LIYKSipqUBpaAKrswByCpGSOEHZkegDavAJR7AA0cCFhESMAupVAA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/40258

**Comment by RyanCavanaugh** [comment]
Sure seems like `KeywordTypeSyntaxKind` is missing `SyntaxKind.NullKeyword`

**Comment by ivank** [comment]
Adding it back would definitely solve my issue.

**Comment by a-tarasyuk** [comment]
> Sure seems like KeywordTypeSyntaxKind is missing SyntaxKind.NullKeyword

It is true. Just one note, 

https://github.com/microsoft/TypeScript/blob/a9175704eea1b52f2035a8e78bf8acbbe032a7df/src/compiler/types.ts#L6624-L6634

There is `NullLiteral`
```ts
createToken(token: SyntaxKind.NullKeyword): NullLiteral; 
```

and `KeywordTypeNode`

```ts
createToken<TKind extends KeywordTypeSyntaxKind>(token: TKind): KeywordTypeNode<TKind>;
```

After adding `SyntaxKind.NullKeyword` to `KeywordTypeSyntaxKind`, you need to use the generic to create the `Null` type.

```ts
const unionTypeNode = factory.createUnionTypeNode([
   factory.createToken<SyntaxKind.NullKeyword>(SyntaxKind.NullKeyword),
   factory.createToken(SyntaxKind.BooleanKeyword)
]);
```

@RyanCavanaugh It is ok?

**Comment by RyanCavanaugh** [comment]
Looking at it more, it looks like the intended codepath is to call `ts.factory.createLiteralTypeNode` instead. This makes categorization makes sense since `null` is a literal value at runtime the same way `0` is.

**Comment by ivank** [comment]
Before 4.0 My code had 

```
ts.createKeywordTypeNode(ts.SyntaxKind.NullKeyword)
```

What I need is to be able to put "null" types into union types as before. TBH if there is _any_ way of doing that I'll be a happy camper, I just couldn't see any way right now. I like `ts.factory.createLiteralTypeNode` as its more specific.

**Comment by ivank** [comment]
Sorry so the intended way for this is to use createLiteralTypeNode like this?
```typescript
ts.factory.createLiteralTypeNode(ts.factory.createToken(ts.SyntaxKind.NullKeyword))
```
While it does [seem to work](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200826#code/JYWwDg9gTgLgBAKjgQwM5xugZlCI4DkMAnmAKaoDGUwYMBA3AFBOUQB2q87ArgDZ8AKhADWZdnAC8GVADosySjGjFZ1MshhkAMsC1RkQ0mQByEACZkAFJnmLlUVes1lhY9jbkBlYuxjIADwBpYHZzWRN+PiCyYgB3aHMASiSAGlYOLjgAIwgIPg12N3EpGTslFTUoDS1ij1sfP0CQsNkAITyC5HYY+MSk5iZbBQrHKpqyAFV2YA5BYzNLKwBtXgE61JzOwrqAXQGmIA) and we can happily close this issue, it does look a bit inconsistent with the other code.

**Comment by RyanCavanaugh** [comment]
It's different because the emitter pipeline now needs to distinguish `null`s that originate in the value space vs the type space

**Comment by ivank** [comment]
Thanks for tracking that down guys!
