### ISSUE TITLE
Using functions and namespaces with the same name disables type inference with generics? 

### ISSUE THREAD

**Issue by dotansimha** [microsoft/TypeScript#40266]
Using function with generics in order to get type inference works great, but when `namespace` is created in order to extend the function properties - inference is lost. 

The best example for that could be a React Component (a function) that accepts generic parameters. And then declaring `propTypes` in a `namespace` for that function. Generics works when explicitly set, but not when type inference is in use.

**TypeScript Version:**  3.9 / 4.0 
**Search Terms:** generics, type inference, namespaces

**Code**

> This is a very minimal example, but take a look at the playground link to have a complete sense of the issue.

```ts
declare function F<V, R>(v: V): R;
declare namespace F {}; // generics that will be provided by inference of the function will be lost now
```

**Expected behavior:**
Type inference should still working? Just like with manually specific generics?

**Actual behavior:**
Type inference isn't working.

**Playground Link:** 
[link](https://www.typescriptlang.org/play?ssl=42&ssc=5&pln=40&pc=4#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHAN5wAqAnmFgCYARCLgCuILADsYAOQj8scAL5wiJOACIAAgHMoyMAAsAjgBsAtDF4Dz-EeKkxzk+VgD0uaFg30m4aPAcYMhQqIoqaqQaegYmpj6MzAFwAArEYDx86JHkYOmW1qi0jIxuCAiMiFyGwOgQAEYAVlj4cKJh6JkCwmIS0nIKcDAQcIbIAG6KMIaK9aLApk7AknA6UlhQwLhDhQA0cC7wdss6KJLc0ydwWKZhKPiiyKam3AB0lQhujJ6SqPDGog23AAXFxrEJ7H1ZK4ADwcAjAG78UEcGBYP6gv6bSSnJRKfYccaYmDY3EAPjgAF44MFQlgABRlOAAcX0RgAigAZRBuAAGAKBQ3RMHpABIiXAAMokk4AQgAlOxVIjTPx6RLxYrUcLlEpefLfKVyh8wXxJbhNmAjlgEZJgDBgBAVhACEMZpgqPA0hAwOhzHAAO72wxu2r7LCTKAXGo4wPQADW6D4UAILRgL3eDB5jCwAA8WPArHw4ABZbgAYRIYG9vphnEEyBgyCpZ24+04ADUQsBkPVTOiW8hzhTqWxKnAJwKo6CuhDeo4Blg6w2m+2u5te-3UGTfBOJ+Nu5v0QB+Gfrnt99G7ve4GqqyiSUH0yioUSLFFwfiN5AzlfNpSKpSFIAFKSgAGq8ACi-ZQnAAA+BxvqYvhKCUDBlBUWZIJwNToLUbqKAouCmCEjaOs6rqcOBcCeP4kiOOg0yNoGCymNckzSI8zz3A6B5ojsxbLKmD64Fg+z1GgAhwE6NLpKgrxTtwypImc-BwPaZDoGs9GbLgqAfF8DB5gWn4tCRlCqKIkj4ORpYVlWTqOMu36Duca6Hpe6DUkO3BkvSeQ+qgoJlpW4A1qgzmrlw55Htu8qgqBEHQVgsEIZISGGkZ+bJD8fx2SWyDLKFkD0dILb0oBFJjlme5uG4cAAEKSWpMnTIo-KAlGvI0mgYT8PsbWaAeG6eRosk+up6D1FgVxCRslBqUOamDbyX5Nt1uBPKYEm4PGKDoAGWCvJme5wHV1T4QGCZaZQjb7IdowTIoyCiMM5i0WA-b8UtcAHqYwBrbZBDQARQ0eVuY1YqIDyUCde6UDAohQCs9LjqdE4wiFDmlf8nXcJSbCKSow0XluBOEqCZAAIxkLqZJo+jp3VYzLN7vSHBrf+lXsAzrOswjSMrDC-DAOMZIc9+rwIkirxonlSgwm4Iti9efPo6hNVqxrrOK1jdGOPTmtwPKjAa6U9UAJKutwECiG01kkLBg3A88EBBrGYCIqJ0mup4Cj7Kt37db2ECTCx3HTbR7U+by5vXNlrBEeZiiSMgEioME3t6yVjg8+h9WncZOVOnlAUZIUoI1l08kW5IwnhZj9lhXJO5x0oQA)

^ In the example above, take a look at `data` and `variables` - it's being inferred automatically. try to uncomment the last 3 lines of that example => `data` and `variables` becomes `any`. 

**Related Issues:** 
- https://github.com/microsoft/TypeScript/issues/19728 
- https://github.com/microsoft/TypeScript/issues/17574

**Comment by RyanCavanaugh** [comment]
The example given in the issue works fine for me; the example in the Playground is very much not self-contained. Do you have a simpler example that demonstrates the problem we could start from?

**Comment by dotansimha** [comment]
@RyanCavanaugh if you'll uncomment last 3 lines, you'll get:
![image](https://user-images.githubusercontent.com/3680083/91409724-7e2a0e80-e84e-11ea-8b97-9c362850176d.png)

I will try to reproduce it with a simpler setup. The thing is - it works in a very weird way, and I think it breaks only if the inference happens on 2 nested level types.

**Comment by dotansimha** [comment]
@RyanCavanaugh I was doing some more research on this one. 
I think I managed to reproduce it in a clean environment, with less dependencies, and I noticed that it looks like there is a very specific usage case that breaks this example, and it might be related to `propTypes` and they way it declared in runtime. 

It seems like it's not 100% coming from the `namespace` declaration, but from the existence of `propTypes` variable declared, and maybe it conflicts with the type coming from the component TS props declaration? Really not sure.

I managed to create some examples and reproductions that might help with that. 

Take a look [at this example first](https://www.typescriptlang.org/play?ts=3.8.3#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHAArFgAqAnmFuiIlyYTgFoYfAbUaMsADxbxJ-OAEkAdgSxQAyhACuUXFgA8XAHxwAvHADecAPowBMAPwAuOFzgBfegy4EBqo8MBaOgBixCBemtp6hsZmDi6hXqFQ4QDmfla2dv6yDApKcCpYcACyPBwQYKjmACLIMMg2KBo8+faMcP1w4QnRJHERiUYmza3IFgEDg+NcEF5syLDAyAA2021zfQO4ABbAWwAmlBpeABRnM15cLW0AlDZWAFK6ABoAdACiWywICwGngAB84BoDFstgFfMVStB4GcsLgtutKgQDBp8MBgtUeABhEiQDQgmC7dq2ZBdCzXUT1VBeGp1BqUizPLyfX4AoHkuAQqEwgJyRRIuAotEYyHIYGoMB4So1YngYL8uwHfoAei1cAAbus4AzuFImb0GAsdQtFsMYqtOLx+KgfgA1bbAO4waCmCAAIwAVqiYPsLQMrQshjplvb6o6BK73Z7vX7A-gQ5bdQtjqcLiCYyanQmth7Wt7rj8K+tsmaaTwANoAXVe1istfTYd18IYXdFZSCIXgNSqyHCKtJ-Ns12bVg1of6lBgRg0cGumutpmVJLVoJtURi1jskagIxAvl3UGWB9Sri8ZAAjGQ-L4LGvrQNZ2-PwNbjNp+avwBAwLkucCmGcwB6hYDiesgPxpPAvimFq4GQfMgHWl26F+K+AxIZuqpkqCL5znAzyMD2DBAA), we have a `InferSource` type that only has generic and meant to hold this generic for later inference. 
We have props declared in TS only (no propTypes or runtime checks), in a type called `MyProps<TData>` and we have a field called `inferFrom` we'll later use to pass a `const` of type `InferSource`. This will be the source of the type inference. 
Now we are using this inferred `TData` in two ways: one for declaring the `children` callback, and one for declaring a new `inferTo: Partial<TData>`. 
That means, that eventually, based on the generic type (`TData`) declared for the variables passed in `inferFrom`, we'll get a React component `children` function with that one, and also a property (`inferTo`) that should accept `Partial<TData>`. 

At this point, everything works. 

Try to [uncomment lines 16 and 20](https://www.typescriptlang.org/play?ts=3.8.3&ssl=19&ssc=67&pln=17&pc=1#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHAArFgAqAnmFuiIlyYTgFoYfAbUaMsADxbxJ-OAEkAdgSxQAyhACuUXFgA8XAHxwAvHADecAPowBMAPwAuOFzgBfegy4EBqo8MBaOgBixCBemtp6hsZmDi6hXqFQ4QDmfla2dv6yDApKcCpYcACyPBwQYKjmACLIMMg2KBo8+faMcP1w4QnRJHERiUYmza3IFgEDg+NcEF5syLDAyAA2021zfQO4ABbAWwAmlBpeABRnM15cLW0AlDZWAFK6ABoAdACiWywICwGngAB84BoDFstgFfMVStB4GcsLgtutKgQDBp8MBgtUeABhEiQDQgmC7dq2ZBdCzXUT1VBeGp1BqUizPLyfX4AoHkuAQqEwgJyRRIuAotEYyHIYGoMB4So1YngYL8uwHfoAN3WcAZ3CkTN6DAWAHpTQtFsMYqtOLx+KgfgA1bbAO4waCmCAAIwAVqiYPsTQNzZahjplrb6vaBM7Xe7PT7-fgg2aLQtjqcLiCowaHXGtm7Wp7rj8y+tskaaTwANoAXVe1is1dTA3hDHborKQRC8BqVWQ4RVpP5tmujasGuD-UoMCMGjg101ltMypJatBVqiMWsdnDUBGIF8W6gy13qVcXjIAEYyH5fBZl5aBlPn2+BrcZhPje-fwNZ-OcCmGcwBahYDjusgPxpPAvimKaIFgfMf6Wu2KF+E+AzwWuqpkqCj7TnAzyMJ2DBAA), so you'll end us with an empty `propTypes` variable inside the `namespace`. At this point, it still working, and `data` and `inferTo` still works.

Now, [uncomment lines 17-19](https://www.typescriptlang.org/play?ts=3.8.3#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHAArFgAqAnmFuiIlyYTgFoYfAbUaMsADxbxJ-OAEkAdgSxQAyhACuUXFgA8XAHxwAvHADecAPowBMAPwAuOFzgBfegy4EBqo8MBaOgBixCBemtp6hsZmDi6hXqFQ4QDmfla2dv6yDApKcCpYcACyPBwQYKjmACLIMMg2KBo8+faMcP1w4QnRJHERiUYmza3IFgEDg+NcEF5syLDAyAA2021zfQO4ABbAWwAmlBpeABRnM15cLW0AlDZWAFK6ABoAdACiWywICwGngAB84BoDFstgFfMVStB4GcsLgtutKgQDBp8MBgtUeABhEiQDQgmC7dq2ZBdCzXUT1VBeGp1BqUizPLyfX4AoHkuAQqEwgJyRRIuAotEYyHIYGoMB4So1YngYL8uwHfoAN3WcAZ3CkTN6DAWCyGURiq04vH4qB+ADVtsA7jBoKYIAAjABWqJg+xNpv65qgyyt9RtAgdTpdbs9Pvw-sD-WOpwuILDBttUa2ztabuuP0L62yRppPAA2gBdV7WKxlxMDeEMJuispBELwGpVZDhFWk-m2a41qwagP9SgwIwaODXTWm0zKklq0GLYYxax2YMjEC+Vc6ZYb1KuLxkACMZD8vgsc6Txtvt9uM2Hd-vr4nU7gpjOwC1FgcLuQH40ngXxTAAem-X95lfU0mxgvwbwGcDF1VMlQWvMc4GeRgWwYIA) and you'll see that `data` is now `any`, and `inferTo` loses the type inference:

![image](https://user-images.githubusercontent.com/3680083/91635205-35fe1e00-e9ff-11ea-81f4-16e25982e1ca.png)

![image](https://user-images.githubusercontent.com/3680083/91635209-41514980-e9ff-11ea-8791-35d922bdd905.png)

Now, here's when it's get weird. [Try to remove `inferTo` and keep only `data` as for inference](https://www.typescriptlang.org/play?ts=3.8.3#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHAArFgAqAnmFuiIlyYTgFoYfAbUaMsADxbxJ-OAEkAdgSxQAyhACuUXFgA8XAHxwAvHADecAPowBMAPwAuOFzgBfegy4EBqo8MBaOgBixCBemtp6hsZmDi6hXqFQ4QDmfla2dv6yDApKcCpYcACyPBwQYKjmACLIMMg2KBo8+faMcP1w4QnRJHERiUYmza3IFgEDcLgAFsAANgAmlBpeABTrM15cLW0AlDZWAFK6ABoAdACiq1ggWBrwAD5wGgarqwG+xVK0Hg6ywuFWyEocAIBg0+GAwWqPAAwiRIBpXjBpm0OsguhYdqJ6qgvDU6g1sbMTl4rndHs9MXBPt9fgE5IpgXBQeDIZUNMgXqgwHhKjVUeBgoy7H0BgA3SFwIncKQk3oMBYLIZRGJecm8fioW4ANWQq2A+xg0FMEAARgArMEwOYyjWLFYbLa6zj6gTG03m1pWna3EOQ7KqvE8ADaAF0ztYrJHneqBgCGGn2WUgiF4DUqshwuL0YzbDt41ZpSn+pQYEYNHAdi6NaYxWjJW9BuMRiBrHYtVBu74LE3Xf1K6OJw2Lchy2rJ-O4DW63BTOtgLKLA5p7c0vBfKYAPRrjfzBcLNNni+jw+tiUYt7DqtwE6MDMMIA) , **and you'll notice at this point, that `data` is not longer `any` and inference works.**

It seems like something causes TS to be confused when some kind of definitions are there. 

In a more complex example with `apollo-client` (see https://github.com/apollographql/apollo-client/pull/6774#issuecomment-683272059), it seems like just having `propTypes` define in a namespace (and it doesn't matter the content of it) causes it to break and fallback to `any`.

@RyanCavanaugh  is there a way to debug it? and understand where it's coming from and why it's failing to `any`?

**Comment by weswigham** [comment]
It's definitely `propTypes` - the `propTypes` static member on react is used as a primary source of inference (as written today), if present. This is determined entirely by the `react` type definitions - look at the [LibraryManagedAttributes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2967) implementation in the `react` type definitions. Unfortunately, that means the generics in the `propTypes` end up with the default values, since they're on the static side of the component (which has no inference).
