### ISSUE TITLE
Isolate transpile from type checker code.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/TypeScript#4026]
Currently, if you want to do runtime transpilation in the browser you need to ship the entire compiler to the browser (~2.3MB).  I suspect that the code required for just the `transpile` method would be much smaller if it could be isolated from the type checking code

I would like to see the two separated into different files so I can ship the transpiler to the browser in a relatively small package and do runtime transpilation of TypeScript into JavaScript.

**Comment by mhegazy** [comment]
It should be simple to separate transpile from services, that saves you 500-600 KB; separating it from the checker is more work though. if would be open to taking a PR for the first, and discussing the design of the second.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of other feedback or demand
