### ISSUE TITLE
Is it possible to specify the AMD module (project) name during compilation?

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#4027]
I have a large library separated into many sub directories and modules which use ES6 module syntax. They are arranged on disk something like this:
```
src
  |- core
  |    foo.ts
  |    bar.ts
  | - ui
  |     baz.ts
  |     ham.ts
```

Instead of generating anonymous AMD modules and declaration files, I'd like to be able to specify a root path name and have the output explicitly define the module names, so that the files can be easily concatenated and minified:

`foo.js`
```
define('myproject/core/foo', [...], function() { ... } );
```

`foo.d.ts`
```
declare module 'myproject/core/foo' { ... }
```

Is there a way to do this with the current compiler flags or tsconfig?

**Comment by tinganho** [comment]
In addition to setting baseurl, I also think something like requirejs route mapping would also be appropriate for TS.

**Comment by mhegazy** [comment]
The current way is to use `amd-module` tag ([more info](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#amd-module-names)]. 

Filling in the names should be simple assuming you have a `--rootDir` specifided. the question is how you would tell the compiler to do that? new flag? or always do it if you have `rootDir`?

**Comment by sccolbert** [comment]
I think a new flag would be reasonable. It would be nice not to have to use an `amd-module` tag in each module when the names just reflect the input hierarchy. Maybe something like `--amdRoot` which is used as the root of all module names, with the balance of the name computed from the input directory structure.

**Comment by mhegazy** [comment]
is this for both JS and .d.ts? how about enabling `--out` with `--module` to generate a single file for all modules with multiple `define` calls? would that solve the problem?

**Comment by sccolbert** [comment]
That would be fantastic. The ultimate goal is to concat the entire library (both JS and d.ts) into a single file(s) which can be distributed and easily consumed by external users via:

```
import { Foo } from 'myproject/core/foo';
import { Baz } from 'myproject/ui/baz';
```

Having the compiler generate the module names would at least make it possible to concat with external tools, but having it handle the total sequence would be awesome!

**Comment by mhegazy** [comment]
this should be fixed then by https://github.com/Microsoft/TypeScript/pull/5090
