### ISSUE TITLE
tsx file error: 'interface' declarations can only be used in TypeScript files.

### ISSUE THREAD

**Issue by EhsanSarshar** [microsoft/TypeScript#40283]
I am trying to use interface inside a tsx file but produce the following error

'interface' declarations can only be used in TypeScript files.

I am JSX

**Comment by EhsanSarshar** [comment]
Ok I found a weird solution. just renaming the file to .ts and then renaming it back to .tsx solve the issue. maybe the problems is with linter or vscode or something else

**Comment by Bjornnyborg** [comment]
You will simply need to change your file to ".tsx", and enable JSX. :) 
https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by BulatDashiev** [comment]
`TypeScript: restart TS server`, in vscode command pallete solves the problem

**Comment by EhsanSarshar** [comment]
@BulatDashiev ok thanks that solve the issue.
the problem was with TS server it some times produce wired errors like this

**Comment by marevandro** [comment]
> TypeScript: restart TS server

Obrigado!

**Comment by islomrakhimkulov** [comment]
You should rename your file name and change it back it again. For example: .vue rename to .ts and renaming it to back .vue from this aproach problem solved for me.

**Comment by saurabhsri108** [comment]
This started again in 2023 July, in Next project as well.

**Comment by RyanCavanaugh** [comment]
Please file a new bug with repro steps. Thanks!
