### ISSUE TITLE
Allow use of generics inside anonymous functions

### ISSUE THREAD

**Issue by zunger-humu** [microsoft/TypeScript#40287]
## Search Terms

generic anonymous function 

## Suggestion

Named generic functions (`function func<T>(...) { }`) have access to the generic parameter `T` within their definition, but anonymous generic functions (`const func: <T>(...) = ... => { }`) do not. This feels surprising in the bad sense of the word, requiring programmers to know an obscure fact and its correct workaround; I propose making the second syntax valid as well.

## Use Cases

It's common for a generic function definition to need access to the generic parameters, especially it needs to declare types of other generics dependent on the same parameter inside them. Right now this works correctly in some syntaxes but not others (see examples below), and the error one gets gives no hint to the fact that this is the case.

## Examples

The following is valid syntax:

```
interface TestInterface<T> {
    foo: (input: T) => string;
};

const interfaces: TestInterface<string>[] = [
    {foo: (x: string) => `foo-${x}`},
    {foo: (x: string) => `bar-${x}`},
];

function func<T>(x: T, index: number): string {
    const int: TestInterface<T> = interfaces[index];
    return `ack-${int.foo(x)}`
}
```

However, the anonymous version of this is not:

```
const func: <T>(x: T, index: number) => string = (x, index) => {
    const int: TestInterface<T> = interfaces[index];
    return `ack-${int.foo(x)}`
}
```

fails with "Cannot find name 'T'". There are other workarounds to this; e.g., the following syntax is also valid --

```
const func: <T extends unknown>(x: T, index: number) => string = (x, index) => {
    const int: TestInterface<typeof x> = interfaces[index];
    return `ack-${int.foo(x)}`
}
```

but this is at least as surprising as the need to change to the function syntax.

## Checklist

My suggestion meets these guidelines:

* [✔] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [✔] This wouldn't change the runtime behavior of existing JavaScript code
* [✔] This could be implemented without emitting different JS based on the types of the expressions
* [✔] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [✔] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is already allowed; you just have to write it
```ts
const func: <T>(x: T, index: number) => string = <T,>(x: T, index: number) => {
    const int: TestInterface<T> = interfaces[index];
    return `ack-${int.foo(x)}`
}
```

The type in the variable annotation isn't the type of the function - these are separate types that may or may not be identical, with different names.

**Comment by zunger-humu** [comment]
Ah, I understand! Damn, that's verbose, though, especially for nontrivial function signatures. :(
