### ISSUE TITLE
A bug of static type checking in function parameter

### ISSUE THREAD

**Issue by runminlook** [microsoft/TypeScript#40285]
**TypeScript Version:**  4.0.2 in my local env, 3.5.1 in playground

**Search Terms:**
static type checking in function parameter

**Code**

export interface StructMeta {
	ID: number
}

export type FuncStructCast<T> = {Meta: StructMeta} & ((o: any) => T)

export interface HelloRequest {
	aaa: number
}
export function CastHelloRequest(o: any): HelloRequest {
	return {
		aaa: o.aaa,
	}
}
CastHelloRequest.Meta = {"ID":100}

export interface HelloReply {
	status: number
}
export function CastHelloReply(o: any): HelloReply {
	return {
		status: o.status,
	}
}
CastHelloReply.Meta = {"ID":101}

interface IContext {
	Reply(msgID: number, res: any): Promise<void>
}
type UntypedHandlerFunc = (ctx: IContext, o: any) => Promise<void>
type UntypedReg = {[index: number]: UntypedHandlerFunc}
class IRegistry {
	reg: UntypedReg = {}
	Register(msgID: number, handler: UntypedHandlerFunc): void {
		this.reg[msgID] = handler
	}
}

async function OnHello1(ctx: IContext, msg: HelloRequest) {
	ctx
	msg
}

async function OnHello2(ctx: IContext, msg: HelloRequest): Promise<HelloReply> {
	ctx
	msg
	const res: HelloReply = {
		status: 2,
	}
	return res
}

function RegisterUntypedRequestHandler<T, U>(
	registry: IRegistry,
	cast: FuncStructCast<T>,
	typedHandler: (ctx: IContext, msg: T) => Promise<U>,
	castRes: FuncStructCast<U>
) {
	const f: UntypedHandlerFunc = async (ctx: IContext, o: any) => {
		const msg = cast(o)
		const res: U = await typedHandler(ctx, msg)
		await ctx.Reply(castRes.Meta.ID, res)
	}
	registry.Register(cast.Meta.ID, f)
}

function RegisterHandlers(registry: IRegistry) {
	RegisterUntypedRequestHandler(
		registry,
		CastHelloRequest,
		OnHello2,
		CastHelloReply
	)
	RegisterUntypedRequestHandler(
		registry,
		CastHelloRequest,
		// !!!!!!!!!!!!!  The problem is here  !!!!!!!!!!!!!
		// Why no compilation error?
		// OnHello1 returns void, doesn't match Promise<HelloReply>
		OnHello1,
		CastHelloReply
	)
}

const gReg = new IRegistry()
RegisterHandlers(gReg)

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Expect a compilation error.

**Actual behavior:**
No compilation error.

**Playground Link:** 
https://typescript-play.js.org/#code/FAUwHgDg9gTgLgAgJYDs4hgMwIYGMQIDKcMArrnALIhzYIDewAkAJIAiAXAiqQLYBGGYAF9goSLERwAnhAIAxUilzEyFAMLYAznAA8AFQB8CALwNqtLqvJUa2YQgBkCABQuoXbCmkBKU8f0fMXBoeGQ0DBx8BAAJEAAbeKgAJRAAR1IQHQZmbDyuHgEhURDJBEwlCiQoFARNHTjElPTMnXdPbx8uRqTUjKzERiYYGlIYWqGmPOwuKAA6aYAaZlFRerge5v6dOYs6M3oAInZDjgBGAAYL0XFQxFR0LDwCTdSIeOkcph1sOFItAp8QQwES3MoVZRwaq1davEDvaTtBBeXzdBK9eEfL4jP7jL7fWh-AEIeY-InLJirYCw9HNBG7OymBjHNinS5nG7AB6RZ4IFjqGroMCDZhvD4uXhaADm7EBRRgiwQI2JKK6CAACjAoLwkFoQLoAG5QJAAE0MoJkcgQAFU0LIQCaYl4TfEMIplEyXBQwFx+YLwHBFR5kZ1-BqtTq9YbjWbgJaCLb4ybUlKmfQANqoE3gOXAgC6XET9sdztdMHduFEuHi2i0fJTupInyGIylhbtcmTIFTB1ETAbOgwEulsu4QIwioAFqWMO2k06UC63ZU1UbTfi4JPdXNW+nJTK2HmmdPF2WVqDgNppB6IVUaggAPIoTZnL1wH18gURYWK-dopp9K0cB+EM3rMPuF5XjelRQveT6bAATG+H5+t+gYIH+sS0oBAxqpq2q6vqcIIsYoHvuB0rMLgNTZMq-4YgiabMASvz-FwCEUn2OJjLUyoXresG1AOjxFp2OENDOMAGIq1qGC4zCto2MDSL6wnKRSuDaHAXAVtYGhaQYhgUvOklcMhvpfkK6GYYEYb4ZG+qyRpWmpMSukkDY6y6LJwAgVRNGIJgc7FguS7lpUTJQbgrjehZ-o-iSHS+GGkzUSg2T7kymltFAQRMEwaW0VkhaRQA7tgSBSCFknIb+0p5VM5WVQg3pzGKiLZXArkMrQczsIqyp5Vx3ZKdIbUjYOMBelpPXYH1bCKpgQQ3AJ0IIMJGChWWWguIpOjKapE1Nn5-ZHRgokOuJGw1cxe1NhSTA0gBLQDA98G0hxzFPQxHzMHlG0wBdXbbNdp5DrdR3qV9WlwiDD0APTwwgACEqNo+jaMIAg+iTgQEBavwrq8Mgda4yMWMY5TqPMYjCAAOqTp8KBQC12oQEgNaCQgGBajAAD8NNI+9TRnEqozjHWa4moqJpQFkKAAOSILwvy4JO4YEVGxEfOa+XC0kZwPd9dK-Uwy1iIViBSimTIoCApX1pDiJBADW0YDt1vdkEYg+8AQA

**Related Issues:**

**Comment by MartinJohns** [comment]
This doesn't look like a bug.

> // OnHello1 returns void, doesn't match Promise<HelloReply>

First of all, `OnHello1` returns `Promise<void>`, not `void`. If it would return `void` then it would not be compatible, as the type of the argument is a function returning `Promise<U>`.

Next, you didn't specify any type arguments for `T` and `U`, so they're being inferred. The type for `U` is inferred from it's first occurrence, which is the argument `typedHandler`. You pass `OnHello1` here, which returns `Promise<void>`, so `U` is inferred to be `void` - **and not `HelloReply`**.

Going further, the type of `castRes` is `FuncStructCast<void>`, which is essentially `((o: any) => void)`. You're allowed to pass `CastHelloReply` returning `HelloReply` here, because it's legal to assign a function returning non-`void` to one returning `void`.

[Why are functions returning non-void assignable to function returning void?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

**Comment by RyanCavanaugh** [comment]
Please provide repros that are as small as possible while still demonstrating the problem.
