### ISSUE TITLE
Unnessesary `export {};` outputted @4.0.2

### ISSUE THREAD

**Issue by diontools** [microsoft/TypeScript#40281]
**TypeScript Version:**  4.0.2

**Search Terms:** export

**Code**

```ts
import { x } from 'foo'
```

**Expected behavior:** output empty (@3.9.2)

**Actual behavior:** output `export {};`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.2#code/JYWwDg9gTgLgBAbzgDzgXzgMyhEcDkmEE+AsAFBA

**Related Issues:** none

**Comment by DanielRosenwasser** [comment]
By default, `x` will get elided leaving you with an empty file. Other tools need something to indicate to them that the file is a module though, so we add an `export {}`

**Comment by diontools** [comment]
Thank you for the explanation. I understand now. :+1:
