### ISSUE TITLE
Incorrect source map with jsx=preserve

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/TypeScript#4028]
Let's create a file with some JSX inside:

```ts
import React from 'react';

export class JsxNode extends React.Component<{}, {}> {
    render() {
        return <div>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>;
    }
}
```

And compile it:

```ts
tsc test.tsx --target es6 --jsx preserve --sourceMap
```

After that, let's load the result into the http://evanw.github.io/source-map-visualization/:

Everything is fine with the first `div`:

![source map visualization](https://cloud.githubusercontent.com/assets/198327/8893958/8575a556-33ad-11e5-8ab5-86e5488abc99.png)

But not for the children:

![source map visualization2](https://cloud.githubusercontent.com/assets/198327/8893963/b84ff56c-33ad-11e5-94bf-2f4ef112d076.png)

It looks like it thinks that all JSX tags are on one line: 

![source map visualization3](https://cloud.githubusercontent.com/assets/198327/8893981/8ae667f4-33ae-11e5-8f63-390caa0fa373.png)

**Comment by RyanCavanaugh** [comment]
PR posted. Let me know if you see any other weirdness here. Thanks!

**Comment by s-panferov** [comment]
@RyanCavanaugh thanks!
