### ISSUE TITLE
Recursive type references with spreading array of self causes circularly error

### ISSUE THREAD

**Issue by rod24574575** [microsoft/TypeScript#40298]
**TypeScript Version:**  4.0.2

**Search Terms:**
circularly, spread, recursive 

**Expected behavior:** 
pass

**Actual behavior:** 
Type alias 'Test' circularly references itself.(2456)

**Related Issues:**
* https://github.com/microsoft/TypeScript/pull/33050
* https://github.com/microsoft/TypeScript/issues/37649

**Code**
```ts
export type Test = [string, ...Array<Test>];

```

<details><summary><b>Output</b></summary>

```ts
export {};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.staging-typescript.org/play?ts=4.0.2#code/KYDwDg9gTgLgBDAnmYcAqwDO8C8cDa2UAlgHYDmANHAHR0CCUUAhogDwbYB8AugNwAoIA)

It would pass in Typescript 3.9.2, but failed in Typescript 4.0.2. I's not sure whether this is a bug or intended behavior.

**Comment by RyanCavanaugh** [comment]
TS incorrectly failed to detect the circularity in previous versions; this was a bug fix

**Comment by rod24574575** [comment]
But the following code would still pass in Typescript 4.0.2. 

```ts
export type Test = [string, Test];
```

I don't know why this does not regarded as circularity while the code with spreading array is.

**Comment by rod24574575** [comment]
The following syntax would pass in Typescript 4.0.2.

```ts
type Test = [string, ...Test[]];
```

But the following syntax would fail in Typescript 4.0.2.

```ts
type Test = [string, ...Array<Test>];
```

I do not think this behavior should be `Working as Intended`.

**Comment by mscottnelson** [comment]
@rod24574575, I'm trying to figure out a similar scenario, but in the specific case you mention, those are expressing different types. Your first one is a recursive Tuple with optional second parameter, while the second is unbounded because it is explicitly *not* a Tuple, but an Array.
```ts
type Test = [string, ...Test[]];
type Test2 = [string, Test2?];
const t1: Test = ["try",["this",["tuple"]]]; //ok
const t2: Test2 = ["try",["this",["tuple"]]]; //ok
const lateAssignment = ["try",["this",["tuple"]]];
const t3: Test = lateAssignment;
// Err: Type '(string | (string | string[])[])[]' is not assignable to type 'Test'.
// Property '0' is optional in type '(string | (string | string[])[])[]' but required in type '[string, ...Test[]]'.
```

Personally, I'm looking for a way to do function parameter mapping using recursive types, basically to construct a strict index access type. Unfortunately, I still haven't found it. Not in a nice succinct way, anyway.
