### ISSUE TITLE
Prefixed properties should be optional

### ISSUE THREAD

**Issue by sploders101** [microsoft/TypeScript#40291]
**TypeScript Version:**  4.0.2 (still relevant on nightly 4.1.0-dev.20200826)

**Search Terms:**
ts2774, webkitGetAsEntry, function is always defined

**Code**

```ts
const element: HTMLDivElement = document.createElement("div");
element.addEventListener("drop", (event) => {
    if(event.dataTransfer) {
        for(let i = 0; i < event.dataTransfer.items.length; i++) {
            if(event.dataTransfer.items[i].webkitGetAsEntry) {
                const test = event.dataTransfer.items[0].webkitGetAsEntry();
                console.log(test);
            }
        }
    }
});
```

**Expected behavior:**

Code compiles, and checks whether the platform-specific method exists before calling it.

**Actual behavior:**

Typescript halts compilation and emits a ts2774 "This condition will always return true since the function is always defined. Did you mean to call it instead?" error.

**Playground Link:** 

https://www.typescriptlang.org/play?downlevelIteration=true&allowJs=true&jsx=0&ts=4.1.0-dev.20200826#

**Related Issues:** 

#440 looked like it was dismissed, locked, and swept under the rug without a second look, even though it clearly *is* a bug. Hopefully, by providing a completely valid use case, this will be compelling enough to take another look at it. There was reference to a .d.ts *generator*, so maybe I'm speaking out of turn here, but it should be as simple as adding a few `?`s. I shouldn't have to use `@ts-ignore` to perform a simple platform-specific method presence check.

**Comment by RyanCavanaugh** [comment]
I don't think anything discussed in #440 has changed. It *really does* look like you're forgetting to call that function; you can write
```
if(!!event.dataTransfer.items[i].webkitGetAsEntry) {
```
if your intent is to check for presence.

Making all of these optional now would be a very substantial breaking change for not very much upside.
