### ISSUE TITLE
What is the scope of var in try…catch() block in TypeScript?

### ISSUE THREAD

**Issue by BraveHeart840** [microsoft/TypeScript#40290]
```
// var xyz = "Outside";
try {
  var xyz = "Inside"; 
  throw new Error("Error");
} catch (err) {
  console.log(xyz);  //Variable 'xyz' is used before being assigned.ts(2454)
              ^^^
} finally {
  console.log(xyz);  //Variable 'xyz' is used before being assigned.ts(2454)
}
```

got this Error message when I comment xyz variable outside of try...catch()
var should available in catch block. is it a Bug ?

**Comment by DanielRosenwasser** [comment]
When analyzing the `catch` block, we assume that the flow of control starts before or after any statement of the `try` block (meaning we assume nothing completes executing in the `try` block).

**Comment by BraveHeart840** [comment]
But Does it has any benefit ? That is not to use var in try..catch().

**Comment by DanielRosenwasser** [comment]
Yes, if you called a function that throws an error (e.g. `var xyz = foo()`) then `xyz` wouldn't be initialized.

**Comment by jgentes** [comment]
Nevermind, the type declaration doesn't allow for the variable to be undefined. So the fix is:
```ts
let foo: string | undefined
```
