### ISSUE TITLE
Declaration Merging Run-Time Bugs

### ISSUE THREAD

**Issue by john-larson** [microsoft/TypeScript#40304]
Declaration merging should require importing the files that contain the declaration that are to be merged. (Like the extension methods in C#). Otherwise, static code analysis cannot detect that the file that contains the declaration members used is not imported. 

There may be a tsconfig switch to enable backwards compatibility.

**Comment by RyanCavanaugh** [comment]
The entire point of declarations *in general* is that you're affirmatively describing what is present. Forcing implementations to be given for declarations is counter to that.
