### ISSUE TITLE
Typings for Array.includes

### ISSUE THREAD

**Issue by PuruVJ** [microsoft/TypeScript#40319]
**TypeScript Version:**  3.9.7 to 4.0.2

**Search Terms:** Typescript array includes typings, type, bug

**Code**:
```
[].includes
```
VSCode intellisense as well as the compiler give the error: `Property 'includes' does not exist on type 'undefined[]'.` The error is on any kind of array.

![]()

**Expected behavior:** `Array.includes` is a valid property. 

**Actual behavior:** Error: Array.includes does not exists

**Comment by MartinJohns** [comment]
#26144

**Comment by PuruVJ** [comment]
@MartinJohns Thanks

**Comment by DanielRosenwasser** [comment]
https://github.com/microsoft/TypeScript/issues/40320
