### ISSUE TITLE
New Error: assignability failure (material-ui)

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#40313]
**TypeScript Version:**  4.1.0-dev.20200828

**Code**

Names are from https://github.com/mui-org/material-ui, but a lot has been inlined.

```ts
interface BaseCSSProperties {
    filter?: string & {};
}

interface CSSProperties extends BaseCSSProperties {
    [k: string]: unknown | CSSProperties;
}

type BaseCreateCSSProperties<Props extends object> = {
    [P in keyof BaseCSSProperties]: ((props: Props) => BaseCSSProperties[P]);
};

interface CreateCSSProperties<Props extends object> extends BaseCreateCSSProperties<Props> {
    [k: string]:
        | BaseCreateCSSProperties<Props>[keyof BaseCreateCSSProperties<Props>]
        | CreateCSSProperties<Props>;
}

type StyleRules<Props extends object> = Record<string, CSSProperties | CreateCSSProperties<Props>>;

/**
 * This function doesn't really "do anything" at runtime, it's just the identity
 * function. Its only purpose is to defeat TypeScript's type widening when providing
 * style rules to `withStyles` which are a function of the `Theme`.
 */
declare function createStyles<Props extends object>(
    styles: StyleRules<Props>
): StyleRules<Props>;

// Old: `Props` is inferred as `{}`
// New: `Props` is inferred as `(value: string, index: number, array: string[]) => unknown`
const rules: StyleRules<{}> = createStyles({
    orange: {
        'purple': [] as string[], // Works if it's not an array
    },
});
```

**Expected behavior:** Compiles, as in 4.0.2

**Actual behavior:** Error on `rules`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200828#code/JYOwLgpgTgZghgYwgAgEJwM4QMIGVcAKUA9gA7RjAQbIDeAsAFDIvIzAA2kUA-AFzIMYKKADmyAGR0AvgG4m0pk1Dd4SZHkIlyUStWQQAHpBAATGuiyaiZClRoNmrANoBrAUJEhRAXQEBXEFcQYgB3EGQAHw18Gx09DHlGRUYmMABPcjRMHCgIOEhrbTtqAB44miMTc2RiACMAKwgEMAA+ZABeOiZWZGcCZFBkVwh04hhsq1ji3Xs-ZAAKBdJtDAEKgEpO9sscadtZ6n6fDaS5JUYVaDUUbDyCva0DhPLVg2MIMxp6ppb2qs+NV2d3yhX28XsrzIGHajl6bg8wjEfh6vVY0WB9zBTwhZQqrTco3Gk1yoMecRKGChpBhPlRaKiGix5JmL3xZwuGSyuAyHAgACV-HyqRV3tVvo1mm1Osh+c1iFBTKVPGIADQxHGUxkgh5FZ6Q-GtJJMAD0ACozT0zcgACoAC2ANBggRawGIEVMxGoIAA5GBkPcOBx0sgAESe5BwEDpMAO7yhyP+qCBSgAWwg6uAYB9NAa-iEyFjKGApk+lAyVrYLso7oAdMgAJJgb4gYPIUj+KCkYhYQY0MDEZClmCg22ZCC4BAiUjZ-vj5ChEufMQLu2fdskABuJbElaE6T5AaF+gHyAABovYzyD9Qz6vgAg7ZG8pGqyBXe7ahMi+f7RB02etZWiaTClggHBwC+zrvjWERTmS17CtSlQfF8tSSn8Cz0oIvLUAIiECseIqrK0TAbPhuGCkh7IXCaJrIAA8hwpgCGeFR3o6gwgCOUB5KYkY0GetDSGepr0QAchAoSsexfZcTxfECeeCybnAHD+BAiJeKImZmEYAggP4qZ1NA6qQVAcDpFpYjOCc2zIIEwRhCAomMAg7oFsmwoUTeVFlMJ7RdPBDwERgCxwqwCpRqImndE4DI+h2XZ8j6Ai2UpKreLZ6p0cgADqCquDQwATFmObICE-pRs+FnpNh0iqgopwXEwQA

**Comment by amcasey** [comment]
@ahejlsberg git bisect identified cd305343279abf94030da39e7292dff0e333a95f

**Comment by amcasey** [comment]
The original repro was the material-ui `docs` project, which I understood was part of our test suite.  Is the test suite broken?

**Comment by ahejlsberg** [comment]
This is working as intended and is an effect of type inference being more precise with the changes in the recursive conditional types PR. Previously we would only explore one level when inferring to the recursive `CreateCSSProperties<Props>` type. We now explore all the way down and get a match between the `filter` property in `BaseCSSProperties` and the `filter` method in `string[]`. The types really should be rewritten to not drill into arrays.
