### ISSUE TITLE
How to import "Types" only form d.ts ES5 Library

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#40321]
I've a ES5 Library wich I load globaly in my index.html. (

In the Library Directory there is a ".d.ts" File. 

Problem is, I cannot import the Libray in the Typescript Code, or the Browser will try to load it, but it is already loaded in the index, the minified version.

I cannot use
import type ... 
cause this does not work with .d.ts for ES5 Libs? (Iat least I dont know how, but the compiler throws an error if I try (Is not a module))

We have no build step involved, so webpack or smth. similar can not help to fix this.

I'd like to import the file so we have type information to help.

**Comment by jogibear9988** [comment]
Wouldn't somthing like

       import type "lib"

for global ES5 Libs possible?

**Comment by askirmas** [comment]
Is this what you're looking for?
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-lib-
```typescript
/// <reference lib="es5" />
```

**Comment by jogibear9988** [comment]
I tried like this, but also with an absolute path but it did not work.

My lib is not in node_modules Folder!

**Comment by jogibear9988** [comment]
![image](https://user-images.githubusercontent.com/364896/91718689-2f54df80-eb94-11ea-84b1-c2634c430cdd.png)

**Comment by jogibear9988** [comment]
If I uncomment line 16 it works!

**Comment by jogibear9988** [comment]
When I add it to the start of the File:

![image](https://user-images.githubusercontent.com/364896/91719488-b35b9700-eb95-11ea-9a1d-b35a53f6b8f2.png)

It seems to make a difference if added to the begining or middle of the file

**Comment by askirmas** [comment]
Read carefully references about tsconfig/jsconfig and `reference` directive.

1. You may have several references but only on file's top.
2. In your case it is not `lib` - more like `path`

**Comment by jogibear9988** [comment]
> 2\. In your case it is not `lib` - more like `path`
Why? It is a node module 'stimulsoft-reports-js'
It is found when I do 
 import 'stimulsoft-reports-js'

I do not find a way to get it to work.

**Comment by AlCalzone** [comment]
@jogibear9988 he meant
```ts
/// <reference path="./relative/path/to/definition.d.ts" />
```

**Comment by jogibear9988** [comment]
okay, this does work:

      /// <reference path="../../../node_modules/stimulsoft-reports-js/Scripts/stimulsoft.reports.d.ts" />

**Comment by jogibear9988** [comment]
but I still suggest to also support syntax like

      import types "stimulsoft-reports-js"

**Comment by AlCalzone** [comment]
>       /// <reference path="../../../node_modules/stimulsoft-reports-js/Scripts/stimulsoft.reports.d.ts" />

If it is in node_modules, you can probably also do

        /// <reference path="stimulsoft-reports-js/Scripts/stimulsoft.reports.d.ts" />

**Comment by Bonnev** [comment]
Hi all,

I had the same issue: Using Neutralino.js as a global variable in a Vite app. Adding what @AlCalzone works fine for me!

`/// <reference path="./neutralino.d.ts" />`
