### ISSUE TITLE
Better errors when using properties/methods from newer versions of ECMAScript

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40320]
This is kind of the progression of #25309, and this issue's fix should be inspired by https://github.com/microsoft/TypeScript/pull/27034.

________

Lots of users seem to be confused by misconfiguration when using popular new methods added to built-in types. A recent example is https://github.com/microsoft/TypeScript/issues/40319.

The idea here come up with a static list of methods added to

* `Array`
* `String`
* `RegExp`
* `ObjectConstructor`
* `Promise`
* `Map`
* `Set`
* `Iterator`
* `AsyncIterator`

in newer versions of ECMAScript. These can be found in `src/lib`.

When a user tries to access a property on any of these types, and that type appears in the list, we can provide a suggestion to set their `lib` or `target` (which we've done in other error messages). For example:

```
Property '{0}' does not exist on type '{1}'. Do you need to change your target library? Try changing the `lib` compiler option to '{2}' or later.
```

**Comment by sarathps93** [comment]
Is it ok if I take this up as my first issue? @DanielRosenwasser

**Comment by Vboivin** [comment]
Hey @sarathps93, are you still working on this? If not, I'll take try this issue

**Comment by sandersn** [comment]
As a first step, it would help to have a list of methods with their respective versions added to this bug, if anybody is looking for an easy way to help with no overhead.

**Comment by Vboivin** [comment]
@DanielRosenwasser @RyanCavanaugh @sandersn I attempted a solution for this problem, it might not be the best, waiting for feedback!

**Comment by DanielRosenwasser** [comment]
Thank you @Vboivin!
