### ISSUE TITLE
Wrong Type definition in generic for array

### ISSUE THREAD

**Issue by arsdu24** [microsoft/TypeScript#40332]
**TypeScript Version:**  
 - **3.3.3**
 - **3.5.1**
 - **3.6.3**
 - **3.7.5**
 - **3.8.2**
 - **3.8.3**
 - **3.9.2**
 - **4.0.2**

**Search Terms:**
 - Array of union types unexpected result type
 - generic array of unions unexpected result type

**Code**

```ts
type Arr<T> = T extends (infer U)[] ? U[] : T[];
```

**Expected behavior:**
```ts
const a11: Arr<1 | 2> = [1, 1]; // Should Work
const a12: Arr<1 | 2> = [1, 2]; // Should Work
const a13: Arr<1 | 2> = [2, 2]; // Should Work

const a21: Arr<(1 | 2)[]> = [1, 1]; // Should Work
const a22: Arr<(1 | 2)[]> = [1, 2]; // Should Work
const a23: Arr<(1 | 2)[]> = [2, 2]; // Should Work

const a31: Arr<boolean> = [true, true];  // Should Work
const a32: Arr<boolean> = [true, false];  // Should Work
const a33: Arr<boolean> = [false, false];  // Should Work

const a41: Arr<boolean[]> = [true, true];  // Should Work
const a42: Arr<boolean[]> = [true, false];  // Should Work
const a43: Arr<boolean[]> = [false, false];  // Should Work
```

**Actual behavior:**

```ts
const a11: Arr<1 | 2> = [1, 1]; // Should Work
const a12: Arr<1 | 2> = [1, 2]; // Got this ''Error:(267, 15) TS2322: Type '(1 | 2)[]' is not assignable to type '1[] | 2[]'"
const a13: Arr<1 | 2> = [2, 2]; // Should Work

const a21: Arr<(1 | 2)[]> = [1, 1]; // Should Work
const a22: Arr<(1 | 2)[]> = [1, 2]; // Should Work
const a23: Arr<(1 | 2)[]> = [2, 2]; // Should Work

const a31: Arr<boolean> = [true, true];  // Should Work
const a32: Arr<boolean> = [true, false];  // Should Work
const a33: Arr<boolean> = [false, false];  // Should Work

const a41: Arr<boolean[]> = [true, true];  // Should Work
const a42: Arr<boolean[]> = [true, false];  // Got this  ''Error:(267, 15) TS2322: Type 'boolean[]' is not assignable to type 'false[] | true[]'."
const a43: Arr<boolean[]> = [false, false];  // Should Work
```

**Playground Link:** [try me](https://www.typescriptlang.org/play?ts=3.3.3#code/FAFwngDgpgBAggJwQHgCoD4YF4aplADxCgDsATAZxgAoBLEgMygRgFUBKAbQF0YB+NjxgAuXDwDcwYAGMA9iQogYAQwCMq0YhSqYAHxgAmTDk6qANDFXdxMAPS2YAZQAWsgK4AbMjADqshADWMvKKKqoGmkjIOvpG2DCmFgbWdg4u7l6+-kFyCkpqAMyR2nqGxgkGSSn2Tq6e3n6BUrmhygYa8FHUMYZc3OWJltVpdZmNOSH5BhGdKN2lBn0D5obDtRkN2cF5KgZFs8jzsUvxnJWrNjXp9VlN260FHVrIAEaysh5QyiQDIAhuUAsfwBKVS6xu43u+QKM2ebw+Xx+p2BgJgDGUHgoUFBV1GmyaLWh+zh70+3wG6MxqMpWJxIw2tyCUJUABYnlF4WSSDxfv9USi6eCxltCazYRzSYieci+RYadibGDrsKCZNWcSJQjvtKTPK5RjaYrcQzxkA)

**Comment by RyanCavanaugh** [comment]
Conditional types are distributive; if this is the behavior you want, then the correct definition of `Arr` is
```ts
type Arr<T> = [T] extends [(infer U)[]] ? U[] : T[];
```
