### ISSUE TITLE
Generic type inference reverting to `any`

### ISSUE THREAD

**Issue by Toma91** [microsoft/TypeScript#40334]
**Context**

Let's say I have an API that returns a JSON with some base properties, but that on request can supply extra properties:
```
GET /api
200 OK
{"id":1,"name":"TypeScript"}

GET /api?expand=support_data_1
200 OK
{"id":1,"name":"TypeScript","support_data_1":{"prop":"More data"}}
```
I want to model a type safe version of this and similar APIs, so I want to use generics functions and types. I create an interface
for the "base" properties and another interface for the "extra" properties, then use a generic `get` function to retrieve the values from the API; this function takes all the extra fields needed and the result value contains all the base fields and the supplied extra fields.

Here is a simplified, stringly-typed version of the function just to understand the context:
```ts
function get<E extends string>(extra?: E[]): BaseValues & { [key in E]: any }
get() // is an object containing all the base properties and nothing else
get(['a', 'b', 'c']) // is an object containing all the base properties and `a`, `b` and `c` of type `any`
```
In the code section is what I actually implemented and what does not work as expected.
***Disclaimer:*** I'm not 100% sure this is the only way / right way to do this.

**TypeScript Version:**  3.4.3

**Search Terms:** generics, infer, extends

**Code**

```ts
interface Link<T> {
  href: string
}

interface HasExtras<Extras> {}

type ExtrasOf<T> = T extends HasExtras<infer Extras> ? Extras : never

interface ApiObjExtras {
  support_data_1: { prop: string }
  support_data_2: { prop: string }
}

interface ApiObj extends HasExtras<ApiObjExtras> {
  id: number
  name: string
}

function get_v1<Extras extends Partial<ExtrasOf<ApiObj>>>(link: Link<ApiObj>, expand?: (keyof Extras)[]): ApiObj & Extras {
    return ... // not important
}

function get_v2<T extends HasExtras<any>, Extras extends Partial<ExtrasOf<T>>>(link: Link<T>, expand?: (keyof Extras)[]): T & Extras {
    return ... // not important
}

function test(link: Link<ApiObj>) {
  const v1 = get_v1(link, ['support_data_1'])
  const v2 = get_v2(link, ['support_data_2'])
}

```

**Expected behavior:**
Using `get_v1` offers autocomplete on `expand` values and then, accordingly, on the result of the function, and the types are correctly inferred i.e. `v1` is `ApiObj & { support_data_1: {prop: string} }`.

Using `get_v2` offers autocomplete on `expand` values and then, accordingly, on the result of the function, and the types are correctly inferred i.e. `v2` is `ApiObj & { support_data_2: {prop: string} }`.

**Actual behavior:**
Using `get_v1` offers autocomplete on `expand` values and then on the result of the function, but accepts any value on `expand` besides the ones expected. `support_data_1` is reported as untyped but autocomplete for `prop` is offered.

Using `get_v2` offers autocomplete on `expand` values and then on the result of the function, but accepts any value on `expand` besides the ones expected. `support_data_2` is reported as `any` and no further autocompleted is offered.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is how you should do this:
```ts
interface Link<T> {
  href: string
}

interface ApiObjExtras {
  support_data_1: { prop: string }
  support_data_2: { prop: string }
}

interface ApiObj {
  id: number
  name: string
}

function get_v1<K extends keyof ApiObjExtras>(link: Link<ApiObj>, expand?: readonly K[]): ApiObj & Pick<ApiObjExtras, K> {
    return null as any;
}
function test(link: Link<ApiObj>) {
  const v1 = get_v1(link, ['support_data_1'])
  v1.support_data_1.prop
}
```

**Comment by Toma91** [comment]
I see... so for the generic case I now have:
```ts
interface Link<T> {
  readonly href: string
}

interface HasExtras<Extras> {}

type ExtrasOf<T> = T extends HasExtras<infer Extras> ? Extras : never

interface ApiObjExtras {
  readonly support_data_1: { readonly prop: string }
  readonly support_data_2: { readonly prop: string }
}

interface ApiObj extends HasExtras<ApiObjExtras> {
  readonly id: number
  readonly name: string
}

function get<T extends HasExtras<any>, K extends keyof ExtrasOf<T> = never>(link: Link<T>, expand?: readonly K[]): T & Pick<ExtrasOf<T>, K> {
    return undefined as any
}
```

I had to add the `= never` bit because when I did not supply the `expand` parameter the return type has all the properties of `ExtrasOf<T>` instead of none.

But now I defined a `type WithExtras<T extends HasExtras<any>, K extends keyof ExtrasOf<T> = never> = T & Pick<ExtrasOf<T>, K>` to assign the result of `get`, but the following code that I expected to raise an error don't.
```ts
const link: Link<ApiObj> = ...
get(link) // has no `support_data_1` or `support_data_2`, which is ok
let obj: WithExtras<ApiObj, 'support_data_1'>
obj.support_data_1 // this property exists
obj.support_data_2 // this property does not exist, which is right
obj = get(link) // no `expand` passed, no `support_data_1` or `support_data_2` available, but assignment permitted?
```
