### ISSUE TITLE
Narrowed down type information is lost in switch/case

### ISSUE THREAD

**Issue by lgrahl** [microsoft/TypeScript#40342]
**TypeScript Version:**  4.1.0-dev.20200901

**Search Terms:** switch case narrowed type enum

**Code**

```ts
enum Type {
    A = 0,
    B = 1,
    C = 2,
}

interface Packet<T extends Type, P> {
    type: T,
    data: P,
};

// Explicitly listed all possible `Type`s.
type Layer1Packet =
    | Packet<Type.A, Uint8Array>
    | Packet<Type.B, Uint8Array>
    | Packet<Type.C, Uint8Array>;

// Not explicitly listed `Type`s.
type Layer1PacketAlt = Packet<Type, Uint8Array>;

type Layer2Packet =
    | Packet<Type.A, string>
    | Packet<Type.B, number>;

function decode<
    T extends Type,
    IP,
    OP,
>(
    packet: Packet<T, IP>,
    decoder: (packet: IP) => OP,
): Packet<T, OP> {
    return {
        type: packet.type,
        data: decoder(packet.data),
    }
}

function zeroDecoder(data: Uint8Array): string {
    return new TextDecoder().decode(data);
}

function oneDecoder(data: Uint8Array): number {
    return data[0] as number;
}

function switchAndDecode(packet: Layer1Packet): Layer2Packet {
    switch (packet.type) {
        case Type.A:
            // Works. `packet.type` has been narrowed down to `Type.A` and the information is transferred to `decode`.
            return decode(packet, zeroDecoder);
        case Type.B:
            // Works. Same as above.
            return decode(packet, oneDecoder);
        default:
            throw new Error('nope');
    }
}

function switchAndDecodeAlt(packet: Layer1PacketAlt): Layer2Packet {
    switch (packet.type) {
        case Type.A:
            // Fails. But why? `packet.type` has been narrowed down to `Type.A` but the information is lost.
            return decode(packet, zeroDecoder);
        case Type.B:
            // Works. Copying the object somehow keeps the narrowed down `packet.type`?
            return decode({ type: packet.type, data: packet.data }, oneDecoder);
        default:
            throw new Error('nope');
    }
}

```

**Expected behavior:** The `case Type.A` branch in `switchAndDecodeAlt` should have narrowed down the type of `packet.type` to `Type.A`.

**Actual behavior:** In the mentioned case branch, `packet.type` still has the broader type `Type` even though the case has narrowed it down to `Type.A`.

**Playground Link:** [Click](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200901#code/KYOwrgtgBAKgngB2FA3gKCpqBBKBeKABgBoMsAhfKARlKygGEqAmUgXzTQEsQAXYAE4AzAIYBjZAAVxAa2C8APDCjAAHvxAATAM6xEwYlEkA+VGUy99ALlh0smkbxE3J7ANycA9J6gBRVQgANlxiXLyBcFDB2vyaUCKBgVAIAPba2lwARoHIAAbwSLnaAHRolkhQADIicILU0mJyvPjmUAA+RrLySvrF2IYAqjy8ABzYAgI1xq0dDU09SMXkg8NjE1MznY3dBcDFDCt8a5Nwxh5o3lAAcinNakEhYRFRXDHAcfn6RaXlyNW1AnqXV42ECzQIcx2+kOo3GJzOnF+VRqgmYkPBm3RCz2-SgMQEPAA5tN6LNgdiloZwBBMoIEWghGAQGJeFwUiAoJpgGIUlyFK1lGoNDo9Eg7JgAJKuVoAeWlxgAFK0EMCXOSYIYpcZxZzubzBDYFSrtrwbFKAJT4Uxy0jmtUmpSGOWmdD0ATyMACDmu+hYX42Y1NYq-HX0BxOGxcnlcgRG4HFcMic06jgcBlMllsjkAL0EKQAInqYwrEzYhkc4TU7XjeASQISzG6PV6oCBgAB3WBCwvRwQK80JovAEuOJMeNOM5ms9lQdnAHv62OlqDl2HrODV6m0gSNrDu3iejmJgDahAAuvFdFvBOPOJPMzPtO2wmIABbYLQLrlxk02f51dFq3-AQ0WBXdMCfF9XygH8g1+S0fV9KAxBEbRkF2PorFaJDMEuAB1FIBBkEooFyQN5GDL4oFfVCoFpUBWxECYUnbd5ORYjleBSUiMOwXJ4i0KBeFfZAeCEQiIEcLMoFeITJhAbQhEEd04i40io31XJShw3190PXVe1g+RDFzAQCyHARzQ8HSULQ0U9nILCdPofDCOI4ooAAZRECBkFokRMhSAA3PZsJwvSWw079yN4Qw5y-QQrLCzAuVEMAwSc5yLFfMzOzbTtfGY2MAHIQBSJBiqS+hUzvDNpw5SDeDfD9NAS0FeCM01kQBIETXaoCURA9FwLxZ8mugzrKKQBDkuQ1D0N6bBMqyy4ADERC4QISPIMBmnbV84AAflImKpuAfiaN0eiORAJjcrYzQOKE7jPkWPi6N2oSRJkkBxIEST6pk3RAjSXhtKyqAIqPIdOpMvMEss6ycNshbFkc2aXJ8AiiJIhhyrgIkvuQFJMgAK25ZptBSXzXxYqA5GABBdGE5BbuY1i4ke9sOTI+NflyQ6Mb3ZtocMlAhOsZI+ehTlRwDeNEygNg4rbBGqpw1KRHS00hey3LWw7PwioVUryuASqkcwGqgA)

**Comment by RyanCavanaugh** [comment]
Duplicate #10065

Side note, this is a much better definition for `decode`
```
function decode<P extends Packet<Type, unknown>, O>(packet: P,  decoder: (packet: P["data"]) => O): Packet<P["type"], O> {
```
