### ISSUE TITLE
IntelliSense not working when esModuleInterop was `true` and swagger-parser was imported.

### ISSUE THREAD

**Issue by JasonHK** [microsoft/TypeScript#40355]
**TypeScript Version:**  4.1.0-dev.20200902

**Search Terms:** tsserver, IntelliSense, VSCode, esModuleInterop, swagger-parser

**Code**

[tsconfig.json](https://github.com/JasonHK-Reproductions/TypeScript-IntelliSense-not-working-when-esModuleInterop-was-true/blob/master/tsconfig.json):

```json
{
    "compilerOptions": {
        "target": "ES2015",
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "moduleResolution": "Node"
    }
}
```

[index.ts](https://github.com/JasonHK-Reproductions/TypeScript-IntelliSense-not-working-when-esModuleInterop-was-true/blob/master/index.ts):

```typescript
import SwaggerParser from "swagger-parser";
```

**Expected behaviour:**

Suggestions should shown when I press the <kbd>Tab</kbd> key.

**Actual behaviour:**

No suggestions were shown.

![2020-09-03_00001](https://user-images.githubusercontent.com/4410086/92010189-1575f100-ed7c-11ea-807a-0f573f91ab7b.png)

**Repository Link:** 

<https://github.com/JasonHK-Reproductions/TypeScript-IntelliSense-not-working-when-esModuleInterop-was-true>

**Related Issues:** 

N/A

**Comment by RyanCavanaugh** [comment]
@elibarzilay I suspect there's a crash going on in the LS

**Comment by RyanCavanaugh** [comment]
Sorry, it looks like this one slipped through the cracks. I'm going to assume this has been fixed by now. Please open a new issue if not.
