### ISSUE TITLE
Publish typescript on Bower

### ISSUE THREAD

**Issue by Maks3w** [microsoft/TypeScript#4035]
Since TypeScript v1.5 is it possible to load the typescript transpiler in a browser (see bin/typescript.js)

So will be good if typescript adds a bower.json package definition and register the package on bower directory

See http://bower.io/docs/creating-packages/

PD: I can't provide a PR because I'm against of CLAs

**Comment by RyanCavanaugh** [comment]
Approved. Not sure when we'll get to it.

**Comment by lastmjs** [comment]
I would like to add an opinion. Why do we want to prolong the use of bower? From my point of view the world is switching to NPM. Why give bower another reason to survive? Especially since TypeScript did not start out on bower.

**Comment by Kingwl** [comment]
What's news on it?  🤷🏻‍♂️

**Comment by DanielRosenwasser** [comment]
I get the feeling that this one isn't happening. 😅

**Comment by RyanCavanaugh** [comment]
Closing due to the 4-year timeout rule
