### ISSUE TITLE
Compiler creates broken .d.ts files with "... more ..." in it

### ISSUE THREAD

**Issue by cyberixae** [microsoft/TypeScript#40354]
**Search Terms:** .d.ts more ...

**Code**
The problem seems to only happen with relatively large code bases.
The problem can be reproduced with `Version 4.1.0-dev.20200902` as follows.

```bash
git clone git@github.com:maasglobal/maas-schemas.git
cd maas-schemas/maas-schemas-ts/
yarn
yarn add --dev typescript@next
yarn tsc --version
yarn tsc
grep -R " more " lib
grep -R "\.\.\." maas-schemas-ts/lib|grep -v more|wc -l
```

**Expected behavior:**
The `.d.ts` files should contain full type signatures instead of abbreviations.

**Actual behavior:**
The following abbreviations with `more` can be found in the generated `.d.ts` files.
There are also 60 abbreviations with `...` but without `more`.

```
lib/maas-backend/provider/routes/response.d.ts:                                            ... 4 more ...;
lib/maas-backend/itineraries/itinerary-create/request.d.ts:                        ... 13 more ...;
lib/tsp/journey-planner/response.d.ts:                    ... 10 more ...;
lib/tsp/journey-planner/response.d.ts:                ... 7 more ...;
```

**Comment by cyberixae** [comment]
Actually, I think this might be an issue with io-ts. I'll close the issue for now and reopen it if needed.

**Comment by cyberixae** [comment]
I checked with io-ts and they believe this is a bug in the TypeScript compiler. So I'm reopening this based on that. See gcanti/i-ts#515

**Comment by haggholm** [comment]
We are also seeing this with some very large type definitions.

**Comment by weswigham** [comment]
> The problem seems to only happen with relatively large code bases.

Aye. Even under declaration emit/other "no truncation" modes, the declaration builder still has a maximum length it's willing to build (something like a million projected characters, IIRC, so those types must be truly huge) - if that length is exceeded, we should probably be issuing an error rather than quietly emitting a truncated declaration, though.

**Comment by haggholm** [comment]
> Even under declaration emit/other "no truncation" modes, the declaration builder still has a maximum length it's willing to build (something like a million projected characters, IIRC, so those types must be truly huge) - if that length is exceeded, we should probably be issuing an error rather than quietly emitting a truncated declaration, though.

Or (optionally?) fall back to `any` or `unknown` with a warning, or something. But outputting known-broken output seems like a worst-case option.

**Comment by weswigham** [comment]
Yeah... For context: in many cases where declarations like that get emitted we used to outright crash due to memory issues; so, IIRC, the original fix was aimed at just preventing the crash.

**Comment by cyberixae** [comment]
Can I somehow run the compiler against the generated `.d.ts` files to validate them?

**Comment by hanayashiki** [comment]
It seems that this issue can't be fixed in the near future. For those who use pure typescript in your project, simple set `"declaration": false` in your `tsconfig.json` and specify `"main": "index.ts"`, then you can work well if this project is okay without .d.ts.
