### ISSUE TITLE
Parameters for private ConstructorDeclarations are not emitted inside declarations

### ISSUE THREAD

**Issue by wessberg** [microsoft/TypeScript#40361]
**TypeScript Version:**  4.0.2

**Search Terms:**
private constructor parameters

**Code**

Consider this source file, called `index.ts`:

```ts
class Foo {
  private constructor(foo: string) {}
}
```

Running `tsc` with the declarations enabled will generate the following declarations:

```ts
declare class Foo {
    private constructor();
}
```

Notice that the parameter `foo` to the `ConstructorDeclaration` is being stripped away.
It works fine for all other visibility modifiers (`protected` or `public`).

In fact, in TypeScript prior to v4.0, the `parameters` property of the `ConstructorDeclaration` won't even be a `NodeArray`, but simply `undefined`, leading to a mismatch between the typings for the Compiler APIs and the actual behavior under these circumstances. This has been resolved in v4, however.

**Expected behavior:**

I would expect the generated declarations to include a `ParameterDeclaration` for `foo`.

**Actual behavior:**

The generated declarations does not include a `ParameterDeclaration` for `foo`.

**Playground Link:** 
https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oAcBOBLAbmAC4Cm0w8AdhEdgK7BHzYAUAZogFzQ16UDmAShQBfVGKA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
This is intentional - we remove details when something is a private because we consider it to be irrelevant to the consumer. @RyanCavanaugh knows more. 

There is definitely some weirdness in how this is done based on work that predates us migrating to `strictNullChecks`.

```ts
        function updateParamsList(node: Node, params: NodeArray<ParameterDeclaration>, modifierMask?: ModifierFlags) {
            if (hasEffectiveModifier(node, ModifierFlags.Private)) {
                return undefined!; // TODO: GH#18217
            }
            const newParams = map(params, p => ensureParameter(p, modifierMask));
            if (!newParams) {
                return undefined!; // TODO: GH#18217
            }
            return factory.createNodeArray(newParams, params.hasTrailingComma);
        }
```

**Comment by wessberg** [comment]
Hey again,

I understand your general position on this matter in terms of how `keyof` only considers public keys, etc, but to follow your argument, I would argue that what _should_ happen is that either the private constructor shouldn't be emitted inside the declarations at all, or it should be nominal. It feels a bit strange to me that the parameter list is incomplete.

**Comment by DanielRosenwasser** [comment]
But if we didn't add the private constructor declaration, the class would always get the default public constructor.

**Comment by wessberg** [comment]
I see your point. I understand why you don't emit the parameters, but it still feels like a gotcha. Thanks for the quick response.
