### ISSUE TITLE
Issue use -m system, systemjs cant handle dumplicate dependence, They have deleted it

### ISSUE THREAD

**Issue by xsilen** [Microsoft/TypeScript#4036]
systemjs when there are dumplicate dependence in system.register entry,
the problem occur because the below systemjs function 
```javascript
function dedupe(deps) {
  var newDeps = [];
  for (var i = 0, l = deps.length; i < l; i++)
    if (indexOf.call(newDeps, deps[i]) == -1)
      newDeps.push(deps[i])
  return newDeps;
}
```
They really delete dumplicate dependence, and the system.register `dependence` array length can't math the `setter` array then I see a lot of red in my console... ...

https://github.com/Microsoft/TypeScript/issues/3444#issuecomment-113298972

fix solution in my local https://github.com/xsilen/TypeScript/commit/751fde222f2973acb04067b95a04daf773974742?diff=unified

**Comment by danquirk** [comment]
A minimal repro would be helpful if possible

**Comment by vladima** [comment]
should be handled by https://github.com/systemjs/systemjs/pull/623

**Comment by vladima** [comment]
fixed in https://github.com/systemjs/systemjs/commit/7efd6f8d79b1757836b33acfb2f2e8fbcf1108cf
