### ISSUE TITLE
Cannot use a type mapping with a generic function in TS >=3.5

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#40372]
**TypeScript Version:**  3.5+

**Search Terms:** generic type map. (I think there's a better word for this because mapped types are something else).

**Code**

```ts
// We have different database tables and we use this type mapping to represent which tables
// contain which types of objects.
type TableToObj = {
  user: {id: string, name: string}
  message: {id: string, userId: string, message: string}
}

type Table = keyof TableToObj
type Obj = TableToObj[Table]

// This function is used all over the place to fetch objects.
type getObjValueFn = <T extends Table>(table: T, id: string) => TableToObj[T] | undefined

// It is impossible to define this function without casting.
const getObjValue: getObjValueFn = (table, id) => {
  if (table === "user") {
    return { id: "1", name: "chet" }
  } else {
    return { id: "2", userId: "1", message: "hello"}
  }
}

// These types work.
const user = getObjValue("user", "1")
const message = getObjValue("message", "2")

// And this is an appropriate union type as well.
const table = "user" as Table
const obj = getObjValue(table, "3")
```

**Expected behavior:**
I would expect this function type check properly without casting. If I cast `return  { id: "1", name: "chet" } as TableToObj[typeof table]` then it works, but even `return  { id: "1", name: "chet" } as TableToObj["user"]` does not work.

**Actual behavior:**

**Playground Link:** [Link](https://www.typescriptlang.org/play?#code/FAehAIHUFNwCwIYDdYBMCWAzT0BO0A7AF3FQSIQCMEBnWCygG2hvAQNXAHdYBXO8ETjpWRAJ4AHWAFsEEiegIBzQQHtw+CfjrFuwgMZxBVZjVAR9q4gkV70hwZJbhVmF5QBW0fURoA6YHEpcAAVE1gAXnAAIn48aPAAHxjpFhoEJWho4ECnUPCQ1QB5T3AogG9gcHA43AAucHL0VAaaIlxFJQAacAIEVNb2zoBfKvBUmnTMhqaW8DaO5R7agEk5hc6eianoQcWlUdHc4JKPMvymaELTgG0wy4BdHLBQ4VZMXgIfdCtwERq6JwEIxGC4ULhBHBYBJGAh9PR1DgiA5VJ5vL4AkFYJkiKcAGrA3jQABiBHOAB4QuBoAAPIiEVCse7MAB8AAoGMwGiEes09p0AJRlFkXZjXTx3B5JGocaCYRTQVDPCArEj-dDSCSqSboS5qUhyhWQ-4fL5EH5krjoISqXgkfS0c3KAKWAhtcA4-GE3Ye6C4zwExhE0nnDnhXmoIUREWVaovEJ5ADklOpdIZTPC7M5Pp5f3WQ2UUZjef5ygA3L1+j6NuWAXg1gB+BqfVCGgiKivbDLQJsy1vy9uoCvDaXlEvzAtKCurfP7TtpbulqeV1K9lttjvgYaJv6sAiqEi0GjoJR9PVEdRY8CJz0B72kxMBOMQaoJ4KJsd8idzlfVyfTuhcEbZtZQHTcu0yNdQIVIct1Hcca2XGcl3nSZF2-ToKz6VcQP7GDhx3f590PHVT3CfUr0TZkrmKCUQilZJ1zA1BHzGF5qlfJNP1nTDfxQusgNQKC8MHVCdmEjdYO3XdegPNhSLPZgKKTajxQ8SVWOfDjtLfWAPwQ-8+Iw2sZwk5ixO7Mz8K3Qi9zko8T0UhFHHfbj+Owv8fxHAAyRoDJ-ZDjOXCDPN47cn3AdjtI43TrzcoKsKrfjTNwySLMg1LzJsmTiPk48yPPS8uP83jAsQ9LQtrcK2JfaKdKcVhXHALRVCkXBxGvGcdwQfA-i+VRNXIXVmAiqK6vq98mJg2zZJI-KnOU99EMfNkACYAGZVtWgUxiwcAwz1CIjpiWpoiFWMOPwIheFwMl4uiABGaIeg8hpokMP0ElGaoR2gRgBAu6orpuu7x2iVbnoEtY3qerYF2mGIoRBVRom+rdgCOeMoQELFWC4VRcAAaxdKx3Vqc5bw8QMiTZWJAMhx6zuAV13RCim-S9INoFpkKGYhnbzHAABBDhjVYf52DYeRcFajpyD4AgLRc2BaG4P7GBJt0SGzc46fieTRWgZnSZIVEziiSnqe57MemidameVcAVnFkgtR1QrSEvN5uGtIxXQwc0rGBZWaAbY5sQ5u8udJVaKSpWl6Q4DNLizcJuQjJcizGeO0yTk76fAMYG0NtSbj13BoilaUpsHMZuVTRPGRSeGskL7Ti9U2j1OiXmq8Y6Da+0zKYMdgARVQWAIRMSHxonNfdS3vVWhpF+jghY6iA7mAjItGhq0IkxTBP00N1PLnTkrC2FPyv3Koy75Svs0vGFurNEuDknih-AOhhKX7QhGd8PJv03NJIi9kFLkQvMra8q9gzr00pFWqsV9K30Mq9P+j8a7gVfsPd+I5P6XyQj-HitYQruSrCAqSM1coOQKkpaBlEc6N1YOXBIxcv7oKSn-AhT9mLgHrsfPOPcW7sJvqQ4h9YJEVX4rw7BnA8GKkQWNA+rkiGJQGJgkhVCKo6OyuAuajkoFFXfMwk+bDwAcPUffQyciB6KgEaEBu5jeaWPEclEh-FyE8OrvYhRfDpp+DWptbau03Bb0iMdNh50xhAz9CDdxMRYZGXelCIgX0xi-X+rAQGGh4m3USeDSGgVGZwwAT6aISNGAozRocR2ABhSWPBwCMCwNrKEvp2wdH0DA20JAaADWgHAVQXAw5XjgSSAgABZOQ5xyh3D6obB4vYIkXzQfsXendbj0UxhAcek9p7cAJsTY2WtfT+ipt6daK9I6XLXqGG2eZd4XRZiQWQEgbkXKtqSGZEg5mxIEg0Nku82T3WSRg1Jn0twCi6AC7xwLr6grBhDZYnikmQ28ZU9WNSdo-RyNUV5eSaC8EYCQKI7ybjZieNUPabJtAkqIDE7SwMCn0tJREneAKXhC1wEoXgqRdBNSYTQiB81jHNR6lWekEIhVJnbOCRBWlOJLUnCKwx9DnKUXlXgRVSDoooOWjlUVRiPZaugAqoJG0AAsABWXFcE-oAwBSyggmSMbACAA)

**Related Issues:** 
This issue seemed to be introduced by https://github.com/microsoft/TypeScript/pull/30769

**Comment by RyanCavanaugh** [comment]
Duplicate #33014

**Comment by ccorcos** [comment]
Ah, that looks like the same thing. Thanks @RyanCavanaugh 

Is there a proper name for this pattern of type mappings? If so, it would be nice to add this to the Advanced Types guide somewhere. 😄
