### ISSUE TITLE
Function overload type does not work for defining new anonymous functions.

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#40375]
**TypeScript Version:**  4.0.2

**Search Terms:**

**Code**

I'm looking for a workaround for https://github.com/microsoft/TypeScript/issues/40372 and I'm exploring function overloads.

```ts
type User = {id: string, name: string}
type Message = {id: string, userId: string, message: string}
type TableToObj = {
  user: User
  message: Message
}

type Table = keyof TableToObj
type Obj = TableToObj[Table]

// This works 👍 
function _getObjValue(table: "user", id: string): User | undefined
function _getObjValue(table: "message", id: string): Message | undefined
function _getObjValue(table: Table, id: string): Obj | undefined
function _getObjValue(table: Table, id: string): Obj | undefined {
  if (table === "user") {
    return { id: "1", name: "chet" }
  } else {
    return { id: "2", userId: "1", message: "hello"}
  }
}

// When I grab the type and define the same function, it doesn't work 👎 
type getObjValueFn = typeof _getObjValue

const getObjValue: getObjValueFn = function (table: Table, id: string): Obj | undefined {
  if (table === "user") {
    return { id: "1", name: "chet" }
  } else {
    return { id: "2", userId: "1", message: "hello"}
  }
}
```

**Expected behavior:**

I would expect I can define an anonymous function with the exact same function body and it should type check accordingly.

**Actual behavior:**

**Playground Link:**  [link](https://www.typescriptlang.org/play?ssl=25&ssc=53&pln=25&pc=58#code/FAFwngDgpgBAqgZygJxgXhgbwJYBMBcMCIy2AdgOYA0MZAhgLZSHGmUC+oksAslAgjoVYGHASIly1GAFckyAJLjWUmkwFDmEthU7hoMACp0ARgBsohgPYB5EwCt0WYDFnzCiFC5jrBwwnwawsCcXAbG5iIwANZQYFYAZkamFtZ29mGw6U4RqbYOANq5UAC6wMAJMmQAxiDYVmQwAPrCIOkAanRmMlAAFCApWgBEcihDNHgskpQAlB7yMAA+smS4UAnkULgVVbX1jS1QbQ6d3X0DkYRDvprjMJPaUnMwgX6wy1VrG2RbOzV1DWarQ6XR6-UGhGKE2U0woz2yH1W60220q-32QKOILO4MuyUi0KmOnhDiWKy+KOcrmwSVxFnQaAwI3kQxmVNcMGQRxkyEamHu4iGAEY7vQmFdqgALI5DGCcVzsGBQMxIdmuLkgHl8gVXABMd1GikFIrU-DeV2lZjMViG8rlIXK+lgwJOoKgADFGhgnYlMcd7KceuVqg1iDAXQG3YQI4GPV6YGi9oC6VooTrHrNCAjycifrh2TSYCmGUzDay1ZzubysOnhaLGMMpTL7QqlSrYJhvOqq9qHkN9TRDUoriafGbNBbldbbd5QqEAPTzozS1VOhAwADuVmQ0QAdMAQ2Qw4anDG3b1mWMaHWZgfQyAx0Eomecddx8I7v3WeVFzAAIKrDAICStg66gTAdCNHQEAQMgViwdgdAgLAVQYk6EHrhuU77oeYYXPSpYshh+IWHeR4PlYpIYC+YL4VA14AMyskAA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; there's no proof in that assignment that the expression has the same overload semantics as the defined type, so you need to use a type assertion. A type assertion isn't necessary in the declaration form since there's no place to put it in the first place.

**Comment by ccorcos** [comment]
> so you need to use a type assertion

Can you elaborate on that?

I would expect that if I leave out any type definitions, then the argument types would be inferred.

```ts
const getObjValue: getObjValueFn = function (table, id) {
  if (table === "user") {
    return { id: "1", name: "chet" }
  } else {
    return { id: "2", userId: "1", message: "hello"}
  }
}
```

At least that is the case for simple functions... Why not extend the same behavior to overloads?
