### ISSUE TITLE
for...of failed to deduce element type

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/TypeScript#4041]
Environment TypeScript 1.5 for VS 2015.

```
var a: HTMLScriptElement[] = Array.prototype.slice.call(document.getElementsByTagName("script"));
for (let script of a) {
}
```
Block level variable `script` should be `HTMLScriptElement`, but TypeScript recognizes it as `any`.

And `for (let script: HTMLScriptElement of scripts)` doesn't work because it is not allowed. Only a separate declaration works, which should not be necessary.

**Comment by RyanCavanaugh** [comment]
I can't reproduce this

VS2015
![image](https://cloud.githubusercontent.com/assets/6685088/8915130/075f3942-3458-11e5-8a20-89e07d319f77.png)

TypeScript playground
![image](https://cloud.githubusercontent.com/assets/6685088/8915003/24c6c1a4-3457-11e5-94e5-8b1112d343d6.png)

**Comment by cnshenj** [comment]
Appears to be a ReSharper bug. Sorry, I'll close this issue and report it to JetBrains.
