### ISSUE TITLE
When one object is assigned to another, the validation is invalid

### ISSUE THREAD

**Issue by rainysir** [microsoft/TypeScript#40414]
**Code**

```ts
interface Test1 { 
  development: string;
  production?: string;
}

interface Test2 {
  development: string;
  production: string;
  xxx: number;
  
}

const b: Test2 = {
  development: '',
  production: '',
  xxx: 123,
}

const a: Test1 = b
```

**Expected behavior:**

TS check error

**Actual behavior:**

Verification passed, Allows assignment of b to a.

The xxx attribute of B is not in a

**Comment by IllusionMH** [comment]
TS uses structural subtyping when you assign or pass variable, therefore it only check that other object has all options needed for `Test1` interface and they are compatible. https://www.typescriptlang.org/docs/handbook/interfaces.html#our-first-interface
Excess properties check is done only for fresh object literals. https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks

Exact types are requested in https://github.com/microsoft/TypeScript/issues/12936

**Comment by MartinJohns** [comment]
[What is structural typing?](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing)
