### ISSUE TITLE
Wrong overload inferred in generic function

### ISSUE THREAD

**Issue by SeparateRecords** [microsoft/TypeScript#40413]
**TypeScript Version:**  4.0.2

**Search Terms:**

* Overload inference
* Overload resolution
* Generic function overloaded

**Expected behavior:**
`T` gets inferred from `value`, should resolve `overloaded` to the most appropriate signature (`(x: number) => number`)

**Actual behavior:**
`T` is inferred from final signature of `overloaded`.

**Related Issues:**

* Possibly #17471?
* Possibly #32418?

**Code**
```ts
declare function overloaded(x: number): number;
declare function overloaded(x: string): string;

declare function wonky<T>(value: T, func: (x: T) => T): void;

wonky(1, overloaded)
//    ^-- Argument of type 'number' is not assignable to parameter of type 'string'.

// Maybe shouldn't resolve a type from a function with overloads unless there's
// no other option?
```

It's not pretty, but it can be worked around by forcing `T` to be inferred from `value`.
```ts
declare function wonky<T, _T extends T>(value: T, func: (x: _T) => _T): void;

wonky(1, overloaded)
// function wonky<number, number>(value: number, func: (x: number) => number): void
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
wonky(1, overloaded);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "removeComments": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?removeComments=true&ts=4.0.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxwDcQYIcpRgAKADwC55VkBbAIxIEoGm2SBuAFChIsBCnTY8BYqXKVaDAM4YYWVAHMu8Zao2Ch4aHCRpMufAHc8AawCeAHgAqAPiqEoEZCAaOANCfQGBXhHDngAXmcQrUIcLGB9K1Q7KgBGfyISMgoQYA4BAQB6QpCACyxFeDAofHZ4KxhrXPhYHDRgeFZbJBwYMDV1EPgMHE6ENUQSOA7EGBxmeAADd08QRaKS4SMxU0lLGwc-EIB9eBAaDBBUYEqXNw8vH39xMCD6E7DIj4ZY+L4gA)

**Comment by RyanCavanaugh** [comment]
Duplicate #32418; generic inference is limited to "last overload" in most cases.
