### ISSUE TITLE
Behavior change when lowering async function which throws during argument evaluation

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#40410]
**TypeScript Version:** 4.0.2

**Search Terms:** async argument throw emit lower incorrect behavior

**Code**

```ts
(async() => {
  async function f1(x, y = z) {}
  async function f2({[z]: x}) {}
  for (let f of [f1, f2]) {
    let p = f({}) // This should not throw an error
    try {
      await p
    } catch (e) {
      continue // This error is expected
    }
    throw new Error('Expected an error')
  }
})()
```

**Expected behavior:**

The code should run without crashing, both when compiled to `ESNext` and when compiled to `ES2015`.

**Actual behavior:**

The code crashes with `ReferenceError: z is not defined` when compiled to `ES2015`. This is because the generated code moves the evaluation of default arguments from inside the promise context to outside of the promise context during lowering:

```js
function f1(x, y = z) {
  return __awaiter(this, void 0, void 0, function* () { });
}
function f2({ [z]: x }) {
  return __awaiter(this, void 0, void 0, function* () { });
}
```

There are many ways to fix this, but an example correct compilation might look something like this:

```js
function f1(_0) {
  return __awaiter(this, arguments, void 0, function* (x, y = z) { });
}
function f2(_0) {
  return __awaiter(this, arguments, void 0, function* ({ [z]: x }) { });
}
```

The `_0` variables are to ensure `f1.length` and `f2.length` don't change.

I discovered this correctness issue because I replicated TypeScript's approach to async function lowering into [esbuild](https://github.com/evanw/esbuild) but it turned out to have this correctness issue.

**Playground Link:** [link](https://www.typescriptlang.org/play?target=2#code/BQQwzgngdgxsCUACAvAPkQbwFCMeaMiAZgK6wAuAlgPZTECMwAHgDSIQqIBeSGAvjjyRYxMjCq1iAJmAYA2lwC6ALkRM+vAbiLUATomAAbAKbliiakURyi9NkSmLeg3CbMAHTkVkbEAej9EABUAC0owRDAQ6hJDABNEKGozchDdagB3PDpjXXTdF0RyXQ5sXHK8DJBKD0K+RBgQchgQg2NnCtwYWiooEmN-QNDwxFz8xBHjJndjcWM4usLU9KyoYyyAUTy9YAByDenZ8nns0e3dXfhBAQ0ELCA)

**Related Issues:**

**Comment by SalathielGenese** [comment]
The playground example you provided does not feature what you are describing.

**Comment by evanw** [comment]
If you open [the playground link](https://www.typescriptlang.org/play?target=2#code/BQQwzgngdgxsCUACAvAPkQbwFCMeaMiAZgK6wAuAlgPZTECMwAHgDSIQqIBeSGAvjjyRYxMjCq1iAJmAYA2lwC6ALkRM+vAbiLUATomAAbAKbliiakURyi9NkSmLeg3CbMAHTkVkbEAej9EABUAC0owRDAQ6hJDABNEKGozchDdagB3PDpjXXTdF0RyXQ5sXHK8DJBKD0K+RBgQchgQg2NnCtwYWiooEmN-QNDwxFz8xBHjJndjcWM4usLU9KyoYyyAUTy9YAByDenZ8nns0e3dXfhBAQ0ELCA) and click Run, you will get this error in the developer console (in Chrome, other browsers will have slightly different errors):

```
Uncaught (in promise) ReferenceError: z is not defined
    at f1 (eval at <anonymous> (runtime.ts:68), <anonymous>:12:24)
    at eval (eval at <anonymous> (runtime.ts:68), <anonymous>:19:17)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (runtime.ts:68), <anonymous>:8:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (runtime.ts:68), <anonymous>:4:12)
    at eval (eval at <anonymous> (runtime.ts:68), <anonymous>:11:8)
    at eval (eval at <anonymous> (runtime.ts:68), <anonymous>:28:4)
    at runtime.ts:68
```

If you change the target from `ES2015` to `ESNext` and click run, there will be no errors printed to the developer console.
