### ISSUE TITLE
tsconfig.json compiler option: indent

### ISSUE THREAD

**Issue by jedmao** [Microsoft/TypeScript#4042]
I would just love an `indent` option for the [tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) file, not only for the obvious reason of preserving indentation, but also to prevent issues like the following, where I have TypeScript code with template strings compiling into an ES6 target:

![ts-compiled](https://cloud.githubusercontent.com/assets/1058243/8914821/03f01024-3467-11e5-9b97-d156ae99f3d1.png)

I would imagine as long as it supports 4 spaces, 2 spaces and tabs, that should fulfill most everyone's needs; however, flexibility would probably be best.

**Comment by jedmao** [comment]
Of course, if my editor displayed tabs in a different width, this would look even more horrible.

**Comment by danquirk** [comment]
This seems like a setting better suited to .editorconfig?

**Comment by jedmao** [comment]
@danquirk I use [EditorConfig](http://editorconfig.org/) religiously and [belong to the organization](https://github.com/orgs/editorconfig/people); however, this is definitely a compiler option. The only way I could see EditorConfig coming into the mix is if the compiler actually ran each file path against EditorConfig to see which settings should be applied per file. I really don't want to incur the performance hit of doing this in the TypeScript compiler, so I feel this is much better suited as a compiler option.

Besides, your source files are likely all the same indentation anyway. EditorConfig is great for targeting files in different locations, usually.

**Comment by jedmao** [comment]
We already have a configuration option to control the newline character, why not the indentation as well?

**Comment by mhegazy** [comment]
> We already have a configuration option to control the newline character, why not the indentation as well?

The new line is used for the generated .js not as an editor configuration. here you are talking about editor configuration.

Having said that, now there is a different way to set these options in different editors. maybe we should put formatting options in tsconfig.json and use it in all editors. @jrieken and @billti what do you think?

**Comment by jedmao** [comment]
@mhegazy I am absolutely NOT talking about the editor setting. My screenshot shows the original source on the top half and the compiled output on the bottom half.

**Comment by jedmao** [comment]
The TS compiler replaces leading-tab indentation with 4 spaces is my point. I'd like to control that!

**Comment by mhegazy** [comment]
Ah.. Sorry my bad. In this case, if output formatting is important to you, we suggest you add a JS beautifier to your build. There are many formatting parameters like where to place curlies, spaces before and after keywords, etc.. And trying to do all adds a lot of complexity for small value.

**Comment by jorritd** [comment]
Allthough closed, will you please reconsider this issue. I was looking for an indent setting in the  tsconfig.json file as well to met my companies styling guidelines for javascript  (despite the suggestion for an extra JS beautifier run). If output formatting is no issue for you guys you may omit the line-ending setting as well

**Comment by S-YOU** [comment]
Although it is closed, and I don't care about generated javascript, which I use uglify later. But I do care about the file size, which is 30~40% bigger with 4 spaces than single tab.

Only supporting to specify tab or space and tabSize options should not be a complex issue, because you already writing 4 spaces there.

**Comment by NathanSweet** [comment]
I agree if you have a line ending setting, you might as well have a tab setting. No one is asking for full formatting options, just these two very common settings. That said, we have to do this to get tabs:
```
ls *.js | awk '{print "unexpand -t 4 ", $0, " > /tmp/e; mv /tmp/e ", $0}' | sh
```

**Comment by RWOverdijk** [comment]
Is there an option available for this? I too prefer two spaces over three (for reasons).

**Comment by zbjornson** [comment]
If I'm not mistaken, a PR to add configurable indentation was rejected:
https://github.com/Microsoft/TypeScript/pull/2768

I would appreciate this option for the sake of keeping the diff between TS and emitted JS files minimal. (tsc could even detect source indentation.)

**Comment by S-YOU** [comment]
Rejecting this is just typescript authors want everyone to use four spaces.

For those who just want to change the output to tab, you can patch typescript.js after you install.

`
sed -i 's/"    "/"\\t"/g' node_modules/typescript/lib/typescript.js
`

```
% grep "indentStrings =" node_modules/typescript -R
node_modules/typescript/lib/typescriptServices.js:    var indentStrings = ["", "    "];
node_modules/typescript/lib/typescript.js:    var indentStrings = ["", "\t"];
node_modules/typescript/lib/tsserverlibrary.js:    var indentStrings = ["", "    "];
node_modules/typescript/lib/tsserver.js:    var indentStrings = ["", "    "];
node_modules/typescript/lib/tsc.js:    var indentStrings = ["", "    "];
```

**Comment by RWOverdijk** [comment]
@S-YOU S you, too! .. But thank you, that helps.

**Comment by scniro** [comment]
Hey all, I see @mhegazy's suggestion of using [js-beautify](https://www.npmjs.com/package/js-beautify) is unpopular, however it served my need quite well all while giving me additional control over the output. Assuming `index.ts` at root => `[index.js`, `index.d.ts]`, I included the following script in my `package.json` and can overwrite inline on the file(s).

```json
"scripts": {
  "transpile": "tsc",
  "posttranspile": "js-beautify -s 2 -r index.js index.d.ts",
}
```
