### ISSUE TITLE
Function using Generics with destructuring args and defaults, casts the wrong types

### ISSUE THREAD

**Issue by RuudBurger** [microsoft/TypeScript#40438]
I tried searching but it's kinda hard to find the correct words to search for without getting 100s of search results.

## Function props casting

The problem is that there is some automatic infer for typing when using default values inside an object arg 
`({ arg1 = 1 }) => ...` here arg1 is infered differently depending on how we cast the function.

`type Props = { args1: boolean }`
`const functionName = ({ arg1 = 1 }: Props) => ...` works (gives error that number isn't boolean type)
`const functionName: (props: Props) => void = ({ arg1 = 1 }) => ...` doesn't work like expected. (makes arg1 a union `number | boolean`)

When we do the same thing, but with normal args, it works like expected.

`const functionName = (arg1: boolean = 1) => ...` gives the correct error
`const functionName: (arg1: boolean) => void = (arg1 = 1) => ...` gives the correct error also

See the playground below.

[Playground of the code below on v4.0.2](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAsiAKAnA9mAzlAvFA3gKCigENEBzARgH4AuKAI2WQBsIiA7AbjwF8u8BjZGzTAowRAFcI8ZGgCWwOQDdo2ABQ5iZclig7utOElRoAlFgB8uAlEHDmEAHRNkpNSQqmeePKEiwQADEJNn5FIV01MBR0QwQYs0soJWQ5ABMfOxEoADMiJjQIADkIUiJFFTjg0PC2SM0PHWx9c0wrfEIsh2dXd20vbh88AHph3JCwuSEMAHcFAAsoNmREAFt8rVIMNWXRdihkOgArCDDTABooGZWAaygmORvoCAAPSDCIDIFp0XEpGXkFQgAGU5GxSCwAIJkSKbci0BgOfbNVrtGxdFg9NyNAY+PzQODVSZCUHgqEw9QeBGMFjsVHJVJfLK-STSWQKZQgsEQiDQ0gAJiqE1qpJ5fNhjV0OnpHVs026Lmx-W8QA)

```typescript
type MyProps = {
  arg1?: boolean;
};

const truePositive = ({ arg1 = 1 }: MyProps) => {
  console.log(arg1)
}

type MyFunction = (props: MyProps) => void

const falseNegative: MyFunction = ({ arg1 = 1 }) => {
  console.log(arg1)
}


// functions with normal args (not an object), work like expected

const truePositiveSingleArg = ( arg1: boolean = 1) => {
  console.log(arg1)
}

type MyFunctionSingleArg = (arg: boolean) => void

const truePositiveSingleArg2: MyFunctionSingleArg = ( arg1 = 1 ) => {
  console.log(arg1)
}
```

## Generics
This was the original issue I've found, it might be the same issue, but with generics.
There is a wrong union of types when setting default values on props that are typed through Generics.

[Playground of the code below on v4.0.2](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAYgrgOwMbAJYHsEHVXABYDiECEATqkgM5QC8UAPAAqnpiUB8AFHgIYIAmAGzIAuKJzAs2Y5q0oBKWuygA3dKn6KaytRoDcAKANJMlYFAgAPHgFsww+MjSYxjlBmy5CxMhWp1uPiEyLWUAbwMoKFIIYDhSBCheAWFSQwBfQwNiOBsoAFEEXIAVcGgIqJUeQTgIAEYAGkjVatqAJibK1ogAZib0o1BIKABZEFk2WigKqB5SAHM6gH4xACN0dGE+Qyi5+baVqCKbVbId2YWew8KSsoA6Kpr6qAAfAuPSyAfutoysgHp-gVrHZhFA6gZAVBinhUNQ4VAAO5edBwcx8EBQfgQABmPDggmAlAaUFwUEoeHQiOo+GgJlIMRQUCGqAQ8ygOPQpAsPCQeAu81yxGA2RB9ggbmcCHoYwmHE4zU4M12C0aUCh602ED4zRV+xJUOOp1IuoFfXVQJuNk+EG+Tzqr3ety+j3ajsQ2JxrIg-Ga6VC01NJgQlC1d0E6HmnD2ar2HTN8nO6SaiaMUPyYrBbUhQJhCPzOKR0DglGgnvxhJaTxpvHRMQQ5lZzLw0C5qHmrOqzLKOfJ6BsrcLtPJqFB0CGEGoglQAGtoGZyGzZgIoJqtol+OgoPNYrMoIgPCTEbCwcOJ0ivM3oDk8pvJwgAOQiqy2cWSjwy8ZSeWK5UW8nAIu7JvGu2oIKaMZTA+6Azg+nRRP+RpkBBCwdKa6YfGUq5ohYliQO4S5kCwpAkqcSD4qWUAAAaur0VGkpQj6Nokw6yt+dx7JQPTdpAKHzNxdBWjadq1H0foBn+wahsI4aRtGqoknGimXKmUTJgYqa9hmr5gj0vYABJkNAcbbrE1CluYwBbjwVa1ByLB5Deoo6RKiDuJgn5ylwv7oUCoE6ghAoOnQgG1PBUSGrkxqkThqCFoi0CcoIEaIleUARh2SD2f2ZokqgSKooI-C4fh5hUUh3JvEJ9y0XUVEkr52HmGRFHji2tmTlA6CFtVwxzMZgihkcUVkMSzb5tQMFLHxbRTL1tq1eF-7zU1JUQAR7JUfNInPFVmEuj89WrutrXUbV9H5ix7VsXIHELFxPEQHxAlOtaNXdI04lKIGgVSWGGXyYsyn6gmSYpgClqZtAAAsvYwFySBtdAkhyF1V2tqsABW63mIiXIzlOs7XnhOM+ncUC9lgA1DTu5hEVy1DHkZRbkruNnlgSlm1li6D3k+HJkmePYvmO76YAqURKo1-ngYFkF0Hig0QEtUL4AiHYqJ1w4o5A3L0yacuoVMiuliruawvC5loMlUDkWYzJbsO9KMuYB6YM9c37QtH3wekYg3WwElBqY-1yTGwPxnsPSqVA6mpkAA)
```typescript
type FunctionWithGenerics = <Props>(handler: (props: Props) => void) => void;

const exampleFunction: FunctionWithGenerics = (handler) => {
  return handler;
};

enum EnumType {
  value1,
  value2,
  value3,
}

type MyProps = {
  arg1?: boolean;
  arg2?: number;
  arg3?: EnumType.value1 | EnumType.value2;
};

// Example 1
// This is without any defaults, it shows the correct typing for each argument
exampleFunction<MyProps>(
  ({
    arg1, // boolean
    arg2, // number
    arg3, // EnumType.value1 | EnumType.value2 | undefined
  }) => {
    console.log(arg1, arg2, arg3);
  },
);

// Example 2
// This is if we use default values that arent in the original type
// some of the simple types like string and boolean do get a union, while the type with the enum doesn't
exampleFunction<MyProps>(
  ({
    // string | boolean
    arg1 = 'ok',
    // number
    arg2,
    // EnumType but expecting error, because `value3` isn't in the MyProps.args3 type
    arg3 = EnumType.value3,
  }) => {
    console.log(arg1, arg2, arg3);
  },
);

// Example 3
// Here arg2 gets set to a value from enum
exampleFunction<MyProps>(
  ({
    // boolean
    arg1 = true,
    // number, but if we follow the logic from arg3, i would expect `number | EnumType.value1`, 
    // but because the values of EnumType are also numbers, this is ok?
    arg2 = EnumType.value1,
    // EnumType but expecting `EnumType.value1 | EnumType.value2`, because `value1` is in the MyProps.args3 type
    arg3 = EnumType.value1,
  }) => {
    console.log(arg1, arg2, arg3);
  },
);

// Example 4
// Force the props on the object works like expected. 
// We also get errors where we set a default that doesn't fit the type
exampleFunction(
  ({
    // boolean
    arg1 = false,
    // this gives the proper error
    arg2 = false,
    // This is still cast to the correct union
    arg3 = EnumType.value1,
  }: MyProps) => {
    console.log(arg1, arg2, arg3);
  },
);
```

If you switch the example to v3.7.5 you'll see that parts return typing as expected in Example 3:
<img width="510" alt="Screenshot 2020-09-08 at 22 00 08" src="https://user-images.githubusercontent.com/38136/92522163-ab979480-f21e-11ea-9f6d-ac66c163f59d.png">

If you look at Example 4, which doesn't use the Generics, you see the expected results.

**Comment by RyanCavanaugh** [comment]
Different code doing different things is an observation, not a *per se* defect. Which behavior here is incorrect and why?

**Comment by RuudBurger** [comment]
Well the code is the exact same, the typing is casted different.


So lets pick the top example, because it's the simplest.

[Playground of the codes below](https://www.typescriptlang.org/play?ts=4.0.2#code/PTAEDEFcDsGMBcCWB7aoDuj4AtTIEYBWApgqAIYBOA5gFDwCeADsaAAqXJMDOoAvKADeFGgEYAXKHzJkAG2Lk0AX1r1mrKHCSoAKutH9QACmFVqBpZI5duASn4A+UADdkiACYBuVbVipu8KDwxAGaCCjQBgImIuaGFlacPPZ8Tn7Q3HLEAHSyyNRGZqK23r7+gcGhMOGoAEySYdrQeixRxqZi8aBKKWn+Wbn5hWIlPiAQ1U0YWLjSWYqxaiwTWhEtxLWGw+aSc-KKvS5uXqrpAUEh8I0RAMxbRbsy+2gCxY6gZwN5BUWjZRkVS7XVAAFgakzW6k20SK8UOn3kgx+I08QA)
```typescript
type Props = { arg1: boolean }
type FunctionType = ({ arg1 }: Props) => void;

const testFunction1 = ({ arg1 = 1 }: Props) => console.log(arg1);

const testFunction2: FunctionType = ({ arg1 = 1 }) => console.log(arg1);
```
The typing of `testFunction1` is the exact same as `FunctionType`. And the `arg1` gives the error `number can't be boolean` which is also correct because that is what we defined in `Props`.
![Screenshot 2020-09-10 at 09 22 20](https://user-images.githubusercontent.com/38136/92694291-22c84800-f347-11ea-9ebf-074a06fe0f8b.png)

Now, my assumption is that if the above typing is the same, if I cast `FunctionType` on the const part of the function, it would make the function that is after the "=" follow the same rules. But it doesn't. Because here you don't get the error on `arg1`. It changed the typing of arg1 to a union of `boolean | number`.


If we do the exact same thing with a boolean argument, instead of an object as first arg, it does give the "number can't be boolean" error for both functions, which is what I expect.

```typescript
type FunctionType2 = (arg1: boolean) => void;

const testFunction3 = (arg1: boolean = 1) => console.log(arg1);

const testFunction4: FunctionType2 = (arg1 = 1) => console.log(arg1);
```

You see that the typing for the function is the same, just like in the example above with the object as first argument.

![Screenshot 2020-09-10 at 09 33 40](https://user-images.githubusercontent.com/38136/92695429-b8b0a280-f348-11ea-9493-77c5ad4b2e50.png)

**Comment by zavarka** [comment]
My team recently realized that we are losing type safety when setting default prop values in React components:
```typescript
export interface ButtonProps {
  color: 'primary' | 'secondary';
  size: 'small' | 'medium' | 'large';
}

export const Button: FunctionComponent<ButtonProps> = ({
  color = 'primary',
  size = 'medium'
}) => {
  return (
    <div>Implementation here</div>
  );
};
```
In any location where we need to set a default value, TypeScript silently redefines the contract to include the type of the default value, however random it may be.  If a wrong type is used, or the Props interface changes, the original contract is broken without any errors.  Instead, the code fails at runtime.  This pattern is ubiquitous in our codebase, and to work around this issue, we have to make sure that all our developers are trained to define the prop types twice, like so:

```typescript
export interface ButtonProps {
  color: 'primary' | 'secondary';
  size: 'small' | 'medium' | 'large';
}

export const Button: FunctionComponent<ButtonProps> = ({
  color = 'primary',
  size = 'medium'
}: ButtonProps) => {
  return (
    <div>Implementation here</div>
  );
};
```
From our perspective, this is a defect, a nasty one, because it tends to stay undetected in the absence of a targeted test.  It's hard to see under what conditions this behavior of generic types would be desirable.

**Comment by RemyMachado** [comment]
@zavarka Exact same problem here. Did you find a way to avoid declaring the type, twice?
