### ISSUE TITLE
Why would not use the declare keyword for interface or type at typescript declaration file?

### ISSUE THREAD

**Issue by bahuwang** [microsoft/TypeScript#40447]
When I am using type declaration file, it should use the declare keyword before, example like:
```
declare var a: number
declare let a: number
declare const a: 1
declare function a(b: number): string
declare class A { b(): number }
declare namespace A {}

type A = number
interface A { b?: string }
```
Why would not use the declare keyword before interface or type?
Related Issues: #1940

**Comment by j-oliveras** [comment]
Declare is used to tell the compiler that at runtime exists something and the compiler erase all of them. The interface or types will be erased always so it will not change nothing. For example:
```ts
declare var a: number
declare let b: number
declare const c: 1
declare function d(b: number): string
declare class A { b(): number }
declare namespace B {}

type C = number
interface D { b?: string }
```
Is compiled as:
```ts
"use strict";
```
[Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA3W8oC54DsCuBbARiDAFCiSwIQgAu8+GOBRp40c8YA9pgM61gYAjC3LsAZtkxhqAS27xgACnpY8hGAEoMfGDMwBzEWwTkePeAEF4AbzqKtqpjHgBfIxSxRcIHgAcoYAgAQjZuxNQAnr4IAMLwALyO6sR61ERiAQgAIjZ0APza1LoGrkA)

PD: If you have question, better ask on StackOverflow.
