### ISSUE TITLE
Variables are not exported when targetting SystemJS

### ISSUE THREAD

**Issue by robertsundstrom** [Microsoft/TypeScript#4044]
I use TypeScript with SystemJS, and want to export some variables that I've declared in a module.

Example: ```export let foo = new Foo();```, or with ```var```

However, I can't seem to import them from consuming code.

Not with ```import * as myModule from "myModule";```

Why are these variables not exported as expected?

**Comment by vladima** [comment]
Can you give a repro? It seems to be working for me:
https://gist.github.com/vladima/25d05c091697d3df1dea

**Comment by mhegazy** [comment]
Can you provide more details..

```ts
function Foo() { return 0 }
export let foo = Foo();
```

emits
```js
System.register([], function(exports_1) {
    var foo;
    function Foo() { return 0; }
    return {
        setters:[],
        execute: function() {
            exports_1("foo", foo = Foo());
        }
    }
});
```

and importing it from another module, seems to work fine:

```ts
import * as ns from "app";
ns.foo // OK;
```

**Comment by robertsundstrom** [comment]
My exported variable looks like this:

    export let bindingHandlers = {
	    defaultNamespace: ""
    };

And this is emitted:

    exports_1("bindingHandlers", bindingHandlers = {
        defaultNamespace: ""
    });

**Comment by mhegazy** [comment]
This looks right to me. `exports_1` is the export function. that is similar to AMD's ```ts
exports.bindingHandlers = { defaktNamespace: "" }
```

Can you elaborate on what is broken on the import side?

**Comment by SergioMorchon** [comment]
Probably same here:
# app/main.ts
``` typescript
import {Menu} from "./components/menu";
import Project from "./project/project";

Menu.onNavigate(path => {
	
});

export class Main {
	title = "WFL Wizard";
	project = new Project();
	
	menu = <Menu.Options>{
		text: this.project.name,
		route: "project"
	};
}
```
## app/main.js
``` JavaScript
System.register(["./components/menu", "./project/project"], function(exports_1) {
    var menu_1, project_1;
    var Main;
    return {
        setters:[
            function (_menu_1) {
                menu_1 = _menu_1;
            },
            function (_project_1) {
                project_1 = _project_1;
            }],
        execute: function() {
            menu_1.Menu.onNavigate(function (path) {
            });
            Main = (function () {
                function Main() {
                    this.title = "WFL Wizard";
                    this.project = new project_1.default();
                    this.menu = {
                        text: this.project.name,
                        route: "project"
                    };
                }
                return Main;
            })();
            exports_1("Main", Main);
        }
    }
});
```

# app/components/menu.ts
``` typescript
@component({
	name: NAME,
	template: TEMPLATE
})
export class Menu implements ObservableTree<Menu> {
// (... too large ...)
}
```
## app/components/menu.js
``` JavaScript
System.register(["./component", "../utils"], function(exports_1) {
    var component_1, Utils;
    var NAME, TEMPLATE, Menu;
    return {
        setters:[
            function (_component_1) {
                component_1 = _component_1;
            },
            function (_Utils) {
                Utils = _Utils;
            }],
        execute: function() {
            NAME = "w-menu";
            TEMPLATE = "<button data-bind=\"enable: enabled\"><!-- ko if: icon --><img src=\"\"/><!-- /ko --><span data-bind=\"text: text\"></button>\n<!-- ko if childs.length -->\n<ul data-bind=\" visible: childs.length, foreach: childs\">\n\t<" + NAME + " params=\"\"></" + NAME + ">\n</ul>\n<!-- /ko -->";
            Menu = (function () {
                function Menu(params) {
                    this.text = Utils.toObservable(params.text);
                    this.icon = Utils.toObservable(params.icon, "");
                    this.enabled = Utils.toObservable(params.enabled, true);
                    this.route = Utils.toObservable(params.route, "");
                    this.childs = Utils.toObservableArray(params.childs);
                }
                Menu.prototype.click = function () {
                    for (var _i = 0, _a = Menu.navigateHandlers; _i < _a.length; _i++) {
                        var handler = _a[_i];
                        handler(this.route.peek());
                    }
                };
                Menu.onNavigate = function (c) {
                    Menu.navigateHandlers.push(c);
                };
                Menu.navigateHandlers = [];
                Menu = __decorate([
                    component_1.component({
                        name: NAME,
                        template: TEMPLATE
                    })
                ], Menu);
                return Menu;
            })();
            exports_1("Menu", Menu);
        }
    }
});
```
And when trying to load the Menu module, System fails with:
`Uncaught (in promise) Error: Cannot read property 'onNavigate' of undefined`

**Comment by mhegazy** [comment]
@vladima  can you take a look. from visual inspection, the output looks right. but seems there is something else going on.

**Comment by vladima** [comment]
Tried to reconstruct the repro [here](https://github.com/vladima/systemjsexports-repro) - no luck, everything works as expected so more info about this case will be appreciated, Btw, can I see the definiton of `component` decorator to make sure that is correctly returns constructor function?

**Comment by vladima** [comment]
pinging @SergioMorchon, can you provide more details about this issue?

**Comment by SergioMorchon** [comment]
Sorry @vladima, I'm not currently at work.
Bur seeing your example [repro](https://github.com/vladima/systemjsexports-repro), I didn't use the typescript transpiler with Systemjs. Instead I compile all the sources before, and load them as `.js`.

Even **without** the `@component ` decorator, it returns undefined. But with an UMD module at tsconfig.json it Works fine, even **with** the decorator.

**Comment by mhegazy** [comment]
@SergioMorchon is this still an issue?

**Comment by SergioMorchon** [comment]
@mhegazy I think I was using incorrectly the Systemjs module loader. Probably my fault... Thank you @vladima for the repo example, it showed me a better way to do it!

**Comment by mhegazy** [comment]
thanks @SergioMorchon for getting back to us on this.
