### ISSUE TITLE
http://www.typescriptlang.org/play/?ts=Nightly is broken

### ISSUE THREAD

**Issue by vfonic** [microsoft/TypeScript#40445]
I was reporting another issue and noticed that Nightly editor is broken: http://www.typescriptlang.org/play/?ts=Nightly

http://www.typescriptlang.org/play/ - works just fine (v4.0.2)

**Comment by orta** [comment]
The underlaying issue was fixed this morning https://github.com/microsoft/monaco-editor/pull/2118 when we got some big monaco updates 🎉 - playground TS releases are immutable so the last 2 nightlies are broke but tomorrows build will be back to working
