### ISSUE TITLE
Provide a way to indicate that a function declaration conforms to some interface/type

### ISSUE THREAD

**Issue by dinofx** [microsoft/TypeScript#40455]
When using jsdoc, you can do something like:

```JavaScript
/**
 * @typedef {(path: string[], line: number) => void} PathHandler
 */

/** @type {PathHandler} */
function handlePath(path, lineNumber) {
  //TODO
}
```

This indicates that the type of `handlePath` is determined by `PathHandler`.  The types for params `path` and `lineNumber` are resolved accordingly.

When converting this code to typescript, there is no way to associate the function declaration with the new type/interface.  One workaround is just to repeat all of the type information from `PathHandler` at every function that conforms to the type.  Another workaround is to use a function expression, like `const handlePath: PathHandler = function(....)`, but this loses hoisting and unnecessarily imposes one style over another.

There should be a way to type the entire function declaration similar to the jsdoc equivalent, e.g.:

```
function:PathHandler handlePath(path, lineNumber) {
  //TODO
}
```

**Comment by RyanCavanaugh** [comment]
Duplicate #22063
