### ISSUE TITLE
Conditional type causes `never` type

### ISSUE THREAD

**Issue by thany** [microsoft/TypeScript#40457]
**TypeScript Version:**  4.1.0-insiders.20200909

**Search Terms:** conditional type
Seriously, I have no clue what good keywords for this problem might be.

**Code**

```ts
type Cached<Extensions = null> = Extensions extends string ? (item: string, extension: Extensions) => void : (item: string) => void;

const test1: Cached<'json'> = (item, extension) => {
  console.log(item, extension);
};
test1('foo', 'json');

const test2: Cached<'json' | 'bson'> = (item, extension) => {
  console.log(item, extension);
};
test2('foo', 'json');

const test3: Cached = (item) => {
  console.log(item);
};
test3('foo');
```

So, `Cached` is supposed to be a function that has 1 or 2 arguments, based on the type of `Extensions`. The second argument sould be the same type as `Extensions`, if passed.

* ✔ `Cached` should become `(item: string) => void`
* ✔ `Cached<'json'>` should become `(item: string, extension: 'json') => void`
* ❌ `Cached<'json'|'bson'>` should become `(item: string, extension: 'json'|'bson') => void`

**Expected behavior:**
No errors.

**Actual behavior:**
1. The `item` and `extension` arguments of `test2` are `any`, which is incorrect. I would expect them to be `string` and `'json' | 'bson'`.
2. Calling `test2` makes typescript expect a second argument of type `never`, which is incorrect. I would expect its type to be `'json' | 'bson'`.

The types and calls around `test1` and `test3` are free of errors, and all argument types are completely as expected.

[**Playground Link**](https://www.typescriptlang.org/play?ts=4.1.0-insiders.20200909#code/C4TwDgpgBAwghgYwBYQCYB4CiAPYEB2AzgJYD2RUAvFPgK4A29AfFVDnkWRRLgaoVELAATsXwBzKAH4oACmJ4AtgC5BIseIA0UHhxLlV7AvqIBKKiwBupYqiir5S1UNETzlKzdQBuAFC+EciEoPCEARlV4ZDR0AHIAK0JyWJZqRwhFbV1jLncWAG9fKChAolJ6CAA6elJxdMydXk5yUz8AXz9Q4DDZWIAzUlJY7QSk-FjW-1LgroAmSMQUDFHkqAAfKFiAIzGU1nqsppM8qELi6fKqmrqFDMO9XPbOiCFZ3oGhkcTkyYCg4BCL2AAGYFtE7GlbooTmcSkFLtVavVJh1fF1ge9BhNvEA)
The erros are more easily explored on the playground. You can also easily see for `test1` and `test3` that their types are correct. Super interesting is that hovering over `test2` on line 8 and on line 11, will show different types for the *same* const, which is probably part of the bug.

**Related Issues:** 
Again, I don't really know what kind of feature this problem even relates to, let alone which issue/bug.

**Comment by RyanCavanaugh** [comment]
It sounds like you don't want distributivity over the conditional type, so write
```ts
type Cached<Extensions = null> = [Extensions] extends [string] ? (item: string, extension: Extensions) => void : (item: string) => void;
```
and this works the way you want

**Comment by thany** [comment]
I haven't seen this bracketed notation anywhere... Did I miss that, or is it a seemingly unrelated feature, or what's going on there?
