### ISSUE TITLE
"Convert to named function" refactoring is not suggested for non-arrow function expressions

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#40469]
**TypeScript Version:**  4.0.2

**Search Terms:**

**Code**

```ts
const fn1 = () => {}
const fn2 = function () {}
```

1. Place cursor on `fn2`
2. View code actions (aka quick fixes aka refactorings)

**Expected behavior:**

"Convert to named function" should be suggested, like it is for `fn1` (arrow function).

**Actual behavior:**

Not suggested.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Misclick
