### ISSUE TITLE
Rename refactoring transitivity across interfaces (and types)

### ISSUE THREAD

**Issue by MuTsunTsai** [microsoft/TypeScript#40467]
**Code**

```ts
interface I1 {
    a: string;
}

interface I2 {
    a: string;
}

class A implements I1, I2 {
    a: string;
}

class B implements I2 {
    a: string;
}
```
Rename `B.a` to `B.b`.

**Expected behavior:**

```ts
interface I1 {
    b: string;
}

interface I2 {
    b: string;
}

class A implements I1, I2 {
    b: string;
}

class B implements I2 {
    b: string;
}
```
The idea of "refactoring" is that all functionality should remain intact afterwards.

**Actual behavior:**

```ts
interface I1 {
    a: string;
}

interface I2 {
    b: string;
}

class A implements I1, I2 {
    b: string;
}

class B implements I2 {
    b: string;
}
```
However the current behavior is that the interface `I1` would not change together, so after refactoring an error shows up, saying that `A` does not correctly implement `I1`. Renaming needs to be transitive in regards to interfaces.

**Playground Link:**

[Playground Link](https://www.staging-typescript.org/play?strictPropertyInitialization=false&ts=4.0.2#code/JYOwLgpgTgZghgYwgAgJIEZkG8CwAoZQ5OALmQGcwpQBzAbnwF999RJZEVUAmbfI4mUrUQ9JizwIANnHLlkAQWTAAtgAcpEFRHDyMAGjS9cBIqQpVaDPMzz5ps+QCFl6zdt1G+pwueFWmIA)

**Remark**

Similar issue applies to the following example as well:
```ts

type T1 = {
	a: number;
}

type T2 = {
	a: number;
}

let a: T1 & T2 = {
	a: 1
};

let b: T2 = {
	a: 2
};
```
Renaming `b.a` should have resulted in renaming all four `.a`s.

**Comment by RyanCavanaugh** [comment]
It's very, very subjective to identify the "correct" stopping point in these cases, and we generally err on the side of not changing enough (and leaving type errors) than changing too much (and breaking the runtime behavior of your program).

**Comment by MuTsunTsai** [comment]
I'm not sure where did the subjectivity came from... All we have to do is go through all classes, interfaces and types that are related either by extension or implementation, and rename all members with the same name together. What can go wrong with this? The only thing I can think of is by exporting the wrong name to external scripts, but this can equally happen to any kind of simple renaming, and is something that the author is supposed to be aware of in the first place.

**Comment by MuTsunTsai** [comment]
@RyanCavanaugh I just tested an analogue example in C#, and it has no problem renaming all properties at once:
```cs
interface I1 {
	string a { get; set; }
}

interface I2 {
	string a { get; set; }
}

class A: I1, I2 {
	public string a { get; set; }
}

class B: I2 {
	public string a { get; set; }
}
```
So I really don't understand your mentioning of subjectivity here...

**Comment by RyanCavanaugh** [comment]
Destructuring, for example - what should happen if you rename 'm' in `A` to 'n' here?
```ts
interface A {
  m: string;
}

declare const obj: A;
const { m } = obj;
const n = 10;

function fn() {
  return { m, n }
}
```

**Comment by MuTsunTsai** [comment]
@RyanCavanaugh Simple; let TypeScript generate an error saying that there's a conflict and renaming cannot be done.
