### ISSUE TITLE
Reverse-sync the wiki

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40464]
Today, we have an action on the PR-able wiki repo

https://github.com/microsoft/TypeScript-wiki/blob/466551af203ca08db17261fd3ad8885534e33a34/.github/workflows/sync.yml

However, it hasn't run in 8 months or so because changes on microsoft/TypeScript.wiki are not sync'd up to microsoft/TypeScript-wiki.

This seems achievable with the `gollum` hook.

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#gollum

**Comment by DanielRosenwasser** [comment]
Thanks to @amcasey for finding this

**Comment by orta** [comment]
Yeah, I've wanted to get around to this for a while

**Comment by orta** [comment]
Just need to give @typescript-bot access to write to the typescript-wiki repo then this is sorted

**Comment by orta** [comment]
Cool, confirmed it does bi-directional merging: accepting https://github.com/microsoft/TypeScript-wiki/pull/257 changed the page:

![Screen Shot 2020-09-10 at 11 07 32 AM](https://user-images.githubusercontent.com/49038/92751794-4fd02700-f356-11ea-95f4-d64fbe76e2d5.png)

![Screen Shot 2020-09-10 at 11 07 45 AM](https://user-images.githubusercontent.com/49038/92751785-4e9efa00-f356-11ea-9d54-9c945568c3aa.png)

**Comment by amcasey** [comment]
Thanks, @orta!
