### ISSUE TITLE
Destructuring function argument seems to lose tagged union type information

### ISSUE THREAD

**Issue by mlrv** [microsoft/TypeScript#40472]
**TypeScript Version:**  4.1.0-dev.20200910

**Search Terms:** tagged union, disjoint union, inference, destructuring, pattern matching

**Code**

```ts
type AorB =
    | { type: "a", data: number }
    | { type: "b", data: string }

const f = (aorb: AorB) => {
    switch (aorb.type) {
        case "a": return aorb.data + 123 // OK
        case "b": return aorb.data.substring(0, 1) // OK
    }
}

const g = ({ type, data }: AorB) => {
    switch (type) {
        case "a": return data + 123 // err
        case "b": return data.substring(0, 1) // err
    }
}
```

**Expected behavior:** `g` behaves like `f`

**Actual behavior:** In `g`, switching over the argument `type` property is not enough to determine the type of `data`. Is this intended?

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200910#code/C4TwDgpgBAgg9gJwEJQLwCgpagHygbylEgC4oAiAQ3IBooATS4SsgOwFcBbAIwgSgC+mbHkLEIZct1oMmLKAGdgCAJasA5oPToAxnFZKoAMzRQAFJUTcy8ZAEo0APgLCsCgO4rgOgBbnLCNwAdOIO+K7YWDqUCtBU5GQIEMDsCKxQAcGMzFAA1FAAjABMAMwRkdGxFNKJyanpmUHZlEEK7NxKqhpmAAx0BXYRQkK6+oaaqOZi4BB0zYI2iEgOqM7hkR5evuahLpEVMXHUtSlpsjn5xWX72JVxNVBJp+nNre2dauq9-YORw0A

**Comment by MartinJohns** [comment]
Duplicate of #12184.

**Comment by mlrv** [comment]
Thanks
