### ISSUE TITLE
How to detect circular dependency in Typescript

### ISSUE THREAD

**Issue by tolotrasamuel** [microsoft/TypeScript#40471]
**TypeScript Version:**  3.9.6

**Search Terms:**
metadata design:paramtypes dependency injection di circular dependency
 
**Code**

 The code below has a circular dependency issue. A -> B -> A
  
```ts
// this is Reproducible

# /a.ts


    import {B} from './b';
    import { Service } from './test';
    @Service
    export class A {
        static id = 'A'
    
        constructor(b: B) {
        }
    }


# /b.ts


    import {A} from './a';
    import { Service } from './test';
    @Service
    export class B {
        static id = 'B'
        constructor(a: A) {
        }
    }



# /test.ts


    export function Service(target: any) {
    // purposefully empty 
    }


# /index.ts

    import 'reflect-metadata'
    import {A} from './a'
    import {B} from './b'
    
    const paramTypesA = Reflect.getMetadata('design:paramtypes', A);
    const paramTypesB = Reflect.getMetadata('design:paramtypes', B);
    
    
    console.log('paramTypesA is', paramTypesA)
    console.log('paramTypesB is', paramTypesB)



```

**Expected behavior:**

Expected output is:

    paramTypesA is [ [Function: B] { id: 'B' } ]
    paramTypesA is [ [Function: A] { id: 'A' } ]

The goal is to detect circular dependency. But we also want to know what parameter exactly causes circular dependency.

If reflect-metadata only output undefined, it is impossible to know which parameter provokes the circular dependency.

At the end of the day, we want to return something like this:  `Warning: Circular dependency detected at: A -> B -> A`

**Actual behavior:**

Actual output is: 

    paramTypesA is [ [Function: B] { id: 'B' } ]
    paramTypesB is [ undefined ]

With this, we can only say that `B depends on something that already depends on B.` This leaves the developer wondering: Which something? 

**Playground Link:** 

**Related Issues:** 

# Question: How to achieve the expected output

Two people already found this bug and asked on StackOverflow but nobody knew the answer on how to resolve it.

https://stackoverflow.com/questions/48080152/detecting-circular-dependencies-in-typescript
And 
https://stackoverflow.com/questions/63827293/how-to-detect-circular-dependency-in-typescript

**Comment by AlCalzone** [comment]
This is not exactly the solution you wanted, but the tsconfig option
```json
"importsNotUsedAsValues": "error"
```

**Comment by RyanCavanaugh** [comment]
This appears to be a question

**Comment by JustFly1984** [comment]
@RyanCavanaugh  @AlCalzone @tolotrasamuel  many years ago I found npm package `eslint-plugin-dependencies` https://www.npmjs.com/package/eslint-plugin-dependencies
https://github.com/zertosh/eslint-plugin-dependencies

It is not maintained for several years, and does not support new versions of eslint for couple years and definitely does not support typescript.
Back then it was working I had found all circular dependencies, but currently I have no tool to find circular dependencies. I think circular type and code imports could lead to increase in build speed.

Would love to have automatic circular dependency detection feature native in typescript.

**Comment by nicolashenry** [comment]
@JustFly1984  The rule `no-cycle` from `eslint-plugin-import` https://github.com/benmosher/eslint-plugin-import works pretty well.

**Comment by agileago** [comment]
keep in mind

**Comment by Townsheriff** [comment]
I'm also interested, because without exercising the code there is no way to know that an import is undefined.

**Comment by 0x80** [comment]
I have been using [madge](https://github.com/pahen/madge) to detect circular dependencies. But occasionally I sometimes have a function that is missing from my built output causing runtime errors like `1_mymodule.foo is not a function` it's a mystery to me what's causing that... so if anyone has a clue I'd love to hear about it :)

**Comment by ffMathy** [comment]
`importsNotUsedAsValues` is a super cool setting. Why is it not enabled when `strict` is `true`? Could save so much trouble.
