### ISSUE TITLE
Spreading Parameters of ternary function type does not recognize parameter type

### ISSUE THREAD

**Issue by alanthai** [microsoft/TypeScript#40478]
**TypeScript Version:**  4.0.2

**Search Terms:** spread, parameters, ternary

**Code**

```ts
type EventCallback<T extends EventType> = T extends 'fetch'
  ? (meta: {url: string; duration: number}) => void
  : never;

type EventType = 'fetch';

const listeners = new Map<string, EventCallback<any>[]>();

const getListeners = (eventType: EventType) => listeners.get(eventType) || [];

export function dispatch<T extends EventType>(
  eventType: T,
  args: Parameters<EventCallback<T>>,
) {
  getListeners(eventType).forEach((listener) => listener(...args));
}
```

**Expected behavior:**
No error

**Actual behavior:**
<img width="889" alt="Screen Shot 2020-09-10 at 1 50 49 PM" src="https://user-images.githubusercontent.com/1744278/92775858-be1fe400-f36c-11ea-94fe-a71879aa405d.png">

**Playground Link:** https://www.typescriptlang.org/play?#code/C4TwDgpgBAogbhAdsAwgQwDYYEZoMYDWAPACpQQAewSAJgM6wLIngQB8UAvFGZdYvSgByAGYRgeABZCAUFCgB+KAAoAtuLQAuKAG8ArgCcM2usAMBLRAHMA3FBqG0wcwHtE2xHtXYIBgL4AlFwccC7mNHJQHhAIBjYyMqCQjEjALMncouJSQvEyeG6mUBjmpki+DNyIEADuUACyaGBEphbWADQpyOhYuIREaIggbADaALpsygF5BYhFVuIAMqX8FVwqManpENrwW6xBnBwlZdUGdAB0C8DKm8wHUAA+j1DjeZRgLgbAUCJ6iHhnG57KUwE4pKRyFRaAw9vdIJNInc0qxtCR2pE0AYrHRtAAFLFodTUc5EOGoTA4fDEEhsNgYoI6SLXZanCq3JgoyABC4iL4wfCSZTKE6rAyHY4rcoGZQXOVYnEBaYyPwyIA

**Related Issues:**  None

**Comment by ahejlsberg** [comment]
This is basically a design limitation. A spread argument `...args` is processed as synthetic discrete arguments only when the type of `args` is an actual tuple type. In this particular case, `args` is of a type that is *assignable* to a tuple type, but it isn't an *actual* tuple type. For that reason, arity checking assumes that the spread argument could be of any length, including zero, and therefore the arity check fails. Unfortunately, it would be non-trivial to do better here.
