### ISSUE TITLE
[feature-request] Interfaces should have the ability to require the presence of certain decorators on its members, and the classes it is applied to.

### ISSUE THREAD

**Issue by Bernd-L** [microsoft/TypeScript#40473]
Interfaces should have the ability to require the presence of certain decorators on its members, and the classes it is applied to.

This would allow the type checker to overcome the issues #4881 (and its duplicate #25119).

Notice: The above mentioned issues request the ability for decorators to modify the types of the stuff it's applied to, and to [allow decorators to implement interfaces](https://stackoverflow.com/q/43461756/5954839), while this issue aims to **allow interfaces to require decorators to be applied to some of the properties of the interface**.

**Comment by RyanCavanaugh** [comment]
The feature request template asks you to fill in a more complete picture of what you would like to see added to the language; off-the-cuff descriptions like this are hard for us to reason about. Please fill it in in a new issue.
