### ISSUE TITLE
Simple array access weirdly typed as 'any' 

### ISSUE THREAD

**Issue by kissge** [microsoft/TypeScript#40470]
**TypeScript Version:**  4.1.0-dev.20200910

**Search Terms:**
implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

**Code**

```ts
const x = [1, 2, 0];
let y: number | null = 0;
while (y != null) {
  const z = x[y];
  y = z;
}
```

**Expected behavior:**
No error.

**Actual behavior:**
Compile error: `'z' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.1.0-dev.20200910#code/MYewdgzgLgBAHjAvDA2gRgDQwExYAwC6A3AFAA2AprAJ4BcMYArgLYBGFATjAD4ONlkkMPKQDuACwCWlGAApqMAITImAgJQwA3iRgxQkWAC8hcFNWI6YC5IdIBfEkA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is a correct error (or at least, correct design limitation). The types of values that can inhabit `z` depend on what types of values inhabit `y`, which depend on which types of values can inhabit `z`, so a circularity exists. You can write `const z: number` to resolve the issue

**Comment by kissge** [comment]
Thanks for your reply. Would you mind if I ask why changing `while` to `if` resolves this error?

**Comment by RyanCavanaugh** [comment]
Because `z` wouldn't then depend on the value it indexed from `y` in the previous execution of the body

**Comment by AlCalzone** [comment]
When replacing while with if, y does not depend on z.

**Comment by kissge** [comment]
Hmm... Intuitively I thought declaring `y` as `number | null` and ensuring `y != null` would bring correct type inference, but the reality is when put inside while-loop, it wouldn't (beyond design limitation).
Thanks anyway.

**Comment by AlCalzone** [comment]
Well, it really depends on the value it had in the previous iteration. For TypeScript to check this, it would have to follow all loop iterations. In your case it can be reasoned that z must be a number and the while loop is infinite.

If you change your code to this:
```ts
const x = [1, 3, 0];
let y: number | null = 0;
while (y != null) {
  const z: any = x[y];
  y = z;
  console.log(typeof z);
}
```
you'll get
```
[LOG]: number 
[LOG]: number 
[LOG]: undefined 
```
