### ISSUE TITLE
Allow a BindingPattern in a BindingRestElement

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#4047]
Destructuring an AssignmentRestElement is allowed in TypeScript, but not so for a BindingRestElement:

``` ts
var a, b, c;
[a, ...[b, c]] = []; // allowed
var [d, ...[e, f]] = []; // Not allowed
```

This is in line with the released ES6 spec, but there is a movement to allow the BindingRestElement case. Many engines and transpilers do support it in fact. So we should allow it syntactically and make sure it is typed correctly.

**Comment by DanielRosenwasser** [comment]
Is

```TypeScript
[a, ...[b, c]] = [];
```

semantically different from the following?

```TypeScript
[a, b, c] = [];
```

**Comment by JsonFreeman** [comment]
Only in a pretty silly way. The first example collects the rest of the elements into an array before destrucutring that new array into `b` and `c`. The second one does not create an array, it just uses the existing one. As far as I can tell, there is absolutely no good use for this pattern, and the only purpose is to be consistent with AssignmentRestElement, which was useless to begin with.

**Comment by RyanCavanaugh** [comment]
This works now
