### ISSUE TITLE
Union Types Split Incorrectly When a Variadic Tuple Type is Used in a Conditional Type

### ISSUE THREAD

**Issue by DonIsaac** [microsoft/TypeScript#40486]
**TypeScript Version:**  4.0.2

**Search Terms:**
variadic tuple types
union types
ternary conditional types
union types split in conditional type

**Expected behavior:**
Each element in the union should not be split into its own type. E.g. the function parameter should be a union type, not the function itself

**Actual behavior:**
The function types are unioned together, where each parameter is one part of the union.

**Related Issues:** N/A

**Code**
```ts
// === Utility types

// True if T and U are the same type, false otherwise
type AreTypesEqual<T, U> = 
    (T extends U ? true : false) &
    (U extends T ? true : false)
;
// True if all three types are the same, false otherwise
type Are3TypesEqual <T, U, V> = AreTypesEqual<T, U> & AreTypesEqual<U, V>



// === The types to test

// An arity 1 function
type Arity1Function<T, U = void> = (arg: T) => U

// An arity N function, where N >= 0
type ArityFunction<T, U = void> = T extends [...infer R] 
    ? (...arg: R) => U
    : (arg: T) => U // Type breaks at this branch when T is a union type
;



// === The tests

// Works as expected
type Works1 = ArityFunction<[ p: boolean, q: boolean ]>
type Works2<A, E = A> = ArityFunction<[accumulator: A, currElem: E], A>

// A type of 'true' means the type is working as expected
type Works3 = AreTypesEqual<(...args: number[]) => void, ArityFunction<number[]>>
type Works4 = Are3TypesEqual<Arity1Function<number>, ArityFunction<number>, ArityFunction< [number]>>
type Works5 = Are3TypesEqual<Arity1Function<string>, ArityFunction<string>, ArityFunction< [string]>>
type Works6 = Are3TypesEqual<Arity1Function<object>, ArityFunction<object>, ArityFunction< [object] >>
type Works7 = AreTypesEqual<() => void, ArityFunction<[]>>
type Works8 = AreTypesEqual<
    false, // these two functions should not have the same type
    AreTypesEqual<ArityFunction<number[]>, ArityFunction< [number[]] >>>

// Union types break ArityFunction. The below 'NotEqual' types are expected to be 'true',
// but actually range between 'false', 'never', and 'boolean'
type Expected1 = Arity1Function<boolean> // booleans are technically the union of 'true' and 'false'
type Breaks1 = ArityFunction<boolean>
type TheseShouldBeEqual = AreTypesEqual<Expected1, Breaks1> // this should be 'false' but is actually never...

type Expected2 = Arity1Function<"a" | "b" | "c">
type Breaks2   = ArityFunction<"a" | "b" | "c">

type Expected3 = Arity1Function<number | undefined>
type Breaks3   = ArityFunction<number | undefined>
type NotEqual3 = AreTypesEqual<Expected3, Breaks3>

// This one gets its type set correctly, but compilation fails unexpectedly. Another bug?
type Expected4 = Arity1Function<number?>
type Breaks4 = ArityFunction<number?>
type NotEqual4 = AreTypesEqual<Expected4, Breaks4>
type NotEqual5 = AreTypesEqual<Arity1Function<number?>, Arity1Function<number | undefined>>

type NotEqual6 = AreTypesEqual<ArityFunction<number?>, ArityFunction<number | undefined>>
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// === Utility types

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/PTAEF5NBVAXBLANvWBPUaAOBTAzgKHxFABUAnAV21HgDNTQBDAOwBMYmzrYALa3RgFtuqHABpQtRolzUA9r2xkA7vFn4s1AIJcSovAFEAjhWkAeEhOgA+CKHyhHoABQlQ2AB6xsbXBwD8GJTUAFyS0rIAlKAAZA5OztDuXj6sfm6BsMGgYVIy2JH4ANxEYORUNPTSiBg8XCI4foxctfxC2BJ5sqAKfCpq2Br6oDrYAMx6jcamNRZWEgBqtuAjuvq40+aWMLYxq9iThibm0IvWhITEkCskfBjrGHIYeLCXYFrMnCjoAIySFMwAMYIOTMIY4VbfH4AMQBwPgoLmHBWADc5PBWMsXM0AOZhEjRcC2aBvEafZrfUAAOX+QJBzAkyj61Bp1hWAAZwdoyN9YXSEcwkUlUejMXY3J5vL5QABtAB0CvgzFoSlAACUALr2JygQLOBVy3FhNWE4nxRxhZxG0imjjEQ6gABGXEYAGsmrBamonWQWICeKAmT4GN7GKAAQL7jhihdShAoLduC8CHGAOpyMjuph+Tw4YHYVhc0DpzO4P4rHS8uH0swy0CYMKOuRyRDYFgSIyN5utligDXnTTFjPugBMZi0EgMdi0WMraD58MRMsYgMBFEEFEQjFgGbCE9Aa7IZAMrcEYQMGokM9JWij8noAHIslQH6BhCw-Io7zQ-Mph0qcWzZI828QtBxLd0xmnNYpmORAzH1BVcVwMJmHXR0lBlDVbTRDErx5edqwFMw0MEDCyCw6wB2GCDcAAFmg8ZDg2ODxwI1AYSIxFSPI6x8KrfluPQpQ+MhQjBMFWUeKUftqIhWiAFZGImdZNngucOIXGtcCyADRI0rTiJ0nlmBxfT2MMxFZWMgDZKLWiADZlOYtS2KhSzBTkR0ACtsGBcyBMXTyfL82AAvEoKzFlLzfOBLUqPs4dcAAdkYlzWOcHDRX4iKa0ouTqFogAONLVNY81wnyCRiEUbpYD-Wkgr8XAeDkTd2GYBRQB4RgUW4O4BGEO8KtGdKZjc3LiOkij+xy1APKimVpqw+KErjaBmEjTQ-GdNtXTE+auOYOVSDuDDEDkZRQAfKkFDU19ts4ahc1CgtHidagn2CB8xDjR0KE9FdYBmRB0F9UzqAw+rsGDB8umwH7ruYbA+rIRGWHYB8mxbNtmAfIsDA8ECC3LA7OIksxsZ7ZhbGIKncaaFpvH9TbAWqdAvwjUEekfZ8EaYNhrvh-HBwAIRdd1SYMo7Ke7XGCtOvBsAAZVa9rRewNTStg8bCeJ1gfgkcW9rLWmwF4b0WraxB2AwoWIn5-7PVDYEQfQZHUYNQhBz117WBHaD3JlgAiRhg9AAAfUBg8dcOo+DwFg4V423VwAPHArCyQ7DyPo9j3OE6T73hl9-NWCgzOg4p6bc4BVhsFoJUC2TiXcCgjODoWmuo7rhum8xItbtgNSK-2MbzFL0CxiN1uxnOONbm9UFqBxbBYD8FBP2GWRPUBDMuGBUGJCdg85EETAkG3SMpCQPwAResvQZOj5elVf6cX8Amib9hjK7QcnIrTX8C3E2v9O4yyAQrIeakwGjTKrrb+Zc6Iz1AVAu6cElKZwOPA8wGkAE1kgXNfBU1hJkFrmwPuyNMTz0HNAuCTksHj3UlnaupDgFzS7qQ8h9dG5UKokAA)

**Comment by Temurson** [comment]
It looks like this has nothing to do with variadic type tuples. In my opinion, it is caused by the use of `infer` and conditional types. Check out this [code](https://www.typescriptlang.org/play?#code/PTAEEkBdQGwezgawM6wJaIKagFYFdloBDABxJgE80A7Ac1BoDNMAnUZOAW0wAs4B3UJyJZUkHtjzU0caqEhxQAI2wATNIRZoleSJlWg4AN1byJoIixYD5FEpgBQIZZnj8ANKEwm54uHloeBjklOHFlFiJqAGMJVH5sHiITM2xkIm4zGnoog2pMNHFTABVQajg2ACULFmxvTDkCfXcnMCKhVkl02mw4RmDmNlionrFzWuQ8GEhs23sAOlbQAHUKlFB+QqCoijnJaVlDfuQ0AC9sWlqiPTZxKNAARkXIO2wABWto-TxagEFGG7gaiDB4AHmKAD5QABeUClTAADz01FUqAAFExTL8AJSgAD8oDRaNx0KhONAAC5CcSYVCjHA0KpsUsAMpnXr9doTKYzOigKQyOQaLwARzwRBg8kU7RO5yOqVAJGsRkZ+n5B2oi2cxXMiPs0T0Bhe9gYqGiMEwlkooAA5DTSWU8JwVGwAD7sSBaPnuuBKHCYA02zwqaJEJpw00WGD8IgUVBEZAnWjUIhKC1ShWYqxq37PV6gAAiTqUxVeDxhoA+cC+qh+mH+gOBrDB1GLpndmlmPr9AcgEKWvwN4slxswFKWRJJUM7dFx7sntMdztYc+pU8MPYNzKWAFkKtgs8g8yaqzW6w3WEDBgAmcGeACqUNh8KRDVRhKzoHJBLR968r5RdFPwAIVxH91wAbV+TxgIAXUpQl13pRlcSpBcHWQplWXZeUuUwSZplmAVDmFTAxQlDN2iVOBawNXDzFlfD6OwaiVVUNViOoI8lh1OoEX1Q09kjc1LRYa07Ugmd6HdVtlzdDd-QNTxZJdUAO09bJYJtY9sCLZ1S3sa8K1Pb4-gBS8mxYW8pLUpdVO7RTIGUtt5Kk-tnEHSBhz2cdnHQqEIKkzwpNg1d-NAQKNLoZy5NC2zwoglTWGCqLaDi+d7QCpKWBil10rXRcIN9RyUq9NKwsyiLit7XLWFChwgA).
```typescript
type ProcedureAfterInfer1<T> = T extends (infer A) ? (() => A) : (() => void)
// Size of the resulting union is equal to the size of the provided union.
// The expected type is clearly '() => number | string | object', because T is always assignable to the inferred A.
type DumbType1 = ProcedureAfterInfer1<number | string | object>
// Actual type:
// (() => string) | (() => number) | (() => object)

// More infers.
type ProcedureAfterInfer2<T, U> = T extends (infer A) ? (U extends (infer B) ? () => [A, B] : () => void) : (() => void)
// Size of the resulting union is equal to the product of the sizes of the provided unions.
// The expected type is clearly '() => [string | number | object, number | string]'.
type DumbType2 = ProcedureAfterInfer2<string | number | object, number | string>
// Actual type:
// (() => [string, string]) | (() => [string, number]) | (() => [number, string]) | (() => [number, number]) | (() => [object, string]) | (() => [object, number])
```

**Comment by RyanCavanaugh** [comment]
The testcase is not correct. Annotated:
```ts
type AreTypesEqual<T, U> = 
    (T extends U ? true : false) &
    (U extends T ? true : false)
;

type And<T, U> = T extends true ? U extends true ? true : false : false;
// This definition was wrong; & is not "logical and" in type space. This type was producing
// 'never' when its intermediate operands were 'true' and 'false', instead of 'false'
type Are3TypesEqual <T, U, V> = And<AreTypesEqual<T, U>, AreTypesEqual<U, V>>;


type Arity1Function<T, U = void> = (arg: T) => U

// You didn't want this to be distributive, so it was missing [] around its leading infers
type ArityFunction<T, U = void> = [T] extends [[...infer R] ]
    ? (...arg: R) => U
    : (arg: T) => U // Type breaks at this branch when T is a union type
;


type Works1 = ArityFunction<[ p: boolean, q: boolean ]>
type Works2<A, E = A> = ArityFunction<[accumulator: A, currElem: E], A>

type Works3 = AreTypesEqual<(...args: number[]) => void, ArityFunction<number[]>>
type Works4 = Are3TypesEqual<Arity1Function<number>, ArityFunction<number>, ArityFunction< [number]>>
type Works5 = Are3TypesEqual<Arity1Function<string>, ArityFunction<string>, ArityFunction< [string]>>
type Works6 = Are3TypesEqual<Arity1Function<object>, ArityFunction<object>, ArityFunction< [object] >>
type Works7 = AreTypesEqual<() => void, ArityFunction<[]>>
type Works8 = AreTypesEqual<
    false, // these two functions should not have the same type
    AreTypesEqual<ArityFunction<number[]>, ArityFunction< [number[]] >>>

type Expected1 = Arity1Function<boolean>
// Now has type (arg: boolean) => void
type Breaks1 = ArityFunction<boolean>
// Is now 'true'
type TheseShouldBeEqual = AreTypesEqual<Expected1, Breaks1> // this should be 'false' but is actually never...

type Expected2 = Arity1Function<"a" | "b" | "c">
// Is now (arg: "a" | "b" | "c") => void
type Breaks2   = ArityFunction<"a" | "b" | "c">

type Expected3 = Arity1Function<number | undefined>
type Breaks3   = ArityFunction<number | undefined>
// Is 'true' now
type NotEqual3 = AreTypesEqual<Expected3, Breaks3>

// "number?" isn't a thing in TypeScript, what are you doing?
// This is just a syntax error.
type Expected4 = Arity1Function<number?>
type Breaks4 = ArityFunction<number?>
```

**Comment by DonIsaac** [comment]
@RyanCavanaugh The `Are3TypesEqual` was just a utility type - it's not actually part of the bug.

As for this working as intended, do you really mean to tell me that this is intended? @Temurson figured out that variadic tuples actually have nothing to do with this bug. To me, this feels wrong

```ts
// Snippet from Temurson's comment
type ProcedureAfterInfer1<T> = T extends (infer A)
    ? (() => A)
    : (() => void);
// Size of the resulting union is equal to the size of the provided union.
// The expected type is clearly '() => number | string | object', because T is always assignable to the inferred A.
type DumbType1 = ProcedureAfterInfer1<number | string | object>
// Actual type:
// (() => string) | (() => number) | (() => object)
```

**Comment by RyanCavanaugh** [comment]
I do really mean to tell you that, yes. Conditional types over a bare type parameter are distributive, so `Foo<T | U | V>` is the same as `Foo<T> | Foo<U> | Foo<V>`. If you want a non-distributing conditional type, you are free to write one:
```ts
// Nondistributing union type
type ProcedureAfterInfer1<T> = [T] extends [(infer A)]
    ? (() => A)
    : (() => void);
// This produces the desired type
type SmartType1 = ProcedureAfterInfer1<number | string | object>
```

**Comment by DonIsaac** [comment]
I see what you're saying, but shouldn't these two types be equal then? It looks like the type system automatically distributes in the conditional branch during the assignment, but doesn't account for this when checking for equality

```ts
type Expected3 = Arity1Function<number | undefined>
// => (arg: number | undefined) => void
type Breaks3   = ArityFunction<number | undefined>
// => (arg: number) => void | (arg: undefined) => void
type NotEqual3 = AreTypesEqual<Expected3, Breaks3>
// => never
let b: Expected3 = (s => undefined) as Breaks3
// Throws a type error
```

**Comment by RyanCavanaugh** [comment]
Which definitions of the helper aliases are you using in that snippet?

**Comment by DonIsaac** [comment]
Definitions are from the original/first snippet

**Comment by RyanCavanaugh** [comment]
As noted in my original reply, those definitions are wrong because they are distributive when you say you don't want them to be
