### ISSUE TITLE
vscode intellisense import from src in typescript project

### ISSUE THREAD

**Issue by wizardnet972** [microsoft/TypeScript#40484]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20200910

**Search Terms**
- paths
- tsconifg 
- auto import

---

Version: 1.49.0-insider (user setup)
Commit: e4256dd1a02339bb1d56647ecd9134bf38bc7c03
Date: 2020-09-04T18:49:12.955Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**This is another problem** with vscode intellisense. the vscode intellisense import from src folder. see "Steps to Reproduce".

Steps to Reproduce:

1. `mkdir ts && cd ts`
2. `npm init -y`
3. `npm i typescript -g`
4. `tsc --init`
5. add this code to tsconfig.json:
```
baseUrl: "./",
paths: {
 "@test/*: ["apps/*/src"]
}
```
5. create folder and index file: `apps/barr/src/index.ts`.
6. write this code `export const barr = 1; ` in `apps/barr/src/index.ts`.
7. create test.ts in the root of the project: `barr`.
8. try to import using vscode intellisense- you will get `import { barr } from "@test/barr/src"`. which is wrong. it should be: `@test/barr`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Example repo: https://github.com/mjbvz/ts-40484

**Comment by h3llrais3r** [comment]
I'm having the same issue. Every time I I use the auto import, it adds the import with the leading `/src` in the import.

**Comment by andrewbranch** [comment]
This was fixed in TypeScript 4.3.
