### ISSUE TITLE
ConvertToTypeOnlyExport codefix duplicates leading comments

### ISSUE THREAD

**Issue by Blasz** [microsoft/TypeScript#40489]
**TypeScript Version:**  3.9.6, 4.1.0

**Search Terms:** TS1205 re-exported type-only exports codefix duplicate leading comments

**Code**

```ts
// @isolatedModules: true

// @Filename: /a.ts
export type A = {};
export type B = {};

// @Filename: /b.ts
/* Comment */
export { A, B } from './a';
});

```

Create the structure above and apply the 'Convert to type-only' codefix via VSCode or by calling through the TS Language Service directly.

**Expected behavior:**

```ts
/* Comment */
export type { A, B } from './a';
```

**Actual behavior:**

```ts
/* Comment */
/* Comment */
export type { A, B } from './a';
```

**Related Issues:**

**Comment by andrewbranch** [comment]
Fixed by #40490
