### ISSUE TITLE
Comparison operator error message misleading

### ISSUE THREAD

**Issue by denis-sokolov** [microsoft/TypeScript#40496]
Comparing a string to a number generates a TypeScript error saying we can not apply a comparison operator to strings with numbers. This is misleading, since if I truly could not apply a comparison operator to strings with numbers, I could not do that even if a string is part of a bigger union. This results in a perceived inconsistency:

```tsx
const s = "s"
if (s > 0) {} // Comparing strings to numbers, TypeScript error “can not do that”

const u = (0 as number | string)
if (u > 0) {} // Comparing strings to numbers sometimes, no TypeScript error
```

The real motivation behind the compiler warning is not the concern about comparing incomparable types, but rather that comparing strings to numbers results in a constant condition. (https://github.com/microsoft/TypeScript/issues/13863#issuecomment-277321071) This resolves the inconsistency between the two similar pieces of code, but it introduces an inconsistency between the error message and the error meaning.

If it was possible to rephrase the error to say “This condition will always return false” or “This condition is constant”, like in case of `if (0 !== "")`, the motivation would be immediately self-evident and not mislead.

**TypeScript Version:**  v4.1.0-insiders.20200910 
**Search Terms:** operator can not be applied, number, bigger, less, comparison operator, union.
**Code**
```ts
const s = "s"
if (s > 0) {}
```
**Expected behavior:** An error “This condition will always return false” on line 2.
**Actual behavior:** An error “Operator '>' can not be applied to types 'number | string' and 'number'” on line 2.
[**Playground Link**](https://www.typescriptlang.org/play?ts=4.1.0-insiders.20200910#code/PTAEGcBcCcEsDsDmAoAxge3lCoC8oAicA5WAM1AApxQA+UABgEpQBvAX2WRAhgUVDwArgFsARgFNooIfFiY0mbELxUGoAIY1h4qaAA+vOEiakKlFfWZtOXHlGMDZ8+IqyQIK-JQIFNNIj9DIgAmAlNyKnBLRhYOOzAxdHQAGwkNVwx3UDFVGCEJMypcqzjbHiTU9PgZOQUs7DEvKnyJf1BWg1AQiPMmulibBJzktIyjflqXN0bo1R8-LQ7oAq7Q8KLKMTnSoaA)
**Related Issues:** #13683

**Comment by denis-sokolov** [comment]
My personal preference would be to resolve the original issue and prevent comparisons across types, which would make this issue moot. But the motivation described in that issue to allow such code patterns seems reasonably decided.

**Comment by RyanCavanaugh** [comment]
See #26592

**Comment by denis-sokolov** [comment]
#26592 seems very related, but I’m not sure if it’s a duplicate. That issue talks about getting a “will always return 'false'” when not expected, whilst I require the opposite. It still makes sense if you want to group them there, I just double check that you’ve not misread my issue description.

**Comment by RyanCavanaugh** [comment]
I think if we're doing something with these messages, we should address them as a group, yes.
