### ISSUE TITLE
TS2322 error when used conditional type within function with generic itself

### ISSUE THREAD

**Issue by setdvd** [microsoft/TypeScript#40497]
**TypeScript Version:**  

3.7.2 - 4.0.2 up to Nightly 

**Code**

```ts
type Params<P = null> = P extends null ? {} : { params: P } 

const a: Params<string> = { params: 'x' }; // OK

const b = <P extends {}>( x: P ):Params<P> =>{
    return {params: x}     // Error Type '{ params: P; }' is not assignable to type 'Params<P>'.
}
```

**Expected behavior:**
P is an object by restriction of b generic type so I expect I can safely constract Params type.

the idea behind Params type is to provide conditionally a property if user specify generic eg 

```ts
type Loadable<T, P = null> = {data: T } & Params<P>
const data:LoadableData<User> = {data: user}
const dataWithParam:LoadableData<User[], Role> = {data: user, params: role} 
```

and I cannot use Loadable type inside function with generic :( 

**Actual behavior:**

Error is produced when Prams type is used inside function that have generic itself

**Playground Link:**

https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.0.2#code/C4TwDgpgBACghgJzgWwM4B4ZQLxQHYCuANkQHw6xQQAewEeAJqvsUVAPxQDeAvlAFzcwiFKkEw+AKEkBjAPZ5UwKHHEi06JQgCWeAOblcXYUjSCA5NXM8A3NPmLlAIwqYqtek249SACmr8MACUgeoYMIakXJJQsVAIEMAECHhCYYLUPJI8QA

Thank you for any help

**Comment by RyanCavanaugh** [comment]
See #30639

**Comment by SowingSadness** [comment]
@typescript-bot reopen
