### ISSUE TITLE
No watch file when extraFileExtensions on WatchCompilerHost 

### ISSUE THREAD

**Issue by yoyo930021** [microsoft/TypeScript#40495]
**TypeScript Version:**  3.9 up

**Search Terms:**
extraFileExtensions, WatchCompilerHost, vue

**Code**
https://github.com/yoyo930021/TypeScript/blob/970d435c8d5848a369b5516a5e597f63f50afae6/src/testRunner/unittests/tscWatch/watchApi.ts#L127
The code is a test about this.
When filename ends with `ts`, It is pass,
but filename ends with `vue`, it isn't pass.

**Expected behavior:**
The test is pass.

**Actual behavior:**
The test is not pass.

**Playground Link:** 
No

**Related Issues:** 
No

The `typescript-eslint` tool is broken when vue with typescript 3.9.
The @sheetalkamat add a PR to fix it in https://github.com/microsoft/TypeScript/pull/37726.
But this PR is only work in startup.
When we add a new file, The WatchCompilerHost isn't watch this.

ref: https://github.com/typescript-eslint/typescript-eslint/issues/2127

**Comment by sheetalkamat** [comment]
I dont understand this issue. We have a test https://github.com/yoyo930021/TypeScript/blob/970d435c8d5848a369b5516a5e597f63f50afae6/src/testRunner/unittests/tscWatch/watchApi.ts#L156 as you pointed out that passes where new .vue file is detected and added to the program

**Comment by sheetalkamat** [comment]
Oh Sorry about that. i thought the test you pointed is already in there so thats where confusion came from.

**Comment by yoyo930021** [comment]
Thanks.
I tested well with `typescript-eslint` and Vue files.
When will this fix be released?

**Comment by sheetalkamat** [comment]
@DanielRosenwasser can we pick this for 4.1 ?

**Comment by DanielRosenwasser** [comment]
If you already merged it into `master`, it already has been 😅
