### ISSUE TITLE
Compiler output includes __exportStar for a type definition file

### ISSUE THREAD

**Issue by zemse** [microsoft/TypeScript#40517]
**TypeScript Version:**  Version 4.1.0-dev.20200911

**Search Terms:**  __exportStar includes type definition, runtime module not found

**Code** 

This problem is specific to a file structure

1. There is a type definition file: `type.d.ts`
```ts
export interface Hello {
  intensity: number;
}
```

2. A normal ts file that exports a number: `const.ts`
```ts
export const constant = 12;
```

3. A file named `index.ts` that exports all from `type.d.ts` and `const.ts`
```ts
export * from './type';
export * from './const';
```

The above three files are in the directory `dependencies`.

4. A file named `main.ts` that consumes `index.ts`:
```ts
import { Hello, constant } from './dependencies';

let hello: Hello = {
  intensity: 123,
};

console.log(hello.intensity, constant);
```

Then we compile the files

```sh
$ tsc main.ts
```

**Expected behavior:**

```sh
$ node main.js
123 12
```

**Actual behavior:**

Running throws error

```sh
$ node main.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module './type'
Require stack:
- <path-to-dir>/types-import-problem/dependencies/index.js
- <path-to-dir>/types-import-problem/main.js
```

This error is caused due to unwanted `__exportStar ` at https://github.com/zemse/types-import-problem/blob/master/dependencies/index.js#L13

**Playground Link:** 

Actually, since this is reproducible with multiple files, I didn't find a feature to do that with playground.

I've created a repository: https://github.com/zemse/types-import-problem

**Comment by RyanCavanaugh** [comment]
If you tell TypeScript that a module named `"./type"` exists by writing a file called `types.d.ts`, TypeScript will believe you

**Comment by zemse** [comment]
> If you tell TypeScript that a module named "./type" exists by writing a file called types.d.ts, TypeScript will believe you

I think I understand this that typescript thinks that a `.js` file might be present over there.
