### ISSUE TITLE
Add `0` for unreachable codes by condition

### ISSUE THREAD

**Issue by jdbruxelles** [microsoft/TypeScript#40515]
For the example below:
```javascript
if (false) { console.log("ok") }
```
The editor tells us that the `console.log` instruction is unreachable because the condition is always `false`, but it does not do the same when it comes to:
```javascript
if (0) { console.log("ok") }
if (null) { console.log("ok") }
if (undefined) { console.log("ok") }
```
While here too they are unreachable.

This is not a bug and surely not useful for everyone, but I just wanted to point it out. Thanks.

**Comment by mjbvz** [comment]
Confirmed with 4.1.0-dev.20200911:

<img width="671" alt="Screen Shot 2020-09-11 at 5 16 44 PM" src="https://user-images.githubusercontent.com/12821956/92982357-a3279f80-f452-11ea-91df-02473a352343.png">

**Comment by RyanCavanaugh** [comment]
I don't think we need to track "here's something I noticed" bugs. No one would write this.

**Comment by jdbruxelles** [comment]
I don't think too. Ok.
