### ISSUE TITLE
Convert to optional chaining doesn't show up for expressions with bracket accessor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#40510]
**TypeScript Version:** 4.1.0-dev.20200911

**Search Terms:**

**Repro**
For the code:

```ts
const a = { b: { c: 1 } }
if (a && a.b && a.b['c']) {
    
}
```

Select `a && a.b && a.b['c']`.

**Expected behavior:**
Convert to optional chaining refactoring is available. It would result in:

```ts
const a = { b: { c: 1 } }
if (a?.b?.['c']) {
    
}
```

**Actual behavior:**
No refactoring available

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
