### ISSUE TITLE
Ensure declaration emit doesn't crash for element accesses

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40519]
Quick question: what's our declaration emit for 
```ts
function D () { }
exports["D space"] = D;
```
?
I don't think we have a good thing we can compile it to? (Maybe an export assignment, but it'd be lossy at best)

_Originally posted by @weswigham in https://github.com/microsoft/TypeScript/pull/40514#issuecomment-691427271_

**Comment by RyanCavanaugh** [comment]
Also tracking at https://github.com/microsoft/TypeScript/issues/40540

**Comment by weswigham** [comment]
#40540 tracks this (and already acknowledges that we don't crash, we just make bad output).
