### ISSUE TITLE
Type narrowing with instanceof on an array element does not restrict its type when using a variable index

### ISSUE THREAD

**Issue by raphj** [microsoft/TypeScript#40516]
I hope this is not a duplicated or a work as intended issue. I've done my best looking at the existent issues.

With the following MWE:

```ts
class A { public a: number = 1; }
class B { public b: number = 1; }

const abList: (A|B)[] = [];

let i = 0;
if (abList[i] instanceof A) abList[i].a === 1
```

I get on the typescript nightly playground:

```
  Property 'a' does not exist on type 'A | B'. Property 'a' does not exist on type 'B'.
```

Replacing `[i]` by `0` works.

**Expected behavior:**
The type of `abList[i]` should be narrowed to A in the `if` body.
 
**Actual behavior:**
The type of `abList[i]` is not narrowed.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200911#code/MYGwhgzhAECC0G9oAcCuAjEBLY0wC5oA7VAW3QFMAnaAXmgEYBuaAXwChRIYAhRFDNlzpCJctTqMWHTgHsiEAC550AGSxLCAClgAfHgEoA2gF1Jppu3YgKyrJIAMlrADNoWsGo2KjDs1gVFMCJgClk3WAMVdSVfEwA6MDpaegYgA

**Related Issues:** Could not find any

**Comment by SancheZz** [comment]
I think TS cannot infer a type of a random element of an array. You should store ref to the element in variable and check It.
[play](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200911#code/MYGwhgzhAECC0G9oAcCuAjEBLY0wC5oA7VAW3QFMAnaAXmgEYBuaAXwChRIYAhRFDNlzpCJctTqMWHTgHsiEAC550AGSxLCAClgAfHgEoA2gF1JppuzkLlWSQAZLweUugUQFUhSLL6YNRqKRlgmluxYAGbQWu6e3rY2YETAFLJRsAaI7NA5bh5ePgB0YHS09AzsrEA)

**Comment by MartinJohns** [comment]
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by raphj** [comment]
Sorry for the duplicate! I missed the "bracket notation" keywords here.
