### ISSUE TITLE
Mixin like in Dart

### ISSUE THREAD

**Issue by cindRoberta** [microsoft/TypeScript#40528]
just copy the mixin of Dart language, it's excellent

**Comment by RyanCavanaugh** [comment]
Please don't post low-effort suggestions like this.

**Comment by cindRoberta** [comment]
> Please don't post low-effort suggestions like this.

@RyanCavanaugh I don't understand how this suggestion is low-effort, the Danes have already documented all on the Google Dart documentation: https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins

high-effort would be a PR? I know that Typescript have already mixin but it use a lot of boilerplate

**Comment by DanielRosenwasser** [comment]
You didn't even follow the issue template and guidelines.
