### ISSUE TITLE
Finding export references is slow

### ISSUE THREAD

**Issue by jp7837** [microsoft/TypeScript#40520]
**TypeScript Version:**  4.0.2

**Search Terms:** export references slow

**Code**

```js
const fs = require("fs");
const ts = require("typescript");
const path = require("path");

// Copied from https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services
function getLanguageService(rootFileNames, options) {
	const files = {};

	// initialize the list of files
	rootFileNames.forEach(fileName => {
		files[fileName] = { version: 0 };
	});

	// Create the language service host to allow the LS to communicate with the host
	const servicesHost = {
		getScriptFileNames: () => rootFileNames,
		getScriptVersion: fileName => files[fileName] && files[fileName].version.toString(),
		getScriptSnapshot: fileName => {
			if (!fs.existsSync(fileName)) {
				return undefined;
			}

			return ts.ScriptSnapshot.fromString(fs.readFileSync(fileName).toString());
		},
		getCurrentDirectory: () => process.cwd(),
		getCompilationSettings: () => options,
		getDefaultLibFileName: options => ts.getDefaultLibFilePath(options),
		getProjectVersion: () => 1,
		fileExists: ts.sys.fileExists,
		readFile: ts.sys.readFile,
		readDirectory: ts.sys.readDirectory,
	};

	// Create the language service files
	const services = ts.createLanguageService(servicesHost, ts.createDocumentRegistry());

	return services;
}

const tsconfigPath = path.resolve(__dirname, "../../tsconfig.json");
const basePath = path.resolve(path.dirname(tsconfigPath));
const parseJsonResult = ts.parseConfigFileTextToJson(tsconfigPath, fs.readFileSync(tsconfigPath, { encoding: "utf8" }));
const tsConfig = ts.parseJsonConfigFileContent(parseJsonResult.config, ts.sys, basePath);
const services = getLanguageService(tsConfig.fileNames, tsConfig.options);

tsConfig.fileNames
	.forEach(file => {
		const source = ts.createSourceFile(file, fs.readFileSync(file, { encoding: "utf8" }));
		ts.forEachChild(source, node => {
			if (ts.isExportDeclaration(node)) {
				if (node.exportClause) {
					node.exportClause.elements.forEach(element => {
						const references = services.findReferences(file, element.name.end - 1);
						console.log(references.length);
					});
				}
			}
		});
	});

```

**Expected behavior:** Call to `services.findReferences` is fast (under 25ms, let's say)

**Actual behavior:** Call to `services.findReferences` is slow (over 200ms)

**Playground Link:** N/A since this is TS language code (let me know if I can replicate this on the playground)

**Related Issues:** None found

**Comment by jp7837** [comment]
Calling `services.findReferences` on things like public class methods is quite fast, but it seems we are creating the import map on every invocation (`getReferencedSymbolsForSymbol` creates a new `State` object every time and eventually calls `createImportTracker`).  Is it possible to cache the `State` object per language service instance?

**Comment by sheetalkamat** [comment]
we would need sample code that you are running this on to see what's going on in detail 
But state is very specific to reference you are finding so its not easily cacheable .. 
I looked into caching `getDirectImportsMap` but i dont think that is worth the benefit either in most use cases that we have seen (it has never come up except in your scenario where you are finding references on all export clauses which isnt a common scenario)
The main issue is storing this state means you need to handle file set it was invoked with and it also depends on checker so all the places we have to handle the change in checker which is cancellation token and that has its own cost (we shouldn't be holding onto checker to be checked later as that can result in not releasing the memory for types for long time so its not as simple as whenever someone asks for this map, check if checker is same)

So if you have a scenario code that shows that at certain location find all references is slow, please file a issue with all the details and we can investigate that but at this point i dont think we can do any type of additional caching that you are suggesting.
