### ISSUE TITLE
Union types from namespaces [feature request]

### ISSUE THREAD

**Issue by cbdeveloper** [microsoft/TypeScript#40539]
## Search Terms

union, namespace, utility type

## Suggestion

I've looked around and it doesn't seem to be possible to get all members (types and interfaces) of a `namespace` as a union type. **I have no idea if this is feasible or not**, but I think it might help other people. Seen some question on StackOverflow on this topic.

## Use Cases

My use for this would be in redux, when I'm type checking actions and action creators. The redux [documentation](https://redux.js.org/recipes/usage-with-typescript#type-checking-actions--action-creators) suggests that you type check your actions and manually add each action to a group of related actions, for example:

```
// src/store/chat/types.ts
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'

interface SendMessageAction {
  type: typeof SEND_MESSAGE
  payload: Message
}

interface DeleteMessageAction {
  type: typeof DELETE_MESSAGE
  meta: {
    timestamp: number
  }
}

export type ChatActionTypes = SendMessageAction | DeleteMessageAction
```

## Examples

The way I'm currently working, I declare all actions for that state "slice" inside a namespace called `ACTIONS`. And I though it would be nice if there was a way of dynamically getting the union type of all types inside the `ACTIONS` namespace, instead of building it manually.

Don't know if it could be accomplished by a utility type, or something else would work better.

```
declare namespace SOME_STATE_SLICE {

  namespace ACTIONS {
    type ACTION_1 = {
      type: "ACTION_1",
      payload: PAYLOAD1
    }

    interface ACTION_2 {
      type: "ACTION_2",
      payload: PAYLOAD2
    }
  }

  // HERE IS HOW IT COULD WORK
  type ACTIONS_UNION = UnionType<ACTIONS>   // THIS SHOULD BE:  ACTION_1 | ACTION_2

}
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**PS:** I'm not 100% sure, but I think it meets all guidelines.

**Comment by RyanCavanaugh** [comment]
There are a bunch of ways you could do this. Here's one
```ts
namespace SOME_STATE_SLICE {
    export interface PAYLOAD1 { name: string }
    export interface PAYLOAD2 { data: number }
    export const A_1 = "ACTION_1";
    export const A_2 = "ACTION_2";
    interface Payloads {
        [A_1]: PAYLOAD1;
        [A_2]: PAYLOAD2;
    }
    export type Action1 = Payloads[typeof A_1];
    export type Action2 = Payloads[typeof A_2];
    
    type Actions = {
        [K in keyof Payloads]: {
            type: K;
            payload: Payloads[K]
        }
    }
}
```
