### ISSUE TITLE
Types for the Screen Wake Lock API

### ISSUE THREAD

**Issue by chrismilson** [microsoft/TypeScript#40534]
## Search Terms

wake screen lock wakelock

## Suggestion

I would like to have `Navigator.wakeLock` types.

## Use Cases

This would be used when interacting with the [Screen Wake Lock API](https://w3c.github.io/screen-wake-lock/).

## Examples

```ts
/**
 * Attempts to obtain a screen lock, according to the [Screen Wake Lock
 * API](https://w3c.github.io/screen-wake-lock/). If successful, returns a
 * callback to release the lock.
 */
const lockScreen = async (): Promise<undefined | (() => void)> => {
  if ('wakeLock' in navigator) {
    try {
      const sentinel = await navigator.wakeLock.request('screen');

      console.log('Screen lock obtained.');

      return () => {
        sentinel.release();
        console.log('Screen lock released.');
      }
    } catch (error) {
      // Wake lock was not allowed.
      alert(error);
    }
  }
};
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Extra information

I would like to do a pull request for this.

**Comment by chrismilson** [comment]
Here is [the relevant code](https://github.com/microsoft/TypeScript/blob/bbf26a07eb2ad8c5e117d6128f01e0a4c31f5687/lib/lib.dom.d.ts#L10670).

**Comment by kitsonk** [comment]
They are experimental APIs not widely adopted and only [recently in browsers](https://chromestatus.com/feature/4636879949398016).  These are not suitable to be added to the default libraries until they are widely adopted.

Interfaces are open ended and can easily be extended by users and/or this is a good opportunity to contribute to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) which is a better home for experimental not widely adopted APIs.

**Comment by chrismilson** [comment]
Thanks @kitsonk!

**Comment by blesswinsamuel** [comment]
Came across this issue on googling. Found the types for wake lock API on DefinitelyTyped.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dom-screen-wake-lock

```
npm i @types/dom-screen-wake-lock
```
