### ISSUE TITLE
noUncheckedIndexedAccess doesn't work

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40531]
Basically the flag rename didn't go through. We check for a non-existent in the checker: https://github.com/microsoft/TypeScript/pull/39560/files#diff-c3ed224e4daa84352f7f1abcd23e8ccaR13645

**Comment by muster-mark** [comment]
noUncheckedIndexedAccess still doesn't do anything in 4.6.3
