### ISSUE TITLE
export * from './localstorage, ./routes'

### ISSUE THREAD

**Issue by fireflysemantics** [microsoft/TypeScript#40530]
Instead of:
```
export * from './localstorage'
export * from './routes'

```

Do:

```
export * from './localstorage, ./routes'
```

**Comment by kitsonk** [comment]
If you want changes to the semantics of JavaScript you should advocate for such a change with TC39 and/or [ESDiscuss](https://esdiscuss.org/). The TypeScript issue tracker is not the right place.

That being said, having to have a string "magically" delimitated and resolved is likely to never be accepted by TC39.

**Comment by RyanCavanaugh** [comment]
This is out of scope and also not going to happen - module specifiers are effectively opaque, so `,` is syntactically legal and could be being used already.
