### ISSUE TITLE
Wrong in type guard spec 

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#4053]
I just stumbled up on the spec for type guard and just saw these two paragraphs:

>In the true branch statement of an 'if' statement, the type of a variable or parameter is narrowed by a type guard in the 'if' condition when true, provided the true branch statement contains no assignments to the variable or parameter.

>In the false branch statement of an 'if' statement, the type of a variable or parameter is narrowed by a type guard in the 'if' condition when false, provided the false branch statement contains no assignments to the variable or parameter.

And I think this is wrong:

> provided the true branch statement contains no assignments to the variable or parameter.

Shouldn't it be?
```
provided the whole if statement contains no assignments to the variable or parameter.
```

In this test [file](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/conformance/expressions/typeGuards/typeGuardsInIfStatement.ts)  there is assignments both in the true branch and false branch:

```typescript
function foo(x: number | string) {
    if (typeof x === "string") {
        return x.length; // string
    }
    else {
        return x++; // number
    }
}
function foo2(x: number | string) {
    // x is assigned in the if true branch, the type is not narrowed
    if (typeof x === "string") {
        x = 10;
        return x; // string | number
    }
    else {
        return x; // string | number
    }
}
function foo3(x: number | string) {
    // x is assigned in the if true branch, the type is not narrowed
    if (typeof x === "string") {
        x = "Hello"; // even though assigned using same type as narrowed expression
        return x; // string | number
    }
    else {
        return x; // string | number
    }
}
function foo4(x: number | string) {
    // false branch updates the variable - so here it is not number
    if (typeof x === "string") {
        return x; // string | number
    }
    else {
        x = 10; // even though assigned number - this should result in x to be string | number
        return x; // string | number
    }
}
```

**Comment by ahejlsberg** [comment]
Fixed in current copy of spec.
