### ISSUE TITLE
Common generic parameter type inference doesn't work for derived parameter types

### ISSUE THREAD

**Issue by outring** [Microsoft/TypeScript#4054]
Consider following definitions:
```
class BaseClass<T> {
}

class DerivedClass extends BaseClass<number> {
}

function usingParameters<T>(c:BaseClass<T>, p:T) {
}
```

In `usingParameters(new BaseClass<number>(), "string")` call common type inference works well and as a result can't infer common generic parameter type and compiler fails with error.

In `usingParameters(new DerivedClass(), "string");` call common type inference doesn't seem to check if `DerivedClass` derives exactly from `BaseClass<string>` or that `"string"` is not `number` and everything compiles well.

The same thing about object notation
```
interface IParameters<T> {
	c: BaseClass<T>,
	p: T
}

function usingObject<T>(IParameters<T>) {
}

usingObject({ c: new BaseClass<number>(), p: "string" }); //Fails
usingObject({ c: new DerivedClass(), p: "string" }); //Compiles
```

**Comment by RyanCavanaugh** [comment]
The problem here is that `BaseClass` doesn't have any members of type `T`. So in terms of a structural type system, `class DerivedClass extends BaseClass<number>` is the same as `class DerivedClass extends BaseClass<Rocket>` -- they have identical members.

If you add a member of type `T` to `BaseClass`, everything works like you expect. In practice, you should *never* have an unconsumed generic type parameter, as it's completely meaningless.

**Comment by outring** [comment]
I'm terribly sorry, the real code has the generic member and it doesn't work as expected too, and I thought that the code above is equivalent. The problem in my real code must be somewhere else, I'll try to figure out where. Thank you!

**Comment by outring** [comment]
Ok, it seems that I have isolated the real problem and it is applies only to objects and, what is the most important, nested objects.

```
class BaseClass<T> {
	p:T;
}

class DerivedClass extends BaseClass<number> {
}

interface IParameters<T> {
    c: BaseClass<T>,
    p: T,
	content?: IParameters<any>
}

function usingObject<T>(p:IParameters<T>) {
}

usingObject({ 
	c: new BaseClass<number>(),
	p: 1,
	content: {  //Must fail
		c: new BaseClass<number>(), 
		p: "string"
	}
});

usingObject({ 
	c: new DerivedClass(), 
	p: 1,
	content: {  //Must fail
		c: new DerivedClass(),
		p: "string"
	}
});
```

In the example above, `content` property is incorrect and must not typecheck, but it does. I can imagine, that there could be the performance problem when typechecking such structures, so maybe there is another common way to build typesafe nested structures?

**Comment by RyanCavanaugh** [comment]
The example is working as intended because `content` is defined as `IParameters<any>`, so `content.p` is of type `any` and `content.c` is of type `IParameters<any>`.

You can tweak the example a little and get correct errors:
```ts
interface IParameters<T> {
    c: BaseClass<T>,
    p: T,
    content?: IParameters<T>
}

function usingObject<T>(p:IParameters<T>): T {
	return null;
}

let a = usingObject({ 
    c: new BaseClass<string>(),
    p: '1',
    content: {  //Must fail
        c: new BaseClass<string>(), 
        p: '32'
    }
});

let b = usingObject({ 
    c: new DerivedClass(), 
    p: 1,
    content: {  //Must fail, does
        c: new DerivedClass(),
        p: "string"
    }
});
```

**Comment by outring** [comment]
Got it, thank you. But the problem is that the `content: IParameters<T>` could not share parent's `T`, there could be any other type and it seems that there's no way to say, the the `T` could be `any`, but only certain `any` :(

**Comment by RyanCavanaugh** [comment]
Is this closer to what you want?

```ts
interface IParameters<T, U> {
    c: BaseClass<T>,
    p: T,
    content?: IParameters<U, any>
}
```

**Comment by outring** [comment]
Yep, I've already tried that, but it works only for 2 levels of nesting :)

**Comment by outring** [comment]
But now I got it, and it seems, that there is no easy way to achieve what I want. Ideal solution is possibility to constrain any to single type which requires proposition and possibly violates some of the type system concepts :D
For now I'll try to solve it another way. Thank you very much!
