### ISSUE TITLE
New features of Typescript 1.6 has still a syntax error highlight in Webstorm

### ISSUE THREAD

**Issue by thakerng** [Microsoft/TypeScript#4055]
I have configured the Typescript compiler in Preferences point to built/local folder of Typescript 1.6 built with Jake.  the features such as abstract class , generator function have a syntax error highlight even through compiling has no any errors

**Comment by mhegazy** [comment]
what is the value of your `--target` flag? generators are only supported on `--target ES6` at the moment. the ES5/ES3 support is in the making right now, and would not be available in master for a few weeks.

**Comment by RyanCavanaugh** [comment]
Crosspost http://stackoverflow.com/questions/31683330/how-to-update-syntax-error-checking-of-typescript-1-6-manually-in-webstorm

**Comment by thakerng** [comment]
I've already set the command line options to be `--target ES6`
sorry about the crosspost, I'm not sure this issue is about Webpack or Typescript ,I've ever found the issue of syntax error highlight of Destructuring feature in Typescript 1.4 When Typescript 1.5 had come ,that feature became available the syntax error highlight of Destructuring feature in Webstorm disappeared. So, I think this issue also may belong to Typescript

**Comment by robertbaker** [comment]
@thakerng  You could try the WebStorm 11 EAP which has more support for TS.

**Comment by DanielRosenwasser** [comment]
I think this is external. The Webstorm folks seem not to use our language service at all.
