### ISSUE TITLE
Mapped discriminating union refinement

### ISSUE THREAD

**Issue by kddeisz** [microsoft/TypeScript#40559]
**TypeScript Version:**  4.0.2

**Search Terms:**

discriminating union
mapped type
inferred discriminating union
inferred mapped type
inference order

**Code**

```ts
type Expr = (
  | { kind: "num", value: number }
  | { kind: "add", left: Expr, right: Expr }
);

type Callback<K extends Expr["kind"]> = (expr: Expr & { kind: K }) => void;
type Visitor = { [K in Expr["kind"]]: Callback<K> };

const visitor: Visitor = {
  num(expr) {
    console.log(expr.value);
  },
  add(expr) {
    console.log(expr.left, expr.right);
  }
};

const visit = (expr: Expr): void => {
  switch (expr.kind) {
    case "add":
      visit(expr.left);
      visit(expr.right);

      // This compiles, because expr has been refined based on the switch statement
      const callback = visitor[expr.kind];
      callback(expr);

      break;
    default:
      break;
  }

  // This does not compile, because expr is still a union at this point, so callback
  // becomes a union here. So then it can't satisfy the extra { kind: K } constraint
  // on the callback argument. But if we lose that constraint, then our visitor
  // doesn't infer the correct arguments.
  //
  // It appears that what's happening is that callback is being inferred immediately
  // here. As in because expr.kind is "num" | "add", callback immediately becomes
  // distributed out to Callback<"num"> | Callback<"add">.
  //
  // As opposed to callback being defined as Callback<typeof expr.kind> which
  // would be equal to (expr: Expr & { kind: typeof expr.kind }) => void. In this
  // version, we can see that the expr variable definitely satisfies
  // Expr & { kind: typeof expr.kind }, because it's the same object.
  const callback = visitor[expr.kind];
  callback(expr);
};

const tree: Expr = {
  kind: "add",
  left: { kind: "num", value: 1 },
  right: { kind: "num", value: 2 }
};

visit(tree);
```

**Expected behavior:**

You should be able to compile `visitor[expr.kind](expr)`, since it's the same object that's doing the indexing. I don't think I would generally expect this behavior if `visitor` were just some random object. But since it's explicitly a mapped type from the source of the discriminating union, I kind of expected this to work.

**Actual behavior:**

You can't compile `visitor[expr.kind](expr)` outside of the switch statement (or an if). Workaround at the moment is `(visitor[expr.kind] as Callback<typeof expr.kind>)(expr)`. This works, but I wonder if it's possible to get it to work with the initial syntax. For one, I'm not 100% sure this cast is doing what I think it's doing, and for two the original syntax is just nicer.

**Playground Link:**

https://www.typescriptlang.org/play?#code/C4TwDgpgBAogHmATlAvFAFAWAFBSgHygG8oBrASwDsATALigCJKBXAWwYBooA3AQwBtmEei1YAjCMgC+OPIRIUa9Br2rVOUfhABmwevCRdE5AOYALPbATScASgDcOHKEhQAwgP5jeAY1IAeAGkoCDhgCBoAZyskAG0GRXUAXQA+VAxQpH1rKAAyYjIqOihgqVtUNO4Ae3JqR2wXaAA1ckjyYCrkNBJY4KoYxHjEhiSk+g9+L18AwLSpepwfKspI4B5W9s76FraOruJZKFF0TMRyokO8JZWqrQA6fiqTE+s7vkEIB0OpDkPVaheSHOlyg10itwgDyegMQDx0wC4pzuxnMwC+uCgMmw8yc2DBa24GzWaBh2SB9GqtQqBwxkQA7u0fGYMq9EsCMVdeJFoCo1AxaCC8ITdjC4bp0XhJesRUiURZ0YKoAB6JVQAAqZlaoKqrDA5C0kS4Eh8vGY3JCOTMXKgEgiUEQOioEGoNq5zqgyygwDM0HpjOZq144VYEWAivxoM83j86WFm0GSMSSXqUs5k2jpBhCo5krEDt4pBTkuoOlN-D0irzEALRaxhxV6s10WoVQg0UoVTWS11+ogRogJrN0FOUC1q31-CgvCgzEo5E9Qa9TagYBqlARUHBkfT03rquNOrbU5nc89PoddygAGUqku7e1I5QAORrSJB1raEB3i3ARDThRFPQpTaisv68FQYYYg2nretAJo7jGvCICYbChpeABCzBrOQ2hQHS0CPOa3qLvif4QVwsGUB6zDIHGex7lALZts+2GUNokjfksiAOj4axIShIbrpEdx7gxACSfFgJASHRMRax0lawBPtEVpSREVAmKOsmKduUwxlqEgaaObGSA6LrkKwIbUOQQYQPwIAMeekJQAAgtE-TGqa5qJkUWmMKIDAEIw-waPBemkKOlnOjZ4T2TaA6HpEDHWasxhiFh7pVFhXq3hM4X+EwbAMGkhB5RmBUhSkIlQUqDFuR6UlVNyLodN+-C8AAXuQHFldM-iNFUuE+TQaQKeQTJ4Vl-AuhIIQAI7MAIOUMaSAx5AUiT0ANQ2sr5ZTUpS1CXmJVHelq3CSG0yxcPhj6bhAEAMXJ34jnwxi8GIWiMY6c6xV+b7AB+3XRAYyD5ABSheuAECDRaSB3IkmK-DV8WDua7TKd+b4hh6YgAFYDsA1VXMsqy6RmsZEp0sTDdQyaHGFGZZvUOLYIspNrL+D1kvsFwYptwV8sjeBaLo9AQ8UhXsFw7xCPQACMSOHHKlgS8oAUywIctQAATJiOCszgdHoFznz1EAA

**Related Issues:**

Didn't find anything quite like this.

**Comment by captain-yossarian** [comment]
I think thats because here `const callback = visitor[expr.kind];` expr.kind can be still `add` or `num`.
If you add `return` statement, to your `case:add` it will compile without any error and `expr.kind` will be treated by TS as `num`

**Comment by kddeisz** [comment]
@captain-yossarian thanks for taking a look. Yeah I totally see what you're saying, and maybe my example was a bad one. In reality this switch has a ton of different cases in it (at the moment 12), not just 2. So ideally it should be able to run `visitor[expr.kind](expr)` after the switch statement and it wouldn't need to go into each individual branch.

**Comment by RyanCavanaugh** [comment]
This code is only safe by a sort of inspection that TypeScript isn't able to do

```ts
  const callback = visitor[expr.kind];
  callback(expr);
```

There are two ways to reason about this code:
 * *By brute force*, every possible inhabitant of `expr` results in this code being OK. This kind of analysis would be prohibitively slow
 * By higher-level reasoning, the fact the `expr.kind` came from the same `expr` as in the prior line, and it's the same variable without intervening assignments or other timing effects, *and* that every corresponding `kind` property is mapped to a safe type in `visitor`, means this is OK

**Comment by kddeisz** [comment]
Right, yeah exactly. I almost want something like `callback<typeof expr.kind>(expr)` or something (I know that wouldn't work because `expr.kind` is still a union. It's almost like I want to tell TypeScript that these two types covary together. Again I wouldn't expect it would work for most cases, but a mapped type over a discriminating union makes sense that this would work because you can guarantee that you're mapping 1-to-1.
