### ISSUE TITLE
Unable to use infer on types with optional keys

### ISSUE THREAD

**Issue by Alphy11** [microsoft/TypeScript#40552]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** infer optional

**Code**

```ts
type keys = { key?: string} extends Record<infer K, any> ? K : never;
```

**Expected behavior:**
keys should be `"key"`
**Actual behavior:**
keys is never
**Playground Link:** 
[Playground link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200914#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBFQ4BoeMheRDwAYMEHsGjfNxmZjsBjMSD8WDQdSJZnwPQiLwAIgAoqsGIgavoJUkcRLwA5UAByYQAOUgEglQRUAHlvmRdoI+VpIMdUI4FK5pHhQE4GTpRlh9CgEIgYcIruyJIzoiIDBwcd0WGwuNwgiVFKgWqB4pA8MIALygADeSZTAH58tdUJROMwAL4Q1YKHjCJ6QBBkbgAHgyyJxAGlLpw8AA+UC50Bt0AFziQPRkADcQA)
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Why not just write `keyof K` ?
