### ISSUE TITLE
Cannot infer type arguments from a default parameter

### ISSUE THREAD

**Issue by wimoy** [microsoft/TypeScript#40557]
**TypeScript Version:**  4.1.0-dev.20200914

**Search Terms:**

default parameter
generic inference

**Code**

```typescript 
function identity<T>(value: T): T {
    return value;
}

function apply<T, U>(value: T, map: (x: T) => U = identity): U {
    return map(value);
}

const a1 = apply(5);
const a2 = apply(5, identity);
```

**Expected behavior:**

Definition `apply` should type check correctly. `x(5)` should have the same type as `x(5, identity)`.

**Actual behavior:**

Definition of `apply` is not valid. Type of `a1` is not correctly inferred. 

**Playground Link:**

https://www.typescriptlang.org/play?ts=4.1.0-dev.20200914#code/GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKANwEMAbENALkXwEp79EBvAWAChFfEAnNFBD8kFamgDc3AL7duoSLASJyABzWU8+ADSIAqiXE0WegLbr6xAB4tGiALyEDj5OkwwczF5x59BwqKIFmpkVDSM0lxyXNwQCADOUKoAjK7qmtjEAKyRcYnJ5ABM6RpaOXqoGFjYkUA

**Comment by captain-yossarian** [comment]
Hi, @wimoy 
```typescript
type Identity = <T>(value: T)=>T 
```
Your `map` argument type is not assignable to `Identity` type, because `identity` function takes `T` arguments and returns `T` value, when your `map` argument takes `T` value and returns `U` value.
I think it is ok that TS throws an error.

Please try next example:
```typescript

type Identity = <T>(value: T) => T;

const identity: Identity = <T extends unknown>(value: T): T => value;

function apply<T>(value: T, map: Identity = identity) {
  return map(value);
}

//OR

function apply<T>(value: T, map: (arg: T) => T = identity) {
  return map(value);
}

const a1 = apply(5);
const a2 = apply(5, identity);
```

**Comment by RyanCavanaugh** [comment]
This is a correct error. It's legal to call
```ts
const a1 = apply<number, string>(5);
```
but this would cause a `number` value to be present where a `string` is expected
