### ISSUE TITLE
trailing comma kept in object notation output for es5 and es3

### ISSUE THREAD

**Issue by pomack** [microsoft/TypeScript#40553]
**TypeScript Version:**  3.3 - 4.0.2

**Search Terms: trailing comma es3 es5 output object notation**

**Expected behavior:**
```js
"use strict";
var v = {
    a: 1,
    b: 2
}
```

**Actual behavior:**
```js
"use strict";
var v = {
    a: 1,
    b: 2,
};

```

**Related Issues: https://github.com/microsoft/TypeScript/issues/7938 https://github.com/microsoft/TypeScript/issues/24530
https://github.com/microsoft/TypeScript/issues/10720
https://github.com/microsoft/TypeScript/issues/271**

**Code**
```ts
const v = {
    a: 1,
    b: 2,
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var v = {
    a: 1,
    b: 2,
};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES5",
    "jsx": "React"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=1&module=0&ts=4.0.2#code/MYewdgzgLgBAbjAvDA3gKBpmBDAXDARgBoMsAjfAJhIF8g)

**Comment by RyanCavanaugh** [comment]
Trailing commas are legal in ES5, and correctly removed in ES3 under `tsc`. It looks like just the Playground has a bug where this isn't being respected correctly.

**Comment by RyanCavanaugh** [comment]
ES3 deprecated
