### ISSUE TITLE
Default a folder module file to index.ts w/ ES6 modules?

### ISSUE THREAD

**Issue by mjw56** [Microsoft/TypeScript#4056]
Hi,

Is it possible to default the file that TypeScript looks for in a folder to index.ts?

e.g.

```typescript
import { Bar, Baz } from '../Foo/';
```

where ```'../Foo/'``` contains an ```index.ts``` that looks like:

```typescript
export { Bar } from './bar';
export { Baz } from './baz';
```

Something similar to this: https://nodejs.org/api/modules.html#modules_folders_as_modules

Any thoughts on making something like this available?
 
Thanks.

**Comment by mhegazy** [comment]
This should be covered by #2338. should be available soon. so stay tuned.

**Comment by mjw56** [comment]
awesome, thanks @mhegazy.
