### ISSUE TITLE
Commonjs import with destructuring ignores trailing property access

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#40578]
Discovered in https://github.com/prettier/prettier/pull/9207, where @brodybits is investigating whether #40143 works.

```js
// @filename: mod1.js
var o = {
    concat() { }
}
exports.builders = o
// @filename: test.js
const { concat } = require('./mod1').builders;
```

**Expected behavior:**

`concat: () => void`

**Actual behavior:**

Error: module "mod1" has no exported member 'concat'.

Looks like we miss the trailing property access and don't fall back to the faked import type.

**Comment by brodybits** [comment]
Small question: does the milestone mean that we would have to wait for `4.1.1` rather than `4.1.0`?

In any case, thanks again for your efforts to support Prettier.

**Comment by j-oliveras** [comment]
@brodybits Version `4.1.0` is the beta, `4.1.1` is the release candidate and `4.1.2` is the final release. They use it like this because the nuget or Visual Studio release (I don't remember witch one) don't support tags/branches.

Probably they wait for the release candidate because the beta will be launched this week (see #40124).

**Comment by brodybits** [comment]
I tried making my own, local build of TypeScript from master, and it DOES seem to work properly with Prettier.

When I tried recent version `4.1.0-dev.20200924` from npm, that one does not seem to be fixed. I tried it here: https://github.com/prettier/prettier/pull/9207

I would be happy to try a newer beta version from npm once it is ready.

**Comment by sandersn** [comment]
Hmm. I think 0924 is built on early on the morning of 9/24, and this was merged in the afternoon. Perhaps 0925 will work?

**Comment by brodybits** [comment]
> 0925 will work?

Seems to work for me, thanks!
