### ISSUE TITLE
Successful build but had lots of 'fake' IntelliSense errors In Typescript (after Visual Studio 2019 +  TS upgrade)

### ISSUE THREAD

**Issue by hvilppu** [microsoft/TypeScript#40571]
TypeScript Version: 3.9 (Was earlier 3.4.2)

I upgraded my Visual Studio to the new version Version 16.7.3. and TS to 3.9 from (3.4.2)

After the upgrade, I get a lot of IntelliSense errors. Those are not 'real' and do not have even underlined with red:
![image](https://user-images.githubusercontent.com/38765280/93186693-97382800-f747-11ea-9b76-e6da3caa3a67.png)

But not red underline:
![image](https://user-images.githubusercontent.com/38765280/93186825-bafb6e00-f747-11ea-8297-a98d31182bd7.png)

Expected behavior:
Intellisense worked on the VS 2017 and VS 2019 earlier version

Actual behavior:
Intellisense broke up. But the project builds.

What I have done:
* Deleted .vs foder
* Deleted bin/obj folders
* Installed TS SDK 3.9
* Set project to use 3.9 on settings
* Restored NuGet packets

**Comment by hvilppu** [comment]
Additional info:

tsconfig.json:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "strictFunctionTypes": false,
    "types": [ ],
    "lib": [ "es2017", "dom", "scripthost" ],
    "typeRoots": [ "../node_modules/@types" ]
  },
  "exclude": [
    "bin"
  ]
}
```

I also tried the Unload -> Load project with no luck

**Comment by hvilppu** [comment]
Even more info. Alt build project for files seems to be "Miscellaneous" (I don't have a project named like that)
![image](https://user-images.githubusercontent.com/38765280/93301170-b941b100-f800-11ea-996a-f9d27165c9b0.png)

**Comment by uniqueiniquity** [comment]
Hi @hvilppu, I'm sorry for the issues the upgrade is giving you.

In the properties window, what is the "Build Action" for your tsconfig.json?
I would recommend that you set it to "TypeScript file" or "TypeScriptCompile" (they're the same - the particular display name depends on what kind of VS project you're using).

If setting that doesn't resolve the issue, could you please follow the instructions shown [here](https://github.com/microsoft/JSTSdocs/blob/master/articles/troubleshooting/index.md#enable-detailed-language-service-logging) to generate an IntelliSense log?

I look forward to investigating further!

**Comment by hvilppu** [comment]
No luck with this one:

> In the properties window, what is the "Build Action" for your tsconfig.json?
> I would recommend that you set it to "TypeScript file" or "TypeScriptCompile" (they're the same - the particular display name depends on what kind of VS project you're using).

I try to generate logs later and post here results.

**Comment by hvilppu** [comment]
[ti-3068.log](https://github.com/microsoft/TypeScript/files/5234658/ti-3068.log)

Here is the first one of logs needs more?

All errors comes to "Miscellaneous"-project  (The real .ts files are at "FishPortal.Web"-project)
![image](https://user-images.githubusercontent.com/38765280/93386499-791a1700-f870-11ea-8b68-5754309c05bf.png)

**Comment by uniqueiniquity** [comment]
Yes - it's the other ones that I need (specifically the one containing the phrase `ProjectHost` in the filename). Thank you!

For transparency, I'm trying figure out why files are ending up in the Miscellaneous project instead of the FishPortal.Web project. That log should be able to show me how the TypeScript language service is interpreting your project structure.

**Comment by hvilppu** [comment]
I cannot see log starting with "ProjectHost" here is all I got with these [instructions](https://github.com/microsoft/JSTSdocs/blob/master/articles/troubleshooting/index.md#enable-detailed-language-service-logging)

I saved logs with PerfView to perfview.log

**(2 different runs)**

[perflog.txt](https://github.com/microsoft/TypeScript/files/5236964/perflog.txt)
[tsserver.21896.log](https://github.com/microsoft/TypeScript/files/5236965/tsserver.21896.log)
[tsserver.20604.log](https://github.com/microsoft/TypeScript/files/5236966/tsserver.20604.log)
[ti-21896.log](https://github.com/microsoft/TypeScript/files/5236968/ti-21896.log)
[tsserver.20492.log](https://github.com/microsoft/TypeScript/files/5236969/tsserver.20492.log)
[tsserver.9904.log](https://github.com/microsoft/TypeScript/files/5236970/tsserver.9904.log)
[ti-20492.log](https://github.com/microsoft/TypeScript/files/5236971/ti-20492.log)

**Comment by uniqueiniquity** [comment]
These logs are perfect. I'll take a look and get back to you as soon as I can.

**Comment by uniqueiniquity** [comment]
The issue appears to be related to having the `alerts.vue.html` file open - we're not handling that file very well.
Would you be willing to share the contents of that file? I've never seen the `.vue.html` file extension used before, so I'm curious to understand how you are using it.

**Comment by hvilppu** [comment]
Hellos:

I simplified files here: ( I need to change them .txt so I can upload them here)

Real files are:
alerts.css
alerts.ts
alerts.vue.html

[alerts.css.txt](https://github.com/microsoft/TypeScript/files/5252198/alerts.css.txt)
[alerts.ts.txt](https://github.com/microsoft/TypeScript/files/5252199/alerts.ts.txt)
[alerts.vue.html.txt](https://github.com/microsoft/TypeScript/files/5252200/alerts.vue.html.txt)

So .vue.html is just an HTML file that has .vue on its name.

There are 3 files 1) .css and 2)alert.ts that are "code behind" for 3) alert.vue.html.. nothing special on them.

**BUT** I get also errors for:
![image](https://user-images.githubusercontent.com/38765280/93717800-cc49dd80-fb80-11ea-86e5-217ea2b101f5.png)

And routes.ts is just ts file that does not have Html-part.
It is that simple:

```
import { RouteConfig } from 'vue-router';
import { Component } from 'vue-property-decorator';

let routes: RouteConfig[] = [    
    { path: '/', component: require('./components/login/login.vue.html').default, meta: { authenticated: false } }, // NO AUTH
];

export default routes;
```

**Comment by uniqueiniquity** [comment]
Thank you for the simplified files!

The issue is that VS considers `.html` files to include JS content from the perspective of figuring out your projects.
Your main project is configured by your `tsconfig.json` and does not include any JS content.

To fix this, you can add `allowJs: true` to the `compilerOptions` section of your tsconfig.
With this change, you may want to add an `include` section to be more precise about the files included in your project, in case you have any JS files or other HTML files nearby that you don't want included:
```json
{
  "include": [
    "./**/*.ts",
    "./**/*.vue.html"
  ]
}
```

**Comment by hvilppu** [comment]
Yeh. This worked! Can be closed now. Thanks!
