### ISSUE TITLE
The class extension output of es5 can't pass the test.

### ISSUE THREAD

**Issue by xiaozs** [microsoft/TypeScript#40570]
```typescript
class SubError extends Error { }

assert(new SubError instanceof SubError);
```
This test will fail when  ```compilerOptions.target``` setted to be ```es5``` or lower.

**Comment by j-oliveras** [comment]
[Why doesn't extending built-ins like Error, Array, and Map work?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work)
