### ISSUE TITLE
All optional generic type parameter accepts extra fields

### ISSUE THREAD

**Issue by 1st1** [microsoft/TypeScript#40582]
**TypeScript Version:**  4.0.2

**Search Terms:** "generic parameters"

**Code**

```ts
type Params = {
  p1: string;
  p2: string;
};

type AllOptional<T extends object> = {
  [K in keyof T]?: T[K];
};

const tmp = <P extends AllOptional<Params>>(params: P): number => {
  return 42;
};

// const tmp = (params: AllOptional<Params>): number => {
//   return 42;
// };

const r0 = tmp({p1: "aaa"});
const r1 = tmp({p1: "aaa", bogus: 123});
const r2 = tmp({p1: "aaa", p2: "bbb", bogus: 123});
```

**Expected behavior:**

The expected behavior is that the `bogus` argument would be marked as invalid. 

**Actual behavior:**

Basically, the commented out second `tmp` function is a non-generic version of the first `tmp` function and works as expected, i.e. the `bogus` field is marked with error.

However, the generic function happily accepts `bogus`. It seems that the `?` in `[K in keyof T]?: T[K];` is what breaks things.  Without the `?` both the generic and the non-generic functions behave the same way: expect both `p1` and `p2` specified and error out on `bogus`.

**Comment by RyanCavanaugh** [comment]
These aren't the same because having them be different allows you to write one or the other depending on how you want it to behave.

**Comment by 1st1** [comment]
My use case is to generate types programmatically and then deduce the actual API from them. So is there a way to make `AllOptional` work? So far it works inconsistently (adding `?` in `AllOptional` drops typing entirely) and I really doubt that this is "working as intended".  Would really appreciate a more detailed explanation if you have time!

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. It works this way on purpose.

You can write this if you want generic inference to not take place

    const r1 = tmp<AllOptional<Params>>({p1: "aaa", bogus: 123});

There isn't a way to make a generic function behave as if it isn't generic, though. If you provide more samples of how you want this to work, we can advise.
