### ISSUE TITLE
Suggestion: disallow mutual imports between 2 modules.

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4058]
For any 2 modules A and B only one of the following can hold true:

- A needs B
- B needs A
- neither A nor B need each other

a situation when A demands B and at the same time B demands A is absurd that doesn't make much sense unless both A and B are considered one single AB module

currently little TypeScript does to prevent this s***ituation from happening, and it happens a lot

it's not that hard to come up with a linter rule, but it feels like such situation should be prevented by the compiler

**Comment by aleksey-bykov** [comment]
for a situations when a single AB module is purposefully separated into 2 mutually dependent modules A and B TypeScript should have some **distinct syntax**, so that it doesn't happen by accident

**Comment by RyanCavanaugh** [comment]
Are you talking about something that's a runtime error?

**Comment by aleksey-bykov** [comment]
it's not a runtime problem is a problem with maintaining the overall composition

an app is a pie of components that go from less to more specific ones, where less specific components must not depend on more specific ones

on our project (of a considerable code base) we have violations of this principle all over the place

it's not a problem if the application is viewed as a single monolith block of code, but when it comes to extracting a reusable layer it was it a base for a project next door we simply can not just do that because of entanglement between the modules (due to a lack of care, supervision and proper design)

now looking back i can tell 99% of all mutual dependencies are there by chance rather than by design, developers just lack basic discipline

preventing modules from being mutually dependent (by chabce) looks like a good candidate for a linter rule (at least) or for a compiler error (better yet)

**Comment by mhegazy** [comment]
one thing to note, this is one of the "features" of ES6 modules. you can have circular references. SystemJs format main design goal is to support these scenarios. 

moreover, there are tools that would help you do this, e.g. [Dependency view in atom-typescript](https://atom.io/packages/atom-typescript). 

We need some clear reasoning on why this is a language error vs a warring that a linter would flag.

**Comment by kitsonk** [comment]
It is also a feature of [AMD](http://requirejs.org/docs/api.html#circular).  As stated, it is usually a design flaw, but I have seen cases where the circular dependency is wider (e.g. A -> B -> C -> A) and it is hard to "uncouple" the dependency loop and maintain optimal reuse of code.

**Comment by RyanCavanaugh** [comment]
We're not here to enforce opinions about abstraction strategies. Many people believe this kind of pattern to be totally valid -- maybe `A` and `B` need each other for technical reasons, but expose meaningfully different surface area depending on the intended use case.

It would have been *much* simpler (in terms of implementation) for the ES6 committee to have completely disallowed this pattern. The fact that they accepted that complexity trade-off means that enough people saw value in mutual dependencies to support it as a runtime feature.

I will stress that I'm not saying that your position on dependency graphs isn't a valid one. It's totally valid position to have. Same as not liking inheritance -- I also think it's an overused pattern. But there is no community consensus about it and we're not here to pick winning opinions.

**Comment by aleksey-bykov** [comment]
on a bright side it good to know that the effort of writing such rule for the linter is not going to go waste one day when a native feature that does exactly the same is shipped
