### ISSUE TITLE
KATA-MoovOne

### ISSUE THREAD

**Issue by PinkiePie-tech** [microsoft/TypeScript#40585]
**TypeScript Version:**  4.0.2

**Search Terms:**

**Expected behavior:**

**Actual behavior:**

**Related Issues:**

**Code**
```ts
const init = [1,0,1,1];
const steps = 2;
let actual = init;

const nextStep = () => {
    return actual.map((value: number, iteration: number) => {
        const previous = actual[iteration !== 0 ? iteration - 1 : actual.length - 1];
        const next = actual[iteration !== actual.length - 1 ? iteration + 1 : 0];
        return previous !== next ? 1 : 0
    })
};

for(let i = 0; i < steps; i++) {
    actual = nextStep();
}
console.log(actual.join(','));
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const init = [1, 0, 1, 1];
const steps = 2;
let actual = init;
const nextStep = () => {
    return actual.map((value, iteration) => {
        const previous = actual[iteration !== 0 ? iteration - 1 : actual.length - 1];
        const next = actual[iteration !== actual.length - 1 ? iteration + 1 : 0];
        return previous !== next ? 1 : 0;
    });
};
for (let i = 0; i < steps; i++) {
    actual = nextStep();
}
console.log(actual.join(','));

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmOsC8MDaBGANABi9jAXQG4BYAKFElmgFMAHCGVAJjPIBtbYBDYKAK48OzeIijsKVaDDC0AHlADKUBqIAUASmYA+GAG8KMYzABO3AabAw+g4QDoAtj3rr1AN2EDaALlkDHACNaUyx4VVMeKDhwPzAA4NNtZD1DchMMmGlYenN3GIEmVFshDjQkEKiY6wBCZFQcGAB+cMro8BgAWhgMGD8Shy4wAHMoAAsunpIjTONs2QUUG35S8oiqjrrilcHaEfHJ3paKyPbrAGoevpgcafTZswsrGFzafJBCmC2FxWarvxwM2MAF9NBRgZJyAAzECmdRcWBwUQ4YjwGAAHhgdEYqLg53O2jSGQGIlQckUKgYWnYwKk4AgIC49g4IGG6hJ9gAViAEOoAORYPmaTTEIA)

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
