### ISSUE TITLE
Deprecated suggestions not reported as deprecated imported alias 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#40588]
**TypeScript Version:**  4.1.0-dev.20200916

**Search Terms:**
- deprecated
- suggestion / IntelliSense
- kindModifiers

**Code**

For the code:

`foo.ts`
```ts
/** @deprecated */
export function foo() {}
```

`index.ts`
```ts
import { foo } from './foo'
foo // trigger suggest here
```

In `index.ts`, trigger the suggestions for `foo`

**Expected behavior:**
The returned suggestion for `foo` is marked as deprecated (it has `"kindModifiers": "deprecated"`)

**Actual behavior:**
The suggestion does not have any kindModifiers

**Comment by DanielRosenwasser** [comment]
Demo-driven bug-finding is my favorite 😅

**Comment by a-tarasyuk** [comment]
`foo` is an alias and doesn't have `deprecated` flag., 
https://github.com/microsoft/TypeScript/blob/88c24e6b0d0efb868088ed6da359ef55e6f1c6b6/src/services/completions.ts#L450
To get the `deprecated` modifier, need to resolve the alias and use it with `getSymbolModifiers`. @sandersn Do we need to combine `alias` and exported declaration `flags` to get `modifiers`? Or just need to use something like `getSymbolModifiers (skipAlias (symbol))`?

**Comment by jeanp413** [comment]
A related issue I found, apart from the suggestions not being marked as deprecated, is that when typing `foo` (line 11) it isn't rendered with a strike-through line as opposed to `foo` inside an import expression (line 1) or when typing `bar` (line 9, defined as a local deprecated function)
![image](https://user-images.githubusercontent.com/25115070/94504258-fc6f2d00-01cd-11eb-9cb7-552c04ce5541.png)

Not sure if I should create a separate issue for this but I traced it back to `checket.ts` line 22686, needs some additional logic when the symbol is an alias
```typescript
if (declaration && getCombinedNodeFlags(declaration) & NodeFlags.Deprecated && isUncalledFunctionReference(node.parent, localOrExportSymbol)) {
        errorOrSuggestion(/* isError */ false, node, Diagnostics._0_is_deprecated, node.escapedText as string);
}
```

**Comment by a-tarasyuk** [comment]
@jeanp413 Not sure if we need a new issue, I can include a fix to PR related to this issue.

**Comment by sandersn** [comment]
Nope, only the in-editor strikethroughs are fixed, github's pattern-matching close is over-eager here.

**Comment by jeanp413** [comment]
Created a PR with a possible fix https://github.com/microsoft/TypeScript/pull/41128
