### ISSUE TITLE
Support “Arbitrary module namespace identifier names”

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/TypeScript#40594]
## Search Terms

- Arbitrary module namespace identifier names
- Arbitrary module namespace identifiers
- Arbitrary module identifier names
- Arbitrary module identifiers
- Arbitrary module identifier
- Arbitrary export names
- Arbitrary export identifiers
- string export names
- string exports

## Suggestion

Implement support for <https://github.com/tc39/ecma262/pull/2154>.

## Use Cases

This is necessary for **WASM** module integration.

This would also allow typing [`@types/webidl‑conversions`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webidl-conversions) without needing to use `export =`.

---

For transpiled modules, this can already be supported, since it’s just creation of arbitrary properties on the **CommonJS** `exports` object, but native modules will require `module: "ESNext"`.

## Examples

See <https://github.com/tc39/ecma262/pull/2154>

```ts repro
// @showEmit
// @filename: module.d.ts
export const foo: unknown;

declare const some_imports: unknown;
export { some_imports as "some imports" };

declare const another_imports: unknown;
export { another_imports as "another imports" };

declare const extra_imports: unknown;
export { extra_imports as "extra imports" };

declare const rest_exports: unknown;
export { rest_exports as "rest exports" };

// @filename: index.ts
import { "some imports" as foo } from "./module.js";

export { foo as "some exports" } from "./module.js";
export { "another imports" as "another exports" } from "./module.js";
export { "rest exports" } from "./module.js";
export { "extra imports" as extra_imports } from "./module.js";

export * as "star exports" from "./module.js";
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEGcAsHsHcCiBbAlgFwLACgQQGaoA2ApgHYCGyJAXKMrACYCupAdI2+pDiQB4AHWACd0oAMawykMfliw6zMgGsyCMgG4cORiXFEKwkhKkzQkWNQD6qZENGRFKtfE29BIsQG9zlkjbtPSFAKYIAiC2pQW3tuMNAAXy1sHT0DIxNpMQo1dGgSYQDYx1AlVXVk-ljQHxzYPIKioJDwuobhaMCHeKTtbF19Q2NJLNB+dGEKJocnctdKj1Easb4JqZjm0NAw8cnO4p7k1MGMkbMjGSsqoNmXN2xrpZ8L9CvF7hbtl5WDxKPcMDgQikSjUOioMi6PhcHjYDZPbaRYzwuKfOSwRKgfDCSzbNjABgsdgAK0gYX+j28WPknwifh+QR6WJxyDxBKYrBIbFJ5Pc1R8YTa+Q6KLJtKFBQZ3Ux2NxYXxhM53LJC35XxIZkpYoSzLlCo5JJVfM8yx2qz2oviW126y6Hx1stZ8vZRK5PIp71AACpaTJDFLUY62YrDbzsEA)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Related issues

- <https://github.com/microsoft/TypeScript/issues/43870>
- <https://github.com/microsoft/TypeScript/pull/49297>

**Comment by ExE-Boss** [comment]
Note that **Babel** now has support for this: <https://github.com/babel/babel/pull/12091>

**Comment by DanielRosenwasser** [comment]
https://github.com/tc39/ecma262/pull/2154

```ts
import { "😊" as yay } from "...";

yay();

export { yay as "🦈" };
```

The above code should be supported.

The minimum viable product should have tests for:

* `esnext` module output
* `es2015` or similar module output just to get an error
* `--declaration` emit
  * Specific declaration emit where the compiler might generate `import()` type syntax.
* Quick info, and error message tests where we might generate `import()` type syntax
* Completions in `import {}` and `export {}` lists
* Go-to-definition

It is likely that we would never try to emit our own `import()` type syntax.

**Comment by evanw** [comment]
Is it planned for this to work with TypeScript types as well as values? For example, I'd expect the following to be valid as well:

```ts
import type { 'a' as b } from 'foo' 
import { type 'a' as b } from 'foo' 

export type { a as 'b' }
export { type a as 'b' }
export { type 'a' } from 'foo' 
export { type 'a' as b } from 'foo' 
export { type a as 'b' } from 'foo' 
export { type 'a' as 'b' } from 'foo' 
```

I'm wondering because esbuild supports both TypeScript and arbitrary module namespace identifier names, so it has to deal with this somehow. Right now I'm moving forward assuming that it will eventually be supported for types as well but it would be good to clarify this.

**Comment by andrewbranch** [comment]
@evanw I’m pretty sure your examples above will “just work” unless we explicitly disallow them, and I don’t see an immediate reason to do that. The syntax above would certainly parse. Just out of curiosity, what’s the impact of this on esbuild?

**Comment by andrewbranch** [comment]
@DanielRosenwasser should this actually be milestoned right now? It’s a bit hard to tell the status of the spec change, but it looks kinda stuck.

**Comment by DanielRosenwasser** [comment]
Good call, I assumed it would be an open-and-shut normative PR but it looks like it hasn't been updated for a while; let's hold off until https://github.com/tc39/ecma262/pull/2154 is actually merged.

**Comment by ExE-Boss** [comment]
@andrewbranch
> @DanielRosenwasser should this actually be milestoned right now? It’s a bit hard to tell the status of the spec change, but it looks kinda stuck.

Note that this is already implemented in **V8**, **SpiderMonkey**, and **JavaScriptCore**; see <https://github.com/tc39/ecma262/pull/2154#issuecomment-825201030>:
> For the `[needs implementation]` label: this now works in Node.js 16 (and thus Chrome 90 I believe).
> 
> EDIT: This works also in JSC and SM.
> 
> ```
> ~ via ⬢ v16.0.0 
> ➜ eshost -x 'import(`/home/nicolo/test.js`).then(JSON.stringify).then(print)'
> #### ChakraCore
> 
> SyntaxError: Syntax error
> 
> #### Hermes
> 
> SyntaxError: Invalid expression encountered
> 
> #### JavaScriptCore
> {"😊":2}
> 
> #### Moddable XS
> 
> 
> #### SpiderMonkey
> {"😊":2}
> 
> #### V8
> {"😊":2}
> ```

**Comment by ExE-Boss** [comment]
@andrewbranch @DanielRosenwasser
<https://github.com/tc39/ecma262/pull/2154> has now been merged.

**Comment by andrewbranch** [comment]
@DanielRosenwasser do we want to make this Help Wanted for 4.6? Kind of surprised we don’t have a community PR already 😁

**Comment by DanielRosenwasser** [comment]
I suppose so - I have a bit of skepticism around this because I'm sure an implementation needs to now handle a bunch of edge-cases around rename, find-all-refs, etc. Also, it might be worth erroring if the module target isn't high enough? Unclear to me right now.

**Comment by Jack-Works** [comment]
Let me try this but no guarantee I will make it

**Comment by Jack-Works** [comment]
Parser and SystemJS/CommonJS work now. Still have no idea how I should change the type system to support analyzing that.

**Comment by evanw** [comment]
(For those on this thread) I gave fixing this a try: https://github.com/microsoft/TypeScript/pull/58640

**Comment by Jack-Works** [comment]
> (For those on this thread) I gave fixing this a try: #58640

I'm happy to see you pick this up! My mental health does not support me finishing my PR for now but I still want to see this happen

**Comment by DanielRosenwasser** [comment]
Thanks @evanw!

**Comment by evanw** [comment]
Thank _you_ for accepting this PR. I'm looking forward to using this feature in VSCode!

One potential remaining task is syntax highlighting. I have another PR ready to go that adds support for this feature to the TypeScript language syntax definition: https://github.com/microsoft/TypeScript-TmLanguage/pull/1030. Would it be possible to add that or a similar change (doesn't have to be mine) so that syntax highlighting works too?
