### ISSUE TITLE
Add argument types to `URL.createObjectURL`

### ISSUE THREAD

**Issue by olyop** [microsoft/TypeScript#40602]
The function `URL.createObjectURL` currently has an argument of type `any`. However, this is not in line with the types it would like to be parsed.

I suggest changing the argument from type `object: any` to `object: File | Blob | MediaSource`.

This would make make the type more helpful and make it inline with the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#Parameters).

I might be missing a type of `null` or `undefined` on the union type but I'm not sure if there is a use case for this.

**Comment by ulrichstark** [comment]
Whoops. I was too fast.

Seems like the type should be changed here: [microsoft/TSJS-lib-generator](https://github.com/microsoft/TSJS-lib-generator)

**Comment by andrewbranch** [comment]
This seems reasonable to me. N.B., `lib.webworker.d.ts` must exclude `MediaSource`.

**Comment by olyop** [comment]
I plan to make a pull request, however I'm not sure which files to edit. Could you point me the right direction?

**Comment by andrewbranch** [comment]
I’ve actually never made a lib edit myself, but you can check the [Contribution Guidelines here](https://github.com/microsoft/TSJS-lib-generator#contribution-guidelines).

**Comment by olyop** [comment]
@andrewbranch

**Comment by jakebailey** [comment]
This was fixed back in #46080.

**Comment by isocroft** [comment]
Hello @jakebailey  . Please, contrary to your statement, this wasn't fixed in #46080 . 

It ought to be `URL.createObjectURL(obj: File | Blob | MediaSource)` and not `URL.createObjectURL(obj: Blob | MediaSource)`.

I will graciously like to re-open this PR which @olyop opened

**Comment by jakebailey** [comment]
`File` extends `Blob`; there is no reason to include `File` in the union as it would be reduced away.

**Comment by isocroft** [comment]
Ok 👍🏾
