### ISSUE TITLE
Transforming ImportDeclaration or ExportDeclaration causes type specifiers to be output in js files

### ISSUE THREAD

**Issue by nonara** [microsoft/TypeScript#40603]
Type imports/exports which are regularly excluded in compiled JS output get included when `updateImportDeclaration` / `updateExportDeclaration` are called during transform.

**TypeScript Version:**  3+

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/31446 (this is the same issue, but it was closed prematurely by the OP)

The aforementioned issue details the problem well. Unfortunately, the OP closed it before it could be investigated because of finding a workaround. The workaround, however, was an internal method (`ts.updateNode`) which has been removed in TS 4.0+.

**Playground Link:**
Reproduction: https://repl.it/@nonara/ts-bug#index.ts

**Search Terms:** updateImportDeclaration, createImportDeclaration

**Code:**

`a.ts`
```ts
export type A = string;
```

`index.ts`
```ts
import { A } from './a'
export { A } from './a'
```

`transformer.ts`
```ts
function transformer(ctx: ts.TransformationContext) {
  const { factory } = ctx;
  return (s: ts.SourceFile) => ts.visitEachChild(s, visitor, ctx);

  function visitor(node: ts.Node): ts.Node {
    if (ts.isImportDeclaration(node) && ts.isStringLiteral(node.moduleSpecifier))
      return factory.updateImportDeclaration(
        node,
        node.decorators,
        node.modifiers,
        node.importClause,
        ts.createStringLiteral(node.moduleSpecifier.text)
      );

    if (ts.isExportDeclaration(node) && node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier))
      return factory.updateExportDeclaration(
        node,
        node.decorators,
        node.modifiers,
        node.isTypeOnly,
        node.exportClause,
        ts.createStringLiteral(node.moduleSpecifier.text)
      );

    return node;
  }
}
```

**Expected Behaviour**: Should match output without transformer...

`index.js`
```js
export {};
```

**Actual Behaviour**: _(Output with transformer)_

`index.js`
```js
import { A } from "./a";
export { A } from "./a";
```

**Comment by andrewbranch** [comment]
@rbuckton can confirm, but I’m not 100% sure this is a bug—if you modify the declaration, how do we know it can still be elided in emit?

**Comment by nonara** [comment]
@andrewbranch That's a good point. I should note that it also happens if I replace just the `moduleSpecifier.text` (`StringLiteral`) node during visit instead of the parent `ImportDeclaration`.

The use case is the plugin https://github.com/LeDDGroup/typescript-transform-paths - We're transforming for `paths`.

**Comment by nonara** [comment]
Out of curiosity, where in the code would I be able to find the type elision behaviour? I've tried several workarounds, but there are still edge cases in which it fails.

If I had a little detail on where to look, I may find time to do a PR before the team gets to it.

**Comment by andrewbranch** [comment]
Calls of `isReferencedAliasDeclaration` in the transformers:

https://github.com/microsoft/TypeScript/blob/54f8d38535426814d1c5972e4ec4676e8cfebcf6/src/compiler/transformers/ts.ts#L2844-L2845

**Comment by nonara** [comment]
Thanks, @andrewbranch !

I was able to track the behaviour to this:

https://github.com/microsoft/TypeScript/blob/54f8d38535426814d1c5972e4ec4676e8cfebcf6/src/compiler/transformers/ts.ts#L242-L268

Is there anyone who can speak to the comment from 245-249 in more detail? It's looking like in order to properly fix this, we'll need to drop the `if (parsed !== node)` block and add safeguards for unavailable type info in the visit functions seen in the `switch (node.kind)` block.

Any detail on the sorts of conditions which would produce the unavailable type info would be helpful!

**Comment by andrewbranch** [comment]
This section of code is not too surprising, and it further reinforces my impression that while you have a good reason to want the behavior you want, the behavior you’re getting is working as we expect—basically, that you’re asking for a feature, not describing a bug. My guess is that if you add or replace anything material in the declaration (e.g. changing the module specifier, adding or replacing import specifiers), we would have problems with the rest of the logic here. The only thing I can think of that would probably be fine to transform and then process as usual is dropping import specifiers. In your case, since you want to change the module specifier, I think it’s unclear what we should do here. Should we resolve type info of the import specifiers as if you _haven’t_ changed the path?

Suppose you transform `import { Foo } from "./a"` to `import { Foo } from "./b"`. One resolves to a type, while the other resolves to a value, and there is additionally a global class `Foo`. Changing the module specifier could change whether the `Foo` alias appears to be referenced or not. You might say, “Well, because we never ran the checker with this declaration referencing module `"./b"`, we can justifiably take it as a technical limitation that we cannot process this declaration as if it references `"./b"`. We should decide whether or not to elide it based on the original node. If the original node would have been elided, we will elide the transformed node. If the original node would have been preserved, we will emit the transformed node.” (If I understand correctly, this is exactly the behavior you’re looking for.)

But now suppose you have an idea for another transformer. You’re building a dev tool that allows you to visualize the dependency graph of all your modules, as TypeScript sees it (i.e., a dependency on only types from a module still counts, even though it gets elided in JS emit). So, you make a transformer that adds to every module an extra `export const __moduleId = "whatever"`, and adds an import specifier importing that module ID onto every import, so it can call some registration function with it. (This is shaping up to be a gross example, but it’s not really the point.) Now, when you transform import declarations to include, and later use, `__moduleId`, that is clearly info that you intend to be preserved in the JS emit. But, if we followed the logic from my previous paragraph, we would entirely miss every import that could have been elided based on its original state (i.e., ones that only imported types).

My point is that even if this was very easy to implement safely, it’s still not obviously desirable. You can imagine scenarios where you want to opt into the elision behavior of the original node _and_ scenarios where you don’t. So this still doesn’t seem like something we can just “fix”; I think if you want this behavior, we need to give you some way to signal it, or some way to check whether the original node would have been elided yourself, so you can just return `undefined` in your own transformer.

But again, @rbuckton (who is on vacation this week) is the expert in this area, so we really need him to weigh in here.

**Comment by andrewbranch** [comment]
> or some way to check whether the original node would have been elided yourself, so you can just return `undefined` in your own transformer

You actually do have access to this, but it’s an internal API. But if you are just looking to try stuff, you should be able to access `context.getEmitResolver().isReferencedAliasDeclaration(node)`

**Comment by nonara** [comment]
Yes, that does make perfect sense. I certainly did not mean to give the impression that I think it's an easy fix, in the sense that there is a clear path forward for a solution.

One thing I imagine that we would agree on is that if something is _recognizably_ a `Type`, it would be ideal for the compiler to never output that in the compiled js. The issue here is that the code in question broadly applies on the basis of whether it is referenced or not, which has plenty of gotchas, as you pointed out.

This is certainly one of those areas where classification of bug / feature request is a bit opaque.

Something to keep in mind is that with the present behaviour, if we touch anything on any one of these elidable nodes during transform, all regular elision functionality breaks down, and we have no easy path to remedy that. Which is simply my argument that it may have a fairly broad-impact potential for anyone doing any transformation.

It definitely does appear, though, that the determination on how (or if) to move forward is something that the team would want to make.

My use case, again, is that we're [transforming for paths and virtual directories](https://www.npmjs.com/package/typescript-transform-paths). I believe that our library is the most widely used for that purpose. We recently rewrote it to rely entirely on TS API as well as adding virtual dir support. The hope is to keep reliance on the API, even if we need to use a few internal API methods.

> you should be able to access `context.getEmitResolver().isReferencedAliasDeclaration(node)`

Having looked over `compiler/transformers/ts.ts`, there is a bit more to the logic in functions like `visitImportDeclaration`, so I think that simply calling `isReferencedAliasDeclaration` will not be sufficient to ensure that using our transformer can reasonably replicate TS's elision process. I'd also prefer to avoid trying to replicate that logic, as it may diverge.

It looks like what we need to do in the short term is to get to the elision functionality via `ts.transformTypeScript`, as it's the lowest exposed function.

Our approach will be to call `ts.transformNodes` on each applicable `SourceFile` (as-needed and only once), passing the `ts.transformTypeScript` as a transformer. From there, we can return a mutable clone of the cached transformed `ImportDeclaration` or `ExportDeclaration` node. I believe that should work. It's hacky, but it's a decent solution for now while this gets hashed out.

On a personal note, it's a shame. I was excited to make a first contribution to TS! Another time, I suppose! 😃 Thanks for the guidance on this!

**Comment by nonara** [comment]
Unfortunately, my solution seems to fail in several cases.

I'm thinking that this has is either because:
1. I'm re-using the `EmitResolver` from the parent transformation context
2. Something is mutated during the `transformNodes` process. 
   We're effectively calling `transformNodes()` on a `SourceFile` in the middle of having already called it on that `SourceFile`. Perhaps this breaking it.

### Call Example
```ts
// transformationContext is the parent transformation context

const compilerOptions = transformationContext.getCompilerOptions();
const emitResolver = transformationContext.getEmitResolver();
const transformFactory = ts.createNodeFactory(ts.NodeFactoryFlags.None, ts.createBaseNodeFactory());

ts.transformNodes(
    emitResolver,
    /* host */ void 0,
    transformFactory,
    compilerOptions, // 
    /* nodes */ [sourceFile],
    [ts.transformTypeScript],
    /* allowDtsFiles */ false
);
```

### Example stack

Not all source files fail, but many do. It seems that some nodes end up not existing when they're walked. 

```
Error: Debug Failure. Could not determine parsed source file.

    at getOrCreateEmitNode (test/node_modules/typescript/lib/typescript.js:25479:157)
    at Object.setCommentRange (test/node_modules/typescript/lib/typescript.js:25603:9)
    at visitParameter (test/node_modules/typescript/lib/typescript.js:84138:20)
    at visitTypeScript (test/node_modules/typescript/lib/typescript.js:82784:28)
    at visitorWorker (test/node_modules/typescript/lib/typescript.js:82527:24)
    at saveStateAndInvoke (test/node_modules/typescript/lib/typescript.js:82465:27)
    at visitor (test/node_modules/typescript/lib/typescript.js:82518:20)
    at visitNodes (test/node_modules/typescript/lib/typescript.js:80380:48)
    at Object.visitParameterList (test/node_modules/typescript/lib/typescript.js:80432:23)
    at visitMethodDeclaration (test/node_modules/typescript/lib/typescript.js:84048:46)
    at visitTypeScript (test/node_modules/typescript/lib/typescript.js:82759:28)
    at visitorWorker (test/node_modules/typescript/lib/typescript.js:82527:24)
    at saveStateAndInvoke (test/node_modules/typescript/lib/typescript.js:82465:27)
    at visitor (test/node_modules/typescript/lib/typescript.js:82518:20)
    at visitNodes (test/node_modules/typescript/lib/typescript.js:80380:48)
    at Object.visitEachChild (test/node_modules/typescript/lib/typescript.js:80727:362)
    at visitClassDeclaration (test/node_modules/typescript/lib/typescript.js:82882:27)
    at visitTypeScript (test/node_modules/typescript/lib/typescript.js:82736:28)
    at visitorWorker (test/node_modules/typescript/lib/typescript.js:82527:24)
    at sourceElementVisitorWorker (test/node_modules/typescript/lib/typescript.js:82552:28)
    at saveStateAndInvoke (test/node_modules/typescript/lib/typescript.js:82465:27)
    at sourceElementVisitor (test/node_modules/typescript/lib/typescript.js:82537:20)
    at visitNodes (test/node_modules/typescript/lib/typescript.js:80380:48)
    at Object.visitLexicalEnvironment (test/node_modules/typescript/lib/typescript.js:80420:22)
    at visitSourceFile (test/node_modules/typescript/lib/typescript.js:82829:54)
    at saveStateAndInvoke (test/node_modules/typescript/lib/typescript.js:82465:27)
    at transformSourceFile (test/node_modules/typescript/lib/typescript.js:82447:27)
    at transformSourceFileOrBundle (test/node_modules/typescript/lib/typescript.js:82427:20)
    at transformation (test/node_modules/typescript/lib/typescript.js:99093:24)
    at transformRoot (test/node_modules/typescript/lib/typescript.js:99120:82)
    at Object.transformNodes (test/node_modules/typescript/lib/typescript.js:99104:78)

    [Our invoked call of transformNodes starts here]

    at Object.getImportOrExportClause (src/utils/get-import-export-clause.ts:83:24)
    at src/visitor.ts:105:51
    at Object.resolvePathAndUpdateNode (src/utils/resolve-path-update-node.ts:62:12)
    at Object.nodeVisitor (src/visitor.ts:102:24)

    [Our transformer begins here] 

    at visitNodes (test/node_modules/typescript/lib/typescript.js:80380:48)
    at visitLexicalEnvironment (test/node_modules/typescript/lib/typescript.js:80420:22)
    at Object.visitEachChild (test/node_modules/typescript/lib/typescript.js:80807:55)
    at src/transformer.ts:51:31
    at transformSourceFileOrBundle (test/node_modules/typescript/lib/typescript.js:81486:57)
    at transformation (test/node_modules/typescript/lib/typescript.js:99093:24)
    at transformRoot (test/node_modules/typescript/lib/typescript.js:99120:82)
    at Object.transformNodes (test/node_modules/typescript/lib/typescript.js:99104:78)
    at emitJsFileOrBundle (test/node_modules/typescript/lib/typescript.js:99725:32)
    at emitSourceFileOrBundle (test/node_modules/typescript/lib/typescript.js:99672:13)
    at forEachEmittedFile (test/node_modules/typescript/lib/typescript.js:99423:34)
    at Object.emitFiles (test/node_modules/typescript/lib/typescript.js:99652:9)
    at emitWorker (test/node_modules/typescript/lib/typescript.js:106123:33)
    at test/node_modules/typescript/lib/typescript.js:106100:72
    at runWithCancellationToken (test/node_modules/typescript/lib/typescript.js:106203:24)
    at Object.emit [as originalEmit] (test/node_modules/typescript/lib/typescript.js:106100:26)
    at Object.newEmit [as emit] (test/node_modules/typescript/lib/typescript.js:152197:34)
    at Object.getEmitResult (test/utils/helpers.ts:92:13)
    at Object.<anonymous> (test/tests/transformer/general.test.ts:57:40)
    at Object.asyncJestLifecycle (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:53:37)
    at node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (<anonymous>)
    at mapper (node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at node_modules/jest-jasmine2/build/queueRunner.js:73:41
```

Other error messages can occur if different scenarios as well relating to nodes being missing. 

### Current implementation
You can see the current implementation of what we're doing here: [get-import-export-clause.ts](https://github.com/LeDDGroup/typescript-transform-paths/blob/0d5ecee04d09267d87028208cab83b8f20d67c06/src/utils/get-import-export-clause.ts)

### Stumped
Ultimately, I'd really prefer to simply create a new `SourceFile` with only the pertinent import / export declarations, but I'm not sure I'd be able to do that without creating a new Program instance, and that feels like adding too much overhead.

I'm fairly stumped. If you have any insight, I'd love to know if there's something I'm missing.

**Comment by AndyOGo** [comment]
The same bugs is happening for `ts-rename-import-plugin`.
https://github.com/banyudu/ts-rename-import-plugin

**Comment by rbuckton** [comment]
I can investigate loosening this behavior in `visitElidableStatement`. In the meantime I'm curious, is it feasible to implement your transform as an `after` transformer instead? There are more cases to handle (i.e., commonjs, AMD, SystemJS, etc), but import elision will have already happened by that point.

**Comment by nonara** [comment]
@rbuckton I considered going that route. It would be a breaking change, and I'm not entirely sure what edge cases may arise, so I was hoping to avoid it. If it turns out that there isn't a good solution on the TS side, I may consider making the shift in the next major version.

Perhaps it would work to remove the the `If the node has been transformed` check in `visitElidableStatement` and add checks in the visitors, where applicable. As an example, the import specifier visitor could compare the original node to determine elidability on a per-specifier basis.

Continuing the example in practice - say we have 10 import specifiers in an `ImportDeclaration`. During transform, we remove two, alter one, and add another. In that case — ideally — elision for the altered and the added would be indeterminable, but the remaining would be determinable.

**Comment by squidfunk** [comment]
Also happening for [ts-transform-paths](https://github.com/OniVe/).

**Comment by uasan** [comment]
It fixes
```JavaScript
sourceFile.resolvedModules.set(
    newPath,
    sourceFile.resolvedModules.get(oldPath)
);
```
But it looks like a hack?
