### ISSUE TITLE
JSX with es6 and commonjs modules

### ISSUE THREAD

**Issue by scottwio** [Microsoft/TypeScript#4060]
I'm using the lastest version of typescript with jsx support and there seems to be an issue when using jsx with the react flag along side es6 modules and commonjs. I've written the below which simply imports the Main component and points react router at it. Main gets imported but JSX references to main does not get converted to the module name main_1. Please let me know if I'm doing something wrong but it seems like the module name should be used here rather than an undefined 'Main' variable.

Orginal code

    import Home from 'dist/app/components/home';
    import Main from 'dist/app/components/main';
    import * as Router from 'react-router';

    var DefaultRoute = Router.DefaultRoute;
    var Route = Router.Route;

    var routes = (
        <Route name="app" path="/" handler={Main}></Route>
    );
    export default routes;

Converts to 

    var main_1 = require('dist/app/components/main');
    var Router = require('react-router');
    var DefaultRoute = Router.DefaultRoute;
    var Route = Router.Route;
    var routes = (React.createElement(Route, {"name": "app", "path": "/", "handler": Main}));
    exports["default"] = routes;
    //# sourceMappingURL=routes.js.map

Should be 

    var main_1 = require('dist/app/components/main');
    var Router = require('react-router');
    var DefaultRoute = Router.DefaultRoute;
    var Route = Router.Route;
    var routes = (React.createElement(Route, {"name": "app", "path": "/", "handler": main_1['default']}));
    exports["default"] = routes;
    //# sourceMappingURL=routes.js.map

**Comment by RyanCavanaugh** [comment]
Queuing up a fix now
