### ISSUE TITLE
Array<Array<any>> doesn't affect [] however [1, 2, 3, 4, 5] does

### ISSUE THREAD

**Issue by thetayloredman** [microsoft/TypeScript#40618]
**TypeScript Version:**  4.0.2

**Search Terms:** Typescript doesn't validate array inside array

**Expected behavior:** The example would error out because `[]` is not matching `Array<Array<any>>`

**Actual behavior:** The example continues as long as there is nothing inside the array

**Related Issues:** None

**Code**
```ts
// Example of Array<Array<any>> not being validated

function test(input: Array<Array<any>>) {
    return input;
}

test( // Expected to work
    [ // First array (Array<...>)
        [ // Second array (Array<Array<any>>)
            1,
            2,
            3,
            4,
            5
        ]
    ]
)

test( // Should not work
    [ // First array (Array<...>)
    ]
)

// Without ANYTHING inside the first-layer array, there are no errors. If I put something IN the first array, it does error out.
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// Example of Array<Array<any>> not being validated
function test(input) {
    return input;
}
test(// Expected to work
[
    [
        1,
        2,
        3,
        4,
        5
    ]
]);
test(// Should not work
[ // First array (Array<...>)
]);
// Without ANYTHING inside the first-layer array, there are no errors. If I put something IN the first array, it does error out.

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ES2015"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?module=5&ts=4.0.2#code/PTAEFEA8EMFsAcA2BTUB7AZqAggJ19AJ4A8eBJ0AdoQHw2iVoAuoARsgJaUDmoAbtEQcAJtCbJhAKEkYArpQDGTDmkqhxAZyYAKLvFlMAXDnxFSpitToBKUAG9JoJ6FzIms3Gr0GA3JIC+0po6oCAQkPDIShLqaKAA7mi4ANaOzgDaoWAAYhy4WqDQFqDaZGYAdJU01mnOGVmgAMpRqsKFxaUW5uTEVLTVtXVDAIwANINDzgBM45OTAMyzc3UALEvLTgCsE84AuoP7NZLB2g2NABZosohtjCyJKYOZYbn5LEXkJWUkleUDdYdpGEAOocJiXAw4AByAE0ACoACQAklCAOKgLgaESocGoDB5LQAWkQRGQuHa5FG6nOZNQRVQjFAZNwSQ05VASKwSNA+hYGjQsDc5y4vBR1LxBPeFipYNAwjQyA0TPwSXQBnKQA)

**Comment by DanielRosenwasser** [comment]
I'm so confused - are you expecting TypeScript to error because the first level of arrays is empty?

**Comment by thetayloredman** [comment]
Yes, I'm expecting it to error because `[]` isn't an Array of Arrays as `Array<Array<any>>` specifies I need something like
```
[ [ 1, 2, 3, 4, 5 ], [ 1, 2, 3, 4, 5 ] ]
```

**Comment by DanielRosenwasser** [comment]
That's like saying a `Set` containing no elements in it yet is not assignable to a `Set<Set<any>>`. It's just not true in this language, nor any other programming language.

You might be looking for open-ended tuples though.

```ts
type AtLeastOne<T> = [T, ...T[]];

function test(input: AtLeastOne<Array<any>>) {
    return input;
}

// Does not work
test([]);
```

**Comment by thetayloredman** [comment]
Oh, I see what I did there, thanks!
