### ISSUE TITLE
faulty function arguments contravariant checks when assigning a function to a function property of an interface

### ISSUE THREAD

**Issue by regevbr** [microsoft/TypeScript#40611]
**TypeScript Version:**  4.0.2

**Search Terms:**

- contravariant
- covariant

**Code**

```ts
interface IFunction {
  fn(x: string | undefined): void;
}

interface ILambda {
  lambda: (x: string | undefined) => void;
}

function fn(x: string): void {
  console.log(x);
}

const lambda = (x: string): void => {
  console.log(x);
};

const functionObject: IFunction = {} as any;
functionObject.fn = fn; // NOT FAILING
functionObject.fn = lambda; // NOT FAILING

const lambdaObject: ILambda = {} as any;
lambdaObject.lambda = lambda; // error TS2322
lambdaObject.lambda = fn; // error TS2322
/*
 error TS2322: Type '(x: string) => void' is not assignable to type '(x: string | undefined) => void'.
  Types of parameters 'x' and 'x' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
*/

```

**Expected behavior:**

When trying to assign a nonmatching function to an interface function property it should fail

**Actual behavior:**

When trying to assign a nonmatching function to an interface function property it doesn't fail

**Playground Link:**

[playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIDECuIFmAexGQG8AoZZGEACgA8AuZAZzClAHNkAfZbAEwgxQEPgEpGAN3zA+AblIBfUqVCRYiFKgAycALYAjPnBLlkAGz2G4jOoxZsQnHv0HCxyALwA+ZFJnylUhhsXAIiKltmVg5xX2k+EwoEQiZ8MwgAOjN8djpRAOVkkBZzSyNPZEj7GMl4zx8yJJS0zOzc2nzFeVIikuCcPEIAeX0AKwhcRgwQwaIPEgVkOCYlkABPeX7Q4bGJsAyqCqpZZAB6U+QAOSGAFWR0AEFtVEuAcSCZsJHx3AO50oMRhO5yut3uTy0L3ePRSYABVm+eymOkBxnmxEWy1WG1IFlRiN+eKsFSJQLOF2gUHwUGQNwAygAmADMDIZuLKcAJ+1JaMoIGBFKgVJp9OZrNIpwAVORKdTaYyWQzGDc1gAHFAAciq0UconqcRkGuQwBWIHwcOWTGA7BAcH06WQYHwjrVmu1DicvBAAiEIBEeu8Br4GoyphV6pW+BgyFVcCgeggahWGtoRrg3uQKbTUBQoGSuljeHtmVMFHDmuqjm4Xp9biNJuQZotTCtNrtDqdLvVmcr7BDpYotNdmZcvpE9dN5qWLettuLjudYGHGt7-clp1IQA)

**Comment by MartinJohns** [comment]
TypeScript FAQ: [Common "Bugs" That Aren't Bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs)

> A method and a function property of the same type behave differently.
> - Methods are always bivariant in their argument, while function properties are contravariant in their argument under `strictFunctionTypes`. More discussion [here](https://github.com/microsoft/TypeScript/pull/18654).

**Comment by regevbr** [comment]
Thanks @MartinJohns
