### ISSUE TITLE
Uncaught uninitialized class member with Symbol key

### ISSUE THREAD

**Issue by soul-codes** [microsoft/TypeScript#40617]
**TypeScript Version:** 4.1.0-dev.20200917

**Search Terms:**
symbol class member uninitialized 

**Code**

```ts
const Foo = Symbol()

class WithFoo {
  [Foo]: any[]; // this shouldn't be allowed without an initialization in a constructor
  Foo: any[]; // compare with this, which errors as expected
}

console.log(new WithFoo()[Foo].length) // uncaught uninitialized symbol member, oops
```

**Expected behavior:**
An error like `Property 'Foo' has no initializer and is not definitely assigned in the constructor` should also be emitted for the _symbolic_ property `Foo`.

**Actual behavior:**
No such error is thrown.

**Playground Link:** 
[here](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200917#code/MYewdgzgLgBAYiEMC8MDKBPAtgIxAGwAoBKAKFOHwEMIIYB1ASygAsEkBvUmGAbXYC6ALhhUwGXgIDc3eIhFiJ00gF9yoSAQCmAOnwgA5oTBaA7g2ZtEJfogF6tYA62IwA9G5iIADhCA)

**Comment by andrewbranch** [comment]
Actually, it looks like this is true of _any_ computed property declaration 😦 

https://www.typescriptlang.org/play?ts=4.0.2#code/MYGwhgzhAEDqCWAXAFgMQPbugbwFDWgG0AiAI3GWIF0AuaMAOwE9CqBufaDdOxl93AF9cuYOgYR0IAKYA6EOgDmACgbSA7nCRpMygJSzyYZPOkNFKPdAD016JgAOEIA

**Comment by a-tarasyuk** [comment]
`isPropertyInitializedInConstructor` doesn't support `ElementAccessExpression`, only `PropertyAccessExpression`.

```ts
function isPropertyInitializedInConstructor(propName: Identifier | PrivateIdentifier, propType: Type, constructor: ConstructorDeclaration) {
    const reference = factory.createPropertyAccessExpression(factory.createThis(), propName);
    setParent(reference.expression, reference);
    setParent(reference, constructor);
    reference.flowNode = constructor.returnFlowNode;
    const flowType = getFlowTypeOfReference(reference, propType, getOptionalType(propType));
    return !(getFalsyFlags(flowType) & TypeFlags.Undefined);
}
```

I think we can be extended to use both `ElementAccessExpression` and `PropertyAccessExpression`, however, I'm not sure that `getFlowTypeOfReference` can resolve the right type for `ElementAccessExpression`s with `Identifiers`.

```ts
const Foo = Symbol()
class WithFoo {
  [Foo]: any[];
  ["prop"]: any[];

  constructor() {
    this[Foo] = []; ??
    this["prop"] = []; Works
  }
}
```

@andrewbranch What do you think?

**Comment by andrewbranch** [comment]
@a-tarasyuk you’re right, that would require https://github.com/microsoft/TypeScript/issues/36230. Maybe the current behavior is intentional, then, as we’re looking at a choice between _always_&sup1; issuing the uninitialized error or _never_ issuing it. 😕 

&sup1; “always,” unless the initialization is on the class field itself, or the error is suppressed with `!`. These are pretty good as workarounds go, but I’m not sure they’re good enough to merit this change.

**Comment by andrewbranch** [comment]
I don’t know though, it seems like issuing the error when _there is no constructor_ would be better than nothing...
