### ISSUE TITLE
Can't make mapped types with `as` clauses be homomorphic

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40619]
I can't seem to find a way to make a mapped object type be homomorphic when it has an `as` clause.

```ts
type Getters<T> = {
    [K in keyof T as `get${capitalize string & K}`]: () => T[K]
};

interface Person {
    readonly name: string;
    age: number;
    location?: string;
}

type LazyPerson = Getters<Person>;
```

None of the modifiers from `Person` are preserved on `LazyPerson`. What is the right way to do this? Is there one?

**Comment by ahejlsberg** [comment]
Hmm, that's a bug. I'll work on a fix.
