### ISSUE TITLE
NumberFormatOptions is missing currencySign option

### ISSUE THREAD

**Issue by ericregnier** [microsoft/TypeScript#40622]
`currencySign` is missing from `NumberFormatOptions`

**TypeScript Version:**  4.1.0-dev.20200916

**Search Terms:** NumberFormatOptions notation

**Code**
```ts
const str = new Intl.NumberFormat('en-NZ', { style: 'currency', currency: 'NZD', currencySign: 'accounting' }).format(999999);
```

**Expected behavior:**
I should be able to use NumberFormat's notation option. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Actual behavior:**
Argument of type '{ style: string; currency: string; currencySign: string; }' is not assignable to parameter of type 'NumberFormatOptions'.
  Object literal may only specify known properties, and 'currencySign' does not exist in type 'NumberFormatOptions'

**Playground Link:** None

**Related Issues:** #36533

**Comment by RyanCavanaugh** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
