### ISSUE TITLE
Improve type inference by checking of property types

### ISSUE THREAD

**Issue by iantropov** [microsoft/TypeScript#40626]
## Search Terms

type inference, type annotation, self-reference, index signature

## Suggestion

Allow to infer generic type parameters from types of properties

## Use Cases
For the following example

```typescript
type State = {
    a: string;
    b: number;
}

type Handler<K extends keyof State> = {
    name: K,
    parse: (value: string) => State[K],
    serialize: (value: State[K]) => string
}

const handlerA: Handler<'a'> = {
    name: 'a',
    parse(value) { return ''; }, // knows that I should return State['a'] = string
    serialize(value) { return ''; }
}

const handlerB: Handler<'b'> = {
    name: 'b',
    parse(value) { return 1; }, // knows that I should return State['b'] = number
    serialize(value) { return ''; }
}

```
In this example I should duplicate name of attribute that isn't good.

Also, I tried with self-reference variant:

```typescript
type State = {
    a: string;
    b: number;
}

type Handler = {
    name: keyof State,
    parse: (value: string) => State[Handler['name']],
    serialize: (value: State[Handler['name']]) => string
}

const handlerA: Handler = {
    name: 'a',
    parse(value) { return ''; }, // correctly allows to return string
    serialize(value) { return ''; }
}

const handlerB: Handler = {
    name: 'b',
    parse(value) { return ''; }, // INCORRECTLY allows to return string
    serialize(value) { return ''; }
}
```
but in this case `value` in `parse` and `serialize` will have all possible types from `State`, when I need the specific. 

## Examples

If this feature will be implemented it will be useful for such constructs (with correct type checking):

```typescript

const handlerA: Handler = {
    name: 'a',
    parse(value) { return ''; },
    serialize(value) { return ''; }
}

const handlerB: Handler = {
    name: 'b',
    parse(value) { return 1; },
    serialize(value) { return ''; }
}

const handlers: Handler[] = [
    {
        name: 'a',
        parse(value) { return ''; },
        serialize(value) { return ''; }
    },
    {
        name: 'b',
        parse(value) { return 1; },
        serialize(value) { return ''; }
    }
]
```

Lets check the following
## Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
What you propose wouldn't be type-safe. A simple example would be: `handlers[0].name = 'b'`

And when a handler is passed along? The compiler couldn't know anymore what actual values are inside.

If writing the duplicate name attribute is a hassle for you, then you can just create a helper function:

    function createHandler<K extends keyof State>(handler: Handler<K>): Handler<K> {
      return handler;
    }

    const handlerA2 = createHandler({
        name: 'a',
        parse(value) { return ''; },
        serialize(value) { return ''; }
    });

But you absolutely can't remove the key-type when you want to remain type-safe.

**Comment by RyanCavanaugh** [comment]
I can see the use case here and I think we've seen proposals for treating something like
```ts
const a: Handler<infer> = { ...
```
but this suggestion doesn't seem like the right approach. This code already means something else and there'd need to be some other mechanism for doing self-inference into an object literal.

**Comment by iantropov** [comment]
OK, thanks for your considerations - they make sense.
