### ISSUE TITLE
Feature Idea. Document how to do common things, like extend Express Request object.

### ISSUE THREAD

**Issue by stoplion** [microsoft/TypeScript#40621]
I have read through 25+ different implementations on how to do this seemingly simple thing. And NONE of them worked.

Here is my original SO post. https://stackoverflow.com/questions/63945039/typescript-confusion-how-to-extend-express-request-with-custom-and-definitely

It is ridiculous that this so hard to get to work. It should be easier..

**Comment by orta** [comment]
@andrewbranch's answer to this SO could be used to extend this doc: https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-plugin-d-ts.html
