### ISSUE TITLE
TypeScript compiler halts before finishing compiling files to resolve error (VS2013+TS1.5Beta)

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/TypeScript#4063]
I'm in a case where I've written a new class and referenced it in another file.

The first file is causing a compile error as it doesn't know about the new class, but VS/TS won't generate the new class file as it's hitting an error on the reference first...

Seems like it's just stuck.  The only way for me to get through it is to remove the reference in the file.  Let it compile my class and then reference it.

This seems to be the most direct example, but I've noticed this in other places when trying to add/change methods around and just having the compiler get stuck is slowing things down.

**Comment by danquirk** [comment]
Are you seeing this with the final 1.5 bits? A minimal repro would be helpful if possible.

**Comment by mhegazy** [comment]
@hawkerm can you provide more information..

**Comment by hawkerm** [comment]
Sorry I haven't had a chance to try and isolate or repro it consistently in a controlled environment yet, been pretty heads down lately trying to fight with some other issues.

**Comment by mhegazy** [comment]
thanks @hawkerm for getting back on this. i will close this one then. Feel free to reactivate if you run into it again.

**Comment by hawkerm** [comment]
Hi @mhegazy, ended up hitting it again.

I'll have to see if I can setup a small project which can show this consistently.  For now, this is what I see in VS2013 with TypeScript 1.5.

While running my code in the debugger, I'll update my class's constructor and make the corresponding updates to where its instantiated in my code.

TypeScript won't recompile it right-away and it'll start complaining that the lines where its instantiated don't match the call signature (as it hasn't recompiled the class).

This issue now persists across stopping debugging and even reloading VS (trying to 'save' the class doesn't force it to recompile just that one file either).  It's effectively halting itself from compiling the root class due to the dependencies having 'errors' which are because it hasn't recompiled the root dependency.

To resolve the issue, I have to go comment/change the instantiated calls out/back in order to get it to recompile the class first in order to resolve the conflict.

**Comment by mhegazy** [comment]
We will need more information to diagnose the issue. A project exhibiting these symptoms would be ideal.

**Comment by mhegazy** [comment]
do not think this is actionable without more information. closing again. please provide a sample project or repro steps to be able to investigate.
