### ISSUE TITLE
notApplicableReason not included in protocol.d.ts

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#40640]
Looks like `RefactorActionInfo.notApplicableReason` never made it into `protocol.d.ts`. This property does seem to be sent along by the TS Server, it is just the typings for the property that is missing

Confirmed with TS 4.0.3

**Comment by DanielRosenwasser** [comment]
@jessetrinity can you fix this and cherry-pick the changes to `release-4.0`?

**Comment by jessetrinity** [comment]
@DanielRosenwasser the only way I can tell how to do this is running `gulp LKG`. Do I update `protocol.ts` and run `LKG` to get the new `protocol.d.ts.` (along with everything else `LKG` produces)?

**Comment by DanielRosenwasser** [comment]
The LKG can be done prior to the publish - in other words, don't worry about `protocol.d.ts`, just fix up `protocol.ts`.
