### ISSUE TITLE
Imported types are not resolving 

### ISSUE THREAD

**Issue by paboulos** [microsoft/TypeScript#40642]
**TypeScript Version:**  4.0.2

**Search Terms:**
type inference
reference types
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

/// <reference types="node-fetch" />
import { request, IncomingHttpHeaders, RequestOptions } from "http";
import { URL } from "url";

interface NodeOptions {
  url: URL;
  options: RequestOptions;
}

function mapFetchParameters(
  urlInfo: RequestInfo,
  init?: RequestInit
): NodeOptions {
  const reqUrl =
    typeof urlInfo == "string" ? new URL(urlInfo) : new URL(urlInfo.url);
  let headers = {};
  let method: string = "";
  let port = "80";
  if (urlInfo instanceof Request) {
    Object.assign(headers, urlInfo.headers);
    method = urlInfo.method;
    port = urlInfo.port.toString();  // ERROR??
  }
  if (init) {
    method = init.method ? init.method : "";
  }
  const options = {
    host: "localhost",
    port: port,
    path: "/posts",
    method: method,
    headers: headers,
  };
  const res = {
    url: reqUrl,
    options,
  };
  return res;
}
```

**Expected behavior:**
 Compiler should find the port class property on the Request class.
The @types/node-fetch index.d.ts exports
export type RequestInfo = string | URLLike | Request;
export class Request extends Body {
  method: string;
  ...
 port?: number;
}
**Actual behavior:**
error TS2339: Property 'port' does not exist on type 'Request'.

71     port = urlInfo.port.toString();

**Playground Link:** 
https://www.typescriptlang.org/play?#code/PQgEB4CcFMDNpgOwMbVAFwJ4AdoGcBeAIkQHsATaAWnnWQAsjRgA+AKAEsBbbUydUAG9QAJWgBHAK750AeWzoOpRHlABfULEikuoIvXTpsRANycefAcICqIgDLrN23UUmQANqbadE6BLABDVFAAOQpoeUVlVUE2UFA3dwAuUFs7M3jSBSUVFLEpGUicvDM1b1hJFCjEUC4A7AAxaDp6AAUAyACuZoQ8AAo4hI8ASURYUjyJaTx0UfGAGkGORA50AH5JgpnR1bYAShSwyiLooUHkaIEYcWsPUAJB+KxcUlgh9znSe4I9GchlgDmTDWoEQ0AA7ql7H1Ep89qAUmDIWkYSMxqQAHSJPYZUDuZqgejQAKUSCqH6CNS4-ECbroegUFJ-QH3PReeI00C8fisogADgADOzQBw3qiPuiRSp0AEUNBXqIpjJ4bF4vFZAAjABW0GQ6AxATweA4AMQfSJJN683enwxFtJeBxj1qzQZ5FZsPRGLpbtx8W5Ah+nvGGIDGPQpAAyuh-ogAX0nfEyvFRaA+stVirnT6KKyM-qc+6Qfnva7cykiMLk6ALtLQFlquSzmrCaQZhX3KRkAF3AyZkRFi2AykA4O1dgAvSK8BeDM8APs2XyClC2P4vbeikN2Sx1TzpdQDAm6q1YkUtdbu41-XstFd7iYOg3DUj6U2EA
**Related Issues:** 
**GitHub Link**
https://github.com/paboulos/http-types

**Comment by MartinJohns** [comment]
From the [documentation](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-):

> Use these directives only when you’re authoring a `d.ts` file by hand.

It doesn't seem to me that you're writing a `d.ts` file. You should just use an import statement in your regular code.

**Comment by paboulos** [comment]
The type is imported through package.json and tsconfig. How do I import types without installing node-fetch module? I want to reuse only the types and publish to npm, without node-fectch implementation module as a dependeny. 
This documentation here https://github.com/definitelytyped/definitelytyped/#definitelytyped says:
"The types should then be automatically included by the compiler. You may need to add a types reference if you're not using modules:

/// <reference types="node" />"

**Comment by paboulos** [comment]
I  [updated ](https://github.com/paboulos/http-types/tree/master/lib/%40types)the type reference directive in a local index.d.ts and changed typeRoots in tsconfig. Getting additional errors from compiler:
lib/index.ts:5:8 - error TS2304: Cannot find name 'HttpRequest'.

5   api: HttpRequest,
         ~~~~~~~~~~~

lib/index.ts:7:12 - error TS2304: Cannot find name 'HttpResponse'.

7 ): Promise<HttpResponse<T>> {
             ~~~~~~~~~~~~

lib/index.ts:8:15 - error TS2304: Cannot find name 'HttpResponse'.

8   const resp: HttpResponse<T> = await api(request);
                ~~~~~~~~~~~~

lib/index.ts:61:20 - error TS2339: Property 'port' does not exist on type 'Request'.

61     port = urlInfo.port.toString();
                      ~~~~

**Comment by RyanCavanaugh** [comment]
This looks like a misconfiguration of some sort, not a bug. We can investigate if there's something clear pointing to a defect, but I don't see evidence of that here.

**Comment by paboulos** [comment]
You explanation should include a reference to spec or doc saying so. Technical answers shouldn't be based on intuitive feelings.

**Comment by RyanCavanaugh** [comment]
That's fine either way, because this is a bug tracker, not a forum for answers.

**Comment by paboulos** [comment]
If something doesn't work it's a bug until you can prove it otherwise. I haven't seen anything like that yet.

**Comment by RyanCavanaugh** [comment]
I looked at the repo and I can't tell why you think this should work

 * `HttpRequest` is declared in a module file (`index.d.ts`), not a global, so it's not going to be visible in `index.ts` without an import. This behavior is documented
 * Same for `HttpResponse`
 * A file in `@types/index.d.ts` doesn't belong to any package because it's not in a folder. This isn't going to get picked up automatically; it doesn't match any existing pattern so it seems to have been put there on accident?
 * You've tested for `instanceof Request` where `Request` is the built-in DOM Request object, not the `node-fetch` `Request` object. This is because you are using the default `lib` option which includes `dom`, and because you didn't import `Request` from the `node-fetch` library

**Comment by paboulos** [comment]
The problem is with node-fetch type Request.port? Are you saying the only way TypeScript lets you import types without using the module is to make it a global namespace?
