### ISSUE TITLE
forof after transform will execute error if target is es5

### ISSUE THREAD

**Issue by agileago** [microsoft/TypeScript#40643]
**TypeScript Version:**  4.0

**Search Terms:**

forof tranfrom code is error

**Code**

```ts
const list: any[] = []
for (const comp of list) {
    comp.sp.y = comp.sp.r.find(k => k.c == (comp.xp ? '1' : '0'))
    for (const item of comp.c) {
        item.v = !!item.t?.length
    }
}
```

**Expected behavior:**

right transform code

**Actual behavior:**
```ts
"use strict";
var _a;
var list = [];
var _loop_1 = function (comp) {
    comp.sp.y = comp.sp.r.find(function (k) { return k.c == (comp.xp ? '1' : '0'); });
    for (var _i = 0, _a = comp.c; _i < _a.length; _i++) {
        var item = _a[_i];
        item.v = !!((_a = item.t) === null || _a === void 0 ? void 0 : _a.length);
    }
};
for (var _i = 0, list_1 = list; _i < list_1.length; _i++) {
    var comp = list_1[_i];
    _loop_1(comp);
}
```

`_a = item.t` will execute error on runtime. because the `_a` is reassign. next loop will execute error

**Playground Link:** 
https://www.typescriptlang.org/play?removeComments=true&target=1#code/MYewdgzgLgBANgS2gLhgQzATwNoF0YC8MeAUAGYgBOMAFKJLKALYAOMIZ8SUAlDAN4kYwmMxYA6CBMyFRIVpImVxZBGAAmNANaEAfDC3jghInXkSAHmwD8MAOQBGOzFR2ADHZ48hIitTMMMAhQAKZM7JxiRnyCInFBoUziAG6yAIRpwWHiUNbicCFgAOZQABY+wgC+JJVAA
**Related Issues:**

**Comment by dezsiszabi** [comment]
Was the fix for this included in `4.1.1`?
