### ISSUE TITLE
Type guards in parenthesis throws syntax error 

### ISSUE THREAD

**Issue by GheorgheP** [microsoft/TypeScript#40655]
**TypeScript Version:**  4.x.x

**Search Terms:** type guards, parenthesis, syntax error.

**Code**

```ts
declare function isSame<A extends B, B>(a: A): (b: B) => b is A
declare function isSame<A extends B, B>(a: A, b: B): b is A
declare function isSame<A extends B, B>(a: A, b?: B): (b is A) | (b: B) => b is A
```

**Expected behavior:** I'm trying to create a curried generic `isSame` with type guards so I can use it in compositions.
But I get syntax error when i try to wrap the type guard in parenthesis, as my result is a type guard or a function that returns a type guard.

**Playground Link:** https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxAEdkoIBnAHgEECAPDEVYM+AIQBo2A+ACigC54VAJSCeAI0Gth8ALxd44+FhZUAUKEiwEKdNjwFipSjRD1GzNp1a8BQzpLajFy1RvDQ4SNJlz4iJOTUdAxMLBzcfIJUDgD8Us4SrkIyAD7wEglyCkoqQmpAA

**Comment by RyanCavanaugh** [comment]
Type guards don't function unless they're a bare return type, so even if this weren't a syntax error, it wouldn't work. You'd need a type assertion regardless since there's no way to narrow to a type guard type.
