### ISSUE TITLE
Filtering keys does not work with generic types

### ISSUE THREAD

**Issue by Pauan** [microsoft/TypeScript#40654]
**TypeScript Version:**  4.1.0-dev.20200920

**Search Terms:** filter key generic

**Code**

```ts
// Selects all the keys from T which have a value of V
type SelectKeys<T, V> = { [K in keyof T]: T[K] extends V ? K : never }[keyof T];

//================================================================
// Using a concrete type works
interface Foo {
    yes: string;
    no: number;
}

let foo: Foo = {
    yes: "hello",
    no: 5
};

// This function can only be called with keys which have a value of string
function lookup<Key extends SelectKeys<Foo, string>>(key: Key): string {
    return foo[key];
}

lookup("yes");
lookup("no"); // This error is correct

//================================================================
// Using a generic type T does not work
class Bar<T> {
    private bar: T;

    constructor(bar: T) {
        this.bar = bar;
    }

    // This method can only be called with keys which have a value of string
    lookup<Key extends SelectKeys<T, string>>(key: Key): string {
        // This error is NOT correct
        return this.bar[key];
    }
}

new Bar<Foo>(foo).lookup("yes");
new Bar<Foo>(foo).lookup("no"); // This error is correct
```

**Expected behavior:**

No error occurs.

**Actual behavior:**

The following error occurs:

```
Type 'T[SelectKeys<T, string>]' is not assignable to type 'string'.
 Type 'T[T[keyof T] extends string ? keyof T : never]' is not assignable to type 'string'.
   Type 'T[keyof T]' is not assignable to type 'string'.
     Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'string'.
       Type 'T[string]' is not assignable to type 'string'.
```

**Playground Link:** [[Link]](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200920#code/PTAEGUFMBtIYwC4GdQENrVAgFpUBrSATxQDMAnAewFtQAVUAd2wEs5tRtUA3PVUbugCueSqVAA1AFAIiABzxRYiANLEkAHjoAaSQD5QAXlABvUAG0VoFgDsCxMfQC6ALnqWnoSAA8EkGwAmKBKgAPygVm42kLzkoAC+5oREjnROANxSUiCGuXn5BYVFxSWlJdlgAKpItgDmaKBwlDZw5JB+WPJ4jJTk+EhStn7kpKhweABilJSmUqDzoESQSG5ICOR1mQugNpRRQtQARpDkmfFZsAigpNNuUzPGJnMLSyugAES4GJTv2s-zuzcAFYpPFMhV6KwyEIWggWM1Gqg7M1oERQMdERhIAEmCwcPYSExWOxODw+AJhKJxGsNjZalJSDDEPC7NBpvghHINGo0T4-IEUEp4AgeZp7roaXU9HoABTJNw8gCUq3WdVm2zaCCE5DsN0oSWIGVBF3ZnJl71e70VmTZlA5cnNuyt6VAIEhLBQJyocQ9jV6bUQWRyZRDobDoYh1TV-Fq-hObE6CnooAClGWO0oVx6fSkcGgqCQKAAQqhyFoDE9tnINoIOodS246ODtk0bDShIhejL6+RG4r1dsFjgPQA6HtGdGlrYLc7-V1gOhQ0DUdrYSg4uBI0AotEYzdYnGMPEcZIoZhsDhcXgNQTQETb6mqulz2327nELy+fxBCAwYWirQJSfWppTlYgFWIZVQElOkB0Hed3U9chvWsFAADkAHkGCaZDhTnDV2m1OxhyQMdSwNIgjW2c5Z2iRhQBLMt7llPVFRHV8zQtZZnSkOiGNLDRmJlVj2NNB13ida0EMXX0vV6VC-VwxAgA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/28111 https://github.com/microsoft/TypeScript/issues/30728 https://github.com/microsoft/TypeScript/issues/38646

**Comment by jack-williams** [comment]
See #39972 and the associated links.

**Comment by RyanCavanaugh** [comment]
👆
