### ISSUE TITLE
change return type declaration from single colon ':' to double colon '::'

### ISSUE THREAD

**Issue by alienfetuseater** [microsoft/TypeScript#40651]
## Search Terms
Function return signature formatting

## Suggestion
My proposal is to change the format for the function return signature from the current single colon 
```
function sum(a: number, b: number): number {
return a + b
}
```
to the more common double colon used in return signatures for functions, ie c++:
```
function sum(a: number, b: number):: number {
return a + b
}
```

## Use Cases
in the above trivial examples, the distinction may not seem helpful. but many typescript users develop using formatters, like prettier and others which can make recognizing where parameters of a function end, and the return signature begun unclear.

## Examples
```
export default function sideForm(
	leadStore: leadStateObject[],
	formStore: Map<string, formFeatureObject[]>,
): { 
propertyA: otherInterface[],
propertyB: Map<number, otherInterface[]>
 } {
```
this example shows how it can begin to become less obvious which part of a function definition we are looking at. moving to a double colon more inline with other strong and staticly typed languages would improve the ease of recognizing where the return type begins:

```
export default function sideForm(
	leadStore: leadStateObject[],
	formStore: Map<string, formFeatureObject[]>,
):: { 
propertyA: otherInterface[],
propertyB: Map<number, otherInterface[]>
 } {
```

I am aware of the proposed bind operator, however distinguishing between the two would be un-ambiguous from context, and the bind operator would likely be used much less frequently than return typing function definitions 
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by kitsonk** [comment]
> This wouldn't be a breaking change in existing TypeScript/JavaScript code

You said this proposal wouldn't do that, it would break all existing TypeScript code... 😭 

Also, you said it is aligned to the rest of TypeScript's design goals.  This would break the following design goal:

> 11. Do not cause substantial breaking changes from TypeScript 1.0.

**Comment by MartinJohns** [comment]
If you're having trouble reading your code then you're free to format it differently.

**Comment by alienfetuseater** [comment]
> > This wouldn't be a breaking change in existing TypeScript/JavaScript code
> 
> 
> 
> You said this proposal wouldn't do that, it would break all existing TypeScript code... 😭 
> 
> 
> 
> Also, you said it is aligned to the rest of TypeScript's design goals.  This would break the following design goal:
> 
> 
> 
> > 11. Do not cause substantial breaking changes from TypeScript 1.0.
> 
> 

Your right, my mistake thank you for pointing that out
