### ISSUE TITLE
Inference not working correctly unless I add an unused property to my interface

### ISSUE THREAD

**Issue by CyberPhoenix90** [microsoft/TypeScript#40656]
**TypeScript Version:**  4.0.2
Although I tried many versions and they all have some form of this bug

**Search Terms:**
Infer Inferrence
**Code**

```ts
export interface Operator<T, M> {
	someProperty:string;
	// If this function is not here type inference will break. Name is irrelevant but it has to exist
	typescriptBugWorkaround?: (value: T) => M;
}

export interface MapOperator<T, M> extends Operator<T, M> {
	someProperty:string,
	operation: (value: T) => M;
}

export function mapper<T, M>(mapper: (value: T) => M): MapOperator<T, M> {
	return {
		someProperty: 'MapOperator',
		operation: (v) => mapper(v)
	};
}
class Thingy<T> {
	 transform<A, B = A, C = B, D = C, E = D, F = E, G = F, H = G, I = H, J = I, K = J>(
		operationA: Operator<T, A>,
		operationB?: Operator<A, B> ,
		operationC?: Operator<B, C> ,
		operationD?: Operator<C, D> ,
		operationE?: Operator<D, E> ,
		operationF?: Operator<E, F> ,
		operationG?: Operator<F, G> ,
		operationH?: Operator<G, H> ,
		operationI?: Operator<H, I> ,
		operationJ?: Operator<I, J> ,
		operationK?: Operator<J, K>
	): J {
    //Implementation irrelevant
    return undefined as any;
}

}
const thingy = new Thingy<number>();

//This works correctly as long as the bug workaround function exists but fails to compile due to wrong inference otherwise
const value:{ test: number} = thingy.transform(mapper(a => a.toString()), mapper(b => parseInt(b)), mapper(c => ({ test: c})));
```

**Expected behavior:**
No extra property needed in the Operator interface

**Actual behavior:**
Inference breaks unless unused seemingly random property is present

**Playground Link:**
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgeTDUxmgB4AVAGjgFkA+OAbwCgBIAZwgFtgAFKBCKwAngC4OMKMgDmAbnYB6RXACS6ODAAWCDnHQBXJNhgIISRHqQR4WtHhgiiiJOnvG8AdwQAbH3AAjKGBMAGsAOjgAOUxeS0QoYJ9gADdMFECDeARbTD1SOFBdGHZHIg5saTAYACEDGQB1aFDMQSMAEwB+MTgACjSfA2AeigBKOABeRloFAF8WFlBIWBdUDBw8WkwwQmJSKEoaBkKQVCR2vV2oEnJqOkZWTh5+QWFHCSlZKnYhPbMkHr9TCDYZwMaTaZzBZLaDwQzGUzmODcbbCQ73XoosDCQEDIYjcZTOijHpbHbCG4HO7HR7BGAGKAWR5PXgCX6iHoAcjJV0pnO+bDY7JI-1xhMYWOE-VG7FmUOwPjyegoOiQMhElAe7E01yQHHQ0G4ZAAgjQapM4Ka4ABhC01GgAEQt1poAFELQ6aAAxC2umgAcQtXpoAAkLf6aKoLSGaAApC2qGgAaQtsfovXYQopiKQxp6vP26ON9AFWb+5hq3QI2fIVpqjFLwpz1qrBfI9ptDczTf+DtbNYOLrgDq7gp75ld-b25E9cFdo7L1xzXqnS-IfrgXoX46Q-tXlLIwbg-u32f+If3hYjcBDp-LSFUl-IMbUd6X-1jT4OibgabgjbPcwky-MhY2Teh2BJX9mBYOA4LgZRVG4MBkl4FARSRBBEmAZI0hQWD4LpBkLA6YB0GQYB2jgPJqKQEQoRYeZsHMSRNFVdULSQYBPDBdiNSQAxuACNB01GBQWGUFVdDgTxmj0ZjsJMHwRGovQfHMGRVLYvAAnqGTmlaCAOn0IwTH+E5ij0XT4CCEJQj0Gw7CgbwOGAFhmL1eA8WGJhNGASQegEoS0FmC1tFkERwikdJ9UNTFUTQXpMAhaioogABlT41V6UZRhoSVEoCFKwFaVzVBQXoAly-KEqgXpsBS3pfNQAK4GwWZcrElggA

This is really confusing to me for some reason the inference suggests that my type is unknown unless I add an unused property to my interface. I admit the type interactions in this example are a bit complex I am open for suggestions on how to rephrase this but I still think it's a bug

**Comment by AlCalzone** [comment]
```ts
export interface Operator<T, M> {
	someProperty:string;
}
```
is not generic and has nothing to infer the generic types from. What would be `T` and `M` in this call?
```ts
thingy.transform({someProperty: "foo"}, {someProperty: "bar"})
```
Both arguments are allowed if you constrain to `Operator`.

**Comment by CyberPhoenix90** [comment]
OK I see where the issue is coming from, I should just add operation: (value: T) => M; to the operator interface. My bad
