### ISSUE TITLE
Incorrectly identifying numbers as strings

### ISSUE THREAD

**Issue by Datarowe** [microsoft/TypeScript#40673]
**TypeScript Version:**  4.0.2

**Search Terms:**
template literal adding numbers 

**Code**
```ts
const a: string | undefined = '';
const b: string | undefined = undefined;
if((a ?? '').length + (b ?? '').length === 0){
  console.log('empty');
}
```

**Expected behavior:**
Log to the console

**Actual behavior:**
getting an error with "Use a template literal instead of concatenating with a string literal" on line 3 (using airbnb, tslint-config-airbnb)

**Comment by DanielRosenwasser** [comment]
Sounds like you are having issues with a linter plugin, not TypeScript.

**Comment by Datarowe** [comment]
It's only being identified on compile with npm, not within VS Code, and I have no linter extensions installed (just reinstalled my computer).

I've been trying to reproduce anywhere outside of my environment, but not getting the issue.

**Comment by RyanCavanaugh** [comment]
Again, this message is produced by a linter, not by TypeScript, so we have no control over it

**Comment by DanielRosenwasser** [comment]
Check whatever scripts you're running with npm are just calling tsc and not something else.
