### ISSUE TITLE
Tagged union narrowing fails

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#40676]
**TypeScript Version:**  4.0.3

**Search Terms:** Narrowing, union, tag, discriminated, prop

It seems that I'm unable to narrow an object union based on its properties. Apologies in advance if this is by design / a fluke.

**Code**

Let's say we have the following interface.

```ts
interface Base {
  a: {
    b: {
      c: string;
    };
  };
}
```

And we create two variations.

```ts
interface One extends Base {
  a: {
    b: {
      c: "one";
    };
  };
}

interface Two extends Base {
  a: {
    b: {
      c: "two";
    };
  };
}
```

Then we define fns that accept the specific variations.

```ts
declare function acceptsOne(one: One): void;
declare function acceptsTwo(two: Two): void;
```

Let's create an instance of base.

```ts
declare const oneOrTwo: Base;
```

And finally, let's try to do some narrowing.

```ts
switch (oneOrTwo.a.b.c) {
  case "one": {
    oneOrTwo.a.b.c; // of type `"one"`
    acceptsOne(oneOrTwo); // type error
    break;
  }

  case "two": {
    oneOrTwo.a.b.c; // of type `"two"`
    acceptsTwo(oneOrTwo); // type error
    break;
  }
}
```

The `acceptsOne` and `acceptsTwo` usage produces a type errors :/

The same is true for use within an if statement that checks the string's value.

```ts
if (oneOrTwo.a.b.c === "one") {
  oneOrTwo.a.b.c; // of type `"one"`
}
```

**Expected behavior:**

Given that the type of `oneOrTwo.a.b.c` is effectively narrowed within the switch cases / if blocks, I'd expect that `acceptsOne` or `acceptsTwo` would not throw type errors, as the types are structurally compatible with they `accepts[One|Two]` fns respectively.

**Actual behavior:**

[Playground Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnJwBcyeBBARiWeQQiRmFKAOYDc+5AvhwT7l1y5QkWIhQB5ECggAPSCAAmGNJhydipTpWrby9ZACIA9tMO9uF-oOHho8JMgAqAd2PI5C5aqxaCmmh0-WmQDQzA3cz1+Pg4bRQgEABs4KBQYAFcQBDBgU0IEJAAHMAwpCAAKUwgScoBKEgA3Y2BFDgTk1PSsnLyQAuLS12MKiOMSYYbkZtaOXA6UtNDTRmRqiShhknQsOYwXYDAEAAtkKukN4YA6OCuKK4Q64IQ1I2rDXVp1zbcbu4e2MgAPRAtYwZBgACeRRQAAMTGZYXpEIMytJzhBLm46oCQRDoTIoFBjFA9BQ0nAANZWIR0V7hSKfcjfa63e4IXGg4zgqEw5DwsaGJG0FEQEoYYYYrHGHHA0G8wnE0m0ckQKk0mzAcFSn7GP7s5AAXmNbzMTxoLN+bIBcrB+L58PeSMEQA)

**Comment by sam-goodwin** [comment]
I think the problem is with 

```
declare const oneOrTwo: Base;
```

`Base` is not a union type, so TS cannot narrow since it is not aware of all the sub types of Base.

**Comment by sam-goodwin** [comment]
Also, I don't think TS can narrow a type based on nested properties. The property you're discriminating on will have to be on the top level.

**Comment by RyanCavanaugh** [comment]
There's nothing preventing this type from existing and being passed into your function accepting a `Base` (imagine for the sake of argument that `One` had some other fields that are missing or of incompatible types in `Three`):
```ts
interface Three extends Base {
  a: {
    b: {
      c: "one";
    };
  };
}
```

**Comment by harrysolovay** [comment]
Thank you for the explanation!
