### ISSUE TITLE
Enable "Convert to template string" on expressions that don't start with a string

### ISSUE THREAD

**Issue by morganwdavis** [microsoft/TypeScript#40671]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20200916

**Search Terms**
- convert to template string
- refactoring / code action

([see comment for condensed repro of the problem](https://github.com/microsoft/TypeScript/issues/40671#issuecomment-696248560))

---

Issue Type: <b>Bug</b>

Please consider the following JavaScript example:
```
const foo = location.href + '#' + 'bar';
```

The editor will raise a suggestion that the concatenation expression should be a template literal. But when you peek the problem in expectation of finding a quick fix for "Convert to template string", none appears.

![image](https://user-images.githubusercontent.com/4434533/93706528-01e8bb00-fadc-11ea-8351-56ed4f4ffa01.png)

However, if the first part of the expression is anything other than an object reference, it works as expected:

![image](https://user-images.githubusercontent.com/4434533/93706550-44aa9300-fadc-11ea-9b40-12ad09012790.png)

Additionally, Quick Fix interactions, depending on how you engage them, have inconsistent behaviors:
```
const url = '//xyzzy.bar';
const foo = url + '#' + 'foo';
```
![image](https://user-images.githubusercontent.com/4434533/93706633-f1851000-fadc-11ea-8e4a-ff1378d9fff6.png)

If you click on the Quick Fix link...

![image](https://user-images.githubusercontent.com/4434533/93706667-4d4f9900-fadd-11ea-8b78-b3aadc8bac92.png)

...this is all you get:

![image](https://user-images.githubusercontent.com/4434533/93706676-5e000f00-fadd-11ea-97af-b5c0834896b2.png)

But if you type Control + . (Period) you get the menu with the "Convert to template" option:

![image](https://user-images.githubusercontent.com/4434533/93706691-7ff99180-fadd-11ea-9ca9-aacf3ad322b5.png)

Similarly, if you click on the lightbulb icon, you also get the option:

![image](https://user-images.githubusercontent.com/4434533/93706710-ae776c80-fadd-11ea-91f8-54f58995eb62.png)

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (24.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-intelephense-client|bme|1.5.4
sqlformatter|bre|0.0.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.6.0
unicode-substitutions|Gle|2.2.8
vscode-phpfmt|kok|1.0.30
vscode-apache|mrm|1.2.0
python|ms-|2020.8.109390
hexeditor|ms-|1.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
php-docblocker|nei|2.1.0
material-icon-theme|PKi|4.3.0
partial-diff|ryu|1.4.1
rewrap|stk|1.13.0
change-case|wma|1.0.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.3.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Self contained example:

```ts
const obj = { prop: '123' };
const z = obj.prop + 'b' + 'c'
```

**Comment by DanielRosenwasser** [comment]
Not that familiar with the code, but sounds like this would be a matter of checking for other node kinds, (e.g. Identifier, PropertyAccess, ElementAccess, ParenthesizedExpressions), skipping those nodes until you reach something else, and checking if that node is a `+` expression

**Comment by morganwdavis** [comment]
Perhaps worth clarifying (as the subject changed and is not 100% accurate from my observations), the refactoring to template literal will work if the first part of the expression is anything other than a dotted object.property reference. In addition to string literals, _simple variables_, and numeric literals all work -- not just bare "strings".

```
const x = 'y';
const w = x + 'A' + 'B';
const z = 5 + 'a' + 'b';
```

It is only obj.prop at the beginning that will cause it to just shrug and make you do it manually.

Thanks @mjbvz for pointing out that it is tslint raising the refactoring suggestion. I understand tslint is being deprecated for eslint, but I've had no luck converting a large project over to eslint depsite following the migration guide.  I'm unable to test if eslint has this same issue. If not, perhaps the fix lies there.

And if tslint v1.2.3 is still being maintained by Microsoft, it would be nice if clicking the `Quick Fix ... (Ctrl+.)` link in the popup dialog worked as advertised -- that is, the behavior you get only if using the keyboard `Ctrl+.` option or the `Show Fixes (Ctrl+.)` menu.

**Comment by dbartholomae** [comment]
Is this a good issue to get into the TypeScript codebase? Unwound line to contribute to TypeScript during Hacktoberfest and if it makes sense would start with this issue :)
