### ISSUE TITLE
Regression in 4.0 with keyof on partial types

### ISSUE THREAD

**Issue by LANGERGabriel** [microsoft/TypeScript#40670]
**TypeScript Version:**  4.0.2, 4.0.3, 4.1.0-dev.20200921

**Search Terms:** partial record keyof

**Code**

type A<T, U> = Partial<Record<keyof T, U>>;
const fn = <T, U1, U2>(a: A<T, U1>, b: A<T, U2>): A<T, U1 & U2> => ({...a, ...b});

**Expected behavior:**

As in 3.9.7, no error

**Actual behavior:**
TS2322: Type 'Partial<Record<keyof T, U1>> & Partial<Record<keyof T, U2>>' is not assignable to type 'Partial<Record<keyof T, U1 & U2>>'.

**Playground Links:** [3.9.7](https://www.typescriptlang.org/play?ts=3.9.7#code/C4TwDgpgBAggPAFQDRQKoD4oF4oAUCGATsAJb4A2cAShAMYD2hAJnANYQj0BmUya66ANwAoBgDsAzsChcx2KIhSoAjEoBM6ABT4AXLEVpl6FACM98Pqg0BKcwZVQAZGg3ZMmgN4A6H-hQ+vEwBfa2EgA), [4.0.2](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAggPAFQDRQKoD4oF4oAUCGATsAJb4A2cAShAMYD2hAJnANYQj0BmUya66ANwAoBgDsAzsChcx2KIhSoAjEoBM6ABT4AXLEVpl6FACM98Pqg0BKcwZVQAZGg3ZMmgN4A6H-hQ+vEwBfa2EgA)

**Related Issues:** None

**Comment by RyanCavanaugh** [comment]
This is a correct error; you can induce an unsoundness through that function signature with that implementation:
```ts
type A1 = { x?: string };
type B1 = { x?: number };

declare const a1: A1, b1: B1;
const q = fn<{ "x": any }, string, number>(a1, b1);
// j: undefined, but could be string or number
const j = q.x;
```
