### ISSUE TITLE
systemjs plugin import, typescript says module not found

### ISSUE THREAD

**Issue by robertbaker** [Microsoft/TypeScript#4069]
typescript doesn't like `import somethingHTML from 'components/something/something.html!text'; `complains it can't find a module.

`import 'components/something/something.html!text';`
would work but not usable since I can't assign it to the template property of a component in angular.

using 
jspm install text=github:systemjs/plugin-text

What's odd is importing css via the systemjs loader works fine...

**Comment by kitsonk** [comment]
I think you will need to declare an ambient module, something like this I think:

```typescript
declare module 'components/something/something.html!text' {
    var text: string;
    export = text;
}
```

**Comment by robertbaker** [comment]
@kitsonk  that works but that means I will need to do that for every template file.

This might be an issue @guybedford can solve in the plugin.

**Comment by mhegazy** [comment]
This is not something that systemJs or an extension can solve for you. There is a suggestion for the issue in #2709.
