### ISSUE TITLE
Create Releasable Package Drop is Failing for release-4.0

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40692]
https://github.com/microsoft/TypeScript/actions?query=workflow%3A%22Create+Releasable+Package+Drop%22

```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "typescript" under a package
npm ERR! also called "typescript". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
```

[First failure starts here, though it's not clear why](https://github.com/microsoft/TypeScript/actions/runs/226162596).

**Comment by amcasey** [comment]
I didn't update all the workflows when I added package-lock.json to old release branches - I just made the minimal change.
