### ISSUE TITLE
Return statement indenting wrong for certain return values

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#4071]
Hi,

**Version**: VS 2015 RTM/TS 1.5

The formatting for the first return statement is correct, but wrong for the second:

```typescript
function foo() {

    return ({
        bar: '1'
    });

    return (
        foo()
        );
}
```
The closing parenthesis should be aligned with the start of the `return` keyword.

**Comment by mhegazy** [comment]
fixed in latest. thanks to @SaschaNaz
