### ISSUE TITLE
Add documents about jsxImportSource And jsx typing

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#40715]
## Search Terms

jsx react

## Suggestion

use this pragma `"jsx": "jsxImportSource"`.

```tsx
/** @jsxImportSource react */
function App() {
  return  <div className="App"> </div> ;
}
```

It works well.

Also, we may define jsx functions use 

```ts
// file: ./utils/my-own-jsx-library/jsx-runtime
function jsxWithValidationDynamic(type, props, key){
}
function jsxWithValidationStatic(type, props, key){
}

export { jsxWithValidationDynamic as jsx, jsxWithValidationStatic as jsxs };
export const Fragment = 0xeacb;
```
```tsx
// file ./app.tsx
/** @jsxImportSource ./utils/my-own-jsx-library */
function App() {
  return  <div className="App"> </div> ;
}
```

What type should I add in `jsxWithValidationDynamic` and `jsxWithValidationStatic`? Should I still use `namespace JSX`?

**Comment by xiaoxiangmoe** [comment]
@weswigham

**Comment by andrewbranch** [comment]
Docs on new compiler options will be added before the stable release (cc @orta).

**Comment by weswigham** [comment]
Everything still uses the `JSX` namespace - the types of the factory function, for better or worse, are still not considered.
