### ISSUE TITLE
"readonly" interface property is not working when modifying instance property using Object.defineProperty

### ISSUE THREAD

**Issue by guybary-wix** [microsoft/TypeScript#40719]
I was playing around with TS interface features, and I saw that setting a custom property configuration (Object.defineProperty) on an object that implements an interface with "readonly" is passing TS checks for the "readonly" interface property.

```ts
  interface SomeInterface {
    readonly x: number;
  }

  let obj: SomeInterface = { x: 10 };

  Object.defineProperty(obj, 'x', { value: 5 });
  //obj.x = 5; //Error: Cannot assign to 'x' because it is a read-only property.ts(2540)
  console.log(obj.x); //will output 5
```

**Expected behavior:**
"Error: Cannot assign to 'x' because it is a read-only property..."
Since readonly property is being modified 

**Actual behavior:**
Readonly property is writable 

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/29634

**Comment by MartinJohns** [comment]
The read-only only applies to access via that interface, but it does not ensure immutability. There's no way to represent immutability in TypeScripts type system.
