### ISSUE TITLE
Cannot find aliased named import type

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#4072]
```typescript
import { Element as _Element } from './element';

let el: _Element; // Cannot find name '_Element'
```

**Comment by RyanCavanaugh** [comment]
This works for me. More details (what's in `./element`? what commandline?) would be useful.
```
C:\Test>type a.ts
import { Element as _Element } from './element';

let el: _Element; // Cannot find name '_Element'

C:\Test>type element.ts
export class Element { }

C:\Test>tsc --module commonjs a.ts
(no errors)
```

**Comment by mhegazy** [comment]
what is "Element"? if it is a variable for instance you would get this message.

**Comment by tinganho** [comment]
It was an empty interface.

hmm I cannot reproduce this either today. Though I worked heavily on my code yesterday so much have changed. I will close this for now and report back if I can reproduce again.
