### ISSUE TITLE
Infer base class' type parameters from super() call

### ISSUE THREAD

**Issue by Raiondesu** [microsoft/TypeScript#40727]
## Search Terms

infer parent generic from super(), infer parent generic, generic from constructor, infer constructor

## Suggestion

Add ability to infer generic parameters from the `super()` call when extending a class, if and only if all said generic parameters appear in the constructor, except ones with default values.

If any of the generic parameters are absent from the constructor parameters' types of a base class, except ones with default values, this inference should take no effect on the child class definition, and the code should behave exactly as it does now.

If all generic parameters of the base class have default values, this inference should take no effect on the child class definition, and the code should behave exactly as it does now.

If a child class definition defines any generic parameter of the base class, this inference should take no effect on the child class definition, and the code should behave exactly as it does now.

## Use Cases

This is useful in cases where a child class extends a generic base class, but needs to provide a complex value for its generic constructor, which currently requires creating separate types and interfaces even if they're never used anywhere again and just duplicate the code that goes to the `super()` function in constructor.

The use-case is fairly common among libraries that manage data in various ways - event managers, data storages, object-oriented model converters, http clients, etc. - where a library exports a class that the user is supposed to extend, while providing a type for the generic type parameter of said class.

## Examples

Currently we have this:
```ts
class EventManager<EventMap extends Record<string, any>> {
  constructor(protected map: EventMap) {}
}

interface MyEventMap {
  event1(param1: any, param2: any): boolean;
}

// Will error, if I don't provide a generic parameter to `EventManager`
class MyEvents extends EventManager<MyEventMap> {
  constructor() {
    super({
      event1(param1: any, param2: any) {
        return param1 !== param2;
      }
    })
  }
}
```

While this issue proposes to allow this:
```ts
class EventManager<EventMap extends Record<string, any>> {
  constructor(protected map: EventMap) {}
}

class MyEvents extends EventManager {
  constructor() {
    super({
      event1(param1: any, param2: any) {
        return param1 !== param2;
      }
    })
  }
}

/*

MyEvents is automatically inferred to be

class MyEvents extends EventManager<{
  event1(param1: any, param2: any): boolean;
}>

*/
```

> If any of the generic parameters are absent from the constructor parameters' types of a base class, except ones with default values, this inference should take no effect on the child class definition, and the code should behave exactly as it does now.

```ts
class EventManager<EventMap extends Record<string, any>, T> {
  someOtherValue!: T;

  constructor(protected map: EventMap) {}
}

// Should error
class MyEvents extends EventManager {
  constructor() {
    super({
      event1(param1: any, param2: any) {
        return param1 !== param2;
      }
    })
  }
}
```

However,
```ts
class EventManager<EventMap extends Record<string, any>, T = number> {
  someOtherValue!: T;

  constructor(protected map: EventMap) {}
}

// Shouldn't error!
class MyEvents extends EventManager {
  constructor() {
    super({
      event1(param1: any, param2: any) {
        return param1 !== param2;
      }
    })
  }
}
```

> If all generic parameters of the base class have default values, this inference should take no effect on the child class definition, and the code should behave exactly as it does now.

```ts
class EventManager<EventMap extends Record<string, any> = Record<string, any>, T = number> {
  someOtherValue!: T;

  constructor(protected map: EventMap) {}
}

// Should error
class MyEvents extends EventManager {
  constructor() {
    super({
      event1(param1: any, param2: any) {
        return param1 !== param2;
      }
    })
  }
}
```

> If a child class definition defines any generic parameter of the base class, this inference should take no effect on the child class definition, and the code should behave exactly as it does now.

```ts
class EventManager<T, EventMap extends Record<string, any>> {
  someOtherValue!: T;

  constructor(protected map: EventMap) {}
}

// Should error that EventMap isn't provided
class MyEvents extends EventManager<T> {
  constructor() {
    super({
      event1(param1: any, param2: any) {
        return param1 !== param2;
      }
    })
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code,
      because currently such syntax is completely prohibited by TypeScript.
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment]
Duplicate of #36456

**Comment by Raiondesu** [comment]
Ok, makes sense. I didn't think of the word `superclass` for some reason.

**Comment by AlCalzone** [comment]
I've added your search terms to my issue
