### ISSUE TITLE
Incorrect code generated when targeting ES5 and using for..of and ?.

### ISSUE THREAD

**Issue by dezsiszabi** [microsoft/TypeScript#40726]
**TypeScript Version:**  next

**Search Terms:**

for..of
elvis operator
ES5

**Code**

```ts
for (const item of ['item']) {
  for (const _ of ['item']) {
    () => item; // Dummy declaration which references outer loop variable. Seems to trigger the issue...

    console.log(([] as any[])[0]?.prop);
  }
}
```

Note: you have to target ES5 for the bug.

**Expected behavior:**
Logs `undefined` without any error.

**Actual behavior:**
Logs `undefined` and throws an error:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at _loop_1 (index.js:3)
    at index.js:11
```

**Playground Link:**
https://www.typescriptlang.org/play?target=1&ts=4.1.0-dev.20200921#code/GYewTgBAFAxiB2BnALhAlsgpgWwiYEA2gOQY7EC6AlBAN4CwAUBBKJLAihAPp4EllslGg2YtoNALwA+dFmwBuCAHplEACIBXbNgCeEACaYYAGwCGYM8jQIIAdwAWaGA4hhMwTO-gxMiPJpYkCYgIAAOEABuFmhmAEYmmAB0EADKmDj+yCAQyGBoAOYFXrkOmOiIiJrJSUlMTOIQcEggiUkhBVBQhBQQZv5m8Lo9VIQADBQA-ElhYOFUCg0QAL5My0A

**Comment by andrewbranch** [comment]
Seems to be a problem all the way back to when optional chaining was introduced. (It looks like the issue is that the for/of and optional chaining downleveling each declare a `_a` temporary variable without realizing that the former’s declaration shadows the latter’s.)

**Comment by dezsiszabi** [comment]
This is possibly the same issue: https://github.com/microsoft/TypeScript/issues/40643

**Comment by andrewbranch** [comment]
You’re right; this is a duplicate, thanks 👍
