### ISSUE TITLE
No intuitive/easy way of finding out what version of TS is in use by Visual Studio

### ISSUE THREAD

**Issue by Bartolomeus-649** [Microsoft/TypeScript#4073]
In Microsoft Visual Studio Professional 2013 Version 12.0.31101.00 Update 4 there is no way to tell what version of TypeScript that is in use.

* Type script is not listed as an installed product in VS About Dialog (Menu: Help -> About)
* Type script is not listed as an installed Extension (Menu: Tools => Updates and Extensions. Navigation: Installed => All)

**Visual Studio Version and "installed products" copied from the Help-About Dialog**
Microsoft Visual Studio Professional 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

Installed Version: Professional

LightSwitch for Visual Studio 2013   06177-004-0444002-02343
Microsoft LightSwitch for Visual Studio 2013

Team Explorer for Visual Studio 2013   06177-004-0444002-02343
Microsoft Team Explorer for Visual Studio 2013

Windows Phone SDK 8.0 - ENU   06177-004-0444002-02343
Windows Phone SDK 8.0 - ENU

Visual Basic 2013   06177-004-0444002-02343
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0444002-02343
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0444002-02343
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0444002-02343
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0444002-02343
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   12.4.51016.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Websites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.3
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debugging Tools for Windows   6.3.9600.17029
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

Microsoft Azure HDInsight HQL Service   2.0.0.0000
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.0.0000
An integrated development environment for HDInsight application development.

Microsoft Azure Management Libraries Demo Project   1.0
Provides a step-by-step walk-through of the Microsoft Azure Management Libraries. Provides a project template, item templates, and snippets that walk you through a 5-step process to creating an application that creates Virtual Machines in Microsoft Azure.

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.5
Microsoft Azure Tools for Microsoft Visual Studio 2013 - v2.5.21104.1601

Microsoft Team Foundation Server 2013 Power Tools   12.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

NuGet Package Manager   2.8.60318.734
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2013 ENU   12.0.31105
Microsoft Office Developer Tools for Visual Studio 2013 ENU

PowerShell Tools   1.3
Provides file classification services using PowerShell

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.41025.0
Microsoft SQL Server Data Tools

Web Essentials 2013   2.5.3
Adds many useful features to Visual Studio for web developers.

Windows Driver Kit   6.3.9600.17246
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by danquirk** [comment]
TypeScript does have a separate entry in Add/Remove Programs, ex:
![image](https://cloud.githubusercontent.com/assets/7121557/8967349/18613576-35eb-11e5-8814-59727a59ca2a.png)
But it is a little awkward that it's in none of the VS related places. We used to ship a .VSIX and show up in the VS Extension Manager but that is no longer the case (there are technical limitations with VSIX that made shipping as a VS Extension not workable). We're now installed as part of the Web Developer Tools which are listed there as you note but its description doesn't mention TypeScript at all, let alone a specific version. Perhaps the simplest thing is to get ourselves mentioned in that blurb. @JsonFreeman @yuit thoughts on something cheap we can do to make this better?

**Comment by JsonFreeman** [comment]
@danquirk Mentioning TypeScript in the installer UI won't actually make it easier to identify which version will be installed, nor will it help you once VS is already installed. You're right that the VSIX was the best option we've ever had for version visibility. I'd say the Add/Remove Programs dialog is the best thing we have today.

I think it is reasonable to try to get TypeScript added to the Installed Products list that @649 mentioned.

**Comment by mhegazy** [comment]
we are working with the VS setup team to get TypeScript listed in the help page as an extension.

**Comment by basarat** [comment]
> we are working with the VS setup team to get TypeScript listed in the help page as an extension.

:+1:

**Comment by yahiko00** [comment]
+1

**Comment by mhegazy** [comment]
`Help` -> `About` should have this already:

![image](https://cloud.githubusercontent.com/assets/8000722/18692207/847fd71a-7f4d-11e6-998b-6bc8dc089150.png)
