### ISSUE TITLE
Compilation error occurs when using one way of equivalent typing syntax for a function

### ISSUE THREAD

**Issue by agubler** [microsoft/TypeScript#40741]
**TypeScript Version:** 4.0.2

**Search Terms:** generic, function typings

**Code**

```ts
// this doesn't work
interface Properties<T extends EventTarget = EventTarget> {
    test: (target: T) => void;
    attr: T;
}

// However this works when typing the function as a function
// interface Properties<T extends EventTarget = EventTarget> {
//     attr: T;
//     test(target: T): void;
// }

interface DivProperties extends Properties<HTMLDivElement> {}

export interface Foo {
    div: DivProperties;
    [index: string]: Properties;
}
```

**Expected behavior:**

No compilation error

**Actual behavior:**

Property 'div' of type 'DivProperties' is not assignable to string index type 'Properties<EventTarget>'.

**Playground Link:** 

https://www.typescriptlang.org/play?#code/PTAEBcAsEsGdQCYHsCmsB2BycoDuSAnAawFgAoc6dcFAgMwEMBjFUABQKQAdbxo0APABVQKAB410CeAFEAbimpCGBAOYocAXlDzF4ZWo0A+UAG9yoSxDTgAXKAAU4FerughASlCaTcpNAQAbgsrBnBwAnshYLIAX3JyEAgYeHxiWASyKhp6ZlYObl5+WGFRCUVpHQUlFw1vKr0DVxNzMitQMIiomPakmlhwJ1q3T3s-AJj4iizqWkYWUAARaDkCngI+NDLJSrWiwQAJIQBZABlluRkAGxQAWz0WqfJxLkIcbLm80AAxJCQzEKWBArewXPYbYo9KwAbSoCHE9gGBCoqgAuvZwZtYJMgA

**Related Issues:**

**Comment by MartinJohns** [comment]
The indexer must return a union of all types present in the "known properties". The documentation used to mention this, but doesn't anymore. So you must write: `[index: string]: DivProperties | Properties;`

**Comment by agubler** [comment]
Thanks @MartinJohns, still not sure why one way it works and one way it doesn't though :) But this does help me a lot, so thank you!

I'm going to close this, please feel free to re-open if there is any other actions that need to be done for this.
