### ISSUE TITLE
onfocusout missing on div element

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#40744]
seems that it is not defined in lib.d.ts

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). :-) That'll make it much easier for the TypeScript team.

**Comment by andrewbranch** [comment]
See https://github.com/microsoft/TSJS-lib-generator/pull/696#issuecomment-484725677 / https://github.com/microsoft/TypeScript/issues/30716#issuecomment-498875162.
