### ISSUE TITLE
Destructuring with strictNullChecks enabled, wrong types inferred

### ISSUE THREAD

**Issue by Ebooth** [microsoft/TypeScript#40749]
**TypeScript Version:**  4.0.2

**Search Terms:**
Destructuring

**Code**

```ts
const emptyString = ""
const [firstLetter] = emptyString.split("")
console.log(firstLetter) // undefined
```

**Expected behavior:**
firstLetter to be of type string | undefined with strictNullChecks = true

**Actual behavior:**
 firstLetter is of type string

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgWwA5QJ4GUoCcCWYDmMAvDAESkBQoksA2gGY5bQAycUUcWAusfMmky4CAOghIANjigAKcgEoq4CCAlwREkPhmNmUNhy6KA9MZgBBYFACuAQwkAuGLtbtOWGDggwQ9GGiQ4GGhhfApTGABRAA9AqzgAEycXfTcufxAYACMg339UQODsPHwAAoAfGGswBLhGMESYAHdpAAsi3CsAOWsJCQBhVrhgAGtvEmxrOAoKIA)

**Related Issues:**

**Comment by MartinJohns** [comment]
Duplicate of #38287.
