### ISSUE TITLE
Visual Studio 2015 not using output folder

### ISSUE THREAD

**Issue by kevinpas** [Microsoft/TypeScript#4075]
When I create a blank node.js console app then in the project properties select "redirect to output folder"  the output continues going to the default location.

You can see this in the small project at: https://github.com/kevinpas/Klib6 
(look at branch AddVS15)

**Comment by kevinpas** [comment]
I the branch AddVS15 of https://github.com/kevinpas/Klib6 

there is a Tools folder.  In that folder there is a vs 15 project that should be used.  But this is easily duplicated by creating a new project in vs 15 and trying to use the "redirect to output folder" option.

**Comment by danquirk** [comment]
this is with the Node Tools for Visual Studio then? Might be an issue on that side. 

@paulvanbrenk us or NTVS?

**Comment by kevinpas** [comment]
I think you're right this should be in Node Tools...

I had it over there but closed it to keep this one and typescript issue #4076 together.

Anyway when I run:  tsc -module commonjs -t ES5 -outDir ../../Output NameValue.ts

the output shows up where I expect.
