### ISSUE TITLE
Refactoring to add inferred return type annotation to a function

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#40750]
## Search Terms
- Refactoring, refactor
- type annotation
- quick fix, code action
- function, method
- return

## Suggestion
Add a refactoring that takes a function with no annotated return type, and inserts the inferred return type.

For example, starting with the code:

```ts
function foo() {
  return { a: 1, b: 2 };
}
```

If you trigger the refactoring on `foo`, it would become:

```ts
function foo(): { a: number; b: number; } {
  return { a: 1, b: 2 };
}
```

## Use Cases
A few example use cases:

- Give your public interfaces explicit typings.

- Updating a function from `() => T` to `() => T | undefined`. Today, you have to explicitly type out the return type and then add `| undefined`

- Extracting the return type to a new interface. Right now, this is a manual process. With this refactoring, this becomes a two step process: generate inferred return type and then extract to interface

- When migrating from JS to TS, many JS functions may not have explicit return types. Often you want to make the code stricter by having these return types

**Comment by jsamr** [comment]
Isn't it similar to #35467?

**Comment by mjbvz** [comment]
Yes but this one is more generic. You can can think of #35467 as a one step version of one refactoring this request would enable as two steps: add types, then extract type.
