### ISSUE TITLE
Missing error when referenced project does not have required `composite` flag

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#40766]
**TypeScript Version:**  4.0.2

**Search Terms:** project references composite missing referenced

**Code**

`shared/index.ts`:
```ts
export const a = 1;
```

`shared/tsconfig.json`:
```jsonc
{
  "compilerOptions": {
    // "composite": true,
    "outDir": "../target-tsc-build/",
    "rootDir": ".."
  },
  "files": ["./index.ts"]
}
```

`tsconfig.json`:

```json
{
  "references": [
    {
      "path": "./shared/tsconfig.json"
    }
  ],
  "files": []
}
```

**Expected behavior:**

When I run `tsc --build tsconfig.json --force --verbose`, it should error because the referenced project is missing the required `composite` flag, as per the docs:

> Referenced projects must have the new composite setting enabled. This setting is needed to ensure TypeScript can quickly determine where to find the outputs of the referenced project.

https://www.typescriptlang.org/docs/handbook/project-references.html#composite:~:text=Referenced%20projects%20must%20have%20the%20new,composite%20flag%20changes%20a%20few%20things%3A

**Actual behavior:**

No error

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
This is by design as the tsconfig is just a solution and hence doesnt need to have composite flag on referenced projects

**Comment by OliverJAsh** [comment]
Ah thanks @sheetalkamat! Out of interest, what is it about solutions that means referenced projects don't need composite? What makes them special? I'm just trying to build an intuition for what the composite flag does.

**Comment by sheetalkamat** [comment]
Solution is the project that has no own files so it doesnt need to be built. So it doesnt care if referenced project is composite or not.  Non solution projects will use .d.ts output from the referenced project and knowing all input output files is also key to check upto dateness of your own project. hence composite requirement for those referenced projects

**Comment by OliverJAsh** [comment]
Thanks, that helps a lot!
