### ISSUE TITLE
Bad error message when forgetting a comma in an array of template strings

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#40763]
**TypeScript Version:**  4.1.0-beta

**Search Terms:** string call signatures

**Code**

```ts
const foo = [
  `template string 1`
  `template string 2`
];
```

**Expected behavior:**
Error: "missing comma" after `template string 1`

**Actual behavior:**
`template string 1` underlined with this error:
```
This expression is not callable.
  Type 'String' has no call signatures.(2349)
```

**Playground Link:** https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MDaAoGMAGUCmAtgA4A2AhgTNAE4CWYA5jAIw5a4EkVW0PMAmdgF0A3EA

**Related Issues:** none found

**Comment by SharadaSowmya14** [comment]
[Playground Link of fix](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MDaAoGMAGUCmAtgA4A2AhgTNAE4CWYA5jAIw4A0WuBJFVtDZgCYcGALoBuIA)

**Comment by saigeethakandepallicherukuru** [comment]
Hello, This my first time attending vGHC and I am looking for my first open source contribution. Can anyone let me know if I can work on this issue? Thanks!

**Comment by romilsiddhapura** [comment]
Hi, I have already started working on this issue.

**Comment by DanielRosenwasser** [comment]
I guess I would suggest a separate error message for tagged templates where the parent expression is an array literal.

````
It is likely that you are missing a comma to separate these two template expressions. They form form a tagged template expression which is invalid.
```

**Comment by DanielRosenwasser** [comment]
Thanks @richa008!
