### ISSUE TITLE
Easy types publication for scoped packages

### ISSUE THREAD

**Issue by sosoba** [microsoft/TypeScript#40760]
## Search Terms

`scoped`

## Suggestion

There is a god practice to write library source code in `ts` and publish output as two separated `npm` packages:
- runtime code (`js`)
- declarations (`d.ts`)

Currently this way demand colaboration with `DefinitelyTyped` big `npm` project. 

Now types for a scoped package `@scope/library` should go in `types/scope__library`.

I suggest to allow to kept it **alternatively** in `@scope/types__library` which may be maintined by scope owner.

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
The good practice is to publish the declarations together with your code. The `@types/..` packages are just a workaround for when the library author does not provide any type declarations.

**Comment by sosoba** [comment]
I beg to differ. Les't consider that your web page add large library from CDN by `<script>` tag. You don't need `js` code inside your `node_modules` but only `@types` and additionaly as `devDependency` only.
Separating body and headers file is a necessity when you linking libraries dynamically.
Please note that Node has a many ways to find package at runtime:
- in local `node_modulese`
- in parent folders `node_modules`
- by `NODE_PATH` 
- by custom `--loader`
but `tsc` compiler seeking (correctly) only first of them.
Now when you manage library outside of project folder, you again need a separated `@types` dev-only package.

**Comment by andrewbranch** [comment]
We have, in the past, briefly and informally discussed the possibility of periodically scraping and republishing the types from popular npm libraries that bundle their types, for the purpose of minimizing the amount we’d need to download in automatic type acquisition for editor support in JS projects. But I don’t think we’re interested in reversing our guidance on where to publish type declaration files or encouraging people not to use DefinitelyTyped. We quite like DefinitelyTyped, and our users quite like knowing that they can find typings on npm under `@types`. If you want to discuss having a mirror of just types from npm libraries that bundle their types with JS, I would suggest starting a conversation on DefinitelyTyped’s issue tracker.
