### ISSUE TITLE
Complex shapes add optional keys for objects

### ISSUE THREAD

**Issue by trivikr** [microsoft/TypeScript#40770]
**TypeScript Version:**  4.1.0-dev.20200925

**Search Terms:**
* complex types https://github.com/microsoft/TypeScript/search?q=complex+types&type=Issues
* complex types destructuring https://github.com/microsoft/TypeScript/search?q=complex+types+destructuring&type=Issues

**Code**

```ts
type ComplexValue = string | number | ComplexValue[] | {[key:string]: ComplexValue};

const func = (value: ComplexValue) => value;

[
  {
    input: [
      { stringKey: "one" },
      { numberKey: 1 }
    ]
  }
].map(({input}) => func(input));
```

**Expected behavior:**
No error

**Actual behavior:**
```console
Argument of type '({ stringKey: string; numberKey?: undefined; } | { numberKey: number; stringKey?: undefined; })[]' is not assignable to parameter of type 'ComplexValue'.
```

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200925#code/C4TwDgpgBAwg9gWzAGwgDwGoENkFdoC8UAzsAE4CWAdgOZQA+UVuCARhGQ7IiutnhADaAXS4BvQQGsIIAFylKtYbO5JUmHPgC+AbgBQegMZwqpKADNcVQ1CIAKAG6aIK+Gr7OAlLYB8UJwL6eoJ6UFBioWFQ1GC4wCohUVFiJOTUNADSMioARCYQOVBaADSRSSnMbBxZclAAjEVlUMKRWnrCAHQIWGB2dmIxcVreBH6W1naDwJ6eOkA

**Related Issues:** No

**[EDIT]:** Updated Playground link to Code shared in description.

**Comment by trivikr** [comment]
On detailed debugging, the types change while destructuring:

<details>
<summary>types inside object</summary>

![input](https://user-images.githubusercontent.com/16024985/94286799-58a22a80-ff0a-11ea-8caf-d672ad67f07d.png)


</details>

<details>
<summary>types when destructuring</summary>

![key](https://user-images.githubusercontent.com/16024985/94286772-4c1dd200-ff0a-11ea-91d3-9c7df83acdb8.png)


</details>

<details>
<summary>types when passed to function</summary>

![func](https://user-images.githubusercontent.com/16024985/94286674-2d1f4000-ff0a-11ea-849f-8da251a6834a.png)

</details>

**Comment by trivikr** [comment]
The issue appears to be with array operations when hovered over method types
```ts
Array<{ input: ({ stringKey: string; numberKey?: undefined; } | { numberKey: number; stringKey?: undefined; })[]; }>
```

It should be:
```ts
Array<{ input: ({ stringKey: string; } | { numberKey: number; })[]; }>
```

<details>
<summary>Screenshot</summary>

![Screen Shot 2020-09-25 at 8 40 27 AM](https://user-images.githubusercontent.com/16024985/94287160-cfd7be80-ff0a-11ea-9a4b-3768ae6a2ee9.png)


</details>

**Comment by trivikr** [comment]
It appears that `?: undefined` is added when TypeScript tries to create type for the array.

<details>
<summary>Code</summary>

```ts
const arr = [
  {
    input: [
      { stringKey: "one" },
      { numberKey: 1 }
    ]
  }
];
```

</details>

<details>
<summary>Screenshot</summary>

![Screen Shot 2020-09-25 at 8 46 07 AM](https://user-images.githubusercontent.com/16024985/94287942-bd11b980-ff0b-11ea-8b1c-8c5fc29a1826.png)

</details>

**Comment by trivikr** [comment]
The issue disappears if I explicitly define type for the array as follows:

<details>
<summary>Code</summary>

```ts
type ComplexValue = string | number | ComplexValue[] | {[key:string]: ComplexValue};

const func = (value: ComplexValue) => value;

const arr: {
  input: ({
    stringKey: string;
  } | {
    numberKey: number;
  })[];
}[] = [
  {
    input: [
      { stringKey: "one" },
      { numberKey: 1 }
    ]
  }
]

arr.map(({input}) => func(input));
```

</details>

Question: Can TypeScript smartly calculate this complex type for me, instead of requiring explicit definition?

**Comment by andrewbranch** [comment]
The problem is that there’s no contextual type for that array, so the type system has to make a guess about what would be reasonable. Only later do you try to assign that type to something else, and at that point, it’s too late. Here’s an option that I think looks pretty good: https://www.typescriptlang.org/play?ts=4.1.0-dev.20200925#code/C4TwDgpgBAwg9gWzAGwgDwGoENkFdoC8UAzsAE4CWAdgOZQA+UVuCARhGQ1GRFgCZwqyELEQp02PBADaAXS4BvaQGsIIAFylKtWetFJUmHPgC+AbgBQFgMaDSUAGa4q1qEQAUAN2MQ98AxI+AJRuAHxQ3lKWFtIWUFAKcfFQ1GC4wHqxyckKJOTUNADSanoARIIQpVAmADRJ2bnMbBzFGlAAjNX1UPJYxFC2VKRJJhayAHQIWGDu7gqp6SYhBOFOLu4LwEFBlkA

**Comment by trivikr** [comment]
Thanks! The option which Andrew shared in playground is using const assertion.

<details>
<summary>Code</summary>

```ts
type ComplexValue = string | number | readonly ComplexValue[] | {[key:string]: ComplexValue};

const func = (value: ComplexValue) => value;

[
  {
    input: [
      { stringKey: "one" },
      { numberKey: 1 }
    ] as const
  }
].map(({input}) => func(input));
```

</details>

Doc: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions

Question: should type system use const assertions by default for complex types, as given in the example.?

**Comment by andrewbranch** [comment]
No: https://www.typescriptlang.org/play?#code/DYUwLgBAdgrgtgIxAJwILOQQwJ4QLwQDaADADQQCM5ATOQMwC6EA9AFSYDOEAxgPZQcwrZgG4WzCAB4AtNIgwofOHBBRIYXhADumMNwAWETMGAQw+kBxARkITv0wJQZ-QEsoAcy4AzTK+AAsABQsIgo6Fi4BIQALOQArOQAbOQA7AwiwaFIaBg4AHQADjAc+gAUABwAlJkh8DkROCRMBHS1wXwCkFAgWgAyvNy6rvz4EADewRDTEPlzACaD8Kpg+cCDw-ykUzP6nPoAXBAA5ADEHLwq0q7zx8EAvizsXJ2CwmLMEjJyCkoqasEsr0BkMwCMoPk9qUxmcLldeOYUNdbrUgA

**Comment by trivikr** [comment]
Both the original question and follow-up question is answered.
This issue can be closed.
