### ISSUE TITLE
VS2015 typescript settings are not honored because they are set to apply to an incorrect platform within the csproj file

### ISSUE THREAD

**Issue by richardspence** [Microsoft/TypeScript#4077]
I created a new web application in vs 2015, and tweaked the default typescript settings.  Within the csprj file they are only applied to 'Debug Any CPU' (note the space)  When they should be Applied to Debug AnyCPU.  This causes the settings to not be picked up at compiled time

**Comment by paulvanbrenk** [comment]
Is this an Asp.net 4 or asp.net 5 project? And is this VS 2015 RTM?

**Comment by richardspence** [comment]
I believe it's VS 2015 RTM, about reads: v 14.0.23107.0 D14REL

I used the classic Asp.net 4.5 web application template

**Comment by nukefusion** [comment]
+1. I can confirm this after struggling for a while to understand why the trusty old "Cannot compile external modules unless the --module flag is provided" message just wouldn't go away.

**Comment by danquirk** [comment]
Manually editing the project file to your desired setting is at least unblocking you while we fix this right?

**Comment by richardspence** [comment]
Yeah, that's exactly what I've done to unblock.

**Comment by paulvanbrenk** [comment]
Checked in a fix, this is in the next release for VS.
