### ISSUE TITLE
Characters count as both prefix and suffix of pattern literal

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#40772]
**TypeScript Version:**  v4.1.0-dev20200925

**Search Terms:** pattern literal prefix suffix

**Code**

```ts
const s: `:${string}:` = ":";
```

**Expected behavior:**
Assignability error because the pattern `` `:${string}:` `` has two literal `:` characters, while `":"` has only one.

**Actual behavior:**
No error

[**Playground Link**](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200925#code/MYewdgzgLgBBBcMAG8AkBvaAnAlmA5gL7xIwC8MARPJQNxA)

**Related Issues:** #40598

**Comment by jamesmfriedman** [comment]
Related to this issue,
- It's great that in dev you can use `string` as a value placeholder! This is a marked improvement from beta.
- The ability to define a prefix or suffix for a key is very valuable, but currently neither of these usecases work:

```
type CustomProps = Record<`x${string}`, any>;
const a: CustomProps = {};
a.x11 = ''; // ERRORS OUT

type CustomProps ={[key: `x${string}`]:  any}; // ERRORS, key must be string or number
const a: CustomProps = {};
```

Would be amazing if this could work!
