### ISSUE TITLE
Anonymous classes do not have distinct private members

### ISSUE THREAD

**Issue by lazytype** [microsoft/TypeScript#40781]
**TypeScript Version:**  4.0.2

**Search Terms:** dynamic anonymous class private protected nominal

According to the FAQ: https://github.com/Microsoft/TypeScript/wiki/FAQ#when-and-why-are-classes-nominal (emphasis added)
> In TypeScript, classes are compared structurally. **The one exception to this is private and protected members**. When a member is private or protected, it must originate in the same declaration to be considered the same as another private or protected member.

**Code**
Ensure `--declaration` is `false`
```ts
function createClass() {
    return class {
        private field?: never;
    };
}

let anonymousClass = createClass()
let otherClass = createClass();

// @ts-expect-error
anonymousClass = otherClass;

// @ts-expect-error
otherClass = anonymousClass;
```

**Expected behavior:**

Lines preceded by `// @ts-expect-error` have a type error

**Actual behavior:**

Lines with `// @ts-expect-error` are labelled as errors because the following line does not have an error.

It's worth noting that when the anonymous classes come from different function definitions, the expected type errors do occur.
```ts
function createClass() {
    return class {
        private field?: never;
    };
}

function createClass2() {
    return class {
        private field?: never;
    };
}

let anonymousClass = createClass()
let otherClass = createClass2();

// @ts-expect-error
anonymousClass = otherClass;

// @ts-expect-error
otherClass = anonymousClass;
```

### Alternate resolution:
Update documentation to clarify that by
>must originate in the same declaration 

a "declaration" is meant as the source code declaration, not the creation of the class at runtime

**Playground Link:** https://tsplay.dev/oN9nqm

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
I'm not sure how to make this more clear. There's only one declaration; if there's only one thing, that thing is the same thing as itself. Open to a docs PR that makes this *clearly* more clear, but this is the first confusion we've seen on this, so it'd have to be very obviously better.

**Comment by lazytype** [comment]
I agree the text is clear when read literally, but I think it's easy to misinterpret since it goes against expectations. 

how it works:
>When a member is private or protected, it must originate in the same declaration to be considered the same as another private or protected member.

how I'd expect it to work:
>When a member is private, it must originate in the same **class** to be considered the same as another private member and when a member is protected, it must originate in the same **class hierarchy** to be considered the same as another protected member.

I think what would make it more clear is a brief explanation as to why it doesn't work as I'd expect, e.g. technical limitation.

>this is the first confusion we've seen on this

The confusion could only arise when applying the rule to dynamically created classes which I doubt many other people have tried to (ab)use 🙂. For some context, I was trying to hack at creating something like a `nominalTypeFactory<T>(type: T)`. AFAIK the only function that create different types on different invocations is `Symbol()` when assigned to a `unique symbol` variable.
