### ISSUE TITLE
re-exporting delcaration file should not generate export javascript code

### ISSUE THREAD

**Issue by pathurs** [microsoft/TypeScript#40789]
When TypeScript generates an export from a `.d.ts` file, the generated `.js` file will be invalid and throw errors about the file not existing.

**TypeScript Version:**  4.0.3

**Search Terms:**
re-export all from declaration file
export type *
export *

**Code**

tsconfig.json
```json
{
    "compilerOptions": {
        "alwaysStrict": true,
        "baseUrl": ".",
        "declaration": true,
        "esModuleInterop": true,
        "importHelpers": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es6"
    }
}
```

foo.d.ts
```ts
export interface Foo { }
```

bar.ts
```ts
export * from './foo'
```

**Expected behavior:**

bar.js
```js
"use strict";
```

bar.d.ts
```js
export * from './foo';
```

foo.d.ts
```js
export interface Foo { }
```

**Actual behavior:**

bar.js
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./foo"), exports);
```

bar.d.ts
```js
export * from './foo';
```

Note:

On a separate issue, I can not figure out a way to export tell TypeScript to copy the `foo.d.ts` file to the `outDir` when compiling.

**Comment by RyanCavanaugh** [comment]
A module declaration file is a file that represents a module that actually exists. Writing `foo.d.ts` when no `foo.js` module exists is telling the compiler a lie and it will believe you. It sounds like you just want to write a `foo.ts` file instead, and possibly not make it a module either (hard to say based on what's in here).

**Comment by pathurs** [comment]
@RyanCavanaugh Is there no way to write helper types in a separate file without that file being compiled, but still providing it in an NPM package? For example, if I were to create a very complex type, I'd rather move it to a different file, but I also don't want that file to have an associated `.js` file.

I thought this was a feature of typescript, especially with the new `import type {} from '';` syntax.
