### ISSUE TITLE
VS project properties bad spacing

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#4078]
![image](https://cloud.githubusercontent.com/assets/7121557/8970503/df6ac084-35fe-11e5-9188-fcd63d7d3987.png)

:disappointed:

**Comment by DanielRosenwasser** [comment]
I had a fix for this. Then my TFS branch got deleted because reasons. I can take it on again.

**Comment by RyanCavanaugh** [comment]
I think I already fixed this when I did the TSX work

**Comment by DanielRosenwasser** [comment]
Do all menus have consistent spacing now then?

**Comment by RyanCavanaugh** [comment]
I'll post some screenshots

**Comment by RyanCavanaugh** [comment]
![image](https://cloud.githubusercontent.com/assets/6685088/8970800/8969b742-3600-11e5-8700-987df17686a2.png)

![image](https://cloud.githubusercontent.com/assets/6685088/8970808/96b7b502-3600-11e5-9032-205b66105ef1.png)

**Comment by danquirk** [comment]
Yay. I think the Output options are still slightly misaligned (the space between the last 2 is smaller than the spaec between the others) and the Debugging ones are as well due to the oversized Browse box (which is longer than the textbox it's associated with).

**Comment by mhegazy** [comment]
Assigning to @RyanCavanaugh since he has an intial fix,

**Comment by DanielRosenwasser** [comment]
Also at the top of "General", those drop-down boxes and their labels are a little too close.

**Comment by danquirk** [comment]
Yeah, the first option in every section is too close to its header text

**Comment by mhegazy** [comment]
Feel free to send a PR if you have a fix, but otherwise do not think any one will get to it.

**Comment by RyanCavanaugh** [comment]
The VS side isn't open source, so no PRs :frown:

**Comment by mhegazy** [comment]
@RyanCavanaugh, I meant you :D as you mentioned you had a fix to it as part of the tsx work.
