### ISSUE TITLE
Add compiler support to disable function hoisting

### ISSUE THREAD

**Issue by pranaydutta89** [microsoft/TypeScript#40797]
## Search Terms

Espruino Typescript, disable function hoisting in typescript

## Suggestion

Add compiler support for disabling function hoisting currently transpiled code use a lot of function hoisting features , i know its normal javascript implementation but i have been trying to use typescript in my IOT projects using Espruino , and esprunio interpretter doesn't support function hoisting, so i have to manually change my transpiled code , like __extends , __generator etc 

## Use Cases

We would be able to use Typescript in Espruino projects

## Example

By adding another compileroption flag in tsconfig.json

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Supporting runtimes that aren't JavaScript is outside the scope of our project. It seems like something like this could be detected with a lint rule
