### ISSUE TITLE
Import suggestions for referenced project include files in `outDir`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#40791]
**TypeScript Version:**  4.0.3

**Search Terms:** auto imports

**Code**

Reduced test case: https://github.com/OliverJAsh/ts-project-references-playground/tree/imports-bug. Below I have inlined the code from this repository.

`shared/tsconfig.json`:
```json
{
  "compilerOptions": {
    "composite": true,
    "outDir": "../target-tsc-build/",
    "rootDir": ".."
  },
  "files": ["./main.ts"]
}
```

`shared/main.ts`:
```ts
export const shared = 1;
```

`webpack/tsconfig.json`:
```json
{
  "compilerOptions": {
    "outDir": "../target-tsc-build/",
    "rootDir": "..",
    "baseUrl": "./",
    "paths": {
      "shared/*": ["../shared/*"]
    }
  },
  "files": ["a.ts", "b.ts"],
  "references": [
    {
      "path": "../shared/tsconfig.json"
    }
  ]
}
```

`webpack/a.ts`:
```ts
import { shared } from "shared/main";

console.log(shared);
```

`webpack/b.ts`:
```ts
console.log(shared);
```

**Expected behavior:**

When I open `webpack/b.ts`

- TypeScript should suggest importing symbol `shared` from `shared/main`. There should be no other suggestions.
- Activating auto import should result in:
   ```ts
   import { shared } from "shared/index";
   
   console.log(shared);
   ```

**Actual behavior:**

- TypeScript suggests importing symbol `shared` from `../target-tsc-build/shared/main` (the file in `outDir`) and _then_ `shared/main`.
   ![image](https://user-images.githubusercontent.com/921609/94349643-5b9e3780-003e-11eb-8650-662d5901b696.png)
- Activating auto import results in:
   ```ts
   import { shared } from "../target-tsc-build/shared/main";
   
   console.log(shared);
   ```
   The `outDir` file is the primary suggestion, therefore it is used for auto import:
   ![image](https://user-images.githubusercontent.com/921609/94349614-06fabc80-003e-11eb-9c2c-933f3249ec30.png)

Import suggestions should never be provided for compiled files—only source files.

Note I also tried adding `exclude: ["./target-tsc-build/"]` and `"declarationMaps": true` to all configs, but that didn't seem to help.

**Playground Link:** 

**Related Issues:**

**Comment by andrewbranch** [comment]
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/38856; have you tried the nightly?

**Comment by OliverJAsh** [comment]
Yes that seems to fix it ❤️ Closing this as a duplicate.
