### ISSUE TITLE
Properties/methods of type becomes undefined after compile

### ISSUE THREAD

**Issue by elitance** [microsoft/TypeScript#40799]
I was just testing TypeScript, and something came up like this: `TypeError: Cannot read property 'forEach' of undefined`. What I did is this: `let x: number[]; x.forEach((el) => { ... })`, and I know how to fix this- by assigning `[]` to `x`. But I think it would be better to be compiled like this:
```typescript
let n: number; // compiles into `let n = 0;` or sth else
let s: string; // compiles into `let n = ''`
let a: number[] // compiles into `let a = []`
// and so on
```

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). :-) That'll make it much easier for the TypeScript team.

What you propose would go against the [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by elitance** [comment]
Sorry, I didn't checked it out!
