### ISSUE TITLE
Type '{ dateStyle: string; }' has no properties in common with type 'DateTimeFormatOptions'.ts(2559)

### ISSUE THREAD

**Issue by TheoMer** [microsoft/TypeScript#40806]
"typescript": "^4.0.3"

How do I resolve the above mentioned typescript error I'm receiving on the following code?:

components/OrderListItem.tsx
```
const newedate = (_date) => {
  const options = {dateStyle: 'medium'}; //{ weekday: 'long', hour: 'numeric'};
  const dateT = new Intl.DateTimeFormat('en-UK', options).format(_date);
  return dateT;
}
```

[![enter image description here][1]][1]

My partial repo is here: https://github.com/TheoMer/next_apollo

  [1]: https://i.stack.imgur.com/1sZb3.jpg

**Comment by RyanCavanaugh** [comment]
`dateStyle` isn't a recognized property in our lib file yet; we should add it

**Comment by tvandinther** [comment]
Any progress on integrating these properties into TypeScript?
