### ISSUE TITLE
Performance regression in 4.0 with semantics-only `createWatchProgram`?

### ISSUE THREAD

**Issue by dfreeman** [microsoft/TypeScript#40808]
The wiki here has [a page that outlines ways to programmatically create a watched build](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher), and suggests that `createSemanticDiagnosticsBuilderProgram` is likely preferable to `createEmitAndSemanticDiagnosticsBuilderProgram` for use cases that aren't interested in emit.

The `ember-cli-typescript` package uses the APIs outlined in that wiki page to integrate typechecking results into Ember CLI builds, and [there've been several reports](https://github.com/typed-ember/ember-cli-typescript/issues/1278) of slower re-checks after a file change from folks that have updated to `typescript@4`.

**TypeScript Version:**
 - 3.9.7 (works as expected)
 - 4.0.3 (exhibits slowdown)
 - 4.1.0-dev.20200928 (exhibits slowdown)

**Search Terms:**
 - `createWatchProgram`
 - `createSemanticDiagnosticsBuilderProgram`
 - 4.0 performance

**Code**

```ts
const ts = require('typescript');
const host = ts.createWatchCompilerHost(
  'tsconfig.json',
  { noEmit: true },
  ts.sys,
  ts.createSemanticDiagnosticsBuilderProgram
);

ts.createWatchProgram(host);
```

**Expected behavior:**
Re-checks are at least as fast with `createSemanticDiagnosticsBuilderProgram` as with its counterpart that tracks emit.

**Actual behavior:**
In a project that takes on the order of 15s to typecheck at startup, re-checking takes less than 1s with the above invocation in 3.9, as well as in 4.0 and the most recent 4.1 nightly when using `createEmitAndSemanticDiagnosticsBuilderProgram`.

When using `createSemanticDiagnosticsBuilderProgram` in 4.0 and 4.1, though, re-checking consistently takes around 5s.

**Comment by sheetalkamat** [comment]
@dfreeman Can you please provide the repro where this happens.. i ran this on sample and it seems to be using cached diagnostics correctly.

**Comment by dfreeman** [comment]
@sheetalkamat Apologies, the project I mentioned above is private, but I'd assumed since it had been reported by several others that it would reproduce easily.

Here's a reproduction repo I put together: https://github.com/dfreeman/ts-40808-perf-demo
(the use of Babel there is incidental; it's just the first thing that popped to mind to give some mass to the typecheck without generating a bunch of code myself)

**Comment by sheetalkamat** [comment]
Note that the issue is coming up because of changes in #39122 where we emit build info.
Your code is doing the right thing because you want to emit tsbuildinfo so it can be reused.

**Comment by andreyfel** [comment]
@sheetalkamat will the fix be released as a patch fix for 4.0.x series?

**Comment by sheetalkamat** [comment]
@DanielRosenwasser is it feasible to take #40880 for 4.0 patch

**Comment by DanielRosenwasser** [comment]
Yeah, I think that'd be reasonable.
