### ISSUE TITLE
Inconsistent contextual typing for functions between object literals and tuples

### ISSUE THREAD

**Issue by artemiswkearney** [microsoft/TypeScript#40809]
**TypeScript Version:** 4.1.0-dev.20200928

**Search Terms:** contextual type, function, generic, mapped type, inference, tuple, implicit any, noImplicitAny

**Code**

```ts
type Mapped<T> = {
    [K in keyof T]: [T[K], (arg: T) => boolean];
}
function inferMapped<T>(arg: Mapped<T>): void {}
inferMapped({
    key: [3, (arg) => arg.key > 5],
})

type Mapped2<T> = {
    [K in keyof T]: [T[K], unknown extends T ? unknown : (arg: T) => boolean];
}
function inferMapped2<T>(arg: Mapped2<T>): void {}
inferMapped2({
    key: [3, (arg) => arg.key > 5],
})

type MappedReadonly<T> = {
    readonly [K in keyof T]: readonly [T[K], (arg: T) => boolean];
}
function inferMappedReadonly<T>(arg: MappedReadonly<T>): void {}
inferMappedReadonly({
    key: [3, (arg) => arg.key > 5],
} as const)

type MappedObj<T> = {
    [K in keyof T]: { 0: T[K], 1: (arg: T) => boolean };
}
function inferMappedObj<T>(arg: MappedObj<T>): void {}
inferMappedObj({
    key: { 0: 3, 1: (arg) => arg.key > 5 },
})
```

**Expected behavior:**
At least one of (`inferMapped`, `inferMapped2`, `inferMappedReadonly`) should provide the same contextual type for the tuple's second element (the arrow function) as `inferMappedObj` provides
**Actual behavior:**
- `inferMapped` completely fails to infer `T` (annoying but not entirely unreasonable)
- `inferMapped2` and `inferMappedReadonly` correctly infer `T`, and show the correct type for `key` (`[number, (arg: { key: number; }) => boolean]`) as a tooltip in Playground, but the arrow function's parameter is treated as an implicit `any` even though its type is known
- `inferMappedObj` works perfectly; the arrow function's `arg` is correctly contextually typed as `{ key: number; }`

**Playground Link:**  [here](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200928#code/C4TwDgpgBAsghmSATAPAFQHxQLxQN4CwAUFKVANoDSUAlgHZQDWEIA9gGZRoC6AXBWircANFAAUcAE4BzfmgCUOLACNWrADYQ4dbgG5iAX2LsArnQDGwGqwb12ESfEQRUmCTP5Pk6DPP4A3VhokfCMiOwcvFzFCEjJmEH5yAGZRd2lFbCwpaQA6BKgsAFYRQ3liYlBIWARkACYfHHxiMgpqeiYWDi4+ASFRM0Y6VgB3BggAD2AIOiQAZy4oAH4oQeGxqH50uUyVNU1tPUNjM0trWzp7R1qXBrcczxukO98AoJC8MIjr52eYlviLCSqXEOV2UBy+RYhSgJWEZQqRCq0CiSAASlokDZ1CBGrhYq1JJjsSA2rQGAlujx+ES4Fi6Di+pQRKCPFxwaoNFodPoiGFTBYrDZyVdURi6SSfNsar9xfScT4-FBAsFQsRvmLiQyQP84qQEsC0mClBCZFDScVSnyIQtzDY5sBykRKuAUU8APLKABWeOaerJHUpnGp+CgAAY5P0oABGLYPdkmzkHBgGXn805Ci6ij3eqXx1Gen2YJUqj5fS6RHNe3WtA2hiNQEGx1kZE2QgrFKAGeF8+RAA)
**Related Issues:**  I got the idea to use mapped type inference here from a Vue typings issue, but I can't find it now - the solution there involved return type annotations to avoid problems from circularity, but nothing is inferred based on return types here, and the annotations don't help anyway

**Comment by RyanCavanaugh** [comment]
Interesting, I expected some `as const`s to fix these but nothing much seemed to work

**Comment by artemiswkearney** [comment]
Playing around some more, and it seems like `as const` just obliterates contextual types for functions in general?  
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogHgQwLZgDbQLxQN5QE4QIAmA9gHaohQDWEIAXFABQBuCqArhI2R0gEYQ8ASigYAfFF4ChAbigBfALAAoAGYcyAY2ABLclGAJaAZ3jI0EJgjwBzRuZTphDxE+i4CwDnjJQbtvLKKqpGpo6WTLi0INZ2op4Q3r7+dkGKwrKhxhBmbpHRdHG2CfhJPn4B6Qr+JlBa5CbAmUA)  
Probably deserves its own issue? This really limits the usefulness of `as const` in any context involving functions.

**Comment by ahejlsberg** [comment]
I agree it's inconsistent that inference succeeds with an object literal but fails with an equivalent tuple type. It appears the fix is as simple as adding an additional check for tuple types in `isPartiallyInferableType`, all of the other logic is already there. I will put up a PR.
