### ISSUE TITLE
operatorOverloading: boolean compiler option for alternative type checking (no language or emit changes).

### ISSUE THREAD

**Issue by david-geo-holmes** [microsoft/TypeScript#40801]
## Search Terms

operator overloading

## Suggestion

I recognize that operator overloading will likely never happen in JavaScript because of the performance penalty. I also recognize the TypeScript principle of not modifying the underlying JavaScript intent in TypeScript code. Accepting these two assumptions, I would like to propose an 'operatorOverloding' option that analyzes the code differently (if set to true), while retaining the normal behavior when set to false. The change in analysis could range from the naive checking of argument types and computing a likely type to a more opinionated examination of the arguments for "dunder" (double underscore) or "special methods" similar to Python. In either setting of the boolean flag there is no change to emitted code (although it may be possible in the opt-in case to generate the overloading code), and users who opt-in would use JavaScript post-processing to modify the code.

I have been using this approach for some time now in my educational tool, https://www.stemcstudio.com.

The TypeScript compiler would make no changes to the emitted code, whichever way the boolean the flag is set. The idea is that users who want to implement overloading can use the TypeScript compiler untouched and then use a tree traversal on the emitted JavaScript to converted JavaScript mathematical operators to function calls that perform the overloading action. I believe it might be practical for the TypeScript compiler to emit different code, but that is not a requirement at this stage.

## Use Cases

1) An existing user who is not interested in Operator Overloading:
Existing users would not be impacted in any noticeable way. There would be no change in behavior with the flag undefined or set to false. There would be negligible performance impact from the checking of the flag.

2) A user who wants to use TypeScript in an educational or research setting where operator overloading enhances the usability of the language:
Users who set the flag to true would get modified type checking that would allow a wider range of arguments in certain situations involving mathematical operators. Further, by assuming that operator overloading follows the established dunder convention in Python, it should be possible to infer the resulting types with sufficient precision (some ambiguity may happen in some cases). 

It is extremely beneficial in educational and research environments to be able to perform operator overloading.

## Examples

For a simple example, see Line 27 in index.ts of https://www.stemcstudio.com/gists/73e68084a4c927ce20bb0b4d06b33192

This has been implemented by using an operatorOverloading compiler flag option in TypeScript.

For an example of dunder methods implemented in TypeScript:

Starting at line 1832:

https://github.com/geometryzen/davinci-eight/blob/master/src/lib/math/Geometric3.ts

I realize that the runtime implementation is of less concern. However a proven prototype is:

https://github.com/geometryzen/davinci-mathscript/blob/master/src/davinci-mathscript.ts

Note: I may separate the design-time and runtime code for this last example in the near future.

Finally, I just want to say that TypeScript is awesome and it has great potential in educational learning settings by guiding novice users to produce correct code and allowing experienced users to write non-trivial programs using in-browser tools to reduce the learning curve.

## Checklist

My suggestion meets these guidelines:

* [Yes] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [Yes] This wouldn't change the runtime behavior of existing JavaScript code
* [Yes] This could be implemented without emitting different JS based on the types of the expressions
* [Yes] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [Yes] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MaxGraey** [comment]
> I recognize that operator overloading will likely never happen in JavaScript because of the performance penalty

How you recognize this?
Did you see this [Stage 1 proposal](https://github.com/tc39/proposal-operator-overloading)?

Btw you could do operator overloading in JS but it's pretty hacky:
https://gist.github.com/pyrocto/5a068100abd5ff6dfbe69a73bbc510d7

**Comment by RyanCavanaugh** [comment]
Runtime systems that aren't JavaScript (which includes JS pre/postprocessed to behave differently from vanilla JS) are outside the scope of our project.

Paths forward would be #2361 (not sure if this would work since `*` is still always going to return a `number`), or the ES operator overloading proposal.

**Comment by stemcstudio** [comment]
@MaxGraey Thanks for pointing out that I appear to be working from an out-of-date assumption; something I read somewhere, maybe 5 years ago. I had not seen the Stage 1 proposal. I haven't digested it yet, but I accept that things in flux lie this could cause the tail (TypeScript) to try to wag the dog (JavaScript). I had seen something at least similar to the JS hack but I felt at the time that I read it that it wasn't going to fall short somewhere and left it alone.

**Comment by stemcstudio** [comment]
@RyanCavanaugh OK. Thanks for pointing out #2361. Wasn't on my radar.
