### ISSUE TITLE
inlined infer gives a different result

### ISSUE THREAD

**Issue by note89** [microsoft/TypeScript#40810]
**TypeScript Version:**  4.0.2 and nightly 4.1.0-dev.20200928

**Search Terms:**
inlined infer gives a different result
Infer bug
inline bug

**Code**

```ts
type ArgsA = Promise<1>  
type ArgsB = Promise<1> | "remove-me"
// Inline
type Ans0A = ArgsA extends Promise<infer M> ? M : never // -> 1
type Ans0B = ArgsB extends Promise<infer M> ? M : never // -> never
// Put it in a type constructor and it gives different correct result
type ExtractPromise<P> = P extends Promise<infer M> ? M : never
type Ans1A = ExtractPromise<ArgsA> // -> 1
type Ans1B = ExtractPromise<ArgsB> // -> 1
```

**Expected behavior:**
That both approaches yield the same result, (inline seems to have a bug)

**Actual behavior:**
The inline version seems to have a bug. 

**Playground Link:**
https://www.typescriptlang.org/play?ts=4.1.0-dev.20200928#code/C4TwDgpgBAggTgcwM4ygXigBTgewLYCWSEAPAIwB8UUAUKJLIkgELpa6HHlUA+UARHAh4cANwgBaPBH40A9HKgBJAHYAbAioh1w0GCqQAGVBnjJUEAB7AIKgCZJ2+IqU0AzCHCgBZKgH4fKAAuKC1xLwUoCSoyHQZ9I1ZTJlYrG3tHbGcud08ff0CQsLzI6NCIcPlFTABXYCgCes0oAEMoemgAYxwDYDgazuAcLxb7BvqEAnFHOwI3DyEVeu64IUGoISQatWA46ABRazgWwazOUkwqDEwoNNsHJ3OSXK9fKADvYPLKjtgDMhMUEOfROwDOLhIZhQVFKMT2fyQZCSQKOoPBXChzBhijKZCAA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `ExtractPromise<P>` is distributive because it has a conditional type over a bare type parameter, but the other positions don't. A "same" version would be
```ts
type ExtractPromise<P> = [P] extends [Promise<infer M>] ? M : never
```
which behaves identically

**Comment by note89** [comment]
@RyanCavanaugh Thank you for your swift answer I did not know about this difference in `extends` and that is only distributed for naked type parameters.

Docs for others that end up here.
https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types
