### ISSUE TITLE
Optional chaining seems to not work properly with union types including `void`

### ISSUE THREAD

**Issue by benlesh** [microsoft/TypeScript#40818]
**TypeScript Version:**  4.0.2

**Search Terms:** optional chain void, optional chaining

**Code**

```ts
function bar(): number | void {
    return 0.5 < Math.random() ? 123 : undefined;
}

bar()?.toString(); // ERROR: property "toString" does not exist on type "number | void"
```

**Expected behavior:**

No error.

**Actual behavior:**

ERROR: property "toString" does not exist on type "number | void"

Note that if the return type was `number | undefined` it works fine.  Similarly if the return type is just inferred, and you return `void 0` instead of `undefined`, it's fine (because the inferred return is `number | undefined`).

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.0.2#code/GYVwdgxgLglg9mABMOcAUBKRBvAsAKESMQCcBTKEEpABgDoBWRAHkQFkBDKACzpI7AATOAFtMiAPyIAjACYAzIgBcicILLAYYMoIDcBAL4ECKdBgl0ocAMpQSWgOaZ9+Y-lCRYCRACMOJTBUwEBEfMhJEAB9EADc4GEEcAmJSCipaRhZ2Ll5+IVFxKTlFFTUNLR0XI1d8PwDzSxs7R2cgA

**Related Issues:** 
Not really.

**Comment by RyanCavanaugh** [comment]
This is a correct error. A legal implementation of `bar` would be
```ts
const m: () => void = () => {
    return ({ toString: 4 });
}

function bar(): number | void {
    return 0.5 < Math.random() ? 123 : m()
}

// Crashes half the time
bar()?.toString(); 
```

`void` is not an alias for `undefined` and you will encounter no end of surprises if you treat it as if it were 🙂 see https://stackoverflow.com/questions/58885485/why-does-typescript-have-both-void-and-undefined

**Comment by benlesh** [comment]
So.. just to be clear... I can't check the truthiness of `T | void` in ANY conditional check? And that's why it doesn't work with `?.` in the manner I'm expecting?

**Comment by benlesh** [comment]
@RyanCavanaugh I've updated my question, to avoid the distraction of `undefined` vs `void`. Which wasn't at all the issue. The behavior of `void` with `?.` is inconsistent with other comparable checks against `void` in TypeScript.

So it's either that the behavior with `?.` is broken, or the behavior with other conditional checks on `void` are broken. If `void` is not to be observed, then I'd think it would error on any read of that kind, and the behavior above would not have been surprising at all, as it would have been well-known for years.

If folks are surprised by the behavior of a ubiquitous type like `void`, perhaps the behavior isn't well defined?

I suspect that the answer would be to have `?.` be consistent with other comparable checks.

**Comment by RyanCavanaugh** [comment]
@benlesh I don't see any edits to the OP; can you provide the new example?

**Comment by RyanCavanaugh** [comment]
Your example on twitter is subject to the same reasoning as my prior explanation

**Comment by benlesh** [comment]
Hmm. Strange it didn't update.

Seems quirky, but I've only had to work around it once. And now I know, so it's no longer surprising. 

🤷‍♂️

Thanks for the explanation.
