### ISSUE TITLE
Missing SubmitEvent in auto complete

### ISSUE THREAD

**Issue by MrTA2** [microsoft/TypeScript#40811]
**Search Terms:** 

SubmitEvent

**Code** 

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
function form_Submit(e:SubmitEvent):void { ....... }

```

**Expected behavior:** 

SubmitEvent is recognized as a DOM type

**Actual behavior:**

It is not

**Playground Link:**  

**Related Issues:**

This can be solved by adding this to lib.dom.d.ts:

interface SubmitEvent extends Event
{
  readonly submitter: HTMLElement;
}
declare var SubmitEvent: {
  prototype: SubmitEvent;
  new(type: string, eventInitDict?: EventInit): SubmitEvent;
};

**Comment by javan** [comment]
> This can be solved by adding this to lib.dom.d.ts: …

I don't think that solves it completely. The event handler interfaces would need updating from `Event` → `SubmitEvent` as well: https://github.com/microsoft/TypeScript/blob/f4157b41dbf9534a5fb5767672599f012bb0636f/lib/lib.dom.d.ts#L5755 https://github.com/microsoft/TypeScript/blob/f4157b41dbf9534a5fb5767672599f012bb0636f/lib/lib.dom.d.ts#L6007

Worth noting that `SubmitEvent` isn't (yet?) implemented in Safari. References:
- https://bugs.webkit.org/show_bug.cgi?id=202978
- https://github.com/whatwg/html/pull/4984

**Comment by TechQuery** [comment]
@MrTA2 this bug has been fixed by microsoft/TypeScript-DOM-lib-generator#1105, you can close it.
