### ISSUE TITLE
Typescript IntelliSense definitions are not automatically updated on npm package update

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/TypeScript#40815]
- VSCode Version: 1.49.1
- OS Version: OS Linux x64 5.4.0-47-generic snap

Steps to Reproduce:

1. In my case, I have my own npm typescript package that I develop.
2. Have it installed in the current project
3. Deploy a new version of the npm package that changes its .d.ts
4. Run npm i to update this package
5. The new typing IntelliSense is not applied automatically. To force the update, it is required the VsCode restart, or as I found out, right click some package method and select `Go to definition`, that will open the .d.ts file and the IntelliSense is now correctly updated.

As the IntelliSense updates when we add a package to a project, it should also automatically update when we install a new version of a already added package. Isn't a big deal, but, should be fixed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by SrBrahma** [comment]
This happens on any project that updates a package version. You can try it by installing an old package version, using some methods / types and then updating it to a new version where they have changed. Or trying to use a method of the new version. It won't find it automatically and throw errors about it not existing. You have to either open the package definition files or reloading VsCode.

**Comment by Boztown** [comment]
I experience this as well.

```
Version: 1.54.0-insider
Commit: fe6eb68d228472db7e656ffbf2b10f5e987fad48
Date: 2021-02-10T05:21:46.685Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```

In my `package.json` I'm referencing a local package like this:

```
    "@types/react-dom": "^16.9.10",
    "api-schema": "file:../common/api_schema",
    "aws-amplify": "^3.3.14"
```

It was taking all kinds of flailing to get my changes to `api-schema` to show up in intellisense, and a restart would usually do the trick but be a huge pain. The `Go to definition` trick mentioned in the parent works (thank you for the tip @SrBrahma).
