### ISSUE TITLE
"TypeError: Cannot read property 'kind' of undefined" when "incremental" is enabled

### ISSUE THREAD

**Issue by salemhilal** [microsoft/TypeScript#40819]
I run into an exception that only occurs when `incremental` is enabled. When it's disabled, typechecking occurs as expected and completes in around 40 seconds. When it's enabled, typechecking takes several minutes and produces the error below:

```sh
╰─ yarn typecheck
yarn run v1.22.4
$ env NODE_OPTIONS="--max-old-space_size=16000 --trace-warnings" yarnpkg tsc --project tsconfig.json
$ /home/shilal/development/Etsyweb/node_modules/.bin/tsc --project tsconfig.json
/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:84774
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isEntityNameExpression (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:13169:21)
    at serializeMaybeAliasAssignment (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39495:42)
    at serializeSymbolWorker (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39161:49)
    at serializeSymbol (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39126:38)
    at /home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39107:25
    at Map.forEach (<anonymous>)
    at visitSymbolTable (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39106:33)
    at serializeAsNamespaceDeclaration (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39370:25)
    at serializeAsFunctionNamespaceMerge (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39348:25)
    at serializeMaybeAliasAssignment (/home/shilal/development/Etsyweb/node_modules/typescript/lib/tsc.js:39525:29)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Some things of note:
* I'm working in a monorep with around 13k JS files.
* There are currently only 2 TypeScript files.
* `noEmit` is enabled and `checkJs` is disabled.

**TypeScript Version:** 4.0.3

**Search Terms:**
Cannot read property 'kind' of undefined

**Code**
There's quite a bit of code, and because it takes so long to run the failure case, it's been hard to narrow down the problem. I'd love any advice here. My TSConfig looks like this, if it's of any help:

```ts
{
  "compilerOptions": {
    "jsx": "react",
    "allowJs": true,
    "checkJs": false,
    "noEmit": true,
    "incremental": true,
    "extendedDiagnostics": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "esModuleInterop": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "declaration": false,
    "target": "ES2019",
    "module": "ES2015",
    "moduleResolution": "node",
    "baseUrl": ".",

    "paths": {
      "*": ["*", "./htdocs/assets/js/*"],
      "jquery": ["node_modules/jquery-2"],
      "template!*": ["./templates/*", "./templates/*.mustache"]
    }
  },

  "include": [
    "htdocs/assets/js/@types/",
    "htdocs/assets/js"
  ],

  "exclude": [
    "node_modules"
  ]
}

```

**Expected behavior:**
The first run of the type checker should complete in a reasonable amount of time with `incremental` enabled, and subsequent runs should be faster.

**Actual behavior:**
The exception above is thrown.

**Playground Link:** 
N/A

**Related Issues:** 
This issue might be related, but I think it's more likely that they both just have similar error messages.
https://github.com/microsoft/TypeScript/issues/40522

**Comment by RyanCavanaugh** [comment]
The best way to start tracking these down is to attach a debugger and see which line of code is causing TS to crash:

 * Run `node --inspect-brk path/to/tsc.js --yourCmdLine` where `path/to/tsc.js` is an actual path to `tsc.js` and `--yourCmdLine` is what you would normally pass `tsc`
 * Attach with your debugger of choice (`about:inspect` in Chromium-based browsers works well)
 * Enable "Break on unhandled exceptions"
 * Run
 * In theory the debugger stops on the crash. Depending on the stack frame, you'll have a few clues available to work from:
  * If you have a `node`, run `ts.getTextOfNode(node)` in the console to see its text. You can use `ts.getTextOfNode(node.parent)`, `ts.getTextOfNode(node.parent.parent)`, and so on, to get more context if needed
  * If something with a name that suggest it's a `symbol` is in scope, `symbol.valueDeclaration` and/or `symbol.declarations` will be a node or array of nodes (respectively) that can be inspected the same way
  * If it's crashing on a type, you can use `ts.typeToString(type)` to get more information about it. Types also usually have a `symbol` property which will in turn lead to you the node that declared them

Hope that helps!

**Comment by RyanCavanaugh** [comment]
I think that's actually enough information for us to fix it (you're welcome to take a stab at a fix yourself if you want, but I can't offer 1:1 support on that). Thanks for the great debugging!

**Comment by salemhilal** [comment]
No problem! If you have time, I'd love to know more about what the actual problem is. Is `serializeMaybeAliasAssignment` misidentifying the type of export statement in use?

**Comment by salemhilal** [comment]
Hey @RyanCavanaugh just wanted to bump this. I have a little spare time this weekend, and if I have a better understanding of the problem, I'd love to use the time to submit a patch (I swear this isn't related to hacktoberfest).

**Comment by sandersn** [comment]
Sorry, didn't see this till now. My first guess is that the support for ES-style `export default` is interfering with commonjs-style `exports.default=`. Without looking, I don't yet know if serializeMaybeAliasAssignment is where it happens

**Comment by sdsl1** [comment]
any one can resolved this problem
We're sorry, but it seems like something is not quite right. Please try again or contact support if the problem persists.
Error Details:
TypeError: Cannot read properties of undefined (reading 'fantasy-land/map')
at https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2559536
at f2 (https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2557188)
at https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2573922
at https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2558984
at https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2554882
at WalletBalanceDropdown_selectors_getData (https://login.blockchain.com/21.2f6984f2a6.js:1038:2500)
at Function.mapToProps (https://login.blockchain.com/21.2f6984f2a6.js:1115:4263)
at mapToPropsProxy (https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2801847)
at Function.detectFactoryAndVerify (https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2802034)
at mapToPropsProxy (https://login.blockchain.com/vendor.6a0cf2db9c.js:2:2801847)
