### ISSUE TITLE
Inconsistent behaviour of rename operation for TypeScript exported names - VSCode ignores not-yet-opened TS projects.

### ISSUE THREAD

**Issue by MBelniak** [microsoft/TypeScript#40812]
- VSCode Version: 1.44.1
- OS Version: Linux x64 4.15.0-46-generic

I am working on quite big project with multiple shared components and multiple modules importing these components via node_modules (linked by yarn). I have enabled declaration maps for components, so navigation works both ways - from usage to component's definition and the other way. 

But, when I do rename refactoring of component's class name (the one that is exported), almost none of usages are renamed. One argument could be that it's because we use default exports, but there are a few places, where names are changed.

Later, I tried to use baseUrl and paths properties in module's tsconfig.json, so now I import, let's say "@component/button" and set the path for "@component/button" to Button component's project (original one, not in node_modules). When I show all references of Button it displays all 100+ references in mentioned module, but again, rename operation works only in files, which I have visited before. Non-visited files are untouched.

My expectation is that either all or none usages of Button in module having path for "@component/button" set to Button's project and importing it via ```import Button from "@component/button"``` are renamed. 

I tried Restarting TS server few times and use named imports, but effect was the same.

**Comment by mjbvz** [comment]
@MBelniak You are on an old VS Code version. Have you tested on VS code 1.49+ as well? Are you using a workspace version of TypeScript?

**Comment by MBelniak** [comment]
I checked it in VSCode 1.49.2 too, the problem still occurs. I created a simple repo to reproduce the problem: https://github.com/MBelniak/ReproduceTSPathIssue
If I open VSCode and go to button/src/Button.tsx (without touching screen directory) and try to rename Button class, it is not renamed in screen/src/Screen.tsx. But if I open screen/src/Screen.tsx and then rename Button class from button/src/Button.tsx level, it is renamed.

**Comment by mjbvz** [comment]
You need to configure [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) if you want the projects to be properly linked. Otherwise we will only load the currently active project

**Comment by MBelniak** [comment]
Ok, thanks for quick clarification.

**Comment by MBelniak** [comment]
@mjbvz I tried using project references and still the problem occurs. I cannot rename Button across all references without opening 'screen' module. Please see https://github.com/MBelniak/ReproduceTSPathIssue with a new commit. Maybe I did something wrong which I don't know about.
I also tried linking button via node_modules, but it didn't help (even though declaration maps worked correctly).

**Comment by MBelniak** [comment]
@mjbvz Will you find some time to look at that?
