### ISSUE TITLE
Suggestion http://www.typescriptlang.org/: Add Github Stars upfront

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#4082]
Lots of OSS projects do this. Adding this to the homepage will definitely increase OSS interaction (stars matter). Most projects use https://ghbtns.com/

Link for us: 
https://ghbtns.com/github-btn.html?user=Microsoft&repo=TypeScript&type=star&count=true&size=large

Code that needs to go in : 

```html
<iframe src="https://ghbtns.com/github-btn.html?user=Microsoft&repo=TypeScript&type=star&count=true&size=large" frameborder="0" scrolling="0" width="160px" height="30px"></iframe>
```

Demo : 

![image](https://cloud.githubusercontent.com/assets/874898/8973565/6d337352-36a9-11e5-82f7-c01c4aff4d73.png)

# More

If `stars` are used as a *link to github* it increases the users chances of actually staring the project.

**Comment by RyanCavanaugh** [comment]
We have some updates in the pipe -- feel free to revisit once you see them :wink:
