### ISSUE TITLE
createTempVariable() should also try to not shadowing upper lexical environment temp variables

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#40826]
**TypeScript Version:**  3.9.3

**Search Terms:**

**Code**

I'm using createTempVariable but I found it is buggy.

The buggy version: https://github.com/Jack-Works/react/commit/792a7f713842db6920c796326b90f324f8a3ea5f#diff-6624517c3255932b3079f651161b7df0

Fixed version:

https://github.com/Jack-Works/react/commit/4ae646b2adee844a99e9ea5af53b43cf8bf725aa#diff-6624517c3255932b3079f651161b7df0

Reproduction:

```js
const ts = require('typescript')
const t = require('./ReactFreshTypeScriptTransformer.js')

console.log(
    ts.transpileModule(
        `
import { useDefaultWallet } from '../../plugins/Wallet/hooks/useWallet'

/**
 * Get the address of the default wallet
 */
export function useAccount() {
    const wallet = useDefaultWallet()
    return wallet?.address ?? ''
}
`,
        {
            transformers: { before: [t()] },
            compilerOptions: { target: ts.ScriptTarget.ES2017 },
        }
    ).outputText
)
```

The buggy result using `createTempVariable()`:

```js
var _a;
_a = $RefreshSig$();
import { useDefaultWallet } from '../../plugins/Wallet/hooks/useWallet';
/**
 * Get the address of the default wallet
 */
export function useAccount() {
    var _a;
    _a();
    const wallet = useDefaultWallet();
    return (_a = wallet === null || wallet === void 0 ? void 0 : wallet.address) !== null && _a !== void 0 ? _a : '';        
}
_a(useAccount, "Zqcse9ORXvHAGVGDGSjWLnVdvA4=", false, () => [useDefaultWallet]);
```

As you can see, downleveling `??` syntax create a new variable also called "_a" which shadows my upper variable "_a", then `_a()` leads to an runtime error.

The correct version using `createFileLevelUniqueName()`:

```js
var $c0;
$c0 = $RefreshSig$();
import { useDefaultWallet } from '../../plugins/Wallet/hooks/useWallet';
/**
 * Get the address of the default wallet
 */
export function useAccount() {
    var _a;
    $c0();
    const wallet = useDefaultWallet();
    return (_a = wallet === null || wallet === void 0 ? void 0 : wallet.address) !== null && _a !== void 0 ? _a : '';
}
$c0(useAccount, "Zqcse9ORXvHAGVGDGSjWLnVdvA4=", false, () => [useDefaultWallet]);
```

**Comment by Jack-Works** [comment]
If createTempVariable can accept this enum, this problem will be resolved!

```ts
export enum GeneratedIdentifierFlags {
        None = 0,
        ReservedInNestedScopes = 8,
        Optimistic = 16,
        FileLevel = 32,
        AllowNameSubstitution = 64
    }
```

**Comment by Jack-Works** [comment]
Exposed: (4.1.0 beta) signature

`createTempVariable(recordTempVariable: ((node: Identifier) => void) | undefined): Identifier`

Signature in source code:

`createTempVariable(recordTempVariable: ((node: Identifier) => void) | undefined, reservedInNestedScopes?: boolean): GeneratedIdentifier`

**Comment by Jack-Works** [comment]
Please explosure those signatures! It's very useful when transforming code

**Comment by rbuckton** [comment]
In the meantime, is `factory.createUniqueName` an option?

**Comment by Jack-Works** [comment]
> In the meantime, is `factory.createUniqueName` an option?

I don't know, but expose `reservedInNestedScopes?: boolean` will be very useful
