### ISSUE TITLE
Provide a standalone build of typescript for use in browser?

### ISSUE THREAD

**Issue by bahuwang** [microsoft/TypeScript#40828]
When loaded in a browser, typescript automatically compile and execute all script tags.
 Like the example code, as shown below:
```
<script src="typescript-standalone.js"></script>
<script type="text/typescript">
function greetText(name: string): string {
  return "Hello " + name;
}
</script>
```

**Comment by RyanCavanaugh** [comment]
This is a neat idea but not something within the scope of our project.
