### ISSUE TITLE
Project references: missing errors in editor (VS Code)

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#40829]
**TypeScript Version:**  4.0.3

**Search Terms:**

Reduced test case: https://github.com/OliverJAsh/ts-project-references-playground/tree/no-vs-code-errors. Below I have inlined the code from this repository.

**Code**

`tsconfig.json`:
```json
{
  "references": [
    {
      "path": "./shared/tsconfig.json"
    },
    {
      "path": "./server/tsconfig.json"
    }
  ],
  "files": []
}
```

`shared/tsconfig.json`:
```json
{
  "compilerOptions": {
    "composite": true,
    "outDir": "../target-tsc-build/",
    "rootDir": "..",
    "lib": ["DOM", "ES2015"]
  },
  "files": ["./index.ts"]
}
```

`shared/index.ts`:
```ts
export const FileContainer = { file: File };
```
`server/tsconfig.json`:
```json
{
    "compilerOptions": {
      "outDir": "../target-tsc-build/",
      "rootDir": "..",
      "lib": ["ES2015"]
    },
    "files": ["./index.ts"],
    "references": [
        {
            "path": "../shared/tsconfig.json"
        }
    ]
  }  
```

`server/index.ts`:
```ts
import { FileContainer } from "../shared/index";

FileContainer;
```

**Expected behavior:**

- When I run `tsc --build tsconfig.json`, I should get errors because the global type `File` does not exist in the project `server/tsconfig.json` (because we intentionally omit the `DOM` types).
- When I open `shared/index.ts` in my editor (VS Code), I should see the same errors as those returned by `tsc --build tsconfig.json`.

**Actual behavior:**

`tsc --build tsconfig.json` errors correctly, but these errors are never shown inside VS Code when opening `shared/index.ts`.

Perhaps this is because VS Code thinks `shared/index.ts` only belongs to the `shared/tsconfig.json` project, which has no errors. However, because `shared/index.ts` is imported by `server/index.ts`, it also "belongs" to the `server/tsconfig.json` project. Therefore VS Code also needs to check for errors inside this project.

I expect VS Code to show errors across all projects the current file is used by.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@mjbvz how does VS Code determine this?

**Comment by mjbvz** [comment]
@RyanCavanaugh We leave all the project logic up to Typescript. VS Code just talks about files and the TypeScript server puts them into the correct project

**Comment by MitaiGit** [comment]
please port the package TypeScript to Visual Studio Code

**Comment by mjbvz** [comment]
@OliverJAsh Do you still see this issue with the latest TypeScript 4.2 beta build?

@RyanCavanaugh Sorry I forgot to unassign myself so I don't think this issue got triaged

**Comment by OliverJAsh** [comment]
> @OliverJAsh Do you still see this issue with the latest TypeScript 4.2 beta build?

Just tested it, yes I still see the issue.

**Comment by sheetalkamat** [comment]
This is working as intended. In editor the errors are asked for defualt project for file and that is shared/tsconfig.json which does not error on that file with that config even with `tsc --build`
```
>node c:\TypeScript\built\local\tsc.js -b -v
[2:11:01 PM] Projects in this build:
    * shared/tsconfig.json
    * server/tsconfig.json
    * tsconfig.json

[2:11:01 PM] Project 'shared/tsconfig.json' is out of date because output file 'target-tsc-build/shared/index.js' does not exist

[2:11:01 PM] Building project 'c:/temp/ts-project-references-playground/shared/tsconfig.json'...

[2:11:03 PM] Project 'server/tsconfig.json' is out of date because output file 'target-tsc-build/server/index.js' does not exist

[2:11:03 PM] Building project 'c:/temp/ts-project-references-playground/server/tsconfig.json'...

target-tsc-build/shared/index.d.ts:3:24 - error TS2304: Cannot find name 'BlobPart'.

3         new (fileBits: BlobPart[], fileName: string, options?: FilePropertyBag): File;
                         ~~~~~~~~

target-tsc-build/shared/index.d.ts:3:64 - error TS2304: Cannot find name 'FilePropertyBag'.

3         new (fileBits: BlobPart[], fileName: string, options?: FilePropertyBag): File;
                                                                 ~~~~~~~~~~~~~~~

target-tsc-build/shared/index.d.ts:3:82 - error TS2304: Cannot find name 'File'.

3         new (fileBits: BlobPart[], fileName: string, options?: FilePropertyBag): File;
                                                                                   ~~~~

target-tsc-build/shared/index.d.ts:4:20 - error TS2304: Cannot find name 'File'.

4         prototype: File;
                     ~~~~


Found 4 errors.


```

**Comment by OliverJAsh** [comment]
Ah okay, I see. In that case I guess this is a suggestion—that editors should show errors from all projects that the file is part of. Otherwise you don't realise there's an issue until you run `tsc`.

**Comment by OliverJAsh** [comment]
I just ran into this again. @sheetalkamat @RyanCavanaugh @mjbvz Can we re-open this and label it as a suggestion?
