### ISSUE TITLE
Lib.d.ts - DataView interface issue?

### ISSUE THREAD

**Issue by jscriptcoder** [Microsoft/TypeScript#4083]
Hi there,

I upgraded recently to TypeScript 1.5 and I got complains from the compiler because the methods "getInt32", "getFloat32", etc... which take "byteOffset" and "littleEndian" as parameters, have the latest one, "littleEndian", mantadatory. I went throw the documentation about these methods and this parameter, "littleEndian", should be optional.

Is this a mistake?

Thanks,
Fran

**Comment by DanielRosenwasser** [comment]
@zhengbli might know more about this.
