### ISSUE TITLE
Return type not inferred from generic callback

### ISSUE THREAD

**Issue by andreabreu-me** [microsoft/TypeScript#40849]
**TypeScript Version:**
Nightly

**Search Terms:**
infer, parameter, argument, callback, function, generics

**Code**
```typescript
function example<F, ID>(options: {
  foo: F
  setID: (foo: F) => ID
  fn: (id: ID) => void
}) {
  
}

// Example A: setID without full signature
example({
  foo: 'some text',
  setID: (foo) => 2,
  fn: (id) => {
    // `id` is not inferred 
  }
})

//  Example B: setID with full signature
example({
  foo: 'some text',
  setID: (foo: string) => 2,
  fn: (id) => {
    // `id` gets inferred 
  }
})
```

**Expected behavior:** 
The parameter `id` of the function `fn` should be inferred as `string`

**Actual behavior:**
The parameter `id` of the function `fn` is inferred as `unknown`

[Playground link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200930#code/GYVwdgxgLglg9mABAUwB4EMC2AHANsgHgDEAaRASQBEA+ACjm1gQGcAuRAbwChFFg447Ij0TNkUKu1r9BiIgEpEAXmoVKI4GCkwAJuyqKViAG5xdXAL6LuvS1y4B6B4gAGul4hjNEYOFE9gwMgATsHIOohcaFh4yLQ2fALsAOTMcJjIiFBoUMkkImISlFIyhqoATPm8mto6ZZz2vBaW8vZOru6IAObi3jCBIWERURg4+PEaSYip6ZnZqLlVouKSiNJTzFDB-V31lRpaa7r13CLNVkA)

**Comment by RyanCavanaugh** [comment]
This requires multiple "rounds" of inference to get right, but we can only divvy up each round of inference by parameter position, not by object properties.

See also #30134
