### ISSUE TITLE
Errorous type restriction for generics in Template literal types / Mapped type 'as' clauses (#40336)

### ISSUE THREAD

**Issue by markusmauch** [microsoft/TypeScript#40848]
It is not possible to use generic type parameters in Template literal types / mapped type 'as' clauses

**TypeScript Version:**  4.1.0-dev.20200929

**PR:** #40336 

**Code:**
``` 
type Key<T extends string> = `${T}`;

class MyClass
{
    property1 = "";
    property2 = 0;
}

type Keys1<T extends MyClass> = { [P in keyof T as Key<P> ]: any };
                                                  /**  ^----------- error: Type 'P' does not satisfy the constraint 'string'. */

type Keys2 = { [P in keyof MyClass as Key<P> ]: any }; // works fine
```

**Expected behavior:** Type parameter ``T`` in the clause ``[P in keyof T as Key<P>`` should be restricted to type ``string``. 

**Actual behavior:** Compiler error ``Type 'P' does not satisfy the constraint 'string'``

[**Playground Link**](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200929#code/C4TwDgpgBA0hIB4AqUIA9gQHYBMDOUewATgJZYDmAfFALxQAGAJAN5IC+DA3ALABQ-AMYAbAIZ4CAWRABhMRP4t+UFVDDEA9pGKgAjHSgAiQ7z6q1m7aABMBgAyn2-fqEix4eXclQZs+KNJy4ng09CxQANoAClDkUADW8BoAZlAo4u6IUTQAugBcUKJYIFDspuYVlVXVNbVQAPQAVI0qAHoAtJ1d3e2oxJrEBUjg0ADkUaNQOBoQBFgawISiwKR4ySXAABbQghpYRMSi5IujB+QUowB0UI31znyu0HAgeLZhkTFxiSApAbLyBAyzwQ2Sg+UKxVKXAa9SgAHcNMR4gRkuQIPwgA)

**Comment by AlCalzone** [comment]
`P` does not satisfy the constraint:
```ts
class MyClass
{
    property1 = "";
    property2 = 0;
}

class Foo extends MyClass {
    [1] = 5;
}
type F = keyof Foo; // 1 | "property1" | "property2"
```

With your constraint `T extends MyClass`, you could use `Foo` for `T`, so `1` would be one of the types for `P`.

**Comment by RyanCavanaugh** [comment]
This is a correct error; you can use
```ts
type Keys1<T extends MyClass> = { [P in string & keyof T as Key<P> ]: any };
```
to restrict to `string` keys only
