### ISSUE TITLE
Object literal type inference with boolean attributes in function arguments

### ISSUE THREAD

**Issue by troch** [microsoft/TypeScript#40847]
**TypeScript Version:**  4.0.3

**Search Terms:**

Object literal type inference boolean attributes function arguments

**Code**

```ts
type MyObject = Record<string, boolean>

interface MyObjectGetter<T extends MyObject> {
    get: <K extends keyof T>(key: K) => T[K]
}

const wrapObject = <T extends MyObject>(obj: T): MyObjectGetter<T> => {
    return {
        get: (key) => obj[key]
    }
}

const getter = wrapObject({ isActive: true })
```

**Expected behavior:**

`T` is inferred as `{ isActive: boolean }`

**Actual behavior:**

`T` is inferred as `{ isActive: true }`

- It works as expected if my generic constraint is `Record<string, any>`, but doesn't if the value type is an union containing `boolean`.
- Regardless of the constraint, it works as expected if the inferred object literal is defined before being used as a function argument.

**Playground Link:** 

Playground (also contains a workaround)

https://www.typescriptlang.org/play?ts=4.0.2#code/PTBQIAgMQSwJwM4BcIFMAeBDAtgBwDaoBc4wEA7qhXJrhJgHYQD2ARgFaoDGK5AFjC58IXRhD6YAblQDWqAJ4IWAM3oN5EJPNxUkzCKyqZWhUpv2YuXVAiWYICHVxjLBEORphN7WnQFoETGUqbEYGVDgAOlJQXyoAWXkAeQ5uFABeCAAlbmY4ABMAHmQ4LwBzABo1eQA+UFAvJAjlSwTk1J4AcVQkJrhCgBU0dCaGfKVElM4eGogAb1AIJYgynqIIQoBpYdHx9wVmVQGagAoPdc2ASgh02YGAbU2AXVAAX3quZgZkaloptJuGyGGF2E3a0yQpzY7HWA0u60mHSQ3V6EUGs1u80WyzgPQArnAmAtliSVmsIGcFNdMdD7h4XiT3u8YpAAMq5MbDHAEYhmQLYXQSbysZjSYbWXC8Kifb5IGheTR8KiSTD4PG6bQ2GJxCCJADCXxKmC8qHy-x4gJynwKxTl5SqJXKEAAPgZmMxCGJXQw8dhDHA6g0GH0WtZdfIDbL5eEzUiUX1BjtUGMwebIViSaskOstkmU-t5IcIMdKfILtS7o8XsyZT9yDRcJGjSbYxDAYmQcm9vrDXLjTG01COLD4eG0-G0ccbrNiTj8YSM6Slln1qWKywOHSFAzlkz6iAzDkEHj8NmzAB1KgYJwoIZ6AxULzBOC4-L0JRzCAMHDEBx2hhlAA3BAMAIAAgjwMDSOsIoeqgjDAZgqzrD6foRBA7yQAAEqK6FZn0VS1n2LYTnAhG9tGpqkQATOYDioFQuLHqeCDRGYSSbKARFkqicCAvWfxIicn7fgK6wAORKvg+DMOJVSgRBSBQb+crqlUSG-tRAAMGGXPuZAcVxvYbuwgIiT+ElSTJckgeBkHQZocBqfQyEQNpGFGbKIgUf2VE9H0tGZAJjY+S2aYnNCelmAAcoZ3FEZR+SkfxDZNsRA5CeZYkQJJqDSbJ8l2UpDmqag6mue5rxRSyZDnnkMiYHAzB4mMJCQFAeRhqVahvi0+AILo+iwZ6DD1DqHVwNYABC7ojR2IxdkoVp5EUjoAep6g1Bii5LI8IFMB4RYDE8sJVnmezDfBTAAPxunBYinc8bxjZqxaAhN02zVdhSfgp9kqU5VCvDUQA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is the intended behavior: when a a literal value is contextually typed by a literal union of members of only its base type, the literal is treated as a literal instead of its widened form.

**Comment by troch** [comment]
@RyanCavanaugh the description wasn't maybe confusing, but the problem described is only for booleans (i.e. a string value will be typed as `string` rather than its value), and for booleans it actually depends on the type constraint which is introduced by a generic (see playground link).

**Comment by RyanCavanaugh** [comment]
This is consistent behavior as with `string` because `boolean` is an alias for `true | false`. You can see the same behavior with string literals
```ts
type MyObject = Record<string, "ya" | "nah">

interface MyObjectGetter<T extends MyObject> {
    get: <K extends keyof T>(key: K) => T[K]
}

const wrapObject = <T extends MyObject>(obj: T): MyObjectGetter<T> => {
    return {
        get: (key) => obj[key]
    }
}

const getter = wrapObject({ isActive: "ya" })
```

**Comment by troch** [comment]
Thanks for your answer, I appreciate it! So when I have `Record<string, string | boolean>` it is actually `Record<string, string | true | false>`, and one of the types of this union will be used for inferring object property value types? Which then explains why I get a different outcome with `Record<string, any>`?

**Comment by RyanCavanaugh** [comment]
Exactly, yes
