### ISSUE TITLE
support for "nameOf" operator like c# has

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#40846]

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md) (like I mentioned to you last time already). :-) That'll make it much easier for the TypeScript team.

---

Duplicate of #1579.

**Comment by RyanCavanaugh** [comment]
It's a safe bet that someone has proposed every C# feature sometime in the previous 40,000 issues 😉
