### ISSUE TITLE
Incorrect inference in some situations involving mapped tuple types and variadic tuple types

### ISSUE THREAD

**Issue by artemiswkearney** [microsoft/TypeScript#40842]
**TypeScript Version:** 4.1.0-dev.20200929

**Search Terms:** mapped variadic tuple inference, generic

**Code**

```ts
type MappedTuple<T> = {
    [K in keyof T]: [T[K]];
}

function func<T extends [unknown, ...unknown[]]>(arg: MappedTuple<T> | [string, ...(MappedTuple<T> & [[number]])]): T {
    return (arg as Array<string | [any]>).filter(e => typeof e !== 'string').map(e => e[0]) as T;
}

// correct
const n: number = func([[5]])[0];

// incorrectly allowed
// - ['test'] is not assignable to any instantiation of MappedTuple
// - ['test'] is not assignable to [string, ...(MappedTuple<T> & [[number]])]
//     - ['test'] is not assignable to [string, ...[[number]]]
//         - ['test'] is not assignable to [string, [number]]
func(['test']);

// this call is valid, and should be valid
// ...but it has the wrong type! (is: [unknown, number], should be: [number])
const result = func(['test', [5]]);

// should be valid
const n2: number = result[0];
// will be undefined- result only has one element!
const n3: number = result[1];
```

**Expected behavior:**
- `func(['test'])` doesn't compile
- in `const result = func(['test', [5]]);`, `result` has type `[number]`

**Actual behavior:**
- `func(['test'])` compiles and has type `[unknown]`
- in `const result = func(['test', [5]]);`, `result` has type `[unknown, number]`

**Playground Link:** [link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200929#code/C4TwDgpgBAsghmSATAKgVzAGwgHhQPigF4oBvAWACgoaoBtAaSgEsA7KAawhAHsAzKCgC6ALnopGQoQG4qAXypU+aVgGNgzHu2Vq8UCAA9gEVkgDO9FR1Y8A7qwA0UAHSurN+3Sn4AFHABOAOZi8IgQqBjYeIQAPvRmwP5sgU6uzj6hyOhYuARQAGT0dKxoALYARhD+UgCUQjViKGRUtFD+EMBo-ux+QVBwFgCC-v5wIDgJSayBUHF0cKwgQvg1znzMmMb+PtBEhKCQ-PpQAIREJADkk8kXq6UIO8SEEHQADPX9FiiylAqUVAB6AFQVQ8EYQdRUUGsBJQVhiEoVKrEKA6VQ+Oh0ACstTeMkUlCBLDUYPa6kwIH6mEwdnCgOBAFp6BdjAkLkIWBYbMBPmZmIFWHBytgoMAeP1FsSEgsNHANFooEdMuFsth6VAmXQWRA2RzmFyeDyBnyBUKRWL4olkqlXBkEFlIrlCIVMYjKtV6kJ1a1NdrdZy4YbefzBcLoBa6NdpjbnK6yu6pF7CcDWj7mazgOyA9zg6aw6LxZGrdH6G6qlIlCp0VqM+yaj91cAABb6kFwakBgBu7eYSCcCyQUDMTZ4aEwg8qUG7mF76rS5TQPOYPKbA1FTegtn8WhmBwgJygPn1Yjo7jsjjh8fLTmHo-HUEqJ7L1RqUK0sPaZjHPJIaIxfszJxsVqBtkyHEcxwnaBp1nShoVhVgACYESvfwUU-b88R+IlbA2TAQVGYcNTaHVv0VVgKSgVcLC0aAIGwUoTGAE43xhHlWAAZhQpE0JIDDNjoABGGQgA)

**Related Issues:** none found

**Comment by artemiswkearney** [comment]
I know that's a *weird* signature, but it's a simplification of something in my actual codebase - an array of any number of <some type best expressed as a mapped type>, optionally with a string in front.

**Comment by RyanCavanaugh** [comment]
This does seem off, but I might be missing something

**Comment by ahejlsberg** [comment]
The key types here are:

```ts
type T1 = MappedTuple<[unknown]> & [[number]];  // [[unknown]] & [[number]]
type T2 = [string, ...T1];  // [string, ([unknown] & [number])[]]
```

The compiler recognizes `[[unknown]] & [[number]]` as an array-like type, but not as a tuple-like type. Thus, when that type is spread into another tuple type, it is simply treated as an array with type `([unknown] & [number])[]`. From there on out, the effects in the OP example are as expected.

We could possibly broaden our definition of tuple-like to include intersections of tuples (presumably with identical element layouts), but can't say that I think it is worth the added complexity.

**Comment by artemiswkearney** [comment]
That would make sense, except T in the third call isn't inferred as `([unknown] & [number])[]`, but as the more specific `[unknown, number]`. Assignability works out if the type gets transformed like you said, but then where does `[unknown, number]` come from, and why is it being shown to the user?

Separately, a bit of an XY problem going on here - I wanted to spread an intersection of tuple types because I didn't have the option to spread just `MappedTuple<T>` - homomorphic mapped types don't seem to preserve array-like-ness or tuple-like-ness, and there's no such thing as a kind assertion that I'm aware of. Is there a better way to do it?

**Comment by ahejlsberg** [comment]
> Assignability works out if the type gets transformed like you said, but then where does `[unknown, number]` come from...

It comes from inference to the parameter type `MappedTuple<T> | [string, ...(MappedTuple<T> & [[number]])]`. Inference doesn't make a choice to only infer to the second part of the union when the first element of the source is `string`. It infers from the source to *both* choices in the union, but then fails to make an appropriate inference for the first tuple element and thus substitutes `unknown`. You'll need overloads to give a clear preference to the `string` prefix case:

```ts
declare function func2<T extends [unknown, ...unknown[]]>(arg: [string, ...MappedTuple<T>]): T;
declare function func2<T extends [unknown, ...unknown[]]>(arg: MappedTuple<T>): T;

func2([[5]]);  // [number]
func2(['hello', [5]]);  // [number]
```

I'm going to mark this as working as intended as I think inference is doing the best it can here.
