### ISSUE TITLE
Array.prototype.some() doesn't cause type narrowing

### ISSUE THREAD

**Issue by DylanSp** [microsoft/TypeScript#40844]
I'm seeing an issue where calling `.some()` on an array and throwing an error if it's true doesn't seem to cause type narrowing. I looked at several potentially related issues (linked below) and wasn't sure if this is a duplicate; if it is, feel free to close.

**TypeScript Version:**  4.1.0-dev.20200929

**Search Terms:**
- Array
- `.some`
- type guard

**Code**

```ts
interface Left {
    tag: "left";
}

interface Right {
    tag: "right";
}

type Either = Left | Right;

function isLeft(e: Either): e is Left {
    return e.tag === "left";
}

const arr: Array<Either> = [
    {
        tag: "right",
    }
];

if (arr.some(isLeft)) {
    throw new Error();
}

const x = arr[0].tag;
```

**Expected behavior:**
`x` is typed as `"right"`.

**Actual behavior:**
`x` is typed as `"left" | "right"`.

**Playground Link:**
[Link to Playground demonstrating this issue on Nightly](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200929#code/JYOwLgpgTgZghgYwgAgDIRmZBvAUMg5MOAcwC5kAiAGwzEoG5cBfXXUSWRFAJWBIAWWPISKkKlKPyGMWbMAE8ADigCiwMAOjIAvGjrIAPsj6CwTXDACuIBGGAB7EMmABndJgAUECus3QASgoUN31MHHxCKAgwKyhnCAA6YhJdHT0aOllWXAQnVyw4KCgKAEFiuAUAHj8tKAA+XWQAbUiCEVFCFIkpM0oAGjbkVgBdC2AYZE8iqETXBwBbCE83DzAAgIjRTSgHAHdkEAgD1WKHKE8Aphy8kALkAA8mmeaABhHk0gsgA)

**Related Issues:**
- https://github.com/microsoft/TypeScript/issues/16069
- https://github.com/microsoft/TypeScript/issues/9998
- https://github.com/microsoft/TypeScript/issues/11498

**Comment by RyanCavanaugh** [comment]
None of our existing narrowing mechanisms come close to being able to model this pattern - inside the `if`, we can't narrow to anything different, so in the implicit `else` that follows there's nothing to take away. Furthermore, `Array<T | U>` isn't itself a union, so can't undergo narrowing either.

It's not even obvious to me that this is desirable; if you wrote something like this, it would seem wrong to issue an error:
```ts
// All arrs must have at least one foo; add the default
// if it's not present
if (!arr.some(hasFoo)) {
  // Error??
  arr.push(defaultFoo);
}
```

**Comment by DylanSp** [comment]
Understood that the existing narrowing mechanisms don't support it, I assume that's due to how the TS compiler is constructed.

As for whether it's desirable; is there any mechanism to note that a method like `.push()` can widen the (narrowed) type of an array?

**Comment by Validark** [comment]
When you do `if (arr.some(func))` what does TS learn about `arr` from `func`? Hint: how does TS understand the `some` method?

Answer: TS has a method signature (or perhaps multiple) that defines `some` as having particular arguments and a particular return type. If you mouse-over it in a code editor, you can see the definition TS is using to interpret how `some` is used and what it returns. If you don't see `arr is ___` in the return type, it probably doesn't change the type of `arr` when you use it. The point is that TS doesn't have a full understanding of all the implications of using different methods, and it isn't baked in. You can do go-to-definition to see how `some` is defined using the TS type language. You can even change the definition yourself or add overloads.

If you want TS to operate on `arr`, I'd make a function like `assertsAllRight(arr): asserts arr is Array<Right>` and stick your logic in there.
