### ISSUE TITLE
Wrong TSX ternary markup block formatting on save

### ISSUE THREAD

**Issue by humkins** [microsoft/TypeScript#40854]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20200930

**Search Terms**
- format
- tsx
- ternary
- Indent 

---

I like 'format on save' VSCode feature very much. But I'm experiencing a very annoying wrong formatting of **tsx** files (my current version is 1.49.2 (Linux), but I've been observing this for more than month).

Here is an example. Here two lines have extra indents ('single' block)

```tsx
import React from 'react';

const TestComponent = (props: { isList: boolean }) => {
  return (
    <div>
      {props.isList ? (
        <div>liiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiist</div>
      ) : (
          <div>siiiiiiiiiiiiiiiiiiiiiiiingle</div>
        )}
    </div>
  );
};

export default TestComponent;
```

the same code in **jsx** file is formatted correctly

```js
import React from 'react';

const TestComponent = props => {
  return (
    <div>
      {props.isList ? (
        <div>liiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiist</div>
      ) : (
        <div>siiiiiiiiiiiiiiiiiiiiiiiingle</div>
      )}
    </div>
  );
};

export default TestComponent;
```
I tried to switch default vscode formatter to `eslint`, `null`, `prettier` (user/workspace level) - doesn't help. 

When I run `prettier --write src/components/TestComponent.tsx` the tsx file is formatted correctly.

I also checked typescript-specific formatting settings in VS Code, but couldn't find anything related (for the test I've removed `.eslint.js` config file and my project doesn't have `.prettierrc` config)

Please let me know what else I should check/try?

**Comment by mjbvz** [comment]
Just to make it clear: Tte issues is that the two `div` elements in the ternary have different indention levels

**Comment by humkins** [comment]
I've found the reason, it was another default formatter specified in `settings.json`

```json
  "[typescriptreact]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
```

I can't remember how I added it, but once I've removed it the problem has gone.

**Comment by mjbvz** [comment]
Reopening since the built-in formatter does appear to have incorrect formatting
