### ISSUE TITLE
"unknown" inferred as generic parameter of generic parameter

### ISSUE THREAD

**Issue by cnshenj** [microsoft/TypeScript#40855]
**TypeScript Version:**  Nightly

**Search Terms:** generic parameter unknown infer

**Code**

```ts
interface G<T> {
    type: T;
}

class MyClass<T, P extends G<T>> {
    constructor(p: P) {
    }
}

const g: G<string> = { type: "Test" };

const myG = new MyClass(g);
```

**Expected behavior:**
`myG` is of type `MyClass<string, G<string>>`.

**Actual behavior:**
`myG` is of type `MyClass<unknown, G<string>>`.

The reason of `unknown` being inferred is probably because there are multiple possible `T` when `T` is not explicitly specified. For example, `g` is `G<string>`, but it is also `G<any>`. But all those possible `T` must form an inheritance chain so that `T1 extends T2 extends T3 ...`.
Compared to `unknown`, wouldn't `T1` (the lowest in this small type tree) be more intuitive if `T` is not specified? Thus,
`const myG = new MyClass(g)` -> `myG` is of type `MyClass<string, G<string>>`
`const myG2 = new MyClass<any, G<any>>(g)` -> `myG` is of type `MyClass<any, G<any>>`

**Playground Link:** [Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200930#code/JYOwLgpgTgZghgYwgAgOIB4AqA+ZBvAKGWOTAE8AHCALmUwG4CBfAghAGzgGcvkBhZMAC2FdhCERwvDFzBRQAc2wAaNOgBEMAPZaARnCjrchEsgoBXXe2AJSlGsk079h5AF5H2vQfWMWbTh5kAFkyPkCuLFUABWQIAA9IEAATaSxsYyISBC0QWShzBDAtKAAKClpogEp8LOIWfxy8sGQFWhk5RVwPPDsqWnVMCFl1ZCZGJtlkBFoBDxAIAHd+UqrGNlypoTJUd2QF5dDw7i5ShTXWSZbtuf2lkLCI0oQLq+QbgCY9g4fjnnR8opVB15CAlNhnq9NtcwgBmb73I4RDReFzqYEo5w+DKQxhAA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Constraints aren't inference positions; in practice this leads to confusing circularities and worse inference overall. Usually this is an indication of suboptimal type parameter design - we could advise on a more complete sample on what a better way to go would be.

**Comment by cnshenj** [comment]
Not a truly real-world example, but it shows what I tried to achieve: [playground](https://www.typescriptlang.org/play?#code/PTAEBkEsCMCcENYE8BQBjANvAzt0AFWAezQFNcAeAeQD5QBvFUZ0NIgO2wBdYBXNLkVgAKAA69oGSGlBFRpBINgAuUFQCUDJiwC+KPeiy5QAdSEBrbAAs51ADQFQpAB5dS7ACZ5CJctmo0dIwsoKKwkABu8G6gAPpGXD5kuKr4ANwo2sziktKgAOakXKAJVPKKQsLqqlQMoLBFvLDsoFxWkNgAdPE4icTJXXIK0UJpoAYhbJw8-ErCkOyQXJDwGEl+qZrBISxtHd0J68YAvKALSytr-X4ZIXoGIKAAgqKioACMKFxI8qAAstErGVhkpQKcAEQAanBoAAPqBwQBacEZTA4PAAtpHPAuNyebzXSiYoHlEawIJZVgcbh8ASVIYVFT-QHAxkOHJSGQM+CeVTsXgAW2gCi2lJC2F45WE3KU6luun0mSm3FAAsBZlglhsb1O7FIAHdTBZrHJhHrDcTscIoeCHAAGdRy9DU4qlUmg05qtoarVyTpukGjTKPF5vABMKHcgtAAGEEAAzZbsfJaEIAMSEhTslL+pAwXEVKAWblg8fgZGZJcuDAMaOMcfgiYW+WxTlc7i8BEJ-gbTeTFMmLtpcxlQlUvaT+XZEk5quiCkuqkxC9Wop2LAlUtHsCdd0LyuKaATk59Jp1oHNRs1Z7NBtjx+bVonzc6GdgWZrjtRLpKvWfybBVgH2TU9tX9XpWTJNIgA).

**Comment by yume-chan** [comment]
You can infer the property type at use site, for example

```ts

class Workshop<P extends Process<any>> {
    private _lastProcess: P;

    public get lastOperator(): P extends Process<infer T> ? T : never { return this._lastProcess.operator; }

    constructor(initialProcess: P) {
        this._lastProcess = initialProcess;
    }
}

const mathWorkshop = new Workshop(new MathProcess("+", 0));
const lastOperator = mathWorkshop.lastOperator; // MathOperator
```

I think `T` was used to constrain `P`, not the reverse.

**Comment by cnshenj** [comment]
Outside the `Workshop` class, "infer at use site" provides good typing. But inside `Workshop`, I'll have to use `P extends Process<infer T> ? T : never` every time I need the type of `T`? Is there any easy way? Like a type alias for it inside `Workshop`?

**Comment by cnshenj** [comment]
Looks like I can define a "extracting type" like this:
```ts
type ConstraintOf<T> = T extends Process<infer O> ? O : never;
```
Then use it in `Workshop`:
```ts
public get lastOperator(): ConstraintOf<P> { return this._lastProcess!.operator; }
```

**Comment by bfanger** [comment]
Real-world example: svelte merged [PR 5269](https://github.com/sveltejs/svelte/pull/5269/files#diff-5d3935a5eacebd6e00221579261c5435R65 ) :-(
```
export function get_store_value<T, S extends Readable<T>>(store: S): T {
```
Which doesn't behave: [playground](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAysD2AnCAeAKgPigXigbwCgooBnYAQ2AgC4o0CBfAgMwFcA7AY2AEt52oAcwjA4lVGgA0sKBAAeVdgBMSsBMnQYMAChK0YASlpp8RKMmCtEAkgDoy4xgU78ypdTTVJU7VgFsAIwhELFw8d3FaAEYAJgBmKCYXdjcHKhwhETEqXQ8DKAB6Aoj0nlUOAGt2eAB3AR4UqnIlKHhmKGAAC2h5SG4IFt9A4KA)

**Comment by tokland** [comment]
I wonder if this approach is acceptable: `class MyClass<P extends G<any>> `. And write `P["type"]` inside the class whenever the inner type is needed.
