### ISSUE TITLE
Wrong description of document.getElementById parameter

### ISSUE THREAD

**Issue by ulrichstark** [microsoft/TypeScript#40874]
**TypeScript Version:**  4.0.2

**Search Terms:**
document getElementById

**Expected behavior:**
document.getElementById takes one case-sensitive parameter for an element-ID

[Described on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)

**Actual behavior:**
The tooltip of document.getElementById tells me, that the parameter:

1. is case-INsensitive
2. matches element ID & NAME

![image](https://user-images.githubusercontent.com/8657779/94847567-09388e80-0423-11eb-81a1-c8f70f61f31b.png)

**Comment by RyanCavanaugh** [comment]
I can't even figure out where we got that wrong text from :\

**Comment by orta** [comment]
Looks to be a manual override in the dom types generator: https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/30fb5f4387cf1e45d3bedc069fe60f3348802a29/inputfiles/comments.json#L837
