### ISSUE TITLE
Tsserver plugin question 

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/TypeScript#40872]
https://github.com/denoland/vscode_deno/blob/ddfe30c5907324b623be0a9d20f1c1dc011e13fa/typescript-deno-plugin/src/plugin.ts#L491
We proxy the `languageServiceHost.resolveModuleNames` method and replace the import path to let ts import the d.ts file instead of the original js file. but there is a problem that when you open the file for the first time, it does not work until you type something(change the file). I'm wondering how to refresh the cache so that you don't need to change the file in order to make it work?

### here is what i've been tried
![image](https://user-images.githubusercontent.com/15936231/94799321-84934380-0415-11eb-89d9-47678bc29455.png)

### you need to change the file in order to make it work
![KXgQj81unt](https://user-images.githubusercontent.com/15936231/94641119-f171e500-0312-11eb-80ec-c6457d4ce7ab.gif)

### here is the problem screencapture
![lTGP5Llsvj](https://user-images.githubusercontent.com/15936231/94642384-888c6c00-0316-11eb-931a-da0d36562f81.gif)

https://github.com/denoland/vscode_deno/issues/97

**Comment by sheetalkamat** [comment]
Is this still the issue? I see that `enablePluginWithOptions` is called before the project is updated with the load..
https://github.com/microsoft/TypeScript/blob/master/src/server/editorServices.ts#L2142

If that doesnt work, can you create small repro that shows the issue you are seeing so its easier to investigate. Thanks
