### ISSUE TITLE
Consider only showing builders in object literal completions its contextual type has an index signature

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4089]
Since users are no longer allowed to have excess properties in an object literal, it might be appropriate to only show a builder when the contextual type of an object literal has no index signature.

For instance:

```TypeScript
type T = { x: string; y: number; };
function f(param: T) {
}

f({ /*$*/ }); // should only allow 'x' and 'y' and no builder.
```

*However*, this may not be sufficient; in the presence of a type assertion, one actually *does* want to allow a builder, since this is one of the recommended workarounds anyway:

```TypeScript
type T = { x: string; y: number; };
function f(param: T) {
}

f(<T>{ /*$*/ }); // should only allow 'x' and 'y' and no builder.
```

**Comment by danquirk** [comment]
Seems like a good idea

**Comment by DanielRosenwasser** [comment]
Though I recall another edge condition is that we would need to allow a builder for the empty type as well.

**Comment by JsonFreeman** [comment]
I believe you would also want a builder when the contextual type is from a type assertion, because you are allowed to specify extra properties there as well.

You may want to look at isKnownProperty in the checker for inspiration.

**Comment by DanielRosenwasser** [comment]
@JsonFreeman sorry that's what I originally meant, I wrote "completion" instead of "a builder" in the original issue.

**Comment by JsonFreeman** [comment]
Yes, but I meant that maybe the builder would always be shown in a type assertion.

**Comment by DanielRosenwasser** [comment]
Right, that was what I was getting at. And actually there's another problem - consider the following:

```TypeScript
function f(options: FooOptions): void;
function f(options: BarOptions): void;
function f(options: any) { }
```

Provided that `FooOptions` and `BarOptions` are non-empty and distinct, if you supply an empty object literal to `f`, you are potentially going to only get `BarOptions` (since resolution would fail on `FooOptions` and settle on `BarOptions`).

This would be bad experience. We should either supply properties from both `FooOptions` and `BarOptions` or not force completion.

**Comment by JsonFreeman** [comment]
I think that is a different issue. You'd need to detect whether multiple overloads are involved in obtaining the contextual type, and decide on a policy for this case. I think it may be acceptable to pick one and show a builder. Alternatively, you could try to collect them from all the overloads, but I think that would be complicated, and not that useful. I would also try to have completion and signature help agree on which overload the user is likely trying to call.

**Comment by RyanCavanaugh** [comment]
We'd rather error on the side of not restricting the typing here.
