### ISSUE TITLE
Function returning object with discriminated properties includes undefined properties

### ISSUE THREAD

**Issue by NiklasWebnuts** [microsoft/TypeScript#40896]
**TypeScript Version:**  4.0.3 (same behaviour in 4.1.0-dev.20201002)

**Search Terms:**
- typescript discriminated object undefined

**Code**

Both of the following code sample reproduce the bug

```ts
function test(arg: boolean) {
  if (arg) {
    return {
      x: true as const,
      y: 'some-other-property'
    }
  } else {
    return {
      x: false as const
    }
  }
}
```

```ts
function test(arg: boolean) {
  if (arg) {
    return {
      x: true,
      y: 'some-other-property'
    } as const
  } else {
    return {
      x: false
    } as const
  }
}
```

**Expected behavior:**

Any properties that are not included in the returned object should not be included in the type, i.e. the type should be the following.

When `x` is `true`, the object also contains the property `y`, which is of type `string`. However, when `x` is `false`, the object will contain no additional properties. 

```
function test(arg: boolean): {
    x: true;
    y: string;
} | {
    x: false;
}
```

**Actual behavior:**

The type is:

```
function test(arg: boolean): {
    x: true;
    y: string;
} | {
    x: false;
    y?: undefined; // should not be included in the type
}
```

**Playground Link:** 

https://www.typescriptlang.org/play?ts=4.1.0-dev.20201002#code/GYVwdgxgLglg9mABFApgZygCgIYCcDmAXIgEZxwA2K2YAlIgN4BQiiMwiOB9zrruKKCFxJefVgA9iUXCBSJsaRBAQYANC3GIAnsQDkaOAFsUAWjhQAFilymADrjh2bUbXs2sAvps+IUFNHkxfkFhUQ8+KURgbAD5RWVVKAjvLyZPIA

**Related Issues:**

**Comment by MartinJohns** [comment]
Duplicate of #32709. This is intentional as per #19513.

**Comment by NiklasWebnuts** [comment]
Thanks for the fast reply. I'll be closing this issue
