### ISSUE TITLE
Weird behavior of generic method parameter type

### ISSUE THREAD

**Issue by vostrnad** [microsoft/TypeScript#40903]
**TypeScript Version:** both 4.0.2 and 4.1.0-dev.20201002

**Search Terms:**
generic method parameter type never

**Code**

```ts
interface Events {
  ready(): void;
  error(e: Error): void;
}

interface Emitter {
  on<T extends keyof Events>(event: T, listener: Events[T]): this;
  emit<T extends keyof Events>(event: T, ...args: Parameters<Events[T]>): boolean;
}

/**
 * Obtain the parameters of a class method type in a tuple.
 */
type MethodParameters<T, U extends keyof T> = T[U] extends (...args: any) => any ? Parameters<T[U]> : never;

// just to show that MethodParameters works correctly
type MathPowParams = MethodParameters<typeof Math, 'pow'>; // [x: number, y: number]
type ArrayIncludesParams = MethodParameters<Array<string>, 'includes'> // [searchElement: string, fromIndex?: number]

// it all goes wrong from here
type EmitterOnParams = MethodParameters<Emitter, 'on'>; // wrong type: [event: "ready" | "error", listener: (() => void) | ((e: Error) => void)]
type EmitterEmitParams = MethodParameters<Emitter, 'emit'>; // wrong type: never

const onParams: EmitterOnParams = ['ready', (e: Error) => { console.log(e); }]; // no error but there should be
const emitParams: EmitterEmitParams = ['error', new Error()]; // error but there shouldn't be
```

**Expected behavior:**
Type of `EmitterOnParams` should be `[event: "ready", listener: (() => void)] | [event: "error", listener: ((e: Error) => void)]`.
Type of `EmitterEmitParams` should be `[event: "ready"] | [event: "error", e: Error]`.
Declaration of `onParams` should raise an error.
Declaration of `emitParams` should not raise an error.

**Actual behavior:**
Type of `EmitterOnParams` is `[event: "ready" | "error", listener: (() => void) | ((e: Error) => void)]` which is too broad and misses a type error when declaring `onParams`.
Type of `EmitterEmitParams` is `never` and causes a type error when declaring `emitParams`.

**Playground Link:** [Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201002#code/JYOwLgpgTgZghgYwgAgKIDcLgM7IN4BQyyUEcAJgJ4AUAlAFzLoD2w5A3EctFM1NREaoovKAyasOBAL4ECoSLEQpUAW2BhF+LsxAAeACrcAHpBDlcAawiVmMNJhwA+AY7CMDAGmQAbYNjNoITdsAG0DAF1xMAALf05iCHUwQxMzC2RrW3sMLDBsFwg3D28AOnK4KABzbEYABUq4VQhFbD1cnHCIp3EAI2ZmHzIQTlkCAHoAKkmiSeQAeV6wOFBkWJQAB0bm1uQ7ZDhkBB84bFwdmOZyNcoNlFXDsABXDaHS2fGCMFuUAFkWy7kBpQJotaBtLzIACqaSwGSy+wMTmQAF5kAZQlCIrDzLhqOVSpUaow4CBKLRUcjSZRkAB+ZDA0GtQyY7rIRggIrQTgTcbIABWTwCa2YyGwlwA7msYnAwMh-rEroyduDkBK+JZcAg+KQEGAfJQvj95bKYnVmBLlbg0QrAcqwVA2t87vtfqbvAByDYWj1OdjIcZ80LGDlPVS9aDeSih8PQCJGu7IACCIjglAAkiBjk9yBBsFbUfKAUrtg62imQZQ9AEoKAqk5PaBs7nsL6A0HsGQoAgYqghs1wIwa3XvDBeKpM7njLSYxGoPHecgNAcfD5kFVmHm1bwQFVkGPmKpkDFoBAEypkop5iACzbi0DS8y1BpFJ7dL7-YHt7o987BMhQi5QdkAAIlIChKBA5AAB9QJ4PgQO8PwAiwIJkGoOhKQkNgKVgjD-2EUQKRRZEWBw+M-zQS9oGfMBbyLRUHxBFVHXaaioE9JINA-dtv13G47g5LkoDkbUQGFXQrSEdjr3o0IPXAqgPW8AQhBEPhiORPAjl0bBBggUofGYKoBFof1pAiT8+RAUV4KgZBeieOV1lIMVLieHxrgjAgxOFLi6O2WoqJfGjkjkj07OU9CCPUsQsO03z9MM4zTPMyzeLshynOlU83OYDzyBAD05W8oA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
We can't capture the `MethodParameters` of a generic function in a way that preserves its generic-ness (if you try to write down what type `EmitterOnParams` "should" have, this becomes quickly apparent).

**Comment by vostrnad** [comment]
@RyanCavanaugh I am not entirely sure what you mean by preserving generic-ness. Also I did write out what type `EmitterOnParams` should have in **Expected behavior** and it's not apparent to me. But I can reproduce this even without the use of `MethodParameters` if I use a function instead of a method:
```ts
interface Events {
  ready(): void;
  error(e: Error): void;
}

function emit<T extends keyof Events>(event: T, ...args: Parameters<Events[T]>) {
  // implementation
}

type EmitParams = Parameters<typeof emit>; // wrong type: never
```
[Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201002#code/JYOwLgpgTgZghgYwgAgKIDcLgM7IN4BQyyUEcAJgJ4AUAlAFzLoD2w5A3EctFM1NREaoovKAyasOBAL4ECMAK4gEYYMxDcAtsDAAeACrcAHpBDlcAawiVmMNJhwA+AQ7CN9AGmQA6X3CgA5tiMAAr+cJoQkFDYuhhYYNgA2voAuo60+FwA9NnIwJoADgA2EJHgcKrqMnJglIUoqNpgYVARuAC8yK0RUdCxdQ22WjqO7Mi5yADuvCAByIOCyCAQmFAEQA)

**Comment by RyanCavanaugh** [comment]
Your "expected" definition isn't correct; it disallows valid combinations of arguments that would be legal in a direct call.

**Comment by vostrnad** [comment]
I'm sorry, but I read it twice again and I don't see any other valid combination of arguments. Can you give an example?

**Comment by RyanCavanaugh** [comment]
```ts
declare const e: Emitter;
declare const x: "ready" | "error";
e.on(x, () => {{ }})
```

**Comment by RyanCavanaugh** [comment]
Given the way the types are written here the tuple form *may* accept that, but this isn't a guaranteed property of the general tuple expansion you've done there.
