### ISSUE TITLE
Variable arguments generated from JS although not applicable

### ISSUE THREAD

**Issue by m-mohr** [microsoft/TypeScript#40901]
**TypeScript Version:**  4.0.3

**Search Terms:** arguments, var args

**Code**

I'm trying to produce a Typscript Declaration file for my JS project:

src/example.js
```js
class Example {
	/**
	 * Example
	 * 
	 * @param {object} [args={}]
	 */
	constructor(args = {}) {
		/**
		 * @type object
		 */
		this.arguments = args;
	}
}
```

tsconfig.json
```json
{
	"include": ["./src/"],
	"typeAcquisition": {
	  "enable": true
	},
	"compilerOptions": {
		"allowJs": true,
		"declaration": true,
		"emitDeclarationOnly": true,
		"moduleResolution": "node",
		"outFile": "openeo.d.ts",
		"target": "es2017"
	}
}
```

cmd line:
```
npx typescript --project tsconfig.json
```

**Expected behavior:**

```ts
declare module "builder/node" {
    export = Example;
    class Example {
        /**
         * Example
         *
         * @param {object} [args={}]
         */
        constructor(args?: object);
        /**
         * @type {object}
         */
        arguments: object;
    }
}
```

**Actual behavior:**

I get a constructor with two args parameters, which is invalid:
```ts
declare class Example {
    /**
     * Example
     *
     * @param {object} [args={}]
     */
    constructor(args?: object, ...args: any[]);
    /**
     * @type object
     */
    arguments: object;
}
```

Interestingly, if I change `this.arguments` to `this.xyz` in the JS code, it works properly and generates:

```ts
declare class Example {
    /**
     * Example
     *
     * @param {object} [args={}]
     */
    constructor(args?: object);
    /**
     * @type object
     */
    xyz: object;
}
```

It seems it thinks that `this.arguments` is a reference to `arguments`, but it is obviously not.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play?strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&checkJs=false&experimentalDecorators=false&emitDecoratorMetadata=false&jsx=0&module=0&useJavaScript=true#code/MYGwhgzhAECiAeYC2AHEBTaBvAsAKAEgB6AKhPwOhLkVQwqugeoAEUwAnZbAewCMAVumAAXAL7QA2pwDmEALxYxAXWZEKwHgDsIIjgFdRPDgApZMedjEBKbBWJl7jFiICeKTPyGinJdYQIRAAsASwgAOll9JHQtEQtocwBuCjF8MSA)

**Related Issues:** No

**Comment by RyanCavanaugh** [comment]
> It seems it thinks that this.arguments is a reference to arguments, but it is obviously not.

Yep, exactly this

**Comment by m-mohr** [comment]
I just want to add that this also happens in normal methods, not only in constructors. 
Just mentioning it, because 75ed47c explicitly refers to constructors.

Simplified example:
```
	addParametersToProcess(args) {
		for(let key in args) {
			let arg = processArgs[key];
			this.handleArgs(arg.arguments);
		}
	}
```

This time I guess it's `arg.arguments`, which is causing the issue.

Results in:
```
        addParametersToProcess(args: object, ...args: any[]): void;
```
