### ISSUE TITLE
Incorrect generic type error

### ISSUE THREAD

**Issue by Jet132** [microsoft/TypeScript#40900]
**TypeScript Version:**  v4.1.0-dev.20201002

**Code**

This code is a strongly boiled down version of the original, so it makes not much sense in usability.

```ts
type NodeInputEvents = {
  valueSet: (value: number) => void;
};

type Listener = (...args: any[]) => void;

type EventDefinitions<ExistingEvents = {}> = {
  [eventName: string]: Listener;
} & ExistingEvents;

class EventEmitter<Events extends EventDefinitions> {
  emit(...args: Parameters<Events['valueSet']>) {
    console.log('success');
  }
}

class NodeInput<Events extends EventDefinitions<NodeInputEvents>> extends EventEmitter<Events> {
  test(value: number) {
    this.emit(value);
    /*
    The above wrongfully throws following error:

    Argument of type '[number]' is not assignable to parameter of type 'Parameters<Events["valueSet"]>'
    */
  }
}

type TestType = {
  valueSet: (value: number, fo: string) => void;
};

const test = new NodeInput<TestType>();
/*
As expected the above throws following error:

Type 'TestType' does not satisfy the constraint 'EventDefinitions<NodeInputEvents>'.
  Type 'TestType' is not assignable to type 'NodeInputEvents'.
    Types of property 'valueSet' are incompatible.
      Type '(value: number, fo: string) => void' is not assignable to type '(value: number) => void'.
*/
test.test(1);

```

**Expected behavior:**

Only the second error should throw.

**Actual behavior:**

Both errors are thrown. 
The first error is incorrect because the definition of `valueSet` is unchangeable. Thus there should actually be no error.
To showcase that the definition cannot be overwritten, the below tries to add an incorrect type and as expected it throws an error.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20201002#code/C4TwDgpgBAcg9gEwgSQHZgK7AKIDcKrADOUAvFAN4CwAUFFLgIYA2GEAyhMAFxQAUTVhF6oMAWwBGEAE4BKMgD4GcAJYIA3LQC+mmrVCQoAGRVFgBGWX4A6W42kBzIr0aoQAbQC680ktyqNWn1waDwCYAARCAAzFVQVYBU4VCIAHmwAD1NE1AcwwhJyCi0lItp6dwh8QhhGMWEoM2k4h09eEzMLaV0tKAAyKEzslvziXVoAY2ZGIhJR7DEE82l06uIoCAzzVAQ5tajY+MTkoiVqOg3F4D5ba3snXgAFezquGTTRoncAckE2TmA308Cnk53o9AmJzgzAg1mYcAcfG+RAwEwmEFm31kunoWm0QRoUxmJHgSDQmGAq3CJE2212g32MTiCSSKVSpJQ6CwnwUSlpBHp8yuyypBTO5Sg5jMAhYbBE4ikckoEvowAAFqZrBArjKhNiVVAAPQAKgNABU1dBGBI4PgoAB3aTJBzRDDMZggSVqp32kjRaHw+0tDbSJ3SbgE8FQACCjnE4SgcGikpCUG+7lEkhknm+UFMUFQcGAUGJKgcqGtMMlcCgYBe9WWieTBmg32e0leyw+ay+ACI-hwuL3gd8DcbDRK8TQp8FDGaMcAzamyhcBwDeLq5QWFTIADRQf28JotHx+AI9caEk7FqXF8ioCD22CITkU1LzsxLyAKPj6mgm2hoxpDJIAmcwEC9K0bTtdUfT9AM4CDXIQzDCM9BoL9Ww-RcQlzBA4AxAsi0aRhEiIaJPXVaBIRSYAOziYtvlGA5mWONkOXJbkewUb5rAlTC02wzDc3zQti1LctK2gYAaxbNMOK5HAe1480QhIJNaydSBpFANM1y4XN7GgOJITEOtEgkGE+IuKMBO+TcGkzRV90PRo6JPRRlDUESSDEktZjLCtLOk2TU3sgd5SzJVfC8hAVJocd9AXaxbz4ABGP8gA

**Comment by andrewbranch** [comment]
More simplified example: https://www.typescriptlang.org/play?ts=4.1.0-dev.20201002#code/C4TwDgpgBAsghiARhAEnAzgMQPbagXigG8oAzXAfgC4o4A7EKAXwG4BYAKE9Eih2wAKcAE5wAtugA8AFSgQAHsAh0AJulgJkaLLgB8BKENFiIS4VOkBtAOTls1gLq72XDiogBjADYjo3jOoAQhgQMnKKymoaSKgY-PpEnFByYgCWwAAUAHQ5IgDm6DT8RuIWugCUNABu2KkqLkycnP7o6gDKAK6ILRbhSqrqJHY0GfI0dB1iyMLlBPo1dcz6Cv1Rweih0glJUErombOJHMnJwAAWqehZEGmZAMzlLsmNHC9AA

**Comment by andrewbranch** [comment]
[Here’s](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201002#code/C4TwDgpgBAcg9gEwgSQHZgK7AKIDcKrADOUAvFAN4CwAUFFLgIYA2GEAyhMAFxQAUTVhF6oMAWwBGEAE4BKMgD4GcAJYIA3LQC+mmrVCQoAGRVFgBGWX4A6W42kBzIr0aoQAbQC680ktyqNWn1waDwCYAARCAAzFVQVYBU4VCIAHmwAD1NE1AcwwhJyCi0lItp6dwh8QhhGMWEoM2k4h09eEzMLaV0tKAAyKEzslvziXVoAY2ZGIhJR7DEE82l06uIoCAzzVAQ5tajY+MTkoiVqOg3F4D5ba3snXgAFezquGTTRoncAckE2TmA308Cnk53o9AmJzgzAg1mYcAcfG+RAwEwmEFm31kunoWm0QRoUxmJHgSDQmGAq3CJE2212g32MTiCSSKVSpJQ6CwnwUSlpBHp8yuyypBTO5Sg5jMAhYbBE4ikckoEvowAAFqZrBArjKhNiVVAAPQAKgNABU1dBGBI4PgoAB3aTJBzRDDMZggSVqp32kjRaHw+0tDbSJ3SbgE8FQACCjnE4SgcGikpCUG+7lEkhknm+UFMUFQcGAUGJKgcqGtMMlcCgYBe9WWieTBmg32e0leyw+ay+ACI-hwuL3gd8DcbDRK8TQp8FDGaMcAzamyhcBwCRFUZD1xoSTsWpcXyKgIPbYIhORTUvOzEvIAo+PqaCbaNGaRlIBNzAgvVabXb1T6foBnAQa5CGYYRnoNC3q216LiEuYIHAGIFkWjSMIkRDRJ66rQJCKTAB2cTFt8owHMyxxshy5Lcj2CjfNYEowWmcEwbm+aFsWpblpW0DADWLZptRXI4D2DHmiEJBJrWTqQNIoBpmuXC5vY0BxJCYh1okEgwoxFxRsx3y6nKBYKjIAA0UD+rwTQtD4fgBOxJCcSWsxlhWOl8QJqZGQO8pZkqvjKGo4k0OO+gLtYB58AAjI+QA) an example showing why, from an assignability perspective, the error is legitimate. This is a valid instantiation of `NodeInput`, but `Parameters<Events['valueSet']>` evaluates to `never`. It is true that `[number]` is not assignable to `never`, so the error is correct.

**Comment by Jet132** [comment]
Ah ok, I see why it throws an error. Thanks for your time 👍
