### ISSUE TITLE
cannot declare void as possible return type for function

### ISSUE THREAD

**Issue by r3wt** [microsoft/TypeScript#40902]
The intended behavior is: user can supply a callback. the callback receives an `input`. if the callback detects an error, it can return `Error|string|Promise<Error|string>`. else it should return nothing (void), or undefined or null (up to the user, who cares, it doesn't matter). this is valid javascript code, as i ported the library from js to ts last week. now i am updating all my tests and example, and i am seeing this problem. user should not be forced to annotate their callback function in order for the code to work!

**TypeScript Version:**  4.0.2

**Search Terms:**
Typescript explicit void return type, typescript allow optional void in function, typescript return void|Type function, etc etc etc

**Code**

```ts
type ErrorLikeObject = Error|{ message: string; };
type FnReturnTypes = void | never | undefined | string | ErrorLikeObject;
type FnType = (val: any) => void | FnReturnTypes | Promise<FnReturnTypes>;

const functions:FnType[] = [];
const addFunction = (fn:FnType) => {
  functions.push(fn);
}

// addFunction's `fn` parameter should not need to explicitly specify void as valid return type! plz help
// user should not have to annote their return type on the function! my type definition `FnType` should satisfy the allowed behaviors of the argument!
addFunction((value:string) => {
  if (value.length < 5) {
    return 'Name must be at least 5 characters'
  }
});// gives error: Not all code paths return a value. 
```

**Expected behavior:**
The code doesn't throw this stupid error

**Actual behavior:**
The code throws this stupid error

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBAogTnA9nAMgSwNYQPICMBWEAxsFALywLIA+A3lALYQDOzAhgOYQBcUzwcNADsOAbigBfUQChQkKADEhAJQjAArnCEAVcC3JQAbojQATKNShCIhiHAtR1Q0xABmwiOcv9BIh-CRUTBwCYmAZOWglXXkKAApDNgAbXjYhEABKcgA+IxMvRRU1TR09ZgcABSQGNGYIAB4lVQ0tGJZsmWkiRCF+KFcnEjQe5m5ovQBtAF0DaZlu3tI2U1MFQeBhoQM41yEx0sgsslzaaSh+9c3mADowdWYACx2hDJkJaWkAek+oZdXLnoAcnKAANdiCoGA2HA2ExgHY+A9EOokuYhIhSNZPFBgIgoBAAB5gJJoIhoYBJEB8SBk1xU4xmX7lRIk8xwYpaHF6ACEkKSAC8oA8IEkwNI-mshEMenEEsl1DwfMIOEcTmcoGhXFA5UkFdckhARMAHlB6lAAKxZU7nc7slpbQEAOVh0AY91IuGgbFIBrYfXNUCID2hbBIdmYgPV7wkryAA
**Related Issues:**

**Comment by MartinJohns** [comment]
`void` means "the result won't be observed / used", it does NOT mean "returns nothing". In this case you want to use `undefined` instead of `void`.

Also using `never` as part of a union type doesn't make sense, as the `never` type represents an empty union.

**Comment by r3wt** [comment]
> void means "the result won't be observed / used", it does NOT mean "returns nothing". In this case you want to use undefined instead of void.

Still gives the same warning, forcing user to explicitly return undefined! this is not acceptable.

> Using void as the return type for your function means it's impossible to distinguish the results returned from FnType:
Why are functions returning non-void assignable to function returning void?

How does that apply to my problem. I want user to not be forced to return anything from function. keep in mind, the code worked fine in javascript before i ported it to ts

>Also using never as part of a union type doesn't make sense, as the never type represents an empty union.
i know, i was trying anything i could to try and resolve the error

**Comment by r3wt** [comment]
assertion: Typescript shouldn't throw error for valid javascript

**Comment by MartinJohns** [comment]
> Still gives the same warning, forcing user to explicitly return undefined! this is not acceptable.

This is a compiler setting: `noImplicitAny`. Turn it off to achive the behavior you want.

**Comment by RyanCavanaugh** [comment]
> assertion: Typescript shouldn't throw error for valid javascript

https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean

Anyway as noted, this is an implicit return, and there's a compiler setting that controls whether or not implicit returns are a warning. Your project is miconfigured if this is the behavior you want.

**Comment by r3wt** [comment]
> This is a compiler setting: noImplicitReturns. Turn it off to achive the behavior you want.
that doesn't help me in userland. user will still see the problem.

**Comment by RyanCavanaugh** [comment]
If your users want to be warned about forgetting to explicitly return from a function, that is their choice.

**Comment by MartinJohns** [comment]
In the userland it's the users choice to enable implicit return values. 🤷

**Comment by r3wt** [comment]
If this is expected behavior, then your definition of expected behavior is asinine and also completely arbitrary. its perfectly legal for a function to return something or not return at all in javascript, right? so why does typescript complain about the convention? the callback satisfies the contract of the type, so why does typescript still complain? help me understand why this is "expected behavior" and "working as intended".

**Comment by RyanCavanaugh** [comment]
This is longstanding well-documented behavior and we've already told you how to configure your project for the desired behavior. It doesn't seem like this is headed toward a productive conversation given the attitude displayed here.
