### ISSUE TITLE
Problem deriving a property from another one with strictNullChecks=false

### ISSUE THREAD

**Issue by clovis1122** [microsoft/TypeScript#40914]
**TypeScript Version:**  4.0.3

**Search Terms: property depends on another, deriving a property, strictNullChecks false**

**Expected behavior:** Code successfully compiles and works.

**Actual behavior:** Code fails to compile. Typescript does not narrow down the type. This only seems to happen with Boolean literals -- it works for numeric and strings literals.

**Related Issues: https://stackoverflow.com/questions/56949513/typescript-type-of-a-property-dependent-on-another-property-within-the-same-obj**

**Code**
```ts
type RockOrScissor =
    | { hasRock: true; value: '123' }
    | { hasRock: false; error: 'scissor' };

const getRock = (): RockOrScissor => ({ hasRock: true, value: '123' });

const p = getRock();

if (p.hasRock) {
    console.log(p.value);
} else {
    console.log(p.error.length);
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```
</details>

**Playground Link (for booleans, which does not compile)** [Provided](https://www.typescriptlang.org/play?strictNullChecks=false&ssl=5&ssc=64&pln=5&pc=67#code/C4TwDgpgBASg9gYwNYHkBOBlBBLAzruNKAXgCgoKoAfKAbygAsBDXeZALimDQFcIBuKADcmAGz6cA5AEYATAGZJUAL7lKNes1aIknAGZjcAqBDRpCU3DnyEly-qVII4AO1zAoAcwjA2SElAAFACUnH7oWHgERMQAfEGaLH6c3HwANMJiElAyCnbBDk6u7lBgAd6+OiGF2HpBYAB0Wn7BdGoUzm5wohANonCegY0i4hAFpMomokZtlFCdBD19A0MNpuZofRAunsAM46pAA)
      

**Playground Link (for numeric literals, which compiles but gives a runtime error):** [Provided](https://www.typescriptlang.org/play?strictNullChecks=false#code/C4TwDgpgBASg9gYwNYHkBOBlBBLAzruNKAXgCgoKoAfKAbygAsBDXeZALigEYBuKANyYAbAK4ROXAEwBmKAF9ylGvWatESTpL4Q0aQpwDkuHPkIH5PUqQRwAdrmBQA5hGBskJKAAoAlJ3foWHgERMQAfN4qLO6ctiJCQgA0AsJiEjLyPpbWdg5QYJ4ubuq+2dgAZt5gAHSq7iTExNw+dIoUNvZwQhDVQnBOXjWCohBZpHJQEEK40LRtUB0E3b39g9U6emi9ELZOwAxjCkA)

**Comment by RyanCavanaugh** [comment]
`tsc` defaults to `strictNullChecks` off, and `if (rock.hasRock)` isn't a safe way to check for a property when strict null checks is off (since it might be `undefined` or `null`). `tsc -- strict example.ts` would be the same behavior as the Playground (which defaults to strict on)

**Comment by clovis1122** [comment]
@RyanCavanaugh thanks, that makes sense. I'll close the issue and analyze it.

**Comment by clovis1122** [comment]
@RyanCavanaugh why this one works? Shouldn't it be the same case?

<img width="645" alt="image" src="https://user-images.githubusercontent.com/22270042/94973347-6f7fe880-04d9-11eb-8caa-97a373d29004.png">

**Comment by clovis1122** [comment]
I'm reopening this since the behavior looks inconsistent to me. The type guard works with both numeric and string literals. Why doesn't it works with boolean literals?

I would expect either of the following behaviors:
A) Typescript refuses to narrow down the type of any literal value, not just booleans.
B) Since `strictNullChecks` is `false`, typescript ignores implicit null/undefined and correctly narrows down the value when using Boolean literals, just like it already does for other literals.

**Comment by clovis1122** [comment]
Doesn't looks like a question for me?
