### ISSUE TITLE
amd-module tag has no effect on generated d.ts file

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#4091]
When using `/// <amd-module name="foo/bar/baz" />` to name an AMD module, the generated d.ts file does not declare an ambient declaration; it remains an anonymous module. This ties into the ongoing discussion about how to best bundle external libraries.

Edit: removed useless hyperbole

**Comment by mhegazy** [comment]
that is because the compiler never emits modules as ambient external module declarations. i am working on a change to make this happen though. so i will take on this one,

**Comment by sccolbert** [comment]
In the meantime, do you have any pointers to generating single `d.ts` file from the generated output? 

It seems like the generated anonymous modules cannot be bundled without substantial manual effort. One cannot simply wrap the generated output in a `declare module 'foo'` clause, because then relative imports don't work. If the source is updated to use absolute imports, the output is still incorrect because the generated code has `export declare class ...` statements which result in these errors: ` error TS1038: A 'declare' modifier cannot be used in an already ambient context.`

So, it seems that there is not a reasonable way to deal with large libraries of external modules currently. Distributing unbundled is frought with its own pains because one cannot set the import path of the compiler.

**Comment by mhegazy** [comment]
Have you tried https://github.com/SitePen/dts-generator?

I have a working version that i need to clean up and send a PR for. hopefully before end of next week.

**Comment by sccolbert** [comment]
Thanks. This works for now. Looking forward to the official support!

**Comment by mhegazy** [comment]
the name from `amd-module` tags should now be reflected in the output with `--out` and `--module` combination.
