### ISSUE TITLE
Parser incorrectly rejects exponentiation whose LHS is an unparenthesized `await`, as in `await a ** 2`

### ISSUE THREAD

**Issue by bakkot** [microsoft/TypeScript#40916]
**TypeScript Version:**  4.1.0-insiders.20201002 [nightly]

**Search Terms:** exponentiation exponential async await operator parser

**Code**

```ts
async function f() {
    await 1 ** 1;
}
```

**Expected behavior:**

No error.

**Actual behavior:**

Error: "An unary expression with the 'await' operator is not allowed in the left-hand side of an exponentiation expression. Consider enclosing the expression in parentheses. (17006)"

**Playground Link:** [Here](https://www.typescriptlang.org/play?ts=4.1.0-insiders.20201002#code/IYZwngdgxgBAZgV2gFwJYHsLwBQEoYDeAUDKTMAO7CrIwCMMAVI-QNxEC+QA)

**Related Issues:** Couldn't find any.

Incidentally, the grammar in the error message is also wrong (or at least unusual) - it's normally "a" unary expression, not "an", in my experience, since most people pronounce it "yoon-ary" rather than "oon-ary".

**Comment by DanielRosenwasser** [comment]
Pretty sure I've heard "an unary" might be a UK-ism, but agree.

**Comment by DanielRosenwasser** [comment]
I'm a little confused - if I look at the spec, I can't seem to find a derivation for *ExponentiationExpression* to `await` `1` `**` `1`.

*ExponentiationExpression* seems to need an *UpdateExpression* on the left, which *does not* include an *AwaitExpression*, whereas *UnaryExpression* does.

**Comment by bakkot** [comment]
Huh. No, I think you're right, and it's just that every other parser and also all the major browsers got this wrong.

**Comment by DanielRosenwasser** [comment]
I don't know how exactly to say this, but I'm just very shocked that every other parser and major browser vendor got this wrong. Would you be interested in bringing this up at the next TC39 meeting with me?

**Comment by bakkot** [comment]
Sure, though I doubt there's much of an action item here except adding a test262 test (though, if engines are reluctant to risk potential web breakage, we might instead need to figure out how to spec what is apparently web reality).

**Comment by DanielRosenwasser** [comment]
Yeah, it seems like the change in the "web reality" case is just moving `AwaitExpression` around, though it's not my preference to treat `await` differently than `void` in this case.

**Comment by bakkot** [comment]
Let's move the discussion to https://github.com/tc39/ecma262/issues/2197, since I beileve you are correct that this isn't actually a TypeScript bug.

**Comment by Jack-Works** [comment]
Oh I pronounce it as "an U-na-ray"
