### ISSUE TITLE
Missing namespace when importing Types with experimentalDecorators

### ISSUE THREAD

**Issue by mhevery** [Microsoft/TypeScript#4092]
SOURCE: https://github.com/mhevery/github_issues/tree/ts_issue

When compiling [`mention_component.ts`](https://github.com/mhevery/github_issues/blob/ts_issue/issue_component.ts) produces incorrect [`mention_component.js`](https://github.com/mhevery/github_issues/blob/ts_issue/build/mentions_component.js)

The issue is that it generates:
```
__metadata('design:paramtypes', [Mentions, CoreTeam])
```

But it should generate:
```
__metadata('design:paramtypes', [github_1.Mentions, core_team_1.CoreTeam]
```

Compiler: tsc v1.5.3 on npm
Repro: run `./watch.sh`

**Comment by sheetalkamat** [comment]
@mhevery I tried running this on latest typescript and it doesn't repro there. Can you please give it a try by picking up latest TypeScript from npm using typescript@next

Thanks

**Comment by IgorMinar** [comment]
This is fixed in 1.7.0-dev.20150827 but not in 1.5.3. Any chance the fix could get cherry-picked into 1.5.x branch?

**Comment by mhegazy** [comment]
@IgorMinar the code in 1.5 was significantly different, so a different fix will need to be applied. this is part of the 1.6 release. do you have a hard dependency on 1.5.3? or can you move to 1.6?

**Comment by IgorMinar** [comment]
we are not locked to 1.5.3 but that's the latest stable version available
on npm.

is 1.6 release due soon?

**Comment by mhegazy** [comment]
> is 1.6 release due soon?

yes.  :)
