### ISSUE TITLE
lib.dom.d.ts - MediaQueryList.matches should not be readonly

### ISSUE THREAD

**Issue by timrobinson33** [microsoft/TypeScript#40925]
The documentation in MDN for MediaQueryList here: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/matches
describes the matches property as "read only", and in lib.dom.d.ts it's declared with `readonly`.

However, these are different things. As far as I understand it, the MDN definition of read-only means "not writable", whereas in typescript, readonly means immutable.

For instance, if you create a media query in the browser console (e.g. `var x = window.matchMedia("(min-width: 1000px)")`, you will see the `matches` property change value as you resize the window, but if you do `"use strict"; x.matches=false` you will get an exception.

I have raised an issue here https://github.com/mdn/sprints/issues/3744 suggesting that it's confusing for MDN to use the term "read-only" for non-writable mutable properties.

However, the issue here is that it's not currently possible to implement MediaQueryList in TypeScript without doing a cast. It seems to me that the best solution is to remove the readonly specifier from that property.

**Comment by MartinJohns** [comment]
> whereas in typescript, readonly means immutable.

This is not true. `readonly` in TypeScript means "not writable via this interface". There is no way to represent immutability in TypeScripts type-system.

**Comment by timrobinson33** [comment]
OK so maybe it's my understanding of typescript that is inadequate, but I can't find any documentation or examples whereby a readonly member can change its value over time.

How could I implement MediaQueryList and have the matches property be readonly but mutable?

**Comment by MartinJohns** [comment]
Interfaces with mutable properties are implicitly compatible with interfaces having matching read-only properties, and vice versa.

**Comment by timrobinson33** [comment]
Thanks - that makes a lot of sense, but it's the one thing I didn't try! I'll close the ticket.
