### ISSUE TITLE
Using this-type with intersection type makes it possible to simulate HKT 

### ISSUE THREAD

**Issue by ENvironmentSet** [microsoft/TypeScript#40928]
**TypeScript Version:** Lastly tested in v4.1.0-dev20201003, but this has been existing at least since v3.8

**Search Terms:** this-type, this type, intersection, HKT, higher kinded type

**Code**

```ts
export interface HKT {
  param: unknown;
  result: unknown;
}

interface NotHKT extends HKT {
  result: this['param'] extends true ? false : true;
}

interface FstHKT extends HKT {
  result: this['param'] extends [infer A, infer _] ? A : never;
}

interface ArrayHKT extends HKT {
  result: Array<this['param']>;
}

export type Apply<f extends HKT, x>
  = (f & { param: x })['result'];

type Test1 = Apply<NotHKT, true> // be deducedd to `false`
type Test2 = Apply<FstHKT, [string, boolean]> // be deduced to `string`
type Test3 = Apply<ArrayHKT, number> // be deduced to `number[]`
```

**Expected behavior:** I expected that reduction of `this` type doesn't depends on type that is intersected with.

**Actual behavior:** reduction of `this` type depends on type that is intersected with.

The actual behavior makes sense to me(at least). It's not hard to accept its behavior. However, It looks like unintended behavior or bug (just like recursive conditional type before) so that I can't certain it's okay to use this. **Is this idea safe to use?**

**[Playground Link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201003#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgCQGkAVOAbwCg44xMpMBbALjgFckBrJCAdyQG4qcKMADOrADYwW7LrwEUAvhQrJUGHHgByEGEVKhUSACaiCJckJHipLGAAsEogNoByWvQauAunEPATMxgoVjwAfjgsCVE8OxDgQWVVFDQsXDgAMVE9C39A81JKamtJaTgHJzcPRh8-ECNTOGdkdDQ4AEEAGkQkVqg4AH1fCPa4FiRgADc0RJU1VM0OqHoAT306hrN1ouExUpZ25cwVgB4Kl3c6Gu8APlmKUEhYcpWwPHawMAlT9A2Axv03RANyEAF44AAKX4AMnINCuzDgIDgigAlG4SlIfIIKDBXnhiGIYABGODgj5fU46HLEbrBUI3OAAeiZcAARnhjMBjKxcMZjOUIHAAAZRGLC3H4uCE7IAJjJHU+3xOWRp3Wc2SgyAA5t02RAIBJgJgkLdmayOXAuTy+YKRZqdRK8W9pUSAMwKinKw6rQFwJCsBgcqCMlnsznc3ncu3CgNBtDObzCoA)**

**Comment by jcalz** [comment]
Related to #1213

**Comment by andrewbranch** [comment]
[Simpler version of the question:](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4ChnLgLmQGcwpQBzAbh2XIjFULAAtgiBtAcjk4F1qAvliwB6EcgDKzAPYBXADYATZABVkAIxScQEAG7ROyaVGScSZEOU4B+LGACeABxRqAvMgAU6AGSY8hEFkAW00TAQBKLjoGPmogA)

```ts
interface A {
  a: string;
  getA: this['a'];
}

// Should T be 'never' or 'string'?
type T = (A & { a: number })['getA'];
```

> Is this idea safe to use?

I don’t really know the answer to this question. I can’t find an instance of this in our test suite, so perhaps in some trivial way, the answer is no. But I would not be surprised if this behavior was intentional. It looks like it could be important for some mixin patterns, for example.

**Comment by andrewbranch** [comment]
@DanielRosenwasser agrees that this is probably intentional 😄

**Comment by ENvironmentSet** [comment]
Thx for the work :)

**Comment by zachsents** [comment]
This is insanely cool
