### ISSUE TITLE
Split up the type checker file into multiple files

### ISSUE THREAD

**Issue by RDambrosio016** [microsoft/TypeScript#40937]
## Search Terms

Split, TypeChecker, Checker

## Suggestion

I would love to see the [type checker file](https://github.com/microsoft/TypeScript/blob/master/src/compiler/checker.ts) be split up into multiple files, as it is it is unreadable, and understanding what is going on is nearly impossible.

## Use Cases

The typescript type checker is a very interesting tool, however, it is nearly unreadable, because:
- it is 40281 lines in total
- it cannot be looked at in github
- it lags vsc (for me at least)

I would love to learn more about it, and eventually make a custom implementation for a tool i am making, but the fact that the checker is a single file makes it nearly impossible to understand.

## Examples

Type checking consists of distinct goals and steps, and it is possible to split up those steps, for example, splitting up checking functions, loops, binary expressions, unary expressions, generics, scope analysis, etc.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

This is purely a formatting feature, it has zero impact on the end user.

## Relevant issues
#17861 seems to be somewhat relevant and it mentions this:
> For better typescript future I think checker.ts should be separated into multiple files/classes, and this is the first step. This code is not merge ready. Of course we should think about methods to be provided to public api, and may be unsafe access for people who do really complicated transformations.

but it is not further discussed

**Comment by andrewbranch** [comment]
The main reason we haven't done this is performance, as shown in #17861. I felt this way when I first joined the team, but my view has softened as I’ve learned to approach the checker differently. I still think certain parts, like the node builder, would be better suited in their own module, but I would probably split up the checking of different kinds of syntactic constructs, as suggested. Performance in VS Code isn’t a huge problem for me, but I run a pretty powerful computer, and I would _love_ if we could view the file on GitHub. But of course, we cannot reduce the amount of code or its conceptual complexity by splitting it into different files, so I don’t believe such a change would make it significantly easier to understand. In my opinion, the only way to begin to understand the checker is by debugging. While fairly high-level and not specific to the checker, I wrote a [blog post](https://blog.andrewbran.ch/debugging-the-type-script-codebase/) on some debugging tips specific to this codebase. I would also suggest @orta’s [typescript-notes](https://github.com/orta/typescript-notes) and @sandersn’s [manual](https://sandersn.github.io/manual/) as good learning resources that you won’t find in official documentation. Aside from that, you can look at the [good first issue](https://github.com/microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and [help wanted](https://github.com/microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) labels and learn by contributing to the compiler. Depending on your level of familiarity with TypeScript and compilers in general, you may find some that can ease you into understanding the checker bit by bit. For housekeeping purposes, I’m going to call this a duplicate of #17861.

**Comment by RDambrosio016** [comment]
I see, my main issue is just finding things in the type checker, like if i wanted to find the entry point or where statements are checked its pretty hard. I would love a dev guide which explains some of the concepts around it and how it works. I have some typechecking experience but tsc seems to have some very specific things.

**Comment by andrewbranch** [comment]
The syntactic entrypoints typically have predictable names in the format of `check{SyntaxKind}`. `checkSourceElementWorker` is the one that fans out into all those syntax-specific ones. In VS Code I frequently use ⌘⇧O (go to symbol) to find those.

**Comment by RDambrosio016** [comment]
Yeah it works for expressions but `checkStmt` and `checkStatement` do not seem to work, which is why i am confused 😄

**Comment by andrewbranch** [comment]
🤔 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/3277153/95257971-eff46100-07d9-11eb-80e6-66242ca0e317.png">

**Comment by RDambrosio016** [comment]
Haha i was checking for checkStmt alone

**Comment by RDambrosio016** [comment]
Ill go ahead and close this as it seems this wont happen soon because of perf reasons 👍
