### ISSUE TITLE
Intersection types are not indexable by keys of their members

### ISSUE THREAD

**Issue by nileshp87** [microsoft/TypeScript#40938]
**TypeScript Version:**  4.1.0-dev.20201004 and 4.0.2

**Search Terms: union keyof**

**Code**

```ts
interface A {
  a: number;
  b: number;
}

interface C {
  a: string;
  c: number;
}

const broken = <T extends keyof A, V = A & C, R = V[T]>(id: T, input: R) => {};
```

**Expected behavior:**
I would expect that keyof on an intersection type would be a superset of the subtypes, not be type incompatible.

**Actual behavior:**
The union type is not indexable by a subtype's key.

**Playground Link:** 
[Playground link containing code above](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201004#code/JYOwLgpgTgZghgYwgAgILIN4ChnLgLmRAFcBbAI2gG4dlzCSLqsBfLLUSWRFAYU1oFkAZzBRQAcxq4EDMpSg02WBAHsQoulFUBrCCGQBeZAB4AKsggAPSCAAmw5HoCeqmGgA0yAGpG0yADJkXi8AJT9vAG0zAF0APgAKYDtCMy9QAAdiMEJQgEojOIFWKiA)

**Related Issues:** 
None found.

**Comment by nileshp87** [comment]
Finally managed a workaround, for anyone that finds this in the future: 
```ts
interface A {
  a: number;
}

interface C {
  a: string;
}

type broken<I> = <T extends keyof I, V extends (I & C), R = V[T]>(id: T, input: R) => {};
```

The change from above is that V in the generic is switched from "V = A & C" to "V extends (A & C) = A & C".  This somehow enables the compiler to be happy about the typing. The compiler still does correct inferencing on the generics, so everything works exactly as needed for the API I'm designing; however, I'm leaving this issue open as I don't believe the extends should be necessary.

**Comment by MartinJohns** [comment]
`A & B` is not a union type, it's an intersection type.

https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#intersection-types

> The change from above is that V in the generic is switched from "V = A & C" to "V extends (A & C) = A & C".

`V = C` and `V extends C` mean **fundamentally different things**. The first is a **unconstrainted** type parameter with a **default type** (meaning `V` doesn't has to extend anything, and if not provided it has the type `C`), while the latter has a type **constrained** type parameter that must extend a specific type and has **no** default type (`V`must extend `C` and must be provided). They can be combined to `V extends C = C`.

https://www.typescriptlang.org/docs/handbook/generics.html#generic-constraints  
*default generic type arguments don't seem to be mentioned in the handbook.*

**Comment by nileshp87** [comment]
Sure, my mistake (I always flip them because set theory union vs intersection is inversed). Anyways, the bug is still valid. All keys of A are a subset of keys of A & C. 

I understand about generic constraints... what I'm not sure of is why that solution works in my more complex (actual) example where I'm using this to dynamically generate types.

**Comment by Validark** [comment]
TypeScript uses the proper definition of "union" and "intersection" according to Set theory.
```ts
type SetA = 1 | 2 | 3;
type SetB = 2 | 3 | 4;

type Union = SetA | SetB; // 1 | 2 | 3 | 4
type Intersection = SetA & SetB; // 2 | 3
```
The difference is that when you are talking about objects; the union of two object types results in an object type where the only keys we are certain will be present are an intersection of the keys of the operand types. An object of the resulting type *could* have its keys be the union of the two operand types, but we don't know that for certain.
Conversely, intersecting two object types (saying an object must be BOTH types simultaneously) results in an object type which has keys which are a union of the keys from the two operand types.

I see how that can be confusing at first but it makes sense. Think of a union as something being A **or** B and an intersection as something being A **and** B.
