### ISSUE TITLE
Better Error Message for a New Ecmascript Property With a Name Similar to an Existing Property

### ISSUE THREAD

**Issue by Vboivin** [microsoft/TypeScript#40933]
## Search Terms
- Error Messages
- Math
- ObjectConstructor
- EcmaScript

## Suggestion
- If a new EcmaScript property name is similar to an existing property, give the option to the user to either change the EcmaScript target or use the existing property with a similar name.
- `Property '{0}' does not exist on type '{1}'. Do you need to change your target library? Try changing the lib compiler option to '{2}' or later. If you did not mean '{0}', did you mean '{3}'?`
- The error message might be too verbose and heavy to the user to be useful here. We could also consider prioritizing one error message over the other.

## Use Cases
- Let the user know that this property is indeed valid if he targets a newer version of EcmaScript.
- Let the user know a property with a similar name is available if he is targeting the correct version of EcmaScript.

## Examples
```ts
// example.ts

// math
const testMathSign = Math.sign(0);
const testMathLog10 = Math.log10(0);
const testMathLog2 = Math.log2(0);
const testMathCosh = Math.cosh(0);
const testMathSinh = Math.sinh(0);
const testMathTanh = Math.tanh(0);
const testMathAcosh = Math.acosh(0);
const testMathAsinh = Math.asinh(0);
const testMathAtanh = Math.atanh(0);
const testMathFround = Math.fround(0);

// ObjetConstructor
const testObjectConstructorGetOwnPropertySymbols = Object.getOwnPropertySymbols({});
const testObjectConstructorGetOwnPropertyDescriptors = Object.getOwnPropertyDescriptors({});
```
- `tsc --lib es5 example.ts`
- The above example for Math.sinh would display this error: `Property 'sinh' does not exist on type 'Math'. Did you mean 'sin'?`
- A better error might be:`Property 'sinh' does not exist on type 'Math'. Do you need to change your target library? Try changing the lib compiler option to 'es2015' or later. If you did not mean 'sinh', did you mean 'sin'?`
- [playground link](https://www.typescriptlang.org/play?target=1&ts=4.1.0-dev.20201004#code/PTAEFsEMBcAsCgDGB7AdgZ2qaBTTBZGWAZQEsBzVUAXlELgDp0LUAKABgEoBuJNTbHmj1YAGWTkAjOxp0iDADYTpHHnwxZcBIuPIAmWSMUS9q3ig2DtcAMLJ0sQ-JQOz6gVuFEyqR7SPMvm4WHkIiACqQvk6M0FGwwfyaYUQAgi5+coyQGYmWniKpgZlGkMV5odawqXHR-vIw8RXJVQBiAE7IAK6oACYxsAwAZp09vW7wIKAA8gBGAFY40HYa7V2I0Mjt7i3Qc4sbK5hrG1sA4kvTAO6oAAqdAA447dAAnsSv4LPICuiy+zgNgxyJcbvdkE8Xu9Pt9fqwAN4AXzUIV2AMOSROm3aFz2YMezzeABE8Ih2qQHti-rR0dBgaC7gSoST0GSKVSEcjeEA)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by andrewbranch** [comment]
Hmm, I think if a property exactly matches something available in a newer lib, we should just prefer the newer lib message?

**Comment by Vboivin** [comment]
@andrewbranch Sounds good, I'll do a PR with this behavior. I'll edit it later if we want a different message.

**Comment by DanielRosenwasser** [comment]
Thank you @Vboivin!
