### ISSUE TITLE
JSX element renaming issues

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#4093]
I just noticed that renaming an JSX element doesn't rename the end tag. I also expect renaming an intrinsic element would be local, when in fact, it renames all elements of that type and even the interface member of `JSX.IntrinsicElements`. Renaming intrinsic elements is quite destructive for a project.

**Comment by RyanCavanaugh** [comment]
> I just noticed that renaming an JSX element doesn't rename the end tag

Ouch, definitely a bug

>  I also expect renaming an intrinsic element would be local

I think the more likely fix is that we would disallow this the same way we disallow renaming things in `lib.d.ts`. Rename always means 'rename', not 'change to some other thing' -- switching a `div` to a `span` or what not should be a different operation.

**Comment by tinganho** [comment]
> Rename always means 'rename', not 'change to some other thing

:+1: 

@RyanCavanaugh I also find that go to definition in the end tag doesn't work.

**Comment by RyanCavanaugh** [comment]
#4096 should fix that as well
