### ISSUE TITLE
Using 'as' inside Interface for additional and only local checks, so it doesn't change anything.

### ISSUE THREAD

**Issue by dadiborn** [microsoft/TypeScript#40947]
## Suggestion

Using 'as' inside Interface for additional and only local checks, so it doesn't change anything.

## Use Cases
Can help to ensure that Interfaces written correctly especially if they are big and use imported types from other places.

## Examples
In this Example we check if keys matches
```typescript
interface Person {
    setup:{
        first_name:string
        secondName:string // Error: The property 'secondName' does not exist
        pin:number
    } as Record<'first_name'|'second_name'|'pin', any>
}
```

**Comment by andrewbranch** [comment]
The strategy here seems to be “if I write the keys the same way multiple times, it’s more likely to be correct,” which is... hard to argue with, but doesn’t seem particularly valuable. The idea of a type system feature whose only purpose is to assert that a block of code is free of typos by writing more code that can also contain typos seems highly implausible. More importantly, this would be a really confusing overload of the `as` keyword.
