### ISSUE TITLE
Call expression's leading comments are removed when assigned to a explicitly typed variable

### ISSUE THREAD

**Issue by cprecioso** [microsoft/TypeScript#40943]
The leading comment of a call expression should be kept when `removeComments: false`. And indeed, it is kept in the majority of cases, except when it is in an assignment statement that also has an explicit type annotation.

My use case for this is to keep `/** @__PURE__ */` annotations in some assignments that are side-effect free, so `terser` and `uglify` can remove them if unused.

There are some similar issues here already but they are closed and I suspect this is an edge case that was not accounted for.

**TypeScript Version:** 4.1.0-dev.20201005

**Search Terms:**  comments, pure, annotation, uglify

**Code**

```ts
const var1 = /* comment1 */ foo(bar);
const var2: any = /* comment2 */ foo(bar);
```

**Expected behavior:**

```js
const var1 = /* comment1 */ foo(bar);
const var2 = /* comment2 */ foo(bar);
```

**Actual behavior:**

```js
const var1 = /* comment1 */ foo(bar);
const var2 = foo(bar);
```

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20201005#code/MYewdgzgLgBAbgQwE4EYYF4YHoBUNQC2BApmFGjljAGYggAUARsgJQDcAUKJLIkgEwAuGAjABPDNjyESZfjEo06TVpyA

**Related Issues:** #17606 #16727

**Comment by a-tarasyuk** [comment]
```ts
function foo(x: number = /* comment1 */ 1, y = /* comment1 */ 1,) {
}

// .js
"use strict";
function foo(x = 1, y = /* comment1 */ 1) {
}
```

[Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201005#code/GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOiAvIgPQBUiEc++xYUAjIrdYuwDSIAnpRr1GzVhy49+ASkQBvAFABfIA)

**Comment by a-tarasyuk** [comment]
The same issue with the parameters

```ts
function foo(x: number = /* comment1 */ 1, y = /* comment1 */ 1,) {
}

// .js
"use strict";
function foo(x = 1, y = /* comment1 */ 1) {
}
```

[Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201005#code/GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOiAvIgPQBUiEc++xYUAjIrdYuwDSIAnpRr1GzVhy49+ASkQBvAFABfIA)

https://github.com/microsoft/TypeScript/blob/14c731689ed37b8d100b8325d0e9c21dc4659de3/src/compiler/emitter.ts#L2897-L2898

ʻEmitter.ts` shouldn't print the `type` annotation, so the` type` property is in ʻundefined`. The `node` has `original` property _(node was updated)_, which refers to the original node with the `type`, not sure, maybe make sense to try to get the `end` position from it. Or is it useless?

```ts
node.type ? node.type.end : getOriginalNode(node, isVariableDeclaration).type?.end || node.name.end
```

@weswigham @rbuckton What do you think?

**Comment by a-tarasyuk** [comment]
The same issue with the parameters

```ts
function foo(x: number = /* comment1 */ 1, y = /* comment1 */ 1,) {
}

// .js
"use strict";
function foo(x = 1, y = /* comment1 */ 1) {
}
```

[Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201005#code/GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOiAvIgPQBUiEc++xYUAjIrdYuwDSIAnpRr1GzVhy49+ASkQBvAFABfIA)

https://github.com/microsoft/TypeScript/blob/14c731689ed37b8d100b8325d0e9c21dc4659de3/src/compiler/emitter.ts#L2897-L2898

`emitter.ts` shouldn't print the `type` annotation for this case, so the` type` property is `undefined`. The `node` has `original` property _(node was updated in transformers)_, which refers to the `original` node with the `type`, not sure, maybe make sense to try to get the `end` position from it. Or is it useless?

```ts
node.type ? node.type.end : getOriginalNode(node, isVariableDeclaration).type?.end || node.name.end
```

@weswigham @rbuckton What do you think?
