### ISSUE TITLE
Why Typescript doesn't use destructuring for imports?

### ISSUE THREAD

**Issue by sosoba** [microsoft/TypeScript#40957]
Let's consider simple code: 
```ts
import {EOL} from 'os';
console.log(EOL);
```
with `target=commonjs` the output are:
```js
const os_1 = require("os");
console.log(os_1.EOL);
```
It seems to me that it may be simplest:
```js
const {EOL} = require("os");
console.log(EOL);
```

**Comment by IllusionMH** [comment]
AFAIK this will process getters once during destructuring and therefore break ["live" imports](https://exploringjs.com/es6/ch_modules.html#_imports-are-read-only-views-on-exports).

**Comment by sosoba** [comment]
This is a good reason. Thanks for the clarification.
