### ISSUE TITLE
enum values with indexOf or includes doesn't work properly.

### ISSUE THREAD

**Issue by ashr81** [microsoft/TypeScript#40960]
**TypeScript Version:**  4.0.2

**Search Terms:**
indexOf or includes with enum

**Code**
```ts
enum TABLE_COLUMN {
    TEXT = 'TEXT'
}
type tableColumnType = keyof typeof TABLE_COLUMN;
const colType: tableColumnType = 'TEXT';
console.log(Object.values(TABLE_COLUMN).indexOf(colType)) //Argument of type '"TEXT"' is not assignable to parameter of type 'TABLE_COLUMN'.
```

**Expected behavior:**
Should correct take the union type and not throw any error.

**Actual behavior:**
Throws error when trying to find the value.

**Playground Link:** Link to playground [here](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBRSo9iIbwVABCLwAogB9ADCAHkXg8ALIAOVAAG9FCUSjgmQANHCgAC8oAA5OKpfLFABfRSoFpoBjSdxs+DQGmcA6y0DxSCGVKaogknAM5nsrm8vkAbkUCE4ghoCGgB3y2t1kH1hsQxq1csVkpw8rdHsEBsgAWg8GYAAoOdIAFaQWCoAI6BiG-Spu2M1mc7n8gCUAQy3DWHOSqZ9ByrVeCKhwDQ8ZC8iHgAx1HBo3zcZmY7AYzEg-Fg0HUiSHehEXgAREzVgxEDV9KukjjV+AHKh5cI+ZAJKugioOd8yLtBDOtJBjqhHApXNI8KAnP2dKMsH0FAEEQGFhCuUcJAHaIRAMDgcW6Fg2C4bgghKIA)

**Related Issues:**

**Comment by andrewbranch** [comment]
Duplicate of #17690, though maybe not obviously so. String enum values are opaque types. Even though your key and your value have the same literal text (`"TEXT"`), `"TEXT"` is not assignable to `TABLE_COLUMN.TEXT`. So you can’t ask if the _values_ of `TABLE_COLUMN` contains a string literal—you can only ask if they contain a particular `TABLE_COLUMN`.

**Comment by rohansinghrawat99** [comment]
Hey @ashr81 hope u are doing good!
I might not have exactly understand what u wanted to from the above code but I tried to resolve the error by trying change it a bit. The output to the last line that is console log should I think be 0. If u wish u can assign me the issue!

**Comment by ashr81** [comment]
Hey @rohansinghrawat99 , Thanks for the help.
The issue is not with the output. It is with the type error I am seeing on the file when using the array `indexOf` method.

**Comment by rohansinghrawat99** [comment]
Hey @ashr81 Actually I wanted to say that the type of argument that Object.values().indexOf() is looking for won't be a string.... Instead of using that I would suggest you to use indexOf(TABLE_COLUMN[colType]). This would give u the desired result.
<img width="920" alt="Screenshot 2020-10-07 221433" src="https://user-images.githubusercontent.com/51116846/95362046-27066780-08eb-11eb-9b0a-9acf6eda6dec.png">
<img width="917" alt="Screenshot 2020-10-07 221540" src="https://user-images.githubusercontent.com/51116846/95362052-28d02b00-08eb-11eb-9d47-f05939e6bc80.png">

**Comment by ashr81** [comment]
Hey @rohansinghrawat99 
Cool. Another approach here would be
```
console.log(colType in TABLE_COLUMN)
```
