### ISSUE TITLE
Typeof (narrowed generic parameter) does not use narrowed type

### ISSUE THREAD

**Issue by eurostar-fennec-cooper** [microsoft/TypeScript#40977]
**TypeScript Version:**  4.1.0-dev.20201007

**Search Terms:**
typeof inference narrowed generic union
**Code**

```ts
interface Thing<T> {
  exampleProperty: T;
}

let something: Thing<"ABC" | "DEF"> = { exampleProperty: "ABC" };
if (something.exampleProperty === "ABC") {
  something.exampleProperty; // Type should be narrowed to "ABC" and it has been
  const a: typeof something.exampleProperty; // Type should be narrowed to "ABC" but it is not.
}
```

**Expected behavior:**
Type of something.exampleProperty is narrowed to "ABC" within the scope of the if statement.
Therefore "typeof something.exampleProperty" should be the narrowed type "ABC".
**Actual behavior:**
Type of something.exampleProperty is narrowed to "ABC" within the scope of the if statement.
Therefore "typeof something.exampleProperty" should be the narrowed type "ABC" but is actually the union type "ABC" | "DEF".
**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.1.0-dev.20201007#code/JYOwLgpgTgZghgYwgAgCoAtQHMA8qB8yA3gFDLIQAecAtgA4A2EAClAPZ3RgCeAXGgG4SAXxIkmYZAGc2NCGEwgs-DNhwAiAIIAhAMLrkAH2TqAIgFEAYusIBeYhWr0mrDlz4md+5MKHAYyAAUMnIK2AB0VLSMLOycUDzItsmeeuoAlMRk0rLyiliRTjGu8TwCyAD0FWjcnNLobACuDAAmyABGKCBwUOwA7hBtYGyp3nAgbcCS6HBSHRAQINkIbCBSknD8PJxsASF5EVHOsW4J3OVVNXVSDc1tncjdvWwDQyNaaR2NklPIwHMgNhgcIiEhAA

If this is expected behaviour, please close but a recommendation on what should be used to obtain this behaviour would be much appreciated.

Besides the example, what I am actually trying to do is have the response type of an express handler narrowed depending on what the request type is narrowed to, my attempt to far was:
```ts
export default async (
req: Request<any, ResponseType1 | ResponseType2, RequestType1 | RequestType2>,
res: Response<typeof req.body extends RequestType1 ? ResponseType1 : ResponseType2>
){
if(req.body.commonProperty === "something"){
// Req.body is narrowed to RequestType1
// res.send/response type is narrowed to ResponseType1
}
}
```
I've tried achieveing this a variety of ways but the type system just doesn't want to let me use the inferred type; I can only use the inferred type in code/outside of the type system it seems.

**Comment by j-oliveras** [comment]
As a workaround, use a variable:
```ts
interface Thing<T> {
  exampleProperty: T;
}

let something: Thing<"ABC" | "DEF"> = { exampleProperty: "ABC" };
const prop = something.exampleProperty;
if (prop === "ABC") {
  prop; // Type is "ABC"
  const a: typeof prop; // Type is "ABC"
}
```
[Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201007#code/JYOwLgpgTgZghgYwgAgCoAtQHMA8qB8yA3gFDLIQAecAtgA4A2EAClAPZ3RgCeAXGgG4SAXxIkmYZAGc2NCGEwgs-DNhwAiAIIAhAMLrkAH2TqAIgFEAYusIBeYhWr0mrDlz4md+5MKEI2IFKSdOx0yPYycgrYAHRUtIwsoe5CwDDIABQhHOG29lp66gCUxGTI2XQCyAD01WjcnMjAUp6FZf6BknD8PJxs6RVVtfWNza36IiRAA)

**Comment by eurostar-fennec-cooper** [comment]
> 
> 
> As a workaround, use a variable:
> 
> ```ts
> interface Thing<T> {
>   exampleProperty: T;
> }
> 
> let something: Thing<"ABC" | "DEF"> = { exampleProperty: "ABC" };
> const prop = something.exampleProperty;
> if (prop === "ABC") {
>   prop; // Type is "ABC"
>   const a: typeof prop; // Type is "ABC"
> }
> ```
> 
> [Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201007#code/JYOwLgpgTgZghgYwgAgCoAtQHMA8qB8yA3gFDLIQAecAtgA4A2EAClAPZ3RgCeAXGgG4SAXxIkmYZAGc2NCGEwgs-DNhwAiAIIAhAMLrkAH2TqAIgFEAYusIBeYhWr0mrDlz4md+5MKEI2IFKSdOx0yPYycgrYAHRUtIwsoe5CwDDIABQhHOG29lp66gCUxGTI2XQCyAD01WjcnMjAUp6FZf6BknD8PJxs6RVVtfWNza36IiRAA)

Nice! Unfortunately my example was a contrived one; realistically I'm trying to use this outside of the code body and trying to influence the type of a generic argument depending on the inferred type of another generic argument.

I added an example of my attempts to make this work for express Request/Response to the issue, I suppose what I'm trying to do is impossible and I should just overload the express handler perhaps. 🤔

**Comment by andrewbranch** [comment]
Not 100% sure if this is a bug, but seems likely. At least, it’s very unintuitive. Only reason I’m not confident is the comment at the implementation explicitly states that the result goes through a widening process. That said, when a union-typed identifier is narrowed, that works as expected: https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwAZ4AfeARhPgCYBuAWAChGBLAM3gApt4BeP8gJTwA3o3jj4GAJ4AHBABVek2SCTts9BgF8gA

**Comment by rasenplanscher** [comment]
This is somewhat related to https://github.com/microsoft/TypeScript/issues/38591#issuecomment-711195524

The workaround here is different, though:
```
type Thing<T> = T extends unknown ? {
  exampleProperty: T,
} : never

let something: Thing<"ABC" | "DEF"> = { exampleProperty: "ABC" }

if (something.exampleProperty === "ABC") {
  something.exampleProperty
  type a = typeof something.exampleProperty // works now 🎉🎉
}
```

The reason why this works is here: https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types

I think that the original is not a bug, but just a missing feature 👍



@eurostar-fennec-cooper 
I couldn't get the express typings on the quick, otherwise, I'd have tried my hand at a solution. Here's a little mockup based on what you've posted, maybe that helps: 
```
type ResponseType1 = { type: 'response1'}
type ResponseType2 = { type: 'response2'}

type RequestType1 = { type: 'request1'}
type RequestType2 = { type: 'request2'}

type XRequest<A,R,Q> = {
  ace: A,
  response: R,
  request: Q,
}
type XResponse<R extends ResponseType1 | ResponseType2> = {}

function x<
  R extends XRequest<any, ResponseType1 | ResponseType2, RequestType1 | RequestType2>,
  Q extends XResponse<ResponseType1 | ResponseType2>
>(
  req: R,
  res: Q,
) {
  if(req.request.type === "request1"){
    req.request.type
    // Req.body is narrowed to RequestType1
    // res.send/response type is narrowed to ResponseType1
  }
}
```

If you still need help, you're welcome to post a more complete code sample that shows what you're trying to accomplish and what's missing. I'm pretty sure, it can be done 🤓

**Comment by sandersn** [comment]
In `typeof something.p`, `something.p` is parsed as a QualifiedName, but `getFlowTypeOfAccessExpression` only works on AccessExpressions. I think it's just an oversight; as far as I can see all EntityNames that make it into `getFlowTypeOfAccessExpression` should narrow exactly the same as normal property access expressions.
