### ISSUE TITLE
Generate 'get' and 'set' accessors refactoring with optional property causes compiler error

### ISSUE THREAD

**Issue by gabritto** [microsoft/TypeScript#40994]
**TypeScript Version:**  4.0.2

**Search Terms:** generate get, optional property, generate accessors

**Code**
Before:
```ts
class Class {
    [| optionalField?: string; |]
}
```
Apply "Generate 'get' and 'set' accessors" refactoring to `[|` selected range `|]`.
After:
```ts
class Class {
    private _optionalField?: string;
    public get optionalField(): string {
        return this._optionalField;
    }
    public set optionalField(value: string) {
        this._optionalField = value;
    }
}
```
**Actual behavior:**
Compiling with **`strictNullChecks: true`**  gives error TS2322: Type 'string | undefined' is not assignable to type 'string'. Type 'undefined' is not assignable to type 'string'.
Error happens because the getter generated has return type `string` but returns `_optionalField`, and `_optionalField`'s type is actually `string | undefined` because it is optional, which is not assignable to type `string`.

**Expected behavior:**
No type checking errors. Maybe the getter and setter functions should actually have type `string | undefined` instead of `string`?

**Playground Link:** [code before refactoring](https://www.typescriptlang.org/play?ts=4.0.2#code/MYGwhgzhAEDC5WgbwFDXdA9gBwC4EtMA7MEAMXwFMQATAfgC5oJcAnfIgcwG4UBfIA), [code after refactoring](https://www.typescriptlang.org/play?ts=4.0.2#code/MYGwhgzhAEDC5WgbwFDXdADgJwJYDcwAXAU2gH0B7TI3SgOzBADFcSQATAfgC5oIieegHMA3GgyYArgCMQuYNGEki0arQZNW7DgAoAlHwFDhyCRgzYVU7PWhEAFrggA6KjTqMWbTuIsBfcyxZeUUIFTUPTW8dXUIQKRIjQVwRfTMLC0dnN3VPLR8OaABeaHjEvwxA-yA)
**Related Issues:** -

**Comment by dbartholomae** [comment]
I'm happy to take a look at this, mainly to get a better understanding of the TypeScript repo.
