### ISSUE TITLE
Omit<> excludes types from merged interfaces including index types

### ISSUE THREAD

**Issue by Kapcash** [microsoft/TypeScript#40999]
**TypeScript Version:**  v4.1.0-dev.20201008

**Search Terms:** Omit merged interface, Generic type with declaration merging

**Code**

```ts
interface Todo extends Record<string, any> {
  title: string
  description: string
  completed: boolean
}

interface Todo extends Record<string, any> {
  tags: string[]
}

const todo: Omit<Todo, 'description'> = {
  title: 'Todo 1',
  completed: false,
  tags: [''],
}

const trimedTags = todo.tags.map(tag => tag.trim()) // tags is considered as 'any' here.
```

**Expected behavior:**
Using `Omit<>` on types defining index types (`[key: xxx]`), the types from merged interface should remain defined and not fallback to the specified index type.

**Actual behavior:**
Any types from the merged interface are transformed to 'any' or 'unknown', as if they were only part of the index type, but they are actually defined. I expect them to keep their defined type from the merged interface.

It works well using `Pick<>` though.

**Playground Link:** 

Here is a [playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201008#code/JYOwLgpgTgZghgYwgAgCoHsAm7kQB6QiYDOyAShAulJgDzFhSgDmANMnCAJ4B8yA3gChkyMMDAAbCAC5kDJiGbDkmCMQRMADmPQhZ8lsqoBbTVMiZZAI3TopnQQF9Bg0JFiIUGbLgIQipBRUNPSMLOycvALKYHDMxPphigDaALpOLlQgDKJY6ADyxuKyheK03ujsAOSq6lo6IFV8ALzRImKSMshVFcgAjFWsRuim5hCWyPASxBBD7XEJyMlVValDzoJZOWB5AArACADW47L7R+V51R1SVcgAPt0mZhAWtw9VsfFNyK1C7eJSWQ9PL9QbDUYvE6TODTWYxBayZardYuAD0qNEC2hEgkVkQh1IO2QAANIsSAHSUza6bZMYzjVBY1o7bClMDkz7EcnGOCaAAUnx+fE+HLpfIAlOK0RiAOrUAmTUCzTHxZDAUhbYCqKDjDikYkGFKpYnU7JgUR0hkLPo-XLYM7HTAchbc3kCuJClWi4DGCVSwRAA) showing the error.

**Related Issues:** 
Indexed access operator issue with Omit type #36316

**Comment by andrewbranch** [comment]
Duplicate of #31153—@dragomirtitian's `OmitFromKnownKeys` suggestion solves your problem.

**Comment by Kapcash** [comment]
Got it, thanks!  
And sorry for the duplicate, I wish I found the issue myself.

**Comment by andrewbranch** [comment]
No worries, duplicates can be hard to find in a haystack of 40k 😄
