### ISSUE TITLE
Import autosuggestion doesn't work (default export error)

### ISSUE THREAD

**Issue by whitecolor** [microsoft/TypeScript#41019]
**TypeScript Version:**  4.0.3

Import autosuggestion stoped work in a project. Doesn't work with the `4.1` dev too.

![image](https://user-images.githubusercontent.com/736697/95631158-a12a1e00-0a9c-11eb-93aa-f4a4305f6fec.png)

This is a full trace log  from output 
https://gist.github.com/whitecolor/19e6ded72a8eb90a874beff468a5b552

There some errors `Error: Debug Failure. Alias targets of default exports must have a parent` don't know if it relates.

**Comment by andrewbranch** [comment]
It does look like that’s related, but I would need a full working repro to be able to do anything here, since _most_ auto imports do in fact work in 4.0.3 😄

**Comment by whitecolor** [comment]
I have debugged it.

It was due to this module:

```ts
import { LocalStorage } from 'node-localstorage'

if (typeof localStorage === 'undefined' || localStorage === null) {
  console.log('localStorage')
  const localStorage = (global.localStorage = new LocalStorage('./.tmp/scratch'))
  localStorage.clear()
}

export default global.localStorage // this line cauzed it.
```
So when I removed line:
```ts
export default global.localStorage
```
It started to work, so something went wrong with default export with `global`, so it seems the error in the log relates because there was no one after the fix.

**Comment by andrewbranch** [comment]
Great, thanks for narrowing it down!

**Comment by andrewbranch** [comment]
@whitecolor I actually still can’t reproduce this. Can you please provide a full repro? I.e., tsconfig.json, package.json, and all source files. A link to a repository would be great.

**Comment by whitecolor** [comment]
@andrewbranch 
https://github.com/whitecolor/ts-global-expor-issue

go to test2.ts
