### ISSUE TITLE
TypeScript suggests only first (default) import 

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#41010]
**TypeScript Version:**  4.1.0 (current master)

**Search Terms:** auto completion, alias, export

**Code**

```ts
// a.d.ts
declare namespace foo { class Bar {} }
declare module 'path1' {
  import Bar = foo.Bar;
  export default Bar;
}
declare module 'path2longer' {
  import Bar = foo.Bar;
  export {Bar};
}
// b.ts

Ba|; // < auto complete here
```

**Expected behavior:**

TypeScript presents two import auto completions, one that chooses to import from 'path1', the other chooses 'path2longer'. I can select the second one and end up importing from 'path2longer'.

**Actual behavior:**

TypeScript does present two import auto completions, but both end up importing 'path1'.

I've debugged this a bit, TS produces the correct completions, and also displays one as "export default Bar" and the other as "export Bar", with correct `source` fields. However TypeScript displays the same module URI (path1) for both, and when creating the code fix actions, it sorts possible modules without taking the option the user chose into account. This means both import completions have the same code fix, they import the shorter path.

Given the import is different (different path, different import style), I think TypeScript should follow the user's selection here.

**Playground Link:** 

**Related Issues:**

**Comment by mprobst** [comment]
See https://github.com/mprobst/TypeScript/commit/c6462e62808c3e6cc756c20dc960afa386db0920 for a test case reproducing the issue.

**Comment by andrewbranch** [comment]
I think this is long-standing “intentional” behavior, but it’s always struck me as very weird, so it’s worth reevaluating.

**Comment by mprobst** [comment]
My usecase is that I'm changing one ambient import scheme to another. The
symbols are represented as aliases of one either. I'd like users to be able
to choose the correct import.
