### ISSUE TITLE
Indexing using [key in Foo['bar']] works inconsistently - works fine without generics, but doesn't work properly with generics

### ISSUE THREAD

**Issue by grumd** [microsoft/TypeScript#41024]
**TypeScript Version:** v4.1.0-insiders.20201009

**Search Terms:**
generic index key in

**Code**

```ts
type Action = {
  param: "one" | "two"; // Can also be "string", same bug happens
}

const func1 = (foo: { [key in Action['param']]: boolean }, bar: Action): void => {
  // Ok
  foo[bar.param];

  // Ok
  const k: Action['param'] = bar.param;
  foo[k];
}

// Call example
func1({ one: true, two: false }, { param: 'one' });

// The only difference here is adding a generic
const func2 = <Act extends Action>(foo: { [key in Act['param']]: boolean }, bar: Act): void => {
  // Error! (error text below)
  foo[bar.param];
  
  // Ok
  const k: Act['param'] = bar.param;
  foo[k];
}
```

**Expected behavior:**
`foo[bar.param]` should be just as successful as
```typescript
  const k: Act['param'] = bar.param;
  foo[k];
```

**Actual behavior:**
`foo[bar.param]` in `func2` throws this:
```
(property) param: "one" | "two"
Element implicitly has an 'any' type because expression of type '"one" | "two"' can't be
  used to index type '{ [key in Act["param"]]: boolean; }'.
  Property 'one' does not exist on type '{ [key in Act["param"]]: boolean; }'.
```

**Playground Link:**
https://www.typescriptlang.org/play?ts=4.1.0-insiders.20201009#code/C4TwDgpgBAggxsAlgewHZQLxQN4CgpRgCGATkQLYBcUARGhDVAD63ADuyNA3FAPS9QAwkXREANgGdkUAEbQaE4CUSoA5jQA0UCRWgyArqqgALImEioJuAL65c-KAHVkJANYSoAMxXQAtFFRpVQhUCGU4D2MwiFw4NEUvfVQ4AEZMKAAKT2RkamwoAG1XCBAoFVgEFFQCgHJiMnIagF0m6hkcsQgRKGstGVJqeCQ0AEpqADdkRAATTAA+HHw+AQB5VyXs5AL+kgA6eoomrjsCBzWluMtgKFdByrRag8am9J390gpjgk2io5s7BzCMRiKAQAAeFDAnVwniSqQy+Xo1CU+ggWnYuS84gk0F6OEIHyoUBq9BqPRGx3sAgAKlEoGgxKVpohPJ5osloIgPERpsy1FAiFBgqFwmUrl1ZshPBVhqhYvFrrDkgAmdIAHiGoLBwBC0w8QyqcyyOTyhWKpXKQ0ehOarVkHS66DxOzuwDGUEmM3mi1OAgAoiQSC4AIQbHLbUjvBp-AhLM7rAiXBK3GXWhrNV6Rp5fLzh1x-WxAA

**Related Issues:**
Maybe these, but I didn't really understand what these issues were talking about.
https://github.com/microsoft/TypeScript/issues/40809
https://github.com/microsoft/TypeScript/issues/40832

**My idea**
Maybe this issue happens because `bar.param` evaluates to `'one' | 'two'` from `Act['params']`,
but `foo` evaluates to `{ [key in Act["param"]: boolean; }` instead of `{ [key in ('one' | 'two'): boolean; }`
So when generics are in action, `foo: [key in ...]` works differently from `bar: ...`

**Comment by RyanCavanaugh** [comment]
This is a correct error given how other parts of generics behave. You could write this call, which would be unsound:
```ts
const func2 = <Act extends Action>(foo: { [key in Act['param']]: boolean }, bar: Act): void => {
    // Allowed, albeit incorrectly
    const m: typeof bar.param = "two";
    // Would be unsound, given that the prior line is not an error
    const b: boolean = foo[m];
}

func2({one: true}, { param: "one"});
```
*The reason* it's unsound is a little sideways, though - when you read a property off `bar`, we treat that as if it were of the type of the constraint, rather than leaving it as a lookup type. This is usually desirable, but leaves you with a too-wide type to correctly index that back into something that's still being typed in terms of the generic values.

If you can prove to yourself that something like this isn't happening in an unsound way, using a type assertion like `foo[m as keyof typeof foo]` would be appropriate here
