### ISSUE TITLE
Support pattern matching in <Reference> directives

### ISSUE THREAD

**Issue by Davidhanson90** [Microsoft/TypeScript#4102]
Hey all, 

Maybe this has been raised before but its something I would really like to see supported in TS.  Basically I would like the ability to support referencing TS files using patterns.  For example 

This 
```
/// <reference path="../../helpers/promiseHelper.ts" />
/// <reference path="../../helpers/loggingHelper.ts" />
```
could be 
```
/// <reference path="../../helpers/*Helper.ts" />
```
or folder patterns
```
/// <reference path="/app/specs/**/*.ts" />
```

Thoughts?

**Comment by mhegazy** [comment]
while i see the value, this makes tooling much harder and more complex. now an IDE has to add a directory watcher on possibly the whole file system, so that eveytime you add a new file that matches your wild card it gets picked up.

**Comment by danquirk** [comment]
In addition to what Mohamed mentioned, /// references in general are a little unwieldy and hopefully the future is more weighted towards tsconfig.json and ES6 modules.

**Comment by Davidhanson90** [comment]
I am not sure why this has been closed without and discussion. Currently you have to manage all these references manually and on very large apps this becomes painful.

**Comment by mhegazy** [comment]
one approach that i have seen to alleviate this issue is to to have smaller files that you would import instead of all files. so you would have something like `helpers\index.ts`:
```ts
/// <reference path="./promiseHelper.ts" />
/// <reference path="./loggingHelper.ts" />
```

then you would include that directly as `/// <reference path="../../helpers/index.ts" />` instead of `/// <reference path="../../helpers/*.ts" />`

**Comment by Davidhanson90** [comment]
Yeah this is our current strategy, but this is just moving the location of the reference to a more local location to the file itself, you still have to manage them all still as well as managing the index file.

**Comment by mhegazy** [comment]
I think the ultimate fix is an easier way to breakup your code into "projects". this is tracked by #3469. this way you do not even need a reference. 

also possibly related, is supporting globs in tsconfig.

**Comment by shuky19** [comment]
👍

**Comment by adrian-moisa** [comment]
Any change regarding this issue? I want to create a system of modules. Each one of them gets connected to the state store. So I need to extend the `AppState` interface from each module without creating hardcoded imports. Some modules might not be around when I build the app. I thought of ambient declarations but they don't work with imports. Then I checked namespaces but again they need hardcoded imports. So I thought maybe reference path can do a wildcard trick.
