### ISSUE TITLE
Reflect.ownKeys should return the keys of the type that it was called upon.

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#41036]
**TypeScript Version:**  Nightly

**Code**

```ts
// x: readonly { 1: 1, 2: 2, 3: 3 };
const x = {
    1: 1,
    2: 2,
    3: 3
} as const;

// y: (keyof typeof x)[]; ideally: [ (1 | 2 | 3), (1 | 2 | 3), (1 | 2 | 3) ]
const y = Reflect.ownKeys(x).map(i => x[i]);
```

**Expected behavior:**

Successful compilation of TypeScript source code.

**Actual behavior:**

Type `symbol | string | number` cannot be used to index type `{ 1: 1, 2: 2, 3: 3 }`.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-insiders.20201010#code/PTAEA8C5Qb1BGa8A0oBM02oMzW6AXwG4AoAYwHsA7AZwBcJQBeWE0dhJZNjjdbjqFxCSBUAEMaoSrTqkSIUAE9oACnigAPui1CAlAG0AukVABLACYBTcQBtbK0AdDrdaXdj2pX299s-eGr4eeqBG5NT0ysygAEpWAGa2VmR0AHQUAO5UANJWSjSq4HppALbiAA6qZswAfBAGZkZ6REA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/34626

Now, this is somewhat weird to think about, as an object's own keys are not *all* of the keys that TypeScript sees, for example, it doesn't give anything from the prototype, so it's giving a subset of the TypeScript keys, yet still keys to the object nonetheless.

You couldn't expect to get `hasOwnProperty` from `Reflect.ownKeys`, yet `hasOwnProperty` is a key in the prototype that TypeScript will allow to be used on the object. This means that `keyof {the object}` isn't a proper type for the output, while still being indexable.

Unless something safer can be done, I suggest changing the type signature of `Reflect.ownKeys` to something along the lines of `ownKeys<T extends object>(source: T): (keyof T)[]`.

**Comment by Qwertiy** [comment]
Not as simple. [Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XQA4CcCWA3MALgKbQAeAXNAHYCuAtgEZGbQC80ADANwpro0MQ2YNACelCARxUA5m2gAiBTwC+SJMAD2VSdDDyqRAO5wAFAEoeSAEpEAZiCLACAOk1GqAaSKiIpsOYudpqYAKJgwAAWpgDWPmwAfHoA2nGiALryCmAMwAqWQA)

```typescript
class A {
    private x: number = 0;
    public y: string = "";
}

const a = new A();

Reflect.ownKeys(a).forEach(key => a[key] = "abc");
```

1. This code access private field.
2. Type `A[keyof A]` is `string`, but field `x` has type `number` and is assigned in this code.
3. In case of interfaces objects can have any other fields except related to interface.

Anyway I agree that error with _"can't be used to index type"_ is something weird, but the property has no the type you want it to.

**Comment by 00ff0000red** [comment]
> Anyway I agree that error with _"can't be used to index type"_ is something weird, but the property has no type you want it to.

Yeah, it's *very* weird trying to describe this in TypeScript, due to just how dynamic this is.
Yes, we can index the type with `ownKeys` from there everything else is almost a black box. Settng the object with these keys, any everything else is beyond me.

Technically this could be misused, but that's with everything.

```ts
const x: {
    a: 'a',
    b: 'b'
} = {
    a: 'a',
    b: 'b'
};

const y: {
    b: 'b',
    c: 'c'
} = {
    ...x,
    c: 'c'
};
// TS keys: ("b" | "c")
// ownKeys: [ 'a', 'b', 'c' ]
// error: "a" doesn't fit into the constrain keyof { b: 'b', c: 'c' } 
```

**Comment by 00ff0000red** [comment]
I guess it could be argued that technically the keys can index the object, not the type, but types are supposed to reflect the reality of the object, right?

**Comment by RyanCavanaugh** [comment]
See https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript

**Comment by 00ff0000red** [comment]
> See https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript

Welp, I'll close this issue, since the core idea has already been addressed before.

Now as for
> 2. A type with additional properties is always a subtype of its base type
> 3. It is legal to alias a subtype value by a supertype reference

I would be all for those, but I guess I'm just looking for AssemblyScript, since it is not one of TS's goals to
> Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

Really I'm looking for something stricter and less *dynamic*.

**Comment by RyanCavanaugh** [comment]
I'm super curious which part of that you think is unsound

**Comment by mellester** [comment]
> Not as simple. [Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XQA4CcCWA3MALgKbQAeAXNAHYCuAtgEZGbQC80ADANwpro0MQ2YNACelCARxUA5m2gAiBTwC+SJMAD2VSdDDyqRAO5wAFAEoeSAEpEAZiCLACAOk1GqAaSKiIpsOYudpqYAKJgwAAWpgDWPmwAfHoA2nGiALryCmAMwAqWQA)
> 
> ```ts
> class A {
>     private x: number = 0;
>     public y: string = "";
> }
> 
> const a = new A();
> 
> Reflect.ownKeys(a).forEach(key => a[key] = "abc");
> ```
> 
> 1. This code access private field.
> 2. Type `A[keyof A]` is `string`, but field `x` has type `number` and is assigned in this code.
> 3. In case of interfaces objects can have any other fields except related to interface.
> 
> Anyway I agree that error with _"can't be used to index type"_ is something weird, but the property has no the type you want it to.

keyof does not show us private keys. 
Mayby if 1 of the suggestion in gets added you can do
` ((key: keyof Public<A>) => ...);
https://github.com/microsoft/TypeScript/issues/22677
