### ISSUE TITLE
Allow resolveTxtModule just like resolveJsonModule to copy txt files from src to dist directory

### ISSUE THREAD

**Issue by amirsaleem-kn** [microsoft/TypeScript#41032]
#### Problem
Suppose I have `.txt` files in my `src` directory, Now when I `build` the source code, the `tsc` compiler ignores the `.txt` files.

#### Suggested Solution:
Typescript compiler should have an option to resolve `.txt` file and copy the same to `dist` directory whenever build happens. This is the same as `JSON` modules. Just like `resolveJsonModule` there should be a way to add the `resolveTxtModule: true` in the compiler configuration for the compiler to resolve `.txt` files and copy the same from `src` to `build` directory

Is this already supported? If yes, please guide me. As far as I know, for this kind of use case, developers use third party packages like `copyfiles` or module bundlers and task runners like `gulp` or `webpack`

Proposed configuration update

```js
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "resolveTxtModule": true, // This is the proposed solution
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "typeRoots": ["node_modules/@types", "node_modules/@types/node"],
    "lib": ["esnext.asynciterable"],
    "paths": {
      "*": ["node_modules/*"]
    }
  },
  "include": ["src/**/*"]
}

```

**Comment by RyanCavanaugh** [comment]
See e.g. #28958 - non-code files are out of scope for our build process
