### ISSUE TITLE
Suggestion: introduce a way to explicitly say what keys don't exist on an object

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#41038]
The entire type system can be described as a system allowing us to describe the qualities that data has.
Some data is a string = `x: string`.
The expected data is structured to be an object with a key "foo" that nothing is known about = `x: { readonly foo: unknown }`.

And for the most part, this works pretty well, just keep adding more to it and your code should be safe, except when it isn't.

A moderate amount of problems with JS/TS are accessing keys that don't exist.
Whether it's sparse arrays, objects, deleted properties, etc.
For example, it's valid to access the [prototype of an arrow function](https://github.com/microsoft/TypeScript/issues/1761):
```ts
(() => {}).prototype;
```
This is because arrow functions are defied as `Function`.
What if we want to inherit from `Function`, yet not have the `prototype`? That is essentially all that arrow functions did.

An example of an attempt an inheriting from `Function`:
```ts
class ArrowFunction extends Function {
    readonly prototype?: undefined;
}
```
There we go, it's undefined, no one will accidentally misuse it.
Except that there's now a problem: it can still be indexed, even though the *key* doesn't exist, not the *value*.
Reality: `"prototype" in (() => {}) === false`.
TypeScript: `typeof (() => {}).prototype === "undefined"`.
We shouldn't even be allowed to access the property in the first place, it doesn't exist.

Maybe someone is working with some built-in native code, ex: the `Worker` class.
If, say for some reason, one had frozen the instances of the `Worker`, it's getters and setters would be readonly, yet why even have them if they would always contain the same value?
```ts
class Thread extends Worker {
    // onerror is always undefined, yet also readonly, so why even allow access to it?
    onerror: DNE; // would normally exist, but now it doesn't

    constructor(...) {
        super(...);
        Object.freeze(this);
    }
};
```
Technically this can be done by casting the constructor, but this would be ugly and unergonomic.

## Suggestion

A method by which we can describe an object, without a specific key or set of keys.

```ts
type type0 = {
    foo: bar,
    baz: qux
};

type type1 = type0 & {
    baz: never
}; // still allows indexing type1["baz"]
```

## Use Cases

This would help fix large amounts of currently broken code. In truth, if all code were perfect already, this would be 100% unnecessary, but that's not the case.

Use cases:
Inheriting from classes and removing properties from indexing entirely.
Fixes old code purely via TS's type system.
Finally allows null prototype objects.

## Examples

```ts
type NullObject<K extends string | symbol, V> = {
    [Key in typeof Object.prototype]: DNE /// does not exist
} & Record<K, V>;

const myNull: NullObject<symbol, symbol> = Object.create(null); // Object.create would now need an overload for (proto: null) and a return type, but that is beyond the scope of this.

const test = Symbol(NaN);
myNull[test] = test;

test.constructor; // Error: property "constructor" doesn't exist on type "NulObject<symbol, symbol>"
```

I personally have no clue as to what the syntax should be, but the example above should give the idea.

## Checklist

My suggestion meets these guidelines:

* [ * ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ * ] This wouldn't change the runtime behavior of existing JavaScript code
* [ * ] This could be implemented without emitting different JS based on the types of the expressions
* [ * ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ * ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by 00ff0000red** [comment]
Oop, accidentally clicked "enter" a bit early

**Comment by RyanCavanaugh** [comment]
This sounds a lot like negated types, or just the existing `Omit` helper, depending on usage. Can you clarify?

**Comment by 00ff0000red** [comment]
> This sounds a lot like negated types, or just the existing `Omit` helper, depending on usage. Can you clarify?

Honestly, now that you mention it, it totally does.

The only difference is that I am suggesting it's usage with class inheritance.

**Comment by RyanCavanaugh** [comment]
We'll track at #29317
