### ISSUE TITLE
Generic union tuple type is not defined correctly

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#4103]
Length and type of tuple elements is not correct.

```ts
function f<T>(arg: [string, T|Function]) { } // need two elements tuple parameter.
f<number>(['', 0, '', 0, Function]);         // must be error, but it is not an error.
```

**Comment by RyanCavanaugh** [comment]
As usual in our type system, you are allowed to have "more" than is required.

The provided array literal satisfies the constraint of having a `0` property of type `string` and a `1` property of type `number` (which is assignable to `number|Function`).

**Comment by falsandtru** [comment]
Sorry, I forgot it spec.
If possible, I want to make it possible to check the following type check.

```ts
function f(arg: [string, number]|[string, number, number]) { }
f(['', 0, '']); // want a type error
```

Thank you.
