### ISSUE TITLE
`Reflect.deleteProperty` allows deletion of properties that aren't optional

### ISSUE THREAD

**Issue by CrimsonCodes0** [microsoft/TypeScript#41039]
**TypeScript Version:**  All / Nightly

**Search Terms:** Reflect, Object, Reflect types, Object types, Reflect method types, Object method types, Reflect.deleteProperty, deleting non optional properties

**Code**

```ts

const foo = { "bar": "baz" } as const;

Reflect.deleteProperty( foo, "bar" );

console.assert( foo.bar === "baz", "unreachable" );
```

**Expected behavior:**

TypeScript compiler error.

**Actual behavior:**

Runtime JavaScript error.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-insiders.20201010#code/MYewdgzgLgBAHjAvDA3gKBpmBGAXDgGgywCZ8SisYBmfatAXxgEMIZRIoBuNNAej4wAJgFMANiKgj4AbWwBdfoICWYiQHNmY-AGsRATxgAibEZjKIYAOSwQAByjLwW3gCURAMwnAoAOlESUgAKAE72IiFQ+gAUcAQ4AJQ8AjAaWvjMwMAiDmxGIABGAFYiPmbMYELG0CHKYOowAD4wYACuALYFEU0wEPqdIGJGvBzQMB7KIdAAkpUicPjYSLIKPGijgyK+YiDq0cSYE1NQs6IIiBeEByvySJfYlFhHM3Nx13ByikkwKfN2pVIhPgoCFWtIQWD4g8cEA

**Related Issues:** None

Seems to be a type issue as `Reflect.deleteProperty`'s type signature is `(object, string | number | symbol) => boolean`, instead of something that uses generics.

**Comment by mayankagarwal44442** [comment]
Hey! I'd like to take up this issue if no one is working on it.

**Comment by RyanCavanaugh** [comment]
I don't believe there's any way to write a working declaration for this without contravariant generics of some sort

**Comment by ExE-Boss** [comment]
@00ff0000red
Your definition of `Object.is` is incorrect, as it needs to be some kind of type predicate, similar to `===`, but treating two `NaN`s as identical and `Object.is(+0, -0)` as being `false`.

**Comment by 00ff0000red** [comment]
> @00ff0000red
> Your definition of `Object.is` is incorrect, as it needs to be some kind of type predicate, similar to `===`, but treating two `NaN`s as identical and `Object.is(+0, -0)` as being `false`.

`Object.is<T>(T x, T y): x is y`
This ^ doesn't make much sense, all TS sees are the types.

Maybe it could be an overload?

`Object.is<T>(T, T): boolean`
`Object.is<T, H>(T x, H y): x is y`

But then, it's already invalid to compare types between each other, using the equality operator, so I don't see how that could make sense.

All I know is that `(any, any)` is wrong.

What do you suggest?
