### ISSUE TITLE
throws keyword

### ISSUE THREAD

**Issue by mateja176** [microsoft/TypeScript#41031]
## Suggestion

The implementation of the Java-like [throws keyword](https://www.w3schools.com/java/ref_keyword_throws.asp). Comparable to having a hypothetical generic `Never<T>` type, the `throws` declare which type of exception a function may throw. 

## Use Cases

- When writing functions whose body contains a `throw` statement.
- As part of the bigger picture where the type of error a Promise throws is explicit and part of the type signature and where errors specified in a catch statement have known types.   

### Function which throws

```ts
function (): throws Error {
  throw new Error(`${getRandom216DigitNumber()} TSLA`) // pun inteded
}
```

### Function which returns a value or throws an error

```ts
function validateEmail(maybeEmail: string): string throws TypeError {
  if (isEmail(maybeEmail)) {
    return email
  } else {
    throw new TypeError(`${maybeEmail} is not a valid email.`)
  }
}
```

### Assertion function

Since assertion functions are expected to have a throw statement and since they assert that a value is of a certain type, their return type may always be a union between `void | TypeError`.

#### Assertion with explicit 

This is an alternative approach, and although it's more explicit it's also verbose.

```ts
function assertEmail(maybeEmail: unknown): asserts maybeEmail is string throws TypeError {
  if (!isEmail(maybeEmail)) {
    throw new TypeError(`${maybeEmail} is not a valid email.)
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Related
- [Promise rejection type.](https://github.com/microsoft/TypeScript/issues/39680)
- [Promise catch error parameter should not be of type any.](https://github.com/microsoft/TypeScript/issues/6283)
- [Promise catch error parameter should not be of type any.](https://github.com/microsoft/TypeScript/issues/6283)

**Comment by MartinJohns** [comment]
Duplicate of #13219.

**Comment by mateja176** [comment]
@MartinJohns Thanks! Closing in favor of [#13219](https://github.com/microsoft/TypeScript/issues/13219)
