### ISSUE TITLE
Generic type uplifting during assignment (ts 2775)

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#41047]
**Search Terms:**

`generic uplifting`, `needs an explicit type annotation.`, `2775`

This is probably an existing issue but I can't find one.

**Code**

```ts
function assertUnknown<T>(value: unknown, validate?: (s: T) => boolean): asserts value is T {
  if (validate && !validate(value as any)) throw new Error('failed')
  return
}
const foo = assertUnknown

const s: unknown = false
assertUnknown(s, (s: boolean) => typeof s === 'boolean')
foo(s, (s: boolean) => typeof s === 'boolean') // failed
```

**Expected behavior:**

`foo` works just like `assertUnknown`

**Actual behavior:**

const foo: <boolean>(value: unknown, validate?: ((s: boolean) => boolean) | undefined) => asserts value is boolean
Assertions require every name in the call target to be declared with an explicit type annotation.ts(2775)
'foo' needs an explicit type annotation.

**Playground Link:** 

[playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwM6oKYCcoFUwDWYcA7mADwAqAfABQBuyANiBgFyLhGlgA0ijJjAAmyKBgD8HWqg6UAlIgC81RACM4cJhmRh5HNJhyoBzVohgnKiAN4AoRI4vBEDZiLEZEAMm+IAhIIe4m4sXmgoYACe8opQABZYpIhgGCSIAKJYSVi0AOTAyDDawnnyDk5YGFAgWGB2AL52EAioUIjAmsoo6Nh4hMRkds2t7bKcAzzdhUyYdoZ9+NxkMvwyHBpaOnrKqlBRAA4YcC4mSueIeZvaumV2nXCrruPX24oqiPtHJ4hnF1eaG5gMpAA)

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/37818

This is probably caused by different handling of assignment vs declaration:

```ts
assertUnknown<boolean>(value: unknown, handler?: ((s: boolean) => boolean) | undefined): asserts value is boolean
foo: <boolean>(value: unknown, handler?: ((s: boolean) => boolean) | undefined) => asserts value is boolean
```

One interesting note:

```ts
// source.ts
export function assertType() { ... }

// works fine
assertType.unknown = function assertUnknown<T>() { ... }

// does not work
function assertUnknown<T>() { ... }
assertType.unknown = assertUnknown

// source.spec.ts
import { assertType } from './source'

assertType.unknown(..)
```

**Comment by MartinJohns** [comment]
This is by design: #32695

All assertion functions must have an explicit type annotation, and your `foo` function does not have it.

Once you add the explicit type annotation it works:

    const foo: <T>(value: unknown, validate?: (s: T) => boolean) => asserts value is T = assertUnknown

Or a shorter version:

    const foo: typeof assertUnknown = assertUnknown

**Comment by unional** [comment]
While it is related to assertion function, I think it is a legacy issue.

Consider this:

```ts
function assertCustom<T>(
  validator: (s: T) => boolean
): (subject: unknown) => asserts subject is T {
  return function (subject) {
    if (!validator(subject as any)) throw new TypeError(`subject fails assertion`)
    return
  }
}

const isBool = assertCustom<boolean>(s => typeof s === 'boolean')
const s: unknown = false

// fail
isBool(s)

// ok
expect(isBool(s)).toBe(undefined)
```

`isBool` has no generic type because the type is declared when calling `assertCustom()`.

https://stackblitz.com/edit/typescript-zcuu9x?file=index.ts

**Comment by MartinJohns** [comment]
Your StackBlitz link doesn't work, there's no relevant content.

> isBool has no generic type because the type is declared when calling assertCustom().

I'm not sure why you think that is relevant. It being generic or not has no relevance.

In your example the second call to `isBool()` is not used for any narrowing by the CFA, so the rule for assertion functions does not apply.

In your first call the explicit type annotation is missing. Once you add it it will work.

**Comment by unional** [comment]
> Your StackBlitz link doesn't work, there's no relevant content.

Ar, I didn't save the file. Please try again.

**Comment by MartinJohns** [comment]
> Please try again.

Works now. 👍 But the answer remains unchanged.

You also wrote:

> If you hover over isBool, you will see it already has the correct type:
> `const isBool: (subject: unknown) => asserts subject is boolean`

Having the correct type is not relevant either when the requirement is to have an **explicit type annotation**. Your `isBool` variable does not have any type annotation at all, so the type is inferred.

**Comment by unional** [comment]
> In your example the second call to `isBool()` is not used for any narrowing by the CFA, so the rule for assertion functions does not apply.

I see, that make sense.

However I don't see there is an explicit decision made in #32695 that the assertion did not copy to the variable.

**Comment by unional** [comment]
I guess you mean this:

> An entity is considered to have an explicit type when it is declared as a function, method, class or namespace, or as a variable, parameter or property with an explicit type annotation. (This particular rule exists so that control flow analysis of potential assertion calls doesn't circularly trigger further analysis.)

**Comment by MartinJohns** [comment]
> However I don't see there is an explicit decision made in #32695 that the assertion did not copy to the variable.

I do. :-)

> A function call is analyzed as an assertion call or never-returning call when  
>
> - each identifier in the function name references an entity with an explicit type, and
>
> An entity is considered to have an explicit type when it is declared as a function, method, class or namespace, or as a variable, parameter or property with an explicit type annotation. (This particular rule exists so that control flow analysis of potential assertion calls doesn't circularly trigger further analysis.)

In your example `isBool` is not declared with an explicit type annotation.

**Comment by unional** [comment]
Thanks.

I can't think of a cases that this would trigger a circular reference during analysis.

On the other hand, I try doing the same with user-defined type guards.
In that case, it is working correctly without the need of explicit type annotation.

So in that case, it may worth some investigation for improvement.

**Comment by RyanCavanaugh** [comment]
User-defined type guards are different from asserting methods because only the latter can cause a statement to become a new node in the control flow graph. This is not a bug or oversight.

Obviously if we could just make this work by looking at it and thinking a little, we would have, rather than write out multiple paragraphs in the PR description about the limitations 😉

**Comment by unional** [comment]
Hi @RyanCavanaugh, thanks!

Just want to dealt into this a little bit more. 😛 
I can understand that user-defined type guards and asserting methods are different at consumption.

But I don't understand why the declaration needs to be explicit.
The language service can get the needed information from the assignment:
![image](https://user-images.githubusercontent.com/3254987/95770966-16e5e380-0c6f-11eb-9200-d85311bf43f1.png)

So my guess is there are sufficient information available at the assignment to create the variable `isBool` declaring it as an asserting method.

btw, great TSConf! Thank you!

**Comment by RyanCavanaugh** [comment]
The relevant process looks like this:
 1. Generate a control flow graph that determines which nodes need to be looked at in order to determine the type of an expression
 2. Get all the types of expressions using that control flow graph
 3. (There is no step 3; do not loop back to step 1)

The first part is *syntactic*, necessarily, because type information depends on the control flow graph. The second step then proceeds using that control flow graph.

What you need to "fix" this is to either make *everything* in expression space part of the control flow graph, which would be unpalatably slow (both in terms of memory consumed and CPU time consumed walking the graph), *or* to run some algorithm to keep augmenting the control flow graph and recalculating types until *hopefully* you reach a fixed point, which would also be very slow.

The "explicit type annotation" rule allows TS to augment the graph appropriately at step 1 so that it doesn't have to use information that is only available during step 2 to form a proper CFA graph.

**Comment by unional** [comment]
Ar, got it. Thanks!

Great explanation as always. 🌷
