### ISSUE TITLE
type guard function does not work with class

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#41050]
**TypeScript Version:**  4.0.2

**Search Terms:**

user defined type guard, not working with class

**Code**

```ts
class Foo { }
const s: Foo | number = 1 as any
function isFoo(v: unknown): v is Foo {
    return v instanceof Foo
}
if (isFoo(s)) {
    // s is still type `number | Foo`
}
```

**Expected behavior:**

`s` is narrowed to `Foo`

**Actual behavior:**

`s` is `number | Foo`

**Playground Link:**

[playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG9oF8BQx4DsIBdoIAuORaAH2hwFcBbAIwFMAnaAXmgEZpJecAnhgBmNHMHwBLXNEkQE8ABQA3UmIDWOeAHccASlLLZMBSgzQL0Fk3w0WOaEcl58YcU3jCy8DJklfFOQVFCD09M0toAHooomMiKRAQaHwBAAcmaAADWkZWSm8s3wwgA)

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/36887

**Comment by unional** [comment]
Also tried:

```ts
function isFoo2(v: unknown): v is InstanceType<typeof Foo> {
    return v instanceof Foo
}
```

**Comment by kitsonk** [comment]
Empty classes equate to an instance type of `{}` which is a problematic type in TypeScript, as they effectively equate to `any`, and so you were asserting a type that equated to `any` which meant that the type was not narrowed.  Adding anything to the class will fix the issue, [for example this resolves the issue](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1pgBQEoUF9VDh4A7CAF2ggC45FoAfaUgVwFsAjAUwCdoAvNACMmGGFIBPVADNWpYBQCWZaEogJ4WAG515Aa1LwA7qRx1tamJpToM0XtwqtepaJaXkKE4N3gz6eCJUJQCsdU0sCBw8NAwIAG5oAHpk6itoCkkAB25AoiA):

```ts
class Foo {
  a() {}
}
const s: Foo | number = 1 as any
function isFoo(v: unknown): v is Foo {
    return v instanceof Foo
}
if (isFoo(s)) {
  s; // s is type Foo
}
```

**Comment by unional** [comment]
@kitsonk  yeah, very nice. Thanks.

Forgot about the empty class issue. For sure it happened to me in the past. 😛
