### ISSUE TITLE
Even with `!`, get `TS2790: The operand of a 'delete' operator must be optional.` with TypeScript 4

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/TypeScript#41054]
class A{ s!: number; b(){this.s=5;} c(){delete this.s;} }
    
    const a = new A();
    a.b();
    a.c();

Output, with a tsconfig from `tsc --init`:

    $ tsc
    1:48 - error TS2790: The operand of a 'delete' operator must be optional.
    
    1 class A{ s!: number; b(){this.s=5;} c(){delete this.s;} }
                                                     ~~~~~~

>Found 1 error.

Shouldn't the `!` force it to always be non empty, and thus not err here?

**Comment by MartinJohns** [comment]
Please follow the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). That will make the work for the TypeScript team much easier. :-)

---

> Shouldn't the ! force it to always be non empty, and thus not err here?

The **non-null assertion operator** `!` just tells the TypeScript compiler to ignore the potentially missing value of a **non-optional property**. It does not force anything to be at runtime.

Also you misread the error message. The `delete` operator requires the operand (in this case `this.s`) to be an **optional property**, but your property `s` is not optional.

**Comment by SamuelMarks** [comment]
Thanks
