### ISSUE TITLE
Add `ThisParameter<Fn>` utility type, to complement `Parameters<Fn>`

### ISSUE THREAD

**Issue by papb** [microsoft/TypeScript#41073]
## Search Terms

Parameters, this

## Suggestion

A new built-in utility type, `ThisParameter<Fn>`, should be added to complement the already existing `Parameters<Fn>` type. See #41072.

## Use Cases

Retrieving the type of the `this` parameter of a given function type.

## Examples

If, for example, I want to declare a new function type based on an existing type, with a different return type, one might think the following is enough:

```ts
type MyFunction = (this: Date, foo: number) => never;
type MyFunctionWithoutThrowing = (args: Parameters<MyFunction>): void;
```

But it is not (see #41072). So the new type would allow:

```ts
type MyFunction = (this: Date, foo: number) => never;
type MyFunctionWithoutThrowing = (this: ThisParameter<MyFunction>, args: Parameters<MyFunction>): void;
```

Which would be correct.

## Workaround

It is currently possible to implement this as follows:

```ts
type ThisParameter<Fn extends Function> = Fn extends (this: infer ThisArg, ...args: any[]) ? ThisArg : unknown;
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DavidANeil** [comment]
This is already a built-in [utility type](https://www.typescriptlang.org/docs/handbook/utility-types.html#thisparametertypetype): `ThisParameterType`

**Comment by papb** [comment]
Wow :facepalm: Really sorry for the noise!!
