### ISSUE TITLE
Add CLI Flag to List all the Source Files and Libs Needed for a Compilation Session

### ISSUE THREAD

**Issue by jginsburgn** [microsoft/TypeScript#41074]
## Search Terms

show, used, files, libs, compile, session

## Suggestion

Add a flag to `tsc`/`typescript` to display all the files and libs needed by a compiler session, which could be dry runned. Also, their interdependence could be displayed to enable users to more easily achieve the use cases described below.

## Use Cases

* Finding the file responsible for declaring a type.
* Ensuring all necessary files exist in a target system used for compilation.

## Examples

`typescript --showSources`

Output
```
Libraries:
/.../lib.dom.d.ts
/.../lib.es5.d.ts

Files:
./index.ts
./src/module.a/index.ts: used in ./index.ts, ./src/module.b/foo.ts
./...
.
.
.
```

**Comment by RyanCavanaugh** [comment]
This is `--noEmit --listFiles`

**Comment by jginsburgn** [comment]
Right! `--explainListFiles` will add the missing feature of revealing the references!
