### ISSUE TITLE
Autocomplete 'duplicates' path when typing part of the path and then autocomplete

### ISSUE THREAD

**Issue by StefanKoenen** [microsoft/TypeScript#41088]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.3

**Search Terms**
- Suggestion / suggest / intellisense
- paths

---

- VSCode Version: 1.49
- OS Version: W10 - up to date

Steps to Reproduce:

1. Create a new typescript project (I have used a nrwl nx workspace)
2. Add a new path to the paths object in the tsconfig to map a path to a folder (I created a new nx library) and make sure the path alias is nested (see my video)
3. Try to import from the path, start with typing 2/3 of the path and then press tab to autocomplete
https://sharexx.blob.core.windows.net/sharex/sharex/2020_10_06_11_24_00_7b322a7d-7e30-4a01-afc6-3050399160db.mp4

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment]
Thanks @StefanKoenen!

Here's the completion entry that TS returns in this case:

```
[Trace  - 20:18:07.884] <semantic> Response received: completionInfo (113). Request took 2 ms. Success: true 
Result: {
    "isGlobalCompletion": false,
    "isMemberCompletion": false,
    "isNewIdentifierLocation": true,
    "entries": [
        {
            "name": "@mylibs/mylib2",
            "kind": "directory",
            "kindModifiers": "",
            "sortText": "0"
        },
        {
            "name": "@mylibs/nested/mylib1",
            "kind": "directory",
            "kindModifiers": "",
            "sortText": "0"
        }
    ]
}
[Trace  - 20:18:07.887] <semantic> Sending request: completionEntryDetails (114). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/vscode-108171/apps/demo/src/app/app.module.ts",
    "line": 3,
    "offset": 25,
    "entryNames": [
        "@mylibs/mylib2"
    ]
}
[Trace  - 20:18:07.888] <semantic> Response received: completionEntryDetails (114). Request took 2 ms. Success: true 
Result: [
    {
        "name": "@mylibs/mylib2",
        "kindModifiers": "",
        "kind": "directory",
        "displayParts": [
            {
                "text": "@mylibs/mylib2",
                "kind": "text"
            }
        ]
    }
]
```

Note that there is no replacement range set in these cases so we always insert the full text at the current cursor position

**Comment by ShuiRuTian** [comment]
maybe duplicated? 
https://github.com/microsoft/TypeScript/issues/40572
