### ISSUE TITLE
Object destructuring: don't throw when property exists in any union type and default value is set

### ISSUE THREAD

**Issue by sandrosc** [microsoft/TypeScript#41080]
## Search Terms

- object destructuring default value
- object destructuring default value property does not exist 
- the title of the issue above

## Suggestion

I would remove the following error:
```js
function foo(bar: boolean) {
  return {
    a: 1,
    b: 2,
    ...(bar && { c: 3 }),
  };
}
const { a = 0, c = 0 } = foo(Math.random() < 0.5);
//             ^ TS2339: Property 'c' does not exist on type '{ a: number; b: number; } | { c: number; a: number; b: number; }'.
console.log(a, c); // 1, 0 or 3
```

## Use Cases

We use the pattern above for errors, dynamically adding a helper text when an error exists.
We would then like to do `const { error, helperText = '' } = errorProps(...stuff)`.

As an alternative `const { error, helperText } = errorProps(...stuff)` (no default value) could/should also work (JS just sets it to `undefined` in this case.

## Examples

```js
export const errorProps = (field: FormField<unknown>, errorKey?: string) => {
  const error = field.isDirty && field.errors.length > 0;

  return {
    error: error,
    ...(error && { helperText: i18n.t(errorKey ?? 'common.form.genericField.required') }),
  };
};

// then
const { error, helperText = '' } = errorProps(field, errorKey);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This hasn't been an error since TypeScript 3.8

**Comment by sandrosc** [comment]
thanks 😄 
what a way to find out you're using the wrong version ^^
