### ISSUE TITLE
Unable to infer type, solvable with strange workarounds

### ISSUE THREAD

**Issue by CapsAdmin** [microsoft/TypeScript#41098]
**TypeScript Version:**  
Seems to affect all versions on ts playground

**Search Terms:**
implicitly has type 'any'
strange inference

**Code**

```ts
let key: string | undefined

if (!key) {
	throw ""
}

let value: { [key: string]: { foo: string } } = {}

for (let i = 0; i < 10; i++) {
	const res = value[key]
//            ^^^: 'res' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
	if (res.foo == key) {
		break
	}
}
```

**Expected behavior:**
`res` should be inferred to {foo: string} inside the loop

If you remove the use of `key` from the if expression inside the loop or define key as a javascript string without throw at the top it will work.

See playground link for 2 working cases with strange workarounds.

**Playground Link:** https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAMQIYwDYGFUGcCmAFAJSIDeAsAFACQG+UiA1vgJ4BciuUATjGAHNEAH0TgAJvmD9846jRjBEhAIQtWpKAAsecAO6IARIerz6jAG6oMIfJzKIA2us7c+ggLr3EwOHFe8-EIAvoihALzkwaa0vjzK5ogwiJEADADcSYgAPIgAjBlJANRFpJS0NBAI3Ig8+LgpiFY2+M5sHjE0CkqEdbgAdL5wKZHqZfJdAEZ1qEwT0bQLC9SgkLAIiADqcDxMQTgEeSTkZgzMbI3G1AD014iIAHpPzy9PnYnNtt5tHFyBnt4hgF3CEwo0yMtYjsEmdkmlMslcgUESVxhUqmAan1Gp9WuoOlQJoplH1Bn4RucNCcKjRpvhZvN5EsYqtoPAkNtdvs8PgAEzHcp0M4uP4gkRiMCSaRgWTyYmqMaIbS6AxXQm0D7WL7kJwitxBLw6oGioJgiJRTpxGGMOGIQqI-L21HUroYrH1HFavHtTrdEn1MnDcKRQx4cTAQxo273GOxuPxx6vCa0mZzCoLGhLIA

**Comment by RyanCavanaugh** [comment]
This is a circularity because the condition inside the `if` could change what type `key` could have on the second iteration of the loop.

**Comment by CapsAdmin** [comment]
Not sure if I follow, how can that happen? Can you illustrate with an example?

One thing about eliminating falsy values from the set with throw, I would think 
```ts
let val: string | undefined
if (!val) return
let x = val << should be string
```
and
```ts
let val: string
let x = val << should be string
```

are identical from `x`'s point of view, how does changing this to the latter fix the error?

**Comment by jgbpercy** [comment]
> Not sure if I follow, how can that happen? Can you illustrate with an example?

Super contrived example, but like this: https://www.typescriptlang.org/play?#code/DYUwLgBA1iCeBcEDOYBOBLAdgcwgHwgFdMATEAMyxBIgF4IByAeygYG4AoD9ciACgCEMWAEoIAbw4BIMAAtUTAO4QARCo4BfLqEgA3AIbBCIROIgBtYYhQYcAXVMRyTJtbRZcGiF-ritHAHoAiAAVWXQkCEUmQmAaACMQCEMMbFkwQOCDIxAAOhY6CScXRAYU9DSwBm9OTIgAIUJIOQiITCZIJCYIAFtCAGNZDmzjfKhCyQgpiGxwYqY+ETdbXEnp9eFC4jJKTGpOdfXUcEJUTEYAeVk2pnYOda1-Z1R+HQh0QoAGNneIAB4IABGb7vADUoLEkik-SYmBQEGOkXoIxAljgdnu00xUxhcKYoFywCY2D4DCsjAgoOgcBE2IguK6BKJJIYiNKlIRICQIlqUh4-ERuWc3Vo9GEkOkUnix30UGkjyAA

TypeScript generally (and rightly imo) makes fairly pessimistic assumptions about what might be changed during loop iteration.

**Comment by CapsAdmin** [comment]
@jgbpercy That makes more sense, thanks!

However I don't see how declaring key as `let key = "foo"` works around the error. 

As far as I know 
```ts
let key: string | undefined = ""
if (!key) throw "" // or return
```
and 
```ts
let key: string = ""
```
are identical, but the latter solves the error. In my mind the semantics for the two should be identical so that's why I suspect there's a bug.

We can also work around your example by doing something like

```ts
let arr = []

for (let i = 0; i < 10; i++) {
    const res = value[key]
    
    console.log('key: ' + key)
    console.log('res: ' + res);

    arr.push(res.foo)

	if (key) {
		break
	}
}

let x = arr // x is becomes string[]
```

But maybe I'm in no-goal territory here. I know typescript does not promise to solve all edge cases.

**Comment by jgbpercy** [comment]
> As far as I know
> 
> ```ts
> let key: string | undefined = ""
> if (!key) throw "" // or return
> ```
> 
> and
> 
> ```ts
> let key: string = ""
> ```
> 
> are identical, but the latter solves the error. In my mind the semantics for the two should be identical so that's why I suspect there's a bug.

These aren't identical, at least under strict null checks. In the first case `key` has type `string | undefined`, but _at the specific point in control flow analysis_ after the conditional `throw`, it has a narrowed type `string`. However, it is legal for code that subsequently runs to set back to `undefined` and widen the type again. TypeScript makes the pessimistic assumption that the loop iteration could do this, and my example shows how that would be possible.

If `key`'s original type is just `string`, it's not legal for any code to set it back to `undefined`, so TS can safely assume the loop iteration doesn't do that. Modifying [my example to change the original type](https://www.typescriptlang.org/play?#code/DYUwLgBA1iCeBcEDOYBOBLAdgcwgXggHIB7KQgbgChLRIA3AQ2AFcREBvCAbRgWTSzYAuhwgAzYsUQoMOCAF8F+CO3nUA9OogAVABbokEAO7FmwACYQARiAhMM2XWEqaIjFiAB0pZZwlSie3RHMEIFKhctACFmSDB9Q0xiSCRiCABbZgBjXUp3Vm8oX0oIUohscHFJAAoASmkBOXYSstbeZWZMcxAxLBBzKlbW1HBmVEwiAHldCCSKFtK1NUoJVAhq2gh0ZQAGci2IAB4IAEY9rYBqC9qVSgBILOJMFAgRwwJ8kB44IQWIP8ez2IoE8wGI2GqhF4iDCF2gcFqAKeqRBYIhhDeMIgcLetQid3QYnWb08-nwBF4N2adzuVhGDCg9yWQA) of `key` shows how the TS compile error moves to the point where we assign `key` = `undefined`.

Hope this helps!

**Comment by jgbpercy** [comment]
As a simpler example of what I mean, this is legal:
```
let key: string | undefined = 'ok';

if (key === undefined) {
    throw "";
}

console.log(key); // Here key type is string

key = Math.random() > 0.5 ? 'Now key type will be widened to string | undefined again' : undefined;

console.log(key);
```

**Comment by CapsAdmin** [comment]
Yeah this makes sense now. Thanks for the explanation.
