### ISSUE TITLE
A function whose declared type is neither 'void' nor 'any' must return a value.

### ISSUE THREAD

**Issue by swing-hh** [microsoft/TypeScript#41108]
```
 onShareAppMessage() {
    const lastfrom: string = app.globalData.lastfrom
    let lastfromParam: string = ''
    lastfrom === 'fxxqy' ? (lastfromParam = 'fxxqy_share') : (lastfromParam = 'fxxqy')

    return {
      title: this.shareObj.title,
      path: path
    }
  }
```
Use the ternary operation before return，This error occurred

**Comment by swing-hh** [comment]
This is a bug in the eslint rule + ts，Add at the end ; can solve the problem

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will make the work for the TypeScript team much easier. :-)

**Comment by RyanCavanaugh** [comment]
I can't tell what's going on here. Please follow the template.
