### ISSUE TITLE
[TS 4.1] Type-level String Accumulation Error In Recursive Type

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#41111]
**TypeScript Version:**  4.1.0-dev.20201014

**Search Terms:** recursive, type, string, literal, accumulation, reducer, token, split

I'm trying to create a mini type-level lexer, that deals solely with a sequence of GraphQL directives. Aka., the following are all valid:

```gql
@aaa
```

```gql
@bbb(some: "arg")
```

```gql
@ccc(some: "arg", and: "another")
```

```gql
@aaa @bbb(some: "arg") @ccc(some: "arg", and: "another")
```

Taking the last example, here's the type-level structure that I'm trying to compute.

```
{
    kind: never;
    value: "";
    next: {
        kind: "DIRECTIVE";
        value: "aaa ";
        next: {
            kind: "DIRECTIVE";
            value: "bbb";
            next: {
                kind: "ARGUMENT_START";
                value: "some: \"arg\"";
                next: {
                    kind: "ARGUMENT_END";
                    value: " ";
                    next: {
                        kind: "DIRECTIVE";
                        value: "ccc";
                        next: {
                          kind: "ARGUMENT_START";
                          value: "some: \"arg\", and: \"another\"";
                          next: undefined;
                        };
                    };
                };
            };
        };
    };
}
```

The generic type should be able to build such a structure––without provoking the excessive depth error––via tail calls.

**Code**

First we define the token type, along with a widened type, `Token.Any` (for the constraint of `Next`).

```ts
interface Token<
  Kind extends string,
  Value extends string,
  Next extends Token.Any | undefined
> {
  kind: Kind;
  value: Value;
  next: Next;
}

namespace Token {
  export type Any = Token<string, string, Token.Any | undefined, any>;
}
```

Next we define our recursive type.

```ts
type Tokenize<
  Src extends string,
  KindByDelimiter extends Record<string, string>,
  Acc extends string = "",
  LastDelimiter extends keyof KindByDelimiter = never
> =
  Src extends `${infer C0}${infer CRest}`
    ? C0 extends keyof KindByDelimiter
      ? Token<
          KindByDelimiter[LastDelimiter],
          Acc,
          Tokenize<CRest, KindByDelimiter, "", C0>
        >
      : Tokenize<CRest, KindByDelimiter, `${Acc}${C0}`, LastDelimiter>
    : undefined;
```

This `Tokenize` type checks whether the character at position `0` of `Src` is a subtype of a delimiting character (`keyof KindByDelimiter`). If so, then we've hit the start of the next token. Therefore we create a token with the kind name and accumulator, and then tail-call `Tokenize` with `C0` as the new `LastDelimiter`. In the case that `C0` is not a delimiting char, we progress down the string (adding `C0` to the accumulator (`Acc`), passing `CRest` in as `Src`, and leaving `LastDelimiter` as is). If we've hit an empty string, we return undefined.

**Result:**

The final argument sequence does not evaluate to the expected token. Instead, we get `any`. I could well be missing something (in which case I apologies for an issue better suited for StackOverflow)... although I believe this to be a bug.

**[Here is the playground Link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201014#code/JYOwLgpgTgZghgYwgAgCoHsDWEQB4BQyyA0qACbIQAekIZAzsvWFKAOYA0hyAanADYBXFNVoMmLdlyIA5UZRo5xGbCAB0AQRABPZAB9kguhBigIZacgAiEAEaC2yALzI4O-AD5kAb26ZyAFwk5ADc3ABuAsJBfEIQYUQgokFyNGEAvvj4IHAAthD0AA6IKCo4PtzUhehQYMhg2oUoWrouZXjMrCCcEl097Zo6+obGpklkHhlZDU1oWDjAAF4QBEQAylAICmKMnVLcpHQAQto2-MC5wJBQ20qMAEoQCDVkuHvdHL3sHpYaCFuiO5fbrOZAAIjBlgAMnBmGcLldoLc6IxsNp0DBgsdThBzpdrqCkuFoJ5nNwNgDFCjkAADAAk3lAMCRAGEAAzpBlM1mPZjpGncIgAfmQ7OR4jRGKxZBO8PxJKIiuQIvaqyV6sOMpxeMRUAA2jC4biEdcALqWdWKv4IC2WuaqJYrFm8sCfTWy43yqCfCGfdkeQXqgOWoLtR24Z0FV3Sj0666fenea2c7zs-mfQ1gOW64OKoJGMgmMxkML4GYoABi-DgYFouAAGl4XPXxYx0LYAFZPOoi7x64jIUDISWY+umoJVmt1+v900edLIIL1sLl5C8wT8OouSe1nBqsPLNVEGkAATg5+QJ9s14AFPR0PkgmC4FA2GCAJSX-4IO8PiBPl830+NwyAAkB0DAAALaAPxpW1fEtMETzBJ8rAASXuABRFlUDQnhMLBBJ1TBG8UPBDR7gAcQAVQAWUwmRUAAfTWVAKNQQjAyID8yLBCiaPoximIYqxOKVTIiA8PUwSSGgwVNaTZLAeTPDCIA)**

Any suggestions as to a better approach would be greatly appreciated, although I understand you likely have higher priorities. Thank you!

**Comment by jcalz** [comment]
It might be helpful to pare this down to a more minimal reproduction so that extraneous details don't distract from the underlying issue.  For example:

```ts
type IterateNoOp<T extends string> =
  T extends `${infer C0}${infer CRest}` ? `${C0}${IterateNoOp<CRest>}` : "";
type Wrapped<T extends string> = { wrapped: IterateNoOp<T> };

type NotTooLong = "abcdefghij";
type Fine = IterateNoOp<NotTooLong>; // type Fine = "abcdefghij"
type AlsoFine = Wrapped<NotTooLong> // type AlsoFine = { wrapped: "abcdefghij"; } 

type TooLong = "abcdefghijklmnopqrstuvwxyz";

type Err = IterateNoOp<TooLong>; // error!
// ------> ~~~~~~~~~~~~~~~~~~~~
// Type instantiation is excessively deep and possibly infinite
// type Err = `abcdefghijklmnopqrstuvwx${any}${any}`

type NoErr = Wrapped<TooLong>; // no error, but still:
// type NoErr = { wrapped: `abcdefghijklmnopqrstuvwx${any}${any}`; }
```

[Playground link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201014#code/C4TwDgpgBAksECcCG8ByB7A8mAPAFSggA94A7AEwGcpLgEBLUgcwD4oBeAKCigOLKpQABgBIA3owBmiKAGEADAF9xUmbIBKEWoqFQA-MPELlYuIhQQM2HBq3AWOqAC4oAIlcBuTqEhQA6shgkOT4hCQQFNS0DMxs7FBiUADugcEuZshoWLh4bIqc3uDQGMB46OgAMujMHG5IAEYAxuQQkkwAFvQAVp6FvgBijNDxGRZWuCVlldWsXgD0c1A+0IOkw3VNLW2dPX3QAIIANpToq+sBSEEQIZPlVbGcC0tFUEcnZ7WJKZdpG82tHW6nigiigBWWvDuM1qrga-223QA1ocALakdBgACOCFoAFcAG5JIggABevQhAFEEAhaqMstYpvdZlAnogEOgEABCR6LAC0-IFbAAfiLRWLxeKebwXoxaEhSMB6Ch6NUoPRqMRGlpKPR8RBDiAoC0IGAoPLyFAwOhKDr6ga1aRJIx6PApZTqbUhHCtoCusi0RjsXjCURxPKQCZwzpwS8MFSafELlcQoyZiwPCzFujCNSOQAaKD1XHAGiKw6HJxu2PoeOfZKpa4uL2bAE7f3orE44AEolh0gRvsRoQZ-JAA)

Here all `IterateNoOp` does is return the same string you pass in, but it does it by recursively iterating over each character in the string.  There is a rather shallow recursion limit, which the 26-character `TooLong` hits.  If you try to use `IterateNoOp` *directly* on `TooLong`, you get a recursion limit error, and you can see that the actual type of `Err` gets those "I give up" `any` types from the compiler.  When you use `IterateNoOp` *indirectly* by wrapping it, this apparently does *not* cause the compiler error, but the types are evaluated the same way.

I haven't checked yet but I'm sure both of these are known issues.  The TS4.1 template literal stuff does tend to slam into recursion limits really easily, so hopefully there will be some way to address this soon.

**Comment by harrysolovay** [comment]
@jcalz thank you for this spectacular explanation and references. You're always incredibly helpful & I appreciate you!

**Comment by tjjfvi** [comment]
You can circumvent this by using HKTs.

```ts
type Access<T, U> = T[Extract<U, keyof T>]

interface GeneratorHKT<I, O> {
  _I: I,
  _O: O,
  input: I,
  _next: IteratorResult<I, O>
  next: IteratorResult<I, O>,
}

type CallGenHKT<G extends GeneratorHKT<any, any>, I extends G["_I"]> = (G & {input: I})["next"];
type IterateGenHKT<G extends GeneratorHKT<any, any>, N extends any> = N extends { done: true } ? N : CallGenHKT<G, Access<N, "value">>;

// Does 10 iterations
interface CompileGeneratorHKT10<G extends GeneratorHKT<any, any>> extends GeneratorHKT<G["_I"], G["_O"]> {
  next: IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IterateGenHKT<G, IteratorYieldResult<this["input"]>>>>>>>>>>>,
}

// Does 1000 iterations
interface CompileGeneratorHKT1000<G extends GeneratorHKT<any, any>> extends CompileGeneratorHKT10<CompileGeneratorHKT10<CompileGeneratorHKT10<G>>> {

}

interface IterateNoOpGenHKT extends GeneratorHKT<[acc: string, i: string], string> {
  next: (
    this["input"][1] extends `${infer C0}${infer CRest}`
      ? IteratorYieldResult<[`${this["input"][0]}${C0}`, CRest]>
      : IteratorReturnResult<this["input"][0]>
  )
}

// If we use normal property accessing (`A[B]`), it needs to check that `B` is assignable to `keyof A`,
// which causes excessively deep. Instead, we use `Access<A, B>`, which circumvents this.
// Strangely, if we make this alias generic intead of assuming `IterateNoOpGenHKT`, it
// throws excessively deep. I am unsure what the cause of this is, but I assume it is related.
type IterateNoOp<T extends string> = Access<IterateGenHKT<CompileGeneratorHKT1000<IterateNoOpGenHKT>, { done: false, value: ["", T] }>, "value">;

type NotTooLong = "abcdefghij";
type Fine = IterateNoOp<NotTooLong>;
// type Fine = "abcdefghij"

type LongerButStillFine = "abcdefghijklmnopqrstuvwxyz";
type StillFine = IterateNoOp<LongerButStillFine>;
// type StillFine = "abcdefghijklmnopqrstuvwxyz"

type SuperLong = "999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars 999 chars"
type StllStillFine = IterateNoOp<SuperLong>;
// type StillStillFine = "999 chars 999 chars..."
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201014#code/FAFwngDgpgBAggYwVAzigPAFQDQwKoB8MAvDJgNoCiAHiAE4CGCI6euA1lGAPYBmZBALrBgASwB2IKHV5NYAcSjjpDENzoAJANKZ0ASVwB5IgG9gMGAH09ALhgHzVw3cPZHEiAFcQdhxcvKtL5SjGp0AEqongA2LAYwxo6BPvYhquqRKDFxRgRuAL4i4NAwAMIM0dGK4tq68jBQtEoAJigw1SphtegM4mC4vWB59g1N4q3t5ABE1lOCRKQAFPUAZDAmHt6++QCU08lzANygkLB6aVLV3fWNUuNtHaHq3YMDfcMAcqN3E4MLMF9bi02iYYM1uMo7PRPLB8jAAPwAmB2cqVK46dDyXCIZBodAfXBTABuFRhUwIBGOwAA9NSYAARbioGAARgADDBRBdRBCUGJJNJZMgytwALYQUTRKCPdKaHTszHfYHtJSdZ4Y14wP5EIH3FXKJ5yurTWaCXDyE2GOamJK3YKdaVKa64c4O9F1F0XR01DFY1Jup2+z0Bn0e-2hb3O8OqSNB6OXQNh10R92Y4MpxNp+PqACaoig0WamWy6BAAAtRChppsQNaKfWG3lgIUaXTGcz2WyOVzOjzxHyJCEhbBSmKJVKZV15V22YrdRNJ+rdJrtUq9aPxZLvWqjQqN+Pt4banux1vF7vZ-J6+sRC3B4K5PGoB9uIYIO61wvVUeMeQmAg7BQegJAAc1wURAOA8QQLNGAgLoUCbQsZI7EWRwLHLStq3ELxa0EcgWUET82gAAwAEg2cReGkMo2XyCiJGougykyEB8hI9CLARbM6DzAsiyiWJ0HIciTEwqsphrOZyDZQR6JMUo6JI3BSlY+ZOIse1DUiEBPDocRiyE8TsNw6TZIIRwdmbERaXsfgAHdYE8FBYHEdRRQqGAIDobhoDocAtSQVAUFAmBFhIuByAAIUEEidnAkAYGUKAJjUGAEDLKAEHYGBy1UGASKikjOTaBg0FEEDxAYAAjKVcu4ArOB4fg4GU1sYHsisMvShhnOZRpcRCokCzAMEoCgCAADp7H7KQGGaXBHJgPqCpxYL0DgXAooIZSOq6st0tEOgEE8UVhskNpxMm9qAGV6F6ECRvAhzYA8zhcorUrolEMqYEeg1RAQTkBXmmA+C1NBTtCkjkxjF833dXauXa8sfPstoBuC0RhuiUbmnGqaRgYUVlv7PTYE6-Ly1gBBepcsH+HEkrcGq7wich0VYC5EqYDoAsY2aa7ijOL14YgLBiLgqCQP+Na8VhhNQ3Qfcz2-WVjxnfRRdfd9E2GUFwUhGBZGiFzcBJaIYTsaYplwTAiPyYZiVJKBySpYWAW4EBMG4bgABkIRAkgYCmGqEHx3gQIrAArKZjg9gAxCRYFIBXnx1-EvZ9-3A8pFHThgJPlGD0PqvDqBI5jqYigLgPoOkKLvDuyVoiLlOQ7DiOo9EaP2GiUU3IgABHOggM8Il7OoMAAC845OEpm8qNvg7TsX0Drx66EbkBF9b5O89sj3d+X0hS-Lyue77gffJHseJ6n2ea4Xzw-I3kuAE5P-SssGFHmBP-ft-X+bQAFAL-qAjKwD-5f0geAmBP84GANgSA+BUCIEIJQUgjB0CsFoNQYgsBmDCE4OIegvBuCCHIJIVQshlDsG0KITQ-BjD6HMOoawihLDyGkLYQw9h3CmGcP4XQgRHCeFCL4ZI3h0iJEyPEfIwRCixGKJUcotRoiNEiK0Vw7RwidH6L0YYqRsiTFKM0QY4xZjdGWNUeYoxcjbHWIceopxpjHEWOcXYmxGDq5HxAJUY+ycV7azfOgG6L9pAbwPnSPxLdAnF1Pt44Bk0UnVyAA)

I was unable to get above 1000 with simple tweaks.
