### ISSUE TITLE
Variable assigned in closure narrowing to wrong type

### ISSUE THREAD

**Issue by bennetthardwick** [microsoft/TypeScript#41113]
**TypeScript Version:**  3.333 -> 4.1.0

**Search Terms:**

- function type interface
- type narrowing callback
- type narrowing captured closure
- type incorrectly narrowing captured closure

**Code**

```ts
function doSomething(callback: () => void) {
  callback();
}

let result: 'foo' | 'bar' = 'bar';

doSomething(() => {
    result = 'foo';
})

// This should work, but fails because type is always "bar"
if (result === 'foo') {

}
```

**Expected behavior:**

It compiles.

**Actual behavior:**

Compiler error:
```
This condition will always return 'false' since the types '"foo"' and '"bar"' have no overlap.
```

**Playground Link:** 

https://www.typescriptlang.org/play?ts=4.0.2#code/GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmAFBAIYA2lARuRANYBciJAlIgLwB8iAbnBjIOAbwBQiRBWp1G7ANxiAvmLGVciAE7YAziEpQWAcmBw4RxAB9ERupoucbdo4rGoMOfIVLsuvcZKS2noGXDam5opKbKoA9LGIACoEOog6eHD6yIgA7nCaDIh42NoAhGIwwKzB+lBcnI4mZkaiqkpAA

**Related Issues:** 

Possibly #9998?

**Comment by MartinJohns** [comment]
Duplicate of #9998. It's literally the first example.

**Comment by bennetthardwick** [comment]
> Duplicate of #9998. It's literally the first example.

Ahh yep. @MartinJohns is that the canonical issue for tracking this bug? It's got a "discussion" label and no progress seems to have been made.

**Comment by MartinJohns** [comment]
> is that the canonical issue for tracking this bug?

I'd say yes. Every other of the many many many many many many duplicates have been closed in favor of it already.

**Comment by bennetthardwick** [comment]
Thanks! Any word on whether this and the many many many many many many duplicates will get fixed?

**Comment by MartinJohns** [comment]
Unlikely, due to the reasons explained in #9998.
