### ISSUE TITLE
Type Inference in Mapped Arrays Functions Incorrectly

### ISSUE THREAD

**Issue by mjkaufer** [microsoft/TypeScript#41129]
**TypeScript Version:**  4.0.2

**Search Terms:** Array Type Inference

**Code**
[TS playground here, pasted below for posterity](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDeAoK6oEMBcUDOwATgJYB2A5gNxoYD0tUAkgGZQDu0mAJl1qSFh7FgxAPalMAGyjNiESVzwAadtDwALUQFcFUchGBQQ8yRF6ZgKAL7UU9KAGFMeaAGIAjCgDG4glAAeuHCIqBhYuADk6iaiEUo06PYAKurEeFAQhISihOnOGf6QXsBmCVAARpFsOQpx1ih2DIAy5I7ObgBMKMxapMVipFAAtpgA1hAAglkAFCC4BCQUANoAugCUQSvIZYQGWoQDIAB0w2BTmAgAfFBToWEYmPF3dAwpafiaOryZ2YQq5VqGYRQLiiCB4UgRYAAQjKYUqUCixDqYSsq1W1CsDXsThcUFcAGYuj0+uIhqMIABlMjkUxnOZEanrWBbMI7YB7Aa3J4PWHPKCvdLfHJ5QWFCDFMwqLhgsDCaBkZjfalQYDRKBsjkq8DygbnPDEQbESSYQgyZypUnAURQLxtPGdJ7oeGI5EYTGYxqtXGuAAsRN6IlJwzGFMwismhBm9IW5BWTJgmy56t2+yMx0wp3O8CuSbCPlIfi4FhwzJCvO5j0dYWSqUFWWFWFFRRKXHLd2dqVdTxsDSrGtTReAmGoKPR9U9LCYEUGBTAkmIXiBbGE6mZVuBEFkpGg8O3ADdMiolzkRsoKgCmO9tAoIYZ1JgDyrrSCVffDNgAApAA)

```ts
type X = {
    a: string;
    // If we add any additional fields, we should get yelled at
};

// Case #1
const x: X = {
    a: 'hello',
    // This errors as expected
    b: 'world',
}

// ❌ Case #2
function makeArr(y: string[]): X[] {
    return y.map(a => ({
        a,
        // This should error, but it doesn't!
        b: 'hi',
    }));
}

// Case #3
function makeSingle(a: string): X {
    return {
        a,
        // This errors as expected, despite inferring the return type in a similar fashion to case #2
        b: 'hi',
    }
}

// Case #4
function makeSafeArr(y: string[]): X[] {
    return y.map(a => {
        const data: X = {
            a,
            // This errors as expected
            b: 'hi',
        };

        return data;
    });
}

// If I'm explicit with X to define b: never, it works, but I shouldn't have to do that :P
```

**Expected behavior:**
Case #2 should throw a type error, since the `b` field is not a valid property on type `X`. If the function's signature expects a `X[]`, and gets some array of outputs not mappable to `X`, it shouldn't compile successfully

**Actual behavior:**
The map in Case #2 (see code / playground) is considered a valid instance of `X` / `X[]`

**Playground Link:** [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDeAoK6oEMBcUDOwATgJYB2A5gNxoYD0tUAkgGZQDu0mAJl1qSFh7FgxAPalMAGyjNiESVzwAadtDwALUQFcFUchGBQQ8yRF6ZgKAL7UU9KAGFMeaAGIAjCgDG4glAAeuHCIqBhYuADk6iaiEUo06PYAKurEeFAQhISihOnOGf6QXsBmCVAARpFsOQpx1ih2DIAy5I7ObgBMKMxapMVipFAAtpgA1hAAglkAFCC4BCQUANoAugCUQSvIZYQGWoQDIAB0w2BTmAgAfFBToWEYmPF3dAwpafiaOryZ2YQq5VqGYRQLiiCB4UgRYAAQjKYUqUCixDqYSsq1W1CsDXsThcUFcAGYuj0+uIhqMIABlMjkUxnOZEanrWBbMI7YB7Aa3J4PWHPKCvdLfHJ5QWFCDFMwqLhgsDCaBkZjfalQYDRKBsjkq8DygbnPDEQbESSYQgyZypUnAURQLxtPGdJ7oeGI5EYTGYxqtXGuAAsRN6IlJwzGFMwismhBm9IW5BWTJgmy56t2+yMx0wp3O8CuSbCPlIfi4FhwzJCvO5j0dYWSqUFWWFWFFRRKXHLd2dqVdTxsDSrGtTReAmGoKPR9U9LCYEUGBTAkmIXiBbGE6mZVuBEFkpGg8O3ADdMiolzkRsoKgCmO9tAoIYZ1JgDyrrSCVffDNgAApAA)

**Related Issues:** N/A

**Comment by MartinJohns** [comment]
Because you didn't specify the return type of your function it will be inferred. No excess property checks happen here. The inferred type is then checked for compatibility with `X`, and it's compatible.

When you specify the expected type it works as you expect:

    y.map((a): X => ({ ... })

**Comment by RyanCavanaugh** [comment]
@MartinJohns any interest in writing a FAQ entry for "Excess properties are not a reason to reject a type assignment" ?
