### ISSUE TITLE
Array type broken when it contains a class instance

### ISSUE THREAD

**Issue by razzp** [microsoft/TypeScript#41131]
**Expected behavior:**
I'd expect the array `[1, 'two', new MyClass()]` to have a type of `(string | number | MyClass)[]`.

**Actual behavior:**
The type of the array is `MyClass[]`. Omitting the class instance yields, as expected, `(string | number)[]`;

Am I missing something or is this broken?

**Playground Link:** 
https://www.typescriptlang.org/play?ssl=6&ssc=16&pln=6&pc=26#code/MYGwhgzhAECyCeBhcVoG9oF8BQ3gHsA7CAF2hIFNSBGaAXmgG1qAaaAchIHd92BdANzYA9MPLwADhXwAzclRK0GAClIAnAJaEA5tAA+0QgFcAtgCMKagJSM+uAsTKVSAJnpNWHbrzaEKXOCQUCGUrQRExAFEADylgSgATAC5xKVl5V3dVEk0dfUNTCzV8hGRICBs7UWgAQXijMBAU6FTpOWcSNwZS4NsgA

**Comment by MartinJohns** [comment]
[Why do these empty classes behave strangely?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely)

**Comment by razzp** [comment]
Scrolled right past it! My apologies and thanks for the help.
