### ISSUE TITLE
Type map inference regression

### ISSUE THREAD

**Issue by mrgleba** [microsoft/TypeScript#41137]
**TypeScript Version:**  
4.1.0-dev.20201016
4.0.3

**Search Terms:** type map inference 

**Code**

```ts
// override types in A by types in B
type X<A, B> = {
    [I in keyof (A & B)]: I extends keyof B ? B[I] : I extends keyof A ? A[I] : never
}

// method adding elements from B to A
var zz = <A extends {}, B extends {}>(a: A, b: B): X<A, B> => {
    return undefined as any
}

zz({ a: 1}, { a: 7 }).a //number
zz({ a: 1}, { a: "foo" }).a //string
zz({ a: 1}, { a: false }).a // Property „a” does not exist in type „X<{ a: number; }, { a: boolean; }>”.ts(2339)
zz({ a: 1}, { a: undefined }).a // Property „a” does not exist in type „X<{ a: number; }, { a: boolean; }>”.ts(2339)
zz({ a: 1}, { a: null }).a // Property „a” does not exist in type „X<{ a: number; }, { a: boolean; }>”.ts(2339)
zz({ a: 1}, { a: true }).a // Property „a” does not exist in type „X<{ a: number; }, { a: boolean; }>”.ts(2339)
``` 

**Expected behavior:**
```ts
zz({ a: 1}, { a: false }).a // boolean
zz({ a: 1}, { a: undefined }).a // undefined
zz({ a: 1}, { a: null }).a // null
zz({ a: 1}, { a: true }).a // true
```

**Actual behavior:**
Property „a” does not exist in type „X<{ a: number; }, { a: boolean; }>”.ts(2339)

**Playground Link:** 
https://www.typescriptlang.org/play?#code/PTAEHsDcFMCdYJYBNqgC4E8AO0DOoEA7UAQVACMN1s8DiAhAKEx1AA0AeEgGlHoD5QAXlABvRqEmgA2gEk6oANbQM4AGagAFGQBkfAJQBdAFyh50AB5pohJPmWqN9UAH4+cw6FPmrNu0pV1UldSDy9QQmgYWEYAX0ZGEFAAW2g0AAtwJFAAQyQkIgBzUGgAG2hUwjR8NVhwZL50cFJGSBzYUAAvTuFQLhLfW3xRWN5nS2shsVj+TRzTHgpTen1TTkWBYUFxKVBYNIBXWGID22g1ImhsnPwcwgw4hO7NUVzTAEZRsTfQAHZQWL6AB0OVAIEIB2S5DgjGer3moE+vHhpgARGpwOBUQDgaCQLg0IhCIVYZ0Xj8kd8EWocqVcKhASCwWAAAp1HCwTCgQB4BDlALgEoCQ4FohHAaAGCAJChYqG5nBREUh0NgAG4AcifuRMeU7mqZnygdVNAAmADMpoAnPpSeSEZSFacUBdItlGXjWey4FzeQKhSKxRKpURqKw5RwFRCoXA9RqEVrwDrCHr+AajWbLda4RSvhGDqVSjimUk2eAOd7+YLhfhReLLJLxcGZTz5T9I8qY1TTPHE8nU7gTearTaFfafoSDgzcczQCWy1QfZX-bWLPXpTRm+HW0ro+rOxRtdBdQCU4b++mrUA

**Related Issues:** 
This is a regression between versions 3.8.3 and 3.9.2

**Comment by RyanCavanaugh** [comment]
The straightforward way to write this is 
```ts
type X<A, B> = B & {
    [I in Exclude<keyof A, keyof B>]: A[I];
}
```
Or if you want to not introduce properties from B then write
```ts
type X<A, B> = Pick<B, (keyof A) & (keyof B)> & {
    [I in Exclude<keyof A, keyof B>]: A[I];
}
```

If this changed two versions ago with no other complaint I don't think this is indicative of a defect
