### ISSUE TITLE
Keyof mapped with `as` type resolving to never

### ISSUE THREAD

**Issue by KieranKaelin** [microsoft/TypeScript#41133]
**TypeScript Version:**  v4.1.0-dev.20201015 

**Search Terms:** mapped as, mapped, mapped keyof

**Code**

```ts
// Interfaces for testing purposes

interface Car {
  name: string;
  seats: number;
  engine: Engine;
  wheels: Wheel[];
}

interface Engine {
  manufacturer: string;
  horsepower: number;
}

interface Wheel {
  type: "summer" | "winter";
  radius: number;
}

// Type to filter all non-primitives from a type

type Primitive = string | number | boolean;
type OnlyPrimitives<T> = { [K in keyof T as T[K] extends Primitive ? K : never]: T[K] };

let primitiveCar: OnlyPrimitives<Car>; // { name: string; seats: number; }
let keys: keyof OnlyPrimitives<Car>; //  "name" | "seats"

// Type to simply return the keyof of the above type

type KeysOfPrimitives<T> = keyof OnlyPrimitives<T>;

let carKeys: KeysOfPrimitives<Car>; // Never
                                    // This should be "name" | "seats"
```

**Expected behavior:** The type `KeysOfPrimitive` should resolve to `"name" | "seats"`.

**Actual behavior:** The type `KeysOfPrimitive` is `never`.

**Playground Link:** [Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201015#code/PTAEEkDsBcFMCcBmBDAxrAzqRB7eo4NoBLSAc1AAcBXeSnDTAWAChXS4k1ZQBhZfAG9WoUJGQBbWAC5QReKTIBuEXNjJoGWZGoSARghUtRscqRmgAomciwjogO4ALWLAA2W0AHUX7gNoAukYAvqzsMAgo6FY2PMLGoBLIOlHQtAiy8or2oE54jPQOGWK6BvAhYSwckdzevm6g8aLQAJ6UFgBEGLpS8B2gAD6gHQ7VfTnwyAAmxNSeOvqGrKFsLCCgACptPNA42MRunKDIbg2QOJAAtJQKEsQkAG6Y2PA4EscE25Wt7aAACrd7sQnqAALxyaAKciDEqLfBDPQ4HBudSQIw-HgAeUgbhaAOId0emAAPBsAHxgxqgPwAaVApFAAGtYC0cIhNscsBtaQFQLAAB5wSBTLD4wnAngAflAdO0sCe8ACsm5NN5wSMrBR0CogKJ-HgsmxuLFQKeGGJ+rJSlA60EYkkFiy5GtjA081KhlAKy1TJZnmZrPZRrxuol5st1vWw3EUn6Qy66k0HUq6y2v12cgJlFxoHgsDS8EgBBcvsDoDZxZ4yERIIx322Mr9mMQJqJ5vJlIDFeDrbDpKtlR9qAENL9slHLQwzd7ZotAitNrAADl5QhVKIN5ut9udzvU05iFgMHlqG4pqADNGHXHhq6k6wgA)

**Comment by RyanCavanaugh** [comment]
Nice repro, thanks!

**Comment by ahejlsberg** [comment]
This is another manifestation of the issue in #40833. Ordinarily we reduce a `keyof M` where `M` is a mapped type `{ [P in K as N<P>]: X }` to simply `N<K>`. This however presumes that `N` is distributes over union types, i.e. that `N<A | B | C>` is equivalent to `N<A> | N<B> | N<C>`. That presumption is generally true, except when `N` is a non-distributive conditional type or an instantiable type with non-distributive conditional type as a constituent. In those cases, we cannot reduce `keyof M` and need to preserve it as is.
