### ISSUE TITLE
JSX result type

### ISSUE THREAD

**Issue by entropitor** [microsoft/TypeScript#41130]
# Search Terms

"JSX result type"

## Suggestion

The documentation explicitly mentions that JSX calls should be treated as a black box and you cannot inspect them (https://www.typescriptlang.org/docs/handbook/jsx.html#the-jsx-result-type). However, I think this limits the use case of JSX to something like UI frameworks where you don't need the output of those elements. It would be nice if this was not the case and we could type the output of a JSX call

This can be achieved by inferring the type from:
* The jsxFactory function. That way if a certain intrinsic element results in a certain output, the type is refined properly if the jsxFactory function has refined the type properly
* Adding a new utility type in JSX. Right now `IntrinsicElements` only types the arguments to intrinsicElements, it could be cool if we have a variant of that which can become a function / an other utility type to declare the output of the intrinsic element call. These should all be a subtype of JSX.Element off course

## Use Cases

Allow using JSX as first class values instead of only as opaque return values that are really badly typed as they can be anything that JSX.Element can be

E.g. I want to look into using this for writing terraform configs

## Examples
https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/PQKgBAUAAgVgzgDzAYwE4FMCGAXdBRAG3QFt0A7baeBAMVUwHMwAzeh0iiMEYCAE3TICmDCwCuZZNgCWAezIoMOfEQ7YAFFzDYAngAd0ALjAAiPrOQBrdKgCSxRuhMAaLXtSy9cAPzGAIhbWqAB09o4ACh5ermBgwfHIABbSBHwYZMZk6ABuNgDaALoQAJT+gTahDgwqJOTYANz8gsKizBJScgpoWLiEtRSasboGxmblqADC8tiY0lmoLm5RPmVWFVMUs-ORnnAxcQnJqemZOflFpWABayEbM3M2fWqNAkIi6CjycNgsbGrGmDIOhezXeYAYBFkACNMAQwABvLRkTCkOB6TDID4AFRs9GYslQxARWiG+g+AGl0DowABeMDfVBzBiNElgOa4VDMDEfABK6DgsjEqExxNiYrAoHAWMSHw5eIJRORpGCYGl0jg9MSgtSZAA5D8koDqmAMR44BqBHpIToNZgNdIfgB3FJwjDdZTaGVgDACoUinis2LWHTGSnA1kAX1Z7JsXJFAFlZHwxERReKJSApV65Zh8YSwEr0Cq1Rq4FqU3w9QbEkaPqbZOawJbrbb7U6Xd7BEpcJ6Pj7BcKPgH02Bg6GqY1xVHWcMPk86gAeLFgdAIXBkPga4OyZhgABSAGUABqhCiMshwaTIecUPZgcIrtfkTcIiMAPlp97AADI0+LZ8YWKTumY5gGGwGxBGwFRrEhZotyVzjH+bIULGCFhNUOxeI+64vjiqDyoSwR8r6g7IbBKJGPS2Dnsygajug6B6AAMhYsIEDovhgFCsiyEQgIQWAMFirOYAYegACC2A0dIUJiLgGp0nyACOYjSBgfALuJWFwB+v6IiOwgKdgxgMkyglQdGqGcuhVQ1Go9GrrhGr4YRxDBDe2ALmMNziS4Yl2VJMlyQpH7wtO4oxjZIp3FsNg6Thz4ubiuYKsR-IDiKBnptIdmmTJZB0SOhb5bRgmxHoBLYHAxgSQRmA6Au8IoRyyIEJkYjEFCNj1IlqBtR1XU2EJb7lQxTGscg7GccYPF8VgZAWTOZJgLFDyoEFjIhfyn4qWpGlaXZOl6eRj4OlMAiDd1qAWYJUVxh8a3zJ5jlPhuyX1Xm7med55g3E9Nj+QDG3SVt8n8mFwnCXB6IioeR7IcAwAtWhIqeYl72ITclSOOj4WskjKPRXOqh1BjL7XEEwTA3jwmxIT90IejTlJVjVPiZ5zhs+s0xxageME8jpIjKYf1BH5YAAD6i+MwMmIJhN09oK3o3SlMVBzpMUFL3O3Lz62eYJomeRMwiNnSWS5DdEBWRyD1iWecyXsgm2yeDGos5jrmpURibJqm+O26jHy2I7F5Xp5GrZeKYs2OJqzs0dyxjbHkz6-MCc85s606UtkEQNOq6VagPwCFyKY-G0kgyPIYDxls6jFGmhNYitU3fEyYCOgSlhwFohPIF8PyFXMCDiZ+gwSkLYALqn4-BjSJgj2QY92SYBaUYvy8IIYRn8tg6-WBNbEEBxNLwlyBBwOgEYSm+-fI03dq6zj1SGzb9PIwAqpehWKD09kybIhkLkDiXce590-p8C8pdxjjzpO6XoWsNA+XFmvLm2VCZBipKMXKjhFhQIoqQYwAADAAJPCPB1QIy72UN8Eh+wsHjRYifDixhL7X0YcjCMxQWRQIAHIKlhPuY8TZZD8irOA1AlgwDqGvh8XEBIUIoHYmAHcYj-rp2Guyc8ztPLFC0IPGBBYGCj3gbI1ks84F2QYjoLepiV4S0LPY0etDjKH0Yiwqap87EX1hNfW+wB76xF4R-Ts2AhQKEnrEBcwT0zwm3uJJWMTU7A3otguxS8HEIDluktkdlz6JLssEPe3xklimcSYCJ2ACTSFhCYPJxdqrnzyHk2I0cRxiiigNMAAAOAADPsTpYoWb9VhMYAZ-TBltKEkM9MBRylBMsUskJjQoxAA
```
  const dockerImage = (
    <dockerImage key="image" name={`${image}:latest`} keepLocally={false} />
  );

  return (
    <>
      {dockerImage}
      <dockerContainer
        key="container"
        // Type error here
        image={dockerImage.latest}
        name={image}
        ports={[
          {
            internal: 80,
            external: 8000,
          },
        ]}
      />
    </>
  );
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Would this be feasible? Do you have pointers to where I can look to potentially implement this myself

**Comment by MartinJohns** [comment]
Sounds like a duplicate of #14729 to me.

**Comment by entropitor** [comment]
Hmmm, I couldn't find it before. It's so sad to see so many others have a similar problem but no solution yet 😭
