### ISSUE TITLE
Conflicting behavior for function return void definitions

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/TypeScript#41138]
**TypeScript Version:**  4.1 beta

**Search Terms:** function return type void

**Code**

```ts
type v = () => void
const f1: v = () => {
  return true
}

function f2 (): void {
  return true 
}
```

**Expected behavior:**

I expect both return statements to return an error; only the `f2` one does.

**Actual behavior:**

`f2` returns `Type 'boolean' is not assignable to type 'void'.(2322)` but `f1` does not.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20201015#code/C4TwDgpgBAblC8UAUBKBA+WB7AlgEwCgBjLAOwGdgoAzARgC5YFk15MBvAqKAJwmACuPUlGA8BEAgF8CBagNJFgOMjQBMLRjFx4onbn0HDR46NKA

**Related Issues:**

I'm certain this has been answered before but I dug through a couple issues and couldn't find the exact answer. I will contribute to the v2 handbook [More on Functions](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/handbook-v2/More%20on%20Functions.md) page too.

**Comment by Ethan-Arrowood** [comment]
Looks like there was a recent discussion on void: https://github.com/microsoft/TypeScript/issues/40969

**Comment by RyanCavanaugh** [comment]
Contextual typing with a return type of `void` doesn't force that functions don't return something. This would make unsuspicious code error:
```ts
const src = [1, 2, 3];
const dst = [0];
// Not a problem, shouldn't be an error
src.forEach(el => dst.push(el));
```

See also https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

Would take a good PR to improve the docs though.

**Comment by Ethan-Arrowood** [comment]
Ahh yes I did come across that FAQ response.

Expanding the example a bit:

```ts
type v = () => void
const f1: v = () => {
  return true // valid
}
const f1b: v = () => true // valid
const f1c: v = function () {
  return true // valid
}

function f2 (): void {
  // @ts-expect-error
  return true 
}

const f3 = function (): void {
  // @ts-expect-error
  return true 
}
```

So like the FAQ says, this goes back to [substitutability](https://github.com/Microsoft/TypeScript/wiki/FAQ#substitutability). What more can we add to documentation on this?

**Comment by Ethan-Arrowood** [comment]
> In other words, if I ask for a fork, a spork is an acceptable substitute because it has the same functions and properties of a fork (three prongs and a handle).

In other words, if I ask for a _void_, _any other type_ is an acceptable substitute because if has the same functions and properties of a _void_ (since void represents the lack of a type)

Whats a better way to say this?

**Comment by Ethan-Arrowood** [comment]
Wow that bot works fast; can we keep this open until I submit a docs update?

**Comment by RyanCavanaugh** [comment]
You can submit a docs update even if this issue is closed

**Comment by Ethan-Arrowood** [comment]
Okay sounds good, I'll get something up by EOW 👍

**Comment by Ethan-Arrowood** [comment]
> Contextual typing with a return type of void doesn't force that functions don't return something.

What would be the best word to describe the other kind of typing? I.e. this:
```ts
function f2 (): void {
  // @ts-expect-error
  return true 
}

const f3 = function (): void {
  // @ts-expect-error
  return true 
}
```
