### ISSUE TITLE
Conditional Type Produces `undefined` Unexpectedly

### ISSUE THREAD

**Issue by m4dc4p** [microsoft/TypeScript#41145]
**TypeScript Version:**  4.0.2

**Search Terms:**
conditional types never keyof required properties

**Expected behavior:**

In the code below, I would expect the type `requiredKeysType1` to be `"name" | "email"`.

**Actual behavior:**
The type of `requiredKeysType1` is actually `"name" | "email" | undefined`. I had to define the `Definable` to filter out `undefined` and I don't understand why. The type `requiredKeysType2` shows usage of that type.

My goal here is to define a const array of the required properties on a given interface for use in a type guard (`isPerson`). I would like the compiler to complain if I remove a key from the `Person` interface and forget to update the array. 

Not implemented here but wished for - I would like the compiler to complain if I add a required property to `Person` and forget to update the array, but I can't figure out how to make that happen.

**Related Issues:**

Didn't find any related issues.

**Code**
```ts
interface Person {
  name: string
  age?: number
  email: string
}

type requiredKeysType1 = keyof RequiredProperties<Person>
// requiredKeys1 = "name" | "email" | undefined
const requiredKeys1: Array<requiredKeysType1> = ["name"]

type requiredKeysType2 = Definable<keyof RequiredProperties<Person>>
// requiredKeys2 = "name" | "email"
const requiredKeys2: ReadonlyArray<requiredKeysType2> = ["name"] as const

function isPerson2(s?: object): s is Person {
    return !! (s && requiredKeys2.every((k) => k in s))
}

/**
 * Remove undefined from the type given (most useful for unions)
 */
type Definable<T> = T extends undefined ? never : T

// Due to https://dev.to/busypeoples/notes-on-typescript-conditional-types-4bh
type RemoveUndefinable<Type> = {
  [Key in keyof Type]: undefined extends Type[Key] ? never : Key
}[keyof Type];

/**
 * Retrieves all the keys for the given object that are required (can't be
 * undefined.)
 */
type RequiredProperties<Type> = { // for some reason, keyof appends an `undefined` value. `Definable` filters that out.
  [Key in RemoveUndefinable<Type>]: Type[Key]
};

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// requiredKeys1 = "name" | "email" | undefined
const requiredKeys1 = ["name"];
// requiredKeys2 = "name" | "email"
const requiredKeys2 = ["name"];
function isPerson2(s) {
    return !!(s && requiredKeys2.every((k) => k in s));
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyyIcAthAFzIZhSgDmRycDEA-NSAK5kBG0ZhDJxgAG2q16IJgF8CBMAE8ADiigQAjt2AaAJgGkISjABVVEAIzIAvMgDWxrDGQAlLTv2ooWNVDDAEBgAPOhQ2CAAfAQA9DHIGtq6EIbGGNZ2AESkFJnIAD7ImcKiYnmF3CB6EDCgKQQIOLQJHsmpJpbUAIJQUHBKwYmeKUYm5mqWkbbIANrZ5BCZALoKymotSfqjZhYATNMAIjWgcHxiEMGOSs5urV4+fgFBoZg4kdFxG8PtGPtZOYsCkUSuJMg0mmAvm1trtqO44HocGIlD0+gMhtC0uMILspnY5gDliwMMhGiBaAoYJUEAEcMhgBgwhFdgAKDCcZBYPgAKwgNIAlJJ6SSmXTCMRiBowNwoLgAIRy5Bs5AAMhVUK2aV2ADoIAA3aBKFks+z82xTez03AYfn8gjyWIAKkdREdtzIWANyEq1VqIBSyBgPjIyDAAAsUGsUAxgAbcCyPc1uBgatwxIGsFBvSBgE07chHTFFBZkEc-adzsFTHjkKZkBAAB6QKokn3Hf16ZDsEj66DIaimBSfA7cSNYZBhsBgFQYShxap67VgLAxPjJiy+c4YGIgLCQDAAWhwB6jGAQ9BUYAPZL0wFppDEJ4sh4ALHww8X1u4PQaAKpVdsKwubEa3FWZRitBwnBcbElmoNs-QDRtmz0ElsRmUYli7HsDSzahRntGYrhuWCAG4h2dV1bjoQIDRJOAxHTcMUCuEkYEzUMI2QGM405Hk+UhcM4EhOANA1AMWQQOAQAAckhAQqIQuo9G1fNC0-FB3E2FJvF8aAnhCEDpjwZBPnYrNsAoFo4AiAAaKDrhcOAVDUFsWFwAADJSOw85A9QY0dtWQDyyxOM4IF82oxEgcJOOEzluDAbVmAw4xIO-T0IH-X0wsrEC4NrCxUqUFZZHIoA)

**Comment by MartinJohns** [comment]
I'm confused. In the title you say it produces `never`, but then you don't mention it anywhere, neither in the actual behavior nor the expected behavior. The code doesn't produce a `never` either. Did you mean to write `undefined` in your title?

**Comment by m4dc4p** [comment]
Sorry about that, you are right. It produces "undefined" unexpectedly.
