### ISSUE TITLE
auto import use "require" to load the module instead of "import"。 

### ISSUE THREAD

**Issue by ForBurning** [microsoft/TypeScript#41144]
When import a module from another file by auto import (step2),
vscode will uses **require()** statements instead of **imports {} from**  (step3). 
I need to convert to an ES6 module manually (step4) .
Is there any way to set  **imports {} from** as a default?  thx!

1. ![111](https://user-images.githubusercontent.com/28643492/95944631-39b4fb00-0e1b-11eb-8eaf-e32b7f177955.png)
1. ![333](https://user-images.githubusercontent.com/28643492/95944835-bea01480-0e1b-11eb-9962-1457d005bde6.png)
1. ![222](https://user-images.githubusercontent.com/28643492/95944752-84367780-0e1b-11eb-8117-1fe1108a85cb.png)
1. ![444](https://user-images.githubusercontent.com/28643492/95945074-530a7700-0e1c-11eb-8163-44a87ddf3001.png)

**Comment by mjbvz** [comment]
I see this in TS 4.0 but can 't reproduce this with TS 4.1-nightly.

Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by RyanCavanaugh** [comment]
Going to assume this has been fixed. Please post repro steps that reproduce the problem on nightly and we can reopen. Thanks!

**Comment by ForBurning** [comment]
> I see this in TS 4.0 but can 't reproduce this with TS 4.1-nightly.
> 
> Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

It works for me. thx a lot!
