### ISSUE TITLE
Redefinable enums

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#41140]
**TypeScript Version:** 4.0.3

**Search Terms:** redefine enum, enum

**Code**

```ts
const enum Foo {
  test = 1
}

const enum Bar {
  test = 1
}

const x: Foo = Foo.test;
const y: Foo = Bar.test;
const z: Foo = 1;
```

**Expected behavior:**

The compiler shouldn't see any errors in that.

**Actual behavior:**

I'm getting this error: "Type 'Bar' is not assignable to type 'Foo'.(2322)"

Now I get that I'm explicitly requiring the value of `y` to be `Foo`, but `Bar` and `Foo` are identical and its trivial to check that, so what's the point of throwing an error here if both would work perfectly fine 100% of the time? This looks doubly wrong to me given that `z` is initialized properly according to the compiler despite its value not coming from `Foo` either.

More practically I'm trying to redefine some enums from some external libraries, to have a tighter control over things (e.g. maybe supporting a subset of the enum), but this error is yelling at me for no good reason.

**Comment by MartinJohns** [comment]
This is intentional. Enums are nominally typed. There was an issue about making them structurally typed, but it got closed: #22373

**Comment by fabiospampinato** [comment]
Why should disallowing people to subset enums be a good idea though?

**Comment by RyanCavanaugh** [comment]
If you want them to be interchangeable, there's already syntax for that
```ts
const Foo = {
  test: 1
} as const;

const Bar = {
  test: 1
} as const;
```

**Comment by fabiospampinato** [comment]
@RyanCavanaugh The thing is I can't mutate one of the two because it is defined in a third-party library, what's the best option to work with that?

**Comment by RyanCavanaugh** [comment]
If you're only in control of the second half, I'd write
```ts
const enum Foo {
  test = 1
}

const Bar = {
  test: Foo.test
} as const;

// OK
const p: Foo = Bar.test;
```

**Comment by fabiospampinato** [comment]
I also have functions that accept arguments of type `Bar`, what do you suggest I replace that with, `(typeof Bar)[keyof typeof Bar]`?

It feels like we are reimplementing enums on top of plain objects here, wouldn't it actually be better if this arbitrary limitation was lifted instead?

**Comment by ilogico** [comment]
Given
```ts
enum Foo { a, b, c }
declare function bar(arg: Bar): void;
```
You can simply use a union:
```ts
type Bar = Foo.a | Foo.b;
// this option forces you to use Foo.a or Foo.b
// I actually prefer this one
```

or
```ts
const Bar = { a: Foo.a, b: Foo.b } as const;
type Bar = (typeof Bar)[keyof typeof Bar];
// this allows using Foo.a, Foo.b, Bar.a or Bar.b
```
IMHO, if the "arbitrary limitation" were lifted, there would be no point in having enums in the language, since they would behave pretty much like union types.

**Comment by ilogico** [comment]
@fabiospampinato, what I meant to say is that if you want to restrict a type to specific values, you can use union types.
Enums were designed to be nominal types. This means you can only use values originating from the initial definition. Numerical or string equivalence is not enough. As stated above, this is by design. If you remove this characteristic, enums become union types and the `enum` keyword would be a non-standard syntax for creating objects.

**Comment by fabiospampinato** [comment]
> This means you can only use values originating from the initial definition. Numerical or string equivalence is not enough.

@ilogico I don't think that's actually correct, because in the snippet I posted in my first post here you can see that it's possible to assign values to variables of type enum even if those values are not coming from the enum themselves:

```ts
const z: Foo = 1;
```

Or even:

```ts
const w: Foo = { foo: 1 }.foo;
```

**Comment by ilogico** [comment]
You're right. I wasn't aware.
