### ISSUE TITLE
Trying to import from folder with correct case name but get: File differs from already included file only in casing

### ISSUE THREAD

**Issue by alexandrehpiva** [microsoft/TypeScript#41148]
> Error TS1149: File name '.../src/packages/admin/components/datatableView.tsx' differs from already included file name '.../src/packages/admin/components/DatatableView.tsx' only in casing. ts(1149)

The thing is that i have a file called '.../src/packages/admin/components/DatatableView.tsx' (with uppercase D) and a folder '.../src/packages/admin/components/datatableView' (with lowercase d) with and index.ts inside and i'm trying to import things from 'packages/admin/components/datatableView/index.ts' using this call:

`import { AssetOne, AssetTwo } from 'packages/admin/components/datatableView';`

It compiles just fine on Linux but throws this error on Windows:

> Cannot find file: 'datatableView.tsx' does not match the corresponding name on disk: '.\src\packages\admin\components\DatatableView.tsx'.

![VSCode import Bug](https://user-images.githubusercontent.com/32683082/96336850-c00a5080-1058-11eb-83f1-da90667d0b8b.png)

I know that if I complete with /index it compiles:

`import { AssetOne, AssetTwo } from 'packages/admin/components/datatableView/index';`

But this isn't a bug in VSCode?

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will make the work for the TypeScript team much easier. :-)

---

This behavior is intentional with `forceConsistentCasingInFileNames` enabled.

You say you want to import from `datatableView/index.ts`, but when running on Windows (case insensitive file system) it will actually import `DatatabeView.tsx`. The compiler error protects you from this mistake.

If you don't care about Windows then you can turn off the compiler option.

**Comment by alexandrehpiva** [comment]
> This behavior is intentional with `forceConsistentCasingInFileNames` enabled.
> 
> You say you want to import from `datatableView/index.ts`, but when running on Windows (case insensitive file system) it will actually import `DatatabeView.tsx`. The compiler error protects you from this mistake.
> 
> If you don't care about Windows then you can turn off the compiler option.


Thanks for your reply!!

Even setting forceConsistentCasingInFileNames to false in tsconfig.json I get the same result.

`{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": false
  }
}`

Am I doing something wrong?

**Comment by alexandrehpiva** [comment]
> This behavior is intentional with `forceConsistentCasingInFileNames` enabled.
> 
> You say you want to import from `datatableView/index.ts`, but when running on Windows (case insensitive file system) it will actually import `DatatabeView.tsx`. The compiler error protects you from this mistake.
> 
> If you don't care about Windows then you can turn off the compiler option.


Thanks for your reply!!

The case is that I'm using Windows and this is the code that my new team made. So, if this code does not work on Windows, I'll have to change to Linux.
I try to set forceConsistentCasingInFileNames to false in tsconfig.json but I get the same error.

`{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": false
  }
}`

Am I doing something wrong or in Windows there is no workaround?

**Comment by MartinJohns** [comment]
> I try to set forceConsistentCasingInFileNames to false in tsconfig.json but I get the same error.

I can't reproduce this. Are you sure you're modifying the right `tsconfig.json`? Did you make sure to reload your VSCode to re-initialize the TypeScript server?

![image](https://user-images.githubusercontent.com/5269069/96348220-89a7f200-10a7-11eb-8315-f0ed7b92d01a.png)

(Note that it's always importing `DatatableView.tsx` regardless of casing, **not** `datatableViewer/index.ts`. This behavior can't be changed.)

**Personally** I would adjust the code structure to avoid this problem in the first place.

**Comment by alexandrehpiva** [comment]
Holy cow! I didn't realize that after the change the error was ESlint's.

![The error was eslint](https://user-images.githubusercontent.com/32683082/96351186-2c547680-1090-11eb-86a4-fbab5fe79b8e.png)

Fix by configuring ESlint but really do not work.

![Fix by configuring eslint but really do not work](https://user-images.githubusercontent.com/32683082/96351197-44c49100-1090-11eb-8d2f-13d81026a963.png)

What you sad really explains everything:

> You say you want to import from `datatableView/index.ts`, but when running on Windows (case insensitive file system) it will actually import `DatatabeView.tsx`. The compiler error protects you from this mistake.

I will follow your recommendation.

> **Personally** I would adjust the code structure to avoid this problem in the first place.

Thanks for your time!
I hope this discussion helps others in similar situations to understand the problem.
