### ISSUE TITLE
Array type should initialize array

### ISSUE THREAD

**Issue by cursorweb** [microsoft/TypeScript#41141]
## Search Terms

Array, Intialization, Type

## Suggestion
When you initialize a variable with a type:
```ts
let myArr: number[];
```

it should automatically make this be:
```ts
let myArr: number[] = [];
```

## Use Cases
This would be useful for implicitly creating an empty array.

## Examples
```ts
let myArr: number[];
myArr.push(1);
console.log(myArr);
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code

It would absolutely be a breaking change when `strictNullChecks` are disabled.

> [x] This feature would agree with the rest of TypeScript's Design Goals.

This would violate goal 7, assuming "all JavaScript code" includes "TypeScript code with erased types". And IMO it would be against the non-goal 7.

**Comment by cursorweb** [comment]
oh oops

**Comment by cursorweb** [comment]
I just thought this was a useful feature, but I guess being explicit doesn't hurt
should I close this?

**Comment by MartinJohns** [comment]
> should I close this?

🤷 I'm not a member of the TypeScript team. But I **highly** doubt they would consider something like this. It hardly brings a real benefit and has several pitfalls.

**Comment by RyanCavanaugh** [comment]
Yeah, not initializing something already has a meaning in JS, and we don't change that.
