### ISSUE TITLE
Infer Object Rest Type

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#41157]
## Search Terms

Infer, object, rest, spread, type, unwrap, fields, exclude

## Suggestion

[This](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDaAiAgigNFFAhLOAwigLpQQAewEAdgCYDOy6BAdOwJY0BmEATlFxp6hMgH5BwuoSgAuKDQgA3fgG4AUEA) works:

```ts
type X = ["A", "B", "C"] extends ["A", ...infer BAndC] ? BAndC : never;
```

[This](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDeBDAXFARAQUwbigCMNMAhfKAYxIGFMBfKCAD2AgDsATAZ2XShTsQAGigA6CQEt2AMwgAnKKWxcajAPxKVnGlAzsIANwV4gA) does not work:

```ts
type X = {a: "A"; b: "B"; c: "C"} extends {a: any, ...infer BAndC} ? BAndC : never;
```

I'm probably not the first to point out this asymmetry, although I was unable to find pertinent issues. Apologies if this is on the roadmap & I'm creating excess noise.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Gerrit0** [comment]
Tuples are special in a lot of ways... objects are, in many ways, easier to work with, this probably doesn't exist because you can already do it (as far back as when conditional types were introduced!)

```ts
type A<T> = T extends { a: any } ? Omit<T, 'a'> : never

type X = A<{a: "A"; b: "B"; c: "C"}>
```

**Comment by harrysolovay** [comment]
@Gerrit0 I never suggested a lack of alternatives for omitting fields. This issue is about symmetry in the language. Not only symmetry with tuple types, but also with runtime code, where it is possible to destructure the rest type from both tuples and objects.

**Comment by MartinJohns** [comment]
"Language symmetry" sounds like a questionable benefit given the additional complexity in various aspects.

**Comment by RyanCavanaugh** [comment]
We generally don't create an additional way of doing something just so the syntaxes line up. `...` was necessary for tuples because removing elements changes the keys and length, but this isn't needed for objects.

**Comment by harrysolovay** [comment]
@RyanCavanaugh that sounds sensible! Thank you for considering.
