### ISSUE TITLE
A private accessibility modifier should be translated to an identifier with the prefix #

### ISSUE THREAD

**Issue by giffeler** [microsoft/TypeScript#41150]
**TypeScript Version:**  4.0.2

**Search Terms:**

accessibility modifier private identifier

**Expected behavior:**

There are two classes **_abc_** and **_def_**. In the first, a property **_x_** is marked as private with an accessibility modifier. In the second, a property **_y_** is also marked as private but with a # prefix. If instances of both classes are converted using **JSON.stringify**, the property is not converted in case of class **_def_** and the property **_y_**. That is the expected behavior. The translation of a property marked as private should take this into account.

```
[LOG]: "{}" 
[LOG]: "{}" 
```
**Actual behavior:**

Although the property **_x_** in class **_abc_** is marked as private, it is converted using **JSON.stringify**.

```
[LOG]: "{"x":"hello"}" 
[LOG]: "{}" 
```

**Related Issues:**

no

**Code**
```ts
class abc {
     private x: string = "hello";
}

class def {
     #y: string = "world";
}

console.log(JSON.stringify(new abc()));
console.log(JSON.stringify(new def()));
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// An accessibility modifier cannot be used with a private identifier.(18010)
var _y;
class abc {
    constructor() {
        this.x = "hello";
    }
}
class def {
    constructor() {
        _y.set(this, "world");
    }
}
_y = new WeakMap();
console.log(JSON.stringify(new abc()));
console.log(JSON.stringify(new def()));
/*
[LOG]: "{"x":"hello"}"
[LOG]: "{}"
*/

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/PTAEEEDtQQwYzgUwM7IJYCM0Bs0BcBPUAWwHsATNAMzUQCdQ4ZJJS9QNFQBXZRc0AHd8AC1igADnTQA3GHi5pyiSHmq06AOgAUARgAcABl2GAlAChzcbDFSwMcUAG9zoN26mz5XAB4AuUGQ8aUgAc1AAXlAAIhFEbGxSaIBucwBfS2tbZFBlKmdXd1AAYgIAoJDwqOjBUjpschT0zNJIZFJsRE1E0O0AKQBlAHkAOU0KtDDqAm1IREF7OG1TFdS4VvbO7tJewdHx4MnQ6dn53MQqZdXLYAAqcwBtABkhgHEAXQDop2ifaL9YvFEtE0tFQI8Xh8vk5QeDbsBzEA)

**Comment by MartinJohns** [comment]
This is intentional and the official plan is to leave the behavior as-is: https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497370201

**Comment by JoseHuertasDev** [comment]
Do you find some workaround @giffeler  ?
