### ISSUE TITLE
TypeScript custom paths to packages are not used by quickfix to suggest imports

### ISSUE THREAD

**Issue by reduckted** [microsoft/TypeScript#41152]
**TypeScript Version:**  
* 4.0.3
* 4.1.0-dev.20201017

**Search Terms:**
package json auto import path mappings quick fix

**Code**

Here's a repo that contains the full setup (there's separate branches for TS 3.9, 4.0 and 4.1):
https://github.com/reduckted/ts-quickfix-path-mappings-bug

Here's an image of the file structure:
![image](https://user-images.githubusercontent.com/10321525/96364749-69e3fd00-117f-11eb-87a3-ff4bb96c62b3.png)

There are two projects, `alpha` and `beta`. At the root there is a common `tsconfig.json` file.

`./tsconfig.json` contains a path mapping of `@test/alpha` to the `alpha` directory:
```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "@test/alpha": ["alpha"]
        }
    }
}
```

`./alpha/package.json` contains a `main` property that points to `src/index.ts`:
```json
{
    "main": "src/index.ts"
}
```

`./beta/src/second.ts` is using  the `First` class, which is defined in `./alpha/src/first.ts` and exported from `alpha/src/index.ts`.
```typescript
export class Second {
    private readonly first!: First;
                             ~~~~~
}
```

The quickfix at the error on `First` is not listing the expected imports.

**Expected behavior:**
The suggested import should be `@test/alpha`.

**Actual behavior:**
The suggested import is `alpha/src`.
![image](https://user-images.githubusercontent.com/10321525/96364791-b4fe1000-117f-11eb-845a-31f6040f53fd.png)

Changing the path mapping to refer directly to `alpha/src` seems to be a workaround, as that results in the suggested imports being `@test/alpha` and `alpha/src/first` (I'm not sure if the second one should actually be listed though).
![image](https://user-images.githubusercontent.com/10321525/96364800-bdeee180-117f-11eb-86a9-88141d455d69.png)

_Additional things to note:_

Manually adding the import from `@test/alpha` results in a successful compilation.

The suggested members to import from `@test/alpha` lists the correct members:
![image](https://user-images.githubusercontent.com/10321525/96364810-cfd08480-117f-11eb-9013-08e01807dd6b.png)

If there is already an import for `@test/alpha`, the quickfix correctly suggests adding to the existing import declaration:
![image](https://user-images.githubusercontent.com/10321525/96364815-d8c15600-117f-11eb-8a57-70712e619ddd.png)

**Playground Link:** 
N/A

**Related Issues:** 
Maybe #15223?

**Comment by andrewbranch** [comment]
Huh, I totally thought that we wouldn’t redirect from a package.json’s `main` field unless we actually discovered it inside a node_modules directory, but I was wrong about that. That means there is a bit of missing logic in module specifier resolution.

**Comment by andrewbranch** [comment]
Will reëvaluate for 4.3, but this might be a wontfix. It adds a lot of overhead to try to do speculative module resolution to come up with nice auto-import paths when there is no reason that users can’t just put the full path to the package entry in their `paths`. Maybe we can issue a suggestion diagnostic for that or something.

**Comment by andrewbranch** [comment]
I don’t think this is going to be worthwhile until/unless the services layer has access to every package.json file we’ve already read, because of wildcard paths. If you have `"@libs/*": ["./packages/*"]`, for example, we can’t eagerly determine whether an import matching this is going to point to a package.json-containing directory, so we’d be left doing file I/O on the fly during auto-imports. This might be possible after all the work around ESM resolution is done, as I think that may expand the package.json info cache and make it accessible on the program. Putting on the backlog for now.

**Comment by reduckted** [comment]
> Changing the path mapping to refer directly to `alpha/src` seems to be a workaround, as that results in the suggested imports being `@test/alpha` and `alpha/src/first` (I'm not sure if the second one should actually be listed though).

This workaround is what I've been using for ages and it works well. It would be nice if `alpha/src/first` didn't show up in the suggestions list, but it's not the first item in the list, so you're unlikely to select it. I've also been using a custom ESLint rule to detect imports like `alpha/src/first`, so this is basically not a problem for me now.
