### ISSUE TITLE
Circular reference error when defining Record type

### ISSUE THREAD

**Issue by jp7837** [microsoft/TypeScript#41164]
**TypeScript Version:**  4.0.2 (and 4.1.0-dev.20201015)

**Search Terms:** circularly, Record

**Code**

```ts
type T1 = { [key: string]: T1 }
type T2 = Record<string, T2>
```

**Expected behavior:**
No compilation errors

**Actual behavior:**
While type T1 compiles properly, type T2 reports `Type alias 'T2' circularly references itself.` even though they are inherently the same type.  This was actually found by autofixing a new @typescript-eslint rule [consistent-indexed-object-style](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-indexed-object-style.md)

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAKgjFAvFA3lA2gawiAXFAZ2ACcBLAOwHMBdfeKAXwFgAoUSWAJiSgCUIAxgHtiAEwA8RMlQA0XAHxA

**Related Issues:** None found

**Comment by RyanCavanaugh** [comment]
Certain circularities are allowed (e.g. T1) but other circularities aren't, e.g.
```ts
type Identity<T> = T;
type T3 = Identity<T3>;
```
Generic instantiation is *deferred*, so at the point TS analyzes `T2`'s declaration, it can't tell if it's in the `Record` case (would be allowed) or the `Identity` case (would not be allowed). It's only later in the process that we could tell that this is actually OK, but if it wasn't OK, it's "too late" to go back and start complaining about it.

**Comment by jp7837** [comment]
@RyanCavanaugh thanks for the explanation.  Not that it's TypeScript team's responsibility, but just as an FYI this may become a more popular issue as teams use the consistent-indexed-object-style rule from @typescript-eslint.  I can file a bug on their project to not auto-fix this case if you think that's a good idea.

**Comment by gbegher** [comment]
@RyanCavanaugh Was there a recent code change related to this?

Earlier today (and for quite some time already), the following worked for me but then I bumped some versions and now it fails.

```
type Product<T> = Record<string, T>

type XX = Product<XX> // <- fails now
```

**Comment by gbegher** [comment]
@RyanCavanaugh 

There seems to be some inconsistent behavior:

```
namespace Fails {
    type Product<T = any> = Record<string, T>;

    type ValueOf<X> = X[keyof X];
    type Sum<Cases extends Product> = ValueOf<SumMapping<Cases>>;
    type SumMapping<Cases extends Product> = {
        // DIFFERENCE IS HERE!
        [cas in keyof Cases]: [type: cas, value: Cases[cas]]
    };

    type Value = Sum<{
        PRODUCT: Product<Value>
    }>
}

namespace Works {
    type Product<T = any> = Record<string, T>;

    type ValueOf<X> = X[keyof X];
    type Sum<Cases extends Product> = ValueOf<SumMapping<Cases>>;
    type SumMapping<Cases extends Product> = {
        // DIFFERENCE IS HERE!
        [cas in keyof Cases]: {
            type: cas;
            value: Cases[cas];
        };
    };

    type Value = Sum<{
        PRODUCT: Product<Value>
    }>
}
```

[Code in playground](https://www.typescriptlang.org/play?ts=4.0.2#code/HYQwtgpgzgDiDGEAEAxEBLANlJBvAUEkUgC4CeMyACgE4D2AJgK7wkA8AKkgLxIjBkAfDyQAlCPDo0GbKCRrpgAcwA0SDoIDc+QsXKUkANRCYmEAPIAzNgA1hvGwG0A1hDJ1LSGwF1txUhTIAMpMYGwAwiBQ0EgQAB4kEMAMOLSMLCT2RiZmVmwhYACyIDAwikoRUdCCWrpE+sGhxaXlldE48YnJqfTMrFkE-v4A9MNIACIAkigoAKKiswBy4bNIk0FIABLzswCEdUOO8FFIikiu7p6R7d4AXEiODffHUGoAbjkQ99fQR1He3gOAF9tAcGtlTMheAU2IMhkQqKJzOMAKrhDj3NJ9djGSGCYH4oE6UCQWAIZAAdSkzhwcPqgSQWIynBE-CEInEkmksnk5TUGlB-nBuNy1jsIicFw8Xl8YIZMJ+HQSSRSjN6GSyIos1gKzTKyja1VqQvlTRK+oqitiyu6avS-REdKGowm0zmC2Wq3WWx2+3hRD+ODOUquVSgdzwB39AUozyifmjxA+kO+YcDsujIOBgr0DK1IhhTv8iORaIxduxbC1+P8QMJ+CAA)

**Comment by gbegher** [comment]
@RyanCavanaugh The behaviour seems a bit inconsistent to me (or at least not very transparent)

In the following example a code change somewhere deep down resulted in a failure.

[Playground link](https://www.typescriptlang.org/play?ts=4.0.2#code/HYQwtgpgzgDiDGEAEB1A9gJwNZSQbwCglikAXATxmQDUQAbAV2QF4kBlBsAHkJL6QAKAJQDyAEQCqAYQAqALkEY0AEwbxSXWowgA+IiQC+e-cQD0ppGIgAzAJbAIypPaQhgaUgAsIGJHboQBCZklMgCSqrqXDJIrG7kOrFIQhDwmMpcUKQY9gDmADRIMjoA3EF8FFRIWkwi1lwAGomsDQDaWBDkaNZIDQC6ZRWh7JxcUiBQ0EgQAB6kEMDKuOEqaqTN1fS19RxgALIgMDB5YxPQOqXBlci7B0cn45O4s-OLyxFrG7z8xK3wE85gEgOl0eo9oH05MEfmYLMpbNZrD4FohnLhvBhAjD+N9sT9rgp-lBBnifgA3LYQBTgqB-CYDaEwgwk4jM8okAgGIKgSCwBDIABiIFsdFwuJCVRqLBG3HFfGE4mk8kUqyiUr0fCM7Nhlhs9kcgNc7i8Pj8IsCV2GK0iGhicWACSSKTSGAyWRywAKRUulsllLqjQ2bRB3V6DKGVV2pye0zmCyWKptGylAduh2Onuj50uEZunDuGdyWeecbeic+STlJDpuBcIbBZygkMZP3MSHhiORwFRtnRyJb-FaBKQRMKFO01MbNb6fWCbK5QA)

```
namespace Works {
    type Value = Sum<{
        PRODUCT: Product<Value>
    }>

    // Defined in another file

    type Product<T = any> = Record<string, T>;

    type ValueOf<X> = X[keyof X];
    type Sum<Cases extends Product> = ValueOf<SumMapping<Cases>>;
    type SumMapping<Cases extends Product> = {
        [cas in keyof Cases]:
            // difference is here
            {
                type: cas;
                value: Cases[cas];
            };
    };

    
}

namespace Fails {
    type Value = Sum<{
        PRODUCT: Product<Value>
    }>

    // Defined in another file

    type Product<T = any> = Record<string, T>;

    type ValueOf<X> = X[keyof X];
    type Sum<Cases extends Product> = ValueOf<SumMapping<Cases>>;
    type SumMapping<Cases extends Product> = {
        [cas in keyof Cases]:
            // difference is here
            [type: cas, value: Cases[cas]]
    };
}
```

**Comment by nscarcella** [comment]
@RyanCavanaugh not sure what's under the hood of `Record`, but it does feel a bit inconsistent that some generics seem to work fine with recursions while others don't:

```typescript
type A<T> = T | Array<A<T>>  // This line works fine
type R = Record<string, R>      // this one doesn't
```

**Comment by jedwards1211** [comment]
> at the point TS analyzes T2's declaration, it can't tell if it's in the Record case (would be allowed) or the Identity case (would not be allowed)

What do you mean by `Identity` case?  `Identity` is only in the example you gave, but OP's example doesn't have an `Identity` type alias so I don't understand what you mean by `Identity` case.

**Comment by jedwards1211** [comment]
I'm also confused why the following would be a problem.  It has a generic type alias so I assume something about "deferred instantiation" would be involved, yet TS doesn't complain:

```ts
type Stuff<T> = {[x: string]: T | Stuff<T>}

const foo: Stuff<number> = {
  a: {
    b: {d: 2}
  }
}
```

**Comment by jedwards1211** [comment]
I guess what you're saying is that a type alias can't reference itself if it's used in a generic type parameter:

```ts
type MyRecord<V> = {[key: string]: V}

type Stuff = MyRecord<string | Stuff> // circular reference error
```

I don't get why this is technically impossible to support though.  Let's say we're checking that `{a: {b: 'c'}}` is of type `Stuff`.

My layperson imagination of how that could work is:
1. Required type gets expanded to `{[key: string]: string | Stuff}`
2. Check that keys of `{a: {b: 'c'}}` are of type `string` (ok)
3. check that values of `{a: {b: 'c'}}` are of type `string | Stuff`
  a. check that `{b: 'c'}` is of type `string | Stuff`
    1. It's obviously not a string, see if it's of type `Stuff`
    2. Required type `Stuff` gets expanded to `{[key: string]: string | Stuff}`
    3. check that keys of `{b: 'c'}` are of type `string` (ok)
    4. check that values of `{b: 'c'}` are of type `string | Stuff`
      a. check that `'c'` is of type `string | Stuff`
      b. `'c'` is of type `string` (ok)

Additionally, Flow supports the `Stuff` type just fine, so it seems perfectly possible.  Or does it lead to other inconsistent behavior in Flow that I'm unaware of?  Or are there some other niche cases in TS that are fundamentally incompatible with supporting the `Stuff` type?

**Comment by jedwards1211** [comment]
To add to what @nscarcella was saying, the way `Array` differs from an ordinary generic type alias is too hazy, because this equivalent type alias doesn't work:

```ts
type MyArray<T> = T[]

type B<T> = T | MyArray<B<T>>
```

**Comment by jedwards1211** [comment]
> It's only later in the process that we could tell that this is actually OK, but if it wasn't OK, it's "too late" to go back and start complaining about it

Does this mean that, with changes, it would be possible to complain about it appropriately, but it would involve a lot of refactoring?

**Comment by jedwards1211** [comment]
Actually, I was wrong about Flow, it fails to produce expected errors on a similar recursive generic type alias:

```js
// @flow
type Record<K, V> = {[K]: V}
type Stuff<T> = Record<string, T | Stuff<T>>
const foo: Stuff<number> = { a: 'not a number' } // should error, but doesn't
```
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagEqYMawBOAJgDwDSANKAGoB8oAvKAN4DaFAugFx0C+KDNgDKyAK6RIZACqMWeQqTIBnZEQCWAOwDmNGaAA+oMZOlz6iQlrWhIsWH1NSyW8QFsARpiLy2oAEM+AHItWGRA0DcvH2DQflAQUBUAC1hxaBJQHyJiGk9xCJJYTBUtYOREIA

Maybe there is something fundamentally hard about supporting such types...I wish I had a more concrete understanding of why

**Comment by RyanCavanaugh** [comment]
Imagine I told you that an integer was a flarpnumber if it was either prime or a flarpnumber. Is 6 a flarpnumber?

**Comment by jedwards1211** [comment]
@RyanCavanaugh I mean obviously that seems undecidable, but I still don't see what it has to do with OP's example of `type T2 = Record<string, T2>`, which seems perfectly decidable?

**Comment by jedwards1211** [comment]
The thing that's frustrating about this is if we define

```ts
type MyRecord<V> = {[key: string]: V}
```

Because of the `=` we'd expect that both sides are truly equivalent and interchangeable.  But this equivalence gets violated when we have

```ts
type T = {[key: string]: T} // okay
```
And try to substitute the RHS with what should be equivalent:
```ts
type T = MyRecord<T> // error, even though this means the same thing
```
So are there other cases where the sides of a type alias aren't equivalent?

**Comment by jp7837** [comment]
BTW, the issue I mentioned with typescript-eslint was fixed (https://github.com/typescript-eslint/typescript-eslint/issues/2687)

**Comment by Pyrolistical** [comment]
@jedwards1211 good point, also what you've described is a workaround for this very issue! 

```ts
type ThisFails = number | Record<string, ThisFails>

type ThisWorks = number | {[key: string]: ThisWorks}
```

[playground](https://www.typescriptlang.org/play?&q=417#code/C4TwDgpgBAKgFgSwM4DECGCA2SoF4oB2ArgLYBGEATlAD5QBKEAxgPaUAmAPEsJQgQHMANLESoM2AHwBYAFBzQkUcgDqbANY58xclVpQA3gG11EEAC4oPPoIC6l+Ko1IAvnLlA)

**Comment by FStefanni** [comment]
Hi,

> @jedwards1211 good point, also what you've described is a workaround for this very issue!
> 
> ```ts
> type ThisFails = number | Record<string, ThisFails>
> 
> type ThisWorks = number | {[key: string]: ThisWorks}
> ```
> 
> [playground](https://www.typescriptlang.org/play?&q=417#code/C4TwDgpgBAKgFgSwM4DECGCA2SoF4oB2ArgLYBGEATlAD5QBKEAxgPaUAmAPEsJQgQHMANLESoM2AHwBYAFBzQkUcgDqbANY58xclVpQA3gG11EEAC4oPPoIC6l+Ko1IAvnLlA)


yes, I was expecting this to work... but it does not :(
I hope in a quick improvement.

Regards

**Comment by yw662** [comment]
This seems work:
```ts
interface ThisWorks extends 
```

**Comment by 1hko** [comment]
Why is it so painful to write recursive programs with TypeScript?

```ts
type texpr =
  | number
  | string
  | Array<texpr>
  | Promise<texpr>
  | Record<string, texpr> // circular reference error 😓
```

```ts
async function evaluate(t: texpr): Promise<texpr> {
  switch (t.constructor) {
    case Number: ...
    case String: ...
    case Array: ...
    case Object: ...
    case Promise: ...
  }
}
```

What's the fix without a bunch of goofy business?

**Comment by Pyrolistical** [comment]
> Hi,
> 
> > @jedwards1211 good point, also what you've described is a workaround for this very issue!
> > ```ts
> > type ThisFails = number | Record<string, ThisFails>
> > 
> > type ThisWorks = number | {[key: string]: ThisWorks}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [playground](https://www.typescriptlang.org/play?&q=417#code/C4TwDgpgBAKgFgSwM4DECGCA2SoF4oB2ArgLYBGEATlAD5QBKEAxgPaUAmAPEsJQgQHMANLESoM2AHwBYAFBzQkUcgDqbANY58xclVpQA3gG11EEAC4oPPoIC6l+Ko1IAvnLlA)
> 
> yes, I was expecting this to work... but it does not :( I hope in a quick improvement.
> 
> Regards

What do you mean it doesn't work? It works for me. The first one errors the second one doesn't.

**Comment by FStefanni** [comment]
@Pyrolistical: exactly, the first one does not work
Regards

**Comment by TyIsI** [comment]
My apologies for replying here. But figured I would double check before creating a possible issue.

Extending the playground @Pyrolistical posted above, I get an error while trying to delete a subkey.

![image](https://github.com/microsoft/TypeScript/assets/3118952/9f432bba-cc3e-483a-ba7b-71309ab7e103)

```Typescript
type ThisFails = number | Record<string, ThisFails>;

type ThisWorks = number | { [key: string]: ThisWorks };

type ButThisErrors =
  | { [key: string]: ButThisErrors | string | number }
  | string
  | number;

const test1TopLevel: ButThisErrors = {
  l2: { l3: { l4: { l5: { l6: "endkey" } } } },
};

delete test1TopLevel.l2.l3.l4.l5.l6;

interface AndSoDoesThis {
    [key: string]: AndSoDoesThis | string | number
}
const test2TopLevel: AndSoDoesThis = {
  l2: { l3: { l4: { l5: { l6: "endkey" } } } },
};

delete test2TopLevel.l2.l3.l4.l5.l6;
```

[Playground](https://www.typescriptlang.org/play?target=99&q=417#code/C4TwDgpgBAKgFgSwM4DECGCA2SoF4oB2ArgLYBGEATlAD5QBKEAxgPaUAmAPEsJQgQHMANLESoM2AHwBuAFCzQkUcgDqbANY58xclVpQA3lADa6iCABcUHn0EBdK-FUacAXzkLw0AEJFgTpABRSko2LVkofSNTcysbfgEHKF9-MWDQyhw6eMF9HQpqVwj9HIFiunyqD1YCHihgCB4ARhgWMAAZCAA3CEwrFID0sLxDYswAJisjTABmKahMABZ5zABWFYA2KwAiCAJ2MxBtqFcTs9chWXd5dl6IBvrG4Ba2zp7MADoJr5mvxa-Vl8Nh5+A1KAAzNBMaAAQX2AGUWAARFiNAKjSKRGKWay8BJJOHsREotFiEp43IVUgFK6yGp1Bo8catDrdXpWQnE1FIdH4AxjSaGBZzIVLFbrUVbKC7faHY6nBUnS7XWS3TD3aCM4DM15sz7fWZ-AFAuRAA)

I'm guessing that this is due to the cut-off for recursive parsing?

**Comment by 2colours** [comment]
Why is this closed as completed? Where is the solution and what is the version where it works as expected?

**Comment by Philzen** [comment]
The issue that @TyIsI [described above](https://github.com/microsoft/TypeScript/issues/41164#issuecomment-1664677158) is exactly what bit me just now. 

The issue is that the first prop is possibly null … so traversing to any other prop will fail.

Strangely in [this JSON example showcasing the TS 3.7 features](https://www.typescriptlang.org/play/?#code/PTAEGEAsHtoZwJYDsDmoBGBTALgd05kqAK6KqjYCeADpqAG5yjLaYBOAZgIYDGdCTLumjFsFSJgBQIUD2hI42NlxZNk4uh0xdsxNpiYdobUNp6QAdKADqCbJFABmCwHYANKHl1oHaWHt0cgpKKgqeRFS0GKKgSNBi6izs3HyguFxM+gC20PSYACYWkn6gAJoislxEHMj5njE5+qBCImL2AsxEmAAeXFnUADaYAFyRBgC0jONJnLwGxTIAkmKkBRTQGHT2OqCUFXLEA3VxYvpaJtgbARQ0dHvEJVxN+Zg1SMhoyIgvGjdRdnBMAMOFYACqQDrpQSgAYILJ2Eq4CHmUD5BD5JAAcjEPQECQU6LoVU6rFmfA8VTqByOmzSxgA1gVHmwREg6rg7A4uDC7NghnS2PSiiUAGLGUy9fpDDztNRME6gLQZBDofnqZwANmGkjGoAAalwBsRMAB5NgAQTYykoAB5QQA+UAAXlAoNAAB9QJbrTaDUbTRarVxbQ77QBuBZgc1EOGDTBZQjYHQIeR0w51SBcPIw2CMuqwxniAQedCUUDw7ofErXXUc+zNGNIUkpTBFXV+41m73BgBMdsdLrdnu7lBNHA7AZH-YjMxbXqDo-Hhs7gZ9DolrDZTCnE67C77odAAG9QABfSOuiGCAYDaC4Qzi7lyfr6CQE7MvN52FNEHygABSADKJoAHJuIiyIOLgDJMKWoBnOwbAfOszDYICwLCrq-5wKmLqKEh5CekgxBZFgJiesI0BDMSRGHAMHoAThSAANoALoMSezGMpQwygPhHysbx2GpqeEaSEEigSn0caAUmuhwEBoFCUxzrHpIoDNPQKgDEIQy8UoxrgRpqxsEgfQjKAABE-7aEg4y3sQ1CWUZ8GwFkvFHupGmxOZvGWQAEggKCQDw+iKM5XkaTI4BVAqXD5HUHDEEgPDYD+ahNlcEiMamYyRaAMiOfkOgWQAFAAlM6jpHueGmnuBonFD00lDLJOikIpIEWCy0BZBYZkJqpllwCNlklOC7CYJiTCNFsGzUaZioslkvzOC4mxJvBQLaICsTxAYDZ1ACoAAAoAEraiAJSQNg2DUHAwwgC89CqtAKBwBY8KhfAPjYBYz7AGMcChQg1DYMAsWsjwHzjEDINg+MjjjC4wDXbd92PcAKCcsQ6D-b1wBfSyOEcODoK3IB8Pg9QdHAI4jgAAwAKwM0AA) this also happens.

Does anyone know how to modify the type in a smart way so this works?
