### ISSUE TITLE
Warn the user that tsconfig.json trumps jsconfig.json

### ISSUE THREAD

**Issue by webdeb** [microsoft/TypeScript#41170]
When both jsconfig.json & tsconfig.json are present jsconfig.json is ignored.

VSCode should highlight jsconfig.json as redundant and warn the user that its configs will not work as long as tsconfig.json is present.

Otherwise the user might feel like its a bug when jsconfig.json settings are not working. microsoft/vscode#108801

**Comment by mjbvz** [comment]
Moving upstream for discussion

The root bug is https://github.com/microsoft/TypeScript/issues/15869. Give that bug is 3 years old and only has 15 upvotes so far, I don't think this issue is commonly being hit

**Comment by RyanCavanaugh** [comment]
I don't understand what "Warn the user" means. If you intended to do this, how do you dismiss the warning? Would we show this every time? It's not a great plan IMO. If this isn't mentioned in the docs we should fix that as a separate thing.
