### ISSUE TITLE
Filter callback with wrong return type (`value is S` instead of `boolean`)

### ISSUE THREAD

**Issue by alias-mac** [microsoft/TypeScript#41172]
**TypeScript Version:**  4.0.3 (and 4.1.0-dev.20201019)

**Search Terms:**
filter
filter return type
filter
filter value is S

**Code**
Make sure that you use `tsc --target esnext` to run the following code:

```ts
const promises = [
  Promise.resolve(1),
  Promise.reject('error'),
  Promise.resolve(3)
];

(async () => {
  const result = await Promise.allSettled(promises);
  console.log(result);
  
  const rejected = result.filter((promise) => promise.status === 'rejected');
  
  // this fails which is expected because the filter above will be of type `PromiseSettledResult`
  console.log(rejected2.map((promise) => promise.reason));
  
  // this should work because we are defining what the types return from this filter 
  const rejected2 = result.filter<PromiseRejectedResult>(
    // fails because function returns a boolean instead of `PromiseRejectedResult`
    (promise) => promise.status === 'rejected'
  );
  
  // this passes now
  console.log(rejected2.map((promise) => promise.reason));
})();
```

**Expected behavior:**
`result.filter<PromiseRejectedResult>` code should not fail on the passed function

**Actual behavior:**
Function passed to `result.filter<PromiseRejectedResult>` is expected to return `PromiseRejectedResult` instead of boolean.

**Playground Link:**
https://codesandbox.io/s/angry-firefly-7c2rw?file=/src/index.ts:0-92

**Related Issues:**
I didn't find anything related with this bug. It seems to be an obvious and straightforward bug in:
https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L1176

I'm expecting this code to be:
```
filter<S extends T>(predicate: (value: T, index: number, array: readonly T[]) => boolean, thisArg?: any): S[];
```

I also believe that the next line:
```
filter(predicate: (value: T, index: number, array: readonly T[]) => unknown, thisArg?: any): T[];
```
should be expecting boolean to be returned from the function, instead of `unknown`, but that would probably be a breaking change at this point.

Probably relevant documentation for this issue:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by MartinJohns** [comment]
> Actual behavior:
> Function passed to `result.filter<PromiseRejectedResult>` is expected to return `PromiseRejectedResult` instead of boolean.

This is not the case. It's expected to return a **type predicate**, but you're providing a function that returns `boolean`.

When you provide a type predicate function it works as you expect:

    // A type predicate ("x is T"):
    (promise): promise is PromiseRejectedResult => promise.status === 'rejected'
    
    // A function returning boolean:
    (promise) => promise.status === 'rejected'

The issue #38390 track the automatic inferrence of type guards for simple cases, but I'm not sure yours would be covered.

---

I'd also like to point out that your "codesandbox.io" link does not work for me (latest Chrome, Windows). You should prefer the [TypeScript Playground](https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBADgJxAWwJYQKYRgXhgbQCgYYAFJNTAOgSxABsA3DACgEYBKAGmLIvQw0MAKwzAoLAOQYESBJO69yKAUIgNmLAMwdCAXQDchQiwCGEAJ5hgMFh1wA+GAG9eoSLFoQArvVh5TAHdTVFhlSkFTenoAZQwoKHoMABMWRBVMCA4jEnd1JKp6EABzFi9fKGzjXPBoGFpRcRTceqwKqgAzVD8ZFjT+THscJ3SIqmhTKG9sHFmYSQaxKBSFIzdahkEi0sWm5KreAHpDmCgAC3QYCDOQX2SYQJAEAGtTkBB1j1bG5eSAJha5T8nW6ywQAB5wgIAEoiJYpWE+PwOFi8EjHGAdEL0bAAIzEpmmGEx3msUFQ4FaUwQkBgphguPeSVMYBgqA8GFM9xAHT4GQwsJ+CLafjRtlGAiGIwGggmUxmcwWcL2kl4BxqkE2hRKZWVvz+VGQpjgfQlg0c8BlQnM4A4VQAvhw7EYgA) for reporting issues.

---

Not a bug, **working as intended**.

**Comment by alias-mac** [comment]
@MartinJohns I'm confused by your comment above. Currently the code in:
https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L1176
is:
```
filter<S extends T>(predicate: (value: T, index: number, array: readonly T[]) => value is S, thisArg?: any): S[];
```

this means that my provided `S` should be a subset of `T` (original type of the Array - as you can see the last param of the predicate function is `array: readonly T[]`).
Why would that function expect to return a value that is `S`? Filter predicate function should always return `boolean`. Also, why would filter return `S[]` based on your comment?

Like I said above I'm confused why `filter` is expecting to return `unknown`:
```
filter(predicate: (value: T, index: number, array: readonly T[]) => unknown, thisArg?: any): T[];
```
when MDN documentation clearly states that the predicate function should return `true` or `false`.

Can you provide an example based on mine where it would compilation work without error?

**Comment by MartinJohns** [comment]
> this means that my provided `S` should be a subset of `T` (original type of the Array - as you can see the last param of the predicate function is `array: readonly T[]`).
> Why would that function expect to return a value that is `S`? Filter predicate function should always return `boolean`. Also, why would filter return `S[]` based on your comment?

Please note that the return type is `value is S`, it is **not** `S`. This syntax is for [type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards). Type guards are special annotated functions that help the compiler to narrow types, and they must return a `boolean`.

**Comment by alias-mac** [comment]
@MartinJohns fair point, but I must say that it is a lot more verbose to write that way. Here is a more simpler example:

```ts
type Foo = {
  type: 'foo';
  foo: number;
}
type Bar = {
  type: 'bar';
  bar: number;
}

const all: Array<Foo|Bar> = [
  { type: 'foo', foo: 1 },
  { type: 'bar', bar: 1 }
]

const foos = all.filter((el): el is Foo => el.type === 'foo');
const bars = all.filter((el): el is Bar => el.type === 'bar');
```

IMO it would be a lot easier/simpler too just defined it like:
```ts
const bars = all.filter<Bar>((el) => el.type === 'bar');
```

jm2c.

**Comment by MartinJohns** [comment]
You should subscribe to #38390. :-) But don't expect any progress soon.

If you create a union type from all your options you can make it more nice using some local functions:

    type Union = Foo | Bar;

    const isFoo = (value: Union): value is Foo => value.type === 'foo';
    const isBar = (value: Union): value is Bar => value.type === 'bar';

    const foos = all.filter(isFoo);
    const bars = all.filter(isBar);

**Comment by alias-mac** [comment]
Yes thanks, I subscribed already. It makes it simple in many scenarios where I need to add that code just to make it happy.

One-liner functions seem harder to read when using type guards, and extracting them to be separately defined functions outside (like you did above) seem to defeat the purpose of simple anonymous functions that now we need to find good names for (naming things is hard 🤣 - https://martinfowler.com/bliki/TwoHardThings.html).

**Comment by MartinJohns** [comment]
> now we need to find good names for (naming things is hard 🤣 - https://martinfowler.com/bliki/TwoHardThings.html).

Generally I agree, but for a type guard that verifies a value is of type `MyType` (`value is MyType`) I think the name `isMyType` is a good convention. :-)
