### ISSUE TITLE
lib.d.ts: parameter littleEndian of the DataView functions should be optional

### ISSUE THREAD

**Issue by AngeloSalvade** [Microsoft/TypeScript#4117]
According to the ECMAScript 6 specification, parameter littleEndian of the DataView functions should be optional.
This was the case for TypeScript <= 1.4

**Comment by kitsonk** [comment]
Dupe of #4083.

**Comment by AngeloSalvade** [comment]
Thanks for the quick reply.
Sorry that I didn't find the dupe.
