### ISSUE TITLE
Discriminating union literal with spread operator gives type error

### ISSUE THREAD

**Issue by RMueAZD** [microsoft/TypeScript#41184]
**TypeScript Version:**  4.1.0-dev.20201021

**Search Terms:** Discriminating Unions literal "spread operator" "type error"

**Code**

```ts
type T = { type: "X"; a: number } | { type: "Y"; b: string };
function getDefaultValue(): T { return { type: "X", a: 1 }; }
const value: T = { ...getDefaultValue(), a: 2 };
//                                       ~~~~
// error TS2322: Type '{ a: number; type: "X"; } | { a: number; type: "Y"; b: string; }' is not assignable to type 'T'.
//   Type '{ a: number; type: "Y"; b: string; }' is not assignable to type 'T'.
//     Object literal may only specify known properties, and 'a' does not exist in type '{ type: "Y"; b: string; }'.
```

**Expected behavior:** TS should infer type T from the expression `{ ...getDefaultValue(), a: 2 }` (this worked last in v2.5.3)

**Actual behavior:** TS infers the wrong type from the object literal and gives a type error:
```
index.ts:3:42 - error TS2322: Type '{ a: number; type: "X"; } | { a: number; type: "Y"; b: string; }' is not assignable to type 'T'.
  Type '{ a: number; type: "Y"; b: string; }' is not assignable to type 'T'.
    Object literal may only specify known properties, and 'a' does not exist in type '{ type: "Y"; b: string; }'.

3 const value: T = { ...getDefaultValue(), a: 2 };
                                           ~~~~


Found 1 error.
```

**Playground Link:** [Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201015#code/C4TwDgpgBAKlC8UDeVSQFxQEQA0sG4oBDTAOwFcBbAIwgCcoBfKAH2VXAkywE0CpqmAM7A6AS1IBzJvgBQAM3KkAxsDEB7UlEkRgAEQjyi5ADbAAakRPkIACgCUmOCjq7ydLSjRdseADTEmACMMkyyypoiUABuVjZOCOwAdCk6+obGZpbWdvYBJFAATDJAA)

**Related Issues:**

**Comment by MartinJohns** [comment]
// w/o module import it works:
    const value2: T = { type: "X", a: 1 };
    const myValue2: T = { ...value2, a: 2 }; // ok

Without the import TypeScript is sure that the type of the local variable never changes, and as a result `value2` is **not** typed `T`, but instead it's typed `{ type: "X"; a: number }`. When you over over the `value2` you see the correct type in the tooltip. That's why you see different behavior.

If you adjust the code that TypeScript is not aware of this anymore you get the same behavior:

    function getValue(): T { return { type: "X", a: 1 }; }

    const value2: T = getValue();
    const myValue2: T = { ...value2, a: 2 };

**Comment by RMueAZD** [comment]
@MartinJohns Thx for explaining why the second version was working.
Based on your comment I tried to remove the code noise and get a little closer to the core issue.

**Comment by RMueAZD** [comment]
Seems to be a duplicate of #28191.
