### ISSUE TITLE
A way to mark a property on an interface as being implemented by getter/setter 

### ISSUE THREAD

**Issue by hotaru355** [microsoft/TypeScript#41188]
## Search Terms

- getter interface
- setter getter

## Suggestion

A way to define a property on an interface that indicates that the property is actually implemented by a getter/setter pair

## Use Cases

I am using a ORM library that provides classes with getter/setter pairs to access mapped table columns. Updating many properties of a table class is convenient by using `Object.assing` or object descructuring (see example), but ultimately fails, since the implementation is done with getter/setter pairs. It would be nice to have some distinction in TS for plain properties versus getter/setter pairs.

## Examples
```ts
class Employee extends OrmModel { // let's assume this has some static CRUD methods as well as instance methods
    private _age: number
    public get age() { return this._age; }

    public set age(theAge: number) { this._age = theAge; }
}

const e1 = await Employee.find()
await Employee.update({...e1, ...{ age: 42 } }) // this does not work, but the compiler does not tell me either

// e1.age=42 obviously works, but is not the best solution when you update tenth of fields at once
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
Duplicate of or strongly related to #3745 & #40415

Also, 
> `Object.assing` 

🍑

**Comment by RyanCavanaugh** [comment]
This would require a pretty substantial rehaul of almost everything in order to actually work; I'm not sure there's appetite for it

**Comment by hotaru355** [comment]
Thanks for the comments. I have a better understanding now of the issue. Will close, as I don't deem it very important.
