### ISSUE TITLE
this type is not assignable to the same property in base type

### ISSUE THREAD

**Issue by helmbold** [microsoft/TypeScript#41181]
**TypeScript Version:**  4.0.2

**Search Terms:** this type assignable same property base subtype

The following should work with [polymorphic `this`](https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types):
```typescript
interface Cloneable {
  clone(): this
}

class A implements Cloneable {
  constructor(readonly a: number){}

  clone(): A {
    return new A(this.a)
  }
}
```

A variant with `clone(): this` in class `A` also doesn't work (but with a different error message).

**Expected behavior:**

The code should compile without error, so that `clone` in the class `A` actually returns type `A`.

**Actual behavior:**

> Property 'clone' in type 'A' is not assignable to the same property in base type 'Cloneable'.
  Type '() => A' is not assignable to type '() => this'.
    Type 'A' is not assignable to type 'this'.
      'A' is assignable to the constraint of type 'this', but 'this' could be instantiated with a different subtype of constraint 'A'.

**Playground Link:** https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMIBsD2IJwEbooDeAUMsgljgBQCUAXMmABbADOJAviSZXG22QBBZMAC2AB0JiI4QRmy4CxMhWxswUAK4IwmKNSi4AJtnQBPZHEYgtYvNFpFuqyorqMRpcuSNgtUCDIOADuwtQs7AB0cLSq3JxAA

**Related**

https://github.com/Microsoft/TypeScript/issues/283

**Comment by MartinJohns** [comment]
> TypeScript Version: 3.7.x-dev.201xxxxx

The TypeScript version you use is fairly outdated. You should consider updating.

---

The error is correct, what you want won't work. Just consider this example:

    class B extends A { }

    const b: B = new B(1);
    b.clone(); // Returns A, when it should actually return B (aka "this")


I can't think of a way this would work as you want. When implementing your clone method you can't know the constructor of `this` because classes are not sealed.

Your best option is to have `Cloneable<T>` and implement `Cloneable<A>`.

**Comment by helmbold** [comment]
@MartinJohns  The version must have been a copy&paste mistake, I tested it with TypeScript 4.0.2. 

To your example: I thought that polymorphic `this` would lead to `b.clone()` returning an Instance of `B`. Maybe my understanding is not correct here.

**Comment by MartinJohns** [comment]
> To your example: I thought that polymorphic `this` would lead to `b.clone()` returning an Instance of `B`. Maybe my understanding is not correct here.

But your method doesn't return the polymorphic `this`. It returns `A`. You would need to replace the `clone(): A` with `clone(): this`.

But then you end up with the other issue that you can't possibly know the constructor of `this` at the point of implementation. To elaborate on the example:

    class B extends A {
      constructor(example: string) {
        super(0);
      }
    }

You have no way of knowing the constructor of `B` when implementing the method in your class `A`, but `this` could possibly be `B`.

**Comment by RyanCavanaugh** [comment]
Probably what you want to do is this
```ts
interface Cloneable<T> {
  clone(): T
}

class A implements Cloneable<A> {
  constructor(readonly a: number){}

  clone(): A {
    return new A(this.a)
  }
}
```

**Comment by helmbold** [comment]
Thanks, @RyanCavanaugh I'm aware of that solution, but hoped to be able to avoid the (somewhat redundant) Type parameter that is always of the same as the class that implements the interface.
