### ISSUE TITLE
`typeRoots` are ignored for normal type resolution when `types` are specified.

### ISSUE THREAD

**Issue by pelepelin** [microsoft/TypeScript#41198]
**TypeScript Version:**  3.x - 4.0.3

**Search Terms:** types typeRoots

**Code**

`tsconfig.json`
```json
{
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "types": ["node"],
    "typeRoots": [
      "node_modules/@types",
      "src/typings"
    ]
  },
  "files": [
    "src/index.ts"
  ]
}
```

**Expected behavior:**

https://www.typescriptlang.org/tsconfig#typeRoots
> By default all visible ”`@types`” packages are included in your compilation.
> If typeRoots is specified, only packages under typeRoots will be included.

https://www.typescriptlang.org/tsconfig#types

> This option does not affect how `@types/*` are included in your application code ...
> When you have this option set, by not including a module in the types array it:
> - Will not add globals to your project (e.g process in node, or expect in Jest)
> - Will not have exports appear as auto-import recommendations

So according to docs `types` option does not prevent resolving normal `import "foo"` (as it is related only to types of global symbols), and `typeRoots` should modify the lookup list when resolving normal imports.

**Actual behavior:**

If `types` are specified, `typeRoots` are ignored for imported modules not listed in `types`, `tsc` looks for types in  `node_modules` and `node_modules/@types`.

**Playground Link:** N/A

Reproduce repo: https://github.com/pelepelin/TypeScript-issue-41198

**Related Issues:**

**Comment by pelepelin** [comment]
Another more obvious setup which fails because of this is when local typings are not in the `include` list.

This one fails to look into `./typings`.
```json
{
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "types": ["node"],
    "typeRoots": [
      "./node_modules/@types",
      "./typings"
    ]
  },
  "include": [
    "src"
  ]
}
```

But this one is ok.
```json
{
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist",
//    "types": ["node"],
    "typeRoots": [
      "./node_modules/@types",
      "./typings"
    ]
  },
  "include": [
    "src"
  ]
}
```

And this one is ok as a workaround.
```json
{
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "types": ["node"]
  },
  "include": [
    "src",
    "./typings"
  ]
}
```

Note that these subtly differ from the original intention, as with `typeRoots` missing or ignored `tsc` looks for additional `node_modules` in `..`, `../..` etc.

**Comment by RyanCavanaugh** [comment]
Which files are you putting where, and how are you trying to import them?

**Comment by pelepelin** [comment]
Created repro https://github.com/pelepelin/TypeScript-issue-41198

**Comment by pelepelin** [comment]
Another person advised me that

> The goal of types and typeRoots is to eagerly pull in types
> types and typeRoots is not part of module resolution

If that's true, then my issue is invalid. However, I did not see this in the documentation.

**Comment by RyanCavanaugh** [comment]
If you specify `types`, as you did here, then the automatic enumeration of your `typeRoots` doesn't happen. A correct tsconfig would be

```
    "types": ["node", "dnscache"],
    "typeRoots": [
      "node_modules/@types",
      "src/typings"
    ]
```
