### ISSUE TITLE
Editor Suggestion Backlog Slog, 10/21/2020

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#41192]
Basically an offhand meeting with @jessetrinity on outstanding productivity/editor feature PRs that turned into something like an editor feature backlog slog.

# Wrap Value in Object

#40241

* Not a committed bug, so hold off for a bit.
* When this gets triggered is a little funky. @jessetrinity and I were thinking potentially just return statements/expressions, and return type annotations.
  * Probably okay to not worry about `@returns` in JSDoc.
* Why just returns? What about an inner property? Seems like you'd like to be able to get some of these rewrites in other places.
* What about when you're not doing plain object literals? If you're using factory functions.
* Bring this to editor sync, see what others have to say.

# Desugar Parameter Properties

#40238

* Kind of feel that this implies there's something wrong with writing code like this.
* Technically "bad" only from the purist perspective.
* You wrote this - someone *meant* to write this.
* But it's a useful feature - we could see some version of parameter properties going into the JS itself.
    * Then people will want to convert to the ECMAScript version of param props.
* Maybe we should have it be bidirectional?
* "I want refactors to tell me the 'right' way to write TypeScript."
    * Don't have a strong opinons on enums, why have one on this?
    * It just overwhelms people to give guidance that just churns code.
    * We don't feel like this is an anti-pattern, we'd like to make it not-an-anti-pattern by seeing it in plain JS.
* Convert to a potential future syntax when it's available.
* Hold off, awaiting more feedback in the meantime to check assumptions.

# Convert Property Accesses to Destructuring

#39832

* Find uses of an object where properties are accessed, destructure that value.
* Woah! That IS cool.
* Bring this to editor sync.

# `let` to `const`

#40213

* Prefer ESLint for these scenarios.

**Comment by DanielRosenwasser** [comment]
CC @Kingwl @minestarks @mjbvz

**Comment by Kingwl** [comment]
I'd like to update these pr ASAP.
