### ISSUE TITLE
Object is possibly undefined when optional key is conditionally assigned

### ISSUE THREAD

**Issue by silicakes** [microsoft/TypeScript#41200]
**TypeScript Version:**  4.0.3

**Search Terms:**
typescript object might be undefined when using conditional assignment

**Code**

```ts
// CASE 1
enum FOOBAR_KEYS {
    FOO ="foo",
    BAR = "bar",
    BAZ = "baz"
}
type Foobar = Record<FOOBAR_KEYS, number>;

let obj: Partial<Foobar> = {}
obj[FOOBAR_KEYS.BAR] = obj[FOOBAR_KEYS.BAR] || 0;
obj[FOOBAR_KEYS.BAR]++; // Object is possibly 'undefined'.(2532)



// CASE 2
interface FooInterface {
    key: { [K in FOOBAR_KEYS]?: number }
}

let obj_2: FooInterface['key'] = {};
obj_2[FOOBAR_KEYS.BAR] = obj_2[FOOBAR_KEYS.BAR] || 0;
obj_2[FOOBAR_KEYS.BAR]++; // Object is possibly 'undefined'.(2532)



// CASE 3
if(obj[FOOBAR_KEYS.BAR] === undefined) {
    obj[FOOBAR_KEYS.BAR] = 0;
}

obj[FOOBAR_KEYS.BAR]++; // Object is possibly 'undefined'.(2532)
```

**Expected behavior:**
Typescript understands that the key cannot be undefined as `undefined` will get `0` to be assigned

**Actual behavior:**
`Object is possibly 'undefined'.(2532)`

**Playground Link:** 
https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true#code/KYOwrgtgBAYg8nAQgQQEoH0DSBRAmgZSgG8BYAKCktgSgF4AiAMwHtn6AacqqFVOqegCMAhgCcOXKigBa-IcIBe9cgF9y5AC4BPAA7BYrEaP6pgAY2aiAJgB54SNFjz52UcBEHBRAPgDc6sgAbYA0oZkEAKwAuKAAFMQ0AS2FAu0Mxb34iNTJwiIBte14nAgA6XgBdfjzChGKcMsqoAB9mqAAGf1zI2ocMBvxytAqAahGu8kSQDS9GYTN9GFYASWnZ+f1SCioAa2AtGKIofMwoKeo+kvwKgH4Y909jHJzyYNC89AAmGKXmVZnRHMFvkAOR7LQgqq0YgqLofT69erOIaoKFhSJfRGOAYoqqtDpwjEIorY5GVMYTMgBRKMAAUNRJ-TJwzotGhYBAVmAjCmwCsAEpiJJKAy6qTGizoe1VAFRZcceTxkA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/31060

**Comment by MartinJohns** [comment]
Related (perhaps duplicate?): #10530

**Comment by RyanCavanaugh** [comment]
It's a true duplicate; the only reason this doesn't work is because this kind of expression doesn't generate a CFA node

**Comment by silicakes** [comment]
> It's a true duplicate; the only reason this doesn't work is because this kind of expression doesn't generate a CFA node

Hi @RyanCavanaugh and thanks for the comment.
Could you elaborate on what a CFA node is and maybe provide some additional reading/references for this?
