### ISSUE TITLE
readonly properties can be modified from outside the class

### ISSUE THREAD

**Issue by DiogoSoaress** [microsoft/TypeScript#41207]
**TypeScript Version:**  4.0.2

**Search Terms:**
readonly class
**Expected behavior:**
readonly properties cannot be modified from outside the class

**Actual behavior:**
readonly properties can actually be modified from outside the class

**Related Issues:**
No. This bug was found in the Typescript Handbook

**Code**
```ts
// @errors: 2540
class Octopus {
  readonly name: string;
  readonly numberOfLegs: number = 8;

  constructor(theName: string) {
    this.name = theName;
  }
}

let dad = new Octopus("Man with the 8 strong legs");
dad.name = "Man with the 3-piece suit";

console.log(dad)
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// @errors: 2540
class Octopus {
    constructor(theName) {
        this.numberOfLegs = 8;
        this.name = theName;
    }
}
let dad = new Octopus("Man with the 8 strong legs");
dad.name = "Man with the 3-piece suit";
console.log(dad);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/PTAEAEFMCdoe2gZwFygEwFYAsAGAUAMYA2AhooqAPIEAucADgK4UDeeoo0kJAJnAHZEAnqH4kAtpFSIa0AJb8A5gG52nbn0Ej+jcQCMYlAGYAZSIpSjdB6KAC8oAByq1BATOiNaCABQ0AFpAAchJSoB4KigCUoGwcHAFyiAB0YpL2oAHBoaocAL54BXhEkDSgPLwZ-JAA7lTeTIg+AEQAsiT8oDVyAZmBTuGyAoqgJRbNUaoVPKmhGW0dXT3+fZCgAMwAtPRykARriIw9zS5u-IhwJclEcIo+01FAA)

**Comment by RyanCavanaugh** [comment]
What is the implied defect here? This is flagged as an error

**Comment by DiogoSoaress** [comment]
It flags the error but still console logs the changed property. Is that the expected behaviour? If so pardon my interpretation.

**Comment by RyanCavanaugh** [comment]
Yes, TypeScript's type system is erased. It doesn't change the runtime behavior of JS.
