### ISSUE TITLE
Add insertSpaceAfterOpeningAndBeforeClosingEmptyBraces to tsserver protocol

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#41208]
Looks like #35427 added a new formatter setting: `insertSpaceAfterOpeningAndBeforeClosingEmptyBraces`

I see this setting in code but it is not exposed in the tsserver protocol at the moment. Should it be added there as well?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser What do you think about this issue?
