### ISSUE TITLE
Union type should not be narrowed to intersection type when used at generics constraint.

### ISSUE THREAD

**Issue by g-plane** [microsoft/TypeScript#41211]
**TypeScript Version:**  4.0.2 , 4.1.0-dev.20201015

**Search Terms:**
generics constraint
union
intersection

**Code**

```ts
class A {
  a: string = ''
}

class B {
  b: boolean = false
}

interface ClassMap {
  a: A
  b: B
}

function demo<T extends keyof ClassMap>(key: T): ClassMap[T] | null {
  switch (key) {
    case 'a':
      return new A  // TS type checker reports at this line.
    default:
      return null
  }
}

```

**Expected behavior:**

Type checker reports no errors, since return type should be `A | B`, not `A & B`.

**Actual behavior:**

The error message is: `Type 'A' is not assignable to type 'A & B'`.

However, if we change the function signature like this:

```ts
function demo<T extends keyof ClassMap>(key: T): ClassMap[keyof ClassMap] | null
```

Or

```ts
function demo<T extends keyof ClassMap>(key: keyof ClassMap): ClassMap[typeof key] | null
```

Type checker *won't* report any errors.

**Playground Link:**

https://www.typescriptlang.org/play?ts=4.0.2#code/MYGwhgzhAECC0G8BQ1XTALmhALgJwEsA7Ac2gF5oByKpAXySVEhgCFEU0AjLLgez4gApmCIVoAMzAgIQ+o2I4heKcCHQAwuCgBZMAAcOadFlidUPaK3lIJAVyLAcBPmIAmQgLZ8APABVoIQAPJSI3GABrIQBPPglNbQg9fQA+AAoo6Kw-AEosLRZkgG0-AF1oAB9oIjsQECM0CAB3AhxgAAtoDJichuNUYEh1KjAqDHN+4zwhHDs8MSIhJrgJ4w8pWpxxycnp2fnq2pAJhgYgA

**Related Issues:**

TBD

**Comment by RyanCavanaugh** [comment]
Duplicate #33014
