### ISSUE TITLE
Private fields: WeakMap needs to be set before calling super()

### ISSUE THREAD

**Issue by JamesB7** [microsoft/TypeScript#41214]
**TypeScript Version:**  4.0.2

**Search Terms:** private fields

**Expected behavior:**
This should work. I am setting the private field from the derived class.

**Actual behavior:**
It says "attempted to set private field on non-instance". This is because the WeakMap initialization happens after calling super(), where it needs to happen before.

**Related Issues:**

**Code**
```ts
abstract class ClassA {
    constructor() {
        this.reset();
    }

    abstract reset(): void;
}

class ClassB extends ClassA {
    #value: number;

    constructor() {
        super();
    }

    reset() {
        this.#value = 1;
    }
}

let InstanceB = new ClassB();
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, privateMap, value) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to set private field on non-instance");
    }
    privateMap.set(receiver, value);
    return value;
};
var _value;
class ClassA {
    constructor() {
        this.reset();
    }
}
class ClassB extends ClassA {
    constructor() {
        super();
        _value.set(this, void 0);
    }
    reset() {
        __classPrivateFieldSet(this, _value, 1);
    }
}
_value = new WeakMap();
let InstanceB = new ClassB();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgwq9BBBA3gFAKlID2AdpFAK7zlQAUAlISWZxABYCWYAOigBTMMIisA3B1IBfIjISgacRCLESWALgQA3crwAm0+URRoM2CwCEEwgB4RhlQ5Zxh8xTgGJdwZLTCOpS0ALYgwlDSirBUNPQQjKzsnJxgtAAOkVKKppzq4sleqaQ8-AK+-oEIALwIAIzSnPKmyOIIAJLUEMCUsMK2dZTCAO5Y7tZSQA)

**Comment by RyanCavanaugh** [comment]
I don't think this is fixable - we can't reference `this` until `super` is invoked. Babel has the same problem with this code. Generally it's very problematic to invoke virtual members from the constructor for reasons like this.

cc @rbuckton to confirm.

**Comment by DanielRosenwasser** [comment]
If you run this in Chromium, you get an error too. Sounds like "working as intended"
```js
class ClassA {
    constructor() {
        this.reset();
    }
}

class ClassB extends ClassA {
    #value;

    constructor() {
        super();
    }

    reset() {
        this.#value = 1;
    }
}

let InstanceB = new ClassB();
```

```
VM151:15 Uncaught TypeError: Cannot write private member #value to an object whose class did not declare it
    at ClassB.reset (<anonymous>:15:21)
    at new ClassA (<anonymous>:3:14)
    at new ClassB (<anonymous>:11:9)
    at <anonymous>:19:17
```

**Comment by JamesB7** [comment]
This is a shame. C#'s behavior (what happens with private) is far more 
usable than C++'s (what now happens with #). Ah well.
