### ISSUE TITLE
Add a signature "(...args: any[]): any" to interface "CallableFunction"

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#41225]
## Search Terms

function callable signature

## Suggestion

There are some posts(https://github.com/Microsoft/TypeScript/issues/20007, https://github.com/microsoft/TypeScript/issues/34540) about `Function` and `(...args: any[]): any`. It seems this is an intended design.
> [The original intention of Function is to not be callable.](https://github.com/Microsoft/TypeScript/issues/20007)

But a `CallableFunction` should be "callable" in semantics. It should be allowed to assign `CallableFunction` to `(...args: any[]): any`.(and vice versa)

## Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
It's callable because it has a `call` method. This interface is basically an implementation detail of the compiler; if you want `(...args: any[]): any` then *write* `(...args: any[]): any`
