### ISSUE TITLE
Spreading introduces undeclared fields in object of specific type

### ISSUE THREAD

**Issue by roman-allen** [microsoft/TypeScript#41237]
This problem not only violates strong typing principles but also introduces memory wasting mechanism which allows to add new/unexpected fields into the strongly typed object.

**Code**

```ts
type MyType = { valueA: string, valueB: string };
const value: MyType = { valueA: 'aaa', valueB: 'bbb' };

const bad = { valueA: 'override A', bad: 'BAD' };
// spreading below overrides valueA which is desired but it also adds `bad` into MyType
const all: MyType = { ...value, ...bad };

function dump(value: MyType) {
  console.log(value); // output contains `bad` which is not in MyType
}

dump(all);
```

**Expected behavior:**
`value` parameter in `dump` function has only fields declared in `MyType`.

**Actual behavior:**
`value` parameter has a field `bad` which is not declared in `MyType` but added into `value` at run-time by spreading.

**Playground Link:** 

https://www.typescriptlang.org/play?target=99&ts=4.0.2&ssl=1&ssc=1&pln=12&pc=11#code/C4TwDgpgBAsiAq5oF4oG8oDcCGAbArhAIIBcUAzsAE4CWAdgOYA0WehAQmZbY1AL4BuAFABjAPZ1KrAhDJxEkKKgw4ZpKAHJs2jS1UcyGgEYmN-YaIlSj2ACZL00wuo1jMEKrVvQiuqDdtDdiIAETNBIQB6SIowKgg7egZ-CFwxAHcoNw8vCHInYih0gAsaEWKoGnzvchp4+yN8YErmvHIxKDtbfIADAJ7KumAO+SRLSVbcXDkEJAcMADol-QgWJYWA8yEhADN8OhFgGgkoW3wAWzAAChWZhQgASnQhKChxSTFcCAW0hhu2R4CKDRLJNMBNN4SYDYei9fpFUrlSr5OhiZr0WCzSBCPjbM6XK54XAPARAA

**Related Issues:**

I didn't find similar reports.

**Comment by MartinJohns** [comment]
This is working as intended. TypeScript is structurally typed. [What is structural typing?](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing)

You want "Exact Types": #12936

**Comment by roman-allen** [comment]
@MartinJohns sorry, maybe I'm missing the point behind your message but how the fact that TypeScript is `structurally typed` language justifies the fact that the object gets altered structurally during spreading?

console.log in the example above outputs
```ts
{ "valueA": "override A", "valueB": "bbb", "bad": "BAD" }
```
which means that a new field was added to the object.

**Comment by MartinJohns** [comment]
> which means that a new field was added to the object.

And this is fine. The object is still structurally compatible with `MyType`. All properties that must exist according to `MyType` are present.

**Comment by roman-allen** [comment]
This fact makes strong typing in TypeScript very controversial because this is invalid
```
type MyType = { valueA: string };
const myValue: MyType = { valueA: 'aaa', valueB: 'bad' };
```
because of the error
```
Type '{ valueA: string; valueB: string; }' is not assignable to type 'MyType'.
  Object literal may only specify known properties, but 'valueB' does not exist in type 'MyType'.
```
which is totally logical and makes sense, but this is valid
```
type MyType = { valueA: string };
type OtherType = { valueB: string };
const otherValue: OtherType = { valueB: 'bad' };
const myValue: MyType = { valueA: 'aaa', ...otherValue };
```
and makes `myValue` equal to `[LOG]: { "valueA": "aaa", "valueB": "bad" } `
🤷‍♂️

**Comment by MartinJohns** [comment]
> Object literal may only specify known properties, but 'valueB' does not exist in type 'MyType'.

This is the excess property check. According to @RyanCavanaugh it's more of a linter, not really part of the type system. But not every case is covered by this check, as you noticed.

Regardless, the presence of additional properties is fine in a structurally type-system. You can follow #12936 for "Exact Types" that would disallow any additional properties.

**Comment by roman-allen** [comment]
> Not controversial at all, just very commonly misunderstood. I'd encourage you again to check the documentation I linked earlier.

I checked the document you've linked.
Let's walk through it together:
> The idea behind structural typing is that two types are compatible if their members are compatible.
This is not my case. I'm adding a property which wasn't declared by type declaration and the type has no similar property to replace it with value I'm passing.

> For example, in C# or Java, two classes named MyPoint and YourPoint, both with public int properties x and y, are not interchangeable, even though they are identical. But in a structural type system, the fact that these types have different names is immaterial.

Not suitable for my example too. I'm not trying to assign an object with the same number of properties which have the same types but different names. I'm adding a completely new property which was never been declared in the type in any form.

> Because they have the same members with the same types, they are identical.

Not my case again.

The best answer to this mess with adding undeclared fields is described in [this comment](https://github.com/microsoft/TypeScript/issues/12936#issuecomment-693606053) and the reason behind it has nothing to do with `type system` specifics or `structurally typed TS`.

**Comment by MartinJohns** [comment]
> I'm adding a property which wasn't declared by type declaration and the type has no similar property to replace it with value I'm passing.

You focused on the wrong part of the documentation. :-)

> The idea behind structural typing is that two types are compatible if their members are compatible.

The members of your type `{ valueA: string, valueB: string }` are compatible with the members of your other type: `{ valueA: string }`, so the types are compatible.

> The best answer to this mess with adding undeclared fields [...]

Honestly, I don't want to imagine the mess TypeScript would be if the behavior would be different. It would require **so much** additional code and overhead.

---

But we've reached a point where any further discussion is moot. 🤷 This works as indented, and the feature you want is tracked by #12936.

**Comment by RyanCavanaugh** [comment]
We really need a FAQ entry on this. Putting it on my TODO list
