### ISSUE TITLE
EmitResult typings are incomplete

### ISSUE THREAD

**Issue by ericmorand** [microsoft/TypeScript#41236]
Using TypeScript npm package 4.0.3, EmitResult type definition is the following:

```ts
export interface EmitResult {
        emitSkipped: boolean;
        /** Contains declaration emit diagnostics */
        diagnostics: readonly Diagnostic[];
        emittedFiles?: string[];
}
```

But here is what is returned by `Program::emit`:

```json
{ emitSkipped: false,
  diagnostics: [],
  emittedFiles: undefined,
  sourceMaps:
   [ { inputSourceFileNames: [Array], sourceMap: [Object] },
     { inputSourceFileNames: [Array], sourceMap: [Object] } ],
  exportedModulesFromDeclarationEmit: undefined }
```

As you can see, the types declaration lacks `sourceMaps` and `exportedModulesFromDeclarationEmit`. It makes impossible to write a custom compiler that needs access to `sourceMaps`.

**Comment by MartinJohns** [comment]
The property is marked as internal, so it's probably still subject to change: https://github.com/microsoft/TypeScript/blob/7e07a2b5d129a35c05107cb5f1d11347876a692b/src/compiler/builderStatePublic.ts#L6

In the meantime you can use declaration merging to expand the `EmitResult` type.

**Comment by DanielRosenwasser** [comment]
just note that you can be broken if you take a dependency on anything marked internal, as we may remove it.

**Comment by ericmorand** [comment]
Thanks @DanielRosenwasser 

sourceMaps is not marked as internal is it? I'm wondering how to retrieve the sourceMaps of the emit result if it is not public. Is there another way to get the source maps ?

**Comment by DanielRosenwasser** [comment]
@sheetalkamat @rbuckton any clue on this one?

**Comment by sheetalkamat** [comment]
`sourceMaps` is internal. You should look at the .map file written instead as part of emit call.

**Comment by ericmorand** [comment]
Thanks @sheetalkamat. I'm not writing the results, TS is part of a build toolchain that doesn't write anything by itself until the end. But I think I can intercept the map from one of the functions available at the compiler host level. I'll try that.

Anyway, I think that the source maps should be made public in emit result for those of us that write build tools.
