### ISSUE TITLE
Documentation on how to transpile from TypeScript to JavaScript is missing (or very hard to find)

### ISSUE THREAD

**Issue by ericmorand** [microsoft/TypeScript#41230]
I need to transpile a TypeScript project to plain JavaScript using node.js. TypeScript comes with a binary - `tsc` - to transpile projects from the command line, which is extensively documented. But its inner API documentation is missing - or I never was able to find it.

Thus, I have no idea how to use `tsc` from a node.js script to transpile, get diagnostics, transform, etc.

We have some very scarce (out probably out-of-date) documentation about the compiler APIs themseleves, but they are extremely low level and recreating perfectly what `tsc` does would take weeks or months of work.

We need some documentation on how to use `tsc` in a node.js script.

**Comment by RyanCavanaugh** [comment]
If you search for "typescript transpile api", the first hit is this page https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

There, if you search for "transpile", you will see this on the page https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function

![image](https://user-images.githubusercontent.com/6685088/97192212-f173d200-1764-11eb-81ff-cde025339665.png)

If you want to *exactly replicate* all of what `tsc` does, its source code is available.

**Comment by ericmorand** [comment]
> If you want to exactly replicate all of what tsc does, its source code is available.

Well, that's the whole point of this issue. :D 

We could use some documentation so that we don't have to read the source code to write a node.js compiler that replicate what tsc does. I mean, with all due respect, would every project lead give us that kind of answer, there would be no API documentation for open source projects since, after all, everything is available in the source code.

**Comment by RyanCavanaugh** [comment]
If you want to replicate all of what tsc does, then by definition you have to rewrite tsc line-for-line, so the documentation *is* https://github.com/microsoft/TypeScript/blob/master/src/tsc/tsc.ts#L21
