### ISSUE TITLE
Cannot infer the type of a generic type parameter T even if T extends a single string literal type

### ISSUE THREAD

**Issue by mingcenwei** [microsoft/TypeScript#41246]
**TypeScript Version:**  4.0.3

**Search Terms:** react jsx html generics React.createElement

**Code**

```ts
import React from "react";

export type HtmlTags = keyof React.ReactHTML;
export type HtmlProps<
	HtmlTag extends HtmlTags
> = JSX.IntrinsicElements[HtmlTag];
type DetailedHtmlPropsToDetailedReactHtmlElement<
	DetailedHtmlProps
> = DetailedHtmlProps extends React.DetailedHTMLProps<infer E, infer T>
	? T extends HTMLElement
		? React.DetailedReactHTMLElement<E, T>
		: never
	: never;
export type HtmlElement<
	HtmlTag extends HtmlTags
> = DetailedHtmlPropsToDetailedReactHtmlElement<HtmlProps<HtmlTag>>;

const f1 = <HtmlTag extends "img">(
	tag: HtmlTag,
	props: HtmlProps<HtmlTag>,
): HtmlElement<HtmlTag> => React.createElement(tag, props);

type HtmlTag = `img`;
const f2 = (tag: HtmlTag, props: HtmlProps<HtmlTag>): HtmlElement<HtmlTag> =>
	React.createElement(tag, props);
```

**Expected behavior:** both `f1` and `f2` can compile or both of them cannot compile.

**Actual behavior:** `f2` can compile, but `f1`has the error `error TS2322: Type 'DetailedReactHTMLElement<HtmlProps<HtmlTag>, HTMLImageElement>' is not assignable to type 'DetailedHtmlPropsToDetailedReactHtmlElement<HtmlProps<HtmlTag>>'.`

**Playground Link:** [link](https://www.typescriptlang.org/play?ts=4.1.0-beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4BYAKCqQA9JY4YBPMJOACRhABsAVFAHMAznAC8cANZJmETImIwAdMnQwOfALIAZCpToN4LNp248ACjjDCAPFQCQXXgMFw6MJADsAJqKf8hYSoAPnE4ACkAZQANJQBJTxgoYE9hYDQAUR4kEC8YYQBtfxcAXT1jdgARJBgUYGzvf0sIaz4Iatr6pG9VDH8snLy7SnsOuoamqyDKUIkxrsazZus3Wg8fUV7leYmtbWXbFMwkKDgMgBo4I5O4PmCHAH5b1fXfTj2B3MSHeyetpR23S2Gh0nyGF1u9xG9gAXHBPEgAG4nBxwhHIqB6AzQIysdj9bJfGDDRxmFwvLxvYqBEJhQGLXgHNr04FmMGJGyTFq2amCYLBPRUNAQVJYACMYU5ZKEFI2BFAgnwwQAFA5aoI4bzzg4wFNNUsplLnEJgtrKABKfW8dnE3mzUL-NBEFAeG3K9WXXXc82CygVUzG1wSAAGCuDemForgmAATGF3UIrQFBJ69QGLIa7Zb0zajcn7Q5Hc7XYS8gmU3AvdYfVQqEA)

**Related Issues:** no.

**Comment by RyanCavanaugh** [comment]
The only way this would work is if TypeScript did specific analysis based on "Does this generic type parameter only have exactly one legal inhabitant?", but there's no reason to do that kind of analysis because there's no reason to write a generic type parameter with exactly one legal inhabitant.
