### ISSUE TITLE
Type-level accumulation produces 2589 unless as a linked list

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#41254]
**TypeScript Version:**  4.1.0-dev.20201026

**Search Terms:** type-level, recursion, accumulator, intersection, linked list, tail, call

I've been struggling to find recursion limiter workarounds, and it's keeping me from representing something which I believe would be extremely useful: a GraphQL-source-string-to-TS-type utility type.

**Code**

We begin by defining our GraphQL statement delimiters.

```ts
type Delimiters = "enum" | "extend" | "input" | "interface" | "scalar" | "schema" | "type" | "union";
```

Next, we create a utility, which accepts a string and a union of possible substrings (our union of delimiters), and matches the first occurrence, along with its leading and trailing text.

```ts
export type MatchLeading<Src extends string, Delimiter extends string> =
  Src extends `${infer Leading}${Delimiter}${infer _Rest}` ? Leading : never;

export interface Match<
  Leading extends string,
  Delimiter extends string,
  Trailing extends string
> {
  leading: Leading;
  delimiter: Delimiter;
  trailing: Trailing;
}

export namespace Match {
  export type Any = Match<string, string, string>;

  type Values<X> = X[keyof X];

  export type First<
    Src extends string,
    DelimiterU extends string
  > = Values<{
    [Leader in MatchLeading<Src, DelimiterU>]: MatchLeading<Src, DelimiterU> extends `${Leader}${infer _Rest}`
      ? Src extends `${Leader}${infer DelimiterAndTrailing}`
        ? DelimiterAndTrailing extends `${DelimiterU}${infer Trailing}`
          ? DelimiterAndTrailing extends `${infer Delimiter}${Trailing}`
            ? Match<Leader, Delimiter, Trailing>
            : never
          : never
        : never
      : never;
  }>;
}
```

Here's an example of this utility's usage:

```ts
type X = FirstMatch<"a b c", "a" | "b" | "c">;

/**
 * ```ts
 * Match<"", "a", " b c">
 * ```
 *
 * –– or ––
 *
 * ```ts
 * {
 *   leading: "";
 *   match: "a";
 *   trailing: " b c";
 * }
 * ```
 */
```

Next, we begin creating our top-level generic `Parse` type, which accepts the GraphQL schema source string type and iterates over it using `Match.First`.

For the purposes of this issue, we won't be going into the mapping of the types. **This is solely meant to demonstrate how we fail to iterate over the string while accumulating a record**. In the final, implementation this record would contain the schema-corresponding types. For now though, we'll just build up a lookup of `Match` results, keyed by the leading text (`Matched["leading"]`).

```ts
type Parse<
  Src extends string,
  Matched extends Match<string, SchemaDelimiters, string> = Match.First<Src, SchemaDelimiters>
> =
  [Matched] extends [Match<string, SchemaDelimiters, string>]
    ? Record<Matched["leading"], Matched> & Parse<Matched["trailing"]>
    : {};
```

While the above fails with `2589`, one subtle change lets it succeed:

```diff
type Parse_LinkedList<
  Src extends string,
  Matched extends Match<string, SchemaDelimiters, string> = Match.First<Src, SchemaDelimiters>
> =
  [Matched] extends [Match<string, SchemaDelimiters, string>]
-   ? Record<Matched["leading"], Matched> & Parse<Matched["trailing"]>
+   ? Record<Matched["leading"], Matched> & {next: Parse_LinkedList<Matched["trailing"]>}
    : {};
```

My first thought was to attach an accumulator, to which we could later traverse.

```ts
type Parse<
  Src extends string,
  Acc extends object = {},
  Matched extends Match<string, SchemaDelimiters, string> = Match.First<Src, SchemaDelimiters>
> =
  [Matched] extends [Match<string, SchemaDelimiters, string>]
    ? {acc: Acc & Record<Matched["leading"], Matched>; next: Parse<Matched["trailing"], Acc & Record<Matched["leading"], Matched>>}
    : {};

type Parsed = Parse<"" /* gql src string here */>;

type GetAcc<T extends object> = T extends {next: object} ? GetAcc<T["next"]> : T extends {acc: any} ? T["acc"] : never;

type Acc = GetAcc<Parsed>; // error
```

Surely enough, this gives us 2589 again––not on the usage of the `Parsed` type, but on its traversal.

I've tried many variations of this to see if I can get around the recursion limiting, but I'm unsuccessful every time. There doesn't seem to be a way to access the final `acc`.

When it comes to iterating over GraphQL schemas, these kinds of recursion limits are debilitating. If we are to create a future of greater type-system interoperability, robust type-level accumulation **is a must**.

[**Playground Link**](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201026#code/KYDwDg9gTgLgBDAnmYcCyBDGBjAFgGWAwBMBLAOwHMAeAZSmzlBmHOIGc52YoLKAaOABFgAG1IBbUiyhMQLNp268qAPjgBeAFBw49Rs1Yc4AAwAkAbwoAzYLMIk+AX0sjxUmS6vlbsgPoASsDcTiZwAPxwDmRUcABccOTAAG52ANxaWqCQsHAUMtYY2KiYOLjUOlFEMZRyCsbKfPyVbpLSdnVGSjxNlQAqUBik4rGGilw9VFrqFpWi1XwJ0XwZusRibTIJrR7plTxDI5QJA4crWk6Z2dDw5BgSwWBFJVh4cLO617lIKHAAguREJp0K9yo0qIJwQIJipKKoMvtkKgAGoYUQAV2C1AAGuoNHBsQBtADWwEQEGsBIAugjPuAbggkXAAGKkKDcCq6XT6TrjKHNLnCDa7KAAVV5DUmlEqeLgqIxWI+XMJ0Q6FBBZWWVDoDEEO3aYtUVISpTwWpo+j1woNovUY2M5gsqqgXhsHUCwRgoUqgsiPPtnEdztdPg6+pkAOIp2GzhMPsFESF7gNkejRwlgdc1pkopDvjgadj8YTifDdlTgxjo3kXVMljdsjLLsshao3pLJcipvKzqtyZkglbcOLHYSSVSUBHgrHKTsU-iiVnk5LM4nqzgTnhF0yAHo91o9zuD-utD9ULQ8MAJBgm5x8QAiVjoiT3uAAHzgj5rbFfH-vFDAdEYF-T98jsQpihA+92GwNEMCgKCYNwK8MCgs8oPRchSAgch7wRM84AABXg9hgD8ABxUhUnYABRKAoGgTk9AYDMYV6XRu2AYhWO7ah+T0S9r1vSEpVlbsADpWXZGAdWwQQL2QoTszsdhVGmTRKkJTjiCpVitNBPipXkwSb2U9kRNhI140iIJsGgYhqG0wl73mRwqHvKlBG09QADIiJI4BHNBLjnIOKtKA8tTp3eJx8KZYj2TI-AKFJYhko5Sp-W-SVYQFDVL24gN8rBIyBMU0z+xUiy+DE0FJLZDlLTKlDbzUvFNO03Siv0spDNy5qlMq8y2LUKlrLgWz7KCsoQpchZ3M84quN894knkBIEtIvxkvIVL0pkpz7zCo5IsuaKLFizICM2pKUq4-a-mwbAmKy+pulyypHoMbLOAgAAjAArYBsHgfELry7SeIM-iFJasz2GqtRgQkqTGt1AaKs2FS2o03QeoKrqfrgfGSv62HBqx4aoSs313iKbAEi+uA-MmqAHMO1yag8rzguIeFF3W-zEu2u60tIbgvumgrQsrE7FqZlngamjn5oixbvNUM6uQSC6EUPY8j3108mR5fE410AjRVI2QlV0UhiASABJIQAEJ4zuB4EloKU3cFaxeCMR2OASQlnZdqlfa5f3SC6EOrbscPI90SBuCD9gQ7DiP4xTmB0+JwiIG4RPKkuRFfgL7h3nje2ndd+MYGkeYvZ9+MMCA3BoDTjPXazwU25gDv2Tj63i8FKAxCwLiK5gLviczpO4HH0RJ+Iae88JafR43LQTDi8uAuIEXdvu8XQaFradr20-ZP5vc4AgYkMEQY398Sw-L5PiWnuBG6j6vr-nr6FvjuOAaJ2AQHvo-Z+BsYFGwIuRYAMBJZ9FYv9IGINZQoKKhYNaMAEhoOBl6RMCCkFPWoH0ZyuDIoLiwUTCw9MEgYEBE4RMFD7z0w8guccewX6oFZHcUQTN8QkMljdd+osHpPWAXAAAcgAeUIjRN2QA)

**Comment by RyanCavanaugh** [comment]
> If we are to create a future of greater type-system interoperability, robust type-level accumulation is a must.

The intent of template literals is *not* to use them to write parsers using the type system. I can't stress this enough; I know everyone was doing it for fun in various issues and on twitter, but this is not what they're for and we're not going to expend engineering effort to enable this scenario. Transforms like this should happen out-of-band in processing steps *once* when the GraphQL changes; by doing this in the type system you're redoing this work literally on every keystroke.

**Comment by harrysolovay** [comment]
Perhaps I misunderstand, but are the types not incrementally computed? Aka., it's fine if the gql types are recomputed when the schema source string changes... but it should not need recomputing when changes are made elsewhere in your code (?).

While I understand why this is not a priority, I'm still uncertain about why moving parsing into TypeScript––as to unify the environments––would be undesirable. To me it feels like a natural step. I'd love to know why you feel like this would be a mistake.

**Comment by RyanCavanaugh** [comment]
Parsing artifacts like ASTs are preserved (and even partially re-used if edited where possible) between edits, but semantic information produced from type computation is recomputed fresh on each edit.

Moving parsing (for the sake of generating .d.ts) into the TypeScript pipeline is perhaps a thing we will consider eventually, but that isn't what template literals is for and it isn't designed to support that level of modification. It's for trivial transforms like `foo` -> `getFoo`.

**Comment by harrysolovay** [comment]
I can't even imagine what would go into producing semantic information incrementally... would this change even make sense in the long-term?

With [the parser-combinator-esque look of conditional assignability](https://github.com/microsoft/TypeScript/issues/40779), I'm surprised that type-level parsers (via template literals) wouldn't be the preferred mechanism. Would extracting DSL types from strings be wrong for any reason other than performance?

**Comment by RyanCavanaugh** [comment]
Incremental semantic analysis is what flow is trying to do and... they're not really able to do much else except making that work 🙂. It's a big trade-off.

Parsing with template literals is fine from a correctness perspective, but you're going to encounter a lot of performance issues doing this on too many large strings, and various depth limiters are subject to change from version to version as we try to stop runaway or useless recursion in other scenarios. If we ever make something that's specifically for turning external DSLs into something TS understands, we'll make it very clear that that's what it's for.

**Comment by harrysolovay** [comment]
Thank you for these wonderful explanations Ryan!

**Comment by harrysolovay** [comment]
@RyanCavanaugh one last thought. Perhaps when DSL processing becomes a priority, it could still occur through template literals, but be safeguarded from unnecessary re-processing with an intrinsic utility type that the compiler recognizes as expensive, and treats differently.

```ts
import {ParseGraphQLSchema} from "wherever";
import {schema} from "./schema";

type Parsed = Expensive<ParseGraphQLSchema<typeof schema>>;
```

**Comment by tjjfvi** [comment]
I find it very surprising that types are not cached at all.

While adding that for all types might be unreliable and unwarranted at the moment, I think some sort of marker for expensive types like @harrysolovay suggested would be a good idea; #41263.

Additionally, in trying to solve the issue with `GetAcc`, I noticed that it seems that `Parsed_LinkedListAcc` has infinite depth:
```ts
type Assert<A, B extends A> = B;
type T = Assert<Parsed_LinkedListAcc, Parsed_LinkedListAcc["next"]>;
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201026#code/KYDwDg9gTgLgBDAnmYcCyBDGBjAFgGWAwBMBLAOwHMAeAZSmzlBmHOIGc52YoLKAaOABFgAG1IBbUiyhMQLNp268qAPjgBeAFBw49Rs1Yc4AAwAkAbwoAzYLMIk+AX0sjxUmS6vlbsgPoASsDcTiZwAPxwDmRUcABccOTAAG52ANxaWqCQsHAUMtYY2KiYOLjUOlFEMZRyCsbKfPyVbpLSdnVGSjxNlQAqUBik4rGGilw9VFrqFpWi1XwJ0XwZusRibTIJrR7plTxDI5QJA4crWk6Z2dDw5BgSwWBFJVh4cLO617lIKHAAguREJp0K9yo0qIJwQIJipKKoMvtkKgAGoYUQAV2C1AAGuoNHBsQBtADWwEQEGsBIAugjPuAbggkXAAGKkKDcCq6XT6TrjKHNLnCDa7KAAVV5DUmlEqeLgqIxWI+XMJ0Q6FBBZWWVDoDEEO3aYtUVISpTwWpo+j1woNovUY2M5gsqqgXhsHUCwRgoUqgsiPPtnEdztdPg6+pkAOIp2GzhMPsFESF7gNkejRwlgdc1pkopDvjgadj8YTifDdlTgxjo3kXVMljdsjLLsshao3pLJcipvKzqtyZkglbcOLHYSSVSUBHgrHKTsU-iiVnk5LM4nqzgTnhF0yAHo91o9zuD-utD9ULQ8MAJBgm5x8QAiVjoiT3uAAHzgj5rbFfH-vFDAdEYF-T98jsQpihA+92GwNEMCgKCYNwK8MCgs8oPRchSAgch7wRM84AABXg9hgD8ABxUhUnYABRKAoGgTk9AYDMYV6XRu2AYhWO7ah+T0S9r1vSEpVlbsADpWXZGAdWwQQL2QoTszsdhVGmTRKkJTjiCpVitNBPipXkwSb2U9kRNhI140iIJsGgYhqG0wl73mRwqHvKlBG09QADIiJIsjKOouiGKgRzQS45yDirSgPLU6d3icfCmWI9kyPwChSWIDKOUqf1v0lWEBQ1S9uIDEqwSMgTFNM-sVIsvgxNBSS2Q5S1qpQ281LxTTtN08r9LKQyio6pS6vMti1Cpay4Fs+zwrKSKXIWdzPIqrjfPeJJ5ASVLSL8DLyCynKZKc+9oqOOLLgSiwksyAi9vSzKuJOv5sGwJj8vqboisqN6DAKzgIAAIwAK2AbB4HxW7iu0niDP4hTOrM9gGrUYEJKktrdVG2rNhU7qNN0QbSv6wG4BJyqRqRsb8YmqErN9d4imwBJ-rgPy5qgByztcmoPK8iLiHhRcdv8tKDue7LSG4f6FtKqLK0utb2c5iH5t5lbYrW7zVGurkEluhFD2PI8TdPJkeXxONdAI0VSNkJVdFIYgEgASSEABCeM7geBJaClb3BWsXgjDdjgEkJD3PapIOuRD0gukj+27BjuPdEgbhw-YSPo9j+NM5gHOKcIiBuDTypLkRX5S+4d54xd92vfjGBpHmf3A-jDAgNwaBs9zr388FbuYF79lk4divBSgMQsC42uYH7im8-TuAZ9EOfiAX4vCQXqeNy0ExkprgLiElo6XplqHxf2w7jqv2SRb3OAIGJDBEAtk+0rPu-L9l97gSPXPvff+H19BPx3HANE7AIAvzfh-T+qA-jsAdjJP4ggABCrE-iygwRkAifRgTINQdQR6P8pavXeoIMhwC-4wH+s5bawEqTwiAA)

**Comment by tjjfvi** [comment]
Looking at it further, this makes sense:
```ts
type Parse_LinkedListAcc<
  Src extends string,
  Acc extends object = {},
  Matched extends Match<string, SchemaDelimiters, string> = Match.First<Src, SchemaDelimiters>
> =
  [Matched] extends [Match<string, SchemaDelimiters, string>]
    ? {acc: Acc & Record<Matched["leading"], Matched>; next: Parse_LinkedListAcc<Matched["trailing"], Acc & Record<Matched["leading"], Matched>>}
    : {};
```
You're checking if `Matched` (which is constrained to `Match<string, SchemaDelimeters, string>`) is assignable to `Match<string, SchemaDelimiters, string>`. I think you're trying to determine if `Matched` is `never`; to do that, you can use `[Matched] extends ["__never__"] ? {} : ...`.

If I understand correctly, it should/could be written:
```ts
type Parse_LinkedListAcc<
  Src extends string,
  Acc extends object = {},
  Matched extends Match<string, SchemaDelimiters, string> = Match.First<Src, SchemaDelimiters>
> =
  [Matched] extends ["__never__"]
    ? null
    : {acc: Acc & Record<Matched["leading"], Matched>; next: Parse_LinkedListAcc<Matched["trailing"], Acc & Record<Matched["leading"], Matched>>};
```

Which works (read: doesn't throw 2589).

Applying this same thing to your first iteration, we get:
```ts
type Parse<
  Src extends string,
  Matched extends Match<string, SchemaDelimiters, string> = Match.First<Src, SchemaDelimiters>
> =
  [Matched] extends ["__never__"]
    ? {}
    : Record<Matched["leading"], Matched> & Parse<Matched["trailing"]>;
```

Which also works.

I suspect the reason the linked list fixed the 2589 was that typescript was deferring the infinite instantiation.

I suspect this `Parse` type will fail at (is the max depth 50?) delimiters (though I did not test this); [that can be worked around via HKTs](https://github.com/microsoft/TypeScript/issues/41111#issuecomment-716769825).

**Comment by tjjfvi** [comment]
A generic type-level parser I've been playing around with: [Playground Link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201014#code/FAUwHgDg9gTgLgAgN4F8DcxgEsB2cQwBmAhgMYgIDiIOBxcsAEgNIAqAPAJIA0CA8gD5kwBAgD6nAFwIeI8X2l9ucsbggBXONPU4A1jigB3HMtFrN0gERixO-UZw3LCcPhwATAM4I4ACyyeANrW5nCWALoIAPwyCNJ+AcGqOBphka40XrExCUEhKZoRcQi0AG4EpuK0YFoy+DD0sABKIJ7qADZwXLyCldW1nPWNMC1tnd38AsoomHAAnhAUAMLE7e3UOCwclC41md4bdAwwW+zEOHO853NTsRkeB0mcEUIAvAgAFDsAZMjJqdJOCgAJTBfoRDDAeaLBBgACM7EovE4byouzcWUODWOp2uVwuQhigU46T2DwQgUoTwikRiKzWG1OSJkQisxGcVgARpZIdCKPCAAyI3isVEfOTw4UIUXo-YIXCEAgIACq0RVsvJgyOsAAmlgQO13KMOl0FUrRXJRDFJcyZfcsmaYOqYqr7d4tdjdfrDcbxo7pQJLaI1TaRUI3fKcIqnaqXRqsh7hnqDUbWib2P6LcHsyGEbbw2SHVGlbH1RHE8dkz6037i06szns9a82H495-aXXYX3UNK97U2NTXWA0HG1bYS2A23I9HnWXu3VtTAqwP05nA2Ox82pXaFx21V2MT2lyvfUPZw3N43t-np-u4+Xe16U2eM8PL1frxOdwWjzOSwe04Vs+1aDm+F4bp+V43mGo5Qdm0iqtIZQEHB8GIcUKEwGhV4YchIDlNh8GiHhJQEah6HqvhhE4SRVFkTRm6kVhcHMeRRHBmxNHArMCz8nCApCre7ziqIgo-new6dkBT7Lv2r7rkGzZCa2Eb3vOf7AXJL41ue5qQU2E4qVOalSYBj4nvJungfpOHKRJpmztJFmetpoFru+BlbkZDl7mZD4Llpp7WYp8H2bejkAQFmmycFYGhcR4WqX5TnmYFsVWfFnm0d54kRSlUUaXKQWZR5EE5ZuSUmQVMZpTFlk6Vl5XEblAk-hVuH0SxLUIV17Edb1SEMRRxFcSNn5jRxTF9YxY6TaxM3jcUQ0sTxUJ8UZgkSSJEoCcZu5-uph7FRljVlbZhmCvtv5ykdMkNe5tbNTmynXZJqXRSdD2rk9F2tVt+WHf5RWaqdj16fWXlfldvlAx9IMJmDP0QyOYWbbDt3A8doPfQp2Uta9GPkndLlJqVv2QwNwaE4DmPw9jiO4yF+M9eOMO08TWP3a5cXnZTrOXXt7UC5xi1TT182s5Lo1ix10vTSt-UK5hSs5vLy0q9xvEwgAclA7gUO8nhwDAuAAOYIAAPggesG4E4SQjgxAALatBAZAUAACvQ9Q4N4SByOA0DwD4G0ADIgMQhAIO8lgCs41uWHCPKB5AsCIHyCAAKLtCArt4DHCAR1HVtUDAUDqBAGCiEH6ehzClDl5XhfBB8li8Dnec0HA9u8JYwIRMAMzYHgBAkOQCDezAnggIybDTliwynEgCCeDApDSMbps4GbvB8tItsgL3CAQDABEH-rR-hMf-QX3b1+RCgvCH-bQgB6It+fEGuTBKERSRU6TgaogERhXmvDeq8Tbmz3nxO+V9eCn3PjbS+9sb6uDgagx+cEYjW1EmOe2QFgh8kHp+GInAwSuH-gue2HUyGyRaHAdQMAcCvjDsQY2XBgiINKC8KGc1Fw83Jl0MB69ATBHAREBBZ9SjSECAAOgUYwSO7h2BKOICo8hlhuG8N4PIhRbCOFqI0Vw6ROii7sK6Jo7R4QBDhHCDAxY0gABiWBp6WIoTUF4vBP6sGIFgdonDLDghsQgFAfDerdRzMCUueDGwuLcYE4hISAEICcTlGITjpxb3NrQmQ4j15UL-AAAwACRICcSgMp-pRhwBQEUqmZD8mkEKXKUpSB-QAFl6CkF8JUpANS6lU3HCVM64wREQJqVIpBei5FGMCdY24MyDHuK0aYmxvAulwB6XY7x6C8lBMofY+uIBpC+P8YkviLxQnhM6pEyidzOojPBuwcZYjLASKOdw2RCi5FWLWbonZxzpBZzAKQdo6gDbsBBSbMgXQnG8HiRwzRSSBC3GyTvW4n9AhnICciy56yEA-M0cEx+Ny6IPNEDxRs1ElQ0o4jxYemc5msGnNcV+oh3gsojDM-0AANXg-oxC0mzjUBopAuj8ulIEHA6hnacgIA-VkUqZVyoVQQiMLKYisGlbK+VMAH6awIBgTOOL2BcoXGykJhdzV-kCIK3gPy+XCuhWKiVIodWqv1ey05Hq9UGo1WqbVKq-UELpca8OFizWsouOy6104eXDjEAK4cvLnWithewSVQbdUKqVdmz1-qFyauVTm-VhqYDhphIiroNq5SWtRLW8kdqU0OoUYKtNMLxWZvdcG3NxR80htJH+YtA6FXlt5BtAAgqQcgnhPBmt4MqBtgQXUZuVLwXQIA5hQGjqKcI60YRTxnuwT205D68AAMpZKgRiwu07Z3ztXV2mGR7Z40C2LwV5CAL0OJORST2nzpGyPtkcrFpLkT0JAIw5hr5rior7qUVY6gQCWAEIEAUDsD0UBZe8V9J6fYED9nIzu+c4B9w+B8AUwIB4CDQEAA)

It runs into 2589 very quickly.

**Comment by harrysolovay** [comment]
That's an interesting approach! Unfortunately––per Ryan's feedback––I don't think type-level parsers will be feasible in the near future :/

Especially considering large ASTs, such as that of GitHub's GraphQL API schema (parsed from ^30K loc).

I suppose we could file an issue to track the progression of a workflow tool for declaration generation. That might be the right move...

Although it doesn't feel as clean as would using template literals within the single environment. Hopefully this will become a possibility.
