### ISSUE TITLE
Error when overriding an overloaded method

### ISSUE THREAD

**Issue by jost-s** [microsoft/TypeScript#41252]
**TypeScript Version:**  4.0.3

**Search Terms:**
override extend class overload method

**Expected behavior:**
The extending class MCE overrides base class's `update` method and adopts the new signature.

**Actual behavior:**
Error because the extending method's signature doesn't match any of the base class's method signatures.

**Related Issues:**

**Code**
```ts
interface Entity {
    id: string;
    name: string;
    length: number;
}

class MC {
    update(id: string, attributes: Partial<Entity>): void;
    update(attributes: Entity & { id: string }): void;
    update(attrsOrId: string | Entity & { id: string }, attrs?: Partial<Entity>) {
        console.log(attrsOrId, attrs);
    }
}

class MCE extends MC {
    update(attributes: Entity & { id: string }, updateReason?: string): void {
        console.log(attributes, updateReason);
    }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class MC {
    update(attrsOrId, attrs) {
        console.log(attrsOrId, attrs);
    }
}
class MCE extends MC {
    update(attributes, updateReason) {
        console.log(attributes, updateReason);
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKLmGAnsg3gKGSOWABMAuZAZzClAHMBuQ4kOAWwkprpCZaIAbCHzAALSiACu7AEbRmAX3z4EguFSrIAsgGE8A5FIAOpOJAAUZbrQYAaZOduypkKpQAKcKGGBxBADzovtgAfACUlABuAPZkzMRGpuYQFk50Lm6UwZg4AGR4JBTUtnzIipHIsfGGJmaW6VQA8lAAksU8DMgAPmgY2MgFuEU2vPTlDo0A-J7evv5B-VgRBomJCDEgVDHCAHSCMfRpYLTNbaSTJ1BU4QnEysqq6po6uqjIEAAekCCkWnqrYh1FLHZyuCDuPohfKFawlMYTJL1CAAJQgGk2M3hDEq1VIgLWyA2Wx2EH2h1BGXBVAcwMgaIxIFuhgeQA)

**Comment by RyanCavanaugh** [comment]
This is a correct error; you could do something like this, which would crash:
```ts
interface Entity {
    id: string;
    name: string;
    length: number;
}

class MC {
    update(id: string, attributes: Partial<Entity>): void;
    update(attributes: Entity & { id: string }): void;
    update(attrsOrId: string | Entity & { id: string }, attrs?: Partial<Entity>) {
        console.log(attrsOrId, attrs);
    }
}

class MCE extends MC {
    update(attributes: Entity & { id: string }, updateReason?: string): void {
        if (updateReason !== undefined) {
            console.log(updateReason.toLowerCase());
        }
    }
}

const base: MC = new MCE();
base.update("", {});
```

**Comment by jost-s** [comment]
@RyanCavanaugh Thank you for the clarification, I understand. In your example `base` will be an instance of MCE in effect and call its update method, regardless of the declaration `const base: MC`.
Then there's no way to override overloaded functions with different signatures, correct?

This compiles fine but also crashes. What's the purpose of the declaration `const base: MC`?
`interface Entity {
    id: string;
    name: string;
    length: number;
}

class MC {
    update(attrsOrId: string | Entity & { id: string }, attrs?: Partial<Entity>) {
        console.log(attrsOrId, attrs);
    }
}

class MCE extends MC {
    update(attributes: Entity & { id: string }, updateReason?: string): void {
        if (updateReason !== undefined) {
            console.log(updateReason.toLowerCase());
        }
    }
}

const base: MC = new MCE();
base.update("", {});`
