### ISSUE TITLE
JSX: Convert HTML entities into UTF-8

### ISSUE THREAD

**Issue by majodev** [Microsoft/TypeScript#4125]
[HTML entities](https://facebook.github.io/react/docs/jsx-gotchas.html#html-entities) within JSX-style-nodes e.g. `<div>&nbsp;</div>` are currently not converted into their UTF-8 representation (e.g. [how babel does it](https://github.com/babel/babel/blob/b91b4a4dc03eff8647b669c8935b18f0c6d7ed81/packages/babylon/src/plugins/jsx/index.js#L62)). Are you planning to implement this?

**Comment by huan086** [comment]
Should this also handle &#?

It's crucial as typing `{` and `}` in jsx would be a pain without it. I use `&#123;` and `&#125;` as the substitute for `{` and `}`

**Comment by RyanCavanaugh** [comment]
@huan086 please log a separate issue if that doesn't work
