### ISSUE TITLE
Assertions do not narrow types when used as operand of the comma operator.

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#41264]
**TypeScript Version:**  4.1.0-dev.20201026

**Search Terms:** assert comma operator

**Code**

`foo1` and `foo2` should be equivalent but the assertion in `foo2` does not narrow they typing of `param`.

```ts
declare function assert(value: any): asserts value;

function foo1(param: number | null | undefined): number | null { 
  const val = param !== undefined;

  if (val) {
    assert(param !== undefined);
    return param
  } else {
    return null;
  }
}

function foo2(param: number | null | undefined): number | null { 
  const val = param !== undefined;
  return val ? (assert(param !== undefined), param) : null;
                                          // ^^^^^ Still typed as number | null | undefined
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

```
Type 'number | null | undefined' is not assignable to type 'number | null'.
  Type 'undefined' is not assignable to type 'number | null'.(2322)
```

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20201026#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAKANygmRAC4DUBPASkaJLMPmtpADcAWABQolOmx4kOHAEZyAB1hQAto1TJVAI1LwAPvE0QIB+GlCIsqEMHZGtumGeOmA3vFHx4YPIQy8NPAAvPDKMGrwAITBoRYgVjbAwmIi3liI8FQ0rPBuXt4ExKQU4ZExcaiW1rasKYXwcBjIMPhlqgUAvvAgECR5Bd5NLfiu9fCdopOpEpi4+IiyAExKKuoOOnqGrmbxibUajlsOJnmeaT5+AXwhYWvRseZVCTXJBcOtgaYA-FmcJasIqoHpVqklWAAaO5A3KHEzjBqIpHIlGo+AAenR8AAerjcfAAMrYU4YZiKWxFDZOFzIU6GPavKZAA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This would probably be a good first bug for anyone wanting to learn how the control flow graph works

**Comment by MartinJohns** [comment]
Related issue: #41183
