### ISSUE TITLE
Group object keys by prototype

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#41279]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1

**Search Terms**
- suggest / suggestion
- IntelliSense

---

Chromium based browsers (here Microsoft Edge) group object keys by prototype inheritance, I'd love to see this in VSCode

![msedge_2020-10-27_16-49-30](https://user-images.githubusercontent.com/30108880/97326622-7863a000-1874-11eb-8f0e-c785101bddaa.png)

**Comment by RyanCavanaugh** [comment]
We don't track this sort of information at all, so have no way to surface this information. The useful part of this is that the non-Object members are at the bottom, and we already hide those, so I think the current behavior qualifies as "good enough"
