### ISSUE TITLE
Type of variable erroneously narrowed to 'never'

### ISSUE THREAD

**Issue by FlorentP42** [microsoft/TypeScript#41270]
**TypeScript Version:**  ~3.5.3

**Code**
```ts
import { Component } from "@angular/core";

export interface Abc {
  name: string;
}

export interface Abcd {
  toto: string;
}

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})

export class AppComponent {
  name = "Angular 6";
  a: Abc | Abcd;

  constructor() {
    this.a = {
      name: "sss"
    };
    console.log(typeof this.a, "---");
    console.log(this.instanceOfA(this.a));
    if (this.instanceOfA(this.a)) {
      console.log(this.a.name);
    } else {
      console.log(this.a.toto); // Why is this.a type marked as 'never' here? Should be 'Abcd', right?
    }
  }

  instanceOfA(object: any): object is Abc {
    return "name" in object;
  }
}
```

**Expected behavior:**
Type of 'this.a' variable is narrowed to 'Abc ' inside the if statement and to 'Abcd' inside the else statement.

**Actual behavior:** 
Type of 'this.a' variable is narrowed to 'Abc|Abcd ' inside the if statement and to 'never' inside the else statement, causing runtime error "TS2339: Property 'toto' does not exist on type 'never'."

**Playground Link:**
https://stackblitz.com/edit/angular-cluhyc?file=src%2Fapp%2Fapp.component.ts

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/27103

**Comment by MartinJohns** [comment]
The control flow analysis can see that `this.a` is never re-assigned again within the function, so the compiler ignores your type annotation of `Abc | Abcd`, assuming the type is always `Abc` (because that's what the compiler sees).

If you adjust your code you will see the behavior you expect:

    this.a = Math.random() > 0.5 ? { name: "sss" } : { toto: 'foo' };

**Comment by FlorentP42** [comment]
This is not something I can change in the actual code, here I used a simplified code to showcase my problem, but in the actual code "this.a" is affected somewhere else and it can actually contain both values, the behavior is still the wrong one though.

**Comment by MartinJohns** [comment]
> but in the actual code "this.a" is affected somewhere else

In that case you're affected by #9998.

Your workaround is to use a type assertion to specify the type:

    this.a = { name: "sss" } as Abc | Abcd;

Or with slightly less redundancy:

    this.a = { name: "sss" } as this['a']

**Comment by FlorentP42** [comment]
Okay so I thought the point of "object is Abc" was precisely to avoid having to specify manually "as Abc" whenver I want to use my variable. (variable that may at some point be instanciated from JSON representation, which is why I cannot always explicitly specify the type of it using "as Abc" during instancitaion).

**Comment by MartinJohns** [comment]
> Okay so I thought the point of "object is Abc" was precisely to avoid having to specify manually "as Abc" whenver I want to use my variable.

You misunderstood me. I said `as Abc | Abcd`, **not** `as Abc`. Then still use your `instanceOfA` check.

You're running into an edge case where the control flow analysis narrows the type of your variable because it's unaware of the modification within other functions that you call. As a result the type of your `this.a` variable is **always** inferred to be `Abc` (ignoring your explicit type annotation), while it actually should be `Abc | Abcd` (due to the side-effects in your other functions).

**Comment by FlorentP42** [comment]
Hmmm then I bet I will have to

**Comment by MartinJohns** [comment]
Here's a simplified example without all that Angular crap (sorry, not sorry :-P):

    type A = { a: string }
    type B = { b: string }

    function isA(value: A | B): value is A { return 'a' in value }
    function modifyValue(): void { value = { b: 'b' } }

    let value: A | B = { a: 'a' }
    modifyValue()

    // Despite the type annotation "A | B" on value the type is inferred to be "A",
    // because the control-flow analysis does not see another assignment to the variable.
    // It is unaware of the modification within the "modifyValue()" function (issue #9998).
    if (isA(value)) { // value is of type A.
      value
    } else {
      // Because according to the type checker the type of value can only ever be "A",
      // and we checked for "A" already in the if-branch, the type now is narrowed to "never".
      value
    }

    // To fix it you could use a type assertion to widen the type again:
    let value2: A | B = { a: 'a' } as A | B
    if (isA(value2)) { // value2 is now of type A | B.
      value
    } else {
      value
    }

**Comment by FlorentP42** [comment]
Okay so thanks to your example I was able to summarize even better what problem I am actually facing, which is:
```
type A = { a: string }
type B = { b: string }

function isA(value: A | B): value is A { return 'a' in value }
function modifyValue(): void { value = { a: 'a' } }

let value: A | B
modifyValue()

if (isA(value)) { 
  value
} else {
  value // here type is 'never'
}
```
The problem is, this only happen in the actual code, the example does not have this issue if I update the code on stackblitz... Could this have been fixed in some later angular version?

**Comment by MartinJohns** [comment]
In your updated example you don't assign any value to `value`. So the compiler does not make the assumption of "it's always `A`" anymore.

**Comment by FlorentP42** [comment]
Yes that's how it is in the actual code, yet I am still facing the erroneous 'never' type in the else in the actual code, while the updated example works fine...

**Comment by MartinJohns** [comment]
> Yes that's how it is in the actual code

This is not how it is, neither in the code of your first post or in your Stackblitz: https://stackblitz.com/edit/angular-cluhyc?file=src%2Fapp%2Fapp.component.ts

In line 20 you assign a value to the variable. So within that function the compiler assumes the value is always of the type of your assigned value.

My example adjusted would be:

    let value: A | B

    function doStuff() {
      value = { a: 'a' }
      modifyValue()

      if (isA(value)) { 
        value
      } else {
        value // here type is 'never'
      }
    }

**Comment by FlorentP42** [comment]
> This is not how it is, neither in the code of your first post or in your Stackblitz: https://stackblitz.com/edit/angular-cluhyc?file=src%2Fapp%2Fapp.component.ts

You are right, what I mean is: the original example was an inaccurate representation of what is actually happenning in my application. Which is why I posted an updated code sample here: https://github.com/microsoft/TypeScript/issues/41270#issuecomment-717211986

**Comment by MartinJohns** [comment]
> Should I update the main code with this?

:shrug: You should update the example. Because the code from https://github.com/microsoft/TypeScript/issues/41270#issuecomment-717211986 does not show the behavior of narrowing to `never`. Not in the TypeScript playground, nor in the Stackblitz of yours (copying over the code).

Without seeing the actual code or a matching example I can just guess that your problem is a combination of the two issues I mentioned earlier.
