### ISSUE TITLE
Module resolution fails when substituion path exists but original path directory does not

### ISSUE THREAD

**Issue by Gozala** [microsoft/TypeScript#41281]
**TypeScript Version:**  3.7.x-dev.201xxxxx

It appears that 

Path substitution fails to resolve module if original path (path before substitution) directory does not exists. E.g. if module is importing module `bar` and corresponding `package.json` has `"main": "src/index.js"` but directory `src` does not exists, but substitution path like `dist/src/index.d.ts` exists module resolution fails.

Here is the repo with minimial reproducible example  illustrating this problem https://github.com/Gozala/bug-tsc-path-substitution/tree/main-field-bug

P.S.: Appears to fail with `typescript@next` as well.

**Search Terms:**

- typeVersions
- path mapping

**Code**

### `package.json`

```json
{
  "name": "bar",
  "main": "src/index.js",
  "typesVersions": {
    "*": {
      "*": [
        "dist/*"
      ]
    }
  }
}
```

### `dist/src/index.d.ts`

```ts
declare class Bar {
}

export default Bar
```

**Expected behavior:**

Module resolution should succeed

**Actual behavior:**

Module resolution fails 

**Playground Link:** 

This involves multiple files, please see example repo instead
https://github.com/Gozala/bug-tsc-path-substitution/tree/main-field-bug

**Related Issues:**

**Comment by rbuckton** [comment]
This doesn't appear to be a bug, but is the intended behavior of the feature. `typesVersions` is only used to override types specific to a version of TypeScript given a module that we could have resolved *without* `typesVersions`. Even though you have specified a TS version of `*`, `typesVersions` still requires a valid original path to override. As such, y\You must have a file at the `main` path for us to start with, even if that file is an empty `index.d.ts` or `index.js` file.
