### ISSUE TITLE
Poor deprecated messages - types should almost never be displayed.

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#41286]
```ts
/** @deprecated - this is bad advice */
declare function crossTheStreams(): void

crossTheStreams()
```

**Expected:** `'crossTheStreams' is deprecated.`
**Actual:** `'(): void' is deprecated`

Notice the type in place of the entity name, notice the lack of a period at the end.

![image](https://user-images.githubusercontent.com/972891/97368025-544d9200-1867-11eb-817a-7720211d43b8.png)

**Comment by AnyhowStep** [comment]
I assume this isn't as simple as using `signature.declaration.name.escapedText`?

Like, `signature.declaration` could be `JSDocSignature`.
How would you get the function name from a `JSDocSignature`?

**Comment by DanielRosenwasser** [comment]
> This should normally happen only with overloads.

**Only** if not every overload is deprecated. If all overloads are deprecated, showing the type doesn't help.

> I assume this isn't as simple as using `signature.declaration.name.escapedText`?

It is better to use one of the various helpers for printing out the expression when a name is available. We've done this in a couple of places where we try to special case this when the invoked expression is an identifier/property access.

**Comment by DanielRosenwasser** [comment]
`tryGetPropertyAccessOrIdentifierToString` is one

**Comment by DanielRosenwasser** [comment]
`getCalledExpressionName` is also similar, but is weird in that it'll give a partial result if the expression gets a bit too complex (e.g. `foo().bar.baz` will give you `bar.baz`).

Probably what you want is just to do something even more basic where you try grabbing the `name.text` off a property access, the text off an Identifier, and stop there. Not sure of any other helper functions that do this, but I'm sure this isn't the only place.

**Comment by AnyhowStep** [comment]
I see `getNameOfDeclaration`, too

**Comment by DanielRosenwasser** [comment]
The declaration name isn't always useful because it might be anonymous, it might come from a default import. The most relevant name for this error message is the one that is being used locally.

Something useful might be to provide a related span linking back to where the deprecation comes from.

**Comment by AnyhowStep** [comment]
I have no clue what I'm doing but I tried something like this,
```ts
        function checkDeprecatedSignature(signature: Signature, node: CallLikeExpression) {
            if (signature.declaration && signature.declaration.flags & NodeFlags.Deprecated) {
                const suggestionNode = getDeprecatedSuggestionNode(node);
                const deprecation = getJSDocDeprecatedTag(signature.declaration);
                if (deprecation == undefined) {
                    errorOrSuggestion(/*isError*/ false, suggestionNode, Diagnostics._0_is_deprecated, signatureToString(signature));
                } else {
                    const diagnostic = createDiagnosticForNode(
                        suggestionNode, 
                        Diagnostics._0_is_deprecated, 
                        signatureToString(signature) + "lol"
                    );
                    addRelatedInfo(
                        diagnostic,
                        createDiagnosticForNode(deprecation, Diagnostics.The_implementation_signature_is_declared_here)
                    );
                    suggestionDiagnostics.add({ ...diagnostic, category: DiagnosticCategory.Suggestion });
                }
            }
        }
```

And got something like this,
![image](https://user-images.githubusercontent.com/5655961/97376003-9fc96580-1892-11eb-9c49-17a7d01249ac.png)

(I know it's the wrong diagnostic lol)

**Comment by DanielRosenwasser** [comment]
> (I should remove the "lol"),

But it's so fun!

Yeah, I don't know what the code currently looks like, but on the `node`, you should be able to `getInvokedExpression` and get the text using any of the methods I described above.

**Comment by AnyhowStep** [comment]
I noticed this doesn't produce the deprecation notice.

![image](https://user-images.githubusercontent.com/5655961/97376417-aefce300-1893-11eb-91fd-ea43649dcf45.png)

**Comment by AnyhowStep** [comment]
I think I've got it down,
![image](https://user-images.githubusercontent.com/5655961/97378329-81feff00-1898-11eb-93a6-5b6e0d306c17.png)

**Comment by AnyhowStep** [comment]
@DanielRosenwasser 
Is it normal for `Symbol.declarations` to be a non-empty array but for `valueDeclaration` to be `undefined`?

I assumed `valueDeclaration` was just a shorthand for `declarations[0]`.

This happens in `tests/cases/fourslash/jsdocDeprecated_suggestion1.ts`

Smaller repro,
```ts
//a.ts
/** @deprecated */
export function bar() {

}

/** @deprecated */
export type QW = 3;
```

```ts
//b.ts
import { bar, QW } from './a';
```

The import of `bar` is fine. It has `valueDeclaration` set.

However, `QW` has `declarations.length == 1` but `valueDeclaration == undefined`.

**Comment by AnyhowStep** [comment]
It also seems like `tryGetPropertyAccessOrIdentifierToString()` doesn't like namespaces + optional chains.

In `tests/cases/fourslash/jsdocDeprecated_suggestion1.ts`,
the line containing `foo?.[[|"faff"|]]?.()` trips up `tryGetPropertyAccessOrIdentifierToString()`.

Minimal repro,
```ts
export namespace foo {
    /** @deprecated */
    export function faff() { }
}

foo?.["faff"]?.();
```

![image](https://user-images.githubusercontent.com/5655961/97382792-8cbe9180-18a2-11eb-9508-bc6e67a735f7.png)
![image](https://user-images.githubusercontent.com/5655961/97382978-e757ed80-18a2-11eb-9490-286d3628c1c6.png)

-----

If you replace the namespace with a variable, it works.
![image](https://user-images.githubusercontent.com/5655961/97382852-b2e43180-18a2-11eb-9e27-f4d99aa3c0fb.png)

**Comment by Kingwl** [comment]
>Is it normal for Symbol.declarations to be a non-empty array but for valueDeclaration to be undefined?
>I assumed valueDeclaration was just a shorthand for declarations[0].

Basically, As the name of `valueDeclaration`, Only existed when some symbol could be an `value`

**Comment by AnyhowStep** [comment]
It trips me up, though, because I see it declared as type `Declaration`, not `Declaration|undefined`.
![image](https://user-images.githubusercontent.com/5655961/97390162-8cc68d80-18b2-11eb-9ca7-ce3a1c88ade1.png)

It also doesn't make sense for a symbol to exist without a declaration, in my head.

**Comment by Kingwl** [comment]
`First value declaration` means `first declaration of value`

You can also find all declarations in the `declarations ` field

**Comment by AnyhowStep** [comment]
I see I had the wrong idea of what `valueDeclaration` was. It's conditionally set.
![image](https://user-images.githubusercontent.com/5655961/97391044-a9fc5b80-18b4-11eb-9c01-be0143bad947.png)
