### ISSUE TITLE
System output dependency missing

### ISSUE THREAD

**Issue by guybedford** [Microsoft/TypeScript#4128]
I'm making some progress getting the TypeScript tests running for SystemJS builder. Currently this issue and https://github.com/systemjs/builder/issues/262 are the blocking issues as far as I can tell.

For the following input source running against the currently nightly:

```javascript
import 'jquery-cdn';
import '@empty';
import { dep } from "./second.js";
import './amd.js';
import './component.jsx!./jsx.js';
```

The output from TypeScript is:

```javascript
System.register(['jquery-cdn', '@empty', './amd.js', './component.jsx!./jsx.js'], function(exports_1) {
    var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
    var p, test;
    return {
        setters:[
            function (_) {},
            function (_) {},
            function (_) {},
            function (_) {}],
        execute: function() {
            exports_1("p", p = 5);
            test = (function (_super) {
                __extends(test, _super);
                function test() {
                    _super.call(this);
                }
                return test;
            })(Object);
            exports_1("test", test);
        }
    }
});
```

Note how the `./second.js` dependency is missing in the above.

Just let me know if there is anything further I can do to help, really appreciate the work to get these workflows running.

**Comment by vladima** [comment]
When processing the whole program TypeScript compiler will elide imports that are not used in as values. There is a compiler option [isolatedModules](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2025) to relax this behavior and suppress elision, it is used when files are compiled separately.Currently it used automatically when user calls [transpile/transpilerModule](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L1788) functions and also it can be set via compiler API.

**Comment by guybedford** [comment]
Ah I see, ok sure so by just making sure `dep` is used I was able to fix this! Awesome, thanks.
