### ISSUE TITLE
Support Intl.NumberFormat.formatToParts in ES2018

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#41299]
**TypeScript Version:**  Nightly

**Search Terms:**

**Code**

```ts
new Intl.NumberFormat().formatToParts
```

**Expected behavior:** Should be supported

**Actual behavior:** It requires ESNext

**Playground Link:** https://www.typescriptlang.org/play?target=5#code/HYUw7gBAksAuA2A6AcgVwLYCMQCcBiA9jugIawAUAlIgGZGmwAqBACiTrAM5A

See also https://github.com/tc39/proposals/blob/master/ecma402/finished-proposals.md

**Comment by sarathps93** [comment]
Hi @RyanCavanaugh Is it ok if I work on this?

**Comment by saschanaz** [comment]
Sure, I'm not working on this at least.

**Comment by Scharkee** [comment]
@RyanCavanaugh After moving `Intl.NumberFormat.formatToParts` to `es2018.intl.d.ts`, `esnext.intl.d.ts` remains empty. Should it be kept that way, or should it be removed completely?

**Comment by saschanaz** [comment]
You can remove `esnext.intl.d.ts` and make `esnext.intl` point to `es2018.intl.d.ts` in `src/compiler/commandLineParser.ts`.

**Comment by orta** [comment]
This is in with https://github.com/microsoft/TypeScript/pull/45647 👍🏻
