### ISSUE TITLE
Passing deprecated function as callback does not give deprecation suggestion

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#41295]
**TypeScript Version:**  4.1.0-dev.20201027

**Search Terms:** Deprecated tag, callback

**Code**

```ts
/**
 * @deprecated
 */
function foo () {}

/**
 * Expected: Deprecation warning
 * Actual: Deprecation warning
 */
foo;

function bar (x : () => void) {
    x();
}


/**
 * Expected: Deprecation warning
 * Actual: No deprecation warning (?)
 */
bar(foo);

/**
 * @deprecated - Not random enough
 */
const x = 4;

/**
 * Expected: Deprecation warning
 * Actual: Deprecation warning
 */
x;

function baz (x : number) {

}

/**
 * Expected: Deprecation warning
 * Actual: Deprecation warning
 */
baz(x);
```

**Expected behavior:**

`bar(foo);` should trigger deprecation suggestion

**Actual behavior:**

`bar(foo);` does not have suggestion

**Playground Link:** [Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201027#code/PQKhCgAIUgBATApgBwE6IMYEMAuj5QjDgBmArgHYY4CWA9hZCXXZABQCUkA3gL7jhQEaJACiAD2SY88AFyQAIinTZaDSAHcsqCjQoBzQpACC1MlgA28pWky56jLTr2HoxZnQDcA8lTWMAI212cUh5TkgAXgA+SAA3Ohp4Lm4oSHTxTm9+ASEjCSlqfGtlO39NbV0DI1MccytIADlWJFtVBwrnA3YAfg5CYiDUNg8Ob0EwIwRS1XxIAFomuhxIVCwKeDoAW0hECjoyfQALAfAMBgBnFdDIyAAWcbyRAulixRn7dScq1xha+pKbU+jkqLlO4nGvmoHSCAC8QmFIBQyFsAohUCkBDknjAXkU5O8geVvmCRP9LICVMDOj9TnC2OIxkA)

**Related Issues:** None

**Comment by Kingwl** [comment]
> Demo driver debug is my favorite -- @DanielRosenwasser
