### ISSUE TITLE
VS2015 Crash on private

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#4129]
Hi,

There is a terrible crash that shutdown visual studio 2015... an Unknown Hard Error!

The bug appears when doing refactor, making an abstract call and get some accessor on privates.

So, when we copy the old stuff to the class that does not have access anymore to the private, we trying to rename the private to use the accessor and ... it crash.

#### Example:

    class DoToMuchSharedStuff{
      private _privateField:number;

      doStuff(): void{
        this._privateField++;
      }
    }

#### then refactoring to:

    class SharedStuff{
      private _privateField:number;

      get privateField():number{ return this._privateField;}
      set privateField(value:number) { this._privateField = value; }

      doStuff(): void{
    
      }
    }

    class DoLessStuff {

      doStuff(): void{
        this._privateField++;
      }
    }

And now, when simply clicking on the underscore of this._privateField to remove it... crash.

**Comment by DanielRosenwasser** [comment]
Not able to get a solid repro - @sebdoucet, if you simply paste the second snippet into your editor, do you get a crash? Which `_privateField` do you put your cursor on to trigger the problem?

**Comment by sebdoucet** [comment]
I can't have too a solid repro without getting you our entire project... and I can't do that.
What I can say is it appear on every one one the team with this exact context and we can reproduce the crash multiple time, the only way to avoid crash when renaming the variable is to select before the dot like "._" en replace it. But each time we reload the project and click on the problematic variable, it crash.
Our project have thousand of typescript lines and I think it can't be reproduce like that, I just explain the contains, I can't get you a repro.

**Comment by mhegazy** [comment]
Can  you share the stack from your event log? (Event Viewer / Windows Logs / Application, there should be an Error event from .Net Runtime as a source)

**Comment by sebdoucet** [comment]
Application : devenv.exe
Version du Framework : v4.0.30319
Description : l'application a demandé l'arrêt du processus via System.Environment.FailFast(message de la chaîne).
Message : System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1.ProcessNewTags(IEnumerable`1 spansToCompute, Nullable`1 oldTextChangeRange, ImmutableDictionary`2 newTags)
   at Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingTagSource.ProcessNewTags(IEnumerable`1 spansToCompute, Nullable`1 oldTextChangeRange, ImmutableDictionary`2 newTags)
   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1.<RecomputeTagsAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1.ProcessNewTags(IEnumerable`1 spansToCompute, Nullable`1 oldTextChangeRange, ImmutableDictionary`2 newTags)
   at Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingTagSource.ProcessNewTags(IEnumerable`1 spansToCompute, Nullable`1 oldTextChangeRange, ImmutableDictionary`2 newTags)
   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1.<RecomputeTagsAsync>d__32.MoveNext()<---

Pile :
   à System.Environment.FailFast(System.String, System.Exception)
   à Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   à Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   à Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   à Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task, System.Object)
   à System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
   à System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   à System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   à System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   à System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   à System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
   à System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
   à System.Threading.Tasks.Task.FinishContinuations()
   à System.Threading.Tasks.Task.FinishStageThree()
   à System.Threading.Tasks.Task.FinishStageTwo()
   à System.Threading.Tasks.Task.Finish(Boolean)
   à System.Threading.Tasks.Task`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   à System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
   à System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeCore(System.Threading.Tasks.Task)
   à System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task)
   à System.Threading.Tasks.Task.FinishContinuations()
   à System.Threading.Tasks.Task.FinishStageThree()
   à System.Threading.Tasks.Task.FinishStageTwo()
   à System.Threading.Tasks.Task.Finish(Boolean)
   à System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   à System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   à Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1+<RecomputeTagsAsync>d__32[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   à System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   à System.Threading.Tasks.Task.FinishContinuations()
   à System.Threading.Tasks.Task.FinishStageThree()
   à System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   à System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   à Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider+TagProducer+<ProduceTagsAsync>d__4.MoveNext()
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   à System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   à System.Threading.Tasks.Task.FinishContinuations()
   à System.Threading.Tasks.Task.FinishStageThree()
   à System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   à System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   à Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler+<PerformSemanticFeatureOperationAsync>d__15`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   à System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by mhegazy** [comment]
@vladima is this the same issue you fixed with @CyrusNajmabadi?

**Comment by vladima** [comment]
@mhegazy, @CyrusNajmabadi has recently finished a serious revision of tagging infrastructure, bits mentioned in the stacktrace were also changed  so I'd say that is likely to be fixed

**Comment by mhegazy** [comment]
@vladima and @CyrusNajmabadi can you link this issue to the changes on the Roslyn side. just for tracking purposes.

**Comment by CyrusNajmabadi** [comment]
Here's the PR for the large tagger refactoring i did: https://github.com/dotnet/roslyn/pull/4046
