### ISSUE TITLE
variable assignments are not taken into account if occur only in the callback

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [microsoft/TypeScript#41305]
**TypeScript Version:**  3.7.x-dev.201xxxxx
typescript@^4.1.0-dev.20201028:

**Search Terms:**

**Code**

```ts
function fizz (): string {
  let foo: object | null = null;
  [{}].forEach(i => (foo = i));
  return foo ? 'foo' : 'bar';
}
```

**Expected behavior:**
`foo` is `object | null` in `return` statement

**Actual behavior:**
![image](https://user-images.githubusercontent.com/15625235/97430379-1b6df580-1919-11eb-822d-28715c73534f.png)

**Playground Link:** 
https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMGAvViAUBKAXIgZygCcYwBzRAbwChFEAbAUymTjnzgCMArJ6RAB9EYEAwaIAvCLEMA3HUQBtKgF8AugDpgcYgFEAhhAAWmGFIB8WHXCmIY2bAvrEWIYkhuIA-IgDkNn6I+H5cBsR+Cqo0QA

**Related Issues:**

**Comment by MartinJohns** [comment]
Another duplicate of #9998. What search terms did you use to look for existing issues? You didn't fill out that part of the issue template. :-)

**Comment by jacekkarczmarczyk** [comment]
Well, tbh i couldn't think of good search terms that wouldn't show me hundreds of issues. Sorry for this, closing as a duplicate and thanks for pointing the right issue
