### ISSUE TITLE
Windows Script Host can't execute tsc.js

### ISSUE THREAD

**Issue by PolarGoose** [microsoft/TypeScript#41311]
**TypeScript Version:**  4.0.5

**OS version:** Windows 10.0.19041 Build 19041

**Search Terms:**
Windows Script Host. JScript. Wscript. Cscript.  ECMA 262 (ECMAScript Edition 3).

**Expected behavior:**
tsc compiler should run using cscript command:
`> cscript C:\typescript-4.0.5\package\lib\tsc.js`

**Actual behavior:**
```
> cscript .\typescript-4.0.5\package\lib\tsc.js
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

C:\my\git-repos\tproject\build\package\lib\tsc.js(478, 9) Microsoft JScript compilation error: Expected identifier, string or number

**Comment by RyanCavanaugh** [comment]
Windows Script Host is not a supported runtime environment

**Comment by PolarGoose** [comment]
@RyanCavanaugh, thank you for the information. But as far as I see it was supported in the past, for instance there are commits like this: https://github.com/microsoft/TypeScript/commit/a64db42337afc44f9893ef22ff326cee19a905bf which fix support for WSH

**Comment by RyanCavanaugh** [comment]
That's correct; it was supported and now it's not

**Comment by PolarGoose** [comment]
ok, no problem. Thank you for the information. Do you think it could be a good idea to add this information in the documentation?

**Comment by fairking** [comment]
https://stackoverflow.com/questions/60693700/microsoft-jscript-compilation-error-800a0404
