### ISSUE TITLE
'in' should not operate on primitive types

### ISSUE THREAD

**Issue by millsp** [microsoft/TypeScript#41317]
**TypeScript Version:**  4.1.0-dev

**Search Terms:**
operator in exception crash unhandled

**Code**

```ts
const hasKey = <A, K extends string | number | symbol>(
    thing: A,
    key: K,
): boolean => {
    return key in thing;
};

hasKey(123, 'hello'); // TypeError exception
```

**Expected behavior:**

TS should expect `A` to be an object

**Actual behavior:**

TS didn't detect the potential crash

**Playground Link:**  https://www.typescriptlang.org/play?ts=4.1.0-beta#code/MYewdgzgLgBAFgQwgaQKYE8YF4YB4CCANDMjKgB5SpgAmEM0ATgJZgDmMAPjGAK4C2AI1SMuDdEJAAbAHwAKAFAxlMKHFZsAXDCJKVAawzbkhBQEptgkNNQIw2GTADee5Y1RReje4cytV6uwA3AoAviEKiCgYcgCMAEwAzMQA5HCoUlIgKWZBMAD0+TAAKugADqgAooyMIKIUwKhlUMzgCkA

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
This is weird because we'd potentially allow `String` but not `string` - but that's probably okay.

**Comment by DanielRosenwasser** [comment]
Approved.

To avoid breakage on unconstrained type parameters, we're thinking to check if the type is assignable to the union of all primitive types - or if it contains any primitive type (e.g. `number`, `string`, `boolean`, `bigint`, `symbol`, `null`, `undefined`). `isTypeAssignableToKind` might be one thing to use here, if not, just use `isAssignableTo`.

If that's still too breaky, `maybeTypeOfKind` is a helper that can do this pretty quickly.

The more thorough version of this would be to check whether the type on the right side of the `in` has to be assignable to `object`. We could run that on the RWC.

**Comment by DanielRosenwasser** [comment]
To be explicit, this is all about the type on the right of the `in` operator. The left can be unconstrained, and maybe we should reconsider that at a later date.

**Comment by orange4glace** [comment]
If possible, I would like to make a PR for this.

**Comment by orange4glace** [comment]
Which line should emit error, 1) or 2)?

```
const hasKey = <A, K extends string | number | symbol>(
    thing: A,
    key: K,
): boolean => {
    return key in thing;
    ~~~~~~~~~~~~~~~~~~~~
    1) TypeError exception
};

hasKey(123, 'hello');
~~~~~~~~~~~~~~~~~~~~
2) TypeError exception
```

**Comment by andrewbranch** [comment]
@orange4glace the former. Are you still interested in doing this? The change would be in checker.ts around line 29940:

```typescript
function checkInExpression(left: Expression, right: Expression, leftType: Type, rightType: Type): Type {
    if (leftType === silentNeverType || rightType === silentNeverType) {
        return silentNeverType;
    }
    leftType = checkNonNullType(leftType, left);
    rightType = checkNonNullType(rightType, right);
    // TypeScript 1.0 spec (April 2014): 4.15.5
    // The in operator requires the left operand to be of type Any, the String primitive type, or the Number primitive type,
    // and the right operand to be of type Any, an object type, or a type parameter type.
    // The result is always of the Boolean primitive type.
    if (!(allTypesAssignableToKind(leftType, TypeFlags.StringLike | TypeFlags.NumberLike | TypeFlags.ESSymbolLike) ||
          isTypeAssignableToKind(leftType, TypeFlags.Index | TypeFlags.TemplateLiteral | TypeFlags.StringMapping | TypeFlags.TypeParameter))) {
        error(left, Diagnostics.The_left_hand_side_of_an_in_expression_must_be_of_type_any_string_number_or_symbol);
    }
    // 👇 here
    if (!allTypesAssignableToKind(rightType, TypeFlags.NonPrimitive | TypeFlags.InstantiableNonPrimitive)) {
        error(right, Diagnostics.The_right_hand_side_of_an_in_expression_must_be_of_type_any_an_object_type_or_a_type_parameter);
    }
    return booleanType;
```

**Comment by orange4glace** [comment]
@andrewbranch Sure! It would be very happy if I can do this.
Thanks for the detailed guidence! I'll investgate on this ;)

**Comment by jonhue** [comment]
Hey @orange4glace, are you still looking into this? Otherwise, I'd be interested in picking this up today! 🙂

**Comment by orange4glace** [comment]
@jonhue Oh, sure! I haven't done anything so far, so feel free to do what you want 🙂

**Comment by jonhue** [comment]
@DanielRosenwasser I don't know about the usual process. Do you generally close issues once their fixes have been merged or once their fixes are published in a release? Just wanted to remind you about this one as this may have been forgotten when making last-minute changes to the pr 🙂

**Comment by andrewbranch** [comment]
My bad, I should have auto-closed it with #42288. Thanks!

**Comment by jungeun-cho** [comment]
@andrewbranch 
```ts
const hasKey = <A, K extends string | number | symbol>(
    thing: A,
    key: K,
): boolean => {
    return key in thing;
};

hasKey(123, 'hello'); 
```

I checked the contents of the 4.2 beta release.
Is it possible to catch the error of `hasKey` at design time?

**Comment by millsp** [comment]
Nope, it's not, because any object of type `T` can allow extraneous properties to be passed.

**Comment by jungeun-cho** [comment]
@millsp Thank you for your reply. I understand. :)
