### ISSUE TITLE
Method parameter types missing in class property initializer in extended class

### ISSUE THREAD

**Issue by puckey** [microsoft/TypeScript#41324]
**TypeScript Version:**  Nightly (v4.1.0-dev.20201029)

**Search Terms:**
extended class property initializer
extended class property function

**Code**

```ts
class A {
  declare test: (foo: string) => string
}

class B extends A {
  test = bar => bar
}
```

or

```ts
class A {
  test = (foo: string) => foo
}

class B extends A {
  test = bar => bar
}
```

**Expected behavior:**
In class B the `bar` parameter should be inferred as `string`

**Actual behavior:**
Parameter 'bar' implicitly has an 'any' type.

**Playground Link:**
https://www.typescriptlang.org/play?ts=4.1.0-dev.20201029#code/MYGwhgzhAECC0G8CwAoa0AuBTCHoF5oAKAMwHsyAuaXAJwEsA7AcwEoCA+acs1AX1SpQkGACFoWAB7ZGAExjxkaaMDKM6AV2AYytIuyXp0EDQAcse1qiOYAFvQgA6bLgLcKnd72UCUvoA

**Related Issues:**
Not that I could find

This does work:
```ts
class A {
  test = (foo: string) => foo
}

class B extends A {
  constructor() {
    super()
    this.test = bar => bar
  }
}
```

**Comment by RyanCavanaugh** [comment]
See #10570
