### ISSUE TITLE
TypeScript does not follow object keys when narrowing types

### ISSUE THREAD

**Issue by catalin-enache** [microsoft/TypeScript#41320]
**TypeScript Version:**  4.0.3

**Search Terms:**
typescript narrowing types via object keys

**Code**

```ts
type A = {
    kind: 'A',
    aField: 'aField'
};

type B = {
    kind: 'B',
    bField: 'bField'
};

function getField(p: A | B) {
    if (p.kind === 'A') {
        // TypeScript knows that p is A
        return p.aField; // intellisense: kind, aField
    }
    // TypeScript knows that p is B
    return p.bField; // intellisense: kind, bField
}

function getField2(p: A | B) {
    switch (p.kind) {
        case 'A':
            // TypeScript knows that p is A
            return p.aField; // intellisense: kind, aField
        case 'B':
            // TypeScript knows that p is B
            return p.bField; // intellisense: kind, bField
    }
}

// TypeScript does not follow object keys when narrowing types
function getField3(p: A | B) {
    return {
        'A': (p as A).aField, // expected to work without type assertion (p.aField), since TypeScript has enough information
        'B': (p as B).bField, // expected to work without type assertion (p.bField), since TypeScript has enough information
    }[p.kind];
    /*
    Since I'm indexing with p.kind,
    TypeScript should know that for the branches where keys match one of p.kind possible values,
    p should pe narrowed to its type, the same way as when TypeScript manages to follow the if and switch branches.
    */
}
```

**Expected behavior:**
TypeScript should be able to follow **object keys** when narrowing types the same way it does when following **if** and **switch** branches.

**Actual behavior:**
TypeScript does not follow object keys when narrowing types even there is enough information.

**Playground Link:** 
https://www.typescriptlang.org/play?target=99&ts=4.0.3#code/C4TwDgpgBAglC8UDeBYAUFTUDWBLAdgCYBcUA5DGQDTpZQCGAYrhADYnlMvtnoC+AbnTpQkKACEEyWljxFSZcdRmYARszYcy67oV5pBwtADMArvgDGwXAHt8UAOYRgG9gAowpOAB8JASmkMLFxjKA8AOjlCBHhECjIA1CC6TAB6VKgAFXAIAGULACdcMGAcfBsAdwBnKGAAC3pSsChcGpgVFILnUwL7MHCuTQEodJb8YDZWVoh8KohSKKoGV0IOvg7R7Mh8opKyypr6xqhm1okOruAevvCdIZGMggnWKbnZ+ZwCQiW79n4jMyWax2RzOFYAJg8XigvnEiQ6VQquGAFjqYX6UXhyRSFnoc3IlGIHRSWE2OR2xVK2HK1VqDSaLTaxJJUEu1xOAxWw1GT0m03eCy+S0Gf2xdFx+MUZCJYpZZO2hUp+1pRwZZ3EzJJbN6HN+hG5j3GfLec0FRB+KzW-zQ6HleUVe0INggNXKpWMNhelSgNlUACsIFYcBAQDUKnUZlB8PQCgVKgQHLUclV0ICrLZ7E4XLoAMxQ2Aw-yBOja+xJFkE6XohhtPyc3RLUYQAAekCsEGiwBsUAqNgK2B7yLqNlMpVE0DxcwKwPsERFhD8SyqBAs0C29t2pQaNRmI4caIIHoKAFtGhnNeQlKQPDX-LcVo2Mi22xNO93e-3B-UR2OcjWpzO6L3roi5QMulhruSDpbniUC7qY+5jEep4zmsADaGJfAAukI2KpAAVB0uQrtAACSZDHmMhAtgmX5oph5odOuFJ7FUw6mOwyp0scR50tAqgFPQlgRmGEZdMGoZQChqI+vg0A2KEDHRGANhVMuqisNAABu9CsKYLo0NizRsSOnFiNGsaVB2tTdsihw5Es9TQFU9DHtAFT0CAt7hpGzHQVJQn0E4hzdh6XoVHxLShEJ0SIsiMkCUJqIuuEHT4ak1pGOgQA

**Related Issues:** 
None so far.

**Comment by RyanCavanaugh** [comment]
It would be completely invalid to "narrow" here, since an operation like this would fail:
```ts
function getField3(p: A | B) {
    return {
        'A': (p as A).aField.toUpperCase(),
        'B': (p as B).bField.toUpperCase()
    }[p.kind];
    /*
    Since I'm indexing with p.kind,
    TypeScript should know that for the branches where keys match one of p.kind possible values,
    p should pe narrowed to its type, the same way as when TypeScript manages to follow the if and switch branches.
    */
}
```
There'd have to be some notion of "expressions which can be safely evaluated and discarded" and only apply narrowing there, but this doesn't seem like a common enough case to invest engineering effort in such an isolated scenario.

**Comment by catalin-enache** [comment]
@RyanCavanaugh thanks for feedback !
