### ISSUE TITLE
Quiet inheritance

### ISSUE THREAD

**Issue by tguichaoua** [microsoft/TypeScript#41325]
## Search Terms
private hide inherit

## Suggestion

Inherit from a class without its interface.
Possibility to disable interface checking. 

## Use Cases

I want to use the [`EEI.ts`](https://www.npmjs.com/package/eei.ts) package to create an securised interface for my `EventEmitter` based class.

```ts
import EEI from 'eei.ts';
import { EventEmitter } from 'events';

interface FooEvents {
    goo: [string, number];
}

export class Foo extends EventEmitter implements EEI<FooEvents> {
    /* ... */
}
```

But it raise this error:
```
Class 'Foo' incorrectly implements interface 'EEI<FooEvents>'.
  Types of property 'on' are incompatible.
    Type '(event: string | Symbol, listener: (...args: any[]) => void) => this' is not assignable to type '<K extends "goo">(event: K, listener: (...args: E[K]) => void) => this'.
      Types of parameters 'listener' and 'listener' are incompatible.
        Types of parameters 'args' and 'args' are incompatible.
          Type 'any[]' is not assignable to type 'E[K]'.
            Type 'any[]' is not assignable to type '[string, number]'.
              Target requires 2 element(s) but source may have fewer.ts(2420)
```
Currently I use this:
```ts
import EEI from 'eei.ts';
import { EventEmitter } from 'events';

interface FooEvents {
    goo: [string, number];
}

export interface Foo extends EEI<FooEvents> {}
export class Foo {
    /* ... */
}

util.inherits(Foo, EventEmitter);
```
But there is two problem:
- The return type of `on` (and other EventEmitter methods) is `this` but it's not resolved as `Foo`.
- Usage of `util.inherits` is not encouraged:
> Its (i.e, util.inherits()) usage is not much encouraged instead use of ES6 class and extends keywords is recommended in order to get language level inheritance support.

### index.ts
```ts
class A {
    on(event: string | Symbol, listener: (...args: any[]) => void): this { /* ... */ return this; }
}
interface B { readonly b: number; }

// from EEI.ts package
type EventsDef<E> = keyof E extends string | symbol
    ? {
          [x in keyof E]: [...any[]];
      }
    : never;

interface C<E extends EventsDef<E>> {
    on<K extends keyof E>(event: K, listener: (...args: E[K]) => void): this;
}

interface E {
    goo: [string, number];
}

class Foo extends !A implements B, !C<E> {
    get b() { return 5; } // implement B
}
```

### index.d.ts
```ts
/* ... */
// the interface of A is hidded.
class Foo implements B, C<E> { /*...*/ }
```

### index.js
```js
/* ... */
class Foo extends A { /* ... */ }
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
There's a conflict between the two types, so you need to manually declare something that is compatible with both, or use a hack like `Omit<EEI<FooEvents>, "on">`

**Comment by tguichaoua** [comment]
> There's a conflict between the two types, so you need to manually declare something that is compatible with both, or use a hack like `Omit<EEI<FooEvents>, "on">`

It's not what I want. I want a class with the interface of `EEI` and with the implementation of `EventEmitter` (without re-implementing `EventEmitter` myself).

**Comment by RyanCavanaugh** [comment]
You'll need to use a type assertion somewhere to accomplish that; this isn't sound at all and it's correct for an error to be issued here.

**Comment by tguichaoua** [comment]
I tried using type assertion, it's work well except from inside the class.
Is there a way to force the type of `this` inside class's methods (other than `(this as T)`) ?

Also the type displayed by the IDE is not really human-friendly.
![image](https://user-images.githubusercontent.com/33934311/98020458-55e8fe00-1e03-11eb-9edd-2ac474acba51.png)

```ts
class _Foo extends A {
    goo(a: string, b: number): void {
        console.log(`goo("${a}", ${b})`)
        this.emit("blah blah", null); // emit not valid event
        this.emit("goo", null, null); // allow invalid arguments
        (this as FooType).emit("goo", a, b); // Is there a better way ?
    }
}

// Class, Parent, Interface
type OverwriteParentInterfaceType<C, P, I> = Omit<C, keyof P> & I;
type OverwriteParentInterface<C, P, I> = OverwriteParentInterfaceType<C, P, I> & { new(): OverwriteParentInterfaceType<C, P, I> };

type FooType = OverwriteParentInterfaceType<_Foo, A, C<E>>;
type Foo = OverwriteParentInterface<_Foo, A, C<E>>;

const Foo = _Foo as unknown as Foo;

const foo = new Foo();
foo.on("goo", (a, b) => console.log(`event goo("${a}", ${b})`));
foo.goo("Hello world", 42);
```
