### ISSUE TITLE
Error with advanced types (Record, keyof, Exclude)

### ISSUE THREAD

**Issue by leqwasd** [microsoft/TypeScript#41328]
**TypeScript Version:**  typescript@4.1.0-dev.20201029

**Search Terms:**
Advanced types, Generics
**Code**

```ts
// I have variouts interfaces, looking like this, 
// they all have the same structure - 
// various keys of string[], and a "rest" prop with one key from the interface
type KeyOfIInterfaceA = Exclude<keyof IInterfaceA, "rest">;
interface IInterfaceA {
    a: string[];
    b: string[];
    rest: KeyOfIInterfaceA;
}

// And I needed a generic function, that could process all of those interfaces, 
// I wrote something like this
function normalize<T extends Record<Exclude<keyof T, "rest">, string[]> & { rest: Exclude<keyof T, "rest"> }>(
    obj: T,
    restOfKeys: Exclude<keyof T, "rest">[]
): T {
    const result = { ...obj };
    for (const key of restOfKeys) {
        result[key] = result[key].filter((s) => s);
    }
    return result;
}

// I can construct the object, and pass it to the function

const a: IInterfaceA = {
    a: ["a", "a"],
    b: ["b", "b", ""],
    rest: "a"
};

const normalizedA = normalize(a, ["a", "b"]);

```

The problem, in the function is in these lines:
```ts
    for (const key of restOfKeys) {
        result[key] = result[key].filter((s) => s);
    }
```
If I assign `result[key]` to a variable
```ts
const arr = result[key]; // tyoe for arr is:     const arr: T[Exclude<keyof T, "rest">]
const arrMapped = arr.map(s => s); // type for arrMapped is:    const arrMapped: string[]
```

I can do directly
```ts
result[key].filter((s) => s)
```
And the transpiler wont say anything - he knows, it is a string[] and it has all of the map, filter etc. functions

But if I try to assign a value to `result[key]`, it will raise an error:
`Type 'string[]' is not assignable to type 'T[Exclude<keyof T, "rest">]'`

Maybe I just need to adjust/improve my code, but I couldn't find out how.

**Expected behavior:**
`T[Exclude<keyof T, "rest">]` should be infered as `string[]`, given that `T` is a `Record<Exclude<keyof T, "rest">, string[]>`

**Actual behavior:**
``Type 'string[]' is not assignable to type 'T[Exclude<keyof T, "rest">]'

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIHkBmBJFA7YEBOSCGAxhAIJQC8UAogB4EA2ArgCYQA8A1vAPZJRqY58RYgBooAImwQAzsHEA+ANwAoAJYDchaPyybhUAN7KoJqHgBcUWdnUBzANoBdFaagAjS9btOXpqbMs4RFQMXSESFQBfZVBIWHhkHUEtACFyKlpGFg5uXiS9CBSxSRk5JTUNcL5Q5KI0o1cCT2AbdAdnY1MmZtb23xMIHu8O139gQISQytSo5SQGdAJgVS50KHQubABbPDpVAC82ABUoCGosdCZpKAAlCAJNplYaemY2ThAeKCPisYUxLxtJzyKAAMkMUDGlheWXeuW+v1KCigkXkAApOiYuG4AFaWH6YyGlZBBaTQzJvHKfXg-CR-eROZQASnxhkJD3QsiJ0gYdGA6QMUAAdCLsTiUSpCUhNlA0RyuR8oF8xiT4NImWzXKMZLzgPYPo50v5dfr4I4hUhVHycGi0eryCD1f0UcpCVJgAxsGtjXzZsp5fyLNVpvoKA1TEH7OI8OJijHHCJCR4oFG3LGJGniuIE27SpZo+JlJFJQH3JZ8uE0mH2ZYowR0+J6znXN0U+ImA2O1nm6ZBm2IA2B93E9qAhIB0WS6suRttrsDhAmKQKLOdntDmi8GIozHimnHEyVKXV-PDkwq+tNmuF2i3NvG4PO9nD675Vw6BAhXQuLY0Sf14uxCHkAA)

**Comment by MartinJohns** [comment]
Simplified example:

    function normalize<T extends Record<keyof T, string[]>>(obj: T, keys: (keyof T)[]) {
        const result = { ...obj }
        for (const key of keys) {
            result[key] = result[key].filter(s => s);
        }
    }
