### ISSUE TITLE
Can assign non existing field in class with checkJs / @ts-check

### ISSUE THREAD

**Issue by Raynos** [microsoft/TypeScript#41323]
When using classes in JavaScript they appear to be open by default, allowing assignment of new properties outside of the constructor.

When using classes in TypeScript they appear to be closed by default, all properties must be declared.

**TypeScript Version:**  4.0.3

**Search Terms:** Property does not exist checkJs class open close

**Code**

```js
// @ts-check
class Foo {
    /** @type {string} */
    foo;

    constructor () {
        /** @type {string} */
        this.foo = 'foo';
    }

    doStuff () {
        this.baz;
        this.bar = 42;
    }
}
```

**Expected behavior:** Two errors, one about `this.baz` and one about `this.bar`

**Actual behavior:** Only one error, about `this.baz`. The exact same code in TypeScript does error with two errors.

**Playground Link:**

JS => https://www.typescriptlang.org/play?strictNullChecks=true&noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&module=1&useJavaScript=true#code/PTAEAEBcGcFoGMAWBTeBrAUB+AbAhtNKAGID2poA3hqLaMAFQMSQCeADsldJAE4CWAOwDmAX1ANgNOgDNyWOqHilBPXgFd4kUr1AAKAJRVpi2o2ZQOXSmqFiJU03UiJ+0AHRyKAXlAByLz8AbhNQUQU6ABNSAGVIdRkZfSNqJ1oXN3cAIzwALxC00AyPHN1fABYAJgK6cNEgA
TS => https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQGaIFzQgBcAnASwDsBzAbnU2HnKOIFdhD5joAKAShTqZMhABakIAOhxIAvNADk0+bSEBfVIOgATeAGVCLLFh780QoaPESARmABeK8xkuTbXOQBYATI4zrVQA

**Related Issues:**

I could not find any way to freeze the class after the constructor and make extra property assignment an error.

**Comment by RyanCavanaugh** [comment]
This is the intentional behavior since you have only very recently been able to explicitly declare properties in JS. We might maybe add an option to force this eventually, but this is the intended behavior right now.

**Comment by Raynos** [comment]
Also without the property declaration I would expect the following to fail and let me know that a field `baz` was not assigned in the constructor

```js
// @ts-check
class Foo {
    constructor () {
        /** @type {string} */
        this.foo = 'foo';
    }

    doStuff () {
        this.baz;
        this.bar = 42;
    }
}
```

Having an option for it would be desirable.
