### ISSUE TITLE
Conditional Template Literal Type not distributing

### ISSUE THREAD

**Issue by zamb3zi** [microsoft/TypeScript#41321]
**TypeScript Version:**  4.1.0-beta

**Search Terms:** "template literal type" union conditional

**Code**

```ts
type S = 'aOne' | 'bTwo';
type bS = S extends `b${infer U}` ? `b${U}` : never; // bS = never - why didn't it distribute as follows?
type bS2 = ('aOne' extends `b${infer U}` ? `b${U}` : never) |
           ('bTwo' extends `b${infer U}` ? `b${U}` : never); // bS2 = 'bTwo' as expected
// forcing an extra distribution works:
type bS3 = S extends infer U ? U extends `b${infer V}` ? `b${V}` : never : never; // bS3 = 'bTwo' as expected
```

**Expected behavior:**

String literal unions should distribute with a single conditional type.

**Actual behavior:**

Nested conditional types are required to distribute over a string literal union.

**Playground Link:** https://www.typescriptlang.org/play?target=99&ts=4.1.0-beta#code/C4TwDgpgBAylC8UDkBDA8gOwkqAfZARgCoDuA9kgNwBQokUBcicEAHsBBgCYDOUABgQAkAbwCWGAGYQATlACqAX35QA-AOEilKgFxQsAN1mUoAelMMm+iEbkBaKCQAWIKFzFcMSYFDE-3PMAyYgQArhxQKHySZAA2sWQkPKq04NCMAEwIUAAUqJjYUGwc3HyCohLSctpqGqI1eoayAJR41FAdnV25SMTkOMWcvHXiUrIKyrXlWpONNi0m5pZZiL2kFJF8bJAAxhxc1EsxMjsSAOaRGEXsMihuYoHBYcBiZFfkMgDWPDqp9IwAZmyLHYQz4lXG8lqUMGpRGELkADVJuppsjdNZbFA5rZFhZAdk1v1NtddvtqNQgA

**Comment by j-oliveras** [comment]
Using another type works:
```ts
type S = 'aOne' | 'bTwo';
type bShelper<T> = T extends `b${infer U}` ? `b${U}` : never
type bS = bShelper<S>; // bS = 'bTwo'
type bS2 = ('aOne' extends `b${infer U}` ? `b${U}` : never) |
           ('bTwo' extends `b${infer U}` ? `b${U}` : never); // bS2 = 'bTwo' as expected
// forcing an extra distribution works:
type bS3 = S extends infer U ? U extends `b${infer V}` ? `b${V}` : never : never; // bS3 = 'bTwo' as expected
```
[Playground](https://www.typescriptlang.org/play?target=99&ts=4.1.0-beta#code/C4TwDgpgBAylC8UDkBDA8gOwkqAfZARgCoDuA9kgNwBQokUBMAFhADaQBOAPEQHwJQiUCAA9gEDABMAzlAAGBACQBvAJYYAZhA5QAqgF85UAPzylyg0YBcULADdttcNEYDGLdtq4xelKAHp-BjhEJGJyJCd6RgAmAQAKVExsYTEJGTMVdS0dSxNMi0MoG3ttAEo8aihqmtqoRPCKVPEpWQUszW09ItN2wutbCAcOMr9A4LjQxpwUWVFIAGNxSWpxjTIOBfUAcygUDGaOFChJVWlgDlUCAFdgVTID8g4Aa2krKJcYAGYBOFEWjLZLq6fIg-7pNrmIE6ABqPQKcIGpR0JSG2jGQUYPympCas1Si2W1CAA)

**Comment by zamb3zi** [comment]
I believe this is still a bug however. Neither a generic type or extra mapped type should be required.

**Comment by ahejlsberg** [comment]
Conditional types are distributive only when the checked type is a naked type parameter. This has been the case since the original introduction of conditional types and changing it would no doubt break a lot of code. So I'm going to call this working as intended.

**Comment by RyanCavanaugh** [comment]
Totally missed that `S` wasn't a type parameter 😞
