### ISSUE TITLE
lib.dom.d.ts: some interfaces declared twice at base interfaces

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#41334]
**TypeScript Version:**  4.0.5

**Search Terms:** ElementCSSInlineStyle

**Code**
In `lib.dom.d.ts`, some interfaces have other interfaces twice in their `extends` list:

* `ElementCSSInlineStyle` in `HTMLElement`
https://github.com/microsoft/TypeScript/blob/80dc9d9e3c7164a77eb7a02d2264bed210a977cd/lib/lib.dom.d.ts#L6586

* `DocumentAndElementEventHandlers` and `GlobalEventHandlers` in `SVGElement`
https://github.com/microsoft/TypeScript/blob/80dc9d9e3c7164a77eb7a02d2264bed210a977cd/lib/lib.dom.d.ts#L12976

All these interfaces extend `HTMLElement` and `SVGElement`, so they could be moved to interface `HTMLOrSVGElement` right?

**Comment by orta** [comment]
This is shipped
