### ISSUE TITLE
&&= incorrect boolean value returned

### ISSUE THREAD

**Issue by towsonTigers** [microsoft/TypeScript#41336]
**Expected behavior:**

var x = true
var y = false
x = x && y;  //false
x&&=y; //false

**Actual behavior:**
x&&=y; //true

**Playground Link:** 

https://www.typescriptlang.org/play?#code/G4QwTgBCwOYFwDsCuBbARgU0gXggJgAYBuCAKFEgAcsBjDBAFxBg0VUxwgE5izzwIADwi5oMAHwBWAIxF+kAJ4iI1MHUbMM4gByzSpGgHsEAZ0MAbDADpzhmAAoARADUQ5pBgiGAZlFhwIRwBqMSDHCAAaUHdPHxVaeiYWAODVdSSMAEo5I1MLa1sHR0ds-VyzSxs7J3sxKQJMgDJG+zTEzR0GlIihZoVSg2MKgurHWth6zIAfKdaEjRZOzO7BGf65QbzKwqcAQntxiUkG5rm1dsXtBuXAiMEAfnv1zeGqopKN4VxhZogFHKG+TeTi+QggvwUjjupVBwhmfwBWxGRVhEHhkOhclRjwRLyBO0c2PufyhQlK5Xxow+pB+jWw-zx21GtPpUMEMLRU3piNeBLhXIxZKxEEe3MZyJBIvurJ67LkQA

**Related Issues:**

**Comment by MartinJohns** [comment]
> **Expected behavior:**
> 
>    var x = true
>    var y = false
>    x = x && y; //false
>    x&&=y; //false

And this is exactly the behavior that is happening. [Playground link.](https://www.typescriptlang.org/play?#code/G4QwTgBAHhC8EBcwFcCmAoUkCecIDMQAbAZwwGMB7AOxMqNQDojKBzAChnhgDIeJsASgDcEAPRjCpCjToNmbTn1hDREqWSA)

In your playground link you assign `true` to `x` before reaching the `x&&=y` code.
