### ISSUE TITLE
Intl.DisplayNames missing

### ISSUE THREAD

**Issue by MichalBryxi** [microsoft/TypeScript#41338]
**Search Terms:** Intl.DisplayNames, "Property 'DisplayNames' does not exist on type 'typeof Intl'."

**Code**

```ts
let languageNames = new Intl.DisplayNames(['en'], { type: 'language' });
```

**Expected behavior:** TS knows `DisplayNames` and does appropriate type checking.

**Actual behavior:** TS displays error: `Property 'DisplayNames' does not exist on type 'typeof Intl'.`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20201030#code/DYUwLgBMCGB2DmBXa8QDloFsQGcIF4JYQB3CASVjGADoARASxwAcYBPDbHACgG0ByELH4BdADQQA3hDBtmIAFwR+MBMlT8IAXwCUAbgBQECEA
**Related Issues:** N/A

**Respective MDN**: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames
**Respective TC39**: https://tc39.es/proposal-intl-displaynames/

**Comment by MartinJohns** [comment]
Type definitions for drafts are **usually** not added to the type definitions provided by TypeScript.

In the [TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator) project they list as a requirement for [additions](https://github.com/microsoft/TypeScript-DOM-lib-generator#additions):

> - Is the IDL source from WHATWG?
> - - Are the additions available in **at least two of Firefox, Safari and Chromium**?
> - Is the IDL source from W3C?
> - - What stage of the W3C process is the proposal for these changes: We aim for Proposed recommendation, but can accept Candidate recommendation for stable looking proposals.
> - - If it's at Working draft the additions available in **all three of Firefox, Safari and Chromium**

Neither Firefox nor Safari support this feature. There's no mention of TC39, but it's likely that the same principle applies.

---

You can use [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) to make the types available in your code base.

**Comment by TimvdLippe** [comment]
Can we reopen this issue for #44022 ?

**Comment by sroucheray** [comment]
It is now supported in all major browser versions https://caniuse.com/?search=Intl.DisplayNames and is referenced in ECMA402 https://tc39.es/ecma402/#intl-displaynames-objects. I think this might be time to reopen this issue.

**Comment by SchmidtDawid** [comment]
Why this is still causing problems? How to fix it?

**Comment by j-ulrich** [comment]
Should be fixed with TypeScript 4.5 according to PR https://github.com/microsoft/TypeScript/pull/45647

**Comment by MichalBryxi** [comment]
TS playground [v5.0.4 still says](https://www.typescriptlang.org/play?ts=5.0.4#code/MYewdgzgLgBATgUwOYEtwDkCGBbBECSYAomEgDYoQAWMAvDGAgO4yFRkB0AIpQA5mYAnllwQAFAG0A5AjBSAugBoYAbxhRBvBAC4YUxKnBSYAXwCUAbiA): "Property 'DisplayNames' does not exist on type 'typeof Intl'"

**Comment by MartinJohns** [comment]
@MichalBryxi It works just fine in the Playground when you target an ES version that supports it.

**Comment by MichalBryxi** [comment]
Ah! So for future travelers: Minimum requirements [that seem to work](https://www.typescriptlang.org/play?target=7&ts=4.5.5#code/MYewdgzgLgBATgUwOYEtwDkCGBbBECSYAomEgDYoQAWMAvDGAgO4yFRkB0AIpQA5mYAnllwQAFAG0A5AjBSAugBoYAbxhRBvBAC4YUxKnBSYAXwCUAbiA):

- TS v4.5.5
- Target: ES2020
