### ISSUE TITLE
Failure to refine generic argument of type `extends boolean`

### ISSUE THREAD

**Issue by 0rvar** [microsoft/TypeScript#41333]
**TypeScript Version:**  4.0, nightly

**Search Terms:**
Generic, refinement, refine, extends boolean

**Code**

```ts
function foo<TValue extends boolean>(value: TValue) {
  if (value === true) {
    const truthy: true = value
  }
}
```

**Expected behavior:**
`TValue` should be refined to `true`. At the very least, the `value` variable should.

**Actual behavior:**
Error:
```
Type 'TValue' is not assignable to type 'true'.
  Type 'boolean' is not assignable to type 'true'.(2322)
```

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.1.0-dev.20201030#code/GYVwdgxgLglg9mABMOcA8AVAagQwDYgCmihAHlIWACYDOiARqnoTmAHwAUAbvkQFyJsvQgEpEAbwCwAKESIYwRN2GIAvOsRQATkTFTZcxBAQ0omnVAAWATwHaiaxDwKEZcgL4zP0oA

**Comment by RyanCavanaugh** [comment]
Narrowing doesn't quite work this way and it'd be difficult to make it do this without breaking other behavior. Ideally it'd be something like `TValue & true` but that kind of analysis only makes sense on unit values like `true` and `false`, but it's rarely useful to write generics that operate like that.

**Comment by 0rvar** [comment]
> Narrowing doesn't quite work this way and it'd be difficult to make it do this without breaking other behavior.
Could you elaborate?

>  it's rarely useful to write generics that operate like that.
Here's a slightly contrived use case:
```ts
type FullPayload = { _brand: 1 };
type LightPayload = { _brand: 2 };
type PayloadTypes = 'full' | 'light';
function callApi<TType extends PayloadTypes>(type: TType, payload: TType extends 'full' ? FullPayload : LightPayload) {
  if (type === 'full') {
    const fullPayload: FullPayload = payload; // Type error
    // serialization logic for full payload etc
  }
  // else etc
}
```
