### ISSUE TITLE
"Find All References" results change depending on what files were previously open

### ISSUE THREAD

**Issue by gluxon** [microsoft/TypeScript#41345]
**TypeScript Version:**  v4.1.0-dev-20201030

**Search Terms:**
- find all references

**Repro Steps**

Example repository here: https://github.com/gluxon/ts-find-references-test-case It's pretty small. 6 files total.

The above repository has projects `a`, `b`, and `c`. `a` has a project reference to `b` and `b` has a project reference to `c`. (i.e The project reference graph is `a` -> `b` -> `c`.)

#### Scenario 1
- Restart TS Server.
- Open `packages/c/src/index.ts` and run *"Find All References"* on the export `c`.
- No references are found except for the definition.

Requests:
```json
{"seq":0,"type":"request","command":"open","arguments":{"file":"/Volumes/git/ts-find-references-example/packages/c/src/index.ts"}}
{"seq":1,"type":"request","command":"references","arguments":{"file":"/Volumes/git/ts-find-references-example/packages/c/src/index.ts","line":1,"offset":14}}
```
Response:
```json
{
  "seq": 0,
  "type": "response",
  "command": "references",
  "request_seq": 1,
  "success": true,
  "body": {
    "refs": [
      {
        "file": "/Volumes/git/ts-find-references-example/packages/c/src/index.ts",
        "start": { "line": 1, "offset": 14 },
        "end": { "line": 1, "offset": 15 },
        "contextStart": { "line": 1, "offset": 1 },
        "contextEnd": { "line": 1, "offset": 30 },
        "lineText": "export const c: string = \"c\";",
        "isWriteAccess": true,
        "isDefinition": true
      }
    ],
    "symbolName": "c",
    "symbolStartOffset": 14,
    "symbolDisplayString": "const c: string"
  }
}

```

#### Scenario 2
- Restart TS Server
- Open `packages/c/src/index.ts`.
- Open `packages/a/src/index.ts`.
- Open `packages/c/src/index.ts` and run *"Find All References"* on the export `c`.
- Reference to `c` found in `packages/b/index.ts.`

Request:
```json
{"seq":0,"type":"request","command":"open","arguments":{"file":"/Volumes/git/ts-find-references-example/packages/c/src/index.ts"}}
{"seq":1,"type":"request","command":"open","arguments":{"file":"/Volumes/git/ts-find-references-example/packages/a/src/index.ts"}}
{"seq":2,"type":"request","command":"references","arguments":{"file":"/Volumes/git/ts-find-references-example/packages/c/src/index.ts","line":1,"offset":14}}
```
Response
```json
{
  "seq": 0,
  "type": "response",
  "command": "references",
  "request_seq": 2,
  "success": true,
  "performanceData": { "updateGraphDurationMs": 5.578943002969027 },
  "body": {
    "refs": [
      {
        "file": "/Volumes/git/ts-find-references-example/packages/c/src/index.ts",
        "start": { "line": 1, "offset": 14 },
        "end": { "line": 1, "offset": 15 },
        "contextStart": { "line": 1, "offset": 1 },
        "contextEnd": { "line": 1, "offset": 30 },
        "lineText": "export const c: string = \"c\";",
        "isWriteAccess": true,
        "isDefinition": true
      },
      {
        "file": "/Volumes/git/ts-find-references-example/packages/b/src/index.ts",
        "start": { "line": 1, "offset": 10 },
        "end": { "line": 1, "offset": 11 },
        "contextStart": { "line": 1, "offset": 1 },
        "contextEnd": { "line": 1, "offset": 28 },
        "lineText": "import { c } from \"@ref/c\";",
        "isWriteAccess": true,
        "isDefinition": true
      },
      {
        "file": "/Volumes/git/ts-find-references-example/packages/b/src/index.ts",
        "start": { "line": 2, "offset": 18 },
        "end": { "line": 2, "offset": 19 },
        "lineText": "export const b = c;",
        "isWriteAccess": false,
        "isDefinition": false
      }
    ],
    "symbolName": "c",
    "symbolStartOffset": 14,
    "symbolDisplayString": "const c: string"
  }
}

```

**Expected behavior:**
Finding `c`'s reference in package `b` should not depend on the user opening `packages/a/src/index.ts` or `packages/b/src/index.ts`.

**Actual behavior:**
References to `c`'s export are only found after `packages/a/src/index.ts` is opened. This is somewhat surprising and makes "*Find All References"* appear non-deterministic to users.

**Related Issues:** 
- Not a related issue, but loading dependent projects of a definition got improved recently https://github.com/microsoft/TypeScript/pull/41126

---

At a technical level, this behavior is understandable. Opening `a` allows tsserver to discover project `b`, which has a project reference to `c`. Until that point, TS Server doesn't know `b` references `c`. It hasn't seen `packages/b/tsconfig.json` yet.

However at the end-user level, this behavior is extremely confusing. "*Find All Reference*" results appear arbitrary since they depend on what files have been open in the editor previously (sometimes somewhat by chance).

**Comment by gluxon** [comment]
Also worth noting: Creating a ["solution-style tsconfig.json"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#support-for-solution-style-tsconfigjson-files) makes results deterministic, but that isn't documented.

An alternative would be to get `tsserver` to build a full project reference graph by looking at all `tsconfig.json` files in the project folder. It wouldn't load the entire project and its root names, just the `tsconfig.json` references array.

**Comment by sheetalkamat** [comment]
This is working as intended and we do not look for tsconfigs unless its in the ancestor directories to determine where to look.

**Comment by gluxon** [comment]
Is that for performance reasons?

 - If I run `fd tsconfig.json` in a repository with ~300,000 files it returns in ~0.2s. But I understand that's with an SSD and a Rust util.
- I also understand that this is by design, but my concern is that most TypeScript developers are not aware of this behavior and find it confusing. Should editors display a message perhaps that "not all source files in the project were considered"?

**Comment by RyanCavanaugh** [comment]
We have to stop *somewhere* short of scanning your entire hard drive. Once a project is loaded and there isn't direct evidence of others, config file searching stops.

This hasn't been a frequent source of feedback so far, so it seems like things are working as the majority of people would expect them to.

**Comment by gluxon** [comment]
> We have to stop somewhere short of scanning your entire hard drive. Once a project is loaded and there isn't direct evidence of others, config file searching stops.

I wasn't suggesting that the entire hard drive should be scanned. Editors generally have some sort of project scope that they're limited to and that scope can be passed to TS Server during initialization. (If it's not already.) TS Server also doesn't have to look at every file, it just has to scan and parse for a specific filename (`tsconfig.json`).

Scanning all `tsconfig.json` files also isn't the only solution. I can think of a few signaling improvements to reduce confusion:

1. Provide documentation on typescriptlang.org that solution-style configs files are required for editors to get full find reference results.
2. Make editors display a short message saying "results may be incomplete".

> This hasn't been a frequent source of feedback so far, so it seems like things are working as the majority of people would expect them to.

If you told someone "*Find All References* results can change without any source code edits", I think most people would tell you that is not what they expect. It took me a several hours to understand this issue before creating it. The lack of feedback may be because people don't know there's behavior causing inconsistent results. They'll see the returned references list and believe it to be complete.

But I understand. At the moment I'm the only one asking for an improvement. I don't want to rush anything and have no hard feelings if this issue needs to wait for more feedback from others. 🙂

**Comment by gluxon** [comment]
@RyanCavanaugh Can this remain open while it's waiting for more feedback? I imagine having it closed would decrease its discovery.
