### ISSUE TITLE
`AsValue` utility type feature request

### ISSUE THREAD

**Issue by TokugawaTakesi** [microsoft/TypeScript#41356]
## Search Terms

* Type same as value
* Type even with value
* Value same as type
* Value event with type

## Suggestion

Avoiding the opinion-based dispute like "Should we always annotate types in TypeScript?", I just tell that the approach "All variables, function and method must be type-annotated" is exists. There is only one case when it's hard to obey to it: then the value is a large object and it's type is event with value. The example from real project:

```typescript
class Button {
 public readonly Properties: {
    HTML_Types: {
      regular: "button";
      submit: "submit";
      inputButton: "inputButton";
      inputSubmit: "inputSubmit";
      inputReset: "inputReset";
    };
   Sizes: {
      regular: "regular";
      small: "small";
    };
   Colorations: {
      regular: "regular";
      accented: "accented";
    };
  } = {
    HTML_Types: {
      regular: "button",
      submit: "submit",
      inputButton: "inputButton",
      inputSubmit: "inputSubmit",
      inputReset: "inputReset"
    },
    Sizes: {
      regular: "regular",
      small: "small"
    },
   Colorations: {
      regular: "regular",
      accented: "accented"
    }
  };
}
```

If there is there is the utility type (e. g. `AsValue`) exists, we can refactor above code as:

```typescript
class Button {
  public readonly Properties: AsValue = {
    HTML_Types: {
      regular: "button",
      submit: "submit",
      inputButton: "inputButton",
      inputSubmit: "inputSubmit",
      inputReset: "inputReset"
    },
    Sizes: {
      regular: "regular",
      small: "small"
    },
    Colorations: {
      regular: "regular",
      accented: "accented"
    }
  };
}
``` 

### The default settings defining

Basically, the default settings are static read-only objects:

```typescript
const MarkupPreprocessingDefaultSettings: AsValue = {
  mustExecuteCodeQualityInspection: true,
  waitingForOtherFilesWillBeSavedPeriod__milliseconds: 1000,
  entryPointsGroupDependent: {
    indentationSpacesCountInOutputCode: 2,
    mustExecuteHTML5_Validation: true,
    mustExecuteAccessibilityInspection: true
  }
};
```

### Anti-hardcoding contants defining

The above `Button` example:

```typescript
class Button {
  public readonly Properties: AsValue = {
    HTML_Types: {
      regular: "button",
      submit: "submit",
      inputButton: "inputButton",
      inputSubmit: "inputSubmit",
      inputReset: "inputReset"
    },
    Sizes: {
      regular: "regular",
      small: "small"
    },
    Colorations: {
      regular: "regular",
      accented: "accented"
    }
  };
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Duplicate of #36450.

**Comment by TokugawaTakesi** [comment]
@MartinJohns 

>This would be a breaking change for everyone who already has a type with that name in their codebase.

Does it mean I can implement this utility type myself via existing TypeScript functionality?
If someone use type `AsValue`, it must be they reached the effect what I need.

**Comment by MartinJohns** [comment]
> Does it mean what I can implement this utility type myself via existing TypeScript functionality?  
> If someone use type `AsValue`, it must be they reached the effect what I need.

No, this is not what it means and you can't implement this utility type via existing functionality.

Just an arbitrary example, but assume I have code like this:

    interface AsValue<T> { value: T }    
    const value: AsValue<number> = { value: 0 }

If TypeScript suddenly introduces an `AsValue` type it would conflict with my own type.

---

I know you don't want this discussion, but notice [the comment](https://github.com/microsoft/TypeScript/issues/36450#issuecomment-578846421) by @RyanCavanaugh on #36450:

> At the risk of issuing a rare style proclamation from the TypeScript team, we **strongly** advise against the `typedef` rule. It's actively harmful in a lot of cases, and we're not going to add language features to work around a lint rule.

Tho he did not mention the cases where it would be harmful.

---

Regardless, this is the exact same feature request as #36450. :-)

**Comment by TokugawaTakesi** [comment]
@MartinJohns 

Thank you for the answer!

> Who he did not mention the cases where it would be harmful.

I have what to say about this, but I don't think the TypeScript developers team will listen.

I'm very grateful about you grant the honor to close the issue myself! :)
