### ISSUE TITLE
omit will ignore callable interface when exclude other properties

### ISSUE THREAD

**Issue by hardfist** [microsoft/TypeScript#41362]
**TypeScript Version:**  4.0

**Search Terms:**
extract overloaded callable methods from interface
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

interface Test{a:number;b:string,(a:number):string,(b:string): number, <T>(arr:T[]): T[]}

type extractFn = Omit<Test, 'a'|'b'> // extract call type, while keep overload feature



declare var y: Test;

y('abc').toExponential // ok
y(123).toLocaleLowerCase // ok

y([1,2,3])[0].toExponential; // ok

y(['a','b']).toLocaleString // ok

declare var x:  Omit<Test,'a'|'b'>

x('abc').toExponential // error
x(123).toLocaleLowerCase // error

x([1,2,3])[0].toExponential; // error

x(['a','b']).toLocaleString // error

```

**Expected behavior:**
x is callable 
**Actual behavior:**
x is not callable.
**Playground Link:** https://www.typescriptlang.org/play?#code/PTAEEFQKgZwUwDYDMC0BjA9gOwC4EMBLLOAEylBLgFtsYcAnPHA7UDJUHACzlAAd6GAEYJqoJBgQIMAdxgA6RQCgQoACpw6nLgRighAT1D0ArlixEA5qAAGOGGhtss23pipU8WEigRE4ADTGTDz02l7agiaWXKBeGNxwYUImBAgknBiSoDAmaLF4egDiJgh8QQDqcEJ8eGgA1kFwOGjySkpEOElIdbwadADeeABcWCZUQkkA3ELDdPRWAQAUI2MTSQCUcwyLS7PzVluga5P0QQA8agB8K-T0w2oA2gC6R0-PAL7tOAZ8vHAADwYdRwADEXABeUAAeSoBBwl00OCCAHI8CiAD4ooQoq6gVSA4FoHCgNB4KScX6BUAyHSiUD1OBwPhsABuSWkeAySDgTBM9Dg7XalDQCDwAtArPFoAMw3USKm7QMSzRQjQKI28hwGAAogC+Ng4LgCOT8WAMPUlMqAIwAJgAzJrtQAZDBk0SumRJADChV4qgtSqWj2tAVtAXtr0eAAZnlrdfrDcbyVMzWxLVbg2iUQFsSjXvHXe64ABlHZYawBjPCuCi8W8KVhAFymFwhH9ZHZrE4q7tAEqvBqjXxvUG4jJhBppKCehKft2x2Ft3kuCen1+qd3DCzufB0PhyMbGNx7WjpPMFObmd9rPo3M4gsu5eiMsLCtX7ftIA

**Related Issues:**

**Comment by MartinJohns** [comment]
Here's a simplified example:

    interface Test { value: string; (): string; }
    type Mapped<T> = { [P in keyof T]: T[P] }
    type MappedTest = Mapped<Test> // Type is { value: string }

This is either a design limitation or working as intended.

Mapped types (such as `Omit`) operate on properties, and call-signatures are not properties.

**Comment by hardfist** [comment]
> > TypeScript Version: 4.1
> 
> This version doesn't even exist yet. :-)
> You also forgot to fill out the "expected behavior" and "actual behavior" sections of the issue template.
> 
> Here's a simplified example:
> 
> ```
> interface Test { value: string; (): string; }
> type Mapped<T> = { [P in keyof T]: T[P] }
> type MappedTest = Mapped<Test> // Type is { value: string }
> ```
> 
> This is either a design limitation or working as intended.
> 
> Mapped types (such as `Omit`) operate on properties, and call-signatures are not properties.

Is there any way to extract overloaded call-signatures from interface ?

**Comment by alexrock** [comment]
One way is
```ts
type extractFn = Test | Function
```
But it only extracts generics if the interface has only generic signatures.

**Comment by MartinJohns** [comment]
> Is there any way to extract overloaded call-signatures from interface ?

I wouldn't know how, except if you split up your call-signatures and your properties to distinct types, then do something like:

    interface Fns {
        (a: number): string;
        (b: string): number;
        <T>(arr: T[]): T[];
    }

    interface Test {
        a: number;
        b: string;
    }

    type Combined = Fns & Test;

    type Foo<T> = T extends (Test & infer R) ? R : never
    type Bla = Foo<Combined> // Type is Fns

But I don't know how reliable a construct like this is.
