### ISSUE TITLE
Only the latest JSDoc has worked

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#41365]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
jsdoc,modifierFlags
**Code**

```ts
class A {
	foo () {}
}

class B extends A {
    /** @public */
    /** @deprecated */
	foo() {}
}

declare const b: B
b./*a*/
```

**Expected behavior:**

> b.foo is marked as deprecated whatever the order of the jsdoc tag

**Actual behavior:**

![image](https://user-images.githubusercontent.com/6831019/97853840-a2650880-1d33-11eb-9ec0-1c1628ffa238.png)
![image](https://user-images.githubusercontent.com/6831019/97853859-a85ae980-1d33-11eb-8626-10fb94574538.png)

**Playground Link:** 

**Related Issues:**

**Comment by Kingwl** [comment]
I saw the `L2502 getJSDocCommentsAndTags` in `src\compiler\utilities.ts`   

```ts
// ...
result = append(result, last(node.jsDoc!));
// ...
```

Is that expected?
If so, why we do that? It's a bit confused.

**Comment by yume-chan** [comment]
If you dig a little deeper you can see this line was modifed in #32181 to fix #32062.

(However I also worked this out backward, because I remember this rule was changed some time but can't find in release notes)

**Comment by MartinJohns** [comment]
> TypeScript Version: 3.7.x-dev.201xxxxx

Support for `@deprecated` arrived in TypeScript 4.0. You should update your TypeScript version. :-)

**Comment by Kingwl** [comment]
@yume-chan I think i have work on the latest version with git commit

```
commit 80dc9d9e3c7164a77eb7a02d2264bed210a977cd (HEAD -> master, ms/master)
Author: TypeScript Bot <typescriptbot@microsoft.com>
Date:   Fri Oct 30 06:16:14 2020 +0000
```

And It's also
![image](https://user-images.githubusercontent.com/6831019/97859186-371f3480-1d3b-11eb-9c65-2c897e0c85f9.png)


And in the code:

```ts
result = append(result, last(node.jsDoc!));
```

**Comment by MartinJohns** [comment]
@Kingwl I just jest with you because you mentioned the wrong TypeScript version in your issue description. :-) You skipped that part of the issue template and left the default value.
