### ISSUE TITLE
Inconsistent type inference between array literals vs. template literal placeholder arrays

### ISSUE THREAD

**Issue by benny-medflyt** [microsoft/TypeScript#41366]
I'm not sure how serious this is in practice, but it bothers me as a subtle inconsistency.

I would expect the type system to work identically for these 2 functions:

```ts
function f1<T>(str: string, array: T[]) {}
function f2<T>(str: TemplateStringsArray, ...placeholders: T[]) {}

f1("Hello", [1, "hello"]); // Works: correctly infers <string | number>
f2`Hello ${1} ${"hello"}`; // Broken: infers <number>
```

Here is another example where we get a difference, this time with inheritance

```ts
export function fun<T>(xs: T[]): T[] {
    return xs;
}

export class B { b(): void {} }
export class C1 extends B {}
export class C2 extends B {}

export const x = fun([new B(), new C1(), new C2()]);
export const y = fun([2, "hello"]);

export function broken<T>(_x: TemplateStringsArray, ...placeholders: T[]): T[] {
    return placeholders;
}

export const z = broken`${new B()} ${new C1()} ${new C2()}`;
export const bad = broken`${2} ${"hello"}`; // Error: Argument of type 'string' is not assignable to parameter of type 'number'.

const typeCheck1: number = x; // Good: "x" was inferred as B[]
const typeCheck2: number = z; // Bad: "z" was inferred as C2[]
```

**Expected behavior:** I expect "x" and "z" both to be inferred to the same type

**Playground Link:** <https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAjAHgCoD4AUBnKAJwC5EDCYwBzAGkQENDD6BPUjAbQF0BKRAbwC+AKFCRYCZACZMucuwCmAWwAOAG3pQFAZSKUqeAIJNWdAHQX19CAoAWcNQBMFhPO258hw0ShwAiAAkFNTU4PzoOFDo-W2DQv14AbkQAehTEAHU4QgBrN0QIbMIFaDUWREpgFzxENHJ9RAAfRDAQJQAjFyxRKQADIJC4RAASfhRBEf4YuLDBXuS0xAAhQjgchTBSSura1o6u72EFAA8VbKhkcGh4JDFZHGP8zl53LgFhRE-EYqgQQiRHolhCIjqdzgUNHgaksBIh2jgeKQAG5wGCOAQTEQnM6EC4QSE1ADCKEQJy0YEc0IxoJxeIJiEJUlJx3JlOWsJB2PBhTABEQx0QAF5LmAcBwwAoAO7LBF0CXS4mylpShlSBFJGnchB88rCsRiqTRWKDBI8IGa3Ei66SdqrdZge4AfWOilUGi0ugo1CMJhY5ksGhs9ic1VIOAwPA8r3eX2+Cl+-0QViDDmcriBnLBlp5fIAXkK4XaNr1RvKZTwJqWVYqK5My4yEXMgVzs9qLu16Ojhba1sXRlJK1NjfEm94cxcoCwVApCbEIDkUKQ9p1CAXjkDx4hJ9PZyUclIl20VwXc0CgA>

**Comment by MartinJohns** [comment]
A more realistic comparison would be:

    function fun<T>(...xs: T[]): T[] { return xs; }

Then you get the same behavior.

And if you remove the `new B()` and make `C1` and `C2` different (currently they're structurally the same type), then you will get the same behavior with classes.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. It's OK for different code to do different things.
