### ISSUE TITLE
Compiler emits syntactically invalid code vs ES5 for code that looks like ES6 async/await

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4137]
In 1.5.3,
```ts
var a = async () => await Promise.resolve(2);
```
compiled to
```js
var a = async();
await;
Promise.resolve(2);
```
which is valid ES5. (Not necessarily what you wanted, but syntactically valid output.) Now it is
```js
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promise, generator) {
    return new Promise(function (resolve, reject) {
        generator = generator.call(thisArg, _arguments);
        function cast(value) { return value instanceof Promise && value.constructor === Promise ? value : new Promise(function (resolve) { resolve(value); }); }
        function onfulfill(value) { try { step("next", value); } catch (e) { reject(e); } }
        function onreject(value) { try { step("throw", value); } catch (e) { reject(e); } }
        function step(verb, value) {
            var result = generator[verb](value);
            result.done ? resolve(result.value) : cast(result.value).then(onfulfill, onreject);
        }
        step("next", void 0);
    });
};
var a = function () { return yield Promise.resolve(2); };
```
which is not valid ES5 (it contains the yield keyword). It's a bit of a surprising change in the emit (certainly that it's capable of emitting something impossible of being valid in strict ES5 when compiling against ES5 is a bug?). Is this intentional?

**Comment by DanielRosenwasser** [comment]
> Is this intentional?

We make no guarantees of our generated code when your input is syntactically invalid. Right now you'll get

* `';' expected.`
* `';' expected.`

which are both parsing errors.

I generally don't agree that we should be unconditionally emitting, but there's always the `--noEmitOnError` flag.

**Comment by weswigham** [comment]
It still certainly feels awkward that the compiler is introducing an ES6 construct (`yield`) not present in the given source into the result when targeting ES5, exceptional emit or no. Inputs as trivial as `await 2` now get transpired to the invalid `yield 2`. Generally speaking, one does not expect the TS compiler to introduce new (and different) errors into one's code. Its prior behavior of performing semicolon insertion also made more sense, given the error message.

**Comment by mhegazy** [comment]
once ES5/ES3 support for async/await is in, this should go away, as you will get ES5/ES3 valid output.
