### ISSUE TITLE
JavaScript output has variable below return

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#4138]
Using latest commit (4c7b214a69c97eb1746b94712ff9a4c2202e2dca) and compiling the code below results in the variable initialization below `return`. 

```ts
class C {
  constructor (...args: any[]) {}
}

function fn (...args) {
  return new (C)(...args)
}
```

```js
function fn() {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i - 0] = arguments[_i];
    }
    return new ((_a = (C)).bind.apply(_a, [void 0].concat(args)))();
    var _a;
}
```

The variable is always below the return, even when the statement is assigned to a variable instead of returning.

Edit: `node node_modules/.bin/tsc test.ts --target es5`

**Comment by DanielRosenwasser** [comment]
It doesn't matter where the variable is placed; it just needs to be declared so that we can use it as a temporary value.

**Comment by blakeembrey** [comment]
I realised, but it didn't look by design and I didn't see a previous issue logged. I actually found Istanbul has issues with code coverage with this, though I've logged an issue there too.

**Comment by kitsonk** [comment]
> I realised, but it didn't look by design and I didn't see a previous issue logged.

I suspect it was because it wasn't supported before when targeting ES5, so it wasn't a "break" of previous behaviour, because there was no previous behaviour.

Declaring things after the return though doesn't seem like clean idiomatic JavaScript though.

**Comment by danquirk** [comment]
Seems reasonable to just put the var before the return isn't it? The objections here (not very idiomatic, plays poorly with tools like code coverage and linters checking for unreachable code) seem compelling enough. Obviously a minor issue but there's not really a good reason to not fix it (eventually) right?

**Comment by mhegazy** [comment]
This is not something that can be easily changed. the way the emitter works today is by doing transformations on the fly. transformations are done as we descend into the tree. at the time we are visiting a destructuring pattern we have emitted previous statements. moreover, destructuring can be in an expression position. so to emit the variables first we need to do a pre-walk to find destructuring assignments, somehow predict the variables needed, emit them, then as we are doing the destructuring use them.

I would say leave this issue open. we value the cleanliness of the emitted code, and there is an oprtnity to make it cleaner here. however the real fix would be to split the emitter to a transformation phase followed by a writing phase. we are looking into this now.

**Comment by mhegazy** [comment]
closing for now. marking as revisit. This should be a simple change once https://github.com/Microsoft/TypeScript/issues/5595 is in.
