### ISSUE TITLE
tsc --watch write output of latest run to file

### ISSUE THREAD

**Issue by mklinik** [microsoft/TypeScript#41381]
## Search Terms

watch output file errors.err error messages

## Suggestion

Make an option to let `tsc --watch` write the output of the latest run to a file. This way you could have all current error messages in a file, say errors.err, ready to source in vim quickfix.

## Use Cases

tsc --watch is already a pretty cool mini IDE, but writing its output to a file would allow for UNIX-like file-based editor integration.

## Examples

- run `npx tsc --watch --outputErrors errors.err`
- when there are errors, type `:cfile` in vim to jump to the first error

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
vim doesn't support terminal panes?

**Comment by MartinJohns** [comment]
If you're running bash you can easily achieve this behavior with some scripting.

This example was just hacked together:

```bash
handleTypeScriptOutput() {
    while read -r line; do
        printf "%s\n" "$line"

        if [[ "$line" == *"File change detected."* || "$line" == *"Starting compilation"* ]]; then
            if [[ -f "output.txt" ]]; then
                rm output.txt
            fi
        fi

        echo "$line" >> output.txt
    done
}
```

And run with:

    unbuffer ./node_modules/.bin/tsc --watch > >(handleTypeScriptOutput)

This will print out the output to the console, and also write it to `output.txt`. On recompilation the `output.txt` is deleted to only see the last result.

**Comment by mklinik** [comment]
@RyanCavanaugh I'm not sure, will dig into that.

@MartinJohns This solution works nicely. Thanks!
