### ISSUE TITLE
ReturnType not being evaluated when used in function definition generics alias

### ISSUE THREAD

**Issue by carlos-algms** [microsoft/TypeScript#41391]
### Scenario:
Given an indexed object of functions that return different value types, generate a new object with the same indexes and the return value of the functions.
```ts
const given = {
  foo: () => 1,
  bar: () => 'milka',
};

const generatedResult = {
  foo: 1,
  bar: 'milka',
};
```

### Failing example:
TypeScript is not re-evaluating the Types when calling the function with predictable values:
![fail](https://user-images.githubusercontent.com/4634613/98051270-c7d93b80-1e33-11eb-8915-9caf09ca7476.png)
It can predict the functions and their return types, but it is not evaluating `ReturnType<...>`

### Workaround example:
The proper types are correctly inferred when using an anonymous type directly in the return type of the function:
![pass](https://user-images.githubusercontent.com/4634613/98051311-dc1d3880-1e33-11eb-90d3-8bb08c52215f.png)

This workaround is not desired given the need for using the Type definition inside the body of the function.

**TypeScript Version:**  4.0.3

**Search Terms:**
- ReturnType
- Generics

**Code**

```ts
function extract<
  P extends string,
  M extends Record<P, () => any>,
  Ret extends {
    [K in P]: ReturnType<M[K]>;
  }
>(_map: M): Ret {
  return <Ret>{};
}

const { foo, bar } = extract({
  foo: () => 1,
  bar: () => 'bar',
});
```

**Expected behavior:**
Variable `foo` should be of type `number`
Variable `bar` should be of type `string`

**Actual behavior:**
All variables are of type `any`

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play?skipLibCheck=true&target=6&jsx=0&ts=4.2.0-dev.20201103#code/GYVwdgxgLglg9mABAUwB5QE4ENoB4BQiiACiusmACYDOi1mMYA5gDSGICyZUFNiASsghwMlXMRaIAFAEpEAXgB8iLGACeitkUFRuvWgG92RANoBpRIxIBdAFwDkUEBjAAVNQAdkuDueuKAbnYAX3xFKQB9AFssD3sOGXsdRCMiDEdnJANglVodIND8YTB6FMRgODhJACMsDEQc+W5saClU8sr7WQVlAEYtRFqMLrklRAByIfG2YJkg-HxQSFgEZpwoACYCIlI0HipaegxGVnYuPf0HYVFxSW6x1Q0wyJi4zkSy80skYjsHJxc7i8Pj8yhyRnSAKyOSwtEeBQWRQQpQMHTgGxqdQ2DQUa2gGza7Aq6JGPUQ-XYQw2pLGkzq03wsyCQA) or a [CodeSandbox Link](https://codesandbox.io/s/returntype-possible-bug-rhyfl) - Both with the same behavior.

**Comment by AnyhowStep** [comment]
Why do you need so many extra type params?

This is more than enough,
```ts
function extract3<M extends Record<string, () => any>> (_map : M) : {
  [k in keyof M] : ReturnType<M[k]>
} {
  return {} as any;
}
```

Also, try this instead,
```ts
function extract<
  P extends keyof M,
  M extends Record<string, () => any>,
  Ret extends {
    [K in P]: ReturnType<M[K]>;
  }
>(_map: M): Ret {
  return {} as Ret;
}
```

**Comment by AnyhowStep** [comment]
If we change your example a little, you'll see that your initial `extract` doesn't really make sense.

![image](https://user-images.githubusercontent.com/5655961/98053052-b5480d80-1e05-11eb-9063-644a042e7c28.png)

[Playground](https://www.typescriptlang.org/play?skipLibCheck=true&target=6&jsx=0&ts=4.2.0-dev.20201103&ssl=5&ssc=16&pln=5&pc=15#code/GYVwdgxgLglg9mABAUwB5QE4ENoB4BQiiACiusmACYDOi1mMYA5gDSGICyZUFNiASsghwMlXMRaIAFAEpEAXgB8iLGACeitkUFRuvWgG92RANoBpRIxIBdAFyIzAbnYBffIqkB9ALZYADvYcMvY6iEZEGMhQIBhIBi4qtDrObvjCYPRhiMBwcJIARlgYiAny3NjQUuHZufayCsoAjFqIhRh1ckqIAORt3WwuMs5AA)

**Comment by carlos-algms** [comment]
@AnyhowStep You might have got it wrong.
In a strict environment with enforced types, and `no-unsafe-any` enabled, those examples are not valid. 
Also, your example will only return `string` types, while every key has its own type.
In my case `foo` is a number, `bar` is a string.
Your example both are strings, what is not correct. 

Also, in a strict environment, you should not typecast something to `any` just to return it.

**Comment by MartinJohns** [comment]
> Also, in a strict environment, you should not typecast something to `any` just to return it.

That is just done to focus on the types, instead of having to create the implementation of the function.

---

I don't see the reason for the complexity. What you want can trivially be written as:

    type DesiredReturn<T extends Record<any, () => any>> = { [P in keyof T]: ReturnType<T[P]> }

    // Type is { foo: number; bar: string; }
    type ParameterReturn = DesiredReturn<Parameter>;
    
    function extract<T extends Record<any, () => any>>(parameter: T): DesiredReturn<T> { /* implementation be here */ }
    
    const { foo, bar } = extract({ foo: () => 0, bar: () => '' });

**Comment by carlos-algms** [comment]
I'm aware of alternatives, but none of the already suggested ones solves the problem or prove that it is not an issue. 

Lets see a more complex example: 
```ts
const randomFn = <T>(): T | null => null; 

export default function makeSelector<T>(context: T) {
  return <
    Keys extends keyof Selectors,
    Selectors extends Record<string, (context: T) => unknown>,
    TRet extends { [K in Keys]: ReturnType<Selectors[K]> }
  >(
    selectors: Selectors,
  ): TRet => { // HERE if I replace the named type TRet with { [K in Keys]: ReturnType<Selectors[K]> } it magically works 🤷🏻‍♂️
    // actual implementation
    // data fetching and parsing and then pass it to another fn
    const ret = randomFn<TRet>();
    return ret;
  };
}

const selector = makeSelector({ unrelated: true, nothingSpecial: false });

const { foo, bar } = selector({ foo: () => 0, bar: () => '' });
```

As explained in the issue description, if I delete the `TRet` definition and just put `{ [K in Keys]: ReturnType<Selectors[K]> }` as the return type, it magically works.

[another playground](https://www.typescriptlang.org/play?skipLibCheck=true&target=6&jsx=0&ts=4.0.5#code/MYewdgzgLgBATgQzAExAWwGJhgXhgHgBUA+ACgEoAuGQmAHxjAFcAbF3Yx1lgbhgCh+AUwAeABxBxYyIQDMErWLKZhgUAJbgYaBAGshAZSEshayUTKgwUUVGqFyMAN78Y8IVCZxs+V25gA0kIAnhAwtkIoYfrBILIwRiZmcBAANH5uiaZQkmERUTAASqaSyPjQcOpgAOapMKRWNiJ2NI44nCq6YCAA7mDE6f40xbD5yGFOMADaATBVgSEQALrUI15ghMFiQvhZyRAzS5wAvn5kGTAQxtm51Hs5KYMwVM7Ts-NBoStFHuub27trvtDicOM4LgB6CEwBBqJgIdjqNBiExoSJQBAacCQ6HITEIGCyDzAAAWVWqMJQMDECBS5MpyBgUBJkWpCAgYXUsBylJAzKEcEJYAuVmg7lgeEQKHQWCIIzI5B4Fzgv284oAhEq3Mclad+KLYFckg9cNo9IYgQ9SJMVCqWJihMhqFA4EwhHVuszyQZtsB1AjqPIWFcYMdFYIDa9ZCAQHUAEa00Omo03ODWwkx6gUMEABnjtKzbU4AHJi6Hw0A) with a working example.

**Comment by MartinJohns** [comment]
Your code is failing because TypeScript can't infer the type of `TRet` from anything. It only knows what it should **extend**, but it doesn't know what the type actually looks like.

That's why it works if you remove the type parameter and actually provide the return type. This is working as intended.

**Comment by carlos-algms** [comment]
It is able to figure it out. 
If you hover your mouse at `selector({ foo: () => 0, bar: () => '' });` you will see all the parameters, functions, Keys and return types are there.
![image](https://user-images.githubusercontent.com/4634613/98112053-d100f180-1ea1-11eb-84ad-3497d053c6c0.png)

Everything is there, except for the TRet, that depends on ReturnType.

**Comment by MartinJohns** [comment]
> It is able to figure it out.

Not fully, that's why you get the `any`. It can't figure out the type of the properties. It knows what the types should **extend**, but not what the types **are**. If you provide the type arguments yourself (so no inference is necessary) you get the desired result. With your initial example:

    function extract<
      P extends string,
      M extends Record<P, () => any>,
      Ret extends {
        [K in P]: ReturnType<M[K]>;
      }
    >(_map: M): Ret {
      return <Ret>{};
    }

    const { foo, bar } = extract<
      'foo' | 'bar',
      { foo: () => number, bar: () => string },
      { foo: number, bar: string }
    >({
      foo: () => 1,
      bar: () => 'bar',
    });

Look at the code of `extract`. Based on what information would the compiler be able to infer the exact type of `Ret`? There's simply not enough information available.

**Comment by carlos-algms** [comment]
But then, why does it work if I remove the named `TRet` generic and just put the anonymous:
`{ [K in Keys]: ReturnType<Selectors[K]> }` as the return of the function? 

Why does the named one fail while the anonymous work?

**Comment by MartinJohns** [comment]
Because then there is no type to **infer**. The compiler **knows** the **exact** type. The compiler doesn't need to figure out "what is the type, and does it extend this other type".

> Why does the named one fail while the anonymous work?

You're assuming `TRet` just means "I have a named type", but that's not the case. You're having a **generic type argument**, so the method can accept **different types** for `TRet` (they just must extend a specific type). Unless explicity provided (see my example) it must be inferred by the compiler.

**Comment by carlos-algms** [comment]
I might be underestimating it, 
But if I look again at the screenshot of the Hover over the `extract` function.
Every single type is there, the properties, the functions, and the return type of the given functions. 
I'm still not following why only the part where `ReturnType` is used is unable to infer the type.
The compiler is literally showing every single piece of information in the screenshot.

**Comment by MartinJohns** [comment]
> Every single type is there, the properties, the functions, and the return type of the given functions.

The first two type arguments can easily be inferred from your input argument (both `P` and `M` are used as part of `_map`). But where should the third type argument be inferred from? The third type argument must be inferred from the value you return within your function, and there's not enough information available for this.

> I'm still not following why only the part where `ReturnType` is used is unable to infer the type.

It's unrelated to `ReturnType`. Remove it, just use `M[K]` and you have the same issue.

**Comment by carlos-algms** [comment]
> It's unrelated to ReturnType. Remove it, just use M[K] and you have the same issue.
I see your point now.

**Comment by MartinJohns** [comment]
> But how is it different, if we move the definition from the generic argument to the return type?

Because then there is no type inference necessary anymore. The compiler doesn't need to figure out what `Ret` ist, it **knows** it's this specific type.

The difference is:

- With the **generic** return type `Ret`: Compiler needs to figure out, what is `Ret` and does it extend `{ [K in P]: M[K] }`?
- With the **non-generic** return type `{ [K in P]: M[K] }`: Compiler doesn't need to figure out the return type. It's `{ [K in P]: M[K] }`.

**Comment by carlos-algms** [comment]
Nice, thanks for the patience and the extremely detailed explanation.

What we do now? 
Is it a feature-request then? instead of a bug?

Or, ~please god no~, is it a Wont-do? 
because it is extremely useful to have it inside a Closure and being able to pass this generic argument deeper.

**Comment by MartinJohns** [comment]
It sounds to me that you don't actually want a generic type, but you just want to reference your rather large type using a local type alias. For this there's #40780 / #30979. But there hasn't been any progress, and likely there won't be in any foreseeable future.

**Comment by AnyhowStep** [comment]
> Looking at your screenshots, both are strings, what is not correct.
> 
> `{ [x: string]: string; } // from your screenshot, not the actual real type.`

I know. I'm saying that you've structured your types in a way that doesn't make sense.
I'm showing you examples of why your attempts do not make sense.

**Comment by AnyhowStep** [comment]
Having type parameters that cannot be inferred/constrained from the actual function arguments is also actually an anti-pattern.

Assume your desired type parameter `Ret` actually works. We have this problem,
```ts
function extract<
  M extends Record<string, () => any>,
  Ret extends {
    foo : number,
    bar : string,
  }
> (_map : M) : Ret {
  return {} as any;
}

const obj = {
  foo: () => 1,
  bar: () => 'bar',
} as const
const { foo, bar } = extract<
  typeof obj,
  {
    foo : 32,
    bar : "lol",
  }
>(obj);

```

[Playground](https://www.typescriptlang.org/play?skipLibCheck=true&target=6&jsx=0&ts=3.5.1#code/GYVwdgxgLglg9mABAUwB5QE4ENoB4BQiiAsiusmACYDOiASshHBpbtZjGAOYA0iAFAEpEAXgB8iLGACeYnoXrIoZKBRqIA3gqLA4cRAC5EYEAFsARsgzyiRc1gyHE7DJ14KAvvgn8A+qawABydiYSMGZS0iDCUQDCQND0laKWkAbnwvfCYwdkQ4cwArUU0FXTgjIVEJAEYbRHsMSuFxRAByRrb5JKxaHPZshDyNRHK+RsQkkRVsPAUoaUDkOGB8ovqo23KnAGYAJnq7BycAIgAbODOT+q8xfgLCwQygA)

![image](https://user-images.githubusercontent.com/5655961/98130057-d6514280-1e87-11eb-98d1-cac38a7816b2.png)

Notice that even thought `obj` returns `1`, and `"bar"`, the user can mess things up by setting `Ret` to be a subtype of `{ foo : number, bar : string }`.

You pointed out that one "*should not typecast something to `any` just to return it*".
However, your `Ret` type parameter is **exactly** that.
It is a "hidden" cast to practically any data type one wants.

**Comment by RyanCavanaugh** [comment]
Doesn't seem like there's a bug here. Thanks for the good discussion everyone.
