### ISSUE TITLE
Infer interdependencies in object literals

### ISSUE THREAD

**Issue by gffuma** [microsoft/TypeScript#41396]
**TypeScript Version:**  4.0.5

**Search Terms:**

infer, object literals, interdependencies

**Code**

```ts
type Selector<S> = (state: S) => any

export interface Reducer<T = any> {
  (state: T | undefined, action: any): T
}

type UnboxState<R extends Reducer> = R extends Reducer<infer U> ? U : never

declare function example<R extends Reducer, S extends Selector<UnboxState<R>>>(r: R, s: S) : void

example(
    (state, action) => ({
        name: 'Gio Va'
    }),
    state => 23
)

declare function example2<R extends Reducer, S extends Selector<UnboxState<R>>>(x: { r: R, s: S }) : void

example2({
    r: (state, action) => ({
        name: 'Gio Va'
    }),
    s: state => 23
})

```

**Expected behavior:**

Infer type `{ name: string }` to `state` in the `example2` function as it does correctly in `example` function.

**Actual behavior:**

In the `example2` function the type inferred to `state` is `any`. 

**Playground Link:** 

[playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=25&pc=3#code/C4TwDgpgBAyhA2EDGwD2AnAPDAfFAvFABQDOwAhsBAFywCUBe5AdiAFBsQAeYGwUAS2ZV0AM3JJoAJQgATAK6SsAFQJQWIPAG82UYmUo0oqgD5R5zWRFFC5AGnUoBqZrQ11aytgF8OoSFAAqswARqhcMBRUmFJQ3FSWJFAyCkp4hLHxEInJcooQWEKiBUF4APxBULTMEABuBRxWSPDk6NCiFk4ucVzkALZgiDE9CbJJKfnoDjAj2WOwCMhoWMFhEVEQMTjbROi0Ug4ktDAMtLWoArIc3P2DEES6evobDhLAzswM+HhEOk--UGY-SMAHIAOLOKAANXIIMeem8dDs8KgBiojCgACYAMxsOiNZAtNpQDrMLrMHq3RCY4ZZHITJTTWY5OCIFAYTCrcKRQxbHZcWhaKB7ZKHY5QRFVKDnS7XXoDam-FEi0gvRzvFxfH5-AF6IF9UEQ1DQ2EoxHI-5HVEbDE4nx0IA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #30134 - certain parts of inference depend on left-to-right per-parameter inference; we would need unification to infer this correctly

**Comment by kripod** [comment]
> we would need unification to infer this correctly

It seems that #31023 has been merged recently 🎉

I’m eager to see how #30134 can be resolved with such a great advancement. Kudos to all the collaborators working hard to make this happen!

_(I’d be so excited to deprecate all the exotic component typings [in react-polymorphic-types](https://github.com/kripod/react-polymorphic-types#usage).)_
