### ISSUE TITLE
Auto-semicolon at the end of return statements changes semantic.

### ISSUE THREAD

**Issue by mtarini** [microsoft/TypeScript#41395]
**TypeScript Version:**  4.0.5

**Search Terms:**
return semicolon

**Code**

```ts
function hello(x,y) {
	return /* (x>5) && */ 
		   (y<6) &&
		   (x+y<12);
}
```
I know commenting out code is bad practice, but don't we all do that occasionally.
In this case, I wanted to quickly remove one clause from a list of conditions, which for clarity had been written one per line
(clauses can be long).

**Expected behavior:**

The produced .js should match the .ts.

**Actual behavior:**

This nightmarish-to-debug monstrosity is produced instead:

```js
function hello(x, y) {
    return; /* (x>5) && */
    (y < 6) &&
        (x + y < 12);
}
```
Note the addition of the semicolon after the return, a _slight_ change of semantics.

Specifically instructing the function to return a boolean (adding ":boolean") will still not save you from this, either.

Removing the comment does not fix the problem. Uncommenting it produces the expected correct result.

It looks like TypeScripts just adds a semicolon after any return statement followed by no code before an end-of-line, regardless of what follows in the next line.
I don't understand. Why should end-of-lines matter? Isn't that incredibly dangerous to do? What am I missing?

**Playground Link:** 

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABACwKYBt1wBQA8A0AngJQDeAUAJABOqUI1SiA9AFR4B8ArMYgGR9EiVsyqUhQ7IQA8ANl4CxlPAGpCAXnUB2YgG5yAX3LkhQA

**Related Issues:** 

_Edit: for clairty._

**Comment by MartinJohns** [comment]
> The produced .js should match the .ts.

The produced .js **does** match the .ts. This is just how JavaScript behaves. Even when the semicolon is **not** inserted the function will still return `undefined`.

What you want would require to emit different JavaScript than your TypeScript (removing the newline), and this is deifnitely out of scope of TypeScript.

---

The compiler actually warns you about the issue with the unreachable code detection.

**Comment by mtarini** [comment]
Thank you!  I wasn't aware of that JavaScript behavior 
(wow, that's ugly -- JavaScript never stops to amaze me, I keep making wrong assumptions about its basic level of decency; thanks TypeScript again, I guess!).

Closing the issue.
