### ISSUE TITLE
Class that implements an interface does not get type inference on method arguments.

### ISSUE THREAD

**Issue by nicksrandall** [microsoft/TypeScript#41399]
**TypeScript Version:**  4.0.5

**Search Terms:**
Class that implements an interface does not get type inference on method arguments. 

**Code**

```ts
interface Component<A> {
  render(settings: A): string;
}

type HelloSettings = {
  greeting: string;
};

class GreetingComponent implements Component<HelloSettings> {
  render(settings) {
    return settings.greeting;
  }
}
```

**Expected behavior:**
I would expect the `settings` argument in render method of the "GreetingComponent" to have an inferred type of `HelloSettings` but currently that argument is inferred as `any`.

**Actual behavior:**
The `settings` argument in the render method of the "GreetingComponent" has an inferred type of `any`.

**Playground Link:**
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMIHsC2AHdILgA8AggHzIDeAUMslAQCbQAUAzhGGKAOasBcyYgEoBrMFB4BuKgF8qVMAE9sKABIQANhvQBlDlxC9kAXko1k3ehx6jxU2dKoINcVq2QBxKwe4YceAjBkYBwNCExA9z9cfCJ1LV19HlZyalp6ECYoNiTDViEzWnSOAFcoEGR2TmSAOksIa0NpWjkZIA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #10570 / #6118 / #1373 / others
