### ISSUE TITLE
Can't define variable using type of typeof

### ISSUE THREAD

**Issue by jabbukka** [Microsoft/TypeScript#4140]
I declared `test` module to export the global mongoose variable as below.
test1.d.ts:
```javascript
  declare module "test" {
    import _mongoose = require('mongoose');
    export var export_mongoose: typeof _mongoose;
  }
```

I tried to define mongoose.Model using the export_mongoose variable. Please refer to below code:
test2.ts:
```javascript
  /// \<reference path="test1.d.ts" /\>
  import test = require('test');
  var model: test.export_mongoose.Model\<number\>;  // it doesn't work.
  var model = test.export_mongoose;  // it works well.
```

However, tsc compiler shows a following error message:
  TS2305: Module `test` has no exported member `export_mongoose`.

I think the export_mongoose is not proper as type cause defined by `typeof`.
Can I use the `export_mongoose` as type?

It would be helpful for me if you have any idea on this.

**Comment by DanielRosenwasser** [comment]
When you use `var export_mongoose = _mongoose`, `export_mongoose` only takes on the *value side* of `_mongoose`.

Instead of using `export_mongoose`, I suggest you instead export the import directly:

```TypeScript
declare module "test" {
    export import _mongoose = require("mongoose");
}
```

**Comment by jabbukka** [comment]
Thanks for a quick reply!

I understood how this code works.
But I have to use an export_mongoose variable for sharing the mongoose object in many places, not only test2.ts. 

If there is no way to solve this problem, I will import mongoose and use it for type:
import mongoose = ('mongoose');
var test_var: mongoose.Model<...>;

**Comment by DanielRosenwasser** [comment]
Try `export import export_mongoose = mongoose;`

**Comment by mhegazy** [comment]
I would use the ES6 import/export syntax here.

```Typescript
declare module "test" {
   // import it locally 
   import * as mongoose from "mongoose";
   // use the import
   var test_var: mongoose.Model<...>;

   // export it directly from "mongoose" module
   export * from "mongoose";
```

**Comment by DanielRosenwasser** [comment]
Yes - if you're still intent on doing it the way you wanted, you can do something like

```TypeScript
declare module "test" {
    import * as mongoose from "mongoose";
    export { mongoose as export_mongoose };
}
```

**Comment by jabbukka** [comment]
This is an exactly what I wanted to do. It works for me. Thanks.

**Comment by mhegazy** [comment]
glad that helped.
