### ISSUE TITLE
frequent MaxListenersExceededWarnings when running test suite

### ISSUE THREAD

**Issue by boneskull** [microsoft/TypeScript#41404]
**TypeScript Version:**  master

**Search Terms:**  MaxListenersExceededWarning, EventEmitter leak, leak

**Code** n/a

**Expected behavior:**

Running `gulp runtests-parallel` does not result in leak warnings

**Actual behavior:**  Many leaks, e.g.

```
[Worker 0] (node:98823) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit

[Worker 1] (node:98824) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**Playground Link:** n/a

**Related Issues:** mochajs/mocha#4329, PR #41403 

This may be a duplicate, but I have created it for #41403.

**Comment by DanielRosenwasser** [comment]
I get this all the time on Codespaces containers...
