### ISSUE TITLE
Allow function declarations to be typed via a type alias

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#41411]
## Search Terms

"function declaration" "type alias"

## Suggestion

Currently functions can only  typed via a type alias when they are an expression, function declarations can't be typed this way.
Could typing function declarations via type alias be supported?

## Use Cases

Declaring a function's type via a type alias.

### In a declaration file

```ts
type F = <T>(param: T) => string;

// New Syntax
declare function foo: F;

declare namespace foo { /* ... */ }
```

`declare const foo: F;` doesn't work in the above example as it results in "Cannot redeclare block-scoped variable 'foo'. ts(2451)"

### In a standard TypeScript file

```ts
type F = <T>(param: T) => string;


// New Syntax: Casting
function bar1(param) { /* ... */ } as F
<F>function bar2(param) { /* ... */ }

// New Syntax: Declaring
function bar3: F (param) { /* ... */ }
```

## Playground

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYlC8UA8AVAfACjAQwE7YFsAuKFASgTSgDcB7ASwBMBuAKFYGNaA7AZ2CjAAFvV4B1WrgDWvEnERY8hCvCoBvKAHoAVFAB0BqNs1QAvm1aMIHADZ5oAMwCu3DsHo8oD2rTkWrtvZQ3IQQvDgcjj5QGjr6hsZm7M6u7p4ARngAjIr4BBSxugZ6RiamUNi8sOxIMGgpbh7cUJm4AEy5yjFaRQllyS6NGXgAzHJQnfndccWlZkA

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
The second part (in a standard TypeScript file) is a duplicate of #40378.

**Comment by RebeccaStevens** [comment]
I'll close this one in favor of that one. I comment the relevant parts of this one there.
