### ISSUE TITLE
More safety with instanceof type narrowing

### ISSUE THREAD

**Issue by grant-dennison** [microsoft/TypeScript#41415]
## Search Terms

* "instanceof type narrowing"
* "using class as interface"

## Suggestion

[Type narrowing with `instanceof`](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#instanceof-narrowing) is at odds with [using classes as interfaces](https://www.typescriptlang.org/docs/handbook/classes.html#using-a-class-as-an-interface). I propose adding a new compiler flag (e.g. `noClassAsInterface`) that disables using classes as interfaces.

Consider the following code ([playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8CwAoa0COBXMwA1gBQCUKAvhlehqJDAEJgBOKGWAtrgHYDmAUzKVqGDADNewAC4BLeD2gCAHgJbBZEIaz4AuOImgAfaMxal9AN3iyAJu0zRZ46MR1OeEaWB7AB8FwR4cjRHLB0AOjwCElIOLGgWAWlcFh54mnCWPgjufiE49BoMFTUNLWJQrGiiYWQaClIgA)):
```typescript
class Foo {
  quack() {}
}

class Bar {
  munge() {}
}

function exercise(arg: Foo | Bar): void {
  if (arg instanceof Foo) {
    arg.quack()
    return
  }
  arg.munge()
}

exercise({
  quack() {}
})
```

In this example, the code correctly compiles because the types check out, but at runtime it springs the error "arg.munge is not a function."

With my proposed compiler flag turned on, the compiler would throw an error on the call to `exercise()` because the anonymous object would not be allowed to satisfy the concrete type `Foo`.

This added strictness would prevent code accidentally failing when classes start getting used as interfaces later in a project's life after `instanceof` is already used extensively.

## Alternatives

The following options are available as an alternative at the present:
* Let code like this just fail at runtime. 😢
* Don't use `instanceof`. :cry:

The following options could serve as alternative solutions to my proposed solution:
* Don't allow `instanceof` narrowing to rule out types. In the example above, the `arg.munge()` call would throw a compiler error because `arg` would still have the type `Foo | Bar`. This behavior could arguably be more desirable than my proposed solution, but it would be a breaking change for some TypeScript code.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
  * _Turning on this compiler flag could break some existing code_
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Another alternative: Don't have purely public classes. As soon as you have a private member you don't face this issue anymore.

**Comment by grant-dennison** [comment]
@MartinJohns Thanks for that suggestion. I don't think I had registered [that part of the documentation](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#private-and-protected-members-in-classes) prior to today. I think that is a pretty good present-time workaround.

**Comment by RyanCavanaugh** [comment]
This is how it used to work. and people really really hated it. Since it's very difficult to accidently construct a matching class instance without realizing you're doing it, we don't see much reason to make this disagreeable again.

**Comment by RyanCavanaugh** [comment]
See also https://github.com/microsoft/TypeScript/issues/1719

**Comment by grant-dennison** [comment]
@RyanCavanaugh Thanks for the history!
