### ISSUE TITLE
Typescript's arrow function has different semantic than ES6's one

### ISSUE THREAD

**Issue by jiaz** [Microsoft/TypeScript#4141]
Hi, I'm playing typescript and happen to find a discrepancy between TS' arrow function and ES6's one. Below is a simple snippet to demonstrate:

```javascript
var x = {
    a: 1,
    b: () => {
        return this.a;
    }
};
console.log(x.b());
```

In ES6 (node --harmony), the above code will print out `1`. However, in typescript, the above code will print out `undefined`.

Is this a behavior by design or will be changed according to ES6's behavior later?

Thanks!

**Comment by Seikho** [comment]
This is because your compiler target is ES5, instead of ES6.

**Comment by jiaz** [comment]
Hi Seikho, thanks for your reply. If I compile to ES6, then for sure, the compiled output will look exactly as the input code which runs exactly the same in ES6 environment.

My question is whether the typescripts arrow function's semantic should be identical to ES6's arrow function or it is by design to be different.

In the case I compile the code to ES5, the reason it outputs undefined is because the code is compiled to:
```javascript
var _this = this;
var x = {
    a: 1,
    b: function () {
        return _this.a;
    }
};
```
If the compiler could detect this case and compile to:
```javascript
var x = {
    a: 1,
    b: function () {
        return x.a;
    }
};
```
Then the typescript can actually compile the code to have the same semantics as the ES6 one even the code is compiled to ES5.

I'm not a compiler guy. Just feel a little bit inconsistent regarding to this behavior.

Thanks!

**Comment by DanielRosenwasser** [comment]
Node might not necessarily have the correct behavior, and in fact, I don't think it is correct. If you can find something in [the spec draft](https://people.mozilla.org/~jorendorff/es6-draft.html) that would imply otherwise, that would clarify whose end the bug is on. Maybe @bterlson can weigh in.

**Comment by RyanCavanaugh** [comment]
Actually reading the spec, what you need to look for is the abstract operation `NewDeclarativeEnvironment` which creates a new lexical record. The runtime semantics (https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer-runtime-semantics-evaluation) of evaluating an `Object` does not do this, so there is no new interior lexical record that `this` should bind to.

Ours is the same behavior as in Firefox nightly, Babel, and Traceur.

**Comment by kitsonk** [comment]
By the way, running the above in Firefox outputs `undefined`, so it seems node's behaviour is incorrect.
