### ISSUE TITLE
Typescript "Organize Imports" action inserts loads of blank lines in import statements

### ISSUE THREAD

**Issue by DanTup** [microsoft/TypeScript#41417]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.2.0-dev.20201103

**Search Terms**
- organize imports
- alias

---

When running TypeScript's "Organize Imports" action on this file from the LSP client:

https://github.com/microsoft/vscode-languageserver-node/blob/05fa3b55538acaa87647111d528d39ddbd86caa2/client/src/common/client.ts

It makes a mess of the file, inserting lots of blank lines in between each class:

![Nov-05-2020 14-23-21](https://user-images.githubusercontent.com/1078012/98253056-7daaa400-1f72-11eb-973a-328b7e4362ad.gif)

I've disabled all other extensions but it still occurs. It shows TS 4.0.3 in the status bar if that's important.

**Comment by mjbvz** [comment]
Minimal repo using 4.2.0-dev.20201103:

`vars`:

```js
export const a = 1
export const b = 1
export const c = 1
```

`index.ts`

```js
import {
    a, b as B,
    c,
    c as C, b
} from './vars'

console.log(a, B, b, c, C)
```

Organize imports in `index.ts` adds a blank line:

```ts
import {
    a, b as B,

    b, c,
    c as C
} from './vars'

console.log(a, B, b, c, C)
```
