### ISSUE TITLE
Member decorator function overwrite has wrong type for "this"

### ISSUE THREAD

**Issue by erykwarren** [microsoft/TypeScript#41426]
**TypeScript Version:**  4.2.0-dev.20201105

**Search Terms:**

**Code**

```ts
class SomeClass {
  public foo: number;
  constructor() {
    this.foo = 1;
  }
  
  private static someDecorator(argPassed: any) {
    return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
      const originalMethod = descriptor.value;
      console.log(`decorator arg: ${argPassed}`);
      // anonymous function, not arrow
      descriptor.value = function (...args: any[]) {
        const result = originalMethod.apply(this, args);
        console.log(`foo from decorator ${this.foo}`);
        return result;
      };
    };
  }
  
  @SomeClass.someDecorator('Passing this in...')
  public doSomething(arg: string) {
    console.log(`original function arg:  ${arg}`)
    console.log(`foo from original function: ${this.foo}`);
  }
}

new SomeClass().doSomething('abc');
```

**Expected behavior:**
_this_ in the context of the anonymous function does not refer to _descriptor_. At the very least, it should be inferred as `any`

**Actual behavior:**
The compiler throws an error, but the code it generates runs as expected.
```
error TS2339: Property 'foo' does not exist on type 'PropertyDescriptor'.

14         console.log(`foo from decorator ${this.foo}`);
                                                  ~~~
```

**Playground Link:** 
Here is a [playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNaADgK4BGIAlsNAGbzwBc0AdkYicgE4Dce0w8TCABcORYEPgcAFAEpsvfEIAW5CADpa8aAF5oARh74Avr14EO5AG5ghyaMJuV7SZABFk-DjclSwHAOYACpAQyAAmjGBMAJ5yuPj4HMhCRBxM0FJCfv7JkTEANIQc8AScQtEA0sjRjMIWTP6FYcgQwBYEEhyMgcWlHOXure2dctoAfPIJCfyCQtCS5P7kTGAgALLJSvBhOtDNQ+QdkmrWIETIhlN8AhDwIMhqIPD+UgAGzZ7eHNDZjAAkWGywSg4SMrxklymAHooT8mAJooh4EQYNQiExxOQBIV4XM-MUAO4KBL7NqHTonVbnXZojFCLHpKRqZnZCB5aIAbQAunFiVMZsJoEkIEQQHNdAslit1pttmowAQCCBopkVBBCqyIXzpjc7g8ni9XpoaMVEHsPJIvtAAcpVBo6GCtVcEkkUmkhS1RUJIQkjD6-bwTPheAABBAodAhNS3FDuT6dKQAcmBEGW-mgtpgy2ZakTMjMpAoVDC8HDmzTvgCtREad5-N190ezzekuWqxo6MxAh+VfwAOyjuJAr1TcNxuopvmFil7dpXaY-ywmft8EdlxMJhwTGQBLgLkjUFkahLZdtDSTYBIwDzXCAA) with the above code

**Related Issues:**

**Comment by whzx5byb** [comment]
I think this is a feature: `this` is inferred as the same type of target when assigning a "method" to the object, to implement the prototype monkey patching.
```
SomeClass.prototype.foo = function() {
    this; // <== inferred as the same type of SomeClass.prototype
}
```

**Comment by rbuckton** [comment]
The only information the compiler has to go off of is the `this` type of `descriptor`, as that is all that has been provided. If you want to carry over the correct `this` type, you need to provide more information. For example, this gives the correct type information:

```ts
private static someDecorator(argPassed: any) {
  return <T extends { foo: any }>(target: T, propertyKey: string, descriptor: TypedPropertyDescriptor<(this: T, ...args: any) => any>) => {
    const originalMethod = descriptor.value!;
    console.log(`decorator arg: ${argPassed}`);
    // anonymous function, not arrow
    descriptor.value = function (...args: any[]) {
      const result = originalMethod.apply(this, args);
      console.log(`foo from decorator ${this.foo}`);
      return result;
    };
  };
}
```
[Playground](https://www.typescriptlang.org/play?experimentalDecorators=true&jsx=0#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNaADgK4BGIAlsNAGbzwBc0AdkYicgE4Dce0w8TCABcORYEPgcAFAEpsvfEIAW5CADpa8aAF5oARh74Avr14EO5AG5ghyaMJuV7SZABFk-DjclSwHAOYACpAQyAAmjGBMAJ5yuPj4HMhCRBxM0AA8ACrQyAAetkxhMFg0dJEx0EYAfFJCfv7JjFkANIQc8AScQtEA0sjRjMIWTP5tYcgQwBYEEhzN0V1hgR1dHD3uUzNzGXUqEM1tascNB9BRsTrV5zHVctrX8Qn4-IJC0JLk-uRMYCAAssklPAwjpoBMtuRZpI1NYQERkABCQzPPgCCDwEDINQgeD+KQAAwmnm8HHOAUYABIsA1glBwkYCTIUc8APSsm4CaKIeBEGDUIhMcTkARtJjwd5+DoAdwUCQh0yhc1hfwRYIFQqEIvSUmOalOFWiAG0ALpxOXPV7CaBJCBEEDvXSfb6-AFAkH6ggEEDRPaqNqnZkWhJWzHY3H4gmaGgdRDgjySUnQanKVQaOiMoOohJJFJpG2Te1CFkJIwlsu8Ez4XgAAQQKHQITUGJQ7hJcykAHI6RAfv5oKmYD89Z2ZGZSBQqGF4PWgX3fBT7CI++bLeiwzi8YTnT8-jRBcKBOT-IxkzSApm5aGsZvI9HqLGPhYXXuNYemFSsIP0-BMyiTCYOBMMg0pwC4jZQLIajTrOqajF2YAkMAo5cEAA)
