### ISSUE TITLE
Custom type guard with argument of type unkown will not infer object properties

### ISSUE THREAD

**Issue by Paalar** [microsoft/TypeScript#41431]
**TypeScript Version:**  4.03 && 4.2.0-dev.20201105

**Search Terms:** custom type guard, unknown type guard

**Code**

```ts
export type Product = {
  pk: number;
  name: string;
  price: number;
  image: {
    sm: string;
  };
  category: {
    pk: number;
    name: string;
  };
};

export const isProduct = (element: unknown): element is Product => {
  return (
    element instanceof Object &&
    element.hasOwnProperty("pk") &&
    element.hasOwnProperty("name") &&
    element.hasOwnProperty("price") &&
    element.pk instanceof Number &&
    element.name instanceof String &&
    element.price instanceof Number
  );
};
```

**Expected behavior:**
No errors to occur.
The code is checking if `element` is a type of `Object`, and that it has all three properties `pk`, `name` and `price`. It should therefore know that `pk` exists on `element`. This does not happen, but the errors described in 'Actual Behavior' occurs instead.

**Actual behavior:**
Three errors, one for each key.
`Property 'pk' does not exist on type 'Object' ts(2339)`
`Property 'name' does not exist on type 'Object' ts(2339)`
`Property 'price' does not exist on type 'Object' ts(2339)`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201105#code/KYDwDg9gTgLgBDAnmYcAKUIBMCuBjeAXjgG8AoOOMAawC44A7HAWwCNgoBuCxgQ2eD0AzjCgBLBgHNulMOLyDGLdlx5jmvSYvKVKQ5sNETpPAL4y4eXjGCToiejt016TNhwuUG-RSPFSLczIgslBIWEsIBhE4MSEMbHwiOAAKYAAbYAEGGHocBmoGCAB3BgBKegys4BzYoXRMXAI4QgA+Uh4oYBgcKAZUnkoq7PgJEV4GBQgAMzgAeVYAK2BmgDJVwbhhmpgAOgALXiE50oSUWEQUgCIaK7K4dc3tnIOjk4YzjiRr7wE7h42ui2mRGr2Op0w52+N3kwH+jyBzz2NFi0RgEymswAcsoOACniCdrtfqgxujJsAZnAAMpGKT4xGEl5yMQKVHjClUnHuKA8e7BbhAA

**Related Issues:**

**Comment by MartinJohns** [comment]
`hasOwnProperty` is not a type-guard (intentionally, see #18282), so no narrowing of `element` is happening. This is working as intended.

Besides the above, according to your type definition `name` is of the type `string`. Checking `name instanceof String` won't return `true`, **unless** the `String` constructor was used (which rarely is the case). The same happens for `Number`.

    "abc" instanceof String // false
    new String("abc") instanceof String // true
    
    123 instanceof Number // false
    new Number(123) instanceof Number // true
