### ISSUE TITLE
Produce correct sourcemaps for local builds of tsc/typescriptServices

### ISSUE THREAD

**Issue by JannesMeyer** [microsoft/TypeScript#41439]
**TypeScript Version:**  master branch

**Search Terms:**
- typescriptServices
- sourcemap

**Code**

Imagine the following program with a breakpoint on the last line. "Stepping in" doesn't show the original file, because source maps are not working.

```ts
import ts from 'typescript';

ts.createProgram(undefined, {}); // <- breakpoint on this line
```

**Expected behaviour**

Source maps should work.

**Actual behaviour**

Source maps for `built/local/typescriptServices.out.js` are disabled as you can see here: https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/src/tsconfig-library-base.json#L5

It's especially confusing because the Gulpfile assumes that they are enabled and produces **broken sourcemaps** for the downstream files (`typescriptServices.js` and `typescript.js`):

https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/Gulpfile.js#L132-L139

https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/Gulpfile.js#L149-L155

**Comment by DanielRosenwasser** [comment]
The compiler API assumes the same behavior as the command line - doing otherwise would be even more confusing and a potentially breaking change. Is there something I'm missing here?

**Comment by JannesMeyer** [comment]
Yes, I think you misunderstood me. Sorry that I didn't express it clearly enough.

This issue is NOT about the emitted files when using the compiler API. It is about being able to step into the **code of the TypeScript compiler** while using it to compile another project.

However, I just noticed that the npm package doesn't even include source maps, so I should add that this probably only applies when building the compiler yourself and importing it via `typescript/built/local/typescript.js`. The updated example should look like this:

```typescript
import ts from 'typescript/built/local/typescript.js';

ts.createProgram(undefined, {}); // <- breakpoint on this line
```

Does that make sense now?

**Comment by RyanCavanaugh** [comment]
We'd be open to having the source maps fixed for local development, but we don't intend to ship sourcemaps with our npm package because they're a lot of extra bytes that very few people will ever need.

**Comment by DanielRosenwasser** [comment]
Do local builds not get correct sourcemaps? I believe that they do.

**Comment by JannesMeyer** [comment]
Hi @RyanCavanaugh. Yes, fixing them for local builds would be perfect. It makes sense that you do not want to distribute them on npm.

@DanielRosenwasser, unfortunately local builds do not have working sourcemaps. That's why I opened this issue. I believe it is due to this line: https://github.com/microsoft/TypeScript/blob/de4a57afdc768bf861da7aabb7e8c49859f696b1/src/tsconfig-library-base.json#L5

`typescriptServices/tsconfig.json` extends `tsconfig-library-base.json`, as you can see here:
https://github.com/microsoft/TypeScript/blob/de4a57afdc768bf861da7aabb7e8c49859f696b1/src/typescriptServices/tsconfig.json#L2
