### ISSUE TITLE
Type information lost if type alias is in a separate file and project

### ISSUE THREAD

**Issue by Jazcash** [microsoft/TypeScript#41440]
**TypeScript Version:** 4.0.3

**Search Terms:** type alias separate same file intellisense any lost argument tsconfig multiple projects

**Code**

```
- lib
    - stuff.ts
    - thing.ts
    - tsconfig.json
- src
    - app.ts
    - tsconfig.json
```
```json
// lib/tsconfig.json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "*": ["./*"]
        }
    },
    "include": [
        "**/*"
    ]
}
```
```json
// src/tsconfig.json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "lib/*": ["../lib/*"]
        },
    },
    "include": [
        "**/*",
        "../lib/**/*"
    ]
}
```
```ts
// stuff.ts
import { Thing } from "thing";

export function Stuff(arg: Thing) {

}

Stuff("5"); // error because Stuff expects a number
```
```ts
// thing.ts
export type Thing = number;
```
```ts
// app.ts
import { Stuff } from "lib/stuff";

Stuff("5"); // no error because Stuff's arg type is now 'any' for some reason??
```

**Expected behavior:** app.ts should know that Stuff's arg type is a number and should error

**Actual behavior:** app.ts thinks Stuff's arg type is 'any' and doesn't error

This works fine if I take the type alias in thing.ts and put it in stuff.ts somewhere, despite both those files still only being part of the lib project.

**Comment by luuap** [comment]
Possibly related to microsoft/vscode#110145.

**Comment by Jazcash** [comment]
> Possibly related to [microsoft/vscode#110145](https://github.com/microsoft/vscode/issues/110145).

I don't think so, intellisense is still working in other areas and my issue seems specifically related to type aliases being imported from a separate file to where they're used. Restarting TS Server or VSCode doesn't fix the issue either.

**Comment by whzx5byb** [comment]
You should use "[Project References](https://www.typescriptlang.org/docs/handbook/project-references.html)" when you import `stuff.ts` from a separate dir because `stuff.ts` has an import from `thing`, which can only be resolved by its local `lib/tsconfig.json`. 

To use Project References you should add `"composite": true` to `lib/tsconfig.json` first:
```
{
  "compilerOptions": {
      "composite": true,
      "baseUrl": ".",
      "paths": {
          "*": ["./*"]
      }
  },
  "include": [
      "**/*"
  ]
}
```

and add `"references"` to `src/tsconfig.json`:
```
{
  "compilerOptions": {
      "baseUrl": ".",
      "paths": {
          "lib/*": ["../lib/*"]
      },
  },
  "include": [
      "**/*",
      "../lib/**/*"
  ],
  "references": [
      { "path": "../lib" }
  ]
}
```

Or you can simply change `import { Thing } from "thing";` to`import { Thing } from "./thing";` to avoid the local path resolving.

**Comment by Jazcash** [comment]
That's awesome, not heard of the references property before, works perfectly. Thanks!
