### ISSUE TITLE
Mapped Type of Intersection of two const types is incorrect

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#41448]
**TypeScript Version:**  4.2.0-dev.20201108

**Search Terms:**

"mapped type" "intersection" "const assertion"

**Code**

```ts
type Merge<T1, T2> = {
  [K in keyof (T1 & T2)]: unknown;
};

type Xconst = {
  readonly foo: "abc",
  bar?: "def",
};

type Yconst = {
  foo: 5,
  bar: "ghi",
};

type Test = Merge<Xconst, Yconst>; // = {}
```

**Expected behavior:**

`Test` should be: 

```ts
{
  readonly foo: unknown;
  bar: unknown;
}
```

**Actual behavior:**

`Test` is: `{}`

**Work Around:**

```ts
type Merge<T1, T2> = {
    [K in keyof T1]: unknown;
} & {
    [K in keyof T2]: unknown;
};
```

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201108#code/PTAEBUE8AcFNQC4AsCGDQBNYFsD2A7AZwQCc1ZDQBLQwgV1gDoAoBGeAWVhIHNYAecAEYANBABMAPlABeUAG9moZaADaAaWr5QAa1iRcAM1AAKYaABkEgJQBdAFygAyrmywocANzMAvt+YgoADquCQ6oCgkuHT4GCxscKBcvLAAggA2CIKiEtJyiipqmlTaegbGwg7Oru7s3j6WCkoqGlq6+kYSVS5uHrD1-iBDwyOjY+MTkxMBYOAUCITMM8GhOpQAxqEksOsI6ZCgAO5IsNoJFBHb+ADk6JtECPHsEPPJfEKySdx8-AAaYgBNSSDMAAEVwFBu6EOqyOJ2092IT0Sc2Ib1g4k+6L+iIQgNxwNAgXyPiWgRCYQ2Wx2ewOhyoyFAhFg6UMyPgqIQ6IAzFjvgJfrixIKCMRgaxnpz0QAWPkpfgAoWgRWihDi5YU8KRaKxI6rSgAIzo6BoUNAACJDOk0AhuPhYBhzeyXmj+RkEB85Oj3X9AeLzi6uW7MpivcGsiKHvjVeqpnH4wn48tOSUeBB2IsJYlfp9FABIbYoDAEfagQy4XCOYgkVMiZrKA2RAD8VdItd8-gDANzzDz5croHwdGwBu4dcKjZIrZr+B4db8SwDkeIPYLsCLJYO-cc5pQBvW5vHKknLYtWEMh47i+eKoeq+3oAArEeG5EdzwkFRLwuZom--+k0CUFh2wA4+lAABaagEGuSh8FwE1sGgUIEBQfBHmvRIelqRJ8giRwYh0eDDm0BcgA

**Comment by Nathan-Fenner** [comment]
The problem can be boiled down to the fact that

```ts

type Xconst = {
	readonly foo: "abc",
    bar?: "def",
};

type Yconst = {
	foo: 5,
    bar: "ghi",
};

type Both = Xconst & Yconst;
```

`Both` is `never`. That's because there aren't any possible objects that have `foo: "abc"` and also `foo: 5`.

Thus you're really mapping over `never`. Weirdly though, it's producing `{}` when the mapped type ought to be producing `never.`

Arguably, you should be seeing the same behavior for `TestMerge1`; `X & Y` ought to be `never` also since `foo` is incompatible there too. It seems that for whatever reason, `string` and `number` are "more compatible" than specific literal values (possibly, this is to help support "branding"?)

**Comment by RebeccaStevens** [comment]
Yeah, when I started debugging this is my project, my first thought was about `Xconst & Yconst` being `never`; but if this was the source of my problem, it inconsistent with the behavior of `X & Y` as that should also be `never` (but things work fine in that case). So yeah, something inconsistent is happening hence why I felt it necessary to open this issue.

**Comment by RyanCavanaugh** [comment]
Reduction to `never` is an expensive operation and only eagerly occurs when we see properties that look like they're discriminants (i.e. have literal types). In general if you apply operations to types which *might* produce a `never` then the results are not necessarily going to match their distributed equivalents.

> Thus you're really mapping over never. Weirdly though, it's producing {} when the mapped type ought to be producing never.

This isn't correct; `never` is simply the empty set, and if you said "Give me an object whose set of keys is empty", which is what's happening here, then `{ }` is the correct result.
