### ISSUE TITLE
IE9 and export default with ES5 compile target

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/TypeScript#4145]
Hello,

we are using TS 1.5 and have a compile target set to ES5.
Now there is an issue with IE9 and the default keyword. Is there a way to get around this via a compiler flag? Or is this just a bug because in IE9 'default' is a reserved word?

**Comment by KnisterPeter** [comment]
Sorry, this is not a TS problem.

**Comment by KnisterPeter** [comment]
While digging deeper, this finally is a tsc problem.
When the compile target is set to ES5, module imports with a default import are transpiled to e.g. 'modulevar.default()'. This breaks in IE9.
While it is a view chars longer the ES5 mode should product 'modulevar["default"]()' instead for IE9 compatibility.

**Comment by danquirk** [comment]
I think https://github.com/Microsoft/TypeScript/issues/2296 covers the general issue here. Note related pull requests https://github.com/Microsoft/TypeScript/pull/2387 and https://github.com/Microsoft/TypeScript/pull/2760

**Comment by alexkrauss** [comment]
The referenced issues only cover ES3 behaviour. However, IE9 claims *ES5* support, but it still does not accept `modulevar.default`. 

Does this mean we must use ES3 to be compatible with IE9? Or could tsc output `modulevar["default"]` also in ES5 mode?

**Comment by KnisterPeter** [comment]
Currently you have to use ES3 to support IE9.

Alexander Krauss <notifications@github.com> schrieb am So., 9. Aug. 2015
22:05:

**Comment by andrewm1986** [comment]
This is seriously affecting my ability to use TS

Can I suggest a switch or tsconfig option to enable this functionality?

**Comment by mhegazy** [comment]
> Can I suggest a switch or tsconfig option to enable this functionality?

use `--target ES3`.

**Comment by andrewm1986** [comment]
@mhegazy no that's not the same.  That removes support for property get/set.

I need support for this _and_ get/set.

So either "--target ES3" needs to convert property get/sets into get/set<PropertyName> or the ES5 conversion needs to do export["default"]

**Comment by KnisterPeter** [comment]
The easiest solution for your problem would be to write a babel plugin to do the transforms from es5 to es3 which you need. And then run babel on your sources after typescript did.
But that may not be the best solution.

**Comment by andrewm1986** [comment]
I'm sure I could

But I still think this should be addressed as an issue with typescript.

I will affect anyone that uses a default export and IE9 and the fix is easy enough - use export['default']

**Comment by c9s** [comment]
Can we add an option this?

something like `enableExportDefaultQuote`
