### ISSUE TITLE
Omit a key from Union type return only type with common keys

### ISSUE THREAD

**Issue by wlf100220** [microsoft/TypeScript#41454]
**TypeScript Version:**  4.0.5

**Search Terms:**
Omit
Union
**Code**

```ts
type A = {
  a: string
  b: string
}

type B = {
  b: number
}

type C = A | B

type D = Omit<C, 'a'>

```

**Expected behavior:**
```ts
type D = Omit<A. 'a'> | Omit<B, 'a'>
```
**Actual behavior:**
```ts
type D = {
  b: string|number
}
```
**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This behavior follows from the definition of `Omit`.

Here's a distributive version if you want it.
```ts
type OmitDist<T, K extends string | number | symbol> = T extends unknown ? Omit<T, K> : never;
type D = OmitDist<C, 'a'>;
```

**Comment by wlf100220** [comment]
> This behavior follows from the definition of `Omit`.
> 
> Here's a distributive version if you want it.
> 
> ```ts
> type OmitDist<T, K extends string | number | symbol> = T extends unknown ? Omit<T, K> : never;
> type D = OmitDist<C, 'a'>;
> ```

Thank you very much for introducing the [distributive conditional type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types).
