### ISSUE TITLE
ImportMeta does not respect undefined checks

### ISSUE THREAD

**Issue by FredKSchott** [microsoft/TypeScript#41468]
**TypeScript Version:**  4.0.5

**Search Terms:** importmeta

```ts
// snowpack.d.ts
interface ImportMeta {
  readonly foo?: () => void;
}

// main.ts
if (import.meta.foo) {
  import.meta.foo();
}
```

**Expected behavior:**

Expected to compile successfully.

**Actual behavior:**

```
// main.ts
if (import.meta.foo) {
  import.meta.foo();
  ^^^^^^^^^^^^^^^^^^

 ts(2722) Cannot invoke an object which is possibly 'undefined'. 
```

**Playground Link:** https://www.typescriptlang.org/play?#code/FAEwpgxgNghgTmABAcygewEYyog3sRQxAemMQGcA7NAdwAcYIBrAOhBYBdyCiBLSjmDgAzRkgCSAWzpo4HALJgOMPDyJEEMEGkpQAnomFo0AfgBciABQBKRAF4AfIgBuaXiADcaxAF9gf4FJESRh+Tm5eYSteaVkOFkklGBYjNFt8QhiZOQSklOMbLx8gA

**Related Issues:** None

**Comment by FredKSchott** [comment]
Snowpack issues: https://github.com/snowpackjs/snowpack/issues/1558, https://github.com/snowpackjs/snowpack/discussions/1533

**Comment by stramel** [comment]
@FredKSchott I believe in the example you meant to make `foo` optional. 

```ts
// snowpack.d.ts
interface ImportMeta {
  readonly foo?: () => void;
}

// main.ts
if (import.meta.foo) {
  import.meta.foo();
}
```

**Comment by FredKSchott** [comment]
@stramel thank you! Updated the issue with your corrections

**Comment by cawa-93** [comment]
I encountered such a problem in 4.1.0-beta.

Not sure why, but this workaround works:
```js
const meta = import.meta
if (meta.foo) {
  meta.foo(); // no error 
}
```
[My Playground for tests link](https://www.typescriptlang.org/play?allowUnreachableCode=true&importHelpers=true&target=99&jsx=0&ts=4.1.0-beta#code/CYUwxgNghgTiAEAXAngBwamB7YBXMiAllgHYCiJAbvALzwDeARALIDyAImYwFyOY74ipRgF8AUKEiwEKdPFCUQELKgC2IEogrU6TNpx6MFSles2iJ4aHCRoEASVWosMRMxCIo22vH54CxORU8AA+8iCKymoaWlRillI2AObKAEZQEAxi8PCEmiAwAGZQYA5OLm4eUFk5ORqU3PCOzq7untoA3Nnw4uJihbgkAaS+2MCsJBDIABRQjQDkfoKB8wCUDOIDQ0Ik4ZQTU7MLxlFmiGsb8fGEhfDThOWuAHTqnk-1T-pktDR0i2PLUgXejdPwHGYPFqIF5Vd5UT4cMjrAD0yPgZBg2BgYj6NzukIqMLeHy+Pz+J1MMWB3QU4Puj2hrygcMoCM4KLRGKxOKuYFIAGdEPB6j4Cc8mSz4Kj4AApXCC+BgOBQRAIDKEKD8663aYkxFk+D-ATDEjUnJgyYzPXsqVo1gAax5YjxuvhpN+5IiJmimjNezp1qRtvgDpxQA)
