### ISSUE TITLE
Duplicate suggestions for react

### ISSUE THREAD

**Issue by Mangatt** [microsoft/TypeScript#41465]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.2.0-dev.20201103

**Search Terms**
- react
- types 
- ata type acquisition 

---

- VSCode Version: 1.51.0
- OS Version: Win 10 2004

Steps to Reproduce:

1.  Use Intellisense to auto import `useEffect` from `React` (just for example, this happens with multiple libraries)
2.  When you choose `useEffect`, import is placed correctly on same line as `React`
3.  If you choose `React.useEffect`, import is **placed on new line**

Does this issue occur when all extensions are disabled?: Yes

Problem:
![1-1](https://user-images.githubusercontent.com/2706990/98571678-14e66300-22b5-11eb-8fbc-29d4d70cc694.png)
![1-2](https://user-images.githubusercontent.com/2706990/98571682-16b02680-22b5-11eb-83a2-6455ac26758f.png)

Correct behavior:
![2-1](https://user-images.githubusercontent.com/2706990/98571719-1f086180-22b5-11eb-9200-293c5175ae86.png)
![2-2](https://user-images.githubusercontent.com/2706990/98571745-22035200-22b5-11eb-996a-0d331b6c4d93.png)

**Comment by mjbvz** [comment]
**Steps to reproduce**
1. `npm i @types/react`
1. In a JS file:

```js
import * as react from 'react';

use // trigger suggest here
```


**Bug**
Duplicate suggestion entries:


```
        {
            "name": "useCallback",
            "kind": "function",
            "kindModifiers": "declare",
            "sortText": "6",
            "hasAction": true,
            "source": "/Users/matb/projects/san/node_modules/@types/react/index"
        },
        {
            "name": "useCallback",
            "kind": "function",
            "kindModifiers": "declare",
            "sortText": "6",
            "hasAction": true,
            "source": "/Users/matb/Library/Caches/typescript/4.2/node_modules/@types/react/index"
        },
```

**Comment by MikeYermolayev** [comment]
Hello, I have a similar problem but with simple Error class and its methods.
![image](https://user-images.githubusercontent.com/8783498/99110412-68c9b280-25fb-11eb-9da4-990653933a63.png)

**Comment by mjbvz** [comment]
@MikeYermolayev Please open a separate issue against the IntelliCode plugin (the stars indicate the suggestions come from IntelliCode)

**Comment by MikeYermolayev** [comment]
Hm. looks like everything's ok now after restarting IntelliCode plugin. Will open an issue if see it again

**Comment by sheetalkamat** [comment]
Is this still issue with typescript@next
 I dont seem to see this 

![image](https://user-images.githubusercontent.com/8052792/105550947-e1fa1b80-5cb6-11eb-9712-27ef4e0a66d0.png)

**Comment by Mangatt** [comment]
Great, is looks fine now. Thanks

**Comment by gkssjovi** [comment]
Hi,
I have installed the typescript@next  ( version 4.3.0-dev.20210233 ) but the problem persists.
It only happen if I have @material-ui/core installed. 
If the package is installed it also duplicate the useEffect method.
Any suggestions on this one, maybe a cache problem?

**Comment by gkssjovi** [comment]
> **Steps to reproduce**
> 
> 1. `npm i @types/react`
> 2. In a JS file:
> 
> ```js
> import * as react from 'react';
> 
> use // trigger suggest here
> ```
> 
> **Bug**
> Duplicate suggestion entries:
> 
> ```
>         {
>             "name": "useCallback",
>             "kind": "function",
>             "kindModifiers": "declare",
>             "sortText": "6",
>             "hasAction": true,
>             "source": "/Users/matb/projects/san/node_modules/@types/react/index"
>         },
>         {
>             "name": "useCallback",
>             "kind": "function",
>             "kindModifiers": "declare",
>             "sortText": "6",
>             "hasAction": true,
>             "source": "/Users/matb/Library/Caches/typescript/4.2/node_modules/@types/react/index"
>         },
> ```

How did you obtained this JSON suggestion code? I have a similar problem with duplicate suggestions and I want to debug it but I don't know how. Thank you

**Comment by 0xdeadc0d3** [comment]
> It only happen if I have @material-ui/core installed.

same with react-bootstrap

**Comment by martinezguillaume** [comment]
Little update here,
I tried to fix it with this [issue](https://github.com/microsoft/TypeScript/issues/35680#issuecomment-565714585) without success

Then, I thought that it was maybe more an IDE problem, so I tried to search for VSCode config around typescript auto-import feature, and then I found this config
`"typescript.preferences.includePackageJsonAutoImports": "off",`

And now, I don't have duplicates react nor react-native suggestions. But I keep all the suggestions from node_modules packages. 
![image](https://user-images.githubusercontent.com/17292331/127236780-c01375f6-80cd-453d-9ffa-040754605547.png)

I don't know what this config do, I tried to search on docs without success, I only have a description
`Activate/Deactivate the research of the dependencies in "packages.json" for the automatic importations available`
