### ISSUE TITLE
Uncalled function checks need rhs-used-exemption for binary expression

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#41492]
```ts
declare var functions: any[]
declare var args: any
functions.forEach((f: () => void) => f && f.apply(parent, args));
```

**Expected behavior:**
No error on `f` in `f && f.apply...`

**Actual behavior:**
Error: "This condition will always return true."

Broken in #40197, found in user tests #41423

**Comment by sandersn** [comment]
Another example (from pyright)

`const x = Buffer.from && (Buffer.from as Function) !== Int8Array.from ? true : false`

**Comment by a-tarasyuk** [comment]
```ts
functions.forEach((f: () => void) => f && f.apply(parent, args));
```

`f` has type `() => void` definition, it is a function, that's why TS throws an error. Does that make sense? 

The following example works without errors
```
functions.forEach(f /* type any */ => f && f.apply(parent, args));
```

**Comment by a-tarasyuk** [comment]
About the example with the `Buffer.from`. Not 100% sure, however, `pyright` uses `@types/node > 12.12.54`, in this version `Buffer.from` defined as `function`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/283a51abf33a877555e2b6c68ea7025662ad929a/types/node/v12/globals.d.ts#L316-L342

**Comment by sandersn** [comment]
I think in this case the author may have some reason to distrust the type system. One giant reason is the possibility that the code was written with `strictNullChecks: false`. Either way, Typescript usually allows for 'unnecessary' checks even where it errors on nonsensical ones.

**Comment by sandersn** [comment]
It's the same in `@types/node@14.14.7` -- but I don't understand why the declaration method makes a difference?

If somebody wants to write feature detection in contradiction of the type system, this error should not appear. It's only intended for cases where the author genuinely forgot to call the function in question.

**Comment by a-tarasyuk** [comment]
The same issue will be for (v.4.0.3)
<img width="687" alt="Screenshot 2020-11-11 at 20 33 40" src="https://user-images.githubusercontent.com/509265/98850317-439f3d80-245d-11eb-994e-8e5fc28ac695.png">

There is an option to use `typeof x === "function"` to make feature detection.

**Comment by a-tarasyuk** [comment]
Maybe this check should be enabled by a new option if it is so noising.

**Comment by sandersn** [comment]
I don't know how good our usage detection is for the non-binary-exp case, but I would hope to see the error in this case:

```ts
if (Buffer.from) {
  // never call Buffer.from
}
```

And not in this case:

```ts
if (Buffer.from) {
  return Buffer.from()
}
```

Which seems to be the way it works.

**Comment by a-tarasyuk** [comment]
👍🏻

```ts
if (Buffer.from) {
  return Buffer.from.apply(null)
}
```
