### ISSUE TITLE
Feature request: disable organize import on specific lines

### ISSUE THREAD

**Issue by danitrod** [microsoft/TypeScript#41494]
I like using the auto organize imports on save feature (`"editor.codeActionsOnSave": {"source.organizeImports": true}` on `settings.json`), but I had to disable it for some specific cases for which the import organization would break my code.

For instance, take this React JS file 
```js
import 'react-app-polyfill/ie11';
import React from 'react';

const app = () => {
  return <div></div>;
};
``` 

The React Polyfill import specifically requires to be the first line in the file to provide Internet Explorer compatibility sucessfully. However, if you save the file with import organizing active, the `import React from 'react';` line jumps to the top, breaking React Polyfill's functionality. I had to disable the functionality in my `settings.json` to work around the issue.

What I propose is some kind of comment-disabling feature, like so:
```js
// vs-code-organize-imports-disable-next-line
import 'react-app-polyfill/ie11';
import React from 'react';

const app = () => {
  return <div></div>;
};
```

This has also been mentioned as an issue previously: https://github.com/microsoft/vscode/issues/78553#issuecomment-520929023

**Comment by clementoriol** [comment]
Having the same issue when importing global css files that needs to be kept in a specific order :  
```
import "styles/globals.css"; // Default styles
import "@theme/style/globals.css"; // Theme overrides
```

They get reorganized in the wrong order, which leads me to having to disable the organize import feature for the all project, which is a shame :( 

Being able to ignore a file would solve issues like this.

**Comment by ShaunLWM** [comment]
Would be a good feature to be implemented.
If you were to use `nanoid` in React Native, you would need to import
`import "react-native-get-random-values";` at the top of your file before any other imports.
Organizing imports would push this down causing your build to throw an error.

**Comment by tkruczek** [comment]
Would be great to have such option. I'm running into this issue when dotenv config needs to be executed before specific imports.

**Comment by zoechi** [comment]
Just run into this in this context https://github.com/angular/angular/issues/40977#issuecomment-785752667
The import has to be the first line otherwise it causes an error.

**Comment by rgoldfinger-quizlet** [comment]
+1 for this feature. In Next.js, import order matters when importing CSS files.

**Comment by Sayakie** [comment]
+1 for this awesome feature! I need this importing CSS files in React.

**Comment by SuspiciousLookingOwl** [comment]
Another example why we need this:

To initialize [`dotenv`](https://www.npmjs.com/package/dotenv)  you need to run
```ts
import dotenv from "dotenv";
dotenv.config();
```

however that can be shortened as:
```ts
import "dotenv/config";
```

Sometimes we need to initialize the `dotenv` before importing other modules, and `organizeImport` can mess this up by putting the `import "dotenv/config"` after importing other modules

**Comment by v1d3rm3** [comment]
+1 i need 'reflect-metadata' to be the first lib in my file

**Comment by thomasskk** [comment]
+1 for example in Nodejs i need to import my controllers after i connect to mongoDB.

**Comment by abumalick** [comment]
@RyanCavanaugh What kind of Feedback are we waiting for? 

This feature is very important when we use reorganize import automatically on save. It happens often in projects that we must import something before other imports. I have to use 'Save without formatting' every time I work on a file where the import order is important, it is boring and also difficult to remember for all team members that they should not change the order of imports in that specific file

Here are some use cases
- Importing i18n configuration in your entry file before any other component
- imports files with mocks in test files before the files that are mocked
- CSS order
- polyfills

**Comment by edzis** [comment]
I need it to respect requirements of https://github.com/welldone-software/why-did-you-render
> Create a `wdyr.js` file and import it as the **first import** in your application.

**Comment by jasonLTaylor88** [comment]
+1 for this feature. I need it to maintain order of imports when using FullCalendar in Next JS projects with next-transpile-modules package

**Comment by RyanCavanaugh** [comment]
What does it meant to disable the sorting of *one item* in a list? e.g. if I wrote
```ts
import E from "E";
// organize-imports-disable-next-line
import D from "D";
import C from "C";
import B from "B ";
import A from "A";
```
and "sort" this list, what is the new order?

**Comment by danitrod** [comment]
Good point. Perhaps pinning an import to the top of the file, as opposed to disabling organizing it, then? Then the others can be normally sorted?

**Comment by abumalick** [comment]
I would even say 'pinning one or multiple imports to the top of the file without changing their order'. I believe that this would handle all the use cases that were cited here.

Something like: 

```js
import E from "E";
import D from "D";
// organize-imports-disable-above
import C from "C";
import B from "B";
import A from "A";
``

**Comment by mcm-ham** [comment]
This feature request could cover this scenario https://github.com/microsoft/vscode/issues/35350

**Comment by jonit-dev** [comment]
Any updates on this one?

In Inversify, I must have import "reflect-metadata"; as the top import for my server.ts file. Changing this breaks the whole server.

**Comment by andrewnick** [comment]
+1 we also need polyfills at the top of the import list.

**Comment by FacundoVazquez** [comment]
+1

**Comment by RyanCavanaugh** [comment]
Can the people +1ing this answer the above question? https://github.com/microsoft/TypeScript/issues/41494#issuecomment-988187118

**Comment by mfulton26** [comment]
I too would like this. e.g. I need to make sure `react-app-polyfill/stable` comes first in my imports but I want the rest of my imports to be sorted after it.

**Comment by RyanCavanaugh** [comment]
What would folks think if we implemented the rule that each block of newline-contiguous imports sorted independently?
e.g.
```ts
import c from "C";

import d from "D";
import a from "A";
import b from "B";
```
would sort to
```ts
import c from "C";

import a from "A";
import b from "B";
import d from "D";
```

**Comment by robertn702** [comment]
@RyanCavanaugh My concern with the proposed contiguous-imports solution is how it would effect automatic imports. Which group would automatic imports be added to? It gets more confusing when you have more than two groups.

I like the previously proposed solution of disabling above/below as others have mentioned since it seems that users typically want imports pinned to the top or the bottom (can't speak for everyone, but this has been my experience). It also makes it clear that automatic imports would be added in between the `organize-imports-disable-above` `organize-imports-disable-below` comments.

```javascript
import b from "B"
import a from "A"
// organize-imports-disable-above
import e from "E"
import f from "F" // <-- automatic imports get added and organized in this group
import g from "G"
// organize-imports-disable-below
import d from "D"
import c from "C"
```

**Comment by edzis** [comment]
@RyanCavanaugheven I am in favor of your suggestion.
I have not stumbled upon the need to pin dependencies to the bottom but feel the urge to visually separate blocks of imports that auto-organize messes up.

**Comment by santialbo** [comment]
I like @RyanCavanaugh's proposal a lot. It's clean and easy to understand. No need for ugly comments.

@robertn702 Automatic imports get added to the last group, which is what is needed in 99% of the cases, as the first groups are usually polyfills. If it's not the case, you can always move the import manually.

**Comment by RyanCavanaugh** [comment]
Happy to take a PR for "automatically create sort groups based on newlines" behavior

**Comment by MQuy** [comment]
hi @RyanCavanaugh, from the your suggested behaviour above, I create an solution for sort groups based on newlines. It would be great to have your feedback 😀 https://github.com/microsoft/TypeScript/pull/48330

**Comment by alexjball** [comment]
Is this integrated into recent versions of VS Code? `Organize Imports` collapses groups in 1.67.1 using typescript@4.6.4.

**Comment by Rlamotte** [comment]
Hi.

Thanks for the amazing update !
 
Do you know if there is a way to enable such the same parameter to **export** organizing?

By default, "organizeImports" also organize exports. 
It seems I have the same problem when trying to make group of exports, which are sometimes dependant of previous export (and which should not be reorder globally) : 

**Example - Before**
```
export d from "D";
export  a from "A";
export  b from "B";

export  c from "C"; //depends on D
```

**Current behaviour**
```
export a from "A";
export b from "B";
export c from "C";  //depends on D which is not currently exported => causes a build error
export d from "D";
```

**Desired behaviour**
 ```
export a from "A";
export b from "B";
export d from "D";

export c from "C";  //depends on D => no error
```

**Comment by RyanCavanaugh** [comment]
@Rlamotte please open a new issue. Thanks!

**Comment by chrishj59** [comment]
NextJs 13 app directory needs 'use client' as the 1st line but VC Code moves until after the import statements. How  do  stop the move?

**Comment by hazae41** [comment]
To avoid the following issue https://github.com/microsoft/TypeScript/issues/42873, I import some "unused" types like this

```tsx
import type { Unused } from "some-dep"
```

But I am also using `source.organizeImports` on save, and it removes that line as it is not explicitly used in the code (it's still implicitly used)

I do not want it to remove that line

One fix I have is that I write the following to explicitly use the type

```tsx
type Unuseds = Unused | ...
```

Now `source.organizeImports` no longer removes that line, but it's ugly and now VSCode greys this line out since the `Unuseds` type is now unused

<img width="100" src="https://github.com/microsoft/TypeScript/assets/4405263/43dd728e-3130-4d12-a965-75bebb15b17c" />

**Comment by vijay-prema** [comment]
It is possible to do this. Just add any comment to separate the items to be sorted, and those items in each 'comment block' will be independently sorted by the "Organize Imports" command.  E.g. in this code due to the two lines of comments, there are now actually 3 independent blocks of imports (the first two only containing one import), each block doesn't lose its place, only the imports within it get sorted.
![Image](https://github.com/user-attachments/assets/b53b7b2c-d71b-4bc1-a07b-5976e1aec32d)
