### ISSUE TITLE
Backing out `Promise`'s `resolve` changes

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#41497]
In TypeScript 4.1, we've worked on two changes:

* Making `resolve`'s parameter non-optional: https://github.com/microsoft/TypeScript/pull/39817
* Making `void` parameters optional in assignability: https://github.com/microsoft/TypeScript/pull/40231

The thing that we've seen a **lot** of is that most large codebases are impacted in some capacity. At Google, 0.26% of "libraries" were impacted by the non-optionality of `resolve`, and [it's a legitimate concern](https://github.com/microsoft/TypeScript/issues/40124#issuecomment-724934630). We've also seen breaks similar things from projects within Microsoft, though we don't have the same sort of holistic view of codebases internally.. the change is relatively mechanical, but it is fairly breaky, and it is fairly common according to the report at https://github.com/microsoft/TypeScript/issues/41445.

It is fairly last-minute, but I think there are a few questions which are worth asking:

* Do these breaks warrant a 2-step release process of allowing `void` parameters to be optional and then making `resolve` optional?
* If so, does this need a back-out?
* Is a back-out even more dangerous at this point?
* Will we realistically put the change back in for 4.2?

**Comment by weswigham** [comment]
(There's also the option of moving the change behind a flag, and inverting the default of the flag in the future)

**Comment by DanielRosenwasser** [comment]
It's an option, but it's unclear how we would flag this since it's primarily a `lib.d.ts` .

**Comment by rbuckton** [comment]
I was discussing this with @DanielRosenwasser offline, but 4.1 doesn't introduce the idea of trailing `void` being optional. That has been a feature since 3.2 (#27522), but only worked for calls, not assignability. #40231 only fixes assignability. If this were a two step process, step one happened a little over two years ago.

**Comment by rbuckton** [comment]
> It's an option, but it's unclear how we would flag this since it's primarily a `lib.d.ts` .

We have `--strictBindCallApply`, although that primarily affects apparent types for functions. I'm not sure there *is* a good way to do this with a flag, given you can't dynamically change the optionality of a parameter by changing its type.
