### ISSUE TITLE
Polymorphic `this[K]` inside a class

### ISSUE THREAD

**Issue by falahati** [microsoft/TypeScript#41495]
Essentially it seems that the typescript can not resolve the type of a property when it is trying to do a `[K in keyof T]: T[K]` operation. I don't know the name of this. lookup? in any case, `T[K]` for `T = this` is always `this[K]` and is never resolved further inside of the class. It works great when used from the outside of the class.

**TypeScript Version:**  4.1.0-dev.20201101

**Search Terms:** "Polymorphic this" "this generic"

**Code**
Consider the following code:
```ts
type NonFunctionPropertyNames<T> = {
    // tslint:disable-next-line:ban-types
    [K in keyof T]: T[K] extends Function ? never : K;
}[keyof T];

class B {
    public test: number = 0;

    public bar() {
        var isThis = this.clone();
        isThis.test = 2; // WORKS, since `this` is resolved to `B`

        this.change({ test: 10 }); // ERROR, can't assign number to type `this["test"]`
        this.onChange(["test"]); // ERROR, can't validate "test" as a valid property name
    }
    
    public change(map: Partial<this>) {
        // do something
    }

    public onChange(fields: Array<NonFunctionPropertyNames<this>>) {
        // do something
    }

    public clone(): this {
        return this;
    }
}

const b = new B();
b.change({ test: 10 }); // works!!
b.onChange(["test"]); // works!!
```

**Expected behavior:**
For it to work regardless of the code being inside the class or outside of it.

**Actual behavior:**
See code.

**Playground Link:** [typescriptlang.org](https://www.typescriptlang.org/play?ts=4.1.0-beta#code/C4TwDgpgBAcg9gOwGIFcEGNgEtEAUBOck+oMAhgLYQDOAPACoB8UAvFAN4CwAUFH1AHoBUYNQA2WBMABcAEyzUyAIzEQAtAggAPYGombpSsgjWhI1HvygBtANJRJUANYQQcAGZR6AXWle73lDawBAIstRQqBjYiFAA-FCaAG4Q+FB+tgDcPAC+1i5unj7Z3DzoYmTUEQCCHJb8YCgqWOhQ6AAWxgDmEAAUFGRgfrhkJFhkYrTA7QqMAJR1vFb8QlCycFDUcFTTkl31fDk8B1CNza2IAMKdCD297lgQYuF+1fj4ZCC08MhomDgIAhEVKkSg0KYzaiMeaLZYrYTrTbbCC7W4nI6lJZ8M4SVrlRB9OZ+XYRLhY5b4FEofAIESQkpWDEYsoVKpQABCQR0oXCUFq7CsJxxLRENBkiRQFCUqVYUAADCUhU1cVAjPhegsyXC+ElRg5qPRIbKSQA6fGaDUM7UKQ0KE0hajAWUAJkygmEAHUAPIAJVsAGUADSbSToaAAAxJ4f1UEpWzEKVkIg24fZ4eO5Kspo63T6Aod4oAjHKoDk5m7VgBRH0+33B9DGADkTsq1CwXVpCEl0rSwA2ZgjJOsACIC8PvOnM-xTVcbncR2PvOX3VBq7WffWm07dRJZGQQlBR2Lh1BKqeoDusEmwIRiKBEmD0bkM+hEI7VbLNAB3DmWnhKM05zzUVHT8YtS2XVYvzgfAnGoABCeD-xNWdc16BdjyXCthGg2CEPgoA) with inheritance, my actual problem

**Related Issues:** This issue might have something to do with #39204 or #22934.

**Comment by RyanCavanaugh** [comment]
If you write code inside the class in terms of `this`, it's assumed that you're writing it that way on purpose to provide correct behavior in the presence of subclasses (otherwise you would just write `B` instead of `this`). The "incorrect" errors are correct identificiations of places where you would break a subclass with subtyped properties:
```ts
class B extends A {    
    public test: number = 0;
    public obj: object = { };

    public bar() {
        var isThis = this.clone();
        isThis.test = 2; // WORKS, since `this` is resolved to `B`

        // Violates C's contract
        this.change({ test: 10 });
        // Violates C's contract
        this.onChange(["obj"]);
    }
}

// Legal extension of B
class C extends B {
    test: 5 = 5;
    obj: Function = () => { };
}
```

Once you're outside the class, you're allowed to assume you're not aliasing and get back types resolved against the type of the reference (since otherwise you'd never be able to do anything ever).

**Comment by falahati** [comment]
But the playground link shows an instance in which the parent class is the one defining the method and the child class still can not use them as expected. If the child class is still unable to use these methods, what is the use of `this` in this context? Am I missing something here?

```Typescript
type NonFunctionPropertyNames<T> = {
    // tslint:disable-next-line:ban-types
    [K in keyof T]: T[K] extends Function ? never : K;
}[keyof T];

class A {
    public change(map: Partial<this>) {
        // do something
    }

    public onChange(fields: Array<NonFunctionPropertyNames<this>>) {
        // do something
    }

    public clone(): this {
        return this;
    }
}

class B extends A {    
    public test: number = 0;

    public bar() {
        var isThis = this.clone();
        isThis.test = 2; // WORKS, since `this` is resolved to `B`

        this.change({ test: 10 }); // ERROR, can't assign number to type `this["test"]`
        this.onChange(["test"]); // ERROR, can't validate "test" as a valid property name
    }
}

const b = new B();
b.change({ test: 10 }); // works!!
b.onChange(["test"]); // works!!

```

As far as I remember; defining the same logic via interfaces works as expected.

**Comment by falahati** [comment]
You argument has some merits; however I dont think it explain the baheier fully. At least it didn't to me. Condider this:

```typescript
type NonFunctionPropertyNames<T> = {
    // tslint:disable-next-line:ban-types
    [K in keyof T]: T[K] extends Function ? never : K;
}[keyof T];

class A {
    public change(map: Partial<this>) {
        // do something
    }

    public onChange(fields: Array<NonFunctionPropertyNames<this>>) {
        // do something
    }

    public clone(): this {
        return this;
    }
}

class B extends A {    
    public test: number = 0;
    public obj: object = { };

    public bar() {
        var isThis = this.clone();
        isThis.test = 2; // WORKS, since `this` is resolved to `B`; but should it? since it's type might be changed later

        this.change({ test: 10 }); // ERROR, can't assign number to type `this["test"]`
        this.onChange(["test"]); // ERROR, can't validate "test" as a valid property name
    }
}

class C extends B {
    public test: 5 = 5;
    public obj: Function = () => { };    
}

const b = new B();
b.change({ test: 10 }); // works as it should!!
b.onChange(["test"]); // works as it should!!

const c: B = new C();
c.change({ test: 10 }); // works; but it shouldn't if we follow the same logic
c.onChange(["test"]); // works as it should!!
```

There are following problems if I accept the reason provided here for this bahavier:

1. `isThis.test = 2;` in `B.bar()` also shouldn't work. Since `test` might get overridden by a new subtype.
2. `this.onChange(["obj"]);` should work anyway, since the name of the property will be valid regardless of its type. If this bahvier raise from the fact that we are checking for function properties via `T[K] extends Function ? never : K`, why removing the check still results in the same error anyway?
3. `c.change({ test: 10 });` works for `c: B = new C();`; if what you describe is the reason for error, this should also fail, in theory!

Breaking a subclass should be a developer choice, and they should accept the responsibility of doing so. It was up to me, I would not even allow that, but this is JS at the end of the day, so its undestandable. But now if is effecting a very legal and common use of `this`. In the current form, the use the `this` is greatly limited to return types as it seems.

So I understand if you can't fix 1 and I dont expect anything to change with 3 since we are explicitly casting the object to `B` expecting a valid implementation from `C`. But for number 2, this seems to be a bug.

**Comment by RyanCavanaugh** [comment]
The current behavior arises from a set of consciously-chosen trade-offs. We definitely could have made other trade-offs, as you describe, but we didn't - that isn't a bug, just a difference in opinion.
