### ISSUE TITLE
Return type inference for intersected functions not using type expansion

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/TypeScript#41514]
**TypeScript Version:**  4.0.5

**Search Terms:**
- function inference return
- function infer return

**Code**

```ts
type HtmlFragment = string & { readonly Type: unique symbol };
type SanitisedHtmlFragment = HtmlFragment & { readonly SanitisedHtmlFragment: unique symbol };
type GetArticle = (() => { abstract: HtmlFragment }) & (() => { abstract: SanitisedHtmlFragment });
```

**Expected behavior:**

`GetArticle` is inferred as  `() => { abstract: SanitisedHtmlFragment }` (as `SanitisedHtmlFragment` extends `HtmlFragment`).

**Actual behavior:**

`GetArticle` is inferred as  `() => { abstract: HtmlFragment }`.

**Playground Link:** https://www.typescriptlang.org/play?#code/PTAEFcGcEsDsHNQCMBOBDWATApp0kAXFOeSAKDIIE8AHbUACQIFsAbAMXXme1gNAC8+IiVAAyUAG9QKbGkwB7WKyqgAKrWwAuCLGgBHcPUhVmSBa1ABfANyVNoAMoZoBaJFxM2nNN178hLw4uHj5xKRk5RWVVZz03D0wgnz8+HXA9Q2NTc0tbCmo6UABxbAIAQRQ3AGNWeiEACgaASkEAPgi0JEJ0aoIdZJD-a1aJJtaBDukunrQ+nTjXd08WYN9Q-itmm1AQJwALBXBWPCR6OAAzbBRZPDRIUAArKH4W9s7uojn+pxcEle8QzCVgo1SUhFA8DKlRqdR0pQqVWgtXqUisoHuGNgVDsZDBsAhMy+81+8WWSVWKQ2gkh0KRKJaADoib0CLi9lBRLV7h5yGQcNzZKBuZAHoN1v4AMKsHkRJTaYTEBDWfnYQX0EUPRb-CmAiV8aWy7AADwIvEwYspQIIhtFEQIAHcFDoeqIQfYigiYci6raHo03pMPrMSeLUjaZXatuFxu9pp9WQs-uSwxs-SMdntHIdjqdzrArjdcBiHs8IYGphiE98k2TEqmpZGHu78RCoYjYdg-fC6Z300JJOjMRgcaDwfwWd9u6SlvWrfqI7KhO3vSi-UzJ312WBOcqAEplcAoWAaOhjgn8WQEI8nzQ6A-X4+n7AAHi99LqHQHQ4eI8zYElBQiz6FRQBwM0UGYOBi0xMt+HjEMfm1FN53DFU8XHKtEIAJlrWcATWNChCvG9n2ZastzIIA

Interesting, `ReturnType` is able to correctly work out the return type as `{ abstract: SanitisedHtmlFragment }`, as does PhpStorm:

![Screenshot 2020-11-12 at 15 58 37](https://user-images.githubusercontent.com/1784740/98967354-4a34c000-2504-11eb-9993-5d8ee8bd4802.png)

**Comment by RyanCavanaugh** [comment]
Multiple call signatures in an intersection are treated as an overload set, not as a decomposition + recomposition of the arguments and return types. `ReturnType` will use the last overload out of those, but call resolution proceeds as normal using the first matching overload.

Basically you should use a different compositional mechanism than intersection if you want the described behavior.
