### ISSUE TITLE
Google Dart and reflection

### ISSUE THREAD

**Issue by unicomp21** [microsoft/TypeScript#41528]
If Dart compiles to javascript, and also supports reflection, why can't typescript do the same?

"Because TypeScript’s type system is fully erased, information about e.g. the instantiation of a generic type parameter is not available at runtime."

I can't help but think the above, from the typescript handbook, is a false argument.
https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-oop.html#reflection

**Comment by MartinJohns** [comment]
Because it's not a goal of TypeScript to support such functionality. They **could**, but they don't **want** to (with good reasons).

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
