### ISSUE TITLE
Infer parameter types from usage inserts JSDoc type at wrong location for arrow function

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#41526]
**TypeScript Version:**  4.2.0-dev.20201113

**Search Terms:**
- Quick fix
- Code action
- suggestion
- jsdoc

**Code**
For the JavaScript:

```js
// @ts-check

export function filter(names) {
    return names.filter(name => name.startsWith(''))
}
```

Run the `infer parameter types from usage` quick fix on `name` inside the function body

**Expected behavior:**
Something like:

```js
export function filter(names) {
    return names.filter((/** @type {string} */ name) => name.startsWith(''))
}
```

**Actual behavior:**
```js
export function filter(names) {
    /**
     * @param {string} name
     */
    return names.filter(name => name.startsWith(''))
}
```

The added JSDoc annotation is not valid so the type is not used by TypeScript. We continue to show the `infer parameter types from usage` on `name`

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
Note:

```ts
export function filter(names) {
  return names.filter(
      /**
       * @param {string} name
       */
      name => name.startsWith(''))
}
```

would also work. I'm not sure if it's more desirable, but it's certainly more work, so I'm going to leave it here for the record and recommend that we proceed with the original Expected example.
