### ISSUE TITLE
When a generic interface instance with a default type and passes the conditional judgment, it cannot be correctly identified as the corresponding type

### ISSUE THREAD

**Issue by misakamaiyako** [microsoft/TypeScript#41527]
## Search Terms

generic,default type, conditional judgment

## Suggestion

the value's type can be narrowed correctly
## Examples

```typescript
enum e  {a,b,c}
interface test<T extends e = e>{
  type: T
}
let instance:test = { type: e.a };
let array:Array<test<e.a>> = [];
if(instance.type===e.a){
  array.push(instance);
  // ↑ get error TS2345: Argument of type 'test<e>' is not assignable to parameter of type 'test<e.a>'. Type 'e' is not assignable to type 'e.a'
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Please provide samples that aren't full of syntax errors (???)

Anyway it seems like you want
```ts
let instance = { type: e.a } as const;
```

The described behavior is intended

**Comment by misakamaiyako** [comment]
> Please provide samples that aren't full of syntax errors (???)
> 
> Anyway it seems like you want
> 
> ```ts
> let instance = { type: e.a } as const;
> ```
> 
> The described behavior is intended

Sorry, I have made a mistake, I have put a new correct sample, thank you for reminding me

**Comment by misakamaiyako** [comment]
what i want is the type of  variable 'instance' will narrow from 'test' to 'test<e.a>' automatic
