### ISSUE TITLE
WithDescription utility type

### ISSUE THREAD

**Issue by entropitor** [microsoft/TypeScript#41531]
## Search Terms

- description
- conditional types
- utility type
- index types

## Suggestion
Add an utility type WithDescription that doesn't do anything at type check time but adds a string as documentation to that field / item

```typescript
type WithDescription<T, Doc extends string> = 
  /**
  * ${Doc}
  */
  T
```

## Use Cases
When computing types through indexed types / conditional types, one can add descriptions to the fields / type itself using this utility type
```typescript
type Variable<T> = {
  description: string;
  value: T;
}
type Scope<S extends {[name: string]: any}> = {
  [name: string]: Variable<S[name]>
}

type ScopeType<MyScope extends Scope<{[name: string]: any}>> = WithDescription<{
  [name in keyof MyScope]: WithDescription<MyScope[name]['value'], MyScope[name]['description']>
}, "This type is computed from a scope">

type MyScope = {
  foobar: {
    value: 42,
    description: "This foobar represents the meaning of life"
  }
} as const

type MyScopeTypeComputed = ScopeType<MyScope>

/** This type is computed from a scope */
type MyScopeTypeLiteral = {
  /** This foobar represents the meaning of life */
  foobar: number
}

// The `MyScopeTypeComputed` and `MyScopeTypeLiteral` should be the exact same type, including documentation strings
```

## Examples
See above

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by whzx5byb** [comment]
possibly related: https://github.com/microsoft/TypeScript/issues/41165
