### ISSUE TITLE
Please add typing for `navigator.brave`

### ISSUE THREAD

**Issue by JasonMFry** [microsoft/TypeScript#41532]
## Search Terms

- brave

## Suggestion

Please add typing for `navigator.brave` for the Brave Browser

## Use Cases

I'd like to use the browser's name in some text. 

## Examples

See [Brian Clifton](https://github.com/brave/brave-browser/issues/10165#issuecomment-641128278)'s comment on detecting Brave.

If I do `await navigator.brave?.isBrave?.();` I get an error `Property 'brave' does not exist on type 'Navigator'. [2339]` so I have to use `// @ts-ignore` which is not ideal

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We don't add browser-specific fields; you can use declaration merging or error supression (ts-ignore / `(navigator as any)`) to access this sort of property.
