### ISSUE TITLE
TSServer doesn't respect watchOptions for watchFile

### ISSUE THREAD

**Issue by gluxon** [microsoft/TypeScript#41549]
This seems to be intentional, but it looks like TSServer always uses fixed polling to watch files regardless of editor configured options.

<img alt="Screen Shot 2020-11-15 at 9 46 45 PM" src="https://user-images.githubusercontent.com/906558/99207549-3bf8d500-278c-11eb-8fd1-640126886964.png" width="511px" />

The [relevant code was written 4.5 years ago](https://github.com/microsoft/TypeScript/pull/8196). Does the TypeScript team plan on revisiting that decision? If not, should the `watchFile` option have its choices limited to reduce confusion? (I understand that will partly be a VSCode issue if the answer is yes.)

Personally I think it's strange that this is configurable in `tsc` but not `tsserver`.

---

**Technical Details**:

Here's the `watchUtilities.ts` call, which passes a `WatchOptions` arg:

https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/compiler/watchUtilities.ts#L440

https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/compiler/types.ts#L5844-L5853

Here's the implemention in `tsserver`, which actually overrides the default implementation and ignores the `options` arg.

https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/tsserver/server.ts#L885-L890

`tsserver.log` also reports a `watchFile` option of `3` ([`WatchFileKind.UseFsEvents`](https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/compiler/types.ts#L5703)), which is incorrect.

```
Info 40   [19:45:41.986] FileWatcher:: Added:: WatchInfo: /Volumes/git/TypeScript/src/server/types.ts 500 {"watchFile":3,"watchDirectory":0} Project:  WatchType: Closed Script info
```

**TypeScript Version:**  v4.2.0-dev.20201112

**Search Terms:**
- tsserver polling

**Steps to Reproduce**

Add the following to VSCode `settings.json`:

```json
{
  "typescript.tsserver.watchOptions": {
    "watchFile": "useFsEvents",
  }
}
```

**Expected behavior:**
- TSServer watches files through FSEvents.
- Updates to watched source files happen almost immediately.

**Actual behavior:**
- TSServer watches files with fixed polling.

**Comment by gluxon** [comment]
@zhengbli Apologies if you're no longer involved with TypeScript, but if you have a moment I'm curious if it was intentional for this to be non-configurable in `tsserver` (but configurable in `tsc`).

**Comment by gluxon** [comment]
This affects language service plugins that provide typings for imported files.

https://github.com/mrmckeb/typescript-plugin-css-modules/issues/95

**Comment by dko-slapdash** [comment]
What an awesome improvement would it be at least on MacOS VSCode! We currently wait for 20-40 seconds after a git pull for some files to be typechecked properly in VSCode. I made an experiment, manually commented out the code @gluxon mentioned above right in tsserver.js:

![image](https://user-images.githubusercontent.com/46383452/100085940-8a981600-2e01-11eb-8bd4-a64ffa7506d1.png)

and it made VSCode to pickup changes within several seconds.

**Comment by ericjeney** [comment]
@sheetalkamat Do you have any updates on whether this is something that the TypeScript team is interested in accepting a fix for? This is the only thing blocking my team from adding type-safety to the last untyped piece of our codebase (CSS modules).

**Comment by sheetalkamat** [comment]
This is scheduled for 4.2.1

**Comment by gluxon** [comment]
@sheetalkamat Thanks! 🎉
