### ISSUE TITLE
Interesting use case, might be thought-provoking

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#41540]
## Search Terms

type-checker, checker, unnecessary, work, extra, match, never

## Suggestion

This is not really a feature request––just a use case that I thought might be valuable to share, & which could later become a feature request.

## Use Cases

Let's say we have two distinct types.

```ts
const AKind = Symbol.for("A");
type AKind = typeof AKind;
interface A {
    [AKind]: true;
}

const BKind = Symbol.for("B");
type BKind = typeof BKind;
interface B {
    [BKind]: true;
}
```

And some generics that operate on the two types.

```ts
type AcceptsA<X extends A> = [X];
type AcceptsB<X extends B> = [X];
```

And we want to create a `Match` type, whose first type param is a union of `A` and `B`, and whose second and third arguments are the types to evaluate to, depending on whether the first is `A` or `B`.

```ts
type Match<X extends A | B, IfA, IfB> = X extends A ? IfA : X extends B ? IfB : never;
```

This doesn't get us very far today. We need to do the subtype check before we can pass `X` to any type param of `IfA` or `IfB`.

```ts
type AMatched = Match<A, AcceptsA<A>, AcceptsB<A>>
//                                             ^
//                                             Type Error
type BMatched = Match<B, AcceptsB<B>, AcceptsA<B>>
//                                             ^
//                                             Type Error
```

These errors make sense, given that `AcceptsB` cannot accept `A`, and `AcceptsA` cannot accept `B`... however, would the type-checker be able to prove that the incompatible-type-provided utility type will never be instantiated?

It seems that this type error doesn't help us much. Could we forgo the subtype check? Am I missing anything, or could this be the start of something beautiful?

## Checklist

... commenting this out for now.

**Comment by RyanCavanaugh** [comment]
This use case doesn't make sense to me because all of this is evaluated statically. If you write `Match<T, U, V>` only either `U` or `V` will be selected and it's pre-knowable which, so you should just write `U` or `V`. In higher-order when this is *not* immediately knowable, then there isn't an error. What is a realistic example where this comes up?

**Comment by harrysolovay** [comment]
Reducing boilerplate in other types (not having to repeat the condition / subtype check). In the following use case, we want to create utilities that accept either root or child node constructors.

A root constructor looks like this:

```ts
type RootCtor = new (props: any) => any;
```

And a child constructor looks like this:

```ts
type ChildCtor = new (parent: Construct, id: string, props: any) => any;
```

As we create utility types which act on these constructors, we'll need to repeat the condition to distinguish root from child. For instance, in gathering props:

```ts
type ConstructCtor = RootCtor | ChildCtor;

type GetProps<Ctor extends ConstructCtor> =
  Ctor extends ChildCtor ? Parameters<Ctor>[2] :
  Ctor extends RootCtor ? Parameters<Ctor>[0] :
  never;
```

I suppose what we really need here is pattern matching. I couldn't find a relevant feature request ([here's my search](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+pattern+match+type+label%3Afeature-request+)). How would you feel about this issue becoming a feature request for something along the following lines?:

Taking into account the rough sketch of conditional assignability:

```ts
type IsRootCtor = match C extends ConstructCtor =>
  C extends RootCtor ? true : false;

type IsChildCtor = match C extends ConstructCtor =>
  C extends ChildCtor ? true : false;

type Props<C extends ConstructCtor> = match {
  IsRootCtor => Parameters<Ctor>[1],
  IsChildCtor => Parameters<Ctor>[2],
}
```

Ideally this matching could be exhaustive. Any thoughts?
