### ISSUE TITLE
TypeScript 1.5 const enum changes break enum.toString()

### ISSUE THREAD

**Issue by styfle** [Microsoft/TypeScript#4155]
I followed the [recommendation](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#enum-reference-in-lining-changes) by changing my `.d.ts` files to use `const` for enum definitions (these are generated view Web Essentials plugin from server-side classes.

Now I am able to compile but I get run time errors when I try to use toString on a number literal. Previously this was not a problem because the compiler put in a comment (which I liked btw) and a space. Here is some example code to reproduce the issue.

```ts
// FileId.d.ts
declare module server {
	const enum FieldId {
		ABSTRACT = 7000,
		RANK = 40002
	}
}

// Usage
var f = getById(server.FieldId.RANK.toString());

// Previous output
var f = getById(4002 /* RANK */.toString());

// TypeScript 1.5 output
var f = getById(4002.toString());
```

This is disappointing because TypeScript is supposed to catch errors like this at compile time. Should this be a compiler error in 1.5? What is the suggested solution?

**Comment by RyanCavanaugh** [comment]
The comment is back in `master`, but it *is* removed under `--removeComments`. We should be inserting the extra `.` automatically when needed.

**Comment by styfle** [comment]
I have the `Keep comments in JavaScript output` unchecked to remove comments. Enabling it seems to show the enum comment as it did in the previous version. It sounds like the the enum comment should be emitted regardless of the flag.

Thanks for the quick response.
