### ISSUE TITLE
keyof typeof Enum yields a different type within a mapped type

### ISSUE THREAD

**Issue by cntkillme** [microsoft/TypeScript#41559]
**TypeScript Version:**  4.1.0-beta

**Search Terms:** enum mapped type keyof

**Code**

```ts
enum Enum { a, b };
type EnumKeys = keyof typeof Enum;
type Type1 = { [K in EnumKeys]: true }; // { a: true; b: true; }
type Type2 = { [K in keyof typeof Enum]: true };  // { [x: number]: true, readonly a: true; readonly b: true; }
```

**Expected behavior:**
`Type1` and `Type2` are equivalent (`{ a: true; b: true; }`).

**Actual behavior:**
`Type2` adds both an index signature and the `readonly` modifier to both `a` and `b`.

**Playground Link:**
[https://www.typescriptlang.org/play?ts=4.1.0-beta&ssl=1&ssc=1&pln=5&pc=1#code/KYOwrgtgBAou0G8oEMA0UBGUC+BuAUAC4CeADsLPANLDEDOUAvFANa0D2AZlCeV5ZAK8KAFTLAAjEyhIA2lSgBLEAIg16AXQBcPAE5gKeKAHpjMlDsL7guTJeu3sRcVDHkATNLkLlrDt2F+OEhtPQMcWxMzOQAPHXgMYF1QqwN0XWBkABN2EAAbYgswmygM7NyCu2LHfCA](https://www.typescriptlang.org/play?ts=4.1.0-beta&ssl=1&ssc=1&pln=5&pc=1#code/KYOwrgtgBAou0G8oEMA0UBGUC+BuAUAC4CeADsLPANLDEDOUAvFANa0D2AZlCeV5ZAK8KAFTLAAjEyhIA2lSgBLEAIg16AXQBcPAE5gKeKAHpjMlDsL7guTJeu3sRcVDHkATNLkLlrDt2F+OEhtPQMcWxMzOQAPHXgMYF1QqwN0XWBkABN2EAAbYgswmygM7NyCu2LHfCA)

**Comment by RyanCavanaugh** [comment]
The mapped type form `{ [K in keyof T]: U ]` is a *homomorphic mapped type* that preserves more information about the type `T`. You can use this syntax to get that behavior or not use that syntax if you don't want that behavior.
