### ISSUE TITLE
String literal in typeof import in typescript 4.1.0-beta.

### ISSUE THREAD

**Issue by ShanonJackson** [microsoft/TypeScript#41550]
**TypeScript Version:** 4.1.0-beta

**Code**
```ts
type T = "./api/hello";
type test = typeof import(`${T}`) // String literal expected.
```

**Expected behavior:**
No error.

**Actual behavior:**
Error

**Playground Link:** 

The reason this is desirable is because i have a API of "typed" endpoints and i often do this.
```ts
// tsconfig.paths allows that import statement to resolve
// api here resolves the ReturnType of that import which is a function.
const response = await api<typeof import("/api/user")>("/api/user")
```
with generics + new string literal types in 4.1 i was hoping to achieve this.
```ts
// tsconfig.paths allows that import statement to resolve
const response = await api("/api/user") 
```

**Comment by DanielRosenwasser** [comment]
My understanding is that in order to type-check the program, all program files need to be loaded to analyze each scope and make sense of the world. In order to do that, all import strings need to be known ahead of time. As a result, there unfortunately can't be a cycle between the type-checking and program construction phases.

**Comment by ShanonJackson** [comment]
If that's true how would .d.ts files work currently? because they are not referenced by any import statement but are implicitly in scope ?  (Module augmentation)

Even if this is a design limitation, is there any chance we can modify the implementation to allow TSC to load in things on the fly?

**Comment by RyanCavanaugh** [comment]
Program construction proceeds as follows:
 * Start with a list of initial files (from `files` or `include`)
 * Parse them for `import` or `reference` directives
 * Add those files to the mix
 * Repeat the last 2 steps until you stop finding new files
 * Bind each file to determine the global scope
 * Start typechecking

There is no going backwards in this algorithm - once you bring in a new file, you'd have to completely restart the typechecking process since you have no real way of knowing whether type data in that file invalidated previous typechecking outputs.

**Comment by ShanonJackson** [comment]
@RyanCavanaugh @DanielRosenwasser 
 I've been thinking about this 'design limitation' for along time, and I think I've got a modified proposal.

Types that can represent your file system.

Before: 
```ts
const response = await api<typeof import("/api/user")>("/api/user")
```
After:
```ts
const response = await api.user(1);
```

```ts
// implementation
const api = new Proxy<FileSystem<"../../../api">>(...);
```

Semantics of 'FileSystem' (name yet to be finalized can be determined as follows, it pulls in a nested object of modules that represent the file system's import("...")'s types with folders represented as object types with keys that allow you to access the nested folders.

TL:DR:
FileSystem traverses the files in the specified folder:
1: If that file is a module it adds it as a key at the depth position with its type set to its ```typeof import("...")```
2: If that file is a folder it adds it as a object with keys to allow you traverse children

Because the end result of this type will just be a object it can easily be used in conjunction with existing 'Mapped' types etc.


More use cases:
**1:** Really strong support for image paths, and removing files in refactors that are referenced by string path.
```ts
 // (note: requires augmentation of JSX types);
<img src={"/static/dolphin.png"}/> // error dolphin.png isn't loaded in the file system.
```

**2:**  Support for string based routing in applications and protection against routing refactors at a type-level.
```ts
 // (note: requires augmentation of JSX types);
<a href={"/home/name"}/>
```

**2:**  Statically typed readFileSync
```ts
const readFileSystem = (path: keyof FileSystem<".">): string=> fs.readFileSync(path);
```


What would be your thoughts on this?

**Comment by ShanonJackson** [comment]
Think this has legs so created a separate feature request, feel free to shoot it down there.
https://github.com/microsoft/TypeScript/issues/42046

**Comment by phenomnomnominal** [comment]
I basically just want to be able to imbue a function with the same power that a `require` statement or `import` statement has.

I'd love to be able to do something like `type CustomRequire<Module> = (id: string) => SomeModifier<Module>` and let the compile know somehow that `Module = typeof require(id);`
