### ISSUE TITLE
Add a way to omit `break` in `switch`

### ISSUE THREAD

**Issue by x1shi** [microsoft/TypeScript#41556]
## Search Terms
`switch`

## Suggestion
A way to omit `break` in `switch` 

## Use Cases
In `switch`, use `only` to automatically add `break` implicitly

## Examples
ts:
```
switch(n){
    case 1: null
    only 2: null
}
```
to js:
```
switch(n){
    case 1:
        null
    case 2:
        null
        break
}
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This isn't related to adding types to JavaScript, so should be taken up as a TC39 proposal.
