### ISSUE TITLE
Type parameter of mapped type widened to 'string' when using 'keyof any'

### ISSUE THREAD

**Issue by sg495** [microsoft/TypeScript#41554]
**TypeScript Version:**  4.0.5

**Search Terms:** "keyof any", "mapped types" 

**Code**

```ts
type MyMappedType = {
  [K in keyof any]: {key: K, value: string}
};
let myMap: MyMappedType = {
  "apple": {key: "orange", value: "delicious"}
};
```

**Expected behavior:**

I would have expected the code to raise error TS2322 `Type '"orange"' is not assignable to type '"apple"'.`, as done by the following code:

```ts
type MyMappedType = {
  [K in "apple" | "orange"]: { key: K, value: string }
};
let myMap: MyMappedType = {
  "apple": { key: "orange", value: "delicious" }
};
```

**Actual behavior:**

No error.

**Playground Link:** https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiMEMyQCYBVzQLxQN4CgooBtAaSgEsA7KAawhAHsAzKBKkAXQC496RepADRQAbggA2AVwi8AzsABO1AOYBffGoDc+fBIjAoAW3hJecRMgjpMUHASIAiJGH2Peufr0eNF7FRCOIuLSslCOKBASFADGFIxSco4a2kA

**Comment by RyanCavanaugh** [comment]
I don't know what to say except that your expectation isn't correct. It's effectively the same as writing
```ts
type MyMappedType = {
  [K: string]: {key: string, value: string}
};
```
There isn't a way from a nongeneric declaration to enforce a key-value match like that; that isn't what the syntax you have there means.

**Comment by sg495** [comment]
Thank you for your reply! Just to be sure that what I mean came through, I'm talking about widening of `K` on the right (ie in `key: K`), not on the left (ie in `K in ...`). I agree that `keyof any` is simply `string`, no questions there. However, there is clearly a difference in behaviour between the first and second code example in the original filing, in the sense that the second code example is **not** the same as the following code example:

```ts
type MyMappedType = {
  [K in "apple" | "orange"]: { key: "apple" | "orange", value: string }
};
```

The second code example in the original filing has an additional static check that ensures that the `key` field in an object literal matches the property name, while the example with `keyof any` does not, despite the sole difference being the replacement of `keyof any` with `"apple" | "orange"`. Perhaps this is a feature request then?

**Comment by AlCalzone** [comment]
@sg495 you can do something like this:
```ts
type Validate<T extends Record<keyof T, any>> = {
	[K in keyof T]: {key: K, value: string};
}
function validate<T extends Validate<T>>(obj: T): T { return obj; }

let myMap = validate({
  "apple": {key: "orange", value: "delicious"},
  //        ~~~ Type '"orange"' is not assignable to type '"apple"'.(2322)
  "banana": {key: "banana", value: "yuck"}
});
```

I'm not sure if there is some conditional trick to do this without the no-op function.

**Comment by sg495** [comment]
Thank you, @AlCalzone: that's a neat solution 👍. However, I'm still wondering why the difference in behaviour when `keyof any` is used...

**Comment by sg495** [comment]
I mean: it has been marked as "Working as Intended", but I am not really convinced it is _actually_ working as intended. The example given by @RyanCavanaugh as being "effectively the same" as the mapped type I used in my original filing does not quite follow the same pattern (as I discussed in a previous comment). It would be good to have the points I raised clarified before this is abandoned.
