### ISSUE TITLE
why not can't proxy a enum object

### ISSUE THREAD

**Issue by xuyanzhuqing** [microsoft/TypeScript#41560]
when I enum a object,  as time goes by, the backend allways change  enum in their code,  and I have to follow them, that is really a bad devloping experience, so I sugguest that the enum type data can be proxy as a  object, so I can set the getter as my convenient way, I hope someone can hear my voice

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
