### ISSUE TITLE
Typescript 1.5 errors in VS2015

### ISSUE THREAD

**Issue by jannavarro** [Microsoft/TypeScript#4156]
Just installed VS2015. Used ES6 syntax and got an error:

![image](https://cloud.githubusercontent.com/assets/4499051/9079601/98e27096-3b7e-11e5-8228-3c77fb6742f1.png)

Upon checking the project file I have 1.5 set already.

![image](https://cloud.githubusercontent.com/assets/4499051/9079614/bbdcbca0-3b7e-11e5-9f53-1429c81a2e75.png)

I also tried setting ECMAScript version in VS Project > Properties > TypeScript Build to ES6

![image](https://cloud.githubusercontent.com/assets/4499051/9079636/f748dbd4-3b7e-11e5-8f4d-171bd6463959.png)

**Comment by mhegazy** [comment]
This is not a message that we generate.. do you have an extension installed? resharper? webessentials? 

if so, you need to update your extension or disable it.

**Comment by jannavarro** [comment]
@mhegazy My bad. It was resharper that was causing the error. I updated it to 1.5. Thanks for your suggestion.
