### ISSUE TITLE
The types `{[P in keyof 1]: P}` and `{[P in keyof 1]: P}` both evaluate to `1` when eta-reduced

### ISSUE THREAD

**Issue by isiahmeadows** [microsoft/TypeScript#41575]
**TypeScript Version:**  4.2.0-dev.20201112 nightly, 4.1.0-beta, 4.0.5, 3.9.7, 3.8.3, 3.7.5, 3.6.2, 3.5.1, 3.3.3

**Search Terms:** keyof value, keyof number

**Expected behavior:** See code.

**Actual behavior:** See code.

**Related Issues:** None I'm aware of.

**Code**
```ts
declare function gen<T>(): T
declare function assign<T>(value: T): void

/* Dynamic keys */
type DynamicKeys = {
  toString: "toString"
  toFixed: "toFixed"
  toExponential: "toExponential"
  toPrecision: "toPrecision"
  valueOf: "valueOf"
  toLocaleString: "toLocaleString"
}

type DirectDynamic<T> = { [P in keyof T]: P }
type IndirectDynamicHelper<T, K extends keyof T> = { [P in K]: P }
type IndirectDynamic<T> = IndirectDynamicHelper<T, keyof T>

type ManualDynamic = { [P in keyof 1]: P }
type DirectAliasDynamic = DirectDynamic<1>
type IndirectAliasDynamic = IndirectDynamic<1>

// Correctly works
assign<DynamicKeys>(gen<ManualDynamic>())
assign<ManualDynamic>(gen<DynamicKeys>())

// Correctly fails
assign<1>(gen<ManualDynamic>())
assign<ManualDynamic>(gen<1>())

// Erroneously fails
assign<DynamicKeys>(gen<DirectAliasDynamic>())
assign<DirectAliasDynamic>(gen<DynamicKeys>())

// Erroneously works
assign<1>(gen<DirectAliasDynamic>())
assign<DirectAliasDynamic>(gen<1>())

// Correctly works
assign<DynamicKeys>(gen<IndirectAliasDynamic>())
assign<IndirectAliasDynamic>(gen<DynamicKeys>())

// Correctly fails
assign<1>(gen<IndirectAliasDynamic>())
assign<IndirectAliasDynamic>(gen<1>())

/* Static keys */
type StaticKeys = {
  toString: "test"
  toFixed: "test"
  toExponential: "test"
  toPrecision: "test"
  valueOf: "test"
  toLocaleString: "test"
}

type DirectStatic<T> = { [P in keyof T]: "test" }
type IndirectStaticHelper<T, K extends keyof T> = { [P in K]: "test" }
type IndirectStatic<T> = IndirectStaticHelper<T, keyof T>

type ManualStatic = { [P in keyof 1]: "test" }
type DirectAliasStatic = DirectStatic<1>
type IndirectAliasStatic = IndirectStatic<1>

// Correctly works
assign<StaticKeys>(gen<ManualStatic>())
assign<ManualStatic>(gen<StaticKeys>())

// Correctly fails
assign<1>(gen<ManualStatic>())
assign<ManualStatic>(gen<1>())

// Erroneously fails
assign<StaticKeys>(gen<DirectAliasStatic>())
assign<DirectAliasStatic>(gen<StaticKeys>())

// Erroneously works
assign<1>(gen<DirectAliasStatic>())
assign<DirectAliasStatic>(gen<1>())

// Correctly works
assign<StaticKeys>(gen<IndirectAliasStatic>())
assign<IndirectAliasStatic>(gen<StaticKeys>())

// Correctly fails
assign<1>(gen<IndirectAliasStatic>())
assign<IndirectAliasStatic>(gen<1>())
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// Correctly works
assign(gen());
assign(gen());
// Correctly fails
assign(gen());
assign(gen());
// Erroneously fails
assign(gen());
assign(gen());
// Erroneously works
assign(gen());
assign(gen());
// Correctly works
assign(gen());
assign(gen());
// Correctly fails
assign(gen());
assign(gen());
// Correctly works
assign(gen());
assign(gen());
// Correctly fails
assign(gen());
assign(gen());
// Erroneously fails
assign(gen());
assign(gen());
// Erroneously works
assign(gen());
assign(gen());
// Correctly works
assign(gen());
assign(gen());
// Correctly fails
assign(gen());
assign(gen());

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMRUAeAFQD4AKASgC54yAoUSWBFdbPeKAZz5YCpSlQBuUCMhAMy9eGJxZgTJgHoAVPAAiAT1RQAtljDwA1iF194GtUwy6ADgj0HjYANKXrAXngBvJnh4DBwAZQwYLFQCBgAiUIiomLigkJwAMSwADxBgeNCs3OBU4NCAUWzHPGJsSQKcSurUWqxJUvSABTgwLEE8Bu7wPtxUDokpEAB5RHiJ6RmO0IAZHDBJECTo2PgEnFX1iE3I7dSAX1UHZx0sHoxXIxNyCng-f3gAbU74aPNLHEQjAAugxvhcrggAJKoYC3cD3fSPMAACRAEGcMHIABp4B54CBshhiMBrBZdADGC83p9vr8PCD4GD7E4oTC4ZgHu5nq94NDYXdOSZUeiQJiyDiyRTKJcWfAALJQVDISSC0zUr4-fCSwEARgZTIhNzuAEEIG0+Kqedp2Qi3E8dRRmdc+TbTebLX4XQLEVyHao1Gp4ABhHAwO4QXTwADuobMfCY-EEwhIqq8VmoRFICqVKp9JmoNBoCYEQiziuVEFVGeIKbznm8BaL6kDIbD8IjSCgWAg8cTpZIDqomZI2YrVdoRb7ydHubtYGrpEHhf9gfKYZqOGQfA7iC7PeLSdIqYbQ5r1pNZv44+XU6PrsvFrrC9rc7TfEbK-ga5gG63HZjMBxge-aDsO57wm6V5PhOwHJuBmCQY+c7PkuTYBsGobhpGAFAbeL5Im+z5ehBD7XpOJbJsRCGkdBYF1oRMHNhhbaYDue69hRi5EWyF7utBN6cSQVEYIh47Dqh-paBEUDYKYZLWLYToINJslvjygRlOEJwxAUIB8BgSyZDkeS6fphlNDUqB1BApkGWkoRDL0-SoLZ4ySAssy7ESZn2fsawbFsOleXpdkXEpRrwipTyUOpNKan85KAmQDIJCFcTwOCsrCVFKJohi2K4vihLEqS-xJVSARxXSKXeQZGXhdlGAydFFWNc1uUimKEplZSMrXDOEA5bFGq-Nq8B6q59WGvBIkPkNfgzTlA6OoawmIfNvI8ZFTWyctn6tlh0axhxh4kDlDHDgNOUfnhV07fmp6kOdJ7LkxB3tpGu7didIHPnd7U3YJ-2yShH5Md+v7bp97GwU9931umj0pve5rXTBeEzet8PPs9iOvehEMtJuUNHYBP3JqBZ4o-waMCadmNzdjSMSW9mEfaTuGCbj75I2tjMA+jgl86jTPDtzYPoe9rHQ99sPLbzW3USLAt0-2ws06LNaoUAA)

**Comment by ahejlsberg** [comment]
I think the key issue here is that `{ [P in keyof T]: P }`, where `T` is a naked type variable, is considered a homomorphic mapped type, whereas `{ [P in keyof 1]: P }` is not because `keyof 1` is eagerly resolved to a union of literal types. For homomorphic mapped types

* if T is a union type we distribute the mapped type over the union,
* if T is a primitive type no mapping is performed and the result is simply T,
* if T is an array we map to an array where the element type has been transformed,
* if T is a tuple we map to a tuple where the element types have been transformed, and
* otherwise we map to an object type where the type of each property has been transformed.

We've had these distinctions in place for a very long time, not sure we can change it now without breaking lots of code.
