### ISSUE TITLE
Still Not Fixed: Windows Script Host can't execute tsc.js

### ISSUE THREAD

**Issue by KGtk-git** [microsoft/TypeScript#41579]
@RyanCavanaugh  Not sure why did you closed the #41311 - I still have it in 4.0.3, and it is even there in 3.5.3   

**Issue ( Let me describe in 3 parts):**
_Part 1:_
After downloading TypeScript_SDK.exe from (https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-403), installing the exe by double-clicking; when I run below command from windows command prompt, I get error.
Command: "C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.0\tsc" -help
Error:  An error window with title "Windows Script Host" and below details:
         Script: C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.0\tsc.js
         Line: 168
         Char: 31
         Error:   Expected identifier
         Code: 800A03F2
         Source: Microsoft JScript compilation error

_Part 2:_
The same error appears with version TypeScript 3.5.3 (https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-353)

_Part 3:_
For version 4.0, when I manually removed the ending comma,
               Commented out line 524:       },
               Added line 524:      }
    I got another error 
                Script: C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.0\tsc.js
                Line: 1422
                Char: 22
                Error:   Expected identifier
                Code: 800A03F2
    
My env:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18363 Build 18363

Context: 
I'm trying to set up typescript project in Microsoft's Visual Studio Code following this page https://code.visualstudio.com/docs/typescript/typescript-compiling

**Comment by MartinJohns** [comment]
#41311 was closed because there was nothing left to do.

> Windows Script Host is not a supported runtime environment

Windows Script Host can't execute TypeScript, that is right. And it won't be able to. It's not supported.

**Comment by IllusionMH** [comment]
It won't be fixed since this is no longer supported (for a long time) as mentioned in #41311.

Are you using Visual Studio or Visual Studio code? Because you are linking extension for VS not VS Code, but later say

> I'm trying to set up typescript project in Microsoft's Visual Studio Code following this page https://code.visualstudio.com/docs/typescript/typescript-compiling

In this guide for VS Code it clearly states to install from npm and use built-in tasks that utilize Node.js as runtime.

**Comment by KGtk-git** [comment]
Thank you for the clarifications.
In that case, I'll take it with Visual Studio Code folks.

**Comment by KGtk-git** [comment]
> It won't be fixed since this is no longer supported (for a long time) as mentioned in #41311.
> 
> Are you using Visual Studio or Visual Studio code? Because you are linking extension for VS not VS Code, but later say
> 
> > I'm trying to set up typescript project in Microsoft's Visual Studio Code following this page https://code.visualstudio.com/docs/typescript/typescript-compiling
> 
> In this guide for VS Code it clearly states to install from npm and use built-in tasks that utilize Node.js as runtime.

Thank you. My lack of knowledge with windows platform, caused some confusion. This suggestion of yours in deed helped me got it running. 
Thanks again.
