### ISSUE TITLE
TypeScript erroneously says we cannot use accessors in abstract class constructors

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#41576]
**TypeScript Version:**  4.0.5

**Search Terms:**

abstract getter used in constructor

**Code**

```ts
// This type error makes sense, because subclass hasn't
// initialized the property yet:
abstract class Foo {
    constructor() {
        console.log(this.foo) // logs undefined
    }

    abstract foo: number
}

class Bar extends Foo {
    foo = 123
}

new Bar()

// This type error does not make sense, because getters are located
// on prototypes, so every super class will be able to read them:
abstract class Foo2 {
    constructor() {
        console.log(this.foo) // logs 123
    }

    abstract get foo(): number
}

class Bar2 extends Foo2 {
    get foo() { return 123 }
}

new Bar2()
```

[playground example](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&useDefineForClassFields=true&noUnusedLocals=true&noUnusedParameters=true#code/PTAEAkEsBdWgLApqATgVwHagEZutAewwDoAoUkUAFXkgGc4BPAB2URRQJVAFsBDANaIGdRBlEAaHIgDGfNKNB002GQBs+dBvE0YA5NAphIGGJD5rIAL0QATOElDNOrFNEahGiaAC5SfbDpoFD4ZWHVNBgAxAgJQAG9SUGTQGSIg9DCuAAoASgSklKK08QI1RGI1AgBzbIR6YgAzWPzKKuqGTFtERpM7QuSAX3IigIzQ2GaCH1AMNB5sdlJh0gitUAAhPm5EAA9oMVto2IKiqdAAXlAARgAmAGZl8gxEAHdN7bzyShp6JlZQOxONxbARhLMCLB+EIlGJJNI5ApkNVvAcUAxtsgqnIDrYjKAiE5OIR3Kw6FI6HFEAA3dgeZSuVIadavSBqNTSUABcpwOIoRB8ewIRA8PxjYITJmRUAxAi3U4pEoZNBZFB5BVFZJKsoVdp1Wh0JotUBtGoMO6PIorUaBCVhUAoyaxPIzOYLJYrNYMLYoeV7A4YI4y2LyxJFR2gKbq+KobxoFBYC2gYYrF7vH23PJAA)

**Expected behavior:**

The second example should not have a type error. It works just fine (see console output).

**Actual behavior:**

There's a type error.

```
Abstract property 'foo' in class 'Foo2' cannot be accessed in the constructor.
```

**Comment by MartinJohns** [comment]
Even if it would work you might want to reconsider your approach, as accessing virtual members in the constructor is generally a very bad idea. Just consider this example:

    class Bar2 extends Foo2 {
        private _foo = 123;
        get foo() { return this._foo }
    }

Trying to access `foo` in the constructor results in `undefined`.

**Comment by trusktr** [comment]
@MartinJohns Ah, I suppose it makes sense to prevent that type of code just for the subset of way to cause an error.
