### ISSUE TITLE
Composite project incremental build always rebuilds project despite no source file change

### ISSUE THREAD

**Issue by pyrocat101** [microsoft/TypeScript#41584]
**TypeScript Version:**  4.2.0-dev.20201118

**Search Terms:** composite project, tsbuild, incremental build

**Code**

The minimal repro: https://github.com/pyrocat101/tsbuild-bug-repro

Three projects in this repo: `a`, `b`, and `c`. They are configured to only emit `d.ts` files to
`a_out`, `b_out`, and `c_out` respectively. With project reference, `c` depends on `b` depends on `a`.

`b/doubly_included.ts` is included in both `a` project and `b` project (**something we cannot change easily**). To allow that, `a`'s rootDir is set to `..` to allow referencing source files in its sibling folder `b`.

Run `yarn tsc -b` to populate `a_out`, `b_out`, and `c_out`. Notice that there is no `b_out/doubly_included.d.ts`,
but there is `a_out/b/doubly_included.d.ts`. `b` is also rebuilt despite no file change with the
reason reported in the verbose mode:

```
Project 'b/tsconfig.json' is out of date because output file 'b_out/doubly_included.d.ts' does not exist
```

Run `yarn tsc -b --verbose` multiple times, despite no file change, `b` project will be always be rebuilt.

**Expected behavior:**

`tsc` should check the timestamp of `a_out/b/doubly_included.d.ts` instead of the non-existent `b_out/doubly_included.d.ts`.

**Actual behavior:**

`tsc` always rebuild `b` project because it cannot find `b_out/doubly_included.d.ts`, which will never exist.

**Playground Link:** N/A (see the minimal repro repo link above)

**Related Issues:** N/A

**Comment by RA80533** [comment]
The project has a circular dependency. `a` is attempting to include `b` via its `include` property while `b` includes `a` as a project reference.

Split the project further, either by separating the files into new folders and creating more tsconfig.json files for those folders *or* creating a tsconfig.json file just for the file `a` needs from ./b (in this case, `a` is including doubly_included.ts).

**Comment by RyanCavanaugh** [comment]
I agree with @RA80533's analysis; this is effectively a project misconfiguration.
