### ISSUE TITLE
Uncalled-function error with function check in binary expression misses usage in body

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#41586]
```ts repro
declare var f: () => void
declare var b: boolean
if (f && b) {
    f()
}
```

**Expected behavior:**
No error

**Actual behavior:**
Error: "Did you mean to call 'f'?"

**Comment by sandersn** [comment]
@a-tarasyuk  you might be interested in this too.

**Comment by MartinJohns** [comment]
In version 4.2.0-dev.20201112 (nightly on the playground) this works as expected. With `strictNullChecks` enabled it errors, without `strictNullChecks` it provides no error.

**Comment by sandersn** [comment]
@MartinJohns I think that's because the problem started with @a-tarasyuk's recent PR to issue the error for binary expressions. Before that, the checker never issued an error for uncalled functions in binary expressions.

Separately, this means that the playground nightly is a week out of date, which is concerning. I'll let @orta know.

**Comment by a-tarasyuk** [comment]
@sandersn Yep. I think these issues (https://github.com/microsoft/TypeScript/issues/41586, https://github.com/microsoft/TypeScript/issues/41588) are equal and both related to this https://github.com/microsoft/TypeScript/pull/40260#discussion_r500246807.

**Comment by sandersn** [comment]
Makes sense. I have some time this morning so I can look at it if you're not already working on it.

**Comment by a-tarasyuk** [comment]
I checked this case before, as I remember we need to handle binary expression and condition body.

**Comment by sandersn** [comment]
I think you just have to find the parent of the binary expression and if it's IfStatement, pass the body to checkTestingKnownTruthyCallableType. I've got a fix for this bug that does just that; I'm going to make sure if fixes the other bug too.

**Comment by sandersn** [comment]
No, the other bug also repros without a binary expression. I'll update the repro for it.
