### ISSUE TITLE
Uncalled-function check misses usage of complex property access

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#41588]
**Code**

Based on chrome-app on Definitely Typed:

```ts
    var chrome = {
        platformKeys: {
            subtleCrypto() {
                return {
                    sign() {},
                    exportKey() { return true }
                }
            }
        }
    }
    // ok
    if (chrome.platformKeys.subtleCrypto().exportKey) {
        chrome.platformKeys.subtleCrypto().exportKey
    }
```

**Expected behavior:**
No error

**Actual behavior:**
Error: "Did you mean to call 'exportKey'?"

**Comment by sandersn** [comment]
@a-tarasyuk you might be interested in this too.

**Comment by MartinJohns** [comment]
This works as expected with TypeScript 4.2.0-dev.20201119. It provides an error with `strictNullChecks` enabled, and provides no error with `strictNullChecks` disabled.

**Comment by sandersn** [comment]
There should be no error under any setting since `chrome.platformKeys.subtleCrypto().sign` is used in the body of the `if`.
