### ISSUE TITLE
Assignability issue with keyof generic in interface

### ISSUE THREAD

**Issue by sharshuv-quotient** [microsoft/TypeScript#41595]
**TypeScript Version:**  4.0.5

**Search Terms:** generic, assignability, keyof, interface

**Code**

```ts
interface Test<G extends { [key: string]: any }> {
  x: keyof G;
}

declare const x: Test<{x: number}>;
const y: Test<{ [key: string]: any }> = x; // error
```

**Expected behavior:**
Expect last assignment to be allowed, since `keyof {x: number}` eqals `'x'` which is assignable to `keyof {[key: string]: any}` equals `string`.

**Actual behavior:**
Fails with the following error:
```ts
Type 'Test<{ x: number; }>' is not assignable to type 'Test<{ [key: string]: any; }>'. Property 'x' is missing in type '{ [key: string]: any; }' but required in type '{ x: number; }'.
```
For some reason it requires `{[key: string]: any}` to be assignable to `{x: number}` instead of just vice versa, which is not needed.

**Playground Link:** 
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5gDwHFkQAekIAJhsgN7IDaA1hAJ4BcyWUoA5gLqtwiNkAXwB8VAFDJkhVg0YB7GMlwBucUPHjSEBABs4UFAnkgs01uizZKM5CACuAWwBG0UWuOmwyFmkw5qeiZWdi5eZH5BUWQAXmkVIA

**Other notes:** 
Please note that does not reproduce without using an interface:
```ts
type Test<G extends { [key: string]: any }> = keyof G;

declare const x: Test<{ x: number }>;
const y: Test<{ [key: string]: any }> = x; // works
```

Also this does not reproduce without using keyof:

```
interface Test<G extends { [key: string]: any }> {
  x: G;
}

declare const x: Test<{x: number}>;
const y: Test<{ [key: string]: any }> = x;
```

Whether this is intended for some reason (though I can't think of any) or not, I'd be happy for a workaround if exits.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `Test` is contravariant on `G` because its only use of `G` is in a contravariant position. It's easier to demonstrate the problem with more concrete types:

```ts
interface Test<G extends { [key: string]: any }> {
  x: keyof G;
}

// Legal initialization of 'x' per definition of 'Test'
const x: Test<{ a: string, b: string }> = { x: "b" };

// Alleged: That this should be allowed because { a: string, b: string } is assignable to { a: string }
const y: Test<{ a: string }> = x;

// Unsound: Value "b" inhabits binding of type "a";
const prop: "a" = y.x;
```

**Comment by ShacharHarshuv** [comment]
I don't understand you answer. First I don't understand what "contravariant" means in this case. Secondly, your example does not contradict my case: 
* I did not suggest that `Test<{a: string, b: string}>` should be assignable to `Test<{a: string}>` because `'a' | 'b'` is not assignable to `a`. 
* I did suggest that `Test<{a: string, b: string}>` should be assignable to Test<{[key in string]: string}> because `'a' | 'b'` is assignable to `string`. 

The problem rises only when using the generic type `{[key in string]: string}`. I expect the `keyof` that type to be string, thus every string should be assignable to it.

**Comment by ShacharHarshuv** [comment]
**Update**: I found a workaround: 
```ts
interface Test<G extends {[key in GKey]: any}, GKey extends keyof any = keyof G> {
  x: GKey;
}

declare const x: Test<{x: number}>;
const y: Test<{ [key: string]: any }> = x; // no error!
```
