### ISSUE TITLE
Different inference for for literals passed to generic methods

### ISSUE THREAD

**Issue by mpawelski** [microsoft/TypeScript#41596]
**TypeScript Version:**  4.0.3  and nightly 4.2.0 

**Code**

```ts
interface EventBusEventsMap {
    "payload-foo": {
        foo: number;
    };
    "payload-bar": {
        bar: string
    };
}

type EventBusCallback<T> = (eventArgs: T) => void;
type EventBusSubscription = { unsubscribe: () => void }

declare function publishFun<T extends keyof EventBusEventsMap>(eventType: T, arg: EventBusEventsMap[T]): void;
declare function subscribeFun<T extends keyof EventBusEventsMap>(eventType: T, callback: EventBusCallback<EventBusEventsMap[T]>): EventBusSubscription

var d1 = publishFun("payload-foo", { foo: 1 });
var d2 = publishFun("payload-foo", { bar: "b" }); //error, good
var s = subscribeFun("payload-bar", a => { console.log(a.bar) });


//Same functions written as methods of generic class:
declare class EventBusBad<T extends keyof EventBusEventsMap> {
    publish(eventType: T, arg: EventBusEventsMap[T]): void
    subscribe(eventType: T, callback: EventBusCallback<EventBusEventsMap[T]>): EventBusSubscription;    
}
const eventBusBad = new EventBusBad();

//Expected: I should get the same inference as in functions above and get errors for invalid code and no error for valid code.
//But the type for methods parameters is inferred as union of literal string types instead of one string type like for functions above.
var d1 = eventBusBad.publish("payload-foo", { foo: 1 });
var d1 = eventBusBad.publish("payload-foo", { bar: "b" }); //no error, bad
var s1 = eventBusBad.subscribe("payload-bar", a => { console.log(a.bar) }); //error, bad. error TS2339: Property 'bar' does not exist on type '{ foo: number; } | { bar: string; }'.

//Workaround:
declare class EventBusGoodWorkaround<TKey extends keyof EventBusEventsMap> {
    subscribe<T extends TKey>(eventType: T, callback: EventBusCallback<EventBusEventsMap[T]>): EventBusSubscription;
    publish<T extends TKey>(eventType: T, arg: EventBusEventsMap[T]): void;
}

const eventBusGood = new EventBusGoodWorkaround();

var d1 = eventBusGood.publish("payload-foo", { foo: 1 });
var d1 = eventBusGood.publish("payload-foo", { bar: "b" }); //error, good
var s1 = eventBusGood.subscribe("payload-bar", a => { console.log(a.bar) });

//But this workaround makes class meber types incompatible with methods parameters.
//Here is real word example from my code base:

/**
 * Simple EventBus based on https://github.com/PierfrancescoSoffritti/light-event-bus.js/blob/1b0d2b8/src/EventBus.js but written in Typescript.
 */
class EventBus<TKey extends keyof EventBusEventsMap> {
    private subscriptions = new Map<string, Map<symbol, EventBusCallback<EventBusEventsMap[TKey]>>>();
    
    public subscribe<T extends TKey>(eventType: T, callback: EventBusCallback<EventBusEventsMap[T]>): EventBusSubscription {
        const id = Symbol('id');

        if (!this.subscriptions.has(eventType)) {
            this.subscriptions.set(eventType, new Map<symbol, EventBusCallback<EventBusEventsMap[TKey]>>());
        }
        let subscriptionsForEvent = this.subscriptions.get(eventType)!;
        subscriptionsForEvent.set(id, callback as any); //ugh..., ugly "as any" workaround for Typescript.
        return {
            unsubscribe: () => {
                let subscriptionsForEvent = this.subscriptions.get(eventType);
                if (subscriptionsForEvent) {
                    subscriptionsForEvent.delete(id);
                    if (subscriptionsForEvent.size === 0) {
                        this.subscriptions.delete(eventType);
                    }
                }
            },
        };
    }

    public publish(eventType: TKey, arg: EventBusEventsMap[TKey]): void {
        let subscriptionsForEvent = this.subscriptions.get(eventType);
        if (!subscriptionsForEvent) {
            return;
        }
        subscriptionsForEvent.forEach(subscribedCallback => {
            subscribedCallback(arg);
        });
    };
}

const eventBus = new EventBus();

var d1 = eventBus.publish("payload-foo", { foo: 1 });

var s1 = eventBus.subscribe("payload-bar", a => { console.log(a.bar) });
```

**Expected behavior:**
Inference of methods should work the same as inference for functions. There is the same constraint (`extends keyof EventBusEventsMap`) just in different "place" (class's generic type parameter vs  method's generic type parameter)

**Actual behavior:**
Different inference. Workaround is possible but breaks type compatibility witch class's fields that use class's type parameter.

**Playground Link:** [playground](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/JYOwLgpgTgZghgYwgAgKIDcLgEIFcDOGWY+AsnAA7IDeAUMg8gEQVwCeANgPZwAmAtDC5cmALhr1GUoV3EhcAWwBG0ANySGAX3VSW7bn35K4UMRKlTjUcfjBRQAcw3JttTbVpg2FFERwEAYTgODmMEAGsAHgAVAD5kAF5kAAoITHAAQSgHfHFogEpE+PQuYF51Lx80dLA8fABlXCV8BHsKMGAuEESaZFwQfCaW+xVxZMKE4tLeFw9eCAQOExQYfoQOruQKJo5gfAALADF+mOQIAA9IEF58ZHCINi4YauI6vxJyCljUmujvCDyABpkCYHOJ3m8amRKABtaIAXXy4hKZXU80Wy2QqxA6063UGzVawBUxxApwuVxudweTxe-kIUM+3zSxD+PiByAQwVCiHC4JqdSCITCUQhBHe0IocPhsSRdNqBEahLaGxAHnQJmQvAAjD1tkpdgdSck9JweAIZExgdQscJxLrNPl1BqoFqAEx6nZ7I79E2sM2GS3W5BWcRMJRMFxO5AAehj0CgXCgwIcwl4tBdyFuSQJw2JEGNpoMAisVpBRV6CC6+C4HAgADpuA5knB61ZCo71B44-U4AoVmtVbcAO72MBXEG3ftgfZcKm0hxYaDABCcpb4XK0dFLKAoDEb+V1bB8cmXLBU+6PZ5ihnESXxOhSfWG-Y-Vn-Dmg-mvcWM2EIuUUXTKRcyJFQ33ANkAWQaJgS5YVeW-ekhR5CJIhvCVPmlWUkIVBohiJdo8VUKQ3FoKsBjAM4BQIY8ZiSEAIGHQ9aL4cYuzjVBzh8dYIF4cQAEks1nXAOBmRcqJnFB8D7FBQBgaAsCQSdkFALFBzxW44CULhMBBa5kAks4oETKBbiEV1QA1XYZireZ9JmEAuGM0zbVdayyk5OcG1oOM8Ek-YUEqFYk2QadZypVgoFkyAzNU255ITPiVP6PFkFpXZYuCLM7EcZBgoSyiID4dLni6aTcpABx8v+ZBdnuNz1JxIcQR0zB6wzTUdR6Fl6To+tn29P19HNQRhDLG0ZHtKNnS63Ukl6vD+sGg5hoDC1xuDUNmAjGbYxjJyXKTYFjHTTN8Hm6if3wfrQJGCA1uLIwTDLOAKxtCiazrRsuGbVt2z2uME2OkM+HrI7XWieo3QAZhhgBOcQAAVEx8KAvGQAByKxMa1LgIFuJyqIuPYqM2YKscmu1kHkZQ1BcZAAB9em22x7CqkjNExjrfJjAB1JNwhMLh+n4rcFh3Pd11uG8AHE0wFqAhcTUWYgAaQeM4z2uW5L1pDC-y+cxGDu-NT0pW5og1thmV+D8YLg7kRVwwUnd5dCaNvcBJWwuUbyVPMiK6HRGBW-ZzfPS3rdt992QdkFshd387ywgDkWmdR3HI6tic9+W5x6RjmLlhXBeF0X2PVOaerztMBq9Vai1GoNeim5AHSdTrXW6hba7neuDSGpvA02lmTDDXbO324Hk0MtMu6zS7FrqfPeHrU3wOHksXuBN7JkratawbJsWzbEwO073n-Py-Y9mQYcy5VgyFDge5bn3KcIBUV0CtUnEuAUKwDoBoUDDmADOMKEAZxzluFFGK0B8AdTjAACUUvFZAu5soPygDMC4fYKB1ixImBQYU2BeXssYfAAJuwACoaH0BocgeowBAGEJvKDKhMxNj7HHBQXIcYHDgP2E0esVYFAxiRsAaAMBoo4gJlWeoTwZHgI6DGXYDgeH8EWkYAg9YABW+AYwGi4EoGM2olAAAZeBuiUAADhjPgKACAYw3n0bcJQuAqKjhUVgP+MF-iBzAB1ZANCYzkWlixfA6tNYUkjtSK8kTMKUAfM4Cg9gNSQCzARFUmlC5MWQJ8SIbNHDAkKfgNgyhazAhvChEUHtrpJKlFbB4MpYjfE7qRJ8XpVwbwgBHHWMFo4QTAFBDk8FUJ8kibU92BsU7-hlH7T2AdCKqmNhYLylFVL0SYRUnSHBkiYzKJjS+6yGDAGeMkAAhDOPY69snACDgMes+w4D4GGVBfIhRHynKkDcxBptHn-Kge8-4wIi4FMoEU3ZVSpluzQrM72qdratPGB0057gfl1iogCochwkzvB6H8u5yoHlDnrBJEFPh8iXJDusnFmk8VQHeOvYFZRHYIQiCpOAIA2DRjjLgDR9YhXAgFRwMhTBXn6TYJGbBysRYGQsv4nwgTgmnN3GAXAUBujfJ+QwfovSxgTBSbq05WKskksBYyglSQiX0urOS4Fi0Pm0pNYwc5KQ7UDCtTUL5zhXUWE9fgb1xB6zzCxQ9MoaL-XrPdckQNwbwDr2AAALxQAkdNyALG+uja6219zAWhogOGylEAo05sYBi8tlaTWaEBH6itLqs5dMHquMOJa8jW13onRJhs4TIsAtMNZFgzXxvxTUQlt9-n5rJRSp1-wy1SFjZc0dTKfVDp+eqzVIAXVSGrQG6dDKx0hosqgRAr5em8GmZy-eOrdUXqveEFs2QF0VrLa4LOn1c7XTycXT2lcF49yuvSAeL5HrN1HlTWQ7cZpV1dBdGu11iV5k3v6J6pZd7vQ2V9Y+v1T4A07EAA)

**Comment by MartinJohns** [comment]
Your class is written fundamentally different.

> const eventBusBad = new EventBusBad();

You did not specify the type parameter `T`, so it falls back to `keyof EventBusEventsMap`. Now take a look at your `public` and `subscribe` methods: They both take a first parameter of type `T`. You wrongly assume that it's `"payload-foo"` for the first method, and `"payload-bar"` for the second method. But in both case it's simply `T`, which is `keyof EventBusEventsMap`, which resolves to the union type `"payload-bar" | "payload-foo"`.  
This is why your code behaves so differently.

Remove the type argument `T` at class level and move it to the methods.

**Comment by mpawelski** [comment]
After second look here is simplified code that shows what I want to achieve ([playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBACghiANgezgEwLJzFAvFAbwCgpSoAiAM2WXIC5CprkBBAJwHMGA7AVwFsARhDZQAviTLlBcNvUYAhWey5QAzsDYBLbh3FEJRUJCgBhOIkQyAxgGsAPABUAfHigAKWascBKPK4A3ZC00AG4iImtEODU1KEcIDVNo2KcAaQgQKAgAD2AIbjQ420zkSlgEFHQsMGdiMigwbQC4fKhrCys4OwZzSxsHeCRUTGwAbUcMkABdV3x3P1xXAnFwyVJ+CGAAC2Q0AEZ3YAZJzIAaKC8+rp6zToH7IarRsAmp2b96hrIdrTUAOg6-W6tjcV3uINCUAA9ND9nB-lBtiJoABJKBoZDcADkwCgHC22TYbGQomEHV4amgxkSlzY0GsyH4YFaWkEiAg630XM2Oz2ACYnNk8gUivEps4jicLuDgbdrg8niMahMPoQuQ1YVB+YIkSi6dACXiRCSyRAKVSoDS4rJoDpGczWezoOS4JToGUmLxuNZgFose1kC1tHAfdB3OijUTTVAsYgsgB3LQ7KAAWlTGm0voAYt7ff7uI5wIkfBqfts-oCIXYwZwFZCoFyJIZg1a3NwIAn4olgMkYmoFuFYfyEVAABL6yOEk2kqCu92XKB-WPlGmXBgrZgqHgCYRsKFiKAAH0Uyk4DEzOg4B6M-15uwO7ioNHIMv8jEZ3DUyA5-xQHE8f4t04PwxFLYdBERCd6SgdFMW4UI8WRY1iVnedLTgJc4iaZBIDYeMrWLNArWQOdoDgDcmBobcoD4IQRBvYA7y2B9+SfZhX0XJYPyxb9f3-QDgI4UCfCAA)):
```ts
type PayloadMap = {
    "foo": { fooArg: number }
    "bar": { BarArg: string }
}

type Callback<T> = (arg: T) => void;

class TestClass<TKey extends keyof PayloadMap>{
    private callback: Callback<PayloadMap[TKey]> = () => { };

    method1(t: TKey, argCallback: Callback<PayloadMap[TKey]>) {
        this.callback = argCallback; //1a. here I don't get error because types are compatible
    }

    method2<T extends TKey>(t: T, argCallback: Callback<PayloadMap[T]>) {
        // 2b here are get error because types are incompatible because of function covariance (I get error only with --strictFunctionTypes)
        this.callback = argCallback; 
    }
}

var t = new TestClass();
//2a. Here I get error because a is of type a: { fooArg: number; } | { BarArg: string; }
t.method1("foo", a => { console.log(a.fooArg) })
//2b. Here I don't get error because a is properly typed to be a: { fooArg: number; }
t.method2("foo", a => { console.log(a.fooArg) })
```

And the "problem" is that because I use  `--strictFunctionTypes` I get error where it says `..  Type 'TKey' is not assignable to type 'T'. 'TKey' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '"foo" | "bar"'. ...`.

Well... I actually don't know If there is any better way to type what I want to achieve. You either get error at call site of a method or in class implementation. I really wanted to achieve this "stringly typed" API that I see [in](https://github.com/microsoft/TypeScript/blob/9ff24b6/lib/lib.dom.d.ts#L4806) [DOM](https://github.com/microsoft/TypeScript/blob/9ff24b6/lib/lib.dom.d.ts#L4880) but I guess having it properly typed only for consumer (and have some `any`s in implementation) is not a big deal)

**Comment by RyanCavanaugh** [comment]
@mpawelski I'm not clear on how this is supposed to work. If you actually try to *call* `this.callback` with any concrete arguments, it's easy to see how you could induce an unsoundness in that class since `TKey` can always be instantiated with `"foo" | "bar"` and there's nothing keeping track of which flavor is currently in `this.callback`.
