### ISSUE TITLE
"extends" naming issue in type constraints

### ISSUE THREAD

**Issue by mvasin** [microsoft/TypeScript#41598]
## Search Terms

extends type constraint

## Suggestion

First of all, disclaimer: it's a nitpick. But I'm curious if it's just me who's bothered.

I see a naming issue with using `extends` in type constraints:

```ts
interface Foo<T extends string> {
  something: T
}
```

In my mental model, `T` does not "extends" a `string`, but quite the opposite - narrows it:

```ts
# 'hello' and 'world' are subsets of a string
type Bar = Foo<'hello' | 'world'>

# this is an error, I cannot "extend" a string with a boolean!
type Bar = Foo<string | boolean>
```

The `extends` keyword perfectly describes what happens when an interface extends another interface

```ts
interface Narrow {
  abc: string
}

interface Wide extends Narrow {
  xyz: number
}
```

But it's not what's happening in type constraints unless my mental model is vastly off (if so, an explanation is greatly appreciated).

I propose to deprecate `extends` and introduce `narrows` for type constraints.

I don't insist on `narrows`, it can be any other antonym of `extends`.

## Use Cases

It will be used everywhere `extends` is currently used in type constraints, instead of `extends`.

The advantage is less confusion for the developers new to the language.
The shortcoming is an extra keyword to remember, because `extends` has to stay around to avoid a breaking change.

## Examples

```ts
interface Foo<T narrows string> {
  something: T
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

especially this non-goal from the Design Goals:

> Introduce behaviour that is likely to surprise users.

**Comment by AlCalzone** [comment]
> I propose to deprecate `extends`

I don't think that is ever going to happen. 

I've built my mental model like this: `extends` on an interface or type makes the resulting interface/type **more specific** by adding additional properties.
The same is true for unions. `T extends string` means `T` must be **at least as specific** as `string`. `'hello' | 'world'` is more specific, so that works. `string | boolean` is less specific, so it is not accepted.

**Comment by mvasin** [comment]
I share your mental model, but that does not explain how the word "extends" fit into it. It just confirms that a word with an exactly opposite meaning should be used.

Renaming is a churn for sure, but I believe the confusion is more expensive.

For now, I just replace "extends" with "narrows" every time I read code, but it's a bit insane.

**Comment by MartinJohns** [comment]
When you create an issue you get a template. This template, which you deleted / ignored, contains a checklist, with the following point:

> [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code

Your suggestion would violate this point, with no reason other than that the wording does not map to your mental model and your language understanding.

**Comment by mvasin** [comment]
Hey @MartinJohns, thanks for joining the conversation.

> This template, which you deleted / ignored
I found it irrelevant indeed. Let me see if I can bring it back, I don't want to come across as ignorant here. :)

> [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
We can keep `extends` around but omit it from the documentation. It doesn't have to be a breaking change.

> Think of it as "the minimum the type must provide"
I do. But a minimum of something (a subset) cannot "extend" with itself its superset. Hence I think the word is misplaced (but would be happy to be proved wrong). I can deal with confusion personally, but my proposal is to ease life for other developers.

> "foo" does extend string
I don't understand how `'foo'` can extend a string; I don't understand how a subset can enlarge/extend/enrich a superset.

**Comment by MartinJohns** [comment]
> I found it irrelevant indeed.

You have a feature request. The template helps the TypeScript team to get a quick overview, it saves them time.

> We can keep `extends` around but omit it from the documentation. It doesn't have to be a breaking change.

Then you still have additional syntax to maintain and support, with no real benefit (IMO). Removing it from the documentation would just lead to confusion when people find the keyword, and it's not mentioned.

> I don't understand how 'foo' can extend a string; I don't understand how a subset can enlarge/extend/enrich a superset.

The same way that `{ a: string; b: string }` extends `{ a: string }`. Everything that the latter type says it provides is present in the first type. Everything that `string` provides is present in `"foo"`. This is the reason why you can assign a variable typed `"foo"` to a variable typed `string`.

> But a minimum of something (a subset) cannot "extend" with itself its superset.

Perhaps think of it in the OOP way. `"foo"` is the derived, `string` is the base. Not every `string` is a `"foo"`, but every `"foo"` is a `string`.

**Comment by mvasin** [comment]
Brilliant explanation, @MartinJohns! Thinking in terms of assignability instead of subset/superset helps indeed.

**Comment by RyanCavanaugh** [comment]
This is the same confusion that leads people to think that we named "union" and "intersection" backwards; see https://stackoverflow.com/questions/38855908/naming-of-typescripts-union-and-intersection-types

A type `extends` another if it has a domain with ***more** specificity* than the domain of the type it extends. You can either think in terms of the number of constituents in the domain (which shrinks as the types get more specific), or the number of ascertainable properties of the constituents in the domain (which grows as the types get more specific). These things are always inversely correlated so any given naming convention will always have one facet or the other "backwards".
