### ISSUE TITLE
Generated lib*.d.ts files differ from the files in TypeScript SDK

### ISSUE THREAD

**Issue by deniskovalchuk** [microsoft/TypeScript#41597]
**TypeScript Version:**  at least 3.9.7 and 4.0.5

The `lib/lib*.d.ts` and `built/local/lib*.d.ts` files contain mixed line breaks (LF/CRLF) and differ from the files in the TypeScript SDK, which contain only LF.

**Steps to reproduce**

Build `LKG` or `local` on any operating system.

```
git clone --config core.autocrlf=input https://github.com/microsoft/TypeScript.git
cd TypeScript
npm ci
gulp LKG
```

**Expected behavior:**

Consistent line breaks in `lib*.d.ts` files and no differences from the TypeScript SDK.

**Actual behavior:**

Mixed line breaks.

![actual-line-breaks](https://user-images.githubusercontent.com/15797194/99663552-d9e3ec80-2a77-11eb-9770-0ddf79876f78.png)

**Comment by jakebailey** [comment]
Post #51387, this one is definitely fixed as the problem here was the way we combined things with gulp (among other things). In the new build, the entirely of `built` and `lib` now consistently use `LF` line endings.

**Comment by deniskovalchuk** [comment]
@jakebailey, I've tested TypeScript 5.1.6 and can confirm that the problem is fixed. Thank you!
