### ISSUE TITLE
Declarations cannot be generated for type aliases with type parameters

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4159]
In the latest version from master (bb3fb7d98b4ac4cd62474dde15c226b26af30b5f) the following code doesn't compile with the `--declaration` flag:

```
// test.ts
export type A<a> = { value: a };
```

```
node tsc.js --module commonjs --declaration test.ts 
```

```
test.ts(1,29): error TS4081: Exported type alias 'A' has or is using private name 'a'.
```

**Comment by danquirk** [comment]
Was this a regression?

**Comment by mhegazy** [comment]
that is a new feature added to type aliases in 1.6. so not a regression.

**Comment by mhegazy** [comment]
should be fixed by #4202

**Comment by mhegazy** [comment]
Can you give `typescript@next` a try some time after 11:50 pm PST :)

**Comment by aleksey-bykov** [comment]
Works like a charm, well done.

**Comment by mhegazy** [comment]
thanks @aleksey-bykov for the verification!
