### ISSUE TITLE
Generated javascript is leaking arguments when extending other classes.

### ISSUE THREAD

**Issue by mientjan** [Microsoft/TypeScript#4160]
When typescript generates its javascript with classes not defining a constructor for example with.

```ts
class Foo {}
class Bar extends Foo {}
```

Typescript generates

```js
var Foo = (function () {
    function Foo() {
    }
    return Foo;
})();
var Bar = (function (_super) {
    __extends(Bar, _super);
    function Bar() {
        _super.apply(this, arguments);
    }
    return Bar;
})(Foo);
```

But as you can see its leaking the arguments object to another function which is by all accounts a no go. https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments

I don't know if this is also the case with other javascript engines.

### Suggestion

Why can't we do the same with arguments as rest arguments

```js
var Foo = (function () {
    function Foo() {
    }
    return Foo;
})();
var Bar = (function (_super) {
    __extends(Bar, _super);
    function Bar() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i - 0] = arguments[_i];
        } 
        _super.apply(this, args);
    }
    return Bar;
})(Foo);
```

**Comment by SaschaNaz** [comment]
The document says *"STRICTLY `x.apply(y, arguments)` is ok"*, and current `_super.apply(this, arguments)` is just okay then.

**Comment by mhegazy** [comment]
the `arguments` object never leaks. its contents are what is passed to the super call, and not the array itself. this is Function.apply, and not Function.call.


```js
var args_a;
var args_b;

function a() { 
    args_a = arguments;
    b.apply(this, arguments);
}
function b() { 
    args_b = arguments;
}

a(1);

console.log("a: " + JSON.stringify(args_a));
console.log("b: " + JSON.stringify(args_b));

console.log("equal: " + (args_a === args_b));
```

**Comment by mhegazy** [comment]
Looks like the original issue has been answered. please reactivate if you are running into other issues.
