### ISSUE TITLE
Property error on recursive type definition

### ISSUE THREAD

**Issue by jost-s** [microsoft/TypeScript#41608]
**TypeScript Version:**  4.0.5

**Search Terms:**
recursive type definition
property error

**Expected behavior:**
`filter.and.push(...)` is correct syntax

**Actual behavior:**
`filter.and.push(...)` gives a property error

**Related Issues:**
no, the ones I found rather are to do with circularity issues

**Code**
```ts
type FilterOptions = { or: FilterOptions[] } | { and: FilterOptions[] };

interface QueryOptions {
  filter: FilterOptions;
}

const queryOptions: QueryOptions = { filter: { and: [] }};
queryOptions.filter.and.push({ role: 'manager' });
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const queryOptions = { filter: { and: [] } };
queryOptions.filter.and.push({ role: 'manager' });

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYglgG2BATgeTMOB7AdgZygF4oBvKbFALlkWXUxwIG0BdKAXygB8yoBDXABMa8JKgxY8+NpwDcAKAVxc9AGb8AxtACKAV1QhJTQqQVQoauqlHWGUgoo5LN04FACOBlEcbSa+obG0sR8VuLUfIIiULIcHIpeQX4EAHTh9KnRqWB6+AAWABTkKNgIEDQA5AC2gvwA5qiVnACUckA)

**Comment by MartinJohns** [comment]
This has nothing to do with recursive type definitions. The type of `queryOptions.filter` is `FilterOptions`. This is a union type, and you can only access properties shared across all types. `and` is not present in all of your types, so you can't access it.

You need to narrow your type first, you can do this by writing a custom type-guard.

**Comment by jost-s** [comment]
@MartinJohns Thank you for the clarification, I understand.
