### ISSUE TITLE
Type narrowing fails for property access when using comma operator

### ISSUE THREAD

**Issue by dummdidumm** [microsoft/TypeScript#41625]
**TypeScript Version:**  4.2.0-dev.20201121
**Search Terms:** comma operator flow narrow type function property access

I encountered a case where type narrowing fails when using the comma operator and accessing a property of the last operator in the chain afterwards. It does narrow the type correctly when using the value directly, but when using that value with a comma operator it does not.

**Code**

```ts
const otherValue = () => true;
const value : {inner: number | string} = null as any;

function isNumber(obj: any): obj is number {
    return true; // method implementation irrelevant
}

if (typeof (otherValue(), value).inner === 'number') {
    const a = value.inner; // number
    const b = (otherValue(), value).inner; // string | number , but should be number
}

if (isNumber((otherValue(), value).inner)) {
    const a = value.inner; // number
    const b = (otherValue(), value).inner; // string | number , but should be number
}
```

**Expected behavior:**
I would expect the second case (variable `b`) to also narrow down the type to `number`

**Actual behavior:**
Type is `string | number`, it was not narrowed.

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.2.0-dev.20201121#code/MYewdgzgLgBCUAsCmAnAagQwDYFckwF4YAKASkID4YoU8BuAWAChRJYA3bPGALhgG8AlmDCo+YHAFsARqhgAfGNBTCA5gF9CMCViwwMEfWACejJswBmOMMCiDwMQRAByU2SmIhpAKz4YTpHxe3o6GEjJy-MwwMTAoSFA4KGDUtEh0MAD0mTCSCQggACaOkgAOWEh5YFAYdg6CKPEVnNXM6szMghYkUMalSCDdnoiomLhIZAA0MJzjpAB0wqIohAREAOTh7uvkUUyxMKzQ+lqzeIsiqBnZ2m6o0bFHsNJaw8joXBOk02dIC0tXLI5ZRqBS3CIrabSHCwCAFHBYYqycHuNodJhdEhOVwQ4hvUafKYzT7-S4oUi7B4xJ4nIi-C7La45Lb3faPcDHF5EfEfcZE36kxlApQ0UGKFmQmDQ2HwxFS-AStFMIA

**Related Issues:** 
#41183

**Comment by andrewbranch** [comment]
I'm not sure whether #41991 was intended to handle this or not. We don’t track all possible control flow constructs because it’s expensive. @weswigham can you confirm?

**Comment by weswigham** [comment]
In this case, I think it's probably just an unhandled case when we recur on property accesses.
