### ISSUE TITLE
Variables are not exported properlly when using ES6 Modules with default export and targetting SystemJS.

### ISSUE THREAD

**Issue by majo44** [Microsoft/TypeScript#4162]
There is problem when I try to re export some module imported from export default.

Link to gist: https://gist.github.com/majo44/4d84feac30ad5a803658
Link to working example (copied compiled code): https://jsfiddle.net/fjfppk0z/

**Comment by vladima** [comment]
that is fair, Babel emits rexports for imported names as a part of `execute`
