### ISSUE TITLE
FileReader.onLoad/onLoadEnd event argument has no target.result property

### ISSUE THREAD

**Issue by oriondean** [Microsoft/TypeScript#4163]
Trying to retrieve the result of a read file/blob via the event passed into the reader's onload/onloadend method results in a type error (Property 'result' does not exist on type 'EventTarget').

This is valid JavaScript, which is failing type checking because the EventTarget interface does not have a result property.

Examples:
- [Typescript playground example](http://www.typescriptlang.org/Playground#src=var%20reader%3A%20FileReader%20%3D%20new%20FileReader%28%29%3B%0D%0A%0D%0Areader.onload%20%3D%20function%28event%3A%20ProgressEvent%29%20%7B%09%20%20%20%20%0D%0A%20%20%20%20alert%28event.target.result%29%3B%0D%0A%7D%0D%0A%0D%0Areader.readAsText%28new%20Blob%28%5B%22hello%22%2C%20%22world%22%5D%29%29%3B) - Clicking the run button should show an alert with the file data
- [Jsfiddle example](http://jsfiddle.net/sdz09aob/)

Workaround: Retrieve the result from the reader object (FileReader.result)

**Comment by mhegazy** [comment]
looks related to #299.

**Comment by mhegazy** [comment]
PRs welcomed. here is some infromation on contributing lib.d.ts changes: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by JasonGoemaat** [comment]
This is used in other cases also such as IndexedDB onsuccess event.

**Comment by zhengbli** [comment]
Should be covered by https://github.com/Microsoft/TSJS-lib-generator/pull/207

**Comment by victorprocure** [comment]
My solution, until this all fixed up, has been just adding a union to the Event callback:

    const reader = new FileReader();
    reader.onload = (e: Event & { target: { result: string } }) => { ... }

It's gross, but does the trick. The better way would probably be something like [this](https://stackoverflow.com/a/35790786/892415) as it is way more complete and abstracts out the types, rather than inlining them.

**Comment by LouisWayne** [comment]
Instead of using `event.target.result`, you can just use `FileReader.result`.

For example,


    const fileReader: FileReader = new FileReader();
    
    fileReader.onload = (event: Event) => {
       event.target.result; // This is invalid
       fileReader.result; // This is valid
    };

**Comment by BernardoMB** [comment]
This does not work when running the app in Electron 5.5.1

**Comment by anouarcharif** [comment]
Hello,

I have the some problem, but only when my angular project is build for production ... what could be the issue ?

**Comment by charlesr1971** [comment]
I have the same problem after I have done ng build --prod. Something happens during the conversion from 'ts' to 'js'...

**Comment by TonnTamerlan** [comment]
const fileReader = new FileReader();

fileReader.onload = (event: Event) => {
      this.result; // This works
};

**Comment by charlesr1971** [comment]
This is how I solved it, in production:

let FileReader: new() => FileReader = ((window as any).FileReader as any).__zone_symbol__OriginalDelegate
let reader = new FileReader();

Based on this StackOverflow post:

https://stackoverflow.com/questions/45542462/angular-4-x-cordova-filereader-fails-silently-white-screen-of-death/45542463?noredirect=1#comment88157606_45542463

**Comment by mattiLeBlanc** [comment]
How about this:
```

export interface IDBEventTarget extends EventTarget {
  result: IDBDatabase;
}
export interface IDBEvent extends IDBVersionChangeEvent {
  target: IDBEventTarget;
}

...
request.onupgradeneeded = ( e: IDBEvent ) => {
      this.db = e.target.result;
});

```

**Comment by thesuraj** [comment]
> ```
> const fileReader = new FileReader();
> fileReader.onload = (event: Event) => {
>       this.result; // This works
> };
> ```


```
const fileReader = new FileReader();
fileReader.onload = function(event: Event) {
      this.result; // This works 

     /*
      Even the below one works as suggested by @LouisWayne  
     */
      fileReader.result // even this works  
};
```

Using arrow function won't give the expected result with (this.result).

**Comment by thesuraj** [comment]
> ```
> const fileReader = new FileReader();
> fileReader.onload = (event: Event) => {
>       this.result; // This works
> };
> ```

using **this** with arrow function will not give the expected result. 

```
const fileReader = new FileReader();
fileReader.onload = function(event: Event) => {
      this.result;              // This works
      fileReader.result;    // Even this works - by @LouisWayne  
};
```
