### ISSUE TITLE
JSDoc for Callbacks

### ISSUE THREAD

**Issue by shadowtime2000** [microsoft/TypeScript#41639]
## Search Terms

jsdoc, callbacks

## Suggestion

I would like to be able to easily specify types for callbacks with JSDoc.

## Use Cases

This could be used for callbacks on functions.

## Examples

```ts
myArray.map((elem /* @type {string} */) => {
  doSomethingWithElem(elem);
});
```

```ts
const myArray /* @type {string[]} */ = ["foo", "bar"];
```

## Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ExE-Boss** [comment]
JSDoc comments have to come before what you’re typing, so the correct way to write that is:
```js
myArray.map((/** @type {string} */ elem) => {
	doSomethingWithElem(elem);
});
```
```js
/** @type {string[]} */
const myArray = ["foo", "bar"];
```
