### ISSUE TITLE
Deprecate const enum

### ISSUE THREAD

**Issue by pauldraper** [microsoft/TypeScript#41641]
## Search Terms

const enum, performance

## Suggestion

Deprecate the misfeature `const enum`.

The behavior of `const enum` is uniquely problematic for tooling, as -- unlike virtually every other feature -- it doesn't work with isolatedModules.

And even if  optimizing user code were a goal (it's an explicit non-goal), *claims that it improves performance lack evidence.*

### Violates usual tooling behavior

[Const enums](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums) cause enormous pain to the ecosystem (for example, [3+ year old](https://github.com/babel/babel/issues/8741) lack of support by babel, plus all the linked issues).

### Fact check: Doesn't reliably improve performance

I searched for hours for the performance tests that justified this problematic behavior. Nothing. Just some unsubstantiated speculation in #1029 .

I wrote some benchmarks, and despite selecting for favorable results, I was unable to show that they actually improved performance: https://github.com/pauldraper/const-enum-perf

More precisely, they increased perf slightly in Chrome/Node.js and slowed it significantly in Firefox.

Users are being misled thinking that `const enum` optimizes their code.

I assume the bar for non-local optimizations is a lot higher than this.

### Can be fixed while staying backwards compatible

The fix is simple:

* in source code, ignore the `const` modifier
* In declarations, keep the existing inlining behavior for `const enum`.

Existing code continues to work, but becomes more portable.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] **This could be implemented without emitting different JS based on the types of the expressions**
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code

This would be a breaking change. You're changing the generated code and runtime behavior.

**Comment by xiaoxiangmoe** [comment]
This would be a breaking change. Some library use 0 1 2 as type code, and `.d.ts` file use const enum to describe it.

**Comment by pauldraper** [comment]
> This would be a breaking change. You're changing the generated code and runtime behavior.

Changing generated code is not in itself a breaking change. It's not clear to me what you think this would break. Example?

> Some library use 0 1 2 as type code, and .d.ts file use const enum to describe it.

As I outlined, `const enum` in a .d.ts would continue to work for backwards compatibility (though tsc would no longer produce `const enum` declarations).

**Comment by RyanCavanaugh** [comment]
We don't deprecate widely-used features like this.

Citing that it doesn't work with `isolatedModules` is like looking backwards through a telescope and saying that things get smaller -- we added `isolatedModules` specifically so that you could avoid using features like `const enum` in scenarios (e.g. babel) where they can't be safely transpiled. It's basically an "opt in" to deprecating the feature, which is exactly what's being proposed.

The "unsubstantiated speculation" was us finding very measurable performance gains *in 2014*; JS engines have evolved quite a bit in the interim and it's mostly unsurprising that you can't necessarily replicate these findings today. There is also going to be clear minification gains when replacing large text names with small numeric values that still persist.

**Comment by pauldraper** [comment]
> we added isolatedModules

Perhaps I should have said `ts.transpileModule`. TS is this close >-< to having a single-file compilation language. Just look at the carnage on https://github.com/babel/babel/issues/8741

> The "unsubstantiated speculation" was us finding very measurable performance gains in 2014

Citation? #1029 has nothing.

I've love to look at those benchmarks that cause so much pain.

> There is also going to be clear minification gains when replacing large text names with small numeric values that still persist.

You have to use a looooooot of const enums. Seems like a good feature for an optimizer.

**Comment by pauldraper** [comment]
Can't pass up this opportunity: https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937

> We are 100% committed to not rewriting JavaScript code as part of non-downleveling compilation. This is how everything else in TS works; see also this comment in a related feature request, and this comment in a related feature request. We are not going to implement features, even under a commandline flag, that imply changing JS semantics by rewriting it during emit

"...unless the name of the feature is `const enum` and then we will definitely rewrite it during emit."

**Comment by RyanCavanaugh** [comment]
Making past mistakes doesn't mandate us to make more of those mistakes. You can ask us at any panel which features we regret adding, and we'll all say "const enum". I'm not sure what your point is and think you could be more constructive about this.

**Comment by RyanCavanaugh** [comment]
(self comment deleted, I'm going to try to do a better job of assuming good faith)
