### ISSUE TITLE
Can't get partial from generic

### ISSUE THREAD

**Issue by VKamotin** [microsoft/TypeScript#41647]
**Code**

```ts
const partial = <T, K extends keyof T>(key: K, value: T[K]): Partial<T> => ({ [key]: value });
```

**Expected behavior:**
Compilation without errros.

**Actual behavior:**
Error: `Type '{ [x: string]: T[K]; }' is not assignable to type 'Partial<T>'.`

**Playground Link:**
[Link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201123#code/MYewdgzgLgBADgQwE5QJYIDYwLwwDwAqANDANIwCmAHlBWACYQwDWFAniAGYwEB8AFKzYAuMiQBumAK4VRBANqkAugEpRABWRpMhXjj38A3jHlCloyRhkwAvioDcQA
)

**Comment by DanielRosenwasser** [comment]
You'd need to either have some concept of a generic index signature (likely not happening) or create a mapped type when writing code like this.

**Comment by VKamotin** [comment]
Okay, thank you for that answer.
