### ISSUE TITLE
TypeScript SIMD support?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/TypeScript#4164]
Hello. In JavaScript added SIMD support. So can I use SIMD in TypeScript?

**Comment by RyanCavanaugh** [comment]
Yes.
```ts
// TODO: Someone should write a simd.d.ts and send to DefinitelyTyped
declare var SIMD: any;

// Good to go
var a = SIMD.Float32x4(1, 2, 3, 4);
```

**Comment by acterhd** [comment]
And how to I can use typed arrays?
var list: Array<SIMD.Float32x4> = [];

**Comment by RyanCavanaugh** [comment]
```ts
declare namespace SIMD {
  interface Float32x4 {
    (...args): Float32x4;
    add(args): Float32x4;
  }
  var Float32x4: Float32x4;
}
```

**Comment by acterhd** [comment]
declare namespace SIMD {
    interface Float32x4 {
        (...args): Float32x4;
        add(args): Float32x4;
        extractLane(args): Number;
    }
    var Float32x4: Float32x4;
}

var vec: SIMD.Float32x4 = SIMD.Float32x4(0.0, 0.0, 0.0, 0.0);
var list: Array<SIMD.Float32x4> = [vec];
var num: Number = SIMD.Float32x4.extractLane(vec, 0);

console.log(num);

Marked as error:
SIMD.Float32x4.extractLane(vec, 0);

**Comment by aleksey-bykov** [comment]
```typescript
declare namespace SIMD {
    interface Float32x4 {
        (...args): Float32x4;
        add(args): Float32x4;
        extractLane(...args): Number;
    }
    var Float32x4: Float32x4;
}

var vec: SIMD.Float32x4 = SIMD.Float32x4(0.0, 0.0, 0.0, 0.0);
var list: Array<SIMD.Float32x4> = [vec];
var num: Number = SIMD.Float32x4.extractLane(vec, 0);

console.log(num);
```

you need to learn some TypeScript: http://www.typescriptlang.org/Handbook

**Comment by acterhd** [comment]
I'm understand that need been two arguments. Multiple points? Thanks.

**Comment by aleksey-bykov** [comment]
```typescript
declare namespace SIMD {
    interface Float32x4 {
        (...args): Float32x4;
        add(args): Float32x4;
        extractLane(t: Float32x4, index: number): number;
    }
    var Float32x4: Float32x4;
}

var vec: SIMD.Float32x4 = SIMD.Float32x4(0.0, 0.0, 0.0, 0.0);
var list: Array<SIMD.Float32x4> = [vec];
var num: Number = SIMD.Float32x4.extractLane(vec, 0);

console.log(num);
```

If you know the **exact** set of parameters you should **not** use `...args`. In case of `extractLane` we [know](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD/extractLane) it should be `extractLane(t: Float32x4, index: number): number` which is better than `...args`, because more specific and strict.

**Comment by acterhd** [comment]
Why in typescript no float, int and other primitives? Sorry, for declare typed vars, need use:
```
var floatNumber:Float32Array = Float32Array([0.0]);
var floatSimd:Array<SIMD.Float32x4> = [SIMD.Float32x4(0.0, 0.0, 0.0, 0.0)];
```
???
