### ISSUE TITLE
Using CompletionEntry for strings when name and insertText differ?

### ISSUE THREAD

**Issue by barik** [microsoft/TypeScript#41679]
**TypeScript Version:**  4.0.3

**Search Terms:**
CompletionEntry

**Code**
We are using the TypeScript plugin model to override `getCompletionsAtPosition`, for example, as demonstrated in [Writing a Language Service](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin).

The scenario we have is a string-based embedded language (with spaces) where the `name` is different from `insertText`, but users will want to specify the completion by `name`. A representative (but abstracted) example:

```ts
const completionEntry: ts.CompletionEntry = {
                name: "color blue",
                kind: ts.ScriptElementKind.string,
                sortText: "123456",                
                insertText: "123456"
};
```

**Expected behavior:**

In the above, we'd like the developer to be able to type "color blue" but have the string "123456" inserted. Currently, we can type `123...` and the autocompletion stays but if we type "c" the autocompletion disappears:

![image](https://user-images.githubusercontent.com/441243/100166430-96bbbc00-2e71-11eb-8d7d-387895486d66.png)

Typing `insertText`:

![image](https://user-images.githubusercontent.com/441243/100166496-b652e480-2e71-11eb-9427-7014077b6222.png)

Typing `name`:

![image](https://user-images.githubusercontent.com/441243/100166512-bfdc4c80-2e71-11eb-9196-1cec2195396a.png)

**Actual behavior:**

Typing "c" will close the autocompletion. It's unclear if this is a bug, unsupported scenario (feature), or if we don't understand how to use `CompletionEntry` correctly (do I need `replacementSpan`?). It appears that there is no [`FilterText` property as in IntelliSense](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.asynccompletion.data.completionitem.filtertext?view=visualstudiosdk-2019).

@mjbvz might know.

**Playground Link:** 

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/20730 seems relevant, but it's not clear what the action is when it's a TypeScript plugin.

It may be also be related to:
https://github.com/microsoft/vscode/blob/00fa5d38843ce928d851e687a318cad75a212581/extensions/typescript-language-features/src/languageFeatures/completions.ts

**Comment by barik** [comment]
From [L83](https://github.com/microsoft/vscode/blob/00fa5d38843ce928d851e687a318cad75a212581/extensions/typescript-language-features/src/languageFeatures/completions.ts#L83), it looks like `filterText` is a function of `insertText`. In the above scenario, it looks like we would need independent control of `filterText`. Would it be possible to have an optional property of `filterText?` in `CompletionEntry` that could be bubbled up?

**Comment by andrewbranch** [comment]
It does look like `getFilterText()` has a baked-in set of assumptions that come from TS Server. I think it would be preferable if we could handle this change on the editor side without requiring a TypeScript/protocol change. In other words, this is a feature request for the TS extension in VS Code.

**Comment by barik** [comment]
That would be preferable. I still suspect we may need both, since `filterText` can be disjoint to both `name` and `insertText`.  Particularly in a "plugin" model where the editor would not know a priori what to do with the plugin's completions.

Even if we make the change solely on the TS extension side, I wonder what `Kind` could be re-used on the TypeScript protocol side to signal that `name` should be part of the filter?

**Comment by maroon1** [comment]
I would like to implement a plugin to convert some kind of complex char to alphabet string, so that i could simply input alpabet string instead of complex char. The scenario also need filterText to filter by converted alphabet string. It's a simple feature, but i have to custom a comprehensive typescript language service client.

**Comment by maroon1** [comment]
eg: input `alpha` and editor show `α` suggest
