### ISSUE TITLE
Why is there no error in this place

### ISSUE THREAD

**Issue by mytheart** [microsoft/TypeScript#41683]
![image](https://user-images.githubusercontent.com/42933010/100177866-d33cf580-2f0d-11eb-8764-300dcaed34ce.png)

**Comment by lazytype** [comment]
This is not a support forum. There are people who would be happy to answer this question on [stackoverflow](https://stackoverflow.com/)

**Comment by IllusionMH** [comment]
Duplicate of #20863 and other.
