### ISSUE TITLE
access elements of labeled tuples by the label

### ISSUE THREAD

**Issue by chrisguttandin** [microsoft/TypeScript#41681]
## Search Terms

named tuples, labeled tuples

## Suggestion

I would like to propose a new mechanism for accessing elements of labeled tuples. In my opinion this would dramatically improve the developer experience with labeled tuples.

Please consider the following example:

```ts
type Range = [start: number, end: number];

const range: Range = [2, 5];
```

Some other part of the same code base is interested in the end of that range.

```ts
const end = range[1];
```

After a while someone decides to refactor the code which defines the `Range` like this:

```ts
type Range = [start: number, length: number];

const range: Range = [2, 3];
```

It might not be obvious to that person that they broke some code somewhere else. The code which retrieves the end of the range by reading the 2nd element does no longer work. But TypeScript will not complain.

```ts
const end = range[1];
```

What if elements of labeled tuples could be referenced by the label instead of the index. In that case the original code would have looked like this:

```ts
const end = range[:end]; // the syntax could be different
```

After the refactor that code could have thrown an error because there is no element with the label `end` anymore and it would have been clear that this needs to be changed as well as part of the refactoring.

```ts
const end = range[:start] + range[:length];
```

However the JavaScript code emitted by TypeScript would still use the array indexes to access the elements of a tuple.

## Use Cases

It would be useful for any code base that uses arrays instead of objects for performance reasons. It would improve the developer experience with labeled tuples. And by making those a real alternative to key/value objects it would open the door to faster and smaller runtime code.

## Examples

It would also allow the code emitted by TypeScript to be smaller if labeled tuples become a real alternative to key/value objects.

```ts
const optionsAsObject: { height: number; width: number } = { height: 100, width: 100 };
const objectHeight = optionsAsObject.height;

const optionsAsTuple: [ height: number; width: number ] = [ 100, 100 ];
const tupleHeight = optionsAsTuple[:height];
```

The minified JS version of that code could look like this:

```ts
const a={height:100,width:100};
const b=a.height;

const c=[100,100];
const d=c[0];
```

The code which uses labeled tuples can be much smaller since the labels disappear at runtime.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] (I'm not sure about this one) This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by lazytype** [comment]
There's almost no precedent to TS introducing alternative syntax for a runtime behavior so the case for setting this precedent would have to be an unprecedentedly strong one. 
> It would also allow the code emitted by TypeScript to be smaller if labeled tuples become a real alternative to key/value objects.

I doubt this would make a meaningful difference once the minified JS is gzipped.

> In my opinion this would dramatically improve the developer experience with labeled tuples.

I think overall developer experience would be improved for code maintainers if tuples were not used where objects are better-suited. e.g.
```ts
const optionsAsTuple: [ height: number; width: number ];
const [width, height] = optionsAsTuple;  // this is an easily avoidable bug
```

**Comment by DanielRosenwasser** [comment]
This would involve type-driven emit, so it's unfortunately not in scope.

**Comment by chrisguttandin** [comment]
Hi @lazytype, hi @DanielRosenwasser, thanks for taking a look at this.

Could this maybe be implemented in a slightly different way? Instead of introducing new syntax it could be only on the type level. Let's say a labeled tuple can be used to determine the index of the given labels and the following two statements are equivalent.

```ts
type End = Range['end'];
type End = 1;
```

It would then still be possible to type check the access of labeled tuples.

```ts
const end = range[<Range['end']> 1];
```

That would throw an error if there is no label called `end` or it corresponds to a different index.

**Comment by RyanCavanaugh** [comment]
That's not really a solution in line with how things typically work - `Range['end']` already has a defined meaning.

We really want labels to just be for display purposes; if you want something that is truly a name in the type system, you can already do lots of things to accomplish these scenarios.

**Comment by lazytype** [comment]
>type End = Range['end'];

(Expanding on Ryan's point) It would be unintuitive for the type syntax to not mirror the semantics of the runtime syntax and would lead to the following ambiguous scenario:
```ts
// is ` Range['end']` going to be `1` or `string`?
type Range = [start: number, end: number] & { start: string, end: string };
```

also labels are not constrained to be unique so this is valid:
```ts
type Range = [value: number, value: number];
```
> ```ts
> const end = range[<Range['end']> 1];
>```

This already wouldn't work as you are expecting if you directly substituted `1` for `Range['end']`.
```ts
// not a type error
const end = range[<1> 0];
```

**Comment by chrisguttandin** [comment]
Thanks for the clarification @RyanCavanaugh and @lazytype. Looks like I misunderstood the intention behind adding labels to tuples.

**Comment by malthe** [comment]
I understand that type-based emit is in conflict with TypeScript Design Non-Goal #5: "TypeScript generally will not "emit different code based on the results of the type system".

Nonetheless, why weren't labels constrained to be unique?

**Comment by RyanCavanaugh** [comment]
> Nonetheless, why weren't labels constrained to be unique?

They're for display purposes, so it doesn't matter if they're unique or not. You could easily imagine places where duplicative labels are fine and desirable, e.g. `measureDistance([point, point])` or `dotProduct([vector, vector])`. Plus, labels are preserved through spread, so you'd always be able to create a tuple with duplicate labels anyway (*or* you'd be randomly blocked from creating valid tuples via a mechanism you have no way to turn off)
