### ISSUE TITLE
Cannot identify params type when define typed variables with generic arrow function

### ISSUE THREAD

**Issue by chenesan** [microsoft/TypeScript#41686]
**TypeScript Version:**  4.2.0-dev.20201124

**Search Terms:** generic arrow function, type inference, contextual type

**Code**

```ts
// Let's assume there's a compute function in another module.
function computeFn<T>(arg: T): T {
  return arg;
}

// In non-generic arrow function use case, we can declare function type and assign it to the variable
// and `arg` will be infered as number type.
export type NormalFn = (arg: number) => number;
const normalFn: NormalFn = (arg) => {
  return arg;
};

// In generic use case, we can still do this and TypeScript will infer `arg` as T.
export type GenericFn = <T>(arg: T) => T;
const genericFn: GenericFn = (arg) => {
  return arg;
}

// However, once we need the generic type in function (ex. call another generic func)
// we have to declare generic before the arrow function
// Then, the arg will be infered as `any`, which is not (I think) the expected behavior.

const genericFn2: GenericFn = <T>(arg) => { 
  // `arg` will be infered as `any`
  return computeFn<T>(arg)
}
```

**Expected behavior:**

In the third use case (`genericFn2`), the parameters should be infered as `T`, which match the variable's type.

**Actual behavior:**

TypeScript will infer parameter type as `any`.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201124#code/MYewdgzgLgBKC2AHArlApgMTDAvDAPACoA0MAfABQCGATgOYBcMhAlLmTLXQNwCwAUGgAeiEDVhQAnojQwA4mjBoaAS2BZcBQpS5NW7Zn0EixsUJFh1FytViYKlq9djxFSO+mxwcA3gJgwNGhQyDTYCCjoWEQedCwCAL4CAlaOtmAUAORUmSzcQA

**Related Issues:** 
Looks similar to https://github.com/microsoft/TypeScript/issues/25293, which is wontfix. But I'm not sure if they are the same thing actually.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; there's no mechanism that would take the type parameters from `GenericFn` and remap them onto the function signature through contextual typing - critically, even though they're both named `T`, they are *different type parameters* and there's no clear reasoning by which they should be treated as the same.

**Comment by chenesan** [comment]
Thanks for the reply :) I have some questions, though:
1. So in theory, can't contextual typing map type parameter? From a newcomer's view, the type
```typescript
type GenericFn = <T1>(arg: T1) => T1;
```
and the function, looks so similar.
```typescript
<T2>(arg) => {
  return arg;
}
```
Since they both have only one type parameter, can't we map the `T1` in `GenericFn` type onto `T2` in latter function and say arg is `T`? If we can map function parameter type during contextual typing, is it possible to map type parameter? (even though there's no such mechanism currently)

2. So how do we get the type parameter through contextual typing? I mean, when
```typescript

type GenericFn = <T>(arg: T) => T;

const fn: GenericFn = (arg) => {
  return computeFn<T>(arg); // How do we get `T` here?
}
```
I don't want to typing `arg` additionally in parens since it can be hard to read function parameter when the type is complicated. Currently the only workaround I can think of is:

```typescript
const fn: GenericFn = (arg) => {
  return computeFn<typeof arg>(arg); 
}
```

But this looks not that good as getting `T` from type parameter.
