### ISSUE TITLE
Create and expose an expression transpiler

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#4169]
As a library consumer, I would like to be able to call an API method which takes a file location and a TS string and returns a JS string.

And by that I mean a function which given an execution context and a TS string, gives equivalent JS for that location (like transpile, but context aware). 

This is useful for watch expressions and console debugging, and without something like this, it is difficult/impossible to account for all the renaming the TS compiler does in such expressions (`super`, `this`, `arguments`, default parameters, probably more).

So, an example.
With project file `foo.ts`:

``` ts
class A {
    foo(): string {
        return 'A';
    }
}

class B extends A {
    foo(): string {
/*marker*/      return 'B';
    }
}
```

calling

``` ts
ts.transpileExpression(/*marker file location*/, 'super.foo()')
```

should yield the string

``` js
'_super.prototype.foo.call(this);'
```

**Comment by RyanCavanaugh** [comment]
Could someone reasonably write this with a wrapper using `transpile` and source maps? It's likely we'd have to do almost the entire amount of work as the entire file anyway, so the perf impact of running the whole file seems minimal.

**Comment by weswigham** [comment]
@RyanCavanaugh Not... really? Certainly not easily. AFAIK it's relatively impossible to just text-edit expressions directly into some contexts (like if I wanted to execute an expression in the context of a parameter initializer). TBH what needs to happen is, once transforms is merged, calculate the transforms flags up to the desired execution context, then create a node tree for the input expression and transform it using those node flags and the active compiler options. (This is what @rbuckton had told me back when I has first asked for the feature.)

**Comment by RyanCavanaugh** [comment]
Closing due to lack of other feedback
