### ISSUE TITLE
Narrow element of `Base[]` to `Derived` using `instanceof`

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/TypeScript#41694]
**TypeScript Version:**  4.2.0-dev.20201124

**Search Terms:** narrow array to derived

**Code**

```ts
type Union = { kind: 'a'; prop: string } | { kind: 'b'; prop: number };
declare let v1: Union[];
if (v1[0].kind === 'a') {
  v1[0].prop; // Correctly narrows to `string`
}
abstract class Base {}
class Derived extends Base {
  constructor(public prop: string) {
    super();
  }
}
declare let v2: Base;
if (v2 instanceof Derived) {
  v2.prop; // Correctly narrows to `string`
}
declare let v3: any[];
if (v3[0] instanceof Derived) {
  v3[0].prop; // Correctly narrows to `string`
}
declare let v4: Base[];
if (v4[0] instanceof Derived) {
  v4[0].prop; // Error "Property 'prop' does not exist on type 'Base'", incorrect, does not narrow
}
```

**Expected behavior:**
`v4[0]` will be narrowed to `Derived` (and thus `v4[0].prop` to `string`), just like it does when there isn't an array or when using a union type or `any[]`.

**Actual behavior:**
`v4[0]` remains of type `Base`, and thus an error "Property 'prop' does not exist on type 'Base'" is emitted.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201124#code/C4TwDgpgBAqgdgSwPZygXigbygawXAEwC4oByAQ1IG4owAnJMEgZ2DvwHMoBfKAHyy58xMgCNqtBkyhwArgFtREOjyoBYAFAEIAYwA25OtD0RgUAG4BGEvGRwA2gF11GhADMoACiv2ADI4A6PEJ0NAwKUgBKLE0oC0s-QPpGGgB6VKgAYSQ6Ix1gPRAZQwYAd2YoYCQoAANWdjgOGs1uTXJRevJ8qH1yZgqAIT7oTFaNXv6oABFlBHMIAigIAA9gCEJB4ZiNOJ0Uetl8nM8wWVE9BB1JRhY2TmjMWLioZllIOk9Ilzixse1eoxQExmcwAJhIQ2YEBc7i8YKg+FY5DgOggSA8M3Y8wIDyeYICyTAaQy2VyugKRTgJSQ5Uq1Tqd0azQ0f10BkBwIsAGYSMiQE4YR5vFzEgi4EiUWiMbNsbidtzEgSpMSsjk8hTirkaRUqrV6pxmayAcZTBYACwQ4YCzSw7xm0WI4DI1Ho6YyhZyuLme3+JUpKDpKAAUS1KgARAAFKTKUBkQmkKAEJAQCpwJBmFYIVhQFCVcDQUiQiCkMMAGjFezJ+XLSZTMnTmrKLU0QA

**Related Issues:**

**Comment by MartinJohns** [comment]
Duplicate of #10530.

**Comment by ChayimFriedman2** [comment]
Thanks. It was hard to find that 😆
