### ISSUE TITLE
Playground: log statements stop showing up after async operation

### ISSUE THREAD

**Issue by Zlatkovsky** [microsoft/TypeScript#41695]
**Playground Version**: V3

**Search Terms:** "playground log"

**Code**

```ts
console.log("start");
pause(100).then(() => console.log("end"))

function pause(ms: number) {
  return new Promise(resolve =>
    setTimeout(resolve, ms));
}
```

**Expected behavior:**
Expect the words "start" to appear in the playground console, followed by "end" a moment later.

**Actual behavior:**
Only "start" appears with each run, never "end". However, the *real* DevTools console does show both being logged.

![image](https://user-images.githubusercontent.com/2230453/100295651-fc29ae80-2f3e-11eb-8849-76611c8b8fba.png)

I think having that inline console is great, but only if it is accurate! If it sometimes fails to capture what the real console does, it can be harmful. I spent probably 5-10 minutes today trying to figure out what was going on -- could I really have messed up the `pause` function?! -- before thinking of checking the real DevTools console.

**Playground Link:** 
<https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUAiCAXAhgJy3QEoBuAKAAccBXCWVARgAYmj4sALWMVVIgAgC8APn6hIMBEjTpuAE2JEyZAGbUwwLAEtw-KrXoBbCAC5+YaoYBGsPAIDeZfvzyws1PGHOwA7vwAKeCCGWnSorlDQAG6wQsJOzvx0WAAqWoawINRY4bCRMQA0-MZEpGQAvmRAA>

**Comment by Gerrit0** [comment]
Duplicate of https://github.com/microsoft/TypeScript-Website/issues/367

**Comment by Zlatkovsky** [comment]
Submitting a fix at https://github.com/microsoft/TypeScript-Website/pull/1376

**Comment by Zlatkovsky** [comment]
Since the issue is tracked in the other repo already, and since there's now a pull request in that repo, going ahead and closing this issue here.
