### ISSUE TITLE
Union of string literals is incorrectly widened in error message when compared to never

### ISSUE THREAD

**Issue by Aprillion** [microsoft/TypeScript#41707]
**TypeScript Version:**  4.1.2, 4.0.5 (worked better in 3.9.7)

**Search Terms:** "string is not assignable to type never" (all 15 issues I found look slightly different I think)

**Code**

```ts
function assertUnreachable(_: never): void {}

type ActionTypes = 'a' | 'b'

function reducer(state: {}, action: {type: ActionTypes}) {
  switch(action.type) {
    case 'a':
      return state
    default: {
      assertUnreachable(action.type) // <-- incorrect widening on this line
      return state
    }
  }
}
```

**Expected behavior:** like in 3.9.7, the error message should be `Argument of type '"b"' is not assignable to parameter of type 'never'`

**Actual behavior:** `Argument of type 'string' is not assignable to parameter of type 'never'` - which is too wide to be actually helpful :(

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.2#code/GYVwdgxgLglg9mABAQwM6oKYCcoFUxYbIQAWyARgDYYAUA+gFyJgYBu2AlE63DACaIA3gF8AUKID0ExCFTIA5hlFQAngAcMiAILR4YACrqMqRAF5EAcmQXEAH0vkL40JFgJEhPiAjYaqKMhQGEwiADQougghqhpMOm4GRqjCHEKiiIioAO4wUKQ0xAkAdDEYqYLpGYgQaJpWFgyVVR4YUCBYSP6BSs18GMDIIJRQIU1VaJg4+ITEZFS0hXolRhxjGYRtHZkBQWNiGWJiohAIqHDURZRw8jSe3r5hQqVMFo4pHEA (change the version number to see the previous error)

**Related Issues:** ?

**Comment by hyzyla** [comment]
I've found a quick workaround for this problem for anyone who has the same issue:

[Typescript Playground](https://www.typescriptlang.org/play/?ts=4.1.2#code/PTAEFUGcFNQFwBYEtKgDZLtATgQzaEgHaRa4AmoA9gGagBER0AbjvfFaNCQK7ayJccULlCQA7pgDGCMXCHQAtt2EouADwS4epJKwB0AKBCgAytFgpIPaAC5QCOHAAOkWyADmmBDwBG+qSpFYEUkKWwqSFo4YAAVAE9naFNwpGcYqxtIYAAWAEYAdgAGAsM4RNgAORYcUzhsYg8AGUwcfFAAXgYAfW7YgAkASVNu036AeXAmgBFugCEAUW7wSoAlBYBBAGF+jbmmpe76AG5DQ2h1ZypsYRoeIik4JCoiEUgYG-AiflwZXF80NAABTMfA2ezVVjYOoNIjNVp4NAASnsTChoAA3oZQPAEBFxKAmASFtgItggQADL4-P4AuygAAkGNBaBsAF8KUjTmyziYdLgPNAyhVQBtHs8iAkkqgugByXCy0AAH1Ast8ipVsqksrOdweTxeoH45B4UhwQNICnsGLZABoROKXtbykl7GKDZKKpA2UjMdixJI4DIgb8PfoXdBfVicTipLgYKqFbZ-TGjdA4HxXpasCnQORoDRtGg4NbcziTBtsB4eMoiMJaPARbL6L52Cr6FJ6Iq1EQqMJ45AkB4iP9ARxQM5cHhlFhsNQ6BHVfRegNhqMJlNZotlmtNjs9gdel2y28PnBqdBflo6SHHURwxUubmeTieTzDIESFRAfo0FQPECxqmuaNr2hiEb2Gqso+kiQA)

```typescript
// Use this literal instead of "never" to ensure that a switch statement is exhaustive.
// See issue: https://github.com/microsoft/TypeScript/issues/41707
type NeverStringLiteral = "__THIS_SHOULD_BE_UNREACHABLE__";

export function assertUnreachable(value: NeverStringLiteral): never {
  throw new Error(`Unreachable: ${value}`);
}

// usage
type ActionTypes = 'a' | 'b' | 'c'

function reducer(state: {}, action: {type: ActionTypes}) {
  switch(action.type) {
    case 'a':
      return state
    default: {
      // 🚫 Argument of type '"b" | "c"' is not assignable to parameter of type '"__THIS_SHOULD_BE_UNREACHABLE__"'
      assertUnreachable(action.type);
    }
  }
}

console.log(reducer({}, {type: 'b'}))
```
