### ISSUE TITLE
Boolean literal type preserved in reduce when used in filter

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#41702]
**TypeScript Version:**  4.2.0-dev.20201126

**Search Terms:** filter reduce inference, filter reduce literal types

**Expected behavior:** The code below compiles and `U` in reduce is inferred as `boolean`

**Actual behavior:** The code below fails to compile with the error `Type false is not assignable to type true`. `U` in reduce is inferred as `true`

**Related Issues:** None

**Code**
```ts
/// <reference no-default-lib="true"/>
interface Array<T> {
  
    filter<S extends T>(predicate: (value: T, index: number, array: T[]) => value is S, thisArg?: any): S[];
    filter(predicate: (value: T, index: number, array: T[]) => unknown, thisArg?: any): T[];
    
    reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;
    
}

[].filter(() => [].reduce(r => r && false, true)) 

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
/// <reference no-default-lib="true"/>
[].filter(() => [].reduce(r => r && false, true));

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201126#code/PQgEB4CcFMDNpgOwMbVIg9gWgCZwIYCuANgC5bECWARgLwBEpkh09wAfAFCWKkKz5UoAIKRI+AJ7gAKu1ABvTqFBLloWJTIJwAZVDQAHn0Q4AzqFkAKAA4wclZPj4AuUJYBu+Yi1fSANKA8eAauiIQAttQIAfhikr4A2gC6AJSgtHKe3miU5joBpAAWuaIA5gD8rviIEimuOskA3KrKGlqQNnYOTtCuHl4+FgFBhqERUZAxcRKJqelyhIgA1pgA7ogFxaZllaDVtbPNairHdoSo4ACq7JaOxMTUgkuwiH220O6UGISmAGoDvVAlwCyEIYmgvH+2V8ILBSFIAEkTKN0ONontprM0hkgcNEJRSJQvFDBpc6kCjmpOABfTicZIAOjafA6lmxckZZ1Qlkg81AvIAZAL1F5TNACsxoCkUpwgA)
      
The issue seems to be cause by the `filter<S extends T>` overload. Removing this overload will make the error go away. The issue does not manifest on calls to `reduce` that are not.

This problem can be reproduced outside of arrays:

```ts
function filter<S>(predicate: (value: unknown) => value is S): void
function filter(predicate: (value: unknown) => boolean): void
function filter(predicate: (value: unknown) => boolean){
}

function reduce<U>(callbackfn: (previousValue: U) => U, initialValue: U): U {
    return initialValue
}

filter(() => reduce(r => r && false, true))
```
[Playground Link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201126#code/GYVwdgxgLglg9mABMGAbKBTATgHgMoB8AFAA5YYAmMEAhpgFyJEBuNqIGj4A1mHAO5gAlIgC8BRK3YZEMAM6I8QxszgwKAKFCRYCZGkxZS5KrQZMpHLmF4DhYiQCM4cVBhrCVazdujwkKOjYxpTUdJwWbFaIPHyCIuKIzq7uwhoA3hoaAL5ZvrpIJiAQGDgAqsS0qKiONBDcwGCMIczwIHIAalERZQkSZQA0smAwsGxd0oy9U4iZiPOI5FAgWEgwI2OoExw5eQbBRH2LlMUYRFgOi4gAZNfIbHIYQ1BYHEJCQA)

Having the overload with the type guard seems to put a constraint on the return type of `reduce` which in turn will make the the inference of `U` preserver literal types.

**Comment by MartinJohns** [comment]
The issue is the lack of #14520.

**Comment by RyanCavanaugh** [comment]
I don't think we have any good way to fix this apart from some new syntax that would allow explicit reprioritization of inference candidates. As-is we consider the argument-position `U` to be higher-priority than the return-type-position `U` and just go with it, which is desirable behavior in a lot of other cases.
