### ISSUE TITLE
String literal intersection type unioned with String properties evaluates to non-literal string

### ISSUE THREAD

**Issue by reiv** [microsoft/TypeScript#41718]
**TypeScript Version:**  4.1.2

**Search Terms:**
string literal intersection union branded type

**Code**

```ts
type Foo = "foo" & {_?: never};
type Foo2 = ("foo" & {_?: never}) | {length: "this is not even a number"};

// Both of these should be errors, I think.
const foo: Foo = "bar";
const foo2: Foo2 = "bar";
```

**Expected behavior:**
Both assignments result in type errors.

**Actual behavior:**
The assignment to `foo2` passes without errors.

**Playground Link:**
https://www.typescriptlang.org/play?ts=4.1.2#code/C4TwDgpgBAYg9nKBeKAiAZg1UBkUDeA+gPwBcUAdhAG4QBOAvgNwCwAUKJLAgEzJQAKDFlwES5KrUYBKKAB8CAGwgUA5sAAW5VJoCWAZygHKcYFBoqoAQ0oBXALYAjeqmbt2AYzgV9ZzHHJ4RBRURys6VFY2Lx8-XkDeflDwyPYgA

Apologies for the strange title. Please feel free to change it to something more appropriate.

For context: the `Foo2` type is the result of a branded string type being in a union with an N-tuple type (basically `{ length: N }`). 

`length` can be replaced with any other `String` property (e.g. `toUpperCase`) - the actual value doesn't seem to matter, only the name.

3.7.5 is the last TS version on the playground that has the expected behavior, so the breaking change would have come after that.

**Comment by RyanCavanaugh** [comment]
Just to flesh it out entirely:
```ts
type Foo = "foo" & {_?: never};
type Foo2 = ("foo" & {_?: never}) | {length: "this is not even a number"};
type Foo3 = {length: "this is not even a number"};

const foo: Foo = "bar";
const foo2: Foo2 = "bar";
const foo3: Foo3 = "bar";
```

**Comment by jcalz** [comment]
Looks like this is fixed as of TS4.6 but I haven't checked into what fixed it.
