### ISSUE TITLE
Creating a class whose instances will be instances of Error

### ISSUE THREAD

**Issue by matthewjh** [Microsoft/TypeScript#4171]
Hi,

I'm creating some custom error classes, but ran into an issue when using jasmine's `expect(fn).toThrowError(MyCustomError);`

The problem is that jasmine's `toThrowError` matcher checks that the exception thrown by `fn` is an instance of `Error`. This is clumsy to satisfy in TypeScript, as in `lib.d.ts` `Error` is an interface.

Thus, if one creates `MyCustomError` in the most straightforward and intuitive way supported:

````javascript
export class MyCustomError implements Error { 
  public name: string = 'MyCustomError';
  public message: string;
}
````

and throws an instance of this class, code such as that in jasmine that checks for an instance of `Error` will fail. And yet, their assumption seems quite legitimate.

Here's the code I ended up with:
````javascript
export class MyCustomError implements Error { 
  public name: string = 'MyCustomError';
  public message: string;
}

MyCustomError.prototype = Object.create(Error.prototype);
````

This will satisfy the `instanceof Error` constraint, but it's fairly unintuitive for what seems like a common task (creating a runtime subtype of `Error`) -- one that shouldn't require setting the `prototype` property manually.

Any thoughts?

**Comment by RyanCavanaugh** [comment]
Upgrade to TypeScript nightly build (`npm install typescript@next`), or wait until TypeScript 1.6, then write

```ts
class MyCustomError extends Error {
}
```

**Comment by matthewjh** [comment]
Oh cool. Out of interest, why was `Error` an interface in the first place and what motivated the change?

**Comment by RyanCavanaugh** [comment]
Prior to some other changes, it wasn't possible to augment an existing class the same way you can an interface (multiple class declarations were an error, rather than merging like interfaces do).

The change in 1.6 is that we allow arbitrary expressions in `extends` clauses instead of requiring the symbol to point to a class.

**Comment by mhegazy** [comment]
Looks like the original issue has been answered. please reactivate if you are running into other issues.
