### ISSUE TITLE
Check a const extends a type at definition whilst not assigning it

### ISSUE THREAD

**Issue by ThomasAribart** [microsoft/TypeScript#41715]
## Search Terms

Extends, assign, as const

## Suggestion

I have a use case where I want to check at a constant definition, that it extends a type whilst not being assigned to it.

## Use Cases

I have developed a library that infers valid types from JSON schemas only through type computations, by making profit of the `as const` statement, generics and type recursions.

Read more here 👉 https://github.com/ThomasAribart/json-schema-to-ts

An example:

```typescript
import { FromSchema } from "json-schema-to-ts";

const dogSchema = {
  type: "object",
  properties: {
    name: { type: "string" },
    age: { type: "integer" },
    hobbies: { type: "array", items: { type: "string" } },
  },
  required: ["name", "age"],
  additionalProperties: false,
} as const;

type Dog = FromSchema<typeof dogSchema>;
// => { name: string; age: number; hobbies?: string[] }
```

The `as const` statement is needed to keep `typeof dogSchema` as narrow (and thus parsable) as possible.

Currently, `FromSchema` will raise an error if `typeof dogSchema` doesn't extend DefinitelyTyped's JSON schema definitions. It's better than nothing, but it would be great to have the benefits of a type assignment (autocomplete, error highlighting etc...).

## Examples

```typescript
import { JSONSchema } from "json-schema-to-ts"; // <= Readonly type based on DefinitelyTyped

const invalidSchema extends JSONSchema = {
  type: "object",
  properties: {
    name: "string" // <= Error is raised
} as const;

const validSchema extends JSONSchema = {
  type: "object",
  properties: {
    name: { type: "string" },
  }
} as const;

type ValidData = FromSchema<typeof validSchema> // <= Still works
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
Sounds like #7481
