### ISSUE TITLE
Type inference fails

### ISSUE THREAD

**Issue by newcat** [microsoft/TypeScript#41712]
**TypeScript Version:**  4.2.0-dev.20201127

**Search Terms:**
* typescript type inference
* typescript type not inferred correctly
* typescript mapped types

**Code**

```ts
interface INodeIO<T = any> {
    value: T;
}

type IODefinition = Record<string, INodeIO>;
type IODefinitionValues<D extends IODefinition> = {
    [K in keyof D]: D[K] extends INodeIO<infer T> ? T : never;
};
type CalcFunc<I extends IODefinition, O extends IODefinition> = (
    inputs: IODefinitionValues<I>
) => IODefinitionValues<O>;

type NodeDefinition<I extends IODefinition, O extends IODefinition> = {
    setup(): { inputs: I; outputs: O };
    calculate?: CalcFunc<I, O>;
};

function defineNode<I extends IODefinition, O extends IODefinition>(def: NodeDefinition<I, O>) {
    return def; // placeholder
}

// T1 is correctly identified as
// T1 = { hello: number; }
type T1 = IODefinitionValues<{ hello: { value: number } }>;

// T2 is identified as (inputs: IODefinitionValues<{ test: { value: number; };}>) => IODefinitionValues<{ ret: { value: boolean; }; }>
type T2 = CalcFunc<{ test: { value: number } }, { ret: { value: boolean } }>;


// This works as expected, Intellisense is working and I get type errors when using the wrong type
const calcFuncTest: T2 = (def) => ({ ret: Boolean(def.test) });
calcFuncTest({ test: 3 });

defineNode({
    setup() {
        return {
            inputs: {
                a: { value: 3 },
                b: { value: "bar" }
            },
            outputs: {
                c: { value: false },
                d: { value: "foo" }
            }
        };
    },
    calculate(inputs) {
        return {
            c: inputs.v, // (1)
            d: inputs.a, // (2)
        };
    }
});
```

**Expected behavior:**
* `(1)` should give an error, since `inputs.v` does not exist
* `(2)` should give an error, since `inputs.a` is a `number`, while `d` is a `string`

**Actual behavior:**
The code above compiles without errors. Also, Intellisense is not working at the `calculate` function inside `defineNode`.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201127#code/JYOwLgpgTgZghgYwgAgJIDkD2ATCqDyAPACrIC8ycIAngHzIDeAUMq8gG5wA2ArhAFzJiAbiYBfJkzDUADigIARCDFDAwwTCHLIAShASYo2QgGcwUUAHMANGiy4CtUdLlp8SlSDUaQANW58JoQKyBAAHpAg2CZuHqrqmvQUzGzIANoA0sigyADWENSYMMgKALqCCpmloREQUTEYOHhEoDDQQvQA-ELIgiAQ7NCiYs6yKADC3AgAYjwgCISoNZHRscrxPrb4y3WriuteCSBJyAAULGygMjxgJoL7nt6a-rwQQai0TACU5PQPG88Am9CPgnJIXCh7BA4ocfIsdvU1o8jlsEXt3AcnsdtCk2CYIGAeDJTl9BAxsiBrrd7sJkJgblS7shtiMLqwEFMeFw4JBOoJJlwZnMFqgtmDWUwYMKjshcJ4IFD4eEVg0McjNsy0aqYVjaKc5YIoTqjosxT9cawoASeFAtHLaQB6B3IGTcpAAC0wXFwUHEkidQgAjNkYgYoFaEGAuNRsrhwMAVBBsJQTEwA8Rg8lkO6IFwuJg+jwALYAIyGyAkEKD2n+sMBryC5JzeYLjA4QMLpfaYgrYLTzuIACYQ7G6upE8m4DFTlcbkza1iXoFCOTIGYye3Xp2y1BaSMxLQfmQ-mqAX4gY3kFawBvOFvkCXMF6IFQ93vPlWh9oBUL5ivkGuN5tnefDbt2Fa2OS163h2D5PlwL5aD2B6iP6A7usAMQAO6GLkMRTjUciRkmtioOAuZcJhdT4iOOFQLkViUFEaDIJYBIAWMoThoY2E5loPAmIxYA5sgWFQJolgcXITAGCAZjIBygqzPMxBvEBX4UPqyhHvQpxQQSggAELwYhWkwAAdIBPxiF8oiKb+CCqWYekAWpggAMwVrZkhyqACpNHpbLIPihLEuaQWpNeNpaBaqRxbO1KMBFcUpXAMH3p5YjWMlKWpCW6WgcgABEJZwFARUVjlcVZVVqT0mAjJkrVuUIAVAjIPAXA0TVuW9bKbWCEVMBPhVEh9WwY25ayqQ9Ww9lcjyEAzpSc7hb1UW2kl43soICUmOZ7C2AGpyBl8zWsNgu0rbc5lwEdzqnIOZ3bR1T4ecgx3uc9U2iDN4jeUwQA)

**Related Issues:**

**Comment by jcalz** [comment]
Could you provide a more minimal example?  

Possibly related to #33042, #39838, #38872, maybe others?

**Comment by newcat** [comment]
Tried shrinking it a bit, wasn't too successful ([new playground link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201127#code/MYGwhgzhAEDqBOYAOSCm8A8AVaBeaYAdgJ4B80A3gFDS3RICuARiAJbDQBuYIDqA-AC5oWANxUAvlSoAXYmjiIUqACYBZZHmgAlVMAD28FRggz4rQgHMANIuRp4pcXIUBVQgHclGACLRUAB4yqIQqMAj2qhpI5PjUdNAA2gDS0BbQANaoxPoAZtA+ALrCPimF-kEhYXbKmBa56CLk-CLQwoSonOjiEuKy8qjQ0UgWlgDC+gC2SPodhDIYAJIVwaHhSmjqyLYA8itV65FbMVrxdBCoMgxIABQAlMIUaYSMMhDCi6LQ+gwyr+-QPa9Gh0SbIITQG4Wf7CdxeZBLUh3PDkOHeHZOSR9FR6cDwQa5BiEYAyVizaDAfFgYLDUYTaazEILZaBVbVCLKY67fZrGqbaKkG443LCWlWekzObM3ZI4ScfSsFR9SmoamoMXjKaSpk3M60C5XW7IvUJaD4q7wQiUEGm03Q34Ak2222EBiTdqoDx89AYV2TJjoQV3aw25220zwD1ejkOExmUZB0NhiQhsMJH5-B2PJNp2hMfT6EBR72YfOF1WEIOp3OmiPFmM+iMJ+4521SZPiBIp0Ng272t7G1tmy4MS3WmvQMtF57-AB0hEZAVYpiZtgA9GvIQBGO5DhJ1mcO+du2xpjeQgBMu47oakEju4iAA)). But I replaced the domain-specific language with some generic terms so I hope it is a bit easier to understand. I'll explain it in more detail below.

```ts
class Wrapper<T = any> {
    public value?: T;
}

type WrappedMap = Record<string, Wrapper>;
type Unwrap<D extends WrappedMap> = {
    [K in keyof D]: D[K] extends Wrapper<infer T> ? T : never;
};

type MappingComponent<I extends WrappedMap, O extends WrappedMap> = {
    setup(): { inputs: I; outputs: O };
    map?: (inputs: Unwrap<I>) => Unwrap<O>;
};

declare function createMappingComponent<I extends WrappedMap, O extends WrappedMap>(def: MappingComponent<I, O>): void;

createMappingComponent({
    setup() {
        return {
            inputs: {
                num: new Wrapper<number>(),
                str: new Wrapper<string>()
            },
            outputs: {
                bool: new Wrapper<boolean>(),
                str: new Wrapper<string>()
            }
        };
    },
    map(inputs) {
        return {
            bool: inputs.nonexistent, // (1)
            str: inputs.num,          // (2)
        };
    }
});
```

Essentially, the code is about creating a `MappingComponent`, which has some defined inputs `I` and some defined outputs `O`. In the `setup()` method, these inputs and outputs are defined as a `Record<string, Wrapper>` each. These wrapper instances can be seen as placeholders.

The `map` function receives the values of the input placeholders (input `Wrapper`), so in this example it would be `{ num: <some number>, str: <some string> }`. It needs to return values for the output placeholders like this `{ bool: <some boolean>, str: <some string> }`.

Similar to above, I expect
* `(1)` should give an error, since `inputs.nonexistent` does not exist
* `(2)` should give an error, since `inputs.num` is a number, while `str` should be a string

Interestingly, the outputs `O` are inferred correctly. So for example, returning `bool: 3` in the map function creates an error, since 3 is not a boolean.

**Comment by RyanCavanaugh** [comment]
I don't see any evidence of a bug here. The inference for a setup like this is *extremely* complex, but if the type parameters are set up correctly then you would see the expected errors.

```ts
class Wrapper<T> {
    public value?: T;
}

type WrappedMap<Values> = Record<string, Wrapper<Values>>;
type Unwrap<D extends WrappedMap<unknown>> = {
    [K in keyof D]: D[K] extends Wrapper<infer T> ? T : never;
};

type MappingComponent<I extends WrappedMap<unknown>, O extends WrappedMap<unknown>> = {
    setup(): { inputs: I; outputs: O };
    map?: (inputs: Unwrap<I>) => Unwrap<O>;
};

declare function createMappingComponent<I extends WrappedMap<unknown>, O extends WrappedMap<unknown>>(def: MappingComponent<I, O>): MappingComponent<I, O>;

const res = createMappingComponent({
    setup() {
        return {
            inputs: {
                num: new Wrapper<number>(),
                str: new Wrapper<string>()
            },
            outputs: {
                bool: new Wrapper<boolean>(),
                str: new Wrapper<string>()
            }
        };
    },
    // Errors as expected
    map(inputs) {
        return {
            bool: inputs.nonexistent, // (1)
            str: inputs.num,          // (2)
        };
    }
});
```

Because there's a `Record<string,` in the definition of `WrappedMap`, you're not going to get an error on `inputs.nonexistent`, but it will produce `unknown` which triggers a downstream error.

**Comment by newcat** [comment]
I tried your code, however, I get errors on correct code now, because the values of `inputs` are of type `unknown` now. Example of a correct `map` function in the context above:
```ts
map(inputs) {
    return {
        bool: true,
        str: inputs.str,
    };
}
```
Results in this error:
```
Type '(inputs: Unwrap<Record<string, Wrapper<unknown>>>) => { bool: boolean; str: unknown; }' is not assignable to type '(inputs: Unwrap<Record<string, Wrapper<unknown>>>) => Unwrap<{ bool: Wrapper<boolean>; str: Wrapper<string>; }>'.
  Call signature return types '{ bool: boolean; str: unknown; }' and 'Unwrap<{ bool: Wrapper<boolean>; str: Wrapper<string>; }>' are incompatible.
    The types of 'str' are incompatible between these types.
      Type 'unknown' is not assignable to type 'string'.(2322)
input.tsx(12, 5): The expected type comes from property 'map' which is declared here on type 'MappingComponent<Record<string, Wrapper<unknown>>, { bool: Wrapper<boolean>; str: Wrapper<string>; }>'
```

This may very well be a design limitation, because when the `map` function is not present, the type of `res` is correctly inferred as
```ts
const res: MappingComponent<{
    num: Wrapper<number>;
    str: Wrapper<string>;
}, {
    bool: Wrapper<boolean>;
    str: Wrapper<string>;
}>
```

As soon as I write the mapping function, the type of `res` changes to:
```ts
const res: MappingComponent<Record<string, Wrapper<unknown>>, Record<string, Wrapper<unknown>>>
```
