### ISSUE TITLE
Type 'Parameters<T>' must have a '[Symbol.iterator]()'

### ISSUE THREAD

**Issue by topce** [microsoft/TypeScript#41728]
**TypeScript Version:**  4.1.2

**Search Terms:** Type 'Parameters<T>' must have a '[Symbol.iterator]()'

**Code**

```ts
export function callUserFunction<T  extends (...args: any) => void>(
  f: T | undefined,
  ...args: Parameters<T>
): void {

  // does not work compile time error
  // Type 'Parameters<T>' must have a '[Symbol.iterator]()' method that returns an iterator.(2488)

  if (f) setTimeout(() => f(...args), 1); 
}
```

**Expected behavior:**
It should compile 
**Actual behavior:**
It does not compile 
**Playground Link:** 
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVzQQwBtCBVAZ2CgDFUNsUAeAFTjlBmBQBMy4AKAHRD8UAOZkAXHHwoAngEo4AXgB8cAG4RMXFXwCwAKFYIpLAD5xUXYAkwpgXADSHWQgSPFSACiPwBbYA4oMmYVQ3kpTW04AG8XOAB6BLgAd2gAazJ4hIAqNjJCOxgAWi5MMnwAI0JgODAoG0pisnrgfC44HIT4zAR+BEUKGCZMAIgkGD4+RVVEdzAwQlk+FCRiRw8yeUc4AEZ5AG5WbOSuCGBeFAh4NKh0vAg-MEwauCwAtigoaBO4JlkwLUAOQ+KD+QKUEJMFRAuB+JBkeAAC3w6lq+DgQIA2gBlWR+SoQQgCTBBfAwaAAXWmsICMCREA69PJcAaMCQUBQvBkcFJlHJ0AEfAATAAWAAc4vkhh6fT4AzgQxGYwmUxmagQgmEYi2O32RxlRkSySIKXwsl4t0ycAOxWlRqScAAAjAyMVMKIrg1Zf1BoFlcBxpNpsoNVr3DrtntDoaAL5AA
**Related Issues:** 
did not found

**Comment by AlCalzone** [comment]
You defined `...args` as `any` when it should be `any[]`. Change that in the playground and the error goes away.

**Comment by MartinJohns** [comment]
Duplicate of #36874.

> Search Terms: Type 'Parameters' must have a 'Symbol.iterator'

When providing search terms it's usually better to just provide a few keywords. I found the issue mentioned above by searching for `parameters symbol iterator`.

**Comment by AlCalzone** [comment]
@MartinJohns it does work though:
```ts
export function callUserFunction<T  extends (...args: any[]) => void>(
  f: T | undefined,
  ...args: Parameters<T>
): void {
  if (f) setTimeout(() => f(...args), 1); 
}
```
yields no error on the playground (v4.1.2).

**Comment by topce** [comment]
Than you @AlCalzone  your suggestion  works!
it is little bit strange because f.apply works with any and any[]
I will close this issue.
TypeScript generics very powerful  pity not used more often ;-)

**Comment by topce** [comment]
happy with suggestion ;-)

**Comment by mindplay-dk** [comment]
This is an easy mistake to make - took me quite a bit of searching to realize what I was doing wrong.

Is there any way the compiler could generate a more helpful *"Did you mean..."*-type error message here? 🤔

**Comment by limgyumin** [comment]
This one worked for me.

```ts
export function callUserFunction<T  extends (...args: any) => void>(
  f: T | undefined,
  ...args: [...Parameters<T>] // this
): void {

  // does not work compile time error
  // Type 'Parameters<T>' must have a '[Symbol.iterator]()' method that returns an iterator.(2488)

  if (f) setTimeout(() => f(...args), 1); 
}
```
