### ISSUE TITLE
Unable to assign functions with fewer parameters to functions that take more parameters in a generic form

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#41720]
**TypeScript Version:**  4.1.2

**Search Terms:**

**Code**

```ts
type F1 = (...args: [number]) => void;
type F2<T extends [number, number]> = (...args: T) => void;

interface I1 {
  runCallback: (cb: F1) => void;
}

interface I2<T extends [number, number]> extends I1 {
  runCallback: (cb: F2<T>) => void;
}
```

**Expected behavior:**
F1 should always be assignable to F2<T>, no matter what T is.
As a result, I2<T> should always be assignable to I1 due to contravariance.

**Actual behavior:**
```
Interface 'I2<T>' incorrectly extends interface 'I1'.
  Types of property 'runCallback' are incompatible.
    Type '(cb: F2<T>) => void' is not assignable to type '(cb: F1) => void'.
      Types of parameters 'cb' and 'cb' are incompatible.
        Types of parameters 'args_0' and 'args' are incompatible.
          Type 'T' is not assignable to type '[number]'.
            Type '[number, number]' is not assignable to type '[number]'.
              Source has 2 element(s) but target allows only 1.ts(2430)
```

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgjFAvFAFAOgwQwE4HMDOAXFANoB2ArgLYBGE2AugJRIB8UAbgPYCWAJgG4AUKEiwATAB4AKlAgAPYBDJ98pSrXoAaKBrqN2ydFjxEo0lonbd+woTzJLsAM0wBjaAEkEAbyFQobAoyAGFMABtwmncAa2IUNxpieEtrXkEhAF8he0d6Vw8oTylZBSUVNXJqfR09egZ2MuVVIt9-QOCwyOi3ONRE5JLWVM504UygA

**Related Issues:** 
https://github.com/microsoft/TypeScript/pull/17765

**Comment by RyanCavanaugh** [comment]
The problem is that `[number, number]` and `[number]` have no relation due to their conflicting `length` properties (`2` and `1`) - they only relate covariantly when instantiated into a parameter list. Once we've measured these types as being contravariant, we use that measure for relational checks. If this shows up often enough we could maybe introduce a new variance measurement result, but as-is I'm calling this a design limitation for now.

**Comment by graphemecluster** [comment]
@RyanCavanaugh I encounter a similar situation too:

https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzCgggCMowBrACgDcjkQAueVZAWxJBgEpmacswANwAoEaEiwEKdNjxIcOKoWJlKzKgDptdCAwDOzANqsOXADQt2nGAH4Aut3gBeAHzx+g3h4HCRiRWUiUnIKblFxcGg4JDRMXHwyGCDVUI1tTV0DY1Mbe3gAH3gTawsrMxhHF3dPYG9a0SSUkMpwsQB6dvgAdxwYClgcNGB9MQlo6Ti5fBUWigBGWnomcptLAH00ZH0QYHXbZlyuet9G2Ga1BbbIyRiZePlZy4AmLW0jLJB7Q9KYI0c+KcRE0nqFnuEgA

Is it essentially the same problem and is it still a design limitation in 2022?
