### ISSUE TITLE
import.meta.url is not supported in module : es2020

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#41722]
**TypeScript Version:**  4.2.0-dev.20201129

**Search Terms:** import.meta.url

**Code** 

```ts
export function foo() {
  return import.meta.url;
}
```

**Expected behavior:** It should work

**Actual behavior:** `Property 'url' does not exist on type 'ImportMeta'.`

**Playground Link:** https://www.typescriptlang.org/play?target=7&ts=4.2.0-dev.20201129#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWIhACgEo4BvAWACg44pgYkpdMBbSWAOhfoEMPGANgG4qAXyA

**Related Issues:** #41274 didn't add `url` in `ImportMeta`, which is supported by [HTML](https://html.spec.whatwg.org/multipage/webappapis.html#hostgetimportmetaproperties).

**Comment by saschanaz** [comment]
ES2020 does not require `import.meta.url` so it should probably go `lib.dom.d.ts`.

**Comment by thatguyintech** [comment]
What should I do in my project if I'm trying to run `npx ts-node` and I'm seeing 

`error TS2339: Property 'url' does not exist on type 'ImportMeta'.` ?

**Comment by saschanaz** [comment]
Maybe check whether your TypeScript version is new enough?
