### ISSUE TITLE
Object completions broken when leading space is present

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#41725]
```ts
declare function foo(x: { abc: string, def: number });

foo({ /**/})
```

and

```ts
declare function foo(x: { abc: string, def: number });

foo({ abc: "hi", /**/})
```

**Expected**: completions
**Actual**: **no completions**

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser The TS server seems to returns the correct response, however, the completion popup doesn't include the correct suggestions. And _fourslash_ test for this case works too. 

```shell
Info 793  [22:12:24.194] request:
    {"seq":160,"type":"request","command":"completionInfo","arguments":{"file":"/index.ts","line":2,"offset":8,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}
Info 801  [22:12:24.195] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":160,"success":true,"body":{"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"entries":[{"name":"abc","kind":"property","kindModifiers":"declare","sortText":"1"},{"name":"def","kind":"property","kindModifiers":"declare","sortText":"1"}]}}

```

**Comment by DanielRosenwasser** [comment]
Hm, so is this a VS Code bug? @mjbvz

**Comment by mjbvz** [comment]
@DanielRosenwasser I can't seem to reproduce this. Is the repro just copy/pasting the snippets into a TS file and triggering suggestions at the `/**/`?

<img width="1315" alt="Screen Shot 2020-12-01 at 12 34 58 PM" src="https://user-images.githubusercontent.com/12821956/100793896-ac7d3400-33d1-11eb-9aee-57274e1dbd7c.png">

<img width="1503" alt="Screen Shot 2020-12-01 at 12 35 06 PM" src="https://user-images.githubusercontent.com/12821956/100793879-a8e9ad00-33d1-11eb-8961-981f6d645a2e.png">

**Comment by DanielRosenwasser** [comment]
Hm, maybe I was running with an older VS Code Insiders build? Sorry.

**Comment by DanielRosenwasser** [comment]
(or an older TS build?)
