### ISSUE TITLE
Object literal completions in declaration initializer include declared variable

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#41731]
**TypeScript Version:**  4.1.2

**Search Terms:** object literal completions

**Code**

```ts
const obj = { prop: o/**/ };
```

**Expected behavior:** No completion for `obj`, because that would be a used-before-declared error

**Actual behavior:** Completion for `obj` offered

**Playground Link:** https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvGAHATiLAXHDAL4DcQA

**Related Issues:** #41539

**Comment by chenjigeng** [comment]
I'm trying to solve this problem, but I have a question. The code below should completion for obj?
```typescript
const obj = { prop: () => {
    console.log(o/**/)
} };
```

**Comment by chenjigeng** [comment]
Now I have a problem.My original idea was to make a judgment on the returned symbols, whether that symbol is an ancestor of the current node, and if so, not return that symbol.
But I find that this judgment should be only for object literals but I don't know how do you distinguish this case. Can you give me some advice?  The code is on this PR @andrewbranch

**Comment by chenjigeng** [comment]
I have found a method, which is to find the literal object declaration of the current node and then go through the symbols to determine whether it contains the declaration. If it does, remove the symbol. please help CR @andrewbranch
