### ISSUE TITLE
tsc says "No inputs were found" when "outDir": "."

### ISSUE THREAD

**Issue by benmccann** [microsoft/TypeScript#41734]
**TypeScript Version:**  Tested with both 4.1.2 and 4.2.0-dev.20201130

**Search Terms:**

"No inputs were found"

**Code**

I get an error message about "No inputs were found" if I have the below in my `tsconfig.json`. This is extremely confusing because the inputs are indeed present at the location mentioned in the error message
```
	"compilerOptions" : {
		"outDir": "."
	},
```

`tsc` completes successfully if I change the `outDir`:
```
	"compilerOptions" : {
		"outDir": "dist"
	},
```

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

Ideally `tsc` should complete successfully and output the `.js`, `.js.map`, and `.ts.d` files alongside my input `.ts` files. Or if that's something that's not supported then it should tell me that `"outDir": "."` is not valid or give some other error message is more understandable and actionable

**Actual behavior:**

TypeScript prints:

>No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["./"]'.

This is completely wrong. The input is indeed at the given location, so I was tearing my hair out trying to figure out what was wrong

**Playground Link:** I'm not that familiar with the Playground, but it doesn't look like I can control `outDir` there, so this probably can't be reproduced there

**Related Issues:** N/A

**Comment by DanielRosenwasser** [comment]
It's unclear what went wrong since this doesn't really have a self-contained repro, but `exclude` is implicitly `./**/*` so if you wanted `./*` you'll have to write that out explicitly.

**Comment by sheetalkamat** [comment]
I think if you dont specify exclude, the default is to exclude outDir so this seems like working as intended. as @DanielRosenwasser you would need to specify include/exclude depending on what your intent is.

**Comment by benmccann** [comment]
Thanks for responding. Here's a repo to reproduce: https://github.com/benmccann/tsc-repro. There may be something more complicated here as this only seems to happen when there's a subdirectory present and the `tsconfig.json` `extends` another.

>I think if you dont specify exclude, the default is to exclude outDir so this seems like working as intended.

Does that also exclude sub-directories? I have `.` as the `outDir` and my source is in a `src` subdirectory
