### ISSUE TITLE
Add compiler-with-unions to on-demand perf suite

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#41733]
We have an old fork of the compiler where the top-level `Node` type is replaced with a union of every possible syntax node type. We use this for internal perf tracking, but there's no way to gauge if a test

**Comment by rbuckton** [comment]
I've updated the Benchmark Settings variable group to include it in benchmarks, though I need to test to make sure it actually runs. IIRC, I've run into issues with the fact the suite has a `-` in the name.

**Comment by rbuckton** [comment]
Looks like this is working.
