### ISSUE TITLE
TypeScript wont read the tsconfig.json

### ISSUE THREAD

**Issue by Sardonyx78** [microsoft/TypeScript#41747]
**TypeScript Version:**  4.2.0-dev.20201201

**Search Terms:** Typescript undefined config

My tsconfig.json:
```json
{
     "compilerOptions": {
         "module": "commonjs",
         "target": "es2019",
         "types": [
             "node"
         ],
         "strict": true,
         "moduleResolution": "node",
         "declaration": false,
         "resolveJsonModule": true,
         "removeComments": false,
         "esModuleInterop": true,
         "alwaysStrict": true,
         "pretty": true,
         "sourceMap": true,
         "outDir": "dist",
         "incremental": true,
         "noEmitHelpers": true,
         "importHelpers": true,
         "skipLibCheck": true,
         "strictNullChecks": false
     },
     "include": ["src/**/**.**"]
 }
```
My folder structure
![folder](https://i.sardonyx.studio/😢🙁🤔🤭😓🐾🐵😝)

**Expected behavior:** Transpiling the code

**Actual behavior:** Throws an error
```log
C:\Users\BoraC\Desktop\Projects\g-lua-tr-bot>tsc
undefined:1

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.getBuildInfo (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:81612:21)
    at readBuilderProgram (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:91421:28)
    at Object.createIncrementalProgram (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:91442:26)
    at Object.performIncrementalCompilation (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:91402:33)
    at performIncrementalCompilation (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:93675:29)
    at executeCommandLineWorker (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:93547:17)
    at Object.executeCommandLine (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:93595:20)
    at Object.<anonymous> (C:\Users\BoraC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:93882:4)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
```

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment]
Do you perhaps have a byte-order-mark (BOM) or any other invisible character in the beginning of your file?

**Comment by filippo-fonseca** [comment]
> Do you perhaps have a byte-order-mark (BOM) or any other invisible character in the beginning of your file?

I agree with this. Perhaps check for invisible characters; happens to me a lot.

**Comment by RyanCavanaugh** [comment]
That's the exact error I get when running this on a file with a BOM:
```
> JSON.parse(fs.readFileSync("./sample.json", { encoding: "utf-8" }))
Uncaught SyntaxError: Unexpected token ﻿ in JSON at position 0
```
so I think that's what's happening.

**Comment by Sardonyx78** [comment]
nope thats not whats happening
![img](https://i.sardonyx.studio/🐴😳😈🙄🐉🚀🙀💕)

**Comment by Sardonyx78** [comment]
Also this error happens in all of my project not only this one, and same tsconfig works in other machines

**Comment by RyanCavanaugh** [comment]
No idea what's happening. If you have some way to reproduce it we can investigate further, but it seems like something is broken on that computer

**Comment by Sardonyx78** [comment]
Well it started after my pc gave me a GSOD, after restarting my pc this error started to occur.

**Comment by orta** [comment]
@Sardonyx78 I'd recommend making a fresh repo we can clone which reproduces this 👍🏻

**Comment by Sardonyx78** [comment]
@orta [This is the repo](https://github.com/Sardonyx78/GLua-Wiki-Searcher-Bot)

**Comment by RyanCavanaugh** [comment]
Cloned the repo; it checks out fine. Maybe your node install is corrupt or something?

**Comment by fogaztuc** [comment]
Got in to same state when my machine blue-screened as well.  The fix was to clear the typescript compiler cache via "tsc --build --clean".
