### ISSUE TITLE
Compiling TS-Files with Special-Character in filename prints escaped filename as sourceMappingURL

### ISSUE THREAD

**Issue by viyaha** [microsoft/TypeScript#41752]
**TypeScript Version:**  4.2.0-dev.20201201 and 4.1.2

**Search Terms:** source map, sourcemap, escaping

**Code**

```ts
console.log("just testing... doesn't matter what we use here");
```

**Expected behavior:** (works in 4.0.5)
Compile-Output:
- {index}.js
- {index}.js.map

Content of {index}.js:
```
console.log("just testing... doesn't matter what we use here");
//# sourceMappingURL={index}.js.map
```

**Actual behavior:**
Compile-Output:
- {index}.js
- {index}.js.map

Content of {index}.js:
```
console.log("just testing... doesn't matter what we use here");
//# sourceMappingURL=%7Bindex%7D.js.map
```

**Playground Link:** Couldn't find a possibility to active sourceMap-Generation in Playground

**Comment by a-tarasyuk** [comment]
I suppose this is expected behavior, isn't it? https://github.com/microsoft/TypeScript/issues/40951, https://github.com/microsoft/TypeScript/pull/41102

/cc @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
@a-tarasyuk yep, you're right. Good catch.
