### ISSUE TITLE
"Convert parameters to destructured object": enable for functions with just one parameter

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#41753]
## Suggestion

Back when this refactor was added in #30089, it was decided that the refactor would not be available for functions with less than 2 parameters.

> The refactor will not be available on:
> - functions with less than 2 parameters

https://github.com/microsoft/TypeScript/pull/30089#pullrequest-256073137-permalink:~:text=functions%20with%20less%20than%202%20parameters

I would like to suggest that this refactor should be available for functions with just one parameter.

## Use Cases

The reason is because I often use this refactoring to make a function into a React component (which always receive their parameters aka props as an object), and it's not infrequent that I need to do this for a function that receives just one parameter.

Furthermore, it would be useful to run this refactoring if you plan to add more parameters immediately afterwards—as opposed to adding more parameters and then converting to an object.

## Examples

```ts
declare const add: (n1: number, n2: number) => number;

const fn = (a: number) => add(a, 1);
```

should convert to

```ts
declare const add: (n1: number, n2: number) => number;

const fn = ({ a }: { a: number }) => add(a, 1);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by OliverJAsh** [comment]
I can see from the code that this would be a very easy change: we just need to tweak this constant: https://github.com/microsoft/TypeScript/blob/87c5b6a752f8ac3239ac05fbcbbb889dc7c0019d/src/services/refactors/convertParamsToDestructuredObject.ts#L4

I can go ahead and do that but I guess I need approval from the TS team beforehand. Is there any reason why we wouldn't want to do this? One potential downside is the refactoring will appear more frequently than it currently does, which might annoy some users.

**Comment by schickling** [comment]
Thanks for pushing this forward @OliverJAsh. Really looking forward to this landing at some point! 🙏

**Comment by OliverJAsh** [comment]
@RyanCavanaugh I would like to raise a PR to fix this, can you accept this issue and add it to the backlog?

**Comment by RyanCavanaugh** [comment]
The React scenario makes a lot of sense; sure

**Comment by OliverJAsh** [comment]
Thanks, PR here: https://github.com/microsoft/TypeScript/pull/46945
