### ISSUE TITLE
Omitted property does not narrow discriminated union contextual type

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#41759]
**TypeScript Version:**  4.2.1

**Search Terms:** discriminated union optional property

**Code**

```ts repro
type DiscriminatorTrue = {
  disc: true;
  cb: (x: string) => void;
}

type DiscriminatorFalse = {
  disc?: false;
  cb: (x: number) => void;
}

type Props = DiscriminatorTrue | DiscriminatorFalse;

declare function f(options: DiscriminatorTrue | DiscriminatorFalse): any;

f({
  disc: true,
  cb: s => parseInt(s) // Inference works 👍 
});

f({
  disc: false,
  cb: n => n.toFixed() // Inference works 👍 
});

f({
  cb: n => n.toFixed() // Implicit any error 👎 
});

f({
  cb: (n: string) => parseInt(n) // But errors correctly with incorrect type annotation 👍 
});
```

**Expected behavior:**
No implicit any error on the third call site

**Actual behavior:**
Implicit any error on the callback parameter at the third call site

[**Playground Link**](https://www.typescriptlang.org/play?ts=4.1.2#code/C4TwDgpgBAIglgZwMYCc4Fs4DsCGwD2KAKigK7QC8UA3gFBRQAmiSAXFMGRANz1RIAjdgAoAHuwSdsAcwCUUCgD4oAN3xxGvAL61aoSLBZpMuAigBiOADYJKNPs2QB+dgDNrt3g0EjxULKToAhAo8kqq6pq0Onrg0AAKKPhgCAqGyMbYeIQk5FAAPumoGFlmljY8uowQSFY4KNCupFhIwHD4WFCuwsltHQjs8BklpjlcBUWZoxYeELLsOFggvLTddAyObBxcADR8PlCp4WD1tgCSWMDCCPIA9LdQF64hEC3QAO6EANYI0bIrawcLDcsz23iE-gUyiwADoCOY4KIIIxhHcHk8Xm8oJ8UD8-gDhOt+BDOuFYfDEcjUVB7o90GArHAkHBgFBFiB8bpAeCRFgJFIsHIoVATihzpdhFg0VAAEKkVkhJJi-iEBqtKwgbEsgAWUGwSFVNVZ+mgiyw+GAeHaWE5QA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/31404#issuecomment-596841068 is this issue, but the OP there is different.

**Notes:**
This pattern sometimes appears in React component props, where convention is to make boolean properties optional and only pass them as `true` (usually with the shorthand `<MyComponent boolProp />`). I actually suggested using discriminated union props for React components in [an old blog post](https://blog.andrewbran.ch/expressive-react-component-apis-with-discriminated-unions/), and noted this issue in a [footnote](https://blog.andrewbran.ch/expressive-react-component-apis-with-discriminated-unions/#fn-1), calling it a possible bug, but didn’t file it at the time because I had low confidence it wasn’t a duplicate or design limitation. It was later mentioned in https://github.com/microsoft/TypeScript/issues/31404#issuecomment-596841068, but was probably ignored because it was assumed to be an instance of the OP’s issue, which was determined to be a design limitation. I dove into this again because [someone tweeted at me](https://twitter.com/ChrisDascoli5/status/1333123689139855362) asking about that footnote after reading the post.

**Comment by weswigham** [comment]
In this case, I think this'd be fixable by adjusting `discriminateContextualTypeByObjectMembers` and `discriminateContextualTypeByJSXAttributes` to include `undefined`'able discriminant props which don't appear in the `node`'s properties. (They both currently filter the props which _do_ exist on the input object down to the discriminant ones right now, so the possibly `undefined` discriminants from the contextual type would need to be appended to those)

**Comment by RyanCavanaugh** [comment]
Tagging backlog since this is a longstanding shortcoming, but we can take it earlier if someone's eager to take a stab.

**Comment by safareli** [comment]
This is same issue as this one right?


```ts
type Props = {
  mode?: boolean;
  nodes?: string;
}

type B =
  | { enabled?: false; }
  | { enabled: true; foo: string; };


// no error UNEXPECTED ❌
export const a: Props & B = {
  mode: true,
  nodes: ",",
  foo: "",
};


type B2 =
  | { enabled: false; }
  | { enabled: true; foo: string; };

// compiles as expected ✅
export const a2: Props & B2 = {
  mode: true,
  nodes: ",",
  enabled: true,
  foo: "",
};


// err as expected ✅
export const a3: Props & B2 = {
  mode: true,
  nodes: ",",
  foo: "",
};

// err as expected ✅
export const a4: Props & B2 = {
  mode: true,
  nodes: ",",
  enabled: false,
  foo: "",
};
```



<details><summary><b>Output</b></summary>

```ts
// no error UNEXPECTED ❌
export const a = {
    mode: true,
    nodes: ",",
    foo: "",
};
// compiles as expected ✅
export const a2 = {
    mode: true,
    nodes: ",",
    enabled: true,
    foo: "",
};
// err as expected ✅
export const a3 = {
    mode: true,
    nodes: ",",
    foo: "",
};
// err as expected ✅
export const a4 = {
    mode: true,
    nodes: ",",
    enabled: false,
    foo: "",
};

```


</details>


<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```


</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgezAZygXigbwFBSgWwQBMIB+ALigCMEEAbCAQwDsBuXKZ4iZCqZYHACWzAObsAvtmyhIUAELoOAHyxQIzRlQZE+AM0Z1kEVlCl5VmdZu0QilQQFcTUPbUoDhY0xPbSA9P6cCOpwiHBQAKoAcgCiABowsQDCACqxACJQgDLk2BAAHmAIcMBQAMYIzAJQjJTwSKgAZAroWByEJA5wzgA0HFwkyJQARD2jHG4II+O+0jLg0PIATEoWahpaOpQGRi7mUJbWm3ZdzqaTHoIi4mZ+geUI+GBCDKiMqAWQZcB2UICg5HlCsVShUqqVGEs6ogUFBmstWjg8B0IKcIH08AMeCMxuijrZ7FAnGiJu4oMMZn5sPcIGEah9ChBvr8AZ9gQ8wTUAMxQhqwhQrDCIgjcVG4zFDMk4klTMkUgJBGkRd7qBlMoj-QFFErs6qMAAsPJhcIFbSRIsJ3WJGO4EtG4zwG3x20MxlxF1lfV8QA)

**Comment by safareli** [comment]
Sort of a "solution" is to do this:

```ts
// Solution is to specify all props from the non optional `enabled` as optional undefined fields
type B3 =
  | { enabled?: false; foo?: undefined}
  | { enabled: true; foo: string; };

// err as expected ✅
export const a5: Props & B3 = {
  mode: true,
  nodes: ",",
};
```

but it's not very nice. (I came across this when I was trying to use discriminated unions for react prop types)

**Comment by Andarist** [comment]
@andrewbranch  Is this supposed to be still open? This doesn't error in 4.6, see [playground](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAIglgZwMYCc4Fs4DsCGwD2KAKigK7QC8UA3gFBRQAmiSAXFMGRANz1RIAjdgAoAHuwSdsAcwCUUCgD4oAN3xxGvAL61aoSLBZpMuAigBiOADYJKNPs2QB+dgDNrt3g0EjxULKToAhAo8kqq6pq0Onrg0AAKKPhgCAqGyMbYeIQk5FAAPumoGFlmljY8uowQSFY4KNCupFhIwHD4WFCuwsltHQjs8BklpjlcBUWZoxYeELLsOFggvLTddAyObBxcADR8PlCp4WD1tgCSWMDCCPLRsitrDixus3veQv4KylgAdATmcFEEEYwluWnuuke73YnXCv3+gOBoKgAHoUf58FAMGArHAkHBgFBFiAoIAeDcAkftYrCuEIQFrQADuhAA1gg7g9hOt+B9hFgJFIsHIvlATihzpdefI0VAAEKkQkhJJi-iEBqtKwkhkEgAWVKQqpqhP00EWWHwwDw7U6gF4NwCyO1B2UA)

**Comment by andrewbranch** [comment]
Huh, the fix was reverted, so I’m not sure what happened.

**Comment by andrewbranch** [comment]
Hm, so it seems like #43633 originally fixed this but caused a crash and was reverted, and then #43937 promptly fixed it again and caused a performance regression that has not been reverted or fixed 😕

**Comment by luxaritas** [comment]
Anyone know the state of this? Is it worth a new issue? Looks to exist in 4.9.5
