### ISSUE TITLE
Missing auto import suggestions for UMD modules such as `classnames`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#41761]
- VSCode Version: 1.51.1
- OS Version: 11.0.1

Steps to Reproduce:

```tsx
import * as React from 'react';

const el = <div className={REPLACE_ME}>foo</div>;
```

1. `yarn add @types/classnames`
1. Erase `REPLACE_ME` and begin typing `classNames`

Does this issue occur when all extensions are disabled?: Yes

Expected: VS Code suggests an auto import of `classNames` from module `'classnames`'.

Actual: no suggested auto import.

![image](https://user-images.githubusercontent.com/921609/100760529-c296ee80-33e9-11eb-994c-85a465dcacb2.png)

I believe this is something to do with the fact that `classnames` is defined as a UMD module. If I change the type definitions for `classnames` to remove the UMD definition, the auto import does work correctly:

![image](https://user-images.githubusercontent.com/921609/100761038-549ef700-33ea-11eb-9dfe-6f604ae9422a.png)

---

Note that VS Code does correctly provide import suggestions after we've finished typing the identifier, when we move our cursor.

![image](https://user-images.githubusercontent.com/921609/100760730-fc67f500-33e9-11eb-9f27-eaae20adad4e.png)

This issue is specifically about auto imports inside the suggestions that appear as you're typing.

**Comment by aminpaks** [comment]
Would someone guide me how I can easily get to a point to reproduce this locally?

Not very familiar how code fixes work for `node_modules/@types/...` and requesting a code completion at a specific point.

**Comment by aminpaks** [comment]
It turns out this case happens cause the completion ends up within a `{..}` and current implementation looks up for destructuring of an object.

Trying to find a good spot to add the completion logic...

**Comment by aminpaks** [comment]
@OliverJAsh is the issue occurs within `JSX/TSX` language variant or `JS`?

**Comment by OliverJAsh** [comment]
> @OliverJAsh is the issue occurs within `JSX/TSX` language variant or `JS`?

I think I only tested it with `TSX`. Not sure if it occurs in other languages.

**Comment by aminpaks** [comment]
@OliverJAsh would you also provide a simplified version of your TS config? specially how you configured the modules.

there are settings that I'm interested to see:
https://www.typescriptlang.org/tsconfig#module
https://www.typescriptlang.org/tsconfig#esModuleInterop
https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

**Comment by aminpaks** [comment]
To be honest at this point I'm not sure if this is a bug or the correct behaviour. The code fix works though I'm not sure if auto import should be provided or even how auto import works in TypeScript/VSCode.

I would need some help to investigate more.

Added a new fourslash test here:
https://github.com/microsoft/TypeScript/pull/4214

**Comment by OliverJAsh** [comment]
@aminpaks I am using the default settings as I have no `tsconfig.json`. Repo with reduced test case: https://github.com/OliverJAsh/ts-umd-auto-import-suggestions-bug
.

**Comment by aminpaks** [comment]
@OliverJAsh yes this is exactly what I observed by looking at the code and writing that unit-test.
If you try to write `class` VSCode will offer you `classNames` as a completion, after you write full `classNames` TypeScript will offer you a code fix to add `classnames` as a new import.

Here I'm not sure if auto import should (if yes what is the default behaviour) be provided when you complete writing `classNames` and press enter.

![image](https://user-images.githubusercontent.com/9244395/103288379-c00cc200-49b2-11eb-907b-399002c0f0ae.png)

**Comment by OliverJAsh** [comment]
> Here I'm not sure if auto import should (if yes what is the default behaviour) be provided when you complete writing `classNames` and press enter.

Most users nowadays choose to import UMD modules rather than relying on the globals provided by the UMD (that's the best practice now) so I think the majority of users would find this useful.

Just to make sure we're on the same page, this is what I'm asking for: the import should be suggested in the list as the user types, in the same way that all other non-UMD modules appear in the list.

![image](https://user-images.githubusercontent.com/921609/103309736-c8deb180-4a0d-11eb-96e1-7bfce2c230f0.png)

**Comment by aminpaks** [comment]
@OliverJAsh that's exactly what I expect to happen. [As you can see](https://github.com/microsoft/TypeScript/pull/42141/files#diff-997c6dd72ca8f6691bb1888731ca4ed034c21c3f25522af8c01d67f4b27d4c6dR36) in the test that I wrote it checks for both. Auto import by completion and code fixes.

I don't know why in provided project auto import stops working though!

**Comment by aminpaks** [comment]
@RyanCavanaugh I would need some help to continue working on this issue. If someone on the team would clarify how TypeScript determines auto imports from `node_modules/@types` in code completion would really help.
