### ISSUE TITLE
JSDoc @extends should apply to @template

### ISSUE THREAD

**Issue by runarberg** [microsoft/TypeScript#41768]
## Search Terms

* JSDoc
* template
* extends

## Suggestion

When writing type annotations in JavaScript files with JSDoc it is not possible to put type constraints on the generic type parameter using `@template`. Intuitively you would follow a `@template` with `@extends`, however `@extends` is limited for classes. We should allow `@extends` to follow `@template` which would add type constraints to the generic type parameter.

## Use Cases

Currently you can write type constraints to a generic function type parameter using the `@type` tag. However this has it’s limitations as we are unable to use the type parameter inside the function body:

```js
/**
 * @type {<T extends Constraint>(x: T) => void}
 */
function foo(x) {
  /** @type {T[]} */
  const arr = [];
  // Cannot find name 'T' [2304]
}
```

Here is a real world example where I am forced to add a `// @ts-ignore` before a yield in which I’m unable to tell typescript that I’m mapping a tuple because because I’m unable to access a type parameter that `extends` a constraint.

<details>
<summary>Example</summary>

```js
/**
 * Take any number of iterators, and zip them together into one iterator of
 * tuples. Closes after the shortest of the inputs closes.
 *
 * @example
 *   import { of, pipe, repeat, seq, toArray, zip } from "andcetera";
 *
 *   pipe(
 *     zip(
 *       of("a", "b", "c"),
 *       seq(Number.POSITIVE_INFINITY),
 *       repeat(() => of(true, false)),
 *     ),
 *     toArray(),
 *   );
 *   // => [["a", 0, true], ["b", 1, false], ["c", 2, true]];
 *
 * @type {<T extends unknown[]>(
 *   ...items: { [K in keyof T]: Iterable<T[K]> }
 * ) => Iterable<T>}
 */
export default function* zip(...items) {
  const iters = items.map((item) => item[Symbol.iterator]());
  let buffer = iters.map((iter) => iter.next());

  while (!buffer.some(({ done }) => done)) {
    // @ts-ignore
    yield buffer.map(({ value }) => value);

    buffer = iters.map((iter) => iter.next());
  }
}
```

</details>

## Examples

If we allowed `@extends` after a `@template` we could annotate the function in a more traditional way, as well as fixing our problem.

```js
/**
 * @template T
 * @extends {Constraint}
 * @param {T} x
 * @returns {void}
 */
function foo(x) {
  /** @type {T[]} */
  const arr = [];
}
```

Here is the previous real world example with a proposed solution (note the `@extends` tag). See [this playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mAVAAgF4wA4B4AqyCmAHlPmACYDOy4A1mHAO5gDaAugHwAUAsAFDLIAdMJgkAthQBcyAN7JmAaWQwwyGvgCecYMhytpASRIAnAIYAjADb5cijsgC+fAJSGTF67nay+AiAgooZRMqAF5g-AlBMVMMTk5RSOdkUO9EsWYAZQ0xczhLQUSzKDhjVk5nZwBuX2RrIPMQYGB8YxSI4wpo2Pii5NSOwTAiKArqvlqGAAsYa2ROAEJG5tbBCjgxfHi5MgR8R37vXeHKn34BZA0YfEsyZGWW4264zjkAN1NLEH2HQ+QPr74ZKmKhyRTKVTqLQ6PTSHB2Rw1Xi1AQPVrtIpdGIvPopNImIYjMZIgROXgOIA) for the typescript equivalent.

<details>
<summary>Example</summary>

```js
 * @template T
 * @extends {unknown[]}
 * @param {{ [K in keyof T]: Iterable<T[K]> }} items
 * @returns {Iterable<T>}
 */
export default function* zip(...items) {
  const iters = items.map((item) => item[Symbol.iterator]());
  let buffer = iters.map((iter) => iter.next());

  while (!buffer.some(({ done }) => done)) {
    /** @type {{ [K in keyof T]: Iterable<T[K]> }} */
    yield buffer.map(({ value }) => value);

    buffer = iters.map((iter) => iter.next());
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by runarberg** [comment]
See also [JSDoc tag `@extends`](https://jsdoc.app/tags-augments.html) usage allows extending a symbol:

> The `@augments` or `@extends` tag indicates that a symbol inherits from, and potentially adds to, a parent symbol. You can use this tag to document both class-based and prototype-based inheritance.

I’m not sure if this will break IDEs or doc systems that reads this tag expecting a class constructor, in that case perhaps an alternative solution is required. Alternatives include:

* Putting constraints before the template deceleration
   ```js
   /*
    * @template {Constraint} T
    */
   ```
* Using a different tag name (e.g. `@constraint`):
   ```js
   /*
    * @template T
    * @constraint {Constraint}
    */
   ```

**Comment by runarberg** [comment]
Closing, I see that constraints is already a feature for `@template`.

**Comment by briandipalma** [comment]
How is it done?

```
@template {{new(...args: any[]): SuperClass}} T
```

?

**Comment by JackVeromeev** [comment]
@briandipalma , just with one pair of brackets

```javascript
/**
 * @template {new(...args: any[]): SuperClass} T
 */
```

**Comment by anion155** [comment]
@JackVeromeev with one pair of brackets you would need to use arrow function declaration
```
/**
 * @template {new(...args: any[]) => SuperClass} T
 */
```
