### ISSUE TITLE
Event type for readystatechange is not specific enough

### ISSUE THREAD

**Issue by jurosh** [microsoft/TypeScript#41775]
**TypeScript Version:**  4.1.0 (probably all)

**Search Terms:** readystatechange, ProgressEvent

**Code**

```ts
document.addEventListener('readystatechange', event => {
  if (event.target?.readyState === 'complete') {
    // ready state
  }
});
```

**Expected behavior:**
For `readystatechange` event, when calling from `document.addEventListener` there is only single event target allowed and that is Document itself.
Spec:
- https://html.spec.whatwg.org/multipage/indices.html#event-readystatechange
- https://developer.mozilla.org/en-US/docs/Web/API/Document/readystatechange_event

So code above should be executable without typescript errors.

**Actual behavior:**
Currently there is no information about event.target. It's pointing to generic event interface.

[Playground Link](https://www.typescriptlang.org/play?#code/CYewxgrgtgpgdgFwHQENjAKIDd4IDICWAzgvDAE4AUA5OTGgJ4kqlgAWKcA5jNQDQACGDkQCAvAD4BAbwBQAgQQBmAysNxIEKcjwQB+JHUYBlLaXFixA6mBBQADgBsYpagEoZ8hQID0PgUbADALMpF4AvrLhbgDcQA)

**Comment by jurosh** [comment]
I've tried to make PR which would fix this https://github.com/microsoft/TypeScript/pull/41776
- but problem is that file I edited is generated (and bot closed it) :disappointed: 
I am not sure right now what is source of those typings, can take closer look later, or if someone can give me hand I can update accordingly

**Comment by jurosh** [comment]
Seems it would be required to modify https://github.com/microsoft/TypeScript-DOM-lib-generator/ and I have no idea how.
Please feel free to close issue if that is too much for for just small typing security benefit.

**Comment by RyanCavanaugh** [comment]
That's the right repro for the fix, but we track the issues here sometimes too

**Comment by jonhue** [comment]
@RyanCavanaugh I suggest closing this here as @orta made the case for making the type more specific here.

**Comment by RyanCavanaugh** [comment]
Agreed
