### ISSUE TITLE
Improperly widened computed property keys in the presence of generics + literal types

### ISSUE THREAD

**Issue by lilred** [microsoft/TypeScript#41779]
**TypeScript Version:**  4.2.0-dev.20201202

**Search Terms:** computed property

**Code**

```ts
function obj<T extends string>(key: T) {
  return { [key]: 0 };
}
const result: { foo: number } = obj<"foo">("foo");
```

**Expected behavior:** this should compile without error.

**Actual behavior:** `error TS2741: Property 'foo' is missing in type '{ [x: string]: number; }' but required in type '{ foo: number; }'.`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201202#code/GYVwdgxgLglg9mABHARgKwDwBVEFMAeUuYAJgM6JlQBOMYA5gHwAUA1rgJ4BciWAlIgDeAKESJquKCGpJBiANrsOAXR4AGRAF8A3MM3CICKuNxkQAGyg85wOHB5gQAWxS5qWxAF5k6DACJbOD8WALs-Pl0gA

**Related Issues:**

* https://github.com/microsoft/TypeScript/issues/13948 interaction between `keyof` and  computed property keys
* https://github.com/microsoft/TypeScript/issues/15534 same, in the absence of generics; fixed

**Comment by RyanCavanaugh** [comment]
This is the correct behavior. If you imagine that we inferred `obj`'s return type to be `Record<T, number>` then this code would be allowed, but it's unsound:
```ts
function obj<T extends string>(key: T) {
  return { [key]: 0 };
}

const result: { bar: number } = obj<"foo" | "bar">("foo");
result.bar.toFixed();
```

**Comment by lilred** [comment]
I thought this was incorrect behavior because the specialized version of the function has the expected type `{foo: number}`, but now I realize that in order to accomplish that you'd need the return type of obj to be something like `T is literal ? Record<T, number> : { [x: string]: number; }`, and `is literal` does not exist in TypeScript. Sorry for the erroneous report, and thank you for the explanation!

**Comment by RyanCavanaugh** [comment]
np, it's tricky!
