### ISSUE TITLE
Rename should work on label

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#41796]
## Search Terms
rename, label

## Suggestion

Should provide rename action on label statement;

## Use Cases
Rename label in label statement.

## Examples

```ts
/*a*/label/*b*/: if () {
  break label;
}
```

```ts
/*a*/foo/*b*/: if () {
  break foo;
}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by a-tarasyuk** [comment]
Label renaming should work (https://github.com/microsoft/TypeScript/pull/40064, https://github.com/microsoft/TypeScript/issues/10019), maybe there is a special case which causes the bug.

**Comment by Kingwl** [comment]
Well....
