### ISSUE TITLE
Syntax for factorizing multiple `typeof`

### ISSUE THREAD

**Issue by abbychau** [microsoft/TypeScript#41792]
## Search Terms

`multiple typeof param`, `typeof factor`, `typeof factorization`, `merge typeof`

## Suggestion

I would like to merge union types that with `typeof` types as members, so to make it not duplicating.

## Use Cases

For cleaner and more manageable function parameter notation.

The current approach leads to duplicated `typeof`s

## Examples

e.g. We have
```TypeScript
const ToEnumType = (
    i: string,
    ti: typeof PostType | typeof PostStatusType | typeof UserType | typeof ReportStatusType | typeof UserStatusType | number,
) => {
//...
}
```

It would be good to have:
```TypeScript
const ToEnumType = (
    i: string,
    ti: typeof (PostType | PostStatusType | UserType | ReportStatusType | UserStatusType) | number,
) => {
//...
}
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I am not sure if it is expression-level syntax but adding it will have no harm but just provide convenience.

**Comment by RyanCavanaugh** [comment]
This isn't something we'd do. `typeof expr` means "Get the type of this expression" and the allowed grammatical forms of `expr` have expanded over time to cover more of the *expression space*, and `A | B` in expression space means "bitwise OR". We want to keep this fully symmetric -- anything you write in the `expr` position means what it would mean in expression space. This is similar to how when you write `typeof a.b` it's property access because it's an expression position, whereas in a type context you'd have to write `a["b"]`.

**Comment by abbychau** [comment]
> This isn't something we'd do. `typeof expr` means "Get the type of this expression" and the allowed grammatical forms of `expr` have expanded over time to cover more of the _expression space_, and `A | B` in expression space means "bitwise OR". We want to keep this fully symmetric -- anything you write in the `expr` position means what it would mean in expression space. This is similar to how when you write `typeof a.b` it's property access because it's an expression position, whereas in a type context you'd have to write `a["b"]`.

you are right. I agree that `A | B` should preserve its original meaning.

What if

**Comment by RyanCavanaugh** [comment]
`typeof {A, B, C}` would mean "the type of the shorthanded object literal {A, B, C}`. Given the constraints of the "expression space" principle and the relative preponderance of patterns which need this, I don't there's a syntactic space we would spend on this feature.
