### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by newblaque** [microsoft/TypeScript#41794]
**TypeScript Version:**  4.1.2

**Search Terms:**

**Expected behavior:**

**Actual behavior:**

**Related Issues:**

**Code**
```ts
function getArrayLength(arr) { 
  return arr.length
}
const maxThing = 12

module.exports = {
  getArrayLength,
  maxThing
}

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?useJavaScript=true#code/GYVwdgxgLglg9mABAcwKZQIICcsEMCeAMqmMlABYAUuOAlIgN6IBQiiW6IWSNWAdABsSZcswC+zCAgDOURAFtcADwAq5GKUQBeRAEYATM2by4AExBC+qJQAc4WKNO2NWKdNjxFhFADSvFquqk4sxAA)

**Comment by RyanCavanaugh** [comment]
Please fill in the template completely. Thanks, and hey back!
