### ISSUE TITLE
official typescript design patterns showcase

### ISSUE THREAD

**Issue by anlexN** [microsoft/TypeScript#41802]
1. typescript team, please you give me all typescript design patterns showcase and source code. 
2. step by step tutorial is better. 
3. i have searched github and google, but there have no good materials to explain.
if official website have these, it will be very good. do you know?

**Comment by orta** [comment]
You can find the documentation for TypeScript ( including a lot of design patterns in the handbook ) at https://www.typescriptlang.org/

**Comment by anlexN** [comment]
@orta i can not find one, where?
