### ISSUE TITLE
Extension Methods supporting?

### ISSUE THREAD

**Issue by yhl1219** [microsoft/TypeScript#41812]
What about supporting c# style extension method? Syntax should be like

```typescript
class MyClass {
  public myClassId: number;
  constructor() {
    this.myClassId = 2;
  }
}

// extend the class by using c# like syntax
class ExtendMyClass {
  public static DisplayMyClassId(this myClass: MyClass) {
    console.log(myClass.myClassId);
  }
}

// or just dont use the a class to extend it, just use a function
function DisplayMyClassId(this myClass: MyClass) {
  console.log(myClass.myClassId);
}
```

I actually prefer the latter one, implementing this should be easy to translate to js since js provide with prototype, export keyword also work with this kind. It would be great if supporting this kind of syntax to use functional programming, like extend a method for a defined type.

**Comment by RyanCavanaugh** [comment]
See #9
