### ISSUE TITLE
Incorrect compile result of arrow function using implicit return (starts with optional chaining) and with line comments in between

### ISSUE THREAD

**Issue by QuincyHe** [microsoft/TypeScript#41814]
**TypeScript Version:**  Since v3.8.3

**Search Terms:**
Arrow function, implicit return, line comments, optional chaining
**Code**

```ts
// Target: ES5
// arrow function, implicit return on 2nd line that starts with optional chaining, and has a line comment in between the lines.
const test = (names: string[]) => 
    // testing 1 two
    names?.filter(x => x);

console.log(test(["a"]));
```

**Expected behavior:**
Something like:
```ts
"use strict";
var test = function (names) { // testing 1 two
return names === null || 
names === void 0 ? void 0 : 
names.filter(function (x) { return x; }); };
console.log(test(["a"]));
```
**Actual behavior:**
1. the comment is being copied 3 times.
1. the first line comment terminates the `return`, making this function always return `undefined`.
```ts
"use strict";
var test = function (names) { return 
// testing 1 two
names === null || 
// testing 1 two
names === void 0 ? void 0 : 
// testing 1 two
names.filter(function (x) { return x; }); };
console.log(test(["a"]));
```
**Playground Link:** 
https://www.typescriptlang.org/play?target=1&ts=3.8.3#code/MYewdgzgLgBFCm0YF4YAowEMC2iBcM0ATgJZgDmA2gLoCUKAfDAFAxswD0HciUZ5MAIxwA7iFbssuCAH4AdADMSAGwRE0AD0YwNtANzNmoSCGXw5ykOTQJoaSgCJMDuvqA
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@rbuckton correctness-affecting emit bug here

**Comment by rbuckton** [comment]
```ts repro
// @showEmit
// @target: es5
const test = (names: string[]) => 
    // single-line comment
    names?.filter(x => x);
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=1&ts=4.2.0-dev.20201211#code/PTAEAEGcAsHsHcCiBbAlgFwLACgQXQIYBOA5gKboBcoZkArDgMawB2k6o6tHAvKABQsCyWtXZFULEgG0AugEpQPAHygcoDaDyRJJADZkAtHsllQzZCJZZsm0EJGQA-ADoAZqj1ci-AB5LVX3kAbiA)
