### ISSUE TITLE
No way to get constructor arguments for abstract class?

### ISSUE THREAD

**Issue by Griffork** [microsoft/TypeScript#41819]
**TypeScript Version:**  4.0.3

**Search Terms:**
Infer arguments from constructor of abstract class.

**Code**

I have the following class, I cannot get the constructor parameters via generic typing.
``` typescript 
abstract class Test {
    constructor(public a: string, public b: number) {}
}
```

Abstract classes cannot be assigned to new:
```ts
type ObjectType<T> = T extends (new (...args: any[]) => infer C) ? C : never;
type ConstructArguments<T> = T extends (new (...args: infer C) => any) ? C : never;

declare function ClassWrapper<
	Class extends (new (...args: any[]) => any),
	Output extends ObjectType<Class>,
	ConstructorArgs extends ConstructArguments<Class>>
	(base: Class): (
			(new (...args: ConstructorArgs) => {c: string} & Output));

var test = ClassWrapper(Test); //Error about abstract class not being able to be assigned to new(): Test
```

Constructor arguments can not be inferred via crawling the prototype:
``` typescript
type AbstractConstructArguments<T> = T extends {prototype:{constructor: (...args: infer C)=>any}}?C: never;

var args: AbstractConstructArguments<Test>;  //args is never.
```

**Expected behavior:**
There should be a way to type the constructor arguments for an abstract class. Either the class is assignable to new or inferring the arguments from the constructor directly should result in valid arguments and not type never.

**Actual behavior:**
`ClassWrapper(Test)` throws an error.
`AbstractConstructArguments` always returns type `never`.

[Playground Link](https://www.typescriptlang.org/play?ts=4.1.2#code/FDCGCMGcBcCdQMbQAQIDakpZAVApjMgN7DJmoD2AdjLAK5IWwAUADneGgJYLKgBcyWlyoBzADTJ2nHsnCCqdALbg8sAJTEAvsB3BoAT1Z5kAeXAArPEhxG8AHhwA+ZAF5cyPAA9oeKgBNsZio8AHdkZgA6aNBYUUhBUCoDAG0AXU1XFxEAMzVkAGFNAH5C5AU8ADc1AG4QQ2NC6loGaABBOOU-aEhHF3ccTx8-QIiQ8KiYuITkXPyitxckgxKyiurYOuB-awxYExy6KiQuakKMLAK6WFgDe2AASAKL7G9fAKDxiOjI2PjE5LpTJLZLqcSPUx0aDsFBvEbYcxWGx2ezPTCQJzgp7NOCtJgdeJDd6jAo4+hIAldKg9VEvJxOR7McCYPCCNFYdSCZiPB4PYJhCIIQTCMSSH5-Gakmi4xiwAmQYHEIVCOAiURaZAAMjMUJh6nUW0qsWQvkI7nZkCuNwMzHwMANIH0dmQbSgcEQ0AttmMfTcyAAYkcTmdtURWLAKNBI3ZBDgtHUGiZXbQPYjrNBvQ5nH7BnCPgGg9BTlQtcRw5Ho8ZBHNYIUNaUCuVkCENltEy63fAkFKWhTOkpur1swMifCyxGo4n+EQEGS8bAueLptWqHla0UssstFpigV1rUQDt0LEDoXi+d0Vbbvcni9R-nk+7uy9M-ZlpiIbqoffRo+u9A02RH0LQ-bFpXJKM5WmH9sD-D0exldp+0HWl0XpRlmUgVkLw5LkeT5L5mGVEUJGQJd-iacD53lRUZ2FVUxA1bVIWhKF9UNY1TRQc0XivG07WgB1gCNWsJUEODuznPtRCpGkBKcGogA) 

**Related Issues:** 

https://stackoverflow.com/questions/57643184/infer-arguments-for-abstract-class-in-typescript

**Comment by RyanCavanaugh** [comment]
See #36392

**Comment by RyanCavanaugh** [comment]
Or #35576

**Comment by Griffork** [comment]
Thanks Ryan. I swear I searched for it, I think since I used the infer and arguments keywords those issues got buried in a bunch of unrelated stuff 😕
