### ISSUE TITLE
Interface Type alias not working as expected.--  "type T = T1 | T2" cannot assign T1 as T //(TS2322: Type is not assignable to type)

### ISSUE THREAD

**Issue by softmarshmallow** [microsoft/TypeScript#41815]
**TypeScript Version:**  4.0.5

**Search Terms:**

interface type alias TS2322: Type is not assignable to type

**Code**

```ts
interface T1{
    a:any
}

interface T2{
    b: any
}

type T = T1 | T2
interface Holder{
   data: T
}

const someHolder : Holder = {
    data: <T1>{
        a: 1
    }
}
```

**Expected behavior:**
Expected to accept T1 typed interface as T without explicit `as any` casting

**Actual behavior:**
TS2322: Type 'T1' is not assignable to type T

**Comment by MartinJohns** [comment]
I don't see the issue. It was as expeced, your acutal behavior doesn't occur.

![image](https://user-images.githubusercontent.com/5269069/101136984-66f97a80-360e-11eb-98bc-a7b03783468f.png)

Works in the [playground](https://www.typescriptlang.org/play?jsx=0&ts=4.0.5#code/JYOwLgpgTgZghgYwgAgCoEYDeAoZflwBccIAntgL7baiSyIqoBMO+yARoQWZdWKQAdGyALxp0yAD5omNcNHhJkACQD2AGwAm0Vnk1wwRNL2wJVIAM5hkF1QFsIardGRcn2qKOS69BowB4MAD4fNgIudFx8KgogA) as well.
