### ISSUE TITLE
Infer parameter from usage doesn't work on interface parameters

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#41827]
```ts
interface Options {
    reportError(start, length, message): void;
}

function stuff(opts: Options) {
    opts.reportError(0, 1, "hello")
}
```

Request a quick fix to infer all types from usage. Currently you'll get

```ts
interface Options {
    reportError(start: any, length: any, message: any): void;
}

function stuff(opts: Options) {
    opts.reportError(0, 1, "hello")
}
```

Even though we should be able to infer

```ts
interface Options {
    reportError(start: number, length: number, message: string): void;
}

function stuff(opts: Options) {
    opts.reportError(0, 1, "hello")
}
```

**Comment by Leulz** [comment]
Hey there. I am looking for somewhat simple tasks to tackle in the the JS/TS ecosystem, and this one apparently fits what I'm looking for.

If that's okay with the contributors, I'd like to try building a solution for this.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by DanielRosenwasser** [comment]
@Leulz sorry this already got fixed - I'd try taking a look at other issues marked as `help wanted` or `good first issue`.
