### ISSUE TITLE
tsc fails to parse file with ZERO WIDTH NON-JOINER or ZERO WIDTH JOINER

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4182]
Using a file containing "\u200C" (\<ZWNJ>) and "\u200D" (\<ZWJ>), the compiler yields the following message:

> (27,32): error TS1127: Invalid character.

However, according to the spec, the two are valid *IdentifierPart*s.

See:
- https://es5.github.io/#x7.1
- https://people.mozilla.org/~jorendorff/es6-draft.html#sec-unicode-format-control-characters

**Comment by mhegazy** [comment]
@DanielRosenwasser feel free to send a PR for this if it is blocking your validation work.

**Comment by radu-b** [comment]
This seems to have been fixed in the meantime:

`class Day‌fly {
	dea‍fly() {		
	}	
}`

copiles correctly with `tsc -t ES5 test.ts` but fails without the ES5 option (as expected).

**Comment by shmelkin-ron** [comment]
Hi, I would like to work on this.
Could you please give me some code pointers. 
@DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Try `0x13D1FA00` to start.

**Comment by DanielRosenwasser** [comment]
Okay, bad joke.

You'll want to create a test case that has a zero-width joiner in `tests/cases/compiler/zeroWidthJoinerParses.ts`


and another with a zero-width non-joiner in `tests/cases/compiler/zeroWidthNonJoinerParses.ts`. Ideally the code should type-check cleanly so that the intention of the test is obvious. Leave a comment above each sample. If possible, you should use both the actual character, as well as an escaped character.

Then, when your tests are in place, you can see their output by running

```
jake runtests t=zeroWidth
```

You should currently observe parse errors. Then, modify the scanner to understand them appropriately. I *believe* there is a function called `isIdentifierPart`

**Comment by ShyykoSerhiy** [comment]
@DanielRosenwasser, I believe this issue should be closed as it's already working fine in master. <ZWNJ> and <ZWJ> are already present in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/scanner.ts#L246 . I've added couple  of tests in #28223 but they are probably unnecessary, feel free to reject the PR.
