### ISSUE TITLE
TypeScript Language Service plugins should be searched relative to tsconfig.json

### ISSUE THREAD

**Issue by gluxon** [microsoft/TypeScript#41828]
**TypeScript Version:**  4.2.0-dev.20201204 360958e04ca8f624ac20e13277cde8804ac3830c

**Search Terms:**
tsserver plugin candidate search

**Description**

I have a TypeScript Language Service plugin defined in `package.json` and installed to the `node_modules` folder in my project. TSServer normally picks this up fine, but when the TypeScript version is changed to *"Use VS Code's Version"*, TSServer stops considering the `node_modules` folder of my project as a candidate path. (And therefore the plugin isn't loaded.)

<img width="577" alt="Screen Shot 2020-12-04 at 6 09 20 PM" src="https://user-images.githubusercontent.com/906558/101224204-02650c80-365c-11eb-9faa-608a54546e03.png">

This is because `tsserver.js` looks up relative to its `__dirname`, which is inside `VS Code.app`. Could it also look up relative from the `tsconfig.json` file that defined the plugin?

**Expected behavior:**
A plugin installed to a project's `node_modules` should be loaded regardless of where TSServer is being loaded from.

**Actual behavior:**
TSServer fails to find plugins in `node_modules`.

**Comment by gluxon** [comment]
If there's no concerns searching up from `tsconfig.json`, I'd be happy to make a pull request.

**Comment by RyanCavanaugh** [comment]
This is for security reasons

**Comment by gluxon** [comment]
@RyanCavanaugh Got it. Thanks for taking a look.
