### ISSUE TITLE
Infer union type of the instance after function call

### ISSUE THREAD

**Issue by playerx** [microsoft/TypeScript#41832]
**TypeScript Version:**  4.1.2

**Search Terms:**
Infer type of the instance of union type inside the function 

**Code**

```ts
export type UserQuery =
  | {
      type: 'User.ById'
      id: string
      __result?: { id: string, name: string }
    }
  | {
      type: 'User.List'
      __result?:  { id: string, name: string }[]
    }
  | {
      type: 'User.TotalCount'
      __result?: number
    }

function publish(query: UserQuery): Promise<typeof query.__result> {
  return Promise.resolve(query.__result)
}

const query: UserQuery = {
  type:'User.TotalCount'
}

// GOOD. here we will get the correct type
type Result = typeof query.__result

// BAD. here we will get all possible options
const result = await publish({
  type: 'User.TotalCount',
})
```

**Expected behavior:**
To infer the correct type based on the instance after function call, the same way it works without function

**Actual behavior:**
Infers all possible options

**Playground Link:** 
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCqBnYUCKBXbROAXgFgAoOOAHzgG8KqmFlgAuOAck2wDoAhRAEkAJp0bM4ASxEcMMKFIB2AcwnMA+hqjAMeADYwA-BzrTZceYtUAaOEoCGAW3aWFylXAC+67xNoMlJJIKBzcWFC8ADJS8uJBmtq6BsYc9OZy7rb2zq5WHt4A2gC6vj5BAb5UIa7hfAAqEDAO+gDCEHhKMPGScFo6eoYm9nhOAEbYZRQUAGadAMYwUhBKcGB4Y-qxABYAFACOBFCIHDy4R4gAlBwAClAQTrHAADw1EDNwh4S8-cmGAHz0CQ6GB4KCrO4PJ68AYQfQAN2ABwuPySgxglwo5Qo8xW8k+F1OEXwhBIQKCNTYdUijWabQ6XXi2PIAHoWXBtthUAB3VAqYDwGCcuC4qA6RYsFAUGpwABKf3gxElwHeBO+v3R01Z7M5OjgvLg-PgLX0awgGAwUk2qAgYCWeJxePgAxSZIc3IcUng602O12gWqrDCZ14tJa7U63RsWMx5AoQA

P.S. This is real use case when building Microservices architecture and will be great to support it

**Comment by MartinJohns** [comment]
// GOOD. here we will get the correct type
    type Result = typeof query.__result

This only works because TypeScript is ignoring your type annotation and uses more type information available, which is not available within the `publish` function. A more realistic comparison would be:

    function getUserQuery(): UserQuery { return { type: 'User.TotalCount' }; }
    
    const query: UserQuery = getUserQuery()

And now the behavior is the same. In this csase, and in the `publish` method, TypeScript simply **can't** know the return type as you want it.

**Comment by playerx** [comment]
Thanks @MartinJohns for the response, It seems I've requested too much from Typescript :)
