### ISSUE TITLE
Can't assign unknown to unknown generic

### ISSUE THREAD

**Issue by ayroblu** [microsoft/TypeScript#41838]
When generic is unknown, I can't assign the unknown to it, ideally I could include the `undefined` in the generic, but I don't see a logical way for that with the existing syntax (please correct me if I'm wrong!)

**TypeScript Version:**  v4.2.1

**Search Terms:**
assign unknown to unknown generic

**Code**

```ts
type Result<T> = {
    first: string;
    p: T;
}
function run<T>(param: {p?: T}): Result<T> {
    if (param.p) {
        return {
            first: 'hi',
            p: param.p,
        }
    } else {
        return {
            first: 'hi',
            p: undefined as unknown, // error here
            // p: param.p as NonNullable<typeof param.p>, // This does work but it's counter intuitive
        }
    }
}
const a = run({p:'hi'});
const b = run({});
a.p
b.p
```

**Expected behavior:**
Be able to assign `p: undefined as unknown,`

**Actual behavior:**
error:
```
Type 'unknown' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.(2322)
```
But `b.p` is type `unknown`

**Playground Link:**
[link here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShDOBXANsAPAFQHxQLxQG8AoKUqAMwEsAneYALijusoDsBzAbhLLEY24BfIuUSsAxsEoB7VlGpjMWABRgAhtTUBbRgTAB+foICUjOElRLCPUpXJRVG7QDowx62U-yIwRNTnEXkEUNHSMAOQAFpThADQ2waR8UOqaWq7xicKeglAQyPDQgcHUPn4BCYlUtAxQUTGZibyMYgAmEFSsEK1QavBQYgDWrNIA7qyNQdlkwsLisnS9ePJiynr09eEm3POsiwBGywqsa9tEaq5E+65AA)

**Related Issues:** 
Sorry if this is a weird expected behaviour or covered in another issue!

**Comment by MartinJohns** [comment]
The type of `b.p` is not `unknown`, it is `T`. And `unknown` is not assignable to `T`. This is working as intended.

If you really want to assign the potentially / likely incompatible value `undefined` you can just use `undefined as any`.

**Comment by ayroblu** [comment]
I don't see why you can't assign unknown which is an arbitrary type too, to T but okay 🤷

**Comment by MartinJohns** [comment]
For the same reason why you can't do this:

    const u: unknown = undefined;
    
    const s: string = u;
    const b: boolean = u;

It's the way `unknown` is designed and intended. It's not compatible with any other type except `any`.

**Comment by MartinJohns** [comment]
And IMO you really should reconsider your approach. You're gonna shoot yourself in the foot if you lie in your type system.

If `Result<T>.p` is not optional, then you shouldn't assign `undefined` to it. If you want to assign `undefined` to it, make it optional.

    const c = run({ p: Math.random() > 0.5 ? 123 : undefined })

In this example the type of `c.p` is `number`, but at runtime it can either be a `number` **or** `undefined`. So effectively the type information provided by the function is wrong.

**Comment by ayroblu** [comment]
Yeah the only way I know to do this is with overloads, but that gets expensive quick so was trying to find a shortcut
In this case, I'm only trying to pass through information as part of an API for a library, so I could simplify it to:

```ts
function run<T>(param: {p?: T}): Result<T> {
    return {
        first: 'hi',
        p: param.p as any,
    }
}
```
