### ISSUE TITLE
Group noImplicit family options same as strict in tsconfig.json

### ISSUE THREAD

**Issue by talohana** [microsoft/TypeScript#41839]
## Search Terms

- noImplicit
- group implicit 
- family implicit

## Suggestion

When I start a new TypeScript project I always turn on the [`strict`](https://www.typescriptlang.org/tsconfig#strict) flag in the tsconfig.json file.

According to strict flag docs:

> Turning this on is equivalent to enabling all of the *strict mode family* options

Often I find myself turning on multiple *noImplicit family* flags such as:

- [noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny)
- [noImplicitThis](https://www.typescriptlang.org/tsconfig#noImplicitThis)
- [noImplicitReturns](https://www.typescriptlang.org/tsconfig#noImplicitReturns)

Grouping them together under a `noImplicit` flag will help turning them and future noImplicit flags all at once.

## Use Cases

Enabling all current and future noImplicit family flags using a single flag.

## Examples

```diff
// tsconfig.json

{
-    "noImplicitAny": true,
-    "noImplicitThis": true,
-    "noImplicitReturns": true,
+    "noImplicit": true,
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
That would be confusing, because `strict` already enables `noImplicitAny` and `noImplicitThis`.
