### ISSUE TITLE
Outdated diagnosticMessages for JSX flag

### ISSUE THREAD

**Issue by ntnyq** [microsoft/TypeScript#41845]
https://github.com/microsoft/TypeScript/blob/bf977ed9189d2f795930366c1baa2cfcab123e1e/src/compiler/diagnosticMessages.json#L3913

It should be replaced by `Specify JSX code generation: 'preserve', 'react', 'react-jsx', 'react-jsxdev' or'react-native'`

**Comment by ikishore** [comment]
I checked the issue, will submit the PR today. Thanks for labelling as "Good first issue"
