### ISSUE TITLE
Type-only imports in d.ts files

### ISSUE THREAD

**Issue by just-boris** [microsoft/TypeScript#41844]
## Search Terms

type-only imports, d.ts declarations, compatibility

## Suggestion

Strip `type` from `import type` expressions when writing `.d.ts` files. This would improve backward-compatibility for the new syntax.

## Use Cases

As a library author, I want to use type-only imports to avoid unnecessary imports in runtime. However, for backward-compatibility reasons, our types should remain working with older TypeScript versions. Currently `import type` requires all consumers to be on at least 3.8. The change will allow supporting other versions too.

As I understand correctly `import type {something} from 'something'` and `import {something} from 'something'` are practically the same in the context of `.d.ts` declarations. Hence it would be great to convert such statements to more widely supported syntax, giving library maintainers better control over the output Javascript without bumping their major version.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
@andrewbranch thoughts?

**Comment by andrewbranch** [comment]
I can‘t think of a downside to this

**Comment by RyanCavanaugh** [comment]
OT but if you have a forward-compat constraint, `downlevel-dts` is the recommended tool for making current-gen .d.ts files work on older versions, and will handle more cases that will surely arise in the future.

**Comment by andrewbranch** [comment]
Update: team members pointed out that it matters for library authors who use type-only exports or reëxport things that were type-only imported. That could be a legitimate signal that the value side of the symbol is _not_ available at runtime, so the error a consumer would get from using that export in an emitting position is important, and would be lost if we elided the `type` keyword in declarations.
