### ISSUE TITLE
spreading class results in type with `prototype` key, which is not present in runtime object 

### ISSUE THREAD

**Issue by Enteleform** [microsoft/TypeScript#41842]
**TypeScript Version:**  4.1.2

**Search Terms:**
spread class static property prototype

**Code**
```ts
class Foo{
  static bar = 123
  baz = 456
}

const FooProps = {...Foo}
// typeof FooProps === {
//   prototype: Foo
//   bar: number
// }

console.log(FooProps)
// { bar: 123 }

console.log(FooProps.prototype)
// undefined
```

**Expected behavior:**

```ts
typeof FooProps === {
  bar: number
}
```

**Actual behavior:**

```ts
typeof FooProps === {
  prototype: Foo
  bar: number
}
```
**Playground Link:** 
https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28DeAoa0IBcyYJbGgCMwAnaAXmgEYAmAZjSLAC8LoAWAVgDYUBfFCmDwAdljiIACiXgAHGJSQA6FQngCA9BuiYAnrICm8AGYT40uQvKKUW9NFkzM8PYYBcZ29vTESHkQCuALaEBiRe0AJCohDwIAZKIPAA5gAUahbyAJQRSEx+1PSRgsJicQlJaRky8kqOLi76Bjl2ASIAJgbGuCIG7ShAA

**Comment by RyanCavanaugh** [comment]
Duplicate #9726
