### ISSUE TITLE
Overloads error for lambdas that take lambdas with varying params

### ISSUE THREAD

**Issue by ayroblu** [microsoft/TypeScript#41840]
Hey, sorry about disturbing!

**EDIT**: Made example clearer

**TypeScript Version:**  v4.2.1

**Search Terms:**
error overflow lambda

**Code**

```ts
type Result = {
    first: string;
}
type ResultWithSecond = {
    first: string;
    second: string;
}

// Basic case works
type IFirst = {
    (): (param: {}) => Result;
    (): (param: {p: string}) => ResultWithSecond
}
const createFirst: IFirst = () => (param: {p?: string}) => {
    // An unfortunate possible solution, which may cause side effects if doing spreading operations
    // return param.p ? {first: 'first', second: 'second'} : {first: 'first', second: 'null'};
    // What I would like to do, but I can't, which makes sense, though the above is still unfortunate
    // return param.p ? {first: 'first', second: 'second'} : {first: 'first'};
    // Workaround for it might be:
    return param.p ? {first: 'first', second: 'second'} : {first: 'first'} as any;
}

// My case
type IFirstWithFunc = {
    (): (func: (param: {}) => string) => Result;
    (showP: boolean): (func: (param: {p: string}) => string) => ResultWithSecond
}
const createFirstWithFunc: IFirstWithFunc = (showP?: boolean) => (func: (param: {p?: string}) => string) => {
    if (showP) {
        return {
            first: 'first' + func({p: 'someparam'}),
            second: 'second',
        }
    } else {
        return {
            first: 'first' + func({}),
        }
    }
}
```

**Expected behavior:**
No error on runFn, same as runNormalFn, as it appears that overloads are supposed to be flexible

**Actual behavior:**
Error on runFn, not fixable by casting the return to any, I must change the `param: {p?: T}` to `param: any` for it to pass

**Playground Link:** 
[link here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShDOBXANsKBeKBvAUFfUAZgJYBO8wAXFBacQHYDmA3DgL46iSwIrADqxYAAsAyhADGAe3oATDNjwES5KjWB0mrAjUkzZ1WgxbscOAPTmoAIQCG8YhKgT70AO5TSAa3idw0AEkAMTIKBVwdAAoASmpIsFtSWwBbaiw2aIwAPh4kVG0CGLiEpNTsMEMNYwzs3L5BEXFpOVNmsIlSCFtgCBDVamDQtEwY2vjElLSwAH5KzUYa9ByIgksoAEF6KER6Qk9gHe7oMCl4BwAjZGh4KWREYGIZABooN2FHYShk2xBnW0R4NdiLJoBBCIRJMB4FBiIQoLIpMYaGBOrZZEipJAkg8ZL4dGtOgdSFsSikAHRgKDTbAqCjUADktOA9JegOaBig9LZ+npbCgaSZDKZLN07IZ9BQyF5BXwa34wm6UACrykKHkyGIXmgwCk8KkL3O9yVf3o9OALzeHy+ti10MB9EBLxEqsYnxE0Fs5ykADdoMQ7Q9kMhtrt9ocekpZVZCYhiVBSckKVSaUMhUMRdy5AzM7JefyU-1OcK2DKoHLPF5Eqq5ERPDC0MliK60OcIJRI1AY3GE0nqVhBUX06y9FnOTm8wLU4PVHn7FBbPQQKwOBYrABZX4uQF+biDVQNYRBHZOTArfBFKCRQjH4oTMrpTJLdTzR85OB5YClyLwYRSNwABWoL1bi6ehYkva96AkW9SimOZqlfZ9jEQ996iEMQR1kVpcTQDouh6PoKAPI8oIGQiBHQkiT0vH8-3-WYoGAq4F0Qq8b0vBMpgYowmEWHIeMYRCzxhOFv1-ADMmEnQuy2KSdGUKdGXTKAAGoiGPSIsAqMcpGSCAE15aIng7eSCBzbNMJZEyCA4HQ+QgZBAUUUz8Bk5yXJ0AclJnVT1KgzSMmMjzbJs9ggA)

**Related Issues:** 
Sorry if this is a duplicate of another!

**Comment by jcalz** [comment]
This example is confusing because `Result<T>` is not dependent on `T`, and  your implementation never even calls the `func()` callback that's passed in.  These issues make it so that it's hard to tell what the intent of the code is.  In any case, consider this implementation instead, which has the same typings as your code:

```ts
const runFn: Irun = <T extends {}>() => (func: (param: { p?: T }) => string) => {
    func({}); // you should be allowed to do this if p is truly optional in param
    return {
        first: 'hi',
        a: 'hi',
    }
}
// but then the following happens
runFn<number>()(x => x.p.toFixed()); // no compiler error, but x.p is undefined at runtime
```

This demonstrates that the call signature of `runFun`'s implementaion does not, in fact, satisfy the `Irun` call signatures.  If you change the call signature so that `p` is not optional in `param`, the error goes away and you are no longer allowed to call `func({})`:

```ts
const runFnBetter: Irun = <T extends {}>() => (func: (param: { p: T }) => string) => {
    func({}); // now this is an error
    return {
        first: 'hi',
        a: 'hi',
    }
}
```

So I don't see any evidence of a bug here; it looks like things are working as intended.  

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShDOBXANsAPAFQHxQLxQG8AoKUqAMwEsAneYALijusoDsBzAbhLIENHmbLkQC+RUJCgBlSgFswyCHCSo8hHqSq0GTYCw7cxRAPTGoAIV7xKAYyg2r0AO4B7agGt448NACS1RFYAOTdZXmQ1YjIoAAoASkYYsF5qXllGAhE4vBwZeUVlFGBuaMwseMTk1PTCKDBGDCgsnNgEIrLRIhsXVjooAODQ8IAxVkZ-QJDqMIj8TCgIAA9gCFYAE3hCEXLs3BwklLSMuoB+BqbdnCiyaghgRGpWdWjorTpGAHIAC0oPgBoNC9+FBvr8AdExEZTFAALIgeyObySCZPfDXUgVWLkQI2SqHGqZS66fTsIl5BRKNqoEpkMqYmLY1i42JVI61epQRrNPbEoREwqoDpGLo9PoDUbjAZqeZLFbrTaZHYtBk4vHVY5gM6ci4tQQcInoig4mKEmmkW73R7PF6aGjvEE-f6A6LA0FOiGdIji1hoViIWQAIwg1B2MUWLUWADowJHgC5hpRFhA1vE4pwoNDg9Q3FBeMB+oFgHIIH8oFGwFBKJtAmsIFRWMmiE3ur1897zHcVtRJYFpY1ZasNlslTyVUy1WyCHVztycHrSS1DYybCasunoawXE4oMAfpsq7mnlm3ICLQ8nobXnadG7wTbc59HXfSJCm0A)

**Comment by ayroblu** [comment]
You're right, I'm sorry I didn't give it that much thought, here's a more intentional piece of code with most of the junk removed

The key confusion here is that in `createFirst`, that it "narrows" the type, but in `createFirstWithFunc` it's "widening".

After refactoring the code the boundaries of the type system are clearer. Apologies for the issue.

```ts
type Result = {
    first: string;
}
type ResultWithSecond = {
    first: string;
    second: string;
}

// Basic case works
type IFirst = {
    (): (param: {}) => Result;
    (): (param: {p: string}) => ResultWithSecond
}
const createFirst: IFirst = () => (param: {p?: string}) => {
    // An unfortunate possible solution, which may cause side effects if doing spreading operations
    // return param.p ? {first: 'first', second: 'second'} : {first: 'first', second: 'null'};
    // What I would like to do, but I can't, which makes sense, though the above is still unfortunate
    // return param.p ? {first: 'first', second: 'second'} : {first: 'first'};
    // Workaround for it might be:
    return param.p ? {first: 'first', second: 'second'} : {first: 'first'} as any;
}

// My case
type IFirstWithFunc = {
    (): (func: (param: {}) => string) => Result;
    (showP: boolean): (func: (param: {p: string}) => string) => ResultWithSecond
}
const createFirstWithFunc: IFirstWithFunc = (showP?: boolean) => (func: (param: {p?: string}) => string) => {
    if (showP) {
        return {
            first: 'first' + func({p: 'someparam'}),
            second: 'second',
        }
    } else {
        return {
            first: 'first' + func({}),
        }
    }
}
```

Playground: [link here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShDOBXANsKBeKBvAUFfUAZgJYBO8wAXFBacQHYDmA3DgL46iSwIrADqxYAAsAyhADGAe3oATDNjwES5KjWB0mrAjUkzZ1WgxbscOAPTmoAIQCG8YhKgT70AO5TSAa3idw0AEkAMTIKBVwdAAoASmpIsFtSWwBbaiw2aIwAPh4kVG0CGLiEpNTsMEMNYwzs3L5BEXFpOVNmsIlSCFtgCBDVamDQtEwY2vjElLSwAH5KzUYa9ByIgksoAEF6KER6Qk9gHe7oMCl4BwAjZGh4KWREYGIZABooN2FHYShk2xBnW0R4NdiLJoBBCIRJMB4FBiIQoLIpMYaGBOrZZEipJAkg8ZL4dGtOgdSFsSikAHRgKDTbAqCjUADktOA9JegOaBig9LZ+npbCgaSZDKZLN07IZ9BQyF5BXwa34wm6UACrykKHkyGIXmgwCk8KkL3O9yVf3o9OALzeHy+ti10MB9EBLxEqsYnxE0Fs5ykADdoMQ7Q9kMhtrt9ocekpZVZCYhiVBSckKVSaUMhUMRdy5AzM7JefyU-1OcK2DKoHLPF5Eqq5ERPDC0MliK60OcIJRI1AY3GE0nqVhBUX06y9FnOTm8wLU4PVHn7FBbPQQKwOBYrABZX4uQF+biDVQNYRBHZOTArfBFKCRQjH4oTMrpTJLdTzR85OB5YClyLwYRSNwABWoL1bi6ehYkva96AkW9SimOZqlfZ9jEQ996iEMQR1kVpcTQDouh6PoKAPI8oIGQiBHQkiT0vH8-3-WYoGAq4F0Qq8b0vBMpgYowmEWHIeMYRCzxhOFv1-ADMmEnQuy2KSdGUKdGXTKAAGoiGPSIsAqMcpGSCAE15aIng7eSCBzbNMJZEyCA4HQ+QgZBAUUUz8Bk5yXJ0AclJnVT1KgzSMmMjzbJs9ggA)

**Comment by ayroblu** [comment]
The reason why `createFirst` allows the optional param can be illustrated in this piece of code:

```ts
type A = () => void
type B = (a: boolean) => void
const a: A = () => {}
const b: B = () => {}
const aOpt: A = (a?: boolean) => {}
const bOpt: B = (a?: boolean) => {}
const aReq: A = (a: boolean) => {} // error here
```

This all makes sense, thanks so much for the explanation!

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UAUBKBA+KA3A9gSwBMAoUSKAIQWQEMAuKAIxxwBsJqA7NeTXQogMY4OAZ2BQ6sKqgxQA3gF9BwsY3qVEMnvKVDR46gHkwwenE3UA-PSat2XWYuX7Gx0xWlWbzNp26YnPVVqACUIAEczT287P0cFIA)
