### ISSUE TITLE
Values of array passed as parameter can't be used to infer the return type

### ISSUE THREAD

**Issue by ericmorand** [microsoft/TypeScript#41859]
Not sure if this is a bug or an expected behavior so please forgive me if this does not belong here.

I'm trying to create a factory that guarantees that the object it returns have certain properties, whose names are passed as parameters:

```ts
const foo = fooFactory(['id', 'name']); // returned object is guaranteed by the type checker to implement the interface {id: string, name: string}
```

It's possible with the latest flavors of TypeScript by using something like this:

```ts
const fooFactory1 = <P extends string>(keys: ReadonlyArray<string>): Record<P, string> => {
    return; // noop for the sake of example
}

const keys= <const>['id', 'name'];

const foo1 = fooFactory1<typeof keys[number]>(keys); // inferred type of foo1 is Record<"id" | "name", string>, as expected
```
But it seems like trying to infer the return type from the type of the parameter passed to the function instead of explicitely, like above doesn't work:

```ts
const fooFactory2 = (keys: ReadonlyArray<string>): Record<typeof keys[number], string> => {
    return;  // noop for the sake of example
}

const foo2 = fooFactory2(<const>['id', 'name']); // inferred type of foo2 is Record<string, string>
```

From my understanding, the two approachs should be analoguous: in the first case, the return type is inferred from the values of the `keys` array _passed_ as parameter, in the second case it should be inferred from the values of the `keys` array _received_ as parameter.

Obviously the second approach is less verbose and doesn't require that the `keys` array is instanciated before being passed as parameter, so I hoped it would work.

Am I doing anything wrong? Is it simply not supported? Or is it a bug?

Thanks by advance.

**Comment by RyanCavanaugh** [comment]
Reasonable question; the difference you've outlined here is exactly the difference between a generic and a non-generic function. In `fooFactory2`, the type `typeof keys[number]` refers only to the *parameter declaration*'s type, whereas in `fooFactory1`, `P` refers to the type of the argument as passed during the call. That's what makes a generic function generic: resolution of types is deferred to each call site, rather than being statically resolved.

**Comment by ericmorand** [comment]
Make a lot of sense. Thanks for the clarification.

**Comment by ericmorand** [comment]
@RyanCavanaugh , actually writing the factory like this gets the job perfectly done:

```ts
const fooFactory = <P>(keys: Array<keyof P>): Record<keyof P, string> => {
    return;  // noop for the sake of example
}

const foo = fooFactory(['id', 'name']); // inferred type of foo is Record<"id" | "name", string>
```

Looks like `P` is inferred by the fact that `keys` are known to be an array containing only the keys of `P`. I have to say that my mind is blown by how smart type inferring is.
