### ISSUE TITLE
tsconfig picks all sibling files of the file specified in the “include” option

### ISSUE THREAD

**Issue by anotheruser584** [microsoft/TypeScript#41856]
**TypeScript Version:**  4.1.xx

**Search Terms:**
 tsconfig checkjs 

I'm using typescript to check JS project for errors. Also I'm utilizing the TS build step to check the cases when change in one file resolved to an error in another Here is my folder structure:
```
|-tsconfig.json
|-src
|---app
|-----app.js
|---components
|-----somecomponent.js
```
my tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "outDir": "./dist",
    "strict": true,
    "types": ["mocha", "node],
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/components/somecomponent.js"]
}
```
So first issue is (and it look like a bug to me):
TS is checking ALL files inside `src` folder despite I told to include only `"src/components/somecomponent.js"`
I tried to change it to `"files": ["src/components/somecomponent.js"]` - no luck.

Second issue (and I believe it comes form the first one):
when i run `"node_modules/.bin/tsc --p tsconfig.json"` (just `"node_modules/.bin/tsc"`) is compiles ALL files inside `src` folder (both `app` and `components`).

My first guess was that my `tsconfig` is ignored...
But when I change something in tsconfig (let's say, I'll remove `types: ["node"]`) VS Code picks up changes and start immediately complaining about missing `@type/node`

When I'm adding new folder in root of the project, let's say a `foo` folder with `bar.js`:
```
|--tsconfig.json
|--src
|----app
|------app.js
|----components
|------somecomponent.js
|--foo
|----bar.js
```
It (the `foo` folder and it's files) is totally ignored by TS (and VSCode intellisense as well) - **and that's what I'm willing to do inside `src` folder.**

Also I tried tsc `--showConfig` and it shows completely correct config (only `"src/components/somecomponent.js"` are included).

**Expected behavior:**
TS should compile (and check) files that are only specified in `include`/`files`
**Actual behavior:**
TS compiles/checks ALL files that are under the first folder specified in the `include` option (siblings or a deeper nested files)

**Comment by MartinJohns** [comment]
Are you importing other files from your `somecomponent.js`?

**Comment by anotheruser584** [comment]
@MartinJohns Yes I do. And as soon as I remove any imports in `"src/components/somecomponent.js"` it compiles **only** this file. Thanks for the clarification. This issue can be closed, but I would really appreciate some links with some more info on this, because I swear I read lots of FAQ etc. Such a shame...

**Comment by RyanCavanaugh** [comment]
FYI you can turn on `noResolve` if you want `import`s to not be followed
