### ISSUE TITLE
Array spread results in incorrect type of array item properties of enum member type

### ISSUE THREAD

**Issue by zuzusik** [microsoft/TypeScript#41863]
**TypeScript Version:**  4.1.2

**Search Terms:** array spread, spread operator, TS2322

**Code**

```ts
const enum EArrItemProp {A = 'a', B = 'b'};
type Arr = Array<{prop: EArrItemProp.A}>

const arr : Arr = [
  {prop: EArrItemProp.A}, // this works
  ...[{prop: EArrItemProp.A}], // this fails, but is basically identical to prev line
]
```

**Expected behavior:**

No errors.

**Actual behavior:**

Error TS2322 on spread operation:
```
Type '{ prop: EArrItemProp; }' is not assignable to type '{ prop: EArrItemProp.A; }'.
  Types of property 'prop' are incompatible.
    Type 'EArrItemProp' is not assignable to type 'EArrItemProp.A'.
```

**Playground Link:**  [click](https://www.typescriptlang.org/play?ts=4.1.2#code/MYewdgzgLgBApmArgWxgUQIICcsEkpzIAKWIADjAN4YwC8MA5AIYMA0MAQnYwEYMC+AbgBQUAJ5k4MbFm4ymYgDyUypMgC50M-IRLkAdBn4A+YcNCRYTHDE0zuAbWEwqq8psw4dxNYf7sAegCYKAALAEsIGAB3ECwAawhnGH1UhxU1D20CHwMjAF1A4LDImAAzJnCAGwh2HkRYUp4mCHDgJiqqsRhwgBMEKDaOkJAYVTgANxgq8LA4YXygA)

**Related Issues:** 

**Workaround:**

```diff
- ...[{prop: EArrItemProp.A}]
+ ...[{prop: EArrItemProp.A as EArrItemProp.A}]
```

looks ugly, but works

**Comment by MartinJohns** [comment]
Use `...[{prop: EArrItemProp.A} as const]` to prevent widening of the type.

**Comment by zuzusik** [comment]
@MartinJohns thanks, that works as workaround too!

But generally it would be nice for it to work just out of the box

**Comment by RyanCavanaugh** [comment]
We need to widen at least sometimes for things to work out correctly, and this is one of those places. It's a little weird, but there's also no real reason to write the expression that way.

**Comment by zuzusik** [comment]
> but there's also no real reason to write the expression that way.

I wouldn't agree with this - we recently encountered this in our code base on a very much real code:

* we do have array of items inherited from one base class, but depending on type field they have other additional fields
* that type field is an enum
* some items in array should be there conditionally and so to form the whole array in one place we do something like this:

```ts
const arr = [
  {type: Enum.t2, /*...*/},
  {type: Enum.t1, /*...*/}
  ...(
    condition 
     ? [{type: Enum.t3, /*...*/}] // fails here
     : []
  ),
  {type: Enum.t5, /*...*/}
];
```
