### ISSUE TITLE
New Website Logo: Vanamco

### ISSUE THREAD

**Issue by vanamco** [Microsoft/TypeScript#4186]
Please fill the following out:

- Name: Vanamco
- Homepage url: http://www.vanamco.com/
- Brand Guidelines/Licensing: feel free to use it!
- Logo: http://www.vanamco.com/var/vanamco-logo.svg

We're now using typescript throughout all our projects, notably Ghostlab, a web and mobile developer and tester tool (vanamco.com/ghostlab).

Thanks for adding us! 
If you have any questions please get in touch at mueller@vanamco.com

Cheers
Florian

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by vanamco** [comment]
Hey Jonathan,
do you have everything you need from our side?

Thanks!
Florian

**Comment by RyanCavanaugh** [comment]
Yep! We do website logo additions in batches so this should get picked up in the next update.

**Comment by vanamco** [comment]
Thanks for the update!

2015-08-26 19:11 GMT+02:00 Ryan Cavanaugh <notifications@github.com>:

> Yep! We do website logo additions in batches so this should get picked up
> in the next update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/4186#issuecomment-135110771>
> .
>



-- 
Vanamco AG
Florian Müller
f.   +41 (0)44 586 77 70
m. +41 (0)78 662 90 10

Technoparkstrasse 1
8005 Zürich
http://www.vanamco.com
