### ISSUE TITLE
Please take the 2023 repo experience survey!

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#41866]
A couple years ago we surveyed you, the members of the community in this repo, to learn how we we're doing as maintainers.
It's time to repeat the same survey. Whether you've been involved for years or you're relatively, new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos.

[2023 Repo Survey Here](https://www.surveymonkey.com/r/8KTX9VT?Source=RepoLink)

**Comment by RyanCavanaugh** [comment]
The survey is now closed

**Comment by RyanCavanaugh** [comment]
There's a new survey!

**Comment by fatcerberus** [comment]
> There's a new survey!

I almost didn't see this comment because I stopped reading at "The survey is now closed" followed by several moderation messages.  I was about to reply asking why this got pinned now when the survey closed months ago...

**Comment by DanielRosenwasser** [comment]
There's a new survey for 2023!

**Comment by RyanCavanaugh** [comment]
The 2023 survey is now closed
