### ISSUE TITLE
Infer type construct signature and infer type parameter signature

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#4187]
I know that you only contextually type values.

But it hurt my finger when having to type the signature of a construct when it could be contextually typed:
```typescript
function(a: new<P extends Props, S, E extends Elements>(props: Props, children: Child[]) => Component<P, S, E>)) {
}
```
It also hurts my fingers when I have to redeclare the type parameters if they should just be the same. Why can't all of the above be written as:

```typescript
function(a: new => Component) {
}
```
We infer the construct signature and we also infer the type parameter signature.

**Comment by OlegDokuka** [comment]
it will be cool if provide somesing like Class in java where we can declare it like Class or Class<any> 

I `v provided it yet but only Class type 

```
module Typejector.Type {
    export type Class = { new (): any };
} 
```

but in this way we lost 

``` 
Class<any>

``` 

of course we can do something like 

```
module Typejector.Type {
    export interface Class<T.> { new (): any };
} 
```

but it is not that we realy want

**Comment by xLama** [comment]
Due to structural typing it is very easy cheat compiler.

```
module Type {
     export interface Class<T> { 
     new (...a:any[]): T }; // To let constructor parameters
} 
class A{}
class B{}

function foo ( bar:Type.Class<A> ) {}
foo(B) } // Ok

```

**Comment by mhegazy** [comment]
Type aliases should be useful in such circumstances. adding a new syntax adds complexity that is not matched by the value gained from this proposal.
