### ISSUE TITLE
Intersection of arrays

### ISSUE THREAD

**Issue by gregoirechauvet** [microsoft/TypeScript#41874]
## Search Terms

intersection array

## Suggestion

Intersections of arrays are weird in my opinion. In TypeScript 4.1, only the first part of the intersection is considered. I think TypeScript should merge the array types, it would be especially convenient for objects:
```ts
type A = { a: string }[];
type B = { b: number }[];
type C = A & B;

// Behaves like
C = { a: string }[];

// Desired
C = { a: string, b: number }[];
```

[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgNoC6A3AFCiRQBCCyUARpoQK4C2HCLnLV6jaAGE2cAGQt6dAMYB7QjiiLMUxKKUA6PqjAAKAB4IAfFFN7UAShpQA9E7RQIp-Diz7DJ8-BWNhwOzq4cUAAmyhBYhADkwHQM4NAAomw4BCS64lAAYmy8AkK5qVAA4mwZcvn0KmrAUMSYVTq0dMQGRmaW1qEu1lBebllEpAAWQtBAA) to try it out.

## Use Cases

I want to be able to cherry-pick some paths from an interface. I have an Elasticsearch cluster and a TypeScript interface for the shape of the documents in the cluster.
With Elasticsearch, I'm able to retrieve only some values with their paths.
```ts
// With some documents of the following shape:
interface Post {
  id: string;
  views: number;
  comments: {
    id: string;
    content: string;
    author: {
      id: string;
    }
  }[];
}

// And a list of source fields
const sourceFields = ['id', 'comments.id'];

// When we do the query with these source fields, at runtime we only have a subset of the interface, like this:
{ id: '1', messages: [{ id: '1' }] };
```

Using features introduced in TypeScript 4.1 I'm able to generate a type based on the interface and the source fields. And it works almost perfectly except for arrays. While it works fine with nested objects, and nullable and optional keys.

Usage:
```ts
// Source fields are known at build time
const sourceFields = ['id', 'comments.id'] as const;

type ActualPost = PartialObjectFromSourceFields<Post, typeof sourceFields[number]>;
/* ActualPost behaves like
{
  id: string;
  comments: {
    id: string;
  }[];
}
*/
```

`PartialObjectFromSourceFields` declaration:
```ts
type ExtractPath<Obj, Path extends string> =
  Obj extends undefined ? ExtractPath<NonNullable<Obj>, Path> | undefined :
  Obj extends null ? ExtractPath<NonNullable<Obj>, Path> | null :
  Obj extends any[] ? ExtractPath<Obj[number], Path>[] :
  Path extends `${infer FirstKey}.${infer OtherPath}`
  ? (FirstKey extends keyof Obj
    ? { [k in FirstKey]: ExtractPath<Obj[FirstKey], OtherPath> }
    : never)
  : Path extends keyof Obj
    ? { [K in Path]: Obj[Path] }
    : never;

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never;
type Distribute<Obj, Fields> = Fields extends string ? ExtractPath<Obj, Fields> : never;

export type PartialObjectFromSourceFields<Obj, Fields> = UnionToIntersection<Distribute<Obj, Fields>>
```

But because of the limitation on array intersection, as soon as 2 paths on an array key are used, only the first one is considered:
```ts
const sourceFields = ['id', 'comments.id', 'comments.content'] as const;

type ActualPost = PartialObjectFromSourceFields<Post, typeof sourceFields[number]>;

// ActualPost is in fact:
{ id: string } & { comments: { id: string }[] } & { comments: { content: string }[] };

// And `content` cannot be accessed inside `comments`, only `id` is available
```

[Playground demo](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogHsATgQwMbAArOACwDwDyARgFYA0UWuUECEAdgCYDOUzSAlvQOYB8UAXgBQUKMRI06TVgFcmEAGZcIjKAH5YCFOir4AcgHt6emQBtTyIqYiFSvCrv4AfKHMaLlqgFwixpScAMLFD0ZqbqmkhomNj6Ribmlta2JPaUsc4hYVA+ouIBQazI9CAA2gC6EfBROrEppaEAtkQQiOUOGRU5vroF0lAABgAkAN5cCq1QAGIciOwA0hAgAL4AdKPjkwS4rbrLA74aABQzc8CLIH3BANZLBgp+JL6iGiNQpddQXNOzC0vlXki2hiuHqpz+IHaYh2iEcUGWzxyIQgADdWgBKXyA3q0QL9W4ge6PRGvd7zL70dK4AGPUq6SoI0SiQH0VGtADcQiEoEgUAAqvQOEYACoGACS9ECcwg6CF9DwfP4AigRz5VyKJQiR2ugL56ME-BRBg43mRaMQ+txhRV2sBm0QUDF+oEhuNjH1GjFSNZ5s5POgABEOOxEBwiDJAikKDMIKYWEqfrHglb+iGuNwqlporoo4m48x+Cy2YhOUJaGADIhgFB-ekqxxkKZxDLgFNEAZGgBlAwyRCoCAx-O5wfxwT8wUi8WS1rMFtyvBBtPhyPiaMcJMF3hcgD02-5zGQ3AgXK4UoUaGgGAM7CgI18JsBaZ4nNEKPXAHdmCyZM0Ob5UB2jQMMAX63oiD5sJwz6IgB06So+UHcC+TLIBGOCVoCd5MkyEFPkhiKMvCFScgiXKwTezA9n2A7rvmY6lAA5CaDEUAxAGNEBkrMKszGsexnEgassF4sADGVMgrDkcAfrgNAACC6AyI2V43sqWD1o2zboG2Hbdr2-YjsweAqcAFD+kSlH6TRG4ND+LRtLwpbWNWyCAgpwBKaYJmcsgACEQmAcB3GNMgYBHHABpQHAAVwcA6LslAu5QMJwFQIwBgQMw9AMdWtDBsAQA)

## Examples

I think the same merging rules should apply as without arrays:
```ts
type A = string[] & number[];

// Behaves like
A = string[]

// Desired?
A = never[];
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I don't know if it would be a breaking change :thinking:  I wonder if it might conflict with this behavior https://github.com/microsoft/TypeScript/issues/38348

**Comment by jcalz** [comment]
Related to #39693

**Comment by RyanCavanaugh** [comment]
Array intersection is weird since there are many invariants of arrays and many invariants of intersections that can't be simultaneously met. For example, if it's valid to call `a.push(x)` when `a` is `A`, then it should be valid to write `ab.push(x)` when `ab` is `A & B`, but that creates an unsound read on `(A & B)[number]`.

In higher-order the current behavior is really the best we can do; in zero-order it's really preferable to just write `Array<A & B>`, `Array<A> | Array<B>`, or `Array<A | B>` depending on which you mean to happen.

**Comment by TRCYX** [comment]
This seems to also affect readonly arrays, though they do not allow mutations like push.

**Comment by kasamachenkaow** [comment]
@RyanCavanaugh Does the `Design Limitation` means it's not gonna be fixed?

**Comment by RyanCavanaugh** [comment]
> Does the Design Limitation means it's not gonna be fixed?

Basically, yes.

**Comment by kasamachenkaow** [comment]
@RyanCavanaugh I see, thanks for clarification!

although I have 2 more questions:
1. Why the issue is still open though?
2. Why there is no `bug` tag attached to this issue 
(since if you access thru `arr[0]` you get both `a` and `b` but get only `a` in the map function?)

**Comment by kasamachenkaow** [comment]
@RyanCavanaugh Thanks for the answers

**Comment by kasamachenkaow** [comment]
I find the workaround way to solve an issue
I created `ArrayIntersect<T1, T2>` like [this](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAggTnAhiAkgO2BOBnCBjYAHgBUBGAGimICYA+KAXigCgorSoIAPTNAE2xQASvgD2cPoQCWaAGZYoAVQDSEEBSgBXNAGs0ogO5p6AfhZs2NTjwj9BIvOMkz5cJapDVKLhYoBqiAA2dFAmrBZsKmrU1rwC7mocYRERANpkqVGeALqU-kHU2bG28akAFD5uimQAlKm5UBVyvjR12UXJKREA8gC2UkRkeR4hAGRQfQMkXgme9OMOToRZM2XwSKgYWLgEy0NKNLRttABc4V1sk4MaK-MT-YMzt1ALYhLLI5TryOiYOPjXTIjBr5YK0U7nFJkF5UahnLrQ8Y0eEWRGw5jMUCQYQwDhMRbvADkQlIhMo2GAcBkAHNaJjwNAhDAYvi3pJidQyVAKVS0LT6dimQBmRjCNmEQmUxADbBcgnsvCIMDATRwCCyyjyiVCIVcnk02j1cECxkwAAsoq1kqQMrl4sJiuVqvVdscRKEZr1lINRrpWNNAFZLfapbbNfbHSq1RqxW72UIA17ebTfSaqLjg3GJaHgDGrVK0NhEAQpKI0K6loSyEmfdljf70yzY5Wc3mQ0hC8XgKXy+Gs1XOeTvXzDXW6WmADKiURgX7bAEkehMcLEYp2KCpSpKDRbxQzAB0h932A6UCnM7n-12qW+mz+OyIihudEoh-3ihP9BO5ioa9Kx9PD8oG-NAIAANywDEGxgIRRXPWctivIhUiZDQmRmYVKGIXFNXNXCAyw5k6wxRxC2AKBEDgb8YNFABvcISW-QkNQYuEoGYslwlbb96IiSNnWwb9Ul4lIdSYliug9cTOMkgNpPISEAF9ckhAsixLMshJEiIyHkyFLDYjiFIiZTwkUhTFIxSj91bfd+OjVIAAZsn3HVmGs2z7PVJyXI9dy4Bsm1czspUo285zXIDfzAulYKvOwfdeiVMo3AYegAp1F5xgyi1RmyyKaisgLbLUrsex8-cyGikqO3U7sywqmhqqChLSo0tBEuS8i0qgYBKo4PLesq6hCqAA) 

hope it helps someone who needs the same use case like mine

**Comment by gregoirechauvet** [comment]
@kasamachenkaow awesome! It's exactly what I was looking for :partying_face:

**Comment by lindapaiste** [comment]
I found this issue while searching for a problem that I am having with refining the type of an array.  Your examples showed me that **the order matters**, which is wild.  I never would have thought that the order of an intersection type would make a difference!  I was able to fix my particular error by swapping the order of `BroadType & { values: string[] }` to `{ values: string[] } & BroadType`.

```
interface BroadType {
    values: (string | boolean)[];
    // Has a bunch of other properties in the actual use case.
}

const badFunction = (input: BroadType & { values: string[] }) => {
    // Error because `term` has type `string | boolean`.
    return input.values.map(term => term.toLowerCase())
}

const goodFunction = (input: { values: string[] } & BroadType) => {
    // This is fine, `term` has type `string`.
    return input.values.map(term => term.toLowerCase());
}
````

**Comment by jcalz** [comment]
cross linking #50346 and #53355
