### ISSUE TITLE
Compiler API: expose path of output files without emitting

### ISSUE THREAD

**Issue by sguillia** [microsoft/TypeScript#41875]
## Search Terms

tsc compiler api out file path resolve js file

## Suggestion

Given the path of a `tsconfig.json` and the path of a `.ts` file, I'd like to programmatically obtain the absolute path of the corresponding `.js` file is the emit had succeeded, and without emitting.

## Use Cases

My current implementation looks like this (using ts-morph). It emits, in order to get the .js file path.

```ts
const sourceFile = this.fakeProject.createSourceFile(tsFilePath, "", { overwrite: true })
const output = sourceFile.getEmitOutput({})
const [file1, file2] = output.getOutputFiles()
console.log(file1?.compilerObject.name)
```

I'm passing an empty file as well as `--noResolve` to speed up the useless emit, but it still takes about one synchronous second.

I'd like not to recode a tsconfig.json reader just to deduce where the js file lives. This would not be maintainable.

My use case is an IDE extension that runs the output files for the user. But in order to run them, and to check whether they exist, you have to know where they are

## Examples

Any compiler API is fine.

```ts
const sourceFile = program.getSourceFile(file);

console.log(sourceFile.getOutFilePath())            // .js
console.log(sourceFile.getOutFileMapPath())         // .js.map
console.log(sourceFile.getDeclarationFilePath())    // .d.ts
console.log(sourceFile.getDeclarationFileMapPath()) // .d.ts.map
```

With file layout:
- `/tmp/tsconfig.json` containing default options
- `/tmp/index.ts`

This example would print:

```
/tmp/index.js
/tmp/index.js.map
/tmp/index.d.ts
/tmp/index.d.ts.map
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
@sheetalkamat thoughts?

**Comment by sheetalkamat** [comment]
There already exists `getOutputFileNames` to get the output file names

**Comment by sguillia** [comment]
`getOutputFileNames` takes a `ParsedCommandLine` which I do not know how to obtain. There is a [getParsedCommandLine](https://github.com/Microsoft/TypeScript//blob/2eca17d7c1a3fb2b077f3a910d5019d74b6f07a0/src/compiler/types.ts#L6399) on `CompilerHost`. [The docs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler) say that `createProgram` "will create a default CompilerHost" but there is no `getCompilerHost` method on type `Program`.

Also I'm not sure why it returns an Array since the file will be written in one place only; and it doesn't return source map and declaration paths

Would it be possible to have a documented example, or a simpler API exposing methods on type `ts.SourceFile`?

Thanks a lot

**Comment by sheetalkamat** [comment]
`ParsedCommandLine` is either from parsing json file using `parseJsonConfigFileContent` or just something you populate based on what your program is.
`createCompilerHost` exists to create the compiler host.
`getOutputFileNames` takes the input file name and returns all the output file names for that file based on the parsed command line which has compiler options etc.

**Comment by sguillia** [comment]
Seems good

`compilerHost.getParsedCommandLine` is undefined, but `parseJsonConfigFileContent` helped:

```ts
import path from "path"
import fs from "fs"
import ts from "typescript"
import json5 from "json5"

const root = path.resolve(process.argv[2])
const tsconfigPath = path.resolve(root, "tsconfig.json")
const filePath = path.resolve(root, "suites/index.test.ts")

const tsconfig = json5.parse(fs.readFileSync(tsconfigPath, "utf-8"))
const parsedCLI = ts.parseJsonConfigFileContent(tsconfig, ts.sys, root)

const outFiles = ts.getOutputFileNames(parsedCLI, filePath, false)
console.log(outFiles)
```

```js
$ node dist/index.js /tmp/proj
[
  '/tmp/temp/__tests__/index.test.js',
  '/tmp/temp/__tests__/index.test.js.map',
  '/tmp/temp/__tests__/index.test.d.ts'
]
```

Thank you

**Comment by danon** [comment]
@sheetalkamat That's very cumbersome to use, especially when using plain compiler api, we have to spoof tsconfig.json just to get outputs.

Isn't there some other, simpler way to get output files? Like maybe using source maps or something?
