### ISSUE TITLE
isArray type guard regression 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#41889]
**TypeScript Version:**  4.2.0-dev.20201208

**Search Terms:**
- 

**Code**

```ts
interface IAction {
    x: number;
}

function foo(arg: IAction | ReadonlyArray<IAction>) {
    const actions: ReadonlyArray<IAction> = Array.isArray(arg) ? arg : [arg];
}
```

**Expected behavior:**
This compiles fine in TS 4.1.2

**Actual behavior:**
In the latest nightly, this produces this error:

```
Type '(IAction & any[]) | (readonly IAction[] & any[]) | (IAction | readonly IAction[])[]' is not assignable to type 'readonly IAction[]'.
  Type '(IAction | readonly IAction[])[]' is not assignable to type 'readonly IAction[]'.
    Type 'IAction | readonly IAction[]' is not assignable to type 'IAction'.
      Property 'x' is missing in type 'readonly IAction[]' but required in type 'IAction'.ts(2322)
```

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201208#code/JYOwLgpgTgZghgYwgAgJIEEFmAexMgbwChlTkAPALmRAFcBbAI2gG4iBfIomWkLXfDBw4AFHCgBzahn55kAH2QAlCHAAmeADYBPdFChxtAHhnY8APgCUhEmQR4AzmGSIzIB9RXqtu-YZOYbubIALzIegbaAHTADhGGYpLWAPwuksjUANriEgC6bOxAA

**Related Issues:**

**Comment by mjbvz** [comment]
The type of `arg` after the `isArray` guard ends up being:

```
(IAction & any[]) | (readonly IAction[] & any[])
```

**Comment by MartinJohns** [comment]
Related: #41808. They mentioned they plan to reverse the previous breaking changes with 4.1.3.
