### ISSUE TITLE
tsc removes comments at the end of lines whose code ends with a comma

### ISSUE THREAD

**Issue by cmloegcmluin** [microsoft/TypeScript#41885]
**TypeScript Version:**  4.1.2

**Search Terms:**

This issue was opened before: https://github.com/microsoft/TypeScript/issues/16727

But then "microsoft locked and limited conversation to collaborators on Jul 30, 2018".

**Code**
```ts
// index.ts

const myMultilineThing = [
  1, // comment A
  2, /* comment B */
  3, /*! comment C */
  4 // comment D
]
const myOneLineThing = [ 1, /* comment A */ 2 ]
```

**Expected behavior:**
```js
// index.js

const myMultilineThing = [
  1, // comment A
  2, /* comment B */
  3, /*! comment C */
  4 // comment D
]
const myOneLineThing = [ 1, /* comment A */ 2 ]
```

**Actual behavior:**
```js
// index.js

const myMultilineThing = [
  1,
  2,
  3,
  4 // comment D
]
const myOneLineThing = [ 1, /* comment A */ 2 ]
```

**Comment by RyanCavanaugh** [comment]
Comments/trivia are usually associated with their most-adjacent tokens/nodes, and are not preserved when it's a token.

100% comment preservation in JS emit is not an invariant of TS and is "best-effort", so some comments not being emitted isn't a per se bug. If you have a scenario that requires comments for machine understanding, you can use the emitted source maps to get back to the originating node and look for comments there.

**Comment by cmloegcmluin** [comment]
Thank you for the explanation @RyanCavanaugh, and for the helpful suggestion. This makes sense. I'll find a way to work around.
