### ISSUE TITLE
JSDoc type tag doesn't handle narrowing of Functions

### ISSUE THREAD

**Issue by bmeck** [microsoft/TypeScript#41881]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** jsdoc type function

**Code**

```mjs
// various attempts at fiddling with function declaration vs expression types also fail
// this one most closely matches the TS expectation below
const Button = /** @type {React.FunctionComponent<{msg: string}>}*/(
  ({msg}) => {
    return <button>{msg}</button>;
  }
);
```

**Expected behavior:** `msg` inside the function has type `string`. It should match the TS equivalent of above:

```ts
const Button: React.FunctionComponent<{msg: string}> = (
  ({msg}) => {
    return <button>{msg}</button>;
  }
);
```

**Actual behavior:** `msg` has type `any`

**Playground Link:** (didn't see how to swap into JS mode) https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoStCAOwGd4AhAVxhlrgF44B6AKj5wAAjACeYJHADeydDAB0AMWY0MwWgGFckGkhowAPFJB0A5gC44DKMBqmAvgD57fHgApycOG+Nn7ASi5HaU8vOCIYZigaOAMAI1Z2GkdfBwMeBLZaRwove3J-CiA

**Related Issues:** none found

**Comment by ajafff** [comment]
It should work if the JSDoc comment is placed above the variable declaration:

```ts
/** @type {React.FunctionComponent<{msg: string}>}*/
const Button = (
  ({msg}) => {
    return <button>{msg}</button>;
  }
);

**Comment by bmeck** [comment]
@ajafff that does not appear to work

<img width="595" alt="Screen Shot 2020-12-09 at 08 06 26" src="https://user-images.githubusercontent.com/234659/101639903-7ce3b280-39f5-11eb-962f-1f3563ba130f.png">

**Comment by sandersn** [comment]
I can't repro this bug from the snippet alone. I tried TS 4.2, 3.6, 3.7 and 3.8. A couple of questions to help produce a repro:

1. Do you have `// @ts-check` on? Is this a JS file?
2. Is `@types/react` installed?

**Comment by sandersn** [comment]
This has been quiet for a long time. Feel free to re-open it if it continues to happen.
