### ISSUE TITLE
Template literal types as index signatures

### ISSUE THREAD

**Issue by danieldelcore** [microsoft/TypeScript#41894]
## Search Terms
- template literal index signature
- object key template literal
- template literal object keys

## Suggestion

The ability to define generic object keys, restricted via template literal types.

## Use Cases

To define objects with properties of a certain shape without having to predefine every possible string as union type.

## Examples

```ts
export type Events = {
    [key in `on${string}`]: boolean;
}

const events: Events = {
    onClick: true,
    onMousedown: true,
    onMouseup: true,
    onMyCustomEvent: false,
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Related: #26797
