### ISSUE TITLE
Optional local variables

### ISSUE THREAD

**Issue by angryziber** [microsoft/TypeScript#41901]
## Suggestion

TypeScript already supports optional parameters and fields with a question mark.
Why not extend this feature to local variables as well, to allow them having an undefined value, e.g.

## Use Cases/Examples

```
let optional?: number = 123
optional = undefined // allowed
```

in this case specifying `number` type is also optional:

```
let optional? = 123
```

This would complete the usage of question mark `?` as nullablity/unefineability operator, similar to Kotlin.

Currently, defining an optional variable requires writing a lot of noise, e.g.

```
let optional: number|undefined = undefined  // too verbose
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
But the variable in your example is not optional. It's always defined. You're confusing optional with "may be undefined".

**Comment by angryziber** [comment]
@MartinJohns I am not confusing - that's exactly what I want. No matter how you name it, it would extend the already existing syntax and make it useful for local variables as well. You already can use it for class variables aka members/properties, so why not local as well

**Comment by MartinJohns** [comment]
> so why not local as well

It would complicate the implementation of #13195, if it ever is to be added. Optional properties and arguments can be missing, not only `undefined`, which is a relevant difference.

**Comment by RyanCavanaugh** [comment]
I don't think it makes sense to put the `?` on the binding name; it's confusing. You wouldn't write `let array[]`; the `| undefined` is part of the type, not the variable. So the logical thing would be `number?`, which we discussed to death when adding `strictNullChecks` (since it might mean `number | null`, `number | undefined`, or `number | null | undefined`) and decided to just not do since different people would rightly declare in a split plurality that it's "obvious" which one of those it should mean and be angry when 66% of them were surprised.

**Comment by malthe** [comment]
I think this is a great idea.
```typescript
let result?: boolean;
```
It's obvious that `result` at this point is `undefined`. I don't think anyone in their right mind would think that it's `null` for example.

Now, @MartinJohns argued that supporting this would complicate https://github.com/microsoft/TypeScript/issues/13195 – meanwhile, on Jun 1, 2021 _that_ issue was [actually resolved](https://github.com/microsoft/TypeScript/pull/43947).

Does this mean that in principle, TypeScript could support this syntax?

I totally agree with @angryziber on this:
```typescript
let result: boolean | undefined = undefined  // too verbose
```
And there's good code to be written that uses this syntax. In the example above, we can imagine that there is no result yet, neither success or failure.
