### ISSUE TITLE
Class with same name in different modules not showing NavBar

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#4191]
Consider the following file:
````language=typescript
module foo {
    class A { }
}

module bar {
    class A { }
}
````

Notice that in the NavBar, ````class A```` in ````module foo```` doesn't show in the navigation bar.

![navbar](https://cloud.githubusercontent.com/assets/5273975/9119887/094d641c-3c2e-11e5-94ab-a23221f54dc8.png)

**Comment by andy-ms** [comment]
Closed by #9220
