### ISSUE TITLE
Typesafe Errorhandling (similar to rust-error-handling)

### ISSUE THREAD

**Issue by alexej-sh** [microsoft/TypeScript#41917]
## Suggestion
Hi, TS is there to give type-safety but currently the errorhandling with try-catch is not type-safe. There are alternatives like the Either-Monad but it requires functional-programming style. I suggest an alternative to try-catch that is simmilar to rust error-handling and it should be a good match to existing feautures of TS.
Here every method can return a (or multiple) subclass(es) of the Error-class instead to throw it. So every method will have a signature like: "number | ErrorType1 | ErrorType2". When calling this method with an additional operator, a check by TS must be made and if the returntype is a instanceof Error, this method must also return automatically with the corresponding errortype. See Examples below.

## Use Cases
- Statically typed error-handling
- force the user to reason more about the error-path
- readable error-handling code

## Examples
**This is what is possible in TS now:**
```
class Error1 extends Error {
  constructor(message: string) {
    super(message);
  }
}

class Error2 extends Error {
  constructor(message: string) {
    super(message);
  }
}

function withErrors(i: number) {
  if (i === 1) {
    return new Error1("Error1");
  } else if (i === 2) {
    return new Error2("Error2");
  } else if (i === 3) {
    return new Error1("Error1 again");
  }

  return "NormalReturnType";
}

function happyPath() {
  const withErrorsVar = withErrors(1); //Error1 | Error2 | "NormalReturnType"
  if (withErrorsVar instanceof Error) {
    //dont handle error here
    return withErrorsVar; //Error1 | Error2
  }

  console.log("this is happy path and a cast was made");
  takeaString(withErrorsVar); //"NormalReturnType"

  return "ReturnSpecialTypeInsteadOfUndefined";
}

function takeaString(param: string) {
  console.log("consume" + param);
}

//handle error here
function errorHandling() {
  const happyPathVar = happyPath(); //Error1 | Error2 | ReturnSpecialTypeInsteadOfUndefined

  if (!(happyPathVar instanceof Error)) {
    return;
  }

  if (happyPathVar instanceof Error1) {
    console.log("hanndle Error1");
    console.log(happyPathVar); //Error1
  } else if (happyPathVar instanceof Error2) {
    console.log("hanndle Error2");
    console.log(happyPathVar); //Error2
  } else {
    exhaustiveCheck(happyPathVar); //never
  }
}

function exhaustiveCheckk(s: never) {
  console.log("exhaustiveCheck");
}
```

**This instanceof Error checks make the code verbose. I suggest to create an operator that will make this checks under the hood. The above code should be written like this:**

```
//no change
class Error1 extends Error {
  constructor(message: string) {
    super(message);
  }
}

//no change
class Error2 extends Error {
  constructor(message: string) {
    super(message);
  }
}

//no change
function withErrors(i: number) {
  if (i === 1) {
    return new Error1("Error1");
  } else if (i === 2) {
    return new Error2("Error2");
  } else if (i === 3) {
    return new Error1("Error1 again");
  }

  return "NormalReturnType";
}

//new operator here
//no instanceof Error checks, just the happy path
function happyPath() { //return: Error1 | Error2 | ReturnSpecialTypeInsteadOfUndefined
  const withErrorsVar = withErrors(1)!!!; //instanceof Error check must be made under the hood with automatic return type inference

  console.log("this is happy path and a cast was made");
  takeaString(withErrorsVar); //"NormalReturnType" because the !!!-operator was used

  return "ReturnSpecialTypeInsteadOfUndefined"; //if returntype is void than a special returntype must be returned
}
//no change
function takeaString(param: string) {
  console.log("consume" + param);
}

//handle error here
//error-pattern-matcher would be great
//but if(a instancfeof Error) is also ok
function errorHandling() {
  const happyPathVar = happyPath(); //Error1 | Error2 | ReturnSpecialTypeInsteadOfUndefined
  
  //something like this...
  //with automatic casting and exhaustiveCheck
  errorPattern(happyPathVar =>
    Error1: console.log("hanndle Error1"),
    Error2: console.log("hanndle Error2"),
  )
}
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals]

**Comment by MartinJohns** [comment]
> [x] This feature would agree with the rest of [TypeScript's Design Goals]

It really wouldn't. It would be against goal 3 and 8, and non-goal 5.

**Comment by RyanCavanaugh** [comment]
This just seems like an inversion of the Either monad into an imperative style without any concrete benefits. It doesn't really fit in with our general philosophy of building primitives that can compose into larger systems, and this pattern of programming isn't prevalent in the JS ecosystem already, so it doesn't look like something people would be eager to adopt even if it did exist.
