### ISSUE TITLE
Template literals as keys in object literals loosing type information

### ISSUE THREAD

**Issue by falsyvalues** [microsoft/TypeScript#41912]
Template literals as keys in object literals loosing type information, even with explicite type literals (works only with one exact type).

**TypeScript Version:**  4.1.2, 4.2.0-dev.20201210

**Search Terms:** Template literal types literal keys object keys literal types

**Code**

```ts
const template = <T extends string>(name: T) => ({
    [`${name}` as const]: name
});
```

**Expected behavior:**

```ts
const value = template ('TEST'); // const value: { TEST: "TEST"; }
```

**Actual behavior:**

```ts
const value = template ('TEST'); // const value: { [x: string]: "TEST"; }
```

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201210&ssl=13&ssc=26&pln=13&pc=44#code/MYewdgzgLgBFCmBbADgGwIYIPphFLA7iAE4DWAlmAOZboRanwCeMAvDADwAqM8AHgjAATCDGjFKVAHwAKMOkTwAXDC4BKNlJgyA3gCgYhmAG0ABgBId8xQF9TMOjFCQoAXRXX4em2oDcevWdoGAA3dFQAV3gcPEISCmo2OCQ0TGjcfCIySVp6RiYZAHIuAFEAZS5CvxgAehqncGCwyOUYHRM+FXFJdxgAIlKKvt8YGwCg2AQUDGwMuOzqQnIoAAssVGX4YnCsKCZkeCTuXgF4YVFu6llPFWLyypgAHxhCgHkAJUKnl4A5V8qNKwtLoDEYzJZPHYHKIJr1PN4-ONGrBmlEYpl4jkNghtqgklNUrNYlkEjQCMs1titjs9gcioMASM6g0XKFwlEVO1jJ0xFAJNRegN7sNRkjWQSZtESZIjjx+IIRLz+dI5ApWncKlVNNp9EYTBYrGqoY5YR41Qj-IFkWyWvNSfiUpK7ZJ6fcqkz6hMbRy2qp7iohUMRmMgA

**Related Issues:** Might be related to #41631

**Comment by RyanCavanaugh** [comment]
This is correct behavior, since you could write `template<"foo" | "bar">("foo")` and would not get back an object with a `bar` property

**Comment by falsyvalues** [comment]
> This is correct behavior, since you could write `template<"foo" | "bar">("foo")` and would not get back an object with a `bar` property

@RyanCavanaugh But this will not produce expected result either I won't get `// const value: { foo: "foo"; }` even if value is there.

**Comment by RyanCavanaugh** [comment]
I don't understand what you mean by that.

**Comment by falsyvalues** [comment]
@RyanCavanaugh  Sorry I wasn't clear enough. Here is a example of expected behavior.

https://www.typescriptlang.org/play?ts=4.2.0-dev.20201210#code/MYewdgzgLgBFCmBbADgGwIYJgXhgCjHUXgC4YByAMxBHJgB8KAjdAJ3IEocA+fAbwBQMYTADaAAwAkfQsQC+4mOggxQkKAF0ys+ALkcA3AOMC10GADd0qAK7wA+gHcQrANYBLMAHMccJGkx4PAAiahBgwxgAeiiYAFEADQAFOIBhABU4gBFVcHMrWwdnN08vMj4YMLJQmmCDGDkgA

**Comment by dishuostec** [comment]
@falsyvalues I'v tried this, it seems work.

```typescript
const template = <T extends string>(name: T): Record<`${T}`, `${T}`> => ({
    [`${name}`]: name,
} as any);
```

https://www.typescriptlang.org/play?ts=4.2.0-dev.20201210&ssl=7&ssc=11&pln=5&pc=1#code/PTDGHsDsGcBcAJYFMC2AHANgQ2fAvPABSRYpIBc8A5AGbjhXwA+1ARlgE5UCU+AfEQDeAKBDxx8ANoADACSCSZAL7T4WaPAgxYAXUqKko4Eu4BuYcK1xEqTDiT54AHgAq8JAA9kkACYa4HACWkADmfMSkFPAu3JQASkgQHD5OcoIuKgA08GkZ0gJ4AoQiElJpBip68AaZwkpqGliQAJ5mFlYIAG5YGACuSAD6AO7gHADWwSGOyOjYyIQARHTgC2bwYgCiABoAChsAwi4bACKaUNbdfYMj45OUgvDLlEv0C6bwSsJAA

**Comment by falsyvalues** [comment]
Hi @dishuostec!

Thanks for that. Looks returning type and `as any` did the job but would be nice achieve that without casting to `any`. @RyanCavanaugh Please take a look on example above.
