### ISSUE TITLE
Cannot use keyof to index an indexed object type if its extended

### ISSUE THREAD

**Issue by willium** [microsoft/TypeScript#41910]
**Code**

```ts
type Foo = { bar(a: string): boolean }

// works
type Thing1<F extends keyof Foo> = ReturnType<Foo[F]>

// doesn't work:
type Thing2<Fo extends Foo, F extends keyof Fo> = ReturnType<Fo[F]>
```

**Expected behavior:**
`Type 'Fo[F]'` should satisfy the constraint `'(...args: any) => any'`.

**Actual behavior:**
```
Type 'Fo[F]' does not satisfy the constraint '(...args: any) => any'.
  Type 'Fo[keyof Fo]' is not assignable to type '(...args: any) => any'.
    Type 'Fo[string] | Fo[number] | Fo[symbol]' is not assignable to type '(...args: any) => any'.
      Type 'Fo[string]' is not assignable to type '(...args: any) => any'.(2344)
```

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKAjAhgJwBRYBcUAzsDgJYB2A5gJTEYIA2EWVUAvgLABQfoSFAAqAC2o0AjAB4YUCAA9gEKgBMSUANYQQcAGawEAPmRQAShGABXHFWHgIshAG0YAXSN8BDkeNoAmJ3klFXVDOAAaWGDlNQ1tXQN4ExQLa1t7SCdXDyA)

**TypeScript Version:**  Playground Version

**Search Terms:** keyof, index signature

**Comment by MartinJohns** [comment]
In `Thing1` we know that all possible keys provided will always result in a function.

In `Thing2` we can't know this, so it won't work.  
For example:

    interface Foo2 extends Foo { mep: string; }

    type ExampleThing2<Fo extends Foo, F extends keyof Fo> = Fo[F]
    type Example = ExampleThing2<Foo2, 'mep'>

The type of `Example` will be `string`. `Foo2['mep']` is not a function.
