### ISSUE TITLE
exports.__esModule should be emitted in declaration file

### ISSUE THREAD

**Issue by themez** [microsoft/TypeScript#41916]
Currently, a `__esModule` export would be appended to target js file for es module, but not in the declaration file, which causes `canHaveSyntheticDefault` checking failed.

**TypeScript Version:**  3.7.x-dev.201xxxxx

__esModule
esModuleInterop

**Code**

```ts
// canHaveSyntheticDefault checks __esModule exports

// function canHaveSyntheticDefault ...

// It _might_ still be incorrect to assume there is no __esModule marker on the import at runtime, even if there is no `default` member
// So we check a bit more,
if (resolveExportByName(moduleSymbol, escapeLeadingUnderscores("__esModule"), /*sourceNode*/ undefined, dontResolveAlias)) {
    // If there is an `__esModule` specified in the declaration (meaning someone explicitly added it or wrote it in their code),
    // it definitely is a module and does not have a synthetic default
    return false;
}
```

**Expected behavior:**
__esModule exports emitted in both declaration and target js file for es module
**Actual behavior:**
__esModule exports only emitted in target js file:
```
Object.defineProperty(exports, "__esModule", { value: true });
```

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/41898

**Comment by RyanCavanaugh** [comment]
My comments in [the other thread](https://github.com/microsoft/TypeScript/issues/41898#issuecomment-742745089) apply equally here
