### ISSUE TITLE
Interface allow to call method with mandatory argument

### ISSUE THREAD

**Issue by sosoba** [microsoft/TypeScript#41929]
**TypeScript Version:**  4.1.2

**Search Terms:** interface optional parameters

**Code**

```ts
interface I {
    m(p?:string):string;
}

class C implements I {
    m(p:string){
        return p;
    }
}

const i : I = new C();
i.m();
```

**Expected behavior:** 
`Class 'C' incorrectly implements interface 'I'.`

**Actual behavior:**

No errors

**Comment by MartinJohns** [comment]
That wouldn't be type-safe.

    const i: I = new C();
    i.m();

**Comment by MartinJohns** [comment]
Duplicate of #38019.
