### ISSUE TITLE
Bug: code repeated in my cordova appBundle.js

### ISSUE THREAD

**Issue by NGumby** [Microsoft/TypeScript#4192]
With Visual Studio 2015 RTM, In my cordova project, the compiled appBundle.js is repeating code at the end of the file, and doesn't repeat it sequentially.  For example, in the following example, debugMode is false when I use it in my project code, but it should be true.

Here is a simplified example of what happens : 

File config.ts
```
var debugMode: boolean = false;
debugMode = true;
var enableWindowLog: boolean = false;
var configMode: string = ""

if (debugMode) {
    enableWindowLog = true;
    configMode = "-dev";
}
```

File index.ts
```
//My app code
```

Compiled appBundle.js
```
var debugMode = false;
debugMode = true;
var enableWindowLog = false;
var configMode = "";
if (debugMode) {
    enableWindowLog = true;
    configMode = "-dev";
}

// My project code compiled

var debugMode = false;
var enableWindowLog = false;
var configMode = "";
var debugMode = false;
debugMode = true;
var enableWindowLog = false;
var configMode = "";
if (debugMode) {
    enableWindowLog = true;
    configMode = "-dev";
}
var debugMode = false;
debugMode = true;
var enableWindowLog = false;
var configMode = "";
if (debugMode) {
    enableWindowLog = true;
    configMode = "-dev";
}
var debugMode = false;
debugMode = true;
var enableWindowLog = false;
var configMode = "";
if (debugMode) {
    enableWindowLog = true;
    configMode = "-dev";
}
var debugMode = false;
debugMode = true;
var enableWindowLog = false;
var configMode = "";
if (debugMode) {
    enableWindowLog = true;
    configMode = "-dev";
}
var debugMode = false;
var enableWindowLog = false;
var configMode = "";
```

**Comment by danquirk** [comment]
Can you share the actual compiler invocation command that's causing this? (presumably in the Output window)

**Comment by NGumby** [comment]
1>Target "PreComputeCompileTypeScript" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "D:\CompuSport\trunk\CS Cordova\CS.Cordova\CS.Cordova.jsproj" (target "CompileTypeScript" depends on it):
1>Using "VsTsc" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll".
1>Task "VsTsc"
1>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc.exe --project "D:\CompuSport\trunk\CS Cordova\CS.Cordova\scripts" COMPUTE_PATHS_ONLY
1>Done executing task "VsTsc".

here is my tsconfig.json
```
{
    "compilerOptions": { 
        "noImplicitAny": false,
        "noEmitOnError": true,
        "removeComments": false,
        "sourceMap": false,
        "out": "www/scripts/appBundle.js",
        "target": "es5"
    }
}
```

**Comment by RyanCavanaugh** [comment]
I'm guessing what's happening is that the Cordova project system, or something else (maybe a source code control tool?), is mirroring config.ts to some other locations in the project folder. `tsconfig` without a file will pick up all .ts files, recursively, in its containing folder. Can you verify that only the two .ts files that you expect to be there exist in the project folder?

**Comment by NGumby** [comment]
Oh yeah, I had a subfolders with a bunch of config.xxxx.ts files that overwrites config.ts with a grunt task.  It was the fact that the repeats where at the end that threw me off.

Sorry about that, and thanks for pointing me in the good direction.
