### ISSUE TITLE
Exported variable ... has or is using name ... from external module ... but cannot be named

### ISSUE THREAD

**Issue by ikibalnyi** [microsoft/TypeScript#41934]
**TypeScript Version:**  4.1.2
**Search Terms:**
typescript declaration exported variable
typescript exported variable cannot be named
typescript error exported variable

**Code**:
```ts
// types.ts
export enum Enum {
  LOGIN = "login",
  REGISTER = "register"
}

export type MappWrapped = Partial<{
  [Enum.LOGIN]: null;
  [Enum.REGISTER]: null;
}>;
```
```ts
// foo.ts
import { Enum, MappWrapped } from "./routes";

// error happens, says:
// Exported variable 'Broken2' has or is using name 'Enum' from external module "types.ts" but cannot be named.
export const Broken2 = <R extends Enum>(props: Required<MappWrapped[R]>) => props;
```

**Expected behavior:**
Code should not fail with `Exported variable ... has or is using name ... from external module ... but cannot be named`

**Actual behavior:**
You use `declaration: true` or `"composite": true`.
If you make a file that's exporting a map wrapped in any helper function like `Record`, `Partial` etc. which is using `enum` values as keys.
And then use this type inside another file and wrap it in another similar helper (e.g. `Record`).
Code fails with `Exported variable ... has or is using name ... from external module ... but cannot be named`.

**Playground Link:** https://codesandbox.io/s/serene-andras-gsjqx?file=/src/index.ts

**Comment by weswigham** [comment]
Dupe #40718 ?

**Comment by ikibalnyi** [comment]
Yeah, looks same, the error code is different tho
