### ISSUE TITLE
Type checking generic middleware

### ISSUE THREAD

**Issue by Bielik20** [microsoft/TypeScript#41930]
## Search Terms

generic middleware

## Suggestion

Ability to infer type of chain of generic functions.

## Use Cases

Before creating this issue I created a [question on stackoverflow](https://stackoverflow.com/questions/64933309/typescript-type-checking-middleware). This underlies what I am trying to achieve.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Please file a new issue where you fill in the template to a degree where it can be read here, not elsewhere.
