### ISSUE TITLE
setLocalDescription requires the description argument when it should not.

### ISSUE THREAD

**Issue by jcc10** [microsoft/TypeScript#41939]
**TypeScript Version:**  4.2.0-dev.20201211

**Search Terms:** setLocalDescription, LocalDescription

**Code**

```ts
export async function test() {
    const pc = new RTCPeerConnection();
    await pc.setLocalDescription();
}
```

**Expected behavior:**
No Errors.

**Actual behavior:**
```
npx tsc test.ts
test.ts:3:14 - error TS2554: Expected 1 arguments, but got 0.

3     await pc.setLocalDescription();
               ~~~~~~~~~~~~~~~~~~~~~

  ../emsdk/node/12.18.1_64bit/lib/node_modules/typescript/lib/lib.dom.d.ts:12238:25
    12238     setLocalDescription(description: RTCSessionDescriptionInit): Promise<void>;
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'description' was not provided.


Found 1 error.
**
```

**Playground Link:** https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAQwO4IJbwGYFcB2BjGVCHOGYAZxgAoBKOAbwCg4W49jK4w84BeOHMCRwASgBUAwgAVgwKBOKCCRHLQDczVsjTxuAOnLAYAGQh4EAGwAiFPFFRhCxdYwC+QA

**Related Issues:** No.

Spec: https://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription (Paragraph 3)

I already have [a fork that has the lib patched](https://github.com/microsoft/TypeScript/compare/master...jcc10:master#diff-796971dc74a3f3cd77ca0a3a776d6fe27ab224cd501d9652dbeffcf45ba0f058) I am unsure if there is any other code that would have to be patched.

**Comment by IllusionMH** [comment]
Looks like error in actual behavior section is not what you want to show for method signature.

To fix error from actual behavior you should use `export​ ​async​ ​function​ ​test​(​)​`

**Comment by jcc10** [comment]
@IllusionMH Thank you, I have no idea how I missed that.
