### ISSUE TITLE
Side-effects-only import won't check module existence when compile

### ISSUE THREAD

**Issue by chengB12** [microsoft/TypeScript#41937]
**TypeScript Version:**  4.2.0-dev.20201210

**Search Terms:**
side-effects import
**Code**
on root, there is foo.ts and bar.ts
```ts
// foo.ts
import './wrong/bar'
```
```ts
// bar.ts
export a = 1
...
```

**Expected behavior:**
import './wrong/bar' shall throw error at compile time,
**Actual behavior:**
![image](https://user-images.githubusercontent.com/66152032/101966600-334dc000-3bcd-11eb-8324-45be75332127.png)
right now tsc will pass. it will throw Error: Cannot find module './wrong/bar' when executed in runtime

I found import {} from './wrong/bar' will check module exists, however, that's not side-effects only import, code inside bar.ts is not executed

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. See #28411 for the suggestion to add a flag to make it behave otherwise
