### ISSUE TITLE
Syntactic sugar: alternative type

### ISSUE THREAD

**Issue by x1shi** [microsoft/TypeScript#41946]
## Suggestion
Use some way to provide `any` with alternative type,
help type inference automatically.

## Use Cases
When I code some open APIs, the same thing always happens:  

The parameter of the function should be of a certain type,  
but because API is public(like will be use by js),  
should not rely entirely on the type of parameter.  
so, need to validate the type at run time.

For this time,  
if use `(param: any)=>void` , the suggestions will be lost.  
But if use `(param: T_SomeType)=>void`,  
not only need to write comment `this @param can be {any}` .
When types and functions are complex,  
it also causes coding TS to be like coding JS:
The operation became unsafe,
everything needs the brain to make the right decisions.

## Examples
```typescript
type T_Type = [string, boolean]
function a(param:^T_Type){
  //...
}
```
Use `^` to tell TS (and humans), `param` can be `T_Type` or `any`.

`^T_Type` is like `any`,  
except for the following points, there will be no change:
* In code suggestions, it is treated as `T_Type`.  
  Only suggestions time, in other time (like compile),  it's `any`.
* When using "^!" like `param^!` , the `param` will be converted to `T_Type` ;  
  `param^!` is just like `param:T_Type`.  
  And :
  ```typescript
  //fn a & T_Type...
  function b(_param?:^T_Type){
    //...
  }
  function c(__param?: T_Type){
    //...
  }
  ```
  `__param!` == `_param^!!` == `param^!`.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
For object types, the behavior requested is already captured to a high degree by `Partial<T_Type> & {[s: string]: any}`.

Overall this isn't a good fit with the language and doesn't look like something we'd add.
