### ISSUE TITLE
inference breaks on intersection types

### ISSUE THREAD

**Issue by matt-42** [microsoft/TypeScript#41944]
**TypeScript Version:**  v4.2.0-dev.20201211 

**Search Terms:**

**Code**

```ts
type Test<T> = {};
function test<T>(a1: Test<T>, a2: (a: T) => void) {}

test({} as (Test<{x: number}>), a => { a.x = 23; });
test({} as (Test<{x: number}> & Array<any>), a => { a.x = 23; });

```

**Expected behavior:**

Inference should world and the above code should compile with no error.

**Actual behavior:**

Code does not compile. Error:  Object is of type 'unknown'

**Playground Link:** 

https://www.typescriptlang.org/play?ts=4.2.0-dev.20201211#code/FAFwngDgpgBAKlAziAPHAfDAvDA3gXwG5gAzAVwDsBjEASwHsKYQlUMAKAQwEYAueVmnQAaGJwBM-LvzgBKbJgBu9WgBN5BYKFbsCYxDHYJkKXAA9+FMgFsARlABO+dLNGcFeMQDoz2GOIBmQhh8WWIWZF18fUNjVHNLG3snTAAyGABBBwdOMBROCjAXNw9cb18cQODQ4iA

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is working as intended. The `Test<T>` type doesn't actually have members that use `T`, so there's nothing from which to infer. If you change the declaration to `Test<T> = { _: T }` it works as expected.

The reason there is no error in the first example is that inference between instances of the same type (i.e. `Test<{ x: number }>` and `Test<T>`) is optimized to just infer between the type parameters. But once a type is a member of a union or intersection, only it's structure is considered.

**Comment by matt-42** [comment]
Thanks for the explanation, I've added a dummy field `_: T` and it works now. 

Just as an eventual future feature, It would be nice to have inference working also on the second case.
