### ISSUE TITLE
Can  not get property type in decorator 

### ISSUE THREAD

**Issue by duongvanba** [microsoft/TypeScript#41940]
I can not get type of property if is array and can not get optional (?) from decorator
Hope that TS will update it in next version

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
