### ISSUE TITLE
Two or more names for union argument

### ISSUE THREAD

**Issue by rpidburachynskyi** [microsoft/TypeScript#41943]
## Search Terms

union, names, argument

## Suggestion

Opportunity to naming argument with union type with different names. This really helpful for function/method overloading.

## Use Cases

Now when I overload function, I need to set name for arguments with union type as universally (`arg2`) or using a separator 'or' (`serverOrOptions`), but I can use different name for each possible type `server | options`.

Current state: 
```ts
type Server = {
	listen: (port?: number) => void;
};

type Options = {
	port: number;
};

function createModule(server: Server): void;
function createModule(options: Server): void;

function createModule(serverOrOptions: Server | Options): void {
	if('listen' in serverOrOptions) { 
		// using server
		serverOrOptions.listen(80);
	} else {
		// using options
		const server = createServer(serverOrOptions);
		server.listen();
	}
}
```
Now this functions we can replace to:
```ts
function createModule(serverOrOptions: Server | Options): void {
	if('listen' in serverOrOptions) { 
		// pass argument to server variable
		const server = serverOrOptions;
		server.listen(80);
	} else {
		// pass argument to options variable
		const options = serverOrOptions;
		const server = createServer(options);
		server.listen();
	}
}
```

## Examples

My suggestion to do that:
```ts
function createModule(server | options: Server | Options): void {
	if('listen' in server) { 
		server.listen(80);
	} else {
		const server = createServer(options);
		server.listen();
	}
}
```

It also can help to write code without `as` operator.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
This is runtime functionality and should be brought up with TC39

**Comment by kitsoRik** [comment]
> This is runtime functionality and should be brought up with TC39

Why this is runtime functionality? We can't replace `server | options` to `serverOrOptions` at compile time?

**Comment by RyanCavanaugh** [comment]
You could do that, and in doing so, would create runtime functionality. That's what we mean when we say that - it's observable runtime behavior.
