### ISSUE TITLE
"Object is possibly 'null'" in JS not inferring non-null correctly

### ISSUE THREAD

**Issue by eventualbuddha** [microsoft/TypeScript#41957]
**TypeScript Version:**  4.1.3

**Search Terms:** type narrowing, null, optional, checkJs

**Code**

> NOTE: I couldn't figure out how to make this happen with just a single file, but I tried to make it as minimal as possible.

```ts
// index.js
const { a } = require("./util");

if (a) {
  console.log(a + 1);
}

// util.d.ts
export const a: null | number;
```

**Expected behavior:**

It should compile fine.

**Actual behavior:**

```
index.js:4:15 - error TS2531: Object is possibly 'null'.

4   console.log(a + 1);
                ~


Found 1 error.

error Command failed with exit code 2.
```

**Playground Link:** https://github.com/eventualbuddha/ts-4-bug

**Related Issues:** n/a

**Comment by RyanCavanaugh** [comment]
Regressed between 4.0 and 4.1

**Comment by eventualbuddha** [comment]
Just for posterity, here was my workaround: https://github.com/votingworks/vxsuite/pull/113/files#diff-8a912ec9364ae35fdb1bbd6c0cfe8380567bc95f928320933a2065e170785b96

In the example given above, it'd be this:

```js
const { a } = require("./util");

const b = a;
if (b) {
  console.log(b + 1);
}
```
