### ISSUE TITLE
Generic function type not narrowed based on enum

### ISSUE THREAD

**Issue by jonhue** [microsoft/TypeScript#41956]
**TypeScript Version:**  4.1.2

**Search Terms:** `narrowing` `generic function type`

**Code**

```ts
enum SyntaxType {
    A = 'a',
    B = 'b',
}

interface NodeA {
    type: typeof SyntaxType.A
}

interface NodeB {
    type: typeof SyntaxType.B
}

type SyntaxNode = NodeA | NodeB

type State<T extends SyntaxNode> = {
    node: T
}

const traverse = <T extends SyntaxNode>(
  state: State<T>,
  node: T,
): State<T> => {
  switch (node.type) {
    case SyntaxType.A:
      return handleA(state, node)
    case SyntaxType.B:
      return handleB(state, node)
  }
}

const handleA = (state: State<NodeA>, node: NodeA): State<NodeA> => state
const handleB = (state: State<NodeB>, node: NodeB): State<NodeB> => state
```

**Expected behavior:** I would expect the `switch` statement to narrow `T` to the concrete types `NodeA` and `NodeB` in the corresponding cases.

**Actual behavior:** Instead, the generic type `T` is not narrowed to the concrete types `NodeA`/`NodeB` leading to an error as the result of `handleA`/`handleB` does not cover all of `T`s possible interpretations.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.2#code/KYOwrgtgBAygniALgQwB4BU4AdhQN4BQUxUAglALxQDky1ANESQEKU0BGDBAvgQQJZJgAJwBmyAMa4AcgHsAJsHKESURNmAAuNRtmjYCFBg0A6Ujz6DEI8VKhzFrFSXU5tr4HoNI0mHCeYLAg9vIwdcKnDyAB97BWBA4I1YFGsAHnQoYFRrEHkAZ1C0cIA+NmdiEHjtdCCJWRB8xDVhZAA3EXyIqAysnNACotRSgAomJuRrbRhU4AySxkrqqHRGAEpp2fnKMud8gHd+RAkACygRqsUTDzX8JmIJZC6hv2AzTXuSYWBEMGEQKAnZB5AA2ShGE2s9Cgl2Aa0+j2e8B8xn8zA+qmI31+-0BwPkYOYENm0Nh8OIvF4BHqjWaQNBSjYxMmWhSLLSUQWMOWUQ2bPSnJ2UEhwGpDSaeIZrCozKm-Lm4WYXNh2kVfJm7MVZQoZRFQA

**Related Issues:** 

Strictly speaking, this is not a bug, neither is it a feature request. It's something in between. 🙂 
I also don't know how easy/hard this is to catch during type inference or whether narrowing the type here is even something that we want to do.

**Comment by RyanCavanaugh** [comment]
This is a correct error. You could legally call `traverse` this way:
```ts
declare const aNode: NodeA, stateB: State<NodeB>;
// Unsound, passes a stateB to handleA
traverse<NodeA | NodeB>(stateB, aNode);
```

That said, `node` could be more correctly narrowed, see #33014

**Comment by jonhue** [comment]
Thank you! Overlooked that.
