### ISSUE TITLE
Transpilation issue for not initialized member variables?

### ISSUE THREAD

**Issue by mcjazzyfunky** [microsoft/TypeScript#41954]
**TypeScript Version:**  4.1.2 (I guess it's the same behavior for older versions too)

**Search Terms:**
 constructor member undefined transpilation 

**Code**

```ts
class X { a: any }

console.log(Object.keys(new X()))
```

**Expected behavior:**

Sholdn't that be transpiled to to following?

```ts
"use strict";
class X {
    constructor() {
        this.a = undefined;
    }
}
console.log(Object.keys(new X()));
```

Shouldn't it print out `["a"]` to the console?

**Actual behavior:**

Actually the code above transpiles to:

```ts
"use strict";
class X {
}
console.log(Object.keys(new X()));
```

and prints out `[]` to the console.

**Playground Link:** 

&raquo; [Demo on TypeScript Playground](https://www.typescriptlang.org/play?ts=4.1.2#code/MYGwhgzhAEAa0G9pgFzIHYE9oF8BQewA9uhESAKYB0IRA5gBQDyARgFYXAAuVA1hZggN0FAO5wGASmlA)

&raquo; [JavaScript counterpart](https://jsbin.com/bokilihayu/edit?js,console) (the experimental syntax feature regarding the declaration of member variables is not yet proper ES2020 but should already work in very modern Chrome and Firefox browsers)
Prints out `["a"]` to the console (in contrast to its TypeScript counterpart)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior, since (pre-standardization of this) you might have just been declaring something with the intent to not set it.

Set the `useDefineForClassFields` setting to get the fully-compliant behavior.
