### ISSUE TITLE
TypeScript issue with DeepMap Union type

### ISSUE THREAD

**Issue by rnnyrk** [microsoft/TypeScript#41953]
I'm trying to create a Union type with the structure of optional fields. I have created the following types:

```javascript
export type StartEndType = {
  start_date: string;
  end_date: string;
};

export type PayrollContract = StartEndType & {
  type: 'ON_PAYROLL';
  yearly_holidays: number;
};

export type FreelanceContract = StartEndType & {
  type: 'FREELANCE';
  hourly_rate: number;
};

export type Contract = PayrollContract | FreelanceContract;
```

In my component it looks like:

```javascript
{contractType === 'ON_PAYROLL' ? (
  <Number name="yearly_holidays"  />
) : contractType === 'FREELANCE' && (
  <Number name="hourly_rate" />
)}
```

When I hover contract, it knows that it's one of `ON_PAYROLL` or `FREELANCE`. Although unfortunately I get a DeepMap error within my component.

Isn't thist supported by TypeScript out of the box, or is this a bug?

```javascript
Property 'yearly_holidays' does not exist on type 'DeepMap<PayrollContract, FieldError> | DeepMap<FreelanceContract, FieldError>'.
  Property 'yearly_holidays' does not exist on type 'DeepMap<FreelanceContract, FieldError>'.
```

Thanks in advance.

**Comment by MartinJohns** [comment]
Please use the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will make it much easier for the TypeScript team and allows them focus on improving the language, instead of decyphering GitHub issues. :-)

In your example code you did not even provide the type definition for `DeepMap<>`.

**Comment by RyanCavanaugh** [comment]
Please provide a complete and self-contained repro

**Comment by maciek-codes** [comment]
This is an issue with `DeepMap` type helper in [react-hook-form](https://github.com/react-hook-form/react-hook-form) repo. See [src/types/utils.ts#97](https://github.com/react-hook-form/react-hook-form/blob/3ad41d62e43e789ee8db32d93e537e282c3e8ed8/src/types/utils.ts#L97)

I reduced it to this:
```typescript
declare const $NestedValue: unique symbol;

type NestedValue<TValue extends object = object> = {
  [$NestedValue]: never;
} & TValue;

export type BrowserNativeObject = Date | FileList | File;
export type IsAny<T> = 0 extends 1 & T ? true : false;
export type NonUndefined<T> = T extends undefined ? never : T;


export type DeepMap<T, TValue> = IsAny<T> extends true
  ? any
  : T extends BrowserNativeObject | NestedValue
  ? TValue
  : T extends object
  ? { [K in keyof T]: DeepMap<NonUndefined<T[K]>, TValue> }
  : TValue;

const map: DeepMap<SomeUnionType, string> = complex;

// No error, prints  "complex"
console.log(map.type);

// Type error, prints "12345". 
// Error ts(2339): Property 'data' does not exist on type 'DeepMap<{ type: "basic"; }, string>'.
console.log(map.data);
