### ISSUE TITLE
in jsx/tsx, close tag doesn't correctly be completed when tag is like `<XX.YY>`

### ISSUE THREAD

**Issue by heroboy** [microsoft/TypeScript#41963]
**TypeScript Version:**  4.1.2

**Search Terms:** jsx tsx auto close completion tag

**Code**
```tsx
import React from 'react';
function Form(props:any)
{
    return <>abc</>
}

Form.Item = function(props:any){
    return <>abc</>;
}

function foo()
{
    return <Form.Item></Form>;
}
```

Please try to change `foo` to `<Form.Item></Form.Item>`

**Expected behavior:**
`<Form.Item></Form.Item>`

**Actual behavior:**
`<Form.Item></Form.Form.Item>`

When you type `.` at `</Form.` , editor show you the completion list `Form.Item` trying to close the tag. But when you accept the suggestion, it doesn't replace the whole close tag but replace the part after the dot.

**Playground Link:** [play](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201211#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoTAVwDsNgIa4AxaEACjBzAGcAuFDQCeASnIBvcnGlwiMKlCYAeAHwoARmiUB6FeQC+5cqyggAdAEkYSPAF441OjAY1O3foNGSZspPMVwqhpauhSGlLT0jA4QEOxi3jJyCsomICo6aSph5EA)

**Related Issues:**

**Comment by aminpaks** [comment]
@heroboy I can't reproduce this with the provided playground link. this is what ive done:

1. deleted `<Form></Form>`
2. started typing `<Form.Item></`
3. used code completion to see what are my options and `Form.Item>` showed up

**Comment by heroboy** [comment]
@aminpaks 
You should not deleted. Modify it.
The key point is when you input `.` at the close tag `</Form.` .
![tsts](https://user-images.githubusercontent.com/54468/102441867-1ba78900-405e-11eb-87b9-8a31c40b37b5.gif)

**Comment by aminpaks** [comment]
@heroboy Gotcha. I'm on it

**Comment by aminpaks** [comment]
Found the issue [here](https://github.com/microsoft/TypeScript/blob/master/src/services/completions.ts#L245). Working on it.

**Comment by aminpaks** [comment]
Here's a fix
https://github.com/microsoft/TypeScript/pull/42029
