### ISSUE TITLE
Use of compilation time constants in types. 

### ISSUE THREAD

**Issue by o-alexandre-felipe** [microsoft/TypeScript#41968]
Typing is in the core of the library and it is very useful and could be more if we could use it easily for validation.

There are libraries that attempt to improve the programming experience in this direction but they fail due to limitations of the language itself.

The closer I could get searching the subject was using the library [zod](https://github.com/colinhacks/zod), however I still need to have separated information for type and content.

The part of generating data from can be disputed as a [Non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals)
> 5. Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

The part of defining generic types from compilation time constant is more related to removing a barrier that seems unnecessary, since the constants and types accept the same input.

## Search Terms

refers to a value, but used as type

## Suggestion

My suggestion is to use things that can be identified as compilation time constants as type or types as value.

Currently it is possible to manipulate types in an interesting way.

```ts
type JSONSchema = {type: string, items?: JSONSchema, properties?: {[key: string]: JSONSchema}}

type TypeFromSchema<T extends JSONSchema> = 
    T['type'] extends 'string' ? string: 
    T['type'] extends 'boolean' ? boolean:
    T['type'] extends 'number'|'integer' ? number:
    T['type'] extends 'array' ? 
        // ignore heterogeneous arrays
        (T['items'] extends JSONSchema ? TypeFromSchema<T['items']>: never):
    T['type'] extends 'object' ? {
        // neglect the required fields
        [k in keyof T['properties']]?: TypeFromSchema<Extract<T['properties'][k], JSONSchema>> 
    } : never;

type stringSchema = {"type": "string"};
type booleanSchema = {"type": "boolean"};
type numberSchema = {"type": "number"};

type objectSchema = {
    "type": "object",
    "properties": {
        "boolean": {"type": "boolean"},
        "integer": {"type": "integer"},
        "number": {"type": "number", "maxLength": 20};
        "string": {"type": "stirng", "required": true};
    }
}

let validString: TypeFromSchema<stringSchema>;  // string

let validNumber: TypeFromSchema<numberSchema>; // number

let validBoolean: TypeFromSchema<booleanSchema>; // boolean
// {boolean?: boolean, integer?: number, number?: number, string?: string}
let obj: TypeFromSchema<objectSchema> = {}; 
```

What I would like is to make the same with `booleanSchema` as a `const` instead of `type`. Or be able to extract information of the type to be used in the run time.

## Use Cases

This would enable more interesting data validation, libraries such as Zod mentioned above could work using only type declarations.

## Examples
I am giving some examples here that can be seen as alternative

### Compilation time constants to types

```ts
import model from 'complex-data-schema.json';
type Model = TypeFromSchema<model>;
```

So that I can declare variables of type `Model` enabling IDE assistance and compilation time type checks, and in run time I can use the value `model` for validation of dynamic data.

```ts
declare function Validate<T, U extends SchemaFromType<T>>(data, schema: U): T;
const X = Validate<Model>(fetchData(), model);
```

The object model is mutable, so if I modify it it will become inconsistent, this will behaves like a deep copy, it only consider the value when that line would have been executed.

### Types to compilation time constants (maybe Non-Goal)
The following candidate would be to provide the mechanisms to extract type information
```ts
type Coord = {latitude: number, longitude: number, height?: number};
const CoordProperties = KeysOf<Coord>;
const CoordOptional = OptionalKeysOf<Coord>;
```

or something more generic like
```ts
const ScalarSchema<T extends  string | boolean | number> {
  [k keyof T]:  
    T[k] extends string ? {type: 'string'}:
    T[k] extends boolean ? {type: 'boolean'} ? 
    T[k] extends number ? {type: 'number'} : never;
}
```

These constructs could just inline the data or create a shared variable to avoid increasing too much the size of the code if this is used in many places in the code.

###  Fused Asignment and type declaration (give a new use to the keyword `type`) 

In the following candidate there is an asignment and the definition of an exact type in merged in one instruction. For example `TypeOf(rightAngle) = {angle: number}` is a generalization of `rightAngle`, on the other hand `RightAngle = {angle: 90}` would be an exact type. The same would apply when importing data form JSON or other modules.

```ts
const rightAngle: type RightAngleType = {angle: 90};
import modelSchema: type ModelSchemaType from 'complex-data-schema.json';
````

### Fused type and schema definition (Maybe Non-Goal) 

In the following candidate we would define the type Color and a [schema](https://json-schema.org/) for the specified type is written. This is something that could be use any widespread schema and transformed during the compilation, possibly with a script specified in `tsconfig.json` if required.

```ts
  type Color: schema colorSchema = 'red' | 'green' | 'blue';
```

And `colorSchema` would be set to
```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "string",
  "enum": ["read", "green", "blue"]
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would (in some of its realizations) agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) .

**Comment by RyanCavanaugh** [comment]
What part of this isn't solved by `typeof` already?

**Comment by o-alexandre-felipe** [comment]
For objects typeof gives a generalized type instead of a exact type.

Scalar example gives the exact type, the example below would fail because `red` is not asignable to `typeof color = 'blue'`

```ts
const blue = 'blue';
const red: typeof color = 'red';
```

But in an object it will give a generic type, the next example would compile, because `typeof color = {name: string}`, rather than `{name: 'blue'}`.
```ts
const color = {name: 'blue'};
const red: typeof color = {name: 'red'};
```

Also for arrays, the next example works because `typeof collorArray = string[]`
```
const colorArray = ['red', 'green', 'blue'];
const newColors: typeof colorArray = ['black'];
```

But there are other types that colorArray is asignable to, a few I can think off `[string, string, string]`, `('red' | 'green' | 'blue')[]`, and the strictest one is `['red', 'green', 'blue']` that is the one and be able to derive the others using type transformations that I hope are already available.

**Comment by RyanCavanaugh** [comment]
It sounds like you want to be using `as const` more often

**Comment by o-alexandre-felipe** [comment]
Thank you for pointing me that, I didn't know about this feature. It will certainly help me to get something from schema to type.

[above example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgygeQHJwMYAsIFsCGUC8UA3qJAFxQDOwATgJYB2A5gDRR3DaUD8F8yaTLjZgaAe0g1gdCDwpEA2gGsIICtXrMAun0QoM2HAF8jAKFOloAFXAQAYuKyDDAHitQIAD04MAJpVg9Z1wAPgIoUygoqCsFAHJLOK0Pbwg-ALiNRiY4qG4qWmyKSOjYhNsklJ9-KDiAIzExABsIHAZc-Ibm1oYyEqiyxOSvaoyGAFcsOogaOIAfOMZOJhmOqAmpmb7omPihqrSauJwaGhwQNf6dqAB6G-YmBjEaaExOcRWGCDFxgJOzkCUK47AAUZQ4XEqI0OAX4+iEeHyNkgDjETgMuDc8QhWEoSRCFC+ADcZgBKbalPYVYapdK1MR1ABWEFQwDWRGB0Tu6wgTBarKgwEwUBeAEdxnQXr4oAAzGRNGqYF6cqLKdgMKAqEBiGW7OKiCQzaSyJJaXgxWyo9EIlwAUW8Z1ZWP14kkxrxWmUWjYcOCOBCYSuRighIgJJoAG5zNyhdAAEoACTgUBwqFQEDAwEFwsoOCw0EoIAYwBwnhTf0CyFM3N+2WzBYxeDhUAA7q8cCSU1AiTgmnRpZYAHSmVBiBjUAqaJh+8JEABEljnFDnWWYc+DOACo-HwCj24nXRabRnhHni+Xh566-LUH3u5HY4nG2mNBPxAXtiXUDnz5m183t6PveFi2FADLMqyb4cjsH6QF+c7gSywBziwVxzgaboyJQX7QdcURzpebQ4bBEDwYRDDrqheH4UsvJ-vIJHwbRKw0JRKrfr+rEMeeHGTC+KHfrgngADJpEwQpfgATAADEYUbUd+q5MMRPEroUa5yUGphmKYLRZj2fa+HA6lMBQyL2I4fouJYOqTtkfohBGtz3EpukQPpvb9kgfFbBaKKWY21m2LZnEOU53KcW5HmGQAQo0R69H5FlolZNm6uRYXOVA5FRVQaIQAgTJIWZloBTaiGQY2jlAA)

This resets my expectations to achieve the goal of defining types from schemas, if I achieve this I can release a package it will probably find use. But it would be certainly easier to write typescript and produce the schema, since it is more readable, not as verbose as the schemas. Do you have any suggestion that could help to do that way?

**Comment by castarco** [comment]
I have some cases where `as const` can't do the job. It would be amazing being able to create constant values from single-valued generic types. It would allow to take advantage of monomorphization to perform dynamic checks:

```typescript

interface MyType { ... }

type RecursivePartial<T> = {
  [P in keyof T]?: RecursivePartial<T[P]>
}
type MyFlakyType = RecursivePartial<MyType>

function validateRequired<T>(
  arg: RecursivePartial<T>,
): T {
  // Except for "const", UnionToTupe and GenericKey are already resolved
  const keys = UnionToTuple<GenericKey<T>> // This would be just awesome

  const fieldErrors: IFieldError[] = []
  keys.forEach((key) => {
    if (key instanceof Array) {
      validateNestedField(arg, key, fieldErrors)
    } else {
      if (arg[key] == null) {
        fieldErrors.push({ ... })
      }
    }
  })

  if (fieldErrors.length) {
    throw new ValidationError(fieldErrors)
  }

  return arg
}

```

**Comment by o-alexandre-felipe** [comment]
I got your point @castarco but I also understand that this is a [Non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals) for the project. This would generate a different function for each type, and it won't work in javascript. What can could be done instead, using the initial proposal is to have `validateRequired` receiving information generated by the type as a parameter.

To say in a different way, the `type to constant` mapping cannot work with generic types.

But tank you form posting, who knows this may become a feature in the future.
