### ISSUE TITLE
Missing 4.1.3 version Git tag

### ISSUE THREAD

**Issue by davidlj95** [microsoft/TypeScript#41967]
Version `4.1.3` has been released, but the tag is not in Git:

https://www.npmjs.com/package/typescript/v/4.1.3
https://github.com/microsoft/TypeScript/tree/v4.1.3

Detected by @daviddgl

**Comment by daviddgl** [comment]
> Version `4.1.3` has been released, but the tag is not in Git:
> 
> https://www.npmjs.com/package/typescript/v/4.1.3
> https://github.com/microsoft/TypeScript/tree/v4.1.3
> 
> Detected by @daviddgl

https://github.com/microsoft/TypeScript/tree/v4.1.3 --> 404
I can't see what's new in this version, so I'm not going to apply something that we don't know.

**Comment by RyanCavanaugh** [comment]
Done, thanks

https://github.com/microsoft/TypeScript/releases/tag/v4.1.3
