### ISSUE TITLE
Was the grammar for object literals changed/relaxed?

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#4197]
According to the spec (3.7.3) a comma separating object literal type members is not allowed, but the following currently seems to work. Was the grammar relaxed here?

```
var b: { a: number, b: string };  // this is okay, but invalid according to the spec
```
http://www.typescriptlang.org/Playground#src=%0Avar%20b%3A%20%7B%20a%3A%20number%2C%20b%3A%20string%20%7D%3B

**Comment by RyanCavanaugh** [comment]
The latest version of the spec allows `;` or `,` to terminate object type literal methods.

> ```ObjectType:
>   {   TypeBodyopt   }
> TypeBody:
>   TypeMemberList   ;opt
>   TypeMemberList   ,opt

**Comment by sccolbert** [comment]
Thanks!
