### ISSUE TITLE
GitHub Release v4.1.3 is not listed as latest release

### ISSUE THREAD

**Issue by trivikr** [microsoft/TypeScript#41978]
**Search Terms:**
* 4.1.3 https://github.com/microsoft/TypeScript/search?q=4.1.3+is%3Aissue&type=Issues
* GitHub Release https://github.com/microsoft/TypeScript/search?q=%22GitHub+Release%22+is%3Aissue&type=Issues

**Code**
This is a Release issue related to TypeScript `v4.1.3` and a code sample is not required.

**Expected behavior:**
The `v4.1.3` should be listed at latest release [on GitHub](https://github.com/microsoft/TypeScript/releases)

**Actual behavior:**
The `v4.1.3` is not listed at latest release [on GitHub](https://github.com/microsoft/TypeScript/releases)

Due to this issue, the users which have custom notifications enabled for TypeScript to notify only of new releases would not have got notified of `v4.1.3` release.

<details>
<summary>Screenshot</summary>

![github-typescript-notiifications-settings](https://user-images.githubusercontent.com/16024985/102280558-3c4ad400-3ee2-11eb-9a65-13779d48f30a.png)

</details>

**Playground Link:**
N/A

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/41967

**Comment by trivikr** [comment]
TypeScript `v4.1.3` is now listed as latest release https://github.com/microsoft/TypeScript/releases/

I also got a notification for the release.

<details>
<summary>Screenshot</summary>

![Screen Shot 2020-12-15 at 7 35 34 PM](https://user-images.githubusercontent.com/16024985/102301952-ce67d200-3f0c-11eb-9987-9f9b15e58bbf.png)

</details>

This issue can be closed if this was a one-off bug while releasing `v4.1.3`.
It can be kept open if it needs to be fixed to ensure it doesn't happen again for future releases.

cc @weswigham who created the `v4.1.3` release.

**Comment by david-fong** [comment]
Not sure if I should make another issue for this-

The release incorrectly links to an issues query for TypeScript 3.3 when it should be linking to 4.1.3.

**Comment by gorbunovav** [comment]
@weswigham links to the release announcement and "What's new in TypeScript v4.1.3" are also broken.

**Comment by RyanCavanaugh** [comment]
Fixed the links. Thanks!
