### ISSUE TITLE
Boolean is assignable to `{}`

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#41970]
**TypeScript Version:**  Nightly

**Search Terms:** Empty object, boolean, boolean assignable to object

**Code**

```ts
const x: {} = false;
```

**Expected behavior:**

A compiler error along the lines of "boolean cannot be assigned to type {}"

**Actual behavior:**

Compiles fine.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201211#code/MYewdgzgLgBAHgLhgbwL4wLwwGYEMA2EApgNwBQZokI+RAdPiAOYAUUAngA5EjbwA08AJQkgA

**Related Issues:** (couldn't find any)

**Comment by MartinJohns** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces
