### ISSUE TITLE
Intellisense type detection doesn't handle recursive generator/async functions well

### ISSUE THREAD

**Issue by a-ejs** [microsoft/TypeScript#41988]
vscode 1.52.0

Code (JS):

```js
function a() { return a(); }
function* b() { return b(); } // same with `yield`
async function c() { return c(); } // or `function c() { return new Promise(c); }`
```

Behavior:

All 3 functions show up as `function(): any`.

Expected:

`b` and `c` should return `Generator` and `Promise` respectively.

**Comment by RyanCavanaugh** [comment]
Function circularities always result in `any`; we'd need significant rework of this logic to improve the intellisense here, which doesn't seem particularly high-value
