### ISSUE TITLE
Latest release notes has dead links

### ISSUE THREAD

**Issue by zraineri** [microsoft/TypeScript#41993]
On the release notes for [v4.1.3](https://github.com/microsoft/TypeScript/releases/tag/v4.1.3) the following are broken links:

Both "release announcement" and "What's new in TypeScript v4.1.3." go to
[https://github.com/microsoft/TypeScript/blob/v4.1.3](https://github.com/microsoft/TypeScript/blob/v4.1.3)

Just wanting to let you know, thanks for all the hard work!

**Comment by RyanCavanaugh** [comment]
Thanks!
