### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by eos3tion** [microsoft/TypeScript#41990]
```ts
function a<T, X extends Extract<keyof T, string>, K extends (T[X] extends number ? X : never)>(cfg: T, key: K) {
            let idx = cfg[key] as number;
 }
```

![image](https://user-images.githubusercontent.com/8804051/102317981-82bc3380-3fb3-11eb-90fe-abfb64f9d7e5.png)

expect:  typeof cfg[key] is number

**Comment by RyanCavanaugh** [comment]
We don't have any way to perform this kind of higher-order reasoning

**Comment by eos3tion** [comment]
@RyanCavanaugh 
So that,we don't have any way to get keys with specific type?🥺😞
