### ISSUE TITLE
Feed Type Inference into Anonymous Function Declaration

### ISSUE THREAD

**Issue by mournie** [microsoft/TypeScript#41998]
## Search Terms

type inference scope, type scope, type guard scope, function scope, type lost in function

## Suggestion

Type inferences made outside of a given function scope are neither effected by nor available inside the function scope, this being a contrast to block scope, which is "understood" by TS (including side-effects). Inferences should be available inside anonymous synchronous function declarations that are either executed directly (e.g. `(()=>{x += 1})()`), or by array methods like Array.map. Optionally, inference in the other direction could be made as well; i.e. inference of side-effects; i.e. function scope code effects outer scope inferences in addition to vice-versa.

## Use Cases
1. Common array methods such as Array.reduce and Array.map make functional programming possible in a way that generic loops without a return do not. But without type checks persisting into the (usually anonymous) function argument declarations, we are limited to either block-scoped options or redundant type checking. The difficulty is that this would involve consideration of prior executions of the function argument for prior array elements, but the block-scoped loops already do that - so I don't see why it would be a huge obstacle. Generalizing this behavior beyond inline anonymous function calls and known array methods, though, sounds more difficult to me (for the same reason as the second item below).

2. Type inference is oblivious to variables being set inside function calls (as opposed to assignments done inline in the current scope). This leaves open the door to plenty of simple errors with side effects (which, I know, is why we're supposed to avoid side effects - but it's also why we come up with tools like TS). I understand that this second piece involves tracing every prior function call, and I mention it more as a limitation that could be emphasized a bit more in the docs, and less as a realistic feature request, particularly as it would be a breaking change (as far as I can tell, side effects are mentioned twice in the handbook, neither with any reference to the lack of inference). My apologies if there are help pages on the topic and I've just missed them.

## Examples

```
type t = number | undefined
let val: t

const setUndefined = () => { val = undefined }

const guard = (arg: t): arg is number => typeof arg === 'number'

if (guard(val)) {

    // set val = undefined
    setUndefined()

    // sees val as number. example of #2 above
    console.log(1 * val);

    [].forEach(nothing => {

        // sees val as ambiguous. example of #1 above
        console.log(1 * val);
    })

    for (const nothing of []) {

        // sees val as number. generic loop counterexample of #1 above

        console.log(1 * val);
    }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
cross-ref to #9998

**Comment by RyanCavanaugh** [comment]
See #11498

**Comment by RyanCavanaugh** [comment]
I think this is a "true duplicate" of #11498; the unknown immediacy of invocation is what makes applying the narrowing unsound.
