### ISSUE TITLE
Add information on gulp diff to the contributing guidelines

### ISSUE THREAD

**Issue by jonhue** [microsoft/TypeScript#41991]
I think it might be a good idea to add information on how to use `gulp diff` to [`CONTRIBUTING.md`](https://github.com/microsoft/TypeScript/blob/master/CONTRIBUTING.md#managing-the-baselines) to first set the `DIFF` env variable:

```
DIFF=$(pwd) gulp diff
```

In that file, I also wasn't able to find any information on how to propose changes to the docs (within this repo). Should I just immediately submit a pull request for this? If yes, I think it would also be valuable to add that information to the file. 🙂 

Also, if there's a better way to manually exporting `DIFF` every time, I would love to hear about it!

**Comment by DanielRosenwasser** [comment]
Hm - maybe we should just provide a script like

```
git diff --diff-filter=AM --no-index ./tests/baselines/reference ./tests/baselines/local
```

and then suggest people use a visual differ like Beyond Compare or WinMerge.

**Comment by jonhue** [comment]
@DanielRosenwasser I love that suggestion!

**Comment by jonhue** [comment]
I opened a pull request that replaces the old suggestion with your suggestion on using `git diff`. I think that's already much better 🎉

**Comment by jonhue** [comment]
@DanielRosenwasser, just out of curiosity, are there already some guidelines on how to propose changes to the documentation within this repository as in whether we should first open an issue or directly propose a pull request? I'm not entirely sure if I missed something 😄

**Comment by DanielRosenwasser** [comment]
Thanks for the change @jonhue! I think for small things like this, it's fine to do what you did here. I appreciate having an issue to track things even if they're small.
