### ISSUE TITLE
defaultChecked not recognised for checkbox input in JSX

### ISSUE THREAD

**Issue by NickLydon** [Microsoft/TypeScript#4199]
/// <reference path="../typings/react/react.d.ts" />
    import React = require('react');

    React.createClass({
        render: function() {
	        return <input type="checkbox" defaultChecked="checked" />;
        }
    });

Gives me the error `"src/sample.tsx(6,33): error TS2339: Property 'defaultChecked' does not exist on type 'HTMLAttributes'."`

**Comment by RyanCavanaugh** [comment]
This is controlled by react.d.ts; please send a PR to DefinitelyTyped adding that field to HTMLAttributes
