### ISSUE TITLE
Typesafety in for...in loops

### ISSUE THREAD

**Issue by JonathanTheZero** [microsoft/TypeScript#42009]
**TypeScript Version:** 4.2.0-dev.20201211

**Search Terms:** for ... in loops, typing, typesafety

**Code**

```ts
type keys = "key1" | "key2" | "key3";

type IType = {
    [key in keys]: number;
};

const obj: IType = {
    key1: 1,
    key2: 2,
    key3: 3
};

for (let key in obj) {
    console.log(key, obj[key]); 
}
```

**Expected behavior:**
Key having the type `"key1" | "key2" | "key3"`, allowing me to index the IType object in the for...in loop with it's own keys.

**Actual behavior:**
Key being of type string, throwing the Error ```Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'IType'.
  No index signature with a parameter of type 'string' was found on type 'IType'.(7053)```

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play?target=99#code/C4TwDgpgBA1hIGcoF4oCI4gIxqgH3UwCZcCN4BmNAbgFgAoB0SKASQBVxpUBvBqAVADamKAEsAdrHgIAugC4oEgK4BbAEYQATnXoBfXQwDGAewkJgUE+oBWijlxRQ+9QdOyKsAGn6Diioh9XP0pFCgYDBgYAMxMtKAAKABsIS1FJK1sASmdfAVNzExSAOiSTAHMEzC9MmxF4WSzqKAigA)

**Related Issues:**

**Comment by ExE-Boss** [comment]
See <https://github.com/microsoft/TypeScript/issues/41036#issuecomment-707363495>

---

Also, doing this with `for...in` is worse than doing this with `Reflect.ownKeys`, `Object.keys`, `Object.getOwnPropertyNames` or `Object.getOwnPropertySymbols`, since `for...in` also includes enumerable properties from `obj`’s prototype chain.

**Comment by RyanCavanaugh** [comment]
Object types aren't sealed, so it would be unsound to allow this.

**Comment by JonathanTheZero** [comment]
What about adding the option for Type annotations in for... in loops for example? Something like
```ts
for (let key: keys in obj) { ... }
```

**Comment by MartinJohns** [comment]
That really wouldn't fix the underlying issue.
