### ISSUE TITLE
Question, how to simplfy the declare type QoS = 0 | 1 | 2 judgement when convert from number to QoS

### ISSUE THREAD

**Issue by lygstate** [microsoft/TypeScript#42006]
**TypeScript Version:**  4.1.2

**Search Terms:**
declare type verify

**Code**

```ts
export declare type QoS = 0 | 1 | 2

let qos: number = some_value; 
const finalQos: QoS = (qos === 0) || (qos === 1) || ((qos === 2)) ? qos : 0;
```

**Expected behavior:**
Simplfy the code

**Comment by MartinJohns** [comment]
Questions are better suited for StackOverflow.

https://github.com/microsoft/TypeScript/blob/master/.github/ISSUE_TEMPLATE/config.yml#L4-L7

**Comment by lygstate** [comment]
> Questions are better suited for StackOverflow.
> 
> https://github.com/microsoft/TypeScript/blob/master/.github/ISSUE_TEMPLATE/config.yml#L4-L7

No sure about if TypeScript support for this, if doesn't, then it will turn out to be a feature request.
