### ISSUE TITLE
tsc 2344 emitted when using Parameters, despite resolving the argument type. 

### ISSUE THREAD

**Issue by EyalPerry** [microsoft/TypeScript#42018]
**TypeScript Version:**  4.1.3

**Search Terms:**
2344

**Code**

```ts
type DomainFunction<Request, Response> = (
   request: Request
) => Promise<Response>;

interface CreateRequest {};
interface CreateResponse {};

interface IItemDomain {
   create: DomainFunction<CreateRequest, CreateResponse>;
};

interface DomainObjects {
   item: IItemDomain;
}

export type DomainFuncRequest<
   Domain extends keyof DomainObjects,
   Func extends keyof DomainObjects[Domain]
> = Parameters<DomainObjects[Domain][Func]>;

type CreateItemRequest = DomainFuncRequest<"item", "create">[0];
```

**Expected behavior:**
Code is expected to compile.
CreateItemRequest  should resolve to CreateRequest.

**Actual behavior:**
Although IDE hints that `CreateItemRequest`  resolves to `CreateRequest`, tsc emits the following error in regard to the ` Parameters<DomainObjects[Domain][Func]>` statement:

```
Type 'DomainObjects[Domain][Func]' does not satisfy the constraint '(...args: any) => any'.
  Type 'DomainObjects[Domain][keyof DomainObjects[Domain]]' is not assignable to type '(...args: any) => any'.
    Type 'DomainObjects[Domain][string] | DomainObjects[Domain][number] | DomainObjects[Domain][symbol]' is not assignable to type '(...args: any) => any'.
      Type 'DomainObjects[Domain][string]' is not assignable to type '(...args: any) => any'.ts(2344)
```

**[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIg9gWwIYEsB2AxArmgxsFONAHgCUIBHLCAZ2ABooAFJEAGziQBMA+KAXigAKAFBRxAJ0rU6ALijkqtYCICUAvkwmIUNCMRbtOvANwiR6YBAkAzJLmgBhKUiuKZwKAG8AvmcvWdg5QzhCuEOQ0YER63n7mAbb20ACSKVYI8Mjo3mLiuC5W8lmomDj4hCSh4e7KjNVutNFoejxm8RZoVknBJegA8gBGAFYQ+DS54lAoGfJpGX1o7eYQAB7REp6gkLCIpdh4tXTEebvZaFBrVmhcEwDWECBwNmelQ6Pj9KcHuJer17coA8ni9Fu8xsAaABtRYAXREfEELAkSAQEG6NGIYJGEOhcKhP1hbXM2ychQg6QgCCOnkEix+NOIACIZlSmYwmQUwlYmTwoQAGWEmIA)** 

**[Related Issues](https://github.com/microsoft/TypeScript/issues/36852)**

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't have the higher-order reasoning required to figure that anything produced from that set of constraints would have to match the `Parameters` constraint.

You can add
```ts
   [k: string]: DomainFunction<any, unknown>;
```
to `IItemDomain` to fix that. Alternatively, you could write
```ts
type ParametersOrNot<T> = T extends (...args: any[]) => any ? Parameters<T> : never;
export type DomainFuncRequest<Domain extends keyof DomainObjects, Func extends keyof DomainObjects[Domain]> = ParametersOrNot<DomainObjects[Domain][Func]>;
```

**Comment by EyalPerry** [comment]
@RyanCavanaugh 
Thanks for taking the time to answer this!
What I don't get is how does the IDE (VS Code) know to hint exactly what I expect it to?
