### ISSUE TITLE
Feature Request: Switch Expressions Feature sort of like C#

### ISSUE THREAD

**Issue by pettyron** [microsoft/TypeScript#42011]
It would be an enhanced language feature of TypeScript if there were an available switch expression similar to C#.

A C# example, borrowed from Microsoft's new features video, would be:
```
return (person.FirstName, person.MiddleName, person.LastName) switch
{
    (string fname, string mname, string lname) => $"{fname} {mname[0]}. {lname}",
    (string fname, null, string lname) => $"{fname} {lname}",
    (string fname, null, null) => $"{fname}",
    (null, string mname, string lname) => $"Ms/Mr {mname[0]}. {lname}",
    (null, null, string lname) => $"Ms/Mr {lname}",
    (null, string mname, null) => $"Ms/Mr {mname[0]}",
    (null, null, null) => $"Some Random Person...",
}
```
This is a very useful feature as it makes a Switch much easier to read and maintain. I'm not sure how this could be implemented in TypeScript but it's likely syntactic sugar for a regular JavaScript Switch to be compiled later. Perhaps the TypeScript implementation looks something like:
```
return [person.FirstName, person.MiddleName, person.LastName]: SwitchExpression<[string | null, string[] | null, string | null]> {
  ([fname: string, mname: string, lname: string]) => `${fname} ${mname[0]}. ${lname}`,
  ([fname: string, null, lname: string]) => `${fname} ${lname}`,
  ([fname: string, null, null]) => `${fname}`,
  ([null mname: string, lname: string]) => `Ms/Mr ${mname[0]}. ${lname}`,
  ([null, null lname: string]) => `Ms/Mr ${lname}`,
  ([null, mname: string, null]) => `Ms/Mr ${mname[0]}`,
  ([null, null, null]) => "Some Random Person..."
}
```
## Search Terms
switch, switch statement, switch expressions

## Suggestion
This does walk the line of breaking away from pure JavaScript. However, this is part of C# which follows an ECMA standard. Therefore, it wouldn't be a huge leap to also see something like this available in standard JavaScript in the future. TypeScript also makes use of Decorators which is experimental and this could be categorized similarly.

It would seem highly useful to have a SwitchExpression type to reduce the amount of code and ease maintenance, considering that Switch statements are so widely used.

## Use Cases
The use case is fairly apparent. Often times, Switch statements grow to be fairly large when cases are allowed to grow dynamically, cases must be accounted for when additional properties or properties change over time and when cases themselves have conditional requirements applied to them.

## Examples
As previously referenced take this example from a person tuple:
```
return [person.FirstName, person.MiddleName, person.LastName]: SwitchExpression<[string | null, string[] | null, string | null]> {
  ([fname: string, mname: string, lname: string]) => `${fname} ${mname[0]}. ${lname}`,
  ([fname: string, null, lname: string]) => `${fname} ${lname}`,
  ([fname: string, null, null]) => `${fname}`,
  ([null mname: string, lname: string]) => `Ms/Mr ${mname[0]}. ${lname}`,
  ([null, null lname: string]) => `Ms/Mr ${lname}`,
  ([null, mname: string, null]) => `Ms/Mr ${mname[0]}`,
  ([null, null, null]) => "Some Random Person..."
}
```
I this case we have no idea if the data is always complete. Some people are not given a middle name at birth. Therefore, we must cover the case of null there. Other times we may not be able to make required fields of a given thing. In this case first name and last name are also not required because this application supports higher privacy. Imagine having to write this in a traditional Switch statement. This will be a decent amount of code taking up lines and if cases were to change or more requirements introduced that may grow again. The result is making the code more difficult to understand, the code less readable and the code more difficult to maintain.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* // I'm checking the below box because this is part of C# which is technically on the ECMA standard ECMA-334
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* // I'm not marking the following box because I cannot say for certain if this is a breaking change for TypeScript 1.
* // However, I do feel that it meets all the other expectations.
* [] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> // I'm checking the below box because this is part of C# which is technically on the ECMA standard ECMA-334

The checkbox refers to ECMAScript, not to ECMA-334 or just any ECMA specification.  
Keep in mind that TypeScript is not C#, and it's not intended to.

> // I'm not marking the following box because I cannot say for certain if this is a breaking change for TypeScript 1.  
> // However, I do feel that it meets all the other expectations.  
> [] This feature would agree with the rest of TypeScript's Design Goals.

This would definitely go against goal 3, 8 and 9, and non-goal 1 and 5.

**Comment by pettyron** [comment]
> > // I'm checking the below box because this is part of C# which is technically on the ECMA standard ECMA-334
> 
> The checkbox refers to ECMAScript, not to ECMA-334 or just any ECMA specification.
> Keep in mind that TypeScript is not C#, and it's not intended to.
> 
> > // I'm not marking the following box because I cannot say for certain if this is a breaking change for TypeScript 1.
> > // However, I do feel that it meets all the other expectations.
> > [] This feature would agree with the rest of TypeScript's Design Goals.
> 
> This would definitely go against goal 3, 8 and 9, and non-goal 1 and 5.

I certainly can respect that. And I do realize that it's not any ECMA standard. However, I do feel that JavaScript could entertain a feature such as this. I'm not expecting an implementation of this in TypeScript now or even the near future. But I do feel it's worthwhile to draw some attention to things that may improve a language standard on the whole. 

Also I would remark that I do not want TypeScript to be an imitator of C#. However, this one singular feature could bring some sanity to how Switch is handled both in JavaScript and TypeScript. Obviously, I think this would be a few years away though, honestly.

**Comment by MartinJohns** [comment]
> I do feel that JavaScript could entertain a feature such as this

Then you should bring it to TC39. :-) https://github.com/tc39/proposals

**Comment by pettyron** [comment]
> > I do feel that JavaScript could entertain a feature such as this
> 
> Then you should bring it to TC39. :-) https://github.com/tc39/proposals

That is also on my agenda. Thank you for the input. I'm going to actually close this issue as I'm concluding this isn't yet ready for review or implementation. It should be properly evaluated if or when JavaScript considers such a feature.
