### ISSUE TITLE
Provide a way to express the relation between generic type parameters in union

### ISSUE THREAD

**Issue by cnshenj** [microsoft/TypeScript#42015]
## Search Terms
- union
- generic
- relation

## Suggestion

Express the concept that two generic type parameters are related.

## Use Cases

Please see simplified example below.
A real use case is when using `typesafe-actions` package, trying to create a generic reducer, like this:
```ts
// ? indicates some generic type parameters
export function createPayloadReducer<?>(actionCreator: AsyncActionCreator<?>): Reducer<?> {
  return createReducer<?>(undefined).handleAction(actionCreator.request, () => undefined);
}
```

## Examples
[Playground](https://www.typescriptlang.org/play?#code/PTAEF5K6dv4TAUCUB5AdgU1Acy9gE4CWAxqAC4CeADjjQIaEMC2WFWhoAtKMRaADuAe0IBrAM6gARllIMArhJyCcAE2EYA5AIAWDAG44Kw0FgAeNQlglSKunNYA2DCsU0z2qgpVPU6Ekj+OJhYADwA0gB8EKAA3qBiWFQAXKARoAC+ANxBtCH2nGEAcjHg8aAYrFhpxVm5wejYAKoY7hixoWEARABmwsLdMQA+TeHd0kxDDfmgAKLmFMykFF0AKmWga2aLBGpSXcQYvZzpMQD86aBp2EaEM3Tzi8urLW0e5QtLDCtdoa3tKK5JC9BQYFbtUAAYU0d1eWAAFMI0mhCoQwl8Xv93hgogBKFFvSFxJCgMmgawUBSEDoJJKpUDCAB0VTY9SQmSQKDAiF5fP50G5WxEeAInDIlFmjGYbA4hECjTWIkiABpQAA1TZ05JpCJqgwMJwKGoa9mNOZOZQlNWa2IJVkm4r6w3GtLqs2zJXCAEfYXCHr9QZqgCMIz9PUmhG6aoATEC8o9MT8KF6whtYtsLBwMPtw0cTlw9XxjqdbZcANpF9UAXWulSwdweOCTKy9Po6n2eydTbZxQNAqHLfQG0dAwdroyHkdHMerXNQxVMggYVF8oFImgkSwUK3mlvCTo1MRMnnXwhYjDc0icKn4uj97aFa1MsjPF9cxGvt-sD5xNtALBKAIr7BkIDgdHUxBSMOQamoBW6njGYE+JB0HTkKACSAgaDY2gCCI4jIRBfDQYG3SgKMExTKADA5qaUFjhRoAxiCYIQh4MIYHCXoIiaFpWoemoEr+xKkuSlLUrSiQ6mYLLVM6RomlgTIGop7KZEAA)
```ts
// Note the following code would work if there is only generic type parameter - thus no need to express relations
type Two<K, V> = { key: K, value: V };
type Else<N, V> = { name: N, value: V };
type TwoUnion = Two<"foo", 1> | Two<"bar", 2>;
type ExtractTwo<T> = T extends Two<infer K, infer V> ? [K, V] : never;
type ExtractTwoUnion = ExtractTwo<TwoUnion>; // ["foo", 1] | ["bar", 2]

// No way to construct Else<N, V> to be compatible with TwoUnion
// To be compatible with TwoUnion, V must be 1 when N is "foo", V must be 2 when N is "bar"
// It doesn't work when N is "foo" | "bar" and V is 1 | 2
function ConvertTwo(e: Else<N, V>): TwoUnion {
    return { key: e.name, value: e.value };
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
```ts
type Two<K, V> = { key: K, value: V };
type Else<N, V> = { name: N, value: V };
type TwoUnion = Two<"foo", 1> | Two<"bar", 2>;
type ExtractTwo<T> = T extends Two<infer K, infer V> ? [K, V] : never;
type ExtractTwoUnion = ExtractTwo<TwoUnion>; // ["foo", 1] | ["bar", 2]

function ConvertTwo<K extends "foo" | "bar">(e: Else<K, {"foo": 1, "bar": 2}[K]>): TwoUnion {
    return { key: e.name, value: e.value } as TwoUnion;
}

// OK
ConvertTwo({ name: "foo", value: 1});
// Error
ConvertTwo({ name: "bar", value: 1});
// Error
ConvertTwo({ name: "foo", value: 2});
// OK
ConvertTwo({ name: "bar", value: 2});
```
See also #27808

**Comment by cnshenj** [comment]
Thanks. It works in this example. However, in real world:

1. TwoUnion may be very big
2. It can even be semi-dynamically generated (e.g. in `typesafe-actions`)

Thus, a hand-written `{ "foo": 1, "bar": 2 }` is not practical. What is missing is a way to convert union `|` to properties using a language feature.

**Comment by RyanCavanaugh** [comment]
You can reconstruct that type in a variety of ways; I just wrote it that way for ease of demonstration

**Comment by cnshenj** [comment]
I guess the example I gave is not the best one. Yes, the example can be solved by what you described in a generic way:

```ts
type TwoKeys = TwoUnion extends Two<infer K, infer V> ? K : never;
type U2U<T> = T extends Two<infer K, infer V> ? (K extends string ? { [key in K]: V } : never) : never;
type U2I<T> = (T extends unknown ? (p: T) => void : never) extends ((p: infer I) => void) ? I : never;
type TwoInt = U2I<U2U<TwoUnion>>;

function ConvertTwo<K extends TwoKeys>(e: Else<K, TwoInt[K]>): TwoUnion {
    return { key: e.name, value: e.value } as TwoUnion;
}
```

What if `TwoUnion` is `type TwoUnion = Two<boolean, 1> | Two<string, 2>;`?
