### ISSUE TITLE
The current type in the union types of Promise.allSettled aren't narrowed down properly

### ISSUE THREAD

**Issue by Symasia** [microsoft/TypeScript#42012]
**TypeScript Version:**  4.2.0-dev.20201211 (Present also on 4.1.3)
**Search Terms:** typescript Promise.allSettled union type discrimination, typescript Promise.allSettled not inferring types properly
**Code**

```ts
const promises = [Promise.resolve({ name: "john" }), Promise.resolve({ name: "Mary" })];
const results = await Promise.allSettled(promises);

for (const result of results) {
  console.log(result.name); // Property 'name' does not exist on type 'PromiseSettledResult<{ name: string; }>'.
                            //   Property 'name' does not exist on type 'PromiseRejectedResult'.
}
```

**Expected behavior:**
TSC figures out the current type by discriminating between unions. Like it does with Promise.all.

**Actual behavior:**
TSC does not narrow down the current type and throws an error akin to the following: 

```
Property 'someProp' does not exist on type 'PromiseSettledResult<SomeType>'.
  Property 'someProp' does not exist on type 'PromiseRejectedResult'.
 ```

**Potential workaround for right now**:
Use switch/case statements like the docs recommend to do things based on when the status is "fulfilled" or "rejected", then access the "value" property to get the data that has been returned from the promise (Demo in playground link).

**Playground Link:** https://www.typescriptlang.org/play?target=7&jsx=0&ts=4.2.0-dev.20201211#code/JYOwLgpgTgZghgYwgAgMojgBwM4AsD2YyA3gFDIXLAAmAXMtmFKAOYDc5lEAHsI9vQBG+fABsIcEB0rJqcMHHoAKAJTIAvAD4SnGRQwBbCPUbMQ7XcgC+pG6QT4QjBhhwEwAQXroseQhp0ZGnoAIgBGACYAZhCAGksePjABZCYAVwh4mTkFVUC9CigIMDSoEHyCmUNjZBCAK3xcEBDLGRs22w57R2dsVz8wACFvfvcAsiC6WoAWAFYANjiE3n56dMzLHLg8icqikrKKyv04I1CDOCgATxbj9sobKy7upyI4UVFUYrBxagC4bBXEAIPJaI4OV4uXzubD-ADucGARAAClB8AY+BAAHTvT7fX5KADaqPRmKxRWwYgAbhAlH1oYQPCpYsgSRjsNiKdTafS3IRBioALoqUiWGD4KDIJQQ3qjfz4GBQvnJNS7AoAenVyAAShADPgaalcChsHCkQhcOqEACUIJRPgEABrZCSP5gY3ILFU94ZZCYNGYVqUU3m3B0uVgLGMeRpbCqoMFa0c2owNKiGDAD4Qaghehq46UGVibH2ljhhmR72iDJYraqNSa5AAUW4mAgCEgU15A1r8m2IoLDwT1ksj1FjZbbY78mAjnobLJuK+YB+2dS+FkfAQzAxGEgyDSIFnTmQgiuVGSEHTyFEwEdKAXHJxHxezlx-0BwNB2nzMqI3ZheFERRNF2WxXEiUfTkIEpUQaXLZUmRZKDyRg7kEIGAVhVFGRxUlaUen-CNkAVJUBjjI4ZCLcQsVLDD3F7XIVBUaQhzsJd8WzVQOCAA

**Related Issues:** No

Happy to send a PR if this is not an issue that has been identified :)

**Comment by ctjlewis** [comment]
Ran into my own issue with this. Will investigate when I get a moment.

**Comment by pitaj** [comment]
This also seems to apply to `Promise.all`

**Comment by ackinc** [comment]
> **Code**
> 
> ```ts
> const promises = [Promise.resolve({ name: "john" }), Promise.resolve({ name: "Mary" })];
> const results = await Promise.allSettled(promises);
> 
> for (const result of results) {
>   console.log(result.name); // Property 'name' does not exist on type 'PromiseSettledResult<{ name: string; }>'.
>                             //   Property 'name' does not exist on type 'PromiseRejectedResult'.
> }
> ```

I might be mistaken, but isn't `Property 'name' does not exist...` exactly what you would expect? The objects returned by `await`-ing a `Promise.allSettled` only have keys `status`, `value`, and `error`.

**Comment by ackinc** [comment]
Perhaps `console.log(result.name)` should be `console.log(result.value)`

**Comment by mrmckeb** [comment]
I think I hit this issue today as well.

I've created an example in the TypeScript Playground [here](https://www.typescriptlang.org/play?target=99&ts=4.3.2#code/MYewdgzgLgBBAWICuAbAJgSTMFS0FMAuGAIxBBXwEMwYBeGKAJyXxiolPMpoG4AofqEiwAtgE8ACkxCiAlhDYMO47DAAUASmLTZC-AB5oTOWADmAbQC6APnp3d8xQDom+CBQBu+dRYBEVCTAfgA0MH4EAGZUqFB+VpoCQuDQMJH07BCqwBqa9jAA3vwwMMKpbhCxnMoA7lRysI76zlQoKADK+FBQlGi+xSUwEk2KWiEDJQD0kzAAKvAKcIioaKREEzDTgyP4nd29AErusQbRKIowAD5wzKaWthtbWNDUaGEYMGZdhI8zJTt7Hr4NBHSooKCnVoXa47Iy3czWGw2DYIZDoLA4PBsABk2KGUhkTh8mnGgyWaMw2FwBBgAH58TstDAdITmhUvD4wKgUCSBgkBABfARAA)

```ts
const shouldInclude: boolean = true as boolean;

const myPromise = async (): Promise<string[]> => Promise.resolve(["abc", "default"]);

const f = async () => {
  const results = await Promise.allSettled([
    myPromise(),
    // This should be:
    //   PromiseSettledResult<false | string[]>
    // Instead, I get:
    //   PromiseSettledResult<false | Promise<string[]>>
    shouldInclude && myPromise(),
    shouldInclude ? myPromise() : Promise.resolve(null),
  ]);
};
```

---

@ackinc, I think you want something like this:
```ts
const names = results.map(result => result.status === 'fulfilled' && result.value.name)
```

**Comment by Symasia** [comment]
[Tim Oxley](https://twitter.com/timkevinoxley) made a [tweet](https://twitter.com/timkevinoxley/status/1389940552209256448) about this about how you could avoid the hacky looping, in case anyone else is looking for a more elegant solution here it is:

```js
const tasks = [firstAsyncCall(), secondAsyncCall()]
await Promise.allSettled(tasks) // wait for both
await Promise.all(tasks) // throw if any errors
```

**Comment by SPGoding** [comment]
I fail to see what's the problem here. Shouldn't it be written as something like this instead?

```typescript
const promises = [Promise.resolve({ name: "john" }), Promise.resolve({ name: "Mary" })];
const results = await Promise.allSettled(promises);

for (const result of results) {
  if (result.status === 'fulfilled') {
    console.log(result.value.name);
  }
}
```

**Comment by mrmckeb** [comment]
@Symasia I see you closed this, is this now resolved? I see you shared a workaround in June, but I didn't see a resolution to this.

**Comment by robertino129** [comment]
The fact that this is closed despite all the comments pointing out that it's still BROKEN is mind blowing. It's things like this that make typescript a joke compared to languages like Java. And the fact that I have to write foreach's instead of using filters is ridiculous, considering this was reported 2 YEARS ago. 

Good to know that I should steer clear of such frameworks that completely ignore the community raised bugs.

**Comment by ctjlewis** [comment]
> The fact that this is closed despite all the comments pointing out that it's still BROKEN is mind blowing.

Par for the course w this team. Got the INABIAF virus pretty hard.

**Comment by nickgraz** [comment]
The issue with this example is that `filter` by default returns a `boolean`, not a typeguard. 
```
const results = Promise.allSettled([Promise.resolve({name: "John"}), Promise.reject("oops")])
const fulfilled = results.filter(({ status }) => status === 'fulfilled')
const rejected = results.filter(({ status }) => status === 'rejected')

fulfilled.forEach(result => {
  result.value.name // the compiler should understand that result["value"] is guaranteed here, but it doesn't.
  // instead, it incorrectly requires this:
  if (result.status === 'fulfilled') {
    result.value.name // now it knows that value is accessible, but it should already have known.
  }
})
```

To fix this, all you gotta do it tell the compiler what your filter is "proving" (this is the typeguard).
```
const results = Promise.allSettled([Promise.resolve({name: "John"}), Promise.reject("oops")])
// `result is T` is the typeguard
const fulfilled = results.filter((result): result is PromiseFulfilledResult<{ name: string; }> => result.status === 'fulfilled')
const rejected = results.filter((result): result is PromiseRejectedResult => result.status === 'rejected')

// Now the compiler knows `fulfilled` is `PromiseFulfilledResult<{ name: string; }>[]` and `rejected` is `PromiseRejectedResult[]`

fulfilled.forEach(result => {
  result.value.name // the compiler now knows this exists
  result.value.reason // compiler correctly knows that this does not exist
})

rejected.forEach(result => {
  result.value.name // compiler correctly knows that this does not exist
  result.value.reason // the compiler now knows this exists
})
```
