### ISSUE TITLE
Quick info on implementation is missing JSDoc tags from interface declaration

### ISSUE THREAD

**Issue by Onimishra** [microsoft/TypeScript#42019]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.2

**Search Terms**
- quickInfo
- implement interface

---

When using the "Implement interface" feature in Typescript, the JSDoc of the interface is not included. This makes it difficult to ensure return types, throws and others are upheld in the implementation. [JSDoc provides information to Typescript](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html), and should thus be considered crucial. 

```typescript
interface Animal {
  sound: string;
  legs: number;
 
  /**
  * Send the sound to the SoundEngine
  * @throws {BadSound} Sound has not been initialised
  */
  makeSound(): void;
}
 
class Horse implements Animal {
}
```

Running the "Implement interface 'Animal'" on the Horse class will yield

```typescript
class Horse implements Animal {
  sound: string;
  legs: number;
  makeSound(): void {
    throw new Error('Method not implemented.');
  }
}
```

The JSDoc should be included in this, above the `makeSound()` method.

VSCode info:
Version: 1.51.1
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
My interpretation of this bug is that hovering over `Horse.makeSound` should include the jsdoc tags from the interface. Currently only the documentation is included:

<img width="753" alt="Screen Shot 2020-12-17 at 12 09 46 PM" src="https://user-images.githubusercontent.com/12821956/102538115-c1f48e00-4060-11eb-972c-7edf1a167cf6.png">

I don't think implement interface should copy over JSDoc comments

**Comment by a-tarasyuk** [comment]
At first glance, I thought that need to add JSDoc to a new method :)

```ts
class Horse implements Animal {
  sound: string;
  legs: number;

  /**
   * Send the sound to the SoundEngine
   * @throws {BadSound} Sound has not been initialised
   */
  makeSound(): void {
    throw new Error('Method not implemented.');
  }
}
```

**Comment by a-tarasyuk** [comment]
@Onimishra Am I right?
 
/cc @mjbvz

**Comment by Onimishra** [comment]
Yes, that is the behavior I would expect. Both with Typescript utilizing those JSDoc to enforce parts of it's type-system, but also with being able to describe to the next developer through comments on interfaces, what the implementation should encompass.

**Comment by mjbvz** [comment]
I would not want `implement interface` to duplicate comments. IntelliSense should look back at the documentation on the interface here. I'd only want to add a comment to an implemented property if the implementation itself needs additional clarification/details

**Comment by a-tarasyuk** [comment]
> if the implementation itself needs additional clarification/details

How TS should determine if the implementation itself needs additional clarification/details? Are there any markers for that?

**Comment by mjbvz** [comment]
I expect the comment would  be added by the developer if they feel a comment is needed.

Using the interface's docs by default seems like good conservative behavior

**Comment by a-tarasyuk** [comment]
So, if there is no need to copy the implementation comments, can we close this issue?

**Comment by mohameed7841987** [comment]
الغاء الاشتراك

في جمعة، 18 ديسمبر، 2020 في 12:10 ص، كتب Onimishra <notifications@github.com

**Comment by mjbvz** [comment]
Currently we do not include all the JSDoc tags from the original interface (https://github.com/microsoft/TypeScript/issues/42019#issuecomment-747674061) which I do think is a bug.

We could either update this issue to track that or open a more specific issue to track including the JSDoc tags. I'll leave that up to the TS team

**Comment by mohameed7841987** [comment]
الغاء

في سبت، 19 ديسمبر، 2020 في 1:13 ص، كتب Matt Bierner <
notifications@github.com>:

**Comment by RyanCavanaugh** [comment]
@mohameed7841987 please stop leaving spammy comments in our repo, or we'll be forced to block you from the entire organization

**Comment by RyanCavanaugh** [comment]
@mohameed7841987 I believe you have accidentally "watched" the repo and this is why you're getting emails. Instead of replying to them, click the "Unwatch" button 
![image](https://user-images.githubusercontent.com/6685088/102662347-8676c400-4133-11eb-87d8-0035bd2bff8f.png)

**Comment by andrewbranch** [comment]
I agree with @mjbvz—implement interface should not copy comments, but the tags from the interface should be reflected in the implementation’s quick info. Retitled the issue to reflect that.
