### ISSUE TITLE
Discriminated Union only auto resolve when it's basic props, not within callback

### ISSUE THREAD

**Issue by alex83130** [microsoft/TypeScript#42023]
**TypeScript Version:**  4.1.2

**Search Terms:**
interdependent props, `Union` changed for an `Intersection`, Discriminated Union

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Since I use `Discriminated Union` I would like to have a Union within the callback as well. 

**Actual behavior:**
Within the callback, I have an intersection instead of Union. But that work well with basic param (Exemple `selected` in the Playgound)

**Playground Link:** 
[Playground](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0MwAUVWDEQNUgADVHBQGNJ3KAALygABEAAkYNAMOB4GRogLFFTBPB3AExcwABT0xnM9zsyhc9wASmCKhwDQ8ZC8iElzhB7Bo3zcZmY7AYzEg-Fg0HUiS58D0Ii8AoZTJZggFSRxAvADlQAHJhAA5SASAVBFQAeW+ZF2gldWkgx1QjgUrmkeFATgtOlGWH0KAQiBhwiudokkuiIgMHBx3RYbC43CCJUUGQUZGSPRQqeoFHgXgA3ooSjoGNB2JB8tdUJROMwANwL+3SGDrmlb3eKAC+wWHPzHdQAwkgLZxaGwCMJ5yUEUDuZBuAB+dcQQVDxOD3c89yHbYb3HUBiGhFliBgSBYCLUAP2uJCUN-ddJ1QadQP3Gc7wcbc11AFV4CnGccKozg9T5AA+UAdHgChuDAq8oNHGCAFkojwhDMNQ9Ds3cLDuBovCZwAbQAXT3EoiJIl11wo2jJPwuT6N5JiWLYjjFFQFpYKEl9KOEfkH3rGczLfUAADJyLgzUSCE39QAAH1APjoAE9xELEos9Qg2UZxpMQADEuBQ-CSn5FVZ1E5Ci34JSHUgc91wC5LbMEbSmPnfcShAHB9FhT4kvE-gWzIRIpGgaB+HkWNjAeTh8KK9FqVpbUNJnTzQFwzTZL5DDAt-TqGG1YISmK4BSvCj5NDS0j+B+NgyH4O02tihxhFMUjXGSSVjAASS47MYpnTr3BoThEyG6jBto0bZyXFcyOjKbl1XaN+EYQ9oHXL6Xi5GBo0vWakk4Yj0pVe6JEeuiLyAA)

**Related Issues:** 
#40647, #12184

Seems like it's issue that has brought a bunch of times, but I'm wondering why we still need to do the 
```
function isCase1(props: AllProps): props is Case1 {
  return !!props.aParamOfCase1;
}
```
Only for the callback function

**Comment by RyanCavanaugh** [comment]
This is a correct error; if this were allowed it'd be straightforward to inhabit an `Option[]` with an `Option`, which is unsound

**Comment by alex83130** [comment]
It's a `SimpleSelected | MultipleSelected` so a  `Option | Option[]` then `newOption` which is of type `Option` should be accepted. I'm kind of confused...

**Comment by RyanCavanaugh** [comment]
```ts
// This call is legal, but crashes
aFunction({
  selected: [], onChange: (a: Option[]) => {
    console.log(a.indexOf(a[0]));
  }
});
```
