### ISSUE TITLE
Missing codefix with 'This may be converted to an async function' suggestion diagnostic

### ISSUE THREAD

**Issue by orassayag** [microsoft/TypeScript#42034]
Is there any way to remove this specific tooltip message? It would be great to add this option. Thanks.
![102495189-78b33700-407e-11eb-96c5-b7bd10999bca](https://user-images.githubusercontent.com/5759067/102591186-4b1bcb80-411a-11eb-99ba-2bd3f63374ae.png)

**Comment by a-tarasyuk** [comment]
I think this is a bug, this message should be visible with the Quick Fix action. @orassayag could you add a code example that produces this message?

**Comment by orassayag** [comment]
> I think this is a bug, this message should be visible with the Quick Fix action. @orassayag could you add a code example that produces this message?

Example:
```
    const readline = require('readline');
    confirm(settings) {
        const readLine = readline.createInterface(process.stdin, process.stdout);
        return new Promise((resolve, reject) => {
            try {
                readLine.on('line', (line) => {
                    switch (line) {
                        case 'y': resolve(true); break;
                        default: resolve(false); break;
                    }
                    readLine.close();
                }).on('close', () => { resolve(false); });
            }
            catch (error) { reject(false); }
        }).catch();
    }
```

**Comment by andrewbranch** [comment]
Minimal repro:

```ts
function foo() {
    return Promise.resolve().catch();
}
```

This is a bug that consists in a mismatch between `isConvertibleFunction` in `suggestionDiagnostics` and the actual convert-to-async codefix—either the former should return `false`, or the latter should return a fix.
