### ISSUE TITLE
Shouldn't GenericTransformStream be generic?

### ISSUE THREAD

**Issue by morganbarrett** [microsoft/TypeScript#42043]
https://github.com/microsoft/TypeScript/blob/a763600cc4f50d864d163a885718b32c04f7f10a/lib/lib.dom.d.ts#L5653-L5673

Should this not be the following?

```typescript
 interface GenericTransformStream<R = any, W = any> { 
     readonly readable: ReadableStream<R>; 
     readonly writable: WritableStream<W>; 
 } 
```

**Comment by RyanCavanaugh** [comment]
Is this just an idle observation? Please follow the templates.

**Comment by morganbarrett** [comment]
More of an enquiry as to whether there is good reason for this.

**Comment by RyanCavanaugh** [comment]
The definitions are generated from the IDL, and the IDL doesn't have generics unless we explicitly add them

**Comment by morganbarrett** [comment]
Would it be worth me adding a feature request for this generic to be added?

**Comment by RyanCavanaugh** [comment]
You can if you'd like
