### ISSUE TITLE
Improve error message for class declared with Symbol prop  - "is declared here"

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#42059]
**TypeScript Version:**  4.1.2

typescript "is declared here"

**Code**

```ts
export const BunionFieldMarker = Symbol('bunion-field-marker');

export class BunionFields {
  [BunionFieldMarker]: boolean
  [key: string]: string
}
```

**Expected behavior:**
should compile?

**Actual behavior:**
I get this:

```
  lib/bunion.ts:70:3
    70   [BunionFieldMarker]: boolean
         ~~~~~~~~~~~~~~~~~~~
    '[BunionFieldMarker]' is declared here.

```

I am not sure what that error means -at the very least the error message could be improved to help me debug? thx

**Comment by MartinJohns** [comment]
Here*s a [playground link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wEIFdkEsUBiuwANgCYCyAhlANbBRwC8cAygJ4C2ARhCQBQBybjnzIAtADNi5cZxr0oggJQBuALAAoLaEixEJKqlRxseQjLImA3lrhwA2mbFFSlBQwC6ALji8+wFTIdo707L7oULjIAOY+cJHRMVoAvlpAA), which you omitted.

I don't see the error you report.
