### ISSUE TITLE
TypedArrays missing signature

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#4206]
Hi,

Is it wanted this signature is not availlable in default lib.ts on all typed array :

    set(array: Array<number>, offset?: number): void;

I don't look to specs, but it's working everywhere on typed arrays and it's not the case for other methods like fill, reverse, foreach, etc.

It's not a big deal to had this on a custom missing signature file, but it doen t make sence for me having stuff that doesn t work and not stuff that already work.

Regards.

**Comment by danquirk** [comment]
Signatures here do seem wrong.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set
```ts
typedarr.set(array [,offset])
typedarr.set(typedarray [,offset])
```
whereas our definition for ```Uint8Array``` has these two signatures:
```ts
set(index: number, value: number): void;
set(array: Uint8Array, offset?: number): void;
```

**Comment by Eyas** [comment]
What is the correct resolution here? The current `core.d.ts` has:

```ts
set(index: number, value: number): void;
set(array: ArrayLike<number>, offset?: number): void;
```

The second variable takes care of both MDN cases:

```js
typedarr.set(array [,offset])
typedarr.set(typedarray [,offset])
````

Judging by the MDN link, we should simply remove the first overload. [MSDN, on the other hand,](https://msdn.microsoft.com/en-us/library/br212929(v=vs.94).aspx) claims that this overload is valid:

```js
uint8Array.set(index, value);
uint8Array.set(array, offset);
```

If MSDN is right, then there is no valid work item for this issue; it should be closed. If MDN is right, then we should change this ticket to refer to removing the first overload, and resolve it accordingly.

**Comment by DanielRosenwasser** [comment]
Sounds like this is fixed; @zhengbli can you confirm?

**Comment by zhengbli** [comment]
This is fixed, as now another signature is added for all the typed arrays:
``set(array: ArrayLike<number>, offset?: number): void;``
