### ISSUE TITLE
'default' is referenced directly or indirectly in its own type annotation

### ISSUE THREAD

**Issue by sKopheK** [microsoft/TypeScript#42061]
**TypeScript Version:**  4.2.0-dev.20201219
latest VS Code, JS project with `checkJs: true`

**Search Terms:** 
default, indirectly, annotation

Hi, I'm really clueless why is this happening. It's really hard to track the error as it disappears everytime I do any code updates and is back after like 20 seconds. What does the error even mean? *default* is a keyword, isn't it.

**Code**
![image](https://user-images.githubusercontent.com/5802917/102778417-70167580-438a-11eb-8540-bda7f5522e76.png)

**Expected behavior:**
no error

**Actual behavior:**
A wild error `'default' is referenced directly or indirectly in its own type annotation.` appears.

**Comment by RyanCavanaugh** [comment]
Can you post the code to reproduce this? We are not able to transcribe screenshots
