### ISSUE TITLE
In JS, @type tag doesn't apply generic type to initialiser

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#42060]
**TypeScript Version:**  4.2.0-dev.20201219

**Search Terms:** template type lost js

**Code**

```js
/** @template T @typedef {<T1 extends T>(data: T1) => T1} Test */

/** @type {Test<number>} */
const test = data => data
```

**Expected behavior:**
data has type `T1 extends number`

**Actual behavior:**
data has any type
![изображение](https://user-images.githubusercontent.com/24425566/102770302-59c5e500-439d-11eb-89af-4971bc4880f6.png)

**Comment by sandersn** [comment]
Note that if you call the function, the type, and the errors are correct:

```js
test(1) // T1=1
test('hi') // error, and T1=number (the default)
```

It's just not applying the type to the initialiser. Might be a bug in contextual typing?

**Comment by sandersn** [comment]
This behaviour is the intended effect of #26236, which says it's trying to avoid circular return type errors. But the bug it fixes only mentions typescript.

I'm going to turn off the erasure to any and see what tests fail.

**Comment by sandersn** [comment]
No tests fail; #26236 never tested the type tag erasure change and it doesn't look correct to me. I'll remove it and send a PR.
