### ISSUE TITLE
Default generic values are lost when InstanceType used to infer return type of a constructor

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#42064]
**TypeScript Version:**  4.1.3

**Search Terms:**

infer generic default InstanceType 

**Code**

```ts
type Newable = new (...args: any[]) => any;

function construct<T extends Newable>(type: T): InstanceType<T>{
    return new type();
}

type Cars = "Porsche" | "BNW" | "Mercedes";

class Collection<T extends string = Cars>{

    addItem(item: T){}

}

const instance = construct(Collection); // typed as MyClass<string> NOT MyClass<Cars>
```

**Expected behavior:**

`instance` should be typed as `MyClass<Cars>`

**Actual behavior:**

`instance` should be typed as `MyClass<string>`

**Playground Link:** 
[link](https://www.typescriptlang.org/play?#code/FDAuE8AcFMAIDloHcCGAjANnAvLAdsrABQB0ZKATgOYDOAXLCnuANoC6AlLNgHyPMBuEADMArngDGoAJYB7PLAnyaoCqKkAeACqxoAD1DQ8AExoJk6LDyIQYDLRwYBJPCqYToWqNG08A3sCwQbAU0KCiFAoESLC20EQcQgC+IHGwAMKUZrgARAAKshQ0EgAW0DmwAD6wOQBC8ADqFdU5ALLQFB7G0DQ5QsASGCg0ZumyGFhScnjaugZGprAqFNJ4VNwZWf4gwYzGxk6GALZE0sf2HH4pwNdKrqCwq26SOIrKquqgRGMT0FPyiVgAHogbFvMZGGZWuB0kMRhplqsqHx4AB5HTQ2HDGgaTJFHjAIA)

**Comment by RyanCavanaugh** [comment]
The default only applies during a direct call when no inference candidates are present. Defining `InstanceType<typeof Collection>` to be `Cars` would be unsound.
