### ISSUE TITLE
Nested array/object types 6+ deep can break typechecking for smaller nested types across the entire file

### ISSUE THREAD

**Issue by mkantor** [microsoft/TypeScript#42070]
I noticed that [you can assign a 5D array value to an array type that requires 6 or more dimensions](https://tsplay.dev/yNa9BN). That's unfortunate, but the more concerning thing is how [doing so can apparently break typechecks for nested arrays of any depth across the whole file](https://www.typescriptlang.org/play?#code/PTAEEEBtNBDBneBLA5gOwLYFM0Bd6hJqi4AWSBAZkpFnAE51EBuskSAJgDSgBGArrgY4A5EMYArLAGNcWDnwCeJUnVyKADjNXSA1lnoA6AFDGQoAKpppAewzY8KinDQL4-DhxyRlZOo3ghG0oVOmpaQgJ1LWkdfQVbekZZHwBCMzBbNEC4ACYALlBA+iIUAG0AXUrQAF5QMsqKjNAsnNhcgGVSG35IDgAxWBpC4tLquvbm1qF2rp6+qHgbQeGi3BK0cqrt2rzTcwBhOwchMmcemddQ0ACgkL9QcKYozW0ZeJabJJlcNONpuAANhG6zG20qEJ2dQaMMaFXhTQBsEBc16AyGkBBGy2kMhu2R-xs2RmKO6aMWywxWLBuPBUKBpgBvAKa2xeOhjUJxL4nTJfRWmNZYN2zK5OWZqIWkCWAupm1pIty+zAgIA1KAvBoyEUsFgMFEbHw1KoSEgNBpSqANDYiLgANw6uhsJaFUi4XAaeD5ED4DSQWCKQxeZjARQAOVgAE4AEJhoA).

A similar thing [happens with deeply-nested object types](https://www.typescriptlang.org/play?#code/C4TwDgpgBA6gTgQzAHgCoD4oF4oG8oIBcUqUAvgFAWiRQDyAdhACIQRjayIoDOwcASwYBzdNXDRUAdwD2rdp3hJkjFmzBiakgBZw28jjiUppc9ZolQAYjICucA4u5pd+8+NpWBANzUKjzjb2Bha0AMoCAB6OAcpeviEe0GEQvgwxXMoR0e4UAPR5UACqDADGMgC2FRAMwFDA2gI8BAwAJlA8tq2tNQA2IPXa0Hp8UDIAZoPQ4wK90E31EqVDpQDWEO3lcHqlwP0AhPmF5QyjwLLEphm4RDeEAOT3ZJQFUCejMkxh2na9rVYIWbEVQZc4yI5vT5nVwQb6-f6A3qXGGg2RUV4AYUq1VqgwWdjqCDaUygIzqExJMzmUAWWmWEDWG0h2wZexAh3edR4UWI2WutwFhDuwqIj2e4sonKgM18cNsfwBQOsPj8hg6UQoUp4qRqcoViN5OvS6k43MiVClYIAQpdZPyhaKnpKoeSvj95QjZjb6ExUTIrZqXYM9LD3fqvciQ36AxCUtAEL0eDJiNpgMAwDxCAVgDwwL0ECAAHQ9bx5K0VSIAGQAjBUgA).

[The depth limiter for nested instantiations](https://github.com/microsoft/TypeScript/issues/34619#issuecomment-546325281) seems relevant, especially since the magic number here is 6 (or really "anything more than 5").

---

**TypeScript Version:** 4.5.2, 4.2.0-dev.20201221 and all other versions tested (3.3.3-4.1.2)

**Search Terms:** "multidimensional array" "deep array" "nested array" 6D "six-dimensional" "nested object" "deep object" "depth limiter" "deeply-nested" isDeeplyNestedType

**Code**

```ts
// All assignments in this file are invalid, but aren't rejected by the typechecker.

// Uncomment this and suddenly the rest of the file is typechecked correctly!
// const a2: string[][] = [[]]
// const a2ShouldFail: string[] = a2
// const a2ShouldAlsoFail: string[][][] = a2

// Comment this out and the rest of the file is typechecked correctly!
const a6: string[][][][][][] = [[[[[[]]]]]]
const a6ShouldFail: string[][][][][] = a6
const a6ShouldAlsoFail: string[][][][][][][] = a6

const b2: string[][] = [[]]
const b2ShouldFail: string[] = b2
const b2ShouldAlsoFail: string[][][] = b2

// 6+ depth seems to be the tipping point; see also: https://tsplay.dev/yNa9BN
```

**Expected behavior:**
Those mis-typed variable assignments should be flagged by the typechecker. More importantly, typechecking for each term should not be affected by the presence/absence/source order of unrelated code.

**Actual behavior:**
TypeScript doesn't complain about anything unless you uncomment the first block of code or comment out the second one.

**Playground Link:**
https://www.typescriptlang.org/play?#code/PTAEEEBtNBDBneBLA5gOwLYFM0Bd6hJqi4AWSBAZkpFnAE51EBuskSAJgDSgBGArrgY4A5EMYArLAGNcWDnwCeJUnVyKADjNXSA1lnoA6AFDGQoAKpppAewzY8KinDQL4-DhxyRlZOo3ghG0oVOmpaQgJ1LWkdfQVbekZZHwBCMzBbNEC4ACYALlBA+iIUAG0AXUrQAF5QMsqKjNAsnNhcgGVSG35IDgAxWBpC4tLquvbm1qF2rp6+qHgbQeGi3BK0cqrt2rzTcwBhOwchMmcemddQ0ACgkL9QcKYozW0ZeJabJJlcNONpuAANhG6zG20qEJ2dQaMMaFXhTQBsEBc16AyGkBBGy2kMhu2R-xs2RmKO6aMWywxWLBuPBUKBpgBvAKa2xeOhjUJxL4nTJfRWmNZYN2zK5OWZqIWkCWAupm1pIty+zAgIA1KAvBoyEUsFgMFEbHw1KoSEgNBpSqANDYiLgANw6uhsJaFUi4XAaeD5ED4DSQWCKQxeZjARQAOVgAE4AEJhoA

**Related Issues:**
- https://github.com/microsoft/TypeScript/issues/21771
- https://github.com/microsoft/TypeScript/issues/34619
- https://github.com/microsoft/TypeScript/pull/34742
- https://github.com/microsoft/TypeScript/pull/41972
- https://github.com/microsoft/TypeScript/pull/14825
- https://github.com/microsoft/TypeScript/issues/41617
- https://github.com/microsoft/TypeScript/issues/34922

**Comment by mkantor** [comment]
Please let me know if I should split this into two separate issues ("5D arrays can be assigned to 6+D array types" vs "6D array types can break of unrelated 2+D array types elsewhere in the file").

**Comment by mkantor** [comment]
Playing around some more I noticed some extra nuance that might help track down the bug. Observe the difference in behavior between these two scenarios:

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgNgFw2gJwJZgOYG0C6BRhJMAvDLldfrXQFAD0jMoksiAygBYgCuAGwAmAMTgYBKdFjwliBcvAT020JT37CAggIggxEqVEw55c84sT0V4NQCMATEZOyFFKrRvsYjjYNHikqjGMm4+DjDMMGAgAO4wUNwYEAkAngAOAKbA3NkA1imgaGjZUAKpMAAUcBAQGNhgMjAAcgAi8MVwFVAgLQC0AIztUBmZAJRe9g5+2rr6gc6hFhSOkSx2fLCJyTBCIJkQYADksNW19Y04Le1wnd29zQDUQ2lZE6qwvrz+Onq-84Zgi4zGFVlFtik4HNonFXtlcsACqwQMVSuUqjU6g0mm0OmgugkHo8HMNRmMgA

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgNgFw2gJwJZgOYG0C6BRhJMAvDLldfrXQFCiSyIDKAFiAK4A2AJgDE4GHinRY8JYgXLwE9APQKYTaHI7d+AQR4QQQkWKiYc0qedmJ6jcGoBGAJiMnJMilVo3mMRxt6DhUVRjCTcfBxglGDAQAHcYKHYMCBg+EABTCDAAclgoAE8AB3TgdhKAaxUQNDQSqB58mAAKOAgIDGwwCRgAOQAReBq4RqgQXoBaAEYBguKASi97Bz9tXX1A51CLCkdI5U5Y9IA3dLQEpJS0zObW9s7u-sG0YYSxnoBqaYSi9IXVWF8nH8Oj0IPWhmCLjMYV2UTgYD4qDGVxSiWSNzaHS6OF6AzgQxGb3eDhmPzmQA

**Comment by mkantor** [comment]
I just realized the same thing happens with nested objects:

https://www.typescriptlang.org/play?#code/C4TwDgpgBA6gTgQzAHgCoD4oF4oG8oIBcUqUAvgFAWiRQDyAdhACIQRjayIoDOwcASwYBzdNXDRUAdwD2rdp3hJkjFmzBiakgBZw28jjiUppc9ZolQAYjICucA4u5pd+8+NpWBANzUKjzjb2Bha0AMoCAB6OAcpeviEe0GEQvgwxXMoR0e4UAPR5UACqDADGMgC2FRAMwFDA2gI8BAwAJlA8tq2tNQA2IPXa0Hp8UDIAZoPQ4wK90E31EqVDpQDWEO3lcHqlwP0AhPmF5QyjwLLEphm4RDeEAOT3ZJQFUCejMkxh2na9rVYIWbEVQZc4yI5vT5nVwQb6-f6A3qXGGg2RUV4AYUq1VqgwWdjqCDaUygIzqExJMzmUAWWmWEDWG0h2wZexAh3edR4UWI2WutwFhDuwqIj2e4sonKgM18cNsfwBQOsPj8hg6UQoUp4qRqcoViN5OvS6k43MiVClYIAQpdZPyhaKnpKoeSvj95QjZjb6ExUTIrZqXYM9LD3fqvciQ36AxCUtAEL0eDJiNpgMAwDxCAVgDwwL0ECAAHQ9bx5K0VSIAGQAjBUgA

**Comment by zifahm** [comment]
any workaround?

**Comment by mkantor** [comment]
@zifahm I believe this was fixed by #46599 which was included in TypeScript 4.5.3, so if you can upgrade your compiler that might help.

I haven't done extensive testing yet but at least the playground links above all exhibit the correct behavior when using 4.5.3. Let me know if you upgrade and still see problems, if not I'll probably close this issue.

**Comment by zifahm** [comment]
@mkantor  I'm trying to do something like this, still, seems to show an error? or am I doing something wrong?

https://www.typescriptlang.org/play?ts=4.5.3#code/AQFwngDgpsDyBOATK8Bi8CGBzAtlAdiMALzADeAUMNcAPq3jT4Z4D8AXMAOQLLxcBuKjQCWiTgGcQ8EfixCawAPZIUABXhLEAVwDGITgEF4mMAB5KixfUYEWUDt17rNO-YOFXgYydNnzPKxU+AFktEQAzERRHY1MLQK9qG0g7Nk4eVXgwxEjo-gUkxR9gKRk5QqLqYJQcvJQAZSgDYDiMc0sqrxSme0dM0PCoxuaPLq8Ssv9KqoBfAD4ZxQXgAB9gfG0AGy214G18ZCj8KEQZhaFZoQpbUuaJEjgs9Gw8QgBtACIa+A0tPRAnwAuu8AAwg75ZOrDeDAsEQn7Q-JNQEg8EUCgAekxwBQmngwAwRERQ3y8KxOL+0Hg4G4oK4wEQSigD3wSiIUAAHiIpMp8KBUsAKdwyHQGKlmOlgJ9nNlSShPnsDkdZKcBN5xKU-BVlFD5fAUZxRT00g5ODK9bkYSjFetlVBjmqNb5yvJgLN3kD1R6gXtNjslYcHarEFwAHQACgATABmGMATgAlEA

**Comment by mkantor** [comment]
@zifahm your `OrderFragment` type specifies that `OrderFragment["orderProduct"][0]["orderModifier"]` is optional and possibly `null`.

Your playground has an error for the same reason that `type X = (unknown[] | null | undefined)[0]` is an error

**Comment by zifahm** [comment]
@mkantor  yeah just got it thanks :)

**Comment by mkantor** [comment]
Since I haven't been able to reproduce this issue since 4.5.3, I'm closing it. I'm very happy to see the depth limiter getting smarter! 🎉
