### ISSUE TITLE
Type narrowing fails to remove undefined/null with ?. and ??

### ISSUE THREAD

**Issue by eamodio** [microsoft/TypeScript#42074]
**TypeScript Version:**  4.1.3

**Search Terms:**
type narrow
null coalesce

**Expected behavior:**
Both if statements should work without error -- e.g. the type should be narrowed to no longer included `undefined` or `null`

**Actual behavior:**
Type is not narrowed

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/38136

**Code**
```ts
function foo(decorations?: any[]) {
	// Works
	if (decorations?.length) {
		for (const d of decorations) {
			console.log(d);
		}
	}

	// Fails
	if (decorations?.length ?? 0) {
		for (const d of decorations) {
			console.log(d);
		}
	}
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function foo(decorations) {
    var _a;
    // Works
    if (decorations === null || decorations === void 0 ? void 0 : decorations.length) {
        for (const d of decorations) {
            console.log(d);
        }
    }
    // Fails
    if ((_a = decorations === null || decorations === void 0 ? void 0 : decorations.length) !== null && _a !== void 0 ? _a : 0) {
        for (const d of decorations) {
            console.log(d);
        }
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ssl=16&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABMOcAUATAphOAnAQ1gQGcB+ALkQLAE8BtAXQEpEBvAKAEgB6HxAOr4A1iW4xgiTDnxF4YcgDoANljABzKAAtWnLlxR4puBVEQZEcSdlyFiC3d30mScVSrjrMzANxOAvtyB3HyIAGIEMMpiXBJSNrL2Sqoa2ohkZIgADI76hsakZhZW5jJ28iS5zqRuWB5eGL4BQRyBQA)

**Comment by RyanCavanaugh** [comment]
There are three cases to consider here with regards to the right operand of `??`
 * It's always truthy, in which case the truthiness of the LHS is irrelevant
 * It's always falsy, in which case it does nothing and there's no reason for you to have written it that way
 * It's possibly either, in which case we can't say anything meaningful about the truthiness of the LHS

Thus it isn't handled

**Comment by eamodio** [comment]
I'm not following. In this case, `decorations` can't be `undefined` inside that `if` statement -- yet TypeScript errors that it can be.

**Comment by RyanCavanaugh** [comment]
We can only narrow in places where we detect that there's a syntactic pattern that could induce a narrowing. The form `x?.y ?? z` isn't in that list of patterns because, as noted, for "normal" code that pattern can't usefully narrow `x`.

If a lint rule is causing you to write non-normal code, we always recommend not turning that rule on. Maybe `!!decorations?.length` would work, though?
