### ISSUE TITLE
TS produce different result while handling function overloads

### ISSUE THREAD

**Issue by tianzhich** [microsoft/TypeScript#42072]
**TypeScript Version:**  v4.2.0-dev.20201221

**Search Terms:** I'm sorry I don't know how to search this.

**Code**

```ts
export interface Action<TPayload = any, TMeta = any> {
    payload?: TPayload
    meta?: TMeta
}

type TPayload = number | undefined
type TMeta = Record<string, any> | undefined

type DispatcherForBar<TPayload = void, TMeta = void> = [TPayload, TMeta] extends [void, void]
    ? (() => Action<void, void>) & { isEffect: false }
    : TMeta extends void
    ? undefined extends TPayload
    ? ((payload?: TPayload) => Action<TPayload, void>) & {
        isEffect: false
    }
    : ((payload: TPayload) => Action<TPayload, void>) & {
        isEffect: false
    }
    : [undefined, undefined] extends [TPayload, TMeta]
    ? ((payload?: TPayload, meta?: TMeta) => Action<TPayload, TMeta>) & {
        isEffect: false
    }
    : undefined extends TMeta
    ? ((payload: TPayload, meta?: TMeta) => Action<TPayload, TMeta>) & {
        isEffect: false
    }
    : ((payload: TPayload, meta: TMeta) => Action<TPayload, TMeta>) & {
        isEffect: false
    }

/**
 * type Bar = (((payload?: TPayload) => Action<TPayload, void>) & {
    isEffect: false;
}) | (((payload: TPayload, meta: Record<string, any>) => Action<TPayload, Record<...>>) & {
    ...;
})
 */
type Bar = DispatcherForBar<TPayload, TMeta>

let bar: Bar;

/**
 * let bar: (payload: TPayload, meta: Record<string, any>) => Action<TPayload, void> | Action<TPayload, Record<string, any>>
    Variable 'bar' is used before being assigned.(2454)
    Expected 2 arguments, but got 0.(2554)
    input.tsx(27, 9): An argument for 'payload' was not provided.
 */
bar();

/**
 * type Baz = ((payload?: TPayload, meta?: TMeta) => Action<TPayload, TMeta>) & {
    isEffect: false;
}
 */
type Baz = [TPayload, TMeta] extends [void, void]
    ? (() => Action<void, void>) & { isEffect: false }
    : TMeta extends void
    ? undefined extends TPayload
    ? ((payload?: TPayload) => Action<TPayload, void>) & {
        isEffect: false
    }
    : ((payload: TPayload) => Action<TPayload, void>) & {
        isEffect: false
    }
    : [undefined, undefined] extends [TPayload, TMeta]
    ? ((payload?: TPayload, meta?: TMeta) => Action<TPayload, TMeta>) & {
        isEffect: false
    }
    : undefined extends TMeta
    ? ((payload: TPayload, meta?: TMeta) => Action<TPayload, TMeta>) & {
        isEffect: false
    }
    : ((payload: TPayload, meta: TMeta) => Action<TPayload, TMeta>) & {
        isEffect: false
    }

let baz: Baz;

// work as intended.
baz();
baz(1);
baz(1, { 'baz': 1 });
```

**Expected behavior:**
There is a complex type aliased as `DispatcherForBar`. It seems that TS produces different results while using aliased type and the type itself(they are totally the same code). So I got different function overloads and failed to work.

`Baz` and `Bar` should be the same. Even they look differently, they should work in the same way.

**Actual behavior:**

`Baz` and `Bar` have different results about function overloads which also works in a different way.

**Playground Link:** 
[click this](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201221#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgQWxgQiQB4AVABUwE8AbCTAEzgF45MlaAaOCgLLAYmdp24A+OAG8AUHAVwwdRiwD8ALn40GTZvMUBbYZk38hI2QF9ZsmLTB5qKvWKQBXQwCM0cAD5w7kjMwOjIwPr2juYmYgBKwNjQzGQAzjBQyADmfFy0UgFBIWFIEbZReAAiCKnKMNgAFmgAYtAAQphQlDqqrBwAbhAIzHyCsQNDzFIcANrOuiyjFpgAunCgqMGpcDODw3x7zCsGCmpwABTnAJTsUoTEpGSHB5MSNwBkMoipAKLo6IkYFosPRUngbIo4FoxiJ1iBNsxtocTnAzkVQuFWBtgFttC4WCizpdlAtmGZ5r0bmw7kQSOQKXoXsM3nBPnJIZCan8AURgZhQcAURDFFpifjmNCenoqTSHvSpYs4IcWWyUZzfv9AXyBUKUVoZuiShE+IbMWtsbi5gqRjERMdIUTziTeuTrXxjCJycsZQRaY8GYqYZgVTI1YouZreXAQWDdZCtKbSlj4TjEbbMISLk7xZLxe6TF6TD77nTunn0yH2RyFBGeUDo-zY5DhQpRdnSbnSfmRNDvbdfXKy12Kx9Q9Waxq69qm4obLIAPQAKkX8kXcAqcA6UDEl3bLs7lP7Jf9bqVr1HVYn3K1DYFAG5rDcArvnXoD4y4B7MFoEkkoCl0kyJAcnEfJiz9eVy1-ZIyAAOngiRKxReDYIfKwrlXec7AcPAtzEapakweomigVooC3IdeiWEwJFsehhDgLxOi0LcHwXZdVzgej4CYqBRVfFh30VL8f0SGDAOyXJJHAwcAxtZV-AHUs5L4aD-zSDJJNAxCUQANU6BBMC8ei4AAcl40zvkCMFWB8dBoDwHxsk4VJUgQLIk1g84ACYABYAFZfIwyEfnAQEIjgbzOCgLJPBxGBUj4Lx3HgLIIHgAAGLzvP8wLgvDJAwBS2CEpAHyAHY+AATiuLR8CQaLYuMFBo2gMyBOYSyAHdMG2JB0qUKAIH6YYIlgzDZF4642KXFc4DXDcOgALx3Pc9Fdcsv0LEQZOU08gyQ9VryjGNgDQibFswFbZhU9NzRTS1njPYZ7UUR1dseJ7lQvb5jvrU64BbKF0zhBEkUmTNEwii00zkzMxVJDbSQ+yDh2+1kx3HWsb1OuMRSzDqhOYFHKI-dHVXHX7I3+xtBWbPUdihm0mfusGdluoNXtOAnxSRqjPwLXsiyPCDScDZZDqxyccdpvHW0CYIMSTUHU22IN4bWwS8WHLahZ2kXZP2iWLzDK9qenOnZwZhHeiJ7tv3TEmOeNjHLw5bGTtl+nZG4xirpYq62KYpbpsmq7zgARiuB9g8jvhpDM4PTK0CPAej2QgA)

**Related Issues:** 
Not found cause I don't know how to search this.

**Comment by tianzhich** [comment]
I just found the reason was [distributive conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types). Before close this, I was curious about:

```ts
type NakedExample<T> = T extends void ? 'true' : 'false';

type OptionalNumber = number | undefined;

// 'true' | 'false'
type Foo = NakedExample<OptionalNumber>;

// 'false'
type Bar = OptionalNumber extends void ? 'true' : 'false';
``` 

Can someone explain why TS only distributes the *naked type parameter* over union types? I think all union types used in `extends` should be distributed, not only for the naked type parameter.

> Conditional types in which the checked type is a naked type parameter are called distributive conditional types. Distributive conditional types are automatically distributed over union types during instantiation. For example, an instantiation of `T extends U ? X : Y` with the type argument `A | B | C` for `T` is resolved as `(A extends U ? X : Y) | (B extends U ? X : Y) | (C extends U ? X : Y)`.

**Comment by RyanCavanaugh** [comment]
Distributivity is usually what you want in those scenarios, so it's the default when the checked type is a naked type parameter. This was in favor of making special syntax for distributivity/non-distributivity since, with this behavior, you just generally don't have to think about it

**Comment by tianzhich** [comment]
Thank you Ryan, what you mean *in favor of making special syntax for distributivity/non-distributivity*?. In my point of view, this behavior helps us construct some helpful utils types like:

```ts
type Diff<T, U> = T extends U ? never : T;  // Remove types from T that are assignable to U
type Filter<T, U> = T extends U ? T : never;  // Remove types from T that are not assignable to U

type NonNullable<T> = Diff<T, null | undefined>;  // Remove null and undefined from T

type T34 = NonNullable<string | number | undefined>;  // string | number
```

But if without this default behavior, it is difficult to achieve this right?
