### ISSUE TITLE
Multiple generic constraints with defaults falsely generating TS2344 error

### ISSUE THREAD

**Issue by T99** [microsoft/TypeScript#42081]
# Bug Report

### 🔎 Search Terms

 - TS2344
 - "could be instantiated with a different subtype of constraint"
 - multiple generic constraints with defaults

### 🕗 Version & Regression Information

The earliest TS version that I observed this in was 3.7.2 (I have not tested earlier versions, it is most likely present in even earlier versions), and I've tested it in the current NPM release version, 4.1.3.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=2&jsx=0&module=1&ts=4.1.3#code/MYGwhgzhAEDiCmA7eAnAlsAQpe0DeAvgFBGiQwDC4UAggDwAa08AHgC5IAmMCy6WOAHz4iASABmAe0kAKAJQAuaEzzQU8NgFcUiaJsSd44tMk7RIexAGtEkgO66LDANzRixUtUpfMjZuy4eJFQMbAh4ABpoAE1-DgNvcnoALWEAXmgqJLpeEIFwwSjkuMC4YP4w3AzciqF8YiA)

### 💻 Code

```ts
class GenericBase {}

class ClassA<X extends GenericBase> {
    foo(): X { return undefined as unknown as X; }
}

class ClassB<X extends GenericBase, Y extends ClassA<Z> = ClassA<GenericBase>, // <-- TS2344 occurs here
    Z extends GenericBase = GenericBase> {}

// error TS2344: Type 'ClassA<GenericBase>' does not satisfy the constraint 'ClassA<Z>'. Type
// 'GenericBase' is not assignable to type 'Z'. 'GenericBase' is assignable to the constraint of
// type 'Z', but 'Z' could be instantiated with a different subtype of constraint 'GenericBase'.

```

### 🙁 Actual behavior

A `TS2344` compile-time error is produced.

The error states that `Z` could be instantiated with a different subtype, but this doesn't actually seem to be possible due to the fact that if `Z` _was_ actually instantiated with a different subtype, then the default generic type wouldn't be used (in order to explicitly instantiate `Z` with a different type, `X` would also need to be explicitly instantiated due to the order in which `X` and `Z` are defined).

### 🙂 Expected behavior

The above code should not produce an error.

**Comment by RyanCavanaugh** [comment]
This is a correct error for the reason given. It's not *currently* allowed to skip generic type arguments, but there's nothing preventing TS from tomorrow allowing `type S = ClassB<X, ,Z>` and in that situation you'd have an unsoundly-constructed `S`.

**Comment by T99** [comment]
The error _is wrong_ as it is written though -- the error states that `...'Z' could be instantiated with a different subtype...`, when in reality that is _not actually the case_ as it currently stands. Perhaps I am unaware of some functionality that exists to rewrite or lazily narrow generic types? 

Also, throwing an error because of a reason that is not currently implemented (nor is planned to be implemented AFAIK) seems very trivially useful. As it stands there is *no way* for the above code to generate a type error _with the current implementation_ as I understand. I could make an argument that _plenty_ of things _could_ throw errors right now because something _could_ change later. Should all of those cases throw compile errors as well?

**Comment by RyanCavanaugh** [comment]
> I could make an argument that plenty of things could throw errors right now because something could change later.

Yes, and you absolutely should if you see change requests that would prevent future language features from being added. Part of our job here is to not paint ourselves into corners based on how things happen to work today. I don't disagree with this at all; you're 100% right that it's important to not do things that make good things in the future impossible or impractical.

Being diligent about this is *why* we have features that originated after the first handfuls of versions. There are 200+ upvotes on #10571, making it one of our highest-requested features under current consideration, and baking in order-dependence of what is fundamentally an unordered set would close the door on that feature.
