### ISSUE TITLE
Object prototype functions are missing in JS code completions

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/TypeScript#42086]
# Bug Report
### 🕗  Version & Regression Information
I'm not sure about the version from which it started to occur

- I was unable to test this on prior versions because - I haven't used Typescript in my working environment
I faced this issue in monaco-editor@0.20.0
- I searched on  https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs and didn't see it as an existing bug

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/G4QwTgBOYgnhBeCBtAugbgFAHptTDLAHSaaiQD2ARgFYCmAxgC6IQDeAvljntfcyTLgIfRkwDqASyYALAMIUAdgGcmAV2YVISRXQDuEAPK0xACgCU3XCJPMpshSvWawgoA)

### 💻 Code

```js
var array = [];
// array.

var object = {};

// object.

var objectWithConstructor = new Object();

// objectWithConstructor.
```

### 🙁 Actual behavior

On Typing `object.` it does not provide any code completions for built-in Object prototype methods

### 🙂 Expected behavior

I wish to see code completions which list down the Object prototype methods, just like it does for `objectWithConstructor` 

### Video 

I have attached the video explaining the issue, For your reference

https://user-images.githubusercontent.com/29809906/102966351-bba95a80-4515-11eb-8154-fa064c60f29d.mov

### Issue Origin

_Originally posted by @Pranomvignesh in https://github.com/microsoft/monaco-editor/issues/1944#issuecomment-687181387_

**Comment by MartinJohns** [comment]
> I'm not sure about the version from which it started to occur

In the Playground this behavior already occurs in the earlierst version available (3.3.3333).

I'm also pretty sure this behavior is intentional, as these methods are **usually** noise and unwanted, and there's no way to order the properties in a meaningful way.

See the comment of @RyanCavanaugh here, where he explicitly mentions that they hide the non-object members (indicating that it's intentional): https://github.com/microsoft/TypeScript/issues/41279#issuecomment-717571176

> The useful part of this is that the non-Object members are at the bottom, and **we already hide those**, so I think the current behavior qualifies as "good enough"

**Comment by Pranomvignesh** [comment]
> as these methods are **usually** noise and unwanted, ... they hide the non-object members 

I wish this decision is made by the user and I would like to have an option whether to show / hide this

> there's no way to order the properties in a meaningful way.

I just want it to be there in the same order as it is shown in object which is created from `new Object()`  ( Refer time : `0:37` of the video )

**Comment by RyanCavanaugh** [comment]
This is the intentional behavior. We haven't heard any other feedback on this yet so wouldn't really be interested in adding a setting or such given that.
