### ISSUE TITLE
ORed function types are merging to ANDed parameters while calling the function

### ISSUE THREAD

**Issue by rajeevnaikte** [microsoft/TypeScript#42083]
# Bug Report

### 🔎 Search Terms

Merged types
Inferred type
Union of types of object properties

### 🕗 Version & Regression Information

4.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201222#code/C4TwDgpgBAggCgSRgEwIZmBATgHgEoCKANFHgMoB8UAvFAN4BQUUAlgHYBuA9gNYQBcUABRYIARwCuEAM7BBhAJQ0qXAEYArCAGNgAbgYBffQ1CRSBAIw16UUwKiys7AOZQjJ8NEIAma3SgcLBAA7oKOLm7GdrBoGNhWtPBIsZi4hBYkqGwgFPrRKOipvomIBXFpBN6Z2bkMHmZlqQBiqDpcWCB+TFCoKfGCjfH6zL2F2N4DfVje+u4MWlxssj1TLW0dk2NYa8DtnbSMI1MWgofMrJy8ECLiUrIK3cxn51CiwBJYbPTuLwZE3X9uqNyhN6I8Ltw+DdJDJgA8Xs9zm8Pl86D9zoDmIC5tEEGwAGbYJKDLB4W6wnAAFSotEpUAgAA9MGxkNJYKUpjh2ISsOZqjkoAB+cxQQRsCAcbDGfESNg6FiLKBaVAAGxVJJwADl6UyICy2XwQFx8TEtjs9hQhN02KgALb2TX-ZiiGGyQR4nnEqZk13AHAk80dADamoAuhR-g8zgslsAVltrMDmq1dsGbfbQ8ZneTlrQXXc46g2XBUFg7RBUtIcHZjfHygA6diQiAUIMABkzdSOW0blyh+dhClmDCAA)

### 💻 Code

```ts
type APIAdapter<RQ, RS> = {
  invoke: (request: RQ) => object;
};

type RQ1 = { type: string };
type RQ2 = { view: string };

type Adapter1 = APIAdapter<RQ1, any>;
type Adapter2 = APIAdapter<RQ2, any>;

type AdapterFactory = {
  adapter1: Adapter1;
  adapter2: Adapter2;
};

const adapterFactory: AdapterFactory = {
  adapter1: {
    invoke(request)
    {
      return {};
    },
  },
  adapter2: {
    invoke(request)
    {
      return {};
    },
  },
};

type InferAPIAdapterRequest<T> = T extends APIAdapter<infer RQ, any> ? RQ : never;

function callAdapter<N extends keyof AdapterFactory>(
  name: N,
  request: InferAPIAdapterRequest<AdapterFactory[N]>,
)
{
  const adapter = adapterFactory[name];

  request = request as Parameters<typeof adapter.invoke>[0]; // error

  adapter.invoke(request); // error with type compatibility of `request`
}

```

### 🙁 Actual behavior

In above code, the type inferred with `InferAPIAdapterRequest<AdapterFactory[N]>` is will be same as union type of first parameter of `invoke` function in type `Adapter1` and `Adapter2`. But while invoking the function getting type incompatibility error. One of the error is `Type 'RQ1 | RQ2' is not assignable to type 'RQ1 & RQ2'`.

### 🙂 Expected behavior

the type inferred with `InferAPIAdapterRequest<AdapterFactory[N]>` must be same as union type of first parameter of `invoke` function in type `Adapter1` and `Adapter2`

**Comment by RyanCavanaugh** [comment]
This is a correct error.
```ts
type APIAdapter<RQ, RS> = {
  invoke: (request: RQ) => object;
};

type RQ1 = { type: string };
type RQ2 = { view: string };

type Adapter1 = APIAdapter<RQ1, any>;
type Adapter2 = APIAdapter<RQ2, any>;

type AdapterFactory = {
  adapter1: Adapter1;
  adapter2: Adapter2;
};

const adapterFactory: AdapterFactory = {
  adapter1: {
    invoke(request)
    {
      console.log("I have a string here: " + typeof request.type);
      return {};
    },
  },
  adapter2: {
    invoke(request)
    {
      console.log("I have a string here: " + typeof request.view);
      return {};
    },
  },
};

type InferAPIAdapterRequest<T> = T extends APIAdapter<infer RQ, any> ? RQ : never;

function callAdapter<N extends keyof AdapterFactory>(name: N, request: InferAPIAdapterRequest<AdapterFactory[N]>)
{
  const adapter = adapterFactory[name];

  request = request as Parameters<typeof adapter.invoke>[0]; // error

  adapter.invoke(request); // error with type compatibility of `request`
}


// Legal call to callAdapter, prints 'undefined' where it should print 'string'
callAdapter<"adapter1" | "adapter2">("adapter2", { type: "" });
```

**Comment by rajeevnaikte** [comment]
When we do that (`callAdapter<"adapter1" | "adapter2">("adapter2", { type: "" });`), then the type of second parameter will be `RQ1 | RQ2`. Inside the `callAdapter` function the type of variable `adapter` will be `Adapter1 | Adapter2`. Then the type of `invoke` function on that (i.e. `adapter.invoke`) will be `((request: RQ1) => object) | ((request: RQ2) => object)`. When we call that function `adapter.invoke(request)`, then it should be accepting as the input (`request`) passed is of type `RQ1 | RQ2`. But in the function call line of code it says the type of the fuction is `(request: RQ1 & RQ2) => object`. It ANDed here (`RQ1 & RQ2`), whereas it was supposed to be ORed (`RQ1 | RQ2`).

**Comment by MartinJohns** [comment]
> hen the type of `invoke` function on that (i.e. `adapter.invoke`) will be `((request: RQ1) => object) | ((request: RQ2) => object)`. When we call that function `adapter.invoke(request)`, then it should be accepting, as the input (`request`) passed is of type `RQ1 | RQ2`.

This is wrong. You either have a function accepting `RQ1`, or you have a function accepting `RQ2`. You can't pass in a value that is either `RQ1` **or** `RQ2`. What if the function you call accepts a `RQ1`, but the value you have is a `RQ2`?

That's why the argument type is inferred to be `RQ1 & RQ2`. If your value is **both** `RQ1` and `RQ2`, then it doesn't matter if the function you call accepts `RQ1` or `RQ2` - your value fulfills both requirements.
