### ISSUE TITLE
Rename in destructured object expression changes property name in source object

### ISSUE THREAD

**Issue by znck** [microsoft/TypeScript#42082]
# Bug Report

### 🔎 Search Terms

[rename + object + restructure](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+rename+%2B+object+%2B+destructure)

### 🕗 Version & Regression Information

4.0.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABCAzgUwGJzgCgJSIDeAUIohAilIgCYCGUdiAvIgIynmXXDYuIAmTgCc0UEMKSFaDOgBpEvOIgC+xNcTQAPAA5xh1GmmB0QAG2oky6cTvxFOZCmCpEZjBQDpvo1yv6omNj4jogA9GFkUVEAeohQwjAA5klowoiiYHQAtmiIABZpaMShouKSbvQeGWh+oRHR0XH6NVm5BUWcaipAA)

### 💻 Code

```ts
function useFoo() {
  const data = 1
  const foo = 2
  return { data, foo }
}

export default {
  setup() {
    const { data, ...rest } = useFoo()
    //        ^ trigger rename here

    return { data, rest }
    //        ^ or rename here
  }
}
```

### 🙁 Actual behavior

After rename:

- case 1:

```ts
function useFoo() {
  const data = 1
  const foo = 2
  return { renamed, foo }
}

export default {
  setup() {
    const { renamed, ...rest } = useFoo()

    return { renamed, rest }
  }
}
```

- case 2:

```ts
function useFoo() {
  const data = 1
  const foo = 2
  return { data, foo }
}

export default {
  setup() {
    const { renamed, ...rest } = useFoo()

    return { renamed, rest }
  }
}
```

### 🙂 Expected behavior

```ts
function useFoo() {
  const data = 1
  const foo = 2
  return { renamed, foo }
}

export default {
  setup() {
    const { data: renamed, ...rest } = useFoo()

    return { renamed, rest }
  }
}
```

Original issue: https://github.com/znck/vue-developer-experience/issues/65

**Comment by RyanCavanaugh** [comment]
This is controlled by the setting `javascript.preferences.renameShorthandProperties` / `typescript.preferences.renameShorthandProperties`. See #29238

**Comment by znck** [comment]
Shouldn't this be the default behavior?

**Comment by RyanCavanaugh** [comment]
This used to be the default behavior and a bunch of people complained.
