### ISSUE TITLE
type checker does not recognize MyType reassembled from MyType["foo"] when MyType is a union

### ISSUE THREAD

**Issue by adambadawy** [microsoft/TypeScript#42085]
# Bug Report

please bear with me it is very difficult for me to make names for meta stuff. i will appreciate any edits to my bug ticket

the type checker does not recognize MyType reassembled from MyType["foo"] if MyType is a union of types each with a field "foo"

### 🔎 Search Terms

member type union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unions
- tested on Nightly, 4.1.3, and 3.9.7

### ⏯ Playground Link

Two playground examples:
- [the most minimal example i could produce](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201222#code/JYOwLgpgTgZghgYwgAgGrAgdwBIHsC2EACnAOYQCCIcANgJ5jAIDOAogG4TjIDeAUMmQATOGDgAuXgMEyADmQgAVOrIiSA5AAsCEdQG5pAXwOG+fUJFiIU6LESi4hAVwRgS5KrQZM2nbv0ERMUkAmUF5cmVVDVkHZ1d9IxMzMBUUT3pGFg4uMGQAXj4AHzQMHB13SmpMnxzwYtK7OJc3BQzvbL8wAz4YJxBXYFwQZHw4AGsqryzfXIAKIIlkdpm6sABtdUX1AF0ASkkV2q6pQSgIMCcoEZ5hUThkYz5DIA)
- [another example with code that may seem a bit more practical](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201222#code/JYOwLgpgTgZghgYwgAgEJwM4QIIjgGwE8xgEMBRANwnGQG8AoZZ5AVyygEkATALmQxgooAOYBuBgF8GDUJFiIUANWAQA7gAkA9gFsIABTgiceIiTJUaYZBAAekENwxpMJgsVIVqtRi2Tc4MDh+Xz8WAAcjCAAVQnCIfgByAAtdCESJP0kJaVlwaHgkZBV1fSgtblYEMENjXHdzLysbexonFyx6s09LHyYWAKCQ-rDkSONY+KTw8srqjJGwmYqqsB5+QWEQcUXsqRkwOJQujwtvawBefoAfYtVNNNq3brOrG7vS2dWnk8besAkDBgrBA1WAWhAyB0cAA1s9Tk1wAAKQbBZC-HrnADaiVRiQAugBKfgY159PxQCBgVhQSF0fyBOAAGjYHHWyESOkIAFp2NBucBuIlkHtpEA)

### 💻 Code

```ts
/**
 * This is the most minimal example I could produce, but it may not
 * seem very practical. I have included a more practical one with
 * my playground examples above.
 */
interface ViewHomePageAnalyticsEvent {
  data: {
      pageType: 'home';
  };
}

interface ViewProductPageAnalyticsEvent {
  data: {
      pageType: 'product';
  };
}

type AnalyticsEvent =
  | ViewHomePageAnalyticsEvent
  | ViewProductPageAnalyticsEvent;

function makeAnalyticsEvent(data: AnalyticsEvent['data']): AnalyticsEvent {
  return { data };
}
```

### 🙁 Actual behavior

TypeScript doesn't recognize that the function `makeAnalyticsEvent` returns an AnalyticsEvent, and the code doesn't pass typecheck.

### 🙂 Expected behavior

The function `makeAnalyticsEvent` passes typecheck.

**Comment by Zzzen** [comment]
I guess its design limitation

**Comment by RyanCavanaugh** [comment]
This code pattern is not really correct *except* when there's only one property, and the special-casing we have in place for these kinds of things doesn't trigger when the properties are structured this way.

Example of why this doesn't work for n > 1 properties:
```ts
interface ViewHomePageAnalyticsEvent {
  data: {
      pageType: 'home';
  };
  type: "home";
}

interface ViewProductPageAnalyticsEvent {
  data: {
      pageType: 'product';
  };
  type: "product";
}

type AnalyticsEvent =
  | ViewHomePageAnalyticsEvent
  | ViewProductPageAnalyticsEvent;

function makeAnalyticsEvent(data: AnalyticsEvent['data'], type: AnalyticsEvent['type']): AnalyticsEvent {
  return { data, type };
}

// Creates an object that isn't a valid AnalyticsEvent
const p = makeAnalyticsEvent({ pageType: "home" }, "product");
```

**Comment by adambadawy** [comment]
so, maybe there's a misunderstanding; in your example @RyanCavanaugh , the `type` fields do not match, but if they did, i would argue you should be able to construct an AnalyticsEvent in that way:

```
interface ViewHomePageAnalyticsEvent {
  data: {
      pageType: 'home';
  };
  name: string;
}

interface ViewProductPageAnalyticsEvent {
  data: {
      pageType: 'product';
  };
  name: string;
}

type AnalyticsEvent =
  | ViewHomePageAnalyticsEvent
  | ViewProductPageAnalyticsEvent;

function makeAnalyticsEvent(data: AnalyticsEvent['data'], name: string): AnalyticsEvent {
  return { data, type };
}

// Creates an object that isn't a valid AnalyticsEvent
const p = makeAnalyticsEvent({ pageType: "home" }, "event name");
```

**Comment by RyanCavanaugh** [comment]
Sure, I clarify: It's not valid except if there's only one non-homogenous property

**Comment by adambadawy** [comment]
cool, so would you agree that this should typecheck? [playground link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201222#code/JYOwLgpgTgZghgYwgAgEJwM4QIIjgGwE8xgEMBRANwnGQG8AoZZ5AVyygEkATALmQxgooAOYBuBgF8GDUJFiIUANWAQA7gAkA9gFsIABTgiceIiTJUaYZBAAekENwxpMJgsVIVqtRi2Tc4MDh+Xz8WAAcjCAAVQnCIfgByAAtdCESJP0kJaVlwaHgkZBV1fSgtblYEMENjXHdzLysbexonFyx6s09LHyYWAKCQ-rDkSONY+KTw8srqjJGwmYqqsB5+QWEQcUXsqRkwOJQujwtvawBefoAfYtVNNNq3brOrG7vS2dWnk8besAkDBgrBA1WAWhAyB0cAA1s9Tk1wAAKQbBZC-HrnADaiVRiQAugBKfgY159PxQCBgVhQSF0fyBOAAGjYHHWyESOkIAFp2NBucBuIlkHtpEA)

maybe it's just out of scope for TypeScript, which is fine, just wanna know that the minimals i provided are valid

**Comment by RyanCavanaugh** [comment]
It should in theory, yes.
