### ISSUE TITLE
Generic defaults doesn't enforce typechecks for function arguments without the default value inheritance

### ISSUE THREAD

**Issue by fughur** [microsoft/TypeScript#42097]
**TypeScript Version:**  4.1.3 (also tried the older one)

**Search Terms:**
default generic with partial

**Expected behavior:**
Function arguments with
```ts
 <GenericType = SomeDefaultType>(val:Partial<GenericType>)=>{}
```
 works the same way as 
```ts
const someVal:Partial<SomeDefaultType>
```

So it requires the user to specify only known properties in the function arguments while also making them optional.
In example below i simply want 
```ts
doStuff({
  customKey: 44
});
```
to behave the same way like
```ts
const val:Partial<SomeModel> = {
  customKey:44
};
```

**Actual behavior:**
User can simply pass any value to the function if it's generic variable isn't extending the default type like so
```ts
<GenericType extends SomeDefaultType = SomeDefaultType>(val:Partial<GenericType>)=>{}
```
But this simply doesn't fit my use-case because it requires GenericType to always inherit the SomeDefaultType which is bad interface.

**Related Issues:**
No

**Code**
```ts
type SomeModel = {
  key:number;
}

function doStuff<ValModel = SomeModel>(val:Partial<ValModel>){
  console.log(val);
}

// works as expected (customKey is blocked as it doesn't exist in original type)
const val:Partial<SomeModel> = {
  customKey:44
};

// but here validation is simply broken and this is the problem i actually having
doStuff({
  customKey: 44
});

function doWeirdStuff<ValModel extends SomeModel = SomeModel>(val:Partial<ValModel>){
  console.log(val);
}

// suddently this one works fine, but it isn't correct for my use-case because forces user to extend default type
doWeirdStuff({
  customKey: 44
});

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function doStuff(val) {
    console.log(val);
}
// works as expected (customKey is blocked as it doesn't exist in original type)
const val = {
    customKey: 44
};
// but here validation is simply broken and this is the problem i actually having
doStuff({
    customKey: 44
});
function doWeirdStuff(val) {
    console.log(val);
}
// suddently this one works fine, but it isn't correct for my use-case because forces user to extend default type
doWeirdStuff({
    customKey: 44
});

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAyg9gWwgWTgEwgGygXigbwFgAoKKAawhAC4A7AVwQCMIAnAbhIF8SSAzerQDGwAJZxaUNHBjB6fPgB4AagENMqDNjzwkmrAD4AFADd11AAqrWY9SvX7MBgJRFSUIRIDOcTBAB0mHAA5qbqzpzEPMQkAPSxUADucKzkXlCq6RAAHpAiEGhQRkL0XsCIANJUUKLpTEFClIWZNcBScBBetADkbTm1baKSKaLBQ+pQoJDOJJ60ZVBmmJbWtpiKuijohrgEJGQlZZVU1AAsp9yRcQlM9G0AFmzQS6JoqmISNeleoghgmCAoExWHBKJJVLRCsB7rUvpNHlAwCD6hAEDUMiJ6OoAVB7qoTENgiRpLJ5HwjG4DqVyggqjQoOduBFeMQBMIPpJpAB1CCiVhoUkKewabbYHLACCQ9KbRy7GWi4xLFY2UR2NQirQuSkeby+AJBUJLZlRFnxKBeehoDC0YA46GwiTQZKpdJ8IYQAA0QLurS+PTanlYrAgIigfBSUAQgNKEAAtEJMtAWAmY2GUkJOlAY6xJnAoOLJYUMHxVPRMG0phBiXAeXyBXIFBT9h5qcd6YyosagA)

**Comment by fughur** [comment]
Okay it seems this behaviour isn't partial issue because i have the same issues with regular generic defaults
https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAyg9gWwgWTgEwgGygXigbwFgAoKKAawhAC4A7AVwQCMIAnAbhIF8SSAzerQDGwAJZxaUNHBjB6fPgB4AagENMqDNjzwkmrAD4AFADd11NRvRYAlEVJQhEgM5xMEAHSY4Ac1PqbTmIeYhIAejCoAHc4VnJnKFUEiAAPSBEINCgjIXpnYEQAaSooUQSmbyFKLKTS4Ck4CGdaAHJ61LL60UlY0R9u9ShQSBsSJ1p8qDNMal0Ua20CEjJc-KKqagAWTe4g8MimenqACzZoadE0VTEJUoTnUQQwTBAoJlY4SklVWizgY7KdyGpygYA+FQgCFKiRE9HULygx1UJm6PhI0lk8j4RnsKzyBQQxRoUG23ECJCAA

```ts
type SomeModel = {
  key:number;
}

function doStuff<ValModel = SomeModel>(val:ValModel){
  console.log(val);
}

// works as expected (customKey is blocked as it doesn't exist in original type)
const val:SomeModel = {
  customKey:44
};

// but here validation is simply broken and this is the problem i actually having
doStuff({
  customKey: 44
});
```

**Expeceted behaviour**

1. if user calls `doStuff<CustomModel>(value)` with some custom generic type the value should be validated against this type and it works just fine
2. if user calls doStuff(value) without custom generic model the default one should be enforced (`SomeModel` in my case) so value will be validated against SomeModel type

**Actual behaviour**
1. the first case with custom arguments works just fine `doStuff<CustomModel>(value)` 
2. the second case with the default one doesn't work at all - it allows user to pass any value he wants like in `<ValModel = any>` case (but at fact we are using `<ValModel = SomeModel>`)

Since this is not the Partial issue anymore i don't sure if it is a bug, but also can't find any information on how to achieve the behaviour i want without enforcing user to inherit SomeModel in his custom types.

**Comment by andrewbranch** [comment]
I don’t totally understand what you want, but the actual behavior you have described is 100% how it’s supposed to work. If you have a question about how to use generics, please ask on StackOverflow and you will get good advice there.
