### ISSUE TITLE
`Record<string, any>` or `object` is not compatible with object like types when appears as an argument of an arrow function

### ISSUE THREAD

**Issue by aminya** [microsoft/TypeScript#42096]
# Bug Report

### 🔎 Search Terms

Record

### 🕗 Version & Regression Information

This happens all the time. Testd with version 3.3.3 up to nightly (4.2.0_

### ⏯ Playground Link

[link with object](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&target=5&ts=4.2.0-dev.20201223#code/C4TwDgpgBAggdiA8gIwFYQMbCgXigezU2AG4AoM0SKAYQBsBLDAawENk7o8BvAuepswD8ACggAuKKwQAaKAFsIwVpPhIiWAJSSAbvgYATKAF9K4aAJbtOMAE638Ad1xRe+foxZDJYydJByisqqCCjoWrgAfFB6hiYUAGYArnBYDO5QtkpJtnAQtgCMIqy2AOaq9qwgADyWbBwQkZquZFBtmdm5UmXkpmTJqcDpcB3AOXm2AEzFZRW2VbWe9Tb2Tk0t7aPj3aW9FGSc2GCsAM4nPhJSslAAHpK8zBAgknBJ8sj5Js040bFGeGI5DdvtFeBh3Cd8JwAHR0fClETcCBA4yaYzkMhZMa5fJFADabg8gkkxzOJgAupoMZjOhNpgS+HUSacThSqUA)

[link with Record<string, Any>](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&target=5&ts=4.2.0-dev.20201223#code/C4TwDgpgBAggdiA8gIwFYQMbCgXigJUwHsAnAEwB4BnYEgSzgHMAaKAQwQD4Aob0SKAGEANnQwBrNsmHQ8AbyhE4IseID8ACggAudglYBbCMDa74SNJmABKXQDcidMlAC+fcNBUSpMmCRJEAO64UApKXuq6WrocIIbGprAIKOhY1ricUA5OrrwAZgCucFh0SlAkxgUkcBAkAIwabCSMZv5sIBQRPhCc6XLcUIPlldXszQDc3G7chcXApXDDwFU1JABMjc2tJO2dot7SEH4Bgb2hA0MVy6NNjJPT3DLYYGxUVFE6enFQAB66CuIICBdHACgZkLVXOkcJlss48FpWD9oZkFBglFQiDIAHTCIiMDRyCBIlzWFyTbhXFa1BoAbTCyn24l0LzergAutYKZSRqsNvTFIzVCzXlQOVygA)

### 💻 Code

```ts
type AnyObject = object // Record<string, any>
type Clickable = { onClick?(e: any, meta: AnyObject ): void }
type ClickableArrow = { onClick?: (e: any, meta: AnyObject ) => void }

function returner1(arg: Array<Clickable>) {
    return arg;
}

function returner2(arg: Array<ClickableArrow>) {
    return arg;
}


let pass: (e: any, x: { key: number }) => void = (e, x) => { console.log({e, x})};

// works
returner1([{ onClick: pass }]);

// fails
returner2([{ onClick: pass }]);
```

### 🙁 Actual behavior
Edit: This error only happens with arrow functions: 

I expect `Record<string, any>` to match all the object like types. But currently an object like `{key: number}` is not compatible with `Record<string, any>`. 

This is unfortunate because other than `any` there is no other type to use to match `AnyObject`.

`object`, `Object`, and `{}` do not work.

### 🙂 Expected behavior

`Record<string, Any>` should be compatible with any object that is indexable by a string. By any object, I mean non-primitive types (those that object does not match), but with support for any key.

### Additional context

Linters suggest replacing `Object` with `Record<string, Any>` which results in these types of errors.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md#default-options

**Comment by RyanCavanaugh** [comment]
We don't write typescript-eslint or control its incorrect recommendations. This code is fundamentally unsound and it's correct to issue an error; a legal invocation of `returner` can crash:
```ts
type AnyObject = Record<string, any>

type Clickable = { onClick?: (e: any, meta: AnyObject) => void }

function returner(arg: Array<Clickable>) {
    arg[0].onClick?.(0, {});
    return arg;
}

let myClickable: (e: any, x: { key: number }) => void = (e, x) => {
    // Crashes
    console.log(x.key.toFixed());
}

returner([{ onClick: myClickable }])
```
There's a type that does what you want here, it's `any`

**Comment by aminya** [comment]
`any` is more permissive than what I want here because it allows `string`, `number`, `null`, etc. But I really want here is indexability by a string that is available for JavaScript's' Object types.

**Comment by RyanCavanaugh** [comment]
You'd need something like negated types for that. There isn't a way to represent this kind of type relationship (which makes sense when you consider that there's no way for `returner` to know what kind of function it got)

**Comment by RyanCavanaugh** [comment]
Actually, I misspoke, you should take advantage of method bivariance:
```ts
type Clickable = { onClick?(e: any, meta: object): void }
function returner(arg: Array<Clickable>) {
    return arg;
}

let pass: (e: any, x: { key: number }) => void = (e, x) => { };
let fail: (e: any, x: string) => void = (e, x) => { };

returner([{ onClick: pass }]);
returner([{ onClick: fail }]);
```

**Comment by aminya** [comment]
Unfortunately, `object` does not work here. I wish it could, but it does not. I thought I can use `Record<string, any>` as a workaround for `object` issue. However, none of them does it.

[object issue](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&target=5&ts=4.2.0-dev.20201223#code/C4TwDgpgBAggdiA8gIwFYQMbCgXigezU2wHoSoAlTfAJwBMAeAZ2BoEs4BzAGigEMEAPgBQw0JCgBhADZsMAaz7Jp0PAG8CcGXPkB+AFxQAFBEMCQvALYRgfQ-CREsASlyCoAN3xs6UAL6iAGYArnBYbPhwUDQ2wTRwEDRGfDSc9jQ0fCAM2gpKKoKuasJQpdGx8fypANzCAcIq2JYguYrKpsYd5rwAHoZq8hAghnDBlsiJfq447l4+uJ290+4aGJFM+CoAdNL4nEZqENw9U9X+ojHAcQlJANpqka2Gza35EH4Aus5AA)

Your example does not work:
[reproduction](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&target=5&ts=4.2.0-dev.20201223#code/C4TwDgpgBAwgNgSwMYGsCGAjO0C8UDeUA9gHbzIoD8AFBAFxRokgA0UAthMGg0RgFYQkwAJQMAbkQQATKAF8AUADMAriWEJSUAE5cV2khG3U02gOYMAgtu1oQAHnKpM2AHwiCCqN516DjcwBuBUUFbGAoMDQAZ2iGWgYmVigADwZCFAgQBhIVdgwjeQ8cVyhJGSg8WjYU4tLCJFJoomwAOjgiM2p8CBYUuQ85YPCoJTQEOHj6RmYahmjgbQQSMzqyqVkq3tS1hqaWiHbO7t7+weCFXWB9Q2MAbUJSJxQGKNj5AF0RYKubo2oHsQyIhUAwxhNPt8gA)

I have edited the original issue so it explains things better

**Comment by MartinJohns** [comment]
> This seems kind of strange. It works with normal functions but not with arrow functions

[Why are function parameters bivariant?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)
