### ISSUE TITLE
tsc --watch does not terminate if run through npm and Cygwin

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#4210]
`tsc --watch` does not seems to respond to the way Cygwin stops programs (i.e. whatever it generates for ctrl-c) and can only be forcibly killed.

Specifically, if `tsc` is launched through the `node_modules/.bin/tsc` shell script in Cygwin, then everything works as expected. However, the Windows version of `npm` calls the `tsc.cmd` which does not seem to work with Cygwin signals.

**Comment by mhegazy** [comment]
additional diagnostics would be appreciated so would be a PR, assuming there is a simple fix.

**Comment by DanielRosenwasser** [comment]
@billccn what terminal emulator are you using? (i.e. CMD/PowerShell, ConEmu, Cmder, MinTTY?)

**Comment by billccn** [comment]
It's MinTTY. I had to say when I played with `cmd.exe` before, its handling of stdIO seemed to be very dodgy. In this case, `cmd` will be killed with its parent process but `node.exe` will continue to run with a stdin?

**Comment by mhegazy** [comment]
any more information available here?

**Comment by mhegazy** [comment]
please reopen if more information is available..
