### ISSUE TITLE
@Jameskmonger if `T extends string | number` then `T` can be `string | number` which means one value of type `T` can be `string` a different value of type `T` can be a `number`.

### ISSUE THREAD

**Issue by lumosmind** [microsoft/TypeScript#42109]
@Jameskmonger if `T extends string | number` then `T` can be `string | number` which means one value of type `T` can be `string` a different value of type `T` can be a `number`.

It really sounds like you should use overloads here rather than a type parameter.

_Originally posted by @RyanCavanaugh in https://github.com/microsoft/TypeScript/issues/12410#issuecomment-286860930_

I think this not true for this example. two arguments with same T type must have same concrete type. otherwise gives error like:
error 1 : Argument of type '5' is not assignable to parameter of type 'false'.ts(2345)
error 2 : Argument of type 'true' is not assignable to parameter of type '5'.ts(2345)

```
const sum = <T extends boolean | number>(a: T, b: T): number => {
  return 1;
};

sum(true, false);
sum(5, 5);
sum(true, true);
sum(false, 5); //error 1
sum(5, true); //error 2
```

**Comment by MartinJohns** [comment]
It's still true. Your issue is just how the type argument `T` is inferred.

This works just fine:

    sum<boolean | number>(false, 5);
    sum<boolean | number>(5, true);

**Comment by lumosmind** [comment]
@MartinJohns  did you read the issue [#12410 (comment)](https://github.com/microsoft/TypeScript/issues/12410#issuecomment-286860930)

**Comment by MartinJohns** [comment]
@lumosmind Yes, I did. Did you read my comment? https://github.com/microsoft/TypeScript/issues/42109#issuecomment-751235775

Like I demonstrated using your `sum` method, the value for the first argument `a` is the type `boolean`, the value for the second argument `b` is the type `number`, while both arguments are typed `T`. This is exactly what Ryan referred to in his comment.

**Comment by lumosmind** [comment]
I got it what you mean. but the [question ](https://github.com/microsoft/TypeScript/issues/12410#issue-190768320)
and @RyanCavanaugh's answer is not fully match with your answer. @RyanCavanaugh's answer says:

> one value of type T can be string a different value of type T can be a number

in your answer you solve this problem with explicit type declaration for T type. But in the @Jameskmonger's question there is no explicit type definition. You create a solution okay but the problem is different I think.

**Comment by MartinJohns** [comment]
The problem is absolutely the same. James wrongly assumes that `T extends string | number` means that `T` is **either** a `string` **or** a `number`. But this assumption is wrong, as I demonstrated, because the type can be `string | number` as well. Then the value passed for `T` can be a `string` for the first argument, and a `number` for the second argument.

> in your answer you solve this problem with explicit type declaration for T type.

In my second example I don't explicitly provide the type argument.

**Comment by lumosmind** [comment]
I have some sense about what you mean but I am new at TS and may be I misunderstood some concepts of TS.
Could you suggest strong resource for TS? [Official documentation](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) is very poor.

Thank you for your patience.
