### ISSUE TITLE
rename symbol support on vue <script>

### ISSUE THREAD

**Issue by GopherJ** [microsoft/TypeScript#42105]
# Suggestion

it seems currently tsserver is not able to rename symbols located in vue <script> (or it's me who didn't find how to do it...) Is it possible to rename referenced symbols in vue <script>?

## 🔍 Search Terms

- rename symbol
- vue component

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

considering having a vue typescript project.

`src/store/types/getters.ts`
```js
const GET_USER_INFO = "GET_USER_INFO"  // <-- rename symbol here, let's say renaming it to `GET_USER_NAME`
```

`src/components/Header.vue`

```vue
<template>
<div>hello, {{ user_info }}</dir>
</template>

<script lang="ts">
import { GET_USER_INFO } from "@/store/types/getters" // <--- sadly this cannot be fixed

export default class Header extends Vue {
  get user_info() {
    return this.$store.getters[GET_USER_INFO] // <-- sadly this cannot be fixed
  }
}
</script>
```

## 💻 Use Cases

vue typescript project

**Comment by GopherJ** [comment]
I'm not sure if this should be in `tsserver` or `vetur`, ideally both... If you feel it should be on `vetur` side, please just close this

**Comment by andrewbranch** [comment]
This would have to be on the Vetur side. As someone mentioned in that linked issue, a TypeScript LS plugin would have to communicate the request to the Vue LS. If there is some specific functionality missing from TypeScript that needs to be added to make that work, we’d probably be able to help with that. But from the issue it doesn’t look like anyone has tried it yet.
