### ISSUE TITLE
return dynamic multiple class with ts and jsdoc “ts implicitly has return type 'any'”

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#42100]
how i can solve this error with jsdoc typescript annotation ?
For me is not logic and should ok !

`implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions`.

Please note this is a very simple version of my current logic in my project for more readability.

**I also have the option of using .ts files because I use parcel, so if you have a ts solution I am also a taker but I would prefer a solution with ts in jsdoc.**

Thanks for any help, suggestions .

---
---
### 🙁 Actual behavior

**Here small example refactoring  visual context of issue.**

```javascript

// make a fake ts interface with jsdoc, plugins are injected later by user.
/**
	* @typedef {object} PLUGINS
	* @property {typeof $String} [$String]
	* @property {typeof $Number} [$Number]
*/

/**@type {PLUGINS} - plugins stored in a proxi store */
const Plugins = {};


export class Value {
	constructor() {};

//// Am stock here with types for Intelisence ////

	/**
	 * @param {keyof PLUGINS} pluginName
	*/
	set(pluginName) {
		return new Plugins[pluginName]();
	}


}


export class $String extends Value  {
	constructor() { super()}
}
export class $Number extends Value {
    constructor() { super() }
}

```

So this seem logique for me `return new Plugins[pluginName]();` 
But actually i cant found a way to get dynamic return.

---
So the parameter are correctly documented by Intelisence.
[![enter image description here][1]][1]

---
But it hint me multiple error !
[![enter image description here][2]][2]

---
And possibly undefined !but yes this is what i expected
[![enter image description here][3]][3]

---
and add conditional do not solve issue issue !
```js
	set(pluginName) {
		if(Plugins[pluginName]){
			return new Plugins[pluginName]()
		}
	}
```
[![enter image description here][4]][4]

---

### 🙂 Expected behavior

Of course it work if i manually implement type in a return ! but this is not what i want !
[![enter image description here][5]][5]

---

```
Version : 1.52.1 (user setup)
Commit : ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date : 2020-12-16T16:34:46.910Z
Electron : 9.3.5
Chrome : 83.0.4103.122
Node.js : 12.14.1
V8 : 8.3.110.13-electron.0
OS : Windows_NT x64 10.0.19042
```
`tsc -Version 4.1.2`

  [1]: https://i.stack.imgur.com/Lp2Bh.png
  [2]: https://i.stack.imgur.com/ghMiU.png
  [3]: https://i.stack.imgur.com/kZoiK.png
  [4]: https://i.stack.imgur.com/2guOH.png
  [5]: https://i.stack.imgur.com/FooRz.png

**Comment by MartinJohns** [comment]
> and add conditional do not solve issue issue !
>
> ```
>	set(pluginName) {
>		if(Plugins[pluginName]){
>			return new Plugins[pluginName]()
>		}
>	}
> ```

Expressions using the bracket notation are not narrowed further. You need to store the value in a variable:

    const plugin = Plugins[pluginName];
    if (plugin) { ... }

But in the end it's the same: You don't return anything in the else-branch, so you still return `undefined`.

**Comment by djmisterjon** [comment]
> > and add conditional do not solve issue issue !
> > ```
> >   set(pluginName) {
> >   	if(Plugins[pluginName]){
> >   		return new Plugins[pluginName]()
> >   	}
> >   }
> > ```
> 
> Expressions using the bracket notation are not narrowed further. You need to store the value in a variable:
> 
> ```
> const plugin = Plugins[pluginName];
> if (plugin) { ... }
> ```
> 
> But in the end it's the same: You don't return anything in the else-branch, so you still return `undefined`.

Actually i find little hacky way but am not big fan.

```js
/**
 * @typedef {object} PLUGINS_typeof
 * @property {typeof $String} $String
 * @property {typeof $Number} $Number
 * @property {typeof $Object} $Object
 * @property {typeof $Array} $Array
 */

/**
 * @typedef {object} PLUGINS
 * @property {$String} $String
 * @property {$Number} $Number
 * @property {$Object} $Object
 * @property {$Array} $Array
 */

/**
 * @typedef {object} Ttypeof_Plugins_Renderer
 * @property {typeof $Layout} $Layout
 * @property {typeof $Input} $Input
 */
/**
	* @typedef {object} TPlugins_Renderer
	* @property {$Layout} $Layout 
	* @property {$Input} $Input 
*/

/**@type { Partial< PLUGINS_typeof > } - plugin store in proxi */
const Plugins = {};
/**@type { Partial< Ttypeof_Plugins_Renderer > } - plugin de type renderer */
const Plugins_Renderer = {};
```

```js

export class Value {
	/**
	 * @template { keyof Omit<PLUGINS_typeof, "$Class">  } T - //TODO: <omit> types Contexts
	 * @param {T} pluginName
	 * @returns {PLUGINS[T]}
	 */
	set(pluginName) {
		return new Plugins[pluginName]();
	}
}
```

Actually all fine, but need a lot of types ! 
![image](https://user-images.githubusercontent.com/24865815/103093506-7eea6b80-45c8-11eb-93c0-232521911511.png)

I think it would be awesome to get more deeps and complexes examples in the doc of typescript jsdoc.
Won't there be some way to clean this up a bit or I'm at the limit of what typescript can do with jsdoc?
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
