### ISSUE TITLE
Type guard does not work correctly with empty string type

### ISSUE THREAD

**Issue by olderor** [microsoft/TypeScript#42101]
# Bug Report

### 🔎 Search Terms
type guard

### 🕗 Version & Regression Information
TypeScript 3.3.3+ (as per playground)

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Common "Bugs" That Aren't Bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs)

### ⏯ Playground Link

[Playground link with error](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAogtmUBlYAnAlgOwOZQLxQDkhUAPlJgK4A21ZUlmAJhAGZYRMDcAsAFD9WjAMbB0Ae0xR0AZ3iIQACgBuAQ2qUIALigy0WXOXnJ9OAJQ61G6LNgITGHFADe-KO6ioIwSqilXNfDwCYjJyAOhggipaMKgIoIJGFnZMTl4+AF9+fmpvKGAIPR09R0MKGjpyZLYObn5hST1PVWZxOHwoAFlVYAALADpWanFxVEUe-oHUVqZ2xTMoACpu3sHh0fGAZjMzDPRWKEUZto6oqAAGRdc+DwKi4E7iDMyoCGoZG0Pj2fbEqAAjNc3B5Cs0ksxaml6lk3h9oDc7mDHtFKi8cnwDkdZMYlMjdi4Qe5GpgZOI8gMRthFAADCI6AAkzmRmRpeyJ0m+yP+xGBtzuHhJZIpVMUhAAcuJIIR2fz3NksvwgA)

[Playground link without error but with incorrect type](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAogtmUBlYAnAlgOwOZQLxQDkhUAPlAK6YAmEAZlhNQNwCwAUB3VQMbDoB7TFHQBneIhAAKAG4BDADYUIALiii0WXOQnJNOAJRr5S6GNgI9GHFADeHKI6ioIwCqmEnl+PAWJlyL2hfAipaBkwmNnYAXw4OBVcoYAgNNQ1rbUoaekYWDh4hDWc5GgE4fCgAWTlgAAsAOjoFAQFUKRr6htRS6nKpAygAKmraxubW9oBmAwNo9DooKR6yipCoAAZB+3YnZNTgSuJomKgIBVEzReXe8p8CAEZthycU4tCciKiOOM52BaWYl00jewFmdhejkKmFEAkSDRa2CkAAMgmoACS2UExZFzSEia6g+5EQjPXZ7JzQ2HwxFSQgAOQEkFJ0T2v1+QA)

### 💻 Code

**The compiled JavaScript version works correctly, but TypeScript gives errors**:
```ts
type EmptyString = '' | null | undefined;

function isEmpty(value: string | EmptyString): value is EmptyString {
    return value === '' || value === null || value === undefined;
}

let test: string | null | undefined;

if (isEmpty(test)) {
    if (test === '') { // Compilation error since test: null | undefined and not test: '' | null | undefined
        console.log('Nope');
    }
}

```

![image](https://user-images.githubusercontent.com/11135046/103078082-fd71e980-4585-11eb-8ad6-14c183881bc2.png)

**Also, it's weird that when I remove null from the list of types, the error disappears, but the incorrect type is still shown**:
```ts
type EmptyString = '' | undefined;

function isEmpty(value: string | EmptyString): value is EmptyString {
    return value === '' || value === undefined;
}

let test: string | undefined;

if (isEmpty(test)) {
    if (test === '') { // No errors, but the editor displays incorrect type.
        console.log('Nope');
    }
}

```

![image](https://user-images.githubusercontent.com/11135046/103078865-98b78e80-4587-11eb-9272-d48d9ff3be69.png)

### 🙁 Actual behavior
TypeGuard ignores empty string and thinks the value can only be null or undefined.

### 🙂 Expected behavior
The type should include empty string. No errors expected.

**Comment by MartinJohns** [comment]
This looks very similar to #31156.
