### ISSUE TITLE
Expose internal TypeChecker.getTypePredicateOfSignature API

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#42118]
# Suggestion

Expose necessary functions for working with type predicates in the TypeChecker

## 🔍 Search Terms

TypeChecker getTypePredicateOfSignature internal compiler API

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Remove `@internal` annotation from `TypeChecker.getTypePredicateOfSignature`

## 📃 Motivating Example

N/A - transparent to normal user

## 💻 Use Cases

In an effort to produce documentation more consistent with the actual types used by the compiler, TypeDoc has recently started using the TypeChecker considerably more when generating documentation. For the most part this just worked - but it caused problems with signatures that have type predicates. @sandersn pointed me towards this function, which I've added to the `ts-internals.ts`.

From discussion in the #compiler channel in the TypeScript discord:

> **shivelysanders** 11/30/2020
> yep, getTypePredicateOfSignature will return the type predicate if there is one
> (includes asserts predicates)
> it's in TYpeChecker, but internal for some reason :rolling_eyes:

**Comment by andrewbranch** [comment]
It does seem like the only changes since the function was written have been adding support for predicates in JSDoc signatures and for assertion signatures. Not really sure how we evaluate requests to make internal APIs public, but this one seems fairly reasonable. @DanielRosenwasser thoughts?
