### ISSUE TITLE
Default jsconfig target

### ISSUE THREAD

**Issue by a-ejs** [microsoft/TypeScript#42113]
vscode 1.52.1

Code 1:

```js
[].includes; // function
Object.entries; // any
```

Code 2:

```js
import fs from "fs";

Object.entries; // function
/_/.dotAll; // boolean
[].flat; // any
```

Apparently, default `target` in absence of a jsconfig/tsconfig is `es2016`. Adding a node import bumps it up to `es2018`.

I'd expect it to be `esnext` in both cases.

**Comment by andrewbranch** [comment]
It doesn’t change the default, it triple-slash references the libs it needs. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/866931d58a831e163ef40f7830864270c281a20f/types/node/base.d.ts#L10

**Comment by a-ejs** [comment]
@andrewbranch 
The issue is not node types changing the `lib`, but what it's set to by default to begin with. Why `es2016`?

**Comment by andrewbranch** [comment]
Default is ES3. See #36180.

**Comment by a-ejs** [comment]
but where'd the definitions for ES2015-16 stuff come from then? Is this something specific to tsserver/intellisense in vscode?

**Comment by andrewbranch** [comment]
What else is in your project / what does your jsconfig.json look like? The default lib file brings in es5, dom, webworker.importscripts, and scripthost. It appears as expected for me.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/3277153/103305053-0c5dff00-49bf-11eb-8140-4ca02ab43b36.png">

**Comment by a-ejs** [comment]
I'm getting this in a project with no jsconfig (same when no project is open at all):

![](https://i.imgur.com/Z1KhyIG.png)

Oddly enough, creating an empty jsconfig.json changes the behavior to what you described.

I'm guessing there's a set of default values used for intellisense in absense of a jsconfig.json different from defaults for the jsconfig itself?

**Comment by andrewbranch** [comment]
When there’s no config file, we create what’s called an “inferred project,” and we actually let the editors set whatever options they want for those. So the default you observed actually comes from VS Code, here: https://github.com/microsoft/vscode/blob/b84858babef576c432154199a8cb7b03a3a0d914/extensions/typescript-language-features/src/utils/tsconfig.ts#L25

**Comment by a-ejs** [comment]
That makes sense. Thanks for the explanation.
