### ISSUE TITLE
Reflect.getMetadata return undefined after transform ts to js

### ISSUE THREAD

**Issue by Dolov** [microsoft/TypeScript#42117]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
@classDecorator
class Demo{

  constructor(str: string) {

  }
}

console.log(Reflect.getMetadata("design:paramtypes", Demo))
// [ [Function: String] ]
```

### 🙁 Actual behavior

when i use ts-node run above code is well,  i use tsc transform the code to js, then i use node run js but return undefined

### 🙂 Expected behavior

i aways think the return should be same , so i very puzzled
thanks for your time

**Comment by MartinJohns** [comment]
How are you compiling the TypeScript code to JavaScript? What's the exact command you run?

**Comment by Dolov** [comment]
> How are you compiling the TypeScript code to JavaScript? What's the exact command you run? What's the content of your tsconfig.json file?

tsc ./test.ts

```js
{
  "compilerOptions": {

    "target": "es5",                          
    "module": "commonjs",                     
    "lib": ["ES6", "DOM"],                         
    "strict": true,                          
   
    "esModuleInterop": true,                 

    "experimentalDecorators": true,       
    "emitDecoratorMetadata": true,        

    "skipLibCheck": true,                     
    "forceConsistentCasingInFileNames": true 
  }
}
```

**Comment by MartinJohns** [comment]
You are compiling your TypeScript code **without** the experimental decorators support. You should actually get an error about this.

[Using tsconfig.json or jsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson)

> When input files are specified on the command line, `tsconfig.json` files are ignored.

The default value for `experimentalDecorators` is false, and your `tsconfig.json` is not used because you specify input files.

**Comment by Dolov** [comment]
Thank you very much for your patient reply
I didn't read the document carefully 
I'm very sorry for wasting your time
