### ISSUE TITLE
Key remapping breaks tuple support for mapped types

### ISSUE THREAD

**Issue by insidewhy** [microsoft/TypeScript#42122]
# Bug Report

### 🔎 Search Terms

key remapping tuples mapped types

### 🕗 Version & Regression Information

Typescript 4.1

- I was unable to test this on prior versions because Typescript 4.1 introduced key remapping

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAcg9gITnANhAhgOwDwGkA0UAKgHxQC8xUEAHsBJgCYDOUARsmllAPxSYQAbhABOUAFxRcAWABQc0JCgAxAJYp6IpKgyZm2UhSgBvOVCgBtXFFWYoAawgg4AMyrpW8bVxwFiVgF0SAMkiQLkAXzkFcGg1DVEIRiN4zW9dfQtmYBFbAHNCDh0sQkwAVwBbNlFCzl0g6NkAeiaoZgALODKUZLhMFBAodABjYYgwYEsAIgBGKcIAZgC5Yb7sqBdJVMTkygtZ+agcsohFwhd0FGYIZdlFaAAZBjzgdpT1TST9tEwX9qnbi02p1ur1+oMRmMJlAAEylOCTAAsKzWkxQkiev1eRkRQA)

### 💻 Code

```ts
type NoBoolean<K, T> = T extends boolean ? never : K

type FilterBooleans<T> = {
  [K in keyof T as NoBoolean<K, T[K]>]: T[K]
}

type Filtered = FilterBooleans<[string, boolean, number, boolean]>

// should only accept ["1", 3]
const f: Filtered = ["1", true, 3, false]
type Length = Filtered["length"];
// should only accept 2, not 4
const l: Length = 4;
```

### 🙁 Actual behavior

https://github.com/microsoft/TypeScript/pull/26063 introduced mapped type support for arrays and tuples. This breaks when using the new "key remapping" feature added to TypeScript `4.1`. A `record` type is produced that looks like a `tuple`, rather than the `tuple` type that would be produced when not using `as` to remap keys.

### 🙂 Expected behavior

A filtered tuple type should be produced.

**Comment by jcalz** [comment]
Duplicate of #40586

I have the same issue here as there: even if you could manage to preserve a tuple type upon key renaming, I don’t see how you’d get a shortened tuple from it.  It would be a sparse tuple, if anything.  In your mapping, the key `"2"` would stay `"2"`, right?

**Comment by insidewhy** [comment]
@jcalz Thanks for the info. Getting a sparse tuple wouldn't be good for many use cases I think, not unless there was a way to compact it. Filtering an array is possible but not without lots of CPU and a size limit 😭
