### ISSUE TITLE
Class constructor improperly inherits types

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#42129]
# Bug Report

### 🔎 Search Terms

Class constructor, class inheritance

### 🕗 Version & Regression Information

- ~~This is the behavior in every version I tried,~~ and I reviewed the FAQ for entries about "class constructor inheritance"
- I was unable to test this on prior versions because: ~~I'm lazy~~

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201227#code/MYewdgzgLgBAKjAvDYAbAhhCMCmAPKHMAE2wGUdYBvAXwFgAoRsHAdxgqgAoAiACRAYAhDwCUAbmZt4vAcLHigA)

### 💻 Code

```ts
const T = class extends Set {}

new Set("Hola!"); // fine
new T("Hola!"); // error
```

### 🙁 Actual behavior

TSC claims that the constructors of `T` and `Set` have different input types.
But, `T` has no constructor, therefore the input should be of the same types.

### 🙂 Expected behavior

Classes that inherit from another class without defining their own constructor transparently should have the same type as calling the inherited class's constructor.

Okay, not exactly the same type, but at least regarding parameters, including overloads and generics.

Pseudo-type definitions: 
```ts
Set(...parameters: Parameters<Set>): Set
T(...parameters: Parameters<Set>): T
```

Possibly related?
https://github.com/microsoft/TypeScript/issues/38359

**Comment by saschanaz** [comment]
Hmm, maybe `const T = class<K> extends Set<K> {}`?

**Comment by 00ff0000red** [comment]
> Hmm, maybe `const T = class<V> extends Set<V> {}`?

Okay, that does work, but couldn't it be implicit?

**Comment by MartinJohns** [comment]
> I was unable to test this on prior versions because: I'm lazy

🤦

> but couldn't it be implicit?

And how would you distinguish between the different behaviors?

    class Foo<T = string> {}

    const TGeneric = class<T> extends Foo<T> {} // New class should be generic and pass T along. 
    const TString = class extends Foo {} // New class should NOT be generic and just use the default type parameter of Foo.
    const TNumber = class extends Foo<number> {} // New class should NOT be generic and provide a specifiy type to Foo.

**Comment by 00ff0000red** [comment]
> And how would you distinguish between the different behaviors?
> 
> ```
> class Foo<T = string> {}
> 
> const TGeneric = class<T> extends Foo<T> {} // New class should be generic and pass T along. 
> const TString = class extends Foo {} // New class should NOT be generic and just use the default type parameter of Foo.
> const TNumber = class extends Foo<number> {} // New class should NOT be generic and provide a specifiy type to Foo.
> ```

Oh, that explains what the code was doing: `class T extends Set<object>`, it was just implicit.
I'm not sure what behavior would even be considered "good," I almost wanted to say that we should allow:
```ts
const TGeneric = class extends Foo<> {}
```
to use the default, but then I remembered that I've been writing too much C++ recently...
