### ISSUE TITLE
Unable to use custom .d.ts types in files which are excluded from tsconfig

### ISSUE THREAD

**Issue by PizzaPartyInc** [microsoft/TypeScript#42132]
# Bug Report

### 🔎 Search Terms

custom 
types 
.d.ts 
tsconfig 
import 
declare 
module 
ts-node 
test 
jest

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `tsconfig.json Behavior`

### ⏯ Playground Link
Minimum reproduction repository: https://github.com/PizzaPartyInc/CustomTypesInExcludedFiles

### 💻 Code
Code from the repository should show everything, as it includes multiple files and several reproduction cases. Readme should describe the steps.

Here is an example of case one:

```ts
// src/generated/custom-module/schema.d.ts
declare module "custom/module" {
  export namespace custom_namespace {
    export interface Test {
      text: string;
    }
  }
}
```
```ts
// src/helpers/test-helper.ts
import { custom_namespace } from "custom/module";
export const getText = (test: custom_namespace.Test): string => {
  return test.text;
};
```
```ts
// src/case-one.spec.ts
// This file is exluded in tsconfig.json
import { custom_namespace } from "custom/module"; // VSCode error highlight here 'Cannot find module 'custom/module' or its corresponding type declarations.ts(2307)'
import { getText } from "./helpers/test-helpers";

describe("Import is highlighted in red because spec files are excluded in tsconfig.json", () => {
  it("returns expected text", () => {
    // Arrange
    const test: custom_namespace.Test = { text: "It Works Here Too!" };

    // Act
    const result = getText(test);

    // Assert
    expect(result).toBe(test.text);
  });
});

```
```json
//tsconfig.json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "baseUrl": "./",
    "preserveWatchOutput": true,
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "outDir": "./dist",
    "resolveJsonModule": true
  },
  "exclude": ["node_modules", "dist", "scripts", "**/*spec.ts"]
}
```

### 🙁 Actual behavior

When you have a custom type (local `*.d.ts` file with module declaration with a type in it) and want to use it in a file that is excluded by the tsconfig (test file or a script file that is called using ts-node) - typescript will not be able to find said type and either highlight the import with error `Cannot find module 'custom/module' or its corresponding type declarations.` or throw an error, depending on the specific case (test or script usage).

I have tried various settings like `paths` and `typeRoots` of tsconfig, including `--files` option of ts-node and was not able to find a proper solution, only workarounds. (in form of secondary tsconfig file or in form of `--transpile-only` option for ts-node) And having 2 different workarounds for the same issue is kind of sad :(

### 🙂 Expected behavior

Typescript should be able to pick up custom types for files which are excluded from ts-config via `exclude` property. (or have an option to do so.)

Would also appreciate any alternative solutions to make sure that custom types are recognized in excluded files. Maybe there is an easy alternative to restructure the code to be able to use custom types. Or perhaps some typescript option that I have missed or misused.

I would prefer to avoid including tests and scripts in tsconfig, because that will mean that output `dist` folder will have to be cleaned up and restructured each time after the build script has ran.

### Additional info

- VSCode version 1.52.1 is used

**Comment by andrewbranch** [comment]
For a file-by-file basis, you could triple-slash reference the declarations you need:

```ts
// src/case-one.spec.ts
// This file is exluded in tsconfig.json

/// <reference path="./generated/custom-module/schema.d.t.s" />
import { custom_namespace } from "custom/module"; // Should work now
```

But I would suggest you include your tests/scripts in a _separate_ tsconfig file (with `noEmit`).

**Comment by PizzaPartyInc** [comment]
Thank you! :)

For some reason every time I tried the triple slash reference - I was always forgetting the slash at the end `/>`, so it never ended up working for me before. Now it worked, but I agree, it's not a solution. I would only resort to it if there was a problem with a single file, not with each excluded file.

Regarding a separate tsconfig, I was already using something similar, but did not know about `noEmit`, so this improves my previous solution to a certain degree. Thanks! :)
Although there are still some inconveniences... you need to remember to always add `--files` flag to your ts-node scripts, otherwise ts-node ignores some tsconfig properties that matter (`exclude` in this particular case). Overall changes would look like this:

tsconfig.json (changed)
![image](https://user-images.githubusercontent.com/37663061/103263099-871f1e00-49af-11eb-85de-a217f5cccf2e.png)

tsconfig.build.json (added)
![image](https://user-images.githubusercontent.com/37663061/103263118-90a88600-49af-11eb-8093-86a6a1179f4e.png)

package.json (changed)
![image](https://user-images.githubusercontent.com/37663061/103263141-a4ec8300-49af-11eb-87a6-92bdc6af479e.png)

I wounder if there is a way to improve this further (and keep the same functionality in working order)? Or can this considered a proper solution for this particular case?

P.S. One thing to note with triple slash reference is that it seems like typescript-eslint discourages it's use by default ([`Do not use a triple slash reference for ../../generated/custom-module/schema.d.ts, use 'import' style instead. eslint(@typescript-eslint/triple-slash-reference)`](https://github.com/typescript-eslint/typescript-eslint/blob/v4.7.0/packages/eslint-plugin/docs/rules/triple-slash-reference.md)), but I assume it's a rule for frontend projects and should not apply to backend projects... Still, if this is required at some point, I assume that an override rule would have to be added to eslint config file.

**Comment by andrewbranch** [comment]
It really depends on what you’re trying to achieve and what tools are in your system here, but it seems like most of your problems are coming from ts-node, which I have never particularly enjoyed using. When I have auxiliary scripts that aren’t part of the primary program in a TS project, I usually write them in JS with `// @ts-check` and JSDoc. Or, they’re test files that ts-jest handles for me. Or, if they get complicated enough that I want to use TypeScript directly, I’ll compile them in a separate project with `tsc` and run the output JS with node.

**Comment by EneroPl** [comment]
I had the same problem with using local `d.ts` files in my project. Thanks @andrewbranch for answer, `noEmit` resolve it.
