### ISSUE TITLE
undefined[] converted to any[] in js

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#42133]
**TypeScript Version:**  4.2.0-dev.20201222

**Search Terms:** undefined any array

**Code**
In .ts everything is ok:

```ts
const a = [1, 2, undefined, 3]

const isUndef = (v: unknown): v is undefined => v === undefined

// OK: undefined[]
const b = a.filter(isUndef)
```

.js:

```js
const a = [1, 2, undefined, 3]

/** @type {(v: unknown) => v is undefined} */
const isUndef = v => v === undefined

// Expected: undefined[]
// Actually: any[]
const b = a.filter(isUndef)
```

**Expected behavior:**
Variable `b` has type `undefined[]`

**Actual behavior:**
Filter method returns `undefined[]`, but variable `b` has `any[]` type

**Comment by MartinJohns** [comment]
Interestingly the playground gets it right with `strictNullChecks` disabled (when it shouldn't), but gets it wrong with `strictNullChecks` enabled (when it should get it right).

[Playground with `strictNullChecks` enabled](https://www.typescriptlang.org/play?noImplicitAny=false&strictNullChecks=true&useJavaScript=true#code/MYewdgzgLgBAhjAvDA2gRgDQwExYK5gAmApgGYCWYxhWAzALoBQjA9AFRswACUAngA7EYAbwAUANwBcMAgGswIAO5gAlEgB8McTHIQZRMpWoBfGGxaNQkWLoCqB0ki0bniN-pIUqhZixYwAUQAPQWAoamkCTyNCFCY-GABBMLw4ABs03mk4MF44y3BoGAAjJzgAOgo08IAnUTsHFUYgA)
[Playground with `strictNullChecks` disabled](https://www.typescriptlang.org/play?noImplicitAny=false&useJavaScript=true#code/MYewdgzgLgBAhjAvDA2gRgDQwExYK5gAmApgGYCWYxhWAzALoBQjA9AFRswACUAngA7EYAbwAUANwBcMAgGswIAO5gAlEgB8McTHIQZRMpWoBfGGxaNQkWLoCqB0ki0bniN-pIUqhZixYwAUQAPQWAoamkCTyNCFCY-GABBMLw4ABs03mk4MF44y3BoGAAjJzgAOgo08IAnUTsHFUYgA)

**Comment by awerlogus** [comment]
@DanielRosenwasser, reopen this. I found related broken example.

Version 4.3.0-dev.20210228

```js
/** @type {() => undefined} */
function a () { return undefined }

// Actually: any
// Expected: undefined
const b = a()
```

**Comment by DanielRosenwasser** [comment]
In the future it's easier for us to just create a new issue and reference the old one.
