### ISSUE TITLE
for ... in over mapped types has inconsistent behaviour

### ISSUE THREAD

**Issue by efreeti** [microsoft/TypeScript#42135]
# Bug Report

```ts
for (const key in mappedTypeInstance) {
    // body
}
```

Constant _key_ is "_Extract<keyof T, string>_" when _mappedTypeInstance_ is of mapped type with unbound type parameter and is "_string_" when it is of mapped type with bound type parameter.

### 🔎 Search Terms

* Mapped types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAKhDOwoF4oG8CwAoKuoDMB7QgLigDsBXAWwCMIAnAGmzyloEMGzEGBLcgHMWOPJwBeZWsQA2EDuWwBfANzZsoSFADqDDmAA8MAHwp0rPABMOwDmRjL1WTdF37Ilo6dSZRuANoAClACUADWECCE+LAAumRuhjBBscZqWEpO+JTkAMbAfITkIcCMNhAAsu4QljDgEADiEOSMfLleABSEtABWCXpgHl4AlOZ+BIQMUB1ySGEhxd09o75sbLlF8IRyAHQyhIJdvf5hsTvWtsPpbJkZWTn5hcV8pXqlVYM1dZAAwkW5DAgpSOfR0AyGcEQxhWFlwRCmMyB4QWUCWMPG6022wgewOIJOZwuHCusKgtyUQA)

### 💻 Code

```ts
type Test = {
    foo: number,
    bar: string,
    baz: boolean
};

type Wrap<T> = {
    data: T
}

type Wrapped<T> = {
    [P in keyof T]: Wrap<T[P]>;
}

function iterateMappedTypeGeneric<T>(obj: Wrapped<T>) {
    for (let k in obj) {
        console.log(obj[k].data);
    }
}

function iterateMappedTypeConcrete(obj: Wrapped<Test>) {
    for (let k in obj) {
        console.log(obj[k].data);
    }
}
```

### 🙁 Actual behaviour

Function _iterateMappedTypeGeneric_ compiles without errors. Function _iterateMappedTypeConcrete_ gives compilation errors.

### 🙂 Expected behaviour

Either both of them should give compilation errors (probably correct but not convenient), or both of them should compile without errors (very convenient but probably not safe).

**Comment by efreeti** [comment]
Official documentation has example of iterating a mapped type using for .. in -  https://www.typescriptlang.org/docs/handbook/advanced-types.html#inference-from-mapped-types

So I would think making generic function not compilable would be a major compatibility issue.

**Comment by andrewbranch** [comment]
The errors is correct. I think it’s easiest to [show why](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.1.3#code/C4TwDgpgBAKhDOwoF4oG8CwAoKuoDMB7QgLigDsBXAWwCMIAnAGmzyloEMGzEGBLcgHMWOPJwBeZWsQA2EDuWwBfANzZsoSFADqDDmAA8MAHwp0rPABMOwDmRjL1WTdF37Ilo6dSZRuANoAClACUADWECCE+LAAumRuhjBBscZqWEpO+JTkAMbAfITkIcCMNhAAsu4QljDgEADiEOSMfLleABSEtABWCXpgHl4AlOZ+BIQMUB1ySGEhxd09o75sbLlF8IRyAHQyhIJdvf5hsTvWtsPpbJkZWTn5hcV8pXqlVYM1dZAAwkW5DAgpSOfR0AyGcEQxhWFlwRCmMyB4QWUCWMPG6022wgewOIJOZwuHCusKgt1u2AA9JSnBtyIgoKUGT5SURSOgoESyAAGMkiNicbgcrlQABEor5pIkZDQnJsdgIHBk8GgSn5eAgAA9cgh4GQAORgBiESAMUD69W4QSEYC5AAWCpylgg+AENWU6WwLzK72qtXqfzygOBTOAJKw3relT930azVauQ6ofDQA).

**Comment by efreeti** [comment]
I don't quite follow to be honest. How is the [https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8CwAoKuoDMB7QgLigDsBXAWwCMIAnAGmzyloEMGzEGBLcgHMWOPJwBeZWsQA2EDuWwBfANzZsoSFADqDDmAA8MAHwp0rPABMOwDmRjL1WTdF37Ilo6dSZRuANoAClACUADWECCE+LAAumRuhjBBscZqWEpOLrAIwIkeAKIAHsAQ5JYQlmb5lUa5pgBk6FAQRQDGCPA8wPxCTFCChMBtABZ2UJTlEPgClVCqTviTbcB8hOQhpXqlALLulTDgEADiZYx8bV4AFIS0AFYJemAeXgCU5n4EhAxQV3JIYRCG1ud3evjYbDa63ghDkADoZIRBDd7v4wrE4dZbK90mxMhknAB6QlOKHkRBQUqIey5GqWYqlKZVHwWXBEUjNLHjAAM8xEbE43E5NnGACJRXzWewOJJhbYyPgODJ4NAlPy8K0OvAulAAORgBiESAMUC69W4QbDMZkSYVGbkSrKdLYPhbGwQPbPA5HU4O-iXOCIYxXKnAHHYIA](following) valid?

**Comment by efreeti** [comment]
Or even more subtle to spot [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8CwAoKuoDMB7QgLigDsBXAWwCMIAnAGmzyloEMGzEGBLcgHMWOPJwBeZWsQA2EDuWwBfANzZsoSFADqDDmAA8MAHwp0rPABMOwDmRjL1WTdF37Ilo6dSZRuANoAClACUADWECCE+LAAumRuhjBBscZqWEpOLrAIwIkeAKIAHsAQ5JYQlmb5lUa5pgBk6FAQRQDGCPA8wPxCTFCChMBtABZ2UJTlEPgClVCqTviTbcB8hOQhpXqlALLulTDgEADiZYx8bV4AFIS0AFYJemAeXgCU5n4EhAxQV3JIYRCG1ud3evjYbDa63ghDkADoZIRBDd7v4wrE4dZbK90mxMhlFstVusoGAGIQOvB4HBECiHjoni8acBjGCLLg+FsbBA9s8DkdTuRzm06TioI4sNgAPRSpxQ8iIKClRD2XI1SzFUpTKo+dlfUjNLHjAAM8xEbE43ENNnGACJbWa9RIyGgoEayPgODJ4NAlOa8K1KV0oAByMmESAMUAh-24QbDMZkSYVGZCyzKdLYcNB5lXZXAHHYIA)

**Comment by RyanCavanaugh** [comment]
@efreeti "these two different things behave differently" is not a bug description. You'd need to make a positive case about which one should change and why.

**Comment by efreeti** [comment]
Both functions iterateMappedTypeGeneric and iterateMappedTypeConcrete can fail with the same runtime error when transpiled to JS code. iterateMappedTypeConcrete fails to compile, while iterateMappedTypeGeneric does not. If the goal is to prevent the runtime error than iterateMappedTypeGeneric should also fail to compile. On the other side then there is no safe way to iterate mapped types after such a change.

Having this inconsistency prevents a certain logical refactoring to be possible - narrowing generic function by binding the parameter type.

Also when exploring mapped types it lead me to believe there is no way to safely iterate them (which is in reality true) while the documentation contains example of doing that. It took me half a day and a lot of hair to in the end spot that the only difference between my function and documentation is generic type. In the end I could not find any logical explanation why it should behave differently.

It's weird that I'm the first one reporting this but it can be an indicator that bumps like this prevent people from deeply exploring application of mapped types and other comprehensive typing capabilities in TypeScript.
