### ISSUE TITLE
typescriptlang.org Playground not respecting settings for noUnusedLocals and noUnusedParameters

### ISSUE THREAD

**Issue by thre3eye** [microsoft/TypeScript#42140]
# Bug Report

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I just started using playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0MwAUVWDEQNUgADVHBQGNJ3KAALygABEAAkYNAMOB4GRogLFFTBPB3AExcwABT0xnM9zsyhc9wASmCKhwDQ8ZC8iElzhB7Bo3zcZmY7AYzEg-Fg0HUiS58D0Ii8AoZTJZggFSRxAvADlQAHJhAA5SASAVBFQAeW+ZF2gldWkgx1QjgUrmkeFATgtOlGWH0KAQiBhwiudokkuiIgMHBx3RYbC43CCJWCJUhkpo7oYgmEChpoAA3kOSouCOxueo0PpUCrp6hRgB9fLXVCUTjMPUHmnHsbzxc3xfuGicChg-kCx+rAUAbkUt9v9+M-IAbQABl4ABGXgACZeAAZgAXS-H8bwYAJkklOkekwFUVU4Xd+AobhVl3PVeQAPmvRCfzlBVICVeBVQAA2waAxVAAASWccIAX3ovUEIo0BOINb9+KcAkzUFbh4E4SBP2Em9OOEzigA

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```
  export class test {

      public test(testing_: string): string {
          let nix = "nix";
          let a = [0,1,2,3];
          a.forEach((n_, idx_)=>{
              console.log(`hello ${n_}`);
          })
          return "done";
      }
  }

### 🙁 Actual behavior

Regardless of the settings for 'noUnusedLocals' and 'noUnusedParameters' getting errors:
'...' is declared but its value is never read

### 🙂 Expected behavior

I don't want to see these (ignorable) errors because I configured the settings to ignore them. 

Thanks

**Comment by andrewbranch** [comment]
These still appear as suggestion diagnostics because they power codefixes. Suggestion diagnostics can be disabled in VS / VS Code, but not in the playground.
