### ISSUE TITLE
TypedPropertyDescriptor<T> doesn't allow decorators that support methods and getters

### ISSUE THREAD

**Issue by SystemParadox** [microsoft/TypeScript#42142]
# Bug Report

### 🔎 Search Terms

Method decorator, getter decorator, cache decorator, PropertyDescriptor, TypedPropertyDescriptor.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about decorators, methods and property descriptors.

### Description

The interface for decorators currently looks like [this](https://github.com/microsoft/TypeScript/blob/e4c4292807f10b093aaffa9dfabdf6fbe22c6ffd/src/lib/es5.d.ts#L1385-L1392):

```ts
interface TypedPropertyDescriptor<T> {
    enumerable?: boolean;
    configurable?: boolean;
    writable?: boolean;
    value?: T;
    get?: () => T;
    set?: (value: T) => void;
}
```

Notice that we've got `get?: () => T`, but just `value?: T`. This makes it incredibly difficult to declare a decorator that supports both getters and normal methods. For example, a cache decorator.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBAhhAFgUwDwBUB8AFFCgE4DmmUAXIgPIBGAVptADSIDWmAnrQM5RSMMOQ4ATTPwjCADlDilauHrMziACqThrSUHgBEpMmPMV58ASkQBvAFCJHiADZVEAWyro44xAF5ESWk5BVIAOkooRAAfaMDjEMUwgDcUZxBMAG4HJ1co4CQA0EhYBERidBh+WhQwHktlWxynJxhgcoBCRChK-jCAfVQMTGt7FvGnHqqBoax-WwBfbInHBebxvMRBtDmAqb7t4eWVts6t2cwAbW4eAF1R9ZXznaub2-nPHp8w1GdnCqqlmOEzWT1IVBApCQhyw114t2BiCW61OhCCJjM4UiDye6MSWLcRTAiIWiEwzn4mCauISplCKTSGXmBRJdjWdggzhQ-H4iAAYnA4NSnAABC7rSKIYCCwgNfmC4UTcFQSFIMCYADu8rgstZ6zFLwlVAFOrlJsV42VqsQ6q1Jt16zWCyAA)

### 💻 Code

```ts
function cache<T>(target: Object, key: string, descriptor: TypedPropertyDescriptor<T>) {
    let method = descriptor.get || descriptor.value;
    let fn = function (this: any): T {
        if (! this._cache) {
            this._cache = {};
        }
        let _cache = this._cache;
        if (! _cache[key]) {
            _cache[key] = method.call(this);
        }
        return _cache[key];
    };
    if (descriptor.get) {
        descriptor.get = fn;
    } else {
        descriptor.value = fn;
    }
}

class Foo {
    @cache
    get foo(): Foo {
        return new Foo();
    }

    @cache
    getFoo(): Foo {
        return new Foo();
    }
}
```

### 🙁 Actual behavior

Using `TypedPropertyDescriptor<T>` works for getters, but gives errors like this if you try to make it work for normal methods:

```
Property 'call' does not exist on type '(() => T) | NonNullable<T>'. Property 'call' does not exist on type 'NonNullable<T>'.
```

Using `TypedPropertyDescriptor<() => T>` works for methods, but gives errors like this if you try to make it work for decorators:

```
Type '(this: any) => T' is not assignable to type '() => () => T'. Type 'T' is not assignable to type '() => T'.
```

### 🙂 Expected behavior

There should be a way to declare a typed decorator that works for getters and methods.

```
interface TypedCallablePropertyDescriptor<T> {
    value?: () => T;
    get?: () => T;
}
```

### Related issues

https://github.com/microsoft/TypeScript/issues/32545

**Comment by andrewbranch** [comment]
Don’t know enough about decorators to answer this one, but I’m guessing this is a design limitation like #32545.

**Comment by CMCDragonkai** [comment]
I was wondering why `TypedPropertyDescriptor` had no way of limiting itself to methods only and not getters and setters. But it looks like the interface allows all of `get`, `set` and `value` to be optional.

Does that mean atm, one has to write a specific interface if they want to limit it?

**Comment by rbuckton** [comment]
The `T` in `TypedPropertyDescriptor<T>` is designed to indicate what `obj[key]` would return. If you want to use it to indicate both a method and getter with the same signature, you would need to use a union like `TypedPropertyDescriptor<T> | TypedPropertyDescriptor<() => T>`.

In addition, `TypedPropertyDescriptor` and `PropertyDescriptor` both reflect what can be passed to `Object.defineProperty` or can be returned from `Object.getOwnPropertyDescriptor`, in which case `value`, `get`, and `set` are all optional. 

I considered having the compiler synthesize a custom `TypedPropertyDescriptor` based on the declaration (i.e., `Required<Pick<TypedPropertyDescriptor<() => void>, "enumerable" | "configurable" | "writable" | "value">>` for a method), but that ends up not working in practice. TypeScript's legacy decorators have the ability to convert methods into accessors, or to delete getters or setters. This means that if there are multiple decorators applied to an element, any one of them could change the descriptor in such a way as to make that type invalid for subsequent decorators. As a result, this is both a design limitation and is working as intended.

We shipped support for the Stage 3 ECMAScript Decorators proposal in TypeScript 5.0. ECMAScript Decorators do not allow you to change decorated element from one kind to another (i.e., methods must remain methods, etc.), so you can enforce the kind of class element they can be used on.
