### ISSUE TITLE
Generated declaration files rewrite import paths

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#42155]
# Bug Report

Originally reported in https://github.com/mui-org/material-ui/issues/24112

### 🔎 Search Terms

`declaration file relative import`

Possibly related: https://github.com/microsoft/TypeScript/issues/38111, https://github.com/microsoft/TypeScript/issues/39695, https://github.com/microsoft/TypeScript/issues/36763, https://github.com/microsoft/TypeScript/issues/18311

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (4.1.3, 4.2.0-dev.20201230), and I reviewed the FAQ for entries about: everything (could not find relevant entries)

### ⏯ Playground Link

Not applicable but I have a cloneable repro: https://github.com/eps1lon/ts-monorepo-type-import-paths

### 💻 Code

```ts
// styles/index.ts
export interface CSSProperties {
  [k: string]: unknown | CSSProperties;
}

export type StyleRules<ClassKey extends string = string> = Record<
  ClassKey,
  CSSProperties
>;
export function createStyles<ClassKey extends string = string>(
  styles: StyleRules<ClassKey>
): StyleRules<ClassKey> {
  return styles;
}


// core/index.ts
import { createStyles } from '@material-ui/styles'; 
export const styles = createStyles({
  root: {
    display: 'block'
  }
});
```

### 🙁 Actual behavior

Generated declaration file imports types via relative path (`"../../styles/src"`).
This path is invalid once published to npm. I was under the impression the `paths` does not apply any rewrites (source: https://github.com/microsoft/TypeScript/issues/25677#issuecomment-405372653)

```ts
// core/dist/index.d.ts
export declare const styles: Record<"root", import("../../styles/src").CSSProperties>;
//# sourceMappingURL=index.d.ts.map
```

### 🙂 Expected behavior (minimum viable)

Types are imported with the original identifier (`"@material-ui/styles"`). Otherwise they're unreachable once installed.

```ts
// core/dist/index.d.ts
export declare const styles: Record<"root", import("@material-ui/styles").CSSProperties>;
//# sourceMappingURL=index.d.ts.map
```

### ideal expected behavior

```ts
// core/dist/index.d.ts
export declare const styles: import("@material-ui/styles").StyleRules<"root">;
//# sourceMappingURL=index.d.ts.map
```
This is the actual return type of `createStyles`. TypeScript should never inline types from libaries we import. Otherwise we need to re-build and publish everytime a dependent library changes their types.

**Comment by andrewbranch** [comment]
I believe this is a definite duplicate of #39117 (which was pointed out to be a probably duplicate of #38111). Does that seem like the same problem @eps1lon?

**Comment by eps1lon** [comment]
> I believe this is a definite duplicate of #39117 (which was pointed out to be a probably duplicate of #38111). Does that seem like the same problem @eps1lon?

Definitely! Thanks for the pointers especially since they contain potential workarounds. 

Closing in favor of https://github.com/microsoft/TypeScript/issues/39117
