### ISSUE TITLE
Union types and array.concat problem

### ISSUE THREAD

**Issue by NikitaEgorov** [Microsoft/TypeScript#4216]
```javascript
var a = (): number | Array<number> => {
	return Math.random() > 0.5? [2,3] : 3;
};

var b = [1];

b.concat(a());
```

http://www.typescriptlang.org/Playground#src=var%20a%20%3D%20()%3A%20number%20%7C%20Array%3Cnumber%3E%20%3D%3E%20%7B%0A%09return%20Math.random()%20%3E%200.5%3F%20%5B2%2C3%5D%20%3A%203%3B%0A%7D%3B%0A%0Avar%20b%20%3D%20%5B1%5D%3B%0A%0Ab.concat(a())%3B

**Comment by aleksey-bykov** [comment]
in the left hand you have apples, in the right hand you have apples *and* oranges, now you are confused: when you put your hands together those oranges that you hold in the right hand don't turn into apples, why is that?

**Comment by darrylring** [comment]
Which is the slightly unhelpful way of saying that union types aren't currently compatible with overloaded functions (see #1805). Neither overload of `concat` accepts `number | number[]`.

From lib.d.ts:

```typescript
concat<U extends T[]>(...items: U[]): T[];
concat(...items: T[]): T[];
```

**Comment by aleksey-bykov** [comment]
Pardon me, didn't know `concat` is designed so loose.

**Comment by darrylring** [comment]
I'd say it's the opposite of loose. In JavaScript you could do:

```javascript
b.concat(2, [3,4], 5, [6]);
```

The way `concat` is defined in `lib.d.ts` forbids this. You can give it one or more `T` or `T[]`, but not both.

**Comment by aleksey-bykov** [comment]
that's what I meant by saying it's designed loose in JavaScript, didn't expect it to be this way, the original observation is valid, technically libs.d.ts should be revised, although personally I'd keep it the way it is, but it's a question of what you believe in

**Comment by darrylring** [comment]
Ah, gotcha. I also think `lib.d.ts` is probably correct.

**Comment by weswigham** [comment]
You can retype the original code like so:
```ts
declare type RandomResult = number | Array<number>;

var a = (): RandomResult => {
	return Math.random() > 0.5? [2,3] : 3;
};

var b: RandomResult[] = [1];

b.concat(a());
```
And it passes the typechecker. Possibly not necessarily for the expected reasons.

**Comment by mhegazy** [comment]
Looks like the original issue has been answered. please reactivate if you are running into other issues.

**Comment by pmowrer** [comment]
Here's an active thread on this problem: https://github.com/Microsoft/TypeScript/issues/6594
