### ISSUE TITLE
why the result of  tuple to union  using T[number] is disorder

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#42178]
version : ^4.0.3

[ you can find code here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDaBGANAJjQZgLoFgAoUSKAIQViQDsBXAWwCMIAnAwooA)

or just look at this
```ts
type A = [1,2,3]
type B = A[number]

// expect ^= type B = 1 | 2 | 3
// output:  ^= type B = 3 |  1 | 2
```

I know it doesn't effect using, but I wonder the order mechanism

**Comment by ajafff** [comment]
Types in unions are (most of the time) ordered in the order they were encountered when checking your code. This order is not guaranteed (see #17944 and linked issues) and may change in every compiler version or by changing your code just a tiny bit.

In your example `3` is encountered first as the length of the tuple, then the numeric literals `1`, `2` and `3` again.
If you change your code a bit, you get a different order:

```ts
type A = [0,1,2,3]
type B = A[number] // 0 | 1 | 2 | 3
```

**Comment by HomyeeKing** [comment]
@ajafff  ok  , thanks 
I think it depend the algrithom behind the processor
we'd better give in to performance
