### ISSUE TITLE
typeguard else statement is not working properly

### ISSUE THREAD

**Issue by ATheCoder** [microsoft/TypeScript#42185]
# Bug Report

### 🔎 Search Terms

Typeguard else not working

Type guard not working

### 🕗 Version & Regression Information

- I first had this issue on version 3.9.5 but I also tested it on the playground nightly and it still happens.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBATgUwOYFcA2BDOA5DBbBAFRAFUwBLUAEwQFkMAHGAXhgG8AoGGACRAIBcMAMpQ45MEgB0AMzj8AwgAssCkDQAUABgAeMgEwA2fQEoANFxgAFNCiQSho8ZNny8y1eoTa9RgIzmloSICI5iEtJyiipwapq6BgCsMoHcwsBKCHgYYc6Rbh6xXj5JCIEAvgDcHBygkLAQIGjkVLgExGSUXvRMrJxpCFgZuRGu0Z7xelpaphZVNRJQCHAyGMAIMACSdVbyDBAAPIQwCDpLYFQQMADkiKiYcNcwAD43jc1U1wB87JZQAJ4MUIwQjVbhdMBCY6nc6XG53dBYa6WbgAfhgAGsEP8QDIYACgbj4MhETh8ERSBRqHRGCiYEIsTi8QSEET3i02hTOtSetVyjUWTAAEokh7bcAsTHYoksokIh6cjpU7qMaqC4RNFrisCSxkywGsvHs1rkpVdGi8mp1aAwcgQEX3LCSjR-A1CW6ipEvN6az4WcF1IQO0na70aj7aiwmIQQ21XYNiuosH79YlQFBwHWC5g5+Gex586q1cA2qySo4nM4IC5Xa7Gp6vD2Ox5fDQMPYQITa3YgfZHL7RmAYMD-ZO-bgTifkGQaO0JrBtjtSFlmGDt3sQKQQkwmVOT-f7xDpzPE5uKynmmkMADa6-2W7qAF06ZPyic0BANnuDz+jxmdca57ciqN53puELPj+MD8uUQA)

### 💻 Code

```ts
const regularNameToUnicodeMap = {
  Home: String.fromCharCode(0xf262),
  Plugin: String.fromCharCode(0xf261),
  Tree: String.fromCharCode(0xf25f),
  Schema: String.fromCharCode(0xf25e),
};

const solidNameToUnicodeMap = {
  Search: String.fromCharCode(0xf002),
};

interface IconProps<T extends 'regular' | 'solid'> {
  type: T;
  icon: T extends 'regular'
    ? keyof typeof regularNameToUnicodeMap
    : keyof typeof solidNameToUnicodeMap;
}

type RegularIcon = keyof typeof regularNameToUnicodeMap;
type SolidIcon = keyof typeof solidNameToUnicodeMap;

const isRegular = (
  type: 'regular' | 'solid',
  icon: RegularIcon | SolidIcon,
): icon is RegularIcon => {
  return type === 'regular';
};

const P = <T extends 'solid' | 'regular'>(props: IconProps<T>): any => {
        if(isRegular(props.type, props.icon)){
                return regularNameToUnicodeMap[props.icon]
        } else {
                return solidNameToUnicodeMap[props.icon] //Error happens here.
        }
}
```

### 🙁 Actual behavior

I get an error:

```
Type 'T extends "regular" ? "Home" | "Plugin" | "Tree" | "Schema" : "Search"' cannot be used to index type '{ Search: string; }'
```

### 🙂 Expected behavior

There shouldn't be an error because according to the [docs](https://www.typescriptlang.org/docs/handbook/advanced-types.html) typescript should know that when the type guard returns false `icon` is of type `SolidIcon`.

**Comment by RyanCavanaugh** [comment]
Given how narrowing and generics interact today, we don't have any way to represent the type of `props.icon` in the `else` branch without negated types; see #29317

**Comment by sladiri** [comment]
Hi, is this the same problem? I have a very minimal example https://stackblitz.com/edit/typescript-s2c1jm?file=index.ts
