### ISSUE TITLE
Generic type can't infer the value as property

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#42187]
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5ICwAUAC6QAOKAKlmQDw2hIAeZSAdgtpmfgEtOqADQA1AHygAvKADeNAFxiAvqQrVQAeQCuZSnpmg6fBgHI8AG0twzIswHc4+SwjMSgA)

### 💻 Code

```ts
// My code goes here
type Test<T extends string,V> = {T:V}
type Output = Test<'hello','world'>
```

### 🙁 Actual behavior
// ^= Output = {T:'world'}

### 🙂 Expected behavior

// ^= Output = {hello:'world'}

**Comment by awerlogus** [comment]
```ts
type Test<T extends string, V> = { T: V }
```
is equal to

```ts
type Test<T extends string, V> = { 'T': V }
```

---

so, try using this:

```ts
type Test<T extends string, V> = { [K in T]: V }
type Output = Test<'hello', 'world'>
```

**Comment by HomyeeKing** [comment]
@awerlogus  shouldn't infer to the string value we pass through ? for my intuition

**Comment by awerlogus** [comment]
@HomyeeKing, no, in `{ T: V }` `T` is just a string literal `'T'`. 
To make it use value of generic `T` you must use such notation: `{ [K in T]: V }`

**Comment by HomyeeKing** [comment]
@awerlogus  ok, thanks
