### ISSUE TITLE
Missing completion after 'asserts' in return type

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#42180]
# Bug Report

### 🔎 Search Terms

completion list, assert, asserts

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, since the feature was introduced in 3.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210102#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAKANwC4DUBPASlqJLMPgHoAqAH285A)

### 💻 Code

```ts
declare function assert(v: any): asserts /* | */
```

### 🙁 Actual behavior

Typing `v` after `asserts` brings up the completion list with `void` at the first position. I'm used to accept the first completion, so I end up with an invalid asserts predicate.

### 🙂 Expected behavior

List all parameter names of the function and/or `this`

**Comment by Simar-B** [comment]
Hi is this bug being worked on?

**Comment by Simar-B** [comment]
Hi this is my first time working with the typescript compiler I'm wondering if any of you know what files I should be looking at to fix this issue?

**Comment by ajafff** [comment]
@Simar-B the relevant code should be somewhere in this function: https://github.com/microsoft/TypeScript/blob/154f2094fc921911896e7edf1583d0d7fe672782/src/services/completions.ts#L161

Unfortunately I cannot give any more guidance as I don't have any experience with completions and don't know how to debug this code.

**Comment by hantatsang** [comment]
@ajafff Is your playground code a complete example? It's throwing error on `asserts` return type

**Comment by ajafff** [comment]
The code is intentionally incomplete to show where I expect a completion.
The code becomes valid if you replace the comment with `v`

**Comment by Kingwl** [comment]
Hi @Simar-B . Are you still interested on working on this?

If so, I might could give more suggestions for you (recommends).
If not, I'm also happy to working on this.

**Comment by Simar-B** [comment]
Hi @Kingwl. Sorry for not mentioning it earlier but I am not working on this.

**Comment by Kingwl** [comment]
@Simar-B Okay. Never mind.

**Comment by omril321** [comment]
Hi @Kingwl , are you working on this? I haven't worked on TypeScript in the past and it looks like a good first issue :)

**Comment by corymharper** [comment]
@omril321 I don't know if he was, but I started working on it this morning, since I didn't see anyone else say they had.

**Comment by omril321** [comment]
@corymharper got it. Thanks for letting me know :) Good luck!

**Comment by Kingwl** [comment]
Nope. Please feel free to working on this one

**Comment by saitonakamura** [comment]
I haven't seen any update on this so decided to give it a shot
