### ISSUE TITLE
Differentiating non-literal template strings from literal template strings

### ISSUE THREAD

**Issue by joonaparjanen** [microsoft/TypeScript#42181]
# Suggestion

## 🔍 Search Terms

-   template string
-   template literal
-   extends
-   string
-   differenciating literal from non-literal

## ✅ Viability Checklist

My suggestion meets these guidelines:

-   [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
-   [x] This wouldn't change the runtime behavior of existing JavaScript code
-   [x] This could be implemented without emitting different JS based on the types of the expressions
-   [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
-   [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

_Non-literal template strings_ should be possible to distinguish from _literal template strings_ inside type notation.

One option would be to not extend _non-literal template strings_ from a string type, because they really aren't strings _( i.e. object keys can't be extended from non-literal template strings )_

```ts
type NonLiteral = `${string}` | `${number}` | `foo${string}bar`;
type Literal = `${"a" | "b"}` | `${1 | 2}` | `foo${1 | "a"}bar`;
```

## 📃 Motivating Example

**Currently there is no way for differentiating viable object keys, 
when template literals are generated from generic types:**

```ts
type Keys = `foo_${string}` | `foo_${number}` | `bar_${"foo" | "bar"}`;

const obj: Record<Keys, string> = {
	bar_foo: "works as expected",
	bar_bar: "works as expected",
	foo_bar: "type error from key", //So by intuition `foo_${string}` should not be a string
	foo_1: "type error from key", //So by intuition `foo_${number}` should not be a string
};
```

## 💻 Use Cases

With this change we could:

1. Differentiate template literals inside type notation which can be used as keys for an object.
2. Differentiate literals and non-literals inside type definition.

**After this feature:**

```ts
type ExcludeNonLiterals<T extends string | number> = `${T}` extends string ? T: never;

type TemplateLiteral = `foo_${string}` | `foo_${number}` | "bar_foo";

type Case1 = ExcludeNonLiterals<TemplateLiteral>; // === 'bar_foo' | 'bar_bar'
type Case2 = ExcludeNonLiterals<1 | 2>; // === 1 | 2
type Case3 = ExcludeNonLiterals<"foo" | "bar">; // === 'foo' | 'bar'
type Case4 = ExcludeNonLiterals<string>; // === never, because `${string}` !== string
type Case5 = ExcludeNonLiterals<number>; // === never
```

**Comment by RyanCavanaugh** [comment]
Maybe I'm misunderstanding, but this seems like a duplicate of https://github.com/microsoft/TypeScript/pull/26797 ?

**Comment by joonaparjanen** [comment]
Yeah, that's what I'm looking for! 
Thanks, I'm closing this issue.
