### ISSUE TITLE
can't assign the default value to the generic type with same type

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#42188]
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5ICwAUAGYCuAdjAC4CWcVotWtAPACqhIAerVBNky189KqgB8ACloAuTgF4A5MoCUAb1KgdoQrQr5mtUgF8gA)

### 💻 Code

```ts
function test<T extends string>(t:T=''){
    return t
}
```

### 🙁 Actual behavior

Type 'string' is not assignable to type 'T'.
  'string' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'string'

### 🙂 Expected behavior

function works

**Comment by MartinJohns** [comment]
> can't assign the default value to the generic type with same type

But they're not the same type. Your default value is of the type `""`, but your generic type can be **any** specific kind of `string`.

For example:

    test<"bar">(); // T is of type "bar", assigning an empty string would be wrong.

**Comment by HomyeeKing** [comment]
@MartinJohns  so how to make it work, how to give it a default string value

**Comment by MartinJohns** [comment]
If you want to assign a default value, then your type must be compatible with the default value. In your example you could write:

    function test<T extends string>(t: T  | "" = "") { return t; }

You can't provide a default value to a generic type, because you can't know what type this will be at compile time.

**Comment by HomyeeKing** [comment]
@MartinJohns   alright , that make sense,  sometimes  I need to realize I am typing  type  😓

**Comment by HomyeeKing** [comment]
@MartinJohns  hey,  sorry to bother you again, [please look at this one](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWBvAUMg5OALmQGcwpQBzAbn0PVJAFcBbdaegX1zAE8ADigCqIYAHsQGTMgC8aLMgBkybGwkATCABtSARl4DhyACoQK85AGsI-CTGRjJ0rLlwQAHoIlQwyGBYQBDAXMwswAB5TZC9IEE0yJ3EpGQAaZABpWM94xJs7B2SXGQA+AApBKAlBMlJTDLgoalJshQByDW0ddoBKYlMAbUyAXTUGAigIMBYoEGQqmrJBpuoR3F4gA)

```ts
interface Obj{
    a: string;
    b: number;
}
type UnionObj = Obj & {model: 1}
type Test = keyof UnionObj

export function Test<T extends UnionObj, K extends keyof UnionObj>(props: T, arg: K = 'model'):T[K] {
    return props[arg]
}

```

it still confuse me
