### ISSUE TITLE
Function.prototype.bind typings do not work properly when supplied a function with variadic arguments.

### ISSUE THREAD

**Issue by benlesh** [microsoft/TypeScript#42196]
# Bug Report

If you pass a function that might behave differently when supplied different arguments, the resulting type does not properly accommodate all call patterns.

I ran into this while trying to figure out how TypeScript handled situations similar to RxJS's `bindNodeCallback` and `bindCallback`, which suffers from similar problems.

### 🔎 Search Terms

- `bind`
- `bind "Arguments for the rest parameter"`

### 🕗 Version & Regression Information

versions 3.3.* - 4.1.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about (I have no idea where the FAQ is, reporting anyway, because this is friction)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-JwBcyAzmFKAOYDcuAvrqJLIigEKa4HIBGJ5SiFoMm4aPCTIAwlzwEEAitTo5GOZhLbIAInJ4ATJUJFrcuBAHsQ5QiXQBeTHeQByOK+T1VVm2D4knE4YAW68nt4W1raKMsjByLGuCBE+0f5GuvHOma4GqeY4APRFyAAyEGCupGRwAJ7IYAAWEKQocFAozSjWADYNAG5wvcAGyADu9TVglrglicO9yJYArlDIAAaQ5BvIMCsgCGDA1kS4+4fH1o2tYAAUxGgANKHsAJT2NMjzAIznB0cTiAbuQHvYXrFpB9kOwvvMAEz-S5AkH3R6oF78GEvTI6aHSOGlADMhXmACJgABbAAOvTJyBanSRgOu2zR4L4AHkoNJAsgAD4yHEAfhIePsAphktk2Hk+GAMGQd2ApFQDzeb30PAICqVKvYd143Khmtl2vNyF1ytIOjuBg1WotFs6YDWwJCSTZqW+xO4ToI9GQEF6bUd-p4Lrdzkeri9XkJyD+cv96idqYtVpV0kNxodZvDyEjUHdoVjt29CL95vT+BrjSaUEs42QIAgzYAolBG1A7q5xo3hAter1XG9VOpmVdgSq1aBqSswCQ4CA6tC5wvLTV0Pn8EXpyB5-4AGRHtweS37w-IE+NOrUiCWRXrsAAbXcrgAuvEHE5qsphK446FBcLLTqQBrPkuK5rgeG4qlKO6FpUUbPtep6uOEF4XleN5gHeD5PrBr4YZ+36-oI1CAaIOCTiiWbKkRUGriQqHwTKVZIa6xbYRuN7JJ4oA8cep54fej5CW+KRfj+5H-lQVFmDROAgVOm62pBhDQSxRGblkiF7kJaFuPkWGobh+Hic+b75NJP5uBRAFAUpUR+MgAAe2RsgAdLwoAGHcIArMOLxwJiY6FL4tjrE4bl3OFSmRZYvQQF5vSWFQdxQGOQA)

### 💻 Code

```ts
interface A {
    a: string;
}
interface B {
    b: string;
}
interface C {
    c: string;
}
interface D {
    d: string;
}

const a: A = { a: 'a' };
const b: B = { b: 'b' };
const c: C = { c: 'c' };
const d: D = { d: 'd' };

// Let's say these are the only valid ways to
// call our `test` function:
function test(a: A, b: B): A; // 1
function test(a: A, c: C): B; // 2
function test(a: A, b: B, d: D): C; // 3

// "impl" here
function test(a: A, bOrC: B | C, d?: D): A | B | C {
    if (isA(a)) {
        if (isB(bOrC)) {
            if (isD(d)) {
                return { c: 'test' }; // 3
            } else {
                return { a: 'test' }; // 1
            }
        }
        if (isC(bOrC)) {
            return { b: 'test' }; // 2
        }
    }
    throw new Error('wrong call');
}

function isA(input: any): input is A {
    return input && 'a' in input && typeof input['a'] === 'string';
}

function isB(input: any): input is B {
    return input && 'b' in input && typeof input['b'] === 'string';
}

function isC(input: any): input is C {
    return input && 'c' in input && typeof input['c'] === 'string';
}

function isD(input: any): input is D {
    return input && 'd' in input && typeof input['d'] === 'string';
}


const x = test.bind(null, a, b);

const r = x();

console.log(r);
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/1540597/103491491-ef279700-4de9-11eb-98c5-e9acfc597e2d.png)

I got a compilation error for a perfectly valid call of my bound function.

### 🙂 Expected behavior

The return type (the type of `r`) should be `C`, and the code should compile successfully.

**Comment by benlesh** [comment]
Additionally, for a "real world" example of where this doesn't work properly. You can use `readdir` from Node.js:

```ts
const readHome = readdir.bind(null, '~/home');

readHome((err, results) => {
    if (err) {
        throw err;
    }
    for (const result of results) {
        console.log(result);
    }
});
```

[Playground link here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBATgUwIYBMASIC2CYF57IooCWcAdAEbFgoAUYArgDZMA0MA5AH4D0AFlgQcAlAG4AsACgpiVBmy1aCOHHaIIzKBGF4AfDADeUmCZjEAZjCUqdRyaYcwofOCADuMZXAn3TAX2NTcxA4K1BIWHVNGBBLKKYtW0DHGHCIECYEMiYQAHNaeKgxZJgAyT9i6SqpHlq6+obGpuaWhpqeGAAlZHSwJApMmHMkYAhiTGJB2JgRqAYkJicATwAHBAh21q3tndqpKXMGMGAoYnACVBI4WhKVpGcALhhoOGpc1hKQFdPwCCeDTzHEAkMC5J4AIQY5nMygAokCQbkYAAfGCMFiiGBuYjOABikwQABVVusAPxPYZMCA4PwomCQ6FwhFvOlHFAIczUBAoOnotglYALJgUEYAaye1jgTwAcsCELCVCFecw2EMCX9nlBXqCANoAXR0uH0ADcQMQUB9JMInqbzT4DkcTmcwBciKRaHdHprte8Yt9nRqAQhmaCngAiChQmFwMOY7F4gnEtYQclDBbU0p0iNR5Rh9iClgi4DiqxeGVyhWuUKovnsTmZDUM6P6w0ms0oa0wW0oe1VQ7HH4u2Ru663e58J4vN6WhxfQeNpDU+GgREAeX9vxgADJDFicXx8Zkk2SKemaXSm0yVyzUWyOVyeTWVTPTAXhWKJWWYLL2ZWlU+WDrdVJy1N59QvHM4BbPQu3bS1O27Xt+ydc5hyuD1xxAn18yFIsS0lctf0Vas0WfNUGywsCDRg7sEPbJDHUHV10M9CdvWnP15whRd5RDXJ13nbdd3jA9ExJDUtQYGkcMLD9SxUJ4kDAJYgIomAABFSGDKBoKNWDzTou19kkXZTN2doYFxJBRRwcYViYTYzKcpoHQHZ1mPdMgvKQOBcg1JSlkMnk7CkMpjMc5zItMizD0yUIoHEoYlX6EBjQQCKosy1opGoKBlGGYAcEvOBl2BFk7AcaAo0U5T9R8MLJFy-KRhwH95WIwwSgGJA2IC+rjKauACqKnjSrXDdIE63wTGDa9Q3Y0F+qqQbhvpSCpocSNGUQFBCT4N5-NqvUlqAA)

**Comment by RyanCavanaugh** [comment]
See #38353

`strictBindCallApply` / typed `bind` work by picking up the argument list and trafficking it through to the output function type; this process isn't able to handle multiple overloads.
