### ISSUE TITLE
Inequivalent intersection types are treated as equivalent

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#42204]
# Bug Report

Inequivalent intersection types are treated as equivalent.

This issue seems to arise for intersections of function types with overlapping domains. In these cases, order matters when it comes to calculating return types based on arguments, but does not seem to matter for assignability.

> cc @ilya-klyuchnikov, who helped find this

### 🔎 Search Terms

intersection, intersection type, assignability, equivalence

### 🕗 Version & Regression Information

4.1.3
Nightly–I think 4.2.0-dev.20210104
4.0.5
3.9.7
3.8.3
3.75
3.6.2
3.5.1
3.333

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about intersection types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.6.3#code/C4TwDgpgBAWgjFAvFAFC4ALAlgOwOYBcUAzsAE654CUSAfCeZVQFBRvscBkq62+RAVxwBrHAHsA7jhqJ6OAQFsARhDJUA3M2ahIsAExIemSoJHipMuYpVrWHe9zTH+DCvkuumm5gBMIAYwAbAEMyaH8xHFIoAC84InhNPyDQ8MjomL0EvW8AelyoTGgVDGCANywxMigxADNYhGCcH1iDLGIoH3bgXH9gZgio4EL4z3xDOJQAIimNAfTh4CyoeWVVCb1p2byCkAhhuKgmlsyjsKhcYFVg4mIsPBxgpUCIeaHCiFJR+A3NQeirqRljADMg4jsjs1YI0oSCoBAAB5XKEQYL+DA1IpkbTgaAAUQAjgIsGVgi8cMAADwAFQANFAAKr0ZDU+FIiDNDoMqAAfkZbORPg6rL55AE0CIOAgZXWkulqj+Cw+pGpuKIhOJpPJVPg9JBzMKZHFmiAA)

### 💻 Code

```ts
type Z1 = ((thing: string) => string)
          & ((thing: unknown) => number);

type Z2 = ((thing: unknown) => number)
          & ((thing: string) => string);

declare const z1: Z1;
declare const z2: Z2;

// the behavior of z1 and z2 is distinct
const t1: string = z1("");
const t2: number = z2("");

// yet z1 and z2 are interassignable
const test1: Z1 = z2;
const test2: Z2 = z1;

// and Z1 and Z2 extend each other
type Equivalent<T, U> = T extends U ? U extends T ? true : never : never;
const testType: Equivalent<Z1, Z2> = true;
```

### 🙁 Actual behavior

z1 (of intersection type Z1) and z2 (of intersection type Z2) have different behavior: the return types of z1("") and z2("") are distinct. Yet z1 and z2 are interassignable and TS thinks Z1 and Z2 extend each other.

### 🙂 Expected behavior

In the code example, I'd expect either t1 and t2 to have the same type **or** for Z1 and Z2 to be inequivalent (not inter-assignable, not mutually-extending).

> Note: I know [the spec](https://github.com/microsoft/TypeScript/blob/master/doc/spec-ARCHIVED.md#3.5) is archived, but it does say that B&A and A&B are not always equivalent. If that's still the case, then I'd expect Z1 and Z2 to be inequivalent in the code example above.

**Comment by mheiber** [comment]
I'm not blocked by this issue and suspect it is low-priority.

**Comment by DanielRosenwasser** [comment]
I believe the same issue applies regardless of intersection types, if you just have two otherwise identical types with re-ordered signatures. I'd say this is either a design limitation (we might want to fix it if there was a clear non-breaky technique to do this right) or just working as intended.

**Comment by mheiber** [comment]
Thanks for taking a look.

> "I believe the same issue applies regardless of intersection types"

I can confirm that the behavior is the same with call signatures. The playground shows the same behavior if Z1 and Z2 are defined as follows:

```ts
interface Z1 {
    (thing: string): string
    (thing: unknown): number
}

interface Z2 {
    (thing: unknown): number
    (thing: string): string
}
```

> "I'd say this is either a design limitation (we might want to fix it if there was a clear non-breaky technique to do this right) or just working as intended."

It's a soundness hole. I haven't been bitten by it, but I can see it causing real bugs. A change that would be backwards-compatible for code that isn't buggy would be to consider order in checkTypeRelatedTo in cases where order matters.

**Comment by RyanCavanaugh** [comment]
I don't find these type definitions to be coherent, so don't really think we can make true statements about them.

`Z2` (from either example)'s mere existence is a soundness hole absent any other behavior, since it fails to do the right thing in the presence of `string -> unknown` aliasing. This is just sort of the trade-off you have to accept with type constructors -- you can `&` any two arbitrary types and we'll try to piece together some meaning of what you tried to mean, which will frequently be right, but we don't have the ability to check those for coherence or directly prevent those conflicts.

**Comment by mheiber** [comment]
Sounds like this is working as designed–shall I close the issue?
