### ISSUE TITLE
﻿Incorrect suggestion: "Cannot find name 'global'. Did you mean 'global'?"

### ISSUE THREAD

**Issue by mkantor** [microsoft/TypeScript#42209]
# Bug Report

### 🔎 Search Terms

"declare global", "error suggestion", "cannot find name", "did you mean"

### 🕗 Version & Regression Information

This is the behavior in every version I tried (3.3.3-4.1.3 and 4.2.0-dev.20210104), and I reviewed the FAQ for entries about error messages.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4CgAmwDGAbAhlYOAc2wgCNdtE5MIA7AZ3hAC45c6BPOVE8ygHQggA)

### 💻 Code

```ts
export {}
declare global { const x: any }
global.x
```

### 🙁 Actual behavior

The error message is `Cannot find name 'global'. Did you mean 'global'? ts(2552)`. This is a legit error, but the suggestion is wrong.

### 🙂 Expected behavior

An error message that doesn't have an incorrect suggestion. Perhaps just `Cannot find name 'global'.` with no suggestion at all?

**Comment by ExE-Boss** [comment]
It should suggest using `globalThis` instead.

**Comment by mkantor** [comment]
@ExE-Boss I'm not sure about that, at least with code like my example above, because [`globalThis` also produces an error](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4CgAmwDGAbAhlYOAc2wgCNdtE5MIA7AZ3hAC45c6BPOVE8ygCoALAJYMAdCCA):

```typescript
export {}
declare global { const x: any }
globalThis.x
```

It's the same deal as what you pointed out in #39504. You need to [use `var` to attach `x` to `globalThis`](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4CgAmwDGAbAhlYOAc2wgCNdtE4A3fOEALjlwDsBPOVE8ygFQAWASwDOAOhBA).

A more universal fix could be "just write `x`", but it might not be worth adding a new type of suggestion for this presumably-rare situation.

**Comment by mkantor** [comment]
I started playing around with checker.ts. If the desired behavior is to have no suggestion, I think something like this could do the trick:

```diff
--- a/src/compiler/checker.ts
+++ b/src/compiler/checker.ts
@@ -2028,6 +2028,10 @@ namespace ts {
                         let suggestion: Symbol | undefined;
                         if (suggestedNameNotFoundMessage && suggestionCount < maximumSuggestionCount) {
                             suggestion = getSuggestedSymbolForNonexistentSymbol(originalLocation, name, meaning);
+                            // Avoid suggesting "global" if it refers to a global scope augmentation declaration.
+                            if (suggestion && isAmbientModule(suggestion.valueDeclaration) && isGlobalScopeAugmentation(suggestion.valueDeclaration)) {
+                                suggestion = undefined;
+                            }
                             if (suggestion) {
                                 const suggestionName = symbolToString(suggestion);
                                 const diagnostic = error(errorLocation, suggestedNameNotFoundMessage, diagnosticName(nameArg!), suggestionName);
```

However this is my first foray into the compiler internals and I don't have my bearings yet, so I'm not sure this is the best approach. This check could also happen inside `getSuggestedSymbolForNonexistentSymbol`, for example, or maybe there's a more general notion of "things that shouldn't be suggested for value positions" that should be captured somewhere.

Anyway, if this is vaguely on the right track let me know and I'll draft a pull request. If not, any guidance would be appreciated!
