### ISSUE TITLE
ImageData constructor signature is incorrect

### ISSUE THREAD

**Issue by jteplitz602** [Microsoft/TypeScript#4220]
lib.d.ts (and lib.webworkers.d.ts) define the ImageData constructor constructor as taking no arguments, but there should actually be two constructor signatures of the following form according to mdn:

```
new ImageData(array, width, height);
new ImageData(width, height);
```

**Comment by jteplitz602** [comment]
Submitted PR #4224 to fix this. It looks like the constructor is only defined in ES6 compatible browsers so I've only added the definition in lib.es6 and lib.webworkers

**Comment by mhegazy** [comment]
We can not accept a PR for this. sorry for the wrong tag. this file is auto generated. we have to update the script that generates this. We should post the sources of this script on another repo to allow the community to update it for similar issues. until then, @zhengbli will take care of this bug.
