### ISSUE TITLE
Error 2322 - Cannot init constant of generic type union of 2 optional index signatures

### ISSUE THREAD

**Issue by ndr47** [microsoft/TypeScript#42200]
**TypeScript Version:**  4.1.3

**Search Terms:**
Error 2322
Type is not assignable to type

**Issue**
Type `ElementShape` has 2 index signature and both of them can be undefined - they have "?" before the ":"

Why I cannot initialize a constant of generic type `ElementShape` with only the common keys?
Also `Partial<ElementShape<A>>` gave the same error.

**Code**
```ts
const element_def = {
	element1: {
		title: {}
	},
	element2: {
		price: {}
	}
} as const;

export type ElementName = 'element1' | 'element2';

export type CommonKeys = 'id' | 'active';

export type ElementShape<A extends ElementName> = 
   { [k in CommonKeys]?: string } &
   { [k in keyof typeof element_def[A]]?: number }


export function myFunc<A extends ElementName>(){

	let myconst:ElementShape<A> = {id: '', active: ''};
            // ~~~ Type '{ id: string; active: string; }' is not assignable to type 'ElementShape<A>'. Type '{ id: string; active: string; }' is not assignable to type '{ [k in keyof { readonly element1: { readonly title: {}; }; readonly element2: { readonly price: {}; }; }[A]]?: number | undefined; }'.

	let mypartial:Partial<ElementShape<A>> = {id: '', active: ''};
             // ~~~  Type '{ id: string; active: string; }' is not assignable to type 'Partial<ElementShape<A>>'.

	console.log(myconst, mypartial);

}
```

<details><summary><b>Output</b></summary>

```ts
const element_def = {
    element1: {
        title: {}
    },
    element2: {
        price: {}
    }
};
export function myFunc() {
    let myconst = { id: '', active: '' };
    let mypartial = { id: '', active: '' };
    console.log(myconst);
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgGzgWzmKB9AJnAZjAXhgG8AoASERTSgEYAuEi8qASyiUeIF8LuAaClVToATF2YAHAE6tgcLr3K9uMAIYQYoSFADcpUnAAekkNNhQAnpLgwAokhFQAcmtSEYAcmE1anmAA+Xj5invqGJmYW1rYAwiDIyOAA0nCWmkSerFj+QZ5qwGwAbnBhBsam5jBWNvaONADKABZqNgA8AILwRlBoWJoO1OiuqAB8HqQwU8QwANoA1jCsYDDxiSlpEAC6APyM0LJgAOYwqgBkk9Nzi8sw82kg+DVwj-D16Nh4sx1bu4xgAFdkAAjODSU4GCKVWC4AFgQqscAwZCWABicOAnW6vTA-TqQxcbjgowAFABKMgUJCwFHaaD0QZOZqtOCdcZEYjZRieTz8dQIkrczzcfRTMXisUAeklMAAfvKYAAVGJeGZcmAHZZHXT84oKDVQQ7a07+ViaMAgWAaCCsI5gNTApDVEDVFWeRmNFrtDqjTwAOiVbrVWH2hq1OoKetDRp13FN5st6ggNrtDqdUBdz1V1yWK3ulleM2kcDUWHACEsbwJDBIMGLpfLlbYHH1PFjOvrZbAFarTnEtc7jZgMjkrZFp1j31+exggJBYMCMDhOFwyzgWFj-oM5GpyOsanMrDUCHoAAUD2xj20Pehmd7RuySOqeXzI6xBV5haKJT+YNK5Qqga1J4wbRuGurvvqmrHJuSwJlaya2vajq2BmrrAeeh5XjeUB3qyPq+n6250iASB+ggIBHCStLgNAfIopIF5HggZLhNwQA)**

**Comment by RyanCavanaugh** [comment]
To allow this assignment, we'd have to be capable of some much higher-order reasoning about what all possible call-site instantiations of `A` are, and whether all of those would be valid sources for the given object. Outside of trivial cases where you don't really need generics in the first place, it's extremely rare for these assignments to actually be valid, so we don't really plan to make the type system "smarter" here.
