### ISSUE TITLE
Bash Executable Types

### ISSUE THREAD

**Issue by jamiebuilds** [microsoft/TypeScript#42212]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- Bash
- Shellscript

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A hot new way of constructing types at build time using the worlds most universally beloved language: bash.

Using the <code>bash\`...`</code> type you can now run entire bash programs inside of TypeScript.

```ts
type FileName = bash`
  find "$PWD"
`
```

The bash template type constructor would create a union of every stdout line of the embedded bash program.

## 📃 Motivating Example

**Before:** Allows all sorts of strings, who knows if this will work at runtime.

```ts
async function readFile(fileName: string) {
  // ...
}
```

**After:** Only real files can be read from the file system, now you can sleep at night

```ts
type FileName = bash`
  find "$PWD"
`

async function readFile(fileName: FileName) {
  // ...
}
```

## 💻 Use Cases

- Type-safe file operations
- Keeping your database in sync with your types
- Running Docker inside TS so your types are reproducible
- Fork bombing VSCode

**Comment by DanielRosenwasser** [comment]
_\*checks date\*_ I think you have confused 1/4/2021 and 4/1/2021 😅

**Comment by jamiebuilds** [comment]
There's another use case! A whole bunch of people need to be reminded to update their copyright year strings, now they can automate that reminder with `$ date`

```tsx
type Year = bash`
  date +"%Y"
`

type Copyright = `Copyright © ${Year} Company, Inc.`


function Footer() {
  let copyright: Copyright = "Copyright © 2020 Company, Inc." // ERROR!!!! Happy 2021!!!
  return <p>{copyright}</p>
}
```

**Comment by jamiebuilds** [comment]
People have pointed out some valid security concerns with third-party dependencies using their own bash types to steal private company code. My advice is add a new entrypoint to your program which turns networking features off, thereby thwarting any and all hacking attempts that steal data.


```tsx
// safe-entry.ts
type main = bash`
  nmcli networking off
  node ./unsafe-entry.ts
  nmcli networking on
`

**Comment by RyanCavanaugh** [comment]
This all makes sense and has no downsides, but I'm trying to figure out why bash instead of Powershell

**Comment by 00ff0000red** [comment]
Why use a specific scripting language that a user may or may not have, instead of, say, TypeScript?

This could be generalized into compile-time TS execution, we already sorta have it for const enums, why not just expand it to include everything?

**Comment by jamiebuilds** [comment]
> I'm trying to figure out why bash instead of Powershell

"bash" has fewer characters than "powershell" so users will save on file storage

**Comment by jamiebuilds** [comment]
> Why use a specific scripting language that a user may or may not have, instead of, say, TypeScript?

Users can call out to `ts-node` from bash. By allowing bash you're actually allowing any other language of your choice!

> this cannot possible be available everywhere anyways, ex: typescriptlang.org/play couldn't execute Bash :/

To be clear, I would expect TypeScript to ship its own copy of Bash for security reasons (who knows what a bad actor may do to `/bin/bash`)

**Comment by jamiebuilds** [comment]
> Just here the "user code" is bash

aha see, therefore it is superior

**Comment by MartinJohns** [comment]
I have to admit that I completely missed the joke.

**Comment by weswigham** [comment]
(But to the people in this thread saying "why not define the type computation in TypeScript": [I've very much toyed with the idea](https://github.com/weswigham/TypeScript/commit/4334efc99a84e12df7c5696a93bdc61f663b6ca3#diff-386c62d16ba6da82cac72ed27f36bcada993b42f58c7543e0e2ff6f907fe676d))
