### ISSUE TITLE
Leading space in generic parameter ignored by autoformat

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#4221]
Hi,

**Version**: VS2015/TS 1.5

In the code below,

```typescript
interface Foo<T> {
}

let foo: Foo<  { bar: string }> = undefined
```

Autoformat (Cntrl+K, Cntrl+D) does not remove the space between `Foo<` and `{ bar`. (It does remove any trailing spaces e.g. `bar: string } __ >`.)

**Comment by NoelAbrahams** [comment]
Here's a slightly different case, where extra *trailing* spaces are not removed:

```typescript
let publisher: {};

(<any>      publisher).subscribe(item => {

    console.log(item);
});
```

The spaces after `<any>` are not affected by autoformat, but any extra spaces before `<any>` are removed correctly.

**Comment by mhegazy** [comment]
//CC: @SaschaNaz, you might find this interesting.

**Comment by SaschaNaz** [comment]
Hmm, I'll take a look.

**Comment by mhegazy** [comment]
thanks @SaschaNaz!
