### ISSUE TITLE
Use of this in static method is wrongly typed in the context of inheritance

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#42226]
# Bug Report

### 🔎 Search Terms

static, inheritance

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because : i just start getting interested in it now.

### ⏯ Playground Link

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/MYGwhgzhAECyD2ATApiaBvAUNaEAuYeAlsNAGYBO8AtgBQCUG2O0w8AdhPCMgHQjwA5rQDkAWgnQinAu2BFCRDiPoBuZjjYzo1JKmgBeaO2QB3aHgAWRCA3UtWHLj35DREsdGTtE0eGQtkfBV7FgpkPABXCnYdPRBmAF9MZi18CkjgPHgKBiYHNO4+AWERSho4lBAQpMxkzFBIGABVCGQKBCqvAA88b0QYTv0sTSc8DKycvJGWCEiAB3a7DUdOItdS8upoSLaKStQanGT6tLwdvcNoVvahkF4tuyA)
      

### 💻 Code

```ts
class Model {
  static from() {
    console.log('--- instanciation');
    const model = new this();
    console.log('--- end of test');
    return model
  }

  constructor() {
    console.log('from model');
  }
}

class UserModel extends Model {
  constructor() {
    super();
    console.log('from user model');
  }
}

const user = UserModel.from();
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class Model {
    static from() {
        console.log('--- instanciation');
        const model = new this();
        console.log('--- end of test');
        return model;
    }
    constructor() {
        console.log('from model');
    }
}
class UserModel extends Model {
    constructor() {
        super();
        console.log('from user model');
    }
}
const user = UserModel.from();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

  
### 🙁 Actual behavior

typeof userModel → Model

### 🙂 Expected behavior

typeof userModel → UserModel

### 💡 Explanations

I can understand that this might be controversial ; the code is effectively located in Model, so the this() should infer that a Model is returned... although... the constructor of UserModel gets called (we can witness this from the console.log), so it's fair say that the inferred type of "model" is wrong.

Either no inheritance for static, or right typing of this should be fixed.

**Comment by ajafff** [comment]
TypeScript only treats `this` in instance members as generic. That means there's already such a mechanism, it currently just doesn't apply to static members.

If static `this` would be generic, you would probably no longer be able to invoke the constructor at all, because TypeScript cannot ensure that each subclass has a compatible constructor.
In your example above, if you add a required parameter to the constructor of `UserModel`, there is no compile error, but calling `UserModel.from()` might cause an error at runtime. With your proposed change, there would be a compile error that prevents you from writing this error-prone code in the first place.

> Either no inheritance for static

That's not going to happen since this is a runtime feature.

**Comment by RyanCavanaugh** [comment]
Duplicate #5863

**Comment by y-nk** [comment]
@ajafff Thanks for the further explanation. I wasn't hoping for "no inheritance for static" to be honest but just give an escape hatch, in case. I'm not really willing to let go of this, as it's used massively everywhere (not only me) :)

I do understand your point about the "this" being generic and the arguments of the constructor. It feels to me you're actually arguing in favor of my point, since it seems that not having a compile error would be a bad thing?

@RyanCavanaugh thanks for pointing to the duplicate, I'll look at the many workarounds in there hoping for a fast resolution of this meanwhile 🙏

**Comment by avin-kavish** [comment]
Just gonna mention, this is not about calling `new this()` alone. there are other uses for correctly getting the `this` type of the caller.
