### ISSUE TITLE
Error due to inconsistent code between Typescript nightly 4.2.0-dev.20210106 and @types/node@14.14.20

### ISSUE THREAD

**Issue by Luxcium** [microsoft/TypeScript#42229]
# Bug Report

 

### 🕗 Version & Regression Information
Version 4.2.0-dev.20210106 and Version 4.2.0-dev.20210105 

### 👨‍💻 actual `tsconfig.json`

[Link with relevant actual `tsconfig.json`](https://github.com/Luxcium/questrade-ts/blob/d2dfa1e2a40d20f80e101fc72caf862409f6de79/tsconfig.json#L1)

#### 🙁 

```shell
code --install-extension ms-vscode.vscode-typescript-next
fnm default 15
fnm use default
yarn add -D typescript@next @types/node@14.14.20
npm -g i typescript@next
yarn global add typescript@next
npm install -g npm@7
yarn global add yarn@latest
yarn global add npm@7
tsc --version
node --version
npm --version
tsc
```
#### 🙂 
```shell
code --uninstall-extension ms-vscode.vscode-typescript-next
fnm default 14
fnm use 14
yarn add typescript@latest @types/node@14.14.20
npm -g i typescript@latest
yarn global add typescript@latest
npm install -g npm@latest
yarn global add yarn@latest
yarn global add npm@latest
tsc --version
node --version
npm --version
tsc
```

### 🙁 Actual behavior

when using  `tsc --version; node --version`
tsc: Version 4.2.0-dev.20210106
node: **v14.15.4**

![Screenshot_20210106_095257](https://user-images.githubusercontent.com/42672814/103782077-0098bb00-5005-11eb-83db-72f97f197f66.png)

when using  `tsc --version; node --version`
tsc: Version 4.2.0-dev.20210106
node: **v15.5.1**
 
![Screenshot_20210106_095904](https://user-images.githubusercontent.com/42672814/103782916-1195fc00-5006-11eb-88bb-5ea92c974693.png)

#### on the left Expected behavior on the right Actual behavior:
 
![Screenshot_misc_backup_temporary-removed_scripts_ts-next sh - questrade-ts_20210106_103027](https://user-images.githubusercontent.com/42672814/103786274-41470300-500a-11eb-9da4-17870737e91a.png)

**Comment by Luxcium** [comment]
**the breadcrumbs on top show the location in my system**
![Screenshot_20210106_091301](https://user-images.githubusercontent.com/42672814/103786477-7d7a6380-500a-11eb-865d-93b7ced24ccd.png)

**Comment by Luxcium** [comment]
This one is line 30 in the related clone of the Definitelytyped node package...

![Screenshot_20210106_091137](https://user-images.githubusercontent.com/42672814/103786661-ac90d500-500a-11eb-87ee-2ef7d2583c11.png)

**Comment by andrewbranch** [comment]
The lib changes were reverted in https://github.com/microsoft/TypeScript/pull/42230; DefinitelyTyped CI is clean today. Thanks!
