### ISSUE TITLE
After updating to TS 4.1 inline require doesn't transpile to JS

### ISSUE THREAD

**Issue by gdavidkov** [microsoft/TypeScript#42227]
# Bug Report

We have a project using TS 3.7.4 and we decided to update it to 4.1. We have a file, which has a function, which requires inline another file. Before updating the TS this file was transpiled to JS but after the update, it is not transpiled.

### 🔎 Search Terms

inline require

### 🕗 Version & Regression Information

4.1

### 💻 Code
```ts
function readConfig() {
const cmds = require("./config/cmds").default;
return cmds.getCmdLine();
}
readConfig();
```

### Workaround
If I add the file in the tsconfig under include section, it gets transpiled

### 🙁 Actual behavior

It is not transpiled

### 🙂 Expected behavior

To be transpiled like in 3.7.4

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; expression-space `require` calls in `.ts` files were not supposed to expand the set of files.

**Comment by gdavidkov** [comment]
Thanks for the prompt reply.
What is appropriate fix? To add the file in the tsconfig file?

**Comment by RyanCavanaugh** [comment]
> add the file in the tsconfig file?

Yep, exactly

**Comment by gdavidkov** [comment]
Thanks!
