### ISSUE TITLE
A directory watcher option through tsc --watch

### ISSUE THREAD

**Issue by jamesxv7** [Microsoft/TypeScript#4222]
Following the discussion from issue #2375, Since Node.js does not provide a native directory watcher functionality, will be possible to add into the `--watch` options of TypeScript the functionality to enable a directory watcher. This in order to avoid re execute the compiler command each time a new file is added to the project (or folder)?

**Comment by mhegazy** [comment]
this should be working correctly today.

**Comment by jamesxv7** [comment]
Excellent! Testing ASAP!
