### ISSUE TITLE
Wrong branch of non-distributing conditional type inference near recursion limit for complex nested type

### ISSUE THREAD

**Issue by MMF2** [microsoft/TypeScript#42223]
# Bug Report
Schematic description of the bug: Two generic conditional types
`VeryComplexNestedTypeNearRecursionLimit<T> extends true ? 'yes' : 'no'`
and
`[VeryComplexNestedTypeNearRecursionLimit<T>] extends [true] ? 'yes' : 'no'`
evaluate, when instantiated with `T` := `6` (the specific instantiation that I have tested) in the first case to 'yes', in the second case to 'no'. The problem has nothing to do with distributive vs. non-distributive behavior, `VeryComplexNestedTypeNearRecursionLimit<6>` evaluates in my specific example to `true`, i.e. is not a union of values.

I suspect the problem is connected with touching the allowed recursion/nesting limit, as wrapping as singleton array increases the nesting level by one. In my actual code (see Playground link below) the schematic `VeryComplexNestedTypeNearRecursionLimit` is realized as type `IsNaturalNumber`. Unfortunately, I cannot give a shorter example as the problem seems to arise only for very complex types.

### 🔎 Search Terms

wrong branch, wrong branch recursive

### 🕗 Version & Regression Information
TypeScript 4.1.3, not found in FAQ, not solved by nightly version 4.2.0-dev-20210105.
I was unable to test this on prior versions because the construed types depend on 4.1 features.

### ⏯ Playground Link
[Playground link with relevant code](https://www.staging-typescript.org/play?ts=4.1.3#code/C4TwDgpgBAkgtmA9gZ2QSwEYBtoF4oB2EAbhAE4DcAUKJLAcQIZZoAmAKuBAAqNmNwIwclHxFSlKlID00qAGEAFhADGAa2RQAZojJRa0CAEcArmiY4CKiABooJZicbDNzAO6MQm4IntpgynrAZCbQutrMyBAAdFSyUADKEHCMBMBoKsgAXFAAFACiAIoAPACCNgBCAHxQgG-k+iEQAJRQgF-keaVQgO-kUBVNNFxQRWV21aJUUJNQANqlALr2AB7CBKya0xVzE1M7APx5GwsQyxCr6-NQ+8GhUDlakc3bO5N3D9QqiATIwPoQ30UARhywwAzFAAD5QAAsdhBNXw9ywUXen2+v3+hQATMCSvlFiosCZWBBimDITCoHC7FD4Q1Qiivj8XMAiiCccVrtBIYionYMIhEDhUrTOQy0cyilD2TzbFB+YKIMLRBEkRAxUy-izCgBWdkwBjMNicSC8fiCYRkOzicgixrq9FagBs7OmcytJBtypl1BkcnyFicLn0vnYUEA5ERQACqUDQWjliACdlDqVYUbsfEM-kCdLCehldjIf0gKnSpCwIDsCcCbjQUWD9AsRq4poEQnIsQMUFKADkACLFdh2SPwp4zdhHE5nGacrbPS4HSMTlZraeNWdzvY50cbnK5aaLpbL9Yy9cbjf7GXbs9THL6xscZt8VsWpr9Oe76bjw+nFfTE9X559j3A9jiPVdQlPa9N0vKD3wXJcf2PB5INgucLweADUJeBtDQfE0n3NchX0wm8cJYPCeAItsyCae1mR7XsgSGEoGOKfMVSiKo7BlW16SoD5GQdBjsWYso+zYh47E5LiOIgXi1X41ENW+Bi2VE1jOW4h4ZJ45VRUUwT6L7KV1PEzScxk6S9LtAzxU1BjdVM-t5SFAgpMaGS71w41KLNaj5Lo+y+2dJzim+Mg0AIABzOxwsiqLPINcifJbQiyAC2zlOABiAHZ2VYggTDgDByFi4J4sS+8Uqoi0MoEuyVL7AAOfLxIBOwAUq7zHz82rrL430hgDZw-nrAAa0NYygSbNAgLMRE5KBwnYqtyBrOsfDIpt8N69sBjobsAHl2AHEcdk-BCp2mGcr3Q1UrxyC7vyu-8oKuRoSNuLaKNS6jAu+I72CY4ZAY5DytNVOqlIdQGRJB46JMh9zQihwzNUBtT4ZOlzFQILrkp659PXwfT6qywGTKx4pCuKm07C8gmdqJ9L+oUsmYeOxyqYABnx7bfOZjLBoAJSEEwyC+bRwkYfQTDAHB9EGfxNEsKKAmiWA41SKA+H4EBFboXIawCHWCCgExVggLRIogVMaZKvREDjCAcEENJkBaWsoCi8xThjRlFVYKTlDiOROwcQkRu8Xx7b2zt2DlnB2EQbtnHF5huyKh2ymeldUhAV1aU6UDEKgABvKBVYCHJIq0EQABkoAAX3nRvbwQFB0GwNnoeZBP5YgZPU+AdOsEz2myCY-uk5TtP+DHrPyGKaZ8-TAgK1Njf87mWkoX+4Bp8H2eR-n8eHbhkpD6HueM8XshinzwurTvoXQ67ExFjQFg+H1gxNB0PQpRCylCwGPG+C8J4JHKtFZA+1oC9jQD7H4+BuYQigACNBmI0FkmhGg7UaDHRoJymgpqaCACc1BOzdk+AALXIIgBBSDlR4gJESEkjD-B2F5j6N+pQP5fzQD-A20AAGwGQJGAgaBPiHS0MPUeZ9yDZAUModQmg3DKACAtZQ3tfZm07IWMAhYojux1nkAgCZCCqD+MgPgX99aGMQJAGi5tJGfDfk7KAcUYF2HUeQCAGB9aKhUIoJacZ1EZBCQYoxpxgCuEIOAwgd8Nb+kcFHHWWAPBeHrHNTRQRGhLTzA8WI8QkgpDSBkJRuQgEQBAWAk+t9IHQKisgU6dQcz9HiLBdouRQyADCiTxTTwxQEAABEmhABQRNNHImgvaaIGRFaKUAol-Bic4KRZsPEywIAk2ONE4FiIkWsmRcjT53ygfM5prTcCjieiXK6XioooXnLkAABgAEjLuwJuzzc6aAAOTc1+Z9ecnIgW7jeR8r5PyoDguoQQOhZAGGIP8E3d5tcRCi2+F8oFm5cgYp+LclcvzAVYUAluElOxbziNcQQI54CFFkDOfFFpeKqhvhJa8VUxE4Lekyg6GAVLDmyLpacppyBgYlH5Qc6RQr6kQIdoymBxRfkgl+Wg352pfmWQ8qzfekrqW0tlfShVzSL7FD1YK45DT5WiqVQAWhVWqjVOltI6t5cyc10rLVyvIMa5AmMJUCs9cKxp5yWn3OdZDV17N3WBppTK+RIrQ2UwDVKuNXqjU2t+ZiVVkJfmlE1RDTiUbe6ag9Wm4N1rQ1cxTfq+NJyQ1MuKDjbWubs1qqhAW2Sr94hKFUBoKAvjcn6G0T7UgejBhLOMbE0xuRzE-CINYVAtjyxQAcU4loFs1mhPibKxJE9kDJOGkGdwnho5vxydmRay0ilv1KakdImRdxloNQm-drT6ichaN0vpe6HZDOGWbCZ7AciAagIAVEJ+idmfXWq1ijLnXK-AS9YOzHn7Gg+mxNjbwWfOeVUB6sldWxpffWh2Yq9REZg96sgLTebIzksWtG3x0MVsUaa5jhq74tO1FqlGDGGrAHY6+0j-qzUUYw2++1Eai0kxstG0tYmWPUeTaJ1NxHYPUeKNzaIVIu18ayoJkjijq0qdreJ0jpJogAhpIW+jMm+JyaYwpjj+6QrDAM+prjJCeO2ZzIR1TlH6XIDyqJdzVGWm2vwZCJqUmfOkxLY5-zZnFEtRC05oTcHbWkMhNxmzqN+OhcC2Q8jiXFPhay1ACLMW8v6bS4Z6jAJubFdM6V4oZC8HYK83R6rfLaseYBOKkzFqWttey2g+1nXdN2Z7oxgTvWwsAjY3NwLrX2uQntZZqEE3dJTb8815zpGAQiYK5x4otrMTRBy5N3zbr5Mlf24oqzTWhv3Y0zsqremet3fS-V4zx232-MYDmqAvyMCdu29dhzs2vt1bFa5mtz3vstOkrlj7Mbod9eC25pbJ2dloPDSjnbUheH8O-mQX+XA7ACQkNO2Zo6-ZbN3bjza2tdaeGEQOrM9hXYxPZwAInzrz02qZZlVxCSVeKw6IBvzp2bUXUB64axgD8L2FsbF108ZFawMYfisEQKNOdUAJCxl-ooZw2vNAy9XTVBuMZplm3uCWUxDPR6-rjoMCRauIBJbIMnQ+xRG5Idd5aaaULH4LHwIXcYOxQyB4rqLnIjcW77FDDkD3jA67e994nEk9c7DTGiAXwcm8d77zTxnxTWeB4DbL17iviA-eXZXuvNeW9m+bxbwsbrzIa+Z-r9n01Pe69+5wY31e7fi9QAClAeIABCOfN3viD5e5XnAIml-fZXySN7efO+o81Ovurm-lMH-U5v0kaCATRE25CLBa3Op57H9vSfrr4iQ5P1Rzfxn3-0rPyCDbMlXRn8dtp85A58Z9K5A5o5TFedCwVBxZ0A3FOlyVkCUDUC0Cph4gfBfBiQIAwBBdyAEUyAid4g+FP5SdydIA7BNdCw3YacR1dEd0XdccAkloiBFdldNBVd09oB0ArBoB-AoBdd9cLEjctATczdlYdEx034wBrc9Buxbd-YIhHdNltkkk9ka99QVB74FDA83tlQr5j5vtl4C9ohv874z9uwZJt4qhS8vhuCtDJ52RNCrB74dMaQX85A397C65HCB8fCIBHCLMrMZJ9DgDZ858IDGAVxmczYYDVB4Ct0sDBCIBcD8CyBCDiC5BSCBEhFOxREABZSKOwCOQMUaURWnBgzdT4bdZ3eeIPKAyQuASKNAOAIqdgxQrg9XXgrXAQoQ2BeIA3YJPtAdDRS9egsdK3XaPQRLTjJQh3H4AAKxMDRHqlrGnQ8TqOYAaI7HdwCKKIIGKFmP3ShR2XplOLvmVF5ijymFyGONIyhRgGBXyQ5SiBaEDxglJRrwOKONM04yHACKCJgCqDwzghgB4XiHgAHloO8G0UAFMiJaJxZwcIGo2ZZoyRFIbdaoyWTYtQk43IXgqKBWHZVwQsUxZAYsQRLAKAFQRgOsDxbEzQJ2N+EkpoQ9VJIMTaBmfmX6C0GMOMA3fkE2WQ6Y0k6ARk2ovE0jYpOQO9cpR9PIA4gAcXYHyGKAqEQTsASBSFARqA-UaC-SgHRLLg1KihbgRONO1OYCwCbjfjxAEAHmyDfmVNVOKByjsG4zaRBXiBdLVO1DsByj1NkmdMihVLVPK2v3QW5mpAISISDO9LkF9NJBjJvzjK9I+ioU+AADFGAv5PckzTSLiJ4tSdTqS9CX4bjJhWI-tzNTTPJsc30rTdSahA8QU0I8hzCJ4z86yoV88C9OyHYz8mysAZJTCw9HlNw2zrxXjHgwSkoeS5D95YUcy8zuDfSmJlzcykQ1zQzXTIzCFIR3SoBPSEQ3gF9gBNzVy65fSRJLztzrzdy-SUyoADyoBAy98AZsytz8zHy1I7yfyCAwzih9yiE7BMQu90YvyryIBfSTJ-ydzALXSQRnzXz3zTzVQlyoL7yYLHzHJ4KHzELwyUK0zCdId8KcLCKQpyKkyIyL9ozcFIRUKILPyCAVzsLfTgtqLHy3SPTmKLysKAKwyUsuLCKeK3y+KRKwyisoBJLXT-TxKvQzyyKBKEKwyGt2RZK1ScpohMQPSr8+Yfo5CJKVKCK1KBtNK3SdK8Er87AyEDLqppjjLWLvzVLVSFsNKTKKKgL7U7BbVrNvoHLBYPz+LnLoL1yRMLLtLb9jybKKs7L6Z5zDLHLgrNLHsZLPKkzkKGKoBoq0Lrt4gcByYMrHyAQ8LirRLrRg9uMKAQDFkEjqMkjsDUiwB7AMjdAsj34yDBEyd2dRF+Vvcche1VFRihBxjoBLdOwvYZY10RBsTJTGdON2TI4XA34T0slNoL0Fp8lr1VRdi6B+VuAEUnF0cwt4Mdgay4N2AWzJwYiPp2y9xEMbrkM74JycU49Tg1ZFBU99jIpWkW5Y8IDopq5-Y649ACjm5sUcVwbyyJ5IazwgIXDtDigCjrqwI0UwbuBCQxU4bUIgICjMaViMEYaHYcbkCgJpgWFCRiQBw7AUbLpfx0aoxqUAB1LMRAEwYAA4169A+GhcFmtmjmrm3syq7mnm2CO6KIUmsW0iO4-mgIdmzmyKIskm6W6WoCCy1NVm+WwW4oqAfGrGzqKFKc1Wk296UIKWk26c2SNlS21A9uJAVATAHALlW2s8e2zuJ22c127CKEj27uG26W92x2-2i20iX24O520moOruSO2CaOz2gO7CHlbwhHGHJiA6o68gE65bE8gjc87OzjESDOxxLOvbRHYoaK3OuLGbAu-dNSYu46sumHCu1bSkf-RSjC-OpujzEyBu0u1OjzFutbSLNukIju5ELugesLRyPusgWu8zaKiLbBWkZO+LYAeexREKWejejTSTce6bfjHeoLSlQ6kuue7u06ke743618keuyles8waIa-tQdMaqQv2SauJLY6knZJaso1wDJU9bJeaPJG4HaqIPa6AfqxTS5LscSC6jTK6uwUGbei+5bK6kEwjb3dO5Ab3YoKu2TNe6Bl7Iu3BmB640iohshl7eu6h4wrTaLferBxTXuuhurU7Bhh+zuyHYh77Geth9TIe48rhienhgRqjLe8R+lIR21BrPBERg+mrb3YLXh9hxeuR0bSEP-KzC-Re87MhMhcrChvOsR73FLVRwRsIkxqh73aSixqjfBtBa+w42+8hEE4K+x+ldSsRPB35BrTVJhjq5OOUcUqIVMOkmkpSfgSKH4CowYEU5mJkuMTsJnXwLQcWIdIxcqFQlQawMAYQVMBJtKKAmWQknAFkqUt3OgZ+22PB5OCoCAGp1gWkUcTxu+AcRABppp1G0uY2qYfYXHfDX5SKaI5oiOiAX5H0UxxTfrSlPBx0KfeIQ6AAaTnDtMKBpJUX7VmWMDMAsFOC1w8T-jsGGCL2HHsCPVGk2kWljDjGTFWCgAADUdYyTdnzBmAYlzymnsH2RvmYGFnn4J5Fm5AVmvmtnanFMRI-mXtigFnlQ95arQWpBOxoXvtMQOmunwXmnlRrk2mJ4MXGmsWqh6b1gbp2zBm4JhmtlWAxmY6Jn95UW6tMQAB9AbRl9TdFgFoPBRmq2qz+2SPkDmzxRQdmrAVMEqLcSHdlqjFlqFrF73Tl3eXl+IAg3QKSJWP5EZml2sOl1VDAIV5AEVkwMVkJoPIAA)

### 💻 Code
```ts
type CheckedNaturalNumber<ToBeChecked> = 
    IsNaturalNumber<ToBeChecked> extends true
      ? number 
      : 'inadmissible';

const testIsNaturalNumber11: IsNaturalNumber<6> = true; // OK      
// EQ checks the equivalence of types, EQ<T, U> evaluates to true iff T and V are equivalent
const testCheckedNaturalNumber1: EQ<CheckedNaturalNumber<6>, number> = true; // OK
const testCheckedNaturalNumber2: CheckedNaturalNumber<6> = 4; // OK


type CheckedNaturalNumber2<ToBeChecked> = 
    [IsNaturalNumber<ToBeChecked>] extends [true]
      ? number 
      : 'inadmissible';
const testCheckedNaturalNumber2_1: EQ<CheckedNaturalNumber2<6>, number> = false;  // type is false, but should be true
const testCheckedNaturalNumber2_2: CheckedNaturalNumber2<6> = 4;  // error, type is 'inadmissible' but should be number
```

### 🙁 Actual behavior
The instantiated type `CheckedNaturalNumber2<6>` (last line) evaluated to `'inadmissible'`. This is the wrong branch of the (non-distributive) conditional type `[IsNaturalNumber<ToBeChecked>] extends [true] ? ...` .

### 🙂 Expected behavior
`CheckedNaturalNumber2<6>` should evaluate to number, i.e. to the true-branch of the conditional type as in the parallel example of `CheckedNaturalNumber<6>`. The only difference between the types `CheckedNaturalNumber` and `CheckedNaturalNumber2` is that the condition in `CheckedNaturalNumber2` is wrapped as an array. That is, `IsNaturalNumber<ToBeChecked> extends true ? ... ` of `CheckedNaturalNumber` is replaced by `[IsNaturalNumber<ToBeChecked>] extends [true] ? ... ` within `CheckedNaturalNumber2`, what should leave the semantics untouched. This has nothing to do with distributive or non-distributive behavior as `IsNaturalNumber<ToBeChecked>` evaluates to `true`, i.e. it is no union of types.

**Comment by RyanCavanaugh** [comment]
There is a nesting limit of instantiations of the same generic definition at which point we'll bail out of the computation. TypeScript's type system is not designed for implementing Peano arithematic and we'd advise using a different typechecker if that's your goal 😉

**Comment by MMF2** [comment]
OK, implementing Peano arithmetic was only for playing around. However, I think a wrong type inference is a serious issue anyway. Wouldn't some "recursion too deep" error here the right thing instead?

**Comment by RyanCavanaugh** [comment]
During assignability checks, we need to sometimes need to bail out of a structural comparison without erroring. An example is
```ts
interface RedNode<T> {
  next: BlueNode<GreenNode<T>>;
  datum: T;
}

interface BlueNode<T>  {
  datum: T;
  next: GreenNode<RedNode<T>>;
}

interface GreenNode<T>  {
  next: RedNode<BlueNode<T>>;
  datum: T;
}

let k: RedNode<any> = { next: null as any, datum: null } as BlueNode<any>;
```

This assignment is correctly legal but a non-bailing structural analysis would need to reason about an infinitely-deep type of `RedNode<BlueNode<GreenNode<RedNode<BlueNode<GreenNode<.....`

**Comment by MMF2** [comment]
OK. I see. But still, wouldn't be some compiler warning about bailing out in such cases more adequate than silently risking some inconsistencies?

**Comment by RyanCavanaugh** [comment]
What would you do with such a warning in places where the expected result occurred?

**Comment by MMF2** [comment]
I would take notice that I have left safe ground and would either rework my type constructions or nodding with a "Thank you for the warning but I know what I am doing" feeling as in your case, probably.

**Comment by RyanCavanaugh** [comment]
>  nodding with a "Thank you for the warning but I know what I am doing" feeling as in your case,

Right, but there's no "nod" syntax

**Comment by MMF2** [comment]
Just some tooltip warning within an editor?
