### ISSUE TITLE
Pare down Node targets in `perf test this`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#42222]
[When we trigger our bot](https://github.com/microsoft/TypeScript/wiki/Triggering-TypeScript-Bot) with the `perf test this` command, we end up running on Node 8, 10, and 12.

In more "relaxed" scenarios, running on 3 targets may be fine; however, in a tight iteration loop for a given task, one might be just interested in running on Node 12.

The idea here is to provide 2 tasks:

* `perf test this` (perf tests on Node 12 only)
* `perf test this broadly` (perf tests across Node versions)

Alternatively, we could have

* `perf test this` (existing behavior - perf tests across Node versions)
* `perf test this faster` (perf tests on Node 12 only)

**Comment by weswigham** [comment]
Done. `perf test this faster` now caused the bot to only run the perf tests on node 12.

**Comment by DanielRosenwasser** [comment]
@ahejlsberg @RyanCavanaugh 👆🏻
