### ISSUE TITLE
NodeJS TypeScript - Run with build errors

### ISSUE THREAD

**Issue by anjdreas** [Microsoft/TypeScript#4223]
Cross-post from https://github.com/Microsoft/nodejstools/issues/312

One thing I found annoying is that the TypeScript NodeJS project refuses to run if there are TypeScript build errors. I understand that build errors are there to help you, while the JS is normally still output. This means I expected to be able to run despite build errors, but instead it just shows me the error list window on F5. I don't see any options in the project to enable the behavior I want.

I've fixed all build errors to be able to run, but it would be very convenient to run code that you know works, but simply suffers from TypeScript related errors.

**Comment by danquirk** [comment]
Toggling TypeScriptNoEmitOnError to false should do the trick, see https://github.com/Microsoft/TypeScript/issues/2848

**Comment by anjdreas** [comment]
Thanks, will give this a try.

**Comment by anjdreas** [comment]
Seemed to work nicely!
