### ISSUE TITLE
JSDoc '@this' not emitted in declaration file

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#42238]
# Bug Report

### 🔎 Search Terms

this jsdoc declaration

### 🕗 Version & Regression Information

- This behavior was present since `v3.7` when declaration emit for JS was introduced. Therefore it never worked.

### ⏯ Playground Link

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106&useJavaScript=true#code/PQKhAIAEBcAsEsDO4DejoCd4DsDmBfcEYAWACgBTADwAcB7DacAMwFdsBjaeO7F+DOgDCsAIYYA8swAqCRAAoAlKnLhwGCtFYY+cJADoOYjAEFo8gAyKA3OXxA)

### 💻 Code

```ts
/** @this {string} */
export function firstCharOfThis() {
  return this.charAt(0);
}
```      

### 🙁 Actual behavior

```ts
/** @this {string} */
export function firstCharOfThis(): string;
```

### 🙂 Expected behavior

```ts
/** @this {string} */
export function firstCharOfThis(this: string): string;
```

**Comment by Kingwl** [comment]
It's not only the 'this' tag but also all jsdoc.
The root cause is the conversion and emit behavior both of jsdoc in js and d.ts.

eg:
```js
export class A {
  /**
   * @private
   */
  a = 1
}
```

**Comment by ajafff** [comment]
@Kingwl JSDoc access modifiers seem to be emitted correctly in DTS
