### ISSUE TITLE
Types used in JSX.LibraryManagedAttributes have to accept both provided type parameters

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#42240]
# Bug Report

### 🔎 Search Terms

LibraryManagedAttributes

### 🕗 Version & Regression Information

This issue manifests itself at least since 3.9 but I strongly suspect that it has been here since `JSX.LibraryManagedAttributes` were introduced to TS. It also happens in the latest nightly build.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSX/React

### ⏯ Playground Link

1. [Extra prop directly provided in LibraryManagedAttributes](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/PQKhAIAECsGcA9x0SYAoAlgWwA4HsAnAF3ACUBTAQwGMSAzAvLcAcgKtpbTQBNzqANpXbhqeAHawSyAFzgiATxzk8dMhyIA6au0pFyAUQHks5cUTTjKp2DhrkkCcAG804d+HLx8xcFZt21A4AUgDKABoubh4xXj4kGObkBHT24EYmZiTOAL7RMe5xhAlJKWkZpuYAwkKwsC55BR5Fvon6ZUHpxpVEAIJERAQYAEYArvqwAAqMysQKDfkFLSXtqZ0VWVUAFhgCPOzi-YMj4w65i7HexeBtyWsOAJLmQ5IY1EdDYxMLTYVXraV7uAnsdXtQapQ6h8ThMADwAFQAfD9fst5EpHs9ErA3htzPUALxRX4FHgYABucmcolqsAActZyHIpC8AObgRq-TlNNGKZTgAAyIwIwgUAFlKFZWeQeNCvuRYLCqgAacCTZFEybgABkLlEdWZoPZ3I5aDyvH4QhEYkkJCqTBwcgAFI69YJIfTGQB+Q1sjkASnABOR4lGAgE3AA3EqHfrYASAERiASEGRbPBEHCJADWkYT4GAiKAA) (working)
2. [Extra prop indirectly provided in LibraryManagedAttributes](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/PQKhAIAECsGcA9x0SYAoAlgWwA4HsAnAF3ACUBTAQwGMSAzAvLcAcgKtpbTSIE8dy4AOoYiACwDCAZSkAFRjgA8sgHzgAvOFngAZOADe4arFgAucLCIEMAOwDm4AL7cAJuWoAbSuyN4blpARzPgE8OjIOIgA6anZKInIAUQ9yLHIbIjQbSjTYHBpBZAM0cFLwcnh8YnBs3PzqQQApKQANYrKO8srCElsEgjoC8GTU9JJ9Z06yiqrejPIBoZG0jIkvEwNJqa7Z8D6FwYbhlJWiAEEiKwwAIwBXBNh5PAFiXk2S7ZmevfnFo+WxhIxBgPC52DYLlc7gl3tsdt99n9BABJDLWfwYaiQ6zQ8iwWGfbrVRGHFFo2ywTFrSgmbE3e54xQAFTUEw+Uy+1RCZKuGOoAIy+M0+nZcPALgwADdzIZPDTYAA5HLkcyWdEOLZTTWdTkkbngAAyNwI3l4AFlKNk7OQXHTcbBFBIADRaNSaETiaRyBTKFSi5zONBuOU+ah+AISJg4cwACmjBiM60VyoA-KreRqAJQaNQ2W4eDzcADcjqjRhM6gARGGPIRTGI8EQcLYANZFyvgYAqIA) (not working)
3. [Unused C type passed to indirect version](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/PQKhAIAECsGcA9x0SYAoAlgWwA4HsAnAF3ACUBTAQwGMSAzAvLcAcgKtpbTSIE8dy4AOoYiACwDCAZSkAFRjgA8sgHzgAvOFngAZOADe4arFgAucLCIEMAOwDm4AL7cAJuWoAbSuyN4blpARzPgE8OjIOIgA6anZKInIAUQ9yLHIbIjQbSjTYHBpBZAM0cFLwcnh8YnBs3PzqQQApKQANYrKO8srCElsEgjoC8GTU9JJ9Z06yiqrejPIBoZG0jIkvEwNJqa7Z8D6FwYbhlJWiAEEiKwwAIwBXBNh5PAFiXk2S7ZmevfnFo+WxhIxBgPC52DYLlc7gl3tsdt99n9BABJDLWfwYaiQ6zQ8iwWGfbrVRGHFFo2ywTFrSgmbE3e54xQAFTUEw+Uy+1RCZKuGOoAIy+M0+nZcPALgwADdzIZPDTYAA5HLkcyWdEOLZTTWdTkkbngAAyNwI3l4AFlKNk7OQXHTcbBFBIADRaNSaETiaRyBTKFSi5zONBuOU+ah+AISJg4cwACmjBiM60VyoA-KreRqAJQaNQ2W4eDzcADcjqjRhM6gARGGPIRTGI8EQcLYANZFyvgYAqIA) (working again)

### 💻 Code

I've stumbled upon this because in Emotion (CSS-in-JS library) we provide support for a "pseudo" css prop - to do that we have a conditional type like:

```ts
type WithConditionalCSSProp<P> = 'className' extends keyof P
  ? string extends P['className' & keyof P]
    ? P & { css?: Interpolation<Theme> }
    : P
  : P
```
which we use in the `LibraryManagedAttributes` type. However, as this is React-based library we want to only extend what React types offers and not replace them entirely. So we've tried this:
```ts
type LibraryManagedAttributes<C, P> = WithConditionalCSSProp<
  ReactJSXLibraryManagedAttributes<C, P>
>
```
and for some weird reason this didn't work as expected. We've managed to work around by doing this:
```ts
type LibraryManagedAttributes<C, P> = ReactJSXLibraryManagedAttributes<C, P> & WithConditionalCSSProp<P>
```
I couldn't wrap my head around why the "composed" type doesn't work though - I've tested that TS is able to resolve it correctly! Even when it was used in the `LibraryManagedAttributes` type (I've assigned result to some extra prop and the produced types were *as expected*).

After more investigation I've discovered that we could make the version with types composition work by making `WithConditionalCSSProp` accept `C` - even if it has stayed unused in its implementation:
```ts
type WithConditionalCSSProp<C, P> = 'className' extends keyof P
  ? string extends P['className' & keyof P]
    ? P & { css?: Interpolation<Theme> }
    : P
  : P

type LibraryManagedAttributes<C, P> = WithConditionalCSSProp<
  C,
  ReactJSXLibraryManagedAttributes<C, P>
>
```

and this has lead me to narrow down the issue to even weirder scenarios - I've linked all of them in the "Playground Link" section.

### 🙁 Actual behavior

Types used by LibraryManagedAttributes that do not accept both provided type parameters are **ignored** which leads to obscure observable effects because one can think that their changes are reflected by the affected type is not used at all - it doesn't error or anything, it's just skipped over.

### 🙂 Expected behavior

Types used by `LibraryManagedAttributes` should be able to accept any amount of type arguments.

**Comment by RyanCavanaugh** [comment]
It sounds like this is a complaint about how the React .d.ts file is written, not a TypeScript bug. The React file is maintained on DefinitelyTyped and changes should be proposed at that repo; we don't ourselves author or control it.

**Comment by Andarist** [comment]
This is not complaint about React types at all - they work fine. Take a look at isolated playgrounds that I have provided. The behavior presented doesn't look as expected - I have also consulted  that with some TS advanced users from the community prior to reporting and all of them were like WAT

**Comment by RyanCavanaugh** [comment]
Yep, you're right, WAT indeed. Condensed inline version
```ts
/** @jsx jsx */
import React from 'react'

declare const jsx: typeof React.createElement
namespace jsx {
    export namespace JSX {
        export interface Element {}
        export interface ElementClass {}
        export interface ElementAttributesProperty {}
        export interface ElementChildrenAttribute {}
        export interface IntrinsicAttributes {}
        export interface IntrinsicClassAttributes<T> {}
        export type IntrinsicElements = {
            div: { className: string }
        }
        // Works
        export type LibraryManagedAttributes<C, P> = P & { css: string };

        // Equivalent to above, but fails
        // export type WithCSSProp<P> = P & { css: string }
        // export type LibraryManagedAttributes<C, P> = WithCSSProp<P>

    }
}

declare const Comp: (p: { className?: string }) => null

;<Comp css="color:hotpink;" />
```
