### ISSUE TITLE
Line 0:  Parsing error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by T-Jedsada** [microsoft/TypeScript#42242]
# Bug Report

Compile Error version 4.0

### 🔎 Search Terms

-

### 🕗 Version & Regression Information

i using vs code

typescript version 4.0 compile error when i change some file and save I got this error 

`Line 0:  Parsing error: Cannot read property 'map' of undefined`

### ⏯ Playground Link

-

### 💻 Code

```
Line 0:  Parsing error: Cannot read property 'map' of undefined
```

### 🙁 Actual behavior

change file and compile

### 🙂 Expected behavior

pass and run project smooth

**Comment by RyanCavanaugh** [comment]
Can you please show how to reproduce the problem?

**Comment by T-Jedsada** [comment]
@RyanCavanaugh downgrade typescript version to 3.8.3 it work now thank 🙏🏻
