### ISSUE TITLE
Recursive function parameter inferring produces unexpected unknown

### ISSUE THREAD

**Issue by phytonmk** [microsoft/TypeScript#42258]
# Bug Report

### 🔎 Search Terms

1. typescript recursive inferring produces unknown
2. typescript unknown in recursion
3. typescript generic recursions

### 🕗 Version & Regression Information

Tested on versions Nightly, 4.1.3, 4.0.5, 3.9.7, 3.8.3, 3.7.5, 3.6.3, 3.5.1, 3.3.3.

Similar behavior on all versions except of `3.3.3`. On `3.3.3` it returns `{}` instead of `unknown` (also seemed to be incorrectly).

### ⏯ Playground Link

[https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgp...](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAkgdgMwgJwGIFc4GMDKEA2CACgIbIkC2AgnHAPbAnACWdcAzlALxQA8AKgD4AFGQDmABgBcUAN4AoKFATMCAExkByAG4l86CJoDci5ZiwzhdAEYArCFmB5CM-gEpugqNrrM1JgF8PLi8SOBATeSw2dmAoZkQUDGxScmpaBiZWDhl4JDRzZ2IyShp6RhYY7ihhUwB9YDo8lHlgr1kAyIT85KxU0oyK7PZhBSUVdS1dfUMAGlMEc0sbe0citrlTJRWHJwIEADoJ-H8oAHozqB21-ZlMAGt6AHc4LaV3j8-Pi6gIAA9II4IBo5MpVCcpnoDJpZmZsMs7Lsiq4Nj4-FAAqYAvMgiYgA)

### 💻 Code

```ts
type InferFuncSelfParamAnnotations = <T>(arg0: {
  field: 'value';
  func: (objectSelf: T) => void;
}) => any;

const inferFuncParamAnnotations: InferFuncSelfParamAnnotations = (
  _toInfer
) => {};

inferFuncParamAnnotations({
  field: 'value',
  func: (objectSelf) => {
    objectSelf.field; // actual: objectSelf is unknown
                      // expected: { field: 'value', func: (objectSelf: T) => void }
  },
});
```

The code above is a minimal reproducible example of an issue.

### 🙁 Actual behavior

Typescript didn't infer typing of object, passed to `inferFuncParamAnnotations` and instead of adding type annotation of the passed object to `objectSelf`, it annotates `objectSelf` as `unknown`. Similar behavior when attempting to annotate `this` (and creating function using the `function` keyword).

### 🙂 Expected behavior

`objectSelf` type inferred as full object `{ field: 'value', func: (objectSelf: T) => void }`. 

Actually not sure if there is another way to make code above work in the expected way. But along with my knowledge of typescript the actual behavior of the code seems more like a bug than a code mistake.

**Comment by RyanCavanaugh** [comment]
I feel like this example has a typo; there's nothing here indicating that that should be the expected type of `objectSelf`. If you try to write a body for `inferFuncParamAnnotations` that invokes it, it becomes apparent that this is a contravariant-only inference site and there's nothing else legal to infer here. Did you mean to write a different example
