### ISSUE TITLE
factory.updateModifiers should be part of NodeFactory public api

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/TypeScript#42254]
# Suggestion

## 🔍 Search Terms

node, modifiers, update, updateModifiers

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently modifying the modifiers for different types of nodes is a bit complicated because each type of nodes has its own update method provided by the factory. The factory already has a [`updateModifiers`](https://github.com/microsoft/TypeScript/blob/v4.1.3/src/compiler/factory/nodeFactory.ts#L5778) method; it is just not public.

## 📃 Motivating Example

https://stackoverflow.com/questions/65075866/typescript-compiler-api-how-to-add-remove-modifier-from-statement

## 💻 Use Cases

Allow API user to update any node with modifiers using the same method

**Comment by rbuckton** [comment]
I've considered this. The only reason I haven't made it public is that I've been considering alternative approaches to updating common node properties like `name`, `parameters`, `body`, and `type`, without essentially duplicating `updateModifiers` for each case, so I did not feel the API endpoint was stable for public consumption as it was likely to change.
