### ISSUE TITLE
Playground won't load on Chromium (Brave)

### ISSUE THREAD

**Issue by grian32** [microsoft/TypeScript#42251]
# Bug Report

### 🔎 Search Terms

playground,
playground broken,
broken

### 🕗 Version & Regression Information

This bug started occuring a few days ago, not sure on the exact date

- This is a crash
Not sure how to classify as it is an unusual issue, just classified as crash.

### ⏯ Playground Link

N/A
### 💻 Code

N/A

### 🙁 Actual behavior

Stuck on "Downloading Typescript" as seen below 
![image](https://user-images.githubusercontent.com/54550982/103971553-981c1c00-5173-11eb-8f63-1c1133ff70d6.png)
This works on firefox
### 🙂 Expected behavior

The playground to load and to be able to use it normally.

**Comment by ajafff** [comment]
I'm using Chrome and had to disable my adblocker plugin for that domain to make it work again.

**Comment by jackHedaya** [comment]
@grian32 Perhaps try disabling your ad blocker and giving it another go. If that doesn't work, open the console and let us know what the error code and message are.

**Comment by orta** [comment]
Someone also reported this  in the discord, and it was their ad-blocker. Perhaps a list got too loose with azure CDN URLs? e.g. `https://typescript.azureedge.net/cdn/next/monaco/min/vs/editor/editor.main.nls.js` - that subdomain is only used by us

**Comment by RyanCavanaugh** [comment]
Tried in Brave:

![image](https://user-images.githubusercontent.com/6685088/104052801-1641e800-519f-11eb-8c51-209a96e612cd.png)

Maybe you can post the network/console diags?

**Comment by weswigham** [comment]
![image](https://user-images.githubusercontent.com/2932786/104054721-725a3b80-51a2-11eb-8b53-28c4db50ec4f.png)
I think ublock origin's block list includes the azureedge domain.

**Comment by akihironagai** [comment]
I've found a solution to the problem.

In uBlock Origin settings, open Filter lists and Purge all caches.

**Comment by weswigham** [comment]
Yeah, looks like forcing ublock to download an updated adblock list will fix the issue (definitely did for me). I suppose this is both not our fault, and fixed~

**Comment by grian32** [comment]
Thanks for the responses, doing what @akihironagai said and purging all caches seems to have to have fixed the problem, thanks! Sorry for the late response, I've been hit with some unexpected health problems lately and was out of comission.
