### ISSUE TITLE
Bug: when I set experimentalDecorators true. It was like didn't work.

### ISSUE THREAD

**Issue by iam-frankqiu** [microsoft/TypeScript#42255]
# Bug Report

### ⏯ Playground Link

https://codesandbox.io/s/snowy-violet-vdquv?file=/src/index.tsx

### 💻 Code

```
 "experimentalDecorators": true,
  "useDefineForClassFields": true,
```

### 🙁 Actual behavior

I have set the experimentalDecorators true. when I import `mobx`. It showed the err  `Support for the experimental syntax 'decorators-legacy' isn't currently enabled`. What I only want to do is use ts compiler to compile my code. I don't want to use babel. So I think is maybe a bug.

### 🙂 Expected behavior

Everything went well.

**Comment by MartinJohns** [comment]
Does this happen as well if you use TypeScript directly, and not Snowpack? It might be an issue with Snowpack.

**Comment by RyanCavanaugh** [comment]
That error message is issued by Babel, not TypeScript.

**Comment by iam-frankqiu** [comment]
> emitDecoratorMetadata

Sorry for my carelessness. It's a bug of Snowpack.
