### ISSUE TITLE
Type system allowing incorrect generic composition

### ISSUE THREAD

**Issue by DavidSouther** [Microsoft/TypeScript#4226]
In this code, I attempt to create a type-safe compose function where the output of `f` must match the input of `g`. Unfortunately, it allows `((A)=>A, (B)=>C)`. I would expect the type system to stop this.

```typescript
class A {}
class B {}
class C {}

function f(a: A): B {
	return new B;
}

function i(a: A): A {
	return a;
}

function g(b: B): C {
	return new C;
}

function compose<In, intermediate, Out>(
	f: (In)=>intermediate,
	g: (intermediate)=>Out
): (In)=>Out
{
	return (t)=>g(f(t));
}

compose(f, g);
compose<A, B, C>(f, g);

compose(i, g); // should fail, either i does not give B, _or_ g does not accept A
compose<A, A, C>(i, g); // should really fail - g does not accept A.
```

http://goo.gl/BkulA3

**Comment by DavidSouther** [comment]
This fails as I would expect in Java:

```java
public class GenericCompose {
  public static <In, Intermediate, Out> MyFunction<In, Out> compose(
      final MyFunction<In, Intermediate> f,
      final MyFunction<Intermediate, Out> g
  ){
    return new MyFunction<In, Out>(){
      @Override
      public Out execute(In i){
        return g.execute(f.execute(i));
      }
    };
  }

  public GenericCompose(){
    GenericCompose.compose(new F(), new G());
    GenericCompose.compose(new I(), new G());
    // The method compose(MyFunction<In,Intermediate>, MyFunction<Intermediate,Out>)
    // in the type GenericCompose is not applicable for the arguments (I, G)
  }
}

class A {}
class B {}
class C {}

abstract class MyFunction<In, Out>{
  public abstract Out execute(In in);
}

class F extends MyFunction<A, B>{
  @Override
  public B execute(A in) {
    return new B();
  }
}

class G extends MyFunction<B, C>{
  @Override
  public C execute(B in) {
    return new C();
  }
}

class I extends MyFunction<A, A>{
  @Override
  public A execute(A in) {
    return new A();
  }
}
```

**Comment by aleksey-bykov** [comment]
TypeScript is quite special in this regard and a bit unsound, so it lets you shoot yourself in your foot and laughs at you crying out in pain: https://github.com/Microsoft/TypeScript/issues/3038

**Comment by jeffreymorlan** [comment]
TypeScript actually would list errors on both of the incorrect `compose` calls, except that:
* `A` and `B` are assignable to each other due to being structurally identical
* `(X) => Y` doesn't mean what it looks like; it's the same as `(X: any) => Y` rather than `(paramName: X) => Y`.

**Comment by RyanCavanaugh** [comment]
Fixed example:
```ts
class A { a }
class B { b }
class C { c }

function f(a: A): B {
    return new B;
}

function i(a: A): A {
    return a;
}

function g(b: B): C {
    return new C;
}

function compose<In, intermediate, Out>(
    f: (x: In)=>intermediate,
    g: (x: intermediate)=>Out
): (x: In)=>Out
{
    return (t)=>g(f(t));
}

compose(f, g);
compose<A, B, C>(f, g);

compose(i, g); // should fail, either i does not give B, _or_ g does not accept A
compose<A, A, C>(i, g); // should really fail - g does not accept A.
```

Errors:
> ```
> a.ts(28,1): error TS2453: The type argument for type parameter 'intermediate' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
>   Type argument candidate 'A' is not a valid type argument because it is not a supertype of candidate 'B'.
>     Property 'a' is missing in type 'B'.
> a.ts(29,21): error TS2345: Argument of type '(b: B) => C' is not assignable to parameter of type '(x: A) => C'.
>   Types of parameters 'b' and 'x' are incompatible.
>     Type 'B' is not assignable to type 'A'.
>       Property 'a' is missing in type 'B'.

**Comment by DavidSouther** [comment]
Awesome, thank you @RyanCavanaugh!

@jeffreymorlan thank you for pointing out exactly how I was invalidating the rules. I should have seen the issue with A, B, and C being compatible types, but I don't think I'd have ever caught the distinction in the compose function argument types.

**Comment by RyanCavanaugh** [comment]
Compiling with `--noImplicitAny` is a good way to catch function type literals that lack parameter type annotations

**Comment by DavidSouther** [comment]
I'll keep that in mind! Thank you.
