### ISSUE TITLE
HTMLStyleElement is missing disabled property

### ISSUE THREAD

**Issue by xmatthias** [microsoft/TypeScript#42266]
# lib Update Request

## Configuration Check

4.1.2
es2020

## Missing / Incorrect Definition

Based on the [dom spec](https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-16428977), 
HTMLStyleElement should derrive from HTMLElement, and has the elements `disabled`, `media` and `type`.

The Type-definition for typescript is missing the "disabled" method, which is causing type-errors when trying to use this, and forces stupid workarounds.

https://github.com/microsoft/TypeScript/blob/eca8957430bf52cfdfa2bfe03c9431682da6a558/lib/lib.dom.d.ts#L8363-L8377

## Sample Code

``` typescript
const styles = document.getElementsByTagName('style') 
styles.forEach((style, index) => {
    if (bw[index].id === themeName) {
        bw[index].disabled = true;
    }
    else {
        bw[index].disabled = false;
    }
}
```

## Documentation Link

W3 DOM Specification [dom spec](https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-16428977)

**Comment by Andarist** [comment]
You might want to take a look here: https://github.com/microsoft/TypeScript-DOM-lib-generator to see why this doesn't get included by default and potentially use overrides to provide the improved typing. An example commit of the latter can be found [here](https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/1f7b275407e9a92ea37674b13451d36cf449ba90).

I encourage you to provide a PR for this :)

**Comment by AGMETEOR** [comment]
Would like to give this a try.

**Comment by huytd** [comment]
I'd like to work on this issue

**Comment by xmatthias** [comment]
I guess we can close this - as https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1301 addressed this, and it seems to be included in the latest typescript release.
