### ISSUE TITLE
Unable to compile, condition checking

### ISSUE THREAD

**Issue by mattjs** [microsoft/TypeScript#42269]
# Bug Report

```
const arr = ['A', 'B'];
if (arr[0] === 'A') {
  arr.shift();
  if (arr[0] === 'B') { // This line has an error
    arr.shift();
  }
}
```

### 🙁 Actual behavior

`This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.`

### 🙂 Expected behavior

Should not error since shift has changed the array and the first element can now be different

**Comment by MartinJohns** [comment]
Duplicate of #33443.

**Comment by mattjs** [comment]
Closing as this seems to be a dupe
