### ISSUE TITLE
Proposal: Expanded inference on type-guards that immediately return true.

### ISSUE THREAD

**Issue by poteat** [microsoft/TypeScript#42267]
# Suggestion

## 🔍 Search Terms
> inference type guard  true 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently, for a type-guard to affect type inference, that type guard must be called within the clause of an if-statement. It would be very useful for certain use-cases if the compiler was able to infer that _because_ the type guard _always_ returns true, the type assertion must be true for the code which executes after the type guard is executed.

This proposal would introduce no new syntax, but would instead be an advancement of some type-level inference regarding type guards. This would only effect type guards which provably always return `true`. I view the blast radius of this to be quite low, but it is at least theoretically possible for someone to be relying on the compiler not making this additional inference.

One of the most salient examples for where this is powerful is via self-modifying type guards on classes, which perform type assertions on `this`.

## 📃 Motivating Example

Imagine a `Set` class, whose types allow the Set to keep track of all items added to the set on a type-level. Such a type is constructed in my blog post **[Chained Tuple Types](https://mpote.at/post/programming/chained-tuple-types/)**, whereby we use chaining and tuple destructuring to simulate an object which operates on both the value and type levels.

Unfortunately, as it stands this is only possible using chaining syntax. However, if this proposal is implemented, one may be able to implement the following:

```ts
const set = new Set();

set.insert(4);
set.insert(8);

const result = set.value(); // Inferred as tuple type [4, 8]
```
From a high level, this allows users to 'build' complex types by using runtime-level syntax. Here is a small example of how the above `Set` may be defined:

```ts
export class Set<Elements extends number[] = []> {
  private elements: number[] = [];

  public insert<SpecificValue extends number>(
    x: SpecificValue
  ): this is Set<[...Elements, SpecificValue]> {
    this.elements.push(x);
    return true;
  }

  public value(): Elements {
    return this.elements as Elements;
  }
}
```

There is in actuality a slight issue with the above code, due to the fact that type guards actually assert intersections. Take me at my word when I say there is a somewhat straightforward way to use variadic tuple type destructuring and `unknown[]` to "smuggle" information across the resultant intersection boundary - this proposal does not require the behavior of type guards to be changed in any way, except for the additional inference as mentioned above.

## 💻 Use Cases

Any type information that is best modeled as a series of iterative actions, with associated runtime code, can be modeled using methods enabled by this proposal. For example, you could successively build a hashmap, inferring the compound type as you go:

```ts
const map = new HashMap();

map.insert("foobar", 42); // HashMap<{foobar: 42}>
map.insert("qux", "bar"); // HashMap<{foobar: 42, qux: "bar"}>

map.value(); // Inferred as {foobar: 42, qux: "bar"}
```
The above is a more-or-less perfect type representation of the action of building up a successive type out of small interactions, which is a constant difficulty to model within Typescript currently - one has to somehow model the initialization process using e.g. `Partial` currently, which is arguably less clear / elegant than the above syntax.

Additional use cases could be frameworks which update the type of their own interfaces according to newly initialized data, such as the registration of additional plugins.

Finally, to top it off - we can already implement this pattern, albeit in the limited cases of either chaining - whereby modification of `this` is avoided - or by `if` towers, which are redundant and messy. This proposal would greatly improve the syntax and readability of this pattern, and enable powerful self-modifying type semantics.

**Comment by MartinJohns** [comment]
Related: #41339

**Comment by poteat** [comment]
I was not aware of the `asserts this is` syntax - let me do some experimentation, if there is a way to achieve the same result with already existing mechanisms I'll close this issue. If not, I'll clarify where it fails. Thanks @MartinJohns !

**Comment by poteat** [comment]
Pursuant to the above, on `typescript@4.2.0-dev.20210108`, the following mechanism is possible that (more or less) implements the above, using the `asserts this` syntax. I'll leave this topic open for a while in case there's further discussion to be had, but it seems pretty clear cut that this is a functionality that 4.2 already provides.

I would be interested if anyone knows of a way to convince the inference to display `[4, 2]` rather than the intersection of unknown types. I'll update this thread if I figure it out the requisite type transformation.

```ts
export class Set<
  Elements extends unknown[] = unknown[],
  N extends unknown[] = []
> {
  private elements: number[] = [];

  public insert<SpecificValue extends number>(
    x: SpecificValue
  ): asserts this is Set<
    Elements & [...N, SpecificValue, ...unknown[]],
    [unknown, ...N]
  > {
    this.elements.push(x);
  }

  public value(): Elements {
    return this.elements as any;
  }
}

const set: Set = new Set();

set.insert(4);
set.insert(2);

// Inferred as: (unknown[] & [4, ...unknown[]] & [unknown, 2, ...unknown[]])
const result = set.value();
```

As briefly mentioned above, the additional complexity is due to the need to "smuggle" type information across the intersection operation that `asserts` naturally produces. Also would be interested if there's a better way to do that.

**Comment by MartinJohns** [comment]
Just be aware that you easily run into a serious soundness hole if you store a reference to your object or use conditional logic.

IMO following an approach with immutable data would be much safer and would not require hacks or workarounds like the one you propose.

**Comment by poteat** [comment]
Hmm, that might be so - although my general goal with complicated types like this is to serve as a contract with external code, not check the internal consistency / correctness of the internal implementation myself.

A much more correct form of the above implementation is below:

```ts
export class Set<Elements extends number[] = []> {
  private elements: number[] = [];

  public insert<SpecificValue extends number>(
    x: SpecificValue
  ): asserts this is Set<[...Elements, SpecificValue]> {
    this.elements.push(x);
  }

  public value(): this extends Set<infer E> ? E : never {
    return this.elements as any;
  }
}

const set: Set = new Set();

set.insert(4);
set.insert(8);

const result = set.value(); // [4, 8]
```

**Comment by poteat** [comment]
Closing this pursuant to the above determination that this use case is already supported by 4.2. Thanks @MartinJohns for pointing out the `asserts` syntax to me.

For anyone who happens to be interested, I've also developed a more comprehensive example and discussion of this use-case in my follow-up article **[Unchained Tuple Types](https://mpote.at/post/programming/unchained-tuple-types/)**.
