### ISSUE TITLE
Implement an interface via Object.assign in constructor

### ISSUE THREAD

**Issue by stephenh** [microsoft/TypeScript#42268]
# Suggestion

## 🔍 Search Terms

* inheritance
* Object.assign 
* mixins (kind of)

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'd like to be able to "implement an interface" by returning the right type from the constructor, and having that be "good enough" for the TypeScript compiler.

## 📃 Motivating Example

I'd like to be able to succinctly have a class implement an interface without using `extend`s (due to multiple inheritance problems) _or_ the boilerplate of re-typing out fields/accessors for every field in the interface.

I.e.:

```typescript
interface Foo {
  a: number;
  b: number;
}

class Bar implements Foo {
  constructor() {
    return Object.assign(this, { a: 1, b: 2 });
  }
}
```

Here I've made `Bar` implement `Foo` solely by "doing fancy things in the constructor", instead of manually typing out all of the fields & methods in the class declaration itself.

As far as I understand, this approach both:

* Already works at runtime, i.e. the Javascript would now have `const b = new Bar(); console.log(b.a)` "just work", and
* At compile-time, sees "easy" / feasible that TypeScript _could_ see that the constructor return value fully implements `Foo`, and so treat the `class Bar { ... }` declaration as valid.

## 💻 Use Cases

* I want to decorate/mixin behavior (via a class) into a data model without the repetitive writing/copy/pasting every field in the interface, i.e. `public a: number;`, `public b: number`, `this.a = a`, `this.b = b`

**Comment by MartinJohns** [comment]
Duplicate of #26792.

**Comment by stephenh** [comment]
Thank you! Closing.
