### ISSUE TITLE
forceConsistentCasingInFileNames does not work

### ISSUE THREAD

**Issue by cybermerlin** [microsoft/TypeScript#42270]
# Bug Report

```
 File name '/mnt/d/src/progress/styles/index.ts' differs from already included file name '/mnt/d/src/Progress/styles/index.ts' only in casing.
```
I found on this link the test:
https://github.com/microsoft/TypeScript/commit/4600d1bd961a1951310c5ed581eb78bc4cc303d1

Which helps to understand.
![image](https://user-images.githubusercontent.com/1460479/104109623-dedb5480-52e0-11eb-9eb5-f61954e75388.png)

Second question: why this test was deleted from the master branch?

### 🔎 Search Terms
Duplicate https://github.com/microsoft/TypeScript/issues/25460, but not resolved yet.

### 🕗 Version & Regression Information
tsc - 4.1.3
node - lts
npm - lts

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by RyanCavanaugh** [comment]
We'd need some way to reproduce the problem in order to investigate. This usually indicates a configuration error in your project

**Comment by cybermerlin** [comment]
for to reproduce - just copy here commit with here Test and execute gulp tests from runTests directory

**Comment by sheetalkamat** [comment]
That test case was replaced by baseline and it is working as intended `https://github.com/microsoft/TypeScript/blob/master/tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/when-renaming-file-with-different-casing.js`.

We would need exact repro.

**Comment by cybermerlin** [comment]
So, I figured out what situation this event occurs, but there is absolutely no time to make corrections to the typescript, I hope you will still want to fix it (because the test you replaced consistently gives an error, and the same is repeated in my project).

The bottom line is this - if in the dependencies of some of the packages from the package.json of my project there is some package with the same name as my class, BUT with different registers, then this causes a build error.

/package.json
```json
{
  dependencies: {
    "material-ui": "*",           <<< this component have components with the name "progress"
    "@widgets/progress": "file://./widgets/progress"
  }
}
```

/widgets/progress/Progress.tsx
/widgets/progress/index.tsx

/index.tsx
```ts
import progress from "@widgets/progress";

function Main() {
  return <Progress />;
}
export default Main;
```

excuse me, but I've no time today to reproduce in the isolated repo.
