### ISSUE TITLE
Language service doesn't handle missing root files

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#4227]
[As seen here](https://github.com/Microsoft/TypeScript/blob/4816bb51807e73b6431bbbe015e0649fb906c8b4/src/server/editorServices.ts#L933), the TS language service gives up on loading a project when it fails to find a _single_ file listed in that project - it would be useful if the service would continue to load the project but skip missing files. The existing behavior is acceptable for the compiler, but for editor experiences, even a partially correct `tsconfig.json` is usually better than an unloaded one.

**Comment by mhegazy** [comment]
Feel free to send a PR for it.

**Comment by RyanCavanaugh** [comment]
This seems to be fixed
