### ISSUE TITLE
add support @sealed()  @enumerable()  and such operation decorator to direct translate it 

### ISSUE THREAD

**Issue by John0King** [microsoft/TypeScript#42282]
## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

since ES2015 with class support ,  the default state for `get` `set` and method in class is not `enumerable: true`, and that cause a problem for `JSON.stringfy`  because  `get` property will not be serialized .

and those `operation decorator`  such like `@enumerable` `@sealed`  can be direct translate to normal javascript without 
decorator and  metadata support.

```ts
class Foo{
    @enumerable()
   get str(){
     return 'foo'
   }
}

// translate to 

class Foo{
    
   get str(){
     return 'foo'
   }
}
Object.getOwnPropertyDescriptor(Foo,'str')!.enumerable = true;

```

## 📃 Motivating Example

 the default state for `get` `set` in class is not `enumerable: true`

## 💻 Use Cases

in [uni-app](https://uniapp.dcloud.io/) for mini-program , it use `JSON.stringfy` to remap the object member , and the class `get` `set`  would not be serialized

**Comment by RyanCavanaugh** [comment]
Baking this in to TS as a built-in would be in direct conflict with the ongoing TC39 decorator proposals.

I believe you could write in user space today with experimental decorators, so there's no need for TS to do this itself.

**Comment by John0King** [comment]
@RyanCavanaugh   may I ask what is the stage of decorator proposals (and how many stage are their)?   and where I can find the detail ?

**Comment by RyanCavanaugh** [comment]
@John0King https://github.com/tc39/proposal-decorators
