### ISSUE TITLE
Tagged template literal inspired strings and values properties

### ISSUE THREAD

**Issue by mateja176** [microsoft/TypeScript#42289]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- template literal
- tagged template literal

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Special properties on template literal type instances:
1. A tuple of string types which represent the hard coded string
2. A tuple of expressions which are interpolated

The name of the first property may for example be `strings`. Whereas the name of the second property may be `values`.

## 📃 Motivating Example

Consider the example of the `Email` type

```ts
export type Email = `${string}@${string}.${string}`;
```

Next, consider a corresponding type guard `isEmail`:  

```ts
const isEmail = (maybeEmail: string): maybeEmail is Email => {
  return /^[a-zA-Z!#$%&'*+-/=?^_`{|}~.,]+@(([a-zA-Z0-9-]+)|([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)+))$/.test(
    maybeEmail,
  );
};
```

Now, that we are able to create an instance of email:

```ts
if (isEmail(emailInput)) {
  const email = emailInput;

  // if a string instance method is invoked i.e.  `split`
  const result = email.split('@');  
}

```

`result` is of type `string[]`. Whereas it's obvious that result is of type

```
[string, `${string}.${string}`]
````

Asking for the compiler to infer this is not the point of the feature request. Instead, in user land, a `split` function may be created which specializes in instances of `Email`. Such a function would be easy to implement with the existence of the hypothetical `strings` and `values` properties.

```ts
const splitEmail = (email: Email) => {
  return email.split('@') as [Email['values'][0], `${Email['values[1]']}${Email['strings'][1]}${Email['values'][2]}`]
}
```

This is closely inspired by [tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates).

## 💻 Use Cases

I was thinking of creating a library containing a number of common template literal types along with their type guards. However I don't see enough merit in the idea at the moment. This would most probably shift the tides.

**Comment by RyanCavanaugh** [comment]
> Whereas it's obvious that result is of type `[string, `${string}.${string}`]`

It isn't, though. `Email` allows values like
```ts
const x: Email = "a@b.c@d";
```
which returns a length-3 tuple when `split`.

We can't add `strings` and `values` to template literal types because they don't exist at runtime; if we allowed the type `Email['values']` then that allows the complementary value-space operation `x.values`, which definitely doesn't exist.

I'd really recommend against trying to use template literal types to represent operations that validate or manipulate *runtime* string values, because they don't behave according to RegEx semantics (e.g. no backtracking). The feature is very much designed for *compile-time* string manipulation (which is one of the reasons it uses template literal syntax, not RegEx syntax).

**Comment by mateja176** [comment]
@RyanCavanaugh Thanks for the feedback. Indeed, it is a rather naive implementation of the `Email` template literal type.

Moreover, I get the point:
> because they don't behave according to RegEx semantics (e.g. no backtracking)

If anyone else comes across this issue, I suppose that the standard approach of creating an `Email` class would be more suitable:

```ts
class Email extends String {
  private value: string;
  private constructor(maybeEmail: string) {
    super(maybeEmail);
  }
  static isEmail = (maybeEmail: string): boolean => {
    return /^[a-zA-Z!#$%&'*+-/=?^_`{|}~.,]+@(([a-zA-Z0-9-]+)|([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)+))$/.test(
      maybeEmail,
    );
  };

  static create = (maybeEmail: string): Email | null => {
    return Email.isEmail(maybeEmail) ? new Email(maybeEmail) : null;
  };

  valueOf() {
    return this.value;
  }
}

const emailInput = 'a@b.c';
const invalidEmailInput = 'a@b.c@d';

const email = Email.create(emailInput);
const invalidEmail = Email.create(invalidEmailInput);

console.log(`This is an email: ${email}`); // This is an email: a@b.c
console.log(invalidEmail);

```
