### ISSUE TITLE
exports from ".d.ts" files should be dropped as it was before 3.9

### ISSUE THREAD

**Issue by valera33** [microsoft/TypeScript#42294]
# Bug Report

exports from ".d.ts" files should be dropped as it was before 3.9
there wil be no javascript file out of ".d.ts" file, so there should not be a "require" from not exisiting file.

### 🔎 Search Terms

export retained
exports

### 🕗 Version & Regression Information

this is valid starting 3.9 version, it is documented here:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#export--is-always-retained

but it breaks a lot of code, because of exports from ".d.ts" files.

### ⏯ Playground Link

Playground link is not possible because multiple files needed.

### 💻 Code
index.ts:
```
// ... here other normal exports from ".ts" files
export * from './foo'
```
foo.d.ts:
```foo.d.ts
export interface Foo {}
```

### 🙁 Actual behavior

the compiled javascript contains `require('./foo')` but there is no such file.

### 🙂 Expected behavior

`require('./foo')` should be dropped from javascript file

**Comment by RyanCavanaugh** [comment]
This was an intentional change. You can use `export type` instead if you don't want the `require` in the emitted code.

**Comment by valera33** [comment]
> This was an intentional change. You can use `export type` instead if you don't want the `require` in the emitted code.

how exactly? what should I put instead of `export * from './foo';` and export all type definitions from it?
as far as I know `export type * from './foo';` is also not possible?
yes I can put for example `export {Foo} from './foo'` but the point is that we have a large project and this change breaks it...
