### ISSUE TITLE
`RegExpMatchArray` index 0 incorrectly possibly `undefined` when `noUncheckedIndexedAccess` is enabled

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#42296]
# Bug Report

### 🔎 Search Terms
RegExpMatchArray noUncheckedIndexedAccess

### 🕗 Version & Regression Information
4.2.0-dev.20210112

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about noUncheckedIndexedAccess

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.2.0-dev.20210112&ssl=1&ssc=1&pln=4&pc=2#code/MYewdgzgLgBAZiEMC8MBEaB0BbAhlYACwAoB6XUgSgFgAoASzhmISQEJlUwBXAG18owA3nRhiYoSLABGuAE4AuGNDn0wAcxTxEAbQAMAXToBfIA)

### 💻 Code

```ts
const foo = "".match(/a/)
if (foo !== null) {
    const bar: string = foo[0] //Type 'string | undefined' is not assignable to type 'string'
}
```

### 🙁 Actual behavior

index 0 is of type `string|undefined`
```ts
interface RegExpExecArray extends Array<string> {
    index: number;
    input: string;
}
```

### 🙂 Expected behavior
index 0 should be of type `string`, since `RegExpMatchArray` will always have at least one value in it as when no matches are found, it returns `null` instead. see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#return_value

therefore we can be confident that if a `RegExpMatchArray` is returned, it will always have a `length` of at least 1

should be something like this:
```ts
type RegExpMatchArray = [string] & string[] & {
    index?: number;
    input?: string;
}
```

**Comment by RyanCavanaugh** [comment]
I tried to fix this by adding `0: string` to `RegExpMatchArray`, but it induces a different error in existing code that seems problematic:
```ts
    (''.match(/ /) || []).map(s => s.toLowerCase());
```
We'd need a fix that didn't create new other problems, IMO

**Comment by utkarshkukreti** [comment]
@RyanCavanaugh sorry I don't understand the problem with adding `0: string` and that code snippet. Could you expand a bit?

**Comment by DetachHead** [comment]
@utkarshkukreti from what i understand the compiler fails to infer the type since the type of the value on the right (`[]`) isn't assignable to the type of the value on the left (`[string]`).

here's a minified example https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MDaByDBdGBDCGaAJwEswBzNbAHwFcwATAUznOcYFgAoH0SWACM8xFOiy4C6EuQq0GLNmA48+4aDGEAvMQiQB+femxqBMAI50AHmOGjDx1d20A6ALZ4ADgAo8KAHwwAN4AvgCUMAD0kQDuIMQA1hAANJrMwHh0EMzGMKSEfgBueAA2pIxEUGSU1DyWVu5evgHB4VGRjCDMEGAYsHGJaRlZOdR5hGAgsEWl5dJVsthAA

**Comment by utkarshkukreti** [comment]
@DetachHead thanks, I get it now. I hope someone figures out a solution, `noUncheckedIndexedAccess` is a game changer for type safety!

**Comment by GiancarlosIO** [comment]
is there a solution for this? or maybe it's the intended behavior?

**Comment by DetachHead** [comment]
#49682
