### ISSUE TITLE
Incorrect signature help position for non-trailing rest arguments

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#42292]
```ts
declare function doStuff(...args: [...names: string[], shouldCapitalize: boolean]): void;
doStuff("fee", "fai"/**/, "foh",  true);
```

Trigger signature help at `/**/`

**Current**: Signature help indicates that we're in the second argument - **shouldCapitalize**.
**Expected**: Signature help indicates that we're still in the first (rest) argument: **names**

**Comment by DanielRosenwasser** [comment]
@ahejlsberg do we have any sort of reusable logic for this one? I think there's a pretty rough UX/UI issue where the user hasn't written the full invocation out yet:

```ts
doStuff("fee", "fai" /*signatureHelpHere*/
```

**Comment by sandersn** [comment]
It's actually worse -- if you ask for signature help on `"foh"`, then there's no active argument at all, even though it should still be `names`.

**Comment by sandersn** [comment]
(I couldn't find any good way to reuse the checker logic -- its basic assumptions are not oriented toward highlighting the 'current' parameter, but toward finding assignability errors for all parameters.)
