### ISSUE TITLE
Provide URL to example source file(s) containing every possible correct ts grammatical construct, and list it in FAQ

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#42299]
# Suggestion
Such files can be re-used by writers of API-plugins for testing -- ensuring no correct constructs cause error or are omitted from consideration.

Probably the TS core group has such files in the development tree, and it is just a matter of disclosing their location.

(In particular, I'm looking for every possible type construct, and every possible declaration construct. But this suggestion is wider and more general than that)

## 🔍 Search Terms

 - typescript test files for compiler api 
 - testing a compiler api

## ✅ Viability Checklist

* [OK ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ OK] This wouldn't change the runtime behavior of existing JavaScript code
* [ OK] This could be implemented without emitting different JS based on the types of the expressions
* [ OK] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ OK] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

For writers of API plugins to test their plugins

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/tree/master/tests/cases/compiler
and
https://github.com/microsoft/TypeScript/tree/master/tests/cases/conformance

This is not a frequently-asked question.

**Comment by craigphicks** [comment]
Thank you!
