### ISSUE TITLE
Add a way to define temporary types when defining function argument types.

### ISSUE THREAD

**Issue by GTOsss** [microsoft/TypeScript#42305]
# Suggestion

## 🔍 Search Terms

typescript paramters function typeof paramenters

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐️ Suggestion

Add a way to define temporary types when defining function argument types. Or the ability to get the argument " as const"

## 📃 Motivating Example

Two solutions with the new syntax:

1)
```
// file from lib
type GetSomeValue = {
  <Obj extends object><K0 extends keyof Obj>(k0: K0): string;
  <Obj extends object><K0 extends keyof Obj, K1 extends keyof Obj[K0]>(k0: K0, k1: K1): string;
};

const getSomeValue = (...keys) => keys.join('.');

// usage
const obj = {
  a: 'a',
  b: { c: { d: '' } },
};

const result = getSomeValue<typeof obj>('b', 'c');
```

2)
```
// file from lib

type GetSomeValue = {
  <Obj extends object>(k0: keyof Obj): string;
  <Obj extends object>(k0: keyof Obj, k1: keyof Obj[typeof (k0 as const)]): string;
  // [typeof (k0 as const)] - get the actually passed value from the first argument
};
const createPath: GetSomeValue = (...keys) => keys.join('.');

// usage

const obj = {
  a: 'a',
  b: { c: { d: '' } },
};

const result = createPath<typeof obj>('a');
```
## 💻 Use Cases
 Now the workaround looks like this:
```
// file from lib
type GetSomeValue<Obj extends object> = {
  <K0 extends keyof Obj>(k0: K0): string;
  <K0 extends keyof Obj, K1 extends keyof Obj[K0]>(k0: K0, k1: K1): string;
};
const getSomeValue = (...keys) => keys.join('.');

// usage
const obj = {
  a: 'a',
  b: { c: { d: '' } },
};

const getSomeValueTyped = getSomeValue as GetSomeValue<typeof obj>; // this line of code creates an inconvenience

const result = getSomeValueTyped('b', 'c');
```

My suggestion, can help in cases where the arguments of a function must match the keys of the object, taking into account nesting. This would allow you to type such methods similar to `lodash.get`
And also, in situations where the type of subsequent arguments depends on the value of the previous ones.

**Comment by RyanCavanaugh** [comment]
I can't tell what this is supposed to be doing. What type is `result` intended to have in these examples?

**Comment by GTOsss** [comment]
@RyanCavanaugh In the most recent code example, on the last line, we get a function getSomeValueTyped that understands the sequence of arguments that correspond to the keys of the object given the nesting.

**Comment by RyanCavanaugh** [comment]
I'm still not sure I understand what you mean this to do.

Can you show some examples of *legal* calls, *illegal* calls, and resulting output types from a function that used this new syntax idea?

**Comment by GTOsss** [comment]
@RyanCavanaugh  Here is an example of a workaround at the moment. I suggest 2 solutions that would allow you to achieve this result with a better code.
https://codesandbox.io/s/typescript-playground-export-forked-3dhs5?file=/index.ts

**Comment by RyanCavanaugh** [comment]
This is already possible
```ts
declare function getSomeValueTyped<O, K1 extends keyof O>(obj: O, k1: K1): O[K1];
declare function getSomeValueTyped<O, K1 extends keyof O, K2 extends keyof O[K1]>(obj: O, k1: K1, k2: K2): O[K1][K2];
declare function getSomeValueTyped<O, K1 extends keyof O, K2 extends keyof O[K1], K3 extends keyof O[K1][K2]>(obj: O, k1: K1, k2: K2, k3: K3): O[K1][K2][K3];

// the method understands nested keys and result
const result = getSomeValueTyped(obj, "a", "b", "c");

const result2 = getSomeValueTyped(obj, "a", "b", "absf"); // error!
```

**Comment by GTOsss** [comment]
@RyanCavanaugh 
Yes, your method is working for this case. But what if you need to take the object type into a generic:
https://codesandbox.io/s/typescript-playground-export-forked-d5cx8?file=/index.ts

**Comment by RyanCavanaugh** [comment]
I feel like we're having an XY problem here.

`getPathTyped` can't be implemented. For it to work, it would have to start with a function call that accepts `obj` somehow, and then that can produce a function that yields that kind of behavior, and you can already use nested generics to accomplish that scenario.

**Comment by GTOsss** [comment]
You may be right about the XY problem. In fact, I encountered a problem that I described in the last code example, it is a pity that the typescript can not solve this problem.

I am the developer of a library that allows you to dynamically manipulate an object. But I want to limit manipulation through generics. The last code example with getPath is my current problem:
The user can create a type:
```
type Values = {a: {b: string }};
```

Next, it calls a method that will create a path for the future object: 
```
getPath<Values>('a', 'b');  // ['a', 'b']
```
At the same time, I want to prevent incorrect input of paths:

The object itself is created something like this (simplified code):
```
const basePath = getPath<Values>('a', 'b');
const obj = createObj<Values>(basePath);  //
```

I need the ability to prevent incorrect path input:
```
getPath('a', 'b'); / / ok
getPath('a', 'c'); / / error
```

It seems that I am close to a solution without a workaround that brings inconvenience.

**Comment by RyanCavanaugh** [comment]
If I'm interpreting this correctly, you have a system where an "object path" is a sort of first-class value that you can pass around, and you want to constrain it during construction? That makes sense but it might be more ergonomic to let those go unconstrained and enforce that they match their target upon later use.

Alternatively, a problem you're having here is that specifying one type argument results in the remaining type arguments going to their defaults rather than going through inference, which is sort of an unfortunate design corner we painted ourselves into. See #26242
