### ISSUE TITLE
Using recursive type aliases gives circular reference error

### ISSUE THREAD

**Issue by saihaj** [microsoft/TypeScript#42308]
# Bug Report
As per [TypeScript v3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#more-recursive-type-aliases) recursive type aliases are valid to use. Trying to migrate from Flow to TypeScript and having issues. This is the [flow equivalent](https://github.com/graphql/graphql-js/blob/661ff1a6b591eea1e7a7e7c9e6b8b2dcfabf3bd7/src/utilities/getIntrospectionQuery.js#L250-L255) and this is what I currently [have for TypeScript](https://github.com/graphql/graphql-js/pull/2828/commits/bbb08daa66255f76150f10dba382726dce42b103) but it is not an ideal solution. If I remove the generic types it works but that is also not an elegant way of doing this. I asked this on [StackOverflow](https://stackoverflow.com/questions/65693844/using-recursive-type-aliases-gives-circular-reference-error).

Is there a limit to how recursive types work?

### 🔎 Search Terms
* TypeScript Type alias circularly references itself

### 🕗 Version & Regression Information
- Tested on v4.0.2, v4.1.2 and v4.1.3

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCSA7GUIGcUDGMAlhBgCrKoC8cA3gFBxxTACGAJmQDaJwDWxDBwBccAOQB5AEIApAKIBhcuIDcDAL7qGoSLARV0WHPmBFSGADLFcMSigBKwAGYAeJnHJxQMYMNxG2HiEJGT2wE7OcLSYQabmYVSRDAB80fQerJw8fILCYuKWaADKKurMWVwYvHAQzuFi5OpaDDrg0PBIKIEmIRYAcmT9AK7c3OGR7sxePn4cAbG9ZqEUSS7pi8HLFhMuqemMFexVNXmiEv2S-QD6-QCqlpZqmcc5tfVUjc3auh0G3Zt4itdlFqB4AD49LYJDD9NgAW2AHBBEKhQIs1lsKOYkMBfSGQ1G4zWbg8zGYeO2QwRSJBcFxxmhK0xdhJZLgKR+7X0XVQlJhcMRyJJU083hAvn8aPxq26MUZ6MSKH2tEOLFe1VyQnO5AA2uIzuIALrfIA)

### 💻 Code

```ts
export type IntrospectionType = {
  readonly kind: 'OBJECT';
};

export type IntrospectionListTypeRef<
  T extends IntrospectionTypeRef = IntrospectionTypeRef
> = {
  readonly kind: 'LIST';
  readonly ofType: T;
};

export type IntrospectionNonNullTypeRef<
  T extends IntrospectionTypeRef = IntrospectionTypeRef
> = {
  readonly kind: 'NON_NULL';
  readonly ofType: T;
};

export type IntrospectionTypeRef =
  | IntrospectionNamedTypeRef
  | IntrospectionListTypeRef
  | IntrospectionNonNullTypeRef<
      IntrospectionNamedTypeRef | IntrospectionListTypeRef
    >;

export type IntrospectionNamedTypeRef<
  T extends IntrospectionType = IntrospectionType
> = {
  readonly kind: T['kind'];
};
```

### 🙁 Actual behavior
Type alias 'IntrospectionTypeRef' circularly references itself.

### 🙂 Expected behavior
Flow equivalent works perfectly and this looks right so should work or maybe I am doing something wrong 🤷🏼‍♂️

**Comment by RyanCavanaugh** [comment]
Recursive type aliases are permitted when they don't create problems, and this creates a problem. One of the problematic recursivenesses is immediate self-instantiation, e.g.
```ts
type Box<T> = { content: T };
type SomeBox = Box<SomeBox>;
```
Basically, you can't create a circularity that results in an instantiation chain of `U<T<T<T<T<T<T<T<T<T<T...[infinity]`.

Interfaces have slightly different rules because they have more concrete restrictions about what kinds of types they can produce (specifically, they're always object types which can be entirely deferred), so you can convert the prior type aliases to interfaces and this will work OK.
