### ISSUE TITLE
The RegExp type definitions incorrectly state that matched groups are always strings, not undefined

### ISSUE THREAD

**Issue by murgatroid99** [microsoft/TypeScript#42307]
# Bug Report

The type definitions for `RegExp#exec`, `RegExp#[Symbol.match]` and `RegExp#[Symbol.exec]`, and the corresponding type definitions for `String#match` and `String#split`, incorrectly state that the output is an array of `string`, which is incorrect because groups that are not found within a pattern that is matched will output `undefined`, not a string.

Specifically, the problematic type definitions are [`RegExpMatchArray` and `RegExpExecArray`](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L909-L917) and [`RegExp#[Symbol.split]`](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2015.symbol.wellknown.d.ts#L226).

### 🔎 Search Terms

RegExp, undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `RegExp`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210112&ssl=1&ssc=1&pln=3&pc=38#code/MYewdgziA2CmB00QHMAUByAhu+BbTALsABaoD0qmAlAD6oBGVZVVAsAFCiQwJJoXU6jMvFgAPWMFQAietJYcuUOIhQYxmMfTE4IAB2gBLAuUq0GTFkA)

### 💻 Code

The following code demonstrates the undefined outputs for the three mentioned functions

```ts
console.log('a'.match(/(a)|(b)/))
console.log(/(a)|(b)/.exec("b"))
console.log('xaxbx'.split(/(a)|(b)/))
```

### 🙁 Actual behavior

Each of the listed functions outputs `undefined` in at least one position in the array, but the listed TypeScript type is `string[]`.

### 🙂 Expected behavior

The TypeScript type should indicate that `undefined` values are possible.

**Comment by RyanCavanaugh** [comment]
Duplicate #17053

**Comment by sindresorhus** [comment]
Please reconsider this. This can easily lead to runtime crashes. If users know it cannot be `undefined`, they can just "force-unwrap" with `!`. Alternatively, add a pedantic flag.

**Comment by RyanCavanaugh** [comment]
> Alternatively, add a pedantic flag.

`--noUncheckedIndexedAccess`

**Comment by NilsIrl** [comment]
> > Alternatively, add a pedantic flag.
> 
> `--noUncheckedIndexedAccess`

This does not trigger any warnings. Because `RegExpExecArray` extends `Array<string>` the index is not undefined.
