### ISSUE TITLE
webkitSpeechRecognition does not come up in the intellisense

### ISSUE THREAD

**Issue by max-programming** [microsoft/TypeScript#42311]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.2.0-dev.20210112

**Search Terms**
- dom
- d.ts

---

- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Add the support for `webkitSpeechRecognition` class just like `SpeechRecognition`.
2. Also when using TypeScript, it throws an error about not finding `webkitSpeechRecognition`
![image](https://user-images.githubusercontent.com/51731966/104404902-c342a900-5581-11eb-85d6-534264f3a0f0.png)
![image](https://user-images.githubusercontent.com/51731966/104404917-ca69b700-5581-11eb-8a09-e2c349dfd2a3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by MartinJohns** [comment]
I think vendor specific API are not generally added.

**Comment by max-programming** [comment]
> I think vendor specific API are not generally added.

Do you mean the ones in the `window` object or the ones built in to the browser?

**Comment by RyanCavanaugh** [comment]
Any vendor-specific API
