### ISSUE TITLE
Narrowing of conditional types

### ISSUE THREAD

**Issue by jonhue** [microsoft/TypeScript#42318]
# Bug Report

### 🔎 Search Terms

conditional type, narrow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _conditional types_ and _narrowing_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210113#code/MYewdgzgLgBAFgQzAEwDYFMDKUBOBLMAcxgF4YAKANwC4Zp8iBKUgPhkoChRJZEUMAcgFcAtgCN0OUhRowwoiTmYk2nLuGjwkaLLgKEAMniiSEqaVVoByevqvLVHdTxgAzMAEZpAHgAqMdAAPExQIOj0iGAAfOQVJFnIOGHYzIXRaXwAaJJhkdAAHdBQi4ABPDIDgouQw20iAfhgbCMIrGGt5cUkrbIcYAG8cvFcKPMLisDLSEjJmhlbmQeTkvh1seaMTHDNyMeqS0uYAeiOAnBwQHDD0SiKYKDgQIUI4GAB3dDpHoVRkGABrMAgN73OB4MLgpp1VoUABUjByK20GHW+ioqXQzGW2JxJzOFyuAVuYFBTxe70+EG+vwBQJBD0hkOhOQAvjlVoI4jh0ag0licQLknjJATrsTSc9Xh8vk8aYDgaDGWFOooOGznJp3AAmHz+IIhGpQlptGJWFXdBI5SgYir66phOZ2GCNaHtWJdHDZZJ7CZlDK9VgDIYjXYFfaTUrTWbQ+xB7Ec3QbYymVCh8Z5CPHU4iy5iu4PMlSynUv7y+lgiEOmOIrT8RNo628zGCgXC865on577k6VU2WlumKyvheas9nI9DCD08vktwVt0WdkkFyUUmU-AcKhnD804NVAA)

### 💻 Code

```ts
const handleString = (v: string) => v
const handleNumber = (v: number) => v

const handleStringLiteral = (v: 'string') => v

const fn1 = <T extends string | number>(
  value: T,
  dependency: T extends string ? 'string' : 'number',
) => {
  if (dependency === 'string') {
    handleStringLiteral(dependency) // errors even though we should know this is 'string' (*)
    handleString(value)             // errors even though we should know this is string
  }
  handleNumber(value)               // errors even though we should know this is number
}

const fn2 = <T extends 'string' | 'number'>(
  value: T extends 'string' ? string : number,
  dependency: T,
) => {
  if (dependency === 'string') {
    handleStringLiteral(dependency) // errors even though we should know this is 'string'
    handleString(value)             // errors even though we should know this is string
  }
  handleNumber(value)               // errors even though we should know this is number
}
```

### 🙁 Actual behavior

In both `fn1` and `fn2` the type of `value` is not narrowed based on the type of `dependency`.

### 🙂 Expected behavior

The above code should not raise any type errors.

I recognize that some cases, namely those where a `T` extending a union is not narrowed, are already covered by #13995.
However, `(*)` is not narrowed even though its type does not extend a union. Instead, it is a conditional type that depends on `T`.
My presumption is, that we'll only be able to fix this once #13995 was addressed. I wasn't able to find this scenario in any other issue though, but think improving this behavior would be worthwhile too.

**Comment by RyanCavanaugh** [comment]
A legal call to `fn1` is
```ts
fn1<string | number>(42, "string");
```
which would produce an unsoundness at `handleString(42)`.

See also #27808

**Comment by jonhue** [comment]
good spot @RyanCavanaugh! 

Intuitively I thought that when we have a type argument for `T` like `string | number` and one argument `"this is a string"` for a value of type `T` we would be able to narrow `T` to `string`. Just out of curiosity, what is the reason why we cannot? 🙂 

It does seem as though my scenario only makes sense with the `oneof` extends type parameters you referred to 👍

**Comment by RyanCavanaugh** [comment]
> Intuitively I thought that when we have a type argument for T like string | number and one argument "this is a string" for a value of type T we would be able to narrow T to string. Just out of curiosity, what is the reason why we cannot?

For the same reason as the provided example: having one `T` value of type `string` doesn't mean that `T` isn't instantiated with e.g. `string | number` (thus making another `T` value be legally `number`)
