### ISSUE TITLE
Leftover Issues Brainstorm

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#4231]
Here are some things I haven't gotten around to handling this summer. Make of them what you will.
Thanks for all the mentorship and support! This summer has been great :).

- [ ] make compile-time constants display their value in the editor
- [ ] add directory-structure support for fourslash
- [ ] move tests/cases/fourslash/fourslash.ts outside that directory.
- [ ] fix indentation in JSDocComments/multi-line comments in vs.
- [ ] Fix (fully) our newline handling.
- [ ] Insert doc comment template has a right-click option in vs and/or a hotkey when carat is over a function declaration
- [ ] support more ts objects for doc comment templating (eg: methods, constructors, etc)
- [ ] automatically close multi-line comments in vs.
- [ ] JSDoc find/replace includes jsdoc comments
- [ ] highlighting a parameter in a call tells you about both what the value in the position is, and what it is supposed to be from the function declaration (including the doc comments).

More ambitious, possibly outside the direction of TS:
- [ ] implement facilities for generic gen-kill form-based flow analysis.
* allows unreachable code analysis, better type guards, etc.
- [ ] get intellisense to work with filling type-holes, eg:
```ts
function foo(x: T) { ... }

// completion should offer/prioritize the T's in scope, 
// including those outside the top-level, eg: 'x.y.z'
foo(^); 
```
- [ ] emit JSDoc comments in the compiled code, either by inserting new templates
or augmenting existing ones.
- [ ] find a way to migrate JSDoc types from JSDoc syntax into actual typescript (eg: optional, structs, typedefs, etc)
** strips the JSDoc and makes the .ts file more readable
** enirches the type information we have
** makes migrating from js to ts easier
- [ ] Add new-able as a constraint for generics, a la c#
- [ ] search within the current scope: get search results informed by what's visible in the current scope
(a sort of intersection of the search results and the completion provider)

**Comment by weswigham** [comment]
> * Add new-able as a constraint for generics, a la c#

So in theory this is already possible by requiring the presence of a `.constructor` property whose value is a function which yields void and takes no parameters. A `new` constraint would then be the alias of this interface:

```ts
interface Constructable {
  constructor: Function
}
```

used as 
```ts
interface ConstructableAddable {
	constructor: () => void;
	add(ConstructableAddable): ConstructableAddable;
}
var a = <T extends ConstructableAddable>(obj: T): ConstructableAddable => {
    return obj.add(new obj.constructor());
}
```
(A union type in the generic didn't seem to work in the playground so I just union'd the interfaces myself)

The downside of this approach is you're passing an instance of a type around to pass the type around, but it's not as if JS has a builtin way to pass types... I guess. It works, is what I'm saying.

**Comment by mhegazy** [comment]
General cleanup, we should log issues/suggestions for remaining issues. closing for now.
