### ISSUE TITLE
QuestionToken missing when ran through Typescript Transformer

### ISSUE THREAD

**Issue by TriStarGod** [microsoft/TypeScript#42328]
# Bug Report

### 🔎 Search Terms

QuestionToken, Transformer, Typescript

### 🕗 Version & Regression Information

This is the behavior in every version 4.x version I tried, including the latest beta.

### ⏯ Playground Link

[Codesandbox sample](https://codesandbox.io/s/ts-transformer-qdtp2?file=/src/index.ts:250-616
)

### 💻 Code

I made a simple transformer.

    import ts from "typescript";
    import path from "path";
    
    export function Transformer(
    	checker: ts.TypeChecker,
    ): ts.TransformerFactory<ts.SourceFile> {
    	return (context) => {
    		const v: ts.Visitor = (node: ts.Node) => {
    			console.log(node.kind);
    			return ts.visitEachChild(node, v, context);
    		};
    		return (node) => ts.visitNode(node, v);
    	};
    }
    
    async function MainAsync() {
    	const dir = path.resolve("./");
    	const filePathIn = path.resolve(dir, "./src/test.ts");
    	console.log({ filePathIn });
    	const program = ts.createProgram([filePathIn], {});
    	const checker = program.getTypeChecker();
    	const source = program.getSourceFile(filePathIn);
    	console.log("checking source");
    	if (!source) return;
    	console.log("run through transformer");
    	await ts.transform(source, [Transformer(checker)]);
    	// console.log({ result });
    }
    
    MainAsync();

Testing against a simple `test.ts` file

    export class TestMe {
    	id0?: {
    		test0: string;
    	};
    	id: number;
    }

### 🙁 Actual behavior

    297 - SourceFile
    252 - ClassDeclaration
    92 - ExportKeyword
    78 - Identifier
    163 - PropertyDeclaration
    78 - Identifier
    177 - TypeLiteral
    162 - PropertySignature
    78 - Identifier
    147 - StringKeyword
    163 - PropertyDeclaration
    78 - Identifier
    144 - NumberKeyword

### 🙂 Expected behavior

    297 - SourceFile
    252 - ClassDeclaration
    92 - ExportKeyword
    78 - Identifier
    163 - PropertyDeclaration
    78 - Identifier
    57 - QuestionToken
    177 - TypeLiteral
    162 - PropertySignature
    78 - Identifier
    147 - StringKeyword
    163 - PropertyDeclaration
    78 - Identifier
    144 - NumberKeyword

Note that its missing `57 - QuestionToken`. I also confirmed the expected test.ts output via [TypeScript AST Viewer](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwDYEMDOa4BVhpgWWDgG8AoASAEsATABgH4AuEi8mXGW5vKSgOwDmAbgoBfEVWrM+AVwC2AI2BQRo0kA) .

Typescript still checks if its an optional type if I try to use it via VSCode. Whats going on? How do I force the QuestionToken to appear?

Also made a [stackoverflow question](https://stackoverflow.com/questions/65714962/typescript-transformer-questiontoken-missing)

**Comment by RyanCavanaugh** [comment]
I've posted an answer to the SO Q.

**Comment by TriStarGod** [comment]
Thank you so much. Where do you find this documented? I've working off typescripts Compiler API docs and various online samples and I hadn't come across this.

**Comment by RyanCavanaugh** [comment]
It's in the function signature:
```ts
function visitEachChild<T extends Node>(node: T | undefined, visitor: Visitor, context: TransformationContext, nodesVisitor?: typeof visitNodes, tokenVisitor?: Visitor): T | undefined;
                                                                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~
```
