### ISSUE TITLE
can not resolve global type when same name tsx & d.ts file exist in same folder

### ISSUE THREAD

**Issue by daskyrk** [microsoft/TypeScript#42329]
# Bug Report

### 🔎 Search Terms
same name tsx and d.ts file, can not resolve global type

### 🕗 Version & Regression Information
3.7.5

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because __can not downgrade___

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

I have a global.d.ts which defined a type Merge:
```ts
// global.d.ts
type Merge<A, B> = ({ [K in keyof A]: K extends keyof B ? B[K] : A[K] } &
B) extends infer O
  ? { [K in keyof O]: O[K] }
  : never;
```

In a folder `table`, if there is a `table.tsx` and a `table.d.ts`
```ts
// table.d.ts
type A = Merge<B, C>; // Cannot find name 'Merge'.ts(2304)
```

**If i rename either one of these two files to another name, or move one of them out of the folder, the error is gone.
I tried a another name `button`, same problem;**

![2021-01-14 15.38.17.gif](https://i.loli.net/2021/01/14/5XPAucylgCi9kIo.gif)

this is my tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es5",                         
    "module": "ESNext",                    
    "lib": [ "dom", "esnext" ],                            
    "allowJs": true,                      
    "checkJs": false,                      
    "jsx": "react",                    
    "declaration": true,                  
    "sourceMap": true,                    
    "incremental": true,
   
    "strict": false,                          
    "noImplicitAny": true,                
    "strictNullChecks": true,             
    "strictFunctionTypes": true,          
    "noUnusedLocals": true,               
    "noUnusedParameters": true,           
    "noImplicitReturns": true,            
    "noFallthroughCasesInSwitch": true,   
    "moduleResolution": "node",           
    "types" : ["webpack-env", "jest"],
    "baseUrl": "./",                      
    "paths": {
      "interface": ["./interface"],
      "app/*": ["./app/*"]
    },                          
    "typeRoots": [],                      
    "allowSyntheticDefaultImports": true, 
    "esModuleInterop": true,                  
   
    "experimentalDecorators": true,       
    "emitDecoratorMetadata": true,        
    "suppressImplicitAnyIndexErrors": true
  },
  "include": [
    "./interface/*",
    "./**/types/*",
    "./app/**/*",
    "./node_modules/@types/*"
  ]
}

```

### 🙁 Actual behavior
if same name of d.ts file and tsx file coexist in the same folder, d.ts file can not resolve global type

### 🙂 Expected behavior
even same name, d.ts file can resolve global type rightly

**Comment by MartinJohns** [comment]
Having both a `.tsx` and a `.d.ts` file makes no sense.

[Quoting @mhegazy:](https://github.com/microsoft/TypeScript/issues/15272)

> `.ts` files are considered sources, where `.d.ts` are considered outputs. the compiler will always prefer a source file for an output when it is resolving modules, the rational, is that sources are more up-to-date than an output.

**Comment by daskyrk** [comment]
So if i want to define a common type, i should define in tsx file and export it, then import in many other tsx file?
