### ISSUE TITLE
error importing from default object

### ISSUE THREAD

**Issue by mjw56** [Microsoft/TypeScript#4232]
Sorry if this is a dup.

Should I be able to do this? Trying to do something like:

Foo.ts
```ts
export default {
  Foo: {
    bar: 'baz'
  }
}
```

```ts
import { Foo } from './Foo';
```

but get ```Module '"./Foo"' has no exported member 'Foo'```

**Comment by danquirk** [comment]
You want
```ts
import Foo from './Foo'
```
to get the default export. The { } syntax is for getting named exports (and/or renaming them yourself)

**Comment by mjw56** [comment]
But the I would have to do ```Foo.Foo.bar``` instead of just wanting to do ```Foo.bar```

Does that make sense?

**Comment by kitsonk** [comment]
The you want to do something like this:

```typescript
export let Foo = {
  bar: 'bad'
};
export default { Foo: Foo }; /* or something more sensible */
```

Then you can:
```typescript
import { Foo } from './Foo';
```

Default create the return value for the module (sort of like `export = value`).  If you want to export something else that you can require in, then you need to export it, but not `export default`.
