### ISSUE TITLE
Private field member value assignment's of child classes should occur before super call

### ISSUE THREAD

**Issue by SLGShark6** [microsoft/TypeScript#42325]
# Suggestion
Fields marked with the "private" keyword in child classes should have their initialization (if an inline assignment is provided) occur before the super call in the emitted JS.

such as:
```typescript
private _field: string = 'Test';
```

## 🔍 Search Terms
child private field assignment initialization before super call

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example
Currently I am extending a class from an imported npm library, which I would rather not touch the code of directly, whether through a fork or local code edit. The issue being that I need to override methods and accessors from the base class in the library while utilizing my own child class's private fields in these methods and accessors. The accessors and methods I am overriding are called directly in the parent class's constructor. This is an issue because my field initializations do not occur until after the super call in the emitted code. The only way around this would to check if the field value is set in the getter of the property, and assign the default value, while also assigning the default value inline at the definition or in the constructor after the super call, which is necessary as i have the '"strictPropertyInitialization": true' TS config compiler option set.

See the simple typescript playground example outlining the issue (open browser console to see the error)
[Simple TS Playground Example Using TS v4.1.3](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=2&ts=4.1.3#code/MYGwhgzhAEwPYFsAOICmAPaBvAUNaSArgEYgCWw0AbmCIagFzQB2hCxqATgNw56xxmEAC6dCwYXE4AKGnUYs2HTgEps-fMIAWZCADo59aAF5qter3wBfHDZyhIMYpFTr8STmRrDXAfQhkyGgAYmSoIAAmTKzsXCbQAIy8-ADmqMIEnHBIXMIAntIq0UpxuPj48EJwaHogcCnSAOTMqADumdm5edBgwMCoUKgRjSqW5ZzphJzM0Nq6ev6BKKih4RFjNvgQ6R05nPnSMcWxqtjQGrM6+otBK2GR8TEb-PyVImISUoVu5XP6EXAIIh0jpmA1Rvw7PgAUCECCyGDvmVyhVBECanUGn89B5OvtugBqaAAJgh1lsfAcUFgOgeGB8zAiThcPw8XjAPmgvngt3Qq0iTB5y0wpha7SFaHQ0gSAA4Iakdri9gciooTj9UVUMfUmmLdl0en0BtthmTxpNppd5tzEML+REDOZUM8toqssqCkc1co1FhzijsTbefbHfJHmxnq80aJxJIZL6LhBCHtCmN8BdAxKMCHDK5TAlickA1c9DDgXNEWabHY9cBaRFU-wgA)

## 💻 Use Cases
As said above in the motivating example, more accurately, I am using an angular component library and extending a component to use my stateChanges RXjs Subject to detect changes inside relevant display related property setters, in order to refresh the view with up-to-date values (for reference I am using the OnPush change detection strategy). 

Having to work around this by both checking for set values in getters and assigning a default value elsewhere, is quite ugly and inconvenient.

If there is an easier/ cleaner workaround, great, but for now I think the best would be to have child private field assignments occur before super calls. This would not cause any adverse side-effects that I can think of with existing typescript code, as derived classes cannot have same named property declarations.

**Comment by ajafff** [comment]
This is not going to happen. JavaScript disallows access to `this` before `super()` is called. Therefore it's impossible to initialize instance properties before the super constructor is executed.

**Comment by SLGShark6** [comment]
Quite unfortunate, because it limits overriding quite a bit, if the super() call relies on overridden members. As a side note a cleaner looking workaround I've come up with to satisfy "strictPropertyInitialization" is to initialize the field with null and only use the accessors internally:

```typescript
// Simple Type Example
private _simpleField: string | null = null;

get simpleProperty(): string {
  if (this._simpleField === null) {
    this._simpleField = "Default Value";
  }
  
  return this._simpleField!;
}

set simpleProperty(value: string) {
  this._simpleField = value;
}

// Complex Type Example
private _complexField: ComplexType | null = null;

get complexProperty(): string {
  if (this._complexField === null) {
    this._complexField = new ComplexType();
  }
  
  return this._complexField!;
}
```

**Comment by RyanCavanaugh** [comment]
As @ajafff noted, this is literally impossible.
