### ISSUE TITLE
Question: where can one find all possible TSC errors?

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#42326]
# Question #

First, my apologies for not asking on SO, I doubt that questions like this are relevant to their platform.

Are any TSC errors documented (outside of the source code)?
Does an exhaustive list containing every possible error exist?
Is there a documented rationale behind why a compiler error is introduced?

If so, where might I find this documentation?
If not, why isn't there? Could this be introduced?

**Comment by RyanCavanaugh** [comment]
We don't have specific documentation for each error, no.

Our experience has been that it's very, very difficult to write meaningful per-error documentation (plus there are literally thousands of them); we prefer to document the system more holistically.

**Comment by 00ff0000red** [comment]
@RyanCavanaugh I can understand, documenting ~20k-30k different compiler errors wouldn't be easy, but is there anywhere that I can easily find the errors and their associated messages, maybe in the source code? Or are they scattered across the codebase?

**Comment by RyanCavanaugh** [comment]
See `src/compiler/diagnosticMessages.json`

**Comment by 00ff0000red** [comment]
Thanks, that'll help!
