### ISSUE TITLE
TS 4.2 beta preserves "keyof" expressions in type display

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#42322]
# Bug Report

### 🔎 Search Terms

- keyof 4.2

### 🕗 Version & Regression Information

    $ tsc --version
    Version 4.2.0-dev

- This changed between versions 4.1.3 and 4.2.0-beta

### ⏯ Playground Link

[playground][]

### 💻 Code

```ts
interface Point {
  x: number;
  y: number;
}
type Axes = keyof Point;
```

Mouse over `Axes`.

### 🙁 Actual behavior

Displays `keyof Point`

### 🙂 Expected behavior

Displays `"x" | "y"`.

I assume this is the result of #42284, but this display seems much less informative than what we used to have:

<img src="https://user-images.githubusercontent.com/98301/104513172-3ae1f980-55bd-11eb-86f3-22cf028b74f6.png" width="50%">

Having used `keyof` in the past, I know that `keyof Point` is the same as `"x" | "y"`. But displaying its type as `keyof Point` isn't very informative if you don't know that. I worry that this will make it much harder for new TypeScript users to understand how `keyof` works.

[playground]: https://www.typescriptlang.org/play?ts=4.2.0-beta&ssl=1&ssc=1&pln=6&pc=1#code/JYOwLgpgTgZghgYwgAgAoHtRmQbwFDLIAeAXMiAK4C2ARtANwHICeZltDeAvnmMwA4oAgkQgBnZAF5kAawjN0MNJnCMgA

**Comment by RyanCavanaugh** [comment]
When there are two keys, it's probably preferable, but what about when there are a hundred? It's less clear then, and losing the information about where those keys are coming from is less recoverable. As a developer I can go to the definition of `Point` and read its keys, but there's no reverse operation that takes me to "a" type that has the keys `"a" | "bold" | "div" | "form" | "h1" | "h2" | "h3" | ...`

**Comment by danvk** [comment]
Fair enough, but with TS 4.2 is there any way to expand the type so that I can see what it actually is?

The `unknown &` trick doesn't seem to work here:

```ts
interface Point {
  x: number;
  y: number;
}
type Axes = keyof Point;
// type is keyof Point

type AxesExpand = unknown & Axes;
// type is keyof Point

type AxesExpand2 = unknown & keyof Point;
// type is keyof Point
```

**Comment by RyanCavanaugh** [comment]
![image](https://user-images.githubusercontent.com/6685088/104519219-ef741f00-55ad-11eb-8d46-f89caf8b026d.png)

**Comment by RyanCavanaugh** [comment]
Or
```ts
type Q = Exclude<Axes, never>;
```

**Comment by danvk** [comment]
Thanks @RyanCavanaugh !

**Comment by SrBrahma** [comment]
> Or
> 
> ```ts
> type Q = Exclude<Axes, never>;
> ```

There is also the useful `{[K in keyof T]: T[K]}` to "simplify" objects. Maybe there should be a page in the docs about those? They are really useful to prettify type definitions and not very known as they should.
