### ISSUE TITLE
Infer on tuples broken on nightly

### ISSUE THREAD

**Issue by mikearnaldi** [microsoft/TypeScript#42331]
# Bug Report

The latest nightly release breaks non distributive `infer`

### 🕗 Version & Regression Information

Bug introduced in the latest nighty release

### 💻 Code

```ts
type _R<T> = [T] extends [{ _R: (_: infer R) => void }] ? R : never
type _E<T> = [T] extends [{ _E: () => infer E }] ? E : never
type _A<T> = [T] extends [{ _A: () => infer A }] ? A : never

interface Sync<R, E, A> {
  _R: (_: R) => void
  _E: () => E
  _A: () => A
}

type R = _R<Sync<number, string, void>>
type E = _E<Sync<number, string, void>>
type A = _A<Sync<number, string, void>>
```

### 🙁 Actual behavior

```ts
R = never
E = never
A = never
```

https://www.typescriptlang.org/play?ts=4.2.0-dev.20210114#code/C4TwDgpgBA+gSgHgCoD4oF4oG0kF0oQAewEAdgCYDO2A3rHAFxQAUMTAlqQGYQBOUcAJQY0ANwD27clAC++APwCoTUhFF8AUKEiwAosjSYc+IiQrUsdGLqbNh6NJx79dshVFcq1m7dBgBBAwxsPAJiMipaWH9be0duPih-NyhFZK91Xg0NThJeLgBDAGNoAGUQUiKEOAAaDzr-NBoNKHpbNgE4qAkpFr1YkQ8+gIGHJI0ZbN8lTHgEcsqEUgBXAFsAIz46ymBeTgBzOp7yFBQtcGhXWf0FqpWNragdvdJD7skTs+nk2cDbpbWm14212ByOH1OGiAA

### 🙂 Expected behavior

```ts
R = number
E = string
A = void
```

https://www.typescriptlang.org/play?ts=4.2.0-beta#code/C4TwDgpgBA+gSgHgCoD4oF4oG0kF0oQAewEAdgCYDO2A3rHAFxQAUMTAlqQGYQBOUcAJQY0ANwD27clAC++APwCoTUhFF8AUKEiwAosjSYc+IiQrUsdGLqbNh6NJx79dshVFcq1m7dBgBBAwxsPAJiMipaWH9be0duPih-NyhFZK91Xg0NThJeLgBDAGNoAGUQUiKEOAAaDzr-NBoNKHpbNgE4qAkpFr1YkQ8+gIGHJI0ZbN8lTHgEcsqEUgBXAFsAIz46ymBeTgBzOp7yFBQtcGhXWf0FqpWNragdvdJD7skTs+nk2cDbpbWm14212ByOH1OGiAA

**Comment by r-cyr** [comment]
I can reproduce it, last working build was 4.2.0-dev.20210112.

**Comment by mikearnaldi** [comment]
It seems related to tuples, rewriting as:

```ts
type _R<T> = {t: T} extends {t: { _R: (_: infer R) => void }} ? R : never
type _E<T> = {t: T} extends {t: { _E: () => infer E }} ? E : never
type _A<T> = {t: T} extends {t: { _A: () => infer A }} ? A : never

interface Sync<R, E, A> {
  _R: (_: R) => void
  _E: () => E
  _A: () => A
}

type R = _R<Sync<number, string, void>>
type E = _E<Sync<number, string, void>>
type A = _A<Sync<number, string, void>>
```

Works on nightly too

**Comment by mikearnaldi** [comment]
Well seems definitely related to tuples:

```ts
type X = [0] extends [infer A] ? A : never
```

`X` here is `never` instead of `0`

**Comment by ahejlsberg** [comment]
@weswigham Might this be caused by #42248?

**Comment by weswigham** [comment]
Hm, must be? I'll have to see why it caused this, since unwrapping the tuples for the "is generic" checks doesn't seem like it should affect inference of `infer` variables. And add some coverage into our test suite since this is pretty common.

**Comment by jcalz** [comment]
Is [this](https://tsplay.dev/wQAKAw) related or unrelated?

```ts
type Hmm = [never] extends [infer T, ...any[]] ?
    [T, [never] extends [T] ? true : false]
    : never

// TS 4.1.5
// type Hmm = [never, true] ✔

// TS 4.2.2
// type Hmm = [never, false] ❌
// So T is inferred as never, but [never] extends [T] is false?
```
