### ISSUE TITLE
Suggestion: Using typeof with an expression

### ISSUE THREAD

**Issue by ander-nz** [Microsoft/TypeScript#4233]
It would be helpful if the `typeof` keyword were changed to support more complex expressions, such as function calls.

#### Example
Given the following AngularJS service definition:
```js
module myApp {
  function myApiFactory($http: HttpSvc) {
    return {
      getSetting: (key: string) => $http.get(etc),
    };
  }
  angular.service("myApi", myApiFactory);
}
```

It would be good if the following statement were possible:
```js
export type MyApi = typeof myApiFactory();
```

#### Explanation
Since the function is a factory rather than the actual service, this type alias would other components to have a strongly-typed reference to the service. Though this example relates to AngularJS' service factory and dependency injection, this particular change would not be solely for AngularJS support.

#### Existing solutions
One option to resolve this issue is to explicitly define an interface for the service. However, this solution would require repeating the signature for all of the service's methods.

A workaround exists that relies on JavaScript's scoping rules to satisfy TypeScript's `typeof` keyword. However, it significantly reduces readability and clarity. An example:
```js
if (false)
  var obj = myApiFactory(null);
export type MyApi = typeof obj;
```

**Comment by lazutkin** [comment]
:+1:  Seems related to https://github.com/Microsoft/TypeScript/issues/3749#issuecomment-123844366  as means to get collection element type through expression.

**Comment by mhegazy** [comment]
I find Using an expression with potential sides effects in a type position really confusing.

**Comment by mhegazy** [comment]
Also can you elaborate on how the API and the type would be used outside the module?

**Comment by yortus** [comment]
I have found myself wishing this were possible sometimes - usually when using type definitions from DefinitelyTyped. For example, `knex.d.ts` internally defines a `QueryBuilder` interface but does not export it, even though most `knex` methods return instances of this type. That makes it a pain to, say, write a function that takes a `QueryBuilder` as an argument.

A workaround is to create a 'dummy' variable with the desired type using an expression that is not necessarily evaluated, and then using `typeof` on that. In the `knex` case, the following works:

```typescript
import Knex = require('knex');
var dummyQueryBuilder = false ? Knex(<any>{})() : null;
type QueryBuilder = typeof dummyQueryBuilder;
```

The proposal outlined by @ander-nz is far cleaner than this, although I agree with @mhegazy that putting expressions in type positions may be confusing.

The best approach in this example is to fix `knex.d.ts` and sumbit a PR to DefinitelyTyped, but that's a 'big fix' approach that may not always be possible, and for which `typeof expr` could provide a nice short-term fix in the meantime.

**Comment by yortus** [comment]
This would be equivalent of C++'s `decltype(expr)`, which is used in a type position but does not evaluate `expr`. It's a very useful facility for writing reuseable code that propagates types without foreknowledge of their names.

**Comment by ander-nz** [comment]
@mhegazy I agree that the syntax could be confusing, as per below:
```js
var a = typeof myApiFunc(); // actually invokes myApiFunc, and then sets a to "object".
type A = typeof myApiFunc(); // does not invoke it, only looks at its return type.
```

A possible alternate syntax is using `<``>` brackets, since these are already used by TypeScript. For example:
```js
type MyApi = typeof<myApiFunc()>;
```

This could simplify the syntax, and would look out of place enough to remind the reader that the expression is a TypeScript feature. Does this look clearer?

**Comment by ander-nz** [comment]
@mhegazy And to answer your question about how the type would be used outside the module. That example is designed for AngularJS, which uses dependency injection, such as:
```js
function MyCtrl($scope, myApi: myApp.MyApi) {
    // ...
}
```

**Comment by mhegazy** [comment]
i would rather have a compiler operator e.g. `__returnTypeof` than to overload `typeof`.

**Comment by yortus** [comment]
If this facility existed as a purely compile-time thing, say `__returnTypeof expr` or `decltype(expr)` or whatever, could it be used in an ambient context? E.g:

```typescript
declare module "mymodule" {
    import knex = require('knex');
    type QueryBuilder = __returnTypeof (knex(<any>{})()); // obtain the QueryBuilder type from knex;
    export function someExportedFunction(query: QueryBuilder): void;
}
```

This covers a likely use case for the construct, but would involve allowing expressions to appear in ambient declarations. Is that feasible with the design of the compiler?

**Comment by rotemdan** [comment]
I think that the scope of `typeof expression` is very wide. It is very powerful but that also means that expressing some specific patterns in it would require sacrificing tidiness and clarity which would lead to lower general usability in those scenarios.

Perhaps it would be beneficial to try to isolate the most prominent cases where `typeof expression` would be commonly used (such as, say, `typeon` or `returnTypeOf` [and perhaps also `returnTypeOn`?] ) and try to individually consider a more "optimized", special-purpose syntax and semantics for each one of them.

It would still be useful to have a more powerful operator for special cases, however, it might be possible to emulate many of them by embedding the evaluated expression in a function and "extracting" the inferred return type, like this:
```ts
function expressionFunc() {
  return [...] // expression
}
// can also be written as 'expressionFunc = () => [..]'

var x: returnTypeOf expressionFunc;
```
This would naturally extend to generic expressions as well:
```ts
function genericExpressionFunc<T>() {
  return [...] // generic expression
}

var x: returnTypeOf expressionFunc<string>;
```

**Comment by benliddicott** [comment]
Can I add my vote to this item. This seems very useful and has wide application.

**Comment by d180cf** [comment]
Why not to introduce the notion of subtypes?

```ts
function f(x: number, y: string) {
  return x || y;
}

type T = (typeof f).ReturnType; // string | number
```

Every function type could have a .ReturnType member that would be equal to the type of what the function returns. Typescript knows this type, but doesn't seem to make it accessible in a straightforward way.

**Comment by rotemdan** [comment]
@d180cf 

I think using a "virtual" sub-type is an interesting approach, and I'm also investigating alternatives to `returnTypeOf` and `returnTypeOn` myself (including even syntax that would handle overloaded return signatures etc.). The problem with this particular syntax is that Typescript (and Javascript) allows declaring hybrid function/object types (functions with normal properties defined on them):
```ts
interface HybridFunc {
  // This is a function signature specifier:
  (x: number, y: string): string;

  // This is an example of a normal property with type 'Array<boolean>'
  // that just happens to have the name 'ReturnType':
  ReturnType: Array<boolean>; 
}

let hybridFunc: HybridFunc;
```
So in this case type `type T = typeof hybridFunc.ReturnType` would be ambiguous. 

Using it with my proposed [`typeon` operator](https://github.com/Microsoft/TypeScript/issues/4640), (an operator that would allow referencing a property type directly through its containing type):  would also have the same problem: `type T = typeon HybridFunc.ReturnType`.

**Comment by basarat** [comment]
Going though the issue. I suggest that a simpler **workaround** be used: 

```ts
function myApiFactory() {
  return {
    getSetting: () => null
  };
}

const myApiFactoryReturn = false && myApiFactory();
export type MyApi = typeof myApiFactoryReturn;
```

Basically instead of 
```ts
export type MyApi = typeof myApiFactory();
```

You have two lines: 

```ts
const myApiFactoryReturn = false && myApiFactory();
type MyApi = typeof myApiFactoryReturn;
```

**Comment by rotemdan** [comment]
@basarat 

I found an even simpler workaround yesterday:
```ts
// The expression would never execute but its type would be inferred:
let e = true ? undefined : ...expression...;
type ExpressionType = typeof e;
```
To get return types:
```ts
let r = true ? undefined : someFunction();
type RerturnType = typeof r;
```
This workaround would only work on runtime code positions though, so it is mostly relevant to`typeof func()`. It can still be used to emulate `typeon this.func()`, but that would be more complex:
```ts
interface A {
  func(x: number): string;
  prop: ReturnType; // emulates 'typeon this.func()'
}

let a: A;
let r = true ? undefined : a.func(0);
type RerturnType = typeof r;
```
But similarly to other workarounds for `typeon`: in the case of a generic interface or class it would not be possible to propagate the generic parameter into the dummy instance:
```ts
interface A<T> {
  func(x: number): T;
  prop: typeon this.func(); // No workaround for this
}
```

**Comment by benliddicott** [comment]
See also Generic Meta Types #3779

**Comment by yortus** [comment]
@basarat @rotemdan At present `typeof` is useable in ambient contexts (e.g. in `.d.ts` files), and perhaps the extended `typeof` proposed here could preserve this quality. That's one thing the workarounds, consisting of imperative statements of various forms, cannot do.

**Comment by msklvsk** [comment]
Dear Santa, please bring me <code>decltype</code> in Typescript.

**Comment by yortus** [comment]
I submitted a proposal + implementation for this: #6606

**Comment by RyanCavanaugh** [comment]
Let's take the discussion over to the nice clean slate at #6066.

**Comment by magnushiie** [comment]
With recent null checks, the above recommendation:
```
let r = true ? undefined : someFunction();
type RerturnType = typeof r;
```
can be changed to 
```
let r = true ? undefined as never : someFunction();
type RerturnType = typeof r;
```
to avoid the (undefined | ...) type.
