### ISSUE TITLE
`\n` not parsed as newline when used as string attribute to TSX component.

### ISSUE THREAD

**Issue by bjnsn** [microsoft/TypeScript#42342]
# Bug Report
Perhaps this is intentional behavior... but it is very unexpected.

`<SomeComponent text="hello\n world"/>`  is not the same as `<SomeComponent text={"hello\n world"}/>`
The newline `\n` is evaluated as a newline in the later case, but as literal characters in the first...

### 🔎 Search Terms
TSX, JSX, newline, string literal, component

### 🕗 Version & Regression Information
This exists as of 4.1.2 and existed also 3.9.7; Presumed to have existed since TSX support was introduced.

Please keep and fill in the line that best applies:
-->

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link
I was unable to figure out how to make the playground or workbench parse as TSX, so I've set it up here:

https://codesandbox.io/s/silly-paper-4ulbn?file=/src/App.tsx

### 💻 Code

```tsx
import * as React from "react";

const Sub: React.FC<{ text1: string; text2: string }> = ({ text1, text2 }) => {
  return <div>{text1 === text2 ? "equal" : "not-equal"}</div>;
};

export default function App() {
  return <Sub text1="hello\n world" text2={"hello\n world"} />;
}
```

### 🙁 Actual behavior
`\n` is not evaluated as a newline if used as a string literal argument

### 🙂 Expected behavior

`\n` is evaluated as a newline if used as a string literal argument

**Comment by MartinJohns** [comment]
But this is the same behavior as in JSX: https://codesandbox.io/s/jsx-react-element-forked-nn4o0?file=/index.js

**Comment by RyanCavanaugh** [comment]
This is the same behavior as Babel, which is our "reference implementation" for JSX.

I believe their reasoning here is that `\` isn't escaped in HTML (e.g. if you write `<input value="foo\nbar">` that displays as-written).

**Comment by bjnsn** [comment]
Hmm - I guess this gotcha illustrates the problem with trying to merge together disparate paradigms. Not intuitive from one perspective, but totally understandable from the other.

Thanks for looking at this!
