### ISSUE TITLE
Only accept 2..36 as Number.toString() param 

### ISSUE THREAD

**Issue by pvarga-dni** [microsoft/TypeScript#42348]
# lib Update Request

PR: #42347

## Missing / Incorrect Definition

`Number.prototype.toString()` should only accept numbers between 2..36 inclusive.

## Sample Code

`(99).toString(99)`, this will throw `RangeError`.

**Comment by RyanCavanaugh** [comment]
This is going to be a breaking change in a nonzero number of places and just seems like an incredibly difficult mistake to make. This isn't worth the churn on our side or anyone else's.

**Comment by pvarga-dni** [comment]
Ok fair enough.
