### ISSUE TITLE
tmi.js has overload resolution error after #42248

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#42340]
To repro `cd DefinitelyTyped/types/tmi.js && tsc`.
I'd also recommend commenting out the second overload of each pair, except that it seems to have been put in expressly to use the assignability rules for overloads. Since that particular code was written by @bterlson, it's likely that one of us advised him to do it.

Without the overloads, I still can't figure out what the cause of the error is, but the error is at least on the right signature.

Probably related to #42337 and #42336.

Expected: No error.
Actual: Error.

**Comment by weswigham** [comment]
Looks like this got fixed by #42409
