### ISSUE TITLE
Compilation failure on function parameters with (any[] | Record<string, any>)

### ISSUE THREAD

**Issue by FuriousLlama** [microsoft/TypeScript#42343]
# Bug Report

### 🔎 Search Terms

"any array parameter"
"any array with record"
"any record with array"

### 🕗 Version & Regression Information

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEDEEMEsBsGdQBcD2oDGKC2AHOBTAKABN91ZIAnfZATxxvBTQF5QAKHKyLALlEgA7WgG0AuqAA+oAEpkUlYgB54SStEEBzADQDhAPgCUoFvtAAjZrHxCA3IWtIB-Jqw5dKPfnMyKVajR1QABFIJHwjEzMAb0JQeIwUQXgUawA6WBRNTm4sQ3sE0GokAFdKQWRKEvx7AF97Qkh2aNAKCn4AZlBa-MJCEFAAOTRMXDgw6CTQfEpKBXgSMgpqOgZQACEqE3dc73k-VXUtXSFaSNMLKxtBe0cLfk3KbZzPPll95UPA3VDw85i4glMMlUvgMlkXjxeoVimUKmpqnUGuZmq1IO1QF0erYgA)

### 💻 Code

```ts
// Fails to compile
declare type Foo = (param: any[] | Record<string, any>) => boolean;
let a: Foo = (param: Record<string, Date>) => {
    console.log(param);
    return true;
};

// No compilation errors
declare type Bar = (param: Record<string, any>) => boolean;
let b: Bar = (param: Record<string, Date>) => {
    console.log(param);
    return true;
};
```

### 🙁 Actual behavior

```
ERROR in [source_path]:
146:5 Type '(param: Record<string, Date>) => true' is not assignable to type 'Foo'.
  Types of parameters 'param' and 'param' are incompatible.
    Type 'any[] | Record<string, any>' is not assignable to type 'Record<string, Date>'.
      Type 'any[]' is not assignable to type 'Record<string, Date>'.
    144 | 
    145 | declare type Foo = (param: any[] | Record<string, any>) => boolean;
  > 146 | let a: Foo = (param: Record<string, Date>) => {
        |     ^
    147 |     console.log(param);
    148 |     return true;
    149 | };
```

### 🙂 Expected behavior

Compilation succeeds.

**Comment by MartinJohns** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

**Comment by RyanCavanaugh** [comment]
This isn't bivariance (the same behavior is observed under SFT), it's just what `any` does.

**Comment by MartinJohns** [comment]
@RyanCavanaugh He's using `any[]`, not `any`. Turning strict-function-types off makes the code compile just fine.

**Comment by RyanCavanaugh** [comment]
I misread and thought the "expected" was no error.

Anyway, yeah, `any[]` is not a valid `Record<string, Date>` since it lacks a string index signature

**Comment by FuriousLlama** [comment]
Thank you @RyanCavanaugh  and @MartinJohns. I'll take a a read on bivariance and see what I missed. My intuition tells me that if any[] is not a valid Record<string, Date> it would match instead Record<string, any>, similar to other types.
