### ISSUE TITLE
TS Compiler doesn't know about Computed object property names

### ISSUE THREAD

**Issue by gaurav21r** [Microsoft/TypeScript#4235]
According to ES6 and Typescript I can do this -> 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Computed_object_property_names_and_destructuring

Although the code produces the right output the TS Compiler is giving me an error like so:

```ts
var o1 = {key: 'value'};

var o2 = {
	[o1.key]: 123
}

//Outputs {value: 123}
console.log (o2);

//Oops Error
// "Property 'value' does not exisit on type '{}'"
console.log (o2.value);
```

Here's the link to the playground: http://www.typescriptlang.org/Playground#src=var%20o1%20%3D%20%7Bkey%3A%20'value'%7D%3B%0D%0A%0D%0Avar%20o2%20%3D%20%7B%0D%0A%09%5Bo1.key%5D%3A%20123%0D%0A%7D%0D%0A%0D%0A%2F%2FOutputs%20%7Bvalue%3A%20123%7D%0D%0Aconsole.log%20(o2)%3B%0D%0A%0D%0A%2F%2FOops%20Error%0D%0A%2F%2F%20%22Property%20'value'%20does%20not%20exisit%20on%20type%20'%7B%7D'%22%0D%0Aconsole.log%20(o2.value)%3B%0D%0A%0D%0A

I figured type inference is happening in run time rather than statically. Maybe that's the issue? 

Sorry if I'm missing something here. First issue on TypeScript.

**TS is AWESOME :+1:**

**Comment by mhegazy** [comment]
Computed properties have dynamic names. The compiler can not know these in all cases. It will emit the rigjt code for you but will not be able to infere the correct type. Consider

{
    [foo()] : 1
}

The name of the property will depend on the return type of foo at runtime.

**Comment by mhegazy** [comment]
Looks like the original issue has been answered. please reactivate if you are running into other issues.
