### ISSUE TITLE
Type behavior of __proto__ isn't correct.

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#42358]
# Bug Report

The `__proto__` in the object literal has special meanings in JavaScript and TypeScript doesn't recognize that.

### 🔎 Search Terms

`__proto__`

### 🕗 Version & Regression Information

- It never worked IMO

### 💻 Code

```ts
class X { echo() { return this } }
const y = { __proto__: X.prototype }
```

### 🙁 Actual behavior

Type of `y` is `{ __proto__: X }

### 🙂 Expected behavior

Type of `y` is `X`

**Comment by MartinJohns** [comment]
Duplicate of #38385. Literally the first issue after yours when searching for `__proto__` (the search term you listed).

**Comment by Jack-Works** [comment]
Oh I'm sorry
