### ISSUE TITLE
Class with default prop that extends a generic with a constructor ignores prop in arguments

### ISSUE THREAD

**Issue by dw-bayer** [microsoft/TypeScript#42362]
**Search Terms:** 
extending generic class constructor, default property taking priority over constructor argument

**Code**

```ts
class Base<T> {
  constructor(props: Partial<T> = {}) {
    Object.assign(this, props);
  }
}

class A extends Base<A> {
  default = false;
  working?: boolean;
}

const classA = new A({default: true, working: true})

console.log(classA.default, classA.working) // false, true

class B extends Base<B> {
  default = false;
  working?: boolean;

  constructor(props: Partial<B>) {
    super(props);
  }
}

const classB = new B({default: true, working: true})

console.log(classB.default, classB.working) // false, true

class C {
  default = false;
  working?: boolean;

  constructor(props: Partial<C> = {}) {
    Object.assign(this, props);
  }
}

const classC = new C({default: true, working: true})

console.log(classC.default, classC.working) //true, true

class Base2<T> {
  constructor(props: T) {
    Object.assign(this, props);
  }
}

class D extends Base2<D> {
  default = false;
  working?: boolean;
}

const classD = new D({default: true, working: true})

console.log(classD.default, classD.working) // false, true
```

**Expected behavior:**
When passing props to the constructor of a class that has default properties and that extends a generic class with a generic constructor I expect those props to be used to initialize the class instead of any default value on the class.

**Actual behavior:**
The default value for the prop is used.

**Playground Link:**  
[Link](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/MYGwhgzhAEBCkFMA8AVAfNA3gWAFDWmAHsA7CAFwCcBXYcoygCgAdKjmIAuaABTEvIBLMCFQYAvFgC+ASix4CBAPIAjAFYI6AOkgRBAcxKNyAC0EQANNFbsIMgNwLoUvC9x5Qu6AEFoCAB7kCCQAJjDwEMjeGDj40CEIAGZg1CDk0JLJIJGOuG4epBSE4FC+kiQIAO4+jJgJyank3FTUCLJ4BWREIAhaIET6jJ6lWvUpaTIduMPhfoHBYXCISLAxTmONGdBZOVMExGQtdAwsbBzcfALCoqtysYrQENTMCEw2HA5ObvnThekzsC2FWqsFqGzSzRobUm7l+XR6fQGQxKEFgoyS43IMI8KOgAGF5HFwelMiJdrD9n8aMc3mcuLx+EIREg8RJpHcnMp1JpyDooAYjKZzFZ3nZcgRvlMDkUZgTylV8WCMY1Ia12rDpd1ev1BrL0Q0JkA)

**Edits**
1. forgot to finish a search query i'd used.
2. added extra examples and a prop to act as a constant to show that non-defaulted props work as expected. Also added a test to see if `Partial` was to blame. it wasn't.

**Comment by MartinJohns** [comment]
This looks like a duplicate of #1617.

**Comment by dw-bayer** [comment]
@MartinJohns maybe?

this would mean `default` _is_ being set to `true` during the `super` but then the default of `default` of the extending class then overwrites `default`?

**Comment by MartinJohns** [comment]
@dw-bayer Yes, intentional. From the other issue:

> The order of initialization is:
>
> 1. The base class initialized properties are initialized
> 2. The base class constructor runs
> 3. The derived class initialized properties are initialized
> 4. The derived class constructor runs

**Comment by RyanCavanaugh** [comment]
You can run this in your browser console:
```ts
class Base {
  constructor(x) {
    this.prop = x;
  }
}
class Derived extends Base {
  prop = 10;
}
const m = new Derived(3);
console.log(m.prop);
```
Prints `10`, not `3`.

**Comment by dw-bayer** [comment]
You cats are right. thanks for your big brains. I hope you can forgive me for not equating the linked issue with mine :D
