### ISSUE TITLE
Syntax proposal: TypeParameters with arguments

### ISSUE THREAD

**Issue by thr0w** [Microsoft/TypeScript#4236]
I propose extend generics to support arguments in type parameters. Something like that:

&emsp;&emsp;*TypeParameter:*  
&emsp;&emsp;&emsp;*BindingIdentifier*&emsp;__*TypeParameters<sub>opt</sub>*__&emsp;*Constraint<sub>opt</sub>*

This is useful for complex API's, like factories and proxies, that need receice too many data types.

>
```typescript
interface Data<K, V> { find(key: K): V }
```
```typescript
function createProxy<T<K,V> extends Data<K,V>> (
   return <T<K,V>> {
      find: function(key: T.K): T.V { ... }
   }
}
```
```typescript
interface PatientData extends Data<number,{name: string, age: number}>{ }
```
```typescript
var pacientProxy = createProxy<PatientData>();
var {name, age} = pacientProxy.find(1);
```

**Comment by aleksey-bykov** [comment]
Also see: https://github.com/Microsoft/TypeScript/issues/1213

**Comment by DanielRosenwasser** [comment]
I notice that you have a function extending a type - can you explain what you mean by this?

**Comment by thr0w** [comment]
@DanielRosenwasser isn't `function createProxy` extending but the type `T` is extending the type `Data` . And how type `Data` needs `K,V` arguments, my suggestion is typescript support use that arguments in type `T`. 

@aleksey-bykov I don't know if #1213 solves my problem. It's new to me, looks complex. I'll study and later answer here.

Thanks guys

**Comment by DanielRosenwasser** [comment]
Whoops, misread that, sorry.

**Comment by radek-holy** [comment]
Would https://github.com/Microsoft/TypeScript/issues/214 solve this?

**Comment by steffansluis** [comment]
:+1: For generic generics

**Comment by sandersn** [comment]
I'm pretty sure this is the same as higher-kinded types in #1213. I'll close this as a duplicate.
