### ISSUE TITLE
[feature idea] `inherits`, class inheritance assertion operator

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#42376]
# Suggestion

## 🔍 Search Terms

N/A

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

This would allow authors to make `class` types that inherit from other types. This is similar to `extends`, but has no runtime effect, and serves for the purpose of asserting that a class _does_ inherit certain members that are not explicitly defined.

The effect is very similar to `implements`, but the difference is implementation is not required. Another difference is that with `inherits` it can accept class types (so the class that has `inherits` will inherit accessibility and other `class` features).

## 📃 Motivating Example

This allows us to create type definitions for certain JavaScript patterns that are too dynamic for TypeScript. For example:

```ts
import {methods} from 'some-plain-JS-project'

function copyMethods(obj: object, methods: Record<string, Function>): void {
  for (const prop in methods) {
    if (typeof methods[prop] !== 'function') continue
    obj[prop] = methods[prop]
  }
}

declare class SomeMethods {
  spaces(n: number): string
  protected isSomething(o: HTMLElement): boolean
}

class MyClass extends HTMLElement inherits SomeMethods {
  connectedCallback() {
    this.spaces(5) // ok
    this.isSomething(document.body) // ok
  }
}

copyMethods(MyClass.prototype, methods)

const m = new MyClass

m.spaces(5) // ok
m.isSomething(m) // Type error, isSomething is protected.
```

## 💻 Use Cases

Various times when type defs can not be made for dynamic plain JS patterns.

## Caveat

The only problem is, this is not type safe. It's a type assertion basically. But it is not necessarily worse than `declare`ing a `class` and using it in `extends`, which also will give a runtime error.

**Comment by RyanCavanaugh** [comment]
This already exists; write
```ts
class MyClass extends HTMLElement {
  connectedCallback() {
    this.spaces(5) // ok
    this.isSomething(document.body) // ok
  }
}
interface MyClass extends SomeMethods { } 
```
