### ISSUE TITLE
The function returned by `f.bind(x)` doesn't have one less arguments than `f` 

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#42374]
# Bug Report

### 🔎 Search Terms

- bind
- bind number arguments
- strictBindCallApply

### 🕗 Version & Regression Information

observed in 4.1.3 and playground/nightly-build  

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "bind"

### ⏯ Playground Link

[Playground link with relevant code]
(https://www.typescriptlang.org/play?ts=4.2.0-dev.20210115&ssl=3&ssc=9&pln=1&pc=1#code/MYewdgzgLgBAZgXgBQA8BcBDMBPAlAgPgG8AnAUygFcSwYUBuAXwChRJY4AjESsAEwRwAdJwCW-JFBKUyuZlx4S5zGDCA)

### 💻 Code
```
const f=(x:any)=>{return x;}
const fbound=f.bind(true)
fbound()
```
### 🙁 Actual behavior

```
{
  message: 'Expected 1 arguments, but got 0.',
  relatedInformation: [
    {
      message: "An argument for 'x' was not provided.",
    },
  ],
};
```

### 🙂 Expected behavior

no error

**Comment by MartinJohns** [comment]
Why should it? Check (and run) the JavaScript code. It doesn't do what you think it does. Calling `fbound()` will return `undefined`, not `true`. The **first** argument of `bind()` is the `thisArg`, the bound this-context, not the first argument passed to the function.

If you run `f.bind(undefined, true)` you get the behavior you want.
