### ISSUE TITLE
tsc --build outputs same error multiple times when importing .ts files from node_modules

### ISSUE THREAD

**Issue by FabianSellmann** [microsoft/TypeScript#42381]
# Bug Report

### 🔎 Search Terms
build error multiple duplicate repeated type error type check from source
### 🕗 Version & Regression Information

- seen on version 4.1.2, 4.1.3

### ⏯ Playground Link

[Github with repro steps and example](https://github.com/FabianSellmann/ts-type-rerun-repro)

### 🙁 Actual behavior

When a building a monorepo using project references, where each package/project directly access the source `.ts` files (instead conventionally the declaration) of it's dependencies, any type error in a dependency will printed out for each package/project depending on it (directly or transitive). 

### 🙂 Expected behavior

I would have expected the error to only be printed once. Also the statement about the amount of errors at the end is misleading. On top of that I assume that the same type checking is repeated multiple times here, maybe there is a potential for better runtime caching?

### A bit more details and background

I am using a mono repo setup. I have been having issues with type checking taking such a long time recently. One idea was to use typescript as a typechecker only and let faster compilers strip away the type annotations when needed. Thus, while not making type checking faster, I can run other things in parallel while type checking - locally as well on CI. Given how fast compilers such as ESBuild or SWC are, I also wanted to use the opportunity to remove the need to have to recompile on every file change and just compile on the fly when needed - e.g. with a jest transformer, or webpack loader and including relevant node_modules for transformation. So setting up typescript to only do type checking should be very simple. Just only emit declarations outside the package structure to easily persist it all at once to a remote cache and switch the `main` of each `package.json` from `.js` to `.ts` and thats it. 

However it appears, due to referencing directly `.ts` files without the presence of a declaration files in other modules, type checks are run multiple times over the same code. Resulting in the above described behavior. With that I am not sure if this expected behavior, as I know it might also not be expected usage. But the repeated output like this is not really helpful. Especially if the error prone code is a dependency for many other projects, the output is cluttered with this.
```
packages/b/b.ts:2:9 - error TS2322: Type 'string' is not assignable to type 'number'.

2   const number: number = "1";
          ~~~~~~

packages/b/b.ts:2:9 - error TS2322: Type 'string' is not assignable to type 'number'.

2   const number: number = "1";
          ~~~~~~


Found 2 errors.

error Command failed with exit code 1.
```

But even more curious, if you play around with removing tsbuildinfo and rebuilding (as described in the repo linked above), you might get into a configuration where typescript will only output the error once.  So either way something is inconsistent here.

I am not sure what is happening under the hood, but if typescript is really rerunning the typecheck again to infer what would otherwise be obvious from the type declaration, then I think there is room for improvement here. Especially since the type checking output is apparently reused with `incremental` from the emitted `tsbuildinfo`, but only after a `build` compile has fully run. Maybe typescript could take into account the previously resolved references' output when checking later dependent project references in the same run.

**Comment by sheetalkamat** [comment]
This is working as intended and something to do with how the repro is setup.
In your example packages `a` and `b` do not depend on each other so they have their own set of files and the errors are reported for each project. Note that we do not deduplicate errors between projects. So error reported are from two different projects.

```
C:\temp\ts-type-rerun-repro\access-source-examle>node c:\TypeScript\built\local\tsc.js -b --explainFiles -v
[3:08:54 PM] Projects in this build:
    * packages/b/tsconfig.json
    * packages/a/tsconfig.json
    * tsconfig.json

[3:08:55 PM] Project 'packages/b/tsconfig.json' is out of date because output file 'typecheck_cache/b/b.d.ts' does not exist

[3:08:55 PM] Building project 'C:/temp/ts-type-rerun-repro/access-source-examle/packages/b/tsconfig.json'...

packages/b/b.ts:2:9 - error TS2322: Type 'string' is not assignable to type 'number'.

2   const number: number = "1";
          ~~~~~~

../../../TypeScript/built/local/lib.d.ts
  Default library for target 'es5'
../../../TypeScript/built/local/lib.es5.d.ts
  Library referenced via 'es5' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.dom.d.ts
  Library referenced via 'dom' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.webworker.importscripts.d.ts
  Library referenced via 'webworker.importscripts' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.scripthost.d.ts
  Library referenced via 'scripthost' from file '../../../TypeScript/built/local/lib.d.ts'
packages/b/b.ts
  Matched by include pattern '**/*' in 'packages/b/tsconfig.json'
[3:08:57 PM] Project 'packages/a/tsconfig.json' is out of date because output file 'typecheck_cache/a/a.d.ts' does not exist

[3:08:57 PM] Building project 'C:/temp/ts-type-rerun-repro/access-source-examle/packages/a/tsconfig.json'...

packages/b/b.ts:2:9 - error TS2322: Type 'string' is not assignable to type 'number'.

2   const number: number = "1";
          ~~~~~~

../../../TypeScript/built/local/lib.d.ts
  Default library for target 'es5'
../../../TypeScript/built/local/lib.es5.d.ts
  Library referenced via 'es5' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.dom.d.ts
  Library referenced via 'dom' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.webworker.importscripts.d.ts
  Library referenced via 'webworker.importscripts' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.scripthost.d.ts
  Library referenced via 'scripthost' from file '../../../TypeScript/built/local/lib.d.ts'
packages/b/b.ts
  Imported via 'b' from file 'packages/a/a.ts' with packageId 'b/b.ts@1.0.0'
packages/a/a.ts
  Matched by include pattern '**/*' in 'packages/a/tsconfig.json'
[3:08:57 PM] Project 'tsconfig.json' can't be built because its dependency 'packages/b' has errors

[3:08:57 PM] Skipping build of project 'C:/temp/ts-type-rerun-repro/access-source-examle/tsconfig.json' because its dependency 'C:/temp/ts-type-rerun-repro/access-source-examle/packages/b' has errors


Found 2 errors.
```

When you fix error and then reintroduce, only error from project `b` is reported. Because of how you have setup `a` to not reference `b` and still picking up files from the `b` in your program which are not listed in the project for `a`'s upto date check only `a.ts` and its output plays a role and not file `b` in `node_modules` so a is assumed to be upto date. (note how in above build log for project `a`, `b.ts` is included through import and not because of tsconfig.

```
C:\temp\ts-type-rerun-repro\access-source-examle>node c:\TypeScript\built\local\tsc.js -b --explainFiles -v
[3:11:34 PM] Projects in this build:
    * packages/b/tsconfig.json
    * packages/a/tsconfig.json
    * tsconfig.json

[3:11:34 PM] Project 'packages/b/tsconfig.json' is out of date because oldest output 'typecheck_cache/b/b.d.ts' is older than newest input 'packages/b/b.ts'

[3:11:34 PM] Building project 'C:/temp/ts-type-rerun-repro/access-source-examle/packages/b/tsconfig.json'...

packages/b/b.ts:2:9 - error TS2322: Type 'string' is not assignable to type 'number'.

2   const number: number = "1";
          ~~~~~~

../../../TypeScript/built/local/lib.d.ts
  Default library for target 'es5'
../../../TypeScript/built/local/lib.es5.d.ts
  Library referenced via 'es5' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.dom.d.ts
  Library referenced via 'dom' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.webworker.importscripts.d.ts
  Library referenced via 'webworker.importscripts' from file '../../../TypeScript/built/local/lib.d.ts'
../../../TypeScript/built/local/lib.scripthost.d.ts
  Library referenced via 'scripthost' from file '../../../TypeScript/built/local/lib.d.ts'
packages/b/b.ts
  Matched by include pattern '**/*' in 'packages/b/tsconfig.json'
[3:11:35 PM] Project 'packages/a/tsconfig.json' is up to date because newest input 'packages/a/a.ts' is older than oldest output 'typecheck_cache/a/a.d.ts'

[3:11:35 PM] Project 'tsconfig.json' can't be built because its dependency 'packages/b' has errors

[3:11:35 PM] Skipping build of project 'C:/temp/ts-type-rerun-repro/access-source-examle/tsconfig.json' because its dependency 'C:/temp/ts-type-rerun-repro/access-source-examle/packages/b' has errors


Found 1 error.
```

**Comment by Akiyamka** [comment]
@sheetalkamat could not look at this problem again, it seems to me the author has not fully revealed the essence of the problem.
I have the following situation:
```
my-monorepo
|- packages
   |- pacakge-one    <- use  pacakge-three as import pacakgeThree from '@my-monorepo/pacakge-three'
   |- pacakge-two    <- use  pacakge-three as import pacakgeThree from '@my-monorepo/pacakge-three'
   |- pacakge-three  <- have typing error
```
In that case `tsb -b` report error in pacakge-three x3 times.
even with 
```
"skipLibCheck": true,
"exclude": [ "node_modules"]
```
This makes me very frustrating and does not at all correlate with what I expect from such a configuration.
