### ISSUE TITLE
TS1005 errors for non javascript files (.cshtml)

### ISSUE THREAD

**Issue by dotnetshadow** [microsoft/TypeScript#42391]
# Bug Report
Get a warning when adding a certain javascript snippet
Warning TS1005 (JS) ‘;’ expected. Foo.Web JavaScript Content Files

### 🔎 Search Terms
TS1005

### 🕗 Version & Regression Information

Using visual studio 2019 16.8.5 Typescript version 4.1.2

### 💻 Code

When I add the following code to my .cshtml file I get
Warning TS1005 (JS) ‘;’ expected. Foo.Web JavaScript Content Files

```
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div class="tradingview-widget-container__widget"></div>
  <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/markets/stocks-usa/" rel="noopener" target="_blank"><span class="blue-text">Stock Market Today</span></a> by TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-hotlists.js" async>
  {
  "colorTheme": "light",
  "dateRange": "12M",
  "exchange": "US",
  "showChart": true,
  "locale": "en",
  "largeChartUrl": "",
  "isTransparent": false,
  "showSymbolLogo": false,
  "width": "400",
  "height": "600",
  "plotLineColorGrowing": "rgba(33, 150, 243, 1)",
  "plotLineColorFalling": "rgba(33, 150, 243, 1)",
  "gridLineColor": "rgba(240, 243, 250, 1)",
  "scaleFontColor": "rgba(120, 123, 134, 1)",
  "belowLineFillColorGrowing": "rgba(33, 150, 243, 0.12)",
  "belowLineFillColorFalling": "rgba(33, 150, 243, 0.12)",
  "symbolActiveColor": "rgba(33, 150, 243, 0.12)"
}
  </script>
</div>
<!-- TradingView Widget END -->
```

You can see documentation here:
https://www.tradingview.com/widget/market-movers/

### 🙁 Actual behavior

Warning TS1005 (JS) ‘;’ expected. Foo.Web JavaScript Content Files
![image](https://user-images.githubusercontent.com/296247/104876950-d05dfe80-59ac-11eb-8fbb-e961334a5d9d.png)

### 🙂 Expected behavior

There shouldn't be any errors, it's not a typescript file, furthermore no option is given to me so that I can suppress the error

**Comment by RyanCavanaugh** [comment]
This is a correct error in the context of a JavaScript script block. Starting with an `{` like that introduces a statement block, not an object literal - put parentheses around the whole thing if you want it to be an object.

**Comment by dotnetshadow** [comment]
Yep I see, thanks for that

**Comment by Abidjon** [comment]
No, this is not a solution, wrapping parentheses indeed removes TS error warnings but it is because it just ignores what is inside that wrapping and widget uses default predefined values
