### ISSUE TITLE
Union type variable in generic can produce unexpected union types.

### ISSUE THREAD

**Issue by 07akioni** [microsoft/TypeScript#42397]
# Bug Report

### 🔎 Search Terms

Generics, Union

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- [x] This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____Generics____
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3&ssl=16&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgEoRgHgCrILzJwgCeAfMgN4BQytyAbnADYCuEAXMtlQL5VVhiABxTYA9uizZyBXBAAekEABMAzmgzIA-F2SdJOUvwD0x5AFF5IhJGXIwY5ACMUB1WCigA5sgA+yEBYAWxcocicWMEIbFmYmYg0sd08QL3J-A0CQ6CNBEWR5fC4JDExk7z8A4NCjKmUIBCY4KBQYFhAbYDEQZAB3ODAEAAtDAApVMRYoJH1S6QBKTnoxYGV+fsGh0YAGQnV2gGsQMV6euHU3Dwr-LJr55FNkMQOTMwBZOAOUDeHkBCIAORRRBIIRRMBDVwYKg-La7c7IQ7HU57Ar3R7HKLPKhAA)

### 💻 Code

```ts
interface Ref<T = any> {
    value: T
}

type ToRef<T> = T extends Ref ? T : Ref<T>

// Expected to be Ref<string | number> but actually Ref<string> | Ref<number>
type x = ToRef<string | number>

declare function watch<T>(source: Ref<T>): void

watch(0 as unknown as Ref<string | number>) // ok

// Make watch can't accept the Ref
watch(0 as unknown as x) // not ok

```

### 🙁 Actual behavior
`x` is  `Ref<string> | Ref<number>`

### 🙂 Expected behavior
Expect `x` to be `Ref<string | number>`

**Comment by MartinJohns** [comment]
This is working as intended. You got struck by [Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types). The documentation explains this behavior and also shows a way to prevent it.

**Comment by 07akioni** [comment]
> This is working as intended. You got struck by [Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types). The documentation explains this behavior and also shows a way to prevent it.

Thanks!

**Comment by 07akioni** [comment]
Sorry I still have some problems. Can I make last two lines work at the same time?

[link](https://www.typescriptlang.org/play?ts=4.1.3&ssl=1&ssc=1&pln=20&pc=1#code/JYOwLgpgTgZghgYwgAgEoRgHgCrILzJwgCeAfMgN4BQytyAbnADYCuEAXMtlQL5VUATCAiZwoKGCxAIwwAPYhkU8VmykAFCs7YAlNuQQAHpBACAzmgyZQMaMgBq5APwPk2wcNHjkk6bIXIKjgGxhCmFnIARgBWwmAajKwcXHpccuiqpB4iYhJSMvKKAO5wYAgAFjgaZnIsUEicGVWp9HLAAtleeX6FIQAOcdjEA1XqiWzaLW0dVAD0s8gIcGYoAIxUYMMo2OlWavjIANrYALohJuaWMMguuI17WXMLSyvIAExPyJsDaU37BLgjBcLBkblw3Fcqvx5sgALJwADWKDA5QgAFtkJE5CjkEU5FAEU4qCUyuV1AAGQgWKQIkByIqKZa-KxmMBQUAAc2QAB9kCAWGjItBSDpkDCXig3nzscg5AiqEYBjIhiNDvzBdAADTIVnskAck4aZQYTQmw6rbUAclWlpOOntYueyzW0rAsvlVCAA)

```ts
interface Ref<T = any> {
    value: T
}

declare function unref<T>(ref: T): T extends Ref<infer V> ? V : T
declare function ref<T extends object>(value: T): ToRef<T>
declare function watch<T>(source: Ref<T>): void
declare function expectType<T>(value: T): void

// case 1
type ToRef<T> = [T] extends Ref ? T : Ref<T>

// case 2
// type ToRef<T> = T extends Ref ? T : Ref<T>

// Make them both work?
watch(0 as unknown as ToRef<string | number>) // case 2 not ok
expectType<[number, string]>(unref(ref([1, '1']))) // case 1 not ok
```

If I create `x = unref(ref[1, '1'])` outside `expectType`, `x` will always be inferred as `(string | number)[]` (in both case). Why in the function `expectType` it has different behaviors and can be inferred as `[number, string]`?
