### ISSUE TITLE
Require been ignord for emitDecoratorMetadata if module is unused and name is lowercase

### ISSUE THREAD

**Issue by tjoskar** [Microsoft/TypeScript#4239]
If an imported module is unused it will be ignored, which is good (It may exist edge cases where this is bad but that is an other discussion).

```javascript
import {db} from './db'
console.log('Hello Dexter Morgan');
```
Compiles to:
```javascript
console.log('Hello Dexter Morgan');
```
(One can of course, `import './db'` to keep it).

But this becomes a problem if I use `emitDecoratorMetadata` and a decorator:

```javascript
import {db} from './db';

function someDecorator(target) {
    return target;
}

@someDecorator
class MyClass {
    db: db;

    constructor(db: db) {
        this.db = db;
        this.db.doSomething();
    }
}

export {MyClass};
```

This compiles to:
```javascript
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
    switch (arguments.length) {
        case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
        case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
        case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
    }
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
function someDecorator(target) {
    return target;
}
var MyClass = (function () {
    function MyClass(db) {
        this.db = db;
        this.db.doSomething();
    }
    MyClass = __decorate([
        someDecorator, 
        __metadata('design:paramtypes', [db_1.db]) // db_1 is not defined
    ], MyClass);
    return MyClass;
})();
exports.MyClass = MyClass;
```

And if a run this code I get `ReferenceError: db_1 is not defined`.

The funny thing is however that this code works:

```javascript
import {db as Database} from './db';

function someDecorator(target) {
    return target;
}

@someDecorator
class MyClass {
    db: Database;

    constructor(db: Database) {
        this.db = db;
        this.db.doSomething();
    }

}

export {MyClass}
```

If I import the database class with `import {Database} from './db';` it works as well. So it seams like the compiler ignore to import a module if its name is in lower case? 

I'm using version `1.6.0-dev.20150808` of `tsc`.

**Comment by sheetalkamat** [comment]
Understood the issue here. When trying to resolve db as value because we are going to reference parameter type, db is resolved to parameter named db instead of the import alias named db. I am working on the fix. Thanks for reporting the issue.

**Comment by mhegazy** [comment]
@tjoskar sorry for the delay. can you give `typescript@next` a try tonight and see if this emits the correct code now.

**Comment by tjoskar** [comment]
Thanks for looking into the issue.
I just upgraded `tsd` to the latest version:
```
❯ tsc --version
message TS6029: Version 1.6.0-dev.20150824
```

But the issue remande. I may however wait a few more hours for `Version 1.6.0-dev.20150825`. Time zones can be a problem sometimes.

**Comment by mhegazy** [comment]
@tjoskar, `1.6.0-dev.20150825` is the one with the fix.
