### ISSUE TITLE
Cannot access the globalThis namespace

### ISSUE THREAD

**Issue by juanrgm** [microsoft/TypeScript#42395]
# Bug Report

### 🔎 Search Terms

root namespace, namespace collision

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about namespaces

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAXAngBwQIXgXngRgFgAoUSWBMgZ0vgGF4BvAX2NOjngDsoBbES1FDAIAgo2LxJ8EAA9UAexiIkaTDngBzCPIBGUCABUAFgEtKAOiwB6K-BPKA7ooDWlCVNkKl8KjXqzEEE5gGi1dfWMzc3pmeBt4AAUYeXQlZHgAcloM+GB5fi55ZVkzZXlOFXRMlHR5ADNNbT1DU0oM82ImIA

### 💻 Code

```ts
declare type B = 1
declare class C {}
declare namespace A {
    export type B = globalThis.B // It works
    export class C extends globalThis.C {} // Property 'C' does not exist on type 'typeof globalThis'.
}
```

### 🙁 Actual behavior

```Property 'C' does not exist on type 'typeof globalThis'.```

It is not possible access to the root namespace.

### 🙂 Expected behavior

Be able to access to the root namespace.

**Comment by whzx5byb** [comment]
related: https://github.com/microsoft/TypeScript/issues/39504

**Comment by sandersn** [comment]
Thanks for the link @whzx5byb! There, @ExE-Boss points out that this is how JS works -- classes aren't accessible from globalThis.

You can work around for normal values by using a class expression:

```ts
var C = class { }
```

For ambient declarations, you have to create an old-style interface/value merger:

```ts
interface CStatic {
    new(): C
}
interface C {
    m1(): number
    a1: number
}
declare var C: CStatic
```
