### ISSUE TITLE
NodeList, NodeListOf<Element> and HTMLCollection

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/TypeScript#424]
Currently, the following DOM methods has a return type definition of <code>NodeList</code>, but the type of nodes returned is actually always <code>Element</code>:

<code>getElementsByClassName</code>
<code>getElementsByTagNameNS</code>
<code>getElementsByTagName(name: string)</code>
<code>getElementsByName</code>
<code>msElementsFromPoint</code>
<code>msElementsFromRect</code>

As a result, a cast to <code>Element</code> is required before any method of <code>Element</code> can be used. To remove the need of the cast, I suggest changing their return type definition to <code>NodeListOf&lt;Element></code>.

Also, there are some HTML DOM properties (e.g. <code>document.forms</code>) having a return type definition of  <code>HTMLCollection</code>, but <code>HTMLCollection</code> does not extend <code>NodeListOf&lt;HTMLElement></code>. That leads to some difficulties in creating a method that takes a list of elements. I suggest changing <code>HTMLCollection</code> to extend <code>NodeListOf&lt;HTMLElement></code>.

Finally, should a <code>List&lt;T></code> interface with the following definition be created, such that <code>Array&lt;T></code>, <code>NodeList</code>, <code>NodeListOf&lt;HTMLElement></code> and <code>HTMLCollection</code> all extend to <code>List&lt;T></code>?

<pre><code>interface List<T> {
    length: number;
    [index: number]: T;
}</code></pre>

**Comment by duanyao** [comment]
In many cases, we want certain sub-interface of `Element` to be returned from those DOM APIs.

Firstly, I suggest making those API as generic methods, e.g.:

```javascript
interface NodeSelector {
  querySelector<E extends Element>(sel : string): E;
  querySelectorAll<E extends Element>(sel : string): NodeListOf<E>;
  //...
}
```

Additionally, I suggest making the non-generic versions return a `UniversalElement` or a list of it. `UniversalElement` is an additional interface that extends all known sub-interfaces of `Element`. Say:

```javascript
interface UniversalElement extends
  HTMLAElement,
  HTMLInputElement,
  //...
  SVGLineElement,
  SVGRectElement,
  //...
 {}

interface NodeSelector {
  //...
  querySelector(sel : string): UniversalElement;
  querySelectorAll(sel : string): NodeListOf<UniversalElement>;
}
```

Rationales:

* `UniversalElement` makes most type assertions unnecessary in DOM related codes, so that greatly simplifies those codes.
* APIs like `querySelector` can actually return any sub type of Element, depending on the parameter and context, so it is not that crazy to let them return `UniversalElement` by default.
* This change won't break existing (correct) code.
* Maybe `UniversalElement` makes it easier for developers to produce type errors in rare cases (I haven't figured out one however), but they can use the generic version of those API to narrow-down the return type if necessary.

**Comment by mhegazy** [comment]
PRs welcomed, here is some information about submitting lib.d.ts changes: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by crash-dive** [comment]
I am happy to add this. But I need to know what would be accepted. I was thinking of adding a new type modelled on NodeListOf called HTMLCollectionOf and then adding generic methods for the collection methods. For example I have these in the project I have open at the moment:

```javascript
interface Document
{
    getElementById<THTMLElement extends HTMLElement>(elementId: string): THTMLElement;
    getElementsByClassName<THTMLElement extends HTMLElement>(classNames: string): NodeListOf<THTMLElement>;
}

interface Element
{
    getElementsByClassName<THTMLElement extends HTMLElement>(classNames: string): NodeListOf<THTMLElement>;
}

interface NodeSelector {
    querySelector<THTMLElement extends HTMLElement>(selectors: string): THTMLElement;
    querySelectorAll<THTMLElement extends HTMLElement>(selectors: string): NodeListOf<THTMLElement>;
}
```

Not an exhaustive list but just an example I have to hand.

Thoughts?

**Comment by mhegazy** [comment]
@crash-dive this looks like can be handled in a separate PR. the OP was about 1. adding a new `HTMLCollectionOf<T extends HTMLElement> extends HTMLCollection` and wiring this in the correct placeds.  2. switch `msElementsFromRect` and `msElementsFromPoint` to return `NodeListOf<Element>`, and possibly others that match their style. and 3. make `NodeList`, `NodeListOf`, `HTMLElementCollection`, `HTMLElementCollectionOf` to extend from `ArrayLike`

**Comment by FranklinWhale** [comment]
A PR has been submitted for adding HTMLCollectionOf. There will be another PR for  msElementsFromRect  and  msElementsFromPoint later. For #3, I think an explicit extension of  ArrayLike is not necessary because of structural typing.

**Comment by FranklinWhale** [comment]
A [second PR](https://github.com/Microsoft/TSJS-lib-generator/pull/83) for this issue has been made. I note that [`form.elements`](https://www.w3.org/TR/html5/forms.html#dom-form-elements) should be changed to return [`HTMLFormControlsCollection`](https://www.w3.org/TR/html5/infrastructure.html#htmlformcontrolscollection-0), but that change, in my view, should be tracked by another issue.  I think this issue may be closed after the second PR is accepted.

**Comment by kumaresan-subramani** [comment]
`onreset(element: MouseEvent) : void {
        let parentNode: NodeListOf<HTMLElement> = document.getElementsByClassName('box-form')[0].querySelectorAll('.e-float-text');
        for (let i: number = 0; i < parentNode.length; i++) {
            parentNode[i].classList.remove('e-label-top');
            parentNode[i].classList.add('e-label-bottom');
        }
    }`

**this is my code, in this case i met following error**

_Type 'NodeListOf<Element>' is not assignable to type 'NodeListOf<HTMLElement>'.

  Type 'Element' is not assignable to type 'HTMLElement'.

    Property 'accessKey' is missing in type 'Element'._
