### ISSUE TITLE
Expose the jsdoc field in the AST without @internal.

### ISSUE THREAD

**Issue by Raynos** [microsoft/TypeScript#42407]
# Suggestion

Currently the `jsDoc` field on `JSDocContainer` is marked as `@internal`.

It would be nice to be able to use the `jsDoc` field in linting tools like `eslint` in custom rules.

here's an example where the `jsDoc` field is used ( https://github.com/typescript-eslint/typescript-eslint/issues/2939#issuecomment-762491546 ).

## 🔍 Search Terms

jsDoc, jsdoc, internal

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Remove the `@internal` declaration on the `jsDoc` field.

## 📃 Motivating Example

https://github.com/typescript-eslint/typescript-eslint/issues/2939#issuecomment-762491546

## 💻 Use Cases

To be able to use the `jsDoc` field without casting in linting rules.

**Comment by ajafff** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/7393

There's a function `getJsDoc` in my package `tsutils` that does exactly what you want: https://github.com/ajafff/tsutils/blob/752e8024003afc23c55f1fae8fbfb015068b9c10/util/util.ts#L1226

**Comment by Raynos** [comment]
Awesome, that resolves this issue.
