### ISSUE TITLE
Optional Chaining does not work with generic this parameter

### ISSUE THREAD

**Issue by osyrisrblx** [microsoft/TypeScript#42404]
# Bug Report

### 🔎 Search Terms

optional chain, generic, this, method

### 🕗 Version & Regression Information

Bug started in TypeScript 3.7.
- I was unable to test this on prior versions because optional chaining did not exist before 3.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgBrIN4Chm+TAewIB4AVAPgAowALYAZwC5lSAaZOKAc2YGsIAngRgsAlMwBuBYABMA3FgC+WLKEixEKAJrIIAD0ggZ9NJhx44zEAFcAtgCNoCvMnvN6YKKC4LlWGRAIADacKAgEIB7IEnBB1hDMOgA+yNZGEDCgEPIqAPS5yLQMyADuBFC89KoilDFxEKJmLnXxAPwAdIQElABEcD2ivnkFRSYyBBD0IADkYFgtEB1dvf2DyPnIAILcdhDgyMKFAgAOKNMeXiBc08jFIARgHPT0wFwgcPZBKGAEyMeccFsEHUBxEYBOZxAEAk0Gm7SwQA)

### 💻 Code

```ts
interface X {
    foo<T>(this: T, arg: keyof T): void;
}

interface Y extends X {
    a: number;
    b: string;
}

declare const value: Y | undefined;

// this works
if (value) {
    value?.foo("a");
}

// this doesn't
value?.foo("a"); // Argument of type 'string' is not assignable to parameter of type 'never'.
```

### 🙁 Actual behavior

Generic `T` is not resolved. `keyof T` results in `never`.

### 🙂 Expected behavior

Generic `T` should resolve to `Y` so that `keyof T` resolves to `"a" | "b" | "foo"`.

**Comment by RyanCavanaugh** [comment]
Repros without inheritance
```ts
interface Y {
    foo<T>(this: T, arg: keyof T): void;
    a: number;
    b: string;
}

declare const value: Y | undefined;

// this works
if (value) {
    value?.foo("a");
}

// this doesn't
value?.foo("a");
```
