### ISSUE TITLE
Indirect type narrowing

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#42402]
# Suggestion

## 🔍 Search Terms

Generics, type dependencies, control flow type, control flow, type assertions, type deduction, type narrowing

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It would be great if TS could narrow the type of another value (variable, parameter, etc), if it depends on another value whose type has already been narrowed.

I'm suggesting that TSC deduct generic parameters that depend on other generic types through control flow analysis.

Essentially, type narrowing of other values, yet indirectly.

```ts
function plusOperator<T extends number | string>(x: T, y: T): T {
	if ( typeof x === "number" ) {
		const sum: number = x + y;
		return sum;
	} else {
		const concatenation: string = x + y;
		return concatenation;
	}
}
```

## 📃 Motivating Example

This allows narrowing the types of variables en masse.

## 💻 Use Cases

I want this so that I could leverage TS's type system to remove redundant type checks in my code.
Currently, if two values are of the same type, and one wants to treat narrow their types, they must all be narrowed individually.
In the meanwhile, I'm narrowing individually.

```ts
function f<T extends number | undefined>(x: T, y: T extends number ? number : undefined): number {
	return typeof x === "number" // x: number
		? y // therefore y: number
		: 0;
}
```

It would also allow code like this,
```ts
function f<T extends number | string>(x: T) {
    const a: T = x;
    const b: T = x;
	if ( typeof a === "string" ) { // T: string
		const assert: string = b; // b: T, therefore b: string
	}
}
```
to work now.

This could affect more than just generics, for example, it might allow code like that in [this SO question](https://stackoverflow.com/questions/65724972) to function, without changing the implementation.

**Comment by MartinJohns** [comment]
You're wrongly assuming that `T extends number | undefined>` means that `T` is either a `number` **or** `undefined`, but `T` can be of type `number | undefined` as well. So what you suggest would simply be unsafe, because the arguments of `x` and `y` can be of different types even when they're both `T`.

**Comment by jcalz** [comment]
Looks like #13995

**Comment by 00ff0000red** [comment]
@MartinJohns What about `function f<T extends number | undefined>(x: T, y: T extends number ? number : T extends undefined ? undefined : never)`? If `T` is `number | undefined`, then `y`'s type should be `never`, right?

**Comment by 00ff0000red** [comment]
@jcalz Ah, it does share a bit with that, but it's slightly different. I'm thinking about rewriting this with the intent of focusing on the SO that I had linked, and explaining why it would be helpful for TS, should I close this and open another, or just rewrite this post?

**Comment by MartinJohns** [comment]
@00ff0000red You could have simply tested this.

	type Test<T> = T extends number ? number : T extends undefined ? undefined : never
	type Assert = Test<number | undefined>

The type `Assert` resolves to `number | undefined`.

**Comment by 00ff0000red** [comment]
@MartinJohns Indeed, https://github.com/microsoft/TypeScript/issues/27808 is very close to part of what I am suggesting here. I'll close this and open a new, very different suggestion.
