### ISSUE TITLE
TS2376 doesn't comply with ECMAScript

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#42400]
# Bug Report

### 🔎 Search Terms

First statement must be super

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about super calls in classes

### ⏯ Playground Link

Couldn't provide a link, TS playground wasn't working, I've opened https://github.com/microsoft/TypeScript-Website/issues/1506

### 💻 Code

```ts
class T extends Number {
	x = 0; // use class instance field
	constructor(n: number) {
		const temp = n ** n; // do something
		super(temp); // not first statement
	}
};

console.log(new T(10).valueOf());
```

### 🙁 Actual behavior

TSC raises error TS2376, claiming that super calls must be the first statement in a class, if a class uses the class instance field.

### 🙂 Expected behavior

TSC removes the `: number`, and ends process.
Removing type annotations, this is otherwise perfectly valid ES.

___

Possibly related to https://github.com/microsoft/TypeScript/issues/6908

**Comment by RyanCavanaugh** [comment]
Duplicate #8277
