### ISSUE TITLE
suggestion for improvement of the error message: `No overload expects 2 arguments, but overloads do exist that expect either 2 or Infinity arguments.` even if there is no definitions that take Infinity arguments

### ISSUE THREAD

**Issue by uraway** [microsoft/TypeScript#42418]
# Bug Report

### 🔎 Search Terms

argument count error

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `overload`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQAoA3ARgC55VkBbAIxBgEpLictgBuAKFElgQp02PARIUqtBjAA08YgCZK1eoxbz2XXuGhwkaTLnyIiZZVMZzF51bPkBmG9PVsOPbmDwBnDPFgx4AF54AG0ABgBdbhNCADp4-zlSJngAelT4AFEADwAHcAwQYHhSAFp7PxgAc1oQVAwvOTpkXyqcX1J4HACabpBYwgUAViGANiZoonjYxJK5BRT0+AA5HC7iRggcKGKQPIKveAVKmpo6hqaW9c3t4EPgNb2sH3gMAAsoXz38zHgQLHejCOXQCAElUIgsKgAQBPE61epeAbDADsQyYQA)

### 💻 Code

```ts
declare function fn(v1: number): void;
declare function fn(v1: number, v2: number): void;
declare function fn(v1: number, v2: number, v3: number): void;

const arr = [0]
fn(...arr, 1, 2) // No overload expects 2 arguments, but overloads do exist that expect either 2 or Infinity arguments. (2575)
```

### 🙁 Actual behavior

The error message is
```
No overload expects 2 arguments, but overloads do exist that expect either 2 or Infinity arguments. (2575)
```

I understand this part: `No overload expects 2 arguments` because the first argument is potentially empty. 
However, I do not define a function that takes `Infinity arguments`, though the error message tells so.

### 🙂 Expected behavior

The error message should be something like
```
Expected 1-3 arguments, but got 2 or more.(2556)
```

since if I use `fn` like below, TypeScript says `Expected 1-3 arguments, but got 1 or more.(2556)`

```ts
fn(...arr, 1) 
```

**Comment by MartinJohns** [comment]
Your `arr` is an array with arbitrary amount of elements. It works correctly if you use a tuple.

    const arr = [0] as const
    fn(...arr, 1)
    fn(...arr, 1, 2)

**Comment by uraway** [comment]
@MartinJohns I know the implementation of its workaround. What I wanted to say here is the error message is contradictory to my overload definitions in the code.

This issue is for a suggestion for improvement of the error message.

**Comment by AlCalzone** [comment]
> I understand this part: No overload expects 2 arguments because the first argument is potentially empty.

I actually don't. The second overload does accept two arguments.

So IMO the message should point out that there are overloads that accept 2 or 3 arguments, but none that accept more. (If that is even a problem)
