### ISSUE TITLE
The readme gulp table is hard to read

### ISSUE THREAD

**Issue by pouyakary** [microsoft/TypeScript#42410]
# Suggestion

The readme gulp table was really hard to read for me and so I cleaned it up. In [this pr](https://github.com/microsoft/TypeScript/pull/42408) I have fixed the problem.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Honestly, the current version is both readable in plain text and as a markdown preview, whereas your improved version is much more difficult to read in plain text. Plus some of the lines look really weird:

![image](https://user-images.githubusercontent.com/5269069/105084506-b7317c80-5a96-11eb-83bd-0d73ca7e8cc6.png)

The grayed color makes it difficult to read even in markdown preview view.

**Comment by RyanCavanaugh** [comment]
We really don't want that table taking up that much vertical space there. The format as-is is good enough.
