### ISSUE TITLE
Javascript: Variable Unreferenced when += is Used

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/TypeScript#42422]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Javascript:-Variable-Unreferenced-when-/1314511)._

---
[severity:It bothers me. A fix would be nice]
In Javascript, when I use _**variable += 'string'**_ with a string variable that has been initialized, that does not change the variable declaration color from gray to white, to indicate it has been referenced. When I change it to variable = variable + 'string', the syntax highlighter works correctly, and changes the variable declaration color to white. Please see screenshots attached.

---
#### Feedback Bot on 1/19/2021, 09:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. If you only ever compound-write to a variable, it's still never *read* in any true sense.
