### ISSUE TITLE
Add exactly empty object ({} literal) type

### ISSUE THREAD

**Issue by emiliskiskis** [microsoft/TypeScript#42426]
# Suggestion
Add an empty object (`{}` literal) type

## 🔍 Search Terms

empty interface object type react

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Right now, TypeScript does not have a way to define a `{}` literal type, because `{}` is an object with no properties and all non-nullish values have at least no properties [https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces)

It would be useful to define a type that meant an empty object literal, where you want to specify that an object has to be passed, but it must contain no properties (primarily in JSX and React for no props).

## 📃 Motivating Example

Right now I have a bunch of components that look like this:
```jsx
export const LayoutComponent = (props: React.PropsWithChildren<{}>) => {
  return (
    <WrapperComponent>
      {...props.children}
    </WrapperComponent>
  )
}
```
or this:
```jsx
export const ExampleComponent = (props: {}) => {
   return <div>Static component</div>
}
```

## 💻 Use Cases

Obviously, the `{}` constraint does not mean that an object must be passed, which is not what I really mean when I write this code. Right now I have no way of describing a type that says that an empty object with no additional properties must be passed, except for `{ [key: string | number | symbol]: any }`, which would mean I accept any object.

**Comment by RyanCavanaugh** [comment]
You can write this already:
```ts
export const ExampleComponent = (props: { [n: string]: never }) => {
   return <div>Static component</div>
}

const props = { m: "hello" };
// Errors
let err = <ExampleComponent {...props} />;
// OK
let ok = <ExampleComponent />;
```
or is your use case something else? I didn't see any "this should error" examples given so I'm not 100% sure what you're going for.

**Comment by emiliskiskis** [comment]
You gave a great example for my use case. I guess I can use `{ [key: string]: never }`, but maybe it could be defined globally as `Empty`?..

**Comment by emiliskiskis** [comment]
Though literally just as I finished writing this comment, I went out and wrote `React.PropsWithChildren<{ [key: string]: never}>` and got an error that the types are incompatible, because in `PropsWithChildren<P> = P & { children?: ReactNode }`, `{ [key: string]: never}` and `{ children? ReactNode }` cannot intersect. I would instead like in that case to have the intersection result to be `P`.

**Comment by RyanCavanaugh** [comment]
Really sounds like you want #12936

**Comment by emiliskiskis** [comment]
`Exact<T>` sounds promising, but then wouldn't this be the same problem with `{}` in `Exact<{}>` still refer to any non-nullish value?

**Comment by RyanCavanaugh** [comment]
No, I don't think so. An "exact" `{}` would have to be statically-known to not have any properties

**Comment by emiliskiskis** [comment]
If that's the case, then I'm closing this issue and subscribing to 12936. Thanks a lot for the help.

**Comment by ejose19** [comment]
@RyanCavanaugh how would one do in this case?

```ts
const obj1 = {};
const obj2 = { bar: '' };
const obj3: { bar?: string } = { bar: '' };

obj1 as { [n: string]: never }; // No error, expected
obj2 as { [n: string]: never }; // Error, expected
obj3 as { [n: string]: never }; // No error, unexpected
 ```

I've tried with many combinations of ```Record``` as well to not avail, being the only "workaround" doing another assert in the middle: 
```ts
(obj3 as Required<typeof obj3>) as { [n: string]: never }; // Error is correctly detected
```

However if there's a direct solution for this it would be preferred.

**Comment by wchargin** [comment]
> `{ [key: string]: never }`

I've been using `type EmptyObject = Record<string, never>` for a while, but today I ran into a problem with it.

I had some old code like this:

```typescript
interface Status {
  success: boolean;
}

interface SomeMessage {
  contents: Status;
}

// In a different file...
const processMessage = (message: SomeMessage) => {
  const { success } = message.contents;
  console.log("success:", success);
}
```

Then I changed the type of `contents` from `Status` to `EmptyObject`. This should have caused a type error in `processMessage`, because `success` is not a property on `EmptyObject`. But instead it went undetected, and this hid a real bug because `processMessage` was now supposed to detect errors in a different way and I was trusting TypeScript to tell me that.

Switching from `Record<string, never>` to `Record<never, never>` would have caught this issue. But that seems to fail in a dual way, because `{ a: 1 }` is assignable to `Record<never, never>` (‽). I don't see a way to use union or intersection types to form a type that satisfies the two desired properties:

1.  You can't assign any fields to it.
2.  You can't read any fields from it.
