### ISSUE TITLE
TS won't spread mapped tuple type as rest params in function arguments

### ISSUE THREAD

**Issue by martaver** [microsoft/TypeScript#42435]
# Bug Report

### 🔎 Search Terms

mapped tuple types, spread operator, rest params

### 🕗 Version & Regression Information

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwsD2AnKBeKBvKA7CB3AFAHTECGiA5gM4BcUJWIA2gLoCUtA8gEYBWEAxsAC+AbgCwAKFCRYCRAAUyJALaUAPABUAyvACuifhBgAbEpUpQIAD2AQsAEwtwkAPlRRteg0dPnLNu0cMbDwiUgoaKABLLAAzCGQAVXYobj5BISgAfihEqFocADcE8QlJaWgAGRIALxBFRBV1T31DEzMLa1sHJzkAGigGpvdnBSVVTR1Wnw6XNzR0SSgoRgBJaKwoAGsIEHhYwfHKZloh1TXmKAAfKHx8VlQ3M8oL1lLRSUl+eCxKYChItU6s81KN5isAIzMUqSWK6LCCKI-KC6SgQTSjfzdIJg-DLJZQQRIWgaUZ9AnEQhkKi0IH1I4YuQuSQPdBCT5lCT8XwWACyIHafkWEmWy2+v2AiF0RMQ+GUIAAghQCrplFwEqz2RItZIAPS6jzgaBRCwkKDAXRgYwQAaUeBQewQWIxKK2YwgAFgRAQEj2Ehca2U80AC2gFU6xU2uCQWzoFmAoboFFVdmAlEIeoNOiguGDHoT0H98GKlkQiCQUGRBaglOplCyHNREHw-MFlAGELemZRaJbAp5AwA5IO3lB9VAAKJlitmfyQQQQeySJt9tsDe6PKCd0rjletge3B4oNzD0fjqfl5Cz6zz2z2IA)

### 💻 Code

```ts
type Ctor = { new(...args: any[]): Object};
type CtorParams<TSourceClass extends Ctor> = TSourceClass extends { new(...args: infer U): Object} ? U : any[];

type LazyParams<TSourceClass extends Ctor, Params = CtorParams<TSourceClass>> = {
  [I in keyof Params]: Params[I] | (() => Params[I]);
};

const s: LazyParams<Ctor> = [1];

function use<TCtor extends Ctor>(  
  ctor: TCtor,
  ...args: LazyParams<TCtor>
) {}


class MyClass {
    constructor(myArg: number) {}
}

// Type is a tuple, so definitely spreadable... the types even work as the arguments.
// So why the above error on the ...args?

use(MyClass, 1);
// use(MyClass, ''); // Error as expected
use(MyClass, () => 1);
// use(MyClass, () => ''); // Error as expected
```

### 🙁 Actual behavior

Even though `LazyParams<Ctor>` appears to be a correctly formed Tuple type, `...args: LazyParams<TCtor>` complains about it not being an `Array`.

If you replace `...args: LazyParams<TCtor>` with `...args: CtorParams<TCtor>`, then Typescript accepts the types fine.

Also notice that even though Typescript complains about the rest params, the actual arguments in the function call are typed correctly.

Try as I might I can't find a case where `LazyParams` might return a non-Array type.

### 🙂 Expected behavior

Typescript to accept `LazyParams<TCtor>` as a valid, spreadable tuple type.

**Comment by martaver** [comment]
As a follow up, it seems possible to coerce the typescript compiler to treat the Tuple as an array by adding `& Array<unknown>` to the type definition of the argument:

[Playground](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/C4TwDgpgBAwsD2AnKBeKBvKA7CB3AFAHTECGiA5gM4BcUJWIA2gLoCUtA8gEYBWEAxsAC+AbgCwAKFCRYCRAAUyJALaUAPABUAyvACuifhBgAbEpUpQIAD2AQsAEwtwkAPlRRteg0dPnLNu0cMbDwiUgoaKABLLAAzCGQAVXYobj5BISgAfihEqFp6JmZxCUlpaABZEhAuCAAZEgAvEE03NA0oAB8ofHxWVDcNVhLJAHpRqHKoBubNXTBjaGtbBwtGYkJClmY2no2yKloNecX+lDdC-xWgsM2I2hj4pLOLhmyoKpr6ppbEt1oWCMpOBoDMWscFksAqsoOtSAxtrt0JIoLCAJLRLBQADWEBA8FiHhOEGYtE+tTBc0hjDROxKQkkZRBUAAgpQWREqYsroE1vsEcwdu4IdyAGSsxCIapqQouIH8eBYSjAKDGWiUxhYXTKWqIAA0UGViBi5CFaEYfQGUAAjAaAOR24qSBVKlUkWhsjlUNQarU6hI7XYWl425iMiSxXRYQRRRVQXSUCCaZzIZa82SufColFQQRII4pvU5-b3aY-NQpxRS1TJuQuNzijlSlpR7FYeC4LAuST9dAM0oD-i+CwVEAmMwWZESVGol1G3R5xD4ZQgABy2toft1BpXWmAxqw5FoRpNvf7-bGEw0zKiFhIk2JBso8Cg9ggsRiUVsxhAhrAiAgEh7BILhFg2SYAAtoHKCwIAANzsKBcCQbE6AsYAoLoChtTsYBKEIS8oB0JCIN-DDoBA+AEMsSUkCgONyKgEsqCycMEwgfBR3HcwDVtKAHWGSR2M4sdh3tO1eOGKBxigABRWjkDMfxIEECB7CExMRO4ygDUtc4bXEwSJGErixJ6EMHUkkRpImeTEDopTrBU2x7CAA)

The types are only accepted when they are correct, however then the problem is that the type reporting is incorrect, since now TS complains about the first argument not being a `string`, when it clearly should be expecting `number`.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg can we relax this restriction now (maybe defer it to call-time resolution)?

**Comment by ahejlsberg** [comment]
Everything works as expected if you write the `LazyParams` type as follows:

```ts
type LazyParams<TSourceClass extends Ctor, Params = CtorParams<TSourceClass>> =
  Params extends unknown[] ?
    { [I in keyof Params]: Params[I] | (() => Params[I]) } :
    [];
```

This convinces the type checker that `LazyParams` always resolves to an array or tuple type. Once this happens, everything else just works as expected, including positional diagnostics and parameter completion in the IDE.

**Comment by martaver** [comment]
Good to know!

Can I ask why the compiler doesn't simply treat all Tuples as arrays? What form of a Tuple isn't an array?

The need for the type assertion as an array is unintuitive to me...

**Comment by ahejlsberg** [comment]
> Can I ask why the compiler doesn't simply treat all Tuples as arrays? What form of a Tuple isn't an array?

The compiler does treat all tuples as arrays.

The issue here is that `LazyParams` is a mapped type, and mapped types are just plain object types (they *might* be arrays or tuples, but aren't *known* to be). The reasoning we're not doing is that when the `Params` type parameter is *omitted* from an instantiation of `LazyParams`, it's default is constrained to be an array type, which in turn means that the mapped type will produce an array type. It isn't trivial to to carry that implication through our constraint reasoning.

**Comment by martaver** [comment]
Okay, thanks very much for following up!
