### ISSUE TITLE
"in keyof" type mapping incorrectly interacts with indexers

### ISSUE THREAD

**Issue by LoganGerber** [microsoft/TypeScript#42436]
# Bug Report

### 🔎 Search Terms
Indexer
Type mapping
Type resolution
Typing

### 🕗 Version & Regression Information
All versions available on the Typescript workbench.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkEMBcGMAsCmBnU0D2amgHaQLYqjoBmokANhbujgLToAO0AlrZaIwE5OJetEWOUABUAUNACejRKABKiAI4BXFl0QATcInwAjPsgA8I0IgAe0RDg2p0ugFaJY0AHygAvKADeY0H9AA2gDSoEKgANaIkqSiALoA-ABcoMrWiCRCmqYWVjaiwbGg8biIAG58oMlBANxiAL4BkdFkIrG1YhLSsgDq6FzhQgDmAKJmBIwUiCJdHt6+-uoqapoAytBcQ8nI60O1-qCLquoaAHLKenzJOOf6XHv+TKzsFABC6OiTkDhJoLrvnzhanV2pNoKAzMkFEtjtoLlwjL1+kNRuNJtMZC4AoVPAEAESHZanG58XEAGlA+KUR1WOxwg1xbVAIFAiIGdOyqMQ5NoFEkoHwMAQRAwWFkeEItjI0GwBOOnB4Mn4LBQHU6MlALx4kRwKPwEymM08Pn2sppGzpW1pg3uflNRLhV2Jd3mfkebDwr3+iC+Pz+H29gJdgSaAHc+hpLebBrFkl9JNUmWBDHQ6KAAPI4XmgDQsEgkPhWWCyfTQEOIKxYFioKTqr4aFl9NkjMZ6tFdeodUGgSSQqmE2G3Iya9Da3X69GITHYwKU6GaM5wskUu1rKMMhPM5Op4ZcHjw4jCaUoWTbKPIAB0FInoAA5KehjfQqgcOgwZBkMgWIM8LpJmhMDWsg3qkGjpJkGg3peAAUABMADMMEwQAlLiQA)

### 💻 Code

```ts
// Matches to the names of all non-optional properties in T
type RequiredMembers<T extends object> = {
    [K in keyof T]?: undefined extends T[K] ? never : K;
}[keyof T];


type WorkingExampleType = {
    requiredString: string;
    requiredNumber: number;
    optionalBoolean?: boolean;
};

let x: RequiredMembers<WorkingExampleType>[] = ["requiredNumber", "requiredString"]; // Working example, only matches to the names of the required properties


type BrokenExampleType = {
    requiredString: string;
    requiredNumber: number;
    optionalBoolean?: boolean;
    [keyword: string]: any; // <-- Only difference between this type and WorkingExampleType
}

let y: RequiredMembers<BrokenExampleType>[] = ["requiredNumber", "requiredString"]; // <-- Errors on these strings. "Type 'string' is not assignable to type 'undefined'. (2322)"
```

### 🙁 Actual behavior
`RequiredMembers<BrokenExampleType>` resolves to `undefined`.

### 🙂 Expected behavior
`RequiredMembers<BrokenExampleType>` resolves to `"requiredString" | "requiredNumber"`

**Comment by MartinJohns** [comment]
By design. See #41966 for a workaround (omit the index signature).

**Comment by LoganGerber** [comment]
> Due to the indexer every `string` is a valid key, so `keyof` returning `string` is correct.

I don't think that's where my problem was. It's in `[K in keyof T]?: undefined extends T[K] ? never : K;`, specifically the `undefined extends T[K] ? never : K;` *always* resolving to `never`. I know that `keyof` should always return string, but the issue is with the values, not the keys.

**Comment by LoganGerber** [comment]
Oh nevermind, I understand what you're saying now. It's the `[keyof T]` that's causing the issue when using it on BrokenExampleType, but it's working as intended. My bad, thanks for the help yall!
