### ISSUE TITLE
lib.dom.d.ts contains `interface Account`

### ISSUE THREAD

**Issue by Aprillion** [microsoft/TypeScript#42440]
# Bug Report

### 🔎 Search Terms

https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+lib.dom.d.ts+Account
Following issues seem related, but none suggests removal of the `Account` interface: #32845, #19040, #23595

### 🕗 Version & Regression Information

?

### ⏯ Playground Link

N/A

### 💻 Code

https://github.com/microsoft/TypeScript/blob/2f47527b99028d969ea90352a13dffc005a50a7d/lib/lib.dom.d.ts#L25-L31

### 🙁 Actual behavior

`interface Account` is present in lib.dom.d.ts without an explanation in comment or git commit message.

### 🙂 Expected behavior

There is no real DOM API with such interface => should be either removed or explained with a comment.

Maybe it was created by webscraping MDN? https://developer.mozilla.org/en-US/account/ page exists and it displays info similar to the interface for logged in users ¯\\\_(ツ)_/¯

**Comment by Aprillion** [comment]
I just found following statement in a closed issue:

> `Account` is part of the Web Authentication DOM APIs (though it is still experimental). if you are not interested in DOM, consider using `--lib es2015` this will get you the JS standard library for es2015 without the DOM.

_Originally posted by @mhegazy in https://github.com/microsoft/TypeScript/issues/22057#issuecomment-367428081_

But none of the Interfaces in https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API has the same shape as `Account` from TypeScript, so I am confused about that...

**Comment by AviVahl** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/931

**Comment by jakebailey** [comment]
This was fixed in #43070.
