### ISSUE TITLE
Taking variables into account when checking for possible null values TS2532

### ISSUE THREAD

**Issue by marvinthepa** [microsoft/TypeScript#42446]
# Suggestion

I excuse in advance for opening this if this is too expensive too implement.
I think it might be useful to some though.

## 🔍 Search Terms

all included below

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

If an if statement only contains a single local constant variable, the compiler should inline the variable into the if statement (if the contents can be locally inferred) when checking for undefined variables.
If that sounds complicated to you, I suggest to check out the example below.

## 📃 Motivating Example

This does not compile:
```typescript
    const noSelection = !start || !end || (start[0] === end[0] && start[1] === end[1]);
    if (noSelection) {
      if (foo) bar();
      return;
    }

    console.log(start[0]); // Object is possibly undefined ts2532
    // some more code using noSelection
```

but this does:
```typescript
    if (!start || !end || (start[0] === end[0] && start[1] === end[1])) {
      if (foo) bar();
      return;
    }

    console.log(start[0]); // No error
    const noSelection = !start || !end || (start[0] === end[0] && start[1] === end[1]);
```

although they are basically the same code.
The information is there to deduce that start can never be undefined, so it could be used in theory.

## 💻 Use Cases

This can prevent uneccessary null checks or executing code twice that only needs to be executed once.
Can also help readability. The current workaround is to duplicate the logic

**Comment by MartinJohns** [comment]
#12184
