### ISSUE TITLE
Function return type allowing extra values

### ISSUE THREAD

**Issue by rajeevnaikte** [microsoft/TypeScript#42443]
# Bug Report

### 🔎 Search Terms

typescript function return type allowing extra values

### 🕗 Version & Regression Information
v4.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gWwgJQgZzHAdm6BeKAbwCgooATAQ2EoEYB+ALijWACcBLLAcwG5SK1SgCYmULAFcEAIwht+ZKjQDMzVpx78Avv2IBjbKyht0mHBGbwkqDIfxEBSuswDkUFwBpHQ1e7LuvRSEAD2ZaAAYyAHooqDA2OEg2KDkEtmIdYmIYqABBNBAsPRY9CCxKTjhiUEhYRAh8wr0AMQki4A5sKAIACgBKboA+KAAFBIQOXAAeKxRTO0HdGuhZmAhgAHkAM1b2zpxuhzIEEF29DuxLesais4usbV0DHGAoDgQwABtaK6Q1zZ2bXO+zQhxIZEoBSKUBOd32-QE4P8JmAEjYWCO-iCKlcZE8AixTh+fnxWOxlFCUAi0ViEGCkGBPBSbDSUAAFnJoGhKCAuNxBDRgm9QVg4K9KJ9PnAAO4QcgEqCZMhaDJPQyvd5fYS-CD-bZwwxggSQpow05A+79KA5VJwZLc3lMpzKYUwyZoPkeN4AOgg3reGtBADcJRwlHyoMAOZHwBBEQqUWiMUjCUJiW5SWSnJTqdbafSIIz+bbkhyTCweRHs67ReLJTK5QqlYrVVksjkYJQkMK0BJoNKOFHYKa0KVypUoJCoLLJd7qrG6kgDRjegM8MNZjYzLglgvZsvQQQkbCLfsdcvHllnkY0PUAJIfT7n0+Go8CE97bAIsgp4zrJOYqmOJ+AECrkumoFkgKFJhJEeYpAWRbMqyZZxlizYqpkQA)

### 💻 Code

```ts
type SomeResponse = {
  data1?: string;
  data2?: number;
  data3: string;
};

const response: SomeResponse = {
  data1: ' ',
  data3: '    ',
  datax: 10  // proper error
};

type SomeAsyncFunction = () => Promise<SomeResponse>;

type SomeSetOfFunctions = {
  myFunction: SomeAsyncFunction;
};

const impl1: SomeSetOfFunctions = {
  async myFunction()
  {
    return {
      data3: '  ',
      data1: ' ',
      datax: 10  **// expecting error here saying datax is not allowed**
    };
  }
};
```

### 🙁 Actual behavior

When type of a property is function and we are writing it as function (someFunction() {} instead of someFunction: () => {}), adding extra properties in the return data is not validated as error. Missing required properties are validated.

### 🙂 Expected behavior

When a return data type is inferred, extra properties must be validated (unless specified `[key: string]: any`).

**Comment by RyanCavanaugh** [comment]
Duplicate #241
