### ISSUE TITLE
peer dependencies of symbolically linked libraries are not resolved correctly

### ISSUE THREAD

**Issue by zwhitchcox** [microsoft/TypeScript#42441]
# Bug Report

Assume you are working on a project called `myproj`.
Assume you are also working on a dependency called `mylib`.
Assume `mylib` has a peer dependency of `react`.

When you use `npm link mylib` or `yarn link mylib` in `myproj`, `tsc` looks for the peer dependencies (in this case `react`) in `mylib/node_modules` instead of `myproj/node_modules`.

This is a problem in the case of `react`, because you cannot have multiple instances of `react` running at the same time, but could be a problem for other libraries as well.

Peer dependencies from `mylib` are supposed to come for the `myproj/node_modules` directory, not `mylib/node_modules`. that's what makes them a "peer".

### Workaround

You can use `create-react-app`, and the webpack compiler resolves the peer dependencies correctly.

### 🔎 Search Terms

peer dependency link

### 🕗 Version & Regression Information

TypeScript version: v4.1.3

I have not tried this on any other versions

### ⏯ Playground Link

Due to the nature of the bug, I can't use the playground, but I made a reproduction repo. It will need to be run on a unix system in order for the symbolic links to be respected though:

https://github.com/zwhitchcox/repro

### 💻 Code

```ts
// module1/run.ts
import { x } from 'module2'
x()
```

```ts
// module2/index.ts
import { y } from 'module3'
export const x = () => {
  console.log('running from module 2')
  y()
}
```

```json
// module2/package.json
{
  "name": "module2",
  "version": "1.0.0",
  "main": "index.js",
  "peerDependencies": {
    "module3": "^0.0.0"
  }
}
```

```ts
// node_modules/module3/index.ts
export const y = () => console.log("hello from module3")
```

### 🙁 Actual behavior

So, for my workflow, I am using `tsc` for testing, and I'm using `npm link` or `yarn link` for one of my peer dependencies.

`tsc` follows the sym link to the `link`ed dependency, but when it tries to find the peer dependency, it looks in the `link`ed `node_modules` directory, not the directory of the project that the `link`ed module is included in.

So, it gives an error of "module not found".

### 🙂 Expected behavior

When `tsc` is following the path for required/imported modules of symbolically linked libraries (via `npm link` or `yarn link`, it should look for the peer dependency in the `node_modules` directory of the original module that required the symbolically linked dependency, not in the symbolically linked dependency's `node_modules`' directory.

The whole point of peer dependencies is that the original module includes the dependency of the dependency, not the dependency itself.

**Comment by zwhitchcox** [comment]
Just as a note, for a workaround in the example case, what I would do is create a symbolic link from `mylib/node_modules/react` to `myproj/node_modules/react`, and that works fine.

**Comment by RyanCavanaugh** [comment]
What's the behavior with `tsc` ? We don't control `ts-node`

**Comment by zwhitchcox** [comment]
Oh, my mistake, yes this is the behavior with tsc...I started to create this issue on the ts-node repo, but then I realized that they don't have control over that behavior, it's the behavior of typescript in general, in particular `tsc`.

I will edit the initial issue post

**Comment by sheetalkamat** [comment]
@zwhitchcox can you please clarify the repro.. 
which project do you run tsc on? 
Do i need to follow any other steps to repro apart from cloning the repro you have attached?

**Comment by zwhitchcox** [comment]
@sheetalkamat 

Ok, you can reproduce this issue by downloading the repo:

https://github.com/zwhitchcox/repro

Then, changing to the `module1` directory, and attempting to run `tsc`. It will say `module3` is not found.

```
cd module1
tsc
```

Error:

```
../module2/index.ts:1:19 - error TS2307: Cannot find module 'module3' or its corresponding type declarations.

1 import { y } from 'module3'
```

This is resolved by using the [pnp webpack plugin](https://github.com/arcanis/pnp-webpack-plugin#ts-loader-integration), assuming your using webpack. It might be nice to add this as an option just for plain `tsc` though.

I believe the webpack plugin uses [ts-pnp[(https://www.npmjs.com/package/ts-pnp) under the hood.

You can read more about the pnp module resolution method [here](https://www.w3resource.com/yarn/getting-started-with-plug-n-play.php), but that is just one way of doing it. `tsc` could implement its own method.

**Comment by zwhitchcox** [comment]
Also, it's worth noting that `tsc` is using the Node resolution method, but that doesn't take into account peer dependencies.

**Comment by sheetalkamat** [comment]
we need the repro steps and clear issue with tsc.. we wouldnt be able provide support for webpack plugin as yet.. 
Did you try using `--traceResolution` to see whats going on. You are suppose to provide path mappings to make module resolution work to tsc. 
I am not sure what the expectation from tsc is here.

**Comment by zwhitchcox** [comment]
> we wouldnt be able provide support for webpack plugin as yet.

That's not what I was saying. I was just using that as an example of how it should work.

But I think ultimately you're right that this is not a `tsc` issue, because `tsc` is not a module bundler.

Ok, well thanks for listening anyway.

**Comment by artemis-prime** [comment]
Why is this closed?  This is definitely a tsc issue, since it needs to compile against peerDependencies (completely aside from the issues of bundling.  @zwhitchcox 

If it's not a tsc issue, how should one manage this:  

Yarn mono repo with "yarn install" run from the root

myModule (lists React as peerDependency)
myBuildTarget ( lists React as an ordinary dependency; references myModule in its "references" section and also as a dependency in package.json)

I should be able to run myBuildTarget/tsc -b and get a valid compile.

What am I missing that makes this "not a tsc issue"?

**Comment by RyanCavanaugh** [comment]
@artemis-prime I'd recommend opening a new issue with clear repro steps; it's confusing for everyone when we re-open issues that start with a long "support" exchange and then jump to a new repro.
