### ISSUE TITLE
Generic mapper not possible to implement

### ISSUE THREAD

**Issue by pinggi** [microsoft/TypeScript#42456]
# Bug Report

### 🔎 Search Terms

generic mapper

### 🕗 Version & Regression Information

- v4.1.3
- I was unable to test this on prior versions because it's not implemented even in the newest.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-IAOUA9oQFzIDOYUoA5rgL666iSyIoBCmuBRUhWq0GzVjnbR4SZAGE+eAgHdSIegH1iZSjTrrxOXBAAehElDDIEJEDWQBbOIWQBeZAB4AKgEkQhAFcwABpkLwB5IMCwAD4AClBoyl9-IIBKZMiwaLcY5DiMZAA6EsSg5CY0gG5kAHpazwBaRuQwAE9CFGhSKGQAC2gICRs7KwAjN0dnD1RQ7njC7WEAcgA3OAAbAIhliurcEfsESadCGdC5BcEdZDXN7d3KmvqmltAaCDgAE2QSGH7BsNbFQSBsIEUNiR6HExqEEPscEA)

### 💻 Code

```
interface A {
    prop: string
}

interface B {
    prop: string
}

interface C {
    wrong_prop: string
}

export const map = <TInput, TOutput>(input: TInput): TOutput => ({ ...input }); // <-- type error here

const b = map<A, B>({ prop: 'value' });
const c = map<A, C>({ prop: 'value' }); // <-- instead of here

console.log(b, c);
```

### 🙁 Actual behavior

It's not possible to implement a generic mapper mapping one type to another since Typescript checks the body of the mapper function also when it doesn't have types known yet.

Error: _Type 'TInput' is not assignable to type 'TOutput'.
  'TOutput' could be instantiated with an arbitrary type which could be unrelated to 'TInput'.(2322)_

### 🙂 Expected behavior

It's possible to implement a generic mapper so that we don't have to write specific mapping functions for DTO <-> Model if they have the same properties.

**Comment by MartinJohns** [comment]
If the types have the same properties, then you just need one type argument. If the types are different, then this wouldn't be typesafe.

**Comment by RyanCavanaugh** [comment]
Generics aren't template instantiation. If you try to reason about them that way, you will arrive at many incorrect conclusions about how things should work.

**Comment by pinggi** [comment]
What I'm trying to achieve is that I have an Output interface and I want to constraint the mapping function so that it only returns an object having exactly the same properties as the interface Output. Not more, not less. The Input interface can be arbitrary type. If the Input type is different from the Output type, the programmer has to implement a conversion from one type to another. So it's enforced that an endpoint will return only data with specific schema.

```
interface Input {
    prop: string,
    prop2: string;
}

interface Output {
    prop: string
}

// no static type check error! :-(
// if I run it, it will return object with "prop2" key even I want only objects with only "prop" key.
export const map = (input: Input): Output => ({ ...input });
```

As a second step - if the Input type and Output type are the same, it's useless to write again and again the same type of function.
I wanted to create a generic version of that can be used for various types.

Can you give me a hint which way of reasoning about generics is the good one?

**Comment by RyanCavanaugh** [comment]
>  Not more,

TypeScript has structural subtyping, so this isn't possible. See also #12936
