### ISSUE TITLE
Typescripts version of `require` should include `require.resolve`

### ISSUE THREAD

**Issue by nickpalmer** [microsoft/TypeScript#42460]
# Bug Report

Apparently TypeScript overrides nodes require without implementing require.resolve.

### 🔎 Search Terms

require.resolve

### 🕗 Version & Regression Information

Not sure. I don't actually use TypeScript, but users of a library I was using reported that a change to using require.resolve broke the library in their environment.

See the issue which surfaced this break from the Node API here:

https://github.com/abhinaba-ghosh/cypress-react-selector/issues/94

TypeScript is breaking the documented Node API by not offering a require.resolve function.

### ⏯ Playground Link

The playground doesn't seem to support require.

### 💻 Code

const fsPath = require.resolve('fs');

### 🙁 Actual behavior

Usage of require.resolve throws a `"require.resolve" is not a function`.

### 🙂 Expected behavior

require.resolve should return the path to the resolved file the same as is promised in the Node API.

See the documented API here:
https://nodejs.org/api/modules.html#modules_require_resolve_request_options

**Comment by RyanCavanaugh** [comment]
I don't understand what's being requested here. TypeScript just emits JS code and doesn't "replace" the `require` value. Can you provide enough information to reproduce the problem?
