### ISSUE TITLE
Property to define entry files for compilation process in tsconfig

### ISSUE THREAD

**Issue by Lenne231** [Microsoft/TypeScript#4246]
Currently we have two ways to define the files include in the compilation process.

1. Include all files from the root directory except the files and directories defined in the `exclude` property #3188

2. Include all files defined in the `files` property https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

It would be much simpler if we could just define some entry files (only modules) and all dependent files will be included in the compilation process automatically. Browserify does something like this (https://github.com/substack/node-browserify#browserifyfiles--opts).

This would drastically simplify the configuration and be very helpful for isomorphic/universal JavaScript apps.

Maybe `modules` or `entryFiles` would be a good name for the property in the `tsconfig`.

**Comment by mhegazy** [comment]
Just put them in "files"; the compiler will follow the imports and include then too. "files" is really "rootFiles".

**Comment by Lenne231** [comment]
Thanks, didn't know that!
