### ISSUE TITLE
Can assign incompatible object to Partial<Record>, why?

### ISSUE THREAD

**Issue by alamothe** [microsoft/TypeScript#42469]
This might be just a TypeScript gotcha, but I am puzzled by why this compiles:

```tsx
function f() {
	return 10
}

// ERROR
const m1: Partial<Record<string, string>> = {
	[10]: false
}
// ERROR
const m2: Partial<Record<string, string>> = {
	[f()]: false
}
// ERROR
const m3: Partial<Record<'A', string>> = {
	[10]: false
}
// Compiles - why?
const m4: Partial<Record<'A', string>> = {
	[f()]: false
}
```

This was an actual bug in our code.

**Comment by alamothe** [comment]
Another weird example:
```tsx
export enum E { A = "A", B = "b" }
function f(): E {
	return E.A
}
// ERROR
const m1: Partial<Record<E, string>> = {
	[E.A]: false
}
// Complies
const m2: Partial<Record<E, string>> = {
	[f()]: false
}
```

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
