### ISSUE TITLE
[bug] name is deprecated

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/TypeScript#42476]
### 💻 Code

![image](https://user-images.githubusercontent.com/28700378/105650929-5b308300-5ef0-11eb-8c2d-8deece0ec092.png)

![image](https://user-images.githubusercontent.com/28700378/105710152-adee5700-5f51-11eb-9d5b-39c8e6b1dd04.png)

### 🙂 Expected behavior

No warning.

**Comment by AviVahl** [comment]
This was an intended change, I believe. See related discussion: https://github.com/microsoft/TypeScript/issues/18433

**Comment by wenfangdu** [comment]
@AviVahl It's actually easier to trigger... please see the newly uploaded picture.

**Comment by AviVahl** [comment]
That's a different behavior, where a .ts file without any esm export/import statements is treated as a script. if you add `export {}` it would treat it as a module. Not to say that this is ideal behavior or anything.

**Comment by DanielRosenwasser** [comment]
Eventually, I assume we'll be able to look at an `.mjs` file and say "that's a module", but until then, this is an external behavior.

**Comment by wenfangdu** [comment]
@DanielRosenwasser Just to add more info, `.js` is the same too:
![image](https://user-images.githubusercontent.com/28700378/105784232-57196980-5fb3-11eb-89dc-22cba7e8fd00.png)
