### ISSUE TITLE
Assignment doesn't have transitivity.

### ISSUE THREAD

**Issue by heroboy** [microsoft/TypeScript#42479]
# Suggestion

## 🔍 Search Terms
extends conditional constrain

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

short example:
```typescript
declare function SampleComponent(props: { a?: any; }, context?: any): React.ReactElement<any, any> | null;
declare var Tag1: React.FunctionComponent<{ a?: any; }>;
declare var Tag2: React.FunctionComponent<{}>;
declare var Tag3: typeof SampleComponent;

//Tag1 and Tag3 can assign to each other.
Tag1 = Tag3;
Tag3 = Tag1;

//Tag1 and Tag2 can assign to each other.
Tag1 = Tag2;
Tag2 = Tag1;

//But Tag2 and Tag3 can not assign to each other.
Tag2 = Tag3; //error
Tag3 = Tag2; //error
```

[playground](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoAEyTQBsUi5MBXAOw2AlbgGUVxaSAMK5IrJKxgAKMDjABnAFxwA3nBQB+ZSlYBPUnAC+AGjhouMJAA8YW9XoCUy5OhgA6FxgCigkBJgAPDq6psEAfHAAPnCszLS0FNR0DEhwAG4McAAqKADmAIzOxO4AYmwcXCLgXP4BapraegaGYYk09IwZUNl5AExFrm5l7DCcrFVitSotbcmdmTm5AMzKMLpgSBCYvPxgghM1khRrG9n5cAC8cCeb24v5x+upWb2X109bPbm9j6dZS28bp9FksKOQAPTg+72ShfAFoHTqeTyYC5bgwCBwYgACzgEBg2KQUDc5BucAAaucrv8sTYJJR5Gc4Bo4OdlD84JD8qSnhT8lSmdZLKwGdkASy2XAflzyNDqXlQbKFW97mDIdCdLDFq8EdwUMjUejMTi8QSiSSyeTXtTzkL6YyXszWXB2QYZZbetbsq87SKHecJS6paQZXKvj8ld8VXkHuQIeCAELMeDamFwsyI1j4pEotHXY3oXH4wnEnmnckA6k+ul+sVOyUcyG9MupCuVuu+0WOwOupuRr0gigg6PfMFxlgjMZwEC6IgiokBLK04Wi6ZhKSLAYYIblUaVUSHQJZMIOVTkOAXuBEGDMKDcRd5TlhciGce7qczufUKC9Dd5RSeKU777tU4iSHULQOOQKjnpe163veizgs+r6fvSRK-vcDgUGh84-n+3zYeQuHfphCrYUAA)

## 📃 Motivating Example

I want to write a function to take any function component that can accept empty props.

```typescript
function myrender<T extends {}>(Tag: React.FunctionComponent<T>) {
    return <Tag /> //error
}

function myrender2(Tag:React.FunctionComponent<{}>)
{
    return <Tag/>
}
myrender2(Tag3); //error

```

**Comment by jcalz** [comment]
I think other issues of assignment transitivity have been raised and closed as design limitations, like #13043 and #40529.  What, specifically, is the suggestion here?  In the following code, what specifically should be changed?

```ts
declare var foo: { a: string, b?: number };
declare var bar: { a: string };
declare var baz: { a: string, b?: boolean };

foo = bar; // okay
bar = foo; // okay

bar = baz; // okay
baz = bar; // okay

foo = baz; // error
baz = foo; // error
```

The mutual assignability of `foo`⇔`bar` and `bar`⇔`baz` is unsound but *very* convenient, and breaking it would break all sorts of real-world code.   Enforcing transitivity here would imply that we should allow `foo`⇔`baz`, but who wants that?  Is there something better than what TypeScript already does here?

**Comment by heroboy** [comment]
@jcalz 
ok , I agree with you. Thanks.

**Comment by masaeedu** [comment]
> Is there something better than what TypeScript already does here?

IMO something better would be to distinguish between closed records, which do not admit additional fields, and open records, which can have an arbitrary set of fields besides the listed ones. I'm not sure if there's an issue for that.

**Comment by jcalz** [comment]
"Closed records" would probably be "Exact types" as requested in #12936

**Comment by fatcerberus** [comment]
> This kind of unsoundness is a pretty deep issue, and shows up in the bajillions of `keyof` related issues for example.

Unsound or not, it’s a fundamental part of the type system and completely by design: TS calls it structural subtyping, and it’s done that way because that’s what best models idiomatic JS.  Soundness comes second. (in fact soundness is explicitly called out as not a primary pursuit in the design goals)

All that being said, #12936 is indeed rather popular as far as feature requests go; people often get to wanting it before they’re even able to articulate it. 😆
