### ISSUE TITLE
Object requires unnecessary type checking

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [microsoft/TypeScript#42473]
# Bug Report

### 🔎 Search Terms
unnecessary type checking

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type checking
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/KYDwDg9gTgLgBDAnmYcAqzUF44G8BQcCmAXHAOQCG5hcAJpTJWQUUWFBGAIxkDOMKAEsAdgHNaAX3yS4AHzy0kKMuQBGNIgyYta7Tj36DREtnEoAFA2gAWjDCgCCAEQjA+AOQgwAEpQBuwEbC4lIy+PigkLBwAMYQIgJwfDYQAK4ANnQA6tAA1gBCaTCu7l7wOAAUEGQOwACUZP4QQnRwWAB8ikQQ7d1sykFwEAB0gwA0evSMzP1mIwuj2pSTZvpcvBRpYNrAbf6UGWnAmmzSRNLSkeDQ8PGJ8ADu+XxFMADKEACqIiLAse4+JQoIg+tVaphGnBmq12l1WMM+qNBu0sDgqKciAB+OYDUjDMaYVZrZa6NZsBYjJYzYnkjgbVTbXb7Q7HTFnKbnNhktaDMjIolTLQzHnkynUpi0tb0wxbHaMPbQ1knIVwLkXcJAA)

### 💻 Code

```ts
export type Type = {
  type: 'a'
  data: {
    prop1: string
  }
} | {
  type: 'b'
  data: {
    prop1: string
    aPropThatTypeADoesNotHave: string
  }
}

export const shouldWorkButDoesNot = (o: Type): void => {
  o = {
    type: o.type,
    data: {
      ...o.data,
      prop1: 'updated value'
    }
  }
}

export const worksButSoUnnecessary = (o: Type): void => {
  o = o.type === 'a'
    ? {
      type: o.type,
      data: {
        ...o.data,
        prop1: 'updated value'
      }
    }
    : {
      type: o.type,
      data: {
        ...o.data,
        prop1: 'updated value'
      }
    }
}

```

### 🙁 Actual behavior

The `shouldWorkButDoesNot` function has a type error. It shouldn't have a type error because no matter what `o.type` is, `...o.data` will always include the required props. 

The function below (`worksButSoUnnecessary `) works by type checking `o.type`, but since both parts of the ternary are exactly the same, the type checking is completely useless. However, it still needed?? for there to not be any typescript errors.

### 🙂 Expected behavior

The function `shouldWorkButDoesNot` should not have an error.

**Comment by jcalz** [comment]
See #30581; `o.type` and `o.data` are correlated in a way the compiler does not understand unless you walk it through the different cases via control flow analysis.

**Comment by ChocolateLoverRaj** [comment]
Duplicate of #30581
