### ISSUE TITLE
Incorrect parsing of IIFE

### ISSUE THREAD

**Issue by chocolatechipui** [Microsoft/TypeScript#4247]
A fairly common form of IIFE is to enclose the function in parens, followed by another set of parens which are used to pass in a global object, such as window or jQuery. In Babel we can do the following:
```
(exports) =>  {
  var foo = (msg) => console.log(msg);
  exports.foo = foo;
}(window);
```
This returns;
```
(function (exports) {
  var foo = function foo(msg) {
    return console.log(msg);
  };
  exports.foo = foo;
})(window);
```
But in your TypeScript playground I get this for the same expression:
```
(function (exports) {
    var foo = function (msg) { return console.log(msg); };
    exports.foo = foo;
});
(window);
```

Notice that the TypeScript transpiler is incorretly detach the final parens with window and putting it on the next line as a separate statement. This has the effect that window, or any other value, never gets passed to the IIFE. This pattern is often used in conjuction with jQuery or other libraries that use the same ```$```:

```
($) =>  {
  $('li').addClass('jQuery-is-here');
}(jQuery);
```
Unfortunately TypeScript is incorrectly creating:

```
(function ($) {
    $('li').addClass('jQuery-is-here');
});
(jQuery);
```

**Comment by S-YOU** [comment]
Not sure about ES6 IIFE, but for normal IIFE, you need wrap a bracket to function.

```javascript
((exports) =>  {
  var foo = (msg) => console.log(msg);
  exports.foo = foo;
})(window);
```

**Comment by basarat** [comment]
I think babel is wrong here. Babel also works for : 

```js
function (exports) {
    var foo = function (msg) { return console.log(msg); };
    exports.foo = foo;
}(window);
```
[Making it](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=function%20(exports)%20%7B%0D%0A%20%20%20%20var%20foo%20%3D%20function%20(msg)%20%7B%20return%20console.log(msg)%3B%20%7D%3B%0D%0A%20%20%20%20exports.foo%20%3D%20foo%3B%0D%0A%7D(window)%3B%0D%0A) : 
```js
(function (exports) {
    var foo = function foo(msg) {
        return console.log(msg);
    };
    exports.foo = foo;
})(window);
```

[TypeScript errors](http://www.typescriptlang.org/Playground/#src=function%20(exports)%20%7B%0A%20%20%20%20var%20foo%20%3D%20function%20(msg)%20%7B%20return%20console.log(msg)%3B%20%7D%3B%0A%20%20%20%20exports.foo%20%3D%20foo%3B%0A%7D(window)%3B%0A) which is consistent with how a browser would error

**Comment by chocolatechipui** [comment]
Thanks S-YOU, that works in TypeScript and Babel. Didn't think about wrapping the whole expression in parens ;-)
