### ISSUE TITLE
Tsx props lose type checking in onClick handler

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [microsoft/TypeScript#42475]
# Bug Report

### 🔎 Search Terms

- tsx props lose type checking
- tsx props
- onClick

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about handlers

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQLABQ9wAdjFlAXlnAArFjoBvenDgwAnmCwAucsjJwAPuQBG8pWVy06AX3pYAHpFhwAJlg4BXADbwAFGD6oZvCPwCUMgFIBlABoA6AFErLBAsFkU4JmsrOABeAD44IToRXAgmVHgrCABzAGF4uFtcGQ0yDzgANwhgE3iklJE0jNQIEP8c3JK3YThdVLhKGAsoJjgHV1R-cUk4AEI4uNktZrgAfmK+tYAeBO21uB3UMGQmA8O4DPyrYFwAaziBWzcG5IvLuGACYsn+GYkXCWyzIqleKQ+l20cCwVlQXCan0uXXy9kcAMkvUGSJEAxx-TxnwA9Ptsc0diSDli1jJolYrPRtEA)

### 💻 Code

```ts
interface Props {
  type: 'a' | 'b' | 'c'
}
export default (props: Props): JSX.Element | null => {
  const logC = (c: 'c'): void => {
    console.log(c)
  }
  // Next line makes sure props.type is 'a'
  return props.type !== 'a'
    ? (
      <>
        <span
          onClick={() => {
            if (props.type === 'b') {

            } else {
              // TypeScript thinks it's possible for props.type to be 'a'
              logC(props.type)
            }
          }}
        />
      </>
    )
    : null
}
```

### 🙁 Actual behavior
There is an error that says `Argument of type '"a" | "c"' is not assignable to parameter of type '"c"'.
  Type '"a"' is not assignable to type '"c"'.ts(2345)`

### 🙂 Expected behavior
`props.type` should be narrowed down to just `'c'`, so there shouldn't be any errors.

**Comment by MartinJohns** [comment]
Another duplicate of #9998.

**Comment by ChocolateLoverRaj** [comment]
Duplicate of #9998

I guess typescript is being 'pessimistic' in my case.

> Another duplicate of #9998.

@MartinJohns Thanks for finding duplicate.
