### ISSUE TITLE
[Feature] Copy interface fields using spread syntax

### ISSUE THREAD

**Issue by nategiraudeau** [microsoft/TypeScript#42488]
# Suggestion

## 🔍 Search Terms

interface, spread interface, spread operator interface, spread type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Copy interface fields onto another interface using spread syntax like this:
```
interface BasicInterface {
    field1: string,
    field2: number
}

interface SpecialInterface {
    ...BasicInterface,
    field3: any
}
```

## 📃 Motivating Example

No longer having to copy interface fields over to another interface by hand, and then copying them again every time the original interface gets changed, when an interface similar to another interface is needed.

## 💻 Use Cases

Currently I have to copy interface fields by hand, which is time consuming and it makes my code messy.

**Comment by IllusionMH** [comment]
In this simple case [`extends`](https://www.typescriptlang.org/docs/handbook/interfaces.html#extending-interfaces) should solve your problem 
```ts
interface SpecialInterface extends BasicInterface {
    field3: any
}
```

[Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM7AQSXNeJZAbwChkLkZgIAbAEwEYAuZDMKUAcwBpzLqdegCZWIAK4BbAEbRSAX1KlQkWIhQBlAA4QEwOLTyrCKCAA9IIehjSZsRgupL8KghgGZWcEAE8FS0gQAexB2ZDB2Vm1dfUN8NSIAXmdXGg9WAHIMCBQwAAs4MCo0pmRvemKhYTKoFFqAR3FgWorMZAB3OloMhSA)

Not clear how this should be different
