### ISSUE TITLE
Error in Handbook documentation?

### ISSUE THREAD

**Issue by tpdi** [Microsoft/TypeScript#4248]
http://www.typescriptlang.org/Handbook

s/return/refer/"Just as in JavaScript, functions can return to variables outside of the function body."

**Comment by mhegazy** [comment]
@DanielRosenwasser can you take a look

**Comment by DanielRosenwasser** [comment]
Thanks @tpdi, in the future, handbook-related documentation can be filed on https://github.com/Microsoft/TypeScript-Handbook
