### ISSUE TITLE
JSDoc parser strips leading spaces inside of parameter documentation

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#42489]
# Bug Report

from https://github.com/microsoft/vscode/issues/112292

### 🔎 Search Terms

- quickinfo
- jsdoc
- markdown

### 🕗 Version & Regression Information

Version: 4.2.0-dev.20210125

Not a regression 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
/**
 * a
 * 
 * 1. As string literals matching the name of a builtin [scalar](https://foo.bar).  
 *   
 *   E.g.: 'ID', 'String', ...
 *
 * @param type Blah blah
 *
 * 1. As string literals matching the name of a builtin [scalar](https://foo.bar).  
 *   
 *   E.g.: 'ID', 'String', ...
 */
const a = 1;
```

Hover over `a`

### 🙁 Actual behavior
The returned jsdoc info for the `param` looks like this:

```
            "text": "type Blah blah\n\n1. As string literals matching the name of a builtin [scalar](https://foo.bar).  \n\nE.g.: 'ID', 'String', ..."
```

You can see here that ` \n\nE.g` has no leading whitespace 

### 🙂 Expected behavior

These whitespaces should be preserved. They end up being significant here since we parse the jsdoc contents as markdown.  

Here it causes the contents to be parsed as:

```html
<ol><li>As string literals matching ...</li></ol>
<p>E.g.: 'ID', 'String', ...</p>
```

Whereas the initial list is parsed as:

```html
<ol>
<li>As string literals matching ...
<p>E.g.: 'ID', 'String', ...</p>
</li>
</ol>
```

**Comment by mjbvz** [comment]
The existing behavior may exist to handle cases where leading spaces should be stripped, such as:

```ts
/**
 * @param foo Documentaion which
 *   continues on to
 *   the next line
 */
const a = 1;
```

**Comment by RyanCavanaugh** [comment]
@mjbvz we need some proposed rule for how we would tell these examples apart. Showing text
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like this
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;in hover text
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;is not going to be well-received

**Comment by mjbvz** [comment]
Short of having TS parse markdown, I don't think there is a good solution. Maybe only strip leading spaces when the pervious line was not blank?

Let's wait for more feedback from the community before looking into this more
