### ISSUE TITLE
Optional chaining does not narrow types in the `else` branch 

### ISSUE THREAD

**Issue by kdmadej** [microsoft/TypeScript#42480]
# Bug Report

### 🔎 Search Terms

* `optional chaining`
* `optional chaining narrow`
* `optional chaining discriminated`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about:
  - optional chaining
  - type narrowing

Tested on all TS versions available in the playground that support optional chaining.
At the time of writing:
- 4.2.0-beta
- 4.1.3
- 4.0.5
- 3.9.7
- 3.8.3
- 3.7.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3&ssl=6&ssc=1&pln=8&pc=1#code/C4TwDgpgBAglC8UDeVSQFxQOQywGigENMtCsoBfAKDWgCEFlVwIS78oAjEz86qgCYQAxgBtCAJ2jCA9gDsAzsCjDMcAD5QGmuQFdRoqgHojUIWMnT5SlWqibtUXXKEAzAJZyIA46fPipFWtlVVh7LSgTKAB3GQkAawUoDy9kuKg5eQBaPQNCTlFoZ3drKip3VygACmEAfgA6WgR4RBwsAEpkKigelQBuSNM5SQkZaO9UGSgAAxhpoiSIAA9IYWBvKgooCFEFaCRu3uEBqNn5pXcDKDApPbllT1QAC2haTaA)

### 💻 Code

```ts
type A = { type: 'A', a: 'a' }
type B = { type: 'B', b: 'b' }

declare const c: A | B | null
// declare const c: A | B | undefined
// declare const c: A | B // works fine for non-nullable unions

if (c?.type === 'A') {
    c; // narrowed to `A` as expected
} else {
    c; // `A` still present in the type
}
```

### 🙁 Actual behavior

In the second branch of the conditional statement the union type inferred for `c` still includes `A`. Same thing happens with ternary operator, functions with early returns, etc.

### 🙂 Expected behavior

In the second branch the type should be narrowed down by excluding `A`.

**Comment by kdmadej** [comment]
Might actually be related to https://github.com/microsoft/TypeScript/issues/42404

**Comment by DanielRosenwasser** [comment]
I don't think they're related but yes, it looks like the expected type should indeed be `null | B` in the example above.

**Comment by ShuiRuTian** [comment]
maybe duplicated? https://github.com/microsoft/TypeScript/issues/40397

Anyway, this could be fixed by https://github.com/microsoft/TypeScript/pull/38839

**Comment by kdmadej** [comment]
Yup, this issue is a duplicate of https://github.com/microsoft/TypeScript/issues/40397
Sorry for the spam (not sure how I missed that in my search 🤦 ).

**Comment by ShuiRuTian** [comment]
Oh, so sorry for the misleading! 
I found that the two issues are very similar, but not same: that issue is `undefined`, and this is `null`. 
Since the PR to fix that issue has been merged(which only handle `undefined` condition, you could see more in the PR link), you could test in `beta` version(not 4.2.0-beta, it should end with a date) in playground.

So, I guess this issue would better to be reopened?

**Comment by kdmadej** [comment]
Indeed, `| undefined` works as expected in the nightly build but `| null` does not.

BTW I'd be more than happy to help out with a PR but I'd need some guidance as to where to start 😅 (i.e. is the aforementioned PR a good example, since it tackles a similar issue?)

**Comment by andrewbranch** [comment]
I think this is going to be a one-identifier change on top of my recent PR; will take a look this afternoon.

**Comment by matchish** [comment]
I'll add one more case with ternary operator and with internal types
```
let a: number|undefined
let b: boolean
let c: number
b = a === undefined ? false : true
if (b) c = a // Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
