### ISSUE TITLE
Not able to restrict children type

### ISSUE THREAD

**Issue by pladaria** [microsoft/TypeScript#42498]
# Bug Report

### 🔎 Search Terms

react children

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `react`

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvADLDMDWAXJlRgA6AGIBhADwBvOAFcoAG35soXAOYAaOLgAWwBQBNKzftjzCz+AHIQDWOAF8AfHAC8cABQz5Crbv1GWMyOAJRuLhLIcDqUBK5SPs5S-obGDhIA9MhODDAAnmD2AArEYOjuUnRw1dp6qUEA-KaCQpYwAKIKWCBBMBL5hRAEcJw8OQ4MTKzwYiSQzL3N5qKSJRBlLu5eKYHMDmGuEQbAAG5OyXW76RnHZ-R0GRlwENx0ErPgLL1OEqPccopXAAiIFONAGAiZP4-DIfebfe6POAAARgqAAtFgAB6FfCYqDEKBvOFfZgwMGoCGZEkLMlORFPVEY7G4mD4wlwYlzUnkqo1X5cf4+YGg8GQjLQvnVAU8AEKEUUqkSwU5anc2nkhkotGYnFYPFYAnQODouAAFT06FQOggskMcAARvZkMFDYSAIRcz4anI1OASVBgF0UggGTKB4NvWHqhFwIA

### 💻 Code

```ts
const Link: React.FC<{ url: string, children: React.ReactNode }> = ({ url, children }) => <a href={url}>{children}</a>

type Props = {
    children?: React.ReactElement<typeof Link>
}

const Component: React.FC<Props> = ({children}) => <div>{children}</div>;

// ok
<Component><Link url="">asdf</Link></Component>;

// @ts-expect-error
<Component>asdf</Component>;

// @ts-expect-error 
<Component>
    <Link url="">asdf</Link>
    <Link url="">asdf</Link>
</Component>;

// @ts-expect-error - This should be an error!
<Component>
    <span>asfd</span>
</Component>; 
```

### 🙁 Actual behavior

A non-Link element inside `<Component>` is accepted

### 🙂 Expected behavior

A non-Link element inside `<Component>` should be a type error

**Comment by MartinJohns** [comment]
This sounds like #40364.

**Comment by MartinJohns** [comment]
Related: #21699.

**Comment by Jessidhia** [comment]
This is because the `React.FC` type always intersects props with `{ children?: React.ReactNode }`; same with class components. The only way to avoid that and to only use the `children` you specify is to not use the `React.FC` type (or any of its aliases), which is for the best tbh.
