### ISSUE TITLE
Type aliases do not compose sensibly (should they?)

### ISSUE THREAD

**Issue by masaeedu** [microsoft/TypeScript#42495]
# Bug Report

### 🔎 Search Terms

Type aliases, composition, semantics

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type aliases

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgPADwHxQLxQVCDgQHYAmAzlABSkCUaKAlngGYQBOUA9lQPxtQBcUeEAG7MAUKEhQA4ohTo4rLDnzEMSStTZjw0AGpooRYEzoBzESID0FqAGNWeQ1CYQiAVwA2wAIz76pE6SCFBRaEgBKLh7e+vDSOkgoVhqGxnhmltZ2DsBQABb6mKgofgEIwaHQABIyMXDSyEjmSVmOzm6eAEz6uYEh4tAR7cBd6NXxUElFUK54ANZ4rADueEA)

### 💻 Code

```ts
type F<x> = x extends (() => infer o) ? o : never
type G<x> = <o extends x>() => o
type V = string

// const result1 = f(g(v))
type Result1 = F<G<V>> // => string

// const h = x => f(g(x))
type H<x> = F<G<x>>

// const result2 = h(v)
type Result2 = H<V> // => unknown
```

### 🙁 Actual behavior

`Result1 = string`, and `Result2 = unknown`

### 🙂 Expected behavior

`Result1 = Result2 = string`

I have developed (perhaps incorrectly) a mental model of type aliases as functions from the big un(i)kinded collection of all TypeScript types to itself. I don't have any very precise mathematical picture of this collection, but it is something like the quotient of the collection of type-forming expressions by the relation `X ~ Y`, where `X ~ Y` iff every expression of type `X` is assignable to `Y` and every expression of type `Y` is assignable to `X`. So just as e.g. `x == y => f(x) == f(y)` for a function `f` and values `x`, `y` of its domain, I expect that `X ~ Y => F<X> ~ F<Y>`.

I understand that there are portals like `any` through which eldritch horrors can enter the type system and destroy our sanity, but I take it that these are the exception rather than the rule, and that the design of the language tends towards eliminating as many of these as is feasible without significant compromises.

Today I was surprised to discover that in general the type expression `F<G<V>>` is not equivalent to the expression `H<V>`, where `H` is the composition of `F` and `G` (i.e. `type H<x> = F<G<x>>`). Is this a desirable invariant? Is this simply an inaccurate mental model of what type aliases represent?

**Comment by RyanCavanaugh** [comment]
Inlining of `F` produces identical results (just not the results you're expecting), so by some definition of "composition" everything is working exactly correctly
```ts
// unknown
type H_inline1<x> = (<o extends x>() => o) extends (() => infer o) ? o : never;
// string
type H_inline2 = (<o extends string>() => o) extends (() => infer o) ? o : never;
```

The rule we have in place, whose origins I do not recall, is that during the `infer` step we substitute type parameters with their base constraint

**Comment by masaeedu** [comment]
@RyanCavanaugh I don't quite understand in what sense those results are identical. One is `unknown`, and the other is `string`. I would expect that `H_inline1<string> = H_inline2 = string`.

The problem is precisely that "de-inlining"/eta expansion produces distinct results, which means you cannot reason about type aliases in a referentially transparent manner, as if they were functions.

**Comment by RyanCavanaugh** [comment]
@weswigham are there any tweaks to type alias deferral we could do to make this behave more predictably?
