### ISSUE TITLE
'hourCycle' missing from interface Intl.DateTimeFormatOptions

### ISSUE THREAD

**Issue by jacobmadsen** [microsoft/TypeScript#42494]
# Bug Report

### 🔎 Search Terms

- Intl
- DateTimeFormat
- DateTimeFormatOptions
- hourCycle

### 🕗 Version & Regression Information

4.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHIAsHsFcCcDCBPAxgGwKblASwM6gC2B+uAdgOYCwAUKAC7IAOmoA1psoQLwdfQAZqACS5BugB0AEQCGDTABVcRTADFo8IvIDyzBrmjl8dOiFCQGDZvgBcIACaYAbpnTRW8SUWgAvXOjospKalMCY5AC0AKoAysAO0Kj4wADqmABGwABSss6ysajwuPrAAEqYgpjwEaiYwADi7hmy6AD6OhkAVpioDCliEsAAMkmt9TAIKBiYdIwsbJNIaFigfFAAjBs4AD4QkBsATLv7hwDMJ1CHACzgQA)

### 💻 Code

```ts
// 'hourCycle' is missing
 type keys = keyof Intl.DateTimeFormatOptions

// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycle
 type hourCycle = 'h11' | 'h12' | 'h23' | 'h24'
```

### 🙁 Actual behavior

`hourCycle` is missing from interface Intl.DateTimeFormatOptions

### 🙂 Expected behavior

`hourCycle` is missing from interface Intl.DateTimeFormatOptions:

```ts
export interface DateTimeFormatOptions {
  hourCycle?: 'h11' | 'h12' | 'h23' | 'h24'
  ...
}
```

**Comment by DanielRosenwasser** [comment]
Looks like it's in `es2020.intl`, so you might need to specify that in your `lib` settings:

```ts
"compilerOptions": {
  "lib": ["dom", "es2019", "es2020.intl"]
}
```
