### ISSUE TITLE
Terser syntax for discriminated unions

### ISSUE THREAD

**Issue by Timmmm** [microsoft/TypeScript#42497]
# Suggestion

[Discriminated unions](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions) are great, but they're very tedious to write, especially if you use a proper `enum` rather than strings for the tag:

```ts
enum NetworkStateTag {
  Loading,
  Failed,
  Success,
}

type NetworkLoadingState = {
  state: NetworkStateTag.Loading;
};

type NetworkFailedState = {
  state: NetworkStateTag.Failed;
  code: number;
};

type NetworkSuccessState = {
  state: NetworkStateTag.Success;
  response: {
    title: string;
    duration: number;
    summary: string;
  };
};

type NetworkState =
  | NetworkLoadingState
  | NetworkFailedState
  | NetworkSuccessState;
```

It's a common pattern, and every time I write them I think "ugh I wish this was like Rust enums". It would be really nice if there were a terser syntax for it.

## 🔍 Search Terms

tagged discriminated union enum syntax verbose terse terser 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I don't have a specific syntax in mind. I just want something shorter. I'm not the only one - someone wrote [an entire library](https://paarthenon.github.io/variant/docs/intro) to improve this, though I think their syntax is kind of horrible:

```ts
export const Animal = variantModule({
    dog: fields<{name: string, favoriteBall?: string}>(),
    cat: fields<{name: string, furnitureDamaged: number}>(),
    snake: (name: string, pattern = 'striped') => ({name, pattern}),
});
// optional, but very helpful.
export type Animal<T extends TypeNames<typeof Animal> = undefined>
    = VariantOf<typeof Animal, T>;
```

Here's a random idea:

```ts
discriminated enum NetworkState(state) {
  Loading: {},
  Failed: {
    code: number;
  },
  Success: {
    response: {
      title: string;
      duration: number;
      summary: string;
    },
  },
}
```

So much shorter!

**Comment by RyanCavanaugh** [comment]
See #36336
