### ISSUE TITLE
ReturnType can not infer promise return type right

### ISSUE THREAD

**Issue by qiyuan-wang** [microsoft/TypeScript#42493]
# Bug Report

### 🔎 Search Terms

- ReturnType
- Promise

### 🕗 Version & Regression Information

- This changed between versions 3.7.3 and 4.1.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABACxgc2QeQE4BMCm2APACqL4AeU+YuAzogBQCG2adAXIgN6IDaAa3wBPLnSjYYYNAF0uzMMMQBfAJSIAvAD5EABWxwAtjDr4iAZS0AaRJcYAoRImBguJe6q6MAdL9CQAQTZOPVZmQ3xqbDpSLXVtRAAlSJBsMBJhAAczEh1uR0RsFLSmX29Wdi5dMIiomNzPJOL0rJydBPynJyKoVKQXFmDVAG4C5VHlIA

### 💻 Code

```ts
function highOrder<T extends (args: { [key: string]: any }) => Promise<S>, S>(
  fn: T
): (...funcArgs: Parameters<T>) => ReturnType<T> {
  return (...args: Parameters<T>): ReturnType<T> => {
    return fn(args);
  };
}
```

### 🙁 Actual behavior

compiler says: Type 'Promise\<S\>' is not assignable to type 'ReturnType\<T\>'. and failed to compile.

### 🙂 Expected behavior

As code above,  'Promise\<S\>' is the return type of T.

**Comment by dragomirtitian** [comment]
Just a suggestion, change your type argument so you don't have to use `Parameters` and `ReturnType`:

```ts
function highOrder<T extends any[], S>(
  fn: (...args: T) => Promise<S>
): (...funcArgs: T) => Promise<S> {
  return (...args: T): Promise<S> => {
    return fn(...args);
  };
}
```
[Playground Link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABACxgc2QeQE4BMCm2APACqL4AeU+YuAzogIZgCeA2gLoA0iAygHwAKAFCJEwMAC5EggHTzG2NHWkkAlIgC8-RAAVscALYw6+IgOFrpc+aEgBBJSsTqtO-UZNmBiAN6jEbHwoEGwkG1lFZVUrPQNjU3MdbT8AsSCQsPEwCKi6NQBuAIBfIuKgA)

Conditional type assignability is generally difficult when you still have unresolved type parameters, so `ReturnType<T>` is not obviously assignable to `Promise<S>`.

**Comment by RyanCavanaugh** [comment]
I'm not sure why this ever worked, but in general a call on a constrained generic like that always produces a nongeneric return value derived from the constraint type, not an indirected `ReturnType<T>` value, so there's no way for TS to know that the right thing is happening. @dragomirtitian's suggestion is good

**Comment by qiyuan-wang** [comment]
@dragomirtitian maybe set constraint on function is not a good idea.
