### ISSUE TITLE
`arguments` not in intellisense list

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#4249]
Start typing `argu` in a function body and the only suggestion is the `IArguments` interface.

What's more annoying is that VS Code always accepts the first item in the list on the dot key no matter what you have typed...

 (I do not think it normally suggests interface names in non-type positions, so I guess somewhere in the code the interface is confused with the `arguments` keyword?)

**Comment by mhegazy** [comment]
`arguments` is never put in the completion list (see #2433). we could inject it in the list if you are requesting completion inside a function.

**Comment by SamuelEnglard** [comment]
I'd like to second the request for it to be in the auto completion inside a function.

**Comment by mhegazy** [comment]
Thanks @Schmavery!
