### ISSUE TITLE
Private and protected modifiers are removed without error in declaration emit if class expression is passed through a generic function

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#42499]
# Bug Report

### 🔎 Search Terms

class expressions private protected declaration
mixins private protected declaration

### 🕗 Version & Regression Information:

- This is the behavior in every version I tried 3.3 - 4.2@beta

### ⏯ Playground Link

[Playground link with relevant code](ng-typescript.org/play?ts=4.1.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFssAPAHgBUBZEgPgAojitUAueKkgSjY+IG4AUALB4AzhngARLKIAOOUVABGEENSb4AvPEhRRo+AG8B8U-FkwcGcNeDwA+nmlyFIOpyMmz3jAAsZAHT2eqIgMBgAkqIAyhgwWLKyIMDuXqYAvmnm8QBuUNYOIWGRMXEJSSkext6Z6YICAPQN8ACixEmYyfBhljDwosxgCKC6MPm4+DLwqFbwcBYgoagYyqrwjc0g7TjhOmISzvKKKmokzC0wvfDahCR0hwqrpxqc9U3wAHI43Zc7ADTwJTICSgRDMLDYPDwKYAd0sqAA5gF1lt5LtQVBkBAJIx7jIjk91MxXgJUTsJLp9PBKHgITtusRrKhgAZcQ9jqoiagqlkLFYbF1HKh2W4eTUBJkgA)

### 💻 Code

```ts
declare function mix<TMix>(mixin: TMix): TMix;

const DisposableMixin = class {
    protected _onDispose() {
        this._assertIsStripped()
    }
    private _assertIsStripped() {
    }
};

// Expected error since declaration is not representable 
// export const DisposableMixinError =  mix(DisposableMixin);

// No error, but definition is wrong. 
export default mix(DisposableMixin);
export class Monitor extends mix(DisposableMixin) {
    protected _onDispose() {
    }
}
```

### 🙁 Actual behavior

Emitted declaration erases `private` and `protected` modifiers on `DisposableMixin`. This actually generates a ts error in the declaration of `Monitor` on the `_onDispose` override, since the method has a more restrictive modifier than the emitted declaration for the base class.

```ts
declare const _default: {
    new (): {
        _onDispose(): void;
        _assertIsStripped(): void;
    };
};
export default _default;
declare const Monitor_base: {
    new (): {
        _onDispose(): void;
        _assertIsStripped(): void;
    };
};
export declare class Monitor extends Monitor_base {
    protected _onDispose(): void;
}
```
[Playground Link](https://www.staging-typescript.org/play?ts=4.1.3#code/CYUwxgNghgTiAEYD2A7AzgF3gfVAMygFcIMAueAbwCh5b4UQB3eACgEpzq7udUARAJZoADkjQh25AG5IBwANw0etbFDTiYGAJJoAyhhgDhwkMEnwZcxdwC+iu1RAAPUZvj4iJHB+IZFoSFgEZHQsAFlUAQwkGGwAIzUQTiVaBmZzLmVeFEERMQkOC1kFFJ5VdRBNHX1DY1NzSxLbe0VnVywA6DhEaHV4CJQomPhnDBAUYDR+yOjYhPFKUuEYJDGwMeBs3NFxBuL7KiA)

### 🙂 Expected behavior

An error on the exported private and protected members (like what happens if you uncomment `DisposableMixinError `):

```
Property '_onDispose' of exported class expression may not be private or protected.(4094)
Property '_assertIsStripped' of exported class expression may not be private or protected.(4094)
```

### Note

This issue might be made moot by #41581 in 4.3, or later, depending when declaration emit will be changed to use `typeof class`

**Comment by MartinJohns** [comment]
#36060

**Comment by dragomirtitian** [comment]
@MartinJohns I agree that issue is related and I did find it. But this issue is specifically the absence of the error the other issue is complaining about. If private and protected are forbidden in exported class expressions this should be uniformly enforced. 

The fact that it isn't uniformly enforced causes some code of ours to fail when using the emitemted declarations, even though they are emitted from error free code.
