### ISSUE TITLE
Possible breaking change: assigning array to 1-tuple

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#42504]
# Bug Report

### 🔎 Search Terms

dom, tuple, assignability

### 🕗 Version & Regression Information

Repros in 4.2 Beta and nightly

- This changed between versions 4.1.3 and 4.2 beta

**Important caveat:** The code was originally building against 4.1 and had polyfills for types that are in lib.dom.d.ts in 4.2.

### ⏯ Playground Link

TS 4.1.3 with polyfills: [Playground](https://www.typescriptlang.org/play?ts=4.1.3#code/JYOwLgpgTgZghgYwgAgEoQM7AF4QPIBGG0AbtAMJwA2VBiA1sgN4BQyyAFBOFMJgFxpMOfEVLQAojwCeAbQC6AGmQB7MVDJRB6LLkLEN0AJSCSK4ABMA3CwC+LFqEixEKHSP3ioUsFGnM2ZCgIOAsVECp-MDgoAHMIMEEJKggAW24wG3Zg0PDI5ARwyHB0BETkABE8AFlSsHRQvAjpG3tHcGh4JCFdUQNNAPY1fogOaLiEpJT08BNkM0ss5ABXEGHxMZj48uS0jLmF60CLYAxCkBAIMo4D8yO2p07XHo91TQBJEAxokG7WbJCYWayAADlAVGAIdIQRBtMI9G9oEtLgB3TgIai0Bhw3qeQxQSg0OgIehzdwIkZQVoOCxXKgxFApMAvCleHGvSmfb5wX4QGztZxdFAAdVAYTR-yCgLy-nJfTZLPl+K5PyQ1JY52+UtxiKgyAAvMhUYq8ZoOBxZBk-PJ2az8T4-AojAaAHyDZBW6R2IxWIA)

TS 4.2 beta with re-declaration of lib.dom.d.ts interface: [Playground](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/JYOwLgpgTgZghgYwgAgEoQM7AF4QPIBGG0AbtAMJwA2VBiA1sgN4BQyyAFBOFMJgFxpMOfEVLQAojwCeAbQC6AGmQB7MVDJRB6LLkLEN0AJSCSK4ABMA3CwC+LFghUgMYZFGF71m5AF5kIBAA7kK6ogaaHByy3GBQ0vJGfgB8zGzIsfF2RlZAA)

### 💻 Code

```ts
interface ResizeObserverCallback {
  (entries: ResizeObserverEntry[], observer: ResizeObserver): void;
}

const resizeObserver = new ResizeObserver(([entry]) => {
  entry
});
```

### 🙁 Actual behavior

```
Argument of type '([entry]: [any]) => void' is not assignable to parameter of type 'ResizeObserverCallback'.
  Types of parameters '__0' and 'entries' are incompatible.
    Type 'ResizeObserverEntry[]' is not assignable to type '[any]'.
      Target requires 1 element(s) but source may have fewer.(2345)
```

### 🙂 Expected behavior

The fact that the repro depends on re-declaring a dom interface is suspicious, but the re-declaration appears to be identical, so it's not obvious to me why this error would be produced.

Also, note that the (as a result of sensible variance reasons), the lambda parameter is listed before the callback parameter on line 2 of the error and the types are in the _opposite_ order on line 3 of the error.  I found this confusing.

**Comment by amcasey** [comment]
@RyanCavanaugh suggested we should probably be using the contextual type `ResizeObserverEntry[]`, rather than the expression type `[ResizeObserverEntry]`.

**Comment by weswigham** [comment]
Multiple overloads -> multiple signatures contextually typing the expression -> no contextual type applied to the expression.

**Comment by amcasey** [comment]
@weswigham Even when the overloads are identical?

**Comment by weswigham** [comment]
`getContextualSignature` merges identical signatures across a union of types, but not identical signatures within a single type (`getContextualCallSignature` returns nothing for types with > 1 signature).

**Comment by RyanCavanaugh** [comment]
Given the root cause I don't think this merits documenting -- we fill in DOM signatures every release and while the downstream behavior here is surprising, it's not at all new.
