### ISSUE TITLE
Loss of inferred generic parameter in mapped type

### ISSUE THREAD

**Issue by chmln** [microsoft/TypeScript#42509]
# Bug Report

### 🔎 Search Terms

- inference
- generic parameter inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generic parameter inference over mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAsg+gZQPYFcBOBjCAeBA+KAXigCUIMk0ATbAZ2DQEsA7AcwBooAKAQwC4oCTgDpRPNK1oCezEAG0AugEoiBfAG4AUKEiw4AEQj1cnACpQIAD2ARmVWnuTosuPAWIBvTVChyA1lAsUH4QIEgAZlCmCgKm-goW1rb23PyCImISUoHM4RBoUACCKoRq3j5QAPzcosLMEADuhVkCxapQAG5IjFTlPgL1HflaAL5a2uDQpoiomDhCsIk2dg7wTnOu7qTklDTl9Exs7OVc4Yxo9M2sAh5Q4QBMAvCGxgswBCMZwmhGwNKyihKBC6PU0eHGOmgAElmGAUMATLAzFsvD5wgBGAQILRox6wHFQCgAWzhNiolVio3GFGY9CgtB4JIANtBiIiYEtkqsZs55ngzJyVlEeRs3m4uOU4CxSQIYaT2cjNECoB4xppNAzmRAuKi7piVVBLAJ0VBPuUHjc+lAqEhkESIMAABYsa7cDGcOC0JD2uBgcSMgYoIkAI3yyvd5TNPmJpIgVEtFWttu9DudbFO50uEhUusTAHo81AnYwHLRHagmVQ7jxGEyrWjM8ArsIHsIbXbUy6uEoCT4o6bjiMe5ogA)

### 💻 Code

```ts
type M_Source<S> = Record<string, (a: S, ...args: any[]) => S>;

type M_Dest<S, T extends M_Source<S>> = {
  [k in keyof T]: T[k] extends (a: S, ...args: infer A) => S
    ? (...newArgs: A) => void
    : never;
};

type T_Source<S, M extends M_Source<S>> = Record<
  string,
  (firstArg: { f2: M_Dest<S, M> }, ...rest: any[]) => void
>;

type Input<S, M, T> = {
  f1: S;
  f2: M;
  computed?: T;
};

const sample = <S, M extends M_Source<S>, T extends T_Source<S, M>>(
  _input: Input<S, M, T>
) => {};

sample({
  f1: { x: 1 },
  f2: {
    doSomething: (f1, _some_param: number) => f1,
  },
  computed: {
    doSomething(firstArg) {
      // this should fail
      firstArg.f2.doSomething();
    },
  },
});


```

### 🙁 Actual behavior

In the computed section, the `doSomething()` is typed as `(...any[]) => void` and thus bypasses the typechecker.

To elaborate, while the `sample` function correctly infers the type of `M`, using `M` in a mapped type unexpectedly passes `M` as the "parent" type which M extends.

### 🙂 Expected behavior

In the computed section, the `doSomething()` should fail as its missing an argument.

**Comment by andrewbranch** [comment]
Haven’t quite figured out what’s going on here yet, but did find a workaround: if you give `f1` (in `f2.doSomething`) an explicit type annotation, it works as expected.

**Comment by andrewbranch** [comment]
[Simplified repro](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAsg+gYQPYDsDOwBOBDAli4KAXigCUIBjJTAEwB4NN8BzAGigApsAuKbFEOwB0I7JmZpe-EAG0AugEpiAPj4DlAbgBQW0JCgAVRKkZ4CdGKpIcAZrkwYAguN4wlRVQDckuGtq00lAA2YtA2AK4oFMC4qFA2FlAQAB7AECg0aLDG6FhmwOwGSanpmYY5pvjAFsrKHFpQUPhg4cC8AN4NjVAAtq6sXY1thl0AvloKvN6+-jYcnY19UO1QNEgAykg9EMAAFiy8tgCMUAD0AFS8jCxQ56fscGhbEHBgYthLKOE9AEYQmO5VDYTqMBkNDnYHMBnMxActBvF7E5xEI1pttnsWBwAETYhRjAajBTaIA)

**Comment by andrewbranch** [comment]
What’s happening is that there are no inference candidates for `T` (since everything in `computed` is context-sensitive), so the contextual type for `computed` falls back to the constraint of `T`, but `M` is still resolving, so its base constraint gets used too. I think the workaround I mentioned before is the “correct” solution.
