### ISSUE TITLE
function type allowing extra props returned in specified return type

### ISSUE THREAD

**Issue by btrauma8** [microsoft/TypeScript#42517]
![image](https://user-images.githubusercontent.com/4399964/106036712-4a704080-609b-11eb-8e52-61ce0b9593c8.png)

**Comment by MartinJohns** [comment]
Working as intended. The return type of your anonymous method is inferred, because it's not specified. Then at the assignment it's checked if your types are compatible, which they are - the additional properties don't cause incompatibility.
