### ISSUE TITLE
ReturnType<SomeClass["someMethodWithOverloads"]> incorrect result

### ISSUE THREAD

**Issue by david-fong** [microsoft/TypeScript#42510]
# Bug Report

### 🔎 Search Terms

- ReturnType
- overload

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (on the playground, the lowest version is 3.3.3), and I reviewed the FAQ for entries about function and method typings.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDC5WgbwLAChqegBwK4CMQBLYaAWwFMAXACwHsATACmzACcwyAuaABgEoe+OnRAUwAOwDc6LDgLFSlWoxbtOPAIyDoEKmyISA5jIxY8hEuWr1mrDt2gAmHbSIRTci4usq76xwlcMnwKNh1hUXEJaAAfXX1DIzjoNxhUMzlMCAB3IipgGmg1B35kWSzK4EgKPh42alw2GP1cCk9KrOqIWs16xuboACI9A2Mhjs6sbtqnfqomlpp3SanoBgoAMzBcECoeWjY6HOgJChOAUTYjtiZ+VbkAXwrMZ7Q3qgBPbFqAFW+KABBYiQaAAXmgACUBhJ-j8ADzwSAQADaQ2UtiGAF0AHxSaAAegJ0Hc0AABkioGSAHTQCgADx+wCoFAY5MiYkkKVGSRSlIgZKAA)

### 💻 Code

```ts
class Class {
    public method(param: 0): boolean;
    public method(param: 1): string;
    public method(param: 2): this;
    public method(param: number): boolean | string | this {
        switch (param) {
            case 0: return true;
            case 1: return "string";
            case 2: return this;
            default: throw new Error();
        }
    }
}
type TypeAlias = ReturnType<Class["method"]>; // is `Class`. expected `boolean | string | Class`;
```

### 🙁 Actual behavior

If you shuffle the order of the overload definitions, the last one (the _non-implementation_ one) becomes the type given by `ReturnType<Class["method"]>`.

### 🙂 Expected behavior

The return type indicated by the method signature that provides the function body should be given by `ReturnType<Class["method"]>`

**Comment by MartinJohns** [comment]
Conditional types do not work with overloads. This is mentioned in the documentation.

**Comment by david-fong** [comment]
> Conditional types do not work with overloads. This is mentioned in the documentation.

I see. Thank you for explaining and sorry I didn't catch this before I made this issue! Feel free to close it.

**Comment by david-fong** [comment]
For anyone that stumbles upon this issue I mistakenly made, here are a couple of related links:
- https://stackoverflow.com/a/52760599/11107541
- https://github.com/Microsoft/TypeScript/issues/26048
- https://github.com/microsoft/TypeScript/issues/37079

I clearly was not looking hard enough. Again, sorry.

**Comment by MartinJohns** [comment]
> I wish the Conditional Types page on the typescript website made this clearer.

[Type inference in conditional types
](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types)

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the *last* signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.
