### ISSUE TITLE
Cannot augment UMD module definition if the global variable name is different than module name

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/TypeScript#42535]
# Bug Report

### 🔎 Search Terms

module UMD augmentation name variable export declare

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about declaration merging

#### Not working example:
```ts repro
// @allowJs: false

// @filename: node_modules/@types/awesomeness/index.d.ts
declare namespace awesomeness {
  interface AwesomenessApi {
    base(): void;
  }
}
declare var awesomenessModule: awesomeness.AwesomenessApi;
export = awesomenessModule;

// @filename: src/augs.d.ts
import 'awesomeness';
declare module 'awesomeness' {
  interface AwesomenessApi {
    aug(): void;
  }
}

// @filename: src/app.ts
import * as awesomeness from 'awesomeness';
awesomeness.base();
awesomeness.aug();
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?module=1&allowSyntheticDefaultImports=true&ts=4.2.0-beta#code/PTAEAEEMBtoewO4CkDOAuUAzGKCmAofECTAS2lwDtIBbXDSuAE1wH0bmBXClYcAFwCeAB1y9ICMXDqUxvUpRYAPAHRMV-FPhYBjaJABOuUNTophkHcYlSZc0AG98oUAv64D2K6ACCklNJUcj7CpI7OLqAARpB4ABQAlBgAbnCkTADcEQC++Lm6+kagyYagNgF2KCgAslwUGOWBslUqfrZBVSGkWbhKwnAG-KAAvGX+TXK1TNy4WURg4GQUpvSgKAY6wJCcAOYoahpapDT9g6AA5I2VKOdZBYbGHNMUF1cdN+Eubh5exm0V7y6n0i2x2iRSaUyOTyhGIi3IVFoq3Wm0gwmEh3wx1OQwAVGUUGN2s1CZgDNJXuNrrd8G8SSoYvEElk6XIVKDEhkgA)

#### Working example:
(The only difference is at lines 9-10)
```ts repro
// @allowJs: false

// @filename: node_modules/@types/awesomeness/index.d.ts
declare namespace awesomeness {
  interface AwesomenessApi {
    base(): void;
  }
}
declare var awesomeness: awesomeness.AwesomenessApi;
export = awesomeness;

// @filename: src/augs.d.ts
import 'awesomeness';
declare module 'awesomeness' {
  interface AwesomenessApi {
    aug(): void;
  }
}

// @filename: src/app.ts
import * as awesomeness from 'awesomeness';
awesomeness.base();
awesomeness.aug();
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?module=1&allowSyntheticDefaultImports=true&ts=4.2.0-beta#code/PTAEAEEMBtoewO4CkDOAuUAzGKCmAofECTAS2lwDtIBbXDSuAE1wH0bmBXClYcAFwCeAB1y9ICMXDqUxvUpRYAPAHRMV-FPhYBjaJABOuUNTophkHcYlSZc0AG98oUAv64D2K6ACCklNJUcj7CpI7OLqAARpB4ABQAlBgAbnCkTADcEQC++Lm6+kagyYagNgF2KOhl-oGyVSp+tkFVIaRZuErCcAb8oAC8Nc31KFlEYOBkFKb0oCgGOsCQnADmKGoaWqQ03b2gAOTldXL7WQWGxhxM3MaHtZUo++Eubh5exk0VLShtz5HLK0SKTSmRyeUIxEm5CotFm80WkGEwk2+G2uz6ACoyighl8RlgDNIDkcHqd8CTvioYvEElkKSMVADEhkgA)

### 🙁 Actual behavior
You can perform augmentation of UMD module definitions only if the global variable's name used for export matches the name of the module (i.e. folder in node-modules). I also tried changing `declare module 'awesomeness'` to `declare module 'awesomenessModule'`, so that the module itself can be resolved, with no luck.

It is possible that this is intended behavior, I've missed something or alike. In that case, how can I force the code above to work (as I obviously cannot modify original module definition)?

**Comment by RyanCavanaugh** [comment]
The original module is, perhaps intentionally, written in a way that prevents augmentation because there's no accessible name by which to augment `AwesomnessApi`. The impact-free fix in the upstream declaration is to write it this way (note that the module name is not really relevant here):
```ts
// @allowJs: false
// @skipLibCheck: false

// @filename: node_modules/@types/awesomeness/index.d.ts
declare namespace awesomenessModule {
  interface AwesomenessApi {
    base(): void;
  }
}
declare var awesomenessModule: awesomenessModule.AwesomenessApi;
export = awesomenessModule;

// @filename: src/augs.d.ts
import awesomeness = require("awesomeness");
declare module "awesomeness" {
  interface AwesomenessApi {
    aug(): void;
  }
}

// @filename: src/app.ts
/// <reference path="./augs.d.ts" />
import * as awesomeness from 'awesomeness';
awesomeness.base();
awesomeness.aug();
```

**Comment by mcpiroman** [comment]
Ok, so if it is intended (or just known), is it stated somewhere that the module name must match the variable? Because it took me quite more than quite a lot of time to figure this out. Ideally it'd be nice if there was a warning of some kind but I'd assume this is too niche of a scenario for that. On the other hand, module authors might not be aware of this requirement on their side.
I also assume you just can't make it work for some many internal and compatibility issues, which I'm fine with.





> ```ts
> // @filename: node_modules/@types/awesomeness/index.d.ts
> declare namespace awesomenessModule {
>   interface AwesomenessApi {
>     base(): void;
>   }
> }
> ```
You just changed the namespace in the upstream, right? Then that won't resolve the issue. Fortunately the module in question just got a fix for that (renamed a var); I'm asking just in case someone else or I come to this situation again.

**Comment by RyanCavanaugh** [comment]
They don't "have to match"; it's simply a consequence of the definition of what `export = ` means and the fact that augmentation can only function on exported identities (which is a logical consequence of non-exported entities being opaque, by design). It's like if I said "You can take all the blue things out of this box" and then you wanted something from the box that was red - it's not an error or even suspicious to not have all things be blue, and it's not an error or even suspicious to restrict takings to a specific color.

There's nothing wrong with the declaration file as written per se, and again, the author may have written it that way on purpose.
