### ISSUE TITLE
No autocompletion on type arguments 

### ISSUE THREAD

**Issue by williamluke4** [microsoft/TypeScript#42531]
# Bug Report

### 🔎 Search Terms
-  autocomplete type parameters
-  type argument autocompletion

### 🕗 Version & Regression Information
- Occurs on both Nightly and Stable

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATgQUQczlAvFA3gKCiKgQBsIBjYAfgC49DimBLAEzqgCMB7b8gQwB2jJkQgBbfs1IcefCEJFQAvgBolzQRVIBXVhA4FRxMNzjA4s3gMFQlTUswDWES-Tk2ly-N9CRYCIgA4hDAAAr8IKTc-KwAPAAqUBAAHsAQgqyY8EioGAB82FAJ+PgU3ILmUOnmtDnBoRFRMfFGxAD07VAActxQyDrA3OXiYOTAzBV2TD6FOLjKQA)

[Nightly Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATgQUQczlAvFA3gKCiKgQBsIBjYAfgC49DimBLAEzqgCMB7b8gQwB2jJkQgBbfs1IcefCEJFQAvgBolzQRVIBXVhA4FRxMNzjA4s3gMFQlTUswDWES-Tk2ly-N9CRYCIgA4hDAAAr8IKTc-KwAPAAqUBAAHsAQgqyY8EioGAB82FAJ+PgU3ILmUOnmtDnBoRFRMfFGxAD07VAActxQyDrA3OXiYOTAzBV2TD6FOLjKQA)

### 💻 Code

```ts
type UserArgs = {
    select?: {
        id?: boolean
        email?: boolean
    },
    include?: {
        posts?: boolean 
        likes?: boolean
    }
}
type UserGetPayload<T extends UserArgs> = T

const test:UserGetPayload<{
    // No Autocompletion
    
}> = {}
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/10773719/106113365-7654fa00-615f-11eb-8cd3-d1da23de8a4e.png)

### 🙂 Expected behavior
It should provide autocompletion using the type `UserArgs`

Related Issues
- https://github.com/prisma/prisma/issues/4968

**Comment by DanielRosenwasser** [comment]
Hm - I think this may be a duplicate of #33302. @andrewbranch did we do some work in a related area a while back? I know we've done this for string literals.

**Comment by andrewbranch** [comment]
It reminds me of work we did on object literal (expression) member completions contextually typed by constrained type parameters, but this should be much easier to fix than that. It does look like an exact duplicate of #33302 to me.

**Comment by williamluke4** [comment]
Closing as it's a duplicate
