### ISSUE TITLE
Not narrowing nested discriminated union

### ISSUE THREAD

**Issue by jonhue** [microsoft/TypeScript#42548]
# Bug Report

### 🔎 Search Terms

`nested discriminated union`

This issue is definitely related to #18758, but it is different from that issue in that the tag is also present in the top-level type.
As in the top-level type, the nested types form a generic union, I believe this is also related to #13995.

### 🕗 Version & Regression Information

This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBA0gliAJlA3gKAJAEEA0mBCeAvmmgC4CeADsFAJIgjABOWUAvKpgNYKIBcUSjQD2AM1h8AdFjQlhtBk2b4OXDLySCF4yUin45pBfUYs1SlmwA+p5YfLVaAeTBkWAHgAqUYAA93JABnO3NOS2YAPjV0DT5BLwBtAHJNRGSAXUwEZQSjNABjERAgsigACwBDJAAbYAi2TgAKHJZBBoBKDmiUEiKSsqra+rMVNRbR9tH8LvYekkLi0qgxEHGRNzaoV3dmWZ7MIIB3ODIC8qgmjd2pNK7YjALKoNp4fSx+TAwMZmAyMGYayGiDqDSum2YUlaey+TxeekQBk+3x+fwBQOqIJG9nBN2hHUwJBIQA)

### 💻 Code

```ts
enum Kind {
	A,
	B,
}

type InnerA = {
	kind: typeof Kind.A
}
type InnerB = {
	kind: typeof Kind.B
}

type Inner = InnerA | InnerB

type Outer<T extends Inner = Inner> = {
	kind: T['kind']
	inner: T
}

const handleInnerA = (inner: InnerA) => {}
const handleInnerB = (inner: InnerB) => {}

const fn = (outer: Outer) => {
	switch (outer.kind) {
		case Kind.A:
			return handleInnerA(outer.inner)
		case Kind.B:
			return handleInnerB(outer.inner)
	}
}
```

### 🙁 Actual behavior

The above code should compile without errors.

### 🙂 Expected behavior

The type of the `inner` property on `outer` should be narrowed based on the value of `outer`'s `kind` property.

**Comment by RyanCavanaugh** [comment]
Narrowing here would be unsound because this is a legal call:
```ts
const p: Outer = { kind: Kind.A, inner: { kind: Kind.B } };
fn(p);
```

See also #27808

**Comment by jonhue** [comment]
oh yes, thanks! you're absolutely right
