### ISSUE TITLE
Spreading in generic fuctions doesn't compose correctly with descructing arguments

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#42552]
# Bug Report

Destructuring spread arguments without also spreading the destruction results in invalid data (verses static types).

### 🔎 Search Terms
- spread
- function
- args

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried
- First saw in version 4.1.2
- Tried 4.2-latest and 3.3.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggTgcwM5QLxQNpOHAlgOwQBop8BXAWwCMI4BdAbgCgmAzM-AY2FwHt8orXrwAUGVrjjYSSCJ34ATOgC5YiJAEpVAN164FUAN5MopqPPxJeAGwgA6a7wQiJU4DLmKNTAL4t2XDz8UPwAYsIAPAAqUBAAHsAQ+AooAIb4IBh0AHwu+KoidkWp6qpRWRpo2VC6+iRFdiXIZVo1egbGZoL4hcXqGsx+TGHCLsIkAESpSBMkAIwDQA)

### 💻 Code

```ts
type Args = [string, number];

function foo([first, second]: Args): void {
    console.log(first, second)
}

function onFoo<T extends any[]>(fn: (...args: T[]) => void, ...args: T): void {
    fn(...args);
}

onFoo(foo, "as", 1);
```

### 🙁 Actual behavior

Typechecking succeeded and the output was `[LOG]: "a",  "s"` instead of the expected `[LOG]: "as", 1`

### 🙂 Expected behavior

To not pass typechecking because either line `8` is wrong (spreading the arguments shouldn't pass) or line `11` is wrong because `Parameters<foo>` is `[Args]`.

**Comment by RyanCavanaugh** [comment]
The correct signature for `onFoo` is
```ts
type Args = [string, number];

function foo([first, second]: Args): void {
    console.log(first, second)
}

function onFoo<T extends (...args: any[]) => void>(fn: T, ...args: Parameters<T>): void {
    fn(...args);
}

// OK
onFoo(foo, ["as", 1]);
// Error
onFoo(foo, [1, 1]);
```

You have two options for the constraint when you write `onFoo` with what is ultimately an incorrect signature - with `extends any[]`, you'll be able to use `args` as an `any[]` in the body of `onFoo` and anything goes. You could instead do `extends unknown[]` and get an error on the spread call, but it'll be an error no matter what.
