### ISSUE TITLE
IntelliSense/navigation for private class member crashes VS 2015

### ISSUE THREAD

**Issue by LordJZ** [Microsoft/TypeScript#4255]
To reproduce, create an empty typescript project, add 2 typescript files.

In file1.ts add this:

    class C {
        private v = 10;
    }

In file2.ts add this:

    var g = new C().v;

Put caret after the dot `.` before `v`. VS 2015 crashes immediately. (If not, try to navigate to declaration of `v`.)

**Comment by vladima** [comment]
I can repro this locally. 
Pinging @CyrusNajmabadi, who've recently done a major rework in this area: can you please check if  this bug still occurs in your bits?

**Comment by mhegazy** [comment]
@CyrusNajmabadi and @vladima is there anything we can do until the roslyn fix goes out? this is the second report of this issue. see  #4129.

**Comment by CyrusNajmabadi** [comment]
@vladima Is working on a local workaround.  Until the Roslyn fix goes out we can address this by not returning tags for documents that Roslyn did not ask for.

**Comment by vladima** [comment]
resolved in #4279
