### ISSUE TITLE
Compiled typescript project with baseUrl configuration not working

### ISSUE THREAD

**Issue by RoeiRom** [microsoft/TypeScript#42565]
# Bug Report

When I compile a typscript project (using tsc) I cant run the compiled project because it can't find the modules that their imports are written with the baseUrl shorthand

### 🕗 Version & Regression Information

   version 4.1.3

### ⏯ Playground Link

the playground is the repo because it is backend service
[github repository](https://github.com/RoeiRom/Typescript_With_Base_URL)

### 💻 Code

It is the whole repository 
[github repository](https://github.com/RoeiRom/Typescript_With_Base_URL)

### 🙁 Actual behavior

The compilred project project 

### 🙂 Expected behavior

That the project will work

**Comment by MartinJohns** [comment]
TypeScript is not going to rewrite the import paths at compile time. The features baseUrl and paths are for the cases when you use third-party tools that do support this functionality. There are numerous issues about this, just search for "baseUrl rewrite" and make sure to check closed issues as well.

**Comment by RyanCavanaugh** [comment]
`baseUrl` is not a mechanism for build-time aliases. It's for you to inform TypeScript about how your module loader works at runtime. If you runtime module loader doesn't provide baseUrl-style module paths, then it is a configuration error to have written your tsconfig this way.
