### ISSUE TITLE
Add 'fits' keyword to easily check if an object fits an interface or not

### ISSUE THREAD

**Issue by NightshadeX9X** [microsoft/TypeScript#42568]
# Suggestion

## 

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to see a 'fits' keyword added to TypeScript.

## 📃 Motivating Example
The 'fits' keyword would be used in the following way:
Lets say we have the following code written beforehand:
```
class MyClass {}
interface X {
  a: string;
  b: number;
  c: boolean;
  d: boolean[];
  e: MyClass;
  f: {
    g: [number, number];
  };
}
```
Currently, to check if a certain object, e.g. `foo`, fits this interface `X`, we would have to use this extremely long and confusing type check, as follows:
```
const fooFitsX = typeof (foo as any).a === "string" &&
                           typeof (foo as any).b === "number" &&
                           typeof (foo as any).c === "boolean" &&
                           Array.isArray((foo as any).d) && (foo as any).d.every(b => typeof b === "boolean") &&
                           (foo as any).e instanceof MyClass &&
                           typeof (foo as any).f === "object" &&
                           Array.isArray((foo as any).f.g) && (foo as any).f.g.every(n => typeof n === "number") && (foo as any).f.g.length === 2;
```
This code is extremely unpleasant, and it would be nice if the TypeScript compiler could just generate this code for us if we wrote:
```
const fooFitsX = foo fits X;
```

The idea is that the latter would compile to the former (without the type assertions).

This feature would improve the language because it would act as a shorthand method to write code that would otherwise take up a lot more time and space. It could only be implemented in TypeScript and not JavaScript because regular JavaScript doesn't have interfaces. 

This would improve developer experience and would meet TypeScript's design goals.

I feel like this is reason enough for it to be implemented as other simple features that improve developer experience, such as the ?? operator, have already been added.

## 💻 Use Cases
I want to use this to type check objects.
The shortcoming of the current approach is that it is way too complicated, time-taking to write and a pain to understand.
This new feature would provide a much more readable and developer-friendly way to achieve the same result.

**Comment by MartinJohns** [comment]
> [x] This could be implemented without emitting different JS based on the types of the expressions
 > [x]  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
 > [x]  This feature would agree with the rest of TypeScript's Design Goals.

You checked these all, but that's wrong. This would require to emit different JS based on the types, and it's a runtime feature. It would also violate the TypeScript Design Goals 8 and 9 and the non-goal 5.

---

Your best option is to manually write a [User-Defined Type Guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards), to at would encapsulate the code. Or use libraries like [`io-ts`](https://github.com/gcanti/io-ts).
