### ISSUE TITLE
Parameters utility type doesn't evaluate optional function parameters as optional tuple members

### ISSUE THREAD

**Issue by amitbeck** [microsoft/TypeScript#42567]
# Bug Report

### 🔎 Search Terms

parameters utility type optional

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Functions, Type System Behavior

I'm pretty sure this existed ever since the introduction of optional tuple elements. Checked in TS Playground from v3.3 to Nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/KYDwDg9gTgLgBMAdgVwLZwCoQIYGcYCSAxhInAN4BQcNc2AJvcPXALxwDkDT9HANNVq5kRIsFy42nYaPG5+gmgEdk4mAEtSUjirWbEC2gnAAbbImwat7DqDBmLVgwIC+lSusQxgUAGbYxTBx8AGFkfAhUAHkwJ0kqIw1UYCjkGAAuOBRUACMfAG5KN0oiMwkgvBgAZR8AN3VAhNpIMCxKgAoYYMISREy2-GJSPjgciHoAT0z8KE8AcxGicK7o2P1cAH5+7rCI1biASkzaiHV6QqMWgZh2xSM4LsqhvorB3oF72jHJ6ZhZxAWdyMSz2MTi20quxWYPWH0+dCITgAQmkuogMKAMnAZvM4TQjnAAApQSLqXDAAA8YwgJmA5gAfBdmhBWt1bvCHt1nhC3sMgV9xlNsX9cfyaCDoWtSLgeTAoZEYdKpOQHupkqksQBmABMAAZdXAXHj7gFkajSBiQDAtsL-oCjATiaTyVSIDS6Yh6XAAD5wZCIJi+TzMChiuBQYAwZBQMhO1Bk4AAOgjACtgIj2gcmTQ3MVevg4FduoTsFBsKgZUTS+XIz5cBTrjUoPUxABtDhFyocAC6XvYreuz0TMjEEhGHBgAAsyXAZ9hOV3u-kgA)

### 💻 Code

```ts
export enum ToastIcon {
    added = 'added',
    success = 'success',
    question = 'question',
    explanation = 'explanation',
}

interface ToastCustomOptions {
    timeout: number;
}

class ToastService {
    popToast(toastIcon: ToastIcon, body: string, customOptions?: ToastCustomOptions): void;
    popToast(
        toastIcon: ToastIcon,
        body: string,
        customOptions: ToastCustomOptions,
        actionButtonText: string,
    ): Promise<boolean>;
    popToast(
        toastIcon: ToastIcon,
        body: string,
        customOptions: ToastCustomOptions = { timeout: 3200 },
        actionButtonText?: string,
    ): Promise<boolean> | undefined {
        // Implementation
    }
}

const popToastParams: Parameters<ToastService['popToast']> = [ToastIcon.success, 'this is a toast'];
      ~~~~~~~~~~~~~~ <- Error!
```

### 🙁 Actual behavior

The assignment to `popToastParams` in line 30 fails with the error 2322 as following:
> Type `'[ToastIcon.success, string]'` is not assignable to type `'[toastIcon: ToastIcon, body: string, customOptions: ToastCustomOptions, actionButtonText: string]'`.
>   Source has 2 element(s) but target requires 4.(2322)

### 🙂 Expected behavior

I would expect `Parameters<ToastService['popToast']>` to evaluate to `[toastIcon: ToastIcon, body: string, customOptions?: ToastCustomOptions, actionButtonText?: string]`, since the `popToast` function's `customOptions` and `actionButtonText` are both optional.

**Comment by MartinJohns** [comment]
Conditional types (such as `Parameters<T>`) and overloads don't play well together.

[Type inference in conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types)

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the _last_ signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by MartinJohns** [comment]
Conditional types (such as `Parameters<T>`) and overloads don't play well together. It's a design limitation.

[Type inference in conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types)

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the _last_ signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by amitbeck** [comment]
@MartinJohns so if I understand correctly, there's no escape from having to cast to `unknown` and then back to the desired type in this case?

**Comment by MartinJohns** [comment]
You can add a proper last signature to your method to cover all your cases:

    popToast(toastIcon: ToastIcon, body: string, customOptions?: ToastCustomOptions): void;
    popToast(toastIcon: ToastIcon, body: string, customOptions: ToastCustomOptions, actionButtonText: string): Promise<boolean>;
    popToast(toastIcon: ToastIcon, body: string, customOptions?: ToastCustomOptions, actionButtonText?: string): Promise<boolean> | undefined;
    popToast(toastIcon: ToastIcon, body: string, customOptions: ToastCustomOptions = { timeout: 3200 }, actionButtonText?: string): Promise<boolean> | undefined { /* Implementation */ }

**Comment by amitbeck** [comment]
@MartinJohns the 3rd signature fixed this. Thanks!

**Comment by MartinJohns** [comment]
> The last signature already defines the last 2 parameters as optional.

The last one is not considered when it comes to overloads.

[Overloads](https://www.typescriptlang.org/docs/handbook/functions.html#overloads)

> Note that the `function pickCard(x): any` piece is not part of the overload list, so it only has two overloads: one that takes an object and one that takes a number. Calling `pickCard` with any other parameter types would cause an error.

**Comment by amitbeck** [comment]
> > The last signature already defines the last 2 parameters as optional.
> 
> The last one is not considered when it comes to overloads.
> 
> [Overloads](https://www.typescriptlang.org/docs/handbook/functions.html#overloads)
> 
> > Note that the `function pickCard(x): any` piece is not part of the overload list, so it only has two overloads: one that takes an object and one that takes a number. Calling `pickCard` with any other parameter types would cause an error.
> 
> That last one is not visible from the callsite either. It must be a "visible" overload.

@MartinJohns That makes sense. Thanks again!
