### ISSUE TITLE
useDefineForClassFields is false, but overriding accessor with property still throws error

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#42563]
# Bug Report

### 🔎 Search Terms

useDefineForClassFields override accessor with instance property (no results really, but related: https://github.com/microsoft/TypeScript/pull/33509)

### 🕗 Version & Regression Information

I'm in 4.1.3

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oH0BmiBc0AdgK4C2ARgKYBO0AvNAIzrQDmlALtLvABQCUKap2LVC0DgAsAlhAB0ORAF8WETt0S8AboORTZCnvWhaVK1KEgwAQmFqUAHh0qEAJjARI0GIw0YAmAGZUJSA)

### 💻 Code

```ts
class Foo {
  _foo: number = 1
  get foo() {return this._foo}
  set foo(v) {this._foo = v}
}

class Bar extends Foo {
  foo = 123 // ERROR, although useDefineForClassFields is false
}
```

### 🙁 Actual behavior

There is an error

### 🙂 Expected behavior

There should be no error, because the legacy [[Set]] semantics are in play, and therefore it works as intended: the subclass calls the super class accessor.

It should desugar to:

```js
class Foo {
    constructor() {
        this._foo = 1;
    }
    get foo() { return this._foo; }
    set foo(v) { this._foo = v; }
}
class Bar extends Foo {
    constructor() {
        super();
        this.foo = 123; // triggers accessor
    }
}
```

which is very similar to the output that you see in the playground.

---

Also it [doesn't work with `declare`](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oH0BmiBc0AdgK4C2ARgKYBO0AvNAIzrQDmlALtLvABQCUKap2LVC0DgAsAlhAB0ORAF8WETt0S8AboORTZCnvWhaVK1KEgwAQmFqUAHh0qEAJjARI0GV5UvCNeAJGACYAZlQlIA).

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/pull/37894, https://github.com/microsoft/TypeScript/issues/40220

**Comment by trusktr** [comment]
I ended up finding that issue, and I left a [comment](https://github.com/microsoft/TypeScript/pull/37894#issuecomment-770318450) stating my sentiment that the new behavior makes `useDefineForClassFields` essentially an obsolete option, and that the new behavior is not a good solution because it prevents declaring types for valid JavaScript code rather than expanding our static type abilities.

**Comment by RyanCavanaugh** [comment]
@sandersn what was the motivation for the change in 4.0 around this?

**Comment by sandersn** [comment]
It's described in #37894.

**Comment by canonic-epicure** [comment]
@RyanCavanaugh The irony is that it seems the motivation for the #37894 was the #34585, filed by the same author as this issue. Also see the updated discussion in the #37894
