### ISSUE TITLE
Javascript intellisence lost

### ISSUE THREAD

**Issue by Piusn** [Microsoft/TypeScript#4256]
I installed this extension for vs 2015 today, and now there is no intellisense for javascript. Even the colorful highlighting of javascript keywords like 'function' is now lost and every is black

**Comment by mhegazy** [comment]
looks like #4238.

This is probably caused by "Tools and Windows SDK 10.0.10240"; follow the instructions in https://github.com/Microsoft/TypeScript/issues/4238#issuecomment-129060370 to restore JS support.
