### ISSUE TITLE
Proposal private-fields-in-in is stage-3

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#42574]
# Suggestion

https://github.com/tc39/proposal-private-fields-in-in is stage 3 now. 

## 🔍 Search Terms
esnext. private field. class

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example
```ts

class C {
  #brand = 42;

  static isC(obj: C) {
    return #brand in obj; // should work
  }
}
```

**Comment by acutmore** [comment]
Good news! A few of us at @Bloomberg have started discussing working on this as a TS contribution

cc: @dragomirtitian @robpalme

**Comment by acutmore** [comment]
Work has now started on this and is going well (basic parsing with simple errors and type checking).

- [ ] Publish wip branch to [bloomberg/TypeScript](https://github.com/bloomberg/TypeScript)
- [x] Add new 'PrivateIdentifierInInExpression' expression
    - `'prop' in obj` is a BinaryExpression, but this isn't because syntactically the left side can only be a `PrivateIdentifier`
    - suggestions for alternative names instead of 'PrivateIdentifierInInExpression' ?
- [x] Error when the `PrivateIdentifier` can't be looked-up symbolically
    - outside of a class
    - no containing class with matching private field
- [x] Expression returns `boolean`
- [x] RHS must be object or any (and not null in strictNullChecks)
    - i.e. same rules as `'prop' in obj`
- [ ] Helpful error messages
- [ ] Use in flowNodes and type narrowing


## Type Narrowing

```ts
class MyClass {
  #branded = true;
  prop = Math.random();

  equals(x: unknown) {
    if (typeof x === 'object' && #branded in x) {
      return x.prop === this.prop;
      //     ^ - should we narrow 'x' to 'MyClass' here?
    }
    return false;
  }
}
```

Pragmatically `#branded in x` could narrow right down from `object` to `MyClass` as in _most_ cases the only way `x` could have the privateField is by being an instance of the class. Unlike `'prop' in x` where there can _easily_ be other classes that also have a `'prop'` field.  So this feels like it would be a nice optimisation for the developer experience.

However this check can also be made to pass in slightly more esoteric code where `x` is not an instance of `MyClass`:

```ts
class SuperReturn {
  constructor(x: any) { return x; }
}

class MyClass extends SuperReturn {
  #branded = true;
  
  constructor(x: unknown) {
    super(x);
  }

  static getBranded(x: MyClass) {
    return x.#branded;
  }
}

const a = {};
new MyClass(a);
// 'a' will now have the #branded private field
assertTrue(MyClass.getBranded(a as any));
// but is not an instance of the class
assertFalse(a instanceOf MyClass);
```

Do we want the type narrow to go for the (assumed) common case or for the correct case? Or maybe there is a middle ground e.g. only narrow when the classes does not extend another class (I believe this is the only way the check can be 'corrupted')

**Comment by sosoba** [comment]
This feature has been marked by TC39 as [finished](https://github.com/tc39/proposals/blob/master/finished-proposals.md).

I have such questions.

1. Currently configuration `target=ES2021` means transpiling to `WeakMap` and `target=ESNext` leaves code unchanged. Will it stay this way or will `ES2021` containt native private fileds or will ES2022 has been added?
2. Is there a table in the documentation that maps the `target` profile to transpilation scenarry?
3. Whether the title of this issue needs to be updated? 

Best regards.

**Comment by acutmore** [comment]
ES2021 was finalised before this proposal went to stage 4 so it will be part of ES2022
