### ISSUE TITLE
Limiting the use cases of array's reduce method 

### ISSUE THREAD

**Issue by navanshu** [microsoft/TypeScript#42573]
# Bug Report
The reduce method on arrays can act as a filter and map combined but when used in such a way the TS compiler complaints. 
Since javascript doesn't have a filter Map, I think so the TS compiler shouldn't compaint about this.  Adding a ts-ignore for dealing with such a issue can backfire in future because of another problem.
### ⏯ Playground Link
[Kindly check this playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJgPYFtkG8BQyRyIcWEAXMgM5hSgDmANIcQCbDUIYBu0EbKgCMMGADYQ4IfAF98+CWDSYs1ZFXTYA2gF1kAXmRb8BYiTKVkAcgASATzZQMDCCCsszHLr36DkdAFcIFhkWU2JSciorADFgMUgoZABZOAAHZBiAkAQwYAwQZFBkACs4HjguejSwd1YiL24+KAEqeDFqCFl5HQBuZHkAegAqYcJh5AB1FGoACwwAsTZkOCUJSqVZ8pQwWZQYFoFsfwxkNlPdznHkABVZzmQAd3ixZChs5Ag+Qt2dtQe5gs8iAGANkBMAJLILZ8GgQVzINIQDBpCTIALURjILDpFYgZa-QoweKJZAYJI8YBIZDNahwa6PPY-PZ2ZAIKSlDFKDEoFpsAJIcaDeSKM6cJq+VKJYBwDoGZTYagAOj5AogAAp1QANdQKrC6JgAUQ0KgAlAYAHx4eRmHUAfjthl0vXqyENSsaPj5yAAZD7kFqlWkMbN1YbTS6zC0wAEoIUtS6ZBH5NwQNRxBAlWJnOrPc0BFLoDKOhGgA)

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

**Comment by RyanCavanaugh** [comment]
I don't understand the complaint because if you use `reduce`'s initial value argument, this checks cleanly
```ts
let discoveredMaterials = Atoms.reduce((X: Atom[], E: Atom) => {
    E.discovered && X.push(E);
    return X;
}, []);
```
The provided way of writing it is not going to be analyzable by a type checker

**Comment by navanshu** [comment]
It may be working as intended, the reduce function is more versatile, it would be better if the reduce function type definition be more adaptive rather than just being the same type as the other arguments.
