### ISSUE TITLE
Type 'Hello[S][string]' is not assignable to type '(...args: any) => any'

### ISSUE THREAD

**Issue by gbili** [microsoft/TypeScript#42576]
# Bug Report

### 🔎 Search Terms

`[T][string] is not assignable to to (...args: any[]) => any`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/C4TwDgpgBAEhA28D2UC8UDeAoKUDOSAthAFyY65QCGZAFAJRoB81AdiANwW4BGdjqFgDckASwAmXXAF8KSVqXKUoAY37MorAK6EeEAE5Sos2VlCRYEEGigAlCMC37WAFXAQAPHERIA2gHJ5CH8AXQCVUKYOKAB6GM0dPX0yAHkAaShRADMoAEkocRRRYChCKm0qRBAzdygAISQkDwBlKAgAD2AIVnE8KABrKyQc72QAGigABTbO7t6BoZGEZF9mkJZ0e0dnN0gvZb8130n16LioAFF9fSRkqAA5JBKkfqgAdwALboKQVipCUQqSrwayFBQ1CwAWQcHzwLRmXR6fUGIGGlh8E2mHUR8xRaNGh3WNgJqzCJy45mgMFENi2Tlc7g80OAsI8-gIxH8E38VH8TCisXi5RAqQy2TyBSKJTKFSqEOgdRAnla2LmyMW6PGUwRaoWqKWPlJGzsDnpu08zNZzUx-LO8SuNzuj2er0+33Ev3+gOBoKCWAoQA)

### 💻 Code

```ts
type Hello = {
  some: {
    a: () => any;
    b: () => void;
  }
  one: {
    c: () => number;
  }
}

type Hey = ReturnType<Hello['one']['c']>; // number: OK if I do it manually
type Boo<S extends keyof Hello, P extends keyof Hello[S]> = ReturnType<Hello[S][P]>; // Error: Not ok when dynamically done
type Meths<S extends keyof Hello, P extends keyof Hello[S]> = Hello[S][P];
type Hi = ReturnType<Meths<'some', 'a'>>; // any: OK if I do it manually
type Bye<S extends keyof Hello, P extends keyof Hello[S]> = ReturnType<Meths<S, P>>; // Error: Not ok when dynamically done
```

### 🙁 Actual behavior

Gives an error: 

```
Type 'Meths<S, P>' does not satisfy the constraint '(...args: any) => any'.
Type 'Hello[S][keyof Hello[S]]' is not assignable to type '(...args: any) => any'.
Type 'Hello[S][string] | Hello[S][number] | Hello[S][symbol]' is not assignable to type '(...args: any) => any'.
Type 'Hello[S][string]' is not assignable to type '(...args: any) => any'.ts(2344)
```

### 🙂 Expected behavior

A generic that can return the ReturnType

**Comment by Nctdtman** [comment]
Because the Hello type does not have an index signature in your example, TS compilation cannot ensure that the value obtained by Hello[S][P] is (...args: any) => any. (TS is not that smart

There are two solutions:
1. Use index signature to ensure that each Hello[S][P] is (...args: any) => any
```
type Hello = {
   some: {
     a: () => any
     b: () => void
     [i: string]: (...args: any) => any
   }
   one: {
     c: () => number
     [i: string]: (...args: any) => any
   }
}

type Boo<S extends keyof Hello, P extends keyof Hello[S]> = ReturnType<
   Hello[S][P]
>
type T1 = Boo<'some','b'>
```
2. Use Conditional Types to ensure that Hello[S][P] is (...args: any) => any
```
...
type Bye<
   S extends keyof Hello,
   P extends keyof Hello[S]
> = Hello[S][P] extends (...args: any) => any
   ? ReturnType<Hello[S][P]>
   : Hello[S][P]
```
