### ISSUE TITLE
Installing Typescript 1.5 for VS2013 after VS2015 gives me wrong reference paths to follow

### ISSUE THREAD

**Issue by GeertVL** [Microsoft/TypeScript#4258]
I get the following error when installing the latest setup for Typescript 1.5

Error	1	Your project file uses a different version of the TypeScript compiler and tools than is currently installed on this machine.  No compiler was found at C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\1.5\tsc.exe.  You may be able to fix this problem by changing the <TypeScriptToolsVersion> element in your project file.	WarehousePortal

What do I do?

The version in my project file is correct.

**Comment by mhegazy** [comment]
looks like a dupe of  #3493. @paulvanbrenk can you take a look.

**Comment by mhegazy** [comment]
also @paulvanbrenk is there a workaround or a fix that you can share with @GeertVL?

**Comment by GeertVL** [comment]
I fixed it by reinstalling the latest Typescript for 2015 install. Fixed for 2013 and 2015.
It seems a typo of some sort in the targets.

**Comment by paulvanbrenk** [comment]
Yep, there is some kind of mismatch in the targets between VS 2013 and VS 2015.
