### ISSUE TITLE
Type '(arg: number) => void' is not assignable to type '(arg: unknown) => void'.

### ISSUE THREAD

**Issue by DidiBear** [microsoft/TypeScript#42582]
# Bug Report

In variables, we can assign anything to `unknown` but not the contrary:

```tsx
const x: unknown = 12           // Fine
const y: number = 12 as unknown // ERROR: Type 'unknown' is not assignable to type 'number'
```

However in function arguments, this behavior is inverted:
```tsx
const fn1: (arg: unknown) => void = (arg: number) => {} // ERROR: Type 'unknown' is not assignable to type 'number'
const fn2: (arg: number) => void = (arg: unknown) => {} // Fine but should be an error
```

### 🔎 Search Terms

- label:Bug unknown function argument 
- label:Bug can assign to unknown 
- Type '(arg: number) => void' is not assignable to type '(arg: unknown) => void'.

### 🕗 Version & Regression Information

Tried in the playground with versions 4.1.3, 4.0.5, 3.9.7 and 4.2.0-dev.
So this is not a regression.

[Playground link with the above code](https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBADwFxwK4QNYTAdwnAXjgEYAmOCyqygehrgDEBLCAU1EljgE8UJUAtgCNWAJ0IlyAQyhpM2PLXoBRAEqqA8qpQAVbgAdWcAOTosuCMbhNZ2eDKhMA5hClCANkZhg4MA0eN+YTFjYA5oeAAzCGIUAAopUScUMwUIAEpCAD44ADcwJgATCQSkvkERUUyCHMSnODo4NU1tOD1DE1SLKxs4OzgHZ1cPLx8-DsCKkPCuaNJ4uvLgquy8guKiUuS5czxq2qSG+mY2OCFUeCgACzBUd2KROBxRSCcwoA)

### 💻 Code

```ts
const fn1: (arg: unknown) => void = (arg: number) => {}
const fn2: (arg: number) => void = (arg: unknown) => {}
```

### 🙁 Actual behavior

Error on the `fn1`: 

```
Type '(arg: number) => void' is not assignable to type '(arg: unknown) => void'.
  Types of parameters 'arg' and 'arg' are incompatible.
    Type 'unknown' is not assignable to type 'number'.ts(2322)
```

### 🙂 Expected behavior

Error on the `fn2`: 

```
Type '(arg: unknown) => void' is not assignable to type '(arg: number) => void'.
  Types of parameters 'arg' and 'arg' are incompatible.
    Type 'unknown' is not assignable to type 'number'.ts(2322)
```

**Comment by RyanCavanaugh** [comment]
See https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Function_types

**Comment by DidiBear** [comment]
Thank you, indeed I misunderstood how types works ! 

I am closing the issue :)
