### ISSUE TITLE
Methods are not new identifier definition locations

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#42595]
```ts
let x = {
  /**/
};
```

Type in `a(` and we'll auto-complete the property. That shouldn't happen.

![autoCompletepProperty01](https://user-images.githubusercontent.com/972891/106533444-0a4bfc00-64a7-11eb-8ef5-4b2e58605fc0.gif)

**Comment by andrewbranch** [comment]
`addEventListener` is a global, so it is possible that you wanted to write

```ts
let x = {
  addEventListener
}
```

It was added in #41539. I argued that you probably _don’t_ ever want to do this with globals, but didn’t realize that `(` was a commit character (IMO, way too many things are commit characters), so I left it up to dissenters, and none showed up:

> I think it’s a bit odd for globals to show up, but I’m not sure it’s harmful, because
>
> - None of these show up if we have any actual property suggestions from a contextual type; these only appear when we previously would have shown no completions
> - Locals are sorted above globals

I think it should be easy to filter out symbols declared in other files.

**Comment by andrewbranch** [comment]
@DanielRosenwasser I bring this up because I think your title for this issue is too strong of an assertion. That _is_ a new identifier location, or else we have to revert #41539, which fixes an issue that you called a bug 😅. I can definitely get behind removing globals from the list here, but if you were in a file with a ton of locals, and had the intention to write a non-contextulaly-typed object literal with bespoke member names, you could hit the same frustration that typing `(` gives you a bad completion.

**Comment by DanielRosenwasser** [comment]
There's 2 things:

1. Outside variables should (often?) be valid shorthand property completions.
2. Property completions should be considered potentially new identifier locations (e.g. see uses of `isNewIdentifierLocation` and `isNewIdentifierDefinitionLocation` from what I recall)

The latter should permit people to write out a new name without a commit character committing to an arbitrary global or local.

**Comment by DanielRosenwasser** [comment]
That "often" has more to do with a contextual type. If you have a contextual type, you just want to provide those completions.

**Comment by DanielRosenwasser** [comment]
It sounds like there's another bug here which is that `isNewIdentifierDefinitionLocation` is very poorly documented. 😅

The idea is that there's 3 states I have in mind

1. Always give completions.
1. Never give completions (`isNewIdentifierLocation`)
1. Give completions, but don't auto-complete on commit characters (`isNewIdentifierDefinitionLocation() -> true`)

And I'm saying we want the third one.

**Comment by andrewbranch** [comment]
Got it, I thought you were talking about (2) but you were talking about (3).

**Comment by andrewbranch** [comment]
If an object literal has a contextual type, are its members still new identifier definition locations? That function currently works off syntax alone.

**Comment by DanielRosenwasser** [comment]
Yeah that doesn't seem too bad I suppose.
