### ISSUE TITLE
"Convert default export to named export" refactoring is not always available

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#42605]
# Bug Report

### 🔎 Search Terms

quick fix, refactoring, vs code, code action, exports, default, named

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about refactorings

Tested with v4.1.2

### ⏯ Playground Link

N/A

### 💻 Code

```ts
export default () => {}
```

or

 ```ts
const foo = () => {};
export default foo;
```

Highlight the full line containing the `default` export.

### 🙁 Actual behavior

"Convert default export to named export" refactoring is not available

### 🙂 Expected behavior

"Convert default export to named export" refactoring should be available, like how it is for function declarations such as:

```ts
export default function foo () {}
```

![image](https://user-images.githubusercontent.com/921609/106598566-d37df080-654f-11eb-9d5d-852956d4a6fa.png)

(For reference, this functionality was added in https://github.com/microsoft/TypeScript/pull/24878.)

**Comment by a-tarasyuk** [comment]
@OliverJAsh How should the named export look like for the first example?

```ts
export default () => {}
```

For the second example, default export needs to convert like this., Am I right?

```ts
const foo = () => {};
export { foo };
```

/cc @RyanCavanaugh

**Comment by OliverJAsh** [comment]
For the first example we could just give it a temporary name and the open the rename prompt, like what happens when you run 'extract constant'.

For the second example yes I believe so, or just `export const foo = `.
