### ISSUE TITLE
Syntax suggestion: Ignore last void parameters

### ISSUE THREAD

**Issue by hoda5** [Microsoft/TypeScript#4260]
``` typescript

class X<T>
{
    f(t: T) { return { a: t }; }
}


var x: X<number>;
var t1 = x.f(5);
t1.a = 5; // Should not error: t1 should have type {a: number}, instead has type {a: T}

```

``` typescript
var x2: X<void>; 
var t2a = x.f(void 0); // It works but void 0 it's unnecessary
var t2b = x.f(); // SUGGESTION: ignore syntax check of last argument if it's type is void
t2b.a = void 0; // Should not error: t2 should have type {a: void}, instead has type {a: T}

```

test case: tests/cases/compiler/genericObjectLitReturnType.ts

maybe the solution is the same for #3356

**Comment by weswigham** [comment]
Would I be correct in saying that the type signature `T|void` should be equivalent to `T?`? (Any type which contains the ) This equality is true in the closure compiler type system (but it uses `undefined` rather than `void` for the type name).

**Comment by thr0w** [comment]
No @weswigham. 
```typescript
class X<T, U>
{
    f(t: T|void, u: U) { ... }
}
```

t: T it's mandatory because is not the last function argument and we can't lose u: U. My suggestion it's only for last argument. However, the rule can be last void parameters because if X<void,void> f function can be invoke with f() lossless

I don't understand when T|undefined equality is true in the closure compiler, can you send me a sample?

Thanks

**Comment by weswigham** [comment]
Oh, sorry, I was (completely) mistaken - The equality's not true for optional function arguments, only optional record type members. :S

**Comment by RyanCavanaugh** [comment]
Chatting with @danquirk, our proposal (roughly) is that at a call expression, we treat the unprovided required arguments as if they were of type `void`, then check that those are assignable to the parameter types (modulo `any`). Leave assignability/subtyping of function types unchanged.

**Comment by thr0w** [comment]
Yes @RyanCavanaugh, just for call expressions. I don't know how works typescript checker then I can't say if it's better don't throw error if last parameter is void and missing or if it's treat the unprovided required arguments as if they were of type `void`.  But it's what you say, just in call expression leaving assignability/subtyping of function types unchanged.

If I can help you just tell what to do.
Thanks.

**Comment by RyanCavanaugh** [comment]
Approved. Should be useful for `Promise<void>`.

**Comment by jack-williams** [comment]
@RyanCavanaugh What is the status on this issue? I saw that @Kingwl was working on a PR that was abandoned (#20642) with some spec issues raised by mhegazy.

Anyway, I have a fix that works for the given examples as well as generic rest / tuple types here 9f6e28b053f94f71ad49438a9b9822bd4b30bb5e if you want to breathe some life into this issue.

@Kingwl : I didn't mean to conflict with your work (I didn't actually see your old PR until I finished my fix). If you want to take my work and finish the PR I would be fine with that.

**Comment by Kingwl** [comment]
@jack-williams take it easy, I have already close the pr

**Comment by FrogTheFrog** [comment]
@jack-williams It does not seem to work with constructors. Is this intentional or were constructors just forgotten?

**Comment by jack-williams** [comment]
@FrogTheFrog Can you provide an example?

**Comment by jack-williams** [comment]
@FrogTheFrog Thanks for the example. The issue is not to do with constructors; the issue is the generics. See this comment [here](
https://github.com/Microsoft/TypeScript/pull/27506#issue-219827844) in an older PR I made.

Basically the special casing for `void` does not apply to arguments that are instantiated as type `void` at the point the argument is called. Getting it to work with generics caused too many problems to ultimately be worth it.

Here is a workaround if you _really_ want it:

```ts
class Test<T1, T2 = void> {
    constructor(input1: T1, input2: T2) {
        // Do something
    }

    static makeFactory<T1, T2 = void>(): (input1: T1, input2: T2) => Test<T1,T2> {
        return (input1: T1, input2: T2) => new Test(input1, input2);
    }
}

const factory = Test.makeFactory<number>();
const factoryTwo = Test.makeFactory<number, number>();
const testOne = factory(3); // ok
const testTwo = factoryTwo(3); // not ok
```

**Comment by FrogTheFrog** [comment]
@jack-williams I'm just nitpicking at this point. Since I mainly use "options" object for public classes, it does not really bother me. I'm using this simple trick fallback to `void` type when nothing is provided:

```ts
interface TestOptions<T1, T2> {
    input1: T1;
    input2?: T2;
}

class Test<T1, T2 = void> {
    constructor(options: TestOptions<T1, T2>) {
        if (options.input2 !== void 0) {
            // Do something with input2
        }
    }
}

const test = new Test({ input1: {} }); //=> test has Test<{}, void> type
```

I'm just glad that the `void 0` nonsense is finally over thanks to you :D

**Comment by garkin** [comment]
Why does this fail?  [playground](https://www.typescriptlang.org/play/index.html#src=function%20qwe%3CT%20%3D%20void%3E(d%3A%20T)%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Aqwe()%3B)
```ts
function qwe<T = void>(d: T) {}
qwe(); // ERROR: Expected 1 arguments, but got 0. An argument for 'd' was not provided. 
```

**Comment by jack-williams** [comment]
@garkin 

> Basically the special casing for void does not apply to arguments that are instantiated as type void at the point the argument is called. Getting it to work with generics caused too many problems to ultimately be worth it.

The checks are done before `T` is replaced with `void`. This is tracked here: #29131

**Comment by thr0w** [comment]
Thank you!
