### ISSUE TITLE
Cannot recognize attribute while using "this".

### ISSUE THREAD

**Issue by kentng201** [microsoft/TypeScript#42603]
# Bug Report

Typescript cannot recognize attribute when using "this" in type, see playground link.

### 🔎 Search Terms

vscode, MVC, data modeling, entity-relationship, exclude specific type.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAsg9gEwgGwNIRAHgCoD4oC8UA1hnAGZQDyAtgJbA4A0UA3gFBRdQDa6IUOgDsSZStgC6ALijY+GCVAgAPYBCEIAzlABiAVyEBjYHTgiA-FH5QZQiADcIAJ3YBfHqRAVZE-AB8oAHIAfToEQIBudnZDZABDTW14JGQ2Tm4nFDiTM00ACzowAApPAEYZZJR+TGACzVwASjZXN2jYhO0AZT0AIyVVdS1YRBQ07ihs4Cc6Hr01AEIZTSnhAHMo8bVloqaOcfHM4D0nEVq6TQA6TPicoXzCosDJ6dm1QIaN7haWmNzgKDghCgdgA7lBuj0onArllbvdik9gCtXhB3lF2EA

### 💻 Code

```ts
type ModelKey<T> = keyof Omit<T, {
    [Key in keyof T]: T[Key] extends Function ? Key : never
}[keyof T]> | '_id';

class Model {
    relationship(key1: ModelKey<this>) {}
}


class Sub extends Model {
    attribute!: string;
    test() {
       // error: Argument of type '"attribute"' is not assignable to parameter of type 'ModelKey<this>'.ts(2345)
        return this.relationship('attribute');
    }
}

const o = new Sub;
// this work fine
o.relationship('attribute');
```

### 🙁 Actual behavior
Argument of type '"attribute"' is not assignable to parameter of type 'ModelKey<this>'.

### 🙂 Expected behavior
The attribute should be assigned as the parameter just like the last line of code.

**Comment by RyanCavanaugh** [comment]
This is a correct error. `Sub` could be inherited by a more-specific class that had more-specific types.

From the outside, the restriction isn't enforced since otherwise you'd never ever be able to call `o.relationship`

**Comment by kentng201** [comment]
<img width="1002" alt="Screenshot 2021-02-08 at 11 07 42 AM" src="https://user-images.githubusercontent.com/4708656/107171487-e08e5a00-69fd-11eb-9305-a553c7ec50be.png">

If I remove `Sub`, typescript still unable to recognize the class key/attribute, may I know what will be 'this' refers to in this case(My assume will be Model itself)?

**Comment by kentng201** [comment]
Since `ModelKey` is a type that ignores all Function type of key, hence I assume the key `Model`.`attr` can be assigned.
