### ISSUE TITLE
Parameter JSDoc could be included in tooltip

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#4261]
Hi,

**Version**: VS 2015 / TS 1.5

![image](https://cloud.githubusercontent.com/assets/1106823/9182144/118545b6-3fa1-11e5-9432-220044004c2e.png)

When hovering over the property `foo`, it would be helpful if the JSDoc `"The foo option"` was also displayed. At present the only way to figure out what the property represents seems to be to delete and type it again:

![image](https://cloud.githubusercontent.com/assets/1106823/9182249/9d4b3650-3fa1-11e5-98a9-2825f6679fbf.png)

**Comment by mhegazy** [comment]
looks like a dupe of #290

**Comment by NoelAbrahams** [comment]
Yes, I think it's a duplicate.
