### ISSUE TITLE
Improve error messages for computed class property names

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#42619]
# Bug Report

### 🔎 Search Terms

"A computed property name in a class property declaration must refer to an expression whose type is a literal type or a 'unique symbol' type. "

"ts(1166)"

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because unlikely to be differenct

### ⏯ Playground Link

[Playground link example giving error message](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=16&pc=2#code/MYewdgzgLgBBC8BlAngWwEYgDYAoDkAZiCHgJQBQoksEBSamWAdEQE75EkXBYCGEEGAGEAjDADe5GHCi8oAS2AxWAU14ATcFmQwA2oWJ4AugC4ASitCt1AHmit5YAOYAaXmGQA+KTLmLlappg2noQpjAWVrb2jq7uXj7QfkqqGlo6urThkSDWdlAOzm4e3tJJCimB6XooGNgsuRyGpNmWudEFscUJAL7kAPT9MACyOqDqKjBOICqCABYqquTkEzy8qjAAbuswICYSAA6sIAf7BiQ9ANzLawLCAEwSPtK6IExHJ0Yw8DAilzCDGAAd1yAGsIM89DgQKR3scDl8fn8AUMNOpYjADusVJApvJNrMYO4YItjqwYOhLLwAK4QSbyKB4QQQZBgWTACq8LAhMAgGBYcBORZEmCaKBQFTqGBgXioFTkHpAA)

### 💻 Code

```
const s=Symbol('foo')
const sf=Symbol.for('foo')
class C1 {
  static readonly ['foo']:Record<string,any>
  static readonly [s]: Record<string,any>
  static readonly [sf]: Record<string,any>
  static readonly [Symbol.for('foo')]: Record<string,any>  // ts1166
}

declare var o: {prop: 'foo'};

class C2 {
    [o.prop] = 1; // works
    [(o).prop] = 1; // ts1166, adding parens gives an error because it's syntactically no longer a dotted name
}
```

See [this closed issue](https://github.com/microsoft/TypeScript/issues/42601) for the source the examples, and the reasoning why error (ts1166) is reasonable enough in both cases (although the error message content is not reasonably straightforward).

### 🙁 Actual behavior

Error message: ts1166
*"A computed property name in a class property declaration must refer to an expression whose type is a literal type or a 'unique symbol' type. "*

### 🙂 Expected behavior

An error message like
*"A computed property name in a class property declaration must be 
a straightforward expression for a literal string or a literal  number, or a constant reference to a symbol. "*

*"Straightforward"* is obviously not a complete description, but it is accurate and fits in the error message.
Error *ts1166* is clearly generated during syntax parsing, so claims about 'type' are bound to be wrong when the type is obscured by non-straightforward syntax.

BTW, 'unique symbol type' seems to be an alias for 'type of a literal symbol`, and isn't particularly helpful - every symbol instance is unique, just like every object is unique, and (AFAIK but I could be wrong) 'unique object type' is not a standard phrase.  But ts1166 doesn't need to mention type anyway.

**Comment by DanielRosenwasser** [comment]
How about

```
A computed property name in a class property declaration must have a simple literal type or a unique symbol type.
```

**Comment by DanielRosenwasser** [comment]
Or

```
A computed class property name must have a simple literal type or a unique symbol type.
```

**Comment by DanielRosenwasser** [comment]
@jonhue this one's close in spirit to #42523.

**Comment by jonhue** [comment]
Thanks! I'll see if I find the time to look into this in the next couple of days!
