### ISSUE TITLE
exclude type from primitive

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#42618]
# Suggestion

## 🔍 Search Terms
exclude type from primitive

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
it would be good to be able to exclude values from a primitive type, for example:
```ts
type Foo = Exclude<string, 'foo'>
```

## 📃 Motivating Example
```ts
declare const asdf: string

if (asdf === 'foo') {
    console.log('this might happen')
} else if (asdf === 'foo') { //type 'foo' is not assignable to type Exclude<string, 'foo'>
    console.log('unreachable')
}
```

## 💻 Use Cases
```ts
if (foo.length > 1) {
   //this could narrow foo to something along the lines of [string, string] & string[]
    //however currently it can't narrow the 'length' property accurately
    console.log('hi')
} else (if arr.length === 0) { //suggestion: compile error, length is of type Exclude<number, 0|1>
    console.log("what?")
}
```

**Comment by RyanCavanaugh** [comment]
See #29317
