### ISSUE TITLE
Preserve original formatting when printing modified nodes

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#42617]
# Suggestion

## 🔍 Search Terms

ast print format 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Make `ts.createPrinter()` preserve whitespace & formatting from the original parsed source file.

## 📃 Motivating Example & Use Case

I'm building a source code migration tool that will do some heavy lifting within types & expressions in JS & TS code, and TypeScript's AST API is very helpful to make sure I always generate correct syntax.

However, right now, when I rewrite a file using the AST and `ts.createPrinter()`, it removes all blank lines, which is unsuitable for migrating checked-in source code.

[Here](https://runkit.com/slaks/sample-typescript-ast-rewriter) is a simple example of an AST-based rewriter; compare the original file to the rewritten file in the output.

**Comment by RyanCavanaugh** [comment]
The parsing AST and associated printing APIs don't have exact trivia preservation as a design constraint, and we don't want to make TS overall slower/more complex by adding that.

**Comment by Ryuurock** [comment]
+1
