### ISSUE TITLE
A source type should be able to understand "keyof" a mapped type

### ISSUE THREAD

**Issue by JeffreyZhao** [microsoft/TypeScript#42623]
# Suggestion

Type `Target` is mapped from `Source`. `Source` should be able to understand `keyof Target`, and vice versa.

### 🔎 Search Terms

keyof, mapped type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

```ts
type State = {
    num: number;
    text: string;
    bool: boolean;
};

class Helper<T> {
    constructor(public value: T) { }
}

type StateHelpers = {
    [K in keyof State]: Helper<State[K]>
}

function initHelper<K extends keyof State, P extends State[K]>(helpers: StateHelpers, key: K, value: State[K]) {
    helpers[key] = new Helper(value);
}
```

## 💻 Use Cases

If it's implemented, different types can be coordinated together and improve code reusability, but currently it's not supported. Now type casting has to be used and type checking is lost.

**Comment by MartinJohns** [comment]
You are under the wrong assumption that `key` always refers to a single key, but that's wrong. `K` can be a union type of multiple keys, making this assignment unsound. You would require #27808.

**Comment by JeffreyZhao** [comment]
@MartinJohns I see, thanks for the explanation. Then the question becomes, is it possible to limit "one" key of a union type, instead of the subset of it in current TypeScript? So it's something like:

```ts
function initHelper<K is keyof State, P is State[K]>(helpers: StateHelpers, key: K, value: State[K]) {
    helpers[key] = new Helper(value);
}
```

Where `K` "is" `keyof State` and `P` "is" `State[K]` instead of "extends".

**Comment by MartinJohns** [comment]
> is it possible to limit "one" key of a union type, instead of the subset of it in current TypeScript?

No. I point you again to the issue #27808.

**Comment by JeffreyZhao** [comment]
@MartinJohns It doesn't seem like the same thing since people are now discussing new operators (e.g, string ^ number) instead of working with existing union types, but I got the idea they're close.

**Comment by urain39** [comment]
Good suggestion! I am searching for a same problem recently.
