### ISSUE TITLE
Type is incorrectly narrowed when reassigning to an optional parameter

### ISSUE THREAD

**Issue by Zombiefruit** [microsoft/TypeScript#42627]
# Bug Report

### 🔎 Search Terms

- optional 
- parameter 
- narrowing 
- assignment

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (3.33 - 4.13), and I reviewed the FAQ for entries about optional parameters, type narrowing, etc.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBIFsCmAxArmYMC8MAUCAhgJ4BGSAylAE4CWYA5gPwBccN9DAlDgHwwBvAFAxRMWgDN8AQiJlKHRj2FjVMakihpqYANwixAXyEHRAejMw55KnUbiIMDABMkE+kmcwAPuzsN2WgAbIIAaGFI0WAgACxA0IK9yP05TKxIbRQDcawV-ADooEAAZEAB3JGoAYUIIJDwufUMgA)

### 💻 Code

```ts
const someFunc = (maybeString?: string) => {
    if (!maybeString) {
        return;
    }

    // maybeString is `string | undefined` still, but should be string
    maybeString = maybeString.toLowerCase();
}
```

### 🙁 Actual behavior

Bad practices aside, the `maybeString` at line 7 is seen as `string | undefined` when it shouldn't be.

### 🙂 Expected behavior

The `maybeString` at line 7 should be `string`, not `string | undefined`.

**Comment by RyanCavanaugh** [comment]
It's not.
```ts
const someFunc = (maybeString?: string) => {
    if (!maybeString) {
        return;
    }

    // maybeString is `string | undefined` still, but should be string
    maybeString = maybeString.toLowerCase();
    // Not an error
    maybeString.toLowerCase();
}
```

The tooltip shows `string | undefined` when you hover over the LHS of an assignment because it's showing you what the valid assignment types for that variable are

**Comment by Zombiefruit** [comment]
Ah. Got it. 

I'd assumed it was an issue because [this](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMGAbKBTATgIQIZQQAWGAzgBTBYgxQBcipUWMYA5gNoC6ANMmplwBPAPwMmLdgEpxzVpy6IA3gChE6xDGCJyAQhTpsOIVOVqNFrBiggsSKjSgBuc+oC+K1-0PDEAXm9BYwA6KDgAGTgAd2wAYTxSDHIpFy8rGztkalpgg0FyLwtKUz8APmRQiOi4hKSpYNYIVBAAEzJKASMTLxSVNyA) isn't working. I'm not understanding something. 

Thanks for the response, and sorry for wasting your time!
