### ISSUE TITLE
`noUncheckedIndexedAccess`: not working as expected in "for...of" loops

### ISSUE THREAD

**Issue by Znerole** [microsoft/TypeScript#42622]
# Bug Report

### 🔎 Search Terms

* noUncheckedIndexedAccess
* for...of

### 🕗 Version & Regression Information

* typescript@4.1.2
* typescript@4.2.0-dev.20210203

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210202#code/PTAEBcAsEsGdQKYA8CGBbADgGwaATggI4Cu0B8ARAHYD2AqlQMaQKMDWCAJgJJWfJcAgo0YJYsChBqgARrgRUUMnJymg0KDqFgKdAKD0AzYk3DQaVbTTQIAcsTRy8AMROMzFgBQB9AFygqBycASlAAbwBfA0YLWHB1AE9BPDwUBP9AxwQ8AG0AXVAAXlB8vTQklLScgFYC4uqDQxo8Txx46CLQAAYAblAOgB5E5NSEgDocKgBzKD6AajnoULC9UDXQGKo40AA3TvKRqugCtZBd-spMp1AAH1ATfkNoKi4KMffV9ehDUE89gEJioEsFhlutwWd3mMrP14i8uPBwNI5BsWOwuKAmnh7nwEE8XpxPuC1rBrHYgtlXKZzFQ-sEiaAolEjM1PJttnsaD8DpUEssGWc9nBQNQKXhJCgRM1OM8pmoACoJDAIADKjDw0Aw4ChArAUJhAHdcIwUJZsngLAgaMRYFgEhsUCCICxMW4PJYDdAoNb4sxWGxZZjmjjHs8uAzSTZ7FkXG6aXS9BEgA)

### 💻 Code

```ts
// this example requires "noUncheckedIndexedAccess" to be enabled to make sense

function someNumberFunction(_: number) {}

const myArray: number[] = []
myArray[5] = 5

for(let i = 0; i < myArray.length; ++i) {
    const v = myArray[i]   // v is "number | undefined"...
    if (v != null) {       // ... so it needs to be checked for undefined
        someNumberFunction(v)
    }
}

for(const v of myArray) {
    // v is "number" according to TypeScript...
    // ... so we can erroneously call the function without checking for undefined
    someNumberFunction(v)
}
```

### 🙁 Actual behavior

With `noUncheckedIndexedAccess` enabled, value `v` in the `for...of` loop is still treated as `number`, allowing to unwittingly further process an `undefined` value.

### 🙂 Expected behavior

Value `v` should be treated as `number | undefined` to be consistent with index access on arrays.

**Comment by RyanCavanaugh** [comment]
"Correctly" handling sparse arrays are not part of `noUncheckedIndexedAccess`. See the PR notes - https://github.com/microsoft/TypeScript/pull/39560

**Comment by Znerole** [comment]
Thank you, I overlooked that part and I get the rationale behind it. I wish JavaScript would differentiate between sparse and dense arrays, but here we are!

**Comment by RyanCavanaugh** [comment]
Me too 😅
