### ISSUE TITLE
How to connect typescript with ecmascript 6 library?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/TypeScript#4263]
Hello. I'm writed in modern ES6 typed library and want use with typescript. How to I can use declarations in typescript, If I used ES6 classes and statics?

Do not question what better ES6 or TS.

**Comment by mhegazy** [comment]
TypeScript is a super-set of ES6. so any valid ES6 code is valid TypeScript code. this includes classes and modules..

```ts
class C {
     constructor(public c: number) {
     }
}
export {C};
```
For more information take a look at the handbook at: https://github.com/Microsoft/TypeScript-Handbook
