### ISSUE TITLE
Cannot export a value if re-exporting a type with same name

### ISSUE THREAD

**Issue by marechal-p** [microsoft/TypeScript#42633]
# Bug Report

TypeScript usually allows exporting values and types with the same name.

```ts
// a.ts
export const a = 1
export type a = string
```

But it doesn't work when re-exporting a type from a third-party library and exporting an arbitrary value at the same time.

```ts
// b.ts
export const a = 1
export type { a } from './a'  
```

### 🔎 Search Terms

export type re-export error

### 🕗 Version & Regression Information

- Bug present in 4.1.3
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about re-export

### ⏯ Playground Link

https://codesandbox.io/s/misty-field-16f9f?file=/src/index.ts

### 💻 Code

```
export type { A } from "./a";
export const A = Symbol("A");
```

### 🙁 Actual behavior

Error:

```
Cannot redeclare exported variable 'A'. ts(2323)
```

### 🙂 Expected behavior

I would expect this to work since the re-exported name is purely a type.

**Comment by DanielRosenwasser** [comment]
I think this is working as intended. Import/export aliases can't merge with local declarations in TypeScript. What's more, `import type` doesn't strictly import the type side of things, it only restricts the things you can do with that import to type-like positions, so even if we wanted to ease the restriction just for `import type`, we still couldn't.

See

* https://github.com/microsoft/TypeScript/issues/33422
* https://github.com/microsoft/TypeScript/pull/31231
* https://github.com/microsoft/TypeScript/issues/31031

**Comment by marechal-p** [comment]
Should this limitation on merging behavior be documented in the appropriate section of the official documentation?
