### ISSUE TITLE
Add setting to disable  @return generation for JS Doc comments

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#42637]
# Suggestion

## 🔍 Search Terms
- JSDoc / jsdocs

## ⭐ Suggestion

Add setting to disable the new `@return` generation for JS Doc comments

This feature was originally added in https://github.com/microsoft/TypeScript/issues/14248

## 📃 Motivating Example

I worry that some users may not like the change that adds `@returns` automatically

We can enable this new feature by default, but should have an easy way to turn it off.

**Comment by mjbvz** [comment]
My proposal would be to add a new parameter to the `docCommentTemplate` request that determines if returns are generated or not:

```ts
    interface DocCommentTemplateRequest extends FileLocationRequest {
        command: CommandTypes.DocCommentTemplate;
        arguments: DocCommentTemplateRequestArgs;
    }

    interface DocCommentTemplateRequestArgs extends FileLocationRequestArgs {
        generateReturn?: boolean; // new field
    }
```

/cc @RyanCavanaugh Since I think we should address this before the 4.2 RC

**Comment by a-tarasyuk** [comment]
> Since I think we should address this before the 4.2 RC

Based on the [Iteration Plan](https://github.com/microsoft/TypeScript/issues/41601) RC will be created tomorrow. So, I've created a Draft PR to resolve this issue.

/cc @mjbvz

**Comment by RyanCavanaugh** [comment]
@mjbvz RC is very soon and this feels like a feature, can we add configurability in 4.3?

**Comment by mjbvz** [comment]
This is a new feature in 4.2, so I'm concerned we're going to get complaints about the change in behavior once this feature goes out. Having a setting to disable the new behavior would be helpful if people do not like the new behavior
