### ISSUE TITLE
Specialized overload signature is not assignable to any non-specialized signature.

### ISSUE THREAD

**Issue by skinnysoftware** [Microsoft/TypeScript#4264]
The following block of code will generate the error "Specialized overload signature is not assignable to any non-specialized signature.":
```
function fn(val: "left");
function fn(val: "right");
function fn(val: any) {
    // Do something here.
}
```
This block of code is accepted by the compiler (and of course provides an unwanted overload):
```
function fn(val: string);
function fn(val: "left");
function fn(val: "right");
function fn(val: any) {
    // Do something here.
}
```

This occurs in VS 2015 using TypeScript 1.5.3

**Comment by RyanCavanaugh** [comment]
The `any` overload is not actually there. When you declare a function with overloads, the implementation signature is not visible.

**Comment by skinnysoftware** [comment]
I'd like to clarify ... although this is by design, does it not defeat the purpose of using specialize signatures and stray from the pattern set by non-specialized overloads?

(What I'm getting at is this seems like a confusing design)

With non-specialized overloads, only the implementation signature is required to be compatible with all overloads. By forcing specialized overloads to be assignable to non-specialized overloads we are left with an unwanted overload that would give another developer the impression that the non-specialized overload is intended to be called and will produce a valid result. This may not always be the case.

By comparison, if we applied a similar rule to the use of non-specialized overloads, clearly we can see an undesirable result.

```typescript
function setValue(val: string);     // This is useful.
function setValue(val: number);     // This is useful.
function setValue(val: Date);       // This is useful.
function setValue(val: any);        // This would NOT be useful.
                                    // We don't want developers passing in arrays or complex objects.
function setValue(val: any) {
    // Validate and return to server.
}
```

Also, for reference, both examples appear to be valid. I have used @RyanCavanaugh's declaration in the screenshot below to illustrate.

![screenshot](https://cloud.githubusercontent.com/assets/13737994/9185288/c8cdd6ea-3f77-11e5-801f-c646705a6022.png)

**Comment by RyanCavanaugh** [comment]
Note that "specialized" means **only** "contains a string literal". In your example, the visible overload taking `any` is not required.

This is a legal declaration:
```ts
function setValue(val: string);     // This is useful.
function setValue(val: number);     // This is useful.
function setValue(val: Date);       // This is useful.
function setValue(val: any) {
    // Validate and return to server.
}
setValue({x: 32}); // Errors
```

This is *not* a legal declaration:
```ts
function setValue(val: "left");
function setValue(val: "right");
function setValue(val: Date);
function setValue(val: any) {
    // Validate and return to server.
}
```
We disallow this because there's no reasonable way to enforce, at an arbitrary call site, that you're only passing in the exact strings "left" and "right".

**Comment by skinnysoftware** [comment]
Thank you @RyanCavanaugh. When one considers that a developer might be doing `setValue(myVariable)` instead of `setValue("some text")` it becomes easy to understand the reason behind the design.
