### ISSUE TITLE
4.2 breaks string literal conditional type checking.

### ISSUE THREAD

**Issue by akutruff** [microsoft/TypeScript#42644]
# Bug Report

In TypeScript 4.1, a type can be constrained conditionally to be a string literal.  In 4.2 conditionals can not enforce string literals

```ts
type StringLiteral<T> = T extends `${string & T}` ? T : never;
```

### 🔎 Search Terms

string literal, conditional types, breaking change

### 🕗 Version & Regression Information

- This is a breaking change
- This changed between versions 4.1 and 4.2 
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about string literals
- I was unable to test this on prior versions because string template literals were introduced in 4.1

### ⏯ Playground Link

[Playground 4.1](https://www.typescriptlang.org/play?ts=4.1.3#code/PTAEHUFNQdwQwHYBdRIPajQgNgT1HNtmjKAM5IBOAlggOajbVKSWFkCwAUErgA7QAylVp0AMs1aEAPABUAfKAC8oWaEgAPFggAmZUAAMAJAG8KNeqABkqgL4HQAflWgAXKASQAbqwDc3bgBjLApGSTZsWTQAYRCqOFpIHQkWCLdQYQtxcJkAcgAjNHzcxRUCotzfUBAMgAs0AFdsHVB86EJiGCSCfUL80Gp9OHIRSyZUwgCuGoAWADoARgJdUHmAJncABUo0HQbAyCHQAHEAeVOAEVBggFs+amxWdUodyh7WooH9YIRzBM8WuhWu0whNsHMMqNsmDpOViopKIc0NgfPogXDckE4iMslFYr94olkjlsOlMqIUlJsLC+iVlKAABQY97mUQASiqU1mi3cZ0u7nJ9EpEWkrPoCKRKMOqAwnh8lAhoG43I2oAAQgBBC4CqHCmRiugSsjI1EynGiRUAOQwt3ujzerFeoD4Oz2Bx0cyxBPN9CigoYOqyeupBtKjOZcH0Bo5Sq4yrADTI0ECkcg7gAor8GojULU4ChjTdIFhoINMDh8Ii6INUqJQF5qMNhgbQVTFQBVJMAMyasFqkAQoETdZTRHycECAGtQDc4HxeqmWlhQDpBoEaDdaPnug0ENQQp6uD2EIEkPvB1Wa6wNafz3J5AyJ2fl4GKST72zQCZbFywLJamWZZ0GguzkLQBygLkgRMFOSS5F8BCthE3CXhQ163lgTLQdQsE6LkHK-vMCy8uc2qgNsuz7NKwy2g8TyOmglDxus7iamRsR3HRbwdCQaIAZwXCoakN7PggWEwZOcEslCMaxtwQA)
[Playground 4.2](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/PTAEHUFNQdwQwHYBdRIPajQgNgT1HNtmjKAM5IBOAlggOajbVKSWFkCwAUErgA7QAylVp0AMs1aEAPABUAfKAC8oWaEgAPFggAmZUAAMAJAG8KNeqABkqgL4HQAflWgAXKASQAbqwDc3bgBjLApGSTZsWTQAYRCqOFpIHQkWCLdQYQtxcJkAcgAjNHzcxRUCotzfUBAMgAs0AFdsHVB86EJiGCSCfUL80Gp9OHIRSyZUwgCuGoAWADoARgJdUHmAJncABUo0HQbAyCHQAHEAeVOAEVBggFs+amxWdUodyh7WooH9YIRzBM8WuhWu0whNsHMMqNsmDpOViopKIc0NgfPogXDckE4iMslFYr94olkjlsOlMqIUlJsLC+iVlKAABQY97mUQASiqU1mi3cZ0u7nJ9EpEWkrPoCKRKMOqAwnh8lAhoG43I2oAAQgBBC4CqHCmRiugSsjI1EynGiRUAOQwt3ujzerFeoD4Oz2Bx0cyxBPN9CigoYOqyeupBtKjOZcH0Bo5Sq4yrADTI0ECkcg7gAor8GojULU4ChjTdIFhoINMDh8Ii6INUqJQF5qMNhgbQVTFQBVJMAMyasFqkAQoETdZTRHycECAGtQDc4HxeqmWlhQDpBoEaDdaPnug0ENQQp6uD2EIEkPvB1Wa6wNafz3J5AyJ2fl4GKST72zQCZbFywLJamWZZ0GguzkLQBygLkgRMFOSS5F8BCthE3CXhQ163lgTLQdQsE6LkHK-vMCy8uc2qgNsuz7NKwy2g8TyOmglDxus7iamRsR3HRbwdCQaIAZwXCoakN7PggWEwZOcEslCMaxtwQA)

### 💻 Code

```ts
// We want to only allow string literals
type StringLiteral<T> = T extends `${string & T}` ? T : never;

const literalToConstrainedLiteral : StringLiteral<'bob'> = 'bob'; // Should be allowed as bob is a string literal

// 4.1 and 4.2: Produces a GOOD compiler error as bob is constrained to be a literal. StringLiteral<'bob'> resolves to 'bob'
const stringToConstrainedLiteral : StringLiteral<'bob'> = ('bob' as string); 

// 4.1: GOOD: StringLiteral<string> resolves to never.  
// 4.2: BAD: StringLiteral<string> resolves to string.  No compiler error produced.
const stringToString : StringLiteral<string> = ('bob' as string); 

// use case: Ensure that someone is only registering via a string literal.  Useful when using callback maps based on discriminated unions.
function registerAction<T>(action : StringLiteral<T>) {}

// This is good since 'clicked' is a literal
registerAction('clicked');

//4.1: GOOD: Produces a compiler error
//4.2: BAD: Compiler allows this
registerAction('clicked' as string);  
```

### 🙁 Actual behavior

TypeScript 4.2 does not produce compiler errors when the type is too wide.

### 🙂 Expected behavior

Produces compiler errors when the type is too wide.

**Comment by DanielRosenwasser** [comment]
Seems like we didn't used to simplify `` `${string}` `` to `string`, which was probably a bug. I understand the desire for an "only assignable to string literals" operator, but I think the new behavior makes sense. I just can't look at the code that's provided and understand why `` `${string & T}` `` should ever reject `string` in the cases where `T` is instantiated with `string`.

**Comment by akutruff** [comment]
Hmm, this was my train of thought - Since string literal templates _should_ only allow literals as input then it makes sense that only a literal passed into a template can actually resolve to a literal type.  

```ts
type AB<T extends string> = T extends `${string & T}AB` ? T : never;  
type ABTest = AB<'foo'>; // makes sense that this is never.  The condition is: 'foo" extends 'fooAB'

type A<T extends string> = T extends `${string & T}A` ? T : never;  
type ATest = A<'foo'>; // makes sense that this is never.  The condition is: 'foo" extends 'fooA'

type Same<T extends string> = T extends `${string & T}` ? T : never;  
type SameTest = Same<'foo'>; // Should be 'foo' because -  The condition is: 'foo" extends 'foo'
```
[playground](https://www.typescriptlang.org/play?ts=4.1.3&ssl=9&ssc=1&pln=1&pc=1#code/C4TwDgpgBAggQgHgCpQgD2BAdgEwM5R7ABOAllgOYB8UAvFCuprgQAYAkA3kWZVAGQMAvvFZQA-AygAuKFggA3CMQDcUKAFgAUKEiw4SCETr6EAcgBmAeytmqagPQOoAWwCGAayOFseaMAALN2AoQNICcLlFZQA6dSQA6ABjK1xSYFJUqHDZSxsAIlQMbHwoPKt4M21tXWgYZCLmUp5yahNGYpYoDm4SVoFhGDFJFFl5JVV1GvA6w2N6evK7R2d3LwI-LD9QoJCwiIJx2PjEqBS0jKycsusrQqYSgnKYKq1pvQBlNxcIBoeulqUGj0DpNNhcQEUAZIITDKRjaKTTQ6GZQL4-OYhejo35LexQJxogJWACuABscFAAEbQJbUiBJNwk7YAWhOyVSOHSmSw2TwuVu906pSW2iAA)

Next is for the sake of consistency and maintaining the spirt of literals being a narrowing mechanism.

```ts
//4.1: resolves in intellisense to `${string}`
//4.2: resolves in intellisense to string
type Foo = `${string & string}`; 

//4.1: resolves in intellisense to `${number}`
//4.2: resolves in intellisense to `${number}`
type Num = `${number & number}`; 
```
[playground](https://www.typescriptlang.org/play?ts=4.1.3#code/PTAsDoEYC4AICcCmBnA9gGwG4tgSwHZ74Aui66uyi+VsxqsABgCQDeyx8BA5gL6MBYAFAgIAJjhI0WHASKlylarXqwOXfN2HEAngAdEsAGKoGAXiZt1PWADI1nHvwDcsYcNFRJKDNmRF5MgoqGkNVFlZ8AFcAWwAjRHh+DzBwCQQfGX85AgVg5TCGCOj4xOShXQNYADlY2Ati2IT4O1gS5pdYIA)

I am using a string literal template, and I would hope that a string literal template would ALWAYS resolve to a string literal, and not promote the contents of the ```${}``` outside the literal itself.  The input of a string literal template should always be a literal.  If it doesn't make sense for ```${number}``` to widen, then neither should ```${string}```.  

```
type NotReallyALiteral = `${string}`; 
const someValue : NotReallyALiteral = ('something' as string);
```

Side note: this breaks all of my type declaration code if this is not a regression.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts?

**Comment by ahejlsberg** [comment]
Daniel is correct, we used to not reduce `` `${string}` `` to `string`, but we now do--and it's the right thing to do. There should be no observable difference in behavior between those two types.

I'd suggesting writing the `StringLiteral<T>` type as this instead:

```ts
type StringLiteral<T> = T extends string ? string extends T ? never : T : never;
```

That works in both 4.1 and 4.2 and really makes more sense--it expresses anything that extends `string` but isn't `string` itself.

**Comment by akutruff** [comment]
Thanks, and that's a super clever alternative.  Thank you all for your time on this!

**Comment by clayne11** [comment]
None of these approaches seem to work. anymore. I have some pretty cool ideas for a library / SDK I can build if I can get TypeScript to infer a single string literal from a generic like `<TString extends string>`. [gql.tada](https://github.com/0no-co/gql.tada) does some pretty cool inference, but it seems to all work on predefined literals / the known ahead of language grammar of GraphQL.

For example `In extends `!${infer In}` ? _state<In, [...Out, Token.Exclam]>` can match a string that starts with `!` and then map the result into a new type. For my library, I want to simply infer the entire string literal and build an object using this as a key.

Was it intended to kill this capability?
