### ISSUE TITLE
Type alias for Record does not allow recursion

### ISSUE THREAD

**Issue by thers** [microsoft/TypeScript#42648]
# Bug Report

### 🔎 Search Terms

record recursion TS2456 ts(2456) 2456 circularily references type alias

### 🕗 Version & Regression Information

Reproducible on:
 - 4.2.0-dev.20210204
 - 4.2.0-beta
 - 4.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/PTAEFECdIe0hYAUAFwJ4AcCmoBKmDGArpAM4CWAbpnvnACagC8uB9APCcpGQHYDmAGhZFSlaq0gMAPqB6EANvIB8AbiRIQoAGK9MSNFmHFyVALIBDdE1AX0HLr0FHRZy6BlzFq9Yk0BBeRIYbV19DGwaYzEASS1zfGxmAG9QAG0Aa0xUAC5QTm5+AF1cyJdMWPjsDwV5UABfFSA)

### 💻 Code

```ts
// Error: Type alias 'RecursiveRecord' circularly references itself. (2456)
type RecursiveRecord = Record<string, RecursiveRecord | null>;

// Fine
type RecursiveMap = Map<string, RecursiveMap | null>;

// Also Fine
type RecursiveIFace = { [key: string]: RecursiveIFace | null };
```

### 🙁 Actual behavior

TS2456 error for `RecursiveRecord`.

### 🙂 Expected behavior

No error for `RecursiveRecord`.

**Comment by RyanCavanaugh** [comment]
Duplicate #41164
