### ISSUE TITLE
Set.has typing

### ISSUE THREAD

**Issue by mbelsky** [microsoft/TypeScript#42641]
# lib Update Request

## Missing / Incorrect Definition

The `Set.has` method's type expects that `value` type is `typeof T`:

https://github.com/microsoft/TypeScript/blob/master/src/lib/es2015.collection.d.ts#L43

And this definition makes safe-code uncompilable.

## Sample Code

```typescript
const set: Set<number> = new Set([1, 2, 3, 4])

set.has(5)
set.has('error?')
        ^^^^^^^ Argument of type 'string' is not assignable to parameter of type 'number'.
```

[sandbox](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=5&pc=1#code/MYewdgzgLgBBCmUBcMDKiA8YCuBbARvAE4B8MAvDGPAO5qIAUA2gIwA0MATBwMwcAsAXQCUAKFEIoAOgAWAQwgMArGMmyFDAOTEiIIgH5NYoA)

## Documentation Link

https://tc39.es/ecma262/#sec-set.prototype.has

---

Well what do you think about replacing this method definition with this:

```typescript
    has(value: unknown): boolean;
```

**Comment by MartinJohns** [comment]
Checking the existence of a value that can't be present (according to the type system) should be an error. Why would you want it to be different?

**Comment by mbelsky** [comment]
I've came with this issue because now users need to add unnecessary type guards to make a safe operation in their code. An example:

```typescript
const set: Set<number> = new Set([])

const list: unknown[] = [1, '2', {}]

list.map((item) => {
    if (typeof item === 'number') { // you don't need this type guard, but the code won't compile without that
        return set.has(item)
    }

    return false
})

```

**Comment by jgbpercy** [comment]
Right, well as Martin says, either do:
```
const set: Set<number> = new Set([])

const list: any[] = [1, '2', {}]

list.map((item) => {
    return set.has(item)
})
```
Or:
```
const set: Set<number> = new Set([])

const list: unknown[] = [1, '2', {}]

list.map((item) => {
    return set.has(item as any)
})
```

...if you want do something like your example code without adding any code that will be present at run time. Although if it were me I'd generally write the version with the type guard! `unknown` is a deliberately restrictive type that's designed to flag these sorts of things as errors if you're not asserting or guarding to a more specific type, `any` is designed to be permissive.

**Comment by RyanCavanaugh** [comment]
Ideally this would be a bivariant parameter; see https://github.com/microsoft/TypeScript/issues/14520. `Array#includes` has the same problem.

The current behavior is the best available compromise. You're free to add the `unknown` overload to your code if you want to opt in to the less-specific version.
