### ISSUE TITLE
Is type assignment a simple compatibility check? Or is it an assertion? TypeScript says "both, sometimes"

### ISSUE THREAD

**Issue by asktree** [microsoft/TypeScript#42656]
Note: I can't tell if this is a bug in the code or a "bug" in the specification. I figured I'd write my "bug" report first and only follow with a feature request if it turns out this is "working as intended".

By "type assignment" I mean setting compiler's expectations about a variable's type using a colon during declaration: `const myThing: MyType = 1`

# Bug Report
I couldn't find a specification of what type assignment is _supposed_ to do (or even what this syntax is called to begin with)

Two plausible-seeming specifications for type assignment, such that behavior is consistent:

1) 
- it enforces structure (blocks compilation if value is incompatible with assigned type)
- it does nothing else (what else is there to do? TS is structurally typed, so as long as there's no problem with the structure, the compiler has no reason to think about this assignment anymore )

2) 
- it enforces structure
- it also _asserts_ structure (overwrites compiler's view of structure)
(this would be a weird spec because if you want this assertion behavior you can just use an assertion)

In actuality, the behavior of type assignment is 1) sometimes and 2) other times. So, either consistency across values is not a part of the specification (which would be weirder still) or there's a bug.

### 🔎 Search Terms

type assertion
type assignment
type contract
type declaration
type check

### 🕗 Version & Regression Information
I made my gist w/ 4.1.2. AFAIK this discrepancy exists on all previous versions.

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.0.5#code/PTAEBUE8AcFMGcDGAnAltALqANrD9RIB7AV1GhK0SIDt4NkBDVG-UW0R+eVAcxoC2sVqAC0o0NSLYAsACgQY0AElQAE1oByLAGsaRAO6gDAC0ZYMJ1AQBmscyWSxQ19jZupEqRtmyRJPrhqnDTBiIw02qAeoS4YAHTyijZEyKCwAB6MAtC4ADSgGLC+LLyFJs7KACIAouXmnJK09BFY8Cak2MEARs6wAG7C8hgwfYM0oAC8oABMoAA+oAAsC6AAbADc8tR0WIxTs1tyO-Sg3QBc6eMHM0cnVJcDwgdLd81Yao-X0wDMG6CKWDIZCpS73JgsLD9VDScwwmjyJJgYhkcITLjwIEWUbwAqWVyuNSodxA4QYACE23e6jmv04BCeNH+igAcgB5dLA0GFZAkZwYrHwxEKMAAVRo2FQOn53EFtAKGL4gjJoAAVGjVeQnJjkIMXDQUsgBHDaEjQAAKbqUdRaLC8PDpDJeIpqACUw1GWtQQhuqx+qwArG9dqAMpdoGgfdNGMHTpBw5HnNNusywBoEKB9FggSDkAruEqhCJwcwRETgln1AgGER-CxDcaMELjtSAF4J71JySpm0ZnOpBXQCNECPeIrC+5nWmzelXYSxrCQGYdqNTnvphlcvP0nVN5o2qv0EF1g2pRvNs0AYkvoBZhhweE0BAY-gMqEsoCcjA0Ev8RG6ABWsCIPgE7UgAggcADemaXHMAC+s73AuoAABorl24HxEyAJpkQGaVv227gAAyqAeiGAQAAGWETJM9GzFRZzAYwJCYnET6fvYP5+GBIYAMKXDBNBfM8iHTMJlz+ohXBNLsPZEQQ1DAsBGB+GIEiWM4JaQi4BCVhEO5ygichUiGABCQmwXOEziaAkkzjJSnvChACaGEHOZ2H-GamRwCBsCfJmRCcrmBRUV5NBMa4o4+hEwQGM45aRHssrIAkZqAOrkgDwf6AOV5bl4EgSQPiXBuoUDjuhYqjpIhVNUh41ieDYmjQ5LtcKig3oAKuSgAAEveaIqIUxTYOU2lEDkqC4GklgNKoBitKA8CTXgVg0GUGAhb0biFJ6VFQSJNnwUxb6WKQHzVsepT6i1e40AA-GZpxVNB1nSUhLmdWA16gIAoOTjTg2TOIt-jmjsGClgQgz0Hw3hjbyrCdstGAkO47otiGiAVIgOgHAAPOAAB85phhArpTET9nwXcOM6PjDmMqA8Ek+Bro9voFXINsdMM9ZTMs+aVTs7hXMFP6riEeM32gL9ANaUDQhpKDFoCKkzgw02vDw5+JBIz69BozYGOTtjwHSmo4FWUdAsHOBHMhURz1UHTgWCfZ-PXHZVQKVuMu-YAMuTlK4Zj6SFiNNj6KCMNAZzWj4K29vAKXGKkePmlR-F0-xBw0E8yBMVabRNr4TRTbg8AYyMcCgFn5uQdM1ewEQNigJBABkHs217RxN7X2cHE3LegK9neMz3-s3vLVgEAYacEPFNk4EQRA6AQkrShAoyiFUaDXFUTzYCORYUvEZ-yGowHYIwTgPnaolMvIZS-L7uaXHPIWS0QWA-GaQdn-EOOHx8LJyiHPZAeMzomDkvQGWyg2iwFgAIdeUpnACH8DHYcjAzbPjMFgFg-RpB6gjsjagl9OC3wVrQdSoNnwhQ0HERIIphpfl8P4Ik8AN7ODmqlHg-AT4wIYKWNgQ1L5HlrLdM8rUmGKHABUdQxI7BOBoIgZwvQMCJWeIqfhNV3gQlYAvWIAp0rwgIO0ToPQJp0GsEUEQ2CQTcFAP0HwfJ4DxCAA)

### 💻 Code

I made a comprehensive Gist with expected/actual in comments
https://gist.github.com/asktree/8ab244583d4163f09a5a15ba5f60c7a3#file-informationdestruction-ts-L31

The gist also covers workarounds.

**Comment by RyanCavanaugh** [comment]
I think you're looking for #7481

Type assertions (`e as T`) are primarily used to downcast, so the fact that they are able to do so is a design goal rather than a design surprise 🙂

**Comment by asktree** [comment]
@RyanCavanaugh 

#7481 is relevant to the last part of my gist -- where I look for "workarounds" / ways to achieve what intuitively it seems like type assignment should be doing already. 

But it is not relevant to what I'm writing this issue about: ambiguity and inconsistency regarding what the type assignment syntax does.

**Comment by RyanCavanaugh** [comment]
Nothing in that gist is ambiguous or unexpected per the rules of the language. StackOverflow would be the best place to continue this conversation since there are many more people there able to answer these sorts of questions.

**Comment by RyanCavanaugh** [comment]
Basically the TL;DR is that if you have some initialization
```ts
const p: T = e
```
then subsequent references of `p` have the type produced by narrowing `T` via `typeof e`. If `T` isn't a union, then there's no narrowing that can (or should!) be performed.

**Comment by asktree** [comment]
@RyanCavanaugh 
So this feature is called initialization? How would I find the rules / what to expect from this syntax?

**Comment by asktree** [comment]
This gist is me doing "science" about what this syntax does, from my experiments I concluded that simple literals were narrowed / preserved while objects weren't. It makes sense that what's really going on is that we're only narrowing unions.

that is, I thought
```ts
const u: number = 2
const i: prime = u
``` 
would not error, but it does (`number` can't be assigned to `prime`)

So I'm satisfied that this isn't a bug.

I still don't understand your comment that narrowing should not be performed, but that is because I don't understand what this syntax is meant to be used for if it doesn't do the thing #7481 is asking for. Normally I would just consider that a StackOverflow question but in this case I'm not sure that the documentation even exists -- googling "Typescript type initialization" didn't direct me to it.

**Comment by RyanCavanaugh** [comment]
https://www.typescriptlang.org/docs/handbook/2/narrowing.html covers many aspects of this, as does https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions . Really it's good to read the entire handbook, since this a minimum provides the necessary vocabulary to discuss these things unambiguously

**Comment by asktree** [comment]
@RyanCavanaugh I don't agree with the claim that either of these pages provide the necessary vocabulary (I still don't know the name of the syntax this issue is about). The case that I'm writing about (variable assignment outside of function arguments) doesn't even appear on the page.

This page also doesn't give me any reason to expect that narrowing can't or shouldn't happen deeply: that is, no reason to expect that `{a: 1} | {a: 2}` can be discriminated but `{a: 1 | 2}` can't.

**Comment by RyanCavanaugh** [comment]
Noted; I'll try to update the narrowing page with a bit of context there.

Anyway the issue tracker is for code defects and there isn't one here, so I'll close this. Thanks!
