### ISSUE TITLE
This condition will always return 'false' since the types have no overlap.

### ISSUE THREAD

**Issue by jhowcrof** [microsoft/TypeScript#42654]
# Bug Report

When writing code, I sometimes want to test out several implementations and flip between them over time. One simple way to flip back and forth is just to add a constant to the code and change it when I want. I'll probably remove it or add some build def or url param to control it more explicitly later on, but for now I just want to write it this way. TypeScript makes this annoying because of the control flow analysis.

### 🔎 Search Terms

Control flow
This condition will always return 'false'

### 🕗 Version & Regression Information

- I don't think this is a regression - this is clearly intended behavior but I don't want it.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYOwrgtgBAsg9gE2FA3gKClAglAvFABgBoMoAhPKARhIF8BuNNAYzhAGcAXWAeQBEAopXhIAdGUZoAlgDMoAChj8huVbETBRWAJSpMAen1QBAJxNwTALigAVABZT2UViARTOUtlADuUgDZ+UACGft5BAJ5OJsCcYCYgUADkMiHswIlQ7FIgzMicdnnhAA7ATokimmQZQa5JFVoZdkEAbsggcFBwrSZ+QUWiGIZQCB3scBAxDiAA5mi0UMB+aaiDRiOZ45PZ0wtLwHNMQ-aOPhYA1uzScorKwU4VeGr1OisHQA

### 💻 Code

```ts
enum Mode {
  A = 0,
  B = 1,
};

const MODE = Mode.B;

if (MODE === Mode.A) {  // Error: This condition will always return 'false' since the types 'Mode.B' and 'Mode.A' have no overlap.
 // do something
} else {
 // do something else
}

```

### 🙁 Actual behavior

Error: This condition will always return 'false' since the types 'Mode.B' and 'Mode.A' have no overlap.

### 🙂 Expected behavior

Just compile and let me write the code that I intended. I have never benefitted from this type of control flow analysis, and this should be a warning at most, not an error.

I was able to work around it by adding a cast, but it looks unnecessary:
`if (MODE as Mode === Mode.A) {`

**Comment by turtleflyer** [comment]
You can aim at the desirable compiler behavior by simply adding explicit `any` to the type of const:

```ts
const MODE: any = Mode.B;
```

**Comment by RyanCavanaugh** [comment]
This detects all kinds of logic bugs and we're not interested in turning it off

**Comment by siakc** [comment]
The original code would cause the same error if MODE was a var instead of a const. In that case MODE value may change at any time so it would be wrong to throw an error.
