### ISSUE TITLE
abstract class implements private field unexpected error

### ISSUE THREAD

**Issue by septs** [microsoft/TypeScript#42660]
# Bug Report

### 🔎 Search Terms

abstract class, private field, implements

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.1.2
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIkIDEAJgK4C2NAngFwIB2tIAplIQL6GGhIMeElToEAIWBQEASxoAHZBxocWEDDjxFS5anSat2XXkA)

### 💻 Code

```ts
abstract class Foo {
    #dummy: number
}

/**
Class 'Bar' incorrectly implements class 'Foo'. Did you mean to extend 'Foo' and inherit its members as a subclass?
  Property '#dummy' in type 'Bar' refers to a different member that cannot be accessed from within type 'Foo'.ts(2720)
**/
abstract class Bar implements Foo {
    #dummy: number
}
```

### 🙁 Actual behavior

```plain
Class 'Bar' incorrectly implements class 'Foo'. Did you mean to extend 'Foo' and inherit its members as a subclass?
  Property '#dummy' in type 'Bar' refers to a different member that cannot be accessed from within type 'Foo'.ts(2720)
```

### 🙂 Expected behavior

No error

**Comment by septs** [comment]
the private field should not be spread to subclass.

**Comment by MartinJohns** [comment]
This looks like #37924 / #37447. The behavior is the same, regardless of using private fields or the `private` / `protected` access modifier.

**Comment by septs** [comment]
@MartinJohns 
subclass in a es private field is not-accessible.
but typescript private / protected access modifier but is it's only semantically

**Comment by RyanCavanaugh** [comment]
This is the correct behavior. `implements` checks assignability, and nothing that isn't a subclass of `Foo` can be assignable to it. Used a mapped type to remove the private fields if that's what you'd like to happen instead.
