### ISSUE TITLE
Records assigned to type parameters lose key compatibility only in *.ts files

### ISSUE THREAD

**Issue by peterhudec** [microsoft/TypeScript#42666]
# Bug Report

When a `Record<string, any>` type (let's say `MyRecord`) is assigned as a default value of a type parameter `R`, their keys are not compatible. Moreover, `keyof R` is not even compatible with `string`. The actual problem seems to be that TypeScript thinks that the keys `K` generated with `[K in keyof R]` still have the type `string | number | symbol`, even though both `MyRecord` and `R` are string-keyed .

Oddly enough, this only happens in `*.ts` files and works without errors in `*.d.ts` files.

### 🔎 Search Terms

mapped key, ts d.ts difference, declaration file mapped key, keyof type parameter 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiBKEDGB7ATgEygXigbwCgooBDALigHIBBSgGiKgCMLKAhexpVgYU4F8CBUJCgAxFCgA8AFSgQAHsAgA7DAGco64GgCWKgOYA+HFBnDw0NiTSz5S1RqgBrCCBQAzWAmToMJ3HMCAHpgqABJLzhEVEwoXU0SdXVdAxUILCTSKAwIDxIAVwAbYCgANxIigugSKCKUJEqoEWgwGxIAWwhlNDooELDXdyifWMy1FzdPKHhSNGgVFFL1CFVSTVQOtuBdJiKIPsXSiDK1gHddYAALLR19AwA6AbMrhKgUFSKQKCuSMEgVJp9FAAFQPYCaDy6faaJgFUpndDOIEqUEPDDgyHQiDqJ4tbwySxSWaKZRqTTRXxxXCUsZ9ADSAGV7GSnENprNcOyvPAAvhGABtenxVFMgC6FAFjGIoTMlio9MoORQOKgRy0JB26g832u0FQgJ0JH0pUo2j0hkoT2IMrCxEJokoTKVb3VSRSaRIe2gwBQzXlZrulutNtlNrlju5MxdmjdyVSKi9+2afvxgYtBit0qgYfDEeg6fuUAAPmqCh0mBA0CWtCAKygijG1Ut1h7E96U-7Heb7lnw7m8-mqCpy5W0E2422kz7UwGe8HsxJpPSjAxs7KHQXFcrVer1JqEjrmld9R9zcaVKaAEQkK81q9MO+lq9IK990N2odOxkTlvuhPTp2aY3k+UAPqBL5viGtp5puVBRvAv6lP+nodr6XYFiB96Pver7vjBg5wYWhg1iOFZVjW6h1kwDZIa2AFobOjpYc+OHPnh0E5p+hFzkGmbxLGf7xqhybocBt7YRBHHrtxg5fghdEoe2olMZh0n9rJclfs6AnNshwnKTOGFUJB+FcVpclEdurpCVOjHGZQpmcQOFnhlZP66ZODEqQ5Tkya5FlEQpnm2d5RnAepH4Ba5RHzgYpGjhRpZUfWjYhfpdk+RFUHZtYtgrmu4ZLlITKruZ7lKhgKqCcsB7arqJ5QAa54mlQcVmXlJWMmVG4BjpVW7i2+5akeepNWeRqtY5EmsVJOXhrSfhCmKfS9Y626NCo6qVlABQrFg6H6LkCgOYtmBmfAy2rWEADy9KMGKBCCBYogABqmMVUZnf4L3QAAmqYnVfaMfhGEIsrhKi6hgJc0DTGNVZoOg6h9HAcGImgyLrPYkBIMoGC-WYpho5Yzz4nIuCELm5BQAKIF9PTYEzWBbFga+DPM+BuFXgz1A82BfNigA3M8xAsLT4EM4+HMQazkEy5J3MM2w-NXirwui01kry2zquc3L7NM7Lc0Mzwqtmxrsr8EAA)

### 💻 Code

```ts
type MyRecord = {
  a: 'A',
  b: 'B',
  c: 'C',
}

type Foo<T extends string> = T
type Bar<T extends keyof MyRecord> = T

// If MyRecord is assigned as a default value a local type parameter R, 
// keyof MyRecord and keyof R are not seen as compatible,
// keyof R is not even compatible with string.
// This only happens in *.ts files but works in *.d.ts files.
type MyType<R extends MyRecord = MyRecord, KS extends keyof R = keyof R> = {
  [K in KS]: [
    // Type 'K' does not satisfy the constraint 'string'.
    //   Type 'KS' is not assignable to type 'string'.
    //     Type 'keyof R' is not assignable to type 'string'.
    //       Type 'string | number | symbol' is not assignable to type 'string'.
    //         Type 'number' is not assignable to type 'string'.
    Foo<K>,

    // Type 'K' does not satisfy the constraint '"a" | "b" | "c"'.
    //   Type 'KS' is not assignable to type '"a" | "b" | "c"'.
    //     Type 'keyof R' is not assignable to type '"a" | "b" | "c"'.
    //       Type 'string | number | symbol' is not assignable to type '"a" | "b" | "c"'.
    //         Type 'string' is not assignable to type '"a" | "b" | "c"'.
    //           Type 'keyof R' is not assignable to type '"c"'.
    //             Type 'KS' is not assignable to type '"c"'.
    //               Type 'K' is not assignable to type '"c"'.
    //                 Type 'KS' is not assignable to type '"c"'.
    //                   Type 'keyof R' is not assignable to type '"c"'.
    //                     Type 'string | number | symbol' is not assignable to type '"c"'.
    Bar<K>,

    Foo<KS>, // Type 'KS' does not satisfy the constraint 'string'.
    Bar<KS>, // Type 'KS' does not satisfy the constraint '"a" | "b" | "c"'.
    MyRecord[K], // Type 'K' cannot be used to index type 'MyRecord'.
    R[K], // OK
  ]
}

type X = Foo<keyof MyRecord>
type Y = Bar<keyof MyRecord>

// In spite of the errors, MyType works as expected
type T = MyType
// type T = {
//   a: ["a", "a", "a" | "b" | "c", "a" | "b" | "c", "A", "A"];
//   b: ["b", "b", "a" | "b" | "c", "a" | "b" | "c", "B", "B"];
//   c: ["c", "c", "a" | "b" | "c", "a" | "b" | "c", "C", "C"];
// }
```

### 🙁 Actual behavior

1. Keys of a type assigned to a type parameter as a default value are not compatible with the keys of the type parameter when iterated over in a mapped type.
2. This only happens in `*.ts` files, but works in `*.d.ts` files

### 🙂 Expected behavior

1. I would expect the type parameter to be just an alias for its default value and thus their keys to be compatible
2. I would expect that the semantics of `*.ts` and `*.d.ts` files are the same.

**Comment by MartinJohns** [comment]
> I would expect that the semantics of `*.ts` and `*.d.ts` files are the same.

They do behave the same. The error you see occurs in a `.d.ts` file as well.

**Comment by RyanCavanaugh** [comment]
> I would expect the type parameter to be just an alias for its default value and thus their keys to be compatible

Defaults aren't aliases; they're defaults. Things that are true about the default might not be true about the actual types present at instantiation. Demo:
```ts
type MyRecord = {
  a: 'A',
  b: 'B',
  c: 'C',
}

// If 'T extends string' can't be violated, then Foo<T> must always be 'good'
type Foo<T> = T extends string ? "good" : "bad";
type MyType<R extends MyRecord = MyRecord, KS extends keyof R = keyof R> = {
  [K in KS]: [
    Foo<K>
  ]
}

type M = MyType<MyRecord & boolean[]>;
declare const m: M;
// Reality: "bad" values present in M
const p: "bad" = m[0][0];
```

**Comment by peterhudec** [comment]
@RyanCavanaugh I see, `MyRecord & boolean[]` satisfies the `extends MyRecord` constraint, but also has the extra numeric keys from `boolean[]`. Makes perfect sense now.
