### ISSUE TITLE
Spread does not infer type for [key: string] object

### ISSUE THREAD

**Issue by zapolnoch** [microsoft/TypeScript#42665]
```ts
type AnyObj = { [key: string]: any; }
const obj: AnyObj = {}

const assing = Object.assign(obj, { foo: 'bar' }) // AnyObj & { foo: string; }

const spread = { ...obj, foo: 'bar' } // {  foo: string; }
```
[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggdiA8gIwFZQLxQN5QNoDWEIAXFAM7ABOAlnAOYC6ZAhggNxQC+AUAMYB7OJSgC0ZeEjSYcvfkJEty5OvRkpUEPsAB0SlfTgAKMagA0OKADMBAsgHJkLKve4BKKAHpPsBBqgAZJY2dhTUqpxygsLAFGBUECwAJjK4OummFiEOTi7cXj641rZklLQMkTxAA)

### 🙁 Actual behavior
Different behavior of Object.assign and spread operator.

**Comment by RyanCavanaugh** [comment]
`Object.assign` doesn't get any special treatment; it's the same as any other userspace function and can only use type syntax that exists.

`{...` is first-class syntax and can get more specific treatment since we actually know what it is.
