### ISSUE TITLE
Variable casting sugar

### ISSUE THREAD

**Issue by alita-moore** [microsoft/TypeScript#42661]
# Suggestion
Double :: casts the type instead of declaring

## 🔍 Search Terms

cast type, variable type declaration

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

declaring variable type with :: casts the variable type

## 📃 Motivating Example
Current
```
// foo is some method that has non-determinant type
const foo: () => string | string[] = () => "foo";
const bar1 = foo(); // type of bar is string | string[]


// for certain use-cases, we may call foo knowing that the type is in fact string in this case
const bar2: string = foo();   // error: Type 'string | string[]' is not assignable to type 'string' ts(2322)
const bar3 = foo() as string; // type of bar is string
```

Proposed Change
```
const foo: () => string | string[] = () => "foo";
const bar:: string = foo()
// type of bar is string
```
## 💻 Use Cases
For backend development, specifically with mongo, it's common to have query methods return either a singular or array of types, and though you may know the actual output is singular, the possibility of non-singular causes issues later in the development pipeline. So it's also common to cast non-determinant types as what they will be. This proposal simply makes the code significantly cleaner. For example,
```
const foo: () => Promise<string | string[]> = async () => "foo";
const bar = (await foo()) as string;
// VS
const bar:: string = await foo()
```

**Comment by RyanCavanaugh** [comment]
We already have two different ways of type asserting; a third that only works in declaration positions like this doesn't seem necessary and the particular sugar here isn't very indicative of what's going on.

**Comment by alita-moore** [comment]
hmm, what about
```
const bar as string = foo()
```
