### ISSUE TITLE
Support event typing declaration in class

### ISSUE THREAD

**Issue by toddwong** [microsoft/TypeScript#42664]
# Suggestion

## 🔍 Search Terms

event

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow declare { event type => handler type } mappings in class. And member methods can refer to these mappings.

```
class EventEmitter {
    addListener(type: @event(type), handler: @event(handler)): this;
    removeListener(type: @event(type), handler: @event(handler)): this;
    on(type: @event(type), handler: @event(handler)): this;
    off(type: @event(type), handler: @event(handler)): this;
    once(type: @event(type), handler: @event(handler)): this;
    protected emit(type: @event(type), ...args: @event(params)): this;
}

class Foo extends EventEmitter {
    @events {
         error: (error: Error)=>void,
         close: ()=>void,
    }
}

```

**Comment by MartinJohns** [comment]
> [x] This could be implemented without emitting different JS based on the types of the expressions
> [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
> [x] This feature would agree with the rest of TypeScript's Design Goals.

You might want to check these points again.

**Comment by toddwong** [comment]
I maybe wrong, but I don't think my suggestion breaks any of these points.

```
class EventEmitter {
    addListener(type: @event(type), handler: @event(handler)): this {
        // implementation
        return this;
    }
    removeListener(type: @event(type), handler: @event(handler)): this {
        // implementation
        return this;
    }
    on(type: @event(type), handler: @event(handler)): this {
        return this.addListener(type, handler);
    }
    off(type: @event(type), handler: @event(handler)): this {
        return this.removeListener(type, handler);
    }
    once(type: @event(type), handler: @event(handler)): this {
        // implementation
        return this;
    }
    protected emit(type: @event(type), ...args: @event(params)): this {
        // implementation
        return this;
    }
}

class Foo extends EventEmitter {
    @events {
         error: (error: Error)=>void,
         close: ()=>void,
    }
}
```

would emit javascript 

```

class EventEmitter {
    addListener(type, handler) {
        // implementation
        return this;
    }
    removeListener(type, handler) {
        // implementation
        return this;
    }
    on(type, handler) {
        return this.addListener(type, handler);
    }
    off(type, handler) {
        return this.removeListener(type, handler);
    }
    once(type, handler) {
        // implementation
        return this;
    }
    protected emit(type, ...args) {
        // implementation
        return this;
    }
}

class Foo extends EventEmitter {
}

```

The typing of methods of Foo will be like

```
addListener(type: 'close', handler: ()=>void): this;
addListener(type: 'error', handler: (error: Error)=>void): this;

removeListener(type: 'close', handler: ()=>void): this;
removeListener(type: 'error', handler: (error: Error)=>void): this;

on(type: 'close', handler: ()=>void): this;
on(type: 'error', handler: (error: Error)=>void): this;

off(type: 'close', handler: ()=>void): this;
off(type: 'error', handler: (error: Error)=>void): this;

once(type: 'close', handler: ()=>void): this;
once(type: 'error', handler: (error: Error)=>void): this;

protected emit(type: 'close'): this;
protected emit(type: 'error', error: Error): this;
```


And if we have a class Bar 


```
class Bar extends Foo {
    @events {
        'data': (data: Buffer)=>void
    }

    getListener(type: @event(type)): @event(handler) {
        // implementation...
    }
}
```

in javascript

```
class Bar extends Foo {
    getListener(type) {
        // implementation...
    }
}
```

And methods of Bar will be 

```
addListener(type: 'close', handler: ()=>void): this;
addListener(type: 'error', handler: (error: Error)=>void): this;
addListener(type: 'data', handler: (data: Buffer)=>void): this;

removeListener(type: 'close', handler: ()=>void): this;
removeListener(type: 'error', handler: (error: Error)=>void): this;
removeListener(type: 'data', handler: (data: Buffer)=>void): this;

on(type: 'close', handler: ()=>void): this;
on(type: 'error', handler: (error: Error)=>void): this;
on(type: 'data', handler: (data: Buffer)=>void): this;

off(type: 'close', handler: ()=>void): this;
off(type: 'error', handler: (error: Error)=>void): this;
off(type: 'data', handler: (data: Buffer)=>void): this;

once(type: 'close', handler: ()=>void): this;
once(type: 'error', handler: (error: Error)=>void): this;
once(type: 'data', handler: (data: Buffer)=>void): this;

protected emit(type: 'close'): this;
protected emit(type: 'error', error: Error): this;
protected emit(type: 'data', data: Buffer): this;

getListener(type: 'close'): ()=>void;
getListener(type: 'error'): (error: Error)=>void;
getListener(type: 'data'): (data: Buffer)=>void;
```

The only effect of these `@events` things are making the typing of events easy.
The keyword `@events` may be not very pretty, Just think that won't conflict with any existing code.

I made some silly mistakes in my origin description, sorry about that.

PS: I'm not profession in language designing. I just think it's a good idea. But if it is not, please feel free to close this.

@MartinJohns

**Comment by alexmorleyfinch** [comment]
Wouldn't a cleaner way of achieving the same thing be to just have a generic handler that receives a single `Event` argument (or maybe and `Event` and an `EventError` argument)? 

Kinda like how JS events currently work. I.E `document.addEventListener(string, (Event) => void)`. Here, `Event` can be a `KeyboardEvent`, a `MouseEvent`, or anything you want. Or in your case, you could have an `ErrorEvent` and a `BufferEvent`.

You might already know this and still be suggesting this change, sorry if that's the case. Just my 2 cents.

@toddwong

**Comment by toddwong** [comment]
@alexmorleyfinch Yes, I knew this. But NodeJS chooses the other way. 

And even for the DOM event handling, we have a lots of `addEventListener`/`removeEventListener` overloads for different type of Event. Look at the lib.dom.d.ts, there are 2 `addEventListener`s and 2 `removeEventListener`s for every event target interface (with the help of the new keyof syntax sugar). 

And much more worse in @types/node, which have dozens of `on`/`off`/`addListener`/`removeListener`/`once`/`prependListener`/`prependOnceListener`.... in every event emitting interface (which, of course, could be simplified a little bit with `keyof` syntax, but would be still too verbosity).
