### ISSUE TITLE
Repeated package.json reads in ts-loader ts api wrapper compared to `tsc --build`

### ISSUE THREAD

**Issue by JasonKleban** [microsoft/TypeScript#42670]
I'm noticing [extreme performance problems](https://github.com/TypeStrong/ts-loader/issues/1245) comparing a `tsc --build` to webpack with ts-loader of the same project.  Sysinternals Process Monitor is showing about 11k file reads from a 1 minute `tsc --build` and nearly 10x ReadFile events through ts-loader, with matchingly awful CPU and memory work before an ultimately successful build hours later.   I am pursuing this as a ts-loader optimization problem, but I'm not sure if the ts api gives enough control to succeed.

https://github.com/microsoft/TypeScript/blob/d36df0dda5589d8bb4c8c16a946660000d2f6dfc/src/compiler/moduleNameResolver.ts#L963-L966

Perhaps it's exactly what it needs to do, but this `/*considerPackageJson*/ true` here is causing repeated reads/parsing of package.json files from dependencies _in a row_.  I can override the injected `readFile()` and possibly avoid the read with a cache, but I don't think we can avoid the json parse because that is done internal to typescript.

![image](https://user-images.githubusercontent.com/17498172/107094359-dfc6af80-67d4-11eb-930e-c18f0c4ffc41.png)

![image](https://user-images.githubusercontent.com/17498172/107095234-6760ee00-67d6-11eb-89eb-e1d4137f9e7c.png)

Common dependencies with many internal .d.ts files are costing 6000+ read/parse of their package.json files in a run, with a long tail down to single reads.

Here is the call to `compiler.resolveModuleName()`

https://github.com/TypeStrong/ts-loader/blob/b8a70f91aa4a450603342e62b8c03bdd09c7a979/src/servicesHost.ts#L1175-L1199

Here is the injected readFile that is called back to read the contents of many package.json again and again, with each relative path import of a .d.ts file within its library:

https://github.com/TypeStrong/ts-loader/blob/b8a70f91aa4a450603342e62b8c03bdd09c7a979/src/servicesHost.ts#L96-L104

Once the packageJsonInfo is extracted, I suspect additional waste but one step at a time.

CC @sheetalkamat

**Comment by JasonKleban** [comment]
@sheetalkamat @RyanCavanaugh I created a self-contained repro for demonstrating this behavior here:  https://github.com/JasonKleban/practices-2021

**Comment by JasonKleban** [comment]
When comparing the output of traceResolutions: true between the two build methods of the linked sample repo, tsc has 898 lines of output while the webpack version generates 6201 lines.  Here is the first significant divergence and it may contain a clue?

![image](https://user-images.githubusercontent.com/17498172/108397080-99664d00-71e5-11eb-962a-f234df56a2d6.png)

**Comment by sheetalkamat** [comment]
This is a multi repo issue and i suggest we fix this with:
1. Module resolution to cache `readJson` as well as `getPackageJsonInfo` and handle those things. Need to see when and which kind of invalidation should happen in watch and tsserver mode.
2. ts-loader could use module resolution cache that gets cleared like its other cache. 
3. API in typescript to provide a way for ts-loader to use efficient module resolution cache we have in ts build state where if module resolution options dont change the module resolution cache is reused.

**Comment by sheetalkamat** [comment]
@JasonKleban  i have PR #43700 and TypeStrong/ts-loader#1287 which i verified with your sample repro. 
Can you check if the builds from these two help with your scenario and report. Thanks
