### ISSUE TITLE
Private properties make class instance types incompatible

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#42683]
```
Return type of constructor signature must be assignable to the instance type of the class. ts(2409)
```
```ts
class A {
}
class B {
    constructor() {
        return new A(); // no error
    }
}
class C {
    #foo = 0;
    constructor() {
        return new A(); // Property '#foo' is missing in type 'A' but required in type 'C'.
    }
}
class D {
    private foo = 0;
    constructor() {
        return new A(); // Property 'foo' is missing in type 'A' but required in type 'D'.
    }
}
```

Expected at least `C`, if not also `D` to not throw errors as private properties can only be used within a same class

**Comment by MartinJohns** [comment]
You forgot to fill out the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md).

---

The error message is quite clear and shows that this is intentional. The type you return must be assignable to the instance type, but `A` is not assignable to neither `C` nor `D` (due to the private field).

If this wouldn't be the case you could easily run into bugs, for example:

    class A {
        getValue() { return "unexpected" };
    }
    class B {
        constructor() {
            return new A(); // no error
        }
    }
    class C {
        #foo = 0;
        constructor() {
            // @ts-ignore
            return new A();
        }

        getValue() { return this.#foo };
    }
    class D {
        private foo = 0;
        constructor() {
            // @ts-ignore
            return new A();
        }

        getValue() { return this.foo };
    }

    const c: C = new C();
    const d: D = new D();

    console.log(c.getValue()); // Expected type is number, but returns string.
    console.log(d.getValue()) // Expected type is number, but returns string.;

**Comment by pushkine** [comment]
@MartinJohns your example produces an error as intended
```
Return type of constructor signature must be assignable to the instance type of the class.
Type 'A' is not assignable to type 'C'. The types returned by 'getValue()' are incompatible between these types. 
Type 'string' is not assignable to type 'number'.
```

**Comment by NoDocCat** [comment]
Maybe we should point out that the error lies in `getValue`.
Because private types are invisible to the outside world, the implementation of private types has no external influence.
In the example, the external influence should be `getValue return type`.

**Comment by NoDocCat** [comment]
Maintain interface compatibility should only verify public.

**Comment by NoDocCat** [comment]
Maybe my example can better illustrate the problem:

I want to custom event like this:
```ts
export class NetworkEvent extends Event {
  private readonly _target: NetworkInformation;

  get target(): NetworkInformation {
    return this._target;
  }

  constructor(type: string, target: NetworkInformation) {
    super(type);
    this._target = target;
  }
}
```

When I use NetworkEvent to replace Event, I will get:
```
Type 'Event' is missing the following properties from type 'NetworkEvent': _target
```

**Comment by RyanCavanaugh** [comment]
These are correct errors because a class can access the private members of another instance of the same class.

**Comment by thetutlage** [comment]
Well, there is an issue with this. Let me share another example.

```ts
class UrlBuilder {
    #params: any
    params() {
        return
    }
}

class RedirectRequest {
    #scopes: any
    params() {
        return
    }

    scopes() {
        return this.#scopes
    }
}

class MakeUrl {
    constructor(builder: UrlBuilder) {
    }
}

new MakeUrl(new RedirectRequest())
```

The `RedirectRequest` should be allowed in place of `UrlBuilder`, because `#params` is a private property the `MakeUrl` class will never be able to access.

Lemme know if should open another issue for this

**Comment by MartinJohns** [comment]
> Lemme know if should open another issue for this.

You shouldn't, because this is working as intended. If you want to be able to pass both classes you should just create a common interface and use that.

**Comment by AlexanderOMara** [comment]
I'd say most classes don't needs to directly access the private properties of another class though.

Perhaps an option to mark properties internal could be added to prevent irrelevant type compatibility issues?
