### ISSUE TITLE
[key:number] accepts a string type variable `x` which might not satisfy `isNaN(Number(x)`

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#42686]
# Bug Report

### 🔎 Search Terms

Generic Properties

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because unlikely to have changed

### ⏯ Playground Link

[Playground link with relevant code]()

### 💻 Code

```ts
{
  type NumKeyObj = {
    [key:number]:any
  }
  const letterstr='a'
  const numberstr='1'
  { const x:NumKeyObj = { 'a':1 } } // not allowed - as expected
  { const x:NumKeyObj = { [letterstr]:1 } } // not allowed - as expected
  { const x:NumKeyObj = { '1':1 } } // allowed 
  { const x:NumKeyObj = { [numberstr]:1 } } // allowed

  // n is 0 or Infinity, (once in a never blue moon something else)
  const n=(0.5+Math.random())**100000  
  const r=n.toString()
  const s:string|number= (r==='0')?'a':1 // fifty-fifty
  
  { const x:NumKeyObj = { [n]:1 } } // allowed  
  { const x:NumKeyObj = { ['Infinity']:1 } } // allowed  
  { const x:NumKeyObj = { [r]:1 } } // allowed --- smart compiler?  
  { const x:NumKeyObj = { [s]:1 } } // <--- UNEXPECTEDLY ALLOWED
}
{
  // for comparison
  type Test=number
  const s:string|number= (Math.random()<0.5)?'a':1
  const t:Test = s;  // not allowed, as expected
}
```

### 🙁 Actual behavior
```
  const n=(0.5+Math.random())**100000  
  const r=n.toString()
  const s:string|number= (r==='0')?'a':1 // fifty-fifty
  { const x:NumKeyObj = { [s]:1 } } // <--- UNEXPECTEDLY ALLOWED
```

### 🙂 Expected behavior
```
  { const x:NumKeyObj = { [s]:1 } } // <--- should not allow
```
should fail compile, similar to the following:
```
{
  // for comparison
  type Test=number
  const s:string|number= (Math.random()<0.5)?'a':1
  const t:Test = s;  // not allowed, as expected
}
```

**Comment by RyanCavanaugh** [comment]
`{ [k: number]: T }` doesn't mean an object with only numeric keys. It means an object whose lookups at numerically-named keys have type `T`.

What you're seeing is the rules for excess properties, which are intentionally rather lenient around computed keys.

**Comment by craigphicks** [comment]
@RyanCavanaugh Thanks very much for your reply.  

I will note here for the record what I determined upon further investigation after your helpful reply.

---

Your first paragraph:

> { [k: number]: T } doesn't mean an object with only numeric keys. It means an object whose lookups at numerically-named keys have type T.

Here *numeric keys* means any number, and *numerically-named keys" means all the strings `s` that pass
`!isNaN(Number(s))`.  That is correct and  demonstrated in the examples provided in the original post:
```
  const numberstr='1'
{ const x:NumKeyObj = { [numberstr]:1 } } // allowed

  const n=(0.5+Math.random())**100000  
  const r=n.toString()
  { const x:NumKeyObj = { ['Infinity']:1 } } // allowed  
  { const x:NumKeyObj = { [r]:1 } } // allowed --- smart compiler?  
  { const x:NumKeyObj = { ['a']:1 } } // not allowed 
```
---

Your second paragraph is independent statement from your first paragraph.  Your second paragraph is: 

> What you're seeing is the rules for excess properties, which are intentionally rather lenient around computed keys.

Here is detailed hypothesis of what is going on: 

 - Given the constraint `type KN={[key:number]:any}` then for the statement `const a:KN={[s]:/*any value*/}` the following rules are applied (in this or equivalent order)  
   1.   If it is known for certain that `s` satisfies the constraint then it is accepted.
   2.   If it is known for certain that `s` doesn't satisfy the constraint then it is rejected.
   3. Otherwise is it not known for certain due to type-computation complexity limit or being unknowable until runtime.  In that case it relies on declared type.
      1.  If the declared types includes `any` then it is accepted (even if any is or'ed with unacceptable types) 
      2. If the declared  type is any OR combination of 'string', 'number', 'symbol' then it is accepted
      3. Otherwise it is rejected.  (here it follows that `any` is not included and some type other than `symbol', 'number', string' is included).    

The hypothesis doesn't cover deep-types (tree of unions and intersections).  It is based on the following examples, some of which were not in the original post:
```
   type NumKeyObj = {
    [key:number]:any
  }
 const n=(0.5+Math.random())**100000  
  const r=n.toString()
  const s2:string|number|symbol= (r==='0')?'a':(r==='1')?Symbol():1 // fifty-fifty
  const s3:string|number|symbol|bigint= (r==='0')?'a':(r==='1')?Symbol():(r==='1.1')?1n:1
  const s4:bigint|string|number|symbol|any= (r==='0')?'a':(r==='1')?Symbol():(r==='1.1')?1n:1
  const s5:bigint|any= (r==='0')?'a':(r==='1')?Symbol():(r==='1.1')?1n:1
  const s6:string= (r==='0')?'a':'b'
  
  { const x:NumKeyObj = { [s2]:1 } } 
  { const x:NumKeyObj = { [s3]:1 } } // NOT ALLOWED  
      // (up) 'A computed property name must be of type 'string', 'number', 'symbol', or 'any'.ts(2464)'
  { const x:NumKeyObj = { [s4]:1 } } 
  { const x:NumKeyObj = { [s5]:1 } } 
  { const x:NumKeyObj = { [s6]:1 } } 
```
The only `s*` variable not accepted is `s3`, because it contains `bigint` (which is not a valid index type) and doesn't contain `any`. 

 I also have a hypothesis about the Modus Operandi

1. Provide `[key:number]` key type checking for literal declarations of number keys (a frequent case).
2. Allow non-literal values used as index values whose type includes `any` a way to prevent type checking from getting in the way of index value coding.   
3. Provide uniform sanity checking for all non-literal values used as index values - if not `any` then they must be any combination of `string`, `number`, or `symbol`.   
4. That's enough.

**It follows there is no need for specific processing for non-literal  values used as index values which are subject  index subtype constraints, e.g.. `{[key:number]:any}` or `{[key:number]:never}`.  (And there is none).**

**Comment by craigphicks** [comment]
I feel it would be negligent not to add a statement about default practical expectations:

**Use of key subtype constraints such as `{[key:number]:any}` or `{[key:number]:never}` would in practice imply that the keys of the properties actually meet those constraints.**

That's may seem too obvious to state, but sometimes obvious things become obscured by technical details, i.e., the conclusion that Typescript need not check non-literal key values.  That 'need not' statement is only saying it is such a low priority that it will never ever be done.  It is **NOT** saying that key values disobeying the constraints are actually acceptable by default.
