### ISSUE TITLE
Override JSDoc for re-exported types / enum / classes / interfaces

### ISSUE THREAD

**Issue by plohoj** [microsoft/TypeScript#42684]
# Suggestion

## 🔍 Search Terms

* Override JSDoc
* JSDoc for re-export

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add the ability to define / override documentation(JSDoc) for re-exported types / enum / classes / interfaces, etc.

## 📃 Motivating Example

In the case when the library developer decided to change the name of the type / enum / class / interface, etc., it would be useful to have two copies of the declaration with different names and the old name would be marked as @deprecated.
This refactoring practice is adopted for class methods, when a new method is created and the body of the old method is transferred into it, and a call to the new method is placed in the old method. The old method is then marked as @deprecated so that the library user has time to replace the name of the called method.

## 💻 Use Cases

An example of overriding JSDoc to mark a enum / interface as deprecated

```ts
// file: core/newFeature.ts
/** Some enum description **/
export enum NewFeatureEnum {
    // ...
}
/** Some interface description **/
export enum INewFeature<T extends NewFeatureEnum> {
    // ...
}

// file: index.ts
export {
  NewFeatureEnum,
  /** @deprecated use NewFeatureEnum */
  NewFeatureEnum as OldFeatureEnum,
  INewFeature,
  /** @deprecated use INewFeature */
  INewFeature as IOldFeature,
  // ...
} from 'core/newFeature';
```
At the moment, the JSDoc comment added to the re-export construct will not affect the final result in any way

**Comment by starball5** [comment]
Is it supposed to be the case that _imports_ of the re-export don't show the overridden JSDoc, but only show the original export's JSDoc with any additional `@deprecated` tag from the re-export? Note that the site of the re-export itself _does_ show the overridden JSDoc.

**Comment by sandersn** [comment]
@starball5 it would be better to open a new bug for this (and it does sound buggy).

**Comment by starball5** [comment]
> @starball5 it would be better to open a new bug for this (and it does sound buggy).

Done: #53960
