### ISSUE TITLE
When a `unknown` variable is narrowed to a specific type, assigning another value with the same type resets the first back to `unknown`

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#42687]
# Bug Report

### 🔎 Search Terms

unknown, number, assign

### 🕗 Version & Regression Information

On the playground this behavior goes back to at least 3.3.3333
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unknown
- I was unable to test this on prior versions because there is no earlier version on the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta&ssl=1&ssc=1&pln=8&pc=2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwygGsQBnAOWQFsAjEGACgDcoJkQAueVaumASi5McWYAG4AUBJTpseAmQzNW7LmiKocAd1T94Abwnx4WRPAYYAngAcQOMyzYIAhAF5X8AEQ9a9T3rgMZBhUSWNCEgpeemUnfjF4AHpE+BwiI3hHdngPAEYE5PgoUlIsAHN8DAALBFIoKgQrW2cMiLJKX0YskHiklPoYHBhzbpNSeHVNHQAaIohqnGQyqvgtBFRYQbXgEwwCHG5o4bpEIZ6JAF8gA)

### 💻 Code

```ts
declare function takesNumber(value: number): void;

function test(value: unknown) {
  if (typeof value !== "number") return;
  takesNumber(value); // ok
  value = 1; // assign the same type!
  takesNumber(value); // error (value is unknown, although we narrowed it to number before)
}
```

### 🙁 Actual behavior

value is `unknown` after the assignment

### 🙂 Expected behavior

value should still be `number`

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/27706#issuecomment-434420073, https://github.com/microsoft/TypeScript/issues/16976#issuecomment-313465982

**Comment by AlCalzone** [comment]
Huh, seems like this is an exact duplicate of #27706. Man, `unknown` is really still awkward.
