### ISSUE TITLE
Function expression / Function declaration different behavior when narrowing types

### ISSUE THREAD

**Issue by gjuchault** [microsoft/TypeScript#42694]
# Bug Report

### 🔎 Search Terms

Function variable expression declaration narrowing discriminating type

### 🕗 Version & Regression Information

The behavior seems to be present in every version I tried, at least 3.3.3+ (tested on [playground](https://www.typescriptlang.org/play)], and up until nightly.

The issue is a different behavior between function declaration and function expression (« function form » or « variable form »). It seems somehow related to https://github.com/microsoft/TypeScript/pull/18654.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.1.3#code/JYOwLgpgTgZghgYwgAgGIFcQLMA9iABSlwAdocIBnAHgBUA+ZAbwChl3lLcBbCAWQhgAFrgAmACgjhgYAJ4AuZLQCUi2gG4WAXxYtQkWIhQA1OFGBwARgBsIRUuWBU6jVh049+gkaMWTpcmrKyAC8jBraunJkyABy6NyW0ACiAbKhzMgA1qC+yABEIAlJUPnqyKJwYHCKRYnQyDrRKADKYOYgAOapOHIZTNm5ivmU7aCdZRVVNZxjXY1RsjE9MukhccUpacgAPshtHd1pmiwI+KPIMCSKGFg4+PZkUBQ0K3KM624cXLwCwmLiGC4XCKeL1KBvWTBL7udhQQToKAgS7AzTuHQ6U7nMDIABu12QpnMVlsj0czkhH2YbG+nj+PkBwNBmwhaWhNNhyHhYERyKBuDRHAxQA

### 💻 Code

```
interface FunctionProperties<T> {
    someMethod(entity: T): T;
}

interface VariableProperties<T> {
    someMethod: (entity: T) => T;
}

type NumberEntity = { kind: "number"; data: number }
type StringEntity = { kind: "string"; data: string }

type Entity = NumberEntity | StringEntity;

const fp: FunctionProperties<Entity> = {
    someMethod(foo: NumberEntity) {
        return foo;
    }
}

const vp: VariableProperties<Entity> = {
    someMethod(foo: NumberEntity) {
        return foo;
    }
}
```

### 🙁 Actual behavior

The following error appears on `vp`:

```
Type '(foo: NumberEntity) => NumberEntity' is not assignable to type '(entity: Entity) => Entity'.
  Types of parameters 'foo' and 'entity' are incompatible.
    Type 'Entity' is not assignable to type 'NumberEntity'.
      Type 'StringEntity' is not assignable to type 'NumberEntity'.
        Types of property 'kind' are incompatible.
          Type '"string"' is not assignable to type '"number"'.(2322)
input.tsx(6, 5): The expected type comes from property 'someMethod' which is declared here on type 'VariableProperties<Entity>'
```

This error can be removed by disabling `strictFunctionTypes` (hence the Github issue I linked above), which makes sense

It does not appears on `fp`

### 🙂 Expected behavior

It should happen on `fp` as well

**Comment by MartinJohns** [comment]
[Why are function parameters bivariant?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)

Member methods are contravariant, function parameters are covariant (or was it the other way around?).

This is working as intended.

**Comment by gjuchault** [comment]
@MartinJohns Thanks for the quick answer.

Two things I'm not sure to get after reading multiple times the link you shared:
- (in the example): are `Dog` and `Animal` two conflicting types? I think that should be the question the compiler should answer before answering `Is Dog[] a subtype of Animal[]? Should Dog[] be a subtype of Animal[] in TypeScript?` If they aren't (let's say Dog extends animal), then I guess indeed, it could be okay to fill a function expecting an Animal with a Dog
- (in this example): It seems to me that the issue's example is a bit different: I'm not asking for the common entity (`Animal`), I'm specifically asking the Number entity (`Dog` or `Cat`). I would assume that the example on the link you shared would also give an error if the callback method was expecting a Cat and given a Dog (two specific types).
- (more generally): may you explain what causes the difference of the compiler behavior depending on the function declaration or expression?
