### ISSUE TITLE
Remove the need for curly brackets surrounding destructured parameter in high order function passed to Array#map

### ISSUE THREAD

**Issue by giluis** [microsoft/TypeScript#42695]
# Suggestion
Remove the need for curly brackets surrounding destructured parameter in high order function passed to Array#map
## 🔍 Search Terms

high order array methods map foreach destructure tuple remove parentheses

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When calling high order array methods (`Array#map`, for example), sometimes (most of the time for me) we only need to access the current element of the array and have no need to access the index or the whole array (2nd and 3rd parameters on the function that is provided to map). 
When accessing only the current element in the array, one can leave out the parentheses that surround the parameter in the function. E.g:

```typescript
let arr = [1,2,3,4,5];
//with 3 parameters, curved braces are needed. Makes sense
arr.map((cur,i,arr)=>/* return something */)

//with 1 parameter, curved braces are optional. Makes sense
arr.map(cur=>/* return something */)
```

However, if this is an array of tuples and we destructure the current element,
typescript forces the parameter to be surrounded by brackets. 
In my view, this is unnecessary and removing it would allow code to be more readable
```typescript
let arr:[number,number][] = [[1,2],[3,4],[4,5],[6,7]];
//current behaviour
arr.map(([n1,n2])=>/* return something */)

//suggested behaviour
arr.map([n1,n2]=>/* return something */)
```

I suggest applying this only to tuples and arrays.
I say this because objects might cause problems because of the curly brackets,
which are needed for destructuring.
 
## 📃 Motivating Example

Using Array#map I was iterating through an array of tuples, performing an operation between the first element and the second and returning the result.
```typescript
tupleArr.map(([t1,t2])=>/* return somevalue */)
``` 
I noticed that the ( ) around the destructured parameter were unecessary (in terms of readability).
Removing them seems intuitive and natural.
## 💻 Use Cases

I think the code would be more readable if the parentheses were not obligatory to surround the destructured parameter.

So imo, ideally:
```typescript 
arr.map([a,b]=>/*do something*/);
```

Using the curly brackets is ok, but I think this a small improvement that would make people's lives beter.

Thank you for your time, if anything in this issue is inadequate, pls let me know. This is the first issue I submit on github, so I would love feedback.

**Comment by MartinJohns** [comment]
That wouldn't be valid JavaScript anymore. So TypeScript would have to emit different JS, which (I'm pretty sure of it) is out of scope for TypeScript.

**Comment by RyanCavanaugh** [comment]
I have no idea why
```js
const f = [a, b] => a;
```
wasn't made legal when they added parameter destructuring to JS, but I have to assume there were reasons (a brief search and pinging a few people didn't turn anything up). Either way, this sort of change should be taken to TC39.
