### ISSUE TITLE
Functions allowed in weird cases where an indexer signature is expected, where functions don't have one.

### ISSUE THREAD

**Issue by benlesh** [microsoft/TypeScript#42708]
# Bug Report

Looking for a workaround or an explanation, really. But it _seems_ like a bug?

### 🔎 Search Terms

- arraylike
- index
- function

### 🕗 Version & Regression Information

This is the behavior in every version I've tried. 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJSnAngGWAawgB4AVAPmQG8BYAKGQeSgjgBMB7EAGy2S4hABzMAAsAXMhABXALYAjaAG46jJiw7deAbRATp86AF0JJZbQC+dOjCkgEYYJ2SQAzmABCpMgAo4UQRLomLgExOQAlFTIlrR0APRxyADiAPIpACISAKIY7FAuyCLQKHAFEAAeAA4Q9hCsAHTIAESgrBXILsCCIHBgUszIwAUyQ51CTfV0rh7e3pEAvBSU5uFm1rb2jiDOEG6ovv6BGNh4hERwIFhkkctWtAnI7qiZyABy7MjQUHkFRcwA-MgSEVBiA2uUOl0en0BkMOg4uFxkCMXGNBAAaZwidhSQQiSa0ab7ObIRZUFZrWhAA)

### 💻 Code

```ts
interface ArrayLike<T> {
    readonly length: number;
    readonly [n: number]: T;
}

function testB<T>(arg: ArrayLike<T>) { }

// GOOD: Errors here as expected. "index signature is missing".
testB(() => {});

function testA(arg: ArrayLike<any>) {}

// BAD: No errors here? The index signature is still missing, though.
testA(() => {});
```

### 🙁 Actual behavior

`testA` allows a developer to pass a function where we didn't intend them to be able to pass a function.

In some (much more complicated) cases in RxJS this becomes an unintuitive footgun. 

### 🙂 Expected behavior

I'd expect that `testA` would error with the same error that `testB` errors with. Functions don't have indexers in their signatures.

Related to: 
- https://github.com/ReactiveX/rxjs/issues/6011
- https://github.com/ReactiveX/rxjs/issues/4563

**Comment by RyanCavanaugh** [comment]
This came up on the bird website the other day: https://twitter.com/OliverJAsh/status/1357374631938830337

`ArrayLike<unknown`> would be a better type at `testA`
