### ISSUE TITLE
Assertion function unable to narrow type if `truthy` condition contains `!` or `=== false`

### ISSUE THREAD

**Issue by ericxjohnston** [microsoft/TypeScript#42707]
# Bug Report

Assertion function is unable to narrow type if the `truthy` condition contains `!` or `=== false`.

### 🔎 Search Terms

`assertion function`, `narrow type`, `CFA`, `truthy condition`

### 🕗 Version & Regression Information

Typescript v4.1.3
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Type Guards](https://github.com/Microsoft/TypeScript/wiki/FAQ#type-guards) and read the [v3.7 release documentation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) and [original pull request](https://github.com/microsoft/TypeScript/pull/32695).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhhCBTATlAXDAFKMATASygPEwFcwBrMEAdzAEoYBeAPnkVSghl0OPAtsAKBi9w-EmAA0wpmxgBvUTAIAzbAEI+RKU2VixUABYo6MMElowAoijMosKwzAAGNgB4AHJMChI8GAByHQEwIJgoEBgAIyRIlDITAE9pWKSYFF8kAgA3AJgAEkVQqQBfV1kXMQYAbhUy4TL64QAbJFgPAEZMMDIAWziUGAAfCzJW1tGYCjwkNQJLPHr2zoAmXoGh6b7J6dn5xYCVjpgPAGZNwdQdiamxg4Wlk86AFivtsd37mfxD57apw8AFYPjcvnd9n8nsdAZ0AGxg4YQvYPaFHZZws4AdiRt1RvzmMMxqzOAA48Sifo8MS8zgBOSnjAk0gHCBDINBYKDJHwgDTdFjMZjBPrXFBBJgAeil4nsvigrWSFjg9joPB5Pki0TFQ3ZnC5mqQ-LOaxgmmFoq2qElMBlcqyfiVKrVtA1vPiUWZ1PRS31nKgWE03I9JouQpFQV1NoY0tloHlTuVYFVZjdkQ92u9UKJGP9XCwIb5AteEat4ttwpFajgrWQcZgxgQFmi8zUCuE+a5ILL31GYx7VcJ-wCDYTjsVydT6ozWq9fbRub9HILHnh5stfYAZFuzuuLSLWaO7fGQInJy60+65zrrSgu4Hgx5sb3ISMBy+h0e8LGT43mzQMBth2K5clgHhkq+qIDpBX6+seQ41nWSANk2PCAcBfiduo2AePSUH3AO+FwUux6KH+44Ks6Kautenq3uKziRKY5iWNYdgOFgdRNJ23S1H+0b3h4az8faC7DsSwgXKJsrid+UmvDJLZAWo7Z+DA7DQAQeyCfiPqkXgvHAkpcnwYZa4mXeUnYiZraqQqGkwFpOl3npOYjuZZK2SpamwJpxAueKbmLh5vH0pZjFAA)

### 💻 Code

```ts
const assert: (condition: unknown) => asserts condition = (
  condition,
) => {
  if (!condition) {
    throw new Error(
      `Expected 'condition' to be truthy, but received ${condition}`,
      );
  }
};

let x1: number | null | undefined;
let x2: number | null | undefined;
let x3: number | null | undefined;
let x4: number | null | undefined;
let x5: number | null | undefined;
let x6: number | null | undefined;
let x7: number | null | undefined;
let x8: number | null | undefined;
let x9: number | null | undefined;

assert(typeof x1 === 'number') // correctly narrows type to number
assert(typeof x2 !== 'number') // correctly narrows type to null | undefined
assert(!(typeof x3 === 'number')) // correctly narrows type to null | undefined
assert((typeof x4 === 'number') === false) // has no effect

assert(x5 === null || x5 === undefined) // correctly narrows type to null | undefined
assert(x6 !== null && x6 !== undefined) // correctly narrows type to number
assert(!(x7 === null || x7 === undefined)) // has no effect
assert((x8 === null || x8 === undefined) === false) // has no effect

if (x9 === null || x9 === undefined) { // correctly narrows type to number
    throw new Error();
}

x1; // number
x2; // null | undefined
x3; // null | undefined
x4; // no effect > still number | null | undefined

x5; // null | undefined
x6; // number
x7; // no effect > still number | null | undefined
x8; // no effect > still number | null | undefined

x9; // number

```

### 🙁 Actual behavior

Variable types for `x4`, `x7`, and `x8` are unaffected by the assertion function.

### 🙂 Expected behavior

Expected the types to be narrowed.

### Use case

I'm converting a large number of `if (truthy) { throw }` type guards to use assertion functions instead for improved code reuse and readability but in the the process I need to flip the condition from "throw when truthy" to "throw when falsy" to satisfy the assertion function truthy constraint.

The simplest change was to just add the `!` or `=== false` condition as part of the change to assertion functions but this doesn't seem to effect the control flow analysis (CFA) for these variables the same way the inline "throw when truthy" code does.

I've read through all of the documentation that I can find on assertion functions and I haven't been able to find any discussion on this or other limitations with the assertion function truthy expression condition CFA analysis. The closest comment that I've been able to find is [this one from Anders Hejlsberg](https://github.com/microsoft/TypeScript/pull/32695#issuecomment-517935342) in original PR saying that the truthy condition reflects full effects of the logical expression.
> No, because the two are not equivalent. asserts x reflects the full effects of a logical expression when x is truthy, similar to an equivalent if statement. assert x is true simply narrows the type of a variable passed for x, similar to the effects of passing x to an equivalent user defined type predicate function.

Additional note, the above code is a simplified example to illustrate the `asserts condition` truthy  issue. For reference, this example can be rewritten to avoid the truthy condition issue by using the `asserts value is NonNullable<T>` assertion format instead.

**Comment by RyanCavanaugh** [comment]
Narrowing works by forming a control flow graph of things that might affect a variable's type, and checking those things to see if they're syntactic forms that look like they might cause something to be narrowed. It is *not* a constraint-solver style thing that can handle all kinds of other combinations and permutations of logical operators.

We pay a performance cost checking for every recognized syntactic form and constructs like `foo((a === b) === false)` aren't common enough to merit inclusion in that list.

**Comment by ericxjohnston** [comment]
Makes sense. Thanks Ryan.
