### ISSUE TITLE
ReferenceError: NAMESPACE is not defined

### ISSUE THREAD

**Issue by ionutcirja** [microsoft/TypeScript#42704]
# Bug Report

I have declared a global namespace in a typings.d.ts file like this:

```ts
declare namespace NAMESPACE {
  export enum Colours {
    GREEN = 'GREEN',
    AMBER = 'AMBER',
    RED = 'RED',
  }

  export type User = {
    name: string;
  }
}
```

My tsconfig looks like this:

```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src",
    "./global.d.ts",
    "./typings.d.ts"
  ]
}
```

When I'm trying to access the enum I defined in my namespace, I'm getting a runtime error saying: Typescript ReferenceError: NAMESCAPE is not defined. This applies just to enums as everything is alright with the types I'm exporting via the same namespace.

Ex.

```
if (colour === NAMESPACE.Colours.GREEN)) {...} // Typescript ReferenceError: NAMESCAPE is not defined
```

### 🕗 Version & Regression Information

I had this bug in version 3.9.2, updated to 4.1.3 and it is still there.

### 🙁 Actual behavior

When I'm trying to access the enum I defined in my namespace, I'm getting a runtime error saying: Typescript ReferenceError: NAMESCAPE is not defined.

### 🙂 Expected behavior

Should be able to access an enum via a namespace.

**Comment by MartinJohns** [comment]
A `.d.ts` file provides typings for existing JavaScript code. In itself it won't create objects at runtime. You just said *"there exists an object named `NAMESPACE`"*, but at runtime you get an error that says *"no object named `NAMESPACE` exists"*.

**Someone** needs to provide this object for your definition.

**Comment by ionutcirja** [comment]
> A `.d.ts` file provides typings for existing JavaScript code. In itself it won't create objects at runtime. You just said _"there exists an object named `NAMESPACE`"_, but at runtime you get an error that says _"no object named `NAMESPACE` exists"_.
> 
> **Someone** needs to provide this object for your definition.

So I assume I should actually define this enum in another file and import it.
It looks like that's not a bug, so I will close it.
Thanks for the advice.

**Comment by MartinJohns** [comment]
> So I assume I should actually define this enum in another file and import it.

This would be the case if you declare it in a `.ts` file.
