### ISSUE TITLE
"Infer function return type" is annoyingly suggested in function bodies

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#42714]
```ts
function foo() {
    let x = 123;
    return x;
}
```

If your cursor is *anywhere* in the body of this function, you will get a code action to "Infer function return type".

This is annoying because it always provides a lightbulb in the editor

![image](https://user-images.githubusercontent.com/972891/107415473-43e4be80-6ac8-11eb-8399-d6ddee7a6e21.png)

and that is doubly-annoying in cases where you think you have a quick fix but it ends up being the same useless code action.

![image](https://user-images.githubusercontent.com/972891/107415561-5fe86000-6ac8-11eb-81d4-a55434b59d2a.png)

I'm not exactly sure what the right way is to surface this refactoring in a way that's not intrusive. Maybe by only providing it on `return` statements and the function signature itself? Thoughts @jessetrinity @sandersn?

**Comment by jessetrinity** [comment]
@DanielRosenwasser return statement and signature sound like the right places.

**Comment by sandersn** [comment]
I agree -- and I'm not even sure about return statements.

**Comment by a-tarasyuk** [comment]
> and I'm not even sure about return statements.

I'm also not sure about return statements...

**Comment by jessetrinity** [comment]
Why not return statements? 😕

**Comment by sandersn** [comment]
The new code will be inserted on the function declaration, which can be far away from the return statement. Not a big deal, but it makes more sense for me to see a light bulb near to where the new code will be inserted.
