### ISSUE TITLE
Updated TypeScript for VS2015 removes JavaScript support

### ISSUE THREAD

**Issue by YuryStrozhevsky** [Microsoft/TypeScript#4271]
After installation of latest TypeScript update on VS2015 Comunity Edition I found that support for JS was removed. There is no "JavaScript" branch in "Configuration / Text Editor" and VS does not recognize JS syntax. However, Node.js Tools do recognize JS files, but I think it is a separate tool. 
S
o, because of the bug I need to completelly remove VS2015 and then try to make "cleare installation" again. Nothing helps: system restore point does not help, VS repair does not help, uninstallation of TypeScript from the system does not help. I will loose whole day making my system working again!

**Comment by DickvdBrink** [comment]
Duplicatie of https://github.com/Microsoft/TypeScript/issues/4238?

**Comment by YuryStrozhevsky** [comment]
Yes, the duplicate.
