### ISSUE TITLE
Type inference issue with interface and class methods

### ISSUE THREAD

**Issue by HyunnoH** [microsoft/TypeScript#42729]
# Bug Report

### 🕗 Version & Regression Information

- Tested in 4.1.2, 4.1.3 and 4.2.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1&ts=4.2.0-dev.20210207#code/JYOwLgpgTgZghgYwgAgMoHsEGsKQCYCSkAtsgN4BQy1yoAzmHADZMBKAriAO7pR4AUUTjz4AuZADFeYYGHZ4IASnEAFKOmLA6EADwAjdOiYQ4IAHwUAvhQqhIsRCilQZcheSo0ITcQyigAcwBuT2o6I18wfxBg0OQ8COQQdmI9aBCaZCZ0cQMjExAQ61twaHgkZABxCGI6D0zvSOjYzPCfZD9AjJoE9uTU9KsbBCY4OjqAQSgEAAtTFVHIWmIAB2NiCHA6jGxcCEISepoxgE8QBFoQBmY2YV4BIW578WraxUpMzKhcdigQZHgTG0cWsxRAEC4yCms3miwg-EUADp6IwWBwnnx+B8vO0AOTeXEAGjibXEuLaRLivXEAEZiZlsuJAcDLIogA)

### 💻 Code

```ts
interface SocketedItem {
    installRunword(runword: Fortitude): Promise<boolean>
}

interface Fortitude {
    el: string;
    sol: string;
    dol: number;
    lo: boolean;
}

interface Gems {
    el: string;
    sol: string;
    dol: number;
}

class ArchanPlate implements SocketedItem {
// expected this line should have error
    async installRunword(runword: Gems){
        return false
    }
}

new ArchanPlate().installRunword({
    el: 'el',
    sol: 'sol',
    dol: 1,
// But this line makes an error.
    lo: false
})
```

### 🙁 Actual behavior

The method `installRunword` doesn't make an error although interface `Gems` don't have property `lo` which is declared in `Fortitude`.  And also, call of `installRunword` makes an error because `lo` isn't in `Gems` type.

### 🙂 Expected behavior

`installRunword` in class definition should make an error because `Gems` type doesn't have `lo` property but requires in `Fortitude` type.

**Comment by RyanCavanaugh** [comment]
Your expectation is not correct; this isn't how subtyping in TS works.

**Comment by HyunnoH** [comment]
@RyanCavanaugh Oh, I misunderstood the subtyping. Thanks for answer!
