### ISSUE TITLE
Compile together multiple ES6 modules imported by canonical names. 

### ISSUE THREAD

**Issue by majo44** [Microsoft/TypeScript#4272]
I have library and application written in TypeScript. 

```
// libA/src/libA.ts
export var value = "libA"
```
```
//app/src/app.ts
import {value} from "libA"
```
For libA I created d.ts file
```
// libA/dist/libA.d.ts
declare module "libA" {
      export var value;
}
```
I compiling them separately with --module system. 
```
// libA/dist/system/libA.js
System.register([], function() { .....
```
```
// app/dist/system/app.js
System.register(["libA"], function() { .....
```
Such code is properly working with System.js lib in browser and also after bundling by System.js builder:
```
// libA/dist/libA.js
System.register("libA", [], function() { .....
```
```
// app/dist/app.js
System.register("app", ["libA"], function() { .....
```

And now is question. What if I will want to compile libA/src/libA.ts and app/src/app.ts together at once. I have to somehow map the "libA" canonical name to eg. ../../libA/src/libA.ts relative path. Is there any way to support such scenario, where I importing canonical names instead of relative ones ?

**Comment by mhegazy** [comment]
this should be covered by the path mapping proposal in #2338

```json
"paths": {
    "libA": "libA/src/libA",
}
```
