### ISSUE TITLE
tsc not converting script properly for es5

### ISSUE THREAD

**Issue by bakirp** [microsoft/TypeScript#42732]
# Bug Report

### 🔎 Search Terms
is:issue is:open es5 transformation 

### 🕗 Version & Regression Information
TSC Version 4.1.3

VS Code version
Version: 1.53.0 (system setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

- This is a crash
in tsconfig target is set to "es5" all other settings are as it is.
I am adding mention code in .ts file. After compile the generated js file I am trying to execute. it is not generating desired js. I beleive we can put any js code in ts file and it will behave same way as normal js. If I am running that code directly than it is working. it's an bug of **_ts_** to **_js_** file transformation for **_es5_**.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1#code/PQKgsAUAygxgTgSwA4BcAEAbA9jAhihLAOzRSzQDMEiATUgCwFM0tEBza3DAOknpRRIAzgC5gwGFhqMkjIt0LAA7oyEAjLEOCyiwAFYB5ALIA1AG4GA0pBDBIkSUSHpccOAEY0AXjQBtSGh+AEREuAC2jEEANGhBCDTRsbhskTFBKghs-IlBAMJYWBhBALpRAcFQAK5CuEQ5AMw5AEwADDnurYkocJWMpeW+QQBSWPR1ae7NkxMArG0x3b39EIGDAEJYas3NjWkAnPOUXEJ9ZSvBa3I5ACzNh0HuLYeLp5DFANz2EI7OaK5wTW8fgGIXCqVi8RyTEy2WWqyCGy2aSaOTmJTO8JGY3aNxm6JBl3GsVuaWujThFWqtQaNwAHCU3p8IA5iL9-vUgf5zoNQhEcpC0khXHIUPjuQjNts0gBPVRizGjIkPHKyoQMiAfL4USpEGAEYhoIVwE4AQTcuGlAAp-gBKNAAb3KP3QviYuBo1DYQhi3F9NHwuGKQP+TMCcEYKEqcBI-pQuG44ZolRgjEt1pgMBisdwMQQdq8AD4HeVAuJMAUkCwzIw4AxmG6PUQvTFanRcEIhJkSCgmIa4FhhKRyLUWGo9Iw9bxzoFnYaa0IDT57QBfUOBSisS2z3zUaQADxiDc9QawFDQR6bQm4IsQqktNrtjun69kxuIrsY7uPQOzO9ojD3TVn2XEs0HDSNoz8X1uFwDMYlfBciCAwJlxiXxihtJkQOZb5WRcDAMAAEQDTlymgo1TXNK1-ncG0MTQcjXEouALWtNwmjosjfQoxgzRY6i3HqTiNSZFknHQCI4BSOgfC4IiAwTRgkxTNNYMzNAYCjcMiBQAAFediHzIsnxnVlCkYbhsDYS0AANnFcAgmzQAASe1NLcEV9LfeReUYZcbJtcoywQM8e0YaU-nDP4MHDd0IuoOs-jgusSEklI6wQWtNnHPVvRYMLEBOP4aDoMKwidPC0AAhBnE9LzEIASX-PdgwzbgqFoJr90tBDFyLXr5HibwvB8dztL0gzBpoTDyhCtBLWq2qm3q4guoAtACx8FpH1AtTfEWxy2BWog1sAoETPXQJoL2g66sm06KUu6Cxs8ya0DLAAVJgiuFRKiEYJRKAQRgMBoIQ0BUAByKL3UbNg0GoUDsMu8CoxINS12R97gHypg4CUGrmFhv40H+wGBoRogAEJylRyDfGu5KXp046gNQvwMNEnCfnM7g4zUDBUzSpSZogIA)

### 💻 Code

```ts
/*
Script location to find the original.
https://codepen.io/wesbos/pen/jOMVvOK
*/

const arr1 = [
  ["name", "id", "age", "weight", "Cool"],
  ["Susan", "3", "20", "120", true],
  ["John", "1", "21", "150", true],
  ["Bob", "2", "23", "90", false],
  ["Ben", "4", "20", "100", true],
];

const arr2 = [
  ["name", "id", "height"],
  ["Bob", "2", "50"],
  ["John", "1", "45"],
  ["Ben", "4", "43"],
  ["Susan", "3", "48"]
];

const arr3 = [
  ["name", "id", "parent"],
  ["Bob", "2", "yes"],
  ["John", "1", "yes"]
];

function parseArray(arr) {
  const [headings, ...data] = arr;
  return data.reduce((acc, data, i) => {
    // loop over the headings, and assign the props to an object.
    const person = {};
    for(const [index, heading] of headings.entries()) {
      person[heading] = data[index];
    }
    return [...acc, person];
  }, []);
}

const allData = [
  ...parseArray(arr1),
  ...parseArray(arr2),
  ...parseArray(arr3),
];

const merged = allData.reduce((acc, currentPerson) => {
  console.log(`starting ${currentPerson.name}`)
  // if they are already in the acc, then merge their objects, otherise add them
  const existingPersonIndex = acc.findIndex(person => person.id === currentPerson.id);
  if (existingPersonIndex >= 0) {
    acc[existingPersonIndex] = {
      ...acc[existingPersonIndex],
      ...currentPerson // These are the new fields we're adding in
    }
    return acc;
  }
  // otherwise add a new person in!
  return [...acc, currentPerson];
}, []);


console.table(merged);

```

### 🙁 Actual behavior

generated js file is breaking the chages.

### 🙂 Expected behavior

it should generate valid es5 file.

**Comment by IllusionMH** [comment]
This works as expected - you have valid ES5 syntax in the end.
TS doesn't provide runtime polyfills for methods of native objects - you need provide your own e.g. CoreJS.

**Comment by IllusionMH** [comment]
You need to make sure that you have [`downlevelIteration`](https://www.typescriptlang.org/tsconfig#downlevelIteration) is set to `true`.
Also make sure that you provide runtime pollyfills for methods of native objects (`Array.prototype.entries` in your case).
