### ISSUE TITLE
Partial<T> is not work well with type 'this'

### ISSUE THREAD

**Issue by WanderWang** [microsoft/TypeScript#42731]
# Bug Report

### 🔎 Search Terms

Partial
this

### 🕗 Version & Regression Information

3.3.3 and 4.2.0-dev.20200207 ( in Playground)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.2.0-dev.20210207#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsdgtEBPAHgBUA+ACg1gHMQMAueKgGngAcYcvAM4B+DgAVY2KBGo0AlGwBuOLMADcAKE2QoQofACC8AN7b4F+AA94AXngAGLZfhk7jrZpfAcAZRwErAAWWKhMdPJmLi5EJOQMIUJcJlZsAIxcZOkAvvJeltma2UA

### 💻 Code

```typescript
declare function modify<T>(target: T, props?: Partial<T>):void;

class A {

    x = 0;
    y = 0;

    doSomething(){
        modify(this,{x:1,y:1})
    }
}
```

### 🙁 Actual behavior

Argument of type '{ x: 1; y: 1; }' is not assignable to parameter of type 'Partial<this>'.(2345)

### 🙂 Expected behavior

no expection

**Comment by RyanCavanaugh** [comment]
This is a correct error, `Partial<this>` isn't the same as `Partial<A>`. You could have written this, which would be unsound:
```ts
declare function modify<T>(target: T, props?: Partial<T>):void;

class A {
    x!: number;
    y!: number;

    doSomething(){
        modify(this, {x:1,y:1})
    }
}

class B extends A {
    x: 1 = 1;
    y: 1 = 1;
}
```
you can write `modify(this as A, ...` if you'd like to proceed anyway
