### ISSUE TITLE
Can we make the URL encoding of online editor easier to use

### ISSUE THREAD

**Issue by bosens-China** [microsoft/TypeScript#42730]
## Why
``` js
const a = 5;
```
``` sh
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDArAbgLACgg
```

I have a piece of code that I hope can be directly passed to the online editor in the form of URL and suffix. But now I don't know how to code his string. Can this method be exposed

**Comment by RyanCavanaugh** [comment]
You can use the old `src` format:
```ts
https://www.typescriptlang.org/play?#src=hello
```
If you want to create a compressed-style format, see the code: 
https://github.com/microsoft/TypeScript-Website/blob/9cf9ad852e9caf89e334a0740fc61f092b2932cf/packages/sandbox/src/compilerOptions.ts#L85
