### ISSUE TITLE
`String.charCodeAt()` must have a parameter

### ISSUE THREAD

**Issue by Nctdtman** [microsoft/TypeScript#42736]
# Bug Report
### 🔎 Search Terms
charCodeAt, string, method
### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/OQQ2DoGMAsQJwMIHsAmBTAggFwBQEog)

### 💻 Code
```ts
'a'.charCodeAt() // error
//  ~~~~~~~~~ An argument for 'index' was not provided.
```

### 🙁 Actual behavior
The parameter of `String.prototype.charCodeAt` written in [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt#parameters) can be omitted, and the default is `0`.
Or is this deliberately designed like this?

### 🙂 Expected behavior
```
'a'.charCodeAt() // return 97
```

**Comment by Nctdtman** [comment]
What I'm not sure about is, deliberately designed like this?
So I create this issue.

**Comment by MartinJohns** [comment]
> The parameter of `String.prototype.charCodeAt` written in mdn can be omitted, and the default is `0`.

Well, technically they don't write that it can be omitted, but that it defaults to `0` if it's not a `number`:

> If `index` is not a number, it defaults to `0`.

Also note that the parameter is **not** marked as optional (neither in the syntax, nor in the parameters list). Compare it to [the MDN entry for `parseInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#syntax) where `radix` is an optional parameter.

**Comment by Nctdtman** [comment]
> > The parameter of `String.prototype.charCodeAt` written in mdn can be omitted, and the default is `0`.
> 
> Well, technically they don't write that it can be omitted, but that it defaults to `0` if it's not a `number`:
> 
> > If `index` is not a number, it defaults to `0`.
> 
> Also note that the parameter is **not** marked as optional (neither in the syntax, nor in the parameters list). Compare it to [the MDN entry for `parseInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#syntax) where `radix` is an optional parameter.

Thanks i got it.
