### ISSUE TITLE
unexpected definition file generated with es6 import export expression.

### ISSUE THREAD

**Issue by vvakame** [Microsoft/TypeScript#4274]
unexpected definition file generated with es6 import export expression.

expected
```
$ tsc --module commonjs --declaration index.ts
$ cat index.d.ts
import { bar } from "./utils";
export { bar };
```

actual
```
$ tsc --module commonjs --declaration index.ts
$ cat index.d.ts
export { bar };
```

index.ts
```
import {foo, bar, Buzz} from "./utils";

foo();
let obj: Buzz;
export {bar};
```

utils.ts
```
export function foo () {}
export function bar () {}
export interface Buzz {}
```

this example is exec in tsc 1.5.3 and master/HEAD.

repro code.
https://gist.github.com/vvakame/92a86decdcccdf8dfbf2

**Comment by vvakame** [comment]
ah... not only for definition file. tsc can't emit expected js file too.
I think my code is es6 valid. isn't it?

**Comment by mhegazy** [comment]
@vvakame the js file looks good to me..

this is what i get with latest from master:

```
var utils_1 = require("./utils");
exports.bar = utils_1.bar;
utils_1.foo();
var obj;
```

**Comment by vvakame** [comment]
oops, you are right. js file is valid.

**Comment by mhegazy** [comment]
sorry for the delay. @vvakame can you give tonight's typescript@next a try.

**Comment by vvakame** [comment]
thanks! :+1:

**Comment by mhegazy** [comment]
thanks for verifying.
