### ISSUE TITLE
Variance analysis of constructors should ignore private/protected members

### ISSUE THREAD

**Issue by masaeedu** [microsoft/TypeScript#42740]
# Bug Report

### 🔎 Search Terms

variance, class members, private, protected, generic

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about variance

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwGIHtMB4AqAfPAN7wAOMmALuDcPAGbYBc8e8AvgFBdUCeZBFkwBhaKnxEAvCXgA7EAHcAFFVZ4AlK2GTOPAPT74AZRABbKHKoBLMFAgQ+AGngADYWJTJX8a2jCYVjBQAG6w1pZUvnJueK4u1jFUABYIyFBmCIpQfPApUFFQjACucmA2gXnJBYgQmMggaJghIDDwlu0wAObFmVbwmAx5AgiucfDKAEbFUQotbXBUxTByaNZUGr7+gVTBYTAR-Ymxrjz8ghgiAIzwMhjYnhLIu4ld8AA+8r2TrQS8I5cAEy3e6icTIHDPA5yLp-LiGeBQ15bdqI4qTc4IQaIl4wj5fMw-GDwozITAAOkpJNBjwhSLxnzk31+iOSmGKEHoP1RyHRmIGQw84MhuNhPFASDgiECz0Rcm0D2F9LejOZMD+AVWUWQCrBXhF0NhIOQcmpeABAHIhfrlfimYTfhaUXJqO1UNYunIoJMIAgqJhhhcrYqbaKCBbydT4GxLTpbaqHeqnX55K6vB6vT6-QH+cHcMrw5GEdHo+ag-GCUTk2gXYV3Z7vb68jnLcqI1GS6XLfaq860-XM03-YGEBa2+TlICAMyAwEaAxGABy1D91SiKRTfjkFsK0tWIAAjsUQGUsUNNVDiuVMDAmm1MilMMA0D9kSAAB7mMhRBiUMzwfZDjABBLHsPhkD8FxlBQeA+gqBR6GOFI0hecp0FKcprECMtGngAAFAAlBJgAAa18IZ8iibI0BAeY8hgY95wRAB1BA7BiawHGKKEClXFNJlyMBqhhZFXAoFdyhAegmEwdQfGHMTKBoSTpJYCY1DYTYpCIEJMGsYB4ngRRklsZJU0UaUzDITjcOqMhrMcVhkJHITwBI1oUTsshckCYDfCiYA-ACeY0GczJE2pSj4DgBhWlCgMxh8ZRjNMlEPxoFZ7EceBSkwSYGhgMIsxcSx6FSU95BAKSawDVywBI15NhTTVdlCcJInJIA)

### 💻 Code

```ts
declare class Foo<T> { protected foo: T }

type FooClass<T> = { new(t: T): Foo<T> }

// Semantically, `FooClass` is contravariant in `T`, in the same way that a
// function that closes over an argument of type `T` (but never returns it)
// is contravariant in `T`. We don't need to check the closure accessible within
// the function body as a covariant usage site.

type FC1 =  FooClass<string | number>
type FC2 = FooClass<string>

// string is a subtype of string | number
// so...
// FooClass<string | number> should be a subtype of FooClass<string>

declare const sn: FooClass<string | number>
const s: FooClass<string> = sn // error!
```

### 🙁 Actual behavior

The code doesn't typecheck, with the following error:

```
// Type 'FooClass<string | number>' is not assignable to type 'FooClass<string>'.
//   Type 'Foo<string | number>' is not assignable to type 'Foo<string>'.
//     Type 'string | number' is not assignable to type 'string'.
//       Type 'number' is not assignable to type 'string'.(2322)
```

### 🙂 Expected behavior

I expect the code to typecheck.

### Why this matters

React class components currently have a constructor `new(props: P, ...): Component<P>`, where `Component<P>` has a `readonly props: ... something involving P covariantly...` property. This makes class components invariant in `P`, whereas function components are covariant in `P`.

I don't believe that React intends users to access `props` from outside the methods of the class component, so I believe this should actually be `protected readonly props: ...` in the `.d.ts`. However, this by itself would have no benefit, because the typechecker's variance analysis still looks at the `protected props` member and rejects a `ClassComponent<P>` where a `ClassComponent<P'>` is expected, even when `P'` is a subtype of `P`. This despite the fact that the `ClassComponent<P>` can happily gobble up the `P'` it is being supplied, and is never expected to produce a `P'` for someone else's consumption.

### Notes

I don't think this is a consequence of constructors or methods being exempt from variance analysis, (as mentioned in the strictFunctionTypes PR). I don't know if this was ever true, but it doesn't appear to be true anymore.

We can illustrate this by changing `protected foo: T` to `protected foo: (t: T) => void`, which now compiles happily: the typechecker is satisfied once it discovers the member that refers to `T` (which is externally unobservable, and hence needs no checking) is contravariant.

**Comment by RyanCavanaugh** [comment]
I don't agree with this analysis because protected members of a class can be accessed by other instances of the class.

If `Foo<T>` observes its `protected foo: T` property *in any form*, then it's covariant.

If not, then what is the type parameter doing here?

It seems like you're trying to model a `writeonly` property?

**Comment by masaeedu** [comment]
@RyanCavanaugh I wasn't aware that private/protected members of a class instance can be accessed by other instances of the same class. Is there some stronger notion than `private`/`protected` that describes a member which is only accessible via `this` in the members of a class?

> If `Foo<T>` observes its `protected foo: T` property in any form, then it's covariant.

If an instance of `Foo<T>` observes its _own_ `protected foo: T` property, i.e. `this.foo`, I don't see what the problem is. It's the same situation as when a function observes its own parameter: does this make it covariant?

**Comment by masaeedu** [comment]
> It seems like you're trying to model a writeonly property?

I'm trying to model a property of the `this` variable/implicit parameter accessible inside class members, but not publicly accessible on constructed instances of the class (whether it's inside the class or outside). It doesn't have to be readonly or writeonly.

**Comment by RyanCavanaugh** [comment]
>  Is there some stronger notion than private/protected that describes a member which is only accessible via this in the members of a class?

Nope. This isn't well-precedented from our research; it looks like only Ruby has this behavior (for classes) among widely-used languages. JS has closure privacy for cases where you want no external reads of any kind.

> It's the same situation as when a function observes its own parameter: does this make it covariant?

This isn't the same situation because functions can't observe other functions' parameter values.

**Comment by masaeedu** [comment]
@RyanCavanaugh is there already an issue for obtaining the public interface of a class (i.e. which has all private/protected properties omitted)? `Foo<T>` might not be contravariant (at least within the class definition), but `(public Foo)<T>` is. Allowing us to implement:

```
const contraCast: <T extends U, U>(foo: public Foo<T>) => public Foo<U> = x => x
```

Will not cause problems in the `Foo` class implementation, because if it tries to pass itself (e.g. `Foo<string>`) to unsoundly narrow the privately observable `foo` property (e.g. to `Foo<"foo">`), it will simply get the `public Foo` supertype back.

**Comment by RyanCavanaugh** [comment]
Non-homomorphic mapped types will skip private/protected properties.
