### ISSUE TITLE
Option that treat each js file as module

### ISSUE THREAD

**Issue by redradist** [microsoft/TypeScript#42748]
# Suggestion

Add option `"typeJs": "module"` (default could be `"typeJs": "script"`)

## 🔍 Search Terms

How to say TypeScript that each js file is a module ?
How treat in TypeScript each js file as module ?

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add option `"typeJs": "module"` (default could be `"typeJs": "script"`)

## 📃 Motivating Example

In NodeJs we have ability to say which module system we use by setting `"type": "module"` in `package.json`
But when I add allowJs option TypeScript compiler treat each js file as plain script and it complains about redeclaration of the same function.
It would be nice instead of renaming each js -> mjs or adding stub export {}; statement to treat each js file as module, to add option, the same way node did

## 💻 Use Cases

It is needed in case for example where in project bunch of scratches js files with some code that do not import or export something at this moment

**Comment by RyanCavanaugh** [comment]
See #14279
