### ISSUE TITLE
Declared types act differently from inline types in functions

### ISSUE THREAD

**Issue by lonewarrior556** [microsoft/TypeScript#42742]
# Bug Report

A type bug cropped up in our code, upon investigating I realized someone simply renamed a type for code readability. 

The process of declaring an Identical type  and using that over an inline type somehow changed the type information being returned by a function. 
This was not the devs fault as this behavior is quite unexpected. 

### 🔎 Search Terms

function override  redeclare type 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried including nightly, and I reviewed the FAQ for entries

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/PTAECMEMGcFMBsCWA7WAoAZgV2QYwC6ID2yo+s0+AjABSIAmAXKJQE4oDmAlM+EUfFiRkAbkw4CxUuUq0GzAOQAhBTzKsssMdjyESZCtTpMW+dsm6gA3q1j4srUg1ABeN6GUKAvmgBukVlBIAEEqVwNZGgVVUBAIfkFhPwCIJTCXCKNPLliwM000NDiGWGRCSHhQeCIORFw0fABPAAdYUABhSGbEfAqlcM9tCT1pQwAmY2Y2TjU+ASFRcV0pTIn5Dq6evrV8rSXJfRl8NZNpixybOwcneld3Tx9-QJCx8KOJ6Jy4ufhkwPAlK8Mu8oiovmAAO4AC0a8XmwgA-H9QLh2kDVqCFEFoBtur14EpwaZEPBKj8FqAAIQI6nUtBAA)

### 💻 Code

```ts
// baseline
function test1(id: string): boolean;
function test1(id: 'B'): true;
function test1(id: string) {return id === 'B'}
var aA1 = test1('') // boolean
var bB1 = test1('B') // true

// idential logic
type CapitalB = 'B';
function test2(id: string): boolean;
function test2(id: CapitalB): true;
function test2(id: string) {return id === 'B'}
var aA2 = test2('') // bool
var bB2 = test2('B') // why boolean?
var cC2 = test2('B' as CapitalB) // still boolean !?!?!?

```

### 🙁 Actual behavior
Somehow `type CapitalB = 'B';` is NOT EQUIVELENT to type `"B"` when doing function overides

### 🙂 Expected behavior
There should be no diffrence betwen type `"B"` and `type CapitalB = "B"`

**Comment by RyanCavanaugh** [comment]
The overload selection algorithm is:
 * The first matching overload gets selected
 * There is no second step

So by putting the `string` overload first, you're always going to hit the `boolean` overload.

*However* there's a (legacy) rule that functions syntactically containing string literal type parameters (which used to *only* be legal in parameter positions) get sorted up to the top of the list. `CapitalB` does not fit that criteria.

The correct way to write this is:
```ts
function test2(id: CapitalB): true;
function test2(id: string): boolean;
```
