### ISSUE TITLE
Add flag to prevent assigning functions to types with differing number of arguments.

### ISSUE THREAD

**Issue by webstrand** [microsoft/TypeScript#42749]
# Suggestion

Add a new flag, `--strictFunctionAssignment`, which prevent the assignment of  _non-fresh_ function types with fewer number arguments than the target expects.

## 🔍 Search Terms
strict, function, assignment, callback, flag, arity

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Using functions not intended to be used as callbacks can be dangerous. Even if it works initially, if either the caller of the callee change the number of arguments or parameters, unintended behavior can result.

I suggest adding a flag, `--strictFunctionAssignment`, which prevents such unintended behavior by preventing the assignment of function types with inequal arity. To avoid becoming a burden, _fresh_ functions would be permitted to omit unused parameters. This is safe, because after assignment, the fresh function type is replaced by the expected type.

```ts
declare function oneArg(x: any): any;

declare function source(fn: (a: any, b: any) => any);
source(oneArg); // error
source(x => oneArg(x)); // due to freshness, not an error.

declare let prop: (a: any, b: any) => any;
prop = oneArg; // error
prop = x => oneArg; // due to freshness, not an error.

```

## 📃 Motivating Example

A very common mistake:
```ts
["1","2"].map(parseInt)
```

## Related Issues
#42579
#40899
#39997
#32228
#31628
#29951
#20274
#18063
#17868
#13977
#13043
#9300
#2392

**Comment by RyanCavanaugh** [comment]
This has been discussed to death and our stance on excess arity has not changed. Toggling this on freshness is just going to confuse the situation further.

**Comment by webstrand** [comment]
Ah, that's disappointing. Is there an existing issue you can link me to? I'm coming up empty.

**Comment by webstrand** [comment]
https://github.com/microsoft/TypeScript/issues/42579
https://github.com/microsoft/TypeScript/issues/17868
https://github.com/microsoft/TypeScript/issues/13043

**Comment by RyanCavanaugh** [comment]
#40899
#39997
#32228
#31628
#29951
#20274
#18063
#17868
#13977
#9300
#2392

etc 😅
