### ISSUE TITLE
The condition will always return 'false' after an array sort

### ISSUE THREAD

**Issue by pfusik** [microsoft/TypeScript#42754]
# Bug Report

### 🔎 Search Terms

array sort condition always

### 🕗 Version & Regression Information

- This changed between versions 3.5.1 and 3.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDMBTA7jAkmKBmAJgEEAnEuATwAoBtADgBoY8BdASgG4AoASwDMYVODQAMLGAEJkdNlwCQUABYkQmAERoAbqhJrucAHQQQJKFU5dQkEABtUBmyADmQi1eN2HzoaPGJkeBZAA)

### 💻 Code

```ts
const a = new Int32Array([8, 3]);
if (a[0] != 8)
    throw "never";
a.sort();
console.log(a);
console.log(a[0] == 3); // The condition will always return 'false' since the types '8' and '3' have no overlap.
```

### 🙁 Actual behavior

This diagnostic is invalid:

    The condition will always return 'false' since the types '8' and '3' have no overlap.

because the condition is `true`.

### 🙂 Expected behavior

No invalid diagnostic.

**Comment by MartinJohns** [comment]
See #9998. The compiler is not aware that the `sort()` function mutates the array.

**Comment by pfusik** [comment]
Thanks, but that is a long thread!
Why doesn't the compiler conservatively assume that the function mutates the array? The return value is clearly discarded.
Is there a workaround?

**Comment by MartinJohns** [comment]
> Why doesn't the compiler conservatively assume that the function mutates the array?

See #9998. It's a long thread because it's a complex topic.

> Is there a workaround?

Move the code to a new function and call it, or use a type assertion.
