### ISSUE TITLE
Type is not resolved from the passed generic type inside the function

### ISSUE THREAD

**Issue by cdpark0530** [microsoft/TypeScript#42759]
# Bug Report

### 🔎 Search Terms
generic parameter resolve

### 🕗 Version & Regression Information
v4.1.3
- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAKgVwA4BsCmMC8MDeBYAKBmJmgEMAnKALhgG0AidAMygYBoYGoQkGBdGGQgxQkKJwD0kmMxAUYAEQDyAWQBKaYFE1kAJsrAoAnoRKiUASzRga9BsCs2oADQ5dH12wE0BQkWLQMNKy8jAACiCWtmgUAKIAbs6EAL4A3ISEUMZIGADSaMbKzIioaHEAHlA2ehAAPHAAfFi4ZiR04TDRMADWhSDMMNm5A-DI6Py0w2ijpegd-HQADIJoVTUifcazMAD8ETC0YGhJFBkEKXRbo9Oz42j854TMCGDaluAwAOZoUABiFBAAFtEs4GjA1tUwLUYKDbI0ABQnZy0OCcLa0ApFEr3SpQ2oNRoASlaRBIITgOQwoyQgNyVGMXREEGQSBAEDQeiGIBgACMMMdTpxeQhYJYoAByEQUNAQEAoJJc4RcFhsGAAHw8Tlsbi6kEsegwUAAFhgXm8oB8wG1iIFYLTeLFsi05mgroVFitzuYZVAEBQwBCkrY6A76c7lXiKGRtHVboMw07jOj+oMmo9gjJLCIyDAAO7yHqUECvPQ2zMwX3+wPIkOJhmPVKZAghRQgWVgCX2wF6BDAI2miEUQEKcAmfOmwMASVIvyEonAwF9Rqpz1e70+P3+gJBwagyh6SL3tEi0Wq8T3KeMmMKxVdeI2dVPMQvzmJpPMdpg9ed2Fd7uMT1GzJYgqwDINnFDOkk2AlJm0kAAqBCzAQmBDHHBxtTVbMYASbNLF5dBODzY1LGAY0YCBNAyEgIZjTIKAUJgLE71xdZoXqJoYBuQckEoMgqPPGAJS2CUmUrWV5UVfwIQqXJtE5CcbBgbYEFEMgUBQOizXXS1wAAOhQyRCC3AFgThKAEWOPMIiiF8LIRBg2TPWIgRAJIGCJThMK8NgiTSIA)

### 💻 Code

```ts
const Tuple = {
    start: ["left", "top"] as const, // for DOMRectReadOnly
    client: ["clientX", "clientY"] as const // for PointerEvent
};

// Generic type that generates the [intersection](https://en.wikipedia.org/wiki/Intersection_(set_theory)) type of Tuple and T
type KeyOfTupleExtends<T> = {
    [P in keyof typeof Tuple]: typeof Tuple[P][0] extends keyof T ? P : never;
}[keyof typeof Tuple];
// type PointerEventTupleIntersection = KeyOfTupleExtends<PointerEvent> // {client: "client"}

function getFromEvent<T extends Event>(event: T, key: KeyOfTupleExtends<T>) {
    // Type of property is supposed to be never, but it's resolved as "left" | "clientX" inside this function
    const property = DirectedPropertySets[key][0];
    // return event[property as Extract<typeof property, keyof T>]; // is a workaround
    return event[property]; // error, but property is supposed to be able to index the argument 'event'
}

// Doesn't produce the error only when I set a concrete type
function getFromEventOk(event: PointerEvent, key: KeyOfTupleExtends<PointerEvent>) {
    const property = Tuple[key][0];
    return event[property];
}

/**
 * Only "client" is visible, which means that
 * KeyOfTupleExtends<T> of the parameter 'key' is resolved as expected when you call the function.
 */
getFromEvent(new PointerEvent("pointermove"), "client");
```

### 🙁 Actual behavior

Type `KeyOfTupleExtends<T>` of the parameter `key` of `getFromEvent` is resolved as `"left" | "top" | "clientX" | "clientY"` **inside the function**.

### 🙂 Expected behavior

Type `KeyOfTupleExtends<T>` of the parameter `key` of `getFromEvent` should be resolved as `never` **inside the function**.

**Comment by RyanCavanaugh** [comment]
There's some misunderstanding here. A value that's actually observed can't validly have type `never`, but this example prints `"clientX"`
```ts
const Tuple = {
    start: ["left", "top"] as const, // for DOMRectReadOnly
    client: ["clientX", "clientY"] as const // for PointerEvent
};

type KeyOfTupleExtends<T> = {
    [P in keyof typeof Tuple]: typeof Tuple[P][0] extends keyof T ? P : never;
}[keyof typeof Tuple];

function getFromEvent<T extends Event>(event: T, key: KeyOfTupleExtends<T>) {
    // Type of property is supposed to be never
    // ^^^^^^^^^^^^^^^^^^^^^^^^^
    const property = Tuple[key][0];
    console.log(property);
    return event[property as Extract<typeof property, keyof T>]; // is a workaround
}

getFromEvent(null as any as PointerEvent, "client");
```

**Comment by cdpark0530** [comment]
@RyanCavanaugh I'm sorry for not understanding your words well, but did you mean the type of `property` can't be `never` by `A value that's actually observed can't validly have type never`? I'm talking about static typing of the function definition not what the actual type will be in process.

I'll demonstrate this issue in another way as it seems I misled you about what I want to explain by `Type of property is supposed to be 'never'`.

When you typed `getFromEvent(null as any as PointerEvent, ...);`, only `client` is visible when you're passing the second parameter. It means that `T` and `KeyOfTupleExtends<T>` of `function getFromEvent<T extends Event>(event: T, key: KeyOfTupleExtends<T>)` are resolved well as expected. But then why the parameter `key` **in the function definition** can't index the parameter `event` by `event[Tuple[key][0]]`, saying below?
```
Element implicitly has an 'any' type because expression of type '"left" | "clientX"' can't be used to index type 'Event'.
Property 'left' does not exist on type 'Event'.(7053)
```

**Comment by cdpark0530** [comment]
@RyanCavanaugh I'm sorry for not understanding your words well, but did you mean the type of `property` can't be `never` by `A value that's actually observed can't validly have type never`? I'm talking about static typing of the function definition not what the actual type will be in process.

I'll demonstrate this issue in another way as it seems I misled you about what I want to explain by `Type of property is supposed to be 'never'`.

In the function definition of `getFromEvent`, the type of the argument `key` is suppopsed to be `never` because `T` extends `Event`. And it's supposed to be able to index the argument `event` by `event[Tuple[key][0]]`, but TS produces below error.
```
Element implicitly has an 'any' type because expression of type '"left" | "clientX"' can't be used to index type 'Event'.
Property 'left' does not exist on type 'Event'.(7053)
```
**Outside of the function definition**, `KeyOfTupleExtends<PointerEvent>` is resolved as `"client"`, which is working as intended as you can see only `"client"` when you pass the second parameter to the function while typing `getFromEvent(null as any as PointerEvent, ...);`.
But **inside of the function definition**, `KeyOfTupleExtends<T extends Event>` is supposed to be `never` because `KeyOfTupleExtends<Event>` is `never`, so the argument `key` is supposed to be able to index the argument `event` by `event[Tuple[key][0]]`.

**Comment by RyanCavanaugh** [comment]
I don't understand what you're trying to demonstrate here. An example that more clearly shows some incorrect behavior would be useful.

**Comment by cdpark0530** [comment]
@RyanCavanaugh 
```
type Something = {
	target: "target",
	clientX: "clientX";
};

type KeysIntersecting<T> = {
	[P in keyof Something]: Something[P] extends keyof T ? P : never;
}[keyof Something];

type IntersectingEvent = KeysIntersecting<Event>;

// fine
function foo<T extends Event>(e: T, k: never) {
	return e[k];
}

// fine
function koo<T extends Event>(e: T, k: IntersectingEvent) {
	return e[k];
}

// produces an error
function boo<T extends Event>(e: T, k: KeysIntersecting<T>) {
	return e[k]; // Type 'KeysIntersecting<T>' cannot be used to index type 'T'
}

// fine, only "target" is visible when setting the second parameter
boo(null as any as Event, "target");
```
Why `boo` produces the error on the return line?

**Comment by RyanCavanaugh** [comment]
There's no way for TS to realize that the only kinds of things that can come out of `Intersecting<T>` are `keyof T`s. You could write it this way to get the desired behavior:
```ts
type Intersecting<T> = {
	[P in keyof Something]: Something[P] extends keyof T ? P : never;
}[keyof Something] & (keyof T);
```
