### ISSUE TITLE
Allowing subclasses to narrow types from the superclass breaks substitutability

### ISSUE THREAD

**Issue by bicknellr** [microsoft/TypeScript#42750]
# Bug Report

### 🔎 Search Terms

- liskov
- liskov substitution
- substitution
- subclass narrow
- subclass substitution

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (all that are available on the playground currently) and I reviewed the FAQ for entries about [substitutability](https://github.com/Microsoft/TypeScript/wiki/FAQ#substitutability). (I'm not sure if the ["Why are function parameters bivariant?"](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant) section is relevant to this situation.)

### ⏯ Playground Link

- [instance method snippet](https://www.typescriptlang.org/play?ts=4.1.3#code/MYGwhgzhAECC0G8BQ1oDMAUAHAXNCALgE4CWAdgObQA+0ZArgLYBGApkQJSIqrTAD2ZCPxCsAdCH4UMAclgyANNCwcA3DwC+SLUlCQYAIWisAHgVZkAJjHjJUmXPmLkKXO7wFCR4ydJkHFZSUsMWAACzAiAGF+S1ZYAgwABg41TW0kXUFCaEiiMABPAHk0WDxYInyCgB5YAD5oAF5oAG0yVgB3OAwOJXaugx6AXXU0fiJoDE8cknNGaH40XMrCktg3HlnWRjFMAEYAJgBmNI0gA)
- [static function snippet](https://www.typescriptlang.org/play?ts=4.1.3&ssl=16&ssc=2&pln=1&pc=1#code/MYGwhgzhAECC0G8BQ1oQC5nQS2NAZgBQAOAXGugE7YB2A5tAD7Q0CuAtgEYCmlAlIhSpowAPY0IokNwB0IUXUIByWEoA00YnwDcQgL5IDSUJBgAhaNwAe6bjQAmMeMlQYsuAiXIZq9AS+ExCSlZeUUlM3VNDWIZYAALMEoAYVF7blh0QgAGPh19QyRjcQxoJMowAE8AeXxYclhKCsqAHnRK4m5RfDgAPmgAXmgAbVgNMwBdXXxRSmhCINLsW3ZobrKmqtrYfyFl7nYZIgBGACYAZny9IA)

### 💻 Code

```ts
class A {
  f(p: string | number) {
    console.log('A', p);
  }
}

class B extends A {
  f(p: string) {
    console.log('B', p, p.charCodeAt(0));
  }
}

const arrayOfA: Array<A> = [new A(), new B()];
for (const item of arrayOfA) {
  item.f(123);
}
```

Also:

```ts
class A {
  static f(p: string | number) {
    console.log('A', p);
  }
}

class B extends A {
  static f(p: string) {
    console.log('B', p, p.charCodeAt(0));
  }
}

const arrayOfA: Array<typeof A> = [A, B];
for (const item of arrayOfA) {
  item.f(123);
}
```

### 🙁 Actual behavior

TypeScript compiles this code with no error. A runtime error is thrown when `B.prototype.f` (or `B.f`) attempts to call `.charCodeAt` of `123`.

### 🙂 Expected behavior

TypeScript should fail to compile this code, with an error explaining that `B` may not override `f` with a function that narrows the type of parameter `p`.

**Comment by bicknellr** [comment]
@justinfagnani pointed me to a couple related issues around the `static` half of this: #5863 #4628

**Comment by RyanCavanaugh** [comment]
This is exactly method bivariance.

**Comment by bicknellr** [comment]
I'm not experienced enough with type systems to know if you're using the phrase "method bivariance" to refer to the same thing as the "function parameter bivariance" from [the FAQ section](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant) or if you're calling out that this is different because this involves a method of a class, rather than some arbitrary function. Do you think this is a valid issue or is this expected behavior?

**Comment by RyanCavanaugh** [comment]
This is the expected behavior; the widespread prevalence of classes with methods that behave this way (e.g. the DOM event methods, classes with overly strict "compareTo" methods, etc) is why we still have function/method parameter bivariance.

**Comment by Woodz** [comment]
I strongly recommend that this issue is re-opened and reviewed. This breaks typing of many OOP design patterns (e.g. abstract factory, etc), causing errors that can only be caught at runtime
