### ISSUE TITLE
Cannot regenerated .d.ts file when "composite" is true in tsconfig.json 

### ISSUE THREAD

**Issue by qkreltms** [microsoft/TypeScript#42755]
# Bug Report
### 🔎 Search Terms
Cannot rebuild type definition file when "composite" is true in tsconfig.json

### 🕗 Version & Regression Information

1. When I start to build it builds d.ts files for each packages(button, button2) and tsconfig.tsbuildinfo is generated for button2 which is `composite: true`.
2. **When I build again** can't build for package(button2), but if I delete tsconfig.tsbuildinfo, it works expected.

I tested it in 4.1.4 and 4.3.0-dev.20210211
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about composite, references options

### ⏯ Playground Link

type `yarn install` and `yarn build`
[Playground link with relevant code](https://github.com/qkreltms/lerna-test1)

### 💻 Code
button/tsconfig.json
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "declarationDir": "./lib",
    "rootDir": "./src",
    "baseUrl": "./",
  },
  "include": ["./src", "../../global.d.ts"],
  "references": [
    { "path": "../button2" }
  ]
}
```
button2/tsconfig.json
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "declarationDir": "./lib",
    "rootDir": "./src",
    "baseUrl": "./",
    "composite": true
  },
  "include": ["./src", "../../global.d.ts"]
}
```
root/tsconfig.json
```json
{
  "compilerOptions": {
    "declaration": true,
    "baseUrl": "./",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react",
  },
  "include": ["packages/*/src", "global.d.ts"],
  "exclude": ["node_modules", "**/*.test.ts", "**/*.test.tsx", "lib", "dist"]
}
```

### 🙁 Actual behavior
.d.ts file is not regenerated for package(button2)

### 🙂 Expected behavior
.d.ts file must be regenerated for package(button2)

**Comment by sheetalkamat** [comment]
The link to repro code is not accessible. Can you make sure we have access to the repro code and get back as its hard to investigate this without actual repro.

**Comment by qkreltms** [comment]
Sorry for long waiting I opened my repo

**Comment by sheetalkamat** [comment]
`yarn install` still fails so cant repro this 
```
c:\temp\lerna-test1>yarn install
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "http://localhost:4873/@my%2fbutton2/-/button2-1.0.1.tgz: connect ECONNREFUSED 127.0.0.1:4873".
info If you think this is a bug, please open a bug report with the information provided in "c:\\temp\\lerna-test1\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by qkreltms** [comment]
@sheetalkamat I cloned it and tried reproduce it, but it works as expected.(can regenerate .d.ts files.)
