### ISSUE TITLE
Optional properties should separate 'having property' and 'its being undefined'

### ISSUE THREAD

**Issue by kemphack** [microsoft/TypeScript#42778]
# Bug Report

### 🔎 Search Terms

Trying to build different types, useful constructions for development with typescript.
example:
`export type DefaultOpts<T> = Required<Pick<T, {
  [K in keyof T]: undefined extends T[K] ? K : never;
}[keyof T]>>
`

### 🕗 Version & Regression Information

- This is inaccuracy
- Everything that touches Object.assign type definition (lib.es2015.core.d.ts)

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA6gFgQ2BAbhATgFXNAvFAbwCgpSoEB+ALigDsBXAWwCMMBuIgXyNElkWRosOAExR8xMuRoMW7LkQA2EYFAD2zAFY14SVBmyQxEkmQQ0RAGgXLVGzQEYdA-cL4mp5qPVoATCABmAJa0EL7W3LbqWiLOekKGeIQKSipQAMZqLCEQDuJQAPJaEOnAAHQIAM6VQQDmtAAUBJyW0Zqt9g4AlBxRmdmhxoXFpRXVdY3NHVrTmiI9RJm0lWrKZYpqtQ39zDkOFT0A9Ie8EJXp6EFgqsBwIQDWlVC3SORQQU+yrOhQcBgQZSgtTUqh8-mCoV8izUy1WAI2Wx2OREBzYx065D8bTEviCAQCGCeCCgu2ArVY6QQ9Eq0HsOLUZ1oqkQaCgYHQakg6FA5FmeUQlSIQA)
### 💻 Code

```ts
let a: {prop: number} = {prop: 2};
let b: {prop?: number} = {prop: undefined};
let combine = Object.assign({}, a, b);
```

### 🙁 Actual behavior

```ts
combine.prop//is undefined, property prop is type of number
```

### 🙂 Expected behavior

Separate 'having property' and 'its being undefined', or correct typing for Object.assign.

**Comment by RyanCavanaugh** [comment]
See #13195

**Comment by kemphack** [comment]
> See #13195
In this case nevertheless Object.assign still a problem.

**Comment by RyanCavanaugh** [comment]
We can make spread work with #13195, but as a userspace function we're unlikely to be able to represent in the type system the complex behavior of `Object.assign`

**Comment by kemphack** [comment]
> We can make spread work with #13195, but as a userspace function we're unlikely to be able to represent in the type system the complex behavior of `Object.assign`
You are right, but it would be much easier to have choice between optional-undefined and just optional
