### ISSUE TITLE
Debug Failure. False expression: end must be the bounds of the file

### ISSUE THREAD

**Issue by fkollmann** [Microsoft/TypeScript#4277]
Hi,

when developing on my laptop, I ran into the following error, when trying to compile a project using VS:

```
VSTSC(0,0): error : Debug Failure. False expression: end must be the bounds of the file. 1627 > 881
```

However, out of the blue, I now got the error on my primary development machine. I also get this issue when building using the commandline:

```
VSTSC : tsc.js(688, 17) JavaScript runtime error : Debug Failure. False expression: end must be the bounds of the file. 1627 > 881 [D:\Projekte\padsy\NodeJs\padsy_api\padsy_api.njsproj]
```

I currently try to get a full stacktrace, but no luck so far.

Getting a clean workspace/source files does not help. Using another new Windows user, doesn't help either :( .

Regards, Felix

**Comment by RyanCavanaugh** [comment]
Can you post a file that reproduces the issue?

**Comment by fkollmann** [comment]
Well, I was able to figure out, that it has sth to do with the references I use. Not with my code, directly:

```
tsc --module CommonJS --sourcemap --target ES5 --noEmitOnError _references.ts
tsc.js(688, 17) JavaScript runtime error: Debug Failure. False expression: end must be the bounds of the file. 1627 > 881
```

Let me try to figure out which one causes this.

**Comment by fkollmann** [comment]
Here is the result:

```
D:\Projekte\padsy\NodeJs\padsy_api>"D:\Projekte\padsy\Tools\Git\bin\find.exe" .\typings -name "*.d.ts" -print -exec tsc --module CommonJS --sourcemap --target ES5 --noEmitOnError "{}" ";"
.\typings/body-parser/body-parser.d.ts
error TS5012: Cannot read file 'typings/body-parser/body-parser.d.ts': Unsupported file encoding.
.\typings/documentdb/documentdb.d.ts
.\typings/express/express.d.ts
.\typings/express-domain/express-domain.d.ts
.\typings/form-data/form-data.d.ts
.\typings/mime/mime.d.ts
.\typings/mocha/mocha.d.ts
.\typings/moment/moment-node.d.ts
.\typings/moment/moment.d.ts
.\typings/morgan/morgan.d.ts
.\typings/node/node.d.ts
.\typings/node-uuid/node-uuid.d.ts
.\typings/passport/passport.d.ts
.\typings/passport-oauth2/passport-oauth2.d.ts
typings/passport-oauth2/passport-oauth2.d.ts(2,30): error TS2307: Cannot find module 'express'.
typings/passport-oauth2/passport-oauth2.d.ts(3,31): error TS2307: Cannot find module 'passport'.
.\typings/pmx/pmx.d.ts
.\typings/redis/redis.d.ts
.\typings/request/request.d.ts
.\typings/serve-static/serve-static.d.ts
.\typings/tsd.d.ts
tsc.js(688, 17) JavaScript runtime error: Debug Failure. False expression: end must be the bounds of the file. 1627 > 881
```

**Comment by fkollmann** [comment]
Okay, problem solved! The error went away after fixing the file encoding of the *body-parser.d.ts* file.

**Comment by mhegazy** [comment]
@fkollmann what version of tsc are you using?  `tsc --version`?

**Comment by fkollmann** [comment]
Latest. "Version 1.5.3" with VS2015  (actually the 1.5.4 installer). But I had the same issue with VS2013.

**Comment by mhegazy** [comment]
I can not get a repro for this locally using latest tsd and latest. any additional information would be appreciated.

**Comment by fkollmann** [comment]
Here is a case to reproduce: [http://public.fkollmann.de/Tickets/GitHub/TypeScript4277/repro.zip]

The issue happens if a file with *wrong* encoding is referenced after one with *correct* encoding. If the *wrong* encoded file is referenced first, the correct encoding error is shown.

```
C:\Users\mail_000\Downloads\repro>tsc --module CommonJS --sourcemap --target ES5 --noEmitOnError ref.ts
tsc.js(688, 17) JavaScript runtime error: Debug Failure. False expression: end must be the bounds of the file. 140 > 94
```

Have fun!

**Comment by mhegazy** [comment]
thanks got the repro.
