### ISSUE TITLE
not able to find global type definition if global file name is the same as a ts file

### ISSUE THREAD

**Issue by bochen2014** [microsoft/TypeScript#42774]
project/
├── src/
│   ├── myFile.d.ts
│   ├── myFile.ts
└── tsconfig.json

```ts
//myFile.d.ts
interface Person{
name
}

//myFile.ts
const ross:Person={
name:'ross'
}

//tsconfig.json
{
  "include":['src/**/*']
}
```

above structure will throw compile error complaining `Person` not defined;
*however*, after changing `myFile.d.ts` to `myFile1.d.ts` , it will compile.

what's the reason behind it? or is it a bug? I'm not able to find any documentation for it. Any thoughts?

**Comment by MartinJohns** [comment]
You forgot to fill out the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md).

---

When you have two files with the same filename (excluding extension), then the one file is considered an output file of the other. Same reason why you can't have a `foo.ts` and a `foo.js` at the same time. See [this comment](https://github.com/microsoft/TypeScript/issues/10704#issuecomment-245336321).

It doesn't really make sense to split up your code into a `.ts` and a `.d.ts` file anyway.

**Comment by bochen2014** [comment]
thanks @MartinJohns 

you comment makes perfect sense. Close the issue
