### ISSUE TITLE
Properties in any members of Union should be Optional (or | undefined)

### ISSUE THREAD

**Issue by benjaminjackman** [microsoft/TypeScript#42775]
# Suggestion

Properties that are present in at least one member of a union type (but not all) should be present as optional or `undefined` | the union {of all of the types for that property in the various union members} e.g. 
```typescript
{a:number,c:number} | {b:number,c:number}
```
should be seen as 
```typescript
{a?:number,b?:number,c:number}
```
or
<s>
```typescript
{a:number|undefined,b:number|undefined,c:number}
```
</s>
_EDIT: `{a?:number,b?:number,c:number}` Needs to be used because ? is subtlety different from |undefined and prevents code from compiling in examples below._

instead of 
```typescript
{c:number} 
```
as is currently the case.

This will allow for code completions off the individual members (perhaps with ?. magically inserted) and the very legal (in javascript) use of ?. and ?? operators on a single property basis without having to resort to "in" or type-guard narrowing.

## 🔍 Search Terms

Union members optional properties or undefined | undefined.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] _(see 1 below)_ This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

1: I think any code this breaks already does not compile. It could, however, be a boon or bane to high level type wizards, and as their ways are often indecipherable from magic, I cannot say which of either, both, or neither.

## 📃 Motivating Example
This example demonstrates a function that can handle 2d and 3d vectors.

```typescript
interface Vec2 {
  x: number
  y: number
}

interface Vec3 {
  x: number
  y: number
  z: number
}

type Vec = Vec2 | Vec3

function magnitude(v: Vec) {
  //In the union of Vec2 | Vec3, the most correct type of `v.z` is `number | undefined`, not just `undefined`
  //currently z is always undefined 
  //Therefore this does not compile
  Math.sqrt(v.x*v.x + v.y*v.y + (v?.z ?? 0) * (v?.z ?? 0))
}
```

Edit this part is not particularly relevant so erasing it:
<s>
```
//However, if we add in a placeholder `z` variable with the type of undefined
interface Vec2U {
  x: number
  y: number
  z: undefined //<-- Placeholder
}

type VecU = Vec2U | Vec3
function magnitudeU(v: VecU) {
  //This now compiles
  Math.sqrt(v.x*v.x + v.y*v.y + (v?.z ?? 0) * (v?.z ?? 0))
}
//The proposal, if accepted and implemented, would make the top function compile as well.
```
</s>

## 💻 Use Cases

What do you want to use this for?
Now that we have ?. and ?? in the language, a lot of lightweight code which is valid javascript and which deals with types represented by unions does not compile in typescript. This proposal seeks to fix that.

What workarounds are you using in the meantime?
I believe you can do something like this :
```typescript
//Off the top of my head I think this type might work as substitute
type JsUnion<A,B> = (A & Record<keyof Omit<B, keyof A>, undefined>) | (B & Record<keyof Omit<A, keyof B>, undefined>)
type VecJ = JsUnion<Vec2, Vec3>

function magnitudeJ(v: VecJ) {
  //compiles
  Math.sqrt(v.x*v.x + v.y*v.y + (v?.z ?? 0) * (v?.z ?? 0))
}
```

**Comment by MartinJohns** [comment]
Remember that TypeScript is structurally typed. The type `{a:string,b:number,c:number}` is assignable to `{b:number,c:number}`. Having the union result into a type with the property `a` typed as `string | undefined` wouldn't be sound.

**Comment by RyanCavanaugh** [comment]
And indeed this works like you expect if you write `Vec2` to prevent aliases to values like `{ x: 1, y: 2, z: "three" }`
```ts
interface Vec2 {
  x: number
  y: number
  z?: number
}
```

**Comment by benjaminjackman** [comment]
I don't understand the structural type unsoundness, can you provide a more concrete example so that I can better understand the issue?

This I what I tried, (though I could fundamentally just not be getting the issue ... it's been a while since I read my copy of Design Concepts in Programming Languages, so please tell me how I am being dense here, because I sure I am somehow)
```typescript
type X = {a:string,b:number,c:number}
type Y = {b:number,c:number}
type XUnionY1 = {a?:string,b:number,c:number}

const x : X = {a:"",b:0,c:0}
const y : Y = {b:0,c:0}
const badnews : {a?:string,b:number,c:number} = {  a:"",  b:0  c:0}

//Compile
const u0x : X|Y = x
const u1x : XUnionY1 = x
const u0y : X|Y = y
const u1y : XUnionY1 = y
//Note if xy1x type XUnionY1 = {a:string|undefined,b:number,c:number}, then this does not compile
// so this points to requiring the union use ? for types not present in all members

//Compile
const y0x : Y =  u0x
const y1x : Y =  u1x
const y0y : Y =  u0y
const y1y : Y =  u1y

//All do not compile
const x0x : X =  u0x
const x1x : X =  u1x
const x0y : X =  u0y
const x1y : X =  u1y

//Both compile
const xy0 : X|Y = badnews //<-- maybe this shouldn't be compiling though it seems to presently?
const xy1 : XUnionY1 = badnews

```

My sense is that if it is the case that ?. can legally be used, and it's reasonable to expect that users will use it, and we know that it legally can in this instance, it should be legal to call it and serve it to them in intellisense.

If users write code that takes a Vec2 or a Vec3, and they want to use `?.` in javascript to access the .z variable it's totally ok to do so. However typescript will give a type error, even though it is reasonable to expect that `?.` can be used *safely* in this instance. I am not referring to the overall assignability of types, just that if you have a `const v :  Vec2| Vec3` and you write  `v?.z` the code should pass the type checker. Though if we want to look a bit further a field if you were to iterate of the keys of a Vec2|Vec3 union you would expect to receive [x:string,y:string, z?:string] so I do think this is more than just a let's be magical about ?. type of issue.

We can coerce the type to Vec3 with an `if ("z" in v)` check, however that is not at all what I would except to be idiomatic moving forward now that we have ?. and ?? in the language. Though It still makes a lot of sense in heavier weight cases (or even better to use type guards) but we are clearly missing being able to type a common use case in javascript code.

With regards to 
```typescript
interface Vec2 {
  x: number
  y: number
  z?: number
}
```
Again I am not following. Is that a workaround that users could employ, or a proof of unsoundness?

**Comment by RyanCavanaugh** [comment]
It's legal to write
```ts
const m = { x: 0, y: 0, z: "hello world" };
const n: { x: number, y: number } = m;
const o: Vec2 | Vec3 = n;
```

It's proposed that it be legal to write
```ts
const p = o?.z ?? 0;
```
yet this code crashes because `p` is inhabited by a `string`, not a `number`:
```ts
p.toFixed();
```

**Comment by benjaminjackman** [comment]
Ok, that's very clear, I understand, thank you.

However:

```typescript
if ("z" in o) o.z.toFixed()
```
Is presently legal and also crashes.

So what I am proposing more so goes towards `?.` and `??` consistent with `in`
logically if we allow
```typescript
if ("z" in o) o.z.toFixed()
```
For consistency, I believe we should allow what seems to be the simplification of the `in` check to:
```typescript
o?.z.toFixed()
```

I believe the corruption of the type system is orthogonal to this proposal. Because it happens at the point we losing typing information in assignment of `m` to `n`. At that point there is a hidden z string monster lurking in that object that can rear it's ugly head at any time and already can with in.

Now outside of this worrisome instance I find myself much more often in a position where I am using an `in` check to narrow and not being surprised like this (not to say it doesn't happen but it's not going to be anywhere near as common as z being a double) and having to write the `in` ceremony which is providing with no extra safety, when we could just use `?.` for all the times something hasn't already gone terribly wrong.

Full code:
```typescript

type Vec2 = {x: number, y: number}
type Vec3 = {x: number, y: number, z: number}

const m = { x: 0, y: 0, z: "hello world" };
const n: { x: number, y: number } = m;
//Have to go through unknown here b/c otherwise the compiler deduces that o is actually a Vec2
const o: Vec2 | Vec3 = n as unknown as Vec2|Vec3;

//Compiles currently ... uh-oh
//crashes
if ("z" in o) o.z.toFixed()

//Does not compile currently, crisis averted?
const p = o?.z ?? 0;
p.toFixed();

//Proposal
type Union2 = {x: number, y: number, z?: number}
const o2: Union2 = n;

//crashes
if ("z" in o2) o2.z.toFixed()

//crashes
o2.z?.toFixed()

//crashes
const p2 = o2?.z ?? 0;
p2.toFixed();
```

**Comment by RyanCavanaugh** [comment]
The difference here is intentional - there's no confusion about what's happening when you use `in`, but with a normal `?.` you might not realize that you're accessing an out-of-type value.

**Comment by benjaminjackman** [comment]
I don't believe their is a good case for the `in` is intentional and `no confusion` argument here.

1. It's not mentioned anywhere in the document if it was supposed to be explicit, then this gotcha would be mentioned, 
2. 

As a matter of fact I'd argue to opposite, one of the primary uses for ?. is 

Perhaps for very experienced people working in the compiler, sure fair enough, and in check triggers their spidey sense to suspicious of what follows in a way that ?. doesn't

But realistically what are you going to be doing here? Not trusting in?
That doesn't smell right. No where in the documentation for `in` is this gotcha mentioned. If there really was no confusion about what in was doing, you'd expect that this cornercase was mentioned in the handbook here: https://www.typescriptlang.org
/docs/handbook/advanced-types.html#type-guards-and-differentiating-types

Warning when using in, you previously could have assigned an object with a member with a type you 

Instead it's pretty clear that the notion that you have some code that has a random other surprising value is pretty rare in practice and it probably falls under the areas where the unsoundness

**Comment by benjaminjackman** [comment]
Oops I accidentally submitted a half completed comment, sorry about that.

Well I feel like we are trading away a lot of the usability we get from the chain-ability and succinctness of `?.` in exchange for 'no confusion'. Which is not mentioned anywhere in the docs for `in` that this is something it's alerting you to, I would hazard a guess that most users don't really think about the potential that some other type snuck into their union when using an `in` block and they need to have a plan to address that ( I certainly haven't but I can't even submit comments correctly on github so I might not be the best example ).

So I believe it's simply a usability tradeoff, 

For example 
```typescript
`const p = {...o}.z?.toFixed()`
```
Spreads with unions face the same perils and therefore we could make the similar decision to erase z entirely. I don't believe we do because I believe that not having the z typed as number | undefined in the result of the spread is worse. I believe it's the same for `?.` It's a matter of convenience and trusting that types we have receive in the type system generally are not incomplete. If you start assuming that every single type is in fact incomplete in typescript and has the potential to have any number additional fields with any number of different types I think we are going to have a lot of problems.

I am all for making users stop and think about what they are doing, but we need to then consider if we are making them really do that or we are making them pay a price for something that happens frequently or very infrequently and do we trust the types as they are or assume every type use will very frequently have a member that snuck in with a name and a type that just so happens conflict with what they are expecting.

But fair enough for all that, let's say I am totally silly, because we don't know that z isn't potentially a string, would the type be?
```typescript
{ x: number, y: number, z?:unknown|number};
```

**Comment by RyanCavanaugh** [comment]
This is longstanding (see #805), well-considered behavior and we really aren't interested in making the language less sound in this particular case. There are places where we're willing to make convenience trade-offs (`in` being a primary example), but plain property access isn't one of them. There are serious problems that can arise when you start doing this, e.g.
```ts
type Message =
  { kind: "close" } |
  { kind: "data", payload: object }

function handle(m: Message) {
  switch (m.kind) {
    case "close":
      console.log("closing!");
      // forgot 'break;' here
    case "data":
      updateBankAccount(m.payload);
  }
}
}
```

> If you start assuming that every single type is in fact incomplete in typescript and has the potential to have any number additional fields with any number of different types I think we are going to have a lot of problems.

This isn't just an assumption, it's a core tenet of the type system, and you can already observe what problems do and don't arise.

**Comment by benjaminjackman** [comment]
Ok, thanks for explaining the details behind this. I'll just close the issue since it's a core tenet of the type system. I am not really clear on exactly why exceptions to that tenet lie where they do (in, spreads etc) but clearly they do not extend for `?.` and I am just going to keep rehashing various remixes on the same basic argument, that in a function(v: Vec2|Vec3). the most sensible thing is to allow for v.z?. (v.z. being a different story) and that it's not going to be any more dangerous to do so than allowing for other cases that bypass the soundness (e.g. in, spreads etc) but the point is taken and I don't want to waste anyone's energy better spent on more clear-cut enhancements to the language.
