### ISSUE TITLE
Type 'IPropertyValue<IDerived>' is not assignable to type 'IPropertyValue<IObjectWithId>'.

### ISSUE THREAD

**Issue by DavidSnipp** [microsoft/TypeScript#42781]
```ts
interface IObjectWithId {
  id: number
}
interface IDerived extends IObjectWithId {
  name: string
}
interface IPropertyValue<T extends IObjectWithId> {
  formatter: (row: T) => void
}

const notassignable: IPropertyValue<IObjectWithId> = {} as IPropertyValue<IDerived>

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const notassignable = {};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210207#code/JYOwLgpgTgZghgYwgAgJIHkBGArCCwDqwYAFqgCbIDeAUMssOQFzIgCuAtptDQL42hIsRClQARaMABuEShAAekEOQDOaLLnxFSFanVZwOEFirBRQAcz4Dw0eEjQAFKAHsADtDABPAGpwANmwQADwAKsgKSqrqOHiExGTkAHx69DAuUBxwYEIsABSuAO4soQCUyAC8KVIujNY0CC4gpqwuYHAqKsAWIHCY-sZOrh5Q3n6BIRixWgkUKRXUvMgdQ+6evgFBweKSMsk0QA)

This fails to compile with: 
const notassignable: IPropertyValue<IObjectWithId>
Type 'IPropertyValue<IDerived>' is not assignable to type 'IPropertyValue<IObjectWithId>'.
  Property 'name' is missing in type 'IObjectWithId' but required in type 'IDerived'.(2322)
input.tsx(5, 3): 'name' is declared here.

Interestingly, if I change the formatter property of the IPropertyValue interface to simply be a type of T, then it compiles.
It seems having formatter as a type of a function that takes a Parameter of T causes it to fail.

**Comment by RyanCavanaugh** [comment]
This error is preventing a potential crash:
```ts
interface IObjectWithId {
  id: number
}
interface IDerived extends IObjectWithId {
  name: string
}
interface IPropertyValue<T extends IObjectWithId> {
  formatter: (row: T) => void
}

const p: IPropertyValue<IDerived> = {
    formatter(m) {
        console.log(m.name.toLowerCase());
    }
}

const notassignable: IPropertyValue<IObjectWithId> = {} as IPropertyValue<IDerived>;
// Crashes
notassignable.formatter({ id: 10 });
```

See https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science) for why parameter position vs property position matters

**Comment by DavidSnipp** [comment]
Thank you for your quick response and simple explanation.
