### ISSUE TITLE
Parameter decorators can't be used on class assigned to variables or constants

### ISSUE THREAD

**Issue by ericmorand** [microsoft/TypeScript#42784]
Consider the following code sample:

```ts
const Decorator = () => {
    return (target: object, key: string | symbol, index?: number) => {

    }
}

const Foo = class {
    constructor(@Decorator() foo: string) {

    }
}

const Foo1 = class Foo1 {
    constructor(@Decorator() foo: string) {

    }
}

class Bar {
    constructor(@Decorator() foo: string) {

    }
}
```

### 🙁 Actual behavior

TypeScript fails at compiling this code and throws the following compilation error for Foo and Foo1 classes:

> error TS1206: Decorators are not valid here.

Class Bar compiles successfully.

### 🙂 Expected behavior

Since

```js
class Foo {

}
```

and

```js
const Foo = class {

}
```

are equivalent syntaxes in ES6, using parameter decorators should be allowed for these two syntaxes.

**Comment by ericmorand** [comment]
To give a bit of context, allowing parameter decorators for anonymous classes would permit writing things like this in nestjs:

```ts
@Module({
    providers: [{
        provide: CatsService,
        useClass: class {
            constructor(@Inject(MyService) private readonly myService: MyServiceInterface) {
            }
        }
    }, MyService],
})
export class AppModule {
}
```

Instead of having to declare the class first and then assign it to `useClass`.

**Comment by RyanCavanaugh** [comment]
Duplicate #7342

**Comment by ericmorand** [comment]
Sorry about that. I close.
