### ISSUE TITLE
jsconfig.json not respecting the exclude directory.

### ISSUE THREAD

**Issue by roebuk** [microsoft/TypeScript#42797]
# Bug Report

### 🔎 Search Terms

jsconfig.json exclude
jsconfig.json node_modules

### 🕗 Version & Regression Information

tested typescript versions 4.0.0, 4.1.5, 4.3.0-dev.20210214

- This is a bug

### 💻 Code

There's a sample repo here https://github.com/roebuk/jsconfig-issue

Clone, install dependencies, then run the two different npm scripts:

```
"check-types-js": "tsc -p jsconfig.json",
"check-types-ts": "tsc -p tsconfig.json",
```

### 🙁 Actual behavior

Running `tsc -p jsconfig.json` should respect the `"exclude": ["node_modules"]` settings and not report errors within `node_modules`. 
```
../node_modules/url/url.js:729:41 - error TS2531: Object is possibly 'null'.

729     host = host.substr(0, host.length - port.length);
                                            ~~~~
Found 4325 errors.
```

### 🙂 Expected behavior

It should not report errors within node_modules, just like the running `tsc -p tsconfig.json`

**Comment by MartinJohns** [comment]
Imported files are always included, and I would guess that you indirectly import the url module via React. You can try running the CLI with the `--traceResolution` argument.

**Comment by roebuk** [comment]
Here's the initial output from `--traceResolution`. 

    > example@1.0.0 check-types-js
    > tsc -p jsconfig.json --traceResolution
    
    ======== Resolving module 'react' from 'example/src/Header.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module 'react' from 'node_modules' folder, target file type 'TypeScript'.
    Directory 'example/src/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/react/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/react.ts' does not exist.
    File 'example/node_modules/react.tsx' does not exist.
    File 'example/node_modules/react.d.ts' does not exist.
    'package.json' does not have a 'typings' field.
    'package.json' does not have a 'types' field.
    'package.json' has 'main' field 'index.js' that references 'example/node_modules/react/index.js'.
    File 'example/node_modules/react/index.js' exist - use it as a name resolution result.File 'example/node_modules/react/index.js' has an unsupported extension, so skipping it.
    Loading module as file / folder, candidate module location 'example/node_modules/react/index.js', target file type 'TypeScript'.
    File 'example/node_modules/react/index.js.ts' does not exist.
    File 'example/node_modules/react/index.js.tsx' does not exist.
    File 'example/node_modules/react/index.js.d.ts' does not exist.
    File name 'example/node_modules/react/index.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react/index.ts' does not exist.
    File 'example/node_modules/react/index.tsx' does not exist.
    File 'example/node_modules/react/index.d.ts' does not exist.
    Directory 'example/node_modules/react/index.js' does not exist, skipping all lookups in it.
    File 'example/node_modules/react/index.ts' does not exist.
    File 'example/node_modules/react/index.tsx' does not exist.
    File 'example/node_modules/react/index.d.ts' does not exist.
    File 'example/node_modules/@types/react.d.ts' does not exist.
    Directory 'node_modules' does not exist, skipping all lookups in it.
    File 'C:/Users/KristianRoebuck/node_modules/react.ts' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/react.tsx' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/react.d.ts' does not exist.
    Directory 'C:/Users/KristianRoebuck/node_modules/@types' does not exist, skipping all lookups in it.
    Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
    Directory 'C:/node_modules' does not exist, skipping all lookups in it.
    Loading module 'react' from 'node_modules' folder, target file type 'JavaScript'.
    Directory 'example/src/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/react/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/react.js' does not exist.
    File 'example/node_modules/react.jsx' does not exist.
    'package.json' has 'main' field 'index.js' that references 'example/node_modules/react/index.js'.
    File 'example/node_modules/react/index.js' exist - use it as a name resolution result.Resolving real path for 'example/node_modules/react/index.js', result 'example/node_modules/react/index.js'.
    ======== Module name 'react' was successfully resolved to 'example/node_modules/react/index.js' with Package ID 'react/index.js@17.0.1'. ========
    ======== Resolving module './cjs/react.production.min.js' from 'example/node_modules/react/index.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module as file / folder, candidate module location 'example/node_modules/react/cjs/react.production.min.js', target file type 'TypeScript'.
    File 'example/node_modules/react/cjs/react.production.min.js.ts' does not exist.
    File 'example/node_modules/react/cjs/react.production.min.js.tsx' does not exist.
    File 'example/node_modules/react/cjs/react.production.min.js.d.ts' does not exist.
    File name 'example/node_modules/react/cjs/react.production.min.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react/cjs/react.production.min.ts' does not exist.
    File 'example/node_modules/react/cjs/react.production.min.tsx' does not exist.
    File 'example/node_modules/react/cjs/react.production.min.d.ts' does not exist.
    Directory 'example/node_modules/react/cjs/react.production.min.js' does not exist, skipping all lookups in it.
    Loading module as file / folder, candidate module location 'example/node_modules/react/cjs/react.production.min.js', target file type 'JavaScript'.
    File 'example/node_modules/react/cjs/react.production.min.js.js' does not exist.
    File 'example/node_modules/react/cjs/react.production.min.js.jsx' does not exist.
    File name 'example/node_modules/react/cjs/react.production.min.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react/cjs/react.production.min.js' exist - use it as a name resolution result.
    Found 'package.json' at 'example/node_modules/react/package.json'.
    'package.json' does not have a 'typesVersions' field.
    ======== Module name './cjs/react.production.min.js' was successfully resolved to 'example/node_modules/react/cjs/react.production.min.js' with Package ID 'react/cjs/react.production.min.js@17.0.1'. ========
    ======== Resolving module './cjs/react.development.js' from 'example/node_modules/react/index.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module as file / folder, candidate module location 'example/node_modules/react/cjs/react.development.js', target file type 'TypeScript'.
    File 'example/node_modules/react/cjs/react.development.js.ts' does not exist.
    File 'example/node_modules/react/cjs/react.development.js.tsx' does not exist.
    File 'example/node_modules/react/cjs/react.development.js.d.ts' does not exist.
    File name 'example/node_modules/react/cjs/react.development.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react/cjs/react.development.ts' does not exist.
    File 'example/node_modules/react/cjs/react.development.tsx' does not exist.
    File 'example/node_modules/react/cjs/react.development.d.ts' does not exist.
    Directory 'example/node_modules/react/cjs/react.development.js' does not exist, skipping all lookups in it.
    Loading module as file / folder, candidate module location 'example/node_modules/react/cjs/react.development.js', target file type 'JavaScript'.
    File 'example/node_modules/react/cjs/react.development.js.js' does not exist.
    File 'example/node_modules/react/cjs/react.development.js.jsx' does not exist.
    File name 'example/node_modules/react/cjs/react.development.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react/cjs/react.development.js' exist - use it as a name resolution result.
    Found 'package.json' at 'example/node_modules/react/package.json'.
    'package.json' does not have a 'typesVersions' field.
    ======== Module name './cjs/react.development.js' was successfully resolved to 'example/node_modules/react/cjs/react.development.js' with Package ID 'react/cjs/react.development.js@17.0.1'. ========
    ======== Resolving module 'object-assign' from 'example/node_modules/react/cjs/react.production.min.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module 'object-assign' from 'node_modules' folder, target file type 'TypeScript'.
    Directory 'example/node_modules/react/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/object-assign/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/object-assign.ts' does not exist.
    File 'example/node_modules/object-assign.tsx' does not exist.
    File 'example/node_modules/object-assign.d.ts' does not exist.
    'package.json' does not have a 'typings' field.
    'package.json' does not have a 'types' field.
    'package.json' does not have a 'main' field.
    File 'example/node_modules/object-assign/index.ts' does not exist.
    File 'example/node_modules/object-assign/index.tsx' does not exist.
    File 'example/node_modules/object-assign/index.d.ts' does not exist.
    File 'example/node_modules/@types/object-assign.d.ts' does not exist.
    Directory 'node_modules' does not exist, skipping all lookups in it.
    File 'C:/Users/KristianRoebuck/node_modules/object-assign.ts' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/object-assign.tsx' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/object-assign.d.ts' does not exist.
    Directory 'C:/Users/KristianRoebuck/node_modules/@types' does not exist, skipping all lookups in it.
    Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
    Directory 'C:/node_modules' does not exist, skipping all lookups in it.
    Loading module 'object-assign' from 'node_modules' folder, target file type 'JavaScript'.
    Directory 'example/node_modules/react/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/object-assign/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/object-assign.js' does not exist.
    File 'example/node_modules/object-assign.jsx' does not exist.
    'package.json' does not have a 'main' field.
    File 'example/node_modules/object-assign/index.js' exist - use it as a name resolution result.
    Resolving real path for 'example/node_modules/object-assign/index.js', result 'example/node_modules/object-assign/index.js'.
    ======== Module name 'object-assign' was successfully resolved to 'example/node_modules/object-assign/index.js' with Package ID 'object-assign/index.js@4.1.1'. ========
    ======== Resolving module 'object-assign' from 'example/node_modules/react/cjs/react.development.js'. ========
    Resolution for module 'object-assign' was found in cache from location 'example/node_modules/react/cjs'.
    ======== Module name 'object-assign' was successfully resolved to 'example/node_modules/object-assign/index.js' with Package ID 'object-assign/index.js@4.1.1'. ========
    ======== Resolving module 'react' from 'example/src/index.js'. ========
    Resolution for module 'react' was found in cache from location 'example/src'.
    ======== Module name 'react' was successfully resolved to 'example/node_modules/react/index.js' with Package ID 'react/index.js@17.0.1'. ========
    ======== Resolving module 'react-dom' from 'example/src/index.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module 'react-dom' from 'node_modules' folder, target file type 'TypeScript'.
    Directory 'example/src/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/react-dom/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/react-dom.ts' does not exist.
    File 'example/node_modules/react-dom.tsx' does not exist.
    File 'example/node_modules/react-dom.d.ts' does not exist.
    'package.json' does not have a 'typings' field.
    'package.json' does not have a 'types' field.
    'package.json' has 'main' field 'index.js' that references 'example/node_modules/react-dom/index.js'.
    File 'example/node_modules/react-dom/index.js' exist - use it as a name resolution result.
    File 'example/node_modules/react-dom/index.js' has an unsupported extension, so skipping it.
    Loading module as file / folder, candidate module location 'example/node_modules/react-dom/index.js', target file type 'TypeScript'.
    File 'example/node_modules/react-dom/index.js.ts' does not exist.
    File 'example/node_modules/react-dom/index.js.tsx' does not exist.
    File 'example/node_modules/react-dom/index.js.d.ts' does not exist.
    File name 'example/node_modules/react-dom/index.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react-dom/index.ts' does not exist.
    File 'example/node_modules/react-dom/index.tsx' does not exist.
    File 'example/node_modules/react-dom/index.d.ts' does not exist.
    Directory 'example/node_modules/react-dom/index.js' does not exist, skipping all lookups in it.
    File 'example/node_modules/react-dom/index.ts' does not exist.
    File 'example/node_modules/react-dom/index.tsx' does not exist.
    File 'example/node_modules/react-dom/index.d.ts' does not exist.
    File 'example/node_modules/@types/react-dom.d.ts' does not exist.
    Directory 'node_modules' does not exist, skipping all lookups in it.
    File 'C:/Users/KristianRoebuck/node_modules/react-dom.ts' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/react-dom.tsx' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/react-dom.d.ts' does not exist.
    Directory 'C:/Users/KristianRoebuck/node_modules/@types' does not exist, skipping all lookups in it.
    Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
    Directory 'C:/node_modules' does not exist, skipping all lookups in it.
    Loading module 'react-dom' from 'node_modules' folder, target file type 'JavaScript'.
    Directory 'example/src/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/react-dom/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/react-dom.js' does not exist.
    File 'example/node_modules/react-dom.jsx' does not exist.
    'package.json' has 'main' field 'index.js' that references 'example/node_modules/react-dom/index.js'.
    File 'example/node_modules/react-dom/index.js' exist - use it as a name resolution result.
    Resolving real path for 'example/node_modules/react-dom/index.js', result 'example/node_modules/react-dom/index.js'.
    ======== Module name 'react-dom' was successfully resolved to 'example/node_modules/react-dom/index.js' with Package ID 'react-dom/index.js@17.0.1'. ========
    ======== Resolving module './cjs/react-dom.production.min.js' from 'example/node_modules/react-dom/index.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module as file / folder, candidate module location 'example/node_modules/react-dom/cjs/react-dom.production.min.js', target file type 'TypeScript'.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.js.ts' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.js.tsx' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.js.d.ts' does not exist.
    File name 'example/node_modules/react-dom/cjs/react-dom.production.min.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.ts' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.tsx' does not exist.File 'example/node_modules/react-dom/cjs/react-dom.production.min.d.ts' does not exist.
    Directory 'example/node_modules/react-dom/cjs/react-dom.production.min.js' does not exist, skipping all lookups in it.
    Loading module as file / folder, candidate module location 'example/node_modules/react-dom/cjs/react-dom.production.min.js', target file type 'JavaScript'.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.js.js' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.js.jsx' does not exist.
    File name 'example/node_modules/react-dom/cjs/react-dom.production.min.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react-dom/cjs/react-dom.production.min.js' exist - use it as a name resolution result.
    Found 'package.json' at 'example/node_modules/react-dom/package.json'.
    'package.json' does not have a 'typesVersions' field.
    ======== Module name './cjs/react-dom.production.min.js' was successfully resolved to 'example/node_modules/react-dom/cjs/react-dom.production.min.js' with Package ID 'react-dom/cjs/react-dom.production.min.js@17.0.1'. ========
    ======== Resolving module './cjs/react-dom.development.js' from 'example/node_modules/react-dom/index.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module as file / folder, candidate module location 'example/node_modules/react-dom/cjs/react-dom.development.js', target file type 'TypeScript'.
    File 'example/node_modules/react-dom/cjs/react-dom.development.js.ts' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.development.js.tsx' does not exist.File 'example/node_modules/react-dom/cjs/react-dom.development.js.d.ts' does not exist.
    File name 'example/node_modules/react-dom/cjs/react-dom.development.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react-dom/cjs/react-dom.development.ts' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.development.tsx' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.development.d.ts' does not exist.
    Directory 'example/node_modules/react-dom/cjs/react-dom.development.js' does not exist, skipping all lookups in it.
    Loading module as file / folder, candidate module location 'example/node_modules/react-dom/cjs/react-dom.development.js', target file type 'JavaScript'.
    File 'example/node_modules/react-dom/cjs/react-dom.development.js.js' does not exist.
    File 'example/node_modules/react-dom/cjs/react-dom.development.js.jsx' does not exist.File name 'example/node_modules/react-dom/cjs/react-dom.development.js' has a '.js' extension - stripping it.
    File 'example/node_modules/react-dom/cjs/react-dom.development.js' exist - use it as a name resolution result.
    Found 'package.json' at 'example/node_modules/react-dom/package.json'.
    'package.json' does not have a 'typesVersions' field.
    ======== Module name './cjs/react-dom.development.js' was successfully resolved to 'example/node_modules/react-dom/cjs/react-dom.development.js' with Package ID 'react-dom/cjs/react-dom.development.js@17.0.1'. ========
    ======== Resolving module 'react' from 'example/node_modules/react-dom/cjs/react-dom.production.min.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module 'react' from 'node_modules' folder, target file type 'TypeScript'.
    Directory 'example/node_modules/react-dom/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react-dom/node_modules' does not exist, skipping all lookups in it.
    Resolution for module 'react' was found in cache from location 'example'.
    ======== Module name 'react' was successfully resolved to 'example/node_modules/react/index.js' with Package ID 'react/index.js@17.0.1'. ========
    ======== Resolving module 'object-assign' from 'example/node_modules/react-dom/cjs/react-dom.production.min.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module 'object-assign' from 'node_modules' folder, target file type 'TypeScript'.
    Directory 'example/node_modules/react-dom/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react-dom/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/object-assign/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/object-assign.ts' does not exist.
    File 'example/node_modules/object-assign.tsx' does not exist.
    File 'example/node_modules/object-assign.d.ts' does not exist.
    'package.json' does not have a 'typings' field.
    'package.json' does not have a 'types' field.
    'package.json' does not have a 'main' field.
    File 'example/node_modules/object-assign/index.ts' does not exist.
    File 'example/node_modules/object-assign/index.tsx' does not exist.
    File 'example/node_modules/object-assign/index.d.ts' does not exist.
    File 'example/node_modules/@types/object-assign.d.ts' does not exist.
    Directory 'node_modules' does not exist, skipping all lookups in it.
    File 'C:/Users/KristianRoebuck/node_modules/object-assign.ts' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/object-assign.tsx' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/object-assign.d.ts' does not exist.
    Directory 'C:/Users/KristianRoebuck/node_modules/@types' does not exist, skipping all lookups in it.
    Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
    Directory 'C:/node_modules' does not exist, skipping all lookups in it.
    Loading module 'object-assign' from 'node_modules' folder, target file type 'JavaScript'.
    Directory 'example/node_modules/react-dom/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react-dom/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/object-assign/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/object-assign.js' does not exist.
    File 'example/node_modules/object-assign.jsx' does not exist.
    'package.json' does not have a 'main' field.
    File 'example/node_modules/object-assign/index.js' exist - use it as a name resolution result.
    Resolving real path for 'example/node_modules/object-assign/index.js', result 'example/node_modules/object-assign/index.js'.
    ======== Module name 'object-assign' was successfully resolved to 'example/node_modules/object-assign/index.js' with Package ID 'object-assign/index.js@4.1.1'. ========
    ======== Resolving module 'scheduler' from 'example/node_modules/react-dom/cjs/react-dom.production.min.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module 'scheduler' from 'node_modules' folder, target file type 'TypeScript'.
    Directory 'example/node_modules/react-dom/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react-dom/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/scheduler/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/scheduler.ts' does not exist.
    File 'example/node_modules/scheduler.tsx' does not exist.
    File 'example/node_modules/scheduler.d.ts' does not exist.
    'package.json' does not have a 'typings' field.
    'package.json' does not have a 'types' field.
    'package.json' has 'main' field 'index.js' that references 'example/node_modules/scheduler/index.js'.
    File 'example/node_modules/scheduler/index.js' exist - use it as a name resolution result.
    File 'example/node_modules/scheduler/index.js' has an unsupported extension, so skipping it.
    Loading module as file / folder, candidate module location 'example/node_modules/scheduler/index.js', target file type 'TypeScript'.
    File 'example/node_modules/scheduler/index.js.ts' does not exist.
    File 'example/node_modules/scheduler/index.js.tsx' does not exist.
    File 'example/node_modules/scheduler/index.js.d.ts' does not exist.
    File name 'example/node_modules/scheduler/index.js' has a '.js' extension - stripping it.
    File 'example/node_modules/scheduler/index.ts' does not exist.
    File 'example/node_modules/scheduler/index.tsx' does not exist.
    File 'example/node_modules/scheduler/index.d.ts' does not exist.
    Directory 'example/node_modules/scheduler/index.js' does not exist, skipping all lookups in it.
    File 'example/node_modules/scheduler/index.ts' does not exist.
    File 'example/node_modules/scheduler/index.tsx' does not exist.
    File 'example/node_modules/scheduler/index.d.ts' does not exist.
    File 'example/node_modules/@types/scheduler.d.ts' does not exist.
    Directory 'node_modules' does not exist, skipping all lookups in it.
    File 'C:/Users/KristianRoebuck/node_modules/scheduler.ts' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/scheduler.tsx' does not exist.
    File 'C:/Users/KristianRoebuck/node_modules/scheduler.d.ts' does not exist.
    Directory 'C:/Users/KristianRoebuck/node_modules/@types' does not exist, skipping all lookups in it.
    Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
    Directory 'C:/node_modules' does not exist, skipping all lookups in it.
    Loading module 'scheduler' from 'node_modules' folder, target file type 'JavaScript'.
    Directory 'example/node_modules/react-dom/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react-dom/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/scheduler/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/scheduler.js' does not exist.
    File 'example/node_modules/scheduler.jsx' does not exist.
    'package.json' has 'main' field 'index.js' that references 'example/node_modules/scheduler/index.js'.
    File 'example/node_modules/scheduler/index.js' exist - use it as a name resolution result.
    Resolving real path for 'example/node_modules/scheduler/index.js', result 'example/node_modules/scheduler/index.js'.
    ======== Module name 'scheduler' was successfully resolved to 'example/node_modules/scheduler/index.js' with Package ID 'scheduler/index.js@0.20.1'. ========
    ======== Resolving module 'react' from 'example/node_modules/react-dom/cjs/react-dom.development.js'. ========
    Resolution for module 'react' was found in cache from location 'example/node_modules/react-dom/cjs'.
    ======== Module name 'react' was successfully resolved to 'example/node_modules/react/index.js' with Package ID 'react/index.js@17.0.1'. ========
    ======== Resolving module 'object-assign' from 'example/node_modules/react-dom/cjs/react-dom.development.js'. ========
    Resolution for module 'object-assign' was found in cache from location 'example/node_modules/react-dom/cjs'.
    ======== Module name 'object-assign' was successfully resolved to 'example/node_modules/object-assign/index.js' with Package ID 'object-assign/index.js@4.1.1'. ========
    ======== Resolving module 'scheduler' from 'example/node_modules/react-dom/cjs/react-dom.development.js'. ========
    Resolution for module 'scheduler' was found in cache from location 'example/node_modules/react-dom/cjs'.
    ======== Module name 'scheduler' was successfully resolved to 'example/node_modules/scheduler/index.js' with Package ID 'scheduler/index.js@0.20.1'. ========
    ======== Resolving module 'scheduler/tracing' from 'example/node_modules/react-dom/cjs/react-dom.development.js'. ========
    Module resolution kind is not specified, using 'NodeJs'.
    Loading module 'scheduler/tracing' from 'node_modules' folder, target file type 'TypeScript'.
    Directory 'example/node_modules/react-dom/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react-dom/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/scheduler/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/scheduler/tracing.ts' does not exist.
    File 'example/node_modules/scheduler/tracing.tsx' does not exist.
    File 'example/node_modules/scheduler/tracing.d.ts' does not exist.
    'package.json' does not have a 'typings' field.
    'package.json' does not have a 'types' field.
    'package.json' has 'main' field 'index.js' that references 'example/node_modules/scheduler/tracing/index.js'.
    Loading module as file / folder, candidate module location 'example/node_modules/scheduler/tracing/index.js', target file type 'TypeScript'.
    File name 'example/node_modules/scheduler/tracing/index.js' has a '.js' extension - stripping it.
    Directory 'node_modules' does not exist, skipping all lookups in it.
    Directory 'C:/Users/KristianRoebuck/node_modules/@types' does not exist, skipping all lookups in it.
    Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
    Directory 'C:/node_modules' does not exist, skipping all lookups in it.
    Loading module 'scheduler/tracing' from 'node_modules' folder, target file type 'JavaScript'.
    Directory 'example/node_modules/react-dom/cjs/node_modules' does not exist, skipping all lookups in it.
    Directory 'example/node_modules/react-dom/node_modules' does not exist, skipping all lookups in it.
    Found 'package.json' at 'example/node_modules/scheduler/package.json'.
    'package.json' does not have a 'typesVersions' field.
    File 'example/node_modules/scheduler/tracing.js' exist - use it as a name resolution result.
    Resolving real path for 'example/node_modules/scheduler/tracing.js', result 'example/node_modules/scheduler/tracing.js'.
    ======== Module name 'scheduler/tracing' was successfully resolved to 'example/node_modules/scheduler/tracing.js' with Package ID 'scheduler/tracing.js@0.20.1'. ========
    ======== Resolving type reference directive 'q', containing file 'example/__inferred type names__.ts', root directory 'example/node_modules/@types'. ========
    Resolving with primary search path 'example/node_modules/@types'.
    Found 'package.json' at 'example/node_modules/@types/q/package.json'.
    'package.json' does not have a 'typesVersions' field.
    'package.json' does not have a 'typings' field.
    'package.json' has 'types' field 'index.d.ts' that references 'example/node_modules/@types/q/index.d.ts'.
    File 'example/node_modules/@types/q/index.d.ts' exist - use it as a name resolution result.
    Resolving real path for 'example/node_modules/@types/q/index.d.ts', result 'example/node_modules/@types/q/index.d.ts'.
    ======== Type reference directive 'q' was successfully resolved to 'example/node_modules/@types/q/index.d.ts' with Package ID '@types/q/index.d.ts@1.5.4', primary: true. ========

**Comment by RyanCavanaugh** [comment]
In 4.2+ you can also run `tsc --explainListFiles`

**Comment by roebuk** [comment]
I've run with `tsc --explainFiles` and this is my output when pointing to `jsconfig.json`


    node_modules/typescript/lib/lib.d.ts
      Default library
    node_modules/typescript/lib/lib.es5.d.ts
      Library referenced via 'es5' from file 'node_modules/typescript/lib/lib.d.ts'
    node_modules/typescript/lib/lib.dom.d.ts
      Library referenced via 'dom' from file 'node_modules/typescript/lib/lib.d.ts'
    node_modules/typescript/lib/lib.webworker.importscripts.d.ts
      Library referenced via 'webworker.importscripts' from file 'node_modules/typescript/lib/lib.d.ts'
    node_modules/typescript/lib/lib.scripthost.d.ts
      Library referenced via 'scripthost' from file 'node_modules/typescript/lib/lib.d.ts'
    node_modules/react/cjs/react.production.min.js
      Imported via './cjs/react.production.min.js' from file 'node_modules/react/index.js' with packageId 'react/cjs/react.production.min.js@17.0.1'
    node_modules/react/cjs/react.development.js
      Imported via './cjs/react.development.js' from file 'node_modules/react/index.js' with packageId 'react/cjs/react.development.js@17.0.1'
    node_modules/react/index.js
      Imported via 'react' from file 'src/Header.js' with packageId 'react/index.js@17.0.1'
      Imported via 'react' from file 'src/index.js' with packageId 'react/index.js@17.0.1'
    src/Header.js
      Matched by include pattern 'src' in 'jsconfig.json'
    node_modules/react-dom/cjs/react-dom.production.min.js
      Imported via './cjs/react-dom.production.min.js' from file 'node_modules/react-dom/index.js' with packageId 'react-dom/cjs/react-dom.production.min.js@17.0.1'
    node_modules/react-dom/cjs/react-dom.development.js
      Imported via './cjs/react-dom.development.js' from file 'node_modules/react-dom/index.js' with packageId 'react-dom/cjs/react-dom.development.js@17.0.1'
    node_modules/react-dom/index.js
      Imported via 'react-dom' from file 'src/index.js' with packageId 'react-dom/index.js@17.0.1'
    src/index.js
      Matched by include pattern 'src' in 'jsconfig.json'
    node_modules/@types/q/index.d.ts
      Entry point for implicit type library 'q' with packageId '@types/q/index.d.ts@1.5.4'



And this is the output when pointing to a `tsconfig.json`

    node_modules/typescript/lib/lib.d.ts
      Default library
    node_modules/typescript/lib/lib.es5.d.ts
      Library referenced via 'es5' from file 'node_modules/typescript/lib/lib.d.ts'
    node_modules/typescript/lib/lib.dom.d.ts
      Library referenced via 'dom' from file 'node_modules/typescript/lib/lib.d.ts'
    node_modules/typescript/lib/lib.webworker.importscripts.d.ts
      Library referenced via 'webworker.importscripts' from file 'node_modules/typescript/lib/lib.d.ts'
    node_modules/typescript/lib/lib.scripthost.d.ts
      Library referenced via 'scripthost' from file 'node_modules/typescript/lib/lib.d.ts'
    src/Header.js
      Matched by include pattern 'src' in 'tsconfig.json'
    src/index.js
      Matched by include pattern 'src' in 'tsconfig.json'
    node_modules/@types/q/index.d.ts
      Entry point for implicit type library 'q' with packageId '@types/q/index.d.ts@1.5.4'

**Comment by roebuk** [comment]
Please don't close an in progress ticket.

**Comment by markcellus** [comment]
This issue is closed but is still happening, even when the project has only a jsconfig.json file. I've refiled in https://github.com/microsoft/TypeScript/issues/50862.

**Comment by Ciantic** [comment]
This is a first result when searching, the solution is this: 

> You're seeing this weird behavior because jsconfig.json sets the `maxNodeModuleJsDepth` option to 2 (tsconfig.json default is 0).

It's explained in the #50862 better, but solution is simply: add property to jsconfig.json

```json5
{
  "compilerOptions": {
    "checkJs": true,
    "strict": true,
    "module": "CommonJS",
    "resolveJsonModule": true,
    "maxNodeModuleJsDepth": 0 // <--- ADD THIS
  },
```
