### ISSUE TITLE
TS not able to infer that T[PropsThatExtend<T, M>] extends M

### ISSUE THREAD

**Issue by Flonk** [microsoft/TypeScript#42795]
# Bug Report

### 🔎 Search Terms

- type inference
- mapped type
- conditional types

### 🕗 Version & Regression Information

All versions I tested.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/C4TwDgpgBACgTgezAZwCoAsCGwCiAPYCAOwBMAeVAGigFkA+KAXigG8AoKKAbQGkoBLIlADWEEAgBmUVAF0AXNN4yoEAsRLJaUAPxQ+CohABuEOAG42AXy6jxU2RbYBjBEWTAByAGIIArnCYoCko6AAoEACMAKwUqKDBEMAV4JDQsXDVSYKgiXwBbCNM6AEomBnZOOAhgfyFIqK4EpGVGVqgAFgtLNjZQSCgfBECKqAjMOAN8wvMOUcwAL0mC0ygAHyh3OEEAcwtOAEdfPAUAJjWOrscAegAqWES07HxCLMHqXOW4BlbmACIxuC-c6-Q54X5mKA3K49fjePxwUIsOYTKAARmoY0WUBO1FBCnaUEsUEwmjeUBBR1+xTMQA)

### 💻 Code

```ts
type PropsThatExtend<T, M> = {
  [K in keyof T]: T[K] extends M ? K : never;
}[keyof T];

const isFour = <T,>(obj: T, prop: PropsThatExtend<T, number>) => {
  return obj[prop] === 4;
}

type Foo = {
  bar: number;
  baz: number | string;
  qux: 2 | 4;
};

/* PropsThatExtend<Foo, number> === "bar" | "qux"; */

isFour({ bar: 1, baz: 2, qux: 4 } as Foo, "qux");
```

### 🙁 Actual behavior

Error on line 6:
`This condition will always return 'false' since the types 'T[PropsThatExtend<T, number>]' and 'number' have no overlap.`

### 🙂 Expected behavior

Since all members in `T[PropsThatExtend<T, number>]` extend `number` the compiler should be able to recognize that the two types being compared overlap.

**Comment by jcalz** [comment]
Duplicate #30728
