### ISSUE TITLE
noImplicitAny bypass in generic object methods

### ISSUE THREAD

**Issue by chmln** [microsoft/TypeScript#42799]
# Bug Report

### 🔎 Search Terms

- noimplicitany rest parameters
- rest parameters infer any
- infer any

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this issue

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=4.1.3#code/C4TwDgpgBAshwAsD2ATAzlAvFAShAxkgE4oA8awRAlgHYDmANFABQBmVRFAgkXQFxQaAVwC2AIwhEmAOllEIFAQEMaIANoBdAJRYAfINESiugFAnCNClGALgAMSE18WKKRhQIADxs10seMjouswiAahoAjA6mPoA3gC+ZjYUDk7MsSZQUKyO+ACMAszCIkwA7ghKNgBuktFxmVlQ8sBCRDRQ5ZUQNUQA3A2J8VpAA)

### 💻 Code

```ts
type Methods = Record<string, (firstArg: number, ...rest: any[]) => number>

const testFunc = <M extends Methods>(methods: M) => {}

testFunc({
  func1: (num, whatever) => {
    return whatever;
  }
})
```

### 🙁 Actual behavior

`whatever` is left untyped despite `noImplicitAny` and satisfies the `number` return type, completely killing type safety.

### 🙂 Expected behavior

`whatever` requires a type because `noImplicitAny` is turned on.

**Comment by MartinJohns** [comment]
But it's not implicit. It's specified right in your first line.

**Comment by chmln** [comment]
The intention here is to restrict `Methods` to functions that return a number.

I found the behavior of rest params here surprising. Just because a function is specified to extend `(..args: any[]) => number` shouldn't mean that its arguments are explicitly specified as `any`.

Are there any workarounds for this ?

**Comment by MartinJohns** [comment]
> The intention here is to restrict Methods to functions that return a number.

This is the case by having the return type specified as `number`. However, the type `any` is an escape-hatch from the type system.

> Just because a function is specified to extend `(..args: any[]) => number` shouldn't mean that its arguments are explicitly specified as `any`.

It **exactly** means that. Or differently said: You don't have type information available for those arguments, so they're `any`.

> Are there any workarounds for this ?

Adjust your types to what you actually want. Use `(firstArg: number) => number` instead.

**Comment by RyanCavanaugh** [comment]
An argument with a contextual type of `any` is not considered an implicit `any`.

**Comment by chmln** [comment]
> Adjust your types to what you actually want. Use (firstArg: number) => number instead.

@MartinJohns I need the function to be variadic. As long as it e.g returns a number I want to place no restrictions on types and number of parameters used.

@RyanCavanaugh thanks for chiming in. I totally understand that viewpoint. 

However there appears to be no mechanism to restrict functions by return type, without also allowing this free-for-all with `any[]`. I have tried using `unknown`, `never`, but to no avail. 

Is there a way to accomplish this?

**Comment by RyanCavanaugh** [comment]
You could rewrite this to make the parameters bivariant:
```ts
type Methods = Record<string, { (firstArg: number, ...rest: unknown[]): number }>

const testFunc = <M extends Methods>(methods: M) => {}

testFunc({
  func1: (num, whatever) => {
    return whatever;
  }
})
```
Ultimately the requested behavior isn't usable in any sound way, so it's not going to be straightforward to get this.
