### ISSUE TITLE
Templated string literal type as key looses type when using non enumerable types like ${number} or ${string} in template

### ISSUE THREAD

**Issue by rpedretti** [microsoft/TypeScript#42796]
# Bug Report

### 🔎 Search Terms

template literal string type
indexed array type

### 🕗 Version & Regression Information

- Versions 4.1+

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3&ssl=2&ssc=36&pln=2&pc=43#code/C4TwDgpgBAygrgIwCrmgXigcgIaagHywUwChRIokIBbMAG22AhQowCUIBjAewCcATADwADAM6IA+gG0AJAG94yVAF8AusIA0UAHZxqCCLwB8JAPQAqMqko16jZtYxySUV1ABE4hNOyr3ALh09A14Abhc3T0kpBD9A3X1DcOUSc1MSKwoAeWAAC0MWdCgOHgERbjzDaXkEbm46CGxtNU0gxOMzS3JoHPzeQqgnCNd3Cr7pADNsOlEIOLaQ8LcPMaqpYF44OYCFpJIUtIzuqCyAd21RAfYuPiFhbnPRWTkEkJatV8MTU1MTx6uoHIUploABhXJNADmEEESCMgygggAYlAIAAPJjafiiKAAawgIG4E0oRgAFGBeNwwIEkVoAG7TLaBJBSJGqACUg3hdO4AEt+OESDwLsAoJwIdpoYFwVCYVRaAwmAMAGR-C4qk6VfqoeEYcmUsD0xkQTloeHC0T1CAAOn4EAQcEh+qpRroW3ZgvFstJo0eUgADH4tJhMB6hRLoT7VrxJtNZkGsKHwl7JRAfV4fAmQ2GgA)

### 💻 Code

```ts
type SubType = 'a' | 'b'
type TemplateType = Record<`sub_[${SubType}]`, number>
/*
type TemplateType = {
    "sub_[a]": number;
    "sub_[b]": number;
}
*/

type OtherType = Record<`other_[${boolean}]`, number>
/*
type OtherType = {
    "other_[false]": number;
    "other_[true]": number;
}
*/

type OwnsType = Record<`owns[${number}]`, number>
// OwnsType = {}

type Change<T> = <F extends keyof T>(prop: F, value: T[F]) => void;

const change: Change<TemplateType & OwnsType & OtherType> = (prop, value) => console.debug(prop, value);

change("owns[0]", '');
change("other_[false]", '');
change("sub_[a]", '');

```

### 🙁 Actual behavior

Having a templated string literal type looses type when using non enumerable types like `${number}` or `${string}` in template

### 🙂 Expected behavior

Templated literal string should resolve to actual type

I don't know if this is intended since it's not possible to enumerate keys for these kind of template but it would be a nice feature

**Comment by jcalz** [comment]
Duplicate #42192

**Comment by yogeshpanchal8195** [comment]
I can resolve this issue at a faster pace & with a better approch
