### ISSUE TITLE
Type inference doesn't work with classes

### ISSUE THREAD

**Issue by tsapko3628** [microsoft/TypeScript#42801]
# Bug Report

Type inference doesn't work with classes but works with types correctly.

### 🕗 Version & Regression Information

typescript: 4.1.2

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/JYOwLgpgTgZghgYwgAgOrDACwEoQM4CuANmADy6EnIC8ycIAngHzIDeAvgNwBQYDADigrEwAFQERSACXoATIhADCAewC2quS1oyQ8pWo27kEAB6RdeNBhz4RpUDGjJhJFgH5ntqgC5kICABu0DygkLCIKCrqcuReYDR0jCym5rKW6FguZFksHNy8EshRclkJuAjKULKkeGBQoADmADR+BKoARtBMPAhEcHiWAKImcKr8ClGGssjAYwqqEOCWkzHFujls7PkVILXIUHG+WeKCpMOj4-rRulrIAOR3PEA)
### 💻 Code

```ts
interface WithResult<Result = any> {};
type ResultType<HandleCommand> = HandleCommand extends WithResult<infer Result> ? Result : never;
interface Command<Result = any> extends WithResult<Result> {}

type ComandResult = Record<string, number>;
class ExampleClassCommand implements Command<ComandResult> {}

const classResult: ResultType< ExampleClassCommand > = '';


type ExampleTypeCommand = Command<ComandResult>;

const typeResult: ResultType< ExampleTypeCommand > = ''; // error: '' is not assignable to  Record<string, number>
```

### 🙁 Actual behavior

```ts
typeof classResult === unknown;
```

### 🙂 Expected behavior

```ts
typeof classResult === Record<string, number>;
error: '' is not assignable to  Record<string, number>
```

**Comment by MartinJohns** [comment]
[Why do these empty classes behave strangely?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely)

**Comment by tsapko3628** [comment]
Thank you! I found resolution. I put here link with it, for people.
Please, close this issue.

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBAgjAvDAygTwLYCMQBsAUAlANwBQwuAhhBDAOoCWUAFgEoCmEArrlADwduvJDEpg0APhgBvUjHkwA2nAC6ALhiCeUMgF9SUNAAd2mztoAqx9nwASYgCa52AYRAYMjqcntgnr908-GHYADyh2P1pGFi1ePgYwADN2ACczISgpAH4M7RgNMHYANzSyCmpaNw9HAXNhZDFJEPDIh2imNnr+OKyZfQNrGGrHXpEOUFSHPmhUxIBzABoYMC5sNIlyqhoYAFFQygwjZ2qghxgGI+cMSKgqwNqRv16paQHQSFhU7o1eqxM+PtDscAjU-N4YABySFkIA)
