### ISSUE TITLE
This PR doesn't have any linked issues. Please open an issue that references this PR. From there we can discuss and prioritise.

### ISSUE THREAD

**Issue by khashayarnazari** [microsoft/TypeScript#42803]
This PR doesn't have any linked issues. Please open an issue that references this PR. From there we can discuss and prioritise.

_Originally posted by @typescript-bot in https://github.com/microsoft/TypeScript/issues/42611#issuecomment-771815539_

**Comment by RyanCavanaugh** [comment]
The bot shouldn't complain at itself
