### ISSUE TITLE
When watching a file, watch the config too!

### ISSUE THREAD

**Issue by chuacw** [microsoft/TypeScript#42800]
# Suggestion

When watching a file, watch the corresponding tsconfig.json too!

## 🔍 watch, tsconfig.json

watch tsconfig.json

My suggestion meets these guidelines:

 [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
 [*] This wouldn't change the runtime behavior of existing JavaScript code
 [*] This could be implemented without emitting different JS based on the types of the expressions
 [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

## ⭐ Suggestion

When a file is being watched, if its tsconfig.json has been updated, TypeScript should look at the configuration and check if any options that affected the output has been updated, if so, it should recompile the watched file.

**Comment by MartinJohns** [comment]
This is already happening.

**Comment by RyanCavanaugh** [comment]
Not sure what's being described here. Please give complete steps in a new issue if the above response didn't address your problem.
