### ISSUE TITLE
React/JSX-based code actions don't ignore whitespace

### ISSUE THREAD

**Issue by lostfictions** [microsoft/TypeScript#42829]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.3.0-dev.20210216

**Search Terms**
- code action
- quick fix
- jsx 

---

Issue Type: <b>Bug</b>

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:43:50.597Z)
OS version: Linux x64 5.8.0-41-generic

For code actions that apply to blocks, leading and trailing whitespace is typically ignored:

![Peek 2021-02-11 23-29](https://user-images.githubusercontent.com/567041/107730293-0008d980-6cc1-11eb-8bd4-a87abd149b20.gif)

However, for code actions that apply to React/JSX blocks, this does not appear to be the case:

![Peek 2021-02-11 23-24](https://user-images.githubusercontent.com/567041/107729991-5295c600-6cc0-11eb-810e-2af5493560eb.gif)

Note in the above image that selecting the block does not appear to be sufficient; the selection has to be at the start of the JSX tag for the code actions to become available.

This seems like a pretty unfortunate usability and discoverability issue -- at first I wasn't certain whether JSX refactorings were completely broken!

---

### Expected behaviour

Code actions that apply to JSX within a selection will be displayed regardless of leading and trailing whitespace in the selection. This matches the behaviour of code actions that apply to non-JSX JavaScript and TypeScript code, including within a JSX/TSX file (for example, refactoring a block to a new function in module scope).

### Actual behaviour

Code actions for JSX are only shown when the beginning of the selection is at the start of the relevant block of JSX. Trailing whitespace seems to be permissible.

### To reproduce

I've created a minimal repro case here: https://github.com/lostfictions/vscode-jsx-actions-repro.

To reproduce the issue:

1. Clone the repo.
2. Enter the repo directory and run `npm install`.
3. Run `code --user-data-dir /tmp/code-user-tmp --extensions-dir /tmp/code-ext-tmp .` for a Code instance with a fresh profile and all extensions disabled.
4. Open `src/index.tsx`.
5. Select lines 4 to 10, including all leading whitespace. The code action icon will display, and if clicked will offer refactorings:
    ![image](https://user-images.githubusercontent.com/567041/107837156-ad392b80-6d6d-11eb-98b6-0f1c43e37c08.png)
6. Select lines 15 to 19, including all leading whitespace. The code action icon will not display:
    ![image](https://user-images.githubusercontent.com/567041/107837301-4405e800-6d6e-11eb-9784-66b9d90fe533.png)
7. Select lines 15 to 19, but this time ensure the selection begins at line 15 at the first non-whitespace character, the `<` in `<div>`. This time the code action icon will display as normal and offer the expected refactorings:
    ![image](https://user-images.githubusercontent.com/567041/107837279-26388300-6d6e-11eb-9a28-55a3ab6d0896.png)

---

For convenience, here are the listings for `index.tsx`, `tsconfig.json`, and `package.json` in the above example:

`index.tsx`:

```tsx
import React from 'react';

export function NormalFunctionThatDoesNotExhibitIssue() {
  if(true) {
    for(let i=0;i<100;i++) {
      console.log('doing some work...', i)
    }
  }

  
}

export default function ComponentThatExhibitsIssue() {
  return <div>
    <div className="some-nested-data">
      hello from my nested component
    </div>

    
  </div>
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "esnext",
    "esModuleInterop": true,
    "jsx": "preserve",
    "strict": true
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

`package.json`:

```json
{
  "name": "vscode-jsx-actions-repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "typescript": "^4.1.5"
  }
}
```

**Comment by jessetrinity** [comment]
Nice repro! The whitespace before and after the div tag is technically JSX text so it doesn't get ignored like normal whitespace like it does in the `if` statement example. There happens to be special handling for whitespace only JSX text at the end of the span which is why it gets ignored there. It seems like we should add something similar at the beginning as well.
