### ISSUE TITLE
Loss of type inference after assignment

### ISSUE THREAD

**Issue by zkldi** [microsoft/TypeScript#42821]
# Bug Report

### 🔎 Search Terms

Loss of type information, Forgotten type inference.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about common bugs that aren't bugs.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/DYUwLgBAHgXBCuA7A1og9gd0RAvBARAGZpr4DcAUBQJaEQAUYAngA4hp1S4574DOYAE7VEAc3wBKCAG8KEeRAD0iiMzZ8AxsJaR0GCKkx9VACwCGkMCerGbEMxAHCxEQoLQBbCCMIhBIRA0QADoqBQhQSCY4JxFRXGhKOQVlCH8PNAA3EFMcwmpBAQgNc0EzDTA-CA5cxyE45PkuPChgvngAI1ixegBGCSTw1K47PQQUPUQAfkaIJgSoSgBfIA)

### 💻 Code

```ts
let x: unknown = "foo";

if (typeof x === "string") {
    // typescript now knows that this is a string from inference.
    let y: string = x;

    // perform any assignment to x;
    // I found this by calling x = x.substring(1), but it appears just reassigning x works.
    x = x;

    // similarly; x = "bar" still results in x being unknown. Any assignment to x results in the type inference being forgotten.

    // x is now unknown?
    // Type 'unknown' is not assignable to type 'string'.(2322)
    y = x;
}
```

### 🙁 Actual behavior

Typescript correctly infers that x is a string if ``typeof x === "string"``, however, it seems to forget this if x is assigned to, including trivial assignments.

### 🙂 Expected behavior

x is inferred to be a string, so x = x should be a no-op -> x should still be a string. This issue in and of itself is not too important, but any assigment to x (including ones that guaranteeably return a string, like `x = x.substring(1)` also causes TS to forget its type inference.)

I apologise if this is known or not a bug, I could not find anything similar reported on the issue tracker.

**Comment by zkldi** [comment]
More information: This seems to only happen with `x: unknown`. This does not happen with other cases of type inference, such as when `x: string | number`, or even `x: any`. This is presumably a bug with `unknown`.

**Comment by RyanCavanaugh** [comment]
See #27706
