### ISSUE TITLE
Incorrect multiline enum parsing

### ISSUE THREAD

**Issue by fedeci** [microsoft/TypeScript#42822]
# Bug Report

### 🔎 Search Terms

- `multiline enum`
- `line break enum`
- `enum parsing`

### 🕗 Version & Regression Information

I don't think this is a regression. 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgUAYgBAbynOAzA9ugNMuAjAQwCcoBfKKUSKAFSiRQ210JNKA)

### 💻 Code

```ts
enum
E 
{
  foo,
  bar
}
```
```ts
enum
F {
  foo,
  bar
}
```

### 🙁 Actual behavior
These declarations are parsed as valid `enum` declarations.
### 🙂 Expected behavior
`enum` declarations containing a line break between the `enum` keyword and the identifier should be parsed as multiple expressions.

```diff
- EnumDeclaration
+ ExpressionStatement: Identifier: enum
+ ExpressionStatement: Identifier: E
+ Block
```

### Linked issues
babel/babel#12773, babel/babel#12776
Also consider: https://github.com/babel/babel/pull/12776#discussion_r577123079
/cc @armano2 @JLHwung @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
I don't think that this is a bug: `enum` is a reserved word (and not a valid identifier), so there is no ambiguity allowing a line terminator.

**Comment by DanielRosenwasser** [comment]
Correct, this is working as intended.
