### ISSUE TITLE
Code that depends on declared variable typechecks, breaks when variable is implemented

### ISSUE THREAD

**Issue by masaeedu** [microsoft/TypeScript#42832]
# Bug Report

### 🔎 Search Terms

Declarations, narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about declarations

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAqBlAolK0A8AtgM4DmcoMwAdgCbFzExQCW1pAfHALxwDeAKDjCEyYBgDGrMDBx4oALjglSAbiEiWhAIak22qIiXVgAN2BR1AX3UDQkWHAkRqTOKZi6ecDIkIAjCAAbAAoAIg9dMIBKW3toeCQUOAA1AxZtahgAeQAzfCguXkEROABtAGs4NjgK4EQIXLgoAF0lPnLI0jba1XdtIIBXYCUoSpa4GwErSvrG5pa48ATRZIAlYBhBqFc8-AliIv4NYUrq6lq5poOeg-GKECo6BhCWYzMLaJ4uNlyLOAgJzgAH4AUClJg5AQwlhtBIABZObTEVA1bRIlFwTIDRDEFgMebo0zpTLwQiDNz+VDo3KDagSGAsFxhDjWWy0YASIIGVDOVxk7QwBFKfAQGRM1wAGgxwAYlBo9H45SqNTqDSaYsZLmIPVeSk1EuI4y+3C4dIq1AgAHcLlYOCFiUMRqkSVk9gbtRxpRJkbKlD6UcQTVw0qxSXsNlsdsQ9gHZRxWQIBByuTynNrErKYABGJShjJu-IdXIQCBKJisdjS-wGYyDAL-O1JvluKCywZBHPeHRC+EhKhMbPS4ul8vfRgAOiCNFIMHh1drcAupqXk2iE8dwzgAHpt3A6w2oNKAOKl2gAQmbGYQWYATHnXTki3AS2XGMw2KQF4ol-WqVBJiODoyi6HoAHIaygMDpU3Z1swABkmK9+WadtO1vbtBQRfs72HF9R0YcdiCnGc52-Yxx1tL5d1WVALHkYhpQAIW0C8gA)

### 💻 Code

```ts
export type TSError<msg extends string> = {
    typeScriptError: msg;
    imaginary: never;
};

export const vtag = Symbol("vtag");

export type VariantOf<r> = {
    [k in keyof r]: { [vtag]: k; value: r[k] };
}[keyof r];

export type ReturnsOf<cs> = {
    [k in keyof cs]: cs[k] extends (i: never) => infer o
    ? o
    : TSError<"Each case in a case analysis of a variant must be a function">;
};

declare const match: <options, cases extends { [k in keyof options]: (i: options[k]) => unknown }>(value: VariantOf<options>, cases: cases) => VariantOf<ReturnsOf<cases>>;

declare const test1: VariantOf<{ foo: string, bar: number }>

const result1 = match(test1, { foo: s => s.length, bar: n => n }).value // : number, Good!

const test2: VariantOf<{ foo: string, bar: number }> = { [vtag]: 'bar', value: 10 }

const result2 = match(test2, { foo: s => s.length, bar: n => n }) // type errors, Bad!
```

### 🙁 Actual behavior

The last line has type errors.

### 🙂 Expected behavior

The last line should have no type errors, and the type of `result2` should be the same as that of `result1`, i.e. `number`. The inputs in each case (`test1` and `test2`) have the same declared type: they only differ in that I implemented one of them.

The reason this is happening seems to be that the typechecker is ignoring my type declaration and inferring the the type of the variable from the implementation (which happens to to be a subtype of my declared type). I'm not sure why it's doing this.

### Notes

I would expect that if the following code type checks:

```
declare const <something>: <Something>

... <code involving something> ...
```

And the following code typechecks:

```
const <something>: <Something> = <some implementation>
```

Then the following code should typecheck:

```
const <something>: <Something> =  <some implementation>

... <code involving something> ...
```

Apparently not the case in general, as shown above. I believe the situations in which this does not hold should be considered bugs.

**Comment by MartinJohns** [comment]
Working as intended, comes up as an issue over and over again. The assigned type takes priority over the type annotation.

Consider this example:

    const f: number | undefined = 5;
    f.toFixed();

Should this complain about `toFixed()` not existing on `undefined` (using the annotated type, your suggestion) or should this work because the compiler knows always a `number` is assigned (current implementation)?

It's exactly the same case as this:

    let f: number | undefined = undefined;
    f = 5;
    f.toFixed();

You can work around this behavior by using a type assertion.

**Comment by masaeedu** [comment]
> Should this complain about toFixed() not existing on undefined (using the annotated type, your suggestion) or should this work because the compiler knows always a number is assigned (current implementation)?

It should complain about `toFixed` not existing on undefined. The entire point of the type annotation is to ensure that the variable has the specified (widened) type.

In general, if we have `const x: X = y`, where the inferred type of `y` is `Y` and `Y :< X`, simplistically narrowing the definition to `x: Y` will cause problems when `x` is passed into a function `<T>(t: T) => F<T>` whenever `F` is contravariant. When `F` is covariant, `F<Y>` is just as good as `F<X>`, given `Y :< X`. But when `F` is contravariant, `F<Y>` is _not_ an appropriate substitute for for `F<X>`: for this reason it is not appropriate in general to narrow the type of a declared variable (at least not without analysis of its usage).

**Comment by RyanCavanaugh** [comment]
Previously initialization *wasn't* a narrowing site, and we got two frequent bug reports - the first being that this is wholly inconsistent with a declaration followed by an initialization.

The other bug is that people would have a type alias like `type Cool = string | number | undefined;` and write code like
```ts
let p: Cool = getKnownString();
// expect no error because why on earth should it?
if (p.length > 0) {
  p = doOtherCoolThing();
}
```

*All* narrowing in TS is unsound in the presence of passing references to contravariant functions so that's really a red herring.
