### ISSUE TITLE
`keyof` a function type is equivalent to `never`

### ISSUE THREAD

**Issue by jswrenn** [microsoft/TypeScript#42831]
# Bug Report

### 🔎 Search Terms

- keyof
- function
- never
- getProperty

### 🕗 Version & Regression Information

The issue occurs in every version currently available in the playground (3.3.3 thru 4.2.0-beta).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/PTAEDMCcHsFtQBYBckAcDOAuEB3PA6JAT1QFN0BjSAS1SQBsBDAOwHN9pJXgATaC9MAQseAI2jQA1sEil6pRulIBaZtCTlgxMpRp1lAJmUBGfMlj0AxKQAejWKnkmAsAChwAV2YUk1aM1BWUiQABRgySGIAHgAVABpQAGlQWw1mHnRQSVIiaHBQGIA+AApoUQArTAKE7KIqxIBKUABvN1BQWSQPSACy8oBtWoBdAG5QEFAASWZwUkhZHlBtUlBqTJj+xKG3AF83N3kkCAlQAF5QfoAGBOMEg1G3cAl8eTYkBDGJnE5JdDcg0LhObEYpPaAJADkr1Y7whDU+YG+kF++1ch1AokYkDOEC8Pj8ATBxQazR2IzcmMg+GY9lICNASJRrgBYWgERBlISACIabBSFz4eMwIACslAFDgqGo8hS804AEIAPxAA).

### 💻 Code

```ts
// from https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#example-1
function getProperty<T, K extends keyof T>(obj: T, key: K) {
  return obj[key]; // Inferred type is T[K]
}

let foo = [0, 1, 2];
foo.length; // works
getProperty(foo, 'length'); // works

let bar = function foo(){};
bar.name; // works
getProperty(bar, "name"); // ⚠ compile error!?
```

### 🙁 Actual behavior

`keyof (() => void)` is equivalent to `never`.

### 🙂 Expected behavior

I expected `keyof (() => void)` to be equivalent to a union of string literal types including `'name'`.

**Comment by RyanCavanaugh** [comment]
Duplicate #16578

**Comment by jswrenn** [comment]
@RyanCavanaugh can you clarify the what the intended behavior here is? What's the distinction between these cases?
```rust
let foo = [0, 1, 2];
getProperty(foo, 'length');   // works
getProperty(foo, 'map');      // works

let bar = 42;
getProperty(bar, "toFixed");  // works

let baz = function foo(){};
getProperty(baz, "name");     // ⚠ compile error!
getProperty(baz, "bind");     // ⚠ compile error!
```

I don't quite follow @ahejlsberg's [explanation](https://github.com/microsoft/TypeScript/issues/16578#issuecomment-309082083) that:
> The `keyof` operator only considers the declared or inherited properties of a type, not those that come from its apparent type.

Doesn't `toFixed` come from the apparent type of `42`?

**Comment by RyanCavanaugh** [comment]
It appears that rule only applies to non-primitives.

**Comment by drzamich** [comment]
Array isn't a primitive, yet this rule doesn't apply to it.
