### ISSUE TITLE
Sometimes produced js file name is fully lower case

### ISSUE THREAD

**Issue by motek80** [Microsoft/TypeScript#4284]
For my ts files I using PascalCase notation. Sometimes, consistently, some of the compiled js files get lower case file name. For example: AbsenceRequestDataService.ts converted to absencerequestdataservice.js

**Comment by kitsonk** [comment]
What operating system, what version of tsc and NodeJS?

**Comment by danquirk** [comment]
Or more generally, what are you building with? (command line node, VS, etc)

**Comment by mhegazy** [comment]
does not seem to be an action item here. closing. @motek80 please feel free to reopen if the issue still exists.
