### ISSUE TITLE
It's possible to create a callable `never`

### ISSUE THREAD

**Issue by mkantor** [microsoft/TypeScript#42859]
# Bug Report

### 🔎 Search Terms

call never, callable intersection, intersection call signature, intersection discriminant

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7 (and still happens in 4.1.5 and 4.2.0-beta).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMwFzwG94AKAD30xgEsUBzASnxQFcBbAIxBgBp4p8ARAPgBfeADJCfJm04xRAKGToscNMwgZB7KMGEBeHMXpA)

### 💻 Code

```ts
declare const f: { (x: string): number, a: "" } & { a: number }
const result: "bad" = f()
```

### 🙁 Actual behavior

The above code typechecks! `f`'s type is displayed as `never`, but it behaves like `(...args: any[]) => any`.

### 🙂 Expected behavior

`f` should either be a real `never` (and therefore not be callable), or be callable with the specified call signature (`(x: string) => number`). Probably the former?

---

This occurs when intersecting a type that has a call signature with another incompatible type, and only if the incompatibility involves a literal type (i.e. when it's a discriminant).

Based on the behavior and affected versions, this is likely related to #36696.

[Elaborated playground with commentary and more examples](https://www.typescriptlang.org/play?#code/PTAEBUAsFNQSwHYBdoCcDO0DGS4HsFQ8AzUAQ1CzIBtqyAja2JATwAdYB3OJScwxFjwBbNmVyNm7WFUJZU0cbDIAoEKFYcNkcQHJ0oSIhQATcgYAGCaADc0FgDSh6AVyTPoOuwepwA1rAWABQAdGFkqADm6ABc-CwA2gC6AJSgALwAfPEWMSom2HQKlATo7sQAjHEA3qBBAB5xZaiIkSlxCC7C9GhOZHEARAOgAL6gAGSgtf2gnd1ooypCCGWgCugu1EhVoAP0ZCbD6aCVQWnq6JB4m2Y9a9AAVtimTq7ucOgIukj5hREypXKACYanVGqBmq12rMuj1UH04hVQAAfUBA0YTKbkOIAZhRoAALItlqt1pskCDdvtDhkTkCzqALlcbh57k8cNATK83PBPt8VGowFAPkQENQWEQsFgXBhQJwYIReLBBCIxBI4L5WPAEDY8NRvORQJq0DQNNIiKhDS4EPgEILQMIDrBoMg4ApxURSMbUKbNNB0CEIDATnrqHhuAhIqBoPUyKImAZOHhUH5dkJUAocOKBvagmR0BthK1DX6jf5AtMmkgWpGMZNKzD5paRhZKGRCHdEDp6DxOdr7UqTm7Vmw6FhoO1flgigCVuUcaCGlWa20OrDetiIdXi2N65u5nDiYD7hstjiZnsDkcTjiGep05mkB6FOzTEtj2Sz-Q103acRb0M5xgHgfhTjOJRzicBKLuCkKRtCB4bjMcFRqi1YuLAu5YjMiGWqi6AsN0epHpBn5IASF7UtexAEneYAPs8z6PM8nLvqR-rkgS36Noexw0UEgGMsBoH2gAkkg+igGwqB4PsjASu6ShmEgeDaLAxBkDg2jiNqKAYM8toGCQ2pCKI4hwJIZocOg9qILq+rFt6vrSAYcDCMInJwEoTEmC444aKpVi2PY3LuHgSqoLZCCmWqFlMLpaCYDghmgCYBDfHkpYAIK0g2KF1thiIYuo1h2JFpYAEK5ZuSKouiWENniqJEmMJXBeV5oAMLVch261g1+7rs2QmzOFsztfaADK0CwJASBIGwsQgJEPCQC49AhKZwBFvIeDoCQSDAOA0iTfIcBsIdbCbNQwA4gAbHdACcd0hpaBRIGQGoBkAA)

**Comment by Maximilian-Seitz** [comment]
This bug also occurs without a call signature in the original portions of the 'never' type.

So this compiles ([Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMwFzwG94p8ByU+AX3gDJDj8BGKgKGXSzjQFcIN8ARACMowAfAC8OABQBKIA)):
```typescript
declare const f: { a: '' } & { a: 1 }
const result: "bad" = f()
```

While this doesn't:
```typescript
declare const f: never
const result: "bad" = f()
```
