### ISSUE TITLE
Type inference of dynamic properties

### ISSUE THREAD

**Issue by Nctdtman** [microsoft/TypeScript#42854]
# Bug Report
### 🔎 Search Terms
union type, dynamic properties

### 🕗 Version & Regression Information
- This is the behavior in every version I tried

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gI1gLngHIUoBbEQ+AHyKgHMKAoZdLJbAK3gF54BvRvHhQUATwKERowgBpB8ANq4YAXQkB3JOtmMAvkA)

### 💻 Code
```ts
declare const bar: 'name' | 'age'
const obj = {
  any: 'any',
  [bar]: 'wow',
}
```

### 🙁 Actual behavior
```ts
const obj: {
    [x: string]: string;
    any: string;
}
```
### 🙂 Expected behavior
```ts
const obj: {
    name: string;
    any: string;
} | {
    age: string;
    any: string;
}
```
I think this is a predictable type.

**Comment by Nctdtman** [comment]
I currently use type assertions.
[Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gI1gLngHIUoBbEQ+AHyKgHMKAoUSWBZdLXALwMNICelGoQwhMhRh0zwk2AFbwAvPADejePCgoBfbUIA0G+AG1cMALp9zhI5rNRuVoj1uMAvlrTwAwgCZGDAEABwQAFQBGAB4AeQN4MPiANQA+ZXgY+BAADzEUYG99YwB+BKzckHzvTBgASxQ6angUAFdSbBAYJrQBdqQIY01S9U1R0ZMfeHqymgBrEAEkADMM50mcvIL4ecWVzNKYiYt4AiTB0fdzghQQADdO42u7h6DQ3wj0yKjVLR0CGvqjXc8VeIGWOFg8QBDRSgRCCH8n2iPgiIPh4J4UIwdRhjCAA)
The test is as follows:
```ts
declare const bar: 'name' | 'age'
declare const baz: 'my' | 'test'
const obj = {
  any: 'any',
  [bar]: 'bar',
  [baz]: 'baz',
} as C2
type T1<O, T, V> = O extends any
  ? T extends string | number | symbol
    ? {
        [C in T | keyof O]: C extends keyof O ? O[C] : V
      }
    : never
  : never
type C1 = T1<{ any: string }, typeof bar, string>
type C2 = T1<C1, typeof baz, string>
```

**Comment by jcalz** [comment]
Duplicate #13948, #21030
