### ISSUE TITLE
Revisit support for `::` operator

### ISSUE THREAD

**Issue by ackvf** [microsoft/TypeScript#42856]
# Suggestion for Extensions and `::` operator

## 🔍 Search Terms

Support proposed ES Next "::" bind operator https://github.com/microsoft/TypeScript/issues/3508
bind operator
Extensions

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to revisit _Support proposed ES Next "::" bind operator #3508_

>We'll revisit this if the proposal proceeds to stage 1.
>
>_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/3508#issuecomment-456615454_

There is a new iteration on the original bind operator proposal that has reached stage 1.

>This is an ECMAScript (JavaScript) proposal in stage 1.
>
>Note: The proposal could be seen as the new iteration of old bind operator proposal and I hope we could continue the further development in the original proposal repo if possible. See https://github.com/tc39/proposal-bind-operator/issues/56 .
>
>~ https://github.com/tc39/proposal-extensions

## 📃 Motivating Example and 💻 Use Cases

https://github.com/tc39/proposal-extensions

**Comment by MartinJohns** [comment]
I think nowadays the team follows the stance to wait for stage 3.

**Comment by RyanCavanaugh** [comment]
What @MartinJohns said -- we don't add new runtime-observable syntax unless it's at Stage 3 in the process. We continue to monitor active proposals and provide feedback where needed to help move them along.

**Comment by ackvf** [comment]
Alright! Get it. Too bad, I would love to see some syntactic sugar for binding.
