### ISSUE TITLE
Ability to be able to map a Record to a Tuple and vice versa

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#42857]
# Suggestion

Given a tuple such as `['one', 'two', three]` I would like to create a `Record< 'one' | 'two' | 'three'>` or vice versa.

## 🔍 Search Terms

`map tuple to record`
`map record to tuple`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

Given that I want to build an object:

```ts
type Car{
    color: string;
    engineSize: number;
    convertable: boolean;
}
```

I would like to write a function that accepts a tuple with one object for each key:

```ts

type BuildInstructions<T extends Record<string, string | boolean | number>{
     // converts T to tuple
}

function buildObject<T>(instructions: BuildInstructions<T>): T{}
```

which would be called:

```ts

const carInstructions: BuildInstructions<Car> = [
    { name: "color", type: "string", values: ["blue", "green"]},
    { name: "engineSize", type: "number", min: 100, mac: 3000},
    { name: "convertable", type: "boolean"},
];

const car = buildObject<Car>(carInstructions);
```

The inverse should also be possible, to define a Record based on a Record.

**Comment by RyanCavanaugh** [comment]
One direction of this is already possible
```ts
type Tuple = ["one", "two", "three"];
type R = Record<Tuple[number], string>;
let p: R = { "one": "uno", "two": "dos", "three": "tres" };
```

The other direction isn't feasible because tuples have an inherent ordering, but object properties don't.

**Comment by masaeedu** [comment]
This can be viewed as a use case for https://github.com/microsoft/TypeScript/issues/27130.

**Comment by Roaders** [comment]
That's very helpful. I think that's going to let me do what I want. Thanks.

**Comment by Roaders** [comment]
Ok... It very nearly gets me where I want but not quite. Given this code:

```ts
type Tuple = [{name: "one", type?: number}, {name: "two", type: number}, {name: "three", type: number[]}];
type R = Record<Tuple[number]["name"], Tuple[number]["type"]>;
let p: R = { "one": 1, "two": undefined, "three": [3] };
```
[Playground](https://typescript-play.js.org/#code/FDAuE8AcFMAIBUCukA2cC8sDaBvAdgIYC20AXLAEQD2e0FANLBDAPzl6JEBG0ATgL6N8xMpVAB3KgyZRRHbn0GxhJchVAALXtDqNmczj15YAuvxMBuMLNgAlWJlvQAxlV4ATADxJU0LPKMTLApCEgoTRh80f0M+IPVZcIA+KzRQWEhye0wcSho6cgBGRnVJCnJEPHdoADMAS1p3Es1tAuwAZhNYfisgA)

R is typed as:

```ts
{ 
one: number | number[] | undefined, 
two: number | number[] | undefined, 
three: number | number[] | undefined, 
}
```

what I would like is to retain the mapping from `name` to `type` and end up with:

```ts
{ 
one?: number, 
two: number, 
three: number[], 
}
```

is that possible?

Thanks again

**Comment by Roaders** [comment]
It seems that I am able to do it as follows:

```ts
type Tuple = [
    {name: "one", type?: number}, 
    {name: "two", type: number}, 
    {name: "three", type: number[]}
];

type RecordFromTuple = {
    [P in Tuple[number] as P["name"]]: P["type"]
}

const record: RecordFromTuple = {
    one: 5,
    two: 6,
    three: [7]
}
```

**Comment by flevi29** [comment]
For testing purposes I write the following:

```ts
type MatchingStrategy = "all" | "last" | "frequency";
const possibleMatchingStrategyValues = Object.keys({
  last: null,
  all: null,
  frequency: null,
  // record because cannot convert union to tuple (https://github.com/microsoft/TypeScript/issues/42857)
} satisfies { [TKey in MatchingStrategy]: null }) as MatchingStrategy[];
```

I wish this would be possible without a runtime cost, but for now it is what it is.
