### ISSUE TITLE
Regression: Compiler crash on call expression with private identifier on an any typed variable in 4.2RC

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#42860]
# Bug Report

### 🔎 Search Terms

A call expression with a private identifier coming from an any typed variable crashes the compiler

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.1 and 4.2

```ts
class A {
    #m: () => void
    method(thing: any) {
        thing.#m();
    }
};

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/MYGwhgzhAECC0G8BQ1XQMQFsCEAuaAFAJTQC8AfNAG4D2AlgCYpqYCmALgBY0MFd0A7AOb4wAgJ4lkaGdH7CAdFmIBuZqgC+SDWqA)
      
### 🙁 Actual behavior

Compiler crashes

### 🙂 Expected behavior

Compiler should not crash. 

Regression appears to have been introduced in fix for #42166 ([PR](https://github.com/microsoft/TypeScript/pull/42176/files))

**Comment by dragomirtitian** [comment]
Should have a PR up shortly.

**Comment by robpalme** [comment]
Thank you for the lightning fast turnaround on this.
