### ISSUE TITLE
User-defined type guard predicate check is too strict, produces TS2677 with inferred union of string literals on interface/type

### ISSUE THREAD

**Issue by 6XGate** [microsoft/TypeScript#42883]
# Bug Report

### 🔎 Search Terms

- `TS2677`
- `User-Defined Type Guards`

### 🕗 Version & Regression Information

- **at 3.3.x**, the guard does not work, nor will it compile
- **starting with 3.5.1**, the guard properly narrows the types, but the guard still won't compile

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBA4gTgQzACwIoBkDyAjAVhAY2AB4A5BAW2ggA9gIA7AEwGcoXg4BLBgcygC87Tj14A+QVADeAWABQUKAH0loSA0oQAXFHJUA3PIC+8+QDMArgyJcA9gyhcW8JGnQAVcBGLuotesxsLigYOPhEADS6fnSMrFDuANoARCpqjJrJALpiABTACHC8EMA67lEaVDqkAJQ6BUUljkGIIVh4hCSkErIKUHAlFnAODcXAAHRpXpXQAnNQM4ZyJnLyPPRwZggE0ADKFmBgADZcEHDS8opT6po6yfuHJ2fJS4ozOhzcfEsrawwbWx2UAA6oUIMhbBYWNBeldVNNblBkqCBhCoRAXpcFojPqIfqY5OszoDoABBJhMAYsNiw5Twm5VJHkykQamYvpgMH-HQPY6nOAAHxR4Mh0NeUAQFKpLA+Im+xgJBHsHHYBz5ZxlUF5TzgiSykkSWNpcPS7yR2v5yQiWLeiORCBYyFEwHsVqxRmtfWNdNNdotz09iltjOSAGEECczLZhlwEG6+isskt5EqGCqAO5g2zIdGa4Vo6F6g1Gm0+hEh-OijGBoNm5IAWS4BCdvAQDHjig9Jb6JvL2iRlfRHdrdvr9gKGmHieTcgA9LOoAAFIZgWzQo4gBa2YBQdJMXe2KDNwgAayg6KgtjMEoYm9sHSIUHTXGAyDLDOgPF3yGgvAshSYcYU2VHdJRZalWWLL1S2uDIQ2ZaVh0UTkBm5VVHn5FhEgABiyGtFDA6U7gAJgAZmIrVbCodMfwGKJdioiBjm2CAomBXZkndGtvVgusENZFgkKgFDGFKdD1TgLDcPwiUpQEu4ADYFIAdko6jaNYqBMFfM5mJ2NiOK47sg3fOD+2Sfi2RkkS0MzAZs1zRIAEY8NLQj5KRABOZSKOBDSnBfKIAE17CYM5MxAFgonrdxOITeQkwJSxrGAOwHCOWxeH9OB8kKMYeTVHUaguPpUxYWwjggcYMt4XIAANsqgAASKRRhKcYZiMOqanxVY5GSmx7CgGrB2hXLGjE0aIGK2kyoqqqavqxqWraiZOu63rzGjKBcjK0C5OpS9r3ciCWBmrEuGvXInGCNxPEgXITrYB1YFaNwwk6KJknQWwCAQVLXRqc6eyPZV5uqzL6pYQr+QAfmaqQbrejB7ogR6DpYcYbOAL7suSGoupqUs5sqiHarqmiwQLCB4ZapHXBRrx0fAzHsa+qb8cJgkTMunb6baVHmelLGuRx80YeeIGSpMxQauyoWBJF1DgB60tfhB3nrucZGPCZp6ldE9mqarfHgZl4bMqmhXqQN-5VZB9WTPnBInTYFCdyVOABiIDc-C96M2GfV9hNFrcd2wCBRAlakuF4DRsEqg9v2gAaAYcPKLCof4gJB53Nf5u69Yx22xfuCW4FN6Wg2d2XLeN9FrdZ0X7adhcVk7BU5CAA)

### 💻 Code

TS2677 error attempting to compile this code:
```ts
type GraphQLObject<Name extends string = string> = {
  __typename: Name;
}

function isGraphQLType<T extends GraphQLObject, N extends T["__typename"]>(target: T, name: N): target is GraphQLObject<N> {
  return target.__typename === name;
}
```

It is import and that `T` is limited to the possible `__typename` values to check that the guard may be used. The guard should also work when a union of `__typename` values can't be determined and results in `string`.

### 🙁 Actual behavior

TS2677 error is reported on the `isGraphQLType` function return type/guard predicate. Even though the guard works when used.

### 🙂 Expected behavior

The guard compiles, and workds.

**Comment by RyanCavanaugh** [comment]
This is the reduced form I've been trying out
```ts
type Animal =
    { kind: 'horse', gallop: any } |
    { kind: 'cat', meow: any } |
    { kind: 'dog', woof: any }
type OfKind<T, K> = T extends { kind: K } ? T : never;
type AnimalOfKind<K extends Animal["kind"]> = OfKind<Animal, K>;

function isAnimalOfKind<T extends Animal, K extends Animal["kind"]>(a: Animal, kind: K): a is AnimalOfKind<K> {
    return a.kind === kind;
}

declare const catdog: AnimalOfKind<"cat"> | AnimalOfKind<"dog">;

// Should be OK
if (isAnimalOfKind(catdog, "cat")) {
    // Should narrow to 'cat'
    catdog.meow;
}

// Should be an error!
if (isAnimalOfKind(catdog, "horse")) {
    // Narrowed to never, though
    catdog
}
```
I haven't been able to hit the trifecta of:
 * Correct narrowing of `cat`
 * Erroring on the `horse` call
 * No errors in the type guard body

Maybe someone with more tricks up their sleeve can figure something out?

**Comment by noppa** [comment]
(came here from @RyanCavanaugh 's tweet :stuck_out_tongue: )

```typescript
function isAnimalOfKind<T extends Animal, K extends T["kind"]>(a: T, kind: K): a is AnimalOfKind<K> & T {
    // Best case: have this be OK
    return a.kind === kind;
}
```
seems to work pretty well - [Playground](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAggdgSwLYEMA2UC8BYAUFAqAbygGsE4ATALigHIALAewCcBnCOgGigHN00TMLRRwQUAL5QAPnkLEyFGvQDGKYNyhIITAO4ixkmXMIlyVWnUpNem3UyYAzA+Il5QkKAHlHAaSUAPAAqPL4AfFhQQVAQAB7AEFRsCubKvkYA-FFQtHAQAG4QLADc7uDQ8MjoPv5UAelxCUmwiKhoANoARKmdALoRmN5+gZVtoWGluHgA9NNQAEoQwACuLHBQHtB5EJTJwExQcEzAUABG0KIxLCysUI63bKsQeI7LcCrACEzrCGyj1cM6tFGoldi0qmhQjF4qDkkEuj1+gAKFC0EKKCxQXwAShEUF+4LaNUC4SgADJskQTARZlAAEIQNgnNQcWgMFCFDYMAnnby+alQFhLVbrFAAOlSWEwg1SkzcU1wlAgKjQKCFUBU3yZGvU1l4tH+aGJdU6amAnQi0kJANqlACnT1FsmMzmAGVmMs0JQztAvPzcAhHFAkb9DcbKEizXqeKb1J1sdjiALae6mJ7vXA1TddBsDnQzXQBVGbGLtHo5XgXVBU+mfVBLkUbiwAIR4QPB0OtG1KSO6mwx5jsCDxxNU-CEWkAOSzeh2ucOBSKPGAHt4DGDvAclGxRb7vDwEiAA).

**Comment by RyanCavanaugh** [comment]
Adding `& T` also fixes OP's example. Very nice, thanks!

**Comment by 6XGate** [comment]
Interesting.  The attempt is to perfectly narrow to the type specified. Looking to ensure that adding `T &`/`& T`. Seems good based on the commented out part.

**Comment by 43081j** [comment]
Just out of interest, isn't OPs illogical because of the default type parameter @RyanCavanaugh ?

You are correctly narrowing a union (your `Animal` type). 

But OP is trying to narrow a generic. Surely `T extends SomeGeneric` would mean `T` extends the generic with its default type parameter?

Or does typescript do some magic here?

```
type Generic<T extends string = string> = {
  kind: T
};

// Isn't this inferred as Generic<string>?
function foo<T extends Generic>(
  obj: T
);

// More like this? Or just use a type union
function foo<K extends string, T extends Generic<K>>(
  obj: T
);
```

Curiosity really. `Generic<'foo'>` doesn't extend `Generic<string>` does it? They are just two distinct types from the same generic type? Or at least I thought they were

**Comment by 6XGate** [comment]
I'm simply trying to check GraphQL results  this with a utility function, which only accepts the limited set of values for `__typename` that are possible for a target. GraphQL objects are identified by their `__typename` field and support unions and interfaces where multiple related or unrelated types respectively may be returned from a query result.

Seeing as TypeScript was designed to narrow types based on members that have literal values, based on [Narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions), I would have figured this would work.

It's obvious that `GraphQLObject<N>` (as `A`) it assignable to `T` since we start with `T` and narrow to `A`. But what does it matter if the if `T` is assignable to its base form, in this case `GraphQLObject<string>`?

Given these models:
```ts
interface Supplier {
  __typename: "Supplier";
  name: string;
}

interface Warehouse {
  __typename: "Warehouse";
  name: string;
}
```

And a related child model referring back to a union of either:
```ts
interface Address {
  __typename: "Address";
  parent: Supplier|Warehouse;
  address: string;
}
```

It would seem this function should resolve to when using against the `parent`:
```ts
function isGraphQLType(target: Supplier|Warehouse, name: "Supplier"): target is Supplier;
function isGraphQLType(target: Supplier|Warehouse, name: "Warehouse"): target is Warehouse;
function isGraphQLType(target: Supplier|Warehouse, name: "Supplier"|"Warehouse"): boolean {
  return target.__typename === name;
}
```

**Comment by 43081j** [comment]
im more surprised that this is valid:

```ts
function isGraphQLType<T extends GraphQLObject>(obj: T);
```

as in, i expected `GraphQLObject` to expand to `GraphQLObject<string>`. so why does the compiler let us pass a `GraphQLObject<'foo'>` into it in the first place?

a `GraphQLObject<'foo'>` doesn't extend a `GraphQLObject<string>` normally in a type system i would've thought. maybe typescript is doing some magic around this?

your example just now @6XGate is vastly different because you're using a union type which you then narrow down. you're not trying to infer types from a generic.

in actual fact, i suspect the only reason your linked code is happy at all is because you casted `as GraphQLType`. which actually answers my first question.

you'll see if you did this:

```ts
const addresses: GraphQLObject[] = [...];
```

tsc would complain at you, because you're telling it its an array of `GraphQLObject<string>` which isn't true.

**Comment by RyanCavanaugh** [comment]
> a `GraphQLObject<'foo'>` doesn't extend a `GraphQLObject<string>` normally in a type system

`GraphQLObject<T>` is presumably covariant on `T` so this is very much expected

**Comment by 43081j** [comment]
IMO the OP is a correct error and all along this has been a misunderstanding of generics and the fact that a defaulted generic isn't the base of a particular generic.

and the only reason it got as far as this was because he was explicitly casting it at the call site into the base generic. which already lost all the extra information

**Comment by 6XGate** [comment]
@43081j  okay... the `as GraphQLType` isn't required... don't know how that snuck in there :) my bad...  And the "Location" string should be "Address"...  so there may be more going on here.

[Here is the corrected code](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBA4gTgQzACwIoBkDyAjAVhAY2AB4A5BAW2ggA9gIA7AEwGcoXg4BLBgcygC87Tj14A+QVADeAWABQUKAH0loSA0oQAXFHJUA3PIC+8+QDMArgyJcA9gyhcW8JGnQAVcBGLuotesxsLigYOPhEADS6fnSMrFDuANoARCpqjJrJALpiABTACHC8EMA67lEaVDqkAJQ6BUUljkGIIVh4hCSkErIKUHAlFnAODcXAAHRpXpXQAnNQM4ZyJnLyPPRwZggE0ADKFmBgADZcEHDS8opT6po6yfuHJ2fJS4ozOhzcfEsrawwbWx2UAA6oUIMhbBYWNBeldVNNblBkqCBhCoRAXpcFojPqIfqY5OszoDoABBJhMAYsNiw5Twm5VJHkykQamYvpgMH-HQPY6nOAAHxR4Mh0NeUAQFKpLA+Im+xgJBHsHHYBz5ZxlUF5TzgiSykkSWNpcPS7yR2v5yQiWLeiORCBYyFEwHsVqxRmtfWNdNNdotz09iltjOSAGEECczLZhlwEG6+isskt5EqGCqAO5g2zIdGa4Vo6F6g1Gm0+hEh-OijGBoNm5IAWS4BCdvAQDHjig9Jb6JvL2iRlfRHdrdvr9gKGmHieTcgA9LOoAAFIZgWzQo4gBa2YBQdJMXe2KDNwgAayg6KgtjMEoYm9sHSIUHTXGAyDLDOgPF3yGgvAshSYcYU2VHdJRZalWR0ZlpSLIRDS9UtrgyENoNZFhh0UTkBm5VVHn5FhEgABiyGtFDA6U7gAJgAZkorVbCodMfwGKJdgYiBjm2CAomBXZkndGtvSQutULZUioCwxhSlw9U4AI4jxPItC7gANhUgB2ejGOY7ioEwV8zk4nYeL4gTuyDd9kP7ZJRPQ8TJJwzMBmzXNEgARhI0slOpO4AE51Lo4EdKcF8ogATXsJgzkzEAWCiet3H4hN5CTAlLGsYA7AcI5bF4f04HyQoxh5NUdRqC4+lTFhbCOCBxhy3hcgAA3yqAABIpFGEpxhmIwmpqfFVjkdKbHsKAGsHaFCsaaTJogcraSqmq6oa5rWo6rqJl6-rBvMaMoFyKrQKlNDL2vbzoRYBasS4a9cicYI3E8SBcguqIbJOtkamunsj2VZb6ty5qWFK-kAH52qkB7WierxXs+lhxgc4B3vy5Iaj6mpSyW2rAcapqmLBAsIAhjrodcDBnogeHwMR5H3rm9HMYJCzboO8m2ipmnpSRrkUfNUHnm+iqLMUBr8u5tDeew4ABtLX5frZ+7nBhym4Yu6WpIZomq3Rn7RfG3K5sl6lNf+OXfoViz5wSJ02CwnclTgAYiA3PxnejNhn1fCS+a3HdsAgUQJWpLheA0bBaoPb9oBGzKxqKiwqH+IDfptpWOdhl6NfpgW8KF-WgxtsWjZ19ETbpvmLethcVk7BU5CAA)

**Comment by 43081j** [comment]
that makes sense, but i think its still an understanding of generics and the error is right.

i really hope someone tells me soon if im just digging holes 😂  but as far as i understand:

```ts
type GraphQLObject<T extends string = string> = {__typename: T};

type Address = {__typename: 'Address'};

// Fine
const addressValue: Address = {__typename: 'Address'};

// Fine, but see below
const addressValueAsGraph: GraphQLObject = addressValue;

// This is what its actually expanding to
const addressValueAsGraph: GraphQLObject<string> = addressValue;

// This means GraphQLObject<string>['__typename'] = string
```

assuming im not just talking nonsense, it was assignable because the _value_ `{__typename: 'Address'}` matches the type `{__typename: string}`. you already lost the strong typing of `__typename` by this point.

so in your code:

```ts
function isGraphQLType<
  // This is actually GraphQLObject<string>
  T extends GraphQLObject,

  // This is always string in reality, but its possible something genuinely
  // extended GraphQLObject<string> which overrode __typename, so
  // we still need to infer it, but it always extends string
  N extends T["__typename"]
>(
  // This could be anything whose __typename
  // is a string
  target: T,

  // Something which inherits string
  name: N

  // GraphQLObject<N> is not assignable to GraphQLObject<string>
  // because if N was 'foo', GraphQLObject<'foo'>['__typename'] can't be assigned
  // any given string. which means it doesn't inherit GraphQLObject<string>.
): target is GraphQLObject<N>;
```

**Comment by 43081j** [comment]
@RyanCavanaugh could you possibly explain this?

i think ive been misunderstanding the covariance. my misunderstanding comes from this being allowed:

```ts
class Base {}
class Derived extends Base {}
class DifferentDerived extends Base {}

interface Foo {
  value: Base;
}

interface Bar {
  value: Derived;
}

declare const test: Foo;
const testAsBar: Bar = test;
test.value = new DifferentDerived(); 
```

in C# for example the assignment would be allowed but would be held in a separate backing field to the subclass' equivalent property. i got confused because in the world of JS of course anything can be assigned to whatever, and there's only one place to hold the value.

so yeah in typescript this'd be fine, and back to OP, `"foo"` is ultimately a string so you can use it as a `GraphQLObject<string>` just fine and assign it to non-foo values.

**Comment by RyanCavanaugh** [comment]
See the FAQ around empty classes. This errors as expected
```ts
class Base { b!: any }
class Derived extends Base { d1!: any }
class DifferentDerived extends Base { d2!: any }

interface Foo {
  value: Base;
}

interface Bar {
  value: Derived;
}

declare const test: Foo;
const testAsBar: Bar = test;
testAsBar.value = new DifferentDerived();
```
I'm not able to provide 1:1 consultation on compiler behavior; the issue tracker is for bugs. Please use other forums (StackOverflow, discord) for help on TS behavior.
