### ISSUE TITLE
`\u` in String.raw

### ISSUE THREAD

**Issue by sugoroku-y** [microsoft/TypeScript#42887]
# Bug Report

### 🔎 Search Terms

String.raw

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about String.raw

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MoFwTglgdg5gdGAhgdwAaICYGMA6GCmAZjjABYQ4BWA1gDY4C2UA9jgA4COYOAziDgFcAbshwAPAJ4AvVACggA)

### 💻 Code

```ts
String.raw`adc\def\ghi\jkl\mno\pqr\st\uvw\xyz`
```

### 🙁 Actual behavior

Error reported:  `error TS1125: Hexadecimal digit expected.`

### 🙂 Expected behavior

Complete transpile

**Comment by DanielRosenwasser** [comment]
@Kingwl you might be interested in this one.

**Comment by ExE-Boss** [comment]
It’s not just `String.raw`, this applies to all tagged template literals, where the top‑level `TemplateStringArray` contains `undefined` for an unknown escape:

```ts repro
const taggedTemplate = (template: TemplateStringsArray, ...substitutions: unknown[]) => {
	console.log(template, substitutions);
}

/* Logs:
[
	"foo", undefined, "baz",
	raw: [ "foo", "\\ubar", "baz" ]
]
[ 123, 456 ]
*/
taggedTemplate`foo${123}\ubar${456}baz`;
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBFCGBzRBTAJgFRQWwA4Bt4oUYBeGACmL0OIC4YsaiUBlKAJwEsxEIBBDh3gBPADQwAdNIgBXAEbQuUWVC7gIDWWADWYEAHcwAbQC6ASjIA+GAG8AUAEhQkEPhST8IRFRwEWEnKKaipqGuYA3PYAvvb2APTxMAAy3poJScYZMI4ARABmICC5EtpoKPk86BK58vAAXiXZjsIGDMYwBUUlnQA6vQrwHD21DbkwptmTiTAdAIwATADMEgAsAKwAbBP2CMjoTP7EAAaFIAAktotL0QN1HJcbm9F19cdRQA)

**Comment by Kingwl** [comment]
>It’s not just String.raw, this applies to all tagged template literals

Sorry I'm not 100% sure what your means.
But seems the runtime behavior is as expected.

![image](https://user-images.githubusercontent.com/6831019/108585010-b1be9f00-7380-11eb-9840-2dea4c173b7a.png)

The current problem is falsely alarm. 

Here's some context:
- https://github.com/microsoft/TypeScript/pull/23801
- https://tc39.github.io/proposal-template-literal-revision/

And I have found an PR who try to fix a part of the alarm: https://github.com/microsoft/TypeScript/pull/41030

**Comment by ExE-Boss** [comment]
The definition of `TemplateStringArray` should include `undefined` in the top‑level index signature, which should be fixed alongside this to correctly describe the runtime behaviour as of <https://github.com/tc39/ecma262/commit/138c9efc5460c22e175007ba2608b2c4238e11ef>.

**Comment by Kingwl** [comment]
Ahhhh Okay. Got the point. Thanks.

**Comment by elibarzilay** [comment]
I think that dealing with octal escapes in all strings #396 should be done before dealing with tagged templates as an exception...

**Comment by bentongxyz** [comment]
Hi, is this issue being worked on? I would like to look into this as a first issue.

**Comment by polkovnikov-ph** [comment]
Almost created a duplicate to this issue.

The proposal [was here](https://tc39.es/proposal-template-literal-revision/), normative section in ECMA-262 [here](https://tc39.es/ecma262/#sec-static-semantics-tv-and-trv).

**Comment by polkovnikov-ph** [comment]
@ExE-Boss

> The definition of TemplateStringArray should include undefined in the top‑level index signature,

I'm afraid such a change will break existing code. `undefined` is there only if a part of string template contains invalid escape characters, and this information is available in compile-time. I'd suggest replacing `TemplateStringsArray` with a `readonly` tuple of `string`s and `undefined`s, intersected with `{raw: ...}`. of equal-sized tuple of `string`s. This type [should be backwards compatible](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gVwFzzimFQgE94BtTGASxQHMAaeau+gXXgDJ4BvGKAHd8hYijKVWDZlI4BfANwAoZOiwZ8AFRABbAA7QMIAMoZaDNAEEYA8gF4cCoA).
