### ISSUE TITLE
ProxyHandler.apply method

### ISSUE THREAD

**Issue by icecream17** [microsoft/TypeScript#42894]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `ESNext`.

The method is in the file: ```lib.es2015.proxy.d.ts``` 
[According to vscode command (Go to Definition)]

## Missing / Incorrect Definition

This is about an incorrect method:
```ProxyHandler.apply()```
(The second argument to the Proxy constructor)

Current type definition: 
```
    apply? (target: T, thisArg: any, argArray?: any): any;
```

Actual type definition:
```
    apply? (target: T, thisArg: any, argArray?: any[]): any;
```

## Sample Code

```markdown
<!--
  What's some code using this that should work, but doesn't?
-->

This only makes this method even stricter,
so the only effect will be to make more code fail.
```

## Documentation Link

https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-call-thisargument-argumentslist
Step 7 specifically creates an __array__, which is passed as the third argument to the ProxyHandler.apply method.

## Edit
This also applies to ```ProxyHandler.construct```

**Comment by ExE-Boss** [comment]
This was already fixed by <https://github.com/microsoft/TypeScript/pull/35594> which will be released in **TypeScript 4.2**.
