### ISSUE TITLE
Explicit application gives different results with a function that returns a template literal type

### ISSUE THREAD

**Issue by tom-sherman** [microsoft/TypeScript#42897]
# Bug Report

### 🔎 Search Terms

template literal, map keys, empty, application, arrow function

### 🕗 Version & Regression Information

This looks to have been an issue since template literal types were introduced.

I'm not entirely sure what the core problem is here because I've never seen a failure case like it before in TypeScript.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=6&ts=4.1.5#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsoAHAaRAE8BnAHgCh54AVeEADwxFWCvgCVwOGMBpUMMLKgDmAGnhRUFAHwyG8ALIkAYvnaduvABQBrSgC54pijkTMAlPAC8S+YrpLDanACMAVhaZVRiJiHQtNUNQ6OwsAbwBtY3hJfhAMZBhUJgpiEBoInSUAXQDEyhtmIoBfOjpQSFgEFHRsPEISJhwAZXFJKUMqCzEJaRj4Yb66MDwxeBwABid2skoqQ1ioCwBGOW8LACYquRDOnpGpO1r66DgkNExcfGI4RCw2AHUsDAALLRwcGhdVgcLg8ca9aQeQbwLpjAAGiH+ABJYl0qnCpjMMHMtksQuRqOtNvAdvA9vBDnITA5nPBniBXh8vr9-tTLtNULMcPs8SQCWsNttdgcjnSXm9Pj8-jhLkA)

### 💻 Code

```ts
declare function mapKeys<
  T extends Record<string, any>,
  MapFn extends (key: keyof T) => any
>(
  obj: T,
  mapFn: MapFn
): {[k in ReturnType<MapFn>]: T[keyof T]}

declare function mapToString(s: string): string
const o0 = mapKeys({a: 1, b: 2}, mapToString)

declare function prefixWithFoo<S extends string>(s: S): `foo${S}`
const o1 = mapKeys({a: 1, b: 2}, (k) => prefixWithFoo(k))
const o2 = mapKeys({a: 1, b: 2}, prefixWithFoo)
```

### 🙁 Actual behavior

`o2` has type `{}`

### 🙂 Expected behavior

`o2` should have the same type as `o1`: `{ fooa: number; foob: number; }`

**Comment by RyanCavanaugh** [comment]
@ahejlsberg any clever ideas on fixing this without switching to unification?

**Comment by ahejlsberg** [comment]
It works if you simplify the `mapKeys` function to this:

```ts
declare function mapKeys<T, K extends string>(obj: T, mapFn: (key: keyof T) => K): { [P in K]: T[keyof T] };
```

Can't think of a way to preserve the _individual_ property types in `T`, but I guess that wasn't asked for either. 😃
