### ISSUE TITLE
No excess property check when ts-expect-error or ts-ignore-error used

### ISSUE THREAD

**Issue by connorjclark** [microsoft/TypeScript#42893]
# Bug Report

### 🔎 Search Terms

excess property check, EPC, ts-expect-error, ts-ignore-error, object literal

### 🕗 Version & Regression Information

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/JYOwLgpgTgZghgYwgAgCoE8AOECMyDeAsAFDLJwD8AXMiAK4C2ARtANwllPW2MtTulkCbvWbQSAXxIkEAexABnMMgBucKDhoZseALwEO5GjgA0hgPTnkAATAKAtMADmIWVAj3oUN4aY0A5Ez+ZoIAJsYmyJbIAKIAHkgKCsiY3thQYOjIXm4UkgJAA)

### 💻 Code

```ts
interface Type1 {
  a?: number;
  b?: number;
  c?: number
}

const var1: Type1 = {
  a: 1,
  // @ts-ignore-error
  b: 'b',
  d: 1, // Excess property error?
};
```

### 🙁 Actual behavior

Code passes with no errors.

### 🙂 Expected behavior

Code fails with "d does not exist on type Type1"

----

FWIW it also doesn't surface an error for `d` when the error for `b` is not ignored: 

![image](https://user-images.githubusercontent.com/4071474/108576900-dd8c4700-72e4-11eb-929d-1da1f730006a.png)

This makes it more clear that the type checking is simply exiting early at the sign of the first critical error (`b` is bad), which makes sense. However, I'd expect excess property checks to still happen if such an error is explicitly ignored with a `ts-ignore-error` comment.

**Comment by DanielRosenwasser** [comment]
Those comments just suppress errors that the type-checker produces. If you're suppressing an error on a value or binding, we can't guarantee anything about related code, so I would judge that this is either working as intended, or a design limitation at best.
