### ISSUE TITLE
typecheck on methods is not strict during interface inheritance

### ISSUE THREAD

**Issue by zimtsui** [microsoft/TypeScript#42906]
# Bug Report

### 🔎 Search Terms

- interface
- method
- inheritance

### 🕗 Version & Regression Information

- tsc 4.1.5
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Why are function parameters bivariant?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)

### 💻 Code

this code can not be compiled, because F1 doesn't extend F12:

```ts
interface F1 {
    (x: 1): void;
}
interface F12 {
    (x: 1 | 2): void;
}

interface A {
    f: F12;
}

interface B extends A {
    f: F1;
}
```

but this semantically equivalent code can be compiled successfully:

```ts
interface A {
    g(x: 1 | 2): void;
}
interface B extends A {
    g(x: 1): void;
}
```

### 🙁 Actual behavior

the first one is wrong, the second is correct.

### 🙂 Expected behavior

both are wrong.

**Comment by MartinJohns** [comment]
Those are not semantically equivalent. The first contains properties, the second methods. Check the FAQ for co- and contra-variance. This is working as intended.

**Comment by MartinJohns** [comment]
This is the semantically equivalent version, which has the same error:

    interface A {
        f: (x: 1 | 2) => void;
    }

    interface B extends A {
        f: (x: 1) => void;
    }

**Comment by zimtsui** [comment]
I'm sorry i didn't fill the template and i have edit it.

what puzzled me is the difference behavior between methods and function properties in strict mode. but now i found this is [a known issue](https://github.com/microsoft/TypeScript/pull/18654) and the bivariance of methods is a trade-off.
