### ISSUE TITLE
Add way to specify partial/mapped return type with static info

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#42902]
# Suggestion

Given this code:

```ts
/**
 * @template T
 * @param {Array<keyof T>} keys
 */
function selectKeys(keys) {
  return (
    /**
     * @param {T} o
     * @return {Pick<T, typeof keys>}
     */
    (o) => keys.reduce((out, key) => ({
      ...out,
      [key]: o[key],
    }), {})
  );
}

/**
 * @template T
 * @param {(o:T)=>any} fn
 * @param {'ASC' | 'DSC'} dir
 */
function sorter(fn, dir = 'ASC') {
  const down = (dir === 'ASC' ? -1 : 1);
  const up = down * -1;
  return (
    /**
     * @param {T} a
     * @param {T} b
     */
    (a, b) => (
      fn(a) < fn(b) ? down : up
    )
  );
}

console.log([
  { a: 2, b: 22, c: 222, d: 2222 },
  { a: 1, b: 11, c: 111, d: 1111 },
  { a: 5, b: 55, c: 555, d: 5555 },
  { a: 4, b: 44, c: 444, d: 4444 },
]
  .map(selectKeys(['c']))
  .sort(sorter(o => o.c))
);
```

When you hover over `o` on the second to last line, VS Code (courtesy TypeScript) shows this:

```ts
(parameter) o: Pick<{
    a: number;
    b: number;
    c: number;
    d: number;
}, ("c" | "a" | "b" | "d")[]>
```

And the `o.c` itself shows as an error:

```ts
Property 'c' does not exist on type 'Pick<{ a: number; b: number; c: number; d: number; }, ("c" | "a" | "b" | "d")[]>'.ts(2339)
```

I get that the array specified in the `selectKeys()` call can be dynamic, but when it's static, we have enough information to keep type safety, so that instead of thinking we have:

```ts
Pick<{
    a: number;
    b: number;
    c: number;
    d: number;
}, ("c" | "a" | "b" | "d")[]>
```

It can clearly see that we have:

```ts
Pick<{
    a: number;
    b: number;
    c: number;
    d: number;
}, "c">
```

I know it's a bit of a special casing thing, but I think it could be at least a little generalized to be more useful than this little FP lib I'm trying to build.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Keep specific type information when Pick<> is provided with a literal array of static keys that could be considered a union.

## 📃 Motivating Example

I guess I put it on the wrong section. But yeah it's above.

## 💻 Use Cases

Here too.

**Comment by ilogico** [comment]
I believe you have an error in your example: you define the return type of selectKeys as `Pick<T, typeof keys>`, which doesn't make much sense, `keys` is an array.
One way of doing it is like [this](https://www.typescriptlang.org/play?useJavaScript=true#code/PQKhFgCgAIWgBALgUwLYAcA2BDF0AqUsCKGOeA3gBQDWyAngPYBmBAlANoC6AvtANLQiceOmwAnbKmgV+fOvQDOw4FGYBXAHYBjRAEtGm6IuSZku-g0W0rbGUWjjkideKNUH0aKAgwvXkTFJaQp8PkZPAIQnFzcZAAU9bRoAHnwAGgEOTXVUACNkcS4APh5I2FU-LypGOwBeYugFRQA6JwATdW1kKhr1REyFesaqCnLoFsnGfvTxjgUuAC5oRnmGLlmq6B42TJ8SenRkGWxNej4QYGhRnbYHNgBuKDLIKB9hEjQsXGPCGECJFIZDVFvg2A1TudoMxNB9RICQgByACCAGUAMKI6AAH2giIAIhjEXx2npxCo1FpdAYjIpGOIUOIqDDMqTxNA6ni0Zi7GM-NpDIpENB2owAO5GTlUNkcuqclFE6AAfmgAFoAIzQZbqx4OAWaIXQdToDki8VGOAap5+GKudyRd5bYjw4IyMLQbDlAGu0J8PJeyr+a7YTJ5YbXcYwqjYOwpaGaKhh5VmiVao3oSJ3Py6yAvKD6ulmFqYRgAcyoHAcFA9ywATKG6-XoNpG032q3a9tNl5q9htQ3oOr1ZkW4Oh6ztUPNTxuzIa9AAKwDhdL5vLFer9uLjddqvzgAsA-3h7X0GPJ635-3u8gXAcLVQ2HQVBMZgsVgriO0iK4bCzXhaOkGRfelGRqDlGkYFptD-KBHiAA).
Note that I had to use a cast to `any` because TS cannot validate the creation of the dynamic object.

**Comment by sdegutis** [comment]
Cool, you're right, this does work. Thanks.

Dev team: if this is indeed the best solution to do what I'm trying to, and a language change/feature isn't necessary, feel free to close this.

**Comment by sdegutis** [comment]
Ahh I see how your solution works @ilogico: since we have an array of keyof T, and we need a union of keyof T, we just need to do (keyof T)[number], which turns the array into a union. Clever.

Surely there's a way to avoid casting the reduce init to any? Maybe if it were a Partial<T> or something, then TypeScript wouldn't complain? Or maybe reduce is the wrong way to solve this with the cleanest/clearest types, and a loop would make typing it more accurate?

**Comment by sdegutis** [comment]
Ah, casting to `@type {Pick<T, K[number]>}` instead of `any` in the same spot seems to work fine.

**Comment by sdegutis** [comment]
Dev team: I suppose, if this really is the best solution, this issue can be repurposed to request better documentation for this kind of thing, maybe even using this specific example for FP style things. I have not yet found a FP TS library that works like this (integrates with JS's built-in lib rather than replacing them) and also has autocompletion working properly in VS Code, and that's part of my motivation for writing these functions for myself, but it wasn't clear how to.

**Comment by RyanCavanaugh** [comment]
I'm really not sure how we can (from a first-party perspective) document how to construct things out of the primitives the language offers, except by way of a finite number of examples. If there are gaps in the documentation for the primitive constructs themselves I'd like to address those, but it seems like this is a case of "how to accomplish a task" that's better suited for fora like StackOverflow.
