### ISSUE TITLE
No warning message for typescript for using different ToolsVersions property

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4291]
Open a project in VS2015 with TypeScriptToolsVersion set to 1.4.  Expected an warring message that version of the project is out-dated. actual not error.

Also building should show and error for missing tools version. actual no.

This breaks backward compatability for VS projects.

**Comment by paulvanbrenk** [comment]
This will be in the next release for VS 2015.

**Comment by mhegazy** [comment]
@paulvanbrenk  what is the behavior on build? do we get a warning as well if the toolset (older) is not installed on the machine?

**Comment by paulvanbrenk** [comment]
@mhegazy No, we removed that a while ago. It was considered annoying, since they already got the warning on project open.
