### ISSUE TITLE
Tsconfig.json does not resolve paths with dashes "-" in folder name

### ISSUE THREAD

**Issue by cbdeveloper** [microsoft/TypeScript#42913]
# Bug Report

### 🔎 Search Terms

tsconfig.json, path, resolve, include, exclude, dash

### 🕗 Version & Regression Information

`typescript@4.1.3` installed globally on VSCode Windows 10.

### ⏯ Playground Link

Not necessary.

### 💻 Code

I work with a monorepo structure and some packages are installed in more than one folder. I don't want to `skipLibCheck`, because I need my own `src/*.d.ts` files to be checked. But at the same time, if I allow all `node_modules` to be checked on the `tsc` call, I'll get many conflicts, because a lot of library types will be declared in more than one place. So, this is what I always do:

**tsconfig.json**

```
// ...
"exclude": [
    "node_modules",
    "server/node_modules",
    "server-jobs/node_modules",    // THIS DOES NOT WORK
    "server_jobs/node_modules",    // THIS WORKS
    "public"
  ]
```

### 🙁 Actual behavior

When I added the `server-jobs/node_modules` folder, I started getting conflict errors for packages inside `server-jobs/node_modules`, which made no sense, because they were supposed to be excluded.

I tried tweaking my code, and experimented with some different `include/exclude` patterns. Nothing seemed to work. Until I though it could be related to the folder name, because of the dash `"-"`  character. Since the `server` folder wasn't triggering any errors. 

Then I changed it to `server_jobs`, with an underscore `"_"` and everything went back to normal. No more conflict errors.

I didn't find anything in the documentation for it.

https://www.typescriptlang.org/tsconfig#exclude

Is this a known issue? Is it supposed to behave like that?

### 🙂 Expected behavior

I expected for the `tsc` to parse folder names with dashes `"-"` without any issues, or at least for it to give me a heads up with a warning telling me that that folder name is not allowed.

**Comment by minestarks** [comment]
This is surprising. I don't think dashes are the problem here (folders with dashes in their name work fine on other projects). Perhaps the folder name had a different type of dash (e.g. `—`) copy-and-pasted from somewhere? Perhaps other files were referencing the files under `server-jobs`?

**Comment by RyanCavanaugh** [comment]
Agree with Mine, it's implausible that dashes are the problem here; `react-router` exists and we would immediately hear about it if that didn't work. A more complete sample that reproduces the problem is needed.

**Comment by cbdeveloper** [comment]
Thank you all for the feedback.

I'm not sure if this issue is specific for the packages I'm using or not. But I can confirm that my project currently **has no type errors** when I run `tsc --project ./tsconfig.json`.

To reproduce the issue and show you guys what is happening, the **only** change I'm making is: to rename `cloudrun_jobs` folder to `cloudrun-jobs` and change `tsconfig.json` accordingly. PS: In my real case, the `server` folder I've mentioned in this issue is `cloudrun`.

To give you an idea of the project structure. Here is what I got:

`app` has my front-end files (React app). Both `cloudrun` and `cloudrun-jobs` are express servers that should run on cloud run instances and both have their own `package.json` file and corresponding `node_modules` folder.

![image](https://user-images.githubusercontent.com/43407798/108828095-524dd280-75be-11eb-8f54-535925d5251d.png)

So, everything was fine again, and I've renamed `cloudrun_jobs` to `cloudrun-jobs`:

Now, here are the errors I'm getting when I do a type check: I'm pasting as images because I think the formatting makes it easier to read.

![image](https://user-images.githubusercontent.com/43407798/108830830-91315780-75c1-11eb-90b7-a573cb03f7fd.png)


Here is my full `tsconfig.json` after I've changed the folder name to `cloudrun-jobs`.

```
// REFERENCE
// https://www.typescriptlang.org/tsconfig

{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "resolveJsonModule": true,
    // "skipLibCheck": true,
    "strictNullChecks": true,
    "target": "ESNext",
    "paths": {
      "@app/*":    ["./app/*"],
      "@common/*": ["./common/*"]
    }
  },
  "ts-node": {
    "files": true     // Load files, include and exclude from tsconfig.json on startup
  },
  "include": [
    "app/**/*",
    "common/**/*",
    "cloudrun/src/**/*",
    "cloudrun-jobs/src/**/*",
    "scripts/**/*"
  ],
  "exclude": [
    "node_modules",
    "cloudrun/node_modules",
    "cloudrun/dist_app",
    "cloudrun/dist_common",
    "cloudrun/dist_service",
    "cloudrun/public",
    "cloudrun-jobs/node_modules",
    "cloudrun-jobs/dist_common",
    "cloudrun-jobs/dist_service",
    "public"
  ]
}
```

Here is the `package.json` of the `cloudrun-jobs` folder:

```
{
  "name": "cloudrun_jobs",
  "version": "1.0.0",
  "description": "",
  "main": "babel.config.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "firebase-admin": "^9.5.0",
  }
}
```

The `firebase-admin` package has `"@google-cloud/firestore": "^4.5.0",` as one of its dependencies. And `firebase-admin` is listed as a `devDependency` in the root `node_modules` folder. This is probably what is being checked as a type conflict.

Before posting this comment, I'm going to change the folder name back to `cloudrun_jobs` and see it all goes away again.

**Result:** all the errors are now gone. Isn't it weird? What do you guys think?

![image](https://user-images.githubusercontent.com/43407798/108830589-7828a680-75c1-11eb-87c2-9753f3cf1770.png)

**Comment by cbdeveloper** [comment]
Hey everyone,

Thank you all for the feedback. Just found out that the errors are still happening with the name `server_jobs`. The reason that they were gone initially is because I was deleting its `node_modules` before renaming (to speed up the rename operation). Of course the errors would be gone in that case. So it has nothing to do with the dashes `-` in the folder names.

I'm still finding it weird. Why would Typescript care for conflicts inside `node_modules` folder when they are being excluded?

This is now off-topic, but would be happy to hear your thoughts. 

I'll close the issue since it's not about folder names at all.

This is my full `tsconfig.json`

```
// REFERENCE
// https://www.typescriptlang.org/tsconfig

{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "resolveJsonModule": true,
    // "skipLibCheck": true,
    "strictNullChecks": true,
    "target": "ESNext",
    "paths": {
      "@app/*":    ["./app/*"],
      "@common/*": ["./common/*"]
    }
  },
  "ts-node": {
    "files": true     // Load files, include and exclude from tsconfig.json on startup
  },
  "include": [
    "app/**/*",
    "common/**/*",
    "server/src/**/*",
    "server_jobs/src/**/*",
    "scripts/**/*"
  ],
  "exclude": [
    "node_modules",
    "server/node_modules",
    "server/dist_app",
    "server/dist_common",
    "server/dist_service",
    "server/public",
    "server_jobs/node_modules",
    "server_jobs/dist_common",
    "server_jobs/dist_service",
    "public"
  ]
}
```

**Comment by cbdeveloper** [comment]
After further research and debug, I found out that the errors were being caused by a version difference between the `firebase-admin` that was installed on the project root as a `devDependency` and the `firebase-admin` installed on the `server_jobs` folder as a dependency.

Since the `server_jobs` folder was the most recent one, it had a more recent version of that package. After updating all to the same version, the errors went away.

But I still find it weird that those errors were caught by `tsc`, given the fact that all `node_modules` were excluded.

**Comment by RyanCavanaugh** [comment]
`exclude` is only a filter on `include`; it doesn't change whether files can get imported into your program, or how they behave once present.

See also #30511

**Comment by l-jonasiak** [comment]
@cbdeveloper It's been a while since this issue was last answered. Have you found a solution?
