### ISSUE TITLE
tsserver worker can not watch the single file

### ISSUE THREAD

**Issue by howel52** [microsoft/TypeScript#42922]
# Suggestion

Currently, tsserver worker cannot watch the single file.  Will miss some events

https://github.com/microsoft/TypeScript/blob/2df960a9bad28c6d6f5a704717ab02fb6800b933/src/webServer/webServer.ts#L127

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
I guess if tsserver worker can not watch the single file,  maybe some effects will be missed

## 💻 Use Cases
tsserver worker can watch single file

**Comment by DanielRosenwasser** [comment]
Can you explain a bit more about what you're trying to work on? I'm pretty sure this logic is written with a very narrow use-case.

**Comment by howel52** [comment]
I am trying to make `tsserver worker` capable of diagnosis for single file. https://github.com/microsoft/vscode/issues/117195  

And I guess one of the reasons is that `tsserver woker` missing some events from filesystem.  

But I am not sure @DanielRosenwasser

**Comment by sheetalkamat** [comment]
This is intentional. Web worker is not suppose to watch anything but operate only on open files (till date)

**Comment by howel52** [comment]
> This is intentional. Web worker is not suppose to watch anything but operate only on open files (till date)

If `tsserver worker` want to get  diagnostics from single file(not all project's files), is it related to this issue?   @mjbvz 

And I want to help `vscode web` to get diagnostics from single typescript file,  are there any suggestions
