### ISSUE TITLE
Documentation of the full algorithms for type *union* (the `|` operator) and *intersection* (the `&` operator), and their higher order combinations.

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#42934]
# Suggestion

## 🔍 Search Terms

typescript unions and intersections

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ]x This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Documentation of the full algorithms for type *union* (the `|` operator) and *intersection* (the `&` operator), and their higher order combinations.

Here are some sample trials to give some insight about edge cases.
```
{
  type A = {a:number,b:number}
  type B = {b:string,c:string}
  type C = {c:bigint,a:bigint}
  const t1:A|B|C = {a:1,b:'1',c:1n} // fail
  const t2:A|B|C = {a:1,b:'1',c:'1'} 
  const t3:A|B|C = {a:1,b:1,c:1n} 
  const t4:A|B|C = {a:1,b:1,c:'1'} 
  const t5:A|B|C = {a:1n,b:'1',c:1n} 
  const t6:A|B|C = {a:1n,b:'1',c:'1'} 
  const t7:A|B|C = {a:1n,b:1,c:1n} 
  const t8:A|B|C = {a:1n,b:1,c:'1'} // fail 
}
{
  type A = {a:number,b:number,c:number}
  type B = {b:string,c:string,a:string}
  type C = {c:bigint,a:bigint, b:bigint}
  const t1:A|B|C = {a:1,b:'1',c:1n} // fail
  const t2:A|B|C = {a:1,b:'1',c:'1'} // fail
  const t3:A|B|C = {a:1,b:1,c:1n} // fail
  const t4:A|B|C = {a:1,b:1,c:'1'} // fail
  const t5:A|B|C = {a:1n,b:'1',c:1n} // fail
  const t6:A|B|C = {a:1n,b:'1',c:'1'} // fail
  const t7:A|B|C = {a:1n,b:1,c:1n} // fail
  const t8:A|B|C = {a:1n,b:1,c:'1'} // fail
}
{
  type A = {a:number,b:number,c:number}
  type B = {b:string,c:string,a:string}
  type C = {c:bigint,a:bigint}
  const t1:A|B|C = {a:1,b:'1',c:1n} // fail 
  const t2:A|B|C = {a:1,b:'1',c:'1'} // fail
  const t3:A|B|C = {a:1,b:1,c:1n} // fail
  const t4:A|B|C = {a:1,b:1,c:'1'} // fail
  const t5:A|B|C = {a:1n,b:'1',c:1n} 
  const t6:A|B|C = {a:1n,b:'1',c:'1'} // fail
  const t7:A|B|C = {a:1n,b:1,c:1n} 
  const t8:A|B|C = {a:1n,b:1,c:'1'} // fail
}
```

The *union* operations looks something like matching subsets of the instance against the 'whole' subtypes under the *union/intersection* tree, and then sometimes allowing at least one partial subset to finish it off. 

It looks complex enough that I'd prefer reading the specifications (also covering *intersection*, `?` marked keys, `[key:string]:T` additional key specifiers) to avoid misunderstanding. 

## 📃 Motivating Example

It's a good idea to make public the documentation for the behavior of core algorithms, e.g., typescript type processing.  Mostly it works as "expected" but there are enough edge cases to create some unnecessary surprises.

## 💻 Use Cases

I would like to use the rules to write precise specifications for Typescript native behavior when interfacing with external software - e.g., using JSON Schema. Having no precise documentation makes this hard and there is really no workaround.

**Comment by MartinJohns** [comment]
> reading the specifications

Unfortunately TypeScript has no specification.

**Comment by craigphicks** [comment]
In the "Use Cases" section, we are asked to describe a workaround.  I am adding this psuedo-code as an approximation for part of the problem:

**True OR with key merging**

Psuedo-Code::
```
mapOperandToDomain<number,Set<string[]|Infinity>>

For each i of [0,...,operands.length-1]
  If operands[i] has additionalKeys
    mapOperandToDomain.set(i,Infinity)
  else 
    mapOperandToDomain.set(i,operands[i].keys())

function valid(data):boolean{
  const atLeastOneOperand=false
  const satisfiedSet = new Set<string[]>
  For each i of [0,...,operands.length-1]{
    pickedKeys=pickKeys(data,mapOperandToDomain.get(i))
    if (valid(pickedKeys,operands[i])){
      atLeastOneOperand=true
      addKeysTo(satisfiedSet, pick(data,mapOperandToDomain.get(i))
    }
  }
  return atLeastOneOperand && equalKeys(satisfiedSet,data.keys())
}
```
It's a reasonable approximation to the observed behavior shown in my original post above.  Like the observed behavior, whole operands matched,  but unlike the observed behavior their is no "sometimes" partial matching of operands  - i.e. no partial matches are allowed.  (I haven't tested it though ... ) 

Another workable solution would be "always" partial matching, i.e., one key at a time, while requiring all keys be matched.  However that seems further from the actual current behavior than the psuedo-code.

**Comment by craigphicks** [comment]
From (Release Notes 3.5)[https://devblogs.microsoft.com/typescript/announcing-typescript-4-2-beta/]

> In TypeScript 3.5, the type-checker at least verifies that all the provided properties belong to some union member and have the appropriate type, meaning that the sample above correctly issues an error.  Note that partial overlap is still permitted as long as the property types are valid. 

Not stated, but implicit, is that at least one member type must also be completely satisfied.

I believe that answers my question, so I am closing this issue.
