### ISSUE TITLE
Regression with unions introduced in typescript 4.2

### ISSUE THREAD

**Issue by dfilatov** [microsoft/TypeScript#42935]
# Bug Report

There's a regression with unions is introduced in typescript 4.2

### 🔎 Search Terms

union, spread, 4.2

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeAoK6pgE4HswEYB+ALigFcA7AEwgDMBLCiKgbjQ2zwCYTzq7GzNgF8oAH2Tt0nAqQDOwLIwDmbDJlxge8xSpFsUAYxwUFUAEak4iJBrz5SAcgKOANHa1OtjqMIPHTYCgAQysESXUAOmjzKEILKFIkYRQ-IA)

### 💻 Code

```ts
type A = {
    prop1?: undefined;
    prop2?: undefined;
} | {
    prop1: string;
    prop2?: string;
};

const b: A = { prop1: 'p1', prop2: 'p2' };

const a: A = {
    ...b ? b : {}
};
```

### 🙁 Actual behavior

Error:
```
const a: A
Type '{ prop1?: string | undefined; prop2?: string | undefined; }' is not assignable to type 'A'.
  Type '{ prop1?: string | undefined; prop2?: string | undefined; }' is not assignable to type '{ prop1: string; prop2?: string | undefined; }'.
    Types of property 'prop1' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.(2322)
```
### 🙂 Expected behavior

No errors

ts 4.1.5 works as expected, without errors

**Comment by sandersn** [comment]
@ahejlsberg When you looked at this earlier, did you figure out whether this new error was working as intended?

I'll bisect when I have time if you didn't investigate this already.

Initial poking around shows that the repro requires `--strict` to succeed on 4.1 -- both 4.1 and 4.2 have the same error without strict.

**Comment by sandersn** [comment]
Broken in #42233. @weswigham can you figure out if this was an intended break from that PR?

**Comment by weswigham** [comment]
Yeah, this was an intentional reduction in spread accuracy - typically there's a _lot_ of exists-of-empty-object spreads like this in a single object (eg, for css or props in the wild), and so the higher accuracy spread logic just costs too much (has exponential check times).
