### ISSUE TITLE
TS2545 and TS2556 triggered, failure to resolve constructor signature on type alias of intersection

### ISSUE THREAD

**Issue by 6XGate** [microsoft/TypeScript#42940]
# Bug Report

### 🔎 Search Terms

- `TS2545`
- `TS2556`
- `TS2556 intersection`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about TS2545

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/PTAEB5NARBTAzAlgO1gE1C0AXAFogJzQFoAHAQwO1ABtEAjAygTwBpQBjc5ZAe2vqxOubgHN0AWABQHGuQDO80AGFeAW1K9UyagG9QAfQCuiDAF5QAWXJ4AdE2Rp1ACgCUoAL7TszUkNUaWrA6ynKKoBb6qADuoM62CZSi8gBcoNzMANoAuq5pAZra1B6gAGQ4vrC88CrqhcHYANygIBCgABIKOLhCHFry2ARGHNi8BKDRiHig8iiiNEIEsAPpBKJGag2g1enIWdm20vBGyCOIWpx1QTrgysqgsAAe2MFoSgXX2KEK8gB8zrJUiplHlgaB9EtsEYCMhODQlF4pK1fiiYAgUOhMLC8IQSBQqLQGEwCGxONw+AJeiJkOI0NJpK0AGLkRDwhK2UD0IzUPBCchoNBTc7Icg0S7IAZMFDYJSURawACOJiWGG4GCWSsImL6EsGw1G42gAHkAKIAZQej0QAyOJzOF0siEe4AAQgohE8Xo53lcit9FP96O60m75LB3LppKBo6AAAJ9QJFKMx2Q-KxOy1et6c93glpgAAqZoATABWAAspfY0VwzAA-N1ev09SMxpglGh0agMPA27yKn56VIY54hyPIdDYY7Ho1pIiGWBmaz5OyZrBYGolP2a7wFu35EYhNbQPAWTRoUJRqAlvJdwA3S89GZGPwEYBBsPiyX6ttcGhi2ZRBFKElkOKRjlObBhXTR5i1dXNPVeH1Ewaf0-mcD9YBDd0I2TaN419Bo8LhNNp2LTMkJzT99FaIsy0rdhmFgchcGrIQAGs+GidguWoAZWTFGt62IkcdW-VsCHiRI1lSDIcgjZ9Xyk2wknkdwSloktS1LAA2VdeFYxtLg0VlYHGU9lxwXhr2We9HybXUhgkmZECAmwLzAkd52HGMJxhGDi1nKRESAA)

### 💻 Code

```ts
// <<< Defined in third-part library, cannot be changed
class Component { _uid = Math.random() }
type ComponentClass = { new (...args: any[]): Component } & typeof Component; // < Has the constructor with single rest argument of any[].
function component<CC extends ComponentClass>(cls: CC): CC { return cls }
// >>> Defined in third-part library, cannot be changed

// Fails... but the additional constraints are required and required constructor DOES exist
function Mix<Base extends ComponentClass>(base: Base) {
    @component
    class Mix extends base { // TS2545, why? the constructor is defined for the type

    }

    return Mix;
}

// Fails... seems the whole issue is failure to resolve the super/base constructor call signature.
function Mix2<Base extends ComponentClass>(base: Base) {
    @component
    class Mix2 extends base { // TS2545, yeah, we know, but still why?
        constructor(...args:any[]) { super(...args) } // TS2556... oh, the compiler fails to resolve the constructor signature.
    }

    return Mix2;
}
```

### 🙁 Actual behavior

TS2545 generated when trying to use an intersection type alias as the base of a mixin.
TS2556 if I attempt to provide a constructor on the mixin.

### 🙂 Expected behavior

This would compiles and works

**Comment by rbuckton** [comment]
`typeof Component` produces a type that contains both the static members of `Component` along with the existing construct signatures of `Component` (in this case, `new () => Component`). Intersections preserve both the structure and the signatures of each constituent type, leaving you with a type that has an overloaded construct signature.

To avoid this, you need to strip off the existing construct signatures using a mapped type. The easiest way to do this is with `Omit`:

```diff ts
- type ComponentClass = { new (...args: any[]): Component } & typeof Component;
+ type ComponentClass = { new (...args: any[]): Component } & Omit<typeof Component, never>;
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.1.5#code/PTAEB5NARBTAzAlgO1gE1C0AXAFogJzQFoAHAQwO1ABtEAjAygTwBpQBjc5ZAe2vqxOubgHN0AWABQHGuQDO80AGFeAW1K9UyagG9QAfQCuiDAF5QAWXJ4AdE2Rp1ACgCUoAL7TszUkNUaWrA6ynKKoBb6qADuoM62CZSi8gBcoNzMANoAuq5pAZra1B6gAGSgAPJqiNjgPn688CrqhcHY7KgAbrAEAHwA3KAgEKAAEgo4uEIcWvLYBEYc2LwEoNE1uKDyKKI0QgSwc+kEokZqbaCN6chZ2bbS8EbIS4hanC1BOuDKyqCwAB7YYJoJQFT7YUIKeS9ZyyVIqZR5BGgfQHbBGAjITg0JReKTDXqEmAIFDoTBYvCEEgUKi0BhMAhsTjcPgCaYiZDiNDSaTDABi5EQOIStlA9CM1DwQnIaDQNVeyHINHeyDmTBQ2CUlH2sAAjiYDhhuBgDvrCGSZqr5otlqtoBUAKIAZT+-0QcweTxeb0siH+4AAQgohACgY5QR8ipDFDD6MG0kH5LB3LppKB06AAAIzQJFNMZ2RQqx+11hkFi4MooZgAAqToATABWAAsjfY0VwzAA-JNprNrUsVpglGgSagMPAh1KcL5YDypBnPPPF2iMVjff9+tI8bywAKhfIRVtYLA1Eppx3eHth-IjEJ3aB4IKaBihMtQAd5Ffur2tkY-AQwBxkmKpqjaQ5cDQyrbKIirogc9xSI8zzYAqxb-PWgaVqGwIRrmbTRtCzjAbACbBim+bptmkZtJR2JFhu9alrhFYgfowx1k2rbsMwsDkLg7ZCAA1nw0TsOK1BzEKyodt2dGLpaYGDgQ8SJCcqQZDkKZ-gBqm2Ek8juCUHENo2jYAGxHrwAm-jmpBCj0j7PuevAfoc35vlMoEDraWyILBNivohi47guGarpi6H1luUh4kAA)
