### ISSUE TITLE
es2020.intl.d.ts is inaccurate

### ISSUE THREAD

**Issue by longlho** [microsoft/TypeScript#42944]
# lib Update Request
- `fractionalSecondDigits`, `dateStyle`, `timeStyle`, `dayPeriod` are in ES2021 draft, not ES2020.
- NumberFormatOptions should have the list of sanctioned unit to prevent `RangeError`.

Reference upstream issue: https://github.com/formatjs/formatjs/issues/2616

## Missing / Incorrect Definition

lib/es202.intl.d.ts

## Documentation Link

https://402.ecma-international.org/7.0/

**Comment by orta** [comment]
In with https://github.com/microsoft/TypeScript/pull/45647 👍🏻
