### ISSUE TITLE
Unable to nest Extract generic inside conditional

### ISSUE THREAD

**Issue by mattkrick** [microsoft/TypeScript#42946]
# Bug Report

### 🔎 Search Terms

Generic, nested generics, Extract, inner join, intersection, union 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `never`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210224#code/C4TwDgpgBAYg9nAJlAvFA5AQzGANhAL3SgB8MAjTAO2s2LPTAEsCC6AoUSWAJwFcmwVBmx4I9CrRrp2ncNADqcHgGsmVAOYBBXLgBqEHuTgBnaGnhIoEAB7AIVRCagAKGP0HW7Dp7ATIAfl4BIQAuKCoIADdDAEooIMtkcMiYnjluJVV1DQB5PnseAFE7HkwAYyELfy97R2cS4DLKgB53EIAaPyQAPgTu5IjowwzFZTVNAEkqSJ4DI1NzKEbm4Db-LvbPWzrfJP6tsKG0ntGoACEeOBUHadmViqrl0sf1pC6H1sPN-x7Ts7uhgAUnB1C0ACodACqfTQ4NqPmcLihCPqUHhQRRKWGPHiQXhUFCqRGXGgl2uDnBEBMwAA4g5DExysJATwQWCkpsPMBTkA)

### 💻 Code

```ts
type Food = 'applez' | 'banana' | 'pizza'
type Fruit = 'apple' | 'banana'

type WorkingAllVerbose = Food extends (Fruit extends Food ? Fruit : never) ? Food : never // never
type WorkingOuterExtract = Food extends Extract<Fruit, Food> ? Food : never // never
type WorkingInnerVerbose = Extract<Food, Fruit extends Food ? Fruit : never> // never
type BrokenInnerExtract = Extract<Food, Extract<Fruit, Food>> // 'banana' 🙁
```

### 🙁 Actual behavior

`BrokenInnerExtract` is syntactically identical to the 3 types above it, but it has type `banana`

### 🙂 Expected behavior

`BrokenInnerExtract` should be of type `never`

**Comment by RyanCavanaugh** [comment]
These aren't the same because the type expression `Fruit extends Food ? Fruit : never` isn't distributive over `Fruit` the way `Extract` is. This identical to a nondistributive `Extract`:
```ts
type NonDisExtract<T, U> = [T] extends [U] ? T : never;
type WorkingInnerVerbose = Extract<Food, Fruit extends Food ? Fruit : never> // never
type TrueEquivalentInnerExtract = Extract<Food, NonDisExtract<Fruit, Food>> // never
```

**Comment by mattkrick** [comment]
Thank you so much for the quick & thoughtful response!
Wrapping T & U so they can't distribute makes sense, although I still have a mental block on why abstracting it into a generic makes it distributive. If you have a reference link I'd love to learn more, but happy to close this & read up on type theory.

**Comment by RyanCavanaugh** [comment]
I need to write a big FAQ entry on it
