### ISSUE TITLE
Change JSDoc @typedef to not apply to following expression

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#42949]
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Change JSDoc `@typedef` to not apply to following expression

## 📃 Motivating Example

Using `@typedef` like `interface` is great for JS files. But if any expression comes after it, TypeScript tries to apply that typedef to that expression. This means we have to make sure to put it at the end of a file and make sure nothing comes after it. Not ideal.

## 💻 Use Cases

See above.

**Comment by RyanCavanaugh** [comment]
@sandersn plausibility check?

**Comment by kungfooman** [comment]
I don't understand this, can you make a full example?

**Comment by sandersn** [comment]
`@typedef` is usually supposed to be independent of the following statement, except for grabbing its name if you leave it off. It definitely should not apply the defined type to the following expression. 

Any example I can think of is a bug, so please do post any you find.
