### ISSUE TITLE
Date.toLocaleDateString signature incorrect

### ISSUE THREAD

**Issue by gwicksted** [Microsoft/TypeScript#4294]
It is incorrectly defined as no arguments in both `lib.d.ts` as well as the most recent DefinitelyTyped `date.format.d.ts`

[See spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)

I believe it should be this:

```typescript
toLocaleDateString(locales?: string[] | string, options?: Intl.DateTimeFormatOptions): string;
```

JavaScript example:

```javascript
var date = new Date(Date.UTC(2015, 8, 12, 9, 41, 0));
console.log(date.toLocaleDateString(['en-US'], { month: "2-digit" }));
// will write "08" to the console
```

NOTE: I believe toLocaleTimeString has the same problem.

I am willing to submit a pull request -- I'm just not that familiar with writing jake tests.

**Comment by danquirk** [comment]
We generally don't write tests for lib.d.ts changes so you don't need to worry about that part.

**Comment by mhegazy** [comment]
@gwicksted I would add the overload in https://github.com/Microsoft/TypeScript/blob/master/src/lib/intl.d.ts, since it is using `options` of a type defined in that file.

**Comment by gwicksted** [comment]
Please review - I also added a parameter to the DateTimeFormatOptions that I noticed was missing and made a minor edit to the comments to reflect date + time formatting (toLocaleString) vs just date formatting (toLocaleDateString).

**Comment by mhegazy** [comment]
thanks @gwicksted !
