### ISSUE TITLE
lib.d.ts: Incorrect MessageEvent constructor signature.

### ISSUE THREAD

**Issue by jduc88** [Microsoft/TypeScript#4295]
# Description:
MessageEvent constructor signature should be same as base Event class ie.
> new(type: string, eventInitDict?: EventInit): MessageEvent;

instead of,
> new()

# Documentation:
http://www.javascripture.com/MessageEvent

# Error message on chrome: 
> TypeError: Failed to construct 'MessageEvent': An event name must be provided.

**Comment by martinduparc** [comment]
This is a problem for progressevent too. Looking at https://github.com/Microsoft/TypeScript/pull/2314 @mhegazy talks about how some definitions are auto generated from the IE references. Looking at https://msdn.microsoft.com/en-us/library/windows/apps/hh466083.aspx, the progressevent seems fine so I am not sure what to do.

**Comment by mhegazy** [comment]
@zhengbli can you take a look.

**Comment by zhengbli** [comment]
Confirmed on Chrome and Firefox that both ``MessageEvent`` and ``ProgressEvent`` has a required parameter and an optional EventInit dictionary. IE and Edge both don't support the constructor, with or without parameters. I think we do need to change the signatures.

**Comment by zhengbli** [comment]
Fixed by #4469
