### ISSUE TITLE
Set object attribute/value from object attribute and not only from variable

### ISSUE THREAD

**Issue by Finnsoft** [microsoft/TypeScript#42954]
I'm sorry, someone may change the title because I really don't know the name for the feature...

You can set an object attribute via a variable like so:
```typescript
const baz = "foo";

const foo = { baz };
```

Now foo is ```{ baz: "foo" }```.

I really would like it to be possible to also set an object parameter as key/variable like so:

```typescript
const abc = { baz: "foo" };

const foo = { abc.baz };
```

Now foo should also be ```{ baz: "foo" }```.

**Comment by RyanCavanaugh** [comment]
This suggestion belongs at TC39, not TypeScript.

Also, to expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
