### ISSUE TITLE
noUncheckedIndexedAccess narrowing fails when utilizing a stored const string literal

### ISSUE THREAD

**Issue by berickson1** [microsoft/TypeScript#42979]
# Bug Report

### 🔎 Search Terms
noUncheckedIndexedAccess
string literal constant

### 🕗 Version & Regression Information

Introduced with noUncheckedIndexedAccess - present in all Typescript versions 4.1+
- This is the behavior in every version I tried, and I reviewed the FAQ for entries.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedParameters=true&ts=4.2.0-beta&ssl=1&ssc=1&pln=34&pc=2#code/MYewdgzgLgBAMgeQQaQKoAUD6yCiBNGAXhgHIoBTaEgbgChaAzAVzGCgEtwYAbEAcwByTALYAjcgCcAFADcAhtwBcMMCPESAlAG9aMGKEghu5AHS8+shRroBfRizacwMACYgAylCYMGU9mAAHJihlLQBtAGtyAE9laAl-PgBdZVUxSRsNGB09dgYYP0DgsMQUDGx8JKycvR5+IXTpfyCoEqQ0LFw8KuoYAHo+mABBCT4RcjBYEHyoaIDyUjT1GAAfGBYXcgZ-chcSGHYIFRBYOQgIdj4wOVFjGCgQGAC5CTlhcgoJGGn7uYWSJaSEi6GB2OzMVgcLhuTzeBgAJkKLVCkRicSgCTAyVSagy1RBeQKzWKZEoUBIVWyIL05ga6iRJIoVB6-UGAHUQBIIkczjByAAPeZsXYgsH0CGOaEeLw+dygeYuADC4GgckmDJC2VRsRg8USKRUuIkmSpegM0Bg8m4RFITPJdFy+Q1YStlJqNPqRudrusrOGo3Gk2+Mz+iyNq3WYE22zAu32h2Op3Ol2utwWDyeLzeH0kwd+8zDjWBejF9khTlc0rhAGYNcoAErkUASFwAHj1WIANIbGgA+fGOolFVqlDoVboD2q0r3EkftcpdFkDf1jd5Bn6zAsA8NrDZbHZ7A5HMAnGBnC5XG53DPPV7vT55zf-QESYug2h2MuS5wwmUMAAsdYwI2zZth2fDdi+-amgcTqzmEpLMpOHqCDOw4IXaFK+suHJcjyRwCkKFAuKKH5AA)

### 💻 Code

```ts
const LOOKUP_KEY = 'test';

function logNumber(val: number){
  console.log(val);
}
function doStuff(input: {[key: string]: number}) {
  if (input[LOOKUP_KEY]) {
    logNumber(input[LOOKUP_KEY]); // Argument of type 'number | undefined' is not assignable to parameter of type 'number'
  }
}
function doStuff2(input: {[key: string]: number}) {
  if (input['test']) {
    logNumber(input['test']); // Works as expected
  }
}

function doStuffScopedConstant(input: {[key: string]: number}) {
  const val = 'test';
  if (input[val]) {
    logNumber(input[val]); // Argument of type 'number | undefined' is not assignable to parameter of type 'number'
  }
}

function doStuff3(input: Record<string, number>) {
  if (input[LOOKUP_KEY]) {
    logNumber(input[LOOKUP_KEY]); // Argument of type 'number | undefined' is not assignable to parameter of type 'number'
  }
}

function doStuff4(input: Record<string, number>) {
  if (input['test']) {
    logNumber(input['test']); // Works as expected
  }
}
```

### 🙁 Actual behavior

In `doStuff`, `doStuffScopedConstant` and `doStuff3`, a compiler error is thrown, even though I've checked that a value exists for that index. When directly using a string literal inline (see other examples), this works as expected.

### 🙂 Expected behavior
All of the provided examples should compile cleanly. Having a stored constant string literal used as an index accessor should work the same way as using the literal in-place.
I suspect that the compiler logic for `noUncheckedIndexedAccess` bails out w hen there's any variable used as an index accessor. I'd expect that if there's a `const` that's also typed as a string literal, it should be treated the same way as using a string literal.

**Comment by MartinJohns** [comment]
#36230
