### ISSUE TITLE
Numbers are not interpreted as certainly truthy in if statement conditions

### ISSUE THREAD

**Issue by bl-ue** [microsoft/TypeScript#42988]
# Bug Report

In `if` statements, when the only conditional is a number, e.g. `123`, the compiler doesn't realize that any non-zero number is truthy and so it thinks the code inside may not be executed.  See my 3rd example.

### 🕗 Version & Regression Information

Happens in all versions available in the Playground (3.3.3, 3.5.1, 3.6.2, 3.7.5, 3.8.3, 3.9.7, 4.0.5, 4.1.5, 4.2.0-beta, Nightly i.e. v4.3.0-dev.20210226), at the moment.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210226#code/PTAEDEEMEsBsGdSUQUwB4AcUGMAuKATALlACIBBUAMwFcA7PaAeztAHcALJ+FUAnWJABOhULgCeWUNER0U0XBxRDQAcgBuTaAVWg6TFash1xugLY14uUCNw0hrSKHWRYNFADpQACgBMAZgBWQIBKUgAoWgZcZlZ8KwBGbxCSKyFoOgBzUABvcNAC6SofKlceENz8wurbe1ZSJVhYJlIAbiqCgF9w7vCQUAB1AwBrRGRQdCw8Qg9I+kYWMRQrX2TU3HSsyuroYu8N9wq86pqUOwcyRua2jtBu3v6oOER6SZx8AlhxElJweZjFoJsKMJnQCBlsrULlZIPgzCg6NZjAQbGc6mJJLwCExlnomNYMtg3Pw1PR+FQMoRVF4-P4AGx0sJ9MDkEx4ugAWgAXsomHoaGYAEbKCYuNyw3G4PkHRTiWZRBZxZa4fxrUBpCHbQq7HwJAJHW6nc71K4tdrVe7hIA)

### 💻 Code

```ts
// Fails as expected: "A function whose declared type is neither 'void' nor 'any' must return a value. (2355)"
function test1(): string {
    if (false) {
        return "hello";
    }
}

// Works as expected.
function test2(): string {
    if (true) {
        return "hello";
    }
}

// Fails unexpectedly: "Function lacks ending return statement and return type does not include 'undefined'. (2366)"
// Any non-zero number evaluates to truthy.
function test3(): string {
    if (123) {
        return "hello";
    }
}

```

### 🙁 Actual behavior

`test3` causes an error.

### 🙂 Expected behavior

`test3` should not cause an error, because 123 is always truthy and therefore the code block will always be executed.

**Comment by RyanCavanaugh** [comment]
We special-case `if (true)` since it's often used for debugging, but `123` is very rarely used for that.

**Comment by bl-ue** [comment]
But it seems like this should be taken care of 🤔
