### ISSUE TITLE
[Bug] Using Class as Object Type

### ISSUE THREAD

**Issue by mattia-lau** [microsoft/TypeScript#42982]
# Bug Report

### 🕗 Version & Regression Information

- This changed between versions 4.1.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/PTAEGUFcGNoUwM4NAYQPYBM4ChoBsBDJUAFUQBdQBvbUUAB0gCM8BLaUAgLlAXICdWAOwDmoALygARFIDctBszYcmPPoNETpc7AF9suNEL6g0TAFY8yJyVU48pARikAaUKukEpoXfOwhQADECVjxcQmJrcgAFQQA3AnI4agVGFnZ7XgFhMUkZeTp6eMTkj3UcrXy9AwDg0NQiZMdDY0oAMxC8RysKWNYEpK07bmlnHz9azoaEZIAmFpMO0Nmevj6B5NtMp1d3By8fIA)

### 💻 Code

```ts
// Success Code
class Test {
  public a: string = "";
  public b: string = "";
}

const obj: Test = { a: "1", b: "a" };

// Fail
class TestPrivate {
  public a: string = "";
  private b: string = "";
}

// Fail Case 1
const fail1: TestPrivate = { a: "1" };

// Fail Case 2
const fail2: TestPrivate = { a: "1", b: "a" }
```

### 🙁 Actual behavior

In this situation, we may `delete` the private parameter or change the `private` modifier to `public`. However, even we dont replace the modifier key, it still can compile, but the editor will highlight it as an error.

### 🙂 Expected behavior

The expected result should be, we can assign Object with Type Test only contain property `a` with no error(s).

**Comment by MartinJohns** [comment]
This is by design. Your example is too trivial. Consider this more complex one:

    class TestPrivate {
        public a: string = "";
        private b: string = "";

        public static getB(instance: TestPrivate): string {
            return instance.b;
        }
    }


    // @ts-ignore
    const f: TestPrivate = { a: "1" };

    const b: string = TestPrivate.getB(f);
    b.length // Will fail, because b is undefined.

Static methods of the class are allowed to access private members, but these are `undefined` when you assign an object literal.
