### ISSUE TITLE
declare class compile to class with `emitDecoratorMetadata: true`

### ISSUE THREAD

**Issue by LasyIsLazy** [microsoft/TypeScript#42980]
# Bug Report

### 🕗 Version & Regression Information

- Unexpected compiler output
- Local TypeScript version: `4.2.2`

### ⏯ Playground Link

```ts
function Test(...args: any) {
    console.log(args);
}

declare class Person {
  firstName: string;
  lastName: string;
}

export class TestClass {
  @Test
  test?: Person = { firstName: 'a', lastName: 'b' };
}

```

<details><summary><b>Output</b></summary>

```ts
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
function Test(...args) {
    console.log(args);
}
export class TestClass {
    constructor() {
        this.test = { firstName: 'a', lastName: 'b' };
    }
}
__decorate([
    Test,
    __metadata("design:type", Person)
], TestClass.prototype, "test", void 0);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAFQKYGcoAoB0eCGATgOboBci+YAngJSIDeAUIq4hAunADao7dxiWIqVoBuJgF8mTACaoI3IqnZL06RAAVUhLkmatgMXVABy+ALaoKmQjDDEJrNWcvXEt+46kzUADwAHOEIoVXx1FAwoAGE1DQNEAAE0TBZEKCiAfgptXQREAF5GRCMTcysKAHJ8SoAaRBdy90qAI0rESQlpIA)
      

### 💻 Code

```ts
function Test(...args: any) {
    console.log(args);
}

declare class Person {
  firstName: string;
  lastName: string;
}

export class TestClass {
  @Test
  test?: Person = { firstName: 'a', lastName: 'b' };
}
```

A part of compiler output:
```
__decorate([
    Test,
    __metadata("design:type", Person) // Person is not defined
], TestClass.prototype, "test", void 0);
```

### 🙁 Actual behavior

The `Person` is a `declare class`, but it is compiled to a real class with `emitDecoratorMetadata: true`.
This leads to an Error: `ReferenceError: Person is not defined`

### 🙂 Expected behavior

I think it should behave like `interface`, so it should be compiled to `Object` at least.

**Comment by MartinJohns** [comment]
> I think it should behave like `interface`, so it should be compiled to `Object` at least.

I wonder, why do you think so? Using `declare` you tell the TypeScript compiler that this class **will exist**, it's just not you who provide the implementation. If the implementation is then missing then it should result in a runtime error.

**Comment by LasyIsLazy** [comment]
> > I think it should behave like `interface`, so it should be compiled to `Object` at least.
> 
> I wonder, why do you think so? Using `declare` you tell the TypeScript compiler that this class **will exist**, it's just not you who provide the implementation. If the implementation is then missing then it should result in a runtime error.

I used a npm package which exports a `declare class` and I want use it as my variable type so that I can get type support.

**Comment by RyanCavanaugh** [comment]
Writing `declare class` when there's no runtime class present is user error
