### ISSUE TITLE
Typesafe string concatenation

### ISSUE THREAD

**Issue by Trias** [microsoft/TypeScript#42983]
# Suggestion
## 🔍 Search Terms

string nan concatenation strict object

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

i was surprised that the following code typechecks:
```
console.log({} + "test") // with the result "[object Object]test"
````

a similar Problem with this code: 
```
const date = "2021-02-26";
console.log("logs" + + "/server-" + date); // result: "logsNaN2021-02-26
```

https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUBvAvgAgNTYCIAXWCIggSgFgAoW0SI7AEwEMTsBeQgJgAYeARgC0A4TwBsBANz1wUOIhSoCSZBAJ4tBAPQRYAJwBuh4ZvxsSFadh07sB0gFdoRAFyE1EAHKtv-IVEecQkgA

while this is obviously valid javascript, it's often a source of errors and it's a goal of typescript to prevent those.

I propose a strict check (name may be `--strictConcatenation`), which would only allow the plus operator with all strings or all numbers (or any type). If you actually wanted to convert an object to String you would have to call `toString()` explicitly  or a cast to `any`.

## 📃 Motivating Example

see above

## 💻 Use Cases
safer string concatenation
less bugs

**Comment by Zzzen** [comment]
checkout https://github.com/microsoft/TypeScript/issues/16895#issuecomment-312558441

**Comment by MartinJohns** [comment]
Related: #30239, #39194, #14114, #8891

I think this would belong more to the realm of linters. This is not really a type error, it's just undesired behavior.

- [no-base-to-string](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-base-to-string.md)
- [restrict-plus-operands](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-plus-operands.md)
- [restrict-template-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-template-expressions.md)
- [no-implicit-coercion](https://eslint.org/docs/rules/no-implicit-coercion)

**Comment by Trias** [comment]
@MartinJohns  Thank you for the tip! I will definitely  check it out.

This feature request is certainly on the boundary to the domain of linters. However, linters are often used to enforce coding standards, whereas this issue would be a type error in most typesafe languages. At least I would expect it from a "typesafe" Javascript.

While I respect that you set to scope of the project, I hope you reconsider from time to time.

If you are open to a pull request I would invest some time in it, however since its a rather large code base I'm not certain I will succeed.

**Comment by MartinJohns** [comment]
> issue would be a type error in most typesafe languages. At least I would expect it from a "typesafe" Javascript.

Unless the language provides implicit transformations to `string` (as JavaScript does).

> I hope you reconsider from time to time.

I'm not a member of the TypeScript team, I'm just a random developer. Not for me to reconsider anything. 🤷🏼‍♂️

**Comment by Trias** [comment]
I'm mistaken then. Let's hear what the typescript team has to say :)

**Comment by Trias** [comment]
@RyanCavanaugh I was hoping for a statement, whether the typescript team is open to reconsider their position from 2017, since "hints" such as this may prevent many bugs with little extra complexity. Also, since it's behind a flag, the change is fully backwards compatible with minimal runtime impact.

Hinting possible errors is one of the best features of Typescript for me (for example exhaustiveness checking, "forgot await", unchecked Indexed access...), which are all somewhat in the domain of linters. Also not everyone uses eslint or is aware of specific rules.

I implemented the feature just for fun, if someone wants to have a look: https://github.com/microsoft/TypeScript/compare/master...Trias:master
