### ISSUE TITLE
Check-time difference - interface vs type alias

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#42995]
# Bug Report

### 🔎 Search Terms
interface, type alias

### 🕗 Version & Regression Information

Tested with 896a2b49ac0a36f4093355f0011bf7232c5845e0 and I have no reason to believe things have changed since then.

### 💻 Code

Reduced from https://github.com/emotion-js/emotion/blob/master/packages/serialize/types/index.d.ts

```ts
import {PropertiesFallback} from 'csstype'

export type CSSProperties = PropertiesFallback<number | string>
export type CSSPropertiesWithMultiValues = {
    [K in keyof CSSProperties]: CSSProperties[K] | Array<Exclude<CSSProperties[K], undefined>>
}

// export interface ArrayCSSInterpolation extends Array<CSSInterpolation> { } // Check time = 1.2 seconds
export type ArrayCSSInterpolation = Array<CSSInterpolation>; // Check time = 0.5 seconds

export type InterpolationPrimitive = null | undefined | boolean | number | string | CSSObject

export type CSSInterpolation = InterpolationPrimitive | ArrayCSSInterpolation

export interface CSSOthersObject {
    [propertiesName: string]: CSSInterpolation
}

export interface CSSObject extends CSSPropertiesWithMultiValues, CSSOthersObject { }
```

### 🙂 Expected behavior

Check time is more or less the same, regardless of which `ArrayCSSInterpolation` declaration is used.

### 🙁 Actual behavior

The interface takes ~3X as long to check.

**Comment by amcasey** [comment]
@DanielRosenwasser suggested that `checkInheritedPropertiesAreIdentical` might determine that the properties are identical and then do _more_ work.

**Comment by DanielRosenwasser** [comment]
Well that's part of the work to see if there's any conflicts that haven't been resolved. I suspect the "more work" is the actual slow work.

**Comment by ahejlsberg** [comment]
The fundamental difference between the two declarations is that the aliased type is another array type whereas the interface type is a distinct new object type that happens to inherit from `Array<T>` and therefore acts like an array in most cases. Use of the interface type will cause structural evaluation of type operations in lots of places. For example, when relating the aliased type to some other array type we simply relate the element types. But when relating the interface type to an array type we relate all of the individual members (and there are many methods on an array).

**Comment by amcasey** [comment]
Sounds like this is the expected effect of losing array-ness.  I don't think this is common enough that we'd want to add a special case for this pattern.  Thanks!
