### ISSUE TITLE
keyof-based lookup into mapped type is treated as not assignable

### ISSUE THREAD

**Issue by taymonbeal** [microsoft/TypeScript#42994]
# Bug Report

### 🔎 Search Terms

mapped types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types and `keyof`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210226#code/JYOwLgpgTgZghgYwgAgLIE8Aq6AOFVw7IDeAsAFDLIwD2NAXMgM5hSgDmA3BVQEZxRGIAK4BbXtG7kAvhQoIaIFsgBiAVQByAYUwBJAPIaAyo2IBtACLJQyANYR0NGGiy58hALqMAFADc4ADbCEIwY2HgEOJYeAJTIALwAfMi+NMAAJtIJJDzUdH6BwXFklFTICko0ARAAdAE07AVBtWA0ADI0AO7QWnBMEN4xMVJU0gA0ufxQTUU5pVQVTFW19Y3+zcgA9MgATMO54xTSUhQwwiAIYMCKyDhQNEhMTAA8ANLIEAAekCDpTHYOJwucLuHCJbz2dCMV5jFKFELAtyRMyvWJzBaKZRnC4+dbBUKuCKEFFopIpNLpbLqbR6QxGMyQjwjajnBAzCD7GQUIA)

### 💻 Code

```ts
interface MyTypeMap {
  foo: string;
  bar: number;
}

const FUNCTIONS: {[D in keyof MyTypeMap]: (value: MyTypeMap[D]) => void} = {
  foo(value) {
    console.log(value.toLowerCase());
  },
  bar(value) {
    console.log(value / 2);
  },
};

function process<K extends keyof MyTypeMap>(key: K, value: MyTypeMap[K]) {
  const func: (value: MyTypeMap[K]) => void = FUNCTIONS[key];
  func(value);
}
```

### 🙁 Actual behavior

This fails to compile with the following error on line 16:
```
Type '{ foo: (value: string) => void; bar: (value: number) => void; }[K]' is not assignable to type '(value: MyTypeMap[K]) => void'.
  Type '((value: string) => void) | ((value: number) => void)' is not assignable to type '(value: MyTypeMap[K]) => void'.
    Type '(value: string) => void' is not assignable to type '(value: MyTypeMap[K]) => void'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'MyTypeMap[K]' is not assignable to type 'string'.
          Type 'string | number' is not assignable to type 'string'.
            Type 'number' is not assignable to type 'string'.
```

### 🙂 Expected behavior

This should compile without errors, because `{ foo: (value: string) => void; bar: (value: number) => void; }[K]` and `(value: MyTypeMap[K]) => void` are the same type and should be recognized as such.

(Sorry for the less-than-totally-clear issue name; I wasn't sure what to name this issue.)

**Comment by RyanCavanaugh** [comment]
This is a correct error. It's legal to call `process` like this:
```ts
const m = Math.random() > 0.5 ? "foo" as const : "bar" as const;
process(m, 42);
```
`extends keyof` doesn't mean "is exactly one of them". See #27808
