### ISSUE TITLE
【Question】publish a chinese document

### ISSUE THREAD

**Issue by Jairwin-L** [microsoft/TypeScript#42998]
# Suggestion

I hope the official can publish a Chinese document, which will make it easier for developers to use the document, thank you

**Comment by RyanCavanaugh** [comment]
See https://www.typescriptlang.org/zh/docs/ . We are accepting PRs to translate pages on these.

**Comment by Jairwin-L** [comment]
I have seen this link, but pr should be completed by relatively professional and authoritative personnel, and it may be necessary for the official to promote this matter.
