### ISSUE TITLE
Go to definition in Visual Studio 2015 on a private method

### ISSUE THREAD

**Issue by laurentiustamate94** [Microsoft/TypeScript#4299]
In Visual Studio 2015 Community Edition, running the latest ts 1.5.4.0, when I try to go to the definition (F12) of a private method or attribute in an external class it crashes the IDE. I agree it should not navigate, but it shouldn't crash the environment.

**Comment by danquirk** [comment]
See https://github.com/Microsoft/TypeScript/issues/4129
