### ISSUE TITLE
'infer function return type' refactoring always shown

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#42993]
# Bug Report

### 🔎 Search Terms
- refactoring
- quick fix
- code action

### 🕗 Version & Regression Information

4.2.2

### 💻 Code

```ts
function foo() {
    return 1;
}
```

1. In VS Code, place cursor anywhere inside of `foo`

### 🙁 Actual behavior

The lightbulb always shows up. This is because the `infer function return type` quick fix is always being returned

### 🙂 Expected behavior

This quick fix should likely only show when refactoring are explicitly requested or if the cursor is at a specific spot in the code (such as the function signature)

/cc @jessetrinity

**Comment by mjbvz** [comment]
I have a feeling the ever present lightbulb is going to spawn a lot of issues when the next VS Code release goes out so I'm going to add a workaround on the VS Code side

**Comment by jessetrinity** [comment]
Is this fixed by #42737?

**Comment by mjbvz** [comment]
Yep looks like the same issue. I've checked in a workaround on the VS Code side

**Comment by jwbth** [comment]
Oh _that's_ why I didn't see the item for "Infer function return type" in the autocomplete menu...
![Image](https://github.com/user-attachments/assets/3bb17502-f836-4820-a21e-0fd331608c37)
Good thing I though of searching the source.
