### ISSUE TITLE
Incorrect type inference of deep nested types

### ISSUE THREAD

**Issue by captain-yossarian** [microsoft/TypeScript#43009]
# Bug Report

### 🔎 Search Terms

[SO question](https://stackoverflow.com/questions/66346104/typescript-incorrect-type-inference)

### ⏯ Playground Link
[Playground](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/C4TwDgpgBAWgogJQPJQLxQAwChSSgOQgA9gAeAFQD40pypjgIA7AEwGdZEUB+KAbygA3AFydkUAL5RRACjoNm7fkNEBLJgDMIAJygBVSVF4CRBBqT3UpophEE6AlFhzhoSfHBqESpeMkoueOQA6ijo3mTucAG40OQAEghwnuHmIUgxrlAAYkh6CF5picmZeNkAkgBqKWY+ufml0ADK5QAahXVV0YHNcNX4HWQtrY1QcOUA4vF0qT5NfXD4o-jlHoOk41NUPbSL6yseATvkcACOFAA0UAAK1OjyJIoc10ZQMi8KrBx0vMDaAK7QGx2RzSKC2ezaZwAGwgwCEAEZRCdzukruk7lA-oCoAB6XFQADGAHttNoIITgKJYhxVBwIKd-gBDaFYWHwwQAZmRZ1Iwyu836mOx0Hx9DJpNEAHcABYgLFZYkaIScqDqLRkiAsKBMjgi7jOWJQBAQNj-aHw+68-lQQWLI5Gk1mi0AfWAMogLrYTIAtp6jeg+FgoCGVPxg6HI6Yg5HY6HoxG40mwzHk2mQwn01n46I-EgANyJ7OxiSF4uh0tF5OV6tliuFqSfJSpjOiFuxzNZzvl7vlnPhvtp3uD5OmPNVkchmuTyR18vT9MLktz2dYKS-AFAqAaFlsUUEnfQvfOXEAKlPwdPUGCcuNpvN8LpWM3l51rDvzuAbo9Xt9-qyT6HseUCnriQA)

### 💻 Code

```ts
type ZERO = 0
type Next<T> = T extends ZERO ? { v: ZERO } : (T extends { v: infer U } ? { v: Next<U> } : never)

type ONE = Next<ZERO>
type TWO = Next<ONE>
type THREE = Next<TWO>
type FOUR = Next<THREE>
type FIVE = Next<FOUR>
type SIX = Next<FIVE>
type SEVEN = Next<SIX>
type EIGHT = Next<SEVEN>
type NINE = Next<EIGHT>
type TEN = Next<NINE>

type TEq<T, P> = T extends P ? (P extends T ? true : never) : never

let v1: TEq<TWO, TWO> = true // correct: types is equal
let v3: TEq<SIX, SEVEN> = true // error: why type of v3 inferred as true?

type Result = TEq<SIX, SEVEN>

type Result_the_same_type = {
    v: {
        v: {
            v: {
                v: {
                    v: {
                        v: ZERO;
                    };
                };
            };
        };
    };
} extends {
    v: {
        v: {
            v: {
                v: {
                    v: {
                        v: {
                            v: ZERO
                        };
                    };
                };
            };
        };
    };
} ? true : false // false

/**
 * Why Result is true
 * and Result_the_same_type is false
 */
```
As you see `Result` and `Result_the_same_type` are structuraly equal. 
### 🙁 Actual behavior

Result is true 
Result_the_same_type is false

### 🙂 Expected behavior

Result should be false

**Comment by RyanCavanaugh** [comment]
See https://github.com/microsoft/TypeScript/issues/35533#issuecomment-574719956

**Comment by DarkGenius** [comment]
> See [#35533 (comment)](https://github.com/microsoft/TypeScript/issues/35533#issuecomment-574719956)

Is there some workaround for this case?

**Comment by captain-yossarian** [comment]
@DarkGenius what about:
```typescript
type AllowedLevels = 1 | 2 | 3 | 4 | 5;

type Levels<T, Cache extends Array<any> = []> = {

  [P in keyof T]: T[P] extends object ? Levels<T[P], [...Cache, 1]> : Cache

}[keyof T];

type Allowed<T> = Levels<T> extends { length: AllowedLevels } ? true : false;

type Result=Allowed<SIX> // true
type Result2=Allowed<SEVEN> // false
```
