### ISSUE TITLE
Unexpected assignable types related to string enum

### ISSUE THREAD

**Issue by chochihim** [microsoft/TypeScript#43002]
# Bug Report

### 🔎 Search Terms

Sorry I am not familiar with the terms so I don't know what to search

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBAwghgF2AcwPYCcCeUDeAoKKAY0QEYoBeKAIhIVOoBoDjEAmSmutpvAXzx4iqEAGcEUAEZx0pAFxQASsGHoAJgB5wEScHSMo23egB8nHAOFiJ09GwX5CAM1SoFABRkIAlnAA2GsqqmvBIaFgGkq5+wHAgJib85iwubrgshHTyUE7+osDMhJnsCrl++YVQfMwCtmwAdKmctqRAA)

### 💻 Code

```ts
enum Category {
  cat1 = "cat1",
  cat2 = "cat2",
}

const bar1: Record<number, number> = {}
const bar2: {
  foo: Partial<Record<Category, boolean>>
} = {
  foo: {
    cat1: false,
    cat2: false,
  },
}
bar2.foo = bar1
```

### 🙁 Actual behavior

`bar1` can be assigned to `bar2.foo`

### 🙂 Expected behavior

`bar1` cannot be assigned to `bar2.foo`

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Without some explanation of why you think it shouldn't be allowed I'm not sure how to correct the misapprehension.

**Comment by chochihim** [comment]
@RyanCavanaugh Why is this intended?

I simplify my example [here](https://www.typescriptlang.org/play?#code/KYOwrgtgBAwghgF2AcwPYCcCeUDeAoKKAY0QEYoBeKAIhIVOoBoDjEAmSmutpvAXzx4ANsARQAZqlSkAXFAAKcdAgCWcIQB4ASsCIYAJhvhI0WRlABGUkXBAA+O5xwCRYyajZyde9IfAQLYHRzf0D0RypnPHdyKnc2QVdLJVkFJVV1bV0DDQBnBHQVEGRzK1QbewjcF1Fk9E8obxzQoJDIMKqoixTObvqgA):

```ts
enum Category {
  cat1 = "cat1",
  cat2 = "cat2",
}

let foo1: Partial<Record<Category, boolean>> = {}
let foo2: Record<number, number> = {}
foo1 = foo2

let bar1: Partial<Record<string, boolean>> = {}
let bar2: Record<number, number> = {}
bar1 = bar2
```

I don't understand why `foo1 = foo2` has no error but `bar1 = bar2` does.
