### ISSUE TITLE
Generic constraints not being applied

### ISSUE THREAD

**Issue by Tinadim** [microsoft/TypeScript#43003]
# Bug Report

I'm having some issues with functions that receive generic types. Looks like that even if I constrain the generic types to simple types, like `T extends string`, this information is not used correctly inside of the function. See the example code below.

### 🔎 Search Terms

- Generics
- Generics constraints
- Generic function

### 🕗 Version & Regression Information

I'm using typescript version `4.0.5`, but I've tested in the playground and the issue seems to happen with all the other versions available in there as well

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [generics](https://github.com/Microsoft/TypeScript/wiki/FAQ#generics)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAYg9nAPAFQHxQLxWVCAPYCAOwBMBnKIgVwFsAjCAJygH4oBvKAQwC5soAvlD6c6fMsEYBLIgHNBAbgBQSgGZUiAY2BS4RKIQmIACrgLFylWg0aoAFFwBy1pn2MBKPvCTH07JVCBUIwQwFSM+v5B0dx8Ti6MADQBQQLKAkpAA)

### 💻 Code
```
type Foo<T> = T extends number ? { a: T } : { b: string };

function test<P extends number>(aNumber: P): Foo<P> {
    return {
        a: aNumber,
    };
}
```

### 🙁 Actual behavior

<img width="453" alt="example" src="https://user-images.githubusercontent.com/7933739/109427134-b3ffa980-79cf-11eb-9932-31c4222b6c7b.png">

### 🙂 Expected behavior

The generic constraint passed in the function should allow typescript to infer the right typings. 

### Additional Notes

The example provided above looks a bit silly and is not a real use case, but I'm facing the same issue with [this library](https://github.com/ajv-validator/ajv/blob/master/lib/types/json-schema.ts). They exposed a generic `JSONSchemaType<T>`, and I wanted to create a function to facilitate constructing json schemas with some common properties, like in:

```
interface Message<T> {
    data: T
}

type MessageSchema<T> = JSONSchemaType<Message<T>>;

export function createMessageSchema<P extends Record<string, any>>(dataSchema: JSONSchemaType<P>): MessageSchema<P> {
    const schema: MessageSchema<P> = {
        type: 'object',
        properties: {
            data: dataSchema, <-------------- errors here
        },
        required: [
            'data',
        ],
    };
    return schema;
}
```

The constraint `P extends Record<string, any>` should be enough for the library to identify the expected types for `properties`, however, seems like it can't infer the right type of `P`, and falls back to `never`.

**Comment by MartinJohns** [comment]
This sounds like https://github.com/microsoft/TypeScript/issues/39787#issuecomment-670477332.

**Comment by Tinadim** [comment]
@MartinJohns indeed. Should I consider this as a language limitation that can't be solved for now? Also, feel free to mark this as duplicate and close it.
