### ISSUE TITLE
enableProjectDiagnostics uses constantly 100% CPU 

### ISSUE THREAD

**Issue by Kokujou** [microsoft/TypeScript#43010]
# Bug Report

i just figured that "typescript.tsserver.experimental.enableProjectDiagnostics" constantly eats all of my CPU, this also results into some not-nice cursor flickering (like it's switching to the loading-cursor every few milliseconds). i disabled it and my CPU went back to normal.

and now i'll be constructive. I see two ways to fix it:

1. run the check once on startup and then only run it again on changed files (but also include changes like on regex replacements)
2. make the interval configurable. milliseconds is definitely too much for a checking interval. seconds, or even one minute might be enough.

this is really an awesome feature and one of the most annyoing things on a not-project-based programming language. now i can basically work with javascript like with c#, moving files is no problem anymore, renaming is the same. so i would personally consider this feature as most important.

### 🔎 Search Terms

diagnostics, enableProjectDiagnostics, cpu

### 🕗 Version & Regression Information

the bug occurred right after enabling the feature

### 🙁 Actual behavior

constantly 100% CPU usage 

### 🙂 Expected behavior

less CPU usage, a higher or configurable polling time for the re-check or a general optimized behaviour

PS: i tried to submit a bug [here first](https://github.com/neoclide/coc-tsserver/issues/265) but i was told to submit here.

**Comment by RyanCavanaugh** [comment]
How do we reproduce this?

**Comment by Kokujou** [comment]
interesting... the template had no reproducing i guess... otherwise i would've already told... 

it's kinda easy, just check out a relatively big project and enable the experimental feature in vscode: "typescript.tsserver.experimental.enableProjectDiagnostics".

then you can observe the task manager and your vscode should now consume 100% CPU.

**Comment by Kokujou** [comment]
i guess usually people don't report bugs and just disable the feature... that's how i would explain it.
I can't give an example here because our project is commercial, i would need to build an example projekt. 

but i can tell you that it's a javascript project which has a jsconfig and the "checkJS" flag enabled. obviously. We don't want to use typescript because of various reasons. (not official, additional build-step) so we are using the checkJS functionality in combination with JSDoc to make it work almost like typescript.

we're using the functionality of this feature to have project-wide reports on errors, which is very useful in case e.g. we do regex replacements or change some imports, or centralized classes. Or when we like now add jsdoc for typesafety.

i think you can just check out any bigger JS Project, turn on the feature and the checkJS of course and then you should see a very high CPU consumption - which is the problem. i tested it on our project and the second i disabled the feature and restarted the CPU consumption reduced rapidly. so it's without any doubt caused by this extension.

**Comment by zakton5** [comment]
I've been struggling with this issue for a while myself. In our code projects we use Material UI/React and whenever I open a TS file my machine slows a crawl. Just found this setting was enabled so I disabled it and now tsserver isn't eating  > 100% CPU.
