### ISSUE TITLE
Improve issue organization by grouping them to categories

### ISSUE THREAD

**Issue by blaumeise20** [microsoft/TypeScript#43014]
# Suggestion

This is not a direct feature for the language, but I think the GitHub repo could be improved by adding different "categories" to the issues.

For example, I (actually) wanted to make a suggestion about types, but there are over 2k open suggestions. So it would be really helpful if I could search for suggestions tagged "Suggestion: type system" or something like that.

I also think this would organize the issues better. I can understand that it is a lot of work to label all the existing suggestion, but it shouldn't be too hard for new suggestion.

---

Sorry that I didn't use any template because no template fits.

**Comment by RyanCavanaugh** [comment]
If GitHub adds hierarchical labels we'll use that, but the current system is optimized for our use cases. You can't combine the Good Text Search from the upper-left box with a label-specific search from the "Issues" tab anyway, so in practice this wouldn't be useful.
