### ISSUE TITLE
Change name of transpiled file if it matches the name of the output file to allow source maps to work

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4301]
see https://github.com/systemjs/systemjs/issues/636#issuecomment-130649492 for more details

from @guybedford comments:

To see the in-browser transpilation, open for example https://github.com/systemjs/systemjs/blob/master/test/test-typescript.html, and see that the original ES6 is not present in comparison to others. Looking at the original source it seems like the reason is that the source map looks like:

```json
{"version":3,"file":"es6-circular1.js","sourceRoot":"","sources":["es6-circular1.js"],"names":["p"],"mappings":";;QACW,CAAC,EACD,CAAC;IACZ;QACEA,EAAEA,CAACA,CAACA,CAACA,CAACA;YACJA,eAAAA,CAACA,GAAGA,oBAACA,CAAAA,CAACA;QACRA,IAAIA;YACFA,eAAAA,CAACA,GAAGA,oBAACA,CAAAA,CAACA;IACVA,CAACA;IALD,iBAKC,CAAA;;;;;;;YACD,CAAC,EAAE,CAAC"}
```
Where the sources and file name are the same. The point is that for in-browser transpilation we have to change the name of the transpiled source to `source.js!transpiled` so it can have a separate representation in the debugger, but the load.address argument provided to transpile at https://github.com/ModuleLoader/es6-module-loader/blob/master/src/transpiler.js#L78 becomes both the sources and file value.

**Comment by guybedford** [comment]
Thanks for looking into this, as mentioned in https://github.com/systemjs/systemjs/issues/636#issuecomment-130847617 it is actually working fine as-is. The `sourceMappingURL` on its own is enough to inform the debugging representation it seems.

**Comment by vladima** [comment]
closing as original issue is resolved
