### ISSUE TITLE
Allow to combine --build and --noEmitOnError=false

### ISSUE THREAD

**Issue by KnisterPeter** [microsoft/TypeScript#43013]
# Suggestion

## 🔍 Search Terms

rapid-prototyping, fast local development, ignore certain errors

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to see an option to combine the existing `noEmitOnError=false` behavior with the build mode.

## 📃 Motivating Example

Allow fast iteration on your code while prototyping.

### Fast iteration, local development

It is kind on annoying to test things out or debug sometimes in a bigger project with build mode.
Lets assume you need to build a feature and you start by importing things you will need. Note: Not every import used used currently. That may include an import which is completely unused.

This doesn't allow to iterate over your code, because it refuses to compile:

```shell
$ xxx/node_modules/.bin/tsc -b ./path/to/project
xxx/src/index.tsx:7:1 - error TS6192: All imports in import declaration are unused.

7 import { Script, BaseOptions } from 'vm';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
```

### Some debugging

A developer needs to debug an error. Do make it easier to understand, certain parts of the file are commented out.
That will result in unused imports and in some cases, this will prevent the file to compile.
Now all unused imports need to be commented out or be removed.

This is very annoying, since they need to be added later on again.

## Related context

As far as I know, this (`noEmitOnError=false`) does work on project builds.
In build mode builds this is refused with:

```sh
$ xxx/node_modules/.bin/tsc -b ./path/to/project --noEmitOnError=false
error TS5072: Unknown build option '--noEmitOnError=false'.

error Command failed with exit code 1.
```

**Comment by MartinJohns** [comment]
Related: #25613

**Comment by RyanCavanaugh** [comment]
#32651

> rapid-prototyping, fast local development, ignore certain errors

I always suggest searching for the terms you yourself put in the title, since this is what other people are likely to have done:

![image](https://user-images.githubusercontent.com/6685088/109691791-a9aeee00-7b3c-11eb-9a4c-4aea7c8b305a.png)

**Comment by KnisterPeter** [comment]
@RyanCavanaugh Sorry, I've searched a lot in the issues and didn't matched them. My fault
