### ISSUE TITLE
Interfaces and classes containing a function with an argument of type "this" cannot be properly set in generics   

### ISSUE THREAD

**Issue by Jet132** [microsoft/TypeScript#43015]
# Bug Report

### 🔎 Search Terms

- generic with callback
- this in callback argument

### 🕗 Version & Regression Information

This is the behavior in every version I tried (4.0.5, 4.1.4, Nightly), and I reviewed the FAQ for entries about generics.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210228#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyMAriAmMOiAOrBgAWAKo8AM4CCXUA5gFzIAFHD6CmHAJTIAvAD5kAN3TAAJgQC+BAqEixEKDOgBMyCAA9IIVezSYcBYsnboAthE6rVDaiDgAbAAUodAAHaDAAT0EQCEVoTW18KPDkAHEIWKhgBGZI8IAeZiMzS0ybO3QFGWRY+KgklJRmCHYwWXTM6By8wqNjOQBuAgB6EacJyamAPVnp0fHelAByfuXkVXRW2vR29jgqdhhI5CYUBBo2qDhdZFXMZYA6BeIl23QYZFCQ8Kgou7IFCoNHoTFYHG4nD461EKFAF1coQOwAARv4IM98GMJks7iIxJVjNJ5EoVKp1hwdu04Ox2MBeH40SgwFgmnjRAJKsSFMo1E8XpM3sgPl9RHB3HpbMsOTDrHcZchYch4W4kVQmZjsVNkMEwhETssXO5PN5gX4gj99RTbK4OHSQLxlSBTvkVkZ1ijSO0oBAAI6kYA+1ROl2pe4mJ5CYwAZgALLHJEA)

### 💻 Code

```ts
interface Foo {
    functionWithThisAsArg: (arg: this) => void
}

interface Foo2 extends Foo {
    someAdditionalProperty: never
}

type GenericType<TFoo extends Foo> = never

type Test = GenericType<Foo2>;
//                      ^^^^
// Type 'Foo2' does not satisfy the constraint 'Foo'.
//   Types of property 'functionWithThisAsArg' are incompatible.
//     Type '(arg: Foo2) => void' is not assignable to type '(arg: Foo) => void'.
//       Types of parameters 'arg' and 'arg' are incompatible.
//         Property 'someAdditionalProperty' is missing in type 'Foo' but required in type 'Foo2'.(2344)
```

### 🙁 Actual behavior

The generic `TFoo` in `GenericType` cannot be set to anything other than `Foo`.

### 🙂 Expected behavior

`TFoo` should be able to be set to other types extending `Foo`. Though the error reason provided is valid, it is not possible to run into that case.

Argument 'arg' from outside the function can be the following:

- `this` inside of `Foo` and `Foo2`
- `TFoo` inside of `GenericType`
- `Foo` when `Foo` is instantiated (If it were a class)
- `Foo2` when `Foo2` is instantiated (if it were a class)

It is not possible to pass `Foo` when `Foo2` is expected of the function.

**Comment by RyanCavanaugh** [comment]
This is a correct error. Otherwise you could write this:
```ts
const p2: Foo2 = {
    functionWithThisAsArg(self) {
        // If 'false', soundness was violated
        console.log("someAdditionalProperty" in self)
    },
    someAdditionalProperty: null as never
};

// Alleged: that this be allowed, not an error
let m: Foo = p2;
// Prints 'false'
m.functionWithThisAsArg({ functionWithThisAsArg() { } });
```

**Comment by Jet132** [comment]
hmm I see. Then methods with arguments of `this` should be avoided at all cost. Kinda sucks when implementing the observable pattern. Thanks 👍  

This is no help-forum but could I ask if you might know of a solution that allows for usage of `Foo2` for `Foo` without locking the type to `Foo`? The example here could just use a simple method but I have much more complex cases of cyclic referencing via several objects.

**Comment by RyanCavanaugh** [comment]
You'd probably just want to declare this with method syntax to get the (unsound) bivariance:
```ts
interface Foo {
    functionWithThisAsArg(arg: this): void;
}

interface Foo2 extends Foo {
    someAdditionalProperty: never
}

type GenericType<TFoo extends Foo> = never

// OK
type Test = GenericType<Foo2>;
```
