### ISSUE TITLE
Proposal class static block

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#43012]
# Suggestion

## 🔍 Search Terms
esnext, class

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

https://github.com/tc39/proposal-class-static-block is stage-3 。

I'm happy to implement this one if no one has already started the work(/cc: @rbuckton ).

**Comment by RyanCavanaugh** [comment]
Happy for you to write the PR, @Kingwl
