### ISSUE TITLE
Tagged type narrowing doesn't work when one of the tags is a union type

### ISSUE THREAD

**Issue by andriy-kudrya** [microsoft/TypeScript#43026]
# Bug Report

Tagged type narrowing doesn't work when one of the tags is a union type. Sorry, not sure how to be more descriptive

### 🔎 Search Terms

union narrowing

### 🕗 Version & Regression Information

3.9.7, 4.2.2, Nightly

- ~~This is a crash~~
- ~~This changed between versions ______ and _______~~
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _common bugs that aren't bugs_
- ~~I was unable to test this on prior versions because _______~~

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.2#code/JYOwLgpgTgZghgYwgAgILIN4Chm+WATwAcIAuZAcjgqwF8stRJZEUAhAYUxz0JPIoAjCsgA+lBDXpYAJhAQAbOFBQIA9iADOYZADc4CgK5k0Y5JwYKIOuOVQNgMZAAp9RiADo+KALx-K1ACUPLhwyD56BsYOTq5Rnt7IAIT+QiIAZOmR7l7EKCkRFJLBeMgA9GX4ecggylBqAO6gAObIMmoQmiAUOg1qUADWyAAW0BAANNnGI3CaVSTIAETo4pyLyKDaEHAyyGpOy4shyGERbtGy8koqyDCGIAhgwBobmqjOAB4C1GZpv8XkD6vAI0RixYBvOI5byBEp4CrzFC1KD1JogVrtTrdXr9IZNMDDRHIZqGZS7CDAAnQY6nKYQIA)

### 💻 Code

```ts
interface A {
    type: 'a'
}

interface BC {
    type: 'b' | 'c'
}

declare const value: A | BC

let a: A

if (value.type === 'a')
    a = value

if (value.type !== 'b' && value.type !== 'c')
    // type narrowing doesn't work here, value has type "A | BC" instead of "A"
    a = value

declare function isA(x: 'a' | 'b' | 'c'): x is 'a'

if (isA(value.type))
    // type narrowing doesn't work with type guard either
    a = value
```

### 🙁 Actual behavior

Type of ```a``` is _not_ narrowed to ```A```

### 🙂 Expected behavior

Type of ```a``` is narrowed to ```A```

**Comment by koushikkothagal** [comment]
I have a simpler use case of another instance where type narrowing doesn't work. 

The union type doesn't narrow unless the expression being checked in the `if` statement is exactly the variable itself. Any redirections in terms of variable assignments causes the type narrowing to fail.

```javascript
let a : string | undefined;


if (new Date().getHours() > 4) {
    a = "value";
}

let b = !!a;

if (b) {
    a; // should be string, but is still union type
}

if (!!a) {
    a; // type is narrowed to a string here.
}

```

TypeScript Playground link: [HERE](https://www.typescriptlang.org/play?#code/DYUwLgBAhhBcEGcwCcCWA7A5hAPhArugCYgBmGIRA3AFB2qkQAU6IA7hACJRghMCUAOkzgAEgHt8yBAIgA+CABZ+EAN40Im6BAC8EAEQA3KMHwh9tAL51QkAEa6IAQidRaNBszsr1W6FQgAekDEAAtJYCIIOxBEFAxMABpo-EhUBDjUYGACdFRxdAgwAE8ABxAaaw9GJhcoHw0tNyCQkvKIdIh0KGRkcTZKIvFtJDQsCFCQZBBBSpogA)

**Comment by MartinJohns** [comment]
@koushikkothagal That would be #12184 (when using `const` instead of `let`).

**Comment by RyanCavanaugh** [comment]
The core problem is more easily explained in the expanded form
```ts
if (value.type !== 'b') {
  // ~~ here ~~
  if (value.type !== 'c') { 
```
At this point, there's no type we can narrow `value` to - it's not `A` yet because there's still the `c` case. So when the subsequent `c` narrowing happens, we're still just narrowing `A | BC`, which again does nothing. We'd need to give it the interim type `(A | BC) & Not<{value: "b"}>`, but we don't have any way to represent this without negated types.

**Comment by imdavidmin** [comment]
If you add value.type in the if condition
```
if (value.type !== 'b' && value.type !== 'c')
    // type narrowing doesn't work here, value has type "A | BC" instead of "A"
    value.type
    a = value
```
Seems that in IDE Typescript is able to figure out the only `value.type` value here is `a`, if you mouse hover over `value.type`. I get @RyanCavanaugh's point, but surely Typescript should be able to infer the type here? Is there any relevant feature suggestion put in to resolve this issue?

**Comment by danny-does-stuff** [comment]
I made [a playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAggQgYQCJwE4HsDWEB2UC8UAsAFBRQA+UA3lAM7ACGwArnQFxQDkMXl3cLgG4oEAB7BUjTg1QBLHAHMoAX1LkqtBszacuCPlS5I+akqVCRYiJAHV0qTAuX51-LU1Yduvfl0Ei4pLS9JLOqm6aoTre+qaRNNFeeiYR5iQAZiw4AMbAcuh4wBAMAJLAAPIswAAUjABGOQAmnPDIaFi4AJSJAPS9UABKEGAANow50AAGbSgY2DhTUADucsAAFlAzNvaOzkuMOE30ENAb0GAY9aMQALZQt4yKcjmMo6MgUKgl6KMAbhAAIRuOQZKB1RpNAB02i8BHwhDilCoDWaMM8bHhiJMPWobnI31YqBwbjM5BuwHoel8RkEBCgqOhsMx-SgABUAMpQTA4dDLOhQDbMLbMuhLOQCnCMVAYZYQY7AdA+QwCPhQ9VuQksYkMyFQoJSKCs9VQqD1apQNZQJroEo4LiUnl8wXrYVTA2McUCxh-RhycbXCCkFRAA) showing what is IMO an even more simple case. I also made a [Flow try](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SRWxgABABBABCAGEACLcygQHZQdkAXnZAB0xeyAD7s4Ds+yZfLIdkAck5Gvlmu5GoA3OyFFIMOr7KYoAh2fSZezdUqVRI1ZreTqFRr+TrbVAZWzsFy+fyAOoQShbCrW8V2h3KyzOkjqrXuvWG43yU3mqSRm0xhWO+MujVu3Oy-Nx1WJzVe0symAPZRwaDshb2ACSEgA8qkABRYMBsdU8gVCkWCACUivZAHpp+zuRAJLV2QADYeC4Wilfs4FsVfr0PhyPbtCL5cAdzDWwAhDG4DB2X20AOrE78hLxZLi+6Ff22K-CxID8vy9SdgBje0WGdShfVlH17TaCRlSTbVdQ1fUJR3Z9-zfIDZ3ZAAVABldktigCBzyApdMlXXDt1pdkoCoYVz1KFsIE1VCPQwqxeJjKChBgrCXxNGgZznXirHZNBUnZOAkLYCB2igDUkLIiiW1qGiV1EjB6KAjAmjgXBWmwGV6VyEAGhMEgmygJIGgABisAAmABmAA2KxHJAekgA) showing the exact same behavior, but with no errors


The playground: https://www.typescriptlang.org/play/?#code/C4TwDgpgBAggQgYQCJwE4HsDWEB2UC8UAsAFBRQA+UA3lAM7ACGwArnQFxQDkMXl3cLgG4oEAB7BUjTg1QBLHAHMoAX1LkqtBszacuCPlS5I+akqVCRYiJAHV0qTAuX51-LU1Yduvfl0Ei4pLS9JLOqm6aoTre+qaRNNFeeiYR5iQAZiw4AMbAcuh4wBAMAJLAAPIswAAUjABGOQAmnPDIaFi4AJSJAPS9UABKEGAANow50AAGbSgY2DhTUADucsAAFlAzNvaOzkuMOE30ENAb0GAY9aMQALZQt4yKcjmMo6MgUKgl6KMAbhAAIRuOQZKB1RpNAB02i8BHwhDilCoDWaMM8bHhiJMPWobnI31YqBwbjM5BuwHoel8RkEBCgqOhsMx-SgABUAMpQTA4dDLOhQDbMLbMuhLOQCnCMVAYZYQY7AdA+QwCPhQ9VuQksYkMyFQoJSKCs9VQqD1apQNZQJroEo4LiUnl8wXrYVTA2McUCxh-RhycbXCCkFRAA
