### ISSUE TITLE
[Question] How to test a typescript plugin without vscode?

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#43037]
# Suggestion

## 🔍 Search Terms
plugin, tests, vscode

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Provide a guide or handbook or WIKI (May some API?) to allow us test the plugin but without setup vscode environment.

And we may update the WIKI/handbook?

**Comment by RyanCavanaugh** [comment]
There are testcases in our own repo that mock up plugins and test them; you can see the general approach there.
