### ISSUE TITLE
Readonly fields and getter-only class members are not compatible when merging declarations

### ISSUE THREAD

**Issue by y2bd** [microsoft/TypeScript#43036]
# Bug Report

### 🔎 Search Terms

readonly, getter, get, interface, class, module, interface merging

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about interface merging

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=45&pc=1#code/PTAEDEEsCcGcBdTwKYIFygO7NAYwIYB2oArrDvqAObLwrRID2os+8ksAZgJ6iXTJ8AE0aEANr06RkYoaEiF6nfLmQBYAFAhQAJVQkx8DAHkA0poVKVOACqp4ARgCCoAN6bQoAcNETQADwxCEgBbACNkaABuTQBfTU1cMXxYWFA7BAcAIXkQgAcxZBDkRTSMxxd3DU8aRH8ACgBKNy9aEmhiAGZOqNB4jX6ErTAAZWRcUTkUdGpaegBaX15i8Mi0-AEkbjzkORTWn3FJaVlYTW09WAMjUDNE5NT0+wAmSo9ZuqaWgXh2rp6+nEhkkUmUXjlIPlCsVSk8EK83O9vCIjgEgqEIgwALygboxAZDeDbWwvADCoBxrlAAG0AAryYgAa2Q3EYnDh8FeAF0MOVXnSuX1etoqcilmjQMFVgxBhpzmAbAALGBTewYIgMqyqPiEPZ4B5pTCQeCKpCKnCsYqS-BW4rQGjydkmlmgFEAckQE0InDEkFw8Hlun0hhM5g0lkiym15U6iOqBxRfkCkoxkXxspBjxjLW0lpwhBtyAANKA7TQ5BHoFH1PGxajk1LMRTcT0gXL29pwIx2iakGq+AnxVIZHtdQPagtxSsm7BFd3ZKAIkhvCg9mlkABHEiQABu+EKih1U3NAk4jE2hEYntEPr9AeGQauIYgTgAkgAZCyKSPWDkAFjjTw6yTdFpXTYEDX-HMwDza1ihLMtdk1H9VHeWoAi+UU2g6FshVAbQAFEdB0V0SAKP02BwSAhBKdhhwYN1-DdNsgA)

### 💻 Code

```ts
interface Test4 {
  readonly x: number;
}

class Test4 { // same name, merged interface
  get x() { return 33 }; // ERR duplicate identifier 'x'
}
```

### 🙁 Actual behavior

Error on both the getter and the readonly field, `Duplicate identifier 'x'`.

### 🙂 Expected behavior

I expected the two declarations to [successfully merge](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), thinking that `readonly x: number` and `get x(): number` with no setter function would be compatible as essentially the same type. The Sandbox link has other tests to attempt to demonstrate that TS considers the types compatible in other cases.

**Comment by MartinJohns** [comment]
> thinking that readonly x: number and get x(): number with no setter function would be compatible as essentially the same type.

They're not the same. The one represents a property, the other a better. Note that readonly properties are only readonly **via that interface**. Interfaces with readonly properties are implicitly compatible with mutable properties. Your getter wouldn't work with that.

**Comment by RyanCavanaugh** [comment]
I don't have much to add.

**Comment by rsimoes** [comment]
@MartinJohns How is your answer to be reconciled with https://github.com/microsoft/TypeScript/issues/3745#issuecomment-118924225, specifically @RyanCavanaugh's statement, "Whether a property is implemented as a field or a getter/setter pair is an implementation detail, not part of the type."

Additionally:
![Screenshot from 2021-03-04 12-42-48](https://user-images.githubusercontent.com/161220/110013625-76f52900-7ce7-11eb-8264-dab2036aed9b.png)

Interfaces, with or without declaring a property `readonly`, seem to have no way to reference getters in certain crucial contexts, as the following interface merge fails with the same error:

```ts
interface Foo {
    x: number;
}
class Foo {
    get x(): number {
        return 0;
    }
}
```

**Comment by RyanCavanaugh** [comment]
The comment from 2015 is no longer accurate due to TC39 deciding on [[define]] semantics for class fields

**Comment by rsimoes** [comment]
Oh, okay. How recent is TC39? https://github.com/microsoft/TypeScript/issues/40415#issuecomment-689850483
