### ISSUE TITLE
Auto imports not working properly with RxJS 7 beta

### ISSUE THREAD

**Issue by benlesh** [microsoft/TypeScript#43034]
- VS Code Version: any
- OS Version: any

Steps to Reproduce:

1. Add `rxjs@7.0.0-beta.12` to a project
2. type `concatMap` and check the possible auto-import locations
3. It should show `rxjs/operators` as the correct import location. Instead it shows `rxjs/dist/types/operators`.

Does this issue occur when all extensions are disabled?: Yes

This comes from an issue reported on the RxJS repository here: https://github.com/ReactiveX/rxjs/issues/6067

Apparently, [neovim users](https://github.com/ReactiveX/rxjs/issues/6067#issuecomment-788300908) don't experience this issue, so it leads me to believe it's not the configuration of the package.

**Comment by mjbvz** [comment]
Having trouble getting any auto imports for `map` to show up:

```ts
import { interval } from "rxjs";

interval(100).pipe(
    map()
)
```

There are no auto imports:

![Screen Shot 2021-03-01 at 4 32 38 PM](https://user-images.githubusercontent.com/12821956/109578283-c0593480-7aab-11eb-9944-9aa703867626.png)


Any extra steps required while setting up the project?

**Comment by voliva** [comment]
Yes, first you need to import something from `rxjs/operators` in another file of the same project. This usually hints that `rxjs/operators` also has exports.

The issue in the other files (where it hasn't been manually imported), then VSCode suggests `rxjs/dist/types/operators` instead.

**Comment by Toliak** [comment]
Reproduced for me with TS 4.2.3.

Yes, There is no suggestions to import `concatMap` (another bug, I think this is it #39778), until there is no `.ts` files with `rxjs/operators` import.

After adding mentioned `.ts` file, for example:
```typescript
import {} from 'rxjs/operators'
```

The bug appears:
![image](https://user-images.githubusercontent.com/25643405/110235604-17df2080-7f42-11eb-8cec-21a0f222b257.png)

**OS** Version: `Linux manjaro 5.4.97-1-MANJARO`

**Code** Version:
```
1.53.1
5d424b828ada08e1eb9f95d6cb41120234ef57c7
x64
```

All extensions are disabled.

**Comment by voliva** [comment]
I've been digging a bit around TSServer and am I correct the fix might be in [moduleSpecifiers.ts#tryGetModuleNameAsNodeModule](https://github.com/microsoft/TypeScript/blob/c497b487a78c049a11ba99b97dccf6126b2d492a/src/compiler/moduleSpecifiers.ts#L471)?

As far as I can see that function receives a declaration file (e.g. `{absolutePath}/node_modules/rxjs/dist/types/index.d.ts` or `{absolutePath}/node_modules/rxjs/dist/types/operators/index.d.ts`) and tries to resolve it to a node module name by looking at package.json (correctly identifying `rxjs/dist/types/index.d.ts` as `rxjs` but failing to identifiy `rxjs/dist/types/operators/index.d.ts`)

Would it be possible to update this file to also consider subfolders?

**Comment by RyanCavanaugh** [comment]
> Would it be possible to update this file to also consider subfolders?

This behavior is intentional. See #42247

**Comment by andrewbranch** [comment]
This is caused by the highly unusual package organization present in RxJS 7. `node_modules/rxjs/operators` is empty except for a package.json (not the root package.json) whose entrypoints point back outside of that folder (to `dist/types/operators/index.d.ts` for `types`). While that works fine for module resolution, it’s hard to imagine how we should be able to come up with that from scratch. When we generate a module specifier for a module file inside node_modules, we walk up the directory tree from that file looking at package.json files we see along the way, and see if their `types`/`main` fields point to that file. If so, we can use a short path to the directory of that package.json. But when we start at `node_modules/rxjs/dist/types/operators/index.d.ts`, we of course never see `node_modules/rxjs/operators/package.json` in that traversal. From the perspective of the module specifier resolver, we have absolutely no indication that some _other_ directory would contain a match for that file. I’m not sure there’s anything TypeScript can reasonably do here.

**Comment by andrewbranch** [comment]
@benlesh let me know if you can’t work out a way to get a good UX given this information and we can brainstorm solutions. Don’t want the closing to come off as dismissive; it just doesn’t seem like this is a bug on our end right now.

**Comment by voliva** [comment]
> But when we start at `node_modules/rxjs/dist/types/operators/index.d.ts`, we of course never see `node_modules/rxjs/operators/package.json` in that traversal.

I wonder if it can be inferred in some way... The root's RxJS@7 package.json has

```
  "types": "./dist/types/index.d.ts",
```

When we use `Observable` and try to get import suggestions, Observable is exported from within `./dist/types/index.d.ts` and we correctly receive to import from `'rxjs'`

Now, if we use `map` and try to get import suggestions... why is TS Server looking at `dist/types/operators/index.d.ts` at the first place? Isn't there a way where we can use this information together with `./dist/types/index.d.ts` to see that the relative path to `dist/types/operators/index.d.ts` is `./operators`?

In a way, this map feels like it should be simple:

```
// Given package.json -> types = ./dist/types/index.d.ts

./dist/types/index.d.ts => 'rxjs'
./dist/types/operators/index.d.ts => 'rxjs/operators'
```

Although I understand that it's not as straightforward.

Otherwise is there any suggestion on how to change the structure to support these kind of imports?

**Comment by andrewbranch** [comment]
> In a way, this map feels like it should be simple

There’s no guarantee it had to work out that way. The relative paths match up because it made sense to a human to do it that way, but I could fork RxJS and make a version that breaks that expectation.

> Otherwise is there any suggestion on how to change the structure to support these kind of imports?

There are lots of solutions, because you really have to be doing non-standard stuff to break this in the first place. In general, shipping types in a different subfolder (e.g. `dist/types`) from the rest of the JS is a recipe for pain. By far the happiest path is just shipping the JS and .d.ts that `tsc` gives you alongside each other. I’m sure there are lots of compelling Technical Reasons why RxJS is doing something different, but the farther you get from that happy path, the more you’re likely to subtly break editor features or have to pile on cascading workarounds to avoid breaking them.

**Comment by benlesh** [comment]
@andrewbranch rxjs now has the `exports` [set in our package.json](https://github.com/ReactiveX/rxjs/blob/5f74c3d9d20bfb8df7853f33b214974a7b91db9c/package.json#L10). Will that be helpful in resolving proper export locations?

**Comment by benlesh** [comment]
@andrewbranch if the onus is on us to make sure that TypeScript/VSCode can find what it needs, that's fine. I just need to know what to do. How do we resolve this on our end? From our perspective, we have to support 3-4 module types, typescript files for source maps, typescript files for types, etc. It's all pretty nuts anyhow. It's not like there's a solid roadmap laid out for how to develop a library that meets everyone's needs.

**Comment by benlesh** [comment]
FWIW: I agree that the rxjs package is weird. It's ALL weird. I hate module resolution and I'll hate it until CJS dies or ESM gives up.

**Comment by benlesh** [comment]
I've zipped up one attempt I had at trying to get a package I thought VS Code might understand, but no luck so far. To be clear: This is just me hacking around on the matter based off of my understanding of what you were saying the problem was above. If anything, it seems worse now, as I can't get any suggested imports for `rxjs/operators` at all.

[rxjs.zip](https://github.com/microsoft/TypeScript/files/6319882/rxjs.zip)

**Comment by benlesh** [comment]
What if we exported the types alongside the esm, (literally next to them in the same directories), but kept everything where it is. Does _that_ solve the issue?

**Comment by andrewbranch** [comment]
> rxjs now has the `exports` set in our package.json. Will that be helpful in resolving proper export locations?

In the future, [yes](https://github.com/microsoft/TypeScript/issues/33079), but right now, unfortunately not.

> What if we exported the types alongside the esm, (literally next to them in the same directories), but kept everything where it is. Does that solve the issue?

It at least solves _part_ of the issue, and getting from there to a good UX should be fairly simple. The main issue here is that a module `.d.ts` file at some path implies that you can import JS at that same path (with a swapped/dropped extension). So removing the `types` directory, which will never be a valid place to import JS, fixes that problem. After that, you may or may not decide that you want to eagerly reference `rxjs/operators` from the “root” `index.d.ts` in order to make those auto-imports available right away. (The tradeoff is that will unnecessarily increase the size of the program for users who have referenced `rxjs` but not `rxjs/operators`. I’m not a RxJS user but my impression is that pretty much everyone ends up referenceing `rxjs/operators` eventually?)

**Comment by andrewbranch** [comment]
Well, looking more at your package structure, I might need to qualify more. TypeScript currently doesn’t have _any_ way of distinguishing between separate entry points for CJS and ESM. So if you put all your typings alongside the ESM, the paths that we’re going to recognize are going to be `rxjs/dist/esm/**/*`, which I’m guessing is still not what you want. Assuming your ESM and CJS have compatible types (beware `export default`), you actually want to put your types in a place that could mimic the structure of your export map. I guess this is what you were doing with the `dist/types` directory. So maybe a workaround that I didn’t think of before is to leverage the [`typesVersions` package.json field](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions)... that actually _will_ make the compiler believe that a subdirectory like `dist/types` maps to the package root. That’s probably your best bet, on second thought.

**Comment by benlesh** [comment]
> So maybe a workaround that I didn’t think of before is to leverage the typesVersions package.json field...

@andrewbranch so basically something like this?

```json
  "typesVersions": {
    ">=4.1": { "*": ["dist/types/*"] }
  }
```

**Comment by andrewbranch** [comment]
Yes, replacing `4.1` with, I don’t know, 1.0, or the lowest version of TS you can support at all, since you’ll only have one version of the typings.

**Comment by benlesh** [comment]
@andrewbranch This change is in `rxjs@7.0.0-rc.1` and I'm seeing cases where apps won't compile because the `rxjs` module cannot be found.

This is the tsconfig:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "moduleResolution": "node",
    "module": "esnext",
    "noEmit": true,
    "target": "esnext",
    "jsx": "react",
    "allowJs": true,
    "typeRoots": [
      "./types",
      "./node_modules/@types"
    ],
    "types": [
      "jest",
      "node"
    ],
    "skipLibCheck": true,
    "lib": [
      "es2019",
      "dom"
    ]
  },
  "exclude": [
    "./docs",
    "./env/"
  ]
}
```

**Comment by benlesh** [comment]
Here's a minimal reproduction. I'm not at all sure what to do about it.
[test.zip](https://github.com/microsoft/TypeScript/files/6345142/test.zip)

**Comment by andrewbranch** [comment]
Your `types` field should be `index.d.ts`, not `dist/types/index.d.ts`. It gets resolved relative to `dist/types/*` from `typesVersions`, so it was trying to find a file at `dist/types/dist/types/index.d.ts`. (You can see exactly what’s happening via `tsc --traceResolution`.)

**Comment by benlesh** [comment]
@andrewbranch that seems to work for `from "rxjs"` but not for `from "rxjs/operators"`. Meanwhile, I'm trying to organize something to where we can just export everything from "rxjs". But man does this suck a bit. Alternatively, I guess we have to change our entire build to... something? I hate module systems.

**Comment by benlesh** [comment]
Okay, I suppose what's the _ideal_ setup?  CJS next to types? ESM next to types? Assuming that we have to put all of the other stuff in other directories, and we don't want multiple copies of the types.

**Comment by andrewbranch** [comment]
> that seems to work for `from "rxjs"` but not for `from "rxjs/operators"`

Are you talking about module resolution or auto imports? I tested importing from `"rxjs/operators"` before my last comment and it worked as expected. But I didn’t test auto imports. If module resolution works but auto imports do not, that’s a bug.

<img width="996" alt="image" src="https://user-images.githubusercontent.com/3277153/115585662-a86a8980-a280-11eb-94f3-725dd1c078cf.png">

**Comment by benlesh** [comment]
> Are you talking about module resolution or auto imports

Both, honestly. I couldn't get either working properly.

**Comment by benlesh** [comment]
> If module resolution works but auto imports do not, that’s a bug.

That's the case even before the `typesVersions` bit. Module resolution has always worked with our package. It's the auto-imports that fail and pull in from the wrong spot.

**Comment by andrewbranch** [comment]
> It's the auto-imports that fail and pull in from the wrong spot.

They were doing exactly what they were expected to do given the structure of the package at the time. Without `typesVersions` to set a different typings root, the presence of a module declaration file at `dist/types/*.d.ts` implies the presence of a module implementation file at `dist/types/*.js`.

> I couldn't get either working properly.

The screenshot I posted shows the changes I made to your package.json from 7.0.0-rc.1 alongside module resolution for `"rxjs/operators"` working correctly, with the exact tsconfig you gave me, using typescript@4.3.0-dev.20210419. Not sure what else to tell you without more info about what you tried.

**Comment by benlesh** [comment]
So I installed `rxjs@7.0.0-rc.2` (which doesn't have the typesVersions), then altered only what you see here (following your screenshot):

![image](https://user-images.githubusercontent.com/1540597/115804571-dd71fb80-a3a8-11eb-8eb4-4e8d03ebb698.png)

After that, when I try to use `rxjs`, I get this:

![image](https://user-images.githubusercontent.com/1540597/115804642-009cab00-a3a9-11eb-9b70-bc5def3482a6.png)

![image](https://user-images.githubusercontent.com/1540597/115804661-127e4e00-a3a9-11eb-8e17-69a0f717ce45.png)

![image](https://user-images.githubusercontent.com/1540597/115804688-1f02a680-a3a9-11eb-8294-1e686005ee92.png)

I'm sure I'm just misunderstanding what needs done. Sorry, @andrewbranch I'm not trying to be frustrating. haha.

**Comment by andrewbranch** [comment]
See [this comment](https://github.com/microsoft/TypeScript/issues/43034#issuecomment-823423227) above:

> Your `types` field should be `index.d.ts`, not `dist/types/index.d.ts`. It gets resolved relative to `dist/types/*` from `typesVersions`, so it was trying to find a file at `dist/types/dist/types/index.d.ts`. (You can see exactly what’s happening via `tsc --traceResolution`.)

<img width="320" alt="image" src="https://user-images.githubusercontent.com/3277153/115896916-c36c0380-a410-11eb-9e92-1b153cb6b2ec.png">

**Comment by benlesh** [comment]
So sorry, I missed that. After making that change, module resolution works again, however, the auto-import still isn't working. Which unfortunately puts us right to where we were before:

![image](https://user-images.githubusercontent.com/1540597/115901097-60856700-a426-11eb-958f-1cebd3b23620.png)

**Comment by andrewbranch** [comment]
It may feel that way, but we are making progress! What you’re seeing now is also expected and can be fixed on your end. @voliva [had it right](https://github.com/microsoft/TypeScript/issues/43034#issuecomment-788668552):

> Yes, first you need to import something from `rxjs/operators` in another file of the same project. This usually hints that `rxjs/operators` also has exports.

Which is the same thing that [I was referencing here](https://github.com/microsoft/TypeScript/issues/43034#issuecomment-820613421):

> After that, you may or may not decide that you want to eagerly reference `rxjs/operators` from the “root” `index.d.ts` in order to make those auto-imports available right away. (The tradeoff is that will unnecessarily increase the size of the program for users who have referenced `rxjs` but not `rxjs/operators`. I’m not a RxJS user but my impression is that pretty much everyone ends up referenceing `rxjs/operators` eventually?)

The problem you’re seeing right now is that `dist/types/index.d.ts`, with all its imports, never references `dist/types/operators/index.d.ts`—it only references things in the `internal` directory—so TypeScript literally has no idea that file exists. You can simply add `import './operators'` or `/// <reference path="operators/index.d.ts" />` to `dist/types/index.d.ts` to make the compiler aware of that file right away:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/3277153/115904005-206bb780-a419-11eb-965f-7738a081a4fb.png">

**Comment by benlesh** [comment]
Can you think of a way I can test this in an automated way?

**Comment by andrewbranch** [comment]
Literally testing auto-imports functionality would be hard and out of scope, in my opinion. It should be trivial to test module resolution on a tiny TypeScript program with `tsc`, though. And you could test the set of files visible to auto-imports by running `tsc --listFilesOnly` on an input file with content `import 'rxjs'`. (You could do the same with the compiler’s JS API, but shelling out and splitting STDOUT by line seems easier.)

**Comment by benlesh** [comment]
Thanks so much for your help, @andrewbranch! The solution did work to get things auto-importing in VS Code properly, however, ultimately we couldn't use this solution because of how it effected tree-shaking with bundlers like Rollup. You can read the fallout here: https://github.com/ReactiveX/rxjs/pull/6276

We're going to have to figure out another solution, which is likely going to involve just getting rid of deep imports, as they've been nothing but a pain.

**Comment by andrewbranch** [comment]
@benlesh you can use

```ts
/// <reference path="./operators/index.ts" />
```

instead of `import "./operators"`.

**Comment by kireet3213** [comment]
Disable Path Intellisense. That worked for me.
