### ISSUE TITLE
Overload function report 'but implementation signatures of overloads are not externally visible.'

### ISSUE THREAD

**Issue by chengB12** [microsoft/TypeScript#43042]
# Bug Report

### 🕗 Version & Regression Information
typescript 4.2.0 and 4.3.0-dev20210228

- I was unable to test this on prior versions,  and I reviewed the FAQ

### ⏯ Playground Link
https://www.typescriptlang.org/dev/bug-workbench/?https://www.typescriptlang.org/dev/bug-workbench/?#code/GYVwdgxgLglg9mABMOcAUMwAcRQFyIDkAjIQJQHEDcAUKJLAsqhtrgYQEzkGe33R4SFOkw58iAM5QATpgDmFRGBABbAEYBTGYgDeNRIcQzNUEDKQA5NVpmtxZGgF86LEuVfouHkWkIBmDyA

### 💻 Code

```ts
function foo(input: '1'): 1;
function foo(input: '2'): 2;
function foo(input: string): number {
    return Number(input)
}

foo('1')
foo('2')
foo('3')  <== not acceptable
```

### 🙁 Actual behavior
shows error:
```
No overload matches this call.
  Overload 1 of 2, '(input: "1"): 1', gave the following error.
    Argument of type '"3"' is not assignable to parameter of type '"1"'.
  Overload 2 of 2, '(input: "2"): 2', gave the following error.
    Argument of type '"3"' is not assignable to parameter of type '"2"'.(2769)
input.tsx(3, 10): The call would have succeeded against this implementation, but implementation signatures of overloads are not externally visible.
About
Docs
Asserts1
Export
Debug
Twoslash Overview
The bug workbench uses Twoslash to help you create accurate bug reports. Twoslash is a markup format for TypeScript files which lets you highlight code, handle-multiple files and show the files the TypeScript compiler creates.

The bug workbench lets make reproductions of bugs which are trivial to verify against many different versions of TypeScript over 
```

### 🙂 Expected behavior

foo('3') should not throw error, and return type inferred as number

**Comment by MartinJohns** [comment]
Working as intended.

https://www.typescriptlang.org/docs/handbook/functions.html#overloads

> Note that the `function pickCard(x): any` piece is not part of the overload list, so it only has two overloads: one that takes an object and one that takes a number. Calling pickCard with any other parameter types would cause an error.

The `function foo(input: string): number` part of your implementation is not part of the signature overload list. If you want this you have to add another overload signature.

**Comment by chengB12** [comment]
Thanks, see I just need to repeat function foo(input: string): number; twice
