### ISSUE TITLE
setting property in callback causes type hint error 

### ISSUE THREAD

**Issue by kwliou** [microsoft/TypeScript#43046]
- VS Code Version: 1.53.2
- OS Version: macOS Catalina (10.15.6)

Steps to Reproduce:

1. Have a normal Javascript project (jsconfig.json) with one .js file containing:
``` js
// @ts-check

class Foo {
  /**
   * @param {(this: this) => void | Promise<void>} fn
   */
  bar(fn) {
    fn.call(this);
  }

  baz = false;
}

const foo = new Foo();
foo.bar(function() {
  this.baz = true;
});
```

  

1. Alternatively, have a Javascript project (jsconfig.json) with a types/index.d.ts for Intellisense purposes only
  
  types/index.d.ts:
  ``` ts
  declare global {
    class Foo {
      bar(fn: (this: this) => void | Promise<void>): void;
      [key: string]: any;
    }
  }
  ```
  
  in some .js file:
  ``` js
  // @ts-check
  
  /** @type {Foo} */
  const foo = undefined; // pretend it gets initialized somehow
  
  foo.bar(function() {
    this.newProp = true;
  })
  ```
  I see the vscode error:
<img width="744" alt="Screen Shot 2021-03-01 at 4 15 43 PM" src="https://user-images.githubusercontent.com/385012/109576845-6192bb80-7aa9-11eb-84f6-aa841b6e30aa.png">

Workaround to avoid the error is to have two separate signatures:
``` ts
class Foo {
  bar(fn: (this: this) => void): void;
  bar(fn: (this: this) => Promise<void>): void;

  [key: string]: any;
}
```

If you create a pure .ts file you don't see the hint error:
``` ts
class Foo {
  bar(fn: (this: this) => void | Promise<void>): void {
    fn.call(this);
  }

  [key: string]: any;
}

const foo = new Foo();

foo.bar(function() {
  this.newProp = true;
})
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by RyanCavanaugh** [comment]
In a JS file we auto-detect `this` assignments and turn the function expression into effectively a class constructor, which has a different `this` type. TS doesn't have that behavior. It's not clear to me what you're trying to do here.

**Comment by kwliou** [comment]
@RyanCavanaugh the `bar` is a hook callback function. Specifically ember-qunit has a `NestedHooks.beforeEach(fn: (this: TestContext, assert: Assert) => void | Promise<void>)` which has a hint error if I set something on the TestContext.

**Comment by kwliou** [comment]
Forgot to mention that I added a merged declaration to support any key
```ts
declare module 'ember-test-helpers' {
  interface TestContext {
    [key: string]: any;
}
```

Also If I don't use a union in the signature `void | Promise<void>` then I don't see the hint error, do you know why that would be?
```js
// @ts-check

class Foo {
  /**
   * @param {(this: this) => void} fn
   */
  bar(fn) {
    fn.call(this);
  }

  baz = false;
}

const foo = new Foo();
foo.bar(function() {
  this.baz = true;
});
```

**Comment by kwliou** [comment]
Here's an example that mimics the use case more clearly with the same hint error. But even if it were a class constructor, the hint error still doesn't make sense to me.

```js
// @ts-check

class Bar {
  qux = false;
}

class Foo {
  /**
   * @param {(this: Bar) => void | Promise<void>} fn
   */
  setupBar(fn) {
    this.bar = new Bar();
    fn.call(this.bar);
  }

  bar;
}

const foo = new Foo();
foo.setupBar(function() { // still get the hint error here
  this.qux = true;
});
```
