### ISSUE TITLE
exported/imported/aliased const enum doens't work in class default property initializers

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4304]
```typescript
module h {
	export const enum A { B, C }
}
module g  {
	export type X = h.A; // <-- Here I found it!
	class Y {
		public value = X.A; // <-- ??? Cannot find name 'X' 
		constructor(
		) {}
	}
}
```

can be seen at [playground](http://www.typescriptlang.org/playground#src=module%20h%20%7B%0D%0A%09export%20const%20enum%20A%20%7B%20B%2C%20C%20%7D%0D%0A%7D%0D%0Amodule%20g%20%20%7B%0D%0A%09export%20type%20X%20%3D%20h.A%3B%20%2F%2F%20%3C--%20Here%20I%20found%20it!%0D%0A%09class%20Y%20%7B%0D%0A%09%09public%20value%20%3D%20X.A%3B%20%2F%2F%20%3C--%20%3F%3F%3F%20Cannot%20find%20name%20'X'%20%0D%0A%09%09constructor(%0D%0A%09%09)%20%7B%7D%0D%0A%09%7D%0D%0A%7D)

**Comment by mhegazy** [comment]
The error message is the issue. it means "Cannot find **value** with name 'X'". 

A type alias only aliases the type-side of an entity, leaving behind its value side. Enums, even const enums, represent both a type (collection of values) and a value (the actual object you dot of to get the const value).

you can switch the type alias declaration to use `import` so you get *all* meanings of the entity.

```ts
export import X = h.A; 
```
