### ISSUE TITLE
TS2345 Generic parameter type, contextually inferred as a union by return at call site, will not accept all properties on object literal

### ISSUE THREAD

**Issue by 6XGate** [microsoft/TypeScript#43044]
# Bug Report

### 🔎 Search Terms

- `TS2345`
- `Object literal may only specify known properties`
- several other combination I cannot recall

### 🕗 Version & Regression Information

- This changed between sometime between versions 3.3.3 and 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hwwE4HsCuYDSEQHdmIBMBnAZQgBsIBjYfKAXigG8BYAKCijBQDMBLSgEkCALihFgiPgDsA5gG52nWSnTCxEqXMUcoAW3hSqRAEoBDORDEBtaaj0AjCIgA0UO4+cBdHQF8d7KCQsPAA8qjA5HzOWLj4xGSUNHSMrLrcyPxCouKSMgpKXCgEqDTCAPwaedqFBnnG5pY2Hk6u7vatPuz+7IHg0ACyZiBOcAiqmNh4hKQU1LSIDCHjaJNxM4nzdABkzFBokdGIRJVQPGbkRNA9bEGDw6NhEVExU-GzSQtLY+GHr+sJObJRa7Jj7Z5HIhiSSoa4BW79ZaxaaAz4pKBDEYQMZIVbI96bYEAH0xj2AvxeiHxGyBC3hPFQ0hofGQ0igsng1OIAAoAPpXNGIMRjLkfLaIACUzEKAHoZVAAIqwqQQIhQADWbxm3V6bAZTOALLZEGkRFQiAgAAVeAIIMIADwAFSgEAAHsATcQ9hksnacpp8lBfAA+bkC8ViUJ6PjAJ1uABEPttwnjwYlYmdaU4FuA5rZYIAdEXw8C3EnsmJ4wAmeNBqBmNWOvy6jnAUXcrNFZAlMo5asAZnjLkK5b9lZrw90B0pUKgMIgk84dSMpgsHJsABEzB6C9JkDhuRKALQAVgADBeL24tzu9weJV5uhL4a32yazRbrZlkwQOyPiqUwDqFAA5DoU06QtCiCwou+iGHwDRrlYUDWDeEC7vuh6npeV5QGhGH3o+bC+BKz7sEAA)

### 💻 Code

```ts
type GetGroupKeywordsSelector = {
  profileId: string;
  groupId: string;
  metricsRange: [number, number];
};

type GetOutlierKeywordsSelector = {
  profileId: string;
  productId?: string;
  metricsRange: [number, number];
};

type MaybeGetGroupKeywordsSelector = GetGroupKeywordsSelector & { outliers?: false };
type MaybeGetOutlierKeywordsSelector = GetOutlierKeywordsSelector & { outliers: true };

type GetKeywordsSelector = MaybeGetGroupKeywordsSelector|MaybeGetOutlierKeywordsSelector;

function getKeywords(_selector: GetKeywordsSelector) {
  // Queries keywords
}

function ensureProfileId<T extends { profileId: string }>(selector: Omit<T, "profileId">): T {
  return { ...selector, profileId: "2" } as T;
}

// Compiles fine
getKeywords({
  productId: "23",
  profileId: "2",
  outliers: true,
  metricsRange: [Date.now()-500000, Date.now()]
});

// Failes with TS2345 on the productId property.
getKeywords(ensureProfileId({
  productId: "23",
  outliers: true,
  metricsRange: [Date.now()-500000, Date.now()]
}));
```

### 🙁 Actual behavior

The code raises a TS2345 from the compiler when attempting to use any property of a union that is not common to all types of the union. This only occurs when passing an object literal to a generic function which has inferred its generic type from contextual typing of the return type.

In this case; the language service does indicate that it has properly determined the correct type, but will not accept any uncommon property belong to only one type of the union.

### 🙂 Expected behavior

In less complex contexts; this would work, and seems as though it should work here.

**Comment by craigphicks** [comment]
Does it work with ...
```
function ensureProfileId<T extends { profileId: string }>(selector: T {
  return { ...selector, ...{profileId: "2"} } as T;
}
```
I ask because [`Omit` is known not to distribute](https://github.com/microsoft/TypeScript/issues/31501)

**Comment by craigphicks** [comment]
`T extends {profileId:string}` was also a constraint on the input (as well as the output).  When you Omit that constraint on the input it becomes 'no constraint', e.g., `any`.  Replacing the input constraint with `any`
seems to make the problem go away.
```
function ensureProfileId<T extends { profileId: string }>(selector: any): T {
  return { ...selector, ...{profileId: "2" } as T;
}
```

**Comment by 6XGate** [comment]
@craigphicks, unfortunately the input must be typed to modified generic type to ensure the correct object is being passed. The language service shows it determines the correct type. This may actually be an issue with `Omit` since writing a non-generic form of the `ensureProfileId` function products similar results AND will not itself compile.

**Comment by 6XGate** [comment]
Alright; after determining the issue is indeed with Omit and searching on that. What I found is that Omit and Pick do not distribute over unions and that this is working as intended per #28339
