### ISSUE TITLE
Inferring type of interface which use never as parameter

### ISSUE THREAD

**Issue by alexshelkov** [microsoft/TypeScript#43054]
# Bug Report

### 🔎 Search Terms

I tried to search for rules of infering the types and how it work with never. Didn't found something relevant.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about inferring the types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/JYOwLgpgTgZghgYwgAgIIB4AaAaAmgPmQG8AoZZACjgC5lMBKW3AbhIF8SSIAPABwHsoYZGACevFAHEIYTOgDCQwgF5ki4T0ggAJgGc06UDGh1syOCFH4yyAPx0btEBABu0Vlz6DhYicmlguApKyKrqyJoQOvoYFqJmRiYENva4jsjOblAeADYy5rQYmdBmIACuALYARtAqlPShhACMHr4oACoQusKqAXJt-DDmhAD0I8gAFnD6bRmu0CSznd0ATKH+MkEDQ3Cj47oT-GU52pNwbiLiKOXVJchVZcIA5vzCxVCcecJVheg3NVBSvMoHUKA1lIQiGAJlB+AB3OYIgCiUFhUAoAHIMfQ2K0rshlmAAMzrProbb3PZnGb4-4LJZdMAAFlJm3JV0GlOQY2plz87yAA)

### 💻 Code

```ts
interface A<X,Y> {
  (a: X): Y;
}

export type GetX<Crt> = Crt extends A<infer X, any>
  ? X
  : never;

export type GetY<Crt> = Crt extends A<any, infer Y>
  ? Y
  : never;

let a: A<never, number> = () => 1;

// don't work as expected
type Test = GetX<typeof a> // has type never
type Test2 = GetY<typeof a> // should have type number, but got never

let b: A<number, never> = () => {throw new Error('')};

// work as expected
type Test3 = GetX<typeof b> // has type number
type Test4 = GetY<typeof b> // has type never
```

### 🙁 Actual behavior

`Test2` has `never` type

### 🙂 Expected behavior

`Test2` is `number`

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `typeof A` does not match `GetY`'s tested type:
```ts
declare let t: A<any, unknown>;
// Not accepted
t = a;
```
Critically, `any` is not assignable to `never`. You see differences here because of co/contravariance of the positions of `X` and `Y`.

**Comment by alexshelkov** [comment]
@RyanCavanaugh than you for explanation, but why [this code](https://www.typescriptlang.org/play?ts=4.1.5&ssl=27&ssc=8&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgEIB4AaAaAmgPmQG8AoZZOALmRzOQCNrds6B6VhqCOAawEkw1ABRUaASmQBeQrgDcyYDGQBXEAgD2AW00RwyMAAtgAZ2QAbUCmBhkIdTYDu6qD2MkAviRIQAHgAdnGzAATz8UAHEIMEwMAGEoMEJJZHibX0gQABNTDFAYaBpsChBg-DoAfho6ahAIADdoWS9fAIT9UIio3DiEpJS29N1stHQ4EqK8goIK5Fxq23rGrzMoigAmagxahqgikGVNemg+oncKUzHgppIQsOQAFQhjMABWKWRI6IxbiHUlODWhHYCx2Nw6DyeYAAbO9Pt10D8-usgRx9odoMtVvQNiM0UddiDju9TudilcvD8Ic8AOywqIxBEdJHYlG2A745Bgu6PZ4ADjpYHhiKULOQwO2GJImQgCDMcC45lWghGlyKqh4dgcIHw1xsyQBTSAA) works as expected:

```ts
interface B<X,Y> {
  a: X,
  b: Y,
  // breakIt: (a: X) => Y; // if uncomment this line it not works
}

export type GetXB<Crt> = Crt extends B<infer X, any>
  ? X
  : never;

export type GetYB<Crt> = Crt extends B<any, infer Y>
  ? Y
  : never;

let a2: B<never, number> = {} as any;

type Test5 = GetXB<typeof a2> // never
type Test6 = GetYB<typeof a2> // number

let b2: B<number, never> = {} as any;

type Test7 = GetXB<typeof b2> // number 
type Test8 = GetYB<typeof b2> // never

declare let t: B<any, unknown>;

t = a2;
```

**Comment by RyanCavanaugh** [comment]
Covariance vs contravariance: `never` in an input position is different from `never` in an output position

**Comment by alexshelkov** [comment]
@RyanCavanaugh so it is impossible to infer type of `Y` in the given situation?

**Comment by alexshelkov** [comment]
Thank for help!
