### ISSUE TITLE
Strip undefined out during truthy filter

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#43050]
# Suggestion

## 🔍 Search Terms

filter undefined

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When `Array<T | undefined>` is passed through `.filter(o=>o)`, it should be narrowed down to `T[]`

## 📃 Motivating Example

```js
const foundWidgets = (names
  .map(name => widgets.find(widget => widget.name === name))
  .filter(widget => widget));
```

## 💻 Use Cases

Right now, we either have to:
1. Annotate map's fn's return value, so that it is definitely `Widget` using `as`, or
2. Explicitly specify the whole `foundWidgets` as `Widget[]`

Neither are ideal, because the filtering really happens at `.filter()`, so the other solutions are more semantically incorrect and thus fragile.

On top of this, I really suspect TypeScript could figure this out by itself. Maybe not though, but that's my intuition.

**Comment by MartinJohns** [comment]
#16069

**Comment by robertmassaioli** [comment]
The library I made for the duplicate issue is: https://www.npmjs.com/package/ts-is-present

**Comment by sdegutis** [comment]
Neat @robertmassaioli. Good thinking. Although, the "isFilled" method isn't intuitive. Makes me think the wider programming community should adopt a consistent word for nonnull. Although that one is already used in Java land, and therefore has precedence, I kind of wonder if we could just create "ull", considering "null" came from "ne" (not) "ullus" (any) in Latin. But that ship has probably sailed decades ago. Also it'd just seem like a typo for "null".
