### ISSUE TITLE
Narrowing down mapped types does not work with generics

### ISSUE THREAD

**Issue by mhohmeier** [microsoft/TypeScript#43075]
# Bug Report

### 🔎 Search Terms

Generic
Narrowing
Mapped Type

### 🕗 Version & Regression Information

I started seeing this in v3.4.5.
I also tried out versions 4.2.2 and the nightly build on the typescript Playground.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics and Type Guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210228&ssl=25&ssc=2&pln=22&pc=1#code/KYDwDg9gTgLgBDAnmYcDyA7ANogClCFWAS2AGcB1YmACwGUUBjYgM2MYBVlgAeDgTVwBRADRwOAPjgBeOAG8AUHDgBtANJxiGOAGtgiCC3EBdAFzj1xuKBjAMAEzLjBQuAH44G8xmAA3YFAA3AoAvip6BkYcxsEKSChwuAFkENqyisoYAIYAtsDmZDBQWgDmwcpZJflwGACuOQBGAcEhsYyphXBEKWnySso1udUARABSEDQYwyL9FVXmACwATKEKCiy1GIwwxKlwKXlJUD0AYpvbuxgAFBANAFbmRz1iYFlQueaYOPiEATvkVFoDGAzDYnG4PEKxQwJTET1SEgAlAUiqU+sooMAYLUoNpbncVK93jkYnAAPRkuAAd2gOjIYnxhLeuSsxCchgQ3DgAHIoaVuasFGSAFTCpTC8Q0VBkIZwDZbHapMQNWrwKnUGhwKo+YqMTkJDjisnrc6K7QHYAAcTsAXYZwVlz4Ehu93MHBezJyn2weAIRH+lA1wNB7C4KEhqJhYkkyP2kZK6Lg7QwnRAKOhCdkjKJLMC5Mp9gg5Aw3LVtPMwzDqG5HBUX19vxIAKDTFYoYhfKj4gkxm5micGAg8CyZDIxBK2QaWFQMAg+urnZK3IAdMN+pjsbi4NnPaSKXBC8XS9Ty3BK1ya3WfT9-aRA0DW2CqxGM9Ge322TUh3AR2OJ1kpxnOd4gXeMVzXEI1n3DgpTlU1LiTLIsCwJw3lQJCsBPKAdDREdrHAEFbHsBRk1TUxFxkfYIEOZJUntC5UiubolR5bI8m5RF8ywukSI6eBEHI+NKIteEMHos0mNojAxG5SpgA4rjDzIEsy2w3iU3gAAvQSM2E6irRtXVxMuSTjhY7k2PkxE833GlsPpL8dkYGcaCyYcUOA2DpxYeBXIcedEO0Jo4wzdTOk07SKNkC1rR1O14MY5jpJ5OSOJsgsi2U487J0BQgA)

### 💻 Code

```ts
export type OnlyPropertiesWithSpecificType<TYPE, T> = {
  [K in keyof T]: T[K] extends TYPE ? K : never;
}[keyof T];

function someGenericFunction<T>(obj: T, param: OnlyPropertiesWithSpecificType<string, T>): string {
  const x: string = obj[param]; // doesn't work: "Type 'T[OnlyPropertiesWithSpecificType<string, T>]' is not assignable to type 'string'."
  return obj[param]; // doesn't work: "Type 'T[OnlyPropertiesWithSpecificType<string, T>]' is not assignable to type 'string'."
}
```

### 🙁 Actual behavior
I want to write a function that takes an object and the name of a property as parameters. What I want to achieve is that only property names of properties with a specific type are accepted.

Inside the function, Typescript does not recognize that the property-value for the given key refers to a string type, even though the caller of the function is restricted to use only keys which point to string-props.

Please notice that when calling the function, the values type is correctly inferred to string.

```ts
const aString: string = someGenericFunction({name: "John", age: 42}, "name"); // works
```

Please also notice that, if the function is declared with a concrete type (<Person> instead of <T>) it also works as expected inside the function. 

### 🙂 Expected behavior
Typescript should recognize the props value to be of type string inside the function just like outside the function.

**Comment by nicojs** [comment]
Maybe related, maybe not.

The (maybe widely used) StackOverflow solution to remove unknown keys from a type seems to be broken since TS 4.2.2. It worked in 4.1

https://stackoverflow.com/questions/51465182/how-to-remove-index-signature-using-mapped-types/51956054#51956054

Example:

```ts
export type KnownKeys<T> = {
  [K in keyof T]: string extends K ? never : number extends K ? never : K;
} extends { [_ in keyof T]: infer U }
  ? U
  : never;


export function propertyName<T>
  (prop: keyof Pick<T, KnownKeys<T>>): string {
//                     ^^^^^^^^^^^^ Error since 4.2.2: Type 'KnownKeys<T>' does not satisfy the constraint 'keyof T'.
  return prop.toString();
}

interface Foo {
  [name: string]: string;
  bar: string;
}

propertyName<Foo>('bar'); // works

// @ts-expect-error Expecting an error here, "baz" is not a known key
propertyName<Foo>('baz');
```

[playground link](https://www.typescriptlang.org/play?ts=4.2.2&ssl=1&ssc=1&pln=21&pc=1#code/KYDwDg9gTgLgBDAnmYcDSA7CB3DbiIDOAPACoB8cAvHAN4BQccA2mnAJYZwDWBEAZnFIBdAFxxCMKJwDmcUDGAYAJoXRwA-HAzAAbsChxxGAK4BbAEYH5IRSrVstO-YfFoA3PQC+Nu6rosAPocXLyIAkJiIfzWAKpwXoyacLFJxnoGnvT0oJCwcPwmGADGMOwQXGBQECiwiAByAIZmwGTkABRVNeJhEQAK7MXcZAA06Fi4+ERt5ACU4pLSGHIMTFDAMCZQldVgAHQwEADKUrLts56J9JyKUPyNxagAYhAQdEnMGM3AC6fLUYtZJ4mBZGlBfksZJdsl1akgmi1iC8IB0AOSgqCoi5wAD0OLg2Gg3EI2TxcAAAjBCABaXLAUq0qDVQwAUXA9LKyzgjS4BmZcAAFgZgGMAESggBeoo4aiw8EaPAmoQI9FhBnh3yRrzRkqxniAA)

**Comment by RyanCavanaugh** [comment]
@nicojs separate issue please 🙂

@ahejlsberg we keep getting reports of this form (OP). Any ideas?

**Comment by RyanCavanaugh** [comment]
@ahejlsberg disregard, I misread.

The way to represent this to the typechecker in a way it understands is:
```ts
function someGenericFunction2<K extends string>(obj: Record<K, string> & Record<string, unknown>, param: K): string {
  const x: string = obj[param];
  return obj[param];
}

const obj = {a: 42, b: "foo", c: 1, d: "bar"};
someGenericFunction2(obj, "c");
someGenericFunction2(obj, "d");
someGenericFunction2({a: 42, b: "foo", c: 1, d: "bar"}, "c");
someGenericFunction2({a: 42, b: "foo", c: 1, d: "bar"}, "d");
```
