### ISSUE TITLE
Can not infer deterministic type, when use intersection in generic

### ISSUE THREAD

**Issue by notforu** [microsoft/TypeScript#43074]
# Bug Report

### 🔎 Search Terms
infer generic intersection

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics, types and classes

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.2#code/C4TwDgpgBAygrgIwM7AE4EMDGwA8AxVAewFsAaKAFUID4oBeKAbygG0BpCEKASwDsoAogA9MAGzgATCDgDWnQgDMoBEuTkhFlGgF0AXMqLF2nbVAC+AKAtj0SJFAAi6YOhjBCGAObSnLqBCFgCF4Je0IEACsIbFpGCwBIJAhcDi4AoJD7dU1fdGoACnV9VPIAN3RxCH1c4xBtAEp9UsJuCSZLSwtQSCgAIVsIXPomCygoBAH9XjhiBAhUAG4LTps7PoGcIfTg0KhwqJj-QJ37XLcPdG8cfqShgDJYRBQMbE3ndHIbwffqWISFQiEfKNKDNVojeLxYAAC24SAAdElgPkAOQTJIo8gARnqS3iHSs3WgMEgmG4Cm4mCGDC+9wh6KqUGefE8eKQpPJlP0zN4rOWVlW9hJ0U5mCOGV2XxwwrJFKpPxGYwBQPqEKhsIRSNRDMxUBxePVcMRyVR7JFct1KIATCjcaNzPygA)

### 💻 Code
```ts
type Substract<From, To> = { [Key in Exclude<keyof From, keyof To>]: From[Key] }

class DataStorage<Data extends object> {
  set<Key extends keyof Data>(key: Key, value: Data[Key]): void {}
}

type BaseData = {
  base: number;
}

class Base<Data extends object> extends DataStorage<BaseData & Substract<Data, BaseData>> {
  foo(): void {
    // here is the error
    this.set('base', 1);
  }
}
```

### 🙁 Actual behavior
Type of the second argument in `set` method can not be inferred, get an error `Argument of type 'number' is not assignable to parameter of type 'number & Data["base"]'.`

### 🙂 Expected behavior
All keys, that exist in `BaseData` are excluded from `Data` by using `Substract` type, so we are sure that the type `BaseData & Substract<Data, BaseData>` can not reassign keys of `BaseData`. That's why I would expect, that the type of the second argument should be unequivocally inferred as number

### However
In the child class with passed exact type `SpecificData`, that even reassigns the `base` key with another type, everything works fine:
```ts
type SpecificData = BaseData & {
  base: string;
  specific: string;
}

class Specific extends Base<SpecificData> {
  foo() {
    // no errors
    this.set('base', 1);
    this.set('specific', '2');
  }
}
```

**Comment by RyanCavanaugh** [comment]
We don't have any way to do that kind of higher-order reasoning.
