### ISSUE TITLE
JSDoc rest arguments can no longer be extracted with Parameters<T>

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#43072]
# Bug Report

According to [the docs](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#var-args-parameter-declaration-inferred-from-use-of-arguments), `{...string}` can be used to define a rest parameter having type `string[]`. This works for the implementation, but does not construct a type that can be extracted using standard utility types.

### 🔎 Search Terms

JSDoc variadic arguments, var args, rest arguments

### 🕗 Version & Regression Information

This was discovered while upgrading TypeScript from 4.1.5 to 4.2.2 in TypeDoc. There is a [test case](https://github.com/TypeStrong/typedoc/blob/master/src/test/converter/js/index.js#L48-L55) for variadic parameters which changed in an unexpected way.

Please keep and fill in the line that best applies:
- This changed between versions 4.1.5 and 4.2.2

### ⏯ Playground Link

Bug Workbench links:
- Good - [4.2.0-dev.20201211](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.2.0-dev.20201211#code/PTAEAEDMEsBsFMB2BDAtvAXKZA6AVgM4BQRwAVGUaGRAMbKywBGytA1qAGID23VN4AA7IATmlABvHNIIAXEdEQBzAL7YRS4tQgj4sgK4jEBSYn2om8ESv7AS5AbICeg+JJ7c1ZO-AAeg7hFZUFpuY2DfUABeUAAKAEpogD5QAEZ7MCg4JDRMUCYcWWI-AKDJGyJnV1AABVFc2SsCAB4AFRSY1tA-RsQAExNY6RxRTSxFSCtQACVEqJTkRCdQAH4Z0CxEeAA3KxIqtzqxVBMYo4am5oPuSFBoVFLZWIAiHGBkZ-iAbQByXx+ALpJUhgUCgAB6KyIQA)
- Bad - [4.2.0-dev.20201219](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.2.0-dev.20201219#code/PTAEAEDMEsBsFMB2BDAtvAXKZA6AVgM4BQRwAVGUaGRAMbKywBGytA1qAGID23VN4AA7IATmlABvHNIIAXEdEQBzAL7YRS4tQgj4sgK4jEBSYn2om8ESv7AS5AbICeg+JJ7c1ZO-AAeg7hFZUFpuY2DfUABeUAAKAEpogD5QAEZ7MCg4JDRMUCYcWWI-AKDJGyJnV1AABVFc2SsCAB4AFRSY1tA-RsQAExNY6RxRTSxFSCtQACVEqJTkRCdQAH4Z0CxEeAA3KxIqtzqxVBMYo4am5oPuSFBoVFLZWIAiHGBkZ-iAbQByXx+ALpJUhgUCgAB6KyIQA)

### 💻 Code

```ts repro
// @filename: a.js

/**
 * @callback Foo
 * @param {...string} args
 * @returns {number}
 */

/** @type {Foo} */
export const x = () => 1

// @filename: b.ts
export {}

type Params = Parameters<typeof import("./a")['x']>
//   ^?
```

### 🙁 Actual behavior

TS 4.2 resolves `Params = never`

```ts
type Params = Parameters<typeof import("./a")['x']>
//   ^? - type Params = never
```

### 🙂 Expected behavior

TS 4.1 resolves `Params = string[]`

```ts
type Params = Parameters<typeof import("./a")['x']>
//   ^? - type Params = string[]
```

**Comment by sandersn** [comment]
The problem is with the interaction of `@callback` and `@type`; you can't even call `x` inside `a.js` like you'd expect: `x('a', 'b')`. Here's a smaller repro:

```js
/**
 * @callback Foo
 * @param {...string} args
 * @returns {number}
 */

/** @type {Foo} */
export const x = () => 1
var res = x('a', 'b')
```

Note that changing x's definition to `(...args) => 1` doesn't help.
