### ISSUE TITLE
Regression on assignability of generics

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#43098]
# Bug Report
I can't tell what is breaking but I have a code example

### 🔎 Search Terms

inference

### 🕗 Version & Regression Information

- This changed between versions 4.1 and 4.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.2.2#code/JYWwDg9gTgLgBAbzgeQNYBo4FEpUwJQFMBnAVwBt4BfOAMyghDgHIZiBaKEit5gWABQggPTC4xGFGAA7AOZwAPnFLSAJoVozCquDLgAVAJ5hCAZQDGUsPAAsAOgCMIsStTSIAd2lwPwGAAs4AEM4GGNCOEJcaF1vewAmYLU4aWBZfxhyQ0FzCGkJYNIA6ABJaQAFIMNyCCCdAF44AAoEGiDiOCIySgAeCSk5TAA3CGBVAD4ASkE4Wbg7ILV9f0JpJqaAD0m4evHmjZ36xuZmOAB+FFQm5kJwMOZtgC5sXDssAFly-QBNSemBObzFQeKBBMDIKBNFTqTTSbT-IA

### 💻 Code

```ts
import { Ok, Err, Result } from 'ts-results'

// string | undefined in TypeScript 4.1, which is expected
// unknown with a type error in 4.2 and nightly
const authorInPayload = ({} as Result<string, void>)
    .andThen((x) => (x === '' ? Ok('empty') : Err.EMPTY))
    .unwrapOr(undefined)
```

### 🙁 Actual behavior

types become unknown. 

### 🙂 Expected behavior

Works as 4.1

**Comment by Jack-Works** [comment]
Another example:

```ts
type A = Ok<1> | Err<2>
function x<T, Q>(y: Result<T, Q>) {}
x({} as A)
```

In 4.1 it's `x<1, 2>(...)` in 4.2 it's `x<unknown, 2>`

**Comment by RyanCavanaugh** [comment]
A more minimal example without dependencies would be useful. Thanks!

**Comment by Jack-Works** [comment]
The type I used is defined in a small single file https://github.com/vultix/ts-results/blob/master/src/result.ts

I inlined the dependency https://www.typescriptlang.org/play?ts=4.2.2#code/PTAEGcBcCcEsDsDmoA+oCu8AmBTAZgjlqAqACoCeADjgMoDGcVkoALAHQCMAsAFAgZ4Aa3gB7AO7xQ42JAAWoAIahI1HKBzRoo6CSkcATEuyh4sRHMgAbCn3qj4UJenk6AkvAAKiildGLiAF5QAAoAbwBfJXBQACUccHQrSAAeKDgkABpQADdRWCwAPgBKPlBy0HZFbDI5HHgQkIAPYtBAwtCmtsDggHJe0AB+UAB5IRDenABbZgpe1oAuUABRLXZlgFlPMgBNYtLeCsrMcWhFKhHoEMxcAngiA4RITTxFenUAIUVwHHjE5JSZGyyw6OCaz2wMTczzOACMrDhARpwfUsFCYYp4YiEHhNKAAKodYb40BLe45TQdMJlCrAABUdNAAAMYOgcEzpHUpPJ1NAEkkWLAYmNQHSwHyAg4bKBREIlrDRKIEdUANw08r0xks6BsjniLkqOqgPn-QUxVa6MXGnCS+DSzTQeWK5XwNW8dWgTUe0VxHCQdDQRyG9T2eCQRSEYhMsYcnKKKxs7KwPDIoWQcDscq1bTiGLVDRaHQkFNiSDsb2MgACVEUZymoCm4GQPIbCXAikQ6kgokNOeLph7IrjCZw5cORzFHrBNHokBCjcQS3SCEQxSWZDdHq944qjPi-sDMRbofDkeZMdy8bZY6OPo+OHoinQP0NQtAeEws9gDgbPl7EiTdMMBfN9O3uM4rGlLAhXsAMOyIG8J1ADwoBtLBsioPlcV0btQDkaosARYNmQtDlHxfacrFgehZBsRDdwrcg5BzGJk2I4c2RIPMpCZUjshkeQlFbcB207UBMNEHICiIUBYQoYjeK0JlehiDjRwrYAPROM4qBCNdyE3HdPQZRj9wDINjwcU97ijC81JlXRlAkqTcGIW4n2SejyjpRjQErH51G085Ll8ytcEwh9FGeYhSFePJdFEFMgouaANKnKwfkBAxChCYd1wMfSyFQcgDEMo5t1vPc-XMo8jRPCMbPPIRYyvdQiyc7QXJk9yBS80VfJCWo3zfFsmWSgB9HQOVIHUoAOSrNKM5LLiynK8pKwrirIUq+C3EyjJ9ABheMMuZKZzhoaBppTFsTQFLimqZbJRB5aAZBfPkDwso1FKuy8RxlFMfisPA+sZIaYg-eAvx-R8pFhQKfmIPAixPbQrHfPxxFk74ZJ-Jk-gFFqRwzNKjII2p6iy4FsvnC7NCWXL43XVp2l9U1qZWbL9MJgFtuBYrlmysraX2yrQA2c482ZXnUiBFZCg5XCCf5AF8WBRXZPki6bBXISoZh7ke2Ueqz2jZr-sTRjlSkpBjBIpTLcCsNRHQeg6iwMHGIh99P0gb8pDh2TEZk3D7BmUQX1u1WgMSlRxB7A3-YcUmDsnIzzqoFJCTpqhLsZ9ayFZjp8R5mPs41kWNTFpDJaoaWVY5+WQSVntG4FQFsgAMU1uSlDz3W7eUJOA5UY3QFNxrfuJq209AG29fzc2Z+d7s3Y9r2559kfYfzBHgNDnsaxE-90AsITEnod4RI-DG7uSTlYCI-DsCooepAdHQwcWo5M4tFIe653zqEdayxi6gC7mXJu3dChugiLtfgYtGSHSsg1Wq6hP66DUmUdO04dAsHoFYb45otBuBmFYFIIISDkOmPUICXwfiyxSOSTQGtQDUiMpqUAABBD+MxVArC0KKH+FQoBRWotaW00pNjbB2G0UwOBsYWjIVQCheQCg5RuPgSMxQq6SKwFKeSsoACESxXgZRwG6I4EoDF2nkg6UxKgdSWI9DYwx-1HHLD0QAbVoBQKYCorDsFkJoKKOgAC6ekljQlCd2aAzCcAUmgNkFhyTjAUCpN6Con1zLsKybeBR4IonIQxHEphqSUmJMpHkg6BTbw5MDOw0AticBLFZDgbIaklhaLuEQYxoAIhWLqUcCImR8kDKGeUeB7ojKhnSG7OJTMrBLDATU4ZbEQjGJCPIYajhwzQxwHHZR5D9hrOGdk6qjT7hKNIeQpZujxnTPGTsjMsp5HmJ+JM28Lz2AOnke0r5RwfnDnkcOL5TzOE113H5cKfJHzRT0O+RQ8VAaCFOMFVKc9-I4GduilKZMjg4AsatJZ+VCpGA4cMhpUgwUeghUcZa8TtprWZhtfKZyCnUv+uChBhKmgzjnAuJcMAVz6VSRy75zEJAKJudoK4TIAAkYQFxRAALSCLlUsJV3ZaAiqQNsuQQp2DDmKBEJkDyjL0oqMlYp4rKV1PkH2a5GqdAhCZGQOAh80U6RdY6UA2rRC6oyIgA1RqTVmotSM3lFRM4kvGpnYBpKFFJPAdtfS-8qH2s5Zc7khrwA8pmUcCmXJOZCxyqIKgBdWWpPAUw-mXMSgrK0JQzJtTyhcpeQWj0f9m1lqAQzUIDoVngKFum3t2UJXWJzTKjV-arjAvjPsLtRkdV6pDfpZcdss31Onb9EIAag0rlDRmcNxQmQFohQIH2J0JAkJwj2fej5IKYiIuqqgkdwCwCxMHR8z42o3SNAkAArBPUQMwn7iJ-OGaAnZIB8DwdAAhKcWAWnkcc1R0QVBqCObcjDAAyUILaQhDpWCO3DFCQQWoQywVQNANUtrQ+RlthkKrINQQgdBEA3bX1Uq1HBi1qMTyISfMYKiKFkA6LAGhUw6ExAYb8cu8tUmtqOGI-29B9HuJkbseRzrRPkJSOooo1xsDaJsha1xaF3EmLac4r5bi7EFmgI4j5LijIOelMORxG5o3lF8f4wJwTSkROKTEs4cSkRgghGiEpoSsQpBxHiQkQwCSkmTdU7dQKpXY2dRaV1-R5oVCteUOZrJZyusLq0TLFRHXSty4WK4BW6XpR+CEca61MAiAkPATa1X23ToXVYZdDL4B4suG1jrwgxCSF6+MjtebjXxmGxUacD45zxqbMK4Ns223Wi+q+E9S3muFutaNnSxSip9b27kwby3yixuZXOqtyzyCpoKksMYq1J0XP23p8YCbNDHsW1YJdx2PTFqpvWvtAO-VJqLm0DodaDA00bezDuUOJ1Xa5TDoHJq7u-ioBm2m8b6aw5IzWhHXN9KfYk99-r+3O3HdU4oXE+IzvnAu3T67jTbtg5XYGtdxTN3ICu7V7G-RjvTME6V0YQh5H6Yw98LDNA44K4xgRkIgIWUvfh2zNXWuqP8vwcr9QNOOjBH1xJt0gnaPqDrWw4IIQzeC17SUUABH5P24Vm6IAA

**Comment by Jack-Works** [comment]
@RyanCavanaugh Hi any progress on this issue? Can you reproduce it?

**Comment by RyanCavanaugh** [comment]
@Jack-Works we can't really allocate time to looking at repros this large since they almost inevitably end up being user error. If a defect can't be demonstrated in 15-20 lines (*counting* lines in dependencies) it's almost never a bug.

**Comment by Jack-Works** [comment]
But the same code working on 4.1 but not 4.2! Ok I'll try to eliminate the lines

**Comment by RyanCavanaugh** [comment]
> But the same code working on 4.1 but not 4.2! 

Sure, but sometimes we fix bugs and the result is new errors

**Comment by Jack-Works** [comment]
https://www.typescriptlang.org/play?ts=4.1.5#code/CYUwxgNghgTiAEYD2A7AzgF3jKB3AXPAEohoCuEGAPJjAJYoDmANPAG5J3AB8AsAFAB6QcVIVqtBi3adg8AD7wyKUADMGIHvAbwAKgE8ADiADKYeoawAWAHQBGViXKUqygNYokuFK3efv3Noo8LYATPBQKvAodIwAFhgQ+gLI6FjAUBhQ8AC82Hg2kcC6cSAoABTlAB4AlLmB1bk5eQDkLfAA-NEguPAA8m7lLSAAtpb6LXWEKD3wAKIwMOXKahrANRsCDBggMKpQYAgAQlBoIE7iVLqsc4EA3gLwT9ggUMCoSfBIboQARkhICCvFCPZ7KXA4Qx9GBXULccpsKAQQi6UI1FEKPShUFPIolMqwm5w8ojKCGYwwQgIpEouo5QIXFyooncdGiZzUZnzTFzOECAC+AhAVUMSBgWEgpzQ80WVFu2jGQJGZQw0pOZ0Z1BmbF2N3uOJebw++i+bgAhIR9hAzgbUrQyGAMGLyoYyL8IHQwIb3ihPojkfM6ndBfxnkoUBCydDYfD-Si0fH4A9Q2HnnAMGQYMF-QaQ2G8aUUIT5sSkIYqXHujqYHSGWImaEWWyFjD5cnU2mQBms-AMHE6GhcwKhSKxRLoGhpQMroE6IrRiq1adzvXOaxtbt9SmnnAjb6Td8Lb2YGQQLbUPbHc7Xe7Pd7jewaXog3mwRHIdDygB9St+LwoNldCTA0w3TTNgj7AcbBzbd4FfXEVHxIsuV5eFSXJXYKyfXRa3ZS4ULhNlNWLVDgNg0Cu3A+B0IpcpILQaCkRqId+BDYVRXFXsjAQYjrnmQI8nKaddECRQWzlVl4AAMngdUVw5K49QEIA

A 29 lines repro. Is that OK? @RyanCavanaugh 

```ts
declare const raw: Result<string, void>
// Result<string, void | undefined> in TypeScript 4.1, Result<unknown, unknown> in 4.2 and nightly
const data = raw.andThen((x) => (x === '' ? new Ok('empty') : new Err(undefined)))
interface BaseResult<T, E> {
    readonly ok: boolean
    unwrapOr<T2>(val: T2): T | T2
    andThen<T2, E2>(mapper: (val: T) => Result<T2, E2>): Result<T2, E | E2>
}
export class Err<E> implements BaseResult<never, E> {
    readonly ok!: false
    constructor(public readonly val: E) {}
    unwrapOr<T2>(val: T2): T2 {
        return val
    }
    andThen<T2, E2>(op: (val: never) => Result<T2, E2>): Err<E> {
        return this
    }
}
export class Ok<T> implements BaseResult<T, never> {
    readonly ok!: true
    constructor(public readonly val: T) {}
    unwrapOr(_val: unknown): T {
        return this.val
    }
    andThen<T2, E2>(mapper: (val: T) => Result<T2, E2>): Result<T2, E2> {
        return mapper(this.val)
    }
}
export type Result<T, E> = (Ok<T> | Err<E>) & BaseResult<T, E>
```

**Comment by RyanCavanaugh** [comment]
This doesn't seem like a bug given those definitions. During structural inference we're trying to line up candidates from `Result<T, E>` -> `BaseResult<T, E>` onto `Ok` and `Err`, but in either branch those don't produce candidates.

It seems like this worked due to some aggressive nominal-based inference in 4.1 that doesn't happen anymore in 4.2 due to the type aliases being preserved differently.

I would rewrite the definitions as
```ts
 // Remove BaseResult since it appears naturally in Result<T, E>
export type Result<T, E> = (Ok<T> | Err<E>) //& BaseResult<T, E>
interface BaseResult<T, E> {
    readonly ok: boolean
    // Remove 'unwrapOr' and let it appear via inference in Result<T, E>
    andThen<T2, E2>(mapper: (val: T) => Result<T2, E2>): Result<T2, E | E2>
}

declare class Err<E> implements BaseResult<never, E> {
    readonly ok: false
    readonly val: E;
    unwrapOr<T2>(val: T2): T2;

    // Keep these public signatures    
    andThen<T2, E2>(mapper: (val: never) => Result<T2, E2>): Result<T2, E | E2>
}
declare class Ok<T> implements BaseResult<T, never> {
    readonly ok: true
    readonly val: T;
    unwrapOr(_val: unknown): T;

    // Keep these public signatures    
    andThen<T2, E2>(mapper: (val: T) => Result<T2, E2>): Result<T2, E2>
}

// use undefined, not void!
declare const raw: Result<string, undefined>
declare const f: (x: string) => (Ok<string> | Err<undefined>);
// Ok<string> | Err<undefined>
const data = raw.andThen(f);
```

**Comment by Jack-Works** [comment]
Ok, I'll report this to the ts-results library. Thanks!

**Comment by Jack-Works** [comment]
I have revisited the source code of `ts-results`.

>     // Remove 'unwrapOr' and let it appear via inference in Result<T, E>

I use a `BaseResult` because I want to re-use all JSDoc documents. If remove it, I need to copy-paste the JSDoc case-by-case since TypeScript does not support `@inheritDoc`
