### ISSUE TITLE
Linked parameterized function argument types: cannot push an element to an array

### ISSUE THREAD

**Issue by slaout** [microsoft/TypeScript#43093]
# Bug Report

### 🔎 Search Terms

* linked argument types
* linked generic types
* push array of generic type

### 🕗 Version & Regression Information

I don't know when this bug started occurring.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about push array of generic linked types

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?ts=4.3.0-dev.20210228#code/GYVwdgxgLglg9mABFApgZygZgDwBVEoAeqYAJmomCALYBGKATgNoC6iAPohgzGAOasAfAAooALkS4ANAQm4mABhYBKCQDc4MUogDeAKESIA9EckBlAEyYALAFYJAQQZ8aKMFERxgyAJ4AHFEQAcnklIMQYCjA4DwBDNDQYPjBY2gAbQKg4RD9YhljqFFQGT28of0CgsBQ1RiCAOgNjU1wK4O5ePg5KGnoGcMjKGMR4xOTUjORs8oDg6tr+xsMTSTagjv4BqOHRpJT0zOm1+bql5Hq-EDQAC2EUZQBuPQBfPT1UDExhJgBGGQsWDJMI93ugsN8-ogATIAEQAYRhj2aiHhMLklhs9kQThchXcpV8s3WUB4mwi2ziCT2E0OOTyBSKjAJM0qVDopyAA

### 💻 Code

function test3<T extends number[] | string[]>(t: T, e: T[0]): void {
  // TS2345: Argument of type 'T[0]' is not assignable to parameter of type 'never'.
  // Type 'string | number' is not assignable to type 'never'.
  // Type 'string' is not assignable to type 'never'.
  t.push(e);
}

test3([1, 2], 3);
test3([1, 2], "C"); // "C": TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

### 🙁 Actual behavior

The second error shows TypeScript knows that the number[] parameter can only accept number as a second parameter.

But the first error is the bug, IMHO: if T is number[], then e is forced to be a number, so t.push(anyNumber) should work. Same for string[].

### 🙂 Expected behavior

t.push(e); should always work: their types are compatible.

**Comment by MartinJohns** [comment]
> t.push(e); should always work: their types are compatible.

They are not.

    const myArr: string[] = ['hello world'];
    test3<string[] | number[]>(myArr, 1234);
