### ISSUE TITLE
`.constructor` has the type "Function" instead of having a more specific type

### ISSUE THREAD

**Issue by peey** [microsoft/TypeScript#43095]
# Bug Report

### 🔎 Search Terms

"this.constructor" type static 

### 🕗 Version & Regression Information

typescript 3.8.3

Also in nightly on they playground

Please keep and fill in the line that best applies:
- ~~This is a crash~~
- ~~This changed between versions ______ and _______~~
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Classes, Type System Behavior
- ~~I was unable to test this on prior versions because _______~~

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210228&ssl=1&ssc=1&pln=13&pc=66#code/MYGwhgzhAEDC0G8BQ1oQC5nQS2GgjABQCU0AXGugE7YB2A5oiqtFQKboCuVt0ARH2YBfZgFsipZC2jAA9rQiyQbAHQhZ9Qn1EBPGeCjQAFpGjoj2GADNOtYDnnQARp3TRsbgCay2EWgHI3dB0ABzZgI3CAaz4AGjMLCBU5BWpOe1kqFQh8YgBuYSQkESQANzAqaAB9UEgYAF44AqQUxWU1DS1I9n8YczY0MFEB8zpGAHcLCLNQ8MjgKIg46tqobNy8oA)
### 💻 Code

```ts
class C {
  static s1() : string {
    return ""
  }
  m1() {
    console.log("my class has this function but it doesn't typecheck", this.constructor.s1);
  }

}

var _class = C;

console.log("here's the same thing which typechecks", _class.s1);
```

### 🙁 Actual behavior

The line inside `m1` doesn't typecheck because `this.constructor` has the type `Function`

### 🙂 Expected behavior

Instead it should have the same type as the variable `_class` later.

**Comment by MartinJohns** [comment]
Duplicate of #3841. Used search terms: `constructor T in:title`

**Comment by peey** [comment]
Closing as duplicate
