### ISSUE TITLE
TS Not Narrowing Optional Prop in Condition, or Nested Condition

### ISSUE THREAD

**Issue by tmillr** [microsoft/TypeScript#43091]
# Bug Report

### 🔎 Search Terms
narrow, narrowing, function, condition, conditional, optional, property

### 🕗 Version & Regression Information
4.2.2

Please keep and fill in the line that best applies:
- I was unable to test this on prior versions (except 4.1.5) but I did review the FAQ

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQghgZwJYGMDyAjAVhFwDqSwAFmmMEgPYB2cANgGLVQC8UA3lJeQPwBcUABQIBCYACck1AOYBKVgD4oYyTIA0yygFsIaEhHEAFcdz6CSSEVACu1ANbVKAd2oaAdB7jjpVuNRDyLEoqUtJQUAC+ALAAULEA9PFQAJIAyqkAqgCiUACM8QBMHm6xsaCQXJLSUvQMUgAmADyx4eFoMABSUBAAHsAQ1PUIsIiomDh4hCRkFDS1zIlQTohQcDbUVMxSUFogUCiU9RAayFpgdEgAZkgQ9VDEBtCXlOJQ+t09cGd0ELFKbO0ur1+oNhvBkOhsLgCERSORNvMWq0eBwka10UJil4fAJDF4vhB+uIEI1AQBtABECG0un0RhMYApAF0FLJcSYtJYIM0Yhi+a1yRTuMBmR8QUMoAAlCAAR2sSHEt1JnQUlOFzLR-K1KOlwGs4moABVwNzBeqmVB4gAqK1QRoAWntUCykslaElAEIUVb4gpNVq+QIAG6UJD1f0YhQAbgj6IQIGoKAEglj-Kx3isePEBKJJMF1J0ege9O4zL9vIDgSUZvIouBAwlgnTONW-irrZAqb5OsJ+qNJuVHTVtYt1ttDqdLrdnpRaUyOXyBSgPvLAYxwdD9RjFfR0R3UAEGEolB+fm3CSSc+yUAKhWKF6gADlnEtYVBHFAMBBqtQNjJKlAQrWESFL7DQ9REJs8RErQ4h7CgDwoHYJQxIsGTUBcdjQHAR5Bsc+yIXYoRQM8rwAAZNp4GYCH4ASKB2ZEAWRDC2HgmyMU4Lx2AgGgPhgwEEbgRH-nA0hwFIYhQGR0pygqSoKIxwFIHQygUHQKn1JQEDDI4wA8GUJqVEgP61A0BSDmKDZgqMkITDC0zwnMjDUP8qL7pRbjYpm+I6Lmg6UgWtLFsYpYsmyUAhZyCDcqmNYiha9aglKsryoqTSAqqQojl2yLJXqBrGpA-lZfFlo2najrOq67peik6TXreS4rjl4QbmGmrRpq8aJsmqbNt52a+QYeadAFNJFgYIWMiymrtqmY5PpQUBhhAaxOMQez8cAbwPCRJ50M4xGceI3Hvs4Gi2Jh0BgIqQZUNYwxkeUECMUclyrLh0A+lAsWjSVdZ9FZUAsYmszUKmPb5f2RVxWWqZtVusQROeqFJAAEo8y3DGspznFcNx3IqN2HNYbE0Fw71kVeOSNYxyQAOR4TsAxg7c9yPChiyGsQlhcNQ2F0NSn7fhJr4kABxArH4XDAQYYGDJBNDQQYsEgBoW1QAAImgWSpO+XgmE4YHiIqeB0HsVwPghQnEVcy3bYlEog2TzCCBronicwulLA8zDW0hxEexJ23SSlclNApNhqbInOXksKzSKG-7AEtX4-mLxA7bzvRfOc0Aa0QfPm-cxnEBc0jEMAwy5BTO3QEulgINY2kpPTWgfJAkgDCgoQPn4dzJMtWiiVI0DvJQdJY030AHNYdB3F+OwvDP2h5z0EteEcrwpyRxn6tAlDAcUZ3bSsKjiRXwCkcs4j1Chz3KEg3wxfuhqWUl4JjFCkywjMCLOX8VgUBDTDlKo7YYMlUpKkNJlc0UBIZ9kKtyEB-1RzlQnFVactVqY3kKMuX0B5VKqGkCjRYqQn7KS8G8JaN0IBBjeIZHClAmYawsMMY6p1HBOAMhUXGPxzKajfuAkYEJxjQimHCMGiIYiuRQXA4RzswbwLyoggcciRxKFEBIUIUYgA)

### 💻 Code
```ts
type BasicObjectWithOptionalFn = { opt?: (s: string) => string, someOtherProp:(this: unknown, ...args: any) => string  }

// ISSUE 1/2...

type originalFind<
    OBJ extends BasicObjectWithOptionalFn // was a union in my code, simplified here for the example
> = OBJ extends BasicObjectWithOptionalFn
    ? {
          (...args: Parameters<OBJ["someOtherProp"]>): Promise<
              OBJ["opt"] extends Required<OBJ>["opt"]
                  ? ReturnType<OBJ["opt"] /** <-- ERROR!? */>
                  : void
          >;
          sync: (
              ...args: Parameters<OBJ["someOtherProp"]>
          ) => OBJ["opt"] extends (...args: any) => any
              ? ReturnType<OBJ["opt"] /** <-- ERROR!? ISSUE 1/2 */>
              : void;
      }
    : boolean;

// ISSUE 2/2...
// Now with no beginning or "outer" condition/ternary check.
// Unlike above, checking for `(...args: any) => any` or `Function` works, 
// but checking against `Required<>` util still does not?
type originalFind2<OBJ extends BasicObjectWithOptionalFn> = {
    (...args: Parameters<OBJ["someOtherProp"]>): Promise<
        OBJ["opt"] extends Required<OBJ>["opt"]
            ? ReturnType<OBJ["opt"] /** <-- ERROR!? ISSUE 2/2 */>
            : void
    >;
    sync: (
        ...args: Parameters<OBJ["someOtherProp"]>
    ) => 
        /** No idea why but the following works now, unlike previous `type` def above */ 
        OBJ["opt"] extends Function
        ? ReturnType<OBJ["opt"]>
        : void;
};

// Here is a simplified reproduction of `ISSUE 2/2` I've mentioned here.
// This one also begins with or has an outer condition/ternary, but DOES narrow correctly if
// checking if it extends Function (but again not when checking against `Required<>` util).
// I was going to begin with this example but it only highlights 1 of the 2 issues I'm experiencing
// and I imagine the other issue could be more complex or harder to figure out... not as straightforward.
type simple<
    T extends BasicObjectWithOptionalFn
> = T["opt"] extends Required<T>["opt"] ? ReturnType<T["opt"] /** <-- ERROR!? ISSUE 2/2 */> : string;

// Similar to previous type above but this works now
type simple2<
    T extends BasicObjectWithOptionalFn
> = T["opt"] extends Function ? ReturnType<T["opt"]> : string;
```

### 🙁 Actual behavior

ISSUE 2/2 (as seen in code) in 

```ts
type simple<
    T extends BasicObjectWithOptionalFn
> = T["opt"] extends Required<T>["opt"] ? ReturnType<T["opt"] /** <-- ERROR!? ISSUE 2/2 */> : string;
```

ReturnType<T["opt"]> fails because TS doesn't know that "opt" prop is defined.

ISSUE 1/2 (as seen in code)
Same error for the same reason, but different context. Is the narrowing of the outer conditional overriding the inner one? 
Please see the code for details.

### 🙂 Expected behavior

ISSUE 2/2
`ReturnType<T["opt"]>` should not fail as all props have been checked to be defined/present in the block where this is running.

ISSUE 1/2
I expect it not to error for the same reason. 

I'm not sure if I've labeled the issues correctly. To best understand please see the playground in order to get an overview and investigate the actual code and errors. Thank you for your time!

**Comment by RyanCavanaugh** [comment]
I'm only going to speak to Issue 2/2 as issue 1/2 has not been simplified enough to clearly demonstrate a defect.

This sort of reasoning
```
T["opt"] extends Required<T>["opt"]
```
is beyond the grasp of TS's understanding. We don't have any mechanisms to reason hypothetically about how every possible inhabitant of `T` transforms through `Required<T>`; this check stays "higher-order" can't doesn't imply any constraint on `T["opt"]` in the true branch of the conditional.

I would write this type as
```ts
type simple<T extends BasicObjectWithOptionalFn> = T["opt"] extends Required<BasicObjectWithOptionalFn>["opt"] ? ReturnType<T["opt"]> : string;
```
since it's simpler and we know from the outside that it has the saem behavior.
