### ISSUE TITLE
Typescript doesn't actually transpile readonly

### ISSUE THREAD

**Issue by tbhaxor** [microsoft/TypeScript#43103]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

1. JS make property readonly

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Here is short difference between readonly and const: https://stackoverflow.com/questions/46561155/difference-between-const-and-readonly-in-typescript

In the first example you will see, readonly is ignored completely in the transpilation no matter that target it. In js as we all know, classes are also function and they have properties. 

So even if you will emit strict js, you can change the readonly property from js. 

There has to be special meaning for `readonly`. So here I am adding another example that demonstrates how we can actually set the property readonly

**Explanation of Example**
1. Object.defineProperty will define the property for the class using `this`
2. In configuration, pass the initial value of the property in `value` &rArr; `Object.defineProperty(this, "PROPNAME", { value: "MY VAL" })`
3. The initialization is done, now we have to mark the property readonly. Use `writable: false` along with object define configuration  &rArr; `Object.defineProperty(this, "PROPNAME", { value: "MY VAL", writable: false })`
4. Preventing this configuration from being changed, use `configurable: false` &rArr; `Object.defineProperty(this, "PROPNAME", { value: "MY VAL", writable: false, configurable: false })`

## 📃 Motivating Example

1. [Example: Typescript output](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCAO9oG8BQ0PXgVwEYgEthoAnAUzABMB7AOxAE8sTr4AuaCAFxINoHNU6TMDrcS2YF2okAFAEoUwzJi4ALAhAB08FkgC80AEQAJAKIAZCwHkjy6AF9UT1KNrdoYRNEO0yAdzhEBVcxahAyLRBqflkjACEyADMZMmgAYTUwATIjABpPRB09eVQveGLWH2MAdRkQSjs3CHDI6NijWCSuMhIMrJz8wordVlKgA)
2. [Example: Modifying the output of typescript](https://repl.it/@tbhaxor/readonlyclass)

|EXAMPLE 1 OUTPUT|EXAMPLE 2 OUTPUT|
|:----:|:----:|
| ![image](https://user-images.githubusercontent.com/28386721/110164319-2f6dba80-7e17-11eb-8106-134312d8d7e3.png) | ![image](https://user-images.githubusercontent.com/28386721/110164571-8a071680-7e17-11eb-8963-165dab0bb2ee.png) |

## 💻 Use Cases

> _Actually giving meaning to readonly modifier_

**Comment by MartinJohns** [comment]
You should note that `readonly` only means "readonly via this type", and all type information is lost after compilation. Also "readonly" interfaces are implicitly compatible with the mutable counterpart:

    function mutateData(data: { value: string }) { data.value = "hello"; }
    
    const readOnlyData: { readonly value: string } = { value: "test" };
    mutateData(readOnlyData); // Works fine

---

Also in #41207 it's mentioned that this (no readonly after compilation) is the intended behavior.

**Comment by DanielRosenwasser** [comment]
[Non-goal #5](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals)

> Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

**Comment by tbhaxor** [comment]
> You should note that `readonly` only means "readonly via this type", and all type information is lost after compilation. Also "readonly" interfaces are implicitly compatible with the mutable counterpart:
> 
> ```
> function mutateData(data: { value: string }) { data.value = "hello"; }
> 
> const readOnlyData: { readonly value: string } = { value: "test" };
> mutateData(readOnlyData); // Works fine
> ```
> 
> Also in #41207 it's mentioned that this (no readonly after compilation) is the intended behavior.

Yes, that what I meant. What is the use of adding readonly in typescript if it's actually of no use after transpilation?

There has be to special meaning to the modifiers

**Comment by tbhaxor** [comment]
Also I have tested my code, it is currently working on all the targets from `es3` to `esnext`

**Comment by MartinJohns** [comment]
> What is the use of adding readonly in typescript if it's actually of no use after transpilation?  
> There has to be special meaning to the modifiers

The use is to describe read-only access via that type/interface. That is the meaning and purpose of the `readonly` modifier.

Also, very important and often misunderstood: **readonly !== immutable**

**Comment by tbhaxor** [comment]
Looks like i misunderstood readonly. 

Thanks @MartinJohns
