### ISSUE TITLE
Classes with private members are not compatible with intersection types

### ISSUE THREAD

**Issue by scottbedard** [microsoft/TypeScript#43109]
# Bug Report

Classes with private members are not compatible with intersection types.

### 🔎  Search Terms

Member visibility, private members, intersection types

### 🕗  Version & Regression Information

This changed between versions 3.8.3 and 3.9.7

### ⏯  Playground Link

3.8.3 works, [playground](https://www.typescriptlang.org/play?ts=3.8.3#code/PTAEAcFcCMBsEsDGBYAUI2BDAzt0AFGBRAMQHszQBvCIpUAFwAt4A7AcwC5RNWBPUAF80GHHkJwkAIUwAnarUmJGLDt14DhqNAz7gApgTqkK0OaAC8RpeUoAya8Rmy0aEBFlkG+xN4AmIli4BJ7evvp+tgrgoT7+KmxcPPxCgWIhXnERztGx4X4Jasmarqi6Bhlh-rZm8lb4edUUoA4NmfnOpe4x8ABumN5pwQ19A-pRND393oVJGqnoQeKyo945kyvThsyJ6ilaOnqGI1s15vWbY1Gtl2tyaEA)
3.9.7 doesn't, [playground](https://www.typescriptlang.org/play?ts=3.9.7#code/PTAEAcFcCMBsEsDGBYAUI2BDAzt0AFGBRAMQHszQBvCIpUAFwAt4A7AcwC5RNWBPUAF80GHHkJwkAIUwAnarUmJGLDt14DhqNAz7gApgTqkK0OaAC8RpeUoAya8Rmy0aEBFlkG+xN4AmIli4BJ7evvp+tgrgoT7+KmxcPPxCgWIhXnERztGx4X4Jasmarqi6Bhlh-rZm8lb4edUUoA4NmfnOpe4x8ABumN5pwQ19A-pRND393oVJGqnoQeKyo945kyvThsyJ6ilaOnqGI1s15vWbY1Gtl2tyaEA)

### 💻  Code

```ts
class Foo {
  private thing: any
}

class Bar {
  private thing: any
}

type Foobar = Foo & Bar
```

### 🙁  Actual behavior

type `Foobar` is reduced to `never`

### 🙂  Expected behavior

Type `Foobar` should be `Foo & Bar`, behaving the same as if `thing` was a public or protected property.

**Comment by MartinJohns** [comment]
This is intentional:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#stricter-checks-on-intersections-and-optional-properties

**Comment by scottbedard** [comment]
Ah, thanks for the clarification
