### ISSUE TITLE
Transform static class field even target esnext

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#43113]
# Bug Report

### 🔎 Search Terms
esnext, class, static

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99#code/MYGwhgzhAEDC0G8BQ1oQC5nQS2Nd0AvNABQCURAfPgBbYRIC+QA)

### 💻 Code

```ts
class C {
  static t = () => this
}
```

### 🙁 Actual behavior

```js
class C {
}
C.t = () => this;
```

And with an exception.

### 🙂 Expected behavior

```js
class C {
  static t = () => this
}
```
Works fine. And:
`C.t() === C // true`

**Comment by Kingwl** [comment]
BTW: I'm not sure which version is the bar that should we ignore the transform.

**Comment by ExE-Boss** [comment]
You need to set <code>[useDefineForClassFields]</code> to `true`.

## See also:
- <https://github.com/microsoft/TypeScript/issues/34787>

[useDefineForClassFields]: https://www.typescriptlang.org/tsconfig#useDefineForClassFields

**Comment by Kingwl** [comment]
Ohhh. Thanks!
