### ISSUE TITLE
Don't suggest `undefined | null` properties

### ISSUE THREAD

**Issue by wojpawlik** [microsoft/TypeScript#43117]
# Suggestion

## 🔍 Search Terms

undefined null properties autocomplete autocompletion suggest

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

`Union/Strict` is very useful for undiscriminated unions. It adds `?: undefined` / `?: never` properties to all the variants, so
- It disallows excess properties (https://github.com/Microsoft/TypeScript/issues/20863#issuecomment-479471546),
- It allows to access any properties without ([uncomfortable](https://github.com/telegraf/telegraf/issues/1388#issuecomment-791573609)) narrowing.

There's just one problem:

> After narrowing [...], suggestions are bloated with multiple `?: undefined` properties.

![expected](https://user-images.githubusercontent.com/23058303/110210809-ae083d80-7e93-11eb-94ec-a04add127ffe.png)

![actual](https://user-images.githubusercontent.com/23058303/110210790-9df05e00-7e93-11eb-86d3-b787de3c8228.png)

https://codesandbox.io/s/ts-toolbelt-forked-fomds

## ⭐ Suggestion

Hide `undefined | null` properties from suggestions.

`undefined` is more readable than `actual.bar` anyway.

**Comment by RA80533** [comment]
The issue you're having is related specifically to the ts-toolbelt package. You might have better luck opening an issue in their repository for what you're dealing with.

**Comment by MartinJohns** [comment]
@RA80533 I'm pretty sure the purpose of that library / the type is to explicitly provide the properties from the other union types with an `undefined` type, and OP is simply asking to not show properties of types when the property type is `undefined` (which IMO would be really weird behavior).

**Comment by RA80533** [comment]
It appears so. In [ts-toolbelt/Strict.ts](https://github.com/millsp/ts-toolbelt/blob/fd03c53dec985a217587687a4d584688525fc955/sources/Union/Strict.ts), we can see that `Union.Strict` merges the unions together using the `OptionalFlat` type defined elsewhere in the library.

**Comment by wojpawlik** [comment]
@MartinJohns understands. Moving the `undefined | null` properties to the bottom of the list and somehow graying them out would be fine too and perhaps less "weird", but it probably needs more code.

@RA80533 the issue is not specific to `ts-toolbelt`. I ended up implementing [essentially the same type](https://github.com/telegraf/telegraf/blob/0894986e8f45d51a8e90c829be8a8184c29e6bf5/src/deunionize.ts#L11-L14). Same problem, no fix.

**Comment by RA80533** [comment]
@wojpawlik If I am understanding your problem correctly, I believe it is implementation-specific. That would mean that, just as it existed in ts-toolbelt, the problem would exist in your implementation if it was written the same way.

Take a look at the following snippet:

```ts
export type Result<TValue, TError = unknown> = Result.Success<TValue> | Result.Failure<TError>;

export namespace Result {
  
  export class Success<T> {
    public constructor (public readonly value: T) {}
    
    public isSuccess(): this is Result.Success<T> {
      return this.constructor.name === Result.Success.name;
    }
    
    public isFailure(): this is Result.Failure<T> & never {
      return false;
    }
  }
  
  export class Failure<T> {
    public constructor (public readonly error: T) {}
    
    public isSuccess(): this is Result.Success<T> & never {
      return false;
    }
    
    public isFailure(): this is Result.Failure<T> {
      return this.constructor.name === Result.Failure.name;
    }
  }
  
}
```

```ts
declare function f<T>(): Result<T>;
```

TypeScript will hint at the existence of `isSuccess()` and `isFailure()` on the return value of `f()`. Both type guards further elaborate the true shape of the value: a truthful `isSuccess()` adds `value` to the list of hinted properties while a `isFailure()` adds `error` to the list of hinted properties, etc.

Is this the kind of behavior you're looking for?

**Comment by RyanCavanaugh** [comment]
It's already possible to filter out `undefined`-inhabited properties in the type system, so if a utility type can do that if that's what should be happening.

I think it would be very confusing to do this in general; we can't assume what's intended by this sort of property.

**Comment by wojpawlik** [comment]
I'm suggesting to just hide it from suggestions without affecting typechecking, not to disallow accessing it.

I don't think there's a way to narrow a value and end up with less properties than one started with.

I'm trying to accurately type an API with an undiscriminated union with [35 variants](https://github.com/KnorpelSenf/typegram/blob/8fa3912cbddeb147c922e06881a854ebf3622ab1/message.d.ts#L198-L244) (no classes @RA80533). My [proposal](https://github.com/tdlib/telegram-bot-api/issues/93#issuecomment-778320913) to add discriminators was rejected. And `Union/Strict` is the [blessed](https://github.com/microsoft/TypeScript/issues/20863#issuecomment-540838200) way for EPC in non-discriminated unions, it should act like it!
