### ISSUE TITLE
Type Script cause VS 2015 Enterprise to use high CPU continuously 

### ISSUE THREAD

**Issue by prayaggandhi1080** [Microsoft/TypeScript#4311]
I had type script installed for VS 2015 Enterprise edition and as soon as I opened a solution containing java script files VS 2015 continuously used high CPU. It also prevented VS 2015 from detaching from the debugging session. Further more it prevented VS 2015 process to terminate even after closing VS 2015. 

All of the issues went away as soon as I uninstalled TypeScript for VS 2015. Before uninstalling I had updated TypeScript with latest version for 2015. 

-Prayag

**Comment by mhegazy** [comment]
@prayaggandhi1080 can you take a process dump when VS is hung?

**Comment by nippur72** [comment]
This also happens to me in VS2015 Community Edition, in a node `.njsproj` project. 

All was doing fine, but at a certain point VS became slow:
- slow to load the `.sln` (up to 15 seconds on a small project)
- always high CPU intensive (30%) and lagging while typing
- sometimes unable to be shut down (I have to kill `devenv.exe`)

Using `typescript@next`.

**Comment by mhegazy** [comment]
@nippur72 so are you using DevMode to enable loading LS from `typescript@next`? what version of TypeScript 1.53? or 1.5.4? is this consistent for all projects? or is it a specific project that causes the problem?

**Comment by nippur72** [comment]
Some additional info:
- the problem is with a specific `.njsproj` project only. I tried creating a fresh new `.njsproj` and it seems to work normally.
- when using `typescript@1.5.3` solution doesn't close, it hangs with `devenv.exe` and `svchost.exe` both at 29% of cpu time.
- when using latest `typescript@1.6.0-dev.20150819` the solution closes, but `devenv.exe` is still at 29% while typing (in other plain TypeScript project usually it's around 1%).

**Comment by mhegazy** [comment]
@nippur72 can you share the project that is causing the issue? you can email me on mhegazy at microsoft.

**Comment by nippur72** [comment]
@mhegazy don't know if you received my mail, anyway it seems to be a [nodejstools bug](https://github.com/Microsoft/nodejstools/issues/384) (at least as regards my slowness issue).

**Comment by mhegazy** [comment]
oh.. sorry i have not had time to look into the repro. i will check with @mousetraps to see if there is anything on the TS side that needs to be done.

**Comment by mhegazy** [comment]
@prayaggandhi1080 is this (https://github.com/Microsoft/nodejstools/issues/384) the same issue you are running into?
