### ISSUE TITLE
Smart Cast / Type Inference fails for element access expression

### ISSUE THREAD

**Issue by Danielku15** [microsoft/TypeScript#43118]
# Bug Report

### 🔎 Search Terms

smart cast smartcast inferred type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about all listed topics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210228&ssl=1&ssc=1&pln=17&pc=2#code/KYOwrgtgBAygLgQzsCo4GkCWIAmUDeUAQgDYD2AxgNZQC+AUNsgE4BmCFwsiyqIcBKFWw4AXNyQo0WXHUb9gbDl1KUawAB7JcAZwm80gnTyn8do+JL5wA2gF059VmBAU4mMiCiYdq6gAoQcUsDfgBKcS8fYnJqQWZgODBmLxAAOmFZAF4c-VMMETS-GgYnFzcPLwALBFwSYBD8nX9jKzRzPOt7MIJ6KH7vVih-H2KWk2sdGwAGOzCe-D6B5dbQuD0sqFWmmbs07cmAbiX+hlLnV3dPKBq6hom0cbb+YIfw3uXMIZHfWKontbzD7LAYHQybMH8fZvda7Y7LM5AA)

### 💻 Code

```ts
enum StatementKind { Block }
interface Statement { kind: StatementKind }
interface Block extends Statement { statements:Statement[] }

function isBlock(n: Statement): n is Block { return n.kind === StatementKind.Block }

function handleStatements(statements: Statement[]) {
    if (isBlock(statements[0])) {
        statements = statements[0].statements;
    }
}

function handleStatement(statement: Statement) {
    if (isBlock(statement)) {
        statement = statement.statements[0];
    }
}
```

### 🙁 Actual behavior

In line 9 the compiler is not able to infer the type `Block` for `statements[0]`. The `isBlock` checks that the passed parameter is a `Block`, and this works correct if you just pass in a normal identifier (second function), but if you pass in an array item, it does not work (first function).

This requires redundant casting to the actual type. 

### 🙂 Expected behavior

Also for element access expressions the smart cast from `Statement` to `Block` should work within the if statement.

**Comment by MartinJohns** [comment]
And another duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by MartinJohns** [comment]
Duplicate of #10530.

**Comment by Danielku15** [comment]
Looks like I had the wrong terminology (from Kotlin) in mind when searching for this topic. Closing this issue in favor of the other one. 😅
