### ISSUE TITLE
Function inference fails when a final argument is supplied after rest via destructured tuples

### ISSUE THREAD

**Issue by poteat** [microsoft/TypeScript#43122]
# Bug Report

I'm not sure whether inference failures are usually classified as suggestions or bugs. Sorry if I've assigned this the wrong label!

### 📖 Context / Introduction

I'm trying to improve the typings for an open source library called [reselect](https://github.com/reduxjs/reselect). Their `createSelector` function first takes in an arbitrary amount of "selector" functions that take in one parameter as a given state type, and then takes in one final additional function which combines the results of the previous functions. I have an implementation, but inference isn't working as I expect.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.2#code/KYDwDg9gTgLgBDAnmYcDKwA2wDGNoA8aMAhjMAHxwC8cAFAM6nkBc6zwAlDVQK4B2Aa34QA7vwDcAKFCRYCZKgzY80ACq8w2Ihyq1lufFB1lKAbQC60meGjwkKOAFEQJALZbgxUzTgBvKTg4ADMICDYAIlCICOkggCMSKDYAFgAmaQBfa1k7EIE8AEsIfjgcKGBTA1VjNDhQcn4AEwZ0LEN1TW0Xd09vcgoKOkC4ADpxhnaahjYzcdHJlSMZ9AAaELY6EDYSfkRuaipdxAs4AHozkLKSXknWwoYGXmAGKW4AoJwShghsUcwIABzRhTZacLJSKTlSrkapGYZBLYHKggUbRdYXOAgOAPOAQYJwADkx0JCkcUDIAAtgFAEJTds5XB5sP1gCMkTwsaNElAMZdsbj8USSWTUBSYNTaRKGT1mV4OOzkXB0m9pEA)

### 💻 Code
```ts
export type Selector<State> = (state: State) => unknown;
export type SelectorTuple<State> = Selector<State>[];

export type ExampleState = {
  foo: "foo";
  bar: 42;
};

export function createSelector<S extends SelectorTuple<ExampleState>>(
  ...selectors: [...selectors: S, f: (x: any) => any] // f causes issues
) {
  console.log(selectors);
}

createSelector(
  (x) => x.foo, // x is of 'any' type rather than ExampleState
  (x) => x.bar, // x is of 'any' type rather than ExampleState
  () => 42
);
```

### 🙁 Actual behavior

In the `createSelector` call, all of the `x` parameters have an implicit type of `any`, instead of `ExampleState`.

Observations:
* When the last tuple element is removed from the type, inference works.
* When the last tuple element is made to have zero parameters, inference works.
* When the last tuple element is made to be anything except a function or `any`, inference works.

For some reason, the compiler is having difficulty inferring the rest parameters in this case.

### 🙂 Expected behavior

I would expect the type system to infer that the `x` parameter of all functions except the last is `ExampleState`.

**Comment by mkantor** [comment]
In case it's useful, here's a smaller example of the same issue:
```ts
declare function example(...args: [...((n: number) => void)[], (x: any) => void]): void
example(
  x => x.foo, // x is any rather than number
  x => x.bar, // x is any rather than number
  x => x.baz, // x is correctly any here, but noImplicitAny is incorrectly complaining
)
```
[Playground](https://www.typescriptlang.org/play?ts=4.2.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxAA8oBbABwhAAoA6O2AcwGcAueAbTpqqtTdWQkARiBgBKeAF4AfPABuOLMDHsAugBp4VQmyioAnhJnzFwVWLYKlAKCKkK1a-HiEpswjUQ4cmgPS+XeCwmeD19eBgoDAALUXgYvXgBYVEnQOMPIVg-ANdg0IMIqNiYeOjE5JEYNNcMmiyALxzA-LAcGDhMCHCw+BKQTSFkDCScAElyCCwwLAwAQUL8rHR2zoxu+DbJqGXlhmsxIA)
