### ISSUE TITLE
Inconsistency in generic type when used as a function's optional type

### ISSUE THREAD

**Issue by mk360** [microsoft/TypeScript#43126]
# Bug Report

### 🔎 Search Terms
generic optional type

### 🕗 Version & Regression Information
First noted occurrence: TypeScript v4.2.2
The bug exists in the TypeScript Playground (version 4.3.0-dev.20210228).

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about any issue related to generic types and their usage
- I was unable to test this on prior versions because Microsoft VS Code's TypeScript version is currently 4.2.2 and I would like to keep my workspace as clean as possible.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210228#code/C4TwDgpgBAogHgQwLZgDYQMIHsB2wECWOEATgCrgQA8ARgQOYDyNAVhAMbBQRzAQ4ATAM5QA3lADaAawggAXFCHASRegF0FJCAgG5UIRctUS1UAL4AaKDIM8+gkTawAzKHSasOwAHxQAvGIAUFAhUGAkWJAkoACMCjgArkg0pMGh4ZGkoABMCkoqOPRpIRlRoADMCu7MbJzSsmoSicmkaoFmANyBgehcWKz+QaFQAETOBCRKIwoSI0IcuAIjpggi7LhKFsWjwAAWE0szY1gJ0bvLUKtQ6zhK7V2Bzgk4nAS4biQJu1Q23Lz8wmsshcUFAkBB-RYVgAcrgAOpYEhSVTYPCEYgkQbwZBoTC4fBEUgUSBUMEQCGsKw2bzeAAUADcECoEDR0ApYTgEUiUfj0aQAJRDUKM5msiAAOlKWRAMW2vSgWD2pAAakyCCy2bBECh0KiCRjidQyRSoUCQL4AqJOvdukA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
type ExampleContainerType<bigObject extends { [key: string]: readonly string[] }, key extends keyof bigObject> = {
    property1: number
    property2: string
    property3: bigObject[key][number]
};

let obj = {
    "first": ["second"] as const,
    "third": ["fourth"] as const
};

function bruh<key extends keyof typeof obj, NonWorkingContainer = ExampleContainerType<typeof obj, key>>(variable: NonWorkingContainer) {
    variable.property1
    // throws an error about a non-existent property, that's the wrong behavior, the property should exist
    let otherVariable: ExampleContainerType<typeof obj, key> = {};
    // correct behavior, reported an error about missing properties
};
```

### 🙁 Actual behavior
When a function argument holds the type created by `ExampleContainerType<typeof obj, key>` and used as an optional type, the compiler doesn't seem to recognize that generic type's properties (such as, property1), and throws an error saying that `property1 doesn't exist on type NonWorkingContainer`. The `otherVariable`, bearing the exact same generic type with the exact same parameters passed to it, actually recognizes that `property1` should be present. `property1` was willfully omitted to create a variable whose behavior we can compare.

### 🙂 Expected behavior
The compiler acknowledges that `variable.property1` exists, because again, with the exact setup with `otherVariable`, it does.

**Comment by RyanCavanaugh** [comment]
A legal call to `bruh` is
```ts
bruh("hello world");
```
and strings don't have a `property1`.

Critically, a generic default is not a type alias. `NonWorkingContainer` isn't another name for `ExampleContainerType<typeof obj, key>`; it's a free type parameter that could be inhabited by anything
