### ISSUE TITLE
Generics aren't working as expected when using them with Partial

### ISSUE THREAD

**Issue by Andrew5569** [microsoft/TypeScript#43125]
# Bug Report

### 🔎 Search Terms

generic partial

### 🕗 Version & Regression Information

4.2.2

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMbAJYHsEBVwQDxYB8UAvFAN4BQUUAZokgBQCGATgOYBcUACm2swA2BQgEpuzBCADclAL6zKoSFADKwVqgTscKslRoBnDd2ObtshZUr1kaTFAgAPZgFswg-FkdPgEBAAmhmoaWjq4hIy0wNzwdhjYuCKiFNR0wAB0tkzkUGbcAEQFUHKilkA)

### 💻 Code

```typescript
type FunctionType<T> = {
  func(arg: Partial<T>): any;
};

type StringType = {
  str: string;
};

function example<T extends StringType>(ft: FunctionType<T>) {
  ft.func({ str: "" });
}
```

### 🙁 Actual behavior

The code doesn't compile because `ft.func({ str: "" })` gives the following error

> Argument of type '{ str: ""; }' is not assignable to parameter of type 'Partial\<T\>'.

### 🙂 Expected behavior

I would expect the code to compile

**Comment by MartinJohns** [comment]
The type `"abc"` extends the type `string`.  
The type `{ str: "abc" }` extends the type `{ str: string }`.  
`""` is not a valid value for the type `"abc"`.

This is unrelated to `Partial<T>`.

**Comment by Andrew5569** [comment]
I understand why your example wouldn't work

```typescript
function example<T extends string>(): T { return ""; }

example<"abc">();
```
`T` could be any string and `""` isn't valid for all types that extend `string`. For example, the type `""` isn't valid type for `"abc"`.

Perhaps I'm misunderstanding but I don't think that's the case here. In this case it doesn't won't work on any type.

```typescript
type FunctionType<T> = {
  func(arg: Partial<T>): any;
};

type StringType = {
  str: any;
};

function example<T extends StringType>(ft: FunctionType<T>) {
  ft.func({ str: "" as any });
}
```
Surely `{ str: any }` should be a valid type for `{ str: any }`, shouldn't it? However, this doesn't work.
