### ISSUE TITLE
Why not reporting an error when instantiating a generic class without explicit or inferred type

### ISSUE THREAD

**Issue by doberkofler** [microsoft/TypeScript#43127]
# Suggestion

## 🔍 Search Terms

generic class inferred unknown

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I do not understand why TypeScript allows to instantiate a generic class without having specified the actual generic type parameter?
In the following example, the class `Foo` has a generic type parameter `T`.
In the line `const foo = new Foo()` it is possible to create a new `foo` object without having to specify the generic type parameter.
`foo` has the type `Foo<unknown>` and `bar` has the type `valueType<unknown>`.

I absolutely understand that TypeScript would infer from the arguments if possible but what if there is nothing to infer from - like in my example. Does it really make sense to use unknown instead of informing me, that there is no explicit type parameter and the type cannot be inferred?

## 📃 Motivating Example

```typescript
type valueType<T> = {
   name: string,
   key: T|null,
};

class Foo<T> {
   private value: valueType<T>;

   public constructor() {
      this.value = {
         name: '',
         key: null,
      };
   }

   public setValue(value: valueType<T>) {
      this.value = value;
   }

   public getValue(): valueType<T> {
      return this.value;
   }
}

const foo = new Foo(); // I would expect a TypeScript error here because the type of foo cannot be inferred
const bar = foo.getValue();
```

**Comment by RyanCavanaugh** [comment]
> Does it really make sense to use unknown instead of informing me, that there is no explicit type parameter and the type cannot be inferred?

Yes. This occurs in many places where it's not suspicious, e.g. optional function parameters.
