### ISSUE TITLE
Omitting a property from an interface with an index signature causes bug

### ISSUE THREAD

**Issue by komninoschat** [microsoft/TypeScript#43139]
# Bug Report

I have an interface `Feature` which has an index signature and two properties defined explicitly. I then define a new `FeatureNoWidth` type which uses `Omit` to omit one of the explicitly defined properties. `FeatureNoWidth` ends up having a weird type.

### 🔎 Search Terms

`omit`, `index signature`

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Types, Omit.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210308#code/JYOwLgpgTgZghgYwgAgGITmArlFBvAKGWWABMAuZELAWwCNoBuI5AdzLAAtLr6mWA2gGsIAT0oBnMFFABzALqU4IUcwC+BAmFEAHFOkw4IAOQD2AdQ6dkAXmQB5GsDAAeA9lwAaZAHJ2pLh8APmYAelDkAAlTADdoOWRY6GQuFG09EhAUzhQdABs4UVkoUywQUmRRYAg80gls4AlyAnCU3X0MDxMLK1tkQlbiYgEAD0lpOUVkZVUWiKHkUZ5aBigpmbCIjVbWTkwAfk0IEZ1TKDBkGDKEMGBTLJAegM4AFVN3IwBZOB09KAAKR6WZ6UD64MzArgASlBnSM-RYuA8WUICwAdBigVZPCxiP4uJQACw44gaNRAA)

### 💻 Code

```ts
interface Feature {
  id: number;
  width: number;
  [key: string]: any;
}

type FeatureNoWidth = Omit<Feature, 'width'>;
// Hovering over the type in the playground yields this:
// type FeatureNoWidth = {
//     [x: string]: any;
//     [x: number]: any;
// }
// what?

export function noWidthToFeatureMapper(noWidth: FeatureNoWidth): Feature {
  return {
    ...noWidth,
    width: 4,
  }
}
```

### 🙁 Actual behavior

`FeatureNoKeys` is
```ts
type FeatureNoWidth = {
    [x: string]: any;
    [x: number]: any;
}
```

### 🙂 Expected behavior

Expected `FeatureNoKeys` to be
```ts
type FeatureNoWidth = {
  id: number;
  [key: string]: any;
}
```

**Comment by MartinJohns** [comment]
See #42436.
