### ISSUE TITLE
Why did you write tsc in typescript???

### ISSUE THREAD

**Issue by grian32** [microsoft/TypeScript#43138]
like why is it not in c or rust or even cpp like a normal compiler?? this makes no sense ???

**Comment by WhileTrueEndWhile** [comment]
> If the guys from SASS managed to do that, it can't be that difficult

XD

**Comment by MartinJohns** [comment]
https://en.m.wikipedia.org/wiki/Eating_your_own_dog_food.

**Comment by komninoschat** [comment]
https://en.wikipedia.org/wiki/Bootstrapping_(compilers)

**Comment by grian32** [comment]
> https://en.m.wikipedia.org/wiki/Eating_your_own_dog_food.

well yeah but ts is pretty slow

**Comment by emiliskiskis** [comment]
https://swc.rs/, but couldn't get it to type check my project while compiling with swc-loader in webpack v4.

**Comment by RyanCavanaugh** [comment]
This doesn't seem like it's asking for a productive discussion. There are lots of good places to vent on the internet apart from a bug tracker.
