### ISSUE TITLE
How can I debug language service with TSX?

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#4314]
I've been debugging TypeScript with dev mode in Visual Studio but my VS2015 does not support .tsx file. Adding extension mapping does not help me very much as it doesn't really load language service.

Are there other good tools to debug language service with TSX file?

**Comment by DanielRosenwasser** [comment]
You can create a fourslash test and run the test in the browser with `jake runtests-browser tests=yourTestName` or add a `debugger` statement to your test and run `jake runtests-browser tests=fourslash`.

**Comment by SaschaNaz** [comment]
`jake runtest-browser`. Thanks! :+1:
