### ISSUE TITLE
organizeImports without the reordering ("remove unused imports" being its own option)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/TypeScript#43141]
# Suggestion

I was originally using the `organizeImports` in my `"editor.codeActionsOnSave"` block on VSCode.  The issue with this feature is it also does the sorting which we don't want. 

It's currently not possible to switch the sorting off without losing the "remove unused imports".

According to VSCode [documentation](https://code.visualstudio.com/docs/languages/typescript#_code-actions-on-save) "addMissingImports" is offered as an "on save" option, but not "removeUnusedImports".

## ⭐ Suggestion

As some projects already use [tools](https://eslint.org/docs/rules/sort-imports) which handle ordering it would be nice to just add/remove imports without changing the order.

Then have a separate command which handles ordering.

## 💻 Use Cases

My team are happy with the ordering of imports and don't want changes. However by keeping the ordering I lose the ability to remove unused imports.

## Example
```json
    "editor.codeActionsOnSave": {
      "source.organizeImports": false,
      "source.fixAll": true,
    },
```

**Comment by blutorange** [comment]
Another use is when you are using a code formatter such as prettier that sorts the imports (with an appropriate prettiert plugin) but  doesn't have enough knowledge to find and remove unused imports. It would be great if the IDE would remove the unused imports, and prettier could format them.

**Comment by jasonwilliams** [comment]
Hey @RyanCavanaugh so you still need more feedback for this? 

It seems like this would be an easy win, as you already implement both features, this is just asking you to separate them out.

**Comment by jasonwilliams** [comment]
Another reason why these command should be separated is due to the fact that some projects like to use [ESLint](https://eslint.org/docs/rules/sort-imports) for organising imports but still want TypeScript to bring in imports which are being used. 

Sadly at the moment you can't do that without conflicting with ESLint.

**Comment by miloszpp-sumo** [comment]
For anyone waiting for this, you can use this extension: https://marketplace.visualstudio.com/items?itemName=kuscamara.remove-unused-imports

**Comment by andrewbranch** [comment]
We have a code fix for removing all unused declarations that I think would be trivial to expose to `codeActionsOnSave`. I actually thought it already was exposed, but it looks like surprisingly little is exposed. Would that satisfy this request, or does it need to be specific to imports?

**Comment by jasonwilliams** [comment]
Yes exposing that would be great @andrewbranch, it would be great if VSCode offered this as an "on save" action via the extension, but just exposing it would be a win here

**Comment by ionut-mocan** [comment]
I want the remove without organizing feature too...

**Comment by andrewbranch** [comment]
I think this slipped through the cracks, @jasonwilliams. Bringing it up with the VS Code team tomorrow. Looking back at my last comment, I’m not sure offering the remove-all-unused-stuff on save is a workable alternative after all, since that could delete entire local function and class declarations, which is probably not what anyone wants 😅

**Comment by andrewbranch** [comment]
@jasonwilliams your original post showed an example code snippet with `"source.fixAll": true`. Do you actually use that, or was it just for context?

**Comment by jasonwilliams** [comment]
> @jasonwilliams your original post showed an example code snippet with `"source.fixAll": true`. Do you actually use that, or was it just for context?

Yes I used to use that also but I can’t remember specifically what for. It may have been to remove imports I wasn’t using.

**Comment by jasonwilliams** [comment]
Thanks so much for this @andrewbranch can't wait to try it

**Comment by andrewbranch** [comment]
Once https://github.com/microsoft/vscode/pull/161654 lands you’ll be able to try it in nightly/Insiders. I’m working on exposing Sort Imports and Remove Unused Imports from the command palette as well.

**Comment by jasonwilliams** [comment]
Wil remove unused imports map to VSCode’s “source.fixAll” option on save? And sort imports maps to “source.organizeImports” then I guess these will “just work” for people who have that set

**Comment by andrewbranch** [comment]
I haven’t made any changes to `source.fixAll` in https://github.com/microsoft/vscode/pull/161654. I’ll take a look at what it currently does and see if it makes sense to include it.
