### ISSUE TITLE
4.2 regression: TS2345: argument is not assignable to a parameter of a generic type

### ISSUE THREAD

**Issue by Igorbek** [microsoft/TypeScript#43152]
# Bug Report

Mapped type's element is not assignable to type `T | undefined` where `T` is unconstrained

### 🔎 Search Terms

mapped types, TS2345, generic, not assignable

### 🕗 Version & Regression Information

Regression in TS 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiMEMwB4ZQgD2BAdgEwGcoB7AIwCsIBjYAPigF4oBvAKCg6gG0BpKASxxQA1hBDEAZrAC6ALhbtOSjPJwBXALakIAJ0UcAvqyOs81ADYId0CWpw1+xIQHNkAFVoAKAG4JzaiAB+eTcASnlvYn48AG5WVlt7YEchCVR0LFxCEgpqOk8NEA0keThEFBhaABoReVFxKQQcEFCFJSonAmB0cwgNSTQmQuKwLmEoBCJ6yRl9KGdPCF7+iRhQuYB6DYA-Xb3tqDcAZQAmAGYAFgBWeQBBHWdNXG6Z0EgoAHJmKBUodS1dDEoAYPgIiDhiN1JgR+M4cAhSL0oMBiFAwFYEBoINgdCQpG9oB8ykhULQxmIZjBpB8AHTGIA)

### 💻 Code

```ts
type MyMap<M extends object> = {
    [K in keyof M]: {
        x: number
    }
}

declare function g<T>(value?: T): void;

function f<M extends object>(mymap: MyMap<M>, k: keyof any) {
    const elemofM = mymap[k as keyof M]
    g(elemofM)
    //~~~~~~~ TS2345: Argument of type '{ x: number; }' is not assignable to parameter of type 'MyMap<M>[keyof M]'.
}
```

### 🙁 Actual behavior

error TS2345: Argument of type '{ x: number; }' is not assignable to parameter of type 'MyMap<M>[keyof M]'.

### 🙂 Expected behavior

No error (it was not in TS 4.1)

**Comment by ahejlsberg** [comment]
Repro that fails in both 4.1 and 4.2:

```ts
function f<M extends object>(mymap: MyMap<M>, k: keyof M, z: { x: number }) {
    const q1: MyMap<M>[keyof M] = z;  // Ok
    const q2: MyMap<M>[keyof M] | undefined = z;  // Error
    const q3: MyMap<M>[keyof M] | string = z;  // Ok
}
```

It only fails for unions with `undefined` or `null`. The issue is a missing normalization step in code that eliminates `undefined` and `null` from target unions in order to improve the error reporting experience.
