### ISSUE TITLE
Partial with generics and nulls failing to compile in 4.2.x

### ISSUE THREAD

**Issue by thunderkid** [microsoft/TypeScript#43153]
# Bug Report
Using `Partial` in the following way now fails to compile.

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.x

### 💻 Code
```
class Monkey {}

export type MonkeyObj<T> = { [P in keyof T]: Monkey | null}

function f1<T>(stuff1: Partial<MonkeyObj<T>>) {
}

function f2<T>(stuff2: MonkeyObj<T>) {
    f1(stuff2);  //  <<< error here
}
```

(More generally, I think that this also needs to compile if you replace `Monkey | null` with `Monkey` - surely anything should be assignable to its own Partial. However, in this form it doesn't compile in 4.2.x, and didn't work in 4.1.5 either, so maybe that would count as a feature request. But with `Monkey | null` it's definitely broken between 4.1.5 and 4.2.x.)

### 🙁 Actual behavior
In typescript 4.2.3 (and all 4.2.x below that) it fails to compile. It compiles fine in 4.1.5.
Error is:
```
 Argument of type 'MonkeyObj<T>' is not assignable to parameter of type 'Partial<MonkeyObj<T>>
Type 'Monkey | null' is not assignable to type 'MonkeyObj<T>[P] | undefined
Type 'Monkey' is not assignable to type 'MonkeyObj<T>[P]
```
### 🙂 Expected behavior
Should compile as it did in typescript 4.1.5.

**Comment by weswigham** [comment]
This was fixed in the beta/nightly, from what I can tell. Not sure by what, specifically.
