### ISSUE TITLE
Generic cannot be narrowed

### ISSUE THREAD

**Issue by danez** [microsoft/TypeScript#43151]
# Bug Report

### 🔎 Search Terms

generic, keyof, narrow

I found some other issues but nothing really was the same kind.

### 🕗 Version & Regression Information

tested with 4.2.3, but also happens in 4.1, 4.0, 3.9

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _generics_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&ssl=1&ssc=1&pln=26&pc=1#code/FASwdgLgpgTgZgQwMZQAQEFUG9ir6iATwAcoAuVAInUoG5gBfUSWRFVAIW13yNIsoc6jYMCgAPYgHsYEAiTToYMBIQDSUQgGcAPABUAfKgC82VAG0ACqnCoA1pqlxUegLoU9V16gnQwAEy0MZVUdBDBCIwB+VGsKMCgAN1hUBnMHQicXV3oxSRk5JAAbBC0ggDkpfyhLBAgAC30jHHxUYgBXLXqACgyKJRV1TV1DAEosJh48JHqoJDtu0YoGkCDV1Erq2oaddGap1tQYKAh2mDACGHaoelamSYB6B9QAWjfRJCkwLTliOvqTKgEgB3DZVGr-XaoAA+nAMi1yIGc3T+DQAdDM5gtRqNuK1Pt85IRAaj6rRUE9UDpqagulJ2kV-KgAEZoTYQnZ7ERAA)

### 💻 Code

```ts

interface A {
    type: "A";
}
interface B {
    type: "B";
}

export type ArrayKeys<T> = { [P in keyof T]: T[P] extends Array<any> ? P : never }[keyof T];

export class NodePath<T> {
    push(key: ArrayKeys<T>){}

    check(): this is NodePath<A> {
        return true;
    }
}

// ---

const path = new NodePath<A | B>();

if (path.check()) {
    const y = path; // <<< should be NodePath<A>
}
```

### 🙁 Actual behavior

On line 24 `path` is `NodePath<A | B> & NodePath<A>`

If the `ArrayKeys<>` type is not used in `NodePath` it works.

### 🙂 Expected behavior

On line 24 `path` is `NodePath<A>`

**Comment by RyanCavanaugh** [comment]
This code example is trying to behave as `path` were declared as
```ts
const path: NodePath<A | B> = new NodePath<A>();
```
Narrowing from `T<U | V>` to `T<U>` via intersection isn't sensical when `T`'s type parameter appears in both co and contravariant positions.

**Comment by danez** [comment]
Thanks for the quick reply. 

Where is the type parameter use as contravariant? Is there maybe a way to prevent that? What `ArrayKeys` is trying to do is simply extracting all property names of the type parameter which are an array.
