### ISSUE TITLE
TS1387: Lack of error message

### ISSUE THREAD

**Issue by endel** [microsoft/TypeScript#43164]
# Bug Report

### 🔎 Search Terms

- "Function type notation must be parenthesized when used in an intersection type"
- TS1387

### 🕗 Version & Regression Information

Tested on `4.2.3`. (Not sure when issue started happening)

### ⏯ Playground Link

https://www.typescriptlang.org/play?strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&alwaysStrict=false#code/KYDwDg9gTgLgBDAnmYcDCEC2YCWAbAQxhwgDsBRKKaOAXjgG8ATAV000QC44AjCCPMAKkAvnABkcABQBKOgD44ANwg4mAbgCwAKFCRYCZKgDqAC0QA5CBmz4iJClRr1ZC5aqYTGrdl179BYRF1OAB6ULgcUiVgWGBPGKgAZwc4ADNqTDgAAxtcQmIySmoobJ09aHgkFDgAFVMcJONoAGskum82Dm4+ASFRLylXWkUVNRktbR0AYzIk+AgW7jNLayx8+yKnKA6pNJZSacLSVwYdOAv0g6PU-cPT88uRR4u76YA6Hw4OmCgWYEmlzgUGAMBYUFIV0OkxEMlkk0Wny6iDCETA1BQsBRpAg8DUwFIxDSOHiOhmcyqDSarSS3HqjWaUDauzexwe2iBrNu13ZQOeHMubyRvh+fwBL2BoPBkLeMLhEx0MCpjLawu+qLgAHkANIAQjg6IgmKQkSYBKJJKYQA

### 💻 Code

This merged declaration results in a compilation error:

```ts
export type CompilationError = {dummy: boolean} & () => void;
```

Whereas the same merged declaration, but inverted, does not point the error, but cause unexpected behaviour:

```ts
export type WhyNoCompilationError = () => void & {dummy: boolean}; // inverted version from `CompilationError`
```

The correct version that works is:

```ts
export type ThisWorks = {dummy: boolean} & (() => void);
```

### 🙁 Actual behavior

When getting rid of the compilation error, the type is not actually correct.

### 🙂 Expected behavior

I believe the same error should happen on both `CompilationError` and `WhyNoCompilationError`.

**Comment by MartinJohns** [comment]
> The correct version that works is:  
> `export type ThisWorks = {dummy: boolean} & (() => void);`

This is pretty much what the compiler tells you in the error.

> Whereas the same merged declaration, but inverted, does not point the error, but cause unexpected behaviour:
> `export type WhyNoCompilationError = () => void & {dummy: boolean}; // inverted version from `CompilationError``

This is not the inverted version, this is a **different** version. It's a function whose return type is `void & {dummy: boolean}`.

The inverted version would be: `(() => void) & {dummy: boolean}`

**Comment by endel** [comment]
Oh, that makes a lot of sense! Sorry for the noise!
