### ISSUE TITLE
Latest version of typescript causes "Could not load Microsoft.VisualStudio.JSLS" 

### ISSUE THREAD

**Issue by GeertVL** [Microsoft/TypeScript#4316]
I know that the solution is to get the setup from the iso of Visual Studio but does that not give a problem with versions?

And will there be a fix shortly in the install?

edit: to be precise, this error occurs when you use the Project Template of Typescript "HTML Application with TypeScript"

**Comment by mhegazy** [comment]
This is not caused by updating TypeScript update. this is causes by updating "Tools for Universal Windows Apps Development"

Please follow the steps in https://github.com/Microsoft/TypeScript/issues/4238#issuecomment-129060370 to restore your JavaScript support.
