### ISSUE TITLE
Infer returns wrong type in 4.2.*

### ISSUE THREAD

**Issue by Lehks** [microsoft/TypeScript#43161]
# Bug Report

With a particular type-setup, `infer` does not provide the correct type. When you open the playground link, you will see the type `Opts` and the types `ExtractReq` and `ExtractOpt`. `Opts` takes two type parameters, `Required` and `Optional` and `ExtractReq` and `ExtractOpt` will extract these two types using `infer`. However, the extracted types are, for the most part, incorrect.

### 🔎 Search Terms

infer, generic

### 🕗 Version & Regression Information

After updating TS to version 4.2.*. I have tried the nightly version and the problem did still arise.

- This changed between versions 4.1.2 and 4.2.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBywBuwpwLxwBKwAxtACYA8AdljgDRy3ZQB8A3ALABQPSKcAPJgYAZ0o84UosACOAVwCWUYOTigYwauVEyyUKqJhRF1AOaN51ANbUIAd2qs4AH3R1cBDC3qTpwmEUIagBDABt1EE1tXWJ9Q2NTCzgrWwcnV3cWfCycHmcCYgVlVTgAMjgABRDYRXDKAKDQsI4ePmRUAFEoqBCSGCLKABUCuCHI6J0hEXFTADMcGWKVckYQ6kRnAH4lpRW4AC4mDy5ufi6evpgA4dHxjS0pgPF1xEZ5xcbg8O3pwO+IkdmDhTjwAPRguDkYBzUyoZ4IDq6ABGMOgwAAFutyO0BM8AIw5Z6UADecBCRyMJnMcAAvq0zh0-qIAExEmaUbwMOBk5GUxI0+mnc7MgDM7LEpPJ-OpZjpjF5MqSdIZ4Mh9gxWgmvX6ypgmt2JTU50Y+qSujMEDg9igwTlpgQBpIIVEqAgcyWbOxS1FADo4ABJa0QeRhNSgFD9JaE71FcUwK1quCouCKaHUQLOsL+ops0QYkNh5OoLlQX241BFQkEbrGK6DAkMkW5nK1nUDOQNGYsptMuOty79BszUWq7gQ63AZTkMJva2a6hwMAu0R6g0IkXkEr9WcIK1t+tyOAAClMRmAITU7pSq5pz2P+JcLJcooAlK-GB5EGaafZoNZdBdSJI00chy0ZAQigAYWgFR+mrOADyHTtiTJCk4CpZV6V7SC5BgqA4JgNka0HDtZC7SVSwVZMlUFVgcMrPDYNIGBxRIutkPI1DpQwgU5Vpai+V42UVTHCckOuEQoQgYBdDseA-ygaxyXgcIIm9cJ7BCRBdBUGB5CgahdH1VBRBCABbVBzn9boQNKP9QzUFNS1TRcTLgZ1XTga8AhjbQ4CTRVhKw1zHVQTy3Q9AIvX8gI-QrP4EIkm5G2FJlooHDjJJgCjWQYv42MQ0iUpHMTIQAVWoMJFGsC4sqKRhkqk8gZLkiAFP-ck5k0XBl1EW85XcjcmS3QjZ3AkUAgAZUCMIwgDah9EIpLipEXKpXQzC6Py6bZvmxbmP6YiiqykrKI8QTaP4+i0rxEQZsUOaFqWljCqanLuM2vj5R5Gjgu204gA)

### 💻 Code

```ts
// Opts type:
type Opts<
    Required extends Record<string, unknown> | Never = Never,
    Optional extends Record<string, unknown> | Never = Never
> = Required & Partial<Optional>;

// extract types
type ExtractReq<T> = T extends Opts<infer Required, any> ? Required : never;
type ExtractOpt<T> = T extends Opts<any, infer Optional> ? Optional : never;

// shortand for Opts type with specific type parameters
type Opts3 = Opts<{ a: string }, { b: string }>;

// this type is Partial<{ a: string }> & Partial<{ b: string }> although { a: string } was expected.
type Req3 = ExtractReq<Opts3>;

// this type is Never | Record<string, unknown> although { b: string } was expected.
type Opt3 = ExtractOpt<Opts3>;
```

### 🙁 Actual behavior

The types that are inferred by `ExtractReq` and `ExtractOpt` are incorrect (see code above / playground link).

### 🙂 Expected behavior

The type `{ a: string }` in the case of `Req3` and `{ b: string }` in the case of `Opt3`.

**Comment by RyanCavanaugh** [comment]
Once you've mixed two types together into a new type, you can't "unmix" them this way unless some very particular conditions (i.e. ones you shouldn't rely on) are met. Our type alias preservation changes in 4.2 changed this example from a "happens to work" to a "happens to not work".

**Comment by FlyingPumba** [comment]
@RyanCavanaugh is there any other, more proper, way to "unmix" the types of a composed type as mentioned by OP.
E.g., from a type that is a `Opts<T, Q>`, obtain the particular T and Q.
I also had (important) code relying on this feature, and it stopped working after updating TS to 4.2.

It would be good to put a big red warning in TS documentation: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#type-inference-in-conditional-types
AFAIK, this is a listed feature, not just a "happens to work" feature.
