### ISSUE TITLE
class generic type won't be captured from constructor

### ISSUE THREAD

**Issue by yaquawa** [microsoft/TypeScript#43170]
### 🕗 Version & Regression Information
v4.3.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210309#code/MYGwhgzhAECyD2ATApiAPAFWsgHgF2QDtEYAlZYeAJ0TQjyoEtCBzAGmjEIE8A+DgNLZ8REtADWybvABm0LAF4JU2fN7QA3gChou6JUL0qAV2B5qACkncAXNAEcAbmBDHkdjAG0BAXQCUmjp6wUG6AL5aodAARmAAXmgAysIExDACvFZSdolOLm4enon+gcF6URFRsXGxVFm29nmu7vLeJdpluhWRlVoG9NAAtkio0EqEyADucCPoGjLw8DZGzOy1NoTGg9HIVGGZAOQL8AdsAIwADBcBAPQ30BAAFvDGIIjQLMh4nITYVFTUGLGb6IRiIQgHPBaYYoEAAOmqtQsR0Wp0u12gdwez1e70+3y4fwBVCBILBEKh0NmCPiyOOaKut3u+J+ROoHEmj0YwEe0EYMDwj2QwgADhQCO8do8wI5GNQtEA)

### 💻 Code

```ts
class Model<T extends Record<string, any>, K extends keyof T = keyof T> {
    constructor(key: K, value: T[K]) {
        
    }

    baz<S extends K>(key: S, value: T[S]) {
       
    }

    bazbar(key: K, value: T[K]) {
       
    }

}


const model = new Model<{foo:string,bar:number}>('foo',100) // should get an error but didn't
model.bazbar('foo',100) // should get an error but didn't

model.baz('foo',100) // get an error, which is the expected behavior

```

**Comment by MartinJohns** [comment]
Working as intended. `K` is typed `keyof T`, so `T[K]` is `T[keyof T]`, meaning a union of all property types.

**Comment by yaquawa** [comment]
Hi @MartinJohns , thanks for replaying!!
But can you explain me why `model.baz('foo',100)` works as expected but the `constructor` and `bazbar` will not?

**Comment by MartinJohns** [comment]
Because in the case of `baz` your type argument `S` is inferred to be `"foo"`, so the second argument is of the type `T["foo"]`, which in your example is `string`.

You end up with the same issue when providing a type argument:

    model.baz<"foo" | "bar">("foo", 100);

**Comment by yaquawa** [comment]
@MartinJohns @RyanCavanaugh 
I understand that if manually provide type arguments, type parameter won't be inferred.

But I didn't pass a type argument for the `K` type parameter, only for the `T`.
Does this mean if any of the type parameters was passed, the typescript won't infer the type?

**Comment by MartinJohns** [comment]
> Does this mean if any of the type parameters was passed, the typescript won't infer the all the types?

Partial type inference is not supported. There's an open issue about it, look at the roadmap. Since you didn't provide the type argument, and it isn't inferred, the default type **you** specified is being used.

**Comment by yaquawa** [comment]
@MartinJohns Got it, thanks for your detailed explanation!
