### ISSUE TITLE
Installing from Visual Studio 2015 breaks... a lot!

### ISSUE THREAD

**Issue by Chaotic-Limited** [Microsoft/TypeScript#4317]
Hello!  (Visual Studio 2015 Enterprise) All I did was go to Tools => Extensions and Updates and update TypeScript from version 1.5.3.0 to 1.5.4.0.  That was the only update I did.  When I then restart Visual Studio and open my solution, I am presented with a number of errors:
The JavaScriptWebExtensionsPackage package did not load correctly.
Upon loading (at least one, but not all) a web forms page, I am presented with this error:
The Visual Studio language support for Style has not been installed.  Code-editing Intellisense will not be available..."
Then - and this is a bit weird - I have a section of the page I want to move elsewhere - cut and paste.  As soon as I cut I get this:
Error HRESULT E_FAIL has been returned from a call to a COM component.
The code I was cutting is removed, however it was not put into the clipboard - to recover it I have to not save the file.  To make this more interesting, I have tried cutting and pasting each component of that code and each individual one works fine, but not all of them together.  Here is what I'm cutting:
<article class="login-form major-item">
	<header>
		<h3>Login</h3>
	</header>
	<fieldset class="body">
		<ul>
			<li>
				<label><asp:Literal runat="server" Text="<%$ Resources:label_email %>"></asp:Literal></label>
				<input type="email" id="txt_Email" runat="server" autocomplete="on" data-myvalgrp="login" required autofocus />
			</li>
			<li>
				<label><asp:Literal runat="server" Text="<%$ Resources:label_password %>"></asp:Literal></label>
				<input type="password" id="txt_Password" runat="server" data-myvalgrp="login" required />
			</li>
			<li>
				<label><asp:Literal runat="server" Text="<%$ Resources:label_rememberme %>"></asp:Literal></label>
				<input type="checkbox" id="check_RememberMe" runat="server" checked="checked" />
			</li>
		</ul>
	</fieldset>
	<div>
		<h2>Temp Bobblejob Button</h2>
		<button onclick="bbljLoginClick(); return false;">Login with Bobblejob API</button>
	</div>
	<asp:UpdatePanel ID="ajax_BbljLogin" runat="server" UpdateMode="Conditional" ChildrenAsTriggers="true">
		<ContentTemplate>
			<asp:Button ID="btn_BbljDone" runat="server" Text="" OnClick="btn_BbljDone_Click" Style="display: none;" />
		</ContentTemplate>
	</asp:UpdatePanel>
	<footer>
		<p class="actionReport" id="loginReport"></p>
	</footer>
</article>

The error appears to be on pasting as I can successfully copy.

In the event viewer, I can see 8 errors all at once, though this doesn't happen every time I try this, but they seem likely related.  The first of which is this:
Windows cannot open the 64-bit extensible counter DLL ASP.NET_64_2.0.50727 in a 32-bit environment. Contact the file vendor to obtain a 32-bit version. Alternatively if you are running a 64-bit native environment, you can open the 64-bit extensible counter DLL by using the 64-bit version of Performance Monitor. To use this tool, open the Windows folder, open the System32 folder, and then start Perfmon.exe.

This might seem a lot and some of it rather obscure - I was running my project perfectly fine, working away, and then remembered to take a look at Typescript (I've not used it before) and installed the update.  Then everything fell to pieces.  I've tried repairing Visual Studio and the problem persists.  I've tried uninstalling the ASP.net windows components and reinstalling them and this still doesn't resolve the issue.

Please please please can you quickly show me how to remove the typescript update or roll back to the previous version.  Otherwise, to put it politely, I'm really quite scr*w*d and unable to work even half as productively as I need to.

Thank you.

**Comment by Chaotic-Limited** [comment]
The content I'm cutting is HTML, which isn't encoded by GitHub it seems - you'd need to view source to get what I mean - apologies for the poor formatting.

**Comment by SaschaNaz** [comment]
You can use this to present HTML code:

    ```html
    <html-code>
        Your codes
    </html-code>
    ```

**Comment by mhegazy** [comment]
This is not caused by updating TypeScript update. this is causes by updating "Tools for Universal Windows Apps Development"

Please follow the steps in https://github.com/Microsoft/TypeScript/issues/4238#issuecomment-129060370 to restore your JavaScript support.

**Comment by Chaotic-Limited** [comment]
@SaschaNaz I added the tag you suggested there but it doesn't appear to have worked.  :-/
@mhegazy Thanks for the response!  I ended up uninstalling VS and reinstalling it again.  There is clearly a clash of some kind - but fair enough if the bug is on the universal apps side.  Regardless the issue is resolved.  Thanks!
