### ISSUE TITLE
TS 4.1+ Key remapping in mapped types allows bypassing statically known members check

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#43189]
# Bug Report

### 🔎 Search Terms

key remapping static member, arbitrary interface keys, bypassing interface dynamic member check

### 🕗 Version & Regression Information

With the key remapping introduced in TS 4.1 for mapped types, the following error can be bypassed:

> An interface can only extend an object type or intersection of object types with statically known members. (2312)

I was unable to test this on prior versions because key remapping didn't exist. 

### ⏯ Playground Link

- [Playground](https://www.typescriptlang.org/play?#code/PTAEAEBcGcFoFMAeAHeBjSCBOWD2XRZZRIALAS2lEoDsBySUAQwBsXcB3eAEwChyakeFgBmTNPFAAldPm4BJQcLESAPAGlQSITW5UA1vACeuEcxpGANKABqAPi2Ide6bKzcN1+6ADeoAL68vJBGqK4AtkzIMmhyGo7OBsam5la2DgC8vqAA2gD61DSgNPAAbsLMVOoAugBctgFBIBAwCCjomMJ4BESgAEYAroxklNTQAIT8SqLikjFyikIzapra8LpJJmZMFl4OaxsRUfPununZgUA)

### 💻 Code

```ts repro
// @ts-expect-error -- this isn't allowed
interface RecordInterface<K extends keyof any, V> extends Record<K, V> { }

type RemapRecord<K extends keyof any, V> = { [_ in never as K]: V }

// @ts-expect-error -- but this is!
interface RecordInterface<K extends keyof any, V> extends RemapRecord<K, V> { }
```

### 🙁 Actual behavior

TypeScript inconsistently prevents using interfaces with dynamic members.

### 🙂 Expected behavior

Either `RecordInterface` to have an error, or to be able to replace `Record1` with `Record` without any error.

CC: @tjjfvi, who discovered this, but hasn't submitted a bug.

There is a feature request (#41383) about changing the definition of `Pick` which includes a comment about this.

**Comment by tjjfvi** [comment]
Seems like a feature to me 🤷

**Comment by MartinJohns** [comment]
I'm confused what `in never` is even supposed to be.

When hovering over `RemapRecord<>` the tooltip shows that it maps to `{}`, so it's an empty interface and a result assignable to **any other type**.

When mapping it to another type and providing type arguments, e.g. `type Foo = RemapRecord<...>`, then the type `Foo` has properties.

**Comment by tjjfvi** [comment]
It has to be `[_ in "" as K]` to work.

**Comment by RyanCavanaugh** [comment]
Please don't take a production dependency on this; I have no idea what might be hiddenly broken when that type starts getting used.

**Comment by crowlKats** [comment]
it would be great if this was an actual feature. "dynamically" adding typings would be great in some scenarios

**Comment by tjjfvi** [comment]
> Please don't take a production dependency on this; I have no idea what might be hiddenly broken when that type starts getting used.

👍 ; thinking back now, I remember having some really cryptic bugs that were fixed when I stopped using this behavior
