### ISSUE TITLE
Property 'resourceUsage' does not exist on type 'Process'

### ISSUE THREAD

**Issue by zMrKrabz** [microsoft/TypeScript#43195]
# Bug Report

Get `Property 'resourceUsage' does not exist on type 'Process'.` when running `process.resourceUsage()`.
Also get property does not exist when doing `process.memoryUsage.rss();`.

### 🔎 Search Terms

memoryUsage, rss 

### 🕗 Version & Regression Information

node version: 15.11.0
typescript version: 4.2.3

Please keep and fill in the line that best applies:
- This is a crash

### 💻 Code

`console.log(process.resourceUsage())`

### 🙂 Expected behavior

Documented (here)[https://nodejs.org/api/process.html#process_process_resourceusage] , in the nodejs docs

**Comment by IllusionMH** [comment]
Typing for Node.js come from `@types/node` and not from TS itself.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1e7c3528f8f66824c99c82be040418f66a17c49d/types/node/process.d.ts#L300
What version do you have installed?

**Comment by zMrKrabz** [comment]
my package.json says my @types/node version is `14.14.33`

**Comment by zMrKrabz** [comment]
Looks like installing latest fixed
