### ISSUE TITLE
Type deduction bug with generics

### ISSUE THREAD

**Issue by radioegor146** [microsoft/TypeScript#43190]
# Bug Report

### 🔎 Search Terms

type deduction
generics

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics and types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoQI4FcIGczIDeAsAFDIXJRwgAmA9gLYDKYWMMAXMvlKAOYBuMgF8yZMAE8ADigASNWgBtoAHgAqAPmQBeZAAow3dQEpd2gG71gtYaTKhIsRCgAKcKLgi0AInDBwRGSUyLT+cNy8AgDaALp2YvakMFggCGDA9CDI0h5eGsgQAB6QdLjI7p7efgHIAGTIAKIANE2FJRBlaJg4+Jr6uVW0CnQqUNwjympaJhOKY6qN2iTklFAQbFDZ+mY6yyIJ4qSO0PBIFXnV4QBMQasUkPiRYHwgQqJHKWkZWTmX1wViqVaOVKl5fDd6k1Wo12sDyuhsHgwP1BuDJmM5qNpppZsgMWolncQutNttdvtDkk0RBrgNLvp9BELkManBbg0wVdag1Eb0wBTkAgsrh6CoAHSgGD0Jnix4CkwmOxkGl0mmM5lciEBDndJH4QXCkCiiVSmVwOXIxVKoA)

### 💻 Code

```ts
interface Request {
    randomStuff: string;
}

type Handler<T> = (t: T) => void;

interface ParsedData {
    data: string[];
}

function parse<T extends ParsedData & E, E extends Request>(parsedHandler: Handler<T>): Handler<E> {
    return () => {};
}

interface ParsedData2 {
    test: string;
}

function parse2<T extends ParsedData2 & E, E extends Request>(parsedHandler: Handler<T>): Handler<E> {
    return () => {};
}

parse2(parse((a: ParsedData2 & ParsedData & Request) => console.info(a.test)));
parse2(parse((a: ParsedData2 & Request) => console.info(a.test)));
```

### 🙁 Actual behavior

Two last lines of code do the exact same thing, but the second is with error.

### 🙂 Expected behavior

No error, as well as with such example:
```ts
parse2(parse((a: ParsedData2) => console.info(a.test)));
```

**Comment by RyanCavanaugh** [comment]
I don't see any bug here. You set a constraint `extends ParsedData` on `T`, but the candidate for `T` provided in the second call doesn't match that.
