### ISSUE TITLE
JSDoc doesn't actually handle dictionary declaration like it says it should

### ISSUE THREAD

**Issue by nathanblair** [microsoft/TypeScript#43208]
# Bug Report

### 🔎 Search Terms

JSDoc, dictionary, not working, Object, generic keys, generic values

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSDoc Object syntax

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PQKhCgAIUhBSC2BDADgWgDYEsDWBTSAewCMArPAYwBdIqALJG5FAZ0iQCdisqPOBPSAAMWvLADsA5kMgoOhFHg5UseNlULDxAVwTElIgHRQI0SAAEq-RZADeAeTKUqhgDyiOEyQBpIOvUoAfAC+JsDgAG6ckB5eACqEAHK6+hwA3ODgoDCW1gQOTtRu-qm+JOTUIdDhURzsHHz8ADK4eGlAA

### 💻 Code

```ts
/**
 * A map-like object that maps arbitrary `string` properties to `number`s.
 *
 * @type {Object.<string, number>}
 */
var stringToNumber;
```

### 🙁 Actual behavior

Any provided hover information, both in playground, and in vscode, and I assume the wider typescript/javascript language service, just recognizes this type as `any`. Therefore there is no correct intellisense for either the property or the value, or since it registers as `any`, it doesn't even recognize there are keys and values.

### 🙂 Expected behavior

The language server should understand what is meant by `{Object.<String, String[]}` (i.e. its exactly the same data structure as a `Map` without having to call it a `Map`) or related JSDoc syntax and provide the proper intellisense for the data structure.

**Comment by IllusionMH** [comment]
Types from JSDoc are ignored in TS files - you should use regular type annotations instead.
To see the errors related to JSDoc нou need to check it in JS file or enable JavaScript language in playground to see results:

https://www.typescriptlang.org/play?useJavaScript=true#code/PQKhCgAIUhBSC2BDADgWgDYEsDWBTSAewCMArPAYwBdIqALJG5FAZ0iQCdisqPOBPSAAMWvLADsA5kMgoOhFHg5UseNlULDxAVwTElIgHRQI0SAAEq-RZADeAeTKUqhgDyiOEyQBpIOvUoAfAC+JsDgAG6ckB5eACqEAHK6+hwA3OCZsVIJyQEchkiQALyQAOQAjgDueGUZ2ZK5KUqGxCWQAIwZ4KAwltYEDk7Ubv6pviTk1CHQ4VEc7Bx8-AAyuHjd4JzLa-gA2gAMALrtAGZIGCwbW0tIq+t7HSeltsFpQA

**Comment by nathanblair** [comment]
This actually wasn't a `ts` file I was working in when I encountered this issue. Its a `.js` file opened in VS Code with the default Typescript/Javascript Language Server enabled so Typescript type annotations won't be available.

**Comment by nathanblair** [comment]
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

The documentation here states:

> You can specify map-like and array-like objects using string and number index signatures, using either standard JSDoc syntax or TypeScript syntax.

It then directly links to the playground link I listed above. So the documentation is pointing to a behavior it says exists but doesn't, or rather, doesn't exist without whatever alterations @IllusionMH made to the playground link.

**Comment by nathanblair** [comment]
It looks like the primary difference between the OG link and the suggested playground link is that the suggested link has `allowJs` and `checkJs` enabled.

I'm wondering how this plays into the VS Code TS/JS Language Server then because I have the `js/ts.implicitProjectConfig.checkJs` set to `true` in my User settings, and I get type information for every other type I declare using JSDoc except this kind.

**Comment by IllusionMH** [comment]
In playground you've linked I've just switched language mode and added 4 lines of code to demonstrate expected behavior.

In editor I don't see behavior you are describing: `Object.<string, number>` correctly maps to `{[key: string]: number}`

Screenshot from clean installation of VS Code 1.54.2 with built in TS Version: 4.2.3
![image](https://user-images.githubusercontent.com/1312662/111039513-1ed0cc00-8437-11eb-832b-21d76b1f43c8.png)

![image](https://user-images.githubusercontent.com/1312662/111039296-ec729f00-8435-11eb-8b37-85747398bac7.png)

**Comment by nathanblair** [comment]
I see! Thanks for providing that. Can you elaborate more on what you mean by "switching the language mode"?

I'm not sure what this could be boiling down to. I wiped out my settings.json and even keyboard settings. Copied your code. Only a handful of extensions running. This is what I see:

![image](https://user-images.githubusercontent.com/16280023/111055056-1b8e0e00-8440-11eb-9a60-21321945e172.png)

**Comment by nathanblair** [comment]
I also think the playground sample linked in the documentation should be fixed; maybe that should be opened as another issue? As it links directly to a playground showcasing this problem front and center.

**Comment by nathanblair** [comment]
Is there a global configuration file that may be affecting these different behaviors? Like a jsconfig.json stored in a home directory? I'm quite sure I don't have anything of the sort but I could very well be forgetting something or not be aware there's some magic file outside the purview of vs code that the language server is taking into consideration?

**Comment by IllusionMH** [comment]
In your screenshot you have `Object.<String, Number>` instead of `Object.<string, number>` as in Handbook (both `string` and `number` are lower case). Uppercase types (that are types of corresponding global objects) lead to `any` type.

As for link to playground that doesn't include language mode flag - please report it in https://github.com/microsoft/TypeScript-Website repo where playground is stored.

**Comment by nathanblair** [comment]
Oh my god. You're 1000% correct. I knew it had to be something easy I was missing as I'm sure I would have found other people with the same problem before now.

Thanks so much for all the support; I'm glad this didn't go any deeper than my boneheaded capitalization issues!
