### ISSUE TITLE
Reserved type primitive names should not be allowed as interface names

### ISSUE THREAD

**Issue by polkovnikov-ph** [microsoft/TypeScript#43215]
# Bug Report

### 🔎 Search Terms

`interface never`

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Classes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210312#code/JYOwLgpgTgZghgYwgAhBAbtZBvAUMg1DaALmTCgFcIBuXAX1wBMIEAbOKFBAexAGcwyAB5k0mKHWEA6cVgD085AAUoPAA7QwAT2QByOVD3ImPCP1Q8hEYcEHI+5bZv2G90gBQAmAMw+AnACUQA)

### 💻 Code

```ts
interface never {
    never: true;
}
declare const x: never;
x.never
```

### 🙁 Actual behavior

`Property 'never' does not exist on type 'never'.(2339)`
Why can't I use a property I defined?

### 🙂 Expected behavior

Property `never` should exist on type `never`, despite their names.

**Comment by RyanCavanaugh** [comment]
`interface never {` should be a syntax error
