### ISSUE TITLE
Static constructor

### ISSUE THREAD

**Issue by MahefaAbel** [microsoft/TypeScript#43216]
# Suggestion

It is practice to have a Static Constructor with typescript

## 🔍 Search Terms

- static constructor
- private static constructor

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

This suggestion has already be made in the past, the community had proposed to use `MyClass.initialise()` approach but 
the suggested static constructor syntax has best of everything : 

- Does not pollute the class structure (even better than private)
- Does not need the developer to remember to call it
- Makes sure it is invoked last
- Makes sure a class does not have multiple static constructors
- Provides a convention, and
- It is concise and intuitive

(Or have I missing something?)

**Comment by RyanCavanaugh** [comment]
See https://github.com/tc39/proposal-class-static-block

**Comment by HolgerJeromin** [comment]
Should this issue now be closed?
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#static-blocks-in-classes
