### ISSUE TITLE
NodeList and DOMTokenList are iterable

### ISSUE THREAD

**Issue by icecream17** [microsoft/TypeScript#43225]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `["ESNext", "DOM"]`.

## Missing / Incorrect Definition

NodeList and DOMTokenList should have [Symbol.iterator] because they're iterable.

## Sample Code

```ts
// NodeList
for (const gameControl of document.querySelectorAll('#main button')) {}

// DOMTokenList
for (const className of document.body.classList) {}
```

## Documentation Link

https://dom.spec.whatwg.org/#interface-nodelist
https://dom.spec.whatwg.org/#interface-domtokenlist

**Comment by MartinJohns** [comment]
This is already supported when you reference the `DOM.Iterable` lib.
