### ISSUE TITLE
Compiler option rootDir breaks compilation

### ISSUE THREAD

**Issue by ldminoc** [Microsoft/TypeScript#4322]
It's unclear whether the option footnote at https://github.com/Microsoft/TypeScript/wiki/Compiler-Options means that it is only available to version 1.5, or 1.5 and higher.

The option is not in the schema shown at http://json.schemastore.org/tsconfig; however, 
Visual Studio Code 0.7.0 seems to think its type is Boolean. Furthermore, including the option causes VSC to fail or not perform compilation/transpilation.

**Comment by mhegazy** [comment]
i have sent a PR for the schemastore to add `rootDir` (https://github.com/SchemaStore/schemastore/pull/37). 

The flag is supported in 1.5. for VSC, @jrieken and @dbaeumer any ideas why this is failing?

**Comment by ldminoc** [comment]
Thanks for the rapid response.
