### ISSUE TITLE
Interface implement with read only properties.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/TypeScript#43224]
# Bug Report

**Error in example 2 only, Example 1 should error when change read only property like example 2.**

Typescript version: **4.2.3**

![image](https://user-images.githubusercontent.com/17777237/111011087-06ae6d80-83a1-11eb-9073-c69477185773.png)

**Another example**

![image](https://user-images.githubusercontent.com/17777237/111011539-7113dd80-83a2-11eb-9ad4-cb80376de8f9.png)

**Comment by jcalz** [comment]
This is maybe a duplicate of #13347, but there's a whole bug report template you're supposed to fill out.  It starts with 

> \

and asks for various things, none of which are images of code.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. `implements` does not change the shape of the class; even if it did, it wouldn't be desirable to change it in this way since there'd be no way to say that you didn't want the property to be readonly.
