### ISSUE TITLE
Computed property names in generated intersection types cannot be named

### ISSUE THREAD

**Issue by coalpha** [microsoft/TypeScript#43238]
TypeScript fails to generate declaration files if a computed property name is used in an intersection type. I'm having trouble even figuring out what's going wrong myself. Hopefully the relevant code is at least marginally useful.

### Search Terms

has or is using name from external module newtype newtypes unique symbol computed property name declaration d.ts intersection

### Version & Regression Information

Still an issue on nightly as of 2021.03.14

### Code

Unfortunately, since this issue is very peculiar, it requires multiple files so I can't link to a playground.
`declaration` must be set to `true` in one way or another for this issue to occur.
Here's [a repo](https://github.com/coarchive/ts-computed-property-export-issue-2021.02) that also shows the issue. Just clone and `npx tsc`.

```ts
// http_host.ts
declare const unique_symbol: unique symbol;

type http_host_t = {[unique_symbol]: "http_host"};

type http_host = `http${"" | "s"}://${string}` & http_host_t;

type http<host extends string = string> = `http://${host}` & http_host;
const http = <host extends string>(host: host) =>
   `http://${host}` as http<host>;

type https<host extends string = string> = `https://${host}` & http_host;
const https = <host extends string>(host: host) =>
   `https://${host}` as https<host>;

export {http_host, http, https};
```
```ts
import {https} from "./http_host";

export const tsl = https("www.typescriptlang.org");
```

### Actual behavior

> Exported variable 'tsl' has or is using name 'unique_symbol' from external module "./src/http_host" but cannot be named.ts(4023)

### Expected behavior

This file is generated:

```ts
// main.d.ts
declare const tsl = import("./http_host").https<"www.typescriptlang.org">;
```

**Comment by coalpha** [comment]
I forgot to note that changing
```ts
type http<host extends string = string> = `http://${host}` & http_host;
```
to
```ts
type http<host extends string = string> = `http://${host}` & http_host_t;
```
is a stopgap solution and fixes the problem well enough for now. The issue only shows itself when there are two layers of intersection to the object type with the computed property name, it seems.

Also, if the computed property name's type is changed from `unique symbol` to something like `1`, the issue goes away. This is an *incredibly* niche issue so sorry somewhat for piling onto the growing list of things to fix.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. The declaration emitter won't emit `import(...` types on its own since this tends to be nonportable in the long-run. You can write the import type as a type annotation in the second file if that's what you want to appear.

**Comment by coalpha** [comment]
Ah. Well, it wasn't so much that I wanted that exact `main.d.ts` file to be generated. Rather that I was unable to get any `main.d.ts` file to generate because of the whole "cannot be named" issue. The expected behavior was just an example of what could happen, I suppose. Even doing this:

```ts
export const tsl = https("www.typescriptlang.org") as import("./http_host").https<"www.typescriptlang.org">;
```
seems to give me the exact same error as before:

> Exported variable 'tsl' has or is using name 'unique_symbol' from external module "./src/http_host" but cannot be named.ts(4023)

I don't have a particular preference on what `.d.ts` files TypeScript generates for me as long as it generates at least something. In this case, trying to generate any declaration for this code fails.

**Comment by RyanCavanaugh** [comment]
A type assertion is different from a type annotation (sorry, technobabble here 😅) This should work:
```ts
export const tsl: import("./http_host").https<"www.typescriptlang.org"> = https("www.typescriptlang.org");
```
If it doesn't, that's a bug

**Comment by coalpha** [comment]
Ah wonderful! Thank you for the help. It seems mildly unfortunate that `"www.typescriptlang.org"` would have to be duplicated within the type itself. Since this is not a bug, I suppose I will close the issue.
