### ISSUE TITLE
JSON.Parse is incorrectly typed

### ISSUE THREAD

**Issue by shooda** [microsoft/TypeScript#43232]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition
The first argument of [JSON.parse](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L1059) should be typed as `string | null` as opposed to just `string`

(Ideally, a generic as the return type would be pretty cool 😄)

## Sample Code
```
console.assert(JSON.parse(null) === null)
```
The above code complains about the types being incorrect, but works perfectly fine in Chrome / Firefox.

## Documentation Link
The docs on MDN ([here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)) don't explicitly state this, but they do show an example of `JSON.parse('null')` and the polyfill implementation does safely convert the first argument to String (`text = String(text)`). This makes it seem like `JSON.parse(null)` and `JSON.parse('null')` would be equivalent.

Note: I am happy to submit a patch myself if we would like to update the definition!

**Comment by MartinJohns** [comment]
#29807. Used search terms: `json.parse null in:title`.

**Comment by jcalz** [comment]
I’m sure this will be declined. 

`JSON.parse()` may not throw an error at runtime when passed a non-`string` argument, but that does not mean TypeScript should support it.  The real question is whether it is idiomatic to do so, as opposed to being indicative of a coding error.  The documentation in MDN for that argument says “the string to parse as JSON.”  So I would be a little suspicious if I see something other than a `string` passed in as an argument, at least in the absence of evidence that such code is widely used.

You might be interested in [“What does ‘all legal JavaScript is legal TypeScript” mean?”](https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean) which discusses why TypeScript is often less permissive than JavaScript.

**Comment by shooda** [comment]
Thanks for the article! It makes a lot of sense. However, I still have a bit of trouble reconciling this with how far TypeScript should go to behave consistently in this regard.

In this scenario, `JSON.parse(null)` is valid and so is `JSON.parse('null')` While both look very similar (in fact the same if you are quickly glancing through a changeset), TypeScript is permissive with only one of them. This could potentially lead to a bad pattern where, in TypeScript, you do `JSON.parse(value ?? 'null')` (assuming `value` is `string | undefined`) and then we're back to the problem we were initially trying to resolve by not including the `null`.

**Comment by shooda** [comment]
> #29807. Used search terms: `json.parse null in:title`.

My apologies! It seems I was a bit too quick in creating the issue. But I still have questions around this that I'd like to resolve if that's okay 🙂

**Comment by MartinJohns** [comment]
@shooda JSON is represented as a `string`. The string `"null"` is a valid JSON string that represents the value `null`. The value `null` is no valid JSON string, because it's not a `string` at all. Even if the implementations (and the spec) accept the `null` value, the TypeScript team chose to not support this type, because it most likely is a mistake to pass the value `null` to a function that's supposed to parse a JSON value from a **string**.

For example the user tries to retrieve a JSON string from somewhere and has `null` as a fallback. Do you think it would be more likely that the user wants `null` as a result? Or that the user actually just forgot to check if he has a valid JSON string?
