### ISSUE TITLE
tsc generate an invalid output for js files that contains private fields when use --allowJs

### ISSUE THREAD

**Issue by ibado** [microsoft/TypeScript#43234]
# Bug Report

### 🔎 Search Terms

private js

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/PTAEBcAsEsGdTqAhqAdAK3gM2gGwKYBQIEsAxqALSVK64D2A7gFLyUB8CAdgG63QATUPQCu4AA5jCZXEljwAYvXoAhJACdQAb0KFQ+0AGIsygBQBKbXoM2y9LrHoFUDAOamARCfofz1-QC+-vrBAEYaFlY2tvaOzm6e4eq+wTZQcKjGZuYA3MFBAUA)

### 💻 Code

```
foobar.js
=====================================
class FooBar {

    #foo() {
        console.log("foo")
    }
     
    bar() {
        console.log("bar")
        this.#foo();
    }
}
=====================================
$ tsc --allowJs -> invalid output
```

### 🙁 Actual behavior

Produces an invalid output
### 🙂 Expected behavior

Produce a valid output

**Comment by orta** [comment]
The canonical issue for this is https://github.com/microsoft/TypeScript/issues/42574 with a draft PR here https://github.com/bloomberg/TypeScript/pull/52
