### ISSUE TITLE
outDir compiler option description or function unclear

### ISSUE THREAD

**Issue by ldminoc** [Microsoft/TypeScript#4323]
The description "Redirect output structure to the directory" seems to imply mimicing of the source structure in the specified directory. 

For example, I take the above description to mean:
if source is "app/app.ts", then output should be <outDir>/app/app.js

Outputs are placed in directory without structure. What is the correct behavior?

**Comment by mhegazy** [comment]
`--outDir` will mimic the input structure. the root of the input files is computed to be the longest common subpath of all input files, if you have one file, that is not going to work obviously.

use `--rootDir` to tell the compiler where is the root of your sources is. so in your case `--rootDir ./` should result in `<outDir>/app/app.js`

**Comment by ldminoc** [comment]
Thanks, your answer describes the behavior I was expecting. (Looks like <outDir>  got left out in my original post).
