### ISSUE TITLE
keyof generic type cannot be used to construct template literal types

### ISSUE THREAD

**Issue by TotallyNotChase** [microsoft/TypeScript#43236]
# Bug Report

A type constructor with a generic argument of type `T extends Record<string, any>` is expected to have `string` types - hence, it should be possible to use `keyof T` to construct template literal types.

However, when mapping over `keyof T`, using `[K in keyof T]` - `${K}` gives an error.
```
Type 'K' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
  Type 'keyof T' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
    Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
      Type 'symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
        Type 'keyof T' is not assignable to type 'bigint'.
          Type 'K' is not assignable to type 'bigint'.
            Type 'keyof T' is not assignable to type 'bigint'.
              Type 'string | number | symbol' is not assignable to type 'bigint'.
                Type 'string' is not assignable to type 'bigint'.ts(2322)
```

### 🔎 Search Terms

template literal types, keyof, generic argument, generics, mapped types

### 🕗 Version & Regression Information

4.2.3 and next

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQghgJwDwBUoQB7AgOwCYDOUAShAMYD2CeSBwCAljgOYA0UcOIAfN1ALxQA3gFgAUFElQA2gGkoTKAGsIICgDMoKALoAuKAAMAJENkBfA+KlQA9DesPHkgHroECKlAAWEBBHFmANzi4nZaPlDqFAA20RQA7kzMUPFUSkRwRJiQZNh4UAC0UDgUUMy4vgxkRACuBBB44qCQUAAiNQC2HSACwlZSDHj6OJ0ARr7BElLADMDREPp0jCyTQSFizdAAYhSlgqJTknIKOMqqGm2d3XqGJuaWYmbrQA)

### 💻 Code

```ts
type Bar<T extends Record<string, any>> = {
    [K in keyof T]: `${K}`
    // ^ error here
};

type Dummy = {
    id: number;
    title: string;
};

type Foo = {
    [K in keyof Dummy]: `${K}`
    // ^ works fine
}
```

### 🙁 Actual behavior

`keyof T`, where T is a generic type extending `Record<string, any>`, is not able to be used to construct a template literal type

### 🙂 Expected behavior

`keyof T`, where T is a generic type extending `Record<string, any>`, should be able to be used to construct a template literal type since `keyof T` is a string.

**Comment by TotallyNotChase** [comment]
On further though - I am assuming this is happening because a generic type that extends `Record<string, any>` is still allowed to have properties of types other than `string`. Since `Record<symbol, any> extends Record<string, any>` returns true.

**Comment by RyanCavanaugh** [comment]
You can't prevent excess properties, but you can filter the mapped type to the string-typed properties. This works without error:
```ts
type Bar<T extends Record<string, any>> = {
    [K in string & keyof T]: `${K}`
};
```

**Comment by TotallyNotChase** [comment]
Alright, closing since this is the expected behavior.
