### ISSUE TITLE
Unexpected runtime difference when using Brackets or not with `ts-node`

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#43230]
# Bug Report

### 🔎 Search Terms

Brackets

### 🕗 Version & Regression Information

- [x] This is a crash
- [ ] This changed between versions ______ and _______
- [ ] This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- [ ] I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhCgAIUgjBDAzgUwCaQPYDtIAEA2AllgNaQAWALpQA6IBcwwA5oZeQK6wB0AxhgFtgiAG7J8lZACtEwZIiJZKAWhr4OrLMtHjJAZmCx8GWMAFJJAJ2GXewGpYy95iDJYD6GGpULZE3GSgQYHBwQgEaN0pISgBPGmRIAG9IABliKwAaSABlDA5bZABhDFREgF9IADNHAUgAcnlFSnrQ5AAPSMtojORLKvhnSAAFR2dEV0sAeW9fLERkqEhmkrKAIWNeEgY4DAx8ZHgscHK2zqjIfnnohycXNxmfP0gAXmTKpBGx++nZv1CmNViOh0ko+pBiIhKEdnOArlDlr1LMN4OxXpAprApMheJRuCRkLFEAAKSzIACOHEIZL4g3IyAAlNwqsDiTRUeRXgA+JbAYkAbWAAB0hQBdBlNDJCgCMRFgxIA-PQZc0+gykgAmcpCgKIAAkwG4kihbI5DMy4AZAJghChR1gHHwEOYWDciUIVWgIQ9kGJAEJVcizYtIDFyI4AO6QLDIKMAUUsjksxPqJUd6Fd0RZWHQcZyoOiBfBxEgZMp1MSvDpyHqVtO4A6XR6YP6g0SRcsJSwLOYkA6khzCw73C7PZDffalEsg0oo8IzAVxJZByw8AEyCVkChlmIzAZ9DSSJH2B7JwBwD7CgyylQtvgRmQyhjk+UikSuDiCUQvB33mUkqUYB4VtAcVE-R9wibRBsg-eJ5B-Qg-wAyhgFdZQyypMllEgqJoLwcDv1-FRkNQjBlBEeBLHQilMPkOE-GiPMO3RUkaIrYlAxRdgGUgT5wIwT0cO6FNkNrJkO3PSB2UoXhOQ7ABiMQdyqWJwEBZCbzvB8n37V9iHfAiEKQq9AI4LBYHyHNlHXdhSno65kkgJSPViSBKjeJij1uSgMHA0JPJbbhvN8uDuGclT0SqMzcTmX0ln4MoDzyApnFWRIAB8tynXcLVDK4ewPDs52YXLMD+eZN23XdIEy4cC0eOZoMtcdASqZAZM5FBqF3RB4oYrd2p8LBmAWF4llDYl8vnSAADIZvG0NfX4z0puYbh+2nXFiteF43nqKKsBi7BWkW07IAVS4T3ndbJ022cruYYkFrOxbQAhO1zMdZ1XTJaN+y9Z6XpiOCBLKp55h2vazLKbM0HqGrMuWsHGshhoquG+GLq8cGFgPbHGuZQgVzXZBSqByArXJg9VsBpkuqGkaePS9KFqSetQ1ucZJgavxuBWUpkA2JxtnRemev5eoBFQdogIF5QjGFxB6lFVGpw4ZBQlDQEq3wJ03HnYh4CdBTwtU0MyUoAocFN2ldeJdhbWyBLScu7t52yfHnk+OqMh5+Y63AIA)

### 💻 Code

```ts
const ESLinter = (require(linterPath) as typeof import('eslint')).Linter

// vs

const ESLinter = require(linterPath) as typeof import('eslint').Linter
```

### 🙁 Actual behavior

The first one with Brackets works well, but when running with the second one there is an error:

```log
TypeError: Cannot read property 'verify' of undefined
```

### 🙂 Expected behavior

They should work the same.

Reproduction:

https://github.com/mdx-js/eslint-mdx/tree/feat/eslint-plugin-markdown

run `yarn eslint --no-ignore test/fixtures/code-blocks.md`

**Comment by Zzzen** [comment]
This is working as intended. The second one is compiled to `const ESLinter = require(linterPath)`

**Comment by JounQin** [comment]
Hah, thanks for your point, I just forgot about that.😂
