### ISSUE TITLE
Array objects error out when setting a property

### ISSUE THREAD

**Issue by tiagovtristao** [microsoft/TypeScript#43233]
# Bug Report

Array objects error out when setting a property.

### 🔎 Search Terms

"array object"

### 🕗 Version & Regression Information

I've tested it in both v3 and v4.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/DYUwLgBAZg9jEF4IG0C6BuAUJ2MB0AtgJ4AKATjAA6IQCM6QA

### 💻 Code

```ts
let foo = [];

foo.myProp = 1;
```

### 🙁 Actual behavior

"Property 'myProp' does not exist on type 'any[]'."

### 🙂 Expected behavior

It shouldn't error out.

**Comment by MartinJohns** [comment]
You probably need to expand on that. Why do you think it shouldn't error, when the type definition declares no such property?

**Comment by tiagovtristao** [comment]
I can't easily get that to work without creating some elaborate TypeScript types to make it valid. I feel that shouldn't be the case.

The following is similar for function objects as it works fine:

``ts
function foobar() {}

foobar.myProp = 1;
``

**Comment by jcalz** [comment]
This is intentional behavior and not a bug in TypeScript.  Perhaps you want a feature request to treat all objects (or maybe just arrays for some reason) as expando objects, the way function statements are currently.  But I’d suspect such a request would be declined, possibly with a pointer to https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean .

**Comment by MartinJohns** [comment]
> I can't easily get that to work without creating some elaborate TypeScript types to make it valid.

Not really **that** elaborate:

    type Foo = Array<string> & { myProp?: number };
    let foo: Foo = [];
    foo.myProp = 1;

**Comment by tiagovtristao** [comment]
> > I can't easily get that to work without creating some elaborate TypeScript types to make it valid.
> 
> Not really **that** elaborate:
> 
> ```
> type Foo = Array<string> & { myProp?: number };
> let foo: Foo = [];
> foo.myProp = 1;
> ```

That works if you want the properties to be optional.

**Comment by tiagovtristao** [comment]
@RyanCavanaugh, do you know if there's any chance of this being implemented, if I raise a feature request?

I came across this issue when issue https://styled-system.com/responsive-styles#using-objects.

**Comment by RyanCavanaugh** [comment]
Unlikely. This would be a rather huge inference revamp for an initialization style that doesn't see much use.

**Comment by tiagovtristao** [comment]
Fair enough, thanks.
