### ISSUE TITLE
This condition will always return 'false' since the types have no overlap.

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/TypeScript#43235]
Hi, I post a "duplicate" of #25642 which does "work as intended". Sorry, I'm not trying to spam you, but i simply disagree. Here is a simplified version of the error i'm getting:

`
const UPDATABLE_OPTION_FLAG : "FLAG1" | "FLAG2" | "FLAG3" = "FLAG2"; // I change this whenever i want

switch (UPDATABLE_OPTION_FLAG) {
    case "FLAG1":
        console.log("Do job 1.");
        break;
    case "FLAG2":
        console.log("Do job 2.");
        break;
    case "FLAG3":
        console.log("Do job 3.");
        break;
}

if (UPDATABLE_OPTION_FLAG == "FLAG1") {
    console.log("Do job 1.");
} else if (UPDATABLE_OPTION_FLAG == "FLAG2") {
    console.log("Do job 2.");
} else {
    console.log("Do job 3.");
}
`

I get a bunch of errors equivalent to "This condition will always return 'false' since the types have no overlap.". To silence them i need either 1) to move the constant, which is making my code harder to read because sometimes i want the flag switch near the code to switch; 2) to comment out some code, which makes refactoring fail and is error-prone; 3) or to use tricks to make the compiler lose it, which will make me lose it too.
IMHO I didn't make any programming mistake here and the compiler is wrong. 

Regards.

**Comment by MartinJohns** [comment]
This is working as intended, whether you agree or not.

You can/should just use `"FLAG2" as "FLAG1" | "FLAG2" | "FLAG3" `.

**Comment by RyanCavanaugh** [comment]
> Sorry, I'm not trying to spam you, but i simply disagree.

Please consider what this place would look like if everyone who disagreed with any of the thousands of decisions we've made filed a new issue.
