### ISSUE TITLE
Template literal expression is not assignable to matching template literal type

### ISSUE THREAD

**Issue by gavinpc-mindgrub** [microsoft/TypeScript#43243]
# Bug Report

### 🔎 Search Terms

template literal types, template literal assignability

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about template literal types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210314#code/C4TwDgpgBAKhC2YA2BDYEAmUC8UAGAJAN4DOwATgJYB2A5gL5TFlV314DcAUFwMYD21MlABuKJAFcIARgBcUFjVo4oAIhQAjXqu4ChwKOkSp0GObATI0mFYSJjJMxpt54oKElD1luAel+w4NAA5HaKbO5aeMFQlJ7U-AYeJJS01JpI0MD8hkFQocwUSoyFrAzRAHQ83gYOUgBMKupaOnyCwkZWpvXycMbWWLh2dRD1zlHunjXcQA)

### 💻 Code

```ts
type Templated = `${string} ${string}`;

const value1: string = "abc";
const templated1: Templated = `${value1} abc` as const;
// Type '`${string} abc`' is not assignable to type '`${string} ${string}`'.

const value2 = "abc";
const templated2: Templated = `${value2} abc` as const;
```

Note in the second case, where `value2` is a literal string, the assignment works okay.

### 🙁 Actual behavior

```
Type '`${string} abc`' is not assignable to type '`${string} ${string}`'.
```

### 🙂 Expected behavior

I would expect this value to be assignable, since the statically known ~value~ type matches the template pattern.

It is also odd that the two cases above behave differently.

**Comment by RyanCavanaugh** [comment]
We currently don't have any assignability rules to allow assigning one arbitrary template type to another (which is what's being suggested here). It's worth thinking about what rules, if any, would make sense to add.

**Comment by gavinpc-mindgrub** [comment]
Ah, thanks @RyanCavanaugh, that makes sense.

This appears to be a generalization of the inferencing operation.  Inferencing is able to do a kind of matching, but only when all parts are closed.

If so, then this is related to #43060

```typescript
type Foo<T> = T extends `${infer A} ${infer B}`
  ? A extends string
    ? B extends string
      ? true
      : never
    : never
  : never;

type V1 = Foo<`${string} abc`>; // never
type V2 = Foo<`abc def`>; // true
```

**Comment by gavinpc-mindgrub** [comment]
My respect and thanks, @ahejlsberg. ☀️
