### ISSUE TITLE
type guards can not work

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4324]
```typescript
interface A { x : number; }
interface B { y: string; }
type C = A | B;
function isA(value: C): value is A {
    return 'x' in value;
}
var c: C = {x : 1 };
if (isA(c)) {
    c.x = 10; // <-- breakes here
} else {
    c = null; // <-- why is it a crime to assign null to c?
}
```

**Comment by tinganho** [comment]
I think this might be related to that assignments is not allowed on type guards or they will revert back to the original type?

**Comment by RyanCavanaugh** [comment]
Assignments to `c` "turn off" type guards everywhere because we don't yet use control flow analysis to detect that the `else` branch does not affect the consequent branch.

See #2388
