### ISSUE TITLE
Incorrect type infer when using conditions in a generic type

### ISSUE THREAD

**Issue by Humberd** [microsoft/TypeScript#43248]
# Bug Report

### 🔎 Search Terms

* type infer
* generic type conditions

### 🕗 Version & Regression Information

- This is a crash: NO
- This changed between versions: NO
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: Every version don't work
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210315&ssl=1&ssc=1&pln=37&pc=1#code/PQKhCgAIUh1BTSALAhgN0SgdpABgUQA8AXAJxQGNiB7U3SYgTwAdEB3JASwqUgFsUzAM6RqAIwBW8KpDQoANgFd4ImngDC1LGWryAPHKXwAfLigxzkAMrVIYlEO4L5jAFyWA3gDNq1V9eo+eHV5ByEAX0gAXmNIb19-TW1SXT0bIJCw43DPHz9IfCxFPkiYuLzErR19QuLs3IS7X3l4bFLY+Pyk6r0xZtaseuhgcAATaVDSRApQoRFulP0AFWMPKEgNoRRGAAl4eXlqAAoASn8l8HCAbnBwUAhoOERUDEgAJlkUUk5sYhFqLwFEjkKi0IQAGlEWEQxFQxEgnBEbFoAGtOFgAOaQbCjKEwuEIkRYajESwEYGUGikWCo9EY+ioETo+To+C4ihaUacYicLQiHykbGfIxkohkSm0ABCKRR8CwDIcDCQ0053N5WBE8ApVDZDFsKEgQngzC+KGIMJY8HMIyYrCB4tB1NpmL0K2icXWGwA2gBpBE4WWMAGQJYAXXOvtDkC15qwoyJxTE8EFAH5INCMILKslUktI8ZLrdbYgALKMABqCmUYpBVL0AFVYlFIPXoyQ5fH04nk5A0xme9meo2bsX7bWpTK5a6mx6Nt6-ejIIHg2H-GXK0YaxLSK784W7mBLEtlZApkJFPJ4cWREIkNQL7ik0rEFsggA6SA7ahseCZyGw+BGEgLkvC8ZNrTGCYvhVDV4TPC9iBpUg0Uxfwt0dJCUIxPROn8PpdAGcJjBucYZmgyAOVg08VAQ6VqFlLA0O1Kk6IYnCKiaAi2mI25gGAPB4MvTC6TfPJ6ERBhLVEQEFlSfCWmwAtBMQ50MVE3w3y2XZ9kOU47n43BlNYuV1OoBURANRQsHVaTIFk-QvAUI1YgAHzsqpFj0MhlCUmjL2MrBTM07Y9gOY4TnAIA)

### 💻 Code

```ts
/**
 * We have an `Extractor` type which maps object values to `Control<value>`
 * 
 * So basically:
 * {foo: SomeClass} => {foo: Control<SomeClass>}
 * {foo: Enum} => {foo: Control<Enum>}
 * {foo: boolean} => {foo: Control<boolean>}
 */
declare class Control<T>{
    sayHello(): T
};

/**
 * We have 2 variants of Extractors, one that is working and one that is not
 * `ExtractorWorking` has inlined conditions for a value
 * `ExtractorBroken` has the conditions extracted to a separate type
 */
type ExtractorWorking<T> = {
    [K in keyof T]: T[K] extends number ? never : Control<T[K]>
}

type MyValueExtractor<U> = U extends number ? never : Control<U>;
type ExtractorBroken<T> = {
    [K in keyof T]: MyValueExtractor<T[K]>
}

/**
 * The result types should be the same. However, they differ
 */
declare const resultWorking: ExtractorWorking<{foo: boolean}>;
declare const resultBroken: ExtractorBroken<{foo: boolean}>;

// `resultWorking.foo` is type of Control<boolean>
resultWorking.foo.sayHello()
// `resultBroken.foo` has a union of Control<false> | Control<true>
resultBroken.foo.sayHello()

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210315#code/PQKhCgAIUh1BTSALAhgN0SgdpABgUQA8AXAJxQGNiB7U3SYgTwAdEB3JASwqUgFsUzAM6RqAIwBW8KpDQoANgFd4ImngDC1LGWryAPHKXwAfLigxzkAMrVIYlEO4L5jAFyWA3gDNq1V9eo+eHV5ByEAX0gAXmNIb19-TW1SXT0bIJCw43DPHz9IfCxFPkiYuLzErR19QuLs3IS7X3l4bFLY+Pyk6r0xZtaseuhgcAATaVDSRApQoRFulP0AFWMPKEgNoRRGAAl4eXlqAAoASn8l8HCAbnBwUAhoOERUDEgAJlkUUk5sYhFqLwFEjkKi0IQAGlEWEQxFQxEgnBEbFoAGtOFgAOaQbCjKEwuEIkRYajESwEYGUGikWCo9EY+ioETo+To+C4ihaUacYicLQiHykbGfIxkohkSm0ABCKRR8CwDIcDCQ0053N5WBE8ApVDZDFsKEgQngzC+KGIMJY8HMIyYrCB4tB1NpmL0K2icXWGwA2gBpBE4WWMAGQJYAXXOvtDkC15qwoyJxTE8EFAH5INCMILKslUktI8ZLrdbYgALKMABqCmUYpBVL0AFVYlFIPXoyQ5fH04nk5A0xme9meo2bsX7bWpTK5a6mx6Nt6-ejIIHg2H-GXK0YaxLSK784W7mBLEtlZApkJFPJ4cWREIkNQL7ik0rEFsggA6SA7ahseCZyGw+BGEgLkvC8ZNrTGCYvhVDV4TPC9iBpUg0Uxfwt0dJCUIxPROn8PpdAGcJjBucYZmgyAOVg08VAQ6VqFlLA0O1Kk6IYnCKiaAi2mI25gGAPB4MvTC6TfPJ6ERBhLVEQEFlSfCWmwAtBMQ50MVE3w3y2XZ9kOU47n43BlNYuV1OoBURANRQsHVaTIFk-QvAUI1YgAHzsqpFj0MhlCUmjL2MrBTM07Y9gOY4TnAIA)
      

### 🙁 Actual behavior

```typescript
// `resultBroken.foo` has a union of Control<false> | Control<true>
resultBroken.foo.sayHello()
```

![image](https://user-images.githubusercontent.com/10242142/111169876-a9363e80-85a3-11eb-9a17-f383518bfac5.png)

### 🙂 Expected behavior

```typescript
// `resultBroken.foo` should be type of Control<boolean>
resultBroken.foo.sayHello()
```

Should be the same as type as `resultWorking`

![image](https://user-images.githubusercontent.com/10242142/111169799-958ad800-85a3-11eb-960e-e69cf4710ea9.png)

**Comment by nmain** [comment]
As `MyValueExtractor<U>` has a naked parameter `U` on the left of the `extends` clause, it is a [Distributive Conditional Type](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).  The type `boolean` is just the union type `true | false`, so that union is being distributed through `MyValueExtractor<U>`.  `ExtractorWorking<T>` avoids this as it never uses the naked `T` in that way.

You can opt out of this behavior as indicated in the linked docs:
```ts
type MyValueExtractor<U> = [U] extends [number] ? never : Control<U>;
```

**Comment by Humberd** [comment]
@nmain Thank you. Works like a charm. I'm closing the issue
