### ISSUE TITLE
Array.isArray works bad with ReadonlyArray

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#43247]
**TypeScript Version:**  4.3.0-dev.20210315

**Search Terms:** array isArray readonly

The first problem is that `Array.isArray` lets us violate `readonly` modifier and push values to `ReadonlyArray`:

```ts
declare const data: ReadonlyArray<any>

if (Array.isArray(data)) {
  // Expected: Error
  data.push(123)
}
```

The second problem is that `Array.isArray` doesn't filter out `ReadonlyArray` type:

```ts
declare const data: Record<string, any> | ReadonlyArray<any>

if (!Array.isArray(data)) {
  // now: readonly any[] | Record<string, any>
  // expected: Record<string, any>
  const alias = data
}
```

**Comment by MartinJohns** [comment]
> The first problem is that Array.isArray lets us violate readonly modifier and push values to ReadonlyArray:

This is most likely intentional. Be aware that readonly does not mean immutable. There is no way to represent immutability in TypeScripts type-system.

> The second problem is that Array.isArray doesn't filter out ReadonlyArray type:

See #17002. Found using your search terms.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. A regular array is a subtype of a ReadonlyArray (otherwise this hierarchy would not be useful). And if a type guard can't narrow down a type to a subtype (otherwise a type guard would not be useful).
