### ISSUE TITLE
Definition for String.prototype.replace is incorrect

### ISSUE THREAD

**Issue by ffxsam** [microsoft/TypeScript#43252]
# lib Update Request

## Configuration Check

My compilation *target* is `esnext` and my *lib* is `esnext`.

## Missing / Incorrect Definition

`String.prototype.replace`

## Sample Code

```js
const newText = old.replace(/[a-z]/, ch => ch.toUpperCase());
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

**Comment by RyanCavanaugh** [comment]
What do you believe to be incorrect about this?

**Comment by ffxsam** [comment]
I'm getting a TypeScript error, and I see this in `lib.es5.d.ts`:

```ts
    /**
     * Replaces text in a string, using a regular expression or search string.
     * @param searchValue A string to search for.
     * @param replaceValue A string containing the text to replace for every successful match of searchValue in this string.
     */
    replace(searchValue: string | RegExp, replaceValue: string): string;
```

`replaceValue` type should be: `string | ((value: string) => string);`

**Comment by MartinJohns** [comment]
@ffxsam Why don't you look a few lines below?

https://github.com/microsoft/TypeScript/blob/79c72751df2aaed2b2ba8caa4170895c343a3d5b/lib/lib.es5.d.ts#L449-L454

**Comment by ffxsam** [comment]
Will do, thanks.
