### ISSUE TITLE
optional parameter for generics is being ignored

### ISSUE THREAD

**Issue by plusgut** [microsoft/TypeScript#43251]
# Bug Report

### 🔎 Search Terms

generics, optional parameter, default generic type, generic constraint

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgMoHsC2ECS5rxIA8AKgHzIDeAUMncgG5wA2ArhAFzInUC+11ACYQEzOFBQxWIBGGDoQyQmHRQAnqWQQAHpBCCAzsgNgooAObIAvMdMWyACnQAHOQpYAFcXGyQoAfi4SAEouDGw8P0IIUjIAbgFhUXFJaVl5RREAC3QiAGktXQh9I0oAbQBrCDUuEzMQcwBdMKxcfFhEGLgQNTJeRxcwLgLQ5DyEgQQFEyUWZgAjRAqSdABhadM4UDA8Ewg4QQB5GAARCHhWZjBrLQQch0oldHQuZVU1B2DkXmQ4IymQCZggkATMQApDq4MiwcAYAGKgFA2bLoB5PF6zWTvBwAIkWAC8cV9eMDJhtkBIwKwoCAAGosdg3N7qT4g8nCC5XXaQA7HdaAzbbOFzRYICo3FFomDPLiU6l0hkoEkJIA)

### 💻 Code

```ts
interface SomeInterface<T> {
    value: T
}

declare function factory<T extends string = string>(optionalParameter?: T): SomeInterface<T>;
declare function echo<K extends {[key: string]: SomeInterface<any>}>(opt: K ): K;

const fallbackToConstraintInsteadOfDefault = echo({ foo: factory() } as const);
```

### 🙁 Actual behavior

the return type of echo is not fully of type K, but falls back to the constraint of K.

### 🙂 Expected behavior

The return type is from the default type of T.

### Notes
This behaviour does not occur in 4.1.5
This behaviour does not occur when no constraint for K is given.
This behaviour does not occur when _factory_ gets called with a parameter.
This behaviour does not occur when the return value of _factory_ is first stored in a variable.

**Comment by ahejlsberg** [comment]
Appears to be caused by #39384 and #41475. With those PRs we now produce contextual types for expressions in `as const` assertions and for that reason we make an inference from `SomeInterface<any>` (the element type in the constraint of `K`) to `SomeInterface<T>` (the return type of the `factory()` invocation). We do the same thing in both 4.1 and 4.2 if you remove `as const`. Things work as expected if you change the `SomeInterface<any>` constraint to `SomeInterface<unknown>` (since `unknown` isn't assignable to `string` we then pick `string`).

**Comment by plusgut** [comment]
A constraint is altering the type, and weakining it through `const`? That doesn't seem to be working as intended to me.

Especially since that doesn't always happen but only when the `optionalParameter` is not given, and therefore the default of `T` is assigned. In all the other cases it does not happen.

Your idea with `unknown` is interesting and does indeed work in this very simple scenario. But if I have a slightly more complex interface it will break. Since `unknown` is not assignable to  `string`

```TS
interface SomeInterface<T> {
    value: (opt: T) => T
}

declare function factory<T extends string = string>(optionalParameter?: T): SomeInterface<T>;

declare function echo<K extends {[key: string]: SomeInterface<unknown>}>(opt: K ): K;


const fallbackToConstraintInsteadOfDefault = echo({ foo: factory() });
``` 
https://www.typescriptlang.org/play?jts=4.2.3&ssl=1&ssc=1&pln=12&pc=1#code/JYOwLgpgTgZghgYwgAgMoHsC2ECS5rxIA8AKgHzIDeAUMncgG5wA2ArhAFzIAU6ADmC4kAlMgC8FEtQC+1agBMICZnCgoYrEAjDB0IZITDooAT1LIIAD0gh5AZ2R2wUUAHNxj527K8BukCwACqpw2JBQAPxCwlwY2HjhhBCkZADccorKquqa2v4WCAAW6EQA0hbWELYOlADaANYQJlxOLiCuALqxWLj4sIjJmvUg6ADuIGTSPvyCyOUxc+lyCHpOBizMAEaI9SToAMKrznCgYHhOEHDyAPIwACIQ8KzMYB5KxdyUBujoXIbGJm4omkwnSKxAaxGIGufj0LBwdgAYqAUGICh8vjAfn9EEZTNwAETbABeBOBoOWR2QajArCgIAAaix2B5-viKeC1ooni9zpArrdDhDjqdERttgh6m8iuhPt9ftSILT6Uy2CgQekgA
