### ISSUE TITLE
dotted names in export assignments

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#4325]
Current description of export assignments in the spec states:
>Export assignments exist for backward compatibility with earlier versions of TypeScript. An export assignment designates a module member as the entity to be exported in place of the module itself.
```ts
  ExportAssignment:
   export = IdentifierReference ;
```
A module containing an export assignment can be imported using an import require declaration (11.3.3), and the local alias introduced by the import require declaration then takes on all meanings of the **identifier** named in the export assignment.

However current implementation also [permits](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/binder.ts#L948) dotted names - in this case only value meaning is exported. This change seems to be quite recent, example below compiles with no errors in current master and issues a syntax error `';' expected."`in v1.4.
```ts
declare module foo.bar {
    export type X = number;
    export var X: { A: number };
}

declare module "test" {
    export = foo.bar;
}
```
This issue can have several interpretations:
- this is only spec bug - current behavior for dotted names should be documented
- this is both spec and implementation issue - we export all meanings also for dotted names and spec should be adjusted to reflect this
- this is implementation bug - we should prohibit usage of dotted names in export assignments.

**Comment by vladima** [comment]
adding @alexeagle since he reported this issue originally

**Comment by alexeagle** [comment]
+cc @mprobst

**Comment by mhegazy** [comment]
We have another report of this issue for `export default` in #4395

**Comment by mhegazy** [comment]
As a work around, you can use aliases:

```ts

declare module foo.bar {
    export type X = number;
    export var X: { A: number };
}

declare module "test" {
    import _alias = foo.bar;
    export = _alias;
}
```

**Comment by RyanCavanaugh** [comment]
Do we need to do anything here other than update the spec?

**Comment by mhegazy** [comment]
yes. we need to implement it. currently we only support exporting all meanings of `export = <identifier>` and only the value side of `export = <dotted name>`.

The main issue we can not trust that a dotted name resolves to a single symbol that we can resolve to. so what we need is create a new alias symbol, and then resolve the module to that. i.e. emulate:
```ts
import _export = a.b.c;
export = _export;
```
