### ISSUE TITLE
Allow defining type alias in class definition

### ISSUE THREAD

**Issue by yaquawa** [microsoft/TypeScript#43264]
# ⭐ Suggestion

Sometime you just want to save the type alias for reusing in class methods, currently the only way to do this is set them as default value like this: 
```ts
class Foo<T, K = keyof T> {
    bar(key: K){

    }
    barbaz(key: K){

    }
}
```

The problem is that the user of `Foo` could potentially overwrite the default ones which is not what we want. Also by writing tons of type alias in the class constructor confusing users, because they have no idea about if this is just a type alias or a real "default" type parameter that could be overwritten. in the above example the `K` has nothing to do with type parameters in perspective of users of `Foo`.

So you end up with using the same raw type definition repeatedly, which is not so DRY...
```ts
class Foo<T> {
    bar(key: keyof T){

    }
    barbaz(key: keyof T){

    }
}
```

To solve the problem, I would suggest allowing user define type alias in the class definition area :

```ts
class Foo<T> {
    type K = keyof T
    
    bar(key: K){

    }
    barbaz(key: K){

    }
}
```

TypeScript already allows defining local type alias like this:
```ts
function bar<T>(foo:T){
    type MyType = keyof T
}
```
it's natural to have similar ability in the class too in my opinion.

**Comment by RyanCavanaugh** [comment]
See #7061
