### ISSUE TITLE
Object.values and Object.entries seem to interpret values of mapped types with generics as unknown

### ISSUE THREAD

**Issue by SIGUSR97** [microsoft/TypeScript#43266]
# lib Update Request

## Missing / Incorrect Definition

`Object.values` and `Object.entries` seem to interpret values of mapped types with generics as unknown.    

## Sample Code

```ts
// OK
type K = 'foo' | 'bar';
declare const foo: { [P in K]: number };
const values = Object.values(foo);             // const values: number[]
for(const v of values) {
    v as number;                               // OK
}

// not OK
class Foo<K extends string> {
    constructor(bar: { [P in K]: number }) {
        const _values = Object.values(bar);    // const _values: unknown[], expect values to be number[] here
        for(const v of _values) {              // const v: unknown, expect v to be number here
            v;                                 // const v: unknown, expect v to be number here
        }
    }
}

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

[Playground Link](https://www.typescriptlang.org/play?ts=4.2.3&ssl=17&ssc=2&pln=1&pc=1#code/PTAEHkGkCgBcE8AOBTUlQF5QHIBmB7fbUAHxwCMBDAJ2wG5oATZAYwBsbUX8A7AZ1igC+AFygA3qADaABVABLHmgC6YngFcAtuWTVQAXwbd+ggG6U265H0wRyAK1awAdOcvWAFMICUdUP4DAgJBQYwFQNys+NS0daillaAJqDzCzUHxcCIso7wloQNNQShsNbV0-IKrqmsCQqGh9aGgQnnxBBvYSmwAxQgAedGQAD1hkHkYbAWpFAHMAPnzAtOp1Flh8FKpqMUlZBSVIVVAyuIM88QLqtNAAfUjrW3AHJ1ccz23fOrAb+-fo0DqHgAazaAHceAkADSgEYodbZdw2DagHQnWK6BKgAAWumQVyqyVSvHCRUydwefAutSCIRupjEQNB+AhMLhTgioBRaNOuhxeIJtVMlRpoppdJJZkZIPBPDZw3h6W5qF5elx1HxNSagSa+iAA)

**Comment by RyanCavanaugh** [comment]
You used `for of` in the top sample and `for in` in the second; seems like a typo?

`unknown[]` is the correct type for `_values`:
```ts
const obj = { a: 10, b: "nope" };

// Legal call; _values will see [10, "nope"]
const m = new Foo<"a">(obj);
```

**Comment by SIGUSR97** [comment]
> You used `for of` in the top sample and `for in` in the second; seems like a typo?
> 
> `unknown[]` is the correct type for `_values`:
> 
> ```ts
> const obj = { a: 10, b: "nope" };
> 
> // Legal call; _values will see [10, "nope"]
> const m = new Foo<"a">(obj);
> ```

Oops... You're right, I did make a mistake about the use of `for...in` and it was suppose to be a `foo...of`(switching between python and ts gets you messed up).  But I insist that the problem still exists, typescript should be able to tell that `_values` is a `number[]` instead of `unknown[]` **in the constructor function** .

**Comment by RyanCavanaugh** [comment]
>  But I insist that the problem still exists, typescript should be able to tell that _values is a number[] instead of unknown[] in the constructor function 

It's not. There might be non-`number` values in it. `number[]`s cannot contain non-`number` entries.

**Comment by SIGUSR97** [comment]
> > But I insist that the problem still exists, typescript should be able to tell that _values is a number[] instead of unknown[] in the constructor function
> 
> It's not. There might be non-`number` values in it. `number[]`s cannot contain non-`number` entries.

I wouldn't expect non-number types to appear in values of type `{ [P in K]: number }`. If the user of this class decides to pass in non-number types as values of the input argument, I would expect them to see errors as below.
```ts
const bar = new Foo({ 'foo': 1 });
// @ts-expect-error
const baz = new Foo({ 'foo': 'not a number' });
```
Should I provide a more specific use case for this just to give more context to my issue?

**Comment by RyanCavanaugh** [comment]
> I wouldn't expect non-number types to appear in values of type { [P in K]: number }

Your expectation is not correct. Object types are not sealed; the only guarantees you have in this class are about what values obtained from `bar[K]`, which is not what `Object.entries` does.

**Comment by SIGUSR97** [comment]
I guess I didn't have too good of an understanding of Object types. Can explain a bit more about the following:

> Object types are not sealed

I still don't quite understand why you wouldn't expect `number[]`, from `Object.values<{[P in K]: number }>`. To my understanding before it should be similar to `Object.values<Record<string, number>>` but apparently not. Sorry for bothering you so much and thanks in advance.

**Comment by MartinJohns** [comment]
@SIGUSR97 Consider this simple code example:

    const val = { a: 0, b: 'hello' };
    const tmp: { a: number } = val;

`tmp` is assignable to `Record<string, number>`, but gettig the values of it will result in `[0, 'hello']`.
