### ISSUE TITLE
`number extends Enum` should evaluate to false

### ISSUE THREAD

**Issue by ljqx** [microsoft/TypeScript#43269]
**TypeScript Version:**  4.2.3

**Search Terms:** number extends enum

**Code**

```ts
export enum NumericEnumFruit {
  APPLE = 1,
  BANANA = 2,
}

export type NumericEnumFruitIsSuperNumber = number extends NumericEnumFruit ? NumericEnumFruit : never; // Yes, returns NumericEnumFruit
export type NumericEnumFruitIsSuperString = string extends NumericEnumFruit ? NumericEnumFruit : never; // No, returns never

export enum StringEnumFruit {
  APPLE = 'apple',
  BANANA = 'banana',
}

export type StringEnumFruitIsSuperNumber = number extends StringEnumFruit ? StringEnumFruit : never; // No, returns never
export type StringEnumFruitIsSuperString = string extends StringEnumFruit ? StringEnumFruit : never; // No, returns never

export enum HeterogeneousEnumFruit {
  APPLE = 'apple',
  BANANA = 2,
}

export type HeterogeneousEnumFruitIsSuperNumber = number extends HeterogeneousEnumFruit ? HeterogeneousEnumFruit : never; // Yes, returns HeterogeneousEnumFruit
export type HeterogeneousEnumFruitIsSuperString = string extends HeterogeneousEnumFruit ? HeterogeneousEnumFruit : never; // No, returns never

const ConstObjectFruit = {
    APPLE: 'apple',
    BANANA: 2,
    // 2: 'BANANA'
} as const;
type ConstObjectFruitType = typeof ConstObjectFruit[keyof typeof ConstObjectFruit];

export type ConstObjectFruitIsSuperNumber = number extends ConstObjectFruitType ? ConstObjectFruitType : never; // No, returns never
export type ConstObjectFruitIsSuperString = string extends ConstObjectFruitType ? ConstObjectFruitType : never; // No, returns never

```

**Expected behavior:**
Always got `never` for all above conditional types.

**Actual behavior:**
For `number extends Enum` cases, it's evaluated to true, instead of false. While things are correct for `string extends Enum` and `number extends ConstObjectType`.

**Playground Link:**  
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwHJuFAlgYwFEVUAxKZXeAbwCg44BBABWYBlC4BeOARgBp6cAEKMMYxtzgAmQQF9atUJFhwYATzDBM2PERLlKMAJIBnAMrItULKgBGOKSQdQEIGEgAmpnahwFiNEMqOAB+X399IIoQgC44RGAANxwAbjgAegy4AE1gU344KGAYZChEH1tIwLIYmCVwaHgNLQi9GuCTCysccxg8RABzKVN+3CG3D0RvNoCDOrDZqNqjOHjElKh0rMwIQuLS8p8NnEVlJoQSOD6BwY6FugYWdk4eAHIAQzAwABtgN8EDFE4nEUjedg+iEhHwBtAUDRUzU02hu4zu8yMZks1lsLicaDxoCmM1RQ3uq3CpPR0VW62SaUy2QweyKJTKFQS9KgCIuLRRYzJGKoWJ6UCpIwFwyJXh8VPJIUpkvl8Dpm22TJZB3Zxy5Z0aqiQaDgAAkSjgIIMkMAIMhTMq4I8mKwOGCvr9-oCRBJQTxZHC9Yi1MiTWaoBarTa7UKuticLjHDxnI5pdMfKaPGHLYlI-bwunzVnrbb7aqGTs8gVWYcOfnMxHi9Geao+SGM+Hsw2acLutZxTxRrdJjLWwX61Gu-A86H20Xxys4py1Yzdvs2UdF6daPgIBV4ABhHejADydgAVsB8DBOlJHU9nYR4p9vn9YQwgd7GPE-W-l9JH8CJDeOE4A+Hxt13VJaBbA9dxPc9L06AAVYMeD5CAADM4Bg48zwvK86gAbQAa2AdQMKDLRyOwmA4LwzoAF1IKbJFWmo2iELqEUcQJBMEh41wUxmNjcI4oxkNacJhPg-CxODUstmXZlV2rHVNmYijtCkujOJ7XpJQlQdBJ8LTRKocTtEkw8aJEmSzLkjcFJ2JSq21BzaCAA

**Related Issues:**
Didn't find related issues.

**Comment by MartinJohns** [comment]
See: https://github.com/microsoft/TypeScript/issues/32690#issuecomment-517882099
