### ISSUE TITLE
Interface that extends from class

### ISSUE THREAD

**Issue by OlegDokuka** [Microsoft/TypeScript#4326]
Hi guys, is it okay, that the interface can exteds from class without any compilation error??

```
 class AAA {
        a: string = "";
        b: string = "";
        c: number = 1;
    }


    interface BBB extends AAA { /// NO COMPILATION ERROR!!
        asdasd: string;
    }

```

I think it is a bit strange...

**Comment by jesseschalken** [comment]
No that's not strange. I imagine it's saying "a `BBB` has to be have all the things an `AAA` has, plus a publc `asdasd:string` property".

In fact it follows from TypeScript's structural typing. When you use `AAA` as a type it doesn't necessarily mean "an instance of the `AAA` class", it just means "a thing with all the public methods/properties of `AAA`".

**Comment by OlegDokuka** [comment]
it breake all my imaging about OOP, that is why it is very strang!)

**Comment by jesseschalken** [comment]
It's just [structural](https://en.wikipedia.org/wiki/Structural_type_system) instead of [nominal](https://en.wikipedia.org/wiki/Nominal_type_system) typing. Make of it what you will, but it fits very well in JavaScript world and often comes in handy. You can probably ignore it and just code like you're used to and things will work out fine.

**Comment by OlegDokuka** [comment]
We talk about Typescript, and if I understand correctly, the TS is trying to provide **nominal** typing like in C#, Java, etc

**Comment by jesseschalken** [comment]
No, TS is trying to provide *static* typing like C#, Java, etc. Static typing can be either nominal or structural.

**Comment by DanielRosenwasser** [comment]
Yes, @jesseschalken is correct, we are going for static typing; nominal/structural is an orthogonal concern. My understanding is that the static type systems in languages like Go, OCaml, F#, and C++ all exhibit characteristics of a structural type system, whether fully or partially.
