### ISSUE TITLE
Not able to infer proper type from an intersection

### ISSUE THREAD

**Issue by SamBreaksThings** [microsoft/TypeScript#43267]
Typescript version: 4.3.0-dev.20210316

When an array is of type `A[] & B[]` and we extract an item, it should infer `A & B` for the item. It works as expected when doing `arr[number]` but using generics infers the type as `B` and not as `A & B`. Not sure if it's an intentional limitation or this use-case is particularly weird. 

```javascript
type Foo = { foo: string };
type Bar = { bar: string };

function getFirst<T>(arg: T[]): T {
  return arg[0];
}

const arr: Foo[] & Bar[] = [];
const headElem = arr[0];             // headElem: Foo & Bar
const firstElem = getFirst(arr);     // firstElem: Bar
```

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKAzBAuKBnYAJwEsA7AcygF8BuAWAChRIoAhAQ0OTSgCNPcBEhWr0GjDAFdSAY2DE4pKOQjAYxQgQA8AFQB8ACk7lcOgNoBdAJSm0jKFEKrJhJcbMAGC2KqNGMxQIoTkJceDhLKAAyNk5IlEsxANIgjA0CAFEAGwgAW24VNXTgI0JCKxooAHoqzGLsvNwOQn9A4CgACwh2ABMG-JQQz29q2q7e-rCEaNjCIA)

**Comment by NightshadeX9X** [comment]
Line 8: Change
`const arr: Foo[] & Bar[] = [];`
to
`const arr: (Foo & Bar)[] = [];`

**Comment by RyanCavanaugh** [comment]
`T[] & U[]` is almost never what you mean to write; this type doesn't really make much sense.

**Comment by SamBreaksThings** [comment]
Yeah, that's right. I know `(A & B)[]` works fine. But I had a module which returned `A[] & B[]` and was curious to see that `arr[number]` inferring the correct type BUT generics did not. Is there a reasoning to it?
