### ISSUE TITLE
Why doesn't the logic of Object.keys being string[] apply also to Object.values?

### ISSUE THREAD

**Issue by aahmadi458** [microsoft/TypeScript#43265]
Consider the following:
```typescript
type MyUnion = 'a' | 'b' | 'c';

type Mapped = Record<MyUnion, number>;

const obj: Mapped = {
    a: 10,
    b: 20,
    c: 30,
}
```

Now, as you most certainly know, the type of `Object.keys(obj)`, in this case, would be `string[]`, rather than `MyUnion[]`.

Whenever we ask "why", we're told that it's because types in TS are open-ended and the object could contain more properties with different keys than what's specified in the type, and that makes sense. I quote (#42009)
> Object types aren't sealed, so it would be unsound to allow this.

But my question is: Why doesn't the same logic apply to `Object.values()`?! In this case, for example, the type of `Object.values(obj)` would be `number[]`! But again, we could use the very same logic to demonstrate why that shouldn't be the case.

`obj` in this case, could have more properties of different types than what's specified in the `Mapped` type, and therefore, allowing `Object.values(obj)` to have a type of `number[]` **makes as much sense as** allowing `Object.keys(obj)` to have a type of `MyUnion[]`.

Correct me if I'm wrong but there seems to be an obvious **double standard** here.

**Comment by RyanCavanaugh** [comment]
Because we made a mistake typing `Object.values` and don't want to take a breaking change on it now.
