### ISSUE TITLE
Re-mapped keys with ternary constraint resolving value as unknown

### ISSUE THREAD

**Issue by jgeurts** [microsoft/TypeScript#43279]
# Bug Report

### 🔎 Search Terms
re-map
remap
ternary
mapped constraint 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about type system behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/IYIwzgLgTsDGEAJYBthjAgogOwgSwgE8EBvAXwFgAoPXAUygDM46tcDiTqEEB9XvGBz4iAfgBcCaAFc6AbmqUq1IgAdWmAB4ppAEzoAxadnh4A9tjABBbLuEcAwmeTI6pi2AA8AFQDyUPABzWmBkb0J1ABoEAGkEOk0IOlsMAGs6QjNGBD8A4OxQ8PUAPgQAXgRqXKCQsIi6AG0YgF14xOTdDHsiBtbRBGw6ADcGBEluHhz-GoK69SbWhKSUhCMTfAsEfsGRqDHKqkmj2IVlKjVWAGUzKAhfEAArNwgfUoquQ4QmhFoEdMzst5mhIEABaACMCAAPggAORoWCw6Fw-RgRHI8GnMinFT1BDXW73J7wABMr3KpAm31+-yyOQQaCw2mQekMxnclhsdnYRCcLme5ksPmiMWKwMkEOR8LRSJhsNR6JhmMUOPOeIJd0ezwAzOT3lS4jSMnTvAyMN4Fm1lp0vn0BsNRpIWiDJXKEbKUXQZRisarGOyNtgEAB3G6pWiBHxWjpdHmEYoACjANwgYEkGqJz1eAEpKZ9GDcEAnYB5EA0CgBbOjRG76KCtOmZ+AAOmS0DwXqTKbA2dzHyOAHoBwha6NBEgblBnshiK64e6pQqPZCYcZ9IxaHRdBMeCXLM46M3kGZAgmAAYAEhIlboZEkV9HUDIZ+zpx4SiU1H960FAzMEAAdTDCMoyWGM2BEeMu1uNN8RTJsIDJbxij7CYCz2YtSy+G8aygOsG2yBDW1wAJO2TGDezzQdh38OsfgwYxUmwMxg2wHcJ33VwjxPc8rxvO8EAfPCGGfV8Jg-agvwDX9mMA4DsECXVTTAlZuig8jU3TeCtXgJSUKohB0KLPdIGw4Aq1w-CR0InSIGI9syO7Sj+0mIcEFoscGOwJiWLYz5dw8A9uNPS9r3M297xIR9RLfBAJKoIA)

### 💻 Code

```ts
abstract class Entity {}
interface Entity {
  __isEntity?: true;
}

type SortObject<T> = {
  [K in keyof T as T[K] extends [] ? never : K]?: -1 | 'asc' | 'desc' | 1;
};

function notWorking<T extends Entity>(sorts: SortObject<T>) {
  for (const [name, order] of Object.entries(sorts)) {
    // Type of order is unknown
  }
}
```

### 🙁 Actual behavior

Type of `order` is `unknown`

### 🙂 Expected behavior

Type of `order` should be `-1 | 'asc' | 'desc' | 1 | undefined`

**Comment by RyanCavanaugh** [comment]
`order` doesn't always have one of those values. Here, it's `"hello world"`:
```ts
const obj = { foo: "hello world" };
const p: {} = obj;
notWorking(p)
```

**Comment by jgeurts** [comment]
Oh, that's not what I expected, with the `extends Entity` constraint. 🤔 

Worth noting that the type of `order` is correctly inferred when using the following:

```
type SortObject<T> = {
  [K in keyof T]?: -1 | 'asc' | 'desc' | 1;
};
```

I'm curious why the re-map would change how the value is determined
