### ISSUE TITLE
Classes, extends, constructor order 'bug'

### ISSUE THREAD

**Issue by SamanthaAdrichem** [microsoft/TypeScript#43271]
# Bug Report

When using classes and extends you'd for example create a class like this:

```
class a {
    public value: string = null;
}

class b extends a {
    public otherValue: string = null;
}
```

Now what we like to do is add this constructor to class a

```
constructor(config?: Partial<a>) {
    Object.assign(this, config);
}
```

This allows you to assign the entire object from another object when actually calling the constructor.

With the following snippet:
```
class a {
    public value: string = null;

    constructor(config?: Partial<a>) {
        Object.assign(this, config);
    }
}

class b extends a {
    public otherValue: string = null;
}

let x = new b({value: 'test', otherValue: 'test 2'});
```

You'd expect otherValue to be 'test 2'.. But that's actually not the case. Because typescript first starts class a, sets the public values, executes the constructor, then starts class b and sets the initial values. causing b to overwrite otherValue back to null.

### 🔎 Search Terms

is:issue is:open constructor
is:issue is:open constructor object assign 

### 🕗 Version & Regression Information

We're using typescript 4.0.5 with ts-node 8.5.4 in an Angular project.

- I was unable to test this on prior versions because I believe this is a bug, but also expected behaviour because that's how it currently works, classes and extends do not really exist.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEDMFcDsGMBcCWB7aoDmBTeA1AhgDaSYA8AKgDSgDSoA1pgJ7LihkB8AFItAA6TwA8gCMAVpgQAuSqABuhYgDk8AW0ySaASg15ojUAG8AUCFBmzAJ2yQLaHvyFiJ8ANryimZWoC6AbhNgAL5GRrAEeADOEaB4hkbmoPzCBIiwcgrqoBHwFjzooAC8oNCQBAT+8eawqNkWkAjIFpzV0OCI6AD8GgAKeBZIhCR47JpxCQki4ggAdJER7dCc8AAWiBFULW3omv4JwcGh4VGgwqCYAB7wmNAAJtGxxglJKWnIK5gW+B4atXmFxaVykYDgRsKBzv9oJgAO4nTgGdzEDQAciu2WRVDeyw+XyRoFRmGyoAATMjAjtQjVkKDpgRkOhOOcdkA)

### 💻 Code

```ts

class a {
    public value: string = null;

    constructor(config?: Partial<a>) {
        Object.assign(this, config);
    }
}

class b extends a {
    public otherValue: string = null;
}

let x = new b({value: 'test', otherValue: 'test 2'});
console.log(x);
// Expected b: {"value": "test", "otherValue": "test 2"} 
// Recieved b: {"value": "test", "otherValue": null} 
```

### 🙁 Actual behavior

The initial value of the class overwrites the value assigned in the constructor whilst the constructor of A and B should be executed after setting the initial class variables.

### 🙂 Expected behavior

To first setup class A's internal vars, then class B's, and then call the constructor of A and then B, just like any other language with classes.

For now i've solved it by doing this in class B, but that only makes it worse, because you have to call the constructor of class A even if it makes no sense  :( But that's javascript.

```
constructor(config?: Partial<b>) {
	super(config);
	Object.assign(this, config);
}
```

**Comment by MartinJohns** [comment]
See: #1617

**Comment by SamanthaAdrichem** [comment]
That's what I was affraid of. :(

**Comment by RyanCavanaugh** [comment]
See also https://stackoverflow.com/questions/43595943/why-are-derived-class-property-values-not-seen-in-the-base-class-constructor
