### ISSUE TITLE
No error when using spead operator on an interal's properties

### ISSUE THREAD

**Issue by jgresty** [microsoft/TypeScript#43270]
# Bug Report

### 🔎 Search Terms

spread built-in internal

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about type system behaviour

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDAFAIwK4DMsC4YDeMaAnlAKYAy5YA5lABb5gYC2a5ATjAL4CUSAHwxQkEABtyAOnEha6bFimkK1Ooz4AoUdGKKkMMOQDuMAIKdOcEgCFFXFAEYATAGYtcBTgEB6HzAAxAEsjTU8CKUjMHH4YPxgABU4QqAgYDDAAE3IsEPJMgBoYcgAPAAdyYApM4ssQTiA)

### 💻 Code

```ts
const a = (buff: { byteLength: number }) => console.log(buff.byteLength)
const buff = new ArrayBuffer(123)
a(buff) // Fine
a({...buff}) // Prints undefined, expected error
```

### 🙁 Actual behavior

Properties are not copied with the spread operator but the typing of the new object asserts they are present.

### 🙂 Expected behavior

The type of an object constructed with the spread operator to not include properties that were not copied to it.

**Comment by RyanCavanaugh** [comment]
Duplicate #9726
