### ISSUE TITLE
Mapped type in generic function can cause unbound generic to leak

### ISSUE THREAD

**Issue by tjjfvi** [microsoft/TypeScript#43277]
# Bug Report

### 🔎 Search Terms

unbound type parameter generic leak

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.3.0-dev.20210316#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYCg9oAPABy2TVFlwGdKsAjAK1AF5QAeAQQBoA+ABQ0AFohLQAXKADeoANoBpUBhygA1tACeWAGaguAXSldFB0AF8AlGz6gRY6ARCgAdJBdoad4VgDuX6mRkOEo0TXFCUnJKahw6UAYsIjZOACF+ATQpVOtWW0YmAVkAN0R4AFdJUEorAG48Z1Am5paAPQB+BrAAFXDoUHgsLDUA8mDYNCcwNw8vET9RuMoiKRKyyuyLSLIKKlpllMSiAQBWSy6Wy6uOi4BlH39QcpxE58hQVKnXd09vBb2lqAVjJQKUKlVUltiDsYvtQJoUkQLlc2p1nPd-s9Xjh3p8LjNfvNHmFxKAAKopEnQXRAlxgyrbaLVPrkyl9GlEOnrRyNFGgG7oh5eLFYN4fPBAA)

### 💻 Code

```ts repro
// @declaration

export const obj = &lt;A,>(shape: { [K in keyof A]: A[K] }) => shape

// .d.ts shows correct type
export const box = &lt;B,>(t: B) => obj({ value: t });
//           ^?
// Type looks correct

// .d.ts shows const x: { value: B }
export const x = box(5)
//               ^?
// Shows unbound B

// .d.ts shows const x: { value: B }
export const y = x
//           ^?
// Shows unbound B

// .d.ts shows type U = typeof x.value
export type U = typeof x.value
//          ^?
// Shows unbound B

```

### 🙁 Actual behavior

The type of `x` is `{ value: B }`, where `B` is an unbound generic that leaked from `box`

### 🙂 Expected behavior

The type of `x` is `{ value: number }`

### Related Issues

#31326, #31402

/cc @samholmes

**Comment by andrewbranch** [comment]
Fixed by #42449
