### ISSUE TITLE
IIFE ReturnType inference misses tuple from expected type

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#43274]
[Playground Link](https://www.typescriptlang.org/play?ts=4.2.3&ssl=1&ssc=1&pln=8&pc=23#code/C4TwDgpgBAKgrmANtAvFA2gOzgWwEYQBOAugNwCwAUACYQDGiAhodMsFMAsgFyxcQUa9JiyhsO-AGKZeACgCUUFAD4+SAVSqd10pVAVLV6AIxkt-PduTSFg8+r2yDKjKfm2gA)

TS 4.2.3 and 4.3.0-dev.20210314

```ts
type Tuple = [number];
declare let tuple: Tuple;
declare let tupleFn: () => Tuple;

tupleFn = () => [1];
tuple = (() => [1])(); // Error
```
```
Type 'number[]' is not assignable to type 'Tuple'.
  Target requires 1 element(s) but source may have fewer.(2322)
```
Unexpected Function Type
Expected typeof `() => [1]` to be inferred as `function(): [number]` in both cases

**Comment by RyanCavanaugh** [comment]
See #241
