### ISSUE TITLE
Using keyof operator for indexing access type gets wrong type

### ISSUE THREAD

**Issue by ErfanMirzapour** [microsoft/TypeScript#43288]
# Bug Report

### 🔎 Search Terms
Indexed Access Types

### 🕗 Version & Regression Information

- I was unable to test this on prior versions.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ssl=3&ssc=20&pln=1&pc=1#code/C4TwDgpgBAglC8UAUA7ArgWwEYQE4B8BnYXASxQHMBKAbQF0BYAKGdEigCEFYaBrCEAHsAZrDpA)

### 💻 Code

```ts
type A = (number|string)[]

type B = A[keyof A]
```

### 🙁 Actual behavior

This is what you get as type `B`:
```ts
type B = string | number | (() => string) | (() => string) | (() => string | number | undefined) | ((...items: (string | number)[]) => number) | {
    (...items: ConcatArray<string | number>[]): (string | number)[];
    (...items: (string | ... 1 more ... | ConcatArray<...>)[]): (string | number)[];
} | ... 23 more ... | ((searchElement: string | number, fromIndex?: number | undefined) => boolean)
```

### 🙂 Expected behavior
The expected type is `number | string`.

If I write the above code in a different way resulting type would be correct, e.g.:
```ts
type A = (number|string)[]

type B = A[number]
// type B = number | string
```

### Note
I don't know it's a bug or expected behavior. Just for me, it seemed like the second one.

**Comment by MartinJohns** [comment]
`A` is an array, so `keyof A` is all the properties/methods of the array: `"length"`, `"toString"`, `"pop"`, etc. You can see this more clear by omitting the `number` type from the union: `type F = Exclude<keyof A, number>`. Looking those values up using the type indexer syntax (e.g. `A["pop"]`) results in the method signature. Why do you expect this to result in the type of the arrays items? That's exactly what the syntax `A[number]` is for.

**Comment by ErfanMirzapour** [comment]
You're right @MartinJohns.
I don't know why I forgot to consider `Array.prototype` properties.

Thank you!
