### ISSUE TITLE
Project that references another does not resolve types

### ISSUE THREAD

**Issue by Fehniix** [microsoft/TypeScript#43286]
# Bug Report

### 🔎 Search Terms

Project that references another does not resolve types; global types and TypeScript project reference(s)

### 💻 Code

I have the following project structure:

    - /
      - tsconfig.json
      - tsconfig-base.json
      - /src
        - types.ts
        - tsconfig.json
      - /test
        - myTest.ts
        - tsconfig.json
      - /dist

`/tsconfig.json` is a solution, it references `/src/tsconfig.json` and `/test/tsconfig.json`.

`/src/tsconfig.json` and `/test/tsconfig.json` both inherit from `/tsconfig-base.json` which contains project-wide `compilerOptions`.

`/test/tsconfig.json` references `/src/tsconfig.json` to get access to the types declared in `/src/types.ts`. These types are visible within `/src` but not from `/test`, as expected. What am I doing wrong?

`/tsconfig.json`
```json
{
	"files": [],
	"include": [],
	"references": [
		{ "path": "src" },
		{ "path": "test" }
	]
}
```

`/tsconfig-base.json`
```json
{
	"compilerOptions": {
		"target": "ES2020",
		"module": "CommonJS",
		"outDir": "dist",
		"rootDir": ".",
                "composite": true,
		"declaration": true,
		"sourceMap": true,
		"declarationMap": true
	}
}
```

`/src/tsconfig.json`
```json
{
	"extends": "../tsconfig-base",
	"include": [
		"./*",
		"./**/*"
	]
}
```

`/test/tsconfig.json`
```json
{
	"extends": "../tsconfig-base",
	"references": [
		{ "path": "../src" }
	],
	"include": [
		"./*",
		"./**/*"
	]
}
```

`/src/types.ts`
```typescript
interface Array<T> {
    myTestMethod(): void
}
```

### 🙁 Actual behavior

`/test/myTest.ts`
```typescript
const arr: Array<string> = new Array<string>(); 
arr.prototype.myTestMethod; // This throws "property myTestMethod does not exist [...]"
```

### 🙂 Expected behavior

`/test/myTest.ts`
```typescript
const arr: Array<string> = new Array<string>();
arr.prototype.myTestMethod; // Should be undefined (the `Array.prototype.myTestMethod` property has yet to be defined)
```
### Notes and intent

`/test/myTest.ts` is a script, not a module. I would expect the types declared in `/src/types.ts` to be visible to the `/test/` project. Is this normal behaviour? My objective is declaring types that are globally visible across referenced projects, where types may reside inside a referenced project - thank you.

**Comment by RyanCavanaugh** [comment]
> Is this normal behaviour?

This is the intended behavior for reasons that are rather long to explain (happy to if you care). If you want to source "global" declarations in an upstream project, they need to come from a project with `module: "none"`

**Comment by Fehniix** [comment]
Hello Ryan – I would be thrilled to know if it's not too much of a bother; thank you!

**Comment by RyanCavanaugh** [comment]
Sure so the whole idea with project references is that you would only be consuming the relevant parts of an upstream project, and would do so quickly. For a module this is straightforward; if you import a module from a target that's a project reference, we redirect it to the .d.ts file of the output folder. A key principle here is that we never want to do more work on the upstream project than is necessary, so for output files from a referenced project that you don't (in)directly consume, we don't even load them in the first place.

For a global file, this is less straightforward. Critically, we don't know *which* files in the upstream project are global files and which are modules. To get the global files into scope automatically, we'd have to first parse every file in the referenced project to see if it's a module or not, which is a ton of work (esp. given that most module compilations contain zero nonmodule files!)

If you have `module: "none"`, though, it's straightforward: Everything must be global! So we can eagerly load all those files without fear of wasting any work.

**Comment by Fehniix** [comment]
Understood! Thank you so much!

This might definitely be out of scope and I would eventually ask on StackOverflow – if a `module: "commonjs"` references a `module: "none"`, then, are all files parsed and visible to the "parent project"? I also wonder how the opposite works – if a `module: "none"` project references a `module: "commonjs"` project, I would still expect every file of the referenced project to be parsed albeit. I will be definitely experimenting, thank you again!
