### ISSUE TITLE
Assign to union with over 25 items gives error

### ISSUE THREAD

**Issue by cevek** [microsoft/TypeScript#43283]
# Bug Report

### 🔎 Search Terms
union 25

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210316#code/C4TwDgpgBAglC8UDeUDWBLAdgEwFxQHIYYCoAfQmAIVIqIGFbKARJogUTZgDEuBxLgAkuAaVIBfANwBYAFChIUKgmRoseQlRLlNNHQSqN9VVsc7HexgceHGxUKXIXR6KlBhz4C9bXXp6-Iz9TP3M-Sz9rP1s-eykoAHoEqHQAMygAJwgAWwB7ADdoABsAQwBnYCgAJhTgHLKAGihgAAsITChc1CdwaGpXRDgKZQp6GVk5bAgAY1KsqGnczAq1T1hDAG0CD2wCAF1xxeXKgA98frdV7AdJIA)

### 💻 Code

```ts
type A = { kind: 'AA' | 'AB' | 'AC' | 'AD' | 'AE' | 'AF' | 'AG' | 'AH' | 'AK' };
type B = { kind: 'BA' | 'BB' | 'BC' | 'BD' | 'BE' | 'BF' | 'BG' | 'BH' | 'BK' };
type C = { kind: 'CA' | 'CB' | 'CC' | 'CD' | 'CE' | 'CF' | 'CG' | 'CH' | 'CK' }; // if remove 2 last items then ok
type ABC = A | B | C;

declare const kind: ABC['kind'];
const x: ABC = { kind }; // error
```

### 🙁 Actual behavior
Types of property 'kind' are incompatible.

### 🙂 Expected behavior

no error

**Comment by MartinJohns** [comment]
Duplicate of #40803. Used search terms: `union 25`.

This is a hard coded intentional limit.

**Comment by MrNovado** [comment]
@MartinJohns Thanks! Is there any know and accepted workaround for this? Or are there any plans to up the limit in the near future?

**Comment by MartinJohns** [comment]
I don't know of any workaround, and I'm not aware of any plans to increase this limit. But that would be up to the TypeScript team, of course.

A good idea is to subscribe to the existing issue, so you get notified if something is changing.

**Comment by RyanCavanaugh** [comment]
We don't plan to change this. There are a decent number of cases where we try this structural expansion but it *doesn't* work, so limiting the cost of that happening is important.

**Comment by cevek** [comment]
It will be good if there will be right error about this limit, not incompatible error

**Comment by RyanCavanaugh** [comment]
> It will be good if there will be right error about this limit, not incompatible error

It's not clear how to do this. "It's possible that a finite expansion of all possible inhabitants of each type may result in a subset" is going to be true a decent amount of time yet would be very confusing.

**Comment by jogibear9988** [comment]
Wouldn't it be desiarable to add a tsconfig parameter for the limit?

**Comment by denbkh** [comment]
> > It will be good if there will be right error about this limit, not incompatible error
> 
> It's not clear how to do this. "It's possible that a finite expansion of all possible inhabitants of each type may result in a subset" is going to be true a decent amount of time yet would be very confusing.

@RyanCavanaugh right now the error message is very confusing. The compiler should output in error message that the hardcoded limit is reached.

**Comment by RyanCavanaugh** [comment]
@denbkh you would see that error all the time in cases where even if the limit were Infinity, the assignment would still fail
