### ISSUE TITLE
what is this mean?

### ISSUE THREAD

**Issue by Elliott-Hu** [microsoft/TypeScript#43282]
# Bug Report

![image](https://user-images.githubusercontent.com/16644716/111412906-35697280-8718-11eb-9d0f-94680be595fb.png)

### 🕗 Version & Regression Information
4.2.3

how to fix？

**Comment by Elliott-Hu** [comment]
'yield' expression implicitly results in an 'any' type because its containing generator lacks a return-type annotation.ts(7057)

**Comment by Elliott-Hu** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html
I Found it, It`s breaking change
thanks

**Comment by RyanCavanaugh** [comment]
FWIW, please don't post code as screenshots
