### ISSUE TITLE
Unexpected "Object literal may only specify known properties" when stripping function keys from a generic interface function parameter

### ISSUE THREAD

**Issue by vkarpov15** [microsoft/TypeScript#43281]
# Bug Report

I'm trying to create a generic type that removes all properties whose type inherits from `Function` in a type. The type mostly works, but seems to strip out _all_ properties in the case when it is passed a generic interface.

### 🔎 Search Terms

typescript generic object literal may only specify known properties
typescript iterate generic interface properties

### 🕗 Version & Regression Information

Only tested on v4.2.3

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMIHsC2n0gJLjTxIA8AKgHzIDeAUMsgM5YRgAWoA5gFxNhRcA3PWQJckcAH5eZYQF9htUJFiIUAMXToaIkHEwRejfkNpzatMAE8ADhoCuIBGGC4AClHR2o1gHL6IRnIqAF4dBgBtAGlkUGQAawgrdBhkMgBdXgAGZAgADwkAE0ZkAAoARmQAMjTo9IBKZElkEAgAN2hkXlKyOtyCiBBi5HVHZ1cQJuQY3laOqHqzCMTk1IzFaztkAGVoYDgAG2AALzgAIwOIDy9oF0Dg5DCAeUxgMBIMbFwCFWIIYIANCMxi53J5vH4AkFKBQNrYUABZdCFCAHB5hOgMGCgQpPVrdMC8XYCQ4nc6Xa4Q4D3SiNEJUNroYCFeSKGAgibIADu6Cg8QA6m82PyoHAbN5gqUcCiDrwkTLgvVeIzmeFkNLUQA6bFDPEQUrUJgsdhcXgAckgxjNyDk9XkFgA9AAqdlOUGTHl8wXsEVi7wAJilyNRcuDaM06AoSuQKsKao1B21OL1BqNBhNIB4yAtgTA1tt8idDqAA)

### 💻 Code

```ts
interface CommonInterface<T> {
  something: string;
  content?: T;
};

interface Foo {
  name: string;
}

type FunctionPropertyNames<T> = {
  [K in keyof T]: 0 extends (1 & T[K]) ? never : (T[K] extends Function ? K : never)
}[keyof T];

type SerializableProperties<T> = Omit<CommonInterface<T>, FunctionPropertyNames<T>>;

type Model<T> = {
  findOne: (t: SerializableProperties<T>) => void;
};

function workWithWrapper<T>(model: Model<T>): void {
  model.findOne({ something: 'test' });
}

/*function workWithWrapper2(model: Model<Foo>): void {
  model.findOne({ something: 'test' });
}*/
```

### 🙁 Actual behavior

Code doesn't compile, I get the below error:

```
Argument of type '{ something: string; }' is not assignable to parameter of type 'SerializableProperties<T>'.
  Object literal may only specify known properties, and 'something' does not exist in type 'SerializableProperties<T>'.
```

However, uncommenting `workWithWrapper2()` and commenting out `workWithWrapper()` compiles.

### 🙂 Expected behavior

I'd expect this code to compile as written. Shouldn't matter what generic value you pass to `Model<T>`, there should always be a `something` property.

Re: https://github.com/Automattic/mongoose/issues/9989

**Comment by RyanCavanaugh** [comment]
> Shouldn't matter what generic value you pass to `Model<T>`, there should always be a `something` property.

We don't have any facility to synthesize that kind of higher-order reasoning. Even as a human I'm not totally convinced based on how `FunctionPropertyNames` is written (what's going on with `0` and `1`?).

**Comment by vkarpov15** [comment]
Checks whether `T[K]` is `any`, got it from this SO thread: https://stackoverflow.com/questions/55541275/typescript-check-for-the-any-type . Is there a better alternative to removing all function properties from a type?

Also, I'm not totally convinced there's any higher order reasoning here. Regardless of what generic parameter you pass to `Model<T>`, `Model<T>` will always have a `something` property that's a string, so why does it not end up in the `SerializableProperties` type?

**Comment by RyanCavanaugh** [comment]
>  Regardless of what generic parameter you pass to Model<T>, Model<T> will always have a something property that's a string, 

That's not true:
```ts
type MyThing = CommonInterface<unknown> & { something: Function };
type Test = SerializableProperties<MyThing>;
declare const p: Test;
p.something
```

You can make an argument about what kind of legal intersections exist, but *that is the higher-order argument*.

**Comment by vkarpov15** [comment]
Ok, that makes sense. I will close this issue, thanks for the information :+1:
