### ISSUE TITLE
Template string literals now participate in occurrences highlighting

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/TypeScript#43292]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.2+

**Search Terms**
- documentHighlights

---

The new release has added the feature in the screenshot. I looked through all of the release notes and couldn't find a single mention of it. All it does is reduce the readability of the string I am looking at. How do I turn it off? Why don't the release notes mention it? I can't even find a commit or pull request linked to it.

<img width="524" alt="Screen Shot 2021-03-05 at 9 40 08 pm" src="https://user-images.githubusercontent.com/960753/110111038-6afa8b80-7dfb-11eb-926c-838e6e2c1970.png">

**Comment by mjbvz** [comment]
Moving this upstream for feedback from the TypeScript team. I believe this was added in TS 4.2.

The new highlighting is consistent with how `'` and `"` string are highlighted

**Comment by RyanCavanaugh** [comment]
@mjbvz what's being requested here?

**Comment by mjbvz** [comment]
Just a point of user feedback on the new behavior

We could consider disabling this for multiline template strings or for strings where there is only a single occurrence

**Comment by shwao** [comment]
+1 for "disabling this [..] for strings where there is only a single occurrence". Does not make much sense to highlight the complete string in my opinion.

**Comment by dncrews** [comment]
I don't know if there's a better way to ask for this to get priority other than commenting. It has been frustrating to no longer have `occurrencesHighlight` functionality.

For me, this occurred because my GraphQL type definition files are exported from a .ts file. This functionalty used to work even in those files, but with this change, the functionality has to be disabled.

**Comment by andrewbranch** [comment]
Happy to accept a PR. Shouldn’t be too difficult.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by enisdenjo** [comment]
This started happening again to me, I had to `editor.occurrencesHighlight: off` in VSCode.

- typescript@5.8.3
- VSCode@1.101.2
