### ISSUE TITLE
Newly created JS files are not added to configured project until server restart

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#43290]
# Bug Report

### 🔎 Search Terms
js inferred project restart server

### 🕗 Version & Regression Information

Tested on 4.3.0-dev.20210316
- I was unable to test this on prior versions because that seemed like it would take a lot of time

### 💻 Code

tsconfig.json:

```json
{
  "compilerOptions": {
    "lib": ["es2020"],
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "noEmit": true,
    "types": ["node"]
  }
}
```

Open project, then add a new JS file.

### 🙁 Actual behavior

It doesn’t get checked for errors, and can’t see globals declared in other JS files in the project. TS Server log shows the file added to a new inferred project instead of the configured project. After restarting TS Server, the file is in the configured project as expected.

### 🙂 Expected behavior

The file gets added to the configured project.

**Comment by MartinJohns** [comment]
That sounds like #43280.

**Comment by andrewbranch** [comment]
Touché @DanielRosenwasser, you got me good, now I’ve gone and duplicated myself

<img width="639" alt="image" src="https://user-images.githubusercontent.com/3277153/111517831-ba518d80-8712-11eb-85c4-c1b659df2cdf.png">
