### ISSUE TITLE
Not working optional chaining on global variables / optional DOM APIs is not detected

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#43295]
# Bug Report

### 🕗 Version & Regression Information

I see this in nightly and 4.2.

### ⏯ Playground Link and💻 Code

```ts
// Runs without exception in runtime (with secure and insecure origin)
window.caches?.has('anything');
// Runs exception in runtime (with insecure origin)
caches?.has('anything');
```
[Playground Link](https://www.typescriptlang.org/play?ts=4.2.3#code/PTAEHUHsCcGsGdQEsB2poFcUBckFsBTUACgHclsALUeAgYw2iIEMUATZFWhp0GJAOaoAlAFgAUOXaRSAOjrM6lAvAD8sys3jEA5KwCeVVAJ3CA3BJCgAIpBWgUkbKFIxYndFlyES5Kp25GIn4hFDFxBSUVdU1tPRRDSmNTMyA)

### 🙁 Actual behavior

TS compiles without problems.

### 🙂 Expected behavior

TS should have warned me that a browser (without a secure context) can throw and the optional chaining will not save the day:
```
> caches?.has('anything');
VM262:1 Uncaught ReferenceError: caches is not defined

**Comment by RyanCavanaugh** [comment]
We don't have any concept of "possibly-present global variable" and don't intend to add this.

**Comment by HolgerJeromin** [comment]
I am fine with that. Thanks for the quick answer.
