### ISSUE TITLE
jsdoc @template not recognized as generic

### ISSUE THREAD

**Issue by dominikschreiber** [microsoft/TypeScript#43297]
# Bug Report

The [JSDoc Reference](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#template) mentions `@template` as a supported JSDoc parameter, to type generic functions. However, this type is never read and instead resolves to `any`. E.g. in the example from the reference

```javascript
/**
 * @template T
 * @param {T} x - A generic parameter that flows through to the return type
 * @return {T}
 */
function id(x) {
  return x;
}

const a = id("string");
const b = id(123);
const c = id({});
```

I'd expect

- `a` to be of type `"string"`,
- `b` to be of type `123`, and
- `c` to be of type `{}`.

However, they all have type `any`. This happens in the TS playground for all supported version.

*Is `@template` just not supported and the documentation has to be updated?*

### 🔎 Search Terms

- @template
- jsdoc
- generic function
- generics

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about *generics*.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUoyyqYBOmykA3rgL6QAekAtJAIKQDmiAdoiQJYBjSMTLJESEpHgALbJABm6APYB3AM7SZJZQFcOM6cq2JIJCbpLdpAT1SICcc-EvXqNAsHALd3QfH5la34AEwAKegBKKigzCysGAG5wD3BBIPV4SExIAF5IULCAIkyBbg4iyOT07kzIACM8gvCARgAmAGYqtIys4XzCyhoqoA)

### 💻 Code

The sample code taken from the JsDoc Reference:

```ts
/**
 * @template T
 * @param {T} x - A generic parameter that flows through to the return type
 * @return {T}
 */
function id(x) {
  return x;
}

const a = id("string");
const b = id(123);
const c = id({});
```

### 🙁 Actual behavior

`a`, `b` and `c` all have type `any`.

### 🙂 Expected behavior

`a` should have type `"string"`, `b` should have type `123` and `c` should have type `{}`. Because the `id()` function returns the type it is called with. This does work with pure typescript (see [Playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAJgJgDwBUB8AKADwC5EsBKErRAbwChFEAnAUyhEaQIG5aBfW2hAQBnKIgCGiALzJ0eAESjGMMAHN5ZHkLCjEAI2my0eAIxoAzJsEixEQ6mPVemoA)).

**Comment by IllusionMH** [comment]
It works, but only in .js files or when you enable JS language mode [Example](https://www.typescriptlang.org/play?useJavaScript=true#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUoyyqYBOmykA3rgL6QAekAtJAIKQDmiAdoiQJYBjSMTLJESEpHgALbJABm6APYB3AM7SZJZQFcOM6cq2JIJCbpLdpAT1SICcc-EvXqNAsHALd3QfH5la34AEwAKegBKKigzCysGAG5wD3BBIPV4SExIAF5IULCAIkyBbg4iyOT07kzIACM8gvCARgAmAGYqtIys4XzCyhoqoA)
![image](https://user-images.githubusercontent.com/1312662/111618950-a890e880-87ed-11eb-93f8-5e3cfa6799cb.png)

TS files/language mode ignore types in JSDoc
