### ISSUE TITLE
Visual Studio Time Machine?

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#4329]
I was editing a .ts file and had it stopped accepting input in that file. I edited it externally and went back to VS and the changes I made got automatically read in. Things worked well for a while but the same symptom appeared so to be safe I close the .ts file in VS 2015 and reopened it and found that I was editing a version from a few ours ago?

WTF?

This may be a weird warp in space time and may be a one off. But have others seen this. In the past I have had problems with multiples copies of a .ts file in VS stepping on each other so may be an extreme version of that glitch.

**Comment by S-YOU** [comment]
Have you tried closing that file and "Refresh" button from Folder tree?

**Comment by BobFrGit** [comment]
Yes and looked at it in the file system -- very strange. I went back to a two hour old backup copy and redid my program. But found no way to recover the file.

**Comment by RyanCavanaugh** [comment]
Never heard of this before. If you find a way to reproduce this, please let us know!

**Comment by BobFrGit** [comment]
I don't know how to give a repro but I keep finding that when I click on an error message and get positioned in the code it's a copy of the TS code and my keyboard input gets ignored. So I close the window and then find the one with the editable copy of the code. I ran into a year or so ago first working with TS (maybe in VS2012?) and thought it had gotten fixed.

**Comment by mhegazy** [comment]
is it a specific file/error that cases this behavior? is there a consistent set of steps that land you in this situation?

**Comment by BobFrGit** [comment]
That's the challenge ... the only consistent symptom is seeing the file a second time in VS2015. What information can I provide for you next time it happens?

**Comment by mhegazy** [comment]
>  the only consistent symptom is seeing the file a second time in VS2015. 

does this mean that there are two instances of the file opened in editor at the same time? or you have closed the file and then opened it again?

**Comment by BobFrGit** [comment]
It means that the TS support has opened a second view or instance on the file -- this is the confused part in the past changes in one wouldn't necessarily be reflect in the other. Next time this happens I'm going to change it externally and see which, if either or both, get reloaded.

**Comment by mhegazy** [comment]
One thing that we have seen before is the file path having different slashes. It was triggered by clicking on an error in the error list, that has a "Build" prefix. 
if/when you see a file opened twice, can you capture the full file path from each tab, and capture the error message that you clicked on to open the file, and ideally the build log that generated the error.

**Comment by BobFrGit** [comment]
Sounds right -- will watch out and report it when it happens again.

**Comment by mhegazy** [comment]
@BobFrGit has this happened again recently?

**Comment by BobFrGit** [comment]
Haven't seen it for a while so maybe it magically fixed itself. ... or I hope it did.

**Comment by mhegazy** [comment]
:) do not really believe in magic. closing for now, but please reactive if you see it again.
