### ISSUE TITLE
Function refactor removes comment

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#43298]
TS 4.2.2 and 4.3.0-dev20210316
```
const foo = () => // comment
1
```
<img width="300" alt="Code_2021-03-18_17-35-12" src="https://user-images.githubusercontent.com/30108880/111662581-557c5d00-8810-11eb-8bd7-acb8a9529ec3.png">
<img width="157" alt="Code_2021-03-18_17-35-21" src="https://user-images.githubusercontent.com/30108880/111662588-57462080-8810-11eb-8b2b-0ce4d9093010.png">

**Comment by hi-rustin** [comment]
I'd like to try to fix it.
