### ISSUE TITLE
New Error: union narrowing

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#43300]
# Bug Report

### 🔎 Search Terms

union, narrowing

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210316#code/CYUwxgNghgTiAEYD2A7AzgF3gBzgMwEsAPAGQMwC55MYCUBzAbQF0BuAKFElgWXSxpUadeh3YQQWABYEMABXzEhGWg3gAfeCgCuECPAC8W3RDG4QhUuQwA6NEgC2IABTnLAZRWGAfPADe7PCIqJjUGLAYnjCGYTB2EARgLgAMADQ4ikRRNhIMGFIAlBxBBHjwzpgRUYYGRm7EUQX+gUHwMvKZMfVZKsWtcBjaMCjwKtogfQC+LQNDI3hQEGgT7JNF7Oyl5e0KFsTwAIS1xnpNAUF8oQCOMeet3VQ7maktQQBui+PKcWgJSc5PPZEA45EB5QovIKTDjTVpw+BAA)

### 💻 Code

Reduced from https://github.com/ant-design/ant-design

```ts
declare const prefixList: string[];
declare const str: string;

let hitPrefix: string | null = null;

prefixList.some(prefixStr => {
  const startStr = str.slice(0, prefixStr.length);
  if (startStr === prefixStr) {
    hitPrefix = prefixStr;
    return true;
  }
  return false;
});

if (hitPrefix !== null) {
  const q = {
    prefix: hitPrefix, // type here was and is `never`
    value: str.slice(hitPrefix!.length), // type here used to be `string | null` but is now `never`
  };
}
```

### 🙁 Old behavior

`hitPrefix` was `never` as a standalone expression but `string | null` when dotted into.

### 🙁 New behavior

`hitPrefix` is `never` in both contexts (more consistent).

### 🙂 Expected behavior

`hitPrefix` is `string`, since it may have been set in the `some` call above and the null check rules out the alternative.

**Comment by amcasey** [comment]
I think @ahejlsberg has been looking at union narrowing.

**Comment by ahejlsberg** [comment]
The change here appears to be that in `hitPrefix!.length`, when `hitPrefix` was previously narrowed to `never` we'd revert to the declared type whereas now we keep the `never` type. I'm not sure which PR changed this, but our new behavior definitely seems preferable from a consistency standpoint.

**Comment by amcasey** [comment]
@ahejlsberg It's definitely more consistent, but how come neither behavior accounts for the possible assignment of the variable in the lambda?  (We can't know that the lambda will run, but can't know that it won't either, AFAICT.)

**Comment by ahejlsberg** [comment]
The reason we don't account for the assignment in the lambda is #9998.

**Comment by amcasey** [comment]
If not considering the possible assignment is by-design, then the new error is an improvement.
