### ISSUE TITLE
jsxImportSource is too eagerly parsed

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#43310]
# Bug Report

### 🔎 Search Terms

jsxImportSource

### 🕗 Version & Regression Information

- `4.3.0-dev.20210319`
- `4.2.3`

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about jsxImportSource

### ⏯ Playground Link

Not useful since the playground can't squire the types. I've created https://github.com/eps1lon/emotion-jsx-import-source-typescript instead

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJgBOEWAxksMWaoigFZQAeKUpA9gA4EopgCqCLAHcsxMGwBmYAAINGASQC2HNoSQBlNgFdCpAiGAAoUOFlMlKtZp16ZERWyRw2CSiXJgDhuMtVIwAN5gpFBQYAC+YBKEbIpgAETS9o7OrlTk8QDchoYQjJb+aBASWFow-hJaCOSpYADCsSoIEMgAFACUgYZgRBBIOghgrd09YAA8iBxaSCOjwaEAvAEhUAAGs3PBbDCqAFy9aNmbYKvhG8AAfCPt2WdAA)

### 💻 Code

```tsx
/* eslint-disable react/react-in-jsx-scope -- Unaware of @jsxImportSource */
/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";

export default function Component() {
  return (
    <input
      css={css`
        color: red;
      `}
    />
  );
}

```

### 🙁 Actual behavior

Compiler fails with `Cannot find module '*//jsx-runtime' or its corresponding type declarations.ts(2307)`

### 🙂 Expected behavior

Passes

### Context

I've identified the bug and can easily change it (by referring to `jsxImportSource` instead of `@jsxImportSource`) but the behavior is still unexpected and opaque. I suspect that altering the parser to not be as eager might be difficult. Instead an additional hint in the error message which line the compiler used to find the `@jsxImportSource` might be sufficient?

**Comment by weswigham** [comment]
Babel also parses both lines as `@jsxImportSource` pragmas, where we differ is that we prefer the first, while babel prefers the last. I've opened #43351 to align our preference with babel.
