### ISSUE TITLE
Reference to method vs method being invoked reports different types

### ISSUE THREAD

**Issue by skeie** [microsoft/TypeScript#43311]
# Bug Report

### 🔎 Search Terms

- invoke method
- Reference to method vs method being invoked reports different types
- method reference

### 🕗 Version & Regression Information

- Its the same behavior in every version I tried, and I reviewed the FAQ for entries about functions and reference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210316#code/KYDwDg9gTgLgBMAdgVwLZwKoCUAyBpYATwGc4BvAKDjmSgBsB5RYOAXjgCJbHmOAaKjXoAVAO4Q2nbmIgcKAXwoVQkWHADGERMXgBzYDAz1iALnKCA2gGsicAJaJMuAiQC6ZytWr6YABQCGMAAWZgAUYP6EdBAAJmYAysBQAG5JWMAAjsjAOsTWRK4WHBFREP4xHK4AlGwAfHA6UA66ANyC1KgGQbFmHD4ccAA+nJA6HG1ecEH+iDF0wOnEAPxh7V4RUP6opnCJKWmZ2bn5hIXFkdHllWs1rPWhobf1vlAQqHbEwAA8yIhWiBBRIhajVhr8YsAAGYOYAxCZweRteSSTxwCzYfBEYgAOm4TGA7nMkx8AWCYSenH8YDsAHo8bwBJNOsEepx+oJ5Iy0RiXDjpOJCajvAZSSE4KEyEI6DIAJIxBEUgAGVNp-IgNIAJGQ1XL5IquR0uqy+gY5NRFIilJDfuoYHYtHAfEY6KFBNwXGYeViuVkkoQApttgkkqkoOlfccYIQwMAIJCpS4ziVLhVXBQaqjNNp4JKSYEgnw4MzujFC9NZvNFgjJE7jBZ3QV4XngvCoAZaI4hXAImTHSL86FfVB-f5A8Qqgai0bS2ty3MFjkOUilCpoPAHDAkpD-OoWHtQ+GjjBSKj0c4sbj6PjBWs28RINpgAAhWKEDxFiAAIzs82dZkazQtHAAJQKg-h0H+DQwE0iC6Ai8LUMmZRxESkwft+8wrHAn4QBA8wzAh6x0IEkLQKgWEAbBhHUMgnzCMAqBgMRm6LA+nxYTheHAARayWua8JnpiJCXtKAoeLeORsc+r7-tBzRDMBaCfkkhFIeU4loVKsooZRrRrNQpGgYEWEoKgylQIRfHwQoFBAA)

### 💻 Code

In the playground link you will see this code: 

```
  getPath;
  return {
    path: getPath(queryParams),
    method,
    handleRes
  };
```

if you hover over the reference to getPath you will see this: 
![image](https://user-images.githubusercontent.com/1346122/111796695-b7989900-88c8-11eb-868e-61e70f5fd80c.png)

but if you try to hover over where the function is invoked you see this type:
![image](https://user-images.githubusercontent.com/1346122/111796776-cd0dc300-88c8-11eb-9b7f-6ac06529a3b2.png)

So the type changed from OR to AND when the function is being invoked
![image](https://user-images.githubusercontent.com/1346122/111797113-21b13e00-88c9-11eb-976c-4b635fc87e8a.png)

```

### 🙁 Actual behavior

The type change based on you invoke the method or if you have the reference to it
![image](https://user-images.githubusercontent.com/1346122/111797113-21b13e00-88c9-11eb-976c-4b635fc87e8a.png)

### 🙂 Expected behavior

From my understanding, it should always be OR (`|`), it should at least not change the behavior, it's still the same function :). But it might be that I'm doing something very strange

**Comment by MartinJohns** [comment]
Your function is one of two versions (or). When invoking the function the compiler can't know which version it is, so you need to provide arguments to satisfy all versions (and).

This is working as intended.

**Comment by skeie** [comment]
Thanks for the response @MartinJohns, that makes sense. I should probably ask this at stackoverflow, but since you've already understood the code, maybe you can explain it to me. But how could I model this so that it infer this based on `urlKey` ?

E.G: 

If you pass in `URLKeys.urlTwo`, how can you tell typescript that it should use that type to lookup in `ServerRequests` ? E.G `ServerRequests[typeof urlKey]["payload"]`

![image](https://user-images.githubusercontent.com/1346122/111865784-52e14b00-8969-11eb-88d9-dace2ec222d4.png)


Thank you again @MartinJohns  🙏

**Comment by MartinJohns** [comment]
> But how could I model this so that it infer this based on `urlKey`?

You can't. This would require #27808.

**Comment by skeie** [comment]
Thank you so much!
