### ISSUE TITLE
Using imported modules in the VSCode debug console

### ISSUE THREAD

**Issue by Christilut** [microsoft/TypeScript#43328]
# Bug Report

When using the VSCode Debug Console when the execution is paused, I get this for everything that is imported:
`Uncaught ReferenceError: Foo is not defined`

This is on a simple piece of code like this:
```ts
import Foo from 'foo'

Foo.bar()
```
When I run this in the debug console: `Foo.bar()`

I can work around it in the debug console like this:
`_Foo.Foo.bar()`

In the closure scope, all the imported modules are shown and that's where I got the `_Foo` from.

Seems like when running Typescript, this should just work in the debug console?

### 🔎 Search Terms

"debug console"

### 🕗 Version & Regression Information

Node 12.20.1
VSCode 1.54.1
Typescript 4.1.2

### 💻 Code

Tsconfig:
```json
{
  "compilerOptions": {
    "target": "ES2019",
    "module": "commonjs",
    "strict": true,
    "outDir": "dist",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strictPropertyInitialization": false,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*"
      ]
    },
    "lib": [
      "dom"
    ]
  },
  "include": [
    "src/**/*",
    "tests/**/*.test.ts"
  ],
  "exclude": [
    "snippets/**/*"
  ]
}
```

### 🙁 Actual behavior

Getting an error in the debug console when copy pasting a piece of source code with imported module that should be able to run as is.

### 🙂 Expected behavior

Every piece of source code where the debugger is currently paused, should be runnable in the debug console.

**Comment by Christilut** [comment]
This issue is reported [here](https://github.com/microsoft/vscode-js-debug/issues/393) as well, but it might be more Typescript related.

**Comment by IllusionMH** [comment]
See existing https://github.com/microsoft/vscode/issues/12066 and https://github.com/microsoft/TypeScript/issues/9627
