### ISSUE TITLE
Deduced type array indexed value does not include `undefined`

### ISSUE THREAD

**Issue by craxal** [microsoft/TypeScript#43321]
# Bug Report

### 🔎 Search Terms

array, index

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about array indexing.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEBUE8AcFNQPYDNQAMCGAnT7KtAJYDOaAdgK4C2ARrJgNoC6+6JsAHnAMYAusAJgDoAUABtYPUFhyRQAXlD0AjABpQAJjUBmRgG5hwkBBjxkadC1L801fMTJVamVGoDuAC1ilCkou4Tkota0DjR0oAA+oORWsEgEpAKoIuKS6PJS2Lj0ALRKemISoNQZ0tllkILipADmPO4FwlwIpEQI4lUINQAUqADk6H2EJAAkAN7oAL6oAJT6za3tsJ09-dRD9uPU03NAA)

### 💻 Code

```ts
// Type of `array` is `number[]` as expected.
let array = [1, 2, 3];

// Type of `a` and `b` is `number`, but their values are `undefined`.
let a = array[-1];
let b = array[array.length];

console.log(`'a' is ${a}`);
console.log(`'b' is ${b}`);
```

### 🙁 Actual behavior

Deduced types for variables `a` and `b` are `number` even though their values are actually `undefined`.

### 🙂 Expected behavior

Deduced types for variables `a` and `b` should be `number | undefined`. JavaScript lets you index arrays out of bounds and returns `undefined`. Therefore I think TypeScript should take this into account.

**Comment by MartinJohns** [comment]
You just need to enable the `noUncheckedIndexedAccess` compiler option.

**Comment by craxal** [comment]
@MartinJohns Ah, thanks. I didn't know that was an option. Are there plans to make that a default setting at some point?
