### ISSUE TITLE
Visual Studio - how to run TypeScript in io.js (not browser)?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/TypeScript#4333]
Hello, I have simple and non simple question. Can I run typescript through io.js, not web browser in VS environments? How to run compiled js instead of index.html?

**Comment by jesseschalken** [comment]
I'm not sure about Visual Studio, but running TypeScript through io.js or node is generally just a matter of compiling it with `--module commonjs` or `--module umd` and running `node` or `iojs` on the resulting .js file.

**Comment by acterhd** [comment]
I want try ecmascript 6 and these module system unavailable.

**Comment by acterhd** [comment]
I'm close.

**Comment by mhegazy** [comment]
io.js as well as node do not support the ES6 module system yet. So untill the support is available, you will need to compiler with `--m commonjs`.
