### ISSUE TITLE
helpers are emitted above import statements

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#43330]
# Bug Report

### 🔎 Search Terms
helpers emitted above import statements

### 🕗 Version & Regression Information
4.3.0-dev.20210316

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1&ts=4.3.0-dev.20210316#code/JYWwDg9gTgLgBAMwM6KhEcDkzMG4BQAxhAHZIQA2ApgHQUQDmAFMgJRGlLzAnDwC8cAN4BDAFxwAjAAYANHABGEmFACuVAL4Fq8ElQDuAeQUArOIKE0rPPvMISSqihS34gA)

#### source
```ts
import fs from 'fs';
console.log(fs)
const init = {a: 10, b: true};
let newObj = {...init, c: null};
```
#### compiled to
```js
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
import fs from 'fs';
console.log(fs);
var init = { a: 10, b: true };
var newObj = __assign(__assign({}, init), { c: null });
```

### 🙁 Actual behavior
`__assign` helper is defined above the `import` statement

### 🙂 Expected behavior
`import` statements should be at the very top, as they aren't allowed to be defined anywhere else

**Comment by MartinJohns** [comment]
> as they aren't allowed to be defined anywhere else

According to a comment in #34900 (same issue as yours) this is not true.

**Comment by DetachHead** [comment]
oops, i noticed that comment right after opening this but forgot to close it

**Comment by DetachHead** [comment]
some additional info that may be useful to anyone else that runs into this problem: `create-react-app` projects have the ESlint rule `import/first` set up to prevent compilation.
