### ISSUE TITLE
TS2454 - Variable is used before being assigned error-  when variable is assigned inside a if condition and accessed in another if block with the same condition

### ISSUE THREAD

**Issue by ar-daniel** [microsoft/TypeScript#43349]
# Bug Report

### 🔎 Search Terms

TS2454 - Variable 'var_a' is used before being assigned.
multiple if statements with same condition
error when variable is assigned inside a if condition and accessed in another if block with the same condition

### 🕗 Version & Regression Information

- This is the behaviour in the following version I tried ( 3.9.9, 4.1.5 & 4.2.3) , 
- and I reviewed the FAQ for entries about _TS2454 and variables being used before assigned.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

![image](https://user-images.githubusercontent.com/58593522/112161286-01f38000-8c11-11eb-9d5c-6d3dc929d9fb.png)

### 💻 Code

```ts


function doubleConditionalFunc() {

    let var_a: string
    let var_b: string
    let var_c: string

    const conditionCheck: boolean = true

    if (conditionCheck) {
        var_a = 'A'
        var_b = 'B'
    } else {  // even if the else block is removed would have the same issue
        var_c = 'C'
    }

    if (conditionCheck) {   // same condtional check
        if (var_a) console.log(var_a)  // does log properly in the console
        if (var_b) console.log(var_b)
    } else {
        if (var_c) console.log(var_c)
    }
}

doubleConditionalFunc()

```

### 🙁 Actual behavior

when we declare a variable (without assigning any value to it)
and assign a value to it in a if condition 
and later access the variable in another if block with the same condition.
error ts2454 occurs - of variable being used before being assigned.
the error present even if there is no else block 

this is valid js code and also works when compiled

### 🙂 Expected behavior

compiler should be able to pick up the scenario/ the condition prior to where the variable is accessed, that whether the variable is already assigned in the same program flow.

###  Solutions checked 
https://github.com/microsoft/TypeScript/issues/42143
the use case is not the same as the above mentioned  assignment to variable happens with different set of if conditions and different in where it was accessed.
however would not prefer to use the solutions there because -
Assigning random or null values to variables in other branch would add verbose code 
and miss the type check if had access the variable in a block not meeting the condition, 
same with the case assigning a default value at the time of declaration, type check would not work in blocks not meeting the condition, 
( would prefer ts complier to warn to not use variables in those cases.)

one could argue to move the logic into the same if block, however in longer code blocks combining them is not really working out due to need of maintainability and readability

**Comment by MartinJohns** [comment]
Simplified example:

    const c = true
    let f: string
    if (c) f = 'test'
    if (c) f.toLocaleLowerCase()

**Comment by ar-daniel** [comment]
In cases where we have single controller function needed to handle different use cases and each having separate set of variables, the assignment happens case wise in the beginning of the controller and logic comes later which are case wise varying different with case, we would need such a flow. We could say to reuse the same variables but the list of variables are named same across functions (even though scoped for those methods) eg. in react-redux world the state management logic is split in reducers, action creators, action types, sagas and application component. It quickly becomes confusing if the variable naming themselves don't provide insight on what its for. 
Though in the examples its trivial no one would split them. I've explained at the end of the issue, initializing with some value -type check would not throw error (and would simply pass) in blocks not meeting the condition. In large code blocks its easy to make use of the incorrect variables (by mistake) in case/ condition blocks not meant to be.

**Comment by RyanCavanaugh** [comment]
I could see writing it this way if you had some common logic between the two `if` blocks you wanted to run, but it seems like this pattern must be pretty rare in practice. The control flow analyzer isn't really set up to find these sorts of parallelisms and it doesn't seem worth the perf/complexity cost to fix something that doesn't come up that often.

**Comment by ar-daniel** [comment]
Ok, I understand if there is lot of work involved to make this fix. You could consider fixing if there is any related work that comes up later and ends up solving this issue as well. 
In the end, Its valid javascript code not able to do in typescript. We will improvise then in our code.

**Comment by MartinJohns** [comment]
@originbeh TypeScript has no way to track what statements may throw errors, and which may not. So if any code in the `try` block before or during the assignment fails it will leave `a` uninitialized. **We** know no error can be thrown here, but like I said: The compiler doesn't track this.

**Comment by matthew-e-brown** [comment]
> And I honestly see no reason to ever write code like this. If I really need this, I'd just initialize the variables with a value.

In my case, the code I have looks something like this:

```ts
let direction: Vec3;

if (shiftIsPressed) {
    direction = doComplicatedVectorMath();
}

for (const obj of allObjects) {
    if (shiftIsPressed) {
        obj.translate(direction);
    }

    if (otherKeyPressed) {
        obj.doSomethingElse();
    }
}
```

I don't want to run `doComplicatedVectorMath()` once for every one of my 2,500 objects, so I take it out of the loop. I also only want to do it if the user is holding the right key, so I put it into an `if`-statement of the same condition.

Of course,

> and it doesn't seem worth the perf/complexity cost to fix something that doesn't come up that often.

This is still totally true; I have to acknowledge that this is pretty uncommon, but I thought I'd throw my example onto the stack nonetheless. In my case, I fixed it by simply setting `direction: Vec3 | null = null`, and then using `direction!` in the second block. But it would be nice to not have to use `!`!

**Comment by cleytonchagas** [comment]
I still have this problem...

**Comment by Aaron46** [comment]
If someone still has this issue, what worked for me was to tell typescript that the let is possibly undefined as such:
`let f: string | undefined`
My assumption is that TS is won't complain now that this doesn't need to be set to a string and can be expected to be undefined

**Comment by BugraAkdogan** [comment]
Typescript has no way of knowing if a value is assigned to an uninitialized const and warns you next time you try to access it.

all you have to do is give these an initial value/state.

let var_a: string = ""
let var_b: number = 0
let array_c: number[ ] = [ ] 

etc
