### ISSUE TITLE
Pattern Matching on types

### ISSUE THREAD

**Issue by akkeshavan** [microsoft/TypeScript#43345]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Curently, it is hard to unravel union types during run-time. The most common hack is to use tagged union types. Pattern matching on types will  address this issue directly. 
## 💻 Use Cases
type Mytype = "a' | "b" | "c"
function foo(): Mytype

function caller( ): number {
     match(foo()){
        case "a"  => 1
        case "b"=> 2
        case "c" => 3
}

I would go so far as to say that even direct function overlaoding should be permissible.

type Mytype = "a' | "b" | "c";
function map (val: "a"){
  return 1
}  

function map (val: "b"){
  return 2
}  
function map (val: "c"){
  return 3;
}  

The pattern matching for  union type values must be exhaustive.

The same technique can be used for subtyping based types, not just literal types.

**Comment by MartinJohns** [comment]
> [x] This could be implemented without emitting different JS based on the types of the expressions

Would you mind explaining how you think this could work without emitting different JS based on the type of expressions?

> List of keywords you searched for before creating this issue.  Write them down here so that others can find this suggestion more easily and help provide feedback.


You forgot to fill out this part of the issue. There is an existing issue about pattern matching already.UU

**Comment by akkeshavan** [comment]
Since this can be achieved with tagged union types with swicth statment, wouldnt this be a syntactic sugar for the same, with tagged values being generated by TS internally? Why would this require newJS to be emitted. 

Anyway, if it is a no go from TS team.. fine.

**Comment by MartinJohns** [comment]
> Why would this require newJS to be emitted.

It would require different JS to be emitted based on the type of the expression. Best example is your overload functionality: **Somewhere** the check "is this type A?" would have to be done, and this check must be different depending on the type.

**Comment by akkeshavan** [comment]
I see. Typescript function overloading doesn't support  typebased overlaoding, otherwise it would have been just a simpe invocation of th same code gen with limited number of types., only number of arguments based one. It will require emitting new code a function table + selection. My bad.

If we drop the function overloading , can you consider it?

**Comment by RyanCavanaugh** [comment]
That's still type-directed emit, which is out of scope

**Comment by akkeshavan** [comment]
Don't get it.  match(x) { }  => switch(x){} with compile time checks for exhaustiveness of union types--  why does it need to emit new code? Isnt it just  syntactic sugar over the existinng switch()..  you are only checking whether the match is exhaustive ( apure front end job for the compiler.)

I understand that you guys a had rejected pattern matching as a feature earlier. But the lack of it makes the language unwieldy especially  while using type level features.

**Comment by akkeshavan** [comment]
Never mind.

Found better alternatives to Typescript.
