### ISSUE TITLE
Module resolution should not succeed but does

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#43342]
a.ts
```ts
export {}
```

b.ts
```ts
import "BAD/../../a";
```

node_modules/
Present but empty

Expected: import fails to resolve
Actual: import resolves because we look in `node_modules/BAD/../../a`, which simplifies to `a`.

The path normalization in question happens [here](https://github.com/microsoft/TypeScript/blob/462271854d68e9058c464f7fb8afa357376f934b/src/compiler/moduleNameResolver.ts#L1308).

**Comment by amcasey** [comment]
Maybe we need to normalize the path _before_ checking if it's relative?

**Comment by amcasey** [comment]
I suppose there's a tiny chance this is desirable, even if it appears to be happening by accident.  @sheetalkamat ?

**Comment by amcasey** [comment]
On further reflection, the is-relative-path check probably needs to check path components after the first one.

**Comment by sheetalkamat** [comment]
I dont think this is issue with module resolution.. Node works in similar way. If you make those file at runtime as js files and run them it works
```
c:\temp\test>type a.js
module.exports = { a: 10};
c:\temp\test>type b.js
const r = require("BAD/../../a");
console.log(r);
c:\temp\test>dir node_modules
 Volume in drive C is OSDisk
 Volume Serial Number is F41A-DBC9

 Directory of c:\temp\test\node_modules

03/23/2021  01:40 PM    <DIR>          .
03/23/2021  01:40 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  689,911,324,672 bytes free

c:\temp\test>node b.js
{ a: 10 }
```.

**Comment by amcasey** [comment]
Well, now I'm sad.
