### ISSUE TITLE
Tooltip on private fields not showing the correct type after narrowing

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [microsoft/TypeScript#43346]
# Bug Report

### 🔎 Search Terms

private field, class, narrow, narrowing

### 🕗 Version & Regression Information
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210316#code/MYGwhgzhAEAqCmEAuBhcVoG8CwAoaB0AxAA4BOAlgG5hLwAKZA9ifGUgJ4Bc0ylAdgHMA2gF1oAH2j8AriBABuPIWgkZAIxAVgjFm048+FIWMnS5ivMsLAm-PjOBImZABQBKLNZUEkACwoIADpSSho6XVZ2DmgAXnN5JXwfXwDgtU1tSP0Y+NlE72gAXytk30QkAFl4fyYAEw8vMp8KADNoV39AkPJqWgZmKM44vIt3QpSCMhqZMn4kyeg2jq70jS0dQZyRhJBx5sXppFn50sXVnrD+7OiFaAB6e94kARFxKXyQCcILjI2bzh3R7PV5iM6TWz2JDQMBxaAXUJ9CJbW7fAhgIFPIwmUSFEq4IpAA)

### 💻 Code

```ts
class TestClass {
    #privateProperty: string[] | null;
    publicProperty: string[] | null;

    constructor() {
        this.#privateProperty = null;
        this.publicProperty = null;
    }

    testMethod() {
        if (this.#privateProperty === null)
            return;
        if (this.publicProperty === null)
            return;

        this.#privateProperty; // string[] | null
        this.publicProperty; // string[]

        const a = this.#privateProperty;
        a; // string[]
    }
}
```

### 🙁 Actual behavior

`this.#privateProperty` is `string[] | null` even after narrowing down the type from `if`. Also assigning `this.#privateProperty` to other variable fixes the type.

### 🙂 Expected behavior

`this.#privateProperty` should be `string[]` after narrowing down

**Comment by MartinJohns** [comment]
The type of `this.#privateProperty` is narrowed to `string[]`. It's just the tooltip that reports the wrong type.
