### ISSUE TITLE
Generic Function parameters losing type inference when two parameters refer to same Generic type.

### ISSUE THREAD

**Issue by ivoiv** [microsoft/TypeScript#43355]
# Bug Report

### 🔎 Search Terms

functions generics losing type inference 

### 🕗 Version & Regression Information

4.2.3 to 3.3.3333

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics

### ⏯ Playground Link

[Function and Record - OK](https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEoA8AVFBTAHrDpACYDOKAFAJQoC8AfCgEo7SIBOx6ps78kAcwA0KAGJQ4SSPXoVgKBSgAO7REtIAuFAG95i-Zi2Yhe-QoCqWlm07oA1jgCeiUMxyxw7SJkdKcWehEAQ0hHelMUAF9gGl1osApdAy1qOkZEiP1SRABbHHEYVO0ohQB6UpQAYQ52VlgAOhRsWo8vchCURAAjACs6lAB3eFgACxQAcmy8guhxlAdHeojIqhN9Sx1MxSn8iS1xkfg5lHKqmrrGydzdmDnagEdweFriFCDyBeXgFaA)

[Function and Function - ERROR](https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEoA8AVFBTAHrDpACYDOKAFAJQoC8AfCgEo7SIBOx6ps78kAcwA0KAGJQ4SSPXoVgKBSgAO7REtIAuFAG95i-Zi2Yhe-QoCqWikoCG7GwFstLNp3QBrHAE9EoZjlhwdkhMLyUcLHoRG0gvehoGFAA3RHhiUxQAX2AaXWywCl0DKwTGQpQ8ah0srKoRMxQAekaUAEkYDnZWWAA6FGx4clIcIhQbchcOYhQAd3hYAAsUHj5BUhN9S2U7R3JEoobt+wdSHq8qw8vmto72Lrg+gEFoaBwlWHIATRQAK3AeND8HA9DLZTJUIA)

[Function and Generic Function - OK](https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEoA8AVFBTAHrDpACYDOKAFAJQoC8AfCgEo7SIBOx6ps78kAcwA0KAGJQ4SSPXoVgKBSgAO7REtIAuFAG95i-Zi2Yhe-QoCqW9AHVcBImRSZZEGFpZtO6ANY4AnoigzDiw4OyQmH5KODb0IgCGkH70NAwoAG6I8MSmKAC+wDS6BWAUugZa1HSMZbn6pIgAtjjiMFXa+WYoAPTdKADCHOyssAB0YhIopAAWiADuqPHkrpLIKHPT8NDTKMOh4eSJKIgARgBWI+vwsDsA5A3NrdC3KL5+o7l5VCb6lmiTaXKXX+MFGDxakzMvQGQxG43uTQhMBeM3m5HAShQS1e-mOQRWn2AXyAA)

[Function and extra Generic - ERROR](https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEoA8AVFBTAHrDpACYDOKAFAJQoC8AfCgEo7SIBOx6ps78kAcwA0KAGJQ4SSPREB1XASJkU2WivoVgKbSgAO7RLtIAuFAG8tOq5lOYhlq9oCqpihBimWbTugDWOAE9EUGYcWHB2SEwA3Rx0WRkUAENIAPoaBhQAN0R4YgcUAF9gGgtisAoLa1cMxkrHBpQAeiaUAGEOdlZYADoVFC7wyPIUlEQAIwArbpQAd3hYAAsUAHJSRABbHHEYFZR-AJ6Cq3Wtp2pzIoLCqnsrFzQJOkYzRqsWlABJGE7uvqcUAAbRCkHDkWAxfjCR4wFDwcgTaZwOYLZYCIg4PjQVY8PiCFYgKzFG5AA)

### 💻 Code

Function and Record - OK
```ts
function f<T extends () => Record<string, Function>>(
    props: {
        T: T,
        U: Record<keyof ReturnType<T>, any>
    }
) {
}

f({
    T: () => ({
        someFunc() { }  // Correct. T returns an object with 'someFunc' key.
    }),
    U: {
        someFunc: 'hi'  // Correct. 'someFunc' required as key
    }
})
```

Function and Function - ERROR
```ts
function f<T extends () => Record<string, Function>>(
    props: {
        T: T,
        U: (func: Record<keyof ReturnType<T>, any>) => void
    }
) {
}

f({
    T: () => ({            // Incorrect. T loses typing, returns object with generic 'string'.
        someU() { }
    }),
    U: func => {           // Incorrect. U loses typing, func is object with generic 'string'

    }
})
```

Function and Generic Function- OK
```ts
function f<T extends () => Record<string, Function>>(
    props: {
        T: T,
        U: <W extends T>(func: Record<keyof ReturnType<W>, any>) => void
    }
) {
}

f({
    T: () => ({
        someFunc() { }      // Correct. Func shown as function which returns an object with 'someFunc' key.
    }),
    U: func => {
        func.someFunc      // Correct. 'someFunc' shows up as key of func
    }
})
```

Function and extra Generic - ERROR
```ts
function f<T extends () => Record<string, Function>, W extends T>(
    props: {
        T: T,
        U: (func: Record<keyof ReturnType<W>, any>) => void
    }
) {
}

f({
    T: () => ({               // Correct. T returns an object with 'someFunc' key.
        someU() { }
    }),
    U: func => {           // Incorrect. U loses typing, func is object with generic 'string'

    }
})
```

### 🙁 Actual behavior

This is a bit of a complicated issue to explain and perhaps it's my own grasp of TypeScript that's bad, but I'm taking a shot with a bug report just in case.

We have a function that uses Generics to infer the types of it's parameters, a single object with keys T and U, where T is a function, and U refers to the ReturnType of T.

If U is an object, it's OK.
If U is a function, type inference for both T and U is lost. 
If U is a generic function, it's OK again.
If U refers to a generic type extending T, typing only for U is lost.

This kind of makes sense as intended functionality when I think more about it, perhaps it has something to do with a "depth limit" for inference. but I'm no guru.

**Comment by RyanCavanaugh** [comment]
I can't tell what defect you're trying to demonstrate here, or why these definitions are written this way. It seems like you're trying to write some declaration for `f` and running into problems, but haven't provided what should be allowed/incorrect calls to it

**Comment by ivoiv** [comment]
@RyanCavanaugh 

In short, why does this work fine
```ts 1-2
function f<T extends () => Record<string, Function>>(
    props: {
        T: T,
        U: Record<keyof ReturnType<T>, any> /* --- This line --- */
    }
)
```

but this makes TS lose all type inference for both T and U.
```ts

function f<T extends () => Record<string, Function>>(
    props: {
        T: T,
        U: (func: Record<keyof ReturnType<T>, any>) => void /* --- This line --- */
    }
)
```

Only difference is one is a Record, the other is a Function.

**Comment by RyanCavanaugh** [comment]
What do you mean "lose all type inference" ?

This works, for example:
```ts
function f<T extends () => Record<string, Function>>(
    props: {
        T: T,
        U: (param: Record<keyof ReturnType<T>, any>) => void /* --- This line --- */
    }
) {
    
}

function someFunc() { }

f({
    T: () => ({ x: someFunc, y: someFunc }),
    U: (param) => {
        param.x; // strongly-checked, cannot write param.z here
    }
})
```

**Comment by ivoiv** [comment]
Hm, it appears to be syntax related.

The following 3 syntaxes are pretty much equivalent, but TS doesn't seem to understand the last one very well.

```ts
function someFunc() { }
T: () => ({ x: someFunc, y: someFunc }), // Correct - y and x inferred as keys

T: () => ({ x: () => {}, y: () => {} })  // Correct - y and x inferred as keys

T: () => ({ x() {}, y() {} }),           // Incorrect - type inferred to 'string'
```

What is interesting is that if you change the type for U like this, it works with all 3 examples.

```ts
        U: (param: Record<keyof ReturnType<T>, any>) => void 
        
        /* changed to */
        
        U: <V extends T>(param: Record<keyof ReturnType<V>, any>) => void 
```

You can see the first U example [here](https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEoA8AVFBTAHrDpACYDOKAFAJQoC8AfCgEo7SIBOx6ps78kAcwA0KAGJQ4SSPXoVgKBSgAO7REtIAuFAG95i-Zi2Yhe-QoCqWlm07oA1jgCeiUMxyxw7SJkdKcWehEAQ0hHelMUAF9gGl1osApdAy1qOkZEiP1SRABbHHEYVO0ohQB6UpQAYQ52VlgAOhRsWo8vchCURAAjACs6lAB3eFgACxQAcmy8guhxlAdHeojIqhN9Sx1MxSn8iS1xkfg5lHKqmrrGydzdmDnagEdweFriFCDyBeXgFaA) and the second generic one [here](https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEoA8AVFBTAHrDpACYDOKAFAJQoC8AfCgEo7SIBOx6ps78kAcwA0KAGJQ4SSPXoVgKBSgAO7REtIAuFAG95i-Zi2Yhe-QoCqW9AHVcBImRSZZEGFpZtO6ANY4AnoigzDiw4OyQmH5KODb0IgCGkH70NAwoAG6I8MSmKAC+wDS6BWAUugZa1HSMZbn6pIgAtjjiMFXa+WYoAPTdKADCHOyssAB0YhIopAAWiADuqPHkrpLIKHPT8NDTKMOh4eSJKIgARgBWI+vwsDsA5A3NrdC3KL5+o7l5VCb6lmiTaXKXX+MFGDxakzMvQGQxG43uTQhMBeM3m5HAShQS1e-mOQRWn2AXyAA)
