### ISSUE TITLE
Format on type incorrectly formats code when pressing enter or ; after closing bracket

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#4335]
Example: type foo(<enter>bar,<enter>arg

now move curso to next line behind the closing ). Code looks like this (. represents a space)

foo(
....bar,
....arg
)<cursor>

Now press enter or insert ;

You get

foo(
....bar,
....arg
....)

You can reproduce in VSCode 0.7.0 with the following editor settings:

{
	"editor.tabSize": 4,
	"editor.insertSpaces": true,
	"editor.formatOnType": true
}

**Comment by mhegazy** [comment]
I believe this is fixed in latest. can you give it a try and reactivate if this is not the case.
![formating](https://cloud.githubusercontent.com/assets/8000722/9311822/c2a6ed82-44cd-11e5-8936-482bf8310e02.gif)
