### ISSUE TITLE
Reduce collection without initialValue and type arguments not working as expected

### ISSUE THREAD

**Issue by murphybob** [microsoft/TypeScript#43360]
# Bug Report

Typescript is in a bistable error state where it I provide 2 type generics to reduce it tells me to use 1, if I use 1 it tells me to use 2. It also doesn't seem to be respecting the generic arguments to reduce when calculating the reducer param types.

(Note: I fully understand that I am probably doing something dumb and typescript is almost certainly not at fault, I apologise in advance if/when this proves a boondoggle of the highest regard)

### 🔎 Search Terms

reduce initialValue

I don't _think_ this is covered by https://github.com/microsoft/TypeScript/issues/36554 but I wasn't sure.

### 🕗 Version & Regression Information

- I tried this on all the 4.x versions available on the playground.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAUwB4AdlgM4wG7IDCcAtugIYBOM2CAFOQFyLZTVgDmANIgEbOt2HAJTNecOABtk5JAG8AUIkSVkUEJSTlEAXj18FAXwULQkWAkQALctgBKyTOSjY6EKcwCClSuQCeADyCMJwAfKJ8EtKyiIrKquqaiO6SAHSqACYgEMhBbCEciAA+iGwgyDzBnMWllOWhdHSoAIw8qABMwrqhsUrKKmoaSC26+mXIxSVomDj4RKQU1LRgTa2IHV1FJR19hl16OrXlRibuOFLIqZJwHHQ29o4yLnQA2gBE5G88b7xfiG8QN4AXWEwgUZ1o0iuNzutgcTme70+31+KL+AOBoIUQA

### 💻 Code

```
function expensiveComparison(a: string, b: string): boolean {
  return a === b
}

function hasRepeats(col: Array<string>): boolean {
  return col.reduce<string | true, string | true>((x1, x2) => {
    return x1 === true || expensiveComparison(x1, x2) || x2
  }) === true
}

console.log(hasRepeats(["a", "b", "c"]))
console.log(hasRepeats(["a", "b", "b", "c"]))
```

### 🙁 Actual behavior

I'm honestly not sure why it's not working or quite how to interpret the error messages, but it seems TS is unwilling to accept that the reduce accumulator may be of a type other than the initialValue despite my generic arguments to `reduce`.

2 type args
![image](https://user-images.githubusercontent.com/1550045/112308149-b9cc7000-8c99-11eb-9e0f-7ab881c2700e.png)

1 type arg
![image](https://user-images.githubusercontent.com/1550045/112308210-ca7ce600-8c99-11eb-9fed-a5934b58e1ac.png)

### 🙂 Expected behavior

x1 (and x2) to be the union type `string | true`

**Comment by MartinJohns** [comment]
The error is fairly misleading and hides a fundamental issue that you provide two type arguments, when the function just accepts one:

![image](https://user-images.githubusercontent.com/5269069/112309623-d5d50f00-8ca3-11eb-86f8-dde1c03ebfcf.png)

When you fix this, you get the error you see as well, about no `initialValue` being passed. You're using the generic overload of `reduce`, where `initialValue` is **not** optional. So you need to provide this argument.

![image](https://user-images.githubusercontent.com/5269069/112309876-306e6b00-8ca4-11eb-81fc-8e3bae371822.png)

**Comment by murphybob** [comment]
Ahhh I see, it's either/or
- use initial value and (optionally) provide 2 type args, OR
- don't use initial value and (optionally) provide 1 type arg

And in the second case deal you could make this work if you wanted by managing the type of the collection being reduced.

Gotcha!  Thanks, that was a great explanation, sorry for the trouble :-)
