### ISSUE TITLE
Typing on function behaves differently if as type, interface or on the function

### ISSUE THREAD

**Issue by mmahalwy** [microsoft/TypeScript#43365]
# Bug Report
No error:
```ts
type CustomType = { name: string };
interface MyFunc {
  (arg: string): CustomType;
}

const myFunc: MyFunc = (arg) => {
  return { name: arg, extraKey: 1234 };
};
```

No error:
```ts
type CustomType = { name: string }
type MyFunc = (arg: string) => CustomType;

const myFunc: MyFunc = (arg) => {
  return { name: arg, extraKey: 1234 };
};
```

Errors:
```ts
type CustomType = { name: string }

const myFunc = (arg: string): CustomType => {
  return { name: arg, extraKey: 1234 };
};

// error: Type '{ name: string; extraKey: number; }' is not assignable to type 'CustomType'.
//  Object literal may only specify known properties, and 'extraKey' does not exist in type 'CustomType'.
````

### 🔎 Search Terms
Function types not erroring when using `type` or `interface`.

### 🕗 Version & Regression Information
Version 4.2.3

Tested from version 3.3.3 to 4.2.3

### ⏯ Playground Link
N/A

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
See above

### 🙁 Actual behavior
Only the last example fails. 

### 🙂 Expected behavior
All examples above should error. The function returns an object with incorrect keys.

**Comment by MartinJohns** [comment]
This is working as intended. In your no error versions you don't specify a return type for your functions, so the return type is inferred. Because the return type is inferree based on your returned value you don't get any excess properties. Then the compiler checks if your value (the function) is compatible with the annotated type of your variable (`MyFunc`).

**Comment by mmahalwy** [comment]
I may have missed this @MartinJohns. For this example, why is the return type inferred? I thought I set it explicitly as `CustomType`. See: 
```ts
type CustomType = { name: string }
type MyFunc = (arg: string) => CustomType;

const myFunc: MyFunc = (arg) => {
  return { name: arg, extraKey: 1234 };
};
```

**Comment by MartinJohns** [comment]
Because your anonymous arrow function has no type annotation for the return type:

    // No return type annotation
    (arg) => { return { name: arg, extraKey: 1234 }; }
    
    // With return type annotation
    (arg): { name: string } => { return { name: arg, extraKey: 1234 }; }

Keep in mind that additional properties are legal in TypeScript. The excess property checks feature is often called "more of a linter feature" by the TypeScript team.

**Comment by mmahalwy** [comment]
Right, I understand that example @MartinJohns but since I am setting the type on the function constant, I'd expect it to adhere to the return type annotation:
```ts
type MyFunc = (arg: string) => CustomType;
const myFunc: MyFunc;
```

**Comment by RyanCavanaugh** [comment]
See also #40311 which attempts to change this

**Comment by mmahalwy** [comment]
@RyanCavanaugh thanks for linking that. Would LOVE to see that PR merged 🙏
