### ISSUE TITLE
Generic (Map) parameter inference mismatches the actual type declared for the variable

### ISSUE THREAD

**Issue by andrew-z** [microsoft/TypeScript#43386]
# Bug Report

### 🔎 Search Terms

map, optional, empty interface, generic inference

### 🕗 Version & Regression Information

No particular version I noticed that started this - I think it was like that since the beginning, or a least since we started the project. 
I still can repro in the latest stable version and [nightly build](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210325#code/KYDwDg9gTgLgBMAdgVwLZwNLAJ4FEXoDeAsAFBwWY4CMANGZVdgEz2kC+ZZokscAlohjAoAMwCGAY2BwAstgCSQkROlwS5ShDAx+EROIA2AMX7BDAEwD8ALjgAjCBEPBxiANwNKbiDAAWIgDyOnoGJmaWtnAE9iKeHFykkvoAzvCo2LLiYHZZYAA8WHgEtHKKymJSwAB8cAC80cAA7nLZABQA2l4UHUX4aAB0RXTqcD7+QSH6RqbmFnbUzADMcOwAumyMvTj9qEM4rKP+-CmzlgopAHK+uABuSAAiwKKCwPNwAERNfuLC91AfVYbMhrACU7iAA).

I believe this might be related to [this FAQ entry](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces) because the interface with all fields optional is somehow similar to an empty interface, but I might be wrong.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210325#code/KYDwDg9gTgLgBMAdgVwLZwNLAJ4FEXoDeAsAFBwWY4CMANGZVdgEz2kC+ZZokscAlohjAoAMwCGAY2BwAstgCSQkROlwS5ShDAx+EROIA2AMX7BDAEwD8ALjgAjCBEPBxiANwNKbiDAAWIgDyOnoGJmaWtnAE9iKeHFykkvoAzvCo2LLiYHZZYAA8WHgEtHKKymJSwAB8cAC80cAA7nLZABQA2l4UHUX4aAB0RXTqcD7+QSH6RqbmFnbUzADMcOwAumyMvTj9qEM4rKP+-CmzlgopAHK+uABuSAAiwKKCwPNwAERNfuLC91AfVYbMhrACU7iAA)

### 💻 Code

```ts
export enum KeyEnum {
    Key1,
    Key2,
}

export interface MyInterface {
    optionalField?: boolean;
    anotherOptionalField?: number;
}

const myMap: Map<KeyEnum, MyInterface> = new Map([
    [KeyEnum.Key1, { anotherOptionalField: 123 }],
    [KeyEnum.Key2, { thisFieldIsNotEvenDefined: "whatever" }],
]);
```

### 🙁 Actual behavior

This compiles

### 🙂 Expected behavior

`MyInterface` doesn't have a field called `thisFieldIsNotEvenDefined` so I would expect it to fail to compile. 
Specifying explicit generic parameters for the `Map` constructor solves the issue.

```ts
const myMap = new Map<KeyEnum, MyInterface>([
    [KeyEnum.Key1, { anotherOptionalField: 123 }],
    [KeyEnum.Key2, { thisFieldIsNotEvenDefined: "whatever" }],
]);
```

**Comment by MartinJohns** [comment]
When you don't specify the type arguments, then they'll be inferred from the provided values. You can see this well when you hover over the constructor call:

![image](https://user-images.githubusercontent.com/5269069/112600511-962c3580-8e11-11eb-83b4-6a37e4df9f30.png)

The inferred types are not incompatible with your target type (`Map<KeyEnum, MyInterface>`), so assignment of your created map works fine.

**Comment by RyanCavanaugh** [comment]
This is intentional. You can write it a different way if you want different behavior:
```ts
// OK & intended (contextual inference candidates do not supercede candidates from parameters)
const myMap1: Map<KeyEnum, MyInterface> = new Map([
    [KeyEnum.Key1, { anotherOptionalField: 123 }],
    [KeyEnum.Key2, { thisFieldIsNotEvenDefined: "whatever" }],
]);

// Errors
const myMap2 = new Map<KeyEnum, MyInterface>([
    [KeyEnum.Key1, { anotherOptionalField: 123 }],
    [KeyEnum.Key2, { thisFieldIsNotEvenDefined: "whatever" }],
]);
```
