### ISSUE TITLE
JS Doc @Link support for referring to property of class/interface

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#43383]
# Bug Report

### 🔎 Search Terms

- jsdoc
- `@link`
- `@see`

### 🕗 Version & Regression Information

4.3.0-dev.20210325

### 💻 Code

For the TS:

```ts
interface Foo {
    /**
     * {@link Foo#xyz}
     * 
     * {@link Foo.xyz}
     * 
     * {@link Foo~xyz}
     * 
     * {@link xyz}
     */
    abc: number;
    
    /**
     * {@link abc}
     */
    xyz: number;
}
```

Hover over `abc` and view the links. 

### 🙁 Actual behavior

None of the links are resolved. I was not able to find a way to have documentation on one property refer to another property 

### 🙂 Expected behavior

If we are following JSDoc, `I'd` expect that `Foo#xyz` would be resolved. However we may also want to support: `xyz` (and maybe `Foo.xyz`?)

**Comment by sandersn** [comment]
Initial `@link` support parses entity names (dotted names) but does not resolve them.

Filed https://github.com/microsoft/TypeScript/issues/43594 to track parsing `#`.
Filed https://github.com/microsoft/TypeScript/issues/43595 to track within-class/interface lookup.

I'll look at the first two after the 4.3 release.

**Comment by mjbvz** [comment]
@sandersn Are there any workarounds for this issue planned for TS 4.3? We're eager to start adopting`@link` in our `d.ts` (https://github.com/microsoft/vscode/issues/120120) but not being able to link to properties is a pretty significant limitation
