### ISSUE TITLE
unknown type generates wrongly inferred generic types

### ISSUE THREAD

**Issue by npenin** [microsoft/TypeScript#43389]
# Bug Report

### 🔎 Search Terms

generic constraint unknown inferred inferance Record decorator

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.2.3#code/GYVwdgxgLglg9mABAQwDwBUDyAjAVgU2kXwA8p8wATAZ0QCVC4AnS1aqJmMAcwBpwA1mDgB3MAD5xACmjMAXGHwjEUgJQBecVjyEoqgFABvfYlOJ9AX336IAG2TVaAWQCeOXEZNmADiGy2YCEQSOXZOHnUAckiAbktrZClXd1UYoA

### 💻 Code

```ts
function a<TObject extends Record<string,unknown>>(ctor:new ()=>TObject)
{
    
}

class MyObj
{
    public x:string='';
}

a(MyObj);

```
### 🙁 Actual behavior

Compilation error: TObject not castable as Record<string,unknown>, while it definitely has a property x 

This is breaking any decorator that one would like to strongly type. Generally, when unknown is involved in generic constraints, it involves a lot of typing issues.

### 🙂 Expected behavior

No error

**Comment by MartinJohns** [comment]
![image](https://user-images.githubusercontent.com/5269069/112611128-b82bb500-8e1d-11eb-8841-c21c99568bed.png)

The error informs you about the missing index signature, which is present in the type `Record<string, unknown>`, but is not present in your class. When you add the index signature it works:

    class MyObj
    {
        [key: string]: string;
        public x:string='';
    }

**Comment by npenin** [comment]
Indeed, I found a workaround
```ts
function a<TObject extends Record<keyof TObject,unknown>>(ctor:new ()=>TObject)
{
    
}

class MyObj
{
    public x:string='';
}

a(MyObj);
```
