### ISSUE TITLE
Using both fat arrow notation and (the original value of) this

### ISSUE THREAD

**Issue by fstanis** [Microsoft/TypeScript#4339]
I've recently written a [question on SO](http://stackoverflow.com/questions/32025342/typescript-how-to-use-both-fat-arrow-and-this) regarding this issue and since the offered solution was interesting, I thought about suggesting it as a possible future feature in TS.

Consider the following:

    function callback() {
        // How to access the button that was clicked?
    }
    $('.button').click(() => { callback() });

While in this specific example it's possible to access the button using jQuery's `event.currentTarget`, there are cases where losing the value of `this` is not desireable, yet using the fat arrow is also convenient to preserve the `this` value of the enclosing context.

The solution offered using `.apply` was very simple so I was thinking it might be a good idea for a future version of TS to have a notation that would do this automatically (turning the original value of `this` into the first argument).

**Comment by RyanCavanaugh** [comment]
Arrow functions are part of the ES spec now; this kind of proposal should start with ESDiscuss.

Probably the cleanest workaround in most cases is to use `var self = this;` and a regular function instead of an arrow function.
