### ISSUE TITLE
Jsdoc unable to refer template from another template's constaint

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#43403]
# Bug Report

### 💻 Code

In .ts files we are able to refer template type from another template's constraint

```ts
type A<T1, T2 extends T1> = [T1, T2]
```

But in jsdoc it's not possible

```js
/** 
 * @template T1
 * // Cannot find name 'T1'.ts(2304)
 * @template {T1} T2
 * 
 * @typedef {[T1, T2]} A
 */
```

### 🙁 Actual behavior

'Cannot find name' error

### 🙂 Expected behavior

No error

**Comment by ilogico** [comment]
This is very strange. It happens with `typedef` only, but I have different errors depending on the location of the `typedef`.
[This one](https://www.typescriptlang.org/play?useJavaScript=true#code/PQKhCgAIUgBAXApgWwA4BsCGTIEEowIobaKQDeuAvpAEIFzwCeqiAJogGYUDauANHQC6NAMIFg4KaAjRGxLDnxyiaRWUo16K1JgBOmZBWqRMDWLoNHytGgCMJ4TgFcAdgGN4ASwD2ryJwAFJiCdgCUFOBUUtJg5khqpHjxCkmadI7uWADO2ZAAIpGQxZAyUCUqzKwUogA8AnQAfNEV0JIVnFFSQA) says B doesn't satisfy A.
[This one](https://www.typescriptlang.org/play?useJavaScript=true#code/FAegVGwARlACAXApgWwA4BsCGyoEFpZFVMckoBvPAXygCFD40sAnLFSmqLRuZtjhTq0ARoRDAAZgFcAdgGMEASwD2sqJIAUWADRQRASkrBqwUBF7J02XARjwrpXFVoN7iAJ5okAEySTKAG08PToAXVoAYXEzcEh3RxtyOyJEsk5XGPlsAGccqAARYygSqDjoUoSvcgpIgB4Q+gA+U0qYCUrJEzMgA) works.
And [this one](https://www.typescriptlang.org/play?useJavaScript=true#code/FAegVGwARlACAXApgWwA4BsCGyoEFpZFVMckoBvPAXygCFD40sAnLFSmqLRuZtjhTq0ARoRDAAZgFcAdgGMEASwD2sqJIAUWADRQRASkrBqwUBF7J02XARjwrpXFVoMYE+dgDOXqABFjKCCocEhgoKIEAE80cgoAYQAePD06AD5TcPdoYMkTM1DLEhtyO0jisk5XSxikABMkSUoAbRT6AF1aePEgA) reproduces your error.
