### ISSUE TITLE
Erroneous "implicitly has type any" for variable later assigned to in loop

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#43409]
# Bug Report

### 🔎 Search Terms

variable declaration equals implicit any loop

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210328&ssl=11&ssc=14&pln=11&pc=5#code/JYOwLgpgTgZghgYwgAgMpjpZBvAvgWACgiATCBAGzihRgFcQExgB7EZUYZuC9TCABQBKAFxoMWAD7IQdChVLkqNZPUbM2MiAA8wfSAIDOEiGP0pps+aOQBtcwF1k0hmRigIJIkR0AHFlBgqgxMrOwARtTCYgBuLMAkOETIKcgUEEHG-MgAvBwgXMA85sLehKkcMMhGJrl5VhRCyDRgdFAgZRUwAdUA3L1N2MkVqQhsxnYgOmAOYvYmTtK2TvXTJVmQTQD8W3YOwyOHAPRHyAB+F2fIAORTutccALa+FMAIXBQAnsgAFnCGyDAn18KGucBAnwe4XIcDohhQXGQJBYEABIBYQT+MRQcAOhwqJ0BwJxIHREjCyHBiWAAJoMGgEEYniRwBoTC+yB6oBIrPIYA5oA4YABLAA7uxONxXgAvaAAOk6+I2KFWugAhHiCIQtUA)

### 💻 Code

```ts
interface State {}

declare function initialState(): State | null
declare function nextState(state: State | null): [State] | undefined

export function bar(): void {
    let state = initialState()

    if (state == null) return

    for (;;) {
        const [next]: [State] | [] = nextState(state) ?? []
             // ~~~~ 'next' implicitly has type 'any' because it does not have a
             // type annotation and is referenced directly or indirectly in its own initializer.

        state = next!
    }
}
```

Originally reported in: https://github.com/typescript-eslint/typescript-eslint/issues/2248

### 🙁 Actual behavior

```
'next' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

If you remove`state = next!` or the `for (;;)`, the code exhibits the expected behavior.

### 🙂 Expected behavior

`next` is inferred to be type `State | undefined`.

**Comment by MartinJohns** [comment]
#36687

**Comment by JoshuaKGoldberg** [comment]
Ha, nice, thank you 😄
