### ISSUE TITLE
JSDoc accessor declaration emit drops undefined when strictNullChecks is off

### ISSUE THREAD

**Issue by dillonredding** [microsoft/TypeScript#43408]
# Bug Report

### 🔎 Search Terms

* JSDoc
* getter
* nullable
* undefined
* optional

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "JSDoc" and "getters".

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&useJavaScript=true#code/PTAEFMFsEsBdfAE1LAngB3KR4DGAbAQwCdDZoB7AOwGdQAzC40ANxOkICN9w6aBXdOiaxQVfviLdwwCunLVC+FBl4BYAFDAAVNtAABNJlABvGrGLQqAcwC8AX1Dbgm3NXMMKFULdAByRgo-AG5NHT1DVVNzSxtQAB9QfioceiskR2dXd1FOEh9-QJCw3QMjLBMAfhira0yXDTdaXMIALwKAr2KtUsjjMwtahLEJfHrs5tAAR34ADw6i0I0wsAALCgB3cBZwYgAaFFXwVFASLCoKUQEhESRQalBrcHhdmlciGjoAMS9TTVBQOEylEBrE7OMNACnqJAgAKACUplAxGe-GIVEKXWCoHs-0BvXK0UGcUSyVS6UQEKhz1AeWICKRKNgaIxnSC2NxkPxEUJVRqNipjxpeVaDJMyNR6Mx7JxeKBfQq-Osw3EkkF0OmczFEuZUrZIVlGk5K0OWBohEgWEIQnw0F4nmY+iZLLejQ+dAAQvkTHLes70XRQbUHE4GtSYV5tf7WYtDQD5dHA0rhmTwGkqBlQ3iNXSo5KY1i49yDInTNViXUs1yc2087qCzLOfG-fmkxWVaN1TSZrM6yzpQbOZygA)

### 💻 Code

See playground link.

### 🙁 Actual behavior

See **.D.TS** tab in playground.

### 🙂 Expected behavior

```ts
// const declarations unchanged...
declare class Foo {
    /** @type {string=} */
    get foo(): string | undefined;
    /** @type {string | undefined} */
    get bar(): string | undefined;
    /** @type {?string} */
    get baz(): string | null;
    /** @type {string | null} */
    get qux(): string | null;
}
declare class Bar {
    /** @returns {string=} */
    get foo(): string | undefined;
    /** @returns {string | undefined} */
    get bar(): string | undefined;
    /** @returns {?string} */
    get baz(): string | null;
    /** @returns {string | null} */
    get qux(): string | null;
}
```

**Comment by RyanCavanaugh** [comment]
FWIW you should probably turn on `strictNullChecks`; there will be other problems without this flag on

**Comment by dillonredding** [comment]
Turning on `strictNullChecks` does work around the issue.
