### ISSUE TITLE
Nested object rest in destructuring results in code with a syntax error

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#43400]
# Bug Report

### 🔎 Search Terms

array object assign destructuring invalid code syntax error

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210326#code/G4QwTgBAHgNBCecRwEYG4BQGD02IGUALAewFcAbAEwgAcwBLAOwBcAuCAbwCIQUBjLqwCMAXwwBtDhAB0sqBBEBdCAF4IkiLz7shCxWgh9ijAM7FyAU2nliAcwAUAKXwB5AHLSTzBo1v0AZvD2UACUIZg4eERkVLQ+bJw8-IKiGP7EkPYastLwehDE-uoaWjp6iiGGxmaW1nZOrh5ePn6B9vBhEbgEJBTUdEwJ3CCCPFwwXCiC3EKjUxMATKMCImLpmVIADOzIMrIoChBMnJr8ZSKVRqbmVjYOzu6e3kytQRy7KBfhQA)

### 💻 Code

```ts
var x, y, a, b;

// Should print: {"abc":1}
[{ ...x }] = [{ abc: 1 }]; console.log(JSON.stringify(x));

// Should print: {"abc":1}
for ([{ ...y }] of [[{ abc: 1 }]]) console.log(JSON.stringify(y));

// Should print: {"a":"a","b":{"1":"b","2":"c"}}
for ({ 0: a, ...b } in { abc: 1 }) console.log(JSON.stringify({a, b}));
```

### 🙁 Actual behavior

Compiling this with a target of `ES2017` results in code with a syntax error:

```js
"use strict";
var x, y, a, b;
// Should print: {"abc":1}
[Object.assign({}, x)] = [{ abc: 1 }];
console.log(JSON.stringify(x));
// Should print: {"abc":1}
for ([Object.assign({}, y)] of [[{ abc: 1 }]])
    console.log(JSON.stringify(y));
// Should print: {"a":"a","b":{"1":"b","2":"c"}}
for (Object.assign({ 0: a }, b) in { abc: 1 })
    console.log(JSON.stringify({ a, b }));
```

The specific syntax error is `SyntaxError: Invalid destructuring assignment target`, and happens because of the call to `Object.assign` in assignment position.

### 🙂 Expected behavior

This should result in valid code, and that code should print this:

```
{"abc":1}
{"abc":1}
{"a":"a","b":{"1":"b","2":"c"}}
```

I have reported this same issue in the past: https://github.com/microsoft/TypeScript/issues/39181#issuecomment-647989968. It must be that either the fix has regressed or the fix was incomplete.

**Comment by a-tarasyuk** [comment]
TS doesn't allow to use destructuring in `for...in` statement. @RyanCavanaugh Do we need to allow it?
```ts
for ({ 0: a, ...b } in { abc: 1 }) console.log(JSON.stringify({a, b}));
// The left-hand side of a 'for...in' statement cannot be a destructuring pattern.(2491)
```
