### ISSUE TITLE
typeof operator not using undefined guard in when used in a loop nested in the guard

### ISSUE THREAD

**Issue by lesiak** [microsoft/TypeScript#43411]
# Bug Report

### 🔎 Search Terms

typeof, type guard, undefined guard, loop

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behaviour and Type Guards

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ssl=17&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJIAUoHsAO0zAQDOyA3gFDJXIxZYD8AXGZdW3B80WFKAOas2VAEaiuPfoOQBfcrPIwAriAQEsIZKGBgAFDmx4oBYswwH8hIgEoWbYDGR7zRywDpaWGxSHUwATzxkADE6AHkAaWQAXmR-PCwHfVwLYnc6AG4qKTYkw2MiNKxMgHpi2ICUYBJSZA44cV4QPkzRYQb+TNkfKlooRwR1bmQAD2QE5ABtAEYAGmQAJjmAZgBdL2yhXJSCjxKyuMrq2s5kbkbm5Fb2ps6NtgPgsKgAVRAAEwgYUAg36PL4xLOfKFPYPKpkY71U4SG6XMTQ86dZAAH2Qyg+XxAPzuMik0mQciAA)

### 💻 Code

```ts
interface IProperties {
    foo?: {
        aaa: string
        bbb: string
    }
}

function init(properties: IProperties) {
    if (properties.foo) {
        type FooOK = typeof properties.foo;  
        properties.foo; // type is { aaa: string; bbb: string; }
        for (const x of [1, 2, 3]) {
          properties.foo; // type is { aaa: string; bbb: string; }
          type FooOrUndefined = typeof properties.foo; //type is { aaa: string; bbb: string; } | undefined
        }
    } 
}
```

### 🙁 Actual behavior

Under a loop nested in undefined type guard for variable `properties.foo`,
- `properties.foo` is inferred to be  `{ aaa: string; bbb: string; }`
- `typeof properties.foo` is inferred to `{ aaa: string; bbb: string; } | undefined`
This happens both for for...of and while loops.

### 🙂 Expected behavior

typeof takes type guard into account:
- `typeof properties.foo` is inferred to `{ aaa: string; bbb: string; }`

**Comment by MartinJohns** [comment]
I'm pretty sure this is related: #37516

**Comment by RyanCavanaugh** [comment]
I'm legitimately curious how you even noticed this

**Comment by lesiak** [comment]
@RyanCavanaugh Indeed, this is not the code someone could write intentionally. I was playing with a question on SO and pasted the check from someones answer in the wrong place.
https://stackoverflow.com/questions/66814919/scoping-rules-for-undefined-type-guard-in-typescript
