### ISSUE TITLE
Function overload with generic is less strict than generic that extends

### ISSUE THREAD

**Issue by niedzielski** [microsoft/TypeScript#43410]
# Bug Report

Adding a generic overload to a function is unexpectedly more lenient than the equivalent `extends`. Consider the non-overloaded version:

```ts
export function area1<T extends number>({x, y}: Readonly<XY<T>>): T {
  return x * y // Error.
}
```

And the overloaded version which unexpectedly succeeds:

```ts
export function area2<T>({x, y}: Readonly<XY<T>>): T
export function area2({x, y}: Readonly<XY<number>>): number {
  return x * y // Expected error as in area1() but passes.
}
```

The overload succeeds even when `T extends number` as in `area1()`:

```ts
export function area2<T extends number>({x, y}: Readonly<XY<T>>): T
export function area2({x, y}: Readonly<XY<number>>): number {
  return x * y // Expected error as in area1() but still passes.
}
```

### 🔎 Search Terms

- Overload generic 

Possibly related to: #43301, #43187

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _function overloading_
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210328&ssl=1&ssc=1&pln=16&pc=1#code/C4TwDgpgBAGgmgHgCoD4oF4oG8AeAuKJAGihAKQF8AoKiHMAewCdgoAzAVwDsBjYASwZcoAQyYQRARmRQ6wCFwAmAZyhcOAWwBGEJigAUuEiAoEAShMVCANiATxkKFAEpy2KlCgB6L1AACwMoAtHSQfCFMTMwe3r4AopHM5ODQAOTq2rqpUPyqXAysIsrK-ADmXCJa1tDADFCgkFCpSKkAdDE+nk0tUDwMHNaKUDo5XMrAIlwCIvJDAO78wAAWosJiWotMYiD1KVBzS-w8K30DQyPc4tYzEEO1TRk6TKkx4sAcTMI4UABUpFTUWj0ZisTi8ARCUTiEQAJkchhwxlMUAsIisXFs9kQqBc5CBjBY7G4fEEa2hMIRSPMlhsdgcj10Tlcak0T3cnk6AWCoQg4V0USYHXi9F5s1kiSYolU-DJEkk+mc7U8bw+X1+-2oQA)

### 💻 Code

```ts
type XY<T> = {x: T, y: T}

export function area1<T extends number>({x, y}: Readonly<XY<T>>): T {
  // @ts-expect-error
  // Error: Type 'number' is not assignable to type 'T'.
  //   'T' could be instantiated with an arbitrary type which could be unrelated to 'number'
  return x * y
}

export function area2<T>({x, y}: Readonly<XY<T>>): T
export function area2({x, y}: Readonly<XY<number>>): number {
  // @ts-expect-error
  // Expected error as in area1() but the following line is permitted.
  return x * y
}
```

### 🙁 Actual behavior

Overloaded function type checking is more lenient than the equivalent non-overloaded.

### 🙂 Expected behavior

Overloaded and non-overload function type checking are equivalent.

**Comment by dragomirtitian** [comment]
This is by design. The overloaded function implementation is only checked against the implementation signature (the last one). The overloads are checked (loosely, bivariant-ly I believe) against the implementation signature. 

And yes this does create an implicit cast and is unsafe. But this behavior has been around since overloads have existed and I don't think it is likely to change.

**Comment by niedzielski** [comment]
Thanks, @dragomirtitian.
