### ISSUE TITLE
noImplicitOverride is not yet a semantics-affecting option

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#43417]
```ts

class Base {
    isLogging = false;
    
    enableLogging(val: boolean) {
        this.isLogging = val;
    }

    doStuff() {
        // ...
    }
}

class Derived extends Base {
    enableLogging(val: boolean) {
        super.enableLogging(val);
        
        // ...
    }

    doStuff() {
        //
    }
}
```

Turn on `noImplicitOverride`.

**Expected**: errors appear in the editor or in watch mode
**Actual**: you need to restart the server to see the effects

**Comment by DanielRosenwasser** [comment]
CC @Kingwl

**Comment by Kingwl** [comment]
copy.

**Comment by DanielRosenwasser** [comment]
My apologies. The problem exists between the chair and my keyboard. I was in an editing scenario where it was just taking a very long time to refresh the errors for some reason.
