### ISSUE TITLE
[BUG] Incorrect event type for `mouseleave` event

### ISSUE THREAD

**Issue by yaquawa** [microsoft/TypeScript#43418]
### 🕗 Version & Regression Information
4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBCwQvBBvAvhAhgZwgUVAWxAHZgBQ0AdKgCaVYBuhYAMgJbpiEgBOAFAOS4B7AK7poIVPV4AabiHpEAlLAB8CYhAgB6TVHmRWEAAZ0GhiAHcAFlxARmkdJeHBKEAEa3DAWWGiTRQ2IkBSA)

### 💻 Code
```ts
let el = {} as Element
el.addEventListener('mouseleave',(event)=>{
  // event is `Event` where it should be `MouseEvent`
})
```

**Comment by nmain** [comment]
It works if you type `el` more specifically:
```ts
let el = {} as HTMLElement
```

**Comment by RyanCavanaugh** [comment]
`Element` doesn't have a defined `mouseleave` event, so we don't know what kind of arguments could actually occur there. `HTMLElement` does, though.

**Comment by yaquawa** [comment]
Thanks for the details!
