### ISSUE TITLE
Add noImplicitOverride to schema store

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#43416]
Currently not provided in VS Code's tsconfig auto-suggestions.

Needs to be fixed on schemastore

https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json

**Comment by a-tarasyuk** [comment]
cc @sandersn @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Thank you!!

**Comment by orta** [comment]
( When https://github.com/microsoft/TypeScript-Website/pull/1708 and https://github.com/SchemaStore/schemastore/pull/1534 gets merged we shouldn't have issues like this in the future 👍🏻  )
