### ISSUE TITLE
Should getters still infer the same type from setters over their return expressions?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#43414]
```ts
class C {
    #x = Promise.resolve("")

    set myValue(x: Promise<string> | string) {
        this.#x = Promise.resolve(x);
    }
    get myValue() {
        return this.#x;
    }
}
```

Should the `get` type of `myValue` be `Promise<string>` or just `string | Promise<string>`? Right now it is the latter; but technically, the former provides a more specific type.

Changing this technically would be a breaking change.

**Comment by MartinJohns** [comment]
Duplicate of #2521.

**Comment by ahejlsberg** [comment]
I agree, I don't think there is a compelling case for us to *infer* divergent getter and setter types.

**Comment by RyanCavanaugh** [comment]
I also would prefer to keep the current behavior

**Comment by DanielRosenwasser** [comment]
Consensus'd
