### ISSUE TITLE
template literals get template literal types even outside a context with one

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#43424]
# Bug Report

From react-motion-loop on DT, along with a couple of other packages. Started failing the day after contextual typing for template literals.

```ts
const interpolatedStyle = { rotate: 12 };
function C2(transform: "-moz-initial" | (string & {})) { return 12; }
C2(`rotate(${interpolatedStyle.rotate}dig)`)
```

### 🙁 Actual behavior

Error: 
```
Argument of type '`rotate(${number}dig)`' is not assignable to parameter of type '(string & {}) | "-moz-initial"'.
  Type '`rotate(${number}dig)`' is not assignable to type '"-moz-initial"'.
```

### 🙂 Expected behavior

No error

**Comment by ahejlsberg** [comment]
The template literal type is intended behavior. The real issue is that we don't consider template literal types assignable to `{}` (or `Object` or `String` for that matter). That's just wrong and has been an issue for a while. For example, all of the below cause errors but shouldn't:

```ts
declare let s: `foo-${number}`;
let x1: {} = s;
let x2: Object = s;
let x3: String = s;
```
