### ISSUE TITLE
Can't call `((_: string) => T) | undefined` when conditionally `string extends T`

### ISSUE THREAD

**Issue by jtbandes** [microsoft/TypeScript#43425]
# Bug Report

I am trying to make a generic callback function `(_: string) => T`, that is allowed to be optional (undefined) only when `T` is `string`. (Specifically, I chose `string extends T` because TS doesn't seem to provide exact equality for conditional types, and I want the default value to be `(x: string) => x`.)

The initial way I wrote this was `string extends T ? ((value: string) => T) | undefined : (value: string) => T`, but I found I was unable to (conditionally) call the function. The error seems to stem from TS treating the type as `(value: T & string) => T`, which prevent me from passing in a string literal.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/14237/112906752-66d32e00-9088-11eb-8109-75a996f84630.png">

I found a workaround that allows me to call the function: `((value: string) => T) | (string extends T ? undefined : never)` (**which I believe should be exactly equivalent**, though let me know if this is wrong). However, this too is broken in the latest nightly, seemingly because of how `NonNullable` is being distributed over `|`:

<img width="607" alt="Screen Shot 2021-03-29 at 12 17 07 PM" src="https://user-images.githubusercontent.com/14237/112906960-c4677a80-9088-11eb-913f-f007ca22b972.png">

### 🔎 Search Terms

generic extends function parameter union 🤷

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7, and changed again between 4.2.2 and the nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbAjAHhgD4oBeKACgoDcEAbAVwgC4oVg4BLJAcwEoyJGAIA+ldl15QIAD2AQkAExSwoAfigMlENNwiKorJBGoQ4fANwBYAFChIsRKkw4ATIRLkJ3HtLkLlVQ0qWkYWNg4fAVIhUU1tXWMDVhp6JlZvXmihaxtbNC0AY2BODCQoeXYPCjRcVnhkdCw8DwAaKDRXeqcmtw8BAG9bKA7cNQA6CgAiAAsIOjoMKcthjtcJ6bmFpZWbAF9bIA)

### 💻 Code

```ts
type Transform1<T> = ((value: string) => T) | (string extends T ? undefined : never);
type Transform2<T> = string extends T ? ((value: string) => T) | undefined : (value: string) => T;

function test<T>(f1: Transform1<T>, f2: Transform2<T>) {
  f1?.("hello");  // error in nightly, no error in 4.2.2
  f2?.("hello");  // error since 3.9.7, no error in 3.8.3
}
```

### 🙁 Actual behavior

Error on the call to `f1` in 4.2.2, and errors on both calls in the nightly.

### 🙂 Expected behavior

Both calls should succeed. The function return value is ignored, so `string extends T` should have no impact on the validity of the expression.

**Comment by jtbandes** [comment]
Unfortunately even with the workaround, [the return type of my default function can't be treated as compatible with `T`](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbAjAHhgD4oBeKACgoDcEAbAVwgC4oVg4BLJAcwEoyJGAIA+ldl15QIAD2AQkAExSwoAfigMlENNwiKorJBGoQ4fANwBYAFChIsRKkw4ATIRLkJ3HtLkLlVQ0qWkYWNg4fAVIhUU1tXWMDVhp6JlZvXmihaxtbAGMMVGAoRR0EBjpgeGR0LGwyShkMyKzBKBlc2zQtfOBOIqh5dg8KCRbJHgAaKDRcVhrneoJiGbRXBac6tw8BAG9bKCg6CBK4CBRK4HnVcgo59Q0ytAqqxe3sPjGOS0Pj06g50uVQ2t0o60epXKV3eLk+33MuQAvrYgA).

**Comment by RyanCavanaugh** [comment]
Let's scope this one to this example
```ts
type Transform1<T> = ((value: string) => T) | (string extends T ? undefined : never);
function test<T>(f1: Transform1<T>) {
  f1?.("hello");  // error in nightly, no error in 4.2.2
}
```

**Comment by jtbandes** [comment]
I went ahead and ran a `git bisect` — this broke in 15fae38b39a370f1f597606e552dd40998a1ac49 / #43183.

**Comment by ahejlsberg** [comment]
This is indeed a regression caused by #43183. However, it was sort of halfway broken before because `getNonNullableType` doesn't properly eliminate higher-order types that are constrained to just 'undefined' or 'null'. For example:

```ts
function f1<T>(x: T | (string extends T ? undefined : never)) {
    let z = x!;  // NonNullable<T> | NonNullable<string extends T ? undefined : never>
}

function f2<T, U extends null | undefined>(x: T | U) {
    let z = x!;  // NonNullable<T> | NonNullable<U>
}
```

In both cases above, the type of `z` should just be `NonNullable<T>` because the other type is known to always be nullable.

Both the regression and the above issue can be solved by being a bit smarter in `getNonNullableType`.
