### ISSUE TITLE
Keep comments on public API's in d.ts files

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#4342]
consider the following

```typescript
// greets the user
class Greeter{
    // Hello method
    public hello(name:string){
        console.log("Hello, " + name);
    }
}
```
Now even without the `removeComments` option there are no comments on the public APIs in the d.ts which would help with the documentation of the APIs

**Comment by mhegazy** [comment]
this is actually by desing. only jsdoc style comments are preserved. see https://github.com/Microsoft/TypeScript/blob/2ffc37510d2f8b74ca03f41633bd06fe2777e94f/src/compiler/declarationEmitter.ts#L307-L314

so far does not seem to bother anyone. would be interested to see if this is not true.
