### ISSUE TITLE
New Allowed Syntax (4.3): Getters / Setters in Non-class Scopes

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#43420]
This is a tracking issue so we can link this to upstream parsers.

In TypeScript 4.3, it's now allowed to declare `get` and `set` accessors in type contexts other than class bodies, e.g.:
```ts
interface X {
  get foo(): string;
  set foo(v: string | number);
}
type Y = {
  get bar(): string;
  set bar(v: string | number);
}
```
It is now also semantically legal for the `get` return type and `set` parameter type be different.

Additionally, it is now semantically legal to have the access modifiers in a class body differ:
```ts
declare class C {
  public get x(): string;
  protected set x(s: string);
}
```

Access modifiers outside of class bodies remain illegal.

**Comment by whzx5byb** [comment]
Will the following syntax be supported in the future?

```
class C {
  declare get x(): string;
  declare protected set x(s: string);
}
```

**Comment by RyanCavanaugh** [comment]
Maybe? Not in 4.3, though.

**Comment by worstpractice** [comment]
@RyanCavanaugh Wonderful work!

Any chance of allowing `readonly` getters?

I noticed the following doesn't work:
```typescript
type Y = {
  readonly get bar(): string;
}
```

What about index signatures?

```typescript
type Y = {
 get [key in "foo" | "bar"](): string;
}
```
