### ISSUE TITLE
Expose Web APIs on iframe window

### ISSUE THREAD

**Issue by Joozty** [microsoft/TypeScript#43433]
# lib Update Request

It would be nice if [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API) are exposed on [the iframe window](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L7096) too. 

For instance, I can access `HTMLElement` via `window.HTMLElement` without any TS error but when I try to access it from within iframe window - `iframe.contentWindow.HTMLElement` I get an error even though the code is valid.

There can be many use cases for this.  For example, I need to check the instance of a node that is retrieved from iframe.

I cannot do simply something like this because objects created within one iframe [do not share [[Prototype]]’s](https://stackoverflow.com/questions/6473273/why-are-myarray-instanceof-array-and-myarray-constructor-array-both-false-wh/6473338#6473338) with object created within another iframe or parent window. 

```
const element =  someIframeElement.contentDocument.createElement('div')
element instanceof HTMLElement // false
element instanceof someIframeElement.contentWindow.HTMLElement // true but TS complains that HTMLElement doesn't exists on contentWindow object
```

Sandbox [here](https://codesandbox.io/s/webapis-iframe-jpmqk?file=/src/index.ts)

**Comment by IllusionMH** [comment]
Simplified case
```ts
declare const w: Window;

w.HTMLElement; // Error
window.HTMLElement; // OK
```

Because constructors like `HTMLElement` are declared on `globalThis` and not on `Window`
