### ISSUE TITLE
Duplicate function implementation.

### ISSUE THREAD

**Issue by DyncMark** [microsoft/TypeScript#43432]
Hi there! 

How to fix the problem below?

**The code:**
```
interface IRes {
  z: string
}

interface IRes1 extends IRes {
  x: string
}

interface IRes2 extends IRes {
  y: boolean
}

interface ITest {
  sub(t: string): IRes1
  sub(t: boolean): IRes2
  sub(t: string | boolean): IRes
}

class Test implements ITest {
  constructor() {

  }

  sub(t: string): IRes1 {
    console.log(t);
    return {
      z: '1'
    };
  }
  
  sub(t: boolean): IRes2 {
    console.log(t);
    return {
      z: '1',
      y: true
    };
  }
  
  sub(t: string | boolean): IRes {
    console.log(t);
    return {
      z: '1',
      y: true
    };
  }

}
```

**report log**:
```
Duplicate function implementation.
```

![image](https://user-images.githubusercontent.com/15116881/112975498-50ab9780-9186-11eb-9ba3-4938befaca19.png)

**Comment by MartinJohns** [comment]
See the documentation: [Function Overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads)

And better ask such questions on a support forum (e.g. StackOverflow). The issue tracker is not meant for questions, but for bug reports and feature requests.

**Comment by DyncMark** [comment]
> See the documentation: [Function Overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads)
> 
> And better ask such questions on a support forum (e.g. StackOverflow). The issue tracker is not meant for questions, but for bug reports and feature requests.

Thank you very much! Thank you for your answer and reminding！My english is very poor, but next time I will ask questions on StackOverflow！
