### ISSUE TITLE
Disabling `noImplicitAny` suppresses index type checking in bracket notation

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#43431]
Duplicated from #43323

# Bug Report

### 🔎 Search Terms

suppress error
index type
bracket notation
noImplicitAny

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behavior

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?noImplicitAny=false&ts=4.2.3#code/MYewdgzgLgBCBGArGBeGBvAvgbgLACgFEA6AMxBFRgEY9CkBtAInJCYF0rag)

### 💻 Code

`"noImplicitAny": false,`

```ts
const obj = {};
obj.foo = 1;
obj["foo"] = 1;
```

### 🙁 Actual behavior

```ts
obj.foo = 1; // Error: Property 'foo' does not exist on type '{}'
obj["foo"] = 1;
```

### 🙂 Expected behavior

```ts
obj.foo = 1; // Error: Property 'foo' does not exist on type '{}'
obj["foo"] = 1; // Error: Property 'foo' does not exist on type '{}'
```

When `noImplicitAny` is disabled (default), Index type errors are suppressed in bracket notation
Expected both `obj.foo = 1` and `obj["foo"] = 1` to throw an error

**Comment by MartinJohns** [comment]
Using the indexer like this is supposed to result in `any`, see #39128 (and others). And assigning `1` to `any` is a valid operation.
