### ISSUE TITLE
Array Type Intefrace paradox

### ISSUE THREAD

**Issue by S-ed** [Microsoft/TypeScript#4344]
This code will not throw an error:
```
interface Interface {
      a: any;
      [id: string]: boolean;
}
```
[id: string] is more general index than 'a', so the returned type of 'a' should be subtype of 'boolean'. But 'any' is more general than 'boolean'.
Am I right?

**Comment by mhegazy** [comment]
correct. any is special. it is both a subtype and a supertype of all other types. so it is more of a wildcard.

**Comment by DanielRosenwasser** [comment]
Specifically, we check if the types are *assignable*, which is in part affected by the rules of subtype/supertype compatibility. `any` can, in a sense, be *thought of* as a supertype/subtype of all other things, but really it comes down to what the TypeScript spec deems assignable.

From [3.9.4 Index Signatures](https://github.com/Microsoft/TypeScript/blob/82b78d85d77085412c87051fb50bf31126476683/doc/spec.md#3.9.4)
> ***String index signatures***, specified using index type `string`, define type constraints for all properties and numeric index signatures in the containing type. Specifically, in a type with a string index signature of type *T*, all properties and numeric index signatures must have types that are assignable to *T*.

From [3.11.4
