### ISSUE TITLE
Array Type Interface dotted notation

### ISSUE THREAD

**Issue by S-ed** [Microsoft/TypeScript#4345]
```
interface Interface {
      [id: string]: string;
}

var a:Interface = {
      b: 'foo'
};

a.b = 'bar';
```
Throws an error:
```
Property 'b' does not exist on type 'Interface'
```
Possible to solve? Maybe treat Array index as 'any':
```
var a:any = {};
a.b= "foobar";
```
This one is ok.

**Comment by mhegazy** [comment]
to access the member `b` you need to define it in the interface. e.g:
```ts
interface Interface {
      b: string;
}

var a:Interface;
a.b = 'bar'; // OK
```

alternatively you can use string indexing to access your property:

```ts
interface Interface {
      [id: string]: string;
}

var a:Interface;

a["b"] = 'bar'; // OK, type of a["b"] is defined in the string indexer definition in Interface
```

if you give a value the type `any`, it can have any number of properties, and the compiler will not enforce any rules there.
