### ISSUE TITLE
Signature overload not working with union type?

### ISSUE THREAD

**Issue by marechal-p** [microsoft/TypeScript#43469]
# Bug Report

A picture is worth a 1000 words:

```ts
function a(b: undefined): undefined
function a(b: string): number
function a(b: number): string
function a(b: string | number | undefined): string | number | undefined {
    return b
}

let c: string | undefined
a(c)
```

I would have expected `let c: string | undefined` to correctly be passed to the `a` function and return `number | undefined` but TypeScript complains.

Feel free to rework the title with the proper terms for that issue, I have no clue what's involved here.

### 🔎 Search Terms

type, inference, overload

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ notably https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwBQCMBcjwBMCmwMY+uAlNnocaQLABQoksCKG2AzlAE7EDmFRF15g+DJtHhI0WIT36IAPjjAEiJcp3milKtTVyIA3g0RnE3fFBDck6BgF8GDADZXEELSL66q6uvRoEGQMQA)

### 💻 Code

See description.

### 🙁 Actual behavior

TypeScript emits a compilation error.

### 🙂 Expected behavior

No error.

**Comment by RyanCavanaugh** [comment]
See #14107

**Comment by marechal-p** [comment]
Ok so mine is most likely a duplicate, thanks!
