### ISSUE TITLE
TypeCheckerHost interface should not be exported

### ISSUE THREAD

**Issue by adidahiya** [Microsoft/TypeScript#4346]
The `TypeCheckerHost` interface isn't referenced anywhere else in `typescriptServices.d.ts`. Is this an error? Unlike `LanguageService`, you can get a `TypeChecker` with `getTypeChecker()` on `ts.Program`. So exposing `TypeCheckerHost` seems unnecessary.

**Comment by mhegazy** [comment]
Sounds correct. A PR would be appreciated!
