### ISSUE TITLE
Types with index signatures lose all attribute signatures when using keyof or Omit

### ISSUE THREAD

**Issue by nuintun** [microsoft/TypeScript#43478]
# Bug Report

![企业微信截图_16172737442928](https://user-images.githubusercontent.com/1730277/113283886-70c08f80-931b-11eb-8020-87d08f9f58e1.png)

### 💻 Code

```ts
interface Route {
  name: string;
  path: string;
  href?: string;
  exact?: boolean;
  strict?: boolean;
  [key: string]: string | boolean | undefined | object;
}

type RouteNode = Omit<Route, 'name'>;

const route: RouteNode = {} as RouteNode;

route.p;
```

### 🙁 Actual behavior

Lose all attribute signatures

### 🙂 Expected behavior

Do not lose attribute signatures

**Comment by MartinJohns** [comment]
This is working as intended.

**Comment by nuintun** [comment]
@MartinJohns 

I wrote a tool that converts some properties of an object into optional, but it doesn't work.

```ts
type PartPartial<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

interface Route {
  name: string;
  path: string;
  href?: string;
  exact?: boolean;
  strict?: boolean;
  [key: string]: string | boolean | undefined | object;
}

type RouteNode = PartPartial<Route, 'name'>;
```

And the same `PartRequired` doesn’t work either.

```ts
type PartRequired<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>;
```

But `PartRequired` like this is work well.

```ts
type PartRequired<T, K extends keyof T> = T & Required<Pick<T, K>>;
```

**Comment by MartinJohns** [comment]
See the existing issues: #43139, #40999, etc. `Omit<T>` is using `keyof T`, and `keyof T` for types with indexers always results in `string | number`, so your individual properties are unavailable. This is working as intended, see #42436.

Issue #41966 mentions a workaround for this behavior (by excluding the index signature from the type).

**Comment by nuintun** [comment]
@MartinJohns 3Q~
