### ISSUE TITLE
generator function with custom interface throws error: Return type of exported function has or is using private name

### ISSUE THREAD

**Issue by ar-daniel** [microsoft/TypeScript#43481]
# Bug Report

### 🔎 Search Terms

Return type of exported function has or is using private name
TS4060, generator function with interface

### 🕗 Version & Regression Information

- checked with version 4.23, 4.15
strangely it doesn't throw any error in some of the code bases but throws error and crashes in some other code bases. The code in the playground link  does show this error

the issue https://github.com/microsoft/TypeScript/issues/42645
might be related - and it shows about classes not generator function hence the separate issue

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBAMwK4DsDGMCWEUCo4DOAhgLZgA2wAYsDGgBYAUAlHAN4BQc3cmKMwKAiJpgcNEgIwIJAJL9Bw0ey481mACYAuOCiQkARoIA0qtdxSlgOqVD4BzM3AC+HJzACeYMVGAEAKl5iALwq5jwESGiiBAQ6BhAQlEQoTmoaRDBEOhJSMvICQiLATq5OlPBIUORwoQAG9DAwYFoA9K2gpBTAAHRoMq32tHVuav0oUnC+BJAT1lN+gd61cB6YwOQaiLQMjFXkpuHcnEfmJLT0ENpwAOQA4gCi-jeHpzz0wEQagnHstwDCOAE-AAtEtgDcdDciGAKJg0JlsChWgArAg4G4uNI8ZzMHowD4oRjTWYEEIAPjCb24vhgVRQCxmODJPTROBY2O4uNGPHG6MoPXIEHsxL8pOAzA4riAA

### 💻 Code

```ts
export function* sampleFetch() {
    interface customInterface {
        id: number,
        name: string
    }

    type resType = {
        success: boolean
        data: customInterface
    }

    let url = `http://example.com/get`

    const response: resType = yield fetch(url,
        {
            method: 'GET',
            headers: { 'Content-Type': 'application/json' }
        }).then(response => {
            return response.json()
        })

    console.log(response)
}

```

### 🙁 Actual behaviour

Throws error at generator function - 
Return type of exported function has or is using private name ... ( ts 4060)

### 🙂 Expected behaviour

since the interface is used only within the generator and not returned/ used /called from outside- ts compiler should not throw any errors.

**Comment by RyanCavanaugh** [comment]
If you move the interface to the outside and look at the .d.ts, you can see it being used:
```ts
interface customInterface {
    id: number;
    name: string;
}
export declare function sampleFetch(): Generator<Promise<any>, void, {
    success: boolean;
    data: customInterface;
}>;
export {};
```
This is because of the contextual type on the `yield` expression. The type is observed when you call `next` with a value

**Comment by ar-daniel** [comment]
Thanks for replying, yes moving outside would solve the problem as the interface is now moved from block/ function scope to global scope. This is however not intended as we now wont be able to reuse same named interface (without declaration merging) and need to create new named interfaces for each generators in the global space results in cluttering the global scope.

seeing the return type of generator (in this case)
```
 Generator<Promise<any>, void, resType>
```
the resType is anyways a custom type declared within the generator, gets returned without issue
```
resType = {
        success: boolean
        data: {   // declaring the interface directly works
              id: number;
              name: string;
        }
    }
```
so my ideology is having a interface declared in the same scope should also work. 



__solutions to achieve this__
to use type instead of interface 
```
export function* sampleFetch() {
    type customType = {
        id: number,
        name: string
    }

    type resType = {
        success: boolean
        data: customType  // no errors now
    }
    .....
}
```

The whole thing of having a separate interface/ type can be considered merged as well.
This issue stemmed out of the need to use custom error interface which extends the built in error interface, thereby needing to be declare it separately
```
export function* sampleFetch() {
    interface customError extends Error {
        errParam1: number,
        errParam2: boolean  
        ...
    }

    type resType = {
        ....
        error?: customError   // throws error ts4060
    }
    .....
}
```
however a solution to make it work is to use intersection types to merge
```
export function* sampleFetch() {
   ...
    type resType = {
        ....
        error?: Error & {  // using intersection
            errParam1: number,
            errParam2: boolean
           .... 
        }
    }
    .....
}
```

having worked all this, I feel interface declared in the same scope should also work without issues just as it did with types.
