### ISSUE TITLE
 Object.fromEntries function  with chrome version 70 line , Angular TS

### ISSUE THREAD

**Issue by mapurba** [microsoft/TypeScript#43484]
Hi All,
I am seeing this issue with chrome version 70 line , Angular TS
tsconfig : "lib": `[ "es2018", "dom", "esnext" ]`
one thing to notice the vendor js in lazy loaded as the .

with the uses of `Object.fromEntries` in `.ts` throws the same error in chrome 70 line .

case .ts :` main.ts:12 TypeError: Object.fromEntries is not a function at new AppComponent (app.component.ts:15) at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:18) at getNodeInjectable (core.js:5993) at instantiateRootComponent (core.js:12873)`

case Vendor : `VM547 vendor.js:98199 Uncaught TypeError: Object.fromEntries is not a function at Module.<anonymous> (VM547 vendor.js:98199) at i (VM547 vendor.js:98199) at push../node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor.js (VM547 vendor.js:98199) at VM547 vendor.js:98199 at VM547 vendor.js:98199 at Object../node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor.js (VM547 vendor.js:98199) at __webpack_require__ (VM542 runtime.js:85) at __webpack_require__ (VM542 runtime.js:85) at Module../src/app/shared/shared.module.ts (VM545 main.js:2147)`

what is the right match so that all the dependency can be added in compile ?

but adding this to the polyfills make it work for all the cases .
`import "core-js/es/object/from-entries";`

ame right ?

*platform is web .

intention is to support the newer libs for older codebase dependency .

Thanks ,
Apurba M.

**Comment by nmain** [comment]
`tsconfig`'s `lib` property lets you tell `tsc` what kind of environment you intend to run your scripts in.  It's up to you to set up that environment at runtime.

https://www.google.com/search?q=polyfill+object.fromentries

**Comment by mapurba** [comment]
but adding this to the polyfills make it work for all the cases .
`import "core-js/es/object/from-entries";
`

ame right ?

**Comment by DanielRosenwasser** [comment]
What @nmain said. You'll need a polyfill like core-js or the like.
