### ISSUE TITLE
Assignment to getter

### ISSUE THREAD

**Issue by MarenkovIgor** [Microsoft/TypeScript#4348]
Following code is compiling without errors and warnings:
```typescript
class A {
    get c(): string {
        return "test";
    }
}

var a = new A;
a.c = "some str"; //It won`t work

console.log(a.c);
```

I think it`s wrong behavior. Typescript compiler should prevent assignment to property without setter.

**Comment by RyanCavanaugh** [comment]
See nearly identical duplicate #4237 and its root #12.
