### ISSUE TITLE
Error messages inconsistently use backticks and single quotes

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#43503]
A lot of new error messages use backticks where old messages use single quotes. Errors should use single quotes unless there's a good reason not to.

Specifically, 

* Backticks around tsconfig properties and values should use single quotes.
* 7035 has surrounds `declare module '{0}'` with backticks. That is probably correct, but only if the code that fixes the error literally includes a string, like `declare module "fs" {`
* 7040 has a single-quote/backtick mismatch that should just be single quoted.

If this is your first issue, you'll need to change diagnosticMessages.json, then `gulp runtests-parallel` followed by `gulp baseline-accept`. You should `git blame` error 7035 to look at the PR that added it.

**Comment by krishnaanaril** [comment]
I'm interested to submit a PR.

**Comment by sandersn** [comment]
Great! If you need help, try discord.gg/typescript. There are a couple of channels there where knowledgeable people hang out.
