### ISSUE TITLE
Dont highlight required arguments in function signature

### ISSUE THREAD

**Issue by TelyakovKostya** [microsoft/TypeScript#43507]
# Bug Report

### 🙁 Actual behavior

type someFunc = (first: string, sec: number) => string
const func: someFunc = () => '' // Dont highlight error

### 🙂 Expected behavior

type someFunc = (first: string, sec: number) => string
const func: someFunc = () => '' // Error, someFunc need required arguments

### Playground
https://www.typescriptlang.org/play?#code/C4TwDgpgBAzg9gWwgMQK4DsDGUC8UAUAZgJYBOMwAXLMKcegOYA0sEm16qCARhKQJS4AfDTqMAUJjjoKUQhnaxEKBbgKCcIgORaoAej1QAItOBQAFsQbmANlfNm+pOKSA

**Comment by DanielRosenwasser** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters
