### ISSUE TITLE
4.3.0 static #private incompatible with importHelpers and tslib 2.1

### ISSUE THREAD

**Issue by arciisine** [microsoft/TypeScript#43501]
# Bug Report

### 🔎 Search Terms

tslib 4.3 __classPrivateFieldGet

### 🕗 Version & Regression Information

4.3.0-dev.20210401

- I was unable to test this on prior versions because this is related to a new feature in 4.3

### ⏯ Playground Link
I'm unable to provide a playground link, as `importHelpers` is not reflecting in the playground, when selected.

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
```typescript
/**
 * Module utils
 */
export class ModuleUtil {

  static #handlers: ModuleHandler[] = [];
  /**
   * Add module post processor (post-load)
   *
   * @param handler The code to run on post module load
   */
  static addHandler(handler: ModuleHandler) {
    this.#handlers.push(handler);
  }
```
### 🙁 Actual behavior
The typescript compiler is showing the below error:

![image](https://user-images.githubusercontent.com/1264175/113414086-23c7d200-938a-11eb-8d52-b186a4cf233e.png)

And I can see in tslib 2.1 that there is no support for more than 2 parameters for `__classPrivateFieldGet`.  It looks like there is no compatible tslib for the 4.3.0 beta.

### 🙂 Expected behavior

`importHelpers` should be able to work with 4.3.

**Comment by DanielRosenwasser** [comment]
@rbuckton can you port the helper changes and additions over to tslib? I'll also need some help figuring out versioning there.

**Comment by arciisine** [comment]
Looks like a PR has already been merged to update the helpers: https://github.com/microsoft/tslib/pull/146.

**Comment by rbuckton** [comment]
@DanielRosenwasser As far as tslib is concerned, the tslib change is backwards compatible so we can publish as a minor or patch version.

**Comment by DanielRosenwasser** [comment]
tslib 2.2.0 should fix this.
