### ISSUE TITLE
Regression: Tagged types are incorrectly refined

### ISSUE THREAD

**Issue by arcanis** [microsoft/TypeScript#43502]
# Bug Report

### 🔎 Search Terms

refine regression 4.3 refine never

### 🕗 Version & Regression Information

Worked with 4.2, stopped working with 4.3 beta

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.3.0-dev.20210402#code/C4TwDgpgBAEghgZwBZQLxQcATgSwHYDmUAZFAN4D6FSiSAXFNgK4QC+A3AFCcBmTeAY2A4A9nigEIweMgAyEQsCQAKGsgYykASgZ4mAWwBGELOU5QLUAPRWoAQSjHMUCDx4iswKAKQQBAayh8b0RoESZTPkFhMSCEKCYECAATRxAoSBEwABtoAHdcYUIoACkAZXNLHB4oZVBMmrUUAEJUdAADTFxCdq1Ky0YkLBE8qDwIUYBRLGGsZXaAFSQceOSRCAQ8AHIvbJERQOycf2g4KCbern6oLCkI8SaAOlzFJC5WTiA

### 💻 Code

```ts
type Hash = string & {__hash: true};

function getHashLength(hash: Hash): number {
    // A best effort check in case our function is used by people writing JS
    if (typeof hash !== `string`)
      throw new Error(`This doesn't look like a hash`);

    return hash.length;
}
```

### 🙁 Actual behavior

The `hash` variable is incorrectly refined to `never`.

### 🙂 Expected behavior

The `hash` variable should remain `Hash`, since the `typeof` check is coherent with `Hash`.

**Comment by arcanis** [comment]
An ugly workaround if you don't use Prettier is to do (note the extra parentheses):

```ts
if ((typeof p) !== `string`)
  throw errors.EBADF(`read`);
```

**Comment by ahejlsberg** [comment]
Hmm, yes this is an effect of #43131. The fixes to `getTypeFacts` are in principle correct, except that here we think that `typeof` is both `"string"` and `"object"`, which is impossible and therefore gets us to `never`. In tagged primitive types like this we should really consider the primitive type be to dominant. I'll put up a PR to that effect.
