### ISSUE TITLE
Compile on Save not Working Console App

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#4350]
Hey,

Both myself and a colleague have hit this issue today.

We have a number of projects that use TypeScript, each .TS file has been added through the  Add New Item  menu and so each one has a  TypeScriptCompile  element in the project file. The projects in question are either library or console projects. 

We are compiling our typescript as AMD modules, the JavaScript files are not combined or minified or have any other processing done to them as they are simply embedded resources in the assemblies.

**Comment by paulvanbrenk** [comment]
@ProfessionalNihilist did that work before? Which version of VS are you using? Do you see a TypeScript Build Tab in the project properties? And to confirm you're using a "Windows Console App".

**Comment by Serguzest** [comment]
@paulvanbrenk  

I see the same buggy behaviour in the project type which created with "file -> open -> website"

I created test.ts file with notepad. Not through visual studio..

It compiles succesfully with tsc test.ts command, however not Visual studio 2015, TS 1.5.4
It was working before the update. (Btw, how can I revert this?)

![image](https://cloud.githubusercontent.com/assets/841238/9337324/6552b646-45e7-11e5-82be-01ddd9900b9d.png)

![image](https://cloud.githubusercontent.com/assets/841238/9337411/e5625cba-45e7-11e5-85d3-3f3d2341b84f.png)

**Comment by paulvanbrenk** [comment]
@Serguzest I'm afraid there is no way to revert to 1.5.3, however I did identify the bug you're encountering and have a fix which will be in 1.6.

**Comment by Serguzest** [comment]
@paulvanbrenk that's unfortunate. 

People who are affected of this bug can still use tsc --watch from commandline to continue the development. I am using the one installed with NPM.

**Comment by ProfessionalNihilist** [comment]
@paulvanbrenk Visual Studio 2015 Enterprise, Class Library project. There is no TypeScript Build tab in project properties (there never has been either).

**Comment by paulvanbrenk** [comment]
@ProfessionalNihilist That's what I expected, in that case the fix I put in for @Serguzest will work for your case to.
