### ISSUE TITLE
Tagged Unions are not discriminated if the tag field is a symbol

### ISSUE THREAD

**Issue by mikearnaldi** [microsoft/TypeScript#43512]
# Bug Report

The type of a tagged union is not discriminated if the field is index via a unique symbol

### 🔎 Search Terms
Tagged Union Symbol

### 🕗 Version & Regression Information
All versions

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBAYwgOwM7wPoBUBccCuyAlgI77ByoCeAtgEYQA2cAvHAMq0OMAUAlACgBoSLDgwqYCgHkwMIigA8AQQB8rOAG84AbWwBdPACIAcimBG4AXzgAfLboPH2EGhYDclV8DzLrQgBNgBEYAQygKJDR4EDxZeSVkfHpgKFUhVAB3IhgEAAs4HhA9LH0+LQE4RFDUCiMXNyM8TUqquBBWqroI0IBrVqtWhBq6s2QLZs64buA+gYFBoA

### 💻 Code

```ts
export const _T: unique symbol = Symbol()

export type Option<A> = { [_T]: "None" } | { [_T]: "Some"; some: A }

declare const x: Option<number>

switch (x[_T]) {
  case "Some": {
    x
    break
  }
  case "None": {
    break
  }
}
```

### 🙁 Actual behavior

The type of `x` remains `Option<number>`

### 🙂 Expected behavior

The type should be narrowed to `{[_T]: "Some", some: number}`

**Comment by whzx5byb** [comment]
duplicate of https://github.com/microsoft/TypeScript/issues/43220

**Comment by mikearnaldi** [comment]
Indeed a duplicate, haven't found the other
