### ISSUE TITLE
Contextual typing breaks with partially applied type arguments

### ISSUE THREAD

**Issue by myandrienko** [microsoft/TypeScript#43524]
# Bug Report

### 🔎 Search Terms

partial type argument inference, contextual typing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type inference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgApQPYAcDOAeAFQGUEALCAWzgBpkCA1OAGwFcIA+ZAbwFgAoZMgDmEMJCgAuZAAoAbszY4pxMpTgBKZAF5ODBRADc-QQHcMUANbQpc-csasImnclkZgAEyN8Avv34eEAhMcFAoMCwgCGDAGCDIMCCEJORUtHqO7NJYmLhS6Nj4Kqk0dA5s7OpSbp7e-BFRMXHIAEagHilqyapUWZq8AshhYCxQ8Q3RsfEtGJEeAGJJGRXZuUpoa90l6eUc-caCCSCrheregj7efnz8CHE4YK2zIAvxWq3tnVR4XMg4GBQILspCAWBQWtBkD4+nU+DM5otpANBCIxNYZPJHDhnJxMYoAHT-QG7agHMyWdG2Rw47gHQQAenprn0yGAOGQkQsIAwJniEmkB2uPjO-CAA)

### 💻 Code

```ts
interface Props<TSchema, TValue> {
  getter: (values: TSchema) => TValue;
  worker: (value: TValue) => void;
}

declare function fn<TSchema, TValue>(props: Props<TSchema, TValue>): void;

function bindSchema<TSchema>() {
  return function boundFn<TValue>(props: Props<TSchema, TValue>) {
    fn(props);
  };
}

const boundFn = bindSchema<{ someValue: number }>();

boundFn({
  getter: (values) => values.someValue,
  worker: (value) => {
    // value is unknown :(
  }
});
```

### 🙁 Actual behavior

`value` parameter type in `worker` method (line 18). is not inferred. `value` type is `unknown`.

### 🙂 Expected behavior

`value` parameter type should be correctly inferred as `number`.

This code sample works fine, which is also surprising since the type for `values` parameter in `getter` method (line 17) is correctly inferred as `{ someValue: number }` anyway:

```ts
boundFn({
  getter: (values: { someValue: number }) => values.someValue,
  worker: (value) => {
    // value is number 👍 
  }
});
```

**Comment by ilogico** [comment]
Looks like #43371
