### ISSUE TITLE
Support Native Private Field Emission

### ISSUE THREAD

**Issue by arciisine** [microsoft/TypeScript#43521]
# Suggestion

## 🔍 Search Terms

Private field emission

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In Node 15+ (v8 8.x), the runtime provides complete support for native private fields, and methods. This additionally includes static level fields/methods as well. Node 12+ includes some support, but does not completely cover the private field specification.

Currently, the compilation target ESNext produces the WeakMap implementation, which incurs performance overhead.  It would be ideal to be able to emit native code when possible, even if its behind a feature flag.

## 💻 Use Cases

More efficient code, and better runtime performance, by offloading complexity to the underlying engine.

**Comment by jtbandes** [comment]
Chrome/V8 also has support for [private fields](https://www.chromestatus.com/feature/6035156464828416) and [private methods/accessors](https://www.chromestatus.com/feature/5700509656678400): https://v8.dev/features/class-fields

**Comment by MartinJohns** [comment]
> Currently, the compilation target ESNext produces the WeakMap implementation

This is not true for TypeScript 4.2: [Playground link](https://www.typescriptlang.org/play?target=99#code/MYGwhgzhAEBiD29oG8BQ0PQMQCMwCdoBeaAIjB2FNQF8g)

**Comment by arciisine** [comment]
The playground appears to be behaving oddly, when I pull up the link above, I see the output target as ES3.  

Additionally, I had an override locally that I had missed, and setting the output to ESNext does indeed seem to preserve the native private syntax.  This means this is working as intended and can be closed.
