### ISSUE TITLE
Declaration-like jsdocs are incorrectly attached to the following statement

### ISSUE THREAD

**Issue by thorn0** [microsoft/TypeScript#43534]
# Bug Report

### 🔎 Search Terms

jsdoc docblock typedef

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210403&useJavaScript=true#code/PQKhAIAEBcE8AcCmATRAzcBvTaD2uAucAcj12IF8LwAxfcEYAWAChX2W0BXAOwGNoAS1w9waABQBKLKwocOEyUA)

### 💻 Code

```ts
/** @typedef {{foo: 'foo'}} Foo */

function f() {
}

f()
```

### 🙁 Actual behavior

Whenever JSDoc typedef blocks are followed by a function (or variable) declaration TS attaches that JSDoc to the function and shows typedefs as part of the function's description when its name is hovered.

![image](https://user-images.githubusercontent.com/94334/113485775-085ae500-94b8-11eb-89d8-97cf5f4df1b9.png)

(The described behavior is old, but the screenshot of v4.3.0-dev is here to show an extra bug with `[object Object]`.)

### 🙂 Expected behavior

Typedefs shouldn't be attached to subsequent statements.

As @sandersn wrote in https://github.com/microsoft/TypeScript/issues/42895#issuecomment-813487362:

> Declaration-like jsdocs are incorrectly attached to the following statement. The fix is probably as simple as a filter somewhere -- the compiler itself doesn't care where `@typedef` is, only the services layer does -- but I'm not sure which component should do the filtering.

**Comment by sandersn** [comment]
I can't repro the `[object Object]` bug with the latest dev build.

@thorn0 Do you care about the extraneous `@typedef` in the quick info for VS Code, or in the services API, or somewhere else?

**Comment by thorn0** [comment]
v4.3.0-dev.20210413 on the playground shows `[object Object]` to me.

> Do you care about the extraneous @typedef in the quick info for VS Code

In VS Code. Are you considering keeping the comment attached to the statement and only hiding typedef tags from it? Not a bad option, but typedefs can have their own descriptions in the same comment, and these descriptions won't be hidden in that case, right?

BTW, currently the descriptions are concatenated in an interesting way ([playground](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210413&useJavaScript=true#code/PQKhFgCgAIWhJADgZwK4Fsq2gAQC4CeiApgCbEBm0A3tRQPb0Bc0A5A-awL5fQBijaABl6AJ2LpYwKDMgVUAOwDGeAJb0F0CgAoAlDShdZxyFFBx8RYjQH1eIaZABuAQ1HQXAblk7dQA), [playground 2](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210413&useJavaScript=true#code/PQKhFgCgAIWhJADgZwK4Fsq2gAQC4CeiApgCbEBm0A3tRQPb0Bc0A5A-awL5fQBijaABl6AJ2LpoWONOgAhADYBDAIyz8RMpRrUARktEtW+0d15yD85QCZpwKA8gVUAOwDGeAJb0X0CgAoAShooLkdwyChQOA0SGgF6XhB7SAA3SyUAbkdo3EI46gtRJJT00WhdbMinIKA)):
![image](https://user-images.githubusercontent.com/94334/114657413-b22c4400-9cf8-11eb-9b5d-23ecb55a15d1.png)
But it's a separate issue I guess.

**Comment by sandersn** [comment]
`[object Object]` is happening because, I'm pretty sure, the language server thinks the playground wants the new displayparts format for comments instead of the old string format. This doesn't happen on my slightly old version of Code or my up-to-date emacs, which I think covers the two main code paths. I'll file a bug to track down whether this is just our use of Monaco or whether it applies to all Code-family editors.

jsdoc is parsed as an optional leading comment (In the above screenshot, "Ipsum") and a sequence of tags with optional trailing comments. So

```ts
/** @typedef {number} N Some commentary
  @type {N} More commentary */
var n = 12
```

would only show the `@type` tag and "More commentary" after the typedef is filtered out.

**Comment by sandersn** [comment]
Filed #43672 for the playground [object Object] mis-rendering.

**Comment by thorn0** [comment]
```js
/**
 * Ipsum
 * @typedef {{foo: 'foo'}} Foo Lorem
 */

function f() {
}
```
corresponds to the following TS syntax:
```ts
/**
 * Ipsum
 * Lorem
 */
type Foo = {foo: 'foo'};

function f() {
}
```
So I think showing "Ipsum" in the quick info for `f` most of the times would be surprising,
