### ISSUE TITLE
Inconsistent behaviour of mapped type

### ISSUE THREAD

**Issue by garronej** [microsoft/TypeScript#43539]
# Bug Report

### 🔎 Search Terms

keyof T[K] mapped type

### 🕗 Version & Regression Information

3.3.3 up to 4.3.0.beta

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs that aren't bugs
- I was unable to test this on prior versions because I tested in playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/FAFwngDgpgBAsmA8gIwFZQMYgLwwN7AxEwDmUIAYgPZUBcMAFAwJTYB8MAblQJYAmzGAB8YAVwB2fKADMe4qHwDcwAL7LgoSLAQAVLQEYAPDo7YCxGAG0A0lDAw5MANZ2q0mDoC69BAFEAHiAATgCGWAp60MY2dp5symoamtDwYJFQAEzGpubEMfaOLmBuHt4e+Z4wUIFQkgDOMBQSWDxU4jAA-DAARBSIiN0w9PKcUEEJ6uApfoGh4Xzp2TC4OlU19Y3NIK3tXb39g8NQo+NJU7CIoiD6y6npRggo6FjxMAD0b3ik5NR0PX0DRQwFTJC5XDK3XRaLKPNCYECvD5fMiUGhHE5AlQwZBXGAAd1g1WgWBglxAEJAVGxsBAAAtYHUQgBbGlaGAhBpk-QAOg0HwAaiEADb8ELbNp8t46KB1EAeGAYGAAVWARKoQTl0i2OxgfCoARAtT4dWMa0NGyVABplWwWPRViIlcIuLw+PhgRpzjAAsTDW7cMifmj-gdgeoPtLZaSrjdcD74QpgHqDUaTVzrfH5rbmMpk+tjYZM37rVzs+pgBGZXKyRC4-5fYm8+aCzWM-WE3wy0n9fmTUWFCXwWX3m9DHXfXISDBxFSxkF1TB6UEoElVxogA)

### 💻 Code

```typescript
type MyObject= {
    getFoo: (()=> void) | undefined;
};

type MyType1<T> ={
    [Key in keyof T]: MyExtractedType<T[Key]>;
};

type MyType2<T> ={
    [Key in keyof T]: T[Key] extends Function ? "FOO" : never;
};

type MyExtractedType<T> = T extends Function ? "FOO" : never;

type Out1 = MyType1<MyObject>; //{ getFoo: "FOO"; }
type Out2 = MyType2<MyObject>; //{ getFoo: never; } but we expect Out2 to be the same type as Out1. 
```

### 🙁 Actual behavior

`MyType2<MyObject>` is  `{ getFoo: never; }`  

### 🙂 Expected behavior

`MyType2<MyObject>` is expected to be `{ getFoo: "FOO"; }`

**Comment by rickwebiii** [comment]
I think the compiler is actually correct in a fairly non-intuitive reason: conditionals distribute through unions:

Consider what happens when you do the substitution yourself:

```
type Foo =  ((()=> void) | undefined) extends Function ? true : false; // false
```

Out2 is actually the "expected" behavior, not Out1. The `| undefined` prevents `T[Key]` from extending function. If you remove the `| undefined`, you get true. So now why does Out1 resolve to "FOO"?

Conditionals distribute Distribution is doing the equivalent of this:
```
type Foo =  
  (()=> void) extends Function ? true : false) 
  | (undefined extends Function ? true : false); // true.
```
However, your branches are "FOO" | never, and never unioned with anything is just the thing. I.e. "FOO" | never = "FOO."

See
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types
and 
https://stackoverflow.com/questions/55382306/typescript-distributive-conditional-types

**Comment by DanielRosenwasser** [comment]
But I would think that `T[Key] extends Function` would distribute over the instantiated type of `T[Key]`. We usually ask the question of whether the left side of the `extends` is a "naked type parameter" (e.g. `T`) or an indexed access type `(e.g. `T[K]`). @ahejlsberg or @weswigham may know more.

**Comment by rickwebiii** [comment]
Is it not distributing over this?
`type MyExtractedType<T> = T extends Function ? "FOO" : never;`

**Comment by rickwebiii** [comment]
Changing the playground ever so slightly (changing `never` to `[never]`) illustrates things a little more clearly. 

https://www.typescriptlang.org/play?ts=4.3.0-beta#code/FAFwngDgpgBAsmA8gIwFZQMYgLwwN7AxEwDmUIAYgPZUBcMAFAwJTYB8MAblQJYAmzGAB8YAVwB2fKADMe4qHwDcwAL7LgoSLAQAVLQEYAPDo7YCxGAG0A0lDAw5MANZ2q0mDoC69BAFEAHiAATgCGWAp60MY2dp5symoamtDwYJFQAEzGpubEMfaOLmBuHt4e+Z4wUIFQkgDOMBQSWDxU4jAA-DAARBSIiN0w9JbynFBBngnq4Cl+gaHhfOnZMLg6VTX1jc0gre1dvf2Dw6Pjk0kzsIiiIPqrqelGCCjoWPEwAPQfeKTk1HQ9PoDRQwFTJK43DL3XRaLLPNCYEDvL4-MiUGj0U5BEEqGDIG4wADusGq0CwMGuIChICoeNgIAAFrA6iEALb0rQwEINSn6AB0wCAA

Out1 is now `"FOO" | [never]` and Out2 is now `[never]`. The former distributes, the latter does not.

**Comment by rickwebiii** [comment]
@DanielRosenwasser Oh I see. The question is "Is `T[Key]` considered a naked type parameter?" I would expect it to immediately resolve to the type associated with `Key`, and thus the answer would be no but my expectations are not a specification and I'm not an expert on type theory :)

**Comment by andrewbranch** [comment]
> We usually ask the question of whether the left side of the extends is a "naked type parameter" (e.g. `T`) or an indexed access type (e.g. `T[K]`)

[We don’t distribute over indexed access types](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/C4TwDgpgBAqgjFAvFA3lAHgLigIgBYQA2hA9jlAL5QA+qG2AdgK4C2ARhAE6U11ZRsSJQhACGDSgG4AUNNCQoAcQjAAciQYARAJYBnYJ21smwbQDcIAHgAqAGigBpKBHTAIDACa6oAawggSADMoawA+JBCAbQcAXWdXdy8ofUMGAHMoAH4o2KhGCAtOGXlodWAdFKMTCA8I5TUNCoMq0wtLeHsAcnRO8IB6PqgGAq57DgBjUSZdaAADa2iY2ag9KFn8IlJyWmZ2Ll5BYTEGZYB3PG1xvBXvBhJgKFFkpjYSqCC1yvTZ2Tf6psMxlaVjsjnibk83j8AWCYQi1nBiW8TAYPjupwk2QWuRcEKSXwyWMWeSGI24+UKxXA0ABLRqdRUtKB5isHSg3V6kigA1wBGIZDGEEm02gp2gHj0zSB9MC2k4+mkQA), so this looks totally expected to me.

**Comment by garronej** [comment]
Thanks for your answers 

> We don’t distribute over indexed access types

Why? For performance reasons?

**Comment by andrewbranch** [comment]
I can’t speak authoritatively to that, but I think it’s likely more for flexibility/usability. If you have a distributive conditional type and you want to make it not distributive, you can easily make this change:

```diff
- type C<T> = T extends { x: number, y: unknown } ? T['y'] : never;
+ type C<T> = [T] extends [{ x: number, y: unknown }] ? T['y'] : never;
```

If you have a conditional type that is not distributive and you want to make it distributive, you can easily make this change:

```diff
- type C<T, K extends keyof T> = T[K] extends string ? K : never;
+ type C<T, K extends keyof T> = T extends unknown ? T[K] extends string ? K : never : never;
```

To me, that’s easier than trying to remember which special forms are distributive over what (e.g. was `T[K]` distributive over `T` or over `K`? Is `T[]` distributive? It’s only one character off from `T[K]` 🤔). There’s only one special form that’s distributive, and it’s the simplest possible form.

**Comment by garronej** [comment]
Brillant thanks
