### ISSUE TITLE
getYear() is missing from Date interface

### ISSUE THREAD

**Issue by guerrerocarlos** [microsoft/TypeScript#43550]
`getYear()` is missing from `Date` interface

**Comment by MartinJohns** [comment]
This is likely intentional: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getYear

> **Deprecated**  
> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
