### ISSUE TITLE
Eager union narrowing when using callbacks

### ISSUE THREAD

**Issue by sploders101** [microsoft/TypeScript#43561]
# Bug Report

### 🔎 Search Terms

- union type callback
- type narrowing callback

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about callbacks

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210406#code/PTAEEFQCwUwGwA4wE6gGYFcB2BjALgJYD2WoeUAhnqDhXHAM5mw11wBGFOA1qAwJ64oyEkQwM4-UBSxSsGALbsUoImjIEFMBgDoAUCAg0iChSVAwAHhQUI4MVevIEmOEjhgJqLiMmQV+HQQRPCI8fiQdNCJkAFEuKD1MXEJzCgAJeCRkAAocdgAuUByGExhnLABzIoY8ZAIq0AAfUHl6AEpQAF4APlAANyICABNOgG89UCmadhyAIkz6Ijn2gG5J6fyctrg1jamtuYB1GLhhgEIV9YBfPQMwI-8EC2tbe2NhhwbpdGx8YlIoVAcE0BGo-Qo9Qo7HeDDcSGkWGGoE+ZiwtX8eAcyHKGGQgIiMCSf1SpAoABUoA1KjlxvtQIYAGqQgjQ94+T5oBowZEAdzBUB+tSoBBwoGwALIhPp9mopS0FWqfDq1OarQw9G66vo62mDLAi2yvywpNAPmQ2AANIjkeQHLR6JweGbXGweXwYP0UHQNFoGPSMlkUDkcorOr1QBM9XrDOA5WVQAghiaUXjVc4mMEiB4GAxrQADeXlKlVfPGDXImBI8XPChMCjK+pVel6ghoUMlyqdIuKrWK3XTa57GNgABCGGo4SQcPqXj4ASYYOkcF5C9AOLwePR2rg+j1G63fDK-b0t3uoAAShQXA4ZBY-DEzeoMaqfFgwmbcHAMJ9kd87eKWAAnobjotQMhhLAyCUtSRQXri+LkoSAA8U4wGo0gwVUfRdKAcxYrU1JzKsQA)

### 💻 Code

```ts
// A helper function that calls the callback synchronously any number of times.
// A common example of this concept is Array.prototype.forEach
function aHelper(cb: (something: string | null) => void) {
    cb("Hello world!");
}

// Wrap example code in a function to limit variable scope and demonstrate return type
function aThing() {
    // Variable is explicitly defined with a union type
    let something: string | null = null;
    // Helper funtion is run, and the callback is called several times
    aHelper((thing) => {
        // At some point during this process, `something` could end up as a string
        if(thing) something = thing;
    });
    // But typescript says it always returns null.
    return something;
}

// Raise an error if string is not included in the union (useful for regression testing)
const anotherThing: ReturnType<typeof aThing> = "testing";
```

### 🙁 Actual behavior

`aThing`'s return type is eagerly narrowed and Typescript says it can never return a string, when it definitely can, and in this case, does.

### 🙂 Expected behavior

Typescript recognizes that a callback is used and disables type narrowing for that scope, reverting the variable back to the types I said it could have (or similar; Typescript just shouldn't be narrowing types like this unless it is 100% confident that the value can never be of the type it omitted).

**Comment by jcalz** [comment]
Duplicate of #9998

**Comment by sploders101** [comment]
Indeed it is, thank you! Closing...
