### ISSUE TITLE
noImplicitOverride complains about static property not overriding non-static property

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#43563]
# Bug Report

### 🔎 Search Terms

- noImplicitOverride
- static

### 🕗 Version & Regression Information

4.3.0-dev.20210406

### 💻 Code

Using `--noImplicitOverride`:

```ts
export class Foo {
    kind = 1
}

class SubFoo extends Foo {
    static kind = '123';
}
```

### 🙁 Actual behavior

On `static kind = 123`, I see:

```
This member must have an 'override' modifier because it overrides a member in the base class 'Foo'.
```

### 🙂 Expected behavior

I don't think this should be an issue. `SubFoo.kind` is distinct from the `Foo.kind` instance property

**Comment by Kingwl** [comment]
Thanks! I'll take a look soon
