### ISSUE TITLE
Generic return type

### ISSUE THREAD

**Issue by MarvelSQ** [microsoft/TypeScript#43568]
# Bug Report

### 🔎 Search Terms
Generic with condition

### 🕗 Version & Regression Information

version 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghiARhAPAFQDRQGJQLxQB2ArgDakB8+UaUEAHsBIQCYDOREAbhAE5QB+HFABcNANwAoSQHoZUAOQlyCyaEhQAgtULc+dRs3ace-IctKiTfKbPlK9vVeugAhavCSpdprBYriQA)

### 💻 Code

```ts
type Maybe<T, F = null> = T extends never ? F : T;

// 'null'
type A = never extends never ? null : never;

// 'never'
type B = Maybe<never, null>;
```

### 🙁 Actual behavior

type A is null
type B is never

### 🙂 Expected behavior

type A & type B both are null

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/31751

**Comment by MarvelSQ** [comment]
> Duplicate of #31751

thanks
