### ISSUE TITLE
Property using `declare` prompts to add 'override' even though that does not seem valid

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#43566]
# Bug Report

### 🔎 Search Terms

- noImplicitOverride
- static

### 🕗 Version & Regression Information

4.3.0-dev.20210406

### 💻 Code

Using `--noImplicitOverride`:

```ts
export class Foo{
    kind = 1;
}

class SubFoo extends Foo{
    declare kind: undefined;
}
```

### 🙁 Actual behavior

On `declare kind: undefined`, I see:

```
This member must have an 'override' modifier because it overrides a member in the base class 'Foo'
```

Adding `override` makes the code invalid

### 🙂 Expected behavior

We should probably change our code to:

```ts
class SubFoo extends Foo{
    override kind: undefined;
}
```

However using `declare` was previously valid and the current error message seems incorrect

**Comment by fregante** [comment]
If anyone lands here from Google, you can either:

- add `"noImplicitOverride": false` to your tsconfig (just to silence it temporarily)
- add the `override` keyword to the methods TypeScript mentions

**Comment by Hatem-Nofal** [comment]
> If anyone lands here from Google, you can either:
> 
> * add `"noImplicitOverride": false` to your tsconfig (just to silence it temporarily)
> * add the `override` keyword to the methods TypeScript mentions

it's work thanks

**Comment by BenRacicot** [comment]
I noticed that `public` does not cause TS to give this error. `private` was.
