### ISSUE TITLE
Type assertions do not meet expectations

### ISSUE THREAD

**Issue by gds-prue** [microsoft/TypeScript#43573]
The first case
![image](https://user-images.githubusercontent.com/35244704/113864969-1ffadc00-97de-11eb-9e7d-6c22cd1f9213.png)
The second case
![image](https://user-images.githubusercontent.com/35244704/113865006-2be69e00-97de-11eb-8ca5-9b907400cd4a.png)

I want to know why the first case does not report an error

**Comment by MartinJohns** [comment]
The [documentation](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) says:

> TypeScript only allows type assertions which convert to a *more specific* or *less specific* version of a type. This rule prevents “impossible” coercions like:

The error message indicates this:

> Conversion of type '{ w: string; }' to type 'B' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

The keyword here being "sufficiently overlaps".

> I want to know why the first case does not report an error

In your first example you assert to a more specific version, which is legal. Type assertions are a way to tell the compiler "this isn't right according to the types, but just trust me on this".

In the second example your types don't overlap at all, so the type assertion reports an error.

---

Personally I would avoid type assertions as much as possible. They can easily hide errors.

**Comment by gds-prue** [comment]
Okay, but this is a very confusing phenomenon
