### ISSUE TITLE
Incorrect sourcemap/ Breakpoints not being hit

### ISSUE THREAD

**Issue by richardbullin** [Microsoft/TypeScript#4357]
I've been having issues getting my breakpoints to hit.

Please refer to previous bug #1980 "Incorrect sourcemap for comments in module function" as I don't believe this has been fixed. Please read through the comments to get my previously listed example source code to help reproduce the issue.

I just updated to typescript v1.5.3 and the sourcemaps being generated are exactly the same as the sourcemaps for versions  1.1.0-1, 1.3.0 and 1.4.1 (which do not work). If I revert to v1.0.1 with the same source the breakpoints get hit correctly.

**Comment by richardbullin** [comment]
Hmm related to #2880 and #2014, whats the status of this problem? Sorry I'm new to Github. #1980 and #2014 says closed and #1980 was closed in typescript 1.5? But then the merged #2880 says it was also merged into 1.5? Have the fixes not been released?

**Comment by sheetalkamat** [comment]
@richardbullin this is fixed by #4086, which is not yet in any of the release.

**Comment by richardbullin** [comment]
:+1:

**Comment by mhegazy** [comment]
@richardbullin can you give the nighties a try to make sure the issue has been fixed. `npm install typescript@next`.

**Comment by richardbullin** [comment]
@mhegazy Yep that worked :+1:

**Comment by mhegazy** [comment]
thanks @richardbullin for verifying.
