### ISSUE TITLE
Incremental Compile time is slower when we make changes to typescript file in specific directory

### ISSUE THREAD

**Issue by last-Programmer** [microsoft/TypeScript#43574]
When we make changes to typescript files in specific directory the  check time is very high. Here is the diagnostics

Files:                         8981
Lines of Library:             28452
Lines of Definitions:        129250
Lines of TypeScript:         367043
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Nodes of Library:            122037
Nodes of Definitions:        337308
Nodes of TypeScript:        1470410
Nodes of JavaScript:              0
Nodes of JSON:                    0
Nodes of Other:                   0
Identifiers:                 633783
Symbols:                     745181
Types:                       504122
Instantiations:             3279398
Memory used:               1621541K
Assignability cache size:    274665
Identity cache size:           2827
Subtype cache size:            3938
Strict subtype cache size:      570
I/O Read time:                0.34s
Parse time:                   3.58s
ResolveModule time:           1.63s
ResolveTypeReference time:    0.02s
Program time:                 6.40s
Bind time:                    1.71s
Check time:                  43.80s
printTime time:              17.72s
Emit time:                   17.85s
transformTime time:           5.93s
Source Map time:              0.78s
commentTime time:             1.18s
I/O Write time:               1.40s
Total time:                  69.75s

At the same time we make changes to typescript file in some other directory we get these result
Lines of Library:            28452
Lines of Definitions:       129250
Lines of TypeScript:        367045
Lines of JavaScript:             0
Lines of JSON:                   0
Lines of Other:                  0
Nodes of Library:           122037
Nodes of Definitions:       337308
Nodes of TypeScript:       1470416
Nodes of JavaScript:             0
Nodes of JSON:                   0
Nodes of Other:                  0
Identifiers:                633785
Symbols:                    324526
Types:                        4819
Instantiations:              12015
Memory used:               616608K
Assignability cache size:     1736
Identity cache size:            22
Subtype cache size:             12
Strict subtype cache size:       0
I/O Read time:               1.13s
Parse time:                  3.69s
ResolveModule time:          1.68s
ResolveTypeReference time:   0.02s
Program time:                7.37s
Bind time:                   1.74s
Check time:                  0.80s
printTime time:              0.53s
Emit time:                   0.53s
transformTime time:          0.04s
Source Map time:             0.01s
commentTime time:            0.02s
I/O Write time:              0.02s
Total time:                 10.45s

the check time with problem directory is very high. Is there anyway i can debug why the check time is taking so long in specific directory

Thanks in advance

**Comment by RA80533** [comment]
Take a look at [Performance-Tracing.md](https://github.com/microsoft/TypeScript-wiki/blob/b95e981dd9b332399f09f641327b87f371392450/Performance-Tracing.md) (specifically, the `generateTrace` flag):

```console
$ tsc --generateTrace trace/ --incremental false
```

**Comment by last-Programmer** [comment]
Thank You. I looked at it. Let me explain our project structure.

We have /React/Generic/**/** and have all the generic controls used in our project. We heavily use barrels. We export all the controls in the Generic folder via /React/Generic/Generic.ts. The consumer folder is /React/Pages/**/** where we import from the barrel file Generic.ts.

By seeing the trace with incremental when we make changes to a file /React/Pages folder that is the only file appears in the check file phase

However when we make changes to a file in /React/Generic folder Check File runs for all the files in the project. 

Is it because of we are importing from Generic.ts barrels or am i missing something?

Cant we use barrels with typescript?

Thanks

**Comment by RA80533** [comment]
Do you just have the one tsconfig.json? What do your include fields look like?

**Comment by last-Programmer** [comment]
I have only one tsconfig.json /React directory and i run tsc in that directory. I don't have anything specified in the include field.

**Comment by RA80533** [comment]
Do files within the /React/Generic directory import modules within that directory through the barrel file at /React/Generic/Generic.ts or is it just the files in /React/Pages? I don't know enough about the compilation process to suggest that the barrel files are problematic because they're barrel files; they might be entangled in circular imports, however.

**Comment by last-Programmer** [comment]
There is no generic.ts -> generic.ts import. Only ./React/Pages import
Generic.ts

**Comment by andrewbranch** [comment]
This observation makes sense to me; if you have 1000 files that import from a barrel, which imports from 1000 other files, each of the latter 1000 is a transitive dependency of each of the former 1000 files. In other words, changing one of the inputs to the barrel changes the shape of the barrel file, so anything that depends on the barrel could be invalidated.

I don’t know for sure whether this is expected, or if it might be feasible to create an optimization for barrel re-exports, which is a pretty common pattern in large projects. @amcasey @sheetalkamat any thoughts on this?

**Comment by amcasey** [comment]
I agree with @andrewbranch that the behavior is, unfortunately, expected.  From the consumer's perspective, the barrel has changed, so an update is required.  Fundamentally, by importing a barrel module, the consumer is explicitly treating the barrel as a black box - the compiler is just following that same interpretation.

It seems conceivable that we could be smarter about re-exports so that a module importing the barrel would only need to be re-checked if the particular re-exported modules it depended upon changed, but it would be pretty complicated (e.g. an edit in the importing module could change the "subset" of the barrel that is actually depended upon).  If we were to do it, we'd probably want to change the handling of re-exports in general and not barrel modules in particular.  @sheetalkamat?

**Comment by sheetalkamat** [comment]
Just depending on direct imports doesnt help because you need to think of inferred types from transitive imports/exports . Eg check test cases here https://github.com/microsoft/TypeScript/blob/master/src/testRunner/unittests/tscWatch/emitAndErrorUpdates.ts 

This is what makes it hard to contain the change to small set. 
We have [assumeChangesOnlyAffectDirectDependencies](https://www.typescriptlang.org/tsconfig#assumeChangesOnlyAffectDirectDependencies) for people who are ok with loose mode letting us know the direct imports/exports are the only things that matter.

**Comment by andrewbranch** [comment]
The scenario we’re interested in is this:

```ts
// @Filename: /lib/a.ts
export class A {}

// @Filename: /lib/b.ts
export class B {}

// @Filename: /lib/index.ts
export * from './a';
export * from './b';

// @Filename: /app/uses-a.ts
import { A } from '../lib';

// @Filename: /app/uses-b.ts
import { B } from '../lib';
```

And the desired outcome would be that

- edits to `/lib/a.ts` affect `/lib/index.ts` and `/app/uses-a.ts`, but _not_ `/app/uses-b.ts`
- edits to `/lib/b.ts` affect `/lib/index.ts` and `/app/uses-b.ts`, but _not_ `/app/uses-a.ts`
- edits to `/lib/index.ts` affect `/app/uses-a.ts` and `/app/uses-b.ts`

**Comment by amcasey** [comment]
And the catch is that changes to `uses-a.ts` or `uses-b.ts` can change the dependency graph (e.g. if you had `import * as Lib from '../lib'`, the change wouldn't even need to be in the import - you could suddenly start referencing `Lib.B`).

**Comment by andrewbranch** [comment]
If either file in `/app` used an import-star form, I would say it necessarily depends on both `/lib/a.ts` and `/lib/b.ts`—doing anything else sounds like it would depend on a full checker run to track references, and would potentially hurt editor operations like completions.

**Comment by amcasey** [comment]
@andrewbranch Is that consistent with the way libraries with barrel exports are consumed?  I think I've seen this pattern in lodash, for example.

**Comment by andrewbranch** [comment]
I see `import *` used rarely in the wild. At one point, there was guidance that named imports allow tree shaking in some bundlers, whereas other kinds imports would not. It’s been a long time since I heard that, but it makes sense to me.

**Comment by andrewbranch** [comment]
I’ll defer to Sheetal to what extent an optimization here is worth looking into during the next cycle.

**Comment by RA80533** [comment]
> I see `import *` used rarely in the wild. At one point, there was guidance that named imports allow tree shaking in some bundlers, whereas other kinds imports would not. It’s been a long time since I heard that, but it makes sense to me.

`import React from "react"` (a very common pattern for importing older CommonJS modules) is much more common because `esModuleInterop` (specifically, its enablement of `allowSyntheticDefaultImpoets`) but it is effectively `import * as React`.

**Comment by andrewbranch** [comment]
Yeah, I should have been more specific about what I meant—`import *` as a way to import CJS exports doesn’t really apply here.

**Comment by dmichon-msft** [comment]
Fully naming re-exports is the only way for a build tool to be able to only read those files that contain the relevant exports, and even then it still depends on the tool being reliably informed that none of the other files have side effects.

**Comment by sheetalkamat** [comment]
Currently we use d.ts signatures and export and import map to determine the file whether we need rebuild.. We do not track types and their origin.. So this is working as intended.
