### ISSUE TITLE
Type constraint lost in conditional type

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#43578]
# Bug Report

### 🔎 Search Terms
- extends
- contain
- constraint 

### 🕗 Version & Regression Information

4.3.0-dev.20210407

This was working in the TS 4.3 beta

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCCATDAxAllAZxgAUBDKUgW2BmCgBUJsBXAOwGMZcJWCAeeuQDmNAHxwAvHADeAKDgK4AbQDScXKzgBrYIggAzOIKgiYAXQBcR4TVVm4oWqwwE4ACgB0X4QSulWiEpmAJSS4gBuELgY8opxAPzuXh4+VmQU1LSEAjYwdqKhEhFRMXFxVpHRsgC+ANyyQA

### 💻 Code

```ts
export type AddFirstParameterToFunctions<Target> = {
    [K in keyof Target]: Target[K] extends (...args: any[]) => void
        ? (...args: Parameters<Target[K]>) => void
        : void
};
```

### 🙁 Actual behavior

`Parameters<Target[K]>` has the error:

```
Type 'Target[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'Target[keyof Target]' is not assignable to type '(...args: any) => any'.
    Type 'Target[string] | Target[number] | Target[symbol]' is not assignable to type '(...args: any) => any'.
      Type 'Target[string]' is not assignable to type '(...args: any) => any'
```

### 🙂 Expected behavior

This code previously compiled without errors in the TS 4.3-beta

**Comment by DanielRosenwasser** [comment]
It's likely that #43439 changed something up if it's a difference since the beta. @ahejlsberg and @weswigham might want to take a look at this.

**Comment by weswigham** [comment]
That PR had a carve out for TypeParameters for compat - it can probably be relatively safely expanded to all TypeVariables to cover this case.
