### ISSUE TITLE
Stray @ signs parsed in JSDoc

### ISSUE THREAD

**Issue by evmar** [microsoft/TypeScript#43580]
# Bug Report

### 🔎 Search Terms

jsdoc at sign

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSDoc

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210407#code/KYDwDg9gTgLgBAbwL4G4BQaD0AqbcACUwMArlAHZwAqAFsAXAM4CWA5pQGZQQC2cMdOMB4BDZgBs42TGg4lyAYxjMIlVsQCCMAMptyACgCUiJEA)

### 💻 Code

```ts
/** @return The @ sign from the email */
function getAtSign() {}
```

### 🙁 Actual behavior

JSDoc parsed (in Monaco hover etc) as if the bare '@' sign itself is a separate JSDoc tag.

### 🙂 Expected behavior

JSDoc parsed where the "The @ sign from the email" is all the documentation of the return type.

**Comment by evmar** [comment]
Related to #38922 a bit, but in this case there is whitespace on either side of the "@" sign so it should make the parsing easier.

**Comment by DanielRosenwasser** [comment]
Seems like an `@` should be a tag strictly when followed by `[a-zA-Z]`, maybe with some other rules about the left side (which are probably a lot harder to nail down).
