### ISSUE TITLE
Type guard does not narrow generic type via property check

### ISSUE THREAD

**Issue by qwelias** [microsoft/TypeScript#43590]
# Bug Report
I tried to find it in existing issues, there's a lot of similar ones, but repro case is not quite the same, so I'm not sure if it's duplicate.

### 🔎 Search Terms
type guard generic property narrow union

### 🕗 Version & Regression Information
TS version 4.2.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the search terms 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210408#code/C4TwDgpgBAqgdgSwPZwAoEMBO6C2UC8UA5OkVAD7EBGZlRAxkQFBOiRQAqEAzsADwcoEAB7AIcACbdYiFBmx5C8ZGiy4AfASgBvJlH1QwanAC5OegxPTB0Z3QYdRbOp2YCMUAL4XHUKnb93Lx9HegCwqA9vB08AbQ4AXSZvJnoUXigcJHoAay1tTydpLl4WBAAzKAAKLNyAOiMFAnxCEiIASkzsnLqrGzr0JiA)

### 💻 Code

```ts
type UnionParam = 'a' | 'b' | 'c'

type Test<T extends UnionParam = UnionParam> = {
    param: T
    data: {
        a: { a: 1 }
        b: { b: 1 }
        c: { c: 1 }
    }[T]
}

const mock = {} as Test

if (mock.param === 'a') mock.data.a
/*
Property 'a' does not exist on type '{ a: 1; } | { b: 1; } | { c: 1; }'.
  Property 'a' does not exist on type '{ b: 1; }'.
*/
```

### 🙁 Actual behavior

Type of `mock.data` is not narrowed to `{ a: 1; }` by a type guard

### 🙂 Expected behavior

Type of `mock.data` is narrowed to `{ a: 1; }` by a type guard.
Expected to work because `mock.param` type is properly narrowed to `'a'` by the type guard, and the type of `mock.param` is defined  by the same generic parameter that narrows the `mock.data` type union.

**Comment by MartinJohns** [comment]
There is nothing it **can** narrow to, because your parameter `T` is typed `'a' | 'b' | 'c'`.

This is a completely legal object for your type:

    const mock: Test = { param: 'b', data: { a: 1 } };

**Comment by qwelias** [comment]
> There is nothing it can narrow to, because your parameter T is typed 'a' | 'b' | 'c'.

`T` is not `'a' | 'b' | 'c'`, rather `T` extends `'a' | 'b' | 'c'` which is very important since after the type guard `mock.param` type is properly narrowed down to just `'a'`, and type of `mock.param` is parametrized by `T`, the same `T` that parametrizes `mock.data`, so it should bed narrowed as well.

Your point would stand only in case where `mock.param` and `mock.data` are not connected by the same param, e.g.:
```ts
type Test = {
    param: UnionParam
    data: {
        a: { a: 1 }
        b: { b: 1 }
        c: { c: 1 }
    }[UnionParam]
}
```
In that case both `param` and `data` prop types are independent from one another.

**Comment by MartinJohns** [comment]
> T is not `'a' | 'b' | 'c'`, rather T extends `'a' | 'b' | 'c'`

Not in the example you gave. You did not provide a type argument to `Test`, so the default type argument `UnionParam` you specified is being used.

`Test<T extends UnionParam = UnionParam>` means `T` must extend `UnionParameter` (which means `T` can extend `'a' | 'b' | 'c'` as well), and **if not provided** use the type `UnionParam`.

**Comment by qwelias** [comment]
I did not provide the exact type exactly because there's this type guards feature that should be able to narrow it down based on runtime assertions, and that's exactly why both properties are parametrized by the same generic argument!
I feel like you're ignoring the fact that types for `param` and `data` depend on the same `T`, so narrowing down one of them narrows down the other as well, this is logical and that's the whole point of using generics -- so you can parametrize types.

**Comment by MartinJohns** [comment]
> I feel like you're ignoring the fact that types for `param` and `data` depend on the same `T`.

I'm not ignoring it. But I'm telling you that `T` **is** `'a' | 'b' | 'c'`, it's **not** one of those. So there is nothing that can be narrowed down. :-)

I provided you a correct working solution, showing the behavior you want. The code you provided simply won't work, you're misunderstanding how generics and unions work here.

**Comment by qwelias** [comment]
Here's a set of questions then:
1. In my initial example is the type of `param` extends or is `T`?
2. Does the type guard from initial example narrows down the type of `mock.param` to just `'a'`?
3. Does the type of `data` depend directly on `T`?

**Comment by MartinJohns** [comment]
1. `param` is `T`, and `T` extends `UnionParam`. That means `T` **can** be just `'a'`, but it also can be `'a' | 'b' | 'c'`.
   - Your type argument `T` has the **default** type of `UnionParam` (`'a' | 'b' | 'c'`) if no type is provided.
   - Your variable `mock` is typed `Test`, so **no type argument** for `T` is provided, and `T` defaults to `UnionParam`.
2. It does indeed narrow `mock.param` to `'a'`.
   - The type of `mock.param` is `'a' | 'b' | 'c'`, because you didn't provide a type argument and it uses the default.
   - The type `'a' | 'b' | 'c'` can be narrowed to `'a'` with your check.
 3. It does!
    - But `data` does not depend directly on `param`.
    - And as clarified before, `T` is typed `'a' | 'b' | 'c'` in your example.
    - `{ a: { a: 1 }; b: { b: 1 }; c: { c: 1 } }['a' | 'b' | 'c']` results in the type `{ a: 1 } | { b: 1 } | { c: 1 }`.
    - You narrowed `param`, but you did not narrow `data`.
    - It's completely legal to assign `'b'` to `param`, and `{ a: 1 }` to `data`. The types match with what `Test` specifies.

Your type `Test` (not the lack of type argument) is **exactly** this type:

    {
        param: UnionParam;
        data: { a: 1 } | { b: 1 } | { c: 1 };
    }

Where as you actually **want** this type:

     { param: 'a'; data: { a: 1 } } | { param: 'b'; data: { b: 1 } 0 | { param: 'c'; data: { c: 1 } }

Here you have three clear different types that can be narrowed as you want. The type where `param` is typed `'a'` has `data` typed `{ a: 1 }`, so TypeScript knows that when you narrowed `param` to `'a'` you can only have one of these three possible types: The one with `data` being `{ a: 1 }`.

I hope this clears it up for you. :-)

**Comment by qwelias** [comment]
That's alot of answer to seemingly simple questions :)

Thanks for the efforts! Tho I'm still left confused as to how TS works here.
> Your type Test (with default type argument) / Test<UnionParam> (with explicit type argument) is exactly this type:
```ts
{
    param: UnionParam;
    data: { a: 1 } | { b: 1 } | { c: 1 };
}
```

From this it seems to me that once the generic is "instantiated" it loses the parameter and just uses compiled unions as they are without initial connections between them (I'd still call it a bug :))

This logic may not be in line with TS implementation of generics, but please follow me here:
1. if:
  - type of `param` is `T`
  - type of `param` is narrowed down to `a`
2. therefore `T` is narrowed down to `a`
3. and if type of `data` directly depends on `T`
4. therefore type of `data` is narrowed down as well as type of `param` and vice versa

I see how this would not work if my guess about the loss of parameters upon generic "instantiation" is correct, but I see this as a flaw as it does not follow the logic and, therefore, is misleading. I understand that there could be workarounds on this, e.g.: making a top-level union based on `T` like you suggested.

So if my statement of those 4 points could be proven wrong -- I would gladly close the issue myself.

**Comment by MartinJohns** [comment]
> From this it seems to me that once the generic is "instantiated" it loses the parameter

Depends what you would call "loses". Perhaps the terms "expanded", "implemented" or "closed" generic types help you get the correct mindset. When providing a type argument you're not dealing with a "hypothetical" type anymore, you're dealing with an actual concrete type. In your case it's `UnionParam`.

> therefore T is narrowed down to a

That's where you got it wrong. You're not narrowing the type parameter `T`, you're narrowing the type of your parameter `a`.

> therefore type of data is narrowed down as well as type of param and vice versa

You're wrongly assuming that **all instances** of `T` are the same type, but that's not specified by your type definition. Again, in your case `T` results in `'a' | 'b' | 'c'`. So in one case the actual value can be `'a'`, in the other case it could be `'b'`. Not all `T` are the same instance, so the core assumption "narrowed one T parameter, narrowed them all" is wrong.

---

Again, there is no flaw or bug here. It's just a (unfortunately common) misunderstanding of how generic types work.

**Comment by MartinJohns** [comment]
Perhaps this simplified example helps you understand it:

```typescript
// We have a dummy type with two properties, each having the type provided as an argument: T.
type Example<T> = { first: T; second: T }

// We create an instance. As the type argument we provide the type `1 | 2`.
const ex: Example<1 | 2> = {} as any;

// Now we're not dealing with a hypothetical type "T" anymore, we **know** the type is `1 | 2`.
// So the type of the example variable is:
// { first: 1 | 2; second: 1 | 2 }

ex.first = 1; // ex.first is typed `1 | 2`, so this is okay!
ex.second = 2; // ex.second is typed `1 | 2`, so this is okay!

if (ex.first === 1) {
    // We checked and narrowed the type of `ex.first` from `1 | 2` to `1`.
    // But that doesn't mean the type of `ex.second` is also narrowed.
}
```

**Comment by qwelias** [comment]
So basically yes, upon generic "instantiation" it's parameters are replaced by their values, so the type becomes `{ first: 1 | 2; second: 1 | 2 }` -- no connection between `first` and `second` anymore (type of parameter `T` is inlined into the type and the parameter itself is lost). 

Good example :+1: , tho the 4-point statement still stands as you have previously agreed that `param` is `T`, but that's not how TS works apparently and `param` is whatever `T` was instantiated as and not refers to `T` anymore:
- assumption was: `first_arg_type -> T -> param` and `T -> data`
- reality: `first_arg_type -> param` and `first_arg_type -> data`

`T` works just as a placeholder, not as a _type variable_ (it's pretty much either constant after initiation or is a template placeholder).
And it does not go in line with [the official handbook](https://www.typescriptlang.org/docs/handbook/2/generics.html) as it says that:
> Instead, we need a way of capturing the type of the argument in such a way that we can also use it to denote what is being returned. Here, we will use a type variable, a special kind of variable that works on types rather than values.

So at this point it's more like a documentation issue, I guess, as otherwise it'd be a super-breaking change.
