### ISSUE TITLE
`jake runtests-browser t=yourTestName` does not load any test on master branch

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#4359]
`jake runtests-browser t=yourTestName` has got broken and the `Run Tests` button just shows `passes: 0 failures: 0 duration: 0s`.

I'm testing on Windows 10 build 10240 and io.js v2.3.1. It had worked a week ago and got broken when I received the latest TypeScript bits. Updating io.js to version 3.0.0 doesn't fix this problem.

`jake runtests t=yourTestName` still works as expected.

**Comment by mhegazy** [comment]
was that ever working? @danquirk?

**Comment by DanielRosenwasser** [comment]
@SaschaNaz if you make it `t=fourslash` and then change your browser URL from `grep=fourslash` to `grep=yourTestName`, does that work at all?

**Comment by SaschaNaz** [comment]
@DanielRosenwasser No, it doesn't work and `grep=fourslash` also does not. I've found that even `jake runtests-browser` without `t=yourTestName` does not work now.

**Comment by SaschaNaz** [comment]
I just found that `ts.sys` in bundle.js is being undefined and that causes an error.

**Comment by vladima** [comment]
PR with the fix: https://github.com/Microsoft/TypeScript/pull/4379

**Comment by vladima** [comment]
fixed in  #4394
