### ISSUE TITLE
JavaScript - No documentation for `padStart` string function.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/TypeScript#43596]
- VS Code Version: 1.55.0
- OS Version: Windows 10 20h2

Steps to Reproduce:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

![image](https://user-images.githubusercontent.com/17777237/114071952-fdca9200-98a1-11eb-9380-14b46c5998b2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@pixieaka To fix this, create a jsconfig/tsconfig that specifies `"target": es2017`. We currently use `target: es2016` as the default

@DanielRosenwasser Should we consider bumping the default for implicit projects to `es2018`?

**Comment by pixieaka** [comment]
It should by default if the user doesn't configure it to be the latest version `es2020`.

**Comment by mjbvz** [comment]
@pixieaka We have to be cautious when changing defaults. It's a bad experience if we suggest `padStart` to a user and then get a runtime error when running the code because their environment doesn't support it

**Comment by pixieaka** [comment]
@mjbvz  In my opinion if it's matter to warning the user maybe if vscode shows to him in function description the compatibility of function in IntelliSense instead of remove it totally.

For example: `Compatible with (es2016)`

![image](https://user-images.githubusercontent.com/17777237/114085436-a8967c80-98b1-11eb-9d71-444bded96c83.png)

**Comment by mjbvz** [comment]
For beginners, we do not want to suggest properties that may cause confusing runtime errors. And most users will never look at the IntelliSense details to see `requires using an ES2020 environment`

Instead we pick a conservative baseline and let users change this if needed

**Comment by pixieaka** [comment]
@mjbvz I respect your point of view. Could that display in somewhere to be clear to user.

Thanks, have a great day.

**Comment by DanielRosenwasser** [comment]
How about we switch it to ES2020? Node 14 is the current LTS and most browsers nowadays are evergreen. A beginner will likely be more confused if they aren't getting functions for 1-2 years back.

**Comment by pixieaka** [comment]
@DanielRosenwasser Can function compatibility adds in IntelliSense description ?

**Comment by DanielRosenwasser** [comment]
We could possibly do that - what I think might also be useful would be signaling browser/runtime compatibility. On the other hand, I don't want to add *too* much information there if it's not always going to get used.

**Comment by DanielRosenwasser** [comment]
I know it's been brought up before, but what if we just linked out to MDN for these functions?

**Comment by pixieaka** [comment]
@DanielRosenwasser That's 'll be useful hint for compatibility like `ES2017` and link to browsers compatibility.

**Comment by pixieaka** [comment]
> How about we switch it to ES2020? Node 14 is the current LTS and most browsers nowadays are evergreen. A beginner will likely be more confused if they aren't getting functions for 1-2 years back.

@mjbvz Is `ES2020` will be the default version in next stable release ?

**Comment by pixieaka** [comment]
@DanielRosenwasser Is this rejected?

> We could possibly do that - what I think might also be useful would be signaling browser/runtime compatibility. On the other hand, I don't want to add _too_ much information there if it's not always going to get used.
