### ISSUE TITLE
Add support for navigator.userAgentData

### ISSUE THREAD

**Issue by jennynotjen** [microsoft/TypeScript#43604]
The `window.navigator` `Navigator `interface has a new property `userAgentData`, documentation here: 
https://web.dev/user-agent-client-hints/. 

This has been added in support of User Agent Client Hints starting in Edge90+. Could we add support this property? Thanks in advance!

**Comment by andrewbranch** [comment]
As far as I can tell, this is still a super early proposal. We don’t have an exact policy on when we add features to https://github.com/microsoft/TypeScript-DOM-lib-generator (which is where this would eventually go), but it would definitely need broader adoption first. In the meantime, I would suggest augmenting your library types locally:

```ts
interface Navigator {
    userAgentData?: /* whatever the type should be */
}
```

Wrap that in a `declare global { ... }` if in a module. Whenever this is in most browsers and/or either a W3C or WHATWG spec, feel free to come back and open an issue or PR against https://github.com/microsoft/TypeScript-DOM-lib-generator. Thanks!

**Comment by SNDST00M** [comment]
https://wicg.github.io/ua-client-hints/#interface
