### ISSUE TITLE
Cannot debug TypeScript applications in Visual Studio 2013/2015 when --inlineSourceMap and --inlineSources set

### ISSUE THREAD

**Issue by Davidhanson90** [Microsoft/TypeScript#4360]
1.) There appears to be no way to set the flags (inlineSourceMap ,inlineSources ) in visual studio 2013 with the 1.5 TypeScript extension installed.  Is this a known bug? 

2.)  As a result of the above I have a pre-build event which runs this. 

```
tsc.exe" build.ts --out app.debug.js --inlineSourceMap --inlineSources --diagnostics --target es5
```

However, while I can debug the TS source in both chrome and IE11, visual studio will no longer break on breakpoints.

**Comment by mhegazy** [comment]
@sheetalkamat, the VS debug extension does not support inline soruce maps, is this correct?

**Comment by danquirk** [comment]
I assume from the status here that the issue also affects VS2015?

**Comment by mhegazy** [comment]
Correct. title updated.

**Comment by sheetalkamat** [comment]
I have updated our debug extension to support inline source map and inline sources.
