### ISSUE TITLE
Suggestion: Implicitly resolve properties/methods without 'this' property access.

### ISSUE THREAD

**Issue by kungfusheep** [Microsoft/TypeScript#4361]
I've just had a look through previous issues and couldn't find anything that resembles this, so apologies if it's been brought up before.

It seems like there's enough information available to TypeScript that would enable it to infer the `this` keyword.  It's a nice feature of a few other languages and it would be great if TypeScript could do the same where possible. 

For example the following class

```javascript
class TestClass {
    public testMember:number;
    public testMethod(value:number) : number {
        return testMember + value; /* 'this' has been omitted from 'testMember' */
    }
}
```

Would output the following 

```javascript
var TestClass = (function () {
    function TestClass() {
    }
    TestClass.prototype.testMethod = function (value) {
        return this.testMember + value; /* 'this' has been inferred */ 
    };
    return TestClass;
})();
```

Thoughts?

Cheers

**Comment by Davidhanson90** [comment]
This could be dangerous, for example the code below. What would you expect testMethod to return.  In javascript window would point to the global object and would be in conflict with the class field.  

```javascript
class TestClass {
    public window : window
    public testMethod() : string {
        return window.name + "Foo";
    }
}
```javascript

**Comment by DanielRosenwasser** [comment]
While I do prefer this in other traditional OO-style languages, this conflicts directly with ECMAScript's semantics, which were chosen intentionally to avoid the scenario @Davidhanson90 gave.

**Comment by kungfusheep** [comment]
Fair enough. Thanks.

**Comment by chdh** [comment]
I understand that in ECMAScript class properties are not included in the scope chain. But if you are used to programming languages like Java, C# and C++, this is not what you expect:

```javascript
var abc = "global level";

module Module1 {

   var abc = "module level";

   export class Class1 {

      abc = "class level";

      method1() {
         console.log(abc);
      }
   }
}

new Module1.Class1().method1();   // output is "module level"
```

If you look at a typical large class implementation in Java, C# or C++, private class instance variables are used to hold the state values used by the program logic of the class implementation. Having to add "this." in front of every reference of such a variable makes the code less readable.

Maybe a class decorator could be used to instruct the TypeScript compiler to automatically insert ".this" for references to class properties.
