### ISSUE TITLE
Type of symbol-named computed property is contextually typed with string literal

### ISSUE THREAD

**Issue by christianalfoni** [microsoft/TypeScript#43628]
# Bug Report

### 🔎 Search Terms

symbol
index
extends

### 🕗 Version & Regression Information

Version 4.2.3 and all previous version. Does not work in 4.3.0 Beta either

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about indexing symbols and extending

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgFQGEIVR4BvAKDjgGcZNUAuOmKZAcwG5KBfSyqEixEpDDjz4AgthgIScKjRgBPMMBb12SDnAA+dFQFsARhAA2PfgKHR4q9QXxRMSWgjklaAHkJwywEgAJrQExKQgMAA0cFL+kYEhBDKeSDEAcsAA7gDKDKjxqMGhhADaAOT0jMDlALoAfHAAvIrUcKV51aJwZZX5NbW1LEo07fhqeMixFQ4DtQD8LAAUbaNwOKkscQBkinCzLOOOvFGro1XMPYWJoeSs1SydBbxw81csSMAAbminawCUzUafgCxT2Fw0cEyuX6cBebz8H2+aB4NF4Vh4lGwXnsLjcHnkSGacF81zBRBIqEiMTioKS0lkhIy2SeeDpJQqELq9RWNAhLEIf3WjJIWyFbFc7lStEOzklBK8vhpzJh1Xqp3+AqBrTgUGAMAArlAieQXphQq4VHwBNi3PA4i0csYzOYluUpOV-licXAAELEp2mCxu32egSzHqUsjEkb8uDlABiAHkk+U+PodfdLuVfVIAEpp6wRlKEmNtA77CYQdCxNpBRiYTRsTjpgwjCuzat+usNj4G0xoa3eu1wW1UmACqORGNmi1IK22+jCzaxEVElqm9Zzq2UCX41JLMdkGIbJmZ5NJ4ZnUpSIZwJankiApqNJZ3OM5-PlOFetFC3N5sM-C8F6QA)

### 💻 Code

```ts
export interface TContext {
  state: string;
}

export interface TAction {
  type: string | symbol;
}


export type TTransitions<C extends TContext, A extends TAction, NewState extends C['state']> = {
  [State in C['state']]: {
    [Type in A['type']]?: (
      action: A & { type: Type },
      state: C extends { state: State } ? C : never,
    ) => C extends { state: NewState } ? C : never;
  };
};

const transition = <C extends TContext, A extends TAction, NewState extends C['state']>(
  state: C,
  action: A,
  transitions: TTransitions<C, A, NewState>,
): C => {
 return {} as any
}

const A = Symbol('A')
const B = Symbol('B')

type Context = {
  state: 'FOO'
} | {
  state: 'BAR'
}

type Action = {
  type: typeof A
  data: string
} | {
  type: typeof B
  data: number
}

const context: Context = {} as any
const action: Action = {} as any

transition(context, action, {
  // When I hover this FOO I can see the correct typing of the [A]: (action) => ({ state: 'BAR' }). It states
  // that the "action" argument indeed is a `{ type: typeof A, data: string }` type
  FOO: {
    // But here the "action" argument becomes `never`
    [A]: (action) => ({ state: 'BAR' })
  },
  BAR: {}
})
```

### 🙁 Actual behavior

The "action" argument becomes `never`

_Here I am hovering the FOO property_
<img width="378" alt="Screenshot 2021-04-10 at 14 50 36" src="https://user-images.githubusercontent.com/3956929/114270389-59189380-9a0c-11eb-972c-72bcc35f83f5.png">

_Here I am hovering the action argument_
<img width="644" alt="Screenshot 2021-04-10 at 14 50 41" src="https://user-images.githubusercontent.com/3956929/114270393-5b7aed80-9a0c-11eb-912b-37b24b15f88b.png">

### 🙂 Expected behavior

The "action" argument should have had the same type as when hovering the "FOO" property:
```ts
{
  type: typeof A;
  data: string;
} & {
  type: typeof A;
}
```

**Comment by christianalfoni** [comment]
I found a workaround which required a changed API surface. It was for the better, but keeping this here as it does seem like a bug 😄

**Comment by andrewbranch** [comment]
Slightly reduced: https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgFQEFsYEIk4BvAKDjhgE8xgAuOAZximQHM4AfDgwC2AIwgAbANzUAvtQXZynOITgBeOAGUR4iQAoA5IUMBKakqQqAQhu27JR62YWNmqkmQqaadN63omYAh0VVo4ABNMGEw2Tm4kHjkBKnD-Nn8QuGtwqJi2JABXMTQ5BQjgbAlMKDxLFRxScjZiJqQZagqqmrx0QqRPcjh0AB58OFBUJAj2AlavAD59Rq82fAAaOFFqgAs2SjgAbQBpRAp8Q8N-QwBdG4B+NmXBpDW4ADIqQOY2U9lTDQLOAANwgCAicH+bEwSAYMnQzzam18R0IN2hL0BX3k-2oQA
