### ISSUE TITLE
Regression with template literal generics (4.3.0-beta)

### ISSUE THREAD

**Issue by zkldi** [microsoft/TypeScript#43620]
# Bug Report

### 🔎 Search Terms
Template Literal Generic
Template Literal Discrimination
Template Literal Resolution

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.0-dev20210408

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBACgThAZgSwB4QM5QLxQESID2heUAPvgEYCGceA3ALABQLokUAggDbfxJoAItWDUc+IoQBcNAF6kKeGnBnV5TVs3bR+KVMNEAeGFAipgEAHYATLLrSYAfOIAGAEgDeMAL6rZLjRZkSws4RGoAY2gASQAVTGBjU3MrW1gEPUwAGigAUWSLGywePgyhETFce30K40dnDxYoZqhKbmoACykoDGA4YIBzFm8gA)

### 💻 Code

```ts
type Prefixes = "foo" | "bar";

// Create a type which is an set of strings
type AllPrefixData = "foo:baz" | "bar:baz";

// Then create a generic type that generates a compliant member of that set
type PrefixData<P extends Prefixes> = `${P}:baz`;

// Create an interface with a generic that expects E to extend AllPrefixData.
// However, even though PrefixData<P> is a valid member of AllPrefixData,
// it will be rejected in 4.3.0.
interface ITest<P extends Prefixes, E extends AllPrefixData = PrefixData<P>> {
    blah: string
}
```

### 🙁 Actual behavior

TypeScript 4.3.0-dev rejects the assignment with the following nonsense error:
```
    Type '`${P}:baz`' does not satisfy the constraint 'AllPrefixData'.
      Type '`${P}:baz`' is not assignable to type '"bar:baz"'.
    'E' is declared but its value is never read.
```

### 🙂 Expected behavior

This should be a legal assignment, and was until 4.3.0-dev.

**Comment by andrewbranch** [comment]
I think this looks like a 4.3 regression—@ahejlsberg, would you be able to take a look?
