### ISSUE TITLE
Allow JSX element attributes type to be an intersection

### ISSUE THREAD

**Issue by jbrantly** [Microsoft/TypeScript#4362]
Consider the following:

```typescript
declare module JSX {
    interface ElementAttributesProperty { props: {}; }
}

class Component<P> {
    props: P & { ref?: string };
}
```

This results in the error: JSX element attributes type '[type parameter] & { ref?: string; }' must be an object type.

An alternative would be an additional member of the JSX namespace that allowed specifying "global" attributes (that would apply to both value-based and intrinsic elements). For example:

```typescript
declare module JSX {
    interface GlobalAttributes {
        ref?: string
    }
}
```

See also borisyankov/DefinitelyTyped#5347

**Comment by RyanCavanaugh** [comment]
Removing this restriction for the sake of intersection types makes sense. It was put in place because we don't really correctly support the JSX Attributes type being a union type.

**Comment by JsonFreeman** [comment]
What should happen if it is an intersection of unions? Or an intersection of type parameters that could be instantiated to unions?

**Comment by Pajn** [comment]
A GlobalAttributes interface would be great because it would make it possible to add global attributes without redefining the entire typing file of for example react.

**Comment by JsonFreeman** [comment]
What does this proposal allow exactly? The attributes type can be any type in the world? Or just an intersection of object types? Keep in mind that an intersection of object types would not fix the `Component<P>` example above because P is a type parameter.

If the attributes can be any type in the world, what are the semantics for union types and type parameters?

**Comment by phiresky** [comment]
My use case is the following:
```typescript
abstract class TestA<T> extends React.Component<{x:number}&T, {}> {
   ...
}
class TestB extends TestA<{y:number}> {
   render() {...}
}
```
Declaration works fine, but it can't be used because (I think) of the above problem.

**Comment by RyanCavanaugh** [comment]
Fixed in nightly build

**Comment by phiresky** [comment]
@RyanCavanaugh Thank you!
