### ISSUE TITLE
Broken links in release notes (4.2.4 & 4.3 Beta)

### ISSUE THREAD

**Issue by zraineri** [microsoft/TypeScript#43626]
[4.2.4](https://github.com/microsoft/TypeScript/releases/tag/v4.2.4)
release announcement > https://github.com/microsoft/TypeScript/blob/v4.2.4
What's new in TypeScript v4.2.4 > https://github.com/microsoft/TypeScript/blob/v4.2.4

[4.3 Beta](https://github.com/microsoft/TypeScript/releases/tag/v4.3-beta)
release announcement > https://github.com/microsoft/TypeScript/blob/v4.3-beta
What's new in TypeScript v4.3-beta. > https://github.com/microsoft/TypeScript/blob/v4.3-beta

**Comment by DanielRosenwasser** [comment]
I've fixed the 4.3 beta content. I don't see the issues with the 4.2.4 content.

**Comment by zraineri** [comment]
Everything looks good to me :+1: I'll close this now

As always thanks for all that you guys do @DanielRosenwasser
