### ISSUE TITLE
Using ternary operator loses hard coded numeric values

### ISSUE THREAD

**Issue by vkarpov15** [microsoft/TypeScript#43637]
# Bug Report

### 🔎 Search Terms

typescript ternary operator loses value

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ternary operator

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=2&pc=1#code/MYewdgzgLgBAbgQwDYwLwwLIKgCwHQBOCYAJiALYAUAlDAHwwAMeArDAPwwDeMAHgFwwAjDAC+MQTwCegkaIDcAKEUBLMFACmBAGYJgGmAA1uimGb7tZS8zCmWYYAK7kARlqWjl2x2GBQV4ADy2oaUiEjUSorevv7gMDF+AWDBoeGChrRcpuagkCBIGnhIIADmYch4vJGKnkA)

### 💻 Code

```ts
const val = Math.random() > 0.5 ? { x: 1 } : { y: 1 };

interface X {
    x?: 1;
    y?: number;
}

functionOfX(val);

function functionOfX(val: X) {
    console.log(val.x);
}
```

### 🙁 Actual behavior

Compiler reports the below error:

```
Argument of type '{ x: number; y?: undefined; } | { y: number; x?: undefined; }' is not assignable to parameter of type 'X'.
```

### 🙂 Expected behavior

I would expect this code to be valid, because `x` is either 1 or undefined

Re: https://github.com/Automattic/mongoose/issues/10066

**Comment by whzx5byb** [comment]
It is unrelated to the ternary operator. `const val = { x: 1 }` still produces the error.

To make the literal value "hard coded", you need `const assertions`.
```
const val = Math.random() > 0.5 ? { x: 1 } as const : { y: 1 };
```
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions

**Comment by vkarpov15** [comment]
Thanks :+1:
