### ISSUE TITLE
async/await inferring

### ISSUE THREAD

**Issue by Florent-Steiner** [microsoft/TypeScript#43630]
# Suggestion

## 🔍 Search Terms
async, await

async await inferring

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

TypeScript should infer async/await

## 📃 Motivating Example

TypeScript can easily infer 'async' keyword of a function if there is a use of an asynchronous function with a 'await' call. You still could explicitly use the 'async' keyword, so it's backward compatible.

When calling an async function, TypeScript should infer the 'await' keyword except if the 'async' keyword. The 'await' keyword can be explicitly used.

## 💻 Use Cases

It will be more easier to writte asynchronous code and the code will be much more readable

The code :

```
async function getCompany(id: number) {
    await Promise.all([
        config.load(),
        db.connect()
    ])
    const company = await db.get("company", 1) as Company
    company.users = await company.getUsers()

    await fs.delete('./companies.json.bak')
    await fs.move('./companies.json', './companies.json.bak')
    await fs.write('./companies.json', JSON.stringify(company))

    db.close()

    return company
}
```

should be become :

```
function getCompany(id: number) {
    Promise.all([
        async config.load(),
        async db.connect()
    ])
    const company = db.get("company", 1) as Company
    company.users = company.getUsers()

    fs.delete('./companies.json.bak')
    fs.move('./companies.json', './companies.json.bak')
    fs.write('./companies.json', JSON.stringify(company))

    async db.close() 

    return company
}
```

**Comment by jcalz** [comment]
> My suggestion meets these guidelines:
> * [x] This could be implemented without emitting different JS based on the types of the expressions

But you're explicitly proposing that `async` and `await` should be emitted to JavaScript depending on the types the compiler infers, right?  You want

```ts
const foo = bar();
```
to either be emitted as-is, or possibly as 
```js
const foo = await bar();
```

depending on whether or not  `bar` is a synchronous or an asynchronous function.  I'm afraid this suggestion will be declined.

**Comment by Florent-Steiner** [comment]
Oh...
You’re right. I read too quickly, sorry :(

**Comment by benjamingr** [comment]
The problem with this is that it breaks existing code:

```js
// an async function that awaits something with excess parameters
async function foo() {
  await(something());
}
// a non-async function that 
function foo() {
  await(something()); // await can just be a global function
}
```

That's why the syntactic bit was required - since await was a valid identifier before async functions were introduced.

**Comment by Florent-Steiner** [comment]
Oooh ...
That totaly makes sense! 

Thank you very much guys for taking the time to explaining that to me :)
