### ISSUE TITLE
Proposal - `some` keyword (opaque types)

### ISSUE THREAD

**Issue by pie6k** [microsoft/TypeScript#43644]
# Suggestion

## 🔍 Search Terms

some keyword, infer the variable type, infer the variable generic type, narrow down variable type, guard variable type, type as const, "reverse" generic placeholder.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

This proposal introduces `some` keyword to TypeScript. It is also called `opaque type`. It is very similar to generics, but it is 'reversed' - implementation is used to resolve the type instead of provided generic type.

Opaque types are present in multiple languages like Swift. It can be a good initial read: https://docs.swift.org/swift-book/LanguageGuide/OpaqueTypes.html 

It allows creating variables and methods or functions that fulfill some interface without losing type details about the created entity.

Let's start with use cases of `as const` as its mechanics are very similar to opaque types.

```ts
const a = [1,2,3]; // <- type is number[]. it means some information is lost as we know exactly what is the content of the array
```

vs

```ts
const a = [1,2,3] as const; // <- type is readonly [1, 2, 3]. details of type are not lost!
```

This works great, but we're not guarded against inserting incorrect data into our array:

```ts
const a = [1,'2',3] as const // oops!;
```

👆 we have const type generated, but it includes string now. What if we want to force this variable to be a const array that includes only numbers.

We could try

```ts
const a: number[] = [1, 2, 3] as const // The type 'readonly [1, 2, 3]' is 'readonly' and cannot be assigned to the mutable type 'number[]'
```

But it's not allowed.

This is where `some` keyword becomes useful:

```ts
const a: some number[] = [1, 2, 3]; // type is readonly [1, 2, 3] 🎉
```

and we are also guarded against inserting incorrect data

```ts
const a: some number[] = [
  1,
  '2', // TS ERROR!
  3
];
```

## 📃 Motivating Example

```ts
type NumbersMap = Record<string, number>;

// We define variable that has to 'extend' `NumbersMap`
const myMap: some NumbersMap = {
  one: 1
}

// But now, `myMap` type is not just `NumbersMap`. Instead, it is an exact, deep type as if we used `as const`.

// compile time types:
myMap.one // type = 1 (number)
myMap.two; // <-- TS ERROR!, myMap has no property 'two'


const myMap: some NumbersMap = {
  one: 1,
  two: 'two', // <- TS error
}

// -------------------------------
// Comparing it to the current version

// We defined some specific object, but it's type is just `NumbersMap`, all details are lost.
const myMap2: NumbersMap = {
  one: 1
}

myMap2.two // type - number (no TS complaining!)
```

## 💻 Use Cases

Things like `JSON Schema`, where we have some general interface, but we need exact content of the object in order to have compile-time useful information:

```ts
const jsonSchema: some JSONSchema {
  foo: JSONSchema.string()
};

type Data = InferJSON<typeof jsonSchema>; // { foo: string }
```

--------

```ts
class Shape {}

class Triangle extends Shape {}

class Circle extends Shape {}

class GeometryFactory {
  getShape(): some Shape {
    return new Circle();
  }
}

const factory = new GeometryFactory();

const shape = factory.getShape(); // <-- type is 'Circle'
```
--------------

It is currently possible to implement some sort of opaque type helper which achieves both main goals - perserving type details and guarding against incorrect type.

```ts
function opaque<T>() {
  return function get<I extends T>(value: I) {
    return value;
  }
}


const foo = opaque<number>()(2); // <- type is 2 🎉 - type details are perserved
const bar = opaque<number>()('2'); // <- TS Error 🎉 - incorrect type is not allowed
```

**Comment by DanielRosenwasser** [comment]
In your motivating examples" section, it looks like you're expecting the apparent type (a version of the type with all the members) of an opaquely-typed variable to be the underlying type of the value that was assigned to it. 

That runs pretty counter to how our type system works. Most precedent in our type system typically would imply that a `some T` would have all the same capabilities as a `T` and nothing else.

In fact, that's not Swift's behavior either:

```swift
import Foundation

protocol Container {
    associatedtype Item
    var count: Int { get }
    subscript(i: Int) -> Item { get }
}
extension Array: Container { }


func makeOpaqueContainer<T>(item: T) -> some Container {
    return [item]
}
let opaqueContainer = makeOpaqueContainer(item: 12)

// error!
let twelve: Int = opaqueContainer[0]
```

Some of the use-case here seems to be closer in spirit to #7481. Would that be more relevant?

**Comment by andrewbranch** [comment]
This sounds exactly like #7481 (and/or its many linked duplicates) but let me know if I’ve misunderstood.

**Comment by pie6k** [comment]
It's indeed very similar. API approach is substantially different, tho
