### ISSUE TITLE
[Emitter] Wrong design:type metadata for decorated fields

### ISSUE THREAD

**Issue by pcan** [Microsoft/TypeScript#4364]
When I compile this code:

```TypeScript
class A {
    constructor() { console.log('new A'); }
}

type AType = A;

function decorator(target: Object, propertyKey: string) {
}

export class B {

    @decorator
    x: AType = new A();
}
```

The emitter produces the following code:

```JavaScript
var A = (function () {
    function A() {
        console.log('new A');
    }
    return A;
})();
function decorator(target, propertyKey) {
}
var B = (function () {
    function B() {
        this.x = new A();
    }
    __decorate([
        decorator, 
        __metadata('design:type', Object)
    ], B.prototype, "x");
    return B;
})();
exports.B = B;
```

But the expected output for metadata should be `__metadata('design:type', A)`. Furthermore, if I change the param declaration to `x: A = new A();`, the emitter will output `__metadata('design:type', )` (type not specified at all).

**Comment by fopsdev** [comment]
i thin i'm running into the same issue here:

import {bindable} from 'aurelia-framework';

```
export class NavBar {
  @bindable router = null ;
}
```
gets translated to:

```
...
        __decorate([
            aurelia_framework_1.bindable, 
            __metadata('design:type', )
...
```

**Comment by mhegazy** [comment]
This is by design. the intended behavior is not doable for the general case. one thing to keep in mind is we are serializing the type using the constructor function. if you alias it, the constructor function might not be, and probably is not,  in scope.

consider this:

```ts
// a.ts
class A {
}

export type TypeA = A;
export function getA() {  return new A(); } 
```

and 
```ts
// b.ts
import {AType, getA} from "a";
export class B {
    @decorator
    x: AType = getA(); // 'A' is not in scope here, the value will be undefined.
}
```

Solutions, either you use `import aliasForA = A`, which will generate a variable `aliasForA = A` so the serialization would work, or not use type aliases.

**Comment by mhegazy** [comment]
@fopsdev this is a different issue. i will file a different bug to track it.

**Comment by wwwsevolod** [comment]
@mhegazy what about @fopsdev issue? can't find created bug ;( im stuck with this bug too =\
