### ISSUE TITLE
Suggestion not shown but parameter hints do show in JS file 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#43647]
- VS Code Version: 1.55.1
- OS Version: Windows 20h2

From #43646

```js
const elementsContainer = document.querySelectorAll('ul');
elementsContainer.forEach((e) => {
    e.addEventListener('dragenter', (e) => {
      e.currentTarget.
    });
});
```

1. Try triggering suggestions for `closest`

![3](https://user-images.githubusercontent.com/17777237/114318650-438b9280-9b0e-11eb-9838-e4b94e76b855.gif)

**Comment by mjbvz** [comment]
The type of `e` is `any` which is why you don't see suggestions

The parameter hints have looser symbol resolving logic. This came up with one of the `Math` symbols before. I think we should consider disabling as I'm not sure how helpful it actually is

**Comment by andrewbranch** [comment]
Isn’t this an example of it working exactly how it’s supposed to work? `e.currentTarget` very likely _is_ an `Element`. We don’t always get these right, but this seems like a demonstration of the value proposition of the feature, not a bug.
