### ISSUE TITLE
NewErrors runs have not been running for the past month

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#43648]
Our last weekly test on popular repos was on https://github.com/microsoft/TypeScript/issues/43004

@amcasey mentioned that a build on [chakra-ui](https://github.com/chakra-ui/chakra-ui) isn't cleaning up properly after 10 minutes, which really shouldn't bring the entire weekly test down.

**Comment by DanielRosenwasser** [comment]
This lives internally in the `typescript__new-errors` repo.

**Comment by DanielRosenwasser** [comment]
We should really try to get this fixed soon to ensure nothing regresses before the RC.

**Comment by amcasey** [comment]
Workaround is [here](https://devdiv.visualstudio.com/NodeRepos/_git/TypeScriptErrorDeltas?path=%2Findex.ts&version=GBmain&line=51&lineEnd=52&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents).  We may wish to continue skipping the problematic repo even after we sort out the timeout issue (looks like the build probably wasn't killed when the timeout was hit).

**Comment by elibarzilay** [comment]
@DanielRosenwasser: this should have been fixed for a while.
@amcasey: can you confirm that it works so this can be closed?

**Comment by amcasey** [comment]
Sunday's run LGTM.
