### ISSUE TITLE
`unique symbol` type lost after property is extracted from an object

### ISSUE THREAD

**Issue by targos** [microsoft/TypeScript#43657]
# Bug Report

Found while working on https://github.com/nodejs/node/pull/38198

### 🔎 Search Terms

unique symbol object

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gawMpIFsQBhVTKFDALngFcUBLAR1oTQE8CAjJCAbgCwAKFCRYCAGb0wGBqngYQmABQA3KBFY0M7AA4gkEnPiKl0GChgCUNVUgbBBI8NDjwpKGXJTwA5iAwAUQAPXSQYDDRlG3gAb2F4RONCEjILSm09AyM8FLNySickhSVqBSzDEswnAF9hYQB6ACoEpORzeBBQmnihYuLc0zTLTP1KwdTzSyL+xMVMUeyqjBnEuqEmhuF2zE7Q+ABePwCQsIioq3qhBob4ZV0YJH0I9itkoamM8rGck0mCjDCLq6AB08wwymBIIm+XS1iuN0QaSRnzKHG4vG2yJ2cMOe1BMOGhSBoTBpWUOMsVicQA)

### 💻 Code

```ts
declare const kSomeConstant: unique symbol;
declare function test(value: typeof kSomeConstant): void;
declare function getExports(): {
    kSomeConstant: typeof kSomeConstant;
    test: typeof test;
}

/*
    const exp: {
        kSomeConstant: typeof kSomeConstant;
        test: typeof test;
    }
*/
const exp = getExports()

// (property) kSomeConstant: typeof kSomeConstant
exp.test(exp.kSomeConstant)

// const constant: symbol
const constant = exp.kSomeConstant;
exp.test(constant);
```

### 🙁 Actual behavior

`exp.test(constant)` is an error, because `constant`'s type is inferred to `symbol` instead of `typeof kSomeConstant`.

### 🙂 Expected behavior

The extracted variable should have the same type

**Comment by RyanCavanaugh** [comment]
This is the intended widening behavior of `unique symbol`, shown in a simpler example:
```ts
declare const kSomeConstant: unique symbol;
declare function test(value: typeof kSomeConstant): void;
const p = kSomeConstant;
test(p);
```
A `unique symbol` type is never transferred from one declaration to another through inference.
