### ISSUE TITLE
Constructor keyword not suggested

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#43650]
# Bug Report

From https://github.com/microsoft/vscode/issues/120881

### 🔎 Search Terms

- suggest
- Intellisense 

### 🕗 Version & Regression Information

4.3.0-dev.20210412

### 💻 Code

```ts
// @ts-check

class Foo {
    abc;
    constructor(name) { }
}
```

Trigger suggest right after `constructor `

### 🙁 Actual behavior

A suggestion for the `constructor` keyword is returned.

### 🙂 Expected behavior
No such suggestion is included

**Comment by DanielRosenwasser** [comment]
Where is auto-complete being triggered here?

**Comment by DanielRosenwasser** [comment]
Ah, I see from the original issue. So certain class member keywords are not suggested once they're finished.

**Comment by DanielRosenwasser** [comment]
The fact that you get keyword completions on

```js
class/*0*/ C {
    yadda;
    async/*1*/ constructor/*2*/() {

    }
}
```

implies you should get keyword completions for

```js
class/*0*/ C {
    yadda;
    constructor/*1*/() {

    }
}
```

as well

**Comment by z0gSh1u** [comment]
It looks like that the `Actual behavior` and `Expected behavior` should be swapped?

**Comment by z0gSh1u** [comment]
Hi! Since no one is working on this, I'll give it a shot.
