### ISSUE TITLE
Incorrect this when passing a method from 1 class to another

### ISSUE THREAD

**Issue by drake7707** [Microsoft/TypeScript#4366]
```
class A {

    private key = "I am key from A";

    private action: () => boolean;

    public constructor(action: () => boolean) {
        this.action = action;
    }

    run(): boolean {
        return this.action();
    }
}

class B {
    protected key = "I am key from B";

    public constructor() {
    }

    test(): boolean {
        alert(this.key);
        return true;
    }
}

var b = new B();
b.test();

var a = new A(b.test);
a.run();

```

This will give 2 alerts, the first one, "I am key from B", obviously, considering I call it directly

However the second alert returns "I am key from A", while the B::test() method is called from a method from A.

The intellisense provided by the compiler in the test() from B is seeing "this" as the B class, which is not always true.

You can verify the code above on the typescript playground.

-- 
I can work around this issue by wrapping the b.test argument as 
```
var a = new A(() =>  b.test());
```

**Comment by RyanCavanaugh** [comment]
This is the ECMAScript behavior of `this`.

See http://stackoverflow.com/a/20627988/1704166 for other solutions.
