### ISSUE TITLE
Set private fields in constructor args

### ISSUE THREAD

**Issue by JonathanDCohen** [microsoft/TypeScript#43678]
# Suggestion

Currently we have this nice convenience:

```ts
class C {
  constructor(private f: string) {} // sets this.f
}
```

However if we'd like to use private fields, we must separately declare and define them

```ts
class C {
  #f: string;
  constructor(f: string) {
    this.#f = f;
  }
}
```

For large classes this can get cumbersome and makes it easier to just use compile-time private fields instead of runtime private fields.  It would be nice to be able to write constructors like this:

```ts
class C {
  constructor(#f: string) {}
}
```

I propose that constructors ONLY may take parameters beginning with `#` and any parameter `#$PARAM` is set to `this.#$PARAM` in the emitted JS.  Since parameters beginning with `#` are already compile-time errors this should be a non-breaking change.

## 🔍 Search Terms

private
private constructor
constructor

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
NA in some sense since this only makes previously invalid expressions valid
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [🤷] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
  * [x] Statically identify constructs that are likely to be errors.
  * [x] Provide a structuring mechanism for larger pieces of code.
  * [x] Impose no runtime overhead on emitted programs.
  * [x] Emit clean, idiomatic, recognizable JavaScript code.
  * [x] Produce a language that is composable and easy to reason about.
  * [🤷] Align with current and future ECMAScript proposals.
  * [x] Preserve runtime behavior of all JavaScript code.
  * [❌] Avoid adding expression-level syntax.
 Although I'd argue it's no more of an addition than `public` and `private`
  * [x] Use a consistent, fully erasable, structural type system.
  * [x] Be a cross-platform development tool.
  * [x] Do not cause substantial breaking changes from TypeScript 1.0.

## ⭐ Suggestion

Allow `#parameters` in class constructors which are the runtime analog of `private parameters`

## 📃 Motivating Example

See the beginning of the request

## 💻 Use Cases

See the beginning of the request

**Comment by DanielRosenwasser** [comment]
This really would be a nice feature; unfortunately it's not something we can do without the support of TC39, the ECMAScript standards committee. If such a proposal does come along that's compatible with this, we'll try to reopen this issue.

**Comment by Jamesernator** [comment]
^ It's probably worth mentioning that while there are historical features of TypeScript such as `constructor(private f: number)` and things like namespaces that aren't part of JavaScript. The current direction of TypeScript is that, other than types, it only adds features that are actually part of the JS spec.

i.e. Going forward, ignoring some of the older features like namespaces and even `constructor(private f: number)` and such, any code that is written in TypeScript would be equivalent to JS if you simply removed the types.

**Comment by JonathanDCohen** [comment]
@Jamesernator I was going to ask what the requirement was that Typescript maintain lock step with TC39.  It makes sense that this is a design decision from the TS team.

Thanks for all you do, I work Typescript every day at my day job and love it ^_^

**Comment by wojpawlik** [comment]
How about allowing just:

```ts
constructor(readonly #f: string)
```

It's already invalid JS syntax.

**Comment by JonathanDCohen** [comment]
@wojpawlik The proposal is already invalid syntax.  I think @DanielRosenwasser's point is that it needs to be on-track to be valid JS in order for the team to consider the proposal.

I have no idea what's involved in submitting a proposal to TC 39

**Comment by wojpawlik** [comment]
I mean, `constructor(readonly f)` is way less likely to become valid JS syntax than `constructor(#f)`.

**Comment by pauldraper** [comment]
> This really would be a nice feature; unfortunately it's not something we can do without the support of TC39, the ECMAScript standards committee.

@DanielRosenwasser this is a nonsensical requirement.

TypeScript constructors will *never* be valid JavaScript:

* Type annotation
* Visibility (private, protected, public) keyword
* Readonly keyword
* Overloads

There are a few ways this feature could work `#f: string`, `private# f:string`, etc, but requiring it to be valid JS syntax is at odds with existing TypeScript.
