### ISSUE TITLE
 //# typingsURL: comment pragma

### ISSUE THREAD

**Issue by majo44** [microsoft/TypeScript#43674]
# Suggestion

## 🔍 Search Terms

typings comment pragma import url 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Related issues: #35749, #41730, #33079 

The idea is very similar to the `//# sourceMappingURL`, that JavaScript code file, by self can point to the place where the types declaration related to current source is located. And as the `sourceMappingURL` the value for the pragma can be a relative path, url, or the inline data url. This will plays well with the individual es modules as well as with the bundles. 

## 📃 Motivating Example
If typescript compiler on one hand will allows to generate the `//# typingsURL` on on the other will read such pragma from the imported sources  this will
* Simplify the work with the [URI style import](https://github.com/microsoft/TypeScript/issues/35749) as just by the same URL import we will get the production code, and the types declaration. 
* Helps with the [NodeJS 12.7+ package exports](https://github.com/microsoft/TypeScript/issues/33079) as we will not need anymore to put the `typings` property to the `package.json` and to `exports` declaration

## 💻 Use Cases

* For TypeScript to find definition file for imports which targets directly code (not declaration, not package), especially in case when the URL style import will be used. 
* Such approach can be easy consumed by the IDE (intellisense, documentation), deno, bundlers, ect ...

**Comment by andrewbranch** [comment]
The compiler really doesn’t want to parse (or even read) (much less _download_) JS that it doesn’t need to, which we would have to do in order to read the comment. You’re right that resolving typings for URL imports is something we’ll have to think about. But we’ll figure out the implementation details as part of implementing whole features/scenarios. Thanks for the input!
