### ISSUE TITLE
Incorrectly extends Interface when overwriting Interface Property Function Argument Type to interface that extends argument

### ISSUE THREAD

**Issue by leumasme** [microsoft/TypeScript#43675]
# Bug Report

### 🔎 Search Terms

extend function argument types incorrectly extends interface

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common Bugs

### ⏯ Playground Link

[This does not work](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgEZwM4QILIN4BQyyADlAPYkD8AXMiAK4C2q0A3AQL4EGiSyIUEAB6QQAE1wix4jGkw58RUhRJ1GLdlx59o8JPKwAhJcTKVsdABRwoAczros2AJTIAvAD5kAN3LBxbV5wPUFkaQgJEwiJOScIE0IzVUtkG3s6GMk3L19-QM4gA)
[But this does work](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210414#code/JYOwLgpgTgZghgYwgAgEZwM4QILIN4BQyyADlAPYkD8AXMiAK4C2q0A3AQL4EGiSyIUEAB6QQAE1wix4jGkw58RUhRJ1GLdlx59o8JPKwAhJcTKVsddFmzbe4PYOTSIEky4lzrEE4TOrLZ1FXSS4gA)

### 💻 Code

```ts
interface baseA {
  prop?: number;
}

interface extendA extends baseA {
  prop: number;
}

interface baseB {
  propA: (arg: baseA) => void
}

interface extendB extends baseB {
  propA: (arg: extendA) => void
}
```

### 🙁 Actual behavior

Error on Line 13:
Interface 'extendB' incorrectly extends interface 'baseB'.
  Types of property 'propA' are incompatible.
    Type '(arg: extendA) => void' is not assignable to type '(arg: baseA) => void'.
      Types of parameters 'arg' and 'arg' are incompatible.
        Type 'baseA' is not assignable to type 'extendA'.
          Types of property 'prop' are incompatible.
            Type 'number | undefined' is not assignable to type 'number'.
              Type 'undefined' is not assignable to type 'number'.(2430)

### 🙂 Expected behavior

TypeScript recognizes that the two types are compatible and lets me extend the interface

**Comment by nmain** [comment]
This is expected behavior.  See https://stackoverflow.com/questions/30365846/why-are-input-parameters-contravariant-in-methods.

**Comment by ilogico** [comment]
This is the correct behaviour, but you can work around it by using methods instead of function properties.
See this [note](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#note)
[playground](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgEZwM4QILIN4BQyyADlAPYkD8AXMiAK4C2q0A3AQL4EGiSyIUEAB6QQAE1wix4jGkw58RUhRJ1GLdlx59o8JPKwAhJcTKVsACjhQA5nXRZsASjoA3csHHbe4PYORpCAkTIIk5RwgTQjNVKxt7QNFgyVdkDy8uIA)

**Comment by leumasme** [comment]
Thanks for the explanation and sorry for the useless issue!
