### ISSUE TITLE
SharedWorker constructor does not accept URL

### ISSUE THREAD

**Issue by johannesf95** [microsoft/TypeScript#43689]
# Bug Report
### 🔎 Search Terms

SharedWorker constructor, Worker URL

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/HYUw7gBAygFghgJxAEwOoHsEGsQIBSiQCqASgDJ4BElAlDQNwCwAUIRBtrgeBKRdXXpA)

### 💻 Code

```ts
new SharedWorker(new URL(""));
```

### 🙁 Actual behavior

SharedWorker constructor only accepts string but not URL.

> [ts] Argument of type 'URL' is not assignable to parameter of type 'string'.

### 🙂 Expected behavior

SharedWorker constructor should accept string or URL like Worker [28397](https://github.com/microsoft/TypeScript/issues/28397)

Since webpack changed its supported syntax for [Worker initialization to pass a URL](https://webpack.js.org/guides/web-workers/#syntax), which also applies to SharedWorker, this missing type became more relevant.

**Comment by andrewbranch** [comment]
Feel free to open a PR at https://github.com/Microsoft/TSJS-lib-generator.

**Comment by TimvdLippe** [comment]
This appears to be another instance of https://github.com/microsoft/TypeScript/issues/43066#issuecomment-790145220

**Comment by FDiskas** [comment]
Works for me

```ts
const worker = new SharedWorker(new URL('./worker.ts', import.meta.url), {
  type: "module",
});
```
tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": [
      "WebWorker",
      "ES2020",
      "DOM",
      "DOM.Iterable"
    ],
    "skipLibCheck": true,
    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
  },
  "include": [
    "src"
  ]
}
```
typescript@5.0.4
