### ISSUE TITLE
Compiler inconsistently (but successfully?) resolves a type which indirectly references itself

### ISSUE THREAD

**Issue by heyheyhello** [microsoft/TypeScript#43683]
# Bug Report

### 🔎 Search Terms

- "ts(7022)"
- "is referenced directly or indirectly in its own initializer."
- "initializer"

### 🕗 Version & Regression Information

Tested and occurs in TS Playground on 4.3.0-beta, 4.2.3, 4.1.5, 4.0.5.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about types that reference themselves in their initializers.

### ⏯ Playground Link

[Playground link with different test cases/attempted workarounds](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/C4TwDgpgBAyglgcwHYEMA2AeAKgPigXigG8oAKASgC4osBuKAX1oFgAoNgEwgGM0UAnaADMArkm7A4AeyRQAtigDWEeMnQBGbFAgAPYBCQcAzsTZQoAbQDSUOLOUgpQmgF1qpCgTwokIclAAfGmsXNgYcUikAIwAraiwqU1Zza1t7CEdnLDdYRFRMLBDtPQNjMn98PDshCH4oACUoAH4GqHiQnBZWBjZuGSNgKA4UYBR1AnklFTyNUiIzKH09agByFYAaBb6xYGoABk3kqG2kYAAFNBEjAHkkCHcKvGHR9QA6E+BPAGoodUPzD4XK5YADuUgeXiGIzG7ykOyBNzu31+hwY5C6bAA9JioAARKQQIxIFaDMH8RSvPEEkxkxRpKAAKRgiwAFnCECzKQB1FkjKAoKJwwYoDgcOwIfmyXTAfgoKAAA08lXl9KwMCabE4PD4gigonEkhkk2UqnyACYtNLSiZ5kdUnYoA4nK53ErvL5-EFClZQt0ItE4jREraUjYHU6sjlTehsEUrYYTG7ypDqrVWi1Gu0fZ0oNioAA5KT6BVulUs2oQMK9fqDZ4oM0TBQmmZoM1zBZLXZQNb-Y5w077XuAy6I+7Jyrjp7Qs2wnbIv5bfvnEeg8GT9d1mfDq63CDz1HozWsPOAHg3AJH7UC513qVmZ56gAHE4AA3QmUI95vpIAZQ0Zm6i2nm5jmJ21DRpgAz8OKnRYjiwF9jsYEthgSAiHIUS1DBx5wcB26jkhaiYKh6GYV0QG4UuCKrgR+QoWhGH8FheY9Ow2GwGyIhoBwxKDHAgxIEWUC0i0PIgLYJhqvyURoNAwBSHqiAiLqQqsrJ4DQM6m4tAAksAKxGLB-JoEY8koCCigggIHCLPJ+hoGgUBXLUJgAEQAJpwvIVyDE5JaPOuAAa8rrFAGHcCgvlqiFJn8PwIAuR+OIALQpalaXpRlmVpYZWW5Xl6WGdcwDlnU6D6PwqCSK+UAAIJnNpQyEnkJgNTKcAQBw76sXmWAsnANJSOSJgyGgYkguWsgKKh6CjVARiQNwcBCCA4qqVAgjAEpsigJArx7VqvACMIYgSNIk1TOBADMlolAmSShvSEYumQSY+H4gTBD6YT+rE8TBgs9rpJkz3gbGPrFPod1JqmdSNBmbSfS4WEsV+P51pdjYXS2l3tkcoHdhsi6IVABxE6cCK7hQ1DEQx93ARtW2-igl2zqc85dOYDBDpRK5glTUA02mIb0xAm0VUzLN4ZT-g-OoHOMAeGJsTVEgiDNYliFwdTFdAbJSNZDo67YchgDJcgGKMhqyM6TbTIRIU64I+n8n24gQGAwCGc6crgTVIhyQAqmAzxpj41k+Py-tSEHId6idVt7ZS+KErYgzlmgYA0MycmOUYlZscVUh50McCCBIo06Ss9mLHFidHjt0C+1HMcjLU2B4IQJD83QjBdFwh26vqp1GhFgfB637ekEISAQhOCQ0egftjyH-Dt0rPV9QNQ1QCNY0TZM032WJ808EtK1IBKRsM+LDc2VIlKFscvIXxArwHTqx0Gmdxp2-kAAsN1IZlGFoDR0GRnTZFdP5Juy9W6rzejgT0iNvqRF+kGACAMwxAwgVGZC3oXAQ2tOuGB0dx7lQwDDBoeB4ZZiRl0FGNYmZ-0xs2Qif9cYgWlKsQmRwPiDjJsuHcSJEgkJbuQwWjE6bmGvrIUepCQ4eH8nWP+rNPgy1+IeI4XMBFUT5iIlsS95FwLoiRSRwtpGi0ZnIsRe4kzKNURTYRUBZaaM5orRKsARBgCgkYcUs0ODUh4kJQaigWjwDkHAHUNkf7gTNCFcacBuAsiGNSYJ5I66sH7h-OOX8jS23AgAVkAUQkBWCwHA0gS9fySZRFkLbggpB+CUEBj+hgu0ZSnqVNBvgwhUMkw1IMc3Opq9KH1EQc0VotDkbVm-LWaEBSWG-3QAUjhiwuEE25sTUmvCeZCLHP0-y1i6mKMhHWApqj5zkE2eTXma4DmQiOQoux8yHEjmls4jRisgA)

### 💻 Code

I'm trying to port a vanilla JS reactive state library to TS. Signals are just getter/setter functions that store a value (`type Signal<T> = { (): T }`). Defining them with a function produces a signal that has a dynamic value.

This is code that a user would write (not the `declare` bit obviously; playground has full example):

```ts
declare function makeSignal<T extends {
  [K in keyof T]: (() => any) | T[K]
}>(obj: T): {
  [K in keyof T]: Signal<T[K] extends () => infer R ? R : T[K]>;
}

const data = makeSignal({
  text: '',
  count: 0,
  countPlusOne: () => data.count() + 1,
  countPlusTwo: () => data.countPlusOne() + 1,
});

// Throws:
// 'data' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer. ts(7022)
```

Instead I tried using `() =>` to add a level of indirection. This surprisingly works, but I don't think it should...

```ts
declare function makeSignal<T extends {
  [K in keyof T]: (() => any) | T[K]
}>(obj: T): {                           // ⬇⬇⬇ NEW `() =>`
  [K in keyof T]: Signal<T[K] extends () => () => infer R ? R : T[K]>;
}

const data = makeSignal({
  text: '',
  count: 0,
  countPlusOne: () => () => data.count() + 1,
  countPlusTwo: () => () => data.countPlusOne() + 1,
});

// Works 🎉
// const data: {
//     text: Signal<string>;
//     count: Signal<number>;
//     countPlusOne: Signal<number>;
//     countPlusTwo: Signal<number>;
// }
```

This works. I worry, is this an **inconsistent resolution by the TS compiler? It isn't capable of resolving the shorter first example, but it can do the second example which uses `infer R` in the same way.** 

I'd like to use the first example, since it feels very odd to tell users _"Please do `() => () => X` because... TS is like that"_

### 🙁 Actual behavior

TS is able to resolve a more complicated variable type that more deeply references its own initializer, but not a more simpler/shallower reference.

### 🙂 Expected behavior

TS would be consistent in applying the 7022 error, either resolving the first example, or failing the second example.

**Comment by heyheyhello** [comment]
I'm mostly interested in knowing if the double `() =>` hack can be relied on - it feels fragile as if it's not supposed to work, and I don't want to tell developers to define all their callbacks as double nested functions only to one day have a new release of TS break type inference.

I'll try building TypeScript locally and seeing what ways there are for stepping through what's happening...

**Comment by andrewbranch** [comment]
The compiler tends to resolve types as lazily as possible, and adding an extra function between a type and one of its members whose type is ultimately recursive could certainly defer work which, if done earlier, would have been a circularity. To answer your question, I think this is likely to continue working, but not outside the realm of possibility of breaking. I would certainly never tell someone “Please do `() => () => X`”; I would tell them to [add a return type annotation on the self-referential functions](https://www.typescriptlang.org/play?ts=4.3.0-beta&ssl=1&ssc=1&pln=12&pc=4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsoBrEAZSwHNUoIAeAFXhAA8MRVgBneAbwFgAUPHgBtANLws+UgE8cieAwC6ALngAKDQEp4AXgB88KKlm6APkonKhAXwMacAIwBW6htvUDhYydPhyCkpq8BTUtIzWzGwc3Jq6hlKoiCAw8ABK8AD8GfDu1gYA3HZCQmB4XBjwwFAYUPqEJORUNBAa3iLsbOoA5D0ANEIi5WgY6gAMgz4jqBgAChDIXADyqCDqOuqoyAROqfpGNXUAdDMYOvAA1PAAjFPDOKMLSwwA7jgbnvDbu-uJR1BTo9Zs8VmsLtc7nZtIUgA).

**Comment by heyheyhello** [comment]
Thanks for the response Andrew. I didn't realize you could add a return type on arrow functions that are in objects, that's a great answer. In the playground I linked I didn't do that and was unhappy with how verbose the alternatives were. Your version is certainly terse enough, so I'll suggest that design.

I imagine the lazy evaluation isn't a bug, even though it's a bit confusing.

**Comment by tjjfvi** [comment]
The reason it was erroring here was the constraint; it was trying to check the `countPlusTwo` property against `() => any`, which forced it to evaluate the return type. When you added another `() =>`, it only had to check `() => () => <defered>` against `() => any`, which doesn't force evaluating `<defered>`.

**Comment by heyheyhello** [comment]
That's amazing thanks! I've poked around the playground a bit and I feel like TS is at least a lot more consistent now with `<defered>` in mind. I'll close the issue.

@tjjfvi how were you able to see that the evaluation was defered? Is that something people need to run TS in a debugger for? I'd love to see how TS breaks down its error reporting to avoid this in the future.
