### ISSUE TITLE
bug: import eliding of `import type` removes previous comments

### ISSUE THREAD

**Issue by milahu** [microsoft/TypeScript#43693]
# Bug Report

import eliding of `import type` removes previous comments

### 🔎 Search Terms

comments before import type are removed

### ⏯ Playground Link

[reproduction on codesandbox](https://codesandbox.io/s/typescript-importsnotusedasvalues-preserve-bug-demo-qm23x)

### 💻 Code

<details>
<summary>ts.transpileModule call</summary>

```js
let result = ts.transpileModule(source, {
  fileName: "test.ts",
  compilerOptions: {
    target: "es2015",
    importsNotUsedAsValues: "preserve",
    onlyRemoveTypeImports: true,
    //isolatedModules: true, // always true in ts.transpileModule
  }
});
```
</details>

```ts
// before 2
// before 1
import type { SomeType } from "./types"
// after
```

### 🙁 Actual behavior

```js
// after
```

### 🙂 Expected behavior

```js
// before 2
// before 1
// after
```

**Comment by andrewbranch** [comment]
The comments are preserved if you add a newline between them and the import. Note also this isn’t specific to `import type`; it’s any import that gets elided. @jessetrinity has looked at comment preservation in great detail so he can correct me if I’m wrong, but I think I mislabeled this—I believe it’s working as intended, with the newline being the most natural heuristic we could come up with—your comment could very well be saying something about the import itself, in which case you’d want it to be removed.

**Comment by RyanCavanaugh** [comment]
See also https://github.com/microsoft/TypeScript/issues/45318
