### ISSUE TITLE
jsdoc template no check

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#43697]
# Bug Report

### 💻 Code

in ts code everything is ok

```ts
// Argument of type 'number' is not assignable to parameter of type 'T'
const a: <T>(func: (x: T, y: T) => T, x: T) => T = (func, x) => func(x, 2)
```

in js code no error
```js
/** @type {<T>(func: (x: T, y: T) => T, x: T) => T} */
const a = (func, x) => func(x, 2)
```

### 🙁 Actual behavior

no error in js code

### 🙂 Expected behavior

the same error as in ts code

**Comment by sandersn** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/42060
