### ISSUE TITLE
Enforcing Generic Type for Generic React Component 

### ISSUE THREAD

**Issue by minseoksuh** [microsoft/TypeScript#43703]
# Suggestion

Hi

I am trying to make a React Component that use Generic Type.

<img width="903" alt="option" src="https://user-images.githubusercontent.com/54365519/114980116-f2412180-9ec6-11eb-97c2-505563256422.png">

For example, because the type of value is "any",

<img width="701" alt="any" src="https://user-images.githubusercontent.com/54365519/114980524-8f03bf00-9ec7-11eb-9a1d-a1fe0fcfb327.png">

I cannot specify the type of value in the component, even though the type of value is actually consistent.
(Which can cause issues like "Uncaught TypeError: Cannot read property 'please' of undefined")

So, I researched the way to create a Generic Component.

![typeError1](https://user-images.githubusercontent.com/54365519/114980812-00437200-9ec8-11eb-9374-957c4fae313a.png)

And it does what I want it to do, forcing types for values inside the component.

However the issue I found irritating was that,

<img width="987" alt="Screen Shot 2021-04-16 at 3 30 27 PM" src="https://user-images.githubusercontent.com/54365519/114981281-b27b3980-9ec8-11eb-9e6a-ec5bee4fcef2.png">

unlike normal Generic function which catches

> Generic type 'FuncProps<T>' requires 1 type argument(s).ts(2314)

generic React Component does not catch when Type is not provided.

## 🔍 Search Terms

- React
- Generic Type
- Functional Component

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Because the user is not given any instructions, it is very likely that he/she will use the component without Typing,

which makes making a component Generic kind of meaningless.

I personally think it can make React Components much more reliable if this kind of Generic Support is provided.

![componentGeneric](https://user-images.githubusercontent.com/54365519/114982535-8a8cd580-9eca-11eb-9de3-989406b0eae3.png)

(EX: if the code above did not have <string | undefined>, and if default Type was not provided, then show "Generic type 'FuncProps<T>' requires 1 type argument(s).ts(2314)" error)

**Comment by ilogico** [comment]
Generic function application also doesn't require you to fill in the type parameters, only when you refer to generic types are you forced to do so.

**Comment by minseoksuh** [comment]
> Generic function application also doesn't require you to fill in the type parameters, only when you refer to generic types are you forced to do so.

Thanks for letting me know. Didn't know about that.

Still, the same applies even if I refer to generic types in Generic React component.

<img width="718" alt="Screen Shot 2021-04-19 at 11 38 30 AM" src="https://user-images.githubusercontent.com/54365519/115174391-23f2fc00-a104-11eb-924f-4fe4ca2a1c1d.png">

I clearly refer to options and value in the component,

yet TS just infers the types of the options, and does not force Type input.

<img width="906" alt="Screen Shot 2021-04-19 at 11 39 10 AM" src="https://user-images.githubusercontent.com/54365519/115174524-5dc40280-a104-11eb-8bc0-22e3950ffb8a.png">

This behavior I believe is in conflict with the utiltiy of TS.
