### ISSUE TITLE
Mark properties defined in Annex B as deprecated

### ISSUE THREAD

**Issue by petamoriken** [microsoft/TypeScript#43709]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `ES2020`.

## Missing / Incorrect Definition

No

## Sample Code

No

## Documentation Link

ES2022 (Draft) B.2 Additional ECMAScript Features for Web Browsers
https://tc39.es/ecma262/#sec-additional-ecmascript-features-for-web-browsers

> These features are not considered part of the core ECMAScript language. Programmers should not use or assume the existence of these features and behaviours when writing new ECMAScript code. ECMAScript implementations are discouraged from implementing these features unless the implementation is part of a web browser or is required to run the same legacy ECMAScript code that web browsers encounter.

ES2022 (Draft) B.2 Additional Built-in Properties
https://tc39.es/ecma262/#sec-additional-built-in-properties

Related: #32191, #19299

**Comment by DanielRosenwasser** [comment]
Thanks @petamoriken!
