### ISSUE TITLE
TS cannot infer return type of multiple functions

### ISSUE THREAD

**Issue by 1abjora** [microsoft/TypeScript#43712]
#### Issue description - I still cannot/don't know how to use [...R] tuple instead of explicit [R1, R2, R3] form.
"typescript": "4.1.5"

Idea is to have HO function which accepts a lists of functions ((...a: any[]) => any), where the list of functions can be given:
- either as array - apl(a: Array<(...a: any[]) => any>)
- or as tuple - apl(a: [...Array<(...a: any[]) => any>])
- or as object - apl(o: { [key in string]: (...a: any[]) => any})
and returns resulting function apl(_): (...a: any[]) => R - which when called:
- calls the all given functions using the given arguments' list (...a:any[]) and returns:
- either an array of results if was given an array of functions
- or tuple of results if was given a tuple of functions
- or object of results if was given an object of functions
- where all results are placed in resulting object of the same shape  and keys (given array of functions results array of results, given object of functions results object of results - all keys match)

Implementation is trivial:
(obj: any) => obj instanceof Array 
  ? (...a: any[]) => obj.map(f => f(...a))
  : (...a: any[]) => mapValues(obj, (f: any) => f(...a))

Problem is to match all types, i.e.
const xx = apl([(s: string, n:number) => s+n, async (s: string) => s.length, () => ["random"]]);
should return a function where xx: (s: string, n: number) => [string, Promise<number>, string[]]

I was able to achieve that using explicit [R1, R2, R3] instead of [...R] - however TS 4.x was advertised as [...R] enabled. So I gave a try :(

const xx = apl([(s: string, n:number) => s+n, async (s: string) => s.length, () => ["random"]]);
xx("Hi", 1);
const yy = apl({ f2: (s: string, n:number) => s+n, f1: async (s: string) => s.length, f0: () => ["random"]});
yy("Hi", 1);

#### Steps to reproduce the issue
As a result I cannot compile the code:

import { mapValues } from "lodash";
type TPure<T> = T extends Promise<infer P> ? P : T;
type TPromise<T> = Promise<TPure<T>>;
type Pr<A> = A | Promise<A>;
export const apl: {
  <T extends Parameters<O[keyof O]>, O extends { [key in string]: (...a: any[]) => any } extends
    ArrayLike<any> ? never : { [key in string]: (...a: any[]) => any }>(o: O): (...a: T) => { [K in keyof O]: ReturnType<O[K]> };
  // <A extends any[], R1, R2, R3, R4, R5, R6, R7, R8, R9, R10>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3, (...a: A) => R4, (...a: A) => R5,
  //   (...a: A) => R6, (...a: A) => R7, (...a: A) => R8, (...a: A) => R9, (...a: A) => R10]): (...a: A) => [R1, R2, R3, R4, R5, R6, R7, R8, R9, R10];
  // <A extends any[], R1, R2, R3, R4, R5, R6, R7, R8, R9>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3, (...a: A) => R4, (...a: A) => R5,
  //   (...a: A) => R6, (...a: A) => R7, (...a: A) => R8, (...a: A) => R9]): (...a: A) => [R1, R2, R3, R4, R5, R6, R7, R8, R9];
  // <A extends any[], R1, R2, R3, R4, R5, R6, R7, R8>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3, (...a: A) => R4, (...a: A) => R5,
  //   (...a: A) => R6, (...a: A) => R7, (...a: A) => R8]): (...a: A) => [R1, R2, R3, R4, R5, R6, R7, R8];
  // <A extends any[], R1, R2, R3, R4, R5, R6, R7>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3, (...a: A) => R4, (...a: A) => R5,
  //   (...a: A) => R6, (...a: A) => R7]): (...a: A) => [R1, R2, R3, R4, R5, R6, R7];
  // <A extends any[], R1, R2, R3, R4, R5, R6>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3, (...a: A) => R4, (...a: A) => R5,
  //   (...a: A) => R6]): (...a: A) => [R1, R2, R3, R4, R5, R6];
  // <A extends any[], R1, R2, R3, R4, R5>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3, (...a: A) => R4, (...a: A) => R5]):
  //   (...a: A) => [R1, R2, R3, R4, R5];
  // <A extends any[], R1, R2, R3, R4>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3, (...a: A) => R4]): (...a: A) => [R1, R2, R3, R4];
  // <A extends any[], R1, R2, R3>(a: [(...a: A) => R1, (...a: A) => R2, (...a: A) => R3]): (...a: A) => [R1, R2, R3];
  // <A extends any[], R1, R2>(a: [(...a: A) => R1, (...a: A) => R2]): (...a: A) => [R1, R2];
  // <A extends any[], R1>(a: [(...a: A) => R1]): (...a: A) => [R1];
  // <A extends any[], R>(a: Array<(...a: A) => R>): (...a: A) => R[];
  <A extends unknown[], F extends Array<(...a: A) => any>>(args: [...F]): (...a: A) => { [K in keyof F]: ReturnType<F[K]> };
} = (obj: any) => obj instanceof Array ? (...a: any[]) => obj.map(f => f(...a)) : (...a: any[]) => mapValues(obj, (f: any) => f(...a)) as any;

#### What's the expected result?
If I correct understand TS syntax - code should compile

#### What's the actual result?
It treats F[K] as object access not as array access
<A extends unknown[], F extends Array<(...a: A) => any>>(args: [...F]): (...a: A) => { [K in keyof F]: 
ReturnType<F[K]> };
        here  ^^^^

#### Additional details / screenshot
I successfully ported another function:
export const all: {
  // <R, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10>(a: [Pr<A1>, Pr<A2>, Pr<A3>, Pr<A4>, Pr<A5>, Pr<A6>, Pr<A7>, Pr<A8>, Pr<A9>, Pr<A10>],
  //   fn: (...args: [A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]) => Pr<R>): Promise<R>,
  // <R, A1, A2, A3, A4, A5, A6, A7, A8, A9>(a: [Pr<A1>, Pr<A2>, Pr<A3>, Pr<A4>, Pr<A5>, Pr<A6>, Pr<A7>, Pr<A8>, Pr<A9>],
  //   fn: (...args: [A1, A2, A3, A4, A5, A6, A7, A8, A9]) => Pr<R>): Promise<R>,
  // <R, A1, A2, A3, A4, A5, A6, A7, A8>(a: [Pr<A1>, Pr<A2>, Pr<A3>, Pr<A4>, Pr<A5>, Pr<A6>, Pr<A7>, Pr<A8>],
  //   fn: (...args: [A1, A2, A3, A4, A5, A6, A7, A8]) => Pr<R>): Promise<R>,
  // <R, A1, A2, A3, A4, A5, A6, A7>(a: [Pr<A1>, Pr<A2>, Pr<A3>, Pr<A4>, Pr<A5>, Pr<A6>, Pr<A7>],
  //   fn: (...args: [A1, A2, A3, A4, A5, A6, A7]) => Pr<R>): Promise<R>,
  // <R, A1, A2, A3, A4, A5, A6>(a: [Pr<A1>, Pr<A2>, Pr<A3>, Pr<A4>, Pr<A5>, Pr<A6>], fn: (...args: [A1, A2, A3, A4, A5, A6]) => Pr<R>): Promise<R>,
  // <R, A1, A2, A3, A4, A5>(a: [Pr<A1>, Pr<A2>, Pr<A3>, Pr<A4>, Pr<A5>], fn: (...args: [A1, A2, A3, A4, A5]) => Pr<R>): Promise<R>,
  // <R, A1, A2, A3, A4>(a: [Pr<A1>, Pr<A2>, Pr<A3>, Pr<A4>], fn: (...args: [A1, A2, A3, A4]) => Pr<R>): Promise<R>,
  // <R, A1, A2, A3>(a: [Pr<A1>, Pr<A2>, Pr<A3>], fn: (...args: [A1, A2, A3]) => Pr<R>): Promise<R>,
  // <R, A1, A2>(a: [Pr<A1>, Pr<A2>], fn: (...args: [A1, A2]) => Pr<R>): Promise<R>,
  // <R, A>(a: Array<Pr<A>>, fn: (...args: A[]) => R): TPromise<R>,
  // <R, A>(a: Array<Pr<A>>, fn: () => R): TPromise<R>, // tslint:disable-line: unified-signatures
  <R, A extends unknown[]>(a: [...A], fn: (...args: { [K in keyof A]: TPure<A[K]> }) => R): Promise<TPure<R>>,
  <R, O extends { [key in string]: any }>(o: O, fn: (a: { [K in keyof O]: TPure<O[K]> }) => R): Promise<TPure<R>>,
} = async (a: any[] | { [k in string]: Promise<any> }, fn: (...args: any[]) => any) => a instanceof Array ? Promise.all(a).then(x => fn!(...x)) :
  ((key = Object.keys(a), val = Object.values(a)) => Promise.all(val).then(res => res.reduce((o, r, i) => (o[key[i]] = r, o), {})).then(fn))();

**Comment by DanielRosenwasser** [comment]
Please use formatting and fill out the bug template.
