### ISSUE TITLE
Feature Request: Reduce property chain in imported symbol from module

### ISSUE THREAD

**Issue by ackava** [microsoft/TypeScript#43724]
# Problem in Module Generation 

```typescript
import { a, b } from "./a";
import c from "./c";
console.log(a, b, c);
```

Results in 

```javascript
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const a_1 = require("./a");
const c_1 = __importDefault(require("./c"));
console.log(a_1.a, a_1.b, c_1.default);
```
This is problem, every time when we refer `a`, internally it is referring `a_1.default`.
The line `const a_1 = __importDefault(require("./a"));` should be changed to `const a_1 = __importDefault(require("./a")).default;`

This is applicable in any module type, UMD, AMD.. .

Every access to imported symbol results in two step property access. 

# ES6 Modules

ES6 modules export constants, they are not changing as you access them, so every access from imported module is essentially a constant. You cannot change symbol once it is exported (that is module is parsed and exports are finalized). Even if you override `Module` and change exported value, changes will still not reflect unless someone calls `import` or `require` again.

I have tried to generate and test various possibilities in ES6 modules but I could not replicate behavior where property chain is needed over a constant import.

# Suggestion

Code generation can be changed to,
```javascript
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const { a: a_1,b: b_1 } = require("./a");
const { default: c_1 } = __importDefault(require("./c"));
console.log(a_1, a_1, c_1);
```
Benefit is, code generated would be smaller.

## Why this is important over minification

**PLEASE READ**
We cannot minimize this by enabling short circuit property chains as minimizing property chains creates problem other logic where minimizer does not support conditional minimizing.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
> ES6 modules export constants, they are not changing as you access them, so every access from imported module is essentially a constant.

This isn't correct.

a.mjs
```ts
let s = 10;
export { s as default };
export function incr() { s++ };
```
b.mjs
```ts
import s from "./a.mjs";
import { incr } from "./a.mjs";
console.log(s);
incr();
console.log(s);
```
This prints
```
10
11
```

**Comment by ackava** [comment]
@RyanCavanaugh Thanks
