### ISSUE TITLE
Ability to get setter types (because now they can be different than getter types).

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#43729]
# ⭐ Suggestion

Now that TS 4.3 introduces the awesome ability to have setter types be a different type than getters, it would be useful to be able to get the type of a setter or getter (not just the property as a whole, which defaults to the type of the getter).

## 🔍 Search Terms

typescript 4.3 get type of setter

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Basically this example shows the issue:

```js
class Foo {
  foo = 123

  _bar: any
  get bar(): number { return this._bar }
  set bar(v: number | string | boolean) { this._bar = Number(v) }

  baz = 'baz'

  set(props: Partial<this>) {
    Object.assign(this, props)
    return this
  }
}

const f = new Foo

const props = {
  foo: 2,
  bar: '123',
  baz: 'blah'
}

f.set(props) // Type error.

console.log(f.foo, f.bar, f.baz) // but it works great at runtime
```

[playground](https://www.typescriptlang.org/play?ts=4.3.0-beta&ssl=1&ssc=1&pln=26&pc=66#code/MYGwhgzhAEBiD29oG8BQ1oDNHQLzQEYAmAZlXWgH0AjMAJwC5owA7ATwoHMBTAF2lp0AFAEomLAK4BbatzopodPhLotovABYBLCADoa9aAF8KEPgPpCAbuOmz5AH2gRedLS07Qn1RCG6sRBU0dfUE8aAA5OzlrQJMKWgAvcIByJJTyDDNeIQAHOnhciCYABXpeLTAQAB5giAA+QLQMDAB5agArbmBeXUgILU4WITqAGmh8wogRCgwlXhU1OooTeOB4FhcscJZuAHc4RHJ1zf5JovDmrEQmIlGE+iYU4hIU+4wkp+pwDQz4zF02TyBSKgQA9GDoAAVNi5bjQOQFOi6Y4bCDwPy6EDwThCAHYeDjAGCIm6JLgyHUCT8LT8PbwOgAaxgnCUYH47MUEhYFSk3CAA)

## 💻 Use Cases

It is currently possible to achieve the desired effect by manually setting the types of the `props` object, but this is more cumbersome, especially when there are many types. I.e., the burden is on the end user instead of the class author (class author can serve many, instead of end users all having to write type defs). 

[Here's an example of that.](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/MYGwhgzhAEBiD29oG8BQ1oDNHQLzQEYAmAZlXWgH0AjMAJwC5owA7ATwoHMBTAF2lp0AFAEomLAK4BbatzopodPhLotovABYBLCADoa9aAF8KEPgPpCAbuOmz5AH2gRedLS07Qn1RCG6sRBU0dfUE8aAA5OzlrQJMKWgAvcIByJJTyDDNeIQAHOnhciCYABXpeLTAQAB5giAA+QLQMDAB5agArbmBeXUgILU4WITqAGmh8wogRCgwlXhU1OooTeOB4FhcscJZuAHc4RHJ1zf5JovDmrEQmIlGE+iYU4hIU5hhWNnfoSRk5cYA9ADIvB+FoACb+EC6B6JJ7UcAaDLxTC6bJ5ApFQJA6AAFTYuW40DkBToMNQJwg8D8uhA8E4QlR2Hg41RglZuiS2OB1AkYP4e3gdAA1jBOEowPxJYoJCwKlJuEA) The end user of the class `as any as number`, which is not ideal.

Ideally the class author would be able to write the `set` method with setter types, something like:

```js
  set(props: Partial<setters this>) {
    Object.assign(this, props)
    return this
  }
```

I don't know what the syntax would be, but the idea is that the result of `setters this` is a type that has the types of the setters for properties that are originally accessors. The other properties works the same as usual.

Or maybe we need types like `get this['foo']` and `set this['foo']` that can return the getter or setter type of a specific property, and then one can create a mapped type that can use the `get` or `set` type operators.

**Comment by trusktr** [comment]
Or, in other words, based on structural typing, `{ foo: number, bar: string | number | boolean, baz: string }` is technically _assignable_ to `{ foo: number, bar: string, baz: string }`.

Maybe the assignability test needs to look at setter types under the hood? This would make it work without adding a syntax addition.

It seems that really we only care about the getter type when we're _getting_ the value.

So the assignability check would need to use setter types of the destination object, or getter types of the source object.

F.e. in `Object.assign(destination, source)`, the type of `source` should be based on getter types, while the types of `destination` should be based on setter types.

**Comment by justinweinberg** [comment]
To add my use case, I would like consumers of my class to be able to assign a setter with a value T or a function that returns a value T, and the on the getter return T (evaluate the function as needed).  

The motivation is to:
-  provide more wrist friendly assignments when the function syntax isn't needed.
- provide a more intuitive result from the getter than () => T
- setup chains of dependent properties  for lazy evaluation and/or revaluation on each evaluation e.g.` _baz = () => this.bar `

```TypeScript
class Foo {

    constructor(spec?:  Partial<Foo>) {
        Object.assign(this, spec);
    }

    _bar : string | (() => string) = ''
    public get bar(): string {
       if (typeof this._bar === 'function') {
           return this._bar();
       }
       return this._bar;     
    }
    
    public set bar(value: string | (() => string)) {
       this._bar = value;
    }

}

//Using assignment with string is fine 
let foo = new Foo();
foo.bar = "Hello";  
console.log(`string assigned setter evaluates to${foo.bar}`)
//Using assignment with function is fine
foo.bar = () => "Hello";  
console.log(`function assigned setter evaluates as ${foo.bar}`)


//Using Partial<T> with value as string is fine
let foo2 = new Foo({bar: "Hello"}); 
console.log(`partial assignment of setter to string results in ${foo2.bar}`)

//Using Partial<T> with () => string gives a type error
let foo3 = new Foo({bar: () => "Hello"} ); //compiler complains unless I force type with 'as any'.   
console.log(`Partial assignment if setter with function results in ${foo3.bar}`)
```

[example](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/MYGwhgzhAEBiD29oG8BQrqeseA7CALgE4CuwB8RAFBAA4CmwA-AFyYAKYRBAlmCAB4E8AHwBKFBizSA8gCMAVowIA6SBB4BzXFQIALHhAA00OozEBuKZgC+6aQH05XaG0JEeuTdAA+0KlQSALwipsSemsHQAOTR1tC0JHIgPMDQmvQE0M7UYm7hXpLSWDwAZv4EAJ4M8OX6hipOLkEtMaUkuOQ8eNESaMUDRJkkRLjQ9RCNOYFWA9B2c0MEI2MTU1wWxfELWPGJyammmdlcVABu-CT0+R6FfgHBoe4RYn3xWGtNRNBB0BcgV1mWDsqBBAHowQBVDSFdRaXAAW3ouCyAHcePowrdvIZoKVPPRoKgQMdSogftBcPRUXBEDNUGT4CochSAEQACXoIBA8FZmyJOHw8BJKh5mioAANnrCoPD6AATI4EAj0b70f4kMAqmAUAAkyEZzK4NglYlQEOhEWgcO0SJR0HRmPanV4eGguPxVIZiCN31+gR+oQ5XJ5fMwqEFEGF9FF8HFEudXTdNqpiogmRVao1WvoMEg0H1hpyJrN6AtMO8nG4fEEABVQo69H9LoT89KcTBPfRiaTEAAmClUmnCKjIHJsYPc3k2SwCvBRkViyW0Li8fjW2W25FZWpKzPjJDt6BDCAkEAEGCeAsG-u+ktlqEV6BVtd1hsYpsBkJYq2aHhnXNrXGapCVVIhKB7LJGQAZkHalaXgUdx38R5oEnUMbGgWcIRwBFaB4Elvlw2hwE8GAOhJKBoAASTxShgEJKoGAdD8YnzMBcEqaIVF2SNo1jeMXxrDcNC3e0yj3VUWKdDokzGE8zwvd0xkLRBoLvU0gA)

**Comment by trusktr** [comment]
CLosing as duplicate of 

- https://github.com/microsoft/TypeScript/issues/60162
