### ISSUE TITLE
__spreadArrays - `this` is undefined

### ISSUE THREAD

**Issue by xon52** [microsoft/TypeScript#43728]
# Bug Report

I recently came across a Rollup build issue for [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator):
```bash
(!) this has been rewritten to undefined
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/vue-property-decordator/index.js
1: var __spreadArrays = (this && this.__spreadArrays) || function () {
                         ^
2: for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
3: for (var r = Array(s), k = 0, i = 0; i < il; i++)
...and 1 other occurrence
```

Investigating I found the same issue for the browser-detect package: [https://github.com/DamonOehlman/detect-browser/issues/162](https://github.com/DamonOehlman/detect-browser/issues/162)

Looking a little closer, the root issue appears to be coming from Typescript; specifically the `__spreadArrays helper` which was added here: [commit/375487ec602c7cc8b4dd9e3991ad6145d8bbe21f](https://github.com/microsoft/TypeScript/commit/375487ec602c7cc8b4dd9e3991ad6145d8bbe21f).

This var is meant to replace the spread operator, but after it has defined itself, it should be reused.
**Because `this is undefined` it always re-defines itself**.

### 🔎 Search Terms

- Rollup "this has been rewritten to undefined"
- __spreadArrays
- "this is undefined"

### 🕗 Version & Regression Information

Relevant commit is [here](https://github.com/microsoft/TypeScript/commit/375487ec602c7cc8b4dd9e3991ad6145d8bbe21f) made on 12 Jun 2019

### ⏯ Playground Link

The issue is pure JavaScript (`this` is undefined), and depends on other tools (like Rollup) catching the issue on packages built with Typescript. Not sure how to add that to a playground.

### 💻 Code

```ts
// src/compiler/factory.ts
export const spreadArraysHelper: UnscopedEmitHelper = {
        name: "typescript:spreadArrays",
        scoped: false,
        text: `
            var __spreadArrays = (this && this.__spreadArrays) || function () {
                for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
                for (var r = Array(s), k = 0, i = 0; i < il; i++)
                    for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
                        r[k] = a[j];
                return r;
            };`
    };
```

```ts
// tests/baselines/reference/argumentExpressionContextualTyping.js
// tests/baselines/reference/arrayLiteralExpressionContextualTyping.js
// tests/baselines/reference/arrayLiteralSpread.js
// tests/baselines/reference/arrayLiterals2ES5.js
// tests/baselines/reference/arrayLiterals3.js
// Lots and lots more from [the relevant commit](https://github.com/microsoft/TypeScript/commit/375487ec602c7cc8b4dd9e3991ad6145d8bbe21f)
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
```

### 🙁 Actual behavior

When a spread operator `...` is used and transformed to `__spreadArrays()` the code above is added to the top of the file. There is a warning that the `this` in `this && this.__spreadArrays` is undefined.

**Considering that, I imagine that this function is broken because it will always re-define __spreadArrays with the function**

### 🙂 Expected behavior

- Not re-defining __spreadArrays every call
- No undefined error

I believe this could be fixed by modifying the first line added to either:
```ts
var __spreadArrays = (__spreadArrays !== undefined) || function () {
```
or
```ts
var __spreadArrays = (window.__spreadArrays) || function () {
```

**Comment by MartinJohns** [comment]
> var __spreadArrays = (window.__spreadArrays) || function () {

`window` may be `undefined` as well. This could would lead to a `ReferenceError`.

It sounds more like an issue with Rollup to me.

**Comment by xon52** [comment]
> `window` may be `undefined` as well. This could would lead to a `ReferenceError`.
Quite possibly - certainly if it's not a browser that uses this.
 
> It sounds more like an issue with Rollup to me.
I believe that if you insert `this` at the top of a JavaScript file it will be undefined - Rollup is just pointing that out.
Outside of the annoying warning, `(this && this.__spreadArrays) || function () {...}` will always run `function () {...}` because `this` is always undefined. So at the very least I think it may be worthwhile removing `(this && this.__spreadArrays) ||`

**Comment by MartinJohns** [comment]
> I believe that if you insert this at the top of a JavaScript file it will be undefined

I'm not sure that is true. I couldn't find a case where `this` would be `undefined`. It's even defined directly in a NodeJS session.

**Comment by xon52** [comment]
My mistake. In a browser it appears `this` at the root is window. So I imagine it's an IDE issue as this at the top of a file is always undefined (as context is not considered). Could `global.__spreadArrays` replace `(this && this.__spreadArrays)`? It should be `window` in a browser and whatever the equivalent is for other platforms (and so always defined)?

I'll raise this with rollup too.

**Comment by nmain** [comment]
> I'm not sure that is true. I couldn't find a case where `this` would be `undefined`.

In the top level of an ES module, `this` is `undefined`.  For proof, paste the following code into the console of any modern web browser:
```js
(s => { s.textContent = "console.log('this is:' + this)", s.type = "module", document.body.appendChild(s) })(document.createElement("script"))
```

So typescript's emit doesn't quite make sense when you ask it to transpile down spread but leave everything as modules.

**Comment by RyanCavanaugh** [comment]
The helper works this way so that you can shim it with an earlier script in a global context.

There's nothing per se wrong with it; Rollup's complaint would be valid if a human wrote this code, but since we use the same helper in all contexts for consistency, it's being overzealous. Rollup should have some way to configure this warning so that it doesn't trigger on this particular snippet.

**Comment by xon52** [comment]
This issue can be easily solved in rollup by correctly adding any external dependencies as external dependencies in the `rollup.config.js` ([https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency](https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency).

By doing so, rollup skips these ES module checks.

Thanks for everyone's input on this. Hopefully it helps anyone else stuck on it!
