### ISSUE TITLE
Parameters does not factor in generics or overloads

### ISSUE THREAD

**Issue by didii** [microsoft/TypeScript#43731]
# Bug Report

### 🔎 Search Terms

* "parameters with generic function"
* "generic function wrapping"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behavior, Generics, 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVAZQygxABp4SA+ACgCh54BnARgC56KqtNvAAOMHACtwGPk259ylagEp4AXgb1lCgNwtQkWAhTpseAsUWCudK9QBMt5sPn8lIGy-sKBDmsLFJaVlXOw86Dm83QXtVDS1dFhYAemT6AAssDngs+FQcDHgAd3SqeABJYpxkCGB4EAAPEWkWDABPZvgAQRgAc2y1eAAFWCgAWxBqGA4iduacRAsGHXhU9XgAbVc0AGt8otQIqN39w9FxKUwQ3ngTnAOjvjuDuM1n1ABdJLWyHAmMTKoXoVKo1OqlABuCEazUwIGArQ6CAAok1pPDSL5aPRbFibNEHJo1MItjcwnRApcZPA5GSsa96F92AAfTahPGPAkgRznIJXGns9z4yI+dyxdSaEgfPTfNLIqH4LCLLCFIogODwDA4eBwDDIGD4AHQtFwupzbEqzjYCAQUG1PIFKowHYsEyYXD4IowKAiZowTHuWy4oXBmLMAB0kdg-T4qNh1GAAcEQa5+LC9gYqgA3sJdfr8IhCExI+HoxxlHp2Gt2DWawA9BuNuvwOPour2AC0AGZ4NHkBNUBgOHQAEbIQq9R0ABngOBg8DGc5A4aY9gArGuAGzKFgAXxYQA)

### 💻 Code

```ts
declare function foo<TState, T>(
  s1: TState,
  project: (s1: TState) => T): T;
declare function foo<TState1, TState2, T>(
  s1: TState1,
  s2: TState2,
  project: (s1: TState1, s2: TState2) => T): T;

// This is not what I would expect
type Args = Parameters<typeof foo>; // = [s1: unknown, s2: unknown, project: (s1: unknown, s2: unknown) => unknown]

// Something I would have expected
type Expected<TState, T, TState1, TState2> =
  [s1: TState, project: (s1: TState) => T]
  | [s1: TState1, s2: TState2, project: (s1: TState1, s2: TState2) => T];


// Even if it were to return the expected type, it still would not work
function wrapper<TState, T, TState1, TState2>(...args: Expected<TState, T, TState1, TState2>) {
  return foo(...args);
  //         ^^^^^^^ Expected 2-3 arguments, but got 0 or more.(2556)
}
```

### 🙁 Actual behavior

The `Parameters` type seems to choose either the last or a random overload of the given method instead of all of them. Also doesn't factor in generics and converts them to `unknown` instead.
Even if it would return what I would have expected (see `Expected` type in example), it still isn't usable in practice.

### 🙂 Expected behavior

That `Args` would result in something similar to `Expected`. All of the overloads should be factored in and also generics.
The `Expected` args should be usable on `foo`.

### Real-world usages

Any wrapper function where the original function is complex, has overloads or is generic. In our case, it's everything :)

More specifically I want to reduce boilerplating with `@ngrx` so I wanted to wrap the function `createSelector` which is declared [here](https://github.com/ngrx/platform/blob/cdb5bd5b2ff9c8c49c96204e3e4798ed605c0c80/modules/store/src/selector.ts#L121-L513), which is similar to the `foo` of my example, but with 31 overloads instead of only 2 and where the return type is dependent on the parameters (the `project` argument).

Wrapping this method is possible, but requires just an insane amount of copy-pasting with some little changes which isn't feasible and does not exactly help in reducing the amount of code.

**Comment by MartinJohns** [comment]
`Parameters<T>` is based on type inferrence in conditional types, and type inferrence in conditional types does not support overloading: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types

This is a known design limitation.

**Comment by didii** [comment]
Thanks for clarifying. Bummer that it isn't supported yet. Are there any plans to support this? I can't see anything about it in the [roadmap](https://github.com/microsoft/TypeScript/wiki/Roadmap) at the moment.

**Comment by MartinJohns** [comment]
I haven't seen any mention regarding this by the TypeScript team, so I wouldn't get my hopes up.

**Comment by didii** [comment]
I'd actually still want to add to this that generics are also not supported since they all get converted to `unknown`.

Here is the same playground, but without the overloads: [Playground](https://www.typescriptlang.org/play?ts=4.0.5#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVAZQygxABp4SA+ACgGcBGALnoqtvgAcYOAFbgMXVp26VqASngBeBvVlcSAbgBQmgPQ76ACywt4x+KhwZ4AdwNV4ASRs5kEYPBAAPfmM0YAnj7wAIIwAOYmCvAACrBQALYg1DAsRAE+OIgEOAzq8HqK8ADa7FxoANYW1qh0giJiEqXwFVWo8krNqJU41QC62ijo2Hg2MFD8PjBMAHSzsBFcsWOJyanpIJnZDPIA3prw8HAYyDD4iIQzc+EssloAvtrr8ADqYxMgMCSBCFHrm9ZvSZ5ApRSRlLqtWpCUSYRpSFo9NqKZQI6rtFEQxHabQFZ52KxOawuNweby+J4AUTJmBAwFIPGodEYhRKUnIMj4dRh4ngYOkvHR9H6mkGmFw+AB40mACZ6RymcxZtN5iwuFSfDS6ezeArdvtDkkTmcLkqVbdNA8-N8XoCPtKvkFft9-raYNLgfoonKdfRmE1tYyBNCGrz-QyQIKSJHNEA)

**Comment by MartinJohns** [comment]
Because `WrapperType` is not generic. You can't pass along generic types like this. I **think** this would require #1213.
