### ISSUE TITLE
generic type is shared unexpectedly 

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#43730]
# Bug Report

### 💻 Code

```ts
type Left<E> = { tag: 'left', data: E }

type Right<R> = { tag: 'right', data: R }

type Either<E, R> = Left<E> | Right<R>

declare const data: Left<string>

declare const idEither: <E, R>(either: Either<E, R>) => Either<E, R>

// Got: Either<string, string>
// Expected: Either<string, never>
const result = idEither(data)
```

### 🙁 Actual behavior

Type L is shared to R

### 🙂 Expected behavior

Type R is inferred as never

**Comment by nmain** [comment]
There's no inference source for `R` here; for instance, this passes type check:
```ts
const result = idEither<string, { lunch: "turkey club with mayo" }>(data)
```

Typescript 4.1.x and below infer `<string, unknown>` here, and can be persuaded to use `<string, never>` instead with this declaration:
```ts
declare const idEither: <E = never, R = never>(either: Either<E, R>) => Either<E, R>
```

But that doesn't work in 4.2.

**Comment by weswigham** [comment]
Regressed by https://github.com/Microsoft/TypeScript/commit/22bee779d729547ca1ea90b1575f34a6f178ad21 I believe (with the caveat that the prior result was indeed `<string, unknown>`, not `<string, never>` without any type parameter defaults to change that).

**Comment by weswigham** [comment]
Conversely, I'm not sure this is a bug - the type of `R` isn't being matched on anywhere, but we have the philosophy that generally speaking, some inference is better than no inference (and it'll error down the lien if it's wrong anyway). So, in service of that, we're matching the `data` field of `Left<string>` to the `data` field of `Right<R>` - we are structural, after all. I can't come up with a compelling argument why we _shouldn't_ make this inference, so I think the new behavior is fine.

**Comment by awerlogus** [comment]
@weswigham

> some inference is better than no inference

OK. Let's mark any empty array as array of strings then. Why not?

```ts
// Should be string[] by default
const a = []
```

I believe that no inference is better than wrong inference. 

`Right` type can not be inferred in that example, but it's somehow being narrowed using a value out of thin air. Relationship based on prop name is not relevant in that case at all. 

So, if we know that some union cases are not reachable, let's infer generic types that are used only by them as `never`.

**Comment by awerlogus** [comment]
Requesting reopen of the issue

**Comment by RyanCavanaugh** [comment]
@awerlogus request seen but not fulfilled. Your follow-up comment was not pertinent at all. If you can actually demonstrate an unsoundness originating from this behavior we can reconsider.
