### ISSUE TITLE
Nullish Coalescing returns fallbackValue for truthy value

### ISSUE THREAD

**Issue by evangeloszotos** [microsoft/TypeScript#43734]
# Bug Report
### 🔎 Search Terms
Typescript Nullish 
Typescript Nullish Coalescing
Typescript ?? 
Typescript ?? brackets
Typescript Nullish Coalescing precedence
Typescript Nullish Coalescing Ternary

### 🕗 Version & Regression Information
v3.8.3
v4.2.3
Nightly

- This is a crash => NO
- This changed between versions => NO
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _Nullish_Coalescing_
- I was unable to test this on prior versions because => Tested

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/MYewdgzgLgBATgUwgVwDawLwwEQAllyFwCGAntjAPyUwCMMGjdVOAKgBbGwDuxEMyMAgAeABwTAoCACYUAXDgCqolRACE2ALAAoUJBCoEAOlQgA5gApEKdAEoYAegcMAfDFFwAlmCj88BIjItbR1Q7SA)

### 💻 Code
```ts
const result = "Hurrrray" ?? 1 === 1 ? "That was unexpected" : "Uppps!"
console.log(result) // => prints "Hurrrray"
```

### 🙁 Actual behavior

` prints => "That was unexpected" `
It is wrong, because the value "Hurrrray" of the ?? - Operator is truthy 

### 🙂 Expected behavior
` prints => "Hurrrray" `
because the value "Hurrrray" of the ?? - Operator is truthy

**Comment by MartinJohns** [comment]
That is the correct behavior. You get the same result when running it as JavaScript.

**Comment by evangeloszotos** [comment]
Thank you for clarification. Considering the information which you provided the operator works as intended.
