### ISSUE TITLE
JSX `<a>#</a>` fails to emit because a shebang trivia scan is attempted

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#4374]
This line https://github.com/Microsoft/TypeScript/pull/4120/files#diff-a15280067dcb3b0929808762f8352e86R468 

Followed by https://github.com/Microsoft/TypeScript/pull/4120/files#diff-a15280067dcb3b0929808762f8352e86R543 

Fix coming soon :rose:

**Comment by basarat** [comment]
Weird that this : https://github.com/Microsoft/TypeScript/pull/4120/files#diff-a15280067dcb3b0929808762f8352e86R406 didn't block a trivia scan.

**Comment by mhegazy** [comment]
thanks @basarat !

**Comment by basarat** [comment]
:rose:
