### ISSUE TITLE
semantic hightlighting function classified as class

### ISSUE THREAD

**Issue by aeschli** [microsoft/TypeScript#43747]
From https://github.com/microsoft/vscode/issues/114894

-- save the following into JavaScript file
```
var test = {
	find: function () {
		this.text = null
	}
}
```
- Note that `find` is classified as class
![image](https://user-images.githubusercontent.com/6461412/115353315-accb6f80-a1b8-11eb-9a1a-340de9dea131.png)
- remove the `this`, it will be a function

**Comment by Kingwl** [comment]
Currently, TypeScript assume all function who have(Or only have) `this assignment` like `this.xxx = yyy`  are a Constructor.

#featureNotBug

**Comment by HondryTravis** [comment]
yes, just like this obj, in obj function internal, as long as `this.xxx =` appears after, this code will be shown different color。
