### ISSUE TITLE
Template literal destructure

### ISSUE THREAD

**Issue by meepeek** [microsoft/TypeScript#43746]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- Template literal destructure
- String pattern destructure
- String pattern validation and extraction
- String type destructure

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It would be nice if we could destructure a string with template literal into variables. Please find the example code below

## 📃 Motivating Example

```
const {y: number, m: number, d: number, t: string}: `${y}-${m}-${d}T${time}` = '2020-08-05T10:15:00'
// result is y = 2020, m = 8, d = 5, t = '10:15:00'
```
This could be done by generating code from split, type convert and custom validate function and the code would be very easy to read, compact and type safe.

## 💻 Use Cases
- id string, phone string, date format
- custom string data extraction

I try to extract date string from web and it is really a pain. Using library such as momentjs can be do so but with more lines of code and I face a lot of problem when I need to move to luxon as the momentjs itself suggests to move on (https://momentjs.com/docs/#/-project-status/). It would be better if I can manage this from vanilla code. Currently, I am doing something like this:
```
const [year, month, date] = dateString.split('-').map( v => Number(v) )
```

**Comment by RyanCavanaugh** [comment]
>  This could be implemented without emitting different JS based on the types of the expressions

We don't do things that don't check this box; that's why it's on the form.
