### ISSUE TITLE
"sufficiently overlaps" on class instance depends on class statics

### ISSUE THREAD

**Issue by evmar** [microsoft/TypeScript#43754]
# Bug Report

### 🔎 Search Terms

sufficiently overlaps class namespace

### 🕗 Version & Regression Information

TS 4.2, TS v4.3.0-dev.20210420 

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about compatibility

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210420#code/FAYwNghgzlAEDCBGWBvWAzA9pgFASlQF9ZDhgA7AUwHcFF9ZpYAlSkTAJwBMAeKAFw4BLcgHMANLACu5ANblM1cgD4A3LFgB6TbEocOnSU0oAPAA5t+lLmTLhoceACZUGbAxTFS5CAFtKUGYQIJQILmimZpz8sOzkAtLkHJSQVlywALywAMzqpBQ0YQxMrOzcfIIiEonyiirqWjoQYGCK1gCEAPzAQA)

### 💻 Code

```ts
class C1 { foo() {} }
new C1() as Record<string, unknown>;  // error, as expected

class C2 { foo() {} }
namespace C2 { export const unrelated = 3; }
new C2() as Record<string, unknown>;  // allowed!?
```

### 🙁 Actual behavior

The existence of the field in the C2 namespace somehow affects the assignability calculation of the instance.

### 🙂 Expected behavior

I would expect these namespace-level properties to not get involved (?) in the assignability of instances.

Either both succeed or both fail.

**Comment by ayazhafiz** [comment]
This is due to the check

```ts
        function isObjectTypeWithInferableIndex(type: Type): boolean {
            return type.flags & TypeFlags.Intersection ? every((<IntersectionType>type).types, isObjectTypeWithInferableIndex) :
                !!(type.symbol && (type.symbol.flags & (SymbolFlags.ObjectLiteral | SymbolFlags.TypeLiteral | SymbolFlags.Enum | SymbolFlags.ValueModule)) !== 0 &&
                !typeHasCallOrConstructSignatures(type)) || !!(getObjectFlags(type) & ObjectFlags.ReverseMapped && isObjectTypeWithInferableIndex((type as ReverseMappedType).source));
        }
```

which yields true for `C2` since it's a ValueModule. This then enables the check

```ts
                if (!(intersectionState & IntersectionState.Source) && isObjectTypeWithInferableIndex(source)) {
                    // Intersection constituents are never considered to have an inferred index signature
                    let related = eachPropertyRelatedTo(source, targetType, kind, reportErrors);
                    if (related && kind === IndexKind.String) {
                        const numberIndexType = getIndexTypeOfType(source, IndexKind.Number);
                        if (numberIndexType) {
                            related &= indexTypeRelatedTo(numberIndexType, targetType, reportErrors);
                        }
                    }
                    return related;
                }
```

in `indexTypesRelatedTo` in the checker.

Admission of ValueModules as an inferable index object type was added in b94924533690661c9b5e6b2ef60b136e624adb83. One solution is to say a ValueModule that is merged with class/function declaration never has a inferable index type, but Im not sure this is desirable.
