### ISSUE TITLE
Inference fails for generic type extending keyof generic type extending Record<string, string>

### ISSUE THREAD

**Issue by mihai1voicescu** [microsoft/TypeScript#43778]
# Bug Report

### 🔎 Search Terms

keyof record string extends fail inference 

### 🕗 Version & Regression Information

4.x 3.x

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8BlAFmADgU2tgHgC7YB2AJjAErbDwBOZSEhdAliQOYA00zbnAPmgBeaNVoMmLdt17TBQgN4AoaGuhgkAaTxFSFaAGtsAT3gAzaOizYBACgBGALmhaAlNBXrv0APS-eNHgAVxAyaHZzbDo5fg5VHzU6bEJguhIIiBR5Dkc3AG4EtQBfZSKNEkcXYzNLaxwPL0S-AIgg0PDI6NiZcu9k1PTM7Li8wu9S0uVzYJJgQlZ4DNYsnLsIFz4ZRuVioA)

### 💻 Code

```ts
class Foo<Shape extends Record<string, string> = Record<string, string>> {
    a<K extends keyof Shape>(b: K) {
        // should infer string
        return isString(b);
    }

    an(b: keyof Shape) {
        // should infer string
        return isString(b);
    }
}

function isString(s: string) {
}
```

### 🙁 Actual behavior

TS infers that b is of type `string | number | symbol` or `string | number` depending on the version of TS.

### 🙂 Expected behavior

TS should infer that b is of type string, as `keyof Record<string, string>` resolves to `string`

**Comment by RyanCavanaugh** [comment]
This is a correct error; `Record<string, string>` is a constraint on the types of string-keyed properties, but does not prevent other structural subtyping. This is a legal call that passes a `symbol` to `isString`:
```ts
const s: unique symbol = Symbol();
const p = new Foo<{ [s]: 1, "foo": ""}>();
p.a(s);
```
