### ISSUE TITLE
assertion functions with globally scoped variables don't work when imported

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#43772]
# Bug Report

### 🔎 Search Terms
Assertion function narrow

### 🕗 Version & Regression Information
4.3.0-beta

### ⏯ Playground Link

Can't reproduce in the playground as multiple files are required

### 💻 Code

foo.ts:
```ts
declare const foo {
    bar: number
}
```

bar.ts:
```ts
declare function narrowFoo(_foo: typeof foo): asserts _foo is typeof _foo & {baz: number}
narrowFoo(foo)
console.log(foo.baz) //works
```

baz.ts
```ts
import './bar'
console.log(foo.baz) //compile error: property baz doesn't exist
```
### 🙁 Actual behavior
The `foo` type isn't narrowed 

### 🙂 Expected behavior
`foo` is narrowed since `import './bar'` imports runtime side effects, it should also import compiletime side effects

**Comment by MartinJohns** [comment]
Shouldn't you also call `narrowFoo` somewhere?

**Comment by DetachHead** [comment]
Oops, fixed

**Comment by RyanCavanaugh** [comment]
The performance cost of this would be massive, it wouldn't work under declaration emit, and I can't imagine this being common at all

**Comment by DetachHead** [comment]
Thanks for the reply. Do you mind elaborating on those points since I'd like to learn more about how the compiler works

> The performance cost of this would be massive

Why's that? I don't see how it'd ccause any issues as all it's really doing is telling the compiler to compile `baz.ts` as if it was appended to the bottom of `bar.ts`. Or is the problem that there's be no way to stop it from compiling `bar.ts` multiple times?

> it wouldn't work under declaration emit

How come?

> and I can't imagine this being common at all

I probably should've included my use case. I think it would be very useful for prototype extensions and for tools like cypress where to add new functions you have to define their signatures twice:

```ts
declare global {
    interface Chainable {
        foo(bar: number): string
    }
}

cy.Commands.add('foo', (bar: number) => "foo")
```
Instead you'd be able to define both at the same time using an assertion function 
```ts
//(pseudocode, the actual function signature to make this accurate to how commands work in cypress is like 60 lines long)
function addCommand<Name extends string, Func extends (...args: any[]) => any>(
  _cy: typeof cy, //need to pas the unused cy object in order for the function to be able to change its type
  name: Name,
  func: Func
): asserts _cy is typeof cy & { [Key in Name]: Func } {
  cy.Commands.add(name, func)
}

//add the new command
addCommand(cy, 'foo', (bar: number) => "foo")

//use the new command
cy.foo(1)
```
this (mostly) works fine except that there doesn't seem to be a way to import the new commands outside of the file they're defined in, since the narrowed `cy` object gets reset to its initial type when you try to import it.

though this seems quite hacky (and now that i think about it, i don't even know if it's possible with prototype extensions with the current limitations of assertion functions and type predicates).

i'm going to raise a separate issue as a feature request which will better fit these use cases.

**Comment by TimvdLippe** [comment]
> and I can't imagine this being common at all

We encountered this issue in Chrome DevTools with our definition of `assertNotNull`: https://github.com/ChromeDevTools/devtools-frontend/blob/63cc5fdff7bc2ee8cef9be01c93b93f0af95f1f4/front_end/core/platform/typescript-utilities.ts#L10 In general, we wanted to extract commonly used TypeScript utilities in this file. However, we quickly ran into this limitation, which wouldn't per se be a problem, except for the fact that we enforce `import * as` for cross-module loads: https://docs.google.com/presentation/d/1KaTDaKEcLmgv3Wum79gPP9mv9x2fm3kuEgx_b8wLVug/preview?slide=id.g6f3bb6e30c_0_163

This means that we currently have to do the following:
```ts
import {assertNotNull} from '../../core/platform/typescript-utilities.js'; // This breaks in production

assertNotNull(foo);
```

whereas our style guide would normally dictate the following:
```ts
import * as Platform from '../../core/platform/platform.js';

Platform.TypeScriptUtilities.assertNotNull(foo);
```

The reason we have this requirement is that we bundle our source code in production in a bundle for each module, which means that the assertion function in the first snippet will actually break in production: https://docs.google.com/presentation/d/1KaTDaKEcLmgv3Wum79gPP9mv9x2fm3kuEgx_b8wLVug/preview?slide=id.g6f3bb6e30c_0_144. As such, we are unable to use TypeScript assertion functions in our production code (we solely use it in tests atm).
