### ISSUE TITLE
Using generics as record keys doesn't narrow types correctly

### ISSUE THREAD

**Issue by danyonedwards** [microsoft/TypeScript#43775]
# Bug Report

### 🔎 Search Terms

assigning a narrowed type to a variable behaves as original type
reassigning a narrowed type loses narrowed type
record with generic keys narrowed type lost

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about narrowing types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwAKAnA9meAeGUIA9gIA7AE3ikRQEtiBzAPigF4oBvAKCm6jpIhoBjANIQQALlgBuLjwBuAQwA2AVwiSAShEFoUpHABooAEQVEoAHygqyEAGa0IpBhwC+HDjuKIoRH6xw8QhJySmAaegYACjB0TEk4RFQMbBgGAEoWJk4eKC8fNj5iAWoRMSNFVQhXFihYlJlc-OAoO3QAW1NzVkq1AG0ikrKQAF0ZWW5qOygogEI2tE6zCEyUCGAVFGIoAHJiNCheiB3Gngm8tG8WlXgnLuhWBaWiADo+YHuo9PGmy59w6hOGBoACC8Hg1DoxHuknutSe9x+PDWGy2h2UahkNW4QA)

### 💻 Code

```ts
type TestProps<T extends string> = {
    genericKey: T;
    value: Record<T, Date | undefined>
}

const test = <T extends string>(props: TestProps<T>) => {
    const {genericKey, value} = props;
    const fromDate = value[genericKey];

    if (!fromDate) return 'no value';
    
    const usedDate = fromDate.getDate();

    const triedToAssignDate: Date = fromDate;

    return value;
}   
```

### 🙁 Actual behaviour

The variable `triedToAssignDate` is not using the narrowed type from `fromDate` and is resorting to the `Date | undefined` of the original `Record` value.

### 🙂 Expected behaviour

I expect to be able to assign `fromDate` without any issues and use it as a `Date` object.

**Comment by RyanCavanaugh** [comment]
This is fixed in the nightly build
