### ISSUE TITLE
Refinement for "obj != undefined" persists after obj becomes undefined again

### ISSUE THREAD

**Issue by jtbandes** [microsoft/TypeScript#43781]
# Bug Report

Inside `if (obj != undefined)`, it is possible for `obj` to become undefined again, but the compiler thinks it is still certain to be defined.

### 🔎 Search Terms

Refinement of undefined through function call

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the [FAQ about soundness](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#a-note-on-soundness)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strict=true#code/BQQwzgngdgxgBMAlHAvAPjgbwLACg5wwD2UYALnEQEYBWAjAFxZwAeA-E1AK4C2VApgCc4AX1TMWTOqIDceAgEsAZgmr0AdCzgBCFHC5QAJvyUKo-Q8hz4ClWnU3qyRAGIKWFpDLgB6H5QBreVsQAHcQBQpzULgABUEiHgUwfmBgQWR0OEFgNQctPQNjU3NLRDkbAjzHZzcPQy9ffzAACyIuABtDOAE4ECg4IQTBYJE8EUQkdRgQMhgW4GJSIg7+dSGiDIq8UEhYBEyMawJVijUAJk5eAWEAH30jEzMLcToKxRVc2nOdQseSixWYJVb5OVzuTzlJqBYF9cKRODROIJJIpNIZVAYHIXcRFJ6lRDlWEXMF1SHePxwVrtLo9fh9AYbEY2Ma4CZTGZzBZLMArNZMxB4IA)

### 💻 Code

```ts
(async () => {
  const obj1: { x?: number } = { x: 1 };
  if (obj1.x != undefined) {
    obj1.x.toFixed(); // ok
    await new Promise((r) => r(obj1.x = undefined));
    obj1.x.toFixed(); // should be an error
  }
})().catch(console.error);

(async () => {
  let obj2: number | undefined = 1;
  if (obj2 != undefined) {
    obj2.toFixed(); // ok
    await new Promise((r) => r(obj2 = undefined));
    obj2.toFixed(); // should be an error
  }
})().catch(console.error)
```

### 🙁 Actual behavior

`[ERR]: undefined is not an object (evaluating 'obj1.x.toFixed') `

### 🙂 Expected behavior

Compile error. After the `await`, `obj1.x` and `obj2` may become undefined again, so the refinement from `!= undefined` should not persist.

For comparison, [Flow gets this right](https://flow.org/try/#0BQQwzgngdgxgBMAlHAvAPjgbwFBzjAeyjABc4CAjAKwEYAuLOADwH4GoBXAWwoFMAnOAF9UjJgxrCA3LjgBLAGYJKtAHRM4AQhRwOUACa8FcqL33IcePCprrVJAgDE5TM0ilwA9J-IBrWXggAO4gcmSmQXAACvwEXHJgvMDA-MjocPzANuqieobGpuaIMlbk1LZM9k4ubsVePmAAFgQcADb6cHxwIFBwArH8skLYQohIqjAgJDCNwITEBK28qv0EqTLYoJCwCGkYlnBLZCoATOzcfIIAPnAAbgRyHTo0JfJKWdQnWjp5RiZmFgCZSoJyqzlc+nc9T8QOCoXCvEiMTiCSSKT2GQ+INyBj+hUQxSBpzBNUhdW8cCaLXanV43V6q0GeGGo3Gk2ms3mYEWy0ZiGwQA).

**Comment by jtbandes** [comment]
I noticed this because [`@typescript-eslint/strict-boolean-expressions`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md) told me a check was unnecessary when it was actually necessary.

**Comment by RyanCavanaugh** [comment]
Side effects of this form aren't considered. See #9998

**Comment by RyanCavanaugh** [comment]
Side note, Flow gets this "right" by getting it wrong in all non-mutating cases:
```ts
(async () => {
  const obj1: { x?: number } = { x: 1 };
  if (obj1.x != undefined) {
    obj1.x.toFixed(); // ok
    await new Promise(() => {});
    obj1.x.toFixed(); // Errors in Flow
  }
})().catch(console.error);
```

**Comment by jtbandes** [comment]
I've found that to be not such a big deal as it's made out to be in #9998 — I'd probably opt in to this stricter behavior for TS if I could.
