### ISSUE TITLE
TS6307: json file not listed within file list

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#43784]
# Bug Report

### 🔎 Search Terms

build mode, composite, json, resolveJsonModule

### 🕗 Version & Regression Information

Repros as of 3d24b85f9e5dde6f35d6014539aeef9801e74493.

### 💻 Code

tsconfig.json
```json
{
    "compilerOptions": {
        "composite": true,
        "resolveJsonModule": true
    },
    "includes": [
        "a.ts",
        "b.json"
    ]
}
```

a.ts
```ts
import { x } from "./b.json";

x.toString();
```

b.json
```json
{
    "x": 1
}
```

### 🙁 Actual behavior

```
a.ts:1:19 - error TS6307: File 'C:/tmp/JsonBuild/b.json' is not listed within the file list of project 'C:/tmp/JsonBuild/tsconfig.json'. Projects must list all files or use an 'include' pattern.

1 import { x } from "./b.json";
                    ~~~~~~~~~~
```

### 🙂 Expected behavior

No error.

Note: works with `files`, rather than `include`.

**Comment by sheetalkamat** [comment]
Your tsconfig has includes instead of include .. is that the issue ?

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/tsconfig#include

**Comment by amcasey** [comment]
@sheetalkamat that does resolve the problem in this toy repro, but the full size repro has `include`, so I'll have to investigate further.

**Comment by amcasey** [comment]
In the meantime, if I drop the `include` entirely, .ts imports are fine but .json imports trigger errors.  Expected?

**Comment by RyanCavanaugh** [comment]
That's correct, since the default include pattern is `**/*.ts`

**Comment by amcasey** [comment]
In that case, it's probably something obscure with path mappings.  I'll re-open if I find a sensible repro.
