### ISSUE TITLE
WebAssembly: ExportValue not callable

### ISSUE THREAD

**Issue by behunin** [microsoft/TypeScript#43782]
https://github.com/microsoft/TypeScript/blob/fb6c8392681f50a305236a7d662123a69827061f/lib/lib.dom.d.ts#L19245

> This expression is not callable.
  No constituent of type 'ExportValue' is callable.

I am seeing this error on all `ExportValue` functions defined.

I have had success with this approach: `(...args: any) => any`
Instead of `Function`

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
