### ISSUE TITLE
Incorrect interface implementation not raise type error

### ISSUE THREAD

**Issue by urffin** [microsoft/TypeScript#43789]
# Bug Report

### 🕗 Version & Regression Information
Reproduced in 4.2.3 and later in playground

```ts
interface Interface {
  stringOrNumber(x: string | number): void;
}

class MyClass implements Interface {
  stringOrNumber(x: number) { // missing string!!!
    console.log(x.toFixed(2)); // BOOM
  }
}


function callInterfaceMethod(cc: Interface) {
    cc.stringOrNumber("foo");
}

callInterfaceMethod(new MyClass());

var t: (x: string | number)=> void = (x: number) => { // missing string!!! error!!!
    console.log(x.toFixed(2)); // BOOM
  }
```

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```
**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/JYOwLgpgTgZghgYwgAgJLmvJyDeAoZZAZzClAHMB5KAOQFcBbAI2gAoAPALmNIuQB9kIRiygBKbgDcA9sAAmAbjwBfPHgQAbOESLIAsgE8Awlp3JgDAA4aIDCOF3pIsRCnyESZEFVoi2XIT9xXGQAelDkBmAdPk8KAEJEgkJkBGkQImkbADoNaXIObLBpADFgdgg5VgAmMTEFMIiAIUpKPWTVVTUYOhAEMGB01LgNDSdMVz0IMAALaSqEBG5xlyQxXGTCRey472p6ZjYAIhhpaSP6lTUEEbGMVYgp2fnWEAgAd31jUyJWOqU8JI4FBkGBuBxuLtyAJAodxABeAB8yBk8mQ8OQENhonWSJC4Ui0SIsV43kS8U2qXSmRyeQK7CKpXKlRq-0ayBabQ6QA)
      

### 🙁 Actual behavior

Available implement interface with different parameters for union type
```ts
interface Interface {
  stringOrNumber(x: string | number): void;
}

class MyClass implements Interface {
  stringOrNumber(x: number) { // missing string!!! but no error
    console.log(x.toFixed(2)); // BOOM
  }
}
```
No Error for this code.

### 🙂 Expected behavior

Expected type error, like in same  case for simple functions
```ts
var t: (x: string | number)=> void = (x: number) => { // missing string!!! type error!!!
    console.log(x.toFixed(2)); // BOOM
  }
```

**Comment by MartinJohns** [comment]
Please see [FAQ: Why are function parameters bivariant?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)

**Comment by urffin** [comment]
> Please see [FAQ: Why are function parameters bivariant?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)
> 
> This is working as intended.

But this should be fixed for flag "strictFunctionTypes". As you can see above flag is up, but type checking still fail

**Comment by MartinJohns** [comment]
`strictFunctionTypes` do not apply to class methods. This is intentional.

**Comment by urffin** [comment]
@MartinJohns but, how subtyping relate to union types?

**Comment by urffin** [comment]
hmm, but why for simple function raised error? Why logic is change?

**Comment by ilogico** [comment]
> but, how subtyping relate to union types?

A union is a supertype of the alternatives. So `number` is a subtype of `number | string`.

**Comment by urffin** [comment]
@RyanCavanaugh, hi, why it still intended if this raise error for simple function? Seems behavior look not consistent

**Comment by RyanCavanaugh** [comment]
This is covered in the FAQ, which has already been linked.

**Comment by urffin** [comment]
> This is covered in the FAQ, which has already been linked.

In linked FAQ not exist anwser

**Comment by RyanCavanaugh** [comment]
The FAQ can't demonstrate every possible permutation of code. `string | number` and `string` are related the same way `Animal` and `Dog` are.

**Comment by urffin** [comment]
> The FAQ can't demonstrate every possible permutation of code. `string | number` and `string` are related the same way `Animal` and `Dog` are.

But question not about types, but about why for simple function checking is work, and for methods is not
