### ISSUE TITLE
Support bigint type for Intl.NumberFormat.formatToParts

### ISSUE THREAD

**Issue by carlansley** [microsoft/TypeScript#43799]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `esnext`.

## Missing / Incorrect Definition

`Intl.NumberFormat.formatToParts(number?: number).`

The `number` parameter can also be a `bigint`.

## Sample Code

This valid code:
```
Intl.NumberFormat([], {
  style: 'currency',
  currency: 'USD',
}).formatToParts(3500n);
```

Produces compiler error:
```
error TS2345: Argument of type '3500n' is not assignable to parameter of type 'number | undefined'.
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts

**Comment by Scharkee** [comment]
I have opened a PR to address this issue: #44015
