### ISSUE TITLE
Incorrect destructured types when setting a default value

### ISSUE THREAD

**Issue by ottah** [microsoft/TypeScript#43795]
# Bug Report

### 🔎 Search Terms
destructure object parameter interface function

### 🕗 Version & Regression Information
3.333 - 4.2.3 have this bug

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function destructuring

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIhge2QbwLABQyyIcAthAFzIDOYUoA5gNyHFyNUkCuZARtFYEAvoUIB6ccgDCmKFAgIwhBJhB1kMEAEZkAXmQAKHKQr7kAJmHJq6LAEpqAN0zAAJvoB8uYULEFQSFhEFAAxEFkyAAcAHgAVcxxhb3wiYiMoqEwommo4x2QXdyFRAgkpdFV5RTAAOmQAA1MIBtoAC0xuABsPAUa6BhBGBtqVNQ0tC2pwyNi7TG8DY2bzK3svXGRff1V1ME0QAGZzQ3W9FLZ03Y1M7Ny0DGwDE3IuAHJmt4AaZA4uABYrEJ0shJI1mq0aB1uh4AFbcDR9BoDJgNAD8l2I132LzMBis5luOUIwiAA)

### 💻 Code
When destructuring it is possible to assign a different default value type to that of its original type. This shouldn't be the case as now that new variable is a union of its previous type and the new default value type.

```ts
interface Info {
  name: string;
  age: number;
}
```

When destructuring a parameter with a explicit type given an error is thrown: `Type 'number' is not assignable to type 'string'.ts(2322)`. This the correct behaviour.

```ts
const fn1 = ({name = 2} : Info): void => {};
```

However the same doesn't apply when using an interface function type. `name` becomes a union - `name: string | number`.

```ts
interface FnComp<T = {}> {
    (props: T): void;
}

const fn2: FnComp<Info> = ({name = 2}) => { };
```

When destructuring an object to variables a union is created `name: string | 2`.
This makes sense but is still undesirable most of the time.
```ts
const props: Info = {name: 'name', age: 42};
const {name = 2} = props;
}
```

### 🙁 Actual behavior
Destructuring interface function type parameters allows you to set a different type as the default value.
Destructuring objects/arrays to variables lets you to set a different type as the default value.

### 🙂 Expected behavior
Destructuring interface function type parameters should not let you set a different type and act the same as a normal function.
Destructuring objects/arrays should not let you set a different type as the default value.

**Comment by RyanCavanaugh** [comment]
There's nothing unsound about this inference, and this behavior is perfectly consistent with a plain desugaring of the destructuring:
```ts
const fn2: FnComp<Info> = (obj) => {
    // name: string | 2
    const name = obj.name === undefined ? 2 : obj.name;    
};
```
