### ISSUE TITLE
Comments removed after transforming the AST

### ISSUE THREAD

**Issue by lrabinowicz** [microsoft/TypeScript#43794]
# Bug Report
Comments before "}" (close bracket) are removed after transforming the AST for the file. Structure: Block.
![image](https://user-images.githubusercontent.com/12565958/115903464-75f39480-a418-11eb-9c70-1f6469443be9.png)

Comments after "{" (open bracket) are removed if they are in the same line as the bracket after transforming the AST for the file. Structure: Block
![image](https://user-images.githubusercontent.com/12565958/115922493-d0e5b580-a431-11eb-95ca-9a94a3ffb700.png)

Comments after a "," are removed after transforming the AST for the file.
![image](https://user-images.githubusercontent.com/12565958/115922309-9714af00-a431-11eb-85b7-c595da8a34e7.png)
![image](https://user-images.githubusercontent.com/12565958/115934395-c7fedf00-a445-11eb-9f20-89ef3039dfe8.png)

In this PR there are some fixes but the ones mentioned above still happen:
https://github.com/microsoft/TypeScript/issues/17689

### 🙁 Actual behavior

Comments are removed.

### 🙂 Expected behavior

Comments should still be there after transforming the AST.

**Comment by weswigham** [comment]
So, we don't track `}` and `{` in the AST, specifically - can you elaborate on what structure those tokens are actually a part of (eg, body of an `if`, or body of a `function`)? In some of your screenshots it's not clear.

**Comment by RyanCavanaugh** [comment]
Duplicate #6982, #8800, etc.

**Comment by lrabinowicz** [comment]
@weswigham I've updated the description with more information. Let me know if there is anything else I can add :) Thank you!
