### ISSUE TITLE
Behaviour inconsistency when a functions returns an inline set versus a variable of type set

### ISSUE THREAD

**Issue by ElianCordoba** [microsoft/TypeScript#43807]
# Bug Report

### 🔎 Search Terms

-- Different behaviour
-- Different type
-- Same code

### 🕗 Version & Regression Information

I found that this started happening after version `3.5.1`, before that there was no error bacause the type of the variable was `Set<string>`

This is still present in the nightly build.

### ⏯ Playground Link
[Link](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/GYVwdgxgLglg9mABMOcAUBKAXIgygUygB4BnKAJxjAHMA+RAbwChFFzCRykx8B3PQpgDcTAL5MmoSLASIARgENymHAWJlKNes1YQEZRCUKIAvIh781wia3ZROSI1BHimAejeIAggBsfiOGBEKAALGBJEXjhyAGsI4Cp8SXBoeCQAWwUABy8VRABZbKIwEHS5fHIAGnNS8vJtFjYOLnM+AuzrVylU2UysgCE8wqzi2orqkrKKht19KEQ+01b+YetGuwcF7JcJbpkkODkAK3xoXOxGRAUcSbrEUUZ15qQGK5wARnud5Ok0gOPTlBBhdXtcalNyPdHrMwAZDkclqCPl8bE17C14S4gA)

### 💻 Code

```ts
function foo(): Set<string> {
  return new Set();
}

function bar(): Set<string> {
  const set = new Set();

  return set; 
         ^^^
  // Type 'Set<unknown>' is not assignable to type 'Set<string>'. 
  // Type 'unknown' is not assignable to type 'string'.(2322)
}

// All of these works fine
function mapA(): Map<number, number> {
  return new Map();
}

function mapB(): Map<number, number> {
  const map = new Map();

  return map;
}

function objectA(): { a: number } {
  return { a: 1 };
}

function objectB(): { a: number } {
  const obj = { a: 1 };

  return obj;
}
```

### 🙁 Actual behavior

There is an error in only one of the functions

### 🙂 Expected behavior

The behaviour should be the same in both `foo` and `bar`

**Comment by RyanCavanaugh** [comment]
This behavior follows from the library definitions. You can file a bug to specifically change one of them to something else (likely to be rejected on compatability grounds) but there's no per se defect here.
