### ISSUE TITLE
Type narrowing is lost when creating a variable

### ISSUE THREAD

**Issue by pikax** [microsoft/TypeScript#43809]
# Bug Report

### 🔎 Search Terms

bug, if, type, conditional, type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210424#code/GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmAFMgFyIDeiMyA-JWCJgEbYBOiAvgJTUAoRIgA2uWkxbsuAXkQBGIbWCIyAOjr8qS4TERzkG5DsQQEAZyiI4+lCYD096xwf2zYS9ds01v5D1cvGHNEAANmNk5EAB9EcGRsYEJsZFDEAFpaDyhsAEN-OBVwqU5Qkz05OCMlbgFuIA)

### 💻 Code

```ts
function doSomething(d: { id?: number }) {
  let i: number = 1
  if (d.id) {
    i = d.id
    const  o = d;
    // or
    //const o = { ...d }
    // o is `number | undefined` - instead of `number`
    i = o.id
  }
}

```
### 🙁 Actual behavior

`o.id` has type `number | undefined` instead the already narrowed type of `number`

### 🙂 Expected behavior

Both expressions should be the same: `i = d.id` and `i = o.id`

EDIT: Removed the spreading information, as pointed out by @whzx5byb this also affects variables declared in the narrowed scope.

**Comment by whzx5byb** [comment]
This is not related to spreading. Changing `const o = { ...d }` to `const o = d` still produces the error.

**Comment by RyanCavanaugh** [comment]
Narrowings of properties don't propagate up to their parent types; this is basically #10065
