### ISSUE TITLE
Broken inferred recursive types

### ISSUE THREAD

**Issue by blackakula** [microsoft/TypeScript#43817]
# Bug Report

TypeScript inference on recursive types is broken since v4.1

### 🔎 Search Terms

- inferred
- recursive

### 🕗 Version & Regression Information

- This changed between versions 4.0.5 and 4.1.5

### ⏯ Playground Link

[Playground link with 4.3.0-beta](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/MYewdgzgLgBAQgVwJYBsAmBTATjAvDAHgBUYMAPKDMNCGAbwF8A+ACgFsRMUAuGIgSjxMYLOgCgYkmAHckUABYBhEGzZUovFqFXre0LEjABzQbmGJUmLKJgA6exy4AaGNrVhYDfk4lTZCgGUABwxgJABDFGUdD01Tc2R0bHZODBR+W38lFXcoFgByYNCIlFcc9XzvX0ksoixw4ABrQyMAOQQ2ACNsTSh6ppbeMA7urHj4RKsbe1tHNJc+hubjGC8fKRhOybihGDnSrzExUEhYcLwJy2TGfgBuMQB6B5hwzLlsmLz8ymhK2y3LCwMosBisnjAAPIAaRgAFpSGQQsBKGgYAAiAAKWBAISwUAAnjBvv1lkZ8jA0CAMLQwCBYOQkNAYOAYASQkS6GVPno+i1bqt8mi0cdwBAQCgMLYUCAjCxXrUSS12l1kgBGABMAGYACwZLJFMKRaK5IH-SamkGk-hAA) - with the TS errors

[Playground link with 4.0.5](https://www.typescriptlang.org/play?ts=4.0.5#code/MYewdgzgLgBAQgVwJYBsAmBTATjAvDAHgBUYMAPKDMNCGAbwF8A+ACgFsRMUAuGIgSjxMYLOgCgYkmAHckUABYBhEGzZUovFqFXre0LEjABzQbmGJUmLKJgA6exy4AaGNrVhYDfk4lTZCgGUABwxgJABDFGUdD01Tc2R0bHZODBR+W38lFXcoFgByYNCIlFcc9XzvX0ksoixw4ABrQyMAOQQ2ACNsTSh6ppbeMA7urHj4RKsbe1tHNJc+hubjGC8fKRhOybihGDnSrzExUEhYcLwJy2TGfgBuMQB6B5hwzLlsmLz8ymhK2y3LCwMosBisnjAAPIAaRgAFpSGQQsBKGgYAAiAAKWBAISwUAAnjBvv1lkZ8jA0CAMLQwCBYOQkNAYOAYASQkS6GVPno+i1bqt8mi0cdwBAQCgMLYUCAjCxXrUSS12l1kgBGABMAGYACwZLJFMKRaK5IH-SamkGk-hAA) - no errors

### 💻 Code

```ts
const Builder = <T extends {}>(model: T) => ({
    withComment: (comment: string) => Builder({ ...model, comment }),
    withSpecialComment: () => Builder(model).withComment('Special comment'),
    withTrackingNumber: (tracking: number) => Builder({ ...model, tracking }),
    build: () => model })

const a = Builder({});
// a.withComment('test').build().tracking // OK - expected "Property 'tracking' does not exist on type '{ comment: string; }'""
console.log(a.withTrackingNumber(1234).withSpecialComment().build().tracking)
```

### 🙁 Actual behavior

TS compiler error: "The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.(7056)"

### 🙂 Expected behavior

No errors on compilation

**Comment by ahejlsberg** [comment]
Below is a version with an explicit type annotation. This works as expected and generates a nice and compact declaration file.

```ts
type Builder<T> = {
    withComment: (comment: string) => Builder<T & { comment: string }>,
    withSpecialComment: () => Builder<T & { comment: string }>,
    withTrackingNumber: (tracking: number) => Builder<T & { tracking: number }>,
    build: () => T
};

const Builder: <T extends {}>(model: T) => Builder<T> = <T extends {}>(model: T) => ({
    withComment: (comment: string) => Builder({ ...model, comment }),
    withSpecialComment: () => Builder(model).withComment('Special comment'),
    withTrackingNumber: (tracking: number) => Builder({ ...model, tracking }),
    build: () => model });

const a = Builder({});
```

**Comment by SephReed** [comment]
Currently running into this issue.

I find that everything is fine until this error comes up, then suddenly the entire language server starts taking 3-6 seconds to respond to anything.

Unfortunately, It's very, very much impossible for me to give "An explicit type annotation is needed."

Also, everything was working fine this morning, and I can't seem to figure out what has changed since then.  So I know TS can do it.

I even have a demo within my installed project that works great, but converting it to an npm package appears to have made the recursion too much somehow.

**Comment by SephReed** [comment]
I made some progress on this issue by converting all my interfaces to abstract classes.  Not sure why it worked, but you can read more here:

https://stackoverflow.com/a/68475392/4808079

**Comment by blackakula** [comment]
Closing this issue without a fix - means breaking backward compatibility in a minor version.
Just [checked in 4.4.0-beta](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/MYewdgzgLgBAQgVwJYBsAmBTATjAvDAHgBUYMAPKDMNCGAbwF8A+ACgFsRMUAuGIgSjxMYLOgCgYkmAHckUABYBhEGzZUovFqFXre0LEjABzQbmGJUmLKJgA6exy4AaGNrVhYDfk4lTZCgGUABwxgJABDFGUdD01Tc2R0bHZODBR+W38lFXcoFgByYNCIlFcc9XzvX0ksoixw4ABrQyMAOQQ2ACNsTSh6ppbeMA7urHj4RKsbe1tHNJc+hubjGC8fKRhOybihGDnSrzExUEhYcLwJy2TGfgBuMQB6B5hwzLlsmLz8ymhK2y3LCwMosBisnjAAPIAaRgAFpSGQQsBKGgYAAiAAKWBAISwUAAnjBvv1lkZ8jA0CAMLQwCBYOQkNAYOAYASQkS6GVPno+i1bqt8mi0cdwBAQCgMLYUCAjCxXrUSS12l1kgBGABMAGYACwZLJFMKRaK5IH-SamkGk-hAA) - still this error

**Comment by mxxnseat** [comment]
i have same issue with mongoose when i try update my document with error text:
`Type instantiation is excessively deep and possibly infinite.`
```
Product.findOneAndUpdate(
            { id: product.id },
            {
                ...product,
                productCategoryId: categoryId,
                parentGroup: groupId,
            },
            { new: true, upsert: true }
        )
```

**Comment by SephReed** [comment]
I haven't shared it in this thread, but one fix I found is to use abstract classes instead of interfaces in certain areas.

I have no idea why this works, but an abstract class that references itself is much happier than an interface that does.  Worked for me at least...

**Comment by zomars** [comment]
This issue just started popping up without any changes made to our project.

**Comment by Qix-** [comment]
This is happening with AJV schemas (trivial ones at that), but only in my editor. The actual `tsc` invocation works fine.
