### ISSUE TITLE
TextTrackList must be iterable

### ISSUE THREAD

**Issue by iamart** [microsoft/TypeScript#43814]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

TextTrackList must be iterable

## Sample Code

video.textTracks.forEach(...)

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList

**Comment by MartinJohns** [comment]
`TextTrackList` **is** already iterable, and `TextTrackList` does **not** have a `forEach` method. Running that code would result in an error.

**Comment by iamart** [comment]
@MartinJohns unless I'm reading it wrong, MDN states:

> The individual tracks can be accessed using array syntax or functions such as forEach() for example.

Besides, `for(let x of video.textTracks)` errors out as well.

**Comment by MartinJohns** [comment]
> @MartinJohns unless I'm reading it wrong, MDN states:
>> The individual tracks can be accessed using array syntax or functions such as forEach() for example.

I don't know about MDN, but in Chrome the property `forEach` was `undefined`.

> Besides, `for(let x of video.textTracks)` errors out but works fine in chromium.

It works fine in TypeScript too, when you include the appropiate lib ("dom.iterable"):

    const textTracks = {} as TextTrackList;
    for (const track of textTracks) { }

**Comment by iamart** [comment]
Thanks, @MartinJohns.
I'm surprised that it has a separate library that needs to be included.
