### ISSUE TITLE
Object possibly null in a callback function from a local variable defined inside a function

### ISSUE THREAD

**Issue by TheThing** [microsoft/TypeScript#43827]
# Bug Report

### 🔎 Search Terms

Object possibly null callback
Object possibly null function local

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about functions and variables.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210426&ssl=1&ssc=1&pln=32&pc=1#code/JYOwLgpgTgZghgYwgAgJKQLbIN7JHDCALmQGcwpQBzAGmRlGFIAsIATEgIwHtuAbCHBDIAvgFgAUJIFhkwTKRIBBKFDgBPADzoIGAHzIAvMgDaAXUmSYAVxAIwwbsLil1dgGJwA1hADKEEDYACgROEndbe0cQAEocSWQyCDAAFWBCbmswEM46AEYABgKYyXEpCRs7BydkKmSAGThIciVA-0CgmJIdLAAfPGs+PniJRJl6TMDuzGR+kEHh43mhy1GJqGQg8eAjZAKAbjlkTTkFADoBECowZkPgAGp7uOwExLkYTYBCeV1SE2AzGcGCAmKw2M9Xm8JrY2Lsfhg-gDIW9OFBBF5kWVEmVXsAPkFPjBJuDkGiwNYoMJlnxVokXG4EJ4fO1gp0jAYXmtEkSYUDGCx2LsKNYIMi6mBGs0wK02CzOq8RCVyokyRThDzAqVVvDSGcAA7WFhBXD4QgkADkSnNdGBoPYJGFKEVkh1+sNzGNeAIxGQlut9H5YJI8D4pCdStdBqNJu9FqtNsD9vocFD4ckQA)

### 💻 Code

```ts
interface Item { name: string, finished: boolean }

let items: Array<Item> = []

function asyncFakeSend(cb: Function) {
  setTimeout(cb, 100)
}

function getLatestAndSend() {
  let found: Item | null = null

  for (let i = 0; i < items.length; i++) {
    if (!items[i].finished) {
      found = items[i]
      break
    }
  }

  if (!found) return

  asyncFakeSend(() => {
    found.finished = true
    getLatestAndSend()
  })
}
```

### 🙁 Actual behavior

Typescript thinks `found` variable inside the `asyncFakeSend` could be null even though I've already verified it is not with the above `if` statement and there is no possible way of re-assigning that variable in the function after the fact or at least in the above code sample.

### 🙂 Expected behavior

No errors.

### 🙁 Workaround

My coworker suggested I create a **new** variable from the `found` inside the function like so:

```
function getLatestAndSend() {
  let found: Item | null = null

  for (let i = 0; i < items.length; i++) {
    if (!items[i].finished) {
      found = items[i]
      break
    }
  }

  if (!found) return

  let foundToMakeTypeScriptHappy = found

  asyncFakeSend(() => {
    foundToMakeTypeScriptHappy .finished = true
    getLatestAndSend()
  })
}
```

But I've never been a fan of adding code noise that provides no functionality and only exists to make typescript happy. Especially when in above situation, `found.finished` can never be null (as far as I understood javascript).

**Comment by MartinJohns** [comment]
Duplicate of #9998.

**Comment by TheThing** [comment]
I saw that and I scrolled through the issue description but to me it didn't seem relevant to my issue as none of the examples seemed to relate to me (at least to me). Especially since on my end this feels like a bug rather than some logic problem. My bad.
