### ISSUE TITLE
Exports on the wrong directory 

### ISSUE THREAD

**Issue by harshetmaruff** [microsoft/TypeScript#43837]
this is what i wrote in tsconfig.json 

{
    "CompilerOptions": {
        "rootDir": "src",
        "outDir" : "dist"
    }
}

but it exports js on src folder itself, i want to export in dist folder

**Comment by alexrock** [comment]
JSON is case-sensitive.

"***c***ompilerOptions": {

**Comment by harshetmaruff** [comment]
Thank you alexrock I got it working now
