### ISSUE TITLE
Unexpected ASI after `static` in class

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#43836]
# Bug Report

### 🔎 Search Terms

static ASI newline

Related: https://github.com/microsoft/TypeScript/issues/38283

### 🕗 Version & Regression Information

It fails 4.2.3 and nightly. It works in 4.0.5. I think this regression has been introduced by https://github.com/microsoft/TypeScript/pull/41127.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=4.3.0-dev.20210426#code/MYGwhgzhAECC0G8BQ1oQC5nQS2CtmOeAvkkA)

### 💻 Code

```ts repro
class A {
  static
  static
}
```

### 🙁 Actual behavior

It is parsed as two instance fields named `static`.

### 🙂 Expected behavior

It should be parsed as a static field named `static`.

**Comment by RyanCavanaugh** [comment]
The phrasing in expected/actual is a bit jumbled, so to be clear, the correct behavior is to parse this as `class A { static static; }`

**Comment by nicolo-ribaudo** [comment]
> The phrasing in expected/actual is a bit jumbled

Oh I just got them reversed, I updated the description.
