### ISSUE TITLE
Narrowing on an instance field should be discarded after a method call but isn't

### ISSUE THREAD

**Issue by floriancargoet** [microsoft/TypeScript#43834]
# Bug Report

### 🔎 Search Terms

- refinement
- never
- narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (every version on the playground from 3.3.3 to nightly = 4.3.0-dev.20210426), and I reviewed the FAQ for entries about refinement/narrowing/never.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210426#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnA9tgFzTK4CWAdgObQA+0lAriCNALyMsgDcm0SREgAU2MLjABbEmSrUAlGn5YkAC3IQAdHkIcurHtAD0Rgeq07s0DdFzwAZlXgATAfmgAiZqw-KzGzQh4JAAFAmxRcSl5QxN-GAhVfBZXYDBKYHg2NXhbBydJeEokP3J7aGE1AMsOdk4xCUlFVGNTHLzHSnhC4usEpHJWaFV4Oz8sBqlNJHwAGXwAd1GAYUh4YRjW0ndJyT6BAE9sF2hITy6AN1HfLCwAX34HrCDQ8OELsBAmeBkkChpmn4qhZwnoPl94Hx7ug7kA)

### 💻 Code

```ts
class Test {
  prop: string | null = null;
  test(param: string) {
    this.prop = null;              // this.prop is narrowed to null.
    this.setProp(param);           // I think this should cancel the narrowing but it doesn't.
    if (this.prop === param) {     // Still narrowed to null, null will never be equal to a string.
      const p1: never = param;     // So param is typed as "never"
      const p2: never = this.prop; // and so is this.prop.
    }
  }
  setProp(value: string) {
    this.prop = value;
  }
}
```

### 🙁 Actual behavior

`this.prop` is refined to `null`, then `this.setProp()` is called. The narrowed type is kept and the if condition appears always false to typescript so `param` and `this.prop` are narrowed to `never` inside the `if`

### 🙂 Expected behavior

`setProp()` assigns a string to this.prop so the narrowing to `null` on `this.prop` should be dropped. In fact, any method call should discard the narrowing since anything could happen in the method.

**Comment by floriancargoet** [comment]
For comparison, Flow does discard the narrowing: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFQFNcAXMAb1TDAAcAnOOgLjHIYEsA7AczAA+YbgFcYMMAF5hYmAG4aYMqTIAKOtgbYAtmw49eASiqLaZABadcAOkbMpM8XLCmwqi1dtNWjmIee0gbTAwEqWNnZ0YAh4wppMCMQAJmAARgCeYcRgeLicvNzE2sTcFK4eNrjEZAAK3uqaOv5BwaEW2dzxiAZgVmBJVhiaSckuQe7hXsws+nzNLWAhYADq2RjmxBgA1mHYFBVTUX3ccBRw3DCZ2OxkXHyuE56RLKLi8wuLoatg65s7Fnswk9vL0CCczhdMq8YA8Ds8bndeAJoc0lp0GAkeuZYjwRqNUsQSv1BsNRmNApwoG44SDJHT6I1tMZKEFXLQGlpdAiDO9aGzqZN4bMkSiFEEAL6KSW0Kq1eoAN2wMBExD0tx5JiCNPs0kVyuIYrAkvFQA

**Comment by MartinJohns** [comment]
See #9998.

**Comment by floriancargoet** [comment]
Thank you @MartinJohns
