### ISSUE TITLE
Figure out how to deal with annoying `node:` prefix in auto-imports from @types/node

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#43842]
Nowadays `@types/node` ships with built-ins like `fs` as well as `node:fs`. Accidentally auto-importing these are *extremely* annoying if you're trying to target older versions of Node.js.

We should consider

* inferring the best type of auto-import from your project
* pick the older style of imports one until Node ~16~ 14 becomes the last supported version
* provide an option

CC @andrewbranch @mjbvz

**Comment by andrewbranch** [comment]
Thanks for opening an issue—this has been on my mental to-do list since @uniqueiniquity brought it up. I’m actually surprised we haven’t gotten a flood of complaints about it already 🤔

**Comment by jakebailey** [comment]
I think it's very likely that people just have old versions of the packages installed, predating https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51107.

I know I hit this and it's frustrating, but I'm pretty diligent about updating my stuff regularly.

**Comment by jakebailey** [comment]
And, this may go away in short order with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52595.

**Comment by DanielRosenwasser** [comment]
CC @rbuckton we don't really understand this well enough, and I heard there's some churn going into DefinitelyTyped?

**Comment by andrewbranch** [comment]
#42764 for reference

**Comment by sheetalkamat** [comment]
Also needs handling for ATA: `https://github.com/microsoft/TypeScript/blob/master/src/jsTyping/jsTyping.ts#L32` ?

**Comment by SimonSchick** [comment]
Even if #42764 was fixed we would not be able to use this feature as the typings need to support old versions.

**Comment by SimonSchick** [comment]
No, I'm talking about the fact that node typings lag several TS versions behind for compatibility.

**Comment by karlhorky** [comment]
So looks like the `node:` scheme / prefix was backported to Node.js 14.13.1 / 12.20.0 🎉

https://nodejs.org/api/esm.html -> link "node: Imports" (links with anchors don't scroll properly right now)

<img width="549" alt="Screen Shot 2021-05-30 at 11 04 39" src="https://user-images.githubusercontent.com/1935696/120098640-6104d200-c137-11eb-934d-3174e9e2afcc.png">

**Comment by karlhorky** [comment]
Ah, maybe `require` / CommonJS support is not quite there yet for v14 and v12:

> In Node 16 `require('node:fs')` works, but it looks like it still doesn't in 14.17.0.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52595#issuecomment-851015583

**Comment by karlhorky** [comment]
`@types/node@16.0.0` has been published now - the `node:` schema / prefix now works again:

- https://www.npmjs.com/package/@types/node
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53669

**Comment by Pytal** [comment]
As the `node:` import URL scheme has been backported to `v14.13.1` and `v12.20.0` https://nodejs.org/api/esm.html#esm_node_imports

![image](https://user-images.githubusercontent.com/24800714/129454899-6be84680-c3fe-4555-bbbc-898bedaba929.png)

Will `@types/node` for versions 14 and 12 be updated?

**Comment by SimonSchick** [comment]
I probably won't do it as I prefer working on the bleeding edge stuff, but the process is relatively trivial.

- Add a secondary `declare module` for each module declaration that re-exports everything with the `node:` prefix
- (Optional): Change all internal imports to prefer `node:` prefix.

You can use the current typings as an example or even just copy/paste from there.

**Comment by ExE-Boss** [comment]
> As the `node:` import URL scheme has been backported to `v14.13.1` and `v12.20.0`

That’s only in **ECMAScript Module** `import` statements, not the **CommonJS** `require(…)` function.
