### ISSUE TITLE
TypeScript Should Prioritize Aliased Imports

### ISSUE THREAD

**Issue by dustinlacewell** [microsoft/TypeScript#43849]
When you Alt-Enter on an unimported name, VSCode will offer to add the import if it can. In a monorepo situation, you'll likely have TypeScript aliases pointing to the thing you want to import from. VSCode lists these aliases, which is great, but it also lists the arbitrarily long possible relative import paths. 

I know this is a small request, but VSCode should prioritize the shortest import path / the aliased path with regards to sorting the items in the context menu. That way the aliased import can be added by hitting enter at that context menu. It's a small quality-of-life issue that I run into hundreds of times a day it feels like.

Thanks so much for considering this request.

**Comment by RyanCavanaugh** [comment]
I thought this was already the case, or was at least configurable

**Comment by andrewbranch** [comment]
This should already be the behavior, definitely in 4.3 if not earlier. https://github.com/microsoft/TypeScript/pull/42614 ensured that even same-named aliases of different origin symbols are sorted by number of directory separators. @dustinlacewell can you please use `typescript@next` in your workspace and/or use the [JS/TS nightly extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and then share an example of the issue?

**Comment by dustinlacewell** [comment]
```json
"typescript.preferences.importModuleSpecifier": "non-relative"
```
did the trick, sorry.
