### ISSUE TITLE
`Omit` breaks intersection with an object type with `[key: string]: unknown`

### ISSUE THREAD

**Issue by kohver** [microsoft/TypeScript#43864]
# Bug Report

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsg9gEwIYBsAKAnOYDOUC8UA3gFBRQQAeAxigK4IQKbYBcUAFAJQEB8UANzgBLBAG4yUHHAC2EFmHbc+gkeMkBtANYQQ7HMAzCAdgHMAuuzrGtxuAHdjEgL4kAZterBhcY1ADCsmC+EMbAHGBYuOwA8jLCwAA88MjoUTgANFAARFS0DEwK2bw8pOTUvtIoEAB0KHCmEek1efSMzFHcXGJQAPS9UDEARgBWEF5QwnigkFBwblAA5Na2DsaLkhXGVbX1jZHYODXScgpdfQPDYxNTUDPQ80srdo4briT3sIioCjgATARiJJWgUOmxODx8PwhKIJOQTvIokpIdC1HCoNpdPpDCYLFYbC8nCRXIxaEgMNABOTiBQaG1ClEsjVmXEEgB9FI-dJskHtBRQZzsTlpQ4SDzGLw+PyBGTBYyhYB-JqHdj3R6s4Ac74i3A8umghSlTaVODVOoNZW4Fr6vmdLjdC6DUbjYCTabgB4LZYEtYbcoms17S1HBFne09fpQexwDBaHAAQmJJCAA)

### 💻 Code

```ts
type ModalProps = {
  excludedProp: () => void;
  someProp: () => void;
  [key: string]: unknown;
}
function Component(props: Omit<ModalProps, "excludedProp">) {
  console.log(props.excludedProp()); // Object is type of 'unknown'. This is ok.
  console.log(props.someProp()) // Object is type of 'unknown'. This is unexpected.
}
```

Workaround:
```ts
type ModalProps = {
  excludedProp: () => void;
  someProp: () => void;
  [key: string]: unknown;
}
declare var { excludedProp, ...Omit_ModalProps_excludedProp }: ModalProps;
function Component(props: typeof Omit_ModalProps_excludedProp) {
  console.log(props.excludedProp()); // Object is type of 'unknown'
  console.log(props.someProp()); // works!
}
```

Also, this works:

```ts
type ModalProps = {
  excludedProp: () => void;
  someProp: () => void;
}
function Component(props: Omit<ModalProps, "excludedProp">) {
  console.log(props.excludedProp()); // Object is type of 'unknown'
  console.log(props.someProp()) // works!
}
```

```ts
type ModalProps = {
  someProp: () => void;
  [key: string]: unknown;
}
function Component(props: ModalProps) {
  console.log(props.someProp()) // works!
}
```

### 🙁 Actual behavior

In the first example the `props.someProp` is `unknown`.

### 🙂 Expected behavior

In the first example the `props.someProp` is `() => void`.

**Comment by MartinJohns** [comment]
See #43478 and many others.

**Comment by kohver** [comment]
Thank you for the link. Closing the issue
