### ISSUE TITLE
Shouldn't Array.isArray narrow the type to `unknown[]`?

### ISSUE THREAD

**Issue by Faithfinder** [microsoft/TypeScript#43865]
# lib Update Request

## Configuration Check

My compilation *target* is whatever and my *lib* is `the default`.

## Missing / Incorrect Definition

Array.isArray()

## Sample Code

```ts
function parseUnknown(value: unknown): Whatever {
  if (Array.isArray(value) {
    // value is suddenly `any[]` even though I've only confirmed that it's an array
  }
}
```

I might be missing other usecases, but seems like Array.isArray typing should be smarter than just `is any[]`

**Comment by MartinJohns** [comment]
`Array.isArray` predates `unknown` and this would be a heavy breaking change.

**Comment by Faithfinder** [comment]
I saw these issues before creating this ticket, yeah. Seems like what's wanted there is some really smart behaviour, but I'm just saying that a simple `unknown` suits the function better.

If this is so much of a breaking change, introducing it or not is your call, but my proposal doesn't seem like a duplicate to me, just because it's less than other opened issues.

**Comment by MartinJohns** [comment]
> introducing it or not is your call

Not mine, but the TypeScript teams. :-)

> but my proposal doesn't seem like a duplicate to me, just because it's less than other opened issues.

What matters in terms of duplicates is the underlying issue, not your proposed solution.
