### ISSUE TITLE
Add { property } to import = require

### ISSUE THREAD

**Issue by bwbjustin** [microsoft/TypeScript#43863]
# Suggestion

## 🔍 Search Terms
import, require

## ✅ Viability Checklist
My suggestion meets these guidelines (Sorry if they don't meet these guidelines, idk what these are):

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Like in ECMAScript and CommonJS import syntax, there should be a way to import only a certain property or more.

## 📃 Motivating Example
```
import { config } = require("dotenv");
config();
```

## 💻 Use Cases
To shorten code, and more

**Comment by bwbjustin** [comment]
Sorry if this was a bit rushed

**Comment by maxloh** [comment]
Shouldn't it be `import { config } from "dotenv";`?

**Comment by bwbjustin** [comment]
Yes, it would be that, but what about non-ES6 TypeScript files?

**Comment by RyanCavanaugh** [comment]
Duplicate #18307
