### ISSUE TITLE
Show 'infer function return type' refactoring in quick fix when relevant

### ISSUE THREAD

**Issue by nicoespeon** [microsoft/TypeScript#43875]
# Suggestion

## 🔍 Search Terms

- "infer function return type"
- quick fix

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The 'infer function return type' refactoring was introduced recently. Unfortunately, it generated a lot of noise because the lightbulb would appear whenever the cursor would be inside a function body: https://github.com/microsoft/TypeScript/issues/42993

To solve this, the action provider was filtered at VS Code level: https://github.com/microsoft/vscode/pull/117800

My suggestion is to bring it back to help discoverability. To reduce the noise, I'd suggest to only trigger the lightbulb if:
1. The selection is within the function signature
2. The function doesn't have a return type already (that may already be handled though)

## 📃 Motivating Example

For the context, I'm the author of a VS Code extension that implements automated refactorings for JS & TS. This came up from a suggested feature: https://github.com/nicoespeon/abracadabra/issues/272. Turns out TS provides the feature already and that's awesome.

I can help implementing this change if you think it's something that would be valuable. That would require some coordination with the VS Code repo though cc @mjbvz 

## 💻 Use Cases

How it works today:

![](https://user-images.githubusercontent.com/11138584/116444946-975be280-a855-11eb-888a-8c0eac47428a.gif)

Suggestion would be to bring that in the light bulb 💡, along other action providers. But not from anywhere in the function body to avoid the noise.

**Comment by ackvf** [comment]
I think it's there already, no? (cursor on function name)

![image](https://user-images.githubusercontent.com/2313018/162596729-07640805-ff5f-41f2-852d-b261bede0f3e.png)

**Comment by nicoespeon** [comment]
Indeed, that looks like it has been solved 👍

Closing this issue.
