### ISSUE TITLE
Allow type of index to not match other properties' types

### ISSUE THREAD

**Issue by lazandrei19** [microsoft/TypeScript#43881]
# Suggestion

## 🔍 Search Terms

index signature

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'd like to be able to create a type that has a couple of properties of certain types and then the index type is different.
Example:
```ts
type Ex = {
    foo: string;
    bar: number;
    baz: string[];
    [key: string]: TFoo // This can be anything
};
```

## 💻 Use Cases

My main usecase for this would be a Settings object, where I provide some of the base settings (the hardcoded keys and types) and any other type follows the TSetting type.

**Comment by MartinJohns** [comment]
Just a fair warning, indexer types with known properties already suffer from an unsoundness when reading their known properties.

For example:

	const obj: Ex = {} as any;
	const key: string = 'bar';
	obj[key] = 'a string';

	const val = obj['bar'] // Compile time type is number, runtime type is string

Your suggestion would introduce this unsoundness to accessing properties via indexer as well.

**Comment by RyanCavanaugh** [comment]
Duplicate #17867
