### ISSUE TITLE
Object is possibly 'undefined' after checking property existance

### ISSUE THREAD

**Issue by bmakan** [microsoft/TypeScript#43896]
# Bug Report

I came across multiple similar issues but [this one for reduxjs/toolkit](https://github.com/reduxjs/redux-toolkit/issues/868) fits my issue the most accurately. I simplified the code example.

Most "solutions" suggest I use "!" to ignore the error/warning. This feels like "cheating" by ignoring the problem.

A simple workaround provided as well.

- Is this intended behavior? Why?
- Is this a limitation in the Typescript? If so, given the numerous complains, can we add it to the "known not-issues"?

### 🔎 Search Terms

* Object is possibly 'undefined'
* Object is possibly 'undefined' type guard
* Object is possibly 'undefined' after condition
* Redux reducer Object is possibly 'undefined'

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "undefined".

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/C4TwDgpgBAqgzhATlAvFA3gKCjqA7AQwFsIAuKOYRASzwHMAabXAus-AVyICMkmBfTJlCQoAZWAFg0NFlxQOCRHHIAlCAGMA9ogAmAHko16DWEqgAfBXl0QAZrQi6AfAKF2OeDcGpa8UJ2pgADliCAAKSil2CWjTXSkCcnQFal1yI1pGfDCMqiyofgBKDGYcbTxKDBySUw40wtQoBMkAbiF5ajsoSMlpADpFJDgAbXrdAF0SuXlcKIGh5TG0if7CEib1iHb5QTKoCqrFpvmIQaVR8Ymd3C6exen9+UW1sM2wm5xBQSA)

### 💻 Code

```ts
type User = {
    name: string,
    age: number,
}

type State = {
    users: Record<string, User | undefined>,
}

function editName(state: State, data: { uid: string, name: string }) {
    const { name, uid } = data;

    if (state.users[uid]) {
        // Object is possibly 'undefined'.(2532)
        state.users[uid].name = name;
    }

    const user = state.users[uid];
    if (user) {
        // Works fine
        user.name = name;
    }
}

```

### 🙁 Actual behavior

I check for existance of a property and then proceed to use it. Typescript throws error it's possibly undefined.

### 🙂 Expected behavior

After checking for the property existance it cannot be undefined and Typescript should recognize it.

**Comment by MartinJohns** [comment]
Duplicate #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by bmakan** [comment]
You're right, it seems to be caused by the issue described in there. Considering it's been years and still no progress on it, I guess I'll just have to use the workaround.
