### ISSUE TITLE
TS Project build meta-output .tsbuildinfo emitted outside of outDir

### ISSUE THREAD

**Issue by michkot** [microsoft/TypeScript#43908]
# Bug Report

### 🔎 Search Terms
project build output directory 
tsbuildinfo

### 🕗 Version & Regression Information
4.2.4
4.3.0-dev.20210430

### ⏯ Playground Link

N/A - problem with project builds

### 💻 Code

Important bits of tsconfig files, all repository code is rooted at `/drive-c/work/c`:
```jsonc
// /drive-c/work/c/d/e/f/tsconfig.base.json
      "outDir": "build/tmp/", 
      "composite": true,

// /drive-c/work/c/d/e/f/tests/tsconfig.json - base case a)
  "extends": "../tsconfig.base.json",
    "rootDir": "../../../../i/j/k/l/",
    //"outDir" not specified
  "include": [
    "../../../../i/j/k/l/**/*",
  ],
// /drive-c/work/c/d/e/f/tests/tsconfig.json - case b)
    "outDir": "../build/tmp/tests/", 
// /drive-c/work/c/d/e/f/tests/tsconfig.json - case c)
    "outDir": "../build/tmp/tests/tests2/tests3/", 
// /drive-c/work/c/d/e/f/tests/tsconfig.json - case d)
    "outDir": "../../../build/tmp", 
```

### 🙁 Actual behavior
In case a) the file tsconfig.tsbuildinfo is emitted into
`/drive-c/work/c/d/`**`d/e/f/tests/tsconfig.tsbuildinfo`**

In case b) the file tsconfig.tsbuildinfo is emitted into
`/drive-c/work/c/d/e/`**`d/e/f/tests/tsconfig.tsbuildinfo`**

In case c) the file tsconfig.tsbuildinfo is emitted into
`/drive-c/work/c/d/e/f/build/`**`d/e/f/tests/tsconfig.tsbuildinfo`**

In case c) the file tsconfig.tsbuildinfo is emitted into
`/drive-c/work/`**`d/e/f/tests/tsconfig.tsbuildinfo`**

All these emit locations are wrong, are polluting my repository, and in case d) tsc emits files completely out of repository tree.

### 🙂 Expected behavior

In all the cases, tsconfig.tsbuildinfo is placed under $outDir/$name-of-project/$name-of-tsconfig.tsbuildinfo (or similar location under $outDir); in my case a):
`/drive-c/work/c/d/e/f/build/tmp/`**`tests/tsconfig.tsbuildinfo`**

### Notes:
I have various requirements that force me to structure TS projects irrelevant of actual code organization. One of them being that it is not possible to have hand-written .d.ts files become part of (project) compilation output, something that's scattered over multiple issues here: https://github.com/microsoft/TypeScript/issues/35296 https://github.com/microsoft/TypeScript/issues/39231 https://github.com/microsoft/TypeScript/issues/38146

**Comment by sheetalkamat** [comment]
We need clear repro with project structure (including source file structure) showing the issue since the complete structure of project matters when determining where the tsbuildinfo goes.

**Comment by michkot** [comment]
> We need clear repro with project structure (including source file structure) showing the issue since the complete structure of project matters when determining where the tsbuildinfo goes.

@sheetalkamat Here it is, I have created a minimal dummy project for reproduction of the behaviour I described above! 😃
[reproducible-example.zip](https://github.com/microsoft/TypeScript/files/6416472/reproducible-example.zip)

**Comment by andrewbranch** [comment]
It looks like this was done intentionally, at least to some degree, [here](https://github.com/microsoft/TypeScript/commit/d53efdf38058e37d52e794b6650689294e69b185#diff-537414476d7c7a690310c5e1e5d6a0bbbfba37c5b05126edee32fdea7e3a09d8R68)—it’s even mentioned in the commit message:

> if rootDir and outDir then outdir/relativePathOfConfigFromRootDir/configname.tsbuildinfo

Here’s a simplified repro:

```ts
// @Filename: /configs/a/tsconfig.json
{
  "compilerOptions": {
    "composite": true,
    "rootDir": "../../sources",
    "outDir": "out"
  },
  "include": ["../../sources"],
}

// @Filename: /sources/index.ts
export {}
```

The `outDir` is `/configs/a/out`, and that’s where `index.js` and `index.d.ts` get written. But using the formula for the .tsbuildinfo path, `{outDir}/{relativePathOfConfigDirectoryFromRootDir}/{configBasename}.tsbuildinfo`, we have

* `outDir` = `/configs/a/out`
* `relativePathOfConfigDirectoryFromRootDir ` = `../configs/a`
* `configBasename` = `tsconfig`

so the result is `/configs/a/out/../configs/a/tsconfig.tsbuildinfo`, which resolves to `/configs/a/configs/a/tsconfig.tsbuildinfo`.

I’m guessing there is a general assumption that the relative path of a config file from its `rootDir` is always either straight up (`../tsconfig.json`) or straight down (`./project-a/tsconfig.json`). But I’m not sure exactly what the motivation is to not just put the .tsbuildinfo file in the outDir all the time—@sheetalkamat?

**Comment by sheetalkamat** [comment]
Always writing to outDir could cause issues with overwriting tsbuildinfo if two projects use same `outDir` and different `rootDir` structure to adjust where things go.. So it follows the logic similar to how output structure is computed and i think that is more sound.

**Comment by michkot** [comment]
Thanks for the investigation @sheetalkamat @andrewbranch, but let me strongly disagree on this being closed.

- the current default behavior goes against the current documentation ("TSConfig Reference"): 
- https://www.typescriptlang.org/tsconfig#tsBuildInfoFile (+ the default is described as ".tsbuildinfo" which is also weird)
> This option offers a way to configure the place where TypeScript keeps track of the files it stores on the disk to indicate a project’s build state — by default, **they are in the same folder as your emitted JavaScript**. 
- https://www.typescriptlang.org/tsconfig#incremental
> This creates a series of .tsbuildinfo files in the same folder as your compilation output.
- the current default can pollute unrelated/unexpected folders with build output and makes change-monitoring (build systems) and cleanup of build outputs un-intuitive / error-prone
- I'd even call the current behavior a consistency/security problem! The tsbuildinfo being not only emitted but also **read** out of the defined source / outDir directory tree means that TSC might read stuff that I do not control! Definitely not something I would call "more sound" :/ 

I would suggest that the right "sound" approach would be one/multiple of:
- warn the user to set tsbuildinfo parameter when using incremental/composite switches in order to prevent his behaviour
- adjust the docs and explain the choose-destination algorithm there (there = composte/incremental/tsBuildInfoFile) 
- by default, generate the tsconfig into outDir (or next to config when outDir=default) and emit and error if it would be overwritten be an unrelated project output (very breaking?)
- keep the behavior as is, except when the tsbuildinfo would be generated outside of outDir - then issue an error (not so breaking, bot not nice either -> user might be surprised about weird directory structure being generated under the outDir)

**Comment by sheetalkamat** [comment]
We already error if tsbuildinfo will be overwritten on tsbuildinfo from referenced projects but the main problem is not all projects might be referenced so its hard to find it out and will depend on how and what you configure. So changing behavior seems unlikely without breaking world. 
Also in most setups the tsbuildinfo goes into `outDir` or next to tsconfig if outDir is not specified unless you configure the options to deteremine your source tree like `rootDir`. So at that point this custom information does affect where tsbuildinfo will be. 
As you suggested, we can give better insight as part of documentation here but i am afraid there isnt much from changing location perspective we can do.

cc: @orta who documents these things and very good at writing these kind of helpers.

**Comment by michkot** [comment]
@sheetalkamat / @orta The docs still say "by default, they are in the same folder as your emitted JavaScript." which is simply not true as we saw in this issue-thread. Any chance getting that fixed?
https://www.typescriptlang.org/tsconfig#tsBuildInfoFile
