### ISSUE TITLE
WeakMapConstructor: readonly iterable elements

### ISSUE THREAD

**Issue by mfulton26** [microsoft/TypeScript#43900]
https://github.com/microsoft/TypeScript/blob/d16790e3cc6a3b65274ffcd857d0163ce6397ebf/src/lib/es2015.iterable.d.ts#L146

like `MapConstructor`, `WeakMapConstructor` should support receiving `Iterable<readonly [K, V]>` instead of `Iterable<[K, V]>`; otherwise tuples created with `as const`, etc. cannot be safely passed in without casts:

```ts
new WeakMap([[{}, false] as const]);
// The type 'readonly [{}, false]' is 'readonly' and cannot be assigned to the mutable type '[{}, false]'.
```

**Comment by RyanCavanaugh** [comment]
Whoever takes this up, please check for other tuple declarations that should be marked readonly

**Comment by mfulton26** [comment]
I've reviewed all matches of `/(?<!readonly )\[[^\]]*,.[^\]]*\]/` in `src/**/*.d.ts` files and the only tuple I find that is received as an argument that isn't already marked `readonly` is this `WeakMapConstructor` one. Some tuples in return types should possibly be marked `readonly` but I don't think so (most objects returns in built-in Web APIs seems to be mutable).
