### ISSUE TITLE
problem with override and static fields in ts4.3 beta

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#43916]
# Bug Report

If I do not add override on static, I get an error "This member must have an override...."

If I add it, I get the error "'static'modifier can not be used with override"

### 🔎 Search Terms
override static 

### 🕗 Version & Regression Information

This is a new feature, so before override was not available

### ⏯ Playground Link

I've none

### 💻 Code

    static readonly style = css`
        :host {
      .....

### 🙁 Actual behavior

see:

![image](https://user-images.githubusercontent.com/364896/116775094-399be600-aa61-11eb-9d79-5b12305c019d.png)

![image](https://user-images.githubusercontent.com/364896/116775102-47516b80-aa61-11eb-94ac-73996c5e588a.png)

### 🙂 Expected behavior

should work after adding override

**Comment by jogibear9988** [comment]
![image](https://user-images.githubusercontent.com/364896/116775148-97c8c900-aa61-11eb-931a-d32afb4e052d.png)

**Comment by whzx5byb** [comment]
It is fixed in the nightly version.

**Comment by Kingwl** [comment]
Fixed via #43569. Please try the typescript@next.

**Comment by jogibear9988** [comment]
fixed
thx
