### ISSUE TITLE
Utility Type - PartialRecord

### ISSUE THREAD

**Issue by tylerjlawson** [microsoft/TypeScript#43918]
# Suggestion

I believe it would be useful to have a type `PartialRecord`. This [SO Post](https://stackoverflow.com/questions/53276792/define-a-list-of-optional-keys-for-typescript-record) has had 13k+ views so I believe this is a commonly desired type.

## 🔍 Search Terms

PartialRecord, Partial Record

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

New Utility Type: `PartialRecord`

```ts
type PartialRecord<K extends keyof any, T> =  Partial<Record<K, T>>;
```
or
```ts
type PartialRecord<K extends keyof any, T> = {
  [P in K]?: T;
};
```
(from SO Post linked above)

## 📃 Motivating Example

This improves the basic support of Typescripts Utility types by adding support for a commonly desired pattern.

## 💻 Use Cases

I want to use this for conveniently defining Partial Record types without needing to maintain and import one in each project I need this pattern. 

Current workaround is to define your own, but this is obviously not ideal.

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.
