### ISSUE TITLE
Adding 1 or more varargs causes incorrect inference of function's return type

### ISSUE THREAD

**Issue by panta82** [microsoft/TypeScript#43919]
# Bug Report

### 🔎 Search Terms

`vararg`, `generic`, `rest`

### 🕗 Version & Regression Information

- I experienced this  on my current project version (4.1.3), and reproduced on 4.3.0-beta, on the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strictNullChecks=false&ts=4.3.0-beta#code/JYOwLgpgTgZghgYwgAgJICUIGcCuAbMAITixQG84AuZLMKUAcwBpkAjakHAW1egF8A3ACghoSLEQoAYojAB7KAE8APABUAglAZZkEAB6QQAEx1wQigNoBdAHzIyQ5Lr0QEOSAAoAdD7has1Br+AJTUAG5ywEbCfCIwOCAIYMByIMgIUBBwkDJJCipB2s6GJshmllYsqpi4BMUQxjoY2PhEJBA2HmQMDdDZECwADvTgfNQOTj0gfZDU3r7+gZrawcgAvHbVLQRMjsjDYnOZtWCBNa2rG8gRUbGhyLnySmrLWHYTyJlgOFBpH076VzuCDzLx+Fb2PZOJwIVK0T7bMDrZBTGYgnxgkLCaHQg7gDzHC7Y6GxJyCISxIQZLI5WT5Lp7VFQfpzS52LrIAD0nOQygAtHzkDhSMgQHJkEZFCA4FxgAh9n4ZVgoWVqABydRq3Y49jIACMACYAMza6EIdUAYTVXJ5-MFcCMRjKoogAHd9lA5INoGBFMgABbQCB7PjBU1404Ik7rOywkBYOR4CBePByBgExFgliEgheVjZzMIVY23kC5Bgf3AHSuhQAa2Voa8gLcnmCwipmX6j3pHyZLOQHjgbIHZBLdqFIr1EqlMrlCuZXBVcFNTl1hpNKvNyDVVrHZYdTrgLvdwy9Pr9gcyIbDewj1BzSKucYTSZTaYzJyzUdaeYLn6Le6ChWVZsJ29YsGYTrAEiWD+nI+BGCAapgBSwRNi4LYghqaptkAA)

### 💻 Code

```ts
interface IResultBase {a: string, b: number};

interface Factory<TArgs extends any[]> {
  execute(...args: TArgs): void;
}

function createFactory<TArgs extends any[], TResult extends IResultBase>({generate, print}: {
  generate: (...args: TArgs) => TResult,
  print: (result: TResult) => void}
): Factory<TArgs> {
  return {
    execute(...args) {
      const result = generate(...args);
      print(result);
    }
  };
}

createFactory({
  generate: () => ({ // <-- use no dynamic params
    a: 'A',
    b: 123,
    c: 'C' // <-- add a new property here
  }),
  print: result => console.log(result.a, result.b, result.c)  // <-- this works
}).execute();

createFactory({
  generate: (a) => ({ // <-- use 1 dynamic param
    a,
    b: 123,
    c: 'C' // <-- add a new property here
  }),
  print: result => console.log(result.a, result.b, result.c) // <-- this breaks, and it shouldn't
}).execute('A');
```

### 🙁 Actual behavior

When calling `createFactory` with `generate` method that has 1 or more varargs, returned type is treated as `IResultBase`, instead of the actual returned type from the varargs function (which should be `{a: string, b: number, c: string}`).

Therefore, the compiler reports error `Property 'c' does not exist on type 'IResultBase'`.

### 🙂 Expected behavior

The returned type from `generate()` should always be inferred correctly, regardless of how many varargs it takes.

**Comment by RyanCavanaugh** [comment]
Context-sensitive positions like that can't be used to generate inference candidates; this is generally not a problem since if the parameter is truly used, it's in a contravariant position that wouldn't work well anyway. We'd need unification to infer this pattern correctly; see #30134.
