### ISSUE TITLE
Cannot specify the type of an expression involving a Class returned from a function

### ISSUE THREAD

**Issue by ssledorze** [microsoft/TypeScript#43923]
# Bug Report

### 🔎 Search Terms

path dependent, untypable, nested class type, nested class reference

### 🕗 Version & Regression Information

No version known which works correctly

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=0&ts=4.2.3#code/MYewdgzgLgBAjjAvDAPAFQHwAoAeAuGNASiQwCgYZgAbAQwghgGEYBvCymAWyRhw8qhIUAE4BXYFBAisJVgF8OiskOjxavMAFMA7jCxwsAIgBMRokVkwA9NZhQAngActMAJYQCcFNBFuwAOYYAHRMKuBqcABGXj6i-kGhmrr6hqbmliS2MACiIiLSZGTZAHIgUK5QABa0sNUe7oy01BAgMLRgjRBirjpu1TBg4DBOINQOXNJOVW7AVCAAJlpFqrAA1rxWiOSCdAzMbALzwuKS0lYKSisR6xrI2npYa7KZNnaOLo0EYaswazEHe4pJ4vKzZPIFERFIA

### 💻 Code

```ts
const q = <T>(x: T) =>
  class C {
    m = x
    constructor() {}
  }

const qa = new (q("2"))() // type is: q<string>.C
const qb: q<string>.C = new (q("2"))() // Error

// Note that this is also an issue with non polymorphic code

const k = () =>
  class C {
    constructor() {}
  }

const ka = new (k())() // type is: C
const kb: C = new (k())() // Error
```

### 🙁 Actual behavior

I can't explicitly type the expressions

### 🙂 Expected behavior

I would expect to be able to type this expression.
Ideally using the signature inferred by the compiler

**Comment by naorzr** [comment]
It's possible to infer the type by doing

```
const ka = new (k())() // type is: C
const kb: InstanceType<typeof ka> = new (k())() 
```

**Comment by whzx5byb** [comment]
For non-polymorphic version:
```
const kb: InstanceType<ReturnType<typeof k>> = new (k())();
```

Unfortunately it doesn't work in the polymorphic version, because ts doesn't support [Generic Values](https://github.com/microsoft/TypeScript/issues/17574).
There are some workarounds in https://stackoverflow.com/a/59072991/3016883 and https://stackoverflow.com/a/62724646/3016883

**Comment by RyanCavanaugh** [comment]
`const` doesn't create a new type; this is the intended behavior. There are many ways to refer to this type depending on what you want to do with it.

**Comment by ssledorze** [comment]
@RyanCavanaugh thanks for having taken the time to review this issue;
are all the ways to refer to this type enumerated above or do you know others? (or know where I can find others)
Thanks again!
