### ISSUE TITLE
Incorrect optimization for keyof Mapped type

### ISSUE THREAD

**Issue by markw65** [microsoft/TypeScript#43920]
I have this Mapped type which creates a type with just those fields of T that are extended by B. It seems to work.

```type FieldsExtendedBy<T,B> = {[K in keyof T as (B extends T[K] ? K :never)] : T[K]};```

But this one, to extract the keys of those fields, doesn't:

```type KeysExtendedByFails<T,B> = keyof {[K in keyof T as (B extends T[K] ? K :never)] : T[K]};```

KeysExtendedByFails always includes all or none of the keys of the original T. I've setup a playground [here](https://www.typescriptlang.org/play?ts=4.2.3#code/LAKALgngDgpgBAMQJYwDYBMDOBRAHmGAO3RnQCEIAeAFQBoyA+OAXjgG8BtAaTiULgDWMCAHsAZnGpwAhpjgAKMnBj4iWSdwC6cAPxweALkIwAbjABOASm0GNXTQF8A3KFCRY+4TlXFSFAOoi5gKYNPRMrEKiEpw8fILC4pIycvLUWso+6gCuhAKEIgDu-HqKmQTEcun2uvpwRqYWlrbGZlY2do4u4NDwXF54FSTkEAjSSKihdIwsCdHs3Lz8UUlSsgpKKkNVGXqGrU0d1V2uIHwE5mLSAMbwAILscLj1cITZALYARhZOcA6g5wsV1ucCUbDgEBemDA5j4AHNfv8zoQLsD4ABhcpqORguAALx0tk+IhEqBg0kIiNOgMuN3gAFlHtJbHdfp8XmRftcXpikaAxLlrmAkCJ+HCSeh5NlbP0IN4hn4IIFgqF6bRQQxLFCYfD2KA4HBzDAwNlzPxst0kQLCEKRfxPtJJdLPHLBmpFWMJqr1YwtbZobDCHC9SADUaTWa4BbQHyQAB6ONwMAACyQclF8CuXrgorg70hfGh0lQqGkwtzSQALAA6ABM1YAzOrPtkwHBCkEQksk8n4FBSxA4eYRLl0PzBeX+B2VQB9Pgz-vSQfD0dS2wrCTINBYN2+EaUNW+7WB4NsfWG42m82W07W2256chGcUiCFJdrxAoDDy937w+al5cnyIp+DPUMLwja8Y1vCc7TgB1zHkLVwXPcMrzgDhzwNcURElAAiaQ8MsdUEzgLNJhSTJYCFUhq1BOB0BEGA5AKNstjUOA7iwuAcPwz4iNobjePkPDrgE7iHXwwjiLgUjchUaiCHQVBIUfTA6KURjmNeEQ2KyTiJMdET+OIwz8LE0zwINNS50IBcByHEdiBE6SSMTa4giNIUVLI8YKPiRdlyc9Bm1bHS2zEII83gQokBTOAa3rBtuJs+dAsc1c8JMwSrPbTtMFs+ylwy5zRPE8DNBvEBxxtSd4OkPEkJDMNL0jTDcpsl83wgeQ2GZNhcAMStawcWhPgMNgIAMLKGrw0brgmvEDBhbIYFoKaZvMOaHBk0jyLkdYFJgGj0A0himJY3SsWIAyOvy59CFfd8+omwbhocHa3N87NDtwRTaLgek00wXV2QpdA4GudVwbgVA4osYs4EwZMRwwcK4GTaQzBkFL7q657xsm6aHTxObaAWtglpWtaNoQ7bdsTNTz00GMgA), and hovering over the use of KeysExtendedByFails in the function bad in the playground example shows the definition has been incorrectly transformed to:

```type KeysExtendedByFails<T, B> = B extends T[keyof T] ? keyof T : never```

which is obviously wrong.

I have another definition, 

```type KeysExtendedByWorks<T,B> = keyof {[K in keyof T as (T[K] extends unknown ? (B extends T[K] ? K :never): never)] : T[K]};```

which works - although `T[K] extends unknown` is pretty much a no op.

Also applying keyof to FieldsExtendedBy seems to work in the playground (versions 4.1.5 and later), but fails for me with 4.2.3. I assume there's a setting which is affecting whether it works or not.

**Comment by RyanCavanaugh** [comment]
This issues the same errors in the commandline as it does in the Playground for me.

I'm not sure about "obviously wrong" here? Is the bug that the definition isn't what you expect (please clarify), or that you're not getting the same errors in the playground?

**Comment by markw65** [comment]
Thanks for looking.

The "obviously wrong" comment was referring to `keyof {[K in keyof T as (B extends T[K] ? K :never)] : T[K]}` being "optimized" to `B extends T[keyof T] ? keyof T : never` - which seems to be what's going on, based on hovering over `KeysExtendedByFails` in the definition of `bad`, and on the behavior of `KeysExtendedByFails` (and its obviously wrong because the latter type always has all the keys of T, or selects `never`, while the former could select (almost) any subset, but can *never* produce `never`).

It also seems obviously wrong that `KeysExtendedByFails` behaves differently from `keyof FieldsExtendedBy` (and that it behaves differently from `KeysExtendedByWorks` for that matter, since `T[K]` always extends `unknown`)

Also, the fact that `bad` accepts all three keys of M, when only two of them *should* be accepted (since FieldsExtendedBy<M,B> only has fields `b` and `c`) seems wrong to me.

So to be as clear as possible: `bad` should not accept the key `'a'`, since its not a member of the underlying mapped type that keyof is being applied to.

Finally, yes, you're right, if I compile the playground example from the cli, it behaves exactly the same as the playground (ie `KeysExtendedByFails` gives incorrect results, `KeysExtendedByWorks` gives correct results, and `keyof FieldsExtendedBy` also gives correct results.

However, if I plug those definitions into my full project, `KeysExtendedByFails` gives incorrect results, `keyof FieldsExtendedBy` also gives (the same) incorrect results, and `KeysExtendedByWorks` gives correct results (but `FieldsExtendedBy` *not* qualified by `keyof` creates a mapped type with the correct fields). I've not yet managed to produce a cut down example that behaves that way in the playground.

**Comment by markw65** [comment]
I've found the problem code:

```
        // Ordinarily we reduce a keyof M, where M is a mapped type { [P in K as N<P>]: X }, to simply N<K>. This however presumes
        // that N distributes over union types, i.e. that N<A | B | C> is equivalent to N<A> | N<B> | N<C>. That presumption may not
        // be true when N is a non-distributive conditional type or an instantiable type with a non-distributive conditional type as
        // a constituent. In those cases, we cannot reduce keyof M and need to preserve it as is.
        function maybeNonDistributiveNameType(type: Type | undefined): boolean {
            return !!(type && (
                type.flags & TypeFlags.Conditional && (!(<ConditionalType>type).root.isDistributive || maybeNonDistributiveNameType((<ConditionalType>type).checkType)) ||
                type.flags & (TypeFlags.UnionOrIntersection | TypeFlags.TemplateLiteral) && some((<UnionOrIntersectionType | TemplateLiteralType>type).types, maybeNonDistributiveNameType) ||
                type.flags & (TypeFlags.Index | TypeFlags.StringMapping) && maybeNonDistributiveNameType((<IndexType | StringMappingType>type).type) ||
                type.flags & TypeFlags.IndexedAccess && maybeNonDistributiveNameType((<IndexedAccessType>type).indexType) ||
                type.flags & TypeFlags.Substitution && maybeNonDistributiveNameType((<SubstitutionType>type).substitute)));
        }
```

In this case, `N` is `B extends T[K] ? K : never`, and it clearly doesn't distribute over union types. But `maybeNonDistributiveNameType` returns false because `type.root.isDistributive` is true (its true whenever the checked type is a template parameter, and `B` is one), and then maybeNonDistributiveNameType((<ConditionalType>type).checkType)) is also false, since its just looking at `B` again.

This explains why my workaround works: In the workaround, we have `T[K] extends unknown ? ...`, and so `type.root.isDistributive` is false.

I'd never looked at the typescript source before yesterday, so its not really clear to me what the correct fix is; but it seems like it must *at least* involve checking `type.extendsType` in addition to `type.checkType`. Perhaps `root.isDistributive` should only be true if *both* `type.checkType` and `type.extendsType` are template parameters - but maybe that misses valid cases too; or maybe there are other uses of isDistributive that really don't care about the `extendsType` - in which case the fix should be in `maybeNonDistributiveNameType` itself.

**Comment by markw65** [comment]
One more observation... the fix has to *also* include checking the `true` and `false` types (presumably via additional recursive calls in `maybeNonDistributiveNameType`. Consider:

```
type KeysExtendedBy<T,B,P1,P2> = keyof {[K in keyof T as P1 extends P2 ? (B extends T[K] ? K : never) : never] : T[K]};
```

Now both `checkType` and `extendsType` are template parameters, but N *still* doesn't distribute over unions (at least, in the case where P1 extends P2).

**Comment by markw65** [comment]
And [here's](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAYglhANgEwM4FEAewIDtkTIBCIAPACoA0URAfFALxQDeAsAFBRQDaA0lHFxQA1hBAB7AGZRyUAIaoaUCNjxoZfALpQA-FH4AuKLggA3CACdNR8loDcHAL4P2HQTguS5AY2gBBFg4uTCNcAFcAWwAjSxdHN1wPL18lNk4oECNUYAtBAHM4hKSfaABhZVV8RSJA9IAvHSMo8XFECDlcQtd2d0tk6ABZWq45Iz8XLiijIgmobyNSro5vRAVFGBaKajphqCi5ZAAKMJCRMSlYBBQMSoJiMioaWgBKXa4LCGAwiyET2fj2ACOJIwrhvMA4OIhPsLIdXmkuN4odkoJIWoxjBAAO6wTYDSh0OGzD5fH48IJcVEtAB0+yOACI5PTntQAPSsqCglSQcGERAgKBY8QWYSoalKZDiCCKXDiYAVHD4KB+ClcNHiWkHQ70qLMyiqqkauna7x6imaLpAA) a new playground example that shows `keyof FieldsExtendedBy` failing.

In the original example, the `B` in `B extends T[K]` was no longer a type parameter by the time maybeNonDistributiveNameType was called (it was the actual class named B), and so `type.root.isDistributed` was false, and everything worked. By wrapping `bad` in a parameterized class, we can make it fail the exact same was as KeysExtendedByFails.

Again, wrapping the conditional in `T[K] extends unknown ? ... : never` (a no op) fixes it.

**Comment by markw65** [comment]
[Here's my stab at a fix](https://github.com/microsoft/TypeScript/commit/7c775d33ffbc7ac14402fe7a21cae9fb3bf2dbaa)

If this looks like its on the right track I'm happy to add test cases and turn it into a pull request.

**Comment by markw65** [comment]
The proposed fix is definitely insufficient, and there are other problems related to isDistributive, which I've detailed in #44019.

Closing this in favor of #44019
