### ISSUE TITLE
Possible 4.3 regression with generic function and rest in object destructuring 

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#43941]
# Bug Report

### 🕗 Version & Regression Information

- This changed between versions 4.2 and 4.3 beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/C4TwDgpgBACghgJzgWwM5QLxQN4CgoFQBmA9iQFxSrAICWAdgOYDcuAvlAGRQAU2UwOI0oByOCOYDwESvQCuyAEYQEUDgB8cAoaMUSpkStTpM1ASla4AxiXrUojCMAAq0zFAA8MKBAAewCHoAE3R4JDQAPh4wRBRUShgzTAicfEIbO2BUwhyoAHo8qAB5ZFpgNNziMgAaXArcgDomhAhqeo4sGPDUSxyW4DkEeigW6lY2SyCIKwAbRGgM+y64hNi0S1QAdzKrAAteZbQGwUYkvByrOFRoMRFKc8r8wucAZSgAFgaAJlkFZQR6jkClBXh8GgBmIw0BiMKCaeRKFSA9K2eyjOQzLJYRwuaTRNaoMzHaS9R6KFpwADWrBybHql2uUBEenuyIIwNBnx+VGhTDZTxBb0+kJ5Jlh8L+SMeUEWWXRmPcONckHx3SJoEgpMq5IgVJphDpdKAA)

### 💻 Code

```ts
type Params = {
    foo: string;
} & ({ tag: 'a'; type: number } | { tag: 'b'; type: string });

const getType = <P extends Params>(params: P) => {
    const {
        // Omit
        foo,

        ...rest
    } = params;

    return rest;
};

declare const params: Params;

switch (params.tag) {
    case 'a': {
        // TS 4.2: number
        // TS 4.3: string | number
        const result = getType(params).type;

        break;
    }
    case 'b': {
        // TS 4.2: string
        // TS 4.3: string | number
        const result = getType(params).type;

        break;
    }
}
```

### 🙁 Actual behavior

4.3 behaviour should match 4.2 behaviour. See comments in code.

### 🙂 Expected behavior

See comments in code.

**Comment by OliverJAsh** [comment]
This is marked as fixed but the behaviour still differs from 4.2. Is that expected?

**Comment by OliverJAsh** [comment]
@weswigham Not sure this issue has been fixed, should we re-open it?

**Comment by weswigham** [comment]
It definitely looks fixed in the nightly playground... and in the associated PR's tests...

**Comment by OliverJAsh** [comment]
I had a look at the tests but I couldn't understand what behaviour they were trying to verify. Do we expect my example to behave the same in 4.3 as it did in 4.2, or is this an intended change?

**Comment by weswigham** [comment]
I see the behavior match what you noted as the 4.2 behavior in the nightly playground?

**Comment by OliverJAsh** [comment]
Yes you're right, sorry!
