### ISSUE TITLE
class static variables and functions access with self

### ISSUE THREAD

**Issue by laaneoks** [microsoft/TypeScript#43952]
# Suggestion

If I have static class variables, then I need to use class_name.variable_name
But:
1. I want to change the class name, then it can be problematic
2. Maybe my class name is quite long, then it is uncomfortable

Can TypeScript add a special word "self" that can use with static variables and functions? Conversion to JavaScript should be simple.

## 🔍 Search Terms
class
static
self

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code - NO
* [ ] This wouldn't change the runtime behavior of existing JavaScript code - NO
* [ ] This could be implemented without emitting different JS based on the types of the expressions - NO
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.) - NO
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). - YES

## ⭐ Suggestion

TypeScript can replace "self" with the name of a class

## 📃 Motivating Example

```javascript
class MinuKlassOnIkkaKirjeldavEtOleksHea{
	static muutuja: string;

	static init(nimi: string){
		MinuKlassOnIkkaKirjeldavEtOleksHea.muutuja = nimi + ".";
		//The new syntax:
		//self.muutuja = nimi + ".";
	}
}
```

## 💻 Use Cases

Shorter TypeScript code and no problems on changing the name of the class

**Comment by whzx5byb** [comment]
You can use `this`

**Comment by MartinJohns** [comment]
> I want to change the class name, then it can be problematic

I don't see how this would be problematic, given the tooling support and refactoring capabilities nowadays.

> Maybe my class name is quite long, then it is uncomfortable

Then create an alias.

    const self = MinuKlassOnIkkaKirjeldavEtOleksHea;
    self.muutuja = nimi + ".";

**Comment by RyanCavanaugh** [comment]
> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

We don't add suggestions that don't meet this criterion.

**Comment by laaneoks** [comment]
Thank you for "this".
 This is a better example need for "self":

```javascript
class MinuKlassOnIkkaKirjeldavEtOleksHea{
	static muutuja: string;

	static arvuta(){
		//Do something there
	}
	static init_DOM(){
		//Some DOM manipulating
	}


	static init(nimi: string){
		$("#teeSeda").on("click", function(){
			MinuKlassOnIkkaKirjeldavEtOleksHea.arvuta();	//can't use this
			//The new syntax:
			//self.arvuta();
		});


		$(function(){
			MinuKlassOnIkkaKirjeldavEtOleksHea.init_DOM();	//can't use "this"
			//The new syntax:
			//self.init_DOM();
		}
	}
}
```

**Comment by whzx5byb** [comment]
> ```js
> $("#teeSeda").on("click", function(){
> 			MinuKlassOnIkkaKirjeldavEtOleksHea.arvuta();	//can't use this
> 			//The new syntax:
> 			//self.arvuta();
> 		});
> ```

A better practice is to use arrow function.
```ts
$("#teeSeda").on("click", () => {
  this.arvuta();
});
```
