### ISSUE TITLE
Implementing an interface with only optional types results in "Type X has no properties in common with type Y.(2559)"

### ISSUE THREAD

**Issue by Ayc0** [microsoft/TypeScript#43951]
# Bug Report

When implementing an interface with only **optional** attributes, and using it as a base for a class with `class Class extends Interface`, if the class defines additional attributes but not from the ones from the interface (which should be possible as the interface only has optional), TypeScript is not happy with the declaration of the class and throws the error `Type 'X' has no properties in common with type 'Y'.(2559)`.

It also throws the same error when we try to use the instance of the class in a function that expects the initial interface.

### 🔎 Search Terms

- `is:open label:Bug 2559`
- `is:open label:Bug no properties in common with type`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (even the nightly), and I reviewed the FAQ for entries about the type system and classes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnIwD2RA-ABQCUAXMgG5HAAmA3LgL666iSyIoBlCAiIgmyPAQJwmTcgCNMEWuiw16jJhy64A9LuSBQclwIANpgzIAwkShRhYAKIBbAA5gAnsmBvTEZxDglqo4+FIiIBhgUACuCGC2CrRCEUyUEmFSUvIAdDJyYAAWwBiUbFmcnHoGgDLkyPIxYMgYhUQxpuLyKMZmFsgAkiAidg4A6sBFVjFRRM7evv6BYMFKGVmuUMB0cJD1cFC0IDHOXVDl4aJRsfGJ8tQpomlrWVJFJTmKUMgAvMgAjOcXvU8rJyG9SoDkJUuPojCZzBhLDYRvFxpNpglnABBMQAMWApj84h8rj8ASCaFWkikGy2OxQn0Ox1OkIiVziCSgSQeYnS1KB4I++x+-0hWVy+TBxQhmShsuIRCoEkqQA)

### 💻 Code

```ts
interface Base {
  foo?(): void;
}

interface Second {
    add(base: Base): void
}


// ✅
class CorrectEmpty implements Base {
    constructor(b: Second) {
        b.add(this);
    }
}

// ❌ but should be ✅
class IncorrectWithCustom implements Base {
    private bar: number;
    constructor(b:Second) {
        this.bar = 1;
        b.add(this);
    }
}

// ✅
class CorrectWithCustomAndFilled implements Base {
    private bar: number;
    constructor(b:Second) {
        this.bar = 1;
        b.add(this);
    }
    foo() {}
}
```

### 🙁 Actual behavior

In the snippet above, both `IncorrectWithCustom` and `b.add(this);` fail with the error `Type 'IncorrectWithCustom' has no properties in common with type 'Base'.(2559)`.

### 🙂 Expected behavior

According to the example `CorrectWithCustomAndFilled`, you can define additional parameters to the class that extends the interface. So the example `IncorrectWithCustom` should pass the typecheck.

**Comment by whzx5byb** [comment]
This is the intended behavior. See https://devblogs.microsoft.com/typescript/announcing-typescript-2-4/#stricter-checks-on-weak-types

**Comment by Ayc0** [comment]
Ohhh, I didn't know about that!
Thanks for the explanation 🙇
