### ISSUE TITLE
Type parameter can leak out of a function instead of being bound to specific type

### ISSUE THREAD

**Issue by jsnajdr** [microsoft/TypeScript#43961]
# Bug Report

### 🔎 Search Terms

type parameter leaks out

### 🕗 Version & Regression Information

In the TS playground, the first version that shows the bug is 3.5.1. Version 3.3.3 also behaves incorrectly, but in a different way.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.3.0-beta#code/GYVwdgxgLglg9mABAdxlAFgBQIwB5GaIB8AFIgA4BcBiAlIgN4CwAUAJAQIDOUiAtogC8ifAEliZYACc4fauPqCiiMg0QA6TdNkAaDZvKIAvnQDcrNlICmUEFKR9zLI61acwPRAEMAJj5xCKGhY2KqIwHBw1NjGZm7cvL4+Vj4xwkk4YQBGXlLUAEyxtE7xHnAANlbq5XAA5mRJKdjqEXB6janqOVJxLKWeENZeUFYAKlJeHhFSAsJiegDyEohQeSrhMnKICkLKS4rKqyUsoJCwCEEYmPn4hKQU1IT0zOzunrMi28vaWztK62pNC1NnogYYTMULNZbPZEIMrMMxhMpnAZmQBJDnK4WG9En5roFUFd8mFWtEik5cd4-ClCul8STGIhugUKdi3hUqjV6tTkj58i1Iu0afyurkzEA)

### 💻 Code

```ts
function withP1<P>(p: P) {
  const m = <I>(from: I) => ({ ...from, ...p });
  return m;
}

const addP1 = withP1({ foo: 1 });
const added1 = addP1({ bar: 2 });

console.log(added1.foo, added1.bar);

const createTransform = <I, O>(tr: (from: I) => O) => tr;

function withP2<P>(p: P) {
  const m = <I>(from: I) => ({ ...from, ...p });
  return createTransform(m);
}

const addP2 = withP2({ foo: 1 });
const added2 = addP2({ bar: 2 });

console.log(added2.foo, added2.bar);
```

### 🙁 Actual behavior

The `added2.foo` expression reports a type error:
```
Property 'foo' does not exist on type '{ bar: number; } & P'.
```

The `index.d.ts` generated from this source has a declaration for `addP2` that contains an undefined identifier `P`:
```ts
declare const addP2: <I>(from: I) => I & P;
```

On the other hand, the `addP1` version works well:
```ts
declare const addP1: <I>(from: I) => I & { foo: number };
```

The only difference is that `withP2` calls an additional `createTransformer` function which is an identity.

### 🙂 Expected behavior

Both `P1` and `P2` versions behave the same way and infer the return type correctly, without leaking the `P` type parameter.

**Comment by Andarist** [comment]
I thought that it might have been just fixed by https://github.com/microsoft/TypeScript/pull/57403 but it didn't 😅 My suspicion is that this PR is crucial for fixing this - maybe it just missed something.
