### ISSUE TITLE
Fix error message typo.

### ISSUE THREAD

**Issue by cjbarth** [Microsoft/TypeScript#4396]
error TS2342: An index expression argument must be of type 'string', 'number', 'symbol, or 'any'.

Should be:

error TS2342: An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.

Note the missing quote after "symbol".

**Comment by mhegazy** [comment]
@cjbarth a PR would be appreciated. the change needed is here: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json#L968

run tests using `jake runtests` and accept changes from the fix using `jake baseline-accept`
