### ISSUE TITLE
TypeScript intellisense is slow in VS2015 on a project with over 1000 files and 200000 LOC

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4397]
Our project is 1000+ TypeScript files and 210000+ lines of code. It takes significant time (from 2 - 10 seconds) to get intellisense support in a newly opened TypeScript file in VS 2015. Acknowledging changes in code and error detection takes as long. 

Is there any hope to make it faster or this is as fast as it can be already?

The total compile time is comparable to the time required for the TypeScript service to respond to a change or open a file.
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.52
```

**Comment by danquirk** [comment]
We'll need some more information to make progress here but we would definitely like to get to the bottom of this. Can you share the project with us (privately is fine)?

**Comment by aleksey-bykov** [comment]
Although I am all up to assist in resolving this problem, I cannot share the project (it doesn't belong to me).

**Comment by danquirk** [comment]
Totally get it, just always have to check in case the easiest option is available :)

**Comment by vladima** [comment]
Out of curiosity, do you mostly use external modules/imports or tripleslash references to refer to other files in project?

**Comment by aleksey-bykov** [comment]
- we only use external modules (AMD)
- there are 49 declaration files (*.d.ts) of 33000 LOC total
- we don't use /// 
- these are the build settings and which, I guess, are what the TypeScript service is initialized with:
```
tsc.exe  --removeComments --noImplicitAny --module AMD --outDir "Scripts\Built\" --target ES3 --noResolve --noEmitOnError --noLib 
```

**Comment by vladima** [comment]
that is good, in 1.6 we've improved the way of how program structure is determined after some file is edited - if edit does not affect imports (which is usually the case) then we don't do lot of expensive work that we'll do otherwise. Note that these changes affect both script and managed sides of the language service so just getting the latest 'typescriptServices.js' from the master is not enough.

**Comment by aleksey-bykov** [comment]
gonna have to wait until 1.6 is officially released, unless there is a way to take a sneak peek at the new managed side of the service

**Comment by mhegazy** [comment]
@aleksey-bykov there is not a way now, but let us see what we can do.

**Comment by aceslick911** [comment]
Also have this issue but in addition to intellisense being very slow and locking the IDE, my VS2015 crashes 3-4 times a day.

We have a very large typescript project also using AMD with about a 12 second compile time (1200+ ts files).

Very interested to hear if there will be fixes made in 1.6 or at least an end to the UI locking 2 seconds after any ts file is opened.

**Comment by vladima** [comment]
@aceslick911 crashes definitely sound bad. Can you set [ProdDump](https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx) as a postmortem debugger to capture dump right before the crash and share it? Also can you check if you have any error entries in system event log (eventvwr) that have '.NET Runtime' as a source.

Re locking the IDE, can you make a dump of the process using ProcDump at the moment when IDE become non responsive ad share it as well?

**Comment by aceslick911** [comment]
Thanks i've installed the tool and will report back when I have some dump files. Do you want me to post it to a specific e-mail address or attach it here?

**Comment by vladima** [comment]
Can you upload them to OneDrive\Dropbox\whatever storage you prefer and send the link to ```vladima <at> microsoft <dot> com```?

**Comment by vladima** [comment]
and as for records from event log (if it have any '.NET Runtime' errors) - you can post them here

**Comment by aceslick911** [comment]
Thanks I just sent an email with a GDrive link to the dump files and event viewer files. Let me know if there is anything else I can do to help diagnose this issue.

**Comment by mhegazy** [comment]
@aleksey-bykov any improvements using 1.6?

**Comment by aleksey-bykov** [comment]
Will let you know tomorrow

**Comment by aleksey-bykov** [comment]
works so much faster! the issue can be closed as far as I can tell, thanks!

**Comment by mhegazy** [comment]
Glad this is fixed! Thanks @aleksey-bykov
