### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by cburnett707** [microsoft/TypeScript#43978]
Yes

_Originally posted by @roblourens in https://github.com/microsoft/vscode-chrome-debug-core/issues/91#issuecomment-265027348_

**Comment by cburnett707** [comment]
> Yes
> 
> _Originally posted by @roblourens in [microsoft/vscode-chrome-debug-core#91 (comment)](https://github.com/microsoft/vscode-chrome-debug-core/issues/91#issuecomment-265027348)_

**Comment by orta** [comment]
Assuming this is an automation mistake
