### ISSUE TITLE
Specializing on this fails to produce an error without unrelated method

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#43970]
# Bug Report

I'm trying to make a method only available on an interface `Foo<T>` for particular types of `T`. This can be done by specializing on `this`, but it only seems to work if I add an unrelated method that uses the generic parameter. I thought this was strange, so here we are!

### 🔎 Search Terms

- 2684

### 🕗 Version & Regression Information

Version: **4.3.0-beta**

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `this`

### ⏯ Playground Link

```ts
interface Foo<T> {
  // val(): T;
  bar(this: Foo<string>): string;
}

declare let f: Foo<Date>;
const b = f.bar();  // ok, type is string
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const b = f.bar();  // ok, type is string

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/JYOwLgpgTgZghgYwgAgGIHt0B4AqA+ZAbwFgAoZZAekuQDc4AbACgEoAuZHAbjIoCM4UJmAAWwAM4cM2cWCigA5nnbJZ8kAp6kAvmTIATCAgaCUDCGGQwpmLABE4kPFoToQs5H2QBeKwDoBIRYtagowsIA-MlCcERQAclEJeORXcAgAD0t0GGQwAE8ABwTpe0cIPBSJZBB0SzhxcWAFEDg+czz0ZABbCxF0fXjxZESxcRScvKKS2zVFSr9omgocaZGHSCrh2vrG5tb2lDAuguKRuY14v2QmACYANgAOABYWMiA)
      

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
interface Foo<T> {
  // val(): T;
  bar(this: Foo<string>): string;
}

declare let f: Foo<Date>;
const b = f.bar();  // ok, type is string (but should be an error)
```

### 🙁 Actual behavior

No error.

### 🙂 Expected behavior

I'd expect an error! When you uncomment the `val(): T` line, you get the expected error:

```ts
interface Foo<T> {
  val(): T;
  bar(this: Foo<string>): string;
}

declare let f: Foo<Date>;
const b = f.bar();
//        ~
// The 'this' context of type 'Foo<Date>' is not assignable to method's 'this' of type 'Foo<string>'.
//   Type 'Date' is not assignable to type 'string'. (2684)
```

But what does `val` have to do with `bar`?

**Comment by RyanCavanaugh** [comment]
A `Foo<string>` is a structural match for `Foo<Date>` when `T` doesn't appear in the definition of `Foo<T>`:
```ts
// Structural expansion of Foo<string>
interface Foo1 {
  bar(this: Foo1): string;
}
// Structural expansion of Foo<Date>
interface Foo2 {
  bar(this: Foo2): string;
}
```
Therefore the call is legal

**Comment by danvk** [comment]
Structural typing strikes again. Thanks for the explanation, Ryan!

**Comment by MartinJohns** [comment]
Related: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--
