### ISSUE TITLE
Breaking assignment: objects of spread arrays to an array type

### ISSUE THREAD

**Issue by oluwasayo** [microsoft/TypeScript#43977]
# Bug Report

### 🔎 Search Terms
- spread array into object
- object array

### 🕗 Version & Regression Information

- The behavior was observed between 3.5.1 and 4.3.0-beta
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common Bugs that aren't Bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/MYewdgzgLgBAhgJwQRhgXhgbQN4wLYCmEEcA5gQFwwDkARgDYCuB1MAvgLoDcAUKJLEQIATOiy4IjWgCsCwKFWoICAE1adefcNBggZVAIJI4ATwA8uQsTKUY0BAEswpdjAA+MCVNnyq9py5sAHxi2AB0EULIADQwEWFCwmya-BAg9ARh9CCkABR60gCUXDAA9KUwAPKMUAAONTD8UHBOELpg9CbtBDAEGYRgUGE8POUwAKIAHlAIcDAAkmAAZiAjqbBgBADulTJiBWF4cLW5k+ghkwD8h0Qk5MVlFbvSMA5ttAQBMDMEcFCq8DacDAMCMsxMsTg9GyWy+UAAFj0jrUYEtGGB5A5wI0ofRhjw0RioFiQdBGEslshcrVEHA8FQAEpyEAIFRmahWO4sdw0SQyORQaixfzOIKFTw8GBSxradKZbJ5ABEABEQF8yRTFcUeGwCejMdiNUthNTafTPPhbjZLn4ZgESnyfFAbXY7c52OLsJLpak5VkcrkVWr3UatbxdYSDaSoOSlgBmU2zc0FAWe71S30Zf1K1XqmOa7W6nhGqkFbVGk1l3hGhNVx5VPZvGC1AgIPAOKD-FSA+AglPyMJAA)

### 💻 Code

```ts
const arr1 = [{ message: 'blue' }];
const arr2 = [{ subject: 'red' }];

const obj: Array<{ message: string } | { subject: string }> = { ...arr1, ...arr2 };

console.log(obj);
```

### 🙁 Actual behavior

Code compiles even though an object is being assigned to an explicitly specified array

### 🙂 Expected behavior

Compilation should fail. The spread into object does not preserve the semantics of spreading into an array since elements will overwrite each other. This opens up the possibility of a serious data loss.

**Comment by RyanCavanaugh** [comment]
Duplicate #35778
