### ISSUE TITLE
Array type refinement on `.every`

### ISSUE THREAD

**Issue by cakoose** [microsoft/TypeScript#43989]
# Suggestion

## 🔍 Search Terms

array refine every

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A way to make `Array.every` refine the type of the argument array.  This isn't sound, but I think the unsoundness is similar in spirit TypeScript's usual unsoundness around mutability.

## 📃 Motivating Example

[Playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWwIYA8CMAeAKgPgAoBnKEYYALkQEEAnO1AT21LpjAHNEAfRMEMgBGAUzr4AlNQHCxiAN4AoRCsQxgiEmQoA6EQDcxTQukQBefIihMADiLgbTZ54gDkM0XVcSJC5aoCAWVQoAAsdNHRCHRjScmAJAG5EAHoUxABRBjg6alc2Dm4+DzFXNWJ+OChEVGJiGE4wVCEAGxErODcSrx1FfxUAX37EOhEyOiQAWkxExSHFABMRCBbUUcRQSFgERAMjPAAaRAAlXfQoETAFioJCNcYmanoHvHwjm1GFmAgQkWpCfSoFogP6IXC+CyIQHA9owCrHKQ1BjMcq0ZEsY74WaKTbQeBISIAJleWniT3RrCg7C4vH4gk8kmk9LkSgC6k0ezoxjiFCOTks1jsDkQThc7mZXh8ClS6SydBy-3Q1AKNOKEohliEcDgbVQYDKcMq1Vq9UazTaHTcAKBIOVVMKtO6GqhNthFRVRTpsi8wyCIXCkWisW0CVmASGAVG4ymMzmfTSiAA6jkANYVADuMDCZxsLW+WastnaerAVRC+MQO1x2yQUZAE0Ldl61YrkQAzCSeVQ0S8PY6JYyvZ4-GyNIROdyQ0cTIjTIbuuYBUXhaKzF0Jd5fKyAqpgmEIhggzou0lhhHVHWG9NZvMWwgAFSIABeMBsJJiOizYnNImI5JeACSFyMK0IivIOQHfqB2DPMw4Ejqo7KEF+IFtMQOhtFw2bOGuAAMvhhPK6b8CIxFyjkhCuChP4VIaIjIDY1jeGGqgJhk6C5vmxpgKWUDljsOxUcBIQ5MQZSiD8IDEO0kGMFAOT5Ig0kQAgCyNsWdCcIIlzVEswCoCALRQBU8luHqTCuEc6ahN8oQoLUaZWKE7SuHQOjQiCZRiPKdCIKILRwOmvQBCpYCkGownyXQf49nBskiXQhyIOAKalumYBHGAnL4JYa7UaB6FoDYyHVJCWYANoAMpMMIOqfpFOQALqED42IBNZMAWoQVIgluvqqKF4WjMQhnGeYEXflFhWoMVBZlVAOhZecLWnjuiFjgAhBOhDDaNxBHL5kJuQsCDtBtLg9SIUryDKmTZL5zmjEcQggNUAGICd+rVKlgWINZIQ1DxZY1pa6bsBcwVrTul5gCxa3nmtTAwCILRqbtRnTcVh2WG5HlXckbH3Ygj0iM9ywGdJIzua6KANKE1SiBsOQ1G4n0iAaDV0GecxAA)

It would be nice if this worked:

```ts
function max1<T>(stuff: Array<string | number>): number {
    if (stuff.every(x => typeof x === 'number')) {
        Math.max(...stuff); // Error: 'string | number' is not assignable to 'number'.

    }
    return -1;
}
```

I tested it out with my own `every` function.  But to get my original example to work, I needed to annotate the return type of my predicate:

```ts
declare function every<T, R extends T>(array: Array<T>, predicate: (value: T) => value is R): array is Array<R>;

function max2<T>(stuff: Array<string | number>): number {
    if (every(stuff, x => typeof x === 'number')) { // Error: (x: string | number) => boolean' is not assignable to '(value: string | number) => value is string | number'
        Math.max(...stuff);
    }
    return -1;
}

// Works with explicit type annotation on predicate return type.
function max3<T>(stuff: Array<string | number>): number {
    if (every(stuff, (x): x is number => typeof x === 'number')) {
        Math.max(...stuff);
    }
    return -1;
}
```

## 💻 Use Cases

The original inspiration for this line of thought came from writing a `zip`-style function:

```ts
function* zip<T>(...iterables: Array<Iterable<T>>): Iterable<Array<T>> {
    if (iterables.length === 0) throw new Error('iterables is empty');
    // Explicit annotation on 'iterators' because Iterator's second type argument defaults to 'any', which masks the 'r.value' error below.
    const iterators: Array<Iterator<T, unknown, never>> = iterables.map(it => it[Symbol.iterator]());

    while (true) {
        const results = iterators.map(it => it.next());
        if (!every(results, r => r.done !== true)) { // Error here, but I don't know what annotation to write.
            return;
        }
        yield results.map(r => r.value); // Error here, because r.value might be for a 'done' iterator
    }
}
```

**Comment by MartinJohns** [comment]
In order for `every()` to narrow the type you must pass in a **type guard** function. You currently don't do that.

This is **not** a type guard: `x => typeof x === 'number'  
This is a type guard: `(x): x is number => typeof x === 'number'`

You're looking for #38390.

**Comment by cakoose** [comment]
Thanks!

**Comment by MartinJohns** [comment]
I removed that part of the comment because you actually mentioned those parts in your issue already. :-) Or so I thought, re-reading your issue I think I too hastely removed that comment.
