### ISSUE TITLE
ts assumes a static function in an abstract class needs to be defined

### ISSUE THREAD

**Issue by oakgary** [microsoft/TypeScript#43994]
# Bug Report

### 🔎 Search Terms

This condition will always return true since the function is always defined. Did you mean to call it instead?ts(2774)
static method in abstract class

### 🕗 Version & Regression Information

This changed between versions 3.8.3 and 4.2.4.
The bug is not fixed in the nightly version.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/IYIwzgLgTsDGEAJYBthjAgggg3gKAUIUmAgEtYFgAuBACgEoEBeAPgQDcB7MgEwG48BIgAcAriGQViEUtJCNa3PrmFEiZAGZ0IACzJgAdMCb515orC4A7MF2QBTQ8i4BzOgHJYwZI94JNMWt4MhsEECprf0Dg8jDgBAMEXgdNMmsHXg8GQQtCAF8EB2QwB1U88ytbeycXdy8fPwCgkLCI4Cjm2NDrKkSMay5EFLSMrIY1c3zJ6em8FDQMAA0igA8IByiMbHw8OYX0BABNNY2trHKiEnJKYEZLiwB6R5m9oSXDBRy8I8-GfiAA)

### 💻 Code

```ts
abstract class A {
    static a: () => void;

    public static b(): void {
        if(this.a) {
            console.log('called function b and function a is defined');
        } else {
            console.log('called function b and function a is not defined')
        }
    }
}

class X extends A {

}

class Y extends A {
    static a() {
        //
    }
}

X.b();
Y.b();
```

### 🙁 Actual behavior

The error "This condition will always return true since the function is always defined. Did you mean to call it instead?ts(2774)" is displayed on this.a in function b of class A.

### 🙂 Expected behavior

A static function in an abstract class does not need to be defined. The error should therefore not be displayed.

**Comment by RyanCavanaugh** [comment]
Duplicate #27899; static members are assumed to have actually been initialized and what you're seeing here is a "missing" error.

**Comment by Stirfry70** [comment]
[]()

**Comment by oakgary** [comment]
> Duplicate #27899; static members are assumed to have actually been initialized and what you're seeing here is a "missing" error. You should mark this property as optional if it's intentionally sometimes-not-present

Actually it is unintentional sometimes-not-present as you cannot make static methods abstract.
The check in function b is there to make sure it is defined.

For anyone stumbling upon this in the future. The error is resolved by marking the function as optional, as suggested by RyanCavanaugh:

```ts
abstract class A {
    static a?: () => void;

    public static b(): void {
        if(this.a) {
            console.log('called function b and function a is defined');
        } else {
            console.log('called function b and function a is not defined')
        }
    }
}

class X extends A {

}

class Y extends A {
    static a() {
        //
    }
}

X.b();
Y.b();
```
