### ISSUE TITLE
Alias type for indexing a generic object breaking change in 4.2.2+

### ISSUE THREAD

**Issue by iPherian** [microsoft/TypeScript#43991]
# Bug Report

### 🔎 Search Terms

index generic with alias, alias generic

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.2
  - Still broken in 4.2.4 and nightly

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAaghgGwPIDMA8AVAfFAvFDAbQGsIQB7FAgXQG4BYAKCdEigFEAnT8zgJQgBjXgBM8UAcM4i0AZ2CcAlgDsA5gBoO3XlgbNGK4BE4o4g6Fx6coAbyZQowkRABcUZQFcAtgCNjegF8mJmFleUdyLy9yZUteWXE7RgcAd0URVQhgWQA5cmAAdXTM0HZlcg9VAAs3JIcHJ1coAEZW9XsoAPbGAKg4BND5PSYIAA8wXmBHBH6EuM5ZNABBERFFYEUYxHnJUSgxo2UROe1+IVEcOqgwJQA3OCMoAH1jK13pNwBhD3lIpB8AFZCYBLWSyRSqZRoDoOVgQSgRKIxeaybr1KArNYbLYIHbnaQdXTBZIRMIKDyCYC8AAUcFW602ym2p1kbkxDJxeKkIgAlLYYVBgFVFLIAHQvU7vMT4QQ-Klef5Aymg8GQ6nCJGxFmaOlYxnMqyyHl6BxBfQOMAeHwIRSCKAlebUgWvXg5OBeJqkChUFHLenYpm4yX4kRYQgAIglbxD4eoHR5bngyHQvvZAYNvClYcjLrO3NjlwFAHoAFQlgVQEsEYUJG3KaA3cgiCkQBJwZT7U5QFSC8CtwRKMBTAAsooATKLRlAfB4prIKeYIMdux3R81RQBWCslosCzhZDycDtCkXi3NSwi5t0eugdM1mkIxcK5hL4espLSG6lXNIZLK5fIij-UpykqGp+RJBomyaVphz6AYn2ANFOmQqlyAAWXbEAABFyCbOlWQg9FGjcVox3g0l5GQromACY1iUGKZfxKWRLHEF9RQdU5qXDZj-zyQpiiyEAygqapw3oxhGKgEQ8JEAj2JZTiskdcM0Mw5QcLkgiJOGRgUA8ZRKUZRw5T+QFgRVCEoQwOBOBKfZRkOZcbC6KAAGUKk4cxHOchJXKwJ0SWAOySjcWz7KyZDZC88w3E8w9zCYBMoG+X4FQs5UwWszBQqijzYogQsSX3YBDw7alFWBUVZmsoL0RsKBRWakLIqmGjIKgGLEogeMKMM4hyhSZQ+X6VKzIypUQWyyFcrazQEu8orAmJOFxvSqqstVKEABkAAl3N8iAjn8ty+AOo6TtsAIcHwJAvHWNBzvczQvQRfb3JwAAyDorgcQgAGkVygN6qA+6g3CBg5juXUGJAugB+eH3MB6goDcD7UZNTo9CAA)

### 💻 Code

```ts
type ValOf<T> = T[keyof T];

type ErrorRecord = Record<string, Error>;

interface Error {
  code: number;
}

const commonErrors = {
  widgetsNotWidgetyEnough: {
    code: 111,
  },
} as const;

export class Errors<AdditionalErrorRecord extends ErrorRecord> {
  private _errorRecord: CustomObjectAssign<
    typeof commonErrors,
    AdditionalErrorRecord
  >;

  constructor(additionalErrors: AdditionalErrorRecord) {
    this._errorRecord = customObjectAssign(commonErrors, additionalErrors);
  }

  public getError(
    errorName: keyof Errors<AdditionalErrorRecord>["_errorRecord"]
  ): ValOf<Errors<AdditionalErrorRecord>["_errorRecord"]> {
    /**
     * This line produces an error in typescript 4.2.x but succeeds in 4.1.5
     */
    return this._errorRecord[errorName];
  }
}

const errors = new Errors({
  widgetsNotWidgetyEnough: {
    code: 114 as const,
  },
  tooManyDoodads: {
    code: 112 as const,
  },
});

const widgetsErr = errors.getError("widgetsNotWidgetyEnough");
const doodads = errors.getError("tooManyDoodads");

function customObjectAssign<Target extends {}, Source extends {}>(
  target: Target,
  source: Source
): CustomObjectAssign<Target, Source> {
  return (Object.assign(
    { ...target },
    source
  ) as unknown) as CustomObjectAssign<Target, Source>;
}

type CustomObjectAssign<LHS extends {}, RHS extends {}> = Omit<RHS, keyof LHS> &
  {
    [K in keyof LHS]: K extends keyof RHS ? RHS[K] : LHS[K];
  };
```

### 🙁 Actual behavior

Says the value returned by getError() is not assignable to the annotated return type.

### 🙂 Expected behavior

Would expect it to succeed, because the return type is just an alias for taking the index like `T[key of T]` which is what the return statement is doing. Also it worked in 4.1.5.

**Comment by RyanCavanaugh** [comment]
This is a correct error; effectively the case you're being warned against is
```ts
const errors = new Errors({
  widgetsNotWidgetyEnough: {
    code: 114 as const,
  },
});

const widgetsErr = errors.getError("widgetsNotWidgetyEnough");
```
Here, `getError` can only legally return `never`, but is failing to do so by returning a concrete value instead.

**Comment by iPherian** [comment]
@RyanCavanaugh You're right! It's my mistake, I left something out of the example (forgot how intersections work). I actually had a custom `Object.assign` which overrides properties when they conflict instead of producing `never`. Updated the OP.

**Comment by iPherian** [comment]
@RyanCavanaugh hmm is it still working as intended with the updated example? I don't know. Should it ever produce never?

**Comment by iPherian** [comment]
hmm I'm not sure anyone saw the edit. Reverting this to the state it was at the time the "working-as-intended" label was applied. I'll open a new issue for the other thing.
