### ISSUE TITLE
Support new 1.6 compiler flags in VS/targets files

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4399]
- [x] jsx in VS2013
- [x] jsx in VS2015
- [x] outFile in VS2013
- [x] outFile in VS2015
- [x] moduleResolution in VS2013 
- [x] moduleResolution in VS2015
- [x] experimentalAsyncFunctions in VS2013
- [x] experimentalAsyncFunctions in VS2015

**Comment by paulvanbrenk** [comment]
checked in for vs 2013/5
