### ISSUE TITLE
Override modifier in parameter declaration should have quickfix

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#44009]
# Bug Report

### 🔎 Search Terms
override, parameter declaration, quickfix

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?noImplicitOverride=true&ts=4.3.0-dev.20210507#code/MYGwhgzhAEBC0G8BQ1XQGYHtPQLzQEYkBfJJUSGAEQOgFMAPAFzoDsATGeZNaYTVhCYAnAK7AmmYQAoUvNAAdRAIxABLYBmwAuaK1EBbZXWEAaaAHoL0CAAtMokO2i2wANzrQAjqI0BrdDUGaEloMHZnA0x2NUCTczAOaGMmFmFoAzooMABzOjlUAEpEAvkIUQUTaUKAblLSUnJwKGgqACZ6ZjZOOBLefkERcUkZUt4lVQ1oTA9hYTV2T2UwYV19I3jLazsHJxd3Tx9-QODQ4Toojwzo2LUTUuKeeVRyypla+pIgA)

### 💻 Code

```ts
class B {
    foo = 1
}

class D1 extends B {
    constructor(
        public foo: number, // should have quickfix to add modifier, and better message
    ) {
        super();
    }
}

class D2 extends B {
    constructor(
        public override bar: number, // should have quickfix to remove modifier
    ) {
        super();
    }
}
```

**Comment by DanielRosenwasser** [comment]
Thanks!
