### ISSUE TITLE
getElementsByClassName isn't implemented on typeof `Element`

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#4401]
MDN leads me to believe that `getElementsByClassName` should be a valid member of any `Element` (and every browser I've tested leads me to the same conclusion).

[Here's the source documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName) that I'm trying to write an application using.

I've tested this with TypeScript 1.5.3 (via the ST plugin's language services) and the latest 1.6-dev.

**Comment by mhegazy** [comment]
@zhengbli can you take a look?

**Comment by SaschaNaz** [comment]
Related to #3220?

**Comment by zhengbli** [comment]
It is a spec error. Indeed the ``getElementsByClassName`` should be defined in ``Element`` instead of ``HTMLElement``.

**Comment by S-YOU** [comment]
I am not sure typescript support IE8, but as far as I remembered, it doesn't have on every element, but on document.

**Comment by LPGhatguy** [comment]
There's no issue targeting IE8 even with typing definitions from modern browsers -- not having the definitions simply makes targeting browsers released in the past 6 years more difficult.
