### ISSUE TITLE
Generate TypeScript files by combining TypeScript declaration files and corresponding JavaScript files

### ISSUE THREAD

**Issue by ApsarasX** [microsoft/TypeScript#44011]

**Comment by orta** [comment]
We have docs on how to generate .d.ts files from JS files: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by ApsarasX** [comment]
> We have docs on how to generate .d.ts files from JS files: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

@orta Sorry, you seem to have misunderstood what I mean. I'm talking about `.js`+`.d.ts`->`.ts`
