### ISSUE TITLE
Incorrect `never` type inference.

### ISSUE THREAD

**Issue by h-joo** [microsoft/TypeScript#44025]
# Bug Report

The type inference does not consider(or be conservative on) side effects of function calls. 
Might be a related issue the first failure report in  #43819 

### 🔎 Search Terms
does not exist on type never

### 🕗 Version & Regression Information
- This changed between versions `4.2.3` and `4.3`
- Also confirmed with the release candidate `4.3.1-rc` with git hash `d805ce877ae6235565ee697c3c0ce8a95a9c58f6`

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210510#code/MYGwhgzhAECC0G8CwAoa7rAPYDsIBcAnAV2Hy0OgApCBTMAE1xAE9ox8iBLAI2gC5oOYgFsetQgEpEAX1RyUAM2I4yXXNEVYsAJirAwIEDzDAA1gPY4W05GgwGjJ81UkBuealTLV+dTk1tV0RUDGgQWnx2HmABeAAfIWIjaABeJKMPe3RQjC1dKmppVIA+EOyw6C5FQpxaAHdoABEOWlcAOgBzSIAVLhE26TKARgAGcYnbXMrKsBi0oQa4KmGdAGZ3acqFMJlNirp8YkIAudiAfmjgdo5uPkFhTPkgA)

### 💻 Code
You need to enable the --strictNullChecks to trigger the bug
`./bin/tsc test.ts --strictNullChecks`

```ts
// test.ts
class A {
    constructor (readonly attrib : number) {}
}
function foo2(callback : any) {
    callback();
}

function foo() {
    let abc :A | null = null;
    
    foo2( () => {
        if( new Date().getTime() > 1000000) {
            abc = new A(123);
        }
    });
    return abc ? abc.attrib : null;
              // compiler error triggers on the abc.attrib
}
```

### 🙁 Actual behavior
tsc prints the following error : 
```
test.ts:21:23 - error TS2339: Property 'attrib' does not exist on type 'never'.
21     return abc ? abc.attrib : null;
Found 1 error.
```

### 🙂 Expected behavior
Not report the error.

**Comment by h-joo** [comment]
> Duplicate #11498, #9998. I'm not sure why this ever worked; adding `!` in that position clearly shouldn't _do_ anything since it's already known to be not-falsy due to its position in the `? :`
You have a point. It seems a bit weird as you say.

**Comment by nmain** [comment]
> I've updated the example from

To clarify, with the `!` weirdness removed this is still a combination of #9998, #11498, and #8513.

It's also no longer a regression: the oldest version on the playground, TS 3.3.3, behaves the same.

**Comment by h-joo** [comment]
> > I've updated the example from
> 
> To clarify, with the `!` weirdness removed this is still a combination of #9998, #11498, and #8513.
> 
> It's also no longer a regression: the oldest version on the playground, TS 3.3.3, behaves the same.

Great, thank you for the clarifying.
