### ISSUE TITLE
Incorrect type deduction

### ISSUE THREAD

**Issue by apirila** [microsoft/TypeScript#44023]
# Bug Report

An unnecessary and rather strange type case needed to case a structural type.

### 🔎 Search Terms

enum, string, literal types

### 🕗 Version & Regression Information

Tested with 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0#code/JYOwLgpgTgZghgYwgAgCoRAVwLbIN4CwAUMqciAFzk4BG0ANMWchFQERxvIA+ybNXXmwRtiAXwDcxUJFiIUqAM5gooAOb4mZStWx0ojEmVbJlqkGvFSixGJhAIwwAPYhkMZ84CMACjBV0LGwASk0iMVt7Rxc3D2cAJj8As3VQwnDiYgRXZWQ4ABlgWTgAG1QATwAHFABeMOYdL0NmEwAeDjYAPg7xLJywPIBlFXVkOvSGqiatUhMejJsiON8CouhSiurg6zjE1eKyqohtzKXPFeHzNW3kAHpb5AARZwhFEAByAYB3ZygAa1snj2l1S1iAA)

### 💻 Code

```ts
interface Tenum {
    n: number,
    e: "a" | "b" | "c"
};
interface Tstring {
    n: number,
    e: string
};

function foo1(t: Tenum) {
}
function foo2(t: Tstring) {
}

const aLiteralType = {
    n: 1,
    e: <"a">"a"
}
const aString = {
    n: 1,
    e: "a"
}

foo1(aLiteralType);
foo2(aLiteralType);

foo1(aString); // Doesn't work
foo2(aString);
```

### 🙁 Actual behavior

foo1(aString) gives a type error, while it could be allowed.

### 🙂 Expected behavior

foo1(aString) would be accepted as <"a"> typecast is strange and doesn't really do anything.

**Comment by nmain** [comment]
This is intended.  At the declaration of `const aString`, no contextual type is available so `aString.e` is widened.  You may be interested in const assertions:  https://blog.logrocket.com/const-assertions-are-the-killer-new-typescript-feature-b73451f35802/
