### ISSUE TITLE
lib.dom.d.ts deprecation comments cause documentation comments not to be picked up

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#44039]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `the default`.

## Bug

Some deprecated elements in `lib.dom.d.ts` are annotated like this:

```ts
interface HTMLFrameElement extends HTMLElement {
    /**
     * Retrieves the document object of the page or frame.
     */
    /** @deprecated */
    readonly contentDocument: Document | null;
```

Notice how it is using two JSDoc comments above `contentDocument`

This causes TS to only pick up the single `@deprecated` comment and drop the documentation comment before it

## Suggestion
I suggest merging these comments together:

```ts
interface HTMLFrameElement extends HTMLElement {
    /**
     * Retrieves the document object of the page or frame.
     * @deprecated
     */
    readonly contentDocument: Document | null;
```

**Comment by Scharkee** [comment]
I have opened a PR to address this issue: https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1011
