### ISSUE TITLE
[JavaScript] Type of `this` incorrectly changes to "`this`" on property assignment within function property implementation

### ISSUE THREAD

**Issue by ericdrobinson** [microsoft/TypeScript#44035]
# Bug Report

### 🔎 Search Terms

- javascript this function scope
- javascript function property scope
- javascript function property scope assignment
- javascript function this scope change

### 🕗 Version & Regression Information

This changed between versions 3.8 and 4.0, but it is still a _partial_ issue in all versions of 3.x on TypeScript Playground. This still occurs in Nightly builds.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&filetype=js#code/PQKhFgCgAIWgBALgTwA4FMAm6Bm0DeA8gEYBW6AxogL7QAq6AzoieVVLAqgE4D2G3FAWbcAlgDsA5rQCGHOPB790g5MMRiptYvK58BQ-CInToFXYv0rD4gK4BbYitrcZ4zL3sA5BxaUG1fAAKAEoAXgA+Yy1oSXREAEE-K1UCUMjo0zjEACFk5VTg8KiNE1psgGF8gLSRAC5oTOKAN15RTFpGeKSYBX9rQKD6xtKpFraOxvi83r0CwyGNBqbI1vbO+KrZy3nB8fWpxLpeLc4dmqLViY3c49O+lIX9ya7ECuOe2GAoKFAIbZQGAIDGYrEoNHk30gzRk3GgiCYLDI0DC0CC+GoIQA3FAEaCyAA6GQo6AAIgSpJxkDxSNIBOIJNJOUpuMRrAJFEZFRZkF+wGgAG1CABpBIATQAutAAAaIAAWokY0ugivhaCw0BkjBlINp4OlrPxdOyCRJOFs4iool44lCUHwHGgTu48Vs3HE8IVjCJVOofMFIvFUtlXuVqsBGq1OrZZH1htpBOyOTNFqtNrtkAdMCd0BdiDdHvlivpvv9ApyCQAIsGi0qVdqI5hNdqQ4qDdSY8bNinLYhrbaQvbHU7gMAALQTydT6cz2dz+cLsfD6Cj6AAJXQ9l4zXQntV4nQAA9ENAADYSXeIXhTS9ymQn+W7lR8bjazCKmSoDCwgCEy9X0AAOqiPKnq7v0qSvAi3AADQyrWYbaowFDKE2V5gf+-LQOavb9gSQEgXKvC2CeIFwa2daqshqHwtej6YU6OFpuIADk2qoLC6DiCevCxlQaKyp2DS6mCVDSiEBIMcBoF0OqADKFBiKgJ48OgY4ACwEgADASACscEAJLcegp7nnJXFdNAADuvDcAA1tqcoqLuxAkQxmoes+tn1rm6CoLZCJNlZTkelBJjwZ2iabMqV7uY+2Gpn2NqSdmI7jouGWZVl07LrWBKuO4ng+PYJIALL3nK+VuB49ihFSOa+fm7p7t6FClpAq7llWNahj5jbNvBobxuyrymqiTFJbaIiDpmuVekSJIiO1nUVtWg1tn16pNlGFHtjSI3TD2zGLNwM1Zg1eUMqiS1QH6HX8l1a27ZtGDbS2CHDYSrwVEdk0nWdmHZUDwNzgxG5bjuLXQAex5nhetE3p695gdAXlwu+jCft+r5-qlK5YdJcooxBQhQSo5EIT51GvQj9F4wBE14QR8rEaRiAU71VEoTT6F0w1DOJf2bHQBxLrcdAvFsCeQSCUawmdvqEmAyDKsg3NxactdGj1TmMJwoeJJ5UmdX8-yXi8Cebio9wL4iy6Y6yRgClKSemk6bpt2fXSo13L9-YZudOaroBIUquIIGiDIplqFZYiIAi4hwTIJGeJ4qCnvEu4oTb4KnmojBEVZWDuVHp52-MohMBLhbqtGRr6ilF3zTIOtpfQTnQFu9hcSe0phMqVlRpg+ivRzG2D0htiYNg4h5+5EjQapgUDfFEYS3gjM2jKPsnMq1VxR3EZIVeX4ajZ9nhdnLpUHnjc5nlxKokbmwm235uW55NveapDvyYpojKWgG7PSnsOxGgJK8HIvtxqC3TADem-IABi3lGCeF3C6LUNo4KxyxuFWsYcRacW4k5RgqocCiEPEwA+u5FSMFsOgO+Togi1gkldFqUU3h1VAftL6mwPh+zgUOBB0BTRbhdKjQ86dRAUBAtAHcr5+zrxRufOysJiLuAGgXGyHoJDuWlJAu40o6j-jAAgNe+ARJ8RoF8NELCFpP3miaLhkA7pAA)

### 💻 Code

```js
/**
 * @typedef {Object} TestObject
 * @property {string} a
 * @property {string} b
 * @property {number} randomNum
 * @property {()=>string} getA
 * @property {()=>string} getB
 * @property {(str: string)=>void} setA
 * @property {(str: string)=>void} setB
 * @property {()=>void} setAToB
 * @property {()=>void} setBToA
 */

/**
 * @type {TestObject}
 */
var testObj = ({});
testObj.a = "A";
testObj.b = "B";

// [OKAY] `this` is typed as `TestObject`
testObj.getA = function()
{
    return this.a;
}
// [BAD] `this` is typed as `this`
testObj.getB = function()
{
    //--------------------------------------------------------
    // Remove this next line to see that the errors disappear!
    //  With the property setter, `this` is scoped to the
    //  function. Without it, `this` is scoped to the
    //  function's parent object (`testObj: TestObject`).
    // With TypeScript pre-4.0.5, IntelliSense works here but
    //  an error is reported when setting `testObj.getC` to
    //  the function.
    //--------------------------------------------------------
    this.randomNum = Math.random();
    return this.b;
}
// [BAD] `this` is typed as `this`
testObj.setA = function(str)
{
    this.a = str;
}
// [BAD] `this` is typed as `this`
testObj.setB = function(str)
{
    //--------------------------------------------------------
    // Remove this next line to see that the error disappears!
    //  With the property setter, `this` is scoped to the
    //  function. Without it, `this` is scoped to the
    //  function's parent object (`testObj: TestObject`).
    //--------------------------------------------------------
    this.b = str;
    var x = this.getB();    // Not an error pre-TypeScript 4.0.5
}
testObj.setAToB = function()
{
    // When initially written, automomplete correctly showed
    //  all properties on type `TestObject`.
    this.a;
    // The moment `=` was dropped, `this` was suddenly
    //  interpreted as the type of function `setAToC` and
    //  the types stopped working correctly.
    this.a = this.getB();   // Not an error pre-TypeScript 4.0.5
}
testObj.setBToA = function()
{
    // For some reason, wrapping this in parenthesis fixes
    //  the issue. I stumbled across this while attempting
    //  to use a type assertion on `this`.
    (this).b = this.getA();
}
```

### 🙁 Actual behavior

The type of `this` changes when assignment (`=`) is declared in a function property implementation. Type inference works correctly as long as `this` is used for access only, whether that be for properties or "methods". Once assignment to a property on `this` occurs within the function, TypeScript suddenly sees the type of `this` as scoped to the function being declared (as opposed to the object to which the function belongs).

#### Workaround

For some reason, putting `this` in parenthesis (i.e. `(this).myProperty = ...`) appears to circumvent this bad behavior.

### 🙂 Expected behavior

The type of `this` to be correctly inferred throughout the body of a function declared in this manner, regardless of property/method access or assignment.

**Comment by ericdrobinson** [comment]
Apologies if the language above is unclear/imprecise. My grasp on the correct terms in this space is... rough at best.

**Comment by RyanCavanaugh** [comment]
This is the intended inference; when there are property assignments to `this`, we assume the target object is a class.

**Comment by ericdrobinson** [comment]
> This is the intended inference; when there are property assignments to this, we assume the target object is a class.

@RyanCavanaugh Where is this documented?

Also, why does wrapping `this` in parenthesis bypass the issue?

**Comment by ericdrobinson** [comment]
> Inference rules for JS aren't documented; they're there for code hinting purposes and are subject to tweaking. If you need more concrete behavior we'd recommend using TypeScript or JS Doc parameters on individual declarations.

@RyanCavanaugh Perhaps I'm a little confused. The issue called out here causes my VSCode to report a whole bunch of errors. It took me an unfortunate amount of time to determine the pattern that lead me to the exact cause for "some functions don't scope `this` correctly".

This was also done after a long pass on adding JS Doc parameters to the source code in question. I also included JSDoc parameters everywhere I could think in the example provided in this Issue. Did I miss some JSDoc annotations in the code that would evade this quirky/surprising behavior?

>The inference takes place by looking for specific patterns in the syntax tree so indirections like parens or var _this = this; this.x = a will evade it.
Good to know that this works as well! I assume that the parenthesis approach adds less overall weight to the parser so I will prefer that for now.

**Comment by ericdrobinson** [comment]
@RyanCavanaugh Any insights here? The indirections you suggested did not, in fact, evade the issue. Is this expected?

Also, how would we use JSDoc as you suggested on individual declarations to work around this issue?

**Comment by ericdrobinson** [comment]
@RyanCavanaugh A quick last-ditch request for some responses to the following questions:

1. Any insight as to why your suggestion wouldn't work? The suggestion:
   >The inference takes place by looking for specific patterns in the syntax tree so indirections like parens or var _this = this; this.x = a will evade it.
1. You suggested "_using... JS Doc parameters on individual declarations_" as a way to help the inference system. What JS Doc parameters can I further add to help here?
