### ISSUE TITLE
TS2322 when trying to use ReturnType on the generic type

### ISSUE THREAD

**Issue by SancheZz** [microsoft/TypeScript#44049]
# Bug Report

### 🔎 Search Terms
TS2322, ReturnType

### 🕗 Version & Regression Information
4.2.3 & 4.3.0-beta & Nightly

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210511#code/C4TwDgpgBAysD2AnaBeKBvAUFHUAm8AksABQCUAXFAEoQDGSeAPAM7CICWAdgOYA0UNp14A+ANyYAvhMwAzAK5c6wDvC5REiqE2xQAKlAgAPYBC54WsBMkwioJNkghU9lKADd4HPBl2hINBDA8ohceuAQACJEwFBotMGh4ZBMegDaAOQExBkAuuK6DFxsGkEhXBB4yc6BiWER0cRxgtYQAHTZpGRiUAD0vfoRUBm0DIjMQtz8LcI8IhlQHJZc8LEAhiwsHDxcawBGADbQCFD+0CNlSQ0xGW0kAEwAzPf3ZFKYcorKquqaXPfaXQGYymcyWOBOWz2RzIFxuTzeXw4M61crVRqxeKXeopCHITKdPLiPoDOgACzWvGgPDMEE4dH0p3gpyGeIghTUJWQdUq1SoCTR1yaaBh7U65B6-UWsQA7kgANYsKRAA)

### 💻 Code

```ts
type Store = {
    doIt(): Record<string, string>;
};

function run <
  T extends Store
> (store: T): void {
  type ReturnTypeDoIt = ReturnType<T['doIt']>;
  const returnedType: ReturnTypeDoIt = store.doIt(); // Type 'Record<string, string>' is not assignable to type 'ReturnTypeDoIt'.(2322)
}

function run2 <
  T extends Store
> (store: T): void {
  type ReturnTypeDoIt = ReturnType<Store['doIt']>; // change generic T to type Store
  const returnedType: ReturnTypeDoIt = store.doIt(); // it works
}
```

### 🙁 Actual behavior
Type 'Record<string, string>' is not assignable to type 'ReturnTypeDoIt'.(2322)

### 🙂 Expected behavior
The function `run` works similarly to the function `run2` without any errors.

**Comment by RyanCavanaugh** [comment]
Property access produces types based on the constraint of the generic, rather than the increasingly-convoluted lookup / conditional types as would be required to make this not have an error.

**Comment by jtbandes** [comment]
This looks like the same issue, is that right?

```ts
const fns = { a: () => 42 };

function call<T extends 'a'>(key: T): ReturnType<typeof fns[T]> {
  return fns[key]();  // Type 'number' is not assignable to type 'ReturnType<{ a: () => number; }[T]>'.
}

let value: number = call('a');
```

https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBAZpGBeGBvGBDAXDAFASmQD4YAWAJhgF8BuAKDrgFcxgoBLcGYDAG14A8AFRgBTAB5RRYACYQYAcgwKiuANaiAnjiH4cAJVFQmAJzBDNAB1ECoV0SDjxIAbSEBdEqjowYJo6ZgzhAuGpruBPRUDLxGMABufEyiOGBMALYARqImyNx8vLhKCvj0QA

**Comment by steveetm** [comment]
@RyanCavanaugh I would like the ask similar, is this the same issue?
https://stackoverflow.com/questions/75525931/typescript-generic-function-which-returns-the-return-type-of-an-object-containin
