### ISSUE TITLE
Empty exports

### ISSUE THREAD

**Issue by Vardner** [microsoft/TypeScript#44040]
# Bug Report

### 🔎 Search Terms

prevent empty exports {} Object.defineProperty(exports, "__esModule", { value: true });
### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 3.9.6 and 4.2.4

### ⏯ Playground Link

[Playground link with relevant code, change typescript version between 3.9.4 and 4+](https://www.typescriptlang.org/play?target=2&ts=3.9.7#code/JYWwDg9gTgLgBAbwIICEDCBfOAzKERwDkAdAPQCGARgMaEDcAsAFDUQB2AzvOXALxwBGAEx0gA)

### 💻 Code

```ts
import {ABC} from './abc';
const a = 12;
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/36897869/117871713-685a5d80-b2a6-11eb-919f-64b31d705ea1.png)

### 🙂 Expected behavior
![image](https://user-images.githubusercontent.com/36897869/117871633-4e207f80-b2a6-11eb-8a3b-4719c238889d.png)

Hello, I have some problems when typescript generates empty exports in each file by itself. I use TS compiler to generate files that will be executed by eval. When eval happens I get an error because of exports. 
In typescript config, we have the option "isolatedModules", which could do this part of the functionality. 

Anyway, how can I get rid of any kind of exports in complied files? I hope you can help me because these exports force me to call string.replace() before executing the files!

**Comment by nmain** [comment]
When you type `import {ABC} from './abc';` you're using es modules syntax and so Typescript is processing your code as an es module.  It's producing output that's also es modules because of your compiler `module` setting.  Depending on what your runtime environment looks like, you could either change the compiler's `module` setting, or use some sort of bundler, but what you're asking to do just doesn't work out of the box -- you can't `eval` an es module.

**Comment by MartinJohns** [comment]
See also #41567, #41562, #41513.

**Comment by Vardner** [comment]
> When you type `import {ABC} from './abc';` you're using es modules syntax and so Typescript is processing your code as an es module. It's producing output that's also es modules because of your compiler `module` setting. Depending on what your runtime environment looks like, you could either change the compiler's `module` setting, or use some sort of bundler, but what you're asking to do just doesn't work out of the box -- you can't `eval` an es module.

yea, of course, but I use imports only for types and interfaces
