### ISSUE TITLE
`String#split` doesn't infer literal types when input is a template literal string

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#44052]
# Bug Report

### 🔎 Search Terms

"template literal" "split"

### 🕗 Version & Regression Information

I tried in latest version (v4.2.3 at time of writing), as it can be seen in the playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsg9gEwgGwM5QLxQOQFdUQBO2UAPjsInNgFCiRQCCAxsAJZwB26WeYBhYCXLYkyCMAi064aAFUBmKAG8aUKGwQAuKKmCE2nAOZqonAIYBbCDr0HjNAL40ZDACpUlq9Ztv7DJupIqMwGYOxcfvaBUAhcEAD8OgBGcHDi5pxOLvTQ8GIAYnCEADxuUBAAHpKcCOj5KKgAfEoAFKblVTV1OPhEJAlQCkRQWh0V1RC16NiUcQNQHnGjppwQAG5ENACULsxcelAAFpkI4oRKZRPd9YiNTa2Wd8g6bgA0UFwwuMDmEZw6VrmVgcAFQAAGABJlG5HAB6aEsf6oRzgj5gcwgZBwczaWDPIqlNxNbaYFrrOCaUmqZw0E61c6tPACbAfVq5dGY7G40kYFreKD7bjAKAAbSeYg+wP+AF0lLkAHSoMDINjAJlw7C7dSmOFw3RHOC4ZAITizKDJaC5T4AMygEpQFugrQARH1CC7SYY9BBcbbdP5jIMoLr9ahDcbTebLVBrXA7dLQU6oK7cPwiMAXWQoC6xBIIJ6NMLfQh-XYAsGnNsgA)

### 💻 Code

```ts
type Models = 'user' | 'todo'
type Actions = 'upsert' | 'delete'

type User = {
  id: string
  name: string
}

type Todo = {
  id: string
  description: string
  done?: boolean
}

type ModelFor<T extends Models> = (
  T extends 'user' ? User :
  T extends 'todo' ? Todo :
  never
)

const handler = <T extends Models>(model: T, onMutation: (action: `${T}/${Actions}`, payload: ModelFor<T>) => void) {
}

handler('user', (type, payload) => {
  const [model, action] = type.split('/')
  
  // shouldn't be type of model be ("user") instead of string?  
  // shouldn't be type of action be ("upsert" | "delete") instead of string?  
})
```

### 🙁 Actual behavior

- Type of `model` is `string`
- Type of `action` is `string`

### 🙂 Expected behavior

- Type of `model` is `"user"` (since it's computed from `T`)
- Type of `action` is `"upsert" | "delete"` (or even better, `Actions` - since it was computed in the template literal)

**Comment by RyanCavanaugh** [comment]
`split` doesn't have any special treatment that would allow it to infer this. You can add this to your local project to make it happen:
```ts
interface String {
  // Add as many as needed
  split<T extends string, U extends string>(this: T, char: U): T extends `${infer A}${U}${infer B}` ? [A, B] : string;
  split<T extends string, U extends string>(this: T, char: U): T extends `${infer A}${U}${infer B}${U}${infer C}` ? [A, B, C] : string;
}
```

**Comment by y-nk** [comment]
Thanks a lot for the suggestion @RyanCavanaugh it's definitely something I'm gonna add ; somehow i think since we have composable types with template literals, this should be added as core? What do you think?

**Comment by dearoneesama** [comment]
```ts
type TSplit<T, U extends string> =
    T extends `${infer F}${U}${infer Rest}` ?
        [F, ...TSplit<Rest, U>]
    : [T]

type is_same<T, U> = T extends U ? U extends T ? true : false : false

interface String {
    split<T extends string, U extends string>(this: T, char: U):
        is_same<T, string> extends true ?
            string[]
        : is_same<U, string> extends true ?
            string[]
        : TSplit<T, U>
}

const a: string = 'abcd/abcc'
const aa = a.split('/')  // string[]

const b = 'abcd/abcc'
const bb = b.split('/')  // ["abcd", "abcc"]
```

can something like this be added to the library?
