### ISSUE TITLE
Types not inferred correctly when combining type generic and function parameter types

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#44058]
# Bug Report

### 🔎 Search Terms

generics, function, conditional types

### 🕗 Version & Regression Information

- Tested with latest 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFpK0HEHkCCAZCVICh0BcCeAHAU1AQGMsBLAewDtQBeUAchICcCBDLAx0AHyYCueACadufJsIIAbAl0aZchUAFlKU6fVABvdKFDlhALlABnLC3LUA5ugC+i-EQAK7HNMrthAHgAqoAgAPLmphU1V1GQAaUABpAOCCUPDSChoAPi0ACj04hJCwplYOeVAAflB-I1z4oILwxiFRUorXFgp2aT9M6v1axOTJGTlxVvISAGs-GMZDRh7c6gIANwIWdABKR2UVASxOKmo-fKTCtQ1Mhm9++uIyQ-Ss9nuaE1iYvDcPLxNXd08fL4YrF0ht6JllpRDABuTAgVBoSoAUQAyv40Bh0PCuOYDABbPCyPFJfZpWh4yLSbBOUAAVVMa3OMi0TM0ADIdLlhORTIS3AA5djEkzmSw2exwsA4rCgT7-LygNgkAjkVbrEg0XHFMQAMVoDCyFI0JnpjMpYLomW0Dg11FxTV1+tAhspv3Y7XInW8ppYrNB4J0Ns1Mo0Iz12SNMl+4ymPtZMzm-stgcwttx5AJRJJB1eqj2OaOccpl2dzzJHy+AItVty5AAZqWXvq6AxmGwxIwtvp9NquHqsnLvsIwfDTFZlaAy4d6C2iu35DElERKA3BwCzAALSgCaTCUAAIyIRY0uRkDIMDaeTZnrYd8i73bvBH7a68I7AY+oE6nNBvghEHaLjSK6ypWCqmFuO57oeoBtB0XTHjI6SntI571o2ZJ-owob3rk+g4c+1ADmBw6gKO45ED+zatgRjBAcoIGvnuEHbruB4uDG3oMr6lIJsI8z2EAA)

### 💻 Code

```ts
// ------ GOAL ------

type Action = 'create' | 'update' | 'delete'

type Model = {
  id: string
}

type Payload<T extends Model, K extends Action> = (
  K extends 'create' ? T :
  K extends 'update' ? Partial<T> :
  K extends 'delete' ? Pick<T, 'id'> :
  never
)

type Mutation<T extends Model> = <K extends Action>(action: K, payload: Payload<T, K>) => void;

// ------ TEST ------

// test implementation model
type UserModel = Model & {
  displayName: string
}

// test payload receiver
const createFn = (model: UserModel) => {}
const updateFn = (model: Partial<UserModel>) => {}
const deleteFn = (model: Pick<UserModel, 'id'>) => {}

const implementation: Mutation<UserModel> = (action, payload) => {
  if (action === 'create')
    createFn(payload) // since action === 'create', type of payload should be UserModel
  else if (action === 'update')
    updateFn(payload) // since action === 'update', type of payload should be Partial<UserModel>
  else if (action === 'delete')
    deleteFn(payload) // since action === 'delete', type of payload should be Pick<UserModel, 'id'>
}
```

### 🙁 Actual behavior

- type of `payload` in `implementation` function is not inferred correctly even with `if` clauses

### 🙂 Expected behavior

- the sample should not have errors, meaning that types should be inferred correctly

**Comment by y-nk** [comment]
Found a workaround with type guards:

```
const isCreate = (str: string, payload: any): payload is UserModel => str === 'create'
const isUpdate = (str: string, payload: any): payload is Partial<UserModel> => str === 'update'
const isDelete = (str: string, payload: any): payload is Pick<UserModel, 'id'> => str === 'delete'

const implementation: Mutation<UserModel> = (action, payload) => {
  if (isCreate(action, payload))
    createFn(payload)
  else if (isUpdate(action, payload))
    updateFn(payload)
  else if (isDelete(action, payload))
    deleteFn(payload)
}
```

But this should obviously be simpler than that.

**Comment by nmain** [comment]
The extra guards are needed.  What if you called it like this?
```ts
implementation<"create" | "delete">("create", { id: "id" });
```

**Comment by y-nk** [comment]
@nmain thanks for the suggestion.

I'm kinda "ok" with the guards since it's just 3 fns, it won't create so much overhead in my final application... but since the target is to make a library, I'd like to keep it as simple as possible.

For the details of "why is it implemented this way?": I'm trying to mimic the blueprints of most of store managers out there already. Wether it's React, redux, VueX, MobX, the general idea is to have a single function (`dispatch(type: string, payload: any)`) to trigger the mutation of a store.

As I'm working on some library which should plug itself on any store manager, I wish to keep providing an interface which will make the consumers of my library having less trouble interfacing my library with their store.

**Comment by RyanCavanaugh** [comment]
See also #27808

**Comment by y-nk** [comment]
Thanks @RyanCavanaugh ; although it works "as intented" would you say it's rather a lack of understanding of TS from myself (totally plausible) or rather that feature should evolve to match expectations (as i'm not the only one asking this) ?
