### ISSUE TITLE
Change the DocumentFragment global vars type to an interface

### ISSUE THREAD

**Issue by chris-kruining** [microsoft/TypeScript#44057]
# lib Update Request

## Configuration Check

My compilation *target* is `es2019` and my *lib* is `the default`.

## Missing / Incorrect Definition
I want to add some static methods to `DocumentFragment`. But there is no `DocumentFragmentConstructor` interface.
Many types do have an interface for the constructor, which makes it easy to add static methods.
But other types seem to miss this.

I did not find any method of re-defining the `DocumentFragment` global var either (thank god).
So I am kind of stuck.

## Sample Code
go from
```ts
declare var DocumentFragment: {
    prototype: DocumentFragment;
    new(): DocumentFragment;
};
```

to
```ts
interface DocumentFragmentConstructor
{
    prototype: DocumentFragment;
    new(): DocumentFragment;
}

declare var DocumentFragment: DocumentFragmentConstructor;
```

## Documentation Link
_

**Comment by chris-kruining** [comment]
I also misjudged the impact of this request so I already gave it a shot in #44056

**Comment by RyanCavanaugh** [comment]
For reference, the repo to fix it in is https://github.com/Microsoft/TSJS-lib-generator

**Comment by chris-kruining** [comment]
should I close this issue, and open one there? or is this just a matter patience for me now?
