### ISSUE TITLE
Turn forceConsistentCasingInFileNames on by defaults (or a new flag)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#44053]
# Suggestion

## 🔍 Search Terms
forceConsistentCasingInFileNames, defaults

## ⭐ Suggestion

As my experience. It's annoying to build failed caused by `Case Sensitive`  (Even at Microsoft or Facebook). Especially It's works fine on some other platform.
(eg: Windows or mac for dev and linux for CI).

And I assume it's common to keep specifier completely match the file name, isn't it?

I thought it's ok to turn it on if there's no expensive effort. It's deserved to break.

**Comment by Kingwl** [comment]
And also in https://github.com/microsoft/vscode/pull/114334

**Comment by Kingwl** [comment]
Plus https://github.com/pytorch/kineto/pull/217/files#diff-f87d80149c474bc6ffd0f4c68cbad9fb4dc8085acefb6959610cdf180d138535R7

**Comment by hardfist** [comment]
It actually causes lots of problems, especially it works fine on dev mode(Mac is not case-senstive), but when it's build on production environment(which mostly linux server, which is case-senstive), it failed. and It's kind of hard to diagnose the problem.

**Comment by RyanCavanaugh** [comment]
This is already on in `tsc --init`, which is our "recommended" configuration. We don't have any inclination to break existing builds -- if someone needs this flag on, they can turn it on; if they don't, they won't gain anything from us turning it on for them.

**Comment by dmichon-msft** [comment]
Note that "forceConsistentCasingInFileNames" doesn't currently enforce that casing on disk matches the casing in your import statements, just that your import statements match each other. This comes up a fair bit when cloning on Windows vs. Linux.
