### ISSUE TITLE
overload interface method

### ISSUE THREAD

**Issue by UziTech** [microsoft/TypeScript#44050]
# Bug Report

### 🔎 Search Terms

overload interface method

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overloading interface methods

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIIBN3WQbwLABQyycmAFAPYgQBcyIArgLYBG0AlHWWAO4V2NWHZAF4AfPWZsoAbkLFS6StQFToAGmS9+koVE67pcggF9ChBFQDOYEpmh0MWKKNzy7SuKr2aWAfm9pdjciYmRgGGRuAE8ABwgKSJZRERFkACIGECwYUAh0dOD8ULDkKAgwBigQKJZA4XESZABqZBZjUrMSsoqqmrgWto7kLpMgA)

### 💻 Code

```ts
interface Adder {
  add(one: number): (two: number) => number;
  add(one: number, two: number): number;
}

const adder: Adder = {
  add(a: number, b?: number) {
    if (typeof b === "undefined") {
      return (b: number) => a + b;
    }
    return a + b;
  }
}
```

### 🙁 Actual behavior

error:

```
Type '(a: number, b?: number | undefined) => number | ((b: number) => number)' is not assignable to type '{ (one: number): (two: number) => number; (one: number, two: number): number; }'.
  Type 'number | ((b: number) => number)' is not assignable to type '(two: number) => number'.
    Type 'number' is not assignable to type '(two: number) => number'.
```

### 🙂 Expected behavior

no error

### Similar issues

#16951
#7230

**Comment by chris-kruining** [comment]
I've struggled with trying to override/overload a lot yesterday, and the this seems to be the closest somewhat satisfiable solution I can come up with:

```ts
interface Adder
{
    add(one: number): (two: number) => number;
    add(one: number, two: number): number;
}

type CustomAdder = Omit<Adder, 'add'> & {
    add(a: number, b?: number): number|((b: number) => number);
};

const adder: CustomAdder = {
    add(a: number, b?: number): number|((b: number) => number) 
    {
        if (typeof b === "undefined") 
        {
            return (b: number) => a + b;
        }

        return a + b;
    }
}
```

please correct me if I'm wrong, I'd love to learn more on this :D

**Comment by UziTech** [comment]
@chris-kruining That seems to defeat the point of typescript knowing what type of variable something is.

If you override a function like: [playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=13&pc=20#code/GYVwdgxgLglg9mABAQwCaoBQIKYC5FggC2ARtgE4CU+GUA7nPoaRZYgLwB8BxZ5A3AFgAUKEiwEKdFjB4eLcgBpE9RvL7V1FIcJFjo8JGkzImvCspIB+Mws3M+AHwwYStjR24PWiAN4jEQMQYYERaAE8AB2w4UJIOdnZEACJwVGxgGFlUZLYAoP9hIOLEcmwoEHIkV3cfLhREAGpEEh1igF8RfMCyiqqG5taRTt1hCAQAZygVDilMAEZlACZKIA)

```ts
function add(one: number): (two: number) => number;
function add(one: number, two: number): number;
function add(a: number, b?: number): number | ((b: number) => number) {
    if (typeof b === "undefined") 
    {
        return (b: number) => a + b;
    }

    return a + b;
}

const t = add(1, 2)
```

TypeScript knows `t` is a `number` not a `number | function`.

There should be able to be something similar for functions in an interface.

```ts
interface Adder {
  add(one: number): (two: number) => number;
  add(one: number, two: number): number;
}

const adder: Adder = {
  add(a: number, b?: number) {
    if (typeof b === "undefined") {
      return (b: number) => a + b;
    }
    return a + b;
  }
}

const t = adder.add(1, 2)
```

These two should be equivalent and `t` should be a `number`

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; overloads don't create any contextual information on method bodies and the inferred type of `add` is only
```
(a: number, b?: number) => (number | ((b: number) =>number))
```
which isn't the same as the overload set.

**Comment by UziTech** [comment]
So there is no way to overload interface methods?

**Comment by UziTech** [comment]
> the inferred type of add is only
> 
> ```
> (a: number, b?: number) => (number | ((b: number) =>number))
> ```

Function overloads infer the correct type. Why do interface method overloads work the same way?

[playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwCaoBQIKYC5FggC2ARtgE4CU+GUA7nPoaRZYgLwB8BxZ5A3AFgAUKEiwEKdFjB4eLcgBpE9RvL7V1FIaPDR4SNJmRNeFZSQD8phZuZ8APhgwkbGjt3utEAbxGIAxBhgRFoATwAHbDgQkg52dkQAInBUbGAYWVQktn9Av2FAosRybCgQciQXN28uFEQAakQSHSKAXxE8gNLyyvqmlpEO4REIBABnKBUOKUwARmUAJkogA)

![image](https://user-images.githubusercontent.com/97994/118134860-fe39d980-b3c7-11eb-889a-04ab4791b490.png)

![image](https://user-images.githubusercontent.com/97994/118134912-0bef5f00-b3c8-11eb-9071-381f6cf7a140.png)

**Comment by UziTech** [comment]
@RyanCavanaugh You marked this as a question but never answered it.
