### ISSUE TITLE
Alias type for indexing a generic object with transform breaking change in 4.2.2+

### ISSUE THREAD

**Issue by iPherian** [microsoft/TypeScript#44054]
# Bug Report

### 🔎 Search Terms

index generic with alias, alias generic

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.2
  - Still broken in 4.2.4 and nightly

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAaghgGwPIDMA8AVAfFAvFDAbQGsIQB7FAgXQG4BYAKCYGNyA7AZ2CgCM5O0fAG8mUKGwTkATgC4oAIgDm0iBHYKANEwC+UARI7cGzRigCu7FsACWHKEojAAYtPIBbAApuwnAHLkwADKABZwqgAmaACyMhDe5L5QEAAewOoRnFDCOlgAFGKG7rw27BAR8gm+AcFhkWigkJR8AhCaULGqVZxY2oziYD7ypBRU3TWh4eUN4BDN-ILtnfE+PUwAlPIA9ABUO2I7UAkR5iwQWRDSbtJQpVCN5yzSNmA8ACwAdABMHyl85jxOKczuUsndPgBGD4AVgOBygQWBakytyoFHMUFUYAQcDO9xC0HgyHQH1JOAe+nY7ECcFs9gA7jZgCE4f1DuNApN6g95q0lnFulhCPDxOIRs0ObUplEeVQFm0OgLVlh4dRWVBDnl6SEbCwQlBBBB3FkEDZSLceO4IHAuPjoJw4Fb1gctkwiag0JKudNZS1FoqusqcKJ+pinOZpOwiiUyhFCINEnRdEwmBSvXVpgAZAASQWSaQyWRy7QASrn8+l2Cicjh8Eh3Ey0GWgu1xVQc0EcAAyQr1xsd1tkZrNrAmIA)

### 💻 Code

```ts
type ValOf<T> = T[keyof T];

const base = {
  color: "green",
} as const;

function getFromPropsNotShared<MoreProps extends {}>(
  combined: PropsNotShared<typeof base, MoreProps>,
  prop: keyof PropsNotShared<typeof base, MoreProps>
): /**
 * Produces error in typescript 4.2.x but succeeds in 4.1.5
 *
 * Succeeds if you replace the ValOf<...> type annotation with
 *
 * PropsNotShared<typeof base, MoreProps>[
 *     keyof PropsNotShared<typeof base, MoreProps>
 * ]
 *
 * (which seems like it means the same)
 */
ValOf<PropsNotShared<typeof base, MoreProps>> {
  return combined[prop];
}

type PropsNotShared<LHS extends {}, RHS extends {}> = Omit<RHS, keyof LHS> &
  Omit<LHS, keyof RHS>;
```

### 🙁 Actual behavior

Says the value returned by getFromPropsNotShared() is not assignable to the annotated return type. Works if you replace it with a similar annotation without using the `ValOf` generic. `ValOf` is awfully convenient though especially for longer type expressions.

### 🙂 Expected behavior

Would expect it to succeed, because the `ValOf` alias that fails seems like it means the same as what works ( manually write out `T[keyof T]` ) but cleaner to write. Also because it worked in 4.1.5.

**Comment by RyanCavanaugh** [comment]
A shorter repro would be appreciated; I'm sure this can be cut down quite a bit.

**Comment by iPherian** [comment]
@RyanCavanaugh okay shortened it

**Comment by RyanCavanaugh** [comment]
This example in 4.1 just returns `any`. I suspect we were incorrectly computing the type in a non-error-reporting context and the error didn't get reported:
```ts
type ValOf<T> = T[keyof T];

const base = {
  color: "green",
} as const;

function getFromPropsNotShared<MoreProps extends {}>(
  combined: PropsNotShared<typeof base, MoreProps>,
  prop: keyof PropsNotShared<typeof base, MoreProps>
): /**
 * Produces error in typescript 4.2.x but succeeds in 4.1.5
 *
 * Succeeds if you replace the ValOf<...> type annotation with
 *
 * PropsNotShared<typeof base, MoreProps>[
 *     keyof PropsNotShared<typeof base, MoreProps>
 * ]
 *
 * (which seems like it means the same)
 */
ValOf<PropsNotShared<typeof base, MoreProps>> {
  return combined[prop];
}

type PropsNotShared<LHS extends {}, RHS extends {}> = Omit<RHS, keyof LHS> &
  Omit<LHS, keyof RHS>;

const p = getFromPropsNotShared({length: 0, color: "green"}, "length");
p.asdf; // no error
```

**Comment by iPherian** [comment]
@RyanCavanaugh Hmm I think that's just because it wasn't inferring the generic type parameter exactly, if you change it to do so it does error there:

[playground](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAaghgGwPIDMA8AVAfFAvFDAbQGsIQB7FAgXQG4BYAKCYGNyA7AZ2CgCM5O0fAG8mUKGwTkATgC4oAIgDm0iBHYKANEwC+UARI7cGzRigCu7FsACWHKEojAAYtPIBbAApuwnAHLkwADKABZwqgAmaACyMhDe5L5QEAAewOoRnFDCOlgAFGKG7rw27BAR8gm+AcFhkWigkJR8AhCaULGqVZxY2oziYD7ypBRU3TWh4eUN4BDN-ILtnfE+PUwAlPIA9ABUO2I7UAkR5iwQWRDSbtJQpVCN5yzSNmA8ACwAdABMHyl85jxOKczuUsndPgBGD4AVgOBygQWBakytyoFHMUFUYAQcDO9xC0HgyHQH1JOAe+nY7ECcFs9gA7jZgCE4f1DuNApN6g95q0lnFulhCFARs0ObUplEeVQFm0OgLVjhqKyoIc8vSQjYWCEoIIIO4sggbKRboCQuRzAgIlB3BA4Ox8dBOHBbesDlsmETUGhxVzptKWot5V1FThRP1MU5zNIHWxiqVyoRBok6LomEwKb66tMADIACSCyTSGSyOXaACUC0X0uwUTkcPgkO4mWhK0F2qKqPmgjgAGSFJst7sdsjNNtYEzpxhsLg8MB4BxOVweLOSqC7KCDCAsGyCRdlZ4se6zTfhF2qrZQNDCBDqJTM+QABlyeRvd4fUEf7UkMnkylU6gKDo7QKLe7D3iECjrCYYAfAIEQoLQ66XtS9LJFcMhAA)

```ts
type ValOf<T> = T[keyof T];

const base = {
  color: "green",
} as const;

function getFromPropsNotShared<MoreProps extends {}>(
  combined: PropsNotShared<typeof base, MoreProps>,
  prop: keyof PropsNotShared<typeof base, MoreProps>
): /**
 * Produces error in typescript 4.2.x but succeeds in 4.1.5
 *
 * Succeeds if you replace the ValOf<...> type annotation with
 *
 * PropsNotShared<typeof base, MoreProps>[ keyof PropsNotShared<typeof base, MoreProps> ]
 *
 * (which seems like it should mean the same)
 */
ValOf<PropsNotShared<typeof base, MoreProps>> {
  return combined[prop];
}

type PropsNotShared<LHS extends {}, RHS extends {}> = Omit<RHS, keyof LHS> &
  Omit<LHS, keyof RHS>;


const p = getFromPropsNotShared /* precise generic type param */ <{length: 0}>({length: 0, color: "green"}, "length");
p.asdf; // now error
```

Furthermore, given that:

```ts
type ValOf<T> = T[keyof T];
```

...the part that seems most strange to me is where in 4.2 (but not in 4.1), an error will be produced when `getFromPropsNotShared()` is annotated return:

```ts
ValOf< PropsNotShared<typeof base, MoreProps> >
```

but not when annotated with return:

```ts
PropsNotShared<typeof base, MoreProps>[ keyof PropsNotShared<typeof base, MoreProps> ]
```

Which is weird, right? Because the only difference is Replacing `T` in `ValOf` with the actual expression of the parameter. In my mind at least it seems like they should do the same.

Between both 4.1 and 4.2 there are correctly errors (i.e. not any) in your example if explicit type params are given:

```ts
const p = getFromPropsNotShared /* precise generic type param */ <{length: 0}>({length: 0, color: "green"}, "length");
p.asdf; // now error
```

**Comment by RyanCavanaugh** [comment]
@iPherian can you reduce this to a minimal repro of what you think the bug is and log a new issue? Thanks!

**Comment by iPherian** [comment]
@RyanCavanaugh okay opened a new issue #44095
