### ISSUE TITLE
Stale errors for a few minutes after switching branches

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#44066]
# Bug Report

### 🔎 Search Terms

performance vs code stale error switch branches git

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about code editing

### 💻 Code

Video demonstration: https://www.loom.com/share/b8accd596ea74f16ae41f524e6e1497f
TS server log: [tsserver.log](https://github.com/microsoft/TypeScript/files/6471744/tsserver.log)

1. Clone and checkout https://github.com/unsplash/unsplash-web/tree/typescript-stale-errors-a, branch `typescript-stale-errors-a`. This is a private repository but I believe some members of the TS team already have access from debugging previous issues. If you don't have access, please send me your email address so I can provide access (TS team members only).
2. Run `yarn`
3. Open VS Code and navigate to `app/routes/Users/components/UserStatsSubRoute/UserStatsSubRoute.tsx`
4. Wait for VS Code to finish initialising TS (no errors)
5. Switch branches: `git checkout typescript-stale-errors-b`

### 🙁 Actual behavior

Stale errors in the open file for about 2 minutes.

### 🙂 Expected behavior

- No stale errors.
- Some indication that TypeScript is updating in the background.
- The update shouldn't take 2 minutes. Restarting TS server only takes ~20 seconds in comparison.

Related: https://github.com/microsoft/vscode/issues/122928

**Comment by sheetalkamat** [comment]
@OliverJAsh The branch is no longer available. Are you still seeing the issue. If yes can you please provide the steps to repro
Thanks

**Comment by OliverJAsh** [comment]
@sheetalkamat Sorry about that, I've pushed the branch again.

**Comment by sheetalkamat** [comment]
@OliverJAsh thank you for the repro. 

While investigating this the root cause of this is that we poll 32 files at a time every 2 seconds. Since your project has 2000+ files being watched it takes a while for it to show up. At this point this looks working as intended.

**Comment by OliverJAsh** [comment]
Is there anything that could be done to improve the user experience? It seems quite extreme to wait this long for TS to fully update. To workaround this I have to restart the TS server very often.

Note that if I add these VS Code settings the issue disappears, i.e. there are no stale errors when I switch branch:

```json
    "typescript.tsserver.watchOptions": {
        "watchFile": "useFsEvents",
        "watchDirectory": "useFsEvents"
        // "fallbackPolling": "dynamicPriorityPolling"
    },
```

**Comment by OliverJAsh** [comment]
In that case should we keep this issue open to track the user experience issue?

**Comment by OliverJAsh** [comment]
I understand this is working as intended but I think there is still a usability issue here. Can we re-open this?

**Comment by OliverJAsh** [comment]
@sheetalkamat I just tested this again using TS 4.8 which includes https://github.com/microsoft/TypeScript/pull/48997, the fix for https://github.com/microsoft/TypeScript/issues/47466 which is mentioned above. Unfortunately the issue persists—it still takes 2 minutes for the stale errors to disappear. Do you think we could re-open this issue and discuss ways to improve the user experience?

As I mentioned above, if I add these VS Code settings the issue disappears, i.e. there are no stale errors when I switch branch. Do you think we could consider making these settings the default now that #47466 has been addresssed?

```json
    "typescript.tsserver.watchOptions": {
        "watchFile": "useFsEvents",
        "watchDirectory": "useFsEvents"
    },
```

**Comment by sheetalkamat** [comment]
4.8 fix was more towards linux which was one of the blocker to make `useFsEvents` default.

`useFsEvents` is default now with #50366 and is in nightly.
@DanielRosenwasser is looking to see if we could get this as experiment in vscode for 4.8 users but it may take some time to get everything together or not work out at all. Mean time nightly will give you that experience.
