### ISSUE TITLE
JSDOC: Enums treated as namespaces in @typedef

### ISSUE THREAD

**Issue by baybal** [microsoft/TypeScript#44062]
# Bug Report

### 🔎 Search Terms

enum
jsdoc
typedef

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSDOC

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/PQKhAIAEFMDsFcC24DeDECNoCcC+4RgBYAKAGMB7WAZwBdwBRda8AXlVPHABkBBPgFzgAjABpOPBtwZCATOJJduAVRVCAzKVylSoEJwiRaATwAO0ACbQAZqjsBrAJawLQpkmoA6PnwDc4akcAL2ghdCxsf3wAHwkuFHAnFzdmbykGfwB3RwtaAAswpAj-POhHAHM82kLMHCjwWMUuB2dXRlSVFX9sAEMLR3hqGuLwXHwALWhJg2AgA)

### 💻 Code

```ts repro
/** @enum {number} */
const Enums = {
  LALA: 1,
  LELE: 2,
  LULU: 3
}

/**
 * @typedef { { kind: Enums.LALA; size: number; } |
    { kind: Enums.LELE; width: number; height: number; } |
    { kind: Enums.LULU; radius: number; }} ZeZe
 */
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/3344988/118024253-4af9c200-b380-11eb-88ab-62fcba2be7be.png)

### 🙂 Expected behavior

Enums should not be treated as namespaces in JSDOC typedefs

**Comment by orta** [comment]
`Enums` isn't a type but a value, you want to use `typeof Enums.LALA` to [pull out that string in a type context](https://www.typescriptlang.org/play?ssl=9&ssc=40&pln=9&pc=23&filetype=js#code/PQKhAIAEFMDsFcC24DeDECNoCcC+4RgBYAKAGMB7WAZwBdwBRda8AXlVPHABkBBPgFzgAjABpOPBtwZCATOJJduAVRVCAzKVylSoEJwiRaATwAO0ACbQAZqjsBrAJawLQk+Yq2mSagDo+fADc4NSOAF7QQuhY2MH4AD4SXCjgTi5uZtCejMz+UgzBAO6OFrQAFlFIMcFl0I4A5mW0lZg4ceCJilwOzq7g7lleuSoqwdgAhhaO8NQt1eC4+ABa0CsGxCRAA)

**Comment by baybal** [comment]
> `Enums` isn't a type but a value, you want to use `typeof Enums.LALA` to [pull out that string in a type context](https://www.typescriptlang.org/play?ssl=9&ssc=40&pln=9&pc=23&filetype=js#code/PQKhAIAEFMDsFcC24DeDECNoCcC+4RgBYAKAGMB7WAZwBdwBRda8AXlVPHABkBBPgFzgAjABpOPBtwZCATOJJduAVRVCAzKVylSoEJwiRaATwAO0ACbQAZqjsBrAJawLQk+Yq2mSagDo+fADc4NSOAF7QQuhY2MH4AD4SXCjgTi5uZtCejMz+UgzBAO6OFrQAFlFIMcFl0I4A5mW0lZg4ceCJilwOzq7g7lleuSoqwdgAhhaO8NQt1eC4+ABa0CsGxCRAA)

Exhaustive search will not work that way

[Playground Link](https://www.typescriptlang.org/play?ssl=59&ssc=30&pln=59&pc=36&filetype=js#code/PQKhAIAEFMDsFcC24DeBnALgJwJawOYC+4IwAsAFDQAeADgPZYbgDG9sm4AhgDbRMBRBMgC8qSuFZc00APr1acaABMAXOADkAYWnRwCpco0AaCeBk8AZrIzRMsy1xw91GgMrQr4W50fP4WNAmZgBGXBi2WACergBC4ZFR4AAW0LwYycEUkmER-FGyLLgYOCy8cQn5KWk8GazFpbxZOZXRDk48aFyW0BV50eB+nd1BptnguYnt-oF9iYMdAaNmLAGBsBiuAPIAbvw89FxGY5K2iIpY4Uvbe1ip4c3e0Of8V4GFDWUumgAqzxdvPRFHAlL4aSiESiUUAQGDCVDCEL8YikShsDjMLT0Hg-KKKNDgMQoMw-AQADR+6gADCdwAAZACSADkANLqACMtIAIgBBH489QAJm5fIE6gAzLSeXSBAAlSngAAstK0AFVZbKBEytABNdQAVlpsS2WxlPKZ6gAbBCoRRoWAJLCMHiVNBLKhxOMZLhyuZsHh8ABuMxcFglPbqEL0bFpWDB8a8fgYNDqAAUAGtoFF6O7nYoc9w+IJhABKADaAF145JaFwovh1Ij+NXwDxpBg3FFYCx1FzwtAW4h2BkeFE+xguI2kEisC3Jm56D3wE3Z6EElooiw+Cnl9Pm2uIjz8L1d4gZ3OEgA1bET49Ts-78aTLRrOCbU-nsy12Cea+1Lh3h+j41lwP48C+WDrO+K4tvQ8AYLQ8EQVB96fuMZwAhg1xAau4ylCwOBqH6uAEC2bbQXuuGSDwBCoY+xDEFy0A7KU0COuQdoUDCjpQHmrruigKB8eofEFliOIumgAB0jKsoQxDiUgsBMZYeAgjg7B0ng6Y8ZAfHKG6qBCS6IkumJ2K4viUnGqaAjmsYTxYLAXDRKomAkfglbyeAimIMpbpqSU7CxNGPC6fphmCcJ3hme64mWXYUlqhqWq6g5qyQXALAxO5Abeb5-mqbA6nsMhWVROFLoGQJxmKKZ+ZxRZklSby-IOTwOCICCqgrvl2JKSpgUacp4RcJVijVUZ0WiY1ElWa1AjgH1PADQFxVBSNtjjfxU0mTFDU+U1VnSnKPxLQp-V+YN63DTyRYYOxtrcdkTpVZFqBlpmSR4OAX0FkxLEsNAFbqAV10lbAWmwOm4AAD6HStV1rRDIXYnDCOrUVEPjlw6Ng8jG1ld2STw-jWMbeOeik5dhVDewd1JgxGNI+Tw1aZgj2cc9JBQLWlzIIJBmA70AOscY1V07Aqhk5L7PMN5tBYAoaCc5Y8Ddht4A-FwIR8LK9AAO7gKmKDgELYtmwTw1LSWnqSOinBsJ0hLgJWZgwrxLqoH9s2Y7LOCYCiHHUdAzBfWYliMMbX3gD9Es3ewtvEuM9vsJwk1iPHEOfVmFZmKnGLgG+AyZ8xrE51Eecp+YBsgiwyTG9VUl8Un+eSFIMjG-FzWySyJbqMn7dD6w2LSYhaDJCbxdRO1OueK4PzJAHscErjHXQxohAlm3Q8hIEXA6dXkjEGUnept3Vk2WaTL93bw+p50Unj5PKDT7PSLfBoi-L8vuNRtiDlQLKBSNIbgjlnLRBMJECBMQm7QJclEMsTJKKpmniWCsxBt5H3bnvNIh974n10F3I6iUTrylvoPe+I9H7PynhsaI7956-CXgSX+rYA7MALImLAaBAGwGAckUBoFuCQTrCYQsSYdxlnAB7PSXsUAZizAWGaEjixIHLBgkgwBUH0KiCWKSiAuC0FTFwEQAA+bhGAhBIDLFwCstsMFYKoRMfe+Dh6ELPhfRKyVNTah1BQne7cnZj3gBPOh2AZ6tjnp-b+rDV6sFfMTahSk+ECKEQkzKSS0A4HwLAcR2TcnqCbhldY2Ut6BJyK4wJHi9DnxIdJVqPIAnYIfiEsJr9dGMJiSwleYDlCjWSX5VJID4kdS6pw2gQVxFjO6pbSwUkZkYHKS0lxeDqkd1qV4hpopmnOOCU-UJL835RI-gvHpbD+m2EGbAYZGQ9DT3AIgUJzBEB6FxgAKTcFsJkZt+zEQDOIy5J4fxG0pqmWRfFUCUyDjoiJJYSzLOcbgg+6zqpcHgLUAeFTqFtKOZ0k5TCNBMnoBkAMjzwj1zsJvJx7i26QnGPSyQgQsJORxRCIAA)

**Comment by orta** [comment]
This would need some sort of `as const` or narrowing in JSDoc enums, a JSDoc enum is not the same as a [TypeScript enum](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#enum).

**Comment by baybal** [comment]
> This would need some sort of `as const` or narrowing in JSDoc enums, a JSDoc enum is not the same as a [TypeScript enum](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#enum).

How to do it?
