### ISSUE TITLE
Conditionally inferred class type loses private properties

### ISSUE THREAD

**Issue by Pmyl** [microsoft/TypeScript#44067]
# Bug Report
Conditional infer of a class type is not the class type but only the public interface of it.

### 🔎 Search Terms
infer, inferred, conditional, private, class

### 🕗 Version & Regression Information
4.2.3

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAggNnAysATgSwHYHMDOAeAFQD4oBeKAbygG0BrCEKTKekAewDMoCBdALig5UmLAG4oAX1EBYAFChIUAMJsMwAIaYIKQiXIEoEAB7AIGACY5YCZOmz5MHbVABC6nBGJQA-JUHD7AQJxACN3CAE3D2DJKAEMCAA3bRlZOQBjOHcrGCUsnCsKOSgoMABXELg0dKhzNkQ2AFsIYAALEQAKdQA1dTgyiP87LABKASFhymKSqBQWspQMKDa0HAA6AH06gElgAAV0RPVTOBAu3v6IEdSSiTlpsEPj6C22XYO0I5Oznr6B8YCowBkyKshms3miygAAMACQUX6XCSvBLQm6SOR3NKyTLZWB5bK2ERWNCNMBwCDNNQ5GyA-C5fI4Eig8HlSrVWr1JotdrYYEiMhQADkdQSQtSWLkAHopVAAKIoFBsFBQADuaDaMIObEgKFAwte7ye3yFTCsjVWOAFzAU0CFVDqDWaKz5UDKGFoGDYqow4gkppCZWAEIAjmU0HNzEwlrbhQzskLodLZQRWtBY6to05FRAo+oLIJWmwynAoyFoPGChlVEIIcAFhhKzgotByB10qoNFoUAIVGpNAkdE2ifYiGN8YyyCQO-3u2swh5UkA)

### 💻 Code

```ts
type AllStrings<T> = { [key in keyof T]: string; };
type Container<T> = T extends AllStrings<infer BaseT> ? { strings: T; base: BaseT; } : never;

class AClass {
  public doSomething(aValue: string): string {
    return this._doItPrivately(aValue);
  }

  private _doItPrivately(aValue: string): string {
    return `${aValue}_done`;
  }
}

class AClassStrings implements AllStrings<AClass> {
    public doSomething: string = 'done';
}

// Error with `Property '_doItPrivately' is missing in type '{ doSomething: unknown; }' but required in type 'AClass'`
// The type is inferred and should be AClass
const returnAClassBase = (container: Container<AClassStrings>): AClass => container.base;
```

### 🙁 Actual behavior
Errors with `Property '_doItPrivately' is missing in type '{ doSomething: unknown; }' but required in type 'AClass`

### 🙂 Expected behavior
Should infer the class type correctly and not give error

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Inference is structural and there are no structural members from which to derive the desired inference. To put it another way, the `implements AllStrings<AClass>` clause *has no effect on the type of `AClassStrings`* and any expectation of different behavior based on that `implements` clause apart from errors on the class declaration itself is incorrect.
