### ISSUE TITLE
TypeChecker does not resolve module path in `require()`

### ISSUE THREAD

**Issue by LinqLover** [microsoft/TypeScript#44077]
# Bug Report

### 🔎 Search Terms

- `require()` with path
- TypeChecker `require()` any

### 🕗 Version & Regression Information

The issue was reproduced in v4.2.4 and 4.3.0-beta.

### ⏯ Playground Link

https://replit.com/@LinqLover/typecheck-js (The example uses `TypeChecker` from the Compiler API to reproduce the bug, but I could watch the issue as well by hovering the variable in VS Code.)

![image](https://user-images.githubusercontent.com/38782922/118161537-fefe5a00-b41f-11eb-9596-80825752e2d1.png) 
![image](https://user-images.githubusercontent.com/38782922/118161591-0de50c80-b420-11eb-9fc6-245da88e1ddd.png)

### 💻 Code

```ts
var vec3 = require('gl-matrix/vec3')
var myVec = vec3.fromValues(1, 2, 3) // $ExpectedType vec3
```

### 🙁 Actual behavior

`myVec` should have the type `vec3`.

### 🙂 Expected behavior

`myVec` has the type `any`.

### 🔀 Known workarounds

- Use `require('gl-matrix').vec3` instead, i.e., don't pass the module path to `require()` (see second screenshot above).

### 🔍 See also 

- [StackOverflow: How to use the TypeScript Compiler API to type-check modules imported using `require()`?](https://stackoverflow.com/questions/67521527/how-to-use-the-typescript-compiler-api-to-type-check-modules-imported-using-req) /cc @dsherret

**Comment by RyanCavanaugh** [comment]
`gl-matrix` ships its own types, and those types don't define `gl-matrix/vec3` as a legal entry point.

**Comment by LinqLover** [comment]
> `gl-matrix` ships its own types, and those types don't define `gl-matrix/vec3` as a legal entry point.

I fear I don't get the point, the code runs as expected both in JavaScript and TypeScript? Only the typing information is missing ...

**Comment by LinqLover** [comment]
Do you mean that the type definition of `gl-matrix` are erroneous as they don't define the same structure as the vanilla JS implementation?

**Comment by RyanCavanaugh** [comment]
If `gl-matrix` intends for you to import `/vec3`, then yes, they're missing information in their .d.ts files to allow that

**Comment by LinqLover** [comment]
Thank you very much, Ryan! I have created an issue in the gl-matrix package since from this side everything is fine.
