### ISSUE TITLE
HTMLElement.setAttribute's parameters are marked optional; they are not

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#4407]
`lib.d.ts` defines HTML.setAttribute with a signature of `(name?: string, value?: string)`. Neither of the parameters are actually optional and will cause runtime errors on at least Chrome and Firefox.

**Comment by mhegazy** [comment]
PRs are welcomed. here is some documentation for adding new types to lib.d.ts: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by LPGhatguy** [comment]
I've submitted a PR (as noted just above this) to the TSJS-lib-generator project.
