### ISSUE TITLE
`never` does not work correctly if typing not explicitly declared

### ISSUE THREAD

**Issue by erencay** [microsoft/TypeScript#44072]
# Bug Report

### 🔎 Search Terms
never, implicit, explicit, null check

### 🕗 Version & Regression Information
4.2.4
4.3.1-rc

This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&ssl=1&ssc=1&pln=42&pc=6#code/GYVwdgxgLglg9mABFAFgJzgdwLIFMAUAlAFyJi4BuuaiA3gFCJPLpZm6aICiaGa+AIgBylagEIBhANz0AvvXoQEAZyiI4AIwBWiALx1GzVBhy4ANHJn0A9NcRC43XnDT18RPQD4DzRABtcNQBDUlpEAA9SMBAAWw1qRFlEAB8yED8-PUQAKQBlAHkhADoAByC0ZQIBaIzJK18YYER8MSDCH18jVlMiGV95QyYlMFVEAE8soKLwqURbRHyAaTE5Ql6FefyS5R2V93bdbwZfAODQiKjY+Jok1JrM-TzC0vLKwXu6hQamlraOzvU2iKxiweHW-S+zGGowm+imMzmdgAKrkAEwAVgAzABGUj5bS4aCIGDKRAlOA7GAaPwTADk91pRVW6w2dgcTj4zUayDGJVwABNELhwiU-DAIDAoDTCG4PId-v5AogQnQLmk4glbmkMlknsUyhUqh9pJCmNzfu1jgDENC1JotKjziDTKQ5d5yFQbll7X1rfbUcDumCTRDBjaVGpYcrprNNotmdIgA)

### 💻 Code

```ts
function throwMe(): never {
    throw new Error("Never!");
}

const obj = {
    throwMe,
};

// No Error
(() => {
    let a: { x: number } | null = JSON.parse("null");

    if (!a) {
        throwMe();
    }

    const y = a.x; // OK!
})();

// Opsss!
(() => {
    let a: { x: number } | null = JSON.parse("null");

    if (!a) {
        obj.throwMe();
    }

    const y = a.x; // TS2531: Object is possibly 'null'.
})();


// No Error (if typed explicitly)
(() => {
    let a: { x: number } | null = JSON.parse("null");

    if (!a) {
        const obj2: { throwMe: () => never } = obj;
        obj2.throwMe();
    }

    const y = a.x; // OK
})();
```

### 🙁 Actual behavior

Compiler thinks the variable could be possibly null, where obviously it is not.

### 🙂 Expected behavior

Compiler should able to tell the variable is not null without the explicit type declaration for `never`.

**Comment by MartinJohns** [comment]
Duplicate of #36753.

Simple workaround: `throw obj2.throwMe()`

**Comment by erencay** [comment]
If this is a known limitation I should use the workaround for the moment instead I guess.
