### ISSUE TITLE
Type Hinting, object key to array item validation for Array Items of Fixed base Types

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/TypeScript#44085]
# Suggestion

When dealing with arrays one can define the types for specific items, however,  there is no meaning for the items,
i.e type args = [string, string, string, string], it would be great to be able to define type hints for auto completion and potentially 
soft error mapping. So something like this type args = [nethost: string, netshare: string, username: string, password: string]
This now gives the array items more meaning, that just the word string,. It further can be used to type match mappings of objects to arrays, to ensure that parameters are in the correct order. A question mark afterword's could be mean not strict or optional key to name array position validation.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
