### ISSUE TITLE
Suppressed bitwise operator (OR)

### ISSUE THREAD

**Issue by corbane** [microsoft/TypeScript#44086]
# Bug Report

### 🔎 Search Terms

- is:issue is:open Bitwise 
- is:issue is:open binary operator 

### 🕗 Version & Regression Information

tested with all versions of the playground

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.2.3&ssl=6&ssc=1&pln=1&pc=1#code/FANwhgTgBJFgnlAvFA8gIwFYFMDGAXAOjAGcSBLAcwDsoAKAbQEYAaAJhYGYBdFqAbyi4AriXwB7ALYAuKACJCiuVAC+ASmChIUctQAm5XNhLI0WPEUrZ8qAO7UAChHEAHbBHzwAcmEnH6sAhqhABm5AA2+O70dADWasgAfFCxyEgoAMr4ELqUcTAmYNTwAD4ADGoa4NAuzm4e5P4oGDgEhFY29k6u7p4+fiZ0gfDBYZHRdHEJSMmpAITpUFk51HmppDDF5ZXAQA)

### 💻 Code

```ts
var n = ("1" as any|0) + (undefined as any|0) + ("..." as any|0)
```

### 🙁 Actual behavior

```ts
var n = "1" + undefined + "..."; // -> "1undefined..."
```

### 🙂 Expected behavior

```ts
var n = ("1"|0) + (undefined|0) + ("..."|0) // -> 1
```

**Comment by MartinJohns** [comment]
You're not using the bitwise operator in your code. The right side of the `as` operator is a type, and in your case this type is `any | 0`. You were probably looking for `("1" as any) | 0`.

**Comment by corbane** [comment]
oh I see, you are right.
I did not expect the transformation of code based on types
(Sorry)

**Comment by corbane** [comment]
However, the behavior is strange because `<any> "1" | 0` works.

**Comment by MartinJohns** [comment]
> I did not expect the transformation of code based on types

The types do not affect transformation. But the types are erased. You have `"1" | as any | 0`, and as I said your type is `any | 0`. So after removal of the TypeScript specific code (the `as` operator and the type `any | 0`) you simply end up with `"1"`.

> However, the behavior is strange because <any> "1" | 0 works.

Not strange. This form of the type assertion operator just acts on the next value. `<any> "1" | 0` is parsed as `(<any> "1") | 0`.

**Comment by corbane** [comment]
I understand !
I wrote this:

```ts
type AnyOrZero = any | 0
var n = "1" as AnyOrZero
```

Thank you

**Comment by MartinJohns** [comment]
Exactly. :-)
