### ISSUE TITLE
Type is lost for unknown reason

### ISSUE THREAD

**Issue by carljohnesan** [microsoft/TypeScript#44088]
# Bug Report

After I got inspiration from ocaml, I decided to implement variants and pattern matching in typescript for my daily workflow.
I wanted to make pattern matching typed as much precise and with as much type inference as I possibly could.
But when I almost finished and decided to write unit tests for my `match` function, I bumped into one, still unsolvable to me problem - type of matched value is lost somewhere, despite all well-thought typings. 

### 🔎 Search Terms

Type is lost

### 🕗 Version & Regression Information

I started seeing this bug today with latest version of typescript

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAXAngBwQERCVAFWiAllBADwAqAfPALzwDeAsAFDzwDau8hAdvANYhkAewBm8cgF0A-AC54WHPhhESFTpMosAvixahIsBCnTx8iRCBg8K1Gizbl4IAB6WewAM7weAVwC2AEZW8NIObBLwsuGOzm4gHt6eiDC8AOahMRFO0awRsa7uXvCBwsIQIFB8YXn5sbl12XFFSchB5Zm1jZEN3WyKeATEZFR6zAbQcEhoCADCUJ4gAOK+sMC2tPAAFFvAUIhQ8uQAlLTUpeWVPKcAPiVlFVX64JPGM-DziwBKIJ6+EIgKAAaeBfOzbXb7Q4SU40ahfW6gsYTIzTUyzYRwACy+zAAAtNlsAG4kXwgeRVZAg1D7SzWCk8ZCw84PK7Il6okwIHGIfEAQT2qDp5DxhE8FAAaqSQCDyABRNwwKBgSzAKUQMngph5QpKlUYKHE6VHdVk45HBUpZWq00gHTswxTLnwHn8wV0yXS2WWvU26Va8K660Gg7SI0a8kSW3miQ+60gNXS8L+XF4rZZRCizzyV14gVQIVWEViz0R72K+OJiOUIFZEkRk1erJgTEgXPyDHY1PhGMXR48e3MZ6Ot6mXOfEAAdUImfMdJs5BBYM27HCc6sC5r4QAdLuJys1rZ2JJa3kJz8-gDgaCtMxJA7XmjuamJ9PM-nCzBS2Ty1aVQnbVlH5EF8axwVXPJcw-D1yEA2MK3-KtNVPNhd23fdVhgdZ5QQv1q2PFCPgWEAL3+QEcL-PCfwkYDQJ4W97yHcYOSdd5x2I69l3sPI7nYxY3zzd0rGvSkl1vNheJfYiBPXaxONvYdH2dPiQAAMQXXMAK9GiQBAsDaHCAAybYsnTLo2BpCwN3kWSNNTLTq0I-I0LSTCvD5DxSIBeQIL6NCMMPchNKQkBKAIrJ8nPX4yIoYK4PIWiwIi+BGPyZkXSk-iZzxWzYvskKgN0ujxPgY4jJMroKDjRDbUoMzGigISYBzVNoOEoL8vi6qqNCpyIhctzPA84AvMQHzktQvdiIPLCqtwhzNXC8yIiiy9yO6haZR0vT6OS1KInSlSBLar8Ot5PFNt-X1Lu24qewfTk2My355JXFT5JBND3sXG9j0YlhXFQTFEHgFEplEXweBVQhhD4FNzvk+r4HrMkjkIsBiOzbYoAnFrzondSPvgAB3QgIGADGsIZJkzgy-HMY+lgYy+MYWBbHhkngYRAgAK02eh4FEMp5AAciF4QRfgXQmPh-Etm5nmQS2AASEEAH10t8+AAHptfgSc8WQeAAAMFeN+A8QWeAqm4fxUAgQgwBnE3KXNrkajYZWtjVkEFdp9nPEubcIGENItmNgBJUHYZFkHKYQYnRXxZHpW4bxM32bcAB0eGN33eeOY5T0kMrmCAA

### 🙁 Actual behavior

`obj` has an implicit `any` type

### 🙂 Expected behavior

`obj` have same type as `match` first parameter

**Comment by RyanCavanaugh** [comment]
This repro doesn't seem to point to any defect. There's two overloads for `$` at that point and we don't seem to have enough information to select one with which to contextually type the function expression argument; this is expected.

**Comment by carljohnesan** [comment]
I get, it's just how typescript works, closing
