### ISSUE TITLE
Assignability check fails on compatible types.

### ISSUE THREAD

**Issue by h-joo** [microsoft/TypeScript#44089]
# Bug Report

Assignability check for types which has same property with different types, yet where the properties are still assignable (e.g. assinging `null` to `string[]|null`) stopped to work.

I wasn't certain if this was an intended behavior or a regression.

### 🔎 Search Terms

- assignability
- generic
- interfaces
- extends

### 🕗 Version & Regression Information

- Start to appear from 4.3.1-rc. All other versions work. 

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210514#code/JYOwLgpgTgZghgYwgAgIIB4AqA+ZBvAWAChlTkZgIAbAE2QC5lNkAfZEAVyqoG5iBfYmACeABxRwAzpOABzEJgD2yALxp0ksFFCyA2gF1sfIqEixEE6XIWKAogA9IIGhDoRHEZ5PWbtIPYb4gkTEMBwgCGDAiiDkisoAFACUDOqc3LiEJGRQEGAcULFZZCXklLSp6VTEJfzGwQD0DcgAqpKuyGDK8MBUyDIRKADMAHSjQ8QIMZrIcKlSMvJKqnGKycZNyADKYHBQYN5d5HC95FCKALbIACxjIwCMALRQCJPTYMgARvNWS3Yezg6ahg8XWQA)

### 💻 Code

```ts
interface A<T> {
    field : T | null;
}
type assignTo = A<string[]>;
interface assignToExtended extends A<string[]> {}

function foo () : A<null> {
    return {
        field : null
    };
}

// This consistently fails on all versions. (and I think this is intended)
const a : assignTo = foo();

// This used to work, but now starts to fail from 4.3.1-rc
const b : assignToExtended = foo();
```

### 🙁 Actual behavior
`A<null>` is not assignable to `assignToExtended`

### 🙂 Expected behavior
`A<null>` be assignable to `assignToExtended`

**Comment by whzx5byb** [comment]
I don't understand why `const a : assignTo = foo()` should fail. I think it is a bug.

Consider the example:
```typescript
type Nullable<T> = { field: T | null };

declare var a: Nullable<number>;
declare var b: { field: null };
declare var c: Nullable<null>;

a = b;
b = c;
a = c; 
// ^Error here.
// Why it is an error when b is assignable to a, and c is assignable to b, but c is not assignable to a???
```

**Comment by RyanCavanaugh** [comment]
This seems odd; I believe we should have fallen back to a structural comparison here when the type parameter check failed.

A workaround is to write:
```ts
function foo () : A<never>
```
which should have identical semantics but doesn't hit this bug.

**Comment by weswigham** [comment]
#40358

**Comment by RyanCavanaugh** [comment]
Duping to #40312. The root cause of the break now is I believe the improved type alias preservation, which "lets" us use the more efficient (but ultimately incorrect) type parameter check rather than a structural check.
