### ISSUE TITLE
`() => string` and `(): string` don't match type

### ISSUE THREAD

**Issue by SephReed** [microsoft/TypeScript#44098]
# Bug Report

[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MAUBKFA+GAiBEPAbgChRJYAjAQwCcAudLZXaOgSzAHMV5EYNCDADyAWw5QAPFACeABwCmIOPxAAafLQBeebMSA)

```
const foo = () => "foo";
const bar: () => string = foo as Omit<typeof foo, "baz">;
```

> Type 'Omit<() => string, "baz">' is not assignable to type '() => string'.
>  Type 'Omit<() => string, "baz">' provides no match for the signature '(): string'.

### 🔎 Search Terms

* `() => string` and `(): string`
* Omit breaks function type match

### 🙁 Actual behavior

A `() => string` has a non-existent property omitted can no longer be assigned to `() => string`

### 🙂 Expected behavior

It's the same exact type, nothing has changed by omitting a non-existent property.

###  Actual use case

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIGEAWdTIN4BQyxyAFAJQBcyAzmFKAOYDcRJkdF1dDILbxeHWgB+LrXpNWAXwIEEAGzg0ayLDhAAJAPYKAJtHwDkABwCuAIwXAEyRhDDIE2UBSMkPT7SDrJtZsGoMFxBkAF4yNzCAPmQAIhhtbTjyZGU0kABPVk8SKAczKFD-R3SAeQBbYDAAHjBMkwhtGD8AgBp4oUgoOOickllZeW9fTF0DKHDkEAgAdzUQnX1oClYx5agAOmcNVeIAen3kCzg9ZGgobSgCdYntkM2ulfJmZEO7JLOLq5vx6HuNJsOGBVgQgA

**Comment by MartinJohns** [comment]
Possibly the same as #44089?

**Comment by DanielRosenwasser** [comment]
Mapped types like `Omit` drop signatures from object types. As far as I can tell, this is working as intended.

**Comment by SephReed** [comment]
@MartinJohns maybe... they seem like they could stem from somewhere similar, though they aren't the same.

@DanielRosenwasser if this is working as intended, is there any way of omitting a property from a function with it remaining a function?

So far, the best I've found is to just re-add the function signature:
```
const foo = () => "foo";
const bar: () => string = foo as Omit<typeof foo, "baz">;  // doesn't work
const qux: () => string = foo as (Omit<typeof foo, "baz"> & (() => string));  // works
```

**Comment by tjjfvi** [comment]
> if this is working as intended, is there any way of omitting a property from a function with it remaining a function?

You can use something like
```ts
type OmitWithFn<T extends (...args: any) => any, K> = Omit<T, K> & ((...args: Parameters<T>) => ReturnType<T>)
```
But if you need overload or generic support, you'll need to manually re-add it.
