### ISSUE TITLE
thisType is not narrowed

### ISSUE THREAD

**Issue by Zzzen** [microsoft/TypeScript#44091]
# Bug Report

### 🔎 Search Terms
thisType is not narrowed

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/MYGwhgzhAEBCkFNoG8CwAoa0BmAKAlChllgJbbS4AuAFqTKQHYRViPAID2FAIgIyE0mElmCdmVaBABc0WvWgBeOXQgBuYiKkA6bHwIbhI+RF378hkQF9NN9HYyhIMfkWF6CKO1aA)

### 💻 Code

```ts
class Base {
  f() {
    if (this instanceof D1) {
      const s: this = this;
      s.f1();
      this.f1();
    }
  }
}

class D1 {
  f1() {}
}
```

### 🙁 Actual behavior

compiler throws an error on `s.f1()`: `Property 'f1' does not exist on type 'Base'.`

### 🙂 Expected behavior

should have no error.

**Comment by RyanCavanaugh** [comment]
`instanceof` won't allow arbitrary cross-type coercions. If this is the behavior you want, write
```ts
class Base {
  f(this: Base | D1) {
    if (this instanceof D1) {
      const s: D1 = this;
      s.f1();
      this.f1();
    }
  }
}
```
Note that `this`, the type, does not change meaning depending on the narrowing context it's in

**Comment by Zzzen** [comment]
Thanks! Now I get it. Type is somehow immutable. If `this` is used as an expression in `typeof` (which I'm trying to implement in https://github.com/microsoft/TypeScript/pull/43898), it should get narrowed. right? 

```ts
class Base {
  f(this: Base | D1) {
    if (this instanceof D1) {
      const s: typeof this = this;
      s.f1();
    }
  }
}
```

**Comment by RyanCavanaugh** [comment]
Yeah, `typeof x` is a "value position" for `x` and all value logic should apply there
