### ISSUE TITLE
Compile on Save cannot be disabled

### ISSUE THREAD

**Issue by theqwertman** [Microsoft/TypeScript#4410]
I've tried the following:

* Put `<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>` in every `PropertyGroup` in my `.njsproj`
* Uncheck "Compile on Save" in the GUI
* Set `TypescriptCompileOnSaveEnabled` to false everywhere it appears in my `.njsproj`
* Set a combined output target in the settings GUI and file

yet whenever I save my `.ts` files, `.js` files are generated. The only way in which I succesfully disabled compilation was by setting `EnableTypeScript` to `false`, but this is not an adequate solution since it reverts Intellisense to Typescript 1.0 syntax.

Visual Studio Community 2015 14.0.23107
Node.JS Tools for Visual Studio 1.1.30716.01

**Comment by danquirk** [comment]
It sounds like you might need to file this specifically against NTVS at https://github.com/Microsoft/nodejstools. If you're having this problem with other TypeScript project types we can re-open this issue with an appropriate repro.
