### ISSUE TITLE
Non-BMP unicode characters in source code break VS debugging

### ISSUE THREAD

**Issue by rotemdan** [Microsoft/TypeScript#4412]
A single non-[BMP](https://en.wikipedia.org/wiki/Plane_%28Unicode%29#Basic_Multilingual_Plane) character such as "𨭎" (cjk unified ideographs extension b u+28b4e) in TypeScript code prevents debugging in VS. Hovering over a breakpoint would show `no symbols have been loaded for this document`. This will also happen if the character appears in a comment block and "keep comments" is set to true.

The following line:
```ts
var t = "𨭎";
```
would compile to:
```js
var t = "ð¨­Ž";
```
Attempting to debug the generated JS file directly would partially work (at least in my basic test) but would break current line highlighting correctness. During debugging the line would show as `var t = "������";`. An editor exception may also occur.

I found this when trying to investigate a project that at some point mysteriously stopped hitting breakpoints in the debugger (but otherwise compiled and worked correctly). Source-mapped debugging for it did work in Chrome and Firefox, and intermittently on IE11 as well. It turned out it contained a unit test that had strings with inline non-BMP characters. Removing that test fixed the problem.

(The problem happens in both VS 2013 and 2015)

**Comment by danquirk** [comment]
Is this with the latest TypeScript installed?

**Comment by rotemdan** [comment]
Currently it's with 1.5.4.0, but it also happened with several (or even all) previous versions, as far as I can remember (It's a large project, and debugging stopped working about a year ago, probably around the time I introduced those characters into the code. For a long time I had no clue why it was happening and I thought it was related to https://github.com/Microsoft/TypeScript/issues/556).

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look,

**Comment by sheetalkamat** [comment]
Investigated this and it seems like bug in IE where it doesn't give source file contents to debugger correctly. Have routed this forward.
