### ISSUE TITLE
Protected static properties cannot be accessed from outside functions despite contextual `this`

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#44128]
ts stable and canary

[Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAECSAuBTAttA3gWAFDVwBwCcB7JYJAE2gnjHgEthoAzIo6AXmgAYBubXaIRKIyiSizade-XAHNE8ABQBKdDIG54ACzoQAdBL44NuBCgOsjAgL7ZbWbEwCuAOzJ0iL6PKXbdALjgkZFVMY00dfUN1IPNorGsgA)

```ts
class Item {
   protected static foo = 0;
   protected foo = 0;
   get() {
       this.foo;
       Item.foo;
   }
}

function get(this: Item) {
    this.foo;
    Item.foo; // Property 'foo' is protected and only accessible within class 'Item' and its subclasses.(2445)
}
```

`function get(this: Item)` is allowed access to protected instance properties, but not static ones. 
Expected access to either both or neither.

**Comment by RyanCavanaugh** [comment]
@pushkine I've asked you twice before to follow the template and will ask again. Future reports not following the template, even if facially valid, will be closed without elaboration.

https://github.com/microsoft/TypeScript/issues/43323#issuecomment-804238174
https://github.com/microsoft/TypeScript/issues/43306#issuecomment-802948331

**Comment by danay1999** [comment]
Looked at the issue with Wesley and found a change made back in 2018.  According to the comments here https://github.com/microsoft/TypeScript/pull/24645, it's working as expected. 

We seem to have 3 options:

- Continue today's behavior
- Make it so none of the statement errors
- Make it so both statements error

What are your thoughts @RyanCavanaugh?

**Comment by RyanCavanaugh** [comment]
I misread the OP, you're right - this is the intended behavior. I thought we were looking at a `this: typeof Item`. Good catch.
