### ISSUE TITLE
Type identifier for class, such that be differentiated from Records/Interfaces

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/TypeScript#44127]
# Suggestion

I would like to suggestion that class get top level type support in that an interface and a class can be differentiate when mapping types, because at current one is not able to  {[K in keyof T]:T[K] extends Class ? 'I am a class and not a Record<any,any>' : 'do something else. When manipulating things one wants to differentiate between imbedded nested object and a class, because one may want to Modifier or drop the Nested Record Structure and preserve and leave types such as Date and other BigInt, Classes un Touch. As far as I know I can't current do this.
## 🔍 Search Terms
type identifier for classes or class

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [✅ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [✅] This wouldn't change the runtime behavior of existing JavaScript code
* [✅] This could be implemented without emitting different JS based on the types of the expressions
* [✅] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [✅] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Basically the ability to differentiate class using a class type keyword, I know that all classes are typically interface, however, one doesn't want to crack open every class, because it looks like a record, when manipulating types. The ability to check if a Type is a class at design time would be greatly appreciated. 

## 📃 Motivating Example
Example1:
```.ts
class A {
// no constructors need.
 fieldA: boolean;
 fieldB: string;
fieldC: number;
field:Date;
field: Moment;
neastedRecord: Record<any,any>;

fieldArray: Array<Record<any,any>>;
}

type ShallowFields<T extends Class> = Omit<T,{
[K in keyof T] :  T[K] extends  Class ? K : never
}[keyof T]>

type Result = ShallowFIelds<A>;
// Expect the following data structure, where the neasted field has been dropped.
{
 fieldA: boolean;
 fieldB: string;
fieldC: number;
field:Date;
field: Moment;
fieldArray: Array<Record<any,any>>;
}
````
Example 2:
```.ts


type ShallowFields<T extends Class> = Omit<T,{
[K in keyof T] :  T[K] extends  Class ? K : never
}[keyof T]>

// many other forms of things here.
function createShallowDataTransferObjectFromClass<T extends TClass>(Object:TClass) : Pick<T, ShallowFields<T>> {
Physically at runtime extract and copy those parameters to a new object.
}
```

```.ts {

type Transfer<T extends (Record<any,any> | Class)> = {
[K in keyof T] : T extend BaseType | Function | Class ? T : Transfer<T[K]>
}

// Type constraint checking = 'T'// false to comple

type Transfer<T extends (Record<any,any> | Class)> = {
[K in keyof T] : T extend BaseType | Function  ? T[K] : T extends Record<any,any> ? T extends Class ? T : Transfer<T[K]> :T[K]
}[Keyof T] 

// transform class reclusively and into nested objects and preserving Classes,  as doesn't think class are Records<any,any>
// however for backwards compatibility, class still need to be seen as Record<any,any> Class is just a further more narrowed type constraint.
type Transfer<T extends (Record<any,any> | Class)> = {
[K in keyof T] : T extend string | number? T : T extends Class ? T : Transfer<T[K]> : 
}

{
  fieldA: string | number ;
  funcA : (index: any []) => any
  Neasted Field : {
      NFieldA: string | number;
      NFieldB: string | number; 
      funcB : (index: any []) => any
      }
}

// transformed, using the above.
{
  fieldA: string | number ;
  Neasted Field : {
      NFieldA: string | number;
      NFieldB: string | number; 
      }
}

```

This provides the ability to easily convert classes to Data Transfer Objects or slim down version, where you excluded deeply neasted parameters, when further queries could retired further depths into the structure.
It also allows for neasted and recursive evaluation of data structure to convert and create and sub class and partially sub class, and remove parameters when transforming a class which had BLL logic to interface data structure that can go over the wire.

## 💻 Use Cases

The ability to really cut out all the duplicate work when going from database all the way to API across into frontend, that structures with validation of structure defined at store level can be used at API request,response and frontend validation, but just picking and selecting fields from existing datastructures, where all this information is already defined using decorators and reflections. Kill all the duplicate work, when outputtting subset of all class and interfaces, with joins and populate and deepopulate. Should be able to seemlessly, be able to work from the lowlevel backend all the way into the frontend, Swagger should basically become irrelevant as defined all of this in a common types file for the backend and frontend as well between micro services. Which means everything is evaluated at Design time. Swgger could still be generated if required. Really want to reduce the amount of crazy work, which really prevents somone from working common lowlevel data source definitions all the way up to all the varius derivatives, right now alot of mental work, not simple to do, even with pick and things, are still limited.
Additional we require class constraints for field types that are alllowed, as well as class names for conventions and validations.
At the end of the day its about how much faster tools like this make things and how many errors they reduce. Still not there that kill lost of time so far as falling shot here and there with simply being able picking types.

**Comment by RyanCavanaugh** [comment]
I can't figure out what distinction you're making here or how it would be determined. How is an Array not a class? It's instantiable via `new Array()` and can be used with `instanceof`. A class might inhabit a `Record`, so that's also suspect. It seems like you need some domain-specific code generator since you have rules of convention rather than structure.

Aside: it's spelled "nested".

**Comment by wesleyolis** [comment]
@RyanCavanaugh Been crazy times. 

Thanx for spelling correction. Noted, get mind and fingers to adjust, hopefully.

Basically this for typescript type manipulation only, which would allow inference of types.
Typically there is no way to differentiate with typescript typing engine a class instance from a Record<any,any>.
Typically only would like to reclusively transform nested typing Record Structures of types, however, can't stop the iteration from recursively re-writing types of class, in other words, one could convert all types for Date or any custom class instance, with ones transform, as one can't distinguish in the typing system when a key if a member of a class instance, to stop reclusively re-writing type properties.

instanceof is a runtime javascript method, which I can't use in a type transform expression in typescript.
However the ability to have typescript typing engine at design time being able to have extends instanceof, for typescript type re-writing.

Basically would allow you to do things like this much more simply, however, there are so many other times, when one in JavaScript reclusively re-writes the data structures, which results in recursive type re-write, in which one needs to also write a typescript type generic transformer, to apply the same typing change, otherwise the types just end up being function():any{}, because typescript can't re-write the types.

The ability for test to maybe detect recursive function calls, such it can, automatically trunk the types in the compiler, to simple representation, that can capture the recursive nature of the type-rewrite would be great.

Here is a simple example of naturally occuring data structure that occurs alot in many datastructures of different systems or binary system protocals, in which I was writting a BufferJSON back and forth, which gets trick, as want to be simple carbon copy of manual LLRP, which makes more understandable.



Type Inference for Mongoose, which be even simpler to do if typescript enhances it typing system.[https://github.com/wesleyolis/mongooseRelationalTypes](https://github.com/wesleyolis/mongooseRelationalTypes)


[Typescript play ground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShDGB7ATgEwM4HkBmAhO8ArugJYBu0AvFAN4BQUjUAglAFxTrDIkB2A5gBoGTXAH52sBCgw58CYuWgAyWiKZNEwABYRkAMRIQANqg69CAWwBGe9VAC+TOg7p0kvLlGAQvHAjJYeASKFADcbj5cAHSs1ABE8XRRwNG4sVAJSSlp0Vq6BkammVAAjBE56VV5OnqGJqgl5SJAA)

```.ts
type RecordsOfBRecusive = {
    A : string,
    B? : RecordsOfBRecusive & {
        otherField: number
    }   
}

const test : RecordsOfBRecusive;

test.A = ""
test.B.A = ""
test.B.otherField = 1;
test.B.B.B.otherField = 1;
 ```
