### ISSUE TITLE
Class extend and subclass other classes using Pick/(recusive) with copy constructor

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/TypeScript#44132]
# Suggestion
The ability to simple create new derivate classes from a class and choose a subset of parameters to be available and possible mutate a few parameters while keeping all decorators an reflection capabilities, such that one easily create all the partial derivates that are transmitted of the API interface, for different field combinations or groups. The ability to be able to easily create derivates will really improve our ability to create all the different Transfer Objects Require for Request/Responses from existing data and for different API. 

## 🔍 Search Terms
class extends pick 
## ✅ Viability Checklist

My suggestion meets these guidelines:

* [✅] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [✅] This wouldn't change the runtime behavior of existing JavaScript code
* [✅] This could be implemented without emitting different JS based on the types of the expressions
* [✅] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [✅] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

```.ts
Class BaseDataSource extends IClassConstraints<PlainDataTypes> {

fieldA: string;
//@Decorator_min_Length('min length)
fieldB: number;
fieldC: boolean;
}

// All Decorators and parameters/types are avaliable on all darivatives
Class MutCLass extends BaseDataSource{
construction(...) // Error construction are not allowed on pure data types.

get Test() /// Error Getter and Settings are not allowed on Class to due class constraint...
}

Class BLL {
 constructor(private bll :MutCLass) {}

get Method() // OK
Function() // OK
}


class NewDerivate<TClass extends Class, TFields extends keyof TClass> extends PicK<TCLass, TFields>
{
constructor<TClass extends Class, TFields extends keyof TClass> (public TClass, fields : TFields) : NewDerivate<TClass, TFields>{
//Copy Constructor code for fields
}

// The Resulting class has all the fields and access to derived class decorators
}

// All that is required is new 
const test = Derivative(MutCLass, 'fieldA' | 'fieldC')
test.FIeldA
test.FieldC
test.FIeldB // not avaliable, original base class decorators avaliable.

//Or

class NewDerivate<TClass extends Class> extends Pick<TCLass, keyof this> //  Requires a copy constructor taking a parameter of TClass.
{
constructor<TClass extends Class,> (public TClass) : NewDerivate<TClass>{
//Copy Constructor code for fields
}
FieldA: any
FieldB: never
FieldC: any
// The Resulting class has all the fields and access to derived class decorators
}

**Comment by RyanCavanaugh** [comment]
In our type system, subclassing is subtyping, so leaving out fields doesn't ever make sense when inheriting. There are other patterns you can use here that accomplish this.
