### ISSUE TITLE
Functions of function interfaces don't accept contravariant types unless explicitly intersected

### ISSUE THREAD

**Issue by erikbrinkman** [microsoft/TypeScript#44133]
# Bug Report

### 🔎 Search Terms

type inference functional interface

### 🕗 Version & Regression Information

This is present in 3.3, 4.2.3, and nightly, so either it was fixed and reintroduced or it's always been present.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgGIFcQIDwBUB8yA3gFDLnIAUwkAtgFzK4CUjAbgPbAAmA3CWQoQAHmChxGAIw4cANhDgh+AXwHcICWXCgoEHEAGcwyUDGgQsEAIyNsqZCMghuBtJhyYA1iA4B3EPj41CAADoyozMgAvIScPPwk6prauvpGyF4YWOHu2F4+-vj8SVo6yHqGxiDotFkIOVjY1bSS0EUCpuaWVpSZ7sz8nTrdlM11A2oapamVJiBmw0gATLa4ADRoDqIWLm6NBEGgYZsAZFTBxyzRsVzczJExyHF8HfNdy70gnuODb4sQS1GNR+QA)

### 💻 Code

```ts
interface Func<T> {
    (item: T): void;
}

declare const inference1: <F extends Func<unknown>>(inp: F) => void;

declare const unkFunc: Func<unknown>;
declare const numFunc: Func<number>;

inference1(unkFunc);  // ok
inference1(numFunc);  // error

declare const inference2: <T, F extends Func<T>>(inp: F & ((inp: T) => void)) => void;

inference2(unkFunc);  // ok
inference2(numFunc);  // ok
```

### 🙁 Actual behavior

`inference1` doesn't accept a valid type, unless the function type is explicitly tagged as in `inference2`.

### 🙂 Expected behavior

no error

**Comment by jcalz** [comment]
Looks like everything is working as intended.  `Func<number>` is not assignable to `Func<unknown>` because `Func<T>` is contravariant in `T`:

```ts
const numFunc: Func<number> = Object.assign((num: number) => num.toFixed(2), { extra: true });
const unkFunc: Func<unknown> = numFunc; // error, because:
unkFunc("hello"); // ERROR! num.toFixed is not a function
```

[Playground link to code](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgGIFcQIDwBUB8yA3gFDLnIAUwkAtgFzK4CUjAbgPbAAmA3GRQgAPMFDiMARhw4AbCHBD8AviRIIOIAM5hkIdLQxZGhnHtoTohALzIA8hIBWEBGAB0cTZuABzEJUpmjGYWUMzIVoRmrmAcqMBCENyUAEzMADTEyMKi4sii6ChKzPzqWjqYANYmxpg4lSAcAO4g1rr6JrzIAPRdWVBQHFAZFghw6JoQ9CSVJpQARAAWEDIyHHPF3b0AogBKO7Y7AIRttNGx8YnIwJq6HDpwyDC1YMAaqiRAA)

**Comment by erikbrinkman** [comment]
@jcalz you're correct, I tried to simplify from an earlier example which was:
```
declare const inference1: <T, F extends Func<T>>(inp: F) => void;
```
but it seems that then the issue is with correctly inferring implicitly bound parameter types, than it is with actually incorrect inference. I couldn't find an issue for that, but it's likely here somewhere, and would probably get pretty difficult with combinations of difference variance.

Thanks for the correction!
