### ISSUE TITLE
Class DataFields only, Constraint, basically interface with support for decorates and reflextion ability to Pick with Classes

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/TypeScript#44131]
# Suggestion
 Well basically, interfaces don't support decorators and reflection, so we would like to be able to use a class, however, for safety,
make all class take an optional Generic FIeld|Property|Function|Constructor|Getter|Setter|NeastedRecord, NeastedArrayRecord Constraint, which will limit the implementations functionality to the desired behavior we choose. Typically look for class to act as an interface, however, with data members. The ability to also create quick copies of classes using a copy constructor, where fields can be Pick, that appear on a class, typically all decorators and Reflection Methods should be available in the specialized derived darivative.

## 🔍 Search Terms
Class Constraints

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [✅ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [✅] This wouldn't change the runtime behavior of existing JavaScript code
* [✅] This could be implemented without emitting different JS based on the types of the expressions
* [✅] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [✅] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

The eco system is so disconnected between low level data source requirements and API level derivates, would like for things to maluable across the whole domains, making things safer with larger teams as to the patterns we employ. Really allows for more advanced runtime functional derivatives of class and neasted classed to be formed, while keep all the typing information and ensure that the typically design boundaries from data source to BLL, Validation, API, Frontend are all confirmed to by using the class constraints, where limit which types of getter, setters, function, constructor, enumeralble, readonly,neastedCLasses(LIst of class), neastedRecords, can be used or not. Easily Create derivative classes.

## 💻 Use Cases

```.ts
Class BaseDataSource extends IClassConstraints<PlainDataTypes> {

fieldA: string;
//@Decorator_min_Length('min length)
fieldB: number;
fieldC: boolean;
}

// All Decorators and parameters/types are avaliable on all darivatives
Class MutCLass extends BaseDataSource{
construction(...) // Error construction are not allowed on pure data types.

get Test() /// Error Getter and Settings are not allowed on Class to due class constraint...
}

Class BLL {
 constructor(private bll :MutCLass) {}

get Method() // OK
Function() // OK
}


class NewDerivate<TClass extends Class, TFields extends keyof TClass> extends PicK<TCLass, TFields>
{
constructor<TClass extends Class, TFields extends keyof TClass> (public TClass, fields : TFields) : NewDerivate<TClass, TFields>{
//Copy Constructor code for fields
}

// The Resulting class has all the fields and access to derived class decorators
}

// All that is required is new 
const test = Derivative(MutCLass, 'fieldA' | 'fieldC')
test.FIeldA
test.FieldC
test.FIeldB // not avaliable, original base class decorators avaliable.

//Or

class NewDerivate<TClass extends Class> extends Pick<TCLass, keyof this> //  Requires a copy constructor taking a paramer of TClass.
{
constructor<TClass extends Class,> (public TClass) : NewDerivate<TClass>{
//Copy Constructor code for fields
}
FieldA: any
FieldB: never
FieldC: any
// The Resulting class has all the fields and access to derived class decorators
}



```

**Comment by RyanCavanaugh** [comment]
This doesn't appear to be a type system feature, based on what I am able to glean from it. Proposals to create new kinds of classes or decorators should be taken to TC39.
