### ISSUE TITLE
Keyword `validates` for assertions that can throw in try-catch and still affect control flow, for soft validation

### ISSUE THREAD

**Issue by isometriq** [microsoft/TypeScript#44141]
# Suggestion

## 🔍 Search Terms

asserts inside try catch block

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Would like to be able to use my `asserts` functions inside a try catch and still have the effect on control flow. Of course, if I re-throw the control flow understands that and applies it.

Perhaps would like to have another keyword (`validates` ?) similar to `asserts` that tells the compiler to trust my function ( a bit like with `!` but just for assertion).

## 📃 Motivating Example

When used in try catch, the the effect of `asserts` keyword on control flow are cancelled. By allowing it, it allows to:
* group multiple validation assertions in a sequential flow;
* be able log a generic message and quit the function or even continue flow;
* when logging, the line number point in the same file and location of the assertion, which helps a lot when stuck with browser debugger or bundled sourcemaps;
* have a graceful handling of the exception;

Perhaps a new keyword `validates` ?

```
let value3: Value;
try {
  assertNonNull(value1, 'value1');
  assertString(value2, 'value2');
  value3 = values[0];
  assertNonNull(value3, 'value3', `Value not found at specified index (0)`);
}
catch(e) {
  console.warn('Unexpected parameters', e, values);
  return;
}
```

## 💻 Use Cases

Allows to group multiple validation assertions in a sequential flow and be able to log a generic message and quit the function or even continue flow.

Workaround is to use separate conditions for testing values and warn/return (requires to have same logic as assertions for tests).

Or continue to use the `!`, but too dangerous, not implicit

**Comment by DanielRosenwasser** [comment]
I'm not totally clear on the proposal here. Can you give me examples of what these `validates` functions look like? Can you explain a bit more about what what the issue is today that you're trying to solve?

**Comment by RyanCavanaugh** [comment]
This is very under-specified. Can you give a complete code sample so we don't have to try to reconstruct what `value1`, `values`, `value2`, `assertNotNull`, and `assertString` are defined as?
