### ISSUE TITLE
Complex generic does not narrow type

### ISSUE THREAD

**Issue by qwelias** [microsoft/TypeScript#44145]
# Bug Report

### 🔎 Search Terms

generic narrow type guard object index 

### 🕗 Version & Regression Information
v4.2.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAYg8lAvFA5AMxVAPqg9igKANEll1wB4AVcaCAD2AgDsATAZ1gWXgD4koAbygBtKlACWzKDUgBdAFxCCUVVBIQlVADQq1rAIbADSgEoQAxrgBOratvXWArhF66AvlHdjacohqgAIQNralooBiY2TngBPgFhMUlpWQhFISg0ciUYcmp+TwAyZTVMpWEAIxCzSxs7HUcXAt1S3CUnZgBrZlwAd2YPMTkvH3kiK2Z2YCgq6wTPA05g6wIJNCgAClmAOizcbYDEI9QMAEoZkO3ZoA)

### 💻 Code

```ts
type FO = 'f' | 'o'

type Foo<Type extends FO = FO> = { [T in Type]: {
    type: T,
    data: Record<T, true>,
} }[Type]

const foo = {} as Foo
if (foo.type === 'f') foo.data.f // all good, narrows the type

type Bar<Type extends FO = FO> = { [T in Type]: { foo: Foo<T> } & {
    f: { bar: Record<T, true> },
    o: unknown,
}[T] }[Type]

const bar = {} as Bar
if (bar.foo.type === 'f') bar.bar // broke
```

### 🙁 Actual behavior

> Property 'bar' does not exist on type 'Bar<FO>'

### 🙂 Expected behavior
`bar.bar` identified as `Record<T, true>` because it's in the same indexed property as `bar.foo.type` for `T` that is equals to `f`

**Comment by RyanCavanaugh** [comment]
See #18758
