### ISSUE TITLE
URLSearchParams can take object

### ISSUE THREAD

**Issue by gorkhadk** [microsoft/TypeScript#44142]
It is perfectly ok to pass an object to URLSearchParams, but typescript wont let you.
should be ok:
let testParams = new URLSearchParams({sportId: 1, sort: 'name'})

tested with 4.2.4 and no mention in 4.3beta

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

Duplicate of #43738.

**Comment by gorkhadk** [comment]
I am not sure how I bypassed that template, but I will comment on the dupe.
