### ISSUE TITLE
Separate generics and generic constraints

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#44155]
# Suggestion

## 🔍 Search Terms

Generic
Constraints

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It should be possible to specify explicitly which generics are constraints and which are not.

## 📃 Motivating Example

With this notation (to be defined), you can define explicitly which generics must be given by the consumer of your type, while also being able to define separately constraints.

## 💻 Use Cases

Meta programming, configuration.

Considering a function to create a bunch of Store objects with proper typing passed down:

```ts
type Store<T extends any> = {}

const createStore = <T extends any>() => ({} as Store<T>)

const createStores = <T extends { [x: string]: {} }, K extends (keyof T)[] = (keyof T)[]>(...keys: K) => (
  keys.reduce((acc, key) => ({ ...acc, [key]: createStore<T[typeof key]>() }), {} as { [X in K[number]]: Store<T[X]> })
)
```

for which `T` is a map of "store name → model type" defining an app most complete store configuration, such as:

```ts
type Config = {
  'userIds': string
  'friendsCount': number
}
```

hopefully it should be used like:

```
const stores = createStores<Config>("userIds")
```

To be noted:

- we explicitly ignore the "friendsCount" since we don't want it
- The type of "stores" should be `{ friendsCount: Store<number> }` ("userIds" is ignored since not part of K)

### Why it doesn't work

- if you pass T, you must pass K.
- if you set default of K to be `(keyof T)[]`, keys of return type will always contain all the keys of T (rather than K[number])

### Workaround

The cleanest I've succeed in doing so far is separating the 2 generics and cast after that:

```ts
type CreateStores<T extends { [x: string]: {} }> = <K extends (keyof T)[] = (keyof T)[]>(...keys: K) => {
  [X in K[number]]: Store<T[X]>
}

const stores = (createStores as CreateStores<Config>)("userIds")
```

[Playground Link](https://www.typescriptlang.org/play?ssl=28&ssc=1&pln=31&pc=1#code/C4TwDgpgBAysD2AnCAeAKlCAPYEB2AJgM5QCGeIAfFALxQDeAvgFDMDG8eRwUbypuOEmh10mHPmJkKlABQBKWtVlMyJIcnSV5rDlx58IAiBohEAjLShjsuQiXpQA2lgBcUbogCWeAOYBdd3IQKEYAGigAaXE7KVkAawgQeAAzKDR5J385ADo8xJAid0jFGmVmKCgCohzkAgBXNghZWVI2NgiC0uVHPJy2jucCwN5+QQRNNCdQSFSqpOyFUPkI1VIHZwANKB8opzx6gFsAIwhEfxHTdCdN7OXmHWYAeieoY-WvNl4kZDYeU4AFqQAG5eJDsTjcDwTMwAQSshmMpgssgA5Cl4PBUY8XlEAPIRbCQP4QAhQBBQMDrEgAJigvnwZ0+RAh+mhwiIACEEWMTDCLChHBj4O5PD5fBF3oh3AcTmdQnJ0ZjsaxcQBaDVserADVq3SQgy85F00QYWySDYuUXAbx+EbBUIRaLm+xQBJJOYZLJWd3JNJexZ9arFbpuirzQq1UmNZqtdqdJKhlRQPoDCJOYbuRHjYTXGYQObDOSKRgrBiMNQMLY7PB7WWnc6XGHXW7UUsPVWvSIEjwA+D1AA2ZLw8B4QOB0AARFLJ5TEPBIIhQKyodwOQBhHlGHPIIg0wVQYXW20St6kaVQevyxiK4Uqte79c5KVQXFEPuDsmnKB1Dw+JpQNO56zl4JAjjwuyRKwzyvLqADuSDxOe-aELqrD5lA65GvyADMNgSK6jhWtCJ4jKoN5WCgzoEXEBSepk-g+nR-oMbk+RJEUUShvQ4Y3DWdZHA2FzuFcUytswLAroa258hyOGUWaNGWm4JHivaFCOlEMQWm6zHpAxTEeixWRsTkwZcUoYaVNUUYNE0LRphGSa9HkjkZgsWbYbmUz5oWCzFssqwVusVZ8ZB+yCWcwmwM2Yl3O2jx6Ku-IACI+tmsm7vJIVYTJyJ4UKmLHuKkrnjKkWIAq8honeOgPmYKU5MKr6vBwiC-MAzD1UQjUvriZzzhebUdUAA)

## Proposal

I don't have much ideas, but probably chaining 2 sets of `<>` could help such as (I've added \n to see clearly the notation):

```ts
const createStores = 
  <T extends { [x: string]: {} }> // the generic types to provide
  <K extends (keyof T)[] = (keyof T)[]> // the function's signature constraints
  (...keys: K) => (
    keys.reduce((acc, key) => ({ ...acc, [key]: createStore<T[typeof key]>() }), {} as { [X in K[number]]: Store<T[X]> })
  )
```

**Comment by jcalz** [comment]
Looks like #26242, where you want `K`'s default to be `infer` (or whatever the sigil is)

**Comment by y-nk** [comment]
Indeed that's it thanks @jcalz !
