### ISSUE TITLE
.d.tsx files are not treated specially.

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#4415]
`.d.tsx` files should probably be treated as `.d.ts` files, or cause a warning telling the user that `.d.tsx` doesn't work, and that they should rename the file to `.d.ts`.

**Comment by jbrantly** [comment]
Out of curiosity, what's the use-case for a .d.tsx file?

**Comment by Gaelan** [comment]
Not much, but having them *just not work* is a bit unexpected. I discovered this after mass-renaming all files from *.ts to *.tsx. (I did this because tsc and atom-typescript disagree about whether normal .ts files should compile to .jsx or .js under `react: preserve`, leading to duplicated files). It would have been nice to have it either work or for the compiler to tell me something was wrong.

**Comment by danquirk** [comment]
The error we currently give suggests this should've been an error:
```error TS6054: File 'a.d.tsj' has unsupported extension. The only supported extensions are '.tsx', '.ts', '.d.ts'.```

**Comment by mhegazy** [comment]
I would rather not support an additional file extension. every time there is a new extension supported, it is another hit to the disk when we are resolving a module import. we need a proposal here.

**Comment by danquirk** [comment]
If we just reported the error when parsing the filename (from the command line, tsconfig, or ///) that might be sufficient to catch many cases without invoking extra disk accesses. It wouldn't catch the case where you only use modules, no ///, and no .d.tsx files (or whatever illegal filetypes) were explicitly mentioned in tsconfig, but that still might be a good enough check to improve the situation?

**Comment by Gaelan** [comment]
Can .d.* files be used as modules in the first place?

**Comment by CyrusNajmabadi** [comment]
“xxx.d.tsx” has the extension “.tsx” ☺   So that error doesn’t apply (unfortunately).

             -- Cyrus

**Comment by mhegazy** [comment]
closing this as won't fix. please post back f you have a proposal on making the experience better and will reopen.

**Comment by Attrash-Islam** [comment]
I use this in migration to React with TSLint usages. But I'll go with the .d.tsx (Also for searching filters in VSCode to show more related code). You can resolve this by importing with the .d which will behave with the files as regular .ts files.

import { IMyInterface } from '../src/interfaces/MyInterface.d'
