### ISSUE TITLE
transformer can't get import type details

### ISSUE THREAD

**Issue by z2014** [microsoft/TypeScript#44160]
# Bug Report

### 🕗 Version & Regression Information
```
"typescript": "^3.9.3"
"@types/node": "^12.0.7",
```
ts.createProgram option
```
        strict: true,
        noEmitOnError: true,
        suppressImplicitAnyIndexErrors: true,
        target: ts.ScriptTarget.ES5,
```

![image](https://user-images.githubusercontent.com/17852357/118758981-a35e2180-b8a2-11eb-80e0-abd0b94e073b.png)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
```javascript
// interface.ts
import { IChalk } from 'chalk'
import { keys } from 'ts-interface-keys-transformer'

interface Test {
    c: IChalk;
}
const config = keys<Test>()

// compile.js
    import transformer from 'ts-interface-keys-transformer';
    const option ={
        strict: true,
        noEmitOnError: true,
        suppressImplicitAnyIndexErrors: true,
        target: ts.ScriptTarget.ES5,
    };
    const program = ts.createProgram(['./interface.ts'], option);

    const transformers: ts.CustomTransformers = {
        before: [transformer(program)],
        after: [],
    };

    const { emitSkipped, diagnostics } = program.emit(undefined, undefined, undefined, false, transformers);
```
when i debug sourcefile, it don't include `node_modules/chalk/types/index.d.ts`
only
```
sourceFile /ts-interface-keys-transformer/test/interface.ts
```

### 🙁 Actual behavior

i can't get IChalk details

### 🙂 Expected behavior

can get IChalk details interface

**Comment by RyanCavanaugh** [comment]
The implication that TS's primary API entry point is malfunctioning in a mainline use case doesn't seem plausible. You have some sort of misconfiguration or other programming error here.
