### ISSUE TITLE
top level `this` is undefined when file contains imports and `module` is commonjs

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#44163]
# Bug Report

### 🔎 Search Terms
top level this undefined imports

### 🕗 Version & Regression Information
4.4.0-dev.20210519

### ⏯ Playground Link
with imports: https://www.typescriptlang.org/play?module=1&ts=4.4.0-dev.20210519#code/JYWwDg9gTgLgBAcgGYQggUOgxhAdgZ3hQjgF44YALYfOAejuLhrgFdcATAUyWFy46YqNAHT4uMACqguEVvAZcoUaEA
without imports: https://www.typescriptlang.org/play?module=1&ts=4.4.0-dev.20210519#code/MYewdgzgLgBAZiEMC8MoAsCWEYHpcJLZoCeADgKYhwwDmANiAEYCG9AKlhAFDcbYA6CBSjtMAWyoBXKEA
### 💻 Code

with imports:
```ts
import 'foo'

const foo = this //foo is undefined

this.setTimeout //error
```
without imports:
```ts
const foo = this //foo is typeof globalThis

this.setTimeout //no error
```
### 🙁 Actual behavior
when the file has no imports, the top level `this` correctly has the same type as `globalThis`, but when there are imports, the top level `this` is of type `undefined`

### 🙂 Expected behavior
the top level `this` has the same type as `globalThis`, regardless of whether or not the file has imports in it

**Comment by MartinJohns** [comment]
"`this`" is intentional: #35882

Used search terms: `this undefined in:title`

**Comment by DetachHead** [comment]
`this` should only be `undefined` when it compiles to a module. if the `module` compiler option is set to "commonjs", the top level `this`  should be `typeof globalThis`.

that issue seems to assume that a ts file is an esmodule just because it has imports, which isn't always true because lots of projects just have them compiling to commonjs

**Comment by MartinJohns** [comment]
TypeScript considers files to be modules when you use `export` or `import`, regardless of the `module` compiler option.

**Comment by DetachHead** [comment]
why? seems silly to use such an unreliable method to determine that instead of just checking the compiler option that says whether they are modules or not

**Comment by MartinJohns** [comment]
Because not every file is automatically a module. You can have global scoped files next to modules.

https://www.typescriptlang.org/docs/handbook/modules.html

> In TypeScript, just as in ECMAScript 2015, any file containing a top-level `import` or `export` is considered a module. Conversely, a file without any top-level `import` or `export` declarations is treated as a script whose contents are available in the global scope (and therefore to modules as well).
