### ISSUE TITLE
When using numbers keyof lost the keys of objects

### ISSUE THREAD

**Issue by SimonChaumet** [microsoft/TypeScript#44170]
# Bug Report

### 🔎 Search Terms
keyof, number, identity, cif

### 🕗 Version & Regression Information

In playground from 3.3.3 to 4.3 beta

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about keyof

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWwJ4DFzXmAjAHgFgAoRRAQUQFMAPKKsAEwGdEAlKiOAJ0f2ajcYYAOYAadpx58BQ0RLAhkAIyrcAfOrEkyAIWp0GLSV179Bw8YgDeAbQAK3OAAc1UVImGIA1lVRxgCgBdAH4ALh8-AIoHJ1dudyCAX3USdQAKAEMI8gllCN0ASgjbXMRdIJsdRG4qKBBuJFtMvKCAbhIkkhIuMAFEWxpcCVRcSoBeFAwsWARcdOtqtEcXCMXSMkR8xGHqpO1ifaqNtHIAGxhM5jXqsmW4iIAiZUeDsi7Dwo7iEgB6X8QAElEAB3TJgKCIKBwRAiOqIcHUbhObieQJoRDOOKIRhwKjMMAAckhtBgAj+AIAEmoqFCABa0sAIAxk2CiTFxNwwfGICC1TL0JEo1imWrQM6oHoIZhwM5UAB0ZzgInSQ3l9xcEjVTLAAFEaKzLCtnCNcOrUOdLsxTfKdfrDaJLVcvt1iL1+oMAEwjT0TKaYSCzPALJaoY03DZkXARAAs3r2nQk6zuFouVwjmym4Z2b0QHySLp+xH+iGptXpjOZpIElg5Li5PMy5aZkL5VAFtbUwsQwB4iEeqE9jylfVlCqVKponvNxq107tBprolniEH5qd1tX84Q9qXIg3XyAA)

### 💻 Code

```ts
function myFunction1<
  A extends Record<string, Record<string, number>>,
  B extends Record<string, {[Property in keyof A]?: keyof A[Property]}>
>(a: A, b: B): [A, B] {
  return [a, b];
}

const [x1, y1] = myFunction1({
  myProp: {
    b: 1,
  },
}, {
  myAlias: {
    myProp: "b",
  }
});

// I want to get an error if my prop doesn't exist
// Here the non existing properties create errors correctly
console.log(x1.myProp /* not an error */, x1.nonExistingProp /* throws error */, y1.myAlias /* not an error */, y1.nonExistingAlias /* throws error*/);

const [x2, y2] = myFunction1({
  myProp: {
    1: 42,
  }
}, {
  myAlias: {
    myProp: 1,
  }
});

// Here the non existing properties are not creating errors for "y2"
console.log(x2.myProp /* not an error */, x2.nonExistingProp /* throws error */, y2.myAlias /* not an error */, y2.nonExistingAlias /* does not throw error */);
```

### 🙁 Actual behavior

When using numbers the type system can't check which property is in my type and which is not.

### 🙂 Expected behavior

The type system should know which prop I can use

### Goal

Here my goal is to create a react component that accepts properties (which are mapped to css properties), and aliases that fill the component properties.

E.g :
I have a prop "size" that accepts the values "large" (which corresponds to an object {padding: 18px} but in the code it is represented by a number), "medium"...
And then I will have an alias like "big" that sets the size to "large" and other properties...

Here my goal was to constraint the possible values of the properties and aliases, in the TS discord I asked this question (how to constrain subproperties of objects while keeping the keys ?) and someone told me to use a CIF (Constrained Identify Function), that's how I ran into this problem.

**Comment by RyanCavanaugh** [comment]
You have a `Record<string, ...>` here so it's expected to be able to write that. You can toggle that behavior with `noPropertyAccessFromIndexSignature` and then correct the definition of `myFunction1` appropriately to be able to access `y2.myAlias`

**Comment by SimonChaumet** [comment]
@RyanCavanaugh 
What do you mean by correcting the definition of my function ? What's wrong in it ?

My problem comes from my objects not treated the same way when there are numbers vs when there are strings, but I can't constrain to keep only strings.

**Comment by SimonChaumet** [comment]
It is not a question, if the issue is not reopened I will create a new issue
