### ISSUE TITLE
super constructor does not set property

### ISSUE THREAD

**Issue by icecream17** [microsoft/TypeScript#44178]
# Bug Report

### 🔎 Search Terms

super
super constructor
property not assigned
has no initializer and is not definitely assigned in the constructor.

### 🕗 Version & Regression Information

(todo)

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAYwNghgzlAECCsDexZoA4CcD26BcsAdgK4C2ARgKaapojaFQAumxIT2msAFAJTK00aJgAsAllAB0WXLAC8sACyCAvsDWhIMWACFYlAB5NKhACZxEKITPxEyVGkPqMWbDlz4ChQqMXTU+VXVgIA)

### 💻 Code

```ts
class A {
   prop: number
   constructor () {
      this.prop = 4
   }
}

class B extends A {
   prop: number
   constructor () {
      super()
   }
}
```

### 🙁 Actual behavior

`Property 'prop' has no initializer and is not definitely assigned in the constructor.` (class B)

### 🙂 Expected behavior

Why doesn't `super` work???????

**Comment by nlanson** [comment]
`super()` isn't working in `class B` because you haven't set any parameters for your constructor in `class A`.\
Also no need to declare property `prop` in `class B` since you're already extending `class A` unless you're overriding it for some reason.

```
class A {
    prop: number;
    constructor( prop: number ) {
        this.prop = prop;
    }
}

class B extends A {
    constructor( prop: number ) {
        super(prop);
    }
}

let e = new B(4);
console.log(e.prop); // 4
```

**Comment by icecream17** [comment]
Edit: Oh... it seems to work when I remove the property. Huh

```ts
class A {
   prop: number
   constructor () {
      this.prop = 4
   }
}

class B extends A {
   constructor () {
      super()
   }
}
```
