### ISSUE TITLE
Generic interfaces flagged incompatible, as if nominal typing [fixed]

### ISSUE THREAD

**Issue by qwertie** [microsoft/TypeScript#44171]
# Bug Report

### 🔎 Search Terms

- Cannot assign compatible object types to each other sometimes when `extends` is used
- Generic interface types incorrectly flagged as incompatible
- Generic type acts as if it is nominally typed

### 🕗 Version & Regression Information

This seems to be fixed in v4.3.0-beta but I couldn't find a bug report for it.

The bug is present in v3.3.3 and v4.2.3.

### 💻 Code

~~~ts
export enum EntityType {
    Unknown = 'Unknown',
    Lake = 'Lake',
    Tank = 'Tank',
    Project = 'Project',
}

type Config<T extends EntityType = EntityType.Unknown> =
    T extends EntityType.Unknown ? { } & { } : { };

interface Thing1<T extends EntityType> {  
    configuration: Config<T>;
}
interface Thing2<T extends EntityType> {  
    configuration: Config<T>;
}

let a : Thing1<EntityType.Project> = { configuration: {} };
let b : Thing1<EntityType.Unknown> = a; // Error on variable `b`
~~~

### 🙁 Actual behavior

The following error appears on the last line if `b` has type `Thing1`. It looks like the kind of error that would legitimately happen in a nominally typed language, but of course, TypeScript is structurally typed.

~~~
Type 'Thing1<EntityType.Project>' is not assignable to type 'Thing1<EntityType.Unknown>'.
  Type 'EntityType.Project' is not assignable to type 'EntityType.Unknown'. ts(2322)
~~~

The error seems to involve the quaternary operator `extends ? :`.  The error disappears if `T extends ... ? {} : {}` is changed to `{}`. The error also disappears if `b` has type `Thing2` rather than `Thing1`.

### 🙂 Expected behavior

No error.

**Comment by RyanCavanaugh** [comment]
We have some optimizations where type relationships between `T<U1> and `T<U2>` can succeed if we a) measure `T` to be linear in one direction or another on its type parameter and b) `U1` and `U2` are related in that same direction.

This optimization depends on types being sensible; if you write adversarial types like `T extends U ? A : A` then you can get into weird situations because the variance measurement assumes that a conditional type actually bifurcates. We don't intend to take back any performance gained from this to enable patterns like this.

**Comment by qwertie** [comment]
@RyanCavanaugh The original types from which this big report was derived were neither adversarial not trivial. As far as I could tell it didn't matter what the contents of the two branches of the quaternary operator were.

**Comment by qwertie** [comment]
@RyanCavanaugh but since you brought it up, I would just point out that it is not far-fetched or adversarial to write code like `A extends B ? C : D` which later becomes `? X : X` after type substitutions.
