### ISSUE TITLE
Generators are no currently supported?

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#4417]
tsc definitely supports generators when targeting es6, but vs2015 still says that generators/yield aren't supported, which is annoying. Why?

**Comment by DanielRosenwasser** [comment]
Generators have an extremely non-trivial emit that requires rewriting your function into a state-machine. The emitted code is not at all canonical JavaScript. We're hoping to have generators, along with `async`/`await`, in in the version that follows 1.6.

**Comment by d180cf** [comment]
I get that and currently trying to use babel: I first `tsc --target es6` and then use babel to convert the generators into that state machine. This works, but when I open the .ts file in vs2015, I see that all these `yeild` things are underlined with red. My question was how to make vs2015 not consider `yield` as a syntax error.

**Comment by DanielRosenwasser** [comment]
```
Tools > Options
    Text Editor
        TypeScript
            Project
                ECMAScript version for files that are not part of a project:  ECMAScript 6
```
![enabling_es6](https://cloud.githubusercontent.com/assets/972891/9431149/6c40c470-49c0-11e5-8bb6-6e710fee65f3.gif)

**Comment by d180cf** [comment]
This didn't help. I'm using vs2015 community edition and have only a tsconfig.json (with target=es6), so when I open my .ts files, they become a part of a "virtual typescript project" - maybe that's why the setting didn't work.

**Comment by mhegazy** [comment]
@d180cf what version of TypeScript do you have installed? what is the error message text you are seeing? can you share a snapshot of the "virtual project" created?

**Comment by d180cf** [comment]
It's a virtual tsconfig project - vs2015 doesn't allow to save it in any form.

**Comment by d180cf** [comment]
Errors:

```
TS9001	Generators are not currently supported.
TS9000	'yield' expressions are not currently supported.
TS9000	'yield' expressions are not currently supported.
TS2488	Type must have a '[Symbol.iterator]()' method that returns an iterator.
```

In `\Microsoft SDKs\TypeScript` I found only `1.5`

**Comment by plantain-00** [comment]
the roadmap says the Generators will be supported at 1.6, for now, current release is 1.5.4.
https://github.com/Microsoft/TypeScript/wiki/Roadmap

**Comment by d180cf** [comment]
I see. Then can I somehow update my local `\Microsoft SDKs\TypeScript` to version 1.6?

**Comment by plantain-00** [comment]
The nightly builds may help, but I don't know how to do exactly, I just wait 1.6.
npm install -g typescript@next

**Comment by DanielRosenwasser** [comment]
@d180cf install the nightly TypeScript 1.6 and [enable dev mode](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio) using `typescript` in your global `node_modules` folder.

**Comment by d180cf** [comment]
It seems the errors have gone after that. Thanks! However I noticed, that the generator function (i.e. `function * F()`) is ruturning `any`, according to the language service from `typescript@1.7.0-dev.20150828`.
