### ISSUE TITLE
use typescript configuration alias report an error 2307 in my webstorm,but it's compile no error.

### ISSUE THREAD

**Issue by muziyan** [microsoft/TypeScript#44182]
I used typescript version is 4.1.2。

`tsconfig.json` configuration `baseUrl` and  `paths`
```javascript
  "baseUrl": ".",
  "paths": {
    "@/pages/**/*": ["src/pages/*"],
    "@/components/*": ["src/components/*"],
    "@/style/*": ["src/commands/*"],
    "@/utils/*": ["src/utils/*"]
  }
```

![image](https://user-images.githubusercontent.com/33919751/119011671-dd751380-b9c7-11eb-9c1c-4f4b4b0cf8a7.png)

I do't known error  the reason , I want to find a solution。

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
