### ISSUE TITLE
Typescript cannot set optional properties and then return as full object.

### ISSUE THREAD

**Issue by Inrixia** [microsoft/TypeScript#44198]
# Bug Report

### 🔎 Search Terms

return full, partial, partial combination

### 🕗 Version & Regression Information

Today, I've been trying to see if there is a workaround all day.
I'm running Version 4.1.3, it still occurs in Nightly.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about this and none seem to relate to this behavior

### 💻 Code
```ts
type TypeA = {
	propertyA: number;
	propertyB: number;
};

type TypeAExtras = {
	propertyC: number;
}

function foo(objA: TypeA & Partial<TypeAExtras>): TypeA & TypeAExtras {
	objA.propertyC = objA.propertyA + objA.propertyB;


	objA.propertyC;
	return objA;
}
```

### 🙁 Actual behavior
![image](https://user-images.githubusercontent.com/6373693/119155723-93fbf580-baa7-11eb-85f1-017d6bba5954.png)

### 🙂 Expected behavior
**No errors if the return type matches the required type.**
Errors if any optional properties of `objA` have not been set to match the requirements of the return type.

As you can see in the above image TS `objA.propertyC` is of type `number` not `number | undefined` because it has been set. 

TS should allow objA to be returned as type `TypeA & TypeAExtras` because even though objA was initially of type `TypeA & Partial<TypeAExtras>` the optional properties from `TypeAExtras` have been set and match the requirements from `TypeA & TypeAExtras`...

Casting `objA` to the return type does remove this error. But it also removes the type checking for `propertyC` allowing `objA` to be returned without the required properties being set.

**Comment by MartinJohns** [comment]
Simplified example:

    interface A { val: string }

    function fubar(a: Partial<A>): A {
      a.val = '...';
      return a;
    }

Assigning values to an objects properties does not change the type of the object.

---

**Personally** I would suggest you do not mutate the object in the first place, or alternatively don't have it returned. The original reference could be re-used, and it would be possible to assign `undefined` to `propertyC`, leading to an unsoundness.

Instead I would return a new constructed object:

    return { ...objA, propertyC: objA.propertyA + objA.propertyB };

**Comment by Inrixia** [comment]
I considered this too but there is significant overhead with destruction. Plus when working with more complex types constructing the entire type at the end is messy.

I agree with the statement regarding mutating a object potentially tainting the type if it's referenced elsewhere.

I just wish there was a easy way to handle that case as as it stands there is no way I can see where a object can be updated without needing to destruct... Though I guess that's intended.

**Comment by Inrixia** [comment]
So after thinking about it I've gone with just having my return type be the same as my input having all the extra properties optional like this example:

```ts
function foo<A extends TypeA & Partial<TypeAExtras>>(objA: A): A {
	objA.propertyC = objA.propertyA + objA.propertyB;

	objA.propertyC;
	return objA;
}
```

While this isnt great as it doesnt give strict type checks its better than nothing and removes the horrendous overhead of destructing that would be required if not mutating the object.

It would be great to have support for mutating objects in the future, the functions I'm working on actually don't return and are intended to modify the object passed. But I guess adding support for something like that kinda breaks type safety and would require some new way to define types that change after a function call happens...

Thanks for the help.
