### ISSUE TITLE
Cannot assign an instance of the Intersection of a Record and a Partial of a Record

### ISSUE THREAD

**Issue by CamilleDrapier** [microsoft/TypeScript#44196]
# Bug Report

Defining an object  as an intersection of a Record and a Partial of a Record with a key more specific and a different value type does not allow to set the instance object with the Partial type.

Not completely sure if this is a bug or a design limitation. :bow: 

### 🔎 Search Terms

- Record intersection partial 

Might be related to: https://github.com/microsoft/TypeScript/issues/17867, https://github.com/microsoft/TypeScript/issues/38977, 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Record`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210520#code/C4TwDgpgBAYgrgLwSA8gIwFYQMbCgXigCUcB7AJwBMAeAZ2HIEsA7AcwBop6m2A+KAGRQACgENywRqIA21Etgo0AROPKiQw8qUgSQSztxasA2gF1evANwBYAFB3pEPADNEyAFyw3qTDjyEAbwBfSygAejCoAHcKAGtaO1ckEAIoAKhRNGxPFSylKBDwyJjyeMTvADpM7FTc7CVQiOi4hNsk5CryNQ0tHVBUs0bilvLkzu7NbQhdAbqlUyHm0ta7BWZ6DKzU9pAqrMWS+IzmSihGWigFLr9pFJZnaYhT0QuAA0M2V9XSdbxVdUmfRShB24wBvWmoAOLWOp3Olwo5Bud2YDyRzzeHxMpi+9ja3lS6X+PSmuk8xjmpgKi0opAgF2YpDwh08rwAKuBoAByLFmLlnBlMjK0WiMVjMTKOKDAUjSzlQHkMIxcioACgATABmdXqgCUuJ2hIyXXBpNA5MpBWFXmS6CwuGhy1GyCN1Ry1X0xomELJUApHqphSatPpUEZzLirI5kAVvNM-Ph4eFovFkugMrlMcVPFYKo12r1BoJgU22Sgc04xMBkJAFoDVpeNuQdr8NLpgojpSj8uzRj5ArDQoUAFswOI09LZaAs1i81qAKyF53AtKl915SsmklAut5QPW0TMFKN+C23wOopLMr45KurLr+qb71m2vlj3Uy8QAAekFwTyg0xaOQ3YzkqbAJh2yZihKaBShm07cnGUAAD5QHAJwQM4LBPHOBb6nYdgIcQEAAG7TLQECns257+CI4iSDIchkFQ1AqFu1a6J6cYWIIxFXDQWIGGBrBWARtiOHgSJkeQFFUa+JDSbJ3gtrghJBsMTq2FJ5GUcWq5um+eQfk0hytNpMm6WM1S1B6jrXuZSlWexPr9IQgyXqZdgOZZHRVi5K7+nudkrLYawbN5ckAIJbIQEWVNUwWwgOVxIrgtxnKijwYlA7zCbiYWSaROlRc5L6pHFTnPkCiWHnCFwpciGVov+ja5TmZi4l5RUWXJrqlTufqWupUAhpBLI5dGiHCf2iZCi8KYwXBU49rOapajq+G2EAA) ; [edited](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210527#code/C4TwDgpgBAYgrgLwSA8gIwFYQMbCgXigCUcB7AJwBMAeAZ2HIEsA7AcwBop6m2A+KAGRQACgENywRqIA21Etgo0AROPKiQw8qUgSQSztxasA2gF1evANwBYAFB3pEPADNEyAFyw3qTDjyEAbwBfSygAejCoAHcKAGtaO1ckEAIoAKhRNGxPFSylKBDwyJjyeMTvADpM7FTc7CVQiOi4hNsk5CryNQ0tHVBUs0bilvLkzu7NbQhdAbqlUygh5tLW9pBx9Um+lMI5pYgAD0hcCEooaa1yTwADABVwaAByOceoRlooZlI8UVpaRlYzEyjigwFIoIeUEehjYZigAB8oHBmJQIM4WKdHhUABQAJgAzLjcQBKa52OwKZj0DJZVJrKpZJYleIZFFvD4KLp+aQpFjOaanDIfa4w1hk2yU6mqTa9ab9Qj06U9Ka6JktVlnd5QTnkbm85j83VnX5QEUMIxmcWjZCpdJKrZykCeYxzBaFJqUUgQD5fPDMm73SBQ0VmV5a31C-6A4HQMEQoPQ81sLF4wkk8VrW0ZLoylWgZ2ugpCrzJdBYXBqlbWnZpGnZKBzTj22W6AvVeYFJae72fb7LWIByGJngmUxhn1935RoFoEFx0AJ0UpglE0nVrPVHLtps55XbNt5N3F+Cl3wVopQbsTv1xQeLpOj8e9vAKAC2YHEMdB4IXTyXOIJABWdN10COstzyHcJhbfMoBddsjxNURmBSE0T2QMs-ErMo2m8Dcsgg+ooNzfcG3bTsL0OY5gEFC4KDvP8HyfCMpwBGc5x-IcQwWRFkVRdFmExAC0zXexbF-YgIAAN2mWgIHQnxy38ERxEkGQ5DIKhqBUXcHV0fQuAfMwLEESTORoUUDAfKxyVsRw8F1GTyDkhTPBIJyXO8TDcFtd1hirWxHNk+S8LAzcyLyCimmZVoguckKxmqWp22w2LpOChSNj3R0BlMVK7DizzEt0mCa3gw98rEyUHPS+KFIAQVpQhCoSjpqlSjV2W1ChdVwHk3gNAVjWFUVxWqqAWoakq8xrSbKmbGaOuQzUOR6vUBsNQUTTNEdLVsubkg3abSPK+o3S7L1r37BjgyMscupYv42K-ecuKY4TV3FIA)

### 💻 Code

```ts
type FuzzyObject = Record<string, string> & Partial<Record<"arrayProperty", string[]>>;

let fuzzy: FuzzyObject = {}; // works
fuzzy = { abc: "abc" }; // works
fuzzy.abc = "abc"; // works
fuzzy.arrayProperty = []; // works
fuzzy.arrayProperty = ["abc"]; // works

const abc = fuzzy.abc; // works and is correctly infered as `string`
const arrayProperty = fuzzy.arrayProperty; // works and is correctly infered as `string[]`

fuzzy = { arrayProperty: ["abc"] }; // does not work: `Type 'string[]' is not assignable to type 'string'.(2322)`
fuzzy = { arrayProperty: ["abc"] } as FuzzyObject; // works
fuzzy = { abc: "abc", arrayProperty: ["abc"] }; // does not work: `Type 'string[]' is not assignable to type 'string'.(2322)`
fuzzy = { abc: "abc", arrayProperty: ["abc"] } as FuzzyObject; // does not work: `Type 'string[]' is not comparable to type 'string'.(2352)`
fuzzy = { abc: "abc", arrayProperty: ["abc"] } as any as FuzzyObject; // works
fuzzy = { abc: "abc", arrayProperty: "abc" }; // expected error: `Type 'string' is not assignable to type 'string[] | undefined'.(2322)`

type ReverseFuzzyObject = Partial<Record<"arrayProperty", string[]>> & Record<string, string>;

let reverseFuzzy: ReverseFuzzyObject = {}; // works
reverseFuzzy = { abc: "abc" }; // works
reverseFuzzy.abc = "abc"; // works
reverseFuzzy.arrayProperty = []; // works
reverseFuzzy.arrayProperty = ["abc"]; // works

const reverseFuzzyAbc = reverseFuzzy.abc; // works and is correctly infered as `string`
const reverseFuzzyArrayProperty = reverseFuzzy.arrayProperty; // works and is correctly infered as `string[]`

reverseFuzzy = { arrayProperty: ["abc"] }; // does not work: `Type 'string[]' is not assignable to type 'string'.(2322)`
```

### 🙁 Actual behavior

The following does not work:

```ts
type FuzzyObject = Record<string, string> & Partial<Record<"arrayProperty", string[]>>;
const fuzzy: FuzzyObject = { abc: "abc", arrayProperty: ["abc"] }; 
```

Has the error:

```
Type '{ arrayProperty: string[]; }' is not assignable to type 'FuzzyObject'.
  Type '{ arrayProperty: string[]; }' is not assignable to type 'Record<string, string>'.
    Property 'arrayProperty' is incompatible with index signature.
      Type 'string[]' is not assignable to type 'string'.(2322)
```

### 🙂 Expected behavior

The above should work with no error.

**Comment by KristjanTammekivi** [comment]
I guess it's related to why arrayProperty isn't allowed in
```typescript
interface FuzzyObject {
    arrayProperty?: string[]; // Property 'arrayProperty' of type 'string[] | undefined' is not assignable to string index type 'string'.(2411)
    [key: string]: string;
}
```

**Comment by CamilleDrapier** [comment]
Thank you for taking the time to provide explanations. 

I see, it seems very reasonable. But isn't this behavior somewhat inconsistent? (the fact that for example I can set/read the `arrayProperty` even if nothing can honor its type in theory?) It seems like once I set the `fuzzy: FuzzyObject` variable, it doesn't really behave like an intersection of type but like the the `Partial<Record<"arrayProperty", string[]>>` overrides the base definition (which is what I originally intended to achieve, maybe unreasonably).

I think this might have to do with the following behavior difference:

```ts
type NeverType = number & boolean; // Resolves to "never"
const neverConst: NeverType = 1; // expected error: `Type 'number' is not assignable to type 'never'.`

type NearlyNeverType = string & string[]; // Resolves to string & string[]
const nearlyNeverConst: NearlyNeverType = "1"; // Expected error, but message says: `Type 'string' is not assignable to type 'string[]'` (and vice-versa when assigning an array)
```

I suppose that `NearlyNeverType` is not resolved to `never` because `string[]` is not a primitive type; and it sounds like if it was an easy problem to solve, it would have been done already.
