### ISSUE TITLE
Types not been check when assign to a variable

### ISSUE THREAD

**Issue by striwensko** [microsoft/TypeScript#44195]
# Bug Report

When I assign an object to a variable and it has extra properties, those extra properties aren't detected to mismatch the type

### 🔎 Search Terms

mismatch properties

### 🕗 Version & Regression Information

4.2.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAsghgJwOYEsB2AhOBnCBlUAG2gF4oBvAW0VTQC4ptgF0kBfAbgCguBjAezRNGRUhS5Qo1ZOgYAiAIwAGMAA85AGglQwcACZ7W8gCxrNXTjwBmAVzS9gKQVABGNlIT0BhPHgAUAG5whAzwMpg4+KIAlAwB-Ch64pICQvzEAHSE-EiBwdHcbDxuHt6+fkwgxAVcJZ4+-uTa0rTyymZakroGRlBypupabDVAA

### 💻 Code

type MarginBaseStyle = {margin: string};

const style = {
  margin: "10px",
  padding: "4px",
};

function buildCSS(val: MarginBaseStyle): void {
  console.log(val);
}

buildCSS(style);

### 🙁 Actual behavior

No error detected

### 🙂 Expected behavior

I expect the type to not match, this occurs if I add the value directly but not if the value is coming through a variable. However if the type of the property in the function is missing a property or the type of the property isn't correct it detects the error.

**Comment by MartinJohns** [comment]
This is working as intended. Objects are allowed to have additional properties.

**Comment by striwensko** [comment]
Thanks for the quick response, I'm new to typescript and I got the following question:
How I can make it not have extra props? And why it marks error if I pass the value directly instead of sending the var, shouldn't the behavior be consistent?

**Comment by MartinJohns** [comment]
> And why it marks error if I pass the value directly instead of sending the var, shouldn't the behavior be consistent?

That's the excess property check. This is more of a linter feature than a type safety feature. You get the same behavior if your variable `style` is declared as the type by adding a type annotation: `const style: MarginBaseStyle = ...`

> How I can make it not have extra props?

By hoping for #12936 to be implemented someday. There is no solution currently, allowing additional properties is an inhering part of the type system.
