### ISSUE TITLE
Check types for right-hand literal values.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#44194]
# Suggestion

## 🔍 Search Terms

Check types for right-hand literal values

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [v] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [v] This wouldn't change the runtime behavior of existing JavaScript code
* [v] This could be implemented without emitting different JS based on the types of the expressions
* [v] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [v] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Check types for right-hand literal values.
I suggest a `##` syntax for right-hand type checking.
```typescript
let str:string = #'LiteralType'# 'LiteralType' // ok
let str:string = #'LiteralType'# 'FooBar' // wrong
```
Same as
```typescript
let FooBar:'FooBar'='FooBar'
let str:string = FooBar
```
Also as function parameters
```typescript
function foo(bar:string){
}
foo(#'bar'#'bar')//ok
foo(#'bar'#'abc')//wrong
```
Use type reference
```typescript
interface inter{
  foo:number
  bar:number
}
let str:string=#keyof inter#'foo' //ok
let str:string=#keyof inter#'bar' //ok
let str:string=#keyof inter#'abc' //wrong
```

## 📃 Motivating Example

Sometimes we need a type checking for right-hand values not only the left-hand variable types.

## 💻 Use Cases

An event dispatcher receive string as event name, but a typed literal name must bu used in caller.

**Comment by MartinJohns** [comment]
You can achieve this easily already without special syntax.

    function id<T>(value: T): T { return value; }
    
    let str: string = id<'LiteralType'>('LiteralType')
    let str: string = id<keyof inter>('foo')

**Comment by RyanCavanaugh** [comment]
Duplicate #7481
