### ISSUE TITLE
tsserver: reload project must return a response.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#4420]
After the project is reloaded the ide should request validation of all open files or the open project. Since this should happen after the project has successfully be reloaded the request must send a response.

**Comment by mhegazy** [comment]
@dbaeumer would not calling "projectInfo" command be sufficient here? what additional information are you looking for?

**Comment by dbaeumer** [comment]
@mhegazy I am not looking for any additional information, however I want to know on the client side if the reload project request has finished successful. I want to write something like:
```typescript
tsserver.exeute(''reloadProjects", ...).then((response) => {
    // Do additional work with the server
});
```
