### ISSUE TITLE
Explore using MDN to improve DOM documentation 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#44204]
# Suggestion

## 🔍 Search Terms

- mdn
- jsdoc
- quickinfo / hover
- IntelliSense
- lib.dom.d.ts

## ⭐ Suggestion

When trying to figure out a DOM api, I often find that our built-in documentation isn't enough and that I instead have to go to MDN. It would be great if we could use MDN data to improve our documentation since MDN seems more up to date and more comprehensive than what we have in `lib.dom.d.ts`. 

On the VS Code team, we have previously used MDN for our css and html support:

- https://github.com/microsoft/vscode-html-languageservice/issues/12
- https://github.com/microsoft/vscode-css-languageservice/issues/68

Some ideas to explore:

- Pull in more documentation for types and parameters from MDN (not sure how much the lib-dom generator already does this, but many DOM types currently are missing documentation)

- Add a MDN link to the bottom of documentation

**Comment by maccman** [comment]
Love this idea!

**Comment by its-all-waves** [comment]
How is this still not a thing?! Why would you add it for 2 of 3 necessary web languages?

**Comment by Nima-MM** [comment]
So is there any solution? This is for us beginner, very very helpful to get familiar with the language we are working with.
MDN or any kind of explanation of the keyword.

**Comment by RyanCavanaugh** [comment]
We looked into this a while back and determined that the licensing of the content makes it quite difficult to move it into the .d.ts files. It's under the CC-BY-SA license but we don't have any ergonomic way to comply with the attribution requirements of that license without hugely bloating the size of the relevant files.
