### ISSUE TITLE
Improve Fuzzer, Drive Fuzzer Bugs to Zero, Expand Fuzzer Functions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#44210]
We have a (currently) private fuzzer which simply opens OSS projects on GitHub, runs some language server operations on a project, and finds crashes. This helps pinpoint stability issues in TypeScript and the server so that we can improve reliability. This issue tracks a few things:

* [x] Improving the fuzzer infrastructure: we believe that the codebase could benefit from some clean-up
* [x] Expanding the fuzzer to work on TypeScript files
* [ ] Fixing crashes found by the fuzzer: there's a couple at the time of writing, and we want to drive them down to 0
* [ ] Expanding functionality of the fuzzer: we want to start performing more involved operations to proactively catch issues

**Comment by DanielRosenwasser** [comment]
I've added one bullet point around broadening the fuzzer to work on TypeScript files; it appears we only work on JS files.

**Comment by elibarzilay** [comment]
There is currently only one open issue (microsoft/tsserverfuzzer#263) which we couldn't reproduce in any way (including asking the person who replied to the linked TS issue, #39584).  So I checked that box.

**Comment by DanielRosenwasser** [comment]
Can we say this is closed out? What is left for this one?

> Expanding functionality of the fuzzer: we want to start performing more involved operations to proactively catch issues

**Comment by DanielRosenwasser** [comment]
I suppose now that we've expanded the fuzzer, we should uncheck

> Fixing crashes found by the fuzzer: there's a couple at the time of writing, and we want to drive them down to 0

**Comment by gabritto** [comment]
@DanielRosenwasser @amcasey can we close this since Andrew is rewriting the fuzzer?
