### ISSUE TITLE
Investigate deoptimization diagnostics tooling

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#44211]
We've been diving deep into perf. One place we find tooling lacking is in identifying deoptimizations in the VM. @rbuckton has had some neat experiments which we might be able to leverage to identify polymorphic/megamorphic usage sites. Work closely with @amcasey here to get a sense of what is and isn't useful.

Also, identify some baselines within the tooling to help drive meaningful goals for users. For example, a use-site might have 500 different object shapes passing through it - is it meaningfully faster to reduce that to 200?

Ideally, this would be usable by the broader team and partner teams who also write CPU-bound Node.js code.

**Comment by Kingwl** [comment]
May I request that be investigation public (Or already public but in somewhere)? 
Very interested in this stuff.
