### ISSUE TITLE
Proxying namespaces through another file does not work.

### ISSUE THREAD

**Issue by imatlopez** [microsoft/TypeScript#44223]
# Bug Report

### 🔎 Search Terms

proxy namespace 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[StackBlitz link with relevant code](https://stackblitz.com/edit/bug-type-proxy?file=index.ts)
~[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wCYFMxwGZQQhwDkUWyAxjALQDuWArsCQNwBQMAnmFpjnAC8cbrwh44oSLAAUZCtXpMWASg7tKEAHap4AQWrBtAZQAWWLDABc-MAG0SBmEa1mLMEgF0htgHROXN0sOUT4Ak3NLH2x7R0MI9y91PEYteK1JVHCdAAVCMAAVHiwZCAAjACsbZC0uFRtyisy4bKCYXzB8ot5UXypnbXQAbzgAelGW9Lbmmq4AfnY4JbhyGEYoDMahYVbI9s6IQuLe-pdUDgBfdiA)~ @nmain pointed out that it's just matter of changing the access to not use dot notation, no such thing works in the StackBlitz example.

### 💻 Code

```ts
// module.ts
export declare namespace Foo {
  export const Bar = 42;
}
export class Foo {
  isBar(num: Bar): true;
  isBar(num: number): false;
  isBar(num: number): boolean {
    return num == 42;
  }
}

// proxy.ts
import * as module from './module';
type module = typeof import('./module');

export const Foo: module['Foo'] = module.Foo;
export type Foo = module['Foo'];

// index.ts
import { Foo } from './proxy';

const num: Foo.Bar = 42; // Foo is typed any?

function isBar(num: number): asserts num is Foo.Bar {
  const foo = new Foo(); // Foo is not typed any
  assert(foo.isBar(num)); // Overloads recognized
}

isBar(num);

num; // typed any
```

as second example

```ts
import * as dep from 'react-weui';
type dep = typeof import('react-weui');

const ActionSheet: dep['ActionSheet'] = dep.ActionSheet;
type ActionSheet = dep['ActionSheet'];

function isActionsPropType(obj: any): obj is ActionSheet.propTypes.actions { // ActionSheet is any?
    return obj == ActionSheet.propTypes.actions;
}

```

### 🙁 Actual behavior

in `index.ts` the "proxied" class Foo can be used, but when the namespace property Bar of Foo is used (Foo.Bar) Foo is `any`, hence Foo is not recognized some of the time.

### 🙂 Expected behavior

in `index.ts` the "proxied" class Foo can be used, but when the namespace property Bar of Foo is used (Foo.Bar) Foo is namespace Foo because the proxying of Foo is not changing the types, in fact the file `proxy.ts` should be considert an identity of sorts.

**Comment by nmain** [comment]
Your playground link gives a TS2713, and when that is corrected everything seems to work as expected.

**Comment by imatlopez** [comment]
mmm I can't replicate it but I did find a way around it using a .js and .d.ts
