### ISSUE TITLE
When using numbers keyof lost the keys of objects

### ISSUE THREAD

**Issue by SimonChaumet** [microsoft/TypeScript#44231]
# Bug Report
Duplicate of #44170 which has been closed due to a contributor which marked it as a question

### 🔎 Search Terms
keyof, number, identity, cif

### 🕗 Version & Regression Information

In playground from 3.3.3 to 4.3 beta

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about keyof

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWwJ4DFzXmAjAHgFgAoRRAQUQFMAPKKsAEwGdEAlKiOAJ0f2ajcYYAOYAadpx58BQ0RLAhkAIyrcAfOrEkyAIWp0GLSV179Bw8YgDeAbQAK3OAAc1UVImGIA1lVRxgCgBdAH4ALh8-AIoHJ1dudyCAX3USdQAKAEMI8gllCN0ASgjbXMRdIJsdRG4qKBBuJFtMvKCAbhIkkhIuMAFEWxpcCVRcSoBeFAwsWARcdOtqtEcXCMXSMkR8xGHqpO1ifaqNtHIAGxhM5jXqsmW4iIAiZUeDsi7Dwo7iEgB6X8QAElEAB3TJgKCIKBwRAiOqIcHUbhObieQJoRDOOKIRhwKjMMAAckhtBgAj+AIAEmoqFCABa0sAIAxk2CiTFxNwwfGICC1TL0JEo1imWrQM6oHoIZhwM5UAB0ZzgInSQ3l9xcEjVTLAAFEaKzLCtnCNcOrUOdLsxTfKdfrDaJLVcvt1iL1+oMAEwjT0TKaYSCzPALJaoY03DZkXARAAs3r2nQk6zuFouVwjmym4Z2b0QHySLp+xH+iGptXpjOZpIElg5Li5PMy5aZkL5VAFtbUwsQwB4iEeqE9jylfVlCqVKponvNxq107tBprolniEH5qd1tX84Q9qXIg3XyAA)

### 💻 Code

```ts
function myFunction1<
  A extends Record<string, Record<string, number>>,
  B extends Record<string, {[Property in keyof A]?: keyof A[Property]}>
>(a: A, b: B): [A, B] {
  return [a, b];
}

const [x1, y1] = myFunction1({
  myProp: {
    b: 1,
  },
}, {
  myAlias: {
    myProp: "b",
  }
});

// I want to get an error if my prop doesn't exist
// Here the non existing properties create errors correctly
console.log(x1.myProp /* not an error */, x1.nonExistingProp /* throws error */, y1.myAlias /* not an error */, y1.nonExistingAlias /* throws error*/);

const [x2, y2] = myFunction1({
  myProp: {
    1: 42,
  }
}, {
  myAlias: {
    myProp: 1,
  }
});

// Here the non existing properties are not creating errors for "y2"
console.log(x2.myProp /* not an error */, x2.nonExistingProp /* throws error */, y2.myAlias /* not an error */, y2.nonExistingAlias /* does not throw error */);
```

### 🙁 Actual behavior

When using numbers the type system can't check which property is in my type and which is not.

### 🙂 Expected behavior

The type system should know which prop I can use

### Goal

Here my goal is to create a react component that accepts properties (which are mapped to css properties), and aliases that fill the component properties.

E.g :
I have a prop "size" that accepts the values "large" (which corresponds to an object {padding: 18px} but in the code it is represented by a number), "medium"...
And then I will have an alias like "big" that sets the size to "large" and other properties...

Here my goal was to constraint the possible values of the properties and aliases, in the TS discord I asked this question (how to constrain subproperties of objects while keeping the keys ?) and someone told me to use a CIF (Constrained Identify Function), that's how I ran into this problem.

**Comment by SimonChaumet** [comment]
@MartinJohns do you have something to ask me or tell me ?

**Comment by fatcerberus** [comment]
It seems like in the first call, it infers a concrete object type for `B`, while the second call infers a `Record<string, ...>` type for `B`.  Once you have a `Record<string, ...>` you can freely access any property on it--that's expected and not a bug.  What I'm not sure is *why* there's an inconsistency in type inference between the two calls for `B`.

**Comment by SimonChaumet** [comment]
@fatcerberus the CIF is used to get access to the right properties (with the extends keyword), which here is good.

The problem come from numbers not treated correctly : the numbers are considered valid as string (for `A extends Record<string, Record<string, number>>`, which I don't understand why by the way) but in the type `A` they are not considered as valid keys I think.

**Comment by fatcerberus** [comment]
> the numbers are considered valid as string

This is because:
```js
let foo = {};
foo[0] = "foo";
console.log(foo["0"]);  // "foo"
```

**Comment by SimonChaumet** [comment]
> > the numbers are considered valid as string
> 
> This is because:
> 
> ```js
> let foo = {};
> foo[0] = "foo";
> console.log(foo["0"]);  // "foo"
> ```

In javascript it works, but as you can see in the playground link : if you change `myProp: 1` to `myProp: "1"` it is not accepted by the typescript compiler

**Comment by RyanCavanaugh** [comment]
I'm still not seeing a defect being demonstrated here. Calls with different objects can create different generic inference; this is uncontroversial. The numeric key vs string key distinction leads to some weirdness in this example, but it's not a bug.

**Comment by SimonChaumet** [comment]
> I'm still not seeing a defect being demonstrated here. Calls with different objects can create different generic inference; this is uncontroversial. The numeric key vs string key distinction leads to some weirdness in this example, but it's not a bug.

"some weirdness" for me is called a bug.

If generic inference isn't the same each time, what should I use to get my type ? In the previous issue you said that `myFunction1` type wasn't correct, so what should I do to fix it ?

You said it's not a bug but there is no one able to tell me what's the right way to get this typing.

**Comment by SimonChaumet** [comment]
Does someone have an idea for this ? Or at least a way to type differently and get the type correctly

**Comment by SimonChaumet** [comment]
up
