### ISSUE TITLE
Variable of type `keyof {[k:string]: T}` is not assignable to string

### ISSUE THREAD

**Issue by emilioplatzer** [microsoft/TypeScript#44234]
# Bug Report

A variable

### 🔎 Search Terms

is:issue is:open keyof generic string 
is:issue is:open Variable of type keyof  is not assignable to string

May be https://github.com/microsoft/TypeScript/issues/42076 is similar

### 🕗 Version & Regression Information

Version 4.2.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYglhANgEygXigb1JAdgQwFsIAuAZ2ACc5cBzAGigHtgALCSgSVwDMnyqNWgF8A3AChxOaAGEmiAK6Fc6LAWIDqdYVABksBCgnSoAFXwAjRNAyYAxvKW4yJOYuUBtALqM4yTUJikhAAHmBMlMBQPAq4dsBwTCq0ELgc+MAQ5lYQACIQPDRwCUkAPPBIyGRQoZm4VVgeANYBdF4kFSjCAHwAFIWVLp1Vvv5NECBMPAaDAJQk2daY4lCrUABu+JRQDu7Oqt5Q+NVuTt4Sa9ERvZvbHuoQjMgFXszTAPIWAFYQ8QB0qUEEDI-UMVVms2Wl0uuycZD+YAUZFYvUwD0Yf0xzx4wlmFzWwhWawA9MSamFflE-FBgEwoBZoMcyHBaAQcjS6RQtLR6b98EjoNS4NUAAbjSbTTDNVq0drDMjCEVE1aUCDABSUFSYPyMWHKBUSQlAA)

### 💻 Code

```ts
type Field = {typename:string, otherInfo:string};

type Column = {name:string} & Field;
type Table = {columns:Column[], id:string};

export function generateTableDefinition<Fields extends {[k:string]:Field}>(fields:Fields, id:keyof Fields):Table{
    var columns = [] as Column[];
    for(var [name, def] of Object.entries(fields)){
        columns.push({name, ...def});
    }
    // expect id to be assignable to string because id is `keyof {[k:string]:Fields}`
    return {id, columns};
}
```

### 🙁 Actual behavior

```txt
(property) id: string
Type 'keyof Fields' is not assignable to type 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.(2322)
input.tsx(4, 33): The expected type comes from property 'id' which is declared here on type 'Table'
```

### 🙂 Expected behavior

No errors becaus id is a `keyof {[k:string]: T}`

**Comment by emilioplatzer** [comment]
I found a workaround:

I add `& string` to the `id` definition

```ts
export function generateTableDefinition<Fields extends {[k:string]:Field}>(fields:Fields, id:keyof Fields & string):Table{
```

**Comment by jcalz** [comment]
This is working as intended, see the release notes for [TypeScript 2.9: Support `number` and `symbol` named properties with `keyof` and mapped types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-number-and-symbol-named-properties-with-keyof-and-mapped-types).

**Comment by emilioplatzer** [comment]
@jcalz, Oh, I see. But I do not understand why. Who needs that keyof returns `number | symbol ` in a mapped type that is known to be indexed only with `string`? Seems like a design error to me. But I already had this feeling other times and I was wrong.

**Comment by RyanCavanaugh** [comment]
Remember that constraints set a *minimum* on a type, not a *maximum*. Something is allowed to have a string index signature *plus* symbol-named properties; index signatures are a restraint on what kind of values can inhabit the properties of a certain name, not a restriction on what other kinds of keys can exist.

**Comment by emilioplatzer** [comment]
Thanks @RyanCavanaugh, 

Then `string` and `number` are interchangeable as index signatures?

```ts
type One = {[k:number]: string};
type Two = {[k:string]: string};

function okOne(x:One){
    var y:Two = x;
    console.log(y);
}

function okTwo(x:Two){
    var y:One = x;
    console.log(y);
}
```

[Playground](https://www.typescriptlang.org/play?#code/FAFwngDgpgBA8gO1gXhgbwNoGsBcCCuAtgEZQBOAujjAM4hkCWCA5gL4DcoksAKgO4B7GKky46jFlVr0mbTsABm+BAGMQDAQhgCsiKAAoAHjj0BKNMBhWYANwCGZGGBz8hqQ52swVmmgIA2UAB0-gLM+mCmnKzAispqGlo6rkYuguaW1vaOznrCMB6ZVj4IfoEhYRFRwKxAA)
