### ISSUE TITLE
>Support for the experimental syntax 'decorators-legacy' isn't currently enabled< persists after adding true in tsconfig

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [microsoft/TypeScript#44239]
I did as is stated in the [introduction to decorators](https://www.typescriptlang.org/docs/handbook/decorators.html), I added `"experimentalDecorators": true` to "compilerOptions" in tsconfig.json.

However, after restarting my entire IDE, the error persists. 

My project is very simple. It was created using "create-react-app" in Webstorm. I haven't fumbled around with my config files, they're almost all entirely clean as my project is still fairly new and small. 

tsconfig.json
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ]
```
package.json
```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^26.0.23",
    "@types/node": "^15.6.0",
    "@types/react": "^17.0.6",
    "@types/react-dom": "^17.0.5",
    "axios": "^0.21.1",
    "framer-motion": "^4.1.17",
    "history": "^5.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-loader-spinner": "^4.0.0",
    "react-promise-tracker": "^2.1.0",
    "react-redux": "^7.2.4",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "redux": "^4.1.0",
    "typescript": "^4.2.4",
    "web-vitals": "^1.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.14.0",
    "@babel/preset-env": "^7.14.1",
    "@babel/preset-react": "^7.13.13",
    "autoprefixer": "^9.8.6",
    "babel-loader": "^8.1.0",
    "file-loader": "^6.1.1",
    "url-loader": "^4.1.1"
  }
}
```

... This is all I have in terms of config files at the moment. 

* Do I have to do something more besides what is stated in the [introduction to decorators](https://www.typescriptlang.org/docs/handbook/decorators.html)?
* Is this a bug?

**Comment by IllusionMH** [comment]
Are you sure this error comes from TS?
Can be Babel error https://stackoverflow.com/questions/52262084/syntax-error-support-for-the-experimental-syntax-decorators-legacy-isnt-cur

**Comment by Sebastian-Nielsen** [comment]
@IllusionMH I am not sure. To be frank, I almost no clue what's going on when it comes to configuring config files. As far as I know, that question (and answer) uses webpack though, which I don't, so I don't see how that could help.

How would I know whether it's a Babel error?

**Comment by IllusionMH** [comment]
Message format and searches suggest it comes from Babel ([source](https://github.com/babel/babel/blob/b1f57e5fb58f7e890b3be58965e014f6fd4950e0/packages/babel-core/src/parser/util/missing-plugin-helper.ts#L303-L306)) so you should look for Babel related solutions in scope of CRA which is outside of this issue tracker.

**Comment by Sebastian-Nielsen** [comment]
Just followed the accepted answer on the SO post you linked to, and it actually resolved the issue. I am no longer getting that error msg! 😄
