### ISSUE TITLE
Object spreed inference got broken with inlined conditional from 4.2

### ISSUE THREAD

**Issue by safareli** [microsoft/TypeScript#44247]
# Bug Report

### 🔎 Search Terms

spreed conditional inline type inference 

### 🕗 Version & Regression Information

- When did you start seeing this bug occur? **4.2.3, 4.3.0-beta**

- This changed between versions 4.1 and 4.2
- This is the behavior in every version I tried (**4.2.3, 4.3.0-beta**)
- Correct behavior is in old versions I tired (**4.1.5, 4.0.5, 3.9.7**)

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/C4TwDgpgBAYg9nKBeKBvKAzBAuKBnYAJwEsA7AcygF8BYAKHtElgRmIC9kXEAyWD+o3DQ2nFPSiSoAHzSYOAflwBXUgBMIGMhDUAaTHHZLVGraR3UJU2ei3tcBEhX1Z7UUsoC2AIwiFLDHQAxnCkBAZwuPCIKLY4UABECQEhYcBQqWq43ggANhAAhqRcRMoQgnQA9JVQuKj01VKSdkpQJpraagDcDTVNrq3tZjo9VTVUMmi9TfJujmTko439hrgePn5L4-Sp4XZcmVAKaBN1drhJLqsAjLRjUGCECBhQwAAWBekABnZfUMR4KAFPDEcikYjefKvRBfURfHahPYcAD6UQ4XDsFUaBVyuVebwBUAA7nBCABrQHAqAQAAekCCwB0CLSETs1yirHRsQAdLysHB9LzuXY7rSwKT0hhVAziKFXsIAJJ4AA8ABUAHwACkIEDwuFVAEp9XIdcBlIRijq8F0UojJc8OAAmDlwURcVBC-mC3lMCBKzWHY6oU5oc6JBJXey3A13Xb2uB2ADMLrdPL5CG93N9SuVoi1gZOtVDHAuEYMUaoMYq0wAQsp0qqCYC1HBde44OkSeT9ABVAByAFEABoABQHAGFVQOACLMvYO9gAFhTXLQnozUCFAdCaiOhbOJfDkew0buy0kAD0r9eL9NVcIoAByWyKBxEBaTIadG0DNZeXz+LIX7mN0ERvk4izUI+-yAqQHZAngIJggUkLQMAiC+k+0SiI+3LTJI97MM+sytPMFCfuoHQgT+hitOsAEUaY35gfg74UDaVDQYScHpMCSGkChULofKRHRFAfAvnMbGQa4f4bIQHG4fhUiEdAxEtOBH5AZRwygb+7j-n4jFUSMLFkZBnEwe2vGIaCAmodCIlqZJmnseWckAYpeH3DMUCqYCCYPE8kCEKAT52NBBQ6v8pAhJ4YCfBC+TeeevmqU+5nGbpXGwfBfF2YJaEYQ+j7mUpPm+SpJXAToOXWQh-GFY5mGldJuGao6iaOo6BrTAA4hAwDAB+7yEn4Tz+KE+oAMrYIu3KOtyib6PNibcgADAAtL4wAFNMcoAG5+CCiJ+bN83XNyACsK0bdd+hrQAnNyADs+KEuOADyACyI4KgAMgO01QAAUj202qrACqDgAhNWgRAA)

### 💻 Code
```ts
type Foo = { foo: string }

type FooFiz = Foo & Fiz

type Fiz = 
    | { fiz?: undefined, foz?:undefined }
    | { fiz: string, foz: number }

const foo: Foo = { foo: "" }
const cond: boolean = true

// : {
//     fiz?: undefined;
//     foz?: undefined;
// } | {
//     fiz: string;
//     foz: number;
// }
const fiz = cond ? {} : {fiz: "", foz:1}
// proof that `fiz` is asignible to `Fiz`
const fiz_: Fiz = fiz

// all this works as expected
const foofiz1: FooFiz = {...foo, ...fiz}
export function typeIs<T>(res: T): T { return res; }
const foofiz2: FooFiz = {...foo, ...typeIs(cond ? {} : {fiz: "", foz:1})}
const foofiz3: FooFiz = {...foo, ...typeIs<Fiz>(cond ? {} : {fiz: "", foz:1})}


// But This does not work, UNEXPECTED
const foofiz4: FooFiz = {...foo, ...(cond ? {} : {fiz: "", foz:1})}
//    ^^^^^^^
// Type '{ fiz?: string | undefined; foz?: number | undefined; foo: string; }' is not assignable to type 'FooFiz'.
//   Type '{ fiz?: string | undefined; foz?: number | undefined; foo: string; }' is not assignable to type 'Foo & { fiz: string; foz: number; }'.
//     Type '{ fiz?: string | undefined; foz?: number | undefined; foo: string; }' is not assignable to type '{ fiz: string; foz: number; }'.
//       Types of property 'fiz' are incompatible.
//         Type 'string | undefined' is not assignable to type 'string'.
//           Type 'undefined' is not assignable to type 'string'.(2322)
// Getting this error on: TS:4.2.3, 4.3.0-beta
// on versions TS:4.1.5, 4.0.5, 3.9.7 this COMPILES JUST FINE!
```

### 🙁 Actual behavior

`foofiz4` is raising compile error.

### 🙂 Expected behavior

`foofiz4` should not raising compile error.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior to prevent a runaway combinatorial explosion (which was actually happening; this is not a theoretical concern but a real one). Some code patterns writes very large sequences of conditional spreads, so we collapse them into a single object type with optional properties rather than generate a union `2 ^ N` types.
