### ISSUE TITLE
Return type can be inferenced, but can not narrow in function branch

### ISSUE THREAD

**Issue by xyuanbuilds** [microsoft/TypeScript#44246]
# Bug Report

```
type Key = 'p1' | 'p2'
type S = {
  p1: { a: string };
  p2: { b: string };
};

function TTT<T extends Key>(p: { a: T }): S[T] {
  if (p.a === 'p1') {
    return { a: '111' }; 
    // Type '{ a: string; }' is not assignable to type 'S[T]'. Type '{ a: string; }' is not assignable to type '{ a: string; } & { b: string; }' Property 'b' is missing in type '{ a: string; }' but required in type '{ b: string; }'.ts(2322)
  } else {
    return { b: '1232' }; // Error too
  }
}

// inferenced: const Test: { a: string }
const Test = TTT<'p1'>({ a: 'p1' });
````
why this happend, how return type can  be narrowing in function scope
### 🕗 Version & Regression Information
latest

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hJQLxQORgIwqgH1WATCgFCiRQDKSUA3kVFBgFw1QCGzAzsAE4CWAdgHMoAXwDcdBvmbUoAI048Bw8UVVEAZgFd+AY2C8A9vygAVcwB5TUCAA9gEfgBMOseAD4AFGBltm1kQBKZnIAbVMAXRpJXg0obwA6ViREZDRMQOj6em4IYC1uE1l2VHQyrHEoSXoAehqzcGgUYsU+ITFRLF5XfkNgNg4OXkF+VjkAG2hgQyhSJrDIlASGsma-KC42wQ6RLp6+gaGRscnZmbnUFo2ldtEoADIWBWutnawABW5DSG5QVDk9lAALbdIZCKACWaNS7rTbKN7yLT9XIARy0vFyTghJgua2ecNuuwSwA4nnwAGZ8PhApIRDZxhxoLRslBcvlCk9mCh0BTCKIOnUoABRbhfbhnQy0tREIiCgQaCC5PQQLG6YxcMwQLi+EoElRENX8DWmLX9ZDmUwWdIoLxXa2iQJiQUAWQQaqc0EEhi1UAAFoqIEA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by fatcerberus** [comment]
You can only narrow individual values. Inside the generic function, you can't narrow the type parameter `T` itself because TS has no way to know (in general) that it's safe to do so.

**Comment by RyanCavanaugh** [comment]
See #33014
