### ISSUE TITLE
valuesOf for enum

### ISSUE THREAD

**Issue by sarahBuisson** [microsoft/TypeScript#44248]
Can you add the equivalent of 'valuesOf' in java for the enum ?
A method , the same in all enum, who list all the possibles enum values ?

**Comment by RyanCavanaugh** [comment]
This is already possible in userspace. See https://www.elite-corner.com/2020/07/how-to-get-names-and-values-of-enum-in-typescript.html

**Comment by sarahBuisson** [comment]
@RyanCavanaugh 
No

I know those codes, it's not that I don't know how to do it, it's just that for me it's something who should be done by an extra methode in the core lib, like ALL other languages do it.

It's ridicul to have to copy/past such a block of code each time. It should be a typescript methode

Please re open me.

**Comment by RyanCavanaugh** [comment]
This isn't something we intend to add.

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

See non-goal:
> Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.
