### ISSUE TITLE
Make incomplete scanner APIs internal

### ISSUE THREAD

**Issue by cubenoy22** [microsoft/TypeScript#44250]
# Suggestion

## 🔍 Search Terms

* scanner + label:API
* SourceFileLike
* getPositionOfLineAndCharacter
* getLineAndCharacterOfPosition

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

* `ts.getPositionOfLineAndCharacter` should be marked with `/* @internal */`
* `ts.getLineAndCharacterOfPosition` should be marked with `/* @internal */`

These methods take an argument of `SourceFileLike` at first, and its type is defined as:

```typescript:src/compiler/types.ts
    /* @internal */
    /**
     * Subset of properties from SourceFile that are used in multiple utility functions
     */
    export interface SourceFileLike {
        readonly text: string;
        lineMap?: readonly number[];
        /* @internal */
        getPositionOfLineAndCharacter?(line: number, character: number, allowEdits?: true): number;
    }
```
in `src/compiler/types.ts` and also defined:

```typescript
    export interface SourceFileLike {
        getLineAndCharacterOfPosition(pos: number): LineAndCharacter;
    }
```

in `src/services/types.ts`. so, required implementation of `SourceFileLike` in public is only `getLineAndCharacterOfPosition`. But two exposed methods are uses all internal-marked members in actual (occurs runtime error). 

## 💻 Use Cases

After this changes, These methods in `SourceFile` is still available:

* getLineAndCharacterOfPosition
* getPositionOfLineAndCharacter

**Comment by DanielRosenwasser** [comment]
@sheetalkamat @sandersn any thoughts on this one?

**Comment by sandersn** [comment]
I'm not familiar with these functions. 
@cubenoy22 Are you saying that both `ts` and `SourceFile` have members named (1) `getLineAndCharacterOfPosition` (2) `getPositionOfLineAndCharacter`? 

If I'm reading your proposal correctly, I think you want to remove the properties on `ts` because they error when called. Is that correct?

**Comment by sheetalkamat** [comment]
I dont understand the suggestion here at all.. 
`getPositionOfLineAndCharacter` on ts handles if there is `getPositionOfLineAndCharacter` on sourceFileLike or not so why should that be issue.

**Comment by cubenoy22** [comment]
@sandersn 
> Are you saying that both ts and SourceFile have members named (1) getLineAndCharacterOfPosition (2) getPositionOfLineAndCharacter?

Exactly. 

@sandersn @sheetalkamat 

Let me explain about two functions.

SourceFile is declared here: https://github.com/microsoft/TypeScript/blob/3d24b85f9e5dde6f35d6014539aeef9801e74493/src/services/types.ts#L90-L104

These methods are easy to use (just call them).

And There are also two exported functions in scanner.ts:
https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/src/compiler/scanner.ts#L387-L394
https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/src/compiler/scanner.ts#L470-L472

Both functions take `sourceFile: SourceFileLike` parameter at first.  
Of course, It is OK to pass SourceFile instances despite of `SourceFile` has own methods.
But I thought `SourceFileLike` is constructable like `PromiseLike` and `ArrayLike`:

```typescript
  ts.getPositionOfLineAndCharacter({
    getLineAndCharacterOfPosition: () => /* ... */,
  }, line, number);
```

And I found a construction case in this project:  
https://github.com/microsoft/TypeScript/blob/db01e84700023a4b728fd6e38878264160c43fbf/src/services/textChanges.ts#L1025

My above code is buildable despite of lacking `text: string` on any projects using TypeScript because SourceFileLike as public is here:  https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/lib/typescript.d.ts#L5339-L5341

But as I wrote in description, Two functions (not methods of SourceFile) use `/** internal */` marked members of SourceFileLike (I explain on below).

---

### Should we expose only `text: string` on SourceFileLike instead of marking `/** @internal */` to two functions?

[getLineStarts](https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/src/compiler/scanner.ts#L425) function which is called in [getLineAndCharacterOfPosition](https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/src/compiler/scanner.ts#L470-L472) and [getPositionOfLineAndCharacter](https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/src/compiler/scanner.ts#L387-L394) mutates `lineMap` of SourceFileLike to cache. So `lineMap?: readonly number[];` should be exposed too I think.

**Comment by sheetalkamat** [comment]
Thank you for explaination.. now i see what you mean.. The actual definition of SourceFileLike in compiler is internal but not in services so public one doesnt have the right definition. Got it

**Comment by sheetalkamat** [comment]
I think we should make SourceFileLike in `compiler\types.ts` not internal but make probably make `lineMap` internal.

**Comment by cubenoy22** [comment]
Thank you for your reply. Let me write my thoughts. SourceFileLike in compiler\types.ts is here:

https://github.com/microsoft/TypeScript/blob/9aa50d6475e0b05bcd170a1c5708548727cf45b0/src/compiler/types.ts#L3460-L3469

* Removing `/** @internal */` at L.3460 exposes `text` and `lineMap` properties
    * L.3466 `lineMap?: readonly number[];` is wrong definition (Built-in functions mutate this property if not exists), so applying `/**  @internal */` looks good for me
        * Adding `lines` field by the library is not expected behavior for users, so should we change its name to `_lines` and so on?
* This changes public APIs so "acknowledge required" before we make a pull request

### Impact to internal codes

* Exposing and marking `/** @internal */` cause no changes to codes
    * We need to change baseline
* If we rename `lines` to `_lines`, It must be fully cared

###  Impact to external codes

* I searched `SourceFileLike` in [typescript.d.ts](https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/lib/typescript.d.ts) and I found another function using SourceFileLike [here](https://github.com/microsoft/TypeScript/blob/5fde87135f25a2dbea8a98e05438e61fdad06fe6/lib/typescript.d.ts#L5273)
, so only three functions expose `SourceFileLike` to public now.
* `SourceFileLike` is not usable alone because of lacking `text` property (No one use these functions or pass SourceFile instances, I think)
* `text` property is a member of SourceFile:
    * https://github.com/microsoft/TypeScript/blob/3d24b85f9e5dde6f35d6014539aeef9801e74493/src/compiler/types.ts#L3456-L3565
    * So, exposing `text: string` causes no impact to any codes passing SourceFile instances

**Comment by cubenoy22** [comment]
And I want to try this fix if acknowledged to change public API.

**Comment by cubenoy22** [comment]
Thank you for reviewing 🙏  @sandersn @sheetalkamat
