### ISSUE TITLE
Add a react monorepo to the perf suite

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#44251]
We currently have poor coverage of both react and project references.  Adding a react monorepo would help.

Nominees:

1) https://github.com/davidkpiano/xstate
    a) Easy build (install packages with yarn, tsc -b tsconfig.monorepo.json)
    b) Already on 4.2.4
    c) Responsive maintainers (I've worked with them before)
2) https://github.com/tinymce/tinymce
    a) Much bigger than xstate
    b) Uses (many) path mappings
    c) Already on 4.2.4
    d) Slightly non-trivial build (need to prebuild icons or get errors about missing types)

**Comment by amcasey** [comment]
FYI @rbuckton @DanielRosenwasser

**Comment by sandersn** [comment]
This is now merged into the RWC repo.
