### ISSUE TITLE
Property 'coaches' is used before its initialization.

### ISSUE THREAD

**Issue by hassannawaz4399** [microsoft/TypeScript#44255]
# Bug Report

Property 'coaches' is used before its initialization.

### 🔎 Search Terms

Property  is used before its initialization.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions _Angular version 11.0_____ and _11.2.13______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about __Angular version 11.2.13_______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Coach } from 'src/app/models/Coach';
import { MatDialogConfig, MatDialog } from '@angular/material/dialog';
import { DeleteConfimrComponent } from '../../shared/delete-confimr/delete-confimr.component';
import { CoachFinderFirestoreService } from 'src/app/services/coach-finder-firestore.service';

@Component({
  selector: 'app-coach-list',
  templateUrl: './coach-list.component.html',
  styleUrls: ['./coach-list.component.css']
})
export class CoachListComponent implements OnInit {

  coachSelected: Coach;
  @Input() coaches: Coach[];
  @Output() coachEvent = new EventEmitter<Coach>();
 
  displayedColumns: string[] = ['title', 'address', 'price', ''];
      dataSource = this.coaches;

  constructor(public deleteDialog: MatDialog,
    private reService: CoachFinderFirestoreService) { }

  ngOnInit() {
    
  }

Html

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by DanielRosenwasser** [comment]
We need

1. Well-formatted issues that follow the issue template.
2. A minimal reproduction that works without external build tooling (e.g. the Angular compiler, webpack, etc.)

**Comment by RyanCavanaugh** [comment]
You can use `coaches!: ...` to indicate this is initialized externally
