### ISSUE TITLE
Duplicate members with lib.d.ts

### ISSUE THREAD

**Issue by dashaus** [Microsoft/TypeScript#4426]
I'm using `core-js` with its correspond [d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/core-js/core-js.d.ts) from `DefinitelyTyped`, but fails when I want compile my project. This only happen with `typescript@next`, with the last stable version compiles fine. 

```
/usr/local/lib/node_modules/typescript/lib/lib.d.ts(1202,5): error TS2300: Duplicate identifier 'length'.
ts/lib/core-js.d.ts(73,5): error TS2300: Duplicate identifier 'length'.
ts/lib/core-js.d.ts(74,5): error TS2375: Duplicate number index signature.
```

**Comment by mhegazy** [comment]
looks like a defintions issues. @DanielRosenwasser have you fixed these with your other changes?

**Comment by zhengbli** [comment]
This is caused by my recent addition of the interface ``ArrayLike`` to ``core.d.ts``. I think the interface can be removed from ``core-js.d.ts`` then?

**Comment by mhegazy** [comment]
oh. yes. then we need to remove that from core-js.d.ts

**Comment by DanielRosenwasser** [comment]
Looks like @vvakame is partially working on this - see https://github.com/borisyankov/DefinitelyTyped/pull/5590.

**Comment by DanielRosenwasser** [comment]
@vvakame this seems to be fixed, can you confirm?

**Comment by vvakame** [comment]
oh, sorry for late. It fixed now :+1:
