### ISSUE TITLE
TypeScript preserves 'override' modifier on properties in JavaScript esnext output

### ISSUE THREAD

**Issue by AsamK** [microsoft/TypeScript#44273]
# Bug Report

### 🔎 Search Terms
override, property, esnext

### 🕗 Version & Regression Information
Bug in new feature of version 4.3

### 💻 Code
```typescript
class Base {
    state?: string;
}
    
export default class TestClass extends Base {
    override state = "string";
}
```

### 🙁 Actual behavior
Compiling this code for target **esnext** the override keyword on properties is preserved:

    tsc -t esnext TestClass.ts

```js
class Base {
    state;
}
export default class TestClass extends Base {
    override state = "string";
}
```

### 🙂 Expected behavior
The `override` keyword should be removed from the javascript output, as it is already done correctly for methods.

(Compiling for other targets (e.g. es2021) works correctly as the property is transformed to a constructor initialization.)

Maybe related to #43535

**Comment by DanielRosenwasser** [comment]
CC @Kingwl

**Comment by DanielRosenwasser** [comment]
We have tests for this, we just didn't read them correctly.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
