### ISSUE TITLE
Compiler API: respect typeRoots in resolveModuleName

### ISSUE THREAD

**Issue by idan-at** [microsoft/TypeScript#44270]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue: I've tried `resolveModuleName`, `typeRoot`, `api` and their combinations.

## ✅ Viability Checklist

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

At the Compiler API Wiki, You can see that `resolveModuleNames` suggested implementation treats node modules packages typings and custom typings differently ([here](https://github.com/microsoft/TypeScript-wiki/blob/master/Using-the-Compiler-API.md#customizing-module-resolution)).

This means anyone that uses the `ts.resolveModuleName` API has to implement the fallback and search on `moduleSearchLocations` (which I assume, we'll get those by reading the `tsconfig` and scanning for the `typeRoot`.

I am not sure whether this is a bug or not, but I would assume `ts.resolveModuleName` would respect the `typeRoots` given in the passed compiler options. What do you think? Is there a reason it doesn't behave this way?

NOTE: I've not just relied on the example, I've tested it myself.

## 💻 Use Cases

Any tool that uses the compiler API will need this, for example, I'm writing an ESLint plugin that makes sure every dependency either comes with type declarations or it has the corresponding `@types` package installed next to it. (It's [here](https://github.com/idan-at/eslint-plugin-package-json-dependencies))

Thanks!

**Comment by sheetalkamat** [comment]
Is this related to #37958 and to be handled in #39708 ?

**Comment by idan-at** [comment]
Yup, it's related, missed that one.

Thanks for working on that.

**Comment by rdsedmundo** [comment]
Not sure if it's related, but I'm also using the example from the Wiki, and the built-in Node modules aren't resolved anymore. I get a bunch of: `Parsing error: {fs,path,stream,etc...} is not defined`. I expected that `ts.resolveModuleName` would handle those provided that compilerOptions.moduleResolutionHost=2 (Node).

@sheetalkamat is this behavior expected?
