### ISSUE TITLE
Regression in 1.6 with editing 

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4428]
We seem to be aggressively autocompleting even in places where we're making a new declaration.  This is a regression from 1.5 (incl. with VS 2015):

```TypeScript
class Foo {
  // type "star(" here modulo quotes
}
```

Expected behavior: no autocomplete
1.6 behavior: autocompletes to "animationStartTime("

**Comment by danquirk** [comment]
In VS2015 RTM we don't autocomplete here. The list appears by typing a completion character like that would leave you with ```star(```.

**Comment by jonathandturner** [comment]
Would it be possible to fix this for the 1.6 release?  It's pretty annoying, imho.

**Comment by mhegazy** [comment]
We could try. not sure if we can get it before 1.6 is out. there are already a lot of other issues.

**Comment by DanielRosenwasser** [comment]
Duplicate of #3377.
