### ISSUE TITLE
unions of objects are annoying

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#44288]
# Bug Report

### 🔎 Search Terms
Object union

### 🕗 Version & Regression Information
4.4.0-dev.20210526

### ⏯ Playground Link
Will add one later, writing this on my phone

### 💻 Code

```ts
interface Foo {
    foo: number
}
interface Bar {
    bar: string
}
declare const baz: Foo | Bar

const qux = baz.bar //error: bar doesn't exist on Foo|Bar
```

### 🙁 Actual behavior
The type is narrowed to the intersection of the two types, making it impossible to narrow it without casting it

### 🙂 Expected behavior
It should narrow to something like
```ts
{
    foo?: number
    bar?: string
}
```

**Comment by MartinJohns** [comment]
That would easily lead to unsoundness:

    const bar = { bar: "", foo: "" };
    const baz: Foo | Bar = bar

---

This also looks like a duplicate of #36194.

**Comment by DetachHead** [comment]
In that example it would correctly fail because `foo` can only be `number | undefined`, not `string`. Is that the unsoundness you're referring to?

**Comment by canonic-epicure** [comment]
No, current behavior is correct. Unions are sum types. You don't know which variant of the union this value represents. Need to perform "case" matching on it (so called "pattern matching") to know that. You are asking to reduce the type-safety.

**Comment by DetachHead** [comment]
ah i see now. my suggestion would mean `{}` is a valid value, which is wrong
