### ISSUE TITLE
WebAssembly: ExportValue not callable

### ISSUE THREAD

**Issue by behunin** [microsoft/TypeScript#44285]
# lib Update Request

## Configuration Check

My compilation *target* is `ESnext` and my *lib* is `the default`.

## Missing / Incorrect Definition

https://github.com/microsoft/TypeScript/blob/fb6c8392681f50a305236a7d662123a69827061f/lib/lib.dom.d.ts#L19245

> This expression is not callable.
  No constituent of type 'ExportValue' is callable.

## Sample Code

I am seeing this error on all `ExportValue` functions defined.

## Documentation Link
https://www.w3.org/TR/wasm-js-api-1/#exported-function-exotic-objects

**Comment by RyanCavanaugh** [comment]
Please fill out actual Sample Code; we cannot guess what you were writing

**Comment by RReverser** [comment]
@behunin You need to explicitly cast export value to function, as export value can be several different types and there's no guarantee it's callable.
