### ISSUE TITLE
Incorrect inferance of never type (regression in 4.3.2)

### ISSUE THREAD

**Issue by marijnh** [microsoft/TypeScript#44293]
# Bug Report

### 🔎 Search Terms

"4.3" never

### 🕗 Version & Regression Information

The code typechecks in 4.2.3, but no longer does so in 4.3.2.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta&ssl=1&ssc=1&pln=2&pc=1&strict=true#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVxsAZxgAoBKOAbwCg44AbYeBCVAEwC44Uk664AfOESiYUAczgBeLjzoBuGnADaAIgAWmFQF0AdMygBRAIZo1xAlIB8iFilZShpBbUwI4xAITM25KIyRQKM5waDgEEAw6dBBixN52HlHA4jBqTlQAvlRAA)

### 💻 Code

```ts
export function test() {
  let found: null | string = null;
  ["hi"].forEach(s => found = s);
  if (!found) return;
  console.log(found!.length);
}
```

### 🙁 Actual behavior

The last line produces an error "Property 'length' does not exist on type 'never'". This goes away if the early return is removed. It seems that narrows the type of `found` from `null` to `never`, but that seems inappropriate in this situation (and hard to work around without `any` casts).

### 🙂 Expected behavior

I'd expect the exclamation point to be enough to make the code typecheck (as it did in previous versions).

**Comment by MartinJohns** [comment]
This seems intentional: https://github.com/microsoft/TypeScript/issues/44025#issuecomment-837028160

**Comment by marijnh** [comment]
Seems to be a duplicate of #44025, indeed.
