### ISSUE TITLE
extends `keyof` does not allow extended new keys on interfaces since 4.3.0

### ISSUE THREAD

**Issue by posva** [microsoft/TypeScript#44295]
# Bug Report

### 🔎 Search Terms

- extends keyof, missing key

### 🕗 Version & Regression Information

I saw this in 4.3.0 beta, it seems to exists in the nightly. It was working on 4.2.x

### ⏯ Playground Link

```ts
export interface GlobalOptions {
  // cannot be added or it wouldn't be able to be extended
  // suffix: string
}

// this is added by a user to extend a global customization
export interface GlobalOptions {
   // suffix: 'New'
}

export type WithSuffix<S extends string> = `${S}${'suffix' extends keyof GlobalOptions ? GlobalOptions['suffix'] : 'Suffix'}`

declare let a: WithSuffix<'hi'>
```

<details><summary><b>Output</b></summary>

```ts
export {};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210527#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgcQBsIAjTQgeTBgQiQGc4BvAKDjgHoO5tMkkI8EnkwATUcFFxoieAHcIAV0KikAciEiShPDAhxhcUKiQTRbTt3qL06BCABccejCjIA5iwC+LFlzgwABYIjCFwYmYGAJ7hcIr0aAH6xsCmse7EZIQ88XoAtggAXpg0dCygkLCIKGhYuASZ5FSlDMwWls42do5wagBywHJq3r4V0PAwUWB4AOoIQQDKXfYAPAtGICaijC5uSO4AfHAAvHAABgAkTAteV2rWtvZqG1uMANbAURDoDaRN1LRWgB+X5ZZqA+gAbXuyxAagAunAnGolo84V4zr4JNhCJgoHgdPBME45otYSs1ME1AcgA)
      

```

### 🙁 Actual behavior

Error with `suffix cannot be used to index`

### 🙂 Expected behavior

No Error

**Comment by RyanCavanaugh** [comment]
The idiomatic way to write this would be
```ts
export type WithSuffix<S extends string> = `${S}${GlobalOptions extends Record<"suffix", unknown> ? GlobalOptions['suffix'] : 'Suffix'}`
```
which works as expected.

The "narrowing" of the RHS in that position was a bug and shouldn't have happened.

**Comment by posva** [comment]
Thanks a lot for telling me the correct way of doing it!
