### ISSUE TITLE
Match C# editing of doc comments

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4430]
Currently, when you are editing a doc comment like this:

``` TypeScript
/**
 * This is my powerful foo function
 * @param x 
 */
function foo(x: number) {
    return x;
}
```

Next, hit enter after the "This is my powerful foo function" comment line.  In C#'s doc comments, you go to a new line that stays inside of the comment and aligned (using the /// comment starter)

We should likely do the same thing here and start the next line with an aligned '*' rather than going to a bare new line

**Comment by zhengbli** [comment]
I agree, VS Code currently is doing it already.

**Comment by RyanCavanaugh** [comment]
Works now
