### ISSUE TITLE
Class property expecting `null` becomes `any` on init when `strictNullChecks` isn't enabled

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#44300]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

`"strictNullChecks" : false`

[Playground Link](https://www.typescriptlang.org/play?strictNullChecks=false&ts=4.2.3#code/JYOwLgpgTgZghgYwgAgILIN4FgBQBIANzgBsBXCALmRFOOIG5cBfXBYuAZw7U10JPLIAvNVoNmQA)
      

### 💻 Code

```ts
interface A {
	value: null;
}
class A {
	value = null; // Property 'value' must be of type 'null', but here has type 'any'.(2717)
}
```

### 🙁 Actual behavior

`null` becomes `any`, which throws an error if `noImplicitAny` is enabled

### 🙂 Expected behavior

Type of `A.value` to stay `null` regardless of `strictNullChecks`

**Comment by MartinJohns** [comment]
When you disable `strictNullChecks` you essentially disable the `null` and `undefined` types. They do not exist, they get filtered by the type system.

This is working as intended.
