### ISSUE TITLE
4.3: Type checking regression with intersection types

### ISSUE THREAD

**Issue by emmettnicholas** [microsoft/TypeScript#44310]
# Bug Report

### 🔎 Search Terms

intersection, inheritance, interface, discriminant, union

### 🕗 Version & Regression Information

- This changed between versions 4.2 and 4.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/C4TwDgpgBAShDOBXANsAPAFQDRQKJQgA9gIA7AE3igG8BfKAXjwCdmB7ZgPkYCgp+oAHxp8BY-swgBDcm1LIQUAG5TkiCAC4oGANyjxAyTLkKCrAPxbSEJRGZ6DtfUJEGxR2fMV3mW3A7cJaU9TFTUISyhrW3tnflo9HlBIKABlSABjAEtVXFYORhZ2ZigAMhoAMzY2LXhgZizSAHMnHgrEUgzgLLkoEjqACkkkVC04EfQ6huacdIhs3PyuAEpa+sam1wEsiqghhBRgADofZa2DYAALdgB3KGHDk9YA+OdJYERmUnuD1COw9R6WhAA)

### 💻 Code

```ts
type Result<T, E extends {} = Error> =
    | {
          readonly value: T;
          readonly err?: never;
      }
    | {
          readonly err: E;
          readonly value?: never;
      };

type SpecialError = Error & {foo: string}

function test(result: Result<string, SpecialError>): string {
    if (result.err) {
        throw result.err;
    }
    return result.value;
}
```

### 🙁 Actual behavior

Error on the return statement:

```
Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

### 🙂 Expected behavior

No error. I realize `Result` isn't a proper discriminated union, but is the difference between 4.2 and 4.3 expected?

### Additional notes

These techniques "fix" the problem, but I don't understand why:
- remove ` & {foo: string}` from the `SpecialError` type
- replace `if (result.err)` with `if (result.value === undefined)`
- define `SpecialError` with an `interface`:

```ts
interface SpecialError extends Error {
    foo: string;
}
```

**Comment by IceCreamYou** [comment]
Here is a smaller repro:

- [Playground for TS 4.3](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/GYVwdgxgLglg9mABMOcAUcAOsEGcBciA3ogOYCmUAKgBYximFpoCUiAvAHyK5QBO9UmwA+PfoMQBfFoV4CGxAFCIViCHijEylWhMkdEAeQBGAK3LQAdAENcuGKTBoSFanQaEA5FHekAjJ5SADSIWDhguCwA3MqqfJQgfEhQAJ6Y5HDA2m4S7HmInqCQ4YEA-Nm6DKyIhK6VpDGSQA)
- [Playground for TS 4.2](https://www.typescriptlang.org/play?ts=4.2.3#code/GYVwdgxgLglg9mABMOcAUcAOsEGcBciA3ogOYCmUAKgBYximFpoCUiAvAHyK5QBO9UmwA+PfoMQBfFoV4CGxAFCIViCHijEylWhMkdEAeQBGAK3LQAdAENcuGKTBoSFanQaEA5FHekAjJ5SADSIWDhguCwA3MqqfJQgfEhQAJ6Y5HDA2m4S7HmInqCQ4YEA-Nm6DKyIhK6VpDGSQA)

Code:

```ts
function foo(options: { getThing: (() => string) | string }): string {
    const { getThing } = Object.assign({ getThing: 'thing1' }, options);
    return typeof getThing === 'function' ? getThing() : getThing;
}
```

In TypeScript 4.2.3 and below, the type of `getThing` is `string | (() => string)`. In TypeScript 4.3.0 and above, it's `string & (string | (() => string))`. The intersection is no longer applied over the union to become `(string & string) | (string & (() => string))`, so the code above errors in 4.3+ with `This expression is not callable. Type 'never' has no call signatures.`

**Comment by RyanCavanaugh** [comment]
This seems like an unintentional break from 4.2 -> 4.3:
```ts
// Somehow this being an intersection matters.
type FooAndBaz = { foo: unknown } & { baz: unknown };

type Disjoint =
 | { readonly value: string; readonly err?: never; }
 | { readonly value?: never; readonly err: FooAndBaz; };

function test(result: Disjoint): string {
    if (result.err) {
        throw result.err;
    }
    return result.value;
}
```

**Comment by arinwt** [comment]
Also encountering this bug when trying to bump to 4.3.

Reduced version with trivial intersection:
```ts
type TrivialIntersection = { a: 1 } & { a: 1 };

function want0(x: 0) {}

function test(a: 0 | TrivialIntersection) {
    if (a === 0) {
        want0(a); // Fails, but expect to work
    }
}
```
