### ISSUE TITLE
Wrong type after await

### ISSUE THREAD

**Issue by mdohot** [microsoft/TypeScript#44314]
# Bug Report

### 🔎 Search Terms

await type wrong after

### 🕗 Version & Regression Information

from 3.3.3333 to nightly (v4.4.0-dev20210527)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.0-dev.20210527#code/MYGwhgzhAECyCeBhcVoG8CwAoavoAcAnASwDcwAXAU2gFt4AFQge3wC5oA7AV1oCMqhaAB8u3ECGgBeMRIDc2bHgLc+IYsGiR4nTSGZgAJgApOVAO4A1MCG5UOPfoICU6JcrwUAFsQgA6eiZWaS4La1sqBSx3D2hgZk4IZhAqP30Ac2MAIgARZmJOdK0IHU1zZkIAa2gAMwqsgBpob18AxhZ8ZzloGI8wczBiCmaff0NmAGVmWioAQRLdAHUKyuMu3uUNvAB6begASU5qCV8qRJoEkdbAjugIL2ZzGAp4fBosxwFCLOg+bmH7sxxIY7g9zM1Xu9PoIRLIQFk-FtcLtoDluCRCiMaNpdNBylUrv4bsFfNBjBU4kCQCCBK4IFRhhRmGSCoS4pAqK4eBJEThYpTEslUhlsvsAOS0aCEKhGeB4oZeaDjApFHFlFa1epNFpE9qsdZ83AAX0UhpUag0cRSYEIaw4pHyIMwZuUOraQXwIW5ICiyhN0TNRDIlGxC004ymM3mpWWVTWbhdeGlFHRnFC4KCtFOAB4HcRDAA+YzSmBSAsJ-keekUAAqxBmQIoxaoECaAGYAAxdg2Vo09vD+-3YeKJRleixwJAoCBrKIUNIGEwARgN89AMttXSAA

### 💻 Code

```ts
class MyClass {
    private myProp: number | null = null;

    public async load(newValue: number) {
        this.myProp = newValue;

        console.log("Doing async work for", this.myProp); 
        await this.doSomeAsyncWork();
        
        // Intellisense on this.myProp shows type "number" but should show type "number | null".
        // During the async work this.myProp is (or could be) set to (in this case) null.
        console.log("I'm ready with doing async work for", this.myProp);
    }

    public clear(): void {
        this.myProp = null;
    }

    private async doSomeAsyncWork() {
        return new Promise<void>(res => {
            setTimeout(res, 3000);
        });
    }
}

const t = new MyClass();
t.load(1);
t.clear();
```

### 🙁 Actual behavior

Intellisense (hovering over) on this.myProp (last line of the load-method) shows type "number".

### 🙂 Expected behavior

Intellisense on this.myProp (last line of the load-method) should show in this case type "number | null".
Reason: During the async work this.myProp is (or could be) set to (in this case) null. This could result in runtime errors.

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/9998
