### ISSUE TITLE
`default class` without `export` is successfully parsed after a decorator

### ISSUE THREAD

**Issue by thorn0** [microsoft/TypeScript#44319]
# Bug Report

### 🔎 Search Terms

default class decorator export

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX1DBxig2IAojUBnDGZTYgLnilQE8BKFt9gbgBQAgAKFipYgNCIoyCBniQo1avADeAXwFA)

### 💻 Code

```ts
declare function decorator(constructor: any): any;

@decorator
default class {}
```

### 🙁 Actual behavior

no error

### 🙂 Expected behavior

syntax error

**Comment by DanielRosenwasser** [comment]
We should continue to gracefully parse this (and `default function`) and say that an `export` keyword was expected.
