### ISSUE TITLE
Typescript should be ignore import only types when emit dist file

### ISSUE THREAD

**Issue by Aqours** [microsoft/TypeScript#44317]
# Bug Report

### 🔎 Search Terms

import only types emit include type file

### 🕗 Version & Regression Information

- This changed between versions ___4.0___ and ___4.3____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ___type______
- I was unable to test this on prior versions because ___Typescript is too older____

### ⏯ Playground Link

n/a

### 💻 Code

```ts
// module.ts
export interface IModule { }
export class Module {  }

// app.ts
import { IModule } from './module';
class App {
    module: IModule;
}
```

Run `tsc` to emit Javascript files.

### 🙁 Actual behavior

```js
// app.js
import './module';
var App = /** @class */ (function () {
    function App() {
    }
    return App;
}());
//# sourceMappingURL=index.js.map
```

The emitted `app.js` file should not include `import './module';` becase I just import type.

### 🙂 Expected behavior

```js
// app.js
var App = /** @class */ (function () {
    function App() {
    }
    return App;
}());
//# sourceMappingURL=index.js.map
```

### More

`import type { IModule } from './module';` could solve this issue, but it's fussy.

**Comment by whzx5byb** [comment]
Try to use the `importsNotUsedAsValues` compiler options.
https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues

**Comment by MartinJohns** [comment]
Your expected behavior is exactly what I get with TypeScript 4.3 and the default init project settings.

**Comment by Aqours** [comment]
aha, my tsconfig.json set `importsNotUsedAsValues: "preserve"`. It works if I remove it. Thanks
