### ISSUE TITLE
Compile Private to #

### ISSUE THREAD

**Issue by Graham-Beer** [microsoft/TypeScript#44316]
# Suggestion
Would be nice if the TypeScript compiler could change the keyword Private to # for JavaScript. I think this feature would allow for cleaner looking code in TypeScript.

# Summary
This is a small change to the compiler when compiled down to JavaScript.

**Comment by MartinJohns** [comment]
This was discussed over and over already, with the clear stance to remain with the existing solution. It's your choice to either use `private` or `#`, each with its own functionality.

> This is a small change to the compiler when compiled down to JavaScript.

And it would be a heavy breaking change.

**Comment by whzx5byb** [comment]
> Is it going to be supported in the form of a transformer , turning private bar into #bar?
> > definitely "no" because that would require type-directed emit.

See https://github.com/microsoft/TypeScript/issues/31670

**Comment by Graham-Beer** [comment]
Noted update, will close issue.
