### ISSUE TITLE
`noUncheckedIndexedAccess` error in 4.3 that wasn't in 4.2: accessing an object based on `keyof` itself.

### ISSUE THREAD

**Issue by ranneyd** [microsoft/TypeScript#44332]
# Bug Report

### 🔎 Search Terms

4.3
4.2
noUncheckedIndexedAccess
keyof
undefined is not assignable

### 🕗 Version & Regression Information

I have a type `P` that has a string index signature. I have `noUnchekcedIndexedAccess` on. When I have `obj` of type `P` and `key` of type `keyof P`, I'd expect `obj[key]` to have no issues. This was not true in TS 4.1, but was fixed in 4.2 with [this](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#relaxed-optional-index-rules). However, it's now erroring again in 4.3.

Note: I'm using Ramda. Ramda's `keys` function works the same as `Object.keys` but properly returns type `(keyof T)[]`. Because of the type coercion, the playground links below don't properly demonstrate that this didn't work in 4.1 (and is a little more of a contrived example).

### ⏯ Playground Link

4.3:
https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.3.0-beta#code/JYOwLgpgTgZghgYwgAgApynAtgZ2QbwChlkBtAawgE8AuZHMKUAcwF06GmRnkAfZEAFcsAI2h9kIgPZSANhDggA3IQC+hQgikgGyLHEoBFQdCoBlRi2QBeZAB5UyCAA9IIACZ50mXDbQZsHAA+AApiZAAHANw6VEIASg5LbhsggnCSeTBkKUEob0CkrmZSVj9SlRISGCkoZBCsyOicmGQAeREAKwgEMAA6SiocEKifHHj49KqqxsG-CBAtdwgAVQAlAEkAYSksCO0FsBHo+Mrp5EaANzhZecWpZfXt3f2QQ+Ox0lHsZDg8QakrVQrFOGSquXy0RwfQighwAAsQgADAAk+EGqmsaOuslUSNB03U0ygEDAeRAyCRAH40RCCrg+p0pKAQgAiABkrPieJUqiAA

4.2:
https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.2.3#code/JYOwLgpgTgZghgYwgAgApynAtgZ2QbwChlkBtAawgE8AuZHMKUAcwF06GmRnkAfZEAFcsAI2h9kIgPZSANhDggA3IQC+hQgikgGyLHEoBFQdCoBlRi2QBeZAB5UyCAA9IIACZ50mXDbQZsHAA+AApiZAAHANw6VEIASg5LbhsggnCSeTBkKUEob0CkrmZSVj9SlRISGCkoZBCsyOicmGQAeREAKwgEMAA6SiocEKifHHj49KqqxsG-CBAtdwgAVQAlAEkAYSksCO0FsBHo+Mrp5EaANzhZecWpZfXt3f2QQ+Ox0lHsZDg8QakrVQrFOGSquXy0RwfQighwAAsQgADAAk+EGqmsaOuslUSNB03U0ygEDAeRAyCRAH40RCCrg+p0pKAQgAiABkrPieJUqiAA

### 💻 Code

```ts
export const apiFetch = async <T, P extends Params = Params>(
  route: string,
  options?: Partial<Options<P>>
): Promise<T> => {
  let url = `${API_URL}${route}`;
  if (options?.params) {
    let params: string[] = [];
    for (let param of R.keys(options.params)) { // <-- Note: this function makes param have type `keyof P`
      let key = encodeURIComponent(param);
      let val = encodeURIComponent(options.params[param]); // <-- Error: Type 'undefined' is not assignable to type 'string | number | boolean'
      params.push(`${key}=${val}`);
    }
...
```

### 🙁 Actual behavior

`params[param]`, where `params` is type `P` (which has a string index signature) and `param` has type `keyof P` errors with "Type 'undefined' is not assignable to type 'string | number | boolean'". In TS 4.3

### 🙂 Expected behavior

No error, as it was in TS 4.2

**Comment by RyanCavanaugh** [comment]
>  When I have `obj` of type `P` and key of type `keyof P`, I'd expect `obj[key]` to have no issues.

I don't agree with this reasoning at all. A `number` is `keyof Array<T>` but the entire point of the flag is to include undefined when indexing arrays by numbers!

**Comment by ranneyd** [comment]
@RyanCavanaugh that's a great point. I guess the "issue" is that `keyof P` is `string`, not `the actual keys of P, whatever they are`. It's made more annoying here because `P` isn't really meant to be a dynamically-indexed type so much as a description of a type of that shape with explicitly-defined keys, so `keyof P` would be more of a union type. Obviously this function doesn't know that, and I'd have to think about how I'd implement that behavior.

Isn't it strange that this worked in 4.2? What changed in 4.3 that made this error?

**Comment by RyanCavanaugh** [comment]
It is strange indeed. I'm not sure what the underlying change was; we didn't have intentional edits there AFAIK.

**Comment by ranneyd** [comment]
Ok I'll close the issue. Do you have any suggestions of how to approach something like this? I could certainly use type assertions or null checks or defaults and stuff, but if I wanted to say "this is a function with a generic type that should have values that are booleans and without index signatures", is there a way to do that?

**Comment by RyanCavanaugh** [comment]
I don't think so; you'd need something like a negated type.
