### ISSUE TITLE
SVGGeometryElement  is missing methods:  isPointInStroke, isPointInFill

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#44336]
see:

https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/isPointInFill
https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/isPointInStroke

Typescript: 4.3.2

**Comment by jogibear9988** [comment]
mhmmm...
in the IDL it seems correct:

https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/3a6fa3b6707dd65eb28c2b3b66e866a654ddcfbd/inputfiles/idl/SVG%20-%20Basic%20Data%20Types%20and%20Interfaces.widl#L36

**Comment by jogibear9988** [comment]
I found the issue:

SVGpathElement has a wrong inhertiance chain

This is from lib.dom.d.ts
![image](https://user-images.githubusercontent.com/364896/120659722-eb766a00-c486-11eb-9c4b-d60f69d83108.png)

This is the expected chain:
![image](https://user-images.githubusercontent.com/364896/120659927-1f518f80-c487-11eb-95ee-451ab3486828.png)

**Comment by jogibear9988** [comment]
so SVGPathElement should extend SVGGeometryElement and not SVGGraphicsElement

**Comment by jogibear9988** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
