### ISSUE TITLE
Variable overwrite issue after upgrade to 4.3.2

### ISSUE THREAD

**Issue by DarthVan** [microsoft/TypeScript#44339]
Hi! My code was workd fine before 4.3.2 update. When I started looking for the problem, I found that after update in my compiled JS file appeared a class properties:
![Скриншот 2021-05-30 18 20 30](https://user-images.githubusercontent.com/5062893/120109982-6cc2b980-c174-11eb-95f7-4b2f7f2da5f8.png)

but in my case that variables calls a bug in runtime. Here i made a simple example for reproduce:

1. TS code:
![Скриншот 2021-05-30 17 38 19](https://user-images.githubusercontent.com/5062893/120110060-d80c8b80-c174-11eb-854e-0570ae188742.png)

2. tsconfig:
![Скриншот 2021-05-30 18 26 59](https://user-images.githubusercontent.com/5062893/120110243-5d903b80-c175-11eb-897a-731e6cc0479b.png)

3. output JS code:
![Скриншот 2021-05-30 17 14 07](https://user-images.githubusercontent.com/5062893/120110299-9203f780-c175-11eb-8c79-2b2fac781de7.png)

4. FireFox / Chrome console log (it seems, one of variables was beed overwritten by constructor):
![Скриншот 2021-05-30 17 01 34](https://user-images.githubusercontent.com/5062893/120110322-aba53f00-c175-11eb-8d9c-ca84ec362789.png)

Firefox 88.0.1 (for Win 10 x64)
VS Code - 1.56.2
typescript - 4.3.2
rollup - 2.50.3

Thanks!

P.S.
Before i used typescript 4.2.4 with same tsconfig and browsers, and generated JS didn't contained public class declarations.
Here i just tried to comment one variable and check the result:
![Скриншот 2021-05-30 17 21 32](https://user-images.githubusercontent.com/5062893/120110720-566a2d00-c177-11eb-8bc9-660edd014fb3.png)
![Скриншот 2021-05-30 17 20 54](https://user-images.githubusercontent.com/5062893/120110726-5b2ee100-c177-11eb-8d68-bddbcd066046.png)

**Comment by DarthVan** [comment]
UPD:

solved my problem by adding this argument to tsconfig.json:
"useDefineForClassFields": false

also found an explanation, when are public instance fields executed, its look like a bit stupid)
https://2ality.com/2019/07/public-class-fields.html

**Comment by RyanCavanaugh** [comment]
We are not able to process bug reports with screenshots of text. Please use text for text.
