### ISSUE TITLE
Provide autocomplete features for plugin configuration options in tsconfig.json

### ISSUE THREAD

**Issue by applemonkey496** [microsoft/TypeScript#44340]
# Suggestion

Currently, TypeScript provides autocomplete features for `tsconfig.json`\*. However, this autocomplete does not work for Typescript plugin options. This discussion started at https://github.com/mrmckeb/typescript-plugin-css-modules/issues/127#issuecomment-850966397.

## 🔍 Search Terms

* `tsconfig autocomplete`
* `tsconfig plugins`
* `typescript plugin autocomplete`
* `tsconfig autocomplete plugins`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

TypeScript plugins that provide typings for their configuration options get autocomplete features for their configuration options in `compilerOptions.plugins` in tsconfig.json.

## 📃 Motivating Example / 💻 Use Cases

The reason that this came up in the first place was some casing issues for plugin options. @mrmckeb pointed out that although typings are provided for the plugin `typescript-plugin-css-modules`, TypeScript pays no attention to them in tsconfig.json. 

This is kind of annoying because I have to check the documentation every time I adjust my configuration options and often verify the options' spellings multiple times (for example, it took me about an hour to find out that the plugin was behaving wrong because I had misspelled the option `postCssOptions` as `postcssOptions`).

I don't think that this would be too difficult to implement either, because it would just be an extension of the existing tsconfig autocomplete feature. 

## ⚠ One Important Point
\* I know that vscode provides this autocomplete feature in tsconfig.json, but here I'm assuming that the autocomplete comes from TypeScript itself, not vscode. I checked out both codebases to see if I could find something, but I wasn't really sure where to look. If it is the case, then I suppose this issue should be closed an its request moved over to the vscode repo.

**Comment by MartinJohns** [comment]
I believe the auto completion comes from VSCode based on the JSON schema file: https://json.schemastore.org/tsconfig.json

**Comment by mrmckeb** [comment]
I think this would mean that there would need to be a way for the JSON schema to be extended by a plugin's configuration when that plugin is used. As each plugin has a `name`, that should help us to understand where types should come from for that plugin.

An alternative solution to this problem would be to allow plugins to more clearly surface errors to users. TS server logs are quite verbose, and users may not even know where to look for plugin errors.

**Comment by applemonkey496** [comment]
The [`typescript-json-schema`](https://www.npmjs.com/package/typescript-json-schema) library on NPM might be useful here.

**Comment by RyanCavanaugh** [comment]
TS doesn't provide the intellisense there. I don't think there's a good way to implement this that isn't a massive scope creep.

**Comment by applemonkey496** [comment]
Maybe something can be done on the VSCode end here. Closing on this end.
