### ISSUE TITLE
Subclass can't explain this type

### ISSUE THREAD

**Issue by shalldie** [microsoft/TypeScript#44349]
# Bug Report

### 🔎 Search Terms
subclass this type.

### 🕗 Version & Regression Information

typescript: 4.3.2

### 💻 Code

![image](https://user-images.githubusercontent.com/9987486/120182094-85000a80-c240-11eb-848a-ef70b4c2ebab.png)

### 🙂 Expected behavior

I think the last code should also works well, and vscode tell me what i can type in.
But some err happen if i type it.

![image](https://user-images.githubusercontent.com/9987486/120182701-4e76bf80-c241-11eb-9f69-e36354a98059.png)

**Comment by jcalz** [comment]
Images of code should be replaced with plain text and a Playground link.  Assuming you want others to pay attention to this report...

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/41495

**Comment by RyanCavanaugh** [comment]
Images are not accessible; please repost with text.
