### ISSUE TITLE
Early binding to sys can cause undefined FormatDiagnosticHost

### ISSUE THREAD

**Issue by kitsonk** [microsoft/TypeScript#44343]
# Bug Report

### 🔎 Search Terms

FormatDiagnosticHost, watch.ts

### 🕗 Version & Regression Information

- Likely existed for a long long time.

### ⏯ Playground Link

N/A

### 💻 Code

The compiler binds early to `sys` when creating the `FormatDiagnosticHost`:

https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/compiler/watch.ts#L3-L7

But then checks here if it equals if the passed system matches the `sys`:

https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/compiler/watch.ts#L13

### 🙁 Actual behavior

n situations where a custom `ts.sys` host is provided, post bootstrapping of the `ts` namespace, this results in the `FormatDiagnosticHost` being `undefined` and generating type errors like this:

```
TypeError: Cannot read property 'getNewLine' of undefined
    at Object.formatDiagnostic (typescript/lib/tsc.js:89556:159)
```

### 🙂 Expected behavior

Obviously the ternary statement was inserted to deal with strict null checks, but in theory, the creation of the `sysFormatDiagnosticsHost` should be late binding or the ternary expression in `createDiagnosticReporter` should check if `sysFormatDiagnosticsHost` is defined, instead of if `system === sys`.

Actually now that I say that out loud, it should be the latter.

**Comment by DanielRosenwasser** [comment]
Thanks @kitsonk!
