### ISSUE TITLE
Key Remapping not working in Typescript playground for TS version 4.1.5 and 4.2

### ISSUE THREAD

**Issue by jtarre** [microsoft/TypeScript#44355]
# Bug Report

Key Re-mapping is throwing an error in Typescript playground and VSCode

I used the code sample from the Typescript docs: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types

Typescript Playground v4.1.5:
![image](https://user-images.githubusercontent.com/1143894/120226148-9fbc8a00-c214-11eb-9284-a706433110ca.png)

Typescript Playground v4.2.3:
![image](https://user-images.githubusercontent.com/1143894/120226172-b19e2d00-c214-11eb-902e-4a8f62089286.png)

VSCode:
![image](https://user-images.githubusercontent.com/1143894/120226212-c4186680-c214-11eb-9fcd-bf269a7c7971.png)

### 🔎 Search Terms

key-remapping

### 🕗 Version & Regression Information

This behavior appeared when I updated a repo with TS from v3.9 to v4.2. This behavior existed in the playground when I tried the code sample for key re-mapping in the typescript docs. 

- I was unable to test this on prior versions because this feature is new as of v4.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&ssl=5&ssc=2&pln=1&pc=1#code/C4TwDgpgBAsghmSATAKuCB1AlsAFgOQgHcBpCEAZwB4UA+KAXigG8AoKDqAbRKiwDsoAa3IB7AGZQUUOBSiFS5NJAC6ALik8V7TgHpdnQ0YB6ps+bM6O+o7am4scx1DzR+xKBRD9gcAB4AhKwAvkA)

### 💻 Code

```ts
type MappedTypeWithNewKeys<T> = {
    [K in keyof T as NewKeyType]: T[K]
    //            ^^^^^^^^^^^^^
    //            This is the new syntax!
}
```

### 🙁 Actual behavior

Error about unrecognized `NewKeyType`

### 🙂 Expected behavior

`NewKeyType` is recognized as a new type.

**Comment by fatcerberus** [comment]
That example is just there to show you what the syntax looks like. You must put a known type there, `NewKeyType` doesn't create a new type, it tells TS how to transform the keys.
