### ISSUE TITLE
`readonly` fields should be `writable: false`

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#44357]
# Suggestion

When `useDefineForClassFields` is enabled `readonly` and `static readonly` fields should be emitted with `writable: false`.

## 🔍 Search Terms

- readonly
- fields
- define

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Emit `writable: false` when a field is `readonly` and `useDefineForClassFields` is enabled

## 📃 Motivating Example

`readonly` fields now are runtime readonly too.

**Comment by jcalz** [comment]
You checked  “This could be implemented without emitting different JS based on the types of the expressions” 

but isn’t this specifically asking for different JS based on information from the static type system?

**Comment by Nokel81** [comment]
Maybe I misunderstood what that meant, but to me a field declaration is not an expression. It is a different kind of parser entry.

**Comment by jcalz** [comment]
Well, I expect this will be declined as it does not allow type erasure.

**Comment by Nokel81** [comment]
How is it not allowing type erasure? There is already a well defined JS way of doing just this. I was slightly surprised that turning on `useDefineForClassFields` didn't do this anyway.

**Comment by MartinJohns** [comment]
Also be aware that readonly properties are implicitly compatible with the mutable counterpart. Your class can implement interfaces where the property is not marked `readonly`.

**Comment by justinfagnani** [comment]
Hopefully this is possible at runtime with the new TC39 decorators proposal, and there would be a way for TypeScript to recognize the property descriptor modifications made by the decorator so the readonly keyword isn't necessary.

**Comment by Nokel81** [comment]
> I don't know well enough what writable actually does to determine whether this has an impact.

It is similar to how `Object.freeze` works. Namely, it is shallow and in normal mode the assignments are ignored. In strict mode a `TypeError` is thrown.

**Comment by Nokel81** [comment]
> Hopefully this is possible at runtime with the new TC39 decorators proposal.

I don't quite understand this, yes the configuration is done at run time but it really should be done in a constructor. The annoying thing is is that without this proposal, the equivalent code is rather obtuse:

---

With proposal:
```ts
class Foo {
  readonly foo = "1";
}

const f = new Foo();

(f as any).foo = "2"; // error
```

Current situation:
```ts
interface Foo {
  readonly foo: string;
}

class Foo {
  constructor() {
    Object.defineProperty(this, "foo", {
      enumerable: true,
      configurable: true,
      writable: false,
      value: "1"
    });
  }
}

const f = new Foo();

(f as any).foo = "2"; // error
```

The current situation is necessary so that a second `Object.defineProperty` isn't emitted in the constructor.

**Comment by MartinJohns** [comment]
> (f as any).foo = "2"; // error

But why should that be an error? `readonly` only applies to the specific TypeScript type. It does not mean immutable, only "can't write via this type". Like I mentioned, the mutable counter-part is implicitly compatible:


```typescript
class Foo { readonly foo = "1"; }
class MFoo { foo = "1"; }

function changeFoo(x: MFoo) { x.foo = "abc"; }

const foo = new Foo();
changeFoo(foo);
```

**Comment by Nokel81** [comment]
> But why should that be an error? `readonly` only applies to the specific TypeScript type. It does not mean immutable, only "can't write via this type". Like I mentioned, the mutable counter-part is implicitly compatible:

Well that is what I am proposing. Namely a change.

And furthermore, I know that you can change the `readonly`-ness of child classes too. But that is compatible with my proposal because I am not talking about changing the `configurable` flag.

**Comment by jcalz** [comment]
> How is it not allowing type erasure?

Because currently the `readonly` modifier is not part of ECMAScript, it's part of TypeScript's static type system.  It sounds like you want the type system to affect the emitted JavaScript, which is counter to type erasure.

> There is already a well defined JS way of doing just this. I was slightly surprised that turning on `useDefineForClassFields` didn't do this anyway.

If you're suggesting that the `readonly` modifier should be considered part of class fields and not part of the static type system, then sure, this isn't a type erasure issue.  But then you're asking for a runtime feature involving "non-ECMAScript syntax with JavaScript output".   TypeScript won't introduce such new runtime features; such requests would belong in  https://github.com/tc39/proposal-class-fields/, such as the (closed) https://github.com/tc39/proposal-class-fields/issues/83. 

Or am I missing what we are trying to achieve here?

**Comment by RyanCavanaugh** [comment]
The only non-type-directed-emit case I can see here would be class fields, and `readonly` class fields are intentionally writable in the constructor, so this is a no-go.

**Comment by c-harding** [comment]
It would be possible to emit `Object.defineProperties` at the end of the constructor, as subclasses aren’t allowed to overwrite readonly properties in the constructor.

However, if subclass overrides a field, the subclass would have to make it writable again:

<details>
<summary>Example with subclass</summary>

```ts
class Super {
    readonly field = 1;
    readonly otherField = 0;

    constructor() {
        this.field = 2;
    }
}

class Sub extends Super {
    readonly field = 3;

    constructor() {
        const value = 4;
        super();
        this.field = value;
    }
}
```
```js
"use strict";
class Super {
    constructor() {
        // field init
        this.field = 1;
        this.otherField = 0;

        // constructor
        this.field = 2;

        // after constructor: make all readonly fields non-writable
        Object.defineProperties(this, {
          field: { writable: false },
          otherField: { writable: false },
        });
    }
}
class Sub extends Super {
    constructor() {
        // part of constructor up to super call
        const value = 4;
        super();

        // after super call: make all fields that override readonly fields writable
        Object.defineProperty(this, { field: { writable: true } });

        // field init
        this.field = 3;

        // part of constructor after super call
        this.field = value;

        // after constructor: make all readonly fields non-writable
        Object.defineProperties(this, { field: { writable: false } });
    }
}
```
</details>

It would be great if this could be a compiler option @RyanCavanaugh

**Comment by justinfagnani** [comment]
@c-harding that would make this violate this guideline:

> This wouldn't change the runtime behavior of existing JavaScript code

I think a decorator would be the TC39-approved way of accomplishing this.

**Comment by c-harding** [comment]
@justinfagnani How would such a decorator look, such that it is possible to set the property in the constructor but no later?

**Comment by c-harding** [comment]
@justinfagnani I had a go [in this gist here](https://gist.github.com/c-harding/cb6605fceab49381202c716df8fe5983), but it has slightly different semantics: I had to disallow overriding readonly properties, as it wasn’t possible to allow this using a decorator. Additionally, it seems like I would have to annotate both the field and the class (in addition to the `readonly` type). It feels like far more effort than if the typescript compiler could do this automatically
