### ISSUE TITLE
add a gitignore command

### ISSUE THREAD

**Issue by lerichardson** [microsoft/TypeScript#44356]
# Suggestion

## 🔍 Search Terms

gitignore typescript command

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions

* [x] This isn't a runtime feature (e.g., library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
I'd like to see a `gitignore` option that will auto-create a gitignore file tailored to Typescript. This is like `.NET`'s `dotnet new gitignore`. This could include standard node.js options, like `/tmp` or `/dist`, but also maybe even `.js` files entirely or at least source map files.
## 📃 Motivating Example
"TypeScript has, in many ways, made the lives of JavaScript developers easier. By adding a simple, easy, gitigore creation command, this should make it even easier to integrate your project into a git-based version management software."
## 💻 Use Cases
I'm creating a new project and want to push it to GitHub, but I don't want to push the built js files, only the typescript files. While I'm in the process of doing that, I may as well add more files to the .gitignore file. Simply adding a `tsc gitignore` or `tsc gitignore --ignore-js`, for example, would be so much easier than going online to copy/paste a gitignore, then add a `*.js` to the end of the file.

**Comment by MartinJohns** [comment]
Why not just use [gitignore](https://www.npmjs.com/package/gitignore)?

**Comment by RyanCavanaugh** [comment]
Someone* should send a PR to https://github.com/github/gitignore/pulls

`*` Other than a TypeScript engineer who should be spending their time fixing bugs that only we or a small number of other people have the expertise to fix
