### ISSUE TITLE
Computed generic argument type is not narrowed

### ISSUE THREAD

**Issue by qwelias** [microsoft/TypeScript#44358]
# Bug Report

### 🔎 Search Terms

computed generic function argument guard narrow

### 🕗 Version & Regression Information

v4.3.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyhA2EDGwA8AVKEAewIDsATAZygHIBDMqAH3ICMyA+KAXigG8AoKXqCgFxRiwAE4BLfAHMA3Dz70h+AK4BbehFFyAvgG10AXTlckAe3wjhCZMDZQMWXARLkqtBswAUoSEPQAaKEIKYEFYaxQMJgBKNhZuPihxADMob3BoViyPWNEIYGVRfCCQiigAKigAVjlEvIKiqABGHSA)

### 💻 Code

```ts
type Select<T extends 'a' | 'b'> = {
    a: string;
    b: number;
}[T];

const select = <T extends 'a' | 'b'>(type: T, data: Select<T>) => {
    if (type === 'b') return data * 5; // The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.(2362)
    return 1;
}
```

### 🙁 Actual behavior

Cannot `data * 5` because `The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.(2362)`

### 🙂 Expected behavior

`data * 5` is valid because it's within the code branch where `type === 'b'` and type of `data` in that case is `number`

**Comment by qwelias** [comment]
There's a workaround to use tuple type for arguments
```ts
type SelectArgs =
    | ['a', string]
    | ['b', number]

const select = (...args: SelectArgs) => {
    if (args[0] === 'b') return args[1] * 5;
    return 1;
}
```
But in that case one cannot destructure them, because then it would break for some reason, so have to keep using indexes :(

**Comment by MartinJohns** [comment]
Because such an operation would be unsound:

    select<'a' | 'b'>('b', 'hello')

You would need #27808 first.

**Comment by qwelias** [comment]
So is the only way right now to do something like this is to use tuples like in https://github.com/microsoft/TypeScript/issues/44358#issuecomment-851696342 (or analogous object type) without the ability to destructure?
[ts pg](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyhA2EDGwCCAnA5gZygXgCgpioAfKAbQHIBDKgGim2HQEsA7TAXSJPOoBGDKOwCuAWwER0PAgHo5UAO4B7dAGtcS1sAAWK0cCgATCM3SiUo9BAJIV7ZkwTIjeKAAoAdD5pZsAFywLigYOACU+AB8UADevMSsAGaefjgUAAxc+HjuVEKRNsDW7FBp2BQAjNkAVFAArADcCVBFJVCVzQC+BPKKxipm7FRGqhpQySZmLJbFNsZ2Dk7YIW6ePl7lQXCIof6ReDHxJFD2jkYUoJCMxjTANNnu5c0nkx5X0Ll5Ba0Qc6W3e5QOpNFptdClToEHoEIA)

**Comment by MartinJohns** [comment]
Yes. Destructure would require #12184 / #44169.

**Comment by qwelias** [comment]
Thanks for links, looks like it depends on existing issues.
