### ISSUE TITLE
Returned inline functions property access privileges differ between methods and functions with contextual this

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#44365]
# Bug Report

Related #44128

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8CwAoAkABwE7wBcBTYYgE2gCMxdoBeaARgG4NMIiCAKASjS0zB4AOwgFoAM0T1oBABYBLCKwG5OAV1zDJ64aQUjeKNpkxT4AOmq4VpgL5sH6Jxgm79I6B27ylALjhEHmMsIVFxcxlfZTY1Ak1tNz0CA2EjflNzKxpbJzsgA)
      

### 💻 Code

```ts
class Foo {
	protected bar = 1;
	set(){
		const foo = this;
		return function() {
			foo.bar; // No Error
		}
	}
}

function set(this: Foo) {
	const foo = this;
	return function() {
		foo.bar; // Property 'bar' is protected and only accessible within class 'Foo' and its subclasses.(2445)
	}
}
```

### 🙁 Actual behavior

`foo.bar` is not accessible from returned inline function despite `this: Foo`

### 🙂 Expected behavior

`Foo.prototype.set` and `function set` to have the same property access privileges

**Comment by RyanCavanaugh** [comment]
Please don't log bugs asking us to make something "the same". Which one do you want changed, *and why* ? A difference is not a per se defect.
