### ISSUE TITLE
Object.keys unable to infer type of key

### ISSUE THREAD

**Issue by haoadoresorange** [microsoft/TypeScript#44376]
# Bug Report

I'm not sure why this isn't the case yet. I look around and there was discussions, but I couldn't find a definitive answer.

### 🔎 Search Terms

Object.keys

### 🕗 Version & Regression Information

- The furthest I can go back is 2.9

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5ICwAUPAHaYAuoAhqALygDepo7dAXKAIwA0bDgCNuAJlIBfUgHkhAKyQwqAOgDWSSJgAUtAJRA)

### 💻 Code

```ts
const a = {
    a: 1,
    b: 2
}
Object.keys(a)
```

### 🙁 Actual behavior

There's an old issue about this #12253
`Object.keys` just returns `string[]`, meanwhile `for..in` returns the correct type

### 🙂 Expected behavior

returns (Extract<keyof T, string>)[]

**Comment by MartinJohns** [comment]
This is intentional. There are many issues about this.

**Comment by haoadoresorange** [comment]
Why does `for..in` behave differently ?

**Comment by MartinJohns** [comment]
It doesn't.

![image](https://user-images.githubusercontent.com/5269069/120429610-f9889580-c375-11eb-8691-dc315a94ccde.png)

**Comment by haoadoresorange** [comment]
An example with generic to show the difference
https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5ICwAUDADYCGm2AYnHADwAqAfAN6mjexwB2mAC74ArjEFx8ACi485AB3wBLAG6VBKQpQT9y0RXHkAuUJxJyLPANoBrJNCV9QdyHABmoZgF0TIvjb44AHc+AG5ZSwBfABoI0ABKU0jSOPkRACNyJRhQdMppRLNLbjdJUCl4AUFne1BHUEEcJUwAOgN5Qri5ZPNigHl0gCskcRaXTClG5rb8Q3i4nsigA

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208

Generics are a different can of worms.

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/q/55012174/1704166
