### ISSUE TITLE
missing error for enum when used in an array property

### ISSUE THREAD

**Issue by barthony** [microsoft/TypeScript#44371]
# Bug Report

### 🔎 Search Terms
enum, conversion, array property, type mix

### 🕗 Version & Regression Information
seen in 4.1.5 and 4.4.0-dev.20210601

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/KYOwrgtgBAsgngUXNA3gWAFBW1ARANwEMAbARlwBpMc8jiAmXTAX00wEsQAXYAJwDNCAY2Cw4ASW59BIqOiw5CvXoTgAFXgHsADny5wAXFAAU8JJCgAfKMgBGfAJQBtALos2GAPSeowAB66QjwAJr7KmrwAzphCmiCRXFBKvKRGpojIVjaQ9rzOLlAAvFBOBCTkbhix8YnJ9GlmmdZ2jq5FJWVklFAADJXVCVCapO0oScqqGjp6hh10FVDMSZFikjwCwsAe3r4BwEHAofzsfjFxg8mkAGInh6PjKupaurz6Rk6NkKXzuC4FS4QVvA1tJNmcag96Dc-HdimNkpNnjN3p8IN9yr8KL1-stVlINiJwYNhtDYXIHojpq9Zh8Ml9OhUcYC8esZFsMJgdhB2JFIpwAOZhLS8ImJbm8gUIcK8ADytgAVvtEnCKU8qW85hisX1Frjgfi2UA)

### 💻 Code

```ts
enum MyEnum {
    "val1",
    "val2"
}

interface MyInterface {
    arrayProperty: (MyEnum | number)[]
}

// expected errors
const arr1: (MyEnum | number)[] = ["val1"]
const arr2: (MyEnum | number)[] = ["val1", 0]
const o1 = { arrayProperty: ["val1"] } as MyInterface

// expected fix
const arr1Fixed = { arrayProperty: [MyEnum["val1"]] } as MyInterface
const arr2Fixed = { arrayProperty: [MyEnum["val1"], 0] } as MyInterface
const o1Fixed = { arrayProperty: [MyEnum["val1"]] } as MyInterface

// missing error
const missingErrorObject = { arrayProperty: ["val1", 0] } as MyInterface
```

### 🙁 Actual behavior

When mixing types (including enum) for an array, no error is detected with string value if that array is part of an object and if it contains other values

### 🙂 Expected behavior

Wrong type should be  detected

**Comment by MartinJohns** [comment]
Just noting that you do get an error when you use a type annotation instead of a type assertion:

    const missingErrorObject: MyInterface = { arrayProperty: ["val1", 0] }

Type assertions are a way to tell the compiler to ignore type errors, to just trust your assesment. There are **some** checks, but they're limited (as you've noticed).

**Comment by RyanCavanaugh** [comment]
This is an expected-allowed type assertion. You can think of it as an assertion that `"val1"` isn't actually in the array (which would then be legal):
```ts
// OK
const noProblem: MyInterface = { arrayProperty: [0] }
```
