### ISSUE TITLE
.every() .find() .filter() methods fail with "This expression is not callable." error on union of array types

### ISSUE THREAD

**Issue by ialexryan** [microsoft/TypeScript#44373]
# Bug Report

### 🔎 Search Terms

- This expression is not callable
- none of those signatures are compatible with each other

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union types. I also reviewed previous related issues.

### ⏯ Playground Link

- .every() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdBAA3aABPC2BIOmQAXgA+Ugjfcm9mZCA)
- .filter() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJwAbaQtgSDpkAF4APlIw33JvZmQgA)
- .find() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJxAyC2BIOmQAXgA+UlDfcm9mZCA)
- .reduce() also doesn't work, but there is already an [issue](https://github.com/microsoft/TypeScript/issues/44063) for that one. (Perhaps we should merge it into this?)

### 💻 Code

```ts
interface Fizz {
    id: number;
    fizz: string;
}

interface Buzz {
    id: number;
    buzz: string;
}

([] as Fizz[] | Buzz[]).filter(item => item.id < 5); 
```

### 🙁 Actual behavior

Compilation fails with the following error:
```
This expression is not callable.
  Each member of the union type '{ <S extends Fizz>(predicate: (value: Fizz, index: number, array: Fizz[]) => value is S, thisArg?: any): S[]; (predicate: (value: Fizz, index: number, array: Fizz[]) => unknown, thisArg?: any): Fizz[]; } | { ...; }' has signatures, but none of those signatures are compatible with each other.
```

### 🙂 Expected behavior

Compilation succeeds, as it does for [map and several other array functions](https://github.com/microsoft/TypeScript/issues/36390#issuecomment-852533093).

### 🔖 Useful links
- [Original issue](https://github.com/microsoft/TypeScript/issues/36390)
- [PR that closed original issue](https://github.com/microsoft/TypeScript/pull/31023)

**Comment by DanielRosenwasser** [comment]
Duplicate of #36390

https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+array+%22This+expression+is+not+callable%22

**Comment by ialexryan** [comment]
Hi @DanielRosenwasser, please review my [comment](https://github.com/microsoft/TypeScript/issues/36390#issuecomment-852533093) on that issue (also linked in the writeup above). This issue is related to #36390, but it is not a duplicate. This issue tracks the handful of array functions which still don't work with union types post-#31023.

**Comment by RyanCavanaugh** [comment]
@weswigham what's the current state of what we might be able to do here?

**Comment by weswigham** [comment]
Well, we'd need to come up with sensible rules for merging overload lists. Conceptually, we could (attempt to) make a list of 4 overloads by combining each of the input signatures, except there's no inherent ordering to those 4 signatures, unlike a normal overload set, so it's unclear how we'd choose which signature to resolve against, ultimately.

**Comment by ITenthusiasm** [comment]
@weswigham Is there anything in particular that makes methods like `filter` difficult to work with compared to `map`? I haven't looked at the type definition in TS. But from a JS standpoint, the two signatures are the same; so it's a bit surprising that the methods involving predicates are more complex.

**Comment by jcalz** [comment]
Maybe something could be done specifically for arrays instead of worrying about merging arbitrary signatures?  Like, widen `A[] | B[]` to `readonly (A | B)[]` for these failing method calls?  🤷‍♂️

**Comment by dderjoel** [comment]
Can we add `concat` to that list above, too?
I have a typescript-playground showing this [here](https://www.typescriptlang.org/play?target=8&jsx=0#code/MYewdgzgLgBAtjAvDA2gXRgQwjAggJ30wE8AeMAVzgCMBTfGAHxmnwEswBzAPgG4BYAFBwAdPloATCsFoAKWWygBKJNxiKlA4SLiYADvI2r1yraNBhgmKLLiahQi9HgAmJKgzY8hEuSp18NWYCIjJWDh4zFx19BShEbg1eGAB6FJgAdwALYhgJEFocKCzrTJB8AGsYAH4hOGjxKRlDZWMkuuiLKxt6+0EhNJZMOFpMxSyYKAo9ABtCx3BnOABmdxQARgAaGHXPHBRKGnptw4CMZhRwrjQzZZiDOJUEkz6VsUlpOUe20zq7rustlWXkwYGIfSAA).

**Comment by vassudanagunta** [comment]
> * .reduce() also doesn't work, but there is already an [issue](https://github.com/microsoft/TypeScript/issues/44063) for that one. (Perhaps we should merge it into this?)

I think it should be merged; if not then ita description "Array.reduce doesn't work" needs to be improved. See [44063](https://github.com/microsoft/TypeScript/issues/44063#issuecomment-840083288).

**Comment by ericblade** [comment]
Probably known, but also affects:

```
const arr = [] as Array<number> | Uint8Array;
arr.reduce(...)
```

**Comment by Draccoz** [comment]
Hey @DanielRosenwasser, any estimates when could that be fixed?

**Comment by gaberogan** [comment]
For anyone looking for an easy workaround:

```ts
interface Fizz {
    id: number;
    fizz: string;
}

interface Buzz {
    id: number;
    buzz: string;
}

const arr: Fizz[] | Buzz[] = [];

arr.filter(item => item.id < 5); // This is an error

const arrFixed: Array<typeof arr[number]> = arr; // This is the fix

arrFixed.filter(item => item.id < 5); // This works!
```

It's not exactly equivalent but should work for most cases. Hope this helps!

**Comment by bmiakoun** [comment]
@gaberogan this just makes arrFixed type to `any`

**Comment by ericbf** [comment]
> @gaberogan this just makes arrFixed type to `any`

What are you talking about? Why would that result in `any`?

```ts
declare const a: string[] | number[]

const b = a.filter(Boolean); // Error. Should work and result in `string[] | number[]`
const c = (a as (typeof a[number])[]).filter(Boolean) as typeof a // Works, but wrong type. `c` is (string | number)[]
const d = (a as (typeof a[number])[]).filter(Boolean) as typeof a // Works but has two typecasts. Cumbersome.
```

[Playground link](https://www.typescriptlang.org/play?ssl=5&ssc=110&pln=1&pc=1#code/CYUwxgNghgTiAEYD2A7AzgF3lAXPTMAligOYDaAuvAD7woCuAtgEYgyUBQHy6Wz8AXmwA6AGaEIGNgAoAQkiQQQUFAEoA3PAD0W+AFEYMJDGHwAygAsk9CMHgB3YwGtsKO3DQ2sxeAAMCxORUtAwsbJS+3KiYiILw0lDYaPEYAJ4ADiBIothkoawwFKqUqmISUjByCkoqqknwaZnZ2Nq6AOrOaAA08Mz0WPZGpA0ZIKa+YL7whMnSAcMhTAXFFFG88HZCCfXSjVk5UHlLbEUlZZIy8orKavV7zYk68B0wTsl9WBZQyRiOI5lgb4YNCmADCxxgaCQjDGQA)

**Comment by Emmahchinonso** [comment]
Hello @weswigham, please has this issue been resolved?

**Comment by ericbf** [comment]
@Emmahchinonso you can see a few lines above your comment is a linked pull request that will close the issue. This issue is still open, meaning it is still open, but you can subscribe to notifications if you want.

**Comment by gegxen** [comment]
will this also gonna work after [this](https://github.com/microsoft/TypeScript/pull/53489) is merged?
```ts
const arr: string[] | number[] = [];
const val: string | number = 5;
const index = arr.indexOf(val);
```

**Comment by mon-jai** [comment]
@gegxen Doesn't seem to work.

https://www.staging-typescript.org/play?ts=5.1.0-pr-53489-26#code/MYewdgzgLgBAhgJwQLhtBBLMBzA2gXRgB8YwBXAWwCMBTBAmAXhgIG4AoUSWANzgBtU6LNmKlKtBExgBWDl2gwsAExoAPaYgQA6FeoDyAMwAUffgEoOQA

**Comment by ericbf** [comment]
@gegxen why don’t you clone the commit in the linked PR and try it?

**Comment by kkumawat333** [comment]
Copying snippet from @gaberogan 

It's better to union the type before typing it as Array.

```
interface Fizz {
    id: number;
    fizz: string;
}

interface Buzz {
    id: number;
    buzz: string;
}

TFizzBuzz = Fizz | Buzz
const arr: TFizzBuzz[] = [];

arr.filter(item => item.id < 5); // This works for me

```

**Comment by gaberogan** [comment]
@ericbf No it seems fine to me, `arrFixed` is not `any`

<img width="520" alt="Screenshot 2023-12-11 at 4 07 42 PM" src="https://github.com/microsoft/TypeScript/assets/58148287/02d2c0fb-d450-4ce7-a10d-061805a07476">

**Comment by ericbf** [comment]
> @ericbf No it seems fine to me, `arrFixed` is not `any`
> 
> <img alt="Screenshot 2023-12-11 at 4 07 42 PM" width="520" src="https://private-user-images.githubusercontent.com/58148287/289672251-02d2c0fb-d450-4ce7-a10d-061805a07476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDMxNTMsIm5iZiI6MTcwMjM0Mjg1MywicGF0aCI6Ii81ODE0ODI4Ny8yODk2NzIyNTEtMDJkMmMwZmItZDQ1MC00Y2U3LWExMGQtMDYxODA1YTA3NDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MmY2OGYxOWUyZDI2YjMwYjNiNWFlYTQxNmE0YmIxNjBjNWNjMDliZGI4NTAzMzE4ZWNkYjg5Y2JhNDE4MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQzQPizRS9wwsP3rcu2IjxEO_OJ84cyazLHxOf6DjJY">

Exactly my point—I stated that `arrFixed` in the example was not `any`, contrary to @bmiakoun's comment above. Anyways, this issue is closed now—if you find something that needs to be discussed or fixed, probably open a new issue for that.

**Comment by Jv7680** [comment]
> For anyone looking for an easy workaround:
> 
> ```ts
> interface Fizz {
>     id: number;
>     fizz: string;
> }
> 
> interface Buzz {
>     id: number;
>     buzz: string;
> }
> 
> const arr: Fizz[] | Buzz[] = [];
> 
> arr.filter(item => item.id < 5); // This is an error
> 
> const arrFixed: Array<typeof arr[number]> = arr; // This is the fix
> 
> arrFixed.filter(item => item.id < 5); // This works!
> ```
> 
> It's not exactly equivalent but should work for most cases. Hope this helps!

Or just do a simple change like this:
_ Use this: const arr: (Fizz | Buzz)[] = [];
_ Instead of this: const arr: Fizz[] | Buzz[] = [];

**Comment by ericbf** [comment]
Hello @Jv7680, this issue has been closed for a while now.

But, for the record, the issue with that suggestion is that the type would not actually be correct. But that's been discussed already further up in the thread.

**Comment by GulgDev** [comment]
That's still the case for typed arrays and .reduce():
```ts
declare const array: Uint8Array | Uint16Array;
array.filter((a, b) => a + b, 0);
```
