### ISSUE TITLE
importModuleSpecifierEnding = js doesn't apply for autocomplete within import paths

### ISSUE THREAD

**Issue by Tyriar** [microsoft/TypeScript#44374]
# Bug Report

I have this workspace setting which works great for auto import:

```json
"typescript.preferences.importModuleSpecifierEnding": "js"
```

But when auto completing the path it still does .ts which requires manually changing:

![image](https://user-images.githubusercontent.com/2193314/120075258-62f66480-c055-11eb-8c8e-45ff1a4b54b3.png)

### 🔎 Search Terms

importModuleSpecifierEnding

### 🕗 Version & Regression Information

4.3.0-dev.20210503

**Comment by jessetrinity** [comment]
Do you have 
```
{
    "compilerOptions": {
        "allowJs": true
    }
}
```

?

**Comment by Tyriar** [comment]
No I don't set that, I can't actually remember why I ended up needing to use .js imports but at some point this not having it was causing exceptions due to some bundling problem. I just tried to remove and it seemed to work, I'm a little hesitant to change it when it working though.

But why would you need `allowJS` for this to work when I've said I want to use .js imports already with `importModuleSpecifierEnding`?

**Comment by jessetrinity** [comment]
Importing a `.js` file should not be allowed at all if `allowJs` is not enabled, so files with a `.js` extension will not show up in the completion list. 

That is, if you have `allowJs: false` (this is the default) and the file
```js
// file: myLib.js
export const myConst = 1;
```
and type the following in a `.ts` file,
```ts
myConst
```

You should not be offered a completion at all. If you enable `allowJs`, this should auto complete to the `.js` file assuming you have `"typescript.preferences.importModuleSpecifierEnding": "js"`.

What I think _is_ a bug, is that we complete with the `.ts` ending at all. It looks like the `importModuleSpecifierEnding` setting is just used to decide whether or not we remove the extension on string literal completion in the import. If `allowJs` is false, the `.js` import is not found, but we still offer the completion for the `.ts` file with the same name, but with the extension (incorrectly) attached. I think in this case we should offer the completion without any extension.

**Comment by Tyriar** [comment]
I can't remember the exact reason but using .js fixed a compile/bundling issue for me at some point. I use tsc and then webpack on its output.

**Comment by andrewbranch** [comment]
Auto imports are working correctly and these path completions are working incorrectly. It’s never correct to write `.ts` in a module specifier. You are always allowed to write a module specifier for a TS file _as_ a `.js` path, and you are allowed to write an import for an actual JS source file only if `allowJs` is enabled. The example shown here is for a TS source file, so the completion should be shown as `number.js` regardless of the `allowJs` setting.
