### ISSUE TITLE
Indexed access type isn't taking information from conditional into account

### ISSUE THREAD

**Issue by sigurdschneider** [microsoft/TypeScript#44387]
# Bug Report

### 🔎 Search Terms

index type, indexed access type, index access operator, extends, Exclude, conditional type

### 🕗 Version & Regression Information

This is the behavior in every version I tried (3.3.3 to 4.3.2), and I reviewed the FAQ for entries about indexed access types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QEwjDmABsBnARgH4AuTAT1vLClAHMBfAbhz0OJlyAJjqYAHs1YceWTliwwAriARhgAexDIEUCHEgAeAApQNABwBycALYoI4yCHzlkAawgMNMNAD4AFHy4ILYQ9KYW1nbIADTIcPSoAJT0AKLiCKRKhIaoANoRVqEAunEqhDCgEPi+mEE6WizIkmgFZkV2xcgAvPF5IZ28eMjAPv7iSch6YEpQ2uJDeGAAFmYA7sggEBupUGZQ-km8nEA)

### 💻 Code

```ts
interface A {
    details1?: {y:string};
    details2?: {x:string};
}

function create<PropName extends keyof A>(
    name: PropName , a: A): Exclude<A[PropName], undefined> {
    const x: A[PropName] = a[name];
    if (x) return x; // Type error: Type 'A[PropName]' is not assignable to type 'Exclude<A[PropName], undefined>'.
    throw new Error();
}
```

### 🙁 Actual behavior

TypeScript complains that `x` in `if (x) return x;` is of type 'A[PropName]' and is not assignable to type 'Exclude<A[PropName], undefined>', because it assumes that `x` can be undefined.

### 🙂 Expected behavior

I would have expected that this works, as `return x` is the consequence of the conditional `if (x)`, so `x` cannot be `undefined`.

Thanks for taking the time to look at this!

**Comment by RyanCavanaugh** [comment]
Duplicate #31908 & others. We'd need, at a minimum, #22348 to be able to model this correctly.

**Comment by sigurdschneider** [comment]
Too bad, thanks for taking a look.
