### ISSUE TITLE
Convey discriminating union field information throughout function calls

### ISSUE THREAD

**Issue by MartinMuzatko** [microsoft/TypeScript#44385]
# Suggestion

## 🔍 Search Terms

* discriminating unions
* discriminated unions
* unions

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code **(please help me figure out)**
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A type that has a common property with other types can be used as discirminator for an union type. When working on individual properties that have to be transformed (e.g. parsed), that information cannot be conveyed to the caller assembling the new object with the correct type. This happened to me when attempting to parse one union type to another union type.

I might have overlooked a solution and this also might be a very narrow use-case, but nevertheless I think a valid one.

See full example with interfaces on the [TS playground](https://www.typescriptlang.org/play?#code/LAKAlgdgLgpgTgMwIYGMYAIAiMJgF44CqEADknAM4wAmASjCmCTAMoAWSzANjBRegG9Q6EeigBPZgC50AcgoduvCrOGjIJAK5QZFKHEgBzUAF9QoSLESoM2XAQjEylGvUbN2nGoLUiJ0uQUvalUQUXQNbV19IwBtAF1Tc3BoeGQ0LBx8IlJyKjoGJhgAMU04CBsfMNF-GBlZBDKKtFDw2RQAew6AawB9KDAAWxhZaIMIY2qRSJ10PXHJsxALVOsMu2yINyLPJT4q8Nr6oL2VXwjSKLmYiYSk5ZSrdNssh22PRW8hKbFJOsDPiFzjMxnF4ncQEsVk9Khs3oVmKVypVvoc-vVGsiWud2l0+gNhqNrgtgZdZvMjPdQLVMvYcO8MABeWmbBm7GA8fYAHxZ8PcrEB6B5cPpCJKTUqADIDqIOtotFBegBHTRIaBgCQyCCaQYAI3gVJANJFjlyLgK-PQzJNTjyrjF7M5-GFrxyznybMFLrppvd9v5SOaGGlqNl8u0ytV6s16G1eoNkOSnQgenQfpNDIAkmSregABRwMUyG1mj1igCUVoAfDLpgh84X+QA6GmM5nyT5O2SVwtQJroRtFJszJsUEhcDV52Rc7vA+sFsUtv5W9snGjdgcwPvlTfNkeDTh5sDViKj8eT6fd8vnXv9wfMYdkw3J1Pp11bMW5hf84vv23mhly1-H0GRPPNQxEJsoPvGAABpSQVGQ3xAsVswVb8imvSFyyAA).

``` ts
const parseDenizenRecipeInput = (recipe: DenizenUnparsedRecipe) => {
    if (recipe.type == 'shapeless') return recipe.input.split('|')
    if (recipe.type == 'shaped') return recipe.input.map(i => i.split('|'))
    return recipe.input
}

const parseDenizenRecipe = (recipe: DenizenUnparsedRecipe): DenizenRecipe => ({
    ...recipe,
    input: parseDenizenRecipeInput(recipe)
})
```

This results into this error:
``` ts
const parseDenizenRecipeInput: (recipe: DenizenUnparsedRecipe) => string | string[] | string[][]
Type '{ input: string | string[] | string[][]; type: "shapeless"; }' is not assignable to type 'DenizenRecipe'.
  Types of property 'input' are incompatible.
    Type 'string | string[] | string[][]' is not assignable to type 'string[]'.
      Type 'string' is not assignable to type 'string[]'.(2322)
```

As you can see from the error message, it is assumed that the three variants ( `string` | `string[]` | `string[][]` ) are now available for all types of the discriminated union type. In this case, `shapeless` - the first type of the union type is used as example. 

To help TypeScript understand my intention, I would assume that I can convey that I'm still working on the same discriminating union property. e.g. by hinting the return signature to the union type field specificially:

``` ts
const parseDenizenRecipeInput = (recipe: DenizenUnparsedRecipe): DenizenRecipe['input'] => {
    if (recipe.type == 'shapeless') return recipe.input.split('|')
    if (recipe.type == 'shaped') return recipe.input.map(i => i.split('|'))
    return recipe.input
}
```

## 📃 Motivating Example

_given that this gets implemented:_

When working on individual fields of an union type, the associated type information can be conveyed throughout function calls. This helps to apply single responsibilty best practice while keeping the function implementation clean from re-implementing the entire object.

This is especially useful when transforming from one union type to another union type and using different functions to transform or re-assemble the object to match the target type.

## 💻 Use Cases

This is the workaround that I use in the meantime:

``` ts
const parseDenizenRecipeInput = (recipe: DenizenUnparsedRecipe) => {
    if (recipe.type == 'shapeless') return { ...recipe, input: recipe.input.split('|') }
    if (recipe.type == 'shaped') return { ...recipe, input: recipe.input.map(i => i.split('|')) }
    return recipe
}

const parseDenizenRecipe = (recipe: DenizenUnparsedRecipe): DenizenRecipe => ({
    ...recipe,
    ...parseDenizenRecipeInput(recipe)
})
```

The second workaround would be to make the transformation of the input directly in the function.
I could either inline the expression as ternary or bloat up the function by not directly returning an object.

In order to re-use functions as much as possible, I don't want to inline such logic there.

``` ts
const parseDenizenRecipe = (recipe: DenizenUnparsedRecipe): DenizenRecipe => {
    let input = recipe.input
    if (recipe.type == 'shapeless') input = recipe.input.split('|')
    if (recipe.type == 'shaped') input = recipe.input.map(i => i.split('|'))
    return {
        ...recipe,
        input,
    }
}
```

**Comment by RyanCavanaugh** [comment]
There are two suggestions here:
 * Infer a generic function type of some sort for `parseDenizenRecipeInput`, something like `f<T extends Recipe>(arg: T): SomeLookup[T]`
 * Use that information to infer that the `{ ...recipe, ...f(recipe) }` form is valid

The first one is not something we'd do for a number of reasons, primarily that we don't infer a generic function if you didn't declare one, and secondarily that we don't think type *inference* for a function should appear as a regurgitation of the function's control flow graph as expressed as a type.

The second one isn't even plausible IMO, because it would require same-reference tracking -- the form `{ ...a, f(a) }` would have to be understood to be *a different thing* from the form `{ ...a, f(b) }` even in cases where `a` and `b` at the same declared type, because the form is valid if and only if the argument to `f` is exactly the same reference as the first spread operand. Determining in JS if two arbitrary expressions are a reference to the same object is extraordinarily difficult to get right and would require a level of tracking we're not interested in spending performance/complexity budget on at this time.

**Comment by MartinMuzatko** [comment]
Thank you for the explanation.
