### ISSUE TITLE
Array methods on union of tuples with empty tuple

### ISSUE THREAD

**Issue by gitcoden** [microsoft/TypeScript#44383]
# Bug Report

### 🔎 Search Terms

empty tuple

### 🕗 Version & Regression Information

4.3.2

### ⏯ Playground Link

https://codesandbox.io/s/old-night-gx7t9?file=/src/some.ts

### 💻 Code

index.ts
```ts
type Tuple = ["A"] | [] | ["A", "B"];

export var a: Tuple = ["A", "B"];

var c: Tuple = ["A"];

c.includes("B");

a.includes("B");

```

some.ts
```ts
import { a } from "./index";

a.includes("B");
```

### 🙁 Actual behavior

in some.ts you get `Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)`

Good error for `c.includes('B');`, but not obvious error when importing variable with union of tuples type

### 🙂 Expected behavior

You cat use includes and indexOf for such unions

**Comment by MartinJohns** [comment]
The behavior is the same, regardless of the export. You got mislead by this assignment:

    export var a: Tuple = ["A", "B"];

`a` is **not** typed `Tuple`, but it's typed `["A", "B"]`. TypeScript never sees a re-assignment. This behavior is intentional.

You can get the desired behavior by using a type assertion:

    export var a: Tuple = ["A", "B"] as Tuple;

**Comment by MartinJohns** [comment]
This is essentially a duplicate of #26255, which points to #14520.

**Comment by gitcoden** [comment]
> The behavior is the same, regardless of the export. You got mislead by this assignment:
> 
> ```
> export var a: Tuple = ["A", "B"];
> ```
> 
> `a` is **not** typed `Tuple`, but it's typed `["A", "B"]`. TypeScript never sees a re-assignment. This behavior is intentional.
> 
> You can get the desired behavior by using a type assertion:
> 
> ```
> export var a: Tuple = ["A", "B"] as Tuple;
> ```

i get error in some.ts not in index.ts

**Comment by MartinJohns** [comment]
> i get error in some.ts not in index.ts

You get the **same** error in `index.ts` when the conditions are the same: `a` is typed `Tuple`. This is the case in `some.ts`, but it's not in `index.ts` (due to the behavior I mentioned).

**Comment by gitcoden** [comment]
in `index.ts` error in for c which is good

**Comment by gitcoden** [comment]
using type assertion causing error `Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)` to raise even in `index.ts`

**Comment by gitcoden** [comment]
well i guess what you saying is that my elems got the most narrow type which is never but i thought that it will be `undefined | "A" | "B"` for such union

**Comment by gitcoden** [comment]
Thanks, closing this one

**Comment by gitcoden** [comment]
see also https://github.com/microsoft/TypeScript/issues/43787
