### ISSUE TITLE
Types for MediaRecorder

### ISSUE THREAD

**Issue by nVitius** [microsoft/TypeScript#44398]
# lib Update Request
I'm making this issue to track the request to add the types for the MediaStream Recording API into TypeScript.

Spec can be found here: https://github.com/microsoft/TypeScript/issues/34728
MDN Docs here: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

There was an issue opened a few years ago about this, but was closed as "unactionable". It would be great to have these types available without needing to install a third-party lib as a dependency. Especially considering that this API is supported by all major browsers. Also, the interfaces for the MediaStream APIs, which this uses, already exist in TS.

I am creating a PR in the DOM-lib-generator and will update this issue.

**Comment by nVitius** [comment]
The previous issue I mentioned can be found here: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

**Comment by guiseek** [comment]
https://github.com/microsoft/TypeScript/issues/34728#issuecomment-913241426

**Comment by jakebailey** [comment]
This was fixed in #44684.
