### ISSUE TITLE
Cannot pass optional property _a_ to the other type's optional property _b_ if `--strictOptionalProperties=true`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [microsoft/TypeScript#44390]
# Bug Report

### 🔎 Search Terms

- `--strictOptionalProperties`, Strict optional properties
    - #43947
    - #13195

### 🕗 Version & Regression Information

- `typescript@4.4.0-dev.20210602`.
    - I seem this contains https://github.com/microsoft/TypeScript/pull/43947
- This changed between versions `typescript@4.4.0-dev.20210601` and `typescript@4.4.0-dev.20210602`
    - Of course, this will not be happen if `--strictOptionalProperties=false`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210602#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XAfgC5kQBXAWwCNoBuLAXyyxjJATGAHsRkuzIUABSgADgJKoAlJhx5QIaEOx5VyAPTrkYAJ6iIAZwRRgosMgRcKo4ABtoyAO7AwAC2QADALReDYExwA8mbcIHC2AApQXPpQnIYAvP5kEB5OdrbIBnA6yK7QKMAGyNDRUPgGcmoaWsgAfMgAKnooAOTk1A4APshsACYQMKAQfa3IRaRc5nAGBsAA5mFU9tpc2i3I7ZQ0UK0AdFVqmrgNzfqb-YPDo+PFIFMVc4twyyhga7rnW527e2AGQgATABmQGAqSHVRwEhiAR7OAAGkODCk9CYLDYHFC4xAimEsLAkhk2AYQA)
At this moment which I filed this issue, typescript playground does not prepare to use `4.4.0-dev.20210602`.

### 💻 Code

```ts
interface A {
    a?: number;
}

function outer(input: A) {
    inner({
        // typescript compiler with `--strictOptionalProperties=true` will say here is error as
        //  > Type 'number | undefined' is not assignable to type 'number'.
        //  > Type 'undefined' is not assignable to type 'number'.ts(2322)
        a: input.a,
    });
}

function inner(input: A) {
}
```

### 🙁 Actual behavior

TypeScript compiler fail to compile the the above example with the reason I commented.
After I read #43947, I could not conclude the current behavior is expected design. So I filed this as a bug.

### 🙂 Expected behavior

I thinks this should be pass to compile.

### Remarks

If we pass `outer`'s `input` to `inner` directly like the following example, typescript compile success to compile.

```ts
interface A {
    a?: number;
    b: string;
}

interface B {
    a?: number;
}

function outer(input: A) {
    inner(input);
}

function inner(input: B) {
}
```

**Comment by fatcerberus** [comment]
`strictOptionalProperties` means, roughly, that an optional property must either exist with the specified type, or not exist at all.  Allowing the assignment would mean you've possibly created an explicit property with the value `undefined`, which is counter to the purpose of the flag.

**Comment by tetsuharuohzeki** [comment]
Ah, I see what #13195 aims. By that, this would not be a bug. Thank you.
