### ISSUE TITLE
Bad template string refactor w/ existing template strings

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript#44396]
Doing a Convert to template string refactors

    const a = `x` + `y` + text + "z";

to

    const a = `${`x` + `y` + text}z`;

which isn't invalid but would be better to convert it to

    const a = `xy${text}z`;

(There is also a point to not do the refactor at all when the author meant to split the template strings, but in that case they just won't use the refactor.)

**Comment by fatcerberus** [comment]
> ```ts
> const a = `${`x` + `y` + text}z`;
> ```

I'm kind of surprised that works. I'd expect the backticks inside the `${}` to need to be escaped.
