### ISSUE TITLE
Object.fromEntries: return type does not account for symbols

### ISSUE THREAD

**Issue by mfulton26** [microsoft/TypeScript#44405]
https://github.com/microsoft/TypeScript/blob/d2516fa95bddf56e8851e54c6e9fec6c6e034a36/src/lib/es2019.object.d.ts#L8

```ts
const record = Object.fromEntries([[Symbol.for("1"), "hi"]]);
console.log(record[Symbol.for("1")]);
```

```console
error: TS2538 [ERROR]: Type 'symbol' cannot be used as an index type.
console.log(record[Symbol.for("1")]);
                   ~~~~~~~~~~~~~~~
```

the return type should account for objects built with symbols for keys (e.g. through a generic type or something)

**Comment by jcalz** [comment]
There's a [whole template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) you're supposed to fill out when you file a bug here, to help the TS team triage and respond.

Anyway I don't think much can be done here until something like #35909 and #26797 are dealt with.  Also relevant: #37457, with the comment: "Symbols are still dropped on the floor, just like the rest of the compiler."

**Comment by mfulton26** [comment]
Weird, I was never prompted with a template. Maybe that is because I made the issue from clicking the referenced line of code...
