### ISSUE TITLE
Inconsistent assignment of function type with optional fields

### ISSUE THREAD

**Issue by duarten** [microsoft/TypeScript#44406]
# Bug Report

### 🔎 Search Terms

Generics

### 🕗 Version & Regression Information

This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.3.2#code/KYDwDg9gTgLgBDAnmYcAqBGOBeOBvAKDmLimAEMATCAOwBtE4QAuOAZxigEsaBzAgL4ECoSLATJUaAEw58REmSq0GTAPysO3PoOFIUcAGJZcAChitMAShwA+OADcIXSgX2pDssxfTSb2eycXPUkjAGY5OAAeNFtzS39A51cCSmAAYzpyMjh02g4mVmMCPJoCxCKI3BBhNMzs1FKChyLpEvz4AHdKuQdhRAJOoA)

### 💻 Code

```ts
export type T1 = {
    readonly x: string
}

export type T2 = {
    readonly x?: string
}

type F1 = (t: T1) => void
type F2 = (t: T2) => void

type F3 =  <T>(t: T) => void

declare const x: F1
const y: F3 = x

declare const v: F2
const w: F3 = v
```

### 🙁 Actual behavior

The assignment of `y` doesn't compile with:

```
Type 'F1' is not assignable to type 'F3'.
  Types of parameters 't' and 't' are incompatible.
    Type 'T' is not assignable to type 'T1'.
```

However, the assignment of `w` compiles fine.

### 🙂 Expected behavior

 I would expect both to be consistent. Furthermore, I would expect both assignments to compile, since `F3` essentially expects `any`.

**Comment by duarten** [comment]
Note that if I change `F3` to `type F3 = <T extends T1>(t: T) => void`, it compiles fine.

**Comment by RyanCavanaugh** [comment]
This is correct and intended behavior. The assignability is checked here by comparing the argument type to the implied constraint of the type parameter, which here is `{ }`, and `{ }` is assignable to an all-optional type but not a type with a required property.

Different code doing different things is not inconsistency, it's how you're able to write different programs, and being able to write different programs is not a defect.

**Comment by duarten** [comment]
> This is correct and intended behavior. The assignability is checked here by comparing the argument type to the implied constraint of the type parameter, which here is `{ }`, and `{ }` is assignable to an all-optional type but not a type with a required property.

Ah, I didn't know that given a generic parameter, it was implicitly constrained to `{}`. My expectation was that, like a generic function `function foo<T>(t: T) { ... }`, `T` could be correctly bound to either `T1` or `T2`.

> Different code doing different things is not inconsistency, it's how you're able to write different programs, and being able to write different programs is not a defect.

No need to condescend.

**Comment by RyanCavanaugh** [comment]
Apologies it came across that way; not my intent.
