### ISSUE TITLE
strict-optional-properties error: Type 'Window & typeof globalThis' is not assignable to type 'Window'

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#44417]
# Bug Report

### 🔎 Search Terms

strictoptionalproperties, global

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strictOptionalProperties=true&ts=4.4.0-dev.20210602#code/MYewdgzgLgBADgLhgdQJZgCYgO4wLwzbpbYDcQA) (and enable `strictOptionalProperties`)

### 💻 Code

```ts
const w: Window = window;
```

### 🙁 Actual behavior

```
test.ts:1:7 - error TS2322: Type 'Window & typeof globalThis' is not assignable to type 'Window'.
  Types of property 'ontouchcancel' are incompatible.
    Type '(((this: GlobalEventHandlers, ev: TouchEvent) => any) & ((this: Window, ev: TouchEvent) => any)) | null | undefined' is not assignable to type '((this: GlobalEventHandlers, ev: TouchEvent) => any) | null'.
      Type 'undefined' is not assignable to type '((this: GlobalEventHandlers, ev: TouchEvent) => any) | null'.

1 const w: Window = window;
        ~
```

### 🙂 Expected behavior

Usually, `T & U` is assignable to `T`.

**Comment by DanielRosenwasser** [comment]
CC @ahejlsberg - it is kind of weird that optional properties on `Window` don't have corresponding optionality on globals (#36057).

It sounds like the "easiest" workaround is just to mark all the optional properties/methods in the DOM as `| undefined`.

**Comment by amcasey** [comment]
I think fixing the new errors in https://github.com/mui-org/material-ui might be a useful exercise.  It looks like there are going to be some issues for consumers of @types/react if we don't seed an update.

**Comment by sandersn** [comment]
Fixed by https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1092 and subsequently https://github.com/microsoft/TypeScript/pull/45324
