### ISSUE TITLE
For almost every .tsx file in my project TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists. 

### ISSUE THREAD

**Issue by wegry** [microsoft/TypeScript#44418]
# Bug Report

### 🔎 Search Terms

`TS7026` `no interface JSX.IntrinsicElements exists typescript 4.3` `typescript 4.3 breaking changes`.

### 🕗 Version & Regression Information

- This changed between versions 4.2.4 and 4.3.2
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

The tsconfig.json in our project

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "importsNotUsedAsValues": "error",
    "incremental": true,
    "isolatedModules": true,
    "moduleResolution": "node",
    "noEmit": true,
    "noEmitOnError": true,
    "jsx": "react-jsxdev",
    "lib": ["dom", "ES2020"],
    "allowJs": true,
    "module": "ES2020",
    "resolveJsonModule": true,
    "strict": true,
    "target": "ES2020",
    "types": [],
    "useDefineForClassFields": true
  },
  "include": [
    "./typings.d.ts",
    "./react-table-config.d.ts",
    "app",
    "components",
    "pages"
  ],
  "exclude": ["**/node_modules", "**/.*/"]
}
```

### 🙁 Actual behavior
Using Yarn 3 with PnP and webpack 5. We're also using the ts fork checker plugin. With a project that built in typescript@4.2.4, typescript@4.3.2 errors has an error in every tsx file.

It's usually

`TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`

But there are a few

```
TS2322: Type '{ title: string; }' is not assignable to type 'Props'.
  Property 'children' is missing in type '{ title: string; }' but required in type '{ children: any; title?: string; }'.
  ```

and 

```
TS2307: Cannot find module 'react/jsx-dev-runtime' or its corresponding type declarations.
```

### 🙂 Expected behavior

There might be a few broken things from breaking changes, but the project should compile.

**Comment by MartinJohns** [comment]
This sounds like #41813. Tho that changed with version 4.2.1.

**Comment by wegry** [comment]
@MartinJohns is there a way to see which libraries are using a global namespace v. which are not? Maybe within the `tsc` command itself?

**Comment by wegry** [comment]
After doing a `yarn up -R @types/react{,-dom}` and bumping to @yarnpkg/berry@3.0.0-rc.5, these errors were no more with typescript@4.3.2.

**Comment by wegry** [comment]
I'm seeing this again with `typescript@4.4.2`.

**Comment by MartinJohns** [comment]
Possibly related to #45681.

**Comment by abitwhy** [comment]
This may be caused by IED (like VSCode). When an update prompt appears, try updating it first.

**Comment by amir-rz** [comment]
I just updated the VSCode and it solved the issue.

**Comment by lolmaus** [comment]
I had this error on Windows while keeping my code in WSL.

Turns out, that despite I opened VS Code via `code .` in WSL, it didn't use the WSL remote and instead opened it via an SMB network share path.

When I reopened the project in the WSL remote, the errors were gone.
