### ISSUE TITLE
ts.Node.getChildren() returns duplicate copies of the same AST nodes in TS 4.3

### ISSUE THREAD

**Issue by octogonz** [microsoft/TypeScript#44422]
# Bug Report

Starting with TypeScript 4.3, the `ts.Node.getChildren()` API may return two copies of the same AST node.

### 🔎 Search Terms

`getChildren`

### 🕗 Version & Regression Information

Repros with TypeScript `4.3.2` and `4.4.0-dev.20210602`

Does NOT repro with TypeScript `4.2.4`

### 💻 Code

Here is a complete project that reproduces the problem: [repro.zip](https://github.com/microsoft/TypeScript/files/6594367/repro.zip)

The code looks like this:

**repro.js**
```ts
const path = require("path");
const ts = require("typescript");

console.log('Start')
try {
  const inputPath = path.join(__dirname, "input.ts");
  const program = ts.createProgram([inputPath], {});
  program.getSemanticDiagnostics();
  const sourceFile = program.getSourceFile(inputPath);
  const docNode = sourceFile.getChildren()[0].getChildren()[0].getChildren()[4].getChildren()[0].getChildren()[0].getChildren()[0];

  for (const child of docNode.getChildren()) {
    console.log(`[pos=${child.pos}, end=${child.end}] ` + child.getText())
  }

  debugger;
} catch (error) {
  console.error(error.stack);
  debugger;
}
```

It uses the compiler API to parse an input like this:

**input.ts**
```ts
export class TypeReferencesInAedoc {
  /**
   * Returns a value
   * @param arg1 - The input parameter of type {@link TypeReferencesInAedoc}.
   * @returns An object of type {@link TypeReferencesInAedoc}.
   */
  public getValue(arg1: TypeReferencesInAedoc): TypeReferencesInAedoc {
    return this;
  }
}
```

### 🙁 Actual behavior

The printed output looks like this:

```
[pos=73, end=78] param
[pos=79, end=83] arg1
[pos=84, end=114] - The input parameter of type
[pos=114, end=143] {@link TypeReferencesInAedoc}
[pos=143, end=151] .
   *
[pos=84, end=114] - The input parameter of type
[pos=114, end=143] {@link TypeReferencesInAedoc}
[pos=143, end=151] .
   *
```

The duplicated pos/end nodes are actually the same object instances, which can be verified in the debugger:
```
docNode.getChildren[3] === docNode.getChildren[6] 
true
```

### 🙂 Expected behavior

`ts.Node.getChildren()` should not return duplicate nodes.

**Comment by DanielRosenwasser** [comment]
Seems like we might need to back-port this to 4.3.

**Comment by sandersn** [comment]
I suspect that these nodes are being added both as jsdoc children and as normal children inside the tree-trivia-reconstruction part of the services code.

**Comment by sandersn** [comment]
Repro in ts-ast-viewer shows this off interactively, right down to highlighting *two* items in the tree pane: https://ts-ast-viewer.com/#code/PQKhCgAIUgBAHAhgJ0QW0ig5gRkgFQAsBTSAb1gBsBLAOwGsCBPeYgJWIDNjljaBjYgGcAkrQCCxACYB7fgF8AdFBDBwANxSQAHuCA

For the smaller program:

```ts
/**
 * @param arg1 The {@link TypeReferencesInAedoc}.
 */
var x
```

Note that this doesn't repro with `@return` or for top-level comments.

**Comment by octogonz** [comment]
> ts-ast-viewer shows this off interactively

(In order to see this, you need to change `Tree mode:` to be `node.getChildren()`.  The ts-ast-viewer.com URL apparently doesn't preserve that state.)

**Comment by sandersn** [comment]
Anyway, it's just a bug in the visitor code for `@param`/`@property`:

```ts
            case SyntaxKind.JSDocParameterTag:
            case SyntaxKind.JSDocPropertyTag:
                return visitNode(cbNode, (node as JSDocTag).tagName) ||
                    ((node as JSDocPropertyLikeTag).isNameFirst
                        ? visitNode(cbNode, (node as JSDocPropertyLikeTag).name) ||
                            visitNode(cbNode, (node as JSDocPropertyLikeTag).typeExpression) ||
                            (typeof (node as JSDoc).comment === "string" ? undefined : visitNodes(cbNode, cbNodes, (node as JSDoc).comment as NodeArray<JSDocComment> | undefined))
                        : visitNode(cbNode, (node as JSDocPropertyLikeTag).typeExpression) ||
                            visitNode(cbNode, (node as JSDocPropertyLikeTag).name)) ||
                            (typeof (node as JSDoc).comment === "string" ? undefined : visitNodes(cbNode, cbNodes, (node as JSDoc).comment as NodeArray<JSDocComment> | undefined));
```

This visits the comment twice, and the test we have to make sure the visitor covers everything doesn't check for double visits.

**Comment by octogonz** [comment]
Thanks for getting this fixed!
