### ISSUE TITLE
ESNext subclasses in 4.3 breaks assignments in super constructor

### ISSUE THREAD

**Issue by jnordberg** [microsoft/TypeScript#44429]
I have code that worked fine compiled with target set to ESNext up until TypeScript 4.3.

Simplified it looks something like this ([real world example](https://github.com/greymass/eosio-core/blob/master/src/chain/struct.ts#L15)):

```ts
class Struct  {
    static fields: {name: string}[]
    constructor(object: any) {
        const self = this.constructor as typeof Struct
        for (const field of self.fields) {
            this[field.name] = object[field.name]
        }
    }
}

class MyStruct extends Struct {
    static fields = [{name: 'foo'}]
    foo!: string
}

const s = new MyStruct({foo: 'bar'})

console.log(s)
```

This produces the following output when compiled with `tsc --target esnext` and executed with node.js v16.2

```
MyStruct { foo: undefined }
```

With TypeScript 4.2 (or target set to es2020) the output is as expected

```
MyStruct { foo: 'bar' }
```

The difference is that 4.3 generates:

```js
class MyStruct extends Struct {
    static fields = [{ name: 'foo' }];
    foo;
}
```

while 4.2 generates:

```js
class MyStruct extends Struct {
}
MyStruct.fields = [{ name: 'foo' }];
```

---

The obvious workaround is to not use the ESNext target but I figured that I would share since this took ages to track down. Stepping in the debugger makes it look like all the struct fields magically turn into undefined when returning from the constructor.

Keywords: esnext, class, subclass, super, constructor, assignment

**Comment by whzx5byb** [comment]
See: https://github.com/tc39/proposal-class-fields#fields-without-initializers-are-set-to-undefined
Solution: change `foo!: string` to `declare foo: string`

**Comment by jnordberg** [comment]
Thanks!

Yes I know the ESNext target isn't stable but up until pretty recently when the ES2020 target was added it was the only option when targeting a modern bundler and most project templates and examples still uses it.

**Comment by dnalborczyk** [comment]
@jnordberg you can opt-in to the behavior of javascript classes and use [useDefineForClassFields](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) even with target ES2020 or ES2021.
