### ISSUE TITLE
Type narrowing does not work for unions which contain template literals.

### ISSUE THREAD

**Issue by Inrixia** [microsoft/TypeScript#44435]
# Bug Report

Type narrowing does not work for unions which contain template literals, the type fails to narrow.

### 🔎 Search Terms

Narrowing type literals
I found an existing issue that seems similar to this, however what they are trying to do is fundamentally different to what I am. https://github.com/microsoft/TypeScript/issues/42007

### 🕗 Version & Regression Information

Today

This is the behavior in every version I tried, and I reviewed the FAQ for entries about template literal type narrowing

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gJwRAxsKBeKBvAsAKAEgU4ATCALigGdgEBLAOwHMDCwE5IFQq6BXCGwhIq-RuQBmTCKQIBfAqEhQAokkw5hoqAAMAJNloMW8qPWpQA7pxYBCXQqXhoAZTgBbCACUIwfgiMACoumvBIqOgAPmpIANwEBAD0SbDIAIbA0OlQEAAe6R5gADbQTLTpjCjQcJJQwAAW0MrNcDQNcFb1TVAARpwA1hCMUIzpSJ1MzAB0BCSMtLkFRaVU7l6+-oEhKljYZumW6z5+AcEuCfjJqQCSdRxcIqC5GhZQ4lIypN3DP-Wh1A6-GK3zGEy6wDa4WQaGmcII9DqAAp8oUShBpiIEJgMFgPhBpIxZABKLREFJQG4LLLpb6NZoA4DpECWek0QrZCSUqDMPxQAAKnG4z1IcAglkYcHQ+QswDswmW6OmD2FIEuiiumopABE4FM-tQOdZ6I0oDlJSNiiaROlii9ONivNRDbzEvgWlAAHJwRgAGWtCFt6gdmjwRCxVGMUyc7tCx02Zx2EG9foDtrCiBh0S9Pv9WUDxWDiEu1zSEEy2SWaNK5mplWqUFqfw9kPanT+VkQA31YM4Vn1-Go+vNPqgVvzttm+HmiwteZthcVqyg8dO2xcKfnBdDByOnhOW3OkE3aeKJfwFLuUBVTxA9vMlnxhNkPxGbI9gLgwNB4z79ShmaRHCU6IlASJzqeqhLhiWI4niEgEl8pJhoQFIAIJciaUCiuK8pEBBE6LtWGI3jwaoxkAA)

### 💻 Code

```ts
type Correct = {
	code: string
	property: true
	err: undefined
}
type Err = {
	err: `${string} is wrong!`
}
type SomeReturnType = Correct | Err;

// Create a example instance of the type to show the broken narrowing.
const example: SomeReturnType = {} as SomeReturnType;

// If property err is undefined then the type should narrow to Correct...
if (example.err === undefined) {
	// Instead the type stays the same and I get Property does not exist!
	example.property;
}


// Doing the same with a non literal error message

type NonLiteralError = {
	err: string
}
type SomeReturnTypeNonLiteral = Correct | NonLiteralError;

// Create a example instance of the type to show the working narrowing using a non literal.
const nonLiteralExample: SomeReturnTypeNonLiteral = {} as SomeReturnTypeNonLiteral;

// If property err is undefined then the type should narrow to Correct...
if (nonLiteralExample.err === undefined) {
	// And it does!
	nonLiteralExample.property;
}
```

### 🙁 Actual behavior
Type should narrow to `Correct` on check that err is undefined .

### 🙂 Expected behavior
Type stays `SomeReturnType` and does not narrow.

**Comment by RyanCavanaugh** [comment]
Should be a straightforward bug to fix since this works as expected for a regular string. Somewhere an `if` or `switch` is missing a case.
