### ISSUE TITLE
Function generic types will not be evaluated by conditional types

### ISSUE THREAD

**Issue by lsby** [microsoft/TypeScript#44433]
# Bug Report

### 🔎 Search Terms

generics, function, conditional types

### 🕗 Version & Regression Information

Tested with 4.2.3, 4.3.2, 4.4.0-dev.20210602

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBA5hwBVwQDzAHxQLxWFCAHsBAHYAmAzlBcAE4CWJMUA-NXY8wFxQkCuAWwBGEWgFgAUADM+JAMbB6AexJQZJFAEF8RUpXYMm6ABQBKKAG9JUG1ABuAQ1pQCPOImRbMOAOQOhcj6SAL5AA)

### 💻 Code

```ts repro
type getType<t> = t extends string ? string : number
function fun<A extends string>() {
    var x: getType<A> = 'abc'
}
```

### 🙁 Actual behavior

`getType` is a type calculation. If the input type is `string`, return `string`, otherwise return `number`.

In the function `fun`, there is a variable `x` of `getType<A>` type.

Because I stated `A extends string`, It is logical to say that `getType<A>` is a `string`.

but TypeScript will not infer this. TypeScript complains: `Type 'string' is not assignable to type 'getType<A>'`.

### 🙂 Expected behavior

`getType<A>` should be inferred as `string`

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/39787#issuecomment-670477332

**Comment by RyanCavanaugh** [comment]
In general it's not safe to perform this substitution. Consider if you had written this:

```ts
type getType<t> = t extends "hello" ? string : number

function fun<A extends string>(arg: A): getType<A> {
    // alleged: this should be OK
    var x: getType<A> = 42;
    return x;
}

const s: string = fun("hello");
```
If we perform the constraint substitution, then we get `string extends "hello"`, which is false, so we pick `number` and let you return `42` from this function. But at the call site, `A` *is* `"hello"`, and we're really expecting a `string` to come out.

One could maybe imagine a full variance tracking system that encoded all this information in a way that checked the body in a sound way, but it's not really in scope at the moment.

**Comment by lsby** [comment]
thank you for your reply.
You are right, the problem is more complicated than I thought.
I look forward to a good solution in the future.
