### ISSUE TITLE
Union of functions with same signature not seen as equivalent to a function with the same signature and union of return values

### ISSUE THREAD

**Issue by ericbiewener** [microsoft/TypeScript#44440]
# Bug Report

### 🔎 Search Terms

`"function union" signatures return`

### 🕗 Version & Regression Information

4.3.2, 3.3.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about anything related to this.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/C4TwDgpgBAYgdgRigXigCgK4CcA2AuKAZ2CwEs4BzAShQD4oAFLAewFtTCIAeAN2dIAmtAFChIsOACYU6bPiIly1OuhrJ6TNh259BIsdHgBVOKWZwZ8JAB8Jk4cIEQAxjgCGWaADMMcZ8DMLL2ZmNAAPAmNTcyoCXQFHF3dPKGdzYigvREjERNcPaDS4DKzJHPthYNCshCpKkLRSuqq0NDUNFnZOADpPQmYcHgg2utFwaAAlCGBsOCjAmUa4HJNA9vRuzY8KQgIGDzdWaYgsQi5581p1qZmsOAAVcfO4Vcux8RvZi6lFrJXouDrb4OIoZTy3OYvAEET53b6-QEqTC4dZZZE4Oqg4BQcFfKGBMpQWGQ14-VBLdbo1FwKlAA)

### 💻 Code

```ts
type Fn1 = (url: string) => Promise<void>
type Fn2 = (url: string) => () => Promise<void>
type FnUnion = Fn1 | Fn2

declare function foo(x: FnUnion): void
declare const fn1: Fn1
declare const fn2: Fn2

foo(fn1)
foo(fn2)
foo(() => Promise.resolve())

type ReturnFnUnion = (fn: FnUnion) => (...args: Parameters<FnUnion>) => ReturnType<FnUnion>
type ReturnFnUnion2 = (fn: FnUnion) => FnUnion

const returnFnUnion: ReturnFnUnion = (fn) => (url) => fn(url)
const returnFnUnion2: ReturnFnUnion2 = (fn) => (url) => fn(url)
```

### 🙁 Actual behavior

An error occurs found on the `(url) => fn(url)` part of `returnFnUnion2` on the last line:

```
Type '(url: string) => Promise<void> | (() => Promise<void>)' is not assignable to type 'FnUnion'.
  Type '(url: string) => Promise<void> | (() => Promise<void>)' is not assignable to type 'Fn1'.
    Type 'Promise<void> | (() => Promise<void>)' is not assignable to type 'Promise<void>'.
      Type '() => Promise<void>' is missing the following properties from type 'Promise<void>': then, catch, [Symbol.toStringTag]
```

TS infers a type of `(url: string) => Promise<void> | (() => Promise<void>)`, which is (in my opinion!) equivalent to `FnUnion` -- the signatures and return types match. But TS clearly disagrees :)

### 🙂 Expected behavior

No errors. TypeScript should realize that `FnUnion` is equivalent to the function type it infers because the inferred function matches the signature of `FnUnion` and the inferred return type union is equivalent to the possible return types from `FnUnion`

**Comment by ArkaneMoose** [comment]
> TS infers a type of `(url: string) => Promise<void> | (() => Promise<void>)`, which is (in my opinion!) equivalent to `FnUnion` -- the signatures and return types match.

I don’t think this is true.

If you have a function of type `FnUnion` and call it twice, you are guaranteed to get either `Promise<void>` twice or `() => Promise<void>` twice.

Whereas if you have a function of type `(url: string) => Promise<void> | (() => Promise<void>)` and call it twice, you could get `Promise<void>` once and `() => Promise<void>` another time.

**Comment by ericbiewener** [comment]
Ah, good point, I agree! However, should this work with generics? In my original typing for `ReturnFnUnion2`, I can see that it isn't telling TS that the version of FnUnion that is provided as the argument to the outer function is that version that will be returned. But I'd expect that to work with generics:

```ts
type ReturnFnUnion3 = <F extends FnUnion>(fn: F) => F
const returnFnUnion3: ReturnFnUnion3 = (fn) => (url) => fn(url)
```

This produces the same error. [Playground link](https://www.typescriptlang.org/play?ts=4.3.2#code/C4TwDgpgBAYgdgRigXigCgK4CcA2AuKAZ2CwEs4BzAShQD4oAFLAewFtTCIAeAN2dIAmtAFChIsOACYU6bPiIly1OuhrJ6TNh259BIsdHgBVOKWZwZ8JAB8Jk4cIEQAxjgCGWaADMMcZ8DMLL2ZmNAAPAmNTcyoCXQFHF3dPKGdzYigvREjERNcPaDS4DKzJHPthYNCshCpKkLRSuqq0NDUNFnZOADpPQmYcHgg2utFwaAAlCGBsOCjAmUa4HJNA9vRuzY8KQgIGDzdWaYgsQi5581p1qZmsOAAVcfO4Vcux8RvZi6lFrJXouDrb7vSbTL4vAEAZhk5ygEDCwAgcAEhAkrzgtCWkSBDiKGU8tzmEMCBE+d2+v0BKkwuHWWRpODqeOAUAJ4PRZSgZKJHMp6wZdLgAuEzNZYPJxPMkNJ4p5UL51LkgoFQA).

**Comment by RyanCavanaugh** [comment]
The generic version isn't sound either - in general you can't take unsafe code and make it safe by lifting out a parameter type into a type parameter constraint.
