### ISSUE TITLE
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53633

### ISSUE THREAD

**Issue by icecream17** [microsoft/TypeScript#44451]
<s>__I'm super tired of debugging today.<sup>Feel like I have the most complicated bugs in the world</sup>\
I'll update this later.<sup>Sorry</sup>__

(See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53633#issuecomment-855162984 for now)</s>

# Bug Report

### 🔎 Search Terms

intersection
pick / setState

This issue is similar: https://github.com/microsoft/TypeScript/issues/44315
I found this: https://github.com/microsoft/TypeScript/issues/28080 but it's different since the first line in the code below seems to work. But the issue code doesn't work? Weird.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground Link with code below](https://www.typescriptlang.org/play?#code/LAKA9GAEBKCmCGBjALpAzrZBlZ9m0gAt4A7AEwBtYAnSASzUmQE8AHWMyCugawOUIMAXKABmAVxIo6AexLpMOPLAA8S-ABpIABWozWaLQGlIsAB75yjPsxmjI62AD5IAClCRP6XPiGQPXoGurqzUsABujn5w8GRyFMxqPs5aofpo0QhxJAkquulOAJSQALwurtp0iDxJysYuAD4OyZBNJOIUFIWFAYFNFVU1jvWtzcqj7Z2FGr2QiPCdAEZIPAD8fq7FZZDhMnRkoMUA3gC+oKAs7JAAKoJojqWQR5Dwfu0Atos0Wotv4p80SBnECgDDYZKuZ6vSAAdiBxQgkBkPFBighm1K5ShfjhJ26kERyNR4OUwVCESiNzuji2LgAsnhCAA6aikOLvDEuAAMTIArJBVpByZEWn5TgioESQGDHGSwiLlH5bgwaZjIAyBCy2TIOcVuXyBUL5Q8xS8cfCCVAaHpqKAgA)

### 💻 Code

```ts
// React setState handler is typed like this:
function setState<State, Props, K extends keyof State> (
    state: 
        ((prevState: Readonly<State>, props: Readonly<Props>) => (Pick<State, K> | State | null))
      | (Pick<State, K> | State | null),
    callback?: () => void
) {}

type ThisState = { a: number, b: number }

setState({ a: 7 }) // ok
setState(() => ({ a: 7 })) // ok
setState((prevState: ThisState) => Math.random() > 0.5 ? prevState : {}) // ok
setState((prevState: ThisState) => Math.random() > 0.5 ? prevState : { a: 7 }) // error
```

### 🙁 Actual behavior
The last call has an error

### 🙂 Expected behavior
No error

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

**Comment by icecream17** [comment]
screenshot
____
![image](https://user-images.githubusercontent.com/58114641/120930129-ada95980-c6b1-11eb-93ea-6826a9cb1492.png)
____

I didn't forget, I just procrastinated. It's now filled out

**Comment by RyanCavanaugh** [comment]
Everything here is proceeding according to the declaration of the function. I don't see any defect being demonstrated here.

**Comment by icecream17** [comment]
If `{ a: 7 }` works and `prevState | {}` works then why not `prevState | { a: 7 }`?

**Comment by icecream17** [comment]
Wait, no one responded to my question
