### ISSUE TITLE
Override keyword on properties is being emitted in ESNext output

### ISSUE THREAD

**Issue by arciisine** [microsoft/TypeScript#44455]
# Bug Report

### 🔎 Search Terms

`override` `esnext` `emit` `output`

### 🕗 Version & Regression Information

- This is new behavior introduced in the 4.3 release

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&useDefineForClassFields=true&alwaysStrict=false&emitDecoratorMetadata=false&target=99&module=1&noImplicitOverride=false&strict=true#code/KYDwDg9gTgLgBAYwDYEMDOa4GVhQG4CWCwAkgHYAWuB8A3gFBxwoDmwcAvHAMwAMA3PQC+9eqEixEqDNlyFi5KlBoAmOKBjAyAE0w58RUpWp1GcCHlzLt7Vuy7cAjIJFA)

### 💻 Code

```ts
export class ServiceInherit {
  age = 30;
}

export class ServiceInherit2 extends ServiceInherit {
  override age = 31;
}
```

### 🙁 Actual behavior

Output is currently being produced with the `override` keyword, when targetting `ESNext` as the language target.

#### Common JS Output
```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServiceInherit2 = exports.ServiceInherit = void 0;
class ServiceInherit {
    age = 30;
}
exports.ServiceInherit = ServiceInherit;
class ServiceInherit2 extends ServiceInherit {
    override age = 31;
}
exports.ServiceInherit2 = ServiceInherit2;
```

#### ESNext Module Ouptut
```ts
export class ServiceInherit {
    age = 30;
}
export class ServiceInherit2 extends ServiceInherit {
    override age = 31;
}
```

### 🙂 Expected behavior
The output should not include non-standard keywords like `override`.

**Comment by MartinJohns** [comment]
What version are you using? You didn't provide it in the issue template. It's been fixed in 4.3.3: #44273

**Comment by arciisine** [comment]
The playground link is for 4.3.2, I didn't realize 4.3.3 had already been released, but great to hear this is already fixed.

**Comment by arciisine** [comment]
So not released yet, but soon.  Closing this as a duplicate of #44273
