### ISSUE TITLE
Auto import show import from 'node_module/..'

### ISSUE THREAD

**Issue by lioaslan** [microsoft/TypeScript#44463]
# Bug Report

### 🔎 Search Terms
`auto import node_module`

### 🕗 Version & Regression Information
- Firstly, I know there is another issue about this at #23230. However, I tried all solutions recommended like updating `typescript` to the newest version or attempting with `typescript@next` but it didn't work
- Version of dependencies
```
typescript: 4.3.2 (I install this global)
antd: 4.16.1 (for test)
```

### 💻 Code
* `jsconfig.json`
```json

{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es6",
    "module":"es6"
  }
}
```
* `index.js`
![image](https://user-images.githubusercontent.com/24852182/120929778-99e30f00-c714-11eb-848f-f77397d9175b.png)

### 🙁 Actual behavior

Like the image

### 🙂 Expected behavior

Auto import from 'antd' instead

**Comment by andrewbranch** [comment]
@lioaslan you need `moduleResolution: "node"` in your jsconfig.json. It defaults to `"classic"` unless `module` is `"commonjs"`. I’m following up on why that is, but whether or not it really makes sense, I doubt it’s something we’ll be able to change for back compat reasons.

**Comment by lioaslan** [comment]
Thanks, it worked. It seems to happen with some libraries.

**Comment by andrewbranch** [comment]
You can follow #11434 if you like.
