### ISSUE TITLE
Parse error on type assertion with contextual keyword in parentheses (override as Type)

### ISSUE THREAD

**Issue by zxbodya** [microsoft/TypeScript#44466]
# Bug Report

### 🔎 Search Terms

typecast, parentheses, override

### 🕗 Version & Regression Information

Started to see the issue after updating from TypeScript 4.2 to 4.3, initially noticing this when running prettier after updating it https://github.com/prettier/prettier/issues/11018

It also is happening in current 'Nightly' version in the playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/MYewdgzgLgBCBuBTATsglgE0TAvDA3gL4DcAUKJLAEa4wAUCK6WMAhhG2AJ4CUZQA)

### 💻 Code

```ts
const override = {};
const b = (override as any);
```

### 🙁 Actual behavior

Code results in a syntax error.

However it works fine when renaming variable `override` to something else.

### 🙂 Expected behavior

Code above should work

**Comment by ShuiRuTian** [comment]
The reason is `override` become a new keyword. This is something like you could not name the variable to `public`, `function`, `const`.... 
Because when scanning, tokenlizer would scan this word as `XXXKeyword` rather than `Identifier`.
So, this is a breaking change, rather than a bug?

**Comment by virtulis** [comment]
Just hit the same problem in my existing code. The problem occurs specifically when casting a variable named `override` - TS has no problem with this name in any other context, so that definitely doesn't look intended to me.

**Comment by DanielRosenwasser** [comment]
@ShuiRuTian `override` is a contextual keyword, and TypeScript needs to support valid uses of it in JS.

From my comment at https://github.com/microsoft/TypeScript/issues/44996#issuecomment-878735155

> Ugh - the same is true of (at least) `readonly`, `declare`, and `abstract`.

**Comment by ShuiRuTian** [comment]
@DanielRosenwasser interesting, if so , I want to have a try to fix this issue.

**Comment by DanielRosenwasser** [comment]
Go for it, though I don't know what precisely to do here.

Maybe when parsing a parameter for anything other than a `constructor` declaration, a keyword that isn't reserved in JS (such as `override`, `readonly`, `declare`, and `abstract`) should be re-scanned as a plain `Identifier`.
