### ISSUE TITLE
Types forgetting key information for infinite keys

### ISSUE THREAD

**Issue by GuiltyDolphin** [microsoft/TypeScript#44478]
# Bug Report

### 🔎 Search Terms

- `key number string`
- `type key loses`
- etc. (I found this hard to search for, please let me know if there's another issues regarding this)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ index but couldn't see any relevant entries, let me know if there are!

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/C4TwDgpgBA0hIEkDOAxAlgOzcaBeKA3gFBSlQDaA1lJlAAxQA+UAjE1AEwC6AXFJUQC+RIqEix4yAHIBXALZR8xMhWq0M8gEYQATr35CRAeiM0AZhMSpM2CORb62wABYQMUF2iRQA7mgA2-lDaHjoyEEQAxgD2GEjA-JLWWDgAKhDxfHBW6Cl2DlAQAB44GAAm3mwA-KHhUHxmAIb+SHi1EADcRCbmltLy9o4eru6e3n6BwdDAYRAANMEyCWM03o2RwDLN-iBQTS3zU5GNMq007tn9cgs+0I060P7RSJgA5udm0TpyjcBosVBGppoktfM5flAAAaUSGrKKxeKJKyyOTpTJ9JAowaFEpuCqsKA1GZ1BrNM74YmdYymF5yAL3HYLEAgqDHdxlaLDLy+bDOKDxHRvJCicDQS7JWwAZRmikIJDIVHOUAA5HRlexlSx1cxlRxlfoBMIReJxdKdLLlAq1O4BW8DYZ4XEEpQkrkpTM0cAsq6bDgzeRNfqcaV8YHCe16nsyW1KV0Yk6kcgzZ7vVZ-YGuMG8d4w0TZpH9uT2l0gA)

### 💻 Code

```ts
type KeyIsFinite = {
    [k in 0 | 1 | 2]: k
}

type KeyIsNum = {
    [k in number]: k
}

// if KeyIsFinite[1]: 1 then this will be true
const keyIsFiniteTest: KeyIsFinite[1] extends 1 ? true : false = true;
// if KeyIsNum[1]: 1 then this will be true, but this is actually false, because in KeyIsNum, we are losing information about what `k` is
const keyIsNumTest: KeyIsNum[1] extends 1 ? true : false = true;

// similarly, you can do this with strings
type KeyIsFiniteStr = {
    [k in '0' | '1' | '2']: k
}

type KeyIsStr = {
    [k in string]: k
}

const keyIsFiniteStrTest: KeyIsFiniteStr['1'] extends '1' ? true : false = true;
const keyIsStrTest: KeyIsStr['1'] extends '1' ? true : false = true;
```

### 🙁 Actual behavior

We see a type error informing us that `keyIsNumTest` has type `false` but is the value `true`, this is because `KeyIsNum` is not preserving information about `k` (I assume), and thus is saying that `KeyIsNum[1] = number` rather than `KeyIsNum[1] = 1`. We see that `KeyIsFinite[1] = 1`, so this appears to be an inconsistency.

### 🙂 Expected behavior

I would expect `KeyIsNum` to behave like `KeyIsFinite` and thus for `KeyIsNum[1] = 1` rather than `KeyIsNum[1] = number`

**Comment by jcalz** [comment]
Duplicate of #22509

**Comment by RyanCavanaugh** [comment]
Strong duplicate energy but really just working as intended: mapped types over finite types produce object types with properties, but mapped types over infinite types produce index signatures. Different input different output.

**Comment by GuiltyDolphin** [comment]
@jcalz Yep, I think with "Here I expect string to behave as if it were the union of all possible string literal types." in #22509 this is likely a duplicate. I'd like to just promote that it'd be good for this to work for things like numbers too, but I'll close this in favour of that issue. Thanks!
