### ISSUE TITLE
k + k results in an error where k is bigint | number

### ISSUE THREAD

**Issue by akihikodaki** [microsoft/TypeScript#44473]
# Suggestion

## 🔍 Search Terms

bigint | number, union

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```TypeScript
declare let k: bigint | number;
k + k;
```

TypeScript v4.3.2 says "Operator '+' cannot be applied to types 'number | bigint' and 'number | bigint'.(2365)". Can TypeScript have a means to write a generic formula which can be applied to both of `number` and `bigint`? I suspect there are already proposals to resolve this kind of issue of union but I couldn't find one.

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEEQBd4GsBc8BGBLA5rgHaoA+8RArgLbYgwDcAUGvANTrNA

## 📃 Motivating Example

Try to write a function which implements euclidean algorithm or other mathematical formulae which accepts both of `bigint` and `number`.

## 💻 Use Cases

This kind of problem happens everywhere when writing a mathematical algorithm. A workaround is to use `any`, and then do type assertion.

```TypeScript
declare let k: bigint | number;
const l: any = k;
(l + l) as bigint | number;
```

**Comment by MartinJohns** [comment]
Related: #39569

As soon as you have more than one variable you run into type issues.

**Comment by RyanCavanaugh** [comment]
The only time this *should* be allowed is when both operands are exactly the same utterance -- if you have
```ts
declare let k: bigint | number, j: bigint | number
k + j;
```
then this is unsafe and should be prohibited, since it could be `k = 4, j = 4n`.

Fixing only the same-utterance case doesn't get you very far, though, since presumably your formula is more complicated than that and has other expressions involved, so isn't really worth carving out a special case for.

**Comment by akihikodaki** [comment]
@RyanCavanaugh

I used `+` operator as an example just for convenience. What really is worth here is a construct which asserts several operands of an operator have the same type. For example,

```TypeScript
// bigint XOR number. It's like union but asserts both of a and b has the same type.
function gcd<T extends bigint ^ number>(a: T, b: T) {
  // implementation
}
```

If such a construct is possible, `+` operator can use the construct to allow `k + k` and also allow to write user-defined functions (which can implement various kind of mathematical formulae).

**Comment by MartinJohns** [comment]
> // bigint XOR number. It's like union but asserts both of a and b has the same type.

This is tracked by #27808.

**Comment by akihikodaki** [comment]
> > // bigint XOR number. It's like union but asserts both of a and b has the same type.
> 
> This is tracked by #27808.

Thanks, that is what I wanted to know.
