### ISSUE TITLE
JSDoc auto-fill only works on functions

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4447]
Currently JSDoc auto-fill for comment scaffolding seems to only work for functions.  This should also work for other forms like classes, methods, namespaces, etc

--------------

*Edit by @DanielRosenwasser*
Adapted from list below:

- [x] methods
- [x] classes
- [x] class constructors
- [x] namespaces
- [x] variables
- [ ] property assignments
- [ ] property declarations
- [ ] computed properties
- [ ] enums
- [ ] enum members
- [ ] index signatures
- [ ] interfaces
- [ ] type aliases
- [ ] IIFEs?
- [ ] parenthesized expressions

**Comment by zhengbli** [comment]
There are a list of elements that the JsDoc scaffolding should be enabled on:
- [ ] methods
- [ ] classes
- [ ] class constructors
- [ ] namespaces
- [ ] variables

**Comment by weswigham** [comment]
I think it would also be useful to be able to have them enabled at the marker here (so on parenthesized expressions):
```ts
var x = /**/ (y);
```

because in closure compiler you do inline casts with jsdoc comments like so:
```ts
var x = /** @type {Foo.Bar} */ (y);
```

VSCode's jsdoc insertion does this already.

**Comment by DanielRosenwasser** [comment]
Why exactly is that useful?

**Comment by DanielRosenwasser** [comment]
@weswigham fair point, added

**Comment by yuit** [comment]
It will be pretty nifty to add :
* type annotation in to @param and @returns when available
* dive into binding element and grab the parameter name from the inside

**Comment by DanielRosenwasser** [comment]
I think that should be part of a separate issue @yuit. Also, I wonder the utility of the type annotations since in TypeScript you already have type annotations.

**Comment by mhegazy** [comment]
the main ones outlined here were fixed. please file other issues if the other ones are still needed.
