### ISSUE TITLE
Union type not correctly narrowing down

### ISSUE THREAD

**Issue by danielbartsch** [microsoft/TypeScript#44479]
# Bug Report

### 🔎 Search Terms

union narrowing wrong

### 🕗 Version & Regression Information

in 3.7.5. still there in 4.3.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "bugs that aren't bugs"
- I was unable to test this on prior versions because prior versions don't support `??`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeUCGAuKA7ArgWwCMIAnAGigMwGdhiBLLAcygF8BtAXQChRIoAhBMjSZchEq05cuAEwgBjADapi0AG4qo8zHAA+AqPpxY5AMwYQZAbmnyA9lhpQZQ+VAD87qJxtcA9H7OUHRU2HYA7lAAVjhO-OQEOMBQVAAWdjiKLkSwhgJAA)

### 💻 Code

```ts
type A = { a: number, b: string }[]
type B = { a: number }[]

declare var c: A | B | undefined;

const d = c ?? []

// d is now just B, but should be A | B
```

### 🙁 Actual behavior

Type inference excludes a part in the intersection type.

### 🙂 Expected behavior

Type inference should just exclude `undefined`, because the `??` operator was used on the variable.

**Comment by fatcerberus** [comment]
That's a *union* type, not an intersection.

**Comment by danielbartsch** [comment]
whoops. You're right. With that correction, I was able to find related issues:
https://github.com/microsoft/TypeScript/issues/44401
https://github.com/microsoft/TypeScript/issues/43825
https://github.com/microsoft/TypeScript/issues/43667

which are almost the same, but not quite.

**Comment by MartinJohns** [comment]
See: https://github.com/microsoft/TypeScript/issues/32237#issuecomment-508184790
