### ISSUE TITLE
confuse comment emit when const multi enum has same key

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#44477]
# Bug Report

### 🔎 Search Terms

- const enum 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM72MgrgWzgUWxwGkBLZAE1QCgBvagSABFSAzV-C0+AXjgHJ8-ADSMW7AHLAA7nD78JIsW1ZNgAG2AxgFOQKZLmKgIJQoAQwCee-saUBfatVCRYiFOjiZcBImUqoAEx0yuyc3DZCokaSMjaK0eKqGlo6NgaJJmZWNnaijtRIaPAAbubqpBT+VHoA2oS41agAdElS0sK+jeRUga0q7QC6cOao7sUA3EA

### 💻 Code

```ts
export const enum EnumKinds
{
	DiffEdit = 'E',
	DiffNew = 'N',
	DiffDeleted = 'D',
	DiffArray = 'A',
}

export const enum EnumKinds2
{
	DiffEdit = 'E',
	DiffNew = 'N',
	DiffDeleted = 'D',
	DiffArray = 'A',
}

const validKinds = [EnumKinds.DiffNew, EnumKinds2.DiffNew] as const;
```

### 🙁 Actual behavior

```ts
const validKinds = ["N" /* DiffNew */, "N" /* DiffNew */];
```

### 🙂 Expected behavior

keep parent name in comment

```ts
const validKinds = ["N" /* EnumKinds.DiffNew */, "N" /* EnumKinds2.DiffNew */];
```

**Comment by a-tarasyuk** [comment]
Do we need to emit a full `path` only to duplicate names?
```ts
export const enum A { A = 'A1' }
export const enum B { A = 'B1' }
const foo = [A.A, B.A] as const;

// .js
const foo = ["A" /* A.A */, "N" /* B.A */];
```

Or full path should be emitted by default 
```ts
export const enum A { A = 'A1' }
const foo = [A.A] as const;

// .js
const foo = ["A" /* A.A */];
```

/cc @RyanCavanaugh @DanielRosenwasser

**Comment by bluelovers** [comment]
> Or full path should be emitted by default

i like this

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Is it acceptable to emit a full path by default? Are there any cases where TS should only return names?

/cc @DanielRosenwasser

**Comment by RyanCavanaugh** [comment]
The comments are only intended for human consumption, so anything that reads well to a human is fine
