### ISSUE TITLE
Npm i -g typescript error

### ISSUE THREAD

**Issue by Rafae1CM** [microsoft/TypeScript#44486]
npm ERR! code EEXIST
npm ERR! path C:\Users\anara\AppData\Roaming\npm\node_modules\typescript\bin\tsc
npm ERR! dest C:\Users\anara\AppData\Roaming\npm\tsc
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\anara\AppData\Roaming\npm\node_modules\typescript\bin\tsc' -> 'C:\Users\anara\AppData\Roaming\npm\tsc'
npm ERR! File exists: C:\Users\anara\AppData\Roaming\npm\tsc
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anara\AppData\Roaming\npm-cache\_logs\2021-06-07T16_17_10_340Z-debug.log

**Comment by IllusionMH** [comment]
It's issue with npm itself, not with typescript package.

Probable `tsc` already exists and can't be removed because it's in use.
