### ISSUE TITLE
The type is not inferred.

### ISSUE THREAD

**Issue by riya81** [microsoft/TypeScript#44502]
# Bug Report

### 🕗 Version & Regression Information

Version 4.2.4

### 💻 Code

```ts
interface TOKENTYPE {
    '+'?: string;
    '-'?: string;
    '*'?: string;
    '%'?: string;
}
const get_token = ({
    TOKEN = {
        '+': 'PLUS',
        '-': 'MINUS',
        '*': 'TIMES',
        '%': 'DIVIDED_BY',
    },
}: {
    TOKEN?: TOKENTYPE;
}) => TOKEN;
const text = '1+2';
const token = get_token({});
const code = text.split(/(\+|\-|\*|\%)/);
for (const i in code) {
    if (code[i] in token) {
        code[i] = token[code[i]];
    }
}
```

### 🙁 Actual behavior

"if in" can establish that the array has the key of the object, but I get an error.

### 🙂 Expected behavior

I'm hoping the type can be deduced.

**Comment by RyanCavanaugh** [comment]
There are at least five separate steps I see here which are either unsound to take as assumptions, or outside the scope of the sort of inference we're capable/willing to make.
