### ISSUE TITLE
Cannot Resolve Upstream Dependency Error

### ISSUE THREAD

**Issue by md56n** [microsoft/TypeScript#44506]
# Bug Report

I'm trying to run this project but I'm getting upstream dependency errors. I've tried downgrading typescript and bypassing the error using --legacy-peer-deps and --force but that doesn't work.

### 🔎 Search Terms

upstream dependency conflict  react native
upstream dependency conflict jest
upstream dependency conflict typescript
upstream dependency conflict
jest looking for outdated typescript
npm peer typescript from ts-jest upstream dependency conflicttypescript jest dependency
npm peer typescript@"2.x" from ts-jest upstream dependency conflict
npm peer typescript@"2.x" from ts-jest@22.4.6 upstream dependency conflict
npm peer typescript@"2.x" from ts-jest@22.4.6
Could not resolve dependency: peer typescript@"2.x" from ts-jest@22.4.6

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I didn't have this project yet

### 💻 Code

tsconfig.json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "noImplicitAny": true,
    "noEmit": true,
    "outDir": "./dist/",
    "module": "es2015",
    "target": "es2015",
    "jsx": "react-native",
    "lib": ["esnext", "dom"],
    "baseUrl": "./",
    "paths": {
      "~/*": ["src/*"],
      "shared/*": ["shared/*"]
    }
  },
  "exclude": ["node_modules", "node_modules/**"],
  "include": ["./src/**/*"]
},
"resolutions": {
    "@types/react-native": "0.55.28"
},
"jest": {
    "preset": "jest-expo",
    "transform": {
      "^.+\\.jsx?$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.tsx?$": "<rootDir>/td/ts-jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|react-clone-referenced-element|expo(nent)?|@expo(nent)?/.*|react-navigation|native-base-shoutem-theme))"
    ],
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "android.ts",
      "android.tsx"
    ],
    "setupFiles": [
      "./jestSetup.js"
    ],
    "globals": {
      "ts-jest": {
        "useBabelrc": true
      }
    }
  }

package.json
"devDependencies": {
    "@types/chai": "^4.1.3",
    "@types/expo": "^30.0.0",
    "@types/jest": "^22.1.2",
    "@types/lodash": "^4.14.96",
    "@types/mocha": "^5.2.0",
    "@types/prop-types": "^15.5.2",
    "@types/react": "~16.7.0",
    "@types/react-navigation": "^2.0.23",
    "@types/react-redux": "^6.0.9",
    "@types/reselect": "^2.2.0",
    "@types/uuid": "^3.4.3",
    "@types/webdriverio": "^4.10.3",
    "@types/yup": "^0.24.0",
    "jest": "^22.3.0",
    "jest-expo": "^31.0.0",
    "ts-jest": "^22.0.4",
    "ts-loader": "^4.4.2",
    "ts-node": "^6.0.2",
    "tslib": "^1.9.3",
    "typescript": "^3.1.6"
}

### 🙁 Actual behavior

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app-mobile@0.0.1
npm ERR! Found: typescript@3.9.9
npm ERR! node_modules/typescript
npm ERR! dev typescript@"^3.1.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"2.x" from ts-jest@22.4.6
npm ERR! node_modules/ts-jest
npm ERR! dev ts-jest@"^22.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### 🙂 Expected behavior

I'm just trying to run the project.

**Comment by IllusionMH** [comment]
It's not related to TS package.

You have old `ts-jest` version that requires old TS version in it's peer dependencies. You should update your dependencies to version that expect your TS version.
