### ISSUE TITLE
Type inference in generic function-parameter types

### ISSUE THREAD

**Issue by wearebear80** [microsoft/TypeScript#44507]
# Bug Report

### 🔎 Search Terms

inference generic function-parameter extends return type arrow function

### 🕗 Version & Regression Information

4.1.3

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVzVYAQxmAFkIATYAGwB4BlAGjgEE5QSUKBnOACm4AuOEzhgA-MMIoAngEo4AXgB8I5XwDeAKDi64AW0o1GOvYQzYU3EwF9h2vQaPVhTU7vNYcQ1lpsKHPQIYJChcQMcnKmoTSI8Lb3c4Gz8tLRgZMGA4ABVyaKU4CLgUQn1gYW4YKEwUAHMkzG4WCwA3CrgAIwgIaiIUVK00b3hDaOE850Li0vLhAHJ52L0mlqx24QRCam5gQeGreAAlQvwiEnyaTSSxmmFbmKTPSx8+B+YwBRV+YscAOgB7ySjnKMEIwjAy10-lsciAA)

### 💻 Code

```ts

 // - here A extends (s: S, p?: any) => S - we want to return our "model" type  as result 
export function createModel<S, A extends (s: S, p?: any) => S>({ 
    model,
    actions,
}: {
    model: S,
    actions: A
}) {
    return {
       model,
       actions
    }
}

type TModel = {
    name: string
    isActive: boolean
}

const model: TModel = {
    name: '',
    isActive: false
}

const R = createModel({
    model: model,
    actions: (model, p) => ({ // - model is TModel model here and its what i expect.
        ...model,
        meta: p,  // - here i return invalid model field, and haven't error, i expect TypeError
    }),
})



// if i delete spread,  it's works  - i have TypeError
const R = createModel({
    model: model,
    actions: (model, p) => ({ // - Type '{ meta: any; }' is missing the following properties from type 'TModel': name, isActive
        meta: p, 
    }),
})




// if try to return primitive (for example - number), it's works  - i have TypeError
export function createModel<S, A extends (s: S, p?: any) => number>({  ......

const R = createModel({
    model: model,
    actions: (model, p) => ({ // - Type '{ meta: any; name: string; isActive: boolean; }' is not assignable to type 'number'.
        ...model,
        meta: p, 
    }),
})
```      

### 🙁 Actual behavior

In "action" function  i have types this function return, and this does not depend on the types specified in createModel.

### 🙂 Expected behavior

In "action" function  i have return type what i define in generic of createModel function.

Comment: maybe it's not a bug, and i just don't know something about typescript inference

**Comment by RyanCavanaugh** [comment]
I don't see any bug demonstrated here; this is normal inference results. A shorter example with a clearer explanation of why you expected / didn't expect an error would be useful. Excess properties are not *always* disallowed so the allowing of `meta` there is expected.

**Comment by wearebear80** [comment]
As i said before i just don't knew something about typescript

Here is the the solution - https://stackoverflow.com/questions/67889090/type-inference-in-generic-function-parameter-types

I close issue
