### ISSUE TITLE
Investigate the use of `readConfigFile()` and friends

### ISSUE THREAD

**Issue by RA80533** [microsoft/TypeScript#44516]
- Its documentation states that it reads tsconfig.json files
- It appears to have the same functionality and level of abstraction as [`readJsonConfigFile()`](https://github.com/microsoft/TypeScript/blob/147d7211367d9f576bb227a2c40004901c5521b6/src/compiler/commandLineParser.ts#L1679-L1686)
- The function is not marked with `/* internal */` despite it lacking consumer-level documentation

https://github.com/microsoft/TypeScript/blob/147d7211367d9f576bb227a2c40004901c5521b6/src/compiler/commandLineParser.ts#L1657-L1664

- In at least one area, it's used in a manner contradictory of its own documentation (see `PackageJson`)

https://github.com/microsoft/TypeScript/blob/147d7211367d9f576bb227a2c40004901c5521b6/src/jsTyping/jsTyping.ts#L210

- The related [`parseJsonConfigFileContent()`](https://github.com/microsoft/TypeScript/blob/147d7211367d9f576bb227a2c40004901c5521b6/src/compiler/commandLineParser.ts#L2416-L2425) appears to only be used for testing but is not marked as internal

**Comment by RyanCavanaugh** [comment]
This is more of a set of observations than a bug report. Since these are now public APIs, I'm not sure what you'd like to see happen here -- at best, we could break some consumers. The documentation comments could be a bit better but the same is true of every comment 😉

**Comment by RA80533** [comment]
This is certainly more of an observation than anything. I suppose the goal of this was to have a clear understanding of that area in order to update the documentation accordingly.
