### ISSUE TITLE
Error reporting for intersection types seems to not find near miss

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4451]
In the following example:

```TypeScript
var z: { a: number; b: string } | { c: number } = { a: 3 };
```

...we currently give a very confusing error message.  

Type '{ a: number; }' is not assignable to type '{ a: number; b: string; } | { c: number; }'.
  Type '{ a: number; }' is not assignable to type '{ c: number; }'.
    Property 'c' is missing in type '{ a: number; }'.

I can see why we might have gotten to this point (failing until we're at the last type, and giving the message based on that), but we've actually gone down arguably the "wrong path" of the intersection.  Ideally, we would error on the "closest" match.  This would at least give the user a chance of understanding where to address the issue.

The problem with the way we currently report errors will compound as types get larger.

**Comment by danquirk** [comment]
I'm not sure whether we could meaningfully generate the 'closest' match in the general case. Perhaps you'd have been satisfied by the more specific error being reported from both sides of the union:
```
Type '{ a: number; }' is not assignable to type '{ a: number; b: string; } | { c: number; }':
    1. Type '{ a: number; }' is not assignable to type '{ a: number; b: string }'
        Property 'b' is missing in type '{ a: number; }'
    2. Type '{ a: number; }' is not assignable to type '{ c: number; }'.
        Property 'c' is missing in type '{ a: number; }'.
```
This could get unwieldy for larger target types (or source types) but at least in the editor you could imagine a more interactive error reporting control that would allow you to control the verbosity (ex imagine the 2nd line of each numbered bullet was collapsed by default but could be expanded)

**Comment by ahejlsberg** [comment]
We currently report errors based on the last constituent type of a union type. As Dan suggests, we could possibly report errors from all of the constituents, but in my opinion that would just add to the noise. We could explore finding a "closest" matching constituent to report errors from, but I'm not sure we'd ever be able to devise a meaningful algorithm for finding such a thing.

**Comment by mhegazy** [comment]
As @danquirk and @ahejlsberg mentioned, i do not see what can be done here to make the situation better. closing. please reopen if you have a proposal for fixing this.
