### ISSUE TITLE
Generic types can't have some types inferred if they are derived from another generic which doesn't necessarily use them.

### ISSUE THREAD

**Issue by SephReed** [microsoft/TypeScript#44525]
# Bug Report

### 🔎 Search Terms

Generics, infer, derived, unused, doesn't work

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=15&ssc=40&pln=1&pc=1#code/C4TwDgpgBAggPAFQDRQJooFoD4oF4oAUAlHjsAE4CuEA3FFAPQNTAAWAlgM5QAmA9hG4A7PsCgB3PuQDWAKCYtw0eMjSYc+YqSgI6jZmy4Sp0zrNmhIUAJJCAZhHII41jTagQAHsAhCe3eHZ7Rx0UAEMhEHDInAB+HSgALighCAA3RxpzBUsIPjtednIIAGNgWwdyKCMAIgpqGtkAGwgxHiLS8uDyZIrHZ3h6iBQhSiamkbGmrCw6HI5uSRluCHY2EPEwkHMLJSgAIUQ3FUnx0+mskr4hTjEfW+TDobctXDIqWmyDJXzqvw6yn0qrVKNIROIhI0FJxWHwxjwoAAjaC-XJQOofGrRBFrYzLaoFEBwqCUIRXAC25N8d1Y0CaQWgYURfAyzVaf3axUB3V63WcuVRgmAs1kQA)

### 💻 Code

```ts
type A<T, Y, Z> = () => true;  // this does not work
// type A<T, Y, Z> = () => T;  // this works

type InferT<I> = I extends A<infer T, any, any> ? T : never;

// typeof directInfer is "true"
let directInfer: InferT<A<true, null, null>>; // this works either way


type B<T> = A<T, null, null>;
const test: B<true> = () => true;

// typeof indirectInfer is "uknown"
// should be of type "true", and it works if you uncomment the line above
let indirectInfer: InferT<typeof test>;
```

### 🙁 Actual behavior

- If you make a generic `A` which does not necessarily use all of its arguments, then instantiate a variable of that type, you can still use `infer` to pull out every generic argument from it.

- If you then make a new generic `B` which is a version of `A` with some fields pre-filled, then use the same inference function as for `A`, it will no longer work on generic arguments which are not used in `A`.

- If you then change `A` to use all of its generic arguments, inferring from `B` will now work. 

### 🙂 Expected behavior

It shouldn't matter whether or not the base generic `A` uses a generic field.  If it can be inferred one way, it should be able to be inferred either way.

**Comment by jcalz** [comment]
This is working as intended; see [this FAQ entry](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--).  TypeScript's type system is structural and not nominal; if a type doesn't depend structurally on `T`, then in principle you can't infer `T` from it.   (In practice, sometimes the compiler *can* do this, but it really shouldn't be relied upon).

**Comment by SephReed** [comment]
Ah.  I suppose that makes sense.  Luckily I found a way of getting around my issue so I guess I'll close this.
