### ISSUE TITLE
Unconstrained generic type is assignable to "empty object" type

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#44520]
# Bug Report

### 🔎 Search Terms

unconstrained generic curly brace object type

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries -- looking for `{}` and `Object`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=2&ts=4.3.2&ssl=19&ssc=2&pln=16&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXyjDBAAcMBnAYWRggE8AKWAcwC54BvAXwEp2A3HFmABuAFBiA9JPgAVAMrwQMGDhjl4AI3BRk5BAANUyCBHgAfeGlCIsqEMAPwsG1DgwFy5LM1RRNEAgYOPAG3AZihMRkVDT0DMamPOJRpBTUtIzWILb2wMkSKOjYeEgAPLIAfEwwbHI8nGLwBERpsZk1zMnw0vBucorKqjDwgDLknnLOGlBePn4BQSHcYlwSvQByIQpKKmrwDGBqcJhaOnoIslNW6HjkGDBQdg48YogJJhAFb9m5zyLwEkKaEwuHwh1QdweT2AFSUAA8MCBUMANGgANZuADuqGqLHYsgaHCaLWi6TijBY3V62yGag0gFByU5gXT6a4YnDYq5uDwzby+fyBeDBTirVZiIA)

### 💻 Code

```ts
declare function acceptsCurly(arg: {}): void;

// ✅ TS errors because `null | undefined` is not assignable to `{}`
acceptsCurly(null);
acceptsCurly(undefined);

function f<T>(arg: T) {
  acceptsCurly(arg); // no TS error ❌ as T is assignable to {}
}

// No TS error (correct because T is unconstrained)
f(null);
f(undefined);



function constrained<T extends unknown>(arg: T) {
  acceptsCurly(arg); // TS errors ✅ because unknown is not assignable to {}
}
```

### 🙁 Actual behaviour

TS allows assignment of an unconstrained generic to the "empty object type" `{}`.
Which can cause runtime crashes because an unconstrained generic accepts `null | undefined`, but `{}` does not.

### 🙂 Expected behaviour

TS should not allow assignment of an unconstrained generic to the `{}` type because `null | undefined` are not assignable to `{}`.

This can cause safety holes which leads to runtime crashes.
For example - as of the ES2015 lib types the following signature exists: `Object.keys(o: {}): string[]`.

`Object.keys(null)` is correctly a TS error as it crashes at runtime.
But `Object.keys(<<T>>)` will not be a TS error, even though `T` could be null and crash at runtime.

### Extra Notes

If you `extends any` on your generic (as of TS3.9) or `extends unknown`, then it constrains the type of the generic to `unknown` - which then correctly errors.

**Comment by RyanCavanaugh** [comment]
"intended" is a bit of a stretch because we're not super happy about it, but this is the behavior. It's a concession to back-compat because `{ }` was the top type when generics were introduced (predating `null` / `undefined`) and changing it to `unknown` introduces a startlingly high number of unuseful breaks.

**Comment by bradzacher** [comment]
😢  That sucks, but I understand the reasoning.

OOC - is there any plan to eventually rip the bandaid and break this to improve the safety?
Or are the breakages too great to make this change?

**Comment by RyanCavanaugh** [comment]
Never say never, but it's not likely soon. It's bad form these days to write `arg: { }`; usually either `arg: unknown` or `arg: object` is what's intended (or `arg: object | string | number`, or whichever other subset of the current primitives you support) so the problem is moot in the presence of "well-written" code.

**Comment by fatcerberus** [comment]
The inconsistency is interesting: the implied constraint is `{}`, but it's allowed to be instantiated with nullish values that aren't assignable to `{}`.

**Comment by dyst5422** [comment]
@RyanCavanaugh How do I then constrain a function to accept only the empty object?

```typescript
type Something = ????;
function myFunc(args: Something): void {}

myFunc({}) // Ok
myFunc(LITERALLY ANYTHING OTHER THAN {}) // Not Ok
```

The why answer on this one is we have an EDSL in typescript where we'd like to enforce this above as the workarounds change the API from cases where there is some key on the expected arg input

**Comment by RyanCavanaugh** [comment]
Oh hey we fixed the OP (see #49489)

There is not a way to guarantee that the only value passed to a function is the literal `{ }`. I don't understand why you would do that, though -- the function can write `{  }` itself? Why would it need a parameter in that case?

**Comment by dyst5422** [comment]
100% for API consistency so all of our functions in the EDSL receive an object as the only argument.

There is definitely not a _need_ in the language for this, I was just hoping here was some magical combination of `readonly` and `never` or some other type trick to accomplish this.

I suppose what I'm really interested is the _WHY_ behind the difference in extra property checking on an empty interface vs a non-empty interface.

<img width="823" alt="Screen Shot 2022-06-23 at 11 30 38" src="https://user-images.githubusercontent.com/13282627/175369834-8056fc5f-5fc5-49de-8d35-e36f00d6da47.png">

**Comment by RyanCavanaugh** [comment]
People use `{ }` (somewhat incorrectly) as an alias for `object`, so it's allowed. Since a function _requiring_ you to pass exactly `{ }` doesn't really make any sense, it's a reasonable interpretation. Excess property checking is there to catch typos and catching typos against a dictionary of zero words doesn't really make much sense.
