### ISSUE TITLE
Infer return type of function when called with certain arguments not working correctly

### ISSUE THREAD

**Issue by entropitor** [microsoft/TypeScript#44536]
# Bug Report

### 🔎 Search Terms

infer, return type

### 🕗 Version & Regression Information
Happens on all versions available on the playground (no regression)

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.3.2#code/C4TwDgpgBAggJgNwIYDsDGE4CULAK4BOKAKuBADwBQUUACkgUgLa4QEA01UxUEAHsAgo4AZygAKMA2YAuOtJaCCASigBeAHxRUISlrXdeAoaIlTGTOfQusV6rQEsUAMzZQsUAPzuoclBAQ2AG5KSjQAexQRYCgHOCFgB1B1KHIefkFhMQByZ3Dw7KgAHyhsgCMGbI1xYDliVU0oYBDKUEgoADF8lPhkdEwcfCJSSHJyyvYmsnDnWPiURNANIKA

### 💻 Code

```ts
type AdvancedReturnType<
  Parameter,
  T extends (param: Parameter) => any
> = T extends (param: Parameter) => infer R ? R : never;

const identity = <T extends 'foo' | 'bar'>(t: T) => t;

// This should be 'foo' but it is 'foo' | 'bar'
type Foo = AdvancedReturnType<'foo', typeof identity>;
```

### 🙁 Actual behavior

```ts
type Foo = 'foo' | 'bar'
```

### 🙂 Expected behavior

```ts
type Foo = 'foo'
```

While the actual behaviour is "correct" it's not as narrow as it could be and basically doesn't allow us to infer what the return type of a function would be when called with certain arguments

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `infer T` is a structural match on the type and doesn't perform call-like inference.

**Comment by entropitor** [comment]
> This is the intended behavior; infer T is a structural match on the type
I wouldn't expect it to do call-like inference but I'd expect it to behave similar to 

```ts
identity('foo')
```
which does refine correctly. It seems the infer doesn't seem to refine the fact that the T can be less than `'foo' | 'bar'` even though it could

@RyanCavanaugh Is there another way to get this kind of information? Or an open bug / issue that could solve this?

**Comment by RyanCavanaugh** [comment]
> I wouldn't expect it to do call-like inference but I'd expect it to behave similar to [...]

That *is* a call 😉

There isn't a general-purpose way to get the result of what a call to a function with particular arguments would be, no

**Comment by entropitor** [comment]
The reason why i think it is a bug is because it seems to resolve the generic BEFORE doing the structural matching, instead of doing it WHILE the structural matching is happening (like with calls) 

Now:
1. Resolve generics to their bounds namely T = 'foo' | 'bar'
2. Do structural matching => MATCH!
3. infer return type: T (which is 'foo' | 'bar')

Should be IMO:
1. Do structural matching, MATCH if T = 'foo'
2. Infer return type: T (which happens to be 'foo')

I'm not sure this is what you mean with call-like inference, but why shouldn't infer work like this? What could it break?

**Comment by RyanCavanaugh** [comment]
I can see why someone might want either, but as you've noted it's a different behavior. There are two different questions that might be being asked by this conditional type:
 * Does this function take this sort of argument *at all* ? If so, I want its return type
 * Does this function take this sort of argument? If so, I want its return type if I called it that way

Experience has shown that any observable change to the type system is a break.

**Comment by entropitor** [comment]
I guess 

> Does this function take this sort of argument at all ? If so, I want its return type

could have been something like

```ts
type AdvancedReturnType<
  Parameter,
  T extends (...args: any[]) => any
> = T extends (param: Parameter) => any ? ReturnType<T> : never;
```
i.e.

```ts
type AdvancedReturnType<
  Parameter,
  T extends (...args: any[]) => any
> = T extends (param: Parameter) => any ? T extends (...args: any[]) => infer R ? R : never : never;
```
