### ISSUE TITLE
Null check do not work with T[keyof T]

### ISSUE THREAD

**Issue by zhujinxuan** [microsoft/TypeScript#44539]
# Bug Report
It is a type check error: the null check does not apply with type `null | undefined | T[keyof T]`

### 🔎 Search Terms

null check, keyof

### 🕗 Version & Regression Information

I only test it with version 16.10 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0MwAUVWDEQNUgADVHBQGNJ3KAALygABEAAkYNAMOB4GRogLFFTBPB3AExcwABT0xnM9zsyhc9wASmCKhwDQ8ZC8iElzhB7Bo3zcZmY7AYzEg-Fg0HUiS58D0Ii8AoZTJZggFSRxAvADlQAHJhAA5SASAVBFQAeW+ZF2gldWkgx1QjgUrmkeFATgtOlGWH0KAQiBhwiudokkuiIgMHBx3RYbC43CCkMlNGSXFgqAo8C8a1QZB6qAAPDgAHwqjLyAAi+IY+VAKr1fKX3n4BHxGh3tFPmEXS-48UgeAKu7vhlSOD1AG0ALp6nc4UAAb0UEoSjlGhuC3Pk-Q3Lc9wAbiA4DkklXdQNAZ8klSZ9BH3QDgLw9FqRoHQGGgdgUH5E9UA0d9n0-eD8OAxFd2I0iUAAQl5flOCiaBQAAMj40AWLI0AOP5PtIGSDJIG4HCEIYvDwILGj70-SDhMgeiFIAX3k0BdLwpwCTNeEt3g3TFFQFo6Eva9INw4D3zBDI0PvEkcE-AB+X8nLUgAfQYeNAAKJKkzgZPM+CgA)

### 💻 Code
```
function extract<T>(initData: () => T, patch: Patch<T>, keys: (keyof T)[]): T {
    const data = initData();
    for (const key of keys) {
        const value = patch[key];
        if (value !== null && value !== undefined) {
            data[key] = value;
        }
    }
    return data;
}

type Patch<T> = {
    [x in keyof T]?: T[x] | null | undefined;
};
```

### 🙁 Actual behavior

All error occurs as 
> Type 'T[keyof T] | null | undefined' is not assignable to type 'T[keyof T]'.
  Type 'undefined' is not assignable to type 'T[keyof T]'.

### 🙂 Expected behavior
The variable `value` shall be considered as not null nor undefined after the if check.

**Comment by zhujinxuan** [comment]
I tried to replace the for loop with forEach.  The problem still exists.  So I can believe the problem is not a result of for-loop.

**Comment by RyanCavanaugh** [comment]
It's not considered safe to write from property one slot to another since the instantiated type could have more specific types on each slot that render the write unsound. It *is* safe if the key happens to be the same in both sides, but we don't have any way to tell when that is or isn't the case.

**Comment by zhujinxuan** [comment]
```
 It is safe if the key happens to be the same in both sides, but we don't have any way to tell when that is or isn't the case.
```
Would it be able to tell if keys variable is passed to prove the keys exists on both sides with the same value?

And I also find something seemingly inconsistent.  If we use `if` statement for the null check, then it throws an error.  But if we use the `??` as the null check, then the following code works without complain: 
https://www.typescriptlang.org/play?ssl=15&ssc=8&pln=27&pc=1#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0MwAUVWDEQNUgADVHBQGNJ3KAALygABEAAkYNAMOB4GRogLFFTBPB3AExcwABT0xnM9zsyhc9wASmCKhwDQ8ZC8iElzhB7Bo3zcZmY7AYzEg-Fg0HUiS58D0Ii8AoZTJZggFSRxAvADlQAHJhAA5SASAVBFQAeW+ZF2gldWkgx1QjgUrmkeFATgtOlGWH0KAQiBhwiudokkuiIgMHBx3RYbC43CCkMlNGSXFgqAo8C8a1QZB6qAAPDgAHwqjLyAAi+IY+VAKr1fKX3n4BHxGh3tFPmEXS-48UgeAKu7vhlSOD1AG0ALp6nc4UAAb0UEoSjlGhuC3Pk-Q3Lc9wAbiA4DkklXdQNAZ8klSZ9BH3QDgLw9FqRoHQGGgdgUH5E9UA0d9n0-eD8OA8CCxo+9P0g4jSJQAB+Lj4S3Fi8E-BCSgAX2Ess80JLwmIYeCxMUVAWjoS9r0g3DgPfMEMjQ+8SRwT8uN-TS2IAH0GKJoFAMy+0gZIMkgbg5PgoA
```
function extract<T>(initData: () => T, patch: Patch<T>, keys: (keyof T)[]): T {
    const data = initData();
    for (const key of keys) {
        const value = patch[key];
        data[key] = value ?? data[key]
    }
    return data;
}

type Patch<T> = {
    [x in keyof T]?: T[x] | null | undefined;
};

```
