### ISSUE TITLE
Proritize .style.ts file inside component folder

### ISSUE THREAD

**Issue by olegKusov** [microsoft/TypeScript#44533]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [* ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [* ] This wouldn't change the runtime behavior of existing JavaScript code
* [ *] This could be implemented without emitting different JS based on the types of the expressions
* [* ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Proritize .style.ts file inside component folder and use some special color or label for local styled component if there is some simular named styled components in projects (its very common case when user use same naming for styled components among app components)

/Component/index.tsx
/Component/style.ts

Now if we add emotion css styled component to style.ts file inside component folder and then try to import it in component inside index.tsx VS code show us Styled component from another folders (from /Component2/style.ts for example) on top and not from our component folder. Its very annoing. Now I need manualy import styled component ... Thank you!

## 📃 Motivating Example

![image](https://user-images.githubusercontent.com/28058268/121509508-6394e080-c9ef-11eb-9265-0dc30ce55afd.png)

## 💻 Use Cases

With styled components

**Comment by RyanCavanaugh** [comment]
We don't do anything special with framework-specific naming conventions.

**Comment by olegKusov** [comment]
> We don't do anything special with framework-specific naming conventions.

VS Code team send me to Typescript team. And know you saying that it's okay. But it's real problem when I always need manually import styling for my components.
