### ISSUE TITLE
Assert that a property is a value when we have already asserted that the key relates only to that value.

### ISSUE THREAD

**Issue by mildfuzz** [microsoft/TypeScript#44532]
Rubbish title, sorry!! This might be a tricky one to explain. Let me give it a go. 

So I have a utility type that can give me the keys of an object where the value is of certain type:

```typescript
export type KeysOfValueType<T, U> = {
  [K in keyof T]: T[K] extends U ? K : never
}[keyof T]
```

We can use that like this

![image](https://user-images.githubusercontent.com/196705/121494251-78ae4700-c9d0-11eb-90e1-e95b00b64495.png)

Now, if I want to use that to create a function where I pass in an object and a key for a property, I would hope that Typescript will know the type because we have already asserted it:

```typescript
function innerLowerCase<
  T extends Record<string, string | number | Record<string, unknown>>,
>(obj: T, key: KeysOfValueType<T, string>) {
  const objString = obj[key]
  return objString.toLowerCase()
}
```

but Typescript can't assert that objString is a string, so we get the following:

![image](https://user-images.githubusercontent.com/196705/121495023-2a4d7800-c9d1-11eb-9936-6cf90060e995.png)

I can add a Typeguard to make this work (which I what is have done in my actual use case), but it feels like something TS should be able to do?

**Comment by mildfuzz** [comment]
@MartinJohns hey, you downvoted this a few hours ago now, is there a specific issue with it?

**Comment by MartinJohns** [comment]
I just started downvoting all issues that completely ignore the issue template. 🤷🏼‍♂️ This also sounds like a question, which is better suited on platforms like StackOverflow.

**Comment by mildfuzz** [comment]
Okay, knowing that is more helpful. I can look at that.

RE: Yeah, did consider it but I'm not sure it is a question, I feel like it's a thing that TS isn't doing that maybe it should be? I might be wrong.
