### ISSUE TITLE
First Argument in Function.prototype.call should be optional

### ISSUE THREAD

**Issue by jonath92** [microsoft/TypeScript#44530]
### 🕗 Version & Regression Information
Occurs in the latest Version (4.3.2) and nightly version

### 💻 Code
[Function.prototype.call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) combined with [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is a nice way to only call a method if the method is defined (see [this thread](https://stackoverflow.com/a/65082211/11603006)). 
```
foo?.call()
```

### 🙁 Actual behavior

Ts complains: `Expected at least 1 arguments, but got 0`  

### 🙂 Expected behavior

I expect that this works as the first argument is actually optional according to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call#using_call_to_invoke_a_function_and_without_specifying_the_first_argument) and own observations.

**Comment by MartinJohns** [comment]
> Function.prototype.call combined with Optional Chaining is a nice way to only call a method if the method is defined

Am I missing something weird here? You can do that with the `?.()` operator as well.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#optional_chaining_with_function_calls

**Comment by jonath92** [comment]
I didn't know that. This is indeed much better as you don't loose IntelliSense that way. Thanks.  But this is a Bug anyway (also not very important tbh) :-)

**Comment by MartinJohns** [comment]
It's not explicitly mentioned, but #27028 seems to me more like it's a design decision, not a bug. Calling `.call()` without a `thisArg` rarely makes sense, and in these few cases you can just pass `undefined` along.
