### ISSUE TITLE
'extends null' doesn't error on using methods from Object.prototype

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4454]
We currently support extends null using #3516 and #3524, but I was wondering if we might also want to error on incorrectly using 'extends null'

```TypeScript
class C extends null{
    x: number;
}

var c: C;
c.toString()
```

From the Mozilla docs "Extending from null works like with a normal class, except that the prototype object does not inherit from Object.prototype."

I may be missing something in the above example (apologies if so), but it looks like we might want to warn on the use of toString since, assuming I'm reading it correctly, this method does not exist on an instance of C.

**Comment by danquirk** [comment]
Probably some relevant discussion in https://github.com/Microsoft/TypeScript/issues/3696 and the linked issues therein

**Comment by jonathandturner** [comment]
Good catch. Missed that one when I searched

**Comment by mhegazy** [comment]
This is by design so far. We assume that Object is the super type of everything. if we want this to work, we need to change this assumption. the complexity of the change does not map to the value added to the user by enabling this feature.
