### ISSUE TITLE
SVGPathElement is missing methods: isPointInStroke, isPointInFill

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#44541]
# Bug Report

### 🔎 Search Terms

SVGPathElement, isPointInStroke, isPointInFill

### 🕗 Version & Regression Information

This is the behavior in every version I tried.

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.3.2#code/DYUwLgBAhhBc0DsCeEC8EEFdjANwCgAKGKAZwgGUA1AcQAUowALAUVAFsQEwBKAOgCWpOgHsB3AJIIAYgJyEeBYtHLUaNECM5gATkjYhO3fkNHiwU2fMVA

### 💻 Code

```ts
let a : any = null;
(a as SVGPathElement).isPointInFill();
(a as SVGGeometryElement).isPointInFill();
```

### 🙁 Actual behavior

Line 2 throws an error

### 🙂 Expected behavior

Line 2 should compile, cause path has this method

**Comment by jogibear9988** [comment]
#44336

**Comment by jogibear9988** [comment]
@RyanCavanaugh 
hopefully now it's better

**Comment by jogibear9988** [comment]
SVGPathElement should extend SVGGeometryElement and not SVGGraphicsElement

**Comment by jogibear9988** [comment]
see mozilla doc's https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement

**Comment by Netail** [comment]
I believe more element are wrong as a lot are extending SVGGraphicsElement instead of the correct one

**Comment by huytd** [comment]
Look like it works in the latest TypeScript (at this moment, it's v4.6.2)

https://www.typescriptlang.org/play?#code/DYUwLgBAhhBc0DsCeEC8EEFdjANwCgAKGKAZwgGUA1AcQAUowALAUVAFsQEwBKAOgCWpOgHsB3AJIIAYgJyEeBYtHLUaNECM5gATkjYhO3fkNHiwU2fMVA

I think we can close this ticket now.
