### ISSUE TITLE
Colorization in peek window for JSX code is incorrect

### ISSUE THREAD

**Issue by paulvanbrenk** [microsoft/TypeScript#4455]
The closing tag in the peek window is treated as being a regular expression.

![image](https://cloud.githubusercontent.com/assets/5273975/9480678/4b53d78c-4b39-11e5-9e65-ba69ca8018e0.png)

_Repro_
1. Create new Html App
2. Add '.tsx' file
3. Add the following code

``` typescript
var React;
var x = <div></div>
```
1. Put cursor on `x` and use Alt + F12 to bring up the peek window. (Screen shot is when using a different file, also repros on same file).

**Comment by azizhk** [comment]
I guess this is fixed.
