### ISSUE TITLE
Unable to pass an awaited ArrayBuffer to a TypedArray constructor

### ISSUE THREAD

**Issue by jyang14** [microsoft/TypeScript#44557]
# Bug Report

### 🔎 Search Terms

`TypedArray`, `ArrayBuffer`, `Promise.then`, `await`

### 🕗 Version & Regression Information

- This changed between versions v3.3.3333 and v3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.4.0-dev.20210611#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBAAUDBO5lAlIAlKAALwAPlAAG9FCUSioAHLDSTwMjxUbcnlcnlS9GcQQ0RxkJgswaQCSPDKoAAcFTIirw1Ny8jobEQQkgASJ8GgekZAW+nEpjJZ7M4qsquqYACF2EifpSAIwABgZIfFJQAvsEpSpwMLRZwxn1UaAnMkeuhKAnQAAiBiGmi0E1mi36K02hl27AOmmnWD0plslVqnV672+sgB4MM7Nh0AqKziQSQDb4lA6RwUBjSdy9yXSkoIWXyj14NvInHMsT541IYuW62QW32x0Nl1ulten3rzuh+cL+BLsQr5WutUPDXalfUldrn4M3uRr2MZxu8ewcDQ3w5vaPZSnO86LnKT56i+brvtsn56gaDBGoWu5DiWghloer7uq2V5+kGIb-lKkbhgyjIANzBCoOANB4ZBeIgwrOCC7AQfcjAJuwDDMJA-CwNA6iJFO8B6CIXjZgAoqsDCIDU+jZkkOLZuADioAA5MIfKqtmQQqAA8t8ZC7EO-CiccqCOAorjSHgKaQFxOijFg+goAgiAwsIVyQRIwrRCIBgcDi3QsGwXDcEEJRAA)

### 💻 Code

```ts
const array = new Uint8Array(await Promise.resolve().then(() => new ArrayBuffer(10)))
```

### 🙁 Actual behavior

The above code throws the following error when passing to a `TypedArray` an awaited `ArrayBuffer` from a `Promise` involving a `then` call
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'Iterable<number> | ArrayBuffer' is not assignable to parameter of type 'ArrayBuffer'.
      Type 'Iterable<number>' is missing the following properties from type 'ArrayBuffer': byteLength, slice, [Symbol.toStringTag]
```

### 🙂 Expected behavior

The code should work because the following will not throw an error as the follow examples don't throw an error (also in playground link):
```ts
// refactoring the arrayBuffer definition to a separate variable doesn't throw an error
const arrayBuffer = await Promise.resolve().then(() => new ArrayBuffer(10))
const array = new Uint8Array(arrayBuffer)
```
```ts
// without the "then" it doesn't throw an error
const array = new Uint8Array(Promise.resolve(new ArrayBuffer(10)))
```

**Comment by RyanCavanaugh** [comment]
See #40466
