### ISSUE TITLE
Incorrectly non-specific inference of a specific template type within a variadic tuple

### ISSUE THREAD

**Issue by jonathan-codaio** [microsoft/TypeScript#44561]
# Bug Report

### 🔎 Search Terms

variadic tuple generic inference

### 🕗 Version & Regression Information

Occurring in 4.2.4 (my environment) as well as 4.3.2 (playground).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBACghgJzhAKgTwA7CgbwFBSFQDOALggJYgDmANAUeBAEbAL0C+eeVpbAZnADG2eEggARYPwA8KKMAAefEABNisRMnRYAfLgaFSmYAC4oKANyGoIZGZLkq1a1zzGsm8VP4aAvFAA2mLIPjJwIGi6tFAAdPEAgghIaDIhktLhkbq6ALpQAD5BudY8IHwIgiJQAGIA9ggQYAA2cGHySirqXqHSxPr4RLb25mSUNNZDGFoQwBXE5lZ4bvxgIEKkFHUgUBBwANbA6XNscgrKoN3pOsC6ABSq0ubp7boAlM8zrwZDCHNgCB2j34rm4q3Wm22uwOwHqjRacDOnUuGhefXuwPMcKarVeH1qDRxbUyKAGNj+pABQOkoLw4I2Wx2e0OAGUnDRjhUHk8ehlZNcTLExs53p9vJkBVghezqGTfv9AVBgbShNsyFB+ISEVAAszYVrWndBowRlAAOQoYBkM30KYzE4IBZBGxDPWcthGuyzcxmm1QDwOSXAaXjagcN62oZEPVs0PuhCe02+mIBsXaQXCmjhyOEXKcN6lVUgdVkCKqODNbZHGY66GHeOJ73mv2p3k3EPOcOlAD03YsAAsKBoh7ywkH9MwwKQSMBgBANM0KIcoBRp8R+3UWqooKxRxKZu3M7L3CYSButwAhavi-gAeX4sectYDdX4GoNcFi03EDuIgQADCUUC9lAACqAByACiAAaMCQQAwigkESHgIEoIOw4aKqyTABszRoHu-IHhmMq6CenhDmid4PjKz4mK+77wq0X72vMgQAIwlKhfboSOI4VsQdRQNhfx4QRVFpMRUpHmRAYrsQCTNIJVH3o+NB0VgDGlmoFZVuklhAA)

### 💻 Code

```ts
enum ParamType {
    string,
    number,
}

interface ParamDef<T extends ParamType> {
    type: T;
    name: string;
}

type ParamDefs = [ParamDef<any>, ...Array<ParamDef<any>>] | [];

interface FormulaDef<T extends ParamDefs> {
    name: string;
    parameters: T;
}

function makeParameter<T extends ParamType>(def: ParamDef<T>): ParamDef<T> {
    return def;
}

function makeFormula<T extends ParamDefs>(def: FormulaDef<T>): FormulaDef<T> {
    return def;
}

function makeStringParameter(def: ParamDef<ParamType.string>): ParamDef<ParamType.string> {
    return def;
}

const formula = makeFormula({
    name: 'Test',
    parameters: [
        makeParameter({name: '', type: ParamType.string}),
        makeStringParameter({name: '', type: ParamType.string}),
    ],
});

const standaloneParam = makeParameter({name: '', type: ParamType.string});

// This is ParamDef<ParamType> but seems like it should be ParamDef<ParamType.string>
type shouldBeParamDefOfString = typeof formula.parameters[0]; // UNEXPECTED
// This is correctly ParamDef<ParamType.string>
type isParamDefOfString = typeof formula.parameters[1];
// This is also correctly ParamDef<ParamType.string>
type isAlsoParamDefOfString = typeof standaloneParam;
```

### 🙁 Actual behavior

I have a function (`makeFormula()`) that's meant to infer the types of each element of a variadic tuple. The tuple members are themselves function invocations (`makeParameter()`) with templated return types that should infer a specific return type based on their arguments.

The `makeFormula()` calls correctly infer specific return type when called on their own. But when called as a tuple element of `parameters: [...]` in a call to `makeFormula()`, `parameters` seems to be incorrectly inferring the tuple element value as the generic `ParamDef<Type>` instead of the specific `ParamDef<Type.string>` that is inferred properly when `makeParameter()` is called on its own.

It seems like their is some kind of top-down inference happening in the `makeFormula()` case? This feels like a bug but is perhaps an expected resolution of inference ambiguity. Even if it is a bug, is there perhaps a way to define any of the types here to force a correct inference?

It's straightforward to add `as const` to force correct inference (as in `makeParameter({type: ParamType.string as const})`, but unfortunately that isn't an option here as this will be part of an SDK and all users would need to know to add `as const` and all independently work around this.

### 🙂 Expected behavior

Expected the type of `formula.parameters[0]` to be inferred as `ParamDef<Type.string>` instead of `ParamDef<Type>`.

**Comment by RyanCavanaugh** [comment]
The inference here veers off from where you expected because we see the `ParamDef<any>` instantation, which ends up creating a lower-priority inference site that competes with the contextual type's inference candidate of `ParamType` derived from the constraint of `createFormula`

You can fix this by changing the definition to the equivalent-from-the-outside form:
```ts
type ParamDefs = [ParamDef<ParamType>, ...Array<ParamDef<ParamType>>] | [];
```

**Comment by jonathan-codaio** [comment]
Wow, can't believe it was that simple, and that in all the things we tried we missed that one. Thank you for the thoughtful explanation and fix!
