### ISSUE TITLE
Non-null assertion operator ignored in sub context

### ISSUE THREAD

**Issue by KyleJune** [microsoft/TypeScript#44575]
# Bug Report

### 🔎 Search Terms

non-null assertion, deno, Property 'x' does not exist on type 'never'.

### 🕗 Version & Regression Information

This regression happened between typescript 4.2.2 and 4.3.2.

### ⏯ Playground Link

[Playground link showing no errors in 4.2.2](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgAoHtRmQbwFDLIAeAXMiAK4C2ARtANwHICeZltDeAvngDYTYADmQxZkAH3IVevZAF4pMxjAogEYYOhDI4AZ13AA5iFQAKAG5xeFCCMzgAlLiaD5yS9YiMeeg8bM4xGQATAA0LGQAzMhcDoz82ABebNR0UG6CAIQAdETIAFTIWdnMjMAwyKaCTviEiRk5eYXFpdx4CFq66PzZYHA0-KaBpEWN4ayjJeH1sfRAA)

[Playground link showing errors in 4.3.2](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgAoHtRmQbwFDLIAeAXMiAK4C2ARtANwHICeZltDeAvngDYTYADmQxZkAH3IVevZAF4pMxjAogEYYOhDI4AZ13AA5iFQAKAG5xeFCCMzgAlLiaD5yS9YiMeeg8bM4xGQATAA0LGQAzMhcDoz82ABebNR0UG6CAIQAdETIAFTIWdnMjMAwyKaCTviEiRk5eYXFpdx4CFq66PzZYHA0-KaBpEWN4ayjJeH1sfRAA)

### 💻 Code

```ts
interface Point {
  x: number;
  y: number;
}
let p: Point | null = null;
function assignP(value: Point) {
  p = value;
}
assignP({ x: 2, y: 3 });
let z: number = p!.x * p!.y;
if (p) {
  z = p!.x * p!.y;
}
console.table({ x: p!.x, y: p!.y, z });
```

### 🙁 Actual behavior

Errors inside the if block because p is inferred as never.

### 🙂 Expected behavior

No errors.

I also believe the non-null assertion operator in the if block should not be required since the context would only be reached if p was not null. The non-null assertion in the if block was required in 4.2.2.

**Comment by MartinJohns** [comment]
You see this behavior due to a fixed bug. See #44025.  
In the end it's due to #9998.

**Comment by MartinJohns** [comment]
You can get the behavior you want by changing your code to this:

    let p = null as Point | null;
