### ISSUE TITLE
Class attribute inference with template literals

### ISSUE THREAD

**Issue by gregoirechauvet** [microsoft/TypeScript#44581]
# Bug Report

### 🔎 Search Terms

template literals class attribute 7022

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.2

### ⏯ Playground Link

Working with TypeScript 4.2.3:
https://www.typescriptlang.org/play?ts=4.2.3#code/MYGwhgzhAECyCeBhcVoG8BQ1oAcBOA9jgKZ4Au8A3FroSefAEzU3AEB2EZeArsGQTwAKAJToa2NpzLQAbmDwBLMACMQxaAF5oAcggEAtsTIALRewDmOjBOinFEAHT4ipClugADAGYECn6mxseycXegpGDx8-AFoAEjR5JVV1AF8A21spLmgQAmAwEAAFOjd4KN8CeMSFZTVidMDoVIxUoA

Not anymore in TypeScript 4.3.2:
https://www.typescriptlang.org/play?ts=4.3.2#code/MYGwhgzhAECyCeBhcVoG8BQ1oAcBOA9jgKZ4Au8A3FroSefAEzU3AEB2EZeArsGQTwAKAJToa2NpzLQAbmDwBLMACMQxaAF5oAcggEAtsTIALRewDmOjBOinFEAHT4ipClugADAGYECn6mxseycXegpGDx8-AFoAEjR5JVV1AF8A21spLmgQAmAwEAAFOjd4KN8CeMSFZTVidMDoVIxUoA

### 💻 Code

```ts
class MyClass {
  property;
  property2;

  constructor() {
    const variable = 'something'

    this.property = `foo`; // Correctly inferred as `string`
    this.property2 = `foo-${variable}`; // Causes an error
    
    const localProperty = `foo-${variable}`; // Correctly inferred as `string`
  }
}
```

### 🙁 Actual behavior

It raises the following error on `property2`:
```
'property2' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer. (7022)
```

### 🙂 Expected behavior

`property2` should be inferred as `string`

**Comment by a-tarasyuk** [comment]
I noticed that weird behavior some time ago working on one of the issues. It seems this [commit](https://github.com/microsoft/TypeScript/pull/43376/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R31802-R31807) causes the error. It looks like  `getContextualType` adds _`circularities`_ that triggers `popTypeResolution` to return `false` in `getTypeOfVariableOrParameterOrPropertyWorker`.
