### ISSUE TITLE
 TypeScript is not able to infer the type narrowing from method

### ISSUE THREAD

**Issue by iRealNirmal** [microsoft/TypeScript#44591]
# Bug Report

### 🔎 Search Terms

Type narrowing
### 🕗 Version & Regression Information
TS - 4.3.2
(Regression not aware)

### 💻 Code

```
  private _enabled(): boolean {
    return this.maxlength ? true : false;
  }

  private _createValidator(): void {
    const maxlength = this.maxlength;
    this._validator = (this._enabled()) ? maxLengthValidator(toInteger(maxlength)) : nullValidator;
  }
  ```
### 🙁 Actual behavior
<img width="1178" alt="Screenshot 2021-06-15 at 1 33 46 PM" src="https://user-images.githubusercontent.com/4091874/122016936-2493d000-cddf-11eb-9115-48592182a256.png">
When using method getting error.

`Argument of type 'string | number | null' is not assignable to parameter of type 'string | number'.` while same thing is working when using variable directly.

<img width="737" alt="Screenshot 2021-06-15 at 1 41 08 PM" src="https://user-images.githubusercontent.com/4091874/122017116-4ee58d80-cddf-11eb-8947-11563baf2479.png">

### 🙂 Expected behavior

**Narrowing should work whether we use method or property.**

**Comment by MartinJohns** [comment]
This just sounds like an issue with the library you use. Without a reproducible example we can't tell you what's wrong, but most likely TypeScript works as it should.

**Comment by wangweixuan** [comment]
To make this narrowing, the compiler has to look into `_enabled` method and perform interprocedural analysis. That might be too costly and hard to implement. Currently type narrowing applies mostly to local variables.
For this problem I would recommend you to use non-null assertion on `maxlength`.

**Comment by MartinJohns** [comment]
Performing analysis for every method would be way too costly. I think the most close would be something like #38390, which aims to automatically infer type guards for simple cases.

**Comment by iRealNirmal** [comment]
@wangweixuan @MartinJohns using non-null assertion resolved type issue.
`this._validator = this._enabled() ? maxLengthValidator(toInteger(maxlength!.toString())) : nullValidator;`

If it's costly process at least can we suggest to either use non-null assertion ?

**Comment by MartinJohns** [comment]
> If it's costly process at least can we suggest to either use non-null assertion ?

I don't understand the question. You're free to use the non-null assertion operator whenever in your code.

**Comment by iRealNirmal** [comment]
You can see suggestion tooltip in below screenshot, do you think it's possible to have some suggestion for non-null assertion. If not then I can close this  ticket as it's not technically feasible right now.
![](https://user-images.githubusercontent.com/4091874/122016936-2493d000-cddf-11eb-9115-48592182a256.png)

**Comment by RyanCavanaugh** [comment]
We don't inline method bodies for CFA purposes, and even if we did, we don't retroactively apply narrowings on the basis of assuming non-mutation of the initializing reference.

We don't automatically suggest `!` because we want you to *actually* think about whether something might be null or not 🙂
