### ISSUE TITLE
Strictly check methods when implementing an interface

### ISSUE THREAD

**Issue by cybrown** [microsoft/TypeScript#44592]
# Bug Report

### 🔎 Search Terms

interface implements parameter sum type

### 🕗 Version & Regression Information

Seen on all versions available on the playground (3.3.3333 to 4.3.2).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/JYOwLgpgTgZghgYwgAgLIE8CS5rycgbwCgjkzkB6C5AFQAtgBnZUSWRFAEwgQBs4oEZnGQBbCGDoB7TsgDuwSchEAHAXHFt5DBHRbDkjAK6jkYdCpRSYyw2CigA5spCyRIEwCNopcjClSABQAbnC8RhAAXHYOIM4APsgeot5QAJTRwVLAnADcRAC+JHxwjMwYAML8ZSyiKrwQ4uDlWDjs+MS+ZFTIAHJSkGZ0cGBDKGpQGhLQAOTM5pb6yFIgvOi2jPZOXcj+QaHhUTFOGchZOYQ75MhX5D0AEtAocigIYby2mtKyK2vKocB+J4GssQMc4owADQsUYKXgfSRQKRybQQMEHCJLdxeHzXa4IFaMKQNAB0vCkjhCYQiJLAUgAqipLFAKqUIIE0ml8tcikUiD1QJs4CB8ExkNwYKAIG5hGCMNg2HgIEQCSBNiw1WBhUhovK2krkABeJIQFGVaqMDn5QVakUQEl7QIAIke8KkTrSlGo9DFcikUAA1owiDbtfbHQBmLle2gMZgEuqAoTITxGWEoRwSWxQIzgYDiZAAUSgSKgRCAA)

### 💻 Code

```ts
interface MyInterface {

    // This interface declares a method with a parameter which is a sum type of a string and a number
    foo(value: string | number): void;
}

class MyClass implements MyInterface {

    // Note that the parameter's type is only a string
    foo(value: string): void {
        
        // Here we call a method only available on strings, it will throw when value is a number
        console.log(value.toUpperCase());
    }
}

// instance is defined as an MyInterface
const instance: MyInterface = new MyClass();
instance.foo("Hello") // This works
instance.foo(3); // This compiles but we get a runtime Error
```

### 🙁 Actual behavior

The code compile but throws at runtime.

### 🙂 Expected behavior

There should be a compile error on the class that implements the interface, or when a class instance is assigned to a value with this interface.

**Comment by IllusionMH** [comment]
Methods are always treated as bivariant and would allow this implementation. You need to change interface to use property declaration:  `foo: (value: string | number) => void;`

Similar to examples in https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types

**Comment by cybrown** [comment]
Thanks, it works with this workaround !
