### ISSUE TITLE
Type guard error with Object spread

### ISSUE THREAD

**Issue by stphdenis** [microsoft/TypeScript#44607]
# Bug Report

### 🕗 Version Information

4.4.0-dev.20210615
4.3.2
All TypeScript Playground versions.

### 💻 Code

```ts
const obj: {
  id?: string
  dummy: string
} = {
  dummy: 'dummy'
}
if (obj.id !== undefined) { //=> obj.id defined
  const obj1 = {...obj} // obj1.id is `string | undefined` => should be `string`
  const obj2 = {...obj, id: obj.id} // obj2.id is `string` => OK
}
```

### 🙁 Actual behavior

The type of `obj1.id` is `string | undefined`
The type of `obj2.id` is  `string`

### 🙂 Expected behavior

`obj1` and `obj2` should have the same type.
The type of `obj1.id` should be `string`.

**Comment by RyanCavanaugh** [comment]
Duplicate #43809
