### ISSUE TITLE
[JS/TS] Add semantic highlighting to @example params in JSDoc comments

### ISSUE THREAD

**Issue by ImRodry** [microsoft/TypeScript#44606]
I'd like to suggest the addition of semantic highlighting for `@example` fields in JSDoc comments. These are often used to insert example code snippets of the function or property in question so being able to visualize them better would be quite helpful. I believe this should work on the line there `@example` is and all the ones below it until a new type of field is added or the JSDoc comments ends.

**Comment by mjbvz** [comment]
Have you tried [this extension](https://marketplace.visualstudio.com/items?itemName=bierner.jsdoc-markdown-highlighting) for basic highlighting?

Semantic highlighting would still need support from TS server

**Comment by ImRodry** [comment]
I was not aware that that extension also highlighted example comments, so I installed it now.
While that extension brings many other good QOL features, I think it would make sense for vscode to support highlighting in example comments natively. Either way that's up to you but this extension does fix my issue, so thanks!
