### ISSUE TITLE
Conditional eval transform is not spec compliant

### ISSUE THREAD

**Issue by acutmore** [microsoft/TypeScript#44617]
# Bug Report

### 🔎 Search Terms

eval, conditional, transform

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about eval

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.3.2#code/GYVwdgxgLglg9mABFApgZygCgJSIN4BQixiANilIgIaIC8iAjANxEnmUBO6Ipl9KANyqkA-ADpMAciqTsLEoggI0ccmNJwA5pi5oeUOQQC+BAqgw4mQA

### 💻 Code

```ts
function test() {
    let a = 1;
    let result = eval?.('a'); // this should not have access to 'a'
    console.log(result);
}
```

### 🙁 Actual behavior

Code logs the value of a.

```js
let result = eval === null || eval === void 0 ? void 0 : eval('a');
```

### 🙂 Expected behavior

Expect a runtime exception

```js
// from Babel
let result = eval === null || eval === void 0 ? void 0 : (0, eval)("test");
```

**Comment by nmain** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/43327
My search term was eval

**Comment by acutmore** [comment]
> Duplicate of #43327
> My search term was eval

Thanks @nmain! Not sure why I jumped immediately to searching for “eval transform”. I probably assumed “eval” on its own would have too many results 🙂
