### ISSUE TITLE
Type information lost when combining intersection type with union type

### ISSUE THREAD

**Issue by Albert-Gao** [microsoft/TypeScript#44610]
# Bug Report

In the following type definition, the `age` and `isHuman` is lost.

```typescript
type Additional = {age: number} | {isHuman: boolean}

type Test = {name: string} & Additional

function test(p:Test){
   // p only has `name` but not `age` and `isHuman`
}
```

![image](https://user-images.githubusercontent.com/18282328/122155296-cb996a00-ceba-11eb-9822-1bd1e6f54ef3.png)

## So essentially, we expect `type Test` to have 2 variations
```typescript
// 1st variation
type Test =  {name: string, age: number}

// 2nd variation
type Test =  {name: string, isHuman: boolean}
```

**Playground link:** 
https://www.typescriptlang.org/play?ssl=6&ssc=2&pln=1&pc=1#code/C4TwDgpgBAggJnAlsRB7AdgQwDZQLxQDemA5hAFxToCuAtgEYQBOAvlAD5GIDOAEnZnSV6qVNgiCWAKCmhIUACoRuwfESy0KUFU0ToSbAGSwEyNFmwyAZtXQBjFBijBlwABRhySlQEpCUliA

## Context
This is a simplified production code example, where the type `Additional` is generated by another function. The final type we will use is consistent in the codebase as `type FinalType = Base & Additional`

**Comment by fatcerberus** [comment]
> So essentially, we expect type Test to have 2 variations

Yes, that's correct. But you don't know which, so `age` and `isHuman` won't be displayed in the IntelliSense until you do, e.g. by checking `if ('age' in p)`.  That's normal for union types; nothing out of the ordinary here.
