### ISSUE TITLE
override keyword does not work with generator methods

### ISSUE THREAD

**Issue by Agreon** [microsoft/TypeScript#44611]
# Bug Report

### 🔎 Search Terms

noImplicitOverride

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because `noImplicitOverride` was previously not available

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210615&noImplicitOverride=true#code/KYDwDg9gTgLgBAYwDYEMDOa4CF3AMKoZwDeAUHBXGAK4BGSAlggFRxrAwDKMKMwAFGh58AXHGoA7ANYSIAdwkBKEgF9Sa0qEixEhTABFgUBgDdgAEwLpMoPhPOYc7K0TKUqdRizgQzUY+bAbBzcvAJCYWKSMvJKqupAA)

### 💻 Code
```
export class BaseClass {
    public* setState(state: unknown) {}
}

export class DerivedClass extends BaseClass {
    public* override setState(state: unknown) {}
}
```
### 🙁 Actual behavior

A parser error occurs (See playground).

### 🙂 Expected behavior

No error occurs.

**Comment by MartinJohns** [comment]
This works:

    export class DerivedClass extends BaseClass {
        public override *setState(state: unknown) {}
    }

**Comment by Agreon** [comment]
Oh im very sorry for the unnecessary issue. Our eslint confused me.

**Comment by MartinJohns** [comment]
Given the weird placing of the `*` symbol in all examples I absolutely understand the confusion.

For function it's usually placed next to the function keyword: `function* foo()...`  
But for properties/methods it's usually placed next to the name: `*foo()...`

Perhaps a feature request for TypeScript could be made to allow both versions, before and after the `override` keyword.

**Comment by RyanCavanaugh** [comment]
I don't think we'd want to do that. Expanding the number of places it can appear in the grammar means we have to decide what to do with `public * override * foo(`, etc., and opens up style debates -- since the keyword ordering is enforced, and `*` is effectively a contextual keyword, we would "want" to enforce that order, which is effectively what's already happening.

Reminds me of the good ol' days of
```
int* c
vs
int *c
```
😅
