### ISSUE TITLE
3.9.10 is published as latest

### ISSUE THREAD

**Issue by shiftgeist** [microsoft/TypeScript#44620]
# Bug Report

### 🔎 Search Terms

npm latest tag 3.9.10

### 🕗 Version & Regression Information

typescript@3.9.10 (5 minutes ago)

### ⏯ Playground Link

https://www.npmjs.com/package/typescript?activeTab=versions

### 💻 Code

![image](https://user-images.githubusercontent.com/30648730/122305189-c235ef00-cf06-11eb-9f7f-a1e9497306ae.png)

### 🙁 Actual behavior

3.9.10 is latest

### 🙂 Expected behavior

4.3.2 is latest

**Comment by RyanCavanaugh** [comment]
Fix in progress 🏃‍♂️

**Comment by DanielRosenwasser** [comment]
It'll take a bit to propagate out but https://github.com/microsoft/TypeScript/releases/tag/v4.3.3 is out and is now tagged as latest.

**Comment by RyanCavanaugh** [comment]
Verified ✔
```
> npm dist-tag ls typescript
beta: 4.3.0-beta
dev: 3.9.4
insiders: 4.2.0-insiders.20210210
latest: 4.3.3
next: 4.4.0-dev.20210616
rc: 4.3.1-rc
tag-for-publishing-older-releases: 4.0.6
```

**Comment by RyanCavanaugh** [comment]
@shiftgeist thanks for the report!

**Comment by DanielRosenwasser** [comment]
Thank you!
