### ISSUE TITLE
interface type can't be assigned to index signature type with `unknown`

### ISSUE THREAD

**Issue by g-plane** [microsoft/TypeScript#44628]
# Bug Report

### 🔎 Search Terms

interface
index signature
assignment
assignability

### 🕗 Version & Regression Information

From 4.0 to Nightly. (I haven't tested it with older versions.)

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.3.2#code/JYOwLgpgTgZghgYwgAgLIE8DyAjAVhBMZAbwFgAoZZABygHtqAuZAZzClAHMKBfCigCYEANnCgphEInGbFkAbQAeyUK3ZcAuswCuIANYg6AdxDI+5IQlHjkkotlkLlqthxCctyOCHRnBIsQkpZARmDBx8Qn5yOGQAXhCKbHiQoA)

### 💻 Code

```ts
interface MyObject {
  prop: string
}

declare let a: { [x in string]: unknown }
declare let b: { [x in string]: any }
declare let c: MyObject

a = c  // error at this line
b = c
```

### 🙁 Actual behavior

Type 'MyObject' is not assignable to type '{ [x: string]: unknown; }'. Index signature is missing in type 'MyObject'.

### 🙂 Expected behavior

No errors.

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript/issues/42825#issuecomment-789242594.
