### ISSUE TITLE
Renaming an object property on destructuring (aliasing) also changes type definition.

### ISSUE THREAD

**Issue by dalmo3** [microsoft/TypeScript#44627]
# Bug Report

I ran into this strange bug where renaming a property on destructuring will also rename the original property in the type definition.

This is a gif that shows what happens: I'm using VSCode's rename function on F2.
 
![destruct-rename](https://user-images.githubusercontent.com/33860060/122339159-d4f70500-cf94-11eb-8713-addc7d6d24c0.gif)

The expected behaviour is that it should just create an alias for the property and update its usage down the file, without also changing the type. In fact, that's what usually happens. 

This bug is somewhat random and I can't easily reproduce it. It was just the 4th or 5th time it happened when I decided to write it here. Apparently it doesn't go away by restarting the ts server, but it does by reloading VSCode.

### 🕗 Version & Regression Information

TS 4.3.2
VSCode insiders 1.57
WSL2

### 💻 Code
`typescript.preferences.useAliasesForRenames: true`

```ts
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "."
    // "noImplicitAny": false
  },
  "include": ["src"]
}

```

I understand that there is very little actionable information here. Let me know how can I collect more info about it next time it happens.

**Comment by RyanCavanaugh** [comment]
We can poke at this but need code (we policy we do not transcribe screenshots)

**Comment by dalmo3** [comment]
Absolutely. I'll come back whenever I have some piece of code that reproduces this again. Just some more info for the record:

I just remembered another time this happened (on another codebase) when I renamed a `div` to a `span` and it went all the way to rename JSX definitions in node_modules. Very similar to https://github.com/microsoft/TypeScript/issues/7458 except it only renamed the scoped `div` (as expected) and the type definition (totally unexpected). 

Also related: https://github.com/microsoft/TypeScript/pull/25273, https://github.com/microsoft/TypeScript/issues/8227, https://github.com/microsoft/TypeScript/issues/42367

It seems different people have conflicting ideas on what should/shouldn't be renamed automatically. I won't discuss that. Could it be that different PRs fixing those little corner cases are causing a race condition between conflicting rules? I think it works consistently 99.9% of the time, but sometimes it goes awry, hence why I opened this as a bug.

**Comment by fatcerberus** [comment]
> I'll come back whenever I have some piece of code that reproduces this again.

You posted a screenshot of code that reproduces it. Can’t you just copy & paste that?

**Comment by dalmo3** [comment]
In theory, yes. But there's nothing special about that piece of code. It just happened that the issue was happening at that point in time, all throughout the project, and I could've used any part of the codebase to show it. The piece in the image was just the first one I found simple enough to describe the issue concisely. The code worked just fine after I reloaded VSCode.

Anything as simple as this could potentially trigger the issue:
```ts
--- A.ts ---

export type A = {
  a: string;
};

--- B.ts ---

import { A } from "./A";
const { a }: A = { a: "" };

```

I added something similar to that to a sandbox and was able to reproduced it, **but only once**: https://codesandbox.io/s/optimistic-water-teghj?file=/src/App.tsx (renaming `a` at `App.tsx:13`, changes type definition in `A.ts`). Note that the sandbox also contains the same `tsconfig` as the original post.

**Comment by RyanCavanaugh** [comment]
The sandbox's "Change all occurrences" functionality is provided by the editor, not TS. "Rename" is a different operation that understands more semantics. e.g. in that sandbox if you add
```ts
function fn() {
  let a = 4;
}
```
in app.tx, "Change all occurrences" will rename that `a`, but "Rename" will not.

**Comment by dalmo3** [comment]
I understand, but that's unrelated to the issue I'm describing, though.
