### ISSUE TITLE
Error extending interface with generic parameter

### ISSUE THREAD

**Issue by rchl** [microsoft/TypeScript#44630]
# Bug Report

Typescript 4.3.x started reporting an error in existing code when extending an interface that includes generic parameter like:

```ts
import 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    foo?: boolean
  }
}
```

### 🕗 Version & Regression Information

- This changed between versions 4.2.4 and 4.3.0
- I can still reproduce in 4.3.3

### ⏯ Playground Link

Reproduction: https://github.com/rchl/ts-types-vue-bug

### 💻 Code

```ts
import 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    foo?: boolean
  }
}
```

### 🙁 Actual behavior

```
npx tsc
node_modules/vue/types/options.d.ts:68:18 - error TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

68 export interface ComponentOptions<
                    ~~~~~~~~~~~~~~~~

types/index.d.ts:4:13 - error TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

4   interface ComponentOptions<V extends Vue> {
              ~~~~~~~~~~~~~~~~
```

### 🙂 Expected behavior

No error.

**Comment by RyanCavanaugh** [comment]
This was a bug in 4.2. The error message means it when it says: all declarations of interfaces must have identical type parameters.

**Comment by rchl** [comment]
The original interface looks like this:
```ts
export interface ComponentOptions<
  V extends Vue,
  Data=DefaultData<V>,
  Methods=DefaultMethods<V>,
  Computed=DefaultComputed,
  PropsDef=PropsDefinition<DefaultProps>,
  Props=DefaultProps> {
// ...
}
```

If I change my override to:

```ts
import 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<
    V extends Vue,
    Data=DefaultData<V>,
    Methods=DefaultMethods<V>,
    Computed=DefaultComputed,
    PropsDef=PropsDefinition<DefaultProps>,
    Props=DefaultProps
  > {
    foo?: boolean
  }
}
```
then it still complains with the same exact error.

**Comment by rchl** [comment]
And note that this was working "since the beginning" since this is pretty common pattern in Vue/Nuxt plugins/modules.

**Comment by ShuiRuTian** [comment]
Surprising, the reason is the "Vue" is not identical to "Vue".

You could press F12 on 
```
import 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
//                                     here, Press F12 to see this "Vue", I will call it "OutVue"
    foo?: boolean
  }
}
```

We could see "OutVue" is not just what it is defined internal. It is added another namespace for backward compatibility.

And I find a interesting "fix":
``` ts
import 'vue'
import Vue from 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    foo?: boolean
  }
}
```

Here we import the non-backword Vue, so it is identical now.

@rchl 
I have never used Vue, so could you please tell me whether this this "fix" meets your requirement or not?

**Comment by rchl** [comment]
Very interesting. Thanks for that investigation.

Even though this was always working before, it seems like it's mostly just my code that did mistake so I can just update it and carry on. I just hope that there are not many other packages that did the same and that would be harder to get updated.

But for now I think it's fine to close this issue.
