### ISSUE TITLE
add DateStyle and TimeStyle to DateTimeFormatOptions

### ISSUE THREAD

**Issue by nstringham** [microsoft/TypeScript#44632]
# lib Update Request

## Configuration Check

My compilation *target* is `es2017` and my *lib* is `["dom"]`.

## Missing / Incorrect Definition

DateTimeFormatOptions.DateStyle
DateTimeFormatOptions.TimeStyle

## Sample Code

```ts
const date = new Date();
date.toLocaleString(undefined, { dateStyle: "long", timeStyle: "short" });
```

## Documentation Link

TC39 spec: https://tc39.es/ecma402/#sec-intl-datetimeformat-constructor

MDN docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#parameters

### Note:
this is a duplicate of #38266 but formated as a lib Update Request

this is not a duplicate of #35865

**Comment by nstringham** [comment]
I noticed that this issue has been given the `Domain: lib.d.ts` tag but this problem is actually in ECMAScript not in a DOM API I think the changes needed to fix this problem should be made to [/lib/lib.es5.d.ts](https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts)

**Comment by nstringham** [comment]
changing target to `es2020` fixes this

**Comment by maxima120** [comment]
> changing target to `es2020` fixes this

does it? I changed my tsconfig and it still throws: 

`Object literal may only specify known properties, and 'timeStyle' does not exist in type 'DateTimeFormatOptions'.`

I am trying to use it like this:

`new Intl.DateTimeFormat(this.userData.options.culture, { timeStyle: 'short' }).format(new Date(sch.startDate))`

tsconfig:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "module": "es2020",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2020",
    "jsx": "react",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2020",
      "dom"
    ]
  }
}
```
