### ISSUE TITLE
Cannot infer const array when put as function args since version 4.2

### ISSUE THREAD

**Issue by dora1998** [microsoft/TypeScript#44631]
# Bug Report

### 🔎 Search Terms

Generics, `const` assertions, Tuple

### 🕗 Version & Regression Information

- This changed between versions v4.1.5 and v4.2.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAysCGxoF4oG8BQUoDMD2eAXFAM7ABOAlgHYDmGAvhqJFAJLVgCuwMEANhADGwPOQA8AFQA0UAApRUANzyUAJgD5FUABRZSCJMTiII0-WHJ4wJYnPPYAdM-jlatqPGogA2gF0MAEpFLUkAbgwIAA8wMWBcLmoRSjxqKCFyCFMObl4BYVEJGXltFXUNHRJ8kTFiHJ4+QRqi2TkNQLrOBurCqVatTGxM4C5yNKqmwoimSJi4hKTgFLSMrKRGgrEScX0ZfQAlKGikajUSKEz4NVT+EHYuvMmxPs9vDX9zConN8g99jqgh0GFwgIzGpB6W0YGAwAHpYVAAMLwKpQACMxAAqqi1BAcDQIGp0qkyJ5yOR4CA4QiALRaGg4CDkKAjMCCKA0EFgtJKeD8LjQIRiTIiW5HJQQNKcpQAFkcACYMELqKTlWQAILk7Q+VbZB4bZo6SqGCDGE3BZBaMimRz4PCBPyec5q4BKknxTIkNHaXXrSG-HQuzXkQLUpEo6Dy4gAETxBOJKvirgpd05OESyVSZPcYbpHOojOZrPZnOGox5fIFxPJBTFACM8WJoLKFbIaEKa6K7iR2825YqXSCSPKfZc-U8AzqxxB6o8fkbrUZYOaQgYbXaHU6E2RQ0A)

### 💻 Code

```ts
type State = {
  foo: string
}
// Selector is a function which has zero or some args.
type InputSelector<T, P = void> = (
  state: State,
  props: P,
  ...args: any[]
) => T;
export function createInputSelector<T, P = void>(selector: InputSelector<T, P>): InputSelector<T, P> {
  return selector;
}

// In this sample, return tuple array as is. 
export function createSelectors<
  T,
  R extends readonly InputSelector<T, any>[],
>(selectors: R): R {
  return selectors
}

// Case 1: Use defined const array
// -> All version: readonly [InputSelector<string, void>]
const constArr = [createInputSelector((state: State) => state.foo)] as const
const res1 = createSelectors(constArr)
// Case 2: Define const array in function args
// -> v4.2.2~: readonly [InputSelector<string, any>]
//    ~v4.1.5: readonly [InputSelector<string, void>]
const res2 = createSelectors([createInputSelector((state: State) => state.foo)] as const)
```

### 🙁 Actual behavior

Cannot infer tuple type since v4.2 (return type becomes extension source)

### 🙂 Expected behavior

Infer tuple type even when define const array in function args

**Comment by RyanCavanaugh** [comment]
This is the intended behavior as of 4.2; a generic default is only applied in the presence of zero inference candidates, but `createSelectors` applies a contextual inference site from its constraint, thus supplying a candidate for `P`.

**Comment by dora1998** [comment]
Thank you for the quick reply.
I undestand inference context, but why did this behavior change in 4.2?

I cannot find the relevant PRs or issues, so if you can, could you tell me those?
