### ISSUE TITLE
Vscode auto-import intellisense never recommends NodeJS packages

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#44634]
# Bug Report

### 🔎 Search Terms

- auto-import
- nodejs
- intellisense

### 🕗 Version & Regression Information

```ts
fs.
```

### 🙁 Actual behavior

If I have the `fs-extra` package then the functions exposed by that package with the prefix of `fs` are suggested. But not `import 'fs' from "fs";`

### 🙂 Expected behavior

An entry for auto-importing `fs`.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; intellisense only shows the top-level identifiers from modules, and the module `"fs"` has no member named `"fs"`. It's not clear how we'd create the mapping otherwise, since not all package names are valid identifiers.

**Comment by Nokel81** [comment]
Couldn't a mapping for packages that have a default export and whose names are valid JS identifiers be good enough?
