### ISSUE TITLE
Object strict literal assigment checking is omitted for the empty type

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4463]
in https://github.com/Microsoft/TypeScript/pull/3823
```typescript
interface A {
}
var a : A = { // valid code, but expected a problem in 1.6, since x, y, z don't belong to A 
    x: 1,
    y: 2,
    z: 3
};
```

**Comment by danquirk** [comment]
Ryan had proposed a rule that would error here if A at least had some optional members, but not if it was empty. I'm not sure what the rationale was for not erroring against empty types as well: https://github.com/Microsoft/TypeScript/pull/3842

**Comment by RyanCavanaugh** [comment]
Lots of people use `{}` in place of `any` because they don't want accidental `any`s creeping in, but still want something that's assignable from anything. Erroring on object literals assigned to `{}` is kind of pointless because, if we did, there would be nothing valid you *could* have written -- if you really wanted a type that couldn't be assigned from any non-null/undefined value, `void` is there.

**Comment by aleksey-bykov** [comment]
Are values of `void` now officially a part of the language? Thought they were leaving.

**Comment by RyanCavanaugh** [comment]
The `void` type isn't going anywhere. The only thing we've been warning people of using the crazy `number|void` thing to fake non-nullability.

**Comment by aleksey-bykov** [comment]
Can's say I see your point:

> The void type isn't going anywhere.

Fine, since it's just a type let's keep it. I was talking about *values* of type `void` which sort of don't make sense since `void` by definition represents a lack of value. The only type that doesn't have a value yet is assignable from `null` and `undefined` (what might this mean?).

> warning people of using the crazy number|void thing

Why would you warn? With all what's above `number|void` seems 100% legit (void is just another type that, hm, has values, remember?). Although I agree as far as making sense it fails, just like the idea of a legit value of `void` does.

> thing to fake non-nullability

Business sees value in it and wants it. I would not call it faking unless proven otherwise. If `number|void` gives hard feelings how about a memberless enum?

```typescript

const enum Nothing {}

```

Ugh, `Nothing | number` is doesn't play nice together, dang, lets go back to void.

**Comment by aleksey-bykov** [comment]
just thought you guys might be interested https://github.com/aleksey-bykov/by-design-script/blob/master/README.md#literal-strictness
