### ISSUE TITLE
Variable assignment changes inferred type of parameter in setter

### ISSUE THREAD

**Issue by connor4312** [microsoft/TypeScript#44641]
# Bug Report

### 🔎 Search Terms

- Setter
- Inferred type
- Undefined

### 🕗 Version & Regression Information

- [x] This is the behavior in every version I tried (3.3 to nightly)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.0-dev.20210616#code/JYOwLgpgTgZghgYwgAgJIDED2nkG8CwAUMicgM6YC2E6IAXMgK4gAmEMoELyAPsgBT8AlMgC8APmQA3TMBZCA3EVLIQmKJTgAbfjHpNW7Ttz6CRE6bPlCGMuUsIBfIkS0Qw5MOq4MzYyXbyDkQImCBkHgDuEMBQLAwY2GJ4yqRk7uRUNCC6ICIExCqkAPTFyAAqABbAZOSVmIxa3PDAWsgAtO3IYJUoAA5QEOkgSMiYMN29yHBkZMAA5iDU4MiDlJhSQ5MoAETMbBwgXDvIMFBU2+TuAHSpRcilyADK7mCg88gABhHe3KKnIE+0z6fQgcCgtS8yAQlTgIHmKB6KFAMGgg24YAAnqCxhNPnpPncij90ck9MFCvdHlUanUGk1VJgPGj1ORQKM9NC4cgAEYoPwWQIiPj7IxHFi3SlFR6oCaYhrTFjcL4iwyHLhAqHfLzoz4AGmQwA8amQWjCCKgyBZEKJKmAE1y+WhYQobmuZvm-AA5DMWDAvSJnFLHHqXFKER4KNRaMI8Kt3IwoCBPL8FMgQ2GVGoNNpHSkpSpHtnNG1qD1MCxauCUGoPHAYKiEJBuDzMZMara0jquGSQA57iR7QI9E7QuFMG6Pd7ff7A0Sg44gA

### 💻 Code

```ts
interface IFoo {
    someFn: undefined | (() => void);
    normal(fn: undefined | (() => void)): void;
}

let stored: (() => void);

const weird: IFoo = {
    set someFn(fn) {
        // This should fail -- the presence of the assignment removes the "undefined" from the set.
        // Setting `stored = fn` appears to change the inferred type of `fn`
        stored = fn;

        // This should not error since fn can be (() => void) | undefined.
        // If you add  `| undefined` to `stored`, it no longer errors
        if (fn) { console.log('asdf') }
    },

    get someFn() { return stored; },

    normal(fn) {
        // normal methods are not affected by this
        stored = fn;
        if (fn) { console.log('asdf') }
    }
}
```

### 🙁 Actual behavior

`stored = fn;` should error with strict null mode, and `if (fn)` should not error.

### 🙂 Expected behavior

`stored = fn;` appears to change the type of `fn` and remove the undefined from it

**Comment by RyanCavanaugh** [comment]
This is the intended behavior: `fn` in the setter gets its type from the inferred return type of the getter (which in turn is from `stored`, which doesn't include undefined), but `fn` in `normal(fn)` gets its type from the contextual type in `IFoo`.

**Comment by connor4312** [comment]
I suspected something like that, but I think there's still an underlying issue. `stored` explicitly typed to be `() => void`
