### ISSUE TITLE
Call base class property via super

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/TypeScript#4465]
In following code:
```
class MyBase {
  getValue(): number { return 1; }
  get value(): number { return 1; }
}

class MyDerived extends MyBase {
  constructor() {
    super();

    const f1 = super.getValue();
    const f2 = super.value;
  }
}

var d = new MyDerived();
var f3 = d.value;
```
disallowing the line "const f2 = super.value;" to be valid is... plain stupid.
What is the scenario where this behavior is valid?

**Comment by aleksey-bykov** [comment]
`super` is referring to the *prototype* object of a super class, not to the instance object, the instance object is shared between both super and sub classes, hence the limitation

**Comment by wgebczyk** [comment]
IF "super is referring to the prototype object" THEN
"super.getValue()" would not work as do not have instance reference "this".
```
class MyBase {
  private _value: number;
  constructor(value: number) { this._value = value; }
  
  getValue(): number { return this._value; }
  get value(): number { return this._value; }
}

class MyDerived extends MyBase {
  constructor() {
    super(2);

    const f1 = super.getValue();
    const f2 = super.value;
	alert(`${f1} | ${f2} | ${MyBase.prototype.value}`);
  }
}

var d = new MyDerived();
var f3 = d.value;
```
alert gets "2 | undefined | undefined". This means super DOES NOT represent prototype, but instance (kind of parent instance, but still instance).

IF "super is referring to the base object instance" THEN
Why "super.value" does not work.

**Comment by aleksey-bykov** [comment]
> IF "super is referring to the prototype object" THEN

"...super is referring to the prototype object of a **super class**"

```typescript
class MyBase {
  getValue(): number { return 1; }
  get value(): number { return 1; }
}

class MyDerived extends MyBase {
  constructor() {
    super();

    const f1 = super.getValue();
    const f2 = super.value;
  }
}

var d = new MyDerived();
var f3 = d.value;
```

is compiled to:
```javascript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var MyBase = (function () {
    function MyBase() {
    }
    MyBase.prototype.getValue = function () { return 1; };
    Object.defineProperty(MyBase.prototype, "value", {
        get: function () { return 1; },
        enumerable: true,
        configurable: true
    });
    return MyBase;
})();
var MyDerived = (function (_super) {
    __extends(MyDerived, _super);
    function MyDerived() {
        _super.call(this);
        var f1 = _super.prototype.getValue.call(this);
        var f2 = _super.prototype.value;
    }
    return MyDerived;
})(MyBase);
var d = new MyDerived();
var f3 = d.value;
```

**Comment by aleksey-bykov** [comment]
missed your point, `value` is a property accessor not just a property, your original complaint looks valid

**Comment by RyanCavanaugh** [comment]
See #338

**Comment by wgebczyk** [comment]
Please do not close this as I'm targeting ES6.
Is there anything in ES2015 that prevents from using super.<base class field/property>?

**Comment by RyanCavanaugh** [comment]
Good point - we should at least allow this in ES6

**Comment by wgebczyk** [comment]
Thanks!

**Comment by vladima** [comment]
#5860 lifts the restriction for ES6, we still need a separate proposal for the downlevel emit

**Comment by tbebekis** [comment]
var GetPropertyDescriptor = function (o, PropName) {
        if (o !== null) {
            return o.hasOwnProperty(PropName) ?
                  Object.getOwnPropertyDescriptor(o, PropName) :
                 GetPropertyDescriptor(Object.getPrototypeOf(o), PropName);
        }

        return null;
    };


return  GetPropertyDescriptor(base, 'Name').get.call(this);      // getter call
GetPropertyDescriptor(base, 'Name').set.call(this, v);          // setter call

**Comment by jsep** [comment]
Maybe a bit late,  but I was able to access `super.<getter/setter>` using bracket notation. `super['value']`.

**Comment by thw0rted** [comment]
@jsep this is very helpful, do you have any idea why the index operator is allowed but calling `super.value` directly is an error?
