### ISSUE TITLE
Auto-imports from within jsx don't work

### ISSUE THREAD

**Issue by selrond** [microsoft/TypeScript#44657]
Auto imports inside jsx stopped working on the latest stable release - worked before.
When I try to use auto import, it show correct info about the identifier, but no way to auto import it:

<img width="590" alt="screencap-Code--2021-06-11--11-00-10" src="https://user-images.githubusercontent.com/6603389/121661239-4b32cd80-caa4-11eb-99dd-e0b586666cf9.png">

However, whn I use auto import outside of jsx, it works (shows correct path and auto-imports on confirm):

<img width="575" alt="screencap-Code--2021-06-11--11-01-32" src="https://user-images.githubusercontent.com/6603389/121661390-71586d80-caa4-11eb-97dc-2e8eca2d827c.png">

Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.57.0
- OS Version: Darwin x64 19.6.0 (Catalina 10.15.7)

Steps to Reproduce:

1. Open any react component
2. Try to use auto import inside jsx

**Comment by mjbvz** [comment]
@andrewbranch Can you help take a look at this issue? We've seen a few reports on the VS Code side after the TS 4.3 update

**Comment by Besuf** [comment]
Any news guys. Or should we rollback to previous version vscode?

**Comment by donni106** [comment]
we have the same issue. for us it helped to remove `"lib"` and `"target"` from tsconfig.json as well as having no `"extends": "expo/tsconfig.base"`.
this way the auto import worked again.
but...this causes other issues.

**Comment by selrond** [comment]
just tried what @donni106 mentioned, didn't seem to help at all

**Comment by selrond** [comment]
just tried what @donni106 mentioned, didn't seem to help at all

**Comment by iamvucms** [comment]
After I disable extension "JavaScript and TypeScript Nightly", it worked. Let's try !

**Comment by Besuf** [comment]
It;s working now on vscode June update

**Comment by Akbar-ATQ** [comment]
I too have the same problem, at first I try to delete path alias and it work, but then when I want to screenshot it, it don't work again, and after I try to include the path alias again, it work again, but only in certain file and not work in other file

![Code_4MXlb2gXFe](https://user-images.githubusercontent.com/82864938/130211546-2f08584f-34d4-4bbb-a415-42468cf7b85e.png)
![Code_EKtyBL4CCi](https://user-images.githubusercontent.com/82864938/130211597-2c24ec5b-d0ce-4b67-a078-8dfefd70f263.png)
![Code_8U0sSsyOND](https://user-images.githubusercontent.com/82864938/130211576-b98cf186-7be2-4cc8-8806-80ccb7832b01.png)

but after some time, it not work again
![Code_TKJkBg3cVp](https://user-images.githubusercontent.com/82864938/130213388-b2980f1e-e2e5-4b7e-9406-a66960478bb9.png)

**Comment by Akbar-ATQ** [comment]
it work again after I update the JavaScript and TypeScript Nightly extension

**Comment by iambestday** [comment]
it don't work again [Version: 1.68.1 ]
