### ISSUE TITLE
Add `module: es2022`

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#44653]
# Suggestion

## 🔍 Search Terms

es2022

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add `module: es2022` and allow top level await in it.

## 📃 Motivating Example

Top level await

## 💻 Use Cases

Not being required to set esnext.

Related to #44571.

**Comment by jimmywarting** [comment]
Yes please! 👍 

TS don't do a good job at figuring out if a file runs in a type module and have no understanding that top level await can be used or not. So i think it should just be enabled by default
```js
// index.js
var x = await Promise.resolve(0)
export default x
```

I'm trying to solve this without a tsconfig in plain javascript
possible with some jsdoc or other js Directives comments

But all i get is:
> Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher.

Is there some method to define that this file is executed as a esnext module somehow?

**Comment by DanielRosenwasser** [comment]
@jimmywarting that's a separate issue, this is just about having a stable target for top level await and regexp match indices.

**Comment by DanielRosenwasser** [comment]
@jimmywarting not yet, this will enable that by giving a stable target for your project.

**Comment by DanielRosenwasser** [comment]
Thanks @saschanaz!
