### ISSUE TITLE
Primitive type `boolean` does not work with conditional types

### ISSUE THREAD

**Issue by benkeil** [microsoft/TypeScript#44663]
# Bug Report

### 🔎 Search Terms

conditional type extends boolean 

### 🕗 Version & Regression Information

4.3.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwBiBXAdgY2ASwPZoB4BJAGigHkA+KAXiiKggA9gI0ATeKAN123agB+KAAoAlLWrkoALlEAnBCgA2wOUQk0pAbgBQujPkRQ0KALYAjCPNSYc+OXES2seQqcvWyvftTrjJKABvAF89DysbdFd8EQBGMT1DNGMLXFxlCABDNBd7NDjHBGRo-II0jOy0bz52P1FNalC9CsycvLc4kWB5FAhEgyNgKFaqjvwAJiLnUrcCACF0tuqeWvqArWCw3VH22cnu3v7tIA)

### 💻 Code

```ts
type TestFunction<I, O> = I extends void ? () => O : (result: I) => O;

const numberFunction: TestFunction<number, void> = () => {};
numberFunction(1);
const booleanFunction1: TestFunction<boolean, void> = () => {};
booleanFunction1(true);
const booleanFunction2: TestFunction<Boolean, void> = () => {};
booleanFunction2(true);
```

### 🙁 Actual behavior

Looks like the keyword `extends` does not work with primitive type `boolean` but with Class `Boolean` and also with primitive type `number`.

`TS2345: Argument of type 'boolean' is not assignable to parameter of type 'never'.`

### 🙂 Expected behavior

`booleanFunction2` should act like `booleanFunction1`

**Comment by MartinJohns** [comment]
`boolean` do work with conditional types, but they (intentional) are [distributive](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).

**Comment by anuraghazra** [comment]
Right, we can avoid distribution of types by wrapping it in a tuple. 

related to https://github.com/microsoft/TypeScript/issues/29368#issuecomment-453529532

```ts
type TestFunction<I, O> = [I] extends [void] ? () => O : (result: I) => O;

const numberFunction: TestFunction<number, void> = () => {};
numberFunction(1);
const booleanFunction1: TestFunction<boolean, void> = () => {};
booleanFunction1(true);
const booleanFunction2: TestFunction<Boolean, void> = () => {};
booleanFunction2(true);
```

**Comment by MartinJohns** [comment]
> Right, we can avoid distribution of types by wrapping it in a tuple.

As shown in the linked documentation.

**Comment by benkeil** [comment]
First of all thank you for pointing out. But can you please explain why boolean acts different and what exactly happens here?

**Comment by fatcerberus** [comment]
`Boolean` acts differently because, in practice, it’s treated as a union of `true | false`.  When a conditional type is applied to a type union, it “distributes” over the members of the union—think `Array#map()`.
