### ISSUE TITLE
`[key: string]: string` of interface sub prop not match type `Record<K, string>` when `K` is extends string

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#44662]
# Bug Report

### 🔎 Search Terms

 > TS2717 record type

### 🕗 Version & Regression Information

> `[key: string]: string` of interface sub prop not match type `Record<K, string>` when `K` is extends string

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/LAKAlgdgLgpgTgMwIYGMYAICCoDeoCQA5nAPYCuADgM4Bc6eI++A2gNYwCedVUckhAXW69+BAL4BuUGNChIsRKgyYAPAGl0MAB6wIAEyroefCIXQBeIyNMA+XAWLlqdBkzadhJwZ9GNJ02XBoeGQ0LHVNHRh9Q2N+CysvOxBXR0padAAlGBQSOD11ABpE-hspEBkQIA)

> Subsequent property declarations must have the same type.  Property 'groups' must be of type '{ [key: string]: string; }', but here has type 'Record<K, string>'.

### 💻 Code

```ts

interface A
{
	groups: {
		[key: string]: string
	};
}

interface A<K extends string = string>
{
	groups: {
		[key: string]: string
	};
}

interface A<K extends string = string>
{
	groups: Record<K, string>;
}

```

### 🙁 Actual behavior

> Subsequent property declarations must have the same type.  Property 'groups' must be of type '{ [key: string]: string; }', but here has type 'Record<K, string>'.

### 🙂 Expected behavior

> no error when `K` is extends string

**Comment by RyanCavanaugh** [comment]
These are indeed different. I'm not sure what else to add.
