### ISSUE TITLE
Change else clause to never in ReturnType

### ISSUE THREAD

**Issue by umireon** [microsoft/TypeScript#44669]
# lib Update Request

## Configuration Check

My compilation *target* is `es5` and my *lib* is `the default`.

## Missing / Incorrect Definition

The else clause of ReturnType is never reached because of the constraint so that it is reasonable to be never.

## Sample Code

```
type T10 = ReturnType<() => string>;  // string
>T10 : string

type T11 = ReturnType<(s: string) => void>;  // void
>T11 : void
>s : string

type T12 = ReturnType<(<T>() => T)>;  // {}
>T12 : unknown

type T13 = ReturnType<(<T extends U, U extends number[]>() => T)>;  // number[]
>T13 : number[]

type T14 = ReturnType<typeof f1>;  // { a: number, b: string }
>T14 : { a: number; b: string; }
>f1 : (s: string) => { a: number; b: string; }

type T15 = ReturnType<any>;  // unknown
>T15 : unknown // changed from any

type T16 = ReturnType<never>;  // never
>T16 : never

type T17 = ReturnType<string>;  // Error
>T17 : never // changed from any

type T18 = ReturnType<Function>;  // Error
>T18 : never // changed from any

type T19<T extends any[]> = ReturnType<(x: string, ...args: T) => T[]>;  // T[]
>T19 : T[]
>x : string
>args : T
```

## Documentation Link

https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype

## Changeset

I already made a changeset. I didn't know that a backlog issue is required to open a pull request.

https://github.com/microsoft/TypeScript/compare/main...umireon:returntype-never?expand=1

## Duplicates

A possible duplicate is #39584 but nothing is discussed there.

**Comment by Zzzen** [comment]
`any` makes sense here. It reduces noise when a type error is encountered. If it is replaced with `never`, there will be a lot of `Property 'xxx' does not exist on type 'never'.`, which may shadow the real error `Type 'xxx' does not satisfy the constraint '(...args: any) => any'.`

```ts
type SomeType = string

// Type 'string' does not satisfy the constraint '(...args: any) => any'.(2344)
let foo: ReturnType<SomeType>

// Property 'toLowerCase' does not exist on type 'never'.
foo.toLowerCase()
```

**Comment by MartinJohns** [comment]
I don't really see the purpose of this change.

Additionally I think `any` makes more sense. The `never` type explicitly says that the function does not return. But due to the type error you don't get a valid result, so you can't say this won't return and defaulting to `any` makes more sense.

**Comment by umireon** [comment]
I was really convinced.
I understood that `never` is for some statements of function execution and not for type errors.
