### ISSUE TITLE
When using Number.is*, the parameter's type is not inferred as number

### ISSUE THREAD

**Issue by til-schneider** [microsoft/TypeScript#44665]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Number.isFinite`, `Number.isInteger`, `Number.isNaN` and `Number.isSafeInteger`

## Sample Code

```typescript
function foo(value: number | null | undefined) {
    if (Number.isFinite(value)) {
        bar(value)   // value should be inferred as `number` here
    }
}

function bar (value: number) {
    ...
}
```

### Number.isFinite

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite

> This means only values of the type number and are finite return true.

### Number.isInteger

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

> If the target value is an integer, return true, otherwise return false.

### Number.isNaN

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

> This also means that only values of the type number, that are also NaN, return true.

### Number.isSafeInteger

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger

> A Boolean indicating whether or not the given value is a number that is a safe integer.

**Comment by til-schneider** [comment]
I created a PR that fixes the definition: #44664

**Comment by MartinJohns** [comment]
This is intentional and there are several existing issues regarding this. Type guards imply that the function matches for **all** values of the type, but that's not the case for these functions.

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript/issues/39090#issuecomment-644829480.

**Comment by til-schneider** [comment]
Unfortunately it doesn't work, see comments above or #44664.
