### ISSUE TITLE
Object Indexing with a Template String

### ISSUE THREAD

**Issue by hbiede** [microsoft/TypeScript#44675]
# Bug Report

### 🔎 Search Terms

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZuKBlAlgLwKYRgXhgbwCgYYALARgC4YBWABgBpiyAmagFhqZNIGYPGzUu2q8uQmqME8AbNRbiAvoUJQAngAcMMAAoAnEBux4iJADYYAbhjPVyMAD4wWjmL1ftXNVzIDchZUJQSFgAcwwoADFEVExovQAJDABDABMMPVwYAAp8GAtrMxhFan1DCABKXAA+eBj0LABtAANSABJ8AptFZoBdfyDwCBALADozEFDsgHIAFSwoaYYYcKj6uJBElPS9XPyrGztiiorfIA)

### 💻 Code

```ts
const fontSizes = {
  h1: 50,
  h2: 45,
  h3: 40,
  h4: 35,
  h5: 30,
  h6: 25,
}

type Props = {
  level: 1 | 2 | 3 | 4 | 5 | 6;
}

const getFontSizeForHeader = ({ level }: Props) => fontSizes[`h${level}`]; // error

console.log('Test', getFontSizeForHeader({ level: 1 }));
```

### 🙁 Actual behavior

When indexing an object with a template string, the template string is typed just as `string` instead of the proper union, causing an error and requiring a type cast or ts-ignore to rid.

### 🙂 Expected behavior

The template string typing to be used to check for valid indexing

**Comment by MartinJohns** [comment]
I think you want #26797 / #44512.

**Comment by ahejlsberg** [comment]
With #44512 we will indeed give template literal types to template literal expressions in index positions. Meanwhile, it works with an explicit const assertion `` `fontSizes[`h${level}` as const]` ``.
