### ISSUE TITLE
type inference of promise that  recursive return itself 

### ISSUE THREAD

**Issue by TomVista** [microsoft/TypeScript#44679]
# Bug Report

### 🔎 Search Terms
type inference

promise

recursive

### 🕗 Version & Regression Information

TS 4.4.0-dev

### 💻 Code

```ts
var a

type Test = Promise<Test | number>

function test():Test {
  return new Promise((res, rej) => {
    if (a == true) {
      res(1)
    } else { rej() }
  }).then(() => {
    return 1
  }).catch(() => {
    return test()
  })
}
```
### 🙁 Actual behavior

test return ``type Test Promise<Test | number>``

### 🙂 Expected behavior

test return ``type Test Promise<number>``

**Comment by TomVista** [comment]
I may have got something wrong,I'll turn it on if necessary

**Comment by MartinJohns** [comment]
You can't return a promise in a promise in JavaScript.

**Comment by TomVista** [comment]
@MartinJohns 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

```
When a nextValue is a promise, the effect is a dynamic replacement. The return causes a promise to be popped, but the nextValue promise is pushed into its place. 
```

actually ``test`` return a any ,if not def a type ``type Test Promise<Test | number>``
![image](https://user-images.githubusercontent.com/42435611/122863778-00dc0700-d356-11eb-930b-0cfdb224b429.png)

promise that return itself has wrong type inference

**Comment by RyanCavanaugh** [comment]
The OP shows a function with an explicit return type annotation, and we don't ever modify return type annotations to a narrower type as a result of inference (this would be bad). I'm not really sure what's being proposed or described in the screenshot, which I am not going to transcribe to investigate.
