### ISSUE TITLE
Generic type self reference

### ISSUE THREAD

**Issue by juanrgm** [microsoft/TypeScript#44672]
# Bug Report

### 🔎 Search Terms

- Generic type self reference
- Recursive generic type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "generic type self reference"

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygHgFCMQFURQA9UwATNRAb1z0QG0BpRGJAaxQE85gCBdAFyIAFHABGAKxTRh+ADSJOXYU0WhIc5vwCUiALwA+ROHZg4AdzABuOgF9shsVJlQ5e2ngBOKKCC9IEtLQtg7YqBginogAhsLOwVCKyurgEHpGNHR4APQ5iEGuwtQO9Ih5StzCAEQx1dnl+RoQwqbmVvbydOLxhdDJ3KmQGcbRufl9bjSl9BXKNeL1ZRXNrWBmlmCd2HY61kA
### 💻 Code
```ts
function test<
  T extends {
    [K in keyof T]: (object: T, key: K, returnValue: ReturnType<T[K]>) => unknown;
  }
>(object: T) {
  return object;
}

test({
  a: (object, key, returnValue) => {
    // object: {}
    // key: "a"
    // returnValue: any
    return 1
  },
  b: (object, key, returnValue) => {
    // object: {}
    // key: "b"
    // returnValue: any
    return true
  },
});
```
### 🙁 Actual behavior

```ts
test({
  a: (object, key, returnValue) => {
    // object: {}
    // key: "a"
    // returnValue: any
    return 1
  },
  b: (object, key, returnValue) => {
    // object: {}
    // key: "b"
    // returnValue: any
    return true
  },
});
```

### 🙂 Expected behavior

```ts
test({
  a: (object, key, returnValue) => {
    // object: { a: ..., b: ... }
    // key: "a"
    // returnValue: number
    return 1
  },
  b: (object, key, returnValue) => {
    // object: { a: ..., b: ... }
    // key: "b"
    // returnValue: boolean
    return true
  },
});
```

**Comment by RyanCavanaugh** [comment]
I don't see a way to solve this without using unification, since any reference to `object` in the function body would induce a circularity. See #30134
