### ISSUE TITLE
Can't stop typescript compiler from walking up parent directories in nested project

### ISSUE THREAD

**Issue by clifton** [microsoft/TypeScript#44685]
hi, #13992 was locked so i am reopening. when using nested directories for deploys (e.g. when deploying [firebase functions](https://firebase.google.com/docs/functions)), the typescript compiler will walk up the parent directory and throw compilation errors on unrelated node modules.

have to resort to using solution from https://github.com/Microsoft/TypeScript/issues/13992#issuecomment-386259930
```json
  "scripts": {
    "build": "if [ -d ../node_modules ]; then mv ../node_modules ../node_modules_tmp; fi; <normal build command here>; if [ -d ../node_modules_tmp ]; then mv ../node_modules_tmp ../node_modules; fi",
  }
```

**Comment by RyanCavanaugh** [comment]
Please provide concrete steps to reproduce the problem. Thanks!

**Comment by tchakabam** [comment]
I think this happens when tsc looks for `@types` patterns for some reasons.

I had the issue with a nested project where errors came up only from the parents project node_modules/@types/... files.

@clifton My Solution: Put `"typeRoots": []` in tsconfig `compilerOptions`

**Comment by tchakabam** [comment]
@RyanCavanaugh Still considering there is some kind of issue here with `tsc` however.

Cant we make this more straight-forward like `gcc` or so, it should just compile. it seems be doing a lot of background-magic not even you guys still have oversight of really tbh? :)

**Comment by wlinna** [comment]
@RyanCavanaugh 

> Please provide concrete steps to reproduce the problem. Thanks!

Here's an easy way to reproduce the problem with minimal setup / code.
1. Unzip
2. Open  command line in the directory `nested`
3. Run `tsc` . The compilation succeeds
4. Now open the parent directory
5. Run `npm i`
6. Go back to  the directory `nested`
7. Run `tsc`. It now gives the following error among many others

```
timer.ts:1:14 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

1 export const timer: number = setTimeout(() => console.log('hello, world'), 500);
```

[ts_parentdir_problem_repro.zip](https://github.com/microsoft/TypeScript/files/14083789/ts_parentdir_problem_repro.zip)

It appears there's now way to prevent `tsc` from confusing the current project with the parent parent project without  introducing composite projects. I also tried `"disableSolutionSearching": true` but that doesn't help. Sure I could try hacks that have been introduced here, but my intuition is that a project  should not interact with parent directories unless it has `composite: true` or something like that.

**Comment by RyanCavanaugh** [comment]
This is intentional behavior because `types` is populated from whatever the apparent local `node_modules` array is. Add `"types": []` to the inner tsconfig to prevent it.
