### ISSUE TITLE
Discriminated Unions with a common partially optional property

### ISSUE THREAD

**Issue by nmalyschkin** [microsoft/TypeScript#44689]
# Bug Report

### 🔎 Search Terms

Discriminated Unions with a common partially optional property

### 🕗 Version & Regression Information

- I tried different versions of 3 and 4.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.4#code/JYOwLgpgTgZghgYwgAgELIN4FgBQzlwBcyYUArhANy74BGxIZAtrdNTgL66iSyIoBhTDQIB+YvAA2AZyoiEDZqyjsuOMAE8ADigCqIYAHsQyALxpkAH2QD2uBMelgSEJwEZi+oyfPY8BCTgZCAAaeWIAVjDOdgcQJxcnACZPA2MzYX8FZAAWaI5Yx2dIJwBmVO8Mv3wiEnJQkXpc-ML44tcwHIr030biPPDm3ALcIA)

### 💻 Code

```ts
interface B {
  a: true;
  b: number;
}
interface C {
  a?: false;
  c: number;
}
type Union = B | C;

const test1: Union = {
  a: false,
  c: 5,
};
const test2: Union = {
  c: 4,
};
const test3: Union = {
  a: true,
  b: 4,
};
const test4: Union = {
  b: 4,
  c: 4,
};
```

### 🙁 Actual behavior

`test4` is displayed as valid.

### 🙂 Expected behavior

`test4` should not be valid.

**Comment by MartinJohns** [comment]
`test4` is valid. All properties that must exist according to the interface are present, and no incompatible properties exist.

**Comment by whzx5byb** [comment]
It is unrelated to discriminated unions or optional property. A minimal repo:
```ts
interface B {
  b: number;
}
interface C {
  c: number;
}
type Union = B | C;

const test1: B = { b: 4, c: 4 }; // Error as expected, because of excess property check.
const test2: C = { b: 4, c: 4 }; // Error as expected, because of excess property check.
const test3: Union = { b: 4, c: 4 }; // No error.
```

See https://github.com/microsoft/TypeScript/issues/20863

**Comment by nmalyschkin** [comment]
@whzx5byb
Thank you, that worked for me!
