### ISSUE TITLE
Overriden properties in jsdoc annotation are not picked up in declaration file

### ISSUE THREAD

**Issue by simonseyock** [microsoft/TypeScript#44693]
# Bug Report

### 🔎 Search Terms

typescript jsdoc declaration override method property signature

### 🕗 Version & Regression Information

- This changed between versions  3.8.3 and 3.9.7.

### ⏯ Playground Link

[Example JavaScript with JSDoc](https://www.typescriptlang.org/play?strictFunctionTypes=false&ts=4.3.2&filetype=js#code/PQKhFgCgAIWgBALgTwA4FMAm6Bm0CCUsCqATgPYakrQDeAzoqQJYB2A5gL7QCGRIwKFFAQYcJGiy5oAIX4kKVGrVYBXALYAjdKW6b+gyFADGAGx716si+jpFoDkfYfEJGOvk7OHA7wDceU1V0AG4oLyNIMwsrABV0Rmh0AA9EdFZMKxkbOxgXJzyXcRR3WnxoADJZCJcfQ1qAoNDwoSjyVkTEaABeaFZ0AHdoeMYACgBKMMggA)

### 💻 Code

```js
/**
 * @typedef A
 * @property {string} a
 */

/**
 * @typedef B
 * @property {number} b
 */

class Base {
    /**
     * @type {A}
     */
    value;
}

class Test extends Base {
    /**
     * @type {A & B}
     */
    value;
}
```

### 🙁 Actual behavior

The declaration file does not contain a typing for the narrower type for value in class Test.

```
declare class Test extends Base {
}
```

### 🙂 Expected behavior

The declaration file should contain the narrower type for value.

```
declare class Test extends Base {
    /**
     * @type {A & B}
     */
    value: A & B;
}
```

**Comment by ahocevar** [comment]
This bug is especially problematic when creating APIs with function overloads for event register functions, because it breaks what has been described in https://github.com/microsoft/TypeScript/issues/25590#issuecomment-561493756.

**Comment by simonseyock** [comment]
I am trying to `git bisect` this bug but I am not able to build older versions of typescript or to run tests on older versions. Does this have to do with the dependency versions? Could someone give me pointer?
