### ISSUE TITLE
conditional compilation

### ISSUE THREAD

**Issue by lengyuxuan** [microsoft/TypeScript#44691]
# Suggestion

Is it possible to support conditional compilation instructions similar to those in C language?

## 🔍 Search Terms

conditional compilation

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Before:

```typescript
import * as os from 'os';

const osType = os.type();

if (osType.includes('Windows')) {
  // win code
} else if (osType.includes('linux')) {
  // linux code
} else {
  // ...
}
```

Result:

```javascript
"use strict";
exports.__esModule = true;
var os = require("os");
var osType = os.type();
if (osType.includes('Windows')) {
    // some code
}
else if (osType.includes('linux')) {
    // other code
}
else {
    // ...
}
```

After support, it looks like:

```c
#if OS_TYPE === windows
// win code
#elif OS_TYPE === linux
// linux code
#else
// ...
```

compile:

```shell
tsc --xxx OS_TYPE=windows
```

Restul:

```javascript
"use strict";
exports.__esModule = true;
// win code
```

**Comment by MartinJohns** [comment]
Please fill out the issue template for feature requests.

**Comment by RyanCavanaugh** [comment]
A C-style preprocessor has indeed been suggested in at least one of the prior 40,000 issues 😅. See #449

**Comment by MartinJohns** [comment]
#4671 and #449 using C-style, #3538 using constants in the config. Search terms `conditional compilation in:title`.
