### ISSUE TITLE
Copyright Notice in License is missing

### ISSUE THREAD

**Issue by divyank-vwits** [microsoft/TypeScript#44692]
For companies that use this library, it is important to understand who is the copyright holder.
In the license file that is attached, the copyright holder is not clearly stated but it is still kept as the template value.

It would be great if you could add the name(s) of the copyright holder such that the legal situation gets clarified properly.

**Comment by RyanCavanaugh** [comment]
I checked various other Apache-licensed projects and none included the copyright holder in the `LICENSE` file itself. Our copyright file is clearly posted on both the top-level of the repo as well as at the top of each distribution file and in the containing npm package file, see 
https://github.com/microsoft/TypeScript/blob/main/CopyrightNotice.txt

**Comment by philwebb** [comment]
@divyank-vwits I see you've opened this issue in many repositories. I suspect most will consider the issue invalid for the [reasons given here](https://github.com/spring-projects/spring-boot/issues/27021). In the future, you might want to wait for a response before opening duplicate issues.
