### ISSUE TITLE
"infer" type failing when matching on type parameter

### ISSUE THREAD

**Issue by jhbertra** [microsoft/TypeScript#44709]
# Bug Report

### 🔎 Search Terms

- infer
- unknown
- extraction
- index signature
- type parameter

### 🕗 Version & Regression Information

first seen in typescript@4.3.4
still occurs in typescript@4.4.0-dev.20210622

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types

### ⏯ Playground Link

I wasn't able to get the package dependencies to work in the playground
[minimal github repo](https://github.com/jhbertra/conditional-infer-demo/tree/main)

### 💻 Code

```ts
import { Kind, URIS } from "fp-ts/lib/HKT";
import * as O from "fp-ts/lib/Option";

type Unlift1<F extends URIS, H> = H extends Kind<F, infer A> ? A : never;
type Unlift0<F extends URIS> = O.Option<number> extends Kind<F, infer A> ? A : never;

type T = Unlift1<O.URI, O.Option<number>>;
type S = Unlift0<O.URI>;

declare const t: T;
declare const s: S;

// Expected: T = number
// Actual: T = unknown
// Error: TS2322: Type 'unknown' is not assignable to type 'number'.
const tAsS: S = t;
const sAsT: T = s;
```

### 🙁 Actual behavior

In the example above, the type `T` is different from the type `S` even though the only change is passing in `O.Option<number>` as a type argument vs. hard-coding it. `T` ends up being `unknown` while `S` is `number`.

### 🙂 Expected behavior

I would expect both `T` and `S` to be `number`.

**Comment by RyanCavanaugh** [comment]
The `fp-ts` types are very difficult to reason about; we'd need a repro that doesn't have dependencies to investigate further.

**Comment by RyanCavanaugh** [comment]
Info not provided.
