### ISSUE TITLE
The same generic type can infer to different values in a single type variable list

### ISSUE THREAD

**Issue by grandivory** [microsoft/TypeScript#44711]
# Bug Report

### 🔎 Search Terms

* generics
* infer generics
* generics infer different values

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt0B4AqA+ZAbwFgAoZZGTALmRzIF8yyYBXEBMYdESzXPAAowtHAEpaGbPiJkKUCGFZRehZACIq6dbTDIGAbkbNSoSLEQoAQnCi4ANGmQQAHpBAATAM5p++AiTkyABGtpLGpCzsnNy8oXY4jqjObhCePlICQjCSEsg2CUkBcsgKSipEGvE6lPpGpEyRpGAAngAOKACiblCIYFI4WMmu7t6+2HAgLXgEALxOI2ljmaAw0HQEAPx0yLQgEABu0PWtHcjdYL2cBYNWKaM+BViTLY4vM8jzd4vp+bZYq3WiWQ72Q2xwu2Q+yOUHqZAQPC8ej08wALAAmAzIAD02OQGOQAFpkABzBRwMAAQnhiL0ME+fHQwjEWNx4ywIFYAFtgtACMSAFasJGUUAQamkBEgEXBBnxQQwFk4vFPdgAaxA6AA7iAkvxOTy+fzkAALVgmzYmU4oLQQ+YXK79TCDa3oekwPCsvE4E3AHxa9BQNU+GBisjWkK2O3nHp9G5YV304Ke5V0X0+BReVgAGzAPlAGnVmp16hMbJ9NvQ2ez2tAJOQAaDPjgzYbgbVtnQ7A84faXVj1yj6Kw31SvyeLzeUw+X3uS0e-0nyEBUDQWxjlz6AyGBD2h2OvbO8Rw6IZDrjQ4TfbdIU9ZCAA)

### 💻 Code

```ts
interface Foo<T> {
  foo: T
}

function foo<T>(t: T): Foo<T> {
  return { "foo": t };
}

interface Bar<T, F extends Foo<T>> {
  bar: F
}

function bar<T, F extends Foo<T>>(f: F): Bar<T, F> {
  return { "bar": f };
}

type ExtractFooT<F extends Foo<any>> = F extends Foo<infer T> ? T : never;
type ExtractBarT<B extends Bar<any, any>> = B extends Bar<infer T, any> ? T : never;

const t = 42; // 42 - great!
const f = foo(t); // Foo<number> - just fine!
const b = bar(f); // Bar<unknown, Foo<number>> - huh? T is both "unknown" and "number"

type fooT = ExtractFooT<typeof f>; // This works fine
type barT = ExtractBarT<typeof b>; // This results in "unknown"

// The following works as a workaround
type ExtractBarT2<B extends Bar<any, any>> = B extends Bar<any, infer F> ? ExtractFooT<F> : never;
type barT2 = ExtractBarT2<typeof b>;
```

### 🙁 Actual behavior

In the above example, the type of `b` is `Bar<unknown, Foo<number>>`, so `T` is inferred as both `unknown` and `number` in the same type parameter list.

### 🙂 Expected behavior

`T` should be inferred to be a single type

**Comment by RyanCavanaugh** [comment]
Constraints aren't inference sites (doing this makes more things worse than it does better), so at `const b = bar(f)` there are no inference candidates for `T`, thus it will always infer to `unknown` in the absence of a contextual type. Usually want you want to write in this scenario is
```ts
function bar<T, F extends Foo<T>>(f: F & Foo<T>): Bar<T, F> {
  return { "bar": f };
}
```
