### ISSUE TITLE
Question: is it possible to put tsconfig.json file not in the root of the project?

### ISSUE THREAD

**Issue by irakliy81** [Microsoft/TypeScript#4471]
I am using VS Code for TypeScript projects and was wondering if it is possible to pace tsconfig.json file in the `.settings` directory created by VS Code (seems like it could be a good place to put a file with compiler settings).

I've tried to place the file in `.settings` and adjust the `outDir` option to point to the parent folder, but it doesn't seem to work.

Thanks!

**Comment by mhegazy** [comment]
You have two ways of managing the files included by your tsconfig.json, 1. do not include a `files` property, this implicitly include all files in the current folder and sub folders, and 2. include a `files` property, and this will include only the files listed.

In you scenario, you want to use the second way, and define a list of files. you would build using `tsc -p .settings\` to build.

Note that this setup is something that your editor does not expect. We recommend placing your tsconfig.json at the root. Editors always assume tsconfig.json is at the root. so you may run into some issues with your editor experience.

See https://github.com/Microsoft/TypeScript/wiki/tsconfig.json for more details on using tsconfig.json

**Comment by irakliy81** [comment]
Thank you for the quick response!
