### ISSUE TITLE
Generic classes with restricted type should recognize and accept Partial<T> data of the base type.

### ISSUE THREAD

**Issue by jozefchutka** [microsoft/TypeScript#44719]
# Bug Report

Generic classes with restricted type should recognize and accept Partial<T> data of the base type.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCA8AVaBTAHgFxQOwCYwBFYA+aAbwChppcwMwAuABTACcMBLMEJYgbgpVowAPbYIGVgFdgGEawAUASnJDqGABYcIAOlr1oAXnKMARGFMBfAdUsU7FUJBgAhVJhz448IqUrVRcUkZOUUVf2poCCkABxQwm0jNbT06MCMTBnMrRLsHDABPOOgiDIjGCVYObABzATsgA)

### 💻 Code

```ts
class A<T extends DA> {
  data:Partial<T>;

  constructor() {
    this.data = {a:"a"};
  }
}

class B extends A<DA> {
  constructor() {
    super();
    this.data = {a:"a"};
  }
}

type DA = {
  a:string;
}
```

### 🙁 Actual behavior

Compiler complains on `Type '{ a: "a"; }' is not assignable to type 'Partial<T>'.`

### 🙂 Expected behavior

Compiler should be happy b/c any A extension will always have `a:string` property

**Comment by whzx5byb** [comment]
In `class A`, you have no knowledge of `T`, and T is possible to be a narrower subtype.

Your expected behavior will cause some runtime error like this:
```ts
let x: A<{a: 'foo'}> = new A();
let y = x.data.a;
// y: "foo" | undefined
// but in runtime it's value is 'a'
```

**Comment by fatcerberus** [comment]
> Compiler should be happy b/c any A extension will always have a:string property

Not necessarily.  `{ a: "b" }` is a valid subtype of `DA`.

**Comment by jozefchutka** [comment]
Thanks for an explanation, seems `string` was not a good example to present and should have used non-primitive object... 

Here in this example, can you please explain or confirm bug with `HTMLElement` for example.

`Type '{ a: HTMLDivElement; }' is not assignable to type 'Partial<T>'.`

```ts
class A<T extends DA> {
  data:Partial<T>;

  constructor() {
    this.data = {a:document.createElement("div")};
  }
}

class B extends A<DA> {
  constructor() {
    super();
    this.data = {a:document.createElement("div")};
  }
}

type DA = {
  a:HTMLElement;
}
```

[Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCA8AVaBTAHgFxQOwCYwBFYA+aAbwChppcwMwAuABTACcMBLMEJYgbgpVowAPbYIGVgFdgGEawAUASnJDqGABYcIAOlr1oAXnKNcI4FIC2ODDuCsUdFAFEQKa9gwKARLg4A3byUAXwFqYIoIilBIGAAhVEwcfDh4IlJKalFxSRk5RRVM6mgIKQAHFAKw4s1tPTowIxMGMwsPW3tHLFd3Gx8-QJDqiKiMAE8K6CImosYACUQAWQAZHvaBCKA)

**Comment by fatcerberus** [comment]
It's literally the same issue.

```ts
class C extends A<DB> {
  constructor() {
    super();
  }
}

type DB = {
  a: HTMLTextElement;
}
```

Oops, now you've assigned an `HTMLDivElement` to a property typed as `HTMLTextElement`, and this is legal because `DB extends DA` is true.

**Comment by jozefchutka** [comment]
hm, I am not sure your claim is true, here is another example, where it compiles all appart from the line 7:

```ts
class A<T extends DA> {
  data:Partial<T>;

  constructor(data:T) {
    this.data = data; // ok
    this.data.a = "a"; // ok
    this.data = {a:"a"}; // Type '{ a: "a"; }' is not assignable to type 'Partial<T>'.
  }
}

type DA = {
  a:string;
}
```

[Plaground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCA8AVaBTAHgFxQOwCYwBFYA+aAbwChppcwMwAuABTACcMBLMEJYgbgpVowAPbYIGVgFdgGEawAUteg0QBKckOoYAFhwgA6ZWGgBeGnTADq2vYeMGT5gERhn1m7v1HLZ8o1dnAF8PIIowigwATwAHFGgiP0pqRglWDmwAcwEwoA)

**Comment by jozefchutka** [comment]
@RyanCavanaugh can you please revisit before marking as "Working as Intended"

**Comment by fatcerberus** [comment]
The direct assignment to `this.data.a` being allowed is likely a bug because as I said above, `Partial<T>` may very well be `{ a?: "b" | "c" }`.  The error is definitely correct.
