### ISSUE TITLE
[webworker.d.ts] Missing `pushsubscriptionchange` event definition

### ISSUE THREAD

**Issue by wbobeirne** [microsoft/TypeScript#44729]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

`ServiceWorkerGlobalScopeEventMap` is missing an entry for `pushsubscriptionchange`.

## Sample Code

```ts
self.addEventListener('pushsubscriptionchange', event => {
    event.waitUntil(resubscribePush());
          ~~~~~~~~~
          Property 'waitUntil' does not exist on type 'Event'.
});
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event

**Comment by MartinJohns** [comment]
It's probably not there because there's close to no browser support.

**Comment by andrewbranch** [comment]
Yep. Please come back if/when it’s widely supported and we can reopen. In the meantime, you can always [augment the types](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) yourself. Thanks!

**Comment by HuHguZ** [comment]
> Yep. Please come back if/when it’s widely supported and we can reopen. In the meantime, you can always [augment the types](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) yourself. Thanks!

But it works for the most popular chrome browser, is that not a reason to return this event back?

**Comment by MartinJohns** [comment]
@HuHguZ According to the browser compatibility of MDN it's still not supported for Chrome:

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event#browser_compatibility

**Comment by dstaley** [comment]
@andrewbranch What browsers need to support a feature to warrant its inclusion?
