### ISSUE TITLE
Immediately-Invoked Arrow Function Expressions

### ISSUE THREAD

**Issue by jonathansampson** [Microsoft/TypeScript#4472]
```js
()=>{}();
```

The above _does not_ result in the invocation of the anonymous arrow function.

TypeScript's Playground presently generates the following output:

```js
(function () { });
();
```

Babel, for contrast, generates the following output:

```js
(function () {})();
```

It is perhaps worth noting that [Esprima doesn't like this syntax](http://esprima.org/demo/parse.html?code=()%3D%3E%7B%7D()%3B).

cc @jdalton

**Comment by RyanCavanaugh** [comment]
Generally you shouldn't use (or even look at :wink:) any js generated in the presence of TypeScript syntax errors; it's unlikely to work.

In a compliant ES6 runtime, this is a syntax error. Babel's doing you a misfavor by parsing this without error.

**Comment by DanielRosenwasser** [comment]
Specifically, in the ES6 spec, the production in question is *CallExpression*, whose target is `super`, a *MemberExpression*, or another *CallExpression*. An *ArrowFunction* can never be derived from these productions, so this code is not valid, and is probably a bug on Babel's end

**Comment by jdalton** [comment]
Trying to map similar IIFE patterns like `(function() { }())` to arrow functions

```js
// will error in environments.
(() => {
    console.log('hi');
}())
```
but in TypeScript will produce:
```
// logs 'hi'
(function () {
    console.log('hi');
})();
```

**Comment by jdalton** [comment]
\\c @bterlson

**Comment by jdalton** [comment]
Related to https://github.com/babel/babel/issues/2118.

**Comment by jmm** [comment]
@DanielRosenwasser Yes, that is a known bug in Babel (linked by @jdalton). So, for people wanting to do this the solution is simply to wrap the `ArrowFunction` in parens making it a `MemberExpression`, right:?

```js
(() => {})();
```

**Comment by DanielRosenwasser** [comment]
@jmm correct.

**Comment by jmm** [comment]
@DanielRosenwasser Awesome, thanks.

**Comment by gndx** [comment]
thanks :)
