### ISSUE TITLE
Rename Symbol(F2) failed to rename the value in `switch` statement when operate on union of string literal

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#44720]
# Bug Report

### 🔎 Search Terms

rename symbol string literal union
Similar to https://github.com/microsoft/TypeScript/issues/44701

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210622#code/C4TwDgpgBAysCGxoF4oHIB2B7YBaAThPACYhpQA+6hJZA3AFAD0TUb7HnX3Aes690FCoYAK7AowABbQAxqPwBnLPigzCAGhGFFiqADEATFHgZiUQhngBbaAAMapO5KxQ7WANZ2AdA1kAbeF0oAEEoAG8GDkUEJAAuWFiUdGw8R3oGKPZRMGJECAAKAEoIrK4ASwAzKALpcsVvGPyoZFbqIlI0EsjhNjLOAF9+oYGgA)

### 💻 Code

```ts
type State = 'not-ready' | 'ready';
//                            ^
//                          put the cursor here, press F2 and rename `ready` to `ok`.
class A {
    state: State = 'not-ready';

    update() {
        switch (this.state) {
            case 'ready':
        }
    }
}
```

### 🙁 Actual behavior

```ts
type State = 'not-ready' | 'ok';
class A {
    state: State = 'not-ready';

    update() {
        switch (this.state) {
            case 'ready':
            // Type '"ready"' is not comparable to type 'State'.(2678)
        }
    }
}
```

### 🙂 Expected behavior

```ts
type State = 'not-ready' | 'ok';
class A {
    state: State = 'not-ready';

    update() {
        switch (this.state) {
            case 'ok':
        }
    }
}
```

**Comment by dimitriskot** [comment]
Hi there!
same thing, when using with Template Literal Types.
if put in `case` statement any interpolated expression, then typechecking doesn't work.
[https://www.typescriptlang.org/play?#code/KYOwrgtgBAogjFA3gKCmqAxA8lqBeKAImy0IBpV0AhAQQCV8ja7zkBfZUSWAJiUrS0AWo0LDWHLtBgBmfuigBlLAFkYAFQASASQByAcVHK1WvfonJkAFwCeAB2BR1jAAYASRPDYA6DzB5sLgDclgBmYCAAxlYAlgD2IFAAzgDuMVaRABYxIADmABQA+gCGAE65AFxOAJRVAG5xMQAm8uip6VlQRWW51a0KaJHFSY7unnCBVQBGpcDFANYhA+hDI1Bj-pNQM3OLAgOro34yWzsLS+gcbEA](ts playground)
