### ISSUE TITLE
Multiple and wrong definition

### ISSUE THREAD

**Issue by timsofteng** [microsoft/TypeScript#44726]
Hello. I use typescript-language-server with neovim native lsp.
When I'm trying to go to definition it works but it also opens quickfix-list with two files with right one and another strange file something like that
node_modules/@types/react/index.d.ts|547 col 9| (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
![image](https://user-images.githubusercontent.com/51912173/123290124-b1463880-d519-11eb-9979-6b3e09bcc742.png)
My definition is UsageAndPlan constant which returned as well but with wrong one definition.

Here is closed issue in nvim repo. So problem is in server.
https://github.com/neovim/neovim/issues/14713
https://github.com/theia-ide/typescript-language-server/issues/216

**Comment by RyanCavanaugh** [comment]
Please include steps to reproduce this in an editor within our control (VS, VS Code)
