### ISSUE TITLE
Azure CDN multiple CDN 

### ISSUE THREAD

**Issue by kethasid** [microsoft/TypeScript#44721]
I'm trying to use Azure CDN for azure static website through storage accounts and azure app service for our frontend. In the configuration part we are unable to configure origin for storage and web app in one endpoint. 

Wanted to know if  there is a possibility of configuring both the origins in the same endpoint or we have to create different endpoints for each of the above origins.

**Comment by orta** [comment]
I'm afraid this is the issues for the TypeScript programming language - I think you're looking for the docs for Azure Static Webapps: https://docs.microsoft.com/en-us/azure/static-web-apps/overview
