### ISSUE TITLE
Go-to-def on `override` should navigate to the overridden method

### ISSUE THREAD

**Issue by uniqueiniquity** [microsoft/TypeScript#44736]
# Suggestion

## 🔍 Search Terms

override, definition

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When writing an overriding method, I want to be able to easily jump to the method that I'm overriding for several reasons (making sure I'm doing it right, viewing implementation differences, etc). Right now, in VS Code, I have to go-to-def on the method name, which shows me all references and other implementations of the method from other subclasses. 

It seems like a good way to arrange this would be to have go-to-def requests that are triggered on the `override` keyword to have this behavior. I haven't fully thought through whether there might be a case where you'd have several targets, but it seems reasonable to just provide all of them for the editor to manifest how they wish. 

I actually expected this to work because this is the behavior for `override` in C# in VS.

## 📃 Motivating Example

See above.

## 💻 Use Cases

See above.

**Comment by Kingwl** [comment]
Hey @a-tarasyuk. I saw you have liked this issue. Are you already or planning start work on this?

**Comment by a-tarasyuk** [comment]
@Kingwl I'm preparing PR, I think it will be done in an hour :).
