### ISSUE TITLE
Make it easier to programmatically detect errors

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/TypeScript#44749]
# Suggestion

## 🔍 Search Terms

json programmatic api errors output format

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

To support codemod tools, I'd like the ability to programmatically find type errors in my code. This could be accomplished by adding a flag like `eslint`'s `--format json`, bunyan's JSON output, or various test runners that have JSON reporters. Or, there could be a simple programmatic API users could call. (I found https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API but it's not quite what I need.)

## 📃 Motivating Example

I made a change that reveals a bunch of type errors. Now I'd like to write a codemod that uses that the information in those type errors to automatically fix them all.

## 💻 Use Cases

Workaround: string parsing the output of `tsc`. 😦

**Comment by RyanCavanaugh** [comment]
>  I'd like the ability to programmatically find type errors in my code [...] I found https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API but it's not quite what I need

There's a very robust compiler API that gives you back the raw, non-stringified diagnostics, upon which you can do whatever you like. What was missing from the compiler API that you needed?

**Comment by NickHeiner** [comment]
Maybe just better docs. :smile: I spent 20 minutes using those docs and inspecting `require('typescript')` in the REPL trying to figure out how to do this, without success. Then I gave up and was able to parse the text output in about 90 seconds.

**Comment by andrewbranch** [comment]
@NickHeiner I’d also recommend looking at https://www.npmjs.com/package/@ts-morph/bootstrap—it abstracts away a lot of the details and boilerplate of getting up and running with the compiler API. Another strategy for exploring the compiler API would be to skim/search through https://github.com/microsoft/TypeScript/blob/main/lib/tsserverlibrary.d.ts, as it has every public interface, method, property, and class in a single file. A lot of the methods on `LanguageService` and `Program` have decent doc comments, and those are typically going to be your entrypoints into all the info you could want from the compiler.

**Comment by andrewbranch** [comment]
There’s also a #compiler-api channel in the [TypeScript Community Discord](https://discord.gg/typescript) 😄

**Comment by Zzzen** [comment]
Checkout ts-migrate. It has many plugins that does exactly what you mentioned.

**Comment by NickHeiner** [comment]
Ok, I'll check out all of this. Thanks! 

For this time, I was saved by how wonderfully regular the plain text output is. :smile:
