### ISSUE TITLE
using prop name in for..in loop yields an error

### ISSUE THREAD

**Issue by DaniBr** [microsoft/TypeScript#44742]
# Bug Report

### 🔎 Search Terms

prop name in for..in loop 

### 🕗 Version & Regression Information

- Error appears at versions 4.3.4, 3.9.2, and 3.3.3.
I didn't check it on other versions.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play#code/PTAEGcAsHsFcBsB2ByALqARgU1AQ0QJ6hYBOJ0JAUAGayIDGqAltIqKAA4lOKoAK5DqVQEAarniws4APLVQACmgYAVgC4ZqrIwCUoAN6UAkNQqL4WdF2gcA0liI9QylXsNGj9VuCuDx8UABeZ1UAbWs7BwBdAG5jIyZ5BREhaHkI-1AAQmDkWgZmVmQ9L0RwaAsAOnhoAHNFDIkdOKMAX0pWoA)

### 💻 Code

```ts
function  printPropertyValuesOf (obj:Object) {
    for (let propKey in obj) {
        const propVal = obj[propKey]; // shouln't be any error in this line
        if (typeof propVal != 'function') console.log (propVal);
    }
}
```

### 🙁 Actual behavior

Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Object'.
  No index signature with a parameter of type 'string' was found on type 'Object'.(7053)

### 🙂 Expected behavior

Shouldn't be any problem, because propKey is in obj, so it's for sure an existing property of obj.

**Comment by MartinJohns** [comment]
See #44706 any many others.

**Comment by RyanCavanaugh** [comment]
Side note, don't use `Object`.
