### ISSUE TITLE
Make it easy to export declared external as named export

### ISSUE THREAD

**Issue by thejohnfreeman** [microsoft/TypeScript#44744]
# Suggestion

## 🔍 Search Terms

export named external

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Make `export declare $name: $type` emit `export {$name}` when compiled to an ES module (and the equivalent of that for other targets).

## 📃 Motivating Example

A declared external value can [presently](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPCgK4C2ARiDALABQIAHgA5IxajZTERa5JA) be exported as default:

```ts
// TypeScript
declare const foo: number
export default foo
```

```js
// ES2015
export default foo
```

And it can be exported as a named export with this [syntax](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPCgK4C2ARiDALABQIAHgA5IxYDeOe8AvkA):

```ts
// TypeScript
declare const foo: number
export { foo }
```

```js
// ES2015
export { foo }
```

But it cannot be exported as a named export with this [syntax](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AYwDYEMrDsiA7AZ3gDMIIAuOPAVwFsAjYKIA):

```ts
// TypeScript
export declare const foo: number
```

```js
// ES2015
export {}
```

I expected the same output as the second example.

## 💻 Use Cases

The use case is that I have sources from project A that are dependencies of project B (a plugin for the project A). To use Rollup for B, every imported TS module needs to be compiled to an ES module. The ES module can just be a bunch of exports of global variables. If I use `export declare` in A to try to export those global variables, they are missing from the compiled ES module. If I try to use `export const foo`, then TypeScript [complains](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wGYQgLjsgVwFsAjYKIA) that `foo` is not initialized.

If I emit declaration files for the modules in A, they are loaded with `export declare ...` declarations. But to get those to work with Rollup as dependencies of B, I have to modify the source (either collect all the exports into one `export { ... }` at the end, or add one `export { name }` under every single `export declare name`).

**Comment by RyanCavanaugh** [comment]
`declare` means "no emit" for that declaration, so tsc is doing exactly what you tell it to do.

**Comment by thejohnfreeman** [comment]
I see. Where is that written in the handbook? I've spent so much time trying to study this issue, and never came across that explanation.
