### ISSUE TITLE
Nested Homomorphic Recursive Type with Intersection behaves like Record<string, uknown>

### ISSUE THREAD

**Issue by valeneiko** [microsoft/TypeScript#44750]
# Bug Report

### 🔎 Search Terms

* Recursive
* Nested
* Conditional
* Homomorphic mapped type

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7
- Also reproducible in: 4.3.4, 4.4.0-dev.20210625

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.4#code/C4TwDgpgBAShCOBXCBnYUC8UDeUA2AjAFw74BMJARgPbV4QCGAdlAL5sDcAUKJFAKIAPBgFsw9ADwAVAHyZSEQQH4SUqAB8oTRHjycuXAPSGoAEQgAzAJZMrwK9SYoowABYN0AJwhhP1ACaIAMbQbtCUiADmPODQAMpBrhAiDNJyWAAUaorAEEz+zjR0jCxKpLwQJADkRfTMVRxsUCS4vtRgKC1QANoAClA2UADWECDUFlBSALokCUkp0n1TcqyNrACUUABkAsJikrLcxhVQc8mpsvJZUDl5BVC1JVBluBXVj-VrUNu7ouIQaWapDaHS6fQGLBGYwm01miXOi16y04TR2Qj+Bxk6yOhhOZwWlyw6P2AMuO2ut3yhVodVK5Vi7xpJQaTS6IM6pHBgyh40mM1O8IJSxWa2xBmMAiQVgAbgx6Ex0P5LDY7A4WG4PFAAO7UTxDZwMZyKSBBXL+Iy42IC+YXdJQCmCXJUh5M5jPemQRnFT6o34kwFsvygv3-QE7XBcyGjXmw60IqTClEbbhcY269BBRxoKAoQUMADylAAVnCbRI4EhUMA7dguN92S06998MQcE3m1AG22Ox28BQPZUoDVXUwqmwADTtns2WV4Kz+EgWOUoCDjqASiQAWk3k1cVmcIIgnlAOdc1B0-igkTyR48oSSOdE0CPfk8UENDwgeGoWrXEUV1CoKO6DXkwt65O+TAgDcnivga6ByngU7fKwk4dqhTYYawBiZk46C5jacSIJQK7AKWCIVsgaAyN0VTslUUzyLW3yEI2HZdsxPZ9l0bxDh8o4TshEKzvOi7Lqu64mFuO5SHuzigeBqCQTBr4kIWRYQKa+B2LeegpNBjh4NBKAmlYFjQUMTA-iwh7HlYqBrswl5VDOcrzmO-iAc4VnoIo+7oIMJxVLg3Fxgs-EyGsVRThhKFcKsXBAA)

### 💻 Code

```ts
type Request = { l1: { l2: boolean } };
type Example<T> = { ex?: T | null };

// Definitions that reproduce the bug
type Schema<T> = (T extends boolean ? { type: 'boolean'; } : { props: { [P in keyof T]: Schema<T[P]> }; }) & Example<T>;
//type Schema<T> = (T extends boolean ? { type: 'boolean'; }  & Example<T> : { props: { [P in keyof T]: Schema<T[P]> }; } & Example<T>);
//type Schema<T> = Example<T> & (T extends boolean ? { type: 'boolean'; } : { props: { [P in keyof T]: Schema<T[P]> }; });

// Equivalent definition that works as expected
//type Schema<T> = (T extends boolean ? { type: 'boolean'; } & Example<T> : { props: Example<T> & { [P in keyof T]: Schema<T[P]> }; });

export const schemaObj: Schema<Request> = {
  props: {
    l1: {
      props: {
        l2: { type: 'boolean' },
        invalid: false, // <-- This property should generate the same error as below, but doesn't generate any errors at all
      },
    },
  },
}

const schemaSubset: Schema<Request>['props'] = {
  l1: {
    props: {
      l2: { type: 'boolean' },
      invalid: false, // <-- This generates an error: Object literal may only specify known properties, and 'invalid' does not exist in type '{ l2: Schema<boolean>; }'
    },
  }
};
```

### 🙁 Actual behavior

When creating an instance of `Schema<Request>` the nested homomorphic recursive type with intersection `Schema<Request>['props']['l1']['props']` allows any properties to be set on the object (as if it was intersectred with `Record<string, uknown>`).

### 🙂 Expected behavior

Only valid properties should be allowed on the object. Same way as they are if the property type is selected (`Schema<Request>['props']`), or intersecting type is used as a Left Hand operand.

When expanded `Schema<Request>` should be equivalent to the following type:
```ts
type SchemaManual = {
  props: {
    l1: {
      props: {
        l2: { type: 'boolean'; ex?: Request['l1']['l2'] | null };
      };
      ex?: Request['l1'] | null;
    }
  },
  ex?: Request | null;
};
```

### Work around

- If the intersection with `Example<T>` is removed, or used as a left hand side operand of the intersection directly with the homomorpic recursive type, it would allow only valid properties.
- Creating an instance of the property type `Schema<Request>['props']` and then assigning it to the original object would also work and would validate the properties correctly.

**Comment by andrewbranch** [comment]
Interestingly, the error re-appears if you add an excess property to the root of `schemaObj`, though the excess property itself is allowed.
