### ISSUE TITLE
Improve the error message: "error TS1210: Invalid use of 'arguments'. Class definitions are automatically in strict mode."

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/TypeScript#44765]
# Suggestion

I suggest a better error message telling that `arguments` is a reserved keyword or something that cannot be used in TS in strict mode.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I suggest a better error message telling that `arguments` is a reserved keyword or something and cannot be used as variable name.

## 📃 Motivating Example

I'm coming from languages that allow using words like "arguments" as a variable name.

I wrote a simple line of code: `let arguments = targetTask.arguments ?? {}` and got a confusing error: "Invalid use of 'arguments'. Modules are automatically in strict mode.ts(1215)". It would be less confusing if it told me what it thought the `arguments` is. E.g.  "Invalid use of reserved keyword 'arguments'" or "Invalid use of disabled builtin function 'arguments'" etc.

## 💻 Use Cases

P.S. Ideally I wish TS supported the name "arguments" for local variables.

**Comment by fatcerberus** [comment]
This is not a TS restriction, but a JS one.  `arguments` is a variable that is automatically in scope inside all functions, and in strict mode you're not allowed to shadow it.  Both classes and modules are, per the ECMAScript specification, automatically strict-mode code.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#making_eval_and_arguments_simpler

**Comment by Ark-kun** [comment]
Sure. I'm not blaming TS for the underlying issue. I only ask for the error message improvement.

**Comment by andrewbranch** [comment]
Example playground: https://www.typescriptlang.org/play?#code/MYGwhgzhAEDC0G8CwAoa0C2AKAlI166IApgC7RgBOA5gK4bEB2pEA3AdAL6rcpA

**Comment by DanielRosenwasser** [comment]
Maybe

```
Code contained in a class is evaluated in strict mode which does not allow uses of the '{0}' variable.
```

**Comment by fatcerberus** [comment]
On a related note I think any reference to "strict mode" might be confusing to beginners, since they might mistake it to mean the `strict` flag in tsconfig.  Especially anyone getting into TS with no prior exposure to JS.

**Comment by Ark-kun** [comment]
@DanielRosenwasser 
`strict mode which does not allow this use of '{0}'`

As a total beginner I wish you characterized/named '{0}'. When the error just says `does not allow this use of 'arguments'` I don't really know what `arguments` is. Is it the language feature? Does JS in strict mode not support [function] arguments? Is it the name of some feature? If it the name of some function? Is it a keyword?

Your previous wording called it variable: `which does not allow uses of the '{0}' variable`, which seems a bit better.

Maybe we can say something like 
`Code contained in a class is evaluated in JavaScript's strict mode which does not allow this use of the legacy built-in variable '{0}'. The name '{0}' is reserved in strict mode.
  For more information, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode.

**Comment by DanielRosenwasser** [comment]
Thanks @henriqueinonhe!
