### ISSUE TITLE
incorrect types with object destructurization

### ISSUE THREAD

**Issue by ariran5** [microsoft/TypeScript#44764]
I try use typescript in React + redux project and i want use action types. If i use in switch/case action fields with /without destructurization i see different variable types

latest typescript 4.3.x

bug in object destructurization syntax

```ts
/// obj = {a: 'my_string'}

// const {
//  a
//} = obj

// types a and obj.a not equal, see reducer and reducer2
```

[all example in playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAaghgGwK4QPIDMA8AVAfFAXimyggA9gIA7AEwGcoBvAbQGsIQAuKO4AJwCWVAOYBdbkPQQ+UAKoBfKAH453KhABu0gNwBYAFAGhlPujgBjaLLrSmBqFCpwAthG69BIgDT2ocYW6OSM4ARtI++g4A7hACwgAWwGrBYXwRDgCOMRBKyaHSBvIGBtTBUACC5sACAPZUAHIuEAyMvgDCABLl9QDiAKIA+uX9hFAA5J3d-UP9Y+lQk72D9eUAsn2jE11LAyvrc4XF+gD0x1ACzmA1fMBQAFR+DBbVdQzofDXO4wB0x8+1VDoYwM5let3+r1GrUiPAgwHKAQAFGA4CAEDU4DRuPBkGgsAAFATmViYazhcb+CBjXC4ACUdhhDj4cKQfCoDIcnKgoEg3EqLwaTTo30W02GGzgDFBgOA8y5KLRGJocqgRRh8nmNmAjVcyNR6Mx2MQKAwmEJxNJNjS4ycrmpdOhXOZwFZ7MdXO54EC-IBOuaIu20z2EqlYJVDgVBuVvgcatjh0M+h50B9dWwXoYRAASiy2enIJgcSasMmaug-FUAXQaUd0EgqJW6lBmTQkJY+IjeHBKNwydaIVQ+Y2qPnmrTe1aOVBpbwpw5kyrI0r5ooiAPfHQogJgOZ4ojk-T3Q5zJKU8O-cLRYNxdwY5zna65x7vi+u5Rw5zKdwl5i7-HGdOp4VOeQoBlMyxrH0t4AUyuZun+nIvt8b4QB+Di2oEP40AhcacjQEBmEgCBJFACEPmyPDAN2EC+GqaoGHWDYCs2ECtu2ABMnZUT2chWl4FYCkOAqjnQ468bY0IbluO57gO3wHk+J42MBAoXmBOw3qRMEsS6FFHs+r7cahCEOF+AkAt8WE4XeSlnqpoFXrskHQR6OmPvpXJIShaGOE03ByVZ2m4Q4+GEcRLkeuR7IobRhRAA)

**Comment by ariran5** [comment]
i think its normal, because i destruct before switch expression and in this moment payload type => number or string, but how i can use destructurization in this case?

maybe, is this not a bug but a feature request ?

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.
